FreeCAD: TechDrawGui::QGIFace Class Reference
TechDrawGui::QGIFace Class Reference
#include <QGIFace.h>
Public Types
enum { Type = QGraphicsItem::UserType + 104 }
enum fillMode {
NoFill, FromFile, SvgFill, BitmapFill,
GeomHatchFill, PlainFill
}
Public Types inherited from TechDrawGui::QGIPrimPath
enum { Type = QGraphicsItem::UserType + 170 }
Public Member Functions
QGIFace (int index=-1)
~QGIFace () override
int type () const override
QRectF boundingRect () const override
QPainterPath shape () const override
int getProjIndex () const
void draw ()
redraw this face
void setPrettyNormal () override
show the face style & colour in normal configuration
void setPrettyPre () override
show the face style & colour in pre-select configuration
void setPrettySel () override
show the face style & colour in selected configuration
void setDrawEdges (bool state)
show or hide the edges of this face. Usually just for debugging
virtual void setOutline (const QPainterPath &path)
update the outline of this face
void isHatched (bool state)
bool isHatched ()
void setFillMode (fillMode mode)
void setHatchColor (App::Color color)
void setHatchScale (double scale)
void setHatchFile (std::string fileSpec)
void loadSvgHatch (std::string fileSpec)
get the .svg file to use for hatching this face
void buildSvgHatch ()
make an array of svg tiles to cover this face
void hideSvg (bool state)
void clearSvg ()
void buildPixHatch ()
void setGeomHatchWeight (double weight)
void setLineWeight (double weight)
void clearLineSets ()
remove the PAT hatch lines
void addLineSet (TechDraw::LineSet &ls)
add PAT hatch line set
void clearFillItems ()
remove the children that make up a PAT fill
void lineSetToFillItems (TechDraw::LineSet &ls)
convert the PAT line set to QGraphicsPathItems
QGraphicsPathItem * geomToLine (TechDraw::BaseGeomPtr base, TechDraw::LineSet &ls)
QGraphicsPathItem * geomToStubbyLine (TechDraw::BaseGeomPtr base, double offset, TechDraw::LineSet &ls)
QGraphicsPathItem * lineFromPoints (Base::Vector3d start, Base::Vector3d end, TechDraw::DashSpec ds)
QPixmap textureFromBitmap (std::string fileSpec) const
void setHatchRotation (double degrees)
double getHatchRotation () const
void setHatchOffset (Base::Vector3d offset)
Base::Vector3d getHatchOffset ()
Public Member Functions inherited from TechDrawGui::QGIPrimPath
QGIPrimPath ()
~QGIPrimPath () override=default
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QPainterPath shape () const override
virtual void setWidth (double w)
virtual double getWidth ()
Qt::PenStyle getStyle ()
void setStyle (Qt::PenStyle s)
void setStyle (int s)
virtual void setNormalColor (QColor c)
virtual void setCapStyle (Qt::PenCapStyle c)
void setFillStyle (Qt::BrushStyle f)
Qt::BrushStyle getFillStyle ()
void setFill (QColor c, Qt::BrushStyle s)
void setFill (QBrush b)
void resetFill ()
void setFillColor (QColor c)
QColor getFillColor ()
void setFillOverride (bool b)
virtual void setCurrentPen ()
Public Attributes
std::string SVGCOLPREFIX = ""
Protected Member Functions
void makeMark (double x, double y)
debugging tool draws a mark at a position on this face
double getXForm ()
get zoom level (scale) from QGraphicsView
void getParameters ()
std::vector< double > offsetDash (const std::vector< double > dv, const double offset)
QPainterPath dashedPPath (const std::vector< double > dv, const Base::Vector3d start, const Base::Vector3d end)
double dashRemain (const std::vector< double > dv, const double offset)
double calcOffset (TechDraw::BaseGeomPtr geom, TechDraw::LineSet ls)
QPen setGeomPen ()
std::vector< double > decodeDashSpec (TechDraw::DashSpec dash)
bool multiselectEligible () override
bool exporting () const
Protected Member Functions inherited from TechDrawGui::QGIPrimPath
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual QColor getNormalColor ()
virtual QColor getPreColor ()
virtual QColor getSelectColor ()
Base::Reference< ParameterGrp > getParmGroup ()
virtual Qt::PenCapStyle prefCapStyle ()
Additional Inherited Members
Protected Attributes inherited from TechDrawGui::QGIPrimPath
bool isHighlighted
bool multiselectActivated
QPen m_pen
QColor m_colCurrent
QColor m_colNormal
bool m_colOverride
Qt::PenStyle m_styleCurrent
Qt::PenStyle m_styleNormal
double m_width
Qt::PenCapStyle m_capStyle
QBrush m_brush
Qt::BrushStyle m_fillStyleCurrent
QColor m_fillColorCurrent
QColor m_colDefFill
QColor m_colNormalFill
Qt::BrushStyle m_fillDef
Qt::BrushStyle m_fillNormal
Qt::BrushStyle m_fillSelect
bool m_fillOverride
Detailed Description
Definition at line 75 of file QGIFace.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 81 of file QGIFace.h.
fillMode
enum TechDrawGui::QGIFace::fillMode
Enumerator
NoFill
FromFile
SvgFill
BitmapFill
GeomHatchFill
PlainFill
Definition at line 87 of file QGIFace.h.
Constructor & Destructor Documentation
QGIFace()
QGIFace::QGIFace (int index = -1) explicit
Definition at line 58 of file QGIFace.cpp.
References TechDrawGui::ALPHAHIGH, TechDrawGui::ALPHALOW, App::Color::asValue(), TechDrawGui::COLWHITE, TechDrawGui::PreferencesGui::getAccessibleQColor(), getParameters(), isHatched(), TechDrawGui::QGIPrimPath::m_colDefFill, TechDrawGui::QGIPrimPath::m_fillDef, TechDrawGui::QGIPrimPath::m_fillSelect, TechDrawGui::QGIPrimPath::m_pen, TechDrawGui::QGIPrimPath::m_styleCurrent, NoFill, PlainFill, TechDrawGui::QGIPrimPath::setFill(), setFillMode(), setLineWeight(), and TechDrawGui::QGIPrimPath::setStyle().
~QGIFace()
QGIFace::~QGIFace () override
Definition at line 100 of file QGIFace.cpp.
Member Function Documentation
addLineSet()
void QGIFace::addLineSet (TechDraw::LineSet & ls)
add PAT hatch line set
Definition at line 244 of file QGIFace.cpp.
Referenced by TechDrawGui::QGIViewPart::drawAllFaces(), and TechDrawGui::QGIViewSection::drawSectionFace().
boundingRect()
QRectF QGIFace::boundingRect () const override
Definition at line 509 of file QGIFace.cpp.
References shape().
buildPixHatch()
void QGIFace::buildPixHatch ()
similar to svg hatch, but using pixmaps. we do this because QGraphicsSvgItems are not clipped when we export the scene to svg, but pixmaps are clipped.
Definition at line 362 of file QGIFace.cpp.
References TechDrawGui::QGCustomImage::centerAt(), Base::Console(), Base::ConsoleSingleton::Error(), TechDrawGui::QGCustomImage::load(), KDL::max(), Base::ConsoleSingleton::Message(), TechDrawGui::SVGCOLDEFAULT, SVGCOLPREFIX, TechDrawGui::SVGSIZEH, TechDrawGui::SVGSIZEW, and Base::ConsoleSingleton::Warning().
Referenced by draw().
buildSvgHatch()
void QGIFace::buildSvgHatch ()
make an array of svg tiles to cover this face
Definition at line 307 of file QGIFace.cpp.
References TechDrawGui::QGCustomRect::centerAt(), Base::Console(), getHatchOffset(), KDL::max(), Base::ConsoleSingleton::Message(), TechDrawGui::SVGCOLDEFAULT, SVGCOLPREFIX, TechDrawGui::SVGSIZEH, TechDrawGui::SVGSIZEW, Base::ConsoleSingleton::Warning(), MovieTool::x, and MovieTool::y.
Referenced by draw().
calcOffset()
double TechDrawGui::QGIFace::calcOffset (TechDraw::BaseGeomPtr geom, TechDraw::LineSet ls) protected
clearFillItems()
void QGIFace::clearFillItems ()
remove the children that make up a PAT fill
Definition at line 286 of file QGIFace.cpp.
Referenced by clearLineSets().
clearLineSets()
void QGIFace::clearLineSets ()
remove the PAT hatch lines
Definition at line 237 of file QGIFace.cpp.
References clearFillItems().
Referenced by TechDrawGui::QGIViewPart::drawAllFaces(), and TechDrawGui::QGIViewSection::drawSectionFace().
clearSvg()
void QGIFace::clearSvg ()
Definition at line 355 of file QGIFace.cpp.
References hideSvg().
dashedPPath()
QPainterPath TechDrawGui::QGIFace::dashedPPath (const std::vector< double > dv, const Base::Vector3d start, const Base::Vector3d end) protected
dashRemain()
double TechDrawGui::QGIFace::dashRemain (const std::vector< double > dv, const double offset) protected
decodeDashSpec()
std::vector<double> TechDrawGui::QGIFace::decodeDashSpec (TechDraw::DashSpec dash) protected
draw()
void QGIFace::draw ()
redraw this face
Definition at line 107 of file QGIFace.cpp.
References BitmapFill, buildPixHatch(), buildSvgHatch(), exporting(), GeomHatchFill, isHatched(), lineSetToFillItems(), loadSvgHatch(), TechDrawGui::QGIPrimPath::m_brush, TechDrawGui::QGIPrimPath::m_colNormalFill, TechDrawGui::QGIPrimPath::m_fillDef, TechDrawGui::QGIPrimPath::m_fillNormal, TechDrawGui::QGIPrimPath::m_fillStyleCurrent, PlainFill, TechDrawGui::QGIPrimPath::setFill(), bimcommands.BimViews::show(), SvgFill, and textureFromBitmap().
Referenced by TechDrawGui::QGIViewPart::drawAllFaces(), and TechDrawGui::QGIViewSection::drawSectionFace().
exporting()
bool QGIFace::exporting () const protected
Definition at line 519 of file QGIFace.cpp.
References TechDrawGui::QGSPage::getExportingSvg().
Referenced by draw().
geomToLine()
QGraphicsPathItem* TechDrawGui::QGIFace::geomToLine (TechDraw::BaseGeomPtr base, TechDraw::LineSet & ls)
geomToStubbyLine()
QGraphicsPathItem* TechDrawGui::QGIFace::geomToStubbyLine (TechDraw::BaseGeomPtr base, double offset, TechDraw::LineSet & ls)
getHatchOffset()
Base::Vector3d TechDrawGui::QGIFace::getHatchOffset () inline
Definition at line 144 of file QGIFace.h.
Referenced by buildSvgHatch().
getHatchRotation()
double TechDrawGui::QGIFace::getHatchRotation () const inline
Definition at line 141 of file QGIFace.h.
getParameters()
void QGIFace::getParameters () protected
Definition at line 503 of file QGIFace.cpp.
References TechDrawGui::MAXSEGMENT, and TechDrawGui::MAXTILES.
Referenced by QGIFace().
getProjIndex()
int TechDrawGui::QGIFace::getProjIndex () const inline
Definition at line 96 of file QGIFace.h.
Referenced by TechDrawGui::MDIViewPage::preSelectionChanged().
getXForm()
double QGIFace::getXForm () protected
get zoom level (scale) from QGraphicsView
Definition at line 270 of file QGIFace.cpp.
hideSvg()
void QGIFace::hideSvg (bool state)
turn svg tiles on or off. QtSvg does not handle clipping, so we must be able to turn the hatching on/off when exporting a face with an svg hatch. Otherwise the full tile pattern is shown in the export. NOTE: there appears to have been a change in Qt that it now clips svg items
Definition at line 471 of file QGIFace.cpp.
Referenced by clearSvg().
isHatched() [1/2]
bool TechDrawGui::QGIFace::isHatched () inline
Definition at line 107 of file QGIFace.h.
Referenced by draw(), QGIFace(), setFillMode(), and setPrettyNormal().
isHatched() [2/2]
void TechDrawGui::QGIFace::isHatched (bool state) inline
Definition at line 106 of file QGIFace.h.
Referenced by TechDrawGui::QGIViewPart::drawAllFaces(), and TechDrawGui::QGIViewSection::drawSectionFace().
lineFromPoints()
QGraphicsPathItem* TechDrawGui::QGIFace::lineFromPoints (Base::Vector3d start, Base::Vector3d end, TechDraw::DashSpec ds)
lineSetToFillItems()
void QGIFace::lineSetToFillItems (TechDraw::LineSet & ls)
convert the PAT line set to QGraphicsPathItems
Definition at line 250 of file QGIFace.cpp.
References TechDrawGui::Rez::guiX(), TechDrawGui::PATPathMaker::lineSetToFillItems(), setGeomPen(), TechDrawGui::PATPathMaker::setLineWidth(), TechDrawGui::PATPathMaker::setPen(), and TechDrawGui::PATPathMaker::setScale().
Referenced by draw().
loadSvgHatch()
void QGIFace::loadSvgHatch (std::string fileSpec)
get the .svg file to use for hatching this face
Definition at line 197 of file QGIFace.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), DrawingExample::file, RobotExample::pos, and SVGCOLPREFIX.
Referenced by draw().
makeMark()
void QGIFace::makeMark (double x, double y) protected
debugging tool draws a mark at a position on this face
Definition at line 296 of file QGIFace.cpp.
References TechDrawGui::QGICMark::setSize(), TechDrawGui::QGICMark::setThick(), ZVALUE::VERTEX, MovieTool::x, and MovieTool::y.
multiselectEligible()
bool TechDrawGui::QGIFace::multiselectEligible () inline override protected virtual
Reimplemented from TechDrawGui::QGIPrimPath.
Definition at line 161 of file QGIFace.h.
References TechDrawGui::SVGCOLDEFAULT.
offsetDash()
std::vector<double> TechDrawGui::QGIFace::offsetDash (const std::vector< double > dv, const double offset) protected
setDrawEdges()
void QGIFace::setDrawEdges (bool state)
show or hide the edges of this face. Usually just for debugging
Definition at line 182 of file QGIFace.cpp.
References TechDrawGui::QGIPrimPath::setStyle().
Referenced by TechDrawGui::QGIViewPart::drawAllFaces(), and TechDrawGui::QGIViewSection::drawSectionFace().
setFillMode()
void QGIFace::setFillMode (QGIFace::fillMode mode)
Definition at line 219 of file QGIFace.cpp.
References isHatched(), NoFill, and PlainFill.
Referenced by TechDrawGui::QGIViewPart::drawAllFaces(), TechDrawGui::QGIViewSection::drawSectionFace(), and QGIFace().
setGeomHatchWeight()
void TechDrawGui::QGIFace::setGeomHatchWeight (double weight) inline
Definition at line 125 of file QGIFace.h.
setGeomPen()
QPen QGIFace::setGeomPen () protected
Definition at line 258 of file QGIFace.cpp.
References TechDrawGui::Rez::guiX(), and result.
Referenced by lineSetToFillItems().
setHatchColor()
void QGIFace::setHatchColor (App::Color color)
Definition at line 456 of file QGIFace.cpp.
References App::Color::asHexString(), and App::Color::asValue().
Referenced by TechDrawGui::QGIViewPart::drawAllFaces(), and TechDrawGui::QGIViewSection::drawSectionFace().
setHatchFile()
void QGIFace::setHatchFile (std::string fileSpec)
Definition at line 191 of file QGIFace.cpp.
Referenced by TechDrawGui::QGIViewPart::drawAllFaces(), and TechDrawGui::QGIViewSection::drawSectionFace().
setHatchOffset()
void TechDrawGui::QGIFace::setHatchOffset (Base::Vector3d offset) inline
Definition at line 143 of file QGIFace.h.
Referenced by TechDrawGui::QGIViewPart::drawAllFaces(), and TechDrawGui::QGIViewSection::drawSectionFace().
setHatchRotation()
void TechDrawGui::QGIFace::setHatchRotation (double degrees) inline
Definition at line 140 of file QGIFace.h.
Referenced by TechDrawGui::QGIViewPart::drawAllFaces(), and TechDrawGui::QGIViewSection::drawSectionFace().
setHatchScale()
void QGIFace::setHatchScale (double scale)
Definition at line 462 of file QGIFace.cpp.
References draftfunctions.scale::scale().
Referenced by TechDrawGui::QGIViewPart::drawAllFaces(), and TechDrawGui::QGIViewSection::drawSectionFace().
setLineWeight()
void QGIFace::setLineWeight (double weight)
Definition at line 499 of file QGIFace.cpp.
Referenced by TechDrawGui::QGIViewPart::drawAllFaces(), TechDrawGui::QGIViewSection::drawSectionFace(), and QGIFace().
setOutline()
void QGIFace::setOutline (const QPainterPath & path) virtual
update the outline of this face
Definition at line 231 of file QGIFace.cpp.
Referenced by TechDrawGui::QGIViewPart::drawFace().
setPrettyNormal()
void QGIFace::setPrettyNormal () override virtual
show the face style & colour in normal configuration
Reimplemented from TechDrawGui::QGIPrimPath.
Definition at line 153 of file QGIFace.cpp.
References BitmapFill, isHatched(), TechDrawGui::QGIPrimPath::m_brush, TechDrawGui::QGIPrimPath::m_fillStyleCurrent, and TechDrawGui::QGIPrimPath::setPrettyNormal().
Referenced by TechDrawGui::QGIViewPart::drawAllFaces(), and TechDrawGui::QGIViewSection::drawSectionFace().
setPrettyPre()
void QGIFace::setPrettyPre () override virtual
show the face style & colour in pre-select configuration
Reimplemented from TechDrawGui::QGIPrimPath.
Definition at line 166 of file QGIFace.cpp.
References TechDrawGui::QGIPrimPath::m_brush, TechDrawGui::QGIPrimPath::m_fillStyleCurrent, and TechDrawGui::QGIPrimPath::setPrettyPre().
setPrettySel()
void QGIFace::setPrettySel () override virtual
show the face style & colour in selected configuration
Reimplemented from TechDrawGui::QGIPrimPath.
Definition at line 174 of file QGIFace.cpp.
References TechDrawGui::QGIPrimPath::m_brush, TechDrawGui::QGIPrimPath::m_fillStyleCurrent, and TechDrawGui::QGIPrimPath::setPrettySel().
shape()
QPainterPath QGIFace::shape () const override
Definition at line 514 of file QGIFace.cpp.
Referenced by boundingRect().
textureFromBitmap()
QPixmap QGIFace::textureFromBitmap (std::string fileSpec) const
create a QPixmap from a bitmap file. The QPixmap will be used as a QBrush texture.
Definition at line 479 of file QGIFace.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), and DrawingExample::file.
Referenced by draw().
type()
int TechDrawGui::QGIFace::type () const inline override
Definition at line 82 of file QGIFace.h.
Member Data Documentation
SVGCOLPREFIX
std::string TechDrawGui::QGIFace::SVGCOLPREFIX = ""
Definition at line 95 of file QGIFace.h.
Referenced by buildPixHatch(), buildSvgHatch(), and loadSvgHatch().
The documentation for this class was generated from the following files:
QGIFace.h
QGIFace.cpp