FreeCAD: SpreadsheetGui::SheetModel Class Reference
SpreadsheetGui::SheetModel Class Reference
#include <SheetModel.h>
Public Member Functions
SheetModel (Spreadsheet::Sheet *_sheet, QObject *parent=nullptr)
~SheetModel () override
SheetModel (QObject *parent)
int rowCount (const QModelIndex &parent=QModelIndex()) const override
int columnCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
QVariant headerData (int section, Qt::Orientation orientation, int role) const override
bool setData (const QModelIndex &index, const QVariant &value, int role) override
Qt::ItemFlags flags (const QModelIndex &) const override
Detailed Description
Definition at line 39 of file SheetModel.h.
Constructor & Destructor Documentation
SheetModel() [1/2]
SheetModel::SheetModel (Spreadsheet::Sheet * _sheet, QObject * parent = nullptr) explicit
Definition at line 46 of file SheetModel.cpp.
References draftgeoutils.faces::bind(), Spreadsheet::Sheet::cellUpdated, App::GetApplication(), ParameterGrp::GetASCII(), App::Application::GetParameterGroupByPath(), and Spreadsheet::Sheet::rangeUpdated.
~SheetModel()
SheetModel::~SheetModel () override
Definition at line 68 of file SheetModel.cpp.
SheetModel() [2/2]
SpreadsheetGui::SheetModel::SheetModel (QObject * parent) explicit
Member Function Documentation
columnCount()
int SheetModel::columnCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 80 of file SheetModel.cpp.
References Init::parent.
data()
QVariant SheetModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 106 of file SheetModel.cpp.
References App::Color::a, App::Color::b, Spreadsheet::Sheet::dependsOn(), SCL.SimpleDataTypes::e, SCL.SimpleDataTypes::f, App::Color::g, Spreadsheet::Cell::getAlias(), Spreadsheet::Cell::getAlignment(), Spreadsheet::Cell::getBackground(), Spreadsheet::Sheet::getCell(), Spreadsheet::Sheet::getCells(), Base::Persistence::getClassTypeId(), Base::UnitsApi::getDecimals(), Spreadsheet::PropertySheet::getDirty(), Spreadsheet::Cell::getDisplayUnit(), Spreadsheet::Cell::getException(), Spreadsheet::Cell::getExpression(), Spreadsheet::Cell::getForeground(), Spreadsheet::Sheet::getPropertyByName(), App::PropertyQuantity::getQuantityValue(), Spreadsheet::Cell::getStringContent(), Spreadsheet::Cell::getStyle(), App::PropertyQuantity::getUnit(), Base::Quantity::getUserString(), App::PropertyQuantity::getValue(), getValue(), App::PropertyString::getValue(), Spreadsheet::Cell::hasException(), SplineSurface::i, Base::BaseClass::isDerivedFrom(), Base::Unit::isEmpty(), RobotExample::l, Spreadsheet::Sheet::providesTo(), App::Color::r, Spreadsheet::DisplayUnit::scaler, Path.Post.scripts.refactored_centroid_post::str, Spreadsheet::DisplayUnit::stringRep, App::CellAddress::toString(), create_qrc::txt, Spreadsheet::DisplayUnit::unit, and TestSpreadsheet::v.
flags()
Qt::ItemFlags SheetModel::flags (const QModelIndex &) const override
Definition at line 590 of file SheetModel.cpp.
headerData()
QVariant SheetModel::headerData (int section, Qt::Orientation orientation, int role) const override
Definition at line 512 of file SheetModel.cpp.
References Spreadsheet::Sheet::getColumnWidth(), Spreadsheet::Sheet::getRowHeight(), Sketcher::Horizontal, and App::ExpressionParser::labels.
rowCount()
int SheetModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 74 of file SheetModel.cpp.
References Init::parent.
setData()
bool SheetModel::setData (const QModelIndex & index, const QVariant & value, int role) override
Definition at line 561 of file SheetModel.cpp.
References Spreadsheet::Sheet::getCell(), Spreadsheet::Cell::getStringContent(), and Path.Post.scripts.refactored_centroid_post::str.
The documentation for this class was generated from the following files:
SheetModel.h
SheetModel.cpp