FreeCAD: Gui::SoSVGVectorOutput Class Reference
Gui::SoSVGVectorOutput Class Reference
#include <SoFCVectorizeSVGAction.h>
Public Member Functions
SoSVGVectorOutput ()
~SoSVGVectorOutput () override
SbBool openFile (const char *filename) override
void closeFile () override
std::fstream & getFileStream ()
Detailed Description
Definition at line 55 of file SoFCVectorizeSVGAction.h.
Constructor & Destructor Documentation
SoSVGVectorOutput()
SoSVGVectorOutput::SoSVGVectorOutput () default
~SoSVGVectorOutput()
SoSVGVectorOutput::~SoSVGVectorOutput () override
Definition at line 142 of file SoFCVectorizeSVGAction.cpp.
References closeFile().
Member Function Documentation
closeFile()
void SoSVGVectorOutput::closeFile () override
Definition at line 159 of file SoFCVectorizeSVGAction.cpp.
Referenced by ~SoSVGVectorOutput().
getFileStream()
std::fstream & SoSVGVectorOutput::getFileStream ()
Definition at line 165 of file SoFCVectorizeSVGAction.cpp.
Referenced by Gui::SoFCVectorizeSVGAction::printBackground(), Gui::SoFCVectorizeSVGAction::printFooter(), Gui::SoFCVectorizeSVGAction::printHeader(), Gui::SoFCVectorizeSVGActionP::printLine(), Gui::SoFCVectorizeSVGActionP::printText(), and Gui::SoFCVectorizeSVGActionP::printTriangle().
openFile()
SbBool SoSVGVectorOutput::openFile (const char * filename) override
Definition at line 147 of file SoFCVectorizeSVGAction.cpp.
References Base::FileInfo::filePath(), and Base::FileInfo::toStdWString().
The documentation for this class was generated from the following files:
SoFCVectorizeSVGAction.h
SoFCVectorizeSVGAction.cpp