FreeCAD: Gui::ViewProviderFeaturePythonT< ViewProviderT > Class Template Reference
Gui::ViewProviderFeaturePythonT< ViewProviderT > Class Template Reference
#include <ViewProviderFeaturePython.h>
Public Member Functions
ViewProviderFeaturePythonT ()
constructor.
~ViewProviderFeaturePythonT () override
destructor.
QIcon getIcon () const override
std::vector< App::DocumentObject * > claimChildren () const override
Nodes
SoSeparator * getRoot () const override
SoSeparator * getFrontRoot () const override
SoSeparator * getBackRoot () const override
Selection handling
bool useNewSelectionModel () const override
bool getElementPicked (const SoPickedPoint *pp, std::string &subname) const override
std::string getElement (const SoDetail *det) const override
SoDetail * getDetail (const char *name) const override
bool getDetailPath (const char *name, SoFullPath *path, bool append, SoDetail *&det) const override
std::vector< Base::Vector3d > getSelectionShape (const char *Element) const override
Update data methods
void attach (App::DocumentObject *obj) override
void updateData (const App::Property *prop) override
void getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &c) const override
bool onDelete (const std::vector< std::string > &sub) override
bool canDelete (App::DocumentObject *obj) const override
Restoring view provider from document load
void startRestoring () override
void finishRestoring () override
Drag and drop
bool canDragObjects () const override
Returns true if the view provider generally supports dragging objects.
bool canDragObject (App::DocumentObject *obj) const override
Check whether the object can be removed from the view provider by drag and drop.
void dragObject (App::DocumentObject *obj) override
Starts to drag the object.
bool canDropObjects () const override
Returns true if the view provider generally accepts dropping of objects.
bool canDropObject (App::DocumentObject *obj) const override
Check whether the object can be dropped to the view provider by drag and drop.
void dropObject (App::DocumentObject *obj) override
If the dropped object type is accepted the object will be added as child.
bool canDragAndDropObject (App::DocumentObject *obj) const override
bool canDropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements) const override
std::string dropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements) override
Public Member Functions inherited from Gui::ViewProviderT
ViewProviderT ()
ViewProviderT (const ViewProviderT &)
ViewProviderT (ViewProviderT &&)
ViewProviderT (const ViewProviderDocumentObject *)
~ViewProviderT ()
ViewProviderT & operator= (const ViewProviderT &)
ViewProviderT & operator= (ViewProviderT &&)
void operator= (const ViewProviderDocumentObject *)
bool operator== (const ViewProviderT &) const
Document * getDocument () const
const std::string & getDocumentName () const
std::string getGuiDocumentPython () const
std::string getAppDocumentPython () const
ViewProviderDocumentObject * getViewProvider () const
const std::string & getObjectName () const
std::string getObjectPython () const
template<typename T >
T * getObjectAs () const
Display methods
bool isShow () const override
Returns true if the icon must always appear enabled in the tree view.
const char * getDefaultDisplayMode () const override
get the default display mode
std::vector< std::string > getDisplayModes () const override
returns a list of all possible modes
void setDisplayMode (const char *ModeName) override
set the display mode
bool canRemoveChildrenFromRoot () const override
PyObject * getPyObject () override
bool canAddToSceneGraph () const override
void setupContextMenu (QMenu *menu, QObject *recipient, const char *member) override
ViewProviderFeaturePythonT (const ViewProviderFeaturePythonT &)=delete
ViewProviderFeaturePythonT (ViewProviderFeaturePythonT &&)=delete
ViewProviderFeaturePythonT & operator= (const ViewProviderFeaturePythonT &)=delete
ViewProviderFeaturePythonT & operator= (ViewProviderFeaturePythonT &&)=delete
void onChanged (const App::Property *prop) override
void onBeforeChange (const App::Property *prop) override
bool setEdit (int ModNum) override
is called by the document when the provider goes in edit mode
void unsetEdit (int ModNum) override
is called when you lose the edit mode
void setEditViewer (View3DInventorViewer *viewer, int ModNum) override
void unsetEditViewer (View3DInventorViewer *viewer) override
std::string getDropPrefix () const override
int replaceObject (App::DocumentObject *oldObj, App::DocumentObject *newObj) override
ViewProviderDocumentObject * getLinkedViewProvider (std::string *subname=nullptr, bool recursive=false) const override
void editProperty (const char *propName) override
bool doubleClicked () override
void setOverrideMode (const std::string &mode) override
Detailed Description
template<class ViewProviderT>
class Gui::ViewProviderFeaturePythonT< ViewProviderT >
Definition at line 198 of file ViewProviderFeaturePython.h.
Constructor & Destructor Documentation
ViewProviderFeaturePythonT() [1/3]
template<class ViewProviderT > Gui::ViewProviderFeaturePythonT< ViewProviderT >::ViewProviderFeaturePythonT () inline
constructor.
Definition at line 204 of file ViewProviderFeaturePython.h.
References ADD_PROPERTY.
~ViewProviderFeaturePythonT()
template<class ViewProviderT > Gui::ViewProviderFeaturePythonT< ViewProviderT >::~ViewProviderFeaturePythonT () inline override
destructor.
Definition at line 209 of file ViewProviderFeaturePython.h.
ViewProviderFeaturePythonT() [2/3]
template<class ViewProviderT > Gui::ViewProviderFeaturePythonT< ViewProviderT >::ViewProviderFeaturePythonT (const ViewProviderFeaturePythonT< ViewProviderT > &) delete
ViewProviderFeaturePythonT() [3/3]
template<class ViewProviderT > Gui::ViewProviderFeaturePythonT< ViewProviderT >::ViewProviderFeaturePythonT (ViewProviderFeaturePythonT< ViewProviderT > &&) delete
Member Function Documentation
attach()
template<class ViewProviderT > void Gui::ViewProviderFeaturePythonT< ViewProviderT >::attach (App::DocumentObject * obj) inline override
Definition at line 289 of file ViewProviderFeaturePython.h.
Referenced by Path.Dressup.Gui.Boundary.DressupPathBoundaryViewProvider::__init__().
canAddToSceneGraph()
template<class ViewProviderT > bool Gui::ViewProviderFeaturePythonT< ViewProviderT >::canAddToSceneGraph () const inline override
Definition at line 488 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::Accepted, Gui::ViewProviderFeaturePythonImp::canAddToSceneGraph(), and Gui::ViewProviderFeaturePythonImp::Rejected.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::onChanged().
canDelete()
template<class ViewProviderT > bool Gui::ViewProviderFeaturePythonT< ViewProviderT >::canDelete (App::DocumentObject * obj) const inline override
Definition at line 311 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::Accepted, Gui::ViewProviderFeaturePythonImp::canDelete(), and Gui::ViewProviderFeaturePythonImp::Rejected.
canDragAndDropObject()
template<class ViewProviderT > bool Gui::ViewProviderFeaturePythonT< ViewProviderT >::canDragAndDropObject (App::DocumentObject * obj) const inline override
Return false to force drop only operation for a give object
Definition at line 404 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::Accepted, Gui::ViewProviderFeaturePythonImp::canDragAndDropObject(), and Gui::ViewProviderFeaturePythonImp::Rejected.
canDragObject()
template<class ViewProviderT > bool Gui::ViewProviderFeaturePythonT< ViewProviderT >::canDragObject (App::DocumentObject * obj) const inline override
Check whether the object can be removed from the view provider by drag and drop.
Definition at line 349 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::Accepted, Gui::ViewProviderFeaturePythonImp::canDragObject(), and Gui::ViewProviderFeaturePythonImp::Rejected.
Referenced by draftviewproviders.view_layer.ViewProviderLayer::canDropObject().
canDragObjects()
template<class ViewProviderT > bool Gui::ViewProviderFeaturePythonT< ViewProviderT >::canDragObjects () const inline override
Returns true if the view provider generally supports dragging objects.
Definition at line 338 of file ViewProviderFeaturePython.h.
canDropObject()
template<class ViewProviderT > bool Gui::ViewProviderFeaturePythonT< ViewProviderT >::canDropObject (App::DocumentObject * obj) const inline override
Check whether the object can be dropped to the view provider by drag and drop.
Definition at line 382 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::Accepted, Gui::ViewProviderFeaturePythonImp::canDropObject(), and Gui::ViewProviderFeaturePythonImp::Rejected.
canDropObjectEx()
template<class ViewProviderT > bool Gui::ViewProviderFeaturePythonT< ViewProviderT >::canDropObjectEx (App::DocumentObject * obj, App::DocumentObject * owner, const char * subname, const std::vector< std::string > & elements) const inline override
Definition at line 414 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::Accepted, Gui::ViewProviderFeaturePythonImp::canDropObjectEx(), and Gui::ViewProviderFeaturePythonImp::Rejected.
canDropObjects()
template<class ViewProviderT > bool Gui::ViewProviderFeaturePythonT< ViewProviderT >::canDropObjects () const inline override
Returns true if the view provider generally accepts dropping of objects.
Definition at line 371 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::Accepted, Gui::ViewProviderFeaturePythonImp::canDropObjects(), and Gui::ViewProviderFeaturePythonImp::Rejected.
canRemoveChildrenFromRoot()
template<class ViewProviderT > bool Gui::ViewProviderFeaturePythonT< ViewProviderT >::canRemoveChildrenFromRoot () const inline override
Definition at line 473 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::Accepted, Gui::ViewProviderFeaturePythonImp::canRemoveChildrenFromRoot(), and Gui::ViewProviderFeaturePythonImp::NotImplemented.
claimChildren()
template<class ViewProviderT > std::vector<App::DocumentObject*> Gui::ViewProviderFeaturePythonT< ViewProviderT >::claimChildren () const inline override
Definition at line 223 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::claimChildren().
Referenced by femviewprovider.view_result_mechanical.VPResultMechanical::onDelete(), BOPTools.SplitFeatures.ViewProviderBooleanFragments::onDelete(), BOPTools.JoinFeatures.ViewProviderConnect::onDelete(), BOPTools.ToleranceFeatures.ViewProviderToleranceSet::onDelete(), femviewprovider.view_mesh_gmsh.VPMeshGmsh::onDelete(), CommandCreateView.ViewProviderExplodedView::onDelete(), CommandCreateSimulation.ViewProviderSimulation::onDelete(), BOPTools.SplitFeatures.ViewProviderSlice::onDelete(), and BOPTools.SplitFeatures.ViewProviderXOR::onDelete().
doubleClicked()
template<class ViewProviderT > bool Gui::ViewProviderFeaturePythonT< ViewProviderT >::doubleClicked () inline override protected
Definition at line 600 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::Accepted, Gui::ViewProviderFeaturePythonImp::doubleClicked(), and Gui::ViewProviderFeaturePythonImp::Rejected.
dragObject()
template<class ViewProviderT > void Gui::ViewProviderFeaturePythonT< ViewProviderT >::dragObject (App::DocumentObject * obj) inline override
Starts to drag the object.
Definition at line 360 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::Accepted, Gui::ViewProviderFeaturePythonImp::dragObject(), and Gui::ViewProviderFeaturePythonImp::Rejected.
dropObject()
template<class ViewProviderT > void Gui::ViewProviderFeaturePythonT< ViewProviderT >::dropObject (App::DocumentObject * obj) inline override
If the dropped object type is accepted the object will be added as child.
Definition at line 393 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::Accepted, Gui::ViewProviderFeaturePythonImp::dropObject(), and Gui::ViewProviderFeaturePythonImp::Rejected.
dropObjectEx()
template<class ViewProviderT > std::string Gui::ViewProviderFeaturePythonT< ViewProviderT >::dropObjectEx (App::DocumentObject * obj, App::DocumentObject * owner, const char * subname, const std::vector< std::string > & elements) inline override
Add an object with full qualified name to the view provider by drag and drop
Definition at line 427 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::dropObjectEx().
editProperty()
template<class ViewProviderT > void Gui::ViewProviderFeaturePythonT< ViewProviderT >::editProperty (const char * propName) inline override protected
Definition at line 587 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::editProperty().
finishRestoring()
template<class ViewProviderT > void Gui::ViewProviderFeaturePythonT< ViewProviderT >::finishRestoring () inline override
Definition at line 329 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::finishRestoring().
getBackRoot()
template<class ViewProviderT > SoSeparator* Gui::ViewProviderFeaturePythonT< ViewProviderT >::getBackRoot () const inline override
Definition at line 239 of file ViewProviderFeaturePython.h.
getDefaultDisplayMode()
template<class ViewProviderT > const char* Gui::ViewProviderFeaturePythonT< ViewProviderT >::getDefaultDisplayMode () const inline override
get the default display mode
Definition at line 452 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::getDefaultDisplayMode().
getDetail()
template<class ViewProviderT > SoDetail* Gui::ViewProviderFeaturePythonT< ViewProviderT >::getDetail (const char * name) const inline override
Definition at line 270 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::getDetail().
getDetailPath()
template<class ViewProviderT > bool Gui::ViewProviderFeaturePythonT< ViewProviderT >::getDetailPath (const char * name, SoFullPath * path, bool append, SoDetail *& det) const inline override
Definition at line 276 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::Accepted, Path.Post.scripts.uccnc_post::append(), Gui::ViewProviderFeaturePythonImp::getDetailPath(), and Gui::ViewProviderFeaturePythonImp::NotImplemented.
getDisplayModes()
template<class ViewProviderT > std::vector<std::string> Gui::ViewProviderFeaturePythonT< ViewProviderT >::getDisplayModes () const inline override
returns a list of all possible modes
Definition at line 459 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::getDisplayModes(), and modes.
getDropPrefix()
template<class ViewProviderT > std::string Gui::ViewProviderFeaturePythonT< ViewProviderT >::getDropPrefix () const inline override protected
Definition at line 560 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::getDropPrefix().
getElement()
template<class ViewProviderT > std::string Gui::ViewProviderFeaturePythonT< ViewProviderT >::getElement (const SoDetail * det) const inline override
Definition at line 264 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::getElement().
getElementPicked()
template<class ViewProviderT > bool Gui::ViewProviderFeaturePythonT< ViewProviderT >::getElementPicked (const SoPickedPoint * pp, std::string & subname) const inline override
Definition at line 256 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::Accepted, Gui::ViewProviderFeaturePythonImp::getElementPicked(), and Gui::ViewProviderFeaturePythonImp::NotImplemented.
getFrontRoot()
template<class ViewProviderT > SoSeparator* Gui::ViewProviderFeaturePythonT< ViewProviderT >::getFrontRoot () const inline override
Definition at line 235 of file ViewProviderFeaturePython.h.
getIcon()
template<class ViewProviderT > QIcon Gui::ViewProviderFeaturePythonT< ViewProviderT >::getIcon () const inline override
Definition at line 214 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::getIcon(), and bimcommands.BimIfcElements::getIcon().
Referenced by ArchAxisSystem.AxisSystemTaskPanel::update(), ArchWindow._ArchWindowTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), bimcommands.BimClassification.BIM_Classification::updateByMaterial(), bimcommands.BimClassification.BIM_Classification::updateByTree(), bimcommands.BimClassification.BIM_Classification::updateByType(), and bimcommands.BimClassification.BIM_Classification::updateDefault().
getLinkedViewProvider()
template<class ViewProviderT > ViewProviderDocumentObject* Gui::ViewProviderFeaturePythonT< ViewProviderT >::getLinkedViewProvider (std::string * subname = nullptr, bool recursive = false) const inline override protected
Definition at line 579 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::getLinkedViewProvider().
getPyObject()
template<class ViewProviderT > PyObject* Gui::ViewProviderFeaturePythonT< ViewProviderT >::getPyObject () inline override
Definition at line 484 of file ViewProviderFeaturePython.h.
getRoot()
template<class ViewProviderT > SoSeparator* Gui::ViewProviderFeaturePythonT< ViewProviderT >::getRoot () const inline override
Definition at line 232 of file ViewProviderFeaturePython.h.
getSelectionShape()
template<class ViewProviderT > std::vector<Base::Vector3d> Gui::ViewProviderFeaturePythonT< ViewProviderT >::getSelectionShape (const char * Element) const inline override
Definition at line 282 of file ViewProviderFeaturePython.h.
getTaskViewContent()
template<class ViewProviderT > void Gui::ViewProviderFeaturePythonT< ViewProviderT >::getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > & c) const inline override
Definition at line 298 of file ViewProviderFeaturePython.h.
References SCL.SimpleDataTypes::c.
isShow()
template<class ViewProviderT > bool Gui::ViewProviderFeaturePythonT< ViewProviderT >::isShow () const inline override
Returns true if the icon must always appear enabled in the tree view.
Definition at line 441 of file ViewProviderFeaturePython.h.
onBeforeChange()
template<class ViewProviderT > void Gui::ViewProviderFeaturePythonT< ViewProviderT >::onBeforeChange (const App::Property * prop) inline override protected
Definition at line 523 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::onBeforeChange().
onChanged()
template<class ViewProviderT > void Gui::ViewProviderFeaturePythonT< ViewProviderT >::onChanged (const App::Property * prop) inline override protected
Definition at line 500 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::attach(), Gui::ViewProviderFeaturePythonT< ViewProviderT >::canAddToSceneGraph(), Gui::ViewProviderT::getDocument(), App::PropertyPythonObject::getValue(), Gui::ViewProviderFeaturePythonImp::init(), Gui::isRestoring, Gui::ViewProviderFeaturePythonImp::onChanged(), and Gui::Document::toggleInSceneGraph().
Referenced by draftviewproviders.view_base.ViewProviderDraft::attach(), ArchSpace._ViewProviderSpace::onChanged(), ArchSchedule._ArchSchedule::setProperties(), draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), ArchAxis._ViewProviderAxis::updateData(), draftviewproviders.view_dimension.ViewProviderLinearDimension::updateData(), ArchSpace._ViewProviderSpace::updateData(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchSite._ViewProviderSite::updateData(), ArchSectionPlane._ViewProviderSectionPlane::updateData(), and ArchPanel.ViewProviderPanelSheet::updateData().
onDelete()
template<class ViewProviderT > bool Gui::ViewProviderFeaturePythonT< ViewProviderT >::onDelete (const std::vector< std::string > & sub) inline override
Definition at line 301 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::Accepted, Gui::ViewProviderFeaturePythonImp::onDelete(), and Gui::ViewProviderFeaturePythonImp::Rejected.
operator=() [1/2]
template<class ViewProviderT > ViewProviderFeaturePythonT& Gui::ViewProviderFeaturePythonT< ViewProviderT >::operator= (const ViewProviderFeaturePythonT< ViewProviderT > &) delete
operator=() [2/2]
template<class ViewProviderT > ViewProviderFeaturePythonT& Gui::ViewProviderFeaturePythonT< ViewProviderT >::operator= (ViewProviderFeaturePythonT< ViewProviderT > &&) delete
replaceObject()
template<class ViewProviderT > int Gui::ViewProviderFeaturePythonT< ViewProviderT >::replaceObject (App::DocumentObject * oldObj, App::DocumentObject * newObj) inline override protected
Definition at line 567 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::Accepted, Gui::ViewProviderFeaturePythonImp::Rejected, and Gui::ViewProviderFeaturePythonImp::replaceObject().
setDisplayMode()
template<class ViewProviderT > void Gui::ViewProviderFeaturePythonT< ViewProviderT >::setDisplayMode (const char * ModeName) inline override
set the display mode
Definition at line 466 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::setDisplayMode().
setEdit()
template<class ViewProviderT > bool Gui::ViewProviderFeaturePythonT< ViewProviderT >::setEdit (int ModNum) inline override protected
is called by the document when the provider goes in edit mode
Definition at line 529 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::Accepted, Gui::ViewProviderFeaturePythonImp::Rejected, Gui::ViewProviderFeaturePythonImp::setEdit(), and PartDesignGui::setEdit().
Referenced by Path.Base.Gui.PropertyBag.ViewProvider::doubleClicked(), Path.Base.Gui.SetupSheet.ViewProvider::doubleClicked(), Path.Tool.Gui.Bit.ViewProvider::doubleClicked(), Path.Base.Gui.IconViewProvider.ViewProvider::setupContextMenu(), Path.Tool.Gui.Controller.ViewProvider::setupContextMenu(), Path.Op.Gui.Base.ViewProvider::setupContextMenu(), and Path.Main.Gui.Job.ViewProvider::setupContextMenu().
setEditViewer()
template<class ViewProviderT > void Gui::ViewProviderFeaturePythonT< ViewProviderT >::setEditViewer (View3DInventorViewer * viewer, int ModNum) inline override protected
Definition at line 551 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::NotImplemented, Gui::ViewProviderFeaturePythonImp::setEditViewer(), and OfflineRenderingUtils::viewer().
setOverrideMode()
template<class ViewProviderT > void Gui::ViewProviderFeaturePythonT< ViewProviderT >::setOverrideMode (const std::string & mode) inline override protected
Definition at line 612 of file ViewProviderFeaturePython.h.
setupContextMenu()
template<class ViewProviderT > void Gui::ViewProviderFeaturePythonT< ViewProviderT >::setupContextMenu (QMenu * menu, QObject * recipient, const char * member) inline override
Definition at line 593 of file ViewProviderFeaturePython.h.
References NavigationIndicatorGui::menu, and Gui::ViewProviderFeaturePythonImp::setupContextMenu().
startRestoring()
template<class ViewProviderT > void Gui::ViewProviderFeaturePythonT< ViewProviderT >::startRestoring () inline override
Definition at line 325 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::startRestoring().
unsetEdit()
template<class ViewProviderT > void Gui::ViewProviderFeaturePythonT< ViewProviderT >::unsetEdit (int ModNum) inline override protected
is called when you lose the edit mode
Definition at line 541 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::Accepted, Gui::ViewProviderFeaturePythonImp::Rejected, and Gui::ViewProviderFeaturePythonImp::unsetEdit().
Referenced by Path.Main.Gui.Job.ViewProvider::uneditObject().
unsetEditViewer()
template<class ViewProviderT > void Gui::ViewProviderFeaturePythonT< ViewProviderT >::unsetEditViewer (View3DInventorViewer * viewer) inline override protected
Definition at line 555 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::NotImplemented, Gui::ViewProviderFeaturePythonImp::unsetEditViewer(), and OfflineRenderingUtils::viewer().
updateData()
template<class ViewProviderT > void Gui::ViewProviderFeaturePythonT< ViewProviderT >::updateData (const App::Property * prop) inline override
Definition at line 294 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::updateData().
Referenced by Path.Main.Gui.JobDlg.JobCreate::exec_(), draftviewproviders.view_wire.ViewProviderWire::onChanged(), draftviewproviders.view_dimension.ViewProviderLinearDimension::onChanged(), draftviewproviders.view_dimension.ViewProviderAngularDimension::onChanged(), Path.Op.Gui.Base.TaskPanelPage::pageUpdateData(), Path.Base.Gui.SetupSheet.OpTaskPanel::setupUi(), and Path.Base.Gui.PropertyBag.TaskPanel::setupUi().
useNewSelectionModel()
template<class ViewProviderT > bool Gui::ViewProviderFeaturePythonT< ViewProviderT >::useNewSelectionModel () const inline override
Definition at line 246 of file ViewProviderFeaturePython.h.
References Gui::ViewProviderFeaturePythonImp::Accepted, Gui::ViewProviderFeaturePythonImp::Rejected, and Gui::ViewProviderFeaturePythonImp::useNewSelectionModel().
The documentation for this class was generated from the following file:
ViewProviderFeaturePython.h