FreeCAD: Gui::ConsoleHistory Class Reference
Gui::ConsoleHistory Class Reference
#include <PythonConsole.h>
Public Member Functions
ConsoleHistory ()
~ConsoleHistory ()
void first ()
bool more ()
bool next ()
bool prev (const QString &prefix=QString())
bool isEmpty () const
const QString & value () const
void append (const QString &inputLine)
const QStringList & values () const
void restart ()
void markScratch ()
void doScratch ()
Detailed Description
This class implements the history for the Python console.
Author
Werner Mayer
Definition at line 70 of file PythonConsole.h.
Constructor & Destructor Documentation
ConsoleHistory()
ConsoleHistory::ConsoleHistory ()
Definition at line 1560 of file PythonConsole.cpp.
~ConsoleHistory()
ConsoleHistory::~ConsoleHistory () default
Member Function Documentation
append()
void ConsoleHistory::append (const QString & inputLine)
Definition at line 1639 of file PythonConsole.cpp.
Referenced by Gui::PythonConsole::keyPressEvent(), and Gui::PythonConsole::printStatement().
doScratch()
void ConsoleHistory::doScratch ()
doScratch removes the tail of the history list, starting from the index marked lately.
Definition at line 1673 of file PythonConsole.cpp.
References restart().
first()
void ConsoleHistory::first ()
Definition at line 1568 of file PythonConsole.cpp.
isEmpty()
bool ConsoleHistory::isEmpty () const
Definition at line 1628 of file PythonConsole.cpp.
Referenced by Gui::PythonConsole::contextMenuEvent(), and Gui::PythonConsole::onCopyHistory().
markScratch()
void ConsoleHistory::markScratch ()
markScratch stores the current end index of the history list. Note: with simply remembering a start index, it does not work to nest scratch regions. However, just replace the index keeping by a stack - in case this is be a concern.
Definition at line 1665 of file PythonConsole.cpp.
more()
bool ConsoleHistory::more ()
Definition at line 1573 of file PythonConsole.cpp.
next()
bool ConsoleHistory::next ()
next switches the history pointer to the next item. While searching the next item, the routine respects the search prefix set by prev().
Returns
true if the pointer was switched to a later item, false otherwise.
Definition at line 1583 of file PythonConsole.cpp.
Referenced by Gui::PythonConsole::keyPressEvent().
prev()
bool ConsoleHistory::prev (const QString & prefix = QString())
prev switches the history pointer to the previous item. The optional parameter prefix allows one to search the history selectively for commands that start with a certain character sequence.
Parameters
prefix - prefix string for searching backwards in history, empty string by default
Returns
true if the pointer was switched to an earlier item, false otherwise.
Definition at line 1609 of file PythonConsole.cpp.
Referenced by Gui::PythonConsole::keyPressEvent().
restart()
void ConsoleHistory::restart ()
restart resets the history access to the latest item.
Definition at line 1655 of file PythonConsole.cpp.
Referenced by doScratch(), and Gui::PythonConsole::keyPressEvent().
value()
const QString & ConsoleHistory::value () const
Definition at line 1633 of file PythonConsole.cpp.
Referenced by src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), Gui::PythonConsole::keyPressEvent(), and src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue().
values()
const QStringList & ConsoleHistory::values () const
Definition at line 1647 of file PythonConsole.cpp.
Referenced by Gui::PythonConsole::createMimeDataFromSelection(), and Gui::PythonConsole::onSaveHistoryAs().
The documentation for this class was generated from the following files:
PythonConsole.h
PythonConsole.cpp