FreeCAD: Cloud Namespace Reference
Cloud Namespace Reference
Classes
struct AmzData
struct AmzDatav4
class CloudReader
class CloudWriter
class Module
Functions
std::string getHexValue (unsigned char *input, unsigned int HMACLength)
void eraseSubStr (std::string &Str, const std::string &toErase)
size_t CurlWrite_CallbackFunc_StdString (void *contents, size_t size, size_t nmemb, std::string *s)
struct AmzData * ComputeDigestAmzS3v2 (char *operation, char *data_type, const char *target, const char *Secret, const char *ptr, long size)
struct AmzDatav4 * ComputeDigestAmzS3v4 (char *operation, const char *server, char *data_type, const char *target, const char *Secret, const char *ptr, long size, char *parameters, std::string Region)
struct curl_slist * BuildHeaderAmzS3v2 (const char *URL, const char *TCPPort, const char *PublicKey, struct AmzData *Data)
struct curl_slist * BuildHeaderAmzS3v4 (const char *URL, const char *PublicKey, struct AmzDatav4 *Data)
char * MD5Sum (const char *ptr, long size)
char * SHA256Sum (const char *ptr, long size)
PyObject * initModule ()
Function Documentation
BuildHeaderAmzS3v2()
struct curl_slist * Cloud::BuildHeaderAmzS3v2 (const char * URL, const char * TCPPort, const char * PublicKey, struct AmzData * Data)
Definition at line 690 of file AppCloud.cpp.
References GCS::free(), and bimcommands.BimTutorial::URL.
Referenced by Cloud::CloudReader::CloudReader(), Cloud::CloudWriter::CloudWriter(), Cloud::CloudWriter::createBucket(), Cloud::CloudReader::DownloadFile(), and Cloud::CloudWriter::pushCloud().
BuildHeaderAmzS3v4()
struct curl_slist * Cloud::BuildHeaderAmzS3v4 (const char * URL, const char * PublicKey, struct AmzDatav4 * Data)
Definition at line 636 of file AppCloud.cpp.
References GCS::free(), and bimcommands.BimTutorial::URL.
Referenced by Cloud::CloudReader::CloudReader(), Cloud::CloudWriter::CloudWriter(), Cloud::CloudWriter::createBucket(), Cloud::CloudReader::DownloadFile(), and Cloud::CloudWriter::pushCloud().
ComputeDigestAmzS3v2()
struct Cloud::AmzData * Cloud::ComputeDigestAmzS3v2 (char * operation, char * data_type, const char * target, const char * Secret, const char * ptr, long size)
Definition at line 545 of file AppCloud.cpp.
References Base::base64_encode(), Cloud::AmzData::ContentType, Cloud::AmzData::dateFormatted, Cloud::AmzData::digest, Cloud::AmzData::MD5, and MD5Sum().
Referenced by Cloud::CloudReader::CloudReader(), Cloud::CloudWriter::CloudWriter(), Cloud::CloudWriter::createBucket(), Cloud::CloudReader::DownloadFile(), and Cloud::CloudWriter::pushCloud().
ComputeDigestAmzS3v4()
struct Cloud::AmzDatav4 * Cloud::ComputeDigestAmzS3v4 (char * operation, const char * server, char * data_type, const char * target, const char * Secret, const char * ptr, long size, char * parameters, std::string Region)
Definition at line 369 of file AppCloud.cpp.
References Cloud::AmzDatav4::ContentType, Cloud::AmzDatav4::dateFormattedD, Cloud::AmzDatav4::dateFormattedS, Cloud::AmzDatav4::digest, GCS::free(), getHexValue(), Cloud::AmzDatav4::MD5, Cloud::AmzDatav4::Region, Cloud::AmzDatav4::SHA256Sum, and SHA256Sum().
Referenced by Cloud::CloudReader::CloudReader(), Cloud::CloudWriter::CloudWriter(), Cloud::CloudWriter::createBucket(), Cloud::CloudReader::DownloadFile(), and Cloud::CloudWriter::pushCloud().
CurlWrite_CallbackFunc_StdString()
size_t Cloud::CurlWrite_CallbackFunc_StdString (void * contents, size_t size, size_t nmemb, std::string * s)
Definition at line 859 of file AppCloud.cpp.
References toolbit-attributes::s.
Referenced by Cloud::CloudReader::CloudReader(), Cloud::CloudWriter::CloudWriter(), and Cloud::CloudReader::DownloadFile().
eraseSubStr()
void Cloud::eraseSubStr (std::string & Str, const std::string & toErase)
Definition at line 1204 of file AppCloud.cpp.
References RobotExample::pos.
Referenced by Cloud::CloudReader::CloudReader(), Cloud::CloudWriter::CloudWriter(), Cloud::CloudWriter::createBucket(), Cloud::CloudReader::DownloadFile(), and Cloud::CloudWriter::pushCloud().
getHexValue()
std::string Cloud::getHexValue (unsigned char * input, unsigned int HMACLength)
Definition at line 530 of file AppCloud.cpp.
References SplineSurface::i.
Referenced by ComputeDigestAmzS3v4(), and SHA256Sum().
initModule()
PyObject* Cloud::initModule ()
Definition at line 199 of file AppCloud.h.
References Base::InterpreterSingleton::addModule(), and Base::Interpreter().
Referenced by PyMOD_INIT_FUNC().
MD5Sum()
char * Cloud::MD5Sum (const char * ptr, long size)
Definition at line 623 of file AppCloud.cpp.
References Base::base64_encode(), and result.
Referenced by ComputeDigestAmzS3v2().
SHA256Sum()
char * Cloud::SHA256Sum (const char * ptr, long size)
Definition at line 609 of file AppCloud.cpp.
References getHexValue(), and result.
Referenced by ComputeDigestAmzS3v4().