FreeCAD: Gui::Dialog::DlgSettingsCacheDirectory Class Reference
Gui::Dialog::DlgSettingsCacheDirectory Class Reference
#include <DlgSettingsCacheDirectory.h>
Public Member Functions
DlgSettingsCacheDirectory (QWidget *parent=nullptr)
~DlgSettingsCacheDirectory () override
void saveSettings () override
void loadSettings () override
void resetSettingsToDefaults () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
Detailed Description
The DlgSettingsCacheDirectory class implements a preference page to change settings for the cache directory handling.
Author
Werner Mayer
Definition at line 79 of file DlgSettingsCacheDirectory.h.
Constructor & Destructor Documentation
DlgSettingsCacheDirectory()
DlgSettingsCacheDirectory::DlgSettingsCacheDirectory (QWidget * parent = nullptr) explicit
Definition at line 53 of file DlgSettingsCacheDirectory.cpp.
References draftgeoutils.intersections::connect(), and App::Application::getUserCachePath().
~DlgSettingsCacheDirectory()
DlgSettingsCacheDirectory::~DlgSettingsCacheDirectory () override default
Member Function Documentation
changeEvent()
void DlgSettingsCacheDirectory::changeEvent (QEvent * e) override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 114 of file DlgSettingsCacheDirectory.cpp.
References SCL.SimpleDataTypes::e.
loadSettings()
void DlgSettingsCacheDirectory::loadSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 85 of file DlgSettingsCacheDirectory.cpp.
References Gui::Dialog::ApplicationCacheSettings::getCacheSizeLimit(), and Gui::Dialog::ApplicationCacheSettings::getCheckPeriod().
resetSettingsToDefaults()
void DlgSettingsCacheDirectory::resetSettingsToDefaults () override virtual
Reimplemented from Gui::Dialog::PreferencePage.
Definition at line 101 of file DlgSettingsCacheDirectory.cpp.
References Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), ParameterGrp::RemoveInt(), ParameterGrp::RemoveUnsigned(), and Gui::Dialog::PreferencePage::resetSettingsToDefaults().
saveSettings()
void DlgSettingsCacheDirectory::saveSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 79 of file DlgSettingsCacheDirectory.cpp.
References Gui::Dialog::ApplicationCacheSettings::setCacheSizeLimit(), and Gui::Dialog::ApplicationCacheSettings::setCheckPeriod().
The documentation for this class was generated from the following files:
DlgSettingsCacheDirectory.h
DlgSettingsCacheDirectory.cpp