FreeCAD: Data::IndexedName Class Reference
Data::IndexedName Class Reference
#include <IndexedName.h>
Public Member Functions
IndexedName (const char *name=nullptr, int _index=0)
IndexedName (const char *name, const std::vector< const char * > &allowedTypeNames, bool allowOthers=true)
IndexedName (const QByteArray &data)
const char * appendToStringBuffer (std::string &buffer) const
std::string toString () const
bool operator== (const IndexedName &other) const
True only if both the name and index compare exactly equal.
IndexedName & operator+= (int offset)
Increments the index by the given offset. Does not affect the text part of the name.
IndexedName & operator++ ()
Pre-increment operator: increases the index of this element by one.
IndexedName & operator-- ()
bool operator!= (const IndexedName &other) const
True if either the name or the index compare not equal.
int compare (const IndexedName &other) const
Equivalent to C++20's operator <=>
bool operator< (const IndexedName &other) const
char operator[] (int input) const
const char * getType () const
Get a pointer to text part of the name - does NOT make a copy, returns direct memory access.
int getIndex () const
Get the numerical part of the name.
void setIndex (int input)
bool isNull () const
A name is considered "null" if its text component is an empty string.
operator bool () const
Static Public Member Functions
static IndexedName fromConst (const char *name, int index)
Protected Member Functions
void set (const char *name, int length=-1, const std::vector< const char * > &allowedNames={}, bool allowOthers=true)
Friends
std::ostream & operator<< (std::ostream &stream, const IndexedName &indexedName)
Detailed Description
The IndexedName class provides a very memory-efficient data structure to hold a name and an index value, and to perform various comparisons and validations of those values. The name must only consist of upper- and lower-case ASCII characters and the underscore ('_') character. The index must be a positive integer. The string representation of this IndexedName is the name followed by the index, with no spaces between: an IndexedName may be constructed from this string. For example "EDGE1" or "FACE345" might be the names of elements that use an IndexedName. If there is then an "EDGE2", only a pointer to the original stored name "EDGE" is retained.
The memory efficiency of the class comes from re-using the same character storage for names that match, while retaining their differing indices. This is achieved by either using user-provided const char * names (provided as a list of typeNames and presumed to never be deallocated), or by maintaining an internal list of names that have been used before, and can be re-used later.
Definition at line 75 of file IndexedName.h.
Constructor & Destructor Documentation
IndexedName() [1/3]
Data::IndexedName::IndexedName (const char * name = nullptr, int _index = 0) inline explicit
Construct from a name and an optional index. If the name contains an index it is read, but is used as the index only if _index parameter is unset. If the _index parameter is given it overrides any trailing integer in the name. Index must be positive, and name must contain only ASCII letters and the underscore character. If these conditions are not met, name is set to the empty string, and isNull() will return true.
Parameters
name The new name - ASCII letters and underscores only, with optional integer suffix. This memory will be copied into a new internal storage location and need not be persistent.
_index The new index - if provided, it overrides any suffix provided by name
Definition at line 107 of file IndexedName.h.
IndexedName() [2/3]
Data::IndexedName::IndexedName (const char * name, const std::vector< const char * > & allowedTypeNames, bool allowOthers = true) inline
Create an indexed name that is restricted to a list of preset type names. If it appears in that list, only a pointer to the character storage in the list is retained: the memory locations pointed at by the list must never be destroyed once they have been used to create names. If allowOthers is true (the default) then a requested name that is not in the list will be added to a static internal storage table, and its memory then re-used for later objects with the same name. If allowOthers is false, then the name request is rejected, and the name is treated as null.
Parameters
name The new name - ASCII letters and underscores only, with optional integer suffix
allowedTypeNames A vector of allowed names. Storage locations must persist for the entire run of the program.
allowOthers Whether a name not in allowedTypeNames is permitted. If true (the default) then a name not in allowedTypeNames is added to a static internal storage vector so that it can be re-used later without additional memory allocation.
Definition at line 136 of file IndexedName.h.
IndexedName() [3/3]
Data::IndexedName::IndexedName (const QByteArray & data) inline explicit
Construct from a QByteArray, but explicitly making a copy of the name on its first occurrence. If this is a name that has already been stored internally, no additional copy is made.
Parameters
data The QByteArray to copy the data from
Definition at line 150 of file IndexedName.h.
Member Function Documentation
appendToStringBuffer()
const char* Data::IndexedName::appendToStringBuffer (std::string & buffer) const inline
Given an existing std::string, append this name to it. If index is not zero, this will include the index.
Parameters
buffer A (possibly non-empty) string buffer to append the name to.
Returns
A const char pointer to the name we appended to the buffer.
Definition at line 178 of file IndexedName.h.
Referenced by App::GeoFeature::_getElementName(), Part::Feature::getElementFromSource(), and Sketcher::SketchObject::getElementName().
compare()
int Data::IndexedName::compare (const IndexedName & other) const inline
Equivalent to C++20's operator <=>
Definition at line 248 of file IndexedName.h.
Referenced by ArchVRM.Renderer::findPosition(), Data::MappedElement::operator<(), and ArchVRM.Renderer::sort().
fromConst()
static IndexedName Data::IndexedName::fromConst (const char * name, int index) inline static
Given constant name and an index, re-use the existing memory for the name, not making a copy of it, or scanning any existing storage for it. The name must never become invalid for the lifetime of the object it names. This memory will never be re-used by another object.
Parameters
name The name of the object. This memory is NOT copied and must be persistent.
index A positive, non-zero integer
Returns
An IndexedName with the given name and index, re-using the existing memory for name
Definition at line 164 of file IndexedName.h.
Referenced by Sketcher::SketchObject::buildShape(), Sketcher::SketchObject::checkSubName(), Sketcher::SketchObject::convertSubName(), FC_LOG_LEVEL_INIT(), Sketcher::SketchObject::getEdge(), Part::Feature::getElementFromSource(), Part::Feature::getExportElementName(), Sketcher::SketchObject::getHigherElements(), Part::Feature::getRelatedElements(), Sketcher::SketchObject::getSubObject(), Part::FaceMaker::postBuild(), PartDesign::Feature::setMaterialToBodyMaterial(), and Sketcher::SketchObject::shapeTypeFromGeoId().
getIndex()
int Data::IndexedName::getIndex () const inline
Get the numerical part of the name.
Definition at line 288 of file IndexedName.h.
Referenced by Data::ElementMap::addChildElements(), Sketcher::SketchObject::convertSubName(), Data::ElementMap::erase(), Part::Chamfer::execute(), Part::Fillet::execute(), FC_LOG_LEVEL_INIT(), Data::ElementMap::find(), Data::ElementMap::findAll(), Sketcher::SketchObject::geoIdFromShapeType(), Data::ElementMap::getAll(), App::StringHasher::getID(), Sketcher::SketchObject::getSubObject(), and Part::TopoShape::shapeTypeAndIndex().
getType()
const char* Data::IndexedName::getType () const inline
Get a pointer to text part of the name - does NOT make a copy, returns direct memory access.
Definition at line 282 of file IndexedName.h.
Referenced by Data::ElementMap::addChildElements(), Sketcher::SketchObject::convertSubName(), Data::ComplexGeoData::elementType(), Data::ElementMap::erase(), Data::ElementMap::find(), Data::ElementMap::findAll(), Sketcher::SketchObject::geoIdFromShapeType(), Part::Feature::getExportElementName(), App::StringHasher::getID(), Sketcher::SketchObject::getSubObject(), Data::ElementMap::setElementName(), and Part::TopoShape::shapeTypeAndIndex().
isNull()
bool Data::IndexedName::isNull () const inline
A name is considered "null" if its text component is an empty string.
Definition at line 306 of file IndexedName.h.
References Data::ByteArray::ByteArray(), Data::ByteArray::bytes, and Path.Post.scripts.opensbp_post::move().
operator bool()
Data::IndexedName::operator bool () const inline explicit
Boolean conversion provides the opposite of isNull(), yielding true when the text part of the name is NOT the empty string.
Definition at line 313 of file IndexedName.h.
operator!=()
bool Data::IndexedName::operator!= (const IndexedName & other) const inline
True if either the name or the index compare not equal.
Definition at line 242 of file IndexedName.h.
References Path.Post.scripts.grbl_post::type.
operator++()
IndexedName& Data::IndexedName::operator++ () inline
Pre-increment operator: increases the index of this element by one.
Definition at line 226 of file IndexedName.h.
References nativeifc.ifc_selftest::compare().
operator+=()
IndexedName& Data::IndexedName::operator+= (int offset) inline
Increments the index by the given offset. Does not affect the text part of the name.
Definition at line 218 of file IndexedName.h.
operator--()
IndexedName& Data::IndexedName::operator-- () inline
Pre-decrement operator: decreases the index of this element by one. Must not make the index negative (only checked when compiled in debug mode).
Definition at line 234 of file IndexedName.h.
operator<()
bool Data::IndexedName::operator< (const IndexedName & other) const inline
Provided to enable sorting operations: the comparison is first lexicographical for the text element of the names, then numerical for the indices.
Definition at line 265 of file IndexedName.h.
References Path.Post.scripts.grbl_post::type.
operator==()
bool Data::IndexedName::operator== (const IndexedName & other) const inline
True only if both the name and index compare exactly equal.
Definition at line 211 of file IndexedName.h.
operator[]()
char Data::IndexedName::operator[] (int input) const inline
Allow direct memory access to the individual characters of the text portion of the name. NOTE: input is not range-checked when compiled in release mode.
Definition at line 272 of file IndexedName.h.
set()
void IndexedName::set (const char * name, int length = -1, const std::vector< const char * > & allowedNames = {}, bool allowOthers = true) protected
Apply the IndexedName rules and either store the characters of a new type or a reference to the characters in a type named in types, or stored statically within this function. If len is not set, or set to -1 (the default), then the provided string in name is scanned for its length using strlen (e.g. it must be null-terminated).
Parameters
name The new name. If necessary a copy is made, this char * need not be persistent
length The length of name
allowedNames A vector of storage locations of allowed names. These storage locations must be persistent for the duration of the program run.
allowOthers If true (the default), then if name is not in allowedNames it is allowed, and it is added to internal storage (making a copy of the name if this is its first occurrence).
Definition at line 71 of file IndexedName.cpp.
References getIntegerSuffix(), and isInvalidChar().
Referenced by draftguitools.gui_trackers.editTracker::move().
setIndex()
void Data::IndexedName::setIndex (int input) inline
Set the numerical part of the name (note that there is no equivalent function to allow changing the text part of the name, which is immutable once created).
Parameters
input The new index. Must be a positive non-zero integer
Definition at line 297 of file IndexedName.h.
Referenced by Data::ElementMap::find(), Data::ElementMap::getAll(), and App::StringHasher::getID().
toString()
std::string Data::IndexedName::toString () const inline
Create and return a new std::string with this name in it.
Returns
A newly-created string with the IndexedName in it (e.g. "EDGE42")
Definition at line 192 of file IndexedName.h.
Referenced by Sketcher::SketchObject::convertSubName().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & stream, const IndexedName & indexedName) friend
An indexedName is represented as the simple concatenation of the name and its index, e.g. "EDGE1" or "FACE42".
Definition at line 201 of file IndexedName.h.
The documentation for this class was generated from the following files:
IndexedName.h
IndexedName.cpp