FreeCAD: PartGui::ThicknessWidget Class Reference
PartGui::ThicknessWidget Class Reference
#include <TaskThickness.h>
Classes
class Private
Public Member Functions
ThicknessWidget (Part::Thickness *, QWidget *parent=nullptr)
~ThicknessWidget () override
bool accept ()
bool reject ()
Part::Thickness * getObject () const
Detailed Description
Definition at line 33 of file TaskThickness.h.
Constructor & Destructor Documentation
ThicknessWidget()
ThicknessWidget::ThicknessWidget (Part::Thickness * thickness, QWidget * parent = nullptr) explicit
Definition at line 78 of file TaskThickness.cpp.
References Gui::Command::App, App::PropertyQuantity::getValue(), App::PropertyEnumeration::getValue(), App::PropertyBool::getValue(), Part::Thickness::Intersection, Part::Thickness::Join, Part::Thickness::Mode, Init::parent, runCommand, Part::Thickness::SelfIntersection, PartGui::ThicknessWidget::Private::thickness, PartGui::ThicknessWidget::Private::ui, and Part::Thickness::Value.
~ThicknessWidget()
ThicknessWidget::~ThicknessWidget () override
Definition at line 114 of file TaskThickness.cpp.
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
accept()
bool ThicknessWidget::accept ()
Definition at line 230 of file TaskThickness.cpp.
References Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Gui::Command::Doc, doCommand, SCL.SimpleDataTypes::e, App::DocumentObject::getStatusString(), Gui::Command::Gui, App::DocumentObject::isValid(), PartGui::ThicknessWidget::Private::selection, PartGui::ThicknessWidget::Private::thickness, src.Mod.AddonManager.Addon::translate, PartGui::ThicknessWidget::Private::ui, and Path.Log::warning().
Referenced by PartGui::TaskThickness::accept().
getObject()
Part::Thickness * ThicknessWidget::getObject () const
Definition at line 140 of file TaskThickness.cpp.
References PartGui::ThicknessWidget::Private::thickness.
Referenced by PartGui::TaskThickness::getObject().
reject()
bool ThicknessWidget::reject ()
Definition at line 262 of file TaskThickness.cpp.
References Gui::Command::abortCommand(), doCommand, Part::Thickness::Faces, App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::Document::getObject(), App::PropertyLinkSub::getValue(), Gui::Application::getViewProvider(), Gui::Command::Gui, Gui::Application::Instance, Gui::ViewProvider::show(), PartGui::ThicknessWidget::Private::thickness, PartGui::ThicknessWidget::Private::ui, and Gui::Command::updateActive().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and PartGui::TaskThickness::reject().
The documentation for this class was generated from the following files:
TaskThickness.h
TaskThickness.cpp