FreeCAD: App::DocInfo Class Reference
App::DocInfo Class Reference
Public Types
using Connection = boost::signals2::scoped_connection
Public Member Functions
QString getFullPath () const
const char * filePath () const
void deinit ()
void init (DocInfoMap::iterator pos, const char *objName, PropertyXLink *l)
void attach (Document *doc)
void remove (PropertyXLink *l)
void slotFinishRestoreDocument (const App::Document &doc)
void slotSaveDocument (const App::Document &doc)
void slotDeleteDocument (const App::Document &doc)
bool hasXLink (const App::Document *doc) const
Static Public Member Functions
static std::string getDocPath (const char *filename, App::Document *pDoc, bool relative, QString *fullPath=nullptr)
static DocInfoPtr get (const char *filename, App::Document *pDoc, PropertyXLink *l, const char *objName)
static QString getFullPath (const char *p)
static void restoreDocument (const App::Document &doc)
static void breakLinks (App::DocumentObject *obj, bool clear)
Public Attributes
Connection connFinishRestoreDocument
Connection connPendingReloadDocument
Connection connDeleteDocument
Connection connSaveDocument
Connection connDeletedObject
DocInfoMap::iterator myPos
std::string myPath
App::Document * pcDoc {nullptr}
std::set< PropertyXLink * > links
Detailed Description
Definition at line 3290 of file PropertyLinks.cpp.
Member Typedef Documentation
Connection
using App::DocInfo::Connection = boost::signals2::scoped_connection
Definition at line 3293 of file PropertyLinks.cpp.
Member Function Documentation
attach()
void App::DocInfo::attach (Document * doc) inline
Definition at line 3486 of file PropertyLinks.cpp.
References App::Application::addPendingDocument(), toolbit-attributes::doc, FC_LOG, FC_WARN, App::GetApplication(), App::PropertyLinkBase::LinkRestoring, links, App::Document::PartialDoc, pcDoc, and TestSpreadsheet::v.
Referenced by Path.Dressup.Gui.Boundary.DressupPathBoundaryViewProvider::__init__(), init(), and slotFinishRestoreDocument().
breakLinks()
static void App::DocInfo::breakLinks (App::DocumentObject * obj, bool clear) inline static
Definition at line 3683 of file PropertyLinks.cpp.
References _DocInfoMap, Path.Op.Gui.Selection::clear(), toolbit-attributes::doc, App::DocumentObject::getDocument(), and links.
Referenced by App::PropertyLinkBase::breakLinks().
deinit()
void App::DocInfo::deinit () inline
Definition at line 3432 of file PropertyLinks.cpp.
References _DocInfoMap, connDeletedObject, connDeleteDocument, connFinishRestoreDocument, connPendingReloadDocument, connSaveDocument, FC_LOG, filePath(), App::Document::getName(), links, myPath, myPos, and pcDoc.
Referenced by remove(), and slotDeleteDocument().
filePath()
const char* App::DocInfo::filePath () const inline
Definition at line 3427 of file PropertyLinks.cpp.
References myPath.
Referenced by deinit(), and init().
get()
static DocInfoPtr App::DocInfo::get (const char * filename, App::Document * pDoc, PropertyXLink * l, const char * objName) inline static
Definition at line 3355 of file PropertyLinks.cpp.
References _DocInfoMap, App::Application::addPendingDocument(), toolbit-attributes::doc, FC_LOG, App::GetApplication(), getDocPath(), getFullPath(), Path.Log::info(), RobotExample::l, and App::PropertyLinkBase::LinkAllowPartial.
Referenced by draftguitools.gui_trackers.editTracker::move(), and slotSaveDocument().
getDocPath()
static std::string App::DocInfo::getDocPath (const char * filename, App::Document * pDoc, bool relative, QString * fullPath = nullptr) inline static
Definition at line 3305 of file PropertyLinks.cpp.
References App::Document::getFileName().
Referenced by get(), and App::PropertyXLink::Save().
getFullPath() [1/2]
QString App::DocInfo::getFullPath () const inline
Definition at line 3416 of file PropertyLinks.cpp.
References myPos.
Referenced by get(), init(), restoreDocument(), slotFinishRestoreDocument(), and slotSaveDocument().
getFullPath() [2/2]
static QString App::DocInfo::getFullPath (const char * p) inline static
Definition at line 3401 of file PropertyLinks.cpp.
References buildPsets::p.
hasXLink()
bool App::DocInfo::hasXLink (const App::Document * doc) const inline
Definition at line 3672 of file PropertyLinks.cpp.
References toolbit-attributes::doc, App::DocumentObject::getDocument(), and links.
init()
void App::DocInfo::init (DocInfoMap::iterator pos, const char * objName, PropertyXLink * l) inline
Definition at line 3449 of file PropertyLinks.cpp.
References src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui::app, attach(), draftgeoutils.faces::bind(), connDeleteDocument, connFinishRestoreDocument, connPendingReloadDocument, connSaveDocument, toolbit-attributes::doc, FC_ERR, FC_LOG, filePath(), App::GetApplication(), getFullPath(), RobotExample::l, App::PropertyLinkBase::LinkAllowPartial, myPath, myPos, App::Document::PartialDoc, RobotExample::pos, slotDeleteDocument(), slotFinishRestoreDocument(), and slotSaveDocument().
Referenced by DocumentObject.DocumentObject::onChanged().
remove()
void App::DocInfo::remove (PropertyXLink * l) inline
Definition at line 3543 of file PropertyLinks.cpp.
References deinit(), RobotExample::l, and links.
Referenced by src.Mod.AddonManager.AddonManager.CommandAddonManager::launch().
restoreDocument()
static void App::DocInfo::restoreDocument (const App::Document & doc) inline static
Definition at line 3554 of file PropertyLinks.cpp.
References _DocInfoMap, toolbit-attributes::doc, and getFullPath().
Referenced by App::PropertyXLink::restoreDocument().
slotDeleteDocument()
void App::DocInfo::slotDeleteDocument (const App::Document & doc) inline
Definition at line 3625 of file PropertyLinks.cpp.
References deinit(), toolbit-attributes::doc, App::DocumentObject::getDocument(), RobotExample::l, App::PropertyLinkBase::LinkDetached, links, pcDoc, and TestSpreadsheet::v.
Referenced by init(), and slotSaveDocument().
slotFinishRestoreDocument()
void App::DocInfo::slotFinishRestoreDocument (const App::Document & doc) inline
Definition at line 3563 of file PropertyLinks.cpp.
References attach(), toolbit-attributes::doc, getFullPath(), and pcDoc.
Referenced by init(), and slotSaveDocument().
slotSaveDocument()
void App::DocInfo::slotSaveDocument (const App::Document & doc) inline
Definition at line 3574 of file PropertyLinks.cpp.
References _DocInfoMap, toolbit-attributes::doc, FC_LOG, FC_WARN, get(), getFullPath(), Path.Log::info(), links, myPos, pcDoc, slotDeleteDocument(), and slotFinishRestoreDocument().
Referenced by init().
Member Data Documentation
connDeletedObject
Connection App::DocInfo::connDeletedObject
Definition at line 3298 of file PropertyLinks.cpp.
Referenced by deinit().
connDeleteDocument
Connection App::DocInfo::connDeleteDocument
Definition at line 3296 of file PropertyLinks.cpp.
Referenced by deinit(), and init().
connFinishRestoreDocument
Connection App::DocInfo::connFinishRestoreDocument
Definition at line 3294 of file PropertyLinks.cpp.
Referenced by deinit(), and init().
connPendingReloadDocument
Connection App::DocInfo::connPendingReloadDocument
Definition at line 3295 of file PropertyLinks.cpp.
Referenced by deinit(), and init().
connSaveDocument
Connection App::DocInfo::connSaveDocument
Definition at line 3297 of file PropertyLinks.cpp.
Referenced by deinit(), and init().
links
std::set<PropertyXLink*> App::DocInfo::links
Definition at line 3303 of file PropertyLinks.cpp.
Referenced by attach(), breakLinks(), deinit(), hasXLink(), remove(), slotDeleteDocument(), and slotSaveDocument().
myPath
std::string App::DocInfo::myPath
Definition at line 3301 of file PropertyLinks.cpp.
Referenced by deinit(), filePath(), and init().
myPos
DocInfoMap::iterator App::DocInfo::myPos
Definition at line 3300 of file PropertyLinks.cpp.
Referenced by deinit(), getFullPath(), init(), and slotSaveDocument().
pcDoc
App::Document* App::DocInfo::pcDoc {nullptr}
Definition at line 3302 of file PropertyLinks.cpp.
Referenced by attach(), deinit(), slotDeleteDocument(), slotFinishRestoreDocument(), and slotSaveDocument().
The documentation for this class was generated from the following file:
PropertyLinks.cpp