FreeCAD: Import::ExportOCAF Class Reference
Import::ExportOCAF Class Reference
#include <ExportOCAF.h>
Public Member Functions
ExportOCAF (Handle(TDocStd_Document) hDoc, bool explicitPlacement)
virtual ~ExportOCAF ()
void exportObjects (std::vector< App::DocumentObject * > &objs)
int exportObject (App::DocumentObject *obj, std::vector< TDF_Label > &hierarchical_label, std::vector< TopLoc_Location > &hierarchical_loc, std::vector< App::DocumentObject * > &hierarchical_part)
int saveShape (Part::Feature *part, const std::vector< App::Color > &, std::vector< TDF_Label > &hierarchical_label, std::vector< TopLoc_Location > &hierarchical_loc, std::vector< App::DocumentObject * > &hierarchical_part)
void getPartColors (std::vector< App::DocumentObject * > hierarchical_part, std::vector< TDF_Label > FreeLabels, std::vector< int > part_id, std::vector< std::vector< App::Color >> &Colors) const
void reallocateFreeShape (std::vector< App::DocumentObject * > hierarchical_part, std::vector< TDF_Label > FreeLabels, std::vector< int > part_id, std::vector< std::vector< App::Color >> &Colors)
void getFreeLabels (std::vector< TDF_Label > &hierarchical_label, std::vector< TDF_Label > &labels, std::vector< int > &label_part_id)
void createNode (App::Part *part, int &root_it, std::vector< TDF_Label > &hierarchical_label, std::vector< TopLoc_Location > &hierarchical_loc, std::vector< App::DocumentObject * > &hierarchical_part)
void pushNode (int root, int node, std::vector< TDF_Label > &hierarchical_label, std::vector< TopLoc_Location > &hierarchical_loc)
Detailed Description
Definition at line 57 of file ExportOCAF.h.
Constructor & Destructor Documentation
ExportOCAF()
ExportOCAF::ExportOCAF (Handle(TDocStd_Document) hDoc, bool explicitPlacement)
Definition at line 70 of file ExportOCAF.cpp.
References Part::Interface::Auto, and Part::Interface::writeStepAssembly().
~ExportOCAF()
ExportOCAF::~ExportOCAF () virtual default
Member Function Documentation
createNode()
void ExportOCAF::createNode (App::Part * part, int & root_it, std::vector< TDF_Label > & hierarchical_label, std::vector< TopLoc_Location > & hierarchical_loc, std::vector< App::DocumentObject * > & hierarchical_part)
Definition at line 205 of file ExportOCAF.cpp.
References DraftVecUtils::angle(), Base::Placement::getPosition(), Base::Placement::getRotation(), Base::Rotation::getValue(), App::PropertyPlacement::getValue(), App::PropertyString::getValue(), Handle(), App::DocumentObject::Label, App::GeoFeature::Placement, Set(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by exportObject().
exportObject()
int ExportOCAF::exportObject (App::DocumentObject * obj, std::vector< TDF_Label > & hierarchical_label, std::vector< TopLoc_Location > & hierarchical_loc, std::vector< App::DocumentObject * > & hierarchical_part)
Definition at line 156 of file ExportOCAF.cpp.
References importers.importIFCmulticore::colors, createNode(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::GroupExtension::Group, Base::BaseClass::isDerivedFrom(), pushNode(), and saveShape().
Referenced by exportObjects().
exportObjects()
void ExportOCAF::exportObjects (std::vector< App::DocumentObject * > & objs)
Definition at line 132 of file ExportOCAF.cpp.
References exportObject(), getFreeLabels(), getPartColors(), replaceobj::objs, and reallocateFreeShape().
getFreeLabels()
void ExportOCAF::getFreeLabels (std::vector< TDF_Label > & hierarchical_label, std::vector< TDF_Label > & labels, std::vector< int > & label_part_id)
Definition at line 340 of file ExportOCAF.cpp.
References SplineSurface::i, and App::ExpressionParser::labels.
Referenced by exportObjects().
getPartColors()
void ExportOCAF::getPartColors (std::vector< App::DocumentObject * > hierarchical_part, std::vector< TDF_Label > FreeLabels, std::vector< int > part_id, std::vector< std::vector< App::Color >> & Colors) const
Definition at line 358 of file ExportOCAF.cpp.
References importers.importIFCmulticore::colors, and SplineSurface::i.
Referenced by exportObjects().
pushNode()
void ExportOCAF::pushNode (int root, int node, std::vector< TDF_Label > & hierarchical_label, std::vector< TopLoc_Location > & hierarchical_loc)
Definition at line 444 of file ExportOCAF.cpp.
Referenced by exportObject().
reallocateFreeShape()
void ExportOCAF::reallocateFreeShape (std::vector< App::DocumentObject * > hierarchical_part, std::vector< TDF_Label > FreeLabels, std::vector< int > part_id, std::vector< std::vector< App::Color >> & Colors)
Definition at line 373 of file ExportOCAF.cpp.
References importers.importIFCmulticore::colors, convertColor(), Mesh2Shape::faces, Base::Persistence::getClassTypeId(), Part::PropertyPartShape::getValue(), SplineSurface::i, and Part::Feature::Shape.
Referenced by exportObjects().
saveShape()
int ExportOCAF::saveShape (Part::Feature * part, const std::vector< App::Color > & colors, std::vector< TDF_Label > & hierarchical_label, std::vector< TopLoc_Location > & hierarchical_loc, std::vector< App::DocumentObject * > & hierarchical_part)
Definition at line 234 of file ExportOCAF.cpp.
References DraftVecUtils::angle(), importers.importIFCmulticore::colors, convertColor(), Mesh2Shape::faces, Base::Placement::getPosition(), Base::Placement::getRotation(), Part::PropertyPartShape::getValue(), Base::Rotation::getValue(), App::PropertyPlacement::getValue(), App::PropertyString::getValue(), Handle(), App::DocumentObject::Label, App::GeoFeature::Placement, Set(), Part::Feature::Shape, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by exportObject().
The documentation for this class was generated from the following files:
ExportOCAF.h
ExportOCAF.cpp