FreeCAD: modelRefine.cpp File Reference
modelRefine.cpp File Reference
#include "PreCompiled.h"
#include <algorithm>
#include <iterator>
#include <Bnd_Box.hxx>
#include <BRep_Builder.hxx>
#include <BRep_Tool.hxx>
#include <BRepAdaptor_Curve.hxx>
#include <BRepBndLib.hxx>
#include <BRepGProp.hxx>
#include <BRepLib_FuseEdges.hxx>
#include <BRepLib_MakeWire.hxx>
#include <BRepBuilderAPI_MakeFace.hxx>
#include <BRepBuilderAPI_MakeSolid.hxx>
#include <BRepBuilderAPI_Sewing.hxx>
#include <Geom_BSplineSurface.hxx>
#include <Geom_Conic.hxx>
#include <Geom_CylindricalSurface.hxx>
#include <Geom_Plane.hxx>
#include <Geom_RectangularTrimmedSurface.hxx>
#include <Geom_Surface.hxx>
#include <GeomAdaptor_Surface.hxx>
#include <GeomAPI_ProjectPointOnSurf.hxx>
#include <gp_Ax3.hxx>
#include <gp_Cylinder.hxx>
#include <gp_Pln.hxx>
#include <GProp_GProps.hxx>
#include <ShapeAnalysis_Curve.hxx>
#include <ShapeAnalysis_Shell.hxx>
#include <ShapeBuild_ReShape.hxx>
#include <ShapeFix_Face.hxx>
#include <Standard_Version.hxx>
#include <TColgp_Array2OfPnt.hxx>
#include <TColgp_SequenceOfPnt.hxx>
#include <TColStd_Array1OfReal.hxx>
#include <TopoDS.hxx>
#include <TopoDS_Compound.hxx>
#include <TopoDS_Shape.hxx>
#include <TopExp.hxx>
#include <TopExp_Explorer.hxx>
#include <TopTools_DataMapIteratorOfDataMapOfIntegerListOfShape.hxx>
#include <TopTools_DataMapIteratorOfDataMapOfShapeShape.hxx>
#include <TopTools_ListIteratorOfListOfShape.hxx>
#include <TopTools_ListOfShape.hxx>
#include <Base/Console.h>
#include "modelRefine.h"
Classes
class ModelRefine::WireSort
Namespaces
ModelRefine
Functions
static Handle (Geom_Plane) getGeomPlane(const TopoDS_Face &faceIn)
static Handle (Geom_CylindricalSurface) getGeomCylinder(const TopoDS_Face &faceIn)
const TopoDS_Face fixFace (const TopoDS_Face &f)
bool wireEncirclesAxis (const TopoDS_Wire &wire, const Handle(Geom_CylindricalSurface)&cylinder)
void collectConicEdges (const TopoDS_Shell &shell, TopTools_IndexedMapOfShape &map)
Function Documentation
collectConicEdges()
void collectConicEdges (const TopoDS_Shell & shell, TopTools_IndexedMapOfShape & map)
Definition at line 789 of file modelRefine.cpp.
References Handle(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf::shell.
Referenced by ModelRefine::FaceUniter::process().
fixFace()
const TopoDS_Face fixFace (const TopoDS_Face & f)
Definition at line 486 of file modelRefine.cpp.
References SCL.SimpleDataTypes::f.
Referenced by ModelRefine::FaceTypedCylinder::buildFace().
Handle() [1/2]
static Handle (Geom_CylindricalSurface) const & static
Definition at line 444 of file modelRefine.cpp.
References Handle().
Handle() [2/2]
static Handle (Geom_Plane) const & static
Definition at line 353 of file modelRefine.cpp.
Referenced by ModelRefine::FaceTypedCylinder::buildFace(), ModelRefine::FaceTypedBSpline::buildFace(), collectConicEdges(), ModelRefine::FaceTypedBase::getFaceType(), Handle(), ModelRefine::FaceTypedPlane::isEqual(), ModelRefine::FaceTypedCylinder::isEqual(), ModelRefine::FaceTypedBSpline::isEqual(), and wireEncirclesAxis().
wireEncirclesAxis()
bool wireEncirclesAxis (const TopoDS_Wire & wire, const Handle(Geom_CylindricalSurface)& cylinder)
Definition at line 507 of file modelRefine.cpp.
References DraftVecUtils::dist(), Handle(), M_PI, and WorkingPlane::plane.
Referenced by ModelRefine::FaceTypedCylinder::buildFace().