FreeCAD: SIM::Coin3D::Quarter::EventFilter Class Reference
SIM::Coin3D::Quarter::EventFilter Class Reference
#include <Quarter/eventhandlers/EventFilter.h>
Public Member Functions
EventFilter (QObject *parent)
~EventFilter () override
void registerInputDevice (InputDevice *device)
void unregisterInputDevice (InputDevice *device)
const QPoint & globalMousePosition () const
Protected Member Functions
bool eventFilter (QObject *obj, QEvent *event) override
Detailed Description
Definition at line 46 of file EventFilter.h.
Constructor & Destructor Documentation
EventFilter()
EventFilter::EventFilter (QObject * parent)
Definition at line 90 of file EventFilter.cpp.
References Init::parent, and PRIVATE.
~EventFilter()
EventFilter::~EventFilter () override
Definition at line 111 of file EventFilter.cpp.
References PRIVATE.
Member Function Documentation
eventFilter()
bool EventFilter::eventFilter (QObject * obj, QEvent * qevent) override protected
Translates Qt Events into Coin events and passes them on to the event QuarterWidget for processing. If the event cannot be translated or processed, it is forwarded to Qt and the method returns false.
Definition at line 144 of file EventFilter.cpp.
References PRIVATE, and SIM::Coin3D::Quarter::InputDevice::translateEvent().
globalMousePosition()
const QPoint & EventFilter::globalMousePosition () const
Returns mouse position in global coordinates
Definition at line 178 of file EventFilter.cpp.
References PRIVATE.
Referenced by SIM::Coin3D::Quarter::QuarterWidgetP::statechangecb().
registerInputDevice()
void EventFilter::registerInputDevice (InputDevice * device)
Adds a device for event translation
Definition at line 121 of file EventFilter.cpp.
References PRIVATE.
Referenced by Gui::View3DInventorViewer::init().
unregisterInputDevice()
void EventFilter::unregisterInputDevice (InputDevice * device)
Removes a device from event translation
Definition at line 130 of file EventFilter.cpp.
References SplineSurface::i, and PRIVATE.
The documentation for this class was generated from the following files:
EventFilter.h
EventFilter.cpp