FreeCAD: Gui::ToolBoxManager Class Reference
Gui::ToolBoxManager Class Reference
#include <ToolBoxManager.h>
Public Member Functions
void setup (ToolBarItem *) const
void setToolBox (DockWnd::ToolBox *)
void retranslate () const
Static Public Member Functions
static ToolBoxManager * getInstance ()
The one and only instance.
static void destruct ()
Protected Member Functions
ToolBoxManager ()
~ToolBoxManager ()
Detailed Description
The ToolBoxManager class is responsible for the creation of command bars and appending them to the toolbox window.
See also
ToolBarManager
MenuManager
Author
Werner Mayer
Definition at line 64 of file ToolBoxManager.h.
Constructor & Destructor Documentation
ToolBoxManager()
ToolBoxManager::ToolBoxManager () protected default
Referenced by getInstance().
~ToolBoxManager()
ToolBoxManager::~ToolBoxManager () protected default
Member Function Documentation
destruct()
void ToolBoxManager::destruct () static
Definition at line 50 of file ToolBoxManager.cpp.
getInstance()
ToolBoxManager * ToolBoxManager::getInstance () static
The one and only instance.
Definition at line 43 of file ToolBoxManager.cpp.
References ToolBoxManager().
retranslate()
void ToolBoxManager::retranslate () const
Definition at line 121 of file ToolBoxManager.cpp.
References Gui::DockWnd::ToolBox::count(), SplineSurface::i, Gui::DockWnd::ToolBox::setItemText(), src.Mod.PartDesign.fcgear.svggear::w, and Gui::DockWnd::ToolBox::widget().
setToolBox()
void ToolBoxManager::setToolBox (DockWnd::ToolBox * tb)
Definition at line 60 of file ToolBoxManager.cpp.
setup()
void ToolBoxManager::setup (ToolBarItem * toolBar) const
Sets up the command bars of a given workbench.
Definition at line 65 of file ToolBoxManager.cpp.
References Gui::DockWnd::ToolBox::addItem(), Gui::CommandManager::addTo(), Gui::Application::commandManager(), Gui::DockWnd::ToolBox::count(), Gui::ToolBarItem::getItems(), SplineSurface::i, Gui::Application::Instance, src.Mod.Test.testPathArray::items, buildPsets::p, Gui::DockWnd::ToolBox::removeItem(), Sketcher::Vertical, src.Mod.PartDesign.fcgear.svggear::w, and Gui::DockWnd::ToolBox::widget().
Referenced by Path.Dressup.Tags.ObjectTagDressup::doExecute(), Path.Dressup.Gui.Dogbone.ObjectDressup::execute(), Path.Dressup.Tags.ObjectTagDressup::generateTags(), Path.Dressup.Tags.ObjectTagDressup::pointAtBottom(), Path.Dressup.Tags.ObjectTagDressup::pointIsOnPath(), Path.Dressup.Tags.ObjectTagDressup::setXyEnabled(), and Path.Dressup.Tags.ObjectTagDressup::supportsTagGeneration().
The documentation for this class was generated from the following files:
ToolBoxManager.h
ToolBoxManager.cpp