FreeCAD: Wm4::ConvexHull3< Real > Class Template Reference
Wm4::ConvexHull3< Real > Class Template Reference
#include <Wm4ConvexHull3.h>
Public Member Functions
ConvexHull3 (int iVertexQuantity, Vector3< Real > *akVertex, Real fEpsilon, bool bOwner, Query::Type eQueryType)
virtual ~ConvexHull3 ()
const Vector3< Real > & GetLineOrigin () const
const Vector3< Real > & GetLineDirection () const
ConvexHull1< Real > * GetConvexHull1 () const
const Vector3< Real > & GetPlaneOrigin () const
const Vector3< Real > & GetPlaneDirection (int i) const
ConvexHull2< Real > * GetConvexHull2 () const
ConvexHull3 (const char *acFilename)
bool Load (const char *acFilename)
bool Save (const char *acFilename) const
Public Member Functions inherited from Wm4::ConvexHull< Real >
virtual ~ConvexHull ()
int GetQueryType () const
int GetVertexQuantity () const
Real GetEpsilon () const
bool GetOwner () const
int GetDimension () const
int GetSimplexQuantity () const
const int * GetIndices () const
Additional Inherited Members
Protected Member Functions inherited from Wm4::ConvexHull< Real >
ConvexHull (int iVertexQuantity, Real fEpsilon, bool bOwner, Query::Type eQueryType)
bool Load (FILE *pkIFile)
bool Save (FILE *pkOFile) const
Protected Attributes inherited from Wm4::ConvexHull< Real >
Query::Type m_eQueryType
int m_iVertexQuantity
int m_iDimension
int m_iSimplexQuantity
int * m_aiIndex
Real m_fEpsilon
bool m_bOwner
Detailed Description
template<class Real>
class Wm4::ConvexHull3< Real >
Definition at line 21 of file Wm4ConvexHull3.h.
Constructor & Destructor Documentation
ConvexHull3() [1/2]
template<class Real > Wm4::ConvexHull3< Real >::ConvexHull3 (int iVertexQuantity, Vector3< Real > * akVertex, Real fEpsilon, bool bOwner, Query::Type eQueryType)
Definition at line 22 of file Wm4ConvexHull3.cpp.
References Wm4::Mapper3< Real >::GetDimension(), Wm4::Mapper3< Real >::GetDirection(), Wm4::Mapper3< Real >::GetExtremeCCW(), Wm4::Mapper3< Real >::GetExtremeIndex(), Wm4::Mapper3< Real >::GetMaxRange(), Wm4::Mapper3< Real >::GetMin(), Wm4::Mapper3< Real >::GetOrigin(), SplineSurface::i, Wm4::ConvexHull< Real >::m_fEpsilon, Wm4::ConvexHull< Real >::m_iDimension, Wm4::ConvexHull< Real >::m_iVertexQuantity, Wm4::System::Memcpy(), Wm4::Query::QT_FILTERED, Wm4::Query::QT_INT64, Wm4::Query::QT_INTEGER, Wm4::Query::QT_RATIONAL, TechDraw::Triangle, and WM4_NEW.
~ConvexHull3()
template<class Real > Wm4::ConvexHull3< Real >::~ConvexHull3 virtual
Definition at line 181 of file Wm4ConvexHull3.cpp.
References WM4_DELETE.
ConvexHull3() [2/2]
template<class Real > Wm4::ConvexHull3< Real >::ConvexHull3 (const char * acFilename)
Definition at line 403 of file Wm4ConvexHull3.cpp.
References Wm4::ConvexHull3< Real >::Load().
Member Function Documentation
GetConvexHull1()
template<class Real > ConvexHull1< Real > * Wm4::ConvexHull3< Real >::GetConvexHull1
Definition at line 217 of file Wm4ConvexHull3.cpp.
References Wm4::Vector3< Real >::Dot(), SplineSurface::i, and WM4_NEW.
Referenced by Wm4::ContMinBox().
GetConvexHull2()
template<class Real > ConvexHull2< Real > * Wm4::ConvexHull3< Real >::GetConvexHull2
Definition at line 237 of file Wm4ConvexHull3.cpp.
References Wm4::Vector2< Real >::Dot(), SplineSurface::i, and WM4_NEW.
GetLineDirection()
template<class Real > const Vector3< Real > & Wm4::ConvexHull3< Real >::GetLineDirection
Definition at line 198 of file Wm4ConvexHull3.cpp.
GetLineOrigin()
template<class Real > const Vector3< Real > & Wm4::ConvexHull3< Real >::GetLineOrigin
Definition at line 192 of file Wm4ConvexHull3.cpp.
GetPlaneDirection()
template<class Real > const Vector3< Real > & Wm4::ConvexHull3< Real >::GetPlaneDirection (int i) const
Definition at line 210 of file Wm4ConvexHull3.cpp.
References SplineSurface::i.
Referenced by Wm4::ContMinBox().
GetPlaneOrigin()
template<class Real > const Vector3< Real > & Wm4::ConvexHull3< Real >::GetPlaneOrigin
Definition at line 204 of file Wm4ConvexHull3.cpp.
Referenced by Wm4::ContMinBox().
Load()
template<class Real > bool Wm4::ConvexHull3< Real >::Load (const char * acFilename)
Definition at line 416 of file Wm4ConvexHull3.cpp.
References Wm4::System::Fclose(), Wm4::System::Fopen(), Wm4::ConvexHull< Real >::Load(), Wm4::Query::QT_FILTERED, Wm4::Query::QT_INT64, Wm4::Query::QT_INTEGER, Wm4::Query::QT_RATIONAL, Wm4::Query::QT_REAL, Wm4::System::Read4le(), Wm4::System::Read8le(), WM4_DELETE, and WM4_NEW.
Referenced by Wm4::ConvexHull3< Real >::ConvexHull3().
Save()
template<class Real > bool Wm4::ConvexHull3< Real >::Save (const char * acFilename) const
Definition at line 488 of file Wm4ConvexHull3.cpp.
References Wm4::System::Fclose(), Wm4::System::Fopen(), Wm4::ConvexHull< Real >::Save(), Wm4::System::Write4le(), and Wm4::System::Write8le().
The documentation for this class was generated from the following files:
Wm4ConvexHull3.h
Wm4ConvexHull3.cpp