FreeCAD: ColorPickerPopup Class Reference
ColorPickerPopup Class Reference
Public Slots
void getColorFromDialog ()
Signals
void selected (const QColor &)
void hid ()
Public Member Functions
ColorPickerPopup (int width, bool withColorDialog, QWidget *parent=nullptr)
~ColorPickerPopup () override
void insertColor (const QColor &col, const QString &text, int index)
void exec ()
void setExecFlag ()
QColor lastSelected () const
ColorPickerItem * find (const QColor &col) const
QColor color (int index) const
void setLastSel (const QColor &col)
Protected Slots
void updateSelected ()
Protected Member Functions
void keyPressEvent (QKeyEvent *e) override
void showEvent (QShowEvent *e) override
void hideEvent (QHideEvent *e) override
void mouseReleaseEvent (QMouseEvent *e) override
void regenerateGrid ()
Detailed Description
Definition at line 207 of file qtcolorpicker.cpp.
Constructor & Destructor Documentation
ColorPickerPopup()
ColorPickerPopup::ColorPickerPopup (int width, bool withColorDialog, QWidget * parent = nullptr)
Definition at line 549 of file qtcolorpicker.cpp.
References ColorPickerButton::clicked(), draftgeoutils.intersections::connect(), getColorFromDialog(), and regenerateGrid().
~ColorPickerPopup()
ColorPickerPopup::~ColorPickerPopup () override
Definition at line 581 of file qtcolorpicker.cpp.
Member Function Documentation
color()
QColor ColorPickerPopup::color (int index) const
Definition at line 646 of file qtcolorpicker.cpp.
Referenced by QtColorPicker::color().
exec()
void ColorPickerPopup::exec ()
Definition at line 658 of file qtcolorpicker.cpp.
References SCL.SimpleDataTypes::e, and bimcommands.BimViews::show().
Referenced by QtColorPicker::getColor().
find()
ColorPickerItem * ColorPickerPopup::find (const QColor & col) const
Definition at line 592 of file qtcolorpicker.cpp.
References SplineSurface::i.
Referenced by insertColor(), and QtColorPicker::setCurrentColor().
getColorFromDialog
void ColorPickerPopup::getColorFromDialog () slot
Definition at line 904 of file qtcolorpicker.cpp.
References Gui::DialogOptions::dontUseNativeColorDialog(), importDXF::getColor(), insertColor(), and selected().
Referenced by ColorPickerPopup().
hid
void ColorPickerPopup::hid () signal
Referenced by hideEvent(), and QtColorPicker::QtColorPicker().
hideEvent()
void ColorPickerPopup::hideEvent (QHideEvent * e) override protected
Definition at line 812 of file qtcolorpicker.cpp.
References SCL.SimpleDataTypes::e, and hid().
insertColor()
void ColorPickerPopup::insertColor (const QColor & col, const QString & text, int index)
Definition at line 607 of file qtcolorpicker.cpp.
References draftgeoutils.intersections::connect(), find(), lastSelected(), regenerateGrid(), ColorPickerItem::selected(), ColorPickerItem::setSelected(), and updateSelected().
Referenced by QtColorPicker::getColor(), getColorFromDialog(), and QtColorPicker::insertColor().
keyPressEvent()
void ColorPickerPopup::keyPressEvent (QKeyEvent * e) override protected
Definition at line 707 of file qtcolorpicker.cpp.
References ColorPickerItem::color(), SCL.SimpleDataTypes::e, ArchFence::hide(), SplineSurface::i, selected(), ColorPickerItem::setSelected(), and src.Mod.PartDesign.fcgear.svggear::w.
lastSelected()
QColor ColorPickerPopup::lastSelected () const
Definition at line 827 of file qtcolorpicker.cpp.
Referenced by QtColorPicker::getColor(), and insertColor().
mouseReleaseEvent()
void ColorPickerPopup::mouseReleaseEvent (QMouseEvent * e) override protected
Definition at line 697 of file qtcolorpicker.cpp.
References SCL.SimpleDataTypes::e, and ArchFence::hide().
regenerateGrid()
void ColorPickerPopup::regenerateGrid () protected
Definition at line 864 of file qtcolorpicker.cpp.
References SplineSurface::i, and KDL::sqrt().
Referenced by ColorPickerPopup(), and insertColor().
selected
void ColorPickerPopup::selected (const QColor &) signal
Referenced by getColorFromDialog(), keyPressEvent(), QtColorPicker::QtColorPicker(), and updateSelected().
setExecFlag()
void ColorPickerPopup::setExecFlag ()
setLastSel()
void ColorPickerPopup::setLastSel (const QColor & col)
Definition at line 925 of file qtcolorpicker.cpp.
Referenced by QtColorPicker::setCurrentColor().
showEvent()
void ColorPickerPopup::showEvent (QShowEvent * e) override protected
Definition at line 837 of file qtcolorpicker.cpp.
References SplineSurface::i, and src.Mod.PartDesign.fcgear.svggear::w.
updateSelected
void ColorPickerPopup::updateSelected () protected slot
Definition at line 671 of file qtcolorpicker.cpp.
References ColorPickerItem::color(), ArchFence::hide(), SplineSurface::i, selected(), ColorPickerItem::setSelected(), and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by insertColor().
The documentation for this class was generated from the following file:
qtcolorpicker.cpp