FreeCAD: Gui::Dialog::DocumentRecovery Class Reference
Gui::Dialog::DocumentRecovery Class Reference
#include <DocumentRecovery.h>
Public Member Functions
DocumentRecovery (const QList< QFileInfo > &, QWidget *parent=nullptr)
~DocumentRecovery () override
void accept () override
bool foundDocuments () const
Protected Member Functions
void closeEvent (QCloseEvent *) override
void contextMenuEvent (QContextMenuEvent *) override
QString createProjectFile (const QString &)
void cleanup (QDir &, const QList< QFileInfo > &, const QString &)
void onButtonCleanupClicked ()
void onDeleteSection ()
Detailed Description
Author
Werner Mayer
Definition at line 81 of file DocumentRecovery.h.
Constructor & Destructor Documentation
DocumentRecovery()
DocumentRecovery::DocumentRecovery (const QList< QFileInfo > & dirs, QWidget * parent = nullptr) explicit
Definition at line 174 of file DocumentRecovery.cpp.
References draftgeoutils.intersections::connect(), Gui::Dialog::DocumentRecoveryPrivate::Created, Path.Log::info(), and onButtonCleanupClicked().
~DocumentRecovery()
DocumentRecovery::~DocumentRecovery () override default
Member Function Documentation
accept()
void DocumentRecovery::accept () override
Definition at line 233 of file DocumentRecovery.cpp.
References Gui::Dialog::DocumentRecoveryCleaner::clearDirectory(), App::Application::closeDocument(), createProjectFile(), SCL.SimpleDataTypes::e, Gui::Dialog::DocumentRecoveryPrivate::Failure, FC_WARN, DrawingExample::file, App::GetApplication(), Gui::Application::getDocument(), SplineSurface::i, Path.Log::info(), Gui::Application::Instance, App::ExpressionParser::labels, App::Application::openDocuments(), Gui::Document::setModified(), and Gui::Dialog::DocumentRecoveryPrivate::Success.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
cleanup()
void DocumentRecovery::cleanup (QDir & tmp, const QList< QFileInfo > & dirs, const QString & lockFile) protected
Definition at line 562 of file DocumentRecovery.cpp.
References Gui::Dialog::DocumentRecoveryCleaner::clearDirectory().
Referenced by Path.Dressup.Gui.Boundary.TaskPanel::abort(), Path.Dressup.Gui.Tags.PathDressupTagTaskPanel::abort(), PathPythonGui.simple_edit_panel.SimpleEditPanel::abort(), Path.Dressup.Gui.Boundary.TaskPanel::accept(), Path.Dressup.Gui.Tags.PathDressupTagTaskPanel::accept(), Path.Dressup.Gui.DogboneII.TaskPanel::accept(), Path.Main.Gui.Job.TaskPanel::accept(), Path.Dressup.Gui.Dogbone.TaskPanel::accept(), Path.Op.Gui.Base.TaskPanel::accept(), onButtonCleanupClicked(), Path.Dressup.Gui.Boundary.TaskPanel::reject(), Path.Dressup.Gui.Tags.PathDressupTagTaskPanel::reject(), Path.Dressup.Gui.DogboneII.TaskPanel::reject(), Path.Main.Gui.Job.TaskPanel::reject(), Path.Dressup.Gui.Dogbone.TaskPanel::reject(), and Path.Op.Gui.Base.TaskPanel::reject().
closeEvent()
void DocumentRecovery::closeEvent (QCloseEvent * e) override protected
Definition at line 226 of file DocumentRecovery.cpp.
References SCL.SimpleDataTypes::e.
contextMenuEvent()
void DocumentRecovery::contextMenuEvent (QContextMenuEvent * ev) override protected
Definition at line 496 of file DocumentRecovery.cpp.
References src.Mod.Test.testPathArray::items, NavigationIndicatorGui::menu, and onDeleteSection().
createProjectFile()
QString DocumentRecovery::createProjectFile (const QString & documentXml) protected
Definition at line 211 of file DocumentRecovery.cpp.
References Gui::Command::App, runCommand, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by accept().
foundDocuments()
bool DocumentRecovery::foundDocuments () const
Definition at line 205 of file DocumentRecovery.cpp.
onButtonCleanupClicked()
void DocumentRecovery::onButtonCleanupClicked () protected
Definition at line 538 of file DocumentRecovery.cpp.
References draftgeoutils.faces::bind(), cleanup(), buildPsets::handler, and Gui::Dialog::DlgCheckableMessageBox::showMessage().
Referenced by DocumentRecovery().
onDeleteSection()
void DocumentRecovery::onDeleteSection () protected
Definition at line 506 of file DocumentRecovery.cpp.
References Gui::Dialog::DocumentRecoveryCleaner::clearDirectory(), App::Application::getUserCachePath(), and src.Mod.Test.testPathArray::items.
Referenced by contextMenuEvent().
The documentation for this class was generated from the following files:
DocumentRecovery.h
DocumentRecovery.cpp