FreeCAD: Gui::ManualAlignment Class Reference
Gui::ManualAlignment Class Reference
#include <ManualAlignment.h>
Classes
class Private
Public Member Functions
void setMinPoints (int minPoints)
void setFixedGroup (const FixedGroup &)
void setModel (const MovableGroupModel &)
void clearAll ()
void setViewingDirections (const Base::Vector3d &view1, const Base::Vector3d &up1, const Base::Vector3d &view2, const Base::Vector3d &up2)
void startAlignment (Base::Type mousemodel)
void finish ()
void align ()
bool canAlign () const
void cancel ()
const Base::Placement & getTransform () const
void alignObject (App::DocumentObject *)
void slotDeletedDocument (const Gui::Document &Doc)
Checks if the given object is about to be removed.
void slotDeletedObject (const Gui::ViewProvider &Obj)
Checks if the given document is about to be closed.
Static Public Member Functions
static ManualAlignment * instance ()
static void destruct ()
static bool hasInstance ()
Protected Member Functions
ManualAlignment ()
~ManualAlignment () override
bool computeAlignment (const std::vector< PickedPoint > &movPts, const std::vector< PickedPoint > &fixPts)
void continueAlignment ()
void showInstructions ()
Probe picking
bool applyPickedProbe (Gui::ViewProviderDocumentObject *, const SoPickedPoint *pnt)
static void probePickedCallback (void *ud, SoEventCallback *n)
void reset ()
void onAlign ()
void onRemoveLastPointMoveable ()
void onRemoveLastPointFixed ()
void onClear ()
void onCancel ()
void emitCanceled ()
void emitFinished ()
Detailed Description
Author
Werner Mayer
Definition at line 188 of file ManualAlignment.h.
Constructor & Destructor Documentation
ManualAlignment()
ManualAlignment::ManualAlignment () protected
Construction.
Definition at line 636 of file ManualAlignment.cpp.
References draftgeoutils.faces::bind(), Gui::Application::Instance, Gui::ManualAlignment::Private::sensorCam1, Gui::ManualAlignment::Private::sensorCam2, Gui::Application::signalDeleteDocument, slotDeletedDocument(), and Gui::ManualAlignment::Private::syncCameraCB().
Referenced by instance().
~ManualAlignment()
ManualAlignment::~ManualAlignment () override protected
Destruction.
Definition at line 653 of file ManualAlignment.cpp.
Member Function Documentation
align()
void ManualAlignment::align ()
Definition at line 939 of file ManualAlignment.cpp.
References Gui::MovableGroupModel::activeGroup(), Gui::AlignmentGroup::addToViewer(), alignObject(), Gui::Document::commitCommand(), computeAlignment(), Gui::MovableGroupModel::continueAlignment(), continueAlignment(), Gui::AlignmentGroup::countPoints(), finish(), Gui::getMainWindow(), Gui::AlignmentGroup::getPoints(), Gui::AlignmentGroup::getViews(), Gui::AlignmentGroup::moveTo(), Gui::Document::openCommand(), NavigationIndicatorGui::pView, Arch::QT_TRANSLATE_NOOP, Gui::AlignmentGroup::removeFromViewer(), Gui::AlignmentGroup::setAlignable(), Gui::MainWindow::showMessage(), and Path.Log::warning().
Referenced by ArchStairs._Stairs::makeStraightLanding(), ArchStairs._Stairs::makeStraightStairs(), ArchStairs._Stairs::makeStraightStairsWithLanding(), and onAlign().
alignObject()
void ManualAlignment::alignObject (App::DocumentObject * obj)
This method performs the actual alignment of view pView.
Definition at line 1089 of file ManualAlignment.cpp.
References Base::BaseClass::isDerivedFrom(), and App::GeoFeature::transformPlacement().
Referenced by align().
applyPickedProbe()
bool ManualAlignment::applyPickedProbe (Gui::ViewProviderDocumentObject * prov, const SoPickedPoint * pnt) protected
This method stores the picked point pnt from the view provider prov. If enough points in both windows have been picked the alignment gets invoked.
Definition at line 1305 of file ManualAlignment.cpp.
References Gui::MovableGroupModel::activeGroup(), Gui::AlignmentGroup::addPoint(), Gui::AlignmentGroup::countPoints(), Gui::ViewProvider::getModelPoints(), Gui::AlignmentGroup::hasView(), Gui::ManualAlignment::Private::picksepLeft, Gui::ManualAlignment::Private::picksepRight, Gui::PickedPoint::point, and SurfaceTests.TestBlendCurve::vec.
canAlign()
bool ManualAlignment::canAlign () const
Definition at line 1024 of file ManualAlignment.cpp.
References Gui::MovableGroupModel::activeGroup(), and Gui::AlignmentGroup::countPoints().
cancel()
void ManualAlignment::cancel ()
Cancels the process and closes the windows without performing an alignment.
Definition at line 924 of file ManualAlignment.cpp.
References emitCanceled(), Gui::getMainWindow(), reset(), and Gui::MainWindow::showMessage().
Referenced by onCancel(), and slotDeletedObject().
clearAll()
void ManualAlignment::clearAll ()
Definition at line 710 of file ManualAlignment.cpp.
References Gui::AlignmentGroup::clear(), and Gui::MovableGroupModel::clear().
computeAlignment()
bool ManualAlignment::computeAlignment (const std::vector< PickedPoint > & movPts, const std::vector< PickedPoint > & fixPts) protected
This method computes the alignment. For the calculation of the alignment the picked points of both views are taken. If the alignment fails false is returned, true otherwise.
Definition at line 1038 of file ManualAlignment.cpp.
References Base::Vector3< float_type >::Normalize(), Base::Placement::setPosition(), Gui::ManualAlignment::Private::transformation2x2(), and Gui::ManualAlignment::Private::transformation3x3().
Referenced by align().
continueAlignment()
void ManualAlignment::continueAlignment () protected
If still one view needs to be aligned then it is shown in the first window. If all views are aligned the process will be terminated.
Definition at line 847 of file ManualAlignment.cpp.
References Gui::MovableGroupModel::activeGroup(), Gui::AlignmentGroup::clearPoints(), Gui::coinRemoveAllChildren(), finish(), Gui::getMainWindow(), toolbit-attributes::grp, Gui::MovableGroupModel::isEmpty(), Gui::ManualAlignment::Private::picksepLeft, Gui::ManualAlignment::Private::picksepRight, and Gui::MainWindow::showMessage().
Referenced by align(), and startAlignment().
destruct()
void ManualAlignment::destruct () static
Destructs the one and only instance of this class.
Definition at line 676 of file ManualAlignment.cpp.
emitCanceled
void Gui::ManualAlignment::emitCanceled () signal
Referenced by cancel().
emitFinished
void Gui::ManualAlignment::emitFinished () signal
Referenced by finish().
finish()
void ManualAlignment::finish ()
Terminates the process and closes the windows.
Definition at line 905 of file ManualAlignment.cpp.
References emitFinished(), Gui::Document::getDocument(), Gui::getMainWindow(), App::Document::recompute(), reset(), and Gui::MainWindow::showMessage().
Referenced by drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::accept(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::accept(), draftguitools.gui_split.Split::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_subelements.SubelementHighlight::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rotate.Rotate::action(), draftguitools.gui_fillets.Fillet::action(), draftguitools.gui_move.Move::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_arcs.Arc::action(), draftguitools.gui_texts.Text::action(), draftguitools.gui_scale.Scale::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_trimex.Trimex::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_styles.ApplyStyle::Activated(), draftguitools.gui_join.Join::Activated(), draftguitools.gui_draft2sketch.Draft2Sketch::Activated(), draftguitools.gui_downgrade.Downgrade::Activated(), draftguitools.gui_upgrade.Upgrade::Activated(), draftguitools.gui_shape2dview.Shape2DView::Activated(), draftguitools.gui_facebinders.Facebinder::Activated(), draftguitools.gui_subelements.SubelementHighlight::Activated(), draftguitools.gui_wire2spline.WireToBSpline::Activated(), draftguitools.gui_clone.Clone::Activated(), draftguitools.gui_dimensions.Dimension::Activated(), draftguitools.gui_edit.Edit::Activated(), align(), draftguitools.gui_selectplane.Draft_SelectPlane::check_selection(), DraftGui.DraftToolBar::checkSpecialChars(), draftguitools.gui_points.Point::click(), draftguitools.gui_orthoarray.OrthoArray::completed(), draftguitools.gui_polararray.PolarArray::completed(), draftguitools.gui_circulararray.CircularArray::completed(), continueAlignment(), draftguitools.gui_labels.Label::create(), bimcommands.BimText.BIM_Text::createObject(), draftguitools.gui_rectangles.Rectangle::createObject(), draftguitools.gui_ellipses.Ellipse::createObject(), draftguitools.gui_texts.Text::createObject(), draftviewproviders.view_text.ViewProviderText::createObject(), draftguitools.gui_stretch.Stretch::doStretch(), draftguitools.gui_fillets.Fillet::draw_arc(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), DraftGui.DraftToolBar::editUi(), DraftGui.DraftToolBar::escape(), draftguitools.gui_move.Move::get_object_selection(), draftguitools.gui_rotate.Rotate::get_object_selection(), draftguitools.gui_scale.Scale::get_object_selection(), draftguitools.gui_arcs.Arc_3Points::getPoint(), draftguitools.gui_edit.Edit::keyPressed(), draftguitools.gui_dimensions.Dimension::numericInput(), draftguitools.gui_offset.Offset::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), draftguitools.gui_trimex.Trimex::numericRadius(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_align(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_auto(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_center(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_front(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_move(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_next(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_previous(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_side(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_top(), bimcommands.BimShape2DView.BIM_Shape2DView::proceed(), draftguitools.gui_join.Join::proceed(), draftguitools.gui_subelements.SubelementHighlight::proceed(), draftguitools.gui_draft2sketch.Draft2Sketch::proceed(), bimcommands.BimSlab.BIM_Slab::proceed(), draftguitools.gui_upgrade.Upgrade::proceed(), draftguitools.gui_downgrade.Downgrade::proceed(), draftguitools.gui_facebinders.Facebinder::proceed(), draftguitools.gui_pathtwistedarray.PathTwistedArray::proceed(), draftguitools.gui_shape2dview.Shape2DView::proceed(), draftguitools.gui_clone.Clone::proceed(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_pointarray.PointArray::proceed(), draftguitools.gui_patharray.PathArray::proceed(), draftguitools.gui_trimex.Trimex::proceed(), draftguitools.gui_edit.Edit::proceed(), draftguitools.gui_selectplane.Draft_SelectPlane::reject(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::reject(), drafttaskpanels.task_polararray.TaskPanelPolarArray::reject(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::reject(), and draftguitools.gui_edit.Edit::setTrackers().
getTransform()
const Base::Placement& Gui::ManualAlignment::getTransform () const inline
Definition at line 214 of file ManualAlignment.h.
hasInstance()
bool ManualAlignment::hasInstance () static
Checks whether the one instance exists.
Definition at line 688 of file ManualAlignment.cpp.
instance()
ManualAlignment * ManualAlignment::instance () static
Creates the one and only instance of this class.
Definition at line 665 of file ManualAlignment.cpp.
References ManualAlignment().
Referenced by probePickedCallback().
onAlign
void ManualAlignment::onAlign () protected slot
Definition at line 1160 of file ManualAlignment.cpp.
References align().
Referenced by probePickedCallback().
onCancel
void ManualAlignment::onCancel () protected slot
Definition at line 1192 of file ManualAlignment.cpp.
References cancel().
Referenced by probePickedCallback().
onClear
void ManualAlignment::onClear () protected slot
Definition at line 1183 of file ManualAlignment.cpp.
References Gui::MovableGroupModel::activeGroup(), Gui::AlignmentGroup::clear(), Gui::coinRemoveAllChildren(), Gui::ManualAlignment::Private::picksepLeft, and Gui::ManualAlignment::Private::picksepRight.
onRemoveLastPointFixed
void ManualAlignment::onRemoveLastPointFixed () protected slot
Definition at line 1174 of file ManualAlignment.cpp.
References Gui::AlignmentGroup::countPoints(), Gui::ManualAlignment::Private::picksepRight, and Gui::AlignmentGroup::removeLastPoint().
Referenced by probePickedCallback().
onRemoveLastPointMoveable
void ManualAlignment::onRemoveLastPointMoveable () protected slot
Definition at line 1165 of file ManualAlignment.cpp.
References Gui::MovableGroupModel::activeGroup(), Gui::AlignmentGroup::countPoints(), Gui::ManualAlignment::Private::picksepLeft, and Gui::AlignmentGroup::removeLastPoint().
Referenced by probePickedCallback().
probePickedCallback()
void ManualAlignment::probePickedCallback (void * ud, SoEventCallback * n) static protected
Definition at line 1197 of file ManualAlignment.cpp.
References Gui::getMainWindow(), instance(), NavigationIndicatorGui::menu, onAlign(), onCancel(), onRemoveLastPointFixed(), onRemoveLastPointMoveable(), RobotExample::pos, Gui::MainWindow::showMessage(), and SurfaceTests.TestBlendCurve::vec.
Referenced by startAlignment().
reset
void ManualAlignment::reset () protected slot
Make all views unpickable and resets internal data.
Definition at line 882 of file ManualAlignment.cpp.
References Gui::MovableGroupModel::activeGroup(), Gui::AlignmentGroup::clear(), Gui::MovableGroupModel::clear(), Gui::coinRemoveAllChildren(), Gui::MovableGroupModel::isEmpty(), Gui::ManualAlignment::Private::picksepLeft, Gui::ManualAlignment::Private::picksepRight, and Gui::AlignmentGroup::setAlignable().
Referenced by ArchVRM.Renderer::__init__(), cancel(), finish(), draftguitools.gui_trackers.gridTracker::set(), slotDeletedDocument(), startAlignment(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testAll(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
setFixedGroup()
void ManualAlignment::setFixedGroup (const FixedGroup & fixed)
Definition at line 699 of file ManualAlignment.cpp.
References Gui::AlignmentGroup::getDocument().
Referenced by StdCmdAlignment::activated().
setMinPoints()
void ManualAlignment::setMinPoints (int minPoints)
Definition at line 693 of file ManualAlignment.cpp.
Referenced by StdCmdAlignment::activated().
setModel()
void ManualAlignment::setModel (const MovableGroupModel & model)
Definition at line 705 of file ManualAlignment.cpp.
Referenced by StdCmdAlignment::activated().
setViewingDirections()
void ManualAlignment::setViewingDirections (const Base::Vector3d & view1, const Base::Vector3d & up1, const Base::Vector3d & view2, const Base::Vector3d & up2)
Definition at line 717 of file ManualAlignment.cpp.
References Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by StdCmdAlignment::activated().
showInstructions()
void ManualAlignment::showInstructions () protected
Definition at line 1001 of file ManualAlignment.cpp.
References Gui::MovableGroupModel::activeGroup(), Gui::AlignmentGroup::countPoints(), Gui::getMainWindow(), and Gui::MainWindow::showMessage().
slotDeletedDocument()
void ManualAlignment::slotDeletedDocument (const Gui::Document & Doc)
Checks if the given object is about to be removed.
Handle if the current document is about to being closed.
Definition at line 1129 of file ManualAlignment.cpp.
References reset().
Referenced by ManualAlignment().
slotDeletedObject()
void ManualAlignment::slotDeletedObject (const Gui::ViewProvider & Obj)
Checks if the given document is about to be closed.
Handle if the a view provider is about to being destroyed.
Definition at line 1138 of file ManualAlignment.cpp.
References Gui::MovableGroupModel::activeGroup(), cancel(), Gui::AlignmentGroup::hasView(), and Base::BaseClass::isDerivedFrom().
Referenced by startAlignment().
startAlignment()
void ManualAlignment::startAlignment (Base::Type mousemodel)
Performs the alignment for the specified aligned and non-aligned views specified by setModel() and setFixedGroup().
Definition at line 779 of file ManualAlignment.cpp.
References Gui::AlignmentGroup::addToViewer(), Gui::MainWindow::addWindow(), draftgeoutils.faces::bind(), draftgeoutils.intersections::connect(), continueAlignment(), Gui::getMainWindow(), Gui::AlignmentGroup::isEmpty(), Gui::MovableGroupModel::isEmpty(), Path.Op.Surface::msg, Gui::ManualAlignment::Private::picksepLeft, Gui::ManualAlignment::Private::picksepRight, probePickedCallback(), reset(), Gui::AlignmentGroup::setAlignable(), Gui::Document::signalDeletedObject, slotDeletedObject(), and Path.Log::warning().
Referenced by StdCmdAlignment::activated().
The documentation for this class was generated from the following files:
ManualAlignment.h
ManualAlignment.cpp