FreeCAD: CDxfRead Class Reference
CDxfRead Class Reference
#include <dxf.h>
Classes
class CommonEntityAttributes
class Layer
struct VertexInfo
Public Member Functions
CDxfRead (const std::string &filepath)
CDxfRead (const CDxfRead &)=delete
CDxfRead (const CDxfRead &&)=delete
CDxfRead & operator= (const CDxfRead &)=delete
CDxfRead & operator= (const CDxfRead &&)=delete
virtual ~CDxfRead ()
bool Failed () const
void DoRead (bool ignore_errors=false)
virtual void StartImport ()
virtual void FinishImport ()
bool IgnoreErrors () const
virtual bool OnReadBlock (const std::string &, int)
virtual void OnReadLine (const Base::Vector3d &, const Base::Vector3d &, bool)
virtual void OnReadPoint (const Base::Vector3d &)
virtual void OnReadText (const Base::Vector3d &, const double, const std::string &, const double)
virtual void OnReadArc (const Base::Vector3d &, const Base::Vector3d &, const Base::Vector3d &, bool, bool)
virtual void OnReadCircle (const Base::Vector3d &, const Base::Vector3d &, bool, bool)
virtual void OnReadEllipse (const Base::Vector3d &, double, double, double, double, double, bool)
virtual void OnReadSpline (struct SplineData &)
virtual void OnReadInsert (const Base::Vector3d &, const Base::Vector3d &, const std::string &, double)
virtual void OnReadDimension (const Base::Vector3d &, const Base::Vector3d &, const Base::Vector3d &, double)
virtual void OnReadPolyline (std::list< VertexInfo > &, int)
bool LineTypeIsHidden () const
Static Public Member Functions
static App::Color ObjectColor (ColorIndex_t colorIndex)
Protected Types
using eEntityMergeType_t = enum { MergeShapes, SingleShapes, DraftObjects }
Protected Member Functions
void SetAdditionalScaling (double scaling)
bool ExplodePolyline (std::list< VertexInfo > &, int flags)
bool ReadBlockContents ()
bool SkipBlockContents ()
virtual bool ReadEntitiesSection ()
template<typename... args>
void UnsupportedFeature (const char *format, args &&... argValues)
virtual Layer * MakeLayer (const std::string &name, ColorIndex_t color, std::string &&lineType)
Static Protected Member Functions
template<typename... args>
static void ImportError (const char *format, args &&... argValues)
template<typename... args>
static void ImportObservation (const char *format, args &&... argValues)
Protected Attributes
bool m_preserveLayers = true
bool m_preserveColors = true
eEntityMergeType_t m_mergeOption = DraftObjects
bool m_importAnnotations = true
bool m_importPoints = true
bool m_importPaperSpaceEntities = false
bool m_importHiddenBlocks = false
bool m_importFrozenLayers = false
bool m_importHiddenLayers = true
eDXFVersion_t m_version = RUnknown
std::map< std::string, Layer * > Layers
CommonEntityAttributes m_entityAttributes
Base::Matrix4D OCSOrientationTransform
Detailed Description
Definition at line 439 of file dxf.h.
Member Typedef Documentation
eEntityMergeType_t
using CDxfRead::eEntityMergeType_t = enum { MergeShapes, SingleShapes, DraftObjects } protected
Definition at line 495 of file dxf.h.
Constructor & Destructor Documentation
CDxfRead() [1/3]
CDxfRead::CDxfRead (const std::string & filepath) explicit
Definition at line 1802 of file dxf.cpp.
References ImportError().
CDxfRead() [2/3]
CDxfRead::CDxfRead (const CDxfRead &) delete
CDxfRead() [3/3]
CDxfRead::CDxfRead (const CDxfRead &&) delete
~CDxfRead()
CDxfRead::~CDxfRead () virtual
Definition at line 1813 of file dxf.cpp.
References Layers.
Member Function Documentation
DoRead()
void CDxfRead::DoRead (bool ignore_errors = false)
Definition at line 2627 of file dxf.cpp.
References eObjectType, FinishImport(), ImportError(), and StartImport().
ExplodePolyline()
bool CDxfRead::ExplodePolyline (std::list< VertexInfo > & vertices, int flags) protected
Definition at line 2404 of file dxf.cpp.
References OnReadLine().
Referenced by Import::ImpExpDxfRead::OnReadPolyline().
Failed()
bool CDxfRead::Failed () const inline
Definition at line 845 of file dxf.h.
FinishImport()
virtual void CDxfRead::FinishImport () inline virtual
Definition at line 853 of file dxf.h.
Referenced by DoRead().
IgnoreErrors()
bool CDxfRead::IgnoreErrors () const inline
Definition at line 868 of file dxf.h.
Referenced by ReadBlockContents(), ReadEntitiesSection(), and SkipBlockContents().
ImportError()
template<typename... args> static void CDxfRead::ImportError (const char * format, args &&... argValues) inline static protected
Definition at line 690 of file dxf.h.
References Base::ConsoleSingleton::Instance(), and Base::ConsoleSingleton::Warning().
Referenced by CDxfRead(), DoRead(), Import::ImpExpDxfRead::ExpandInsert(), Import::ImpExpDxfRead::OnReadBlock(), and ReadEntitiesSection().
ImportObservation()
template<typename... args> static void CDxfRead::ImportObservation (const char * format, args &&... argValues) inline static protected
Definition at line 695 of file dxf.h.
References Base::ConsoleSingleton::Instance(), and Base::ConsoleSingleton::Message().
LineTypeIsHidden()
bool CDxfRead::LineTypeIsHidden () const inline
Definition at line 922 of file dxf.h.
References CDxfRead::CommonEntityAttributes::m_LineType.
MakeLayer()
CDxfRead::Layer * CDxfRead::MakeLayer (const std::string & name, ColorIndex_t color, std::string && lineType) protected virtual
Reimplemented in Import::ImpExpDxfRead.
Definition at line 2962 of file dxf.cpp.
References Path.Post.scripts.opensbp_post::move().
Referenced by Import::ImpExpDxfRead::MakeLayer().
ObjectColor()
App::Color CDxfRead::ObjectColor (ColorIndex_t colorIndex) static
Definition at line 3036 of file dxf.cpp.
References result, and wheel().
Referenced by ImportGui::ImpExpDxfReadGui::ApplyGuiStyles(), and Import::ImpExpDxfRead::MakeLayer().
OnReadArc()
virtual void CDxfRead::OnReadArc (const Base::Vector3d & , const Base::Vector3d & , const Base::Vector3d & , bool , bool) inline virtual
Reimplemented in AreaDxfRead, and Import::ImpExpDxfRead.
Definition at line 887 of file dxf.h.
OnReadBlock()
virtual bool CDxfRead::OnReadBlock (const std::string & , int) inline virtual
Reimplemented in Import::ImpExpDxfRead.
Definition at line 873 of file dxf.h.
OnReadCircle()
virtual void CDxfRead::OnReadCircle (const Base::Vector3d & , const Base::Vector3d & , bool , bool) inline virtual
Reimplemented in Import::ImpExpDxfRead.
Definition at line 893 of file dxf.h.
OnReadDimension()
virtual void CDxfRead::OnReadDimension (const Base::Vector3d & , const Base::Vector3d & , const Base::Vector3d & , double) inline virtual
Reimplemented in Import::ImpExpDxfRead.
Definition at line 913 of file dxf.h.
OnReadEllipse()
virtual void CDxfRead::OnReadEllipse (const Base::Vector3d & , double , double , double , double , double , bool) inline virtual
Reimplemented in Import::ImpExpDxfRead.
Definition at line 898 of file dxf.h.
OnReadInsert()
virtual void CDxfRead::OnReadInsert (const Base::Vector3d & , const Base::Vector3d & , const std::string & , double) inline virtual
Reimplemented in Import::ImpExpDxfRead.
Definition at line 908 of file dxf.h.
OnReadLine()
virtual void CDxfRead::OnReadLine (const Base::Vector3d & , const Base::Vector3d & , bool) inline virtual
Reimplemented in AreaDxfRead, and Import::ImpExpDxfRead.
Definition at line 878 of file dxf.h.
Referenced by ExplodePolyline().
OnReadPoint()
virtual void CDxfRead::OnReadPoint (const Base::Vector3d &) inline virtual
Reimplemented in Import::ImpExpDxfRead.
Definition at line 880 of file dxf.h.
OnReadPolyline()
virtual void CDxfRead::OnReadPolyline (std::list< VertexInfo > & , int) inline virtual
Reimplemented in Import::ImpExpDxfRead.
Definition at line 918 of file dxf.h.
OnReadSpline()
virtual void CDxfRead::OnReadSpline (struct SplineData &) inline virtual
Reimplemented in Import::ImpExpDxfRead.
Definition at line 906 of file dxf.h.
OnReadText()
virtual void CDxfRead::OnReadText (const Base::Vector3d & , const double , const std::string & , const double) inline virtual
Reimplemented in Import::ImpExpDxfRead.
Definition at line 882 of file dxf.h.
operator=() [1/2]
CDxfRead& CDxfRead::operator= (const CDxfRead &&) delete
operator=() [2/2]
CDxfRead& CDxfRead::operator= (const CDxfRead &) delete
ReadBlockContents()
bool CDxfRead::ReadBlockContents () protected
Definition at line 2304 of file dxf.cpp.
References eObjectType, and IgnoreErrors().
Referenced by Import::ImpExpDxfRead::OnReadBlock().
ReadEntitiesSection()
bool CDxfRead::ReadEntitiesSection () protected virtual
Reimplemented in Import::ImpExpDxfRead.
Definition at line 2898 of file dxf.cpp.
References SCL.SimpleDataTypes::e, eObjectType, IgnoreErrors(), and ImportError().
Referenced by Import::ImpExpDxfRead::ReadEntitiesSection().
SetAdditionalScaling()
void CDxfRead::SetAdditionalScaling (double scaling) inline protected
Definition at line 460 of file dxf.h.
References importers.exportIFCStructuralTools::scaling.
Referenced by Import::ImpExpDxfRead::setOptions().
SkipBlockContents()
bool CDxfRead::SkipBlockContents () protected
Definition at line 2324 of file dxf.cpp.
References eObjectType, and IgnoreErrors().
Referenced by Import::ImpExpDxfRead::OnReadBlock().
StartImport()
virtual void CDxfRead::StartImport () inline virtual
Definition at line 851 of file dxf.h.
Referenced by DoRead().
UnsupportedFeature()
template<typename... args> void CDxfRead::UnsupportedFeature (const char * format, args &&... argValues) protected
Definition at line 2342 of file dxf.cpp.
Referenced by Import::ImpExpDxfRead::OnReadBlock().
Member Data Documentation
Layers
std::map<std::string, Layer*> CDxfRead::Layers protected
Definition at line 743 of file dxf.h.
Referenced by Import::ImpExpDxfRead::ReadEntitiesSection(), and ~CDxfRead().
m_entityAttributes
CommonEntityAttributes CDxfRead::m_entityAttributes protected
Definition at line 816 of file dxf.h.
Referenced by ImportGui::ImpExpDxfReadGui::ApplyGuiStyles(), Import::ImpExpDxfRead::ExpandInsert(), and Import::ImpExpDxfRead::ReadEntitiesSection().
m_importAnnotations
bool CDxfRead::m_importAnnotations = true protected
Definition at line 514 of file dxf.h.
Referenced by Import::ImpExpDxfRead::OnReadDimension(), Import::ImpExpDxfRead::OnReadText(), and Import::ImpExpDxfRead::setOptions().
m_importFrozenLayers
bool CDxfRead::m_importFrozenLayers = false protected
Definition at line 523 of file dxf.h.
m_importHiddenBlocks
bool CDxfRead::m_importHiddenBlocks = false protected
Definition at line 521 of file dxf.h.
Referenced by Import::ImpExpDxfRead::OnReadBlock(), and Import::ImpExpDxfRead::setOptions().
m_importHiddenLayers
bool CDxfRead::m_importHiddenLayers = true protected
Definition at line 526 of file dxf.h.
m_importPaperSpaceEntities
bool CDxfRead::m_importPaperSpaceEntities = false protected
Definition at line 518 of file dxf.h.
Referenced by Import::ImpExpDxfRead::setOptions().
m_importPoints
bool CDxfRead::m_importPoints = true protected
Definition at line 516 of file dxf.h.
Referenced by Import::ImpExpDxfRead::setOptions().
m_mergeOption
eEntityMergeType_t CDxfRead::m_mergeOption = DraftObjects protected
Definition at line 508 of file dxf.h.
Referenced by Import::ImpExpDxfRead::ReadEntitiesSection(), and Import::ImpExpDxfRead::setOptions().
m_preserveColors
bool CDxfRead::m_preserveColors = true protected
Definition at line 484 of file dxf.h.
Referenced by Import::ImpExpDxfRead::setOptions().
m_preserveLayers
bool CDxfRead::m_preserveLayers = true protected
Definition at line 479 of file dxf.h.
Referenced by Import::ImpExpDxfRead::MakeLayer(), Import::ImpExpDxfRead::ReadEntitiesSection(), and Import::ImpExpDxfRead::setOptions().
m_version
eDXFVersion_t CDxfRead::m_version = RUnknown protected
Definition at line 674 of file dxf.h.
OCSOrientationTransform
Base::Matrix4D CDxfRead::OCSOrientationTransform protected
Definition at line 834 of file dxf.h.
The documentation for this class was generated from the following files:
dxf.h
dxf.cpp