FreeCAD: Gui::UndoAction Class Reference
Gui::UndoAction Class Reference
#include <Action.h>
Public Member Functions
UndoAction (Command *pcCmd, QObject *parent=nullptr)
~UndoAction () override
void addTo (QWidget *widget) override
void setEnabled (bool) override
void setVisible (bool) override
Public Member Functions inherited from Gui::Action
Action (Command *pcCmd, QObject *parent=nullptr)
Action (Command *pcCmd, QAction *action, QObject *parent)
Action takes ownership of the 'action' object.
~Action () override
void setCheckable (bool)
void setChecked (bool, bool no_signal=false)
bool isChecked () const
bool isEnabled () const
void setShortcut (const QString &)
QKeySequence shortcut () const
void setIcon (const QIcon &)
QIcon icon () const
void setStatusTip (const QString &)
QString statusTip () const
void setText (const QString &)
QString text () const
void setToolTip (const QString &, const QString &title=QString())
QString toolTip () const
void setWhatsThis (const QString &)
QString whatsThis () const
void setMenuRole (QAction::MenuRole menuRole)
QAction * action () const
Command * command () const
Additional Inherited Members
Public Slots inherited from Gui::Action
virtual void onActivated ()
virtual void onToggled (bool)
Static Public Member Functions inherited from Gui::Action
static QString createToolTip (QString helpText, const QString &title, const QFont &font, const QString &shortCut, const Command *command=nullptr)
static QString commandToolTip (const Command *cmd, bool richFormat=true)
static QString commandMenuText (const Command *cmd)
static QString cleanTitle (const QString &title)
Clean the title by stripping the mnemonic symbol '&' and ending punctuation.
Detailed Description
The UndoAction class reimplements a special behaviour to make a menu appearing when the button with the arrow is clicked.
Author
Werner Mayer
Definition at line 319 of file Action.h.
Constructor & Destructor Documentation
UndoAction()
UndoAction::UndoAction (Command * pcCmd, QObject * parent = nullptr) explicit
Definition at line 1210 of file Action.cpp.
References draftgeoutils.intersections::connect(), and Gui::Action::onActivated().
~UndoAction()
UndoAction::~UndoAction () override
Definition at line 1218 of file Action.cpp.
References NavigationIndicatorGui::menu.
Member Function Documentation
addTo()
void UndoAction::addTo (QWidget * widget) override virtual
Adds this action to widget widget.
Reimplemented from Gui::Action.
Definition at line 1225 of file Action.cpp.
References Gui::Action::action(), and draftgeoutils.intersections::connect().
Referenced by src.Mod.PartDesign.WizardShaft.Shaft.Shaft::equilibrium().
setEnabled()
void UndoAction::setEnabled (bool enable) override virtual
Sets whether the action is enabled.
Reimplemented from Gui::Action.
Definition at line 1249 of file Action.cpp.
References ArchCommands::check(), and Gui::Action::setEnabled().
Referenced by Path.Dressup.Gui.Tags.HoldingTagMarker::setSelected().
setVisible()
void UndoAction::setVisible (bool check) override virtual
Reimplemented from Gui::Action.
Definition at line 1255 of file Action.cpp.
References ArchCommands::check(), and Gui::Action::setVisible().
The documentation for this class was generated from the following files:
Action.h
Action.cpp