FreeCAD: Base::ParameterGrpPy Class Reference
Base::ParameterGrpPy Class Reference
Public Member Functions
ParameterGrpPy (const Base::Reference< ParameterGrp > &rcParamGrp)
~ParameterGrpPy () override
Py::Object repr () override
Py::Object getGroup (const Py::Tuple &)
Py::Object getGroupName (const Py::Tuple &)
Py::Object getGroups (const Py::Tuple &)
Py::Object remGroup (const Py::Tuple &)
Py::Object hasGroup (const Py::Tuple &)
Py::Object renameGroup (const Py::Tuple &)
Py::Object copyTo (const Py::Tuple &)
Py::Object getManager (const Py::Tuple &)
Py::Object getParent (const Py::Tuple &)
Py::Object isEmpty (const Py::Tuple &)
Py::Object clear (const Py::Tuple &)
Py::Object attach (const Py::Tuple &)
Py::Object attachManager (const Py::Tuple &args)
Py::Object detach (const Py::Tuple &)
Py::Object notify (const Py::Tuple &)
Py::Object notifyAll (const Py::Tuple &)
Py::Object setBool (const Py::Tuple &)
Py::Object getBool (const Py::Tuple &)
Py::Object getBools (const Py::Tuple &)
Py::Object remBool (const Py::Tuple &)
Py::Object setInt (const Py::Tuple &)
Py::Object getInt (const Py::Tuple &)
Py::Object getInts (const Py::Tuple &)
Py::Object remInt (const Py::Tuple &)
Py::Object setUnsigned (const Py::Tuple &)
Py::Object getUnsigned (const Py::Tuple &)
Py::Object getUnsigneds (const Py::Tuple &)
Py::Object remUnsigned (const Py::Tuple &)
Py::Object setFloat (const Py::Tuple &)
Py::Object getFloat (const Py::Tuple &)
Py::Object getFloats (const Py::Tuple &)
Py::Object remFloat (const Py::Tuple &)
Py::Object setString (const Py::Tuple &)
Py::Object getString (const Py::Tuple &)
Py::Object getStrings (const Py::Tuple &)
Py::Object remString (const Py::Tuple &)
Py::Object importFrom (const Py::Tuple &)
Py::Object insert (const Py::Tuple &)
Py::Object exportTo (const Py::Tuple &)
Py::Object getContents (const Py::Tuple &)
Static Public Member Functions
static void init_type ()
Detailed Description
Definition at line 125 of file ParameterPy.cpp.
Constructor & Destructor Documentation
ParameterGrpPy()
Base::ParameterGrpPy::ParameterGrpPy (const Base::Reference< ParameterGrp > & rcParamGrp) explicit
Definition at line 283 of file ParameterPy.cpp.
~ParameterGrpPy()
Base::ParameterGrpPy::~ParameterGrpPy () override
Definition at line 287 of file ParameterPy.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, and ParameterGrp::importFrom().
Member Function Documentation
attach()
Py::Object Base::ParameterGrpPy::attach (const Py::Tuple & args)
Definition at line 758 of file ParameterPy.cpp.
Referenced by Path.Dressup.Gui.Boundary.DressupPathBoundaryViewProvider::__init__().
attachManager()
Py::Object Base::ParameterGrpPy::attachManager (const Py::Tuple & args)
Definition at line 803 of file ParameterPy.cpp.
References src.Mod.Test.testPathArray::o.
clear()
Py::Object Base::ParameterGrpPy::clear (const Py::Tuple & args)
Definition at line 706 of file ParameterPy.cpp.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), and src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__().
copyTo()
Py::Object Base::ParameterGrpPy::copyTo (const Py::Tuple & args)
Definition at line 746 of file ParameterPy.cpp.
detach()
Py::Object Base::ParameterGrpPy::detach (const Py::Tuple & args)
Definition at line 851 of file ParameterPy.cpp.
exportTo()
Py::Object Base::ParameterGrpPy::exportTo (const Py::Tuple & args)
Definition at line 342 of file ParameterPy.cpp.
getBool()
Py::Object Base::ParameterGrpPy::getBool (const Py::Tuple & args)
Definition at line 459 of file ParameterPy.cpp.
getBools()
Py::Object Base::ParameterGrpPy::getBools (const Py::Tuple & args)
Definition at line 470 of file ParameterPy.cpp.
getContents()
Py::Object Base::ParameterGrpPy::getContents (const Py::Tuple & args)
Definition at line 897 of file ParameterPy.cpp.
References src.Mod.Test.testmakeWireString::String, and src.Mod.PartDesign.Scripts.Gear::t3.
getFloat()
Py::Object Base::ParameterGrpPy::getFloat (const Py::Tuple & args)
Definition at line 574 of file ParameterPy.cpp.
getFloats()
Py::Object Base::ParameterGrpPy::getFloats (const Py::Tuple & args)
Definition at line 585 of file ParameterPy.cpp.
getGroup()
Py::Object Base::ParameterGrpPy::getGroup (const Py::Tuple & args)
Definition at line 359 of file ParameterPy.cpp.
getGroupName()
Py::Object Base::ParameterGrpPy::getGroupName (const Py::Tuple & args)
Definition at line 420 of file ParameterPy.cpp.
getGroups()
Py::Object Base::ParameterGrpPy::getGroups (const Py::Tuple & args)
Definition at line 431 of file ParameterPy.cpp.
getInt()
Py::Object Base::ParameterGrpPy::getInt (const Py::Tuple & args)
Definition at line 498 of file ParameterPy.cpp.
getInts()
Py::Object Base::ParameterGrpPy::getInts (const Py::Tuple & args)
Definition at line 508 of file ParameterPy.cpp.
getManager()
Py::Object Base::ParameterGrpPy::getManager (const Py::Tuple & args)
Definition at line 384 of file ParameterPy.cpp.
getParent()
Py::Object Base::ParameterGrpPy::getParent (const Py::Tuple & args)
Definition at line 402 of file ParameterPy.cpp.
getString()
Py::Object Base::ParameterGrpPy::getString (const Py::Tuple & args)
Definition at line 613 of file ParameterPy.cpp.
getStrings()
Py::Object Base::ParameterGrpPy::getStrings (const Py::Tuple & args)
Definition at line 624 of file ParameterPy.cpp.
Referenced by draftguitools.gui_rectangles.Rectangle::createObject(), draftguitools.gui_ellipses.Ellipse::createObject(), draftguitools.gui_texts.Text::createObject(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), draftguitools.gui_lines.Line::finish(), draftguitools.gui_splines.BSpline::finish(), draftguitools.gui_beziers.BezCurve::finish(), and draftguitools.gui_beziers.CubicBezCurve::finish().
getUnsigned()
Py::Object Base::ParameterGrpPy::getUnsigned (const Py::Tuple & args)
Definition at line 536 of file ParameterPy.cpp.
getUnsigneds()
Py::Object Base::ParameterGrpPy::getUnsigneds (const Py::Tuple & args)
Definition at line 546 of file ParameterPy.cpp.
hasGroup()
Py::Object Base::ParameterGrpPy::hasGroup (const Py::Tuple & args)
Definition at line 725 of file ParameterPy.cpp.
References toolbit-attributes::args, ParameterGrp::copyTo(), and toolbit-attributes::grp.
importFrom()
Py::Object Base::ParameterGrpPy::importFrom (const Py::Tuple & args)
Definition at line 308 of file ParameterPy.cpp.
init_type()
void Base::ParameterGrpPy::init_type () static
Definition at line 202 of file ParameterPy.cpp.
Referenced by GetPyObject(), and Base::ParameterGrpObserver::~ParameterGrpObserver().
insert()
Py::Object Base::ParameterGrpPy::insert (const Py::Tuple & args)
Definition at line 325 of file ParameterPy.cpp.
isEmpty()
Py::Object Base::ParameterGrpPy::isEmpty (const Py::Tuple & args)
Definition at line 716 of file ParameterPy.cpp.
notify()
Py::Object Base::ParameterGrpPy::notify (const Py::Tuple & args)
Definition at line 876 of file ParameterPy.cpp.
References toolbit-attributes::args, and ParameterGrp::IsEmpty().
notifyAll()
Py::Object Base::ParameterGrpPy::notifyAll (const Py::Tuple & args)
Definition at line 887 of file ParameterPy.cpp.
References src.Mod.Test.testmakeWireString::String, and src.Mod.PartDesign.Scripts.Gear::t2.
remBool()
Py::Object Base::ParameterGrpPy::remBool (const Py::Tuple & args)
Definition at line 662 of file ParameterPy.cpp.
References toolbit-attributes::args, and ParameterGrp::RemoveFloat().
remFloat()
Py::Object Base::ParameterGrpPy::remFloat (const Py::Tuple & args)
Definition at line 684 of file ParameterPy.cpp.
References toolbit-attributes::args, and ParameterGrp::Clear().
remGroup()
Py::Object Base::ParameterGrpPy::remGroup (const Py::Tuple & args)
Definition at line 673 of file ParameterPy.cpp.
References toolbit-attributes::args, and ParameterGrp::RemoveASCII().
remInt()
Py::Object Base::ParameterGrpPy::remInt (const Py::Tuple & args)
Definition at line 640 of file ParameterPy.cpp.
References toolbit-attributes::args, and ParameterGrp::RemoveBool().
remString()
Py::Object Base::ParameterGrpPy::remString (const Py::Tuple & args)
Definition at line 695 of file ParameterPy.cpp.
References toolbit-attributes::args, and ParameterGrp::IsEmpty().
remUnsigned()
Py::Object Base::ParameterGrpPy::remUnsigned (const Py::Tuple & args)
Definition at line 651 of file ParameterPy.cpp.
References toolbit-attributes::args, and ParameterGrp::RemoveGrp().
renameGroup()
Py::Object Base::ParameterGrpPy::renameGroup (const Py::Tuple & args)
Definition at line 735 of file ParameterPy.cpp.
repr()
Py::Object Base::ParameterGrpPy::repr () override
Definition at line 301 of file ParameterPy.cpp.
setBool()
Py::Object Base::ParameterGrpPy::setBool (const Py::Tuple & args)
Definition at line 447 of file ParameterPy.cpp.
setFloat()
Py::Object Base::ParameterGrpPy::setFloat (const Py::Tuple & args)
Definition at line 562 of file ParameterPy.cpp.
setInt()
Py::Object Base::ParameterGrpPy::setInt (const Py::Tuple & args)
Definition at line 486 of file ParameterPy.cpp.
References toolbit-attributes::args, ParameterGrp::GetIntMap(), and src.Mod.Test.testmakeWireString::String.
setString()
Py::Object Base::ParameterGrpPy::setString (const Py::Tuple & args)
Definition at line 601 of file ParameterPy.cpp.
Referenced by draftguitools.gui_trackers.archDimTracker::p1(), and draftguitools.gui_trackers.archDimTracker::p2().
setUnsigned()
Py::Object Base::ParameterGrpPy::setUnsigned (const Py::Tuple & args)
Definition at line 524 of file ParameterPy.cpp.
References toolbit-attributes::args, ParameterGrp::GetUnsignedMap(), and src.Mod.Test.testmakeWireString::String.
The documentation for this class was generated from the following file:
ParameterPy.cpp