FreeCAD: femtools.geomtools Namespace Reference
femtools.geomtools Namespace Reference
Functions
def find_element_in_shape (aShape, anElement)
def get_vertexes_by_element (aShape, anElement)
def is_same_geometry (shape1, shape2)
def get_element (part, element)
Function Documentation
find_element_in_shape()
def femtools.geomtools.find_element_in_shape (aShape, anElement)
Definition at line 32 of file geomtools.py.
References femtools.geomtools.is_same_geometry(), and Path.Post.scripts.refactored_centroid_post.str.
get_element()
def femtools.geomtools.get_element (part, element)
Definition at line 166 of file geomtools.py.
get_vertexes_by_element()
def femtools.geomtools.get_vertexes_by_element (aShape, anElement)
Definition at line 84 of file geomtools.py.
References femtools.geomtools.is_same_geometry(), and Path.Post.scripts.refactored_centroid_post.str.
is_same_geometry()
def femtools.geomtools.is_same_geometry (shape1, shape2)
Definition at line 130 of file geomtools.py.
Referenced by femtools.geomtools.find_element_in_shape(), and femtools.geomtools.get_vertexes_by_element().