FreeCAD: DrawSketchHandlerRectangularArray Class Reference
DrawSketchHandlerRectangularArray Class Reference
Public Types
enum SelectMode { STATUS_SEEK_First, STATUS_End }
mode table
enum SnapMode { SnapMode::Free, SnapMode::Snap5Degree }
Public Member Functions
DrawSketchHandlerRectangularArray (string geoidlist, int origingeoid, Sketcher::PointPos originpos, int nelements, bool clone, int rows, int cols, bool constraintSeparation, bool equalVerticalHorizontalSpacing)
~DrawSketchHandlerRectangularArray () override
void mouseMove (Base::Vector2d onSketchPos) override
bool pressButton (Base::Vector2d) override
bool releaseButton (Base::Vector2d onSketchPos) override
Public Member Functions inherited from SketcherGui::DrawSketchHandler
DrawSketchHandler ()
virtual ~DrawSketchHandler ()
void activate (ViewProviderSketch *)
void deactivate () override
virtual void registerPressedKey (bool pressed, int key)
virtual void pressRightButton (Base::Vector2d pos)
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
void quit () override
int getHighestVertexIndex ()
int getHighestCurveIndex ()
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
int seekAndRenderAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::PointPos::none, bool createowncommand=true)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
void setPositionText (const Base::Vector2d &Pos)
void resetPositionText ()
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void toolWidgetChanged (QWidget *newwidget)
Slot to receive signaling that a widget intended for the tool has changed and is available ant the provided pointer.
std::unique_ptr< QWidget > createToolWidget () const
Factory function returning a tool widget of the type necessary for the specific tool. This is a NVI interface and specific handlers must overload the corresponding virtual function.
bool isToolWidgetVisible () const
Returns whether this tool expects/supports a visible tool widget. Emphasis is in visibility, so to allow one to adapt the interface accordingly. This is an NVI interface and specific handlers must overload the corresponding virtual function.
QPixmap getToolWidgetHeaderIcon () const
Returns a pixmap icon intended for a visible tool widget. This is an NVI interface and specific handlers must overload the corresponding virtual function.
QString getToolWidgetHeaderText () const
Returns a header text intended for a visible tool widget. This is an NVI interface and specific handlers must overload the corresponding virtual function.
Public Member Functions inherited from Gui::ToolHandler
ToolHandler ()=default
virtual ~ToolHandler ()=default
bool activate ()
void updateCursor ()
Protected Attributes
SelectMode Mode
SnapMode snapMode
string geoIdList
Base::Vector3d Origin
int OriginGeoId
Sketcher::PointPos OriginPos
int nElements
bool Clone
int Rows
int Cols
bool ConstraintSeparation
bool EqualVerticalHorizontalSpacing
std::vector< Base::Vector2d > EditCurve
std::vector< AutoConstraint > sugConstr1
Protected Attributes inherited from SketcherGui::DrawSketchHandler
ViewProviderSketch * sketchgui
QWidget * toolwidget
Protected Attributes inherited from Gui::ToolHandler
QCursor oldCursor
QCursor actCursor
QPixmap actCursorPixmap
Additional Inherited Members
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
virtual std::string getToolName () const
virtual std::unique_ptr< QWidget > createWidget () const
virtual bool isWidgetVisible () const
virtual QPixmap getToolIcon () const
virtual QString getToolWidgetText () const
void drawEdit (const std::vector< Base::Vector2d > &EditCurve) const
void drawEdit (const std::list< std::vector< Base::Vector2d >> &list) const
void drawEdit (const std::vector< Part::Geometry * > &geometries) const
void drawEditMarkers (const std::vector< Base::Vector2d > &EditMarkers, unsigned int augmentationlevel=0) const
void clearEdit () const
void clearEditMarkers () const
void setAxisPickStyle (bool on)
void moveCursorToSketchPoint (Base::Vector2d point)
void ensureFocus ()
void preselectAtPoint (Base::Vector2d point)
void drawPositionAtCursor (const Base::Vector2d &position)
void drawDirectionAtCursor (const Base::Vector2d &position, const Base::Vector2d &origin)
void drawWidthHeightAtCursor (const Base::Vector2d &position, const double val1, const double val2)
void drawDoubleAtCursor (const Base::Vector2d &position, const double radius, Base::Unit unit=Base::Unit::Length)
int getPreselectPoint () const
int getPreselectCurve () const
int getPreselectCross () const
Sketcher::SketchObject * getSketchObject ()
void setAngleSnapping (bool enable, Base::Vector2d referencePoint=Base::Vector2d(0., 0.))
void moveConstraint (int constNum, const Base::Vector2d &toPos)
void signalToolChanged () const
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Protected Member Functions inherited from Gui::ToolHandler
virtual QString getCrosshairCursorSVGName () const
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
void unsetCursor ()
void applyCursor ()
restitutes the DSH cached cursor (without any tail due to autoconstraints, ...)
void addCursorTail (std::vector< QPixmap > &pixmaps)
unsigned long getCrosshairColor ()
returns the color to be used for the crosshair (configurable as a parameter)
qreal devicePixelRatio ()
functions to set the cursor to a given svgName (to be migrated to NVI style)
View3DInventorViewer * getViewer ()
virtual QWidget * getCursorWidget ()
virtual void setWidgetCursor (QCursor cursor)
Detailed Description
Definition at line 1746 of file CommandSketcherTools.cpp.
Member Enumeration Documentation
SelectMode
enum DrawSketchHandlerRectangularArray::SelectMode
mode table
Enumerator
STATUS_SEEK_First
STATUS_End
Definition at line 1770 of file CommandSketcherTools.cpp.
SnapMode
enum DrawSketchHandlerRectangularArray::SnapMode strong
Enumerator
Free
Snap5Degree
Definition at line 1776 of file CommandSketcherTools.cpp.
Constructor & Destructor Documentation
DrawSketchHandlerRectangularArray()
DrawSketchHandlerRectangularArray::DrawSketchHandlerRectangularArray (string geoidlist, int origingeoid, Sketcher::PointPos originpos, int nelements, bool clone, int rows, int cols, bool constraintSeparation, bool equalVerticalHorizontalSpacing) inline
Definition at line 1749 of file CommandSketcherTools.cpp.
~DrawSketchHandlerRectangularArray()
DrawSketchHandlerRectangularArray::~DrawSketchHandlerRectangularArray () inline override
Definition at line 1767 of file CommandSketcherTools.cpp.
Member Function Documentation
mouseMove()
void DrawSketchHandlerRectangularArray::mouseMove (Base::Vector2d onSketchPos) inline override virtual
Implements SketcherGui::DrawSketchHandler.
Definition at line 1782 of file CommandSketcherTools.cpp.
References DraftVecUtils::angle(), FreeCADInit::Angle, SketcherGui::angleToDisplayFormat(), Gui::ToolHandler::applyCursor(), KDL::cos(), SketcherGui::DrawSketchHandler::drawEdit(), EditCurve, Free, length(), FreeCADInit::Length, SketcherGui::lengthToDisplayFormat(), M_PI, Mode, SketcherGui::DrawSketchHandler::renderSuggestConstraintsCursor(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), SketcherGui::DrawSketchHandler::setPositionText(), SketcherGui::showCursorCoords(), KDL::sin(), Snap5Degree, snapMode, STATUS_SEEK_First, sugConstr1, and ZVALUE::VERTEX.
pressButton()
bool DrawSketchHandlerRectangularArray::pressButton (Base::Vector2d) inline override virtual
Implements SketcherGui::DrawSketchHandler.
Definition at line 1820 of file CommandSketcherTools.cpp.
References SketcherGui::DrawSketchHandler::drawEdit(), EditCurve, Mode, STATUS_End, and STATUS_SEEK_First.
releaseButton()
bool DrawSketchHandlerRectangularArray::releaseButton (Base::Vector2d onSketchPos) inline override virtual
Implements SketcherGui::DrawSketchHandler.
Definition at line 1829 of file CommandSketcherTools.cpp.
References Gui::Command::abortCommand(), Clone, Gui::cmdAppObjectArgs(), Cols, Gui::Command::commitCommand(), ConstraintSeparation, SketcherGui::DrawSketchHandler::createAutoConstraints(), SketcherGui::DrawSketchHandler::drawEdit(), SCL.SimpleDataTypes::e, EditCurve, EqualVerticalHorizontalSpacing, geoIdList, Gui::ViewProviderDocumentObject::getObject(), Mode, nElements, Gui::NotifyUserError(), Gui::Command::openCommand(), OriginGeoId, OriginPos, SketcherGui::ViewProviderSketch::purgeHandler(), Arch::QT_TRANSLATE_NOOP, SketcherGui::DrawSketchHandler::resetPositionText(), Rows, SketcherGui::DrawSketchHandler::sketchgui, STATUS_End, sugConstr1, SketcherGui::tryAutoRecomputeIfNotSolve(), Gui::ToolHandler::unsetCursor(), Base::Vector2d::x, and Base::Vector2d::y.
Member Data Documentation
Clone
bool DrawSketchHandlerRectangularArray::Clone protected
Definition at line 1893 of file CommandSketcherTools.cpp.
Referenced by releaseButton().
Cols
int DrawSketchHandlerRectangularArray::Cols protected
Definition at line 1895 of file CommandSketcherTools.cpp.
Referenced by releaseButton().
ConstraintSeparation
bool DrawSketchHandlerRectangularArray::ConstraintSeparation protected
Definition at line 1896 of file CommandSketcherTools.cpp.
Referenced by releaseButton().
EditCurve
std::vector<Base::Vector2d> DrawSketchHandlerRectangularArray::EditCurve protected
Definition at line 1898 of file CommandSketcherTools.cpp.
Referenced by mouseMove(), pressButton(), and releaseButton().
EqualVerticalHorizontalSpacing
bool DrawSketchHandlerRectangularArray::EqualVerticalHorizontalSpacing protected
Definition at line 1897 of file CommandSketcherTools.cpp.
Referenced by releaseButton().
geoIdList
string DrawSketchHandlerRectangularArray::geoIdList protected
Definition at line 1888 of file CommandSketcherTools.cpp.
Referenced by releaseButton().
Mode
SelectMode DrawSketchHandlerRectangularArray::Mode protected
Definition at line 1886 of file CommandSketcherTools.cpp.
Referenced by mouseMove(), pressButton(), and releaseButton().
nElements
int DrawSketchHandlerRectangularArray::nElements protected
Definition at line 1892 of file CommandSketcherTools.cpp.
Referenced by releaseButton().
Origin
Base::Vector3d DrawSketchHandlerRectangularArray::Origin protected
Definition at line 1889 of file CommandSketcherTools.cpp.
OriginGeoId
int DrawSketchHandlerRectangularArray::OriginGeoId protected
Definition at line 1890 of file CommandSketcherTools.cpp.
Referenced by releaseButton().
OriginPos
Sketcher::PointPos DrawSketchHandlerRectangularArray::OriginPos protected
Definition at line 1891 of file CommandSketcherTools.cpp.
Referenced by releaseButton().
Rows
int DrawSketchHandlerRectangularArray::Rows protected
Definition at line 1894 of file CommandSketcherTools.cpp.
Referenced by releaseButton().
snapMode
SnapMode DrawSketchHandlerRectangularArray::snapMode protected
Definition at line 1887 of file CommandSketcherTools.cpp.
Referenced by mouseMove().
sugConstr1
std::vector<AutoConstraint> DrawSketchHandlerRectangularArray::sugConstr1 protected
Definition at line 1899 of file CommandSketcherTools.cpp.
Referenced by mouseMove(), and releaseButton().
The documentation for this class was generated from the following file:
CommandSketcherTools.cpp