FreeCAD: Part::GeometryExtension Class Reference
Part::GeometryExtension Class Reference abstract
#include <GeometryExtension.h>
Public Member Functions
~GeometryExtension () override=default
virtual std::unique_ptr< GeometryExtension > copy () const =0
PyObject * getPyObject () override=0
PyObject * copyPyObject () const
void setName (const std::string &str)
const std::string & getName () const
virtual void notifyAttachment (Part::Geometry *)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
GeometryExtension ()
GeometryExtension (const GeometryExtension &obj)=default
GeometryExtension & operator= (const GeometryExtension &obj)=default
virtual void copyAttributes (Part::GeometryExtension *cpy) const
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 57 of file GeometryExtension.h.
Constructor & Destructor Documentation
~GeometryExtension()
Part::GeometryExtension::~GeometryExtension () override default
GeometryExtension() [1/2]
GeometryExtension::GeometryExtension () protected default
GeometryExtension() [2/2]
Part::GeometryExtension::GeometryExtension (const GeometryExtension & obj) protected default
Member Function Documentation
copy()
virtual std::unique_ptr<GeometryExtension> Part::GeometryExtension::copy () const pure virtual
Implemented in Sketcher::SolverGeometryExtension, Sketcher::SketchGeometryExtension, Sketcher::ExternalGeometryExtension, Part::GeometryMigrationExtension, Part::GeometryDefaultExtension< T >, and SketcherGui::ViewProviderSketchGeometryExtension.
Referenced by copyPyObject().
copyAttributes()
void GeometryExtension::copyAttributes (Part::GeometryExtension * cpy) const protected virtual
Reimplemented in Sketcher::SolverGeometryExtension, Sketcher::SketchGeometryExtension, Sketcher::ExternalGeometryExtension, Part::GeometryMigrationExtension, SketcherGui::ViewProviderSketchGeometryExtension, and Part::GeometryDefaultExtension< T >.
Definition at line 45 of file GeometryExtension.cpp.
References getName(), and setName().
Referenced by Part::GeometryDefaultExtension< T >::copyAttributes(), SketcherGui::ViewProviderSketchGeometryExtension::copyAttributes(), Part::GeometryMigrationExtension::copyAttributes(), Sketcher::ExternalGeometryExtension::copyAttributes(), Sketcher::SketchGeometryExtension::copyAttributes(), and Sketcher::SolverGeometryExtension::copyAttributes().
copyPyObject()
PyObject * GeometryExtension::copyPyObject () const
Definition at line 38 of file GeometryExtension.cpp.
References copy(), and getPyObject().
getName()
const std::string& Part::GeometryExtension::getName () const inline
Definition at line 69 of file GeometryExtension.h.
References TYPESYSTEM_HEADER_WITH_OVERRIDE.
Referenced by copyAttributes(), and Part::GeometryPersistenceExtension::saveAttributes().
getPyObject()
PyObject* Part::GeometryExtension::getPyObject () override pure virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Implemented in Sketcher::SolverGeometryExtension, Sketcher::SketchGeometryExtension, Sketcher::ExternalGeometryExtension, Part::GeometryMigrationExtension, Part::GeometryDefaultExtension< T >, SketcherGui::ViewProviderSketchGeometryExtension, Part::GeometryDefaultExtension< T >, Part::GeometryDefaultExtension< T >, Part::GeometryDefaultExtension< T >, and Part::GeometryDefaultExtension< T >.
Referenced by copyPyObject().
notifyAttachment()
virtual void Part::GeometryExtension::notifyAttachment (Part::Geometry *) inline virtual
Reimplemented in Sketcher::SolverGeometryExtension.
Definition at line 73 of file GeometryExtension.h.
operator=()
GeometryExtension& Part::GeometryExtension::operator= (const GeometryExtension & obj) protected default
setName()
void Part::GeometryExtension::setName (const std::string & str) inline
Definition at line 68 of file GeometryExtension.h.
Referenced by copyAttributes(), and Part::GeometryDefaultExtension< T >::GeometryDefaultExtension().
The documentation for this class was generated from the following files:
GeometryExtension.h
GeometryExtension.cpp