FreeCAD: ifc2x3.ifcstructuralsteelprofileproperties Class Reference
ifc2x3.ifcstructuralsteelprofileproperties Class Reference
Public Member Functions
def __init__ (self, inherited0__profilename, inherited1__profiledefinition, inherited2__physicalweight, inherited3__perimeter, inherited4__minimumplatethickness, inherited5__maximumplatethickness, inherited6__crosssectionarea, inherited7__torsionalconstantx, inherited8__momentofinertiayz, inherited9__momentofinertiay, inherited10__momentofinertiaz, inherited11__warpingconstant, inherited12__shearcentrez, inherited13__shearcentrey, inherited14__sheardeformationareaz, inherited15__sheardeformationareay, inherited16__maximumsectionmodulusy, inherited17__minimumsectionmodulusy, inherited18__maximumsectionmodulusz, inherited19__minimumsectionmodulusz, inherited20__torsionalsectionmodulus, inherited21__centreofgravityinx, inherited22__centreofgravityiny, shearareaz, shearareay, plasticshapefactory, plasticshapefactorz)
def shearareaz ()
def shearareay ()
def plasticshapefactory ()
def plasticshapefactorz ()
def wr31 (self)
def wr32 (self)
Public Member Functions inherited from ifc2x3.ifcstructuralprofileproperties
def __init__ (self, inherited0__profilename, inherited1__profiledefinition, inherited2__physicalweight, inherited3__perimeter, inherited4__minimumplatethickness, inherited5__maximumplatethickness, inherited6__crosssectionarea, torsionalconstantx, momentofinertiayz, momentofinertiay, momentofinertiaz, warpingconstant, shearcentrez, shearcentrey, sheardeformationareaz, sheardeformationareay, maximumsectionmodulusy, minimumsectionmodulusy, maximumsectionmodulusz, minimumsectionmodulusz, torsionalsectionmodulus, centreofgravityinx, centreofgravityiny)
def torsionalconstantx ()
def momentofinertiayz ()
def momentofinertiay ()
def momentofinertiaz ()
def warpingconstant ()
def shearcentrez ()
def shearcentrey ()
def sheardeformationareaz ()
def sheardeformationareay ()
def maximumsectionmodulusy ()
def minimumsectionmodulusy ()
def maximumsectionmodulusz ()
def minimumsectionmodulusz ()
def torsionalsectionmodulus ()
def centreofgravityinx ()
def centreofgravityiny ()
def wr21 (self)
def wr22 (self)
Public Member Functions inherited from ifc2x3.ifcgeneralprofileproperties
def __init__ (self, inherited0__profilename, inherited1__profiledefinition, physicalweight, perimeter, minimumplatethickness, maximumplatethickness, crosssectionarea)
def physicalweight ()
def perimeter ()
def minimumplatethickness ()
def maximumplatethickness ()
def crosssectionarea ()
def wr1 (self)
Public Member Functions inherited from ifc2x3.ifcprofileproperties
def __init__ (self, profilename, profiledefinition)
def profilename ()
def profiledefinition ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
shearareaz
shearareay
plasticshapefactory
plasticshapefactorz
Public Attributes inherited from ifc2x3.ifcstructuralprofileproperties
torsionalconstantx
momentofinertiayz
momentofinertiay
momentofinertiaz
warpingconstant
shearcentrez
shearcentrey
sheardeformationareaz
sheardeformationareay
maximumsectionmodulusy
minimumsectionmodulusy
maximumsectionmodulusz
minimumsectionmodulusz
torsionalsectionmodulus
centreofgravityinx
centreofgravityiny
Public Attributes inherited from ifc2x3.ifcgeneralprofileproperties
physicalweight
perimeter
minimumplatethickness
maximumplatethickness
crosssectionarea
Public Attributes inherited from ifc2x3.ifcprofileproperties
profilename
profiledefinition
Detailed Description
Entity ifcstructuralsteelprofileproperties definition.
:param shearareaz
:type shearareaz:ifcareameasure
:param shearareay
:type shearareay:ifcareameasure
:param plasticshapefactory
:type plasticshapefactory:ifcpositiveratiomeasure
:param plasticshapefactorz
:type plasticshapefactorz:ifcpositiveratiomeasure
Definition at line 32004 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcstructuralsteelprofileproperties.__init__ (self, inherited0__profilename, inherited1__profiledefinition, inherited2__physicalweight, inherited3__perimeter, inherited4__minimumplatethickness, inherited5__maximumplatethickness, inherited6__crosssectionarea, inherited7__torsionalconstantx, inherited8__momentofinertiayz, inherited9__momentofinertiay, inherited10__momentofinertiaz, inherited11__warpingconstant, inherited12__shearcentrez, inherited13__shearcentrey, inherited14__sheardeformationareaz, inherited15__sheardeformationareay, inherited16__maximumsectionmodulusy, inherited17__minimumsectionmodulusy, inherited18__maximumsectionmodulusz, inherited19__minimumsectionmodulusz, inherited20__torsionalsectionmodulus, inherited21__centreofgravityinx, inherited22__centreofgravityiny, shearareaz, shearareay, plasticshapefactory, plasticshapefactorz)
Definition at line 32019 of file ifc2x3.py.
Member Function Documentation
plasticshapefactory()
def ifc2x3.ifcstructuralsteelprofileproperties.plasticshapefactory ()
Definition at line 32055 of file ifc2x3.py.
References ifc2x3.ifcstructuralsteelprofileproperties._plasticshapefactory, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralsteelprofileproperties.plasticshapefactory.
plasticshapefactorz()
def ifc2x3.ifcstructuralsteelprofileproperties.plasticshapefactorz ()
Definition at line 32069 of file ifc2x3.py.
References ifc2x3.ifcstructuralsteelprofileproperties._plasticshapefactorz, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralsteelprofileproperties.plasticshapefactorz.
shearareay()
def ifc2x3.ifcstructuralsteelprofileproperties.shearareay ()
Definition at line 32041 of file ifc2x3.py.
References ifc2x3.ifcstructuralsteelprofileproperties._shearareay, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralsteelprofileproperties.shearareay.
shearareaz()
def ifc2x3.ifcstructuralsteelprofileproperties.shearareaz ()
Definition at line 32027 of file ifc2x3.py.
References ifc2x3.ifcstructuralsteelprofileproperties._shearareaz, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralsteelprofileproperties.shearareaz.
wr31()
def ifc2x3.ifcstructuralsteelprofileproperties.wr31 (self)
Definition at line 32081 of file ifc2x3.py.
References SCL.Builtin.EXISTS(), and ifc2x3.ifcstructuralsteelprofileproperties.shearareay.
wr32()
def ifc2x3.ifcstructuralsteelprofileproperties.wr32 (self)
Definition at line 32088 of file ifc2x3.py.
References SCL.Builtin.EXISTS(), and ifc2x3.ifcstructuralsteelprofileproperties.shearareaz.
Member Data Documentation
plasticshapefactory
ifc2x3.ifcstructuralsteelprofileproperties.plasticshapefactory
Definition at line 32023 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralsteelprofileproperties.plasticshapefactory().
plasticshapefactorz
ifc2x3.ifcstructuralsteelprofileproperties.plasticshapefactorz
Definition at line 32024 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralsteelprofileproperties.plasticshapefactorz().
shearareay
ifc2x3.ifcstructuralsteelprofileproperties.shearareay
Definition at line 32022 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralsteelprofileproperties.shearareay(), and ifc2x3.ifcstructuralsteelprofileproperties.wr31().
shearareaz
ifc2x3.ifcstructuralsteelprofileproperties.shearareaz
Definition at line 32021 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralsteelprofileproperties.shearareaz(), and ifc2x3.ifcstructuralsteelprofileproperties.wr32().
The documentation for this class was generated from the following file:
ifc2x3.py