FreeCAD: App::PropertyFloat Class Reference
App::PropertyFloat Class Reference
#include <PropertyStandard.h>
Public Member Functions
PropertyFloat ()
~PropertyFloat () override
void setValue (double lValue)
double getValue () const
const char * getEditorName () const override
Get the class name of the associated property editor item.
PyObject * getPyObject () override
void setPyObject (PyObject *py) override
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
Property * Copy () const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
unsigned int getMemSize () const override
void setPathValue (const App::ObjectIdentifier &path, const boost::any &value) override
Set value of property.
const boost::any getPathValue (const App::ObjectIdentifier &path) const override
Get value of property.
bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
Public Member Functions inherited from App::Property
Property ()
~Property () override
const char * getName () const
bool hasName () const
std::string getFullName () const
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual void afterRestore ()
virtual void onContainerRestored ()
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
int64_t getID () const
virtual void beforeSave () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Attributes
double _dValue
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::Property
virtual void hasSetValue ()
Gets called by all setValue() methods after the value has changed.
virtual void aboutToSetValue ()
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Float properties This is the father of all properties handling floats. Use this type only in rare cases. Mostly you want to use the more specialized types like e.g. PropertyLength. These properties also fulfill the needs of the unit system. See PropertyUnits.h for all properties with units.
Definition at line 542 of file PropertyStandard.h.
Constructor & Destructor Documentation
PropertyFloat()
PropertyFloat::PropertyFloat ()
Value Constructor Construct with explicit Values
Definition at line 979 of file PropertyStandard.cpp.
~PropertyFloat()
PropertyFloat::~PropertyFloat () override default
A destructor. A more elaborate description of the destructor.
Member Function Documentation
Copy()
Property * PropertyFloat::Copy () const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Reimplemented in Spreadsheet::PropertySpreadsheetQuantity.
Definition at line 1038 of file PropertyStandard.cpp.
References buildPsets::p.
getEditorName()
const char* App::PropertyFloat::getEditorName () const inline override virtual
Get the class name of the associated property editor item.
Reimplemented from App::Property.
Reimplemented in App::PropertyPrecision, App::PropertyFloatConstraint, App::PropertyAngle, App::PropertyQuantityConstraint, and App::PropertyQuantity.
Definition at line 562 of file PropertyStandard.h.
getMemSize()
unsigned int App::PropertyFloat::getMemSize () const inline override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence
See also
Base::Persistence
Reimplemented from App::Property.
Definition at line 576 of file PropertyStandard.h.
getPathValue()
const boost::any PropertyFloat::getPathValue (const App::ObjectIdentifier & path) const override virtual
Get value of property.
Reimplemented from App::Property.
Reimplemented in App::PropertyQuantity.
Definition at line 1079 of file PropertyStandard.cpp.
References src.Mod.Test.testPathArray::path.
getPyObject()
PyObject * PropertyFloat::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Reimplemented in App::PropertyQuantity.
Definition at line 1001 of file PropertyStandard.cpp.
getValue()
double PropertyFloat::getValue () const
Definition at line 996 of file PropertyStandard.cpp.
Referenced by PartGui::TaskDlgAttacher::accept(), PartDesignGui::TaskHelixParameters::apply(), PartDesignGui::ViewProviderDatumCoordinateSystem::attach(), TechDrawGui::TaskRichAnno::calcTextStartPos(), TechDraw::DrawView::checkScale(), Part::Scale::computeFinalParameters(), Assembly::AssemblyObject::create_mbdSimulationParameters(), TechDrawGui::QGIViewPart::drawAllFaces(), TechDrawGui::QGIViewBalloon::drawBalloon(), TechDrawGui::QGIViewPart::drawHighlight(), TechDrawGui::QGIViewPart::drawMatting(), TechDrawGui::QGIViewSection::drawSectionFace(), App::FunctionExpression::evalAggregate(), Surface::Filling::execute(), PartDesign::Helix::execute(), Surface::Sewing::execute(), Part::Offset::execute(), Surface::Extend::execute(), Part::Revolution::execute(), Part::Offset2D::execute(), Surface::FeatureBlendCurve::execute(), Drawing::FeatureViewSpreadsheet::execute(), TechDraw::DrawViewDraft::execute(), TechDraw::DrawViewArch::execute(), Mesh::FixDegenerations::execute(), Mesh::FixDeformations::execute(), Mesh::FillHoles::execute(), Inspection::Feature::execute(), PartGui::ViewProviderGridExtension::extensionHandleChangedPropertyType(), Gui::ViewProviderLink::finishRestoring(), PartDesign::Helix::generateHelixPath(), TechDraw::DrawTemplate::getAutofillValue(), TechDraw::DrawViewSection::getDrawableLines(), TechDraw::DrawGeomHatch::getFaceOverlay(), TechDraw::DrawViewDetail::getFudgeRadius(), TechDrawGui::TaskGeomHatch::getParameters(), TechDraw::DrawViewImage::getRect(), FemGui::TaskFemConstraint::getScale(), TechDraw::DrawProjGroupItem::getScale(), TechDraw::DrawView::getScale(), Fem::Constraint::getScaleFactor(), TechDraw::DrawViewSpreadsheet::getSheetImage(), PartDesign::Scaled::getTransformations(), TechDraw::DrawGeomHatch::getTrimmedLines(), App::PropertyQuantity::getValue(), Fem::ConstraintTransform::handleChangedPropertyName(), TechDrawGui::ViewProviderRichAnno::handleChangedPropertyType(), TechDrawGui::ViewProviderLeader::handleChangedPropertyType(), PartGui::ViewProvider2DObjectGrid::handleChangedPropertyType(), TechDraw::DrawViewBalloon::handleChangedPropertyType(), Part::Primitive::handleChangedPropertyType(), Mesh::Sphere::handleChangedPropertyType(), Fem::ConstraintPressure::handleChangedPropertyType(), TechDraw::DrawView::handleChangedPropertyType(), Mesh::Ellipsoid::handleChangedPropertyType(), Fem::ConstraintForce::handleChangedPropertyType(), TechDraw::DrawPage::handleChangedPropertyType(), Fem::ConstraintInitialTemperature::handleChangedPropertyType(), Fem::ConstraintTemperature::handleChangedPropertyType(), Fem::ConstraintHeatflux::handleChangedPropertyType(), Fem::ConstraintContact::handleChangedPropertyType(), PartDesign::Helix::handleChangedPropertyType(), TechDrawGui::ViewProviderBalloon::handleChangedPropertyType(), TechDrawGui::ViewProviderViewPart::handleChangedPropertyType(), Fem::ConstraintDisplacement::handleChangedPropertyType(), TechDraw::DrawViewAnnotation::handleChangedPropertyType(), Mesh::Cylinder::handleChangedPropertyType(), TechDrawGui::ViewProviderDimension::handleChangedPropertyType(), PartDesign::Transformed::handleChangedPropertyType(), Mesh::Cone::handleChangedPropertyType(), Mesh::Torus::handleChangedPropertyType(), TechDraw::DrawProjGroup::handleChangedPropertyType(), Mesh::Cube::handleChangedPropertyType(), TechDraw::DrawViewDimension::handleChangedPropertyType(), PartGui::ViewProviderPartExt::loadParameter(), PartGui::OffsetWidget::OffsetWidget(), PartDesignGui::ViewProviderDatumCoordinateSystem::onChanged(), TechDrawGui::ViewProviderHatch::onChanged(), Gui::ViewProviderAnnotation::onChanged(), InspectionGui::ViewProviderInspection::onChanged(), FemGui::ViewProviderFemPostDataAtPoint::onChanged(), FemGui::ViewProviderFemPostObject::onChanged(), Fem::ConstraintPulley::onChanged(), Fem::ConstraintBearing::onChanged(), FemGui::ViewProviderFemPostFunction::onChanged(), TechDraw::DrawView::onChanged(), FemGui::ViewProviderFemMesh::onChanged(), TechDraw::DrawProjGroup::onChanged(), TechDraw::DrawPage::onChanged(), PartGui::ViewProviderPartExt::onChanged(), Gui::ViewProviderLink::onChanged(), MeshGui::ViewProviderMesh::onChanged(), FemGui::ViewProviderFemPostPlaneFunction::onChanged(), TechDrawGui::TaskDetail::onScaleTypeEdit(), TechDraw::DrawViewDetail::postHlrTasks(), PartDesign::Helix::safePitch(), TechDrawGui::TaskDetail::saveDetailState(), TechDrawGui::TaskProjGroup::saveGroupState(), TechDrawGui::TaskHatch::saveHatchState(), TechDrawGui::TaskSectionView::scaleTypeChanged(), TechDrawGui::TaskComplexSection::scaleTypeChanged(), TechDraw::DrawViewSection::sectionLineEnds(), PartDesignGui::ViewProviderDatumCoordinateSystem::setExtents(), RobotGui::TaskRobot6Axis::setRobot(), TechDrawGui::QGIRichAnno::setTextItem(), TechDrawGui::TaskComplexSection::setUiEdit(), TechDrawGui::TaskRichAnno::setUiEdit(), TechDrawGui::TaskDetail::setUiFromFeat(), TechDrawGui::QGIViewBalloon::setViewPartFeature(), FemGui::TaskFemConstraintBearing::TaskFemConstraintBearing(), FemGui::TaskFemConstraintContact::TaskFemConstraintContact(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), FemGui::TaskFemConstraintGear::TaskFemConstraintGear(), FemGui::TaskFemConstraintHeatflux::TaskFemConstraintHeatflux(), FemGui::TaskFemConstraintPulley::TaskFemConstraintPulley(), FemGui::TaskPostScalarClip::TaskPostScalarClip(), FemGui::TaskTetParameter::TaskTetParameter(), TechDrawGui::TaskProjGroup::turnProjGroupToView(), PartDesign::SubShapeBinder::update(), PartDesignGui::ViewProviderAddSub::updateAddSubShapeIndicator(), RobotGui::ViewProviderRobotObject::updateData(), FemGui::ViewProviderFemConstraintBearing::updateData(), FemGui::ViewProviderFemConstraintGear::updateData(), FemGui::ViewProviderFemConstraintPulley::updateData(), FemGui::ViewProviderFemConstraintFluidBoundary::updateData(), FemGui::ViewProviderFemPostPlaneFunction::updateData(), FemGui::ViewProviderFemPostFunctionProvider::updateSize(), PartGui::ViewProviderPartExt::updateVisual(), TechDraw::DrawView::validateScale(), FemGui::ViewProviderFemMesh::ViewProviderFemMesh(), and PartGui::ViewProviderPartExt::ViewProviderPartExt().
isSame()
bool App::PropertyFloat::isSame (const Property & other) const inline override virtual
Compare if this property has the same content as the given one.
Reimplemented from App::Property.
Reimplemented in App::PropertyQuantity.
Definition at line 584 of file PropertyStandard.h.
References Base::Persistence::getTypeId(), and getValue().
Paste()
void PropertyFloat::Paste (const Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 1045 of file PropertyStandard.cpp.
Restore()
void PropertyFloat::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 1030 of file PropertyStandard.cpp.
References TechDrawTools.TaskFillTemplateFields::reader.
Referenced by PartGui::ViewProviderGridExtension::extensionHandleChangedPropertyType(), TechDraw::DrawViewBalloon::handleChangedPropertyName(), Fem::ConstraintTransform::handleChangedPropertyName(), Part::Circle::handleChangedPropertyName(), Part::Ellipse::handleChangedPropertyName(), TechDrawGui::ViewProviderRichAnno::handleChangedPropertyType(), TechDrawGui::ViewProviderLeader::handleChangedPropertyType(), PartGui::ViewProvider2DObjectGrid::handleChangedPropertyType(), TechDraw::DrawViewBalloon::handleChangedPropertyType(), Mesh::Sphere::handleChangedPropertyType(), Fem::ConstraintPressure::handleChangedPropertyType(), Part::Primitive::handleChangedPropertyType(), TechDraw::DrawView::handleChangedPropertyType(), Mesh::Ellipsoid::handleChangedPropertyType(), Fem::ConstraintForce::handleChangedPropertyType(), Fem::ConstraintInitialTemperature::handleChangedPropertyType(), TechDraw::DrawPage::handleChangedPropertyType(), Fem::ConstraintHeatflux::handleChangedPropertyType(), Fem::ConstraintTemperature::handleChangedPropertyType(), Fem::ConstraintContact::handleChangedPropertyType(), PartDesign::Helix::handleChangedPropertyType(), TechDrawGui::ViewProviderBalloon::handleChangedPropertyType(), TechDrawGui::ViewProviderViewPart::handleChangedPropertyType(), Fem::ConstraintDisplacement::handleChangedPropertyType(), TechDraw::DrawViewAnnotation::handleChangedPropertyType(), Mesh::Cylinder::handleChangedPropertyType(), TechDrawGui::ViewProviderDimension::handleChangedPropertyType(), PartDesign::Transformed::handleChangedPropertyType(), Mesh::Cone::handleChangedPropertyType(), Mesh::Torus::handleChangedPropertyType(), TechDraw::DrawProjGroup::handleChangedPropertyType(), Mesh::Cube::handleChangedPropertyType(), and TechDraw::DrawViewDimension::handleChangedPropertyType().
Save()
void PropertyFloat::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 1025 of file PropertyStandard.cpp.
References Base::Writer::ind(), and Base::Writer::Stream().
setPathValue()
void PropertyFloat::setPathValue (const App::ObjectIdentifier & path, const boost::any & value) override virtual
Set value of property.
Reimplemented from App::Property.
Reimplemented in App::PropertyQuantity.
Definition at line 1052 of file PropertyStandard.cpp.
References getValue(), and src.Mod.Test.testPathArray::path.
setPyObject()
void PropertyFloat::setPyObject (PyObject * py) override virtual
Reimplemented from Base::BaseClass.
Reimplemented in App::PropertyFloatConstraint, App::PropertyQuantityConstraint, and App::PropertyQuantity.
Definition at line 1006 of file PropertyStandard.cpp.
References Path.Log::error().
setValue()
void PropertyFloat::setValue (double lValue)
Definition at line 989 of file PropertyStandard.cpp.
Referenced by RobotGui::TaskRobot6Axis::changeSliderA1(), RobotGui::TaskRobot6Axis::changeSliderA2(), RobotGui::TaskRobot6Axis::changeSliderA3(), RobotGui::TaskRobot6Axis::changeSliderA4(), RobotGui::TaskRobot6Axis::changeSliderA5(), RobotGui::TaskRobot6Axis::changeSliderA6(), TechDraw::DrawView::checkScale(), TechDrawGui::TaskRichAnno::commonFeatureUpdate(), TechDrawGui::TaskHatch::createHatch(), FemGui::ViewProviderFemPostPlaneFunction::draggerUpdate(), PartDesign::Helix::execute(), TechDraw::DrawProjGroup::execute(), Surface::Extend::handleChangedPropertyName(), TechDraw::DrawView::handleChangedPropertyType(), TechDraw::DrawPage::handleChangedPropertyType(), Fem::ConstraintContact::handleChangedPropertyType(), PartDesign::Helix::handleChangedPropertyType(), TechDraw::DrawViewAnnotation::handleChangedPropertyType(), Fem::Constraint::handleChangedPropertyType(), PartGui::ViewProviderPartExt::loadParameter(), PartDesignGui::ViewProviderSubShapeBinder::onChanged(), Surface::Extend::onChanged(), Fem::ConstraintPulley::onChanged(), Fem::ConstraintBearing::onChanged(), TechDraw::DrawView::onChanged(), TechDraw::DrawProjGroup::onChanged(), TechDraw::DrawPage::onChanged(), TechDrawGui::TaskDetail::onScaleTypeEdit(), TechDraw::DrawViewDetail::postHlrTasks(), TechDraw::DrawViewSection::postHlrTasks(), TechDraw::DrawViewPart::postHlrTasks(), TechDrawGui::TaskGeomHatch::reject(), TechDrawGui::TaskDetail::restoreDetailState(), TechDrawGui::TaskProjGroup::restoreGroupState(), TechDrawGui::TaskHatch::restoreHatchState(), TechDrawGui::TaskSectionView::restoreSectionState(), TechDrawGui::TaskComplexSection::restoreSectionState(), TechDrawGui::TaskProjGroup::scaleTypeChanged(), Spreadsheet::Sheet::setFloatProperty(), App::PropertyQuantity::setPyObject(), App::PropertyQuantityConstraint::setPyObject(), App::PropertyQuantity::setValue(), TechDrawGui::TaskProjGroup::turnProjGroupToView(), TechDrawGui::TaskProjGroup::turnViewToProjGroup(), FemGui::ViewProviderFemPostPlaneFunction::updateData(), TechDrawGui::TaskDetail::updateDetail(), FemGui::ViewProviderFemPostPipeline::updateFunctionSize(), TechDrawGui::TaskHatch::updateHatch(), FemGui::ViewProviderFemPostFunctionProvider::updateSize(), TechDrawGui::TaskGeomHatch::updateValues(), and SketcherGui::ViewProviderSketch::ViewProviderSketch().
Member Data Documentation
_dValue
double App::PropertyFloat::_dValue protected
Definition at line 594 of file PropertyStandard.h.
Referenced by Spreadsheet::PropertySpreadsheetQuantity::Copy().
The documentation for this class was generated from the following files:
PropertyStandard.h
PropertyStandard.cpp