FreeCAD: FemGui::TaskFemConstraintGear Class Reference
FemGui::TaskFemConstraintGear Class Reference
#include <TaskFemConstraintGear.h>
Public Member Functions
TaskFemConstraintGear (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="FEM_ConstraintGear")
double getDiameter () const
double getForce () const
double getForceAngle () const
const std::string getDirectionName () const
const std::string getDirectionObject () const
bool getReverse () const
Public Member Functions inherited from FemGui::TaskFemConstraintBearing
TaskFemConstraintBearing (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="FEM_ConstraintBearing")
~TaskFemConstraintBearing () override
double getDistance () const
const std::string getReferences () const override
const std::string getLocationName () const
const std::string getLocationObject () const
bool getAxial () const
Public Member Functions inherited from FemGui::TaskFemConstraint
TaskFemConstraint (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="")
~TaskFemConstraint () override=default
const std::string getReferences (const std::vector< std::string > &items) const
const std::string getScale () const
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Protected Member Functions
void changeEvent (QEvent *e) override
void onSelectionChanged (const Gui::SelectionChanges &msg) override
Protected Member Functions inherited from FemGui::TaskFemConstraintBearing
void changeEvent (QEvent *e) override
Protected Member Functions inherited from FemGui::TaskFemConstraint
void changeEvent (QEvent *e) override
const QString makeRefText (const std::string &objName, const std::string &subName) const
const QString makeRefText (const App::DocumentObject *obj, const std::string &subName) const
void keyPressEvent (QKeyEvent *ke) override
void createDeleteAction (QListWidget *parentList)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Protected Types inherited from FemGui::TaskFemConstraint
enum { seldir, selref, selloc, selnone }
Protected Slots inherited from FemGui::TaskFemConstraint
void onReferenceDeleted (const int row)
void onButtonReference (const bool pressed=true)
void setSelection (QListWidgetItem *item)
bool event (QEvent *event) override
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Attributes inherited from FemGui::TaskFemConstraintBearing
std::unique_ptr< Ui_TaskFemConstraintBearing > ui
Protected Attributes inherited from FemGui::TaskFemConstraint
QWidget * proxy
QAction * deleteAction
Gui::WeakPtrT< ViewProviderFemConstraint > ConstraintView
enum FemGui::TaskFemConstraint:: { ... } selectionMode
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
Definition at line 54 of file TaskFemConstraintGear.h.
Constructor & Destructor Documentation
TaskFemConstraintGear()
TaskFemConstraintGear::TaskFemConstraintGear (ViewProviderFemConstraint * ConstraintView, QWidget * parent = nullptr, const char * pixmapname = "FEM_ConstraintGear") explicit
Definition at line 48 of file TaskFemConstraintGear.cpp.
References draftgeoutils.intersections::connect(), FemGui::TaskFemConstraint::ConstraintView, Fem::ConstraintGear::Diameter, Fem::ConstraintGear::Direction, FLOAT_MAX, Fem::ConstraintGear::Force, Fem::ConstraintGear::ForceAngle, App::PropertyLinkSub::getSubValues(), App::PropertyFloat::getValue(), App::PropertyLinkSub::getValue(), App::PropertyBool::getValue(), FemGui::TaskFemConstraint::makeRefText(), Fem::ConstraintGear::Reversed, and FemGui::TaskFemConstraintBearing::ui.
Member Function Documentation
changeEvent()
void TaskFemConstraintGear::changeEvent (QEvent * e) override protected
Definition at line 257 of file TaskFemConstraintGear.cpp.
References SCL.SimpleDataTypes::e, FemGui::TaskFemConstraint::proxy, and FemGui::TaskFemConstraintBearing::ui.
getDiameter()
double TaskFemConstraintGear::getDiameter () const
Definition at line 252 of file TaskFemConstraintGear.cpp.
References FemGui::TaskFemConstraintBearing::ui.
Referenced by FemGui::TaskDlgFemConstraintGear::accept().
getDirectionName()
const std::string TaskFemConstraintGear::getDirectionName () const
Definition at line 225 of file TaskFemConstraintGear.cpp.
References RobotExample::pos, and FemGui::TaskFemConstraintBearing::ui.
Referenced by FemGui::TaskDlgFemConstraintGear::accept().
getDirectionObject()
const std::string TaskFemConstraintGear::getDirectionObject () const
Definition at line 236 of file TaskFemConstraintGear.cpp.
References RobotExample::pos, and FemGui::TaskFemConstraintBearing::ui.
Referenced by FemGui::TaskDlgFemConstraintGear::accept().
getForce()
double TaskFemConstraintGear::getForce () const
Definition at line 215 of file TaskFemConstraintGear.cpp.
References FemGui::TaskFemConstraintBearing::ui.
Referenced by FemGui::TaskDlgFemConstraintGear::accept().
getForceAngle()
double TaskFemConstraintGear::getForceAngle () const
Definition at line 220 of file TaskFemConstraintGear.cpp.
References FemGui::TaskFemConstraintBearing::ui.
Referenced by FemGui::TaskDlgFemConstraintGear::accept().
getReverse()
bool TaskFemConstraintGear::getReverse () const
Definition at line 247 of file TaskFemConstraintGear.cpp.
References FemGui::TaskFemConstraintBearing::ui.
Referenced by FemGui::TaskDlgFemConstraintGear::accept().
onSelectionChanged()
void TaskFemConstraintGear::onSelectionChanged (const Gui::SelectionChanges & msg) override protected virtual
Reimplemented from FemGui::TaskFemConstraintBearing.
Definition at line 119 of file TaskFemConstraintGear.cpp.
References Gui::SelectionChanges::AddSelection, Gui::SelectionSingleton::clearSelection(), FemGui::TaskFemConstraint::ConstraintView, Fem::ConstraintGear::Direction, Part::PropertyPartShape::getShape(), Part::TopoShape::getSubShape(), Fem::Tools::isLinear(), Fem::Tools::isPlanar(), FemGui::TaskFemConstraint::makeRefText(), Path.Op.Surface::msg, FemGui::TaskFemConstraintBearing::onSelectionChanged(), FemGui::TaskFemConstraint::seldir, Gui::Selection(), FemGui::TaskFemConstraint::selectionMode, FemGui::TaskFemConstraint::selnone, App::PropertyLinkSub::setValue(), Part::Feature::Shape, FemGui::TaskFemConstraintBearing::ui, and Path.Log::warning().
The documentation for this class was generated from the following files:
TaskFemConstraintGear.h
TaskFemConstraintGear.cpp