FreeCAD: TechDrawGui::QGIViewBalloon Class Reference
TechDrawGui::QGIViewBalloon Class Reference
#include <QGIViewBalloon.h>
Public Types
enum { Type = QGraphicsItem::UserType + 140 }
Public Types inherited from TechDrawGui::QGIView
enum { Type = QGraphicsItem::UserType + 101 }
Public Slots
void balloonLabelDragged (bool ctrl)
void balloonLabelDragFinished ()
void select (bool state)
void hover (bool state)
void updateBalloon (bool obtuse=false)
Public Member Functions
QGIViewBalloon ()
~QGIViewBalloon () override=default
void setViewPartFeature (TechDraw::DrawViewBalloon *balloonFeat)
int type () const override
void drawBorder () override
void updateView (bool update=false) override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QString getLabelText ()
void placeBalloon (QPointF pos)
void setPrettyPre ()
void setPrettySel ()
void setPrettyNormal ()
bool getGroupSelection () override
void setGroupSelection (bool isSelected) override
virtual QGIBalloonLabel * getBalloonLabel ()
void setNormalColorAll ()
QColor prefNormalColor ()
int prefDefaultArrow () const
bool prefOrthoPyramid () const
TechDraw::DrawViewBalloon * getBalloonFeat ()
Public Member Functions inherited from TechDrawGui::QGIView
QGIView ()
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
const char * getViewName () const
const std::string getViewNameAsString () const
void setViewFeature (TechDraw::DrawView *obj)
TechDraw::DrawView * getViewObject () const
MDIViewPage * getMDIViewPage () const
double getScale ()
void hideFrame ()
virtual bool getFrameState ()
virtual void toggleCache (bool state)
virtual void isVisible (bool state)
virtual bool isVisible ()
virtual void setGroupSelection (bool isSelected, const std::vector< std::string > &subNames)
virtual void drawCaption ()
virtual void rotateView ()
void makeMark (double xPos, double yPos, QColor color=Qt::red)
void makeMark (Base::Vector3d pos, QColor color=Qt::red)
void makeMark (QPointF pos, QColor color=Qt::red)
void setPosition (qreal xPos, qreal yPos)
qreal getY ()
bool isInnerView () const
void isInnerView (bool state)
QGIViewClip * getClipGroup ()
bool isSnapping ()
void snapPosition (QPointF &position)
void snapSectionView (const TechDraw::DrawViewSection *sectionView, QPointF &newPosition)
Base::Vector3d projItemPagePos (TechDraw::DrawViewPart *item)
void alignTo (QGraphicsItem *, const QString &alignment)
QColor prefNormalColor ()
QColor getNormalColor ()
void setNormalColor (QColor color)
QColor getPreColor ()
QColor getSelectColor ()
QColor getCurrentColor ()
void setCurrentColor (QColor color)
QColor getSettingColor ()
void setSettingColor (QColor color)
virtual void setStack (int z)
virtual void setStackFromVP ()
QFont getFont ()
void setFont (QFont font)
virtual void removeChild (QGIView *child)
virtual void addArbitraryItem (QGraphicsItem *qgi)
virtual void switchParentItem (QGIView *targetParent)
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
Protected Member Functions
void draw () override
void drawBalloon (bool originDrag=false)
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
virtual void setSvgPens ()
virtual void setPens ()
QString getPrecision ()
void parentViewMousePressed (QGIView *view, QPointF pos)
TechDraw::DrawView * getSourceView () const
Base::Vector3d arrowPosInDrag ()
void getBalloonPoints (TechDraw::DrawViewBalloon *balloon, TechDraw::DrawView *refObj, bool isDragging, Base::Vector3d &labelPos, Base::Vector3d &arrowPos)
retrieves the appropriate label position and origin (arrow) point
Protected Member Functions inherited from TechDrawGui::QGIView
QGIView * getQGIVByName (std::string name)
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QRectF customChildrenBoundingRect () const
void dumpRect (const char *text, QRectF rect)
Base::Reference< ParameterGrp > getParmGroupCol ()
Additional Inherited Members
Static Public Member Functions inherited from TechDrawGui::QGIView
static Gui::ViewProvider * getViewProvider (App::DocumentObject *obj)
static ViewProviderPage * getViewProviderPage (TechDraw::DrawView *dView)
static int calculateFontPixelSize (double sizeInMillimetres)
static int calculateFontPixelWidth (const QFont &font)
static QString getPrefFont ()
static double getPrefFontSize ()
static double getDimFontSize ()
static int exactFontSize (std::string fontFamily, double nominalSize)
Static Public Attributes inherited from TechDrawGui::QGIView
static const double DefaultFontSizeInMM = 5.0
Detailed Description
Definition at line 167 of file QGIViewBalloon.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 172 of file QGIViewBalloon.h.
Constructor & Destructor Documentation
QGIViewBalloon()
QGIViewBalloon::QGIViewBalloon () explicit
Definition at line 246 of file QGIViewBalloon.cpp.
References ZVALUE::BALLOON, balloonLabelDragFinished(), balloonLabelDragged(), draftgeoutils.intersections::connect(), ZVALUE::DIMENSION, TechDrawGui::QGIBalloonLabel::dragFinished(), TechDrawGui::QGIBalloonLabel::dragging(), TechDrawGui::QGIBalloonLabel::hover(), hover(), prefDefaultArrow(), prefNormalColor(), select(), TechDrawGui::QGIBalloonLabel::selected(), TechDrawGui::QGIBalloonLabel::setColor(), TechDrawGui::QGIPrimPath::setFill(), TechDrawGui::QGIPrimPath::setFillColor(), TechDrawGui::QGIPrimPath::setFillOverride(), TechDrawGui::QGIPrimPath::setNormalColor(), TechDrawGui::QGIBalloonLabel::setPosFromCenter(), TechDrawGui::QGIPrimPath::setPrettyNormal(), TechDrawGui::QGIBalloonLabel::setPrettyNormal(), TechDrawGui::QGIBalloonLabel::setQBalloon(), TechDrawGui::QGIPrimPath::setStyle(), and TechDrawGui::QGIArrow::setStyle().
~QGIViewBalloon()
TechDrawGui::QGIViewBalloon::~QGIViewBalloon () override default
Member Function Documentation
arrowPosInDrag()
Base::Vector3d QGIViewBalloon::arrowPosInDrag () protected
Calculate the required position of the arrow tip during drag operations. Uses the current label position and relative positions of the label and tip at the start of the drag. Note this returns the Gui position of the arrow, not the App position.
Definition at line 982 of file QGIViewBalloon.cpp.
References TechDraw::DrawUtil::toVector3d().
Referenced by balloonLabelDragFinished(), and getBalloonPoints().
balloonLabelDragFinished
void QGIViewBalloon::balloonLabelDragFinished () slot
Definition at line 491 of file QGIViewBalloon.cpp.
References TechDrawGui::Rez::appX(), arrowPosInDrag(), Gui::Command::commitCommand(), Gui::Command::Doc, doCommand, drawBalloon(), TechDrawGui::QGIBalloonLabel::getCenterX(), TechDrawGui::QGIBalloonLabel::getCenterY(), TechDraw::DrawView::getScale(), getSourceView(), App::PropertyQuantity::getValue(), TechDrawGui::QGIView::getViewObject(), TechDraw::DrawUtil::invertY(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, TechDraw::DrawView::Rotation, draftfunctions.scale::scale(), Base::toRadians(), MovieTool::x, and MovieTool::y.
Referenced by QGIViewBalloon().
balloonLabelDragged
void QGIViewBalloon::balloonLabelDragged (bool ctrl) slot
Definition at line 457 of file QGIViewBalloon.cpp.
References drawBalloon(), getSourceView(), TechDrawGui::QGIView::getViewObject(), and TechDraw::DrawUtil::toVector3d().
Referenced by QGIViewBalloon().
draw()
void QGIViewBalloon::draw () override protected virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 602 of file QGIViewBalloon.cpp.
References drawBalloon().
Referenced by hover(), itemChange(), placeBalloon(), select(), setViewPartFeature(), and updateView().
drawBalloon()
void QGIViewBalloon::drawBalloon (bool originDrag = false) protected
Definition at line 608 of file QGIViewBalloon.cpp.
References KDL::atan2(), TechDraw::DrawViewBalloon::BubbleShape, KDL::cos(), TechDrawGui::QGIArrow::draw(), TechDraw::DrawViewBalloon::EndType, TechDraw::DrawViewBalloon::EndTypeScale, TechDraw::FILLED_TRIANGLE, getBalloonPoints(), Base::Persistence::getClassTypeId(), TechDrawGui::QGIBalloonLabel::getDimText(), TechDrawGui::QGIArrow::getOverlapAdjust(), TechDraw::DrawViewBalloon::getParentView(), TechDrawGui::QGIArrow::getPrefArrowSize(), TechDrawGui::QGIBalloonLabel::getSeps(), App::PropertyQuantity::getValue(), App::PropertyEnumeration::getValue(), App::PropertyFloat::getValue(), App::PropertyEnumeration::getValueAsString(), TechDrawGui::QGIBalloonLabel::getVerticalSep(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), TechDrawGui::Rez::guiX(), SplineSurface::i, Base::BaseClass::isDerivedFrom(), TechDraw::DrawView::isLocked(), App::DocumentObject::isRestoring(), TechDraw::DrawViewBalloon::KinkLength, M_PI, KDL::max(), NONE, Base::pow(), prefOrthoPyramid(), draftfunctions.scale::scale(), setPrettyNormal(), setPrettyPre(), setPrettySel(), TechDrawGui::QGIArrow::setSize(), TechDrawGui::QGIArrow::setStyle(), TechDraw::DrawViewBalloon::ShapeScale, KDL::sin(), KDL::sqrt(), KDL::tan(), TechDraw::DrawUtil::toQPointF(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by balloonLabelDragFinished(), balloonLabelDragged(), and draw().
drawBorder()
void QGIViewBalloon::drawBorder () override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 891 of file QGIViewBalloon.cpp.
getBalloonFeat()
TechDraw::DrawViewBalloon* TechDrawGui::QGIViewBalloon::getBalloonFeat () inline
Definition at line 209 of file QGIViewBalloon.h.
Referenced by prefNormalColor().
getBalloonLabel()
virtual QGIBalloonLabel* TechDrawGui::QGIViewBalloon::getBalloonLabel () inline virtual
Definition at line 199 of file QGIViewBalloon.h.
getBalloonPoints()
void QGIViewBalloon::getBalloonPoints (TechDraw::DrawViewBalloon * balloon, TechDraw::DrawView * refObj, bool isDragging, Base::Vector3d & labelPos, Base::Vector3d & arrowPos) protected
retrieves the appropriate label position and origin (arrow) point
Definition at line 991 of file QGIViewBalloon.cpp.
References arrowPosInDrag(), TechDrawGui::QGIBalloonLabel::getCenterX(), TechDrawGui::QGIBalloonLabel::getCenterY(), TechDraw::DrawView::getScale(), App::PropertyQuantity::getValue(), TechDrawGui::Rez::guiX(), TechDraw::DrawViewBalloon::OriginX, TechDraw::DrawViewBalloon::OriginY, TechDrawGui::DrawGuiUtil::toGuiPoint(), MovieTool::x, TechDraw::DrawView::X, MovieTool::y, and TechDraw::DrawView::Y.
Referenced by drawBalloon().
getGroupSelection()
bool QGIViewBalloon::getGroupSelection () override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 327 of file QGIViewBalloon.cpp.
getLabelText()
QString TechDrawGui::QGIViewBalloon::getLabelText ()
getPrecision()
QString TechDrawGui::QGIViewBalloon::getPrecision () protected
getSourceView()
DrawView * QGIViewBalloon::getSourceView () const protected
Definition at line 968 of file QGIViewBalloon.cpp.
References App::PropertyLink::getValue(), TechDrawGui::QGIView::getViewObject(), and TechDraw::DrawViewBalloon::SourceView.
Referenced by balloonLabelDragFinished(), and balloonLabelDragged().
hover
void QGIViewBalloon::hover (bool state) slot
Definition at line 350 of file QGIViewBalloon.cpp.
References draw().
Referenced by QGIViewBalloon().
itemChange()
QVariant QGIViewBalloon::itemChange (GraphicsItemChange change, const QVariant & value) override protected
Definition at line 303 of file QGIViewBalloon.cpp.
References draw(), and TechDrawGui::QGIView::itemChange().
paint()
void QGIViewBalloon::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 897 of file QGIViewBalloon.cpp.
References TechDrawGui::QGIView::paint(), setPens(), and setSvgPens().
parentViewMousePressed()
void TechDrawGui::QGIViewBalloon::parentViewMousePressed (QGIView * view, QPointF pos) protected
placeBalloon()
void QGIViewBalloon::placeBalloon (QPointF pos)
Definition at line 542 of file QGIViewBalloon.cpp.
References TechDrawGui::Rez::appX(), TechDrawGui::QGIView::calculateFontPixelSize(), draw(), TechDrawGui::QGIView::exactFontSize(), TechDraw::DrawView::findParentPage(), TechDrawGui::QGIBalloonLabel::getFont(), TechDraw::DrawView::getScale(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), TechDrawGui::Rez::guiX(), RobotExample::pos, TechDrawGui::QGIBalloonLabel::setDimString(), TechDrawGui::QGIBalloonLabel::setFont(), and TechDrawGui::QGIBalloonLabel::setPosFromCenter().
prefDefaultArrow()
int QGIViewBalloon::prefDefaultArrow () const
Definition at line 958 of file QGIViewBalloon.cpp.
Referenced by QGIViewBalloon().
prefNormalColor()
QColor QGIViewBalloon::prefNormalColor ()
Definition at line 942 of file QGIViewBalloon.cpp.
References App::Color::asValue(), TechDrawGui::ViewProviderBalloon::Color, TechDrawGui::PreferencesGui::dimQColor(), TechDrawGui::PreferencesGui::getAccessibleQColor(), getBalloonFeat(), TechDrawGui::QGIView::getNormalColor(), App::PropertyColor::getValue(), TechDrawGui::QGIView::getViewProvider(), and TechDrawGui::QGIView::setNormalColor().
Referenced by QGIViewBalloon(), setNormalColorAll(), and setViewPartFeature().
prefOrthoPyramid()
bool QGIViewBalloon::prefOrthoPyramid () const
Definition at line 963 of file QGIViewBalloon.cpp.
Referenced by drawBalloon().
select
void QGIViewBalloon::select (bool state) slot
Definition at line 343 of file QGIViewBalloon.cpp.
References draw().
Referenced by QGIViewBalloon().
setGroupSelection()
void QGIViewBalloon::setGroupSelection (bool isSelected) override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 333 of file QGIViewBalloon.cpp.
setNormalColorAll()
void QGIViewBalloon::setNormalColorAll ()
Definition at line 932 of file QGIViewBalloon.cpp.
References prefNormalColor(), TechDrawGui::QGIBalloonLabel::setColor(), TechDrawGui::QGIPrimPath::setFillColor(), and TechDrawGui::QGIPrimPath::setNormalColor().
Referenced by updateView().
setPens()
void QGIViewBalloon::setPens () protected virtual
Definition at line 924 of file QGIViewBalloon.cpp.
References TechDrawGui::PreferencesGui::pageQColor(), TechDrawGui::QGIPrimPath::setFillColor(), and TechDrawGui::QGIPrimPath::setWidth().
Referenced by paint().
setPrettyNormal()
void QGIViewBalloon::setPrettyNormal ()
Definition at line 882 of file QGIViewBalloon.cpp.
References TechDrawGui::QGIPrimPath::setPrettyNormal().
Referenced by drawBalloon().
setPrettyPre()
void QGIViewBalloon::setPrettyPre ()
Definition at line 863 of file QGIViewBalloon.cpp.
References TechDrawGui::QGIPrimPath::setPrettyPre().
Referenced by drawBalloon().
setPrettySel()
void QGIViewBalloon::setPrettySel ()
Definition at line 873 of file QGIViewBalloon.cpp.
References TechDrawGui::QGIPrimPath::setPrettySel().
Referenced by drawBalloon().
setSvgPens()
void QGIViewBalloon::setSvgPens () protected virtual
Definition at line 916 of file QGIViewBalloon.cpp.
References TechDrawGui::QGIPrimPath::getWidth(), and TechDrawGui::QGIPrimPath::setWidth().
Referenced by paint().
setViewPartFeature()
void QGIViewBalloon::setViewPartFeature (TechDraw::DrawViewBalloon * balloonFeat)
Definition at line 356 of file QGIViewBalloon.cpp.
References draw(), TechDraw::DrawView::getScale(), App::PropertyString::getStrValue(), App::PropertyQuantity::getValue(), App::PropertyFloat::getValue(), App::PropertyLink::getValue(), TechDrawGui::Rez::guiX(), prefNormalColor(), TechDrawGui::QGIBalloonLabel::setColor(), TechDrawGui::QGIBalloonLabel::setDimString(), TechDrawGui::QGIBalloonLabel::setPosFromCenter(), TechDrawGui::QGIView::setViewFeature(), TechDraw::DrawViewBalloon::SourceView, TechDraw::DrawViewBalloon::Text, TechDraw::DrawViewBalloon::TextWrapLen, updateBalloon(), MovieTool::x, TechDraw::DrawView::X, MovieTool::y, and TechDraw::DrawView::Y.
type()
int TechDrawGui::QGIViewBalloon::type () const inline override
Definition at line 181 of file QGIViewBalloon.h.
updateBalloon
void QGIViewBalloon::updateBalloon (bool obtuse = false) slot
Definition at line 414 of file QGIViewBalloon.cpp.
References TechDrawGui::QGIView::exactFontSize(), TechDrawGui::QGIBalloonLabel::getFont(), TechDraw::DrawView::getScale(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), TechDrawGui::Rez::guiX(), Gui::QtTools::horizontalAdvance(), RobotExample::pos, TechDrawGui::QGIBalloonLabel::setDimString(), TechDrawGui::QGIBalloonLabel::setFont(), TechDrawGui::QGIBalloonLabel::setPosFromCenter(), TechDrawGui::QGIBalloonLabel::setSeps(), TechDrawGui::QGIBalloonLabel::setVerticalSep(), MovieTool::x, and MovieTool::y.
Referenced by setViewPartFeature(), and updateView().
updateView()
void QGIViewBalloon::updateView (bool update = false) override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 390 of file QGIViewBalloon.cpp.
References draw(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), TechDrawGui::Rez::guiX(), TechDrawGui::QGIBalloonLabel::setDimString(), setNormalColorAll(), and updateBalloon().
The documentation for this class was generated from the following files:
QGIViewBalloon.h
QGIViewBalloon.cpp