FreeCAD: PartGui::DlgFilletEdges Class Reference
PartGui::DlgFilletEdges Class Reference
#include <DlgFilletEdges.h>
Classes
class Private
Public Types
enum FilletType { FILLET, CHAMFER }
Public Member Functions
DlgFilletEdges (FilletType type, Part::FilletBase *, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgFilletEdges () override
bool accept ()
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Protected Member Functions
void findShapes ()
void setupFillet (const std::vector< App::DocumentObject * > &)
void changeEvent (QEvent *e) override
virtual const char * getFilletType () const
Detailed Description
Definition at line 82 of file DlgFilletEdges.h.
Member Enumeration Documentation
FilletType
enum PartGui::DlgFilletEdges::FilletType
Enumerator
FILLET
CHAMFER
Definition at line 87 of file DlgFilletEdges.h.
Constructor & Destructor Documentation
DlgFilletEdges()
DlgFilletEdges::DlgFilletEdges (FilletType type, Part::FilletBase * fillet, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
Definition at line 230 of file DlgFilletEdges.cpp.
References Gui::SelectionSingleton::addSelectionGate(), draftgeoutils.faces::bind(), CHAMFER, draftgeoutils.intersections::connect(), draftgeoutils.fillets::fillet(), findShapes(), App::GetApplication(), Sketcher::Horizontal, Base::Unit::Length, Gui::Selection(), App::Application::signalDeletedObject, App::Application::signalDeleteDocument, PartGui::FilletRadiusModel::toggleCheckState(), and Path.Post.scripts.grbl_post::type.
~DlgFilletEdges()
DlgFilletEdges::~DlgFilletEdges () override
Definition at line 301 of file DlgFilletEdges.cpp.
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
accept()
bool DlgFilletEdges::accept ()
Definition at line 959 of file DlgFilletEdges.cpp.
References Gui::Command::App, App::Document::commitTransaction(), copyVisual, App::Application::getActiveDocument(), App::GetApplication(), Base::UnitsApi::getDecimals(), getFilletType(), App::Document::getUniqueObjectName(), Base::Quantity::getValue(), Gui::Application::getViewProvider(), SplineSurface::i, Gui::Application::Instance, App::Document::openTransaction(), App::Document::recompute(), runCommand, Gui::ViewProvider::show(), Path.Post.scripts.grbl_post::type, and Path.Log::warning().
Referenced by PartGui::FilletEdgesDialog::accept(), PartGui::TaskFilletEdges::accept(), and PartGui::TaskChamferEdges::accept().
changeEvent()
void DlgFilletEdges::changeEvent (QEvent * e) override protected
Sets the strings of the subwidgets using the current language.
Definition at line 739 of file DlgFilletEdges.cpp.
References src.Mod.AddonManager.NetworkManager::count, SCL.SimpleDataTypes::e, and SplineSurface::i.
findShapes()
void DlgFilletEdges::findShapes () protected
Definition at line 559 of file DlgFilletEdges.cpp.
References App::Application::getActiveDocument(), App::GetApplication(), Base::Persistence::getClassTypeId(), App::Document::getObjectsOfType(), replaceobj::objs, Gui::Selection(), and setupFillet().
Referenced by DlgFilletEdges().
getFilletType()
const char * DlgFilletEdges::getFilletType () const protected virtual
Reimplemented in PartGui::DlgChamferEdges.
Definition at line 954 of file DlgFilletEdges.cpp.
Referenced by accept().
setupFillet()
void DlgFilletEdges::setupFillet (const std::vector< App::DocumentObject * > & objs) protected
Definition at line 594 of file DlgFilletEdges.cpp.
References Gui::SelectionSingleton::addSelections(), Gui::SelectionSingleton::clearSelection(), toolbit-attributes::doc, SCL.SimpleDataTypes::e, FC_ERR, FC_WARN, DraftVecUtils::find(), Part::Feature::getRelatedElements(), Part::Feature::getTopoShape(), Gui::Application::getViewProvider(), Gui::ViewProvider::hide(), SplineSurface::i, SplineSurface::id, Gui::Application::Instance, Base::Unit::Length, replaceobj::objs, Gui::Selection(), Gui::ViewProvider::show(), Path.Post.scripts.refactored_centroid_post::str, and importers.importIFCmulticore::subs.
Referenced by findShapes().
The documentation for this class was generated from the following files:
DlgFilletEdges.h
DlgFilletEdges.cpp