FreeCAD: CAMTests.TestPathPreferences.TestPathPreferences Class Reference
CAMTests.TestPathPreferences.TestPathPreferences Class Reference
Public Member Functions
def test00 (self)
def test01 (self)
def test02 (self)
def test03 (self)
def test10 (self)
Public Member Functions inherited from CAMTests.PathTestUtils.PathTestBase
def assertRoughly (self, f1, f2, error=0.00001)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertPlacement (self, p1, p2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertArc (self, edge, pt1, pt2, direction="CW")
def assertCircle (self, edge, pt, r)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCommandEqual (self, c1, c2)
def assertEqualLocale (self, s1, s2)
def assertEdgeShapesMatch (self, e1, e2)
def assertPointsMatch (self, pts0, pts1)
def assertSuccessfulRecompute (self, doc, *objs, msg=None)
Detailed Description
Definition at line 27 of file TestPathPreferences.py.
Member Function Documentation
test00()
def CAMTests.TestPathPreferences.TestPathPreferences.test00 (self)
There is at least one search path.
Definition at line 28 of file TestPathPreferences.py.
References Path.Preferences.searchPaths().
Referenced by CAMTests.TestPathToolController.TestPathToolController.test01().
test01()
def CAMTests.TestPathPreferences.TestPathPreferences.test01 (self)
Path/Post is part of the posts search path.
Definition at line 34 of file TestPathPreferences.py.
References Path.Preferences.searchPathsPost().
test02()
def CAMTests.TestPathPreferences.TestPathPreferences.test02 (self)
Path/Post/scripts is part of the posts search path.
Definition at line 39 of file TestPathPreferences.py.
References Path.Preferences.searchPathsPost().
test03()
def CAMTests.TestPathPreferences.TestPathPreferences.test03 (self)
Available post processors include linuxcnc, grbl and opensbp.
Definition at line 44 of file TestPathPreferences.py.
References Path.Preferences.allAvailablePostProcessors().
test10()
def CAMTests.TestPathPreferences.TestPathPreferences.test10 (self)
Default paths for tools are resolved correctly
Definition at line 51 of file TestPathPreferences.py.
References Path.Preferences.pathDefaultToolsPath().
The documentation for this class was generated from the following file:
TestPathPreferences.py