FreeCAD: TechDraw::ShapeUtils Class Reference
TechDraw::ShapeUtils Class Reference
#include <ShapeUtils.h>
Static Public Member Functions
static TopoDS_Shape mirrorShapeVec (const TopoDS_Shape &input, const Base::Vector3d &inputCenter=Base::Vector3d(0.0, 0.0, 0.0), double scale=1.0)
scales & mirrors a shape about a center
static TopoDS_Shape mirrorShapeVec (TopoDS_Shape &input, const Base::Vector3d &inputCenter=Base::Vector3d(0.0, 0.0, 0.0), double scale=1.0)
scales & mirrors a shape about a center
static TopoDS_Shape mirrorShape (const TopoDS_Shape &input, const gp_Pnt &inputCenter=gp_Pnt(0.0, 0.0, 0.0), double scale=1.0)
static TopoDS_Shape invertGeometry (const TopoDS_Shape s)
another mirroring routine that modifies the shape to conform with the Qt coordinate system.
static TopoDS_Shape scaleShape (const TopoDS_Shape &input, double scale)
scales a shape uniformly in all directions
static TopoDS_Shape rotateShape (const TopoDS_Shape &input, const gp_Ax2 &coordSys, double rotAngle)
rotates a shape around the Z axis of a coordinate system
static TopoDS_Shape moveShape (const TopoDS_Shape &input, const Base::Vector3d &motion)
moves a shape in a direction and distance specified by the motion parameter
static TopoDS_Shape centerShapeXY (const TopoDS_Shape &inShape, const gp_Ax2 &coordSys)
move a shape such that its centroid is aligned with the origin point of a CoordinateSystem
static gp_Pnt findCentroid (const TopoDS_Shape &shape)
Returns the centroid of shape, as viewed according to direction.
static gp_Pnt findCentroid (const TopoDS_Shape &shape, const Base::Vector3d &direction)
Returns the centroid of shape, as viewed according to direction.
static gp_Pnt findCentroid (const TopoDS_Shape &shape, const gp_Ax2 &viewAxis)
Returns the centroid of shape, as viewed according to direction.
static Base::Vector3d findCentroidVec (const TopoDS_Shape &shape, const Base::Vector3d &direction)
static Base::Vector3d findCentroidVec (const TopoDS_Shape &shape, const gp_Ax2 &cs)
static gp_Ax2 getViewAxis (const Base::Vector3d origin, const Base::Vector3d &direction, const bool flip=true)
creates a RH coordinate system with the origin at origin and the Z axis along direction.
static gp_Ax2 getViewAxis (const Base::Vector3d origin, const Base::Vector3d &direction, const Base::Vector3d &xAxis, const bool flip=true)
gets a coordinate system specified by Z and X directions
static gp_Ax2 legacyViewAxis1 (const Base::Vector3d origin, const Base::Vector3d &direction, const bool flip=true)
static TopoDS_Shape projectSimpleShape (const TopoDS_Shape &shape, const gp_Ax2 &CS)
static TopoDS_Shape simpleProjection (const TopoDS_Shape &shape, const gp_Ax2 &projCS)
static TopoDS_Shape projectFace (const TopoDS_Shape &face, const gp_Ax2 &CS)
static std::pair< Base::Vector3d, Base::Vector3d > getEdgeEnds (TopoDS_Edge edge)
static bool isShapeReallyNull (TopoDS_Shape shape)
static bool edgesAreParallel (TopoDS_Edge edge0, TopoDS_Edge edge1)
static TopoDS_Shape fromQt (const TopoDS_Shape &inShape)
static TopoDS_Shape toQt (const TopoDS_Shape &inShape)
static TopoDS_Wire fromQtAsWire (const TopoDS_Shape &inShape)
specialization offromQt for Wire. should be templated?
static TopoDS_Face fromQtAsFace (const TopoDS_Shape &inShape)
specialization offromQt for Faces. should be templated?
Detailed Description
Definition at line 76 of file ShapeUtils.h.
Member Function Documentation
centerShapeXY()
static TopoDS_Shape TechDraw::ShapeUtils::centerShapeXY (const TopoDS_Shape & inShape, const gp_Ax2 & coordSys) static
move a shape such that its centroid is aligned with the origin point of a CoordinateSystem
edgesAreParallel()
bool ShapeUtils::edgesAreParallel (TopoDS_Edge edge0, TopoDS_Edge edge1) static
Definition at line 416 of file ShapeUtils.cpp.
References dot(), Base::Vector3< float_type >::Dot(), EWTOLERANCE, TechDraw::DrawUtil::fpCompare(), and Base::Vector3< float_type >::Normalize().
Referenced by TechDraw::DrawBrokenView::isBreakObjectSketch().
findCentroid() [1/3]
gp_Pnt ShapeUtils::findCentroid (const TopoDS_Shape & shape) static
Returns the centroid of shape, as viewed according to direction.
Returns the centroid of shape based on R3.
Definition at line 164 of file ShapeUtils.cpp.
References MovieTool::x, xMax, xMin, MovieTool::y, yMax, and yMin.
Referenced by TechDraw::DrawViewMulti::execute(), findCentroidVec(), TechDraw::DrawBrokenView::getCompressedCentroid(), TechDraw::DrawViewPart::getCurrentCentroid(), TechDraw::DrawViewSection::getCutCentroid(), TechDraw::DrawComplexSection::makeAlignedPieces(), TechDraw::DrawViewDetail::makeDetailShape(), TechDraw::DrawViewPart::makeGeometryForShape(), TechDraw::DrawViewSection::prepareShape(), and TechDraw::GeometryObject::projectShapeWithPolygonAlgo().
findCentroid() [2/3]
gp_Pnt ShapeUtils::findCentroid (const TopoDS_Shape & shape, const Base::Vector3d & direction) static
Returns the centroid of shape, as viewed according to direction.
Definition at line 179 of file ShapeUtils.cpp.
findCentroid() [3/3]
gp_Pnt ShapeUtils::findCentroid (const TopoDS_Shape & shape, const gp_Ax2 & viewAxis) static
Returns the centroid of shape, as viewed according to direction.
Definition at line 188 of file ShapeUtils.cpp.
References MovieTool::x, xMax, xMin, MovieTool::y, yMax, and yMin.
findCentroidVec() [1/2]
Base::Vector3d ShapeUtils::findCentroidVec (const TopoDS_Shape & shape, const Base::Vector3d & direction) static
Definition at line 211 of file ShapeUtils.cpp.
References findCentroid(), and buildPsets::p.
Referenced by TechDraw::CenterLine::calcEndPoints(), and TechDraw::DrawBrokenView::execute().
findCentroidVec() [2/2]
Base::Vector3d ShapeUtils::findCentroidVec (const TopoDS_Shape & shape, const gp_Ax2 & cs) static
Definition at line 218 of file ShapeUtils.cpp.
References findCentroid(), and buildPsets::p.
fromQt()
TopoDS_Shape ShapeUtils::fromQt (const TopoDS_Shape & inShape) static
transforms a shape defined in invertedY (Qt) coordinates into one defined by conventional coordinates
Definition at line 342 of file ShapeUtils.cpp.
Referenced by fromQtAsFace(), and fromQtAsWire().
fromQtAsFace()
TopoDS_Face ShapeUtils::fromQtAsFace (const TopoDS_Shape & inShape) static
specialization offromQt for Faces. should be templated?
Definition at line 354 of file ShapeUtils.cpp.
References fromQt().
Referenced by TechDraw::GeometryUtils::makePerforatedFace().
fromQtAsWire()
TopoDS_Wire ShapeUtils::fromQtAsWire (const TopoDS_Shape & inShape) static
specialization offromQt for Wire. should be templated?
Definition at line 368 of file ShapeUtils.cpp.
References fromQt().
Referenced by TechDraw::GeometryUtils::makePerforatedFace().
getEdgeEnds()
std::pair< Base::Vector3d, Base::Vector3d > ShapeUtils::getEdgeEnds (TopoDS_Edge edge) static
Definition at line 394 of file ShapeUtils.cpp.
References result, and TechDraw::DrawUtil::toVector3d().
getViewAxis() [1/2]
gp_Ax2 ShapeUtils::getViewAxis (const Base::Vector3d origin, const Base::Vector3d & direction, const Base::Vector3d & xAxis, const bool flip = true) static
gets a coordinate system specified by Z and X directions
Definition at line 111 of file ShapeUtils.cpp.
References Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
getViewAxis() [2/2]
gp_Ax2 ShapeUtils::getViewAxis (const Base::Vector3d origin, const Base::Vector3d & direction, const bool flip = true) static
creates a RH coordinate system with the origin at origin and the Z axis along direction.
gets a coordinate system that matches view system used in 3D with +Z up (or +Y up if necessary) used for individual views, but not secondary views in projection groups flip determines Y mirror or not.
Definition at line 81 of file ShapeUtils.cpp.
References TechDraw::DrawUtil::checkParallel(), Base::Vector3< float_type >::Cross(), Base::Vector3< float_type >::IsEqual(), Base::Vector3< float_type >::Normalize(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
invertGeometry()
TopoDS_Shape ShapeUtils::invertGeometry (const TopoDS_Shape s) static
another mirroring routine that modifies the shape to conform with the Qt coordinate system.
Definition at line 325 of file ShapeUtils.cpp.
References toolbit-attributes::s, and DrawingExample::Y.
Referenced by TechDraw::ReferenceEntry::asCanonicalTopoShape(), TechDraw::DrawGeomHatch::getTrimmedLinesSection(), TechDraw::BaseGeom::inverted(), TechDraw::GeometryObject::projectFace(), TechDraw::GeometryObject::projectShape(), TechDraw::GeometryObject::projectShapeWithPolygonAlgo(), and TechDraw::GeometryObject::projectSimpleShape().
isShapeReallyNull()
bool ShapeUtils::isShapeReallyNull (TopoDS_Shape shape) static
check for shape is null or shape has no subshapes(vertex/edge/face/etc) this handles the case of an empty compound which is not IsNull, but has no content.
Definition at line 410 of file ShapeUtils.cpp.
Referenced by TechDraw::ShapeExtractor::getShapes().
legacyViewAxis1()
gp_Ax2 ShapeUtils::legacyViewAxis1 (const Base::Vector3d origin, const Base::Vector3d & direction, const bool flip = true) static
Definition at line 124 of file ShapeUtils.cpp.
References TechDraw::DrawUtil::checkParallel(), Base::Vector3< float_type >::Cross(), Base::Vector3< float_type >::IsEqual(), Base::Vector3< float_type >::Normalize(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by TechDraw::DrawProjectSplit::getEdgesForWalker(), and TechDraw::DrawViewPart::getLegacyX().
mirrorShape()
TopoDS_Shape ShapeUtils::mirrorShape (const TopoDS_Shape & input, const gp_Pnt & inputCenter = gp_Pnt(0.0, 0.0, 0.0), double scale = 1.0) static
mirrors a shape around the y axis. this is need to deal with Qt's odd coordinate choice where the Y-axis has increasing values in the down direction. also performs a scaling of the input shaft
Definition at line 234 of file ShapeUtils.cpp.
Referenced by TechDraw::DrawViewMulti::execute(), mirrorShapeVec(), TechDraw::CosmeticEdge::scaledAndRotatedGeometry(), TechDraw::CenterLine::scaledAndRotatedGeometry(), TechDraw::DrawUtil::shapeVectorToCompound(), and TechDraw::DrawUtil::vectorToCompound().
mirrorShapeVec() [1/2]
TopoDS_Shape ShapeUtils::mirrorShapeVec (const TopoDS_Shape & input, const Base::Vector3d & inputCenter = Base::Vector3d(0.0, 0.0, 0.0), double scale = 1.0) static
scales & mirrors a shape about a center
Definition at line 227 of file ShapeUtils.cpp.
References mirrorShape(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
mirrorShapeVec() [2/2]
static TopoDS_Shape TechDraw::ShapeUtils::mirrorShapeVec (TopoDS_Shape & input, const Base::Vector3d & inputCenter = Base::Vector3d(0.0, 0.0, 0.0), double scale = 1.0) static
scales & mirrors a shape about a center
moveShape()
TopoDS_Shape ShapeUtils::moveShape (const TopoDS_Shape & input, const Base::Vector3d & motion) static
moves a shape in a direction and distance specified by the motion parameter
moves a shape
Definition at line 308 of file ShapeUtils.cpp.
References Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by TechDraw::DrawViewSection::alignSectionFaces(), TechDraw::CenterLine::calcEndPoints(), TechDraw::DrawViewPart::centerScaleRotate(), TechDraw::DrawGeomHatch::getTrimmedLinesSection(), TechDraw::DrawComplexSection::makeAlignedPieces(), TechDraw::DrawViewDetail::makeDetailShape(), TechDraw::DrawViewSection::postHlrTasks(), TechDraw::DrawViewSection::prepareShape(), and TechDraw::GeometryObject::projectShapeWithPolygonAlgo().
projectFace()
static TopoDS_Shape TechDraw::ShapeUtils::projectFace (const TopoDS_Shape & face, const gp_Ax2 & CS) static
projectSimpleShape()
static TopoDS_Shape TechDraw::ShapeUtils::projectSimpleShape (const TopoDS_Shape & shape, const gp_Ax2 & CS) static
rotateShape()
TopoDS_Shape ShapeUtils::rotateShape (const TopoDS_Shape & input, const gp_Ax2 & coordSys, double rotAngle) static
rotates a shape around the Z axis of a coordinate system
rotates a shape about a viewAxis
Definition at line 267 of file ShapeUtils.cpp.
References M_PI.
Referenced by TechDraw::DrawViewSection::alignSectionFaces(), TechDraw::ReferenceEntry::asCanonicalTopoShape(), TechDraw::CenterLine::calcEndPoints(), TechDraw::DrawViewPart::centerScaleRotate(), TechDraw::DrawViewMulti::execute(), TechDraw::DrawViewSection::getShapeForDetail(), TechDraw::DrawViewPart::getShapeForDetail(), TechDraw::DrawViewPart::getSizeAlongVector(), TechDraw::DrawViewDetail::makeDetailShape(), TechDraw::DrawViewSection::postHlrTasks(), TechDraw::DrawComplexSection::prepareShape(), TechDraw::DrawViewSection::prepareShape(), TechDraw::CosmeticEdge::scaledAndRotatedGeometry(), and TechDraw::CenterLine::scaledAndRotatedGeometry().
scaleShape()
TopoDS_Shape ShapeUtils::scaleShape (const TopoDS_Shape & input, double scale) static
scales a shape uniformly in all directions
scales a shape about origin
Definition at line 291 of file ShapeUtils.cpp.
Referenced by TechDraw::DrawViewSection::alignSectionFaces(), TechDraw::ReferenceEntry::asCanonicalTopoShape(), TechDraw::BaseGeom::asTopoShape(), TechDraw::DrawViewPart::centerScaleRotate(), TechDraw::DrawProjectSplit::getEdgesForWalker(), TechDraw::DrawViewDetail::makeDetailShape(), TechDraw::DrawComplexSection::makeSectionLineWire(), TechDraw::DrawViewSection::postHlrTasks(), TechDraw::DrawComplexSection::prepareShape(), TechDraw::DrawViewSection::prepareShape(), TechDraw::CosmeticEdge::scaledGeometry(), and TechDraw::CenterLine::scaledGeometry().
simpleProjection()
static TopoDS_Shape TechDraw::ShapeUtils::simpleProjection (const TopoDS_Shape & shape, const gp_Ax2 & projCS) static
toQt()
TopoDS_Shape ShapeUtils::toQt (const TopoDS_Shape & inShape) static
transforms a shape defined in conventional coordinates coordinates into one defined by invertedY (Qt) coordinates
Definition at line 383 of file ShapeUtils.cpp.
The documentation for this class was generated from the following files:
ShapeUtils.h
ShapeUtils.cpp