FreeCAD: Wm4::IntrTriangle2Triangle2< Real > Class Template Reference
Wm4::IntrTriangle2Triangle2< Real > Class Template Reference
#include <Wm4IntrTriangle2Triangle2.h>
Public Member Functions
IntrTriangle2Triangle2 (const Triangle2< Real > &rkTriangle0, const Triangle2< Real > &rkTriangle1)
const Triangle2< Real > & GetTriangle0 () const
const Triangle2< Real > & GetTriangle1 () const
virtual bool Test ()
virtual bool Find ()
virtual bool Test (Real fTMax, const Vector2< Real > &rkVelocity0, const Vector2< Real > &rkVelocity1)
virtual bool Find (Real fTMax, const Vector2< Real > &rkVelocity0, const Vector2< Real > &rkVelocity1)
int GetQuantity () const
const Vector2< Real > & GetPoint (int i) const
Public Member Functions inherited from Wm4::Intersector< Real, Vector2< Real > >
virtual ~Intersector ()
Real GetContactTime () const
int GetIntersectionType () const
Additional Inherited Members
Public Types inherited from Wm4::Intersector< Real, Vector2< Real > >
enum
Protected Member Functions inherited from Wm4::Intersector< Real, Vector2< Real > >
Intersector ()
Protected Attributes inherited from Wm4::Intersector< Real, Vector2< Real > >
Real m_fContactTime
int m_iIntersectionType
Detailed Description
template<class Real>
class Wm4::IntrTriangle2Triangle2< Real >
Definition at line 29 of file Wm4IntrTriangle2Triangle2.h.
Constructor & Destructor Documentation
IntrTriangle2Triangle2()
template<class Real > Wm4::IntrTriangle2Triangle2< Real >::IntrTriangle2Triangle2 (const Triangle2< Real > & rkTriangle0, const Triangle2< Real > & rkTriangle1)
Definition at line 24 of file Wm4IntrTriangle2Triangle2.cpp.
Member Function Documentation
Find() [1/2]
template<class Real > bool Wm4::IntrTriangle2Triangle2< Real >::Find virtual
Reimplemented from Wm4::Intersector< Real, Vector2< Real > >.
Definition at line 81 of file Wm4IntrTriangle2Triangle2.cpp.
References Wm4::Vector2< Real >::Dot(), and SplineSurface::i.
Find() [2/2]
template<class Real > bool Wm4::IntrTriangle2Triangle2< Real >::Find (Real fTMax, const Vector2< Real > & rkVelocity0, const Vector2< Real > & rkVelocity1) virtual
Reimplemented from Wm4::Intersector< Real, Vector2< Real > >.
Definition at line 165 of file Wm4IntrTriangle2Triangle2.cpp.
References Wm4::Vector2< Real >::Dot(), SplineSurface::i, Wm4::Vector2< Real >::X(), and Wm4::Vector2< Real >::Y().
GetPoint()
template<class Real > const Vector2< Real > & Wm4::IntrTriangle2Triangle2< Real >::GetPoint (int i) const
Definition at line 237 of file Wm4IntrTriangle2Triangle2.cpp.
References SplineSurface::i.
GetQuantity()
template<class Real > int Wm4::IntrTriangle2Triangle2< Real >::GetQuantity
Definition at line 231 of file Wm4IntrTriangle2Triangle2.cpp.
GetTriangle0()
template<class Real > const Triangle2< Real > & Wm4::IntrTriangle2Triangle2< Real >::GetTriangle0
Definition at line 34 of file Wm4IntrTriangle2Triangle2.cpp.
GetTriangle1()
template<class Real > const Triangle2< Real > & Wm4::IntrTriangle2Triangle2< Real >::GetTriangle1
Definition at line 40 of file Wm4IntrTriangle2Triangle2.cpp.
Test() [1/2]
template<class Real > bool Wm4::IntrTriangle2Triangle2< Real >::Test virtual
Reimplemented from Wm4::Intersector< Real, Vector2< Real > >.
Definition at line 46 of file Wm4IntrTriangle2Triangle2.cpp.
References Wm4::Vector2< Real >::X(), and Wm4::Vector2< Real >::Y().
Test() [2/2]
template<class Real > bool Wm4::IntrTriangle2Triangle2< Real >::Test (Real fTMax, const Vector2< Real > & rkVelocity0, const Vector2< Real > & rkVelocity1) virtual
Reimplemented from Wm4::Intersector< Real, Vector2< Real > >.
Definition at line 110 of file Wm4IntrTriangle2Triangle2.cpp.
References Wm4::Vector2< Real >::Dot(), Wm4::Vector2< Real >::X(), and Wm4::Vector2< Real >::Y().
The documentation for this class was generated from the following files:
Wm4IntrTriangle2Triangle2.h
Wm4IntrTriangle2Triangle2.cpp