FreeCAD: Wm4::DistVector3Plane3< Real > Class Template Reference
Wm4::DistVector3Plane3< Real > Class Template Reference
#include <Wm4DistVector3Plane3.h>
Public Member Functions
DistVector3Plane3 (const Vector3< Real > &rkVector, const Plane3< Real > &rkPlane)
const Vector3< Real > & GetVector () const
const Plane3< Real > & GetPlane () const
virtual Real Get ()
virtual Real GetSquared ()
virtual Real Get (Real fT, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
virtual Real GetSquared (Real fT, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
Public Member Functions inherited from Wm4::Distance< Real, Vector3< Real > >
virtual ~Distance ()
virtual Real Get (Real fTMin, Real fTMax, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
virtual Real GetSquared (Real fTMin, Real fTMax, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
virtual Real GetDerivative (Real fT, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
virtual Real GetDerivativeSquared (Real fT, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
void SetDifferenceStep (Real fDifferenceStep)
Real GetDifferenceStep () const
Real GetContactTime () const
const Vector3< Real > & GetClosestPoint0 () const
const Vector3< Real > & GetClosestPoint1 () const
bool HasMultipleClosestPoints0 () const
bool HasMultipleClosestPoints1 () const
Additional Inherited Members
Public Attributes inherited from Wm4::Distance< Real, Vector3< Real > >
int MaximumIterations
Real ZeroThreshold
Protected Member Functions inherited from Wm4::Distance< Real, Vector3< Real > >
Distance ()
Protected Attributes inherited from Wm4::Distance< Real, Vector3< Real > >
Real m_fContactTime
Vector3< Real > m_kClosestPoint0
Vector3< Real > m_kClosestPoint1
bool m_bHasMultipleClosestPoints0
bool m_bHasMultipleClosestPoints1
Real m_fDifferenceStep
Real m_fInvTwoDifferenceStep
Detailed Description
template<class Real>
class Wm4::DistVector3Plane3< Real >
Definition at line 28 of file Wm4DistVector3Plane3.h.
Constructor & Destructor Documentation
DistVector3Plane3()
template<class Real > Wm4::DistVector3Plane3< Real >::DistVector3Plane3 (const Vector3< Real > & rkVector, const Plane3< Real > & rkPlane)
Definition at line 24 of file Wm4DistVector3Plane3.cpp.
Member Function Documentation
Get() [1/2]
template<class Real > Real Wm4::DistVector3Plane3< Real >::Get virtual
Implements Wm4::Distance< Real, Vector3< Real > >.
Definition at line 45 of file Wm4DistVector3Plane3.cpp.
References Wm4::Math< Real >::FAbs().
Referenced by Wm4::DistVector3Plane3< Real >::Get().
Get() [2/2]
template<class Real > Real Wm4::DistVector3Plane3< Real >::Get (Real fT, const Vector3< Real > & rkVelocity0, const Vector3< Real > & rkVelocity1) virtual
Implements Wm4::Distance< Real, Vector3< Real > >.
Definition at line 63 of file Wm4DistVector3Plane3.cpp.
References Wm4::Vector3< Real >::Dot(), and Wm4::DistVector3Plane3< Real >::Get().
GetPlane()
template<class Real > const Plane3< Real > & Wm4::DistVector3Plane3< Real >::GetPlane
Definition at line 39 of file Wm4DistVector3Plane3.cpp.
GetSquared() [1/2]
template<class Real > Real Wm4::DistVector3Plane3< Real >::GetSquared virtual
Implements Wm4::Distance< Real, Vector3< Real > >.
Definition at line 54 of file Wm4DistVector3Plane3.cpp.
Referenced by Wm4::DistVector3Plane3< Real >::GetSquared().
GetSquared() [2/2]
template<class Real > Real Wm4::DistVector3Plane3< Real >::GetSquared (Real fT, const Vector3< Real > & rkVelocity0, const Vector3< Real > & rkVelocity1) virtual
Implements Wm4::Distance< Real, Vector3< Real > >.
Definition at line 75 of file Wm4DistVector3Plane3.cpp.
References Wm4::Vector3< Real >::Dot(), and Wm4::DistVector3Plane3< Real >::GetSquared().
GetVector()
template<class Real > const Vector3< Real > & Wm4::DistVector3Plane3< Real >::GetVector
Definition at line 33 of file Wm4DistVector3Plane3.cpp.
The documentation for this class was generated from the following files:
Wm4DistVector3Plane3.h
Wm4DistVector3Plane3.cpp