FreeCAD: Base::UnitsApi Class Reference
Base::UnitsApi Class Reference
#include <UnitsApi.h>
Static Public Member Functions
static void setSchema (UnitSystem s)
static UnitSystem getSchema ()
return the active schema
static QString getDescription (UnitSystem)
Returns a brief description of a schema.
static std::string schemaTranslate (const Base::Quantity &quant, double &factor, std::string &unitString)
static std::string schemaTranslate (const Base::Quantity &quant)
static std::string toString (const Base::Quantity &q, const QuantityFormat &f=QuantityFormat(QuantityFormat::Default))
static std::string toNumber (const Base::Quantity &q, const QuantityFormat &f=QuantityFormat(QuantityFormat::Default))
static std::string toNumber (double value, const QuantityFormat &f=QuantityFormat(QuantityFormat::Default))
static double toDouble (PyObject *args, const Base::Unit &u=Base::Unit())
generate a value for a quantity with default user preferred system
static Quantity toQuantity (PyObject *args, const Base::Unit &u=Base::Unit())
generate a value for a quantity with default user preferred system
static void setDecimals (int)
static int getDecimals ()
static bool isMultiUnitLength ()
static bool isMultiUnitAngle ()
static std::string getBasicLengthUnit ()
static UnitsSchemaPtr createSchema (UnitSystem s)
return an instance of the given enum value
Static Public Attributes
static PyMethodDef Methods []
Static Protected Member Functions
static PyObject * sParseQuantity (PyObject *self, PyObject *args)
static PyObject * sListSchemas (PyObject *self, PyObject *args)
static PyObject * sGetSchema (PyObject *self, PyObject *args)
static PyObject * sSetSchema (PyObject *self, PyObject *args)
static PyObject * sSchemaTranslate (PyObject *self, PyObject *args)
static PyObject * sToNumber (PyObject *self, PyObject *args)
Static Protected Attributes
static UnitsSchemaPtr UserPrefSystem
static UnitSystem currentSystem = UnitSystem::SI1
static int UserPrefDecimals = 2
number of decimals for floats
Detailed Description
The UnitsApi
Definition at line 43 of file UnitsApi.h.
Member Function Documentation
createSchema()
UnitsSchemaPtr UnitsApi::createSchema (UnitSystem s) static
return an instance of the given enum value
Definition at line 82 of file UnitsApi.cpp.
References Base::Centimeters, Base::FemMilliMeterNewton, Base::Imperial1, Base::ImperialBuilding, Base::ImperialCivil, Base::ImperialDecimal, Base::MeterDecimal, Base::MmMin, Base::SI1, and Base::SI2.
Referenced by setSchema(), Gui::QuantitySpinBox::setSchema(), and sSchemaTranslate().
getBasicLengthUnit()
std::string UnitsApi::getBasicLengthUnit () static
Definition at line 172 of file UnitsApi.cpp.
References UserPrefSystem.
Referenced by TechDraw::DimensionFormatter::formatValue().
getDecimals()
int UnitsApi::getDecimals () static
Definition at line 234 of file UnitsApi.cpp.
References UserPrefDecimals.
Referenced by PartGui::DlgFilletEdges::accept(), FemGui::BoxWidget::BoxWidget(), TechDrawGui::VectorEditWidget::buildWidget(), PartGui::CircleFromThreePoints::command(), FemGui::CylinderWidget::CylinderWidget(), SpreadsheetGui::SheetModel::data(), PartGui::DlgExtrusion::DlgExtrusion(), PartGui::DlgScale::DlgScale(), Gui::Dialog::DlgUnitsCalculator::DlgUnitsCalculator(), TechDraw::DimensionFormatter::formatValue(), TechDraw::DrawUtil::formatVector(), TechDraw::DimensionFormatter::getDefaultFormatSpec(), Spreadsheet::Cell::getFormattedQuantity(), TechDrawGui::QGIDatumLabel::getPrecision(), Gui::getPreselectionInfo(), Gui::LocationWidget::getUserDirection(), Gui::LocationDialog::getUserDirection(), Gui::Dialog::DlgSettingsGeneral::loadSettings(), PartGui::SectionCut::onCutXHSsliderMoved(), PartGui::SectionCut::onCutYHSsliderMoved(), PartGui::SectionCut::onCutZHSsliderMoved(), FemGui::PlaneWidget::PlaneWidget(), PartDesignGui::TaskBoxPrimitives::setPrimitive(), TechDrawGui::TaskCenterLine::setUiEdit(), TechDrawGui::TaskDetail::setUiFromFeat(), TechDrawGui::TaskCenterLine::setUiPrimary(), TechDrawGui::TaskCosVertex::setUiPrimary(), PartDesignGui::TaskExtrudeParameters::setupDialog(), PartGui::ShapeFromMesh::ShapeFromMesh(), Gui::Application::slotActiveDocument(), FemGui::SphereWidget::SphereWidget(), FemGui::TaskPostDataAlongLine::TaskPostDataAlongLine(), FemGui::TaskPostDataAtPoint::TaskPostDataAtPoint(), PartGui::Picker::toPlacement(), PartGui::Location::toPlacement(), and Gui::Dialog::DlgUnitsCalculator::valueChanged().
getDescription()
QString UnitsApi::getDescription (UnitSystem system) static
Returns a brief description of a schema.
Definition at line 54 of file UnitsApi.cpp.
References Base::Centimeters, Base::FemMilliMeterNewton, Base::Imperial1, Base::ImperialBuilding, Base::ImperialCivil, Base::ImperialDecimal, Base::MeterDecimal, Base::MmMin, Base::SI1, and Base::SI2.
Referenced by Gui::Dialog::DlgProjectInformationImp::DlgProjectInformationImp(), Gui::Dialog::DlgSettingsGeneral::DlgSettingsGeneral(), Gui::Dialog::DlgUnitsCalculator::DlgUnitsCalculator(), App::Document::Document(), and sListSchemas().
getSchema()
static UnitSystem Base::UnitsApi::getSchema () inline static
return the active schema
Definition at line 56 of file UnitsApi.h.
isMultiUnitAngle()
bool UnitsApi::isMultiUnitAngle () static
Definition at line 167 of file UnitsApi.cpp.
References UserPrefSystem.
Referenced by SketcherGui::angleToDisplayFormat(), and TechDraw::DimensionFormatter::isMultiValueSchema().
isMultiUnitLength()
bool UnitsApi::isMultiUnitLength () static
Definition at line 161 of file UnitsApi.cpp.
References UserPrefSystem.
Referenced by TechDraw::DimensionFormatter::isMultiValueSchema(), and SketcherGui::lengthToDisplayFormat().
schemaTranslate() [1/2]
static std::string Base::UnitsApi::schemaTranslate (const Base::Quantity & quant) inline static
Definition at line 65 of file UnitsApi.h.
References schemaTranslate().
schemaTranslate() [2/2]
std::string UnitsApi::schemaTranslate (const Base::Quantity & quant, double & factor, std::string & unitString) static
Definition at line 180 of file UnitsApi.cpp.
References UserPrefSystem.
Referenced by Base::Quantity::getUserString(), SketcherGui::lengthToDisplayFormat(), Gui::View3DInventorViewer::printDimension(), schemaTranslate(), Gui::schemaTranslatePoint(), and Gui::QuantitySpinBoxPrivate::validate().
setDecimals()
void UnitsApi::setDecimals (int prec) static
Definition at line 229 of file UnitsApi.cpp.
References UserPrefDecimals.
Referenced by Gui::Application::slotActiveDocument().
setSchema()
void UnitsApi::setSchema (UnitSystem s) static
set Schema set the UnitsSchema of the Application this a represented by a class of type UnitSchema which defines a set of standard units for that schema and rules for representative strings.
Definition at line 112 of file UnitsApi.cpp.
References createSchema(), currentSystem, Base::SI1, and UserPrefSystem.
Referenced by Gui::DimensionWidget::setUserSchema(), Gui::Application::slotActiveDocument(), and sSetSchema().
sGetSchema()
PyObject * UnitsApi::sGetSchema (PyObject * self, PyObject * args) static protected
Definition at line 135 of file UnitsApiPy.cpp.
References toolbit-attributes::args, and currentSystem.
sListSchemas()
PyObject * UnitsApi::sListSchemas (PyObject * self, PyObject * args) static protected
Definition at line 103 of file UnitsApiPy.cpp.
References toolbit-attributes::args, getDescription(), SplineSurface::i, Py::new_reference_to(), Base::NumUnitSystemTypes, and src.Mod.Test.testmakeWireString::String.
sParseQuantity()
PyObject * UnitsApi::sParseQuantity (PyObject * self, PyObject * args) static protected
Definition at line 82 of file UnitsApiPy.cpp.
References toolbit-attributes::args, Base::Quantity::parse(), src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::Quantity, and Path.Post.scripts.refactored_centroid_post::str.
sSchemaTranslate()
PyObject * UnitsApi::sSchemaTranslate (PyObject * self, PyObject * args) static protected
Definition at line 159 of file UnitsApiPy.cpp.
References toolbit-attributes::args, createSchema(), Py::new_reference_to(), and src.Mod.Test.testmakeWireString::String.
sSetSchema()
PyObject * UnitsApi::sSetSchema (PyObject * self, PyObject * args) static protected
Definition at line 144 of file UnitsApiPy.cpp.
References toolbit-attributes::args, Base::NumUnitSystemTypes, Py_Return, and setSchema().
sToNumber()
PyObject * UnitsApi::sToNumber (PyObject * self, PyObject * args) static protected
Definition at line 188 of file UnitsApiPy.cpp.
References toolbit-attributes::args, Base::QuantityFormat::format, Py::new_reference_to(), Base::QuantityFormat::precision, src.Mod.Test.testmakeWireString::String, Base::QuantityFormat::toFormat(), and toNumber().
toDouble()
double UnitsApi::toDouble (PyObject * args, const Base::Unit & u = Base::Unit()) static
generate a value for a quantity with default user preferred system
Definition at line 185 of file UnitsApi.cpp.
References toolbit-attributes::args, Base::Quantity::getUnit(), Base::Quantity::getValue(), Base::Quantity::parse(), Path.Post.scripts.refactored_centroid_post::str, and buildPsets::u.
toNumber() [1/2]
std::string UnitsApi::toNumber (const Base::Quantity & q, const QuantityFormat & f = QuantityFormat(QuantityFormat::Default)) static
Get a number as string for a quantity of a given format. The string is a number in C locale (i.e. the decimal separator is always a dot) and if needed represented in scientific notation. The string doesn't include the unit of the quantity.
Definition at line 136 of file UnitsApi.cpp.
References Base::Quantity::getValue().
Referenced by Gui::PropertyEditor::PropertyVectorDistanceItem::setValue(), Gui::PropertyEditor::PropertyRotationItem::setValue(), Gui::PropertyEditor::PropertyPlacementItem::setValue(), sToNumber(), and toString().
toNumber() [2/2]
std::string UnitsApi::toNumber (double value, const QuantityFormat & f = QuantityFormat(QuantityFormat::Default)) static
Get a number as string for a double of a given format. The string is a number in C locale (i.e. the decimal separator is always a dot) and if needed represented in scientific notation. The string doesn't include the unit of the quantity.
Definition at line 141 of file UnitsApi.cpp.
References Base::QuantityFormat::Fixed, Base::QuantityFormat::format, Base::QuantityFormat::precision, and Base::QuantityFormat::Scientific.
toQuantity()
Quantity UnitsApi::toQuantity (PyObject * args, const Base::Unit & u = Base::Unit()) static
generate a value for a quantity with default user preferred system
Definition at line 207 of file UnitsApi.cpp.
References toolbit-attributes::args, Base::Quantity::getValue(), Base::Quantity::parse(), src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::Quantity, Path.Post.scripts.refactored_centroid_post::str, and buildPsets::u.
toString()
std::string UnitsApi::toString (const Base::Quantity & q, const QuantityFormat & f = QuantityFormat(QuantityFormat::Default)) static
Get a number as string for a quantity of a given format. The string is a number in C locale (i.e. the decimal separator is always a dot) and if needed represented in scientific notation. The string also includes the unit of the quantity.
Definition at line 131 of file UnitsApi.cpp.
References Base::Unit::getString(), Base::Quantity::getUnit(), and toNumber().
Referenced by Gui::PropertyEditor::PropertyUnitItem::setValue().
Member Data Documentation
currentSystem
UnitSystem UnitsApi::currentSystem = UnitSystem::SI1 static protected
Definition at line 123 of file UnitsApi.h.
Referenced by setSchema(), and sGetSchema().
Methods
PyMethodDef UnitsApi::Methods static
Definition at line 116 of file UnitsApi.h.
UserPrefDecimals
int UnitsApi::UserPrefDecimals = 2 static protected
number of decimals for floats
Definition at line 125 of file UnitsApi.h.
Referenced by getDecimals(), and setDecimals().
UserPrefSystem
UnitsSchemaPtr UnitsApi::UserPrefSystem static protected
Definition at line 122 of file UnitsApi.h.
Referenced by getBasicLengthUnit(), isMultiUnitAngle(), isMultiUnitLength(), schemaTranslate(), and setSchema().
The documentation for this class was generated from the following files:
UnitsApi.h
UnitsApi.cpp
UnitsApiPy.cpp