FreeCAD: SketcherGui::SketchRectangularArrayDialog Class Reference
SketcherGui::SketchRectangularArrayDialog Class Reference
#include <SketchRectangularArrayDialog.h>
Public Member Functions
SketchRectangularArrayDialog ()
~SketchRectangularArrayDialog () override
void accept () override
Public Attributes
int Rows
int Cols
bool ConstraintSeparation
bool EqualVerticalHorizontalSpacing
bool Clone
Protected Member Functions
void updateValues ()
Detailed Description
Definition at line 53 of file SketchRectangularArrayDialog.h.
Constructor & Destructor Documentation
SketchRectangularArrayDialog()
SketchRectangularArrayDialog::SketchRectangularArrayDialog ()
Definition at line 36 of file SketchRectangularArrayDialog.cpp.
References updateValues().
~SketchRectangularArrayDialog()
SketchRectangularArrayDialog::~SketchRectangularArrayDialog () override
Definition at line 51 of file SketchRectangularArrayDialog.cpp.
Member Function Documentation
accept()
void SketchRectangularArrayDialog::accept () override
Definition at line 54 of file SketchRectangularArrayDialog.cpp.
References updateValues().
updateValues()
void SketchRectangularArrayDialog::updateValues () protected
Definition at line 67 of file SketchRectangularArrayDialog.cpp.
References Clone, Cols, ConstraintSeparation, EqualVerticalHorizontalSpacing, and Rows.
Referenced by accept(), and SketchRectangularArrayDialog().
Member Data Documentation
Clone
bool SketcherGui::SketchRectangularArrayDialog::Clone
Definition at line 67 of file SketchRectangularArrayDialog.h.
Referenced by updateValues().
Cols
int SketcherGui::SketchRectangularArrayDialog::Cols
Definition at line 64 of file SketchRectangularArrayDialog.h.
Referenced by updateValues().
ConstraintSeparation
bool SketcherGui::SketchRectangularArrayDialog::ConstraintSeparation
Definition at line 65 of file SketchRectangularArrayDialog.h.
Referenced by updateValues().
EqualVerticalHorizontalSpacing
bool SketcherGui::SketchRectangularArrayDialog::EqualVerticalHorizontalSpacing
Definition at line 66 of file SketchRectangularArrayDialog.h.
Referenced by updateValues().
Rows
int SketcherGui::SketchRectangularArrayDialog::Rows
Definition at line 63 of file SketchRectangularArrayDialog.h.
Referenced by updateValues().
The documentation for this class was generated from the following files:
SketchRectangularArrayDialog.h
SketchRectangularArrayDialog.cpp