FreeCAD: MillSim::StockObject Class Reference
MillSim::StockObject Class Reference
#include <StockObject.h>
Public Member Functions
StockObject ()
void GenerateBoxStock (float x, float y, float z, float l, float w, float h)
Public Member Functions inherited from MillSim::SolidObject
SolidObject ()
virtual ~SolidObject ()
void SetPosition (vec3 position)
virtual void render ()
Calls the display list.
void GenerateSolid (std::vector< Vertex > &verts, std::vector< GLushort > &indices)
Additional Inherited Members
Public Attributes inherited from MillSim::SolidObject
Shape shape
vec3 center = {}
vec3 size = {}
vec3 position = {}
bool isValid = false
Protected Attributes inherited from MillSim::SolidObject
mat4x4 mModelMat
Detailed Description
Definition at line 51 of file StockObject.h.
Constructor & Destructor Documentation
StockObject()
StockObject::StockObject ()
Definition at line 29 of file StockObject.cpp.
Member Function Documentation
GenerateBoxStock()
void StockObject::GenerateBoxStock (float x, float y, float z, float l, float w, float h)
Definition at line 32 of file StockObject.cpp.
References MillSim::SolidObject::center, MillSim::Shape::ExtrudeProfileLinear(), RobotExample::l, NUM_PROFILE_POINTS, MillSim::SolidObject::position, SET_DUAL, MillSim::SolidObject::shape, MillSim::SolidObject::size, vec3_set(), src.Mod.PartDesign.fcgear.svggear::w, MovieTool::x, and MovieTool::y.
Referenced by MillSim::MillSimulation::SetBoxStock().
The documentation for this class was generated from the following files:
StockObject.h
StockObject.cpp