FreeCAD: MeshGui::DlgSmoothing Class Reference
MeshGui::DlgSmoothing Class Reference
#include <DlgSmoothing.h>
Public Types
enum Smooth { None, Taubin, Laplace, MedianFilter }
Signals
void toggledSelection (bool)
Public Member Functions
DlgSmoothing (QWidget *parent=nullptr)
~DlgSmoothing () override
int iterations () const
double lambdaStep () const
double microStep () const
Smooth method () const
bool smoothSelection () const
Detailed Description
Definition at line 41 of file DlgSmoothing.h.
Member Enumeration Documentation
Smooth
enum MeshGui::DlgSmoothing::Smooth
Enumerator
None
Taubin
Laplace
MedianFilter
Definition at line 46 of file DlgSmoothing.h.
Constructor & Destructor Documentation
DlgSmoothing()
DlgSmoothing::DlgSmoothing (QWidget * parent = nullptr) explicit
Definition at line 44 of file DlgSmoothing.cpp.
References draftgeoutils.intersections::connect().
~DlgSmoothing()
DlgSmoothing::~DlgSmoothing () override
Definition at line 73 of file DlgSmoothing.cpp.
Member Function Documentation
iterations()
int DlgSmoothing::iterations () const
Definition at line 91 of file DlgSmoothing.cpp.
Referenced by MeshGui::TaskSmoothing::accept().
lambdaStep()
double DlgSmoothing::lambdaStep () const
Definition at line 96 of file DlgSmoothing.cpp.
Referenced by MeshGui::TaskSmoothing::accept().
method()
DlgSmoothing::Smooth DlgSmoothing::method () const
Definition at line 106 of file DlgSmoothing.cpp.
References Laplace, None, and Taubin.
Referenced by MeshGui::TaskSmoothing::accept().
microStep()
double DlgSmoothing::microStep () const
Definition at line 101 of file DlgSmoothing.cpp.
Referenced by MeshGui::TaskSmoothing::accept().
smoothSelection()
bool DlgSmoothing::smoothSelection () const
Definition at line 117 of file DlgSmoothing.cpp.
Referenced by MeshGui::TaskSmoothing::accept().
toggledSelection
void MeshGui::DlgSmoothing::toggledSelection (bool) signal
Referenced by MeshGui::TaskSmoothing::TaskSmoothing().
The documentation for this class was generated from the following files:
DlgSmoothing.h
DlgSmoothing.cpp