FreeCAD: MeshGui::SoFCIndexedFaceSet Class Reference
MeshGui::SoFCIndexedFaceSet Class Reference
The SoFCIndexedFaceSet class is designed to optimize redrawing a mesh during user interaction.
#include <SoFCIndexedFaceSet.h>
Public Member Functions
SoFCIndexedFaceSet ()
void invalidate ()
Static Public Member Functions
static void initClass ()
Public Attributes
SoSFBool updateGLArray
unsigned int renderTriangleLimit
Protected Member Functions
~SoFCIndexedFaceSet () override=default
void GLRender (SoGLRenderAction *action) override
void drawFaces (SoGLRenderAction *action)
void drawCoords (const SoGLCoordinateElement *const vertexlist, const int32_t *vertexindices, int numindices, const SbVec3f *normals, const int32_t *normalindices, SoMaterialBundle *materials, const int32_t *matindices, const int32_t binding, const SoTextureCoordinateBundle *const texcoords, const int32_t *texindices)
void doAction (SoAction *action) override
Detailed Description
The SoFCIndexedFaceSet class is designed to optimize redrawing a mesh during user interaction.
class SoFCIndexedFaceSet
Author
Werner Mayer
Definition at line 100 of file SoFCIndexedFaceSet.h.
Constructor & Destructor Documentation
SoFCIndexedFaceSet()
SoFCIndexedFaceSet::SoFCIndexedFaceSet ()
Definition at line 462 of file SoFCIndexedFaceSet.cpp.
References updateGLArray.
~SoFCIndexedFaceSet()
MeshGui::SoFCIndexedFaceSet::~SoFCIndexedFaceSet () override protected default
Member Function Documentation
doAction()
void SoFCIndexedFaceSet::doAction (SoAction * action) override protected
Definition at line 925 of file SoFCIndexedFaceSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action.
drawCoords()
void SoFCIndexedFaceSet::drawCoords (const SoGLCoordinateElement *const vertexlist, const int32_t * vertexindices, int numindices, const SbVec3f * normals, const int32_t * normalindices, SoMaterialBundle * materials, const int32_t * matindices, const int32_t binding, const SoTextureCoordinateBundle *const texcoords, const int32_t * texindices) protected
Definition at line 618 of file SoFCIndexedFaceSet.cpp.
References importers.importIFCmulticore::materials, mod, MeshCore::MeshIO::PER_FACE, MeshCore::MeshIO::PER_VERTEX, renderTriangleLimit, and draftgeoutils.general::v1().
Referenced by drawFaces().
drawFaces()
void SoFCIndexedFaceSet::drawFaces (SoGLRenderAction * action) protected
Definition at line 531 of file SoFCIndexedFaceSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action, MeshGui::MeshRenderer::canRenderGLArray(), drawCoords(), Gui::SoFCInteractiveElement::get(), MeshCore::MeshIO::OVERALL, MeshGui::MeshRenderer::renderCoordsGLArray(), MeshGui::MeshRenderer::renderFacesGLArray(), renderTriangleLimit, and updateGLArray.
Referenced by GLRender().
GLRender()
void SoFCIndexedFaceSet::GLRender (SoGLRenderAction * action) override protected
Either renders the complete mesh or only a subset of the points.
Definition at line 474 of file SoFCIndexedFaceSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action, MeshGui::MeshRenderer::canRenderGLArray(), drawFaces(), Gui::SoGLVBOActivatedElement::get(), MeshGui::MeshRenderer::matchMaterial(), MeshGui::MeshRenderer::needUpdate(), MeshGui::MeshRenderer::renderFacesGLArray(), MeshGui::MeshRenderer::update(), and updateGLArray.
initClass()
void SoFCIndexedFaceSet::initClass () static
Definition at line 457 of file SoFCIndexedFaceSet.cpp.
Referenced by PyMOD_INIT_FUNC().
invalidate()
void SoFCIndexedFaceSet::invalidate ()
Definition at line 716 of file SoFCIndexedFaceSet.cpp.
References updateGLArray.
Referenced by MeshGui::ViewProviderMeshFaceSet::updateData().
Member Data Documentation
renderTriangleLimit
unsigned int MeshGui::SoFCIndexedFaceSet::renderTriangleLimit
Definition at line 111 of file SoFCIndexedFaceSet.h.
Referenced by drawCoords(), and drawFaces().
updateGLArray
SoSFBool MeshGui::SoFCIndexedFaceSet::updateGLArray
Definition at line 110 of file SoFCIndexedFaceSet.h.
Referenced by drawFaces(), GLRender(), invalidate(), and SoFCIndexedFaceSet().
The documentation for this class was generated from the following files:
SoFCIndexedFaceSet.h
SoFCIndexedFaceSet.cpp