FreeCAD: Gui::View3DSettings Class Reference
Gui::View3DSettings Class Reference
#include <View3DSettings.h>
Public Member Functions
View3DSettings (ParameterGrp::handle hGrp, View3DInventorViewer *)
View3DSettings (ParameterGrp::handle hGrp, const std::vector< View3DInventorViewer * > &)
~View3DSettings () override
void OnChange (ParameterGrp::SubjectType &rCaller, ParameterGrp::MessageType Reason) override
Observer message from the ParameterGrp.
void applySettings ()
int stopAnimatingIfDeactivated () const
Public Attributes
bool ignoreNavigationStyle = false
bool ignoreVBO = false
bool ignoreDimensions = false
bool ignoreRenderCache = false
bool ignoreTransparent = false
Detailed Description
Definition at line 53 of file View3DSettings.h.
Constructor & Destructor Documentation
View3DSettings() [1/2]
View3DSettings::View3DSettings (ParameterGrp::handle hGrp, View3DInventorViewer * view)
Definition at line 43 of file View3DSettings.cpp.
View3DSettings() [2/2]
View3DSettings::View3DSettings (ParameterGrp::handle hGrp, const std::vector< View3DInventorViewer * > & view)
Definition at line 51 of file View3DSettings.cpp.
References Base::Subject< MsgType >::Attach().
~View3DSettings()
View3DSettings::~View3DSettings () override
Definition at line 59 of file View3DSettings.cpp.
References Base::Subject< MsgType >::Detach().
Member Function Documentation
applySettings()
void View3DSettings::applySettings ()
Definition at line 70 of file View3DSettings.cpp.
References OnChange().
OnChange()
void View3DSettings::OnChange (ParameterGrp::SubjectType & rCaller, ParameterGrp::MessageType Reason) override
Observer message from the ParameterGrp.
Definition at line 111 of file View3DSettings.cpp.
References Gui::NavigationStyle::BoundingBoxCenter, SCL.SimpleDataTypes::f, Gui::NavigationStyle::FocalPointAtCursor, Base::Type::fromName(), ParameterGrp::GetASCII(), ParameterGrp::GetBool(), Base::BaseClass::getClassTypeId(), ParameterGrp::GetFloat(), ParameterGrp::GetInt(), ParameterGrp::GetUnsigned(), highlight(), ignoreDimensions, ignoreNavigationStyle, ignoreRenderCache, ignoreTransparent, ignoreVBO, OpenSCADFeatures::long, RobotExample::pos, Gui::NavigationStyle::ScenePointAtCursor, Path.Dressup.Utils::selection(), Base::to_vector(), Path.Post.scripts.grbl_post::type, toolbit-attributes::val, Gui::NavigationStyle::WindowCenter, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by applySettings().
stopAnimatingIfDeactivated()
int View3DSettings::stopAnimatingIfDeactivated () const
Definition at line 64 of file View3DSettings.cpp.
References ParameterGrp::GetInt().
Member Data Documentation
ignoreDimensions
bool Gui::View3DSettings::ignoreDimensions = false
Definition at line 67 of file View3DSettings.h.
Referenced by OnChange().
ignoreNavigationStyle
bool Gui::View3DSettings::ignoreNavigationStyle = false
Definition at line 65 of file View3DSettings.h.
Referenced by OnChange().
ignoreRenderCache
bool Gui::View3DSettings::ignoreRenderCache = false
Definition at line 68 of file View3DSettings.h.
Referenced by OnChange().
ignoreTransparent
bool Gui::View3DSettings::ignoreTransparent = false
Definition at line 69 of file View3DSettings.h.
Referenced by OnChange().
ignoreVBO
bool Gui::View3DSettings::ignoreVBO = false
Definition at line 66 of file View3DSettings.h.
Referenced by OnChange().
The documentation for this class was generated from the following files:
View3DSettings.h
View3DSettings.cpp