FreeCAD: Import::Tools Struct Reference
Import::Tools Struct Reference
#include <Tools.h>
Static Public Member Functions
static App::Color convertColor (const Quantity_ColorRGBA &rgba)
static Quantity_ColorRGBA convertColor (const App::Color &col)
static std::string labelName (TDF_Label label)
static void printLabel (TDF_Label label, Handle(XCAFDoc_ShapeTool) aShapeTool, Handle(XCAFDoc_ColorTool) aColorTool, const char *msg=nullptr)
static void dumpLabels (TDF_Label label, Handle(XCAFDoc_ShapeTool) aShapeTool, Handle(XCAFDoc_ColorTool) aColorTool, int depth=0)
Detailed Description
Definition at line 81 of file Mod/Import/App/Tools.h.
Member Function Documentation
convertColor() [1/2]
Quantity_ColorRGBA Tools::convertColor (const App::Color & col) static
Definition at line 59 of file Mod/Import/App/Tools.cpp.
References App::Color::a, App::Color::b, App::Color::g, OCC_COLOR_SPACE, and App::Color::r.
convertColor() [2/2]
App::Color Tools::convertColor (const Quantity_ColorRGBA & rgba) static
Definition at line 49 of file Mod/Import/App/Tools.cpp.
References blue, green, OCC_COLOR_SPACE, and red.
Referenced by operator<<().
dumpLabels()
void Tools::dumpLabels (TDF_Label label, Handle(XCAFDoc_ShapeTool) aShapeTool, Handle(XCAFDoc_ColorTool) aColorTool, int depth = 0) static
Definition at line 134 of file Mod/Import/App/Tools.cpp.
References indent, and printLabel().
Referenced by Import::ExportOCAF2::exportObjects(), and Import::ImportOCAF2::loadShapes().
labelName()
std::string Tools::labelName (TDF_Label label) static
Definition at line 73 of file Mod/Import/App/Tools.cpp.
References Handle(), Path.Post.scripts.refactored_centroid_post::str, Materials::trim(), and create_qrc::txt.
Referenced by Import::ImportOCAF2::loadShapes(), and printLabel().
printLabel()
void Tools::printLabel (TDF_Label label, Handle(XCAFDoc_ShapeTool) aShapeTool, Handle(XCAFDoc_ColorTool) aColorTool, const char * msg = nullptr) static
Definition at line 88 of file Mod/Import/App/Tools.cpp.
References SCL.SimpleDataTypes::c, Base::Console(), FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, labelName(), Base::Log, Path.Op.Surface::msg, Base::ConsoleSingleton::Notify(), and Part::TopoShape::shapeName().
Referenced by dumpLabels().
The documentation for this struct was generated from the following files:
Mod/Import/App/Tools.h
Mod/Import/App/Tools.cpp