FreeCAD: Attacher::AttachEngine Class Reference
Attacher::AttachEngine Class Reference abstract
The AttachEngine class is the placement calculation routine, modes, hints and so on. It can be used separately, without deriving from AttachableObject.
#include <Attacher.h>
Public Member Functions
AttachEngine ()
virtual void setUp (const App::PropertyLinkSubList &references, eMapMode mapMode=mmDeactivated, bool mapReverse=false, double attachParameter=0.0, double surfU=0.0, double surfV=0.0, const Base::Placement &attachmentOffset=Base::Placement())
virtual void setUp (const AttachEngine &another)
void setOffset (const Base::Placement &offset)
virtual AttachEngine * copy () const =0
Base::Placement calculateAttachedPlacement (const Base::Placement &origPlacement, bool *subChanged=0)
virtual Base::Placement _calculateAttachedPlacement (const std::vector< App::DocumentObject * > &objs, const std::vector< std::string > &subs, const Base::Placement &origPlacement) const =0
void setReferences (const App::PropertyLinkSubList &references)
void setReferences (const std::vector< App::SubObjectT > &references)
Base::Placement placementFactory (const gp_Dir &ZAxis, gp_Vec XAxis, gp_Pnt Origin, gp_Pnt refOrg=gp_Pnt(), bool useRefOrg_Line=false, bool useRefOrg_Plane=false, bool makeYVertical=false, bool makeLegacyFlatFaceOrientation=false, Base::Placement *placeOfRef=nullptr) const
placementFactory calculates placement from Z axis direction, optional X axis direction, and origin point.
virtual void suggestMapModes (SuggestResult &result) const
suggestMapModes is the procedure that knows everything about mapping modes. It returns the most appropriate mapping mode, as well as list of all modes that will accept the set of references. In case no modes apply, extra information regarding reasons is returned in msg.
void EnableAllSupportedModes ()
EnableAllModes enables all modes that have shape type lists filled. The function acts on modeEnabled array.
~AttachEngine () override=default
std::vector< App::DocumentObject * > getRefObjects () const
const std::vector< std::string > & getSubValues () const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static eRefType getShapeType (const TopoDS_Shape &sh)
getShapeType by shape. Will never set rtFlagHasPlacement.
static eRefType getShapeType (const App::DocumentObject *obj, const std::string &subshape)
getShapeType by link content. Will include rtFlagHasPlacement, if applies.
static eRefType downgradeType (eRefType type)
downgradeType converts a more-specific type into a less-specific type (e.g. rtCircle->rtCurve, rtCurve->rtEdge, rtEdge->rtAnything)
static int getTypeRank (eRefType type)
getTypeRank determines, how specific is the supplied shape type. The ranks are outlined in definition of eRefType. The ranks are defined by implementation of downgradeType().
static int isShapeOfType (eRefType shapeType, eRefType requirement)
isShapeOfType tests if a shape fulfills the requirement of a mode, and returns a score of how spot on was the requirement.
static std::string getModeName (eMapMode mmode)
getModeName
static eMapMode getModeByName (const std::string &modeName)
static std::string getRefTypeName (eRefType shapeType)
static eRefType getRefTypeByName (const std::string &typeName)
static GProp_GProps getInertialPropsOfShape (const std::vector< const Part::TopoShape * > &shapes)
static void verifyReferencesAreSafe (const App::PropertyLinkSubList &references)
verifyReferencesAreSafe: checks if pointers in references still point to objects contained in open documents. This guarantees the links are valid. Throws Base::Exception if invalid links are found.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes
std::string docName
std::vector< std::string > objNames
std::vector< std::string > subnames
std::vector< std::string > shadowSubs
eMapMode mapMode = mmDeactivated
bool mapReverse = false
double attachParameter = 0.0
double surfU = 0.0
double surfV = 0.0
Base::Placement attachmentOffset
std::vector< bool > modeEnabled
modeEnabled is an indicator, whether some mode is ever suggested or not. Set to false to suppress suggesting some mode, like so: modeEnabled[mmModeIDontLike] = false;
std::vector< refTypeStringList > modeRefTypes
Static Public Attributes
static const char * eMapModeStrings []
static const char * eRefTypeStrings []
Protected Member Functions
refTypeString cat (eRefType rt1)
refTypeString cat (eRefType rt1, eRefType rt2)
refTypeString cat (eRefType rt1, eRefType rt2, eRefType rt3)
refTypeString cat (eRefType rt1, eRefType rt2, eRefType rt3, eRefType rt4)
Static Protected Member Functions
static void readLinks (const std::vector< App::DocumentObject * > &objs, const std::vector< std::string > &subs, std::vector< const Part::TopoShape * > &shapes, std::vector< Part::TopoShape > &storage, std::vector< eRefType > &types)
AttachEngine3D::readLinks.
static void throwWrongMode (eMapMode mmode)
static App::GeoFeature * extractGeoFeature (App::DocumentObject *obj)
static Part::TopoShape extractSubShape (App::DocumentObject *obj, const std::string &subname)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
The AttachEngine class is the placement calculation routine, modes, hints and so on. It can be used separately, without deriving from AttachableObject.
Definition at line 237 of file Attacher.h.
Constructor & Destructor Documentation
AttachEngine()
AttachEngine::AttachEngine () default
~AttachEngine()
Attacher::AttachEngine::~AttachEngine () override default
Member Function Documentation
_calculateAttachedPlacement()
virtual Base::Placement Attacher::AttachEngine::_calculateAttachedPlacement (const std::vector< App::DocumentObject * > & objs, const std::vector< std::string > & subs, const Base::Placement & origPlacement) const pure virtual
Implemented in Attacher::AttachEnginePoint, Attacher::AttachEngineLine, Attacher::AttachEnginePlane, and Attacher::AttachEngine3D.
calculateAttachedPlacement()
Base::Placement AttachEngine::calculateAttachedPlacement (const Base::Placement & origPlacement, bool * subChanged = 0)
Definition at line 970 of file Attacher.cpp.
References Data::ComplexGeoData::elementMapPrefix(), Part::followTypeChange, Base::Placement::getPosition(), Part::Feature::getRelatedElements(), Base::Placement::getRotation(), Data::hasMissingElement(), SplineSurface::i, Path.Post.scripts.opensbp_post::move(), replaceobj::objs, Data::oldElementName(), importers.importIFCmulticore::subs, and TestSpreadsheet::v.
cat() [1/4]
refTypeString Attacher::AttachEngine::cat (eRefType rt1) inline protected
Definition at line 426 of file Attacher.h.
cat() [2/4]
refTypeString Attacher::AttachEngine::cat (eRefType rt1, eRefType rt2) inline protected
Definition at line 431 of file Attacher.h.
cat() [3/4]
refTypeString Attacher::AttachEngine::cat (eRefType rt1, eRefType rt2, eRefType rt3) inline protected
Definition at line 437 of file Attacher.h.
cat() [4/4]
refTypeString Attacher::AttachEngine::cat (eRefType rt1, eRefType rt2, eRefType rt3, eRefType rt4) inline protected
Definition at line 444 of file Attacher.h.
copy()
virtual AttachEngine* Attacher::AttachEngine::copy () const pure virtual
Implemented in Attacher::AttachEnginePoint, Attacher::AttachEngineLine, Attacher::AttachEnginePlane, and Attacher::AttachEngine3D.
downgradeType()
eRefType AttachEngine::downgradeType (eRefType type) static
downgradeType converts a more-specific type into a less-specific type (e.g. rtCircle->rtCurve, rtCurve->rtEdge, rtEdge->rtAnything)
Parameters
type
Returns
the downgraded type.
Definition at line 593 of file Attacher.cpp.
References Attacher::rtAnything, Attacher::rtCircle, Attacher::rtConic, Attacher::rtConicalFace, Attacher::rtCurve, Attacher::rtCylindricalFace, Attacher::rtEdge, Attacher::rtEllipse, Attacher::rtFace, Attacher::rtFlagHasPlacement, Attacher::rtFlatFace, Attacher::rtHyperbola, Attacher::rtLine, Attacher::rtParabola, Attacher::rtPart, Attacher::rtSolid, Attacher::rtSphericalFace, Attacher::rtSurfaceRev, Attacher::rtToroidalFace, Attacher::rtVertex, Attacher::rtWire, and Path.Post.scripts.grbl_post::type.
EnableAllSupportedModes()
void AttachEngine::EnableAllSupportedModes ()
EnableAllModes enables all modes that have shape type lists filled. The function acts on modeEnabled array.
Definition at line 478 of file Attacher.cpp.
References SplineSurface::i, and Attacher::mmDummy_NumberOfModes.
extractGeoFeature()
App::GeoFeature * AttachEngine::extractGeoFeature (App::DocumentObject * obj) static protected
Extracts GeoFeature instance from given DocumentObject.
In case of object itself being GeoFeature it returns itself, in other cases (like links) the method should return pointer to associated GeoFeature or nullptr if none is available.
Parameters
obj The document object to extract the GeoFeature.
Returns
App::GeoFeature pointer associated with this document object
Definition at line 863 of file Attacher.cpp.
References App::DocumentObject::getLinkedObject().
extractSubShape()
TopoShape AttachEngine::extractSubShape (App::DocumentObject * obj, const std::string & subname) static protected
Tries to extract sub shape from document object with given subname.
Parameters
obj DocumentObject containing the sub shape
subname Name of the sub shape to extract
Returns
Extracted sub shape. Can be null.
Exceptions
AttachEngineException If given sub shape does not exist or is impossible to obtain.
Definition at line 877 of file Attacher.cpp.
References Part::TopoShape::countSubShapes(), SCL.SimpleDataTypes::e, FC_THROWM, App::DocumentObject::getNameInDocument(), Part::TopoShape::getSubTopoShape(), Part::Feature::getTopoShape(), Part::TopoShape::isNull(), and Part::TopoShape::shapeType().
getInertialPropsOfShape()
GProp_GProps AttachEngine::getInertialPropsOfShape (const std::vector< const Part::TopoShape * > & shapes) static
Definition at line 746 of file Attacher.cpp.
References SplineSurface::i.
getModeByName()
eMapMode AttachEngine::getModeByName (const std::string & modeName) static
Definition at line 695 of file Attacher.cpp.
References Attacher::mmDummy_NumberOfModes.
getModeName()
std::string AttachEngine::getModeName (eMapMode mmode) static
getModeName
Parameters
mmode
Returns
returns a string that identifies the attachment mode in enum property.
Definition at line 688 of file Attacher.cpp.
References Attacher::mmDummy_NumberOfModes.
Referenced by PartDesignGui::fixSketchSupport(), and AttacherGui::getUIStrings().
getRefObjects()
std::vector< App::DocumentObject * > AttachEngine::getRefObjects () const
Definition at line 949 of file Attacher.cpp.
References toolbit-attributes::doc, FC_THROWM, App::GetApplication(), App::Application::getDocument(), and replaceobj::objs.
getRefTypeByName()
eRefType AttachEngine::getRefTypeByName (const std::string & typeName) static
Definition at line 719 of file Attacher.cpp.
References AttacherGui::eRefTypeStrings, Attacher::rtDummy_numberOfShapeTypes, and Attacher::rtFlagHasPlacement.
getRefTypeName()
std::string AttachEngine::getRefTypeName (eRefType shapeType) static
Definition at line 707 of file Attacher.cpp.
References AttacherGui::eRefTypeStrings, result, Attacher::rtDummy_numberOfShapeTypes, and Attacher::rtFlagHasPlacement.
getShapeType() [1/2]
eRefType AttachEngine::getShapeType (const App::DocumentObject * obj, const std::string & subshape) static
getShapeType by link content. Will include rtFlagHasPlacement, if applies.
Parameters
obj
subshape (input). Can be empty string (then, whole object will be used for shape type testing)
Returns
Definition at line 578 of file Attacher.cpp.
References App::PropertyLinkSubList::getSubValues(), App::PropertyLinkSubList::getValues(), and App::PropertyLinkSubList::setValue().
getShapeType() [2/2]
eRefType AttachEngine::getShapeType (const TopoDS_Shape & sh) static
getShapeType by shape. Will never set rtFlagHasPlacement.
Parameters
sh
Returns
Definition at line 487 of file Attacher.cpp.
References SCL.SimpleDataTypes::e, SCL.SimpleDataTypes::f, Attacher::rtAnything, Attacher::rtCircle, Attacher::rtConicalFace, Attacher::rtCurve, Attacher::rtCylindricalFace, Attacher::rtEllipse, Attacher::rtFace, Attacher::rtFlatFace, Attacher::rtHyperbola, Attacher::rtLine, Attacher::rtParabola, Attacher::rtSolid, Attacher::rtSphericalFace, Attacher::rtSurfaceRev, Attacher::rtToroidalFace, Attacher::rtVertex, and Attacher::rtWire.
getSubValues()
const std::vector<std::string>& Attacher::AttachEngine::getSubValues () const inline
Definition at line 390 of file Attacher.h.
getTypeRank()
int AttachEngine::getTypeRank (eRefType type) static
getTypeRank determines, how specific is the supplied shape type. The ranks are outlined in definition of eRefType. The ranks are defined by implementation of downgradeType().
Parameters
type
Returns
number of times the type can be downgradeType() before it becomes rtAnything
Definition at line 634 of file Attacher.cpp.
References Attacher::rtAnything, Attacher::rtFlagHasPlacement, and Path.Post.scripts.grbl_post::type.
isShapeOfType()
int AttachEngine::isShapeOfType (eRefType shapeType, eRefType requirement) static
isShapeOfType tests if a shape fulfills the requirement of a mode, and returns a score of how spot on was the requirement.
Parameters
shapeType (use return value of AttachEngine::getShapeType)
requirement
Returns
: -1 - doesn't fulfill, 0 - compatible topology, but incompatible specific (e.g. rtLine, rtCircle); 1 - valid by generic type (e.g. rtCircle is rtEdge), 2 and up - more and more specific match (according to rank of requirement)
Definition at line 648 of file Attacher.cpp.
References Attacher::rtAnything, and Attacher::rtFlagHasPlacement.
placementFactory()
Base::Placement AttachEngine::placementFactory (const gp_Dir & ZAxis, gp_Vec XAxis, gp_Pnt Origin, gp_Pnt refOrg = gp_Pnt(), bool useRefOrg_Line = false, bool useRefOrg_Plane = false, bool makeYVertical = false, bool makeLegacyFlatFaceOrientation = false, Base::Placement * placeOfRef = nullptr) const
placementFactory calculates placement from Z axis direction, optional X axis direction, and origin point.
Parameters
ZAxis (input) mandatory. Z axis of the returned placement will strictly coincide with ZAxis.
XAxis (input) optional (i.e., can be zero). Sets the preferred X axis orientation. If it is not perpendicular to ZAxis, it will be forced to be. If XAxis is zero, the effect is equivalent to setting makeYVertical to true.
Origin (input) mandatory.
refOrg (input). The point that will be used in case any of useRefOrg_XX parameters is true.
useRefOrg_Line (input). If true, Origin will be moved along ZAxis to be as close as possible to refOrg.
useRefOrg_Plane (input). If true, Origin will be moved in XAxis-YAxis plane to be as close as possible to refOrg.
makeYVertical (input). If true, XAxis is ignored, and X and Y axes are defined in order to make Y axis go as upwards as possible. If ZAxis is strictly upwards, XY will match global XY. If ZAxis is strictly downwards, XAxis will be the reversed global X axis.
makeLegacyFlatFaceOrientation (input). Modifies the behavior of makeYVertical to match the logic that was used in mapping of sketches to flat faces in FreeCAD prior to introduction of Attacher. Set makeYVertical to true if using this.
Returns
the resulting placement. ReverseXY property of Attacher will be automatically applied.
Definition at line 272 of file Attacher.cpp.
References Part::TopoShape::convertToMatrix(), RobotExample::pos, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
readLinks()
void AttachEngine::readLinks (const std::vector< App::DocumentObject * > & objs, const std::vector< std::string > & subs, std::vector< const Part::TopoShape * > & shapes, std::vector< Part::TopoShape > & storage, std::vector< eRefType > & types) static protected
AttachEngine3D::readLinks.
Parameters
shapes
storage is a buffer storing what some of the pointers in shapes point to. It is needed, since subshapes are copied in the process (but copying a whole shape of an object can potentially be slow).
Definition at line 825 of file Attacher.cpp.
References FC_THROWM, importers.importIFClegacy::getShape(), SplineSurface::i, replaceobj::objs, Attacher::rtFlagHasPlacement, storage, and importers.importIFCmulticore::subs.
setOffset()
void AttachEngine::setOffset (const Base::Placement & offset)
Definition at line 267 of file Attacher.cpp.
setReferences() [1/2]
void AttachEngine::setReferences (const App::PropertyLinkSubList & references)
Definition at line 182 of file Attacher.cpp.
References App::PropertyLinkSubList::getShadowSubs(), App::PropertyLinkSubList::getValues(), Path.Post.scripts.opensbp_post::move(), and femtools.tokrules::names.
Referenced by UnifiedDatumCommand().
setReferences() [2/2]
void AttachEngine::setReferences (const std::vector< App::SubObjectT > & references)
Definition at line 211 of file Attacher.cpp.
References FC_THROWM, Path.Post.scripts.opensbp_post::move(), and femtools.tokrules::names.
setUp() [1/2]
void AttachEngine::setUp (const App::PropertyLinkSubList & references, eMapMode mapMode = mmDeactivated, bool mapReverse = false, double attachParameter = 0.0, double surfU = 0.0, double surfV = 0.0, const Base::Placement & attachmentOffset = Base::Placement()) virtual
Definition at line 238 of file Attacher.cpp.
Referenced by Attacher::AttachEnginePlane::_calculateAttachedPlacement(), Attacher::AttachEngineLine::_calculateAttachedPlacement(), Attacher::AttachEnginePoint::_calculateAttachedPlacement(), and SketcherGui::SuggestAutoMapMode().
setUp() [2/2]
void AttachEngine::setUp (const AttachEngine & another) virtual
Definition at line 253 of file Attacher.cpp.
References attachmentOffset, attachParameter, docName, mapMode, mapReverse, objNames, shadowSubs, subnames, surfU, and surfV.
suggestMapModes()
void AttachEngine::suggestMapModes (SuggestResult & result) const virtual
suggestMapModes is the procedure that knows everything about mapping modes. It returns the most appropriate mapping mode, as well as list of all modes that will accept the set of references. In case no modes apply, extra information regarding reasons is returned in msg.
Parameters
result (output). Returns results of suggestion, such as best fit mode, list of all modes that apply, hints, etc.
Definition at line 379 of file Attacher.cpp.
References Attacher::mmDeactivated, Attacher::mmDummy_NumberOfModes, result, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by SketcherGui::SuggestAutoMapMode(), and UnifiedDatumCommand().
throwWrongMode()
void AttachEngine::throwWrongMode (eMapMode mmode) static protected
Definition at line 917 of file Attacher.cpp.
References Attacher::mmDummy_NumberOfModes.
verifyReferencesAreSafe()
void AttachEngine::verifyReferencesAreSafe (const App::PropertyLinkSubList & references) static
verifyReferencesAreSafe: checks if pointers in references still point to objects contained in open documents. This guarantees the links are valid. Throws Base::Exception if invalid links are found.
Definition at line 932 of file Attacher.cpp.
References toolbit-attributes::doc, App::GetApplication(), App::Application::getDocuments(), and App::PropertyLinkSubList::getValues().
Member Data Documentation
attachmentOffset
Base::Placement Attacher::AttachEngine::attachmentOffset
Definition at line 414 of file Attacher.h.
Referenced by Attacher::AttachEngineLine::_calculateAttachedPlacement(), Attacher::AttachEnginePoint::_calculateAttachedPlacement(), and setUp().
attachParameter
double Attacher::AttachEngine::attachParameter = 0.0
Definition at line 412 of file Attacher.h.
Referenced by setUp().
docName
std::string Attacher::AttachEngine::docName
Definition at line 405 of file Attacher.h.
Referenced by setUp().
eMapModeStrings
const char * AttachEngine::eMapModeStrings static
Definition at line 400 of file Attacher.h.
eRefTypeStrings
const char * AttachEngine::eRefTypeStrings static
Initial value:
= {
    "Any",
    "Vertex",
    "Edge",
    "Face",
    "Line",
    "Curve",
    "Circle",
    "Conic",
    "Ellipse",
    "Parabola",
    "Hyperbola",
    "Plane",
    "Sphere",
    "Revolve",
    "Cylinder",
    "Torus",
    "Cone",
    "Object",
    "Solid",
    "Wire",
    nullptr
}
Definition at line 401 of file Attacher.h.
mapMode
eMapMode Attacher::AttachEngine::mapMode = mmDeactivated
Definition at line 410 of file Attacher.h.
Referenced by Attacher::AttachEngineLine::_calculateAttachedPlacement(), Attacher::AttachEnginePoint::_calculateAttachedPlacement(), and setUp().
mapReverse
bool Attacher::AttachEngine::mapReverse = false
Definition at line 411 of file Attacher.h.
Referenced by setUp().
modeEnabled
std::vector<bool> Attacher::AttachEngine::modeEnabled
modeEnabled is an indicator, whether some mode is ever suggested or not. Set to false to suppress suggesting some mode, like so: modeEnabled[mmModeIDontLike] = false;
Definition at line 421 of file Attacher.h.
modeRefTypes
std::vector<refTypeStringList> Attacher::AttachEngine::modeRefTypes
Definition at line 423 of file Attacher.h.
Referenced by Attacher::AttachEngineLine::AttachEngineLine(), Attacher::AttachEnginePlane::AttachEnginePlane(), Attacher::AttachEnginePoint::AttachEnginePoint(), and AttacherGui::getRefListForMode().
objNames
std::vector<std::string> Attacher::AttachEngine::objNames
Definition at line 406 of file Attacher.h.
Referenced by setUp().
shadowSubs
std::vector<std::string> Attacher::AttachEngine::shadowSubs
Definition at line 408 of file Attacher.h.
Referenced by setUp().
subnames
std::vector<std::string> Attacher::AttachEngine::subnames
Definition at line 407 of file Attacher.h.
Referenced by setUp().
surfU
double Attacher::AttachEngine::surfU = 0.0
Definition at line 413 of file Attacher.h.
Referenced by setUp().
surfV
double Attacher::AttachEngine::surfV = 0.0
Definition at line 413 of file Attacher.h.
Referenced by setUp().
The documentation for this class was generated from the following files:
Attacher.h
Attacher.cpp