FreeCAD: Gui::Dialog::UndoDialog Class Reference
Gui::Dialog::UndoDialog Class Reference
#include <DlgUndoRedo.h>
Public Member Functions
UndoDialog (QWidget *parent=nullptr)
~UndoDialog () override
Protected Slots
void onSelected ()
void onFetchInfo ()
Detailed Description
This class implements the undo dialog.
Author
Werner Mayer
Definition at line 75 of file DlgUndoRedo.h.
Constructor & Destructor Documentation
UndoDialog()
UndoDialog::UndoDialog (QWidget * parent = nullptr) explicit
Constructs a UndoRedoDialog which is a child of 'parent', with the name 'name'.'
Definition at line 44 of file DlgUndoRedo.cpp.
References draftgeoutils.intersections::connect(), and onFetchInfo().
~UndoDialog()
UndoDialog::~UndoDialog () override default
Destroys the object and frees any allocated resources.
Member Function Documentation
onFetchInfo
void UndoDialog::onFetchInfo () protected slot
This method fetches the undo / redo information from the active document and shows it in the undo / redo dialog.
Definition at line 59 of file DlgUndoRedo.cpp.
References Gui::MainWindow::activeWindow(), Path.Op.Gui.Selection::clear(), Gui::getMainWindow(), SplineSurface::i, onSelected(), and Gui::MDIView::undoActions().
Referenced by UndoDialog().
onSelected
void UndoDialog::onSelected () protected slot
Closes the dialog and sends the message 'Undo' to the currently active MDI view.
Definition at line 73 of file DlgUndoRedo.cpp.
References a, Gui::Application::Instance, and Gui::Application::sendMsgToActiveView().
Referenced by onFetchInfo().
The documentation for this class was generated from the following files:
DlgUndoRedo.h
DlgUndoRedo.cpp