FreeCAD: dimAttributes Class Reference
dimAttributes Class Reference
#include <TaskSelectLineAttributes.h>
Public Member Functions
dimAttributes ()
void setCascadeSpacing (double)
double getCascadeSpacing ()
void setLineStretch (double)
double getLineStretch ()
Detailed Description
Definition at line 32 of file TaskSelectLineAttributes.h.
Constructor & Destructor Documentation
dimAttributes()
dimAttributes::dimAttributes ()
Definition at line 61 of file TaskSelectLineAttributes.cpp.
Member Function Documentation
getCascadeSpacing()
double dimAttributes::getCascadeSpacing () inline
Definition at line 60 of file TaskSelectLineAttributes.h.
Referenced by execCascadeHorizDimension(), execCascadeObliqueDimension(), execCascadeVertDimension(), execCreateHorizCoordDimension(), execCreateVertCoordDimension(), TDHandlerDimension::getDimPositionToBe(), TechDrawGui::makeObliqueChainDimension(), TechDrawGui::makeObliqueCoordDimension(), TDHandlerDimension::mouseMoveEvent(), TechDrawGui::TaskSelectLineAttributes::setUiEdit(), and TechDrawGui::QGIDatumLabel::snapPosition().
getLineStretch()
double dimAttributes::getLineStretch () inline
Definition at line 62 of file TaskSelectLineAttributes.h.
Referenced by execExtendShortenLine(), and TechDrawGui::TaskSelectLineAttributes::setUiEdit().
setCascadeSpacing()
void dimAttributes::setCascadeSpacing (double spacing)
Definition at line 67 of file TaskSelectLineAttributes.cpp.
Referenced by TechDrawGui::TaskSelectLineAttributes::accept().
setLineStretch()
void dimAttributes::setLineStretch (double stretch)
Definition at line 72 of file TaskSelectLineAttributes.cpp.
References Part::stretch.
Referenced by TechDrawGui::TaskSelectLineAttributes::accept().
The documentation for this class was generated from the following files:
TaskSelectLineAttributes.h
TaskSelectLineAttributes.cpp