FreeCAD: Materials::LibraryBase Class Reference
Materials::LibraryBase Class Reference
#include <ModelLibrary.h>
Public Member Functions
LibraryBase ()=default
LibraryBase (const QString &libraryName, const QString &dir, const QString &icon)
~LibraryBase () override=default
const QString getName () const
const QString getDirectory () const
const QString getDirectoryPath () const
const QString getIconPath () const
bool operator== (const LibraryBase &library) const
bool operator!= (const LibraryBase &library) const
QString getLocalPath (const QString &path) const
QString getRelativePath (const QString &path) const
bool isRoot (const QString &path) const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 61 of file ModelLibrary.h.
Constructor & Destructor Documentation
LibraryBase() [1/2]
Materials::LibraryBase::LibraryBase () default
LibraryBase() [2/2]
LibraryBase::LibraryBase (const QString & libraryName, const QString & dir, const QString & icon)
Definition at line 39 of file ModelLibrary.cpp.
~LibraryBase()
Materials::LibraryBase::~LibraryBase () override default
Member Function Documentation
getDirectory()
const QString Materials::LibraryBase::getDirectory () const inline
Definition at line 93 of file ModelLibrary.h.
References operator==().
Referenced by Materials::MaterialLoader::getMaterialFolders().
getDirectoryPath()
const QString Materials::LibraryBase::getDirectoryPath () const inline
Definition at line 97 of file ModelLibrary.h.
Referenced by getLocalPath(), and getRelativePath().
getIconPath()
const QString Materials::LibraryBase::getIconPath () const inline
Definition at line 101 of file ModelLibrary.h.
getLocalPath()
QString LibraryBase::getLocalPath (const QString & path) const
Definition at line 50 of file ModelLibrary.cpp.
References Path.Preferences::filePath(), getDirectoryPath(), and getName().
Referenced by Materials::MaterialLibrary::createFolder(), Materials::MaterialLibrary::deleteRecursive(), Materials::MaterialLibrary::fileExists(), isRoot(), Materials::MaterialLibrary::renameFolder(), and Materials::MaterialLibrary::saveMaterial().
getName()
const QString Materials::LibraryBase::getName () const inline
Definition at line 89 of file ModelLibrary.h.
Referenced by getLocalPath(), and getRelativePath().
getRelativePath()
QString LibraryBase::getRelativePath (const QString & path) const
Definition at line 79 of file ModelLibrary.cpp.
References Path.Preferences::filePath(), getDirectoryPath(), and getName().
Referenced by Materials::MaterialLibrary::addMaterial(), Materials::ModelLibrary::addModel(), Materials::MaterialLibrary::deleteFile(), Materials::MaterialLibrary::getMaterialByPath(), Materials::ModelLibrary::getModelByPath(), Materials::MaterialLibrary::getUUIDFromPath(), Materials::MaterialLibrary::saveMaterial(), and Materials::MaterialLibrary::updatePaths().
isRoot()
bool LibraryBase::isRoot (const QString & path) const
Definition at line 70 of file ModelLibrary.cpp.
References getLocalPath().
Referenced by Materials::MaterialLibrary::deleteRecursive().
operator!=()
bool Materials::LibraryBase::operator!= (const LibraryBase & library) const inline
Definition at line 106 of file ModelLibrary.h.
operator==()
bool LibraryBase::operator== (const LibraryBase & library) const
Definition at line 45 of file ModelLibrary.cpp.
Referenced by getDirectory().
The documentation for this class was generated from the following files:
ModelLibrary.h
ModelLibrary.cpp