FreeCAD: BOPTools.JoinFeatures.FeatureCutout Class Reference
BOPTools.JoinFeatures.FeatureCutout Class Reference
Public Member Functions
def __init__ (self, obj)
def execute (self, selfobj)
Public Attributes
Type
Detailed Description
The Part Cutout object.
Definition at line 318 of file BOPTools/JoinFeatures.py.
Constructor & Destructor Documentation
__init__()
def BOPTools.JoinFeatures.FeatureCutout.__init__ (self, obj)
Definition at line 321 of file BOPTools/JoinFeatures.py.
References BOPTools.JoinFeatures.getParamRefine().
Member Function Documentation
execute()
def BOPTools.JoinFeatures.FeatureCutout.execute (self, selfobj)
Definition at line 333 of file BOPTools/JoinFeatures.py.
Referenced by src.Mod.PartDesign.Scripts.Spring.MySpring.onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped.onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder.onChanged(), and FeaturePython.DistanceBolt.onChanged().
Member Data Documentation
Type
BOPTools.JoinFeatures.FeatureCutout.Type
Definition at line 331 of file BOPTools/JoinFeatures.py.
The documentation for this class was generated from the following file:
BOPTools/JoinFeatures.py