FreeCAD: Fem::Tools Class Reference
Fem::Tools Class Reference
#include <FemTools.h>
Static Public Member Functions
static Base::Vector3d getDirectionFromShape (const TopoDS_Shape &)
static bool isLinear (const TopoDS_Edge &)
static bool isPlanar (const TopoDS_Face &)
static gp_XYZ getDirection (const TopoDS_Edge &)
static gp_XYZ getDirection (const TopoDS_Face &)
static std::string checkIfBinaryExists (std::string prefSection, std::string prefBinaryPath, std::string prefBinaryName)
static Base::Placement getSubShapeGlobalLocation (const Part::Feature *feat, const TopoDS_Shape &sh)
static void setSubShapeGlobalLocation (const Part::Feature *feat, TopoDS_Shape &sh)
static TopoDS_Shape getFeatureSubShape (const Part::Feature *feat, const char *subName, bool silent)
static bool getCylinderParams (const TopoDS_Shape &sh, Base::Vector3d &base, Base::Vector3d &axis, double &height, double &radius)
Detailed Description
Definition at line 46 of file FemTools.h.
Member Function Documentation
checkIfBinaryExists()
std::string Fem::Tools::checkIfBinaryExists (std::string prefSection, std::string prefBinaryPath, std::string prefBinaryName) static
function to determine 3rd-party binaries used by the FEM WB The result is either the full path if available or just the binary name if it was found in a system path
Definition at line 293 of file FemTools.cpp.
References App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetBool(), App::Application::getHomePath(), and App::Application::GetParameterGroupByPath().
Referenced by FemGui::DlgSettingsFemGeneralImp::DlgSettingsFemGeneralImp(), and FemGui::Workbench::setupToolBars().
getCylinderParams()
bool Fem::Tools::getCylinderParams (const TopoDS_Shape & sh, Base::Vector3d & base, Base::Vector3d & axis, double & height, double & radius) static
Get cylinder parameters. Base is located at the center of the cylinder
Definition at line 373 of file FemTools.cpp.
References exportCSG::center(), and Handle().
Referenced by Fem::ConstraintTransform::onChanged(), and Fem::ConstraintBearing::onChanged().
getDirection() [1/2]
gp_XYZ Fem::Tools::getDirection (const TopoDS_Edge & edge) static
It is assumed that the edge is 'linear'. The direction vector of the line is returned.
See also
isLinear
Definition at line 256 of file FemTools.cpp.
References Handle(), and SurfaceTests.TestBlendCurve::vec.
Referenced by getDirectionFromShape().
getDirection() [2/2]
gp_XYZ Fem::Tools::getDirection (const TopoDS_Face & face) static
It is assumed that the face is 'planar'. The normal vector of the plane is returned.
See also
isPlanar
Definition at line 152 of file FemTools.cpp.
References Handle(), and WorkingPlane::plane.
getDirectionFromShape()
Base::Vector3d Fem::Tools::getDirectionFromShape (const TopoDS_Shape & shape) static
Get the direction of the shape. If the shape is a planar face then get its normal direction. If it's 'linear' then get its direction vector.
See also
isLinear
isPlanar
Definition at line 57 of file FemTools.cpp.
References getDirection(), isLinear(), and isPlanar().
Referenced by Fem::Constraint::getDirection().
getFeatureSubShape()
TopoDS_Shape Fem::Tools::getFeatureSubShape (const Part::Feature * feat, const char * subName, bool silent) static
Get subshape from Part Feature. The subShape is returned with global location
Definition at line 355 of file FemTools.cpp.
References Part::PropertyPartShape::getShape(), Part::TopoShape::getSubShape(), Part::TopoShape::isNull(), and Part::Feature::Shape.
Referenced by Fem::Constraint::getPoints(), Fem::ConstraintTransform::onChanged(), Fem::ConstraintBearing::onChanged(), and Fem::Constraint::onChanged().
getSubShapeGlobalLocation()
Base::Placement Fem::Tools::getSubShapeGlobalLocation (const Part::Feature * feat, const TopoDS_Shape & sh) static
Subshape placement is not necessarily the same as the feature placement
Definition at line 336 of file FemTools.cpp.
References Part::TopoShape::convert(), App::PropertyPlacement::getValue(), App::GeoFeature::globalPlacement(), Base::Placement::inverse(), and App::GeoFeature::Placement.
isLinear()
bool Fem::Tools::isLinear (const TopoDS_Edge & edge) static
Checks whether the curve of the edge is 'linear' which is the case for a line or a spline or Bezier curve with collinear control points.
Definition at line 202 of file FemTools.cpp.
References DraftVecUtils::dist(), Handle(), SplineSurface::i, and SurfaceTests.TestBlendCurve::vec.
Referenced by getDirectionFromShape(), FemGui::TaskFemConstraintBearing::onSelectionChanged(), and FemGui::TaskFemConstraintGear::onSelectionChanged().
isPlanar()
bool Fem::Tools::isPlanar (const TopoDS_Face & face) static
Checks whether the surface of the face is planar.
Definition at line 78 of file FemTools.cpp.
References DraftVecUtils::dist(), Handle(), SplineSurface::i, and WorkingPlane::plane.
Referenced by getDirectionFromShape(), FemGui::TaskFemConstraintBearing::onSelectionChanged(), and FemGui::TaskFemConstraintGear::onSelectionChanged().
setSubShapeGlobalLocation()
void Fem::Tools::setSubShapeGlobalLocation (const Part::Feature * feat, TopoDS_Shape & sh) static
Definition at line 347 of file FemTools.cpp.
References Part::Tools::fromPlacement().
The documentation for this class was generated from the following files:
FemTools.h
FemTools.cpp