FreeCAD: MatGui::MaterialsEditor Class Reference
MatGui::MaterialsEditor Class Reference
#include <MaterialsEditor.h>
Public Member Functions
MaterialsEditor (std::shared_ptr< Materials::MaterialFilter > filter, QWidget *parent=nullptr)
MaterialsEditor (QWidget *parent=nullptr)
~MaterialsEditor () override=default
void onName (const QString &text)
void onAuthor (const QString &text)
void onLicense (const QString &text)
void onSourceURL (const QString &text)
void onSourceReference (const QString &text)
void onDescription ()
void propertyChange (const QString &property, const QVariant &value)
void onInheritNewMaterial (bool checked)
void onNewMaterial (bool checked)
void onFavourite (bool checked)
void onURL (bool checked)
void onPhysicalAdd (bool checked)
void onPhysicalRemove (bool checked)
void onAppearanceAdd (bool checked)
void onAppearanceRemove (bool checked)
void onOk (bool checked)
void onCancel (bool checked)
void onSave (bool checked)
void accept () override
void reject () override
Materials::MaterialManager & getMaterialManager ()
Materials::ModelManager & getModelManager ()
void updateMaterialAppearance ()
void updateMaterialProperties ()
void updateMaterialGeneral ()
void updateMaterial ()
void onSelectMaterial (const QItemSelection &selected, const QItemSelection &deselected)
void onDoubleClick (const QModelIndex &index)
void onContextMenu (const QPoint &pos)
bool isMaterialSelected () const
std::shared_ptr< Materials::Material > getMaterial ()
Static Public Member Functions
static QString libraryPath (const std::shared_ptr< Materials::Material > &material)
Protected Member Functions
int confirmSave (QWidget *parent)
void saveMaterial ()
Detailed Description
Definition at line 70 of file MaterialsEditor.h.
Constructor & Destructor Documentation
MaterialsEditor() [1/2]
MaterialsEditor::MaterialsEditor (std::shared_ptr< Materials::MaterialFilter > filter, QWidget * parent = nullptr) explicit
Definition at line 63 of file MaterialsEditor.cpp.
MaterialsEditor() [2/2]
MaterialsEditor::MaterialsEditor (QWidget * parent = nullptr) explicit
Definition at line 75 of file MaterialsEditor.cpp.
~MaterialsEditor()
MatGui::MaterialsEditor::~MaterialsEditor () override default
Member Function Documentation
accept()
void MaterialsEditor::accept () override
Definition at line 589 of file MaterialsEditor.cpp.
References Base::Console(), and Base::ConsoleSingleton::Log().
Referenced by onDoubleClick(), onOk(), and MaterialEditor.MaterialEditor::verify().
confirmSave()
int MaterialsEditor::confirmSave (QWidget * parent) protected
Definition at line 1309 of file MaterialsEditor.cpp.
References MengerSponge::box, Init::parent, and saveMaterial().
Referenced by onDoubleClick(), onInheritNewMaterial(), onNewMaterial(), onOk(), and onSelectMaterial().
getMaterial()
std::shared_ptr<Materials::Material> MatGui::MaterialsEditor::getMaterial () inline
Definition at line 125 of file MaterialsEditor.h.
Referenced by onSelectMaterial().
getMaterialManager()
Materials::MaterialManager& MatGui::MaterialsEditor::getMaterialManager () inline
Definition at line 102 of file MaterialsEditor.h.
Referenced by onAppearanceAdd(), and onSelectMaterial().
getModelManager()
Materials::ModelManager& MatGui::MaterialsEditor::getModelManager () inline
Definition at line 106 of file MaterialsEditor.h.
Referenced by onAppearanceAdd(), updateMaterialAppearance(), and updateMaterialProperties().
isMaterialSelected()
bool MatGui::MaterialsEditor::isMaterialSelected () const inline
Definition at line 121 of file MaterialsEditor.h.
libraryPath()
QString MaterialsEditor::libraryPath (const std::shared_ptr< Materials::Material > & material) static
Definition at line 1175 of file MaterialsEditor.cpp.
Referenced by updateMaterialGeneral().
onAppearanceAdd()
void MaterialsEditor::onAppearanceAdd (bool checked)
Definition at line 423 of file MaterialsEditor.cpp.
References Base::Console(), Materials::MaterialManager::defaultAppearance(), src.Mod.PartDesign.Scripts.Gear::dialog, getMaterialManager(), Materials::ModelManager::getModel(), getModelManager(), Base::ConsoleSingleton::Log(), Materials::ModelFilter_Appearance, Materials::ModelUUIDs::ModelUUID_Rendering_Basic, and updateMaterial().
onAppearanceRemove()
void MaterialsEditor::onAppearanceRemove (bool checked)
Definition at line 446 of file MaterialsEditor.cpp.
References toolbit-attributes::group, propertyName(), and updateMaterial().
onAuthor()
void MaterialsEditor::onAuthor (const QString & text)
Definition at line 337 of file MaterialsEditor.cpp.
onCancel()
void MaterialsEditor::onCancel (bool checked)
Definition at line 563 of file MaterialsEditor.cpp.
References reject().
onContextMenu()
void MaterialsEditor::onContextMenu (const QPoint & pos)
Definition at line 1284 of file MaterialsEditor.cpp.
References draftgeoutils.intersections::connect(), and RobotExample::pos.
onDescription()
void MaterialsEditor::onDescription ()
Definition at line 357 of file MaterialsEditor.cpp.
onDoubleClick()
void MaterialsEditor::onDoubleClick (const QModelIndex & index)
Definition at line 1267 of file MaterialsEditor.cpp.
References accept(), confirmSave(), and Materials::Material::ModelEdit_None.
onFavourite()
void MaterialsEditor::onFavourite (bool checked)
Definition at line 469 of file MaterialsEditor.cpp.
onInheritNewMaterial()
void MaterialsEditor::onInheritNewMaterial (bool checked)
Definition at line 525 of file MaterialsEditor.cpp.
References confirmSave(), Materials::Material::ModelEdit_None, and Init::parent.
onLicense()
void MaterialsEditor::onLicense (const QString & text)
Definition at line 342 of file MaterialsEditor.cpp.
onName()
void MaterialsEditor::onName (const QString & text)
Definition at line 332 of file MaterialsEditor.cpp.
onNewMaterial()
void MaterialsEditor::onNewMaterial (bool checked)
Definition at line 506 of file MaterialsEditor.cpp.
References confirmSave(), and Materials::Material::ModelEdit_None.
onOk()
void MaterialsEditor::onOk (bool checked)
Definition at line 547 of file MaterialsEditor.cpp.
References accept(), confirmSave(), and Materials::Material::ModelEdit_None.
onPhysicalAdd()
void MaterialsEditor::onPhysicalAdd (bool checked)
Definition at line 384 of file MaterialsEditor.cpp.
References Base::Console(), src.Mod.PartDesign.Scripts.Gear::dialog, Base::ConsoleSingleton::Log(), Materials::ModelFilter_Physical, and updateMaterial().
onPhysicalRemove()
void MaterialsEditor::onPhysicalRemove (bool checked)
Definition at line 400 of file MaterialsEditor.cpp.
References toolbit-attributes::group, propertyName(), and updateMaterial().
onSave()
void MaterialsEditor::onSave (bool checked)
Definition at line 570 of file MaterialsEditor.cpp.
References saveMaterial().
onSelectMaterial()
void MaterialsEditor::onSelectMaterial (const QItemSelection & selected, const QItemSelection & deselected)
Definition at line 1222 of file MaterialsEditor.cpp.
References confirmSave(), Base::Console(), getMaterial(), getMaterialManager(), Base::ConsoleSingleton::Log(), Materials::Material::ModelEdit_None, and updateMaterial().
onSourceReference()
void MaterialsEditor::onSourceReference (const QString & text)
Definition at line 352 of file MaterialsEditor.cpp.
onSourceURL()
void MaterialsEditor::onSourceURL (const QString & text)
Definition at line 347 of file MaterialsEditor.cpp.
onURL()
void MaterialsEditor::onURL (bool checked)
Definition at line 374 of file MaterialsEditor.cpp.
propertyChange()
void MaterialsEditor::propertyChange (const QString & property, const QVariant & value)
Definition at line 362 of file MaterialsEditor.cpp.
reject()
void MaterialsEditor::reject () override
Definition at line 614 of file MaterialsEditor.cpp.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and onCancel().
saveMaterial()
void MaterialsEditor::saveMaterial () protected
Definition at line 577 of file MaterialsEditor.cpp.
References src.Mod.PartDesign.Scripts.Gear::dialog, and updateMaterialGeneral().
Referenced by confirmSave(), and onSave().
updateMaterial()
void MaterialsEditor::updateMaterial ()
Definition at line 1213 of file MaterialsEditor.cpp.
References updateMaterialAppearance(), updateMaterialGeneral(), and updateMaterialProperties().
Referenced by onAppearanceAdd(), onAppearanceRemove(), onPhysicalAdd(), onPhysicalRemove(), and onSelectMaterial().
updateMaterialAppearance()
void MaterialsEditor::updateMaterialAppearance ()
Definition at line 1047 of file MaterialsEditor.cpp.
References Materials::ModelManager::getModel(), getModelManager(), and src.Mod.Test.testPathArray::items.
Referenced by updateMaterial().
updateMaterialGeneral()
void MaterialsEditor::updateMaterialGeneral ()
Definition at line 1191 of file MaterialsEditor.cpp.
References Materials::MaterialManager::getParent(), libraryPath(), and Init::parent.
Referenced by saveMaterial(), and updateMaterial().
updateMaterialProperties()
void MaterialsEditor::updateMaterialProperties ()
Definition at line 1109 of file MaterialsEditor.cpp.
References Materials::ModelProperty::getDescription(), Materials::ModelProperty::getDisplayName(), Materials::ModelManager::getModel(), getModelManager(), Materials::ModelProperty::getPropertyType(), Materials::ModelProperty::getUnits(), and src.Mod.Test.testPathArray::items.
Referenced by updateMaterial().
The documentation for this class was generated from the following files:
MaterialsEditor.h
MaterialsEditor.cpp