FreeCAD: Sketcher::GeometryFacade Class Reference
Sketcher::GeometryFacade Class Reference
This class is a Facade to handle geometry and sketcher geometry extensions with a single sketcher specific interface.
#include <GeometryFacade.h>
Public Member Functions
GeometryFacade (const GeometryFacade &)=delete
GeometryFacade & operator= (const GeometryFacade &)=delete
GeometryFacade (GeometryFacade &&)=default
GeometryFacade & operator= (GeometryFacade &&)=default
~GeometryFacade () override
void setGeometry (Part::Geometry *geometry)
void setOwner (bool owner)
bool getOwner () const
long getId () const override
void setId (long id) override
InternalType::InternalType getInternalType () const override
void setInternalType (InternalType::InternalType type) override
bool testGeometryMode (int flag) const override
void setGeometryMode (int flag, bool v=true) override
int getGeometryLayerId () const override
void setGeometryLayerId (int geolayer) override
bool getBlocked () const
void setBlocked (bool status=true)
bool getConstruction () const
void setConstruction (bool construction)
bool isInternalAligned () const
bool isInternalType (InternalType::InternalType type) const
const std::string & getExtensionName () const
template<typename GeometryT = Part::Geometry, typename = typename std::enable_if< std::is_base_of<Part::Geometry, typename std::decay<GeometryT>::type>::value>::type>
GeometryT * getGeometry ()
template<typename GeometryT = Part::Geometry, typename = typename std::enable_if< std::is_base_of<Part::Geometry, typename std::decay<GeometryT>::type>::value>::type>
const GeometryT * getGeometry () const
PyObject * getPyObject () override
TopoDS_Shape toShape () const
const Handle (Geom_Geometry) &handle() const
Part::Geometry * copy () const
Part::Geometry * clone () const
boost::uuids::uuid getTag () const
std::vector< std::weak_ptr< const Part::GeometryExtension > > getExtensions () const
bool hasExtension (const Base::Type &type) const
bool hasExtension (const std::string &name) const
std::weak_ptr< const Part::GeometryExtension > getExtension (const Base::Type &type) const
std::weak_ptr< const Part::GeometryExtension > getExtension (const std::string &name) const
void setExtension (std::unique_ptr< Part::GeometryExtension > &&geo)
void deleteExtension (const Base::Type &type)
void deleteExtension (const std::string &name)
void mirror (const Base::Vector3d &point)
void mirror (const Base::Vector3d &point, Base::Vector3d dir)
void rotate (const Base::Placement &plm)
void scale (const Base::Vector3d &vec, double scale)
void transform (const Base::Matrix4D &mat)
void translate (const Base::Vector3d &vec)
bool isGeoType (const Base::Type &type) const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static std::unique_ptr< GeometryFacade > getFacade (const Part::Geometry *geometry, bool owner=false)
static void ensureSketchGeometryExtension (Part::Geometry *geometry)
static void copyId (const Part::Geometry *src, Part::Geometry *dst)
static bool getConstruction (const Part::Geometry *geometry)
static void setConstruction (Part::Geometry *geometry, bool construction)
static bool isInternalType (const Part::Geometry *geometry, InternalType::InternalType type)
static bool isInternalAligned (const Part::Geometry *geometry)
static InternalType::InternalType getInternalType (const Part::Geometry *geometry)
static void setInternalType (Part::Geometry *geometry, InternalType::InternalType type)
static bool getBlocked (const Part::Geometry *geometry)
static int getId (const Part::Geometry *geometry)
static void setId (const Part::Geometry *geometry, int id)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions
GeometryFacade (const Part::Geometry *geometry, bool owner=false)
GeometryFacade ()
Friends
class GeometryFacadePy
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
This class is a Facade to handle geometry and sketcher geometry extensions with a single sketcher specific interface.
The facade privately inherits from a common interface it shares with the extension thereby implementing a compiler enforced same interface as the extension. It does not inherit from Part::Geometry and thus is intended to provide, in part a convenience subset of the interface of Part::Geometry, in part a different interface.
GeometryFacade has private constructors and objects may only be created using the getFacade factory methods.
There is a version of getFacade taking a const Part::Geometry and producing a const GeometryFacade, and a non-const version producing a non-const GeometryFacade. So constness of the Part::Geometry object is preserved by the GeometryFacade container.
There are some static convenience utility functions to simplify common operations such as ID copy or to ensure that a geometry object has the extension (creating the extension if not existing).
Warning
The const factory method will throw if the geometry does not have a SketchGeometryExtension (being const, it commits not to create one and modify the const Part::Geometry object). The non-const factory method will create the extension if not existing.
If the Geometry Pointer fed into the factory method is a nullptr, a nullptr GeometryFacade is created. It should not be possible to create a GeometryFacade having a Part::Geometry * being a nullptr.
A simple usage example:
const std::vector< Part::Geometry * > &vals = getInternalGeometry(); auto gf = GeometryFacade::getFacade(vals[GeoId]); id = gf->getId();
An example of static Id utility function
const Part::Geometry *geo = getGeometry(GeoId); ... std::unique_ptr<Part::GeomBSplineCurve> bspline(new Part::GeomBSplineCurve(curve)); ...
Part::GeomBSplineCurve * gbsc = bspline.release(); GeometryFacade::copyId(geo, gbsc);
Examples getting and setting the construction stations without creating a Facade:
if ((*geo) && GeometryFacade::getConstruction(*geo) && (*geo)->is<Part::GeomLineSegment>()) count++;
Part::Geometry* copy = v->copy();
if(construction && copy->getTypeId() != Part::GeomPoint::getClassTypeId()) { GeometryFacade::setConstruction(copy, construction); }
Note: The standard GeometryFacade stores Part::Geometry derived classes as a Part::Geometry *, while it has the ability to return a dynamic_cast-ed version to a provided type as follows:
HLine->getGeometry<Part::GeomLineSegment>();
If for seamless operation it is convenient to have a given derived class of Part::Geometry, it is possible to use GeometryTypedFacade (see below).
Remarks
Summary Remarks: It is intended to have a separate type (not being a Geometry type). it is intended to have the relevant interface in full for the sketcher extension only It is intended to work on borrowed memory allocation. But the getFacade has an owner parameter to take ownership of the geometry pointer if that is intended (this can also be achieved via the setOwner method once created).
Definition at line 130 of file GeometryFacade.h.
Constructor & Destructor Documentation
GeometryFacade() [1/4]
GeometryFacade::GeometryFacade (const Part::Geometry * geometry, bool owner = false) explicit protected
Definition at line 42 of file GeometryFacade.cpp.
GeometryFacade() [2/4]
GeometryFacade::GeometryFacade () protected
Definition at line 36 of file GeometryFacade.cpp.
Referenced by getFacade(), and getPyObject().
GeometryFacade() [3/4]
Sketcher::GeometryFacade::GeometryFacade (const GeometryFacade &) delete
GeometryFacade() [4/4]
Sketcher::GeometryFacade::GeometryFacade (GeometryFacade &&) default
~GeometryFacade()
GeometryFacade::~GeometryFacade () override
Definition at line 51 of file GeometryFacade.cpp.
Member Function Documentation
clone()
Part::Geometry* Sketcher::GeometryFacade::clone () const inline
Definition at line 286 of file GeometryFacade.h.
Referenced by SketcherGui::GeometryLayerParameters::getSubLayerIndex().
copy()
Part::Geometry* Sketcher::GeometryFacade::copy () const inline
Definition at line 282 of file GeometryFacade.h.
copyId()
void GeometryFacade::copyId (const Part::Geometry * src, Part::Geometry * dst) static
Definition at line 128 of file GeometryFacade.cpp.
References getFacade().
Referenced by Sketcher::SketchObject::convertToNURBS(), Sketcher::SketchObject::increaseBSplineDegree(), and Sketcher::SketchObject::modifyBSplineKnotMultiplicity().
deleteExtension() [1/2]
void Sketcher::GeometryFacade::deleteExtension (const Base::Type & type) inline
Definition at line 319 of file GeometryFacade.h.
deleteExtension() [2/2]
void Sketcher::GeometryFacade::deleteExtension (const std::string & name) inline
Definition at line 323 of file GeometryFacade.h.
ensureSketchGeometryExtension()
void GeometryFacade::ensureSketchGeometryExtension (Part::Geometry * geometry) static
Definition at line 119 of file GeometryFacade.cpp.
References Base::BaseClass::getClassTypeId().
getBlocked() [1/2]
bool Sketcher::GeometryFacade::getBlocked () const inline
Definition at line 217 of file GeometryFacade.h.
Referenced by Sketcher::SketchObject::fillet().
getBlocked() [2/2]
bool GeometryFacade::getBlocked (const Part::Geometry * geometry) static
Definition at line 198 of file GeometryFacade.cpp.
References getFacade().
getConstruction() [1/2]
bool Sketcher::GeometryFacade::getConstruction () const inline
Definition at line 226 of file GeometryFacade.h.
Referenced by Sketcher::SketchObject::buildShape(), Sketcher::PythonConverter::convert(), Sketcher::SketchObject::getAxis(), Sketcher::SketchObject::getAxisCount(), Sketcher::SketchObject::join(), and Sketcher::SketchObject::split().
getConstruction() [2/2]
bool GeometryFacade::getConstruction (const Part::Geometry * geometry) static
Definition at line 150 of file GeometryFacade.cpp.
References getFacade().
Referenced by SketcherGui::GeometryLayerParameters::getSubLayerIndex().
getExtension() [1/2]
std::weak_ptr<const Part::GeometryExtension> Sketcher::GeometryFacade::getExtension (const Base::Type & type) const inline
Definition at line 307 of file GeometryFacade.h.
getExtension() [2/2]
std::weak_ptr<const Part::GeometryExtension> Sketcher::GeometryFacade::getExtension (const std::string & name) const inline
Definition at line 311 of file GeometryFacade.h.
getExtensionName()
const std::string& Sketcher::GeometryFacade::getExtensionName () const inline
Definition at line 246 of file GeometryFacade.h.
getExtensions()
std::vector<std::weak_ptr<const Part::GeometryExtension> > Sketcher::GeometryFacade::getExtensions () const inline
Definition at line 295 of file GeometryFacade.h.
References Path.Post.scripts.opensbp_post::move().
getFacade()
std::unique_ptr< GeometryFacade > GeometryFacade::getFacade (const Part::Geometry * geometry, bool owner = false) static
Definition at line 58 of file GeometryFacade.cpp.
References GeometryFacade().
Referenced by Sketcher::SketchObject::addCopy(), Sketcher::Sketch::addGeometry(), Sketcher::SketchObject::addSymmetric(), Sketcher::SketchObject::convertSubName(), copyId(), Sketcher::SketchAnalysis::detectMissingPointOnPointConstraints(), Sketcher::Sketch::extractGeoListFacade(), Sketcher::Sketch::extractGeometry(), Sketcher::GeoListModel< T >::GeoListModel(), getBlocked(), getConstruction(), Sketcher::SketchObject::getGeoListFacade(), Sketcher::SketchObject::getGeometryFacade(), Sketcher::GeoListModel< T >::getGeometryFacadeFromGeoId(), Sketcher::SketchObject::getGeometryId(), getId(), getInternalType(), Sketcher::SketchObject::getSymmetric(), isInternalAligned(), isInternalType(), Sketcher::SketchObject::migrateSketch(), Sketcher::SketchObject::onChanged(), setConstruction(), Sketcher::SketchObject::setGeometryId(), setId(), setInternalType(), Sketcher::SketchObject::synchroniseGeometryState(), Sketcher::SketchObject::toggleConstruction(), Sketcher::Sketch::toShape(), and Sketcher::SketchObject::validateExpression().
getGeometry() [1/2]
template<typename GeometryT = Part::Geometry, typename = typename std::enable_if< std::is_base_of<Part::Geometry, typename std::decay<GeometryT>::type>::value>::type> GeometryT* Sketcher::GeometryFacade::getGeometry () inline
Definition at line 256 of file GeometryFacade.h.
getGeometry() [2/2]
template<typename GeometryT = Part::Geometry, typename = typename std::enable_if< std::is_base_of<Part::Geometry, typename std::decay<GeometryT>::type>::value>::type> const GeometryT* Sketcher::GeometryFacade::getGeometry () const inline
Definition at line 266 of file GeometryFacade.h.
getGeometryLayerId()
int Sketcher::GeometryFacade::getGeometryLayerId () const inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 207 of file GeometryFacade.h.
References Sketcher::GeometryMode::Construction.
getId() [1/2]
long Sketcher::GeometryFacade::getId () const inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 180 of file GeometryFacade.h.
Referenced by Sketcher::SketchObject::checkSubName(), Sketcher::SketchObject::generateId(), Sketcher::SketchObject::rebuildExternalGeometry(), and Sketcher::SketchObject::updateGeoHistory().
getId() [2/2]
int GeometryFacade::getId (const Part::Geometry * geometry) static
Definition at line 138 of file GeometryFacade.cpp.
References getFacade().
getInternalType() [1/2]
InternalType::InternalType Sketcher::GeometryFacade::getInternalType () const inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 189 of file GeometryFacade.h.
getInternalType() [2/2]
InternalType::InternalType GeometryFacade::getInternalType (const Part::Geometry * geometry) static
Definition at line 182 of file GeometryFacade.cpp.
References getFacade().
getOwner()
bool Sketcher::GeometryFacade::getOwner () const inline
Definition at line 174 of file GeometryFacade.h.
References Path.Post.scripts.grbl_post::type.
getPyObject()
PyObject * GeometryFacade::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 206 of file GeometryFacade.cpp.
References GeometryFacade(), and GeometryFacadePy.
getTag()
boost::uuids::uuid Sketcher::GeometryFacade::getTag () const inline
Definition at line 290 of file GeometryFacade.h.
Handle()
const Sketcher::GeometryFacade::Handle (Geom_Geometry) const & inline
Definition at line 278 of file GeometryFacade.h.
hasExtension() [1/2]
bool Sketcher::GeometryFacade::hasExtension (const Base::Type & type) const inline
Definition at line 299 of file GeometryFacade.h.
References Path.Post.scripts.grbl_post::type.
hasExtension() [2/2]
bool Sketcher::GeometryFacade::hasExtension (const std::string & name) const inline
Definition at line 303 of file GeometryFacade.h.
isGeoType()
bool Sketcher::GeometryFacade::isGeoType (const Base::Type & type) const inline
Definition at line 354 of file GeometryFacade.h.
isInternalAligned() [1/2]
bool Sketcher::GeometryFacade::isInternalAligned () const inline
Definition at line 235 of file GeometryFacade.h.
isInternalAligned() [2/2]
bool GeometryFacade::isInternalAligned (const Part::Geometry * geometry) static
Definition at line 174 of file GeometryFacade.cpp.
References getFacade().
Referenced by SketcherGui::GeometryLayerParameters::getSubLayerIndex(), and SketcherGui::EditModeGeometryCoinManager::updateGeometryColor().
isInternalType() [1/2]
bool GeometryFacade::isInternalType (const Part::Geometry * geometry, InternalType::InternalType type) static
Definition at line 166 of file GeometryFacade.cpp.
References getFacade(), and Path.Post.scripts.grbl_post::type.
Referenced by Sketcher::Sketch::addConstraint(), and Sketcher::SketchObject::trim().
isInternalType() [2/2]
bool Sketcher::GeometryFacade::isInternalType (InternalType::InternalType type) const inline
Definition at line 240 of file GeometryFacade.h.
mirror() [1/2]
void Sketcher::GeometryFacade::mirror (const Base::Vector3d & point) inline
Definition at line 328 of file GeometryFacade.h.
References SurfaceTests.TestBlendCurve::vec.
mirror() [2/2]
void Sketcher::GeometryFacade::mirror (const Base::Vector3d & point, Base::Vector3d dir) inline
Definition at line 332 of file GeometryFacade.h.
operator=() [1/2]
GeometryFacade& Sketcher::GeometryFacade::operator= (const GeometryFacade &) delete
operator=() [2/2]
GeometryFacade& Sketcher::GeometryFacade::operator= (GeometryFacade &&) default
rotate()
void Sketcher::GeometryFacade::rotate (const Base::Placement & plm) inline
Definition at line 336 of file GeometryFacade.h.
scale()
void Sketcher::GeometryFacade::scale (const Base::Vector3d & vec, double scale) inline
Definition at line 340 of file GeometryFacade.h.
setBlocked()
void Sketcher::GeometryFacade::setBlocked (bool status = true) inline
Definition at line 221 of file GeometryFacade.h.
References Path.Post.scripts.grbl_post::type.
setConstruction() [1/2]
void Sketcher::GeometryFacade::setConstruction (bool construction) inline
Definition at line 230 of file GeometryFacade.h.
setConstruction() [2/2]
void GeometryFacade::setConstruction (Part::Geometry * geometry, bool construction) static
Definition at line 158 of file GeometryFacade.cpp.
References getFacade().
Referenced by Sketcher::SketchObject::addCopy(), Sketcher::SketchObject::addGeometry(), SketcherGui::DrawSketchDefaultHandler< ControllerT::HandlerType, ControllerT::SelectModeType, ControllerT::AutoConstraintInitialSize, ControllerT::ContructionMethodType >::addToShapeConstraints(), Sketcher::SketchObject::carbonCopy(), Sketcher::SketchObject::migrateSketch(), Sketcher::SketchObject::rebuildExternalGeometry(), and Sketcher::SketchObject::setConstruction().
setExtension()
void Sketcher::GeometryFacade::setExtension (std::unique_ptr< Part::GeometryExtension > && geo) inline
Definition at line 315 of file GeometryFacade.h.
setGeometry()
void GeometryFacade::setGeometry (Part::Geometry * geometry)
Definition at line 71 of file GeometryFacade.cpp.
References THROWM.
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_readme_browser.WidgetReadmeBrowser::setMarkdown().
setGeometryLayerId()
void Sketcher::GeometryFacade::setGeometryLayerId (int geolayer) inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 211 of file GeometryFacade.h.
References Sketcher::GeometryMode::Construction.
setGeometryMode()
void Sketcher::GeometryFacade::setGeometryMode (int flag, bool v = true) inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 202 of file GeometryFacade.h.
References Sketcher::GeometryMode::Blocked.
setId() [1/2]
void GeometryFacade::setId (const Part::Geometry * geometry, int id) static
Definition at line 144 of file GeometryFacade.cpp.
References getFacade().
Referenced by Sketcher::SketchObject::generateId(), and Sketcher::SketchObject::rebuildExternalGeometry().
setId() [2/2]
void Sketcher::GeometryFacade::setId (long id) inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 184 of file GeometryFacade.h.
setInternalType() [1/2]
void Sketcher::GeometryFacade::setInternalType (InternalType::InternalType type) inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 193 of file GeometryFacade.h.
setInternalType() [2/2]
void GeometryFacade::setInternalType (Part::Geometry * geometry, InternalType::InternalType type) static
Definition at line 190 of file GeometryFacade.cpp.
References getFacade(), and Path.Post.scripts.grbl_post::type.
setOwner()
void Sketcher::GeometryFacade::setOwner (bool owner) inline
Definition at line 168 of file GeometryFacade.h.
testGeometryMode()
bool Sketcher::GeometryFacade::testGeometryMode (int flag) const inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 198 of file GeometryFacade.h.
References Sketcher::GeometryMode::Blocked.
toShape()
TopoDS_Shape Sketcher::GeometryFacade::toShape () const inline
Definition at line 274 of file GeometryFacade.h.
transform()
void Sketcher::GeometryFacade::transform (const Base::Matrix4D & mat) inline
Definition at line 344 of file GeometryFacade.h.
translate()
void Sketcher::GeometryFacade::translate (const Base::Vector3d & vec) inline
Definition at line 348 of file GeometryFacade.h.
Friends And Related Function Documentation
GeometryFacadePy
friend class GeometryFacadePy friend
Definition at line 138 of file GeometryFacade.h.
Referenced by getPyObject().
The documentation for this class was generated from the following files:
GeometryFacade.h
GeometryFacade.cpp