FreeCAD: MeshCore::MeshProjection Class Reference
MeshCore::MeshProjection Class Reference
#include <Projection.h>
Public Member Functions
MeshProjection (const MeshKernel &)
bool projectLineOnMesh (const MeshFacetGrid &grid, const Base::Vector3f &p1, FacetIndex f1, const Base::Vector3f &p2, FacetIndex f2, const Base::Vector3f &view, std::vector< Base::Vector3f > &polyline)
Protected Member Functions
bool bboxInsideRectangle (const Base::BoundBox3f &bbox, const Base::Vector3f &p1, const Base::Vector3f &p2, const Base::Vector3f &view) const
bool isPointInsideDistance (const Base::Vector3f &p1, const Base::Vector3f &p2, const Base::Vector3f &pt) const
bool connectLines (std::list< std::pair< Base::Vector3f, Base::Vector3f >> &cutLines, const Base::Vector3f &startPoint, const Base::Vector3f &endPoint, std::vector< Base::Vector3f > &polyline) const
Detailed Description
Definition at line 46 of file Projection.h.
Constructor & Destructor Documentation
MeshProjection()
MeshProjection::MeshProjection (const MeshKernel & mesh) explicit
Definition at line 40 of file Projection.cpp.
Member Function Documentation
bboxInsideRectangle()
bool MeshProjection::bboxInsideRectangle (const Base::BoundBox3f & bbox, const Base::Vector3f & p1, const Base::Vector3f & p2, const Base::Vector3f & view) const protected
Definition at line 44 of file Projection.cpp.
References importers.importWebGL::base, Base::BoundBox3< Precision >::CalcDiagonalLength(), Base::Vector3< float_type >::DistanceToPlane(), Base::BoundBox3< Precision >::GetCenter(), Base::BoundBox3< Precision >::IsCutPlane(), FreeCADInit::Length, and Base::Vector3< float_type >::Normalize().
Referenced by projectLineOnMesh().
connectLines()
bool MeshProjection::connectLines (std::list< std::pair< Base::Vector3f, Base::Vector3f >> & cutLines, const Base::Vector3f & startPoint, const Base::Vector3f & endPoint, std::vector< Base::Vector3f > & polyline) const protected
Definition at line 76 of file Projection.cpp.
References Base::DistanceP2(), FLOAT_MAX, and KDL::sqrt().
Referenced by projectLineOnMesh().
isPointInsideDistance()
bool MeshProjection::isPointInsideDistance (const Base::Vector3f & p1, const Base::Vector3f & p2, const Base::Vector3f & pt) const protected
Definition at line 64 of file Projection.cpp.
References Path.Post.scripts.opensbp_post::move(), and Base::Vector3< float_type >::ProjectToLine().
Referenced by projectLineOnMesh().
projectLineOnMesh()
bool MeshProjection::projectLineOnMesh (const MeshFacetGrid & grid, const Base::Vector3f & p1, FacetIndex f1, const Base::Vector3f & p2, FacetIndex f2, const Base::Vector3f & view, std::vector< Base::Vector3f > & polyline)
Definition at line 134 of file Projection.cpp.
References importers.importWebGL::base, bboxInsideRectangle(), connectLines(), src.Mod.PartDesign.Scripts.Gear::e1, MeshCore::MeshGridIterator::GetBoundBox(), MeshCore::MeshGeomFacet::GetBoundBox(), MeshCore::MeshGridIterator::GetElements(), MeshCore::MeshKernel::GetFacet(), Plot::grid(), MeshCore::MeshGridIterator::Init(), MeshCore::MeshGeomFacet::IntersectWithPlane(), isPointInsideDistance(), MeshCore::MeshGridIterator::More(), MeshCore::MeshGridIterator::Next(), Base::Vector3< float_type >::Normalize(), draftgeoutils.general::v1(), and CAMTests.TestPathVoronoi::vd.
Referenced by MeshPartGui::CurveOnMeshHandler::Private::projectLineOnMesh(), and MeshPart::MeshProjection::projectParallelToMesh().
The documentation for this class was generated from the following files:
Projection.h
Projection.cpp