FreeCAD: ExpressionDelegate Class Reference
ExpressionDelegate Class Reference
Public Member Functions
ExpressionDelegate (QListWidget *_view)
Protected Member Functions
QPixmap getIcon (const char *name, const QSize &size) const
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const override
Protected Attributes
QListWidget * view
Detailed Description
Definition at line 439 of file TaskSketcherConstraints.cpp.
Constructor & Destructor Documentation
ExpressionDelegate()
ExpressionDelegate::ExpressionDelegate (QListWidget * _view) inline explicit
Definition at line 442 of file TaskSketcherConstraints.cpp.
Member Function Documentation
getIcon()
QPixmap ExpressionDelegate::getIcon (const char * name, const QSize & size) const inline protected
Definition at line 448 of file TaskSketcherConstraints.cpp.
References Gui::BitmapFactory(), DraftVecUtils::find(), AssemblyImport::insert(), and Gui::BitmapFactoryInst::pixmapFromSvg().
paint()
void ExpressionDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const inline override protected
Definition at line 464 of file TaskSketcherConstraints.cpp.
References ConstraintItem::ConstraintNbr, Sketcher::SketchObject::Constraints, Sketcher::PropertyConstraintList::createPath(), App::PropertyExpressionEngine::ExpressionInfo::expression, App::DocumentObject::getExpression(), bimcommands.BimIfcElements::getIcon(), Sketcher::PropertyConstraintList::getSize(), Sketcher::Constraint::isDriving, toolbit-attributes::s, and ConstraintItem::sketch.
Member Data Documentation
view
QListWidget* ExpressionDelegate::view protected
Definition at line 496 of file TaskSketcherConstraints.cpp.
Referenced by TechDrawTools.TaskAddOffsetVertex.TaskAddOffsetVertex::accept(), src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::set_status_filter(), TDTest.DrawViewDimensionTest.DrawViewDimensionTest::testLengthDimension(), TDTest.DrawViewDetailTest.DrawViewDetailTest::testMakeDrawViewPart(), TDTest.DrawViewSectionTest.DrawViewSectionTest::testMakeDrawViewSection(), and TDTest.DrawHatchTest.DrawHatchTest::testMakeHatchCase().
The documentation for this class was generated from the following file:
TaskSketcherConstraints.cpp