FreeCAD: Gui::QuantitySpinBoxPrivate Class Reference
Gui::QuantitySpinBoxPrivate Class Reference
Public Member Functions
QuantitySpinBoxPrivate (QuantitySpinBox *q)
~QuantitySpinBoxPrivate ()=default
QString stripped (const QString &t, int *pos) const
bool validate (QString &input, Base::Quantity &result, const App::ObjectIdentifier &path) const
bool parseString (const QString &str, Base::Quantity &result, double &value, const App::ObjectIdentifier &path) const
Base::Quantity validateAndInterpret (QString &input, QValidator::State &state, const App::ObjectIdentifier &path) const
Public Attributes
QLocale locale
bool validInput
bool pendingEmit
bool checkRangeInExpression
QString validStr
Base::Quantity quantity
Base::Quantity cached
Base::Unit unit
double unitValue
QString unitStr
double maximum
double minimum
double singleStep
QuantitySpinBox * q_ptr
std::unique_ptr< Base::UnitsSchema > scheme
Detailed Description
Definition at line 61 of file QuantitySpinBox.cpp.
Constructor & Destructor Documentation
QuantitySpinBoxPrivate()
Gui::QuantitySpinBoxPrivate::QuantitySpinBoxPrivate (QuantitySpinBox * q) inline
Definition at line 64 of file QuantitySpinBox.cpp.
~QuantitySpinBoxPrivate()
Gui::QuantitySpinBoxPrivate::~QuantitySpinBoxPrivate () default
Member Function Documentation
parseString()
bool Gui::QuantitySpinBoxPrivate::parseString (const QString & str, Base::Quantity & result, double & value, const App::ObjectIdentifier & path) const inline
Definition at line 129 of file QuantitySpinBox.cpp.
References App::UnitExpression::getQuantity(), App::ExpressionParser::parse(), result, and Path.Post.scripts.refactored_centroid_post::str.
stripped()
QString Gui::QuantitySpinBoxPrivate::stripped (const QString & t, int * pos) const inline
Definition at line 77 of file QuantitySpinBox.cpp.
References RobotExample::pos, toolbit-attributes::s, and InitGui::t.
validate()
bool Gui::QuantitySpinBoxPrivate::validate (QString & input, Base::Quantity & result, const App::ObjectIdentifier & path) const inline
Definition at line 87 of file QuantitySpinBox.cpp.
References result, Base::UnitsApi::schemaTranslate(), Base::Quantity::setFormat(), Base::Quantity::setUnit(), unit(), and Gui::validateInput().
validateAndInterpret()
Base::Quantity Gui::QuantitySpinBoxPrivate::validateAndInterpret (QString & input, QValidator::State & state, const App::ObjectIdentifier & path) const inline
Definition at line 154 of file QuantitySpinBox.cpp.
References Base::Quantity::getUnit(), Base::Unit::isEmpty(), KDL::max(), KDL::min(), src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression, Base::Quantity::setUnit(), Base::Quantity::setValue(), and unit().
Member Data Documentation
cached
Base::Quantity Gui::QuantitySpinBoxPrivate::cached
Definition at line 259 of file QuantitySpinBox.cpp.
Referenced by nativeifc.ifc_objects.ifc_object::execute().
checkRangeInExpression
bool Gui::QuantitySpinBoxPrivate::checkRangeInExpression
Definition at line 256 of file QuantitySpinBox.cpp.
locale
QLocale Gui::QuantitySpinBoxPrivate::locale
Definition at line 253 of file QuantitySpinBox.cpp.
maximum
double Gui::QuantitySpinBoxPrivate::maximum
Definition at line 263 of file QuantitySpinBox.cpp.
minimum
double Gui::QuantitySpinBoxPrivate::minimum
Definition at line 264 of file QuantitySpinBox.cpp.
pendingEmit
bool Gui::QuantitySpinBoxPrivate::pendingEmit
Definition at line 255 of file QuantitySpinBox.cpp.
q_ptr
QuantitySpinBox* Gui::QuantitySpinBoxPrivate::q_ptr
Definition at line 266 of file QuantitySpinBox.cpp.
quantity
Base::Quantity Gui::QuantitySpinBoxPrivate::quantity
Definition at line 258 of file QuantitySpinBox.cpp.
Referenced by automotive_design.quantified_assembly_component_usage::wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.quantified_assembly_component_usage::wr1(), automotive_design.make_from_usage_option::wr1(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.make_from_usage_option::wr1().
scheme
std::unique_ptr<Base::UnitsSchema> Gui::QuantitySpinBoxPrivate::scheme
Definition at line 267 of file QuantitySpinBox.cpp.
singleStep
double Gui::QuantitySpinBoxPrivate::singleStep
Definition at line 265 of file QuantitySpinBox.cpp.
unit
Base::Unit Gui::QuantitySpinBoxPrivate::unit
Definition at line 260 of file QuantitySpinBox.cpp.
unitStr
QString Gui::QuantitySpinBoxPrivate::unitStr
Definition at line 262 of file QuantitySpinBox.cpp.
unitValue
double Gui::QuantitySpinBoxPrivate::unitValue
Definition at line 261 of file QuantitySpinBox.cpp.
validInput
bool Gui::QuantitySpinBoxPrivate::validInput
Definition at line 254 of file QuantitySpinBox.cpp.
validStr
QString Gui::QuantitySpinBoxPrivate::validStr
Definition at line 257 of file QuantitySpinBox.cpp.
The documentation for this class was generated from the following file:
QuantitySpinBox.cpp