FreeCAD: Gui::PrefRadioButton Class Reference
Gui::PrefRadioButton Class Reference
#include <PrefWidgets.h>
Public Member Functions
PrefRadioButton (QWidget *parent=nullptr)
~PrefRadioButton () override
Public Member Functions inherited from Gui::PrefWidget
void setEntryName (const QByteArray &name)
QByteArray entryName () const
void setPrefEntry (const QByteArray &name)
void setParamGrpPath (const QByteArray &path)
QByteArray paramGrpPath () const
void setPrefPath (const QByteArray &name)
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
void onSave ()
void onRestore ()
Public Member Functions inherited from Gui::WindowParameter
WindowParameter (const char *name)
~WindowParameter () override
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
ParameterGrp::handle getWindowParameter ()
return the parameter group of this window
Protected Member Functions
void restorePreferences () override
void savePreferences () override
Protected Member Functions inherited from Gui::PrefWidget
void failedToSave (const QString &) const
void failedToRestore (const QString &) const
PrefWidget ()
~PrefWidget () override
Protected Member Functions inherited from Gui::WindowParameter
bool setGroupName (const char *name)
template<typename S , typename T >
void setSlotParamChanged (S slot, T *obsPtr)
connect slot to ParameterManager signal
Properties
QByteArray prefEntry
QByteArray prefPath
Additional Inherited Members
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter ()
get the parameters
Protected Attributes inherited from Gui::PrefWidget
bool m_Restored = false
Detailed Description
The PrefRadioButton class.
Author
Werner Mayer
Definition at line 295 of file PrefWidgets.h.
Constructor & Destructor Documentation
PrefRadioButton()
PrefRadioButton::PrefRadioButton (QWidget * parent = nullptr) explicit
Definition at line 457 of file PrefWidgets.cpp.
~PrefRadioButton()
PrefRadioButton::~PrefRadioButton () override default
Member Function Documentation
restorePreferences()
void PrefRadioButton::restorePreferences () override protected virtual
Restores the preferences Must be reimplemented in any subclasses.
Implements Gui::PrefWidget.
Definition at line 464 of file PrefWidgets.cpp.
References Gui::PrefWidget::entryName(), Gui::PrefWidget::failedToRestore(), ParameterGrp::GetBool(), Gui::WindowParameter::getWindowParameter(), and draftgeoutils.general::isNull().
savePreferences()
void PrefRadioButton::savePreferences () override protected virtual
Save the preferences Must be reimplemented in any subclasses.
Implements Gui::PrefWidget.
Definition at line 476 of file PrefWidgets.cpp.
References Gui::PrefWidget::entryName(), Gui::PrefWidget::failedToSave(), Gui::WindowParameter::getWindowParameter(), draftgeoutils.general::isNull(), and ParameterGrp::SetBool().
Property Documentation
prefEntry
QByteArray Gui::PrefRadioButton::prefEntry read write
Definition at line 299 of file PrefWidgets.h.
prefPath
QByteArray Gui::PrefRadioButton::prefPath read write
Definition at line 300 of file PrefWidgets.h.
The documentation for this class was generated from the following files:
PrefWidgets.h
PrefWidgets.cpp