FreeCAD: Gui::StartupPostProcess Class Reference
Gui::StartupPostProcess Class Reference
#include <StartupProcess.h>
Public Member Functions
StartupPostProcess (MainWindow *mw, Application &guiApp, QApplication *app)
void setLoadFromPythonModule (bool value)
void execute ()
Detailed Description
Definition at line 53 of file StartupProcess.h.
Constructor & Destructor Documentation
StartupPostProcess()
StartupPostProcess::StartupPostProcess (MainWindow * mw, Application & guiApp, QApplication * app)
Definition at line 201 of file StartupProcess.cpp.
References NavigationIndicatorGui::mw.
Member Function Documentation
execute()
void StartupPostProcess::execute ()
Definition at line 213 of file StartupProcess.cpp.
Referenced by draftobjects.facebinder.Facebinder::addSubobjects(), Path.Dressup.Gui.Dogbone.ObjectDressup::boneStateList(), Path.Dressup.Tags.ObjectTagDressup::generateTags(), ArchRoof._Roof::getSubVolume(), ArchPanel.PanelCut::getWires(), src.Mod.PartDesign.Scripts.Spring.MySpring::onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid::onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped::onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt::onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder::onChanged(), MeasureCOM.MeasureCOM::onChanged(), Path.Main.Stock.StockFromBase::onChanged(), Path.Main.Stock.StockCreateBox::onChanged(), Path.Main.Stock.StockCreateCylinder::onChanged(), FeaturePython.DistanceBolt::onChanged(), draftobjects.draftlink.DraftLink::onDocumentRestored(), Gui::Application::runApplication(), ArchSchedule._ArchSchedule::setSpreadsheetData(), and draftobjects.array.Array::update_properties_0v21().
setLoadFromPythonModule()
void StartupPostProcess::setLoadFromPythonModule (bool value)
Definition at line 208 of file StartupProcess.cpp.
The documentation for this class was generated from the following files:
StartupProcess.h
StartupProcess.cpp