FreeCAD: SketcherGui::DrawSketchHandler Class Reference
SketcherGui::DrawSketchHandler Class Reference abstract
#include <DrawSketchHandler.h>
Public Member Functions
DrawSketchHandler ()
virtual ~DrawSketchHandler ()
void activate (ViewProviderSketch *)
void deactivate () override
virtual void mouseMove (Base::Vector2d pos)=0
virtual bool pressButton (Base::Vector2d pos)=0
virtual bool releaseButton (Base::Vector2d pos)=0
virtual void registerPressedKey (bool pressed, int key)
virtual void pressRightButton (Base::Vector2d pos)
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
void quit () override
int getHighestVertexIndex ()
int getHighestCurveIndex ()
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
int seekAndRenderAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::PointPos::none, bool createowncommand=true)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
void setPositionText (const Base::Vector2d &Pos)
void resetPositionText ()
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
Public Member Functions inherited from Gui::ToolHandler
ToolHandler ()=default
virtual ~ToolHandler ()=default
bool activate ()
void updateCursor ()
Friends
class ViewProviderSketch
Interfacing with tool dialogs
ViewProviderSketch * sketchgui
QWidget * toolwidget
void toolWidgetChanged (QWidget *newwidget)
Slot to receive signaling that a widget intended for the tool has changed and is available ant the provided pointer.
std::unique_ptr< QWidget > createToolWidget () const
Factory function returning a tool widget of the type necessary for the specific tool. This is a NVI interface and specific handlers must overload the corresponding virtual function.
bool isToolWidgetVisible () const
Returns whether this tool expects/supports a visible tool widget. Emphasis is in visibility, so to allow one to adapt the interface accordingly. This is an NVI interface and specific handlers must overload the corresponding virtual function.
QPixmap getToolWidgetHeaderIcon () const
Returns a pixmap icon intended for a visible tool widget. This is an NVI interface and specific handlers must overload the corresponding virtual function.
QString getToolWidgetHeaderText () const
Returns a header text intended for a visible tool widget. This is an NVI interface and specific handlers must overload the corresponding virtual function.
virtual std::string getToolName () const
virtual std::unique_ptr< QWidget > createWidget () const
virtual bool isWidgetVisible () const
virtual QPixmap getToolIcon () const
virtual QString getToolWidgetText () const
void drawEdit (const std::vector< Base::Vector2d > &EditCurve) const
void drawEdit (const std::list< std::vector< Base::Vector2d >> &list) const
void drawEdit (const std::vector< Part::Geometry * > &geometries) const
void drawEditMarkers (const std::vector< Base::Vector2d > &EditMarkers, unsigned int augmentationlevel=0) const
void clearEdit () const
void clearEditMarkers () const
void setAxisPickStyle (bool on)
void moveCursorToSketchPoint (Base::Vector2d point)
void ensureFocus ()
void preselectAtPoint (Base::Vector2d point)
void drawPositionAtCursor (const Base::Vector2d &position)
void drawDirectionAtCursor (const Base::Vector2d &position, const Base::Vector2d &origin)
void drawWidthHeightAtCursor (const Base::Vector2d &position, const double val1, const double val2)
void drawDoubleAtCursor (const Base::Vector2d &position, const double radius, Base::Unit unit=Base::Unit::Length)
int getPreselectPoint () const
int getPreselectCurve () const
int getPreselectCross () const
Sketcher::SketchObject * getSketchObject ()
void setAngleSnapping (bool enable, Base::Vector2d referencePoint=Base::Vector2d(0., 0.))
void moveConstraint (int constNum, const Base::Vector2d &toPos)
void signalToolChanged () const
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Additional Inherited Members
Protected Member Functions inherited from Gui::ToolHandler
virtual QString getCrosshairCursorSVGName () const
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
void unsetCursor ()
void applyCursor ()
restitutes the DSH cached cursor (without any tail due to autoconstraints, ...)
void addCursorTail (std::vector< QPixmap > &pixmaps)
unsigned long getCrosshairColor ()
returns the color to be used for the crosshair (configurable as a parameter)
qreal devicePixelRatio ()
functions to set the cursor to a given svgName (to be migrated to NVI style)
View3DInventorViewer * getViewer ()
virtual QWidget * getCursorWidget ()
virtual void setWidgetCursor (QCursor cursor)
Protected Attributes inherited from Gui::ToolHandler
QCursor oldCursor
QCursor actCursor
QPixmap actCursorPixmap
Detailed Description
Handler to create new sketch geometry This class has to be reimplemented to create geometry in the sketcher while its in editing.
DrawSketchHandler takes over the responsibility of drawing edit temporal curves and markers necessary to enable visual feedback to the user, as well as the UI interaction during such edits. This is its exclusive responsibility under the Single Responsibility Principle.
A plethora of speciliased handlers derive from DrawSketchHandler for each specialised editing (see for example all the handlers for creation of new geometry). These derived classes do * not * have direct access to the ViewProviderSketchDrawSketchHandlerAttorney. This is intended to keep coupling under control. However, generic functionality requiring access to the Attorney can be implemented in DrawSketchHandler and used from its derived classes by virtue of the inheritance. This promotes a concentrating the coupling in a single point (and code reuse).
Definition at line 141 of file DrawSketchHandler.h.
Constructor & Destructor Documentation
DrawSketchHandler()
DrawSketchHandler::DrawSketchHandler ()
Definition at line 272 of file DrawSketchHandler.cpp.
~DrawSketchHandler()
DrawSketchHandler::~DrawSketchHandler () virtual
Definition at line 277 of file DrawSketchHandler.cpp.
Member Function Documentation
activate()
void DrawSketchHandler::activate (ViewProviderSketch * vp)
Definition at line 306 of file DrawSketchHandler.cpp.
References Gui::ToolHandler::activate(), SketcherGui::ViewProviderSketch::purgeHandler(), and sketchgui.
clearEdit()
void DrawSketchHandler::clearEdit () const protected
Definition at line 956 of file DrawSketchHandler.cpp.
References drawEdit().
Referenced by deactivate().
clearEditMarkers()
void DrawSketchHandler::clearEditMarkers () const protected
Definition at line 961 of file DrawSketchHandler.cpp.
References drawEditMarkers().
Referenced by deactivate().
createAutoConstraints()
void DrawSketchHandler::createAutoConstraints (const std::vector< AutoConstraint > & autoConstrs, int geoId, Sketcher::PointPos pointPos = Sketcher::PointPos::none, bool createowncommand = true)
Definition at line 748 of file DrawSketchHandler.cpp.
References SketcherGui::ViewProviderSketch::Autoconstraints, Gui::cmdAppObjectArgs(), Sketcher::Coincident, Gui::Command::commitCommand(), Sketcher::GeoUndef, Sketcher::SketchObject::getGeometry(), Gui::ViewProviderDocumentObject::getObject(), SketcherGui::ViewProviderSketch::getSketchObject(), App::PropertyBool::getValue(), Sketcher::Horizontal, Base::BaseClass::is(), SketcherGui::makeTangentToArcOfEllipseviaNewPoint(), SketcherGui::makeTangentToEllipseviaNewPoint(), Sketcher::none, Gui::Command::openCommand(), Sketcher::PointOnObject, Arch::QT_TRANSLATE_NOOP, sketchgui, Sketcher::Symmetric, Sketcher::Tangent, and Sketcher::Vertical.
Referenced by DrawSketchHandlerRectangularArray::releaseButton().
createToolWidget()
std::unique_ptr< QWidget > DrawSketchHandler::createToolWidget () const
Factory function returning a tool widget of the type necessary for the specific tool. This is a NVI interface and specific handlers must overload the corresponding virtual function.
Definition at line 1019 of file DrawSketchHandler.cpp.
References createWidget().
createWidget()
std::unique_ptr< QWidget > DrawSketchHandler::createWidget () const protected virtual
Definition at line 285 of file DrawSketchHandler.cpp.
Referenced by createToolWidget().
deactivate()
void DrawSketchHandler::deactivate () override virtual
Reimplemented from Gui::ToolHandler.
Definition at line 315 of file DrawSketchHandler.cpp.
References clearEdit(), clearEditMarkers(), Gui::ToolHandler::deactivate(), resetPositionText(), setAngleSnapping(), and sketchgui.
drawDirectionAtCursor()
void DrawSketchHandler::drawDirectionAtCursor (const Base::Vector2d & position, const Base::Vector2d & origin) protected
Definition at line 971 of file DrawSketchHandler.cpp.
References SketcherGui::angleToDisplayFormat(), SCL.SimpleDataTypes::f, FreeCADInit::Length, SketcherGui::lengthToDisplayFormat(), M_PI, setPositionText(), and SketcherGui::showCursorCoords().
drawDoubleAtCursor()
void DrawSketchHandler::drawDoubleAtCursor (const Base::Vector2d & position, const double radius, Base::Unit unit = Base::Unit::Length) protected
Definition at line 1003 of file DrawSketchHandler.cpp.
References SketcherGui::angleToDisplayFormat(), Base::Unit::Length, SketcherGui::lengthToDisplayFormat(), M_PI, setPositionText(), SketcherGui::showCursorCoords(), unit(), and toolbit-attributes::val.
drawEdit() [1/3]
void DrawSketchHandler::drawEdit (const std::list< std::vector< Base::Vector2d >> & list) const protected
Definition at line 942 of file DrawSketchHandler.cpp.
References sketchgui.
drawEdit() [2/3]
void DrawSketchHandler::drawEdit (const std::vector< Base::Vector2d > & EditCurve) const protected
Definition at line 937 of file DrawSketchHandler.cpp.
References sketchgui.
Referenced by clearEdit(), SketcherGui::DrawSketchDefaultHandler< ControllerT::HandlerType, ControllerT::SelectModeType, ControllerT::AutoConstraintInitialSize, ControllerT::ContructionMethodType >::commandAddShapeGeometryAndConstraints(), drawEdit(), DrawSketchHandlerCopy::mouseMove(), DrawSketchHandlerRectangularArray::mouseMove(), DrawSketchHandlerCopy::pressButton(), DrawSketchHandlerRectangularArray::pressButton(), DrawSketchHandlerCopy::releaseButton(), and DrawSketchHandlerRectangularArray::releaseButton().
drawEdit() [3/3]
void DrawSketchHandler::drawEdit (const std::vector< Part::Geometry * > & geometries) const protected
Definition at line 947 of file DrawSketchHandler.cpp.
References SCL.SimpleDataTypes::c, and drawEdit().
drawEditMarkers()
void DrawSketchHandler::drawEditMarkers (const std::vector< Base::Vector2d > & EditMarkers, unsigned int augmentationlevel = 0) const protected
Definition at line 1039 of file DrawSketchHandler.cpp.
References sketchgui.
Referenced by clearEditMarkers(), and DrawSketchHandlerBSplineInsertKnot::mouseMove().
drawPositionAtCursor()
void DrawSketchHandler::drawPositionAtCursor (const Base::Vector2d & position) protected
Definition at line 966 of file DrawSketchHandler.cpp.
References setPositionText().
drawWidthHeightAtCursor()
void DrawSketchHandler::drawWidthHeightAtCursor (const Base::Vector2d & position, const double val1, const double val2) protected
Definition at line 988 of file DrawSketchHandler.cpp.
References SketcherGui::lengthToDisplayFormat(), setPositionText(), and SketcherGui::showCursorCoords().
ensureFocus()
void DrawSketchHandler::ensureFocus () protected
Definition at line 1057 of file DrawSketchHandler.cpp.
References sketchgui.
getHighestCurveIndex()
int DrawSketchHandler::getHighestCurveIndex ()
Definition at line 376 of file DrawSketchHandler.cpp.
References Sketcher::SketchObject::getHighestCurveIndex(), SketcherGui::ViewProviderSketch::getSketchObject(), and sketchgui.
Referenced by seekAutoConstraint().
getHighestVertexIndex()
int DrawSketchHandler::getHighestVertexIndex ()
Definition at line 371 of file DrawSketchHandler.cpp.
References Sketcher::SketchObject::getHighestVertexIndex(), SketcherGui::ViewProviderSketch::getSketchObject(), and sketchgui.
getPreselectCross()
int DrawSketchHandler::getPreselectCross () const protected
Definition at line 1077 of file DrawSketchHandler.cpp.
References sketchgui.
Referenced by seekAutoConstraint().
getPreselectCurve()
int DrawSketchHandler::getPreselectCurve () const protected
Definition at line 1072 of file DrawSketchHandler.cpp.
References sketchgui.
Referenced by SketcherGui::DrawSketchHandlerTrimming::pressButton(), and seekAutoConstraint().
getPreselectPoint()
int DrawSketchHandler::getPreselectPoint () const protected
Definition at line 1067 of file DrawSketchHandler.cpp.
References sketchgui.
Referenced by SketcherGui::DrawSketchHandlerSplitting::pressButton(), and seekAutoConstraint().
getSketchObject()
Sketcher::SketchObject * DrawSketchHandler::getSketchObject () protected
Definition at line 1082 of file DrawSketchHandler.cpp.
References SketcherGui::ViewProviderSketch::getSketchObject(), and sketchgui.
getToolIcon()
QPixmap DrawSketchHandler::getToolIcon () const protected virtual
Definition at line 295 of file DrawSketchHandler.cpp.
Referenced by getToolWidgetHeaderIcon().
getToolName()
std::string DrawSketchHandler::getToolName () const protected virtual
Reimplemented in SketcherGui::DrawSketchControllableHandler< ControllerT >.
Definition at line 280 of file DrawSketchHandler.cpp.
Referenced by SketcherGui::DrawSketchControllableHandler< ControllerT >::DrawSketchControllableHandler(), and signalToolChanged().
getToolWidgetHeaderIcon()
QPixmap DrawSketchHandler::getToolWidgetHeaderIcon () const
Returns a pixmap icon intended for a visible tool widget. This is an NVI interface and specific handlers must overload the corresponding virtual function.
Definition at line 1029 of file DrawSketchHandler.cpp.
References getToolIcon().
getToolWidgetHeaderText()
QString DrawSketchHandler::getToolWidgetHeaderText () const
Returns a header text intended for a visible tool widget. This is an NVI interface and specific handlers must overload the corresponding virtual function.
Definition at line 1034 of file DrawSketchHandler.cpp.
References getToolWidgetText().
getToolWidgetText()
QString DrawSketchHandler::getToolWidgetText () const protected virtual
Definition at line 300 of file DrawSketchHandler.cpp.
Referenced by getToolWidgetHeaderText().
isToolWidgetVisible()
bool DrawSketchHandler::isToolWidgetVisible () const
Returns whether this tool expects/supports a visible tool widget. Emphasis is in visibility, so to allow one to adapt the interface accordingly. This is an NVI interface and specific handlers must overload the corresponding virtual function.
Definition at line 1024 of file DrawSketchHandler.cpp.
References isWidgetVisible().
isWidgetVisible()
bool DrawSketchHandler::isWidgetVisible () const protected virtual
Definition at line 290 of file DrawSketchHandler.cpp.
Referenced by isToolWidgetVisible().
mouseMove()
virtual void SketcherGui::DrawSketchHandler::mouseMove (Base::Vector2d pos) pure virtual
Implemented in DrawSketchHandlerGenConstraint, DrawSketchHandlerRectangularArray, DrawSketchHandlerDimension, DrawSketchHandlerCopy, DrawSketchHandlerBSplineInsertKnot, SketcherGui::DrawSketchDefaultHandler< HandlerT, SelectModeT, PInitAutoConstraintSize, ConstructionMethodT >, SketcherGui::DrawSketchDefaultHandler< ControllerT::HandlerType, ControllerT::SelectModeType, ControllerT::AutoConstraintInitialSize, ControllerT::ContructionMethodType >, SketcherGui::DrawSketchHandlerLineSet, SketcherGui::DrawSketchHandlerCarbonCopy, SketcherGui::DrawSketchHandlerExternal, SketcherGui::DrawSketchHandlerExtend, SketcherGui::DrawSketchControllableHandler< ControllerT >, SketcherGui::DrawSketchHandlerSplitting, SketcherGui::DrawSketchHandlerTrimming, SketcherGui::DrawSketchHandlerArcOfEllipse, SketcherGui::DrawSketchHandlerArcOfParabola, and SketcherGui::DrawSketchHandlerArcOfHyperbola.
moveConstraint()
void DrawSketchHandler::moveConstraint (int constNum, const Base::Vector2d & toPos) protected
Definition at line 1094 of file DrawSketchHandler.cpp.
References sketchgui.
moveCursorToSketchPoint()
void DrawSketchHandler::moveCursorToSketchPoint (Base::Vector2d point) protected
Definition at line 1052 of file DrawSketchHandler.cpp.
References sketchgui.
onSelectionChanged()
virtual bool SketcherGui::DrawSketchHandler::onSelectionChanged (const Gui::SelectionChanges &) inline virtual
Reimplemented in SketcherGui::DrawSketchHandlerCarbonCopy, and SketcherGui::DrawSketchHandlerExternal.
Definition at line 157 of file DrawSketchHandler.h.
preselectAtPoint()
void DrawSketchHandler::preselectAtPoint (Base::Vector2d point) protected
Definition at line 1062 of file DrawSketchHandler.cpp.
References sketchgui.
pressButton()
virtual bool SketcherGui::DrawSketchHandler::pressButton (Base::Vector2d pos) pure virtual
Implemented in DrawSketchHandlerRectangularArray, DrawSketchHandlerCopy, DrawSketchHandlerGenConstraint, DrawSketchHandlerBSplineInsertKnot, DrawSketchHandlerDimension, SketcherGui::DrawSketchDefaultHandler< HandlerT, SelectModeT, PInitAutoConstraintSize, ConstructionMethodT >, SketcherGui::DrawSketchDefaultHandler< ControllerT::HandlerType, ControllerT::SelectModeType, ControllerT::AutoConstraintInitialSize, ControllerT::ContructionMethodType >, SketcherGui::DrawSketchHandlerLineSet, SketcherGui::DrawSketchHandlerExtend, SketcherGui::DrawSketchHandlerArcOfEllipse, SketcherGui::DrawSketchHandlerArcOfHyperbola, SketcherGui::DrawSketchHandlerArcOfParabola, SketcherGui::DrawSketchHandlerTrimming, SketcherGui::DrawSketchHandlerCarbonCopy, SketcherGui::DrawSketchHandlerExternal, SketcherGui::DrawSketchControllableHandler< ControllerT >, and SketcherGui::DrawSketchHandlerSplitting.
pressRightButton()
void DrawSketchHandler::pressRightButton (Base::Vector2d pos) virtual
Reimplemented in SketcherGui::DrawSketchDefaultHandler< HandlerT, SelectModeT, PInitAutoConstraintSize, ConstructionMethodT >, and SketcherGui::DrawSketchDefaultHandler< ControllerT::HandlerType, ControllerT::SelectModeType, ControllerT::AutoConstraintInitialSize, ControllerT::ContructionMethodType >.
Definition at line 344 of file DrawSketchHandler.cpp.
References quit().
quit()
void DrawSketchHandler::quit () override virtual
Reimplemented from Gui::ToolHandler.
Reimplemented in SketcherGui::DrawSketchHandlerLineSet.
Definition at line 352 of file DrawSketchHandler.cpp.
References SketcherGui::ViewProviderSketch::purgeHandler(), Gui::SelectionSingleton::rmvPreselect(), Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), and sketchgui.
Referenced by pressRightButton(), and registerPressedKey().
registerPressedKey()
void DrawSketchHandler::registerPressedKey (bool pressed, int key) virtual
Reimplemented in DrawSketchHandlerDimension, SketcherGui::DrawSketchDefaultHandler< HandlerT, SelectModeT, PInitAutoConstraintSize, ConstructionMethodT >, SketcherGui::DrawSketchDefaultHandler< ControllerT::HandlerType, ControllerT::SelectModeType, ControllerT::AutoConstraintInitialSize, ControllerT::ContructionMethodType >, and SketcherGui::DrawSketchHandlerLineSet.
Definition at line 335 of file DrawSketchHandler.cpp.
References quit().
releaseButton()
virtual bool SketcherGui::DrawSketchHandler::releaseButton (Base::Vector2d pos) pure virtual
Implemented in SketcherGui::DrawSketchHandlerArcOfHyperbola, SketcherGui::DrawSketchHandlerArcOfParabola, DrawSketchHandlerRectangularArray, DrawSketchHandlerDimension, DrawSketchHandlerCopy, DrawSketchHandlerGenConstraint, DrawSketchHandlerBSplineInsertKnot, SketcherGui::DrawSketchHandlerLineSet, SketcherGui::DrawSketchDefaultHandler< HandlerT, SelectModeT, PInitAutoConstraintSize, ConstructionMethodT >, SketcherGui::DrawSketchDefaultHandler< ControllerT::HandlerType, ControllerT::SelectModeType, ControllerT::AutoConstraintInitialSize, ControllerT::ContructionMethodType >, SketcherGui::DrawSketchHandlerExtend, SketcherGui::DrawSketchHandlerArcOfEllipse, SketcherGui::DrawSketchHandlerTrimming, SketcherGui::DrawSketchHandlerCarbonCopy, SketcherGui::DrawSketchHandlerExternal, SketcherGui::DrawSketchControllableHandler< ControllerT >, and SketcherGui::DrawSketchHandlerSplitting.
renderSuggestConstraintsCursor()
void DrawSketchHandler::renderSuggestConstraintsCursor (std::vector< AutoConstraint > & suggestedConstraints)
Definition at line 914 of file DrawSketchHandler.cpp.
References Gui::ToolHandler::addCursorTail(), and suggestedConstraintsPixmaps().
Referenced by DrawSketchHandlerRectangularArray::mouseMove(), and seekAndRenderAutoConstraint().
resetPositionText()
void DrawSketchHandler::resetPositionText ()
Definition at line 932 of file DrawSketchHandler.cpp.
References sketchgui.
Referenced by deactivate(), SketcherGui::DrawSketchDefaultHandler< ControllerT::HandlerType, ControllerT::SelectModeType, ControllerT::AutoConstraintInitialSize, ControllerT::ContructionMethodType >::pressRightButton(), DrawSketchHandlerCopy::releaseButton(), and DrawSketchHandlerRectangularArray::releaseButton().
seekAndRenderAutoConstraint()
int DrawSketchHandler::seekAndRenderAutoConstraint (std::vector< AutoConstraint > & suggestedConstraints, const Base::Vector2d & Pos, const Base::Vector2d & Dir, AutoConstraint::TargetType type = AutoConstraint::VERTEX)
Definition at line 898 of file DrawSketchHandler.cpp.
References Gui::ToolHandler::applyCursor(), renderSuggestConstraintsCursor(), seekAutoConstraint(), and Path.Post.scripts.grbl_post::type.
Referenced by SketcherGui::DrawSketchHandlerArcOfHyperbola::DrawSketchHandlerArcOfHyperbola(), SketcherGui::DrawSketchHandlerArcOfParabola::DrawSketchHandlerArcOfParabola(), and SketcherGui::DrawSketchHandlerBSpline::DrawSketchHandlerBSpline().
seekAutoConstraint()
int DrawSketchHandler::seekAutoConstraint (std::vector< AutoConstraint > & suggestedConstraints, const Base::Vector2d & Pos, const Base::Vector2d & Dir, AutoConstraint::TargetType type = AutoConstraint::VERTEX)
Definition at line 425 of file DrawSketchHandler.cpp.
References a, KDL::abs(), KDL::atan2(), SketcherGui::ViewProviderSketch::Autoconstraints, SCL.SimpleDataTypes::b, exportCSG::center(), Sketcher::Coincident, SketcherGui::AutoConstraint::CURVE, D_PI, SCL.SimpleDataTypes::e, Path.Log::error(), SCL.SimpleDataTypes::f, Base::fmod(), SketcherGui::AutoConstraint::GeoId, Sketcher::GeoUndef, Sketcher::SketchObject::getCompleteGeometry(), Sketcher::SketchObject::getGeometry(), Sketcher::SketchObject::getGeoVertexIndex(), getHighestCurveIndex(), getPreselectCross(), getPreselectCurve(), getPreselectPoint(), SketcherGui::ViewProviderSketch::getScaleFactor(), SketcherGui::ViewProviderSketch::getSketchObject(), App::PropertyBool::getValue(), Sketcher::HAxis, Sketcher::Horizontal, SplineSurface::i, Base::BaseClass::is(), Base::Vector2d::Length(), Base::Vector3< float_type >::Length(), FreeCADInit::Length, M_PI, M_PI_2, Sketcher::None, Base::Vector3< float_type >::Normalize(), Sketcher::PointOnObject, SketcherGui::AutoConstraint::PosId, Base::Vector3< float_type >::ProjectToLine(), Sketcher::RtPnt, sketchgui, KDL::sqrt(), Sketcher::Symmetric, Sketcher::Tangent, toVector2d(), SketcherGui::AutoConstraint::Type, Path.Post.scripts.grbl_post::type, Sketcher::VAxis, SketcherGui::AutoConstraint::VERTEX, SketcherGui::AutoConstraint::VERTEX_NO_TANGENCY, Sketcher::Vertical, Base::Vector2d::x, Base::Vector3< float_type >::x, Base::Vector2d::y, and Base::Vector3< float_type >::y.
Referenced by DrawSketchHandlerRectangularArray::mouseMove(), and seekAndRenderAutoConstraint().
setAngleSnapping()
void DrawSketchHandler::setAngleSnapping (bool enable, Base::Vector2d referencePoint = Base::Vector2d(0., 0.)) protected
Definition at line 1087 of file DrawSketchHandler.cpp.
References sketchgui.
Referenced by deactivate().
setAxisPickStyle()
void DrawSketchHandler::setAxisPickStyle (bool on) protected
Definition at line 1047 of file DrawSketchHandler.cpp.
References sketchgui.
setPositionText() [1/2]
void DrawSketchHandler::setPositionText (const Base::Vector2d & Pos)
Definition at line 927 of file DrawSketchHandler.cpp.
References sketchgui.
setPositionText() [2/2]
void DrawSketchHandler::setPositionText (const Base::Vector2d & Pos, const SbString & text)
Definition at line 921 of file DrawSketchHandler.cpp.
References sketchgui.
Referenced by drawDirectionAtCursor(), drawDoubleAtCursor(), drawPositionAtCursor(), SketcherGui::DrawSketchHandlerArcOfHyperbola::DrawSketchHandlerArcOfHyperbola(), SketcherGui::DrawSketchHandlerArcOfParabola::DrawSketchHandlerArcOfParabola(), drawWidthHeightAtCursor(), SketcherGui::DrawSketchHandlerArcOfEllipse::mouseMove(), DrawSketchHandlerBSplineInsertKnot::mouseMove(), DrawSketchHandlerCopy::mouseMove(), and DrawSketchHandlerRectangularArray::mouseMove().
signalToolChanged()
void DrawSketchHandler::signalToolChanged () const protected
Definition at line 1099 of file DrawSketchHandler.cpp.
References getToolName(), and sketchgui.
suggestedConstraintsPixmaps()
std::vector< QPixmap > DrawSketchHandler::suggestedConstraintsPixmaps (std::vector< AutoConstraint > & suggestedConstraints) protected
Returns constraints icons scaled to width.
Definition at line 382 of file DrawSketchHandler.cpp.
References Gui::BitmapFactory(), Sketcher::Coincident, Gui::ToolHandler::getViewer(), Sketcher::Horizontal, Gui::BitmapFactoryInst::pixmapFromSvg(), Sketcher::PointOnObject, Sketcher::Symmetric, Sketcher::Tangent, Sketcher::Vertical, and OfflineRenderingUtils::viewer().
Referenced by renderSuggestConstraintsCursor().
toolWidgetChanged()
void DrawSketchHandler::toolWidgetChanged (QWidget * newwidget)
Slot to receive signaling that a widget intended for the tool has changed and is available ant the provided pointer.
Definition at line 362 of file DrawSketchHandler.cpp.
References toolwidget.
Friends And Related Function Documentation
ViewProviderSketch
friend class ViewProviderSketch friend
Definition at line 164 of file DrawSketchHandler.h.
Member Data Documentation
sketchgui
ViewProviderSketch* SketcherGui::DrawSketchHandler::sketchgui protected
Definition at line 282 of file DrawSketchHandler.h.
Referenced by activate(), createAutoConstraints(), SketcherGui::DrawSketchDefaultHandler< ControllerT::HandlerType, ControllerT::SelectModeType, ControllerT::AutoConstraintInitialSize, ControllerT::ContructionMethodType >::createGeneratedAutoConstraints(), deactivate(), drawEdit(), drawEditMarkers(), SketcherGui::DrawSketchHandlerExtend::DrawSketchHandlerExtend(), ensureFocus(), SketcherGui::DrawSketchHandlerTrimming::executeCommands(), getHighestCurveIndex(), getHighestVertexIndex(), getPreselectCross(), getPreselectCurve(), getPreselectPoint(), getSketchObject(), moveConstraint(), moveCursorToSketchPoint(), SketcherGui::DrawSketchDefaultHandler< ControllerT::HandlerType, ControllerT::SelectModeType, ControllerT::AutoConstraintInitialSize, ControllerT::ContructionMethodType >::onModeChanged(), preselectAtPoint(), SketcherGui::DrawSketchHandlerTrimming::pressButton(), quit(), SketcherGui::DrawSketchHandlerExternal::releaseButton(), SketcherGui::DrawSketchHandlerCarbonCopy::releaseButton(), DrawSketchHandlerBSplineInsertKnot::releaseButton(), DrawSketchHandlerCopy::releaseButton(), DrawSketchHandlerRectangularArray::releaseButton(), resetPositionText(), seekAutoConstraint(), setAngleSnapping(), setAxisPickStyle(), setPositionText(), and signalToolChanged().
toolwidget
QWidget* SketcherGui::DrawSketchHandler::toolwidget protected
Definition at line 284 of file DrawSketchHandler.h.
Referenced by SketcherGui::DrawSketchControllableHandler< ControllerT >::getToolName(), and toolWidgetChanged().
The documentation for this class was generated from the following files:
DrawSketchHandler.h
DrawSketchHandler.cpp