FreeCAD: StartMigrator.StartMigrator2024 Class Reference
StartMigrator.StartMigrator2024 Class Reference
Public Member Functions
def __init__ (self)
def run_migration (self)
Public Attributes
completion_indicator
start_prefs
general_prefs
migration_2024_complete
Detailed Description
In April 2024 the old Start workbench was retired, and replaced with the current Start command. This function
cleans up references to the old workbench, migrating the settings where appropriate, and deleting them where they
are no longer relevant. Web was also removed, without replacement.
TODO: Remove the 2024 migration code when enough time has passed that it is no longer useful
Definition at line 37 of file StartMigrator.py.
Constructor & Destructor Documentation
__init__()
def StartMigrator.StartMigrator2024.__init__ (self)
Definition at line 43 of file StartMigrator.py.
Member Function Documentation
run_migration()
def StartMigrator.StartMigrator2024.run_migration (self)
Definition at line 49 of file StartMigrator.py.
References StartMigrator.StartMigrator2024._mark_complete(), StartMigrator.StartMigrator2024._remove_commands(), StartMigrator.StartMigrator2024._remove_deprecated_parameters(), StartMigrator.StartMigrator2024._remove_toolbars(), StartMigrator.StartMigrator2024._remove_wb_references(), StartMigrator.StartMigrator2024._update_startup_flags(), StartMigrator.StartMigrator2024.completion_indicator, StartMigrator.StartMigrator2024.general_prefs, StartMigrator.StartMigrator2024.migration_2024_complete, and StartMigrator.StartMigrator2024.start_prefs.
Member Data Documentation
completion_indicator
StartMigrator.StartMigrator2024.completion_indicator
Definition at line 44 of file StartMigrator.py.
Referenced by StartMigrator.StartMigrator2024.run_migration().
general_prefs
StartMigrator.StartMigrator2024.general_prefs
Definition at line 46 of file StartMigrator.py.
Referenced by StartMigrator.StartMigrator2024.run_migration().
migration_2024_complete
StartMigrator.StartMigrator2024.migration_2024_complete
Definition at line 47 of file StartMigrator.py.
Referenced by StartMigrator.StartMigrator2024.run_migration().
start_prefs
StartMigrator.StartMigrator2024.start_prefs
Definition at line 45 of file StartMigrator.py.
Referenced by StartMigrator.StartMigrator2024.run_migration().
The documentation for this class was generated from the following file:
StartMigrator.py