FreeCAD: Path.Post.scripts.mach3_mach4_post Namespace Reference
Path.Post.scripts.mach3_mach4_post Namespace Reference
Functions
def processArguments (argstring)
def export (objectslist, filename, argstring)
def linenumber ()
def parse (pathobj)
Variables
TOOLTIP
now
parser
prog
add_help
action = "store_true",
help = "don't pop up editor before writing output",
default
TOOLTIP_ARGS
OUTPUT_COMMENTS
OUTPUT_HEADER
OUTPUT_LINE_NUMBERS
SHOW_EDITOR
MODAL
USE_TLO
OUTPUT_DOUBLES
COMMAND_SPACE
LINENR
UNITS
UNIT_SPEED_FORMAT
UNIT_FORMAT
MACHINE_NAME
CORNER_MIN
CORNER_MAX
PRECISION
PREAMBLE
POSTAMBLE
PRE_OPERATION
POST_OPERATION
TOOL_CHANGE
Function Documentation
export()
def Path.Post.scripts.mach3_mach4_post.export (objectslist, filename, argstring)
Definition at line 173 of file mach3_mach4_post.py.
References Path.Post.scripts.mach3_mach4_post.linenumber(), Path.Post.scripts.mach3_mach4_post.parse(), Path.Post.scripts.mach3_mach4_post.processArguments(), and Path.Post.scripts.refactored_centroid_post.str.
linenumber()
def Path.Post.scripts.mach3_mach4_post.linenumber ()
Definition at line 282 of file mach3_mach4_post.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.mach3_mach4_post.export(), and Path.Post.scripts.mach3_mach4_post.parse().
parse()
def Path.Post.scripts.mach3_mach4_post.parse (pathobj)
Definition at line 290 of file mach3_mach4_post.py.
References Path.Post.scripts.mach3_mach4_post.linenumber(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.mach3_mach4_post.export().
processArguments()
def Path.Post.scripts.mach3_mach4_post.processArguments (argstring)
Definition at line 123 of file mach3_mach4_post.py.
Referenced by Path.Post.scripts.mach3_mach4_post.export().
Variable Documentation
action
string Path.Post.scripts.mach3_mach4_post.action = "store_true",
Definition at line 48 of file mach3_mach4_post.py.
add_help
Path.Post.scripts.mach3_mach4_post.add_help
Definition at line 47 of file mach3_mach4_post.py.
COMMAND_SPACE
Path.Post.scripts.mach3_mach4_post.COMMAND_SPACE
Definition at line 90 of file mach3_mach4_post.py.
CORNER_MAX
Path.Post.scripts.mach3_mach4_post.CORNER_MAX
Definition at line 100 of file mach3_mach4_post.py.
CORNER_MIN
Path.Post.scripts.mach3_mach4_post.CORNER_MIN
Definition at line 99 of file mach3_mach4_post.py.
default
Path.Post.scripts.mach3_mach4_post.default
Definition at line 56 of file mach3_mach4_post.py.
help
string Path.Post.scripts.mach3_mach4_post.help = "don't pop up editor before writing output",
Definition at line 48 of file mach3_mach4_post.py.
LINENR
Path.Post.scripts.mach3_mach4_post.LINENR
Definition at line 91 of file mach3_mach4_post.py.
MACHINE_NAME
Path.Post.scripts.mach3_mach4_post.MACHINE_NAME
Definition at line 98 of file mach3_mach4_post.py.
MODAL
Path.Post.scripts.mach3_mach4_post.MODAL
Definition at line 87 of file mach3_mach4_post.py.
now
Path.Post.scripts.mach3_mach4_post.now
Definition at line 45 of file mach3_mach4_post.py.
OUTPUT_COMMENTS
Path.Post.scripts.mach3_mach4_post.OUTPUT_COMMENTS
Definition at line 83 of file mach3_mach4_post.py.
OUTPUT_DOUBLES
Path.Post.scripts.mach3_mach4_post.OUTPUT_DOUBLES
Definition at line 89 of file mach3_mach4_post.py.
OUTPUT_HEADER
Path.Post.scripts.mach3_mach4_post.OUTPUT_HEADER
Definition at line 84 of file mach3_mach4_post.py.
OUTPUT_LINE_NUMBERS
Path.Post.scripts.mach3_mach4_post.OUTPUT_LINE_NUMBERS
Definition at line 85 of file mach3_mach4_post.py.
parser
Path.Post.scripts.mach3_mach4_post.parser
Definition at line 47 of file mach3_mach4_post.py.
POST_OPERATION
Path.Post.scripts.mach3_mach4_post.POST_OPERATION
Definition at line 117 of file mach3_mach4_post.py.
POSTAMBLE
Path.Post.scripts.mach3_mach4_post.POSTAMBLE
Definition at line 108 of file mach3_mach4_post.py.
PRE_OPERATION
Path.Post.scripts.mach3_mach4_post.PRE_OPERATION
Definition at line 114 of file mach3_mach4_post.py.
PREAMBLE
Path.Post.scripts.mach3_mach4_post.PREAMBLE
Definition at line 104 of file mach3_mach4_post.py.
PRECISION
Path.Post.scripts.mach3_mach4_post.PRECISION
Definition at line 101 of file mach3_mach4_post.py.
prog
Path.Post.scripts.mach3_mach4_post.prog
Definition at line 47 of file mach3_mach4_post.py.
SHOW_EDITOR
Path.Post.scripts.mach3_mach4_post.SHOW_EDITOR
Definition at line 86 of file mach3_mach4_post.py.
TOOL_CHANGE
Path.Post.scripts.mach3_mach4_post.TOOL_CHANGE
Definition at line 120 of file mach3_mach4_post.py.
TOOLTIP
Path.Post.scripts.mach3_mach4_post.TOOLTIP
Definition at line 34 of file mach3_mach4_post.py.
TOOLTIP_ARGS
Path.Post.scripts.mach3_mach4_post.TOOLTIP_ARGS
Definition at line 80 of file mach3_mach4_post.py.
UNIT_FORMAT
Path.Post.scripts.mach3_mach4_post.UNIT_FORMAT
Definition at line 96 of file mach3_mach4_post.py.
UNIT_SPEED_FORMAT
Path.Post.scripts.mach3_mach4_post.UNIT_SPEED_FORMAT
Definition at line 95 of file mach3_mach4_post.py.
UNITS
Path.Post.scripts.mach3_mach4_post.UNITS
Definition at line 94 of file mach3_mach4_post.py.
USE_TLO
Path.Post.scripts.mach3_mach4_post.USE_TLO
Definition at line 88 of file mach3_mach4_post.py.