FreeCAD: materialtools.cardutils Namespace Reference
materialtools.cardutils Namespace Reference
Functions
def get_material_preferred_directory (category=None)
def get_material_preferred_save_directory ()
def get_material_resources (category='Solid')
def get_material_libraries ()
def list_cards (mat_dir, icon)
def output_resources (resources)
def import_materials (category='Solid', template=False)
def add_cards_from_a_dir (materials, cards, icons, mat_dir, icon, template=False)
def output_trio (trio)
def output_cards (cards)
def output_icons (icons)
def output_materials (materials)
def output_material_param (mat_dict)
def get_material_template (withSpaces=False)
def create_mat_tools_header ()
def create_mat_template_card (write_group_section=True)
def get_source_path ()
def get_known_material_quantity_parameter ()
def get_and_output_all_carddata (cards)
def read_cards_from_path (cards_path)
def write_cards_to_path (cards_path, cards_data, write_group_section=True, write_template=False)
def check_parm_unit (param)
def check_value_unit (param, value)
def output_parm_unit_info (param)
def output_value_unit_info (param, value)
def check_mat_units (mat)
Variables
unicode = str
Function Documentation
add_cards_from_a_dir()
def materialtools.cardutils.add_cards_from_a_dir (materials, cards, icons, mat_dir, icon, template = False)
Definition at line 281 of file cardutils.py.
References importers.import3DS.read().
check_mat_units()
def materialtools.cardutils.check_mat_units (mat)
Definition at line 761 of file cardutils.py.
References materialtools.cardutils.check_value_unit(), and materialtools.cardutils.get_known_material_quantity_parameter().
check_parm_unit()
def materialtools.cardutils.check_parm_unit (param)
Definition at line 587 of file cardutils.py.
check_value_unit()
def materialtools.cardutils.check_value_unit (param, value)
Definition at line 600 of file cardutils.py.
Referenced by materialtools.cardutils.check_mat_units().
create_mat_template_card()
def materialtools.cardutils.create_mat_template_card (write_group_section = True)
Definition at line 413 of file cardutils.py.
References materialtools.cardutils.get_material_template(), materialtools.cardutils.get_source_path(), and AssemblyImport.open().
create_mat_tools_header()
def materialtools.cardutils.create_mat_tools_header ()
Definition at line 393 of file cardutils.py.
References materialtools.cardutils.get_material_template(), materialtools.cardutils.get_source_path(), and AssemblyImport.open().
get_and_output_all_carddata()
def materialtools.cardutils.get_and_output_all_carddata (cards)
Definition at line 493 of file cardutils.py.
References materialtools.cardutils.get_material_template(), and importers.import3DS.read().
get_known_material_quantity_parameter()
def materialtools.cardutils.get_known_material_quantity_parameter ()
Definition at line 478 of file cardutils.py.
References materialtools.cardutils.get_material_template().
Referenced by materialtools.cardutils.check_mat_units().
get_material_libraries()
def materialtools.cardutils.get_material_libraries ()
Definition at line 196 of file cardutils.py.
get_material_preferred_directory()
def materialtools.cardutils.get_material_preferred_directory (category = None)
    Return the preferred material directory. In priority order they are:
    1. user specified
    2. user modules folder
    3. system folder
Definition at line 61 of file cardutils.py.
get_material_preferred_save_directory()
def materialtools.cardutils.get_material_preferred_save_directory ()
    Return the preferred directory for saving materials. In priority order they are:
    1. user specified
    2. user modules folder
Definition at line 105 of file cardutils.py.
get_material_resources()
def materialtools.cardutils.get_material_resources (category = 'Solid')
Definition at line 144 of file cardutils.py.
get_material_template()
def materialtools.cardutils.get_material_template (withSpaces = False)
Definition at line 359 of file cardutils.py.
References AssemblyImport.open().
Referenced by materialtools.cardutils.create_mat_template_card(), materialtools.cardutils.create_mat_tools_header(), materialtools.cardutils.get_and_output_all_carddata(), materialtools.cardutils.get_known_material_quantity_parameter(), MaterialEditor.MaterialEditor.implementModel(), and importFCMat.write().
get_source_path()
def materialtools.cardutils.get_source_path ()
Definition at line 462 of file cardutils.py.
References AssemblyImport.open().
Referenced by materialtools.cardutils.create_mat_template_card(), and materialtools.cardutils.create_mat_tools_header().
import_materials()
def materialtools.cardutils.import_materials (category = 'Solid', template = False)
Definition at line 262 of file cardutils.py.
list_cards()
def materialtools.cardutils.list_cards (mat_dir, icon)
Definition at line 238 of file cardutils.py.
output_cards()
def materialtools.cardutils.output_cards (cards)
Definition at line 326 of file cardutils.py.
output_icons()
def materialtools.cardutils.output_icons (icons)
Definition at line 333 of file cardutils.py.
output_material_param()
def materialtools.cardutils.output_material_param (mat_dict)
Definition at line 348 of file cardutils.py.
Referenced by materialtools.cardutils.output_materials().
output_materials()
def materialtools.cardutils.output_materials (materials)
Definition at line 340 of file cardutils.py.
References materialtools.cardutils.output_material_param().
output_parm_unit_info()
def materialtools.cardutils.output_parm_unit_info (param)
Definition at line 658 of file cardutils.py.
output_resources()
def materialtools.cardutils.output_resources (resources)
Definition at line 253 of file cardutils.py.
output_trio()
def materialtools.cardutils.output_trio (trio)
Definition at line 315 of file cardutils.py.
output_value_unit_info()
def materialtools.cardutils.output_value_unit_info (param, value)
Definition at line 694 of file cardutils.py.
read_cards_from_path()
def materialtools.cardutils.read_cards_from_path (cards_path)
Definition at line 557 of file cardutils.py.
References importers.import3DS.read().
write_cards_to_path()
def materialtools.cardutils.write_cards_to_path (cards_path, cards_data, write_group_section = True, write_template = False)
Definition at line 571 of file cardutils.py.
References feminout.exportNastranMesh.write().
Variable Documentation
unicode
materialtools.cardutils.unicode = str
Definition at line 34 of file cardutils.py.