FreeCAD: Part Namespace Reference
Part Namespace Reference
Namespaces
IGES
OCAF
STEP
Classes
class AttachEngineException
class AttachExtension
The AttachableObject class is the thing to extend an object with that should be attachable. It includes the required properties, and shortcuts for accessing the attachment math class.
class BodyBase
class Boolean
class BooleanException
class Box
class BRepBuilderAPI_RefineModel
class BRepFeatModule
class BRepMesh
class BRepOffsetAPI_MakeOffsetFix
The BRepOffsetAPI_MakeOffsetFix class This class works around a limitation of the BRepOffsetAPI_MakeOffset which returns unexpected results when an input wire has set a placement and consists of a single edge only.
class BRepOffsetAPIModule
class BSplineCurveBiArcs
class CallbackRegistrationRecord
class Chamfer
class ChFi2dModule
class Circle
class Common
class Compound
class Compound2
Same as Part::Compound, except it marks the Shape as transient, and rebuild it during restore.
class Cone
class CrossSection
class CurveNet
class CustomFeature
class Cut
struct cutFaces
struct cutTopoShapeFaces
class Cylinder
class Datum
class DatumLine
class DatumPlane
class DatumPoint
class Edgecluster
struct Edgesort_gp_Pnt_Less
class Ellipse
class Ellipsoid
class Extrusion
class ExtrusionHelper
struct ExtrusionParameters
The ExtrusionParameters struct is supposed to be filled with final extrusion parameters, after resolving links, applying mode logic, reversing, etc., and be passed to extrudeShape.
class Face
class FaceMaker
FaceMaker class is the base class for implementing various "smart" face making routines. This was created to address the problem of multiple private implementations of making faces with holes, which are quite complex. The two most important facemaking routines then was: one in Part Extrude, and one in PartDesign (there, it is used in every sketch-based feature). Plus, another one (new) was needed for filling 2D offset.
class FaceMakerBullseye
The FaceMakerBullseye class is a tool to make planar faces with holes, where there can be additional faces inside holes and they can have holes too and so on.
class FaceMakerCheese
The FaceMakerCheese class is a legacy face maker that was extracted from Part Extrude. It is used by almost all PartDesign.
class FaceMakerExtrusion
FaceMakerExtrusion provides legacy compounding-structure-ignorant behavior of facemaker of Part Extrude. Strengths: makes faces with holes Weaknesses: can't make islands in holes. Ignores compounding nesting. All faces must be on same plane.
class FaceMakerPublic
The FaceMakerPublic class: derive from it if you want the face maker to be listed in tools that allow choosing one.
class FaceMakerSimple
The FaceMakerSimple class: make plane faces from all closed wires supplied, ignoring overlaps.
class Feature
class FeatureExt
class FeatureGeometrySet
class FeatureReference
class Fillet
class FilletBase
struct FilletElement
class Fuse
class FuzzyHelper
The FuzzyHelper class provides a static helper function to determine fuzzy value for a boolean operation.
struct GenericShapeMapper
class Geom2dArcOfCircle
class Geom2dArcOfConic
class Geom2dArcOfEllipse
class Geom2dArcOfHyperbola
class Geom2dArcOfParabola
class Geom2dBezierCurve
class Geom2dBSplineCurve
class Geom2dCircle
class Geom2dConic
class Geom2dCurve
class Geom2dEllipse
class Geom2dHyperbola
class Geom2dLine
class Geom2dLineSegment
class Geom2dModule
class Geom2dOffsetCurve
class Geom2dParabola
class Geom2dPoint
class Geom2dTrimmedCurve
class GeomArcOfCircle
class GeomArcOfConic
class GeomArcOfEllipse
class GeomArcOfHyperbola
class GeomArcOfParabola
class GeomBezierCurve
class GeomBezierSurface
class GeomBoundedCurve
class GeomBSplineCurve
class GeomBSplineSurface
class GeomCircle
class GeomCone
class GeomConic
class GeomCurve
class GeomCylinder
class GeomElementarySurface
class GeomEllipse
class Geometry
class Geometry2d
class GeometryDefaultExtension
class GeometryExtension
class GeometryMigrationExtension
class GeometryMigrationPersistenceExtension
class GeometryPersistenceExtension
class GeomHyperbola
class GeomLine
class GeomLineSegment
class GeomOffsetCurve
class GeomOffsetSurface
class GeomParabola
class GeomPlane
class GeomPlateModule
class GeomPlateSurface
class GeomPoint
class GeomSphere
class GeomSurface
class GeomSurfaceOfExtrusion
class GeomSurfaceOfRevolution
class GeomSweptSurface
class GeomToroid
class GeomTrimmedCurve
class GeomTrimmedSurface
class Helix
class HLRBRepModule
class ImportBrep
class ImportIges
class ImportStep
class Interface
class Line
class LocalCoordinateSystem
class Loft
struct MapperHistory
struct MapperMaker
struct MapperSewing
class MeasureAngleInfo
class MeasureAreaInfo
class MeasureClient
class MeasureDistanceInfo
class MeasureInfo
class MeasureLengthInfo
class MeasurePositionInfo
class MeasureRadiusInfo
class Mirroring
class Module
class MultiCommon
class MultiFuse
class NullShapeException
class Offset
class Offset2D
class OpCodes
class Part2DObject
class Plane
class Polygon
class Primitive
class Prism
class PrismExtension
class ProgressIndicator
class ProjectOnSurface
class PropertyFilletEdges
class PropertyGeometryList
class PropertyPartShape
class PropertyShapeCache
class PropertyShapeHistory
class PropertyTopoShapeList
class Refine
class RegularPolygon
class Reverse
class Revolution
class RuledSurface
class Scale
class Section
class ShapeFixModule
struct ShapeHasher
Shape hasher that ignore orientation.
struct ShapeHistory
class ShapeMapHasher
struct ShapeMapper
struct ShapeRelationKey
class ShapeSegment
class ShapeUpgradeModule
class Sphere
class Spiral
class Spline
class Sweep
class TangentialArc
class Thickness
class Tools
class TopoCrossSection
struct TopoShape
Parameters for TopoShape::makeElementFilledFace()
class TopoShapeCache
class Torus
class VectorAdapter
Convert to vector.
class Vertex
class Wedge
class WireJoiner
Typedefs
using AttachExtensionPython = App::ExtensionPythonT< AttachExtension >
using CustomFeaturePython = App::FeaturePythonT< CustomFeature >
using tEdgeVector = std::vector< TopoDS_Edge >
using tMapPntEdge = std::map< gp_Pnt, tEdgeVector, Edgesort_gp_Pnt_Less >
using tMapPntEdgePair = std::pair< gp_Pnt, tEdgeVector >
using tEdgeClusterVector = std::vector< std::vector< TopoDS_Edge > >
using GeometryIntExtension = GeometryDefaultExtension< long >
using GeometryStringExtension = GeometryDefaultExtension< std::string >
using GeometryBoolExtension = GeometryDefaultExtension< bool >
using GeometryDoubleExtension = GeometryDefaultExtension< double >
using MeasureInfoPtr = std::shared_ptr< MeasureInfo >
using MeasureAngleInfoPtr = std::shared_ptr< MeasureAngleInfo >
using MeasureAreaInfoPtr = std::shared_ptr< MeasureAreaInfo >
using MeasureDistanceInfoPtr = std::shared_ptr< MeasureDistanceInfo >
using MeasureLengthInfoPtr = std::shared_ptr< MeasureLengthInfo >
using MeasurePositionInfoPtr = std::shared_ptr< MeasurePositionInfo >
using MeasureRadiusInfoPtr = std::shared_ptr< MeasureRadiusInfo >
using GeometryHandler = std::function< Part::MeasureInfoPtr(App::SubObjectT)>
callback registrations
using CallbackRegistrationList = std::vector< CallbackRegistrationRecord >
using Part2DObjectPython = App::FeaturePythonT< Part2DObject >
using FeaturePython = App::FeaturePythonT< Feature >
using TopoShapeMap = std::unordered_map< TopoShape, TopoShape, ShapeHasher, ShapeHasher >
Enumerations
enum KeepTag { NewTag, CopyTag }
enum HistoryTraceType { HistoryTraceType::stopOnTypeChange, HistoryTraceType::followTypeChange }
enum RefineFail { RefineFail::shapeUntouched, RefineFail::throwException }
enum CheckGeometry { CheckGeometry::ignoreGeometry, CheckGeometry::checkGeometry }
Behavior of findSubShapesWithSharedVertex.
enum LinearizeFace { LinearizeFace::noFaces, LinearizeFace::linearizeFaces }
enum LinearizeEdge { LinearizeEdge::noEdges, LinearizeEdge::linearizeEdges }
enum IsSolid { IsSolid::notSolid, IsSolid::solid }
enum IsRuled { IsRuled::notRuled, IsRuled::ruled }
enum IsClosed { IsClosed::notClosed, IsClosed::closed }
enum TransitionMode { TransitionMode::Transformed, TransitionMode::RightCorner, TransitionMode::RoundCorner }
Option to manage discontinuity in pipe sweeping.
enum MakeSolid { MakeSolid::noSolid, MakeSolid::makeSolid }
enum MapElement { MapElement::noMap, MapElement::map }
enum JoinType { JoinType::arc, JoinType::tangent, JoinType::intersection }
Defines how to fill the holes that may appear after offset two adjacent faces.
enum Flip { Flip::none, Flip::flip }
enum ChamferType { ChamferType::equalDistance, ChamferType::twoDistances, ChamferType::distanceAngle }
enum CheckScale { CheckScale::noScaleCheck, CheckScale::checkScale }
enum CopyType { CopyType::noCopy, CopyType::copy }
enum FillingStyle { stretch, coons, curved }
Filling style when making a BSpline face.
enum CoordinateSystem { CoordinateSystem::relativeToSpine, CoordinateSystem::global }
enum Spine { Spine::notOn, Spine::on }
enum FillType { FillType::noFill, FillType::fill }
enum OpenResult { OpenResult::noOpenResult, OpenResult::allowOpenResult }
enum RevolMode { RevolMode::CutFromBase = 0, RevolMode::FuseWithBase = 1, RevolMode::None = 2 }
enum MappingStatus { MappingStatus::Generated, MappingStatus::Modified }
Functions
PyObject * initModule ()
PartExport void getPyShapes (PyObject *obj, std::vector< TopoShape > &shapes)
PartExport std::vector< TopoShape > getPyShapes (PyObject *obj)
PartExport std::list< TopoDS_Edge > sort_Edges (double tol3d, std::list< TopoDS_Edge > &edges)
bool tangentialArc (const gp_Pnt &p0, const gp_Vec &v0, const gp_Pnt &p1, gp_Pnt &c, gp_Dir &axis)
std::string encodeFilename (std::string fn)
void throwIfInvalidIfCheckModel (const TopoDS_Shape &shape)
bool getRefineModelParameter ()
const Py::Object makeGeometryCurvePy (const Handle(Geom_Curve)&c)
Py::Object shape2pyshape (const TopoDS_Shape &shape)
void create3dCurve (const TopoDS_Edge &edge)
bool find2DLinesIntersection (const Base::Vector3d &orig1, const Base::Vector3d &dir1, const Base::Vector3d &orig2, const Base::Vector3d &dir2, Base::Vector3d &point)
bool find2DLinesIntersection (const GeomLineSegment *lineSeg1, const GeomLineSegment *lineSeg2, Base::Vector3d &point)
bool findFilletCenter (const GeomLineSegment *lineSeg1, const GeomLineSegment *lineSeg2, double radius, Base::Vector3d &center)
bool findFilletCenter (const GeomLineSegment *lineSeg1, const GeomLineSegment *lineSeg2, double radius, const Base::Vector3d &refPnt1, const Base::Vector3d &refPnt2, Base::Vector3d &center)
double suggestFilletRadius (const GeomLineSegment *lineSeg1, const GeomLineSegment *lineSeg2, const Base::Vector3d &refPnt1, const Base::Vector3d &refPnt2)
GeomArcOfCircle * createFilletGeometry (const GeomLineSegment *lineSeg1, const GeomLineSegment *lineSeg2, const Base::Vector3d &center, double radius)
std::unique_ptr< GeomSurface > makeFromSurface (const Handle(Geom_Surface)&s, bool silent)
std::unique_ptr< GeomSurface > makeFromSurfaceAdaptor (const BRepAdaptor_Surface &adapt, bool silent)
std::unique_ptr< GeomCurve > makeFromCurve (const Handle(Geom_Curve)&c, bool silent)
std::unique_ptr< GeomCurve > makeFromTrimmedCurve (const Handle(Geom_Curve)&c, double f, double l, bool silent)
std::unique_ptr< GeomCurve > makeFromCurveAdaptor (const Adaptor3d_Curve &adapt, bool silent)
std::unique_ptr< Geom2dCurve > makeFromCurve2d (Handle(Geom2d_Curve) curve)
std::unique_ptr< Geom2dCurve > makeFromTrimmedCurve2d (const Handle(Geom2d_Curve)&c, double f, double l)
std::unique_ptr< Geom2dCurve > makeFromCurveAdaptor2d (const Adaptor2d_Curve2d &adapt)
const Py::Object makeTrimmedCurvePy (const Handle(Geom_Curve)&c, double f, double l)
PartExport int ImportIgesParts (App::Document *pcDoc, const char *Name)
bool ReadColors (const Handle(XSControl_WorkSession) &WS, std::map< int, Quantity_Color > &hash_col)
bool ReadNames (const Handle(XSControl_WorkSession) &WS)
PartExport int ImportStepParts (App::Document *pcDoc, const char *Name)
std::list< std::string > supportedSTEPSchemes ()
PartExport std::vector< cutFaces > findAllFacesCutBy (const TopoDS_Shape &shape, const TopoDS_Shape &face, const gp_Dir &dir)
PartExport std::vector< cutTopoShapeFaces > findAllFacesCutBy (const TopoShape &shape, const TopoShape &face, const gp_Dir &dir)
PartExport bool checkIntersection (const TopoDS_Shape &first, const TopoDS_Shape &second, const bool quick, const bool touch_is_intersection)
PartExport Py::Object shape2pyshape (const TopoShape &shape)
PartExport void closestPointsOnLines (const gp_Lin &lin1, const gp_Lin &lin2, gp_Pnt &p1, gp_Pnt &p2)
PartExport bool intersect (const gp_Pln &pln1, const gp_Pln &pln2, gp_Lin &lin)
std::vector< std::string > buildShapeEnumVector ()
std::vector< std::string > buildBOPCheckResultVector ()
static const std::map< PyTypeObject *, TopAbs_ShapeEnum > mapTypeShape (vecTypeShape.begin(), vecTypeShape.end())
static TopAbs_ShapeEnum ShapeTypeFromPyType (PyTypeObject *pyType)
Variables
PartExport PyObject * PartExceptionOCCError
PartExport PyObject * PartExceptionOCCDomainError
PartExport PyObject * PartExceptionOCCRangeError
PartExport PyObject * PartExceptionOCCConstructionError
PartExport PyObject * PartExceptionOCCDimensionError
const App::PropertyQuantityConstraint::Constraints apexRange = {-89.9, 89.9, 0.1}
const App::PropertyQuantityConstraint::Constraints torusRangeV = {-180.0, 180.0, 1.0}
const App::PropertyQuantityConstraint::Constraints angleRangeU = {0.0, 360.0, 1.0}
const App::PropertyQuantityConstraint::Constraints angleRangeV = {-90.0, 90.0, 1.0}
const App::PropertyQuantityConstraint::Constraints quantityRange = {0.0, FLT_MAX, 0.1}
static const std::vector< std::pair< PyTypeObject *, TopAbs_ShapeEnum > > vecTypeShape
Detailed Description
AttachExtensionh, .cpp contain a extension class to derive other features from, to make them attachable.
MeasureInfo.h ancestor class and the various flavours of MeasureXXXXXInfo.
Definition of commonly used TopoShape operational code
The operational code (op code) is encoded into the mapped element name to provide more context and meaning to the shape history when tracing it back to its predecessors. Some op codes can be passed to the generalized shape- making API TopoShape::makEBoolean() to make a shape.
Typedef Documentation
AttachExtensionPython
using Part::AttachExtensionPython = typedef App::ExtensionPythonT<AttachExtension>
Definition at line 185 of file AttachExtension.h.
CallbackRegistrationList
using Part::CallbackRegistrationList = typedef std::vector<CallbackRegistrationRecord>
Definition at line 174 of file MeasureInfo.h.
CustomFeaturePython
using Part::CustomFeaturePython = typedef App::FeaturePythonT<CustomFeature>
Definition at line 77 of file CustomFeature.h.
FeaturePython
using Part::FeaturePython = typedef App::FeaturePythonT<Feature>
Definition at line 225 of file PartFeature.h.
GeometryBoolExtension
using Part::GeometryBoolExtension = typedef GeometryDefaultExtension<bool>
Definition at line 132 of file GeometryDefaultExtension.h.
GeometryDoubleExtension
using Part::GeometryDoubleExtension = typedef GeometryDefaultExtension<double>
Definition at line 133 of file GeometryDefaultExtension.h.
GeometryHandler
using Part::GeometryHandler = typedef std::function<Part::MeasureInfoPtr (App::SubObjectT)>
callback registrations
Definition at line 159 of file MeasureInfo.h.
GeometryIntExtension
using Part::GeometryIntExtension = typedef GeometryDefaultExtension<long>
Definition at line 130 of file GeometryDefaultExtension.h.
GeometryStringExtension
using Part::GeometryStringExtension = typedef GeometryDefaultExtension<std::string>
Definition at line 131 of file GeometryDefaultExtension.h.
MeasureAngleInfoPtr
using Part::MeasureAngleInfoPtr = typedef std::shared_ptr<MeasureAngleInfo>
Definition at line 66 of file MeasureInfo.h.
MeasureAreaInfoPtr
using Part::MeasureAreaInfoPtr = typedef std::shared_ptr<MeasureAreaInfo>
Definition at line 68 of file MeasureInfo.h.
MeasureDistanceInfoPtr
using Part::MeasureDistanceInfoPtr = typedef std::shared_ptr<MeasureDistanceInfo>
Definition at line 70 of file MeasureInfo.h.
MeasureInfoPtr
using Part::MeasureInfoPtr = typedef std::shared_ptr<MeasureInfo>
Definition at line 64 of file MeasureInfo.h.
MeasureLengthInfoPtr
using Part::MeasureLengthInfoPtr = typedef std::shared_ptr<MeasureLengthInfo>
Definition at line 72 of file MeasureInfo.h.
MeasurePositionInfoPtr
using Part::MeasurePositionInfoPtr = typedef std::shared_ptr<MeasurePositionInfo>
Definition at line 74 of file MeasureInfo.h.
MeasureRadiusInfoPtr
using Part::MeasureRadiusInfoPtr = typedef std::shared_ptr<MeasureRadiusInfo>
Definition at line 76 of file MeasureInfo.h.
Part2DObjectPython
using Part::Part2DObjectPython = typedef App::FeaturePythonT<Part2DObject>
Definition at line 99 of file Part2DObject.h.
tEdgeClusterVector
using Part::tEdgeClusterVector = typedef std::vector<std::vector<TopoDS_Edge> >
Definition at line 78 of file edgecluster.h.
tEdgeVector
using Part::tEdgeVector = typedef std::vector<TopoDS_Edge>
Definition at line 75 of file edgecluster.h.
tMapPntEdge
using Part::tMapPntEdge = typedef std::map<gp_Pnt,tEdgeVector,Edgesort_gp_Pnt_Less>
Definition at line 76 of file edgecluster.h.
tMapPntEdgePair
using Part::tMapPntEdgePair = typedef std::pair<gp_Pnt,tEdgeVector>
Definition at line 77 of file edgecluster.h.
TopoShapeMap
using Part::TopoShapeMap = typedef std::unordered_map<TopoShape, TopoShape, ShapeHasher, ShapeHasher>
Definition at line 63 of file TopoShape.h.
Enumeration Type Documentation
ChamferType
enum Part::ChamferType strong
Enumerator
equalDistance
twoDistances
distanceAngle
Definition at line 212 of file TopoShape.h.
CheckGeometry
enum Part::CheckGeometry strong
Behavior of findSubShapesWithSharedVertex.
Enumerator
ignoreGeometry
checkGeometry
Definition at line 126 of file TopoShape.h.
CheckScale
enum Part::CheckScale strong
Enumerator
noScaleCheck
checkScale
Definition at line 219 of file TopoShape.h.
CoordinateSystem
enum Part::CoordinateSystem strong
Enumerator
relativeToSpine
global
Definition at line 242 of file TopoShape.h.
CopyType
enum Part::CopyType strong
Enumerator
noCopy
copy
Definition at line 225 of file TopoShape.h.
FillingStyle
enum Part::FillingStyle
Filling style when making a BSpline face.
Enumerator
stretch
The style with the flattest patches.
coons
A rounded style of patch with less depth than those of Curved.
curved
The style with the most rounded patches.
Definition at line 232 of file TopoShape.h.
FillType
enum Part::FillType strong
Enumerator
noFill
fill
Definition at line 254 of file TopoShape.h.
Flip
enum Part::Flip strong
Enumerator
none
flip
Definition at line 206 of file TopoShape.h.
HistoryTraceType
enum Part::HistoryTraceType strong
When tracing an element's history, one can either stop the trace when the element's type changes, or continue tracing the history through the change. This enumeration replaces a boolean parameter in the original Toponaming branch by realthunder.
Enumerator
stopOnTypeChange
followTypeChange
Definition at line 111 of file TopoShape.h.
IsClosed
enum Part::IsClosed strong
Enumerator
notClosed
closed
Definition at line 156 of file TopoShape.h.
IsRuled
enum Part::IsRuled strong
Enumerator
notRuled
ruled
Definition at line 150 of file TopoShape.h.
IsSolid
enum Part::IsSolid strong
Enumerator
notSolid
solid
Definition at line 144 of file TopoShape.h.
JoinType
enum Part::JoinType strong
Defines how to fill the holes that may appear after offset two adjacent faces.
Enumerator
arc
tangent
intersection
Definition at line 199 of file TopoShape.h.
KeepTag
enum Part::KeepTag
Enumerator
NewTag
CopyTag
Definition at line 97 of file Part/App/Geometry.h.
LinearizeEdge
enum Part::LinearizeEdge strong
Enumerator
noEdges
linearizeEdges
Definition at line 138 of file TopoShape.h.
LinearizeFace
enum Part::LinearizeFace strong
Enumerator
noFaces
linearizeFaces
Definition at line 132 of file TopoShape.h.
MakeSolid
enum Part::MakeSolid strong
Enumerator
noSolid
makeSolid
Definition at line 186 of file TopoShape.h.
MapElement
enum Part::MapElement strong
Enumerator
noMap
map
Definition at line 192 of file TopoShape.h.
MappingStatus
enum Part::MappingStatus strong
Enumerator
Generated
Modified
Definition at line 110 of file TopoShapeMapper.h.
OpenResult
enum Part::OpenResult strong
Enumerator
noOpenResult
allowOpenResult
Definition at line 260 of file TopoShape.h.
RefineFail
enum Part::RefineFail strong
Behavior of refines when a problem arises; either leave the shape untouched or throw an exception. This replaces a boolean parameter in the original Toponaming branch by realthunder..
Enumerator
shapeUntouched
throwException
Definition at line 119 of file TopoShape.h.
RevolMode
enum Part::RevolMode strong
Enumerator
CutFromBase
FuseWithBase
None
Definition at line 267 of file TopoShape.h.
Spine
enum Part::Spine strong
Enumerator
notOn
on
Definition at line 248 of file TopoShape.h.
TransitionMode
enum Part::TransitionMode strong
Option to manage discontinuity in pipe sweeping.
Enumerator
Transformed
Discontinuities are treated by modification of the sweeping mode. The pipe is "transformed" at the fractures of the spine. This mode assumes building a self-intersected shell.
RightCorner
Discontinuities are treated like right corner. Two pieces of the pipe corresponding to two adjacent segments of the spine are extended and intersected at a fracture of the spine.
RoundCorner
Discontinuities are treated like round corner. The corner is treated as rotation of the profile around an axis which passes through the point of the spine's fracture. This axis is based on cross product of directions tangent to the adjacent segments of the spine at their common point.
Definition at line 163 of file TopoShape.h.
Function Documentation
buildBOPCheckResultVector()
std::vector<std::string> Part::buildBOPCheckResultVector ()
Definition at line 1408 of file TopoShape.cpp.
Referenced by Part::TopoShape::analyze().
buildShapeEnumVector()
std::vector<std::string> Part::buildShapeEnumVector ()
Definition at line 1393 of file TopoShape.cpp.
References femtools.tokrules::names.
Referenced by Part::TopoShape::analyze().
checkIntersection()
bool Part::checkIntersection (const TopoDS_Shape & first, const TopoDS_Shape & second, const bool quick, const bool touch_is_intersection)
Check for intersection between the two shapes. Only solids are guaranteed to work properly There are two modes:
Bounding box check only - quick but inaccurate
Bounding box check plus (if necessary) boolean operation - costly but accurate Return true if the shapes intersect, false if they don't The flag touch_is_intersection decides whether shapes touching at distance zero are regarded as intersecting or not
If set to true, a true check result means that a boolean fuse operation between the two shapes will return a single solid
If set to false, a true check result means that a boolean common operation will return a valid solid If there is any error in the boolean operations, the check always returns false
Definition at line 1934 of file PartFeature.cpp.
References KDL::Add().
closestPointsOnLines()
void Part::closestPointsOnLines (const gp_Lin & lin1, const gp_Lin & lin2, gp_Pnt & p1, gp_Pnt & p2)
Definition at line 75 of file Mod/Part/App/Tools.cpp.
References a, SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::c, Path.Dressup.Gui.Dragknife::D, SCL.SimpleDataTypes::e, toolbit-attributes::s, InitGui::t, and draftgeoutils.general::v1().
Referenced by tangentialArc().
create3dCurve()
void Part::create3dCurve (const TopoDS_Edge & edge)
Definition at line 113 of file Curve2dPyImp.cpp.
References Handle().
createFilletGeometry()
PartExport GeomArcOfCircle * Part::createFilletGeometry (const GeomLineSegment * lineSeg1, const GeomLineSegment * lineSeg2, const Base::Vector3d & center, double radius)
Definition at line 6205 of file Part/App/Geometry.cpp.
References KDL::atan2(), exportCSG::center(), geoff_geometry::corner(), find2DLinesIntersection(), Part::GeomLineSegment::getEndPoint(), Part::GeomLineSegment::getStartPoint(), M_PI, Base::Vector3< float_type >::ProjectToLine(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by Sketcher::SketchObject::fillet().
encodeFilename()
std::string Part::encodeFilename (std::string fn) inline
Definition at line 49 of file encodeFilename.h.
Referenced by Part::TopoShape::exportBrep(), Part::TopoShape::exportIges(), Part::TopoShape::exportStep(), Part::TopoShape::exportStl(), Part::TopoShape::importBrep(), Part::TopoShape::importIges(), Part::TopoShape::importStep(), ImportStepParts(), Import::ReaderIges::read(), Import::ReaderStep::read(), Import::WriterIges::write(), Import::WriterGltf::write(), and Import::WriterStep::write().
find2DLinesIntersection() [1/2]
PartExport bool Part::find2DLinesIntersection (const Base::Vector3d & orig1, const Base::Vector3d & dir1, const Base::Vector3d & orig2, const Base::Vector3d & dir2, Base::Vector3d & point)
Definition at line 6079 of file Part/App/Geometry.cpp.
References src.Mod.PartDesign.Scripts.Gear::c1, SCL.SimpleDataTypes::e, SCL.SimpleDataTypes::f, MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, and Base::Vector3< float_type >::y.
Referenced by createFilletGeometry(), Sketcher::SketchObject::fillet(), find2DLinesIntersection(), findFilletCenter(), and suggestFilletRadius().
find2DLinesIntersection() [2/2]
PartExport bool Part::find2DLinesIntersection (const GeomLineSegment * lineSeg1, const GeomLineSegment * lineSeg2, Base::Vector3d & point)
Definition at line 6094 of file Part/App/Geometry.cpp.
References find2DLinesIntersection(), Part::GeomLineSegment::getEndPoint(), and Part::GeomLineSegment::getStartPoint().
findAllFacesCutBy() [1/2]
std::vector< Part::cutFaces > Part::findAllFacesCutBy (const TopoDS_Shape & shape, const TopoDS_Shape & face, const gp_Dir & dir)
Definition at line 1849 of file PartFeature.cpp.
References Part::cutFaces::distsq, Part::cutFaces::face, and result.
Referenced by PartDesign::ProfileBased::getUpToFace(), and PartDesign::FeatureExtrude::makeShellFromUpToShape().
findAllFacesCutBy() [2/2]
std::vector< Part::cutTopoShapeFaces > Part::findAllFacesCutBy (const TopoShape & shape, const TopoShape & face, const gp_Dir & dir)
Definition at line 1890 of file PartFeature.cpp.
References Part::cutTopoShapeFaces::distsq, Part::cutTopoShapeFaces::face, Part::TopoShape::getShape(), Part::TopoShape::mapSubElement(), and result.
findFilletCenter() [1/2]
PartExport bool Part::findFilletCenter (const GeomLineSegment * lineSeg1, const GeomLineSegment * lineSeg2, double radius, Base::Vector3d & center)
Definition at line 6104 of file Part/App/Geometry.cpp.
References exportCSG::center(), Part::GeomLineSegment::getEndPoint(), and Part::GeomLineSegment::getStartPoint().
Referenced by Sketcher::SketchObject::fillet().
findFilletCenter() [2/2]
PartExport bool Part::findFilletCenter (const GeomLineSegment * lineSeg1, const GeomLineSegment * lineSeg2, double radius, const Base::Vector3d & refPnt1, const Base::Vector3d & refPnt2, Base::Vector3d & center)
Definition at line 6112 of file Part/App/Geometry.cpp.
References exportCSG::center(), geoff_geometry::corner(), find2DLinesIntersection(), Part::GeomLineSegment::getEndPoint(), Part::GeomLineSegment::getStartPoint(), Base::Vector3< float_type >::Normalize(), Base::Vector3< float_type >::ProjectToLine(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
getPyShapes() [1/2]
PartExport std::vector< TopoShape > Part::getPyShapes (PyObject * obj)
Definition at line 149 of file AppPartPy.cpp.
References getPyShapes().
getPyShapes() [2/2]
PartExport void Part::getPyShapes (PyObject * obj, std::vector< TopoShape > & shapes)
Definition at line 118 of file AppPartPy.cpp.
Referenced by getPyShapes(), makeShape(), and PyShapeMapper::populate().
getRefineModelParameter()
bool Part::getRefineModelParameter ()
Definition at line 61 of file FeaturePartBoolean.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by Part::Boolean::Boolean(), Part::MultiCommon::MultiCommon(), and Part::MultiFuse::MultiFuse().
ImportIgesParts()
int Part::ImportIgesParts (App::Document * pcDoc, const char * Name)
Definition at line 53 of file ImportIges.cpp.
References App::Document::addObject(), SCL.SimpleDataTypes::e, Base::FileInfo::fileNamePure(), Handle(), SplineSurface::i, ClipperLib::pi, Part::PropertyPartShape::setValue(), DrawingExample::Shape, and Part::Feature::Shape.
ImportStepParts()
int Part::ImportStepParts (App::Document * pcDoc, const char * Name)
The part shape property
Definition at line 61 of file ImportStep.cpp.
References App::Document::addObject(), Base::Console(), SCL.SimpleDataTypes::e, encodeFilename(), Base::FileInfo::exists(), Base::FileInfo::fileNamePure(), Part::Feature::getPyObject(), Handle(), SplineSurface::i, Base::ConsoleSingleton::Log(), ClipperLib::pi, Part::PropertyPartShape::setValue(), Part::Feature::Shape, and Path.Post.scripts.refactored_centroid_post::str.
initModule()
PyObject * TechDraw::initModule ()
Definition at line 2384 of file AppPartPy.cpp.
References Base::InterpreterSingleton::addModule(), and Base::Interpreter().
Referenced by PyMOD_INIT_FUNC().
intersect()
bool Part::intersect (const gp_Pln & pln1, const gp_Pln & pln2, gp_Lin & lin)
Definition at line 105 of file Mod/Part/App/Tools.cpp.
References Handle().
Referenced by TechDraw::DrawUtil::apparentIntersection(), Sketcher::SketchObject::deriveConstraintsForPieces(), TechDraw::DrawComplexSection::faceShapeIntersect(), TechDraw::DrawUtil::intersect2Lines3d(), TechDraw::DrawComplexSection::makeAlignedPieces(), and tangentialArc().
makeFromCurve()
PartExport std::unique_ptr< GeomCurve > Part::makeFromCurve (const Handle(Geom_Curve)& c, bool silent)
Definition at line 6423 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, Handle(), and makeFromTrimmedCurve().
Referenced by Part::GeomTrimmedCurve::isSame(), Part::GeomOffsetCurve::isSame(), and Part::GeomSweptSurface::isSame().
makeFromCurve2d()
std::unique_ptr< Geom2dCurve > Part::makeFromCurve2d (Handle(Geom2d_Curve) curve)
Definition at line 2251 of file Geometry2d.cpp.
References Handle().
makeFromCurveAdaptor()
PartExport std::unique_ptr< GeomCurve > Part::makeFromCurveAdaptor (const Adaptor3d_Curve & adapt, bool silent)
Definition at line 6578 of file Part/App/Geometry.cpp.
References Handle(), makeFromTrimmedCurve(), buildPsets::u, and TestSpreadsheet::v.
Referenced by Part::Geometry::fromShape().
makeFromCurveAdaptor2d()
std::unique_ptr< Geom2dCurve > Part::makeFromCurveAdaptor2d (const Adaptor2d_Curve2d & adapt)
Definition at line 2372 of file Geometry2d.cpp.
References Handle(), makeFromTrimmedCurve2d(), buildPsets::u, and TestSpreadsheet::v.
makeFromSurface()
PartExport std::unique_ptr< GeomSurface > Part::makeFromSurface (const Handle(Geom_Surface)& s, bool silent)
Definition at line 6246 of file Part/App/Geometry.cpp.
References Handle(), and toolbit-attributes::s.
Referenced by Part::GeomOffsetSurface::isSame(), and Part::GeomTrimmedSurface::isSame().
makeFromSurfaceAdaptor()
PartExport std::unique_ptr< GeomSurface > Part::makeFromSurfaceAdaptor (const BRepAdaptor_Surface & adapt, bool silent)
Definition at line 6313 of file Part/App/Geometry.cpp.
References create_qrc::ext, Handle(), and toolbit-attributes::s.
Referenced by Part::Geometry::fromShape().
makeFromTrimmedCurve()
PartExport std::unique_ptr< GeomCurve > Part::makeFromTrimmedCurve (const Handle(Geom_Curve)& c, double f, double l, bool silent)
Definition at line 6481 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, SCL.SimpleDataTypes::f, Handle(), RobotExample::l, and TestSpreadsheet::v.
Referenced by makeFromCurve(), and makeFromCurveAdaptor().
makeFromTrimmedCurve2d()
std::unique_ptr< Geom2dCurve > Part::makeFromTrimmedCurve2d (const Handle(Geom2d_Curve)& c, double f, double l)
Definition at line 2284 of file Geometry2d.cpp.
References SCL.SimpleDataTypes::c, SCL.SimpleDataTypes::f, Handle(), RobotExample::l, and TestSpreadsheet::v.
Referenced by makeFromCurveAdaptor2d().
makeGeometryCurvePy()
const Py::Object Part::makeGeometryCurvePy (const Handle(Geom_Curve)& c)
Definition at line 91 of file GeometrySurfacePyImp.cpp.
makeTrimmedCurvePy()
const Py::Object Part::makeTrimmedCurvePy (const Handle(Geom_Curve)& c, double f, double l)
Definition at line 80 of file GeometrySurfacePyImp.cpp.
mapTypeShape()
static const std::map<PyTypeObject*, TopAbs_ShapeEnum> Part::mapTypeShape (vecTypeShape. begin(), vecTypeShape. end()) static
ReadColors()
bool Part::ReadColors (const Handle(XSControl_WorkSession) & WS, std::map< int, Quantity_Color > & hash_col)
Definition at line 218 of file ImportStep.cpp.
ReadNames()
bool Part::ReadNames (const Handle(XSControl_WorkSession) & WS)
Definition at line 225 of file ImportStep.cpp.
shape2pyshape() [1/2]
Py::Object Part::shape2pyshape (const TopoDS_Shape & shape)
Definition at line 55 of file PartPyCXX.cpp.
Referenced by getElements(), Part::PropertyShapeCache::getPyObject(), Part::TopoShape::getPySubShape(), PartDesign::CoordinateSystem::getSubObject(), Part::Datum::getSubObject(), Part::Feature::getSubObject(), Sketcher::SketchObject::getSubObject(), and makeShape().
shape2pyshape() [2/2]
PartExport Py::Object Part::shape2pyshape (const TopoShape & shape)
Definition at line 49 of file PartPyCXX.cpp.
ShapeTypeFromPyType()
static TopAbs_ShapeEnum Part::ShapeTypeFromPyType (PyTypeObject * pyType) static
Definition at line 878 of file TopoShapePyImp.cpp.
References vecTypeShape.
sort_Edges()
PartExport std::list<TopoDS_Edge> Part::sort_Edges (double tol3d, std::list< TopoDS_Edge > & edges)
Definition at line 166 of file AppPartPy.cpp.
References Handle().
suggestFilletRadius()
PartExport double Part::suggestFilletRadius (const GeomLineSegment * lineSeg1, const GeomLineSegment * lineSeg2, const Base::Vector3d & refPnt1, const Base::Vector3d & refPnt2)
Definition at line 6167 of file Part/App/Geometry.cpp.
References geoff_geometry::corner(), find2DLinesIntersection(), Part::GeomLineSegment::getEndPoint(), Part::GeomLineSegment::getStartPoint(), FreeCADInit::Length, Base::Vector3< float_type >::Normalize(), Base::Vector3< float_type >::ProjectToLine(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
supportedSTEPSchemes()
std::list<std::string> Part::supportedSTEPSchemes () inline
Definition at line 39 of file ImportStep.h.
tangentialArc()
PartExport bool Part::tangentialArc (const gp_Pnt & p0, const gp_Vec & v0, const gp_Pnt & p1, gp_Pnt & c, gp_Dir & axis)
Definition at line 50 of file BSplineCurveBiArcs.cpp.
References SCL.SimpleDataTypes::c, closestPointsOnLines(), intersect(), src.Mod.PartDesign.Scripts.Gear::l1, and draftgeoutils.general::v1().
Referenced by Part::TangentialArc::TangentialArc().
throwIfInvalidIfCheckModel()
void Part::throwIfInvalidIfCheckModel (const TopoDS_Shape & shape)
Definition at line 45 of file FeaturePartBoolean.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by Part::Boolean::execute(), Part::MultiFuse::execute(), and Part::MultiCommon::execute().
Variable Documentation
angleRangeU
const App::PropertyQuantityConstraint::Constraints Part::angleRangeU = {0.0, 360.0, 1.0}
Definition at line 78 of file PrimitiveFeature.cpp.
Referenced by Part::Cone::Cone(), Part::Cylinder::Cylinder(), Part::Ellipsoid::Ellipsoid(), Part::Revolution::Revolution(), Part::Sphere::Sphere(), and Part::Torus::Torus().
angleRangeV
const App::PropertyQuantityConstraint::Constraints Part::angleRangeV = {-90.0, 90.0, 1.0}
Definition at line 79 of file PrimitiveFeature.cpp.
Referenced by Part::Ellipsoid::Ellipsoid(), and Part::Sphere::Sphere().
apexRange
const App::PropertyQuantityConstraint::Constraints Part::apexRange = {-89.9, 89.9, 0.1}
Definition at line 76 of file PrimitiveFeature.cpp.
Referenced by Part::Helix::Helix().
PartExceptionOCCConstructionError
PyObject * Part::PartExceptionOCCConstructionError
Definition at line 206 of file AppPart.cpp.
Referenced by PyMOD_INIT_FUNC().
PartExceptionOCCDimensionError
PyObject * Part::PartExceptionOCCDimensionError
Definition at line 207 of file AppPart.cpp.
Referenced by PyMOD_INIT_FUNC().
PartExceptionOCCDomainError
PyObject * Part::PartExceptionOCCDomainError
Definition at line 204 of file AppPart.cpp.
Referenced by PyMOD_INIT_FUNC().
PartExceptionOCCError
PyObject * Part::PartExceptionOCCError
Definition at line 203 of file AppPart.cpp.
Referenced by Fem::Module::Module(), and PyMOD_INIT_FUNC().
PartExceptionOCCRangeError
PyObject * Part::PartExceptionOCCRangeError
Definition at line 205 of file AppPart.cpp.
Referenced by PyMOD_INIT_FUNC().
quantityRange
const App::PropertyQuantityConstraint::Constraints Part::quantityRange = {0.0, FLT_MAX, 0.1}
Definition at line 80 of file PrimitiveFeature.cpp.
Referenced by Part::Ellipsoid::Ellipsoid(), Part::Helix::Helix(), Part::Sphere::Sphere(), Part::Spiral::Spiral(), and Part::Torus::Torus().
torusRangeV
const App::PropertyQuantityConstraint::Constraints Part::torusRangeV = {-180.0, 180.0, 1.0}
Definition at line 77 of file PrimitiveFeature.cpp.
Referenced by Part::Torus::Torus().
vecTypeShape
const std::vector<std::pair<PyTypeObject*, TopAbs_ShapeEnum> > Part::vecTypeShape static
Initial value:
= {
    {&TopoShapeCompoundPy::Type, TopAbs_COMPOUND},
    {&TopoShapeCompSolidPy::Type, TopAbs_COMPSOLID},
    {&TopoShapeSolidPy::Type, TopAbs_SOLID},
    {&TopoShapeShellPy::Type, TopAbs_SHELL},
    {&TopoShapeFacePy::Type, TopAbs_FACE},
    {&TopoShapeWirePy::Type, TopAbs_WIRE},
    {&TopoShapeEdgePy::Type, TopAbs_EDGE},
    {&TopoShapeVertexPy::Type, TopAbs_VERTEX},
    {&TopoShapePy::Type, TopAbs_SHAPE}
}
Definition at line 861 of file TopoShapePyImp.cpp.
Referenced by ShapeTypeFromPyType().