FreeCAD: MeshCore::MeshInfo Class Reference
MeshCore::MeshInfo Class Reference
#include <Info.h>
Public Member Functions
MeshInfo (const MeshKernel &rclM)
virtual ~MeshInfo ()=default
std::ostream & GeneralInformation (std::ostream &rclStream) const
std::ostream & DetailedInformation (std::ostream &rclStream) const
std::ostream & InternalInformation (std::ostream &rclStream) const
std::ostream & TopologyInformation (std::ostream &rclStream) const
MeshInfo ()=delete
MeshInfo (const MeshInfo &)=delete
MeshInfo (MeshInfo &&)=delete
MeshInfo & operator= (const MeshInfo &)=delete
MeshInfo & operator= (MeshInfo &&)=delete
Protected Member Functions
std::ostream & DetailedPointInfo (std::ostream &rclStream) const
std::ostream & DetailedEdgeInfo (std::ostream &rclStream) const
std::ostream & DetailedFacetInfo (std::ostream &rclStream) const
std::ostream & InternalPointInfo (std::ostream &rclStream) const
std::ostream & InternalFacetInfo (std::ostream &rclStream) const
Detailed Description
Determines information about the mesh data structure.
Definition at line 57 of file Info.h.
Constructor & Destructor Documentation
MeshInfo() [1/4]
MeshInfo::MeshInfo (const MeshKernel & rclM) explicit
Definition at line 38 of file Info.cpp.
~MeshInfo()
virtual MeshCore::MeshInfo::~MeshInfo () virtual default
MeshInfo() [2/4]
MeshCore::MeshInfo::MeshInfo () delete
MeshInfo() [3/4]
MeshCore::MeshInfo::MeshInfo (const MeshInfo &) delete
MeshInfo() [4/4]
MeshCore::MeshInfo::MeshInfo (MeshInfo &&) delete
Member Function Documentation
DetailedEdgeInfo()
std::ostream & MeshInfo::DetailedEdgeInfo (std::ostream & rclStream) const protected
Writes detailed edge information.
Definition at line 78 of file Info.cpp.
References MeshCore::MeshFacet::_aulPoints, MeshCore::MeshKernel::GetFacets(), MeshCore::MeshKernel::GetPoints(), SplineSurface::i, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by DetailedInformation().
DetailedFacetInfo()
std::ostream & MeshInfo::DetailedFacetInfo (std::ostream & rclStream) const protected
Writes detailed facet information.
Definition at line 126 of file Info.cpp.
References MeshCore::MeshKernel::CountFacets(), MeshCore::MeshFacetIterator::End(), and SplineSurface::i.
Referenced by DetailedInformation().
DetailedInformation()
std::ostream & MeshInfo::DetailedInformation (std::ostream & rclStream) const
Writes detailed information about the mesh structure into the stream.
Definition at line 154 of file Info.cpp.
References DetailedEdgeInfo(), DetailedFacetInfo(), and DetailedPointInfo().
DetailedPointInfo()
std::ostream & MeshInfo::DetailedPointInfo (std::ostream & rclStream) const protected
Writes detailed point information.
Definition at line 57 of file Info.cpp.
References MeshCore::MeshKernel::CountPoints(), MeshCore::MeshPointIterator::End(), and SplineSurface::i.
Referenced by DetailedInformation().
GeneralInformation()
std::ostream & MeshInfo::GeneralInformation (std::ostream & rclStream) const
Writes general information about the mesh structure into the stream.
Definition at line 42 of file Info.cpp.
References MeshCore::MeshKernel::CountEdges(), MeshCore::MeshKernel::CountFacets(), and MeshCore::MeshKernel::CountPoints().
InternalFacetInfo()
std::ostream & MeshInfo::InternalFacetInfo (std::ostream & rclStream) const protected
Writes internal facet information.
Definition at line 190 of file Info.cpp.
References MeshCore::MeshKernel::CountFacets(), MeshCore::MeshKernel::GetFacets(), and SplineSurface::i.
Referenced by InternalInformation().
InternalInformation()
std::ostream & MeshInfo::InternalInformation (std::ostream & rclStream) const
Writes internal information about the mesh structure into the stream.
Definition at line 221 of file Info.cpp.
References InternalFacetInfo(), and InternalPointInfo().
InternalPointInfo()
std::ostream & MeshInfo::InternalPointInfo (std::ostream & rclStream) const protected
Writes internal point information.
Definition at line 163 of file Info.cpp.
References MeshCore::MeshKernel::CountPoints(), MeshCore::MeshPointIterator::End(), and SplineSurface::i.
Referenced by InternalInformation().
operator=() [1/2]
MeshInfo& MeshCore::MeshInfo::operator= (const MeshInfo &) delete
operator=() [2/2]
MeshInfo& MeshCore::MeshInfo::operator= (MeshInfo &&) delete
TopologyInformation()
std::ostream & MeshInfo::TopologyInformation (std::ostream & rclStream) const
Writes topological information about the mesh structure into the stream.
Definition at line 229 of file Info.cpp.
References MeshCore::MeshKernel::GetFacets().
The documentation for this class was generated from the following files:
Info.h
Info.cpp