FreeCAD: Py Namespace Reference
Py Namespace Reference
Classes
class GeometryT
class SmartPtr
This is a stripped-down version of Py::Object. The purpose of this class is to avoid to include any other header file and therefore the PyObject is forward declared and the implementation is separated from the class declaration.
class Vector
Typedefs
using Vector2d = PythonClassObject< Base::Vector2dPy >
using BoundingBox = GeometryT< Base::BoundBox3d, Base::BoundBoxPy, &Base::BoundBoxPy::getBoundBoxPtr >
using Matrix = GeometryT< Base::Matrix4D, Base::MatrixPy, &Base::MatrixPy::getMatrixPtr >
using Rotation = GeometryT< Base::Rotation, Base::RotationPy, &Base::RotationPy::getRotationPtr >
using Placement = GeometryT< Base::Placement, Base::PlacementPy, &Base::PlacementPy::getPlacementPtr >
using FemMesh = ExtensionObject< Fem::FemMeshPy >
using TopoShape = ExtensionObject< Part::TopoShapePy >
Functions
Base::Vector2d toVector2d (PyObject *py)
Base::Vector2d toVector2d (const Object &py)
BaseExport PyObject * new_reference_to (const SmartPtr &ptr)
Typedef Documentation
BoundingBox
using Py::BoundingBox = typedef GeometryT<Base::BoundBox3d, Base::BoundBoxPy, &Base::BoundBoxPy::getBoundBoxPtr>
Definition at line 282 of file GeometryPyCXX.h.
FemMesh
using Py::FemMesh = typedef ExtensionObject<Fem::FemMeshPy>
Definition at line 297 of file HypothesisPy.cpp.
Matrix
using Py::Matrix = typedef GeometryT<Base::Matrix4D, Base::MatrixPy, &Base::MatrixPy::getMatrixPtr>
Definition at line 283 of file GeometryPyCXX.h.
Placement
using Py::Placement = typedef GeometryT<Base::Placement, Base::PlacementPy, &Base::PlacementPy::getPlacementPtr>
Definition at line 286 of file GeometryPyCXX.h.
Rotation
using Py::Rotation = typedef GeometryT<Base::Rotation, Base::RotationPy, &Base::RotationPy::getRotationPtr>
Definition at line 284 of file GeometryPyCXX.h.
TopoShape
typedef ExtensionObject< Part::TopoShapePy > Py::TopoShape
Definition at line 298 of file HypothesisPy.cpp.
Vector2d
using Py::Vector2d = typedef PythonClassObject<Base::Vector2dPy>
Definition at line 130 of file GeometryPyCXX.h.
Function Documentation
new_reference_to()
BaseExport PyObject * Py::new_reference_to (const SmartPtr & ptr)
Definition at line 142 of file SmartPtrPy.cpp.
Referenced by App::UnitExpression::_getPyValue(), App::ConstantExpression::_getPyValue(), _pyObjectFromVariant(), calc(), Gui::CommandActionPy::descriptorGetter(), Gui::FreeCADGui_subgraphFromObject(), App::DocumentObjectExtension::getExtensionPyObject(), Gui::ViewProviderExtension::getExtensionPyObject(), TechDraw::CosmeticExtension::getExtensionPyObject(), App::GroupExtension::getExtensionPyObject(), Part::AttachExtension::getExtensionPyObject(), App::Extension::getExtensionPyObject(), App::LinkBaseExtension::getExtensionPyObject(), App::PropertyPythonObject::getPyObject(), TechDraw::DrawHatch::getPyObject(), TechDraw::DrawParametricTemplate::getPyObject(), Assembly::BomObject::getPyObject(), TechDraw::CosmeticVertex::getPyObject(), Assembly::AssemblyLink::getPyObject(), Part::Feature::getPyObject(), TechDraw::DrawGeomHatch::getPyObject(), TechDraw::CosmeticEdge::getPyObject(), TechDraw::DrawWeldSymbol::getPyObject(), Part::PropertyGeometryList::getPyObject(), Part::PropertyTopoShapeList::getPyObject(), TechDraw::DrawLeaderLine::getPyObject(), Assembly::AssemblyObject::getPyObject(), Measure::Measurement::getPyObject(), Assembly::BomGroup::getPyObject(), Assembly::JointGroup::getPyObject(), Assembly::SimulationGroup::getPyObject(), Assembly::ViewGroup::getPyObject(), Part::Primitive::getPyObject(), Gui::LinkView::getPyObject(), Mesh::Feature::getPyObject(), Fem::FemPostObject::getPyObject(), TechDraw::DrawTemplate::getPyObject(), TechDraw::DrawViewSymbol::getPyObject(), App::DocumentObjectGroup::getPyObject(), Fem::FemPostPipeline::getPyObject(), Fem::FemSetElementsObject::getPyObject(), App::VRMLObject::getPyObject(), Fem::FemSetFacesObject::getPyObject(), Fem::FemSetGeometryObject::getPyObject(), App::InventorObject::getPyObject(), Robot::RobotObject::getPyObject(), Fem::FemSetObject::getPyObject(), Robot::TrajectoryObject::getPyObject(), Fem::FemSetElementNodesObject::getPyObject(), Fem::FemSetNodesObject::getPyObject(), TechDraw::DrawRichAnno::getPyObject(), TechDraw::DrawTile::getPyObject(), Path::Feature::getPyObject(), TechDraw::DrawTileWeld::getPyObject(), TechDraw::DrawViewDimExtent::getPyObject(), Fem::FemMeshObject::getPyObject(), Fem::FemSolverObject::getPyObject(), TechDraw::DrawSVGTemplate::getPyObject(), TechDraw::DrawBrokenView::getPyObject(), Path::FeatureCompound::getPyObject(), TechDraw::CenterLine::getPyObject(), Measure::MeasureBase::getPyObject(), TechDraw::DrawProjGroupItem::getPyObject(), Fem::FemResultObject::getPyObject(), Fem::PropertyPostDataObject::getPyObject(), TechDraw::DrawView::getPyObject(), App::GeoFeature::getPyObject(), Part::Geom2dPoint::getPyObject(), TechDraw::DrawPage::getPyObject(), TechDraw::DrawViewClip::getPyObject(), TechDraw::DrawProjGroup::getPyObject(), PartDesign::Body::getPyObject(), TechDraw::GeomFormat::getPyObject(), TechDraw::DrawViewPart::getPyObject(), Spreadsheet::PropertyColumnWidths::getPyObject(), TechDraw::DrawViewDimension::getPyObject(), Spreadsheet::PropertyRowHeights::getPyObject(), Mesh::PropertyCurvatureList::getPyObject(), App::PropertyExpressionEngine::getPyObject(), Part::PropertyShapeHistory::getPyObject(), Spreadsheet::Sheet::getPyObject(), Spreadsheet::PropertySheet::getPyObject(), Mesh::PropertyMaterial::getPyObject(), Base::Exception::getPyObject(), Part::PropertyFilletEdges::getPyObject(), Part::PropertyShapeCache::getPyObject(), Base::FileException::getPyObject(), App::Document::getPyObject(), Sketcher::SketchObject::getPyObject(), App::PropertyLinkList::getPyObject(), App::PropertyLinkSub::getPyObject(), App::PropertyLinkSubList::getPyObject(), App::PropertyMaterialList::getPyObject(), App::PropertyXLink::getPyObject(), App::PropertyXLinkSub::getPyObject(), App::PropertyXLinkSubList::getPyObject(), App::PropertyXLinkList::getPyObject(), Part::TopoShape::getPySubShape(), Spreadsheet::PropertySheet::getPyValue(), App::FeaturePythonImp::getSubObject(), PartDesign::CoordinateSystem::getSubObject(), Part::Datum::getSubObject(), Part::Feature::getSubObject(), Sketcher::SketchObject::getSubObject(), makeShape(), PartDesign::PYTHON_TYPE_DEF(), Gui::PythonDebuggerP::PythonDebuggerP(), Gui::ApplicationPy::sActivateWorkbenchHandler(), Gui::ApplicationPy::sActiveView(), Gui::SelectionSingleton::sGetCompleteSelection(), Gui::ApplicationPy::sGetIcon(), Gui::ApplicationPy::sGetMainWindow(), AttacherGui::AttacherGuiPy::sGetModeStrings(), Gui::SelectionSingleton::sGetPickedList(), AttacherGui::AttacherGuiPy::sGetRefTypeUserFriendlyName(), Gui::SelectionSingleton::sGetSelection(), Gui::SelectionSingleton::sGetSelectionEx(), Gui::SelectionSingleton::sGetSelectionFromStack(), Gui::ApplicationPy::sGetUserEditMode(), Gui::SelectionSingleton::sHasSelection(), Gui::SelectionSingleton::sHasSubSelection(), Gui::ApplicationPy::sIsIconCached(), Base::UnitsApi::sListSchemas(), Gui::ApplicationPy::sListUserEditModes(), Base::UnitsApi::sSchemaTranslate(), Gui::ApplicationPy::sSetUserEditMode(), Gui::ApplicationPy::sSupportedLocales(), and Base::UnitsApi::sToNumber().
toVector2d() [1/2]
Base::Vector2d Py::toVector2d (const Object & py) inline
Definition at line 138 of file GeometryPyCXX.h.
References Base::Vector2dPy::value().
toVector2d() [2/2]
Base::Vector2d Py::toVector2d (PyObject * py) inline
Definition at line 132 of file GeometryPyCXX.h.
References Base::Vector2dPy::value().
Referenced by Base::Vector2dPy::distance(), Base::Vector2dPy::getAngle(), getPointFromPy(), Base::Vector2dPy::isEqual(), Base::Vector2dPy::number_add(), Base::Vector2dPy::number_multiply(), Base::Vector2dPy::number_subtract(), and Base::Vector2dPy::projectToLine().