FreeCAD: Sandbox::DocumentProtectorPy Class Reference
Sandbox::DocumentProtectorPy Class Reference
#include <DocumentProtectorPy.h>
Public Member Functions
DocumentProtectorPy (App::DocumentPy *doc)
~DocumentProtectorPy ()
Py::Object repr ()
Py::Object getattr (const char *)
int setattr (const char *, const Py::Object &)
Py::Object addObject (const Py::Tuple &)
Py::Object recompute (const Py::Tuple &)
Static Public Member Functions
static void init_type (void)
Friends
class DocumentProtector
Detailed Description
Definition at line 38 of file DocumentProtectorPy.h.
Constructor & Destructor Documentation
DocumentProtectorPy()
DocumentProtectorPy::DocumentProtectorPy (App::DocumentPy * doc)
Definition at line 54 of file DocumentProtectorPy.cpp.
References toolbit-attributes::doc, and DocumentProtector.
~DocumentProtectorPy()
DocumentProtectorPy::~DocumentProtectorPy ()
Definition at line 59 of file DocumentProtectorPy.cpp.
Member Function Documentation
addObject()
Py::Object DocumentProtectorPy::addObject (const Py::Tuple & args)
Definition at line 126 of file DocumentProtectorPy.cpp.
References Sandbox::DocumentProtector::addObject(), toolbit-attributes::args, toolbit-attributes::s, and Path.Post.scripts.grbl_post::type.
Referenced by init_type().
getattr()
Py::Object DocumentProtectorPy::getattr (const char * attr)
Definition at line 92 of file DocumentProtectorPy.cpp.
References toolbit-attributes::s.
init_type()
void DocumentProtectorPy::init_type (void) static
Definition at line 41 of file DocumentProtectorPy.cpp.
References addObject(), and recompute().
Referenced by Sandbox::PythonBaseClass::sequence_repeat().
recompute()
Py::Object DocumentProtectorPy::recompute (const Py::Tuple & args)
Definition at line 146 of file DocumentProtectorPy.cpp.
References toolbit-attributes::args, and Sandbox::DocumentProtector::recompute().
Referenced by init_type().
repr()
Py::Object DocumentProtectorPy::repr ()
Definition at line 64 of file DocumentProtectorPy.cpp.
References toolbit-attributes::s, and src.Mod.Test.testmakeWireString::String.
setattr()
int DocumentProtectorPy::setattr (const char * attr, const Py::Object & value)
Definition at line 112 of file DocumentProtectorPy.cpp.
References toolbit-attributes::s.
Friends And Related Function Documentation
DocumentProtector
friend class DocumentProtector friend
Definition at line 60 of file DocumentProtectorPy.h.
Referenced by DocumentProtectorPy().
The documentation for this class was generated from the following files:
DocumentProtectorPy.h
DocumentProtectorPy.cpp