FreeCAD: Base::BaseClass Class Reference
Base::BaseClass Class Reference
BaseClass class and root of the type system.
#include <BaseClass.h>
Public Member Functions
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
BaseClass class and root of the type system.
Definition at line 138 of file BaseClass.h.
Constructor & Destructor Documentation
BaseClass() [1/3]
BaseClass::BaseClass () default
Construction.
A constructor. A more elaborate description of the constructor.
BaseClass() [2/3]
Base::BaseClass::BaseClass (const BaseClass &) default
BaseClass() [3/3]
Base::BaseClass::BaseClass (BaseClass &&) default
~BaseClass()
BaseClass::~BaseClass () virtual default
Destruction.
A destructor. A more elaborate description of the destructor.
Member Function Documentation
create()
static void* Base::BaseClass::create () inline static
Definition at line 153 of file BaseClass.h.
Referenced by draftguitools.gui_labels.Label::action(), and init().
getClassTypeId()
Type BaseClass::getClassTypeId () static
Definition at line 70 of file BaseClass.cpp.
Referenced by SpreadsheetGui::DlgSheetConf::accept(), DrawingGui::TaskProjection::accept(), TechDrawGui::TaskProjection::accept(), StdCmdImport::activated(), StdCmdEdit::activated(), StdCmdToggleNavigation::activated(), Gui::Application::activateWorkbench(), InspectionGui::ViewProviderProxyObject::addFlag(), SpreadsheetGui::ViewProviderSheet::beforeDelete(), checkMigration(), Part::FaceMaker::ConstructFromType(), TechDrawGui::TaskActiveView::createActiveView(), Gui::Document::createView(), Gui::WorkbenchManager::createWorkbench(), SketcherGui::ViewProviderSketch::draw(), Sketcher::GeometryFacade::ensureSketchGeometryExtension(), Sketcher::ExternalGeometryFacade::ensureSketchGeometryExtensions(), App::FunctionExpression::evalAggregate(), App::FunctionExpression::evaluate(), MeshGui::ViewProviderMesh::faceInfoCallback(), Gui::Document::getActiveView(), Gui::ViewProvider::getBoundingBox(), TechDrawGui::QGVPage::getDevicePixelRatio(), Gui::Document::getEditingViewOfViewProvider(), Sketcher::SketchObject::getGeometryWithDependentParameters(), Gui::ViewProviderTextDocument::getMDIView(), getSafeGeomLayerId(), SketcherGui::ViewProviderSketch::getScaleFactor(), AttacherGui::getUIStrings(), Gui::UserNavigationStyle::getUserFriendlyNames(), Gui::ToolHandler::getViewer(), Gui::Document::getViewOfNode(), NaviCubeDraggableCmd::isActive(), StdViewScreenShot::isActive(), StdCmdToggleNavigation::isActive(), StdCmdTextureMapping::isActive(), Gui::View3DInventorPy::listNavigationTypes(), Gui::Dialog::DlgSettingsNavigation::loadSettings(), Sketcher::SketchObject::migrateSketch(), Gui::TreeWidget::mouseDoubleClickEvent(), Gui::TreeWidget::onActivateDocument(), Gui::View3DSettings::OnChange(), TechDrawGui::QGVPage::Private::OnChange(), Sketcher::SketchObject::onChanged(), Gui::Application::onLastWindowClosed(), SpreadsheetGui::DlgSheetConf::prepare(), Gui::Application::reopen(), Part::Geometry::Restore(), Gui::ApplicationPy::sActiveView(), Part::Geometry::Save(), Gui::Document::setActiveView(), Gui::View3DInventorViewer::setNavigationType(), setSafeGeomLayerId(), AttacherGui::AttacherGuiPy::sGetModeStrings(), Gui::Application::slotNewDocument(), SketcherGui::ViewProviderSketch::slotSolverUpdate(), and SketcherGui::EditModeGeometryCoinManager::updateGeometryColor().
getPyObject()
PyObject * BaseClass::getPyObject () virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented in Part::GeomTrimmedCurve, Part::GeomBezierCurve, TechDraw::DrawBrokenView, TechDraw::DrawSVGTemplate, TechDraw::DrawTile, TechDraw::DrawTemplate, Part::GeomArcOfConic, Part::GeomConic, Part::Geom2dArcOfConic, Part::Geom2dConic, Part::GeometryExtension, App::PropertyXLinkList, App::PropertyXLinkSubList, App::PropertyXLinkSub, App::PropertyPersistentObject, App::PropertyXLink, Part::GeomSurfaceOfExtrusion, App::PropertyMaterialList, Part::GeomSurfaceOfRevolution, Part::GeomTrimmedSurface, Part::GeomPlateSurface, Part::GeomOffsetSurface, App::PropertyMaterial, App::PropertyLinkSubList, Part::GeomPlane, Part::GeomToroid, App::PropertyColorList, Part::GeomSphere, App::PropertyColor, Part::GeomCone, Part::GeomCylinder, App::PropertyBoolList, Part::GeomBSplineSurface, App::PropertyLinkSub, App::PropertyBool, Part::GeomBezierSurface, App::PropertyStringList, Part::GeomOffsetCurve, Part::GeomLineSegment, App::PropertyUUID, Part::GeomLine, App::PropertyLinkList, Part::GeomArcOfParabola, App::PropertyString, Part::GeomParabola, App::StringHasher, Part::GeomArcOfHyperbola, App::PropertyFloatList, Part::GeomHyperbola, App::PropertyLink, Part::GeomArcOfEllipse, Part::GeomEllipse, Sketcher::SketchObject, Part::GeomArcOfCircle, Part::Geom2dTrimmedCurve, App::PropertyFloat, App::Document, Part::Geom2dOffsetCurve, Part::GeomCircle, Part::Geom2dLineSegment, App::PropertyMap, Part::Geom2dLine, App::PropertyRotation, Part::Geom2dArcOfParabola, Part::Geom2dParabola, Part::TopoShape, App::PropertyIntegerSet, App::PropertyPlacementList, Part::Geom2dArcOfHyperbola, Gui::AlignmentView, Sketcher::SolverGeometryExtension, Part::Geom2dHyperbola, Base::FileException, Part::GeomBSplineCurve, App::DocumentObject, Gui::ViewProvider, App::PropertyIntegerList, Part::Geom2dArcOfEllipse, App::PropertyPlacement, Part::Geom2dEllipse, Mesh::PropertyMeshKernel, Part::Geom2dArcOfCircle, Gui::Document, Part::Geom2dCircle, Part::PropertyShapeCache, App::PropertyMatrix, Sketcher::GeometryFacade, Gui::PythonBaseWorkbench, Part::PropertyFilletEdges, Gui::ViewProviderLink, App::PropertyEnumeration, Base::Exception, App::PropertyVectorList, Sketcher::ExternalGeometryFacade, Mesh::PropertyMaterial, Points::PropertyCurvatureList, Spreadsheet::PropertySheet, Inspection::PropertyDistanceList, Part::Geom2dBSplineCurve, Spreadsheet::Sheet, App::StringID, Gui::NavigationStyle, Part::PropertyShapeHistory, App::PropertyExpressionEngine, Part::GeomPoint, Mesh::PropertyCurvatureList, AssemblyGui::ViewProviderAssembly, MeshGui::ViewProviderMesh, PartGui::ViewProviderPartExt, Part::Geom2dBezierCurve, Points::PropertyNormalList, FemGui::ViewProviderFemMesh, App::Part, App::PropertyPath, Sketcher::Constraint, Spreadsheet::PropertyColumnWidths, Spreadsheet::PropertyRowHeights, TechDraw::DrawViewDimension, SpreadsheetGui::ViewProviderSheet, Part::BodyBase, Sketcher::SketchGeometryExtension, Sketcher::PropertyConstraintList, TechDraw::DrawViewPart, PartDesign::Body, Sketcher::ExternalGeometryExtension, TechDraw::GeomFormat, Fem::PropertyFemMesh, TechDraw::DrawProjGroup, TechDraw::DrawPage, TechDraw::DrawViewClip, Part::Geom2dPoint, App::GeoFeature, SpreadsheetGui::SheetView, Gui::ViewProviderDocumentObject, TechDraw::DrawView, Gui::View3DInventor, Fem::PropertyPostDataObject, Robot::PropertyTrajectory, Fem::FemResultObject, Part::GeometryMigrationExtension, TechDraw::DrawProjGroupItem, Measure::MeasureBase, Mesh::PropertyNormalList, Part::PropertyPartShape, Points::PropertyGreyValueList, Points::PropertyPointKernel, TechDraw::CenterLine, TechDrawGui::MDIViewPage, Path::FeatureCompound, Gui::ViewProviderGeometryObject, Fem::FemSolverObject, PartDesign::FeaturePrimitive, Path::FeatureArea, Fem::FemMeshObject, PartDesignGui::ViewProvider, TechDraw::DrawTileWeld, TechDraw::DrawViewDimExtent, Path::Feature, Fem::FemSetElementNodesObject, Fem::FemSetNodesObject, TechDraw::DrawRichAnno, Fem::FemSetObject, Robot::TrajectoryObject, App::InventorObject, App::PropertyFileIncluded, Path::PropertyPath, FemGui::ViewProviderFemPostPipeline, Robot::RobotObject, App::VRMLObject, Fem::FemSetElementsObject, Fem::FemSetFacesObject, Fem::FemSetGeometryObject, App::DocumentObjectGroup, Fem::FemPostPipeline, TechDraw::DrawViewSymbol, Gui::MDIView, App::PropertyVector, Fem::FemPostObject, Mesh::Feature, Gui::LinkView, Part::GeometryDefaultExtension< T >, Part::Primitive, Assembly::BomGroup, Assembly::JointGroup, Assembly::SimulationGroup, Assembly::ViewGroup, PartDesign::Feature, Gui::AbstractSplitView, Measure::Measurement, SketcherGui::ViewProviderSketchGeometryExtension, Assembly::AssemblyObject, TechDraw::DrawLeaderLine, Part::PropertyTopoShapeList, Part::PropertyGeometryList, Gui::MDIViewPyWrap, TechDraw::DrawWeldSymbol, TechDraw::PropertyCosmeticVertexList, TechDraw::PropertyCosmeticEdgeList, App::PropertyInteger, TechDraw::CosmeticEdge, TechDraw::PropertyGeomFormatList, Part::Feature, TechDraw::DrawGeomHatch, Gui::Workbench, Assembly::AssemblyLink, Materials::PropertyMaterial, Assembly::BomObject, TechDraw::CosmeticVertex, TechDraw::DrawParametricTemplate, TechDraw::PropertyCenterLineList, FemGui::ViewProviderFemConstraint, TechDraw::DrawHatch, SketcherGui::PropertyVisualLayerList, Gui::SelectionObject, App::PropertyPythonObject, App::PropertyQuantity, Part::GeometryDefaultExtension< T >, Part::GeometryDefaultExtension< T >, DrawingGui::DrawingView, Part::GeometryDefaultExtension< T >, and Part::GeometryDefaultExtension< T >.
Definition at line 107 of file BaseClass.cpp.
References Py_Return.
Referenced by Sandbox::DocumentObjectProtectorPy::getattr(), and Spreadsheet::PropertySheet::getPyValue().
getTypeId()
Type BaseClass::getTypeId () const virtual
Reimplemented in Base::AbortException, Base::Exception, Base::Persistence, CAMSimulator::CAMSim, and Measure::MeasureDistanceType.
Definition at line 75 of file BaseClass.cpp.
Referenced by Gui::View3DInventorPy::getNavigationType(), App::Expression::isSame(), Part::GeometryPersistenceExtension::Save(), and Gui::View3DInventorViewer::setNavigationType().
init()
void BaseClass::init () static
Definition at line 57 of file BaseClass.cpp.
References Base::Type::badType(), create(), and Base::Type::createType().
Referenced by Gui::DocumentModel::DocumentModel(), Gui::SoFCDB::init(), Gui::Application::initTypes(), App::Application::initTypes(), DocumentObject.DocumentObject::onChanged(), and PyMOD_INIT_FUNC().
initSubclass()
void BaseClass::initSubclass (Base::Type & toInit, const char * ClassName, const char * ParentName, Type::instantiationMethod method = nullptr) static protected
Definition at line 81 of file BaseClass.cpp.
References Base::Type::badType(), OverlayParams::ClassName, Base::Type::createType(), and Base::Type::fromName().
Referenced by Measure::MeasureDistanceType::init().
is()
template<typename T > bool Base::BaseClass::is () const inline
Definition at line 159 of file BaseClass.h.
Referenced by SketcherCopy::activate(), StdCmdPlacement::activated(), Sketcher::SketchObject::addCopy(), Sketcher::Sketch::addGeometry(), Sketcher::SketchObject::addSymmetric(), SketcherGui::FilletSelection::allow(), SketcherGui::calculateAngle(), Sketcher::SketchObject::calculateAngleViaPoint(), Gui::Document::cloneView(), Sketcher::SketchObject::convertToNURBS(), SketcherGui::DrawSketchHandler::createAutoConstraints(), DrawSketchHandlerDimension::createHorizontalConstrain(), DrawSketchHandlerDimension::createVerticalConstrain(), Sketcher::SketchObject::deleteUnusedInternalGeometry(), Sketcher::SketchObject::deriveConstraintsForPieces(), SketcherGui::EditModeConstraintCoinManager::drawConstraintIcons(), SketcherGui::DrawSketchHandlerExtend::DrawSketchHandlerExtend(), Mesh::SegmentByMesh::execute(), Mesh::HarmonizeNormals::execute(), Mesh::FlipNormals::execute(), Mesh::FixNonManifolds::execute(), Mesh::FixDuplicatedFaces::execute(), Mesh::FixDuplicatedPoints::execute(), Mesh::FixDegenerations::execute(), Mesh::FixDeformations::execute(), Mesh::FixIndices::execute(), Mesh::FillHoles::execute(), Mesh::RemoveComponents::execute(), Sketcher::SketchObject::exposeInternalGeometry(), Sketcher::SketchObject::extend(), PartGui::ViewProviderGridExtension::extensionUpdateData(), PartGui::ViewProviderSplineExtension::extensionUpdateData(), Sketcher::SketchObject::fillet(), findBSplineAndKnotIndex(), Gui::FreeCADGui_subgraphFromObject(), SketcherGui::ViewProviderSketch::generateContextMenu(), Mesh::MeshObject::getFacesFromSubElement(), Part::TopoShape::getFacesFromSubElement(), SketcherGui::getGeoIdsOfEdgesFromNames(), Part::TopoShape::getLinesFromSubElement(), Sketcher::SketchObject::getPoint(), Sketcher::SketchObject::getSymmetric(), Sketcher::SketchObject::hasInternalGeometry(), InspectionGui::ViewProviderInspection::inspectDistance(), Sketcher::isArcOfCircle(), Sketcher::isArcOfEllipse(), Sketcher::isArcOfHyperbola(), Sketcher::isArcOfParabola(), Sketcher::isBSplineCurve(), SketcherGui::isBsplineKnotOrEndPoint(), Sketcher::isCircle(), Sketcher::SketchObject::isClosedCurve(), Sketcher::isEllipse(), Sketcher::isLineSegment(), Sketcher::isPeriodicBSplineCurve(), Sketcher::isPoint(), SketcherGui::IsPointAlreadyOnCurve(), SketcherGui::isSimpleVertex(), Sketcher::SketchObject::isSupportedGeometry(), PartDesignGui::TaskFeaturePick::makeCopy(), Gui::TreeView::mouseDoubleClickEvent(), App::PropertyPythonObject::Paste(), SketcherGui::DrawSketchHandlerTrimming::pressButton(), SketcherGui::EditModeConstraintCoinManager::processConstraints(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), PartGui::ViewProviderSplineExtension::showControlPoints(), SketcherGui::SnapManager::snapToObject(), Sketcher::SketchObject::split(), PartGui::ViewProviderCurveNet::updateData(), Gui::ViewProviderAnnotation::updateData(), InspectionGui::ViewProviderInspection::updateData(), DrawingGui::ViewProviderDrawingPage::updateData(), PartGui::ViewProvider2DObjectGrid::updateData(), PartDesignGui::ViewProvider::updateData(), PartGui::ViewProviderMultiFuse::updateData(), PartGui::ViewProviderRuledSurface::updateData(), PartGui::ViewProviderBoolean::updateData(), PartGui::ViewProviderCompound::updateData(), PartGui::ViewProviderFillet::updateData(), Gui::ViewProviderAnnotationLabel::updateData(), PartGui::ViewProviderMultiCommon::updateData(), PartGui::ViewProviderChamfer::updateData(), PointsGui::ViewProviderScattered::updateData(), MeshGui::ViewProviderMesh::updateData(), PointsGui::ViewProviderStructured::updateData(), and MeshGui::ViewProviderIndexedFaceSet::updateData().
isDerivedFrom() [1/2]
template<typename T > bool Base::BaseClass::isDerivedFrom () const inline
Definition at line 165 of file BaseClass.h.
References Base::Type::isDerivedFrom().
Referenced by Gui::ViewProviderDocumentObject::canDelete(), PartDesignGui::ViewProviderShapeBinder::highlightReferences(), App::PropertyLink::resetLink(), App::PropertyLinkList::set1Value(), Part::GeomCurve::toLineSegment(), Part::GeomSurface::toPlane(), TechDrawGui::ViewProviderTemplate::updateData(), App::PropertyLinkList::~PropertyLinkList(), App::PropertyLinkSub::~PropertyLinkSub(), and App::PropertyLinkSubList::~PropertyLinkSubList().
isDerivedFrom() [2/2]
bool Base::BaseClass::isDerivedFrom (const Type type) const inline
Definition at line 143 of file BaseClass.h.
References Base::Type::isDerivedFrom(), and Path.Post.scripts.grbl_post::type.
Referenced by _getTopoShape(), Gui::Document::_resetEdit(), PartDesignGui::TaskDlgFeatureParameters::accept(), Gui::Dialog::TransformStrategy::acceptDataTransform(), StdCmdGroup::activated(), StdCmdToggleSelectability::activated(), StdCmdEdit::activated(), StdCmdToggleNavigation::activated(), Gui::Application::activateView(), PartDesign::Body::addObject(), Assembly::BomObject::addObjectChildrenToBom(), TechDraw::DrawViewCollection::addView(), TechDraw::DrawViewClip::addView(), TechDraw::DrawPage::addView(), Gui::ManualAlignment::alignObject(), PartDesignGui::ReferenceSelection::allow(), SketcherGui::FilletSelection::allow(), SurfaceGui::FillingVertexPanel::VertexSelection::allow(), PartGui::ShapeSelection::allow(), SurfaceGui::FillingEdgePanel::ShapeSelection::allow(), PartGui::MirrorPlaneSelection::allow(), SurfaceGui::GeomFillSurface::EdgeSelection::allow(), SurfaceGui::FillingPanel::ShapeSelection::allow(), SurfaceGui::SectionsPanel::ShapeSelection::allow(), Gui::PropertyEditor::PropertyRotationItem::assignProperty(), Gui::PropertyEditor::PropertyPlacementItem::assignProperty(), Gui::ExpressionBinding::assignToProperty(), Gui::ViewProviderLink::attach(), PartDesign::ShapeBinder::buildShapeFromReferences(), TechDrawGui::TaskRichAnno::calcTextStartPos(), Part::Extrusion::calculateShapeNormal(), PathGui::ViewProviderPathShape::canDragObject(), PartGui::ViewProviderCompound::canDragObject(), PathGui::ViewProviderArea::canDragObject(), PathGui::ViewProviderAreaView::canDragObject(), FemGui::ViewProviderFemAnalysis::canDragObject(), PartDesignGui::ViewProviderBody::canDropObject(), PartGui::ViewProviderCompound::canDropObject(), App::PropertyExpressionEngine::canonicalPath(), TechDrawGui::ViewProviderRichAnno::claimChildren(), PartDesignGui::ViewProviderSketchBased::claimChildren(), PartDesignGui::ViewProviderHelix::claimChildren(), TechDrawGui::ViewProviderProjGroup::claimChildren(), TechDrawGui::ViewProviderPage::claimChildren(), PartDesignGui::ViewProviderPipe::claimChildren(), TechDrawGui::ViewProviderBalloon::claimChildren(), TechDrawGui::ViewProviderDimension::claimChildren(), PartDesignGui::collectMovableDependencies(), Sketcher::SketchObject::convertToNURBS(), TechDrawGui::TaskRichAnno::createAnnoFeature(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), SpreadsheetGui::SheetModel::data(), Sketcher::SketchObject::deriveConstraintsForPieces(), Gui::SoFCUnifiedSelection::doAction(), TechDrawGui::ViewProviderViewClip::dragObject(), SketcherGui::ViewProviderSketch::draw(), TechDrawGui::QGIViewBalloon::drawBalloon(), TechDrawGui::ViewProviderPageExtension::dropObject(), PartDesignGui::ViewProviderBody::dropObject(), TechDrawGui::ViewProviderViewClip::dropObject(), Sketcher::SketchObject::evaluateSupport(), TechDraw::DrawViewDetail::execute(), Surface::Filling::execute(), Surface::Sections::execute(), Part::Mirroring::execute(), PartDesign::Pipe::execute(), Surface::Extend::execute(), TechDraw::DrawViewSpreadsheet::execute(), Robot::Edge2TracObject::execute(), Drawing::FeatureViewSpreadsheet::execute(), Robot::TrajectoryDressUpObject::execute(), Drawing::FeatureViewPart::execute(), Drawing::FeatureProjection::execute(), TechDraw::FeatureProjection::execute(), Inspection::Feature::execute(), App::Document::exportGraphviz(), Import::ExportOCAF::exportObject(), Spreadsheet::Sheet::exportToFile(), TechDrawGui::ViewProviderPageExtension::extensionCanDropObject(), TechDrawGui::ViewProviderPageExtension::extensionCanDropObjectEx(), TechDrawGui::ViewProviderPageExtension::extensionDropObject(), PartGui::ViewProviderGridExtension::extensionHandleChangedPropertyType(), MeshGui::ViewProviderMesh::faceInfoCallback(), FC_LOG_LEVEL_INIT(), Sketcher::SketchObject::fillet(), TechDraw::DrawView::findAllParentPages(), ImportGui::ExportOCAFGui::findColors(), finishProfileBased(), Gui::ViewProviderDragger::forwardToLink(), TechDraw::DrawViewDimension::getAnglePointsThreeVerts(), TechDraw::DrawViewDimension::getAnglePointsTwoEdges(), TechDraw::DrawViewDimension::getArcParameters(), TechDraw::DrawViewDimension::getAreaParameters(), App::LocalCoordinateSystem::getAxis(), PartDesign::ProfileBased::getAxis(), PartDesign::ProfileBased::getBaseObject(), Fem::Constraint::getDirection(), App::PropertyFileIncluded::getDocTransientPath(), Part::Feature::getElementHistory(), getElementSource(), PartDesign::ProfileBased::getFaceFromLinkSub(), Spreadsheet::Cell::getFormattedQuantity(), Assembly::AssemblyObject::getGroundedParts(), App::OriginGroupExtension::getGroupOfObject(), App::GeoFeatureGroupExtension::getGroupOfObject(), InspectionGui::ViewProviderInspection::getIcon(), Gui::View3DInventorPy::getObjectInfo(), Gui::View3DInventorPy::getObjectsInfo(), Gui::View3DInventor::getObjInfoRay(), TechDraw::DrawPage::getOrientation(), App::OriginGroupExtension::getOrigin(), TechDraw::DrawPage::getPageHeight(), TechDraw::DrawPage::getPageOrientation(), TechDraw::DrawPage::getPageWidth(), TechDrawGui::QGIDrawingTemplate::getParametricTemplate(), App::LocalCoordinateSystem::getPlane(), App::LocalCoordinateSystem::getPoint(), PartDesign::Feature::getPointFromFace(), TechDraw::DrawViewDimension::getPointsEdgeVert(), TechDraw::DrawViewDimExtent::getPointsExtent(), TechDraw::DrawViewDimension::getPointsOneEdge(), TechDraw::DrawViewDimension::getPointsTwoEdges(), TechDraw::DrawViewDimension::getPointsTwoVerts(), PartDesign::ProfileBased::getProfileWires(), getProperty(), PartDesignGui::getReferencedSelection(), Measure::MeasureBase::getResultString(), SketcherGui::ViewProviderSketch::getScaleFactor(), PartDesign::Loft::getSectionShape(), TechDraw::ShapeExtractor::getShapes(), TechDraw::ShapeExtractor::getShapesFromObject(), TechDraw::DrawViewSpreadsheet::getSheetImage(), TechDrawGui::QGISVGTemplate::getSVGTemplate(), Part::Feature::getTopoShape(), PartDesignGui::TaskTransformedParameters::getTopTransformedObject(), PartDesign::LinearPattern::getTransformations(), PartDesign::PolarPattern::getTransformations(), Gui::LinkInfo::getView(), MeshGui::MeshSelection::getViewer(), Gui::ToolHandler::getViewer(), PartGui::ViewProvider2DObjectGrid::handleChangedPropertyType(), Part::Primitive::handleChangedPropertyType(), TechDraw::DrawView::handleChangedPropertyType(), TechDraw::DrawPage::hasValidTemplate(), TechDrawGui::ViewProviderDrawingView::hide(), TechDrawGui::ViewProviderViewClip::hide(), DrawingGui::ViewProviderDrawingView::hide(), DrawingGui::ViewProviderDrawingClip::hide(), PartDesignGui::ViewProviderShapeBinder::highlightReferences(), App::GeoFeatureGroupExtension::initExtension(), PartDesign::Body::insertObject(), InspectionGui::ViewProviderInspection::inspectCallback(), InspectionGui::ViewProviderInspection::inspectDistance(), NaviCubeDraggableCmd::isActive(), StdCmdToggleNavigation::isActive(), StdCmdTextureMapping::isActive(), PartDesign::Body::isAllowed(), Measure::ShapeFinder::isLinkLike(), App::GeoFeatureGroupExtension::isLinkValid(), PartDesignGui::isPartDesignAwareObjecta(), App::PropertyLinkBase::isSame(), Part::GeomBSplineCurve::isSame(), Part::GeomConic::isSame(), Part::GeomLine::isSame(), Part::GeomBSplineSurface::isSame(), Part::GeomElementarySurface::isSame(), Part::GeomPlane::isSame(), Part::GeomSweptSurface::isSame(), PartDesign::Body::isSolidFeature(), TechDrawGui::QGIProjGroup::itemChange(), TechDrawGui::QGIViewSymbol::legacyScaler(), Fem::FemPostPipeline::load(), Import::ImportOCAF2::loadShapes(), PartDesignGui::TaskSketchBasedParameters::make2DLabel(), PartDesignGui::TaskFeaturePick::makeCopy(), TechDraw::DrawLeaderLine::makeLeader(), makeRefString(), FemGui::Module::Module(), Gui::TreeView::mouseDoubleClickEvent(), PartGui::OffsetWidget::OffsetWidget(), App::Document::onBeforeChangeProperty(), Assembly::AssemblyLink::onChanged(), TechDraw::DrawViewSection::onChanged(), TechDrawGui::MDIViewPage::onDeleteObject(), App::OriginGroupExtension::onExtendedSetupObject(), PartDesignGui::TaskLinearPatternParameters::onSelectionChanged(), PartDesignGui::TaskPolarPatternParameters::onSelectionChanged(), PartDesignGui::TaskMirroredParameters::onSelectionChanged(), TechDrawGui::MDIViewPage::onSelectionChanged(), PartDesignGui::TaskBooleanParameters::onSelectionChanged(), Gui::PropertyView::onTimer(), PartGui::PropertyEnumAttacherItem::openTask(), App::DocumentObjectT::operator=(), PartDesignGui::TaskTransformedParameters::originalSelected(), App::PropertyLink::Paste(), App::PropertyLinkList::Paste(), App::PropertyLinkSub::Paste(), App::PropertyLinkSubList::Paste(), App::PropertyXLink::Paste(), App::PropertyXLinkSubList::Paste(), PartDesign::ProfileBased::positionByPrevious(), prepareProfileBased(), SketcherGui::DrawSketchHandlerTrimming::pressButton(), Sketcher::SketchObject::rebuildExternalGeometry(), TechDraw::DrawViewCollection::rebuildViewList(), PartDesignGui::relinkToOrigin(), PartDesign::Body::removeObject(), TechDraw::DrawPage::removeView(), App::PropertyLinkList::Restore(), Path::PropertyPath::RestoreDocFile(), Fem::PropertyPostDataObject::RestoreDocFile(), Gui::ApplicationPy::sActiveView(), Fem::PropertyPostDataObject::SaveDocFile(), Gui::Document::sendMsgToFirstView(), Gui::Document::setActiveView(), PartDesign::Body::setBaseProperty(), Gui::Document::setHide(), TechDrawGui::QGSPage::setPageTemplate(), App::LinkBaseExtension::setProperty(), Gui::Document::setShow(), PartDesignGui::Workbench::setupContextMenu(), Gui::Application::setupContextMenu(), PartDesignGui::TaskSketchBasedParameters::setUpToFace(), Gui::RecoveryWriter::shouldWrite(), TechDrawGui::ViewProviderDrawingView::show(), TechDrawGui::ViewProviderViewClip::show(), DrawingGui::ViewProviderDrawingView::show(), DrawingGui::ViewProviderDrawingClip::show(), Gui::Document::slotActivatedObject(), Gui::Document::slotChangedObject(), Gui::ManualAlignment::slotDeletedObject(), Gui::Document::slotFinishRestoreDocument(), Gui::Document::slotRelabelObject(), SketcherGui::ViewProviderSketch::slotSolverUpdate(), Gui::Document::slotTransactionAppend(), Sketcher::SketchObject::split(), App::PropertyXLink::supportXLink(), Assembly::AssemblyLink::synchronizeComponents(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), TechDrawGui::TaskRichAnno::TaskRichAnno(), Gui::TaskView::TaskSelectLinkProperty::TaskSelectLinkProperty(), TechDrawGui::TaskWeldingSymbol::TaskWeldingSymbol(), Gui::PropertyEditor::PropertyMatrixItem::toolTip(), Gui::PropertyEditor::PropertyRotationItem::toolTip(), Gui::PropertyEditor::PropertyPlacementItem::toolTip(), Gui::PropertyEditor::PropertyMaterialItem::toolTip(), Gui::PropertyEditor::PropertyMaterialListItem::toolTip(), Sketcher::SketchObject::trim(), UnifiedDatumCommand(), Gui::TaskMeasure::update(), Gui::ViewProviderVRMLObject::updateData(), InspectionGui::ViewProviderInspection::updateData(), Gui::ViewProviderGeometryObject::updateData(), PartDesignGui::ViewProviderBody::updateData(), Gui::ViewProviderDragger::updateData(), PathGui::ViewProviderPathShape::updateData(), PartGui::ViewProviderCustom::updateData(), SketcherGui::ViewProviderCustom::updateData(), PathGui::ViewProviderArea::updateData(), PartGui::ViewProviderMultiFuse::updateData(), FemGui::ViewProviderFemMesh::updateData(), PartGui::ViewProviderBoolean::updateData(), PathGui::ViewProviderAreaView::updateData(), Gui::ViewProviderInventorObject::updateData(), PartGui::ViewProviderCompound::updateData(), PartGui::ViewProviderMultiCommon::updateData(), FemGui::ViewProviderFemPostPipeline::updateFunctionSize(), TechDrawGui::QGSPage::updateTemplate(), Sketcher::SketchObject::validateExternalLinks(), SketcherGui::PropertyConstraintListItem::value(), Gui::PropertyEditor::PropertyStringItem::value(), Gui::PropertyEditor::PropertyFontItem::value(), Gui::PropertyEditor::PropertyIntegerItem::value(), Gui::PropertyEditor::PropertyIntegerConstraintItem::value(), Gui::PropertyEditor::PropertyFloatItem::value(), Gui::PropertyEditor::PropertyUnitItem::value(), Gui::PropertyEditor::PropertyFloatConstraintItem::value(), Gui::PropertyEditor::PropertyBoolItem::value(), Gui::PropertyEditor::PropertyVectorItem::value(), Gui::PropertyEditor::PropertyVectorListItem::value(), Gui::PropertyEditor::PropertyVectorDistanceItem::value(), Gui::PropertyEditor::PropertyMatrixItem::value(), Gui::PropertyEditor::PropertyRotationItem::value(), Gui::PropertyEditor::PropertyPlacementItem::value(), Gui::PropertyEditor::PropertyEnumItem::value(), Gui::PropertyEditor::PropertyStringListItem::value(), Gui::PropertyEditor::PropertyFloatListItem::value(), Gui::PropertyEditor::PropertyIntegerListItem::value(), Gui::PropertyEditor::PropertyColorItem::value(), Gui::PropertyEditor::PropertyMaterialItem::value(), Gui::PropertyEditor::PropertyMaterialListItem::value(), Gui::PropertyEditor::PropertyFileItem::value(), Gui::PropertyEditor::PropertyPathItem::value(), Gui::PropertyEditor::PropertyTransientFileItem::value(), MeshPartGui::CurveOnMeshHandler::Private::vertexCallback(), Gui::RecoveryWriter::writeFiles(), and PartDesignGui::TaskDatumParameters::~TaskDatumParameters().
operator=() [1/2]
BaseClass& Base::BaseClass::operator= (BaseClass &&) default
operator=() [2/2]
BaseClass& Base::BaseClass::operator= (const BaseClass &) default
setPyObject()
void BaseClass::setPyObject (PyObject *) virtual
Reimplemented in App::PropertyXLinkSubList, App::PropertyLinkSub, App::PropertyLink, App::PropertyListsT< T, ListT, ParentT >, App::PropertyListsT< long >, App::PropertyListsT< Base::Vector3d >, App::PropertyListsT< double >, App::PropertyListsT< Color >, App::PropertyListsT< std::string >, App::PropertyListsT< bool, boost::dynamic_bitset<> >, App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >, App::PropertyListsT< Material >, App::PropertyListsT< Base::Placement >, App::PropertyListsT< VisualLayer >, Mesh::PropertyMeshKernel, Part::PropertyShapeCache, Mesh::PropertyCurvatureList, Fem::PropertyFemMesh, Fem::PropertyPostDataObject, Robot::PropertyTrajectory, Part::PropertyPartShape, Points::PropertyPointKernel, Path::PropertyPath, Base::FileException, Base::Exception, App::PropertyMaterial, App::PropertyColor, App::PropertyBoolList, App::PropertyBool, App::PropertyUUID, App::PropertyString, App::PropertyFloatConstraint, App::PropertyFloat, App::PropertyMap, App::PropertyIntegerSet, App::PropertyIntegerConstraint, App::PropertyEnumeration, App::PropertyPath, App::PropertyInteger, App::PropertyLinkListBase, App::PropertyLists, Part::TopoShape, App::PropertyPythonObject, App::PropertyXLinkList, App::PropertyXLink, App::PropertyLinkSubList, App::PropertyRotation, App::PropertyPlacement, App::PropertyMatrix, Part::PropertyFilletEdges, Mesh::PropertyMaterial, Points::PropertyCurvatureList, Spreadsheet::PropertySheet, Inspection::PropertyDistanceList, Part::PropertyShapeHistory, App::PropertyExpressionEngine, Points::PropertyNormalList, App::PropertyQuantityConstraint, Sketcher::PropertyConstraintList, Mesh::PropertyNormalList, Points::PropertyGreyValueList, App::PropertyFileIncluded, App::PropertyVector, Gui::AbstractSplitView, Part::PropertyTopoShapeList, Part::PropertyGeometryList, TechDraw::PropertyCosmeticVertexList, TechDraw::PropertyCosmeticEdgeList, TechDraw::PropertyGeomFormatList, Materials::PropertyMaterial, TechDraw::PropertyCenterLineList, App::PropertyFile, and App::PropertyQuantity.
Definition at line 112 of file BaseClass.cpp.
The documentation for this class was generated from the following files:
BaseClass.h
BaseClass.cpp