FreeCAD: MeshPartGui::Mesh2ShapeGmsh Class Reference
MeshPartGui::Mesh2ShapeGmsh Class Reference
#include <Tessellation.h>
Classes
class Private
Signals
void processed ()
Public Member Functions
Mesh2ShapeGmsh (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~Mesh2ShapeGmsh () override
void process (App::Document *doc, const std::list< App::SubObjectT > &)
Public Member Functions inherited from MeshGui::GmshWidget
GmshWidget (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~GmshWidget () override
void accept ()
void reject ()
Protected Member Functions
bool writeProject (QString &inpFile, QString &outFile) override
bool loadOutput () override
Protected Member Functions inherited from MeshGui::GmshWidget
void changeEvent (QEvent *e) override
int meshingAlgorithm () const
double getAngle () const
double getMaxSize () const
double getMinSize () const
Detailed Description
Non-modal dialog to mesh a shape.
Author
Werner Mayer
Definition at line 46 of file Tessellation.h.
Constructor & Destructor Documentation
Mesh2ShapeGmsh()
Mesh2ShapeGmsh::Mesh2ShapeGmsh (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Definition at line 545 of file Tessellation.cpp.
References App::Application::getTempFileName().
~Mesh2ShapeGmsh()
Mesh2ShapeGmsh::~Mesh2ShapeGmsh () override default
Member Function Documentation
loadOutput()
bool Mesh2ShapeGmsh::loadOutput () override protected virtual
Reimplemented from MeshGui::GmshWidget.
Definition at line 640 of file Tessellation.cpp.
References MeshGui::GmshWidget::accept(), Base::FileInfo::deleteFile(), toolbit-attributes::doc, Mesh::MeshObject::getKernel(), Mesh::MeshObject::harmonizeNormals(), App::DocumentObject::Label, MeshCore::MeshInput::LoadBinarySTL(), and App::PropertyString::setValue().
process()
void Mesh2ShapeGmsh::process (App::Document * doc, const std::list< App::SubObjectT > & objs)
Definition at line 556 of file Tessellation.cpp.
References MeshGui::GmshWidget::accept(), toolbit-attributes::doc, and replaceobj::objs.
processed
void MeshPartGui::Mesh2ShapeGmsh::processed () signal
Referenced by writeProject().
writeProject()
bool Mesh2ShapeGmsh::writeProject (QString & inpFile, QString & outFile) override protected virtual
Reimplemented from MeshGui::GmshWidget.
Definition at line 565 of file Tessellation.cpp.
References toolbit-attributes::doc, Part::TopoShape::exportBrep(), MeshGui::GmshWidget::getMaxSize(), MeshGui::GmshWidget::getMinSize(), App::DocumentObjectT::getObject(), App::PropertyString::getStrValue(), App::SubObjectT::getSubName(), Part::Feature::getTopoShape(), App::DocumentObject::Label, MeshGui::GmshWidget::meshingAlgorithm(), and processed().
The documentation for this class was generated from the following files:
Tessellation.h
Tessellation.cpp