FreeCAD: CAMTests.TestPathDressupHoldingTags.TestHoldingTags Class Reference
CAMTests.TestPathDressupHoldingTags.TestHoldingTags Class Reference
Public Member Functions
def test00 (self)
def test01 (self)
def test02 (self)
def test03 (self)
def test04 (self)
Public Member Functions inherited from CAMTests.PathTestUtils.PathTestBase
def assertRoughly (self, f1, f2, error=0.00001)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertPlacement (self, p1, p2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertArc (self, edge, pt1, pt2, direction="CW")
def assertCircle (self, edge, pt, r)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCommandEqual (self, c1, c2)
def assertEqualLocale (self, s1, s2)
def assertEdgeShapesMatch (self, e1, e2)
def assertPointsMatch (self, pts0, pts1)
def assertSuccessfulRecompute (self, doc, *objs, msg=None)
Detailed Description
Unit tests for the HoldingTags dressup.
Definition at line 30 of file TestPathDressupHoldingTags.py.
Member Function Documentation
test00()
def CAMTests.TestPathDressupHoldingTags.TestHoldingTags.test00 (self)
Check Tag origin.
Definition at line 33 of file TestPathDressupHoldingTags.py.
References CAMTests.PathTestUtils.PathTestBase.assertCoincide().
Referenced by CAMTests.TestPathToolController.TestPathToolController.test01().
test01()
def CAMTests.TestPathDressupHoldingTags.TestHoldingTags.test01 (self)
Verify solid for a 90 degree tag is a cylinder.
Definition at line 38 of file TestPathDressupHoldingTags.py.
References CAMTests.PathTestUtils.PathTestBase.assertCylinderAt().
test02()
def CAMTests.TestPathDressupHoldingTags.TestHoldingTags.test02 (self)
Verify trapezoidal tag has a cone shape with a lid.
Definition at line 46 of file TestPathDressupHoldingTags.py.
References CAMTests.PathTestUtils.PathTestBase.assertConeAt().
test03()
def CAMTests.TestPathDressupHoldingTags.TestHoldingTags.test03 (self)
Verify pointy cone shape of tag with pointy end if width, angle and height match up.
Definition at line 54 of file TestPathDressupHoldingTags.py.
References CAMTests.PathTestUtils.PathTestBase.assertConeAt().
test04()
def CAMTests.TestPathDressupHoldingTags.TestHoldingTags.test04 (self)
Verify height adjustment if tag isn't wide eough for angle.
Definition at line 62 of file TestPathDressupHoldingTags.py.
References CAMTests.PathTestUtils.PathTestBase.assertConeAt().
The documentation for this class was generated from the following file:
TestPathDressupHoldingTags.py