FreeCAD: Gui::Dialog::ParameterInt Class Reference
Gui::Dialog::ParameterInt Class Reference
#include <DlgParameterImp.h>
Public Member Functions
ParameterInt (QTreeWidget *parent, QString label1, long value, const Base::Reference< ParameterGrp > &hcGrp)
Constructor.
~ParameterInt () override
void changeValue () override
void appendToGroup () override
void removeFromGroup () override
Public Member Functions inherited from Gui::Dialog::ParameterValueItem
ParameterValueItem (QTreeWidget *parent, const Base::Reference< ParameterGrp > &hcGrp)
Constructor.
~ParameterValueItem () override
void setData (int column, int role, const QVariant &value) override
Protected Member Functions
void replace (const QString &oldName, const QString &newName) override
Additional Inherited Members
Protected Attributes inherited from Gui::Dialog::ParameterValueItem
Base::Reference< ParameterGrp > _hcGrp
Detailed Description
The ParameterInt class allows interaction with "integer" parameter leaves.
Author
Werner Mayer
Definition at line 324 of file DlgParameterImp.h.
Constructor & Destructor Documentation
ParameterInt()
ParameterInt::ParameterInt (QTreeWidget * parent, QString label1, long value, const Base::Reference< ParameterGrp > & hcGrp)
Constructor.
Definition at line 1182 of file DlgParameterImp.cpp.
References Gui::BitmapFactory().
~ParameterInt()
ParameterInt::~ParameterInt () override default
Member Function Documentation
appendToGroup()
void ParameterInt::appendToGroup () override virtual
Append this item as leaf to the parameter group.
Implements Gui::Dialog::ParameterValueItem.
Definition at line 1226 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::_hcGrp, and ParameterGrp::SetInt().
changeValue()
void ParameterInt::changeValue () override virtual
Opens an input dialog to change the value.
Implements Gui::Dialog::ParameterValueItem.
Definition at line 1196 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::_hcGrp, and ParameterGrp::SetInt().
removeFromGroup()
void ParameterInt::removeFromGroup () override virtual
Remove the leaf from the parameter group.
Implements Gui::Dialog::ParameterValueItem.
Definition at line 1214 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::_hcGrp, and ParameterGrp::RemoveInt().
replace()
void ParameterInt::replace (const QString & oldName, const QString & newName) override protected virtual
Replaces the name of the leaf from oldName to newName.
Implements Gui::Dialog::ParameterValueItem.
Definition at line 1219 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::_hcGrp, ParameterGrp::GetInt(), ParameterGrp::RemoveInt(), ParameterGrp::SetInt(), and toolbit-attributes::val.
The documentation for this class was generated from the following files:
DlgParameterImp.h
DlgParameterImp.cpp