FreeCAD: Sandbox::DocumentObjectProtector Class Reference
Sandbox::DocumentObjectProtector Class Reference
#include <DocumentProtector.h>
Public Member Functions
DocumentObjectProtector (App::DocumentObject *)
~DocumentObjectProtector ()
App::DocumentObject * getObject () const
bool setProperty (const std::string &name, const App::Property &p)
void execute (const AbstractCallable &)
void purgeTouched ()
Detailed Description
Definition at line 111 of file DocumentProtector.h.
Constructor & Destructor Documentation
DocumentObjectProtector()
DocumentObjectProtector::DocumentObjectProtector (App::DocumentObject * o)
Definition at line 295 of file DocumentProtector.cpp.
~DocumentObjectProtector()
DocumentObjectProtector::~DocumentObjectProtector ()
Definition at line 299 of file DocumentProtector.cpp.
Member Function Documentation
execute()
void DocumentObjectProtector::execute (const AbstractCallable & call)
Definition at line 324 of file DocumentProtector.cpp.
References Sandbox::DocumentReceiver::globalInstance(), and Sandbox::DocumentReceiver::postEventAndWait().
Referenced by FeaturePython.DistanceBolt::onChanged(), and Sandbox::DocumentTestThread::run().
getObject()
App::DocumentObject * DocumentObjectProtector::getObject () const
Definition at line 309 of file DocumentProtector.cpp.
Referenced by Sandbox::DocumentObjectProtectorPy::getattr(), Sandbox::DocumentObjectProtectorPy::getObject(), and Sandbox::DocumentObjectProtectorPy::setattr().
purgeTouched()
void DocumentObjectProtector::purgeTouched ()
Definition at line 330 of file DocumentProtector.cpp.
References Sandbox::DocumentReceiver::globalInstance(), and Sandbox::DocumentReceiver::postEventAndWait().
Referenced by Sandbox::DocumentObjectProtectorPy::purgeTouched().
setProperty()
bool DocumentObjectProtector::setProperty (const std::string & name, const App::Property & p)
Definition at line 314 of file DocumentProtector.cpp.
References App::ExtensionContainer::getPropertyByName(), Sandbox::DocumentReceiver::globalInstance(), and Sandbox::DocumentReceiver::postEventAndWait().
Referenced by Sandbox::DocumentTestThread::run(), and Sandbox::DocumentObjectProtectorPy::setattr().
The documentation for this class was generated from the following files:
DocumentProtector.h
DocumentProtector.cpp