FreeCAD: Gui::Gui::GestureNavigationStyle ::GestureState Class Reference
Gui::Gui::GestureNavigationStyle ::GestureState Class Reference
Public Types
using reactions = sc::custom_reaction< Gui::GestureNavigationStyle ::Event >
Public Member Functions
GestureState (my_context ctx)
virtual ~GestureState ()
sc::result react (const Gui::GestureNavigationStyle ::Event &ev)
Detailed Description
Definition at line 670 of file GestureNavigationStyle.cpp.
Member Typedef Documentation
reactions
using Gui::Gui::GestureNavigationStyle ::GestureState::reactions = sc::custom_reaction< Gui::GestureNavigationStyle ::Event>
Definition at line 673 of file GestureNavigationStyle.cpp.
Constructor & Destructor Documentation
GestureState()
Gui::Gui::GestureNavigationStyle ::GestureState::GestureState (my_context ctx) inline explicit
Definition at line 681 of file GestureNavigationStyle.cpp.
References Base::Console(), App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), Base::ConsoleSingleton::Log(), and Gui::NavigationStyle::PANNING.
~GestureState()
virtual Gui::Gui::GestureNavigationStyle ::GestureState::~GestureState () inline virtual
Definition at line 693 of file GestureNavigationStyle.cpp.
Member Function Documentation
react()
sc::result Gui::Gui::GestureNavigationStyle ::GestureState::react (const Gui::GestureNavigationStyle ::Event & ev) inline
Definition at line 700 of file GestureNavigationStyle.cpp.
References Base::Console(), SoGestureEvent::SbGsCanceled, SoGestureEvent::SbGSEnd, and Base::ConsoleSingleton::Warning().
The documentation for this class was generated from the following file:
GestureNavigationStyle.cpp