FreeCAD: App::PropertyMaterialList Class Reference
App::PropertyMaterialList Class Reference
#include <PropertyStandard.h>
Public Member Functions
PropertyMaterialList ()
~PropertyMaterialList () override
void setValue ()
void setValue (const std::vector< App::Material > &materials)
void setValues (const std::vector< App::Material > &newValues=std::vector< App::Material >()) override
void setValue (const Material &mat)
void setValue (int index, const Material &mat)
void setAmbientColor (const Color &col)
void setAmbientColor (float r, float g, float b, float a=1.0F)
void setAmbientColor (uint32_t rgba)
void setAmbientColor (int index, const Color &col)
void setAmbientColor (int index, float r, float g, float b, float a=1.0F)
void setAmbientColor (int index, uint32_t rgba)
void setDiffuseColor (const Color &col)
void setDiffuseColor (float r, float g, float b, float a=1.0F)
void setDiffuseColor (uint32_t rgba)
void setDiffuseColor (int index, const Color &col)
void setDiffuseColor (int index, float r, float g, float b, float a=1.0F)
void setDiffuseColor (int index, uint32_t rgba)
void setDiffuseColors (const std::vector< App::Color > &colors)
void setSpecularColor (const Color &col)
void setSpecularColor (float r, float g, float b, float a=1.0F)
void setSpecularColor (uint32_t rgba)
void setSpecularColor (int index, const Color &col)
void setSpecularColor (int index, float r, float g, float b, float a=1.0F)
void setSpecularColor (int index, uint32_t rgba)
void setEmissiveColor (const Color &col)
void setEmissiveColor (float r, float g, float b, float a=1.0F)
void setEmissiveColor (uint32_t rgba)
void setEmissiveColor (int index, const Color &col)
void setEmissiveColor (int index, float r, float g, float b, float a=1.0F)
void setEmissiveColor (int index, uint32_t rgba)
void setShininess (float)
void setShininess (int index, float)
void setTransparency (float)
void setTransparency (int index, float)
void setTransparencies (const std::vector< float > &transparencies)
const Color & getAmbientColor () const
const Color & getAmbientColor (int index) const
const Color & getDiffuseColor () const
const Color & getDiffuseColor (int index) const
std::vector< App::Color > getDiffuseColors () const
const Color & getSpecularColor () const
const Color & getSpecularColor (int index) const
const Color & getEmissiveColor () const
const Color & getEmissiveColor (int index) const
float getShininess () const
float getShininess (int index) const
float getTransparency () const
float getTransparency (int index) const
std::vector< float > getTransparencies () const
PyObject * getPyObject () override
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void SaveDocFile (Base::Writer &writer) const override
void RestoreDocFile (Base::Reader &reader) override
const char * getEditorName () const override
Get the class name of the associated property editor item.
Property * Copy () const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
unsigned int getMemSize () const override
Public Member Functions inherited from App::PropertyListsT< Material >
virtual void setSize (int newSize, const_reference def)
void setSize (int newSize) override
int getSize () const override
void setValue (const_reference value)
void setValue (const std::vector< Material > &newValues=std::vector< Material >())
const std::vector< Material > & getValues () const
const std::vector< Material > & getValue () const
const_reference operator[] (int idx) const
bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
void setPyObject (PyObject *value) override
virtual void set1Value (int index, const_reference value)
Public Member Functions inherited from App::PropertyLists
void setOrderRelevant (bool on)
bool isOrderRelevant () const
Public Member Functions inherited from App::Property
Property ()
~Property () override
const char * getName () const
bool hasName () const
std::string getFullName () const
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual void afterRestore ()
virtual void onContainerRestored ()
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
int64_t getID () const
virtual void beforeSave () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::PropertyListsBase
virtual int getSize () const =0
const std::set< int > & getTouchList () const
void clearTouchList ()
Protected Member Functions
Material getPyValue (PyObject *py) const override
Protected Member Functions inherited from App::PropertyListsT< Material >
void setPyValues (const std::vector< PyObject * > &vals, const std::vector< int > &indices) override
Protected Member Functions inherited from App::Property
virtual void hasSetValue ()
Gets called by all setValue() methods after the value has changed.
virtual void aboutToSetValue ()
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Protected Member Functions inherited from App::PropertyListsBase
void _setPyObject (PyObject *)
Protected Member Functions inherited from App::AtomicPropertyChangeInterface< PropertyListsT< Material, std::vector< Material >, PropertyLists > >
AtomicPropertyChangeInterface ()=default
Additional Inherited Members
Public Types inherited from App::PropertyListsT< Material >
using const_reference = typename std::vector< Material > ::const_reference
using list_type = std::vector< Material >
using parent_type = PropertyLists
using atomic_change = typename AtomicPropertyChangeInterface< PropertyListsT< Material, std::vector< Material >, PropertyLists > >::AtomicPropertyChange
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::PropertyListsT< Material >
friend atomic_change
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::PropertyListsT< Material >
std::vector< Material > _lValueList
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::PropertyListsBase
std::set< int > _touchList
Protected Attributes inherited from App::AtomicPropertyChangeInterface< PropertyListsT< Material, std::vector< Material >, PropertyLists > >
int signalCounter
bool hasChanged
Detailed Description
Material properties
Definition at line 1180 of file PropertyStandard.h.
Constructor & Destructor Documentation
PropertyMaterialList()
PropertyMaterialList::PropertyMaterialList ()
A constructor. A more elaborate description of the constructor.
Definition at line 2771 of file PropertyStandard.cpp.
~PropertyMaterialList()
PropertyMaterialList::~PropertyMaterialList () override default
A destructor. A more elaborate description of the destructor.
Member Function Documentation
Copy()
Property * PropertyMaterialList::Copy () const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 3407 of file PropertyStandard.cpp.
References buildPsets::p.
getAmbientColor() [1/2]
const Color & PropertyMaterialList::getAmbientColor () const
Definition at line 3159 of file PropertyStandard.cpp.
getAmbientColor() [2/2]
const Color & PropertyMaterialList::getAmbientColor (int index) const
Definition at line 3164 of file PropertyStandard.cpp.
getDiffuseColor() [1/2]
const Color & PropertyMaterialList::getDiffuseColor () const
Definition at line 3169 of file PropertyStandard.cpp.
Referenced by MeshGui::ViewProviderFace::attach(), MeshGui::ViewProviderMesh::deselectFacet(), PartGui::ViewProviderPartExt::getElementColors(), FemGui::ViewProviderFemConstraintOnBoundary::highlightReferences(), PartDesignGui::ViewProviderDressUp::highlightReferences(), MeshGui::ViewProviderMesh::highlightSegments(), MeshGui::ViewProviderMesh::highlightSelection(), MeshGui::ViewProviderMesh::onChanged(), FemGui::ViewProviderFemMesh::resetColorByElementId(), FemGui::ViewProviderFemMesh::resetColorByNodeId(), MeshGui::ViewProviderMesh::resetFacetTransparency(), FemGui::ViewProviderFemMesh::setColorByIdHelper(), MeshGui::ViewProviderMesh::setFacetTransparency(), MeshGui::ViewProviderMesh::tryColorPerVertexOrFace(), MeshGui::ViewProviderMesh::unhighlightSelection(), and FemGui::ViewProviderFemMesh::ViewProviderFemMesh().
getDiffuseColor() [2/2]
const Color & PropertyMaterialList::getDiffuseColor (int index) const
Definition at line 3174 of file PropertyStandard.cpp.
getDiffuseColors()
std::vector< App::Color > PropertyMaterialList::getDiffuseColors () const
Definition at line 3179 of file PropertyStandard.cpp.
Referenced by FemGui::ViewProviderFemConstraintOnBoundary::highlightReferences().
getEditorName()
const char * PropertyMaterialList::getEditorName () const override virtual
Get the class name of the associated property editor item.
Reimplemented from App::Property.
Definition at line 3399 of file PropertyStandard.cpp.
getEmissiveColor() [1/2]
const Color & PropertyMaterialList::getEmissiveColor () const
Definition at line 3199 of file PropertyStandard.cpp.
getEmissiveColor() [2/2]
const Color & PropertyMaterialList::getEmissiveColor (int index) const
Definition at line 3204 of file PropertyStandard.cpp.
getMemSize()
unsigned int PropertyMaterialList::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence
See also
Base::Persistence
Reimplemented from App::Property.
Definition at line 3419 of file PropertyStandard.cpp.
getPyObject()
PyObject * PropertyMaterialList::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 2793 of file PropertyStandard.cpp.
References SplineSurface::i, and Py::new_reference_to().
getPyValue()
Material PropertyMaterialList::getPyValue (PyObject * py) const override protected virtual
Implements App::PropertyListsT< Material >.
Definition at line 3239 of file PropertyStandard.cpp.
References Path.Log::error().
getShininess() [1/2]
float PropertyMaterialList::getShininess () const
Definition at line 3209 of file PropertyStandard.cpp.
getShininess() [2/2]
float PropertyMaterialList::getShininess (int index) const
Definition at line 3214 of file PropertyStandard.cpp.
getSpecularColor() [1/2]
const Color & PropertyMaterialList::getSpecularColor () const
Definition at line 3189 of file PropertyStandard.cpp.
getSpecularColor() [2/2]
const Color & PropertyMaterialList::getSpecularColor (int index) const
Definition at line 3194 of file PropertyStandard.cpp.
getTransparencies()
std::vector< float > PropertyMaterialList::getTransparencies () const
Definition at line 3229 of file PropertyStandard.cpp.
getTransparency() [1/2]
float PropertyMaterialList::getTransparency () const
Definition at line 3219 of file PropertyStandard.cpp.
Referenced by Gui::ViewProviderGeometryObject::onChanged(), and FemGui::ViewProviderFemMesh::onChanged().
getTransparency() [2/2]
float PropertyMaterialList::getTransparency (int index) const
Definition at line 3224 of file PropertyStandard.cpp.
Paste()
void PropertyMaterialList::Paste (const Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 3414 of file PropertyStandard.cpp.
Restore()
void PropertyMaterialList::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 3260 of file PropertyStandard.cpp.
References DrawingExample::file, and TechDrawTools.TaskFillTemplateFields::reader.
RestoreDocFile()
void PropertyMaterialList::RestoreDocFile (Base::Reader &) override virtual
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data. Again you have to apply for the call of this method in the Restore() call:
void PropertyMeshKernel::Restore(Base::XMLReader &reader)
{
  reader.readElement("Mesh");
  std::string file (reader.getAttribute("file") );
  if(file == "")
  {
    // read XML
    MeshCore::MeshDocXML restorer(*_pcMesh);
    restorer.Restore(reader);
  }else{
    // initiate a file read
    reader.addFile(file.c_str(),this);
 }
}
After you issued the reader.addFile() your RestoreDocFile() is called:
void PropertyMeshKernel::RestoreDocFile(Base::Reader &reader)
{
    _pcMesh->Read( reader );
}
See also
Base::Reader,Base::XMLReader
Reimplemented from Base::Persistence.
Definition at line 3305 of file PropertyStandard.cpp.
References src.Mod.AddonManager.NetworkManager::count, TechDrawTools.TaskFillTemplateFields::reader, Path.Post.scripts.refactored_centroid_post::str, and Dice3DS::version.
Save()
void PropertyMaterialList::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 3251 of file PropertyStandard.cpp.
References Base::Writer::addFile(), Base::Writer::ind(), Base::Writer::isForceXML(), and Base::Writer::Stream().
SaveDocFile()
void PropertyMaterialList::SaveDocFile (Base::Writer &) const override virtual
This method is used to save large amounts of data to a binary file. Sometimes it makes no sense to write property data as XML. In case the amount of data is too big or the data type has a more effective way to save itself. In this cases it is possible to write the data in a separate file inside the document archive. In case you want do so you have to re-implement SaveDocFile(). First, you have to inform the framework in Save() that you want do so. Here an example from the Mesh module which can save a (pontetionaly big) triangle mesh:
void PropertyMeshKernel::Save (Base::Writer &writer) const
{
  if (writer.isForceXML())
  {
    writer << writer.ind() << "<Mesh>" << std::endl;
    MeshCore::MeshDocXML saver(*_pcMesh);
    saver.Save(writer);
  }else{
   writer << writer.ind() << "<Mesh file=\"" << writer.addFile("MeshKernel.bms", this) <<
"\"/>" << std::endl;
}
The writer.isForceXML() is an indication to force you to write XML. Regardless of size and effectiveness. The second part informs the Base::writer through writer.addFile("MeshKernel.bms", this) that this object wants to write a file with the given name. The method addFile() returns a unique name that then is written in the XML stream. This allows your RestoreDocFile() method to identify and read the file again. Later your SaveDocFile() method is called as many times as you issued the addFile() call:
 void
PropertyMeshKernel::SaveDocFile (Base::Writer &writer) const
{
    _pcMesh->Write( writer );
}
In this method you can simply stream your content to the file (Base::Writer inheriting from ostream).
Reimplemented from Base::Persistence.
Definition at line 3276 of file PropertyStandard.cpp.
References Path.Post.scripts.refactored_centroid_post::str, and Base::Writer::Stream().
setAmbientColor() [1/6]
void PropertyMaterialList::setAmbientColor (const Color & col)
Definition at line 2857 of file PropertyStandard.cpp.
setAmbientColor() [2/6]
void PropertyMaterialList::setAmbientColor (float r, float g, float b, float a = 1.0F)
Definition at line 2867 of file PropertyStandard.cpp.
References a, SCL.SimpleDataTypes::b, and toolbit-attributes::g.
setAmbientColor() [3/6]
void PropertyMaterialList::setAmbientColor (int index, const Color & col)
Definition at line 2887 of file PropertyStandard.cpp.
setAmbientColor() [4/6]
void PropertyMaterialList::setAmbientColor (int index, float r, float g, float b, float a = 1.0F)
Definition at line 2897 of file PropertyStandard.cpp.
References a, SCL.SimpleDataTypes::b, and toolbit-attributes::g.
setAmbientColor() [5/6]
void PropertyMaterialList::setAmbientColor (int index, uint32_t rgba)
Definition at line 2907 of file PropertyStandard.cpp.
setAmbientColor() [6/6]
void PropertyMaterialList::setAmbientColor (uint32_t rgba)
Definition at line 2877 of file PropertyStandard.cpp.
setDiffuseColor() [1/6]
void PropertyMaterialList::setDiffuseColor (const Color & col)
Definition at line 2917 of file PropertyStandard.cpp.
Referenced by Gui::ViewProviderLine::attach(), Gui::ViewProviderPlane::attach(), FemGui::ViewProviderFemConstraint::handleChangedPropertyName(), Gui::ViewProviderGeometryObject::handleChangedPropertyName(), PartDesignGui::ViewProviderSubShapeBinder::onChanged(), PROPERTY_SOURCE(), FemGui::ViewProviderFemConstraintFluidBoundary::updateData(), PartDesignGui::ViewProviderDatum::ViewProviderDatum(), FemGui::ViewProviderFemMesh::ViewProviderFemMesh(), and Gui::ViewProviderImagePlane::ViewProviderImagePlane().
setDiffuseColor() [2/6]
void PropertyMaterialList::setDiffuseColor (float r, float g, float b, float a = 1.0F)
Definition at line 2927 of file PropertyStandard.cpp.
References a, SCL.SimpleDataTypes::b, and toolbit-attributes::g.
setDiffuseColor() [3/6]
void PropertyMaterialList::setDiffuseColor (int index, const Color & col)
Definition at line 2947 of file PropertyStandard.cpp.
setDiffuseColor() [4/6]
void PropertyMaterialList::setDiffuseColor (int index, float r, float g, float b, float a = 1.0F)
Definition at line 2957 of file PropertyStandard.cpp.
References a, SCL.SimpleDataTypes::b, and toolbit-attributes::g.
setDiffuseColor() [5/6]
void PropertyMaterialList::setDiffuseColor (int index, uint32_t rgba)
Definition at line 2967 of file PropertyStandard.cpp.
setDiffuseColor() [6/6]
void PropertyMaterialList::setDiffuseColor (uint32_t rgba)
Definition at line 2937 of file PropertyStandard.cpp.
setDiffuseColors()
void PropertyMaterialList::setDiffuseColors (const std::vector< App::Color > & colors)
Definition at line 2977 of file PropertyStandard.cpp.
References importers.importIFCmulticore::colors, and SplineSurface::i.
Referenced by FemGui::ViewProviderFemConstraintOnBoundary::highlightReferences(), and PartGui::ViewProviderPartExt::onChanged().
setEmissiveColor() [1/6]
void PropertyMaterialList::setEmissiveColor (const Color & col)
Definition at line 3048 of file PropertyStandard.cpp.
setEmissiveColor() [2/6]
void PropertyMaterialList::setEmissiveColor (float r, float g, float b, float a = 1.0F)
Definition at line 3058 of file PropertyStandard.cpp.
References a, SCL.SimpleDataTypes::b, and toolbit-attributes::g.
setEmissiveColor() [3/6]
void PropertyMaterialList::setEmissiveColor (int index, const Color & col)
Definition at line 3078 of file PropertyStandard.cpp.
setEmissiveColor() [4/6]
void PropertyMaterialList::setEmissiveColor (int index, float r, float g, float b, float a = 1.0F)
Definition at line 3088 of file PropertyStandard.cpp.
References a, SCL.SimpleDataTypes::b, and toolbit-attributes::g.
setEmissiveColor() [5/6]
void PropertyMaterialList::setEmissiveColor (int index, uint32_t rgba)
Definition at line 3098 of file PropertyStandard.cpp.
setEmissiveColor() [6/6]
void PropertyMaterialList::setEmissiveColor (uint32_t rgba)
Definition at line 3068 of file PropertyStandard.cpp.
setShininess() [1/2]
void PropertyMaterialList::setShininess (float val)
Definition at line 3108 of file PropertyStandard.cpp.
References toolbit-attributes::val.
setShininess() [2/2]
void PropertyMaterialList::setShininess (int index, float val)
Definition at line 3118 of file PropertyStandard.cpp.
References toolbit-attributes::val.
setSpecularColor() [1/6]
void PropertyMaterialList::setSpecularColor (const Color & col)
Definition at line 2988 of file PropertyStandard.cpp.
setSpecularColor() [2/6]
void PropertyMaterialList::setSpecularColor (float r, float g, float b, float a = 1.0F)
Definition at line 2998 of file PropertyStandard.cpp.
References a, SCL.SimpleDataTypes::b, and toolbit-attributes::g.
setSpecularColor() [3/6]
void PropertyMaterialList::setSpecularColor (int index, const Color & col)
Definition at line 3018 of file PropertyStandard.cpp.
setSpecularColor() [4/6]
void PropertyMaterialList::setSpecularColor (int index, float r, float g, float b, float a = 1.0F)
Definition at line 3028 of file PropertyStandard.cpp.
References a, SCL.SimpleDataTypes::b, and toolbit-attributes::g.
setSpecularColor() [5/6]
void PropertyMaterialList::setSpecularColor (int index, uint32_t rgba)
Definition at line 3038 of file PropertyStandard.cpp.
setSpecularColor() [6/6]
void PropertyMaterialList::setSpecularColor (uint32_t rgba)
Definition at line 3008 of file PropertyStandard.cpp.
setTransparencies()
void PropertyMaterialList::setTransparencies (const std::vector< float > & transparencies)
Definition at line 3148 of file PropertyStandard.cpp.
References SplineSurface::i.
Referenced by PartGui::ViewProviderPartExt::onChanged().
setTransparency() [1/2]
void PropertyMaterialList::setTransparency (float val)
Definition at line 3128 of file PropertyStandard.cpp.
References toolbit-attributes::val.
Referenced by Gui::ViewProviderGeometryObject::onChanged(), and PartGui::ViewProviderPartExt::onChanged().
setTransparency() [2/2]
void PropertyMaterialList::setTransparency (int index, float val)
Definition at line 3138 of file PropertyStandard.cpp.
References toolbit-attributes::val.
setValue() [1/4]
void PropertyMaterialList::setValue ()
Definition at line 2831 of file PropertyStandard.cpp.
Referenced by Gui::ViewProviderGeometryObject::handleChangedPropertyName(), Gui::ViewProviderGeometryObject::updateData(), and Gui::ViewProviderLink::updateDataPrivate().
setValue() [2/4]
void PropertyMaterialList::setValue (const Material & mat)
Definition at line 2837 of file PropertyStandard.cpp.
setValue() [3/4]
void App::PropertyMaterialList::setValue (const std::vector< App::Material > & materials) inline
Definition at line 1198 of file PropertyStandard.h.
References importers.importIFCmulticore::materials, and App::PropertyListsT< T, ListT, ParentT >::setValue().
setValue() [4/4]
void PropertyMaterialList::setValue (int index, const Material & mat)
Definition at line 2847 of file PropertyStandard.cpp.
setValues()
void PropertyMaterialList::setValues (const std::vector< App::Material > & newValues = std::vector<App::Material>()) override virtual
Reimplemented from App::PropertyListsT< Material >.
Definition at line 2781 of file PropertyStandard.cpp.
References App::PropertyListsT< T, ListT, ParentT >::setValues().
Referenced by PartDesignGui::ViewProviderShapeBinder::highlightReferences(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle(), PartGui::ViewProviderMultiFuse::updateData(), PartGui::ViewProviderBoolean::updateData(), PartGui::ViewProviderCompound::updateData(), PartGui::ViewProviderFillet::updateData(), PartGui::ViewProviderMultiCommon::updateData(), and PartGui::ViewProviderChamfer::updateData().
The documentation for this class was generated from the following files:
PropertyStandard.h
PropertyStandard.cpp