FreeCAD: Path.Main.Job Namespace Reference
Path.Main.Job Namespace Reference
Classes
class JobTemplate
class NotificationClass
class ObjectJob
Functions
def isResourceClone (obj, propLink, resourceName)
def createResourceClone (obj, orig, name, icon)
def createModelResourceClone (obj, orig)
def Instances ()
def Create (name, base, templateFile=None)
Variables
Draft
translate
Notification
Function Documentation
Create()
def Path.Main.Job.Create (name, base, templateFile = None)
Create(name, base, templateFile=None) ... creates a new job and all it's resources.
If a template file is specified the new job is initialized with the values from the template.
Definition at line 808 of file Job.py.
createModelResourceClone()
def Path.Main.Job.createModelResourceClone (obj, orig)
Definition at line 93 of file Job.py.
References Path.Main.Job.createResourceClone().
Referenced by Path.Main.Job.ObjectJob.setupBaseModel().
createResourceClone()
def Path.Main.Job.createResourceClone (obj, orig, name, icon)
Definition at line 78 of file Job.py.
References Path.Base.Gui.IconViewProvider.Attach().
Referenced by Path.Main.Job.createModelResourceClone().
Instances()
def Path.Main.Job.Instances ()
Instances() ... Return all Jobs in the current active document.
Definition at line 797 of file Job.py.
isResourceClone()
def Path.Main.Job.isResourceClone (obj, propLink, resourceName)
Definition at line 70 of file Job.py.
Referenced by Path.Main.Job.ObjectJob.baseObject(), Path.Main.Job.ObjectJob.removeBase(), and Path.Main.Job.ObjectJob.resourceClone().
Variable Documentation
Draft
Path.Main.Job.Draft
Definition at line 39 of file Job.py.
Notification
Path.Main.Job.Notification
Definition at line 101 of file Job.py.
translate
Path.Main.Job.translate
Definition at line 48 of file Job.py.