FreeCAD: nativeifc.ifc_tree Namespace Reference
nativeifc.ifc_tree Namespace Reference
Functions
def get_geometry_tree (element, prefix="")
def print_geometry_tree (element)
def show_geometry_tree (element)
def isfloat (s)
def show_properties (current, previous)
def edit_property (item)
Variables
int TAB = 2
Function Documentation
edit_property()
def nativeifc.ifc_tree.edit_property (item)
Edits the value of a property
Definition at line 217 of file ifc_tree.py.
References Init.parent, and Path.Post.scripts.refactored_centroid_post.str.
get_geometry_tree()
def nativeifc.ifc_tree.get_geometry_tree (element, prefix = "")
Returns a list of elements representing an object's representation
Definition at line 31 of file ifc_tree.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by nativeifc.ifc_tree.print_geometry_tree(), and nativeifc.ifc_tree.show_geometry_tree().
isfloat()
def nativeifc.ifc_tree.isfloat (s)
Tells if the given string is a number
Definition at line 134 of file ifc_tree.py.
Referenced by nativeifc.ifc_tree.show_geometry_tree().
print_geometry_tree()
def nativeifc.ifc_tree.print_geometry_tree (element)
Same as get_geometry_tree but printed
Definition at line 70 of file ifc_tree.py.
References nativeifc.ifc_tree.get_geometry_tree().
show_geometry_tree()
def nativeifc.ifc_tree.show_geometry_tree (element)
Same as get_geometry_tree but in a Qt dialog
Definition at line 77 of file ifc_tree.py.
References nativeifc.ifc_tree.get_geometry_tree(), and nativeifc.ifc_tree.isfloat().
show_properties()
def nativeifc.ifc_tree.show_properties (current, previous)
Displays object properties
Definition at line 145 of file ifc_tree.py.
References Path.Post.scripts.refactored_centroid_post.str.
Variable Documentation
TAB
int nativeifc.ifc_tree.TAB = 2
Definition at line 28 of file ifc_tree.py.
Referenced by SIM::Coin3D::Quarter::KeyboardP.initKeyMap().