FreeCAD: Materials::Material2DArray Class Reference
Materials::Material2DArray Class Reference
#include <MaterialValue.h>
Public Member Functions
Material2DArray ()
Material2DArray (const Material2DArray &other)
~Material2DArray () override=default
Material2DArray & operator= (const Material2DArray &other)
bool isNull () const override
const QList< std::shared_ptr< QList< QVariant > > > & getArray () const
void validateRow (int row) const
void validateColumn (int column) const
std::shared_ptr< QList< QVariant > > getRow (int row) const
std::shared_ptr< QList< QVariant > > getRow (int row)
int rows () const
int columns () const
void setColumns (int size)
void addRow (const std::shared_ptr< QList< QVariant >> &row)
void insertRow (int index, const std::shared_ptr< QList< QVariant >> &row)
void deleteRow (int row)
void setValue (int row, int column, const QVariant &value)
QVariant getValue (int row, int column) const
QString getYAMLString () const override
Public Member Functions inherited from Materials::MaterialValue
MaterialValue ()
MaterialValue (const MaterialValue &other)
MaterialValue (ValueType type)
virtual ~MaterialValue ()=default
MaterialValue & operator= (const MaterialValue &other)
virtual bool operator== (const MaterialValue &other) const
bool operator!= (const MaterialValue &other) const
ValueType getType () const
QVariant getValue () const
QList< QVariant > getList ()
const QList< QVariant > getList () const
virtual const QVariant getValueAt (const QVariant &value) const
void setValue (const QVariant &value)
void setList (const QList< QVariant > &value)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
void deepCopy (const Material2DArray &other)
Protected Member Functions inherited from Materials::MaterialValue
MaterialValue (ValueType type, ValueType inherited)
void setType (ValueType type)
void setInitialValue (ValueType inherited)
QString getYAMLStringImage () const
QString getYAMLStringList () const
QString getYAMLStringImageList () const
QString getYAMLStringMultiLine () const
Protected Attributes
QList< std::shared_ptr< QList< QVariant > > > _rows
int _columns
Protected Attributes inherited from Materials::MaterialValue
ValueType _valueType
QVariant _value
Additional Inherited Members
Public Types inherited from Materials::MaterialValue
enum ValueType {
None = 0, String = 1, Boolean = 2, Integer = 3,
Float = 4, Quantity = 5, Distribution = 6, List = 7,
Array2D = 8, Array3D = 9, Color = 10, Image = 11,
File = 12, URL = 13, MultiLineString = 14, FileList = 15,
ImageList = 16, SVG
}
Static Public Member Functions inherited from Materials::MaterialValue
static QString escapeString (const QString &source)
static ValueType mapType (const QString &stringType)
static const Base::QuantityFormat getQuantityFormat ()
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Attributes inherited from Materials::MaterialValue
static const int PRECISION = 6
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 155 of file MaterialValue.h.
Constructor & Destructor Documentation
Material2DArray() [1/2]
Material2DArray::Material2DArray ()
Definition at line 323 of file MaterialValue.cpp.
Material2DArray() [2/2]
Material2DArray::Material2DArray (const Material2DArray & other)
Definition at line 331 of file MaterialValue.cpp.
References deepCopy().
~Material2DArray()
Materials::Material2DArray::~Material2DArray () override default
Member Function Documentation
addRow()
void Material2DArray::addRow (const std::shared_ptr< QList< QVariant >> & row)
Definition at line 408 of file MaterialValue.cpp.
References _rows.
Referenced by deepCopy().
columns()
int Materials::Material2DArray::columns () const inline
Definition at line 182 of file MaterialValue.h.
Referenced by validateColumn().
deepCopy()
void Material2DArray::deepCopy (const Material2DArray & other) protected
Definition at line 352 of file MaterialValue.cpp.
References _rows, and addRow().
Referenced by Material2DArray(), and operator=().
deleteRow()
void Material2DArray::deleteRow (int row)
Definition at line 418 of file MaterialValue.cpp.
References _rows.
getArray()
const QList<std::shared_ptr<QList<QVariant> > >& Materials::Material2DArray::getArray () const inline
Definition at line 168 of file MaterialValue.h.
getRow() [1/2]
std::shared_ptr< QList< QVariant > > Material2DArray::getRow (int row)
Definition at line 396 of file MaterialValue.cpp.
References _rows, and validateRow().
getRow() [2/2]
std::shared_ptr< QList< QVariant > > Material2DArray::getRow (int row) const
Definition at line 384 of file MaterialValue.cpp.
References _rows, and validateRow().
Referenced by getValue(), and setValue().
getValue()
QVariant Material2DArray::getValue (int row, int column) const
Definition at line 440 of file MaterialValue.cpp.
References App::ExpressionParser::column, getRow(), toolbit-attributes::val, and validateColumn().
getYAMLString()
QString Material2DArray::getYAMLString () const override virtual
Reimplemented from Materials::MaterialValue.
Definition at line 469 of file MaterialValue.cpp.
References _rows, App::ExpressionParser::column, and isNull().
insertRow()
void Material2DArray::insertRow (int index, const std::shared_ptr< QList< QVariant >> & row)
Definition at line 413 of file MaterialValue.cpp.
References _rows.
isNull()
bool Material2DArray::isNull () const override virtual
Reimplemented from Materials::MaterialValue.
Definition at line 365 of file MaterialValue.cpp.
References rows().
Referenced by getYAMLString().
operator=()
Material2DArray & Material2DArray::operator= (const Material2DArray & other)
Definition at line 338 of file MaterialValue.cpp.
References _columns, deepCopy(), and Materials::MaterialValue::operator=().
rows()
int Materials::Material2DArray::rows () const inline
Definition at line 178 of file MaterialValue.h.
Referenced by isNull(), and validateRow().
setColumns()
void Materials::Material2DArray::setColumns (int size) inline
Definition at line 186 of file MaterialValue.h.
setValue()
void Material2DArray::setValue (int row, int column, const QVariant & value)
Definition at line 426 of file MaterialValue.cpp.
References App::ExpressionParser::column, getRow(), toolbit-attributes::val, validateColumn(), and validateRow().
validateColumn()
void Material2DArray::validateColumn (int column) const
Definition at line 377 of file MaterialValue.cpp.
References columns().
Referenced by getValue(), and setValue().
validateRow()
void Material2DArray::validateRow (int row) const
Definition at line 370 of file MaterialValue.cpp.
References rows().
Referenced by getRow(), and setValue().
Member Data Documentation
_columns
int Materials::Material2DArray::_columns protected
Definition at line 203 of file MaterialValue.h.
Referenced by operator=().
_rows
QList<std::shared_ptr<QList<QVariant> > > Materials::Material2DArray::_rows protected
Definition at line 202 of file MaterialValue.h.
Referenced by addRow(), deepCopy(), deleteRow(), getRow(), getYAMLString(), and insertRow().
The documentation for this class was generated from the following files:
MaterialValue.h
MaterialValue.cpp