FreeCAD: PartGui::LinePrimitive Class Reference
PartGui::LinePrimitive Class Reference
#include <DlgPrimitives.h>
Public Member Functions
LinePrimitive (std::shared_ptr< Ui_DlgPrimitives > ui, Part::Line *feature=nullptr)
const char * getDefaultName () const override
QString create (const QString &objectName, const QString &placement) const override
QString change (const QString &objectName, const QString &placement) const override
void changeValue (QObject *) override
Public Member Functions inherited from PartGui::AbstractPrimitive
AbstractPrimitive (Part::Primitive *feature=nullptr)
~AbstractPrimitive () override=default
bool hasValidPrimitive () const
Additional Inherited Members
Protected Member Functions inherited from PartGui::AbstractPrimitive
void connectSignalMapper (QSignalMapper *mapper)
Protected Attributes inherited from PartGui::AbstractPrimitive
App::DocumentObjectWeakPtrT featurePtr
Detailed Description
Definition at line 352 of file DlgPrimitives.h.
Constructor & Destructor Documentation
LinePrimitive()
LinePrimitive::LinePrimitive (std::shared_ptr< Ui_DlgPrimitives > ui, Part::Line * feature = nullptr)
Definition at line 1572 of file DlgPrimitives.cpp.
References PartGui::connectMapSignalMapper(), PartGui::AbstractPrimitive::connectSignalMapper(), App::PropertyQuantity::getQuantityValue(), Gui::QuantitySpinBox::valueChanged(), Part::Line::X1, Part::Line::X2, Part::Line::Y1, Part::Line::Y2, Part::Line::Z1, and Part::Line::Z2.
Member Function Documentation
change()
QString LinePrimitive::change (const QString & objectName, const QString & placement) const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 1642 of file DlgPrimitives.cpp.
References PartGui::safeQuantityQString().
changeValue()
void LinePrimitive::changeValue (QObject * widget) override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 1662 of file DlgPrimitives.cpp.
References App::DocumentObjectWeakPtrT::expired(), PartGui::AbstractPrimitive::featurePtr, App::DocumentObjectWeakPtrT::get(), App::DocumentObject::recomputeFeature(), App::PropertyQuantity::setValue(), Part::Line::X1, Part::Line::X2, Part::Line::Y1, Part::Line::Y2, Part::Line::Z1, and Part::Line::Z2.
create()
QString LinePrimitive::create (const QString & objectName, const QString & placement) const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 1619 of file DlgPrimitives.cpp.
References PartGui::safeQuantityQString().
getDefaultName()
const char * LinePrimitive::getDefaultName () const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 1614 of file DlgPrimitives.cpp.
The documentation for this class was generated from the following files:
DlgPrimitives.h
DlgPrimitives.cpp