FreeCAD: TechDraw Namespace Reference
TechDraw Namespace Reference
a class to the projection of shapes, removal/identifying hidden lines and
Namespaces
CommandHelpers
Classes
class anglePoints
class ANSILineName
class AOC
class AOE
class arcPoints
class areaPoint
class ArrowPropEnum
class ASMELineName
class BalloonPropEnum
class BaseGeom
class BezierSegment
struct BreakListEntry
class BSpline
class CenterLine
class ChangePoint
class Circle
class CosmeticEdge
class CosmeticExtension
class CosmeticVertex
class DashSpec
class DimensionAutoCorrect
class DimensionFormatter
class DrawBrokenView
class DrawComplexSection
class DrawDimHelper
Additional functions for working with Dimensions.
class DrawGeomHatch
class DrawHatch
class DrawLeaderLine
class DrawPage
class DrawParametricTemplate
class DrawProjectSplit
class DrawProjGroup
class DrawProjGroupItem
class DrawRichAnno
class DrawSVGTemplate
class DrawTemplate
class DrawTile
class DrawTileWeld
class DrawUtil
Convenient utility functions for TechDraw Module.
class DrawView
class DrawViewAnnotation
class DrawViewArch
class DrawViewBalloon
class DrawViewClip
class DrawViewCollection
class DrawViewDetail
class DrawViewDimension
class DrawViewDimExtent
class DrawViewDraft
class DrawViewImage
class DrawViewMulti
class DrawViewPart
class DrawViewSection
class DrawViewSpreadsheet
class DrawViewSymbol
class DrawWeldSymbol
class DXFOutput
struct EdgePoints
class edgeSortItem
class edgeVectorEntry
class edgeVisitor
class EdgeWalker
class Ellipse
class embedItem
class ewWire
class ewWireList
class Face
Simple Collection of geometric features based on BaseGeom inherited classes in order.
class FeatureProjection
class Generic
class GeometryMatcher
class GeometryObject
class GeometryUtils
Encapsulates some useful static methods.
class GeomFormat
class incidenceItem
class ISOLineName
class LandmarkDimension
class LineFormat
general purpose line format specifier
class LineGenerator
class LineGroup
class LineName
common definitions for line numbers, names and lineicon names
class LineSet
a LineSet is all the generated edges for 1 PATLineSpec for 1 Face
class MattingPropEnum
class Module
class PATLineSpec
PATLineSpec is the result of parsing a singleline from PAT file into accessible parameters.
struct PieceLimitEntry
class pointPair
class Preferences
class ProjectionAlgos
class PropertyCenterLineList
class PropertyCosmeticEdgeList
class PropertyCosmeticVertexList
class PropertyGeomFormatList
class ReferenceEntry
class ShapeExtractor
class ShapeUtils
struct splitPoint
class SVGOutput
class TechDrawOutput
class Vertex
class WalkerEdge
class Wire
Simple Collection of geometric features based on BaseGeom inherited classes in order.
class XMLQuery
Typedefs
using CosmeticExtensionPython = App::ExtensionPythonT< CosmeticExtension >
using ReferenceVector = std::vector< ReferenceEntry >
using BreakList = std::vector< BreakListEntry >
using PieceLimitList = std::vector< PieceLimitEntry >
using DrawBrokenViewPython = App::FeaturePythonT< DrawBrokenView >
using DrawComplexSectionPython = App::FeaturePythonT< DrawComplexSection >
using DrawGeomHatchPython = App::FeaturePythonT< DrawGeomHatch >
using DrawHatchPython = App::FeaturePythonT< DrawHatch >
using DrawLeaderLinePython = App::FeaturePythonT< DrawLeaderLine >
using DrawPagePython = App::FeaturePythonT< DrawPage >
using DrawParametricTemplatePython = App::FeaturePythonT< DrawParametricTemplate >
using GeometryObjectPtr = std::shared_ptr< GeometryObject >
using vertexMap = std::map< Base::Vector3d, int, DrawUtil::vectorLessType >
using DrawProjectSplitPython = App::FeaturePythonT< DrawProjectSplit >
using DrawRichAnnoPython = App::FeaturePythonT< DrawRichAnno >
using DrawSVGTemplatePython = App::FeaturePythonT< DrawSVGTemplate >
using DrawTemplatePython = App::FeaturePythonT< DrawTemplate >
using DrawTilePython = App::FeaturePythonT< DrawTile >
using DrawTileWeldPython = App::FeaturePythonT< DrawTileWeld >
using DrawViewPython = App::FeaturePythonT< DrawView >
using DrawViewAnnotationPython = App::FeaturePythonT< DrawViewAnnotation >
using DrawViewClipPython = App::FeaturePythonT< DrawViewClip >
using DrawViewDetailPython = App::FeaturePythonT< DrawViewDetail >
using DrawViewDraftPython = App::FeaturePythonT< DrawViewDraft >
using DrawViewImagePython = App::FeaturePythonT< DrawViewImage >
using DrawViewMultiPython = App::FeaturePythonT< DrawViewMulti >
using DrawViewPartPython = App::FeaturePythonT< DrawViewPart >
using ChangePointVector = std::vector< ChangePoint >
using DrawViewSectionPython = App::FeaturePythonT< DrawViewSection >
using DrawViewSpreadsheetPython = App::FeaturePythonT< DrawViewSpreadsheet >
using DrawViewSymbolPython = App::FeaturePythonT< DrawViewSymbol >
using DrawWeldSymbolPython = App::FeaturePythonT< DrawWeldSymbol >
using graph = boost::adjacency_list< boost::vecS, boost::vecS, boost::bidirectionalS, boost::property< boost::vertex_index_t, int >, boost::property< boost::edge_index_t, int > >
using vertex_t = boost::graph_traits< graph >::vertex_descriptor
using edge_t = boost::graph_traits< graph >::edge_descriptor
using planar_embedding_storage_t = std::vector< std::vector< edge_t > >
using planar_embedding_t = boost::iterator_property_map< planar_embedding_storage_t::iterator, boost::property_map< graph, boost::vertex_index_t >::type >
using BaseGeomPtr = std::shared_ptr< BaseGeom >
using CirclePtr = std::shared_ptr< Circle >
using AOCPtr = std::shared_ptr< AOC >
using EllipsePtr = std::shared_ptr< Ellipse >
using AOEPtr = std::shared_ptr< AOE >
using BezierSegmentPtr = std::shared_ptr< BezierSegment >
using BSplinePtr = std::shared_ptr< BSpline >
using GenericPtr = std::shared_ptr< Generic >
using BaseGeomPtrVector = std::vector< BaseGeomPtr >
using WirePtr = std::shared_ptr< Wire >
using FacePtr = std::shared_ptr< Face >
using VertexPtr = std::shared_ptr< Vertex >
Enumerations
enum ArrowType {
FILLED_ARROW = 0, OPEN_ARROW, TICK, DOT,
OPEN_CIRCLE, FORK, FILLED_TRIANGLE, NONE
}
enum BalloonType {
Circular = 0, None, Triangle, Inspection,
Hexagon, Square, Rectangle, Line
}
enum ProjItemType {
Front, Left, Right, Rear,
Top, Bottom, FrontTopLeft, FrontTopRight,
FrontBottomLeft, FrontBottomRight
}
enum ExtractionType { Plain, WithHidden, WithSmooth }
enum edgeClass {
ecNONE, ecUVISO, ecOUTLINE, ecSMOOTH,
ecSEAM, ecHARD
}
enum GeomType {
NOTDEF, CIRCLE, ARCOFCIRCLE, ELLIPSE,
ARCOFELLIPSE, BEZIER, BSPLINE, GENERIC
}
enum SourceType { GEOM, COSEDGE, CENTERLINE }
enum DimensionGeometryEnum {
isInvalid, isHorizontal, isVertical, isDiagonal,
isCircle, isEllipse, isBSplineCircle, isBSpline,
isAngle, isAngle3Pt, isMultiEdge, isZLimited,
isHybrid, isFace, isViewReference
}
Functions
PyObject * initModule ()
template<typename OutputIt >
void copy (Py::Dict sourceRange, OutputIt targetIt)
const TopoDS_Shape & build3dCurves (const TopoDS_Shape &shape)
DrawViewPart * getReferencesFromSelection (ReferenceVector &references2d, ReferenceVector &references3d)
DimensionGeometryType validateDimSelection (const ReferenceVector &references, const StringVector &acceptableGeometry, const std::vector< int > &minimumCounts, const std::vector< DimensionGeometryType > &acceptableDimensionGeometrys)
verify that the proposed references contains valid geometries from a 2d DrawViewPart.
DimensionGeometryType validateDimSelection3d (DrawViewPart *dvp, const ReferenceVector &references, const StringVector &acceptableGeometry, const std::vector< int > &minimumCounts, const std::vector< DimensionGeometryType > &acceptableDimensionGeometrys)
verify that the proposed references contains valid geometries from non-TechDraw objects.
bool validateSubnameList (StringVector subNames, GeometrySet acceptableGeometrySet)
DimensionGeometryType getGeometryConfiguration (ReferenceVector valid2dReferences)
DimensionGeometryType getGeometryConfiguration3d (DrawViewPart *dvp, ReferenceVector valid3dReferences)
GeomCountMap loadRequiredCounts (const StringVector &acceptableGeometry, const std::vector< int > &minimumCouts)
bool checkGeometryOccurrences (StringVector subNames, GeomCountMap keyedMinimumCounts)
DimensionGeometryType isValidVertexes (ReferenceVector refs)
verify that the vertex references can make a dimension
DimensionGeometryType isValidMultiEdge (ReferenceVector refs)
DimensionGeometryType isValidSingleEdge (ReferenceEntry ref)
verify that Selection contains a valid Geometry for a single Edge Dimension
DimensionGeometryType isValidSingleFace (ReferenceEntry ref)
verify that Selection contains a valid Geometry for a single Edge Dimension
DimensionGeometryType isValidHybrid (ReferenceVector refs)
verify that the mixed bag (ex Vertex-Edge) of references can make a dimension
DimensionGeometryType isValidVertexes3d (DrawViewPart *dvp, ReferenceVector refs)
verify that the vertex references can make a dimension
DimensionGeometryType isValidMultiEdge3d (DrawViewPart *dvp, ReferenceVector refs)
DimensionGeometryType isValidSingleEdge3d (DrawViewPart *dvp, ReferenceEntry ref)
verify that Selection contains a valid Geometry for a single Edge Dimension
DimensionGeometryType isValidSingleFace3d (DrawViewPart *dvp, ReferenceEntry ref)
verify that Selection contains a valid Geometry for a single Edge Dimension
DimensionGeometryType isValidHybrid3d (DrawViewPart *dvp, ReferenceVector refs)
verify that the mixed bag (ex Vertex-Edge) of references can make a dimension
long int mapGeometryTypeToDimType (long int dimType, DimensionGeometryType geometry2d, DimensionGeometryType geometry3d)
bool refsMatchToken (const ReferenceVector &refs, const std::string &matchToken)
Variables
const int MAXPROJECTIONCOUNT = 10
Detailed Description
a class to the projection of shapes, removal/identifying hidden lines and
a class to contain useful shape manipulations. these methods were originally
LineGroup - Classes related to processing LineGroup definition CSV files.
HatchLine - Classes related to processing PAT files.
DrawBrokenView produces a view of the Source shapes after a portion of the shapes has been removed.
a class for handling standard ISO128 and ANSI Y14.2 line types and their dash patterns ISO standard lines are defined by a sequence of graphical elements as in the dotted line (line type 7): DOT, GAP each graphical element (DOT, GAP, DASH, etc) has a standard length in units of the line's width. the graphical elements and line definitions are stored in csv files. ANSI lines standards are not numbered, but we assign a number as a convenient reference. ANSI standard lines are defined similarly to ISO, but the element lengths are defined in mm, and do not vary with pen width. ASME standard lines do not specify the element lengths at all, so we have chosen values generally equal to those for ISO128
Typedef Documentation
AOCPtr
using TechDraw::AOCPtr = typedef std::shared_ptr<AOC>
Definition at line 85 of file TechDraw/App/Geometry.h.
AOEPtr
using TechDraw::AOEPtr = typedef std::shared_ptr<AOE>
Definition at line 89 of file TechDraw/App/Geometry.h.
BaseGeomPtr
using TechDraw::BaseGeomPtr = typedef std::shared_ptr<BaseGeom>
Definition at line 81 of file TechDraw/App/Geometry.h.
BaseGeomPtrVector
using TechDraw::BaseGeomPtrVector = typedef std::vector<BaseGeomPtr>
Definition at line 177 of file TechDraw/App/Geometry.h.
BezierSegmentPtr
using TechDraw::BezierSegmentPtr = typedef std::shared_ptr<BezierSegment>
Definition at line 91 of file TechDraw/App/Geometry.h.
BreakList
using TechDraw::BreakList = typedef std::vector<BreakListEntry>
Definition at line 70 of file DrawBrokenView.h.
BSplinePtr
using TechDraw::BSplinePtr = typedef std::shared_ptr<BSpline>
Definition at line 93 of file TechDraw/App/Geometry.h.
ChangePointVector
using TechDraw::ChangePointVector = typedef std::vector<ChangePoint>
Definition at line 76 of file DrawViewSection.h.
CirclePtr
using TechDraw::CirclePtr = typedef std::shared_ptr<Circle>
Definition at line 83 of file TechDraw/App/Geometry.h.
CosmeticExtensionPython
using TechDraw::CosmeticExtensionPython = typedef App::ExtensionPythonT<CosmeticExtension>
Definition at line 128 of file CosmeticExtension.h.
DrawBrokenViewPython
using TechDraw::DrawBrokenViewPython = typedef App::FeaturePythonT<DrawBrokenView>
Definition at line 182 of file DrawBrokenView.h.
DrawComplexSectionPython
using TechDraw::DrawComplexSectionPython = typedef App::FeaturePythonT<DrawComplexSection>
Definition at line 137 of file DrawComplexSection.h.
DrawGeomHatchPython
using TechDraw::DrawGeomHatchPython = typedef App::FeaturePythonT<DrawGeomHatch>
Definition at line 123 of file DrawGeomHatch.h.
DrawHatchPython
using TechDraw::DrawHatchPython = typedef App::FeaturePythonT<DrawHatch>
Definition at line 85 of file DrawHatch.h.
DrawLeaderLinePython
using TechDraw::DrawLeaderLinePython = typedef App::FeaturePythonT<DrawLeaderLine>
Definition at line 121 of file DrawLeaderLine.h.
DrawPagePython
using TechDraw::DrawPagePython = typedef App::FeaturePythonT<DrawPage>
Definition at line 147 of file DrawPage.h.
DrawParametricTemplatePython
using TechDraw::DrawParametricTemplatePython = typedef App::FeaturePythonT<DrawParametricTemplate>
Definition at line 92 of file DrawParametricTemplate.h.
DrawProjectSplitPython
using TechDraw::DrawProjectSplitPython = typedef App::FeaturePythonT<DrawProjectSplit>
Definition at line 137 of file DrawProjectSplit.h.
DrawRichAnnoPython
using TechDraw::DrawRichAnnoPython = typedef App::FeaturePythonT<DrawRichAnno>
Definition at line 88 of file DrawRichAnno.h.
DrawSVGTemplatePython
using TechDraw::DrawSVGTemplatePython = typedef App::FeaturePythonT<DrawSVGTemplate>
Definition at line 102 of file DrawSVGTemplate.h.
DrawTemplatePython
using TechDraw::DrawTemplatePython = typedef App::FeaturePythonT<DrawTemplate>
Definition at line 112 of file DrawTemplate.h.
DrawTilePython
using TechDraw::DrawTilePython = typedef App::FeaturePythonT<DrawTile>
Definition at line 85 of file DrawTile.h.
DrawTileWeldPython
using TechDraw::DrawTileWeldPython = typedef App::FeaturePythonT<DrawTileWeld>
Definition at line 89 of file DrawTileWeld.h.
DrawViewAnnotationPython
using TechDraw::DrawViewAnnotationPython = typedef App::FeaturePythonT<DrawViewAnnotation>
Definition at line 103 of file DrawViewAnnotation.h.
DrawViewClipPython
using TechDraw::DrawViewClipPython = typedef App::FeaturePythonT<DrawViewClip>
Definition at line 101 of file DrawViewClip.h.
DrawViewDetailPython
using TechDraw::DrawViewDetailPython = typedef App::FeaturePythonT<DrawViewDetail>
Definition at line 119 of file DrawViewDetail.h.
DrawViewDraftPython
using TechDraw::DrawViewDraftPython = typedef App::FeaturePythonT<DrawViewDraft>
Definition at line 96 of file DrawViewDraft.h.
DrawViewImagePython
using TechDraw::DrawViewImagePython = typedef App::FeaturePythonT<DrawViewImage>
Definition at line 95 of file DrawViewImage.h.
DrawViewMultiPython
using TechDraw::DrawViewMultiPython = typedef App::FeaturePythonT<DrawViewMulti>
Definition at line 82 of file DrawViewMulti.h.
DrawViewPartPython
using TechDraw::DrawViewPartPython = typedef App::FeaturePythonT<DrawViewPart>
Definition at line 263 of file DrawViewPart.h.
DrawViewPython
using TechDraw::DrawViewPython = typedef App::FeaturePythonT<DrawView>
Definition at line 168 of file DrawView.h.
DrawViewSectionPython
using TechDraw::DrawViewSectionPython = typedef App::FeaturePythonT<DrawViewSection>
Definition at line 215 of file DrawViewSection.h.
DrawViewSpreadsheetPython
using TechDraw::DrawViewSpreadsheetPython = typedef App::FeaturePythonT<DrawViewSpreadsheet>
Definition at line 96 of file DrawViewSpreadsheet.h.
DrawViewSymbolPython
using TechDraw::DrawViewSymbolPython = typedef App::FeaturePythonT<DrawViewSymbol>
Definition at line 101 of file DrawViewSymbol.h.
DrawWeldSymbolPython
using TechDraw::DrawWeldSymbolPython = typedef App::FeaturePythonT<DrawWeldSymbol>
Definition at line 93 of file DrawWeldSymbol.h.
edge_t
using TechDraw::edge_t = typedef boost::graph_traits < graph >::edge_descriptor
Definition at line 81 of file EdgeWalker.h.
EllipsePtr
using TechDraw::EllipsePtr = typedef std::shared_ptr<Ellipse>
Definition at line 87 of file TechDraw/App/Geometry.h.
FacePtr
using TechDraw::FacePtr = typedef std::shared_ptr<Face>
Definition at line 359 of file TechDraw/App/Geometry.h.
GenericPtr
using TechDraw::GenericPtr = typedef std::shared_ptr<Generic>
Definition at line 95 of file TechDraw/App/Geometry.h.
GeometryObjectPtr
typedef std::shared_ptr< GeometryObject > TechDraw::GeometryObjectPtr
Definition at line 43 of file DrawProjectSplit.h.
graph
using TechDraw::graph = typedef boost::adjacency_list < boost::vecS, boost::vecS, boost::bidirectionalS, boost::property<boost::vertex_index_t, int>, boost::property<boost::edge_index_t, int> >
Definition at line 75 of file EdgeWalker.h.
PieceLimitList
using TechDraw::PieceLimitList = typedef std::vector<PieceLimitEntry>
Definition at line 76 of file DrawBrokenView.h.
planar_embedding_storage_t
using TechDraw::planar_embedding_storage_t = typedef std::vector< std::vector<edge_t> >
Definition at line 84 of file EdgeWalker.h.
planar_embedding_t
using TechDraw::planar_embedding_t = typedef boost::iterator_property_map< planar_embedding_storage_t::iterator, boost::property_map<graph, boost::vertex_index_t>::type >
Definition at line 89 of file EdgeWalker.h.
ReferenceVector
using TechDraw::ReferenceVector = typedef std::vector<ReferenceEntry>
Definition at line 102 of file DimensionReferences.h.
vertex_t
using TechDraw::vertex_t = typedef boost::graph_traits < graph >::vertex_descriptor
Definition at line 78 of file EdgeWalker.h.
vertexMap
using TechDraw::vertexMap = typedef std::map<Base::Vector3d, int, DrawUtil::vectorLessType>
Definition at line 80 of file DrawProjectSplit.h.
VertexPtr
using TechDraw::VertexPtr = typedef std::shared_ptr<Vertex>
Definition at line 420 of file TechDraw/App/Geometry.h.
WirePtr
using TechDraw::WirePtr = typedef std::shared_ptr<Wire>
Definition at line 345 of file TechDraw/App/Geometry.h.
Enumeration Type Documentation
ArrowType
enum TechDraw::ArrowType
Enumerator
FILLED_ARROW
OPEN_ARROW
TICK
DOT
OPEN_CIRCLE
FORK
FILLED_TRIANGLE
NONE
Definition at line 57 of file ArrowPropEnum.h.
BalloonType
enum TechDraw::BalloonType
Enumerator
Circular
None
Triangle
Inspection
Hexagon
Square
Rectangle
Line
Definition at line 56 of file BalloonPropEnum.h.
DimensionGeometryEnum
enum TechDraw::DimensionGeometryEnum
Enumerator
isInvalid
isHorizontal
isVertical
isDiagonal
isCircle
isEllipse
isBSplineCircle
isBSpline
isAngle
isAngle3Pt
isMultiEdge
isZLimited
isHybrid
isFace
isViewReference
Definition at line 49 of file DimensionValidators.h.
edgeClass
enum TechDraw::edgeClass
Enumerator
ecNONE
ecUVISO
ecOUTLINE
ecSMOOTH
ecSEAM
ecHARD
Definition at line 54 of file TechDraw/App/Geometry.h.
ExtractionType
enum TechDraw::ExtractionType
Enumerator
Plain
WithHidden
WithSmooth
Definition at line 48 of file TechDraw/App/Geometry.h.
GeomType
enum TechDraw::GeomType
Enumerator
NOTDEF
CIRCLE
ARCOFCIRCLE
ELLIPSE
ARCOFELLIPSE
BEZIER
BSPLINE
GENERIC
Definition at line 63 of file TechDraw/App/Geometry.h.
ProjItemType
enum TechDraw::ProjItemType
Enumerator
Front
Left
Right
Rear
Top
Bottom
FrontTopLeft
FrontTopRight
FrontBottomLeft
FrontBottomRight
Definition at line 58 of file DrawProjGroupItem.h.
SourceType
enum TechDraw::SourceType
Enumerator
GEOM
COSEDGE
CENTERLINE
Definition at line 74 of file TechDraw/App/Geometry.h.
Function Documentation
build3dCurves()
const TopoDS_Shape & TechDraw::build3dCurves (const TopoDS_Shape & shape)
Definition at line 57 of file TechDraw/App/ProjectionAlgos.cpp.
Referenced by TechDraw::ProjectionAlgos::execute().
checkGeometryOccurrences()
bool TechDraw::checkGeometryOccurrences (StringVector subNames, GeomCountMap keyedMinimumCounts)
Definition at line 225 of file DimensionValidators.cpp.
References TechDraw::DrawUtil::getGeomTypeFromName().
Referenced by validateDimSelection(), and validateDimSelection3d().
copy()
template<typename OutputIt > void TechDraw::copy (Py::Dict sourceRange, OutputIt targetIt)
Copies a Python dictionary of Python strings to a C++ container.
After the function call, the key-value pairs of the Python dictionary are copied into the target buffer as C++ pairs (pair<string, string>).
Parameters
sourceRange is a Python dictionary (Py::Dict). Both, the keys and the values must be Python strings.
targetIt refers to where the data should be inserted. Must be of concept output iterator.
Definition at line 109 of file AppTechDrawPy.cpp.
References src.Mod.Test.testmakeWireString::String.
getGeometryConfiguration()
DimensionGeometryType TechDraw::getGeometryConfiguration (ReferenceVector valid2dReferences)
Definition at line 266 of file DimensionValidators.cpp.
References isInvalid, isValidHybrid(), isValidMultiEdge(), isValidSingleEdge(), isValidSingleFace(), and isValidVertexes().
Referenced by validateDimSelection().
getGeometryConfiguration3d()
DimensionGeometryType TechDraw::getGeometryConfiguration3d (DrawViewPart * dvp, ReferenceVector valid3dReferences)
Definition at line 295 of file DimensionValidators.cpp.
References isInvalid, isMultiEdge, isValidHybrid3d(), isValidMultiEdge3d(), isValidSingleEdge3d(), isValidSingleFace3d(), and isValidVertexes3d().
Referenced by validateDimSelection3d().
getReferencesFromSelection()
TechDraw::DrawViewPart * TechDraw::getReferencesFromSelection (ReferenceVector & references2d, ReferenceVector & references3d)
Definition at line 44 of file DimensionValidators.cpp.
References Base::Persistence::getClassTypeId(), Gui::SelectionSingleton::getSelectionEx(), TechDraw::DrawViewDimension::getViewPart(), Gui::NoResolve, and Gui::Selection().
Referenced by execDim(), execExtent(), and TechDrawGui::TaskDimRepair::slotUseSelection().
initModule()
PyObject* TechDraw::initModule ()
Definition at line 1329 of file AppTechDrawPy.cpp.
References Base::InterpreterSingleton::addModule(), and Base::Interpreter().
Referenced by PyMOD_INIT_FUNC().
isValidHybrid()
DimensionGeometryType TechDraw::isValidHybrid (ReferenceVector refs)
verify that the mixed bag (ex Vertex-Edge) of references can make a dimension
Definition at line 693 of file DimensionValidators.cpp.
References TechDraw::DrawUtil::getGeomTypeFromName(), isHybrid, and isInvalid.
Referenced by getGeometryConfiguration(), and isValidHybrid3d().
isValidHybrid3d()
DimensionGeometryType TechDraw::isValidHybrid3d (DrawViewPart * dvp, ReferenceVector refs)
verify that the mixed bag (ex Vertex-Edge) of references can make a dimension
Definition at line 718 of file DimensionValidators.cpp.
References isValidHybrid().
Referenced by getGeometryConfiguration3d().
isValidMultiEdge()
DimensionGeometryType TechDraw::isValidMultiEdge (ReferenceVector refs)
verify that the edge references can make a dimension. Currently only extent dimensions support more than 2 edges
Definition at line 502 of file DimensionValidators.cpp.
References dot(), Base::Vector3< float_type >::Dot(), EWTOLERANCE, TechDraw::DrawUtil::fpCompare(), GENERIC, TechDraw::DrawUtil::getIndexFromName(), isAngle, isDiagonal, isInvalid, isMultiEdge, Base::Vector3< float_type >::Normalize(), and refsMatchToken().
Referenced by TDHandlerDimension::createAngleDimension(), and getGeometryConfiguration().
isValidMultiEdge3d()
DimensionGeometryType TechDraw::isValidMultiEdge3d (DrawViewPart * dvp, ReferenceVector refs)
verify that the edge references can make a dimension. Currently only extent dimensions support more than 2 edges
Definition at line 553 of file DimensionValidators.cpp.
References dot(), Base::Vector3< float_type >::Dot(), EWTOLERANCE, FirstVertex(), TechDraw::DrawUtil::fpCompare(), TechDraw::ShapeExtractor::getShapesFromObject(), isAngle, isDiagonal, isInvalid, isMultiEdge, LastVertex(), Base::Vector3< float_type >::Normalize(), refsMatchToken(), and TechDraw::DrawUtil::toVector3d().
Referenced by getGeometryConfiguration3d().
isValidSingleEdge()
DimensionGeometryType TechDraw::isValidSingleEdge (ReferenceEntry ref)
verify that Selection contains a valid Geometry for a single Edge Dimension
Definition at line 362 of file DimensionValidators.cpp.
References ARCOFCIRCLE, ARCOFELLIPSE, BSPLINE, CIRCLE, ELLIPSE, GENERIC, TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::DrawUtil::getIndexFromName(), TechDraw::ReferenceEntry::getObject(), TechDraw::ReferenceEntry::getSubName(), isBSpline, isBSplineCircle, isCircle, isDiagonal, isEllipse, isHorizontal, isInvalid, isVertical, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by getGeometryConfiguration().
isValidSingleEdge3d()
DimensionGeometryType TechDraw::isValidSingleEdge3d (DrawViewPart * dvp, ReferenceEntry ref)
verify that Selection contains a valid Geometry for a single Edge Dimension
Definition at line 411 of file DimensionValidators.cpp.
References FirstVertex(), TechDraw::ReferenceEntry::getGeometry(), TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::ReferenceEntry::getSubName(), isBSpline, isBSplineCircle, isCircle, TechDraw::GeometryUtils::isCircle(), isDiagonal, isEllipse, isHorizontal, isInvalid, isVertical, LastVertex(), TechDraw::DrawViewPart::projectPoint(), TechDraw::DrawUtil::toVector3d(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by getGeometryConfiguration3d().
isValidSingleFace()
DimensionGeometryType TechDraw::isValidSingleFace (ReferenceEntry ref)
verify that Selection contains a valid Geometry for a single Edge Dimension
Definition at line 460 of file DimensionValidators.cpp.
References TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::ReferenceEntry::getObject(), TechDraw::ReferenceEntry::getSubName(), isFace, and isInvalid.
Referenced by getGeometryConfiguration().
isValidSingleFace3d()
DimensionGeometryType TechDraw::isValidSingleFace3d (DrawViewPart * dvp, ReferenceEntry ref)
verify that Selection contains a valid Geometry for a single Edge Dimension
Definition at line 482 of file DimensionValidators.cpp.
References Base::Console(), TechDraw::ReferenceEntry::getGeometry(), TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::ReferenceEntry::getSubName(), isFace, isInvalid, and Base::ConsoleSingleton::Warning().
Referenced by getGeometryConfiguration3d().
isValidVertexes()
DimensionGeometryType TechDraw::isValidVertexes (ReferenceVector refs)
verify that the vertex references can make a dimension
Definition at line 617 of file DimensionValidators.cpp.
References TechDraw::DrawViewPart::getVertex(), isAngle3Pt, isDiagonal, isHorizontal, isInvalid, isVertical, refsMatchToken(), draftgeoutils.general::v1(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by getGeometryConfiguration().
isValidVertexes3d()
DimensionGeometryType TechDraw::isValidVertexes3d (DrawViewPart * dvp, ReferenceVector refs)
verify that the vertex references can make a dimension
Definition at line 652 of file DimensionValidators.cpp.
References isAngle3Pt, isDiagonal, isHorizontal, isInvalid, isVertical, TechDraw::DrawViewPart::projectPoint(), refsMatchToken(), TechDraw::DrawUtil::toVector3d(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by getGeometryConfiguration3d().
loadRequiredCounts()
GeomCountMap TechDraw::loadRequiredCounts (const StringVector & acceptableGeometry, const std::vector< int > & minimumCouts)
Definition at line 345 of file DimensionValidators.cpp.
References result.
Referenced by validateDimSelection(), and validateDimSelection3d().
mapGeometryTypeToDimType()
long int TechDraw::mapGeometryTypeToDimType (long int dimType, DimensionGeometryType geometry2d, DimensionGeometryType geometry3d)
Definition at line 726 of file DimensionValidators.cpp.
References TechDraw::DrawViewDimension::Angle, TechDraw::DrawViewDimension::Angle3Pt, TechDraw::DrawViewDimension::Distance, TechDraw::DrawViewDimension::DistanceX, TechDraw::DrawViewDimension::DistanceY, isAngle, isAngle3Pt, isDiagonal, isHorizontal, isInvalid, isVertical, and isViewReference.
refsMatchToken()
bool TechDraw::refsMatchToken (const ReferenceVector & refs, const std::string & matchToken)
true if all the input references have subelements that match the geometry type token.
Definition at line 766 of file DimensionValidators.cpp.
References TechDraw::DrawUtil::getGeomTypeFromName().
Referenced by isValidMultiEdge(), isValidMultiEdge3d(), isValidVertexes(), and isValidVertexes3d().
validateDimSelection()
DimensionGeometryType TechDraw::validateDimSelection (const ReferenceVector & references, const StringVector & acceptableGeometry, const std::vector< int > & minimumCounts, const std::vector< DimensionGeometryType > & acceptableDimensionGeometrys)
verify that the proposed references contains valid geometries from a 2d DrawViewPart.
Definition at line 98 of file DimensionValidators.cpp.
References checkGeometryOccurrences(), getGeometryConfiguration(), isInvalid, isViewReference, loadRequiredCounts(), and validateSubnameList().
Referenced by execDim(), execExtent(), TDHandlerDimension::isVerticalDistance(), and TechDrawGui::TaskDimRepair::slotUseSelection().
validateDimSelection3d()
DimensionGeometryType TechDraw::validateDimSelection3d (TechDraw::DrawViewPart * dvp, const ReferenceVector & references, const StringVector & acceptableGeometry, const std::vector< int > & minimumCounts, const std::vector< DimensionGeometryType > & acceptableDimensionGeometrys)
verify that the proposed references contains valid geometries from non-TechDraw objects.
Definition at line 169 of file DimensionValidators.cpp.
References checkGeometryOccurrences(), getGeometryConfiguration3d(), isInvalid, loadRequiredCounts(), and validateSubnameList().
Referenced by execDim(), execExtent(), and TechDrawGui::TaskDimRepair::slotUseSelection().
validateSubnameList()
bool TechDraw::validateSubnameList (StringVector subNames, GeometrySet acceptableGeometrySet)
Definition at line 212 of file DimensionValidators.cpp.
References TechDraw::DrawUtil::getGeomTypeFromName().
Referenced by validateDimSelection(), and validateDimSelection3d().
Variable Documentation
MAXPROJECTIONCOUNT
const int TechDraw::MAXPROJECTIONCOUNT = 10
Definition at line 43 of file DrawProjGroup.h.
Referenced by TechDraw::DrawProjGroup::arrangeViewPointers(), TechDraw::DrawProjGroup::getXYPosition(), and TechDraw::DrawProjGroup::makeViewBbs().