FreeCAD: SoDevicePixelRatioElement Class Reference
SoDevicePixelRatioElement Class Reference
#include <SoDevicePixelRatioElement.h>
Public Member Functions
virtual void init (SoState *state) override
Static Public Member Functions
static void initClass ()
static void set (SoState *state, float dpr)
static float get (SoState *state)
Protected Member Functions
virtual ~SoDevicePixelRatioElement ()
Detailed Description
Definition at line 31 of file SoDevicePixelRatioElement.h.
Constructor & Destructor Documentation
~SoDevicePixelRatioElement()
SoDevicePixelRatioElement::~SoDevicePixelRatioElement () protected virtual
Definition at line 55 of file SoDevicePixelRatioElement.cpp.
Member Function Documentation
get()
float SoDevicePixelRatioElement::get (SoState * state) static
Definition at line 51 of file SoDevicePixelRatioElement.cpp.
Referenced by Gui::SoShapeScale::GLRender(), and draftguitools.gui_trackers.editTracker::move().
init()
void SoDevicePixelRatioElement::init (SoState * state) override virtual
Definition at line 42 of file SoDevicePixelRatioElement.cpp.
References SIM::Coin3D::Quarter::Quarter::init().
Referenced by DocumentObject.DocumentObject::onChanged().
initClass()
void SoDevicePixelRatioElement::initClass () static
Definition at line 36 of file SoDevicePixelRatioElement.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
set()
void SoDevicePixelRatioElement::set (SoState * state, float dpr) static
Definition at line 47 of file SoDevicePixelRatioElement.cpp.
Referenced by draftguitools.gui_trackers.editTracker::move(), and Gui::View3DInventorViewer::renderScene().
The documentation for this class was generated from the following files:
SoDevicePixelRatioElement.h
SoDevicePixelRatioElement.cpp