FreeCAD: ifc2x3.ifctextstyletextmodel Class Reference
ifc2x3.ifctextstyletextmodel Class Reference
Public Member Functions
def __init__ (self, textindent, textalign, textdecoration, letterspacing, wordspacing, texttransform, lineheight)
def textindent ()
def textalign ()
def textdecoration ()
def letterspacing ()
def wordspacing ()
def texttransform ()
def lineheight ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
textindent
textalign
textdecoration
letterspacing
wordspacing
texttransform
lineheight
Detailed Description
Entity ifctextstyletextmodel definition.
:param textindent
:type textindent:ifcsizeselect
:param textalign
:type textalign:ifctextalignment
:param textdecoration
:type textdecoration:ifctextdecoration
:param letterspacing
:type letterspacing:ifcsizeselect
:param wordspacing
:type wordspacing:ifcsizeselect
:param texttransform
:type texttransform:ifctexttransformation
:param lineheight
:type lineheight:ifcsizeselect
Definition at line 19645 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifctextstyletextmodel.__init__ (self, textindent, textalign, textdecoration, letterspacing, wordspacing, texttransform, lineheight)
Definition at line 19669 of file ifc2x3.py.
Member Function Documentation
letterspacing()
def ifc2x3.ifctextstyletextmodel.letterspacing ()
Definition at line 19721 of file ifc2x3.py.
References ifc2x3.ifctextstyletextmodel._letterspacing, SCL.TypeChecker.check_type(), ifc2x3.ifcsizeselect, and ifc2x3.ifctextstyletextmodel.letterspacing.
lineheight()
def ifc2x3.ifctextstyletextmodel.lineheight ()
Definition at line 19763 of file ifc2x3.py.
References ifc2x3.ifctextstyletextmodel._lineheight, SCL.TypeChecker.check_type(), ifc2x3.ifcsizeselect, and ifc2x3.ifctextstyletextmodel.lineheight.
textalign()
def ifc2x3.ifctextstyletextmodel.textalign ()
Definition at line 19693 of file ifc2x3.py.
References ifc2x3.ifctextstyletextmodel._textalign, SCL.TypeChecker.check_type(), and ifc2x3.ifctextstyletextmodel.textalign.
textdecoration()
def ifc2x3.ifctextstyletextmodel.textdecoration ()
Definition at line 19707 of file ifc2x3.py.
References ifc2x3.ifctextstyletextmodel._textdecoration, SCL.TypeChecker.check_type(), and ifc2x3.ifctextstyletextmodel.textdecoration.
textindent()
def ifc2x3.ifctextstyletextmodel.textindent ()
Definition at line 19679 of file ifc2x3.py.
References ifc2x3.ifctextstyletextmodel._textindent, SCL.TypeChecker.check_type(), ifc2x3.ifcsizeselect, and ifc2x3.ifctextstyletextmodel.textindent.
texttransform()
def ifc2x3.ifctextstyletextmodel.texttransform ()
Definition at line 19749 of file ifc2x3.py.
References ifc2x3.ifctextstyletextmodel._texttransform, SCL.TypeChecker.check_type(), and ifc2x3.ifctextstyletextmodel.texttransform.
wordspacing()
def ifc2x3.ifctextstyletextmodel.wordspacing ()
Definition at line 19735 of file ifc2x3.py.
References ifc2x3.ifctextstyletextmodel._wordspacing, SCL.TypeChecker.check_type(), ifc2x3.ifcsizeselect, and ifc2x3.ifctextstyletextmodel.wordspacing.
Member Data Documentation
letterspacing
ifc2x3.ifctextstyletextmodel.letterspacing
Definition at line 19673 of file ifc2x3.py.
Referenced by ifc2x3.ifctextstyletextmodel.letterspacing().
lineheight
ifc2x3.ifctextstyletextmodel.lineheight
Definition at line 19676 of file ifc2x3.py.
Referenced by ifc2x3.ifctextstyletextmodel.lineheight().
textalign
ifc2x3.ifctextstyletextmodel.textalign
Definition at line 19671 of file ifc2x3.py.
Referenced by ifc2x3.ifctextstyletextmodel.textalign().
textdecoration
ifc2x3.ifctextstyletextmodel.textdecoration
Definition at line 19672 of file ifc2x3.py.
Referenced by ifc2x3.ifctextstyletextmodel.textdecoration().
textindent
ifc2x3.ifctextstyletextmodel.textindent
Definition at line 19670 of file ifc2x3.py.
Referenced by ifc2x3.ifctextstyletextmodel.textindent().
texttransform
ifc2x3.ifctextstyletextmodel.texttransform
Definition at line 19675 of file ifc2x3.py.
Referenced by ifc2x3.ifctextstyletextmodel.texttransform().
wordspacing
ifc2x3.ifctextstyletextmodel.wordspacing
Definition at line 19674 of file ifc2x3.py.
Referenced by ifc2x3.ifctextstyletextmodel.wordspacing().
The documentation for this class was generated from the following file:
ifc2x3.py