FreeCAD: MeshGui::DlgSettingsMeshView Class Reference
MeshGui::DlgSettingsMeshView Class Reference
#include <DlgSettingsMeshView.h>
Public Member Functions
DlgSettingsMeshView (QWidget *parent=nullptr)
~DlgSettingsMeshView () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void saveSettings () override
void loadSettings () override
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
The DlgSettingsMeshView class implements a preference page to change settings for display of meshes.
Author
Werner Mayer
Definition at line 62 of file DlgSettingsMeshView.h.
Constructor & Destructor Documentation
DlgSettingsMeshView()
DlgSettingsMeshView::DlgSettingsMeshView (QWidget * parent = nullptr) explicit
Constructs a DlgSettingsMeshView which is a child of 'parent'.
Definition at line 36 of file DlgSettingsMeshView.cpp.
~DlgSettingsMeshView()
DlgSettingsMeshView::~DlgSettingsMeshView () override default
Destroys the object and frees any allocated resources
Member Function Documentation
changeEvent()
void DlgSettingsMeshView::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 84 of file DlgSettingsMeshView.cpp.
References SCL.SimpleDataTypes::e.
loadSettings()
void DlgSettingsMeshView::loadSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 63 of file DlgSettingsMeshView.cpp.
References ParameterGrp::GetBool(), Gui::WindowParameter::getDefaultParameter(), and ParameterGrp::GetGroup().
saveSettings()
void DlgSettingsMeshView::saveSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 50 of file DlgSettingsMeshView.cpp.
The documentation for this class was generated from the following files:
DlgSettingsMeshView.h
DlgSettingsMeshView.cpp