FreeCAD: SketcherGui::ViewProviderSketch Class Reference
SketcherGui::ViewProviderSketch Class Reference
The Sketch ViewProvider.
#include <ViewProviderSketch.h>
Classes
class ToolManager
Public Member Functions
Classes storing the state of Dragging, Selection and Preselection
All these classes enable the identification of a Vertex, a Curve, the root Point, axes, and constraints.
A word on indices and ways to identify elements and parts of them:
The Sketcher has a general main way to identify geometry, {GeoId, PointPos}, these can be provided as separate data, or using Sketcher::GeoElementId. The latter defines comparison and equality operators enabling, for example to use it as key in a std::map.
While it is indeed possible to refer to any point using that nomenclature, creating maps in certain circumnstances leads to a performance drawback. Additionally, the legacy selection mechanism refers to positive indexed Vertices (for both normal and external vertices). Both reasons discourage moving to a single identification. This situation has been identified at different levels:
(1) In sketch.cpp, the solver facade defining the interface with GCS, both {GeoId, PointPos} and PointId are used.
(2) In SketchObject.cpp, the actual document object, both {GeoId, PointPos} and VertexId are used (see VertexId2GeoId and VertexId2GeoPosId).
(3) In ViewProviderSketch, both {GeoId, PointPos} an Point indices are used (see these structures)
(4) At CoinManager level, {GeoId, PointPos}, Point indices (for selection) and MultiFieldIds (specific structure defining a coin multifield index and layer) are used.
Using a single index instead of a multi-index field, allows mappings to be implemented via std::vectors instead of std::maps. Direct mappings using std::vectors are accessed in constant time. Multi-index mappings relying on std::maps involve a search for the key. This leads to a drop in performance.
What are these indices and how do they relate each other?
PointId, VertexId depend on the order of the geometries in the sketch. GeoList and GeoListFacade enable to convert between indices.
CurveId is basically the GeoId assuming PointPos to be PointPos::none (edge)
Sometimes, Axes and root point are separated into a third index or enum. Legacy reasons aside, the root point is has GeoId=-1, which is sometimes used as invalid value in positive only indices. Additionally, root point and the Horizontal Axes both have GeoId=-1 (differing in PointPos only). Following the decision not to rely on PointPos, creating a separate index, best when enum-ed, appears justified.
ViewProviderSketch ()
constructor
~ViewProviderSketch () override
destructor
handler control
void activateHandler (std::unique_ptr< DrawSketchHandler > newHandler)
sets an DrawSketchHandler in control
void purgeHandler ()
removes the active handler
Drawing functions
void draw (bool temp=false, bool rebuildinformationoverlay=true)
void updateColor ()
helper change the color of the sketch according to selection and solver status
Toggle angle snapping and set the reference point
void setAngleSnapping (bool enable, Base::Vector2d referencePoint=Base::Vector2d(0., 0.))
Toggle angle snapping and set the reference point.
Access to Sketch and Solver objects
Sketcher::SketchObject * getSketchObject () const
get the pointer to the sketch document object
const Sketcher::Sketch & getSolvedSketch () const
constraint Virtual Space visibility management
void updateVirtualSpace ()
updates the visibility of the virtual space of constraints
void setIsShownVirtualSpace (bool isshownvirtualspace)
bool getIsShownVirtualSpace () const
returns whether the virtual space is being shown
Register slot for signal
template<typename F >
boost::signals2::connection registerToolChanged (F &&f)
Public Member Functions inherited from PartGui::ViewProvider2DObject
ViewProvider2DObject ()
constructor
~ViewProvider2DObject () override
destructor
std::vector< std::string > getDisplayModes () const override
returns a list of all possible display modes
const char * getDefaultDisplayMode () const override
get the default display mode
Public Member Functions inherited from PartGui::ViewProviderPart
ViewProviderPart ()
constructor
~ViewProviderPart () override
destructor
Public Member Functions inherited from PartGui::ViewProviderPartExt
ViewProviderPartExt ()
constructor
~ViewProviderPartExt () override
destructor
void setDisplayMode (const char *ModeName) override
set the display mode
std::vector< std::string > getDisplayModes () const override
returns a list of all possible modes
void reload ()
Update the view representation.
bool changeFaceAppearances ()
If no other task is pending it opens a dialog to allow one to change face colors.
bool useNewSelectionModel () const override
indicates if the ViewProvider use the new Selection model
std::string getElement (const SoDetail *) const override
return a hit element to the selection path or 0
SoDetail * getDetail (const char *) const override
return the coin node detail of the subelement
std::vector< Base::Vector3d > getModelPoints (const SoPickedPoint *) const override
std::vector< Base::Vector3d > getSelectionShape (const char *Element) const override
return the highlight lines for a given element or the whole shape
void setHighlightedFaces (const std::vector< App::Material > &materials)
void setHighlightedFaces (const App::PropertyMaterialList &appearance)
void unsetHighlightedFaces ()
void setHighlightedEdges (const std::vector< App::Color > &colors)
void unsetHighlightedEdges ()
void setHighlightedPoints (const std::vector< App::Color > &colors)
void unsetHighlightedPoints ()
std::map< std::string, App::Color > getElementColors (const char *element=nullptr) const override
bool isUpdateForced () const override
void forceUpdate (bool enable=true) override
bool allowOverride (const App::DocumentObject &) const override
PyObject * getPyObject () override
Get the python wrapper for that ViewProvider.
Public Member Functions inherited from Gui::ViewProviderGeometryObject
ViewProviderGeometryObject ()
constructor.
~ViewProviderGeometryObject () override
destructor.
SoPickedPointList getPickedPoints (const SbVec2s &pos, const View3DInventorViewer &viewer, bool pickAll=false) const
SoPickedPoint * getPickedPoint (const SbVec2s &pos, const View3DInventorViewer &viewer) const
virtual void showBoundingBox (bool)
Public Member Functions inherited from Gui::ViewProviderDragger
ViewProviderDragger ()
constructor.
~ViewProviderDragger () override
destructor.
Base::Placement getTransformOrigin () const
Convenience method to obtain the transform origin.
void setTransformOrigin (const Base::Placement &placement)
Convenience method to set the transform origin.
void resetTransformOrigin ()
Resets transform origin to the object origin.
ViewProvider * startEditing (int ModNum=0) override
void updatePlacementFromDragger ()
updates placement of object based on dragger position
void updateTransformFromDragger ()
updates transform of object based on dragger position, can be used to preview movement
Base::Placement getObjectPlacement () const
Gets object placement relative to its coordinate system.
Base::Placement getDraggerPlacement () const
Gets current dragger placement, including current dragger movement.
Base::Placement getOriginalDraggerPlacement () const
Gets original dragger placement, without current dragger movement.
void setDraggerPlacement (const Base::Placement &placement)
Sets placement of dragger relative to objects origin.
Public Member Functions inherited from Gui::ViewProviderDocumentObject
ViewProviderDocumentObject ()
constructor.
~ViewProviderDocumentObject () override
destructor.
virtual void reattach (App::DocumentObject *)
void update (const App::Property *) override
void setActiveMode ()
Set the active mode, i.e. the first item of the 'Display' property.
void hide () override
Hide the object in the view.
void show () override
Show the object in the view.
bool canDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const override
int replaceObject (App::DocumentObject *, App::DocumentObject *) override
bool showInTree () const override
void getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &) const override
Get a list of TaskBoxes associated with this object.
void updateView ()
Run a redraw.
App::DocumentObject * getObject () const
Get the object of this ViewProvider object.
template<class T >
T * getObject () const
Get the object of this ViewProvider object as specified type.
bool canDelete (App::DocumentObject *obj) const override
Asks the view provider if the given object can be deleted.
virtual bool acceptDeletionsInEdit ()
Ask the view provider if it accepts object deletions while in edit.
Gui::Document * getDocument () const
Get the GUI document to this ViewProvider object.
bool getElementPicked (const SoPickedPoint *, std::string &subname) const override
return a hit element given the picked point which contains the full node path
bool getDetailPath (const char *subname, SoFullPath *pPath, bool append, SoDetail *&det) const override
return the coin node detail and path to the node of the subname
int getTreeRank () const
void setTreeRank (int value)
bool removeDynamicProperty (const char *prop) override
App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
virtual ViewProviderDocumentObject * getLinkedViewProvider (std::string *subname=nullptr, bool recursive=false) const
std::string getFullName () const override
void setShowable (bool enable)
bool isShowable () const
void startDefaultEditMode ()
Public Member Functions inherited from Gui::ViewProvider
ViewProvider ()
constructor.
~ViewProvider () override
destructor.
virtual SoSeparator * getRoot () const
SoSwitch * getModeSwitch () const
SoTransform * getTransformNode () const
SoSeparator * getAnnotation ()
virtual SoSeparator * getFrontRoot () const
virtual SoGroup * getChildRoot () const
virtual SoSeparator * getBackRoot () const
virtual bool canAddToSceneGraph () const
Indicate whether to be added to scene graph or not.
virtual bool isPartOfPhysicalObject () const
virtual std::vector< App::DocumentObject * > claimChildren3D () const
int partialRender (const std::vector< std::string > &subelements, bool clear)
Base::BoundBox3d getBoundingBox (const char *subname=nullptr, bool transform=true, MDIView *view=nullptr) const
virtual void beforeDelete ()
virtual bool canDragObjects () const
virtual bool canDragObject (App::DocumentObject *) const
virtual bool canDragObjectToTarget (App::DocumentObject *obj, App::DocumentObject *target) const
virtual void dragObject (App::DocumentObject *)
virtual bool canDropObjects () const
virtual bool canDropObject (App::DocumentObject *) const
virtual bool canDragAndDropObject (App::DocumentObject *) const
virtual void dropObject (App::DocumentObject *)
virtual bool acceptReorderingObjects () const
virtual std::string getDropPrefix () const
return a subname referencing the sub-object holding the dropped objects
virtual std::string dropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements)
virtual bool canRemoveChildrenFromRoot () const
std::string getActiveDisplayMode () const
virtual bool isShow () const
checks whether the view provider is visible or not
void setVisible (bool)
bool isVisible () const
void setLinkVisible (bool)
bool isLinkVisible () const
virtual void setOverrideMode (const std::string &mode)
Overrides the display mode with mode.
const std::string getOverrideMode ()
virtual QIcon getIcon () const
deliver the icon shown in the tree view
virtual std::vector< App::DocumentObject * > claimChildren () const
virtual std::vector< App::DocumentObject * > claimChildrenRecursive () const
bool isUpdatesEnabled () const
void setUpdatesEnabled (bool enable)
unsigned long getStatus () const
return the status bits
bool testStatus (ViewStatus pos) const
void setStatus (ViewStatus pos, bool on)
std::string toString () const
virtual void setElementColors (const std::map< std::string, App::Color > &colors)
bool isEditing () const
void finishEditing ()
virtual void setTransformation (const Base::Matrix4D &rcMatrix)
set the viewing transformation of the provider
virtual void setTransformation (const SbMatrix &rcMatrix)
virtual MDIView * getMDIView () const
void Restore (Base::XMLReader &reader) override
bool isRestoring ()
void addDisplayMaskMode (SoNode *node, const char *type)
Adds a new display mask mode.
void setDisplayMaskMode (const char *type)
Activates the display mask mode type.
SoNode * getDisplayMaskMode (const char *type) const
Get the node to the display mask mode type.
std::vector< std::string > getDisplayMaskModes () const
Returns a list of added display mask modes.
void setDefaultMode (int)
int getDefaultMode () const
virtual void setRenderCacheMode (int)
Public Member Functions inherited from App::TransactionalObject
TransactionalObject ()
Constructor.
~TransactionalObject () override
Public Member Functions inherited from App::ExtensionContainer
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
Property * getPropertyByName (const char *name) const override
find a property by its name
template<typename T >
T * getPropertyByName (const char *name) const
find a property by its name, dynamic cased to specified type
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop) override
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from PartGui::ViewProviderGridExtension
ViewProviderGridExtension ()
constructor
~ViewProviderGridExtension () override
void setGridEnabled (bool enable)
void drawGrid (bool cameraUpdate)
void extensionUpdateData (const App::Property *) override
SoSeparator * getGridNode ()
void setGridOrientation (Base::Vector3d origin, Base::Rotation rotation)
void getClosestGridPoint (double &x, double &y) const
double getGridSize () const
Public Member Functions inherited from Gui::ViewProviderExtension
ViewProviderExtension ()
~ViewProviderExtension () override
Gui::ViewProviderDocumentObject * getExtendedViewProvider ()
const Gui::ViewProviderDocumentObject * getExtendedViewProvider () const
virtual std::vector< App::DocumentObject * > extensionClaimChildren3D () const
virtual bool extensionOnDelete (const std::vector< std::string > &)
virtual void extensionBeforeDelete ()
virtual std::vector< App::DocumentObject * > extensionClaimChildren () const
virtual bool extensionCanDragObjects () const
virtual bool extensionCanDragObject (App::DocumentObject *) const
virtual void extensionDragObject (App::DocumentObject *)
virtual bool extensionCanDropObjects () const
virtual bool extensionCanDropObject (App::DocumentObject *) const
virtual bool extensionCanDragAndDropObject (App::DocumentObject *) const
virtual void extensionDropObject (App::DocumentObject *)
virtual bool extensionCanDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const
virtual std::string extensionDropObjectEx (App::DocumentObject *obj, App::DocumentObject *, const char *, const std::vector< std::string > &)
virtual int extensionReplaceObject (App::DocumentObject *, App::DocumentObject *)
virtual void extensionHide ()
Hides the view provider.
virtual void extensionShow ()
Shows the view provider.
virtual void extensionModeSwitchChange ()
virtual SoSeparator * extensionGetFrontRoot () const
virtual SoGroup * extensionGetChildRoot () const
virtual SoSeparator * extensionGetBackRoot () const
virtual void extensionAttach (App::DocumentObject *)
virtual void extensionReattach (App::DocumentObject *)
virtual void extensionSetDisplayMode (const char *)
virtual std::vector< std::string > extensionGetDisplayModes () const
PyObject * getExtensionPyObject () override
void setIgnoreOverlayIcon (bool on)
bool ignoreOverlayIcon () const
virtual QIcon extensionMergeGreyableOverlayIcons (const QIcon &orig) const
virtual void extensionStartRestoring ()
virtual void extensionFinishRestoring ()
virtual bool extensionGetElementPicked (const SoPickedPoint *, std::string &) const
virtual bool extensionGetDetailPath (const char *, SoFullPath *, SoDetail *&) const
Public Member Functions inherited from App::Extension
virtual Base::Type getExtensionTypeId (void) const
Extension ()=default
virtual ~Extension ()
virtual void initExtension (App::ExtensionContainer *obj)
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Public Member Functions inherited from PartGui::ViewProviderAttachExtension
ViewProviderAttachExtension ()
Constructor.
~ViewProviderAttachExtension () override=default
QIcon extensionMergeColorfullOverlayIcons (const QIcon &orig) const override
void extensionUpdateData (const App::Property *) override
void extensionSetupContextMenu (QMenu *, QObject *, const char *) override
void showAttachmentEditor ()
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Public Attributes
Properties
App::PropertyBool Autoconstraints
App::PropertyBool AvoidRedundant
App::PropertyPythonObject TempoVis
App::PropertyBool HideDependent
App::PropertyBool ShowLinks
App::PropertyBool ShowSupport
App::PropertyBool RestoreCamera
App::PropertyBool ForceOrtho
App::PropertyBool SectionView
App::PropertyBool AutoColor
App::PropertyString EditingWorkbench
SketcherGui::PropertyVisualLayerList VisualLayerList
const ToolManager toolManager
Signals for controlling information in Task dialogs
boost::signals2::signal< void()> signalConstraintsChanged
signals if the constraints list has changed
boost::signals2::signal< void(const QString &state, const QString &msg, const QString &url, const QString &linkText)> signalSetUp
signals if the sketch has been set up
boost::signals2::signal< void()> signalElementsChanged
signals if the elements list has changed
Public Attributes inherited from PartGui::ViewProviderPartExt
App::PropertyFloatConstraint Deviation
App::PropertyBool ControlPoints
App::PropertyAngle AngularDeflection
App::PropertyEnumeration Lighting
App::PropertyEnumeration DrawStyle
App::PropertyFloatConstraint PointSize
App::PropertyColor PointColor
App::PropertyMaterial PointMaterial
App::PropertyColorList PointColorArray
App::PropertyFloatConstraint LineWidth
App::PropertyColor LineColor
App::PropertyMaterial LineMaterial
App::PropertyColorList LineColorArray
Public Attributes inherited from Gui::ViewProviderGeometryObject
App::PropertyPercent Transparency
App::PropertyMaterialList ShapeAppearance
App::PropertyBool BoundingBox
App::PropertyBool Selectable
Public Attributes inherited from Gui::ViewProviderDragger
App::PropertyPlacement TransformOrigin
Public Attributes inherited from Gui::ViewProviderDocumentObject
App::PropertyEnumeration DisplayMode
App::PropertyBool Visibility
App::PropertyBool ShowInTree
App::PropertyEnumeration OnTopWhenSelected
App::PropertyEnumeration SelectionStyle
Public Attributes inherited from Gui::ViewProvider
boost::signals2::signal< void()> signalChangeIcon
signal on icon change
boost::signals2::signal< void(const QString &)> signalChangeToolTip
signal on tooltip change
boost::signals2::signal< void(const QString &)> signalChangeStatusTip
signal on status tip change
boost::signals2::signal< void(bool, Gui::HighlightMode)> signalChangeHighlight
signal on highlight change
Public Attributes inherited from PartGui::ViewProviderGridExtension
App::PropertyBool ShowGrid
App::PropertyLength GridSize
App::PropertyBool GridAuto
Protected Member Functions
miscelanea editing functions
void deactivateHandler ()
purges the DrawHandler if existing and tidies up
void editDoubleClicked ()
get called if a subelement is double clicked while editing
void toggleWireSelelection (int geoId)
get called when an edge is double clicked to select/unselect the whole wire
manage updates during undo/redo operations
void slotUndoDocument (const Gui::Document &)
void slotRedoDocument (const Gui::Document &)
void slotSolverUpdate ()
void forceUpdateData ()
Protected Member Functions inherited from PartGui::ViewProviderPart
void applyColor (const Part::ShapeHistory &hist, const std::vector< App::Color > &colBase, std::vector< App::Color > &colBool)
void applyMaterial (const Part::ShapeHistory &hist, const std::vector< App::Material > &colBase, std::vector< App::Material > &colBool)
void applyTransparency (float transparency, std::vector< App::Color > &colors)
void applyTransparency (float transparency, std::vector< App::Material > &colors)
Protected Member Functions inherited from PartGui::ViewProviderPartExt
bool loadParameter ()
void updateVisual ()
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container. This method is typically called if the property on file has changed its name in more recent versions.
Protected Member Functions inherited from Gui::ViewProviderGeometryObject
void setSelectable (bool Selectable=true)
virtual unsigned long getBoundColor () const
void setCoinAppearance (const App::Material &source)
Protected Member Functions inherited from Gui::ViewProviderDragger
bool forwardToLink ()
virtual TaskView::TaskDialog * getTransformDialog ()
Protected Member Functions inherited from Gui::ViewProviderDocumentObject
Gui::MDIView * getActiveView () const
Gui::MDIView * getEditingView () const
Gui::MDIView * getInventorView () const
Gui::MDIView * getViewOfNode (SoNode *node) const
void onBeforeChange (const App::Property *prop) override
get called before the value is changed
SoNode * findFrontRootOfType (const SoType &type) const
bool isAttachedToDocument () const override
const char * detachFromDocument () override
void onPropertyStatusChanged (const App::Property &prop, unsigned long oldStatus) override
get called when a property status has changed
void setModeSwitch () override
Turn on mode switch.
void addDefaultAction (QMenu *, const QString &)
Protected Member Functions inherited from Gui::ViewProvider
virtual QIcon mergeGreyableOverlayIcons (const QIcon &orig) const
int getEditingMode () const
return the edit mode or -1 if nothing is being edited
bool checkRecursion (SoNode *)
SoPickedPoint * getPointOnRay (const SbVec2s &pos, const View3DInventorViewer *viewer) const
SoPickedPoint * getPointOnRay (const SbVec3f &pos, const SbVec3f &dir, const View3DInventorViewer *viewer) const
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual void onEarlyChange (const Property *)
virtual const PropertyData & getPropertyData () const
Protected Member Functions inherited from PartGui::ViewProviderGridExtension
void extensionOnChanged (const App::Property *) override
void setGridSizePixelThreshold (int value)
void setGridNumberSubdivision (int value)
void setGridLinePattern (int pattern)
void setGridDivLinePattern (int pattern)
void setGridLineWidth (int width)
void setGridDivLineWidth (int width)
void setGridLineColor (const App::Color &color)
void setGridDivLineColor (const App::Color &color)
bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, App::Property *prop) override
returns true if the property type change was handled by the extension.
Protected Member Functions inherited from App::Extension
virtual const App::PropertyData & extensionGetPropertyData (void) const
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
returns true if the property name change was handled by the extension.
void initExtensionType (Base::Type type)
Friends
Attorneys for collaboration with helper classes
class ViewProviderSketchDrawSketchHandlerAttorney
class ViewProviderSketchCoinAttorney
class ViewProviderSketchSnapAttorney
Friends inherited from Gui::ViewProviderDocumentObject
Friends inherited from App::Extension
modus handling
enum SketchMode {
STATUS_NONE, STATUS_SELECT_Point, STATUS_SELECT_Edge, STATUS_SELECT_Constraint,
STATUS_SELECT_Cross, STATUS_SELECT_Wire, STATUS_SKETCH_Drag, STATUS_SKETCH_DragConstraint,
STATUS_SKETCH_UseHandler, STATUS_SKETCH_StartRubberBand, STATUS_SKETCH_UseRubberBand
}
mode table
void setSketchMode (SketchMode mode)
is called by GuiCommands to set the drawing mode
SketchMode getSketchMode () const
get the sketch mode
void generateContextMenu ()
Selection functions
bool isSelectable () const override
Is the view provider selectable.
void onSelectionChanged (const Gui::SelectionChanges &msg) override
Observer message from the Selection.
miscelanea utilities
void centerSelection ()
float getScaleFactor () const
returns the scale factor
int getViewOrientationFactor () const
returns view orientation factor
base class implementer
void attach (App::DocumentObject *) override
void updateData (const App::Property *) override
void setupContextMenu (QMenu *menu, QObject *receiver, const char *member) override
set up the context-menu with the supported edit modes
bool onDelete (const std::vector< std::string > &) override
is called when the Provider is in edit and a deletion request occurs
const char * getTransactionText () const override
bool selectAll () override
bool doubleClicked () override
is called by the tree if the user double clicks on the object
bool mouseMove (const SbVec2s &pos, Gui::View3DInventorViewer *viewer) override
is called when the Provider is in edit and the mouse is moved
bool keyPressed (bool pressed, int key) override
is called when the Provider is in edit and a key event ocours. Only ESC ends edit.
bool mouseButtonPressed (int Button, bool pressed, const SbVec2s &cursorPos, const Gui::View3DInventorViewer *viewer) override
is called when the Provider is in edit and the mouse is clicked
bool mouseWheelEvent (int delta, const SbVec2s &cursorPos, const Gui::View3DInventorViewer *viewer) override
void deleteSelected ()
QIcon mergeColorfulOverlayIcons (const QIcon &orig) const override
Control the overlays appearing on the Tree and reflecting different sketcher states.
void onChanged (const App::Property *prop) override
get called by the container whenever a property has been changed
void startRestoring () override
hook after property restoring to change some property statuses
void finishRestoring () override
enter/exit edit mode
bool setEdit (int ModNum) override
is called by the document when the provider goes in edit mode
void unsetEdit (int ModNum) override
is called when you lose the edit mode
void setEditViewer (Gui::View3DInventorViewer *, int ModNum) override
adjust viewer settings when editing a view provider
void unsetEditViewer (Gui::View3DInventorViewer *) override
restores viewer settings when leaving editing mode
void onCameraChanged (SoCamera *cam)
static void camSensCB (void *data, SoSensor *)
static void camSensDeleteCB (void *data, SoSensor *)
Solver Information
void UpdateSolverInformation ()
update solver information based on last solving at SketchObject
static QString appendConstraintMsg (const QString &singularmsg, const QString &pluralmsg, const std::vector< int > &vector)
Additional Inherited Members
Public Types inherited from Gui::ViewProvider
enum EditMode { Default = 0, Transform, Cutting, Color }
Public Types inherited from App::ExtensionContainer
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Static Public Member Functions inherited from Gui::ViewProviderDragger
static void updateTransform (const Base::Placement &from, SoTransform *to)
Static Public Member Functions inherited from Gui::ViewProvider
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
static SbMatrix convert (const Base::Matrix4D &rcMatrix)
static Base::Matrix4D convert (const SbMatrix &sbMat)
static void eventCallback (void *ud, SoEventCallback *node)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Member Functions inherited from App::Extension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Static Protected Member Functions inherited from App::Extension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Protected Attributes inherited from PartGui::ViewProviderPartExt
SoMaterialBinding * pcFaceBind
SoMaterialBinding * pcLineBind
SoMaterialBinding * pcPointBind
SoMaterial * pcLineMaterial
SoMaterial * pcPointMaterial
SoDrawStyle * pcLineStyle
SoDrawStyle * pcPointStyle
SoShapeHints * pShapeHints
SoCoordinate3 * coords
SoBrepFaceSet * faceset
SoNormal * norm
SoNormalBinding * normb
SoBrepEdgeSet * lineset
SoBrepPointSet * nodeset
bool VisualTouched
bool NormalsFromUV
Protected Attributes inherited from Gui::ViewProviderGeometryObject
SoMaterial * pcShapeMaterial {nullptr}
SoFCBoundingBox * pcBoundingBox {nullptr}
SoSwitch * pcBoundSwitch {nullptr}
SoBaseColor * pcBoundColor {nullptr}
SoPickStyle * pickStyle {nullptr}
App::Material materialAppearance
Protected Attributes inherited from Gui::ViewProviderDragger
CoinPtr< SoFCCSysDragger > csysDragger = nullptr
ViewProvider * forwardedViewProvider = nullptr
Protected Attributes inherited from Gui::ViewProviderDocumentObject
App::DocumentObject * pcObject {nullptr}
Gui::Document * pcDocument {nullptr}
Protected Attributes inherited from Gui::ViewProvider
SoSeparator * pcRoot
The root Separator of the ViewProvider.
SoTransform * pcTransform
this is transformation for the provider
const char * sPixmap
SoSwitch * pcModeSwitch
this is the mode switch, all the different viewing modes are collected here
SoSeparator * pcAnnotation {nullptr}
The root separator for annotations.
ViewProviderPy * pyViewObject {nullptr}
std::string overrideMode
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Detailed Description
The Sketch ViewProvider.
As any ViewProvider, this class is responsible for the view representation of Sketches.
Functionality inherited from parent classes deal with the majority of the representation of a sketch when it is ** not ** in edit mode.
This class handles mainly the drawing and editing of the sketch.
The class delegates a substantial part of this functionality on two main classes, DrawSketchHandler and EditModeCoinManager.
In order to enforce a certain degree of encapsulation and promote a not too tight coupling, while still allowing well defined collaboration, DrawSketchHandler and EditModeCoinManager access ViewProviderSketch via two Attorney classes (Attorney-Client pattern), ViewProviderSketchDrawSketchHandlerAttorney and ViewProviderSketchCoinAttorney.
Given the substantial amount of code involved in coin node management, EditModeCoinManager further delegates on other specialised helper classes. Some of them share the ViewProviderSketchCoinAttorney, which defines the maximum coupling and minimum encapsulation.
DrawSketchHandler aids temporary edit mode drawing and is extensively used for the creation of geometry.
EditModeCoinManager takes over the responsibility of creating the Coin (Inventor) scenograph and modifying it, including all the drawing of geometry, constraints and overlay layer. This is an exclusive responsibility under the Single Responsibility Principle.
EditModeCoinManager exposes a public interface to be used by ViewProviderSketch. Where, EditModeCoinManager needs special access to facilities of ViewProviderSketch in order to fulfil its responsibility, this access is defined by ViewProviderSketchCoinAttorney.
Similarly, DrawSketchHandler takes over the responsibility of drawing edit temporal curves and markers necessary to enable visual feedback to the user, as well as the UI interaction during such edits. This is its exclusive responsibility under the Single Responsibility Principle.
A plethora of speciliased handlers derive from DrawSketchHandler for each specialised editing (see for example all the handlers for creation of new geometry). These derived classes do * not * have direct access to the ViewProviderSketchDrawSketchHandlerAttorney. This is intended to keep coupling under control. However, generic functionality requiring access to the Attorney can be implemented in DrawSketchHandler and used from its derived classes by virtue of the inheritance. This promotes a concentrating the coupling in a single point (and code reuse).
Definition at line 147 of file ViewProviderSketch.h.
Member Enumeration Documentation
SketchMode
enum SketcherGui::ViewProviderSketch::SketchMode
mode table
Enumerator
STATUS_NONE
enum value View provider is in neutral.
STATUS_SELECT_Point
enum value a point was selected.
STATUS_SELECT_Edge
enum value an edge was selected.
STATUS_SELECT_Constraint
enum value a constraint was selected.
STATUS_SELECT_Cross
enum value the base coordinate system was selected.
STATUS_SELECT_Wire
enum value and edge was double clicked.
STATUS_SKETCH_Drag
enum value while dragging curves and or points.
STATUS_SKETCH_DragConstraint
enum value while dragging a compatible constraint.
STATUS_SKETCH_UseHandler
enum value a DrawSketchHandler is in control.
STATUS_SKETCH_StartRubberBand
enum value for initiating a rubber band selection
STATUS_SKETCH_UseRubberBand
enum value when making a rubber band selection
Definition at line 535 of file ViewProviderSketch.h.
Constructor & Destructor Documentation
ViewProviderSketch()
ViewProviderSketch::ViewProviderSketch ()
constructor
Definition at line 482 of file ViewProviderSketch.cpp.
References ADD_PROPERTY_TYPE, AutoColor, Autoconstraints, AvoidRedundant, camSensCB(), EditingWorkbench, ForceOrtho, HideDependent, App::Extension::initExtension(), importers.importIFCmulticore::layers, Path.Post.scripts.opensbp_post::move(), PartGui::ViewProviderPartExt::PointSize, App::Prop_None, App::Prop_ReadOnly, RestoreCamera, SectionView, App::PropertyFloat::setValue(), App::PropertyListsT< T, ListT, ParentT >::setValues(), ShowLinks, ShowSupport, Gui::ViewProvider::sPixmap, TempoVis, and VisualLayerList.
~ViewProviderSketch()
ViewProviderSketch::~ViewProviderSketch () override
destructor
Definition at line 591 of file ViewProviderSketch.cpp.
Member Function Documentation
activateHandler()
void ViewProviderSketch::activateHandler (std::unique_ptr< DrawSketchHandler > newHandler)
sets an DrawSketchHandler in control
Definition at line 628 of file ViewProviderSketch.cpp.
References Path.Post.scripts.opensbp_post::move(), and STATUS_SKETCH_UseHandler.
Referenced by ActivateBSplineHandler(), SketcherGui::ActivateHandler(), and ActivateVirtualSpaceHandler().
appendConstraintMsg()
QString ViewProviderSketch::appendConstraintMsg (const QString & singularmsg, const QString & pluralmsg, const std::vector< int > & vector) static protected
Auxiliary function to generate messages about conflicting, redundant and malformed constraints
Definition at line 3177 of file ViewProviderSketch.cpp.
References SplineSurface::i, and Path.Op.Surface::msg.
attach()
void ViewProviderSketch::attach (App::DocumentObject * pcObject) override virtual
Attaches the document object to this view provider.
Reimplemented from PartGui::ViewProviderPartExt.
Definition at line 2961 of file ViewProviderSketch.cpp.
Referenced by camSensDeleteCB(), and SketcherGui::ViewProviderCustom::updateData().
camSensCB()
void ViewProviderSketch::camSensCB (void * data, SoSensor *) static protected
Definition at line 3509 of file ViewProviderSketch.cpp.
References Base::Console(), and Base::ConsoleSingleton::DeveloperWarning().
Referenced by ViewProviderSketch().
camSensDeleteCB()
void ViewProviderSketch::camSensDeleteCB (void * data, SoSensor * s) static protected
Definition at line 3493 of file ViewProviderSketch.cpp.
References attach(), and toolbit-attributes::s.
Referenced by setEditViewer().
centerSelection()
void ViewProviderSketch::centerSelection ()
Look at the center of the bounding of all selected items
Definition at line 2361 of file ViewProviderSketch.cpp.
References Path.Post.scripts.dynapath_4060_post::action, MengerSponge::box, Gui::ViewProviderDocumentObject::getActiveView(), Gui::View3DInventor::getViewer(), toolbit-attributes::group, and OfflineRenderingUtils::viewer().
Referenced by SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsEmitCenterSelectedItems().
deactivateHandler()
void ViewProviderSketch::deactivateHandler () protected
purges the DrawHandler if existing and tidies up
Definition at line 643 of file ViewProviderSketch.cpp.
References STATUS_NONE.
Referenced by purgeHandler(), and unsetEdit().
deleteSelected()
void ViewProviderSketch::deleteSelected ()
Definition at line 3595 of file ViewProviderSketch.cpp.
References Base::Console(), Base::ConsoleSingleton::DeveloperWarning(), toolbit-attributes::doc, Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), Gui::SelectionSingleton::getSelectionEx(), getSketchObject(), onDelete(), and Gui::Selection().
Referenced by SketcherGui::ShortcutListener::eventFilter().
doubleClicked()
bool ViewProviderSketch::doubleClicked () override virtual
is called by the tree if the user double clicks on the object
Reimplemented from PartGui::ViewProviderPart.
Definition at line 2610 of file ViewProviderSketch.cpp.
References Gui::Application::activeDocument(), Gui::Application::Instance, and Gui::Document::setEdit().
draw()
void ViewProviderSketch::draw (bool temp = false, bool rebuildinformationoverlay = true)
draw the sketch in the inventor nodes temp => use temporary solver solution in SketchObject recreateinformationscenography => forces a rebuild of the information overlay scenography
Definition at line 2786 of file ViewProviderSketch.cpp.
References Sketcher::Sketch::extractGeoListFacade(), Sketcher::GeoListModel< T >::geomlist, Gui::ViewProviderDocumentObject::getActiveView(), Base::BaseClass::getClassTypeId(), Sketcher::SketchObject::getGeoListFacade(), getSketchObject(), getSolvedSketch(), Base::BaseClass::isDerivedFrom(), STATUS_NONE, and STATUS_SKETCH_UseHandler.
Referenced by finishDatumConstraint(), mouseButtonPressed(), onCameraChanged(), onDelete(), and slotSolverUpdate().
editDoubleClicked()
void ViewProviderSketch::editDoubleClicked () protected
get called if a subelement is double clicked while editing
Definition at line 1224 of file ViewProviderSketch.cpp.
References Base::Console(), Sketcher::SketchObject::Constraints, SketcherGui::EditDatumDialog::exec(), getSketchObject(), Sketcher::PropertyConstraintList::getValues(), SplineSurface::id, Sketcher::Constraint::isDimensional(), Base::ConsoleSingleton::Log(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, and STATUS_SELECT_Wire.
Referenced by mouseButtonPressed().
finishRestoring()
void SketcherGui::ViewProviderSketch::finishRestoring () override protected virtual
Reimplemented from PartGui::ViewProviderPartExt.
Definition at line 2937 of file ViewProviderSketch.cpp.
References AutoColor, SCL.SimpleDataTypes::f, App::PropertyBool::getValue(), App::PropertyColor::getValue(), App::Property::isTouched(), PartGui::ViewProviderPartExt::LineColor, PartGui::ViewProviderPartExt::PointColor, and App::PropertyBool::setValue().
forceUpdateData()
void ViewProviderSketch::forceUpdateData () protected
Definition at line 618 of file ViewProviderSketch.cpp.
References getSketchObject(), and Gui::Command::updateActive().
Referenced by slotRedoDocument(), and slotUndoDocument().
generateContextMenu()
void ViewProviderSketch::generateContextMenu ()
Definition at line 4117 of file ViewProviderSketch.cpp.
References Gui::ViewProviderDocumentObject::getActiveView(), Base::Persistence::getClassTypeId(), Sketcher::SketchObject::getGeometry(), SketcherGui::getIdsFromName(), Gui::MenuManager::getInstance(), Gui::ViewProviderDocumentObject::getObject(), Gui::SelectionSingleton::getSelectionEx(), getSketchObject(), Gui::Application::Instance, Base::BaseClass::is(), SketcherGui::isBsplineKnotOrEndPoint(), Sketcher::isLineSegment(), NavigationIndicatorGui::menu, App::Extension::name(), RobotExample::pos, Gui::Selection(), Gui::MenuManager::setupContextMenu(), and Gui::Application::setupContextMenu().
Referenced by mouseButtonPressed().
getIsShownVirtualSpace()
bool ViewProviderSketch::getIsShownVirtualSpace () const
returns whether the virtual space is being shown
Definition at line 2842 of file ViewProviderSketch.cpp.
Referenced by SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsItemChanged().
getScaleFactor()
float ViewProviderSketch::getScaleFactor () const
returns the scale factor
Definition at line 2616 of file ViewProviderSketch.cpp.
References Gui::Application::editViewOfNode(), SCL.SimpleDataTypes::f, Base::BaseClass::getClassTypeId(), Gui::Application::Instance, Base::BaseClass::isDerivedFrom(), draftfunctions.scale::scale(), and OfflineRenderingUtils::viewer().
Referenced by finishDatumConstraint(), and SketcherGui::DrawSketchHandler::seekAutoConstraint().
getSketchMode()
SketchMode SketcherGui::ViewProviderSketch::getSketchMode () const inline
get the sketch mode
Definition at line 556 of file ViewProviderSketch.h.
Referenced by isCreateConstraintActive(), SketcherGui::isSketcherBSplineActive(), isSketcherVirtualSpaceActive(), SketcherGui::TaskDlgEditSketch::reject(), and SketcherGui::ReleaseHandler().
getSketchObject()
Sketcher::SketchObject * ViewProviderSketch::getSketchObject () const
get the pointer to the sketch document object
Definition at line 3585 of file ViewProviderSketch.cpp.
References Gui::ViewProviderDocumentObject::pcObject.
Referenced by CmdSketcherConstrainLock::applyConstraint(), CmdSketcherConstrainDistance::applyConstraint(), CmdSketcherConstrainDistanceX::applyConstraint(), CmdSketcherConstrainDistanceY::applyConstraint(), CmdSketcherConstrainParallel::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainRadiam::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), CmdSketcherConstrainCoincidentUnified::applyConstraintCoincident(), CmdSketcherConstrainCoincidentUnified::applyConstraintPointOnObject(), SketcherGui::DrawSketchHandler::createAutoConstraints(), deleteSelected(), draw(), SketcherGui::DrawSketchHandlerExtend::DrawSketchHandlerExtend(), SketcherGui::EditDatumDialog::EditDatumDialog(), editDoubleClicked(), forceUpdateData(), generateContextMenu(), SketcherGui::DrawSketchHandler::getHighestCurveIndex(), SketcherGui::DrawSketchHandler::getHighestVertexIndex(), getSketchObject(), SketcherGui::DrawSketchHandler::getSketchObject(), getSolvedSketch(), mergeColorfulOverlayIcons(), mouseButtonPressed(), mouseMove(), onDelete(), SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsItemChanged(), SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsItemSelectionChanged(), SketcherGui::TaskSketcherElements::onListWidgetElementsItemPressed(), SketcherGui::TaskSketcherElements::onListWidgetElementsMouseMoveOnItem(), SketcherGui::TaskSketcherElements::onSelectionChanged(), SketcherGui::TaskSketcherConstraints::onSelectionChanged(), onSelectionChanged(), SketcherGui::DrawSketchHandlerTrimming::pressButton(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), setEdit(), setEditViewer(), slotSolverUpdate(), SketcherGui::SnapManager::snapToObject(), SketcherGui::TaskSketcherMessages::TaskSketcherMessages(), toggleWireSelelection(), unsetEdit(), updateData(), SketcherGui::TaskSketcherSolverAdvanced::updateDefaultMethodParameters(), SketcherGui::TaskSketcherSolverAdvanced::updateRedundantMethodParameters(), SketcherGui::TaskSketcherSolverAdvanced::updateSketchObject(), and UpdateSolverInformation().
getSolvedSketch()
const Sketcher::Sketch & ViewProviderSketch::getSolvedSketch () const
returns a const reference to the last solved sketch object. It guarantees that the solver object does not lose synchronisation with the SketchObject properties.
NOTE: Operations requiring * write * access to the solver must be done via SketchObject interface. See for example functions: -> inline void setRecalculateInitialSolutionWhileMovingPoint(bool recalculateInitialSolutionWhileMovingPoint) -> inline int initTemporaryMove(int geoId, PointPos pos, bool fine=true) -> inline int moveGeometryTemporary(int geoId, PointPos pos, Base::Vector3d toPoint, bool relative=false) -> inline void updateSolverExtension(int geoId, std::unique_ptr<Part::GeometryExtension> && ext)
Definition at line 3590 of file ViewProviderSketch.cpp.
References getSketchObject().
Referenced by draw(), mouseMove(), and slotSolverUpdate().
getTransactionText()
const char* SketcherGui::ViewProviderSketch::getTransactionText () const inline override virtual
Is called by the tree if the user double clicks on the object. It returns the string for the transaction that will be shown in the undo/redo dialog. If null is returned then no transaction will be opened.
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 644 of file ViewProviderSketch.h.
getViewOrientationFactor()
int ViewProviderSketch::getViewOrientationFactor () const
returns view orientation factor
Definition at line 4020 of file ViewProviderSketch.cpp.
isSelectable()
bool ViewProviderSketch::isSelectable () const override virtual
Is the view provider selectable.
Reimplemented from Gui::ViewProviderGeometryObject.
Definition at line 2063 of file ViewProviderSketch.cpp.
References Gui::ViewProvider::isEditing(), and Gui::ViewProviderGeometryObject::isSelectable().
keyPressed()
bool ViewProviderSketch::keyPressed (bool pressed, int key) override virtual
is called when the Provider is in edit and a key event ocours. Only ESC ends edit.
Reimplemented from Gui::ViewProvider.
Definition at line 753 of file ViewProviderSketch.cpp.
References STATUS_NONE.
mergeColorfulOverlayIcons()
QIcon ViewProviderSketch::mergeColorfulOverlayIcons (const QIcon & orig) const override virtual
Control the overlays appearing on the Tree and reflecting different sketcher states.
Reimplemented from Gui::ViewProvider.
Definition at line 3782 of file ViewProviderSketch.cpp.
References Gui::BitmapFactory(), Gui::BitmapFactoryInst::BottomRight, getSketchObject(), Gui::ViewProvider::mergeColorfulOverlayIcons(), and Gui::BitmapFactoryInst::mergePixmap().
mouseButtonPressed()
bool ViewProviderSketch::mouseButtonPressed (int Button, bool pressed, const SbVec2s & cursorPos, const Gui::View3DInventorViewer * viewer) override virtual
is called when the Provider is in edit and the mouse is clicked
Reimplemented from Gui::ViewProvider.
Definition at line 876 of file ViewProviderSketch.cpp.
References Gui::SelectionSingleton::clearSelection(), Sketcher::Constraint::clone(), Gui::Document::commitCommand(), Sketcher::SketchObject::Constraints, draw(), editDoubleClicked(), generateContextMenu(), Sketcher::PropertyConstraintList::getConstraintName(), Gui::ViewProviderDocumentObject::getDocument(), Gui::ViewProvider::getPointOnRay(), getSketchObject(), getValue(), SplineSurface::id, Path.Post.scripts.opensbp_post::move(), Gui::Document::openCommand(), updateLeaderLines::point, RobotExample::pos, Arch::QT_TRANSLATE_NOOP, Gui::Selection(), Sketcher::PropertyConstraintList::setValues(), STATUS_NONE, STATUS_SELECT_Constraint, STATUS_SELECT_Cross, STATUS_SELECT_Edge, STATUS_SELECT_Point, STATUS_SELECT_Wire, STATUS_SKETCH_Drag, STATUS_SKETCH_DragConstraint, STATUS_SKETCH_StartRubberBand, STATUS_SKETCH_UseHandler, STATUS_SKETCH_UseRubberBand, toggleWireSelelection(), SketcherGui::tryAutoRecomputeIfNotSolve(), OfflineRenderingUtils::viewer(), MovieTool::x, and MovieTool::y.
mouseMove()
bool ViewProviderSketch::mouseMove (const SbVec2s & pos, Gui::View3DInventorViewer * viewer) override virtual
is called when the Provider is in edit and the mouse is moved
Reimplemented from Gui::ViewProvider.
Definition at line 1323 of file ViewProviderSketch.cpp.
References KDL::abs(), Sketcher::SketchObject::getGeoVertexIndex(), Gui::ViewProvider::getPointOnRay(), getSketchObject(), getSolvedSketch(), getValue(), Sketcher::none, RobotExample::pos, STATUS_NONE, STATUS_SELECT_Constraint, STATUS_SELECT_Edge, STATUS_SELECT_Point, STATUS_SKETCH_Drag, STATUS_SKETCH_DragConstraint, STATUS_SKETCH_StartRubberBand, STATUS_SKETCH_UseHandler, STATUS_SKETCH_UseRubberBand, updateColor(), OfflineRenderingUtils::viewer(), MovieTool::x, and MovieTool::y.
mouseWheelEvent()
bool ViewProviderSketch::mouseWheelEvent (int delta, const SbVec2s & cursorPos, const Gui::View3DInventorViewer * viewer) override virtual
Reimplemented from Gui::ViewProvider.
Definition at line 1210 of file ViewProviderSketch.cpp.
References OfflineRenderingUtils::viewer().
onCameraChanged()
void ViewProviderSketch::onCameraChanged (SoCamera * cam) protected
Definition at line 3524 of file ViewProviderSketch.cpp.
References Base::Console(), draw(), PartGui::ViewProviderGridExtension::drawGrid(), Gui::ViewProviderDocumentObject::getActiveView(), Gui::ViewProviderDocumentObject::getDocument(), Gui::View3DInventor::getViewer(), Gui::View3DInventorViewer::getViewportOnXYPlaneOfPlacement(), Base::Interpreter(), Base::ConsoleSingleton::Log(), and Base::InterpreterSingleton::runStringObject().
onChanged()
void ViewProviderSketch::onChanged (const App::Property * prop) override protected virtual
get called by the container whenever a property has been changed
Reimplemented from PartGui::ViewProviderPartExt.
Definition at line 2899 of file ViewProviderSketch.cpp.
References AutoColor, App::PropertyBool::getValue(), App::Property::Hidden, PartGui::ViewProviderPartExt::LineColor, PartGui::ViewProviderPartExt::PointColor, App::Property::ReadOnly, App::Property::setStatus(), App::Property::Transient, and VisualLayerList.
Referenced by SketcherGui::ViewProviderCustom::onChanged().
onDelete()
bool ViewProviderSketch::onDelete (const std::vector< std::string > & subList) override virtual
is called when the Provider is in edit and a deletion request occurs
Reimplemented from Gui::ViewProvider.
Definition at line 3622 of file ViewProviderSketch.cpp.
References Gui::SelectionSingleton::clearSelection(), Gui::cmdAppObjectArgs(), Sketcher::Coincident, Base::Console(), Sketcher::SketchObject::Constraints, Base::ConsoleSingleton::DeveloperError(), draw(), SCL.SimpleDataTypes::e, Sketcher::GeoUndef, Sketcher::SketchObject::getGeoVertexIndex(), Sketcher::PropertyConstraintList::getIndexFromConstraintName(), Gui::ViewProviderDocumentObject::getObject(), getSketchObject(), Sketcher::PropertyConstraintList::getValues(), Gui::ViewProvider::onDelete(), Sketcher::RefExt, Sketcher::RtPnt, Gui::Selection(), signalConstraintsChanged, signalElementsChanged, Sketcher::SketchObject::solve(), Sketcher::start, Gui::Command::updateActive(), updateColor(), and UpdateSolverInformation().
Referenced by deleteSelected().
onSelectionChanged()
void ViewProviderSketch::onSelectionChanged (const Gui::SelectionChanges & msg) override virtual
Observer message from the Selection.
Implements Gui::SelectionObserver.
Definition at line 2071 of file ViewProviderSketch.cpp.
References Gui::SelectionChanges::AddSelection, Gui::SelectionChanges::ClrSelection, Gui::ViewProviderDocumentObject::getDocument(), Sketcher::PropertyConstraintList::getIndexFromConstraintName(), Gui::ViewProviderDocumentObject::getObject(), getSketchObject(), Sketcher::HAxis, Path.Op.Surface::msg, Gui::SelectionChanges::RmvPreselect, Gui::SelectionChanges::RmvSelection, Sketcher::RtPnt, Gui::SelectionChanges::SetPreselect, Gui::SelectionChanges::SetSelection, STATUS_SKETCH_UseHandler, updateColor(), and Sketcher::VAxis.
purgeHandler()
void ViewProviderSketch::purgeHandler ()
removes the active handler
Definition at line 654 of file ViewProviderSketch.cpp.
References Gui::SelectionSingleton::clearSelection(), deactivateHandler(), Gui::Application::editDocument(), Gui::Document::getActiveView(), Gui::Application::Instance, Gui::Selection(), and OfflineRenderingUtils::viewer().
Referenced by SketcherGui::DrawSketchHandler::activate(), ActivateBSplineHandler(), SketcherGui::ActivateHandler(), ActivateVirtualSpaceHandler(), SketcherGui::DrawSketchHandler::quit(), SketcherGui::TaskDlgEditSketch::reject(), DrawSketchHandlerBSplineInsertKnot::releaseButton(), DrawSketchHandlerCopy::releaseButton(), DrawSketchHandlerRectangularArray::releaseButton(), and SketcherGui::ReleaseHandler().
registerToolChanged()
template<typename F > boost::signals2::connection SketcherGui::ViewProviderSketch::registerToolChanged (F && f) inline
Definition at line 687 of file ViewProviderSketch.h.
References SCL.SimpleDataTypes::f.
Referenced by SketcherGui::TaskDlgEditSketch::TaskDlgEditSketch().
selectAll()
bool ViewProviderSketch::selectAll () override virtual
is called when the provider is in edit and a "Select All" command was issued Provider shall return 'false' is it ignores the command, 'true' otherwise
Reimplemented from Gui::ViewProvider.
Definition at line 2604 of file ViewProviderSketch.cpp.
setAngleSnapping()
void ViewProviderSketch::setAngleSnapping (bool enable, Base::Vector2d referencePoint = Base::Vector2d(0., 0.))
Toggle angle snapping and set the reference point.
Definition at line 798 of file ViewProviderSketch.cpp.
setEdit()
bool ViewProviderSketch::setEdit (int ModNum) override protected virtual
is called by the document when the provider goes in edit mode
Reimplemented from PartGui::ViewProviderPartExt.
Definition at line 2973 of file ViewProviderSketch.cpp.
References Gui::ControlSingleton::activeDialog(), Gui::Command::addModule(), Gui::SelectionObserver::attachSelection(), draftgeoutils.faces::bind(), MengerSponge::box, Gui::SelectionSingleton::clearSelection(), Gui::ControlSingleton::closeDialog(), Base::Console(), Gui::Control(), Base::ConsoleSingleton::DeveloperError(), Base::ConsoleSingleton::DeveloperWarning(), SCL.SimpleDataTypes::e, Gui::Application::editDocument(), SketcherGui::Workbench::enterEditMode(), Sketcher::SketchObject::evaluateConstraints(), Gui::ViewProviderDocumentObject::getDocument(), PartGui::ViewProviderGridExtension::getGridNode(), Gui::getMainWindow(), Gui::Command::getObjectCmd(), Base::Placement::getPosition(), Base::Placement::getRotation(), getSketchObject(), SketcherGui::TaskDlgEditSketch::getSketchView(), Gui::Command::Gui, Gui::Application::Instance, App::DocumentObject::isFreezed(), SketcherGui::TaskDlgEditSketch::registerToolWidgetChanged(), Gui::SelectionSingleton::rmvPreselect(), runCommand, Gui::Selection(), PartGui::ViewProviderGridExtension::setGridEnabled(), PartGui::ViewProviderGridExtension::setGridOrientation(), Sketcher::SketchObject::setRecalculateInitialSolutionWhileMovingPoint(), Gui::ControlSingleton::showDialog(), Gui::Document::signalRedoDocument, Sketcher::SketchObject::signalSolverUpdate, Gui::Document::signalUndoDocument, slotRedoDocument(), slotSolverUpdate(), slotUndoDocument(), Sketcher::SketchObject::solve(), Sketcher::SketchObject::validateExternalLinks(), and Gui::ViewProviderDocumentObject::ViewProviderDocumentObject().
setEditViewer()
void ViewProviderSketch::setEditViewer (Gui::View3DInventorViewer * , int ModNum) override protected virtual
adjust viewer settings when editing a view provider
Reimplemented from Gui::ViewProviderDragger.
Definition at line 3373 of file ViewProviderSketch.cpp.
References camSensDeleteCB(), Base::Console(), Base::ConsoleSingleton::DeveloperError(), DraftVecUtils::dist(), dot(), SCL.SimpleDataTypes::e, Gui::Application::editDocument(), App::GetApplication(), ParameterGrp::GetBool(), Gui::ViewProviderDocumentObject::getDocument(), App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), App::Application::GetParameterGroupByPath(), Base::Placement::getPosition(), Base::Placement::getRotation(), getSketchObject(), App::PropertyPythonObject::getValue(), Gui::Command::Gui, Gui::Application::Instance, Init::parent, runCommand, ParameterGrp::SetASCII(), TempoVis, OfflineRenderingUtils::viewer(), and Gui::ViewProviderDocumentObject::ViewProviderDocumentObject().
setIsShownVirtualSpace()
void ViewProviderSketch::setIsShownVirtualSpace (bool isshownvirtualspace)
determines whether the constraints in the normal space or the ones in the virtual are to be shown
Definition at line 2833 of file ViewProviderSketch.cpp.
References signalConstraintsChanged.
setSketchMode()
void SketcherGui::ViewProviderSketch::setSketchMode (SketchMode mode) inline
is called by GuiCommands to set the drawing mode
Definition at line 551 of file ViewProviderSketch.h.
setupContextMenu()
void ViewProviderSketch::setupContextMenu (QMenu * menu, QObject * receiver, const char * method) override virtual
set up the context-menu with the supported edit modes
Reimplemented from PartGui::ViewProviderPartExt.
Definition at line 2966 of file ViewProviderSketch.cpp.
References NavigationIndicatorGui::menu, and Gui::ViewProvider::setupContextMenu().
slotRedoDocument()
void ViewProviderSketch::slotRedoDocument (const Gui::Document &) protected
Definition at line 607 of file ViewProviderSketch.cpp.
References forceUpdateData().
Referenced by setEdit().
slotSolverUpdate()
void ViewProviderSketch::slotSolverUpdate () protected
Definition at line 2871 of file ViewProviderSketch.cpp.
References draw(), Gui::Application::editDocument(), Gui::Document::getActiveView(), Base::BaseClass::getClassTypeId(), getSketchObject(), getSolvedSketch(), Gui::Application::Instance, Base::BaseClass::isDerivedFrom(), signalConstraintsChanged, and UpdateSolverInformation().
Referenced by setEdit().
slotUndoDocument()
void ViewProviderSketch::slotUndoDocument (const Gui::Document &) protected
Definition at line 596 of file ViewProviderSketch.cpp.
References forceUpdateData().
Referenced by setEdit().
startRestoring()
void SketcherGui::ViewProviderSketch::startRestoring () override protected virtual
hook after property restoring to change some property statuses
Reimplemented from PartGui::ViewProviderPartExt.
Definition at line 2930 of file ViewProviderSketch.cpp.
References AutoColor, App::Property::setStatus(), and App::Property::Touched.
toggleWireSelelection()
void ViewProviderSketch::toggleWireSelelection (int geoId) protected
get called when an edge is double clicked to select/unselect the whole wire
Definition at line 1259 of file ViewProviderSketch.cpp.
References DraftVecUtils::find(), Sketcher::SketchObject::getGeometry(), Sketcher::SketchObject::getHighestCurveIndex(), Sketcher::SketchObject::getPoint(), getSketchObject(), TechDraw::isCircle, TechDraw::isEllipse, Sketcher::isPeriodicBSplineCurve(), Sketcher::isPoint(), FreeCADInit::Length, and Path.Post.scripts.grbl_post::type.
Referenced by mouseButtonPressed().
unsetEdit()
void ViewProviderSketch::unsetEdit (int ModNum) override protected virtual
is called when you lose the edit mode
Reimplemented from PartGui::ViewProviderPartExt.
Definition at line 3279 of file ViewProviderSketch.cpp.
References Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::clearSelection(), Gui::ControlSingleton::closeDialog(), Base::Console(), Gui::Control(), deactivateHandler(), Gui::SelectionObserver::detachSelection(), Base::ConsoleSingleton::DeveloperError(), SCL.SimpleDataTypes::e, App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetBool(), Gui::ViewProviderDocumentObject::getDocument(), PartGui::ViewProviderGridExtension::getGridNode(), Gui::ViewProviderDocumentObject::getInventorView(), Gui::getMainWindow(), App::Application::GetParameterGroupByPath(), getSketchObject(), Gui::Command::Gui, SketcherGui::Workbench::leaveEditMode(), Gui::ViewProvider::pcRoot, runCommand, Gui::Selection(), PartGui::ViewProviderGridExtension::setGridEnabled(), Gui::Command::updateActive(), and OfflineRenderingUtils::viewer().
unsetEditViewer()
void ViewProviderSketch::unsetEditViewer (Gui::View3DInventorViewer *) override protected virtual
restores viewer settings when leaving editing mode
Reimplemented from Gui::ViewProviderDragger.
Definition at line 3480 of file ViewProviderSketch.cpp.
References OfflineRenderingUtils::viewer().
updateColor()
void ViewProviderSketch::updateColor ()
helper change the color of the sketch according to selection and solver status
Definition at line 2597 of file ViewProviderSketch.cpp.
Referenced by mouseMove(), onDelete(), and onSelectionChanged().
updateData()
void ViewProviderSketch::updateData (const App::Property * prop) override virtual
Reimplemented from PartGui::ViewProviderPartExt.
Definition at line 2864 of file ViewProviderSketch.cpp.
References SketcherExample::Constraints, getSketchObject(), and signalElementsChanged.
UpdateSolverInformation()
void ViewProviderSketch::UpdateSolverInformation () protected
update solver information based on last solving at SketchObject
Definition at line 3221 of file ViewProviderSketch.cpp.
References SketcherExample::Geometry, Sketcher::SketchObject::getLastDoF(), Sketcher::SketchObject::getLastHasConflicts(), Sketcher::SketchObject::getLastHasMalformedConstraints(), Sketcher::SketchObject::getLastHasPartialRedundancies(), Sketcher::SketchObject::getLastHasRedundancies(), getSketchObject(), intListHelper(), and signalSetUp.
Referenced by onDelete(), and slotSolverUpdate().
updateVirtualSpace()
void SketcherGui::ViewProviderSketch::updateVirtualSpace ()
updates the visibility of the virtual space of constraints
Friends And Related Function Documentation
ViewProviderSketchCoinAttorney
friend class ViewProviderSketchCoinAttorney friend
Definition at line 696 of file ViewProviderSketch.h.
ViewProviderSketchDrawSketchHandlerAttorney
friend class ViewProviderSketchDrawSketchHandlerAttorney friend
Definition at line 695 of file ViewProviderSketch.h.
ViewProviderSketchSnapAttorney
friend class ViewProviderSketchSnapAttorney friend
Definition at line 697 of file ViewProviderSketch.h.
Member Data Documentation
AutoColor
App::PropertyBool SketcherGui::ViewProviderSketch::AutoColor
Definition at line 509 of file ViewProviderSketch.h.
Referenced by finishRestoring(), onChanged(), startRestoring(), and ViewProviderSketch().
Autoconstraints
App::PropertyBool SketcherGui::ViewProviderSketch::Autoconstraints
Definition at line 500 of file ViewProviderSketch.h.
Referenced by SketcherGui::DrawSketchHandler::createAutoConstraints(), SketcherGui::DrawSketchDefaultHandler< ControllerT::HandlerType, ControllerT::SelectModeType, ControllerT::AutoConstraintInitialSize, ControllerT::ContructionMethodType >::onModeChanged(), SketcherGui::TaskSketcherConstraints::onSettingsAutoConstraintsChanged(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), and ViewProviderSketch().
AvoidRedundant
App::PropertyBool SketcherGui::ViewProviderSketch::AvoidRedundant
Definition at line 501 of file ViewProviderSketch.h.
Referenced by ViewProviderSketch().
EditingWorkbench
App::PropertyString SketcherGui::ViewProviderSketch::EditingWorkbench
Definition at line 510 of file ViewProviderSketch.h.
Referenced by ViewProviderSketch().
ForceOrtho
App::PropertyBool SketcherGui::ViewProviderSketch::ForceOrtho
Definition at line 507 of file ViewProviderSketch.h.
Referenced by ViewProviderSketch().
HideDependent
App::PropertyBool SketcherGui::ViewProviderSketch::HideDependent
Definition at line 503 of file ViewProviderSketch.h.
Referenced by ViewProviderSketch().
RestoreCamera
App::PropertyBool SketcherGui::ViewProviderSketch::RestoreCamera
Definition at line 506 of file ViewProviderSketch.h.
Referenced by ViewProviderSketch().
SectionView
App::PropertyBool SketcherGui::ViewProviderSketch::SectionView
Definition at line 508 of file ViewProviderSketch.h.
Referenced by ViewProviderSketch().
ShowLinks
App::PropertyBool SketcherGui::ViewProviderSketch::ShowLinks
Definition at line 504 of file ViewProviderSketch.h.
Referenced by ViewProviderSketch().
ShowSupport
App::PropertyBool SketcherGui::ViewProviderSketch::ShowSupport
Definition at line 505 of file ViewProviderSketch.h.
Referenced by ViewProviderSketch().
signalConstraintsChanged
boost::signals2::signal<void()> SketcherGui::ViewProviderSketch::signalConstraintsChanged
signals if the constraints list has changed
Definition at line 675 of file ViewProviderSketch.h.
Referenced by onDelete(), setIsShownVirtualSpace(), and slotSolverUpdate().
signalElementsChanged
boost::signals2::signal<void()> SketcherGui::ViewProviderSketch::signalElementsChanged
signals if the elements list has changed
Definition at line 681 of file ViewProviderSketch.h.
Referenced by onDelete(), and updateData().
signalSetUp
boost::signals2::signal< void(const QString& state, const QString& msg, const QString& url, const QString& linkText)> SketcherGui::ViewProviderSketch::signalSetUp
signals if the sketch has been set up
Definition at line 679 of file ViewProviderSketch.h.
Referenced by SketcherGui::TaskSketcherMessages::TaskSketcherMessages(), and UpdateSolverInformation().
TempoVis
App::PropertyPythonObject SketcherGui::ViewProviderSketch::TempoVis
Definition at line 502 of file ViewProviderSketch.h.
Referenced by setEditViewer(), and ViewProviderSketch().
toolManager
const ToolManager SketcherGui::ViewProviderSketch::toolManager
Definition at line 514 of file ViewProviderSketch.h.
Referenced by SketcherGui::TaskSketcherTool::toolChanged().
VisualLayerList
SketcherGui::PropertyVisualLayerList SketcherGui::ViewProviderSketch::VisualLayerList
Definition at line 511 of file ViewProviderSketch.h.
Referenced by SketcherGui::EditModeGeometryCoinManager::createEditModeInventorNodes(), onChanged(), SketcherGui::EditModeGeometryCoinManager::processGeometry(), SketcherGui::EditModeGeometryCoinManager::updateGeometryLayersConfiguration(), and ViewProviderSketch().
The documentation for this class was generated from the following files:
ViewProviderSketch.h
ViewProviderSketch.cpp