FreeCAD: FileCardDelegate Class Reference
FileCardDelegate Class Reference
#include <FileCardDelegate.h>
Public Member Functions
FileCardDelegate (QObject *parent=nullptr)
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const override
QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const override
Protected Member Functions
QPixmap generateThumbnail (const QString &path) const
Detailed Description
Definition at line 32 of file FileCardDelegate.h.
Constructor & Destructor Documentation
FileCardDelegate()
FileCardDelegate::FileCardDelegate (QObject * parent = nullptr) explicit
Definition at line 46 of file FileCardDelegate.cpp.
References App::GetApplication(), and App::Application::GetParameterGroupByPath().
Member Function Documentation
generateThumbnail()
QPixmap FileCardDelegate::generateThumbnail (const QString & path) const protected
Definition at line 206 of file FileCardDelegate.cpp.
References ParameterGrp::GetInt(), Start::image, src.Mod.Test.testPathArray::path, and TechDrawTools.TaskFillTemplateFields::reader.
Referenced by paint().
paint()
void FileCardDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const override
Definition at line 85 of file FileCardDelegate.cpp.
References Start::baseName, generateThumbnail(), ParameterGrp::GetInt(), Start::image, src.Mod.Test.testPathArray::path, Start::size, and DraftVecUtils::toString().
sizeHint()
QSize FileCardDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex & index) const override
Definition at line 177 of file FileCardDelegate.cpp.
References ParameterGrp::GetInt().
The documentation for this class was generated from the following files:
FileCardDelegate.h
FileCardDelegate.cpp