FreeCAD: ifc2x3.ifcfuelproperties Class Reference
ifc2x3.ifcfuelproperties Class Reference
Public Member Functions
def __init__ (self, inherited0__material, combustiontemperature, carboncontent, lowerheatingvalue, higherheatingvalue)
def combustiontemperature ()
def carboncontent ()
def lowerheatingvalue ()
def higherheatingvalue ()
Public Member Functions inherited from ifc2x3.ifcmaterialproperties
def __init__ (self, material)
def material ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
combustiontemperature
carboncontent
lowerheatingvalue
higherheatingvalue
Public Attributes inherited from ifc2x3.ifcmaterialproperties
material
Detailed Description
Entity ifcfuelproperties definition.
:param combustiontemperature
:type combustiontemperature:ifcthermodynamictemperaturemeasure
:param carboncontent
:type carboncontent:ifcpositiveratiomeasure
:param lowerheatingvalue
:type lowerheatingvalue:ifcheatingvaluemeasure
:param higherheatingvalue
:type higherheatingvalue:ifcheatingvaluemeasure
Definition at line 32297 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcfuelproperties.__init__ (self, inherited0__material, combustiontemperature, carboncontent, lowerheatingvalue, higherheatingvalue)
Definition at line 32312 of file ifc2x3.py.
Member Function Documentation
carboncontent()
def ifc2x3.ifcfuelproperties.carboncontent ()
Definition at line 32334 of file ifc2x3.py.
References ifc2x3.ifcfuelproperties._carboncontent, ifc2x3.ifcfuelproperties.carboncontent, and SCL.TypeChecker.check_type().
combustiontemperature()
def ifc2x3.ifcfuelproperties.combustiontemperature ()
Definition at line 32320 of file ifc2x3.py.
References ifc2x3.ifcfuelproperties._combustiontemperature, SCL.TypeChecker.check_type(), and ifc2x3.ifcfuelproperties.combustiontemperature.
higherheatingvalue()
def ifc2x3.ifcfuelproperties.higherheatingvalue ()
Definition at line 32362 of file ifc2x3.py.
References ifc2x3.ifcfuelproperties._higherheatingvalue, SCL.TypeChecker.check_type(), and ifc2x3.ifcfuelproperties.higherheatingvalue.
lowerheatingvalue()
def ifc2x3.ifcfuelproperties.lowerheatingvalue ()
Definition at line 32348 of file ifc2x3.py.
References ifc2x3.ifcfuelproperties._lowerheatingvalue, SCL.TypeChecker.check_type(), and ifc2x3.ifcfuelproperties.lowerheatingvalue.
Member Data Documentation
carboncontent
ifc2x3.ifcfuelproperties.carboncontent
Definition at line 32315 of file ifc2x3.py.
Referenced by ifc2x3.ifcfuelproperties.carboncontent().
combustiontemperature
ifc2x3.ifcfuelproperties.combustiontemperature
Definition at line 32314 of file ifc2x3.py.
Referenced by ifc2x3.ifcfuelproperties.combustiontemperature().
higherheatingvalue
ifc2x3.ifcfuelproperties.higherheatingvalue
Definition at line 32317 of file ifc2x3.py.
Referenced by ifc2x3.ifcfuelproperties.higherheatingvalue().
lowerheatingvalue
ifc2x3.ifcfuelproperties.lowerheatingvalue
Definition at line 32316 of file ifc2x3.py.
Referenced by ifc2x3.ifcfuelproperties.lowerheatingvalue().
The documentation for this class was generated from the following file:
ifc2x3.py