FreeCAD: Wm4::IntrSegment3Box3< Real > Class Template Reference
Wm4::IntrSegment3Box3< Real > Class Template Reference
#include <Wm4IntrSegment3Box3.h>
Public Member Functions
IntrSegment3Box3 (const Segment3< Real > &rkSegment, const Box3< Real > &rkBox, bool bSolid)
const Segment3< Real > & GetSegment () const
const Box3< Real > & GetBox () const
virtual bool Test ()
virtual bool Find ()
int GetQuantity () const
const Vector3< Real > & GetPoint (int i) const
Public Member Functions inherited from Wm4::Intersector< Real, Vector3< Real > >
virtual ~Intersector ()
virtual bool Test (Real fTMax, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
virtual bool Find (Real fTMax, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
Real GetContactTime () const
int GetIntersectionType () const
Additional Inherited Members
Public Types inherited from Wm4::Intersector< Real, Vector3< Real > >
enum
Protected Member Functions inherited from Wm4::Intersector< Real, Vector3< Real > >
Intersector ()
Protected Attributes inherited from Wm4::Intersector< Real, Vector3< Real > >
Real m_fContactTime
int m_iIntersectionType
Detailed Description
template<class Real>
class Wm4::IntrSegment3Box3< Real >
Definition at line 29 of file Wm4IntrSegment3Box3.h.
Constructor & Destructor Documentation
IntrSegment3Box3()
template<class Real > Wm4::IntrSegment3Box3< Real >::IntrSegment3Box3 (const Segment3< Real > & rkSegment, const Box3< Real > & rkBox, bool bSolid)
Definition at line 25 of file Wm4IntrSegment3Box3.cpp.
Member Function Documentation
Find()
template<class Real > bool Wm4::IntrSegment3Box3< Real >::Find virtual
Reimplemented from Wm4::Intersector< Real, Vector3< Real > >.
Definition at line 104 of file Wm4IntrSegment3Box3.cpp.
References Wm4::IntrLine3Box3< Real >::DoClipping().
GetBox()
template<class Real > const Box3< Real > & Wm4::IntrSegment3Box3< Real >::GetBox
Definition at line 41 of file Wm4IntrSegment3Box3.cpp.
GetPoint()
template<class Real > const Vector3< Real > & Wm4::IntrSegment3Box3< Real >::GetPoint (int i) const
Definition at line 119 of file Wm4IntrSegment3Box3.cpp.
References SplineSurface::i.
GetQuantity()
template<class Real > int Wm4::IntrSegment3Box3< Real >::GetQuantity
Definition at line 113 of file Wm4IntrSegment3Box3.cpp.
GetSegment()
template<class Real > const Segment3< Real > & Wm4::IntrSegment3Box3< Real >::GetSegment
Definition at line 35 of file Wm4IntrSegment3Box3.cpp.
Test()
template<class Real > bool Wm4::IntrSegment3Box3< Real >::Test virtual
Reimplemented from Wm4::Intersector< Real, Vector3< Real > >.
Definition at line 47 of file Wm4IntrSegment3Box3.cpp.
References Wm4::Vector3< Real >::Cross(), Wm4::Vector3< Real >::Dot(), and Wm4::Math< Real >::FAbs().
Referenced by MeshCore::MeshGeomEdge::IntersectBoundingBox(), and MeshCore::MeshGeomFacet::IntersectBoundingBox().
The documentation for this class was generated from the following files:
Wm4IntrSegment3Box3.h
Wm4IntrSegment3Box3.cpp