FreeCAD: TechDrawGui::PreferencesGui Class Reference
TechDrawGui::PreferencesGui Class Reference
#include <PreferencesGui.h>
Static Public Member Functions
static QFont labelFontQFont ()
static int labelFontSizePX ()
static int dimFontSizePX ()
static QColor normalQColor ()
static QColor selectQColor ()
static QColor preselectQColor ()
static App::Color sectionLineColor ()
static QColor sectionLineQColor ()
static App::Color centerColor ()
static QColor centerQColor ()
static QColor vertexQColor ()
static App::Color leaderColor ()
static QColor leaderQColor ()
static App::Color dimColor ()
static QColor dimQColor ()
static App::Color pageColor ()
static QColor pageQColor ()
static App::Color breaklineColor ()
static QColor breaklineQColor ()
static int dimArrowStyle ()
static double dimArrowSize ()
static double edgeFuzz ()
static QString weldingDirectory ()
static bool showGrid ()
static App::Color gridColor ()
static QColor gridQColor ()
static double gridSpacing ()
static bool multiSelection ()
static QColor getAccessibleQColor (QColor orig)
static QColor lightTextQColor ()
static QColor reverseColor (QColor orig)
static QColor lightenColor (QColor orig)
static double templateClickBoxSize ()
static QColor templateClickBoxColor ()
static int get3dMarkerSize ()
Detailed Description
Definition at line 47 of file PreferencesGui.h.
Member Function Documentation
breaklineColor()
App::Color PreferencesGui::breaklineColor () static
Definition at line 100 of file PreferencesGui.cpp.
References App::Color::setPackedValue().
breaklineQColor()
QColor PreferencesGui::breaklineQColor () static
Definition at line 107 of file PreferencesGui.cpp.
References App::Color::asValue(), and App::Color::setPackedValue().
centerColor()
App::Color PreferencesGui::centerColor () static
Definition at line 115 of file PreferencesGui.cpp.
centerQColor()
QColor PreferencesGui::centerQColor () static
Definition at line 120 of file PreferencesGui.cpp.
References App::Color::asValue().
Referenced by TechDrawGui::TaskCenterLine::getCenterColor(), and TechDrawGui::QGICMark::getCMarkColor().
dimArrowSize()
double PreferencesGui::dimArrowSize () static
Definition at line 164 of file PreferencesGui.cpp.
Referenced by TechDrawGui::QGIArrow::getPrefArrowSize(), and TechDrawGui::QGIWeldSymbol::prefArrowSize().
dimArrowStyle()
int PreferencesGui::dimArrowStyle () static
Definition at line 159 of file PreferencesGui.cpp.
Referenced by TechDrawGui::QGIArrow::getPrefArrowStyle(), TechDrawGui::DlgPrefsTechDrawDimensionsImp::prefArrowStyle(), and TechDrawGui::TaskLeaderLine::setUiPrimary().
dimColor()
App::Color PreferencesGui::dimColor () static
Definition at line 131 of file PreferencesGui.cpp.
References App::Color::setPackedValue().
Referenced by TechDrawGui::ViewProviderDimension::prefColor(), and TechDrawGui::ViewProviderBalloon::ViewProviderBalloon().
dimFontSizePX()
int PreferencesGui::dimFontSizePX () static
Definition at line 62 of file PreferencesGui.cpp.
References TechDrawGui::Rez::guiX().
Referenced by TechDrawGui::QGIWeldSymbol::drawAllAround(), and TechDrawGui::QGIWeldSymbol::drawFieldFlag().
dimQColor()
QColor PreferencesGui::dimQColor () static
Definition at line 138 of file PreferencesGui.cpp.
References App::Color::asValue(), and App::Color::setPackedValue().
Referenced by TechDrawGui::QGIViewDimension::prefNormalColor(), and TechDrawGui::QGIViewBalloon::prefNormalColor().
edgeFuzz()
double PreferencesGui::edgeFuzz () static
Definition at line 170 of file PreferencesGui.cpp.
Referenced by TechDrawGui::QGIDimLines::getEdgeFuzz(), TechDrawGui::QGILeaderLine::getEdgeFuzz(), TechDrawGui::QGIEdge::getEdgeFuzz(), and TechDrawGui::QGEPath::getEdgeFuzz().
get3dMarkerSize()
int PreferencesGui::get3dMarkerSize () static
Definition at line 300 of file PreferencesGui.cpp.
References App::GetApplication(), ParameterGrp::GetInt(), and App::Application::GetParameterGroupByPath().
Referenced by TechDrawGui::QGEPath::showMarkers().
getAccessibleQColor()
QColor PreferencesGui::getAccessibleQColor (QColor orig) static
Definition at line 234 of file PreferencesGui.cpp.
Referenced by TechDrawGui::QGIEdge::getHiddenColor(), TechDrawGui::QGIView::getPreColor(), TechDrawGui::QGIView::getSelectColor(), TechDrawGui::QGITile::getTileColor(), TechDrawGui::QGTracker::getTrackerColor(), TechDrawGui::QGIView::hoverLeaveEvent(), TechDrawGui::QGIView::itemChange(), TechDrawGui::QGISVGTemplate::load(), TechDrawGui::QGILeaderLine::prefNormalColor(), TechDrawGui::QGIView::prefNormalColor(), TechDrawGui::QGIViewDimension::prefNormalColor(), TechDrawGui::QGIViewBalloon::prefNormalColor(), TechDrawGui::QGIFace::QGIFace(), TechDrawGui::QGEPath::showMarkers(), and TechDrawGui::QGIViewSymbol::symbolToSvg().
gridColor()
App::Color PreferencesGui::gridColor () static
Definition at line 192 of file PreferencesGui.cpp.
References App::Color::setPackedValue().
gridQColor()
QColor PreferencesGui::gridQColor () static
Definition at line 199 of file PreferencesGui.cpp.
References App::Color::asValue(), and App::Color::setPackedValue().
Referenced by TechDrawGui::QGVPage::drawForeground().
gridSpacing()
double PreferencesGui::gridSpacing () static
Definition at line 206 of file PreferencesGui.cpp.
Referenced by TechDrawGui::DlgPrefsTechDrawGeneralImp::loadSettings(), and TechDrawGui::ViewProviderPage::ViewProviderPage().
labelFontQFont()
QFont PreferencesGui::labelFontQFont () static
Definition at line 51 of file PreferencesGui.cpp.
Referenced by TechDrawGui::QGIRichAnno::prefFont().
labelFontSizePX()
int PreferencesGui::labelFontSizePX () static
Definition at line 57 of file PreferencesGui.cpp.
References TechDrawGui::Rez::guiX().
Referenced by TechDrawGui::QGITile::makeText(), and MRichTextEdit::MRichTextEdit().
leaderColor()
App::Color PreferencesGui::leaderColor () static
Definition at line 145 of file PreferencesGui.cpp.
References App::Color::setPackedValue().
Referenced by TechDrawGui::ViewProviderRichAnno::getDefLineColor(), TechDrawGui::ViewProviderLeader::getDefLineColor(), TechDrawGui::TaskRichAnno::prefLineColor(), and TechDrawGui::TaskLeaderLine::setUiPrimary().
leaderQColor()
QColor PreferencesGui::leaderQColor () static
Definition at line 152 of file PreferencesGui.cpp.
References App::Color::asValue(), and App::Color::setPackedValue().
Referenced by TechDrawGui::QGIWeldSymbol::prefNormalColor(), and TechDrawGui::QGILeaderLine::prefNormalColor().
lightenColor()
QColor PreferencesGui::lightenColor (QColor orig) static
Definition at line 260 of file PreferencesGui.cpp.
References blue, green, test::m, KDL::max(), KDL::min(), and red.
lightTextQColor()
QColor PreferencesGui::lightTextQColor () static
Definition at line 245 of file PreferencesGui.cpp.
multiSelection()
bool PreferencesGui::multiSelection () static
Definition at line 216 of file PreferencesGui.cpp.
References Gui::SelectionSingleton::getSelectionStyle(), Gui::SelectionSingleton::GreedySelection, and Gui::Selection().
Referenced by TechDrawGui::DlgPrefsTechDrawGeneralImp::loadSettings(), TechDrawGui::QGIPrimPath::mousePressEvent(), TechDrawGui::QGSPage::mousePressEvent(), TechDrawGui::QGIView::mousePressEvent(), TechDrawGui::QGIPrimPath::mouseReleaseEvent(), and TechDrawGui::QGIView::mouseReleaseEvent().
normalQColor()
QColor PreferencesGui::normalQColor () static
Definition at line 67 of file PreferencesGui.cpp.
References App::Color::asValue().
Referenced by TechDrawGui::QGCustomText::getNormalColor(), TechDrawGui::QGIPrimPath::getNormalColor(), TechDrawGui::QGIView::hoverLeaveEvent(), TechDrawGui::QGIView::itemChange(), TechDrawGui::QGIDecoration::prefNormalColor(), TechDrawGui::QGIView::prefNormalColor(), and TechDrawGui::QGIDatumLabel::setPrettyNormal().
pageColor()
App::Color PreferencesGui::pageColor () static
Definition at line 222 of file PreferencesGui.cpp.
References result.
Referenced by pageQColor().
pageQColor()
QColor PreferencesGui::pageQColor () static
Definition at line 229 of file PreferencesGui.cpp.
References App::Color::asValue(), and pageColor().
Referenced by TechDrawGui::QGVPage::drawBackground(), and TechDrawGui::QGIViewBalloon::setPens().
preselectQColor()
QColor PreferencesGui::preselectQColor () static
Definition at line 79 of file PreferencesGui.cpp.
References App::Color::asValue().
Referenced by TechDrawGui::QGCustomText::getPreColor(), TechDrawGui::QGIPrimPath::getPreColor(), TechDrawGui::QGIView::getPreColor(), TechDrawGui::QGIDecoration::prefPreColor(), and TechDrawGui::QGIDatumLabel::setPrettyPre().
reverseColor()
QColor PreferencesGui::reverseColor (QColor orig) static
Definition at line 250 of file PreferencesGui.cpp.
sectionLineColor()
App::Color PreferencesGui::sectionLineColor () static
Definition at line 85 of file PreferencesGui.cpp.
References App::Color::setPackedValue().
Referenced by TechDrawGui::ViewProviderViewPart::prefSectionColor().
sectionLineQColor()
QColor PreferencesGui::sectionLineQColor () static
Definition at line 92 of file PreferencesGui.cpp.
References App::Color::asValue(), and App::Color::setPackedValue().
Referenced by TechDrawGui::QGIHighlight::getHighlightColor(), and TechDrawGui::QGIBreakLine::QGIBreakLine().
selectQColor()
QColor PreferencesGui::selectQColor () static
Definition at line 73 of file PreferencesGui.cpp.
References App::Color::asValue().
Referenced by TechDrawGui::QGCustomText::getSelectColor(), TechDrawGui::QGIPrimPath::getSelectColor(), TechDrawGui::QGIView::getSelectColor(), TechDrawGui::QGIDecoration::prefSelectColor(), and TechDrawGui::QGIDatumLabel::setPrettySel().
showGrid()
bool PreferencesGui::showGrid () static
Definition at line 211 of file PreferencesGui.cpp.
Referenced by TechDrawGui::DlgPrefsTechDrawGeneralImp::loadSettings(), and TechDrawGui::ViewProviderPage::ViewProviderPage().
templateClickBoxColor()
QColor PreferencesGui::templateClickBoxColor () static
Definition at line 293 of file PreferencesGui.cpp.
References App::Color::asValue(), and App::Color::setPackedValue().
Referenced by TechDrawGui::QGISVGTemplate::createClickHandles().
templateClickBoxSize()
double PreferencesGui::templateClickBoxSize () static
Definition at line 287 of file PreferencesGui.cpp.
vertexQColor()
QColor PreferencesGui::vertexQColor () static
Definition at line 126 of file PreferencesGui.cpp.
Referenced by TechDrawGui::QGIVertex::QGIVertex().
weldingDirectory()
QString PreferencesGui::weldingDirectory () static
Definition at line 175 of file PreferencesGui.cpp.
References Base::Console(), App::Application::getResourceDir(), Base::FileInfo::isReadable(), and Base::ConsoleSingleton::Warning().
Referenced by TechDrawGui::TaskWeldingSymbol::setUiEdit(), and TechDrawGui::TaskWeldingSymbol::setUiPrimary().
The documentation for this class was generated from the following files:
PreferencesGui.h
PreferencesGui.cpp