FreeCAD: GCS::ArcOfHyperbola Class Reference
GCS::ArcOfHyperbola Class Reference
#include <Geo.h>
Public Member Functions
ArcOfHyperbola ()
~ArcOfHyperbola () override
int PushOwnParams (VEC_pD &pvec) override
void ReconstructOnNewPvec (VEC_pD &pvec, int &cnt) override
ArcOfHyperbola * Copy () override
Public Member Functions inherited from GCS::Hyperbola
Hyperbola ()
~Hyperbola () override
double getRadMaj (const DeriVector2 &center, const DeriVector2 &f1, double b, double db, double &ret_dRadMaj) const override
double getRadMaj (double *derivparam, double &ret_dRadMaj) const override
double getRadMaj () const override
DeriVector2 CalculateNormal (const Point &p, const double *derivparam=nullptr) const override
DeriVector2 Value (double u, double du, const double *derivparam=nullptr) const override
Value: returns point (vector) given the value of parameter.
Public Member Functions inherited from GCS::MajorRadiusConic
~MajorRadiusConic () override
Public Member Functions inherited from GCS::Curve
virtual ~Curve ()
virtual DeriVector2 CalculateNormal (const double *param, const double *derivparam=nullptr) const
Public Attributes
double * startAngle
double * endAngle
Point start
Point end
Public Attributes inherited from GCS::Hyperbola
Point center
Point focus1
double * radmin
Detailed Description
Definition at line 366 of file Geo.h.
Constructor & Destructor Documentation
ArcOfHyperbola()
GCS::ArcOfHyperbola::ArcOfHyperbola () inline
Definition at line 369 of file Geo.h.
Referenced by Copy().
~ArcOfHyperbola()
GCS::ArcOfHyperbola::~ArcOfHyperbola () inline override
Definition at line 375 of file Geo.h.
Member Function Documentation
Copy()
ArcOfHyperbola * GCS::ArcOfHyperbola::Copy () override virtual
Reimplemented from GCS::Hyperbola.
Definition at line 601 of file Geo.cpp.
References ArcOfHyperbola().
PushOwnParams()
int GCS::ArcOfHyperbola::PushOwnParams (VEC_pD & pvec) override virtual
Reimplemented from GCS::Hyperbola.
Definition at line 567 of file Geo.cpp.
References end, endAngle, GCS::Hyperbola::PushOwnParams(), start, startAngle, GCS::Point::x, and GCS::Point::y.
ReconstructOnNewPvec()
void GCS::ArcOfHyperbola::ReconstructOnNewPvec (VEC_pD & pvec, int & cnt) override virtual
Reimplemented from GCS::Hyperbola.
Definition at line 585 of file Geo.cpp.
References end, endAngle, GCS::Hyperbola::ReconstructOnNewPvec(), start, startAngle, GCS::Point::x, and GCS::Point::y.
Member Data Documentation
end
Point GCS::ArcOfHyperbola::end
Definition at line 381 of file Geo.h.
Referenced by PushOwnParams(), and ReconstructOnNewPvec().
endAngle
double* GCS::ArcOfHyperbola::endAngle
Definition at line 379 of file Geo.h.
Referenced by PushOwnParams(), and ReconstructOnNewPvec().
start
Point GCS::ArcOfHyperbola::start
Definition at line 380 of file Geo.h.
Referenced by PushOwnParams(), and ReconstructOnNewPvec().
startAngle
double* GCS::ArcOfHyperbola::startAngle
Definition at line 378 of file Geo.h.
Referenced by PushOwnParams(), and ReconstructOnNewPvec().
The documentation for this class was generated from the following files:
Geo.h
Geo.cpp