FreeCAD: Gui::WidgetFactoryInst Class Reference
Gui::WidgetFactoryInst Class Reference
#include <WidgetFactory.h>
Public Member Functions
QWidget * createWidget (const char *sName, QWidget *parent=nullptr) const
Gui::Dialog::PreferencePage * createPreferencePage (const char *sName, QWidget *parent=nullptr) const
QWidget * createPrefWidget (const char *sName, QWidget *parent, const char *sPref)
Public Member Functions inherited from Base::Factory
void AddProducer (const char *sClassName, AbstractProducer *pcProducer)
Adds a new prducer instance.
bool CanProduce (const char *sClassName) const
returns true if there is a producer for this class registered
std::list< std::string > CanProduce () const
returns a list of all registered producer
virtual ~Factory ()
destruction
Static Public Member Functions
static WidgetFactoryInst & instance ()
static void destruct ()
Additional Inherited Members
Protected Member Functions inherited from Base::Factory
void * Produce (const char *sClassName) const
produce a class with the given name
Factory ()=default
construction
Protected Attributes inherited from Base::Factory
std::map< const std::string, AbstractProducer * > _mpcProducers
Detailed Description
The widget factory provides methods for the dynamic creation of widgets. To create these widgets once they must be registered to the factory. To register them use WidgetProducer or any subclasses; to register a preference page use PrefPageProducer instead.
Author
Werner Mayer
Definition at line 51 of file WidgetFactory.h.
Member Function Documentation
createPreferencePage()
Gui::Dialog::PreferencePage * WidgetFactoryInst::createPreferencePage (const char * sName, QWidget * parent = nullptr) const
Creates a widget with the name sName which is a child of parent. To create an instance of this widget once it must has been registered. If there is no appropriate widget registered nullptr is returned.
Definition at line 115 of file WidgetFactory.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), Base::ConsoleSingleton::Log(), Init::parent, Base::Factory::Produce(), src.Mod.PartDesign.fcgear.svggear::w, and Base::ConsoleSingleton::Warning().
Referenced by Gui::Dialog::DlgPreferencesImp::createPreferencePage().
createPrefWidget()
QWidget * WidgetFactoryInst::createPrefWidget (const char * sName, QWidget * parent, const char * sPref)
Creates a preference widget with the name sName and the preference name sPref which is a child of parent. To create an instance of this widget once it must has been registered. If there is no appropriate widget registered nullptr is returned. After creation of this widget its recent preferences are restored automatically.
Definition at line 156 of file WidgetFactory.cpp.
References Base::Console(), createWidget(), Base::ConsoleSingleton::Error(), Init::parent, Gui::PrefWidget::setEntryName(), and src.Mod.PartDesign.fcgear.svggear::w.
createWidget()
QWidget * WidgetFactoryInst::createWidget (const char * sName, QWidget * parent = nullptr) const
Creates a widget with the name sName which is a child of parent. To create an instance of this widget once it must has been registered. If there is no appropriate widget registered nullptr is returned.
Definition at line 73 of file WidgetFactory.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), Base::ConsoleSingleton::Log(), Init::parent, Base::Factory::Produce(), src.Mod.PartDesign.fcgear.svggear::w, and Base::ConsoleSingleton::Warning().
Referenced by createPrefWidget().
destruct()
void WidgetFactoryInst::destruct () static
Definition at line 61 of file WidgetFactory.cpp.
Referenced by Gui::WidgetFactorySupplier::destruct().
instance()
WidgetFactoryInst & WidgetFactoryInst::instance () static
Definition at line 54 of file WidgetFactory.cpp.
Referenced by Gui::CustomPageProducer< CLASS >::CustomPageProducer(), Gui::PrefPageProducer< CLASS >::PrefPageProducer(), Gui::PrefPagePyProducer::PrefPagePyProducer(), Gui::PrefPageUiProducer::PrefPageUiProducer(), Gui::WidgetFactory(), and Gui::WidgetProducer< CLASS >::WidgetProducer().
The documentation for this class was generated from the following files:
WidgetFactory.h
WidgetFactory.cpp