FreeCAD: TechDraw::GeometryUtils Class Reference
TechDraw::GeometryUtils Class Reference
Encapsulates some useful static methods.
#include <Geometry.h>
Classes
struct ReturnType
Used by nextGeom()
Static Public Member Functions
static ReturnType nextGeom (Base::Vector3d atPoint, std::vector< TechDraw::BaseGeomPtr > geoms, std::vector< bool > used, double tolerance)
Find an unused geom starts or ends at atPoint.
static BaseGeomPtrVector chainGeoms (BaseGeomPtrVector geoms)
return a vector of BaseGeomPtr's in tail to nose order
static TopoDS_Edge edgeFromGeneric (TechDraw::GenericPtr g)
static TopoDS_Edge edgeFromCircle (TechDraw::CirclePtr c)
static TopoDS_Edge edgeFromCircleArc (TechDraw::AOCPtr c)
static bool isCircle (TopoDS_Edge occEdge)
static bool getCircleParms (TopoDS_Edge occEdge, double &radius, Base::Vector3d &center, bool &isArc)
static TopoDS_Edge asCircle (TopoDS_Edge splineEdge, bool &arc)
make a circle or arc of circle Edge from BSpline Edge
static bool isLine (TopoDS_Edge occEdge)
static TopoDS_Edge asLine (TopoDS_Edge occEdge)
make a line Edge from B-spline Edge
static double edgeLength (TopoDS_Edge occEdge)
static TopoDS_Face makePerforatedFace (FacePtr bigCheese, const std::vector< FacePtr > &holesAll)
return a perforated shape/face (using Part::FaceMakerCheese) formed by creating holes in the input face.
static std::vector< FacePtr > findHolesInFace (const DrawViewPart *dvp, const std::string &bigCheeseSubRef)
find faces within the bounds of the input face
Detailed Description
Encapsulates some useful static methods.
Definition at line 423 of file TechDraw/App/Geometry.h.
Member Function Documentation
asCircle()
TopoDS_Edge GeometryUtils::asCircle (TopoDS_Edge splineEdge, bool & arc) static
make a circle or arc of circle Edge from BSpline Edge
Definition at line 1636 of file TechDraw/App/Geometry.cpp.
References exportCSG::center(), EWTOLERANCE, getCircleParms(), Handle(), and TechDraw::DrawUtil::togp_Pnt().
Referenced by TechDraw::DrawViewDimension::arcPointsFromEdge(), and TechDraw::BSpline::asCircle().
asLine()
TopoDS_Edge GeometryUtils::asLine (TopoDS_Edge occEdge) static
make a line Edge from B-spline Edge
Definition at line 1712 of file TechDraw/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, Handle(), and result.
chainGeoms()
BaseGeomPtrVector GeometryUtils::chainGeoms (BaseGeomPtrVector geoms) static
return a vector of BaseGeomPtr's in tail to nose order
Definition at line 1451 of file TechDraw/App/Geometry.cpp.
References SplineSurface::i, nextGeom(), and result.
edgeFromCircle()
TopoDS_Edge GeometryUtils::edgeFromCircle (TechDraw::CirclePtr c) static
Definition at line 1527 of file TechDraw/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, Handle(), and M_PI.
Referenced by TechDraw::CosmeticEdge::Restore(), and TechDraw::CenterLine::Restore().
edgeFromCircleArc()
TopoDS_Edge GeometryUtils::edgeFromCircleArc (TechDraw::AOCPtr c) static
Definition at line 1540 of file TechDraw/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, and Handle().
Referenced by TechDraw::CosmeticEdge::Restore(), and TechDraw::CenterLine::Restore().
edgeFromGeneric()
TopoDS_Edge GeometryUtils::edgeFromGeneric (TechDraw::GenericPtr g) static
Definition at line 1514 of file TechDraw/App/Geometry.cpp.
References toolbit-attributes::g, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by TechDraw::CosmeticEdge::Restore(), and TechDraw::CenterLine::Restore().
edgeLength()
double GeometryUtils::edgeLength (TopoDS_Edge occEdge) static
Definition at line 1728 of file TechDraw/App/Geometry.cpp.
References Handle(), FreeCADInit::Length, and THROWM.
Referenced by getCircleParms().
findHolesInFace()
std::vector< FacePtr > GeometryUtils::findHolesInFace (const DrawViewPart * dvp, const std::string & bigCheeseSubRef) static
find faces within the bounds of the input face
Definition at line 1798 of file TechDraw/App/Geometry.cpp.
References EWTOLERANCE, TechDraw::DrawViewPart::getFaceGeometry(), TechDraw::DrawUtil::getIndexFromName(), TechDraw::DrawUtil::simpleMinDist(), and TechDraw::DrawUtil::togp_Pnt().
Referenced by TechDraw::DrawViewDimension::getAreaParameters().
getCircleParms()
bool GeometryUtils::getCircleParms (TopoDS_Edge occEdge, double & radius, Base::Vector3d & center, bool & isArc) static
tries to interpret a B-spline edge as a circle. Used by DVDim for approximate dimensions. calculates the curvature of the spline at a number of places and measures the deviation from the average a true circle has constant curvature and would have no deviation from the average.
Definition at line 1567 of file TechDraw/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, exportCSG::center(), edgeLength(), Path.Log::error(), EWTOLERANCE, SCL.SimpleDataTypes::f, Handle(), SplineSurface::i, isCircle(), RobotExample::l, FreeCADInit::Length, and TechDraw::DrawUtil::toVector3d().
Referenced by TechDraw::DrawViewDimension::arcPointsFromBaseGeom(), asCircle(), and isCircle().
isCircle()
bool GeometryUtils::isCircle (TopoDS_Edge occEdge) static
Definition at line 1556 of file TechDraw/App/Geometry.cpp.
References exportCSG::center(), and getCircleParms().
Referenced by TechDraw::DrawViewDimension::arcPointsFromEdge(), getCircleParms(), TechDraw::BSpline::isCircle(), and TechDraw::isValidSingleEdge3d().
isLine()
bool GeometryUtils::isLine (TopoDS_Edge occEdge) static
Definition at line 1673 of file TechDraw/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, SCL.SimpleDataTypes::e, SCL.SimpleDataTypes::f, TechDraw::DrawUtil::fpCompare(), Handle(), SplineSurface::i, RobotExample::l, FreeCADInit::Length, toolbit-attributes::s, TechDraw::DrawUtil::toVector3d(), and draftgeoutils.general::v1().
Referenced by TechDraw::BSpline::isLine().
makePerforatedFace()
TopoDS_Face GeometryUtils::makePerforatedFace (FacePtr bigCheese, const std::vector< FacePtr > & holesAll) static
return a perforated shape/face (using Part::FaceMakerCheese) formed by creating holes in the input face.
Definition at line 1744 of file TechDraw/App/Geometry.cpp.
References Base::Console(), SCL.SimpleDataTypes::e, TechDraw::ShapeUtils::fromQtAsFace(), TechDraw::ShapeUtils::fromQtAsWire(), Part::FaceMakerCheese::makeFace(), and Base::ConsoleSingleton::Warning().
Referenced by TechDraw::DrawViewDimension::getAreaParameters().
nextGeom()
GeometryUtils::ReturnType GeometryUtils::nextGeom (Base::Vector3d atPoint, std::vector< TechDraw::BaseGeomPtr > geoms, std::vector< bool > used, double tolerance) static
Find an unused geom starts or ends at atPoint.
returns index[1:geoms.size()), reversed [true, false]
Definition at line 1487 of file TechDraw/App/Geometry.cpp.
References result, and draftutils.utils::tolerance().
Referenced by chainGeoms().
The documentation for this class was generated from the following files:
TechDraw/App/Geometry.h
TechDraw/App/Geometry.cpp