FreeCAD: Base::ofstream Class Reference
Base::ofstream Class Reference
#include <Stream.h>
Public Member Functions
ofstream ()=default
ofstream (const ofstream &)=delete
ofstream (ofstream &&)=delete
ofstream (const FileInfo &fi, ios_base::openmode mode=std::ios::out|std::ios::trunc)
~ofstream () override=default
void open (const FileInfo &fi, ios_base::openmode mode=std::ios::out|std::ios::trunc)
ofstream & operator= (const ofstream &)=delete
ofstream & operator= (ofstream &&)=delete
Detailed Description
The ofstream class is provided for convenience. On Windows platforms it opens a stream with UCS-2 encoded file name while on Linux platforms the file name is UTF-8 encoded.
Author
Werner Mayer
Definition at line 572 of file Stream.h.
Constructor & Destructor Documentation
ofstream() [1/4]
Base::ofstream::ofstream () default
ofstream() [2/4]
Base::ofstream::ofstream (const ofstream &) delete
ofstream() [3/4]
Base::ofstream::ofstream (ofstream &&) delete
ofstream() [4/4]
Base::ofstream::ofstream (const FileInfo & fi, ios_base::openmode mode = std::ios::out | std::ios::trunc) inline explicit
Definition at line 578 of file Stream.h.
~ofstream()
Base::ofstream::~ofstream () override default
Member Function Documentation
open()
void Base::ofstream::open (const FileInfo & fi, ios_base::openmode mode = std::ios::out | std::ios::trunc) inline
Definition at line 586 of file Stream.h.
References Base::FileInfo::filePath(), AssemblyImport::open(), and Base::FileInfo::toStdWString().
operator=() [1/2]
ofstream& Base::ofstream::operator= (const ofstream &) delete
operator=() [2/2]
ofstream& Base::ofstream::operator= (ofstream &&) delete
The documentation for this class was generated from the following file:
Stream.h