FreeCAD: App::ObjectIdentifier Class Reference
App::ObjectIdentifier Class Reference
#include <ObjectIdentifier.h>
Classes
class Component
A component is a part of a Path object, and is used to either name a property or a field within a property. A component can be either a single entry, and array, or a map to other sub-fields.
class DocumentMapper
struct ResolveResults
class String
Public Types
using SubNameMap = std::map< std::pair< App::DocumentObject *, std::string >, std::string >
using Dependencies = std::map< App::DocumentObject *, std::set< std::string > >
Public Member Functions
ObjectIdentifier (const App::PropertyContainer *_owner=nullptr, const std::string &property=std::string(), int index=INT_MAX)
Construct an ObjectIdentifier object, given an owner and a single-value property.
ObjectIdentifier (const App::PropertyContainer *_owner, bool localProperty)
ObjectIdentifier (const App::Property &prop, int index=INT_MAX)
Construct an ObjectIdentifier object given a property. The property is assumed to be single-valued.
ObjectIdentifier (const ObjectIdentifier &)=default
ObjectIdentifier & operator= (const ObjectIdentifier &)=default
ObjectIdentifier (ObjectIdentifier &&other)
ObjectIdentifier & operator= (ObjectIdentifier &&other)
virtual ~ObjectIdentifier ()=default
App::DocumentObject * getOwner () const
void addComponent (const Component &c)
void addComponent (Component &&c)
std::string getPropertyName () const
Get the name of the property.
template<typename C >
void addComponents (const C &cs)
const Component & getPropertyComponent (int i, int *idx=nullptr) const
Get Component at given index i.
void setComponent (int idx, Component &&comp)
void setComponent (int idx, const Component &comp)
std::vector< Component > getPropertyComponents () const
const std::vector< Component > & getComponents () const
std::string getSubPathStr (bool toPython=false) const
int numComponents () const
Return number of components.
int numSubComponents () const
Compute number of sub components, i.e excluding the property.
const std::string & toString () const
Create a string representation of this object identifier.
std::string toPersistentString () const
std::string toEscapedString () const
Escape toString representation so it is suitable for being embedded in a python command.
bool isTouched () const
App::Property * getProperty (int *ptype=nullptr) const
Get pointer to property pointed to by this object identifier.
App::ObjectIdentifier canonicalPath () const
Create a canonical representation of an object identifier.
void setDocumentName (String &&name, bool force=false)
Set the document name for this object identifier.
String getDocumentName () const
Get the document name from this object identifier.
void setDocumentObjectName (String &&name, bool force=false, String &&subname=String(), bool checkImport=false)
Set the document object name of this object identifier.
void setDocumentObjectName (const App::DocumentObject *obj, bool force=false, String &&subname=String(), bool checkImport=false)
bool hasDocumentObjectName (bool forced=false) const
bool isLocalProperty () const
String getDocumentObjectName () const
Get the document object name.
const std::string & getSubObjectName (bool newStyle) const
const std::string & getSubObjectName () const
void importSubNames (const SubNameMap &subNameMap)
bool updateLabelReference (App::DocumentObject *, const std::string &, const char *)
bool relabeledDocument (ExpressionVisitor &v, const std::string &oldLabel, const std::string &newLabel)
Dependencies getDep (bool needProps, std::vector< std::string > *labels=nullptr) const
void getDep (Dependencies &deps, bool needProps, std::vector< std::string > *labels=nullptr) const
void getDepLabels (std::vector< std::string > &labels) const
Returns all label references.
App::Document * getDocument (String name=String(), bool *ambiguous=nullptr) const
Find a document with the given name.
App::DocumentObject * getDocumentObject () const
Get the document object for the object identifier.
std::vector< std::string > getStringList () const
Get components as a string list.
App::ObjectIdentifier relativeTo (const App::ObjectIdentifier &other) const
Construct the simplest possible object identifier relative to another.
bool replaceObject (ObjectIdentifier &res, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const
App::ObjectIdentifier & operator<< (const Component &value)
<< operator, used to add a component to the object identifier.
App::ObjectIdentifier & operator<< (Component &&value)
bool operator== (const ObjectIdentifier &other) const
Compare object identifier with other.
bool operator!= (const ObjectIdentifier &other) const
Compare object identifier with other.
bool operator< (const ObjectIdentifier &other) const
Compare object identifier with other.
App::any getValue (bool pathValue=false, bool *isPseudoProperty=nullptr) const
Get the value of the property or field pointed to by this object identifier.
Py::Object getPyValue (bool pathValue=false, bool *isPseudoProperty=nullptr) const
void setValue (const App::any &value) const
Set value of a property or field pointed to by this object identifier.
std::string resolveErrorString () const
bool adjustLinks (ExpressionVisitor &v, const std::set< App::DocumentObject * > &inList)
bool updateElementReference (ExpressionVisitor &v, App::DocumentObject *feature=nullptr, bool reverse=false)
void resolveAmbiguity ()
bool verify (const App::Property &prop, bool silent=false) const
std::size_t hash () const
Static Public Member Functions
static Component SimpleComponent (const char *_component)
static Component SimpleComponent (const String &_component)
static Component SimpleComponent (String &&_component)
static Component SimpleComponent (const std::string _component)
static Component ArrayComponent (int _index)
static Component RangeComponent (int _begin, int _end=INT_MAX, int _step=1)
static Component MapComponent (const String &_key)
static Component MapComponent (String &&_key)
static ObjectIdentifier parse (const App::DocumentObject *docObj, const std::string &str)
Parse a string to create an object identifier.
Protected Member Functions
App::Property * resolveProperty (const App::DocumentObject *obj, const char *propertyName, App::DocumentObject *&sobj, int &ptype) const
void getSubPathStr (std::ostream &ss, const ResolveResults &result, bool toPython=false) const
Get sub field part of a property as a string.
Py::Object access (const ResolveResults &rs, Py::Object *value=nullptr, Dependencies *deps=nullptr) const
void resolve (ResolveResults &results) const
Resolve the object identifier to a concrete document, documentobject, and property.
void resolveAmbiguity (ResolveResults &results)
void getDepLabels (const ResolveResults &result, std::vector< std::string > &labels) const
Static Protected Member Functions
static App::DocumentObject * getDocumentObject (const App::Document *doc, const String &name, std::bitset< 32 > &flags)
Search for the document object given by name in doc.
Protected Attributes
App::DocumentObject * owner
String documentName
String documentObjectName
String subObjectName
ElementNamePair shadowSub
std::vector< Component > components
bool documentNameSet
bool documentObjectNameSet
bool localProperty
Friends
struct ResolveResults
Detailed Description
Definition at line 77 of file ObjectIdentifier.h.
Member Typedef Documentation
Dependencies
using App::ObjectIdentifier::Dependencies = std::map<App::DocumentObject*, std::set<std::string> >
Type for storing dependency of an ObjectIdentifier
The dependency is a map from document object to a set of property names. An object identifier may references multiple objects using syntax like 'Part.Group[0].Width'.
Also, we use set of string instead of set of Property pointer, because the property may not exist at the time this ObjectIdentifier is constructed.
Definition at line 472 of file ObjectIdentifier.h.
SubNameMap
using App::ObjectIdentifier::SubNameMap = std::map<std::pair<App::DocumentObject*, std::string>, std::string>
Definition at line 453 of file ObjectIdentifier.h.
Constructor & Destructor Documentation
ObjectIdentifier() [1/5]
ObjectIdentifier::ObjectIdentifier (const App::PropertyContainer * _owner = nullptr, const std::string & property = std::string(), int index = INT_MAX) explicit
Construct an ObjectIdentifier object, given an owner and a single-value property.
Parameters
_owner Owner of property.
property Name of property.
Definition at line 111 of file ObjectIdentifier.cpp.
References addComponent(), ArrayComponent(), FC_THROWM, owner, setDocumentObjectName(), and SimpleComponent().
ObjectIdentifier() [2/5]
ObjectIdentifier::ObjectIdentifier (const App::PropertyContainer * _owner, bool localProperty)
Definition at line 139 of file ObjectIdentifier.cpp.
References FC_THROWM, and owner.
ObjectIdentifier() [3/5]
ObjectIdentifier::ObjectIdentifier (const App::Property & prop, int index = INT_MAX)
Construct an ObjectIdentifier object given a property. The property is assumed to be single-valued.
Parameters
prop Property to construct object identifier for.
Definition at line 161 of file ObjectIdentifier.cpp.
References addComponent(), ArrayComponent(), FC_THROWM, App::Property::getContainer(), App::Property::getName(), App::Property::hasName(), owner, setDocumentObjectName(), SimpleComponent(), and src.Mod.Test.testmakeWireString::String.
ObjectIdentifier() [4/5]
App::ObjectIdentifier::ObjectIdentifier (const ObjectIdentifier &) default
ObjectIdentifier() [5/5]
App::ObjectIdentifier::ObjectIdentifier (ObjectIdentifier && other) inline
Definition at line 351 of file ObjectIdentifier.h.
~ObjectIdentifier()
virtual App::ObjectIdentifier::~ObjectIdentifier () virtual default
Member Function Documentation
access()
Py::Object ObjectIdentifier::access (const ResolveResults & rs, Py::Object * value = nullptr, Dependencies * deps = nullptr) const protected
Definition at line 1694 of file ObjectIdentifier.cpp.
References components, src.Mod.AddonManager.NetworkManager::count, Path.Base.SetupSheet::dict, create_qrc::ext, FC_THROWM, FC_WARN, src.Mod.AddonManager.addonmanager_freecad_interface::FreeCAD, src.Mod.AddonManager.addonmanager_freecad_interface::FreeCADGui, GET_MODULE, Base::Persistence::getClassTypeId(), App::ExtensionContainer::getPropertyByName(), App::ObjectIdentifier::String::getString(), Path.Op.PocketShape::math, PseudoApp, PseudoBuiltins, PseudoCadquery, PseudoCollections, PseudoGui, PseudoLinkMatrix, PseudoLinkPlacement, PseudoMath, PseudoMatrix, PseudoNone, PseudoPart, PseudoPlacement, PseudoRegex, PseudoSelf, PseudoShape, result, src.Mod.Test.testmakeWireString::String, subObjectName, and toString().
Referenced by getDep(), getPyValue(), getValue(), and setValue().
addComponent() [1/2]
void App::ObjectIdentifier::addComponent (Component && c) inline
Definition at line 382 of file ObjectIdentifier.h.
References SCL.SimpleDataTypes::c, and Path.Post.scripts.opensbp_post::move().
addComponent() [2/2]
void App::ObjectIdentifier::addComponent (const Component & c) inline
Definition at line 375 of file ObjectIdentifier.h.
References SCL.SimpleDataTypes::c.
Referenced by ObjectIdentifier().
addComponents()
template<typename C > void App::ObjectIdentifier::addComponents (const C & cs) inline
Definition at line 391 of file ObjectIdentifier.h.
adjustLinks()
bool ObjectIdentifier::adjustLinks (ExpressionVisitor & v, const std::set< App::DocumentObject * > & inList)
Definition at line 2098 of file ObjectIdentifier.cpp.
References App::PropertyLinkSub::adjustLink(), documentObjectName, App::DocumentObject::getNameInDocument(), App::PropertyLinkSub::getSubValues(), App::PropertyLinkSub::getValue(), result, App::PropertyLinkSub::setValue(), src.Mod.Test.testmakeWireString::String, subObjectName, and TestSpreadsheet::v.
Referenced by App::VariableExpression::_adjustLinks().
ArrayComponent()
static Component App::ObjectIdentifier::ArrayComponent (int _index) inline static
Definition at line 323 of file ObjectIdentifier.h.
Referenced by App::VariableExpression::addComponent(), and ObjectIdentifier().
canonicalPath()
ObjectIdentifier ObjectIdentifier::canonicalPath () const
Create a canonical representation of an object identifier.
The main work is actually done by the property's virtual canonicalPath(...) method, which is invoked by this call.
Returns
A new object identifier.
Definition at line 1470 of file ObjectIdentifier.cpp.
References owner, PseudoNone, resolveAmbiguity(), and result.
Referenced by App::VariableExpression::_collectReplacement(), and App::VariableExpression::_renameObjectIdentifier().
getComponents()
const std::vector<Component>& App::ObjectIdentifier::getComponents () const inline
Definition at line 402 of file ObjectIdentifier.h.
getDep() [1/2]
ObjectIdentifier::Dependencies ObjectIdentifier::getDep (bool needProps, std::vector< std::string > * labels = nullptr) const
Get dependencies of this object identifier
Parameters
needProps whether need property dependencies.
labels optional return of any label references.
In case of multi-object references, like 'Part.Group[0].Width', if no property dependency is required, then this function will only return the first referred object dependency. Or else, all object and property dependencies will be returned.
Definition at line 1245 of file ObjectIdentifier.cpp.
References App::ExpressionParser::labels.
Referenced by App::Expression::getDepObjects(), App::Expression::getDeps(), and App::PropertyExpressionEngine::hasSetValue().
getDep() [2/2]
void ObjectIdentifier::getDep (Dependencies & deps, bool needProps, std::vector< std::string > * labels = nullptr) const
Get dependencies of this object identifier
Parameters
deps returns the dependencies.
needProps whether need property dependencies.
labels optional return of any label references.
In case of multi-object references, like 'Part.Group[0].Width', if no property dependency is required, then this function will only return the first referred object dependency. Or else, all object and property dependencies will be returned.
Definition at line 1253 of file ObjectIdentifier.cpp.
References access(), SCL.SimpleDataTypes::e, getDepLabels(), App::ExpressionParser::labels, and result.
getDepLabels() [1/2]
void ObjectIdentifier::getDepLabels (const ResolveResults & result, std::vector< std::string > & labels) const protected
Definition at line 1229 of file ObjectIdentifier.cpp.
References components, documentObjectName, App::PropertyLinkBase::getLabelReferences(), App::ObjectIdentifier::String::getString(), App::ObjectIdentifier::String::isRealString(), App::ExpressionParser::labels, result, and subObjectName.
getDepLabels() [2/2]
void ObjectIdentifier::getDepLabels (std::vector< std::string > & labels) const
Returns all label references.
Definition at line 1224 of file ObjectIdentifier.cpp.
References App::ExpressionParser::labels, and ResolveResults.
Referenced by getDep().
getDocument()
Document * ObjectIdentifier::getDocument (String name = String(), bool * ambiguous = nullptr) const
Find a document with the given name.
Parameters
name Name of document
Returns
Pointer to document, or 0 if it is not found or not uniquely defined by name.
Definition at line 1133 of file ObjectIdentifier.cpp.
References toolbit-attributes::doc, App::GetApplication(), App::Application::getDocument(), getDocumentName(), App::Application::getDocuments(), App::ObjectIdentifier::String::getString(), App::ObjectIdentifier::String::isForceIdentifier(), App::ObjectIdentifier::String::isRealString(), and App::ObjectIdentifier::String::toString().
Referenced by getDocumentObject(), and resolve().
getDocumentName()
ObjectIdentifier::String ObjectIdentifier::getDocumentName () const
Get the document name from this object identifier.
Returns
Document name as a String object.
Definition at line 1538 of file ObjectIdentifier.cpp.
References result.
Referenced by getDocument().
getDocumentObject() [1/2]
DocumentObject * ObjectIdentifier::getDocumentObject () const
Get the document object for the object identifier.
Returns
Pointer to document object, or 0 if not found or uniquely defined.
Definition at line 1190 of file ObjectIdentifier.cpp.
References toolbit-attributes::doc, getDocument(), and result.
Referenced by Gui::InputField::bind(), App::ObjectIdentifier::String::checkImport(), SpreadsheetGui::DlgBindSheet::DlgBindSheet(), Gui::Dialog::DlgExpressionInput::DlgExpressionInput(), resolve(), and App::PropertyExpressionEngine::validateExpression().
getDocumentObject() [2/2]
App::DocumentObject * ObjectIdentifier::getDocumentObject (const App::Document * doc, const String & name, std::bitset< 32 > & flags) static protected
Search for the document object given by name in doc.
Name might be the internal name or a label. In any case, it must uniquely define the document object.
Parameters
doc Document to search
name Name to search for.
Returns
Pointer to document object if a unique pointer is found, 0 otherwise.
Definition at line 935 of file ObjectIdentifier.cpp.
References toolbit-attributes::doc, FC_WARN, App::ObjectIdentifier::String::isForceIdentifier(), App::ObjectIdentifier::String::isRealString(), ResolveAmbiguous, ResolveByIdentifier, and ResolveByLabel.
getDocumentObjectName()
ObjectIdentifier::String ObjectIdentifier::getDocumentObjectName () const
Get the document object name.
Returns
String with name of document object as resolved by object identifier.
Definition at line 1623 of file ObjectIdentifier.cpp.
References result.
Referenced by App::VariableExpression::_renameObjectIdentifier(), and Sketcher::SketchObject::carbonCopy().
getOwner()
App::DocumentObject* App::ObjectIdentifier::getOwner () const inline
Definition at line 369 of file ObjectIdentifier.h.
Referenced by relativeTo().
getProperty()
Property * ObjectIdentifier::getProperty (int * ptype = nullptr) const
Get pointer to property pointed to by this object identifier.
Returns
Point to property if it is uniquely defined, or 0 otherwise.
Definition at line 1406 of file ObjectIdentifier.cpp.
References result.
Referenced by Gui::ExpressionBinding::bind(), and App::VariableExpression::getProperty().
getPropertyComponent()
const App::ObjectIdentifier::Component & App::ObjectIdentifier::getPropertyComponent (int i, int * idx = nullptr) const
Get Component at given index i.
Parameters
i Index to get
idx optional return of adjusted component index
Returns
A component.
Definition at line 209 of file ObjectIdentifier.cpp.
References FC_THROWM, SplineSurface::i, and result.
Referenced by App::VariableExpression::_moveCells(), and App::VariableExpression::_offsetCells().
getPropertyComponents()
std::vector< ObjectIdentifier::Component > ObjectIdentifier::getPropertyComponents () const
Definition at line 240 of file ObjectIdentifier.cpp.
References components, documentObjectName, App::ObjectIdentifier::String::getString(), and result.
getPropertyName()
std::string App::ObjectIdentifier::getPropertyName () const
Get the name of the property.
Returns
Name
Definition at line 192 of file ObjectIdentifier.cpp.
References result.
getPyValue()
Py::Object ObjectIdentifier::getPyValue (bool pathValue = false, bool * isPseudoProperty = nullptr) const
Definition at line 1963 of file ObjectIdentifier.cpp.
References access(), components, App::ExtensionContainer::getPropertyByName(), App::Property::getPyPathValue(), isLocalProperty(), owner, App::ObjectIdentifier::ResolveResults::propertyIndex, App::ObjectIdentifier::ResolveResults::propertyType, PseudoNone, PseudoSelf, App::ObjectIdentifier::ResolveResults::resolvedProperty, and Base::PyException::ThrowException().
Referenced by App::VariableExpression::_getPyValue().
getStringList()
std::vector< std::string > ObjectIdentifier::getStringList () const
Get components as a string list.
Returns
List of strings.
Definition at line 1294 of file ObjectIdentifier.cpp.
References components, documentName, documentNameSet, documentObjectName, documentObjectNameSet, App::ObjectIdentifier::String::getString(), SplineSurface::i, RobotExample::l, owner, result, subObjectName, and App::ObjectIdentifier::String::toString().
getSubObjectName() [1/2]
const std::string & ObjectIdentifier::getSubObjectName () const
Definition at line 2031 of file ObjectIdentifier.cpp.
References App::ObjectIdentifier::String::getString(), and subObjectName.
getSubObjectName() [2/2]
const std::string & ObjectIdentifier::getSubObjectName (bool newStyle) const
Definition at line 2020 of file ObjectIdentifier.cpp.
References App::ObjectIdentifier::String::getString(), App::ElementNamePair::newName, App::ElementNamePair::oldName, shadowSub, and subObjectName.
Referenced by App::VariableExpression::_renameObjectIdentifier().
getSubPathStr() [1/2]
std::string ObjectIdentifier::getSubPathStr (bool toPython = false) const
Definition at line 627 of file ObjectIdentifier.cpp.
References ResolveResults.
Referenced by toPersistentString(), and toString().
getSubPathStr() [2/2]
void ObjectIdentifier::getSubPathStr (std::ostream & s, const ResolveResults & result, bool toPython = false) const protected
Get sub field part of a property as a string.
Returns
String representation of path.
Definition at line 613 of file ObjectIdentifier.cpp.
References components, SplineSurface::i, result, and toolbit-attributes::s.
getValue()
App::any ObjectIdentifier::getValue (bool pathValue = false, bool * isPseudoProperty = nullptr) const
Get the value of the property or field pointed to by this object identifier.
All type of objects are supported. Some types are casted to FC native type, including: Int, Float, String, Unicode String, and Quantities. Others are just kept as Python object wrapped by App::any.
Parameters
pathValue if true, calls the property's getPathValue(), which is necessary for Qunatities to work.
Returns
The value of the property or field.
Definition at line 1936 of file ObjectIdentifier.cpp.
References access(), components, App::Property::getPathValue(), App::ExtensionContainer::getPropertyByName(), isLocalProperty(), owner, App::ObjectIdentifier::ResolveResults::propertyIndex, App::ObjectIdentifier::ResolveResults::propertyType, PseudoNone, PseudoSelf, App::pyObjectToAny(), App::ObjectIdentifier::ResolveResults::resolvedProperty, and Base::PyException::ThrowException().
hasDocumentObjectName()
bool ObjectIdentifier::hasDocumentObjectName (bool forced = false) const
Definition at line 1630 of file ObjectIdentifier.cpp.
References documentObjectName, documentObjectNameSet, and App::ObjectIdentifier::String::getString().
Referenced by App::VariableExpression::_moveCells(), App::VariableExpression::_offsetCells(), and App::VariableExpression::_renameObjectIdentifier().
hash()
std::size_t ObjectIdentifier::hash () const
Definition at line 459 of file ObjectIdentifier.cpp.
References App::hash_value(), and toString().
importSubNames()
void ObjectIdentifier::importSubNames (const SubNameMap & subNameMap)
Definition at line 2036 of file ObjectIdentifier.cpp.
References documentName, documentNameSet, documentObjectName, FC_ERR, App::DocumentObject::getDocument(), App::Document::getObject(), App::ObjectIdentifier::String::getString(), App::ObjectIdentifier::String::isRealString(), App::ElementNamePair::newName, App::ElementNamePair::oldName, owner, result, shadowSub, src.Mod.Test.testmakeWireString::String, and subObjectName.
Referenced by App::VariableExpression::_importSubNames().
isLocalProperty()
bool App::ObjectIdentifier::isLocalProperty () const inline
Definition at line 443 of file ObjectIdentifier.h.
Referenced by getPyValue(), getValue(), and resolveAmbiguity().
isTouched()
bool ObjectIdentifier::isTouched () const
Definition at line 2119 of file ObjectIdentifier.cpp.
References PseudoNone, and result.
Referenced by App::VariableExpression::isTouched().
MapComponent() [1/2]
static Component App::ObjectIdentifier::MapComponent (const String & _key) inline static
Definition at line 333 of file ObjectIdentifier.h.
Referenced by App::VariableExpression::addComponent().
MapComponent() [2/2]
static Component App::ObjectIdentifier::MapComponent (String && _key) inline static
Definition at line 338 of file ObjectIdentifier.h.
numComponents()
int ObjectIdentifier::numComponents () const
Return number of components.
Returns
Number of components in this identifier.
Definition at line 298 of file ObjectIdentifier.cpp.
References components.
numSubComponents()
int ObjectIdentifier::numSubComponents () const
Compute number of sub components, i.e excluding the property.
Returns
Number of components.
Definition at line 308 of file ObjectIdentifier.cpp.
References components, and result.
operator!=()
bool ObjectIdentifier::operator!= (const ObjectIdentifier & other) const
Compare object identifier with other.
Parameters
other Other object identifier
Returns
true if they differ from each other.
Definition at line 271 of file ObjectIdentifier.cpp.
operator<()
bool ObjectIdentifier::operator< (const ObjectIdentifier & other) const
Compare object identifier with other.
Parameters
other Other object identifier.
Returns
true if this object is less than the other.
Definition at line 282 of file ObjectIdentifier.cpp.
References owner, and toString().
operator<<() [1/2]
ObjectIdentifier & ObjectIdentifier::operator<< (ObjectIdentifier::Component && value)
Definition at line 1393 of file ObjectIdentifier.cpp.
References components, and Path.Post.scripts.opensbp_post::move().
operator<<() [2/2]
ObjectIdentifier & ObjectIdentifier::operator<< (const Component & value)
<< operator, used to add a component to the object identifier.
Parameters
value Component object
Returns
Reference to itself.
Definition at line 1386 of file ObjectIdentifier.cpp.
References components.
operator=() [1/2]
ObjectIdentifier& App::ObjectIdentifier::operator= (const ObjectIdentifier &) default
operator=() [2/2]
ObjectIdentifier& App::ObjectIdentifier::operator= (ObjectIdentifier && other) inline
Definition at line 351 of file ObjectIdentifier.h.
References Path.Post.scripts.opensbp_post::move().
operator==()
bool ObjectIdentifier::operator== (const ObjectIdentifier & other) const
Compare object identifier with other.
Parameters
other Other object identifier.
Returns
true if they are equal.
Definition at line 260 of file ObjectIdentifier.cpp.
References owner, and toString().
parse()
ObjectIdentifier ObjectIdentifier::parse (const App::DocumentObject * docObj, const std::string & str) static
Parse a string to create an object identifier.
This method throws an exception if the string is invalid.
Parameters
docObj Document object that will own this object identifier.
str String to parse
Returns
A new object identifier.
Definition at line 1360 of file ObjectIdentifier.cpp.
References FC_THROWM, App::ExpressionParser::parse(), Path.Post.scripts.refactored_centroid_post::str, and TestSpreadsheet::v.
Referenced by BOPTools.GeneralFuseResult.GeneralFuseResult::__init__(), App::PropertyExpressionEngine::afterRestore(), Gui::ExpressionBindingPy::bind(), BOPTools.GeneralFuseResult.GeneralFuseResult::explodeCompounds(), Gui::TreeWidget::itemSearch(), StdCmdExpression::pasteExpressions(), PartDesignGui::TaskExtrudeParameters::setupDialog(), BOPTools.GeneralFuseResult.GeneralFuseResult::splitAggregates(), PartGui::TaskAttacher::TaskAttacher(), FemGui::TaskFemConstraintRigidBody::TaskFemConstraintRigidBody(), and FemGui::TaskFemConstraintTransform::TaskFemConstraintTransform().
RangeComponent()
static Component App::ObjectIdentifier::RangeComponent (int _begin, int _end = INT_MAX, int _step = 1) inline static
Definition at line 328 of file ObjectIdentifier.h.
Referenced by App::VariableExpression::addComponent().
relabeledDocument()
bool ObjectIdentifier::relabeledDocument (ExpressionVisitor & v, const std::string & oldLabel, const std::string & newLabel)
Definition at line 595 of file ObjectIdentifier.cpp.
References documentName, documentNameSet, App::ObjectIdentifier::String::getString(), App::ObjectIdentifier::String::isRealString(), src.Mod.Test.testmakeWireString::String, and TestSpreadsheet::v.
Referenced by App::VariableExpression::_relabeledDocument().
relativeTo()
ObjectIdentifier ObjectIdentifier::relativeTo (const App::ObjectIdentifier & other) const
Construct the simplest possible object identifier relative to another.
Parameters
other The other object identifier.
Returns
A new simplified object identifier.
Definition at line 1328 of file ObjectIdentifier.cpp.
References components, getOwner(), SplineSurface::i, Path.Post.scripts.opensbp_post::move(), App::ObjectIdentifier::ResolveResults::propertyIndex, App::ObjectIdentifier::ResolveResults::resolvedDocument, App::ObjectIdentifier::ResolveResults::resolvedDocumentName, App::ObjectIdentifier::ResolveResults::resolvedDocumentObject, App::ObjectIdentifier::ResolveResults::resolvedDocumentObjectName, result, and subObjectName.
Referenced by App::VariableExpression::_renameObjectIdentifier().
replaceObject()
bool ObjectIdentifier::replaceObject (ObjectIdentifier & res, const App::DocumentObject * parent, App::DocumentObject * oldObj, App::DocumentObject * newObj) const
Definition at line 468 of file ObjectIdentifier.cpp.
References toolbit-attributes::doc, documentName, documentObjectName, App::DocumentObject::getDocument(), App::ObjectIdentifier::String::getString(), App::ObjectIdentifier::String::isRealString(), App::ElementNamePair::newName, App::ElementNamePair::oldName, owner, Init::parent, result, setDocumentName(), shadowSub, src.Mod.Test.testmakeWireString::String, subObjectName, and App::PropertyLinkBase::tryReplaceLink().
Referenced by App::VariableExpression::_collectReplacement().
resolve()
void ObjectIdentifier::resolve (ResolveResults & results) const protected
Resolve the object identifier to a concrete document, documentobject, and property.
This method is a helper method that fills out data in the given ResolveResults object.
Definition at line 997 of file ObjectIdentifier.cpp.
References components, documentName, documentObjectName, App::ObjectIdentifier::ResolveResults::flags, App::DocumentObject::getDocument(), getDocument(), getDocumentObject(), App::Document::getName(), App::DocumentObject::getNameInDocument(), App::Document::getObject(), App::ObjectIdentifier::ResolveResults::getProperty(), App::ObjectIdentifier::String::getString(), owner, App::ObjectIdentifier::ResolveResults::propertyIndex, App::ObjectIdentifier::ResolveResults::propertyName, App::ObjectIdentifier::ResolveResults::propertyType, ResolveAmbiguous, ResolveByIdentifier, App::ObjectIdentifier::ResolveResults::resolvedDocument, App::ObjectIdentifier::ResolveResults::resolvedDocumentName, App::ObjectIdentifier::ResolveResults::resolvedDocumentObject, App::ObjectIdentifier::ResolveResults::resolvedDocumentObjectName, App::ObjectIdentifier::ResolveResults::resolvedProperty, App::ObjectIdentifier::ResolveResults::resolvedSubObject, resolveProperty(), src.Mod.Test.testmakeWireString::String, App::ObjectIdentifier::ResolveResults::subObjectName, and subObjectName.
Referenced by App::ObjectIdentifier::ResolveResults::ResolveResults().
resolveAmbiguity() [1/2]
void ObjectIdentifier::resolveAmbiguity ()
Definition at line 2137 of file ObjectIdentifier.cpp.
References documentObjectName, documentObjectNameSet, App::ObjectIdentifier::String::getString(), App::DocumentObject::isAttachedToDocument(), App::ObjectIdentifier::String::isForceIdentifier(), isLocalProperty(), App::ObjectIdentifier::String::isRealString(), owner, and result.
Referenced by canonicalPath().
resolveAmbiguity() [2/2]
void ObjectIdentifier::resolveAmbiguity (ResolveResults & results) protected
Definition at line 2149 of file ObjectIdentifier.cpp.
References components, App::DocumentObject::getDocument(), Path.Post.scripts.opensbp_post::move(), owner, ResolveByIdentifier, result, setDocumentName(), setDocumentObjectName(), src.Mod.Test.testmakeWireString::String, and subObjectName.
resolveErrorString()
std::string ObjectIdentifier::resolveErrorString () const
Definition at line 1373 of file ObjectIdentifier.cpp.
References result.
Referenced by App::VariableExpression::getProperty().
resolveProperty()
Property * ObjectIdentifier::resolveProperty (const App::DocumentObject * obj, const char * propertyName, App::DocumentObject *& sobj, int & ptype) const protected
Definition at line 1415 of file ObjectIdentifier.cpp.
References App::ExtensionContainer::getPropertyByName(), App::ObjectIdentifier::String::getString(), App::DocumentObject::getSubObject(), propertyName(), PseudoApp, PseudoBuiltins, PseudoCadquery, PseudoCollections, PseudoGui, PseudoLinkMatrix, PseudoLinkPlacement, PseudoMath, PseudoMatrix, PseudoNone, PseudoPart, PseudoPlacement, PseudoRegex, PseudoSelf, PseudoShape, subObjectName, and App::ObjectIdentifier::String::toString().
Referenced by App::ObjectIdentifier::ResolveResults::getProperty(), and resolve().
setComponent() [1/2]
void App::ObjectIdentifier::setComponent (int idx, Component && comp)
Definition at line 226 of file ObjectIdentifier.cpp.
References FC_THROWM, and Path.Post.scripts.opensbp_post::move().
Referenced by App::VariableExpression::_moveCells(), and App::VariableExpression::_offsetCells().
setComponent() [2/2]
void App::ObjectIdentifier::setComponent (int idx, const Component & comp)
Definition at line 235 of file ObjectIdentifier.cpp.
setDocumentName()
void ObjectIdentifier::setDocumentName (ObjectIdentifier::String && name, bool force = false)
Set the document name for this object identifier.
If force is true, the document name will always be included in the string representation.
Parameters
name Name of document object.
force Force name to be set
Definition at line 1506 of file ObjectIdentifier.cpp.
References _DocumentMap, documentName, documentNameSet, Path.Post.scripts.opensbp_post::move(), and src.Mod.Test.testmakeWireString::String.
Referenced by replaceObject(), resolveAmbiguity(), and setDocumentObjectName().
setDocumentObjectName() [1/2]
void ObjectIdentifier::setDocumentObjectName (const App::DocumentObject * obj, bool force = false, ObjectIdentifier::String && subname = String(), bool checkImport = false)
Definition at line 1572 of file ObjectIdentifier.cpp.
References documentName, documentNameSet, documentObjectName, documentObjectNameSet, FC_THROWM, App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), App::PropertyString::getStrValue(), App::DocumentObject::isAttachedToDocument(), App::ObjectIdentifier::String::isRealString(), App::Document::Label, localProperty, Path.Post.scripts.opensbp_post::move(), owner, setDocumentName(), src.Mod.Test.testmakeWireString::String, and subObjectName.
setDocumentObjectName() [2/2]
void ObjectIdentifier::setDocumentObjectName (ObjectIdentifier::String && name, bool force = false, ObjectIdentifier::String && subname = String(), bool checkImport = false)
Set the document object name of this object identifier.
If force is true, the document object will not be resolved dynamically from the object identifier's components, but used as given by this method.
Parameters
name Name of document object.
force Force name to be set.
Definition at line 1555 of file ObjectIdentifier.cpp.
References documentObjectName, documentObjectNameSet, Path.Post.scripts.opensbp_post::move(), owner, and subObjectName.
Referenced by App::VariableExpression::_renameObjectIdentifier(), ObjectIdentifier(), and resolveAmbiguity().
setValue()
void ObjectIdentifier::setValue (const App::any & value) const
Set value of a property or field pointed to by this object identifier.
This method uses Python to do the actual work. and a limited set of types that can be in the App::any variable is supported: Base::Quantity, double, char*, const char*, int, unsigned int, short, unsigned short, char, and unsigned char.
Parameters
value Value to set
Definition at line 2002 of file ObjectIdentifier.cpp.
References access(), FC_THROWM, App::ObjectIdentifier::ResolveResults::propertyType, App::pyObjectFromAny(), and Base::PyException::ThrowException().
SimpleComponent() [1/4]
static Component App::ObjectIdentifier::SimpleComponent (const char * _component) inline static
Definition at line 303 of file ObjectIdentifier.h.
Referenced by App::VariableExpression::_moveCells(), App::VariableExpression::_offsetCells(), Sketcher::PropertyConstraintList::canonicalPath(), Sketcher::SketchObject::carbonCopy(), App::PropertyVector::getPaths(), Sketcher::PropertyConstraintList::getPaths(), App::PropertyPlacement::getPaths(), App::PropertyRotation::getPaths(), and ObjectIdentifier().
SimpleComponent() [2/4]
static Component App::ObjectIdentifier::SimpleComponent (const std::string _component) inline static
Definition at line 318 of file ObjectIdentifier.h.
SimpleComponent() [3/4]
static Component App::ObjectIdentifier::SimpleComponent (const String & _component) inline static
Definition at line 308 of file ObjectIdentifier.h.
SimpleComponent() [4/4]
static Component App::ObjectIdentifier::SimpleComponent (String && _component) inline static
Definition at line 313 of file ObjectIdentifier.h.
References Path.Post.scripts.opensbp_post::move().
toEscapedString()
std::string ObjectIdentifier::toEscapedString () const
Escape toString representation so it is suitable for being embedded in a python command.
Returns
Escaped string.
Definition at line 517 of file ObjectIdentifier.cpp.
References Base::Tools::escapedUnicodeFromUtf8(), and toString().
Referenced by Gui::ExpressionBinding::apply().
toPersistentString()
std::string ObjectIdentifier::toPersistentString () const
Definition at line 399 of file ObjectIdentifier.cpp.
References components, documentName, documentNameSet, documentObjectName, documentObjectNameSet, App::PropertyLinkBase::exportSubName(), App::ObjectIdentifier::String::getString(), getSubPathStr(), App::ObjectIdentifier::String::isRealString(), localProperty, owner, result, toolbit-attributes::s, src.Mod.Test.testmakeWireString::String, subObjectName, and App::ObjectIdentifier::String::toString().
Referenced by App::VariableExpression::_toString().
toString()
const std::string & ObjectIdentifier::toString () const
Create a string representation of this object identifier.
An identifier is written as document::documentobject.property.subproperty1...subpropertyN document# may be dropped; it is assumed to be within owner's document. If documentobject is dropped, the property is assumed to be owned by the owner specified in the object identifiers constructor.
Returns
A string
Definition at line 354 of file ObjectIdentifier.cpp.
References components, documentName, documentNameSet, documentObjectName, documentObjectNameSet, App::ObjectIdentifier::String::getString(), getSubPathStr(), localProperty, owner, result, toolbit-attributes::s, subObjectName, and App::ObjectIdentifier::String::toString().
Referenced by App::VariableExpression::_toString(), access(), Gui::QuantitySpinBox::boundToName(), Sketcher::SketchObject::carbonCopy(), hash(), operator<(), operator==(), and toEscapedString().
updateElementReference()
bool ObjectIdentifier::updateElementReference (ExpressionVisitor & v, App::DocumentObject * feature = nullptr, bool reverse = false)
Definition at line 2073 of file ObjectIdentifier.cpp.
References App::ObjectIdentifier::String::getString(), result, shadowSub, subObjectName, and TestSpreadsheet::v.
Referenced by App::VariableExpression::_updateElementReference().
updateLabelReference()
bool ObjectIdentifier::updateLabelReference (App::DocumentObject * obj, const std::string & ref, const char * newLabel)
Definition at line 522 of file ObjectIdentifier.cpp.
References components, documentObjectName, App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::ObjectIdentifier::String::getString(), App::PropertyString::getValue(), SplineSurface::id, App::ObjectIdentifier::String::isForceIdentifier(), App::ObjectIdentifier::String::isRealString(), App::DocumentObject::Label, owner, result, src.Mod.Test.testmakeWireString::String, subObjectName, and App::PropertyLinkBase::updateLabelReference().
Referenced by App::VariableExpression::_updateLabelReference().
verify()
bool ObjectIdentifier::verify (const App::Property & prop, bool silent = false) const
Definition at line 315 of file ObjectIdentifier.cpp.
References components, FC_THROWM, App::Property::getName(), App::CellAddress::parseAbsoluteAddress(), result, App::CellAddress::ShowRowColumn, Base::silent, and App::CellAddress::toString().
Friends And Related Function Documentation
ResolveResults
friend struct ResolveResults friend
Definition at line 578 of file ObjectIdentifier.h.
Referenced by getDepLabels(), and getSubPathStr().
Member Data Documentation
components
std::vector<Component> App::ObjectIdentifier::components protected
Definition at line 604 of file ObjectIdentifier.h.
Referenced by access(), getDepLabels(), getPropertyComponents(), getPyValue(), getStringList(), getSubPathStr(), getValue(), numComponents(), numSubComponents(), operator<<(), relativeTo(), resolve(), resolveAmbiguity(), toPersistentString(), toString(), updateLabelReference(), and verify().
documentName
String App::ObjectIdentifier::documentName protected
Definition at line 600 of file ObjectIdentifier.h.
Referenced by getStringList(), importSubNames(), relabeledDocument(), replaceObject(), resolve(), setDocumentName(), setDocumentObjectName(), toPersistentString(), and toString().
documentNameSet
bool App::ObjectIdentifier::documentNameSet protected
Definition at line 605 of file ObjectIdentifier.h.
Referenced by getStringList(), importSubNames(), relabeledDocument(), setDocumentName(), setDocumentObjectName(), toPersistentString(), and toString().
documentObjectName
String App::ObjectIdentifier::documentObjectName protected
Definition at line 601 of file ObjectIdentifier.h.
Referenced by adjustLinks(), getDepLabels(), getPropertyComponents(), getStringList(), hasDocumentObjectName(), importSubNames(), replaceObject(), resolve(), resolveAmbiguity(), setDocumentObjectName(), toPersistentString(), toString(), and updateLabelReference().
documentObjectNameSet
bool App::ObjectIdentifier::documentObjectNameSet protected
Definition at line 606 of file ObjectIdentifier.h.
Referenced by getStringList(), hasDocumentObjectName(), resolveAmbiguity(), setDocumentObjectName(), toPersistentString(), and toString().
localProperty
bool App::ObjectIdentifier::localProperty protected
Definition at line 607 of file ObjectIdentifier.h.
Referenced by setDocumentObjectName(), toPersistentString(), and toString().
owner
App::DocumentObject* App::ObjectIdentifier::owner protected
Definition at line 599 of file ObjectIdentifier.h.
Referenced by canonicalPath(), App::ObjectIdentifier::String::checkImport(), getPyValue(), getStringList(), getValue(), importSubNames(), ObjectIdentifier(), operator<(), operator==(), replaceObject(), resolve(), resolveAmbiguity(), setDocumentObjectName(), toPersistentString(), toString(), and updateLabelReference().
shadowSub
ElementNamePair App::ObjectIdentifier::shadowSub protected
Definition at line 603 of file ObjectIdentifier.h.
Referenced by getSubObjectName(), importSubNames(), replaceObject(), and updateElementReference().
subObjectName
String App::ObjectIdentifier::subObjectName protected
Definition at line 602 of file ObjectIdentifier.h.
Referenced by access(), adjustLinks(), getDepLabels(), getStringList(), getSubObjectName(), importSubNames(), relativeTo(), replaceObject(), resolve(), resolveAmbiguity(), App::ObjectIdentifier::ResolveResults::resolveErrorString(), resolveProperty(), setDocumentObjectName(), toPersistentString(), toString(), updateElementReference(), and updateLabelReference().
The documentation for this class was generated from the following files:
ObjectIdentifier.h
ObjectIdentifier.cpp