FreeCAD: nurbs Namespace Reference
nurbs Namespace Reference
Classes
struct NurbsBase1D
struct NurbsBase2D
Typedefs
using trip = Eigen::Triplet< double >
using spMat = Eigen::SparseMatrix< double >
Functions
double divide (double a, double b)
std::function< double(double)> get_basis (int degree, int i, Eigen::VectorXd knots)
std::function< double(double)> get_basis_derivative (int order, int degree, int i, Eigen::VectorXd knots)
void add_triplets (Eigen::VectorXd values, double row, std::vector< trip > &triplets)
Typedef Documentation
spMat
using nurbs::spMat = typedef Eigen::SparseMatrix<double>
Definition at line 55 of file MeshFlatteningNurbs.h.
trip
using nurbs::trip = typedef Eigen::Triplet<double>
Definition at line 54 of file MeshFlatteningNurbs.h.
Function Documentation
add_triplets()
void nurbs::add_triplets (Eigen::VectorXd values, double row, std::vector< trip > & triplets)
Definition at line 219 of file MeshFlatteningNurbs.cpp.
References nurbs::NurbsBase2D::Du_functions, nurbs::NurbsBase2D::Dv_functions, get_basis_derivative(), nurbs::NurbsBase2D::u_functions, and nurbs::NurbsBase2D::v_functions.
Referenced by nurbs::NurbsBase1D::getInfluenceVector().
divide()
double nurbs::divide (double a, double b)
Definition at line 55 of file MeshFlatteningNurbs.cpp.
References nurbs::NurbsBase1D::weights.
get_basis()
std::function<double(double)> nurbs::get_basis (int degree, int i, Eigen::VectorXd knots)
Definition at line 86 of file MeshFlatteningNurbs.cpp.
get_basis_derivative()
std::function<double(double)> nurbs::get_basis_derivative (int order, int degree, int i, Eigen::VectorXd knots)
Definition at line 130 of file MeshFlatteningNurbs.cpp.
Referenced by add_triplets().