FreeCAD: App::DocumentObject Class Reference
App::DocumentObject Class Reference
#include <DocumentObject.h>
Public Types
enum OutListOption { OutListNoExpression = 1, OutListNoHidden = 2, OutListNoXLinked = 4 }
OutList options.
enum GSReason { GS_DEFAULT, GS_SELECT }
reason of calling getSubObjects()
Public Types inherited from App::ExtensionContainer
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Public Member Functions
virtual const char * getViewProviderName () const
returns the type name of the ViewProvider
virtual const char * getViewProviderNameOverride () const
DocumentObject ()
Constructor.
~DocumentObject () override
const char * getDagKey () const
returns a value that uniquely identifies this DocumentObject.
const char * getNameInDocument () const
returns the name which is set in the document for this object (not the name property!)
long getID () const
Return the object ID that is unique within its owner document.
std::string getExportName (bool forced=false) const
returns the name that is safe to be exported to other document
std::string getFullName () const override
Return the object full name of the form DocName::ObjName.
std::string getFullLabel () const
Return the object full label in the form DocName::ObjName.
bool isAttachedToDocument () const override
const char * detachFromDocument () override
App::Document * getDocument () const
gets the document in which this Object is handled
void touch (bool noRecompute=false)
set this document object touched (cause recomputation on dependent features)
bool isTouched () const
test if this document object is touched
void enforceRecompute ()
Enforce this document object to be recomputed.
bool mustRecompute () const
Test if this document object must be recomputed.
void purgeTouched ()
reset this document object touched
bool isError () const
set this feature to error
bool isValid () const
void purgeError ()
remove the error from the object
bool isRecomputing () const
returns true if this objects is currently recomputing
bool isRestoring () const
returns true if this objects is currently restoring from file
bool isRemoving () const
returns true if this objects is currently removed from the document
void freeze ()
set this document object freezed (prevent recomputation)
void unfreeze (bool noRecompute=false)
set this document object unfreezed (and touch it)
bool isFreezed () const
returns true if this objects is currently freezed
unsigned long getStatus () const
return the status bits
bool testStatus (ObjectStatus pos) const
void setStatus (ObjectStatus pos, bool on)
int isExporting () const
virtual int setElementVisible (const char *element, bool visible)
virtual int isElementVisible (const char *element) const
virtual bool hasChildElement () const
return true to activate tree view group object handling and element visibility
const std::vector< App::DocumentObject * > & getOutList () const
returns a list of objects this object is pointing to by Links
std::vector< App::DocumentObject * > getOutList (int option) const
void getOutList (int option, std::vector< App::DocumentObject * > &res) const
std::vector< App::DocumentObject * > getOutListOfProperty (App::Property *) const
returns a list of objects linked by the property
std::vector< App::DocumentObject * > getOutListRecursive () const
returns a list of objects this object is pointing to by Links and all further descended
void clearOutListCache () const
clear internal out list cache
std::vector< std::list< App::DocumentObject * > > getPathsByOutList (App::DocumentObject *to) const
get all possible paths from this to another object following the OutList
const std::vector< App::DocumentObject * > & getInList () const
std::vector< App::DocumentObject * > getInListRecursive () const
get all objects link directly or indirectly to this object
void getInListEx (std::set< App::DocumentObject * > &inSet, bool recursive, std::vector< App::DocumentObject * > *inList=nullptr) const
std::set< App::DocumentObject * > getInListEx (bool recursive) const
DocumentObjectGroup * getGroup () const
get group if object is part of a group, otherwise 0 is returned
bool isInInListRecursive (DocumentObject *objToTest) const
test if this object is in the InList and recursive further down
bool isInInList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the InList
bool isInOutListRecursive (DocumentObject *objToTest) const
test if the given object is in the OutList and recursive further down
bool isInOutList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the OutList
void _removeBackLink (DocumentObject *)
internal, used by PropertyLink to maintain DAG back links
void _addBackLink (DocumentObject *)
internal, used by PropertyLink to maintain DAG back links
bool testIfLinkDAGCompatible (DocumentObject *linkTo) const
testIfLinkIsDAG tests a link that is about to be created for circular references.
bool testIfLinkDAGCompatible (const std::vector< DocumentObject * > &linksTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSubList &linksTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSub &linkTo) const
virtual std::string getElementMapVersion (const App::Property *prop, bool restored=false) const
virtual bool checkElementMapVersion (const App::Property *prop, const char *ver) const
Return true to signal re-generation of geometry element names.
virtual short mustExecute () const
bool recomputeFeature (bool recursive=false)
const char * getStatusString () const
get the status Message
virtual void onLostLinkToObject (DocumentObject *)
PyObject * getPyObject () override
virtual DocumentObject * getSubObject (const char *subname, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
std::vector< DocumentObject * > getSubObjectList (const char *subname, std::vector< int > *subsizes=nullptr, bool flatten=false) const
virtual std::vector< std::string > getSubObjects (int reason=0) const
std::vector< std::pair< App::DocumentObject *, std::string > > getParents (int depth=0) const
Obtain top parents and subnames of this object using its InList.
App::DocumentObject * getFirstParent () const
Obtain the first parent group of this object.
virtual DocumentObject * getLinkedObject (bool recurse=true, Base::Matrix4D *mat=nullptr, bool transform=false, int depth=0) const
virtual bool canLinkProperties () const
virtual bool isLink () const
virtual bool isLinkGroup () const
virtual bool allowDuplicateLabel () const
virtual void onBeforeChangeLabel (std::string &newLabel)
void Save (Base::Writer &writer) const override
virtual void setExpression (const ObjectIdentifier &path, std::shared_ptr< App::Expression > expr)
void clearExpression (const ObjectIdentifier &path)
virtual const PropertyExpressionEngine::ExpressionInfo getExpression (const ObjectIdentifier &path) const
virtual void renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &paths)
const std::string & getOldLabel () const
const char * getViewProviderNameStored () const
bool removeDynamicProperty (const char *prop) override
App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
App::DocumentObject * resolve (const char *subname, App::DocumentObject **parent=nullptr, std::string *childName=nullptr, const char **subElement=nullptr, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
App::DocumentObject * resolveRelativeLink (std::string &subname, App::DocumentObject *&link, std::string &linkSub) const
virtual bool adjustRelativeLinks (const std::set< App::DocumentObject * > &inList, std::set< App::DocumentObject * > *visited=nullptr)
virtual int canLoadPartial () const
virtual void onUpdateElementReference (const Property *)
virtual bool redirectSubName (std::ostringstream &ss, DocumentObject *topParent, DocumentObject *child) const
Public Member Functions inherited from App::TransactionalObject
TransactionalObject ()
Constructor.
~TransactionalObject () override
Public Member Functions inherited from App::ExtensionContainer
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
Property * getPropertyByName (const char *name) const override
find a property by its name
template<typename T >
T * getPropertyByName (const char *name) const
find a property by its name, dynamic cased to specified type
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void onChanged (const Property *) override
get called by the container when a property has changed
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop) override
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
Check if the subname reference ends with hidden marker.
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes
PropertyString Label
PropertyString Label2
PropertyExpressionEngine ExpressionEngine
PropertyBool Visibility
Allow control visibility status in App name space.
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalBeforeChange
signal before changing a property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalChanged
signal on changed property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalEarlyChanged
signal on changed property of this object before document scoped signalChangedObject
Static Public Attributes
static DocumentObjectExecReturn * StdReturn
Protected Member Functions
virtual App::DocumentObjectExecReturn * recompute ()
recompute only this object
virtual App::DocumentObjectExecReturn * execute ()
App::DocumentObjectExecReturn * executeExtensions ()
void setError ()
void resetError ()
void setDocument (App::Document *doc)
void onBeforeChange (const Property *prop) override
get called before the value is changed
void onChanged (const Property *prop) override
get called by the container when a property was changed
void onEarlyChange (const Property *prop) override
get called by the container when a property was changed
virtual void onDocumentRestored ()
get called after a document has been fully restored
virtual void onUndoRedoFinished ()
get called after an undo/redo transaction is finished
virtual void onSettingDocument ()
get called after setting the document
virtual void setupObject ()
get called after a brand new object was created
virtual void unsetupObject ()
get called when object is going to be removed from the document
void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus) override
get called when a property status has changed
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData () const
Protected Attributes
std::bitset< 32 > StatusBits
Py::SmartPtr PythonObject
python object of this class and all descendent
App::Document * _pDoc {nullptr}
pointer to the document this object belongs to
std::string oldLabel
Old label; used for renaming expressions.
const std::string * pcNameInDocument {nullptr}
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Friends
class Document
class Transaction
class ObjectExecution
Additional Inherited Members
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Base class of all Classes handled in the Document
Definition at line 101 of file DocumentObject.h.
Member Enumeration Documentation
GSReason
enum App::DocumentObject::GSReason
reason of calling getSubObjects()
Enumerator
GS_DEFAULT
default, mostly for exporting shape objects
GS_SELECT
for element selection
Definition at line 442 of file DocumentObject.h.
OutListOption
enum App::DocumentObject::OutListOption
OutList options.
DAG handling This part of the interface deals with viewing the document as a DAG (directed acyclic graph).
Enumerator
OutListNoExpression
Do not include link from expression engine.
OutListNoHidden
Do not hide any link (i.e. include links with LinkScopeHidden)
OutListNoXLinked
Do not include link from PropertyXLink.
Definition at line 269 of file DocumentObject.h.
Constructor & Destructor Documentation
DocumentObject()
App::DocumentObject::DocumentObject ()
Constructor.
~DocumentObject()
App::DocumentObject::~DocumentObject () override
Member Function Documentation
_addBackLink()
void App::DocumentObject::_addBackLink (DocumentObject * newObj)
internal, used by PropertyLink to maintain DAG back links
Definition at line 1263 of file DocumentObject.cpp.
Referenced by App::PropertyLinkSubList::addValue(), App::PropertyXLink::restoreLink(), App::PropertyLinkList::set1Value(), App::PropertyLink::setValue(), App::PropertyLinkSubList::setValue(), App::PropertyLinkSubList::setValues(), and App::PropertyXLinkContainer::updateDeps().
_removeBackLink()
void App::DocumentObject::_removeBackLink (DocumentObject * rmvObj)
internal, used by PropertyLink to maintain DAG back links
Definition at line 1249 of file DocumentObject.cpp.
References DraftVecUtils::find().
Referenced by App::PropertyXLinkContainer::breakLink(), App::PropertyXLinkContainer::clearDeps(), App::PropertyLink::resetLink(), App::PropertyLinkList::set1Value(), App::PropertyLink::setValue(), App::PropertyLinkSubList::setValue(), App::PropertyLinkSubList::setValues(), App::PropertyXLinkContainer::updateDeps(), and App::PropertyLinkSub::~PropertyLinkSub().
addDynamicProperty()
App::Property* App::DocumentObject::addDynamicProperty (const char * type, const char * name = nullptr, const char * group = nullptr, const char * doc = nullptr, short attr = 0, bool ro = false, bool hidden = false) override virtual
Reimplemented from App::PropertyContainer.
Referenced by Spreadsheet::Sheet::setFloatProperty(), Spreadsheet::Sheet::setIntegerProperty(), Spreadsheet::Sheet::setObjectProperty(), App::LinkBaseExtension::setOnChangeCopyObject(), Spreadsheet::Sheet::setQuantityProperty(), Spreadsheet::Sheet::setStringProperty(), and PartDesign::SubShapeBinder::update().
adjustRelativeLinks()
virtual bool App::DocumentObject::adjustRelativeLinks (const std::set< App::DocumentObject * > & inList, std::set< App::DocumentObject * > * visited = nullptr) virtual
Called to adjust link properties to avoid cyclic links
Parameters
inList the recursive in-list of the future parent object, including the parent itself.
visited optional set holding the visited objects. If null then only this object is adjusted, or else all object inside the out-list of this object will be checked.
Returns
Return whether the object has been modified
This function tries to adjust any relative link properties (i.e. link properties that can hold subnames) to avoid cyclic when added to the future parent.
allowDuplicateLabel()
virtual bool App::DocumentObject::allowDuplicateLabel () const inline virtual
Definition at line 512 of file DocumentObject.h.
canLinkProperties()
virtual bool App::DocumentObject::canLinkProperties () const inline virtual
Reimplemented in App::Link, and PartDesign::SubShapeBinder.
Definition at line 494 of file DocumentObject.h.
Referenced by Gui::ViewProviderLink::getPropertyByName(), and Gui::PropertyView::onTimer().
canLoadPartial()
virtual int App::DocumentObject::canLoadPartial () const inline virtual
allow partial loading of dependent objects
Returns
Returns 0 means do not support partial loading. 1 means allow dependent objects to be partially loaded, i.e. only create, but not restored. 2 means this object itself can be partially loaded.
Reimplemented in PartDesign::SubShapeBinder.
Definition at line 660 of file DocumentObject.h.
checkElementMapVersion()
virtual bool App::DocumentObject::checkElementMapVersion (const App::Property * prop, const char * ver) const virtual
Return true to signal re-generation of geometry element names.
clearExpression()
void App::DocumentObject::clearExpression (const ObjectIdentifier & path)
clearOutListCache()
void App::DocumentObject::clearOutListCache () const
clear internal out list cache
detachFromDocument()
const char* App::DocumentObject::detachFromDocument () override virtual
Reimplemented from App::TransactionalObject.
enforceRecompute()
void App::DocumentObject::enforceRecompute ()
Enforce this document object to be recomputed.
Referenced by App::Document::onChanged(), and Gui::TreeWidget::onMarkRecompute().
execute()
virtual App::DocumentObjectExecReturn* App::DocumentObject::execute () protected virtual
get called by the document to recompute this feature Normally this method get called in the processing of Document::recompute(). In execute() the output properties get recomputed with the data from linked objects and objects own properties.
Reimplemented in TechDraw::DrawTile, Drawing::FeatureProjection, Drawing::FeatureView, Drawing::FeatureViewPart, Drawing::FeatureClip, Drawing::FeatureViewSpreadsheet, Sandbox::SandboxObject, Drawing::FeatureViewAnnotation, Drawing::FeatureViewSymbol, Drawing::FeaturePage, Part::Ellipse, Part::Wedge, PartDesign::Wedge, Part::Spiral, Fem::FemPostWarpVectorFilter, Part::Helix, PartDesign::Prism, Fem::FemPostScalarClipFilter, Part::Torus, Fem::FemPostCutFilter, PartDesign::Torus, Part::Cone, Mesh::RemoveComponents, Fem::FemPostContoursFilter, Inspection::Feature, Part::RegularPolygon, PartDesign::Ellipsoid, Mesh::FillHoles, Part::Prism, App::FeatureTestAttribute, Mesh::FixIndices, Fem::FemPostClipFilter, App::FeatureTestPlacement, App::LocalCoordinateSystem, PartDesign::Cone, Mesh::FixDeformations, Part::FilletBase, Part::Reverse, Part::Cylinder, Spreadsheet::Sheet, App::FeatureTestAbsAddress, Fem::FemPostDataAtPointFilter, Mesh::Cube, Part::Refine, App::FeatureTestRow, Mesh::FixDegenerations, Part::Ellipsoid, PartDesign::Sphere, App::FeatureTestColumn, Mesh::FixDuplicatedPoints, Mesh::Torus, Part::Feature, Part::Thickness, Fem::Constraint, Fem::FemPostDataAlongLineFilter, Part::Sphere, Mesh::FixDuplicatedFaces, App::FeatureTestException, App::FeatureTest, Mesh::Cone, PartDesign::SubShapeBinder, Part::Plane, PartDesign::Cylinder, Mesh::FixNonManifolds, Part::Sweep, Measure::MeasureDistanceDetached, PartDesign::Transformed, Mesh::Cylinder, Part::Line, Sketcher::SketchObject, Mesh::FlipNormals, TechDraw::DrawViewDimension, TechDraw::DrawViewPart, TechDraw::DrawViewSection, Fem::ConstraintDisplacement, Path::FeatureAreaView, PartDesign::ShapeBinder, Part::Scale, TechDraw::DrawProjGroup, Part::Loft, TechDraw::FeatureProjection, TechDraw::DrawViewAnnotation, TechDraw::DrawViewClip, TechDraw::DrawViewCollection, Fem::ConstraintFluidBoundary, PartDesign::Box, TechDraw::DrawViewArch, Fem::ConstraintContact, Part::Extrusion, PartDesign::Groove, PartDesign::FeaturePrimitive, PartDesign::Revolution, Fem::ConstraintBearing, Fem::FemPostFilter, TechDraw::DrawViewDraft, Fem::ConstraintRigidBody, Mesh::HarmonizeNormals, Mesh::Export, Robot::TrajectoryDressUpObject, TechDraw::DrawPage, Fem::ConstraintPulley, Fem::FemResultObject, Part::ProjectOnSurface, Surface::GeomFillSurface, TechDraw::DrawBrokenView, Fem::ConstraintHeatflux, Fem::ConstraintTemperature, Fem::FemPostFunction, Robot::Edge2TracObject, Fem::FemMeshShapeNetgenObject, Measure::MeasureAngle, Mesh::FixDefects, Mesh::SegmentByMesh, Part::Offset2D, PartDesign::Boolean, Surface::FeatureBlendCurve, TechDraw::DrawProjGroupItem, TechDraw::DrawViewImage, Path::FeatureArea, Fem::ConstraintInitialTemperature, Measure::MeasurePosition, Mesh::Ellipsoid, Part::Revolution, PartDesign::Pad, TechDraw::DrawViewSpreadsheet, Measure::MeasureArea, Measure::MeasureRadius, Mesh::SetOperations, Mesh::Transform, Part::Offset, PartDesign::Draft, Surface::Extend, Fem::ConstraintGear, Fem::ConstraintTransform, Fem::FemSolverObject, Mesh::Curvature, TechDraw::DrawViewDimExtent, Path::FeatureCompound, Fem::FemMeshObject, Mesh::Import, Mesh::TransformDemolding, PartDesign::Chamfer, PartDesign::Pipe, PartDesign::Pocket, Points::Structured, Assembly::AssemblyObject, Path::Feature, Fem::FemPostPipeline, Fem::FemSetElementNodesObject, Fem::FemSetNodesObject, Measure::MeasureLength, Mesh::Sphere, Part::Vertex, PartDesign::Thickness, Surface::Sewing, TechDraw::DrawRichAnno, Fem::ConstraintForce, Fem::FemSetObject, Part::Mirroring, Part::RuledSurface, PartDesign::FeatureBase, Robot::TrajectoryCompound, Robot::TrajectoryObject, TechDraw::DrawView, App::InventorObject, Part::Circle, Part::Polygon, Part::Part2DObject, PartDesign::Helix, Robot::RobotObject, App::VRMLObject, Fem::ConstraintSpring, Fem::FemSetElementsObject, Fem::FemSetFacesObject, Fem::FemSetGeometryObject, Part::CustomFeature, Part::Compound, Part::Box, PartDesign::Fillet, Sketcher::SketchObjectSF, Fem::ConstraintPressure, Part::ImportStep, Fem::FemMeshShapeObject, Part::Face, Part::FeatureGeometrySet, PartDesign::Loft, Fem::ConstraintFixed, Fem::ConstraintPlaneRotation, Part::CurveNet, Part::ImportBrep, Part::ImportIges, Part::Primitive, Surface::Cut, Surface::Sections, Part::Chamfer, Part::Fillet, Part::MultiCommon, Part::MultiFuse, PartDesign::Hole, Measure::MeasureDistance, Assembly::AssemblyLink, TechDraw::DrawViewSymbol, Assembly::BomObject, TechDraw::DrawLeaderLine, Mesh::Feature, TechDraw::DrawViewBalloon, TechDraw::DrawWeldSymbol, Part::FeatureReference, Surface::Filling, TechDraw::DrawViewDetail, Points::Feature, TechDraw::DrawGeomHatch, TechDraw::DrawViewMulti, TechDraw::DrawParametricTemplate, PartDesign::Body, TechDraw::DrawHatch, TechDraw::LandmarkDimension, and Part::Boolean.
Referenced by draftobjects.facebinder.Facebinder::addSubobjects(), Path.Dressup.Gui.Dogbone.ObjectDressup::boneStateList(), TechDraw::DrawViewBalloon::execute(), Assembly::AssemblyLink::execute(), TechDraw::DrawView::execute(), Fem::FemPostPipeline::execute(), Assembly::AssemblyObject::execute(), TechDraw::DrawPage::execute(), App::LocalCoordinateSystem::execute(), Path.Dressup.Tags.ObjectTagDressup::generateTags(), ArchRoof._Roof::getSubVolume(), ArchPanel.PanelCut::getWires(), src.Mod.PartDesign.Scripts.Spring.MySpring::onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid::onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped::onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt::onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder::onChanged(), MeasureCOM.MeasureCOM::onChanged(), Path.Main.Stock.StockFromBase::onChanged(), Path.Main.Stock.StockCreateBox::onChanged(), Path.Main.Stock.StockCreateCylinder::onChanged(), FeaturePython.DistanceBolt::onChanged(), draftobjects.draftlink.DraftLink::onDocumentRestored(), ArchSchedule._ArchSchedule::setSpreadsheetData(), and draftobjects.array.Array::update_properties_0v21().
executeExtensions()
App::DocumentObjectExecReturn* App::DocumentObject::executeExtensions () protected
Executes the extensions of a document object.
freeze()
void App::DocumentObject::freeze ()
set this document object freezed (prevent recomputation)
getDagKey()
const char* App::DocumentObject::getDagKey () const
returns a value that uniquely identifies this DocumentObject.
Referenced by Gui::LinkInfo::getLinkedName().
getDocument()
App::Document* App::DocumentObject::getDocument () const
gets the document in which this Object is handled
Referenced by TechDrawGui::_createBalloon(), TechDrawGui::_createLinDimension(), _getTopoShape(), SpreadsheetGui::DlgBindSheet::accept(), PartGui::FaceAppearances::accept(), FemGui::TaskDlgMeshShapeNetgen::accept(), TechDrawGui::TaskLineDecor::accept(), PartDesignGui::TaskShapeBinder::accept(), TechDrawGui::TaskProjGroup::accept(), TechDrawGui::TaskDetail::accept(), TechDrawGui::TaskCosVertex::accept(), Gui::TaskOrientation::accept(), TechDrawGui::TaskRichAnno::accept(), TechDrawGui::TaskLeaderLine::accept(), TechDrawGui::TaskCenterLine::accept(), PathGui::TaskDlgPathCompound::accept(), Gui::TaskImage::accept(), PartDesignGui::TaskDlgFeatureParameters::accept(), PartGui::DlgProjectOnSurface::accept(), PartGui::DlgPrimitives::accept(), Gui::Dialog::TransformStrategy::acceptDataTransform(), StdCmdToggleTransparency::activated(), Gui::ViewProviderDocumentObject::addDynamicProperty(), Sketcher::SketchObject::addExternal(), PartDesignGui::ComboLinks::addLink(), App::GroupExtension::addObject(), App::Document::addObject(), Assembly::BomObject::addObjectToBom(), TechDraw::DrawProjGroup::addProjection(), TechDrawGui::MDIViewPage::addSceneItemToTreeSel(), adjustLinkSubs(), App::PropertyXLinkContainer::afterRestore(), Gui::ExpressionBinding::apply(), Gui::Dialog::TransformStrategy::applyViewTransform(), Gui::TaskView::TaskDialog::associateToObject3dView(), Gui::ViewProviderVRMLObject::attach(), Gui::ViewProviderDatum::attach(), RobotGui::ViewProviderTrajectory::attach(), RobotGui::ViewProviderRobotObject::attach(), Gui::ViewProviderAnnotation::attach(), MeshGui::ViewProviderMeshCurvature::attach(), PointsGui::ViewProviderScattered::attach(), MeshGui::ViewProviderMesh::attach(), PointsGui::ViewProviderStructured::attach(), Sketcher::SketchObject::attachExternal(), Gui::ExpressionBinding::bind(), App::PropertyXLinkContainer::breakLink(), App::DocInfo::breakLinks(), PartDesign::FeatureExtrude::buildExtrusion(), Gui::ViewProviderLink::canDragAndDropObject(), Gui::ViewProviderDocumentObject::canDropObjectEx(), Gui::ViewProviderLink::canDropObjectEx(), Sketcher::SketchObject::carbonCopy(), PartDesign::SubShapeBinder::checkCopyOnChange(), App::LinkBaseExtension::checkGeoElementMap(), App::ObjectIdentifier::String::checkImport(), Gui::TreeWidget::checkTopParent(), PartDesign::SubShapeBinder::clearCopiedObjects(), App::PropertyXLinkContainer::clearDeps(), Gui::cmdAppObjectShow(), Gui::DAG::Model::contextMenuEvent(), App::PropertyXLink::copyTo(), TechDrawGui::TaskActiveView::createActiveView(), TechDrawGui::TaskRichAnno::createAnnoFeature(), TechDrawGui::QGSPage::createBalloon(), TechDrawGui::TaskDetail::createDetail(), TechDrawGui::TaskHatch::createHatch(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), TechDrawGui::TaskSectionView::createSectionView(), Gui::ViewProviderIndex::data(), App::DocumentObjectWeakPtrT::Private::deletedDocument(), SketcherGui::ViewProviderSketch::deleteSelected(), App::LinkBaseExtension::detachElement(), dimensionMaker(), dimMaker(), SpreadsheetGui::DlgBindSheet::DlgBindSheet(), FemGui::ViewProviderFemAnalysis::doubleClicked(), AssemblyGui::ViewProviderBom::doubleClicked(), Assembly::AssemblyLink::ensureJointGroup(), Assembly::AssemblyLink::ensureNoJointGroup(), PartDesign::Loft::execute(), Part::Thickness::execute(), App::Document::exportGraphviz(), Import::ExportOCAF2::exportObjects(), App::PropertyLinkBase::exportSubName(), Gui::ViewProviderGroupExtension::extensionDragObject(), App::LinkBaseExtension::extensionExecute(), App::OriginGroupExtension::extensionOnChanged(), Gui::ViewProviderDocumentObject::findFrontRootOfType(), TechDrawGui::QGSPage::fixOrphans(), PartDesignGui::fixSketchSupport(), Gui::Dialog::DlgPropertyLink::formatObject(), Assembly::BomObject::generateBOM(), Gui::ViewProviderDocumentObject::getActiveView(), TechDraw::DrawTemplate::getAutofillValue(), TechDrawGui::TaskDetail::getDetailFeat(), Gui::ViewProviderDocumentObject::getDocument(), FemGui::TaskPostBox::getDocument(), App::PropertyXLink::getDocumentInList(), App::PropertyXLink::getDocumentOutList(), Gui::ViewProviderDocumentObject::getEditingView(), Part::Feature::getElementHistory(), getElementSource(), Assembly::AssemblyObject::getExplodedViewGroup(), TechDrawGui::QGIView::getFrameState(), App::GeoFeature::getGlobalPlacement(), Assembly::AssemblyObject::getGroup(), InspectionGui::ViewProviderInspection::getIcon(), Gui::ViewProviderDocumentObject::getInventorView(), Assembly::AssemblyObject::getJoints(), Assembly::getMovingPartFromRef(), App::GroupExtension::getObject(), Gui::Command::getObjectCmd(), TechDraw::DrawTemplate::getPageNumbers(), PartDesignGui::getPartFor(), App::PropertyLinkSubList::getPyReprString(), App::PropertyXLinkSubList::getPyReprString(), TechDrawGui::ViewProviderTemplate::getQTemplate(), TechDrawGui::ViewProviderDrawingView::getQView(), PartDesignGui::getReferencedSelection(), PartDesignGui::ViewProviderDatum::getRelevantBoundBox(), PartDesign::Loft::getSectionShape(), Gui::TreeWidget::getSelection(), MeshPartGui::Tessellation::getStandardParameters(), Assembly::AssemblyObject::getSubAssemblies(), PartDesign::ProfileBased::getTopoShapeVerifiedFace(), Gui::Command::getUniqueObjectName(), Gui::LinkInfo::getView(), Gui::ViewProviderDocumentObject::getViewOfNode(), TechDrawGui::QGIView::getViewProvider(), TechDrawGui::QGIView::getViewProviderPage(), PartDesign::ProfileBased::handleChangedPropertyName(), App::DocInfo::hasXLink(), App::Expression::importSubNames(), App::ObjectIdentifier::importSubNames(), Spreadsheet::PropertySheet::insertColumns(), Spreadsheet::PropertySheet::insertRows(), PartDesignGui::isAnyNonPartDesignLinksTo(), Gui::TreeWidget::isObjectShowable(), Gui::DocumentItem::isObjectShowable(), Gui::SelectionSingleton::isSelected(), TechDrawGui::TaskLinkDim::loadAvailDims(), MeshGui::RemeshGmsh::loadOutput(), PartDesignGui::makeBodyActive(), App::LinkBaseExtension::makeCopyOnChange(), TechDraw::DrawDimHelper::makeDistDim(), TechDraw::DrawDimHelper::makeExtentDim(), TechDraw::DrawDimHelper::makeExtentDim3d(), Gui::DAG::Model::mouseDoubleClickEvent(), Gui::DAG::Model::mousePressEvent(), App::Document::moveObject(), PartDesignGui::TaskSketchBasedParameters::onAddSelection(), Part::Feature::onBeforeChange(), Gui::ViewProviderDocumentObject::onBeforeChange(), PartDesign::DressUp::onChanged(), TechDraw::DrawViewSection::onChanged(), PartDesign::Body::onChanged(), Part::FilletBase::onChanged(), App::GeoFeature::onChanged(), Gui::TreeWidget::onCreateGroup(), AssemblyGui::ViewProviderAssembly::onDelete(), App::OriginGroupExtension::onExtendedSetupObject(), App::OriginGroupExtension::onExtendedUnsetupObject(), Gui::TreeWidget::onFinishEditing(), SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsItemSelectionChanged(), SketcherGui::TaskSketcherElements::onListWidgetElementsItemPressed(), SketcherGui::TaskSketcherElements::onListWidgetElementsMouseMoveOnItem(), Gui::ViewProviderDocumentObject::onPropertyStatusChanged(), PartGui::FaceAppearances::onSelectionChanged(), PartDesignGui::TaskBooleanParameters::onSelectionChanged(), SketcherGui::TaskSketcherElements::onSelectionChanged(), SketcherGui::TaskSketcherConstraints::onSelectionChanged(), TechDraw::DrawWeldSymbol::onSettingDocument(), Fem::Constraint::onSettingDocument(), PartGui::FaceAppearances::open(), Gui::TaskOrientation::open(), Gui::TaskImage::open(), Gui::ViewProviderT::operator=(), App::DocumentObjectT::operator=(), PartDesignGui::TaskTransformedParameters::originalSelected(), Gui::DocumentItem::populateItem(), prepareProfileBased(), prepareTransformed(), TechDrawGui::MDIViewPage::preSelectionChanged(), TechDrawGui::PagePrinter::print(), Gui::ElementColors::Private::Private(), PartGui::FaceAppearances::Private::Private(), FemGui::TaskDlgPost::recompute(), TechDrawGui::TaskBalloon::recomputeFeature(), TechDrawGui::TaskDimension::recomputeFeature(), TechDrawGui::TaskLeaderLine::recomputeFeature(), PartDesignGui::ViewProviderTransformed::recomputeFeature(), PartDesignGui::TaskFeatureParameters::recomputeFeature(), TechDraw::ReferenceEntry::ReferenceEntry(), PartDesignGui::TaskPipeParameters::referenceSelected(), PartDesignGui::TaskPipeScaling::referenceSelected(), PartGui::ThicknessWidget::reject(), PartGui::FaceAppearances::reject(), TechDrawGui::TaskGeomHatch::reject(), FemGui::TaskDlgMeshShapeNetgen::reject(), TechDrawGui::TaskLineDecor::reject(), TechDrawGui::TaskProjGroup::reject(), TechDrawGui::TaskDetail::reject(), Gui::TaskOrientation::reject(), TechDrawGui::TaskCosVertex::reject(), TechDrawGui::TaskRichAnno::reject(), TechDrawGui::TaskLeaderLine::reject(), TechDrawGui::TaskCenterLine::reject(), Gui::TaskImage::reject(), PartGui::DlgProjectOnSurface::reject(), PartGui::DlgPrimitives::reject(), PartDesignGui::relinkToBody(), Spreadsheet::PropertySheet::removeColumns(), Gui::ViewProviderDocumentObject::removeDynamicProperty(), TechDraw::DrawProjGroup::removeProjection(), Spreadsheet::PropertySheet::removeRows(), TechDrawGui::MDIViewPage::removeUnselectedTreeSelection(), TechDraw::DrawPage::removeView(), App::ObjectIdentifier::replaceObject(), Gui::Dialog::TransformStrategy::resetViewTransform(), App::ObjectIdentifier::resolve(), App::ObjectIdentifier::resolveAmbiguity(), App::PropertyLinkList::Restore(), App::PropertyLinkSubList::Restore(), Gui::SelectionSingleton::sAddSelection(), App::PropertyXLinkContainer::Save(), App::VRMLObject::SaveDocFile(), TechDrawGui::QGSPage::saveSvg(), Gui::SelectionObject::SelectionObject(), Gui::SelectionObserver::SelectionObserver(), App::DocumentObjectWeakPtrT::Private::set(), FemGui::ActiveAnalysisObserver::setActiveObject(), Spreadsheet::PropertySheet::setAlias(), Gui::DocumentObjectItem::setData(), ExpressionCompleterModel::setDocumentObject(), App::ObjectIdentifier::setDocumentObjectName(), TechDrawGui::ViewProviderViewPart::setEdit(), SurfaceGui::FillingVertexPanel::setEditedObject(), SurfaceGui::FillingEdgePanel::setEditedObject(), SurfaceGui::GeomFillSurface::setEditedObject(), SurfaceGui::SectionsPanel::setEditedObject(), SurfaceGui::FillingPanel::setEditedObject(), SketcherGui::ViewProviderSketch::setEditViewer(), App::LinkBaseExtension::setLink(), App::LinkBaseExtension::setOnChangeCopyObject(), Spreadsheet::PropertySheet::setPathValue(), Gui::PropertyEditor::PropertyItem::setPropertyValue(), TechDrawGui::ViewProviderPage::setTemplateMarkers(), TechDrawGui::MDIViewPage::setTreeToSceneSelect(), App::PropertyLink::setValue(), FemGui::FunctionWidget::setViewProvider(), PartDesignGui::ViewProviderBody::setVisualBodyMode(), Gui::ApplicationPy::sExport(), DrawingGui::ViewProviderDrawingPage::showDrawingView(), Gui::SelectionSingleton::slotDeletedObject(), App::DocInfo::slotDeleteDocument(), Gui::DocumentItem::slotRecomputedObject(), TechDrawGui::TaskDimRepair::slotUseSelection(), Gui::SelectionSingleton::sRemoveSelection(), Gui::SelectionSingleton::sSetPreselection(), Gui::SelectionSingleton::sUpdateSelection(), Assembly::AssemblyLink::synchronizeComponents(), Assembly::AssemblyLink::synchronizeJoints(), TechDrawGui::TaskComplexSection::TaskComplexSection(), TechDrawGui::TaskCosVertex::TaskCosVertex(), TechDrawGui::TaskDetail::TaskDetail(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), TechDrawGui::TaskProjGroup::TaskProjGroup(), TechDrawGui::TaskRichAnno::TaskRichAnno(), TechDrawGui::TaskSectionView::TaskSectionView(), Gui::DocumentObjectItem::testStatus(), TechDrawGui::TaskProjGroup::turnProjGroupToView(), TechDrawGui::TaskProjGroup::turnViewToProjGroup(), UnifiedDatumCommand(), PartDesignGui::ViewProviderBody::unifyVisualProperty(), PartDesignGui::ViewProvider::unsetEdit(), TechDraw::DrawViewCollection::unsetupObject(), TechDraw::DrawPage::unsetupObject(), TechDraw::DrawViewPart::unsetupObject(), Gui::TaskMeasure::update(), PartDesign::SubShapeBinder::update(), DrawingGui::ViewProviderDrawingPage::updateData(), Gui::ViewProviderInventorObject::updateData(), App::PropertyXLinkContainer::updateDeps(), TechDrawGui::TaskLinkDim::updateDims(), TechDrawGui::ViewProviderGeomHatch::updateGraphic(), Gui::DocumentItem::updateItemSelection(), App::ObjectIdentifier::updateLabelReference(), PartGui::DlgScale::writeParametersToFeature(), and PartGui::DlgExtrusion::writeParametersToFeature().
getElementMapVersion()
virtual std::string App::DocumentObject::getElementMapVersion (const App::Property * prop, bool restored = false) const virtual
Return the element map version of the geometry data stored in the given property
Parameters
prop the geometry property to query for element map version
restored whether to query for the restored element map version. In case of version upgrade, the restored version may be different from the current version.
Returns
Return the element map version string.
getExportName()
std::string App::DocumentObject::getExportName (bool forced = false) const
returns the name that is safe to be exported to other document
Referenced by App::PropertyLinkBase::exportSubName(), App::PropertyLink::Save(), App::PropertyLinkList::Save(), App::PropertyLinkSub::Save(), App::PropertyLinkSubList::Save(), App::PropertyXLink::Save(), and App::PropertyLinkBase::tryImport().
getExpression()
virtual const PropertyExpressionEngine::ExpressionInfo App::DocumentObject::getExpression (const ObjectIdentifier & path) const virtual
Referenced by Sketcher::SketchObject::addCopyOfConstraints(), Gui::InputField::bind(), Spreadsheet::PropertySheet::getBinding(), Gui::ExpressionBinding::getExpression(), and ExpressionDelegate::paint().
getFirstParent()
App::DocumentObject* App::DocumentObject::getFirstParent () const
Obtain the first parent group of this object.
Referenced by TechDraw::DrawViewDimension::setAll3DMeasurement(), and TechDraw::DrawViewDimension::setReferences3d().
getFullLabel()
std::string App::DocumentObject::getFullLabel () const
Return the object full label in the form DocName::ObjName.
Referenced by Gui::cmdAppObjectShow(), and Part::Mirroring::execute().
getFullName()
std::string App::DocumentObject::getFullName () const override virtual
Return the object full name of the form DocName::ObjName.
Reimplemented from App::PropertyContainer.
Referenced by App::Document::_recomputeFeature(), App::Document::_removeObject(), SpreadsheetGui::DlgSheetConf::accept(), Spreadsheet::PropertySheet::adjustLink(), App::PropertyXLinkContainer::afterRestore(), Gui::ViewProviderLink::attach(), App::PropertyXLinkContainer::breakLink(), PartDesign::FeatureExtrude::buildExtrusion(), App::PropertyXLink::checkRestore(), Gui::TreeWidget::dragMoveEvent(), PartDesign::Hole::execute(), PartDesign::Thickness::execute(), Spreadsheet::Sheet::execute(), App::OriginGroupExtension::extensionOnChanged(), Assembly::AssemblyObject::fixGroundedPart(), Gui::Dialog::DlgPropertyLink::formatObject(), Part::PropertyShapeCache::get(), PartDesign::DressUp::getAddSubShape(), App::LocalCoordinateSystem::getAxis(), PartDesign::DressUp::getContinuousEdges(), App::LocalCoordinateSystem::getDatumElement(), PartDesign::DressUp::getFaces(), Gui::ViewProviderDocumentObject::getFullName(), Assembly::AssemblyObject::getMbDData(), App::OriginGroupExtension::getOrigin(), App::LocalCoordinateSystem::getPlane(), App::LocalCoordinateSystem::getPoint(), Assembly::AssemblyObject::getRackPinionMarkers(), Gui::DocumentObjectItem::getRelativeParent(), Gui::TreeWidget::getSelection(), Part::Feature::getSubObject(), Gui::DocumentItem::getTopParent(), Assembly::AssemblyObject::handleOneSideOfJoint(), Spreadsheet::PropertySheet::invalidateDependants(), Assembly::AssemblyObject::isJointConnectingPartToGround(), Assembly::AssemblyObject::isPartGrounded(), Gui::LinkInfo::LinkInfo(), Assembly::AssemblyObject::makeMbdJoint(), Spreadsheet::Sheet::onDocumentRestored(), Part::FilletBase::onUpdateElementReference(), Gui::DocumentItem::populateItem(), Gui::DocumentItem::populateObject(), Spreadsheet::Sheet::providesTo(), App::Document::readObjects(), App::PropertyLinkBase::restoreLabelReference(), Spreadsheet::PropertySheet::setAlias(), Spreadsheet::Cell::setException(), Gui::ActiveObjectList::setObject(), App::LinkBaseExtension::setOnChangeCopyObject(), Spreadsheet::Cell::setResolveException(), Gui::Document::slotChangedObject(), Gui::Document::slotNewObject(), Gui::Document::slotTouchedObject(), Gui::DocumentP::tryGetSubObject(), Gui::DocumentP::tryGetSubViewProvider(), App::PropertyLinkBase::tryImportSubName(), Gui::DocumentP::tryStartEditing(), PartDesign::SubShapeBinder::update(), App::PropertyXLinkContainer::updateDeps(), App::LinkBaseExtension::updateGroup(), and PartGui::ViewProviderPartExt::updateVisual().
getGroup()
DocumentObjectGroup* App::DocumentObject::getGroup () const
get group if object is part of a group, otherwise 0 is returned
getID()
long App::DocumentObject::getID () const inline
Return the object ID that is unique within its owner document.
Definition at line 150 of file DocumentObject.h.
Referenced by _getTopoShape(), PartDesign::FeatureExtrude::buildExtrusion(), App::LinkBaseExtension::checkGeoElementMap(), PartDesign::Loft::execute(), PartDesign::Groove::execute(), PartDesign::FeaturePrimitive::execute(), PartDesign::Revolution::generateRevolution(), Part::Feature::getElementFromSource(), Data::HistoryItem::HistoryItem(), Gui::DocumentItem::slotNewObject(), and PartDesign::SubShapeBinder::update().
getInList()
const std::vector<App::DocumentObject*>& App::DocumentObject::getInList () const
Referenced by _getPartOfObject(), _isInInListRecursive(), PartDesignGui::TaskDlgFeatureParameters::accept(), StdCmdToggleTransparency::activated(), AssemblyGui::ViewProviderAssembly::canDelete(), TechDrawGui::ViewProviderProjGroup::claimChildren(), TechDrawGui::ViewProviderAnnotation::claimChildren(), TechDraw::DrawView::countParentPages(), TechDrawGui::ViewProviderPageExtension::dropObject(), App::OriginGroupExtension::extensionOnChanged(), App::GroupExtension::extensionOnChanged(), TechDraw::DrawView::findAllParentPages(), TechDraw::DrawView::findParentPage(), Assembly::BomObject::getAssembly(), TechDraw::DrawViewPart::getBalloons(), TechDraw::DrawView::getClipGroup(), TechDraw::DrawView::getCollection(), TechDraw::DrawViewPart::getDetailRefs(), TechDraw::DrawViewPart::getDimensions(), TechDraw::DrawViewPart::getGeomHatches(), App::OriginGroupExtension::getGroupOfObject(), App::GeoFeatureGroupExtension::getGroupOfObject(), App::GroupExtension::getGroupOfObject(), TechDraw::DrawViewPart::getHatches(), App::DatumElement::getLCS(), TechDraw::DrawView::getLeaders(), App::LinkElement::getLinkGroup(), App::Application::getLinksTo(), PartDesignGui::getParent(), Assembly::AssemblyLink::getParentAssembly(), TechDraw::DrawTemplate::getParentPage(), TechDraw::DrawViewPart::getSectionRefs(), TechDraw::DrawWeldSymbol::getTiles(), Assembly::AssemblyLink::handleJointReference(), TechDrawGui::ViewProviderViewClip::hide(), DrawingGui::ViewProviderDrawingView::hide(), DrawingGui::ViewProviderDrawingClip::hide(), TechDraw::DrawView::isInClip(), TechDraw::DrawViewSection::postSectionCutTasks(), TechDrawGui::ViewProviderViewClip::show(), DrawingGui::ViewProviderDrawingView::show(), DrawingGui::ViewProviderDrawingClip::show(), and PartDesignGui::ViewProviderTransformed::startEditing().
getInListEx() [1/2]
std::set<App::DocumentObject*> App::DocumentObject::getInListEx (bool recursive) const
Return a set of all objects linking to this object, including possible external parent objects
Parameters
recursive [in]: whether to obtain recursive in list
getInListEx() [2/2]
void App::DocumentObject::getInListEx (std::set< App::DocumentObject * > & inSet, bool recursive, std::vector< App::DocumentObject * > * inList = nullptr) const
Get a set of all objects linking to this object, including possible external parent objects
Parameters
inSet [out]: a set containing all objects linking to this object.
recursive [in]: whether to obtain recursive in list
inList [in, out]: optional pointer to a vector holding the output objects, with the furthest linking object ordered last.
Referenced by execComplexSection(), ExpressionCompleterModel::setDocumentObject(), PartDesign::SubShapeBinder::setLinks(), and App::PropertyExpressionEngine::validateExpression().
getInListRecursive()
std::vector<App::DocumentObject*> App::DocumentObject::getInListRecursive () const
get all objects link directly or indirectly to this object
getLinkedObject()
virtual DocumentObject* App::DocumentObject::getLinkedObject (bool recurse = true, Base::Matrix4D * mat = nullptr, bool transform = false, int depth = 0) const virtual
Return the linked object with optional transformation
Parameters
recurse If false, return the immediate linked object, or else recursively call this function to return the final linked object.
mat If non zero, it is used as the current transformation matrix on input. And output as the accumulated transformation till the final linked object.
transform if false, then it will not accumulate the object's own placement into mat, which lets you override the object's placement.
Returns
Return the linked object. This function must return itself if the it is not a link or the link is invalid.
Referenced by _getTopoShape(), Mesh::Exporter::addObject(), Assembly::BomObject::addObjectChildrenToBom(), TechDrawGui::ViewProviderPageExtension::dropObject(), expandSubObjectNames(), TechDrawGui::ViewProviderPageExtension::extensionCanDropObject(), TechDrawGui::ViewProviderPageExtension::extensionCanDropObjectEx(), Attacher::AttachEngine::extractGeoFeature(), TechDraw::DrawPage::getAllViews(), Gui::ViewProviderLink::getElementColors(), Part::Feature::getElementHistory(), getElementSource(), Measure::MeasureBaseExtendable< Part::MeasureAreaInfo >::getGeometryHandler(), App::GeoFeature::getGlobalPlacement(), Gui::ViewProviderLink::getLinkedView(), Gui::ViewProviderDocumentObject::getLinkedViewProvider(), Assembly::getMovingPartFromRef(), Part::Feature::getShapeOwner(), TechDraw::DrawViewCollection::getViews(), TechDraw::DrawViewClip::getViews(), TechDraw::DrawPage::getViews(), Gui::DocumentObjectItem::isGroup(), Gui::DocumentObjectItem::isLink(), Gui::DocumentObjectItem::isLinkFinal(), linkConvert(), Gui::PropertyView::onTimer(), Gui::DocumentItem::populateItem(), TechDraw::DrawViewCollection::rebuildViewList(), App::GeoFeature::resolveElement(), Gui::Document::setActiveView(), Gui::ViewProviderLink::startEditing(), Assembly::AssemblyLink::synchronizeComponents(), Gui::DocumentObjectItem::testStatus(), and Gui::TaskMeasure::update().
getNameInDocument()
const char* App::DocumentObject::getNameInDocument () const
returns the name which is set in the document for this object (not the name property!)
Referenced by TechDrawGui::_createBalloon(), TechDrawGui::_createLinDimension(), ExpressionCompleterModel::_data(), App::PropertyLinkBase::_registerElementReference(), App::Document::_removeObject(), App::PropertyLinkBase::_updateElementReference(), MeshGui::Segmentation::accept(), ReverseEngineeringGui::Segmentation::accept(), PartGui::DlgRevolution::accept(), FemGui::TaskDlgFemConstraintInitialTemperature::accept(), FemGui::TaskDlgFemConstraintSpring::accept(), FemGui::TaskDlgFemConstraintPressure::accept(), FemGui::TaskDlgFemConstraintContact::accept(), FemGui::TaskDlgFemConstraintTemperature::accept(), FemGui::TaskDlgFemConstraintTransform::accept(), FemGui::TaskDlgFemConstraintRigidBody::accept(), FemGui::TaskDlgFemConstraintHeatflux::accept(), FemGui::TaskDlgFemConstraintPulley::accept(), FemGui::TaskDlgFemConstraintBearing::accept(), FemGui::TaskDlgFemConstraintGear::accept(), FemGui::TaskDlgFemConstraintForce::accept(), FemGui::TaskDlgFemConstraintDisplacement::accept(), FemGui::TaskDlgFemConstraint::accept(), MeshGui::SegmentationBestFit::accept(), FemGui::TaskDlgFemConstraintFluidBoundary::accept(), PartGui::FaceAppearances::Private::addFacesToSelection(), App::GroupExtension::addObject(), TechDraw::DrawProjGroup::addProjection(), TechDrawGui::MDIViewPage::addSceneItemToTreeSel(), App::ObjectIdentifier::adjustLinks(), PartGui::MirrorPlaneSelection::allow(), Gui::ElementColors::Private::allow(), Gui::SelectionGateFilterExternal::allow(), Gui::ExpressionBinding::apply(), TechDraw::DrawProjGroup::arrangeViewPointers(), Gui::ViewProviderLine::attach(), Gui::ViewProviderVRMLObject::attach(), Gui::ViewProviderDatum::attach(), RobotGui::ViewProviderTrajectory::attach(), RobotGui::ViewProviderRobotObject::attach(), Gui::ViewProviderAnnotation::attach(), TechDrawGui::ViewProviderPage::attach(), PartDesignGui::ViewProviderSubShapeBinder::attach(), PointsGui::ViewProviderScattered::attach(), MeshGui::ViewProviderMesh::attach(), PointsGui::ViewProviderStructured::attach(), TechDraw::DrawViewPart::buildGeometryObject(), TechDraw::DrawProjGroup::canDelete(), Gui::SelectionSingleton::checkSelection(), TechDraw::ShapeExtractor::checkShape(), Gui::LinkInfo::checkSubname(), TechDrawGui::ViewProviderViewPart::claimChildren(), PartDesign::SubShapeBinder::clearCopiedObjects(), Gui::cmdAppObjectShow(), PartDesign::SubShapeBinder::collapseGeoChildren(), Gui::DAG::Model::contextMenuEvent(), App::PropertyXLink::copyTo(), countExpandedItem(), TechDrawGui::TaskActiveView::createActiveView(), TechDrawGui::TaskRichAnno::createAnnoFeature(), TechDrawGui::QGSPage::createBalloon(), Gui::TreeWidgetItemDelegate::createEditor(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), TechDrawGui::TaskSectionView::createSectionView(), DefineElementsCallback(), DefineNodesCallback(), SpreadsheetGui::SheetTableView::deleteSelection(), App::LinkBaseExtension::detachElement(), dimensionMaker(), dimMaker(), Gui::DocumentObjectItem::displayStatusInfo(), Gui::DocumentObjectData::DocumentObjectData(), AssemblyGui::ViewProviderBom::doubleClicked(), TechDrawGui::QGIViewPart::drawHighlight(), Assembly::AssemblyLink::ensureNoJointGroup(), Sketcher::SketchObjectSF::execute(), Part::Mirroring::execute(), TechDraw::DrawBrokenView::execute(), TechDraw::DrawViewDraft::execute(), TechDraw::DrawViewArch::execute(), TechDraw::DrawViewSection::execute(), TechDraw::DrawViewPart::execute(), PartDesignGui::TaskBooleanParameters::exitSelectionMode(), App::Document::exportGraphviz(), App::PropertyLinkBase::exportSubName(), Gui::ViewProviderGroupExtension::extensionDragObject(), Gui::ViewProviderGroupExtension::extensionDropObject(), App::OriginGroupExtension::extensionGetSubObject(), App::GroupExtension::extensionGetSubObjects(), App::GeoFeatureGroupExtension::extensionGetSubObjects(), TechDraw::DrawViewPart::extractFaces(), Attacher::AttachEngine::extractSubShape(), TechDraw::DrawViewPart::findFacesNew(), TechDraw::DrawViewPart::findFacesOld(), Gui::DocumentItem::findItem(), TechDrawGui::DrawGuiUtil::findPage(), TechDrawGui::QGSPage::findParent(), TechDrawGui::QGSPage::findQViewForDocObj(), TechDraw::DrawViewSection::findSectionPlaneIntersections(), TDHandlerDimension::finishDimensionMove(), PartDesignGui::TaskSketchBasedParameters::finishReferenceSelection(), PartDesignGui::TaskHelixParameters::finishReferenceSelection(), Gui::Dialog::DlgPropertyLink::formatObject(), TechDraw::DimensionFormatter::formatValue(), TechDraw::DrawViewPart::getDirsFromFront(), getLocatedShape(), Gui::DocumentObjectItem::getName(), Gui::Command::getObjectCmd(), PartDesignGui::getParent(), TechDraw::DimensionFormatter::getPrefixSuffixSpec(), TechDraw::DrawViewPart::getProjectionCS(), TechDraw::DrawProjGroup::getProjItem(), TechDraw::DrawProjGroup::getProjObj(), App::PropertyLinkSubList::getPyReprString(), App::PropertyXLinkSubList::getPyReprString(), Assembly::AssemblyObject::getRackPinionMarkers(), PartDesignGui::getRefStr(), Gui::ViewProviderPlane::getRole(), TechDraw::DrawViewSection::getSectionCS(), Gui::TreeWidget::getSelection(), TechDraw::ShapeExtractor::getShapeFromXLink(), TechDraw::DrawViewSpreadsheet::getSheetImage(), Gui::LinkInfo::getSnapshot(), MeshPartGui::Tessellation::getStandardParameters(), Gui::DocumentObjectItem::getSubName(), Part::Feature::getTopoShape(), Gui::DocumentItem::getTopParent(), TechDraw::DrawProjGroup::getViewIndex(), Assembly::AssemblyLink::handleJointReference(), Assembly::AssemblyObject::handleOneSideOfJoint(), TechDraw::DrawProjGroup::hasProjection(), TechDrawGui::QGSPage::hasQView(), TechDrawGui::TaskLineDecor::initUi(), Gui::DocumentObjectItem::isGroup(), Gui::SelectionSingleton::isSelected(), linkConvert(), TechDraw::DrawViewSymbol::loadQDomDocument(), TechDrawGui::TaskLinkDim::loadToTree(), PartDesignGui::TaskSketchBasedParameters::make2DLabel(), PartDesignGui::TaskFeaturePick::makeCopy(), TechDraw::DrawViewDetail::makeDetailShape(), TechDraw::DrawDimHelper::makeDistDim(), TechDraw::DrawDimHelper::makeExtentDim(), TechDraw::DrawDimHelper::makeExtentDim3d(), TechDraw::DrawViewSection::makeFaceFromWires(), TechDraw::DrawViewSection::makeLineSets(), makeRefString(), FemGui::TaskFemConstraint::makeRefText(), TechDraw::DrawViewSection::makeSectionCut(), FemGui::TaskFemConstraintTransform::makeText(), TechDraw::DrawViewSection::mapToPage(), Gui::DAG::Model::mousePressEvent(), Gui::TreeWidget::mousePressEvent(), App::Document::moveObject(), PartDesignGui::TaskSketchBasedParameters::objectNameByLabel(), PartDesignGui::TaskSketchBasedParameters::onAddSelection(), TechDraw::DrawPage::onChanged(), Gui::TreeWidget::onCreateGroup(), AssemblyGui::ViewProviderAssembly::onDelete(), TechDrawGui::MDIViewPage::onDeleteObject(), App::OriginGroupExtension::onExtendedUnsetupObject(), TechDraw::DrawViewPart::onFacesFinished(), TechDraw::DrawViewPart::onHlrFinished(), SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsItemSelectionChanged(), SketcherGui::TaskSketcherElements::onListWidgetElementsItemPressed(), SketcherGui::TaskSketcherElements::onListWidgetElementsMouseMoveOnItem(), Gui::TreeWidget::onPreSelectTimer(), TechDrawGui::TaskComplexSection::onProfileObjectsUseSelectionClicked(), TechDraw::DrawViewSection::onSectionCutFinished(), PartGui::FaceAppearances::onSelectionChanged(), PartDesignGui::TaskBooleanParameters::onSelectionChanged(), SketcherGui::TaskSketcherElements::onSelectionChanged(), SketcherGui::TaskSketcherConstraints::onSelectionChanged(), Part::FilletBase::onUpdateElementReference(), Gui::ItemViewSelection::MatchName::operator()(), Gui::ViewProviderT::operator=(), App::DocumentObjectT::operator=(), PartMeasureTypeCb(), TechDraw::DrawViewSection::prepareShape(), TechDrawGui::MDIViewPage::preSelectionChanged(), TechDrawGui::PagePrinter::printPdf(), Gui::ElementColors::Private::Private(), TechDraw::DrawProjGroup::purgeProjections(), TechDrawGui::QGVPage::QGVPage(), App::Document::readObjects(), Sketcher::SketchObject::rebuildExternalGeometry(), TechDrawGui::QGSPage::redraw1View(), TechDraw::ReferenceEntry::ReferenceEntry(), PartDesignGui::TaskShapeBinder::referenceSelected(), PartGui::ThicknessWidget::reject(), TechDrawGui::TaskSectionView::reject(), TechDrawGui::TaskGeomHatch::reject(), TechDrawGui::TaskProjGroup::reject(), TechDrawGui::TaskComplexSection::reject(), PartDesignGui::TaskDlgBooleanParameters::reject(), TechDrawGui::TaskRichAnno::removeFeature(), TechDrawGui::TaskLeaderLine::removeFeature(), App::Document::removeObject(), TechDraw::DrawProjGroup::removeProjection(), TechDrawGui::MDIViewPage::removeUnselectedTreeSelection(), TechDraw::DrawViewCollection::removeView(), TechDraw::DrawViewClip::removeView(), TechDraw::DrawPage::removeView(), App::ObjectIdentifier::resolve(), Gui::SelectionSingleton::sAddSelection(), App::Document::save(), TechDrawGui::PagePrinter::saveDXF(), saveExpandedItem(), TechDrawGui::QGSPage::saveSvg(), TechDrawGui::TaskProjGroup::scaleManuallyChanged(), Gui::SelectionObject::SelectionObject(), Gui::SelectionObserver::SelectionObserver(), TechDraw::DrawViewDimension::setAll3DMeasurement(), PartGui::DlgExtrusion::setAxisLink(), PartGui::DlgRevolution::setAxisLink(), SpreadsheetGui::WorkbenchHelper::setBackgroundColor(), Gui::QuantitySpinBox::setBoundToByName(), ExpressionCompleterModel::setDocumentObject(), App::ObjectIdentifier::setDocumentObjectName(), PartDesignGui::setEdit(), PartDesignGui::ViewProviderDressUp::setEdit(), TechDrawGui::ViewProviderViewPart::setEdit(), SurfaceGui::FillingEdgePanel::setEditedObject(), SurfaceGui::SectionsPanel::setEditedObject(), SurfaceGui::FillingPanel::setEditedObject(), SketcherGui::ViewProviderSketch::setEditViewer(), SpreadsheetGui::WorkbenchHelper::setForegroundColor(), App::LinkBaseExtension::setLink(), Gui::PropertyEditor::PropertyItem::setPropertyValue(), TechDraw::DrawViewDimension::setReferences3d(), PartDesignGui::TaskDressUpParameters::setSelection(), TechDrawGui::MDIViewPage::setTreeToSceneSelect(), TechDrawGui::TaskSectionView::setUiCommon(), TechDrawGui::TaskComplexSection::setUiCommon(), TechDrawGui::TaskComplexSection::setUiEdit(), TechDrawGui::TaskCenterLine::setUiEdit(), TechDrawGui::TaskRichAnno::setUiEdit(), TechDrawGui::TaskLeaderLine::setUiEdit(), TechDrawGui::TaskDetail::setUiFromFeat(), TechDrawGui::TaskDimRepair::setUiPrimary(), TechDrawGui::TaskComplexSection::setUiPrimary(), TechDrawGui::TaskCenterLine::setUiPrimary(), TechDrawGui::TaskCosVertex::setUiPrimary(), TechDrawGui::TaskRichAnno::setUiPrimary(), TechDrawGui::TaskLeaderLine::setUiPrimary(), PartDesignGui::TaskRevolutionParameters::setupDialog(), PartDesignGui::TaskExtrudeParameters::setupDialog(), TechDrawGui::QGIView::setViewFeature(), DrawingGui::ViewProviderDrawingPage::showDrawingView(), Gui::SelectionSingleton::slotDeletedObject(), Gui::DocumentItem::slotExpandObject(), TechDrawGui::TaskDimRepair::slotUseSelection(), MeshGui::ViewProviderMesh::splitMesh(), Gui::SelectionSingleton::sRemoveSelection(), Gui::SelectionSingleton::sSetPreselection(), PartDesignGui::TaskSketchBasedParameters::startReferenceSelection(), PartDesignGui::TaskHelixParameters::startReferenceSelection(), Gui::SelectionSingleton::sUpdateSelection(), Assembly::AssemblyLink::synchronizeJoints(), TechDrawGui::TaskComplexSection::TaskComplexSection(), TechDrawGui::TaskDetail::TaskDetail(), FemGui::TaskObjectName::TaskObjectName(), TechDrawGui::TaskSectionView::TaskSectionView(), Gui::DocumentObjectItem::testStatus(), Gui::DocumentP::throwIfNotInMap(), App::PropertyLinkBase::tryReplaceLink(), TechDrawGui::TaskProjGroup::turnProjGroupToView(), TechDrawGui::TaskProjGroup::turnViewToProjGroup(), PartDesignGui::ViewProvider::unsetEdit(), TechDraw::DrawProjGroupItem::unsetupObject(), TechDraw::DrawPage::unsetupObject(), PartDesign::SubShapeBinder::update(), PartDesignGui::ViewProviderAddSub::updateAddSubShapeIndicator(), TechDraw::DrawProjGroup::updateChildrenEnforce(), TechDraw::DrawProjGroup::updateChildrenLock(), TechDraw::DrawProjGroup::updateChildrenSource(), Gui::ViewProviderInventorObject::updateData(), TechDrawGui::TaskLinkDim::updateDims(), App::PropertyLinkBase::updateElementReferences(), TechDrawGui::TaskHatch::updateHatch(), Gui::DocumentItem::updateItemSelection(), App::ObjectIdentifier::updateLabelReference(), TechDrawGui::TaskSectionView::updateSectionView(), TechDrawGui::TaskWeldingSymbol::updateTiles(), TechDrawGui::TaskDimRepair::updateUi(), TechDrawGui::TaskProjGroup::viewToggled(), PartGui::DlgScale::writeParametersToFeature(), and PartGui::DlgExtrusion::writeParametersToFeature().
getOldLabel()
const std::string& App::DocumentObject::getOldLabel () const inline
Definition at line 548 of file DocumentObject.h.
getOutList() [1/3]
const std::vector<App::DocumentObject*>& App::DocumentObject::getOutList () const
returns a list of objects this object is pointing to by Links
Referenced by _getOutListRecursive(), _isInOutListRecursive(), App::TransactionDocumentObject::applyDel(), App::TransactionDocumentObject::applyNew(), App::Document::exportGraphviz(), Gui::ViewProviderGroupExtension::extensionCanDropObject(), Assembly::getObjFromRef(), getOutList(), App::Document::getPathsByOutList(), TechDraw::DrawPage::hasObject(), and TechDraw::DrawViewCollection::rebuildViewList().
getOutList() [2/3]
std::vector<App::DocumentObject*> App::DocumentObject::getOutList (int option) const
getOutList() [3/3]
void App::DocumentObject::getOutList (int option, std::vector< App::DocumentObject * > & res) const
getOutListOfProperty()
std::vector<App::DocumentObject*> App::DocumentObject::getOutListOfProperty (App::Property *) const
returns a list of objects linked by the property
getOutListRecursive()
std::vector<App::DocumentObject*> App::DocumentObject::getOutListRecursive () const
returns a list of objects this object is pointing to by Links and all further descended
Referenced by StdCmdToggleTransparency::activated().
getParents()
std::vector<std::pair<App::DocumentObject*, std::string> > App::DocumentObject::getParents (int depth = 0) const
Obtain top parents and subnames of this object using its InList.
Referenced by PartDesignGui::makeBodyActive(), and PartDesign::SubShapeBinder::update().
getPathsByOutList()
std::vector<std::list<App::DocumentObject*> > App::DocumentObject::getPathsByOutList (App::DocumentObject * to) const
get all possible paths from this to another object following the OutList
getPyObject()
PyObject* App::DocumentObject::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Reimplemented in TechDraw::DrawBrokenView, TechDraw::DrawSVGTemplate, TechDraw::DrawTile, TechDraw::DrawTemplate, Sketcher::SketchObject, Spreadsheet::Sheet, App::Part, TechDraw::DrawViewDimension, Part::BodyBase, TechDraw::DrawViewPart, PartDesign::Body, TechDraw::DrawProjGroup, TechDraw::DrawPage, TechDraw::DrawViewClip, App::GeoFeature, TechDraw::DrawView, Fem::FemResultObject, TechDraw::DrawProjGroupItem, Measure::MeasureBase, Path::FeatureCompound, Fem::FemSolverObject, PartDesign::FeaturePrimitive, Path::FeatureArea, Fem::FemMeshObject, TechDraw::DrawTileWeld, TechDraw::DrawViewDimExtent, Path::Feature, Fem::FemSetElementNodesObject, Fem::FemSetNodesObject, TechDraw::DrawRichAnno, Fem::FemSetObject, Robot::TrajectoryObject, App::InventorObject, Robot::RobotObject, App::VRMLObject, Fem::FemSetElementsObject, Fem::FemSetFacesObject, Fem::FemSetGeometryObject, App::DocumentObjectGroup, Fem::FemPostPipeline, TechDraw::DrawViewSymbol, Fem::FemPostObject, Mesh::Feature, Part::Primitive, Assembly::BomGroup, Assembly::JointGroup, Assembly::SimulationGroup, Assembly::ViewGroup, PartDesign::Feature, Assembly::AssemblyObject, TechDraw::DrawLeaderLine, TechDraw::DrawWeldSymbol, Part::Feature, TechDraw::DrawGeomHatch, Assembly::AssemblyLink, Assembly::BomObject, TechDraw::DrawParametricTemplate, and TechDraw::DrawHatch.
Referenced by Gui::SelectionGatePython::allow(), App::FeaturePythonImp::allowDuplicateLabel(), Gui::ViewProviderFeaturePythonImp::canDelete(), Gui::ViewProviderFeaturePythonImp::canDragAndDropObject(), Gui::ViewProviderFeaturePythonImp::canDragObject(), Gui::ViewProviderFeaturePythonImp::canDropObject(), Gui::ViewProviderFeaturePythonImp::canDropObjectEx(), App::FeaturePythonImp::canLinkProperties(), App::FeaturePythonImp::canLoadPartial(), Gui::ViewProviderFeaturePythonImp::dragObject(), Gui::ViewProviderFeaturePythonImp::dropObject(), Gui::ViewProviderFeaturePythonImp::dropObjectEx(), App::FeaturePythonImp::execute(), App::LinkBaseExtension::extensionExecute(), Gui::MDIViewPy::getActiveObject(), Gui::View3DInventorPy::getattr(), App::FeaturePythonImp::getLinkedObject(), Sandbox::DocumentObjectProtectorPy::getObject(), App::PropertyLink::getPyObject(), App::PropertyLinkSub::getPyObject(), App::PropertyXLink::getPyObject(), App::PropertyXLinkSub::getPyObject(), App::PropertyXLinkSubList::getPyObject(), App::PropertyXLinkList::getPyObject(), App::RangeExpression::getRange(), App::FeaturePythonImp::getSubObject(), App::FeaturePythonImp::getSubObjects(), App::FeaturePythonImp::getViewProviderName(), App::FeaturePythonImp::hasChildElement(), App::FeaturePythonImp::isElementVisible(), App::FeaturePythonImp::mustExecute(), App::FeaturePythonImp::onBeforeChange(), App::FeaturePythonImp::onBeforeChangeLabel(), App::FeaturePythonImp::onChanged(), App::FeaturePythonImp::onDocumentRestored(), App::FeaturePythonImp::redirectSubName(), Gui::ViewProviderFeaturePythonImp::replaceObject(), App::FeaturePythonImp::setElementVisible(), App::FeaturePythonImp::unsetupObject(), and Gui::ViewProviderFeaturePythonImp::updateData().
getStatus()
unsigned long App::DocumentObject::getStatus () const inline
return the status bits
Definition at line 222 of file DocumentObject.h.
getStatusString()
const char* App::DocumentObject::getStatusString () const
get the status Message
Referenced by PartGui::OffsetWidget::accept(), PartGui::ThicknessWidget::accept(), PartGui::LoftWidget::accept(), PartGui::SweepWidget::accept(), FemGui::TaskDlgMeshShapeNetgen::accept(), FemGui::TaskDlgFemConstraintInitialTemperature::accept(), SurfaceGui::FillingEdgePanel::accept(), SurfaceGui::GeomFillSurface::accept(), SurfaceGui::SectionsPanel::accept(), SurfaceGui::FillingPanel::accept(), FemGui::TaskDlgFemConstraint::accept(), SurfaceGui::GeomFillSurface::changeFillType(), and Gui::DocumentObjectItem::displayStatusInfo().
getSubObject()
virtual DocumentObject* App::DocumentObject::getSubObject (const char * subname, PyObject ** pyObj = nullptr, Base::Matrix4D * mat = nullptr, bool transform = true, int depth = 0) const virtual
Get the sub element/object by name
Parameters
subname a string which is dot separated name to refer to a sub element or object. An empty string can be used to refer to the object itself
pyObj if non zero, returns the python object corresponding to this sub object. The actual type of this python object is implementation dependent. For example, The current implementation of Part::Feature will return the TopoShapePy, event if there is no sub-element reference, in which case it returns the whole shape.
mat If non zero, it is used as the current transformation matrix on input. And output as the accumulated transformation up until and include the transformation applied by the final object reference in subname. For Part::Feature, the transformation is applied to the TopoShape inside pyObj before returning.
transform if false, then it will not apply the object's own transformation to mat, which lets you override the object's placement (and possibly scale).
depth depth limitation as hint for cyclic link detection
Returns
The last document object referred in subname. If subname is empty, then it shall return itself. If subname is invalid, then it shall return zero.
Reimplemented in PartDesign::SubShapeBinder, Sketcher::SketchObject, PartDesign::Body, PartDesign::Feature, PartDesign::CoordinateSystem, Part::Feature, and Part::Datum.
Referenced by _getTopoShape(), Mesh::Exporter::addObject(), adjustLinkSubs(), Import::ExportOCAF2::canFallback(), expandSubObjectNames(), App::PropertyLinkBase::exportSubName(), App::OriginGroupExtension::extensionGetSubObject(), App::GroupExtension::extensionGetSubObject(), App::GeoFeatureGroupExtension::extensionGetSubObject(), App::LinkBaseExtension::extensionGetSubObject(), Gui::DocumentItem::findItem(), Gui::Dialog::DlgPropertyLink::formatObject(), Gui::DocumentObjectItem::getRelativeParent(), Part::Feature::getShapeOwner(), Part::Feature::getSubObject(), PartDesign::SubShapeBinder::getSubObject(), Part::Feature::getTopoShape(), App::GeoFeature::resolveElement(), App::ObjectIdentifier::resolveProperty(), App::PropertyLinkBase::restoreLabelReference(), Gui::Document::slotChangedObject(), Gui::DocumentP::tryGetSubObject(), App::PropertyLinkBase::tryImportSubName(), App::PropertyLinkBase::tryReplaceLink(), Gui::TaskMeasure::update(), and Gui::LinkView::updateLink().
getSubObjectList()
std::vector<DocumentObject*> App::DocumentObject::getSubObjectList (const char * subname, std::vector< int > * subsizes = nullptr, bool flatten = false) const
Return a list of objects referenced by a given subname including this object
Parameters
subname the sub name path
subsizes optional sub name sizes for each returned object, that is, ret[i] = getSubObject(std::string(subname, subsizes[i]).c_str());
flatten whether to flatten the object hierarchies that belong to the same geo feature group, e.g. (Part.Fusion.Box -> Part.Box)
Returns
Return a list of objects along the path.
Referenced by Gui::DocumentP::findSubObjectList().
getSubObjects()
virtual std::vector<std::string> App::DocumentObject::getSubObjects (int reason = 0) const virtual
Return name reference of all sub-objects
Parameters
reason indicate reason of obtaining the sub objects
The default implementation returns all object references in PropertyLink, and PropertyLinkList, if any
Returns
Return a vector of subname references for all sub-objects. In most cases, the name returned will be the object name plus an ending '.', which can be passed directly to getSubObject() to retrieve the name. The reason to return the name reference instead of the sub object itself is because there may be no real sub object, or the sub object need special transformation. For example, sub objects of an array type of object.
Reimplemented in PartDesign::Body.
Referenced by _getTopoShape(), Import::ExportOCAF2::canFallback(), expandSubObjectNames(), App::LinkBaseExtension::extensionGetSubObjects(), and PartDesign::Body::getSubObjects().
getViewProviderName()
virtual const char* App::DocumentObject::getViewProviderName () const inline virtual
returns the type name of the ViewProvider
Reimplemented in TechDraw::DrawSVGTemplate, TechDraw::DrawTile, TechDraw::DrawTemplate, Drawing::FeatureViewPart, Drawing::FeatureClip, Drawing::FeatureViewSpreadsheet, Drawing::FeatureViewAnnotation, Sandbox::SandboxObject, Drawing::FeatureViewSymbol, Drawing::FeaturePage, Drawing::FeatureView, Drawing::PageGroup, Path::FeatureShape, Part::Datum, App::LinkGroup, App::LinkElement, App::Link, Part::Ellipse, Part::Wedge, Part::Spiral, Fem::FemPostWarpVectorFilter, Part::Helix, Fem::FemPostScalarClipFilter, Part::Torus, Fem::FemPostCutFilter, Part::Cone, Inspection::Group, Inspection::Feature, Part::RegularPolygon, Fem::FemPostContoursFilter, Part::Prism, Part::FeatureExt, Fem::FemPostClipFilter, Part::Cylinder, Part::Reverse, Fem::FemPostSphereFunction, Part::Refine, Part::Ellipsoid, Fem::FemPostDataAtPointFilter, Fem::FemPostPlaneFunction, Fem::Constraint, Part::Thickness, Part::Sphere, Fem::FemPostDataAlongLineFilter, Fem::FemPostCylinderFunction, App::FeatureTestException, App::FeatureTest, Part::Plane, Part::Sweep, Measure::MeasureDistanceDetached, Fem::FemPostBoxFunction, App::Part, Part::Line, Sketcher::SketchObject, App::LocalCoordinateSystem, TechDraw::DrawViewDimension, TechDraw::DrawViewPart, TechDraw::DrawViewSection, Fem::ConstraintDisplacement, Fem::FemAnalysis, TechDraw::DrawPage, TechDraw::DrawProjGroup, Part::Scale, TechDraw::DrawViewAnnotation, TechDraw::DrawViewClip, TechDraw::DrawViewCollection, Part::Loft, PartDesign::SubShapeBinder, TechDraw::DrawViewArch, Path::FeatureAreaView, Fem::ConstraintFluidBoundary, Fem::ConstraintContact, Fem::FemPostFunctionProvider, Part::Extrusion, PartDesign::Groove, PartDesign::Revolution, TechDraw::DrawViewDraft, Fem::ConstraintBearing, Fem::ConstraintRigidBody, TechDraw::DrawBrokenView, TechDraw::DrawView, TechDraw::DrawViewSpreadsheet, Fem::ConstraintPulley, Part::Revolution, Surface::GeomFillSurface, App::Point, Fem::ConstraintHeatflux, Fem::ConstraintTemperature, Spreadsheet::Sheet, TechDraw::DrawViewImage, Part::ProjectOnSurface, PartDesign::Boolean, PartDesign::ShapeBinder, Fem::ConstraintInitialTemperature, Measure::MeasureAngle, Part::Offset2D, Surface::FeatureBlendCurve, TechDraw::DrawProjGroupItem, Measure::MeasurePosition, Part::LocalCoordinateSystem, PartDesign::Draft, PartDesign::Pad, Surface::Extend, Image::ImagePlane, Fem::ConstraintGear, Fem::ConstraintTransform, Measure::MeasureArea, Mesh::Curvature, Mesh::Transform, Part::Offset, Measure::MeasureRadius, Part::Vertex, PartDesign::Chamfer, PartDesign::Pipe, Robot::TrajectoryDressUpObject, Fem::FemPostPipeline, Fem::FemResultObject, Mesh::TransformDemolding, PartDesign::Pocket, PartDesign::Thickness, Points::Structured, TechDraw::DrawTileWeld, Fem::ConstraintForce, Measure::MeasureLength, Part::CustomFeature, Part::Mirroring, Part::Circle, PartDesign::FeaturePrimitive, Robot::Edge2TracObject, TechDraw::DrawRichAnno, Fem::FemMeshShapeNetgenObject, Fem::FemPostFunction, Part::Part2DObject, Part::RuledSurface, PartDesign::Helix, Path::FeatureArea, Fem::ConstraintSpring, Mesh::Export, Part::Box, PartDesign::Plane, PartDesign::Fillet, Fem::ConstraintPressure, Part::Compound, Part::ImportStep, PartDesign::Line, PartDesign::Scaled, App::Annotation, App::AnnotationLabel, App::Origin, App::TextDocument, Assembly::BomGroup, Assembly::JointGroup, Assembly::SimulationGroup, Assembly::ViewGroup, Fem::FemSolverObject, Part::Face, PartDesign::Loft, App::Line, Path::FeatureCompound, Fem::ConstraintFixed, Fem::ConstraintPlaneRotation, Fem::FemMeshObject, Part::FeatureGeometrySet, Part::CurveNet, Part::ImportBrep, Part::ImportIges, PartDesign::Feature, PartDesign::Mirrored, PartDesign::MultiTransform, App::DocumentObjectGroup, App::MaterialObject, Path::Feature, Fem::FemSetElementNodesObject, Fem::FemSetNodesObject, Part::MultiCommon, Part::MultiFuse, Surface::Sections, App::DocumentObjectFileIncluded, App::Placement, Assembly::AssemblyObject, Robot::TrajectoryCompound, Robot::TrajectoryObject, App::InventorObject, Fem::FemMeshShapeBaseObject, Part::DatumPoint, Part::Chamfer, Part::Fillet, PartDesign::Point, PartDesign::FeatureBase, Robot::RobotObject, App::VRMLObject, Fem::FemSetElementsObject, Fem::FemSetFacesObject, Fem::FemSetGeometryObject, PartDesign::Hole, App::VarSet, Fem::FemMeshShapeObject, Measure::MeasureDistance, PartDesign::CoordinateSystem, TechDraw::DrawViewSymbol, Part::DatumPlane, Part::Spline, TechDraw::DrawLeaderLine, Mesh::Feature, PartDesign::PolarPattern, Part::FeatureReference, PartDesign::LinearPattern, TechDraw::DrawWeldSymbol, App::Plane, TechDraw::DrawViewBalloon, Assembly::AssemblyLink, Surface::Filling, Part::DatumLine, TechDraw::DrawViewMulti, Assembly::BomObject, TechDraw::DrawViewDetail, Part::Feature, Points::Feature, TechDraw::DrawGeomHatch, PartDesign::FeatureExtrude, TechDraw::DrawParametricTemplate, PartDesign::Body, TechDraw::LandmarkDimension, Part::Boolean, and TechDraw::DrawHatch.
Definition at line 123 of file DocumentObject.h.
Referenced by Gui::FreeCADGui_subgraphFromObject(), and Gui::Document::slotNewObject().
getViewProviderNameOverride()
virtual const char* App::DocumentObject::getViewProviderNameOverride () const inline virtual
This function is introduced to allow Python feature override its view provider. The default implementation just returns getViewProviderName().
The core will only accept the overridden view provider if it returns true when calling Gui::ViewProviderDocumentObject::allowOverride(obj). If not, the view provider will be reverted to the one returned from getViewProviderName().
Definition at line 136 of file DocumentObject.h.
Referenced by App::Document::_addObject(), App::Document::addObject(), and App::Document::addObjects().
getViewProviderNameStored()
const char* App::DocumentObject::getViewProviderNameStored () const inline
Definition at line 553 of file DocumentObject.h.
Referenced by Gui::Document::slotNewObject().
hasChildElement()
virtual bool App::DocumentObject::hasChildElement () const virtual
return true to activate tree view group object handling and element visibility
Referenced by App::LinkBaseExtension::extensionHasChildElement(), and Gui::DocumentObjectItem::isGroup().
hasHiddenMarker()
static const char* App::DocumentObject::hasHiddenMarker (const char * subname) static
Check if the subname reference ends with hidden marker.
Referenced by Gui::ViewProvider::hasHiddenMarker(), and App::GeoFeature::resolveElement().
hiddenMarker()
static const std::string& App::DocumentObject::hiddenMarker () static
Special marker to mark the object as hidden
It is used by Gui::ViewProvider::getElementColors(), but exposed here for convenience
Referenced by Gui::ViewProvider::hiddenMarker().
isAttachedToDocument()
bool App::DocumentObject::isAttachedToDocument () const override virtual
Reimplemented from App::TransactionalObject.
Referenced by Gui::Command::_copyVisual(), App::PropertyXLinkSubList::addValue(), App::PropertyLinkSub::adjustLink(), App::PropertyXLink::adjustLink(), App::PropertyXLinkSubList::adjustLink(), App::PropertyLinkSub::afterRestore(), App::PropertyXLink::afterRestore(), Gui::ViewProviderDocumentObject::attach(), TechDrawGui::ViewProviderPage::attach(), App::PropertyXLinkContainer::breakLink(), Import::ExportOCAF2::canFallback(), Gui::TreeWidget::checkTopParent(), App::PropertyXLinkContainer::clearDeps(), App::PropertyLinkSub::CopyOnImportExternal(), App::PropertyXLink::CopyOnImportExternal(), App::PropertyLinkSub::CopyOnLabelChange(), App::PropertyXLink::CopyOnLabelChange(), App::PropertyXLink::copyTo(), countExpandedItem(), Gui::DocumentItem::createNewItem(), App::LinkBaseExtension::detachElement(), App::Document::exportGraphviz(), App::PropertyLinkBase::exportSubName(), App::OriginGroupExtension::extensionGetSubObject(), App::GroupExtension::extensionGetSubObjects(), App::GeoFeatureGroupExtension::extensionGetSubObjects(), App::GroupExtension::extensionOnChanged(), Gui::DocumentItem::findRootIndex(), TechDrawGui::QGSPage::fixOrphans(), Gui::Dialog::DlgPropertyLink::formatObject(), Gui::ViewProviderDocumentObject::getActiveView(), App::PropertyXLink::getDocumentInList(), App::PropertyXLink::getDocumentOutList(), Gui::ViewProviderDocumentObject::getLinkedViewProvider(), Gui::ViewProviderLink::getLinkExtension(), App::PropertyLink::getLinks(), App::PropertyLinkSub::getLinks(), App::PropertyLinkSubList::getLinks(), App::PropertyXLink::getLinks(), App::PropertyXLinkSubList::getLinks(), Gui::Command::getObjectCmd(), App::PropertyXLinkSubList::getPyObject(), App::PropertyXLinkList::getPyObject(), App::PropertyXLinkSubList::getPyReprString(), Gui::TreeWidget::getSelection(), Gui::DocumentObjectItem::getSubName(), PartDesign::SubShapeBinder::getSubObject(), Gui::LinkInfo::getView(), App::PropertyExpressionEngine::hasSetValue(), Spreadsheet::PropertySheet::hasSetValue(), Gui::LinkInfo::isLinked(), Gui::TreeWidget::isObjectShowable(), Gui::SelectionSingleton::isSelected(), linkConvert(), App::PropertyLinkSub::onContainerRestored(), App::PropertyXLink::onContainerRestored(), Gui::TreeWidget::onStartEditing(), App::DocumentObjectT::operator=(), App::Document::recomputeFeature(), TechDraw::DrawPage::removeView(), Gui::ViewProviderDocumentObject::replaceObject(), Gui::ViewProviderFeaturePythonImp::replaceObject(), App::ObjectIdentifier::resolveAmbiguity(), App::GeoFeature::resolveElement(), Gui::SelectionSingleton::sAddSelection(), App::PropertyLinkSub::Save(), App::PropertyLinkSubList::Save(), saveExpandedItem(), Gui::TreeWidget::selectAllLinks(), App::PropertyLinkList::set1Value(), Gui::ExpressionCompleter::setDocumentObject(), App::ObjectIdentifier::setDocumentObjectName(), PartDesignGui::setEdit(), App::LinkBaseExtension::setLink(), Gui::SelectionSingleton::setVisible(), Gui::SelectionSingleton::slotDeletedObject(), Gui::DocumentItem::slotNewObject(), Gui::DocumentItem::slotScrollToObject(), Gui::Document::slotSkipRecompute(), Gui::SelectionSingleton::sRemoveSelection(), Gui::SelectionSingleton::sSetPreselection(), Gui::SelectionSingleton::sUpdateSelection(), App::PropertyLinkBase::tryImport(), App::PropertyLinkBase::tryImportSubName(), PartDesign::SubShapeBinder::update(), App::PropertyXLinkContainer::updateDeps(), Gui::DocumentItem::updateItemSelection(), App::PropertyLinkBase::updateLabelReference(), App::PropertyLinkBase::updateLabelReferences(), updateLinkReference(), and updateLinkSubs().
isElementVisible()
virtual int App::DocumentObject::isElementVisible (const char * element) const virtual
Get sub-element visibility
Returns
-1 if element visibility is not supported or element not found, 0 if element is invisible, or else 1
Referenced by _getTopoShape(), expandSubObjectNames(), App::LinkBaseExtension::extensionIsElementVisible(), and Gui::DocumentObjectItem::testStatus().
isError()
bool App::DocumentObject::isError () const inline
set this feature to error
Definition at line 184 of file DocumentObject.h.
References App::Error.
Referenced by PartDesignGui::TaskDlgThicknessParameters::accept(), Gui::DocumentObjectItem::displayStatusInfo(), Mesh::Curvature::execute(), Mesh::SegmentByMesh::execute(), Mesh::Export::execute(), PartDesignGui::TaskDressUpParameters::hideOnError(), App::Document::readObjects(), PartDesignGui::ViewProviderTransformed::recomputeFeature(), and Gui::DocumentObjectItem::testStatus().
isExporting()
int App::DocumentObject::isExporting () const
Referenced by App::PropertyLinkBase::exportSubName(), and App::PropertyXLink::Save().
isFreezed()
bool App::DocumentObject::isFreezed () const inline
returns true if this objects is currently freezed
Definition at line 217 of file DocumentObject.h.
References App::Freeze.
Referenced by SketcherGui::ViewProviderSketch::setEdit(), and Gui::DocumentObjectItem::testStatus().
isInInList()
bool App::DocumentObject::isInInList (DocumentObject * objToTest) const
test if this object is directly (non recursive) in the InList
isInInListRecursive()
bool App::DocumentObject::isInInListRecursive (DocumentObject * objToTest) const
test if this object is in the InList and recursive further down
isInOutList()
bool App::DocumentObject::isInOutList (DocumentObject * objToTest) const
test if this object is directly (non recursive) in the OutList
isInOutListRecursive()
bool App::DocumentObject::isInOutListRecursive (DocumentObject * objToTest) const
test if the given object is in the OutList and recursive further down
isLink()
virtual bool App::DocumentObject::isLink () const inline virtual
Reimplemented in App::LinkElement, and App::Link.
Definition at line 500 of file DocumentObject.h.
Referenced by App::GeoFeature::getGlobalPlacement().
isLinkGroup()
virtual bool App::DocumentObject::isLinkGroup () const inline virtual
Reimplemented in App::Link.
Definition at line 506 of file DocumentObject.h.
isRecomputing()
bool App::DocumentObject::isRecomputing () const inline
returns true if this objects is currently recomputing
Definition at line 198 of file DocumentObject.h.
References App::Recompute.
Referenced by Part::Feature::onChanged(), Fem::Constraint::onChanged(), and PartDesign::MultiTransform::positionBySupport().
isRemoving()
bool App::DocumentObject::isRemoving () const inline
returns true if this objects is currently removed from the document
Definition at line 208 of file DocumentObject.h.
References App::Remove.
Referenced by TechDrawGui::MDIViewPage::addSceneItemToTreeSel(), App::LinkBaseExtension::detachElement(), TechDraw::DrawViewPart::getGeomHatches(), TechDraw::DrawViewPart::getHatches(), App::OriginGroupExtension::onExtendedUnsetupObject(), MeasureGui::ViewProviderMeasureBase::onSubjectVisibilityChanged(), TechDrawGui::MDIViewPage::removeUnselectedTreeSelection(), and TechDrawGui::MDIViewPage::setTreeToSceneSelect().
isRestoring()
bool App::DocumentObject::isRestoring () const inline
returns true if this objects is currently restoring from file
Definition at line 203 of file DocumentObject.h.
References App::Restore.
Referenced by TechDrawGui::QGISVGTemplate::createClickHandles(), TechDrawGui::QGIViewBalloon::drawBalloon(), PartDesign::ShapeBinder::execute(), App::PropertyExpressionEngine::hasSetValue(), Spreadsheet::PropertySheet::hasSetValue(), TechDrawGui::ViewProviderDrawingView::hide(), TechDrawGui::ViewProviderViewClip::hide(), DrawingGui::ViewProviderDrawingView::hide(), DrawingGui::ViewProviderDrawingClip::hide(), TechDraw::DrawViewMulti::mustExecute(), TechDraw::DrawViewBalloon::mustExecute(), TechDraw::DrawViewDetail::mustExecute(), TechDraw::DrawViewSymbol::mustExecute(), TechDraw::DrawLeaderLine::mustExecute(), TechDraw::DrawRichAnno::mustExecute(), TechDraw::DrawView::mustExecute(), TechDraw::DrawViewSpreadsheet::mustExecute(), TechDraw::DrawViewClip::mustExecute(), TechDraw::DrawBrokenView::mustExecute(), TechDraw::DrawProjGroup::mustExecute(), TechDraw::DrawPage::mustExecute(), TechDraw::DrawViewDraft::mustExecute(), TechDraw::DrawViewArch::mustExecute(), TechDraw::DrawViewAnnotation::mustExecute(), TechDraw::DrawViewPart::mustExecute(), TechDraw::DrawViewSection::mustExecute(), TechDraw::DrawView::onBeforeChange(), TechDrawGui::ViewProviderTemplate::onChanged(), TechDraw::LandmarkDimension::onChanged(), TechDraw::DrawViewMulti::onChanged(), TechDraw::DrawGeomHatch::onChanged(), TechDraw::DrawViewDetail::onChanged(), TechDrawGui::ViewProviderDrawingView::onChanged(), TechDraw::DrawHatch::onChanged(), TechDraw::DrawViewBalloon::onChanged(), Part::Circle::onChanged(), TechDrawGui::ViewProviderImage::onChanged(), Part::Primitive::onChanged(), TechDraw::DrawSVGTemplate::onChanged(), Part::Vertex::onChanged(), TechDraw::DrawViewSymbol::onChanged(), Surface::GeomFillSurface::onChanged(), Part::Box::onChanged(), Part::Revolution::onChanged(), Part::Mirroring::onChanged(), TechDraw::DrawTile::onChanged(), TechDraw::DrawRichAnno::onChanged(), TechDraw::DrawTileWeld::onChanged(), Assembly::AssemblyLink::onChanged(), Surface::FeatureBlendCurve::onChanged(), TechDraw::DrawViewImage::onChanged(), PartDesign::Hole::onChanged(), TechDraw::DrawViewSection::onChanged(), TechDraw::DrawViewAnnotation::onChanged(), Part::Line::onChanged(), PartDesign::Body::onChanged(), PartDesign::SubShapeBinder::onChanged(), TechDraw::DrawView::onChanged(), TechDraw::DrawProjGroup::onChanged(), TechDraw::DrawPage::onChanged(), Part::Helix::onChanged(), Part::Spiral::onChanged(), Part::Wedge::onChanged(), Part::Ellipse::onChanged(), TechDraw::DrawSVGTemplate::processTemplate(), Spreadsheet::Cell::setContent(), TechDrawGui::ViewProviderDrawingView::show(), TechDrawGui::ViewProviderViewClip::show(), DrawingGui::ViewProviderDrawingView::show(), DrawingGui::ViewProviderDrawingClip::show(), Gui::ViewProviderLink::updateData(), and TechDrawGui::QGIWeldSymbol::updateView().
isTouched()
bool App::DocumentObject::isTouched () const
test if this document object is touched
Referenced by App::OriginGroupExtension::extensionMustExecute(), TechDraw::DrawLeaderLine::mustExecute(), Mesh::Curvature::mustExecute(), Part::Prism::mustExecute(), Part::RegularPolygon::mustExecute(), prepareProfileBased(), Assembly::AssemblyLink::synchronizeJoints(), Gui::DocumentObjectItem::testStatus(), TechDrawGui::QGSPage::updateTemplate(), and TechDraw::DrawProjGroup::waitingForChildren().
isValid()
bool App::DocumentObject::isValid () const inline
Definition at line 188 of file DocumentObject.h.
References App::Error.
Referenced by PartGui::OffsetWidget::accept(), PartGui::ThicknessWidget::accept(), PartGui::LoftWidget::accept(), PartGui::SweepWidget::accept(), FemGui::TaskDlgFemConstraintInitialTemperature::accept(), SurfaceGui::FillingEdgePanel::accept(), SurfaceGui::GeomFillSurface::accept(), SurfaceGui::SectionsPanel::accept(), SurfaceGui::FillingPanel::accept(), FemGui::TaskDlgFemConstraint::accept(), PartDesignGui::TaskDlgFeatureParameters::accept(), SurfaceGui::GeomFillSurface::changeFillType(), Measure::MeasureDistance::execute(), Measure::MeasureAngle::execute(), Spreadsheet::Sheet::getCharsFromPrefs(), Measure::MeasureDistance::getShape(), Measure::MeasureAngle::location1(), Measure::MeasureAngle::location2(), App::Document::recomputeFeature(), Gui::DocumentItem::slotRecomputed(), Gui::DocumentItem::slotRecomputedObject(), PartDesign::SubShapeBinder::update(), Measure::MeasureAngle::vector1(), and Measure::MeasureAngle::vector2().
mustExecute()
virtual short App::DocumentObject::mustExecute () const virtual
mustExecute We call this method to check if the object was modified to be invoked. If the object label or an argument is modified. If we must recompute the object - to call the method execute(). 0: no recomputation is needed 1: recomputation needed
Remarks
If an object is marked as 'touched' then this does not necessarily mean that it will be recomputed. It only means that all objects that link it (i.e. its InList) will be recomputed.
Reimplemented in Sandbox::SandboxObject, Part::Ellipse, Part::Wedge, PartDesign::Wedge, Part::Spiral, Fem::FemPostWarpVectorFilter, Part::Helix, PartDesign::Prism, Fem::FemPostScalarClipFilter, Part::Torus, Fem::FemPostCutFilter, PartDesign::Torus, Part::Cone, Part::RegularPolygon, Inspection::Feature, Fem::FemPostContoursFilter, PartDesign::Ellipsoid, Part::Prism, Fem::FemPostClipFilter, PartDesign::Cone, Part::FilletBase, Part::Cylinder, Spreadsheet::Sheet, App::LocalCoordinateSystem, Fem::FemPostDataAtPointFilter, Mesh::Cube, Part::Ellipsoid, PartDesign::Sphere, Mesh::Torus, Part::Thickness, Part::Sphere, Fem::FemPostDataAlongLineFilter, App::FeatureTest, Mesh::Cone, Part::Plane, PartDesign::Cylinder, Part::Sweep, PartDesign::Transformed, Mesh::Cylinder, TechDraw::DrawViewSection, Part::Line, Sketcher::SketchObject, TechDraw::DrawViewPart, TechDraw::DrawViewAnnotation, TechDraw::DrawViewArch, TechDraw::DrawViewDimension, TechDraw::DrawViewDraft, Part::Scale, PartDesign::ShapeBinder, Part::Loft, TechDraw::DrawPage, PartDesign::Box, Fem::FemResultObject, Part::Extrusion, PartDesign::Groove, PartDesign::Revolution, TechDraw::DrawProjGroup, Mesh::Export, TechDraw::DrawBrokenView, Fem::FemSolverObject, Mesh::FixDefects, Mesh::SegmentByMesh, Part::Offset2D, PartDesign::Boolean, Surface::FeatureBlendCurve, TechDraw::DrawViewClip, Path::FeatureArea, Fem::FemMeshObject, Mesh::Ellipsoid, Part::Revolution, Surface::GeomFillSurface, TechDraw::DrawViewSpreadsheet, Path::Feature, Fem::FemSetElementNodesObject, Fem::FemSetNodesObject, Mesh::SetOperations, Part::Offset, PartDesign::Draft, Surface::Extend, Fem::FemSetObject, Mesh::Curvature, Robot::TrajectoryObject, App::InventorObject, Mesh::Import, PartDesign::FeatureAddSub, PartDesign::Chamfer, PartDesign::Pipe, Robot::RobotObject, App::VRMLObject, Fem::FemSetElementsObject, Fem::FemSetFacesObject, Fem::FemSetGeometryObject, Mesh::Sphere, Part::Vertex, PartDesign::Thickness, Surface::Sewing, TechDraw::DrawView, TechDraw::DrawViewCollection, Part::Mirroring, Part::RuledSurface, Fem::FemPostPipeline, Part::Circle, Part::Polygon, PartDesign::Helix, TechDraw::DrawRichAnno, TechDraw::DrawTile, Part::CustomFeature, Part::Box, PartDesign::Fillet, Sketcher::SketchObjectSF, Part::ImportStep, PartDesign::DressUp, PartDesign::Hole, Part::Face, Part::Section, PartDesign::Loft, PartDesign::Scaled, Part::Compound, Part::CurveNet, Part::ImportBrep, Part::ImportIges, Part::Primitive, Surface::Cut, PartDesign::Mirrored, PartDesign::MultiTransform, Part::MultiCommon, Part::MultiFuse, PartDesign::FeatureBase, PartDesign::PolarPattern, TechDraw::DrawLeaderLine, Part::FeatureReference, PartDesign::LinearPattern, TechDraw::DrawViewSymbol, TechDraw::DrawWeldSymbol, Surface::Filling, TechDraw::DrawViewDetail, Part::Feature, PartDesign::Feature, PartDesign::ProfileBased, Points::Feature, TechDraw::DrawViewBalloon, TechDraw::DrawViewMulti, PartDesign::FeatureExtrude, TechDraw::DrawParametricTemplate, PartDesign::Body, TechDraw::LandmarkDimension, and Part::Boolean.
Referenced by Gui::DocumentObjectItem::displayStatusInfo(), TechDraw::DrawParametricTemplate::mustExecute(), Fem::FemPostPipeline::mustExecute(), TechDraw::DrawView::mustExecute(), Path::Feature::mustExecute(), Mesh::Ellipsoid::mustExecute(), TechDraw::DrawPage::mustExecute(), Mesh::Cylinder::mustExecute(), App::FeatureTest::mustExecute(), Mesh::Cone::mustExecute(), Fem::FemPostDataAlongLineFilter::mustExecute(), Mesh::Torus::mustExecute(), Mesh::Cube::mustExecute(), Fem::FemPostDataAtPointFilter::mustExecute(), App::LocalCoordinateSystem::mustExecute(), Fem::FemPostClipFilter::mustExecute(), Fem::FemPostContoursFilter::mustExecute(), Fem::FemPostCutFilter::mustExecute(), Fem::FemPostScalarClipFilter::mustExecute(), Fem::FemPostWarpVectorFilter::mustExecute(), and Gui::DocumentObjectItem::testStatus().
mustRecompute()
bool App::DocumentObject::mustRecompute () const
Test if this document object must be recomputed.
onBeforeChange()
void App::DocumentObject::onBeforeChange (const Property * prop) override protected virtual
get called before the value is changed
Reimplemented from App::PropertyContainer.
Reimplemented in Part::Feature, TechDraw::DrawPage, TechDraw::DrawView, Part::BodyBase, and Drawing::FeaturePage.
Referenced by Drawing::FeaturePage::onBeforeChange(), TechDraw::DrawView::onBeforeChange(), and TechDraw::DrawPage::onBeforeChange().
onBeforeChangeLabel()
virtual void App::DocumentObject::onBeforeChangeLabel (std::string & newLabel) inline virtual
Definition at line 523 of file DocumentObject.h.
onChanged()
void App::DocumentObject::onChanged (const Property * prop) override protected virtual
get called by the container when a property was changed
Reimplemented from App::PropertyContainer.
Reimplemented in App::GeoFeature, App::TextDocument, Part::Wedge, Part::Spiral, Fem::FemPostWarpVectorFilter, Part::Helix, Fem::FemPostScalarClipFilter, Fem::FemPostCutFilter, Fem::FemPostContoursFilter, Spreadsheet::Sheet, Fem::FemPostClipFilter, TechDraw::DrawViewPart, TechDraw::DrawViewDimension, Fem::FemPostSphereFunction, Fem::FemPostDataAtPointFilter, PartDesign::ProfileBased, Fem::Constraint, Fem::FemPostPlaneFunction, Part::Feature, Fem::FemPostDataAlongLineFilter, Fem::FemPostCylinderFunction, TechDraw::DrawPage, TechDraw::DrawProjGroup, Part::Extrusion, TechDraw::DrawView, PartDesign::SubShapeBinder, Part::Sweep, PartDesign::Body, Fem::FemPostBoxFunction, Part::BodyBase, Fem::ConstraintDisplacement, Robot::RobotObject, TechDraw::DrawViewClip, TechDraw::DrawProjGroupItem, TechDraw::DrawViewAnnotation, PartDesign::Helix, TechDraw::DrawViewSection, Part::Loft, TechDraw::DrawViewCollection, Fem::FemPostFunctionProvider, Fem::FemPostPipeline, PartDesign::Hole, Fem::ConstraintFluidBoundary, TechDraw::DrawViewImage, PartDesign::DressUp, Assembly::AssemblyLink, Surface::FeatureBlendCurve, Fem::ConstraintBearing, PartDesign::ShapeBinder, Fem::ConstraintContact, Fem::ConstraintRigidBody, Fem::ConstraintPulley, Fem::FemMeshObject, PartDesign::PolarPattern, TechDraw::DrawViewSpreadsheet, Fem::ConstraintHeatflux, Fem::ConstraintTemperature, Robot::TrajectoryDressUpObject, TechDraw::DrawTileWeld, Fem::ConstraintInitialTemperature, TechDraw::DrawRichAnno, Path::Feature, Robot::TrajectoryObject, Surface::Extend, Fem::ConstraintForce, Fem::ConstraintGear, Fem::ConstraintTransform, PartDesign::Boolean, PartDesign::LinearPattern, Robot::Edge2TracObject, TechDraw::DrawTile, Part::Mirroring, Part::RuledSurface, Part::Revolution, Part::Box, PartDesign::FeaturePrimitive, Fem::ConstraintFixed, Fem::ConstraintSpring, PartDesign::Point, TechDraw::DrawViewSymbol, Part::Primitive, PartDesign::Feature, TechDraw::DrawSVGTemplate, Fem::ConstraintPlaneRotation, PartDesign::Plane, PartDesign::FeatureBase, TechDraw::DrawWeldSymbol, PartDesign::Line, TechDraw::DrawViewBalloon, TechDraw::DrawParametricTemplate, Points::Feature, TechDraw::DrawHatch, Mesh::Feature, TechDraw::DrawViewDetail, TechDraw::DrawGeomHatch, TechDraw::DrawViewMulti, TechDraw::LandmarkDimension, Drawing::FeatureClip, Drawing::FeaturePage, Drawing::FeatureViewSymbol, Sandbox::SandboxObject, Sketcher::SketchObject, Part::Ellipse, Part::FilletBase, Part::Line, App::VRMLObject, PartDesign::Chamfer, Surface::GeomFillSurface, Part::Vertex, and Part::Circle.
Referenced by draftviewproviders.view_base.ViewProviderDraft::attach(), TechDraw::DrawGeomHatch::onChanged(), TechDraw::DrawHatch::onChanged(), TechDraw::DrawParametricTemplate::onChanged(), App::TextDocument::onChanged(), TechDraw::DrawSVGTemplate::onChanged(), Sandbox::SandboxObject::onChanged(), Drawing::FeatureViewSymbol::onChanged(), Drawing::FeaturePage::onChanged(), Drawing::FeatureClip::onChanged(), Fem::FemPostFunctionProvider::onChanged(), Fem::FemPostBoxFunction::onChanged(), TechDraw::DrawView::onChanged(), TechDraw::DrawPage::onChanged(), Fem::FemPostCylinderFunction::onChanged(), Fem::Constraint::onChanged(), Fem::FemPostPlaneFunction::onChanged(), Fem::FemPostSphereFunction::onChanged(), App::GeoFeature::onChanged(), Spreadsheet::Sheet::onChanged(), ArchSpace._ViewProviderSpace::onChanged(), ArchSchedule._ArchSchedule::setProperties(), draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), ArchAxis._ViewProviderAxis::updateData(), draftviewproviders.view_dimension.ViewProviderLinearDimension::updateData(), ArchSpace._ViewProviderSpace::updateData(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchSite._ViewProviderSite::updateData(), ArchSectionPlane._ViewProviderSectionPlane::updateData(), and ArchPanel.ViewProviderPanelSheet::updateData().
onDocumentRestored()
virtual void App::DocumentObject::onDocumentRestored () protected virtual
get called after a document has been fully restored
Reimplemented in Sketcher::SketchObject, App::LinkGroup, App::LinkElement, App::Link, Spreadsheet::Sheet, App::LocalCoordinateSystem, TechDraw::DrawViewDimension, Part::FilletBase, Fem::Constraint, TechDraw::DrawViewSection, Fem::FemPostPlaneFunction, Fem::FemPostCylinderFunction, TechDraw::DrawPage, PartDesign::Body, PartDesign::SubShapeBinder, Fem::FemPostBoxFunction, Part::Extrusion, Measure::MeasureBase, TechDraw::DrawViewCollection, Part::Datum, PartDesign::Point, PartDesign::FeatureBase, TechDraw::DrawView, TechDraw::DrawProjGroupItem, Part::Compound2, TechDraw::DrawGeomHatch, TechDraw::LandmarkDimension, and Drawing::FeaturePage.
Referenced by Path.Base.PropertyBag.PropertyBag::__init__(), Path.Dressup.DogboneII.Proxy::__init__(), TechDraw::DrawGeomHatch::onDocumentRestored(), Part::Datum::onDocumentRestored(), PartDesign::SubShapeBinder::onDocumentRestored(), TechDraw::DrawPage::onDocumentRestored(), Fem::Constraint::onDocumentRestored(), Part::FilletBase::onDocumentRestored(), App::LocalCoordinateSystem::onDocumentRestored(), and Sketcher::SketchObject::onDocumentRestored().
onEarlyChange()
void App::DocumentObject::onEarlyChange (const Property * prop) override protected virtual
get called by the container when a property was changed
Reimplemented from App::PropertyContainer.
onLostLinkToObject()
virtual void App::DocumentObject::onLostLinkToObject (DocumentObject *) virtual
Called in case of losing a link Get called by the document when a object got deleted a link property of this object ist pointing to. The standard behaviour of the DocumentObject implementation is to reset the links to nothing. You may override this method to implement additional or different behavior.
onPropertyStatusChanged()
void App::DocumentObject::onPropertyStatusChanged (const Property & prop, unsigned long oldStatus) override protected virtual
get called when a property status has changed
Reimplemented from App::PropertyContainer.
onSettingDocument()
virtual void App::DocumentObject::onSettingDocument () protected virtual
get called after setting the document
Reimplemented in Spreadsheet::Sheet, Fem::Constraint, PartDesign::Body, TechDraw::DrawSVGTemplate, and TechDraw::DrawWeldSymbol.
Referenced by TechDraw::DrawWeldSymbol::onSettingDocument(), TechDraw::DrawSVGTemplate::onSettingDocument(), PartDesign::Body::onSettingDocument(), and Fem::Constraint::onSettingDocument().
onUndoRedoFinished()
virtual void App::DocumentObject::onUndoRedoFinished () protected virtual
get called after an undo/redo transaction is finished
Reimplemented in Sketcher::SketchObject.
onUpdateElementReference()
virtual void App::DocumentObject::onUpdateElementReference (const Property *) inline virtual
Reimplemented in Part::FilletBase, and Sketcher::SketchObject.
Definition at line 665 of file DocumentObject.h.
Referenced by App::PropertyExpressionEngine::updateElementReference(), and Spreadsheet::PropertySheet::updateElementReference().
purgeError()
void App::DocumentObject::purgeError () inline
remove the error from the object
Definition at line 193 of file DocumentObject.h.
References App::Error.
purgeTouched()
void App::DocumentObject::purgeTouched () inline
reset this document object touched
Definition at line 177 of file DocumentObject.h.
References App::Enforce, and App::Touch.
Referenced by TechDrawGui::TaskBalloon::accept(), PartGui::CrossSections::apply(), MeshPartGui::CrossSections::apply(), TechDraw::DrawProjGroupItem::autoPosition(), PointsGui::ViewProviderScattered::cut(), PointsGui::ViewProviderStructured::cut(), TechDraw::DrawView::execute(), Sandbox::CustomPurgeEvent::execute(), Mesh::Importer::load(), TechDraw::DrawProjGroup::onChanged(), TechDraw::DrawPage::onChanged(), Assembly::AssemblyObject::redrawJointPlacement(), TechDrawGui::TaskBalloon::reject(), Gui::TaskOrientation::reject(), Gui::TaskImage::reject(), MeshGui::ViewProviderMesh::removeFacets(), MeshGui::ViewProviderMesh::segmentMesh(), Assembly::AssemblyObject::setNewPlacements(), MeshGui::ViewProviderMesh::splitMesh(), MeshGui::ViewProviderMesh::trimMesh(), and Assembly::AssemblyLink::updateContents().
recompute()
virtual App::DocumentObjectExecReturn* App::DocumentObject::recompute () protected virtual
recompute only this object
Reimplemented in Drawing::FeatureView, Part::Feature, and PartDesign::Feature.
Referenced by App::Document::_recomputeFeature(), Measure::MeasureBase::onDocumentRestored(), Drawing::FeatureView::recompute(), Part::Feature::recompute(), TechDraw::DrawViewPart::rotate(), draftguitools.gui_trackers.arcTracker::setApertureAngle(), draftguitools.gui_trackers.arcTracker::setEndAngle(), draftguitools.gui_trackers.arcTracker::setStartAngle(), TechDraw::DrawViewPart::spin(), draftguitools.gui_trackers.bsplineTracker::update(), and draftguitools.gui_trackers.bezcurveTracker::update().
recomputeFeature()
bool App::DocumentObject::recomputeFeature (bool recursive = false)
Recompute only this feature
Parameters
recursive set to true to recompute any dependent objects as well
Referenced by TechDrawGui::_createLinDimension(), TechDrawGui::TaskDimRepair::accept(), TechDrawGui::TaskGeomHatch::accept(), FemGui::TaskDlgMeshShapeNetgen::accept(), RobotGui::TaskDlgEdge2Trac::accept(), RobotGui::TaskDlgTrajectoryDressUp::accept(), TechDrawGui::TaskActiveView::accept(), TechDrawGui::TaskProjGroup::accept(), FemGui::TaskDlgCreateNodeSet::accept(), FemGui::TaskDlgCreateElementSet::accept(), TechDrawGui::TaskCosVertex::accept(), SurfaceGui::FillingEdgePanel::accept(), SurfaceGui::GeomFillSurface::accept(), SurfaceGui::SectionsPanel::accept(), SurfaceGui::FillingPanel::accept(), TechDrawGui::TaskWeldingSymbol::accept(), TechDraw::DrawProjGroup::addProjection(), TechDrawGui::TaskSectionView::apply(), TechDrawGui::TaskProjGroup::apply(), TechDrawGui::TaskHatch::apply(), TechDrawGui::TaskComplexSection::apply(), TechDrawGui::TaskProjGroup::AutoDistributeClicked(), SurfaceGui::GeomFillSurface::changeFillType(), PartGui::CylinderPrimitive::changeValue(), PartGui::ConePrimitive::changeValue(), PartGui::SpherePrimitive::changeValue(), PartGui::EllipsoidPrimitive::changeValue(), PartGui::TorusPrimitive::changeValue(), PartGui::PrismPrimitive::changeValue(), PartGui::WedgePrimitive::changeValue(), PartGui::HelixPrimitive::changeValue(), PartGui::SpiralPrimitive::changeValue(), PartGui::EllipsePrimitive::changeValue(), PartGui::PolygonPrimitive::changeValue(), PartGui::LinePrimitive::changeValue(), RobotGui::TaskDlgTrajectoryDressUp::clicked(), TechDrawGui::TaskCenterLine::createCenterLine(), dimMaker(), execMidpoints(), execQuadrants(), SurfaceGui::GeomFillSurface::flipOrientation(), TechDraw::DrawViewSpreadsheet::getSheetImage(), Import::ImportOCAF2::loadShapes(), SurfaceGui::FillingVertexPanel::onSelectionChanged(), SurfaceGui::FillingEdgePanel::onSelectionChanged(), SurfaceGui::GeomFillSurface::onSelectionChanged(), SurfaceGui::SectionsPanel::onSelectionChanged(), SurfaceGui::FillingPanel::onSelectionChanged(), prepareProfileBased(), PartDesignGui::ViewProviderTransformed::recomputeFeature(), TechDrawGui::TaskSectionView::reject(), TechDrawGui::TaskBalloon::reject(), TechDrawGui::TaskDetail::reject(), TechDrawGui::TaskComplexSection::reject(), TechDrawGui::TaskCenterLine::reject(), TechDraw::DrawProjGroup::reportReady(), TechDrawGui::TaskProjGroup::scaleManuallyChanged(), Gui::Document::slotSkipRecompute(), TechDrawGui::TaskProjGroup::spacingChanged(), FemGui::TaskPostDataAtPoint::TaskPostDataAtPoint(), TechDrawGui::TaskProjGroup::turnProjGroupToView(), PartDesign::SubShapeBinder::update(), TechDraw::DrawPage::updateAllViews(), TechDrawGui::TaskDetail::updateDetail(), PartDesignGui::TaskDressUpParameters::updateFeature(), TechDrawGui::TaskCenterLine::updateOrientation(), and TechDrawGui::TaskProjGroup::viewToggled().
redirectSubName()
virtual bool App::DocumentObject::redirectSubName (std::ostringstream & ss, DocumentObject * topParent, DocumentObject * child) const virtual
Allow object to redirect a subname path
Parameters
ss input as the current subname path from topParent leading just before this object, i.e. ends at the parent of this object. This function should append its own name to this path, or redirect the subname to other place.
topParent top parent of this subname path
child the immediate child object in the path
This function is called by tree view to generate a subname path when an item is selected in the tree. Document object can use this function to redirect the selection to some other objects.
Referenced by Gui::DocumentItem::findItem(), Gui::DocumentObjectItem::getSubName(), Gui::TreeWidget::onPreSelectTimer(), and Gui::DocumentItem::updateItemSelection().
removeDynamicProperty()
bool App::DocumentObject::removeDynamicProperty (const char * prop) override virtual
Reimplemented from App::PropertyContainer.
Referenced by Spreadsheet::Sheet::clear(), Spreadsheet::Sheet::clearAll(), Spreadsheet::Sheet::removeColumns(), Spreadsheet::Sheet::removeRows(), Spreadsheet::Cell::setAlias(), Spreadsheet::Sheet::setFloatProperty(), Spreadsheet::Sheet::setIntegerProperty(), Spreadsheet::Sheet::setObjectProperty(), Spreadsheet::Sheet::setQuantityProperty(), Spreadsheet::Sheet::setStringProperty(), PartDesign::SubShapeBinder::setupCopyOnChange(), PartDesign::SubShapeBinder::update(), and Spreadsheet::Sheet::updateProperty().
renameObjectIdentifiers()
virtual void App::DocumentObject::renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > & paths) virtual
Reimplemented in Spreadsheet::Sheet.
resetError()
void App::DocumentObject::resetError () inline protected
Definition at line 730 of file DocumentObject.h.
References App::Error.
Referenced by App::Document::_recomputeFeature().
resolve()
App::DocumentObject* App::DocumentObject::resolve (const char * subname, App::DocumentObject ** parent = nullptr, std::string * childName = nullptr, const char ** subElement = nullptr, PyObject ** pyObj = nullptr, Base::Matrix4D * mat = nullptr, bool transform = true, int depth = 0) const
Resolve the last document object referenced in the subname
Parameters
subname dot separated subname
parent return the direct parent of the object
childName return child name to be passed to is/setElementVisible()
subElement return non-object sub-element name if found. The pointer is guaranteed to be within the buffer pointed to by 'subname'
See also
getSubObject()
Returns
Returns the last referenced document object in the subname. If no such object in subname, return pObject.
Referenced by _getTopoShape(), Gui::ViewProviderLink::applyColors(), Gui::ViewProviderLink::getElementColors(), Measure::ShapeFinder::resolveSelection(), and Gui::SelectionSingleton::setVisible().
resolveRelativeLink()
App::DocumentObject* App::DocumentObject::resolveRelativeLink (std::string & subname, App::DocumentObject *& link, std::string & linkSub) const
Resolve a link reference that is relative to this object reference
Parameters
subname on input, this is the subname reference to the object that is to be assigned a link. On output, the reference may be offset to be rid of any common parent.
link on input, this is the top parent of the link reference. On output, it may be altered to one of its child to be rid off any common parent.
linkSub on input, this the subname of the link reference. On output, it may be offset to be rid off any common parent.
Returns
The corrected top parent of the object that is to be assigned the link. If the output 'subname' is empty, then return the object itself.
To avoid any cyclic reference, an object must not be assign a link to any of the object in its parent. This function can be used to resolve any common parents of an object and its link target.
For example, with the following object hierarchy
Group |–Group001 | |–Box | |–Cylinder |–Group002 |–Box001 |–Cylinder001
If you want add a link of Group.Group002.Box001 to Group.Group001, you can call with the following parameter (which are usually obtained from Selection.getSelectionEx(), check usage in TreeWidget::onDropEvent()): std::string subname("Group002."); auto link = Group; std::string linkSub("Group001.Box001."); parent = Group.resolveRelativeLink(subname,link,linkSub);
The resolving result is as follow: return -> Group001 subname -> "" link -> Group002 linkSub -> "Box001."
The common parent 'Group' is removed.
Save()
void App::DocumentObject::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Reimplemented in App::VRMLObject, Sketcher::SketchObject, and Robot::RobotObject.
Referenced by App::VRMLObject::Save(), Robot::RobotObject::Save(), and Sketcher::SketchObject::Save().
setDocument()
void App::DocumentObject::setDocument (App::Document * doc) protected
Referenced by App::Document::addObject(), App::Document::addObjects(), and App::Document::moveObject().
setElementVisible()
virtual int App::DocumentObject::setElementVisible (const char * element, bool visible) virtual
Child element handling Set sub-element visibility
For performance reason, element must not contain any further sub-elements, i.e. there should be no '.' inside element.
Returns
-1 if element visibility is not supported, 0 if element is not found, 1 if success
Referenced by App::LinkBaseExtension::extensionSetElementVisible().
setError()
void App::DocumentObject::setError () inline protected
Definition at line 726 of file DocumentObject.h.
References App::Error.
Referenced by App::LocalCoordinateSystem::execute().
setExpression()
virtual void App::DocumentObject::setExpression (const ObjectIdentifier & path, std::shared_ptr< App::Expression > expr) virtual
setStatus()
void App::DocumentObject::setStatus (ObjectStatus pos, bool on) inline
Definition at line 230 of file DocumentObject.h.
References RobotExample::pos.
Referenced by App::Document::_removeObject(), PartDesign::AdditiveHelix::AdditiveHelix(), App::Document::addObject(), App::Document::addObjects(), App::DocumentP::addRecomputeLog(), TechDraw::DrawViewDimension::DrawViewDimension(), App::LocalCoordinateSystem::LocalCoordinateSystem(), Part::Offset2D::Offset2D(), App::Origin::Origin(), App::Document::readObjects(), App::Document::Restore(), Path::PropertyPath::RestoreDocFile(), Gui::DocumentObjectItem::setExpandedStatus(), and PartDesign::SubtractiveHelix::SubtractiveHelix().
setupObject()
virtual void App::DocumentObject::setupObject () protected virtual
get called after a brand new object was created
Reimplemented in App::LocalCoordinateSystem, TechDraw::DrawViewSection, PartDesign::SubShapeBinder, Part::Extrusion, PartDesign::Body, Part::Sweep, Part::Revolution, Sketcher::SketchObject, Part::Loft, TechDraw::DrawViewImage, Part::Face, TechDraw::DrawTileWeld, TechDraw::DrawGeomHatch, PartDesign::ProfileBased, PartDesign::FeatureExtrude, and TechDraw::DrawHatch.
Referenced by App::Document::addObject(), App::Document::addObjects(), TechDraw::DrawTileWeld::setupObject(), Part::Face::setupObject(), Part::Loft::setupObject(), Part::Revolution::setupObject(), Part::Sweep::setupObject(), PartDesign::Body::setupObject(), Part::Extrusion::setupObject(), and TechDraw::DrawViewSection::setupObject().
testIfLinkDAGCompatible() [1/4]
bool App::DocumentObject::testIfLinkDAGCompatible (App::PropertyLinkSub & linkTo) const
testIfLinkDAGCompatible() [2/4]
bool App::DocumentObject::testIfLinkDAGCompatible (App::PropertyLinkSubList & linksTo) const
testIfLinkDAGCompatible() [3/4]
bool App::DocumentObject::testIfLinkDAGCompatible (const std::vector< DocumentObject * > & linksTo) const
testIfLinkDAGCompatible() [4/4]
bool App::DocumentObject::testIfLinkDAGCompatible (DocumentObject * linkTo) const
testIfLinkIsDAG tests a link that is about to be created for circular references.
Parameters
objToLinkIn (input). The object this object is to depend on after the link is going to be created.
Returns
true if link can be created (no cycles will be made). False if the link will cause a circular dependency and break recomputes. Throws an error if the document already has a circular dependency. That is, if the return is true, the link is allowed.
testStatus()
bool App::DocumentObject::testStatus (ObjectStatus pos) const inline
Definition at line 226 of file DocumentObject.h.
References RobotExample::pos.
Referenced by Gui::SelectionSingleton::checkSelection(), Gui::DocumentItem::createNewItem(), App::GeoFeatureGroupExtension::extensionGetSubObjects(), App::Expression::getDepObjects(), App::PropertyXLink::getDocumentInList(), App::PropertyXLink::getDocumentOutList(), Part::Feature::onBeforeChange(), PartDesign::DressUp::onChanged(), FemGui::ViewProviderFemMesh::onChanged(), Part::FilletBase::onChanged(), App::GeoFeature::onChanged(), App::Document::readObjects(), PartDesign::SubShapeBinder::slotRecomputedObject(), and App::LinkBaseExtension::update().
touch()
void App::DocumentObject::touch (bool noRecompute = false)
set this document object touched (cause recomputation on dependent features)
Set the property touched -> changed, cause recomputation in Update()
Referenced by TechDrawGui::_createLinDimension(), Gui::ElementColors::Private::accept(), App::Document::addRecomputeObject(), TechDrawGui::TaskRichAnno::createAnnoFeature(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), dimensionMaker(), TDHandlerDimension::finalizeCommand(), PartDesign::FeaturePrimitive::onChanged(), PartDesign::Boolean::onChanged(), Gui::ViewProviderGeometryObject::onChanged(), TechDraw::DrawViewSection::onChanged(), TechDraw::DrawProjGroupItem::onChanged(), FemGui::ViewProviderFemMesh::onChanged(), TechDrawGui::TaskGeomHatch::reject(), PartGui::ViewProviderPartExt::setHighlightedEdges(), PartGui::ViewProviderPartExt::setHighlightedFaces(), PartGui::ViewProviderPartExt::setHighlightedPoints(), and TechDraw::DrawView::touchTreeOwner().
unfreeze()
void App::DocumentObject::unfreeze (bool noRecompute = false)
set this document object unfreezed (and touch it)
unsetupObject()
virtual void App::DocumentObject::unsetupObject () protected virtual
get called when object is going to be removed from the document
Reimplemented in TechDraw::DrawViewPart, App::LocalCoordinateSystem, Fem::Constraint, TechDraw::DrawPage, PartDesign::Body, TechDraw::DrawViewSection, TechDraw::DrawViewCollection, TechDraw::DrawProjGroupItem, TechDraw::DrawGeomHatch, TechDraw::DrawViewDetail, TechDraw::DrawHatch, and TechDraw::LandmarkDimension.
Referenced by App::Document::_removeObject(), TechDraw::DrawHatch::unsetupObject(), TechDraw::DrawGeomHatch::unsetupObject(), and PartDesign::Body::unsetupObject().
Friends And Related Function Documentation
Document
friend class Document friend
Definition at line 528 of file DocumentObject.h.
ObjectExecution
friend class ObjectExecution friend
Definition at line 530 of file DocumentObject.h.
Transaction
friend class Transaction friend
Definition at line 529 of file DocumentObject.h.
Member Data Documentation
_pDoc
App::Document* App::DocumentObject::_pDoc {nullptr} protected
pointer to the document this object belongs to
Definition at line 763 of file DocumentObject.h.
ExpressionEngine
PropertyExpressionEngine App::DocumentObject::ExpressionEngine
Definition at line 108 of file DocumentObject.h.
Referenced by App::Document::_recomputeFeature(), Gui::ExpressionBinding::bind(), App::Document::exportGraphviz(), Gui::ExpressionBinding::setExpression(), and Spreadsheet::Sheet::updateBindings().
Label
PropertyString App::DocumentObject::Label
Definition at line 106 of file DocumentObject.h.
Referenced by ExpressionCompleterModel::_data(), PartGui::SweepWidget::accept(), MeshGui::Segmentation::accept(), ReverseEngineeringGui::Segmentation::accept(), FemGui::TaskDlgCreateNodeSet::accept(), FemGui::TaskDlgCreateElementSet::accept(), MeshGui::SegmentationBestFit::accept(), App::Document::addObject(), App::Document::addObjects(), Assembly::BomObject::addObjectToBom(), TechDraw::DrawProjGroup::addProjection(), Gui::ExpressionBinding::apply(), Gui::ViewProviderFeaturePythonImp::attach(), SurfaceGui::FillingEdgePanel::checkOpenCommand(), SurfaceGui::FillingVertexPanel::checkOpenCommand(), SurfaceGui::GeomFillSurface::checkOpenCommand(), SurfaceGui::SectionsPanel::checkOpenCommand(), SurfaceGui::FillingPanel::checkOpenCommand(), TechDraw::ShapeExtractor::checkShape(), TechDrawGui::TaskRichAnno::createAnnoFeature(), Gui::TreeWidgetItemDelegate::createEditor(), Import::ExportOCAF::createNode(), Gui::ViewProviderIndex::data(), SpreadsheetGui::DlgBindSheet::DlgBindSheet(), PartGui::DlgProjectionOnSurface::DlgProjectionOnSurface(), Gui::DocumentObjectData::DocumentObjectData(), PartDesignGui::ViewProviderDatum::doubleClicked(), Gui::ElementColors::ElementColors(), Drawing::FeatureViewSpreadsheet::execute(), TechDraw::DrawViewArch::execute(), Inspection::Feature::execute(), App::Document::exportGraphviz(), App::PropertyLinkBase::exportSubName(), App::OriginGroupExtension::extensionGetSubObject(), PartGui::FaceAppearances::FaceAppearances(), Gui::Dialog::DlgPropertyLink::formatObject(), TechDraw::DrawTemplate::getAutofillValue(), TechDraw::DrawProjGroup::getDirsFromFront(), Gui::LinkInfo::getLinkedLabel(), TechDraw::DrawTemplate::getPageNumbers(), TechDraw::DrawViewSpreadsheet::getSheetImage(), MeshPartGui::Mesh2ShapeGmsh::loadOutput(), Import::ImportOCAF2::loadShapes(), TechDrawGui::TaskLinkDim::loadToTree(), PartDesignGui::TaskSketchBasedParameters::make2DLabel(), MeshGui::MeshSplit::makeCopy(), TechDraw::DrawViewSection::makeSectionCut(), PartDesignGui::TaskSketchBasedParameters::objectNameByLabel(), TechDraw::DrawViewDetail::onChanged(), App::TextDocument::onChanged(), TechDraw::DrawView::onChanged(), TechDraw::DrawPage::onChanged(), TechDraw::DrawViewPart::onHlrFinished(), TechDrawGui::TaskComplexSection::onProfileObjectsUseSelectionClicked(), PartDesignGui::TaskBooleanParameters::onSelectionChanged(), SurfaceGui::FillingEdgePanel::onSelectionChanged(), SurfaceGui::FillingVertexPanel::onSelectionChanged(), SurfaceGui::GeomFillSurface::onSelectionChanged(), SurfaceGui::SectionsPanel::onSelectionChanged(), SurfaceGui::FillingPanel::onSelectionChanged(), TechDraw::DrawWeldSymbol::onSettingDocument(), App::DocumentObjectT::operator=(), Fem::PropertyPostDataObject::RestoreDocFile(), App::PropertyLinkBase::restoreLabelReference(), Fem::PropertyPostDataObject::SaveDocFile(), Import::ExportOCAF::saveShape(), Gui::DocumentObjectItem::setData(), SurfaceGui::FillingEdgePanel::setEditedObject(), SurfaceGui::SectionsPanel::setEditedObject(), SurfaceGui::FillingPanel::setEditedObject(), Gui::ExpressionBinding::setExpression(), RobotGui::TaskEdge2TracParameter::setHideShowObject(), Gui::Dialog::DlgInspector::setNodeNames(), TechDrawGui::TaskComplexSection::setUiCommon(), TechDrawGui::TaskDetail::setUiFromFeat(), TechDrawGui::TaskDimRepair::setUiPrimary(), PartDesignGui::TaskRevolutionParameters::setupDialog(), PartDesignGui::TaskExtrudeParameters::setupDialog(), PartDesignGui::TaskTransformedParameters::setupTransaction(), DrawingGui::ViewProviderDrawingPage::showDrawingView(), Spreadsheet::SheetObserver::slotChangedObject(), FemGui::TaskObjectName::TaskObjectName(), PartDesignGui::TaskPipeOrientation::TaskPipeOrientation(), PartDesignGui::TaskPipeParameters::TaskPipeParameters(), TechDraw::DrawHatch::translateLabel(), TechDraw::DrawGeomHatch::translateLabel(), TechDraw::DrawSVGTemplate::translateLabel(), TechDraw::DrawView::translateLabel(), TechDraw::DrawPage::translateLabel(), App::PropertyLinkBase::tryReplaceLink(), TechDrawGui::TaskProjGroup::turnProjGroupToView(), TechDraw::DrawProjGroupItem::unsetupObject(), PartDesign::SubShapeBinder::update(), DrawingGui::ViewProviderDrawingPage::updateData(), App::ObjectIdentifier::updateLabelReference(), App::PropertyLinkBase::updateLabelReferences(), TechDrawGui::TaskDimRepair::updateUi(), MeshPartGui::Mesh2ShapeGmsh::writeProject(), TechDraw::DrawViewDetail::~DrawViewDetail(), TechDraw::DrawViewPart::~DrawViewPart(), and TechDraw::DrawViewSection::~DrawViewSection().
Label2
PropertyString App::DocumentObject::Label2
Definition at line 107 of file DocumentObject.h.
Referenced by Gui::TreeWidgetItemDelegate::createEditor(), Gui::DocumentObjectData::DocumentObjectData(), and Gui::DocumentObjectItem::setData().
oldLabel
std::string App::DocumentObject::oldLabel protected
Old label; used for renaming expressions.
Definition at line 766 of file DocumentObject.h.
pcNameInDocument
const std::string* App::DocumentObject::pcNameInDocument {nullptr} protected
Definition at line 769 of file DocumentObject.h.
Referenced by App::Document::_addObject(), App::Document::addObject(), App::Document::addObjects(), and Spreadsheet::Sheet::execute().
PythonObject
Py::SmartPtr App::DocumentObject::PythonObject protected
python object of this class and all descendent
Definition at line 761 of file DocumentObject.h.
Referenced by TechDraw::DrawHatch::getPyObject(), Assembly::BomObject::getPyObject(), TechDraw::DrawParametricTemplate::getPyObject(), Assembly::AssemblyLink::getPyObject(), Part::Feature::getPyObject(), TechDraw::DrawGeomHatch::getPyObject(), TechDraw::DrawWeldSymbol::getPyObject(), Assembly::AssemblyObject::getPyObject(), TechDraw::DrawLeaderLine::getPyObject(), Assembly::BomGroup::getPyObject(), Assembly::SimulationGroup::getPyObject(), Assembly::ViewGroup::getPyObject(), Assembly::JointGroup::getPyObject(), Part::Primitive::getPyObject(), Mesh::Feature::getPyObject(), TechDraw::DrawTemplate::getPyObject(), TechDraw::DrawViewSymbol::getPyObject(), App::DocumentObjectGroup::getPyObject(), App::VRMLObject::getPyObject(), App::InventorObject::getPyObject(), TechDraw::DrawTile::getPyObject(), Path::Feature::getPyObject(), TechDraw::DrawRichAnno::getPyObject(), TechDraw::DrawViewDimExtent::getPyObject(), TechDraw::DrawTileWeld::getPyObject(), TechDraw::DrawSVGTemplate::getPyObject(), TechDraw::DrawBrokenView::getPyObject(), Measure::MeasureBase::getPyObject(), TechDraw::DrawProjGroupItem::getPyObject(), TechDraw::DrawView::getPyObject(), App::GeoFeature::getPyObject(), TechDraw::DrawViewClip::getPyObject(), TechDraw::DrawPage::getPyObject(), TechDraw::DrawProjGroup::getPyObject(), PartDesign::Body::getPyObject(), TechDraw::DrawViewPart::getPyObject(), Spreadsheet::Sheet::getPyObject(), and PartDesign::PYTHON_TYPE_DEF().
signalBeforeChange
boost::signals2::signal<void(const App::DocumentObject&, const App::Property&)> App::DocumentObject::signalBeforeChange
signal before changing a property of this object
Definition at line 115 of file DocumentObject.h.
signalChanged
boost::signals2::signal<void(const App::DocumentObject&, const App::Property&)> App::DocumentObject::signalChanged
signal on changed property of this object
Definition at line 117 of file DocumentObject.h.
Referenced by MeasureGui::ViewProviderMeasureBase::connectToSubject(), App::GroupExtension::extensionOnChanged(), and Spreadsheet::PropertySheet::onAddDep().
signalEarlyChanged
boost::signals2::signal<void(const App::DocumentObject&, const App::Property&)> App::DocumentObject::signalEarlyChanged
signal on changed property of this object before document scoped signalChangedObject
Definition at line 119 of file DocumentObject.h.
StatusBits
std::bitset<32> App::DocumentObject::StatusBits protected
Status bits of the document object The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects. The bits and their meaning are listed below: 0 - object is marked as 'touched' 1 - object is marked as 'erroneous' 2 - object is marked as 'new' 3 - object is marked as 'recompute', i.e. the object gets recomputed now 4 - object is marked as 'restoring', i.e. the object gets loaded at the moment 5 - object is marked as 'deleting', i.e. the object gets deleted at the moment 6 - reserved 7 - reserved 16 - object is marked as 'expanded' in the tree view
Definition at line 724 of file DocumentObject.h.
StdReturn
DocumentObjectExecReturn* App::DocumentObject::StdReturn static
Definition at line 532 of file DocumentObject.h.
Referenced by App::Document::_recomputeFeature(), App::Document::afterRestore(), PartDesign::FeatureExtrude::buildExtrusion(), TechDraw::DrawHatch::execute(), TechDraw::LandmarkDimension::execute(), PartDesign::Body::execute(), TechDraw::DrawParametricTemplate::execute(), TechDraw::DrawViewMulti::execute(), Points::Feature::execute(), TechDraw::DrawGeomHatch::execute(), Surface::Filling::execute(), Part::FeatureReference::execute(), Mesh::Feature::execute(), TechDraw::DrawLeaderLine::execute(), PartDesign::Hole::execute(), Part::CurveNet::execute(), Part::ImportBrep::execute(), Part::ImportIges::execute(), Surface::Sections::execute(), Part::FeatureGeometrySet::execute(), PartDesign::Loft::execute(), Fem::FemMeshShapeObject::execute(), Part::Face::execute(), Part::ImportStep::execute(), Part::CustomFeature::execute(), Sketcher::SketchObjectSF::execute(), PartDesign::Fillet::execute(), PartDesign::Helix::execute(), Part::Polygon::execute(), Robot::TrajectoryCompound::execute(), Surface::Sewing::execute(), PartDesign::Thickness::execute(), TechDraw::DrawRichAnno::execute(), Mesh::Sphere::execute(), Path::FeatureCompound::execute(), PartDesign::Pipe::execute(), Points::Structured::execute(), PartDesign::Chamfer::execute(), Mesh::Import::execute(), Mesh::TransformDemolding::execute(), Drawing::FeaturePage::execute(), TechDraw::DrawViewDimExtent::execute(), Mesh::Curvature::execute(), Drawing::FeatureViewSymbol::execute(), Mesh::SetOperations::execute(), Surface::Extend::execute(), Mesh::Transform::execute(), Part::Offset::execute(), Drawing::FeatureViewAnnotation::execute(), Mesh::Ellipsoid::execute(), Mesh::SegmentByMesh::execute(), Mesh::FixDefects::execute(), Surface::FeatureBlendCurve::execute(), PartDesign::Boolean::execute(), Fem::FemMeshShapeNetgenObject::execute(), Part::Offset2D::execute(), Robot::Edge2TracObject::execute(), Drawing::FeatureViewSpreadsheet::execute(), Drawing::FeatureClip::execute(), Fem::FemPostFunction::execute(), Surface::GeomFillSurface::execute(), Part::ProjectOnSurface::execute(), TechDraw::DrawBrokenView::execute(), Mesh::Export::execute(), Mesh::HarmonizeNormals::execute(), Robot::TrajectoryDressUpObject::execute(), Drawing::FeatureViewPart::execute(), TechDraw::DrawViewDraft::execute(), PartDesign::Groove::execute(), PartDesign::Revolution::execute(), Part::Extrusion::execute(), Drawing::FeatureView::execute(), Drawing::FeatureProjection::execute(), TechDraw::DrawViewArch::execute(), TechDraw::DrawViewClip::execute(), TechDraw::DrawViewCollection::execute(), TechDraw::FeatureProjection::execute(), PartDesign::FeaturePrimitive::execute(), TechDraw::DrawProjGroup::execute(), Part::Scale::execute(), TechDraw::DrawViewSection::execute(), Mesh::FlipNormals::execute(), Sketcher::SketchObject::execute(), Mesh::Cylinder::execute(), PartDesign::Transformed::execute(), Part::Sweep::execute(), Mesh::FixNonManifolds::execute(), PartDesign::Cylinder::execute(), Mesh::Cone::execute(), App::FeatureTest::execute(), App::PropertyExpressionEngine::execute(), Mesh::FixDuplicatedFaces::execute(), Fem::Constraint::execute(), Mesh::Torus::execute(), Mesh::FixDuplicatedPoints::execute(), PartDesign::Sphere::execute(), Mesh::FixDegenerations::execute(), Mesh::Cube::execute(), Part::Refine::execute(), App::FeatureTestAbsAddress::execute(), Part::Reverse::execute(), Mesh::FixDeformations::execute(), PartDesign::Cone::execute(), App::FeatureTestAttribute::execute(), Mesh::FixIndices::execute(), Mesh::FillHoles::execute(), PartDesign::Ellipsoid::execute(), Mesh::RemoveComponents::execute(), PartDesign::Torus::execute(), PartDesign::Prism::execute(), PartDesign::Wedge::execute(), App::DocumentObjectExtension::extensionExecute(), and validateParameters().
Visibility
PropertyBool App::DocumentObject::Visibility
Allow control visibility status in App name space.
Definition at line 111 of file DocumentObject.h.
Referenced by PartDesign::Body::addObject(), Gui::ViewProviderDocumentObject::attach(), ReverseEngineeringGui::SegmentationManual::createSegment(), FemGui::ViewProviderFemPostObject::hide(), Gui::TreeWidget::mousePressEvent(), Gui::ViewProviderDocumentObject::onChanged(), PartGui::SectionCut::onRefreshCutPBclicked(), MeasureGui::ViewProviderMeasureBase::onSubjectVisibilityChanged(), and Gui::ViewProviderDocumentObject::show().
The documentation for this class was generated from the following files:
DocumentObject.h
DocumentObject.cpp