FreeCAD: Gui::SoFCSelection Class Reference
Gui::SoFCSelection Class Reference
#include <SoFCSelection.h>
Public Types
enum HighlightModes { AUTO, ON, OFF }
enum SelectionModes { SEL_ON, SEL_OFF }
enum Selected { NOTSELECTED, SELECTED }
enum Styles { EMISSIVE, EMISSIVE_DIFFUSE, BOX }
Public Member Functions
SoFCSelection ()
void applySettings ()
Load highlight settings from the configuration.
SbBool isHighlighted () const
void doAction (SoAction *action) override
void GLRender (SoGLRenderAction *action) override
void handleEvent (SoHandleEventAction *action) override
void GLRenderBelowPath (SoGLRenderAction *action) override
void GLRenderInPath (SoGLRenderAction *action) override
Static Public Member Functions
static void initClass ()
static void finish ()
static void turnOffCurrentHighlight (SoGLRenderAction *action)
Public Attributes
SoSFColor colorHighlight
SoSFColor colorSelection
SoSFEnum style
SoSFEnum selected
SoSFEnum highlightMode
SoSFEnum selectionMode
SoSFString documentName
SoSFString objectName
SoSFString subElementName
SoSFBool useNewSelection
Protected Types
using SelContext = SoFCSelectionContext
using SelContextPtr = std::shared_ptr< SelContext >
Protected Member Functions
~SoFCSelection () override
virtual void redrawHighlighted (SoAction *act, SbBool flag)
SbBool readInstance (SoInput *in, unsigned short flags) override
Protected Attributes
SelContextPtr selContext
SelContextPtr selContext2
Detailed Description
Selection node This node does the complete highlighting and selection together with the viewer
Author
Jürgen Riegel
Definition at line 59 of file SoFCSelection.h.
Member Typedef Documentation
SelContext
using Gui::SoFCSelection::SelContext = SoFCSelectionContext protected
Definition at line 113 of file SoFCSelection.h.
SelContextPtr
using Gui::SoFCSelection::SelContextPtr = std::shared_ptr<SelContext> protected
Definition at line 114 of file SoFCSelection.h.
Member Enumeration Documentation
HighlightModes
enum Gui::SoFCSelection::HighlightModes
Enumerator
AUTO
ON
OFF
Definition at line 72 of file SoFCSelection.h.
Selected
enum Gui::SoFCSelection::Selected
Enumerator
NOTSELECTED
SELECTED
Definition at line 80 of file SoFCSelection.h.
SelectionModes
enum Gui::SoFCSelection::SelectionModes
Enumerator
SEL_ON
SEL_OFF
Definition at line 76 of file SoFCSelection.h.
Styles
enum Gui::SoFCSelection::Styles
Enumerator
EMISSIVE
EMISSIVE_DIFFUSE
BOX
Definition at line 84 of file SoFCSelection.h.
Constructor & Destructor Documentation
SoFCSelection()
SoFCSelection::SoFCSelection ()
Constructor.
Definition at line 75 of file SoFCSelection.cpp.
References SCL.SimpleDataTypes::f, Gui::ViewParams::getUseNewSelection(), Gui::ViewParams::instance(), and MeshCore::MeshIO::OFF.
~SoFCSelection()
SoFCSelection::~SoFCSelection () override protected
Destructor.
Definition at line 122 of file SoFCSelection.cpp.
Member Function Documentation
applySettings()
void SoFCSelection::applySettings ()
Load highlight settings from the configuration.
Definition at line 1034 of file SoFCSelection.cpp.
References colorHighlight, colorSelection, ParameterGrp::GetBool(), Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), ParameterGrp::GetUnsigned(), highlight(), highlightMode, OpenSCADFeatures::long, OFF, SEL_OFF, Path.Dressup.Utils::selection(), and selectionMode.
doAction()
void SoFCSelection::doAction (SoAction * action) override
Definition at line 155 of file SoFCSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::SelectionChanges::AddSelection, Gui::SoSelectionElementAction::All, Gui::SoSelectionElementAction::Append, AUTO, Gui::SelectionChanges::ClrSelection, colorHighlight, colorSelection, documentName, Gui::SoFCDocumentObjectAction::documentName, Gui::SoFCSelectionRoot::getActionContext(), highlightMode, Gui::SelectionSingleton::isSelected(), Gui::SoSelectionElementAction::None, NOTSELECTED, objectName, OFF, Gui::SoSelectionElementAction::Remove, Gui::SelectionChanges::RmvSelection, SEL_OFF, SEL_ON, selContext, SELECTED, selected, Gui::Selection(), selectionMode, Gui::SelectionChanges::SetSelection, subElementName, and useNewSelection.
finish()
void SoFCSelection::finish () static
Definition at line 141 of file SoFCSelection.cpp.
Referenced by drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::accept(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::accept(), draftguitools.gui_split.Split::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_subelements.SubelementHighlight::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rotate.Rotate::action(), draftguitools.gui_fillets.Fillet::action(), draftguitools.gui_move.Move::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_arcs.Arc::action(), draftguitools.gui_texts.Text::action(), draftguitools.gui_scale.Scale::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_trimex.Trimex::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_styles.ApplyStyle::Activated(), draftguitools.gui_join.Join::Activated(), draftguitools.gui_draft2sketch.Draft2Sketch::Activated(), draftguitools.gui_downgrade.Downgrade::Activated(), draftguitools.gui_upgrade.Upgrade::Activated(), draftguitools.gui_shape2dview.Shape2DView::Activated(), draftguitools.gui_facebinders.Facebinder::Activated(), draftguitools.gui_subelements.SubelementHighlight::Activated(), draftguitools.gui_wire2spline.WireToBSpline::Activated(), draftguitools.gui_clone.Clone::Activated(), draftguitools.gui_dimensions.Dimension::Activated(), draftguitools.gui_edit.Edit::Activated(), draftguitools.gui_selectplane.Draft_SelectPlane::check_selection(), DraftGui.DraftToolBar::checkSpecialChars(), draftguitools.gui_points.Point::click(), draftguitools.gui_orthoarray.OrthoArray::completed(), draftguitools.gui_polararray.PolarArray::completed(), draftguitools.gui_circulararray.CircularArray::completed(), draftguitools.gui_labels.Label::create(), bimcommands.BimText.BIM_Text::createObject(), draftguitools.gui_rectangles.Rectangle::createObject(), draftguitools.gui_ellipses.Ellipse::createObject(), draftguitools.gui_texts.Text::createObject(), draftviewproviders.view_text.ViewProviderText::createObject(), draftguitools.gui_stretch.Stretch::doStretch(), draftguitools.gui_fillets.Fillet::draw_arc(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), DraftGui.DraftToolBar::editUi(), DraftGui.DraftToolBar::escape(), Gui::SoFCDB::finish(), draftguitools.gui_move.Move::get_object_selection(), draftguitools.gui_rotate.Rotate::get_object_selection(), draftguitools.gui_scale.Scale::get_object_selection(), draftguitools.gui_arcs.Arc_3Points::getPoint(), draftguitools.gui_edit.Edit::keyPressed(), draftguitools.gui_dimensions.Dimension::numericInput(), draftguitools.gui_offset.Offset::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), draftguitools.gui_trimex.Trimex::numericRadius(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_align(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_auto(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_center(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_front(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_move(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_next(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_previous(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_side(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_top(), bimcommands.BimShape2DView.BIM_Shape2DView::proceed(), draftguitools.gui_join.Join::proceed(), draftguitools.gui_subelements.SubelementHighlight::proceed(), draftguitools.gui_draft2sketch.Draft2Sketch::proceed(), draftguitools.gui_downgrade.Downgrade::proceed(), bimcommands.BimSlab.BIM_Slab::proceed(), draftguitools.gui_upgrade.Upgrade::proceed(), draftguitools.gui_facebinders.Facebinder::proceed(), draftguitools.gui_pathtwistedarray.PathTwistedArray::proceed(), draftguitools.gui_shape2dview.Shape2DView::proceed(), draftguitools.gui_clone.Clone::proceed(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_pointarray.PointArray::proceed(), draftguitools.gui_patharray.PathArray::proceed(), draftguitools.gui_trimex.Trimex::proceed(), draftguitools.gui_edit.Edit::proceed(), draftguitools.gui_selectplane.Draft_SelectPlane::reject(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::reject(), drafttaskpanels.task_polararray.TaskPanelPolarArray::reject(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::reject(), and draftguitools.gui_edit.Edit::setTrackers().
GLRender()
void SoFCSelection::GLRender (SoGLRenderAction * action) override
Definition at line 691 of file SoFCSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, colorHighlight, colorSelection, glDepthFunc, selContext, selContext2, SELECTED, selected, and useNewSelection.
GLRenderBelowPath()
void SoFCSelection::GLRenderBelowPath (SoGLRenderAction * action) override
Definition at line 650 of file SoFCSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, colorHighlight, colorSelection, glDepthFunc, selContext, selContext2, SELECTED, selected, and useNewSelection.
GLRenderInPath()
void SoFCSelection::GLRenderInPath (SoGLRenderAction * action) override
Definition at line 734 of file SoFCSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, colorHighlight, colorSelection, glDepthFunc, selContext, selContext2, SELECTED, selected, and useNewSelection.
handleEvent()
void SoFCSelection::handleEvent (SoHandleEventAction * action) override
Definition at line 354 of file SoFCSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::SelectionSingleton::addSelection(), AUTO, Gui::SelectionSingleton::clearSelection(), documentName, SCL.SimpleDataTypes::e, Gui::getMainWindow(), highlightMode, SplineSurface::i, isHighlighted(), objectName, OFF, ON, Gui::printPreselectionInfo(), redrawHighlighted(), Gui::SelectionSingleton::rmvPreselect(), Gui::SelectionSingleton::rmvSelection(), SEL_ON, Gui::Selection(), selectionMode, Gui::SelectionSingleton::setPreselect(), Gui::SelectionSingleton::setPreselectCoord(), Gui::MainWindow::showMessage(), subElementName, and useNewSelection.
initClass()
void SoFCSelection::initClass () static
Definition at line 136 of file SoFCSelection.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
isHighlighted()
SbBool Gui::SoFCSelection::isHighlighted () const inline
Definition at line 88 of file SoFCSelection.h.
Referenced by handleEvent().
readInstance()
SbBool SoFCSelection::readInstance (SoInput * in, unsigned short flags) override protected
Definition at line 921 of file SoFCSelection.cpp.
redrawHighlighted()
void SoFCSelection::redrawHighlighted (SoAction * action, SbBool doHighlight) protected virtual
Empty method in Coin. Can be used by subclasses to be told when status change.
Definition at line 831 of file SoFCSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, AUTO, Gui::SoGLWidgetElement::get(), Gui::SoGLRenderActionElement::get(), and highlightMode.
Referenced by handleEvent().
turnOffCurrentHighlight()
void SoFCSelection::turnOffCurrentHighlight (SoGLRenderAction * action) static
Static method that can be used to turn off the current highlight.
Definition at line 150 of file SoFCSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action.
Member Data Documentation
colorHighlight
SoSFColor Gui::SoFCSelection::colorHighlight
Definition at line 90 of file SoFCSelection.h.
Referenced by applySettings(), doAction(), GLRender(), GLRenderBelowPath(), and GLRenderInPath().
colorSelection
SoSFColor Gui::SoFCSelection::colorSelection
Definition at line 91 of file SoFCSelection.h.
Referenced by applySettings(), doAction(), GLRender(), GLRenderBelowPath(), and GLRenderInPath().
documentName
SoSFString Gui::SoFCSelection::documentName
Definition at line 97 of file SoFCSelection.h.
Referenced by Gui::ViewProviderVRMLObject::attach(), MeshGui::ViewProviderMesh::attach(), doAction(), and handleEvent().
highlightMode
SoSFEnum Gui::SoFCSelection::highlightMode
Definition at line 94 of file SoFCSelection.h.
Referenced by applySettings(), doAction(), handleEvent(), and redrawHighlighted().
objectName
SoSFString Gui::SoFCSelection::objectName
Definition at line 98 of file SoFCSelection.h.
Referenced by Gui::ViewProviderVRMLObject::attach(), MeshGui::ViewProviderMesh::attach(), doAction(), and handleEvent().
selContext
SelContextPtr Gui::SoFCSelection::selContext protected
Definition at line 115 of file SoFCSelection.h.
Referenced by doAction(), GLRender(), GLRenderBelowPath(), and GLRenderInPath().
selContext2
SelContextPtr Gui::SoFCSelection::selContext2 protected
Definition at line 116 of file SoFCSelection.h.
Referenced by GLRender(), GLRenderBelowPath(), and GLRenderInPath().
selected
SoSFEnum Gui::SoFCSelection::selected
Definition at line 93 of file SoFCSelection.h.
Referenced by doAction(), GLRender(), GLRenderBelowPath(), GLRenderInPath(), Path.Dressup.Gui.Tags.HoldingTagMarker::setEnabled(), and Path.Dressup.Gui.Tags.HoldingTagMarker::setSelected().
selectionMode
SoSFEnum Gui::SoFCSelection::selectionMode
Definition at line 95 of file SoFCSelection.h.
Referenced by applySettings(), doAction(), handleEvent(), and Gui::ViewProviderGeometryObject::setSelectable().
style
SoSFEnum Gui::SoFCSelection::style
Definition at line 92 of file SoFCSelection.h.
Referenced by MeshGui::ViewProviderMesh::onChanged().
subElementName
SoSFString Gui::SoFCSelection::subElementName
Definition at line 99 of file SoFCSelection.h.
Referenced by Gui::ViewProviderVRMLObject::attach(), MeshGui::ViewProviderMesh::attach(), doAction(), and handleEvent().
useNewSelection
SoSFBool Gui::SoFCSelection::useNewSelection
Definition at line 100 of file SoFCSelection.h.
Referenced by doAction(), GLRender(), GLRenderBelowPath(), GLRenderInPath(), and handleEvent().
The documentation for this class was generated from the following files:
SoFCSelection.h
SoFCSelection.cpp