FreeCAD: FemGui::DataAlongLineMarker Class Reference
FemGui::DataAlongLineMarker Class Reference
#include <TaskPostBoxes.h>
Signals
void PointsChanged (double x1, double y1, double z1, double x2, double y2, double z2)
Public Member Functions
DataAlongLineMarker (Gui::View3DInventorViewer *view, Fem::FemPostDataAlongLineFilter *obj)
Public Member Functions inherited from FemGui::PointMarker
PointMarker (Gui::View3DInventorViewer *view, App::DocumentObject *obj)
~PointMarker () override
void addPoint (const SbVec3f &)
void clearPoints () const
int countPoints () const
SbVec3f getPoint (int idx) const
void setPoint (int idx, const SbVec3f &pt) const
Gui::View3DInventorViewer * getView () const
App::DocumentObject * getObject () const
template<class T >
T * getObject () const
Protected Member Functions
void customEvent (QEvent *e) override
Protected Member Functions inherited from FemGui::PointMarker
std::string ObjectInvisible ()
Additional Inherited Members
Public Attributes inherited from FemGui::PointMarker
QMetaObject::Connection connSelectPoint
Detailed Description
Definition at line 115 of file TaskPostBoxes.h.
Constructor & Destructor Documentation
DataAlongLineMarker()
DataAlongLineMarker::DataAlongLineMarker (Gui::View3DInventorViewer * view, Fem::FemPostDataAlongLineFilter * obj)
Definition at line 171 of file TaskPostBoxes.cpp.
Member Function Documentation
customEvent()
void DataAlongLineMarker::customEvent (QEvent * e) override protected
Definition at line 176 of file TaskPostBoxes.cpp.
References Gui::Command::Doc, doCommand, FemGui::PointMarker::getObject(), FemGui::PointMarker::getPoint(), FemGui::PointMarker::ObjectInvisible(), and PointsChanged().
PointsChanged
void FemGui::DataAlongLineMarker::PointsChanged (double x1, double y1, double z1, double x2, double y2, double z2) signal
Referenced by customEvent().
The documentation for this class was generated from the following files:
TaskPostBoxes.h
TaskPostBoxes.cpp