FreeCAD: src.Mod.Show.SceneDetails.ObjectClipPlane Namespace Reference
src.Mod.Show.SceneDetails.ObjectClipPlane Namespace Reference
Classes
class ObjectClipPlane
Functions
def getClipPlaneNode (viewprovider, make_if_missing=True)
def placement2plane (placement, offset)
def clipPlane (obj, enable, placement=None, offset=0, tv=None)
Function Documentation
clipPlane()
def src.Mod.Show.SceneDetails.ObjectClipPlane.clipPlane (obj, enable, placement = None, offset = 0, tv = None)
Definition at line 110 of file ObjectClipPlane.py.
getClipPlaneNode()
def src.Mod.Show.SceneDetails.ObjectClipPlane.getClipPlaneNode (viewprovider, make_if_missing = True)
Definition at line 84 of file ObjectClipPlane.py.
References getLength().
Referenced by src.Mod.Show.SceneDetails.ObjectClipPlane.ObjectClipPlane.apply_data(), and src.Mod.Show.SceneDetails.ObjectClipPlane.ObjectClipPlane.scene_value().
placement2plane()
def src.Mod.Show.SceneDetails.ObjectClipPlane.placement2plane (placement, offset)
returns tuple (normal, D) for making coin plane.
Definition at line 103 of file ObjectClipPlane.py.
Referenced by src.Mod.Show.SceneDetails.ObjectClipPlane.ObjectClipPlane.val().