FreeCAD: ifc2x3.ifcsectionproperties Class Reference
ifc2x3.ifcsectionproperties Class Reference
Public Member Functions
def __init__ (self, sectiontype, startprofile, endprofile)
def sectiontype ()
def startprofile ()
def endprofile ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
sectiontype
startprofile
endprofile
Detailed Description
Entity ifcsectionproperties definition.
:param sectiontype
:type sectiontype:ifcsectiontypeenum
:param startprofile
:type startprofile:ifcprofiledef
:param endprofile
:type endprofile:ifcprofiledef
Definition at line 28013 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcsectionproperties.__init__ (self, sectiontype, startprofile, endprofile)
Definition at line 28025 of file ifc2x3.py.
Member Function Documentation
endprofile()
def ifc2x3.ifcsectionproperties.endprofile ()
Definition at line 28059 of file ifc2x3.py.
References ifc2x3.ifcsectionproperties._endprofile, SCL.TypeChecker.check_type(), and ifc2x3.ifcsectionproperties.endprofile.
sectiontype()
def ifc2x3.ifcsectionproperties.sectiontype ()
Definition at line 28031 of file ifc2x3.py.
References ifc2x3.ifcsectionproperties._sectiontype, SCL.TypeChecker.check_type(), and ifc2x3.ifcsectionproperties.sectiontype.
startprofile()
def ifc2x3.ifcsectionproperties.startprofile ()
Definition at line 28045 of file ifc2x3.py.
References ifc2x3.ifcsectionproperties._startprofile, SCL.TypeChecker.check_type(), and ifc2x3.ifcsectionproperties.startprofile.
Member Data Documentation
endprofile
ifc2x3.ifcsectionproperties.endprofile
Definition at line 28028 of file ifc2x3.py.
Referenced by ifc2x3.ifcsectionproperties.endprofile().
sectiontype
ifc2x3.ifcsectionproperties.sectiontype
Definition at line 28026 of file ifc2x3.py.
Referenced by ifc2x3.ifcsectionproperties.sectiontype().
startprofile
ifc2x3.ifcsectionproperties.startprofile
Definition at line 28027 of file ifc2x3.py.
Referenced by ifc2x3.ifcsectionproperties.startprofile().
The documentation for this class was generated from the following file:
ifc2x3.py