FreeCAD: Gui::GraphvizWorker Class Reference
Gui::GraphvizWorker Class Reference
The GraphvizWorker class.
Signals
void svgFileRead (const QByteArray &data)
void error ()
void emitFinished ()
Public Member Functions
GraphvizWorker (QObject *parent=nullptr)
~GraphvizWorker () override
void setData (const QByteArray &data)
void startThread ()
void run () override
QProcess * dotProcess ()
QProcess * unflattenProcess ()
Detailed Description
The GraphvizWorker class.
Implements a QThread class that does the actual conversion from dot to svg. All critical communication is done using queued signals.
Definition at line 64 of file GraphvizView.cpp.
Constructor & Destructor Documentation
GraphvizWorker()
Gui::GraphvizWorker::GraphvizWorker (QObject * parent = nullptr) inline explicit
Definition at line 67 of file GraphvizView.cpp.
~GraphvizWorker()
Gui::GraphvizWorker::~GraphvizWorker () inline override
Definition at line 72 of file GraphvizView.cpp.
Member Function Documentation
dotProcess()
QProcess* Gui::GraphvizWorker::dotProcess () inline
Definition at line 120 of file GraphvizView.cpp.
emitFinished
void Gui::GraphvizWorker::emitFinished () signal
Referenced by Gui::GraphvizView::GraphvizView(), and startThread().
error
void Gui::GraphvizWorker::error () signal
Referenced by Gui::GraphvizView::GraphvizView(), FreeCADInit.FCADLogger::report(), and run().
run()
void Gui::GraphvizWorker::run () inline override
Definition at line 93 of file GraphvizView.cpp.
References error(), App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), and svgFileRead().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femsolver.task.Task::protector(), and startThread().
setData()
void Gui::GraphvizWorker::setData (const QByteArray & data) inline
Definition at line 78 of file GraphvizView.cpp.
startThread()
void Gui::GraphvizWorker::startThread () inline
Definition at line 83 of file GraphvizView.cpp.
References emitFinished(), and run().
svgFileRead
void Gui::GraphvizWorker::svgFileRead (const QByteArray & data) signal
Referenced by Gui::GraphvizView::GraphvizView(), and run().
unflattenProcess()
QProcess* Gui::GraphvizWorker::unflattenProcess () inline
Definition at line 124 of file GraphvizView.cpp.
The documentation for this class was generated from the following file:
GraphvizView.cpp