FreeCAD: Gui::MainWindowPy Class Reference
Gui::MainWindowPy Class Reference
#include <MainWindowPy.h>
Public Member Functions
MainWindowPy (MainWindow *mw)
~MainWindowPy () override
Py::Object repr () override
Py::Object getWindows (const Py::Tuple &)
Py::Object getWindowsOfType (const Py::Tuple &)
Py::Object setActiveWindow (const Py::Tuple &)
Py::Object getActiveWindow (const Py::Tuple &)
Py::Object addWindow (const Py::Tuple &)
Py::Object removeWindow (const Py::Tuple &)
Static Public Member Functions
static void init_type ()
static PyObject * extension_object_new (PyTypeObject *subtype, PyObject *, PyObject *)
static Py::Object createWrapper (MainWindow *mw)
static Py::Object type ()
static Py::ExtensionObject< MainWindowPy > create (MainWindow *mw)
Detailed Description
Definition at line 55 of file MainWindowPy.h.
Constructor & Destructor Documentation
MainWindowPy()
MainWindowPy::MainWindowPy (MainWindow * mw) explicit
Definition at line 100 of file MainWindowPy.cpp.
Referenced by extension_object_new().
~MainWindowPy()
MainWindowPy::~MainWindowPy () override
Definition at line 105 of file MainWindowPy.cpp.
Member Function Documentation
addWindow()
Py::Object MainWindowPy::addWindow (const Py::Tuple & args)
Definition at line 186 of file MainWindowPy.cpp.
References toolbit-attributes::args, and Gui::MDIViewPyWrap::getPyObject().
Referenced by init_type().
create()
Py::ExtensionObject< MainWindowPy > MainWindowPy::create (MainWindow * mw) static
Definition at line 71 of file MainWindowPy.cpp.
References NavigationIndicatorGui::mw, and type().
Referenced by draftguitools.gui_labels.Label::action(), and createWrapper().
createWrapper()
Py::Object MainWindowPy::createWrapper (MainWindow * mw) static
Definition at line 80 of file MainWindowPy.cpp.
References create(), Gui::PythonWrapper::fromQWidget(), Gui::PythonWrapper::loadCoreModule(), Gui::PythonWrapper::loadGuiModule(), Gui::PythonWrapper::loadWidgetsModule(), and NavigationIndicatorGui::mw.
Referenced by Gui::ApplicationPy::sGetMainWindow().
extension_object_new()
PyObject * MainWindowPy::extension_object_new (PyTypeObject * subtype, PyObject * , PyObject *) static
Definition at line 61 of file MainWindowPy.cpp.
References MainWindowPy().
Referenced by init_type().
getActiveWindow()
Py::Object MainWindowPy::getActiveWindow (const Py::Tuple & args)
Definition at line 172 of file MainWindowPy.cpp.
References toolbit-attributes::args, and Gui::MDIView::getPyObject().
Referenced by init_type().
getWindows()
Py::Object MainWindowPy::getWindows (const Py::Tuple & args)
Definition at line 121 of file MainWindowPy.cpp.
References toolbit-attributes::args.
Referenced by init_type().
getWindowsOfType()
Py::Object MainWindowPy::getWindowsOfType (const Py::Tuple & args)
Definition at line 140 of file MainWindowPy.cpp.
References toolbit-attributes::args, and InitGui::t.
Referenced by init_type().
init_type()
void MainWindowPy::init_type () static
Definition at line 43 of file MainWindowPy.cpp.
References addWindow(), extension_object_new(), getActiveWindow(), getWindows(), getWindowsOfType(), removeWindow(), and setActiveWindow().
Referenced by Gui::Application::Application().
removeWindow()
Py::Object MainWindowPy::removeWindow (const Py::Tuple & args)
Definition at line 210 of file MainWindowPy.cpp.
References toolbit-attributes::args.
Referenced by init_type().
repr()
Py::Object MainWindowPy::repr () override
Definition at line 111 of file MainWindowPy.cpp.
References toolbit-attributes::s, and src.Mod.Test.testmakeWireString::String.
setActiveWindow()
Py::Object MainWindowPy::setActiveWindow (const Py::Tuple & args)
Definition at line 162 of file MainWindowPy.cpp.
References toolbit-attributes::args.
Referenced by init_type().
type()
Py::Object MainWindowPy::type () static
Definition at line 66 of file MainWindowPy.cpp.
Referenced by create().
The documentation for this class was generated from the following files:
MainWindowPy.h
MainWindowPy.cpp