FreeCAD: CommandInsertRobot.cpp File Reference
CommandInsertRobot.cpp File Reference
#include "PreCompiled.h"
#include <QMessageBox>
#include <Gui/Application.h>
#include <Gui/Command.h>
#include <Gui/Document.h>
#include <Gui/MainWindow.h>
#include <Gui/Selection.h>
#include <Mod/Robot/App/RobotObject.h>
#include "TrajectorySimulate.h"
Functions
void CreateRobotCommandsInsertRobots ()
Function Documentation
CreateRobotCommandsInsertRobots()
void CreateRobotCommandsInsertRobots ()
Definition at line 290 of file CommandInsertRobot.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().