FreeCAD: PartGui::ViewProviderPartExt Class Reference
PartGui::ViewProviderPartExt Class Reference
#include <ViewProviderExt.h>
Public Member Functions
ViewProviderPartExt ()
constructor
~ViewProviderPartExt () override
destructor
void attach (App::DocumentObject *) override
void setDisplayMode (const char *ModeName) override
set the display mode
std::vector< std::string > getDisplayModes () const override
returns a list of all possible modes
void reload ()
Update the view representation.
bool changeFaceAppearances ()
If no other task is pending it opens a dialog to allow one to change face colors.
void updateData (const App::Property *) override
Restoring view provider from document load
void startRestoring () override
void finishRestoring () override
Selection handling
This group of methods do the selection handling. Here you can define how the selection for your ViewProfider works.
bool useNewSelectionModel () const override
indicates if the ViewProvider use the new Selection model
std::string getElement (const SoDetail *) const override
return a hit element to the selection path or 0
SoDetail * getDetail (const char *) const override
return the coin node detail of the subelement
std::vector< Base::Vector3d > getModelPoints (const SoPickedPoint *) const override
std::vector< Base::Vector3d > getSelectionShape (const char *Element) const override
return the highlight lines for a given element or the whole shape
Highlight handling
This group of methods do the highlighting of elements.
void setHighlightedFaces (const std::vector< App::Material > &materials)
void setHighlightedFaces (const App::PropertyMaterialList &appearance)
void unsetHighlightedFaces ()
void setHighlightedEdges (const std::vector< App::Color > &colors)
void unsetHighlightedEdges ()
void setHighlightedPoints (const std::vector< App::Color > &colors)
void unsetHighlightedPoints ()
Color management methods
std::map< std::string, App::Color > getElementColors (const char *element=nullptr) const override
bool isUpdateForced () const override
void forceUpdate (bool enable=true) override
bool allowOverride (const App::DocumentObject &) const override
Public Member Functions inherited from Gui::ViewProviderGeometryObject
ViewProviderGeometryObject ()
constructor.
~ViewProviderGeometryObject () override
destructor.
bool isSelectable () const override
SoPickedPointList getPickedPoints (const SbVec2s &pos, const View3DInventorViewer &viewer, bool pickAll=false) const
SoPickedPoint * getPickedPoint (const SbVec2s &pos, const View3DInventorViewer &viewer) const
virtual void showBoundingBox (bool)
Public Member Functions inherited from Gui::ViewProviderDragger
ViewProviderDragger ()
constructor.
~ViewProviderDragger () override
destructor.
Base::Placement getTransformOrigin () const
Convenience method to obtain the transform origin.
void setTransformOrigin (const Base::Placement &placement)
Convenience method to set the transform origin.
void resetTransformOrigin ()
Resets transform origin to the object origin.
bool doubleClicked () override
is called by the tree if the user double clicks on the object
ViewProvider * startEditing (int ModNum=0) override
void updatePlacementFromDragger ()
updates placement of object based on dragger position
void updateTransformFromDragger ()
updates transform of object based on dragger position, can be used to preview movement
Base::Placement getObjectPlacement () const
Gets object placement relative to its coordinate system.
Base::Placement getDraggerPlacement () const
Gets current dragger placement, including current dragger movement.
Base::Placement getOriginalDraggerPlacement () const
Gets original dragger placement, without current dragger movement.
void setDraggerPlacement (const Base::Placement &placement)
Sets placement of dragger relative to objects origin.
Public Member Functions inherited from Gui::ViewProviderDocumentObject
ViewProviderDocumentObject ()
constructor.
~ViewProviderDocumentObject () override
destructor.
virtual void reattach (App::DocumentObject *)
void update (const App::Property *) override
void setActiveMode ()
Set the active mode, i.e. the first item of the 'Display' property.
void hide () override
Hide the object in the view.
void show () override
Show the object in the view.
const char * getTransactionText () const override
bool canDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const override
int replaceObject (App::DocumentObject *, App::DocumentObject *) override
bool showInTree () const override
void getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &) const override
Get a list of TaskBoxes associated with this object.
void updateView ()
Run a redraw.
App::DocumentObject * getObject () const
Get the object of this ViewProvider object.
template<class T >
T * getObject () const
Get the object of this ViewProvider object as specified type.
bool canDelete (App::DocumentObject *obj) const override
Asks the view provider if the given object can be deleted.
virtual bool acceptDeletionsInEdit ()
Ask the view provider if it accepts object deletions while in edit.
Gui::Document * getDocument () const
Get the GUI document to this ViewProvider object.
bool getElementPicked (const SoPickedPoint *, std::string &subname) const override
return a hit element given the picked point which contains the full node path
bool getDetailPath (const char *subname, SoFullPath *pPath, bool append, SoDetail *&det) const override
return the coin node detail and path to the node of the subname
int getTreeRank () const
void setTreeRank (int value)
bool removeDynamicProperty (const char *prop) override
App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
virtual ViewProviderDocumentObject * getLinkedViewProvider (std::string *subname=nullptr, bool recursive=false) const
std::string getFullName () const override
void setShowable (bool enable)
bool isShowable () const
void startDefaultEditMode ()
Public Member Functions inherited from Gui::ViewProvider
ViewProvider ()
constructor.
~ViewProvider () override
destructor.
virtual SoSeparator * getRoot () const
SoSwitch * getModeSwitch () const
SoTransform * getTransformNode () const
SoSeparator * getAnnotation ()
virtual SoSeparator * getFrontRoot () const
virtual SoGroup * getChildRoot () const
virtual SoSeparator * getBackRoot () const
virtual bool canAddToSceneGraph () const
Indicate whether to be added to scene graph or not.
virtual bool isPartOfPhysicalObject () const
virtual std::vector< App::DocumentObject * > claimChildren3D () const
int partialRender (const std::vector< std::string > &subelements, bool clear)
Base::BoundBox3d getBoundingBox (const char *subname=nullptr, bool transform=true, MDIView *view=nullptr) const
virtual bool onDelete (const std::vector< std::string > &subNames)
virtual void beforeDelete ()
virtual bool canDragObjects () const
virtual bool canDragObject (App::DocumentObject *) const
virtual bool canDragObjectToTarget (App::DocumentObject *obj, App::DocumentObject *target) const
virtual void dragObject (App::DocumentObject *)
virtual bool canDropObjects () const
virtual bool canDropObject (App::DocumentObject *) const
virtual bool canDragAndDropObject (App::DocumentObject *) const
virtual void dropObject (App::DocumentObject *)
virtual bool acceptReorderingObjects () const
virtual std::string getDropPrefix () const
return a subname referencing the sub-object holding the dropped objects
virtual std::string dropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements)
virtual bool canRemoveChildrenFromRoot () const
std::string getActiveDisplayMode () const
virtual const char * getDefaultDisplayMode () const
get the default display mode
virtual bool isShow () const
checks whether the view provider is visible or not
void setVisible (bool)
bool isVisible () const
void setLinkVisible (bool)
bool isLinkVisible () const
virtual void setOverrideMode (const std::string &mode)
Overrides the display mode with mode.
const std::string getOverrideMode ()
virtual bool selectAll ()
virtual bool keyPressed (bool pressed, int key)
is called when the provider is in edit and a key event occurs. Only ESC ends edit.
virtual bool mouseMove (const SbVec2s &cursorPos, View3DInventorViewer *viewer)
is called when the provider is in edit and the mouse is moved
virtual bool mouseButtonPressed (int button, bool pressed, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
is called when the Provider is in edit and the mouse is clicked
virtual bool mouseWheelEvent (int delta, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
virtual QIcon getIcon () const
deliver the icon shown in the tree view
virtual QIcon mergeColorfulOverlayIcons (const QIcon &orig) const
virtual std::vector< App::DocumentObject * > claimChildren () const
virtual std::vector< App::DocumentObject * > claimChildrenRecursive () const
bool isUpdatesEnabled () const
void setUpdatesEnabled (bool enable)
unsigned long getStatus () const
return the status bits
bool testStatus (ViewStatus pos) const
void setStatus (ViewStatus pos, bool on)
std::string toString () const
virtual void setElementColors (const std::map< std::string, App::Color > &colors)
bool isEditing () const
void finishEditing ()
virtual void setTransformation (const Base::Matrix4D &rcMatrix)
set the viewing transformation of the provider
virtual void setTransformation (const SbMatrix &rcMatrix)
virtual MDIView * getMDIView () const
void Restore (Base::XMLReader &reader) override
bool isRestoring ()
void addDisplayMaskMode (SoNode *node, const char *type)
Adds a new display mask mode.
void setDisplayMaskMode (const char *type)
Activates the display mask mode type.
SoNode * getDisplayMaskMode (const char *type) const
Get the node to the display mask mode type.
std::vector< std::string > getDisplayMaskModes () const
Returns a list of added display mask modes.
void setDefaultMode (int)
int getDefaultMode () const
virtual void setRenderCacheMode (int)
Public Member Functions inherited from App::TransactionalObject
TransactionalObject ()
Constructor.
~TransactionalObject () override
Public Member Functions inherited from App::ExtensionContainer
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
Property * getPropertyByName (const char *name) const override
find a property by its name
template<typename T >
T * getPropertyByName (const char *name) const
find a property by its name, dynamic cased to specified type
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop) override
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Attributes
App::PropertyFloatConstraint Deviation
App::PropertyBool ControlPoints
App::PropertyAngle AngularDeflection
App::PropertyEnumeration Lighting
App::PropertyEnumeration DrawStyle
App::PropertyFloatConstraint PointSize
App::PropertyColor PointColor
App::PropertyMaterial PointMaterial
App::PropertyColorList PointColorArray
App::PropertyFloatConstraint LineWidth
App::PropertyColor LineColor
App::PropertyMaterial LineMaterial
App::PropertyColorList LineColorArray
Public Attributes inherited from Gui::ViewProviderGeometryObject
App::PropertyPercent Transparency
App::PropertyMaterialList ShapeAppearance
App::PropertyBool BoundingBox
App::PropertyBool Selectable
Public Attributes inherited from Gui::ViewProviderDragger
App::PropertyPlacement TransformOrigin
Public Attributes inherited from Gui::ViewProviderDocumentObject
App::PropertyEnumeration DisplayMode
App::PropertyBool Visibility
App::PropertyBool ShowInTree
App::PropertyEnumeration OnTopWhenSelected
App::PropertyEnumeration SelectionStyle
Public Attributes inherited from Gui::ViewProvider
boost::signals2::signal< void()> signalChangeIcon
signal on icon change
boost::signals2::signal< void(const QString &)> signalChangeToolTip
signal on tooltip change
boost::signals2::signal< void(const QString &)> signalChangeStatusTip
signal on status tip change
boost::signals2::signal< void(bool, Gui::HighlightMode)> signalChangeHighlight
signal on highlight change
Edit methods
SoMaterialBinding * pcFaceBind
SoMaterialBinding * pcLineBind
SoMaterialBinding * pcPointBind
SoMaterial * pcLineMaterial
SoMaterial * pcPointMaterial
SoDrawStyle * pcLineStyle
SoDrawStyle * pcPointStyle
SoShapeHints * pShapeHints
SoCoordinate3 * coords
SoBrepFaceSet * faceset
SoNormal * norm
SoNormalBinding * normb
SoBrepEdgeSet * lineset
SoBrepPointSet * nodeset
bool VisualTouched
bool NormalsFromUV
void setupContextMenu (QMenu *, QObject *, const char *) override
set up the context-menu with the supported edit modes
PyObject * getPyObject () override
Get the python wrapper for that ViewProvider.
bool setEdit (int ModNum) override
is called by the document when the provider goes in edit mode
void unsetEdit (int ModNum) override
is called when you lose the edit mode
void onChanged (const App::Property *prop) override
get called by the container whenever a property has been changed
bool loadParameter ()
void updateVisual ()
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container. This method is typically called if the property on file has changed its name in more recent versions.
Additional Inherited Members
Public Types inherited from Gui::ViewProvider
enum EditMode { Default = 0, Transform, Cutting, Color }
Public Types inherited from App::ExtensionContainer
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Static Public Member Functions inherited from Gui::ViewProviderDragger
static void updateTransform (const Base::Placement &from, SoTransform *to)
Static Public Member Functions inherited from Gui::ViewProvider
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
static SbMatrix convert (const Base::Matrix4D &rcMatrix)
static Base::Matrix4D convert (const SbMatrix &sbMat)
static void eventCallback (void *ud, SoEventCallback *node)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions inherited from Gui::ViewProviderGeometryObject
void setSelectable (bool Selectable=true)
virtual unsigned long getBoundColor () const
void setCoinAppearance (const App::Material &source)
Protected Member Functions inherited from Gui::ViewProviderDragger
void setEditViewer (View3DInventorViewer *, int ModNum) override
adjust viewer settings when editing a view provider
void unsetEditViewer (View3DInventorViewer *) override
restores viewer settings when leaving editing mode
bool forwardToLink ()
virtual TaskView::TaskDialog * getTransformDialog ()
Protected Member Functions inherited from Gui::ViewProviderDocumentObject
Gui::MDIView * getActiveView () const
Gui::MDIView * getEditingView () const
Gui::MDIView * getInventorView () const
Gui::MDIView * getViewOfNode (SoNode *node) const
void onBeforeChange (const App::Property *prop) override
get called before the value is changed
SoNode * findFrontRootOfType (const SoType &type) const
bool isAttachedToDocument () const override
const char * detachFromDocument () override
void onPropertyStatusChanged (const App::Property &prop, unsigned long oldStatus) override
get called when a property status has changed
void setModeSwitch () override
Turn on mode switch.
void addDefaultAction (QMenu *, const QString &)
Protected Member Functions inherited from Gui::ViewProvider
virtual QIcon mergeGreyableOverlayIcons (const QIcon &orig) const
int getEditingMode () const
return the edit mode or -1 if nothing is being edited
bool checkRecursion (SoNode *)
SoPickedPoint * getPointOnRay (const SbVec2s &pos, const View3DInventorViewer *viewer) const
SoPickedPoint * getPointOnRay (const SbVec3f &pos, const SbVec3f &dir, const View3DInventorViewer *viewer) const
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual void onEarlyChange (const Property *)
virtual const PropertyData & getPropertyData () const
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::ViewProviderGeometryObject
SoMaterial * pcShapeMaterial {nullptr}
SoFCBoundingBox * pcBoundingBox {nullptr}
SoSwitch * pcBoundSwitch {nullptr}
SoBaseColor * pcBoundColor {nullptr}
SoPickStyle * pickStyle {nullptr}
App::Material materialAppearance
Protected Attributes inherited from Gui::ViewProviderDragger
CoinPtr< SoFCCSysDragger > csysDragger = nullptr
ViewProvider * forwardedViewProvider = nullptr
Protected Attributes inherited from Gui::ViewProviderDocumentObject
App::DocumentObject * pcObject {nullptr}
Gui::Document * pcDocument {nullptr}
Protected Attributes inherited from Gui::ViewProvider
SoSeparator * pcRoot
The root Separator of the ViewProvider.
SoTransform * pcTransform
this is transformation for the provider
const char * sPixmap
SoSwitch * pcModeSwitch
this is the mode switch, all the different viewing modes are collected here
SoSeparator * pcAnnotation {nullptr}
The root separator for annotations.
ViewProviderPy * pyViewObject {nullptr}
std::string overrideMode
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Detailed Description
Definition at line 63 of file ViewProviderExt.h.
Constructor & Destructor Documentation
ViewProviderPartExt()
ViewProviderPartExt::ViewProviderPartExt ()
constructor
Definition at line 125 of file ViewProviderExt.cpp.
References ADD_PROPERTY_TYPE, App::Material::ambientColor, AngularDeflection, coords, Deviation, App::Material::diffuseColor, DrawStyle, App::Material::emissiveColor, SCL.SimpleDataTypes::f, faceset, App::GetApplication(), ParameterGrp::GetBool(), Gui::ViewParams::getDefaultShapeLineColor(), Gui::ViewParams::getDefaultShapeLineWidth(), Gui::ViewParams::getDefaultShapePointSize(), Gui::ViewParams::getDefaultShapeVertexColor(), ParameterGrp::GetFloat(), App::Application::GetParameterGroupByPath(), App::PropertyFloat::getValue(), App::PropertyColor::getValue(), App::Extension::initExtension(), Gui::ViewParams::instance(), Lighting, LineColor, LineColorArray, LineMaterial, lineset, LineWidth, loadParameter(), App::PropertyFloatConstraint::Constraints::LowerBound, KDL::max(), nodeset, norm, NormalsFromUV, normb, pcFaceBind, pcLineBind, pcLineMaterial, pcLineStyle, pcPointBind, pcPointMaterial, pcPointStyle, PointColor, PointColorArray, PointMaterial, PointSize, App::Prop_None, pShapeHints, App::Color::set(), App::PropertyQuantityConstraint::setConstraints(), App::PropertyFloatConstraint::setConstraints(), App::PropertyEnumeration::setEnums(), App::Material::shininess, App::Material::specularColor, Gui::ViewProvider::sPixmap, App::Property::touch(), App::Material::transparency, and VisualTouched.
~ViewProviderPartExt()
ViewProviderPartExt::~ViewProviderPartExt () override
destructor
Definition at line 257 of file ViewProviderExt.cpp.
References coords, faceset, lineset, nodeset, norm, normb, pcFaceBind, pcLineBind, pcLineMaterial, pcLineStyle, pcPointBind, pcPointMaterial, pcPointStyle, and pShapeHints.
Member Function Documentation
allowOverride()
bool ViewProviderPartExt::allowOverride (const App::DocumentObject &) const override virtual
Allow this class to be used as an override for the original view provider of the given object
See also
App::DocumentObject::getViewProviderNameOverride()
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 407 of file ViewProviderExt.cpp.
attach()
void ViewProviderPartExt::attach (App::DocumentObject * pcObject) override virtual
Attaches the document object to this view provider.
Reimplemented from Gui::ViewProviderGeometryObject.
Reimplemented in PartDesignGui::ViewProviderSubShapeBinder, PartDesignGui::ViewProviderShapeBinder, SketcherGui::ViewProviderSketch, PartDesignGui::ViewProviderBoolean, PartDesignGui::ViewProviderAddSub, PartDesignGui::ViewProviderPrimitive, and PartDesignGui::ViewProviderBody.
Definition at line 413 of file ViewProviderExt.cpp.
References Gui::ViewProvider::addDisplayMaskMode(), coords, faceset, Gui::ViewProviderTextureExtension::getAppearance(), lineset, nodeset, norm, normb, MeshCore::MeshIO::OFF, pcFaceBind, pcLineBind, pcLineMaterial, pcLineStyle, Gui::ViewProvider::pcModeSwitch, pcPointBind, pcPointMaterial, pcPointStyle, Gui::ViewProvider::pcRoot, Gui::ViewProviderGeometryObject::pcShapeMaterial, pShapeHints, and Gui::ViewProviderFaceTexture::setup().
Referenced by PartGui::ViewProvider2DObjectGrid::attach(), PartDesignGui::ViewProviderAddSub::attach(), PartDesignGui::ViewProviderBoolean::attach(), and PartGui::ViewProviderCustom::updateData().
changeFaceAppearances()
bool ViewProviderPartExt::changeFaceAppearances ()
If no other task is pending it opens a dialog to allow one to change face colors.
Definition at line 901 of file ViewProviderExt.cpp.
References Gui::ControlSingleton::activeDialog(), Gui::SelectionSingleton::clearSelection(), Gui::Control(), Gui::Selection(), and Gui::ControlSingleton::showDialog().
Referenced by setEdit().
finishRestoring()
void ViewProviderPartExt::finishRestoring () override virtual
Reimplemented from Gui::ViewProviderDocumentObject.
Reimplemented in SketcherGui::ViewProviderSketch.
Definition at line 881 of file ViewProviderExt.cpp.
References Gui::ViewProviderDocumentObject::finishRestoring(), App::PropertyListsT< T, ListT, ParentT >::getSize(), and onChanged().
forceUpdate()
void ViewProviderPartExt::forceUpdate (bool enable = true) override virtual
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 1340 of file ViewProviderExt.cpp.
References Gui::ViewProvider::isShow(), updateVisual(), and VisualTouched.
getDetail()
SoDetail * ViewProviderPartExt::getDetail (const char *) const override virtual
return the coin node detail of the subelement
Reimplemented from Gui::ViewProvider.
Definition at line 545 of file ViewProviderExt.cpp.
References Part::TopoShape::getElementTypeAndIndex(), nodeset, and Path.Post.scripts.grbl_post::type.
getDisplayModes()
std::vector< std::string > ViewProviderPartExt::getDisplayModes () const override virtual
returns a list of all possible modes
Reimplemented from Gui::ViewProvider.
Reimplemented in PartGui::ViewProviderPrism, PartGui::ViewProviderRegularPolygon, PartGui::ViewProviderHelixParametric, PartGui::ViewProviderRuledSurface, PartGui::ViewProviderSphereParametric, PartGui::ViewProviderWedge, PartGui::ViewProviderSpiralParametric, PartGui::ViewProviderEllipsoid, PartDesignGui::ViewProviderBody, PartGui::ViewProviderLineParametric, PartGui::ViewProviderPlaneParametric, PartGui::ViewProviderPointParametric, and PartGui::ViewProviderTorusParametric.
Definition at line 507 of file ViewProviderExt.cpp.
getElement()
std::string ViewProviderPartExt::getElement (const SoDetail * detail) const override virtual
return a hit element to the selection path or 0
Reimplemented from Gui::ViewProvider.
Definition at line 521 of file ViewProviderExt.cpp.
References nodeset, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by getModelPoints().
getElementColors()
std::map< std::string, App::Color > ViewProviderPartExt::getElementColors (const char * element = nullptr) const override virtual
Reimplemented from Gui::ViewProvider.
Definition at line 674 of file ViewProviderExt.cpp.
References App::PropertyMaterialList::getDiffuseColor(), App::PropertyListsT< T, ListT, ParentT >::getSize(), App::PropertyInteger::getValue(), App::PropertyColor::getValue(), SplineSurface::i, LineColor, LineColorArray, PointColor, PointColorArray, App::Color::setTransparency(), Gui::ViewProviderGeometryObject::ShapeAppearance, and Gui::ViewProviderGeometryObject::Transparency.
getModelPoints()
std::vector< Base::Vector3d > ViewProviderPartExt::getModelPoints (const SoPickedPoint * pp) const override virtual
Reimplemented from Gui::ViewProvider.
Definition at line 570 of file ViewProviderExt.cpp.
References getElement(), Gui::ViewProviderDocumentObject::getObject(), Part::Feature::getTopoShape(), buildPsets::p, TestSpreadsheet::v, and SurfaceTests.TestBlendCurve::vec.
getPyObject()
PyObject * ViewProviderPartExt::getPyObject () override virtual
Get the python wrapper for that ViewProvider.
Reimplemented from Gui::ViewProviderGeometryObject.
Reimplemented in PartDesignGui::ViewProvider.
Definition at line 275 of file ViewProviderExt.cpp.
References Gui::ViewProvider::pyViewObject.
getSelectionShape()
std::vector< Base::Vector3d > ViewProviderPartExt::getSelectionShape (const char * Element) const override virtual
return the highlight lines for a given element or the whole shape
Reimplemented from Gui::ViewProvider.
Definition at line 615 of file ViewProviderExt.cpp.
handleChangedPropertyName()
void ViewProviderPartExt::handleChangedPropertyName (Base::XMLReader & reader, const char * TypeName, const char * PropName) override protected virtual
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container. This method is typically called if the property on file has changed its name in more recent versions.
The default implementation does nothing.
Parameters
reader The XML stream to read from.
TypeName Name of property type on file.
PropName Name of property on file that does not exist in the container anymore.
Reimplemented from Gui::ViewProviderGeometryObject.
Definition at line 1351 of file ViewProviderExt.cpp.
References Base::Persistence::getClassTypeId(), Gui::ViewProviderGeometryObject::handleChangedPropertyName(), TechDrawTools.TaskFillTemplateFields::reader, and App::PropertyColorList::Restore().
isUpdateForced()
bool PartGui::ViewProviderPartExt::isUpdateForced () const inline override virtual
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 142 of file ViewProviderExt.h.
Referenced by onChanged(), and updateData().
loadParameter()
bool ViewProviderPartExt::loadParameter () protected
Definition at line 830 of file ViewProviderExt.cpp.
References AngularDeflection, Deviation, App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetFloat(), App::Application::GetParameterGroupByPath(), App::PropertyQuantity::getValue(), App::PropertyFloat::getValue(), NormalsFromUV, App::PropertyQuantity::setValue(), and App::PropertyFloat::setValue().
Referenced by reload(), and ViewProviderPartExt().
onChanged()
void ViewProviderPartExt::onChanged (const App::Property * prop) override protected virtual
get called by the container whenever a property has been changed
Reimplemented from Gui::ViewProviderGeometryObject.
Reimplemented in SketcherGui::ViewProviderSketch, PartDesignGui::ViewProviderSubShapeBinder, PartDesignGui::ViewProviderBoolean, SketcherGui::ViewProviderCustom, PartGui::ViewProviderCustom, PartDesignGui::ViewProvider, and PartDesignGui::ViewProviderBody.
Definition at line 284 of file ViewProviderExt.cpp.
References App::Material::ambientColor, AngularDeflection, App::Color::b, SCL.SimpleDataTypes::c, importers.importIFCmulticore::colors, Deviation, App::Material::diffuseColor, DrawStyle, App::Material::emissiveColor, App::Color::g, App::PropertyInteger::getValue(), App::PropertyEnumeration::getValue(), App::PropertyFloat::getValue(), App::PropertyBool::getValue(), App::PropertyColor::getValue(), App::PropertyMaterial::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), SplineSurface::i, isUpdateForced(), Lighting, LineColor, LineColorArray, LineMaterial, LineWidth, App::Property::NoModify, pcLineMaterial, pcLineStyle, pcPointMaterial, pcPointStyle, PointColor, PointColorArray, PointMaterial, PointSize, pShapeHints, App::Color::r, App::PropertyMaterial::setDiffuseColor(), App::PropertyMaterialList::setDiffuseColors(), setHighlightedEdges(), setHighlightedFaces(), setHighlightedPoints(), App::PropertyMaterialList::setTransparencies(), App::PropertyMaterialList::setTransparency(), App::PropertyListsT< T, ListT, ParentT >::setValue(), App::PropertyColor::setValue(), Gui::ViewProviderGeometryObject::ShapeAppearance, App::Material::shininess, App::Material::specularColor, Gui::ViewProviderGeometryObject::Transparency, App::Material::transparency, updateVisual(), Gui::ViewProviderDocumentObject::Visibility, and VisualTouched.
Referenced by finishRestoring(), PartDesignGui::ViewProviderBody::onChanged(), PartDesignGui::ViewProvider::onChanged(), PartGui::ViewProvider2DObjectGrid::onChanged(), and PartGui::ViewProviderCustom::onChanged().
reload()
void ViewProviderPartExt::reload ()
Update the view representation.
Definition at line 850 of file ViewProviderExt.cpp.
References loadParameter(), and updateVisual().
setDisplayMode()
void ViewProviderPartExt::setDisplayMode (const char * ModeName) override virtual
set the display mode
If you add new viewing modes in getDisplayModes() then you need to reimplement also seDisplaytMode() to handle these new modes by setting the appropriate display mode.
Reimplemented from Gui::ViewProvider.
Reimplemented in PartDesignGui::ViewProviderBody.
Definition at line 493 of file ViewProviderExt.cpp.
References Gui::ViewProvider::setDisplayMaskMode().
Referenced by PartDesignGui::ViewProviderBoolean::onChanged(), PartDesignGui::ViewProviderBody::setDisplayMode(), PartGui::ViewProviderCustom::updateData(), and SketcherGui::ViewProviderCustom::updateData().
setEdit()
bool ViewProviderPartExt::setEdit (int ModNum) override protected virtual
is called by the document when the provider goes in edit mode
Reimplemented from Gui::ViewProviderDragger.
Reimplemented in SketcherGui::ViewProviderSketch, PartGui::ViewProviderThickness, PartGui::ViewProviderOffset, PartGui::ViewProviderChamfer, PartDesignGui::ViewProvider, PartDesignGui::ViewProviderBoolean, PartDesignGui::ViewProviderLoft, PartDesignGui::ViewProviderPipe, PartDesignGui::ViewProviderSubShapeBinder, PartGui::ViewProviderFillet, PartDesignGui::ViewProviderHelix, PartDesignGui::ViewProviderHole, PartDesignGui::ViewProviderPrimitive, PartGui::ViewProviderMirror, PartGui::ViewProviderPrimitive, PartGui::ViewProviderProjectOnSurface, PartDesignGui::ViewProviderBase, PartDesignGui::ViewProviderShapeBinder, PartDesignGui::ViewProviderDressUp, PartDesignGui::ViewProviderTransformed, SurfaceGui::ViewProviderFilling, SurfaceGui::ViewProviderSections, SurfaceGui::ViewProviderGeomFillSurface, and PartGui::ViewProviderImport.
Definition at line 914 of file ViewProviderExt.cpp.
References changeFaceAppearances(), and Gui::ViewProviderDragger::setEdit().
Referenced by PartGui::ViewProviderImport::setEdit(), PartDesignGui::ViewProviderBase::setEdit(), PartGui::ViewProviderPrimitive::setEdit(), PartGui::ViewProviderMirror::setEdit(), PartGui::ViewProviderProjectOnSurface::setEdit(), PartDesignGui::ViewProviderHole::setEdit(), PartGui::ViewProviderFillet::setEdit(), PartDesignGui::ViewProviderBoolean::setEdit(), PartDesignGui::ViewProvider::setEdit(), PartGui::ViewProviderChamfer::setEdit(), PartGui::ViewProviderOffset::setEdit(), and PartGui::ViewProviderThickness::setEdit().
setHighlightedEdges()
void ViewProviderPartExt::setHighlightedEdges (const std::vector< App::Color > & colors)
Definition at line 769 of file ViewProviderExt.cpp.
References SCL.SimpleDataTypes::b, importers.importIFCmulticore::colors, toolbit-attributes::g, Gui::ViewProviderDocumentObject::getObject(), SplineSurface::i, lineset, MeshCore::MeshIO::OVERALL, pcLineBind, pcLineMaterial, MeshCore::MeshIO::PER_FACE, Gui::ViewProvider::testStatus(), App::DocumentObject::touch(), and App::TouchOnColorChange.
Referenced by SurfaceGui::ViewProviderGeomFillSurface::highlightReferences(), SurfaceGui::ViewProviderSections::highlightReferences(), SurfaceGui::ViewProviderFilling::highlightReferences(), PartDesignGui::ViewProviderDressUp::highlightReferences(), onChanged(), and updateVisual().
setHighlightedFaces() [1/2]
void ViewProviderPartExt::setHighlightedFaces (const App::PropertyMaterialList & appearance)
Definition at line 669 of file ViewProviderExt.cpp.
References App::PropertyListsT< T, ListT, ParentT >::getValues(), and setHighlightedFaces().
setHighlightedFaces() [2/2]
void ViewProviderPartExt::setHighlightedFaces (const std::vector< App::Material > & materials)
Definition at line 620 of file ViewProviderExt.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::ViewProviderTextureExtension::activateMaterial(), faceset, Gui::ViewProviderDocumentObject::getObject(), SplineSurface::i, importers.importIFCmulticore::materials, MeshCore::MeshIO::OVERALL, PartGui::SoBrepFaceSet::partIndex, pcFaceBind, Gui::ViewProviderGeometryObject::pcShapeMaterial, Gui::ViewProviderGeometryObject::setCoinAppearance(), Gui::ViewProvider::testStatus(), App::DocumentObject::touch(), and App::TouchOnColorChange.
Referenced by SurfaceGui::ViewProviderSections::highlightReferences(), SurfaceGui::ViewProviderFilling::highlightReferences(), PartDesignGui::ViewProviderDressUp::highlightReferences(), onChanged(), setHighlightedFaces(), and updateVisual().
setHighlightedPoints()
void ViewProviderPartExt::setHighlightedPoints (const std::vector< App::Color > & colors)
Definition at line 806 of file ViewProviderExt.cpp.
References SCL.SimpleDataTypes::b, importers.importIFCmulticore::colors, toolbit-attributes::g, Gui::ViewProviderDocumentObject::getObject(), SplineSurface::i, MeshCore::MeshIO::OVERALL, pcPointBind, pcPointMaterial, MeshCore::MeshIO::PER_VERTEX, Gui::ViewProvider::testStatus(), App::DocumentObject::touch(), and App::TouchOnColorChange.
Referenced by SurfaceGui::ViewProviderSections::highlightReferences(), SurfaceGui::ViewProviderFilling::highlightReferences(), onChanged(), and updateVisual().
setupContextMenu()
void ViewProviderPartExt::setupContextMenu (QMenu * menu, QObject * receiver, const char * method) override virtual
set up the context-menu with the supported edit modes
Reimplemented from Gui::ViewProviderDragger.
Reimplemented in SketcherGui::ViewProviderSketch, PartDesignGui::ViewProvider, PartDesignGui::ViewProviderSubShapeBinder, PartDesignGui::ViewProviderPrimitive, PartGui::ViewProviderProjectOnSurface, PartDesignGui::ViewProviderHole, PartDesignGui::ViewProviderBase, PartDesignGui::ViewProviderBody, PartGui::ViewProviderThickness, PartGui::ViewProviderOffset, PartGui::ViewProviderChamfer, PartDesignGui::ViewProviderBoolean, PartDesignGui::ViewProviderPipe, PartDesignGui::ViewProviderLoft, PartGui::ViewProviderFillet, PartDesignGui::ViewProviderDraft, PartDesignGui::ViewProviderChamfer, PartDesignGui::ViewProviderFillet, PartDesignGui::ViewProviderThickness, PartGui::ViewProviderHelixParametric, PartGui::ViewProviderPrimitive, PartDesignGui::ViewProviderMultiTransform, PartDesignGui::ViewProviderGroove, PartDesignGui::ViewProviderHelix, PartDesignGui::ViewProviderMirrored, PartDesignGui::ViewProviderPocket, PartDesignGui::ViewProviderPolarPattern, PartDesignGui::ViewProviderRevolution, PartDesignGui::ViewProviderScaled, PartGui::ViewProviderMirror, PartDesignGui::ViewProviderLinearPattern, PartDesignGui::ViewProviderPad, PartDesignGui::ViewProviderShapeBinder, PartGui::ViewProviderSpiralParametric, PartDesignGui::ViewProviderDressUp, PartDesignGui::ViewProviderTransformed, SurfaceGui::ViewProviderFilling, SurfaceGui::ViewProviderSections, and SurfaceGui::ViewProviderGeomFillSurface.
Definition at line 893 of file ViewProviderExt.cpp.
References Gui::BitmapFactory(), NavigationIndicatorGui::menu, Gui::ViewProvider::mergeGreyableOverlayIcons(), and Gui::ViewProviderDragger::setupContextMenu().
Referenced by SurfaceGui::ViewProviderGeomFillSurface::setupContextMenu(), SurfaceGui::ViewProviderSections::setupContextMenu(), SurfaceGui::ViewProviderFilling::setupContextMenu(), PartGui::ViewProviderMirror::setupContextMenu(), PartGui::ViewProviderPrimitive::setupContextMenu(), PartDesignGui::ViewProviderHole::setupContextMenu(), PartGui::ViewProviderProjectOnSurface::setupContextMenu(), PartGui::ViewProviderFillet::setupContextMenu(), PartGui::ViewProviderChamfer::setupContextMenu(), PartGui::ViewProviderOffset::setupContextMenu(), and PartGui::ViewProviderThickness::setupContextMenu().
startRestoring()
void ViewProviderPartExt::startRestoring () override virtual
Reimplemented from Gui::ViewProviderDocumentObject.
Reimplemented in SketcherGui::ViewProviderSketch.
Definition at line 876 of file ViewProviderExt.cpp.
References Gui::ViewProviderDocumentObject::startRestoring().
unsetEdit()
void ViewProviderPartExt::unsetEdit (int ModNum) override protected virtual
is called when you lose the edit mode
Reimplemented from Gui::ViewProviderDragger.
Reimplemented in SketcherGui::ViewProviderSketch, PartGui::ViewProviderThickness, PartGui::ViewProviderOffset, PartGui::ViewProviderChamfer, PartDesignGui::ViewProvider, PartDesignGui::ViewProviderLoft, PartDesignGui::ViewProviderPipe, PartGui::ViewProviderFillet, PartDesignGui::ViewProviderHelix, PartDesignGui::ViewProviderPrimitive, PartGui::ViewProviderMirror, PartGui::ViewProviderPrimitive, PartGui::ViewProviderProjectOnSurface, PartDesignGui::ViewProviderBase, PartDesignGui::ViewProviderShapeBinder, PartDesignGui::ViewProviderTransformed, SurfaceGui::ViewProviderFilling, SurfaceGui::ViewProviderSections, SurfaceGui::ViewProviderGeomFillSurface, and PartGui::ViewProviderImport.
Definition at line 927 of file ViewProviderExt.cpp.
References Gui::ViewProviderDragger::unsetEdit().
Referenced by PartGui::ViewProviderImport::unsetEdit(), SurfaceGui::ViewProviderGeomFillSurface::unsetEdit(), SurfaceGui::ViewProviderSections::unsetEdit(), SurfaceGui::ViewProviderFilling::unsetEdit(), PartDesignGui::ViewProviderBase::unsetEdit(), PartDesignGui::ViewProviderShapeBinder::unsetEdit(), PartGui::ViewProviderPrimitive::unsetEdit(), PartGui::ViewProviderMirror::unsetEdit(), PartGui::ViewProviderProjectOnSurface::unsetEdit(), PartGui::ViewProviderFillet::unsetEdit(), PartDesignGui::ViewProvider::unsetEdit(), PartGui::ViewProviderChamfer::unsetEdit(), PartGui::ViewProviderOffset::unsetEdit(), and PartGui::ViewProviderThickness::unsetEdit().
unsetHighlightedEdges()
void ViewProviderPartExt::unsetHighlightedEdges ()
Definition at line 800 of file ViewProviderExt.cpp.
References LineMaterial, MeshCore::MeshIO::OVERALL, pcLineBind, and App::Property::touch().
Referenced by SurfaceGui::ViewProviderGeomFillSurface::highlightReferences(), SurfaceGui::ViewProviderSections::highlightReferences(), SurfaceGui::ViewProviderFilling::highlightReferences(), and PartDesignGui::ViewProviderDressUp::highlightReferences().
unsetHighlightedFaces()
void ViewProviderPartExt::unsetHighlightedFaces ()
Definition at line 763 of file ViewProviderExt.cpp.
References Gui::ViewProviderGeometryObject::ShapeAppearance, App::Property::touch(), and Gui::ViewProviderGeometryObject::Transparency.
Referenced by SurfaceGui::ViewProviderSections::highlightReferences(), SurfaceGui::ViewProviderFilling::highlightReferences(), PartDesignGui::ViewProviderDressUp::highlightReferences(), and PartDesignGui::ViewProviderExtrude::highlightShapeFaces().
unsetHighlightedPoints()
void ViewProviderPartExt::unsetHighlightedPoints ()
Definition at line 825 of file ViewProviderExt.cpp.
References PointColorArray, and App::Property::touch().
Referenced by SurfaceGui::ViewProviderSections::highlightReferences(), and SurfaceGui::ViewProviderFilling::highlightReferences().
updateData()
void ViewProviderPartExt::updateData (const App::Property * prop) override virtual
Reimplemented from Gui::ViewProviderGeometryObject.
Reimplemented in PartDesignGui::ViewProviderBody, SketcherGui::ViewProviderSketch, PartGui::ViewProviderChamfer, PartGui::ViewProviderFillet, PartGui::ViewProviderRuledSurface, PartDesignGui::ViewProviderAddSub, PartDesignGui::ViewProviderPrimitive, SketcherGui::ViewProviderCustom, PartGui::ViewProviderCustom, and PartDesignGui::ViewProvider.
Definition at line 856 of file ViewProviderExt.cpp.
References faceset, App::Property::getName(), App::PropertyBool::getValue(), isUpdateForced(), MeshCore::MeshIO::OVERALL, PartGui::SoBrepFaceSet::partIndex, pcFaceBind, Gui::ViewProviderGeometryObject::updateData(), updateVisual(), Gui::ViewProviderDocumentObject::Visibility, and VisualTouched.
Referenced by PartDesignGui::ViewProviderBody::updateData(), PartGui::ViewProvider2DObjectGrid::updateData(), PartDesignGui::ViewProvider::updateData(), PathGui::ViewProviderArea::updateData(), PartGui::ViewProviderMultiFuse::updateData(), PartGui::ViewProviderRuledSurface::updateData(), PartGui::ViewProviderBoolean::updateData(), PathGui::ViewProviderAreaView::updateData(), PartGui::ViewProviderFillet::updateData(), PartGui::ViewProviderCompound::updateData(), PartGui::ViewProviderMultiCommon::updateData(), and PartGui::ViewProviderChamfer::updateData().
updateVisual()
void ViewProviderPartExt::updateVisual () protected
Definition at line 937 of file ViewProviderExt.cpp.
References Path.Post.scripts.dynapath_4060_post::action, KDL::Add(), AngularDeflection, Base::Console(), coords, Deviation, Base::TimeElapsed::diffTimeF(), SCL.SimpleDataTypes::e, faceset, FC_ERR, toolbit-attributes::g, App::DocumentObject::getFullName(), Gui::ViewProviderDocumentObject::getObject(), Part::Tools::getPointNormals(), Part::Feature::getShape(), App::PropertyQuantity::getValue(), App::PropertyFloat::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Handle(), SplineSurface::i, RobotExample::l, LineColorArray, lineset, Base::ConsoleSingleton::Log(), M_PI, Mesh2Shape::mesh, nodeset, Gui::SoSelectionElementAction::None, norm, NormalsFromUV, src.Mod.Test.testPathArray::orient, buildPsets::p, PartGui::SoBrepFaceSet::partIndex, Gui::ViewProviderDocumentObject::pcObject, PointColorArray, setHighlightedEdges(), setHighlightedFaces(), setHighlightedPoints(), Gui::ViewProviderGeometryObject::ShapeAppearance, draftgeoutils.general::v1(), VisualTouched, xMax, xMin, yMax, and yMin.
Referenced by forceUpdate(), PartDesignGui::ViewProvider::makeTemporaryVisible(), onChanged(), reload(), and updateData().
useNewSelectionModel()
bool PartGui::ViewProviderPartExt::useNewSelectionModel () const inline override virtual
indicates if the ViewProvider use the new Selection model
Reimplemented from Gui::ViewProvider.
Definition at line 114 of file ViewProviderExt.h.
Member Data Documentation
AngularDeflection
App::PropertyAngle PartGui::ViewProviderPartExt::AngularDeflection
Definition at line 76 of file ViewProviderExt.h.
Referenced by loadParameter(), onChanged(), PartDesignGui::ViewProviderAddSub::updateAddSubShapeIndicator(), updateVisual(), and ViewProviderPartExt().
ControlPoints
App::PropertyBool PartGui::ViewProviderPartExt::ControlPoints
Definition at line 75 of file ViewProviderExt.h.
coords
SoCoordinate3* PartGui::ViewProviderPartExt::coords protected
Definition at line 180 of file ViewProviderExt.h.
Referenced by attach(), PartGui::ViewProviderCurveNet::computeEdges(), FeaturePython.ViewProviderCircleSet::updateData(), updateVisual(), ViewProviderPartExt(), and ~ViewProviderPartExt().
Deviation
App::PropertyFloatConstraint PartGui::ViewProviderPartExt::Deviation
Definition at line 74 of file ViewProviderExt.h.
Referenced by loadParameter(), onChanged(), PartDesignGui::ViewProviderAddSub::updateAddSubShapeIndicator(), updateVisual(), and ViewProviderPartExt().
DrawStyle
App::PropertyEnumeration PartGui::ViewProviderPartExt::DrawStyle
Definition at line 78 of file ViewProviderExt.h.
Referenced by onChanged(), and ViewProviderPartExt().
faceset
SoBrepFaceSet* PartGui::ViewProviderPartExt::faceset protected
Definition at line 181 of file ViewProviderExt.h.
Referenced by attach(), setHighlightedFaces(), updateData(), updateVisual(), ViewProviderPartExt(), and ~ViewProviderPartExt().
Lighting
App::PropertyEnumeration PartGui::ViewProviderPartExt::Lighting
Definition at line 77 of file ViewProviderExt.h.
Referenced by onChanged(), and ViewProviderPartExt().
LineColor
App::PropertyColor PartGui::ViewProviderPartExt::LineColor
Definition at line 86 of file ViewProviderExt.h.
Referenced by SketcherGui::ViewProviderSketch::finishRestoring(), getElementColors(), SurfaceGui::ViewProviderGeomFillSurface::highlightReferences(), SurfaceGui::ViewProviderSections::highlightReferences(), SurfaceGui::ViewProviderFilling::highlightReferences(), PartDesignGui::ViewProviderDressUp::highlightReferences(), PartDesignGui::ViewProviderShapeBinder::highlightReferences(), PartDesignGui::ViewProviderSubShapeBinder::onChanged(), onChanged(), SketcherGui::ViewProviderSketch::onChanged(), and ViewProviderPartExt().
LineColorArray
App::PropertyColorList PartGui::ViewProviderPartExt::LineColorArray
Definition at line 88 of file ViewProviderExt.h.
Referenced by getElementColors(), FemGui::ViewProviderFemConstraintOnBoundary::highlightReferences(), PartDesignGui::ViewProviderDressUp::highlightReferences(), PartDesignGui::ViewProviderShapeBinder::highlightReferences(), onChanged(), PartDesignGui::ViewProviderBody::unifyVisualProperty(), updateVisual(), and ViewProviderPartExt().
LineMaterial
App::PropertyMaterial PartGui::ViewProviderPartExt::LineMaterial
Definition at line 87 of file ViewProviderExt.h.
Referenced by onChanged(), unsetHighlightedEdges(), and ViewProviderPartExt().
lineset
SoBrepEdgeSet* PartGui::ViewProviderPartExt::lineset protected
Definition at line 184 of file ViewProviderExt.h.
Referenced by attach(), PartGui::ViewProviderCurveNet::computeEdges(), setHighlightedEdges(), updateVisual(), ViewProviderPartExt(), and ~ViewProviderPartExt().
LineWidth
App::PropertyFloatConstraint PartGui::ViewProviderPartExt::LineWidth
Definition at line 85 of file ViewProviderExt.h.
Referenced by PartDesignGui::ViewProviderSubShapeBinder::onChanged(), onChanged(), and ViewProviderPartExt().
nodeset
SoBrepPointSet* PartGui::ViewProviderPartExt::nodeset protected
Definition at line 185 of file ViewProviderExt.h.
Referenced by attach(), getDetail(), getElement(), updateVisual(), ViewProviderPartExt(), and ~ViewProviderPartExt().
norm
SoNormal* PartGui::ViewProviderPartExt::norm protected
Definition at line 182 of file ViewProviderExt.h.
Referenced by attach(), PartGui::ViewProviderCurveNet::handleEvent(), PartGui::ViewProviderMirror::setEdit(), PartGui::ViewProviderMirror::unsetEdit(), updateVisual(), ViewProviderPartExt(), and ~ViewProviderPartExt().
NormalsFromUV
bool PartGui::ViewProviderPartExt::NormalsFromUV protected
Definition at line 188 of file ViewProviderExt.h.
Referenced by loadParameter(), updateVisual(), and ViewProviderPartExt().
normb
SoNormalBinding* PartGui::ViewProviderPartExt::normb protected
Definition at line 183 of file ViewProviderExt.h.
Referenced by attach(), ViewProviderPartExt(), and ~ViewProviderPartExt().
pcFaceBind
SoMaterialBinding* PartGui::ViewProviderPartExt::pcFaceBind protected
Definition at line 171 of file ViewProviderExt.h.
Referenced by attach(), setHighlightedFaces(), updateData(), ViewProviderPartExt(), and ~ViewProviderPartExt().
pcLineBind
SoMaterialBinding* PartGui::ViewProviderPartExt::pcLineBind protected
Definition at line 172 of file ViewProviderExt.h.
Referenced by attach(), setHighlightedEdges(), unsetHighlightedEdges(), ViewProviderPartExt(), and ~ViewProviderPartExt().
pcLineMaterial
SoMaterial* PartGui::ViewProviderPartExt::pcLineMaterial protected
Definition at line 174 of file ViewProviderExt.h.
Referenced by PartGui::ViewProviderCurveNet::attach(), attach(), PartGui::ViewProviderCurveNet::computeEdges(), onChanged(), setHighlightedEdges(), ViewProviderPartExt(), and ~ViewProviderPartExt().
pcLineStyle
SoDrawStyle* PartGui::ViewProviderPartExt::pcLineStyle protected
Definition at line 176 of file ViewProviderExt.h.
Referenced by PartGui::ViewProviderCurveNet::attach(), attach(), PartGui::ViewProviderCurveNet::computeEdges(), PartGui::ViewProviderCurveNet::handleEvent(), onChanged(), ViewProviderPartExt(), and ~ViewProviderPartExt().
pcPointBind
SoMaterialBinding* PartGui::ViewProviderPartExt::pcPointBind protected
Definition at line 173 of file ViewProviderExt.h.
Referenced by attach(), setHighlightedPoints(), ViewProviderPartExt(), and ~ViewProviderPartExt().
pcPointMaterial
SoMaterial* PartGui::ViewProviderPartExt::pcPointMaterial protected
Definition at line 175 of file ViewProviderExt.h.
Referenced by PartGui::ViewProviderCurveNet::attach(), attach(), PartGui::ViewProviderCurveNet::computeVertices(), onChanged(), setHighlightedPoints(), ViewProviderPartExt(), and ~ViewProviderPartExt().
pcPointStyle
SoDrawStyle* PartGui::ViewProviderPartExt::pcPointStyle protected
Definition at line 177 of file ViewProviderExt.h.
Referenced by attach(), PartGui::ViewProviderCurveNet::computeVertices(), onChanged(), ViewProviderPartExt(), and ~ViewProviderPartExt().
PointColor
App::PropertyColor PartGui::ViewProviderPartExt::PointColor
Definition at line 81 of file ViewProviderExt.h.
Referenced by SketcherGui::ViewProviderSketch::finishRestoring(), getElementColors(), SurfaceGui::ViewProviderSections::highlightReferences(), SurfaceGui::ViewProviderFilling::highlightReferences(), PartDesignGui::ViewProviderSubShapeBinder::onChanged(), onChanged(), SketcherGui::ViewProviderSketch::onChanged(), and ViewProviderPartExt().
PointColorArray
App::PropertyColorList PartGui::ViewProviderPartExt::PointColorArray
Definition at line 83 of file ViewProviderExt.h.
Referenced by getElementColors(), FemGui::ViewProviderFemConstraintOnBoundary::highlightReferences(), onChanged(), PartDesignGui::ViewProviderBody::unifyVisualProperty(), unsetHighlightedPoints(), updateVisual(), and ViewProviderPartExt().
PointMaterial
App::PropertyMaterial PartGui::ViewProviderPartExt::PointMaterial
Definition at line 82 of file ViewProviderExt.h.
Referenced by onChanged(), and ViewProviderPartExt().
PointSize
App::PropertyFloatConstraint PartGui::ViewProviderPartExt::PointSize
Definition at line 80 of file ViewProviderExt.h.
Referenced by onChanged(), ViewProviderPartExt(), and SketcherGui::ViewProviderSketch::ViewProviderSketch().
pShapeHints
SoShapeHints* PartGui::ViewProviderPartExt::pShapeHints protected
Definition at line 178 of file ViewProviderExt.h.
Referenced by attach(), onChanged(), ViewProviderPartExt(), and ~ViewProviderPartExt().
VisualTouched
bool PartGui::ViewProviderPartExt::VisualTouched protected
Definition at line 187 of file ViewProviderExt.h.
Referenced by forceUpdate(), PartDesignGui::ViewProvider::makeTemporaryVisible(), onChanged(), updateData(), updateVisual(), and ViewProviderPartExt().
The documentation for this class was generated from the following files:
ViewProviderExt.h
ViewProviderExt.cpp