FreeCAD: Path.Op.Adaptive Namespace Reference
Path.Op.Adaptive Namespace Reference
Classes
class PathAdaptive
Functions
def convertTo2d (pathArray)
def sceneDrawPath (path, color=(0, 0, 1))
def sceneClean ()
def discretize (edge, flipDirection=False)
def CalcHelixConePoint (height, cur_z, radius, angle)
def GenerateGCode (op, obj, adaptiveResults, helixDiameter)
def Execute (op, obj)
def SetupProperties ()
def Create (name, obj=None, parentJob=None)
Variables
Part
FeatureExtensions
DraftGeomUtils
translate
sceneGraph
scenePathNodes
topZ
Function Documentation
CalcHelixConePoint()
def Path.Op.Adaptive.CalcHelixConePoint (height, cur_z, radius, angle)
Definition at line 111 of file Adaptive.py.
Referenced by Path.Op.Adaptive.GenerateGCode().
convertTo2d()
def Path.Op.Adaptive.convertTo2d (pathArray)
Definition at line 60 of file Adaptive.py.
Referenced by Path.Op.Adaptive.Execute().
Create()
def Path.Op.Adaptive.Create (name, obj = None, parentJob = None)
Create(name) ... Creates and returns a Adaptive operation.
Definition at line 1174 of file Adaptive.py.
discretize()
def Path.Op.Adaptive.discretize (edge, flipDirection = False)
Definition at line 103 of file Adaptive.py.
Referenced by Path.Op.Gui.FeatureExtension._Extension.createExtensionSoSwitch(), draftgeoutils.wires.curvetowire(), and Path.Op.Adaptive.Execute().
Execute()
def Path.Op.Adaptive.Execute (op, obj)
Definition at line 609 of file Adaptive.py.
References Path.Geom.combineHorizontalFaces(), Path.Op.Adaptive.convertTo2d(), Path.Op.Adaptive.discretize(), Path.Op.Adaptive.GenerateGCode(), Path.Log.info(), Path.Op.Adaptive.sceneClean(), and Path.Op.Adaptive.sceneDrawPath().
Referenced by init_pyarea().
GenerateGCode()
def Path.Op.Adaptive.GenerateGCode (op, obj, adaptiveResults, helixDiameter)
Definition at line 119 of file Adaptive.py.
References Path.Op.Adaptive.CalcHelixConePoint().
Referenced by Path.Op.Adaptive.Execute().
sceneClean()
def Path.Op.Adaptive.sceneClean ()
Definition at line 96 of file Adaptive.py.
Referenced by Path.Op.Adaptive.Execute().
sceneDrawPath()
def Path.Op.Adaptive.sceneDrawPath (path, color = (0, 0, 1))
Definition at line 76 of file Adaptive.py.
Referenced by Path.Op.Adaptive.Execute().
SetupProperties()
def Path.Op.Adaptive.SetupProperties ()
Definition at line 1150 of file Adaptive.py.
Variable Documentation
DraftGeomUtils
Path.Op.Adaptive.DraftGeomUtils
Definition at line 47 of file Adaptive.py.
FeatureExtensions
Path.Op.Adaptive.FeatureExtensions
Definition at line 46 of file Adaptive.py.
Part
Path.Op.Adaptive.Part
Definition at line 44 of file Adaptive.py.
sceneGraph
Path.Op.Adaptive.sceneGraph
Definition at line 71 of file Adaptive.py.
scenePathNodes
Path.Op.Adaptive.scenePathNodes
Definition at line 72 of file Adaptive.py.
topZ
Path.Op.Adaptive.topZ
Definition at line 73 of file Adaptive.py.
translate
Path.Op.Adaptive.translate
Definition at line 57 of file Adaptive.py.