FreeCAD: PartGui::PlanePrimitive Class Reference
PartGui::PlanePrimitive Class Reference
#include <DlgPrimitives.h>
Public Member Functions
PlanePrimitive (std::shared_ptr< Ui_DlgPrimitives > ui, Part::Plane *feature=nullptr)
const char * getDefaultName () const override
QString create (const QString &objectName, const QString &placement) const override
QString change (const QString &objectName, const QString &placement) const override
void changeValue (QObject *) override
Public Member Functions inherited from PartGui::AbstractPrimitive
AbstractPrimitive (Part::Primitive *feature=nullptr)
~AbstractPrimitive () override=default
bool hasValidPrimitive () const
Additional Inherited Members
Protected Member Functions inherited from PartGui::AbstractPrimitive
void connectSignalMapper (QSignalMapper *mapper)
Protected Attributes inherited from PartGui::AbstractPrimitive
App::DocumentObjectWeakPtrT featurePtr
Detailed Description
Definition at line 100 of file DlgPrimitives.h.
Constructor & Destructor Documentation
PlanePrimitive()
PlanePrimitive::PlanePrimitive (std::shared_ptr< Ui_DlgPrimitives > ui, Part::Plane * feature = nullptr)
Definition at line 242 of file DlgPrimitives.cpp.
References PartGui::connectMapSignalMapper(), PartGui::AbstractPrimitive::connectSignalMapper(), App::PropertyQuantity::getQuantityValue(), Part::Plane::Length, Gui::QuantitySpinBox::valueChanged(), and Part::Plane::Width.
Member Function Documentation
change()
QString PlanePrimitive::change (const QString & objectName, const QString & placement) const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 282 of file DlgPrimitives.cpp.
References PartGui::safeQuantityQString().
changeValue()
void PlanePrimitive::changeValue (QObject * widget) override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 294 of file DlgPrimitives.cpp.
References App::DocumentObjectWeakPtrT::expired(), PartGui::AbstractPrimitive::featurePtr, App::DocumentObjectWeakPtrT::get(), and WorkingPlane::plane.
create()
QString PlanePrimitive::create (const QString & objectName, const QString & placement) const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 267 of file DlgPrimitives.cpp.
References PartGui::safeQuantityQString().
getDefaultName()
const char * PlanePrimitive::getDefaultName () const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 262 of file DlgPrimitives.cpp.
The documentation for this class was generated from the following files:
DlgPrimitives.h
DlgPrimitives.cpp