FreeCAD: Gui::Dialog::DlgSettingsUI Class Reference
Gui::Dialog::DlgSettingsUI Class Reference
#include <DlgSettingsUI.h>
Public Member Functions
DlgSettingsUI (QWidget *parent=nullptr)
~DlgSettingsUI () override
void saveSettings () override
void loadSettings () override
void loadStyleSheet ()
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Static Public Member Functions
static void attachObserver ()
Protected Member Functions
void changeEvent (QEvent *e) override
void populateStylesheets (const char *key, const char *path, PrefComboBox *combo, const char *def, QStringList filter=QStringList())
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
The DlgSettingsUI class implements a preference page to change theme settings.
Author
Pierre-Louis Boyer
Definition at line 61 of file DlgSettingsUI.h.
Constructor & Destructor Documentation
DlgSettingsUI()
DlgSettingsUI::DlgSettingsUI (QWidget * parent = nullptr) explicit
Constructs a DlgSettingsUI which is a child of 'parent', with the name 'name' and widget flags set to 'f'
Definition at line 43 of file DlgSettingsUI.cpp.
~DlgSettingsUI()
DlgSettingsUI::~DlgSettingsUI () override default
Destroys the object and frees any allocated resources
Member Function Documentation
attachObserver()
void DlgSettingsUI::attachObserver () static
Definition at line 200 of file DlgSettingsUI.cpp.
References Gui::ParamHandlers::addDelayedHandler(), Gui::ParamHandlers::addHandler(), and buildPsets::handler.
changeEvent()
void DlgSettingsUI::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 178 of file DlgSettingsUI.cpp.
References SCL.SimpleDataTypes::e, and loadStyleSheet().
loadSettings()
void DlgSettingsUI::loadSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 83 of file DlgSettingsUI.cpp.
References loadStyleSheet().
loadStyleSheet()
void DlgSettingsUI::loadStyleSheet ()
Definition at line 111 of file DlgSettingsUI.cpp.
References populateStylesheets().
Referenced by changeEvent(), and loadSettings().
populateStylesheets()
void DlgSettingsUI::populateStylesheets (const char * key, const char * path, PrefComboBox * combo, const char * def, QStringList filter = QStringList()) protected
Definition at line 117 of file DlgSettingsUI.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), Gui::PrefWidget::onRestore(), and Path.Preferences::searchPaths().
Referenced by loadStyleSheet().
saveSettings()
void DlgSettingsUI::saveSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 55 of file DlgSettingsUI.cpp.
The documentation for this class was generated from the following files:
DlgSettingsUI.h
DlgSettingsUI.cpp