FreeCAD: DlgExpressionInput.cpp File Reference
DlgExpressionInput.cpp File Reference
#include "PreCompiled.h"
#include <QApplication>
#include <QMenu>
#include <QMouseEvent>
#include <QTreeWidget>
#include <fmt/format.h>
#include <App/Application.h>
#include <App/Document.h>
#include <App/DocumentObject.h>
#include <App/ExpressionParser.h>
#include <App/VarSet.h>
#include <Base/Tools.h>
#include "DlgExpressionInput.h"
#include "ui_DlgExpressionInput.h"
#include "Application.h"
#include "Command.h"
#include "Tools.h"
#include "ExpressionBinding.h"
#include "BitmapFactory.h"
#include "ViewProviderDocumentObject.h"
#include "moc_DlgExpressionInput.cpp"
Classes
class Binding
Functions
static void getVarSetsDocument (std::vector< App::VarSet * > &varSets, App::Document *doc)
static std::vector< App::VarSet * > getAllVarSets ()
static bool isNamePropOk (const QString &nameProp, App::DocumentObject *obj, std::stringstream &message)
static QString getValue (QTreeWidgetItem *item, int role)
static void addGroupsVarSetComboBox (App::VarSet *varSet, QTreeWidgetItem *varSetItem)
static void addVarSetsVarSetComboBox (std::vector< App::VarSet * > &varSets, QTreeWidgetItem *docItem)
static void addDocVarSetComboBox (App::Document *doc, QPixmap &docIcon, QTreeWidgetItem *rootItem)
static QTreeWidget * createVarSetTreeWidget ()
static bool isNameGroupOk (const QString &nameGroup, std::stringstream &message)
Variables
static const bool NO_CHECK_EXPR = false
static const int ROLE_DOC = Qt::UserRole
static const int ROLE_VARSET_NAME = Qt::UserRole + 1
static const int ROLE_VARSET_LABEL = Qt::UserRole + 2
static const int ROLE_GROUP = Qt::UserRole + 3
Function Documentation
addDocVarSetComboBox()
static void addDocVarSetComboBox (App::Document * doc, QPixmap & docIcon, QTreeWidgetItem * rootItem) static
Definition at line 570 of file DlgExpressionInput.cpp.
References addVarSetsVarSetComboBox(), toolbit-attributes::doc, getVarSetsDocument(), ROLE_DOC, and App::Document::TempDoc.
Referenced by createVarSetTreeWidget().
addGroupsVarSetComboBox()
static void addGroupsVarSetComboBox (App::VarSet * varSet, QTreeWidgetItem * varSetItem) static
Definition at line 529 of file DlgExpressionInput.cpp.
References App::ExtensionContainer::getPropertyList(), ROLE_DOC, ROLE_GROUP, ROLE_VARSET_LABEL, and ROLE_VARSET_NAME.
Referenced by addVarSetsVarSetComboBox().
addVarSetsVarSetComboBox()
static void addVarSetsVarSetComboBox (std::vector< App::VarSet * > & varSets, QTreeWidgetItem * docItem) static
Definition at line 554 of file DlgExpressionInput.cpp.
References addGroupsVarSetComboBox(), Gui::Application::Instance, ROLE_DOC, ROLE_VARSET_LABEL, and ROLE_VARSET_NAME.
Referenced by addDocVarSetComboBox().
createVarSetTreeWidget()
static QTreeWidget* createVarSetTreeWidget () static
Definition at line 588 of file DlgExpressionInput.cpp.
References addDocVarSetComboBox(), Gui::BitmapFactory(), toolbit-attributes::doc, App::GetApplication(), and App::Application::getDocuments().
getAllVarSets()
static std::vector<App::VarSet*> getAllVarSets () static
Definition at line 144 of file DlgExpressionInput.cpp.
References toolbit-attributes::doc, App::GetApplication(), App::Application::getDocuments(), and getVarSetsDocument().
getValue()
static QString getValue (QTreeWidgetItem * item, int role) static
Definition at line 459 of file DlgExpressionInput.cpp.
Referenced by Gui::Dialog::TransformStrategy::acceptDataTransform(), StdCmdPlacement::activated(), WorkingPlane.PlaneGui::align_view(), Gui::InputField::apply(), Gui::Dialog::TransformStrategy::applyViewTransform(), Gui::PropertyEditor::PropertyRotationItem::assignProperty(), Gui::PropertyEditor::PropertyPlacementItem::assignProperty(), WorkingPlane.PlaneGui::auto_align(), Gui::ViewProviderLink::callDraggerProxy(), WorkingPlane.PlaneGui::center_on_view(), BimSelect.CyclicObjectSelector::cycleSelectableObjects(), SpreadsheetGui::SheetModel::data(), importDXF::export(), Fem::FemPostSmoothFilterExtension::extensionOnChanged(), PartDesignGui::TaskRevolutionParameters::fillAxisCombo(), PartDesignGui::TaskExtrudeParameters::fillDirectionCombo(), draftfunctions.svg::format_point(), draftutils.gui_utils::get_bbox(), draftfunctions.svg::get_svg(), draftviewproviders.view_label.ViewProviderLabel::get_text_size(), draftguitools.gui_snapper.Snapper::getApparentPoint(), App::PropertyFileIncluded::getExchangeTempFile(), Spreadsheet::Cell::getFormattedQuantity(), draftguitools.gui_trackers.lineTracker::getLength(), PartDesignGui::ComboLinks::getLink(), App::PropertyEnumeration::getPathValue(), App::PropertyVector::getPyPathValue(), App::PropertyEnumeration::getPyPathValue(), StdDevCollector::getQuantity(), TechDraw::DrawViewSpreadsheet::getSheetImage(), draftguitools.gui_trackers.rectangleTracker::getSize(), Gui::SoFCBoundingBox::GLRender(), Gui::ViewProviderLink::initDraggingPlacement(), PartDesignGui::isAnyNonPartDesignLinksTo(), Part::AttachExtension::isAttacherActive(), Materials::PropertyMaterial::isSame(), App::PropertyQuantity::isSame(), App::PropertyInteger::isSame(), App::PropertyVector::isSame(), App::PropertyPath::isSame(), App::PropertyMatrix::isSame(), App::PropertyPlacement::isSame(), App::PropertyFloat::isSame(), App::PropertyFont::isSame(), App::PropertyBool::isSame(), App::PropertyColor::isSame(), App::PropertyMaterial::isSame(), SketcherGui::ViewProviderSketch::mouseButtonPressed(), SketcherGui::ViewProviderSketch::mouseMove(), draftguitools.gui_points.Point::move(), draftguitools.gui_polararray.PolarArray::move(), draftguitools.gui_circulararray.CircularArray::move(), FemGui::BoxWidget::onChange(), FemGui::CylinderWidget::onChange(), FemGui::PlaneWidget::onChange(), FemGui::SphereWidget::onChange(), draftviewproviders.view_base.ViewProviderDraft::onChanged(), draftguitools.gui_trackers.lineTracker::p1(), draftguitools.gui_trackers.rectangleTracker::p1(), draftguitools.gui_trackers.archDimTracker::p1(), draftguitools.gui_trackers.lineTracker::p2(), draftguitools.gui_trackers.rectangleTracker::p2(), draftguitools.gui_trackers.archDimTracker::p2(), draftguitools.gui_trackers.rectangleTracker::p3(), draftguitools.gui_trackers.rectangleTracker::p4(), importers.importWebGL::populate_camera(), Gui::Gui::GestureNavigationStyle ::AwaitingMoveState::react(), PartGui::SoBrepFaceSet::VBO::render(), Gui::Dialog::TransformStrategy::resetViewTransform(), App::PropertyEnumeration::Restore(), BimSelect.CyclicObjectSelector::selectObject(), WorkingPlane.PlaneGui::set_to_view(), Path.Base.Gui.SetupSheetOpPrototype._PropertyEnumEditor::setEditorData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyBoolEditor::setEditorData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyStringEditor::setEditorData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyAngleEditor::setEditorData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyLengthEditor::setEditorData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyPercentEditor::setEditorData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyIntegerEditor::setEditorData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyFloatEditor::setEditorData(), Path.Base.Gui.SetupSheetOpPrototype._PropertyFileEditor::setEditorData(), App::PropertyInteger::setPathValue(), Sketcher::PropertyConstraintList::setPathValue(), App::PropertyFloat::setPathValue(), App::PropertyBool::setPathValue(), draftguitools.gui_trackers.archDimTracker::setString(), WorkingPlane.Plane::setup(), Gui::PropertyEditor::PropertyVectorDistanceItem::setX(), Gui::PropertyEditor::PropertyVectorDistanceItem::setY(), Gui::PropertyEditor::PropertyVectorDistanceItem::setZ(), PartGui::ViewProviderSplineExtension::showControlPoints(), Gui::PropertyEditor::PropertyMatrixItem::toolTip(), Gui::PropertyEditor::PropertyRotationItem::toolTip(), Gui::PropertyEditor::PropertyPlacementItem::toolTip(), Gui::PropertyEditor::PropertyMaterialItem::toolTip(), bimcommands.BimWindow.Arch_Window::update(), Gui::ViewProviderVRMLObject::updateData(), PartGui::ViewProviderCurveNet::updateData(), Gui::ViewProviderAnnotation::updateData(), Gui::ViewProviderDragger::updateData(), PartGui::ViewProviderBoolean::updateData(), PathGui::ViewProviderAreaView::updateData(), Gui::ViewProviderInventorObject::updateData(), Gui::ViewProviderAnnotationLabel::updateData(), ArchPanel.ViewProviderPanelSheet::updateData(), draftguitools.gui_edit.Edit::updateTrackerAndGhost(), Gui::PropertyEditor::PropertyStringItem::value(), Gui::PropertyEditor::PropertyFontItem::value(), Gui::PropertyEditor::PropertyFloatItem::value(), Gui::PropertyEditor::PropertyFloatConstraintItem::value(), Gui::PropertyEditor::PropertyBoolItem::value(), Gui::PropertyEditor::PropertyVectorItem::value(), Gui::PropertyEditor::PropertyVectorListItem::value(), Gui::PropertyEditor::PropertyVectorDistanceItem::value(), Gui::PropertyEditor::PropertyMatrixItem::value(), Gui::PropertyEditor::PropertyRotationItem::value(), Gui::PropertyEditor::PropertyPlacementItem::value(), Gui::PropertyEditor::PropertyColorItem::value(), Gui::PropertyEditor::PropertyMaterialItem::value(), Gui::PropertyEditor::PropertyFileItem::value(), Gui::PropertyEditor::PropertyPathItem::value(), Gui::PropertyEditor::PropertyTransientFileItem::value(), draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::writeCamera(), and ArchBuildingPart.ViewProviderBuildingPart::writeCamera().
getVarSetsDocument()
static void getVarSetsDocument (std::vector< App::VarSet * > & varSets, App::Document * doc) static
Definition at line 135 of file DlgExpressionInput.cpp.
References toolbit-attributes::doc.
Referenced by addDocVarSetComboBox(), and getAllVarSets().
isNameGroupOk()
static bool isNameGroupOk (const QString & nameGroup, std::stringstream & message) static
Definition at line 664 of file DlgExpressionInput.cpp.
References Base::Tools::getIdentifier().
isNamePropOk()
static bool isNamePropOk (const QString & nameProp, App::DocumentObject * obj, std::stringstream & message) static
Definition at line 420 of file DlgExpressionInput.cpp.
References Base::Tools::getIdentifier(), App::ExtensionContainer::getPropertyByName(), App::ExpressionParser::isTokenAConstant(), and App::ExpressionParser::isTokenAUnit().
Variable Documentation
NO_CHECK_EXPR
const bool NO_CHECK_EXPR = false static
Definition at line 323 of file DlgExpressionInput.cpp.
ROLE_DOC
const int ROLE_DOC = Qt::UserRole static
Definition at line 454 of file DlgExpressionInput.cpp.
Referenced by addDocVarSetComboBox(), addGroupsVarSetComboBox(), and addVarSetsVarSetComboBox().
ROLE_GROUP
const int ROLE_GROUP = Qt::UserRole + 3 static
Definition at line 457 of file DlgExpressionInput.cpp.
Referenced by addGroupsVarSetComboBox().
ROLE_VARSET_LABEL
const int ROLE_VARSET_LABEL = Qt::UserRole + 2 static
Definition at line 456 of file DlgExpressionInput.cpp.
Referenced by addGroupsVarSetComboBox(), and addVarSetsVarSetComboBox().
ROLE_VARSET_NAME
const int ROLE_VARSET_NAME = Qt::UserRole + 1 static
Definition at line 455 of file DlgExpressionInput.cpp.
Referenced by addGroupsVarSetComboBox(), and addVarSetsVarSetComboBox().