FreeCAD: Part::FaceMakerBullseye::FaceDriller Class Reference
Part::FaceMakerBullseye::FaceDriller Class Reference
The FaceDriller class is similar to BRepBuilderAPI_MakeFace, except that it is tolerant to wire orientation (wires are oriented as needed automatically).
#include <FaceMakerBullseye.h>
Public Member Functions
FaceDriller (const gp_Pln &plane, TopoDS_Wire outerWire)
bool hitTest (const gp_Pnt &point) const
hitTest: returns True if point is on the face
void addHole (TopoDS_Wire w)
const TopoDS_Face & Face () const
Static Public Member Functions
static int getWireDirection (const gp_Pln &plane, const TopoDS_Wire &w)
wireDirection: determines direction of wire with respect to myPlane.
Detailed Description
The FaceDriller class is similar to BRepBuilderAPI_MakeFace, except that it is tolerant to wire orientation (wires are oriented as needed automatically).
Definition at line 112 of file FaceMakerBullseye.h.
Constructor & Destructor Documentation
FaceDriller()
FaceMakerBullseye::FaceDriller::FaceDriller (const gp_Pln & plane, TopoDS_Wire outerWire)
Definition at line 137 of file FaceMakerBullseye.cpp.
References getWireDirection(), and WorkingPlane::plane.
Member Function Documentation
addHole()
void FaceMakerBullseye::FaceDriller::addHole (TopoDS_Wire w)
Definition at line 168 of file FaceMakerBullseye.cpp.
References Part::FaceMakerBullseye::myPlane, and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by Part::FaceMakerBullseye::Build_Essence().
Face()
const TopoDS_Face& Part::FaceMakerBullseye::FaceDriller::Face () const inline
Definition at line 125 of file FaceMakerBullseye.h.
getWireDirection()
int FaceMakerBullseye::FaceDriller::getWireDirection (const gp_Pln & plane, const TopoDS_Wire & w) static
wireDirection: determines direction of wire with respect to myPlane.
Parameters
w
Returns
1 = CCW (suits as outer wire), -1 = CW (suits as hole)
Definition at line 178 of file FaceMakerBullseye.cpp.
References WorkingPlane::plane.
Referenced by FaceDriller().
hitTest()
bool FaceMakerBullseye::FaceDriller::hitTest (const gp_Pnt & point) const
hitTest: returns True if point is on the face
Parameters
point
Definition at line 152 of file FaceMakerBullseye.cpp.
References buildPsets::u, and TestSpreadsheet::v.
The documentation for this class was generated from the following files:
FaceMakerBullseye.h
FaceMakerBullseye.cpp