FreeCAD: TechDrawGui::Rez Class Reference
TechDrawGui::Rez Class Reference
Functions to handle mm resolution conversion.
#include <Rez.h>
Static Public Member Functions
static double getParameter (void)
static double getRezFactor (void)
static void setRezFactor (double f)
static double guiX (double x)
static Base::Vector3d guiX (Base::Vector3d v)
static Base::Vector2d guiX (Base::Vector3d v, bool planar)
static QPointF guiX (QPointF p)
static double appX (double x)
static Base::Vector3d appX (Base::Vector3d v)
static QPointF appX (QPointF p)
static QPointF guiPt (QPointF p)
static QPointF appPt (QPointF p)
static QRectF guiRect (QRectF r)
static QSize guiSize (QSize s)
static QSize appSize (QSize s)
Detailed Description
Functions to handle mm resolution conversion.
Definition at line 59 of file Rez.h.
Member Function Documentation
appPt()
QPointF Rez::appPt (QPointF p) static
Definition at line 93 of file Rez.cpp.
References buildPsets::p.
appSize()
QSize Rez::appSize (QSize s) static
Definition at line 111 of file Rez.cpp.
References toolbit-attributes::s.
appX() [1/3]
Base::Vector3d Rez::appX (Base::Vector3d v) static
Definition at line 75 of file Rez.cpp.
References TestSpreadsheet::v.
appX() [2/3]
double Rez::appX (double x) static
Definition at line 70 of file Rez.cpp.
References MovieTool::x.
Referenced by TechDrawGui::QGIViewBalloon::balloonLabelDragFinished(), TechDrawGui::TaskRichAnno::commonFeatureUpdate(), TechDrawGui::TaskRichAnno::createAnnoFeature(), TechDrawGui::QGSPage::createBalloon(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), TechDrawGui::QGIViewDimension::datumLabelDragFinished(), TechDrawGui::QGIViewDimension::drawAngle(), TechDrawGui::QGIViewDimension::drawDistanceExecutive(), TechDrawGui::QGIViewDimension::drawDistanceOverride(), TDHandlerDimension::finishDimensionMove(), TechDrawGui::DrawGuiUtil::fromSceneCoords(), TechDrawGui::PATPathMaker::geomToStubbyLine(), TechDrawGui::QGIView::itemChange(), TechDrawGui::QGIProjGroup::mouseReleaseEvent(), TechDrawGui::TaskDetail::onHighlightMoved(), TechDrawGui::QGILeaderLine::onLineEditFinished(), TechDrawGui::TaskCosVertex::onTrackerFinished(), TechDrawGui::QGIViewBalloon::placeBalloon(), and TechDrawGui::TaskActiveView::setUiPrimary().
appX() [3/3]
QPointF Rez::appX (QPointF p) static
Definition at line 80 of file Rez.cpp.
References buildPsets::p.
getParameter()
double Rez::getParameter (void) static
Definition at line 116 of file Rez.cpp.
References ParameterGrp::GetFloat(), and TechDraw::Preferences::getPreferenceGroup().
getRezFactor()
double Rez::getRezFactor (void) static
Definition at line 37 of file Rez.cpp.
Referenced by TechDrawGui::QGIRichAnno::convertTextSizes(), TechDrawGui::QGIViewSymbol::legacyScaler(), and TechDrawGui::QGIViewSymbol::symbolScaler().
guiPt()
QPointF Rez::guiPt (QPointF p) static
Definition at line 88 of file Rez.cpp.
References buildPsets::p.
Referenced by TechDrawGui::QGISectionLine::makeChangePointMarks().
guiRect()
QRectF Rez::guiRect (QRectF r) static
Definition at line 98 of file Rez.cpp.
guiSize()
QSize Rez::guiSize (QSize s) static
Definition at line 106 of file Rez.cpp.
References toolbit-attributes::s.
guiX() [1/4]
Base::Vector3d Rez::guiX (Base::Vector3d v) static
Definition at line 53 of file Rez.cpp.
References TestSpreadsheet::v.
guiX() [2/4]
Base::Vector2d Rez::guiX (Base::Vector3d v, bool planar) static
Definition at line 58 of file Rez.cpp.
References TestSpreadsheet::v.
guiX() [3/4]
double Rez::guiX (double x) static
Definition at line 48 of file Rez.cpp.
References MovieTool::x.
Referenced by TechDrawGui::QGSPage::addDrawViewClip(), TechDrawGui::QGSPage::addItemToParent(), TechDrawGui::QGSPage::addQView(), TechDrawGui::TaskRichAnno::calcTextStartPos(), TechDrawGui::QGIView::calculateFontPixelSize(), TechDrawGui::TaskActiveView::createActiveView(), TechDrawGui::QGISVGTemplate::createClickHandles(), TechDrawGui::PATPathMaker::decodeDashSpec(), TechDrawGui::PreferencesGui::dimFontSizePX(), TechDrawGui::QGIViewImage::draw(), TechDrawGui::QGIMatting::draw(), TechDrawGui::QGIView::draw(), TechDrawGui::QGIViewDimension::draw(), TechDrawGui::QGIViewAnnotation::drawAnnotation(), TechDrawGui::QGVPage::drawBackground(), TechDrawGui::QGIViewBalloon::drawBalloon(), TechDrawGui::QGIViewClip::drawClip(), TechDrawGui::QGIViewDimension::drawDiameter(), TechDrawGui::QGIView::exactFontSize(), TechDrawGui::QGISectionLine::extensionEndsISO(), TechDrawGui::PATPathMaker::geomToLine(), TechDrawGui::PATPathMaker::geomToStubbyLine(), TechDrawGui::TaskDetail::getAnchorScene(), TechDrawGui::QGISectionLine::getArrowPosition(), TechDrawGui::QGILeaderLine::getAttachFromFeature(), TechDrawGui::QGILeaderLine::getAttachPoint(), TechDrawGui::QGIViewBalloon::getBalloonPoints(), TDHandlerDimension::getDimPositionToBe(), TechDrawGui::QGISVGTemplate::getFontSizeFromElement(), TechDrawGui::QGISVGTemplate::getFontSizeFromStyle(), TechDrawGui::QGIWeldSymbol::getKinkPoint(), TechDrawGui::QGILeaderLine::getLineWidth(), TechDrawGui::QGIWeldSymbol::getTailPoint(), TechDrawGui::QGSPage::getTemplateCenter(), TechDrawGui::QGIWeldSymbol::getTileOrigin(), TechDrawGui::QGILeaderLine::getWayPointsFromFeature(), TechDrawGui::PreferencesGui::labelFontSizePX(), TechDrawGui::PATPathMaker::lineFromPoints(), TechDrawGui::PATPathMaker::lineSetToFillItems(), TechDrawGui::QGIFace::lineSetToFillItems(), TechDrawGui::QGISVGTemplate::load(), TechDrawGui::QGIArrow::makeDot(), TechDrawGui::QGIArrow::makeFilledTriangle(), TechDrawGui::QGIArrow::makeForkArrow(), TechDrawGui::QGVPage::makeGrid(), TechDrawGui::QGIArrow::makeHashMark(), TechDrawGui::QGIArrow::makeOpenArrow(), TechDrawGui::QGIArrow::makeOpenDot(), TechDrawGui::QGIArrow::makePyramid(), TechDrawGui::QGSPage::matchSceneRectToTemplate(), TDHandlerDimension::mouseMoveEvent(), TechDrawGui::QGTracker::mousePressEvent(), TechDrawGui::TaskDetail::onHighlightMoved(), TechDrawGui::TaskCosVertex::onTrackerFinished(), TechDrawGui::QGIViewBalloon::placeBalloon(), TechDrawGui::QGSPage::postProcessXml(), TechDrawGui::PagePrinter::print(), TechDrawGui::PagePrinter::printAll(), TechDrawGui::PagePrinter::printAllPdf(), TechDrawGui::PagePrinter::printPdf(), TechDrawGui::QGIDatumLabel::QGIDatumLabel(), TechDrawGui::QGIGhostHighlight::QGIGhostHighlight(), TechDrawGui::QGIHighlight::QGIHighlight(), TechDrawGui::QGISectionLine::QGISectionLine(), TechDrawGui::QGIViewClip::QGIViewClip(), TechDrawGui::QGIRichAnno::rectPen(), TechDrawGui::QGSPage::saveSvg(), TechDrawGui::QGIHighlight::setBounds(), TechDrawGui::QGEPath::setEndAdjust(), TechDrawGui::QGIFace::setGeomPen(), TechDrawGui::QGILeaderLine::setLeaderFeature(), TechDrawGui::QGIRichAnno::setLineSpacing(), TechDrawGui::QGEPath::setStartAdjust(), TechDrawGui::QGIRichAnno::setTextItem(), TechDrawGui::QGIViewDimension::setViewPartFeature(), TechDrawGui::QGIViewBalloon::setViewPartFeature(), TechDrawGui::QGIDatumLabel::snapPosition(), TechDrawGui::QGIView::snapPosition(), TechDrawGui::QGIView::snapSectionView(), TechDrawGui::QGILeaderLine::startPathEdit(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), TechDrawGui::TaskRichAnno::TaskRichAnno(), TechDrawGui::DrawGuiUtil::toGuiPoint(), TechDrawGui::DrawGuiUtil::toSceneCoords(), TechDrawGui::QGIViewBalloon::updateBalloon(), TDHandlerDimension::updateChainDistanceType(), TDHandlerDimension::updateDistanceType(), TDHandlerDimension::updateExtentDistanceType(), TechDrawGui::QGIRichAnno::updateView(), TechDrawGui::QGIView::updateView(), TechDrawGui::QGIViewDimension::updateView(), and TechDrawGui::QGIViewBalloon::updateView().
guiX() [4/4]
QPointF Rez::guiX (QPointF p) static
Definition at line 64 of file Rez.cpp.
References buildPsets::p.
setRezFactor()
void Rez::setRezFactor (double f) static
Definition at line 42 of file Rez.cpp.
References SCL.SimpleDataTypes::f.
The documentation for this class was generated from the following files:
Rez.h
Rez.cpp