FreeCAD: Gui::ToolBarAreaWidget Class Reference
Gui::ToolBarAreaWidget Class Reference
#include <ToolBarAreaWidget.h>
Public Member Functions
ToolBarAreaWidget (QWidget *parent, ToolBarArea area, const ParameterGrp::handle &hParam, boost::signals2::scoped_connection &conn, QTimer *timer=nullptr)
void addWidget (QWidget *widget)
void insertWidget (int index, QWidget *widget)
void removeWidget (QWidget *widget)
void adjustParent ()
QWidget * widgetAt (int index) const
int count () const
int indexOf (QWidget *widget) const
ToolBarArea area () const
template<class FuncT >
void foreachToolBar (FuncT &&func)
void saveState ()
void restoreState (const std::map< int, QToolBar * > &toolbars)
Detailed Description
Definition at line 67 of file ToolBarAreaWidget.h.
Constructor & Destructor Documentation
ToolBarAreaWidget()
ToolBarAreaWidget::ToolBarAreaWidget (QWidget * parent, ToolBarArea area, const ParameterGrp::handle & hParam, boost::signals2::scoped_connection & conn, QTimer * timer = nullptr)
Definition at line 35 of file ToolBarAreaWidget.cpp.
Member Function Documentation
addWidget()
void ToolBarAreaWidget::addWidget (QWidget * widget)
Definition at line 50 of file ToolBarAreaWidget.cpp.
References adjustParent(), and ParameterGrp::SetInt().
adjustParent()
void ToolBarAreaWidget::adjustParent ()
Definition at line 113 of file ToolBarAreaWidget.cpp.
Referenced by addWidget(), insertWidget(), removeWidget(), and Gui::ToolBarManager::setToolBarIconSize().
area()
ToolBarArea Gui::ToolBarAreaWidget::area () const inline
Definition at line 102 of file ToolBarAreaWidget.h.
count()
int Gui::ToolBarAreaWidget::count () const inline
Definition at line 92 of file ToolBarAreaWidget.h.
Referenced by Gui::ToolBarManager::addToolBarToArea(), and src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::set_status_filter().
foreachToolBar()
template<class FuncT > void Gui::ToolBarAreaWidget::foreachToolBar (FuncT && func) inline
Definition at line 108 of file ToolBarAreaWidget.h.
Referenced by saveState(), and Gui::ToolBarManager::showContextMenu().
indexOf()
int Gui::ToolBarAreaWidget::indexOf (QWidget * widget) const inline
Definition at line 97 of file ToolBarAreaWidget.h.
insertWidget()
void ToolBarAreaWidget::insertWidget (int index, QWidget * widget)
Definition at line 72 of file ToolBarAreaWidget.cpp.
References adjustParent(), and saveState().
Referenced by Gui::ToolBarManager::addToolBarToArea(), and restoreState().
removeWidget()
void ToolBarAreaWidget::removeWidget (QWidget * widget)
Definition at line 96 of file ToolBarAreaWidget.cpp.
References adjustParent(), and ParameterGrp::RemoveInt().
Referenced by Gui::ToolBarManager::addToolBarToArea().
restoreState()
void ToolBarAreaWidget::restoreState (const std::map< int, QToolBar * > & toolbars)
Definition at line 133 of file ToolBarAreaWidget.cpp.
References ParameterGrp::GetBoolMap(), Gui::getMainWindow(), Sketcher::Horizontal, and insertWidget().
Referenced by Gui::ToolBarManager::restoreState().
saveState()
void ToolBarAreaWidget::saveState ()
Definition at line 120 of file ToolBarAreaWidget.cpp.
References foreachToolBar(), ParameterGrp::GetIntMap(), ParameterGrp::RemoveInt(), ParameterGrp::SetInt(), and TestSpreadsheet::v.
Referenced by insertWidget().
widgetAt()
QWidget* Gui::ToolBarAreaWidget::widgetAt (int index) const inline
Definition at line 85 of file ToolBarAreaWidget.h.
Referenced by Gui::ToolBarManager::addToolBarToArea().
The documentation for this class was generated from the following files:
ToolBarAreaWidget.h
ToolBarAreaWidget.cpp