FreeCAD: AppRobotGui.cpp File Reference
AppRobotGui.cpp File Reference
#include "PreCompiled.h"
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/PyObjectBase.h>
#include <Gui/Application.h>
#include <Gui/Language/Translator.h>
#include "ViewProviderEdge2TracObject.h"
#include "ViewProviderRobotObject.h"
#include "ViewProviderTrajectory.h"
#include "ViewProviderTrajectoryCompound.h"
#include "ViewProviderTrajectoryDressUp.h"
#include "Workbench.h"
Classes
class RobotGui::Module
Namespaces
RobotGui
Functions
void CreateRobotCommands ()
void CreateRobotCommandsExport ()
void CreateRobotCommandsInsertRobots ()
void CreateRobotCommandsTrajectory ()
void loadRobotResource ()
PyObject * RobotGui::initModule ()
PyMOD_INIT_FUNC (RobotGui)
Function Documentation
CreateRobotCommands()
void CreateRobotCommands ()
Definition at line 261 of file Mod/Robot/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
CreateRobotCommandsExport()
void CreateRobotCommandsExport ()
Definition at line 190 of file CommandExport.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
CreateRobotCommandsInsertRobots()
void CreateRobotCommandsInsertRobots ()
Definition at line 290 of file CommandInsertRobot.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
CreateRobotCommandsTrajectory()
void CreateRobotCommandsTrajectory ()
Definition at line 522 of file CommandTrajectory.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
loadRobotResource()
void loadRobotResource ()
Definition at line 45 of file AppRobotGui.cpp.
References Gui::Translator::instance(), and Gui::Translator::refresh().
Referenced by PyMOD_INIT_FUNC().
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (RobotGui)
Definition at line 76 of file AppRobotGui.cpp.
References Base::Console(), CreateRobotCommands(), CreateRobotCommandsExport(), CreateRobotCommandsInsertRobots(), CreateRobotCommandsTrajectory(), SCL.SimpleDataTypes::e, Base::Persistence::init(), Base::BaseClass::init(), RobotGui::initModule(), Gui::Application::Instance, Base::Interpreter(), loadRobotResource(), Base::ConsoleSingleton::Log(), mod, PyMOD_Return, and Base::InterpreterSingleton::runString().