FreeCAD: CAMTests.TestPathVcarve.TestPathVcarve Class Reference
CAMTests.TestPathVcarve.TestPathVcarve Class Reference
Public Member Functions
def test00 (self)
def test01 (self)
def test02 (self)
def test03 (self)
def test10 (self)
def test11 (self)
def test12 (self)
def test13 (self)
def test14 (self)
def test15 (self)
def test16 (self)
Public Member Functions inherited from CAMTests.PathTestUtils.PathTestBase
def assertRoughly (self, f1, f2, error=0.00001)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertPlacement (self, p1, p2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertArc (self, edge, pt1, pt2, direction="CW")
def assertCircle (self, edge, pt, r)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCommandEqual (self, c1, c2)
def assertEqualLocale (self, s1, s2)
def assertEdgeShapesMatch (self, e1, e2)
def assertPointsMatch (self, pts0, pts1)
def assertSuccessfulRecompute (self, doc, *objs, msg=None)
Detailed Description
Test Vcarve milling basics.
Definition at line 44 of file TestPathVcarve.py.
Member Function Documentation
test00()
def CAMTests.TestPathVcarve.TestPathVcarve.test00 (self)
Verify 90 deg depth calculation
Definition at line 47 of file TestPathVcarve.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly().
test01()
def CAMTests.TestPathVcarve.TestPathVcarve.test01 (self)
Verify 90 deg depth limit
Definition at line 55 of file TestPathVcarve.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly().
test02()
def CAMTests.TestPathVcarve.TestPathVcarve.test02 (self)
Verify 60 deg depth calculation
Definition at line 63 of file TestPathVcarve.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly().
test03()
def CAMTests.TestPathVcarve.TestPathVcarve.test03 (self)
Verify 60 deg depth limit
Definition at line 71 of file TestPathVcarve.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly().
test10()
def CAMTests.TestPathVcarve.TestPathVcarve.test10 (self)
Verify 90 deg with tip dia depth calculation
Definition at line 79 of file TestPathVcarve.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly().
test11()
def CAMTests.TestPathVcarve.TestPathVcarve.test11 (self)
Verify 90 deg with tip dia depth limit calculation
Definition at line 88 of file TestPathVcarve.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly().
test12()
def CAMTests.TestPathVcarve.TestPathVcarve.test12 (self)
Verify 45 deg with tip dia depth calculation
Definition at line 97 of file TestPathVcarve.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly().
test13()
def CAMTests.TestPathVcarve.TestPathVcarve.test13 (self)
Verify 45 deg with tip dia depth limit calculation
Definition at line 106 of file TestPathVcarve.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly().
test14()
def CAMTests.TestPathVcarve.TestPathVcarve.test14 (self)
Verify if max dept is calculated properly when step-down is disabled
Definition at line 115 of file TestPathVcarve.py.
test15()
def CAMTests.TestPathVcarve.TestPathVcarve.test15 (self)
Verify if step-down sections match final max depth
Definition at line 124 of file TestPathVcarve.py.
test16()
def CAMTests.TestPathVcarve.TestPathVcarve.test16 (self)
Verify 90 deg with tip dia depth calculation with step-down enabled
Definition at line 135 of file TestPathVcarve.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly().
The documentation for this class was generated from the following file:
TestPathVcarve.py