FreeCAD: MeasureGui::ViewProviderMeasureBase Class Reference
MeasureGui::ViewProviderMeasureBase Class Reference
#include <ViewProviderMeasureBase.h>
Public Member Functions
ViewProviderMeasureBase ()
constructor.
~ViewProviderMeasureBase () override
destructor.
bool isPartOfPhysicalObject () const override
void attach (App::DocumentObject *pcObj) override
void updateData (const App::Property *prop) override
handle changes to the feature's properties
virtual void positionAnno (const Measure::MeasureBase *measureObject)
void finishRestoring () override
bool useNewSelectionModel () const override
indicates if the ViewProvider use the new Selection model
std::vector< std::string > getDisplayModes () const override
returns a list of all possible display modes
void setDisplayMode (const char *ModeName) override
set the display mode
void show () override
Show the annotation in the 3d window.
virtual void redrawAnnotation ()
Measure::MeasureBase * getMeasureObject ()
retrieve the feature
virtual bool isSubjectVisible ()
void onSubjectVisibilityChanged (const App::DocumentObject &docObj, const App::Property &prop)
void connectToSubject (App::DocumentObject *subject)
connect to the subject to receive visibility updates
void connectToSubject (std::vector< App::DocumentObject * > subject)
connect to the subject to receive visibility updates
Public Member Functions inherited from Gui::ViewProviderDocumentObject
ViewProviderDocumentObject ()
constructor.
~ViewProviderDocumentObject () override
destructor.
virtual void reattach (App::DocumentObject *)
void update (const App::Property *) override
void setActiveMode ()
Set the active mode, i.e. the first item of the 'Display' property.
void hide () override
Hide the object in the view.
const char * getTransactionText () const override
bool canDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const override
int replaceObject (App::DocumentObject *, App::DocumentObject *) override
bool showInTree () const override
void getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &) const override
Get a list of TaskBoxes associated with this object.
void updateView ()
Run a redraw.
App::DocumentObject * getObject () const
Get the object of this ViewProvider object.
template<class T >
T * getObject () const
Get the object of this ViewProvider object as specified type.
bool canDelete (App::DocumentObject *obj) const override
Asks the view provider if the given object can be deleted.
virtual bool acceptDeletionsInEdit ()
Ask the view provider if it accepts object deletions while in edit.
Gui::Document * getDocument () const
Get the GUI document to this ViewProvider object.
PyObject * getPyObject () override
Get the python wrapper for that ViewProvider.
bool getElementPicked (const SoPickedPoint *, std::string &subname) const override
return a hit element given the picked point which contains the full node path
bool getDetailPath (const char *subname, SoFullPath *pPath, bool append, SoDetail *&det) const override
return the coin node detail and path to the node of the subname
virtual void forceUpdate (bool enable=true)
virtual bool isUpdateForced () const
virtual void startRestoring ()
int getTreeRank () const
void setTreeRank (int value)
bool removeDynamicProperty (const char *prop) override
App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
virtual ViewProviderDocumentObject * getLinkedViewProvider (std::string *subname=nullptr, bool recursive=false) const
std::string getFullName () const override
virtual bool allowOverride (const App::DocumentObject &) const
void setShowable (bool enable)
bool isShowable () const
void startDefaultEditMode ()
Public Member Functions inherited from Gui::ViewProvider
ViewProvider ()
constructor.
~ViewProvider () override
destructor.
virtual SoSeparator * getRoot () const
SoSwitch * getModeSwitch () const
SoTransform * getTransformNode () const
SoSeparator * getAnnotation ()
virtual SoSeparator * getFrontRoot () const
virtual SoGroup * getChildRoot () const
virtual SoSeparator * getBackRoot () const
virtual bool canAddToSceneGraph () const
Indicate whether to be added to scene graph or not.
virtual std::vector< App::DocumentObject * > claimChildren3D () const
virtual bool isSelectable () const
virtual std::string getElement (const SoDetail *) const
return a hit element to the selection path or 0
virtual SoDetail * getDetail (const char *) const
return the coin node detail of the subelement
int partialRender (const std::vector< std::string > &subelements, bool clear)
virtual std::vector< Base::Vector3d > getModelPoints (const SoPickedPoint *) const
virtual std::vector< Base::Vector3d > getSelectionShape (const char *Element) const
return the highlight lines for a given element or the whole shape
Base::BoundBox3d getBoundingBox (const char *subname=nullptr, bool transform=true, MDIView *view=nullptr) const
virtual bool onDelete (const std::vector< std::string > &subNames)
virtual void beforeDelete ()
virtual bool canDragObjects () const
virtual bool canDragObject (App::DocumentObject *) const
virtual bool canDragObjectToTarget (App::DocumentObject *obj, App::DocumentObject *target) const
virtual void dragObject (App::DocumentObject *)
virtual bool canDropObjects () const
virtual bool canDropObject (App::DocumentObject *) const
virtual bool canDragAndDropObject (App::DocumentObject *) const
virtual void dropObject (App::DocumentObject *)
virtual bool acceptReorderingObjects () const
virtual std::string getDropPrefix () const
return a subname referencing the sub-object holding the dropped objects
virtual std::string dropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements)
virtual bool canRemoveChildrenFromRoot () const
std::string getActiveDisplayMode () const
virtual const char * getDefaultDisplayMode () const
get the default display mode
virtual bool isShow () const
checks whether the view provider is visible or not
void setVisible (bool)
bool isVisible () const
void setLinkVisible (bool)
bool isLinkVisible () const
virtual void setOverrideMode (const std::string &mode)
Overrides the display mode with mode.
const std::string getOverrideMode ()
virtual bool selectAll ()
virtual bool keyPressed (bool pressed, int key)
is called when the provider is in edit and a key event occurs. Only ESC ends edit.
virtual bool doubleClicked ()
is called by the tree if the user double clicks on the object
virtual bool mouseMove (const SbVec2s &cursorPos, View3DInventorViewer *viewer)
is called when the provider is in edit and the mouse is moved
virtual bool mouseButtonPressed (int button, bool pressed, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
is called when the Provider is in edit and the mouse is clicked
virtual bool mouseWheelEvent (int delta, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
virtual void setupContextMenu (QMenu *, QObject *, const char *)
set up the context-menu with the supported edit modes
virtual QIcon getIcon () const
deliver the icon shown in the tree view
virtual QIcon mergeColorfulOverlayIcons (const QIcon &orig) const
virtual std::vector< App::DocumentObject * > claimChildren () const
virtual std::vector< App::DocumentObject * > claimChildrenRecursive () const
bool isUpdatesEnabled () const
void setUpdatesEnabled (bool enable)
unsigned long getStatus () const
return the status bits
bool testStatus (ViewStatus pos) const
void setStatus (ViewStatus pos, bool on)
std::string toString () const
virtual std::map< std::string, App::Color > getElementColors (const char *element=nullptr) const
virtual void setElementColors (const std::map< std::string, App::Color > &colors)
virtual ViewProvider * startEditing (int ModNum=0)
bool isEditing () const
void finishEditing ()
virtual void setEditViewer (View3DInventorViewer *, int ModNum)
adjust viewer settings when editing a view provider
virtual void unsetEditViewer (View3DInventorViewer *)
restores viewer settings when leaving editing mode
virtual void setTransformation (const Base::Matrix4D &rcMatrix)
set the viewing transformation of the provider
virtual void setTransformation (const SbMatrix &rcMatrix)
virtual MDIView * getMDIView () const
void Restore (Base::XMLReader &reader) override
bool isRestoring ()
void addDisplayMaskMode (SoNode *node, const char *type)
Adds a new display mask mode.
void setDisplayMaskMode (const char *type)
Activates the display mask mode type.
SoNode * getDisplayMaskMode (const char *type) const
Get the node to the display mask mode type.
std::vector< std::string > getDisplayMaskModes () const
Returns a list of added display mask modes.
void setDefaultMode (int)
int getDefaultMode () const
virtual void setRenderCacheMode (int)
Public Member Functions inherited from App::TransactionalObject
TransactionalObject ()
Constructor.
~TransactionalObject () override
Public Member Functions inherited from App::ExtensionContainer
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
Property * getPropertyByName (const char *name) const override
find a property by its name
template<typename T >
T * getPropertyByName (const char *name) const
find a property by its name, dynamic cased to specified type
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop) override
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static Base::Vector3d toVector3d (SbVec3f svec)
static SbVec3f toSbVec3f (Base::Vector3d vec3)
Static Public Member Functions inherited from Gui::ViewProvider
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
static SbMatrix convert (const Base::Matrix4D &rcMatrix)
static Base::Matrix4D convert (const SbMatrix &sbMat)
static void eventCallback (void *ud, SoEventCallback *node)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes
App::PropertyColor TextColor
App::PropertyColor TextBackgroundColor
App::PropertyColor LineColor
App::PropertyInteger FontSize
Public Attributes inherited from Gui::ViewProviderDocumentObject
App::PropertyEnumeration DisplayMode
App::PropertyBool Visibility
App::PropertyBool ShowInTree
App::PropertyEnumeration OnTopWhenSelected
App::PropertyEnumeration SelectionStyle
Public Attributes inherited from Gui::ViewProvider
boost::signals2::signal< void()> signalChangeIcon
signal on icon change
boost::signals2::signal< void(const QString &)> signalChangeToolTip
signal on tooltip change
boost::signals2::signal< void(const QString &)> signalChangeStatusTip
signal on status tip change
boost::signals2::signal< void(bool, Gui::HighlightMode)> signalChangeHighlight
signal on highlight change
Protected Member Functions
void onChanged (const App::Property *prop) override
Gets called by the container whenever a property has been changed.
virtual void onLabelMoved ()
void setLabelValue (const Base::Quantity &value)
void setLabelValue (const QString &value)
void setLabelTranslation (const SbVec3f &position)
void updateIcon ()
SoPickStyle * getSoPickStyle ()
SoDrawStyle * getSoLineStylePrimary ()
SoDrawStyle * getSoLineStyleSecondary ()
SoSeparator * getSoSeparatorText ()
virtual Base::Vector3d getTextDirection (Base::Vector3d elementDirection, double tolerance=defaultTolerance)
float getViewScale ()
Protected Member Functions inherited from Gui::ViewProviderDocumentObject
Gui::MDIView * getActiveView () const
Gui::MDIView * getEditingView () const
Gui::MDIView * getInventorView () const
Gui::MDIView * getViewOfNode (SoNode *node) const
void onBeforeChange (const App::Property *prop) override
get called before the value is changed
SoNode * findFrontRootOfType (const SoType &type) const
bool isAttachedToDocument () const override
const char * detachFromDocument () override
void onPropertyStatusChanged (const App::Property &prop, unsigned long oldStatus) override
get called when a property status has changed
void setModeSwitch () override
Turn on mode switch.
void addDefaultAction (QMenu *, const QString &)
Protected Member Functions inherited from Gui::ViewProvider
virtual QIcon mergeGreyableOverlayIcons (const QIcon &orig) const
virtual bool setEdit (int ModNum)
is called by the document when the provider goes in edit mode
virtual void unsetEdit (int ModNum)
is called when you lose the edit mode
int getEditingMode () const
return the edit mode or -1 if nothing is being edited
bool checkRecursion (SoNode *)
SoPickedPoint * getPointOnRay (const SbVec2s &pos, const View3DInventorViewer *viewer) const
SoPickedPoint * getPointOnRay (const SbVec3f &pos, const SbVec3f &dir, const View3DInventorViewer *viewer) const
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual void onEarlyChange (const Property *)
virtual const PropertyData & getPropertyData () const
Static Protected Member Functions
static void draggerChangedCallback (void *data, SoDragger *)
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes
bool _mShowTree = true
SoSeparator * pGlobalSeparator
Gui::SoFrameLabel * pLabel
SoTranslate2Dragger * pDragger
SoTransform * pDraggerOrientation
SoTransform * pLabelTranslation
SoBaseColor * pColor
SoSeparator * pRootSeparator
SoSeparator * pTextSeparator
SoSeparator * pLineSeparator
SoSeparator * pLineSeparatorSecondary
Protected Attributes inherited from Gui::ViewProviderDocumentObject
App::DocumentObject * pcObject {nullptr}
Gui::Document * pcDocument {nullptr}
Protected Attributes inherited from Gui::ViewProvider
SoSeparator * pcRoot
The root Separator of the ViewProvider.
SoTransform * pcTransform
this is transformation for the provider
const char * sPixmap
SoSwitch * pcModeSwitch
this is the mode switch, all the different viewing modes are collected here
SoSeparator * pcAnnotation {nullptr}
The root separator for annotations.
ViewProviderPy * pyViewObject {nullptr}
std::string overrideMode
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Static Protected Attributes
static constexpr double defaultTolerance = 10e-6
Additional Inherited Members
Public Types inherited from Gui::ViewProvider
enum EditMode { Default = 0, Transform, Cutting, Color }
Public Types inherited from App::ExtensionContainer
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Detailed Description
Definition at line 73 of file ViewProviderMeasureBase.h.
Constructor & Destructor Documentation
ViewProviderMeasureBase()
ViewProviderMeasureBase::ViewProviderMeasureBase ()
constructor.
Definition at line 76 of file ViewProviderMeasureBase.cpp.
References ADD_PROPERTY_TYPE, and App::Prop_None.
~ViewProviderMeasureBase()
ViewProviderMeasureBase::~ViewProviderMeasureBase () override
destructor.
Definition at line 199 of file ViewProviderMeasureBase.cpp.
Member Function Documentation
attach()
void ViewProviderMeasureBase::attach (App::DocumentObject * pcObj) override virtual
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 331 of file ViewProviderMeasureBase.cpp.
connectToSubject() [1/2]
void ViewProviderMeasureBase::connectToSubject (App::DocumentObject * subject)
connect to the subject to receive visibility updates
Definition at line 388 of file ViewProviderMeasureBase.cpp.
References draftgeoutils.faces::bind(), onSubjectVisibilityChanged(), and App::DocumentObject::signalChanged.
connectToSubject() [2/2]
void ViewProviderMeasureBase::connectToSubject (std::vector< App::DocumentObject * > subject)
connect to the subject to receive visibility updates
Definition at line 409 of file ViewProviderMeasureBase.cpp.
draggerChangedCallback()
void ViewProviderMeasureBase::draggerChangedCallback (void * data, SoDragger *) static protected
Definition at line 258 of file ViewProviderMeasureBase.cpp.
References onLabelMoved().
finishRestoring()
void ViewProviderMeasureBase::finishRestoring () override virtual
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 230 of file ViewProviderMeasureBase.cpp.
References bimcommands.BimViews::show().
getDisplayModes()
std::vector< std::string > ViewProviderMeasureBase::getDisplayModes () const override virtual
returns a list of all possible display modes
Reimplemented from Gui::ViewProvider.
Definition at line 213 of file ViewProviderMeasureBase.cpp.
getMeasureObject()
Measure::MeasureBase * ViewProviderMeasureBase::getMeasureObject ()
retrieve the feature
Definition at line 422 of file ViewProviderMeasureBase.cpp.
getSoLineStylePrimary()
SoDrawStyle * ViewProviderMeasureBase::getSoLineStylePrimary () protected
Definition at line 294 of file ViewProviderMeasureBase.cpp.
getSoLineStyleSecondary()
SoDrawStyle * ViewProviderMeasureBase::getSoLineStyleSecondary () protected
Definition at line 301 of file ViewProviderMeasureBase.cpp.
getSoPickStyle()
SoPickStyle * ViewProviderMeasureBase::getSoPickStyle () protected
Definition at line 287 of file ViewProviderMeasureBase.cpp.
getSoSeparatorText()
SoSeparator * ViewProviderMeasureBase::getSoSeparatorText () protected
Definition at line 308 of file ViewProviderMeasureBase.cpp.
getTextDirection()
Base::Vector3d ViewProviderMeasureBase::getTextDirection (Base::Vector3d elementDirection, double tolerance = defaultTolerance) protected virtual
calculate a good direction from the elements being measured to the annotation text based on the layout of the elements and relationship with the cardinal axes and the view direction. elementDirection is expected to be a normalized vector. an example of an elementDirection would be the vector from the start of a line to the end.
Reimplemented in MeasureGui::ViewProviderMeasureDistance.
Definition at line 438 of file ViewProviderMeasureBase.cpp.
References Base::Console(), Base::Vector3< float_type >::Cross(), Gui::View3DInventor::getViewer(), Base::Vector3< float_type >::Length(), Base::ConsoleSingleton::Log(), Base::Vector3< float_type >::Normalize(), draftutils.utils::tolerance(), toVector3d(), viewDirection(), and OfflineRenderingUtils::viewer().
getViewScale()
float ViewProviderMeasureBase::getViewScale () protected
Definition at line 539 of file ViewProviderMeasureBase.cpp.
References exportCSG::center(), Base::Console(), Gui::View3DInventor::getViewer(), Base::ConsoleSingleton::Log(), draftfunctions.scale::scale(), and OfflineRenderingUtils::viewer().
isPartOfPhysicalObject()
bool MeasureGui::ViewProviderMeasureBase::isPartOfPhysicalObject () const inline override virtual
Attaches the document object to this view provider.
Reimplemented from Gui::ViewProvider.
Definition at line 94 of file ViewProviderMeasureBase.h.
isSubjectVisible()
bool ViewProviderMeasureBase::isSubjectVisible () virtual
true if the subject of this measurement is visible. For Measures that have multiple object subject, all of the subjects must be visible.
Definition at line 482 of file ViewProviderMeasureBase.cpp.
References Base::Console(), Gui::Document::getViewProvider(), Gui::ViewProvider::isVisible(), and Base::ConsoleSingleton::Log().
onChanged()
void ViewProviderMeasureBase::onChanged (const App::Property * prop) override protected virtual
Gets called by the container whenever a property has been changed.
Reimplemented from Gui::ViewProviderDocumentObject.
Reimplemented in MeasureGui::ViewProviderMeasure, and MeasureGui::ViewProviderMeasureDistance.
Definition at line 237 of file ViewProviderMeasureBase.cpp.
References App::Color::b, App::Color::g, App::Color::r, and App::Color::setValue().
Referenced by MeasureGui::ViewProviderMeasure::onChanged().
onLabelMoved()
virtual void MeasureGui::ViewProviderMeasureBase::onLabelMoved () inline protected virtual
Definition at line 133 of file ViewProviderMeasureBase.h.
Referenced by draggerChangedCallback().
onSubjectVisibilityChanged()
void ViewProviderMeasureBase::onSubjectVisibilityChanged (const App::DocumentObject & docObj, const App::Property & prop)
gets called when the subject object issues a signalChanged (ie a property change). We are only interested in the subject's Visibility property
Definition at line 517 of file ViewProviderMeasureBase.cpp.
References App::Property::getName(), App::PropertyBool::getValue(), App::DocumentObject::isRemoving(), and App::DocumentObject::Visibility.
Referenced by connectToSubject().
positionAnno()
void ViewProviderMeasureBase::positionAnno (const Measure::MeasureBase * measureObject) virtual
Reimplemented in MeasureGui::ViewProviderMeasure, MeasureGui::ViewProviderMeasureDistance, and MeasureGui::ViewProviderMeasureAngle.
Definition at line 314 of file ViewProviderMeasureBase.cpp.
redrawAnnotation()
void ViewProviderMeasureBase::redrawAnnotation () virtual
Reimplemented in MeasureGui::ViewProviderMeasure, MeasureGui::ViewProviderMeasureDistance, and MeasureGui::ViewProviderMeasureAngle.
Definition at line 382 of file ViewProviderMeasureBase.cpp.
Referenced by MeasureGui::ViewProviderMeasure::redrawAnnotation().
setDisplayMode()
void ViewProviderMeasureBase::setDisplayMode (const char * ModeName) override virtual
set the display mode
If you add new viewing modes in getDisplayModes() then you need to reimplement also seDisplaytMode() to handle these new modes by setting the appropriate display mode.
Reimplemented from Gui::ViewProvider.
Definition at line 221 of file ViewProviderMeasureBase.cpp.
setLabelTranslation()
void ViewProviderMeasureBase::setLabelTranslation (const SbVec3f & position) protected
Definition at line 280 of file ViewProviderMeasureBase.cpp.
setLabelValue() [1/2]
void ViewProviderMeasureBase::setLabelValue (const Base::Quantity & value) protected
Definition at line 264 of file ViewProviderMeasureBase.cpp.
References Base::Quantity::getUserString().
setLabelValue() [2/2]
void ViewProviderMeasureBase::setLabelValue (const QString & value) protected
Definition at line 269 of file ViewProviderMeasureBase.cpp.
References SplineSurface::i.
show()
void ViewProviderMeasureBase::show () override virtual
Show the annotation in the 3d window.
called by the system when it is time to display this measure
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 717 of file ViewProviderMeasureBase.cpp.
References bimcommands.BimViews::show().
Referenced by src.Mod.Show.mTempoVis.TempoVis::show_all_dependencies(), and src.Mod.Show.mTempoVis.TempoVis::show_all_dependent().
toSbVec3f()
static SbVec3f MeasureGui::ViewProviderMeasureBase::toSbVec3f (Base::Vector3d vec3) inline static
Definition at line 121 of file ViewProviderMeasureBase.h.
toVector3d()
static Base::Vector3d MeasureGui::ViewProviderMeasureBase::toVector3d (SbVec3f svec) inline static
Definition at line 117 of file ViewProviderMeasureBase.h.
updateData()
void ViewProviderMeasureBase::updateData (const App::Property * prop) override virtual
handle changes to the feature's properties
Reimplemented from Gui::ViewProvider.
Definition at line 339 of file ViewProviderMeasureBase.cpp.
References DraftVecUtils::find(), and App::Property::getName().
updateIcon()
void ViewProviderMeasureBase::updateIcon () protected
Definition at line 320 of file ViewProviderMeasureBase.cpp.
References Gui::BitmapFactory().
useNewSelectionModel()
bool MeasureGui::ViewProviderMeasureBase::useNewSelectionModel () const inline override virtual
indicates if the ViewProvider use the new Selection model
Reimplemented from Gui::ViewProvider.
Definition at line 103 of file ViewProviderMeasureBase.h.
Member Data Documentation
_mShowTree
bool MeasureGui::ViewProviderMeasureBase::_mShowTree = true protected
Definition at line 150 of file ViewProviderMeasureBase.h.
defaultTolerance
constexpr double MeasureGui::ViewProviderMeasureBase::defaultTolerance = 10e-6 static constexpr protected
Definition at line 144 of file ViewProviderMeasureBase.h.
FontSize
App::PropertyInteger MeasureGui::ViewProviderMeasureBase::FontSize
Definition at line 88 of file ViewProviderMeasureBase.h.
LineColor
App::PropertyColor MeasureGui::ViewProviderMeasureBase::LineColor
Definition at line 87 of file ViewProviderMeasureBase.h.
pColor
SoBaseColor* MeasureGui::ViewProviderMeasureBase::pColor protected
Definition at line 157 of file ViewProviderMeasureBase.h.
pDragger
SoTranslate2Dragger* MeasureGui::ViewProviderMeasureBase::pDragger protected
Definition at line 154 of file ViewProviderMeasureBase.h.
pDraggerOrientation
SoTransform* MeasureGui::ViewProviderMeasureBase::pDraggerOrientation protected
Definition at line 155 of file ViewProviderMeasureBase.h.
pGlobalSeparator
SoSeparator* MeasureGui::ViewProviderMeasureBase::pGlobalSeparator protected
Definition at line 152 of file ViewProviderMeasureBase.h.
pLabel
Gui::SoFrameLabel* MeasureGui::ViewProviderMeasureBase::pLabel protected
Definition at line 153 of file ViewProviderMeasureBase.h.
pLabelTranslation
SoTransform* MeasureGui::ViewProviderMeasureBase::pLabelTranslation protected
Definition at line 156 of file ViewProviderMeasureBase.h.
pLineSeparator
SoSeparator* MeasureGui::ViewProviderMeasureBase::pLineSeparator protected
Definition at line 160 of file ViewProviderMeasureBase.h.
pLineSeparatorSecondary
SoSeparator* MeasureGui::ViewProviderMeasureBase::pLineSeparatorSecondary protected
Definition at line 161 of file ViewProviderMeasureBase.h.
pRootSeparator
SoSeparator* MeasureGui::ViewProviderMeasureBase::pRootSeparator protected
Definition at line 158 of file ViewProviderMeasureBase.h.
pTextSeparator
SoSeparator* MeasureGui::ViewProviderMeasureBase::pTextSeparator protected
Definition at line 159 of file ViewProviderMeasureBase.h.
TextBackgroundColor
App::PropertyColor MeasureGui::ViewProviderMeasureBase::TextBackgroundColor
Definition at line 86 of file ViewProviderMeasureBase.h.
TextColor
App::PropertyColor MeasureGui::ViewProviderMeasureBase::TextColor
Definition at line 85 of file ViewProviderMeasureBase.h.
The documentation for this class was generated from the following files:
ViewProviderMeasureBase.h
ViewProviderMeasureBase.cpp