FreeCAD: MeshCore::PlaneFitSmoothing Class Reference
MeshCore::PlaneFitSmoothing Class Reference
#include <Smoothing.h>
Public Member Functions
PlaneFitSmoothing (MeshKernel &)
void SetMaximum (float max)
void Smooth (unsigned int) override
void SmoothPoints (unsigned int, const std::vector< PointIndex > &) override
Public Member Functions inherited from MeshCore::AbstractSmoothing
AbstractSmoothing (MeshKernel &)
virtual ~AbstractSmoothing ()
AbstractSmoothing (const AbstractSmoothing &)=delete
AbstractSmoothing (AbstractSmoothing &&)=delete
AbstractSmoothing & operator= (const AbstractSmoothing &)=delete
AbstractSmoothing & operator= (AbstractSmoothing &&)=delete
void initialize (Component comp, Continuity cont)
Additional Inherited Members
Public Types inherited from MeshCore::AbstractSmoothing
enum Component { Tangential, Normal, TangentialNormal }
enum Continuity { C0, C1, C2 }
Protected Attributes inherited from MeshCore::AbstractSmoothing
MeshKernel & kernel
Component component {Normal}
Continuity continuity {C0}
Detailed Description
Definition at line 99 of file Smoothing.h.
Constructor & Destructor Documentation
PlaneFitSmoothing()
PlaneFitSmoothing::PlaneFitSmoothing (MeshKernel & m) explicit
Definition at line 52 of file Smoothing.cpp.
Member Function Documentation
SetMaximum()
void MeshCore::PlaneFitSmoothing::SetMaximum (float max) inline
Definition at line 103 of file Smoothing.h.
Smooth()
void PlaneFitSmoothing::Smooth (unsigned int) override virtual
Smooth the triangle mesh.
Implements MeshCore::AbstractSmoothing.
Definition at line 56 of file Smoothing.cpp.
References MeshCore::Approximation::AddPoint(), MeshCore::MeshPointIterator::Begin(), exportCSG::center(), src.Mod.AddonManager.NetworkManager::count, MeshCore::MeshKernel::CountPoints(), MeshCore::PlaneFit::Fit(), MeshCore::PlaneFit::GetNormal(), MeshCore::MeshKernel::GetPoints(), SplineSurface::i, MeshCore::AbstractSmoothing::kernel, MeshCore::MeshPointIterator::More(), MeshCore::MeshPointIterator::Next(), Base::Vector3< float_type >::Normalize(), MeshCore::MeshPointIterator::Position(), Base::Vector3< float_type >::Scale(), Base::Vector3< float_type >::Set(), MeshCore::MeshKernel::SetPoint(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
SmoothPoints()
void PlaneFitSmoothing::SmoothPoints (unsigned int iterations, const std::vector< PointIndex > & point_indices) override virtual
Implements MeshCore::AbstractSmoothing.
Definition at line 111 of file Smoothing.cpp.
References MeshCore::Approximation::AddPoint(), exportCSG::center(), src.Mod.AddonManager.NetworkManager::count, MeshCore::MeshKernel::CountPoints(), MeshCore::PlaneFit::Fit(), MeshCore::PlaneFit::GetNormal(), MeshCore::MeshKernel::GetPoints(), SplineSurface::i, MeshCore::AbstractSmoothing::kernel, Base::Vector3< float_type >::Normalize(), MeshCore::MeshPointIterator::Position(), Base::Vector3< float_type >::Scale(), Base::Vector3< float_type >::Set(), MeshCore::MeshPointIterator::Set(), MeshCore::MeshKernel::SetPoint(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
The documentation for this class was generated from the following files:
Smoothing.h
Smoothing.cpp