FreeCAD: ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching Class Reference
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching Class Reference
Public Member Functions
def __init__ (self, inherited0__name, hatch_line_appearance, start_of_next_hatch_line, point_of_reference_hatch_line, pattern_start, hatch_line_angle)
def hatch_line_appearance ()
def start_of_next_hatch_line ()
def point_of_reference_hatch_line ()
def pattern_start ()
def hatch_line_angle ()
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_representation_item
def __init__ (self, inherited0__name)
def dim ()
def wr1 (self)
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation_item
def name ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
hatch_line_appearance
start_of_next_hatch_line
point_of_reference_hatch_line
pattern_start
hatch_line_angle
Public Attributes inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation_item
name
Detailed Description
Entity fill_area_style_hatching definition.
:param hatch_line_appearance
:type hatch_line_appearance:curve_style
:param start_of_next_hatch_line
:type start_of_next_hatch_line:one_direction_repeat_factor
:param point_of_reference_hatch_line
:type point_of_reference_hatch_line:cartesian_point
:param pattern_start
:type pattern_start:cartesian_point
:param hatch_line_angle
:type hatch_line_angle:plane_angle_measure
Definition at line 31975 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Constructor & Destructor Documentation
__init__()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching.__init__ (self, inherited0__name, hatch_line_appearance, start_of_next_hatch_line, point_of_reference_hatch_line, pattern_start, hatch_line_angle)
Definition at line 31993 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Member Function Documentation
hatch_line_angle()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching.hatch_line_angle ()
Definition at line 32058 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching._hatch_line_angle, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching.hatch_line_angle.
hatch_line_appearance()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching.hatch_line_appearance ()
Definition at line 32002 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching._hatch_line_appearance, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching.hatch_line_appearance.
pattern_start()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching.pattern_start ()
Definition at line 32044 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching._pattern_start, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching.pattern_start.
point_of_reference_hatch_line()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching.point_of_reference_hatch_line ()
Definition at line 32030 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching._point_of_reference_hatch_line, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching.point_of_reference_hatch_line.
start_of_next_hatch_line()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching.start_of_next_hatch_line ()
Definition at line 32016 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching._start_of_next_hatch_line, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching.start_of_next_hatch_line.
Member Data Documentation
hatch_line_angle
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching.hatch_line_angle
Definition at line 31999 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching.hatch_line_angle().
hatch_line_appearance
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching.hatch_line_appearance
Definition at line 31995 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching.hatch_line_appearance().
pattern_start
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching.pattern_start
Definition at line 31998 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching.pattern_start().
point_of_reference_hatch_line
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching.point_of_reference_hatch_line
Definition at line 31997 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching.point_of_reference_hatch_line().
start_of_next_hatch_line
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching.start_of_next_hatch_line
Definition at line 31996 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_hatching.start_of_next_hatch_line().
The documentation for this class was generated from the following file:
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py