FreeCAD: GCS::Hyperbola Class Reference
GCS::Hyperbola Class Reference
#include <Geo.h>
Public Member Functions
Hyperbola ()
~Hyperbola () override
double getRadMaj (const DeriVector2 &center, const DeriVector2 &f1, double b, double db, double &ret_dRadMaj) const override
double getRadMaj (double *derivparam, double &ret_dRadMaj) const override
double getRadMaj () const override
DeriVector2 CalculateNormal (const Point &p, const double *derivparam=nullptr) const override
DeriVector2 Value (double u, double du, const double *derivparam=nullptr) const override
Value: returns point (vector) given the value of parameter.
int PushOwnParams (VEC_pD &pvec) override
void ReconstructOnNewPvec (VEC_pD &pvec, int &cnt) override
Hyperbola * Copy () override
Public Member Functions inherited from GCS::MajorRadiusConic
~MajorRadiusConic () override
Public Member Functions inherited from GCS::Curve
virtual ~Curve ()
virtual DeriVector2 CalculateNormal (const double *param, const double *derivparam=nullptr) const
Public Attributes
Point center
Point focus1
double * radmin
Detailed Description
Definition at line 340 of file Geo.h.
Constructor & Destructor Documentation
Hyperbola()
GCS::Hyperbola::Hyperbola () inline
Definition at line 343 of file Geo.h.
Referenced by Copy().
~Hyperbola()
GCS::Hyperbola::~Hyperbola () inline override
Definition at line 347 of file Geo.h.
Member Function Documentation
CalculateNormal()
DeriVector2 GCS::Hyperbola::CalculateNormal (const Point & p, const double * derivparam = nullptr) const override virtual
Implements GCS::Curve.
Definition at line 475 of file Geo.cpp.
References center, focus1, GCS::DeriVector2::getNormalized(), GCS::DeriVector2::linCombi(), GCS::DeriVector2::mult(), buildPsets::p, GCS::DeriVector2::subtr(), and GCS::DeriVector2::sum().
Copy()
Hyperbola * GCS::Hyperbola::Copy () override virtual
Implements GCS::Curve.
Reimplemented in GCS::ArcOfHyperbola.
Definition at line 560 of file Geo.cpp.
References Hyperbola().
getRadMaj() [1/3]
double GCS::Hyperbola::getRadMaj () const override virtual
Implements GCS::MajorRadiusConic.
Definition at line 469 of file Geo.cpp.
Referenced by getRadMaj(), and Value().
getRadMaj() [2/3]
double GCS::Hyperbola::getRadMaj (const DeriVector2 & center, const DeriVector2 & f1, double b, double db, double & ret_dRadMaj) const override virtual
Implements GCS::MajorRadiusConic.
Definition at line 445 of file Geo.cpp.
References a, SCL.SimpleDataTypes::b, center, GCS::DeriVector2::length(), KDL::sqrt(), and GCS::DeriVector2::subtr().
getRadMaj() [3/3]
double GCS::Hyperbola::getRadMaj (double * derivparam, double & ret_dRadMaj) const override virtual
Implements GCS::MajorRadiusConic.
Definition at line 461 of file Geo.cpp.
References SCL.SimpleDataTypes::c, center, focus1, getRadMaj(), and radmin.
PushOwnParams()
int GCS::Hyperbola::PushOwnParams (VEC_pD & pvec) override virtual
Implements GCS::Curve.
Reimplemented in GCS::ArcOfHyperbola.
Definition at line 532 of file Geo.cpp.
References center, focus1, radmin, GCS::Point::x, and GCS::Point::y.
Referenced by GCS::ConstraintInternalAlignmentPoint2Hyperbola::ConstraintInternalAlignmentPoint2Hyperbola(), and GCS::ArcOfHyperbola::PushOwnParams().
ReconstructOnNewPvec()
void GCS::Hyperbola::ReconstructOnNewPvec (VEC_pD & pvec, int & cnt) override virtual
Implements GCS::Curve.
Reimplemented in GCS::ArcOfHyperbola.
Definition at line 547 of file Geo.cpp.
References center, focus1, radmin, GCS::Point::x, and GCS::Point::y.
Referenced by GCS::ArcOfHyperbola::ReconstructOnNewPvec().
Value()
DeriVector2 GCS::Hyperbola::Value (double u, double du, const double * derivparam = nullptr) const override virtual
Value: returns point (vector) given the value of parameter.
Parameters
u value of parameter
du derivative of parameter by derivparam
derivparam pointer to sketch parameter to calculate the derivative for
Returns
Reimplemented from GCS::Curve.
Definition at line 496 of file Geo.cpp.
References a, SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::c, center, KDL::cosh(), focus1, GCS::DeriVector2::getNormalized(), getRadMaj(), GCS::DeriVector2::multD(), radmin, GCS::DeriVector2::rotate90ccw(), KDL::sinh(), GCS::DeriVector2::subtr(), GCS::DeriVector2::sum(), and buildPsets::u.
Member Data Documentation
center
Point GCS::Hyperbola::center
Definition at line 349 of file Geo.h.
Referenced by CalculateNormal(), Path.Dressup.Gui.AxisMap.ObjectDressup::execute(), getRadMaj(), Path.Dressup.Gui.AxisMap.ObjectDressup::onChanged(), PushOwnParams(), ReconstructOnNewPvec(), and Value().
focus1
Point GCS::Hyperbola::focus1
Definition at line 350 of file Geo.h.
Referenced by CalculateNormal(), getRadMaj(), PushOwnParams(), ReconstructOnNewPvec(), and Value().
radmin
double* GCS::Hyperbola::radmin
Definition at line 351 of file Geo.h.
Referenced by getRadMaj(), PushOwnParams(), ReconstructOnNewPvec(), and Value().
The documentation for this class was generated from the following files:
Geo.h
Geo.cpp