FreeCAD: MeshCore::MeshHelpPoint Struct Reference
MeshCore::MeshHelpPoint Struct Reference
#include <Helpers.h>
Public Member Functions
void Set (FacetIndex ulCorner, FacetIndex ulFacet, const Base::Vector3f &rclPt)
bool operator< (const MeshHelpPoint &rclObj) const
bool operator== (const MeshHelpPoint &rclObj) const
FacetIndex Index () const
FacetIndex Corner () const
Public Attributes
MeshPoint _clPt
FacetIndex _ulInd {FACET_INDEX_MAX}
Detailed Description
Helper class for points.
Definition at line 55 of file Helpers.h.
Member Function Documentation
Corner()
FacetIndex MeshCore::MeshHelpPoint::Corner () const inline
Definition at line 87 of file Helpers.h.
Index()
FacetIndex MeshCore::MeshHelpPoint::Index () const inline
Definition at line 82 of file Helpers.h.
operator<()
bool MeshCore::MeshHelpPoint::operator< (const MeshHelpPoint & rclObj) const inline
Definition at line 127 of file Helpers.h.
References Set().
operator==()
bool MeshCore::MeshHelpPoint::operator== (const MeshHelpPoint & rclObj) const inline
Definition at line 142 of file Helpers.h.
References MeshCore::MeshHelpBuilderEdge::_aulInd.
Set()
void MeshCore::MeshHelpPoint::Set (FacetIndex ulCorner, FacetIndex ulFacet, const Base::Vector3f & rclPt) inline
Definition at line 121 of file Helpers.h.
References _clPt, MeshCore::MeshDefinitions::_fMinPointDistanceP2, and Base::DistanceP2().
Referenced by operator<().
Member Data Documentation
_clPt
MeshPoint MeshCore::MeshHelpPoint::_clPt
Definition at line 92 of file Helpers.h.
Referenced by Set().
_ulInd
FacetIndex MeshCore::MeshHelpPoint::_ulInd {FACET_INDEX_MAX}
Definition at line 93 of file Helpers.h.
The documentation for this struct was generated from the following file:
Helpers.h