FreeCAD: App Namespace Reference
App Namespace Reference
a class to assist with exporting sketches to dxf
Namespaces
ExpressionParser
Meta
Util
Classes
class Annotation
class AnnotationLabel
class Application
class AtomicPropertyChangeInterface
class AutoTransaction
Helper class to manager transaction (i.e. undo/redo)
class BackupPolicy
class Branding
struct CellAddress
class CenterOfMassProvider
class CleanupProcess
The CleanupProcess class.
class Color
struct color_traits
struct color_traits< App::Color >
struct color_traits< QColor >
struct color_traits< SbColor >
struct color_traits< SbColor4f >
class ColorField
class ColorGradient
struct ColorGradientProfile
class ColorLegend
class ColorModel
class ColorModelBlackGray
class ColorModelBlackWhite
class ColorModelBlueCyanGreen
class ColorModelBlueGreenRed
class ColorModelBlueWhite
class ColorModelBlueWhiteRed
class ColorModelGrayBlack
class ColorModelGrayWhite
class ColorModelGreenCyanBlue
class ColorModelGreenYellowRed
struct ColorModelPack
class ColorModelRedGreenBlue
class ColorModelRedYellowGreen
class ColorModelWhiteBlack
class ColorModelWhiteGray
class ColorModelWhiteRed
class ConditionalExpression
class ConstantExpression
struct CStringHasher
class DatumElement
class DocInfo
class Document
The document class.
class DocumentObject
class DocumentObjectExecReturn
class DocumentObjectExtension
Extension with special document object calls.
class DocumentObjectFileIncluded
class DocumentObjectGroup
class DocumentObjectObserver
class DocumentObjectT
class DocumentObjectWeakPtrT
The DocumentObjectWeakPtrT class.
class DocumentObserver
class DocumentObserverPython
struct DocumentP
class DocumentT
class DocumentWeakPtrT
The DocumentWeakPtrT class.
class DynamicProperty
struct ElementNamePair
class Enumeration
A bidirectional string-integer mapping.
struct Expression
class ExpressionModifier
class ExpressionTokenizer
class ExpressionVisitor
class Extension
Base class for all extension that can be added to a DocumentObject.
class ExtensionContainer
Container which can hold extensions.
class ExtensionPythonT
class FeatureCustomT
class FeaturePythonImp
class FeaturePythonPyT
class FeaturePythonT
class FeatureTest
The testing feature.
class FeatureTestAbsAddress
class FeatureTestAttribute
class FeatureTestColumn
class FeatureTestException
The exception testing feature.
class FeatureTestPlacement
class FeatureTestRow
class FunctionExpression
class GeoFeature
class GeoFeatureGroupExtension
The base class for placeable group of DocumentObjects. It represents a local coordnate system.
class GroupExtension
class GroupExtensionPythonT
class InventorObject
class Line
class Link
class LinkBaseExtension
class LinkElement
class LinkExtension
class LinkGroup
class LinkParams
class LocalCoordinateSystem
class Material
class MaterialObject
struct MeasureHandler
class MeasureManager
struct MeasureSelectionItem
struct MeasureType
class MergeDocuments
class Metadata
Reads data from a metadata file.
class MoveCellsExpressionVisitor
class NullCenterOfMass
class NumberExpression
class ObjectIdentifier
class OffsetCellsExpressionVisitor
class OperatorExpression
class Origin
class OriginGroupExtension
class Part
class Path
class Placement
class Plane
class Point
class ProjectFile
class Property
class PropertyAcceleration
class PropertyAmountOfSubstance
class PropertyAngle
class PropertyArea
class PropertyBool
class PropertyBoolList
struct PropertyCleaner
The PropertyCleaner struct Make deleting dynamic property safer by postponing its destruction.
class PropertyColor
class PropertyColorList
class PropertyComplexGeoData
class PropertyCompressiveStrength
class PropertyContainer
class PropertyCurrentDensity
struct PropertyData
class PropertyDensity
class PropertyDirection
class PropertyDissipationRate
class PropertyDistance
class PropertyDynamicViscosity
class PropertyElectricalCapacitance
class PropertyElectricalConductance
class PropertyElectricalConductivity
class PropertyElectricalInductance
class PropertyElectricalResistance
class PropertyElectricCharge
class PropertyElectricCurrent
class PropertyElectricPotential
class PropertyElectromagneticPotential
class PropertyEnumeration
Property wrapper around an Enumeration object.
class PropertyExpressionContainer
class PropertyExpressionEngine
class PropertyFile
class PropertyFileIncluded
class PropertyFloat
class PropertyFloatConstraint
class PropertyFloatList
class PropertyFont
class PropertyForce
class PropertyFrequency
class PropertyGeometry
class PropertyHeatFlux
class PropertyInteger
class PropertyIntegerConstraint
class PropertyIntegerList
class PropertyIntegerSet
class PropertyInverseArea
class PropertyInverseLength
class PropertyInverseVolume
class PropertyKinematicViscosity
class PropertyLength
class PropertyLink
class PropertyLinkBase
Parent class of all link type properties.
class PropertyLinkChild
class PropertyLinkGlobal
class PropertyLinkHidden
class PropertyLinkList
class PropertyLinkListBase
class PropertyLinkListChild
class PropertyLinkListGlobal
class PropertyLinkListHidden
class PropertyLinkSub
class PropertyLinkSubChild
class PropertyLinkSubGlobal
class PropertyLinkSubHidden
class PropertyLinkSubList
class PropertyLinkSubListChild
class PropertyLinkSubListGlobal
class PropertyLinkSubListHidden
class PropertyLinkT
class PropertyLists
class PropertyListsBase
class PropertyListsT
class PropertyLuminousIntensity
class PropertyMagneticFieldStrength
class PropertyMagneticFlux
class PropertyMagneticFluxDensity
class PropertyMagnetization
class PropertyMap
class PropertyMass
class PropertyMaterial
class PropertyMaterialList
class PropertyMatrix
Property representing a 4x4 matrix.
class PropertyMoment
class PropertyPath
class PropertyPercent
class PropertyPersistentObject
class PropertyPlacement
Property representing a placement.
class PropertyPlacementLink
class PropertyPlacementList
class PropertyPosition
class PropertyPower
class PropertyPrecision
class PropertyPressure
class PropertyPythonObject
class PropertyQuantity
class PropertyQuantityConstraint
class PropertyRotation
Property representing a rotation.
class PropertyShearModulus
class PropertySpecificEnergy
class PropertySpecificHeat
class PropertySpeed
class PropertyStiffness
class PropertyStiffnessDensity
class PropertyStress
class PropertyString
class PropertyStringList
class PropertyTemperature
class PropertyThermalConductivity
class PropertyThermalExpansionCoefficient
class PropertyThermalTransferCoefficient
class PropertyTime
class PropertyUltimateTensileStrength
class PropertyUUID
class PropertyVacuumPermittivity
class PropertyVector
class PropertyVectorDistance
class PropertyVectorList
class PropertyVelocity
class PropertyVolume
class PropertyVolumeFlowRate
class PropertyVolumetricThermalExpansionCoefficient
class PropertyWork
class PropertyXLink
class PropertyXLinkContainer
class PropertyXLinkList
class PropertyXLinkSub
class PropertyXLinkSubHidden
class PropertyXLinkSubList
class PropertyYieldStrength
class PropertyYoungsModulus
class PyObjectExpression
class Range
The Range class is a spreadsheet range iterator. It takes a starting (row, col) and an ending (row, col). Notice that ranges are always at least one element. The next() functions is therefore used e.g as follows:
class RangeExpression
class RelabelDocumentExpressionVisitor
class RenameObjectIdentifierExpressionVisitor
The RenameObjectIdentifierExpressionVisitor class is a functor used to visit each node of an expression, and possibly rename VariableExpression nodes.
class ScopedLink
Enables scope handling for links This class is a base for all link properties and enables them to handle scopes of the linked objects. The possible scopes are defined by LinkScope enum class. The default value is Local. The scope of a property is not saved in the document. It is a value that needs to be fixed when the object holding the property is loaded. That is possible with two methods:
class StringExpression
class StringHasher
A bidirectional map of strings and their integer identifier.
class StringID
class StringIDRef
class SubObjectPlacementProvider
class SubObjectT
class SuppressibleExtension
class SuppressibleExtensionPythonT
class TextDocument
class Transaction
class TransactionalObject
class TransactionDocumentObject
class TransactionFactory
class TransactionLocker
class TransactionObject
class TransactionProducer
class UnitExpression
class UpdateElementReferenceExpressionVisitor
class ValueFloatToRGB
class VariableExpression
class VarSet
class VRMLObject
class WeakPtrT
The WeakPtrT class.
class XMLMergeReader
Typedefs
using VisibilityFlags = Base::Flags< Visibility >
using StringHasherRef = Base::Reference< StringHasher >
using DocumentObjectGroupPython = App::FeaturePythonT< DocumentObjectGroup >
using ExpressionPtr = std::unique_ptr< Expression >
using ExpressionDeps = std::map< App::DocumentObject *, std::map< std::string, std::vector< ObjectIdentifier > > >
using ExtensionPython = ExtensionPythonT< App::Extension >
using FeaturePython = FeaturePythonT< DocumentObject >
using GeometryPython = FeaturePythonT< GeoFeature >
using GeoFeatureGroupExtensionPython = ExtensionPythonT< GroupExtensionPythonT< GeoFeatureGroupExtension > >
using GroupExtensionPython = ExtensionPythonT< GroupExtensionPythonT< GroupExtension > >
using TLicenseArr = std::array< const char *, colsInArray >
using LinkBaseExtensionPython = ExtensionPythonT< LinkBaseExtension >
using LinkExtensionPython = ExtensionPythonT< LinkExtension >
using LinkPython = App::FeaturePythonT< Link >
using LinkElementPython = App::FeaturePythonT< LinkElement >
using LinkGroupPython = App::FeaturePythonT< LinkGroup >
using MaterialObjectPython = App::FeaturePythonT< MaterialObject >
using MeasureSelection = std::vector< MeasureSelectionItem >
using MeasureValidateMethod = std::function< bool(const MeasureSelection &)>
using MeasurePrioritizeMethod = std::function< bool(const MeasureSelection &)>
using MeasureTypeMethod = std::function< MeasureElementType(App::DocumentObject *, const char *)>
using any = boost::any
using OriginGroupExtensionPython = ExtensionPythonT< GroupExtensionPythonT< OriginGroupExtension > >
using PlacementPython = App::FeaturePythonT< App::Placement >
using HasherMap = boost::bimap< StringHasherRef, int >
using DocInfoPtr = std::shared_ptr< DocInfo >
using SuppressibleExtensionPython = ExtensionPythonT< SuppressibleExtensionPythonT< SuppressibleExtension > >
Enumerations
enum GetLinkOption { GetLinkRecursive = 1, GetLinkArrayElement = 2, GetLinkedObject = 4, GetLinkExternal = 8 }
enum MessageOption { MessageOption::Quiet, Error, MessageOption::Throw }
enum Visibility { Visibility::Default, Visibility::Grayed, Visibility::Invisible }
enum ColorBarStyle { ColorBarStyle::FLOW, ColorBarStyle::ZERO_BASED }
enum ObjectStatus {
Touch = 0, Error = 1, Error, New = 2,
Recompute = 3, Restore = 4, Remove = 5, PythonCall = 6,
Destroy = 7, Enforce = 8, Recompute2 = 9, PartialObject = 10,
PendingRecompute = 11, ObjImporting = 13, NoTouch = 14, GeoExcluded = 15,
Expand = 16, NoAutoExpand = 17, PendingTransactionUpdate = 18, RecomputeExtension = 19,
TouchOnColorChange = 20, Freeze = 21
}
enum MeasureElementType {
MeasureElementType::INVALID, MeasureElementType::POINT, MeasureElementType::LINE, MeasureElementType::LINESEGMENT,
MeasureElementType::CIRCLE, MeasureElementType::ARC, MeasureElementType::CURVE, MeasureElementType::PLANE,
MeasureElementType::CYLINDER, MeasureElementType::Volume
}
enum PropertyType {
Prop_None = 0, Prop_ReadOnly = 1, Prop_Transient = 2, Prop_Hidden = 4,
Prop_Output = 8, Prop_NoRecompute = 16, Prop_NoPersist = 32
}
enum LinkScope { LinkScope::Local, LinkScope::Child, LinkScope::Global, LinkScope::Hidden }
Defines different scopes for which a link can be valid The scopes defined in this enum describe the different possibilities of where a link can point to. Local: links are valid only within the same GeoFeatureGroup as the linkowner is in or in none. Child: links are valid within the same or any sub GeoFeatureGroup Global: all possible links are valid Hidden: links are not included in dependency calculation.
Functions
App::Application & GetApplication ()
Singleton getter of the Application.
Py::Object pyObjectFromAny (const App::any &value)
App::any pyObjectToAny (Py::Object value, bool check)
bool pyToQuantity (Quantity &q, const Py::Object &pyobj)
static Quantity pyToQuantity (const Py::Object &pyobj, const Expression *e, const char *msg=nullptr)
Py::Object pyFromQuantity (const Quantity &quantity)
Quantity anyToQuantity (const App::any &value, const char *msg)
static bool anyToLong (long &res, const App::any &value)
static bool anyToDouble (double &res, const App::any &value)
bool isAnyEqual (const App::any &v1, const App::any &v2)
Expression * expressionFromPy (const DocumentObject *owner, const Py::Object &value)
constexpr int findLicense (const char *identifier)
template<class T >
const T & any_cast (const boost::any &value)
template<class T >
T & any_cast (boost::any &value)
AppExport std::string quote (const std::string &input, bool toPython=false)
Quote input string according to quoting rules for an expression: because " and ' are used to designate inch and foot units, strings are quoted as <<string>>.
std::size_t hash_value (const App::ObjectIdentifier &path)
const char * getNameFromFile (PyObject *value)
bool isIOFile (PyObject *file)
bool maybeAbsolute (std::string_view address)
AppExport CellAddress stringToAddress (const char *strAddress, bool silent=false)
Convert a string address into integer row and column. row and col are 0-based.
AppExport int decodeColumn (const std::string &colstr, bool silent=false)
Decode a column name string into a 0-based integer.
AppExport int decodeRow (const std::string &rowstr, bool silent=false)
Decode a row specification into a 0-based integer.
AppExport bool validColumn (const std::string &colstr)
Determine if a string is a valid column specification.
AppExport int validRow (const std::string &rowstr)
Determine whether a row specification is valid or not.
Variables
static bool globalIsRestoring
static bool globalIsRelabeling
template class AppExport ExtensionPythonT< Extension >
template class AppExport FeaturePythonT< DocumentObject >
template class AppExport FeaturePythonT< GeoFeature >
template class AppExport ExtensionPythonT< GroupExtensionPythonT< GeoFeatureGroupExtension > >
template class AppExport ExtensionPythonT< GroupExtensionPythonT< GroupExtension > >
constexpr int colsInArray = 3
constexpr int posnOfIdentifier = 0
constexpr int posnOfFullName = 1
constexpr int posnOfUrl = 2
constexpr int countOfLicenses {18}
constexpr std::array< TLicenseArr, countOfLicenses > licenseItems
template class AppExport ExtensionPythonT< LinkBaseExtension >
template class AppExport ExtensionPythonT< GroupExtensionPythonT< OriginGroupExtension > >
template class AppExport ExtensionPythonT< SuppressibleExtensionPythonT< SuppressibleExtension > >
Detailed Description
a class to assist with exporting sketches to dxf
CommandHelpers is a collection of methods for common actions in commands.
Typedef Documentation
any
using App::any = typedef boost::any
Definition at line 44 of file ObjectIdentifier.h.
DocInfoPtr
using App::DocInfoPtr = typedef std::shared_ptr<DocInfo>
Definition at line 49 of file PropertyLinks.h.
DocumentObjectGroupPython
using App::DocumentObjectGroupPython = typedef App::FeaturePythonT<DocumentObjectGroup>
Definition at line 74 of file DocumentObjectGroup.h.
ExpressionDeps
using App::ExpressionDeps = typedef std::map<App::DocumentObject*, std::map<std::string, std::vector<ObjectIdentifier> > >
Definition at line 55 of file Expression.h.
ExpressionPtr
typedef std::unique_ptr< Expression > App::ExpressionPtr
Definition at line 48 of file Expression.h.
ExtensionPython
using App::ExtensionPython = typedef ExtensionPythonT<App::Extension>
Definition at line 79 of file ExtensionPython.h.
FeaturePython
using App::FeaturePython = typedef FeaturePythonT<DocumentObject>
Definition at line 426 of file FeaturePython.h.
GeoFeatureGroupExtensionPython
using App::GeoFeatureGroupExtensionPython = typedef ExtensionPythonT<GroupExtensionPythonT<GeoFeatureGroupExtension> >
Definition at line 177 of file GeoFeatureGroupExtension.h.
GeometryPython
using App::GeometryPython = typedef FeaturePythonT<GeoFeature>
Definition at line 427 of file FeaturePython.h.
GroupExtensionPython
using App::GroupExtensionPython = typedef ExtensionPythonT<GroupExtensionPythonT<GroupExtension> >
Definition at line 201 of file GroupExtension.h.
HasherMap
using App::HasherMap = typedef boost::bimap<StringHasherRef, int>
Definition at line 58 of file DocumentP.h.
LinkBaseExtensionPython
using App::LinkBaseExtensionPython = typedef ExtensionPythonT<LinkBaseExtension>
Definition at line 505 of file Link.h.
LinkElementPython
using App::LinkElementPython = typedef App::FeaturePythonT<LinkElement>
Definition at line 723 of file Link.h.
LinkExtensionPython
using App::LinkExtensionPython = typedef ExtensionPythonT<LinkExtension>
Definition at line 618 of file Link.h.
LinkGroupPython
using App::LinkGroupPython = typedef App::FeaturePythonT<LinkGroup>
Definition at line 757 of file Link.h.
LinkPython
using App::LinkPython = typedef App::FeaturePythonT<Link>
Definition at line 672 of file Link.h.
MaterialObjectPython
using App::MaterialObjectPython = typedef App::FeaturePythonT<MaterialObject>
Definition at line 72 of file MaterialObject.h.
MeasurePrioritizeMethod
using App::MeasurePrioritizeMethod = typedef std::function<bool(const MeasureSelection&)>
Definition at line 87 of file MeasureManager.h.
MeasureSelection
using App::MeasureSelection = typedef std::vector<MeasureSelectionItem>
Definition at line 85 of file MeasureManager.h.
MeasureTypeMethod
using App::MeasureTypeMethod = typedef std::function<MeasureElementType(App::DocumentObject*, const char*)>
Definition at line 88 of file MeasureManager.h.
MeasureValidateMethod
using App::MeasureValidateMethod = typedef std::function<bool(const MeasureSelection&)>
Definition at line 86 of file MeasureManager.h.
OriginGroupExtensionPython
using App::OriginGroupExtensionPython = typedef ExtensionPythonT<GroupExtensionPythonT<OriginGroupExtension> >
Definition at line 115 of file OriginGroupExtension.h.
PlacementPython
using App::PlacementPython = typedef App::FeaturePythonT<App::Placement>
Definition at line 70 of file App/Placement.h.
StringHasherRef
typedef Base::Reference< StringHasher > App::StringHasherRef
Definition at line 55 of file App/Document.h.
SuppressibleExtensionPython
using App::SuppressibleExtensionPython = typedef ExtensionPythonT<SuppressibleExtensionPythonT<SuppressibleExtension> >
Definition at line 80 of file SuppressibleExtension.h.
TLicenseArr
using App::TLicenseArr = typedef std::array<const char*, colsInArray>
Definition at line 58 of file License.h.
VisibilityFlags
using App::VisibilityFlags = typedef Base::Flags<Visibility>
Definition at line 66 of file ColorModel.h.
Enumeration Type Documentation
ColorBarStyle
enum App::ColorBarStyle strong
Enumerator
FLOW
ZERO_BASED
Definition at line 68 of file ColorModel.h.
GetLinkOption
enum App::GetLinkOption
Enumerator
GetLinkRecursive
Get all links (both directly and in directly) linked to the given object.
GetLinkArrayElement
Get link array element instead of the array.
GetLinkedObject
Get linked object instead of the link, no effect if GetLinkRecursive.
GetLinkExternal
Get only external links, no effect if GetLinkRecursive.
Definition at line 55 of file App/Application.h.
LinkScope
enum App::LinkScope strong
Defines different scopes for which a link can be valid The scopes defined in this enum describe the different possibilities of where a link can point to. Local: links are valid only within the same GeoFeatureGroup as the linkowner is in or in none. Child: links are valid within the same or any sub GeoFeatureGroup Global: all possible links are valid Hidden: links are not included in dependency calculation.
Enumerator
Local
Child
Global
Hidden
Definition at line 60 of file PropertyLinks.h.
MeasureElementType
enum App::MeasureElementType strong
Enumerator
INVALID
POINT
LINE
LINESEGMENT
CIRCLE
ARC
CURVE
PLANE
CYLINDER
Volume
Definition at line 63 of file MeasureManager.h.
MessageOption
enum App::MessageOption strong
Enumerator
Quiet
Suppress error.
Error
Print an error message.
Throw
Throw an exception.
Definition at line 66 of file App/Application.h.
ObjectStatus
enum App::ObjectStatus
Enumerator
Touch
Error
Error
Print an error message.
New
Recompute
Restore
Remove
PythonCall
Destroy
Enforce
Recompute2
PartialObject
PendingRecompute
ObjImporting
NoTouch
GeoExcluded
Expand
NoAutoExpand
PendingTransactionUpdate
RecomputeExtension
TouchOnColorChange
Freeze
Definition at line 50 of file DocumentObject.h.
PropertyType
enum App::PropertyType
Enumerator
Prop_None
No special property type
Prop_ReadOnly
Property is read-only in the editor
Prop_Transient
Property content won't be saved to file, but still saves name, type and status
Prop_Hidden
Property won't appear in the editor
Prop_Output
Modified property doesn't touch its parent container
Prop_NoRecompute
Modified property doesn't touch its container for recompute
Prop_NoPersist
Property won't be saved to file at all
Definition at line 46 of file PropertyContainer.h.
Visibility
enum App::Visibility strong
Enumerator
Default
Grayed
Invisible
Definition at line 59 of file ColorModel.h.
Function Documentation
any_cast() [1/2]
template<class T > T& App::any_cast (boost::any & value) inline
Definition at line 53 of file ObjectIdentifier.h.
any_cast() [2/2]
template<class T > const T& App::any_cast (const boost::any & value) inline
Definition at line 47 of file ObjectIdentifier.h.
anyToDouble()
static bool App::anyToDouble (double & res, const App::any & value) inline static
Definition at line 551 of file Expression.cpp.
References is_type().
Referenced by isAnyEqual().
anyToLong()
static bool App::anyToLong (long & res, const App::any & value) inline static
Definition at line 539 of file Expression.cpp.
References is_type().
Referenced by isAnyEqual().
anyToQuantity()
AppExport Base::Quantity App::anyToQuantity (const App::any & value, const char * msg)
Definition at line 520 of file Expression.cpp.
References is_type(), Path.Op.Surface::msg, src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::Quantity, and TYPE_THROW.
Referenced by isAnyEqual(), and App::PropertyQuantity::setPathValue().
decodeColumn()
int App::decodeColumn (const std::string & colstr, bool silent = false)
Decode a column name string into a 0-based integer.
Parameters
colstr input string.
Returns
The column.
Definition at line 184 of file Range.cpp.
References columnStringToNum(), and validColumn().
Referenced by App::FeatureTestColumn::execute(), Spreadsheet::PropertyColumnWidths::Restore(), and stringToAddress().
decodeRow()
int App::decodeRow (const std::string & rowstr, bool silent = false)
Decode a row specification into a 0-based integer.
Parameters
rowstr Row specified as a string, with "1" being the first row.
Returns
The row.
Definition at line 150 of file Range.cpp.
References validRow().
Referenced by App::FeatureTestRow::execute(), Spreadsheet::PropertyRowHeights::Restore(), and stringToAddress().
expressionFromPy()
Expression* App::expressionFromPy (const DocumentObject * owner, const Py::Object & value)
Definition at line 641 of file Expression.cpp.
References pyToQuantity(), and src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::Quantity.
Referenced by App::Expression::eval().
findLicense()
constexpr int App::findLicense (const char * identifier) constexpr
Definition at line 86 of file License.h.
GetApplication()
App::Application& App::GetApplication () inline
Singleton getter of the Application.
Definition at line 645 of file App/Application.h.
Referenced by App::Document::_checkTransaction(), App::Document::_commitTransaction(), _copyShape(), Gui::Command::_copyVisual(), ExpressionCompleterModel::_data(), _GetParam(), App::Document::_openTransaction(), _replaceDirs(), Gui::Document::_resetEdit(), Gui::Command::abortCommand(), App::Document::abortTransaction(), PartGui::Mirroring::accept(), Gui::Dialog::DlgAddProperty::accept(), SpreadsheetGui::DlgBindSheet::accept(), PartGui::DlgBooleanOperation::accept(), MeshGui::Segmentation::accept(), ReverseEngineeringGui::Segmentation::accept(), PartGui::DlgRevolution::accept(), PartDesignGui::DlgActiveBody::accept(), Gui::Dialog::DlgRevertToBackupConfigImp::accept(), Gui::Dialog::DocumentRecovery::accept(), PartGui::DlgFilletEdges::accept(), MeshPartGui::Tessellation::accept(), Gui::Dialog::DlgAddPropertyVarSet::accept(), MeshGui::SegmentationBestFit::accept(), Gui::ElementColors::Private::accept(), DrawingGui::TaskDlgOrthoViews::accept(), App::TransactionLocker::activate(), PartDesignGui::Workbench::activated(), StdCmdLinkMakeGroup::activated(), StdCmdOpen::activated(), Gui::StdCmdDownloadOnlineHelp::activated(), StdCmdImport::activated(), StdCmdLinkMake::activated(), StdCmdLinkMakeRelative::activated(), StdCmdExport::activated(), StdCmdDlgPreferences::activated(), StdCmdMergeProjects::activated(), StdCmdOnlineHelpWebsite::activated(), CmdSandboxMeshLoader::activated(), StdCmdFreeCADDonation::activated(), StdCmdDependencyGraph::activated(), StdCmdFreeCADWebsite::activated(), StdCmdLinkImportAll::activated(), StdCmdExportDependencyGraph::activated(), StdCmdFreeCADUserHub::activated(), StdCmdFreeCADPowerUserHub::activated(), StdCmdNew::activated(), StdCmdFreeCADForum::activated(), StdCmdFreeCADFAQ::activated(), StdCmdReportBug::activated(), Gui::MacroCommand::activated(), StdCmdUserEditMode::activated(), StdCmdToggleSelectability::activated(), StdCmdDuplicateSelection::activated(), StdCmdViewHome::activated(), StdCmdSelectAll::activated(), StdCmdExpression::activated(), StdViewScreenShot::activated(), CmdSketcherConstrainLock::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadiam::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), Gui::Application::activateWorkbench(), Gui::MainWindow::activateWorkbench(), Gui::ParamHandlers::addDelayedHandler(), App::DynamicProperty::addDynamicProperty(), Gui::ParamHandlers::addHandler(), Gui::Dialog::DlgSettingsNavigation::addOrientations(), App::Document::addOrRemovePropertyOfObject(), Gui::WorkbenchGroup::addTo(), App::Document::afterRestore(), Gui::RecentMacrosAction::appendFile(), Gui::Application::Application(), PartGui::DlgScale::apply(), PartGui::DlgExtrusion::apply(), Gui::ExpressionBinding::apply(), Gui::PreferencePack::apply(), Gui::TaskMeasure::apply(), Gui::ElementColors::Private::apply(), CmdSketcherConstrainLock::applyConstraint(), Gui::ViewProviderLine::attach(), Gui::ViewProviderPlane::attach(), Gui::ViewProviderDatum::attach(), RobotGui::ViewProviderTrajectory::attach(), Gui::ViewProviderPoint::attach(), PartDesignGui::ViewProviderDatumPoint::attach(), App::DocInfo::attach(), Gui::Dialog::DlgSettingsGeneral::attachObserver(), App::AutoTransaction::AutoTransaction(), Gui::Gui::GestureNavigationStyle ::AwaitingMoveState::AwaitingMoveState(), PartDesign::Body::Body(), PartDesignGui::TaskFeaturePick::buildFeatures(), checkCanonicalPath(), checkFileName(), Gui::Application::checkForDeprecatedSettings(), Gui::Application::checkForRecomputes(), Fem::Tools::checkIfBinaryExists(), App::Document::clearDocument(), App::AutoTransaction::close(), Gui::MainWindow::closeAllDocuments(), Gui::Dialog::DlgParameterImp::closeEvent(), Cloud::Module::cloudRestore(), Cloud::Module::cloudSave(), CmdSketcherConstrainCoincident::CmdSketcherConstrainCoincident(), CmdSketcherConstrainCoincidentUnified::CmdSketcherConstrainCoincidentUnified(), Gui::Command::commitCommand(), Gui::GUIApplication::commitData(), App::Document::commitTransaction(), StartGui::StartView::configureRecentFilesListWidget(), Gui::MainWindow::confirmSave(), SketcherGui::ConstraintFilterList::ConstraintFilterList(), Sketcher::SketchObject::constraintsRenamed(), Gui::TreeWidget::contextMenuEvent(), copyTemplateParameters(), Gui::Dialog::AboutDialog::copyToClipboard(), Part::Feature::create(), StdCmdUserEditMode::createAction(), createDefaultExportBasename(), Gui::TreeWidgetItemDelegate::createEditor(), PartGui::ViewProvider2DObjectGrid::createGrid(), MatGui::MaterialTreeWidget::createLayout(), Gui::Workbench::createLinkMenu(), Fem::createObjectByType(), DrawSketchHandlerDimension::createRadiusDiameterConstrain(), TDHandlerDimension::createRadiusDiameterDimension(), createVarSetTreeWidget(), Gui::CreateViewStdCommands(), SketcherGui::CurveConverter::CurveConverter(), Gui::View3DInventor::customEvent(), Import::ExportOCAF2::customExportOptions(), Import::ImportOCAF2::customImportOptions(), ConstraintItem::data(), Materials::MaterialManager::defaultAppearance(), Materials::MaterialManager::defaultMaterialUUID(), Gui::ViewProviderCoordinateSystem::defaultSize(), SketcherGui::ConstraintView::deleteSelectedItems(), SketcherGui::ElementView::deleteSelectedItems(), TechDrawGui::QGVPage::Private::detach(), Gui::Dialog::DlgAddProperty::DlgAddProperty(), SpreadsheetGui::DlgBindSheet::DlgBindSheet(), PartGui::DlgBooleanOperation::DlgBooleanOperation(), Gui::Dialog::DlgCustomActionsImp::DlgCustomActionsImp(), MeshGui::DlgEvaluateMeshImp::DlgEvaluateMeshImp(), Gui::Dialog::DlgExpressionInput::DlgExpressionInput(), PartGui::DlgFilletEdges::DlgFilletEdges(), Gui::Dialog::DlgParameterImp::DlgParameterImp(), PartGui::DlgProjectionOnSurface::DlgProjectionOnSurface(), PartGui::DlgSettings3DViewPart::DlgSettings3DViewPart(), FemGui::DlgSettingsFemGeneralImp::DlgSettingsFemGeneralImp(), Gui::Dialog::DlgSettingsMacroImp::DlgSettingsMacroImp(), Gui::SoFCUnifiedSelection::doAction(), Gui::Document::Document(), App::Document::Document(), Gui::DocumentItem::DocumentItem(), App::DocumentObserver::DocumentObserver(), Gui::DialogOptions::dontUseNativeColorDialog(), Gui::DialogOptions::dontUseNativeFileDialog(), doSelect(), SpreadsheetGui::ViewProviderSheet::doubleClicked(), AssemblyGui::ViewProviderAssembly::doubleClicked(), DrawingGui::DrawingView::DrawingView(), dressupGetSelected(), Gui::MainWindow::dropEvent(), Gui::ElementColors::ElementColors(), SketcherGui::ElementFilterList::ElementFilterList(), AssemblyGui::ViewProviderAssembly::endMove(), Gui::MainWindow::event(), Gui::PropertyEditor::PropertyEditor::eventFilter(), Assembly::AssemblyObject::execute(), expandSubObjectNames(), Gui::GraphvizView::exportGraph(), App::Document::exportGraphviz(), Gui::SelectModule::exportHandler(), App::PropertyLinkBase::exportSubName(), Gui::Application::exportTo(), MeshGui::ViewProviderMesh::faceInfoCallback(), FemGui::FemSettings::FemSettings(), Gui::PythonTracing::fetchFromSettings(), FileCardDelegate::FileCardDelegate(), MatGui::MaterialTreeWidget::fillMaterialTree(), TDHandlerDimension::finalizeCommand(), DrawSketchHandlerDimension::finalizeCommand(), TechDrawGui::DrawGuiUtil::findPage(), PartGui::DlgScale::findShapes(), PartGui::DlgExtrusion::findShapes(), PartGui::DlgFilletEdges::findShapes(), finishDatumConstraint(), StartGui::StartView::firstStartWidgetDismissed(), Gui::GestureNavigationStyle::GestureNavigationStyle(), Gui::Gui::GestureNavigationStyle ::GestureState::GestureState(), App::DocInfo::get(), TechDrawGui::PreferencesGui::get3dMarkerSize(), Gui::ViewProviderDocumentObject::getActiveView(), getAllVarSets(), PartGui::DlgExtrusion::getAxisLink(), PartGui::DlgRevolution::getAxisLink(), PathGui::ViewProviderPath::getBoundColor(), Gui::ViewProviderGeometryObject::getBoundColor(), Spreadsheet::Sheet::getCharsFromPrefs(), Gui::ToolHandler::getCrosshairColor(), Path::Toolpath::getCycleTime(), App::Material::getDefaultAppearance(), Gui::WindowParameter::getDefaultParameter(), Gui::Dialog::DlgSettingsWorkbenchesImp::getDisabledWorkbenches(), App::DocumentT::getDocument(), App::DocumentObjectT::getDocument(), Gui::Application::getDocument(), Gui::Command::getDocument(), App::ObjectIdentifier::getDocument(), Gui::SelectionSingleton::getDocument(), Gui::Dialog::DlgSettingsWorkbenchesImp::getEnabledWorkbenches(), MatGui::MaterialTreeWidget::getFavorites(), PartDesignGui::TaskFeaturePick::getFeatures(), Gui::View3DInventorViewer::getInternalTextureFormat(), App::LinkBaseExtension::getLink(), App::Document::getLinksTo(), Materials::MaterialLoader::getMaterialLibraries(), TechDrawGui::QGVPage::getNavStyleParameter(), Gui::SelectionObject::getObject(), Gui::Command::getObjectCmd(), MeshGui::MeshSelection::getObjects(), TechDrawGui::QGIView::getParmGroupCol(), getPreferencesViewParameter(), MatGui::MaterialTreeWidget::getRecents(), Part::getRefineModelParameter(), Attacher::AttachEngine::getRefObjects(), PartGui::DlgExtrusion::getShapesToExtrude(), PartGui::DlgRevolution::getShapesToRevolve(), PartGui::DlgScale::getShapesToScale(), getSketcherGeneralParameter(), Part::Feature::getSubObject(), PartDesign::SubShapeBinder::getSubObject(), Gui::Command::getUniqueObjectName(), PartGui::TaskCheckGeometryResults::goCheck(), Gui::GraphicsView3D::GraphicsView3D(), Gui::GraphvizView::GraphvizView(), Gui::Command::hasPendingCommand(), StartGui::FileCardView::heightForWidth(), SketcherGui::hideUnits(), horVerActivated(), TechDrawGui::DrawGuiUtil::iconForLine(), Gui::Application::importFrom(), Gui::SelectModule::importHandler(), Gui::Dialog::DlgPropertyLink::init(), App::DocInfo::init(), TechDrawGui::QGVNavStyle::initialize(), Gui::NavigationStyle::initialize(), Gui::InputField::InputField(), Gui::MainWindow::insertFromMimeData(), Gui::BitmapFactoryInst::instance(), StdCmdLinkMakeGroup::isActive(), StdCmdCloseAllWindows::isActive(), StdCmdLinkMake::isActive(), StdCmdLinkImportAll::isActive(), StdCmdLinkSelectAllLinks::isActive(), StdCmdSelectVisibleObjects::isActive(), StdCmdToggleObjects::isActive(), StdCmdShowObjects::isActive(), StdCmdHideObjects::isActive(), StdCmdSelectAll::isActive(), StdCmdExpression::isActive(), Gui::ExpressionParameter::isCaseSensitive(), Gui::ExpressionParameter::isExactMatch(), PartDesignGui::TaskFeaturePick::isSingleSelectionEnabled(), Gui::PreferencePackManager::isVisible(), Gui::WorkbenchTabWidget::itemStyle(), AssemblyGui::ViewProviderAssembly::keyPressed(), StartGui::StartLauncher::Launch(), Cloud::Module::LinkXSetValue(), Gui::MacroCommand::load(), TechDrawGui::DrawGuiUtil::loadArrowBox(), TechDrawGui::DrawGuiUtil::loadBalloonShapeBox(), TechDrawGui::DrawGuiUtil::loadMattingStyleBox(), PartGui::ViewProviderPartExt::loadParameter(), InspectionGui::VisualInspection::loadSettings(), Gui::Dialog::DlgSettingsNavigation::loadSettings(), Gui::Dialog::DlgSettingsGeneral::loadSettings(), TechDrawGui::DlgPrefsTechDrawDimensionsImp::loadSettings(), FemGui::DlgSettingsFemExportAbaqusImp::loadSettings(), FemGui::DlgSettingsFemInOutVtkImp::loadSettings(), SpreadsheetGui::DlgSettingsImp::loadSettings(), FemGui::DlgSettingsFemGmshImp::loadSettings(), MeshGui::DlgSettingsImportExport::loadSettings(), SketcherGui::SketcherSettings::loadSettings(), FemGui::DlgSettingsFemZ88Imp::loadSettings(), FemGui::DlgSettingsFemCcxImp::loadSettings(), Gui::Dialog::DlgSettingsNotificationArea::loadSettings(), Gui::Dialog::DlgSettingsWorkbenchesImp::loadSettings(), SketcherGui::SketcherSettingsGrid::loadSettings(), SketcherGui::SketcherSettingsAppearance::loadSettings(), Gui::DockWindowManager::loadState(), Gui::Dialog::DlgSettingsGeneral::loadThemes(), Gui::MainWindow::loadUrls(), Gui::MacroManager::MacroManager(), Gui::MainWindow::MainWindow(), PartDesignGui::TaskFeaturePick::makeCopy(), MeshGui::ViewProviderMeshDefects::makeMarkerSet(), Assembly::AssemblyObject::makeMbdAssembly(), Materials::MaterialFilterOptions::MaterialFilterOptions(), Materials::MaterialFilterTreeWidgetOptions::MaterialFilterTreeWidgetOptions(), Gui::DAG::Model::Model(), ExpressionCompleterModel::modelIndexToParentInfo(), TechDrawGui::QGIViewAnnotation::mouseDoubleClickEvent(), TechDrawGui::QGIRichAnno::mouseDoubleClickEvent(), TechDrawGui::DrawGuiUtil::needPage(), Gui::Notify(), CmdSketcherConstrainCoincidentUnified::onActivated(), Gui::Dialog::DlgParameterImp::onButtonSaveToDiskClicked(), SketcherGui::TaskSketcherConstraints::OnChange(), PathGui::ViewProviderPath::onChanged(), PartDesignGui::ViewProviderSubShapeBinder::onChanged(), Assembly::AssemblyLink::onChanged(), App::Document::onChanged(), Gui::Dialog::DlgParameterImp::onChangeParameterSet(), SketcherGui::TaskSketcherElements::onFilterBoxStateChanged(), SketcherGui::TaskSketcherConstraints::onFilterBoxStateChanged(), SketcherGui::TaskSketcherConstraints::onFilterListItemChanged(), Gui::Dialog::DlgSettingsGeneral::onLinkActivated(), SketcherGui::TaskSketcherElements::onListMultiFilterItemChanged(), Gui::TreeWidget::onReloadDoc(), Gui::GestureNavigationStyle::onRollGesture(), SketcherGui::TaskSketcherConstraints::onSettingsAutoConstraintsChanged(), SketcherGui::TaskSketcherConstraints::onSettingsAutoRemoveRedundantChanged(), SketcherGui::TaskSketcherElements::onSettingsExtendedInformationChanged(), SketcherGui::TaskSketcherConstraints::onSettingsExtendedInformationChanged(), SketcherGui::TaskSketcherConstraints::onSettingsHideInternalAligmentChanged(), SketcherGui::TaskSketcherConstraints::onSettingsRestrictVisibilityChanged(), Gui::OverlayManager::Private::onTimer(), Gui::Application::open(), TechDrawGui::TaskDlgProjGroup::open(), Gui::Command::openCommand(), Gui::PropertyEditor::PropertyEditor::openEditor(), App::Document::openTransaction(), DrawingGui::OrthoViews::OrthoViews(), OverlayInfo::OverlayInfo(), OverlayStyleSheet::OverlayStyleSheet(), Gui::NotificationArea::ParameterObserver::ParameterObserver(), App::PropertyXLink::Paste(), SpreadsheetGui::SheetTableView::pasteClipboard(), StdCmdExpression::pasteExpressions(), FemGui::DlgSettingsFemGmshImp::populateLogVerbosity(), Gui::Dialog::DlgSettingsUI::populateStylesheets(), StartGui::StartView::postStart(), TechDrawGui::MDIViewPage::printAllPages(), TechDrawGui::QGVPage::Private::Private(), App::DocumentWeakPtrT::Private::Private(), Gui::RecentFilesAction::Private::Private(), App::Application::processCmdLineFiles(), App::Application::processFiles(), Gui::PropertyEditor::PropertyEditor::PropertyEditor(), App::PropertyExpressionContainer::PropertyExpressionContainer(), Gui::PropertyView::PropertyView(), PyMOD_INIT_FUNC(), Import::ReaderIges::read(), Gui::Multisample::readMSAAFromSettings(), Start::RecentFilesModel::RecentFilesModel(), App::Document::recompute(), Gui::Document::redo(), Gui::OverlayTabWidget::refreshIcons(), Gui::WorkbenchComboBox::refreshList(), SketcherGui::TaskDlgEditSketch::reject(), Gui::TaskMeasure::reject(), DrawingGui::TaskDlgOrthoViews::reject(), DrawSketchHandlerBSplineInsertKnot::releaseButton(), App::DynamicProperty::removeDynamicProperty(), Gui::Application::reopen(), Gui::ViewProviderDocumentObject::replaceObject(), Gui::Application::replaceVariablesInQss(), Gui::ElementColors::Private::reset(), Gui::Dialog::DlgSettings3DViewImp::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsNavigation::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsGeneral::resetSettingsToDefaults(), TechDrawGui::DlgPrefsTechDrawDimensionsImp::resetSettingsToDefaults(), SketcherGui::SketcherSettings::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsWorkbenchesImp::resetSettingsToDefaults(), Gui::Dialog::PreferencePage::resetSettingsToDefaults(), Gui::ViewProviderDatum::resetTemporarySize(), ZoomableView::resetZoom(), App::Document::restore(), Part::PropertyPartShape::RestoreDocFile(), Gui::FileDialog::restoreLocation(), Gui::MDIView::restorePrinterSettings(), Sandbox::DocumentThread::run(), Gui::GraphvizWorker::run(), Sandbox::DocumentTestThread::run(), Gui::MacroManager::run(), Gui::Document::Save(), App::Document::save(), Gui::MacroCommand::save(), Gui::Document::saveAll(), Gui::Document::saveAs(), Gui::Document::saveCopy(), Gui::Thumbnail::SaveDocFile(), Part::PropertyPartShape::SaveDocFile(), Gui::AutoSaver::saveDocument(), Gui::FileDialog::saveLocation(), MatGui::MaterialTreeWidget::saveMaterialTree(), MeshPartGui::Tessellation::saveParameters(), Gui::View3DInventorViewer::savePicture(), Gui::MDIView::savePrinterSettings(), MatGui::MaterialTreeWidget::saveRecents(), InspectionGui::VisualInspection::saveSettings(), Gui::Dialog::DlgSettingsNavigation::saveSettings(), Gui::Dialog::DlgSettingsGeneral::saveSettings(), PartGui::DlgSettings3DViewPart::saveSettings(), TechDrawGui::DlgPrefsTechDrawDimensionsImp::saveSettings(), FemGui::DlgSettingsFemExportAbaqusImp::saveSettings(), FemGui::DlgSettingsFemInOutVtkImp::saveSettings(), SpreadsheetGui::DlgSettingsImp::saveSettings(), SketcherGui::SketcherSettings::saveSettings(), MeshGui::DlgSettingsImportExport::saveSettings(), FemGui::DlgSettingsFemZ88Imp::saveSettings(), FemGui::DlgSettingsFemCcxImp::saveSettings(), Gui::Dialog::DlgSettingsNotificationArea::saveSettings(), Gui::Dialog::DlgSettingsWorkbenchesImp::saveSettings(), SketcherGui::SketcherSettingsGrid::saveSettings(), SketcherGui::SketcherSettingsAppearance::saveSettings(), Gui::Dialog::DlgSettingsGeneral::saveThemes(), App::Document::saveToFile(), Gui::RecentFilesAction::Private::saveUserParameter(), MatGui::MaterialTreeWidget::saveWidgetSettings(), Gui::TreeWidget::selectAll(), Gui::TreeWidget::selectAllLinks(), Gui::SelectionSingleton::SelectionSingleton(), Gui::TreeWidget::selectLinkedObject(), Gui::SelectionSingleton::selStackPush(), App::DocumentObjectWeakPtrT::Private::set(), App::PropertyXLink::setAllowPartial(), Gui::QuantitySpinBox::setBoundToByName(), SketcherGui::ViewProviderSketch::setEditViewer(), App::AutoTransaction::setEnable(), Gui::ExpressionBinding::setExpression(), Gui::WindowParameter::setGroupName(), Gui::DocumentObjectItem::setHighlight(), Gui::Dialog::DlgCheckableMessageBox::setIconPixmap(), Import::ImpExpDxfRead::setOptions(), Import::ImpExpDxfWrite::setOptions(), Gui::StatefulLabel::setParameterGroup(), Gui::InputField::setParamGrpPath(), PartDesignGui::TaskBoxPrimitives::setPrimitive(), Gui::MenuManager::setup(), Gui::ToolBarManager::setup(), Gui::StartupProcess::setupApplication(), Gui::StdWorkbench::setupDockWindows(), Sketcher::SketchObject::setupObject(), FemGui::ViewProviderFemPostObject::setupPipeline(), Gui::AbstractSplitView::setupSettings(), TechDrawGui::Workbench::setupToolBars(), PartDesignGui::TaskDressUpParameters::setupTransaction(), PartDesignGui::TaskTransformedParameters::setupTransaction(), Gui::DimensionWidget::setUserSchema(), App::PropertyString::setValue(), Gui::SelectionSingleton::setVisible(), Gui::MainWindow::setWindowTitle(), Gui::ApplicationPy::sGetMarkerIndex(), SpreadsheetGui::SheetModel::SheetModel(), Gui::TaskView::TaskWatcherCommandsEmptyDoc::shouldShow(), Gui::TaskView::TaskWatcherCommandsEmptySelection::shouldShow(), Gui::Dialog::DlgPreferencePackManagementImp::showAddonManager(), SketcherGui::showCursorCoords(), Gui::Dialog::DlgParameterImp::showEvent(), StartGui::StartView::showOnStartupChanged(), PartDesignGui::TaskHelixParameters::showPreview(), ShowRestoreInformationLayer(), Gui::View3DInventorViewer::showRotationCenter(), SketcherGui::SketcherAddWorkbenchConstraints< Gui::MenuItem >(), SketcherGui::SketcherAddWorkbenchConstraints< Gui::ToolBarItem >(), Gui::ApplicationPy::sLoadFile(), Gui::Application::slotActiveDocument(), Gui::DocumentItem::slotInEdit(), Gui::Document::slotSkipRecompute(), MeshGui::ViewProviderMesh::splitMesh(), Gui::ApplicationPy::sReload(), Gui::View3DInventorViewer::startAnimation(), MeshGui::MeshFillHole::startEditing(), Gui::MainWindow::startSplasher(), Gui::StatefulLabel::StatefulLabel(), StdCmdRefresh::StdCmdRefresh(), Gui::OverlayTabWidget::syncAutoMode(), App::LinkBaseExtension::syncCopyOnChange(), PartGui::TaskCheckGeometryDialog::TaskCheckGeometryDialog(), FemGui::TaskCreateElementSet::TaskCreateElementSet(), SketcherGui::TaskDlgEditSketch::TaskDlgEditSketch(), PartDesignGui::TaskDressUpParameters::TaskDressUpParameters(), PartDesignGui::TaskHoleParameters::TaskHoleParameters(), Gui::TaskMeasure::TaskMeasure(), DrawingGui::TaskOrthoViews::TaskOrthoViews(), SketcherGui::TaskSketcherElements::TaskSketcherElements(), SketcherGui::TaskSketcherMessages::TaskSketcherMessages(), TechDrawGui::TaskSurfaceFinishSymbols::TaskSurfaceFinishSymbols(), PartDesignGui::TaskTransformedParameters::TaskTransformedParameters(), Gui::TaskView::TaskView::TaskView(), MeshPartGui::Tessellation::Tessellation(), Gui::Dialog::TextureMapping::TextureMapping(), StartGui::ThemeSelectorWidget::themeChanged(), Part::throwIfInvalidIfCheckModel(), PartDesignGui::ViewProviderBody::toggleActiveBody(), Gui::PreferencePackManager::toggleVisibility(), Data::ElementMap::traceElement(), SketcherGui::tryAutoRecompute(), Gui::Application::tryClose(), Gui::RecentFilesAction::Private::trySaveUserParameter(), TYPESYSTEM_SOURCE_ABSTRACT(), Gui::Document::undo(), SketcherGui::ViewProviderSketch::unsetEdit(), Gui::TaskMeasure::update(), PartDesign::SubShapeBinder::update(), SketcherGui::TaskSketcherSolverAdvanced::updateDefaultMethodParameters(), SketcherGui::TaskSketcherSolverAdvanced::updateRedundantMethodParameters(), SketcherGui::useSystemDecimals(), PartGui::DlgScale::validate(), Attacher::AttachEngine::verifyReferencesAreSafe(), Gui::View3DInventorPy::viewDefaultOrientation(), Gui::ViewParams::ViewParams(), Gui::ViewProviderAnnotation::ViewProviderAnnotation(), PartDesignGui::ViewProviderDatum::ViewProviderDatum(), PartDesignGui::ViewProviderDatumCoordinateSystem::ViewProviderDatumCoordinateSystem(), PartGui::ViewProviderPartExt::ViewProviderPartExt(), PathGui::ViewProviderPath::ViewProviderPath(), FemGui::ViewProviderPointMarker::ViewProviderPointMarker(), PartDesignGui::ViewProviderShapeBinder::ViewProviderShapeBinder(), Gui::ViewProviderTextDocument::ViewProviderTextDocument(), InspectionGui::VisualInspection::VisualInspection(), Path::PathSegmentWalker::walk(), SandboxGui::Workbench::Workbench(), Import::WriterStep::write(), Gui::Multisample::writeMSAAToSettings(), App::AutoTransaction::~AutoTransaction(), MeshGui::DlgEvaluateMeshImp::~DlgEvaluateMeshImp(), and SketcherGui::TaskSketcherConstraints::~TaskSketcherConstraints().
getNameFromFile()
const char* App::getNameFromFile (PyObject * value)
Definition at line 249 of file PropertyFile.cpp.
Referenced by App::PropertyFileIncluded::setPyObject().
hash_value()
std::size_t App::hash_value (const App::ObjectIdentifier & path) inline
Definition at line 614 of file ObjectIdentifier.h.
References src.Mod.Test.testPathArray::path.
Referenced by App::ObjectIdentifier::hash().
isAnyEqual()
AppExport bool App::isAnyEqual (const App::any & v1, const App::any & v2)
Definition at line 567 of file Expression.cpp.
References __pyObjectFromAny(), anyToDouble(), anyToLong(), anyToQuantity(), SCL.SimpleDataTypes::c, src.Mod.PartDesign.Scripts.Gear::c1, essentiallyEqual(), is_type(), isAnyPyObject(), src.Mod.PartDesign.Scripts.Gear::l1, src.Mod.PartDesign.Scripts.Gear::l2, Base::PyException::ThrowException(), and draftgeoutils.general::v1().
Referenced by App::PropertyExpressionEngine::execute().
isIOFile()
bool App::isIOFile (PyObject * file)
Definition at line 270 of file PropertyFile.cpp.
References DrawingExample::file.
Referenced by App::PropertyFileIncluded::setPyObject().
maybeAbsolute()
bool App::maybeAbsolute (std::string_view address)
Definition at line 47 of file Range.cpp.
Referenced by App::CellAddress::parseAbsoluteAddress().
pyFromQuantity()
Py::Object App::pyFromQuantity (const Quantity & quantity)
Definition at line 505 of file Expression.cpp.
References essentiallyInteger(), Base::Quantity::getUnit(), Base::Quantity::getValue(), SplineSurface::i, Base::Unit::isEmpty(), RobotExample::l, src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::Quantity, and TestSpreadsheet::v.
Referenced by App::UnitExpression::_getPyValue(), and App::FunctionExpression::evalAggregate().
pyObjectFromAny()
Py::Object AppExport App::pyObjectFromAny (const App::any & value)
Definition at line 445 of file Expression.cpp.
References _pyObjectFromAny().
Referenced by Spreadsheet::PropertySheet::setPathValue(), App::PropertyEnumeration::setPathValue(), App::PropertyString::setPathValue(), and App::ObjectIdentifier::setValue().
pyObjectToAny()
App::any AppExport App::pyObjectToAny (Py::Object pyobj, bool check = true)
Helper function to convert Python object to/from App::any
WARNING! Must hold Python global interpreter lock before calling these functions
Definition at line 449 of file Expression.cpp.
References ArchCommands::check(), FC_THROWM, and pyObjectWrap().
Referenced by App::PropertyEnumeration::getPathValue(), App::ObjectIdentifier::getValue(), and App::Expression::getValueAsAny().
pyToQuantity() [1/2]
static Quantity App::pyToQuantity (const Py::Object & pyobj, const Expression * e, const char * msg = nullptr) inline static
Definition at line 493 of file Expression.cpp.
References __EXPR_THROW, SCL.SimpleDataTypes::e, Path.Op.Surface::msg, and pyToQuantity().
pyToQuantity() [2/2]
bool App::pyToQuantity (Quantity & q, const Py::Object & pyobj)
Definition at line 481 of file Expression.cpp.
References src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::Quantity.
Referenced by App::FunctionExpression::evalAggregate(), App::FunctionExpression::evaluate(), and App::FunctionExpression::extractLengthValueArgument().
quote()
std::string App::quote (const std::string & input, bool toPython = false)
Quote input string according to quoting rules for an expression: because " and ' are used to designate inch and foot units, strings are quoted as <<string>>.
Parameters
input
Returns
Definition at line 63 of file ObjectIdentifier.cpp.
Referenced by ExpressionCompleterModel::_data(), App::StringExpression::_toString(), SpreadsheetGui::DlgBindSheet::accept(), App::PropertyXLinkContainer::afterRestore(), SpreadsheetGui::ViewProviderSheet::exportAsFile(), and App::ObjectIdentifier::String::toString().
stringToAddress()
App::CellAddress App::stringToAddress (const char * strAddress, bool silent = false)
Convert a string address into integer row and column. row and col are 0-based.
This function will throw an exception if the specified address is invalid.
Parameters
strAddress Address to parse.
Definition at line 241 of file Range.cpp.
References SCL.SimpleDataTypes::c, decodeColumn(), decodeRow(), and SCL.SimpleDataTypes::e.
Referenced by App::VariableExpression::_moveCells(), App::RangeExpression::_moveCells(), App::VariableExpression::_offsetCells(), App::RangeExpression::_offsetCells(), SpreadsheetGui::DlgBindSheet::accept(), Spreadsheet::PropertySheet::getCellAddress(), App::RangeExpression::getRange(), and App::CellAddress::parseAbsoluteAddress().
validColumn()
bool App::validColumn (const std::string & colstr)
Determine if a string is a valid column specification.
Parameters
colstr input string.
Returns
true if valid, false if not.
Definition at line 226 of file Range.cpp.
Referenced by decodeColumn(), and Spreadsheet::PropertySheet::isValidCellAddressName().
validRow()
int App::validRow (const std::string & rowstr)
Determine whether a row specification is valid or not.
Parameters
rowstr Row specified as a string, with "1" being the first row.
Returns
0 or positive on success, -1 on error.
Definition at line 205 of file Range.cpp.
References SplineSurface::i, and App::CellAddress::MAX_ROWS.
Referenced by decodeRow(), and Spreadsheet::PropertySheet::isValidCellAddressName().
Variable Documentation
colsInArray
constexpr int App::colsInArray = 3 constexpr
Licenses data [identifier, fullName, url] See also https://spdx.org/licenses/
Definition at line 57 of file License.h.
countOfLicenses
constexpr int App::countOfLicenses {18} constexpr
Definition at line 62 of file License.h.
Referenced by App::Document::Document(), and Gui::Dialog::DlgSettingsDocumentImp::onLicenseTypeChanged().
ExtensionPythonT< Extension >
template class AppExport App::ExtensionPythonT< Extension >
Definition at line 227 of file Extension.cpp.
ExtensionPythonT< GroupExtensionPythonT< GeoFeatureGroupExtension > >
template class AppExport App::ExtensionPythonT< GroupExtensionPythonT< GeoFeatureGroupExtension > >
Definition at line 564 of file GeoFeatureGroupExtension.cpp.
ExtensionPythonT< GroupExtensionPythonT< GroupExtension > >
template class AppExport App::ExtensionPythonT< GroupExtensionPythonT< GroupExtension > >
Definition at line 43 of file GroupExtension.cpp.
ExtensionPythonT< GroupExtensionPythonT< OriginGroupExtension > >
template class AppExport App::ExtensionPythonT< GroupExtensionPythonT< OriginGroupExtension > >
Definition at line 321 of file OriginGroupExtension.cpp.
ExtensionPythonT< LinkBaseExtension >
template class AppExport App::ExtensionPythonT< LinkBaseExtension >
Definition at line 2593 of file Link.cpp.
ExtensionPythonT< SuppressibleExtensionPythonT< SuppressibleExtension > >
template class AppExport App::ExtensionPythonT< SuppressibleExtensionPythonT< SuppressibleExtension > >
Definition at line 61 of file SuppressibleExtension.cpp.
FeaturePythonT< DocumentObject >
template class AppExport App::FeaturePythonT< DocumentObject >
Definition at line 659 of file FeaturePython.cpp.
FeaturePythonT< GeoFeature >
template class AppExport App::FeaturePythonT< GeoFeature >
Definition at line 673 of file FeaturePython.cpp.
globalIsRelabeling
bool App::globalIsRelabeling static
Definition at line 140 of file App/Document.cpp.
Referenced by App::Document::onBeforeChangeProperty(), and App::Document::onChanged().
globalIsRestoring
bool App::globalIsRestoring static
Definition at line 139 of file App/Document.cpp.
Referenced by App::Document::afterRestore(), App::Document::clearDocument(), App::Document::importObjects(), App::Document::isAnyRestoring(), and App::Document::restore().
licenseItems
constexpr std::array<TLicenseArr, countOfLicenses> App::licenseItems constexpr
Initial value:
{{
    { "AllRightsReserved", "All rights reserved",                                          "https://en.wikipedia.org/wiki/All_rights_reserved"  },
    { "CC_BY_40",          "Creative Commons Attribution 4.0",                             "https://creativecommons.org/licenses/by/4.0/"       },
    { "CC_BY_SA_40",       "Creative Commons Attribution-ShareAlike 4.0",                  "https://creativecommons.org/licenses/by-sa/4.0/"    },
    { "CC_BY_ND_40",       "Creative Commons Attribution-NoDerivatives 4.0",               "https://creativecommons.org/licenses/by-nd/4.0/"    },
    { "CC_BY_NC_40",       "Creative Commons Attribution-NonCommercial 4.0",               "https://creativecommons.org/licenses/by-nc/4.0/"    },
    { "CC_BY_NC_SA_40",    "Creative Commons Attribution-NonCommercial-ShareAlike 4.0",    "https://creativecommons.org/licenses/by-nc-sa/4.0/" },
    { "CC_BY_NC_ND_40",    "Creative Commons Attribution-NonCommercial-NoDerivatives 4.0", "https://creativecommons.org/licenses/by-nc-nd/4.0/" },
    { "CC_BY_30",          "Creative Commons Attribution 3.0",                             "https://creativecommons.org/licenses/by/3.0/"       },
    { "CC_BY_SA_30",       "Creative Commons Attribution-ShareAlike 3.0",                  "https://creativecommons.org/licenses/by-sa/3.0/"    },
    { "CC_BY_ND_30",       "Creative Commons Attribution-NoDerivatives 3.0",               "https://creativecommons.org/licenses/by-nd/3.0/"    },
    { "CC_BY_NC_30",       "Creative Commons Attribution-NonCommercial 3.0",               "https://creativecommons.org/licenses/by-nc/3.0/"    },
    { "CC_BY_NC_SA_30",    "Creative Commons Attribution-NonCommercial-ShareAlike 3.0",    "https://creativecommons.org/licenses/by-nc-sa/3.0/" },
    { "CC_BY_NC_ND_30",    "Creative Commons Attribution-NonCommercial-NoDerivatives 3.0", "https://creativecommons.org/licenses/by-nc-nd/3.0/" },
    { "PublicDomain",      "Public Domain",                                                "https://en.wikipedia.org/wiki/Public_domain"        },
    { "FreeArt",           "FreeArt",                                                      "https://artlibre.org/licence/lal"                   },
    { "CERN_OHS_S",        "CERN Open Hardware Licence strongly-reciprocal",               "https://cern-ohl.web.cern.ch/"                      },
    { "CERN_OHS_W",        "CERN Open Hardware Licence weakly-reciprocal",                 "https://cern-ohl.web.cern.ch/"                      },
    { "CERN_OHS_P",        "CERN Open Hardware Licence permissive",                        "https://cern-ohl.web.cern.ch/"                      },
}}
Definition at line 64 of file License.h.
Referenced by Gui::Dialog::DlgSettingsDocumentImp::addLicenseTypes(), Gui::Dialog::DlgProjectInformationImp::DlgProjectInformationImp(), App::Document::Document(), and Gui::Dialog::DlgSettingsDocumentImp::onLicenseTypeChanged().
posnOfFullName
constexpr int App::posnOfFullName = 1 constexpr
Definition at line 60 of file License.h.
Referenced by Gui::Dialog::DlgSettingsDocumentImp::addLicenseTypes(), Gui::Dialog::DlgProjectInformationImp::DlgProjectInformationImp(), and App::Document::Document().
posnOfIdentifier
constexpr int App::posnOfIdentifier = 0 constexpr
Definition at line 59 of file License.h.
posnOfUrl
constexpr int App::posnOfUrl = 2 constexpr
Definition at line 61 of file License.h.
Referenced by App::Document::Document(), and Gui::Dialog::DlgSettingsDocumentImp::onLicenseTypeChanged().