FreeCAD: CommandTrajectory.cpp File Reference
CommandTrajectory.cpp File Reference
#include "PreCompiled.h"
#include <QInputDialog>
#include <QMessageBox>
#include <Gui/Application.h>
#include <Gui/Command.h>
#include <Gui/Document.h>
#include <Gui/MainWindow.h>
#include <Gui/Placement.h>
#include <Gui/Selection.h>
#include <Mod/Robot/App/Edge2TracObject.h>
#include <Mod/Robot/App/RobotObject.h>
#include <Mod/Robot/App/TrajectoryCompound.h>
#include <Mod/Robot/App/TrajectoryDressUpObject.h>
#include <Mod/Robot/App/TrajectoryObject.h>
#include "TaskDlgEdge2Trac.h"
Functions
void CreateRobotCommandsTrajectory ()
Function Documentation
CreateRobotCommandsTrajectory()
void CreateRobotCommandsTrajectory ()
Definition at line 522 of file CommandTrajectory.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().