FreeCAD: Command.cpp File Reference
Mod/CAM/Gui/Command.cpp File Reference
#include "PreCompiled.h"
#include <TopExp_Explorer.hxx>
#include <Base/Console.h>
#include <Gui/Application.h>
#include <Gui/Command.h>
#include <Gui/Document.h>
#include <Gui/Selection.h>
#include <Gui/SelectionObject.h>
#include <Mod/CAM/App/FeatureArea.h>
#include <Mod/CAM/App/FeaturePathShape.h>
Functions
void CreatePathCommands ()
Function Documentation
CreatePathCommands()
void CreatePathCommands ()
Definition at line 368 of file Mod/CAM/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().