FreeCAD: ifc2x3.ifcmateriallayerset Class Reference
ifc2x3.ifcmateriallayerset Class Reference
Public Member Functions
def __init__ (self, materiallayers, layersetname)
def materiallayers ()
def layersetname ()
def totalthickness ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
materiallayers
layersetname
Detailed Description
Entity ifcmateriallayerset definition.
:param materiallayers
:type materiallayers:LIST(1,None,'ifcmateriallayer', scope = schema_scope)
:param layersetname
:type layersetname:ifclabel
:param totalthickness
:type totalthickness:ifclengthmeasure
Definition at line 13010 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcmateriallayerset.__init__ (self, materiallayers, layersetname)
Definition at line 13022 of file ifc2x3.py.
Member Function Documentation
layersetname()
def ifc2x3.ifcmateriallayerset.layersetname ()
Definition at line 13041 of file ifc2x3.py.
References ifc2x3.ifcmateriallayerset._layersetname, SCL.TypeChecker.check_type(), and ifc2x3.ifcmateriallayerset.layersetname.
materiallayers()
def ifc2x3.ifcmateriallayerset.materiallayers ()
Definition at line 13027 of file ifc2x3.py.
References ifc2x3.ifcmateriallayerset._materiallayers, SCL.TypeChecker.check_type(), and ifc2x3.ifcmateriallayerset.materiallayers.
totalthickness()
def ifc2x3.ifcmateriallayerset.totalthickness ()
Definition at line 13055 of file ifc2x3.py.
References ifc2x3.ifcmlstotalthickness().
Member Data Documentation
layersetname
ifc2x3.ifcmateriallayerset.layersetname
Definition at line 13024 of file ifc2x3.py.
Referenced by ifc2x3.ifcmateriallayerset.layersetname().
materiallayers
ifc2x3.ifcmateriallayerset.materiallayers
Definition at line 13023 of file ifc2x3.py.
Referenced by ifc2x3.ifcmateriallayerset.materiallayers().
The documentation for this class was generated from the following file:
ifc2x3.py