FreeCAD: Gui::UIntSpinBox Class Reference
Gui::UIntSpinBox Class Reference
#include <SpinBox.h>
Public Slots
void setValue (uint value)
Signals
void unsignedChanged (uint value)
Public Member Functions
UIntSpinBox (QWidget *parent=nullptr)
~UIntSpinBox () override
void setRange (uint minVal, uint maxVal)
uint value () const
QValidator::State validate (QString &input, int &pos) const override
uint minimum () const
void setMinimum (uint value)
uint maximum () const
void setMaximum (uint value)
bool apply (const std::string &propName) override
void keyPressEvent (QKeyEvent *event) override
void resizeEvent (QResizeEvent *event) override
void paintEvent (QPaintEvent *event) override
Public Member Functions inherited from Gui::ExpressionSpinBox
ExpressionSpinBox (QAbstractSpinBox *)
~ExpressionSpinBox () override
void bind (const App::ObjectIdentifier &_path) override
void setExpression (std::shared_ptr< App::Expression > expr) override
Public Member Functions inherited from Gui::ExpressionWidget
ExpressionWidget ()
QPixmap getIcon (const char *name, const QSize &size) const
Public Member Functions inherited from Gui::ExpressionBinding
ExpressionBinding ()
virtual ~ExpressionBinding ()
virtual void bind (const App::Property &prop)
bool isBound () const
void unbind ()
virtual bool apply ()
bool hasExpression () const
bool autoApply () const
void setAutoApply (bool value)
Protected Member Functions
QString textFromValue (int v) const override
int valueFromText (const QString &text) const override
void setNumberExpression (App::NumberExpression *) override
Protected Member Functions inherited from Gui::ExpressionSpinBox
void showInvalidExpression (const QString &)
void showValidExpression (Number number)
void clearExpression ()
void updateExpression ()
void onChange () override
virtual void showIcon ()
virtual void validateInput ()
void resizeWidget ()
bool handleKeyEvent (const QString &)
virtual void openFormulaDialog ()
void drawControl (QStyleOptionSpinBox &)
Protected Member Functions inherited from Gui::ExpressionWidget
void makeLabel (QLineEdit *parent)
Protected Member Functions inherited from Gui::ExpressionBinding
const App::ObjectIdentifier & getPath () const
std::shared_ptr< App::Expression > getExpression () const
std::string getExpressionString (bool no_throw=true) const
std::string getEscapedExpressionString () const
bool assignToProperty (const std::string &propName, double)
void expressionChange (const App::ObjectIdentifier &id)
void objectDeleted (const App::DocumentObject &)
Additional Inherited Members
Protected Types inherited from Gui::ExpressionSpinBox
enum Number { Number::KeepCurrent = 0, Number::SetIfNumber = 1 }
Protected Attributes inherited from Gui::ExpressionSpinBox
QLineEdit * lineedit
QAbstractSpinBox * spinbox
Protected Attributes inherited from Gui::ExpressionWidget
ExpressionLabel * iconLabel {nullptr}
QPalette defaultPalette
int iconHeight {-1}
Protected Attributes inherited from Gui::ExpressionBinding
boost::signals2::scoped_connection expressionchanged
boost::signals2::scoped_connection objectdeleted
bool m_autoApply {false}
Detailed Description
The UIntSpinBox class does basically the same as Qt's QSpinBox unless that it works with unsigned int's instead. This allows one to use numbers in the range of [0, UINT_MAX]
Author
Werner Mayer
Definition at line 112 of file SpinBox.h.
Constructor & Destructor Documentation
UIntSpinBox()
UIntSpinBox::UIntSpinBox (QWidget * parent = nullptr) explicit
Definition at line 313 of file SpinBox.cpp.
References draftgeoutils.intersections::connect(), maximum(), minimum(), Gui::UIntSpinBoxPrivate::mValidator, setRange(), and setValue().
~UIntSpinBox()
UIntSpinBox::~UIntSpinBox () override
Definition at line 325 of file SpinBox.cpp.
References Gui::UIntSpinBoxPrivate::mValidator.
Member Function Documentation
apply()
bool UIntSpinBox::apply (const std::string & propName) override virtual
Reimplemented from Gui::ExpressionBinding.
Definition at line 411 of file SpinBox.cpp.
References Gui::ExpressionBinding::apply(), Gui::Command::Doc, doCommand, and value().
keyPressEvent()
void UIntSpinBox::keyPressEvent (QKeyEvent * event) override
Definition at line 432 of file SpinBox.cpp.
References Gui::ExpressionSpinBox::handleKeyEvent().
maximum()
uint UIntSpinBox::maximum () const
Definition at line 372 of file SpinBox.cpp.
References Gui::UIntSpinBoxPrivate::mapToUInt().
Referenced by setMinimum(), and UIntSpinBox().
minimum()
uint UIntSpinBox::minimum () const
Definition at line 359 of file SpinBox.cpp.
References Gui::UIntSpinBoxPrivate::mapToUInt().
Referenced by setMaximum(), and UIntSpinBox().
paintEvent()
void UIntSpinBox::paintEvent (QPaintEvent * event) override
Definition at line 438 of file SpinBox.cpp.
References Gui::ExpressionSpinBox::drawControl().
resizeEvent()
void UIntSpinBox::resizeEvent (QResizeEvent * event) override
Definition at line 426 of file SpinBox.cpp.
References Gui::ExpressionSpinBox::resizeWidget().
setMaximum()
void UIntSpinBox::setMaximum (uint value)
Definition at line 377 of file SpinBox.cpp.
References minimum(), and setRange().
setMinimum()
void UIntSpinBox::setMinimum (uint value)
Definition at line 364 of file SpinBox.cpp.
References maximum(), and setRange().
setNumberExpression()
void UIntSpinBox::setNumberExpression (App::NumberExpression * expr) override protected virtual
Implements Gui::ExpressionSpinBox.
Definition at line 421 of file SpinBox.cpp.
References App::UnitExpression::getValue(), and setValue().
setRange()
void UIntSpinBox::setRange (uint minVal, uint maxVal)
Definition at line 331 of file SpinBox.cpp.
References Gui::UIntSpinBoxPrivate::mapToInt().
Referenced by Gui::Dialog::ParameterUInt::changeValue(), setMaximum(), setMinimum(), and UIntSpinBox().
setValue
void UIntSpinBox::setValue (uint value) slot
Definition at line 349 of file SpinBox.cpp.
References Gui::UIntSpinBoxPrivate::mapToInt(), and value().
Referenced by Gui::Dialog::ParameterUInt::changeValue(), setNumberExpression(), and UIntSpinBox().
textFromValue()
QString UIntSpinBox::textFromValue (int v) const override protected
Definition at line 385 of file SpinBox.cpp.
References Gui::UIntSpinBoxPrivate::mapToUInt(), toolbit-attributes::s, TestSpreadsheet::v, and toolbit-attributes::val.
unsignedChanged
void Gui::UIntSpinBox::unsignedChanged (uint value) signal
validate()
QValidator::State UIntSpinBox::validate (QString & input, int & pos) const override
Definition at line 339 of file SpinBox.cpp.
References Gui::UIntSpinBoxPrivate::mValidator, RobotExample::pos, and Gui::UnsignedValidator::validate().
value()
uint UIntSpinBox::value () const
Definition at line 344 of file SpinBox.cpp.
References Gui::UIntSpinBoxPrivate::mapToUInt().
Referenced by apply(), src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), and setValue().
valueFromText()
int UIntSpinBox::valueFromText (const QString & text) const override protected
Definition at line 393 of file SpinBox.cpp.
References Gui::UIntSpinBoxPrivate::mapToInt(), and toolbit-attributes::s.
The documentation for this class was generated from the following files:
SpinBox.h
SpinBox.cpp