FreeCAD: Gui::PythonDebugger Class Reference
Gui::PythonDebugger Class Reference
#include <PythonDebugger.h>
Signals
void signalNextStep ()
Public Member Functions
PythonDebugger ()
~PythonDebugger () override
Breakpoint getBreakpoint (const QString &) const
bool toggleBreakpoint (int line, const QString &)
void runFile (const QString &fn)
bool isRunning () const
bool start ()
bool stop ()
void tryStop ()
void stepOver ()
void stepInto ()
void stepRun ()
void showDebugMarker (const QString &, int line)
void hideDebugMarker (const QString &)
Detailed Description
Definition at line 178 of file PythonDebugger.h.
Constructor & Destructor Documentation
PythonDebugger()
PythonDebugger::PythonDebugger ()
Definition at line 358 of file PythonDebugger.cpp.
~PythonDebugger()
PythonDebugger::~PythonDebugger () override
Definition at line 363 of file PythonDebugger.cpp.
Member Function Documentation
getBreakpoint()
Breakpoint PythonDebugger::getBreakpoint (const QString & fn) const
Definition at line 368 of file PythonDebugger.cpp.
References Gui::PythonDebuggerP::bps, and Gui::Breakpoint::filename().
Referenced by Gui::PythonEditor::drawMarker().
hideDebugMarker()
void PythonDebugger::hideDebugMarker (const QString & fn)
Definition at line 532 of file PythonDebugger.cpp.
References Gui::EditorView::fileName(), Gui::getMainWindow(), Gui::PythonEditorView::hideDebugMarker(), and Gui::MainWindow::windows().
isRunning()
bool PythonDebugger::isRunning () const
Definition at line 451 of file PythonDebugger.cpp.
References Gui::PythonDebuggerP::running.
Referenced by StdCmdMacroStartDebug::activated(), StdCmdMacroStopDebug::isActive(), StdCmdMacroStepOver::isActive(), and StdCmdMacroStepInto::isActive().
runFile()
void PythonDebugger::runFile (const QString & fn)
Definition at line 401 of file PythonDebugger.cpp.
References Base::Console(), Path.Base.SetupSheet::dict, src.Mod.PartDesign.fcgear.svggear::module, result, Gui::PythonDebuggerP::running, Base::FileInfo::toStdWString(), and Base::ConsoleSingleton::Warning().
Referenced by Gui::PythonEditor::startDebug().
showDebugMarker()
void PythonDebugger::showDebugMarker (const QString & fn, int line)
Definition at line 509 of file PythonDebugger.cpp.
References Gui::MainWindow::addWindow(), Gui::BitmapFactory(), Path.Post.Utils::editor(), Gui::EditorView::fileName(), Gui::getMainWindow(), Gui::EditorView::open(), Gui::MainWindow::setActiveWindow(), Gui::PythonEditorView::showDebugMarker(), and Gui::MainWindow::windows().
signalNextStep
void Gui::PythonDebugger::signalNextStep () signal
Referenced by stepInto(), stepOver(), stepRun(), and tryStop().
start()
bool PythonDebugger::start ()
Definition at line 456 of file PythonDebugger.cpp.
References Gui::PythonDebuggerP::err_n, Gui::PythonDebuggerP::err_o, Gui::PythonDebuggerP::exc_o, Gui::PythonDebuggerP::init, Gui::PythonDebuggerP::out_n, Gui::PythonDebuggerP::out_o, Gui::PythonDebuggerP::pydbg, and Gui::PythonDebuggerP::trystop.
Referenced by Gui::PythonEditor::startDebug().
stepInto()
void PythonDebugger::stepInto ()
Definition at line 499 of file PythonDebugger.cpp.
References signalNextStep().
Referenced by StdCmdMacroStepInto::activated().
stepOver()
void PythonDebugger::stepOver ()
Definition at line 494 of file PythonDebugger.cpp.
References signalNextStep().
Referenced by StdCmdMacroStepOver::activated().
stepRun()
void PythonDebugger::stepRun ()
Definition at line 504 of file PythonDebugger.cpp.
References signalNextStep().
Referenced by StdCmdMacroStartDebug::activated().
stop()
bool PythonDebugger::stop ()
Definition at line 475 of file PythonDebugger.cpp.
References Gui::PythonDebuggerP::err_o, Gui::PythonDebuggerP::exc_o, Gui::PythonDebuggerP::init, and Gui::PythonDebuggerP::out_o.
Referenced by bimcommands.BimPanel.NestTaskPanel::accept(), bimcommands.BimPanel.NestTaskPanel::reject(), and Gui::PythonEditor::startDebug().
toggleBreakpoint()
bool PythonDebugger::toggleBreakpoint (int line, const QString & fn)
Definition at line 379 of file PythonDebugger.cpp.
References Gui::Breakpoint::addLine(), Gui::PythonDebuggerP::bps, Gui::Breakpoint::checkLine(), Gui::Breakpoint::filename(), Gui::Breakpoint::removeLine(), and Gui::Breakpoint::setFilename().
Referenced by Gui::PythonEditor::toggleBreakpoint().
tryStop()
void PythonDebugger::tryStop ()
Definition at line 488 of file PythonDebugger.cpp.
References signalNextStep(), and Gui::PythonDebuggerP::trystop.
Referenced by StdCmdMacroStopDebug::activated().
The documentation for this class was generated from the following files:
PythonDebugger.h
PythonDebugger.cpp