FreeCAD: Part::Tools Class Reference
Part::Tools Class Reference
#include <Tools.h>
Public Member Functions
Handle (Geom_Surface) makeSurface(const TColStd_ListOfTransient &theBoundaries
Static Public Member Functions
static bool getTriangulation (const TopoDS_Face &face, std::vector< gp_Pnt > &points, std::vector< Poly_Triangle > &facets)
getTriangulation The indexes of the triangles are adjusted to the points vector.
static bool getPolygonOnTriangulation (const TopoDS_Edge &edge, const TopoDS_Face &face, std::vector< gp_Pnt > &points)
getPolygonOnTriangulation Get the polygon of edge.
static bool getPolygon3D (const TopoDS_Edge &edge, std::vector< gp_Pnt > &points)
getPolygon3D
static void getPointNormals (const std::vector< gp_Pnt > &points, const std::vector< Poly_Triangle > &facets, std::vector< gp_Vec > &vertexnormals)
getPointNormals Calculate the point normals of the given triangulation.
static void getPointNormals (const std::vector< gp_Pnt > &points, const TopoDS_Face &face, std::vector< gp_Vec > &vertexnormals)
getPointNormals Computes the more accurate surface normals for the points. If the calculation for a point fails then the precomputed point normal of the triangulation is used.
static void getPointNormals (const TopoDS_Face &face, Handle(Poly_Triangulation) aPoly, TColgp_Array1OfDir &normals)
getPointNormals Computes the exact surface normals for the points by using the UV coordinates of the mesh vertexes.
static void getPointNormals (const TopoDS_Face &face, Handle(Poly_Triangulation) aPoly, std::vector< gp_Vec > &normals)
getPointNormals Computes the exact surface normals for the points by using the UV coordinates of the mesh vertexes.
static void applyTransformationOnNormals (const TopLoc_Location &loc, std::vector< gp_Vec > &normals)
applyTransformationOnNormals Apply the transformation to the vectors
static Handle (Poly_Triangulation) triangulationOfFace(const TopoDS_Face &face)
triangulationOfInfinite Returns the triangulation of the face of the tessellated shape. In case the face has infinite lengths the triangulation of a limited parameter range is computed.
static Handle (Poly_Polygon3D) polygonOfEdge(const TopoDS_Edge &edge
polygonOfEdge Returns the polygon of the edge of the tessellated shape. In case the edge has infinite length the polygon of a limited parameter range is computed.
static void getNormal (const Handle(Geom_Surface)&surf, double u, double v, const Standard_Real tol, gp_Dir &dir, Standard_Boolean &done)
getNormal Returns the normal at the given parameters on the surface and the state of the calculation
static void getNormal (const TopoDS_Face &face, double u, double v, const Standard_Real tol, gp_Dir &dir, Standard_Boolean &done)
getNormal Returns the normal at the given parameters on the face and the state of the calculation. The orientation is taken into account
static TopLoc_Location fromPlacement (const Base::Placement &)
fromPlacement Converts a placement into a TopLoc_Location
static bool isConcave (const TopoDS_Face &face, const gp_Pnt &pointOfVue, const gp_Dir &direction)
isConcave
Public Attributes
const Standard_Real theTol
const Standard_Real const Standard_Integer theNbPnts
const Standard_Real const Standard_Integer const Standard_Integer theNbIter
const Standard_Real const Standard_Integer const Standard_Integer const Standard_Integer theMaxDeg
static TopLoc_Location & loc
Detailed Description
Definition at line 110 of file Mod/Part/App/Tools.h.
Member Function Documentation
applyTransformationOnNormals()
void Part::Tools::applyTransformationOnNormals (const TopLoc_Location & loc, std::vector< gp_Vec > & normals) static
applyTransformationOnNormals Apply the transformation to the vectors
Parameters
loc
normals
Definition at line 596 of file Mod/Part/App/Tools.cpp.
Referenced by PartDesignGui::ViewProviderAddSub::updateAddSubShapeIndicator().
fromPlacement()
TopLoc_Location Part::Tools::fromPlacement (const Base::Placement & plm) static
fromPlacement Converts a placement into a TopLoc_Location
Returns
TopLoc_Location
Definition at line 737 of file Mod/Part/App/Tools.cpp.
References Base::Placement::getPosition(), Base::Placement::getRotation(), Base::Rotation::getValue(), and InitGui::t.
Referenced by Fem::Tools::setSubShapeGlobalLocation().
getNormal() [1/2]
void Part::Tools::getNormal (const Handle(Geom_Surface)& surf, double u, double v, const Standard_Real tol, gp_Dir & dir, Standard_Boolean & done) static
getNormal Returns the normal at the given parameters on the surface and the state of the calculation
Parameters
surf
u
v
tol
dir
done
Definition at line 713 of file Mod/Part/App/Tools.cpp.
References buildPsets::u, TestSpreadsheet::v, and draftgeoutils.general::v1().
Referenced by Attacher::AttachEngine3D::_calculateAttachedPlacement(), and Part::GeomSurface::normal().
getNormal() [2/2]
void Part::Tools::getNormal (const TopoDS_Face & face, double u, double v, const Standard_Real tol, gp_Dir & dir, Standard_Boolean & done) static
getNormal Returns the normal at the given parameters on the face and the state of the calculation. The orientation is taken into account
Parameters
face
u
v
tol
dir
done
Definition at line 723 of file Mod/Part/App/Tools.cpp.
References buildPsets::u, and TestSpreadsheet::v.
getPointNormals() [1/4]
void Part::Tools::getPointNormals (const std::vector< gp_Pnt > & points, const std::vector< Poly_Triangle > & facets, std::vector< gp_Vec > & vertexnormals) static
getPointNormals Calculate the point normals of the given triangulation.
Parameters
points
facets
normals
Definition at line 377 of file Mod/Part/App/Tools.cpp.
References draftgeoutils.general::v1().
Referenced by PartDesignGui::ViewProviderAddSub::updateAddSubShapeIndicator(), and PartGui::ViewProviderPartExt::updateVisual().
getPointNormals() [2/4]
void Part::Tools::getPointNormals (const std::vector< gp_Pnt > & points, const TopoDS_Face & face, std::vector< gp_Vec > & vertexnormals) static
getPointNormals Computes the more accurate surface normals for the points. If the calculation for a point fails then the precomputed point normal of the triangulation is used.
Parameters
points
face
vertexnormals
Definition at line 402 of file Mod/Part/App/Tools.cpp.
References Handle(), SplineSurface::i, buildPsets::u, and TestSpreadsheet::v.
getPointNormals() [3/4]
void Part::Tools::getPointNormals (const TopoDS_Face & face, Handle(Poly_Triangulation) aPoly, std::vector< gp_Vec > & normals) static
getPointNormals Computes the exact surface normals for the points by using the UV coordinates of the mesh vertexes.
Parameters
face
aPoly
vertexnormals
Definition at line 585 of file Mod/Part/App/Tools.cpp.
References SplineSurface::i.
getPointNormals() [4/4]
void Part::Tools::getPointNormals (const TopoDS_Face & face, Handle(Poly_Triangulation) aPoly, TColgp_Array1OfDir & normals) static
getPointNormals Computes the exact surface normals for the points by using the UV coordinates of the mesh vertexes.
Parameters
face
aPoly
vertexnormals
Definition at line 434 of file Mod/Part/App/Tools.cpp.
References Handle(), and draftgeoutils.general::v1().
getPolygon3D()
bool Part::Tools::getPolygon3D (const TopoDS_Edge & edge, std::vector< gp_Pnt > & points) static
getPolygon3D
Parameters
edge
points
Returns
true if a polygon exists or false otherwise
Definition at line 343 of file Mod/Part/App/Tools.cpp.
References Handle(), SplineSurface::i, and buildPsets::p.
Referenced by Part::TopoShape::exportLineSet().
getPolygonOnTriangulation()
bool Part::Tools::getPolygonOnTriangulation (const TopoDS_Edge & edge, const TopoDS_Face & face, std::vector< gp_Pnt > & points) static
getPolygonOnTriangulation Get the polygon of edge.
Note
edge must belong to face.
Parameters
edge
face
points
Returns
true if a triangulation exists or false otherwise
Definition at line 298 of file Mod/Part/App/Tools.cpp.
References Handle(), SplineSurface::i, and buildPsets::p.
Referenced by Part::TopoShape::exportLineSet().
getTriangulation()
bool Part::Tools::getTriangulation (const TopoDS_Face & face, std::vector< gp_Pnt > & points, std::vector< Poly_Triangle > & facets) static
getTriangulation The indexes of the triangles are adjusted to the points vector.
Parameters
face
points
facets
Returns
true if a triangulation exists or false otherwise
Definition at line 232 of file Mod/Part/App/Tools.cpp.
References Handle(), SplineSurface::i, src.Mod.Test.testPathArray::orient, and buildPsets::p.
Referenced by Part::TopoShape::exportFaceSet(), Part::TopoShape::getDomains(), and PartDesignGui::ViewProviderAddSub::updateAddSubShapeIndicator().
Handle() [1/3]
Part::Tools::Handle (Geom_Surface) const &
Referenced by Handle().
Handle() [2/3]
static Part::Tools::Handle (Poly_Polygon3D) const & static
polygonOfEdge Returns the polygon of the edge of the tessellated shape. In case the edge has infinite length the polygon of a limited parameter range is computed.
Parameters
edge
loc
Handle() [3/3]
static Part::Tools::Handle (Poly_Triangulation) const & static
triangulationOfInfinite Returns the triangulation of the face of the tessellated shape. In case the face has infinite lengths the triangulation of a limited parameter range is computed.
Parameters
edge
loc
isConcave()
bool Part::Tools::isConcave (const TopoDS_Face & face, const gp_Pnt & pointOfVue, const gp_Dir & direction) static
isConcave
Parameters
face
pointOfVue
direction
Returns
true if the face is concave when shown from pointOfVue and looking into direction and false otherwise, plane case included.
Definition at line 749 of file Mod/Part/App/Tools.cpp.
References Handle(), M_PI_2, and result.
Referenced by FC_LOG_LEVEL_INIT().
Member Data Documentation
loc
TopLoc_Location& Part::Tools::loc
Definition at line 199 of file Mod/Part/App/Tools.h.
theMaxDeg
const Standard_Real const Standard_Integer const Standard_Integer const Standard_Integer Part::Tools::theMaxDeg
Definition at line 117 of file Mod/Part/App/Tools.h.
Referenced by Handle().
theNbIter
const Standard_Real const Standard_Integer const Standard_Integer Part::Tools::theNbIter
Definition at line 116 of file Mod/Part/App/Tools.h.
Referenced by Handle().
theNbPnts
const Standard_Real const Standard_Integer Part::Tools::theNbPnts
Definition at line 115 of file Mod/Part/App/Tools.h.
Referenced by Handle().
theTol
const Standard_Real Part::Tools::theTol
Definition at line 114 of file Mod/Part/App/Tools.h.
Referenced by Handle().
The documentation for this class was generated from the following files:
Mod/Part/App/Tools.h
Mod/Part/App/Tools.cpp