FreeCAD: Gui::OverlayParams Class Reference
Gui::OverlayParams Class Reference
#include <OverlayParams.h>
Static Public Member Functions
static ParameterGrp::handle getHandle ()
static const bool & getDockOverlayAutoView ()
Accessor for parameter DockOverlayAutoView.
static const bool & defaultDockOverlayAutoView ()
static void removeDockOverlayAutoView ()
static void setDockOverlayAutoView (const bool &v)
static const char * docDockOverlayAutoView ()
static void onDockOverlayAutoViewChanged ()
static const long & getDockOverlayDelay ()
static const long & defaultDockOverlayDelay ()
static void removeDockOverlayDelay ()
static void setDockOverlayDelay (const long &v)
static const char * docDockOverlayDelay ()
static const long & getDockOverlayRevealDelay ()
Accessor for parameter DockOverlayRevealDelay.
static const long & defaultDockOverlayRevealDelay ()
static void removeDockOverlayRevealDelay ()
static void setDockOverlayRevealDelay (const long &v)
static const char * docDockOverlayRevealDelay ()
static const long & getDockOverlaySplitterHandleTimeout ()
static const long & defaultDockOverlaySplitterHandleTimeout ()
static void removeDockOverlaySplitterHandleTimeout ()
static void setDockOverlaySplitterHandleTimeout (const long &v)
static const char * docDockOverlaySplitterHandleTimeout ()
static const bool & getDockOverlayActivateOnHover ()
static const bool & defaultDockOverlayActivateOnHover ()
static void removeDockOverlayActivateOnHover ()
static void setDockOverlayActivateOnHover (const bool &v)
static const char * docDockOverlayActivateOnHover ()
static const bool & getDockOverlayAutoMouseThrough ()
static const bool & defaultDockOverlayAutoMouseThrough ()
static void removeDockOverlayAutoMouseThrough ()
static void setDockOverlayAutoMouseThrough (const bool &v)
static const char * docDockOverlayAutoMouseThrough ()
static const bool & getDockOverlayWheelPassThrough ()
static const bool & defaultDockOverlayWheelPassThrough ()
static void removeDockOverlayWheelPassThrough ()
static void setDockOverlayWheelPassThrough (const bool &v)
static const char * docDockOverlayWheelPassThrough ()
static const long & getDockOverlayWheelDelay ()
static const long & defaultDockOverlayWheelDelay ()
static void removeDockOverlayWheelDelay ()
static void setDockOverlayWheelDelay (const long &v)
static const char * docDockOverlayWheelDelay ()
static const long & getDockOverlayAlphaRadius ()
static const long & defaultDockOverlayAlphaRadius ()
static void removeDockOverlayAlphaRadius ()
static void setDockOverlayAlphaRadius (const long &v)
static const char * docDockOverlayAlphaRadius ()
static const bool & getDockOverlayCheckNaviCube ()
static const bool & defaultDockOverlayCheckNaviCube ()
static void removeDockOverlayCheckNaviCube ()
static void setDockOverlayCheckNaviCube (const bool &v)
static const char * docDockOverlayCheckNaviCube ()
static void onDockOverlayCheckNaviCubeChanged ()
static const long & getDockOverlayHintTriggerSize ()
static const long & defaultDockOverlayHintTriggerSize ()
static void removeDockOverlayHintTriggerSize ()
static void setDockOverlayHintTriggerSize (const long &v)
static const char * docDockOverlayHintTriggerSize ()
static const long & getDockOverlayHintSize ()
static const long & defaultDockOverlayHintSize ()
static void removeDockOverlayHintSize ()
static void setDockOverlayHintSize (const long &v)
static const char * docDockOverlayHintSize ()
static const long & getDockOverlayHintLeftLength ()
static const long & defaultDockOverlayHintLeftLength ()
static void removeDockOverlayHintLeftLength ()
static void setDockOverlayHintLeftLength (const long &v)
static const char * docDockOverlayHintLeftLength ()
static const long & getDockOverlayHintRightLength ()
static const long & defaultDockOverlayHintRightLength ()
static void removeDockOverlayHintRightLength ()
static void setDockOverlayHintRightLength (const long &v)
static const char * docDockOverlayHintRightLength ()
static const long & getDockOverlayHintTopLength ()
static const long & defaultDockOverlayHintTopLength ()
static void removeDockOverlayHintTopLength ()
static void setDockOverlayHintTopLength (const long &v)
static const char * docDockOverlayHintTopLength ()
static const long & getDockOverlayHintBottomLength ()
static const long & defaultDockOverlayHintBottomLength ()
static void removeDockOverlayHintBottomLength ()
static void setDockOverlayHintBottomLength (const long &v)
static const char * docDockOverlayHintBottomLength ()
static const long & getDockOverlayHintLeftOffset ()
static const long & defaultDockOverlayHintLeftOffset ()
static void removeDockOverlayHintLeftOffset ()
static void setDockOverlayHintLeftOffset (const long &v)
static const char * docDockOverlayHintLeftOffset ()
static const long & getDockOverlayHintRightOffset ()
static const long & defaultDockOverlayHintRightOffset ()
static void removeDockOverlayHintRightOffset ()
static void setDockOverlayHintRightOffset (const long &v)
static const char * docDockOverlayHintRightOffset ()
static const long & getDockOverlayHintTopOffset ()
static const long & defaultDockOverlayHintTopOffset ()
static void removeDockOverlayHintTopOffset ()
static void setDockOverlayHintTopOffset (const long &v)
static const char * docDockOverlayHintTopOffset ()
static const long & getDockOverlayHintBottomOffset ()
static const long & defaultDockOverlayHintBottomOffset ()
static void removeDockOverlayHintBottomOffset ()
static void setDockOverlayHintBottomOffset (const long &v)
static const char * docDockOverlayHintBottomOffset ()
static const bool & getDockOverlayHintTabBar ()
static const bool & defaultDockOverlayHintTabBar ()
static void removeDockOverlayHintTabBar ()
static void setDockOverlayHintTabBar (const bool &v)
static const char * docDockOverlayHintTabBar ()
static const bool & getDockOverlayHideTabBar ()
static const bool & defaultDockOverlayHideTabBar ()
static void removeDockOverlayHideTabBar ()
static void setDockOverlayHideTabBar (const bool &v)
static const char * docDockOverlayHideTabBar ()
static void onDockOverlayHideTabBarChanged ()
static const long & getDockOverlayHintDelay ()
static const long & defaultDockOverlayHintDelay ()
static void removeDockOverlayHintDelay ()
static void setDockOverlayHintDelay (const long &v)
static const char * docDockOverlayHintDelay ()
static const long & getDockOverlayAnimationDuration ()
static const long & defaultDockOverlayAnimationDuration ()
static void removeDockOverlayAnimationDuration ()
static void setDockOverlayAnimationDuration (const long &v)
static const char * docDockOverlayAnimationDuration ()
static const long & getDockOverlayAnimationCurve ()
static const long & defaultDockOverlayAnimationCurve ()
static void removeDockOverlayAnimationCurve ()
static void setDockOverlayAnimationCurve (const long &v)
static const char * docDockOverlayAnimationCurve ()
static const bool & getDockOverlayHidePropertyViewScrollBar ()
static const bool & defaultDockOverlayHidePropertyViewScrollBar ()
static void removeDockOverlayHidePropertyViewScrollBar ()
static void setDockOverlayHidePropertyViewScrollBar (const bool &v)
static const char * docDockOverlayHidePropertyViewScrollBar ()
static const long & getDockOverlayMinimumSize ()
static const long & defaultDockOverlayMinimumSize ()
static void removeDockOverlayMinimumSize ()
static void setDockOverlayMinimumSize (const long &v)
static const char * docDockOverlayMinimumSize ()
static void onDockOverlayMinimumSizeChanged ()
Static Public Attributes
static const std::vector< QString > AnimationCurveTypes
Detailed Description
Convenient class to obtain overlay widgets related parameters
The parameters are under group "User parameter:BaseApp/Preferences/View"
This class is auto generated by Gui/OverlayParams.py. Modify that file instead of this one, if you want to add any parameter. You need to install Cog Python package for code generation:
pip install cogapp
Once modified, you can regenerate the header and the source file,
python3 -m cogapp -r Gui/OverlayParams.h Gui/OverlayParams.cpp
You can add a new parameter by adding lines in Gui/OverlayParams.py. Available parameter types are 'Int, UInt, String, Bool, Float'. For example, to add a new Int type parameter,
ParamInt(parameter_name, default_value, documentation, on_change=False)
If there is special handling on parameter change, pass in on_change=True. And you need to provide a function implementation in Gui/OverlayParams.cpp with the following signature.
void OverlayParams:on<parameter_name>Changed()
Definition at line 90 of file OverlayParams.h.
Member Function Documentation
defaultDockOverlayActivateOnHover()
static const bool& Gui::OverlayParams::defaultDockOverlayActivateOnHover () static
defaultDockOverlayAlphaRadius()
static const long& Gui::OverlayParams::defaultDockOverlayAlphaRadius () static
defaultDockOverlayAnimationCurve()
static const long& Gui::OverlayParams::defaultDockOverlayAnimationCurve () static
defaultDockOverlayAnimationDuration()
static const long& Gui::OverlayParams::defaultDockOverlayAnimationDuration () static
defaultDockOverlayAutoMouseThrough()
static const bool& Gui::OverlayParams::defaultDockOverlayAutoMouseThrough () static
defaultDockOverlayAutoView()
static const bool& Gui::OverlayParams::defaultDockOverlayAutoView () static
defaultDockOverlayCheckNaviCube()
static const bool& Gui::OverlayParams::defaultDockOverlayCheckNaviCube () static
defaultDockOverlayDelay()
static const long& Gui::OverlayParams::defaultDockOverlayDelay () static
defaultDockOverlayHidePropertyViewScrollBar()
static const bool& Gui::OverlayParams::defaultDockOverlayHidePropertyViewScrollBar () static
defaultDockOverlayHideTabBar()
static const bool& Gui::OverlayParams::defaultDockOverlayHideTabBar () static
defaultDockOverlayHintBottomLength()
static const long& Gui::OverlayParams::defaultDockOverlayHintBottomLength () static
defaultDockOverlayHintBottomOffset()
static const long& Gui::OverlayParams::defaultDockOverlayHintBottomOffset () static
defaultDockOverlayHintDelay()
static const long& Gui::OverlayParams::defaultDockOverlayHintDelay () static
defaultDockOverlayHintLeftLength()
static const long& Gui::OverlayParams::defaultDockOverlayHintLeftLength () static
defaultDockOverlayHintLeftOffset()
static const long& Gui::OverlayParams::defaultDockOverlayHintLeftOffset () static
defaultDockOverlayHintRightLength()
static const long& Gui::OverlayParams::defaultDockOverlayHintRightLength () static
defaultDockOverlayHintRightOffset()
static const long& Gui::OverlayParams::defaultDockOverlayHintRightOffset () static
defaultDockOverlayHintSize()
static const long& Gui::OverlayParams::defaultDockOverlayHintSize () static
defaultDockOverlayHintTabBar()
static const bool& Gui::OverlayParams::defaultDockOverlayHintTabBar () static
defaultDockOverlayHintTopLength()
static const long& Gui::OverlayParams::defaultDockOverlayHintTopLength () static
defaultDockOverlayHintTopOffset()
static const long& Gui::OverlayParams::defaultDockOverlayHintTopOffset () static
defaultDockOverlayHintTriggerSize()
static const long& Gui::OverlayParams::defaultDockOverlayHintTriggerSize () static
defaultDockOverlayMinimumSize()
static const long& Gui::OverlayParams::defaultDockOverlayMinimumSize () static
defaultDockOverlayRevealDelay()
static const long& Gui::OverlayParams::defaultDockOverlayRevealDelay () static
defaultDockOverlaySplitterHandleTimeout()
static const long& Gui::OverlayParams::defaultDockOverlaySplitterHandleTimeout () static
defaultDockOverlayWheelDelay()
static const long& Gui::OverlayParams::defaultDockOverlayWheelDelay () static
defaultDockOverlayWheelPassThrough()
static const bool& Gui::OverlayParams::defaultDockOverlayWheelPassThrough () static
docDockOverlayActivateOnHover()
static const char* Gui::OverlayParams::docDockOverlayActivateOnHover () static
docDockOverlayAlphaRadius()
static const char* Gui::OverlayParams::docDockOverlayAlphaRadius () static
docDockOverlayAnimationCurve()
static const char* Gui::OverlayParams::docDockOverlayAnimationCurve () static
docDockOverlayAnimationDuration()
static const char* Gui::OverlayParams::docDockOverlayAnimationDuration () static
docDockOverlayAutoMouseThrough()
static const char* Gui::OverlayParams::docDockOverlayAutoMouseThrough () static
docDockOverlayAutoView()
static const char* Gui::OverlayParams::docDockOverlayAutoView () static
docDockOverlayCheckNaviCube()
static const char* Gui::OverlayParams::docDockOverlayCheckNaviCube () static
docDockOverlayDelay()
static const char* Gui::OverlayParams::docDockOverlayDelay () static
docDockOverlayHidePropertyViewScrollBar()
static const char* Gui::OverlayParams::docDockOverlayHidePropertyViewScrollBar () static
docDockOverlayHideTabBar()
static const char* Gui::OverlayParams::docDockOverlayHideTabBar () static
docDockOverlayHintBottomLength()
static const char* Gui::OverlayParams::docDockOverlayHintBottomLength () static
docDockOverlayHintBottomOffset()
static const char* Gui::OverlayParams::docDockOverlayHintBottomOffset () static
docDockOverlayHintDelay()
static const char* Gui::OverlayParams::docDockOverlayHintDelay () static
docDockOverlayHintLeftLength()
static const char* Gui::OverlayParams::docDockOverlayHintLeftLength () static
docDockOverlayHintLeftOffset()
static const char* Gui::OverlayParams::docDockOverlayHintLeftOffset () static
docDockOverlayHintRightLength()
static const char* Gui::OverlayParams::docDockOverlayHintRightLength () static
docDockOverlayHintRightOffset()
static const char* Gui::OverlayParams::docDockOverlayHintRightOffset () static
docDockOverlayHintSize()
static const char* Gui::OverlayParams::docDockOverlayHintSize () static
docDockOverlayHintTabBar()
static const char* Gui::OverlayParams::docDockOverlayHintTabBar () static
docDockOverlayHintTopLength()
static const char* Gui::OverlayParams::docDockOverlayHintTopLength () static
docDockOverlayHintTopOffset()
static const char* Gui::OverlayParams::docDockOverlayHintTopOffset () static
docDockOverlayHintTriggerSize()
static const char* Gui::OverlayParams::docDockOverlayHintTriggerSize () static
docDockOverlayMinimumSize()
static const char* Gui::OverlayParams::docDockOverlayMinimumSize () static
docDockOverlayRevealDelay()
static const char* Gui::OverlayParams::docDockOverlayRevealDelay () static
docDockOverlaySplitterHandleTimeout()
static const char* Gui::OverlayParams::docDockOverlaySplitterHandleTimeout () static
docDockOverlayWheelDelay()
static const char* Gui::OverlayParams::docDockOverlayWheelDelay () static
docDockOverlayWheelPassThrough()
static const char* Gui::OverlayParams::docDockOverlayWheelPassThrough () static
getDockOverlayActivateOnHover()
static const bool& Gui::OverlayParams::getDockOverlayActivateOnHover () static
Accessor for parameter DockOverlayActivateOnHover
Show auto hidden dock overlay on mouse over. If disabled, then show on mouse click.
Referenced by Gui::OverlayProxyWidget::hitTest().
getDockOverlayAlphaRadius()
static const long& Gui::OverlayParams::getDockOverlayAlphaRadius () static
Accessor for parameter DockOverlayAlphaRadius
If auto mouse click through is enabled, then this radius defines a region of alpha test under the mouse cursor. Auto click through is only activated if all pixels within the region are non-opaque.
Referenced by Gui::OverlayTabWidget::testAlpha().
getDockOverlayAnimationCurve()
static const long& Gui::OverlayParams::getDockOverlayAnimationCurve () static
Accessor for parameter DockOverlayAnimationCurve
Auto hide animation curve type
Referenced by Gui::OverlayTabWidget::startHide(), and Gui::OverlayTabWidget::startShow().
getDockOverlayAnimationDuration()
static const long& Gui::OverlayParams::getDockOverlayAnimationDuration () static
Accessor for parameter DockOverlayAnimationDuration
Auto hide animation duration, 0 to disable
Referenced by Gui::OverlayTabWidget::startHide(), and Gui::OverlayTabWidget::startShow().
getDockOverlayAutoMouseThrough()
static const bool& Gui::OverlayParams::getDockOverlayAutoMouseThrough () static
Accessor for parameter DockOverlayAutoMouseThrough
Auto mouse click through transparent part of dock overlay.
Referenced by Gui::OverlayManager::eventFilter(), and Gui::OverlayTabWidget::setOverlayMode().
getDockOverlayAutoView()
static const bool& Gui::OverlayParams::getDockOverlayAutoView () static
Accessor for parameter DockOverlayAutoView.
Referenced by Gui::OverlayTabWidget::checkAutoHide(), and Gui::OverlayTabWidget::isTransparent().
getDockOverlayCheckNaviCube()
static const bool& Gui::OverlayParams::getDockOverlayCheckNaviCube () static
Accessor for parameter DockOverlayCheckNaviCube
Leave space for Navigation Cube in dock overlay
Referenced by Gui::OverlayManager::Private::onTimer().
getDockOverlayDelay()
static const long& Gui::OverlayParams::getDockOverlayDelay () static
Accessor for parameter DockOverlayDelay
Overlay dock (re),layout delay.
Referenced by Gui::OverlayManager::Private::refresh().
getDockOverlayHidePropertyViewScrollBar()
static const bool& Gui::OverlayParams::getDockOverlayHidePropertyViewScrollBar () static
Accessor for parameter DockOverlayHidePropertyViewScrollBar
Hide property view scroll bar in dock overlay
Referenced by Gui::OverlayTabWidget::_setOverlayMode().
getDockOverlayHideTabBar()
static const bool& Gui::OverlayParams::getDockOverlayHideTabBar () static
Accessor for parameter DockOverlayHideTabBar
Hide tab bar in dock overlay
Referenced by Gui::OverlayTabWidget::setOverlayMode().
getDockOverlayHintBottomLength()
static const long& Gui::OverlayParams::getDockOverlayHintBottomLength () static
Accessor for parameter DockOverlayHintBottomLength
Auto hide hint visual display length for bottom panel. Set to zero to fill the space.
Referenced by Gui::OverlayProxyWidget::getRect().
getDockOverlayHintBottomOffset()
static const long& Gui::OverlayParams::getDockOverlayHintBottomOffset () static
Accessor for parameter DockOverlayHintBottomOffset
Auto hide hint visual display offset for bottom panel
Referenced by Gui::OverlayProxyWidget::getRect().
getDockOverlayHintDelay()
static const long& Gui::OverlayParams::getDockOverlayHintDelay () static
Accessor for parameter DockOverlayHintDelay
Delay before show hint visual
Referenced by Gui::OverlayProxyWidget::enterEvent(), and Gui::OverlayProxyWidget::hitTest().
getDockOverlayHintLeftLength()
static const long& Gui::OverlayParams::getDockOverlayHintLeftLength () static
Accessor for parameter DockOverlayHintLeftLength
Auto hide hint visual display length for left panel. Set to zero to fill the space.
Referenced by Gui::OverlayProxyWidget::getRect().
getDockOverlayHintLeftOffset()
static const long& Gui::OverlayParams::getDockOverlayHintLeftOffset () static
Accessor for parameter DockOverlayHintLeftOffset
Auto hide hint visual display offset for left panel
Referenced by Gui::OverlayProxyWidget::getRect().
getDockOverlayHintRightLength()
static const long& Gui::OverlayParams::getDockOverlayHintRightLength () static
Accessor for parameter DockOverlayHintRightLength
Auto hide hint visual display length for right panel. Set to zero to fill the space.
Referenced by Gui::OverlayProxyWidget::getRect().
getDockOverlayHintRightOffset()
static const long& Gui::OverlayParams::getDockOverlayHintRightOffset () static
Accessor for parameter DockOverlayHintRightOffset
Auto hide hint visual display offset for right panel
Referenced by Gui::OverlayProxyWidget::getRect().
getDockOverlayHintSize()
static const long& Gui::OverlayParams::getDockOverlayHintSize () static
Accessor for parameter DockOverlayHintSize
Auto hide hint visual display width
Referenced by Gui::OverlayTabWidget::getAutoHideRect().
getDockOverlayHintTabBar()
static const bool& Gui::OverlayParams::getDockOverlayHintTabBar () static
Accessor for parameter DockOverlayHintTabBar
Show tab bar on mouse over when auto hide
Referenced by Gui::OverlayTabWidget::setOverlayMode(), Gui::OverlayTabWidget::setRect(), and Gui::OverlayTabWidget::setState().
getDockOverlayHintTopLength()
static const long& Gui::OverlayParams::getDockOverlayHintTopLength () static
Accessor for parameter DockOverlayHintTopLength
Auto hide hint visual display length for top panel. Set to zero to fill the space.
Referenced by Gui::OverlayProxyWidget::getRect().
getDockOverlayHintTopOffset()
static const long& Gui::OverlayParams::getDockOverlayHintTopOffset () static
Accessor for parameter DockOverlayHintTopOffset
Auto hide hint visual display offset for top panel
Referenced by Gui::OverlayProxyWidget::getRect().
getDockOverlayHintTriggerSize()
static const long& Gui::OverlayParams::getDockOverlayHintTriggerSize () static
Accessor for parameter DockOverlayHintTriggerSize
Auto hide hint visual display triggering width
Referenced by Gui::OverlayProxyWidget::hitTest().
getDockOverlayMinimumSize()
static const long& Gui::OverlayParams::getDockOverlayMinimumSize () static
Accessor for parameter DockOverlayMinimumSize
Minimum overlay dock widget width/height
Referenced by Gui::OverlayManager::Private::dragDockWidget(), Gui::OverlayTitleBar::mousePressEvent(), Gui::OverlaySplitterHandle::mousePressEvent(), Gui::OverlayTabWidget::onSizeGripMove(), and Gui::OverlayTabWidget::setRect().
getDockOverlayRevealDelay()
static const long& Gui::OverlayParams::getDockOverlayRevealDelay () static
Accessor for parameter DockOverlayRevealDelay.
Referenced by Gui::OverlayManager::Private::dragDockWidget(), and Gui::OverlayManager::Private::onToggleDockWidget().
getDockOverlaySplitterHandleTimeout()
static const long& Gui::OverlayParams::getDockOverlaySplitterHandleTimeout () static
Accessor for parameter DockOverlaySplitterHandleTimeout
Overlay splitter handle auto hide delay. Set zero to disable auto hiding.
Referenced by Gui::OverlaySplitterHandle::leaveEvent(), Gui::OverlaySplitterHandle::showEvent(), and Gui::OverlaySplitterHandle::showTitle().
getDockOverlayWheelDelay()
static const long& Gui::OverlayParams::getDockOverlayWheelDelay () static
Accessor for parameter DockOverlayWheelDelay
Delay capturing mouse wheel event for passing through if it is previously handled by other widget.
Referenced by Gui::OverlayManager::eventFilter().
getDockOverlayWheelPassThrough()
static const bool& Gui::OverlayParams::getDockOverlayWheelPassThrough () static
Accessor for parameter DockOverlayWheelPassThrough
Auto pass through mouse wheel event on transparent dock overlay.
Referenced by Gui::OverlayManager::eventFilter().
getHandle()
static ParameterGrp::handle Gui::OverlayParams::getHandle () static
onDockOverlayAutoViewChanged()
static void Gui::OverlayParams::onDockOverlayAutoViewChanged () static
onDockOverlayCheckNaviCubeChanged()
static void Gui::OverlayParams::onDockOverlayCheckNaviCubeChanged () static
onDockOverlayHideTabBarChanged()
static void Gui::OverlayParams::onDockOverlayHideTabBarChanged () static
onDockOverlayMinimumSizeChanged()
static void Gui::OverlayParams::onDockOverlayMinimumSizeChanged () static
removeDockOverlayActivateOnHover()
static void Gui::OverlayParams::removeDockOverlayActivateOnHover () static
removeDockOverlayAlphaRadius()
static void Gui::OverlayParams::removeDockOverlayAlphaRadius () static
removeDockOverlayAnimationCurve()
static void Gui::OverlayParams::removeDockOverlayAnimationCurve () static
removeDockOverlayAnimationDuration()
static void Gui::OverlayParams::removeDockOverlayAnimationDuration () static
removeDockOverlayAutoMouseThrough()
static void Gui::OverlayParams::removeDockOverlayAutoMouseThrough () static
removeDockOverlayAutoView()
static void Gui::OverlayParams::removeDockOverlayAutoView () static
removeDockOverlayCheckNaviCube()
static void Gui::OverlayParams::removeDockOverlayCheckNaviCube () static
removeDockOverlayDelay()
static void Gui::OverlayParams::removeDockOverlayDelay () static
removeDockOverlayHidePropertyViewScrollBar()
static void Gui::OverlayParams::removeDockOverlayHidePropertyViewScrollBar () static
removeDockOverlayHideTabBar()
static void Gui::OverlayParams::removeDockOverlayHideTabBar () static
removeDockOverlayHintBottomLength()
static void Gui::OverlayParams::removeDockOverlayHintBottomLength () static
removeDockOverlayHintBottomOffset()
static void Gui::OverlayParams::removeDockOverlayHintBottomOffset () static
removeDockOverlayHintDelay()
static void Gui::OverlayParams::removeDockOverlayHintDelay () static
removeDockOverlayHintLeftLength()
static void Gui::OverlayParams::removeDockOverlayHintLeftLength () static
removeDockOverlayHintLeftOffset()
static void Gui::OverlayParams::removeDockOverlayHintLeftOffset () static
removeDockOverlayHintRightLength()
static void Gui::OverlayParams::removeDockOverlayHintRightLength () static
removeDockOverlayHintRightOffset()
static void Gui::OverlayParams::removeDockOverlayHintRightOffset () static
removeDockOverlayHintSize()
static void Gui::OverlayParams::removeDockOverlayHintSize () static
removeDockOverlayHintTabBar()
static void Gui::OverlayParams::removeDockOverlayHintTabBar () static
removeDockOverlayHintTopLength()
static void Gui::OverlayParams::removeDockOverlayHintTopLength () static
removeDockOverlayHintTopOffset()
static void Gui::OverlayParams::removeDockOverlayHintTopOffset () static
removeDockOverlayHintTriggerSize()
static void Gui::OverlayParams::removeDockOverlayHintTriggerSize () static
removeDockOverlayMinimumSize()
static void Gui::OverlayParams::removeDockOverlayMinimumSize () static
removeDockOverlayRevealDelay()
static void Gui::OverlayParams::removeDockOverlayRevealDelay () static
removeDockOverlaySplitterHandleTimeout()
static void Gui::OverlayParams::removeDockOverlaySplitterHandleTimeout () static
removeDockOverlayWheelDelay()
static void Gui::OverlayParams::removeDockOverlayWheelDelay () static
removeDockOverlayWheelPassThrough()
static void Gui::OverlayParams::removeDockOverlayWheelPassThrough () static
setDockOverlayActivateOnHover()
static void Gui::OverlayParams::setDockOverlayActivateOnHover (const bool & v) static
setDockOverlayAlphaRadius()
static void Gui::OverlayParams::setDockOverlayAlphaRadius (const long & v) static
setDockOverlayAnimationCurve()
static void Gui::OverlayParams::setDockOverlayAnimationCurve (const long & v) static
setDockOverlayAnimationDuration()
static void Gui::OverlayParams::setDockOverlayAnimationDuration (const long & v) static
setDockOverlayAutoMouseThrough()
static void Gui::OverlayParams::setDockOverlayAutoMouseThrough (const bool & v) static
setDockOverlayAutoView()
static void Gui::OverlayParams::setDockOverlayAutoView (const bool & v) static
setDockOverlayCheckNaviCube()
static void Gui::OverlayParams::setDockOverlayCheckNaviCube (const bool & v) static
setDockOverlayDelay()
static void Gui::OverlayParams::setDockOverlayDelay (const long & v) static
setDockOverlayHidePropertyViewScrollBar()
static void Gui::OverlayParams::setDockOverlayHidePropertyViewScrollBar (const bool & v) static
setDockOverlayHideTabBar()
static void Gui::OverlayParams::setDockOverlayHideTabBar (const bool & v) static
setDockOverlayHintBottomLength()
static void Gui::OverlayParams::setDockOverlayHintBottomLength (const long & v) static
setDockOverlayHintBottomOffset()
static void Gui::OverlayParams::setDockOverlayHintBottomOffset (const long & v) static
setDockOverlayHintDelay()
static void Gui::OverlayParams::setDockOverlayHintDelay (const long & v) static
setDockOverlayHintLeftLength()
static void Gui::OverlayParams::setDockOverlayHintLeftLength (const long & v) static
setDockOverlayHintLeftOffset()
static void Gui::OverlayParams::setDockOverlayHintLeftOffset (const long & v) static
setDockOverlayHintRightLength()
static void Gui::OverlayParams::setDockOverlayHintRightLength (const long & v) static
setDockOverlayHintRightOffset()
static void Gui::OverlayParams::setDockOverlayHintRightOffset (const long & v) static
setDockOverlayHintSize()
static void Gui::OverlayParams::setDockOverlayHintSize (const long & v) static
setDockOverlayHintTabBar()
static void Gui::OverlayParams::setDockOverlayHintTabBar (const bool & v) static
setDockOverlayHintTopLength()
static void Gui::OverlayParams::setDockOverlayHintTopLength (const long & v) static
setDockOverlayHintTopOffset()
static void Gui::OverlayParams::setDockOverlayHintTopOffset (const long & v) static
setDockOverlayHintTriggerSize()
static void Gui::OverlayParams::setDockOverlayHintTriggerSize (const long & v) static
setDockOverlayMinimumSize()
static void Gui::OverlayParams::setDockOverlayMinimumSize (const long & v) static
setDockOverlayRevealDelay()
static void Gui::OverlayParams::setDockOverlayRevealDelay (const long & v) static
setDockOverlaySplitterHandleTimeout()
static void Gui::OverlayParams::setDockOverlaySplitterHandleTimeout (const long & v) static
setDockOverlayWheelDelay()
static void Gui::OverlayParams::setDockOverlayWheelDelay (const long & v) static
setDockOverlayWheelPassThrough()
static void Gui::OverlayParams::setDockOverlayWheelPassThrough (const bool & v) static
Member Data Documentation
AnimationCurveTypes
const std::vector<QString> Gui::OverlayParams::AnimationCurveTypes static
Definition at line 444 of file OverlayParams.h.
The documentation for this class was generated from the following file:
OverlayParams.h