FreeCAD: Materials::MaterialManager Class Reference
Materials::MaterialManager Class Reference
#include <MaterialManager.h>
Public Member Functions
MaterialManager ()
~MaterialManager () override=default
std::shared_ptr< std::map< QString, std::shared_ptr< Material > > > getMaterials () const
std::shared_ptr< Material > getMaterial (const QString &uuid) const
std::shared_ptr< Material > getMaterialByPath (const QString &path) const
std::shared_ptr< Material > getMaterialByPath (const QString &path, const QString &library) const
std::shared_ptr< Material > getParent (const std::shared_ptr< Material > &material) const
std::shared_ptr< MaterialLibrary > getLibrary (const QString &name) const
bool exists (const QString &uuid) const
bool exists (const std::shared_ptr< MaterialLibrary > &library, const QString &uuid) const
std::shared_ptr< std::list< std::shared_ptr< MaterialLibrary > > > getMaterialLibraries () const
std::shared_ptr< std::map< QString, std::shared_ptr< MaterialTreeNode > > > getMaterialTree (const std::shared_ptr< MaterialLibrary > &library, const std::shared_ptr< Materials::MaterialFilter > &filter) const
std::shared_ptr< std::map< QString, std::shared_ptr< MaterialTreeNode > > > getMaterialTree (const std::shared_ptr< MaterialLibrary > &library, const std::shared_ptr< Materials::MaterialFilter > &filter, const MaterialFilterOptions &options) const
std::shared_ptr< std::map< QString, std::shared_ptr< MaterialTreeNode > > > getMaterialTree (const std::shared_ptr< MaterialLibrary > &library) const
std::shared_ptr< std::list< QString > > getMaterialFolders (const std::shared_ptr< MaterialLibrary > &library) const
void createFolder (const std::shared_ptr< MaterialLibrary > &library, const QString &path) const
void renameFolder (const std::shared_ptr< MaterialLibrary > &library, const QString &oldPath, const QString &newPath) const
void deleteRecursive (const std::shared_ptr< MaterialLibrary > &library, const QString &path) const
void remove (const QString &uuid) const
void saveMaterial (const std::shared_ptr< MaterialLibrary > &library, const std::shared_ptr< Material > &material, const QString &path, bool overwrite, bool saveAsCopy, bool saveInherited) const
bool isMaterial (const fs::path &p) const
bool isMaterial (const QFileInfo &file) const
std::shared_ptr< std::map< QString, std::shared_ptr< Material > > > materialsWithModel (const QString &uuid) const
std::shared_ptr< std::map< QString, std::shared_ptr< Material > > > materialsWithModelComplete (const QString &uuid) const
void dereference (std::shared_ptr< Material > material) const
void dereference () const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static void cleanup ()
static void refresh ()
static std::shared_ptr< App::Material > defaultAppearance ()
static std::shared_ptr< Material > defaultMaterial ()
static QString defaultMaterialUUID ()
static std::shared_ptr< Material > getMaterial (const App::Material &material)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 49 of file MaterialManager.h.
Constructor & Destructor Documentation
MaterialManager()
MaterialManager::MaterialManager ()
Definition at line 54 of file MaterialManager.cpp.
~MaterialManager()
Materials::MaterialManager::~MaterialManager () override default
Member Function Documentation
cleanup()
void MaterialManager::cleanup () static
Definition at line 80 of file MaterialManager.cpp.
Referenced by PyMOD_INIT_FUNC(), and refresh().
createFolder()
void Materials::MaterialManager::createFolder (const std::shared_ptr< MaterialLibrary > & library, const QString & path) const inline
Definition at line 101 of file MaterialManager.h.
defaultAppearance()
std::shared_ptr< App::Material > MaterialManager::defaultAppearance () static
Definition at line 141 of file MaterialManager.cpp.
References App::Material::ambientColor, blue, App::Material::DEFAULT, App::Material::diffuseColor, App::Material::emissiveColor, App::GetApplication(), ParameterGrp::GetBool(), importDXF::getColor(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), ParameterGrp::GetUnsigned(), green, KDL::max(), KDL::min(), red, App::Material::shininess, App::Material::specularColor, and App::Material::transparency.
Referenced by defaultMaterial(), and MatGui::MaterialsEditor::onAppearanceAdd().
defaultMaterial()
std::shared_ptr< Material > MaterialManager::defaultMaterial () static
Definition at line 183 of file MaterialManager.cpp.
References defaultAppearance(), defaultMaterialUUID(), and Materials::ModelUUIDs::ModelUUID_Rendering_Basic.
Referenced by Part::Feature::copyMaterial(), and Part::Feature::Feature().
defaultMaterialUUID()
QString MaterialManager::defaultMaterialUUID () static
Definition at line 210 of file MaterialManager.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and Init::param.
Referenced by defaultMaterial().
deleteRecursive()
void Materials::MaterialManager::deleteRecursive (const std::shared_ptr< MaterialLibrary > & library, const QString & path) const inline
Definition at line 111 of file MaterialManager.h.
dereference() [1/2]
void MaterialManager::dereference () const
Definition at line 392 of file MaterialManager.cpp.
dereference() [2/2]
void MaterialManager::dereference (std::shared_ptr< Material > material) const
Definition at line 407 of file MaterialManager.cpp.
References Materials::MaterialLoader::dereference().
exists() [1/2]
bool MaterialManager::exists (const QString & uuid) const
Definition at line 285 of file MaterialManager.cpp.
References getMaterial().
Referenced by MatGui::MaterialSave::onOk(), and Materials::Material::save().
exists() [2/2]
bool MaterialManager::exists (const std::shared_ptr< MaterialLibrary > & library, const QString & uuid) const
Definition at line 309 of file MaterialManager.cpp.
References getMaterial().
getLibrary()
std::shared_ptr< MaterialLibrary > MaterialManager::getLibrary (const QString & name) const
Definition at line 324 of file MaterialManager.cpp.
Referenced by getMaterialByPath().
getMaterial() [1/2]
std::shared_ptr< Material > MaterialManager::getMaterial (const App::Material & material) static
Definition at line 229 of file MaterialManager.cpp.
References App::Material::uuid.
getMaterial() [2/2]
std::shared_ptr< Material > MaterialManager::getMaterial (const QString & uuid) const
Definition at line 219 of file MaterialManager.cpp.
Referenced by MatGui::MaterialTreeWidget::addFavorites(), MatGui::MaterialTreeWidget::addRecent(), MatGui::MaterialTreeWidget::addRecents(), exists(), getParent(), Materials::Material::saveAppearanceModels(), and Materials::Material::saveModels().
getMaterialByPath() [1/2]
std::shared_ptr< Material > MaterialManager::getMaterialByPath (const QString & path) const
Definition at line 236 of file MaterialManager.cpp.
References Materials::MaterialConfigLoader::getMaterialFromPath(), and Materials::MaterialConfigLoader::isConfigStyle().
getMaterialByPath() [2/2]
std::shared_ptr< Material > MaterialManager::getMaterialByPath (const QString & path, const QString & library) const
Definition at line 278 of file MaterialManager.cpp.
References getLibrary().
getMaterialFolders()
std::shared_ptr< std::list< QString > > MaterialManager::getMaterialFolders (const std::shared_ptr< MaterialLibrary > & library) const
Definition at line 351 of file MaterialManager.cpp.
References Materials::MaterialLoader::getMaterialFolders().
getMaterialLibraries()
std::shared_ptr< std::list< std::shared_ptr< MaterialLibrary > > > MaterialManager::getMaterialLibraries () const
Definition at line 336 of file MaterialManager.cpp.
Referenced by MatGui::MaterialTreeWidget::fillMaterialTree(), and MatGui::MaterialSave::setLibraries().
getMaterials()
std::shared_ptr<std::map<QString, std::shared_ptr<Material> > > Materials::MaterialManager::getMaterials () const inline
Definition at line 63 of file MaterialManager.h.
getMaterialTree() [1/3]
std::shared_ptr<std::map<QString, std::shared_ptr<MaterialTreeNode> > > Materials::MaterialManager::getMaterialTree (const std::shared_ptr< MaterialLibrary > & library) const inline
Definition at line 93 of file MaterialManager.h.
getMaterialTree() [2/3]
std::shared_ptr<std::map<QString, std::shared_ptr<MaterialTreeNode> > > Materials::MaterialManager::getMaterialTree (const std::shared_ptr< MaterialLibrary > & library, const std::shared_ptr< Materials::MaterialFilter > & filter) const inline
Definition at line 79 of file MaterialManager.h.
Referenced by MatGui::MaterialTreeWidget::fillMaterialTree(), and MatGui::MaterialSave::showSelectedTree().
getMaterialTree() [3/3]
std::shared_ptr<std::map<QString, std::shared_ptr<MaterialTreeNode> > > Materials::MaterialManager::getMaterialTree (const std::shared_ptr< MaterialLibrary > & library, const std::shared_ptr< Materials::MaterialFilter > & filter, const MaterialFilterOptions & options) const inline
Definition at line 86 of file MaterialManager.h.
getParent()
std::shared_ptr< Material > MaterialManager::getParent (const std::shared_ptr< Material > & material) const
Definition at line 300 of file MaterialManager.cpp.
References getMaterial().
Referenced by MatGui::MaterialsEditor::updateMaterialGeneral().
isMaterial() [1/2]
bool MaterialManager::isMaterial (const fs::path & p) const
Definition at line 117 of file MaterialManager.cpp.
References buildPsets::p.
isMaterial() [2/2]
bool MaterialManager::isMaterial (const QFileInfo & file) const
Definition at line 129 of file MaterialManager.cpp.
References DrawingExample::file.
materialsWithModel()
std::shared_ptr< std::map< QString, std::shared_ptr< Material > > > MaterialManager::materialsWithModel (const QString & uuid) const
Definition at line 357 of file MaterialManager.cpp.
References Path.Base.SetupSheet::dict.
materialsWithModelComplete()
std::shared_ptr< std::map< QString, std::shared_ptr< Material > > > MaterialManager::materialsWithModelComplete (const QString & uuid) const
Definition at line 375 of file MaterialManager.cpp.
References Path.Base.SetupSheet::dict.
refresh()
void MaterialManager::refresh () static
Definition at line 99 of file MaterialManager.cpp.
References cleanup().
remove()
void Materials::MaterialManager::remove (const QString & uuid) const inline
Definition at line 116 of file MaterialManager.h.
renameFolder()
void Materials::MaterialManager::renameFolder (const std::shared_ptr< MaterialLibrary > & library, const QString & oldPath, const QString & newPath) const inline
Definition at line 105 of file MaterialManager.h.
saveMaterial()
void MaterialManager::saveMaterial (const std::shared_ptr< MaterialLibrary > & library, const std::shared_ptr< Material > & material, const QString & path, bool overwrite, bool saveAsCopy, bool saveInherited) const
Definition at line 106 of file MaterialManager.cpp.
Referenced by MatGui::MaterialSave::onOk().
The documentation for this class was generated from the following files:
MaterialManager.h
MaterialManager.cpp