FreeCAD: Base::NurbsSurfaceItem Class Reference
Base::NurbsSurfaceItem Class Reference
The NurbsSurfaceItem class supports the SoNurbsSurface node.
#include <Builder3D.h>
Public Member Functions
void setControlPoints (int numU, int numV)
void setKnotVector (const std::vector< float > &, const std::vector< float > &)
void write (InventorOutput &out) const override
Public Member Functions inherited from Base::NodeItem
virtual ~NodeItem ()=default
Additional Inherited Members
Protected Member Functions inherited from Base::NodeItem
NodeItem ()=default
NodeItem (const NodeItem &)=default
NodeItem (NodeItem &&)=default
NodeItem & operator= (const NodeItem &)=default
NodeItem & operator= (NodeItem &&)=default
Detailed Description
The NurbsSurfaceItem class supports the SoNurbsSurface node.
Definition at line 627 of file Builder3D.h.
Member Function Documentation
setControlPoints()
void NurbsSurfaceItem::setControlPoints (int numU, int numV)
Definition at line 875 of file Builder3D.cpp.
setKnotVector()
void NurbsSurfaceItem::setKnotVector (const std::vector< float > & uKnots, const std::vector< float > & vKnots)
Definition at line 881 of file Builder3D.cpp.
write()
void NurbsSurfaceItem::write (InventorOutput & out) const override virtual
Implements Base::NodeItem.
Definition at line 888 of file Builder3D.cpp.
References Base::InventorOutput::decreaseIndent(), Base::InventorOutput::increaseIndent(), Base::InventorOutput::write(), and Base::InventorFieldWriter::write().
The documentation for this class was generated from the following files:
Builder3D.h
Builder3D.cpp