FreeCAD: Gui::WorkbenchComboBox Class Reference
Gui::WorkbenchComboBox Class Reference
#include <WorkbenchSelector.h>
Public Slots
void refreshList (QList< QAction * >)
Public Member Functions
WorkbenchComboBox (WorkbenchGroup *aGroup, QWidget *parent=nullptr)
~WorkbenchComboBox () override=default
WorkbenchComboBox (WorkbenchComboBox &&rhs)=delete
void showPopup () override
WorkbenchComboBox operator= (WorkbenchComboBox &&rhs)=delete
Detailed Description
Definition at line 66 of file WorkbenchSelector.h.
Constructor & Destructor Documentation
WorkbenchComboBox() [1/2]
WorkbenchComboBox::WorkbenchComboBox (WorkbenchGroup * aGroup, QWidget * parent = nullptr) explicit
Definition at line 49 of file WorkbenchSelector.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::Action::action(), Gui::ActionGroup::actions(), draftgeoutils.intersections::connect(), Gui::WorkbenchGroup::getEnabledWbActions(), Gui::ActionGroup::groupAction(), refreshList(), Gui::Action::toolTip(), and Gui::WorkbenchGroup::workbenchListRefreshed().
~WorkbenchComboBox()
Gui::WorkbenchComboBox::~WorkbenchComboBox () override default
WorkbenchComboBox() [2/2]
Gui::WorkbenchComboBox::WorkbenchComboBox (WorkbenchComboBox && rhs) delete
Member Function Documentation
operator=()
WorkbenchComboBox Gui::WorkbenchComboBox::operator= (WorkbenchComboBox && rhs) delete
refreshList
void WorkbenchComboBox::refreshList (QList< QAction * > actionList) slot
Definition at line 77 of file WorkbenchSelector.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Path.Op.Gui.Selection::clear(), src.Mod.AddonManager.NetworkManager::count, App::GetApplication(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), Gui::IconOnly, and Gui::TextOnly.
Referenced by WorkbenchComboBox().
showPopup()
void WorkbenchComboBox::showPopup () override
Definition at line 65 of file WorkbenchSelector.cpp.
References src.Mod.AddonManager.NetworkManager::count.
The documentation for this class was generated from the following files:
WorkbenchSelector.h
WorkbenchSelector.cpp