FreeCAD: Base::ZipWriter Class Reference
Base::ZipWriter Class Reference
#include <Writer.h>
Public Member Functions
ZipWriter (const char *FileName)
ZipWriter (std::ostream &)
~ZipWriter () override
void writeFiles () override
process the requested file storing
std::ostream & Stream () override
void setComment (const char *str)
void setLevel (int level)
void putNextEntry (const char *filename, const char *objName=nullptr) override
put the next entry with a give name
ZipWriter (const ZipWriter &)=delete
ZipWriter (ZipWriter &&)=delete
ZipWriter & operator= (const ZipWriter &)=delete
ZipWriter & operator= (ZipWriter &&)=delete
Public Member Functions inherited from Base::Writer
Writer ()
virtual ~Writer ()
void setForceXML (bool on)
switch the writer in XML only mode (no files allowed)
bool isForceXML () const
check on state
void setFileVersion (int)
int getFileVersion () const
void insertAsciiFile (const char *FileName)
insert a file as CDATA section in the XML file
void insertBinFile (const char *FileName)
insert a binary file BASE64 coded as CDATA section in the XML file
void insertText (const std::string &str)
insert text string as CDATA
std::string addFile (const char *Name, const Base::Persistence *Object)
add a write request of a persistent object
const std::vector< std::string > & getFilenames () const
get all registered file names
void setMode (const std::string &mode)
Set mode.
void setModes (const std::set< std::string > &modes)
Set modes.
bool getMode (const std::string &mode) const
Get mode.
std::set< std::string > getModes () const
Get modes.
void clearMode (const std::string &mode)
Clear mode.
void clearModes ()
Clear modes.
void addError (const std::string &)
bool hasErrors () const
void clearErrors ()
std::vector< std::string > getErrors () const
const char * ind () const
get the current indentation
void incInd ()
increase indentation by one tab
void decInd ()
decrease indentation by one tab
std::ostream & beginCharStream (CharStreamFormat format=CharStreamFormat::Raw)
std::ostream & endCharStream ()
std::ostream & charStream ()
Return the current character output stream.
Writer (const Writer &)=delete
Writer (Writer &&)=delete
Writer & operator= (const Writer &)=delete
Writer & operator= (Writer &&)=delete
Additional Inherited Members
Public Attributes inherited from Base::Writer
std::string ObjectName
name for underlying file saves
Protected Member Functions inherited from Base::Writer
std::string getUniqueFileName (const char *Name)
Protected Attributes inherited from Base::Writer
std::vector< FileEntry > FileList
std::vector< std::string > FileNames
std::vector< std::string > Errors
std::set< std::string > Modes
short indent {0}
char indBuf [1024] {}
bool forceXML {false}
int fileVersion {1}
Detailed Description
The ZipWriter class This is an important helper class implementation for the store and retrieval system of persistent objects in FreeCAD.
See also
Base::Persistence
Author
Juergen Riegel
Definition at line 210 of file Writer.h.
Constructor & Destructor Documentation
ZipWriter() [1/4]
ZipWriter::ZipWriter (const char * FileName) explicit
Definition at line 330 of file Writer.cpp.
ZipWriter() [2/4]
ZipWriter::ZipWriter (std::ostream & os) explicit
Definition at line 342 of file Writer.cpp.
~ZipWriter()
ZipWriter::~ZipWriter () override
Definition at line 376 of file Writer.cpp.
ZipWriter() [3/4]
Base::ZipWriter::ZipWriter (const ZipWriter &) delete
ZipWriter() [4/4]
Base::ZipWriter::ZipWriter (ZipWriter &&) delete
Member Function Documentation
operator=() [1/2]
ZipWriter& Base::ZipWriter::operator= (const ZipWriter &) delete
operator=() [2/2]
ZipWriter& Base::ZipWriter::operator= (ZipWriter &&) delete
putNextEntry()
void ZipWriter::putNextEntry (const char * filename, const char * objName = nullptr) override virtual
put the next entry with a give name
Reimplemented from Base::Writer.
Definition at line 354 of file Writer.cpp.
References DrawingExample::file, and Base::Writer::putNextEntry().
Referenced by Base::Persistence::dumpToStream(), App::Document::exportObjects(), App::ProjectFile::replacePropertyFiles(), Sandbox::DocumentSaverThread::run(), Gui::AutoSaver::saveDocument(), App::Document::saveToFile(), and writeFiles().
setComment()
void Base::ZipWriter::setComment (const char * str) inline
Definition at line 224 of file Writer.h.
Referenced by App::ProjectFile::replacePropertyFiles(), Sandbox::DocumentSaverThread::run(), Gui::AutoSaver::saveDocument(), and App::Document::saveToFile().
setLevel()
void Base::ZipWriter::setLevel (int level) inline
Definition at line 228 of file Writer.h.
Referenced by Base::Persistence::dumpToStream(), App::ProjectFile::replacePropertyFiles(), Sandbox::DocumentSaverThread::run(), Gui::AutoSaver::saveDocument(), and App::Document::saveToFile().
Stream()
std::ostream& Base::ZipWriter::Stream () inline override virtual
Implements Base::Writer.
Definition at line 219 of file Writer.h.
Referenced by Base::Persistence::dumpToStream(), App::Document::exportObjects(), App::ProjectFile::replacePropertyFiles(), and App::Document::saveToFile().
writeFiles()
void ZipWriter::writeFiles () override virtual
process the requested file storing
Implements Base::Writer.
Definition at line 361 of file Writer.cpp.
References Base::Writer::FileList, Base::Writer::FileEntry::FileName, Base::Writer::indBuf, Base::Writer::indent, Base::Writer::FileEntry::Object, putNextEntry(), and Base::Persistence::SaveDocFile().
Referenced by Base::Persistence::dumpToStream(), App::Document::exportObjects(), Sandbox::DocumentSaverThread::run(), Gui::AutoSaver::saveDocument(), and App::Document::saveToFile().
The documentation for this class was generated from the following files:
Writer.h
Writer.cpp