FreeCAD: PartGui::ShapeBuilderWidget Class Reference
PartGui::ShapeBuilderWidget Class Reference
#include <TaskShapeBuilder.h>
Classes
class Private
Public Member Functions
ShapeBuilderWidget (QWidget *parent=nullptr)
~ShapeBuilderWidget () override
bool accept ()
bool reject ()
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Detailed Description
Definition at line 53 of file TaskShapeBuilder.h.
Constructor & Destructor Documentation
ShapeBuilderWidget()
ShapeBuilderWidget::ShapeBuilderWidget (QWidget * parent = nullptr) explicit
Definition at line 106 of file TaskShapeBuilder.cpp.
References Gui::SelectionSingleton::addSelectionGate(), PartGui::ShapeBuilderWidget::Private::bg, draftgeoutils.intersections::connect(), PartGui::ShapeBuilderWidget::Private::gate, Init::parent, Gui::Selection(), and PartGui::ShapeBuilderWidget::Private::ui.
~ShapeBuilderWidget()
ShapeBuilderWidget::~ShapeBuilderWidget () override
Definition at line 139 of file TaskShapeBuilder.cpp.
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
accept()
bool ShapeBuilderWidget::accept ()
Definition at line 578 of file TaskShapeBuilder.cpp.
Referenced by PartGui::TaskShapeBuilder::accept().
reject()
bool ShapeBuilderWidget::reject ()
Definition at line 583 of file TaskShapeBuilder.cpp.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and PartGui::TaskShapeBuilder::reject().
The documentation for this class was generated from the following files:
TaskShapeBuilder.h
TaskShapeBuilder.cpp