FreeCAD: CAMTests.TestPathThreadMillingGenerator.TestPathThreadMillingGenerator Class Reference
CAMTests.TestPathThreadMillingGenerator.TestPathThreadMillingGenerator Class Reference
Public Member Functions
def test00 (self)
def test01 (self)
def test02 (self)
def test03 (self)
def test04 (self)
def test10 (self)
def test11 (self)
Public Member Functions inherited from CAMTests.PathTestUtils.PathTestBase
def assertRoughly (self, f1, f2, error=0.00001)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertPlacement (self, p1, p2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertArc (self, edge, pt1, pt2, direction="CW")
def assertCircle (self, edge, pt, r)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCommandEqual (self, c1, c2)
def assertEqualLocale (self, s1, s2)
def assertEdgeShapesMatch (self, e1, e2)
def assertPointsMatch (self, pts0, pts1)
def assertSuccessfulRecompute (self, doc, *objs, msg=None)
Detailed Description
Test thread milling generator.
Definition at line 35 of file TestPathThreadMillingGenerator.py.
Member Function Documentation
test00()
def CAMTests.TestPathThreadMillingGenerator.TestPathThreadMillingGenerator.test00 (self)
Verify thread commands for a single thread
Definition at line 38 of file TestPathThreadMillingGenerator.py.
References CAMTests.PathTestUtils.PathTestBase.assertCoincide().
Referenced by CAMTests.TestPathToolController.TestPathToolController.test01().
test01()
def CAMTests.TestPathThreadMillingGenerator.TestPathThreadMillingGenerator.test01 (self)
Verify thread commands for a thwo threads
Definition at line 65 of file TestPathThreadMillingGenerator.py.
References CAMTests.PathTestUtils.PathTestBase.assertCoincide().
test02()
def CAMTests.TestPathThreadMillingGenerator.TestPathThreadMillingGenerator.test02 (self)
Verify thread commands for a one and a half threads
Definition at line 94 of file TestPathThreadMillingGenerator.py.
References CAMTests.PathTestUtils.PathTestBase.assertCoincide().
test03()
def CAMTests.TestPathThreadMillingGenerator.TestPathThreadMillingGenerator.test03 (self)
Verify thread commands for a one and 3 quarter threads
Definition at line 122 of file TestPathThreadMillingGenerator.py.
References CAMTests.PathTestUtils.PathTestBase.assertCoincide().
test04()
def CAMTests.TestPathThreadMillingGenerator.TestPathThreadMillingGenerator.test04 (self)
Verify thread commands for a one and 3 quarter threads - CCW
Definition at line 153 of file TestPathThreadMillingGenerator.py.
References CAMTests.PathTestUtils.PathTestBase.assertCoincide().
test10()
def CAMTests.TestPathThreadMillingGenerator.TestPathThreadMillingGenerator.test10 (self)
Verify lead in/out commands for a single thread
Definition at line 184 of file TestPathThreadMillingGenerator.py.
References CAMTests.PathTestUtils.PathTestBase.assertCoincide().
test11()
def CAMTests.TestPathThreadMillingGenerator.TestPathThreadMillingGenerator.test11 (self)
Verify lead in/out commands for one and a half threads
Definition at line 215 of file TestPathThreadMillingGenerator.py.
References CAMTests.PathTestUtils.PathTestBase.assertCoincide().
The documentation for this class was generated from the following file:
TestPathThreadMillingGenerator.py