FreeCAD: femtools.femutils Namespace Reference
femtools.femutils Namespace Reference
Functions
def createObject (doc, name, proxy, viewProxy=None)
def type_of_obj (obj)
def is_of_type (obj, ty)
def is_derived_from (obj, t)
def get_pref_working_dir (solver_obj)
def get_temp_dir (obj=None)
def get_beside_dir (obj)
def get_custom_dir (obj)
def get_beside_base (obj)
def get_custom_base (solver)
def check_working_dir (wdir)
def make_dir (specific_path)
def getBoundBoxOfAllDocumentShapes (doc)
def getSelectedFace (selectionex)
def get_refshape_type (fem_doc_object)
def pydecode (bytestring)
def startProgramInfo (code)
def expandParentObject ()
def getOutputWinColor (type)
Function Documentation
check_working_dir()
def femtools.femutils.check_working_dir (wdir)
Definition at line 207 of file femutils.py.
createObject()
def femtools.femutils.createObject (doc, name, proxy, viewProxy = None)
Add python object to document using python type string.
Add a document object suitable for the *proxy* and the *viewProxy* to *doc*
and attach it to the *proxy* and the *viewProxy*. This function can only be
used with python proxies that specify their C++ type via the BaseType class
member (e.g. Cube.BaseType). If there already exists a object with *name* a
suitable unique name is generated. To auto generate a name pass ``""``.
:param doc:         document object to which the object is added
:param name:        string of the name of new object in *doc*, use
                    ``""`` to generate a name
:param proxy:       python proxy for new object
:param viewProxy:   view proxy for new object
:returns:           reference to new object
Definition at line 48 of file femutils.py.
Referenced by DraftGui.DraftToolBar.sendText().
expandParentObject()
def femtools.femutils.expandParentObject ()
expands parent and selected obj in tree view
Definition at line 375 of file femutils.py.
Referenced by femcommands.commands._SolverCalculixContextManager.__exit__(), femcommands.commands._SolverElmer.Activated(), femcommands.manager.CommandManager.add_obj_on_gui_expand_noset_edit(), and femcommands.manager.CommandManager.add_obj_on_gui_selobj_expand_noset_edit().
get_beside_base()
def femtools.femutils.get_beside_base (obj)
Definition at line 171 of file femutils.py.
References femtools.femutils.get_temp_dir().
Referenced by femtools.femutils.get_beside_dir().
get_beside_dir()
def femtools.femutils.get_beside_dir (obj)
Definition at line 155 of file femutils.py.
References femtools.femutils.get_beside_base(), and femtools.femutils.make_dir().
Referenced by femtools.femutils.get_pref_working_dir(), and femexamples.manager.run_analysis().
get_custom_base()
def femtools.femutils.get_custom_base (solver)
Definition at line 190 of file femutils.py.
References femtools.femutils.get_custom_dir(), and femtools.femutils.get_temp_dir().
Referenced by femtools.femutils.get_custom_dir().
get_custom_dir()
def femtools.femutils.get_custom_dir (obj)
Definition at line 163 of file femutils.py.
References femtools.femutils.get_custom_base(), and femtools.femutils.make_dir().
Referenced by femtools.femutils.get_custom_base(), and femtools.femutils.get_pref_working_dir().
get_pref_working_dir()
def femtools.femutils.get_pref_working_dir (solver_obj)
Return working directory for solver honoring user settings.
:throws femtools.errors.MustSaveError:
 If user setting is set to BESIDE and the document isn't saved.
:note:
 Not working correctly for most cases because this circumvents directory
 caching of the solver framework. For solver use getMachine from run.py
 instead.
Definition at line 121 of file femutils.py.
References femtools.femutils.get_beside_dir(), femtools.femutils.get_custom_dir(), and femtools.femutils.get_temp_dir().
get_refshape_type()
def femtools.femutils.get_refshape_type (fem_doc_object)
Return shape type the constraints references.
Determine single shape type of references of *fem_doc_object* which must be
a constraint (=have a *References* property). All references must be of the
same type which is than returned as a string. A type can be "Vertex",
"Edge", "Face" or "Solid".
:param fem_doc_object:
 A constraint object with a *References* property.
:returns:
 A string representing the shape type ("Vertex", "Edge", "Face" or
 "Solid"). If *fem_doc_object* isn't a constraint ``""`` is returned.
:note:
 Undefined behaviour if the type of the references of one object are
 not all the same.
:note:
 Undefined behaviour if constraint contains no references (empty list).
Definition at line 312 of file femutils.py.
References UtilsAssembly.get_element().
get_temp_dir()
def femtools.femutils.get_temp_dir (obj = None)
Definition at line 149 of file femutils.py.
Referenced by femtools.femutils.get_beside_base(), femtools.femutils.get_custom_base(), femtools.femutils.get_pref_working_dir(), and femtools.femutils.make_dir().
getBoundBoxOfAllDocumentShapes()
def femtools.femutils.getBoundBoxOfAllDocumentShapes (doc)
Calculate bounding box containing all objects inside *doc*.
:returns:
 A bounding box containing all objects that have a *Shape* attribute (all
 Part and PartDesign objects). If the document contains no such objects or
 no objects at all return ``None``.
Definition at line 236 of file femutils.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by femcommands.commands._ClippingPlaneAdd.Activated().
getOutputWinColor()
def femtools.femutils.getOutputWinColor (type)
type: 'Error', 'Warning', 'Logging', 'Text'
Definition at line 386 of file femutils.py.
Referenced by femtaskpanels.task_solver_ccxtools._TaskPanel.femConsoleMessage(), femtaskpanels.base_femmeshtaskpanel._BaseMeshTaskPanel.process_finished(), femtaskpanels.base_femmeshtaskpanel._BaseMeshTaskPanel.process_started(), femtaskpanels.base_femmeshtaskpanel._BaseMeshTaskPanel.thread_started(), femtaskpanels.base_femmeshtaskpanel._BaseMeshTaskPanel.write_error(), and femtaskpanels.base_femmeshtaskpanel._BaseMeshTaskPanel.write_output().
getSelectedFace()
def femtools.femutils.getSelectedFace (selectionex)
Return selected face if exactly one face is selected.
:returns:
 The selected face as a ``Part::TopoShape`` if exactly one face is selected.
 Otherwise return ``None``.
:param selectionex:
 A list of selection object like the one Gui.Selection.getSelectionEx()
 returns.
Definition at line 283 of file femutils.py.
Referenced by femcommands.commands._ClippingPlaneAdd.Activated().
is_derived_from()
def femtools.femutils.is_derived_from (obj, t)
Check if *obj* is derived from *t* honoring Fems typesystem.
Essentially just call ``obj.isDerivedFrom(t)`` and return it's value. For
objects using Fems typesystem (see :py:func:`type_of_obj`) return always
True if the Fem type is equal to *t*.
:note:
 Inheritance of Fem types is not checked. If *obj* uses Fems typesystem the
 type is just checked for equality. If the type doesn't match
 ``obj.isDerivedFrom`` is called as usual. See
 https://forum.freecad.org/viewtopic.php?f=10&t=32625
Definition at line 101 of file femutils.py.
Referenced by femexamples.manager.run_analysis(), and femtest.app.test_object.TestObjectType.test_femobjects_derivedfromfem().
is_of_type()
def femtools.femutils.is_of_type (obj, ty)
Compare type of *obj* with *ty* honoring Fems typesystem.
See :py:func:`type_of_obj` for more info about the special typesystem of
the Fem module.
:returns:
 ``True`` if *obj* is of type *ty*, ``False`` otherwise. Type must match
 exactly: Derived objects are not considered to be of type of one of their
 super classes.
Definition at line 87 of file femutils.py.
References femtools.femutils.type_of_obj().
Referenced by femcommands.commands._MaterialMechanicalNonlinear.Activated(), femcommands.commands._SolverCcxTools.Activated(), femcommands.commands._SolverCalculix.Activated(), femresult.resulttools.add_principal_stress_reinforced(), femviewprovider.view_mesh_gmsh.VPMeshGmsh.canDragObject(), femviewprovider.view_mesh_gmsh.VPMeshGmsh.dragObject(), femviewprovider.view_mesh_gmsh.VPMeshGmsh.dropObject(), femmesh.meshtools.get_analysis_group_elements(), femresult.resulttools.get_concrete_nodes(), femmesh.meshtools.get_elset_short_name(), femcommands.manager.CommandManager.gmsh_femmesh_selected(), femresult.resulttools.purge_results(), femcommands.manager.CommandManager.result_mesh_present(), femcommands.manager.CommandManager.solver_elmer_selected(), and femtest.app.test_object.TestObjectType.test_femobjects_isoftype().
make_dir()
def femtools.femutils.make_dir (specific_path)
Definition at line 218 of file femutils.py.
References femtools.femutils.get_temp_dir().
Referenced by femtools.femutils.get_beside_dir(), and femtools.femutils.get_custom_dir().
pydecode()
def femtools.femutils.pydecode (bytestring)
Return *bytestring* as a unicode string
Definition at line 351 of file femutils.py.
startProgramInfo()
def femtools.femutils.startProgramInfo (code)
starts a program under Windows minimized, hidden or normal
Definition at line 356 of file femutils.py.
type_of_obj()
def femtools.femutils.type_of_obj (obj)
Return type of *obj* honoring the special typesystem of Fem.
Python objects of the Fem workbench define their type via a class member
``<Class>.Type``. Return this type if the property exists. If not return
the conventional ``TypeId`` value.
:para obj: a document object
Definition at line 73 of file femutils.py.
Referenced by femtest.app.test_open.TestObjectOpen.compare_cpp_objs(), femtest.app.test_open.TestObjectOpen.compare_feature_pythons_class_app(), femtest.gui.test_open.TestObjectOpen.compare_feature_pythons_class_gui(), femtools.femutils.is_of_type(), and femtest.app.test_object.TestObjectType.test_femobjects_type().