FreeCAD: Materials::ModelManager Class Reference
Materials::ModelManager Class Reference
#include <ModelManager.h>
Public Member Functions
ModelManager ()
~ModelManager () override=default
void refresh ()
std::shared_ptr< std::list< std::shared_ptr< ModelLibrary > > > getModelLibraries ()
std::shared_ptr< std::map< QString, std::shared_ptr< Model > > > getModels ()
std::shared_ptr< std::map< QString, std::shared_ptr< ModelTreeNode > > > getModelTree (std::shared_ptr< ModelLibrary > library, ModelFilter filter=ModelFilter_None) const
std::shared_ptr< Model > getModel (const QString &uuid) const
std::shared_ptr< Model > getModelByPath (const QString &path) const
std::shared_ptr< Model > getModelByPath (const QString &path, const QString &lib) const
std::shared_ptr< ModelLibrary > getLibrary (const QString &name) const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static void cleanup ()
static bool isModel (const QString &file)
static bool passFilter (ModelFilter filter, Model::ModelType modelType)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 58 of file ModelManager.h.
Constructor & Destructor Documentation
ModelManager()
ModelManager::ModelManager ()
Definition at line 44 of file ModelManager.cpp.
~ModelManager()
Materials::ModelManager::~ModelManager () override default
Member Function Documentation
cleanup()
void ModelManager::cleanup () static
Definition at line 75 of file ModelManager.cpp.
Referenced by PyMOD_INIT_FUNC().
getLibrary()
std::shared_ptr< ModelLibrary > ModelManager::getLibrary (const QString & name) const
Definition at line 132 of file ModelManager.cpp.
Referenced by getModelByPath().
getModel()
std::shared_ptr< Model > ModelManager::getModel (const QString & uuid) const
Definition at line 99 of file ModelManager.cpp.
Referenced by MatGui::MaterialsEditor::onAppearanceAdd(), Materials::Material::saveAppearanceModels(), Materials::Material::saveModels(), MatGui::MaterialsEditor::updateMaterialAppearance(), and MatGui::MaterialsEditor::updateMaterialProperties().
getModelByPath() [1/2]
std::shared_ptr< Model > ModelManager::getModelByPath (const QString & path) const
Definition at line 113 of file ModelManager.cpp.
getModelByPath() [2/2]
std::shared_ptr< Model > ModelManager::getModelByPath (const QString & path, const QString & lib) const
Definition at line 126 of file ModelManager.cpp.
References getLibrary().
getModelLibraries()
std::shared_ptr<std::list<std::shared_ptr<ModelLibrary> > > Materials::ModelManager::getModelLibraries () inline
Definition at line 88 of file ModelManager.h.
getModels()
std::shared_ptr<std::map<QString, std::shared_ptr<Model> > > Materials::ModelManager::getModels () inline
Definition at line 92 of file ModelManager.h.
getModelTree()
std::shared_ptr<std::map<QString, std::shared_ptr<ModelTreeNode> > > Materials::ModelManager::getModelTree (std::shared_ptr< ModelLibrary > library, ModelFilter filter = ModelFilter_None) const inline
Definition at line 97 of file ModelManager.h.
isModel()
bool ModelManager::isModel (const QString & file) static
Definition at line 64 of file ModelManager.cpp.
References DrawingExample::file.
Referenced by Materials::ModelLibrary::getModelTree().
passFilter()
bool ModelManager::passFilter (ModelFilter filter, Model::ModelType modelType) static
Definition at line 143 of file ModelManager.cpp.
References Materials::ModelFilter_Appearance, Materials::ModelFilter_None, Materials::ModelFilter_Physical, Materials::Model::ModelType_Appearance, and Materials::Model::ModelType_Physical.
Referenced by Materials::ModelLibrary::getModelTree().
refresh()
void ModelManager::refresh ()
Definition at line 90 of file ModelManager.cpp.
The documentation for this class was generated from the following files:
ModelManager.h
ModelManager.cpp