FreeCAD: PartDesignGui::SketchWorkflow Class Reference
PartDesignGui::SketchWorkflow Class Reference
#include <SketchWorkflow.h>
Public Member Functions
SketchWorkflow (Gui::Document *)
void createSketch ()
Detailed Description
Definition at line 43 of file SketchWorkflow.h.
Constructor & Destructor Documentation
SketchWorkflow()
SketchWorkflow::SketchWorkflow (Gui::Document * document) explicit
Definition at line 641 of file SketchWorkflow.cpp.
References Gui::Document::getDocument().
Member Function Documentation
createSketch()
void SketchWorkflow::createSketch ()
Definition at line 647 of file SketchWorkflow.cpp.
References Gui::getMainWindow(), and Path.Log::warning().
The documentation for this class was generated from the following files:
SketchWorkflow.h
SketchWorkflow.cpp