FreeCAD: Base::UnitsSchemaImperialBuilding Class Reference
Base::UnitsSchemaImperialBuilding Class Reference
#include <UnitsSchemaImperial1.h>
Public Member Functions
std::string schemaTranslate (const Base::Quantity &quant, double &factor, std::string &unitString) override
This method translates the quantity in a string as the user may expect it.
std::string getBasicLengthUnit () const override
bool isMultiUnitLength () const override
Public Member Functions inherited from Base::UnitsSchema
UnitsSchema ()=default
UnitsSchema (const UnitsSchema &)=default
UnitsSchema (UnitsSchema &&)=default
UnitsSchema & operator= (const UnitsSchema &)=default
UnitsSchema & operator= (UnitsSchema &&)=default
virtual ~UnitsSchema ()=default
virtual void setSchemaUnits ()
virtual void resetSchemaUnits ()
If you use setSchemaUnits() you also have to impment this method to undo your changes!
std::string toLocale (const Base::Quantity &quant, double factor, const std::string &unitString) const
virtual bool isMultiUnitAngle () const
Detailed Description
The schema class for the imperial unit system Here are the definitions for the imperial unit system. It also defines how the value/units get printed.
Definition at line 85 of file UnitsSchemaImperial1.h.
Member Function Documentation
getBasicLengthUnit()
std::string Base::UnitsSchemaImperialBuilding::getBasicLengthUnit () const inline override virtual
Reimplemented from Base::UnitsSchema.
Definition at line 90 of file UnitsSchemaImperial1.h.
isMultiUnitLength()
bool Base::UnitsSchemaImperialBuilding::isMultiUnitLength () const inline override virtual
Reimplemented from Base::UnitsSchema.
Definition at line 96 of file UnitsSchemaImperial1.h.
schemaTranslate()
std::string UnitsSchemaImperialBuilding::schemaTranslate (const Base::Quantity & quant, double & factor, std::string & unitString) override virtual
This method translates the quantity in a string as the user may expect it.
Implements Base::UnitsSchema.
Definition at line 190 of file UnitsSchemaImperial1.cpp.
References a, KDL::abs(), Base::Unit::Angle, Base::Unit::Area, SCL.SimpleDataTypes::b, Base::QuantityFormat::getDenominator(), Base::Quantity::getFormat(), Base::Unit::getString(), Base::Quantity::getUnit(), Base::Quantity::getValue(), Base::Unit::Length, Base::UnitsSchema::toLocale(), unit(), Base::Unit::Velocity, and Base::Unit::Volume.
The documentation for this class was generated from the following files:
UnitsSchemaImperial1.h
UnitsSchemaImperial1.cpp