FreeCAD: Gui::Dialog::ParameterGroup Class Reference
Gui::Dialog::ParameterGroup Class Reference
#include <DlgParameterImp.h>
Public Member Functions
ParameterGroup (QWidget *parent=nullptr)
~ParameterGroup () override
Protected Slots
void onDeleteSelectedItem ()
void onCreateSubgroup ()
void onToggleSelectedItem ()
void onExportToFile ()
void onImportFromFile ()
void onRenameSelectedItem ()
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *event) override
void keyPressEvent (QKeyEvent *event) override
void changeEvent (QEvent *e) override
Detailed Description
The ParameterGroup class represents the tree structure of the parameters. The leaves represented by ParameterValueItem are displayed in ParameterValue.
Author
Werner Mayer
Definition at line 134 of file DlgParameterImp.h.
Constructor & Destructor Documentation
ParameterGroup()
ParameterGroup::ParameterGroup (QWidget * parent = nullptr) explicit
Definition at line 491 of file DlgParameterImp.cpp.
References onCreateSubgroup(), onDeleteSelectedItem(), onExportToFile(), onImportFromFile(), onRenameSelectedItem(), and onToggleSelectedItem().
~ParameterGroup()
ParameterGroup::~ParameterGroup () override default
Member Function Documentation
changeEvent()
void ParameterGroup::changeEvent (QEvent * e) override protected
Definition at line 668 of file DlgParameterImp.cpp.
References SCL.SimpleDataTypes::e.
contextMenuEvent()
void ParameterGroup::contextMenuEvent (QContextMenuEvent * event) override protected
Shows the context menu.
Definition at line 511 of file DlgParameterImp.cpp.
keyPressEvent()
void ParameterGroup::keyPressEvent (QKeyEvent * event) override protected
Triggers the "Del" key.
Definition at line 529 of file DlgParameterImp.cpp.
References onDeleteSelectedItem().
onCreateSubgroup
void ParameterGroup::onCreateSubgroup () protected slot
Creates a sub-group to the current selected parameter group.
Definition at line 577 of file DlgParameterImp.cpp.
References ParameterGrp::GetGroup(), importers.exportIFC::getText(), ParameterGrp::HasGroup(), geoff_geometry::Normal(), and Gui::validateInput().
Referenced by ParameterGroup().
onDeleteSelectedItem
void ParameterGroup::onDeleteSelectedItem () protected slot
Removes the underlying parameter group and its sub-groups from the parameter tree structure.
Definition at line 539 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterGroupItem::_hcGrp, Init::parent, and ParameterGrp::RemoveGrp().
Referenced by keyPressEvent(), and ParameterGroup().
onExportToFile
void ParameterGroup::onExportToFile () protected slot
Exports the current selected parameter with all sub-groups to a file.
Definition at line 608 of file DlgParameterImp.cpp.
References ParameterGrp::exportTo(), DrawingExample::file, and Gui::FileDialog::getSaveFileName().
Referenced by ParameterGroup().
onImportFromFile
void ParameterGroup::onImportFromFile () protected slot
Imports a file and inserts the parameter to the current selected parameter node.
Definition at line 624 of file DlgParameterImp.cpp.
References DrawingExample::file, ParameterGrp::GetGroups(), Gui::FileDialog::getOpenFileName(), and ParameterGrp::importFrom().
Referenced by ParameterGroup().
onRenameSelectedItem
void ParameterGroup::onRenameSelectedItem () protected slot
Changes the name of the leaf of the selected item.
Definition at line 660 of file DlgParameterImp.cpp.
Referenced by ParameterGroup().
onToggleSelectedItem
void ParameterGroup::onToggleSelectedItem () protected slot
Expands or closes the selected item. If it is open it will be closed and the other way round.
Definition at line 564 of file DlgParameterImp.cpp.
Referenced by ParameterGroup().
The documentation for this class was generated from the following files:
DlgParameterImp.h
DlgParameterImp.cpp