FreeCAD: VisualPathSegmentVisitor Class Reference
VisualPathSegmentVisitor Class Reference
Public Member Functions
VisualPathSegmentVisitor (const Toolpath &tp, SoCoordinate3 *pcLineCoords_, SoCoordinate3 *pcMarkerCoords_, std::vector< int > &command2Edge_, std::deque< int > &edge2Command_, std::deque< int > &edgeIndices_, std::vector< int > &colorindex_, std::deque< Base::Vector3d > &points_, std::deque< Base::Vector3d > &markers_)
void setup (const Base::Vector3d &last) override
void g0 (int id, const Base::Vector3d &last, const Base::Vector3d &next, const std::deque< Base::Vector3d > &pts) override
void g1 (int id, const Base::Vector3d &last, const Base::Vector3d &next, const std::deque< Base::Vector3d > &pts) override
void g23 (int id, const Base::Vector3d &last, const Base::Vector3d &next, const std::deque< Base::Vector3d > &pts, const Base::Vector3d &center) override
void g8x (int id, const Base::Vector3d &last, const Base::Vector3d &next, const std::deque< Base::Vector3d > &pts, const std::deque< Base::Vector3d > &p, const std::deque< Base::Vector3d > &q) override
void g38 (int id, const Base::Vector3d &last, const Base::Vector3d &next) override
Public Member Functions inherited from Path::PathSegmentVisitor
virtual ~PathSegmentVisitor ()
Detailed Description
Definition at line 532 of file ViewProviderPath.cpp.
Constructor & Destructor Documentation
VisualPathSegmentVisitor()
VisualPathSegmentVisitor::VisualPathSegmentVisitor (const Toolpath & tp, SoCoordinate3 * pcLineCoords_, SoCoordinate3 * pcMarkerCoords_, std::vector< int > & command2Edge_, std::deque< int > & edge2Command_, std::deque< int > & edgeIndices_, std::vector< int > & colorindex_, std::deque< Base::Vector3d > & points_, std::deque< Base::Vector3d > & markers_) inline
Definition at line 535 of file ViewProviderPath.cpp.
References Path::Toolpath::getSize().
Member Function Documentation
g0()
void VisualPathSegmentVisitor::g0 (int id, const Base::Vector3d & last, const Base::Vector3d & next, const std::deque< Base::Vector3d > & pts) inline override virtual
Reimplemented from Path::PathSegmentVisitor.
Definition at line 571 of file ViewProviderPath.cpp.
g1()
void VisualPathSegmentVisitor::g1 (int id, const Base::Vector3d & last, const Base::Vector3d & next, const std::deque< Base::Vector3d > & pts) inline override virtual
Reimplemented from Path::PathSegmentVisitor.
Definition at line 580 of file ViewProviderPath.cpp.
g23()
void VisualPathSegmentVisitor::g23 (int id, const Base::Vector3d & last, const Base::Vector3d & next, const std::deque< Base::Vector3d > & pts, const Base::Vector3d & center) inline override virtual
Reimplemented from Path::PathSegmentVisitor.
Definition at line 589 of file ViewProviderPath.cpp.
References exportCSG::center().
g38()
void VisualPathSegmentVisitor::g38 (int id, const Base::Vector3d & last, const Base::Vector3d & next) inline override virtual
Reimplemented from Path::PathSegmentVisitor.
Definition at line 634 of file ViewProviderPath.cpp.
References Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
g8x()
void VisualPathSegmentVisitor::g8x (int id, const Base::Vector3d & last, const Base::Vector3d & next, const std::deque< Base::Vector3d > & pts, const std::deque< Base::Vector3d > & p, const std::deque< Base::Vector3d > & q) inline override virtual
Reimplemented from Path::PathSegmentVisitor.
Definition at line 600 of file ViewProviderPath.cpp.
References buildPsets::p.
setup()
void VisualPathSegmentVisitor::setup (const Base::Vector3d & last) inline override virtual
Reimplemented from Path::PathSegmentVisitor.
Definition at line 565 of file ViewProviderPath.cpp.
Referenced by Path.Dressup.Tags.ObjectTagDressup::doExecute(), Path.Dressup.Gui.Dogbone.ObjectDressup::execute(), Path.Dressup.Tags.ObjectTagDressup::generateTags(), Path.Dressup.Tags.ObjectTagDressup::pointAtBottom(), Path.Dressup.Tags.ObjectTagDressup::pointIsOnPath(), Path.Dressup.Tags.ObjectTagDressup::setXyEnabled(), and Path.Dressup.Tags.ObjectTagDressup::supportsTagGeneration().
The documentation for this class was generated from the following file:
ViewProviderPath.cpp