FreeCAD: Gui::Dialog::DlgInspector Class Reference
Gui::Dialog::DlgInspector Class Reference
Dialog window to display scenegraph model as a tree.
#include <SceneInspector.h>
Public Member Functions
DlgInspector (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgInspector () override
void setDocument (Gui::Document *doc)
Protected Member Functions
void changeEvent (QEvent *e) override
void setNode (SoNode *node)
void setNodeNames (Gui::Document *)
Detailed Description
Dialog window to display scenegraph model as a tree.
Definition at line 69 of file SceneInspector.h.
Constructor & Destructor Documentation
DlgInspector()
DlgInspector::DlgInspector (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
Definition at line 245 of file SceneInspector.cpp.
References draftgeoutils.intersections::connect().
~DlgInspector()
DlgInspector::~DlgInspector () override
Definition at line 261 of file SceneInspector.cpp.
Member Function Documentation
changeEvent()
void DlgInspector::changeEvent (QEvent * e) override protected
Definition at line 320 of file SceneInspector.cpp.
References SCL.SimpleDataTypes::e.
setDocument()
void DlgInspector::setDocument (Gui::Document * doc)
Definition at line 267 of file SceneInspector.cpp.
References toolbit-attributes::doc, setNode(), setNodeNames(), and OfflineRenderingUtils::viewer().
setNode()
void DlgInspector::setNode (SoNode * node) protected
Definition at line 279 of file SceneInspector.cpp.
References DATA, INVENTOR_TREE, MEMORY_ADDRESS, NAME, and Gui::Dialog::SceneModel::setNode().
Referenced by setDocument().
setNodeNames()
void DlgInspector::setNodeNames (Gui::Document * doc) protected
Definition at line 294 of file SceneInspector.cpp.
References toolbit-attributes::doc, Base::Persistence::getClassTypeId(), App::PropertyString::getValue(), App::DocumentObject::Label, NavigationIndicatorGui::label, modes, and Gui::Dialog::SceneModel::setNodeNames().
Referenced by setDocument().
The documentation for this class was generated from the following files:
SceneInspector.h
SceneInspector.cpp