FreeCAD: FemGui::PointMarker Class Reference
FemGui::PointMarker Class Reference
#include <TaskPostBoxes.h>
Public Member Functions
PointMarker (Gui::View3DInventorViewer *view, App::DocumentObject *obj)
~PointMarker () override
void addPoint (const SbVec3f &)
void clearPoints () const
int countPoints () const
SbVec3f getPoint (int idx) const
void setPoint (int idx, const SbVec3f &pt) const
Gui::View3DInventorViewer * getView () const
App::DocumentObject * getObject () const
template<class T >
T * getObject () const
Public Attributes
QMetaObject::Connection connSelectPoint
Protected Member Functions
std::string ObjectInvisible ()
Detailed Description
Definition at line 66 of file TaskPostBoxes.h.
Constructor & Destructor Documentation
PointMarker()
PointMarker::PointMarker (Gui::View3DInventorViewer * view, App::DocumentObject * obj)
Definition at line 75 of file TaskPostBoxes.cpp.
References Gui::View3DInventorViewer::addViewProvider().
~PointMarker()
PointMarker::~PointMarker () override
Definition at line 84 of file TaskPostBoxes.cpp.
References Gui::View3DInventorViewer::removeViewProvider().
Member Function Documentation
addPoint()
void PointMarker::addPoint (const SbVec3f & pt)
Definition at line 90 of file TaskPostBoxes.cpp.
References countPoints(), FemGui::ViewProviderPointMarker::pCoords, and FemGui::ViewProviderPointMarker::pMarker.
Referenced by FemGui::TaskPostDataAlongLine::pointCallback().
clearPoints()
void PointMarker::clearPoints () const
Definition at line 97 of file TaskPostBoxes.cpp.
References FemGui::ViewProviderPointMarker::pCoords, and FemGui::ViewProviderPointMarker::pMarker.
countPoints()
int PointMarker::countPoints () const
Definition at line 103 of file TaskPostBoxes.cpp.
References FemGui::ViewProviderPointMarker::pCoords.
Referenced by addPoint(), and FemGui::TaskPostDataAlongLine::pointCallback().
getObject() [1/2]
App::DocumentObject * PointMarker::getObject () const
Definition at line 123 of file TaskPostBoxes.cpp.
Referenced by FemGui::DataAlongLineMarker::customEvent(), and getObject().
getObject() [2/2]
template<class T > T* FemGui::PointMarker::getObject () const inline
Definition at line 82 of file TaskPostBoxes.h.
References getObject().
getPoint()
SbVec3f PointMarker::getPoint (int idx) const
Definition at line 108 of file TaskPostBoxes.cpp.
References FemGui::ViewProviderPointMarker::pCoords.
Referenced by FemGui::DataAlongLineMarker::customEvent().
getView()
Gui::View3DInventorViewer * PointMarker::getView () const
Definition at line 118 of file TaskPostBoxes.cpp.
Referenced by FemGui::TaskPostDataAlongLine::~TaskPostDataAlongLine().
ObjectInvisible()
std::string PointMarker::ObjectInvisible () protected
Definition at line 128 of file TaskPostBoxes.cpp.
Referenced by FemGui::DataAlongLineMarker::customEvent().
setPoint()
void PointMarker::setPoint (int idx, const SbVec3f & pt) const
Definition at line 113 of file TaskPostBoxes.cpp.
References FemGui::ViewProviderPointMarker::pCoords.
Member Data Documentation
connSelectPoint
QMetaObject::Connection FemGui::PointMarker::connSelectPoint
Definition at line 86 of file TaskPostBoxes.h.
Referenced by FemGui::TaskPostDataAlongLine::pointCallback().
The documentation for this class was generated from the following files:
TaskPostBoxes.h
TaskPostBoxes.cpp