FreeCAD: App::StringExpression Class Reference
App::StringExpression Class Reference
#include <ExpressionParser.h>
Public Member Functions
StringExpression (const App::DocumentObject *_owner=nullptr, const std::string &_text=std::string())
~StringExpression () override
Expression * simplify () const override
virtual std::string getText () const
Public Member Functions inherited from App::Expression
Expression (const App::DocumentObject *_owner)
~Expression () override
virtual bool isTouched () const
Expression * eval () const
std::string toString (bool persistent=false, bool checkPriority=false, int indent=0) const
void toString (std::ostream &os, bool persistent=false, bool checkPriority=false, int indent=0) const
Expression * copy () const
virtual int priority () const
void getIdentifiers (std::map< App::ObjectIdentifier, bool > &) const
std::map< App::ObjectIdentifier, bool > getIdentifiers () const
void getDeps (ExpressionDeps &deps, int option=DepNormal) const
ExpressionDeps getDeps (int option=DepNormal) const
std::map< App::DocumentObject *, bool > getDepObjects (std::vector< std::string > *labels=nullptr) const
void getDepObjects (std::map< App::DocumentObject *, bool > &, std::vector< std::string > *labels=nullptr) const
ExpressionPtr importSubNames (const std::map< std::string, std::string > &nameMap) const
ExpressionPtr updateLabelReference (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const
ExpressionPtr replaceObject (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const
bool adjustLinks (const std::set< App::DocumentObject * > &inList)
void visit (ExpressionVisitor &v)
App::DocumentObject * getOwner () const
virtual void addComponent (Component *component)
bool hasComponent () const
boost::any getValueAsAny () const
Py::Object getPyValue () const
bool isSame (const Expression &other, bool checkComment=true) const
Component (const std::string &n)
Component (Expression *e1, Expression *e2, Expression *e3, bool isRange=false)
Component (const ObjectIdentifier::Component &comp)
Component (const Component &other)
~Component ()
Component & operator= (const Component &)=delete
void visit (ExpressionVisitor &v)
bool isTouched () const
void toString (std::ostream &ss, bool persistent) const
Component * copy () const
Component * eval () const
Py::Object get (const Expression *owner, const Py::Object &pyobj) const
void set (const Expression *owner, Py::Object &pyobj, const Py::Object &value) const
void del (const Expression *owner, Py::Object &pyobj) const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
Expression * _copy () const override
void _toString (std::ostream &ss, bool persistent, int indent) const override
Py::Object _getPyValue () const override
bool _isIndexable () const override
Protected Member Functions inherited from App::Expression
virtual void _getIdentifiers (std::map< App::ObjectIdentifier, bool > &) const
virtual bool _adjustLinks (const std::set< App::DocumentObject * > &, ExpressionVisitor &)
virtual bool _updateElementReference (App::DocumentObject *, bool, ExpressionVisitor &)
virtual bool _relabeledDocument (const std::string &, const std::string &, ExpressionVisitor &)
virtual void _importSubNames (const ObjectIdentifier::SubNameMap &)
virtual void _updateLabelReference (App::DocumentObject *, const std::string &, const char *)
virtual bool _renameObjectIdentifier (const std::map< ObjectIdentifier, ObjectIdentifier > &, const ObjectIdentifier &, ExpressionVisitor &)
virtual void _collectReplacement (std::map< ObjectIdentifier, ObjectIdentifier > &, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const
virtual void _moveCells (const CellAddress &, int, int, ExpressionVisitor &)
virtual void _offsetCells (int, int, ExpressionVisitor &)
virtual void _visit (ExpressionVisitor &)
Additional Inherited Members
Public Types inherited from App::Expression
enum DepOption { DepNormal, DepHidden, DepAll }
using ComponentList = std::vector< Component * >
Static Public Member Functions inherited from App::Expression
static Expression * parse (const App::DocumentObject *owner, const std::string &buffer)
static Component * createComponent (const std::string &n)
static Component * createComponent (Expression *e1, Expression *e2=nullptr, Expression *e3=nullptr, bool isRange=false)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::Expression
std::string comment
ObjectIdentifier::Component comp
Expression * e1
Expression * e2
Expression * e3
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Expression
App::DocumentObject * owner
ComponentList components
Detailed Description
Class implementing a string. Used to signal either a genuine string or a failed evaluation of an expression.
Definition at line 555 of file ExpressionParser.h.
Constructor & Destructor Documentation
StringExpression()
StringExpression::StringExpression (const App::DocumentObject * _owner = nullptr, const std::string & _text = std::string()) explicit
Definition at line 3138 of file Expression.cpp.
Referenced by _copy().
~StringExpression()
StringExpression::~StringExpression () override
Definition at line 3144 of file Expression.cpp.
Member Function Documentation
_copy()
Expression * StringExpression::_copy () const override protected virtual
Return a copy of the expression.
Implements App::Expression.
Definition at line 3169 of file Expression.cpp.
References App::Expression::owner, and StringExpression().
_getPyValue()
Py::Object StringExpression::_getPyValue () const override protected virtual
Implements App::Expression.
Definition at line 3174 of file Expression.cpp.
References src.Mod.Test.testmakeWireString::String.
_isIndexable()
bool App::StringExpression::_isIndexable () const inline override protected virtual
Reimplemented from App::Expression.
Definition at line 575 of file ExpressionParser.h.
_toString()
void StringExpression::_toString (std::ostream & ss, bool persistent, int indent) const override protected virtual
Implements App::Expression.
Definition at line 3160 of file Expression.cpp.
References App::quote().
getText()
virtual std::string App::StringExpression::getText () const inline virtual
Definition at line 566 of file ExpressionParser.h.
simplify()
Expression * StringExpression::simplify () const override virtual
Simplify the expression. For strings, this is a simple copy of the object.
Implements App::Expression.
Definition at line 3155 of file Expression.cpp.
References App::Expression::copy().
The documentation for this class was generated from the following files:
ExpressionParser.h
Expression.cpp