FreeCAD: MillSim::Shader Class Reference
MillSim::Shader Class Reference
#include <Shader.h>
Public Member Functions
Shader ()
~Shader ()
void UpdateModelMat (mat4x4 transformMat, mat4x4 normalMat)
void UpdateProjectionMat (mat4x4 mat)
void UpdateViewMat (mat4x4 mat)
void UpdateEnvColor (vec3 lightPos, vec3 lightColor, vec3 ambient, float linearity)
void UpdateScreenDimension (int width, int height)
void UpdateObjColor (vec3 objColor)
void UpdateObjColorAlpha (vec4 objColor)
void UpdateNormalState (bool isInverted)
void UpdateSsaoActive (bool isInverted)
void UpdateTextureSlot (int slot)
void UpdateColorTexSlot (int albedoSlot)
void UpdatePositionTexSlot (int positionSlot)
void UpdateNormalTexSlot (int normalSlot)
void UpdateRandomTexSlot (int noiseSlot)
void UpdateSsaoTexSlot (int ssaoSlot)
void UpdateKernelVals (int nVals, float *vals)
void UpdateCurSegment (int curSeg)
unsigned int CompileShader (const char *name, const char *vertShader, const char *fragShader)
void Activate ()
void Destroy ()
bool IsValid ()
Public Attributes
unsigned int shaderId = 0
Protected Attributes
int mModelPos = -1
int mNormalRotPos = -1
int mProjectionPos = -1
int mViewPos = -1
int mLightPosPos = -1
int mLightColorPos = -1
int mLightLinearPos = -1
int mLightAmbientPos = -1
int mObjectColorPos = -1
int mObjectColorAlphaPos = -1
int mTexSlotPos = -1
int mInvertedNormalsPos = -1
int mSsaoActivePos = -1
int mAlbedoPos = -1
int mPositionPos = -1
int mNormalPos = -1
int mSsaoPos = -1
int mRandTexPos = -1
int mSamplesPos = -1
int mCurSegmentPos = -1
int mScreenWidthPos = -1
int mScreenHeightPos = -1
const char * vertShader = nullptr
const char * fragShader = nullptr
Detailed Description
Definition at line 51 of file Shader.h.
Constructor & Destructor Documentation
Shader()
MillSim::Shader::Shader () inline
Definition at line 74 of file Shader.h.
~Shader()
MillSim::Shader::~Shader ()
Definition at line 69 of file Shader.cpp.
References glUniform3fv, and mLightPosPos.
Member Function Documentation
Activate()
void MillSim::Shader::Activate ()
Definition at line 293 of file Shader.cpp.
Referenced by MillSim::SimDisplay::PrepareDisplay(), MillSim::GuiDisplay::Render(), and MillSim::SimDisplay::RenderLightObject().
CompileShader()
unsigned int MillSim::Shader::CompileShader (const char * name, const char * vertShader, const char * fragShader)
Definition at line 232 of file Shader.cpp.
References Destroy().
Referenced by MillSim::GuiDisplay::InitGui().
Destroy()
void MillSim::Shader::Destroy ()
Definition at line 301 of file Shader.cpp.
Referenced by CompileShader(), and MillSim::GuiDisplay::ResetGui().
IsValid()
bool MillSim::Shader::IsValid () inline
Definition at line 100 of file Shader.h.
UpdateColorTexSlot()
void MillSim::Shader::UpdateColorTexSlot (int albedoSlot)
Definition at line 159 of file Shader.cpp.
References glUniform1i, and mSsaoPos.
UpdateCurSegment()
void MillSim::Shader::UpdateCurSegment (int curSeg)
Definition at line 199 of file Shader.cpp.
UpdateEnvColor()
void MillSim::Shader::UpdateEnvColor (vec3 lightPos, vec3 lightColor, vec3 ambient, float linearity)
Definition at line 98 of file Shader.cpp.
References glUniform3fv, and mObjectColorPos.
UpdateKernelVals()
void MillSim::Shader::UpdateKernelVals (int nVals, float * vals)
Definition at line 194 of file Shader.cpp.
UpdateModelMat()
void MillSim::Shader::UpdateModelMat (mat4x4 transformMat, mat4x4 normalMat)
Definition at line 74 of file Shader.cpp.
Referenced by MillSim::Shape::Render().
UpdateNormalState()
void MillSim::Shader::UpdateNormalState (bool isInverted)
Definition at line 138 of file Shader.cpp.
References glUniform1i, and mPositionPos.
Referenced by MillSim::SimDisplay::PrepareDisplay().
UpdateNormalTexSlot()
void MillSim::Shader::UpdateNormalTexSlot (int normalSlot)
Definition at line 173 of file Shader.cpp.
References glUniform1i, and mCurSegmentPos.
UpdateObjColor()
void MillSim::Shader::UpdateObjColor (vec3 objColor)
Definition at line 124 of file Shader.cpp.
References glUniform1i, and mTexSlotPos.
Referenced by MillSim::SimDisplay::PrepareDisplay().
UpdateObjColorAlpha()
void MillSim::Shader::UpdateObjColorAlpha (vec4 objColor)
Definition at line 131 of file Shader.cpp.
References glUniform1i, and mAlbedoPos.
UpdatePositionTexSlot()
void MillSim::Shader::UpdatePositionTexSlot (int positionSlot)
Definition at line 166 of file Shader.cpp.
References glUniform3fv, and mSamplesPos.
UpdateProjectionMat()
void MillSim::Shader::UpdateProjectionMat (mat4x4 mat)
Definition at line 84 of file Shader.cpp.
UpdateRandomTexSlot()
void MillSim::Shader::UpdateRandomTexSlot (int noiseSlot)
Definition at line 180 of file Shader.cpp.
References glGetShaderiv, and KDL::log().
UpdateScreenDimension()
void MillSim::Shader::UpdateScreenDimension (int width, int height)
Definition at line 114 of file Shader.cpp.
UpdateSsaoActive()
void MillSim::Shader::UpdateSsaoActive (bool isInverted)
Definition at line 145 of file Shader.cpp.
References glUniform1i, and mNormalPos.
UpdateSsaoTexSlot()
void MillSim::Shader::UpdateSsaoTexSlot (int ssaoSlot)
Definition at line 187 of file Shader.cpp.
UpdateTextureSlot()
void MillSim::Shader::UpdateTextureSlot (int slot)
Definition at line 152 of file Shader.cpp.
References glUniform1i, and mRandTexPos.
Referenced by MillSim::GuiDisplay::InitGui(), and MillSim::GuiDisplay::Render().
UpdateViewMat()
void MillSim::Shader::UpdateViewMat (mat4x4 mat)
Definition at line 91 of file Shader.cpp.
References glUniform1f, and mScreenHeightPos.
Referenced by MillSim::SimDisplay::PrepareDisplay().
Member Data Documentation
fragShader
const char* MillSim::Shader::fragShader = nullptr protected
Definition at line 131 of file Shader.h.
mAlbedoPos
int MillSim::Shader::mAlbedoPos = -1 protected
Definition at line 120 of file Shader.h.
Referenced by UpdateObjColorAlpha().
mCurSegmentPos
int MillSim::Shader::mCurSegmentPos = -1 protected
Definition at line 126 of file Shader.h.
Referenced by UpdateNormalTexSlot().
mInvertedNormalsPos
int MillSim::Shader::mInvertedNormalsPos = -1 protected
Definition at line 118 of file Shader.h.
mLightAmbientPos
int MillSim::Shader::mLightAmbientPos = -1 protected
Definition at line 114 of file Shader.h.
mLightColorPos
int MillSim::Shader::mLightColorPos = -1 protected
Definition at line 112 of file Shader.h.
mLightLinearPos
int MillSim::Shader::mLightLinearPos = -1 protected
Definition at line 113 of file Shader.h.
mLightPosPos
int MillSim::Shader::mLightPosPos = -1 protected
Definition at line 111 of file Shader.h.
Referenced by ~Shader().
mModelPos
int MillSim::Shader::mModelPos = -1 protected
Definition at line 107 of file Shader.h.
mNormalPos
int MillSim::Shader::mNormalPos = -1 protected
Definition at line 122 of file Shader.h.
Referenced by UpdateSsaoActive().
mNormalRotPos
int MillSim::Shader::mNormalRotPos = -1 protected
Definition at line 108 of file Shader.h.
mObjectColorAlphaPos
int MillSim::Shader::mObjectColorAlphaPos = -1 protected
Definition at line 116 of file Shader.h.
mObjectColorPos
int MillSim::Shader::mObjectColorPos = -1 protected
Definition at line 115 of file Shader.h.
Referenced by UpdateEnvColor().
mPositionPos
int MillSim::Shader::mPositionPos = -1 protected
Definition at line 121 of file Shader.h.
Referenced by UpdateNormalState().
mProjectionPos
int MillSim::Shader::mProjectionPos = -1 protected
Definition at line 109 of file Shader.h.
mRandTexPos
int MillSim::Shader::mRandTexPos = -1 protected
Definition at line 124 of file Shader.h.
Referenced by UpdateTextureSlot().
mSamplesPos
int MillSim::Shader::mSamplesPos = -1 protected
Definition at line 125 of file Shader.h.
Referenced by UpdatePositionTexSlot().
mScreenHeightPos
int MillSim::Shader::mScreenHeightPos = -1 protected
Definition at line 128 of file Shader.h.
Referenced by UpdateViewMat().
mScreenWidthPos
int MillSim::Shader::mScreenWidthPos = -1 protected
Definition at line 127 of file Shader.h.
mSsaoActivePos
int MillSim::Shader::mSsaoActivePos = -1 protected
Definition at line 119 of file Shader.h.
mSsaoPos
int MillSim::Shader::mSsaoPos = -1 protected
Definition at line 123 of file Shader.h.
Referenced by UpdateColorTexSlot().
mTexSlotPos
int MillSim::Shader::mTexSlotPos = -1 protected
Definition at line 117 of file Shader.h.
Referenced by UpdateObjColor().
mViewPos
int MillSim::Shader::mViewPos = -1 protected
Definition at line 110 of file Shader.h.
shaderId
unsigned int MillSim::Shader::shaderId = 0
Definition at line 79 of file Shader.h.
vertShader
const char* MillSim::Shader::vertShader = nullptr protected
Definition at line 130 of file Shader.h.
The documentation for this class was generated from the following files:
Shader.h
Shader.cpp