FreeCAD: TechDraw::DrawViewSection Class Reference
TechDraw::DrawViewSection Class Reference
#include <DrawViewSection.h>
Public Slots
virtual void onSectionCutFinished (void)
Public Slots inherited from TechDraw::DrawViewPart
void onHlrFinished (void)
continue processing after hlr thread completes
void onFacesFinished (void)
Public Member Functions
DrawViewSection ()
~DrawViewSection () override
bool isReallyInBox (const Base::Vector3d v, const Base::BoundBox3d bb) const
bool isReallyInBox (const gp_Pnt p, const Bnd_Box &bb) const
App::DocumentObjectExecReturn * execute () override
recalculate the Feature
void onChanged (const App::Property *prop) override
get called by the container when a property was changed
const char * getViewProviderName () const override
returns the type name of the ViewProvider
void unsetupObject () override
short mustExecute () const override
void sectionExec (TopoDS_Shape &s)
virtual void makeSectionCut (const TopoDS_Shape &baseShape)
void postHlrTasks (void) override
run any tasks that need to been done after geometry is available
virtual void postSectionCutTasks ()
void waitingForCut (bool s)
bool waitingForCut (void) const
bool waitingForResult () const override
virtual TopoDS_Shape makeCuttingTool (double shapeSize)
virtual TopoDS_Shape getShapeToCut ()
virtual bool isBaseValid () const
virtual TopoDS_Shape prepareShape (const TopoDS_Shape &rawShape, double shapeSize)
virtual TopoDS_Shape getShapeToPrepare () const
void setCSFromBase (const std::string sectionName)
void setCSFromBase (Base::Vector3d localUnit)
void setCSFromLocalUnit (const Base::Vector3d localUnit)
virtual gp_Ax2 getCSFromBase (const std::string sectionName) const
gp_Ax2 getSectionCS () const
Base::Vector3d getXDirection () const override
TechDraw::DrawViewPart * getBaseDVP () const
std::vector< TechDraw::FacePtr > getTDFaceGeometry ()
TopoDS_Face getSectionTopoDSFace (int i)
virtual TopoDS_Compound alignSectionFaces (TopoDS_Shape faceIntersections)
TopoDS_Compound mapToPage (TopoDS_Shape &shapeToAlign)
virtual std::vector< TechDraw::FacePtr > makeTDSectionFaces (TopoDS_Compound topoDSFaces)
virtual TopoDS_Shape getShapeToIntersect ()
void makeLineSets (void)
std::vector< LineSet > getDrawableLines (int i=0)
std::vector< PATLineSpec > getDecodedSpecsFromFile (std::string fileSpec, std::string myPattern)
TopoDS_Shape getCutShape () const
TopoDS_Shape getCutShapeRaw () const
TopoDS_Shape getShapeForDetail () const override
virtual std::pair< Base::Vector3d, Base::Vector3d > sectionLineEnds ()
Base::Vector3d getSectionDirectionOnBaseView ()
virtual ChangePointVector getChangePointsFromSectionLine ()
bool showSectionEdges (void)
TopoDS_Shape makeFaceFromWires (std::vector< TopoDS_Wire > &inWires)
Base::Vector3d getCutCentroid () const
return the center of the shape resulting from the cut operation
Public Member Functions inherited from TechDraw::DrawViewPart
DrawViewPart ()
~DrawViewPart () override
PyObject * getPyObject () override
std::vector< TechDraw::DrawHatch * > getHatches () const
std::vector< TechDraw::DrawGeomHatch * > getGeomHatches () const
std::vector< TechDraw::DrawViewDimension * > getDimensions () const
std::vector< TechDraw::DrawViewBalloon * > getBalloons () const
virtual std::vector< DrawViewSection * > getSectionRefs () const
virtual std::vector< DrawViewDetail * > getDetailRefs () const
const std::vector< TechDraw::VertexPtr > getVertexGeometry () const
const BaseGeomPtrVector getEdgeGeometry () const
const BaseGeomPtrVector getVisibleFaceEdges () const
const std::vector< TechDraw::FacePtr > getFaceGeometry () const
bool hasGeometry () const
TechDraw::GeometryObjectPtr getGeometryObject () const
TechDraw::VertexPtr getVertex (std::string vertexName) const
TechDraw vertex names run from 0 to n-1.
TechDraw::BaseGeomPtr getEdge (std::string edgeName) const
TechDraw::FacePtr getFace (std::string faceName) const
TechDraw::BaseGeomPtr getGeomByIndex (int idx) const
returns existing BaseGeom of 2D Edge(idx)
TechDraw::VertexPtr getProjVertexByIndex (int idx) const
returns existing geometry of 2D Vertex(idx)
TechDraw::VertexPtr getProjVertexByCosTag (std::string cosTag)
std::vector< TechDraw::BaseGeomPtr > getFaceEdgesByIndex (int idx) const
returns existing geometry of 2D Face(idx)
virtual std::vector< TopoDS_Wire > getWireForFace (int idx) const
TopoDS_Shape getEdgeCompound () const
virtual Base::BoundBox3d getBoundingBox () const
double getBoxX () const
double getBoxY () const
QRectF getRect () const override
double getSizeAlongVector (Base::Vector3d alignmentVector)
virtual Base::Vector3d projectPoint (const Base::Vector3d &pt, bool invert=true) const
virtual BaseGeomPtr projectEdge (const TopoDS_Edge &e) const
virtual gp_Ax2 getViewAxis (const Base::Vector3d &pt, const Base::Vector3d &direction, const bool flip=true) const
virtual gp_Ax2 getProjectionCS (Base::Vector3d pt=Base::Vector3d(0.0, 0.0, 0.0)) const
virtual gp_Ax2 getRotatedCS (Base::Vector3d basePoint=Base::Vector3d(0.0, 0.0, 0.0)) const
virtual Base::Vector3d getOriginalCentroid () const
virtual Base::Vector3d getCurrentCentroid () const
virtual Base::Vector3d getLegacyX (const Base::Vector3d &pt, const Base::Vector3d &axis, const bool flip=true) const
void rotate (const std::string &rotationdirection)
void spin (const std::string &spindirection)
void spin (double val)
std::pair< Base::Vector3d, Base::Vector3d > getDirsFromFront (std::string viewType)
Base::Vector3d dir2vec (gp_Dir d)
gp_Ax2 localVectorToCS (const Base::Vector3d localUnit) const
Base::Vector3d localVectorToDirection (const Base::Vector3d localUnit) const
bool handleFaces ()
bool newFaceFinder ()
bool isUnsetting ()
virtual TopoDS_Shape getSourceShape (bool fuse=false) const
std::vector< App::DocumentObject * > getAllSources () const
combine the regular links and xlinks into a single list
void dumpVerts (const std::string text)
void dumpCosVerts (const std::string text)
void dumpCosEdges (const std::string text)
std::string addReferenceVertex (Base::Vector3d v)
void addReferencesToGeom ()
void removeReferenceVertex (std::string tag)
void updateReferenceVert (std::string tag, Base::Vector3d loc2d)
void removeAllReferencesFromGeom ()
remove reference vertexes from the view geometry
void resetReferenceVerts ()
virtual void postFaceExtractionTasks (void)
bool waitingForFaces () const
void waitingForFaces (bool s)
bool waitingForHlr () const
void waitingForHlr (bool s)
void progressValueChanged (int v)
Public Member Functions inherited from TechDraw::DrawView
DrawView ()
Constructor.
~DrawView () override
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, App::Property *prop) override
bool isInClip ()
DrawViewClip * getClipGroup ()
DrawViewCollection * getCollection () const
virtual DrawPage * findParentPage () const
virtual std::vector< DrawPage * > findAllParentPages () const
virtual DrawView * claimParent () const
virtual int countParentPages () const
DrawView::countParentPages Fixes a crash in TechDraw when user creates duplicate page without dependencies In fixOrphans() we check how many parent pages an object has before deleting in case it is also a child of another duplicate page.
QRectF getRectAligned () const
virtual double autoScale () const
virtual double autoScale (double w, double h) const
virtual bool checkFit () const
virtual bool checkFit (DrawPage *) const
check if View is too big for page
virtual void setPosition (double x, double y, bool force=false)
virtual Base::Vector3d getPosition () const
virtual bool keepUpdated (void)
void requestPaint (void)
void showProgressMessage (std::string featureName, std::string text)
virtual double getScale (void) const
virtual int getScaleType () const
void checkScale (void)
virtual void handleXYLock (void)
virtual bool isLocked (void) const
virtual bool showLock (void) const
std::vector< TechDraw::DrawLeaderLine * > getLeaders (void) const
void setScaleAttribute ()
void overrideKeepUpdated (bool s)
bool overrideKeepUpdated (void)
void translateLabel (std::string context, std::string baseName, std::string uniqueName)
virtual App::PropertyLink * getOwnerProperty ()
Public Member Functions inherited from App::DocumentObject
virtual const char * getViewProviderNameOverride () const
DocumentObject ()
Constructor.
~DocumentObject () override
const char * getDagKey () const
returns a value that uniquely identifies this DocumentObject.
const char * getNameInDocument () const
returns the name which is set in the document for this object (not the name property!)
long getID () const
Return the object ID that is unique within its owner document.
std::string getExportName (bool forced=false) const
returns the name that is safe to be exported to other document
std::string getFullName () const override
Return the object full name of the form DocName::ObjName.
std::string getFullLabel () const
Return the object full label in the form DocName::ObjName.
bool isAttachedToDocument () const override
const char * detachFromDocument () override
App::Document * getDocument () const
gets the document in which this Object is handled
void touch (bool noRecompute=false)
set this document object touched (cause recomputation on dependent features)
bool isTouched () const
test if this document object is touched
void enforceRecompute ()
Enforce this document object to be recomputed.
bool mustRecompute () const
Test if this document object must be recomputed.
void purgeTouched ()
reset this document object touched
bool isError () const
set this feature to error
bool isValid () const
void purgeError ()
remove the error from the object
bool isRecomputing () const
returns true if this objects is currently recomputing
bool isRestoring () const
returns true if this objects is currently restoring from file
bool isRemoving () const
returns true if this objects is currently removed from the document
void freeze ()
set this document object freezed (prevent recomputation)
void unfreeze (bool noRecompute=false)
set this document object unfreezed (and touch it)
bool isFreezed () const
returns true if this objects is currently freezed
unsigned long getStatus () const
return the status bits
bool testStatus (ObjectStatus pos) const
void setStatus (ObjectStatus pos, bool on)
int isExporting () const
virtual int setElementVisible (const char *element, bool visible)
virtual int isElementVisible (const char *element) const
virtual bool hasChildElement () const
return true to activate tree view group object handling and element visibility
const std::vector< App::DocumentObject * > & getOutList () const
returns a list of objects this object is pointing to by Links
std::vector< App::DocumentObject * > getOutList (int option) const
void getOutList (int option, std::vector< App::DocumentObject * > &res) const
std::vector< App::DocumentObject * > getOutListOfProperty (App::Property *) const
returns a list of objects linked by the property
std::vector< App::DocumentObject * > getOutListRecursive () const
returns a list of objects this object is pointing to by Links and all further descended
void clearOutListCache () const
clear internal out list cache
std::vector< std::list< App::DocumentObject * > > getPathsByOutList (App::DocumentObject *to) const
get all possible paths from this to another object following the OutList
const std::vector< App::DocumentObject * > & getInList () const
std::vector< App::DocumentObject * > getInListRecursive () const
get all objects link directly or indirectly to this object
void getInListEx (std::set< App::DocumentObject * > &inSet, bool recursive, std::vector< App::DocumentObject * > *inList=nullptr) const
std::set< App::DocumentObject * > getInListEx (bool recursive) const
DocumentObjectGroup * getGroup () const
get group if object is part of a group, otherwise 0 is returned
bool isInInListRecursive (DocumentObject *objToTest) const
test if this object is in the InList and recursive further down
bool isInInList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the InList
bool isInOutListRecursive (DocumentObject *objToTest) const
test if the given object is in the OutList and recursive further down
bool isInOutList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the OutList
void _removeBackLink (DocumentObject *)
internal, used by PropertyLink to maintain DAG back links
void _addBackLink (DocumentObject *)
internal, used by PropertyLink to maintain DAG back links
bool testIfLinkDAGCompatible (DocumentObject *linkTo) const
testIfLinkIsDAG tests a link that is about to be created for circular references.
bool testIfLinkDAGCompatible (const std::vector< DocumentObject * > &linksTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSubList &linksTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSub &linkTo) const
virtual std::string getElementMapVersion (const App::Property *prop, bool restored=false) const
virtual bool checkElementMapVersion (const App::Property *prop, const char *ver) const
Return true to signal re-generation of geometry element names.
bool recomputeFeature (bool recursive=false)
const char * getStatusString () const
get the status Message
virtual void onLostLinkToObject (DocumentObject *)
virtual DocumentObject * getSubObject (const char *subname, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
std::vector< DocumentObject * > getSubObjectList (const char *subname, std::vector< int > *subsizes=nullptr, bool flatten=false) const
virtual std::vector< std::string > getSubObjects (int reason=0) const
std::vector< std::pair< App::DocumentObject *, std::string > > getParents (int depth=0) const
Obtain top parents and subnames of this object using its InList.
App::DocumentObject * getFirstParent () const
Obtain the first parent group of this object.
virtual DocumentObject * getLinkedObject (bool recurse=true, Base::Matrix4D *mat=nullptr, bool transform=false, int depth=0) const
virtual bool canLinkProperties () const
virtual bool isLink () const
virtual bool isLinkGroup () const
virtual bool allowDuplicateLabel () const
virtual void onBeforeChangeLabel (std::string &newLabel)
void Save (Base::Writer &writer) const override
virtual void setExpression (const ObjectIdentifier &path, std::shared_ptr< App::Expression > expr)
void clearExpression (const ObjectIdentifier &path)
virtual const PropertyExpressionEngine::ExpressionInfo getExpression (const ObjectIdentifier &path) const
virtual void renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &paths)
const std::string & getOldLabel () const
const char * getViewProviderNameStored () const
bool removeDynamicProperty (const char *prop) override
App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
App::DocumentObject * resolve (const char *subname, App::DocumentObject **parent=nullptr, std::string *childName=nullptr, const char **subElement=nullptr, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
App::DocumentObject * resolveRelativeLink (std::string &subname, App::DocumentObject *&link, std::string &linkSub) const
virtual bool adjustRelativeLinks (const std::set< App::DocumentObject * > &inList, std::set< App::DocumentObject * > *visited=nullptr)
virtual int canLoadPartial () const
virtual void onUpdateElementReference (const Property *)
virtual bool redirectSubName (std::ostringstream &ss, DocumentObject *topParent, DocumentObject *child) const
Public Member Functions inherited from App::TransactionalObject
TransactionalObject ()
Constructor.
~TransactionalObject () override
Public Member Functions inherited from App::ExtensionContainer
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
Property * getPropertyByName (const char *name) const override
find a property by its name
template<typename T >
T * getPropertyByName (const char *name) const
find a property by its name, dynamic cased to specified type
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from TechDraw::CosmeticExtension
CosmeticExtension ()
~CosmeticExtension () override
virtual CosmeticVertex * getCosmeticVertexBySelection (const int i) const
retrieve a cosmetic vertex by index (the 5 in Vertex5)
virtual CosmeticVertex * getCosmeticVertexBySelection (const std::string &name) const
virtual CosmeticVertex * getCosmeticVertex (const std::string &tag) const
retrieve a cosmetic vertex by unique id
virtual int add1CVToGV (const std::string &tag)
add a single cosmetic vertex in the property list to the view's vertex geometry list
virtual int getCVIndex (const std::string &tag)
find the position of a cosmetic vertex with the given tag in the parent view's geometry list
virtual std::string addCosmeticVertex (const Base::Vector3d &pos, bool invert=true)
virtual void addCosmeticVertexesToGeom ()
add the cosmetic verts in the property list to view's vertex geometry list
virtual void clearCosmeticVertexes ()
remove all the cosmetic vertices in the property list
virtual void refreshCVGeoms ()
update the parent view's vertex geometry with all the cosmetic vertices in the list property
virtual void removeCosmeticVertex (const std::string &tag)
remove the cosmetic vertex with the given tag from the list property
virtual void removeCosmeticVertex (const std::vector< std::string > &tags)
remove the cosmetic vertices with the given tags from the list property
virtual std::string addCosmeticEdge (Base::Vector3d start, Base::Vector3d end)
virtual std::string addCosmeticEdge (TechDraw::BaseGeomPtr bg)
virtual CosmeticEdge * getCosmeticEdgeBySelection (const std::string &name) const
virtual CosmeticEdge * getCosmeticEdgeBySelection (int i) const
find the cosmetic edge corresponding to the input parameter (the 5 in Edge5)
virtual CosmeticEdge * getCosmeticEdge (const std::string &id) const
retrieve a CE by unique id
virtual void removeCosmeticEdge (const std::string &tag)
remove the cosmetic edge with the given tag from the list property
virtual void removeCosmeticEdge (const std::vector< std::string > &delTags)
remove the cosmetic edges with the given tags from the list property
virtual void clearCosmeticEdges ()
remove all the cosmetic edges for this view
virtual int add1CEToGE (const std::string &tag)
add a single cosmetic edge to the geometry edge list
virtual void addCosmeticEdgesToGeom ()
add the cosmetic edges to geometry edge list
virtual void refreshCEGeoms ()
update Edge geometry with current CE's
virtual void refreshCLGeoms ()
virtual void addCenterLinesToGeom ()
virtual int add1CLToGE (const std::string &tag)
virtual std::string addCenterLine (Base::Vector3d start, Base::Vector3d end)
virtual std::string addCenterLine (TechDraw::CenterLine *cl)
virtual std::string addCenterLine (TechDraw::BaseGeomPtr bg)
virtual CenterLine * getCenterLineBySelection (const std::string &name) const
virtual CenterLine * getCenterLineBySelection (int i) const
virtual CenterLine * getCenterLine (const std::string &tag) const
virtual void removeCenterLine (const std::string &tag)
virtual void removeCenterLine (const std::vector< std::string > &delTags)
virtual void clearCenterLines ()
virtual std::string addGeomFormat (TechDraw::GeomFormat *gf)
virtual GeomFormat * getGeomFormatBySelection (const std::string &name) const
virtual GeomFormat * getGeomFormatBySelection (int i) const
virtual GeomFormat * getGeomFormat (const std::string &id) const
virtual void removeGeomFormat (const std::string &tag)
virtual void clearGeomFormats ()
void deleteCosmeticElements (std::vector< std::string > removables)
remove cosmetic elements for a list of subelement names
TechDraw::DrawViewPart * getOwner ()
get a pointer to the parent view
PyObject * getExtensionPyObject () override
Public Member Functions inherited from App::DocumentObjectExtension
virtual Base::Type getExtensionTypeId (void) const override
DocumentObjectExtension ()
~DocumentObjectExtension () override
App::DocumentObject * getExtendedObject ()
const App::DocumentObject * getExtendedObject () const
virtual short extensionMustExecute ()
virtual App::DocumentObjectExecReturn * extensionExecute ()
virtual void onExtendedSettingDocument ()
get called after setting the document
virtual void onExtendedDocumentRestored ()
get called after a document has been fully restored
virtual void onExtendedSetupObject ()
get called after a brand new object was created
virtual void onExtendedUnsetupObject ()
get called when object is going to be removed from the document
virtual const char * getViewProviderExtensionName () const
virtual bool extensionGetSubObject (DocumentObject *&ret, const char *subname, PyObject **pyObj, Base::Matrix4D *mat, bool transform, int depth) const
virtual bool extensionGetSubObjects (std::vector< std::string > &ret, int reason) const
virtual bool extensionGetLinkedObject (DocumentObject *&ret, bool recursive, Base::Matrix4D *mat, bool transform, int depth) const
virtual int extensionSetElementVisible (const char *, bool)
virtual int extensionIsElementVisible (const char *)
virtual bool extensionHasChildElement () const
Public Member Functions inherited from App::Extension
Extension ()=default
virtual ~Extension ()
virtual void initExtension (App::ExtensionContainer *obj)
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Public Attributes
App::PropertyLink BaseView
App::PropertyVector SectionNormal
App::PropertyVector SectionOrigin
App::PropertyString SectionSymbol
App::PropertyEnumeration SectionDirection
App::PropertyEnumeration CutSurfaceDisplay
App::PropertyFile FileHatchPattern
App::PropertyFile FileGeomPattern
App::PropertyFileIncluded SvgIncluded
App::PropertyFileIncluded PatIncluded
App::PropertyString NameGeomPattern
App::PropertyFloat HatchScale
App::PropertyFloat HatchRotation
App::PropertyVector HatchOffset
App::PropertyBool FuseBeforeCut
App::PropertyBool TrimAfterCut
App::PropertyBool UsePreviousCut
App::PropertyFloatConstraint SectionLineStretch
Public Attributes inherited from TechDraw::DrawViewPart
App::PropertyLinkList Source
App::PropertyXLinkList XSource
App::PropertyVector Direction
App::PropertyVector XDirection
App::PropertyBool Perspective
App::PropertyDistance Focus
App::PropertyBool CoarseView
App::PropertyBool SeamVisible
App::PropertyBool SmoothVisible
App::PropertyBool IsoVisible
App::PropertyBool HardHidden
App::PropertyBool SmoothHidden
App::PropertyBool SeamHidden
App::PropertyBool IsoHidden
App::PropertyInteger IsoCount
App::PropertyInteger ScrubCount
Public Attributes inherited from TechDraw::DrawView
App::PropertyDistance X
App::PropertyDistance Y
App::PropertyBool LockPosition
App::PropertyFloatConstraint Scale
App::PropertyEnumeration ScaleType
App::PropertyAngle Rotation
App::PropertyString Caption
boost::signals2::signal< void(const DrawView *)> signalGuiPaint
boost::signals2::signal< void(const DrawView *, std::string, std::string)> signalProgressMessage
Public Attributes inherited from App::DocumentObject
PropertyString Label
PropertyString Label2
PropertyExpressionEngine ExpressionEngine
PropertyBool Visibility
Allow control visibility status in App name space.
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalBeforeChange
signal before changing a property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalChanged
signal on changed property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalEarlyChanged
signal on changed property of this object before document scoped signalChangedObject
Public Attributes inherited from TechDraw::CosmeticExtension
TechDraw::PropertyCosmeticVertexList CosmeticVertexes
TechDraw::PropertyCosmeticEdgeList CosmeticEdges
TechDraw::PropertyCenterLineList CenterLines
TechDraw::PropertyGeomFormatList GeomFormats
Static Public Attributes
static const char * SectionDirEnums []
static const char * CutSurfaceEnums [] = {"Hide", "Color", "SvgHatch", "PatHatch", nullptr}
Static Public Attributes inherited from App::DocumentObject
static DocumentObjectExecReturn * StdReturn
Protected Member Functions
virtual gp_Pln getSectionPlane () const
virtual TopoDS_Compound findSectionPlaneIntersections (const TopoDS_Shape &shape)
void getParameters ()
bool debugSection () const
int prefCutSurface () const
bool trimAfterCut () const
void onDocumentRestored () override
get called after a document has been fully restored
void setupObject () override
get called after a brand new object was created
void replaceSvgIncluded (std::string newSvgFile)
void replacePatIncluded (std::string newPatFile)
Protected Member Functions inherited from TechDraw::DrawViewPart
bool checkXDirection () const
virtual TechDraw::GeometryObjectPtr buildGeometryObject (TopoDS_Shape &shape, const gp_Ax2 &viewAxis)
create a geometry object and trigger the HLR process in another thread
virtual TechDraw::GeometryObjectPtr makeGeometryForShape (TopoDS_Shape &shape)
prepare the shape for HLR processing by centering, scaling and rotating it
void partExec (TopoDS_Shape &shape)
virtual void addPoints (void)
void extractFaces ()
make faces from the edge geometry
void findFacesNew (const std::vector< TechDraw::BaseGeomPtr > &goEdges)
void findFacesOld (const std::vector< TechDraw::BaseGeomPtr > &goEdges)
Protected Member Functions inherited from TechDraw::DrawView
void onBeforeChange (const App::Property *prop) override
get called before the value is changed
virtual void validateScale ()
int prefScaleType ()
double prefScale ()
void touchTreeOwner (App::DocumentObject *owner) const
Protected Member Functions inherited from App::DocumentObject
virtual App::DocumentObjectExecReturn * recompute ()
recompute only this object
App::DocumentObjectExecReturn * executeExtensions ()
void setError ()
void resetError ()
void setDocument (App::Document *doc)
void onEarlyChange (const Property *prop) override
get called by the container when a property was changed
virtual void onUndoRedoFinished ()
get called after an undo/redo transaction is finished
virtual void onSettingDocument ()
get called after setting the document
void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus) override
get called when a property status has changed
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData () const
Protected Member Functions inherited from App::DocumentObjectExtension
virtual const App::PropertyData & extensionGetPropertyData (void) const override
Protected Member Functions inherited from App::Extension
virtual void extensionOnChanged (const Property *p)
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
returns true if the property name change was handled by the extension.
virtual bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
returns true if the property type change was handled by the extension.
void initExtensionType (Base::Type type)
Protected Attributes
TopoDS_Compound m_sectionTopoDSFaces
std::vector< LineSet > m_lineSets
std::vector< TechDraw::FacePtr > m_tdSectionFaces
TopoDS_Shape m_cutShape
TopoDS_Shape m_cutShapeRaw
TopoDS_Shape m_cutPieces
gp_Ax2 m_projectionCS
TopoDS_Shape m_preparedShape
QMetaObject::Connection connectCutWatcher
QFutureWatcher< void > m_cutWatcher
QFuture< void > m_cutFuture
bool m_waitingForCut
TopoDS_Shape m_cuttingTool
double m_shapeSize
Protected Attributes inherited from TechDraw::DrawViewPart
TechDraw::GeometryObjectPtr geometryObject
TechDraw::GeometryObjectPtr m_tempGeometryObject
Base::BoundBox3d bbox
Base::Vector3d shapeCentroid
bool m_handleFaces
TopoDS_Shape m_saveShape
Base::Vector3d m_saveCentroid
std::vector< TechDraw::VertexPtr > m_referenceVerts
Protected Attributes inherited from TechDraw::DrawView
std::string pageFeatName
bool autoPos
bool mouseMove
Protected Attributes inherited from App::DocumentObject
std::bitset< 32 > StatusBits
Py::SmartPtr PythonObject
python object of this class and all descendent
App::Document * _pDoc {nullptr}
pointer to the document this object belongs to
std::string oldLabel
Old label; used for renaming expressions.
const std::string * pcNameInDocument {nullptr}
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Static Protected Attributes
static App::PropertyFloatConstraint::Constraints stretchRange
Additional Inherited Members
Public Types inherited from App::DocumentObject
enum OutListOption { OutListNoExpression = 1, OutListNoHidden = 2, OutListNoXLinked = 4 }
OutList options.
enum GSReason { GS_DEFAULT, GS_SELECT }
reason of calling getSubObjects()
Public Types inherited from App::ExtensionContainer
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Static Public Member Functions inherited from TechDraw::DrawViewPart
static TopoDS_Shape centerScaleRotate (const DrawViewPart *dvp, TopoDS_Shape &inOutShape, Base::Vector3d centroid)
Modify a shape by centering, scaling and rotating and return the centered (but not rotated) shape.
Static Public Member Functions inherited from TechDraw::DrawView
static bool isProjGroupItem (DrawViewPart *item)
Static Public Member Functions inherited from App::DocumentObject
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
Check if the subname reference ends with hidden marker.
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Member Functions inherited from App::DocumentObjectExtension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Static Public Member Functions inherited from App::Extension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Static Protected Member Functions inherited from App::DocumentObjectExtension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
Static Protected Member Functions inherited from App::Extension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 78 of file DrawViewSection.h.
Constructor & Destructor Documentation
DrawViewSection()
DrawViewSection::DrawViewSection ()
Definition at line 142 of file DrawViewSection.cpp.
References ADD_PROPERTY_TYPE, App::Global, App::Property::Hidden, TechDraw::DrawGeomHatch::prefGeomHatchFile(), TechDraw::DrawGeomHatch::prefGeomHatchName(), TechDraw::DrawHatch::prefSvgHatch(), App::Prop_None, App::Prop_Output, App::Property::ReadOnly, and TechDraw::Preferences::SectionUsePreviousCut().
~DrawViewSection()
DrawViewSection::~DrawViewSection () override
Definition at line 258 of file DrawViewSection.cpp.
References Base::Console(), App::PropertyString::getValue(), App::DocumentObject::Label, m_cutFuture, and Base::ConsoleSingleton::Message().
Member Function Documentation
alignSectionFaces()
TopoDS_Compound DrawViewSection::alignSectionFaces (TopoDS_Shape faceIntersections) virtual
Reimplemented in TechDraw::DrawComplexSection.
Definition at line 760 of file DrawViewSection.cpp.
References TechDraw::DrawUtil::fpCompare(), TechDraw::DrawViewPart::getOriginalCentroid(), TechDraw::DrawViewPart::getProjectionCS(), TechDraw::DrawView::getScale(), App::PropertyQuantity::getValue(), mapToPage(), TechDraw::ShapeUtils::moveShape(), TechDraw::ShapeUtils::rotateShape(), TechDraw::DrawView::Rotation, and TechDraw::ShapeUtils::scaleShape().
Referenced by TechDraw::DrawComplexSection::alignSectionFaces(), and postHlrTasks().
debugSection()
bool DrawViewSection::debugSection () const protected
Definition at line 1297 of file DrawViewSection.cpp.
References ParameterGrp::GetBool(), and TechDraw::Preferences::getPreferenceGroup().
Referenced by findSectionPlaneIntersections(), getCSFromBase(), makeCuttingTool(), makeSectionCut(), mapToPage(), onSectionCutFinished(), postHlrTasks(), and prepareShape().
execute()
App::DocumentObjectExecReturn * DrawViewSection::execute () override virtual
recalculate the Feature
Reimplemented from TechDraw::DrawViewPart.
Definition at line 387 of file DrawViewSection.cpp.
References TechDraw::DrawViewPart::addPoints(), TechDraw::DrawViewPart::checkXDirection(), Base::Console(), TechDraw::DrawView::execute(), App::DocumentObject::getNameInDocument(), getShapeToCut(), App::PropertyVector::getValue(), getXDirection(), isBaseValid(), isReallyInBox(), TechDraw::DrawView::keepUpdated(), TechDraw::DrawViewPart::m_saveShape, m_shapeSize, App::Property::purgeTouched(), sectionExec(), SectionOrigin, App::PropertyVector::setValue(), KDL::sqrt(), App::DocumentObject::StdReturn, waitingForCut(), TechDraw::DrawViewPart::waitingForHlr(), Base::ConsoleSingleton::Warning(), Base::Vector3< float_type >::x, TechDraw::DrawViewPart::XDirection, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by FeaturePython.DistanceBolt::onChanged().
findSectionPlaneIntersections()
TopoDS_Compound DrawViewSection::findSectionPlaneIntersections (const TopoDS_Shape & shape) protected virtual
tries to find the intersection of the section plane with the shape giving a collection of planar faces the original algo finds the intersections first then transforms them to match the centered, rotated and scaled cut shape. Aligned complex sections need to intersect the final cut shape (which in this case is a compound of individual cuts) with the "effective" (flattened) section plane.
Reimplemented in TechDraw::DrawComplexSection.
Definition at line 718 of file DrawViewSection.cpp.
References Base::Console(), debugSection(), App::DocumentObject::getNameInDocument(), getSectionPlane(), m_shapeSize, result, and Base::ConsoleSingleton::Warning().
Referenced by postHlrTasks().
getBaseDVP()
TechDraw::DrawViewPart * DrawViewSection::getBaseDVP () const
Definition at line 1192 of file DrawViewSection.cpp.
References importers.importWebGL::base, BaseView, and App::PropertyLink::getValue().
Referenced by getCSFromBase(), getSectionDirectionOnBaseView(), onChanged(), sectionLineEnds(), setCSFromBase(), TechDrawGui::QGIView::snapSectionView(), and unsetupObject().
getChangePointsFromSectionLine()
ChangePointVector DrawViewSection::getChangePointsFromSectionLine () virtual
Definition at line 962 of file DrawViewSection.cpp.
References BaseView, App::PropertyLink::getValue(), result, sectionLineEnds(), and TechDraw::DrawUtil::togp_Pnt().
Referenced by TechDrawGui::QGIViewPart::drawSectionLine().
getCSFromBase()
gp_Ax2 DrawViewSection::getCSFromBase (const std::string sectionName) const virtual
Reimplemented in TechDraw::DrawComplexSection.
Definition at line 1079 of file DrawViewSection.cpp.
References debugSection(), TechDraw::DrawUtil::dumpCS(), getBaseDVP(), TechDraw::DrawViewPart::getProjectionCS(), App::PropertyVector::getValue(), SectionNormal, SectionOrigin, Base::Vector3< float_type >::x, TechDraw::DrawViewPart::XDirection, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by TechDraw::DrawComplexSection::getCSFromBase(), getXDirection(), and setCSFromBase().
getCutCentroid()
Base::Vector3d DrawViewSection::getCutCentroid () const
return the center of the shape resulting from the cut operation
Definition at line 1158 of file DrawViewSection.cpp.
References TechDraw::ShapeUtils::findCentroid(), TechDraw::DrawViewPart::getProjectionCS(), and m_cutPieces.
Referenced by TechDrawGui::QGIView::snapSectionView().
getCutShape()
TopoDS_Shape TechDraw::DrawViewSection::getCutShape () const inline
Definition at line 158 of file DrawViewSection.h.
Referenced by getShapeForDetail().
getCutShapeRaw()
TopoDS_Shape TechDraw::DrawViewSection::getCutShapeRaw () const inline
Definition at line 159 of file DrawViewSection.h.
Referenced by getShapeToCut().
getDecodedSpecsFromFile()
std::vector<PATLineSpec> TechDraw::DrawViewSection::getDecodedSpecsFromFile (std::string fileSpec, std::string myPattern)
getDrawableLines()
std::vector< LineSet > DrawViewSection::getDrawableLines (int i = 0)
Definition at line 1165 of file DrawViewSection.cpp.
References getSectionTopoDSFace(), TechDraw::DrawGeomHatch::getTrimmedLinesSection(), App::PropertyVector::getValue(), App::PropertyFloat::getValue(), HatchOffset, HatchRotation, HatchScale, SplineSurface::i, m_lineSets, makeLineSets(), and result.
getParameters()
void DrawViewSection::getParameters () protected
Definition at line 1290 of file DrawViewSection.cpp.
References FuseBeforeCut, ParameterGrp::GetBool(), TechDraw::Preferences::getPreferenceGroup(), and App::PropertyBool::setValue().
getSectionCS()
gp_Ax2 DrawViewSection::getSectionCS () const
Definition at line 1136 of file DrawViewSection.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), App::DocumentObject::getNameInDocument(), App::PropertyVector::getValue(), getXDirection(), SectionNormal, SectionOrigin, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by getSectionPlane(), and setCSFromLocalUnit().
getSectionDirectionOnBaseView()
Base::Vector3d DrawViewSection::getSectionDirectionOnBaseView ()
Definition at line 949 of file DrawViewSection.cpp.
References Base::Vector3< float_type >::Cross(), TechDraw::DrawViewPart::Direction, getBaseDVP(), App::PropertyVector::getValue(), Base::Vector3< float_type >::Normalize(), TechDraw::DrawViewPart::projectPoint(), and SectionNormal.
Referenced by sectionLineEnds().
getSectionPlane()
gp_Pln DrawViewSection::getSectionPlane () const protected virtual
Reimplemented in TechDraw::DrawComplexSection.
Definition at line 704 of file DrawViewSection.cpp.
References getSectionCS().
Referenced by findSectionPlaneIntersections(), TechDraw::DrawComplexSection::getSectionPlane(), and makeCuttingTool().
getSectionTopoDSFace()
TopoDS_Face DrawViewSection::getSectionTopoDSFace (int i)
Definition at line 1180 of file DrawViewSection.cpp.
References src.Mod.AddonManager.NetworkManager::count, SplineSurface::i, and m_sectionTopoDSFaces.
Referenced by getDrawableLines().
getShapeForDetail()
TopoDS_Shape DrawViewSection::getShapeForDetail () const override virtual
deliver a shape appropriate for making a detail view based on this view TODO: why does dvp do the thinking for detail, but section picks its own version of the shape? Should we have a getShapeForSection?
Reimplemented from TechDraw::DrawViewPart.
Definition at line 382 of file DrawViewSection.cpp.
References getCutShape(), TechDraw::DrawViewPart::getProjectionCS(), App::PropertyQuantity::getValue(), TechDraw::ShapeUtils::rotateShape(), and TechDraw::DrawView::Rotation.
Referenced by TechDraw::DrawComplexSection::getShapeForDetail().
getShapeToCut()
TopoDS_Shape DrawViewSection::getShapeToCut () virtual
Definition at line 344 of file DrawViewSection.cpp.
References importers.importWebGL::base, BaseView, Base::Console(), FuseBeforeCut, getCutShapeRaw(), TechDraw::DrawViewDetail::getDetailShape(), getShapeToCut(), TechDraw::DrawViewPart::getSourceShape(), App::PropertyLink::getValue(), App::PropertyBool::getValue(), Base::ConsoleSingleton::Message(), and UsePreviousCut.
Referenced by execute(), and getShapeToCut().
getShapeToIntersect()
virtual TopoDS_Shape TechDraw::DrawViewSection::getShapeToIntersect () inline virtual
Reimplemented in TechDraw::DrawComplexSection.
Definition at line 152 of file DrawViewSection.h.
Referenced by TechDraw::DrawComplexSection::getShapeToIntersect(), and postHlrTasks().
getShapeToPrepare()
virtual TopoDS_Shape TechDraw::DrawViewSection::getShapeToPrepare () const inline virtual
Reimplemented in TechDraw::DrawComplexSection.
Definition at line 134 of file DrawViewSection.h.
Referenced by TechDraw::DrawComplexSection::getShapeToPrepare(), and onSectionCutFinished().
getTDFaceGeometry()
std::vector<TechDraw::FacePtr> TechDraw::DrawViewSection::getTDFaceGeometry () inline
Definition at line 147 of file DrawViewSection.h.
getViewProviderName()
const char* TechDraw::DrawViewSection::getViewProviderName () const inline override virtual
returns the type name of the ViewProvider
Reimplemented from TechDraw::DrawViewPart.
Definition at line 115 of file DrawViewSection.h.
getXDirection()
Base::Vector3d DrawViewSection::getXDirection () const override virtual
Reimplemented from TechDraw::DrawViewPart.
Definition at line 1007 of file DrawViewSection.cpp.
References BaseView, TechDraw::DrawUtil::fpCompare(), getCSFromBase(), App::ExtensionContainer::getPropertyByName(), App::PropertyVector::getValue(), App::PropertyLink::getValue(), App::PropertyEnumeration::getValueAsString(), Base::Vector3< float_type >::Length(), SectionDirection, and TechDraw::DrawViewPart::XDirection.
Referenced by execute(), and getSectionCS().
isBaseValid()
bool DrawViewSection::isBaseValid () const virtual
Reimplemented in TechDraw::DrawComplexSection.
Definition at line 438 of file DrawViewSection.cpp.
References BaseView, and App::PropertyLink::getValue().
Referenced by execute().
isReallyInBox() [1/2]
bool DrawViewSection::isReallyInBox (const Base::Vector3d v, const Base::BoundBox3d bb) const
check if point is in box or on boundary of box compare to isInBox which doesn't allow on boundary
Definition at line 988 of file DrawViewSection.cpp.
References Base::BoundBox3< Precision >::MaxX, Base::BoundBox3< Precision >::MaxY, Base::BoundBox3< Precision >::MaxZ, Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, Base::BoundBox3< Precision >::MinZ, and TestSpreadsheet::v.
Referenced by execute().
isReallyInBox() [2/2]
bool DrawViewSection::isReallyInBox (const gp_Pnt p, const Bnd_Box & bb) const
Definition at line 1002 of file DrawViewSection.cpp.
References buildPsets::p.
makeCuttingTool()
TopoDS_Shape DrawViewSection::makeCuttingTool (double shapeSize) virtual
Reimplemented in TechDraw::DrawComplexSection.
Definition at line 597 of file DrawViewSection.cpp.
References debugSection(), and getSectionPlane().
Referenced by sectionExec().
makeFaceFromWires()
TopoDS_Shape DrawViewSection::makeFaceFromWires (std::vector< TopoDS_Wire > & inWires)
Definition at line 860 of file DrawViewSection.cpp.
References Base::Console(), App::DocumentObject::getNameInDocument(), Handle(), TechDraw::EdgeWalker::sortWiresBySize(), and Base::ConsoleSingleton::Warning().
Referenced by mapToPage().
makeLineSets()
void DrawViewSection::makeLineSets (void)
Definition at line 1231 of file DrawViewSection.cpp.
References Base::Console(), App::DocumentObject::getNameInDocument(), App::PropertyFileIncluded::getValue(), App::PropertyString::getValue(), Base::FileInfo::hasExtension(), App::PropertyFileIncluded::isEmpty(), App::PropertyString::isEmpty(), Base::FileInfo::isReadable(), m_lineSets, TechDraw::DrawGeomHatch::makeLineSets(), Base::ConsoleSingleton::Message(), NameGeomPattern, and PatIncluded.
Referenced by getDrawableLines(), onChanged(), and onDocumentRestored().
makeSectionCut()
void DrawViewSection::makeSectionCut (const TopoDS_Shape & baseShape) virtual
Reimplemented in TechDraw::DrawComplexSection.
Definition at line 486 of file DrawViewSection.cpp.
References Base::Console(), debugSection(), App::DocumentObject::getNameInDocument(), App::PropertyString::getValue(), App::DocumentObject::Label, m_cutPieces, m_cuttingTool, TechDraw::DrawViewPart::m_saveShape, toolbit-attributes::s, TechDraw::DrawView::showProgressMessage(), trimAfterCut(), waitingForCut(), and Base::ConsoleSingleton::Warning().
Referenced by TechDraw::DrawComplexSection::makeSectionCut(), and sectionExec().
makeTDSectionFaces()
std::vector< TechDraw::FacePtr > DrawViewSection::makeTDSectionFaces (TopoDS_Compound topoDSFaces) virtual
Definition at line 904 of file DrawViewSection.cpp.
References TechDraw::BaseGeom::baseFactory(), SCL.SimpleDataTypes::e, and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by postHlrTasks().
mapToPage()
TopoDS_Compound DrawViewSection::mapToPage (TopoDS_Shape & shapeToAlign)
Definition at line 779 of file DrawViewSection.cpp.
References Base::Console(), debugSection(), EWTOLERANCE, App::DocumentObject::getNameInDocument(), TechDraw::DrawViewPart::getProjectionCS(), Base::ConsoleSingleton::Log(), TechDraw::EdgeWalker::makeCleanWire(), makeFaceFromWires(), TechDraw::GeometryObject::projectSimpleShape(), and result.
Referenced by alignSectionFaces().
mustExecute()
short DrawViewSection::mustExecute () const override virtual
mustExecute We call this method to check if the object was modified to be invoked. If the object label or an argument is modified. If we must recompute the object - to call the method execute(). 0: no recomputation is needed 1: recomputation needed
Remarks
If an object is marked as 'touched' then this does not necessarily mean that it will be recomputed. It only means that all objects that link it (i.e. its InList) will be recomputed.
Reimplemented from TechDraw::DrawViewPart.
Definition at line 267 of file DrawViewSection.cpp.
References BaseView, TechDraw::DrawViewPart::Direction, App::DocumentObject::isRestoring(), App::Property::isTouched(), TechDraw::DrawView::mustExecute(), TechDraw::DrawView::Rotation, TechDraw::DrawView::Scale, SectionNormal, and SectionOrigin.
onChanged()
void DrawViewSection::onChanged (const App::Property * prop) override virtual
get called by the container when a property was changed
Reimplemented from TechDraw::DrawViewPart.
Definition at line 281 of file DrawViewSection.cpp.
References BaseView, CutSurfaceDisplay, TechDraw::DrawViewPart::Direction, toolbit-attributes::doc, FileGeomPattern, FileHatchPattern, getBaseDVP(), App::DocumentObject::getDocument(), App::PropertyVector::getValue(), App::PropertyLink::getValue(), App::PropertyString::getValue(), Base::BaseClass::isDerivedFrom(), App::DocumentObject::isRestoring(), App::PropertyEnumeration::isValue(), makeLineSets(), NameGeomPattern, TechDraw::DrawView::onChanged(), TechDraw::DrawViewPart::onChanged(), App::Property::ReadOnly, replacePatIncluded(), replaceSvgIncluded(), TechDraw::DrawView::requestPaint(), SectionLineStretch, SectionNormal, SectionSymbol, App::Property::setStatus(), App::PropertyVector::setValue(), App::DocumentObject::touch(), and UsePreviousCut.
onDocumentRestored()
void DrawViewSection::onDocumentRestored () override protected virtual
get called after a document has been fully restored
Reimplemented from TechDraw::DrawView.
Definition at line 1213 of file DrawViewSection.cpp.
References makeLineSets(), and TechDraw::DrawView::onDocumentRestored().
onSectionCutFinished
void DrawViewSection::onSectionCutFinished (void) virtual slot
Definition at line 616 of file DrawViewSection.cpp.
References TechDraw::DrawViewPart::buildGeometryObject(), connectCutWatcher, debugSection(), App::DocumentObject::getNameInDocument(), TechDraw::DrawViewPart::getProjectionCS(), getShapeToPrepare(), m_preparedShape, m_shapeSize, TechDraw::DrawViewPart::m_tempGeometryObject, postSectionCutTasks(), prepareShape(), and TechDraw::DrawView::showProgressMessage().
Referenced by TechDraw::DrawComplexSection::onSectionCutFinished(), and sectionExec().
postHlrTasks()
void DrawViewSection::postHlrTasks (void) override virtual
run any tasks that need to been done after geometry is available
Reimplemented from TechDraw::DrawViewPart.
Definition at line 636 of file DrawViewSection.cpp.
References alignSectionFaces(), TechDraw::DrawView::autoScale(), BaseView, TechDraw::DrawView::checkFit(), debugSection(), findSectionPlaneIntersections(), TechDraw::DrawUtil::fpCompare(), TechDraw::DrawViewPart::getProjectionCS(), TechDraw::DrawView::getScale(), getShapeToIntersect(), App::PropertyQuantity::getValue(), App::PropertyLink::getValue(), App::PropertyEnumeration::isValue(), TechDraw::DrawViewPart::m_saveCentroid, TechDraw::DrawViewPart::m_saveShape, m_sectionTopoDSFaces, m_tdSectionFaces, makeTDSectionFaces(), TechDraw::ShapeUtils::moveShape(), TechDraw::DrawView::overrideKeepUpdated(), TechDraw::DrawViewPart::postHlrTasks(), App::Property::purgeTouched(), TechDraw::DrawView::requestPaint(), TechDraw::ShapeUtils::rotateShape(), TechDraw::DrawView::Rotation, TechDraw::DrawView::Scale, TechDraw::ShapeUtils::scaleShape(), TechDraw::DrawView::ScaleType, sectionExec(), and App::PropertyFloat::setValue().
postSectionCutTasks()
void DrawViewSection::postSectionCutTasks () virtual
Definition at line 684 of file DrawViewSection.cpp.
References SCL.SimpleDataTypes::c, and App::DocumentObject::getInList().
Referenced by onSectionCutFinished().
prefCutSurface()
int DrawViewSection::prefCutSurface () const protected
Definition at line 1302 of file DrawViewSection.cpp.
References ParameterGrp::GetInt(), and TechDraw::Preferences::getPreferenceGroup().
prepareShape()
TopoDS_Shape DrawViewSection::prepareShape (const TopoDS_Shape & rawShape, double shapeSize) virtual
position, scale and rotate shape for buildGeometryObject save the cut shape for further processing
Reimplemented in TechDraw::DrawComplexSection.
Definition at line 555 of file DrawViewSection.cpp.
References Base::Console(), debugSection(), src.Mod.PartDesign.Scripts.Gear::e1, TechDraw::ShapeUtils::findCentroid(), TechDraw::DrawUtil::fpCompare(), App::DocumentObject::getNameInDocument(), TechDraw::DrawViewPart::getProjectionCS(), TechDraw::DrawView::getScale(), App::PropertyQuantity::getValue(), m_cutShape, m_cutShapeRaw, m_projectionCS, TechDraw::DrawViewPart::m_saveCentroid, TechDraw::ShapeUtils::moveShape(), TechDraw::ShapeUtils::rotateShape(), TechDraw::DrawView::Rotation, TechDraw::ShapeUtils::scaleShape(), and Base::ConsoleSingleton::Warning().
Referenced by onSectionCutFinished(), and TechDraw::DrawComplexSection::prepareShape().
replacePatIncluded()
void DrawViewSection::replacePatIncluded (std::string newPatFile) protected
Definition at line 1272 of file DrawViewSection.cpp.
References Base::FileInfo::isReadable(), PatIncluded, and App::PropertyFileIncluded::setValue().
Referenced by onChanged(), and setupObject().
replaceSvgIncluded()
void DrawViewSection::replaceSvgIncluded (std::string newSvgFile) protected
Definition at line 1255 of file DrawViewSection.cpp.
References Base::FileInfo::isReadable(), App::PropertyFileIncluded::setValue(), and SvgIncluded.
Referenced by onChanged(), and setupObject().
sectionExec()
void DrawViewSection::sectionExec (TopoDS_Shape & s)
Definition at line 447 of file DrawViewSection.cpp.
References draftgeoutils.intersections::connect(), connectCutWatcher, Base::Console(), m_cutFuture, m_cuttingTool, m_cutWatcher, m_shapeSize, makeCuttingTool(), makeSectionCut(), Base::ConsoleSingleton::Message(), Path.Post.scripts.opensbp_post::move(), onSectionCutFinished(), MovieTool::run(), waitingForCut(), and TechDraw::DrawViewPart::waitingForHlr().
Referenced by execute(), and postHlrTasks().
sectionLineEnds()
std::pair< Base::Vector3d, Base::Vector3d > DrawViewSection::sectionLineEnds () virtual
Reimplemented in TechDraw::DrawComplexSection.
Definition at line 933 of file DrawViewSection.cpp.
References getBaseDVP(), TechDraw::DrawViewPart::getOriginalCentroid(), getSectionDirectionOnBaseView(), TechDraw::DrawViewPart::getSizeAlongVector(), App::PropertyVector::getValue(), App::PropertyFloat::getValue(), TechDraw::DrawViewPart::projectPoint(), result, SectionLineStretch, and SectionOrigin.
Referenced by TechDrawGui::QGIViewPart::drawSectionLine(), and getChangePointsFromSectionLine().
setCSFromBase() [1/2]
void DrawViewSection::setCSFromBase (Base::Vector3d localUnit)
Definition at line 1047 of file DrawViewSection.cpp.
References TechDraw::DrawViewPart::Direction, getBaseDVP(), TechDraw::DrawViewPart::localVectorToCS(), SectionNormal, App::PropertyVector::setValue(), and TechDraw::DrawViewPart::XDirection.
setCSFromBase() [2/2]
void DrawViewSection::setCSFromBase (const std::string sectionName)
Definition at line 1033 of file DrawViewSection.cpp.
References TechDraw::DrawViewPart::Direction, getCSFromBase(), SectionNormal, App::PropertyVector::setValue(), and TechDraw::DrawViewPart::XDirection.
Referenced by TechDrawGui::TaskSectionView::createSectionView(), and TechDrawGui::TaskSectionView::updateSectionView().
setCSFromLocalUnit()
void DrawViewSection::setCSFromLocalUnit (const Base::Vector3d localUnit)
Definition at line 1065 of file DrawViewSection.cpp.
References getSectionCS(), App::PropertyVector::getValue(), TechDraw::DrawViewPart::projectPoint(), SectionNormal, SectionOrigin, App::PropertyVector::setValue(), TechDraw::DrawUtil::togp_Dir(), TechDraw::DrawUtil::togp_Pnt(), TechDraw::DrawUtil::toVector3d(), and TechDraw::DrawViewPart::XDirection.
setupObject()
void DrawViewSection::setupObject () override protected virtual
get called after a brand new object was created
Reimplemented from App::DocumentObject.
Definition at line 1219 of file DrawViewSection.cpp.
References FileGeomPattern, FileHatchPattern, App::PropertyString::getValue(), replacePatIncluded(), replaceSvgIncluded(), and App::DocumentObject::setupObject().
showSectionEdges()
bool DrawViewSection::showSectionEdges (void)
Definition at line 1310 of file DrawViewSection.cpp.
References ParameterGrp::GetBool(), and TechDraw::Preferences::getPreferenceGroup().
trimAfterCut()
bool DrawViewSection::trimAfterCut () const protected
Definition at line 1315 of file DrawViewSection.cpp.
References App::PropertyBool::getValue(), and TrimAfterCut.
Referenced by makeSectionCut().
unsetupObject()
void DrawViewSection::unsetupObject () override virtual
remove features that are useless without this DVP hatches, geomhatches, dimensions, ...
Reimplemented from TechDraw::DrawViewPart.
Definition at line 1204 of file DrawViewSection.cpp.
References getBaseDVP(), and TechDraw::DrawViewPart::unsetupObject().
waitingForCut() [1/2]
void TechDraw::DrawViewSection::waitingForCut (bool s) inline
Definition at line 126 of file DrawViewSection.h.
References toolbit-attributes::s.
waitingForCut() [2/2]
bool TechDraw::DrawViewSection::waitingForCut (void) const inline
Definition at line 127 of file DrawViewSection.h.
Referenced by execute(), makeSectionCut(), sectionExec(), and waitingForResult().
waitingForResult()
bool DrawViewSection::waitingForResult () const override virtual
Reimplemented from TechDraw::DrawViewPart.
Definition at line 696 of file DrawViewSection.cpp.
References waitingForCut(), and TechDraw::DrawViewPart::waitingForResult().
Member Data Documentation
BaseView
App::PropertyLink TechDraw::DrawViewSection::BaseView
Definition at line 86 of file DrawViewSection.h.
Referenced by getBaseDVP(), getChangePointsFromSectionLine(), getShapeToCut(), getXDirection(), isBaseValid(), mustExecute(), onChanged(), postHlrTasks(), TechDrawGui::TaskComplexSection::TaskComplexSection(), and TechDrawGui::TaskSectionView::TaskSectionView().
connectCutWatcher
QMetaObject::Connection TechDraw::DrawViewSection::connectCutWatcher protected
Definition at line 204 of file DrawViewSection.h.
Referenced by onSectionCutFinished(), and sectionExec().
CutSurfaceDisplay
App::PropertyEnumeration TechDraw::DrawViewSection::CutSurfaceDisplay
Definition at line 93 of file DrawViewSection.h.
Referenced by onChanged().
CutSurfaceEnums
const char * DrawViewSection::CutSurfaceEnums = {"Hide", "Color", "SvgHatch", "PatHatch", nullptr} static
Definition at line 164 of file DrawViewSection.h.
FileGeomPattern
App::PropertyFile TechDraw::DrawViewSection::FileGeomPattern
Definition at line 95 of file DrawViewSection.h.
Referenced by onChanged(), and setupObject().
FileHatchPattern
App::PropertyFile TechDraw::DrawViewSection::FileHatchPattern
Definition at line 94 of file DrawViewSection.h.
Referenced by onChanged(), and setupObject().
FuseBeforeCut
App::PropertyBool TechDraw::DrawViewSection::FuseBeforeCut
Definition at line 103 of file DrawViewSection.h.
Referenced by getParameters(), and getShapeToCut().
HatchOffset
App::PropertyVector TechDraw::DrawViewSection::HatchOffset
Definition at line 101 of file DrawViewSection.h.
Referenced by getDrawableLines().
HatchRotation
App::PropertyFloat TechDraw::DrawViewSection::HatchRotation
Definition at line 100 of file DrawViewSection.h.
Referenced by getDrawableLines().
HatchScale
App::PropertyFloat TechDraw::DrawViewSection::HatchScale
Definition at line 99 of file DrawViewSection.h.
Referenced by getDrawableLines().
m_cutFuture
QFuture<void> TechDraw::DrawViewSection::m_cutFuture protected
Definition at line 206 of file DrawViewSection.h.
Referenced by sectionExec(), and ~DrawViewSection().
m_cutPieces
TopoDS_Shape TechDraw::DrawViewSection::m_cutPieces protected
Definition at line 200 of file DrawViewSection.h.
Referenced by getCutCentroid(), and makeSectionCut().
m_cutShape
TopoDS_Shape TechDraw::DrawViewSection::m_cutShape protected
Definition at line 192 of file DrawViewSection.h.
Referenced by prepareShape().
m_cutShapeRaw
TopoDS_Shape TechDraw::DrawViewSection::m_cutShapeRaw protected
Definition at line 193 of file DrawViewSection.h.
Referenced by prepareShape().
m_cuttingTool
TopoDS_Shape TechDraw::DrawViewSection::m_cuttingTool protected
Definition at line 208 of file DrawViewSection.h.
Referenced by makeSectionCut(), and sectionExec().
m_cutWatcher
QFutureWatcher<void> TechDraw::DrawViewSection::m_cutWatcher protected
Definition at line 205 of file DrawViewSection.h.
Referenced by sectionExec().
m_lineSets
std::vector<LineSet> TechDraw::DrawViewSection::m_lineSets protected
Definition at line 181 of file DrawViewSection.h.
Referenced by getDrawableLines(), and makeLineSets().
m_preparedShape
TopoDS_Shape TechDraw::DrawViewSection::m_preparedShape protected
Definition at line 202 of file DrawViewSection.h.
Referenced by onSectionCutFinished().
m_projectionCS
gp_Ax2 TechDraw::DrawViewSection::m_projectionCS protected
Definition at line 201 of file DrawViewSection.h.
Referenced by prepareShape().
m_sectionTopoDSFaces
TopoDS_Compound TechDraw::DrawViewSection::m_sectionTopoDSFaces protected
Definition at line 180 of file DrawViewSection.h.
Referenced by getSectionTopoDSFace(), and postHlrTasks().
m_shapeSize
double TechDraw::DrawViewSection::m_shapeSize protected
Definition at line 209 of file DrawViewSection.h.
Referenced by execute(), findSectionPlaneIntersections(), onSectionCutFinished(), and sectionExec().
m_tdSectionFaces
std::vector<TechDraw::FacePtr> TechDraw::DrawViewSection::m_tdSectionFaces protected
Definition at line 182 of file DrawViewSection.h.
Referenced by postHlrTasks().
m_waitingForCut
bool TechDraw::DrawViewSection::m_waitingForCut protected
Definition at line 207 of file DrawViewSection.h.
NameGeomPattern
App::PropertyString TechDraw::DrawViewSection::NameGeomPattern
Definition at line 98 of file DrawViewSection.h.
Referenced by makeLineSets(), and onChanged().
PatIncluded
App::PropertyFileIncluded TechDraw::DrawViewSection::PatIncluded
Definition at line 97 of file DrawViewSection.h.
Referenced by makeLineSets(), and replacePatIncluded().
SectionDirection
App::PropertyEnumeration TechDraw::DrawViewSection::SectionDirection
Definition at line 92 of file DrawViewSection.h.
Referenced by getXDirection(), TechDrawGui::TaskSectionView::restoreSectionState(), TechDrawGui::TaskComplexSection::restoreSectionState(), TechDrawGui::TaskSectionView::saveSectionState(), TechDrawGui::TaskComplexSection::saveSectionState(), and TechDrawGui::TaskSectionView::TaskSectionView().
SectionDirEnums
const char * DrawViewSection::SectionDirEnums static
Initial value:
=
    {"Right", "Left", "Up", "Down", "Aligned", nullptr}
Definition at line 163 of file DrawViewSection.h.
SectionLineStretch
App::PropertyFloatConstraint TechDraw::DrawViewSection::SectionLineStretch
Definition at line 107 of file DrawViewSection.h.
Referenced by onChanged(), and sectionLineEnds().
SectionNormal
App::PropertyVector TechDraw::DrawViewSection::SectionNormal
Definition at line 87 of file DrawViewSection.h.
Referenced by TechDrawGui::QGIViewPart::drawComplexSectionLine(), TechDrawGui::QGIViewPart::drawSectionLine(), getCSFromBase(), getSectionCS(), getSectionDirectionOnBaseView(), mustExecute(), onChanged(), TechDrawGui::TaskSectionView::restoreSectionState(), TechDrawGui::TaskComplexSection::restoreSectionState(), TechDrawGui::TaskSectionView::saveSectionState(), TechDrawGui::TaskComplexSection::saveSectionState(), setCSFromBase(), setCSFromLocalUnit(), TechDrawGui::TaskSectionView::setUiEdit(), TechDrawGui::TaskComplexSection::setUiEdit(), and TechDrawGui::QGIView::snapSectionView().
SectionOrigin
App::PropertyVector TechDraw::DrawViewSection::SectionOrigin
Definition at line 88 of file DrawViewSection.h.
Referenced by execute(), getCSFromBase(), getSectionCS(), mustExecute(), TechDrawGui::TaskSectionView::restoreSectionState(), TechDrawGui::TaskComplexSection::restoreSectionState(), TechDrawGui::TaskSectionView::saveSectionState(), TechDrawGui::TaskComplexSection::saveSectionState(), sectionLineEnds(), setCSFromLocalUnit(), TechDrawGui::TaskSectionView::setUiEdit(), and TechDrawGui::QGIView::snapSectionView().
SectionSymbol
App::PropertyString TechDraw::DrawViewSection::SectionSymbol
Definition at line 89 of file DrawViewSection.h.
Referenced by TechDrawGui::QGIViewPart::drawComplexSectionLine(), TechDrawGui::QGIViewPart::drawSectionLine(), onChanged(), TechDrawGui::TaskSectionView::restoreSectionState(), TechDrawGui::TaskComplexSection::restoreSectionState(), TechDrawGui::TaskSectionView::saveSectionState(), TechDrawGui::TaskComplexSection::saveSectionState(), TechDrawGui::TaskSectionView::setUiEdit(), and TechDrawGui::TaskComplexSection::setUiEdit().
stretchRange
App::PropertyFloatConstraint::Constraints DrawViewSection::stretchRange static protected
Initial value:
= {
                            stretchMinimum, stretchMaximum, stretchStep}
Definition at line 211 of file DrawViewSection.h.
SvgIncluded
App::PropertyFileIncluded TechDraw::DrawViewSection::SvgIncluded
Definition at line 96 of file DrawViewSection.h.
Referenced by replaceSvgIncluded().
TrimAfterCut
App::PropertyBool TechDraw::DrawViewSection::TrimAfterCut
Definition at line 104 of file DrawViewSection.h.
Referenced by trimAfterCut().
UsePreviousCut
App::PropertyBool TechDraw::DrawViewSection::UsePreviousCut
Definition at line 105 of file DrawViewSection.h.
Referenced by getShapeToCut(), and onChanged().
The documentation for this class was generated from the following files:
DrawViewSection.h
DrawViewSection.cpp