FreeCAD: PreferencePackManager.cpp File Reference
PreferencePackManager.cpp File Reference
#include "PreCompiled.h"
#include <memory>
#include <string_view>
#include <mutex>
#include <boost/filesystem.hpp>
#include <boost/algorithm/string.hpp>
#include <QDir>
#include "PreferencePackManager.h"
#include "App/Metadata.h"
#include "Base/Parameter.h"
#include "Base/Interpreter.h"
#include "Base/Console.h"
#include "DockWindowManager.h"
#include "ToolBarManager.h"
#include <App/Application.h>
#include <ctime>
Functions
static boost::filesystem::path getSavedPrefPacksPath ()
static boost::filesystem::path getResourcePrefPacksPath ()
static std::string findUnusedName (const std::string &basename, ParameterGrp::handle parent)
static void copyTemplateParameters (Base::Reference< ParameterGrp > templateGroup, const std::string &path, Base::Reference< ParameterGrp > outputGroup)
static void copyTemplateParameters (ParameterManager &templateParameterManager, ParameterManager &outputParameterManager)
static std::vector< fs::path > scanForTemplateFolders (const std::string &groupName, const fs::path &entry)
static std::vector< PreferencePackManager::TemplateFile > scanForTemplateFiles (const std::string &groupName, const fs::path &entry)
Function Documentation
copyTemplateParameters() [1/2]
static void copyTemplateParameters (Base::Reference< ParameterGrp > templateGroup, const std::string & path, Base::Reference< ParameterGrp > outputGroup) static
Definition at line 446 of file PreferencePackManager.cpp.
References App::GetApplication(), ParameterGrp::GetASCIIMap(), ParameterGrp::GetBoolMap(), ParameterGrp::GetFloatMap(), ParameterGrp::GetGroup(), ParameterGrp::GetGroups(), Gui::ToolBarManager::getInstance(), ParameterGrp::GetIntMap(), App::Application::GetParameterGroupByPath(), ParameterGrp::GetUnsignedMap(), Gui::DockWindowManager::instance(), src.Mod.Test.testPathArray::path, Gui::DockWindowManager::saveState(), Gui::ToolBarManager::saveState(), ParameterGrp::SetASCII(), ParameterGrp::SetBool(), ParameterGrp::SetFloat(), ParameterGrp::SetInt(), and ParameterGrp::SetUnsigned().
Referenced by copyTemplateParameters(), and Gui::PreferencePackManager::save().
copyTemplateParameters() [2/2]
static void copyTemplateParameters (ParameterManager & templateParameterManager, ParameterManager & outputParameterManager) static
Definition at line 497 of file PreferencePackManager.cpp.
References copyTemplateParameters(), ParameterGrp::GetGroup(), ParameterGrp::GetGroups(), and toolbit-attributes::group.
findUnusedName()
static std::string findUnusedName (const std::string & basename, ParameterGrp::handle parent) static
Definition at line 375 of file PreferencePackManager.cpp.
References SplineSurface::i, and Init::parent.
Referenced by Gui::PreferencePackManager::toggleVisibility().
getResourcePrefPacksPath()
static boost::filesystem::path getResourcePrefPacksPath () static
Definition at line 59 of file PreferencePackManager.cpp.
References App::Application::getResourceDir(), src.Mod.Test.testPathArray::path, and Base::FileInfo::stringToPath().
Referenced by Gui::PreferencePackManager::getResourcePreferencePacksPath().
getSavedPrefPacksPath()
static boost::filesystem::path getSavedPrefPacksPath () static
Definition at line 53 of file PreferencePackManager.cpp.
References App::Application::getUserAppDataDir(), src.Mod.Test.testPathArray::path, and Base::FileInfo::stringToPath().
Referenced by Gui::PreferencePack::apply(), and Gui::PreferencePackManager::getSavedPreferencePacksPath().
scanForTemplateFiles()
static std::vector<PreferencePackManager::TemplateFile> scanForTemplateFiles (const std::string & groupName, const fs::path & entry) static
Definition at line 556 of file PreferencePackManager.cpp.
References Base::FileInfo::pathToString(), and scanForTemplateFolders().
Referenced by Gui::PreferencePackManager::templateFiles().
scanForTemplateFolders()
static std::vector<fs::path> scanForTemplateFolders (const std::string & groupName, const fs::path & entry) static
Definition at line 534 of file PreferencePackManager.cpp.
References Base::FileInfo::pathToString().
Referenced by scanForTemplateFiles().