FreeCAD: App::PropertyXLinkList Class Reference
App::PropertyXLinkList Class Reference
#include <PropertyLinks.h>
Public Member Functions
PropertyXLinkList ()
~PropertyXLinkList () override
PyObject * getPyObject () override
void setPyObject (PyObject *) override
Public Member Functions inherited from App::PropertyXLinkSubList
PropertyXLinkSubList ()
~PropertyXLinkSubList () override
void afterRestore () override
void onContainerRestored () override
int getSize () const
void setValue (DocumentObject *, const char *)
void setValues (const std::vector< DocumentObject * > &)
void set1Value (int idx, DocumentObject *value, const std::vector< std::string > &SubList={})
void setValues (const std::vector< DocumentObject * > &, const std::vector< const char * > &)
void setValues (const std::vector< DocumentObject * > &, const std::vector< std::string > &)
void setValues (std::map< App::DocumentObject *, std::vector< std::string >> &&)
void setValues (const std::map< App::DocumentObject *, std::vector< std::string >> &)
void addValue (App::DocumentObject *obj, const std::vector< std::string > &SubList={}, bool reset=false)
void addValue (App::DocumentObject *obj, std::vector< std::string > &&SubList={}, bool reset=false)
void setValue (App::DocumentObject *lValue, const std::vector< std::string > &SubList={})
setValue: PropertyLinkSub-compatible overload
std::vector< DocumentObject * > getValues () const
const std::string getPyReprString () const
DocumentObject * getValue () const
const std::vector< std::string > & getSubValues (App::DocumentObject *obj) const
std::vector< std::string > getSubValues (App::DocumentObject *obj, bool newStyle) const
const std::vector< ShadowSub > & getShadowSubs (App::DocumentObject *obj) const
int removeValue (App::DocumentObject *lValue)
Removes all occurrences of lValue in the property together with its sub-elements and returns the number of entries removed.
void setSubListValues (const std::vector< PropertyLinkSubList::SubSet > &)
const std::list< PropertyXLinkSub > & getSubListValues () const
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
Property * Copy () const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
const char * getEditorName () const override
Get the class name of the associated property editor item.
Property * CopyOnImportExternal (const std::map< std::string, std::string > &nameMap) const override
Property * CopyOnLabelChange (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const override
Property * CopyOnLinkReplace (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const override
unsigned int getMemSize () const override
void updateElementReference (DocumentObject *feature, bool reverse=false, bool notify=false) override
bool referenceChanged () const override
Test if the element reference has changed after restore.
void getLinks (std::vector< App::DocumentObject * > &objs, bool all=false, std::vector< std::string > *subs=nullptr, bool newStyle=true) const override
void getLinksTo (std::vector< App::ObjectIdentifier > &identifiers, App::DocumentObject *obj, const char *subname=nullptr, bool all=false) const override
void breakLink (App::DocumentObject *obj, bool clear) override
bool adjustLink (const std::set< App::DocumentObject * > &inList) override
bool upgrade (Base::XMLReader &reader, const char *typeName)
int checkRestore (std::string *msg=nullptr) const override
void setAllowPartial (bool enable) override
void hasSetChildValue (Property &) override
Called when a child property has changed value.
void aboutToSetChildValue (Property &) override
Called before a child property changing value.
void setSyncSubObject (bool enable)
Public Member Functions inherited from App::PropertyLinkBase
PropertyLinkBase ()
~PropertyLinkBase () override
void unregisterElementReference ()
Clear internal element reference registration.
void registerLabelReferences (std::vector< std::string > &&labels, bool reset=true)
void checkLabelReferences (const std::vector< std::string > &subs, bool reset=true)
void unregisterLabelReferences ()
Clear internal label references registration.
std::vector< App::DocumentObject * > linkedObjects (bool all=false) const
Helper function to return all linked objects of this property.
template<class T >
void getLinkedObjects (T &inserter, bool all=false) const
Helper function to return linked objects using an std::inserter.
void getLinkedElements (std::map< App::DocumentObject *, std::vector< std::string >> &elements, bool newStyle=true, bool all=false) const
Helper function to return a map of linked object and its subname references.
std::map< App::DocumentObject *, std::vector< std::string > > linkedElements (bool newStyle=true, bool all=false) const
Helper function to return a map of linked object and its subname references.
bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
void setAllowExternal (bool allow)
bool _updateElementReference (App::DocumentObject *feature, App::DocumentObject *obj, std::string &sub, ShadowSub &shadow, bool reverse, bool notify=false)
void _registerElementReference (App::DocumentObject *obj, std::string &sub, ShadowSub &shadow)
bool testFlag (int flag) const
void setReturnNewElement (bool enable)
void setSilentRestore (bool enable)
Public Member Functions inherited from App::Property
Property ()
~Property () override
const char * getName () const
bool hasName () const
std::string getFullName () const
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
int64_t getID () const
virtual void beforeSave () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::ScopedLink
void setScope (LinkScope scope)
Set the links scope Allows to define what kind of links are allowed. Only in the Local GeoFeatureGroup, in this and all Childs or to all objects within the Glocal scope.
LinkScope getScope () const
Get the links scope Retrieve what kind of links are allowed. Only in the Local GeoFeatureGroup, in this and all Childs or to all objects within the Glocal scope.
Additional Inherited Members
Public Types inherited from App::PropertyXLinkSubList
using atomic_change = typename AtomicPropertyChangeInterface< PropertyXLinkSubList >::AtomicPropertyChange
Public Types inherited from App::PropertyLinkBase
enum LinkFlags {
LinkAllowExternal, LinkDetached, LinkRestoring, LinkAllowPartial,
LinkRestoreLabel, LinkSyncSubObject, LinkNewElement, LinkSilentRestore
}
using ShadowSub = ElementNamePair
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Static Public Member Functions inherited from App::PropertyLinkBase
static std::pair< App::DocumentObject *, std::string > tryReplaceLink (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const char *sub=nullptr)
Helper functions.
static std::pair< App::DocumentObject *, std::vector< std::string > > tryReplaceLinkSubs (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const std::vector< std::string > &subs)
static void updateElementReferences (DocumentObject *feature, bool reverse=false)
Update all element references in all link properties of feature.
static const std::unordered_set< PropertyLinkBase * > & getElementReferences (DocumentObject *)
Obtain link properties that contain element references to a given object.
static void breakLinks (App::DocumentObject *link, const std::vector< App::DocumentObject * > &objs, bool clear)
static std::string tryImportSubName (const App::DocumentObject *obj, const char *sub, const App::Document *doc, const std::map< std::string, std::string > &nameMap)
static App::DocumentObject * tryImport (const App::Document *doc, const App::DocumentObject *obj, const std::map< std::string, std::string > &nameMap)
static const char * exportSubName (std::string &output, const App::DocumentObject *obj, const char *subname, bool first_obj=false)
static std::string importSubName (Base::XMLReader &reader, const char *sub, bool &restoreLabel)
static void restoreLabelReference (const App::DocumentObject *obj, std::string &sub, ShadowSub *shadow=nullptr)
static void getLabelReferences (std::vector< std::string > &labels, const char *subname)
static std::vector< std::pair< Property *, std::unique_ptr< Property > > > updateLabelReferences (App::DocumentObject *obj, const char *newLabel)
static std::string updateLabelReference (const App::DocumentObject *linked, const char *subname, App::DocumentObject *obj, const std::string &ref, const char *newLabel)
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::PropertyXLinkSubList
friend atomic_change
Public Attributes inherited from App::PropertyLinkBase
boost::signals2::signal< void(const std::string &, const std::string &)> signalUpdateElementReference
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::PropertyXLinkSubList
void _getLinksToList (std::vector< App::ObjectIdentifier > &identifiers, App::DocumentObject *obj, const char *subname, const std::vector< std::string > &subs, const std::vector< PropertyLinkBase::ShadowSub > &shadows) const
Protected Member Functions inherited from App::PropertyLinkBase
void hasSetValue () override
Gets called by all setValue() methods after the value has changed.
void setFlag (int flag, bool value=true)
void _getLinksTo (std::vector< App::ObjectIdentifier > &identifiers, App::DocumentObject *obj, const char *subname, const std::vector< std::string > &subs, const std::vector< PropertyLinkBase::ShadowSub > &shadows) const
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue ()
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Protected Member Functions inherited from App::AtomicPropertyChangeInterface< PropertyXLinkSubList >
AtomicPropertyChangeInterface ()=default
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::PropertyXLinkSubList
std::list< PropertyXLinkSub > _Links
Protected Attributes inherited from App::PropertyLinkBase
std::bitset< 32 > _Flags
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::ScopedLink
LinkScope _pcScope = LinkScope::Local
Protected Attributes inherited from App::AtomicPropertyChangeInterface< PropertyXLinkSubList >
int signalCounter
bool hasChanged
Detailed Description
Link to one or more (sub)object(s) of one or more object(s) from the same or different document
The only difference for PropertyXLinkList and PropertyXLinkSubList is in their getPyObject(). PropertyXLinkList will return a list of object is there is no sub-object/sub-elements in the property.
Definition at line 1573 of file PropertyLinks.h.
Constructor & Destructor Documentation
PropertyXLinkList()
PropertyXLinkList::PropertyXLinkList () default
~PropertyXLinkList()
PropertyXLinkList::~PropertyXLinkList () override default
Member Function Documentation
getPyObject()
PyObject * PropertyXLinkList::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from App::PropertyXLinkSubList.
Definition at line 5610 of file PropertyLinks.cpp.
References App::PropertyXLinkSubList::_Links, App::DocumentObject::getPyObject(), App::PropertyXLinkSubList::getPyObject(), App::DocumentObject::isAttachedToDocument(), and Py::new_reference_to().
setPyObject()
void PropertyXLinkList::setPyObject (PyObject * value) override virtual
Reimplemented from App::PropertyXLinkSubList.
Definition at line 5633 of file PropertyLinks.cpp.
References App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyLinkBase::setAllowExternal(), App::PropertyListsT< T, ListT, ParentT >::setPyObject(), App::PropertyXLinkSubList::setPyObject(), and App::PropertyXLinkSubList::setValues().
The documentation for this class was generated from the following files:
PropertyLinks.h
PropertyLinks.cpp