FreeCAD: TechDraw::anglePoints Class Reference
TechDraw::anglePoints Class Reference
#include <DimensionGeometry.h>
Public Member Functions
anglePoints ()
anglePoints (const Base::Vector3d &apex, const Base::Vector3d &point0, Base::Vector3d point1)
anglePoints (const anglePoints &ap)
anglePoints & operator= (const anglePoints &ap)
pointPair ends () const
void ends (const pointPair &newEnds)
Base::Vector3d first () const
void first (const Base::Vector3d &newFirst)
Base::Vector3d second () const
void second (const Base::Vector3d &newSecond)
Base::Vector3d vertex () const
void vertex (const Base::Vector3d &newVertex)
void move (const Base::Vector3d &offset)
void project (const DrawViewPart *dvp)
void mapToPage (const DrawViewPart *dvp)
void invertY ()
void dump (const std::string &text) const
anglePoints toCanonicalForm (DrawViewPart *dvp) const
anglePoints toDisplayForm (DrawViewPart *dvp) const
Detailed Description
Definition at line 117 of file DimensionGeometry.h.
Constructor & Destructor Documentation
anglePoints() [1/3]
anglePoints::anglePoints ()
Definition at line 158 of file DimensionGeometry.cpp.
References TechDraw::pointPair::first(), and TechDraw::pointPair::second().
anglePoints() [2/3]
TechDraw::anglePoints::anglePoints (const Base::Vector3d & apex, const Base::Vector3d & point0, Base::Vector3d point1) inline
Definition at line 121 of file DimensionGeometry.h.
anglePoints() [3/3]
anglePoints::anglePoints (const anglePoints & ap)
Definition at line 165 of file DimensionGeometry.cpp.
Member Function Documentation
dump()
void anglePoints::dump (const std::string & text) const
Definition at line 233 of file DimensionGeometry.cpp.
References Base::Console(), first(), TechDraw::DrawUtil::formatVector(), Base::ConsoleSingleton::Message(), second(), and vertex().
ends() [1/2]
pointPair TechDraw::anglePoints::ends () const inline
Definition at line 127 of file DimensionGeometry.h.
Referenced by operator=().
ends() [2/2]
void TechDraw::anglePoints::ends (const pointPair & newEnds) inline
Definition at line 128 of file DimensionGeometry.h.
first() [1/2]
Base::Vector3d TechDraw::anglePoints::first () const inline
Definition at line 129 of file DimensionGeometry.h.
Referenced by TechDrawGui::QGIViewDimension::drawAngle(), dump(), TechDraw::DrawViewDimension::getAnglePointsTwoEdges(), and TechDraw::DrawViewDimension::getProjectedDimValue().
first() [2/2]
void TechDraw::anglePoints::first (const Base::Vector3d & newFirst) inline
Definition at line 130 of file DimensionGeometry.h.
invertY()
void anglePoints::invertY ()
Definition at line 203 of file DimensionGeometry.cpp.
References TechDraw::pointPair::invertY(), and TechDraw::DrawUtil::invertY().
mapToPage()
void anglePoints::mapToPage (const DrawViewPart * dvp)
Definition at line 190 of file DimensionGeometry.cpp.
References TechDraw::DrawViewPart::getRotatedCS(), TechDraw::pointPair::mapToPage(), TechDraw::DrawUtil::togp_Vec(), and TechDraw::DrawUtil::toVector3d().
move()
void anglePoints::move (const Base::Vector3d & offset)
Definition at line 175 of file DimensionGeometry.cpp.
References TechDraw::pointPair::move().
Referenced by TechDraw::DrawViewDimension::getAnglePointsThreeVerts(), and TechDraw::DrawViewDimension::getAnglePointsTwoEdges().
operator=()
anglePoints & anglePoints::operator= (const anglePoints & ap)
Definition at line 167 of file DimensionGeometry.cpp.
References ends(), and vertex().
project()
void anglePoints::project (const DrawViewPart * dvp)
Definition at line 182 of file DimensionGeometry.cpp.
References TechDraw::DrawView::getScale(), TechDraw::pointPair::project(), and TechDraw::DrawViewPart::projectPoint().
Referenced by TechDraw::DrawViewDimension::getAnglePointsThreeVerts(), and TechDraw::DrawViewDimension::getAnglePointsTwoEdges().
second() [1/2]
Base::Vector3d TechDraw::anglePoints::second () const inline
Definition at line 131 of file DimensionGeometry.h.
Referenced by TechDrawGui::QGIViewDimension::drawAngle(), dump(), TechDraw::DrawViewDimension::getAnglePointsTwoEdges(), and TechDraw::DrawViewDimension::getProjectedDimValue().
second() [2/2]
void TechDraw::anglePoints::second (const Base::Vector3d & newSecond) inline
Definition at line 132 of file DimensionGeometry.h.
toCanonicalForm()
anglePoints anglePoints::toCanonicalForm (DrawViewPart * dvp) const
return unscaled, unrotated version of this anglePoints. caller is responsible for for ensuring this anglePoints is in scaled, rotated form before calling this method.
Definition at line 211 of file DimensionGeometry.cpp.
References TechDraw::CosmeticVertex::makeCanonicalPoint(), result, and TechDraw::pointPair::toCanonicalForm().
toDisplayForm()
anglePoints anglePoints::toDisplayForm (DrawViewPart * dvp) const
return scaled and rotated version of this anglePoints. caller is responsible for for ensuring this anglePoints is in canonical form before calling this method.
Definition at line 221 of file DimensionGeometry.cpp.
References TechDraw::DrawView::getScale(), App::PropertyQuantity::getValue(), result, TechDraw::DrawView::Rotation, TechDraw::pointPair::toDisplayForm(), and Base::toRadians().
vertex() [1/2]
Base::Vector3d TechDraw::anglePoints::vertex () const inline
Definition at line 133 of file DimensionGeometry.h.
Referenced by TechDrawGui::QGIViewDimension::drawAngle(), dump(), TechDraw::DrawViewDimension::getAnglePointsTwoEdges(), TechDraw::DrawViewDimension::getProjectedDimValue(), and operator=().
vertex() [2/2]
void TechDraw::anglePoints::vertex (const Base::Vector3d & newVertex) inline
Definition at line 134 of file DimensionGeometry.h.
The documentation for this class was generated from the following files:
DimensionGeometry.h
DimensionGeometry.cpp