FreeCAD: CustomGLWidget Class Reference
CustomGLWidget Class Reference
Public Member Functions
CustomGLWidget (const QSurfaceFormat &format, QWidget *parent=nullptr, const QOpenGLWidget *shareWidget=nullptr, Qt::WindowFlags f=Qt::WindowFlags())
~CustomGLWidget () override=default
void initializeGL () override
void paintGL () override
bool event (QEvent *e) override
void handleLoggedMessage (const QOpenGLDebugMessage &message)
void showEvent (QShowEvent *) override
void slotResized ()
Public Attributes
QSurfaceFormat myFormat
Detailed Description
Definition at line 146 of file QuarterWidget.cpp.
Constructor & Destructor Documentation
CustomGLWidget()
CustomGLWidget::CustomGLWidget (const QSurfaceFormat & format, QWidget * parent = nullptr, const QOpenGLWidget * shareWidget = nullptr, Qt::WindowFlags f = Qt::WindowFlags()) inline
Definition at line 150 of file QuarterWidget.cpp.
~CustomGLWidget()
CustomGLWidget::~CustomGLWidget () override default
Member Function Documentation
event()
bool CustomGLWidget::event (QEvent * e) inline override
Definition at line 200 of file QuarterWidget.cpp.
References SCL.SimpleDataTypes::e.
handleLoggedMessage()
void CustomGLWidget::handleLoggedMessage (const QOpenGLDebugMessage & message) inline
Definition at line 218 of file QuarterWidget.cpp.
Referenced by initializeGL().
initializeGL()
void CustomGLWidget::initializeGL () inline override
Definition at line 169 of file QuarterWidget.cpp.
References draftgeoutils.intersections::connect(), handleLoggedMessage(), and slotResized().
paintGL()
void CustomGLWidget::paintGL () inline override
Definition at line 192 of file QuarterWidget.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::redraw().
showEvent()
void CustomGLWidget::showEvent (QShowEvent *) inline override
Definition at line 222 of file QuarterWidget.cpp.
slotResized()
void CustomGLWidget::slotResized () inline
Definition at line 226 of file QuarterWidget.cpp.
Referenced by initializeGL().
Member Data Documentation
myFormat
QSurfaceFormat CustomGLWidget::myFormat
Definition at line 148 of file QuarterWidget.cpp.
The documentation for this class was generated from the following file:
QuarterWidget.cpp