FreeCAD: Gui::LocationWidget Class Reference
Gui::LocationWidget Class Reference
#include <InputVector.h>
Public Member Functions
LocationWidget (QWidget *parent=nullptr)
~LocationWidget () override
QSize sizeHint () const override
Base::Vector3d getPosition () const
void setPosition (const Base::Vector3d &)
void setDirection (const Base::Vector3d &dir)
Base::Vector3d getDirection () const
Base::Vector3d getUserDirection (bool *ok=nullptr) const
Detailed Description
Definition at line 40 of file InputVector.h.
Constructor & Destructor Documentation
LocationWidget()
LocationWidget::LocationWidget (QWidget * parent = nullptr)
Definition at line 38 of file InputVector.cpp.
References draftgeoutils.intersections::connect(), SCL.SimpleDataTypes::e, Base::Unit::Length, Gui::QuantitySpinBox::setMaximum(), Gui::QuantitySpinBox::setMinimum(), and Gui::QuantitySpinBox::setUnit().
~LocationWidget()
LocationWidget::~LocationWidget () override default
Member Function Documentation
getDirection()
Base::Vector3d LocationWidget::getDirection () const
Definition at line 170 of file InputVector.cpp.
getPosition()
Base::Vector3d LocationWidget::getPosition () const
Definition at line 128 of file InputVector.cpp.
References Base::Quantity::getValue(), and Gui::QuantitySpinBox::value.
getUserDirection()
Base::Vector3d LocationWidget::getUserDirection (bool * ok = nullptr) const
Definition at line 181 of file InputVector.cpp.
References Base::UnitsApi::getDecimals(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
setDirection()
void LocationWidget::setDirection (const Base::Vector3d & dir)
Definition at line 142 of file InputVector.cpp.
References femsolver.report::display(), Base::Vector3< double >::epsilon(), SplineSurface::i, Base::Vector3< float_type >::Length(), toolbit-attributes::val, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
setPosition()
void LocationWidget::setPosition (const Base::Vector3d & v)
Definition at line 135 of file InputVector.cpp.
References Gui::QuantitySpinBox::setValue(), and TestSpreadsheet::v.
sizeHint()
QSize LocationWidget::sizeHint () const override
Definition at line 84 of file InputVector.cpp.
The documentation for this class was generated from the following files:
InputVector.h
InputVector.cpp