FreeCAD: TechDrawGui::QGIViewImage Class Reference
TechDrawGui::QGIViewImage Class Reference
#include <QGIViewImage.h>
Public Types
enum { Type = QGraphicsItem::UserType + 200 }
Public Types inherited from TechDrawGui::QGIView
enum { Type = QGraphicsItem::UserType + 101 }
Public Member Functions
QGIViewImage ()
~QGIViewImage () override
int type () const override
void updateView (bool update=false) override
void setViewImageFeature (TechDraw::DrawViewImage *obj)
void draw () override
void rotateView () override
Public Member Functions inherited from TechDrawGui::QGIView
QGIView ()
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
const char * getViewName () const
const std::string getViewNameAsString () const
void setViewFeature (TechDraw::DrawView *obj)
TechDraw::DrawView * getViewObject () const
MDIViewPage * getMDIViewPage () const
double getScale ()
void hideFrame ()
virtual bool getFrameState ()
virtual void toggleCache (bool state)
virtual void drawBorder ()
virtual void isVisible (bool state)
virtual bool isVisible ()
virtual bool getGroupSelection ()
virtual void setGroupSelection (bool isSelected)
virtual void setGroupSelection (bool isSelected, const std::vector< std::string > &subNames)
virtual void drawCaption ()
void makeMark (double xPos, double yPos, QColor color=Qt::red)
void makeMark (Base::Vector3d pos, QColor color=Qt::red)
void makeMark (QPointF pos, QColor color=Qt::red)
void setPosition (qreal xPos, qreal yPos)
qreal getY ()
bool isInnerView () const
void isInnerView (bool state)
QGIViewClip * getClipGroup ()
bool isSnapping ()
void snapPosition (QPointF &position)
void snapSectionView (const TechDraw::DrawViewSection *sectionView, QPointF &newPosition)
Base::Vector3d projItemPagePos (TechDraw::DrawViewPart *item)
void alignTo (QGraphicsItem *, const QString &alignment)
QColor prefNormalColor ()
QColor getNormalColor ()
void setNormalColor (QColor color)
QColor getPreColor ()
QColor getSelectColor ()
QColor getCurrentColor ()
void setCurrentColor (QColor color)
QColor getSettingColor ()
void setSettingColor (QColor color)
virtual void setStack (int z)
virtual void setStackFromVP ()
QFont getFont ()
void setFont (QFont font)
virtual void removeChild (QGIView *child)
virtual void addArbitraryItem (QGraphicsItem *qgi)
virtual void switchParentItem (QGIView *targetParent)
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
Protected Member Functions
virtual void drawImage ()
Protected Member Functions inherited from TechDrawGui::QGIView
QGIView * getQGIVByName (std::string name)
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QRectF customChildrenBoundingRect () const
void dumpRect (const char *text, QRectF rect)
Base::Reference< ParameterGrp > getParmGroupCol ()
Protected Attributes
QGCustomImage * m_imageItem
QGCustomClip * m_cliparea
Additional Inherited Members
Static Public Member Functions inherited from TechDrawGui::QGIView
static Gui::ViewProvider * getViewProvider (App::DocumentObject *obj)
static ViewProviderPage * getViewProviderPage (TechDraw::DrawView *dView)
static int calculateFontPixelSize (double sizeInMillimetres)
static int calculateFontPixelWidth (const QFont &font)
static QString getPrefFont ()
static double getPrefFontSize ()
static double getDimFontSize ()
static int exactFontSize (std::string fontFamily, double nominalSize)
Static Public Attributes inherited from TechDrawGui::QGIView
static const double DefaultFontSizeInMM = 5.0
Detailed Description
Definition at line 39 of file QGIViewImage.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 45 of file QGIViewImage.h.
Constructor & Destructor Documentation
QGIViewImage()
QGIViewImage::QGIViewImage ()
Definition at line 44 of file QGIViewImage.cpp.
References TechDrawGui::QGCustomClip::centerAt(), TechDrawGui::QGCustomImage::centerAt(), m_cliparea, m_imageItem, and TechDrawGui::QGCustomClip::setRect().
~QGIViewImage()
QGIViewImage::~QGIViewImage () override
Definition at line 65 of file QGIViewImage.cpp.
Member Function Documentation
draw()
void QGIViewImage::draw () override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 96 of file QGIViewImage.cpp.
References TechDrawGui::QGCustomClip::centerAt(), TechDrawGui::ViewProviderImage::Crop, drawImage(), App::PropertyBool::getValue(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), TechDrawGui::Rez::guiX(), TechDrawGui::QGCustomImage::imageSize(), TechDrawGui::QGIView::isVisible(), m_cliparea, m_imageItem, and TechDrawGui::QGCustomClip::setRect().
Referenced by updateView().
drawImage()
void QGIViewImage::drawImage () protected virtual
Definition at line 124 of file QGIViewImage.cpp.
References TechDrawGui::QGCustomImage::centerAt(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGCustomImage::load(), m_cliparea, m_imageItem, and TechDrawGui::QGCustomClip::rect().
Referenced by draw().
rotateView()
void QGIViewImage::rotateView () override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 142 of file QGIViewImage.cpp.
References TechDrawGui::QGCustomClip::boundingRect(), App::PropertyQuantity::getValue(), TechDrawGui::QGIView::getViewObject(), m_cliparea, and TechDraw::DrawView::Rotation.
setViewImageFeature()
void QGIViewImage::setViewImageFeature (TechDraw::DrawViewImage * obj)
Definition at line 70 of file QGIViewImage.cpp.
References TechDrawGui::QGIView::setViewFeature().
type()
int TechDrawGui::QGIViewImage::type () const inline override
Definition at line 46 of file QGIViewImage.h.
updateView()
void QGIViewImage::updateView (bool update = false) override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 75 of file QGIViewImage.cpp.
References draw(), TechDrawGui::QGIView::getViewObject(), and TechDrawGui::QGIView::updateView().
Member Data Documentation
m_cliparea
QGCustomClip* TechDrawGui::QGIViewImage::m_cliparea protected
Definition at line 58 of file QGIViewImage.h.
Referenced by draw(), drawImage(), QGIViewImage(), and rotateView().
m_imageItem
QGCustomImage* TechDrawGui::QGIViewImage::m_imageItem protected
Definition at line 57 of file QGIViewImage.h.
Referenced by draw(), drawImage(), and QGIViewImage().
The documentation for this class was generated from the following files:
QGIViewImage.h
QGIViewImage.cpp