FreeCAD: FemGui::DlgSettingsFemElmerImp Class Reference
FemGui::DlgSettingsFemElmerImp Class Reference
#include <DlgSettingsFemElmerImp.h>
Public Member Functions
DlgSettingsFemElmerImp (QWidget *parent=nullptr)
~DlgSettingsFemElmerImp () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Slots
void onfileNameChanged (QString FileName)
void onfileNameChangedMT (QString FileName)
void onCoresValueChanged (int cores)
Protected Member Functions
void saveSettings () override
void loadSettings () override
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
Definition at line 57 of file DlgSettingsFemElmerImp.h.
Constructor & Destructor Documentation
DlgSettingsFemElmerImp()
DlgSettingsFemElmerImp::DlgSettingsFemElmerImp (QWidget * parent = nullptr) explicit
Definition at line 37 of file DlgSettingsFemElmerImp.cpp.
References draftgeoutils.intersections::connect(), Gui::FileChooser::fileNameChanged(), onCoresValueChanged(), onfileNameChanged(), and onfileNameChangedMT().
~DlgSettingsFemElmerImp()
DlgSettingsFemElmerImp::~DlgSettingsFemElmerImp () override default
Member Function Documentation
changeEvent()
void DlgSettingsFemElmerImp::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 98 of file DlgSettingsFemElmerImp.cpp.
References SCL.SimpleDataTypes::e.
loadSettings()
void DlgSettingsFemElmerImp::loadSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 81 of file DlgSettingsFemElmerImp.cpp.
onCoresValueChanged
void DlgSettingsFemElmerImp::onCoresValueChanged (int cores) protected slot
Definition at line 152 of file DlgSettingsFemElmerImp.cpp.
References onfileNameChangedMT().
Referenced by DlgSettingsFemElmerImp().
onfileNameChanged
void DlgSettingsFemElmerImp::onfileNameChanged (QString FileName) protected slot
Definition at line 108 of file DlgSettingsFemElmerImp.cpp.
Referenced by DlgSettingsFemElmerImp().
onfileNameChangedMT
void DlgSettingsFemElmerImp::onfileNameChangedMT (QString FileName) protected slot
Definition at line 119 of file DlgSettingsFemElmerImp.cpp.
References Path.Log::warning().
Referenced by DlgSettingsFemElmerImp(), and onCoresValueChanged().
saveSettings()
void DlgSettingsFemElmerImp::saveSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 67 of file DlgSettingsFemElmerImp.cpp.
The documentation for this class was generated from the following files:
DlgSettingsFemElmerImp.h
DlgSettingsFemElmerImp.cpp