FreeCAD: ifc2x3.ifccomplexproperty Class Reference
ifc2x3.ifccomplexproperty Class Reference
Public Member Functions
def __init__ (self, inherited0__name, inherited1__description, usagename, hasproperties)
def usagename ()
def hasproperties ()
def wr21 (self)
def wr22 (self)
Public Member Functions inherited from ifc2x3.ifcproperty
def __init__ (self, name, description)
def name ()
def description ()
def propertyfordependance ()
def propertydependson ()
def partofcomplex ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
usagename
hasproperties
Public Attributes inherited from ifc2x3.ifcproperty
name
description
Detailed Description
Entity ifccomplexproperty definition.
:param usagename
:type usagename:ifcidentifier
:param hasproperties
:type hasproperties:SET(1,None,'ifcproperty', scope = schema_scope)
Definition at line 8253 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifccomplexproperty.__init__ (self, inherited0__name, inherited1__description, usagename, hasproperties)
Definition at line 8262 of file ifc2x3.py.
Member Function Documentation
hasproperties()
def ifc2x3.ifccomplexproperty.hasproperties ()
Definition at line 8282 of file ifc2x3.py.
References ifc2x3.ifccomplexproperty._hasproperties, SCL.TypeChecker.check_type(), and ifc2x3.ifccomplexproperty.hasproperties.
usagename()
def ifc2x3.ifccomplexproperty.usagename ()
Definition at line 8268 of file ifc2x3.py.
References ifc2x3.ifccomplexproperty._usagename, SCL.TypeChecker.check_type(), and ifc2x3.ifccomplexproperty.usagename.
wr21()
def ifc2x3.ifccomplexproperty.wr21 (self)
Definition at line 8294 of file ifc2x3.py.
References SCL.Builtin.SIZEOF().
Referenced by ifc4.ifcphmeasure.__init__().
wr22()
def ifc2x3.ifccomplexproperty.wr22 (self)
Definition at line 8301 of file ifc2x3.py.
References ifc2x3.ifccomplexproperty.hasproperties, and ifc2x3.ifcuniquepropertyname().
Member Data Documentation
hasproperties
ifc2x3.ifccomplexproperty.hasproperties
Definition at line 8265 of file ifc2x3.py.
Referenced by ifc2x3.ifccomplexproperty.hasproperties(), ifc4.ifcpropertyset.uniquepropertynames(), ifc2x3.ifccomplexproperty.wr22(), ifc4.ifccomplexproperty.wr22(), and ifc2x3.ifcpropertyset.wr32().
usagename
ifc2x3.ifccomplexproperty.usagename
Definition at line 8264 of file ifc2x3.py.
Referenced by ifc2x3.ifccomplexproperty.usagename().
The documentation for this class was generated from the following file:
ifc2x3.py