FreeCAD: AreaClipper.cpp File Reference
AreaClipper.cpp File Reference
#include "Area.h"
#include "clipper.hpp"
Classes
class DoubleAreaPoint
Macros
#define TPolygon Path
#define TPolyPolygon Paths
Functions
static void AddPoint (const DoubleAreaPoint &p)
static void AddVertex (const CVertex &vertex, const CVertex *prev_vertex)
static void MakeLoop (const DoubleAreaPoint &pt0, const DoubleAreaPoint &pt1, const DoubleAreaPoint &pt2, double radius)
static void OffsetWithLoops (const Paths &pp, Paths &pp_new, double inwards_value)
static void MakeObround (const Point &pt0, const CVertex &vt1, double radius)
static void OffsetSpansWithObrounds (const CArea &area, Paths &pp_new, double radius)
static void MakePoly (const CCurve &curve, Path &p, bool reverse=false)
static void MakePolyPoly (const CArea &area, Paths &pp, bool reverse=true)
static void SetFromResult (CCurve &curve, Path &p, bool reverse=true, bool is_closed=true)
static void SetFromResult (CArea &area, Paths &pp, bool reverse=true, bool is_closed=true, bool clear=true)
void UnFitArcs (CCurve &curve)
Variables
static std::list< DoubleAreaPoint > pts_for_AddVertex
Macro Definition Documentation
TPolygon
#define TPolygon Path
Definition at line 9 of file AreaClipper.cpp.
TPolyPolygon
#define TPolyPolygon Paths
Definition at line 10 of file AreaClipper.cpp.
Function Documentation
AddPoint()
static void AddPoint (const DoubleAreaPoint & p) static
Definition at line 43 of file AreaClipper.cpp.
References buildPsets::p, and pts_for_AddVertex.
Referenced by AddVertex().
AddVertex()
static void AddVertex (const CVertex & vertex, const CVertex * prev_vertex) static
Definition at line 48 of file AreaClipper.cpp.
References KDL::acos(), AddPoint(), KDL::atan2(), KDL::cos(), SplineSurface::i, CArea::m_accuracy, CVertex::m_c, CArea::m_min_arc_points, CVertex::m_p, CVertex::m_type, CArea::m_units, PI, KDL::sin(), KDL::sqrt(), Point::x, and Point::y.
Referenced by MakeLoop(), MakeObround(), MakePoly(), and UnFitArcs().
MakeLoop()
static void MakeLoop (const DoubleAreaPoint & pt0, const DoubleAreaPoint & pt1, const DoubleAreaPoint & pt2, double radius) static
Definition at line 131 of file AreaClipper.cpp.
References AddVertex(), CArea::m_units, Point::normalize(), draftgeoutils.general::v1(), DoubleAreaPoint::X, Point::x, DoubleAreaPoint::Y, and Point::y.
Referenced by OffsetWithLoops().
MakeObround()
static void MakeObround (const Point & pt0, const CVertex & vt1, double radius) static
Definition at line 243 of file AreaClipper.cpp.
References AddVertex(), Span::GetVector(), CVertex::m_c, CVertex::m_p, CVertex::m_type, CArea::m_units, Point::normalize(), draftgeoutils.general::v1(), Point::x, and Point::y.
Referenced by OffsetSpansWithObrounds().
MakePoly()
static void MakePoly (const CCurve & curve, Path & p, bool reverse = false) static
Definition at line 325 of file AreaClipper.cpp.
References AddVertex(), SplineSurface::i, CCurve::IsClosed(), CCurve::m_vertices, buildPsets::p, and pts_for_AddVertex.
Referenced by MakePolyPoly(), CArea::PopulateClipper(), and CArea::UniteCurves().
MakePolyPoly()
static void MakePolyPoly (const CArea & area, Paths & pp, bool reverse = true) static
Definition at line 367 of file AreaClipper.cpp.
References CArea::m_curves, MakePoly(), and TPolygon.
Referenced by CArea::Intersect(), CArea::Offset(), CArea::OffsetWithClipper(), CArea::Subtract(), CArea::Union(), and CArea::Xor().
OffsetSpansWithObrounds()
static void OffsetSpansWithObrounds (const CArea & area, Paths & pp_new, double radius) static
Definition at line 271 of file AreaClipper.cpp.
References SCL.SimpleDataTypes::c, SplineSurface::i, CArea::m_clipper_simple, CArea::m_curves, CVertex::m_p, CCurve::m_vertices, MakeObround(), buildPsets::p, pts_for_AddVertex, TPolygon, and TPolyPolygon.
Referenced by CArea::Thicken().
OffsetWithLoops()
static void OffsetWithLoops (const Paths & pp, Paths & pp_new, double inwards_value) static
Definition at line 161 of file AreaClipper.cpp.
References SCL.SimpleDataTypes::c, SplineSurface::i, CArea::m_clipper_simple, MakeLoop(), buildPsets::p, pts_for_AddVertex, TPolygon, and TPolyPolygon.
Referenced by CArea::Offset().
SetFromResult() [1/2]
static void SetFromResult (CArea & area, Paths & pp, bool reverse = true, bool is_closed = true, bool clear = true) static
Definition at line 410 of file AreaClipper.cpp.
References Path.Op.Gui.Selection::clear(), SplineSurface::i, CArea::m_curves, buildPsets::p, SetFromResult(), and TPolygon.
SetFromResult() [2/2]
static void SetFromResult (CCurve & curve, Path & p, bool reverse = true, bool is_closed = true) static
Definition at line 378 of file AreaClipper.cpp.
References ClipperLib::CleanPolygon(), CCurve::FitArcs(), CArea::m_clipper_clean_distance, CArea::m_fit_arcs, CArea::m_units, CCurve::m_vertices, buildPsets::p, Point::tolerance, DoubleAreaPoint::X, and DoubleAreaPoint::Y.
Referenced by CArea::Clip(), CArea::Intersect(), CArea::Offset(), CArea::OffsetWithClipper(), SetFromResult(), CArea::Subtract(), CArea::Thicken(), CArea::Union(), CArea::UniteCurves(), and CArea::Xor().
UnFitArcs()
void UnFitArcs (CCurve & curve)
Definition at line 600 of file AreaClipper.cpp.
References AddVertex(), CArea::m_units, CCurve::m_vertices, pts_for_AddVertex, DoubleAreaPoint::X, and DoubleAreaPoint::Y.
Variable Documentation
pts_for_AddVertex
std::list<DoubleAreaPoint> pts_for_AddVertex static
Definition at line 41 of file AreaClipper.cpp.
Referenced by AddPoint(), MakePoly(), OffsetSpansWithObrounds(), OffsetWithLoops(), and UnFitArcs().