FreeCAD: PartGui::TaskDlgAttacher Class Reference
PartGui::TaskDlgAttacher Class Reference
simulation dialog for the TaskView
#include <TaskAttacher.h>
Public Member Functions
TaskDlgAttacher (Gui::ViewProviderDocumentObject *ViewProvider, bool createBox=true)
~TaskDlgAttacher () override
Gui::ViewProviderDocumentObject * getViewProvider () const
void open () override
is called the TaskView when the dialog is opened
void clicked (int) override
is called by the framework if an button is clicked which has no accept or reject role
bool accept () override
is called by the framework if the dialog is accepted (Ok)
bool reject () override
is called by the framework if the dialog is rejected (Cancel)
bool isAllowedAlterDocument () const override
is called by the framework if the user presses the help button
QDialogButtonBox::StandardButtons getStandardButtons () const override
returns for Close and Help button
Public Member Functions inherited from Gui::TaskView::TaskDialog
TaskDialog ()
~TaskDialog () override
QWidget * addTaskBox (QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBox (const QPixmap &icon, QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBoxWithoutHeader (QWidget *widget)
void setButtonPosition (ButtonPosition p)
ButtonPosition buttonPosition () const
const std::vector< QWidget * > & getDialogContent () const
bool canClose () const
virtual void modifyStandardButtons (QDialogButtonBox *)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
bool isEscapeButtonEnabled () const
void setAutoCloseOnTransactionChange (bool on)
bool isAutoCloseOnTransactionChange () const
void setAutoCloseOnDeletedDocument (bool on)
bool isAutoCloseOnDeletedDocument () const
const std::string & getDocumentName () const
void setDocumentName (const std::string &doc)
void setAutoCloseOnClosedView (bool on)
bool isAutoCloseOnClosedView () const
void associateToObject3dView (App::DocumentObject *obj)
const Gui::MDIView * getAssociatedView () const
void setAssociatedView (const Gui::MDIView *view)
virtual bool isAllowedAlterView () const
virtual bool isAllowedAlterSelection () const
virtual bool needsFullSpace () const
virtual void closed ()
is called by the framework when the dialog is closed
virtual void autoClosedOnTransactionChange ()
virtual void autoClosedOnDeletedDocument ()
virtual void autoClosedOnClosedView ()
virtual void helpRequested ()
is called by the framework if the user press the help button
void emitDestructionSignal ()
Protected Attributes
Gui::ViewProviderDocumentObject * ViewProvider
TaskAttacher * parameter
Protected Attributes inherited from Gui::TaskView::TaskDialog
QPointer< QDialogButtonBox > buttonBox
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Detailed Description
simulation dialog for the TaskView
Definition at line 158 of file TaskAttacher.h.
Constructor & Destructor Documentation
TaskDlgAttacher()
TaskDlgAttacher::TaskDlgAttacher (Gui::ViewProviderDocumentObject * ViewProvider, bool createBox = true) explicit
Definition at line 1227 of file TaskAttacher.cpp.
References Gui::TaskView::TaskDialog::Content, parameter, and Gui::TaskView::TaskDialog::setDocumentName().
~TaskDlgAttacher()
TaskDlgAttacher::~TaskDlgAttacher () override default
Member Function Documentation
accept()
bool TaskDlgAttacher::accept () override virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
Reimplemented in PartDesignGui::TaskDlgDatumParameters.
Definition at line 1256 of file TaskAttacher.cpp.
References Part::AttachExtension::AttachmentOffset, Part::AttachExtension::AttachmentSupport, Gui::cmdAppObject(), Gui::cmdAppObjectArgs(), Gui::cmdGuiDocument(), Gui::Command::commitCommand(), toolbit-attributes::doc, SCL.SimpleDataTypes::e, Gui::TaskView::TaskDialog::getDocumentName(), App::ExtensionContainer::getExtensionByType(), Base::Placement::getPosition(), App::PropertyLinkSubList::getPyReprString(), Base::Placement::getRotation(), App::PropertyEnumeration::getValue(), App::PropertyPlacement::getValue(), App::PropertyFloat::getValue(), App::PropertyBool::getValue(), Base::Rotation::getYawPitchRoll(), Part::AttachExtension::MapMode, Part::AttachExtension::MapPathParameter, Part::AttachExtension::MapReversed, parameter, src.Mod.AddonManager.Addon::translate, Path.Log::warning(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by PartDesignGui::TaskDlgDatumParameters::accept().
clicked()
void TaskDlgAttacher::clicked (int) override virtual
is called by the framework if an button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 1251 of file TaskAttacher.cpp.
getStandardButtons()
QDialogButtonBox::StandardButtons PartGui::TaskDlgAttacher::getStandardButtons () const inline override virtual
returns for Close and Help button
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 184 of file TaskAttacher.h.
getViewProvider()
Gui::ViewProviderDocumentObject* PartGui::TaskDlgAttacher::getViewProvider () const inline
Definition at line 166 of file TaskAttacher.h.
Referenced by PartDesignGui::ViewProviderDatum::setEdit().
isAllowedAlterDocument()
bool PartGui::TaskDlgAttacher::isAllowedAlterDocument () const inline override virtual
is called by the framework if the user presses the help button
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 180 of file TaskAttacher.h.
open()
void TaskDlgAttacher::open () override virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 1244 of file TaskAttacher.cpp.
References Gui::Command::hasPendingCommand(), Gui::Command::openCommand(), and Arch::QT_TRANSLATE_NOOP.
reject()
bool TaskDlgAttacher::reject () override virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
Reimplemented in PartDesignGui::TaskDlgDatumParameters.
Definition at line 1296 of file TaskAttacher.cpp.
References Gui::Command::abortCommand(), toolbit-attributes::doc, Gui::Command::Doc, doCommand, Gui::TaskView::TaskDialog::getDocumentName(), and Gui::Command::Gui.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and PartDesignGui::TaskDlgDatumParameters::reject().
Member Data Documentation
parameter
TaskAttacher* PartGui::TaskDlgAttacher::parameter protected
Definition at line 190 of file TaskAttacher.h.
Referenced by PartDesignGui::TaskDlgDatumParameters::accept(), accept(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotAbortTransaction(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotActivateDocument(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::slotActivateDocument(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotAddedDynamicExtension(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotAppendDynamicProperty(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotBeforeAddingDynamicExtension(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotBeforeChangeDocument(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotBeforeChangeObject(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotChangedDocument(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotChangedObject(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::slotChangedObject(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotChangePropertyEditor(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotCommitTransaction(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotCreatedDocument(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::slotCreatedDocument(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotCreatedObject(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::slotCreatedObject(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotDeletedDocument(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::slotDeletedDocument(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotDeletedObject(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::slotDeletedObject(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotFinishSaveDocument(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::slotInEdit(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotOpenTransaction(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotRecomputedDocument(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotRecomputedObject(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotRedoDocument(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotRelabelDocument(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::slotRelabelDocument(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotRemoveDynamicProperty(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::slotRenameDocument(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::slotResetEdit(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotStartSaveDocument(), src.Mod.Test.Document.DocumentObserverCases.Observer::slotUndoDocument(), TaskDlgAttacher(), and PartDesignGui::TaskDlgDatumParameters::TaskDlgDatumParameters().
ViewProvider
Gui::ViewProviderDocumentObject* PartGui::TaskDlgAttacher::ViewProvider protected
Definition at line 188 of file TaskAttacher.h.
The documentation for this class was generated from the following files:
TaskAttacher.h
TaskAttacher.cpp