FreeCAD: MatGui::DlgDisplayPropertiesImp Class Reference
MatGui::DlgDisplayPropertiesImp Class Reference
#include <DlgDisplayPropertiesImp.h>
Classes
class Private
Public Member Functions
DlgDisplayPropertiesImp (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgDisplayPropertiesImp () override
void OnChange (Gui::SelectionSingleton::SubjectType &rCaller, Gui::SelectionSingleton::MessageType Reason) override
Observer message from the Selection.
void showDefaultButtons (bool)
void reject () override
Protected Member Functions
void changeEvent (QEvent *e) override
Detailed Description
The DlgDisplayPropertiesImp class implements a dialog containing all available document templates to create a new document.
Author
Jürgen Riegel
Definition at line 54 of file DlgDisplayPropertiesImp.h.
Constructor & Destructor Documentation
DlgDisplayPropertiesImp()
DlgDisplayPropertiesImp::DlgDisplayPropertiesImp (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Definition at line 138 of file DlgDisplayPropertiesImp.cpp.
References Base::Subject< MsgType >::Attach(), draftgeoutils.faces::bind(), Gui::Application::Instance, Gui::Selection(), and Gui::Application::signalChangedObject.
~DlgDisplayPropertiesImp()
DlgDisplayPropertiesImp::~DlgDisplayPropertiesImp () override
Definition at line 167 of file DlgDisplayPropertiesImp.cpp.
References Base::Subject< MsgType >::Detach(), and Gui::Selection().
Member Function Documentation
changeEvent()
void DlgDisplayPropertiesImp::changeEvent (QEvent * e) override protected
Definition at line 259 of file DlgDisplayPropertiesImp.cpp.
References SCL.SimpleDataTypes::e.
OnChange()
void MatGui::DlgDisplayPropertiesImp::OnChange (Gui::SelectionSingleton::SubjectType & rCaller, Gui::SelectionSingleton::MessageType Reason) override
Observer message from the Selection.
reject()
void DlgDisplayPropertiesImp::reject () override
Definition at line 367 of file DlgDisplayPropertiesImp.cpp.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and MatGui::TaskDisplayProperties::reject().
showDefaultButtons()
void MatGui::DlgDisplayPropertiesImp::showDefaultButtons (bool)
The documentation for this class was generated from the following files:
DlgDisplayPropertiesImp.h
DlgDisplayPropertiesImp.cpp