FreeCAD: Path.Post.scripts.dynapath_post Namespace Reference
Path.Post.scripts.dynapath_post Namespace Reference
Functions
def processArguments (argstring)
def export (objectslist, filename, argstring)
def linenumber ()
def parse (pathobj)
Variables
TOOLTIP
parser
prog
add_help
action = "store_true",
help = "don't pop up editor before writing output",
default
TOOLTIP_ARGS
now
OUTPUT_COMMENTS
OUTPUT_HEADER
OUTPUT_LINE_NUMBERS
SHOW_EDITOR
MODAL
COMMAND_SPACE
LINENR
UNIT_SPEED_FORMAT
UNIT_FORMAT
UNITS
MACHINE_NAME
CORNER_MIN
CORNER_MAX
PREAMBLE
POSTAMBLE
PRE_OPERATION
POST_OPERATION
TOOL_CHANGE
Function Documentation
export()
def Path.Post.scripts.dynapath_post.export (objectslist, filename, argstring)
Definition at line 194 of file dynapath_post.py.
References Path.Post.scripts.dynapath_post.linenumber(), Path.Post.scripts.dynapath_post.parse(), Path.Post.scripts.dynapath_post.processArguments(), and Path.Post.scripts.refactored_centroid_post.str.
linenumber()
def Path.Post.scripts.dynapath_post.linenumber ()
Definition at line 280 of file dynapath_post.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.dynapath_post.export(), and Path.Post.scripts.dynapath_post.parse().
parse()
def Path.Post.scripts.dynapath_post.parse (pathobj)
Definition at line 288 of file dynapath_post.py.
References Path.Post.scripts.dynapath_post.linenumber(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.dynapath_post.export().
processArguments()
def Path.Post.scripts.dynapath_post.processArguments (argstring)
Definition at line 151 of file dynapath_post.py.
Referenced by Path.Post.scripts.dynapath_post.export().
Variable Documentation
action
string Path.Post.scripts.dynapath_post.action = "store_true",
Definition at line 78 of file dynapath_post.py.
add_help
Path.Post.scripts.dynapath_post.add_help
Definition at line 77 of file dynapath_post.py.
COMMAND_SPACE
Path.Post.scripts.dynapath_post.COMMAND_SPACE
Definition at line 110 of file dynapath_post.py.
CORNER_MAX
Path.Post.scripts.dynapath_post.CORNER_MAX
Definition at line 120 of file dynapath_post.py.
CORNER_MIN
Path.Post.scripts.dynapath_post.CORNER_MIN
Definition at line 119 of file dynapath_post.py.
default
Path.Post.scripts.dynapath_post.default
Definition at line 86 of file dynapath_post.py.
help
string Path.Post.scripts.dynapath_post.help = "don't pop up editor before writing output",
Definition at line 78 of file dynapath_post.py.
LINENR
Path.Post.scripts.dynapath_post.LINENR
Definition at line 111 of file dynapath_post.py.
MACHINE_NAME
Path.Post.scripts.dynapath_post.MACHINE_NAME
Definition at line 118 of file dynapath_post.py.
MODAL
Path.Post.scripts.dynapath_post.MODAL
Definition at line 109 of file dynapath_post.py.
now
Path.Post.scripts.dynapath_post.now
Definition at line 102 of file dynapath_post.py.
OUTPUT_COMMENTS
Path.Post.scripts.dynapath_post.OUTPUT_COMMENTS
Definition at line 105 of file dynapath_post.py.
OUTPUT_HEADER
Path.Post.scripts.dynapath_post.OUTPUT_HEADER
Definition at line 106 of file dynapath_post.py.
OUTPUT_LINE_NUMBERS
Path.Post.scripts.dynapath_post.OUTPUT_LINE_NUMBERS
Definition at line 107 of file dynapath_post.py.
parser
Path.Post.scripts.dynapath_post.parser
Definition at line 77 of file dynapath_post.py.
POST_OPERATION
Path.Post.scripts.dynapath_post.POST_OPERATION
Definition at line 145 of file dynapath_post.py.
POSTAMBLE
Path.Post.scripts.dynapath_post.POSTAMBLE
Definition at line 131 of file dynapath_post.py.
PRE_OPERATION
Path.Post.scripts.dynapath_post.PRE_OPERATION
Definition at line 142 of file dynapath_post.py.
PREAMBLE
Path.Post.scripts.dynapath_post.PREAMBLE
Definition at line 123 of file dynapath_post.py.
prog
Path.Post.scripts.dynapath_post.prog
Definition at line 77 of file dynapath_post.py.
SHOW_EDITOR
Path.Post.scripts.dynapath_post.SHOW_EDITOR
Definition at line 108 of file dynapath_post.py.
TOOL_CHANGE
Path.Post.scripts.dynapath_post.TOOL_CHANGE
Definition at line 148 of file dynapath_post.py.
TOOLTIP
Path.Post.scripts.dynapath_post.TOOLTIP
Definition at line 43 of file dynapath_post.py.
TOOLTIP_ARGS
Path.Post.scripts.dynapath_post.TOOLTIP_ARGS
Definition at line 100 of file dynapath_post.py.
UNIT_FORMAT
Path.Post.scripts.dynapath_post.UNIT_FORMAT
Definition at line 114 of file dynapath_post.py.
UNIT_SPEED_FORMAT
Path.Post.scripts.dynapath_post.UNIT_SPEED_FORMAT
Definition at line 113 of file dynapath_post.py.
UNITS
Path.Post.scripts.dynapath_post.UNITS
Definition at line 117 of file dynapath_post.py.