FreeCAD: Gui::Document Class Reference
Gui::Document Class Reference
#include <Document.h>
Public Member Functions
Document (App::Document *pcDocument, Application *app)
~Document () override
methods for View handling
Gui::MDIView * getActiveView () const
Getter for the active view.
void setActiveWindow (Gui::MDIView *view)
Document::setActiveWindow If this document is active and the view is part of it then it will be activated. If the document is not active of the view is already active nothing is done.
Gui::MDIView * getEditingViewOfViewProvider (Gui::ViewProvider *) const
Gui::MDIView * getViewOfViewProvider (const Gui::ViewProvider *) const
Gui::MDIView * getViewOfNode (SoNode *) const
MDIView * createView (const Base::Type &typeId)
Create a new view.
Gui::MDIView * cloneView (Gui::MDIView *)
Create a clone of the given view.
bool sendMsgToViews (const char *pMsg)
send Messages to all views
bool sendMsgToFirstView (const Base::Type &typeId, const char *pMsg, const char **ppReturn)
void attachView (Gui::BaseView *pcView, bool bPassiv=false)
Attach a view (get called by the MDIView constructor)
void detachView (Gui::BaseView *pcView, bool bPassiv=false)
Detach a view (get called by the MDIView destructor)
ViewProviderDocumentObject * getViewProviderByPathFromTail (SoPath *path) const
helper for selection
ViewProviderDocumentObject * getViewProviderByPathFromHead (SoPath *path) const
helper for selection
std::vector< std::pair< ViewProviderDocumentObject *, int > > getViewProvidersByPath (SoPath *path) const
Get all view providers along the path and the corresponding node index in the path.
void onUpdate ()
call update on all attached views
void onRelabel ()
call relabel to all attached views
std::list< MDIView * > getMDIViews () const
returns a list of all attached MDI views
std::list< MDIView * > getMDIViewsOfType (const Base::Type &typeId) const
returns a list of all MDI views of a certain type
MDIView * setActiveView (const ViewProviderDocumentObject *vp=nullptr, Base::Type typeId=Base::Type())
View3DInventor * openEditingView3D (const ViewProviderDocumentObject *vp)
View3DInventor * openEditingView3D (const App::DocumentObject *obj)
View provider handling
ViewProvider * getViewProvider (const App::DocumentObject *) const
Get the view provider for that object.
ViewProviderDocumentObject * getViewProvider (SoNode *node) const
void setAnnotationViewProvider (const char *name, ViewProvider *pcProvider)
set an annotation view provider
ViewProvider * getAnnotationViewProvider (const char *name) const
get an annotation view provider
bool isAnnotationViewProvider (const ViewProvider *vp) const
return true if the view provider is added as an annotation view provider
ViewProvider * takeAnnotationViewProvider (const char *name)
remove an annotation view provider from the document and return it
void removeAnnotationViewProvider (const char *name)
remove and delete an annotation view provider
bool isShow (const char *name)
test if the feature is in show
void setShow (const char *name)
put the feature in show
void setHide (const char *name)
set the feature in Noshow
void setPos (const char *name, const Base::Matrix4D &rclMtrx)
set the feature transformation (only viewing)
std::vector< ViewProvider * > getViewProvidersOfType (const Base::Type &typeId) const
ViewProvider * getViewProviderByName (const char *name) const
bool setEdit (Gui::ViewProvider *p, int ModNum=0, const char *subname=nullptr)
set the ViewProvider in special edit mode
const Base::Matrix4D & getEditingTransform () const
void setEditingTransform (const Base::Matrix4D &mat)
void resetEdit ()
reset from edit mode, this cause all document to reset edit
void _resetEdit ()
reset edit of this document
void setEditRestore (bool val)
set if the edit asks for restore or not.
ViewProvider * getInEdit (ViewProviderDocumentObject **parentVp=nullptr, std::string *subname=nullptr, int *mode=nullptr, std::string *subElement=nullptr) const
get the in edit ViewProvider or NULL
void setInEdit (ViewProviderDocumentObject *parentVp, const char *subname)
set the in edit ViewProvider subname reference
void toggleInSceneGraph (ViewProvider *vp)
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Attributes
Signals of the document
boost::signals2::signal< void(const Gui::ViewProviderDocumentObject &)> signalNewObject
signal on new Object
boost::signals2::signal< void(const Gui::ViewProviderDocumentObject &)> signalDeletedObject
signal on deleted Object
boost::signals2::signal< void(const Gui::ViewProviderDocumentObject &, const App::Property &)> signalChangedObject
boost::signals2::signal< void(const Gui::ViewProviderDocumentObject &)> signalRelabelObject
signal on renamed Object
boost::signals2::signal< void(const Gui::ViewProviderDocumentObject &)> signalActivatedObject
signal on activated Object
boost::signals2::signal< void(const Gui::ViewProviderDocumentObject &)> signalInEdit
signal on entering in edit mode
boost::signals2::signal< void(const Gui::ViewProviderDocumentObject &)> signalResetEdit
signal on leaving edit mode
boost::signals2::signal< void(const Gui::ViewProviderDocumentObject &, const Gui::HighlightMode &, bool, App::DocumentObject *parent, const char *subname)> signalHighlightObject
signal on changed Object, the 2nd argument is the highlite mode to use
boost::signals2::signal< void(const Gui::ViewProviderDocumentObject &, const Gui::TreeItemMode &, App::DocumentObject *parent, const char *subname)> signalExpandObject
signal on changed Object, the 2nd argument is the highlite mode to use
boost::signals2::signal< void(const Gui::ViewProviderDocumentObject &)> signalShowItem
signal on changed ShowInTree property in view provider
boost::signals2::signal< void(const Gui::ViewProviderDocumentObject &)> signalScrollToObject
signal on scrolling to an object
boost::signals2::signal< void(const Gui::Document &doc)> signalUndoDocument
signal on undo Document
boost::signals2::signal< void(const Gui::Document &doc)> signalRedoDocument
signal on redo Document
boost::signals2::signal< void(const Gui::Document &doc)> signalDeleteDocument
signal on deleting Document
I/O of the document
void addViewProvider (Gui::ViewProviderDocumentObject *)
unsigned int getMemSize () const override
bool save ()
Save the document.
bool saveAs ()
Save the document under a new file name.
bool saveCopy ()
Save a copy of the document under a new file name.
void Save (Base::Writer &writer) const override
This method is used to save properties or very small amounts of data to an XML document.
void Restore (Base::XMLReader &reader) override
This method is used to restore properties from an XML document.
void SaveDocFile (Base::Writer &writer) const override
This method is used to save large amounts of data to a binary file.
void RestoreDocFile (Base::Reader &reader) override
This method is used to restore large amounts of data from a binary file.
void exportObjects (const std::vector< App::DocumentObject * > &, Base::Writer &)
void importObjects (const std::vector< App::DocumentObject * > &, Base::Reader &, const std::map< std::string, std::string > &nameMapping)
void addRootObjectsToGroup (const std::vector< App::DocumentObject * > &, App::DocumentObjectGroup *)
Add all root objects of the given array to a group.
void setModified (bool)
Observer message from the App doc.
bool isModified () const
bool isAboutToClose () const
Returns true if the document is about to be closed, false otherwise.
App::Document * getDocument () const
Getter for the App Document.
void slotNewObject (const App::DocumentObject &)
This slot is connected to the App::Document::signalNewObject(...)
void slotDeletedObject (const App::DocumentObject &)
void slotChangedObject (const App::DocumentObject &, const App::Property &)
void slotRelabelObject (const App::DocumentObject &)
void slotTransactionAppend (const App::DocumentObject &, App::Transaction *)
void slotTransactionRemove (const App::DocumentObject &, App::Transaction *)
void slotActivatedObject (const App::DocumentObject &)
void slotStartRestoreDocument (const App::Document &)
void slotFinishRestoreDocument (const App::Document &)
void slotUndoDocument (const App::Document &)
void slotRedoDocument (const App::Document &)
void slotShowHidden (const App::Document &)
void slotFinishImportObjects (const std::vector< App::DocumentObject * > &)
void slotFinishRestoreObject (const App::DocumentObject &obj)
void slotRecomputed (const App::Document &)
void slotSkipRecompute (const App::Document &doc, const std::vector< App::DocumentObject * > &objs)
void slotTouchedObject (const App::DocumentObject &)
void slotChangePropertyEditor (const App::Document &, const App::Property &)
static void saveAll ()
Save all open document.
methods for the UNDO REDO handling
Gui::DocumentPy * _pcDocPy
void openCommand (const char *sName=nullptr)
Open a new Undo transaction on the document.
void commitCommand ()
Commit the Undo transaction on the document.
void abortCommand ()
Abort the Undo transaction on the document.
bool hasPendingCommand () const
Check if an Undo transaction is open.
std::vector< std::string > getUndoVector () const
Get an Undo string vector with the Undo names.
std::vector< std::string > getRedoVector () const
Get an Redo string vector with the Redo names.
void undo (int iSteps)
Will UNDO one or more steps.
void redo (int iSteps)
Will REDO one or more steps.
bool isPerformingTransaction () const
bool canClose (bool checkModify=true, bool checkLink=false)
handles the application close event
bool isLastView ()
void beforeDelete ()
called by Application before being deleted
PyObject * getPyObject () override
const char * getCameraSettings () const
bool saveCameraSettings (const char *) const
std::vector< App::DocumentObject * > getTreeRootObjects () const
get all tree root objects (objects that are at the root of the object tree)
attributes for the UNDO REDO facility
class TransactionViewProvider
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
The Gui Document This is the document on GUI level. Its main responsibility is keeping track off open windows for a document and warning on unsaved closes. All handled views on the document must inherit from MDIView
See also
App::Document
MDIView
Author
Jrgen Riegel
Definition at line 69 of file Gui/Document.h.
Constructor & Destructor Documentation
Document()
Document::Document (App::Document * pcDocument, Application * app)
Definition at line 421 of file Gui/Document.cpp.
References Gui::DocumentP::_changeViewTouchDocument, Gui::DocumentP::_editingObject, Gui::DocumentP::_editingViewer, Gui::DocumentP::_editMode, Gui::DocumentP::_editModePrevious, Gui::DocumentP::_editViewProvider, Gui::DocumentP::_editViewProviderParent, Gui::DocumentP::_editViewProviderPrevious, Gui::DocumentP::_editWantsRestore, Gui::DocumentP::_editWantsRestorePrevious, Gui::DocumentP::_iDocId, Gui::DocumentP::_isClosing, Gui::DocumentP::_isModified, Gui::DocumentP::_isTransacting, Gui::DocumentP::_iWinCount, Gui::DocumentP::_pcAppWnd, _pcDocPy, Gui::DocumentP::_pcDocument, src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui::app, draftgeoutils.faces::bind(), Gui::DocumentP::connectActObject, Gui::DocumentP::connectActObjectBlocker, Gui::DocumentP::connectChangeDocument, Gui::DocumentP::connectChangeDocumentBlocker, Gui::DocumentP::connectChangePropertyEditor, Gui::DocumentP::connectCngObject, Gui::DocumentP::connectDelObject, Gui::DocumentP::connectExportObjects, Gui::DocumentP::connectFinishImportObjects, Gui::DocumentP::connectFinishLoadDocument, Gui::DocumentP::connectFinishRestoreObject, Gui::DocumentP::connectImportObjects, Gui::DocumentP::connectNewObject, Gui::DocumentP::connectRecomputed, Gui::DocumentP::connectRedoDocument, Gui::DocumentP::connectRenObject, Gui::DocumentP::connectRestDocument, Gui::DocumentP::connectSaveDocument, Gui::DocumentP::connectShowHidden, Gui::DocumentP::connectSkipRecompute, Gui::DocumentP::connectStartLoadDocument, Gui::DocumentP::connectTouchedObject, Gui::DocumentP::connectTransactionAppend, Gui::DocumentP::connectTransactionRemove, Gui::DocumentP::connectUndoDocument, exportObjects(), App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), importObjects(), Restore(), Save(), App::Document::setMaxUndoStackSize(), App::Document::setUndoMode(), App::Document::signalActivatedObject, App::Document::signalChanged, App::Document::signalChangedObject, App::Document::signalChangePropertyEditor, App::Document::signalDeletedObject, App::Document::signalExportViewObjects, App::Document::signalFinishImportObjects, App::Application::signalFinishRestoreDocument, App::Document::signalFinishRestoreObject, App::Document::signalImportViewObjects, App::Document::signalNewObject, App::Document::signalRecomputed, App::Document::signalRedo, App::Document::signalRelabelObject, App::Document::signalRestoreDocument, App::Document::signalSaveDocument, App::Application::signalShowHidden, App::Document::signalSkipRecompute, App::Application::signalStartRestoreDocument, App::Document::signalTouchedObject, App::Document::signalTransactionAppend, App::Document::signalTransactionRemove, App::Document::signalUndo, slotActivatedObject(), slotChangedObject(), slotChangePropertyEditor(), slotDeletedObject(), slotFinishImportObjects(), slotFinishRestoreDocument(), slotFinishRestoreObject(), slotNewObject(), slotRecomputed(), slotRedoDocument(), slotRelabelObject(), slotShowHidden(), slotSkipRecompute(), slotStartRestoreDocument(), slotTouchedObject(), slotTransactionAppend(), slotTransactionRemove(), and slotUndoDocument().
~Document()
Document::~Document () override
Definition at line 515 of file Gui/Document.cpp.
References Gui::DocumentP::_isClosing, _pcDocPy, Gui::DocumentP::_ViewProviderMap, Gui::DocumentP::_ViewProviderMapAnnotation, Gui::DocumentP::baseViews, Gui::DocumentP::connectActObject, Gui::DocumentP::connectChangeDocument, Gui::DocumentP::connectChangePropertyEditor, Gui::DocumentP::connectCngObject, Gui::DocumentP::connectDelObject, Gui::DocumentP::connectExportObjects, Gui::DocumentP::connectFinishImportObjects, Gui::DocumentP::connectFinishLoadDocument, Gui::DocumentP::connectFinishRestoreObject, Gui::DocumentP::connectImportObjects, Gui::DocumentP::connectNewObject, Gui::DocumentP::connectRecomputed, Gui::DocumentP::connectRedoDocument, Gui::DocumentP::connectRenObject, Gui::DocumentP::connectRestDocument, Gui::DocumentP::connectSaveDocument, Gui::DocumentP::connectShowHidden, Gui::DocumentP::connectSkipRecompute, Gui::DocumentP::connectStartLoadDocument, Gui::DocumentP::connectTouchedObject, Gui::DocumentP::connectTransactionAppend, Gui::DocumentP::connectTransactionRemove, and Gui::DocumentP::connectUndoDocument.
Member Function Documentation
_resetEdit()
void Document::_resetEdit ()
reset edit of this document
Definition at line 677 of file Gui/Document.cpp.
References Gui::DocumentP::_editingObject, Gui::DocumentP::_editingViewer, Gui::DocumentP::_editMode, Gui::DocumentP::_editModePrevious, Gui::DocumentP::_editObjs, Gui::DocumentP::_editViewProvider, Gui::DocumentP::_editViewProviderParent, Gui::DocumentP::_editViewProviderPrevious, Gui::DocumentP::_editWantsRestore, Gui::DocumentP::_editWantsRestorePrevious, Gui::DocumentP::baseViews, App::Application::closeActiveTransaction(), Gui::ViewProvider::finishEditing(), App::GetApplication(), Base::Persistence::getClassTypeId(), Gui::ViewProviderDocumentObject::getDocument(), Gui::View3DInventor::getViewer(), Gui::Application::Instance, Base::BaseClass::isDerivedFrom(), Gui::View3DInventorViewer::resetEditingViewProvider(), Gui::Application::setEditDocument(), and signalResetEdit.
Referenced by canClose(), and slotDeletedObject().
abortCommand()
void Document::abortCommand ()
Abort the Undo transaction on the document.
Definition at line 2538 of file Gui/Document.cpp.
References App::Document::abortTransaction(), and getDocument().
Referenced by MeshGui::ViewProviderMesh::clipMeshCallback(), ReverseEngineeringGui::SegmentationManual::createSegment(), TechDrawGui::TaskBalloon::reject(), Gui::TaskCSysDragger::reject(), and MeshGui::ViewProviderMesh::trimMeshCallback().
addRootObjectsToGroup()
void Document::addRootObjectsToGroup (const std::vector< App::DocumentObject * > & obj, App::DocumentObjectGroup * grp)
Add all root objects of the given array to a group.
Definition at line 1958 of file Gui/Document.cpp.
References Gui::ViewProvider::claimChildren(), getViewProvider(), and toolbit-attributes::grp.
addViewProvider()
void Document::addViewProvider (Gui::ViewProviderDocumentObject * vp)
Definition at line 1186 of file Gui/Document.cpp.
References Gui::DocumentP::_CoinMap, Gui::DocumentP::_ViewProviderMap, Gui::Detach, Gui::ViewProviderDocumentObject::getObject(), Gui::ViewProvider::getRoot(), and Gui::ViewProvider::setStatus().
attachView()
void Document::attachView (Gui::BaseView * pcView, bool bPassiv = false)
Attach a view (get called by the MDIView constructor)
Definition at line 2131 of file Gui/Document.cpp.
References Gui::DocumentP::baseViews, and Gui::DocumentP::passiveViews.
Referenced by Gui::BaseView::setDocument().
beforeDelete()
void Document::beforeDelete ()
called by Application before being deleted
Definition at line 1012 of file Gui/Document.cpp.
References Gui::DocumentP::_ViewProviderMap, Gui::Application::editDocument(), Gui::Application::Instance, Gui::Application::setEditDocument(), and TestSpreadsheet::v.
canClose()
bool Document::canClose (bool checkModify = true, bool checkLink = false)
handles the application close event
This method checks if the document can be closed. It checks on the save state of the document and is able to abort the closing.
Definition at line 2217 of file Gui/Document.cpp.
References Gui::DocumentP::_editViewProvider, Gui::DocumentP::_isClosing, _resetEdit(), Gui::ControlSingleton::activeDialog(), Gui::MainWindow::confirmSave(), Gui::Control(), getActiveView(), getDocument(), App::PropertyXLink::getDocumentInList(), Gui::TaskView::TaskDialog::getDocumentName(), Gui::getMainWindow(), App::PropertyString::getValue(), isModified(), App::Document::Label, App::Document::PartialDoc, save(), App::Document::TempDoc, and Path.Log::warning().
cloneView()
Gui::MDIView * Document::cloneView (Gui::MDIView * oldview)
Create a clone of the given view.
Definition at line 2051 of file Gui/Document.cpp.
References Gui::DocumentP::_editMode, Gui::DocumentP::_editViewProvider, Gui::DocumentP::_ViewProviderMap, Gui::DocumentP::_ViewProviderMapAnnotation, Gui::getMainWindow(), Gui::View3DInventorViewer::getOverrideMode(), Gui::View3DInventor::getViewer(), getViewProvider(), and Base::BaseClass::is().
commitCommand()
void Document::commitCommand ()
Commit the Undo transaction on the document.
Definition at line 2533 of file Gui/Document.cpp.
References App::Document::commitTransaction(), and getDocument().
Referenced by TechDrawGui::TaskBalloon::accept(), Gui::TaskCSysDragger::accept(), StdCmdToggleTransparency::activated(), Gui::ManualAlignment::align(), MeshGui::ViewProviderMesh::clipMeshCallback(), ReverseEngineeringGui::SegmentationManual::createSegment(), PointsGui::ViewProviderScattered::cut(), PointsGui::ViewProviderStructured::cut(), MeshGui::ViewProviderMesh::fillHole(), MeshGui::ViewProviderMesh::markPartCallback(), SketcherGui::ViewProviderSketch::mouseButtonPressed(), MeshGui::ViewProviderMesh::partMeshCallback(), MeshGui::ViewProviderMesh::segmMeshCallback(), and MeshGui::ViewProviderMesh::trimMeshCallback().
createView()
MDIView * Document::createView (const Base::Type & typeId)
Create a new view.
Definition at line 1985 of file Gui/Document.cpp.
References Gui::DocumentP::_iWinCount, Gui::DocumentP::_ViewProviderMap, Gui::DocumentP::_ViewProviderMapAnnotation, Gui::MainWindow::addWindow(), Base::BaseClass::getClassTypeId(), getDocument(), Gui::getMainWindow(), getMDIViewsOfType(), Gui::View3DInventorViewer::getOverrideMode(), App::PropertyString::getValue(), Gui::View3DInventor::getViewer(), getViewProvider(), Base::Type::isDerivedFrom(), isModified(), App::Document::Label, saveCameraSettings(), and Plot::title().
Referenced by StdCmdViewCreate::activated(), and setActiveView().
detachView()
void Document::detachView (Gui::BaseView * pcView, bool bPassiv = false)
Detach a view (get called by the MDIView destructor)
Definition at line 2139 of file Gui/Document.cpp.
References Gui::DocumentP::_isClosing, Gui::DocumentP::_pcAppWnd, Gui::DocumentP::baseViews, DraftVecUtils::find(), getDocument(), App::PropertyXLink::getDocumentInList(), Gui::Application::onLastWindowClosed(), and Gui::DocumentP::passiveViews.
Referenced by Gui::BaseView::onClose(), and Gui::BaseView::setDocument().
exportObjects()
void Document::exportObjects (const std::vector< App::DocumentObject * > & obj, Base::Writer & writer)
Definition at line 1842 of file Gui/Document.cpp.
References Base::Writer::decInd(), toolbit-attributes::doc, App::Expand, Gui::Application::getDocument(), App::ExtensionContainer::hasExtensions(), Base::Writer::incInd(), Base::Writer::ind(), Gui::Application::Instance, Base::Writer::isForceXML(), App::ExtensionContainer::Save(), Base::Writer::setForceXML(), and Base::Writer::Stream().
Referenced by Document(), and Gui::MergeDocuments::SaveDocFile().
getActiveView()
MDIView * Document::getActiveView () const
Getter for the active view.
Definition at line 2365 of file Gui/Document.cpp.
References Gui::MainWindow::activeWindow(), Base::BaseClass::getClassTypeId(), Gui::getMainWindow(), getMDIViews(), and Gui::MainWindow::windows().
Referenced by StdCmdViewCreate::activated(), Gui::SelectionSingleton::addSelection(), canClose(), Gui::ViewProviderDocumentObject::getActiveView(), getInEdit(), Gui::Command::isViewOfType(), openEditingView3D(), SketcherGui::ViewProviderSketch::purgeHandler(), Gui::SelectionSingleton::rmvPreselect(), sendMsgToFirstView(), setActiveView(), setEditingTransform(), Gui::SelectionSingleton::setPreselect(), Gui::ApplicationPy::sExport(), SketcherGui::ViewProviderSketch::slotSolverUpdate(), and Gui::ApplicationPy::sSetActiveDocument().
getAnnotationViewProvider()
ViewProvider * Document::getAnnotationViewProvider (const char * name) const
get an annotation view provider
Definition at line 770 of file Gui/Document.cpp.
References Gui::DocumentP::_ViewProviderMapAnnotation.
Referenced by Gui::View3DInventorPy::removeAnnotation().
getCameraSettings()
const char * Document::getCameraSettings () const
Definition at line 2103 of file Gui/Document.cpp.
Referenced by SaveDocFile().
getDocument()
App::Document * Document::getDocument () const
Getter for the App Document.
Definition at line 1273 of file Gui/Document.cpp.
References Gui::DocumentP::_pcDocument.
Referenced by abortCommand(), Gui::Dialog::DlgMacroExecuteImp::accept(), Gui::TaskCSysDragger::accept(), StdCmdVarSet::activated(), StdCmdImport::activated(), Gui::MacroCommand::activated(), Gui::RecentMacrosAction::activateFile(), PartGui::FaceAppearances::Private::addFacesToSelection(), canClose(), Gui::View3DInventorSelection::checkGroupOnTop(), FemGui::ViewProviderFemAnalysis::checkSelectedChildren(), DrawingGui::DrawingView::closeEvent(), commitCommand(), ReverseEngineeringGui::SegmentationManual::createSegment(), createView(), Gui::DocumentIndex::data(), detachView(), Gui::View3DInventorViewer::dropEvent(), ReverseEngineeringGui::SegmentationManual::Private::findGeometry(), Gui::ManualAlignment::finish(), Gui::BaseView::getAppDocument(), Gui::LinkInfo::getDocName(), Gui::Command::getDocument(), getRedoVector(), getUndoVector(), getViewProviderByName(), hasPendingCommand(), Gui::Command::isActiveObjectValid(), Gui::DAG::Model::Model(), Gui::Application::onLastWindowClosed(), Gui::MDIView::onRelabel(), DrawingGui::DrawingView::onRelabel(), Gui::View3DInventor::onRename(), openCommand(), MeshPartGui::CurveOnMeshHandler::recomputeDocument(), redo(), Gui::TaskCSysDragger::reject(), save(), saveAs(), saveCopy(), Gui::DocumentItem::selectItems(), Gui::Application::setActiveDocument(), Gui::DocumentItem::setData(), Gui::View3DInventorViewer::setDocument(), Gui::DocumentItem::setShowHidden(), Gui::DocumentItem::showHidden(), PartDesignGui::SketchWorkflow::SketchWorkflow(), slotChangePropertyEditor(), Gui::ElementColors::slotDeleteDocument(), Gui::DocumentItem::slotExpandObject(), Gui::DocumentItem::slotNewObject(), Gui::TreeWidget::startItemSearch(), undo(), and Gui::DocumentObjectData::updateChildren().
getEditingTransform()
const Base::Matrix4D & Document::getEditingTransform () const
Definition at line 652 of file Gui/Document.cpp.
References Gui::DocumentP::_editingTransform.
getEditingViewOfViewProvider()
Gui::MDIView * Document::getEditingViewOfViewProvider (Gui::ViewProvider * vp) const
Definition at line 2503 of file Gui/Document.cpp.
References Base::BaseClass::getClassTypeId(), getMDIViewsOfType(), and OfflineRenderingUtils::viewer().
Referenced by Gui::ViewProviderDocumentObject::getEditingView(), and Gui::ViewProviderDocumentObject::getInventorView().
getInEdit()
ViewProvider * Document::getInEdit (ViewProviderDocumentObject ** parentVp = nullptr, std::string * subname = nullptr, int * mode = nullptr, std::string * subElement = nullptr) const
get the in edit ViewProvider or NULL
Definition at line 720 of file Gui/Document.cpp.
References Gui::DocumentP::_editMode, Gui::DocumentP::_editSubElement, Gui::DocumentP::_editSubname, Gui::DocumentP::_editViewProvider, Gui::DocumentP::_editViewProviderParent, and getActiveView().
Referenced by CmdSketcherConstrainLock::applyConstraint(), CmdSketcherConstrainBlock::applyConstraint(), CmdSketcherConstrainDistance::applyConstraint(), CmdSketcherConstrainDistanceX::applyConstraint(), CmdSketcherConstrainDistanceY::applyConstraint(), CmdSketcherConstrainParallel::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainRadiam::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), CmdSketcherConstrainCoincidentUnified::applyConstraintCoincident(), CmdSketcherConstrainCoincidentUnified::applyConstraintPointOnObject(), and horVerApplyConstraint().
getMDIViews()
std::list< MDIView * > Document::getMDIViews () const
returns a list of all attached MDI views
Definition at line 2297 of file Gui/Document.cpp.
References Gui::DocumentP::baseViews.
Referenced by TechDrawGui::DrawGuiUtil::get3DDirAndRot(), getActiveView(), TechDrawGui::QGVPage::getDevicePixelRatio(), RestoreDocFile(), Save(), SaveDocFile(), setActiveWindow(), and setModified().
getMDIViewsOfType()
std::list< MDIView * > Document::getMDIViewsOfType (const Base::Type & typeId) const
returns a list of all MDI views of a certain type
Definition at line 2310 of file Gui/Document.cpp.
References Gui::DocumentP::baseViews.
Referenced by DrawingGui::TaskProjection::accept(), TechDrawGui::TaskProjection::accept(), StdCmdImport::activated(), TechDrawGui::TaskActiveView::createActiveView(), createView(), getEditingViewOfViewProvider(), Gui::ViewProviderTextDocument::getMDIView(), getViewOfNode(), and sendMsgToFirstView().
getMemSize()
unsigned int Document::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
Definition at line 1580 of file Gui/Document.cpp.
References Gui::DocumentP::_ViewProviderMap.
getPyObject()
PyObject * Document::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 2656 of file Gui/Document.cpp.
References _pcDocPy.
Referenced by Gui::ApplicationPy::sActiveDocument(), Gui::ApplicationPy::sEditDocument(), and Gui::ApplicationPy::sGetDocument().
getRedoVector()
std::vector< std::string > Document::getRedoVector () const
Get an Redo string vector with the Redo names.
Get a string vector with the 'Redo' actions.
Definition at line 2555 of file Gui/Document.cpp.
References App::Document::getAvailableRedoNames(), and getDocument().
getTreeRootObjects()
std::vector< App::DocumentObject * > Document::getTreeRootObjects () const
get all tree root objects (objects that are at the root of the object tree)
Definition at line 2783 of file Gui/Document.cpp.
References Gui::DocumentP::_pcDocument, Gui::ViewProvider::claimChildren(), App::Document::getObjects(), Gui::Application::getViewProvider(), and Gui::Application::Instance.
getUndoVector()
std::vector< std::string > Document::getUndoVector () const
Get an Undo string vector with the Undo names.
Get a string vector with the 'Undo' actions.
Definition at line 2549 of file Gui/Document.cpp.
References App::Document::getAvailableUndoNames(), and getDocument().
Referenced by TechDrawGui::TaskRichAnno::removeFeature(), and TechDrawGui::TaskLeaderLine::removeFeature().
getViewOfNode()
Gui::MDIView * Document::getViewOfNode (SoNode * node) const
Definition at line 2486 of file Gui/Document.cpp.
References Base::BaseClass::getClassTypeId(), and getMDIViewsOfType().
Referenced by Gui::ViewProviderDocumentObject::getViewOfNode(), and getViewOfViewProvider().
getViewOfViewProvider()
Gui::MDIView * Document::getViewOfViewProvider (const Gui::ViewProvider * vp) const
Definition at line 2498 of file Gui/Document.cpp.
References Gui::ViewProvider::getRoot(), and getViewOfNode().
Referenced by Gui::ViewProviderDocumentObject::getInventorView().
getViewProvider() [1/2]
ViewProvider * Document::getViewProvider (const App::DocumentObject * Feat) const
Get the view provider for that object.
Definition at line 814 of file Gui/Document.cpp.
References Gui::DocumentP::_ViewProviderMap.
Referenced by TechDrawGui::_createBalloon(), addRootObjectsToGroup(), Gui::AlignmentGroup::addView(), ImportGui::ImpExpDxfReadGui::ApplyGuiStyles(), cloneView(), DrawingGui::DrawingView::closeEvent(), TechDrawGui::TaskActiveView::createActiveView(), TechDrawGui::TaskHatch::createHatch(), createView(), Gui::ViewProviderDocumentObject::findFrontRootOfType(), ReverseEngineeringGui::SegmentationManual::Private::findGeometry(), PartGui::DlgScale::findShapes(), PartGui::DlgExtrusion::findShapes(), Gui::ViewProviderDocumentObject::getElementPicked(), TechDrawGui::QGIView::getFrameState(), TechDrawGui::ViewProviderTemplate::getMDIViewPage(), TechDrawGui::ViewProviderTemplate::getQTemplate(), TechDrawGui::ViewProviderPage::getQTemplate(), Gui::LinkInfo::getView(), TechDrawGui::QGIView::getViewProvider(), TechDrawGui::ViewProviderDrawingView::getViewProviderPage(), TechDrawGui::QGIView::getViewProviderPage(), Gui::ViewProviderDocumentObjectGroup::getViewProviders(), Gui::MergeDocuments::importObject(), MeasureGui::ViewProviderMeasureBase::isSubjectVisible(), TechDrawGui::TaskLinkDim::loadToTree(), Gui::DAG::Model::Model(), openEditingView3D(), FemGui::ActiveAnalysisObserver::setActiveObject(), TechDrawGui::ViewProviderPage::setTemplateMarkers(), PartDesignGui::ViewProviderBody::setVisualBodyMode(), slotActivatedObject(), slotChangedObject(), slotDeletedObject(), slotFinishRestoreDocument(), slotFinishRestoreObject(), slotNewObject(), slotRelabelObject(), slotTransactionAppend(), TechDrawGui::ViewProviderDrawingView::stackBottom(), TechDrawGui::ViewProviderDrawingView::stackTop(), TechDrawGui::TaskCosVertex::TaskCosVertex(), TechDrawGui::TaskDetail::TaskDetail(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), TechDrawGui::TaskProjGroup::TaskProjGroup(), TechDrawGui::TaskRichAnno::TaskRichAnno(), RobotGui::TaskTrajectory::TaskTrajectory(), RobotGui::TrajectorySimulate::TrajectorySimulate(), TechDrawGui::TaskProjGroup::turnProjGroupToView(), PartDesignGui::ViewProviderBody::unifyVisualProperty(), MeshGui::ViewProviderMeshCurvature::updateData(), and TechDrawGui::ViewProviderGeomHatch::updateGraphic().
getViewProvider() [2/2]
ViewProviderDocumentObject * Document::getViewProvider (SoNode * node) const
Definition at line 1250 of file Gui/Document.cpp.
References Gui::DocumentP::_CoinMap.
getViewProviderByName()
ViewProvider * Document::getViewProviderByName (const char * name) const
Definition at line 832 of file Gui/Document.cpp.
References Gui::DocumentP::_ViewProviderMap, Gui::DocumentP::_ViewProviderMapAnnotation, getDocument(), and App::Document::getObject().
Referenced by StdCmdToggleSelectability::activated(), importObjects(), isShow(), RestoreDocFile(), setHide(), setPos(), and setShow().
getViewProviderByPathFromHead()
ViewProviderDocumentObject * Document::getViewProviderByPathFromHead (SoPath * path) const
helper for selection
Definition at line 1236 of file Gui/Document.cpp.
References Gui::DocumentP::_CoinMap, and SplineSurface::i.
Referenced by Gui::View3DInventorViewer::getViewProviderByPath().
getViewProviderByPathFromTail()
ViewProviderDocumentObject * Document::getViewProviderByPathFromTail (SoPath * path) const
helper for selection
Definition at line 1221 of file Gui/Document.cpp.
References Gui::DocumentP::_CoinMap, and SplineSurface::i.
Referenced by Gui::View3DInventorViewer::getViewProviderByPathFromTail().
getViewProvidersByPath()
std::vector< std::pair< ViewProviderDocumentObject *, int > > Document::getViewProvidersByPath (SoPath * path) const
Get all view providers along the path and the corresponding node index in the path.
Definition at line 1259 of file Gui/Document.cpp.
References Gui::DocumentP::_CoinMap, and SplineSurface::i.
getViewProvidersOfType()
std::vector< ViewProvider * > Document::getViewProvidersOfType (const Base::Type & typeId) const
Definition at line 821 of file Gui/Document.cpp.
References Gui::DocumentP::_ViewProviderMap.
Referenced by Gui::SoFCUnifiedSelection::doAction(), Gui::View3DInventorViewer::getViewProvidersOfType(), and Gui::View3DInventorViewer::setOverrideMode().
hasPendingCommand()
bool Document::hasPendingCommand () const
Check if an Undo transaction is open.
Definition at line 2543 of file Gui/Document.cpp.
References getDocument(), and App::Document::hasPendingTransaction().
importObjects()
void Document::importObjects (const std::vector< App::DocumentObject * > & obj, Base::Reader & reader, const std::map< std::string, std::string > & nameMapping)
Definition at line 1889 of file Gui/Document.cpp.
References Gui::ExpandItem, getViewProviderByName(), SplineSurface::i, Gui::isRestoring, TechDrawTools.TaskFillTemplateFields::reader, Gui::ViewProvider::Restore(), Gui::ViewProvider::setStatus(), and signalExpandObject.
Referenced by Document(), and Gui::MergeDocuments::RestoreDocFile().
isAboutToClose()
bool Document::isAboutToClose () const
Returns true if the document is about to be closed, false otherwise.
Definition at line 1216 of file Gui/Document.cpp.
References Gui::DocumentP::_isClosing.
isAnnotationViewProvider()
bool Document::isAnnotationViewProvider (const ViewProvider * vp) const
return true if the view provider is added as an annotation view provider
Definition at line 776 of file Gui/Document.cpp.
References Gui::DocumentP::_ViewProviderMapAnnotation.
isLastView()
bool Document::isLastView ()
Definition at line 2206 of file Gui/Document.cpp.
References Gui::DocumentP::baseViews.
isModified()
bool Document::isModified () const
Definition at line 1211 of file Gui/Document.cpp.
References Gui::DocumentP::_isModified.
Referenced by canClose(), createView(), Gui::ViewProviderDocumentObject::onChanged(), TechDrawGui::PagePrinter::print(), TechDrawGui::PagePrinter::printAll(), TechDrawGui::PagePrinter::printAllPdf(), TechDrawGui::PagePrinter::printPdf(), TechDrawGui::PagePrinter::saveSVG(), slotChangedObject(), and slotTouchedObject().
isPerformingTransaction()
bool Document::isPerformingTransaction () const
Check if the document is performing undo/redo transaction
Unlike App::Document::isPerformingTransaction(), Gui::Document will report transacting when triggering grouped undo/redo in other documents
Definition at line 2620 of file Gui/Document.cpp.
References Gui::DocumentP::_isTransacting.
isShow()
bool Document::isShow (const char * name)
test if the feature is in show
Definition at line 855 of file Gui/Document.cpp.
References getViewProviderByName(), and Gui::ViewProvider::isShow().
onRelabel()
void Document::onRelabel ()
call relabel to all attached views
Definition at line 2187 of file Gui/Document.cpp.
References Gui::DocumentP::baseViews, Gui::DocumentP::connectChangeDocumentBlocker, Base::Console(), Base::ConsoleSingleton::Log(), and Gui::DocumentP::passiveViews.
onUpdate()
void Document::onUpdate ()
call update on all attached views
Definition at line 2170 of file Gui/Document.cpp.
References Gui::DocumentP::baseViews, Base::Console(), Base::ConsoleSingleton::Log(), and Gui::DocumentP::passiveViews.
openCommand()
void Document::openCommand (const char * sName = nullptr)
Open a new Undo transaction on the document.
Open a new Undo transaction on the active document This method opens a new UNDO transaction on the active document. This transaction will later appear in the UNDO/REDO dialog with the name of the command. If the user recall the transaction everything changed on the document between OpenCommand() and CommitCommand will be undone (or redone). You can use an alternative name for the operation default is the command name.
See also
CommitCommand(),AbortCommand()
Definition at line 2528 of file Gui/Document.cpp.
References getDocument(), and App::Document::openTransaction().
Referenced by StdCmdToggleTransparency::activated(), Gui::ManualAlignment::align(), MeshGui::ViewProviderMesh::clipMeshCallback(), ReverseEngineeringGui::SegmentationManual::createSegment(), PointsGui::ViewProviderScattered::cut(), PointsGui::ViewProviderStructured::cut(), MeshGui::ViewProviderMesh::fillHole(), MeshGui::ViewProviderMesh::markPartCallback(), SketcherGui::ViewProviderSketch::mouseButtonPressed(), Gui::TaskCSysDragger::open(), MeshGui::ViewProviderMesh::partMeshCallback(), MeshGui::ViewProviderMesh::segmMeshCallback(), and MeshGui::ViewProviderMesh::trimMeshCallback().
openEditingView3D() [1/2]
View3DInventor * Document::openEditingView3D (const App::DocumentObject * obj)
Definition at line 603 of file Gui/Document.cpp.
References getViewProvider(), Gui::Application::Instance, and openEditingView3D().
openEditingView3D() [2/2]
View3DInventor * Document::openEditingView3D (const ViewProviderDocumentObject * vp)
Definition at line 589 of file Gui/Document.cpp.
References getActiveView(), Gui::getMainWindow(), setActiveView(), and Gui::MainWindow::setActiveWindow().
Referenced by Gui::TaskView::TaskDialog::associateToObject3dView(), and openEditingView3D().
redo()
void Document::redo (int iSteps)
Will REDO one or more steps.
Definition at line 2639 of file Gui/Document.cpp.
References Gui::DocumentP::_isTransacting, Gui::DocumentP::_redoViewProviders, App::GetApplication(), getDocument(), SplineSurface::i, App::Document::redo(), and App::Application::signalRedo.
Referenced by Gui::View3DInventor::onMsg().
removeAnnotationViewProvider()
void Document::removeAnnotationViewProvider (const char * name)
remove and delete an annotation view provider
Definition at line 808 of file Gui/Document.cpp.
References takeAnnotationViewProvider().
Referenced by Gui::View3DInventorPy::removeAnnotation(), and setAnnotationViewProvider().
resetEdit()
void Document::resetEdit ()
reset from edit mode, this cause all document to reset edit
Definition at line 664 of file Gui/Document.cpp.
References Gui::DocumentP::_editModePrevious, Gui::DocumentP::_editViewProvider, Gui::DocumentP::_editViewProviderPrevious, Gui::DocumentP::_editWantsRestorePrevious, Gui::Application::Instance, setEdit(), and Gui::Application::setEditDocument().
Referenced by TechDrawGui::TaskBalloon::accept(), Gui::TaskCSysDragger::accept(), StdCmdTransformManip::activated(), TechDrawGui::TaskBalloon::reject(), Gui::TaskCSysDragger::reject(), and PartGui::FaceAppearances::slotUndoDocument().
Restore()
void Document::Restore (Base::XMLReader & reader) override virtual
This method is used to restore properties from an XML document.
Loads a separate XML file from the projects file with information about the view providers.
Implements Base::Persistence.
Definition at line 1622 of file Gui/Document.cpp.
References Gui::DocumentP::_ViewProviderMap, Gui::isRestoring, and TechDrawTools.TaskFillTemplateFields::reader.
Referenced by Document().
RestoreDocFile()
void Document::RestoreDocFile (Base::Reader & reader) override virtual
This method is used to restore large amounts of data from a binary file.
Restores the properties of the view providers.
Reimplemented from Base::Persistence.
Definition at line 1638 of file Gui/Document.cpp.
References Base::Console(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), Gui::ExpandItem, getMDIViews(), getViewProviderByName(), SplineSurface::i, Gui::TreeWidget::instance(), TechDrawTools.TaskFillTemplateFields::reader, Gui::ViewProvider::Restore(), saveCameraSettings(), setModified(), and signalExpandObject.
save()
bool Document::save ()
Save the document.
Definition at line 1367 of file Gui/Document.cpp.
References Gui::DocumentP::_pcDocument, checkCanonicalPath(), toolbit-attributes::doc, Gui::Command::Doc, doCommand, SCL.SimpleDataTypes::e, FC_ERR, App::Document::getDependentDocuments(), getDocument(), Gui::Application::getDocument(), Gui::getMainWindow(), Gui::Application::Instance, App::Document::isSaved(), App::Document::mustExecute(), App::Document::PartialDoc, saveAs(), setModified(), and App::Document::TempDoc.
Referenced by canClose(), src.Mod.Show.mTempoVis.TempoVis::modify(), src.Mod.Show.mTempoVis.TempoVis::modifyVPProperty(), Gui::View3DInventor::onMsg(), Gui::TextDocumentEditorView::onMsg(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle(), src.Mod.Show.mTempoVis.TempoVis::saveCamera(), and nativeifc.ifc_viewproviders.ifc_vp_document::setupContextMenu().
Save()
void Document::Save (Base::Writer & writer) const override virtual
This method is used to save properties or very small amounts of data to an XML document.
Adds a separate XML file to the projects file that contains information about the view providers.
Implements Base::Persistence.
Definition at line 1594 of file Gui/Document.cpp.
References Gui::DocumentP::_pcDocument, Base::Writer::addFile(), App::Document::FileName, App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetInt(), getMDIViews(), App::Application::GetParameterGroupByPath(), App::PropertyString::getValue(), Base::Writer::isForceXML(), Gui::Thumbnail::Save(), Gui::Thumbnail::setFileName(), Gui::Thumbnail::setSize(), Gui::Thumbnail::setViewer(), and Gui::DocumentP::thumb.
Referenced by Document().
saveAll()
void Document::saveAll () static
Save all open document.
Definition at line 1497 of file Gui/Document.cpp.
References checkCanonicalPath(), toolbit-attributes::doc, Gui::Command::Doc, doCommand, SCL.SimpleDataTypes::e, App::GetApplication(), App::Document::getDependentDocuments(), Gui::Application::getDocument(), App::Application::getDocuments(), Gui::getMainWindow(), Gui::Application::Instance, App::Document::PartialDoc, and App::Document::TempDoc.
Referenced by StdCmdSaveAll::activated().
saveAs()
bool Document::saveAs ()
Save the document under a new file name.
Definition at line 1450 of file Gui/Document.cpp.
References Gui::DocumentP::_pcDocument, Gui::MainWindow::appendRecentFile(), Gui::Command::Doc, doCommand, SCL.SimpleDataTypes::e, Base::Tools::escapedUnicodeFromUtf8(), Base::Tools::escapeEncodeFilename(), App::Document::FileName, App::GetApplication(), getDocument(), App::Application::getDocumentName(), Gui::getMainWindow(), Gui::FileDialog::getSaveFileName(), App::PropertyString::getValue(), setModified(), and Gui::MainWindow::showMessage().
Referenced by Gui::View3DInventor::onMsg(), and save().
saveCameraSettings()
bool Document::saveCameraSettings (const char * settings) const
Definition at line 2107 of file Gui/Document.cpp.
References SCL.SimpleDataTypes::c.
Referenced by createView(), RestoreDocFile(), SaveDocFile(), and Gui::View3DInventor::~View3DInventor().
saveCopy()
bool Document::saveCopy ()
Save a copy of the document under a new file name.
Definition at line 1555 of file Gui/Document.cpp.
References Gui::Command::Doc, doCommand, Base::Tools::escapeEncodeFilename(), App::GetApplication(), getDocument(), App::Application::getDocumentName(), Gui::getMainWindow(), Gui::FileDialog::getSaveFileName(), and Gui::MainWindow::showMessage().
Referenced by Gui::View3DInventor::onMsg().
SaveDocFile()
void Document::SaveDocFile (Base::Writer & writer) const override virtual
This method is used to save large amounts of data to a binary file.
Saves the properties of the view providers.
Reimplemented from Base::Persistence.
Definition at line 1772 of file Gui/Document.cpp.
References Gui::DocumentP::_ViewProviderMap, Base::Writer::decInd(), toolbit-attributes::doc, Base::Persistence::encodeAttribute(), App::Expand, getCameraSettings(), getMDIViews(), Gui::ViewProviderDocumentObject::getTreeRank(), App::ExtensionContainer::hasExtensions(), Base::Writer::incInd(), Base::Writer::ind(), Gui::TreeWidget::instance(), Base::Writer::isForceXML(), App::ExtensionContainer::Save(), saveCameraSettings(), Base::Writer::setForceXML(), and Base::Writer::Stream().
sendMsgToFirstView()
bool Document::sendMsgToFirstView (const Base::Type & typeId, const char * pMsg, const char ** ppReturn)
Sends the message pMsg to the views of type typeid and stops with the first view that supports the message and returns ppReturn. The very first checked view is the current active view. If a view supports the message true is returned and false otherwise.
Definition at line 2344 of file Gui/Document.cpp.
References getActiveView(), getMDIViewsOfType(), Base::BaseClass::isDerivedFrom(), and Gui::MDIView::onMsg().
sendMsgToViews()
bool Document::sendMsgToViews (const char * pMsg)
send Messages to all views
send messages to the active view
send messages to the active view Send a specific massage to the active view and is able to receive a return message
Definition at line 2324 of file Gui/Document.cpp.
References Gui::DocumentP::baseViews, and Gui::DocumentP::passiveViews.
setActiveView()
MDIView * Document::setActiveView (const ViewProviderDocumentObject * vp = nullptr, Base::Type typeId = Base::Type())
Definition at line 2398 of file Gui/Document.cpp.
References Gui::DocumentP::baseViews, Gui::MDIView::containsViewProvider(), createView(), getActiveView(), Base::BaseClass::getClassTypeId(), App::DocumentObject::getLinkedObject(), Gui::getMainWindow(), Gui::ViewProvider::getMDIView(), Gui::ViewProviderDocumentObject::getObject(), Gui::Application::getViewProvider(), Gui::Application::Instance, Base::Type::isBad(), Base::BaseClass::isDerivedFrom(), Gui::MainWindow::setActiveWindow(), and TestSpreadsheet::v.
Referenced by Gui::TreeWidget::dropEvent(), openEditingView3D(), Gui::Application::reopen(), and Gui::TreeWidget::syncView().
setActiveWindow()
void Document::setActiveWindow (Gui::MDIView * view)
Document::setActiveWindow If this document is active and the view is part of it then it will be activated. If the document is not active of the view is already active nothing is done.
Parameters
view
Definition at line 2463 of file Gui/Document.cpp.
References Gui::MainWindow::activeWindow(), DraftVecUtils::find(), Gui::getMainWindow(), getMDIViews(), and Gui::MainWindow::setActiveWindow().
setAnnotationViewProvider()
void Document::setAnnotationViewProvider (const char * name, ViewProvider * pcProvider)
set an annotation view provider
Definition at line 745 of file Gui/Document.cpp.
References Gui::DocumentP::_ViewProviderMapAnnotation, Gui::View3DInventorViewer::addViewProvider(), Gui::DocumentP::baseViews, Gui::View3DInventor::getViewer(), and removeAnnotationViewProvider().
Referenced by Gui::MainWindow::customEvent(), and Gui::View3DInventorPy::setAnnotation().
setEdit()
bool Document::setEdit (Gui::ViewProvider * p, int ModNum = 0, const char * subname = nullptr)
set the ViewProvider in special edit mode
Definition at line 568 of file Gui/Document.cpp.
References SCL.SimpleDataTypes::e, FC_ERR, and buildPsets::p.
Referenced by StdCmdTransformManip::activated(), Gui::ViewProviderDragger::doubleClicked(), Gui::ViewProviderMaterialObject::doubleClicked(), Path.Base.Gui.PropertyBag.ViewProvider::doubleClicked(), Path.Base.Gui.SetupSheet.ViewProvider::doubleClicked(), FemGui::ViewProviderFemPostObject::doubleClicked(), Path.Tool.Gui.Bit.ViewProvider::doubleClicked(), FemGui::ViewProviderFemPostFunction::doubleClicked(), Gui::ViewProviderLink::doubleClicked(), SketcherGui::ViewProviderSketch::doubleClicked(), resetEdit(), PartDesignGui::ViewProviderShapeBinder::setupContextMenu(), Path.Base.Gui.IconViewProvider.ViewProvider::setupContextMenu(), Path.Tool.Gui.Controller.ViewProvider::setupContextMenu(), Path.Op.Gui.Base.ViewProvider::setupContextMenu(), Path.Main.Gui.Job.ViewProvider::setupContextMenu(), and Gui::ViewProviderDocumentObject::startDefaultEditMode().
setEditingTransform()
void Document::setEditingTransform (const Base::Matrix4D & mat)
Definition at line 656 of file Gui/Document.cpp.
References Gui::DocumentP::_editingTransform, Gui::DocumentP::_editObjs, getActiveView(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::setEditingTransform().
setEditRestore()
void Document::setEditRestore (bool val)
set if the edit asks for restore or not.
Definition at line 765 of file Gui/Document.cpp.
References Gui::DocumentP::_editWantsRestore.
setHide()
void Document::setHide (const char * name)
set the feature in Noshow
Definition at line 872 of file Gui/Document.cpp.
References getViewProviderByName(), and Base::BaseClass::isDerivedFrom().
Referenced by Gui::ApplicationPy::sHide().
setInEdit()
void Document::setInEdit (ViewProviderDocumentObject * parentVp, const char * subname)
set the in edit ViewProvider subname reference
Definition at line 738 of file Gui/Document.cpp.
References Gui::DocumentP::_editSubname, Gui::DocumentP::_editViewProvider, and Gui::DocumentP::_editViewProviderParent.
setModified()
void Document::setModified (bool b)
Observer message from the App doc.
Definition at line 1199 of file Gui/Document.cpp.
References Gui::DocumentP::_isModified, SCL.SimpleDataTypes::b, and getMDIViews().
Referenced by Gui::Dialog::DocumentRecovery::accept(), Gui::ViewProviderDocumentObject::onChanged(), RestoreDocFile(), save(), saveAs(), slotChangedObject(), slotChangePropertyEditor(), slotDeletedObject(), slotFinishRestoreDocument(), slotNewObject(), and slotTouchedObject().
setPos()
void Document::setPos (const char * name, const Base::Matrix4D & rclMtrx)
set the feature transformation (only viewing)
set the feature in Noshow
Definition at line 882 of file Gui/Document.cpp.
References getViewProviderByName(), and Gui::ViewProvider::setTransformation().
setShow()
void Document::setShow (const char * name)
put the feature in show
Definition at line 862 of file Gui/Document.cpp.
References getViewProviderByName(), and Base::BaseClass::isDerivedFrom().
Referenced by Gui::ApplicationPy::sShow().
slotActivatedObject()
void Document::slotActivatedObject (const App::DocumentObject & Obj) protected
Definition at line 1116 of file Gui/Document.cpp.
References Base::Persistence::getClassTypeId(), getViewProvider(), Base::BaseClass::isDerivedFrom(), and signalActivatedObject.
Referenced by Document().
slotChangedObject()
void Document::slotChangedObject (const App::DocumentObject & Obj, const App::Property & Prop) protected
Definition at line 1028 of file Gui/Document.cpp.
References Gui::DocumentP::_editingObject, Gui::DocumentP::_editingTransform, Gui::DocumentP::_editingViewer, Gui::DocumentP::_editObjs, Gui::DocumentP::_editSubname, Gui::DocumentP::_editViewProviderParent, SCL.SimpleDataTypes::e, FC_ERR, FC_LOG, Base::Persistence::getClassTypeId(), App::Property::getFullName(), App::DocumentObject::getFullName(), Gui::getMainWindow(), App::Property::getName(), Gui::ViewProviderDocumentObject::getObject(), App::DocumentObject::getSubObject(), getViewProvider(), Base::BaseClass::isDerivedFrom(), isModified(), App::Property::NoModify, Gui::View3DInventorViewer::setEditingTransform(), setModified(), signalChangedObject, App::Property::testStatus(), Gui::ViewProvider::update(), and Gui::MainWindow::updateActions().
Referenced by Document().
slotChangePropertyEditor()
void Document::slotChangePropertyEditor (const App::Document & doc, const App::Property & Prop) protected
Definition at line 2775 of file Gui/Document.cpp.
References toolbit-attributes::doc, FC_LOG, getDocument(), App::Property::getFullName(), Gui::getMainWindow(), setModified(), and Gui::MainWindow::setUserSchema().
Referenced by Document().
slotDeletedObject()
void Document::slotDeletedObject (const App::DocumentObject & Obj) protected
Definition at line 975 of file Gui/Document.cpp.
References Gui::DocumentP::_editViewProvider, Gui::DocumentP::_editViewProviderParent, _resetEdit(), Gui::DocumentP::baseViews, Gui::ViewProvider::beforeDelete(), Gui::Application::editDocument(), Base::Persistence::getClassTypeId(), Base::Persistence::getTypeId(), Gui::View3DInventor::getViewer(), getViewProvider(), Gui::Application::Instance, Base::Type::isDerivedFrom(), Gui::View3DInventorViewer::removeViewProvider(), Gui::Application::setEditDocument(), setModified(), and signalDeletedObject.
Referenced by Document().
slotFinishImportObjects()
void Document::slotFinishImportObjects (const std::vector< App::DocumentObject * > & objs) protected
Definition at line 1945 of file Gui/Document.cpp.
References replaceobj::objs.
Referenced by Document().
slotFinishRestoreDocument()
void Document::slotFinishRestoreDocument (const App::Document & doc) protected
Definition at line 1744 of file Gui/Document.cpp.
References Gui::DocumentP::_pcDocument, Gui::DocumentP::connectActObjectBlocker, toolbit-attributes::doc, Base::Persistence::getClassTypeId(), getViewProvider(), Base::BaseClass::isDerivedFrom(), App::Document::LinkStampChanged, setModified(), and signalActivatedObject.
Referenced by Document().
slotFinishRestoreObject()
void Document::slotFinishRestoreObject (const App::DocumentObject & obj) protected
Definition at line 1734 of file Gui/Document.cpp.
References getViewProvider(), Gui::isRestoring, Gui::ViewProvider::setStatus(), and toggleInSceneGraph().
Referenced by Document().
slotNewObject()
void Document::slotNewObject (const App::DocumentObject & Obj) protected
This slot is connected to the App::Document::signalNewObject(...)
Definition at line 893 of file Gui/Document.cpp.
References Gui::DocumentP::_changeViewTouchDocument, Gui::DocumentP::_CoinMap, Gui::DocumentP::_isTransacting, Gui::DocumentP::_redoViewProviders, Gui::DocumentP::_ViewProviderMap, Gui::View3DInventorViewer::addViewProvider(), Gui::DocumentP::baseViews, SCL.SimpleDataTypes::e, FC_ERR, FC_LOG, FC_WARN, Base::Persistence::getClassTypeId(), App::DocumentObject::getFullName(), Base::Type::getTypeIfDerivedFrom(), Gui::View3DInventor::getViewer(), getViewProvider(), App::DocumentObject::getViewProviderName(), App::DocumentObject::getViewProviderNameStored(), setModified(), signalNewObject, Gui::TouchDocument, and Path.Post.scripts.grbl_post::type.
Referenced by Document().
slotRecomputed()
void Document::slotRecomputed (const App::Document & doc) protected
Definition at line 1142 of file Gui/Document.cpp.
References Gui::DocumentP::_pcDocument, toolbit-attributes::doc, Gui::getMainWindow(), Gui::MainWindow::updateActions(), and Gui::TreeWidget::updateStatus().
Referenced by Document().
slotRedoDocument()
void Document::slotRedoDocument (const App::Document & doc) protected
Definition at line 1133 of file Gui/Document.cpp.
References Gui::DocumentP::_pcDocument, toolbit-attributes::doc, Gui::getMainWindow(), signalRedoDocument, and Gui::MainWindow::updateActions().
Referenced by Document().
slotRelabelObject()
void Document::slotRelabelObject (const App::DocumentObject & Obj) protected
Definition at line 1079 of file Gui/Document.cpp.
References Base::Persistence::getClassTypeId(), getViewProvider(), Base::BaseClass::isDerivedFrom(), and signalRelabelObject.
Referenced by Document().
slotShowHidden()
void Document::slotShowHidden (const App::Document & doc) protected
Definition at line 1761 of file Gui/Document.cpp.
References Gui::DocumentP::_pcDocument, toolbit-attributes::doc, Gui::Application::Instance, and Gui::Application::signalShowHidden.
Referenced by Document().
slotSkipRecompute()
void Document::slotSkipRecompute (const App::Document & doc, const std::vector< App::DocumentObject * > & objs) protected
Definition at line 1155 of file Gui/Document.cpp.
References Gui::DocumentP::_pcDocument, App::Document::AllowPartialRecompute, toolbit-attributes::doc, Gui::Application::editDocument(), App::Application::getActiveDocument(), App::GetApplication(), Gui::Application::Instance, App::DocumentObject::isAttachedToDocument(), replaceobj::objs, and App::DocumentObject::recomputeFeature().
Referenced by Document().
slotStartRestoreDocument()
void Document::slotStartRestoreDocument (const App::Document & doc) protected
Definition at line 1726 of file Gui/Document.cpp.
References Gui::DocumentP::_pcDocument, Gui::DocumentP::connectActObjectBlocker, and toolbit-attributes::doc.
Referenced by Document().
slotTouchedObject()
void Document::slotTouchedObject (const App::DocumentObject & Obj) protected
Definition at line 1177 of file Gui/Document.cpp.
References FC_LOG, App::DocumentObject::getFullName(), Gui::getMainWindow(), isModified(), setModified(), and Gui::MainWindow::updateActions().
Referenced by Document().
slotTransactionAppend()
void Document::slotTransactionAppend (const App::DocumentObject & obj, App::Transaction * transaction) protected
Definition at line 1087 of file Gui/Document.cpp.
References App::Transaction::addObjectDel(), Base::Persistence::getClassTypeId(), getViewProvider(), and Base::BaseClass::isDerivedFrom().
Referenced by Document().
slotTransactionRemove()
void Document::slotTransactionRemove (const App::DocumentObject & obj, App::Transaction * transaction) protected
Definition at line 1095 of file Gui/Document.cpp.
References Gui::DocumentP::_CoinMap, Gui::DocumentP::_ViewProviderMap, App::Transaction::addObjectNew(), and Gui::ViewProvider::getRoot().
Referenced by Document().
slotUndoDocument()
void Document::slotUndoDocument (const App::Document & doc) protected
Definition at line 1124 of file Gui/Document.cpp.
References Gui::DocumentP::_pcDocument, toolbit-attributes::doc, Gui::getMainWindow(), signalUndoDocument, and Gui::MainWindow::updateActions().
Referenced by Document().
takeAnnotationViewProvider()
ViewProvider * Document::takeAnnotationViewProvider (const char * name)
remove an annotation view provider from the document and return it
Definition at line 787 of file Gui/Document.cpp.
References Gui::DocumentP::_ViewProviderMapAnnotation, and Gui::DocumentP::baseViews.
Referenced by removeAnnotationViewProvider().
toggleInSceneGraph()
void Document::toggleInSceneGraph (ViewProvider * vp)
Add or remove view provider from scene graphs of all views
It calls ViewProvider::canAddToSceneGraph() to decide whether to add the view provider or remove it
Definition at line 2734 of file Gui/Document.cpp.
References Gui::DocumentP::baseViews, Gui::ViewProvider::canAddToSceneGraph(), and Gui::ViewProvider::getRoot().
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::onChanged(), and slotFinishRestoreObject().
undo()
void Document::undo (int iSteps)
Will UNDO one or more steps.
Definition at line 2625 of file Gui/Document.cpp.
References Gui::DocumentP::_isTransacting, App::GetApplication(), getDocument(), SplineSurface::i, App::Application::signalUndo, and App::Document::undo().
Referenced by Gui::View3DInventor::onMsg(), TechDrawGui::TaskRichAnno::removeFeature(), and TechDrawGui::TaskLeaderLine::removeFeature().
Friends And Related Function Documentation
TransactionViewProvider
friend class TransactionViewProvider friend
Definition at line 344 of file Gui/Document.h.
Member Data Documentation
_pcDocPy
Gui::DocumentPy* Gui::Document::_pcDocPy protected
Definition at line 317 of file Gui/Document.h.
Referenced by Document(), getPyObject(), and ~Document().
signalActivatedObject
boost::signals2::signal<void (const Gui::ViewProviderDocumentObject&)> Gui::Document::signalActivatedObject mutable
signal on activated Object
Definition at line 115 of file Gui/Document.h.
Referenced by slotActivatedObject(), and slotFinishRestoreDocument().
signalChangedObject
boost::signals2::signal<void (const Gui::ViewProviderDocumentObject&, const App::Property&)> Gui::Document::signalChangedObject mutable
signal on changed Object, the 2nd argument is the changed property of the referenced document object, not of the view provider
Definition at line 111 of file Gui/Document.h.
Referenced by Gui::ViewProviderLink::finishRestoring(), Gui::DAG::Model::Model(), and slotChangedObject().
signalDeletedObject
boost::signals2::signal<void (const Gui::ViewProviderDocumentObject&)> Gui::Document::signalDeletedObject mutable
signal on deleted Object
Definition at line 107 of file Gui/Document.h.
Referenced by Gui::DAG::Model::Model(), slotDeletedObject(), Gui::ManualAlignment::startAlignment(), and PartGui::TaskAttacher::TaskAttacher().
signalDeleteDocument
boost::signals2::signal<void (const Gui::Document& doc)> Gui::Document::signalDeleteDocument mutable
signal on deleting Document
Definition at line 140 of file Gui/Document.h.
Referenced by PartGui::TaskAttacher::TaskAttacher().
signalExpandObject
boost::signals2::signal<void (const Gui::ViewProviderDocumentObject&, const Gui::TreeItemMode&, App::DocumentObject *parent, const char *subname)> Gui::Document::signalExpandObject mutable
signal on changed Object, the 2nd argument is the highlite mode to use
Definition at line 130 of file Gui/Document.h.
Referenced by importObjects(), and RestoreDocFile().
signalHighlightObject
boost::signals2::signal<void (const Gui::ViewProviderDocumentObject&, const Gui::HighlightMode&, bool, App::DocumentObject *parent, const char *subname)> Gui::Document::signalHighlightObject mutable
signal on changed Object, the 2nd argument is the highlite mode to use
Definition at line 125 of file Gui/Document.h.
Referenced by FemGui::ActiveAnalysisObserver::highlightActiveObject().
signalInEdit
boost::signals2::signal<void (const Gui::ViewProviderDocumentObject&)> Gui::Document::signalInEdit mutable
signal on entering in edit mode
Definition at line 117 of file Gui/Document.h.
Referenced by Gui::DAG::Model::Model().
signalNewObject
boost::signals2::signal<void (const Gui::ViewProviderDocumentObject&)> Gui::Document::signalNewObject mutable
signal on new Object
Definition at line 105 of file Gui/Document.h.
Referenced by Gui::DAG::Model::Model(), and slotNewObject().
signalRedoDocument
boost::signals2::signal<void (const Gui::Document& doc)> Gui::Document::signalRedoDocument mutable
signal on redo Document
Definition at line 138 of file Gui/Document.h.
Referenced by SketcherGui::ViewProviderSketch::setEdit(), and slotRedoDocument().
signalRelabelObject
boost::signals2::signal<void (const Gui::ViewProviderDocumentObject&)> Gui::Document::signalRelabelObject mutable
signal on renamed Object
Definition at line 113 of file Gui/Document.h.
Referenced by slotRelabelObject().
signalResetEdit
boost::signals2::signal<void (const Gui::ViewProviderDocumentObject&)> Gui::Document::signalResetEdit mutable
signal on leaving edit mode
Definition at line 119 of file Gui/Document.h.
Referenced by _resetEdit(), and Gui::DAG::Model::Model().
signalScrollToObject
boost::signals2::signal<void (const Gui::ViewProviderDocumentObject&)> Gui::Document::signalScrollToObject mutable
signal on scrolling to an object
Definition at line 134 of file Gui/Document.h.
signalShowItem
boost::signals2::signal<void (const Gui::ViewProviderDocumentObject&)> Gui::Document::signalShowItem mutable
signal on changed ShowInTree property in view provider
Definition at line 132 of file Gui/Document.h.
signalUndoDocument
boost::signals2::signal<void (const Gui::Document& doc)> Gui::Document::signalUndoDocument mutable
signal on undo Document
Definition at line 136 of file Gui/Document.h.
Referenced by PartGui::FaceAppearances::FaceAppearances(), SketcherGui::ViewProviderSketch::setEdit(), and slotUndoDocument().
The documentation for this class was generated from the following files:
Gui/Document.h
Gui/Document.cpp