FreeCAD: PointsGui::ViewProviderPointsBuilder Class Reference
PointsGui::ViewProviderPointsBuilder Class Reference
#include <ViewProvider.h>
Public Member Functions
ViewProviderPointsBuilder ()=default
~ViewProviderPointsBuilder () override=default
void buildNodes (const App::Property *, std::vector< SoNode * > &) const override
void createPoints (const App::Property *, SoCoordinate3 *, SoPointSet *) const
void createPoints (const App::Property *, SoCoordinate3 *, SoIndexedPointSet *) const
Public Member Functions inherited from Gui::ViewProviderBuilder
ViewProviderBuilder ()
Constructor.
virtual ~ViewProviderBuilder ()
Additional Inherited Members
Static Public Member Functions inherited from Gui::ViewProviderBuilder
static void add (const Base::Type &, const Base::Type &)
static ViewProvider * create (const Base::Type &)
static SoFCSelection * createSelection ()
Detailed Description
Definition at line 63 of file Mod/Points/Gui/ViewProvider.h.
Constructor & Destructor Documentation
ViewProviderPointsBuilder()
PointsGui::ViewProviderPointsBuilder::ViewProviderPointsBuilder () default
~ViewProviderPointsBuilder()
PointsGui::ViewProviderPointsBuilder::~ViewProviderPointsBuilder () override default
Member Function Documentation
buildNodes()
void ViewProviderPointsBuilder::buildNodes (const App::Property * prop, std::vector< SoNode * > & nodes) const override virtual
Implements Gui::ViewProviderBuilder.
Definition at line 678 of file Mod/Points/Gui/ViewProvider.cpp.
createPoints() [1/2]
void ViewProviderPointsBuilder::createPoints (const App::Property * prop, SoCoordinate3 * coords, SoIndexedPointSet * points) const
Definition at line 728 of file Mod/Points/Gui/ViewProvider.cpp.
References Points::PointKernel::getBasicPoints(), Points::PropertyPointKernel::getValue(), RobotExample::pos, Points::PointKernel::size(), and SurfaceTests.TestBlendCurve::vec.
createPoints() [2/2]
void ViewProviderPointsBuilder::createPoints (const App::Property * prop, SoCoordinate3 * coords, SoPointSet * points) const
Definition at line 704 of file Mod/Points/Gui/ViewProvider.cpp.
References Points::PointKernel::getBasicPoints(), Points::PropertyPointKernel::getValue(), Points::PointKernel::size(), and SurfaceTests.TestBlendCurve::vec.
Referenced by PointsGui::ViewProviderScattered::updateData(), and PointsGui::ViewProviderStructured::updateData().
The documentation for this class was generated from the following files:
Mod/Points/Gui/ViewProvider.h
Mod/Points/Gui/ViewProvider.cpp