FreeCAD: TechDrawGui::QGIViewSymbol Class Reference
TechDrawGui::QGIViewSymbol Class Reference
#include <QGIViewSymbol.h>
Public Types
enum { Type = QGraphicsItem::UserType + 121 }
Public Types inherited from TechDrawGui::QGIView
enum { Type = QGraphicsItem::UserType + 101 }
Public Member Functions
QGIViewSymbol ()
~QGIViewSymbol () override
int type () const override
void updateView (bool update=false) override
void setViewSymbolFeature (TechDraw::DrawViewSymbol *obj)
void draw () override
void rotateView () override
Public Member Functions inherited from TechDrawGui::QGIView
QGIView ()
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
const char * getViewName () const
const std::string getViewNameAsString () const
void setViewFeature (TechDraw::DrawView *obj)
TechDraw::DrawView * getViewObject () const
MDIViewPage * getMDIViewPage () const
double getScale ()
void hideFrame ()
virtual bool getFrameState ()
virtual void toggleCache (bool state)
virtual void drawBorder ()
virtual void isVisible (bool state)
virtual bool isVisible ()
virtual bool getGroupSelection ()
virtual void setGroupSelection (bool isSelected)
virtual void setGroupSelection (bool isSelected, const std::vector< std::string > &subNames)
virtual void drawCaption ()
void makeMark (double xPos, double yPos, QColor color=Qt::red)
void makeMark (Base::Vector3d pos, QColor color=Qt::red)
void makeMark (QPointF pos, QColor color=Qt::red)
void setPosition (qreal xPos, qreal yPos)
qreal getY ()
bool isInnerView () const
void isInnerView (bool state)
QGIViewClip * getClipGroup ()
bool isSnapping ()
void snapPosition (QPointF &position)
void snapSectionView (const TechDraw::DrawViewSection *sectionView, QPointF &newPosition)
Base::Vector3d projItemPagePos (TechDraw::DrawViewPart *item)
void alignTo (QGraphicsItem *, const QString &alignment)
QColor prefNormalColor ()
QColor getNormalColor ()
void setNormalColor (QColor color)
QColor getPreColor ()
QColor getSelectColor ()
QColor getCurrentColor ()
void setCurrentColor (QColor color)
QColor getSettingColor ()
void setSettingColor (QColor color)
virtual void setStack (int z)
virtual void setStackFromVP ()
QFont getFont ()
void setFont (QFont font)
virtual void removeChild (QGIView *child)
virtual void addArbitraryItem (QGraphicsItem *qgi)
virtual void switchParentItem (QGIView *targetParent)
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
Protected Member Functions
virtual void drawSvg ()
void symbolToSvg (QByteArray qba)
double legacyScaler (TechDraw::DrawViewSymbol *feature) const
double symbolScaler (TechDraw::DrawViewSymbol *feature) const
Protected Member Functions inherited from TechDrawGui::QGIView
QGIView * getQGIVByName (std::string name)
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QRectF customChildrenBoundingRect () const
void dumpRect (const char *text, QRectF rect)
Base::Reference< ParameterGrp > getParmGroupCol ()
Protected Attributes
QGDisplayArea * m_displayArea
QGCustomSvg * m_svgItem
Additional Inherited Members
Static Public Member Functions inherited from TechDrawGui::QGIView
static Gui::ViewProvider * getViewProvider (App::DocumentObject *obj)
static ViewProviderPage * getViewProviderPage (TechDraw::DrawView *dView)
static int calculateFontPixelSize (double sizeInMillimetres)
static int calculateFontPixelWidth (const QFont &font)
static QString getPrefFont ()
static double getPrefFontSize ()
static double getDimFontSize ()
static int exactFontSize (std::string fontFamily, double nominalSize)
Static Public Attributes inherited from TechDrawGui::QGIView
static const double DefaultFontSizeInMM = 5.0
Detailed Description
Definition at line 43 of file QGIViewSymbol.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 49 of file QGIViewSymbol.h.
Constructor & Destructor Documentation
QGIViewSymbol()
QGIViewSymbol::QGIViewSymbol ()
Definition at line 50 of file QGIViewSymbol.cpp.
~QGIViewSymbol()
QGIViewSymbol::~QGIViewSymbol () override
Definition at line 68 of file QGIViewSymbol.cpp.
Member Function Documentation
draw()
void QGIViewSymbol::draw () override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 96 of file QGIViewSymbol.cpp.
References TechDrawGui::QGIView::draw().
drawSvg()
void QGIViewSymbol::drawSvg () protected virtual
Definition at line 106 of file QGIViewSymbol.cpp.
References importers.exportIFCStructuralTools::scaling.
legacyScaler()
double QGIViewSymbol::legacyScaler (TechDraw::DrawViewSymbol * feature) const protected
this is the original scaling logic as used in versions <= 1.0 it does not scale correctly for svg files that use mm units, but is available for backwards compatibility. Set General/LegacySvgScaling to true to use this method.
Definition at line 165 of file QGIViewSymbol.cpp.
References Base::Persistence::getClassTypeId(), TechDrawGui::Rez::getRezFactor(), TechDraw::DrawView::getScale(), Base::BaseClass::isDerivedFrom(), and importers.exportIFCStructuralTools::scaling.
rotateView()
void QGIViewSymbol::rotateView () override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 154 of file QGIViewSymbol.cpp.
setViewSymbolFeature()
void QGIViewSymbol::setViewSymbolFeature (TechDraw::DrawViewSymbol * obj)
Definition at line 73 of file QGIViewSymbol.cpp.
symbolScaler()
double QGIViewSymbol::symbolScaler (TechDraw::DrawViewSymbol * feature) const protected
new symbol scaling logic as of v1.1 svg in mm scales correctly. svg in px will be drawn using scene units (0.1 mm) as pixels.
Definition at line 187 of file QGIViewSymbol.cpp.
References TechDrawGui::Rez::getRezFactor(), TechDraw::DrawView::getScale(), App::PropertyString::getValue(), src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression, importers.exportIFCStructuralTools::scaling, and TechDraw::DrawViewSymbol::Symbol.
symbolToSvg()
void QGIViewSymbol::symbolToSvg (QByteArray qba) protected
Definition at line 127 of file QGIViewSymbol.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), and TechDrawGui::PreferencesGui::getAccessibleQColor().
type()
int TechDrawGui::QGIViewSymbol::type () const inline override
Definition at line 50 of file QGIViewSymbol.h.
updateView()
void QGIViewSymbol::updateView (bool update = false) override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 79 of file QGIViewSymbol.cpp.
References TechDrawGui::QGIView::updateView().
Member Data Documentation
m_displayArea
QGDisplayArea* TechDrawGui::QGIViewSymbol::m_displayArea protected
Definition at line 65 of file QGIViewSymbol.h.
m_svgItem
QGCustomSvg* TechDrawGui::QGIViewSymbol::m_svgItem protected
Definition at line 66 of file QGIViewSymbol.h.
The documentation for this class was generated from the following files:
QGIViewSymbol.h
QGIViewSymbol.cpp