FreeCAD: Base::SequencerLauncher Class Reference
Base::SequencerLauncher Class Reference
#include <Sequencer.h>
Public Member Functions
SequencerLauncher (const char *pszStr, size_t steps)
~SequencerLauncher ()
size_t numberOfSteps () const
void setText (const char *pszTxt)
bool next (bool canAbort=false)
void setProgress (size_t)
bool wasCanceled () const
SequencerLauncher (const SequencerLauncher &)=delete
SequencerLauncher (SequencerLauncher &&)=delete
void operator= (const SequencerLauncher &)=delete
void operator= (SequencerLauncher &&)=delete
Detailed Description
The SequencerLauncher class is provided for convenience. It allows you to run an instance of the sequencer by instantiating an object of this class – most suitable on the stack. So this mechanism can be used for try-catch-blocks to destroy the object automatically if the C++ exception mechanism cleans up the stack.
This class has been introduced to simplify the use with the sequencer. In the FreeCAD Gui layer there is a subclass of SequencerBase called ProgressBar that grabs the keyboard and filters most of the incoming events. If the programmer uses the API of SequencerBase directly to start an instance without due diligence with exceptions then a not handled exception could block the whole application – the user has to kill the application then.
Below is an example of a not correctly used sequencer.
 #include <Base/Sequencer.h>
 void runOperation();
 void myTest()
 {
   try{
      runOperation();
   } catch(...) {
      // the programmer forgot to stop the sequencer here
      // Under circumstances the sequencer never gets stopped so the keyboard never gets
ungrabbed and
      // all Gui events still gets filtered.
   }
 }
 void runOperation()
 {
   Base::Sequencer().start ("my text", 10);
   for (int i=0; i<10; i++)
   {
     // do something where an exception be thrown
     ...
     Base::Sequencer().next ();
   }
   Base::Sequencer().stop ();
 }
To avoid such problems the SequencerLauncher class can be used as follows:
#include <Base/Sequencer.h>
void runOperation();
void myTest()
{
  try{
     runOperation();
  } catch(...) {
     // the programmer forgot to halt the sequencer here
     // If SequencerLauncher leaves its scope the object gets destructed automatically and
     // stops the running sequencer.
  }
}
void runOperation()
{
  // create an instance on the stack (not on any terms on the heap)
  SequencerLauncher seq("my text", 10);
  for (int i=0; i<10; i++)
  {
    // do something (e.g. here can be thrown an exception)
    ...
    seq.next ();
  }
}
Author
Werner Mayer
Definition at line 388 of file Sequencer.h.
Constructor & Destructor Documentation
SequencerLauncher() [1/3]
SequencerLauncher::SequencerLauncher (const char * pszStr, size_t steps)
Definition at line 237 of file Sequencer.cpp.
References Base::SequencerP::_topLauncher, Base::SequencerBase::Instance(), Base::SequencerP::mutex, and Base::SequencerBase::start().
~SequencerLauncher()
SequencerLauncher::~SequencerLauncher ()
Definition at line 247 of file Sequencer.cpp.
References Base::SequencerP::_topLauncher, Base::SequencerBase::Instance(), Base::SequencerP::mutex, and Base::SequencerBase::stop().
SequencerLauncher() [2/3]
Base::SequencerLauncher::SequencerLauncher (const SequencerLauncher &) delete
SequencerLauncher() [3/3]
Base::SequencerLauncher::SequencerLauncher (SequencerLauncher &&) delete
Member Function Documentation
next()
bool SequencerLauncher::next (bool canAbort = false)
Definition at line 262 of file Sequencer.cpp.
References Base::SequencerP::_topLauncher, Base::SequencerBase::Instance(), Base::SequencerP::mutex, and Base::SequencerBase::next().
Referenced by CmdTestProgress1::activated(), CmdTestProgress2::activated(), CmdTestProgress3::activated(), CmdTestProgress4::activated(), MeshCore::MeshBuilder::AddFacet(), PartGui::CrossSections::apply(), Reen::BSplineParameterCorrection::CalcFirstSmoothMatrix(), Reen::BSplineParameterCorrection::CalcSecondSmoothMatrix(), Reen::BSplineParameterCorrection::CalcThirdSmoothMatrix(), MeshCore::MeshTrimming::CheckFacets(), MeshCore::MeshAlgorithm::CheckFacets(), MeshCore::MeshCurvature::ComputePerFace(), Reen::BSplineParameterCorrection::DoParameterCorrection(), MeshCore::MeshEvalTopology::Evaluate(), MeshCore::MeshEvalSelfIntersection::Evaluate(), MeshCore::MeshEvalNeighbourhood::Evaluate(), Robot::Edge2TracObject::execute(), Inspection::Feature::execute(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), MeshCore::MeshEvalNeighbourhood::GetIndices(), MeshCore::MeshIntersection::getIntersection(), MeshCore::MeshEvalSelfIntersection::GetIntersections(), Points::PointsAlgos::LoadAscii(), MeshPart::CurveProjectorWithToolMesh::makeToolMesh(), App::Application::openDocuments(), Base::FutureWatcherProgress::progressValueChanged(), MeshPart::CurveProjectorSimple::projectCurve(), MeshPart::MeshProjection::projectEdgeToEdge(), MeshPart::MeshProjection::projectOnMesh(), MeshPart::MeshProjection::projectParallelToMesh(), MeshPart::MeshProjection::projectToMesh(), Base::XMLReader::readFiles(), Sandbox::WorkerThread::run(), BarThread::run(), MeshCore::WriterOBJ::Save(), MeshCore::MeshOutput::SaveAsciiSTL(), MeshCore::MeshOutput::SaveBinarySTL(), MeshCore::MeshOutput::SaveNastran(), MeshCore::MeshOutput::SaveOFF(), MeshCore::MeshOutput::SaveSMF(), MeshCore::MeshOutput::SaveVRML(), and MeshCore::MeshTrimming::TrimFacets().
numberOfSteps()
size_t SequencerLauncher::numberOfSteps () const
Definition at line 277 of file Sequencer.cpp.
References Base::SequencerBase::Instance(), Base::SequencerP::mutex, and Base::SequencerBase::numberOfSteps().
operator=() [1/2]
void Base::SequencerLauncher::operator= (const SequencerLauncher &) delete
operator=() [2/2]
void Base::SequencerLauncher::operator= (SequencerLauncher &&) delete
setProgress()
void SequencerLauncher::setProgress (size_t pos)
Definition at line 271 of file Sequencer.cpp.
References Base::SequencerBase::Instance(), Base::SequencerP::mutex, RobotExample::pos, and Base::SequencerBase::setProgress().
setText()
void SequencerLauncher::setText (const char * pszTxt)
Definition at line 256 of file Sequencer.cpp.
References Base::SequencerBase::Instance(), Base::SequencerP::mutex, and Base::SequencerBase::setText().
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_readme_browser.WidgetReadmeBrowser::setMarkdown().
wasCanceled()
bool SequencerLauncher::wasCanceled () const
Definition at line 283 of file Sequencer.cpp.
References Base::SequencerBase::Instance(), and Base::SequencerBase::wasCanceled().
The documentation for this class was generated from the following files:
Sequencer.h
Sequencer.cpp