FreeCAD: Gui::Dialog::ApplicationCache Class Reference
Gui::Dialog::ApplicationCache Class Reference
#include <DlgSettingsCacheDirectory.h>
Public Types
enum Period {
Period::Always, Period::Daily, Period::Weekly, Period::Monthly,
Period::Yearly, Period::Never
}
Public Member Functions
ApplicationCache ()
void applyUserSettings ()
ApplicationCache::applyUserSettings Set period and limit according to user settings.
void setPeriod (Period)
ApplicationCache::setPeriod Set the period to check for the cache size.
void setLimit (qint64)
ApplicationCache::setLimit Set the limit in bytes to perform a check.
bool periodicCheckOfSize () const
ApplicationCache::periodicCheckOfSize Checks if the periodic check should be performed now.
qint64 size () const
ApplicationCache::size Determines the size of the cache.
bool performAction (qint64)
ApplicationCache::performAction If the cache size total is higher than the limit then show a dialog to the user.
Static Public Member Functions
static QString toString (qint64 size)
static qint64 toBytes (unsigned int)
Detailed Description
Definition at line 104 of file DlgSettingsCacheDirectory.h.
Member Enumeration Documentation
Period
enum Gui::Dialog::ApplicationCache::Period strong
Enumerator
Always
Daily
Weekly
Monthly
Yearly
Never
Definition at line 109 of file DlgSettingsCacheDirectory.h.
Constructor & Destructor Documentation
ApplicationCache()
ApplicationCache::ApplicationCache ()
Definition at line 155 of file DlgSettingsCacheDirectory.cpp.
References Base::pow(), setPeriod(), and Weekly.
Member Function Documentation
applyUserSettings()
void ApplicationCache::applyUserSettings ()
ApplicationCache::applyUserSettings Set period and limit according to user settings.
Definition at line 333 of file DlgSettingsCacheDirectory.cpp.
References Gui::Dialog::ApplicationCacheSettings::getCacheSizeLimit(), Gui::Dialog::ApplicationCacheSettings::getCheckPeriod(), setLimit(), setPeriod(), and toBytes().
Referenced by Gui::Application::checkForPreviousCrashes().
performAction()
bool ApplicationCache::performAction (qint64 total)
ApplicationCache::performAction If the cache size total is higher than the limit then show a dialog to the user.
Parameters
total
Definition at line 234 of file DlgSettingsCacheDirectory.cpp.
References Gui::getMainWindow(), App::Application::getUserCachePath(), toString(), and importDXF::warn().
Referenced by Gui::Application::checkForPreviousCrashes().
periodicCheckOfSize()
bool ApplicationCache::periodicCheckOfSize () const
ApplicationCache::periodicCheckOfSize Checks if the periodic check should be performed now.
Returns
Definition at line 205 of file DlgSettingsCacheDirectory.cpp.
References App::Application::Config(), App::Application::getExecutableName(), and Path.Post.scripts.dumper_post::now.
Referenced by Gui::Application::checkForPreviousCrashes().
setLimit()
void ApplicationCache::setLimit (qint64 value)
ApplicationCache::setLimit Set the limit in bytes to perform a check.
Parameters
value
Definition at line 195 of file DlgSettingsCacheDirectory.cpp.
Referenced by applyUserSettings().
setPeriod()
void ApplicationCache::setPeriod (ApplicationCache::Period period)
ApplicationCache::setPeriod Set the period to check for the cache size.
Parameters
period
Definition at line 166 of file DlgSettingsCacheDirectory.cpp.
References Always, Daily, Monthly, Never, Weekly, and Yearly.
Referenced by ApplicationCache(), and applyUserSettings().
size()
qint64 ApplicationCache::size () const
ApplicationCache::size Determines the size of the cache.
Returns
Definition at line 276 of file DlgSettingsCacheDirectory.cpp.
References App::Application::getUserCachePath().
Referenced by Gui::Application::checkForPreviousCrashes(), Path.Post.Utils.GCodeEditorDialog::done(), and toString().
toBytes()
qint64 ApplicationCache::toBytes (unsigned int sizeInMB) static
Definition at line 342 of file DlgSettingsCacheDirectory.cpp.
Referenced by applyUserSettings().
toString()
QString ApplicationCache::toString (qint64 size) static
Definition at line 348 of file DlgSettingsCacheDirectory.cpp.
References SplineSurface::i, and size().
Referenced by performAction().
The documentation for this class was generated from the following files:
DlgSettingsCacheDirectory.h
DlgSettingsCacheDirectory.cpp