FreeCAD: DrawingGui::orthoview Class Reference
DrawingGui::orthoview Class Reference
#include <TaskOrthoViews.h>
Public Member Functions
orthoview (App::Document *parent, App::DocumentObject *part, App::DocumentObject *page, Base::BoundBox3d *partbox)
~orthoview ()
void set_data (int r_x, int r_y)
void set_projection (const gp_Ax2 &cs)
void setPos (float=0, float=0)
void setScale (float newscale)
float getScale ()
void deleteme ()
void hidden (bool)
void smooth (bool)
App::DocumentObject * getViewPart ()
Public Attributes
bool ortho
bool auto_scale
int rel_x
int rel_y
bool away
bool tri
int axo
gp_Dir up
gp_Dir right
Detailed Description
Definition at line 64 of file TaskOrthoViews.h.
Constructor & Destructor Documentation
orthoview()
orthoview::orthoview (App::Document * parent, App::DocumentObject * part, App::DocumentObject * page, Base::BoundBox3d * partbox)
Definition at line 139 of file TaskOrthoViews.cpp.
References importDXF::addObject(), Base::BoundBox3< Precision >::GetCenter(), Init::parent, MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
~orthoview()
orthoview::~orthoview ()
Definition at line 172 of file TaskOrthoViews.cpp.
Member Function Documentation
deleteme()
void orthoview::deleteme ()
Definition at line 187 of file TaskOrthoViews.cpp.
getScale()
float orthoview::getScale ()
Definition at line 212 of file TaskOrthoViews.cpp.
References draftfunctions.scale::scale().
getViewPart()
App::DocumentObject* DrawingGui::orthoview::getViewPart () inline
Definition at line 82 of file TaskOrthoViews.h.
hidden()
void orthoview::hidden (bool state)
Definition at line 223 of file TaskOrthoViews.cpp.
set_data()
void orthoview::set_data (int r_x, int r_y)
Definition at line 175 of file TaskOrthoViews.cpp.
Referenced by DrawingGui::OrthoViews::add_view().
set_projection()
void orthoview::set_projection (const gp_Ax2 & cs)
Definition at line 233 of file TaskOrthoViews.cpp.
References KDL::abs(), M_PI, MovieTool::x, and MovieTool::y.
setPos()
void orthoview::setPos (float px = 0, float py = 0)
Definition at line 192 of file TaskOrthoViews.cpp.
References MovieTool::x, and MovieTool::y.
setScale()
void orthoview::setScale (float newscale)
Definition at line 206 of file TaskOrthoViews.cpp.
smooth()
void orthoview::smooth (bool state)
Definition at line 228 of file TaskOrthoViews.cpp.
Member Data Documentation
auto_scale
bool DrawingGui::orthoview::auto_scale
Definition at line 92 of file TaskOrthoViews.h.
away
bool DrawingGui::orthoview::away
Definition at line 94 of file TaskOrthoViews.h.
axo
int DrawingGui::orthoview::axo
Definition at line 95 of file TaskOrthoViews.h.
ortho
bool DrawingGui::orthoview::ortho
Definition at line 91 of file TaskOrthoViews.h.
rel_x
int DrawingGui::orthoview::rel_x
Definition at line 93 of file TaskOrthoViews.h.
rel_y
int DrawingGui::orthoview::rel_y
Definition at line 93 of file TaskOrthoViews.h.
right
gp_Dir DrawingGui::orthoview::right
Definition at line 97 of file TaskOrthoViews.h.
tri
bool DrawingGui::orthoview::tri
Definition at line 94 of file TaskOrthoViews.h.
up
gp_Dir DrawingGui::orthoview::up
Definition at line 96 of file TaskOrthoViews.h.
The documentation for this class was generated from the following files:
TaskOrthoViews.h
TaskOrthoViews.cpp