FreeCAD: Points::PointsGridIterator Class Reference
Points::PointsGridIterator Class Reference
#include <PointsGrid.h>
Public Member Functions
PointsGridIterator (const PointsGrid &rclG)
Construction.
Base::BoundBox3d GetBoundBox () const
void GetElements (std::vector< unsigned long > &raulElements) const
Iteration
void Init ()
bool More () const
void Next ()
Tests with rays
bool InitOnRay (const Base::Vector3d &rclPt, const Base::Vector3d &rclDir, std::vector< unsigned long > &raulElements)
bool InitOnRay (const Base::Vector3d &rclPt, const Base::Vector3d &rclDir, float fMaxSearchArea, std::vector< unsigned long > &raulElements)
bool NextOnRay (std::vector< unsigned long > &raulElements)
void GetGridPos (unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
Detailed Description
The PointsGridIterator class provides an interface to walk through all grid elements of a point grid.
Definition at line 217 of file PointsGrid.h.
Constructor & Destructor Documentation
PointsGridIterator()
PointsGridIterator::PointsGridIterator (const PointsGrid & rclG) explicit
Construction.
Definition at line 788 of file PointsGrid.cpp.
Member Function Documentation
GetBoundBox()
Base::BoundBox3d Points::PointsGridIterator::GetBoundBox () const inline
Returns the bounding box of the current grid element.
Definition at line 223 of file PointsGrid.h.
Referenced by Points::PointsGrid::Verify().
GetElements()
void Points::PointsGridIterator::GetElements (std::vector< unsigned long > & raulElements) const inline
Returns indices of the elements in the current grid.
Definition at line 228 of file PointsGrid.h.
Referenced by Points::PointsGrid::Verify().
GetGridPos()
void Points::PointsGridIterator::GetGridPos (unsigned long & rulX, unsigned long & rulY, unsigned long & rulZ) const inline
Returns the grid number of the current position.
Definition at line 281 of file PointsGrid.h.
Init()
void Points::PointsGridIterator::Init () inline
Sets the iterator to the first element
Definition at line 237 of file PointsGrid.h.
Referenced by Points::PointsGrid::Verify().
InitOnRay() [1/2]
bool PointsGridIterator::InitOnRay (const Base::Vector3d & rclPt, const Base::Vector3d & rclDir, float fMaxSearchArea, std::vector< unsigned long > & raulElements)
Searches for facets around the ray.
Definition at line 794 of file PointsGrid.cpp.
References InitOnRay().
InitOnRay() [2/2]
bool PointsGridIterator::InitOnRay (const Base::Vector3d & rclPt, const Base::Vector3d & rclDir, std::vector< unsigned long > & raulElements)
Searches for facets around the ray.
Definition at line 804 of file PointsGrid.cpp.
References FLOAT_MAX, Points::PointsGrid::GetBoundBox(), Base::BoundBox3< Precision >::IntersectWithLine(), Base::BoundBox3< Precision >::IsInBox(), FreeCADInit::Length, and Points::PointsGrid::Position().
Referenced by InitOnRay().
More()
bool Points::PointsGridIterator::More () const inline
Checks if the iterator has not yet reached the end position.
Definition at line 242 of file PointsGrid.h.
Referenced by Points::PointsGrid::Verify().
Next()
void Points::PointsGridIterator::Next () inline
Go to the next grid.
Definition at line 247 of file PointsGrid.h.
Referenced by Points::PointsGrid::Verify().
NextOnRay()
bool PointsGridIterator::NextOnRay (std::vector< unsigned long > & raulElements)
Searches for facets around the ray.
Definition at line 850 of file PointsGrid.cpp.
References Base::BoundBox3< double >::BACK, Base::BoundBox3< double >::BOTTOM, Points::PointsGrid::CheckPos(), Base::BoundBox3< double >::FRONT, Points::PointsGrid::GetBoundBox(), Base::BoundBox3< Precision >::GetSideFromRay(), Base::BoundBox3< double >::INVALID, Base::BoundBox3< double >::LEFT, FreeCADInit::Length, RobotExample::pos, Base::BoundBox3< double >::RIGHT, and Base::BoundBox3< double >::TOP.
The documentation for this class was generated from the following files:
PointsGrid.h
PointsGrid.cpp