FreeCAD: Path.Post.scripts.fablin_post Namespace Reference
Path.Post.scripts.fablin_post Namespace Reference
Functions
def processArguments (argstring)
def export (objectslist, filename, argstring)
def linenumber ()
def parse (pathobj)
Variables
now
TOOLTIP_ARGS
OUTPUT_COMMENTS
OUTPUT_HEADER
OUTPUT_LINE_NUMBERS
OUTPUT_TOOL_CHANGE
SHOW_EDITOR
MODAL
COMMAND_SPACE
LINENR
UNITS
MACHINE_NAME
CORNER_MIN
CORNER_MAX
RAPID_MOVES
RAPID_FEEDRATE
PREAMBLE
POSTAMBLE
SUPPRESS_COMMANDS
PRE_OPERATION
POST_OPERATION
TOOL_CHANGE
Function Documentation
export()
def Path.Post.scripts.fablin_post.export (objectslist, filename, argstring)
Definition at line 124 of file fablin_post.py.
References Path.Post.scripts.fablin_post.linenumber(), Path.Post.scripts.fablin_post.parse(), Path.Post.scripts.fablin_post.processArguments(), and Path.Post.scripts.refactored_centroid_post.str.
linenumber()
def Path.Post.scripts.fablin_post.linenumber ()
Definition at line 207 of file fablin_post.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.fablin_post.export(), and Path.Post.scripts.fablin_post.parse().
parse()
def Path.Post.scripts.fablin_post.parse (pathobj)
Definition at line 215 of file fablin_post.py.
References Path.Post.scripts.fablin_post.linenumber(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.fablin_post.export().
processArguments()
def Path.Post.scripts.fablin_post.processArguments (argstring)
Definition at line 94 of file fablin_post.py.
Referenced by Path.Post.scripts.fablin_post.export().
Variable Documentation
COMMAND_SPACE
Path.Post.scripts.fablin_post.COMMAND_SPACE
Definition at line 58 of file fablin_post.py.
CORNER_MAX
Path.Post.scripts.fablin_post.CORNER_MAX
Definition at line 65 of file fablin_post.py.
CORNER_MIN
Path.Post.scripts.fablin_post.CORNER_MIN
Definition at line 64 of file fablin_post.py.
LINENR
Path.Post.scripts.fablin_post.LINENR
Definition at line 59 of file fablin_post.py.
MACHINE_NAME
Path.Post.scripts.fablin_post.MACHINE_NAME
Definition at line 63 of file fablin_post.py.
MODAL
Path.Post.scripts.fablin_post.MODAL
Definition at line 57 of file fablin_post.py.
now
Path.Post.scripts.fablin_post.now
Definition at line 32 of file fablin_post.py.
OUTPUT_COMMENTS
Path.Post.scripts.fablin_post.OUTPUT_COMMENTS
Definition at line 51 of file fablin_post.py.
OUTPUT_HEADER
Path.Post.scripts.fablin_post.OUTPUT_HEADER
Definition at line 52 of file fablin_post.py.
OUTPUT_LINE_NUMBERS
Path.Post.scripts.fablin_post.OUTPUT_LINE_NUMBERS
Definition at line 53 of file fablin_post.py.
OUTPUT_TOOL_CHANGE
Path.Post.scripts.fablin_post.OUTPUT_TOOL_CHANGE
Definition at line 54 of file fablin_post.py.
POST_OPERATION
Path.Post.scripts.fablin_post.POST_OPERATION
Definition at line 88 of file fablin_post.py.
POSTAMBLE
Path.Post.scripts.fablin_post.POSTAMBLE
Definition at line 76 of file fablin_post.py.
PRE_OPERATION
Path.Post.scripts.fablin_post.PRE_OPERATION
Definition at line 85 of file fablin_post.py.
PREAMBLE
Path.Post.scripts.fablin_post.PREAMBLE
Definition at line 72 of file fablin_post.py.
RAPID_FEEDRATE
Path.Post.scripts.fablin_post.RAPID_FEEDRATE
Definition at line 69 of file fablin_post.py.
RAPID_MOVES
Path.Post.scripts.fablin_post.RAPID_MOVES
Definition at line 67 of file fablin_post.py.
SHOW_EDITOR
Path.Post.scripts.fablin_post.SHOW_EDITOR
Definition at line 56 of file fablin_post.py.
SUPPRESS_COMMANDS
Path.Post.scripts.fablin_post.SUPPRESS_COMMANDS
Definition at line 82 of file fablin_post.py.
TOOL_CHANGE
Path.Post.scripts.fablin_post.TOOL_CHANGE
Definition at line 91 of file fablin_post.py.
TOOLTIP_ARGS
Path.Post.scripts.fablin_post.TOOLTIP_ARGS
Definition at line 41 of file fablin_post.py.
UNITS
Path.Post.scripts.fablin_post.UNITS
Definition at line 62 of file fablin_post.py.