FreeCAD: Commands Namespace Reference
Commands Namespace Reference
Classes
class SphereCreator
class TemplatePyCheckable
class TemplatePyGroup
class TemplatePyGrp_1
class TemplatePyGrp_2
class TemplatePyGrp_3
class TemplatePyMod_Cmd1
class TemplatePyMod_Cmd2
class TemplatePyMod_Cmd3
class TemplatePyMod_Cmd4
class TemplatePyMod_Cmd5
class TemplatePyMod_Cmd6
Functions
def addCommand (name, cmdObject)
Variables
myRenderArea = None
Function Documentation
addCommand()
def Commands.addCommand (name, cmdObject)
Definition at line 12 of file TemplatePyMod/Commands.py.
Referenced by CmdSketcherCompConstrainTools.CmdSketcherCompConstrainTools(), CmdSketcherCompDimensionTools.CmdSketcherCompDimensionTools(), CmdSketcherCompLine.CmdSketcherCompLine(), CmdSketcherCompToggleConstraints.CmdSketcherCompToggleConstraints(), Commands.TemplatePyCheckable.GetResources(), and draftguitools.gui_snaps.Draft_Snap_Lock.IsActive().
Variable Documentation
myRenderArea
Commands.myRenderArea = None
Definition at line 154 of file TemplatePyMod/Commands.py.