FreeCAD: Utils.h File Reference
Sketcher/Gui/Utils.h File Reference
#include <Base/Exception.h>
#include <Base/Tools.h>
#include <Base/Tools2D.h>
#include <Mod/Sketcher/App/GeoEnum.h>
#include "AutoConstraint.h"
#include "ViewProviderSketchGeometryExtension.h"
#include "GeometryCreationMode.h"
Namespaces
App
a class to assist with exporting sketches to dxf
Gui
Part
Sketcher
a class for establishing our connection with the unified measurement facility
SketcherGui
Functions
bool Sketcher::isCircle (const Part::Geometry &)
bool Sketcher::isArcOfCircle (const Part::Geometry &)
bool Sketcher::isEllipse (const Part::Geometry &)
bool Sketcher::isArcOfEllipse (const Part::Geometry &)
bool Sketcher::isLineSegment (const Part::Geometry &)
bool Sketcher::isArcOfHyperbola (const Part::Geometry &)
bool Sketcher::isArcOfParabola (const Part::Geometry &)
bool Sketcher::isBSplineCurve (const Part::Geometry &)
bool Sketcher::isPeriodicBSplineCurve (const Part::Geometry &)
bool Sketcher::isPoint (const Part::Geometry &)
bool Sketcher::isCircleOrArc (const Part::Geometry &geo)
std::tuple< double, Base::Vector3d > Sketcher::getRadiusCenterCircleArc (const Part::Geometry *geo)
bool SketcherGui::tryAutoRecompute (Sketcher::SketchObject *obj)
bool SketcherGui::tryAutoRecompute (Sketcher::SketchObject *obj, bool &autoremoveredundants)
Same as the other overload, but also returns whether redundants shall be removed or not.
void SketcherGui::tryAutoRecomputeIfNotSolve (Sketcher::SketchObject *obj)
bool SketcherGui::ReleaseHandler (Gui::Document *doc)
std::string SketcherGui::getStrippedPythonExceptionString (const Base::Exception &)
void SketcherGui::getIdsFromName (const std::string &name, const Sketcher::SketchObject *Obj, int &GeoId, Sketcher::PointPos &PosId)
std::vector< int > SketcherGui::getGeoIdsOfEdgesFromNames (const Sketcher::SketchObject *Obj, const std::vector< std::string > &names)
Returns ONLY the geometry elements when the "Edge" is selected (including GeomPoints)
bool SketcherGui::checkBothExternal (int GeoId1, int GeoId2)
bool SketcherGui::isPointOrSegmentFixed (const Sketcher::SketchObject *Obj, int GeoId)
bool SketcherGui::areBothPointsOrSegmentsFixed (const Sketcher::SketchObject *Obj, int GeoId1, int GeoId2)
bool SketcherGui::areAllPointsOrSegmentsFixed (const Sketcher::SketchObject *Obj, int GeoId1, int GeoId2, int GeoId3)
bool SketcherGui::isVertex (int GeoId, Sketcher::PointPos PosId)
bool SketcherGui::isEdge (int GeoId, Sketcher::PointPos PosId)
bool SketcherGui::isSimpleVertex (const Sketcher::SketchObject *Obj, int GeoId, Sketcher::PointPos PosId)
bool SketcherGui::isBsplineKnot (const Sketcher::SketchObject *Obj, int GeoId)
Checks if GeoId corresponds to a B-Spline knot.
bool SketcherGui::isBsplineKnotOrEndPoint (const Sketcher::SketchObject *Obj, int GeoId, Sketcher::PointPos PosId)
bool SketcherGui::IsPointAlreadyOnCurve (int GeoIdCurve, int GeoIdPoint, Sketcher::PointPos PosIdPoint, Sketcher::SketchObject *Obj)
bool SketcherGui::isBsplinePole (const Part::Geometry *geo)
bool SketcherGui::isBsplinePole (const Sketcher::SketchObject *Obj, int GeoId)
bool SketcherGui::checkConstraint (const std::vector< Sketcher::Constraint * > &vals, Sketcher::ConstraintType type, int geoid, Sketcher::PointPos pos)
bool SketcherGui::isConstructionMode ()
const char * SketcherGui::constructionModeAsBooleanText ()
double SketcherGui::GetPointAngle (const Base::Vector2d &p1, const Base::Vector2d &p2)
void SketcherGui::GetCirclesMinimalDistance (const Part::Geometry *geom1, const Part::Geometry *geom2, Base::Vector3d &point1, Base::Vector3d &point2)
void SketcherGui::ActivateHandler (Gui::Document *doc, std::unique_ptr< DrawSketchHandler > handler)
bool SketcherGui::isSketchInEdit (Gui::Document *doc)
Returns if a sketch is in edit mode.
bool SketcherGui::isCommandActive (Gui::Document *doc, bool actsOnSelection=false)
bool SketcherGui::isSketcherBSplineActive (Gui::Document *doc, bool actsOnSelection)
SketcherGui::ViewProviderSketch * SketcherGui::getInactiveHandlerEditModeSketchViewProvider (Gui::Document *doc)
SketcherGui::ViewProviderSketch * SketcherGui::getInactiveHandlerEditModeSketchViewProvider ()
void SketcherGui::removeRedundantHorizontalVertical (Sketcher::SketchObject *psketch, std::vector< AutoConstraint > &sug1, std::vector< AutoConstraint > &sug2)
void SketcherGui::ConstraintToAttachment (Sketcher::GeoElementId element, Sketcher::GeoElementId attachment, double distance, App::DocumentObject *obj)
bool SketcherGui::hideUnits ()
bool SketcherGui::showCursorCoords ()
bool SketcherGui::useSystemDecimals ()
std::string SketcherGui::lengthToDisplayFormat (double value, int digits)
std::string SketcherGui::angleToDisplayFormat (double value, int digits)
bool SketcherGui::areCollinear (const Base::Vector2d &p1, const Base::Vector2d &p2, const Base::Vector2d &p3)
int SketcherGui::indexOfGeoId (const std::vector< int > &vec, int elem)
Base::Vector3d toVector3d (const Base::Vector2d &vector2d)
converts a 2D vector into a 3D vector in the XY plane
Base::Vector2d toVector2d (const Base::Vector3d &vector3d)
converts a 3D vector in the XY plane into a 2D vector
template<typename T >
auto toPointerVector (const std::vector< std::unique_ptr< T >> &vector)
template<typename T >
auto getSafeGeomLayerId (T geom)
template<typename T >
void setSafeGeomLayerId (T geom, int layerindex)
Function Documentation
getSafeGeomLayerId()
template<typename T > auto getSafeGeomLayerId (T geom)
returns the visual layer id (not the one of the GeometryFacade, but the index to PropertyVisualLayerList) from a geometry or GeometryFacade. NOTE: If the geometry or geometryfacade does not have a corresponding ViewProviderSketchGeometryExtension, the default layer (layer 0) is returned.
Definition at line 246 of file Sketcher/Gui/Utils.h.
References Base::BaseClass::getClassTypeId().
Referenced by SketcherGui::EditModeGeometryCoinConverter::convert(), and SketcherGui::ElementItem::isVisible().
setSafeGeomLayerId()
template<typename T > void setSafeGeomLayerId (T geom, int layerindex)
sets the visual layer id (not the one of the GeometryFacade, but the index to PropertyVisualLayerList) for a geometry or GeometryFacade. NOTE: If no ViewProviderSketchGeometryExtension is present, one is created.
Definition at line 268 of file Sketcher/Gui/Utils.h.
References Base::BaseClass::getClassTypeId().
toPointerVector()
template<typename T > auto toPointerVector (const std::vector< std::unique_ptr< T >> & vector)
Definition at line 229 of file Sketcher/Gui/Utils.h.
References buildPsets::p.
Referenced by SketcherGui::DrawSketchDefaultHandler< ControllerT::HandlerType, ControllerT::SelectModeType, ControllerT::AutoConstraintInitialSize, ControllerT::ContructionMethodType >::commandAddShapeGeometryAndConstraints(), and SketcherGui::DrawSketchDefaultHandler< ControllerT::HandlerType, ControllerT::SelectModeType, ControllerT::AutoConstraintInitialSize, ControllerT::ContructionMethodType >::createGeneratedAutoConstraints().
toVector2d()
Base::Vector2d toVector2d (const Base::Vector3d & vector3d) inline
converts a 3D vector in the XY plane into a 2D vector
Definition at line 222 of file Sketcher/Gui/Utils.h.
References Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by horVerActivated(), horVerApplyConstraint(), SketcherGui::EditModeConstraintCoinManager::processConstraints(), and SketcherGui::DrawSketchHandler::seekAutoConstraint().
toVector3d()
Base::Vector3d toVector3d (const Base::Vector2d & vector2d) inline
converts a 2D vector into a 3D vector in the XY plane
Definition at line 216 of file Sketcher/Gui/Utils.h.
References exportCSG::vector2d().
Referenced by MeasureGui::ViewProviderMeasureBase::getTextDirection().