FreeCAD: src.Mod.Test.BaseTests.AlgebraTestCase Class Reference
src.Mod.Test.BaseTests.AlgebraTestCase Class Reference
Public Member Functions
def setUp (self)
def testAngle (self)
def testVector2d (self)
def testAngleWithNullVector (self)
def testMatrix (self)
def testRotAndMoveMatrix (self)
def testRotationFromMatrix (self)
def testRotation (self)
def testInverted (self)
def testDecomposeScale (self)
def testDecomposeRotation (self)
def testDecomposeMove (self)
def testMatrixDecompose (self)
def testYawPitchRoll (self)
def testBounding (self)
def testMultLeftOrRight (self)
Detailed Description
Definition at line 188 of file BaseTests.py.
Member Function Documentation
setUp()
def src.Mod.Test.BaseTests.AlgebraTestCase.setUp (self)
Definition at line 189 of file BaseTests.py.
testAngle()
def src.Mod.Test.BaseTests.AlgebraTestCase.testAngle (self)
Definition at line 192 of file BaseTests.py.
testAngleWithNullVector()
def src.Mod.Test.BaseTests.AlgebraTestCase.testAngleWithNullVector (self)
Definition at line 204 of file BaseTests.py.
testBounding()
def src.Mod.Test.BaseTests.AlgebraTestCase.testBounding (self)
Definition at line 415 of file BaseTests.py.
References femsolver.elmer.sifio.isValid().
testDecomposeMove()
def src.Mod.Test.BaseTests.AlgebraTestCase.testDecomposeMove (self)
Definition at line 349 of file BaseTests.py.
testDecomposeRotation()
def src.Mod.Test.BaseTests.AlgebraTestCase.testDecomposeRotation (self)
Definition at line 338 of file BaseTests.py.
testDecomposeScale()
def src.Mod.Test.BaseTests.AlgebraTestCase.testDecomposeScale (self)
Definition at line 329 of file BaseTests.py.
testInverted()
def src.Mod.Test.BaseTests.AlgebraTestCase.testInverted (self)
Definition at line 324 of file BaseTests.py.
References KDL.abs().
testMatrix()
def src.Mod.Test.BaseTests.AlgebraTestCase.testMatrix (self)
Definition at line 210 of file BaseTests.py.
testMatrixDecompose()
def src.Mod.Test.BaseTests.AlgebraTestCase.testMatrixDecompose (self)
Definition at line 358 of file BaseTests.py.
References src.Mod.Test.Document.DocumentExpressionCases.assertAlmostEqual(), and draftgeoutils.linear_algebra.determinant().
testMultLeftOrRight()
def src.Mod.Test.BaseTests.AlgebraTestCase.testMultLeftOrRight (self)
Definition at line 442 of file BaseTests.py.
testRotAndMoveMatrix()
def src.Mod.Test.BaseTests.AlgebraTestCase.testRotAndMoveMatrix (self)
Definition at line 215 of file BaseTests.py.
testRotation()
def src.Mod.Test.BaseTests.AlgebraTestCase.testRotation (self)
Definition at line 247 of file BaseTests.py.
References src.Mod.Test.Document.DocumentExpressionCases.assertAlmostEqual().
testRotationFromMatrix()
def src.Mod.Test.BaseTests.AlgebraTestCase.testRotationFromMatrix (self)
Definition at line 231 of file BaseTests.py.
testVector2d()
def src.Mod.Test.BaseTests.AlgebraTestCase.testVector2d (self)
Definition at line 198 of file BaseTests.py.
References src.Mod.Test.Document.DocumentExpressionCases.assertAlmostEqual().
testYawPitchRoll()
def src.Mod.Test.BaseTests.AlgebraTestCase.testYawPitchRoll (self)
Definition at line 384 of file BaseTests.py.
The documentation for this class was generated from the following file:
BaseTests.py