FreeCAD: Part::Interface Class Reference
Part::Interface Class Reference
#include <Interface.h>
Public Types
enum Assembly { Assembly::Off = 0, Assembly::On = 1, Assembly::Auto = 2 }
enum Unit { Unit::Millimeter = 0, Unit::Meter = 1, Unit::Inch = 2 }
Static Public Member Functions
static void writeStepAssembly (Assembly)
static Standard_CString writeStepScheme ()
static bool writeStepScheme (Standard_CString)
static Standard_CString writeStepUnit ()
static bool writeStepUnit (Standard_CString)
static bool writeStepUnit (Unit)
static Standard_CString writeStepHeaderProduct ()
static bool writeStepHeaderProduct (Standard_CString)
static Standard_CString writeIgesHeaderAuthor ()
static bool writeIgesHeaderAuthor (Standard_CString)
static Standard_CString writeIgesHeaderCompany ()
static bool writeIgesHeaderCompany (Standard_CString)
static Standard_CString writeIgesHeaderProduct ()
static bool writeIgesHeaderProduct (Standard_CString)
static Standard_CString writeIgesUnit ()
static bool writeIgesUnit (Standard_CString)
static bool writeIgesUnit (Unit)
static int writeIgesBrepMode ()
static bool writeIgesBrepMode (int)
Detailed Description
Definition at line 53 of file Interface.h.
Member Enumeration Documentation
Assembly
enum Part::Interface::Assembly strong
Enumerator
Off
(Default) writes STEP files without assemblies
On
writes all shapes in the form of STEP assemblies
Auto
writes shapes having a structure of (possibly nested) TopoDS_Compounds in the form of STEP assemblies, single shapes are written without assembly structures
Definition at line 77 of file Interface.h.
Unit
enum Part::Interface::Unit strong
Enumerator
Millimeter
Meter
Inch
Definition at line 84 of file Interface.h.
Member Function Documentation
writeIgesBrepMode() [1/2]
int Interface::writeIgesBrepMode () static
Definition at line 192 of file Interface.cpp.
writeIgesBrepMode() [2/2]
bool Interface::writeIgesBrepMode (int mode) static
Definition at line 197 of file Interface.cpp.
writeIgesHeaderAuthor() [1/2]
Standard_CString Interface::writeIgesHeaderAuthor () static
IGES settings
Definition at line 140 of file Interface.cpp.
Referenced by Part::TopoShape::exportIges(), Part::IGES::ImportExportSettings::getBRepMode(), Part::IGES::ImportExportSettings::setSkipBlankEntities(), and Import::WriterIges::write().
writeIgesHeaderAuthor() [2/2]
bool Interface::writeIgesHeaderAuthor (Standard_CString name) static
Definition at line 145 of file Interface.cpp.
writeIgesHeaderCompany() [1/2]
Standard_CString Interface::writeIgesHeaderCompany () static
Definition at line 150 of file Interface.cpp.
Referenced by Part::TopoShape::exportIges(), and Import::WriterIges::write().
writeIgesHeaderCompany() [2/2]
bool Interface::writeIgesHeaderCompany (Standard_CString name) static
Definition at line 155 of file Interface.cpp.
writeIgesHeaderProduct() [1/2]
Standard_CString Interface::writeIgesHeaderProduct () static
Definition at line 160 of file Interface.cpp.
Referenced by Part::TopoShape::exportIges(), Part::IGES::ImportExportSettings::setBRepMode(), and Import::WriterIges::write().
writeIgesHeaderProduct() [2/2]
bool Interface::writeIgesHeaderProduct (Standard_CString name) static
Definition at line 165 of file Interface.cpp.
writeIgesUnit() [1/3]
Standard_CString Interface::writeIgesUnit () static
Definition at line 187 of file Interface.cpp.
writeIgesUnit() [2/3]
bool Interface::writeIgesUnit (Standard_CString unit) static
Definition at line 170 of file Interface.cpp.
References unit().
writeIgesUnit() [3/3]
bool Interface::writeIgesUnit (Interface::Unit unit) static
Definition at line 175 of file Interface.cpp.
References Inch, Meter, and unit().
writeStepAssembly()
void Interface::writeStepAssembly (Interface::Assembly mode) static
STEP settings
Definition at line 93 of file Interface.cpp.
Referenced by Import::ExportOCAF::ExportOCAF(), Import::ExportOCAF2::ExportOCAF2(), Part::TopoShape::exportStep(), and Import::WriterStep::write().
writeStepHeaderProduct() [1/2]
Standard_CString Interface::writeStepHeaderProduct () static
Definition at line 130 of file Interface.cpp.
writeStepHeaderProduct() [2/2]
bool Interface::writeStepHeaderProduct (Standard_CString name) static
Definition at line 135 of file Interface.cpp.
writeStepScheme() [1/2]
Standard_CString Interface::writeStepScheme () static
Definition at line 98 of file Interface.cpp.
writeStepScheme() [2/2]
bool Interface::writeStepScheme (Standard_CString scheme) static
Definition at line 103 of file Interface.cpp.
writeStepUnit() [1/3]
Standard_CString Interface::writeStepUnit () static
Definition at line 125 of file Interface.cpp.
Referenced by Part::STEP::ImportExportSettings::setVisibleImportDialog().
writeStepUnit() [2/3]
bool Interface::writeStepUnit (Standard_CString unit) static
Definition at line 108 of file Interface.cpp.
References unit().
writeStepUnit() [3/3]
bool Interface::writeStepUnit (Interface::Unit unit) static
Definition at line 113 of file Interface.cpp.
References Inch, Meter, and unit().
The documentation for this class was generated from the following files:
Interface.h
Interface.cpp