FreeCAD: Gui::TaskImage Class Reference
Gui::TaskImage Class Reference
#include <TaskImage.h>
Public Member Functions
TaskImage (Image::ImagePlane *obj, QWidget *parent=nullptr)
~TaskImage () override
void open ()
void accept ()
void reject ()
Detailed Description
Definition at line 88 of file TaskImage.h.
Constructor & Destructor Documentation
TaskImage()
TaskImage::TaskImage (Image::ImagePlane * obj, QWidget * parent = nullptr) explicit
Definition at line 61 of file TaskImage.cpp.
References App::PropertyQuantity::getValue(), Image::ImagePlane::XSize, and Image::ImagePlane::YSize.
~TaskImage()
TaskImage::~TaskImage () override
Definition at line 78 of file TaskImage.cpp.
References App::WeakPtrT< T >::expired().
Member Function Documentation
accept()
void TaskImage::accept ()
Definition at line 264 of file TaskImage.cpp.
References toolbit-attributes::doc, App::WeakPtrT< T >::expired(), and App::DocumentObject::getDocument().
Referenced by Gui::TaskImageDialog::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
open()
void TaskImage::open ()
Definition at line 255 of file TaskImage.cpp.
References toolbit-attributes::doc, App::WeakPtrT< T >::expired(), App::DocumentObject::getDocument(), App::PropertyPlacement::getValue(), App::GeoFeature::Placement, and Arch::QT_TRANSLATE_NOOP.
Referenced by Gui::TaskImageDialog::open().
reject()
void TaskImage::reject ()
Definition at line 273 of file TaskImage.cpp.
References toolbit-attributes::doc, App::WeakPtrT< T >::expired(), App::DocumentObject::getDocument(), and App::DocumentObject::purgeTouched().
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), Gui::TaskImageDialog::reject(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
TaskImage.h
TaskImage.cpp