FreeCAD: WireJoiner::WireJoinerP::VertexInfo Struct Reference
WireJoiner::WireJoinerP::VertexInfo Struct Reference
Public Member Functions
VertexInfo ()=default
VertexInfo (Edges::iterator it, bool start)
VertexInfo reversed () const
bool operator== (const VertexInfo &other) const
bool operator< (const VertexInfo &other) const
const gp_Pnt & pt () const
gp_Pnt & pt ()
const gp_Pnt & ptOther () const
gp_Pnt & ptOther ()
TopoDS_Vertex vertex () const
TopoDS_Vertex otherVertex () const
EdgeInfo * edgeInfo () const
const TopoDS_Edge & edge () const
Public Attributes
Edges::iterator it {}
bool start {}
Detailed Description
Definition at line 399 of file WireJoiner.cpp.
Constructor & Destructor Documentation
VertexInfo() [1/2]
WireJoiner::WireJoinerP::VertexInfo::VertexInfo () default
VertexInfo() [2/2]
WireJoiner::WireJoinerP::VertexInfo::VertexInfo (Edges::iterator it, bool start) inline
Definition at line 403 of file WireJoiner.cpp.
Member Function Documentation
edge()
const TopoDS_Edge& WireJoiner::WireJoinerP::VertexInfo::edge () const inline
Definition at line 444 of file WireJoiner.cpp.
References it.
Referenced by WireJoiner::WireJoinerP::addNoDuplicates(), otherVertex(), and vertex().
edgeInfo()
EdgeInfo* WireJoiner::WireJoinerP::VertexInfo::edgeInfo () const inline
Definition at line 441 of file WireJoiner.cpp.
Referenced by WireJoiner::WireJoinerP::_findClosedWires(), WireJoiner::WireJoinerP::_findClosedWiresUpdateEdges(), WireJoiner::WireJoinerP::addNoDuplicates(), WireJoiner::WireJoinerP::exhaustTightBoundUpdateVertex(), WireJoiner::WireJoinerP::exhaustTightBoundWithAdjacent(), WireJoiner::WireJoinerP::findTightBoundByVertices(), and operator<().
operator<()
bool WireJoiner::WireJoinerP::VertexInfo::operator< (const VertexInfo & other) const inline
Definition at line 412 of file WireJoiner.cpp.
References edgeInfo(), and start.
operator==()
bool WireJoiner::WireJoinerP::VertexInfo::operator== (const VertexInfo & other) const inline
Definition at line 409 of file WireJoiner.cpp.
References it, and start.
otherVertex()
TopoDS_Vertex WireJoiner::WireJoinerP::VertexInfo::otherVertex () const inline
Definition at line 438 of file WireJoiner.cpp.
References edge(), FirstVertex(), LastVertex(), and start.
Referenced by WireJoiner::WireJoinerP::addNoDuplicates().
pt() [1/2]
gp_Pnt& WireJoiner::WireJoinerP::VertexInfo::pt () inline
Definition at line 426 of file WireJoiner.cpp.
References it, and start.
pt() [2/2]
const gp_Pnt& WireJoiner::WireJoinerP::VertexInfo::pt () const inline
Definition at line 423 of file WireJoiner.cpp.
References it, and start.
Referenced by WireJoiner::WireJoinerP::_findClosedWires(), WireJoiner::WireJoinerP::exhaustTightBoundWithAdjacent(), WireJoiner::WireJoinerP::findTightBound(), and WireJoiner::WireJoinerP::PntGetter::operator()().
ptOther() [1/2]
gp_Pnt& WireJoiner::WireJoinerP::VertexInfo::ptOther () inline
Definition at line 432 of file WireJoiner.cpp.
References it, and start.
ptOther() [2/2]
const gp_Pnt& WireJoiner::WireJoinerP::VertexInfo::ptOther () const inline
Definition at line 429 of file WireJoiner.cpp.
References it, and start.
Referenced by WireJoiner::WireJoinerP::_findClosedWires(), WireJoiner::WireJoinerP::_findClosedWiresUpdateEdges(), WireJoiner::WireJoinerP::exhaustTightBoundUpdateVertex(), WireJoiner::WireJoinerP::exhaustTightBoundWithAdjacent(), and WireJoiner::WireJoinerP::findTightBoundByVertices().
reversed()
VertexInfo WireJoiner::WireJoinerP::VertexInfo::reversed () const inline
Definition at line 406 of file WireJoiner.cpp.
References it, and start.
vertex()
TopoDS_Vertex WireJoiner::WireJoinerP::VertexInfo::vertex () const inline
Definition at line 435 of file WireJoiner.cpp.
References edge(), FirstVertex(), LastVertex(), and start.
Member Data Documentation
it
Edges::iterator WireJoiner::WireJoinerP::VertexInfo::it {}
Definition at line 400 of file WireJoiner.cpp.
Referenced by WireJoiner::WireJoinerP::_findClosedWires(), WireJoiner::WireJoinerP::_findClosedWiresWithExisting(), edge(), WireJoiner::WireJoinerP::findTightBound(), operator==(), pt(), ptOther(), and reversed().
start
bool WireJoiner::WireJoinerP::VertexInfo::start {}
Definition at line 401 of file WireJoiner.cpp.
Referenced by src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::__mul__(), WireJoiner::WireJoinerP::_findClosedWires(), WireJoiner::WireJoinerP::_findClosedWiresIsClosed(), WireJoiner::WireJoinerP::_findClosedWiresUpdateEdges(), WireJoiner::WireJoinerP::_findClosedWiresWithExisting(), src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::asString(), src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::clone(), WireJoiner::WireJoinerP::exhaustTightBoundUpdateWire(), WireJoiner::WireJoinerP::exhaustTightBoundWithAdjacent(), src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::hasStart(), src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::negated(), operator<(), operator==(), otherVertex(), pt(), ptOther(), reversed(), src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::value(), and vertex().
The documentation for this struct was generated from the following file:
WireJoiner.cpp