FreeCAD: Mesh::Exporter Class Reference
Mesh::Exporter Class Reference abstract
Virtual base class for exporting meshes.
#include <Exporter.h>
Public Member Functions
Exporter ()
virtual ~Exporter ()=default
int addObject (App::DocumentObject *obj, float tol)
Add object and all subobjects and links etc. Returns the number of stuff added.
virtual bool addMesh (const char *name, const MeshObject &mesh)=0
Exporter (const Exporter &)=delete
Exporter (Exporter &&)=delete
Exporter & operator= (const Exporter &)=delete
Exporter & operator= (Exporter &&)=delete
Protected Member Functions
void throwIfNoPermission (const std::string &)
Static Protected Member Functions
static std::string xmlEscape (const std::string &input)
Does some simple escaping of characters for XML-type exports.
Protected Attributes
std::map< const App::DocumentObject *, std::vector< std::string > > subObjectNameCache
std::map< const App::DocumentObject *, MeshObject > meshCache
Detailed Description
Virtual base class for exporting meshes.
Constructors of derived classes are expected to be required, for passing in the name of output file.
If objects are meant to be combined into a single file, then the file should be saved from the derived class' destructor.
Definition at line 66 of file Exporter.h.
Constructor & Destructor Documentation
Exporter() [1/3]
Exporter::Exporter () default
~Exporter()
virtual Mesh::Exporter::~Exporter () virtual default
Exporter() [2/3]
Mesh::Exporter::Exporter (const Exporter &) delete
Exporter() [3/3]
Mesh::Exporter::Exporter (Exporter &&) delete
Member Function Documentation
addMesh()
virtual bool Mesh::Exporter::addMesh (const char * name, const MeshObject & mesh) pure virtual
Implemented in Mesh::ExporterAMF, Mesh::Exporter3MF, and Mesh::MergeExporter.
addObject()
int Exporter::addObject (App::DocumentObject * obj, float tol)
Add object and all subobjects and links etc. Returns the number of stuff added.
Parameters
obj The object to export. If this is a group like object, its sub-objects will be added.
tol The tolerance/accuracy with which to generate the triangle mesh
Returns
The number of objects/subobjects that was exported from the document. See the parameter accuracy of ComplexGeoData::getFaces
Definition at line 104 of file Exporter.cpp.
References src.Mod.AddonManager.NetworkManager::count, expandSubObjectNames(), Base::Persistence::getClassTypeId(), App::DocumentObject::getLinkedObject(), and App::DocumentObject::getSubObject().
operator=() [1/2]
Exporter& Mesh::Exporter::operator= (const Exporter &) delete
operator=() [2/2]
Exporter& Mesh::Exporter::operator= (Exporter &&) delete
throwIfNoPermission()
void Exporter::throwIfNoPermission (const std::string & filename) protected
Definition at line 152 of file Exporter.cpp.
References Base::FileInfo::dirPath(), Base::FileInfo::exists(), and Base::FileInfo::isWritable().
Referenced by Mesh::Exporter3MF::Exporter3MF(), and Mesh::ExporterAMF::ExporterAMF().
xmlEscape()
std::string Exporter::xmlEscape (const std::string & input) static protected
Does some simple escaping of characters for XML-type exports.
Definition at line 93 of file Exporter.cpp.
Referenced by Mesh::ExporterAMF::addMesh().
Member Data Documentation
meshCache
std::map<const App::DocumentObject*, MeshObject> Mesh::Exporter::meshCache protected
Definition at line 115 of file Exporter.h.
subObjectNameCache
std::map<const App::DocumentObject*, std::vector<std::string> > Mesh::Exporter::subObjectNameCache protected
Definition at line 114 of file Exporter.h.
The documentation for this class was generated from the following files:
Exporter.h
Exporter.cpp