FreeCAD: Materials::ModelLibrary Class Reference
Materials::ModelLibrary Class Reference
#include <ModelLibrary.h>
Public Member Functions
ModelLibrary ()
ModelLibrary (const QString &libraryName, const QString &dir, const QString &icon)
~ModelLibrary () override=default
bool operator== (const ModelLibrary &library) const
bool operator!= (const ModelLibrary &library) const
std::shared_ptr< Model > getModelByPath (const QString &path) const
std::shared_ptr< Model > addModel (const Model &model, const QString &path)
std::shared_ptr< ModelLibrary > getptr ()
std::shared_ptr< std::map< QString, std::shared_ptr< ModelTreeNode > > > getModelTree (ModelFilter filter) const
Public Member Functions inherited from Materials::LibraryBase
LibraryBase ()=default
LibraryBase (const QString &libraryName, const QString &dir, const QString &icon)
~LibraryBase () override=default
const QString getName () const
const QString getDirectory () const
const QString getDirectoryPath () const
const QString getIconPath () const
bool operator== (const LibraryBase &library) const
bool operator!= (const LibraryBase &library) const
QString getLocalPath (const QString &path) const
QString getRelativePath (const QString &path) const
bool isRoot (const QString &path) const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 103 of file ModelLibrary.h.
Constructor & Destructor Documentation
ModelLibrary() [1/2]
ModelLibrary::ModelLibrary ()
Definition at line 114 of file ModelLibrary.cpp.
ModelLibrary() [2/2]
ModelLibrary::ModelLibrary (const QString & libraryName, const QString & dir, const QString & icon)
Definition at line 108 of file ModelLibrary.cpp.
~ModelLibrary()
Materials::ModelLibrary::~ModelLibrary () override default
Member Function Documentation
addModel()
std::shared_ptr< Model > ModelLibrary::addModel (const Model & model, const QString & path)
Definition at line 131 of file ModelLibrary.cpp.
References Path.Preferences::filePath(), getptr(), and Materials::LibraryBase::getRelativePath().
getModelByPath()
std::shared_ptr< Model > ModelLibrary::getModelByPath (const QString & path) const
Definition at line 119 of file ModelLibrary.cpp.
References Path.Preferences::filePath(), and Materials::LibraryBase::getRelativePath().
getModelTree()
std::shared_ptr< std::map< QString, std::shared_ptr< ModelTreeNode > > > ModelLibrary::getModelTree (ModelFilter filter) const
Definition at line 144 of file ModelLibrary.cpp.
References Materials::ModelManager::isModel(), and Materials::ModelManager::passFilter().
getptr()
std::shared_ptr<ModelLibrary> Materials::ModelLibrary::getptr () inline
Definition at line 126 of file ModelLibrary.h.
Referenced by addModel().
operator!=()
bool Materials::ModelLibrary::operator!= (const ModelLibrary & library) const inline
Definition at line 117 of file ModelLibrary.h.
operator==()
bool Materials::ModelLibrary::operator== (const ModelLibrary & library) const inline
Definition at line 113 of file ModelLibrary.h.
The documentation for this class was generated from the following files:
ModelLibrary.h
ModelLibrary.cpp