FreeCAD: Base::MultiLineItem Class Reference
Base::MultiLineItem Class Reference
#include <Builder3D.h>
Public Member Functions
MultiLineItem (std::vector< Vector3f > points, DrawStyle drawStyle, const ColorRGB &rgb=ColorRGB {1.0F, 1.0F, 1.0F})
void write (InventorOutput &out) const override
Public Member Functions inherited from Base::NodeItem
virtual ~NodeItem ()=default
Additional Inherited Members
Protected Member Functions inherited from Base::NodeItem
NodeItem ()=default
NodeItem (const NodeItem &)=default
NodeItem (NodeItem &&)=default
NodeItem & operator= (const NodeItem &)=default
NodeItem & operator= (NodeItem &&)=default
Detailed Description
Definition at line 341 of file Builder3D.h.
Constructor & Destructor Documentation
MultiLineItem()
MultiLineItem::MultiLineItem (std::vector< Vector3f > points, DrawStyle drawStyle, const ColorRGB & rgb = ColorRGB {1.0F, 1.0F, 1.0F}) explicit
add a line defined by a list of points whereat always a pair (i.e. a point and the following point) builds a line.
Definition at line 406 of file Builder3D.cpp.
References Path.Post.scripts.opensbp_post::move().
Member Function Documentation
write()
void MultiLineItem::write (InventorOutput & out) const override virtual
Implements Base::NodeItem.
Definition at line 412 of file Builder3D.cpp.
References Base::ColorRGB::blue, Base::ColorRGB::green, Base::DrawStyle::lineWidth, Base::DrawStyle::patternAsString(), Base::ColorRGB::red, Base::InventorOutput::write(), and Base::InventorFieldWriter::write().
The documentation for this class was generated from the following files:
Builder3D.h
Builder3D.cpp