FreeCAD: AppCloud.h File Reference
AppCloud.h File Reference
#include <App/Document.h>
#include <Base/Base64.h>
#include <Base/Interpreter.h>
#include <Base/Reader.h>
#include <Base/Writer.h>
#include <xercesc/dom/DOM.hpp>
#include <xercesc/framework/MemBufInputSource.hpp>
#include <xercesc/framework/XMLPScanToken.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>
#include <xercesc/sax/HandlerBase.hpp>
#include <xercesc/sax2/Attributes.hpp>
#include <xercesc/sax2/DefaultHandler.hpp>
Classes
struct Cloud::AmzData
struct Cloud::AmzDatav4
class Cloud::CloudReader
struct Cloud::CloudReader::FileEntry
class Cloud::Module
class Cloud::CloudWriter
Namespaces
Cloud
Functions
std::string Cloud::getHexValue (unsigned char *input, unsigned int HMACLength)
void Cloud::eraseSubStr (std::string &Str, const std::string &toErase)
size_t Cloud::CurlWrite_CallbackFunc_StdString (void *contents, size_t size, size_t nmemb, std::string *s)
struct AmzData * Cloud::ComputeDigestAmzS3v2 (char *operation, char *data_type, const char *target, const char *Secret, const char *ptr, long size)
struct AmzDatav4 * Cloud::ComputeDigestAmzS3v4 (char *operation, const char *server, char *data_type, const char *target, const char *Secret, const char *ptr, long size, char *parameters, std::string Region)
struct curl_slist * Cloud::BuildHeaderAmzS3v2 (const char *URL, const char *TCPPort, const char *PublicKey, struct AmzData *Data)
struct curl_slist * Cloud::BuildHeaderAmzS3v4 (const char *URL, const char *PublicKey, struct AmzDatav4 *Data)
char * Cloud::MD5Sum (const char *ptr, long size)
char * Cloud::SHA256Sum (const char *ptr, long size)
PyObject * Cloud::initModule ()
void readFiles (Cloud::CloudReader reader, Base::XMLReader *xmlreader)
Function Documentation
readFiles()
void readFiles (Cloud::CloudReader reader, Base::XMLReader * xmlreader)
Definition at line 1407 of file AppCloud.cpp.
References Base::XMLReader::FileList, Base::XMLReader::FileVersion, Base::Reader::getLocalReader(), Base::Reader::getStream(), TechDrawTools.TaskFillTemplateFields::reader, and readFiles().
Referenced by Cloud::Module::cloudRestore(), and readFiles().