FreeCAD: ArchIFC Namespace Reference
ArchIFC Namespace Reference
Classes
class IfcContext
class IfcProduct
class IfcRoot
Functions
def QT_TRANSLATE_NOOP (ctx, txt)
def uncamel (t)
Variables
list IfcTypes = [uncamel(t) for t in ArchIFCSchema.IfcProducts.keys()]
Function Documentation
QT_TRANSLATE_NOOP()
def ArchIFC.QT_TRANSLATE_NOOP (ctx, txt)
Definition at line 36 of file ArchIFC.py.
Referenced by ArchIFC.IfcRoot.addIfcAttribute(), and ArchIFC.IfcRoot.setProperties().
uncamel()
def ArchIFC.uncamel (t)
Definition at line 39 of file ArchIFC.py.
Referenced by importers.importIFCmulticore.setAttributes().
Variable Documentation
IfcTypes
list ArchIFC.IfcTypes = [uncamel(t) for t in ArchIFCSchema.IfcProducts.keys()]
Definition at line 42 of file ArchIFC.py.