FreeCAD: Base::Type Class Reference
Base::Type Class Reference
#include <Type.h>
Public Types
using instantiationMethod = void *(*)()
Public Member Functions
Type (const Type &type)=default
Construction.
Type (Type &&type)=default
Type ()=default
~Type ()=default
Destruction.
void * createInstance ()
creates a instance of this type
bool canInstantiate () const
Checks whether this type can instantiate.
const char * getName () const
Type getParent () const
bool isDerivedFrom (const Type &type) const
unsigned int getKey () const
bool isBad () const
Type & operator= (const Type &type)=default
Type & operator= (Type &&type)=default
bool operator== (const Type &type) const
bool operator!= (const Type &type) const
bool operator< (const Type &type) const
bool operator<= (const Type &type) const
bool operator>= (const Type &type) const
bool operator> (const Type &type) const
Static Public Member Functions
static void * createInstanceByName (const char *TypeName, bool bLoadModule=false)
creates a instance of the named type
static void importModule (const char *TypeName)
static Type fromName (const char *name)
static Type fromKey (unsigned int key)
static int getAllDerivedFrom (const Type &type, std::vector< Type > &List)
static Type getTypeIfDerivedFrom (const char *name, const Type &parent, bool bLoadModule=false)
Returns the given named type if is derived from parent type, otherwise return bad type.
static int getNumTypes ()
static Type createType (const Type &parent, const char *name, instantiationMethod method=nullptr)
static Type badType ()
static void init ()
static void destruct ()
static std::string getModuleName (const char *ClassName)
Detailed Description
Type system class Many of the classes in the FreeCAD must have their type information registered before any instances are created (including, but not limited to: App::Feature, App::Property, Gui::ViewProvider). The use of Type to store this information provides lots of various functionality for working with class hierarchies, comparing class types, instantiating objects from classnames, etc etc.
It is for instance possible to do things like this:
void getRightFeature(Base::Base * anode)
{
  assert(anode->isDerivedFrom<App::Feature>());
  if (anode->is<Mesh::MeshFeature>()) {
    // do something..
  }
  else if (anode->is<Part::PartFeature>()) {
    // do something..
  }
  else {
    Base::Console().Warning("getRightFeature", "Unknown feature type %s!\n",
                              anode->getTypeId().getName());
  }
}
A notable feature of the Type class is that it is only 16 bits long and therefore should be passed around by value for efficiency reasons.
One important note about the use of Type to register class information: super classes must be registered before any of their derived classes are.
Definition at line 100 of file Type.h.
Member Typedef Documentation
instantiationMethod
using Base::Type::instantiationMethod = void* (*)()
Definition at line 118 of file Type.h.
Constructor & Destructor Documentation
Type() [1/3]
Base::Type::Type (const Type & type) default
Construction.
Type() [2/3]
Base::Type::Type (Type && type) default
Type() [3/3]
Base::Type::Type () default
~Type()
Base::Type::~Type () default
Destruction.
Member Function Documentation
badType()
Type Type::badType () static
Definition at line 119 of file Type.cpp.
Referenced by Gui::SelectionSingleton::countObjectsOfType(), fromKey(), fromName(), Measure::MeasureDistanceType::getClassTypeId(), Gui::SelectionSingleton::getObjectList(), Gui::SelectionSingleton::getObjectsOfType(), Measure::MeasureDistanceType::getTypeId(), App::ProjectFile::getTypeId(), getTypeIfDerivedFrom(), Part::GeometryDefaultExtension< T >::getValue(), Gui::DAG::FilterOrigin::goFilter(), Gui::DAG::FilterTyped::goFilter(), DrawSketchHandlerDimension::handleInitialSelection(), Base::BaseClass::init(), App::Extension::init(), App::Extension::initExtensionSubclass(), Base::BaseClass::initSubclass(), and DrawSketchHandlerDimension::releaseButton().
canInstantiate()
bool Type::canInstantiate () const
Checks whether this type can instantiate.
Definition at line 68 of file Type.cpp.
createInstance()
void * Type::createInstance ()
creates a instance of this type
Definition at line 62 of file Type.cpp.
Referenced by App::DynamicProperty::addDynamicProperty(), TechDraw::PropertyCenterLineList::Restore(), TechDraw::PropertyGeomFormatList::Restore(), TechDraw::PropertyCosmeticEdgeList::Restore(), TechDraw::PropertyCosmeticVertexList::Restore(), Part::PropertyGeometryList::Restore(), App::ExtensionContainer::restoreExtensions(), Sandbox::DocumentObjectProtectorPy::setattr(), and Gui::View3DInventorViewer::setNavigationType().
createInstanceByName()
void * Type::createInstanceByName (const char * TypeName, bool bLoadModule = false) static
creates a instance of the named type
Definition at line 74 of file Type.cpp.
References Path.Post.scripts.grbl_post::type.
Referenced by MeshGui::DlgEvaluateMeshImp::addViewProvider(), Part::AttachExtension::changeAttacherType(), Gui::FreeCADGui_subgraphFromObject(), and App::PropertyPersistentObject::setValue().
createType()
Type Type::createType (const Type & parent, const char * name, instantiationMethod method = nullptr) static
Definition at line 127 of file Type.cpp.
References getKey(), and Init::parent.
Referenced by Base::BaseClass::init(), App::Extension::init(), App::Extension::initExtensionSubclass(), and Base::BaseClass::initSubclass().
destruct()
void Type::destruct () static
Definition at line 150 of file Type.cpp.
Referenced by App::Application::destruct().
fromKey()
Type Type::fromKey (unsigned int key) static
Definition at line 172 of file Type.cpp.
References badType().
fromName()
Type Type::fromName (const char * name) static
Definition at line 160 of file Type.cpp.
References badType(), and RobotExample::pos.
Referenced by StdCmdAlignment::activated(), Gui::Application::activateWorkbench(), FemGui::ViewProviderFemAnalysis::canDragObject(), Part::AttachExtension::changeAttacherType(), Part::FaceMaker::ConstructFromType(), App::Document::countObjectsOfType(), Gui::SelectionSingleton::countObjectsOfType(), Gui::Dialog::DlgAddProperty::DlgAddProperty(), Part::AttachExtension::extensionHandleChangedPropertyName(), PartGui::ViewProviderGridExtension::extensionHandleChangedPropertyType(), PartGui::ViewProviderBoolean::getIcon(), Fem::FemPostFilter::getInputData(), App::ProjectFile::getObjects(), App::ProjectFile::getObjectsOfType(), Gui::SelectionSingleton::getObjectsOfType(), TechDrawGui::QGVPage::getStyleType(), App::ProjectFile::getTypeId(), Gui::View3DInventorPy::getViewProvidersOfType(), Gui::DAG::FilterOrigin::goFilter(), Gui::DAG::FilterTyped::goFilter(), TechDraw::DrawViewBalloon::handleChangedPropertyName(), FemGui::ViewProviderFemConstraint::handleChangedPropertyName(), Part::Circle::handleChangedPropertyName(), Surface::Extend::handleChangedPropertyName(), PartDesign::Boolean::handleChangedPropertyName(), Fem::FemAnalysis::handleChangedPropertyName(), Part::Ellipse::handleChangedPropertyName(), PartGui::ViewProvider2DObjectGrid::handleChangedPropertyType(), Part::Primitive::handleChangedPropertyType(), PartDesign::Transformed::handleChangedPropertyType(), App::Extension::initExtensionSubclass(), Base::BaseClass::initSubclass(), Gui::Node_Object::Node_Object(), Part::BodyBase::onBeforeChange(), Gui::View3DSettings::OnChange(), FemGui::ViewProviderFemPostObject::onChanged(), Gui::Dialog::find_transform::operator()(), Gui::Dialog::find_placement::operator()(), PartMeasureTypeCb(), TechDraw::PropertyCenterLineList::Restore(), TechDraw::PropertyGeomFormatList::Restore(), TechDraw::PropertyCosmeticEdgeList::Restore(), TechDraw::PropertyCosmeticVertexList::Restore(), Part::PropertyGeometryList::Restore(), Part::Geometry::Restore(), App::ExtensionContainer::restoreExtensions(), Gui::TreeView::rowsInserted(), Gui::ApplicationPy::sActivateView(), Gui::ApplicationPy::sActiveView(), Gui::View3DInventorPy::setNavigationType(), FemGui::ViewProviderFemPostObject::setupPipeline(), App::PropertyPersistentObject::setValue(), AttacherGui::AttacherGuiPy::sGetModeStrings(), App::PropertyLinkSubList::upgrade(), and InspectionGui::VisualInspection::VisualInspection().
getAllDerivedFrom()
int Type::getAllDerivedFrom (const Type & type, std::vector< Type > & List) static
Definition at line 205 of file Type.cpp.
References Path.Post.scripts.grbl_post::type.
Referenced by Gui::Dialog::DlgAddProperty::DlgAddProperty(), Gui::UserNavigationStyle::getUserFriendlyNames(), and Gui::View3DInventorPy::listNavigationTypes().
getKey()
unsigned int Base::Type::getKey () const inline
Definition at line 165 of file Type.h.
References getKey().
Referenced by createType(), getKey(), Gui::PropertyView::onTimer(), operator!=(), and operator==().
getModuleName()
string Type::getModuleName (const char * ClassName) static
Definition at line 108 of file Type.cpp.
References OverlayParams::ClassName, and RobotExample::pos.
Referenced by Gui::TaskMeasure::update().
getName()
const char * Type::getName () const
Definition at line 181 of file Type.cpp.
Referenced by PartDesignGui::TaskDlgFeatureParameters::accept(), App::Document::addObject(), Gui::SelectionSingleton::checkSelection(), Gui::DocumentObjectItem::displayStatusInfo(), Part::AttachExtension::extensionHandleChangedPropertyName(), Gui::View3DInventorPy::getNavigationType(), App::OriginGroupExtension::getOrigin(), getProperty(), AttacherGui::getUIStrings(), TechDraw::DrawView::handleChangedPropertyType(), PartDesign::Fillet::handleChangedPropertyType(), TechDraw::DrawPage::handleChangedPropertyType(), PartDesign::Chamfer::handleChangedPropertyType(), Gui::Dialog::DlgPropertyLink::init(), Sketcher::SketchObject::isCarbonCopyAllowed(), TechDraw::ShapeExtractor::isDatumPoint(), Import::SketchExportHelper::isSketch(), TechDraw::ShapeExtractor::isSketchObject(), PartDesignGui::TaskFeaturePick::makeCopy(), App::Extension::name(), TechDrawGui::QGVPage::Private::OnChange(), Gui::ViewProviderLink::onChanged(), FemGui::TaskDlgFemConstraint::open(), App::PropertyLinkList::Restore(), Part::GeometryPersistenceExtension::Save(), Gui::SelectionObject::SelectionObject(), InspectionGui::ViewProviderInspection::setDistances(), App::LinkBaseExtension::setProperty(), and Gui::TaskMeasure::update().
getNumTypes()
int Type::getNumTypes () static
Definition at line 218 of file Type.cpp.
getParent()
Type Type::getParent () const
Definition at line 186 of file Type.cpp.
Referenced by Gui::Dialog::DlgPropertyLink::init(), and isDerivedFrom().
getTypeIfDerivedFrom()
Type Type::getTypeIfDerivedFrom (const char * name, const Type & parent, bool bLoadModule = false) static
Returns the given named type if is derived from parent type, otherwise return bad type.
Definition at line 223 of file Type.cpp.
References badType(), Init::parent, and Path.Post.scripts.grbl_post::type.
Referenced by App::DynamicProperty::addDynamicProperty(), App::Document::addObject(), App::Document::addObjects(), Gui::WorkbenchManager::createWorkbench(), Gui::View3DInventorViewer::setNavigationType(), and Gui::Document::slotNewObject().
importModule()
void Type::importModule (const char * TypeName) static
Definition at line 90 of file Type.cpp.
References Base::Console(), Base::Interpreter(), Base::InterpreterSingleton::loadModule(), Base::ConsoleSingleton::Log(), and RobotExample::pos.
Referenced by App::PropertyPersistentObject::setValue().
init()
void Type::init () static
Definition at line 141 of file Type.cpp.
Referenced by App::Application::initTypes(), and DocumentObject.DocumentObject::onChanged().
isBad()
bool Base::Type::isBad () const inline
Definition at line 200 of file Type.h.
Referenced by App::DynamicProperty::addDynamicProperty(), Part::FaceMaker::ConstructFromType(), Gui::Dialog::DlgPropertyLink::init(), App::Extension::initExtension(), App::Extension::initExtensionType(), App::Extension::name(), App::ExtensionContainer::restoreExtensions(), and Gui::Document::setActiveView().
isDerivedFrom()
bool Type::isDerivedFrom (const Type & type) const
Definition at line 191 of file Type.cpp.
References getParent(), and Path.Post.scripts.grbl_post::type.
Referenced by StdCmdToggleTransparency::activated(), Gui::Application::activateWorkbench(), FemGui::ViewProviderFemAnalysis::canDragObject(), Gui::Document::createView(), PartDesign::Body::execute(), PartGui::ViewProviderGridExtension::extensionHandleChangedPropertyType(), getLocatedShape(), AttacherGui::getUIStrings(), PartDesign::ProfileBased::getUpToFaceFromLinkSub(), App::PropertyLink::getValue(), App::PropertyLinkSub::getValue(), PartGui::ViewProvider2DObjectGrid::handleChangedPropertyType(), Part::Primitive::handleChangedPropertyType(), PartDesign::Transformed::handleChangedPropertyType(), Gui::Dialog::DlgPropertyLink::init(), Base::BaseClass::isDerivedFrom(), Gui::SelectionObject::isObjectTypeOf(), PartMeasureTypeCb(), App::ExtensionContainer::registerExtension(), App::ExtensionContainer::restoreExtensions(), Gui::Document::slotDeletedObject(), and Gui::SelectionFilter::test().
operator!=()
bool Base::Type::operator!= (const Type & type) const inline
Definition at line 170 of file Type.h.
References getKey().
operator<()
bool Base::Type::operator< (const Type & type) const inline
Definition at line 180 of file Type.h.
operator<=()
bool Base::Type::operator<= (const Type & type) const inline
Definition at line 185 of file Type.h.
operator=() [1/2]
Type& Base::Type::operator= (const Type & type) default
operator=() [2/2]
Type& Base::Type::operator= (Type && type) default
operator==()
bool Base::Type::operator== (const Type & type) const inline
Definition at line 175 of file Type.h.
References getKey().
operator>()
bool Base::Type::operator> (const Type & type) const inline
Definition at line 195 of file Type.h.
operator>=()
bool Base::Type::operator>= (const Type & type) const inline
Definition at line 190 of file Type.h.
The documentation for this class was generated from the following files:
Type.h
Type.cpp