FreeCAD: Gui::PropertyView Class Reference
Gui::PropertyView Class Reference
#include <PropertyView.h>
Classes
struct PropFind
struct PropInfo
Public Slots
void tabChanged (int index)
Stores a preference for the last tab selected.
void onTimer ()
Public Member Functions
PropertyView (QWidget *parent=nullptr)
~PropertyView () override
void clearPropertyItemSelection ()
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Static Public Member Functions
static bool showAll ()
static void setShowAll (bool)
static bool isPropertyHidden (const App::Property *)
Public Attributes
Gui::PropertyEditor::PropertyEditor * propertyEditorView
Gui::PropertyEditor::PropertyEditor * propertyEditorData
Protected Member Functions
void changeEvent (QEvent *e) override
void showEvent (QShowEvent *) override
void hideEvent (QHideEvent *) override
Detailed Description
The property view class.
Definition at line 54 of file PropertyView.h.
Constructor & Destructor Documentation
PropertyView()
PropertyView::PropertyView (QWidget * parent = nullptr) explicit
Property Editor Widget
Provides two Gui::PropertyEditor::PropertyEditor widgets, for "View" and "Data", in two tabs.
Definition at line 70 of file PropertyView.cpp.
References _GetParam(), draftgeoutils.faces::bind(), draftgeoutils.intersections::connect(), src.Mod.AddonManager.NetworkManager::count, App::GetApplication(), ParameterGrp::GetInt(), Gui::Application::Instance, Gui::NoResolve, onTimer(), propertyEditorData, propertyEditorView, Gui::PropertyEditor::PropertyEditor::setAutomaticDocumentUpdate(), Gui::PropertyEditor::PropertyEditor::setAutomaticExpand(), Gui::Application::signalActiveDocument, App::Application::signalAppendDynamicProperty, App::Application::signalChangedDocument, Gui::Application::signalChangedObject, App::Application::signalChangedObject, App::Application::signalChangePropertyEditor, Gui::Application::signalDeletedObject, App::Application::signalDeletedObject, Gui::Application::signalDeleteDocument, App::Application::signalRedoDocument, App::Application::signalRemoveDynamicProperty, App::Application::signalUndoDocument, tabChanged(), Base::tabs(), and PersistentToolbarsGui::timer.
~PropertyView()
PropertyView::~PropertyView () override
Definition at line 145 of file PropertyView.cpp.
Member Function Documentation
changeEvent()
void PropertyView::changeEvent (QEvent * e) override protected
Definition at line 547 of file PropertyView.cpp.
References SCL.SimpleDataTypes::e.
clearPropertyItemSelection()
void PropertyView::clearPropertyItemSelection ()
Definition at line 197 of file PropertyView.cpp.
References propertyEditorData, and propertyEditorView.
Referenced by hideEvent(), and onTimer().
hideEvent()
void PropertyView::hideEvent (QHideEvent * ev) override protected
Definition at line 181 of file PropertyView.cpp.
References Gui::PropertyEditor::PropertyEditor::buildUp(), clearPropertyItemSelection(), Gui::SelectionObserver::detachSelection(), propertyEditorData, propertyEditorView, and PersistentToolbarsGui::timer.
isPropertyHidden()
bool PropertyView::isPropertyHidden (const App::Property * prop) static
Definition at line 231 of file PropertyView.cpp.
References App::Property::getType(), App::Property::Hidden, App::Prop_Hidden, showAll(), and App::Property::testStatus().
Referenced by onTimer().
onTimer
void PropertyView::onTimer () slot
Definition at line 340 of file PropertyView.cpp.
References Gui::PropertyEditor::PropertyEditor::buildUp(), App::DocumentObject::canLinkProperties(), clearPropertyItemSelection(), Base::Console(), toolbit-attributes::doc, Base::Persistence::getClassTypeId(), Base::Type::getKey(), App::DocumentObject::getLinkedObject(), App::Property::getName(), Gui::ViewProviderDocumentObject::getObject(), App::ExtensionContainer::getPropertyList(), App::ExtensionContainer::getPropertyMap(), Gui::SelectionSingleton::getSelectionEx(), Base::Persistence::getTypeId(), Gui::Application::getViewProvider(), Gui::Application::Instance, Base::BaseClass::isDerivedFrom(), isPropertyHidden(), Gui::SelectionObserver::isSelectionAttached(), src.Mod.Test.testPathArray::items, Base::ConsoleSingleton::Log(), Path.Post.scripts.opensbp_post::move(), ClipperLib::pi, App::Property::PropDynamic, propertyEditorData, propertyEditorView, Gui::PropertyView::PropInfo::propId, Gui::PropertyView::PropInfo::propList, Gui::PropertyView::PropInfo::propName, Gui::TreeWidget::selectedDocument(), Gui::Selection(), App::Property::testStatus(), and TestSpreadsheet::v.
Referenced by PropertyView().
setShowAll()
void PropertyView::setShowAll (bool enable) static
Definition at line 167 of file PropertyView.cpp.
References _ShowAll, Gui::PropertyEditor::PropertyEditor::buildUp(), Gui::getMainWindow(), and propertyEditorData.
Referenced by Gui::PropertyEditor::PropertyEditor::contextMenuEvent().
showAll()
bool PropertyView::showAll () static
Definition at line 163 of file PropertyView.cpp.
References _ShowAll.
Referenced by Gui::PropertyEditor::PropertyEditor::contextMenuEvent(), createPropertyItem(), isPropertyHidden(), and Gui::PropertyEditor::PropertyEnumItem::PropertyEnumItem().
showEvent()
void PropertyView::showEvent (QShowEvent * ev) override protected
Definition at line 191 of file PropertyView.cpp.
References Gui::SelectionObserver::attachSelection(), Gui::ViewParams::instance(), and PersistentToolbarsGui::timer.
tabChanged
void PropertyView::tabChanged (int index) slot
Stores a preference for the last tab selected.
Definition at line 542 of file PropertyView.cpp.
References _GetParam(), and ParameterGrp::SetInt().
Referenced by PropertyView().
Member Data Documentation
propertyEditorData
Gui::PropertyEditor::PropertyEditor* Gui::PropertyView::propertyEditorData
Definition at line 63 of file PropertyView.h.
Referenced by clearPropertyItemSelection(), hideEvent(), onTimer(), PropertyView(), and setShowAll().
propertyEditorView
Gui::PropertyEditor::PropertyEditor* Gui::PropertyView::propertyEditorView
Definition at line 62 of file PropertyView.h.
Referenced by clearPropertyItemSelection(), hideEvent(), onTimer(), and PropertyView().
The documentation for this class was generated from the following files:
PropertyView.h
PropertyView.cpp