FreeCAD: Base::Quantity Class Reference
Base::Quantity Class Reference
#include <Quantity.h>
Public Member Functions
Quantity ()
default constructor
Quantity (const Quantity &)=default
Quantity (Quantity &&)=default
Quantity (double value, const Unit &unit=Unit())
Quantity (double value, const std::string &unit)
~Quantity ()=default
Destruction.
Quantity operator* (const Quantity &other) const
Quantity operator* (double factor) const
Quantity operator+ (const Quantity &other) const
Quantity & operator+= (const Quantity &other)
Quantity operator- (const Quantity &other) const
Quantity & operator-= (const Quantity &other)
Quantity operator- () const
Quantity operator/ (const Quantity &other) const
Quantity operator/ (double factor) const
bool operator== (const Quantity &) const
bool operator!= (const Quantity &) const
bool operator< (const Quantity &) const
bool operator> (const Quantity &) const
bool operator<= (const Quantity &) const
bool operator>= (const Quantity &) const
Quantity & operator= (const Quantity &)=default
Quantity & operator= (Quantity &&)=default
Quantity pow (const Quantity &) const
Quantity pow (double) const
const QuantityFormat & getFormat () const
void setFormat (const QuantityFormat &fmt)
std::string getUserString (double &factor, std::string &unitString) const
transfer to user preferred unit/potence
std::string getUserString () const
std::string getUserString (UnitsSchema *schema, double &factor, std::string &unitString) const
std::string getSafeUserString () const
const Unit & getUnit () const
returns the unit of the quantity
void setUnit (const Unit &un)
set the unit of the quantity
double getValue () const
get the Value of the quantity
void setValue (double val)
set the value of the quantity
double getValueAs (const Quantity &) const
bool isDimensionless () const
true if it has a number without a unit
bool isDimensionlessOrUnit (const Unit &unit) const
true if it has a specific unit or no dimension.
bool isQuantity () const
true if it has a number and a valid unit
bool isValid () const
true if it has a number with or without a unit
void setInvalid ()
sets the quantity invalid
Static Public Member Functions
static Quantity parse (const std::string &string)
Static Public Attributes
static const Quantity NanoMetre
static const Quantity MicroMetre
static const Quantity CentiMetre
static const Quantity DeciMetre
static const Quantity Metre
static const Quantity MilliMetre
static const Quantity KiloMetre
static const Quantity Liter
static const Quantity MilliLiter
static const Quantity Hertz
static const Quantity KiloHertz
static const Quantity MegaHertz
static const Quantity GigaHertz
static const Quantity TeraHertz
static const Quantity MicroGram
static const Quantity MilliGram
static const Quantity Gram
static const Quantity KiloGram
static const Quantity Ton
static const Quantity Second
static const Quantity Minute
static const Quantity Hour
static const Quantity Ampere
static const Quantity MilliAmpere
static const Quantity KiloAmpere
static const Quantity MegaAmpere
static const Quantity Kelvin
static const Quantity MilliKelvin
static const Quantity MicroKelvin
static const Quantity MilliMole
static const Quantity Mole
static const Quantity Candela
static const Quantity Inch
static const Quantity Foot
static const Quantity Thou
static const Quantity Yard
static const Quantity Pound
static const Quantity Ounce
static const Quantity Stone
static const Quantity Hundredweights
static const Quantity Mile
static const Quantity MilePerHour
static const Quantity SquareFoot
static const Quantity CubicFoot
static const Quantity PoundForce
static const Quantity Newton
static const Quantity MilliNewton
static const Quantity KiloNewton
static const Quantity MegaNewton
static const Quantity NewtonPerMeter
static const Quantity MilliNewtonPerMeter
static const Quantity KiloNewtonPerMeter
static const Quantity MegaNewtonPerMeter
static const Quantity Pascal
static const Quantity KiloPascal
static const Quantity MegaPascal
static const Quantity GigaPascal
static const Quantity Bar
static const Quantity MilliBar
static const Quantity Torr
static const Quantity mTorr
static const Quantity yTorr
static const Quantity PSI
static const Quantity KSI
static const Quantity MPSI
static const Quantity Watt
static const Quantity MilliWatt
static const Quantity KiloWatt
static const Quantity VoltAmpere
static const Quantity Volt
static const Quantity MilliVolt
static const Quantity KiloVolt
static const Quantity MegaSiemens
static const Quantity KiloSiemens
static const Quantity Siemens
static const Quantity MilliSiemens
static const Quantity MicroSiemens
static const Quantity Ohm
static const Quantity KiloOhm
static const Quantity MegaOhm
static const Quantity Coulomb
static const Quantity Tesla
static const Quantity Gauss
static const Quantity Weber
static const Quantity Farad
static const Quantity MilliFarad
static const Quantity MicroFarad
static const Quantity NanoFarad
static const Quantity PicoFarad
static const Quantity Henry
static const Quantity MilliHenry
static const Quantity MicroHenry
static const Quantity NanoHenry
static const Quantity Joule
static const Quantity MilliJoule
static const Quantity KiloJoule
static const Quantity NewtonMeter
static const Quantity VoltAmpereSecond
static const Quantity WattSecond
static const Quantity KiloWattHour
static const Quantity ElectronVolt
static const Quantity KiloElectronVolt
static const Quantity MegaElectronVolt
static const Quantity Calorie
static const Quantity KiloCalorie
static const Quantity KMH
static const Quantity MPH
static const Quantity Degree
static const Quantity Radian
static const Quantity Gon
static const Quantity AngMinute
static const Quantity AngSecond
Detailed Description
The Quantity class.
Definition at line 125 of file Quantity.h.
Constructor & Destructor Documentation
Quantity() [1/5]
Quantity::Quantity ()
default constructor
Definition at line 75 of file Quantity.cpp.
Referenced by operator*(), operator+(), operator-(), operator/(), parse(), and pow().
Quantity() [2/5]
Base::Quantity::Quantity (const Quantity &) default
Quantity() [3/5]
Base::Quantity::Quantity (Quantity &&) default
Quantity() [4/5]
Quantity::Quantity (double value, const Unit & unit = Unit()) explicit
Definition at line 79 of file Quantity.cpp.
Quantity() [5/5]
Quantity::Quantity (double value, const std::string & unit) explicit
Definition at line 84 of file Quantity.cpp.
~Quantity()
Base::Quantity::~Quantity () default
Destruction.
Member Function Documentation
getFormat()
const QuantityFormat& Base::Quantity::getFormat () const inline
Definition at line 160 of file Quantity.h.
Referenced by Gui::InputField::getFormat(), Gui::InputField::getPrecision(), Sketcher::Constraint::getPresentationValue(), Gui::InputField::newInput(), Base::UnitsSchemaImperialBuilding::schemaTranslate(), Gui::InputField::setFormat(), Gui::InputField::setPrecision(), and Base::UnitsSchema::toLocale().
getSafeUserString()
std::string Quantity::getSafeUserString () const
Definition at line 250 of file Quantity.cpp.
References Base::Tools::escapeQuotesFromString(), getUnit(), getUserString(), and parse().
Referenced by PartGui::safeQuantityQString().
getUnit()
const Unit& Base::Quantity::getUnit () const inline
returns the unit of the quantity
Definition at line 182 of file Quantity.h.
Referenced by Collector::collect(), StdDevCollector::collect(), App::FunctionExpression::evaluate(), getSafeUserString(), Gui::InputField::newInput(), Gui::Dialog::DlgUnitsCalculator::onUnitsBoxActivated(), App::pyFromQuantity(), Base::UnitsSchemaImperialDecimal::schemaTranslate(), Base::UnitsSchemaCentimeters::schemaTranslate(), Base::UnitsSchemaMKS::schemaTranslate(), Base::UnitsSchemaImperial1::schemaTranslate(), Base::UnitsSchemaInternal::schemaTranslate(), Base::UnitsSchemaMmMin::schemaTranslate(), Base::UnitsSchemaFemMilliMeterNewton::schemaTranslate(), Base::UnitsSchemaMeterDecimal::schemaTranslate(), Base::UnitsSchemaImperialBuilding::schemaTranslate(), Base::UnitsSchemaImperialCivil::schemaTranslate(), App::PropertyQuantity::setPyObject(), App::PropertyQuantityConstraint::setPyObject(), Gui::QuantitySpinBox::setUnitText(), Gui::InputField::setUnitText(), Gui::InputField::setValue(), Gui::QuantitySpinBox::setValue(), Gui::Dialog::NumberRange::throwIfOutOfRange(), Base::UnitsApi::toDouble(), Base::UnitsApi::toString(), Base::Unit::Unit(), Gui::QuantitySpinBoxPrivate::validateAndInterpret(), and Gui::Dialog::DlgUnitsCalculator::valueChanged().
getUserString() [1/3]
std::string Base::Quantity::getUserString () const inline
Definition at line 170 of file Quantity.h.
Referenced by getSafeUserString().
getUserString() [2/3]
std::string Quantity::getUserString (double & factor, std::string & unitString) const
transfer to user preferred unit/potence
Definition at line 239 of file Quantity.cpp.
References Base::UnitsApi::schemaTranslate().
Referenced by SketcherGui::angleToDisplayFormat(), areaStr(), SpreadsheetGui::SheetModel::data(), PartGui::FilletRadiusModel::data(), ConstraintItem::data(), Gui::TDragger::drag(), Gui::TPlanarDragger::drag(), Gui::RDragger::drag(), Gui::InputField::focusOutEvent(), TechDraw::DimensionFormatter::formatValue(), Gui::InputField::getQuantityString(), Gui::InputField::getUnitText(), Materials::Material::getValueString(), Gui::InputField::keyPressEvent(), SketcherGui::lengthToDisplayFormat(), Gui::InputField::newInput(), MeasureGui::ViewProviderMeasureBase::setLabelValue(), Gui::InputField::setRawText(), Gui::EditableDatumLabel::stopEdit(), Gui::Dialog::NumberRange::throwIfOutOfRange(), Gui::PropertyEditor::PropertyPlacementItem::toolTip(), Gui::PropertyEditor::PropertyVectorDistanceItem::toString(), Gui::PropertyEditor::PropertyRotationItem::toString(), Gui::PropertyEditor::PropertyPlacementItem::toString(), Gui::InputField::validate(), and Gui::InputField::wheelEvent().
getUserString() [3/3]
std::string Quantity::getUserString (UnitsSchema * schema, double & factor, std::string & unitString) const
Definition at line 245 of file Quantity.cpp.
References Base::UnitsSchema::schemaTranslate().
getValue()
double Base::Quantity::getValue () const inline
get the Value of the quantity
Definition at line 192 of file Quantity.h.
Referenced by PartGui::DlgFilletEdges::accept(), Gui::QuantitySpinBox::apply(), ConstraintItem::data(), App::FunctionExpression::evaluate(), SketcherGui::PropertyConstraintListItem::event(), App::FunctionExpression::extractLengthValueArgument(), TechDraw::DrawSVGTemplate::extractTemplateAttributes(), TechDraw::DimensionFormatter::formatValue(), TechDrawGui::DirectionEditDialog::getAngle(), TechDrawGui::DirectionEditDialog::getDirection(), SketcherGui::SketcherToolDefaultWidget::getParameter(), Gui::LocationWidget::getPosition(), App::UnitExpression::getValue(), getValueAs(), Gui::InputField::newInput(), Gui::Dialog::DlgUnitsCalculator::onUnitsBoxActivated(), App::pyFromQuantity(), Base::UnitsSchemaMKS::schemaTranslate(), Base::UnitsSchemaImperial1::schemaTranslate(), Base::UnitsSchemaInternal::schemaTranslate(), Base::UnitsSchemaImperialBuilding::schemaTranslate(), Base::UnitsSchemaImperialCivil::schemaTranslate(), Gui::InputField::setMaximum(), Gui::InputField::setMinimum(), App::PropertyQuantity::setPyObject(), App::PropertyQuantityConstraint::setPyObject(), Gui::InputField::setValue(), Gui::PropertyEditor::PropertyVectorDistanceItem::setX(), Gui::PropertyEditor::PropertyVectorDistanceItem::setY(), Gui::PropertyEditor::PropertyVectorDistanceItem::setZ(), PartGui::SpiralPrimitive::SpiralPrimitive(), Gui::QuantitySpinBox::textFromValue(), Gui::Dialog::NumberRange::throwIfOutOfRange(), Base::UnitsApi::toDouble(), Base::UnitsSchema::toLocale(), Base::UnitsApi::toNumber(), Base::UnitsApi::toQuantity(), Gui::InputField::validate(), and Gui::Dialog::DlgUnitsCalculator::valueChanged().
getValueAs()
double Quantity::getValueAs (const Quantity & other) const
get the Value in a special unit given as quantity. One can use one of the predifeined quantity units in this class
Definition at line 104 of file Quantity.cpp.
References getValue().
Referenced by FemGui::TaskFemConstraintRigidBody::TaskFemConstraintRigidBody(), and FemGui::TaskFemConstraintTransform::TaskFemConstraintTransform().
isDimensionless()
bool Quantity::isDimensionless () const
true if it has a number without a unit
Definition at line 264 of file Quantity.cpp.
References Base::Unit::isEmpty(), and isValid().
Referenced by App::FunctionExpression::evaluate(), and isDimensionlessOrUnit().
isDimensionlessOrUnit()
bool Quantity::isDimensionlessOrUnit (const Unit & unit) const
true if it has a specific unit or no dimension.
Definition at line 270 of file Quantity.cpp.
References isDimensionless(), and unit().
Referenced by App::FunctionExpression::evaluate(), and App::FunctionExpression::extractLengthValueArgument().
isQuantity()
bool Quantity::isQuantity () const
true if it has a number and a valid unit
Definition at line 276 of file Quantity.cpp.
References Base::Unit::isEmpty(), and isValid().
isValid()
bool Quantity::isValid () const
true if it has a number with or without a unit
Definition at line 282 of file Quantity.cpp.
Referenced by isDimensionless(), and isQuantity().
operator!=()
bool Quantity::operator!= (const Quantity & that) const
Definition at line 114 of file Quantity.cpp.
operator*() [1/2]
Quantity Quantity::operator* (const Quantity & other) const
Operators.
Definition at line 159 of file Quantity.cpp.
References Quantity().
operator*() [2/2]
Quantity Quantity::operator* (double factor) const
Definition at line 164 of file Quantity.cpp.
References Quantity().
operator+()
Quantity Quantity::operator+ (const Quantity & other) const
Definition at line 194 of file Quantity.cpp.
References Quantity().
operator+=()
Quantity & Quantity::operator+= (const Quantity & other)
Definition at line 203 of file Quantity.cpp.
operator-() [1/2]
Quantity Quantity::operator- () const
Definition at line 234 of file Quantity.cpp.
References Quantity().
operator-() [2/2]
Quantity Quantity::operator- (const Quantity & other) const
Definition at line 214 of file Quantity.cpp.
References Quantity().
operator-=()
Quantity & Quantity::operator-= (const Quantity & other)
Definition at line 223 of file Quantity.cpp.
operator/() [1/2]
Quantity Quantity::operator/ (const Quantity & other) const
Definition at line 169 of file Quantity.cpp.
References Quantity().
operator/() [2/2]
Quantity Quantity::operator/ (double factor) const
Definition at line 174 of file Quantity.cpp.
References Quantity().
operator<()
bool Quantity::operator< (const Quantity & that) const
Definition at line 119 of file Quantity.cpp.
operator<=()
bool Quantity::operator<= (const Quantity & that) const
Definition at line 139 of file Quantity.cpp.
operator=() [1/2]
Quantity& Base::Quantity::operator= (const Quantity &) default
operator=() [2/2]
Quantity& Base::Quantity::operator= (Quantity &&) default
operator==()
bool Quantity::operator== (const Quantity & that) const
Definition at line 109 of file Quantity.cpp.
operator>()
bool Quantity::operator> (const Quantity & that) const
Definition at line 129 of file Quantity.cpp.
operator>=()
bool Quantity::operator>= (const Quantity & that) const
Definition at line 149 of file Quantity.cpp.
parse()
Quantity Quantity::parse (const std::string & string) static
Definition at line 564 of file Quantity.cpp.
References DOUBLE_MIN, Quantity(), QuantResult, and yyparse().
Referenced by BOPTools.GeneralFuseResult.GeneralFuseResult::__init__(), BOPTools.GeneralFuseResult.GeneralFuseResult::explodeCompounds(), TechDraw::DrawSVGTemplate::extractTemplateAttributes(), TechDraw::DimensionFormatter::formatValue(), getSafeUserString(), Materials::MaterialProperty::setQuantity(), Gui::InputField::setRawText(), Gui::QuantitySpinBox::setUnitText(), Gui::InputField::setUnitText(), Materials::MaterialProperty::setValue(), Base::UnitsApi::sParseQuantity(), BOPTools.GeneralFuseResult.GeneralFuseResult::splitAggregates(), Base::UnitsApi::toDouble(), Base::UnitsApi::toQuantity(), Base::Unit::Unit(), and Gui::Dialog::DlgUnitsCalculator::valueChanged().
pow() [1/2]
Quantity Quantity::pow (const Quantity & other) const
Definition at line 179 of file Quantity.cpp.
References Base::Unit::isEmpty(), Base::pow(), and Quantity().
pow() [2/2]
Quantity Quantity::pow (double exp) const
Definition at line 189 of file Quantity.cpp.
References KDL::exp(), Base::Unit::pow(), Base::pow(), and Quantity().
setFormat()
void Base::Quantity::setFormat (const QuantityFormat & fmt) inline
Definition at line 164 of file Quantity.h.
References Path.Post.scripts.comparams_post::fmt().
Referenced by MatGui::Array2DModel::data(), MatGui::Array3DDepthModel::data(), MatGui::Array3DModel::data(), App::PropertyQuantity::getPathValue(), Sketcher::Constraint::getPresentationValue(), App::PropertyQuantity::getQuantityValue(), Path.Main.Gui.Inspect.GCodeHighlighter::highlightBlock(), Path.Post.Utils.GCodeHighlighter::highlightBlock(), Gui::InputField::newInput(), Gui::InputField::setFormat(), Gui::InputField::setPrecision(), Materials::MaterialProperty::setQuantity(), and Gui::QuantitySpinBoxPrivate::validate().
setInvalid()
void Quantity::setInvalid ()
sets the quantity invalid
Definition at line 287 of file Quantity.cpp.
Referenced by Materials::MaterialValue::setInitialValue().
setUnit()
void Base::Quantity::setUnit (const Unit & un) inline
set the unit of the quantity
Definition at line 187 of file Quantity.h.
Referenced by SketcherGui::angleToDisplayFormat(), SketcherGui::EditDatumDialog::exec(), TechDraw::DrawSVGTemplate::extractTemplateAttributes(), TechDraw::DimensionFormatter::formatValue(), Sketcher::Constraint::getPresentationValue(), SketcherGui::lengthToDisplayFormat(), Gui::InputField::newInput(), TechDrawGui::TaskCenterLine::setUiEdit(), TechDrawGui::TaskCenterLine::setUiPrimary(), Gui::InputField::setUnit(), Gui::QuantitySpinBoxPrivate::validate(), Gui::QuantitySpinBoxPrivate::validateAndInterpret(), and SketcherGui::PropertyConstraintListItem::value().
setValue()
void Base::Quantity::setValue (double val) inline
set the value of the quantity
Definition at line 197 of file Quantity.h.
References toolbit-attributes::val.
Referenced by SketcherGui::angleToDisplayFormat(), SketcherGui::EditDatumDialog::exec(), TechDraw::DimensionFormatter::formatValue(), Sketcher::Constraint::getPresentationValue(), SketcherGui::lengthToDisplayFormat(), Gui::InputField::newInput(), Gui::View3DInventorViewer::printDimension(), Gui::schemaTranslatePoint(), Gui::PropertyEditor::PropertyUnitItem::setEditorData(), Gui::PropertyEditor::PropertyUnitConstraintItem::setEditorData(), Gui::InputField::setMaximum(), Gui::InputField::setMinimum(), App::PropertyQuantityConstraint::setPyObject(), TechDrawGui::TaskCenterLine::setUiEdit(), TechDrawGui::TaskCenterLine::setUiPrimary(), Gui::InputField::setValue(), Gui::QuantitySpinBox::setValue(), Gui::QuantitySpinBoxPrivate::validateAndInterpret(), and SketcherGui::PropertyConstraintListItem::value().
Member Data Documentation
Ampere
const Quantity Quantity::Ampere static
Definition at line 248 of file Quantity.h.
AngMinute
const Quantity Quantity::AngMinute static
Definition at line 363 of file Quantity.h.
AngSecond
const Quantity Quantity::AngSecond static
Definition at line 364 of file Quantity.h.
Bar
const Quantity Quantity::Bar static
Definition at line 294 of file Quantity.h.
Calorie
const Quantity Quantity::Calorie static
Definition at line 354 of file Quantity.h.
Candela
const Quantity Quantity::Candela static
Definition at line 260 of file Quantity.h.
CentiMetre
const Quantity Quantity::CentiMetre static
Definition at line 223 of file Quantity.h.
Coulomb
const Quantity Quantity::Coulomb static
Definition at line 324 of file Quantity.h.
CubicFoot
const Quantity Quantity::CubicFoot static
Definition at line 275 of file Quantity.h.
DeciMetre
const Quantity Quantity::DeciMetre static
Definition at line 224 of file Quantity.h.
Degree
const Quantity Quantity::Degree static
Definition at line 360 of file Quantity.h.
Referenced by PartGui::DlgRevolution::getAngle(), FemGui::TaskFemConstraintRigidBody::TaskFemConstraintRigidBody(), and FemGui::TaskFemConstraintTransform::TaskFemConstraintTransform().
ElectronVolt
const Quantity Quantity::ElectronVolt static
Definition at line 351 of file Quantity.h.
Farad
const Quantity Quantity::Farad static
Definition at line 333 of file Quantity.h.
Foot
const Quantity Quantity::Foot static
Definition at line 263 of file Quantity.h.
Gauss
const Quantity Quantity::Gauss static
Definition at line 327 of file Quantity.h.
GigaHertz
const Quantity Quantity::GigaHertz static
Definition at line 235 of file Quantity.h.
GigaPascal
const Quantity Quantity::GigaPascal static
Definition at line 292 of file Quantity.h.
Gon
const Quantity Quantity::Gon static
Definition at line 362 of file Quantity.h.
Gram
const Quantity Quantity::Gram static
Definition at line 240 of file Quantity.h.
Henry
const Quantity Quantity::Henry static
Definition at line 339 of file Quantity.h.
Hertz
const Quantity Quantity::Hertz static
Definition at line 232 of file Quantity.h.
Hour
const Quantity Quantity::Hour static
Definition at line 246 of file Quantity.h.
Hundredweights
const Quantity Quantity::Hundredweights static
Definition at line 270 of file Quantity.h.
Inch
const Quantity Quantity::Inch static
Definition at line 262 of file Quantity.h.
Joule
const Quantity Quantity::Joule static
Definition at line 344 of file Quantity.h.
Kelvin
const Quantity Quantity::Kelvin static
Definition at line 253 of file Quantity.h.
KiloAmpere
const Quantity Quantity::KiloAmpere static
Definition at line 250 of file Quantity.h.
KiloCalorie
const Quantity Quantity::KiloCalorie static
Definition at line 355 of file Quantity.h.
KiloElectronVolt
const Quantity Quantity::KiloElectronVolt static
Definition at line 352 of file Quantity.h.
KiloGram
const Quantity Quantity::KiloGram static
Definition at line 241 of file Quantity.h.
KiloHertz
const Quantity Quantity::KiloHertz static
Definition at line 233 of file Quantity.h.
KiloJoule
const Quantity Quantity::KiloJoule static
Definition at line 346 of file Quantity.h.
KiloMetre
const Quantity Quantity::KiloMetre static
Definition at line 227 of file Quantity.h.
KiloNewton
const Quantity Quantity::KiloNewton static
Definition at line 281 of file Quantity.h.
KiloNewtonPerMeter
const Quantity Quantity::KiloNewtonPerMeter static
Definition at line 286 of file Quantity.h.
KiloOhm
const Quantity Quantity::KiloOhm static
Definition at line 321 of file Quantity.h.
KiloPascal
const Quantity Quantity::KiloPascal static
Definition at line 290 of file Quantity.h.
KiloSiemens
const Quantity Quantity::KiloSiemens static
Definition at line 315 of file Quantity.h.
KiloVolt
const Quantity Quantity::KiloVolt static
Definition at line 312 of file Quantity.h.
KiloWatt
const Quantity Quantity::KiloWatt static
Definition at line 307 of file Quantity.h.
KiloWattHour
const Quantity Quantity::KiloWattHour static
Definition at line 350 of file Quantity.h.
KMH
const Quantity Quantity::KMH static
Definition at line 357 of file Quantity.h.
KSI
const Quantity Quantity::KSI static
Definition at line 302 of file Quantity.h.
Liter
const Quantity Quantity::Liter static
Definition at line 229 of file Quantity.h.
MegaAmpere
const Quantity Quantity::MegaAmpere static
Definition at line 251 of file Quantity.h.
MegaElectronVolt
const Quantity Quantity::MegaElectronVolt static
Definition at line 353 of file Quantity.h.
MegaHertz
const Quantity Quantity::MegaHertz static
Definition at line 234 of file Quantity.h.
MegaNewton
const Quantity Quantity::MegaNewton static
Definition at line 282 of file Quantity.h.
MegaNewtonPerMeter
const Quantity Quantity::MegaNewtonPerMeter static
Definition at line 287 of file Quantity.h.
MegaOhm
const Quantity Quantity::MegaOhm static
Definition at line 322 of file Quantity.h.
MegaPascal
const Quantity Quantity::MegaPascal static
Definition at line 291 of file Quantity.h.
MegaSiemens
const Quantity Quantity::MegaSiemens static
Definition at line 314 of file Quantity.h.
Metre
const Quantity Quantity::Metre static
Definition at line 225 of file Quantity.h.
MicroFarad
const Quantity Quantity::MicroFarad static
Definition at line 335 of file Quantity.h.
MicroGram
const Quantity Quantity::MicroGram static
Definition at line 238 of file Quantity.h.
MicroHenry
const Quantity Quantity::MicroHenry static
Definition at line 341 of file Quantity.h.
MicroKelvin
const Quantity Quantity::MicroKelvin static
Definition at line 255 of file Quantity.h.
MicroMetre
const Quantity Quantity::MicroMetre static
Definition at line 222 of file Quantity.h.
MicroSiemens
const Quantity Quantity::MicroSiemens static
Definition at line 318 of file Quantity.h.
Mile
const Quantity Quantity::Mile static
Definition at line 271 of file Quantity.h.
MilePerHour
const Quantity Quantity::MilePerHour static
Definition at line 273 of file Quantity.h.
MilliAmpere
const Quantity Quantity::MilliAmpere static
Definition at line 249 of file Quantity.h.
MilliBar
const Quantity Quantity::MilliBar static
Definition at line 295 of file Quantity.h.
MilliFarad
const Quantity Quantity::MilliFarad static
Definition at line 334 of file Quantity.h.
MilliGram
const Quantity Quantity::MilliGram static
Definition at line 239 of file Quantity.h.
MilliHenry
const Quantity Quantity::MilliHenry static
Definition at line 340 of file Quantity.h.
MilliJoule
const Quantity Quantity::MilliJoule static
Definition at line 345 of file Quantity.h.
MilliKelvin
const Quantity Quantity::MilliKelvin static
Definition at line 254 of file Quantity.h.
MilliLiter
const Quantity Quantity::MilliLiter static
Definition at line 230 of file Quantity.h.
MilliMetre
const Quantity Quantity::MilliMetre static
Definition at line 226 of file Quantity.h.
Referenced by PartGui::DlgRevolution::getPosition(), Gui::View3DInventorViewer::printDimension(), and Gui::schemaTranslatePoint().
MilliMole
const Quantity Quantity::MilliMole static
Definition at line 257 of file Quantity.h.
MilliNewton
const Quantity Quantity::MilliNewton static
Definition at line 280 of file Quantity.h.
MilliNewtonPerMeter
const Quantity Quantity::MilliNewtonPerMeter static
Definition at line 285 of file Quantity.h.
MilliSiemens
const Quantity Quantity::MilliSiemens static
Definition at line 317 of file Quantity.h.
MilliVolt
const Quantity Quantity::MilliVolt static
Definition at line 311 of file Quantity.h.
MilliWatt
const Quantity Quantity::MilliWatt static
Definition at line 306 of file Quantity.h.
Minute
const Quantity Quantity::Minute static
Definition at line 245 of file Quantity.h.
Mole
const Quantity Quantity::Mole static
Definition at line 258 of file Quantity.h.
MPH
const Quantity Quantity::MPH static
Definition at line 358 of file Quantity.h.
MPSI
const Quantity Quantity::MPSI static
Definition at line 303 of file Quantity.h.
mTorr
const Quantity Quantity::mTorr static
Definition at line 298 of file Quantity.h.
NanoFarad
const Quantity Quantity::NanoFarad static
Definition at line 336 of file Quantity.h.
NanoHenry
const Quantity Quantity::NanoHenry static
Definition at line 342 of file Quantity.h.
NanoMetre
const Quantity Quantity::NanoMetre static
Predefined Unit types.
Definition at line 221 of file Quantity.h.
Newton
const Quantity Quantity::Newton static
Definition at line 279 of file Quantity.h.
NewtonMeter
const Quantity Quantity::NewtonMeter static
Definition at line 347 of file Quantity.h.
NewtonPerMeter
const Quantity Quantity::NewtonPerMeter static
Definition at line 284 of file Quantity.h.
Ohm
const Quantity Quantity::Ohm static
Definition at line 320 of file Quantity.h.
Ounce
const Quantity Quantity::Ounce static
Definition at line 268 of file Quantity.h.
Pascal
const Quantity Quantity::Pascal static
Definition at line 289 of file Quantity.h.
PicoFarad
const Quantity Quantity::PicoFarad static
Definition at line 337 of file Quantity.h.
Pound
const Quantity Quantity::Pound static
Definition at line 267 of file Quantity.h.
PoundForce
const Quantity Quantity::PoundForce static
Definition at line 277 of file Quantity.h.
PSI
const Quantity Quantity::PSI static
Definition at line 301 of file Quantity.h.
Radian
const Quantity Quantity::Radian static
Definition at line 361 of file Quantity.h.
Referenced by FemGui::TaskFemConstraintRigidBody::getRotation(), and FemGui::TaskFemConstraintTransform::getRotation().
Second
const Quantity Quantity::Second static
Definition at line 244 of file Quantity.h.
Siemens
const Quantity Quantity::Siemens static
Definition at line 316 of file Quantity.h.
SquareFoot
const Quantity Quantity::SquareFoot static
Definition at line 274 of file Quantity.h.
Stone
const Quantity Quantity::Stone static
Definition at line 269 of file Quantity.h.
TeraHertz
const Quantity Quantity::TeraHertz static
Definition at line 236 of file Quantity.h.
Tesla
const Quantity Quantity::Tesla static
Definition at line 326 of file Quantity.h.
Thou
const Quantity Quantity::Thou static
Definition at line 264 of file Quantity.h.
Ton
const Quantity Quantity::Ton static
Definition at line 242 of file Quantity.h.
Torr
const Quantity Quantity::Torr static
Definition at line 297 of file Quantity.h.
Volt
const Quantity Quantity::Volt static
Definition at line 310 of file Quantity.h.
VoltAmpere
const Quantity Quantity::VoltAmpere static
Definition at line 308 of file Quantity.h.
VoltAmpereSecond
const Quantity Quantity::VoltAmpereSecond static
Definition at line 348 of file Quantity.h.
Watt
const Quantity Quantity::Watt static
Definition at line 305 of file Quantity.h.
WattSecond
const Quantity Quantity::WattSecond static
Definition at line 349 of file Quantity.h.
Weber
const Quantity Quantity::Weber static
Definition at line 329 of file Quantity.h.
Yard
const Quantity Quantity::Yard static
Definition at line 265 of file Quantity.h.
yTorr
const Quantity Quantity::yTorr static
Definition at line 299 of file Quantity.h.
The documentation for this class was generated from the following files:
Quantity.h
Quantity.cpp