FreeCAD: Gui::PythonStdin Class Reference
Gui::PythonStdin Class Reference
#include <PythonConsolePy.h>
Public Member Functions
PythonStdin (PythonConsole *pc)
~PythonStdin () override
Py::Object repr () override
Py::Object getattr (const char *name) override
Py::Object readline (const Py::Tuple &)
Static Public Member Functions
static void init_type ()
Detailed Description
Python class for redirection of stdin to an input dialog of Qt.
Author
Werner Mayer
Definition at line 136 of file PythonConsolePy.h.
Constructor & Destructor Documentation
PythonStdin()
PythonStdin::PythonStdin (PythonConsole * pc) explicit
Definition at line 291 of file PythonConsolePy.cpp.
~PythonStdin()
PythonStdin::~PythonStdin () override default
Member Function Documentation
getattr()
Py::Object PythonStdin::getattr (const char * name) override
Definition at line 306 of file PythonConsolePy.cpp.
init_type()
void PythonStdin::init_type () static
Definition at line 281 of file PythonConsolePy.cpp.
References readline().
Referenced by Gui::Application::Application().
readline()
Py::Object PythonStdin::readline (const Py::Tuple &)
Definition at line 314 of file PythonConsolePy.cpp.
References Gui::PythonConsole::readline(), and src.Mod.Test.testmakeWireString::String.
Referenced by init_type().
repr()
Py::Object PythonStdin::repr () override
Definition at line 298 of file PythonConsolePy.cpp.
References toolbit-attributes::s, and src.Mod.Test.testmakeWireString::String.
The documentation for this class was generated from the following files:
PythonConsolePy.h
PythonConsolePy.cpp