FreeCAD: MaterialEditor Namespace Reference
MaterialEditor Namespace Reference
Classes
class MaterialEditor
class MaterialsDelegate
Functions
def matProperWidget (parent=None, matproperty=None, Type="String", Value=None, minimum=None, maximum=None, stepsize=None, precision=12)
def string2tuple (string)
def translate (context, text)
def openEditor (obj=None, prop=None)
def editMaterial (material=None, card_path=None, category="Solid")
Variables
unicode = str
Function Documentation
editMaterial()
def MaterialEditor.editMaterial (material = None, card_path = None, category = "Solid")
editMaterial(material): opens the editor to edit the contents
of the given material dictionary. Returns the modified material dictionary.
Definition at line 956 of file MaterialEditor.py.
Referenced by femtaskpanels.task_material_reinforced._TaskPanel.edit_material_m(), femtaskpanels.task_material_reinforced._TaskPanel.edit_material_r(), and ArchMaterial._ArchMaterialTaskPanel.openEditor().
matProperWidget()
def MaterialEditor.matProperWidget (parent = None, matproperty = None, Type = "String", Value = None, minimum = None, maximum = None, stepsize = None, precision = 12)
customs widgets for the material stuff.
Definition at line 810 of file MaterialEditor.py.
References string2tuple().
Referenced by MaterialEditor.MaterialsDelegate.createEditor().
openEditor()
def MaterialEditor.openEditor (obj = None, prop = None)
openEditor([obj,prop]): opens the editor, optionally with
an object name and material property name to edit
Definition at line 944 of file MaterialEditor.py.
string2tuple()
def MaterialEditor.string2tuple (string)
Definition at line 930 of file MaterialEditor.py.
Referenced by matProperWidget().
translate()
def MaterialEditor.translate (context, text)
Definition at line 939 of file MaterialEditor.py.
Variable Documentation
unicode
MaterialEditor.unicode = str
Definition at line 39 of file MaterialEditor.py.
Referenced by MaterialEditor.MaterialEditor.getDict().