FreeCAD: Gui::ImageView Class Reference
Gui::ImageView Class Reference
#include <ImageView.h>
Public Member Functions
ImageView (QWidget *parent)
bool loadFile (const QString &)
const char * getName () const override
returns the name of the view (important for messages)
bool onMsg (const char *pMsg, const char **ppReturn) override
Message handler.
bool onHasMsg (const char *pMsg) const override
Message handler test.
Public Member Functions inherited from Gui::MDIView
MDIView (Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
~MDIView () override
void onRelabel (Gui::Document *pDoc) override
get called when the document is updated
virtual void viewAll ()
QString buildWindowTitle () const
build window title
bool onMsg (const char *pMsg, const char **ppReturn) override
Message handler.
bool onHasMsg (const char *pMsg) const override
Message handler test.
bool canClose () override
overwrite when checking on close state
void deleteSelf () override
delete itself
PyObject * getPyObject () override
virtual QStringList undoActions () const
virtual QStringList redoActions () const
QSize minimumSizeHint () const override
virtual void setCurrentViewMode (ViewMode mode)
ViewMode currentViewMode () const
template<typename _T >
_T getActiveObject (const char *name, App::DocumentObject **parent=nullptr, std::string *subname=nullptr) const
access getter for the active object list
void setActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr)
bool hasActiveObject (const char *n) const
bool isActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr) const
virtual bool containsViewProvider (const ViewProvider *) const
containsViewProvider Checks if the given view provider is part of this view. The default implementation returns false.
virtual void print ()
virtual void printPdf ()
virtual void printPreview ()
void savePrinterSettings (QPrinter *printer)
void restorePrinterSettings (QPrinter *printer)
Public Member Functions inherited from Gui::BaseView
BaseView (Gui::Document *pcDocument=nullptr)
~BaseView () override
void setDocument (Gui::Document *pcDocument)
sets the view to another document (called by Application)
void onClose ()
is sent from the document in order to close the document
Gui::Document * getGuiDocument () const
returns the document the view is attached to
App::Document * getAppDocument () const
returns the document the view is attached to
bool isPassive () const
indicates if the view is in passive mode
virtual void onUpdate ()
get called when the document is updated
virtual void onRename (Gui::Document *)
get called when the document is renamed (change of its internal name)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Printing
void print (QPrinter *printer) override
virtual void print ()
void contextMenuEvent (QContextMenuEvent *event) override
void mousePressEvent (QMouseEvent *event) override
void mouseReleaseEvent (QMouseEvent *event) override
void mouseMoveEvent (QMouseEvent *event) override
void dropEvent (QDropEvent *event) override
void dragEnterEvent (QDragEnterEvent *event) override
virtual void print (QPrinter *printer)
Additional Inherited Members
Public Types inherited from Gui::MDIView
enum ViewMode { Child, TopLevel, FullScreen }
MDI view mode enum.
Public Slots inherited from Gui::MDIView
virtual void setOverrideCursor (const QCursor &)
virtual void restoreOverrideCursor ()
Signals inherited from Gui::MDIView
void message (const QString &, int)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Slots inherited from Gui::MDIView
virtual void windowStateChanged (QWidget *)
Protected Member Functions inherited from Gui::MDIView
void closeEvent (QCloseEvent *e) override
void changeEvent (QEvent *e) override
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::MDIView
PyObject * pythonObject
Protected Attributes inherited from Gui::BaseView
Gui::Document * _pcDocument
bool bIsDetached {false}
bool bIsPassive {false}
Detailed Description
Definition at line 37 of file ImageView.h.
Constructor & Destructor Documentation
ImageView()
ImageView::ImageView (QWidget * parent) explicit
Definition at line 50 of file ImageView.cpp.
Member Function Documentation
contextMenuEvent()
void ImageView::contextMenuEvent (QContextMenuEvent * event) override protected
Definition at line 179 of file ImageView.cpp.
References draftgeoutils.intersections::connect(), and NavigationIndicatorGui::menu.
dragEnterEvent()
void ImageView::dragEnterEvent (QDragEnterEvent * event) override protected
Definition at line 240 of file ImageView.cpp.
dropEvent()
void ImageView::dropEvent (QDropEvent * event) override protected
Definition at line 229 of file ImageView.cpp.
getName()
const char* Gui::ImageView::getName () const inline override virtual
returns the name of the view (important for messages)
Reimplemented from Gui::BaseView.
Definition at line 45 of file ImageView.h.
loadFile()
bool ImageView::loadFile (const QString & fileName)
Definition at line 69 of file ImageView.cpp.
References TechDrawTools.TaskFillTemplateFields::reader.
Referenced by StdViewLoadImage::activated().
mouseMoveEvent()
void ImageView::mouseMoveEvent (QMouseEvent * event) override protected
Definition at line 217 of file ImageView.cpp.
mousePressEvent()
void ImageView::mousePressEvent (QMouseEvent * event) override protected
Definition at line 196 of file ImageView.cpp.
mouseReleaseEvent()
void ImageView::mouseReleaseEvent (QMouseEvent * event) override protected
Definition at line 207 of file ImageView.cpp.
onHasMsg()
bool ImageView::onHasMsg (const char * pMsg) const override virtual
Message handler test.
Implements Gui::BaseView.
Definition at line 350 of file ImageView.cpp.
onMsg()
bool ImageView::onMsg (const char * pMsg, const char ** ppReturn) override virtual
Message handler.
Implements Gui::BaseView.
Definition at line 315 of file ImageView.cpp.
References Gui::MDIView::print(), Gui::MDIView::printPdf(), and Gui::MDIView::printPreview().
print() [1/3]
void MDIView::print
Print content of view
Definition at line 247 of file MDIView.cpp.
print [2/3]
void MDIView::print slot
Definition at line 241 of file MDIView.cpp.
print() [3/3]
void ImageView::print (QPrinter * printer) override virtual
Reimplemented from Gui::MDIView.
Definition at line 303 of file ImageView.cpp.
The documentation for this class was generated from the following files:
ImageView.h
ImageView.cpp