FreeCAD: Gui::SoFCBackgroundGradient Class Reference
Gui::SoFCBackgroundGradient Class Reference
#include <SoFCBackgroundGradient.h>
Public Types
enum Gradient { LINEAR = 0, RADIAL = 1 }
Public Member Functions
SoFCBackgroundGradient ()
void GLRender (SoGLRenderAction *action) override
void setGradient (Gradient grad)
Gradient getGradient () const
void setColorGradient (const SbColor &fromColor, const SbColor &toColor)
void setColorGradient (const SbColor &fromColor, const SbColor &toColor, const SbColor &midColor)
Static Public Member Functions
static void initClass ()
static void finish ()
Protected Member Functions
~SoFCBackgroundGradient () override
Protected Attributes
SbColor fCol
SbColor tCol
SbColor mCol
Detailed Description
Definition at line 37 of file SoFCBackgroundGradient.h.
Member Enumeration Documentation
Gradient
enum Gui::SoFCBackgroundGradient::Gradient
Enumerator
LINEAR
RADIAL
Definition at line 43 of file SoFCBackgroundGradient.h.
Constructor & Destructor Documentation
SoFCBackgroundGradient()
SoFCBackgroundGradient::SoFCBackgroundGradient ()
Constructor.
Definition at line 68 of file SoFCBackgroundGradient.cpp.
References SCL.SimpleDataTypes::f, fCol, LINEAR, mCol, and tCol.
~SoFCBackgroundGradient()
SoFCBackgroundGradient::~SoFCBackgroundGradient () override protected default
Destructor.
Member Function Documentation
finish()
void SoFCBackgroundGradient::finish () static
Definition at line 60 of file SoFCBackgroundGradient.cpp.
Referenced by drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::accept(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::accept(), draftguitools.gui_split.Split::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_subelements.SubelementHighlight::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rotate.Rotate::action(), draftguitools.gui_fillets.Fillet::action(), draftguitools.gui_move.Move::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_arcs.Arc::action(), draftguitools.gui_texts.Text::action(), draftguitools.gui_scale.Scale::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_trimex.Trimex::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_styles.ApplyStyle::Activated(), draftguitools.gui_join.Join::Activated(), draftguitools.gui_draft2sketch.Draft2Sketch::Activated(), draftguitools.gui_downgrade.Downgrade::Activated(), draftguitools.gui_upgrade.Upgrade::Activated(), draftguitools.gui_shape2dview.Shape2DView::Activated(), draftguitools.gui_facebinders.Facebinder::Activated(), draftguitools.gui_subelements.SubelementHighlight::Activated(), draftguitools.gui_wire2spline.WireToBSpline::Activated(), draftguitools.gui_clone.Clone::Activated(), draftguitools.gui_dimensions.Dimension::Activated(), draftguitools.gui_edit.Edit::Activated(), draftguitools.gui_selectplane.Draft_SelectPlane::check_selection(), DraftGui.DraftToolBar::checkSpecialChars(), draftguitools.gui_points.Point::click(), draftguitools.gui_orthoarray.OrthoArray::completed(), draftguitools.gui_polararray.PolarArray::completed(), draftguitools.gui_circulararray.CircularArray::completed(), draftguitools.gui_labels.Label::create(), bimcommands.BimText.BIM_Text::createObject(), draftguitools.gui_rectangles.Rectangle::createObject(), draftguitools.gui_ellipses.Ellipse::createObject(), draftguitools.gui_texts.Text::createObject(), draftviewproviders.view_text.ViewProviderText::createObject(), draftguitools.gui_stretch.Stretch::doStretch(), draftguitools.gui_fillets.Fillet::draw_arc(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), DraftGui.DraftToolBar::editUi(), DraftGui.DraftToolBar::escape(), Gui::SoFCDB::finish(), draftguitools.gui_move.Move::get_object_selection(), draftguitools.gui_rotate.Rotate::get_object_selection(), draftguitools.gui_scale.Scale::get_object_selection(), draftguitools.gui_arcs.Arc_3Points::getPoint(), draftguitools.gui_edit.Edit::keyPressed(), draftguitools.gui_dimensions.Dimension::numericInput(), draftguitools.gui_offset.Offset::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), draftguitools.gui_trimex.Trimex::numericRadius(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_align(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_auto(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_center(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_front(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_move(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_next(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_previous(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_side(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_top(), bimcommands.BimShape2DView.BIM_Shape2DView::proceed(), draftguitools.gui_join.Join::proceed(), draftguitools.gui_subelements.SubelementHighlight::proceed(), draftguitools.gui_draft2sketch.Draft2Sketch::proceed(), draftguitools.gui_downgrade.Downgrade::proceed(), bimcommands.BimSlab.BIM_Slab::proceed(), draftguitools.gui_upgrade.Upgrade::proceed(), draftguitools.gui_facebinders.Facebinder::proceed(), draftguitools.gui_pathtwistedarray.PathTwistedArray::proceed(), draftguitools.gui_shape2dview.Shape2DView::proceed(), draftguitools.gui_clone.Clone::proceed(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_pointarray.PointArray::proceed(), draftguitools.gui_patharray.PathArray::proceed(), draftguitools.gui_trimex.Trimex::proceed(), draftguitools.gui_edit.Edit::proceed(), draftguitools.gui_selectplane.Draft_SelectPlane::reject(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::reject(), drafttaskpanels.task_polararray.TaskPanelPolarArray::reject(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::reject(), and draftguitools.gui_edit.Edit::setTrackers().
getGradient()
SoFCBackgroundGradient::Gradient SoFCBackgroundGradient::getGradient () const
Definition at line 163 of file SoFCBackgroundGradient.cpp.
Referenced by Gui::View3DInventorViewer::getGradientBackground().
GLRender()
void SoFCBackgroundGradient::GLRender (SoGLRenderAction * action) override
Definition at line 88 of file SoFCBackgroundGradient.cpp.
References big_circle, SCL.SimpleDataTypes::f, fCol, glDisable, glMatrixMode, SplineSurface::i, LINEAR, mCol, small_oval, and tCol.
initClass()
void SoFCBackgroundGradient::initClass () static
Definition at line 83 of file SoFCBackgroundGradient.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
setColorGradient() [1/2]
void SoFCBackgroundGradient::setColorGradient (const SbColor & fromColor, const SbColor & toColor)
Definition at line 168 of file SoFCBackgroundGradient.cpp.
References fCol, mCol, and tCol.
Referenced by Gui::View3DInventorViewer::setGradientBackgroundColor().
setColorGradient() [2/2]
void SoFCBackgroundGradient::setColorGradient (const SbColor & fromColor, const SbColor & toColor, const SbColor & midColor)
Definition at line 176 of file SoFCBackgroundGradient.cpp.
References fCol, mCol, and tCol.
setGradient()
void SoFCBackgroundGradient::setGradient (SoFCBackgroundGradient::Gradient grad)
Definition at line 158 of file SoFCBackgroundGradient.cpp.
Referenced by Gui::View3DInventorViewer::setGradientBackground().
Member Data Documentation
fCol
SbColor Gui::SoFCBackgroundGradient::fCol protected
Definition at line 66 of file SoFCBackgroundGradient.h.
Referenced by GLRender(), setColorGradient(), and SoFCBackgroundGradient().
mCol
SbColor Gui::SoFCBackgroundGradient::mCol protected
Definition at line 66 of file SoFCBackgroundGradient.h.
Referenced by GLRender(), setColorGradient(), and SoFCBackgroundGradient().
tCol
SbColor Gui::SoFCBackgroundGradient::tCol protected
Definition at line 66 of file SoFCBackgroundGradient.h.
Referenced by GLRender(), setColorGradient(), and SoFCBackgroundGradient().
The documentation for this class was generated from the following files:
SoFCBackgroundGradient.h
SoFCBackgroundGradient.cpp