FreeCAD: MeshGui::TaskRemeshGmsh Class Reference
MeshGui::TaskRemeshGmsh Class Reference
#include <RemeshGmsh.h>
Public Member Functions
TaskRemeshGmsh (Mesh::Feature *mesh)
void clicked (int) override
is called by the framework if a button is clicked which has no accept or reject role
QDialogButtonBox::StandardButtons getStandardButtons () const override
tells the framework which buttons are wished for the dialog
bool isAllowedAlterDocument () const override
Public Member Functions inherited from Gui::TaskView::TaskDialog
TaskDialog ()
~TaskDialog () override
QWidget * addTaskBox (QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBox (const QPixmap &icon, QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBoxWithoutHeader (QWidget *widget)
void setButtonPosition (ButtonPosition p)
ButtonPosition buttonPosition () const
const std::vector< QWidget * > & getDialogContent () const
bool canClose () const
virtual void modifyStandardButtons (QDialogButtonBox *)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
bool isEscapeButtonEnabled () const
void setAutoCloseOnTransactionChange (bool on)
bool isAutoCloseOnTransactionChange () const
void setAutoCloseOnDeletedDocument (bool on)
bool isAutoCloseOnDeletedDocument () const
const std::string & getDocumentName () const
void setDocumentName (const std::string &doc)
void setAutoCloseOnClosedView (bool on)
bool isAutoCloseOnClosedView () const
void associateToObject3dView (App::DocumentObject *obj)
const Gui::MDIView * getAssociatedView () const
void setAssociatedView (const Gui::MDIView *view)
virtual bool isAllowedAlterView () const
virtual bool isAllowedAlterSelection () const
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
virtual void closed ()
is called by the framework when the dialog is closed
virtual void autoClosedOnTransactionChange ()
virtual void autoClosedOnDeletedDocument ()
virtual void autoClosedOnClosedView ()
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
virtual void helpRequested ()
is called by the framework if the user press the help button
void emitDestructionSignal ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from Gui::TaskView::TaskDialog
QPointer< QDialogButtonBox > buttonBox
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Detailed Description
Embed the panel into a task dialog.
Definition at line 117 of file RemeshGmsh.h.
Constructor & Destructor Documentation
TaskRemeshGmsh()
TaskRemeshGmsh::TaskRemeshGmsh (Mesh::Feature * mesh) explicit
Definition at line 409 of file RemeshGmsh.cpp.
References Gui::TaskView::TaskDialog::addTaskBox(), and Mesh2Shape::mesh.
Member Function Documentation
clicked()
void TaskRemeshGmsh::clicked (int) override virtual
is called by the framework if a button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 415 of file RemeshGmsh.cpp.
References MeshGui::GmshWidget::accept(), and MeshGui::GmshWidget::reject().
getStandardButtons()
QDialogButtonBox::StandardButtons MeshGui::TaskRemeshGmsh::getStandardButtons () const inline override virtual
tells the framework which buttons are wished for the dialog
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 127 of file RemeshGmsh.h.
isAllowedAlterDocument()
bool MeshGui::TaskRemeshGmsh::isAllowedAlterDocument () const inline override virtual
Indicates whether this task dialog allows other commands to modify the document while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 131 of file RemeshGmsh.h.
The documentation for this class was generated from the following files:
RemeshGmsh.h
RemeshGmsh.cpp