FreeCAD: Mesh::PropertyNormalList Class Reference
Mesh::PropertyNormalList Class Reference
#include <MeshProperties.h>
Public Member Functions
PropertyNormalList ()
void setSize (int newSize) override
int getSize () const override
void setValue (const Base::Vector3f &)
void setValue (float x, float y, float z)
const Base::Vector3f & operator[] (const int idx) const
void set1Value (const int idx, const Base::Vector3f &value)
void setValues (const std::vector< Base::Vector3f > &values)
const std::vector< Base::Vector3f > & getValues () const
PyObject * getPyObject () override
void setPyObject (PyObject *) override
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void SaveDocFile (Base::Writer &writer) const override
void RestoreDocFile (Base::Reader &reader) override
App::Property * Copy () const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const App::Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
unsigned int getMemSize () const override
void transformGeometry (const Base::Matrix4D &rclMat)
Public Member Functions inherited from App::PropertyLists
void setOrderRelevant (bool on)
bool isOrderRelevant () const
Public Member Functions inherited from App::Property
Property ()
~Property () override
const char * getName () const
bool hasName () const
std::string getFullName () const
virtual const char * getEditorName () const
Get the class name of the associated property editor item.
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual void afterRestore ()
virtual void onContainerRestored ()
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
int64_t getID () const
virtual void beforeSave () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::PropertyListsBase
const std::set< int > & getTouchList () const
void clearTouchList ()
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::Property
virtual void hasSetValue ()
Gets called by all setValue() methods after the value has changed.
virtual void aboutToSetValue ()
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Protected Member Functions inherited from App::PropertyListsBase
virtual void setPyValues (const std::vector< PyObject * > &vals, const std::vector< int > &indices)
void _setPyObject (PyObject *)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::PropertyListsBase
std::set< int > _touchList
Detailed Description
The normals property class. Note: We need an own class for that to distinguish from the base vector list.
Author
Werner Mayer
Definition at line 70 of file MeshProperties.h.
Constructor & Destructor Documentation
PropertyNormalList()
PropertyNormalList::PropertyNormalList () default
Referenced by Copy().
Member Function Documentation
Copy()
App::Property * PropertyNormalList::Copy () const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 168 of file MeshProperties.cpp.
References buildPsets::p, and PropertyNormalList().
getMemSize()
unsigned int PropertyNormalList::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence
See also
Base::Persistence
Reimplemented from App::Property.
Definition at line 182 of file MeshProperties.cpp.
getPyObject()
PyObject * PropertyNormalList::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 83 of file MeshProperties.cpp.
References getSize(), and SplineSurface::i.
getSize()
int PropertyNormalList::getSize () const override virtual
Implements App::PropertyListsBase.
Definition at line 55 of file MeshProperties.cpp.
Referenced by getPyObject(), SaveDocFile(), and transformGeometry().
getValues()
const std::vector<Base::Vector3f>& Mesh::PropertyNormalList::getValues () const inline
Definition at line 95 of file MeshProperties.h.
operator[]()
const Base::Vector3f& Mesh::PropertyNormalList::operator[] (const int idx) const inline
Definition at line 83 of file MeshProperties.h.
Paste()
void PropertyNormalList::Paste (const App::Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 175 of file MeshProperties.cpp.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
Restore()
void PropertyNormalList::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 135 of file MeshProperties.cpp.
References DrawingExample::file, and TechDrawTools.TaskFillTemplateFields::reader.
RestoreDocFile()
void PropertyNormalList::RestoreDocFile (Base::Reader &) override virtual
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data. Again you have to apply for the call of this method in the Restore() call:
void PropertyMeshKernel::Restore(Base::XMLReader &reader)
{
  reader.readElement("Mesh");
  std::string file (reader.getAttribute("file") );
  if(file == "")
  {
    // read XML
    MeshCore::MeshDocXML restorer(*_pcMesh);
    restorer.Restore(reader);
  }else{
    // initiate a file read
    reader.addFile(file.c_str(),this);
 }
}
After you issued the reader.addFile() your RestoreDocFile() is called:
void PropertyMeshKernel::RestoreDocFile(Base::Reader &reader)
{
    _pcMesh->Read( reader );
}
See also
Base::Reader,Base::XMLReader
Reimplemented from Base::Persistence.
Definition at line 156 of file MeshProperties.cpp.
References TechDrawTools.TaskFillTemplateFields::reader, setValues(), and Path.Post.scripts.refactored_centroid_post::str.
Save()
void PropertyNormalList::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 127 of file MeshProperties.cpp.
References Base::Writer::addFile(), App::Property::getName(), Base::Writer::ind(), Base::Writer::isForceXML(), and Base::Writer::Stream().
SaveDocFile()
void PropertyNormalList::SaveDocFile (Base::Writer &) const override virtual
This method is used to save large amounts of data to a binary file. Sometimes it makes no sense to write property data as XML. In case the amount of data is too big or the data type has a more effective way to save itself. In this cases it is possible to write the data in a separate file inside the document archive. In case you want do so you have to re-implement SaveDocFile(). First, you have to inform the framework in Save() that you want do so. Here an example from the Mesh module which can save a (pontetionaly big) triangle mesh:
void PropertyMeshKernel::Save (Base::Writer &writer) const
{
  if (writer.isForceXML())
  {
    writer << writer.ind() << "<Mesh>" << std::endl;
    MeshCore::MeshDocXML saver(*_pcMesh);
    saver.Save(writer);
  }else{
   writer << writer.ind() << "<Mesh file=\"" << writer.addFile("MeshKernel.bms", this) <<
"\"/>" << std::endl;
}
The writer.isForceXML() is an indication to force you to write XML. Regardless of size and effectiveness. The second part informs the Base::writer through writer.addFile("MeshKernel.bms", this) that this object wants to write a file with the given name. The method addFile() returns a unique name that then is written in the XML stream. This allows your RestoreDocFile() method to identify and read the file again. Later your SaveDocFile() method is called as many times as you issued the addFile() call:
 void
PropertyMeshKernel::SaveDocFile (Base::Writer &writer) const
{
    _pcMesh->Write( writer );
}
In this method you can simply stream your content to the file (Base::Writer inheriting from ostream).
Reimplemented from Base::Persistence.
Definition at line 146 of file MeshProperties.cpp.
References getSize(), Path.Post.scripts.refactored_centroid_post::str, and Base::Writer::Stream().
set1Value()
void Mesh::PropertyNormalList::set1Value (const int idx, const Base::Vector3f & value) inline
Definition at line 88 of file MeshProperties.h.
Referenced by transformGeometry().
setPyObject()
void PropertyNormalList::setPyObject (PyObject * value) override virtual
Reimplemented from App::PropertyLists.
Definition at line 94 of file MeshProperties.cpp.
References Path.Log::error(), SplineSurface::i, setValue(), setValues(), and toolbit-attributes::val.
setSize()
void PropertyNormalList::setSize (int newSize) override virtual
Implements App::PropertyListsBase.
Definition at line 50 of file MeshProperties.cpp.
setValue() [1/2]
void PropertyNormalList::setValue (const Base::Vector3f & lValue)
Definition at line 60 of file MeshProperties.cpp.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
Referenced by setPyObject().
setValue() [2/2]
void PropertyNormalList::setValue (float x, float y, float z)
Definition at line 68 of file MeshProperties.cpp.
References App::Property::aboutToSetValue(), App::Property::hasSetValue(), MovieTool::x, and MovieTool::y.
setValues()
void PropertyNormalList::setValues (const std::vector< Base::Vector3f > & values)
Definition at line 76 of file MeshProperties.cpp.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
Referenced by RestoreDocFile(), and setPyObject().
transformGeometry()
void PropertyNormalList::transformGeometry (const Base::Matrix4D & rclMat)
Definition at line 187 of file MeshProperties.cpp.
References App::Property::aboutToSetValue(), getSize(), App::Property::hasSetValue(), SplineSurface::i, toolbit-attributes::s, set1Value(), Base::Matrix4D::setToUnity(), and KDL::sqrt().
The documentation for this class was generated from the following files:
MeshProperties.h
MeshProperties.cpp