FreeCAD: MeshGui::MeshRenderer Class Reference
MeshGui::MeshRenderer Class Reference
#include <SoFCIndexedFaceSet.h>
Classes
class Private
Public Member Functions
MeshRenderer ()
~MeshRenderer ()
void generateGLArrays (SoGLRenderAction *, SoMaterialBindingElement::Binding binding, std::vector< float > &vertex, std::vector< int32_t > &index)
void renderFacesGLArray (SoGLRenderAction *action)
void renderCoordsGLArray (SoGLRenderAction *action)
bool canRenderGLArray (SoGLRenderAction *action) const
bool matchMaterial (SoState *) const
void update ()
bool needUpdate (SoGLRenderAction *action)
Static Public Member Functions
static bool shouldRenderDirectly (bool)
Detailed Description
Definition at line 47 of file SoFCIndexedFaceSet.h.
Constructor & Destructor Documentation
MeshRenderer()
MeshRenderer::MeshRenderer ()
Definition at line 323 of file SoFCIndexedFaceSet.cpp.
~MeshRenderer()
MeshRenderer::~MeshRenderer ()
Definition at line 327 of file SoFCIndexedFaceSet.cpp.
Member Function Documentation
canRenderGLArray()
bool MeshRenderer::canRenderGLArray (SoGLRenderAction * action) const
Definition at line 384 of file SoFCIndexedFaceSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and MeshGui::MeshRenderer::Private::canRenderGLArray().
Referenced by MeshGui::SoFCIndexedFaceSet::drawFaces(), and MeshGui::SoFCIndexedFaceSet::GLRender().
generateGLArrays()
void MeshRenderer::generateGLArrays (SoGLRenderAction * action, SoMaterialBindingElement::Binding binding, std::vector< float > & vertex, std::vector< int32_t > & index)
Definition at line 342 of file SoFCIndexedFaceSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action, MeshGui::MeshRenderer::Private::generateGLArrays(), and MeshGui::MeshRenderer::Private::pcolors.
matchMaterial()
bool MeshRenderer::matchMaterial (SoState * state) const
Definition at line 389 of file SoFCIndexedFaceSet.cpp.
References MeshGui::MeshRenderer::Private::matbinding, MeshCore::MeshIO::OVERALL, and MeshGui::MeshRenderer::Private::pcolors.
Referenced by MeshGui::SoFCIndexedFaceSet::GLRender().
needUpdate()
bool MeshRenderer::needUpdate (SoGLRenderAction * action)
Definition at line 337 of file SoFCIndexedFaceSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and MeshGui::MeshRenderer::Private::needUpdate().
Referenced by MeshGui::SoFCIndexedFaceSet::GLRender().
renderCoordsGLArray()
void MeshRenderer::renderCoordsGLArray (SoGLRenderAction * action)
Definition at line 359 of file SoFCIndexedFaceSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and MeshGui::MeshRenderer::Private::renderCoordsGLArray().
Referenced by MeshGui::SoFCIndexedFaceSet::drawFaces().
renderFacesGLArray()
void MeshRenderer::renderFacesGLArray (SoGLRenderAction * action)
Definition at line 379 of file SoFCIndexedFaceSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and MeshGui::MeshRenderer::Private::renderFacesGLArray().
Referenced by MeshGui::SoFCIndexedFaceSet::drawFaces(), and MeshGui::SoFCIndexedFaceSet::GLRender().
shouldRenderDirectly()
bool MeshRenderer::shouldRenderDirectly (bool direct) static
Definition at line 414 of file SoFCIndexedFaceSet.cpp.
Referenced by MeshGui::ViewProviderMeshFaceSet::updateData().
update()
void MeshRenderer::update ()
Definition at line 332 of file SoFCIndexedFaceSet.cpp.
References MeshGui::MeshRenderer::Private::update().
Referenced by MeshGui::SoFCIndexedFaceSet::GLRender(), and Plot.Plot::plot().
The documentation for this class was generated from the following files:
SoFCIndexedFaceSet.h
SoFCIndexedFaceSet.cpp