FreeCAD: Part::Geom2dArcOfEllipse Class Reference
Part::Geom2dArcOfEllipse Class Reference
#include <Geometry2d.h>
Public Member Functions
Geom2dArcOfEllipse ()
Geom2dArcOfEllipse (const Handle(Geom2d_Ellipse)&)
~Geom2dArcOfEllipse () override
Geometry2d * clone () const override
returns a cloned object
double getMajorRadius () const
void setMajorRadius (double Radius)
double getMinorRadius () const
void setMinorRadius (double Radius)
Base::Vector2d getMajorAxisDir () const
Geom2dArcOfEllipse::getMajorAxisDir.
void setMajorAxisDir (Base::Vector2d newdir)
Geom2dArcOfEllipse::setMajorAxisDir Rotates the ellipse in its plane, so that its major axis is as close as possible to the provided direction.
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
PyObject * getPyObject () override
void setHandle (const Handle(Geom2d_TrimmedCurve)&)
const Handle (Geom2d_Geometry) &handle() const override
Public Member Functions inherited from Part::Geom2dArcOfConic
~Geom2dArcOfConic () override
Base::Vector2d getLocation () const
void setLocation (const Base::Vector2d &Center)
bool isReversed () const
Base::Vector2d getStartPoint () const
Geom2dArcOfConic::getStartPoint.
Base::Vector2d getEndPoint () const
Geom2dArcOfConic::getEndPoint.
void getRange (double &u, double &v) const
Geom2dArcOfConic::getRange.
void setRange (double u, double v)
Geom2dArcOfConic::setRange.
Public Member Functions inherited from Part::Geom2dCurve
Geom2dCurve ()
~Geom2dCurve () override
TopoDS_Shape toShape () const override
bool tangent (double u, gp_Dir2d &) const
Base::Vector2d pointAtParameter (double u) const
Base::Vector2d firstDerivativeAtParameter (double u) const
Base::Vector2d secondDerivativeAtParameter (double u) const
bool normal (double u, gp_Dir2d &dir) const
bool closestParameter (const Base::Vector2d &point, double &u) const
bool closestParameterToBasicCurve (const Base::Vector2d &point, double &u) const
Public Member Functions inherited from Part::Geometry2d
~Geometry2d () override
Geometry2d (const Geometry2d &)=delete
Geometry2d & operator= (const Geometry2d &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions inherited from Part::Geom2dArcOfConic
Geom2dArcOfConic ()
void SaveAxis (Base::Writer &writer, const gp_Ax22d &, double u, double v) const
void RestoreAxis (Base::XMLReader &reader, gp_Ax22d &, double &u, double &v)
Protected Member Functions inherited from Part::Geometry2d
Geometry2d ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 354 of file Geometry2d.h.
Constructor & Destructor Documentation
Geom2dArcOfEllipse() [1/2]
Geom2dArcOfEllipse::Geom2dArcOfEllipse ()
Definition at line 1213 of file Geometry2d.cpp.
References SCL.SimpleDataTypes::e, and Handle().
Geom2dArcOfEllipse() [2/2]
Geom2dArcOfEllipse::Geom2dArcOfEllipse (const Handle(Geom2d_Ellipse)& e)
Definition at line 1219 of file Geometry2d.cpp.
References SCL.SimpleDataTypes::e.
~Geom2dArcOfEllipse()
Geom2dArcOfEllipse::~Geom2dArcOfEllipse () override default
Member Function Documentation
clone()
Geometry2d* Part::Geom2dArcOfEllipse::clone () const override virtual
returns a cloned object
Implements Part::Geom2dArcOfConic.
Referenced by src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated().
getMajorAxisDir()
Base::Vector2d Geom2dArcOfEllipse::getMajorAxisDir () const
Geom2dArcOfEllipse::getMajorAxisDir.
Returns
the direction vector (unit-length) of major axis of the ellipse. The direction also points to the first focus.
Definition at line 1287 of file Geometry2d.cpp.
References SCL.SimpleDataTypes::c, and Handle().
getMajorRadius()
double Part::Geom2dArcOfEllipse::getMajorRadius () const
getMemSize()
unsigned int Geom2dArcOfEllipse::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Part::Geom2dArcOfConic.
Definition at line 1321 of file Geometry2d.cpp.
getMinorRadius()
double Geom2dArcOfEllipse::getMinorRadius () const
Definition at line 1264 of file Geometry2d.cpp.
References Handle().
getPyObject()
PyObject * Geom2dArcOfEllipse::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::Geom2dArcOfConic.
Definition at line 1383 of file Geometry2d.cpp.
References draftmake.make_clone::clone.
Handle()
const Part::Geom2dArcOfEllipse::Handle (Geom2d_Geometry) const & override virtual
Implements Part::Geom2dArcOfConic.
Restore()
void Geom2dArcOfEllipse::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from Part::Geometry2d.
Definition at line 1348 of file Geometry2d.cpp.
References SCL.SimpleDataTypes::e, gce_ErrorStatusText(), Handle(), TechDrawTools.TaskFillTemplateFields::reader, Part::Geometry2d::Restore(), buildPsets::u, and TestSpreadsheet::v.
Save()
void Geom2dArcOfEllipse::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Reimplemented from Part::Geometry2d.
Definition at line 1326 of file Geometry2d.cpp.
References SCL.SimpleDataTypes::e, Handle(), Base::Writer::ind(), Part::Geometry2d::Save(), Base::Writer::Stream(), buildPsets::u, and TestSpreadsheet::v.
setHandle()
void Geom2dArcOfEllipse::setHandle (const Handle(Geom2d_TrimmedCurve)& c)
Definition at line 1226 of file Geometry2d.cpp.
References SCL.SimpleDataTypes::c, and Handle().
setMajorAxisDir()
void Geom2dArcOfEllipse::setMajorAxisDir (Base::Vector2d newdir)
Geom2dArcOfEllipse::setMajorAxisDir Rotates the ellipse in its plane, so that its major axis is as close as possible to the provided direction.
Parameters
newdir [in] is the new direction. If the vector is small, the orientation of the ellipse will be preserved. If the vector is not small, but its projection onto plane of the ellipse is small, an exception will be thrown.
Definition at line 1303 of file Geometry2d.cpp.
References SCL.SimpleDataTypes::c, SCL.SimpleDataTypes::e, Handle(), Base::Vector2d::Length(), RobotExample::pos, Base::Vector2d::x, and Base::Vector2d::y.
setMajorRadius()
void Part::Geom2dArcOfEllipse::setMajorRadius (double Radius)
setMinorRadius()
void Geom2dArcOfEllipse::setMinorRadius (double Radius)
Definition at line 1270 of file Geometry2d.cpp.
References SCL.SimpleDataTypes::e, and Handle().
The documentation for this class was generated from the following files:
Geometry2d.h
Geometry2d.cpp