FreeCAD: MillSim::GCodeParser Class Reference
MillSim::GCodeParser Class Reference
#include <GCodeParser.h>
Public Member Functions
GCodeParser ()
virtual ~GCodeParser ()
bool Parse (const char *filename)
bool AddLine (const char *ptr)
Public Attributes
std::vector< MillMotion > Operations
MillMotion lastState = {eNop, 0, 0, 0, 0, 0, 0, 0, 0}
MillMotion lastLastState = {eNop, 0, 0, 0, 0, 0, 0, 0, 0}
Protected Member Functions
const char * GetNextToken (const char *ptr, GCToken *token)
bool IsValidToken (char tok)
const char * ParseFloat (const char *ptr, float *retFloat)
bool ParseLine (const char *ptr)
Protected Attributes
int lastTool = -1
Detailed Description
Definition at line 57 of file GCodeParser.h.
Constructor & Destructor Documentation
GCodeParser()
MillSim::GCodeParser::GCodeParser () inline
Definition at line 60 of file GCodeParser.h.
~GCodeParser()
GCodeParser::~GCodeParser () virtual
Definition at line 35 of file GCodeParser.cpp.
References Operations.
Member Function Documentation
AddLine()
bool GCodeParser::AddLine (const char * ptr)
Definition at line 208 of file GCodeParser.cpp.
References MillSim::MillMotion::cmd, MillSim::eDril, MillSim::eMoveLiner, lastState, Operations, ParseLine(), MillSim::MillMotion::r, and MillSim::MillMotion::z.
Referenced by MillSim::MillSimulation::AddGcodeLine(), and Parse().
GetNextToken()
const char * GCodeParser::GetNextToken (const char * ptr, GCToken * token) protected
Definition at line 63 of file GCodeParser.cpp.
References MillSim::GCToken::fval, IsValidToken(), MillSim::GCToken::ival, MillSim::GCToken::letter, and ParseFloat().
Referenced by ParseLine().
IsValidToken()
bool GCodeParser::IsValidToken (char tok) protected
Definition at line 89 of file GCodeParser.cpp.
References SplineSurface::i, and TokTypes.
Referenced by GetNextToken().
Parse()
bool GCodeParser::Parse (const char * filename)
Definition at line 41 of file GCodeParser.cpp.
References AddLine(), MillSim::eNop, lastState, lastTool, and Operations.
Referenced by MillSim::MillSimulation::LoadGCodeFile().
ParseFloat()
const char * GCodeParser::ParseFloat (const char * ptr, float * retFloat) protected
Definition at line 100 of file GCodeParser.cpp.
References KDL::sign().
Referenced by GetNextToken().
ParseLine()
bool GCodeParser::ParseLine (const char * ptr) protected
Definition at line 139 of file GCodeParser.cpp.
References MillSim::MillMotion::cmd, MillSim::eDril, MillSim::eMoveLiner, MillSim::eRotateCCW, MillSim::eRotateCW, MillSim::GCToken::fval, GetNextToken(), MillSim::MillMotion::i, MillSim::GCToken::ival, MillSim::MillMotion::j, MillSim::MillMotion::k, lastLastState, lastState, MillSim::GCToken::letter, MillSim::MillMotion::r, MillSim::MillMotion::tool, MillSim::MillMotion::x, MillSim::MillMotion::y, and MillSim::MillMotion::z.
Referenced by AddLine().
Member Data Documentation
lastLastState
MillMotion MillSim::GCodeParser::lastLastState = {eNop, 0, 0, 0, 0, 0, 0, 0, 0}
Definition at line 69 of file GCodeParser.h.
Referenced by ParseLine().
lastState
MillMotion MillSim::GCodeParser::lastState = {eNop, 0, 0, 0, 0, 0, 0, 0, 0}
Definition at line 68 of file GCodeParser.h.
Referenced by AddLine(), Parse(), and ParseLine().
lastTool
int MillSim::GCodeParser::lastTool = -1 protected
Definition at line 76 of file GCodeParser.h.
Referenced by Parse().
Operations
std::vector<MillMotion> MillSim::GCodeParser::Operations
Definition at line 67 of file GCodeParser.h.
Referenced by AddLine(), MillSim::MillSimulation::Clear(), MillSim::MillSimulation::InitSimulation(), Parse(), and ~GCodeParser().
The documentation for this class was generated from the following files:
GCodeParser.h
GCodeParser.cpp