FreeCAD: TechDrawGui::QGITemplate Class Reference
TechDrawGui::QGITemplate Class Reference abstract
#include <QGITemplate.h>
Public Types
enum { Type = QGraphicsItem::UserType + 150 }
Public Member Functions
QGITemplate (QGSPage *)
~QGITemplate () override
int type () const override
void clearContents ()
void setTemplate (TechDraw::DrawTemplate *obj)
TechDraw::DrawTemplate * getTemplate ()
qreal getY ()
virtual void updateView (bool update=false)
std::vector< TemplateTextField * > getTextFields ()
virtual void draw ()=0
Protected Attributes
TechDraw::DrawTemplate * pageTemplate
std::vector< TemplateTextField * > textFields
Detailed Description
Definition at line 44 of file QGITemplate.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 52 of file QGITemplate.h.
Constructor & Destructor Documentation
QGITemplate()
QGITemplate::QGITemplate (QGSPage * scene)
Definition at line 34 of file QGITemplate.cpp.
References ZVALUE::TEMPLATE.
~QGITemplate()
QGITemplate::~QGITemplate () override
Definition at line 44 of file QGITemplate.cpp.
References pageTemplate.
Member Function Documentation
clearContents()
void QGITemplate::clearContents ()
Definition at line 57 of file QGITemplate.cpp.
draw()
virtual void TechDrawGui::QGITemplate::draw () pure virtual
Implemented in TechDrawGui::QGISVGTemplate, and TechDrawGui::QGIDrawingTemplate.
Referenced by updateView().
getTemplate()
TechDraw::DrawTemplate* TechDrawGui::QGITemplate::getTemplate () inline
Definition at line 58 of file QGITemplate.h.
getTextFields()
std::vector<TemplateTextField *> TechDrawGui::QGITemplate::getTextFields () inline
Definition at line 63 of file QGITemplate.h.
Referenced by TechDrawGui::ViewProviderTemplate::setMarkers().
getY()
qreal TechDrawGui::QGITemplate::getY () inline
Definition at line 60 of file QGITemplate.h.
References MovieTool::y.
setTemplate()
void QGITemplate::setTemplate (TechDraw::DrawTemplate * obj)
Definition at line 49 of file QGITemplate.cpp.
References pageTemplate.
Referenced by TechDrawGui::QGSPage::setPageTemplate(), and TechDrawGui::QGSPage::updateTemplate().
type()
int TechDrawGui::QGITemplate::type () const inline override
Definition at line 53 of file QGITemplate.h.
updateView()
void QGITemplate::updateView (bool update = false) virtual
Reimplemented in TechDrawGui::QGISVGTemplate, and TechDrawGui::QGIDrawingTemplate.
Definition at line 62 of file QGITemplate.cpp.
References draw().
Referenced by TechDrawGui::QGSPage::setPageTemplate(), TechDrawGui::ViewProviderTemplate::updateData(), and TechDrawGui::QGSPage::updateTemplate().
Member Data Documentation
pageTemplate
TechDraw::DrawTemplate* TechDrawGui::QGITemplate::pageTemplate protected
Definition at line 68 of file QGITemplate.h.
Referenced by TechDrawGui::QGIDrawingTemplate::getParametricTemplate(), TechDrawGui::QGISVGTemplate::getSVGTemplate(), setTemplate(), and ~QGITemplate().
textFields
std::vector<TemplateTextField *> TechDrawGui::QGITemplate::textFields protected
Definition at line 70 of file QGITemplate.h.
Referenced by TechDrawGui::QGISVGTemplate::createClickHandles().
The documentation for this class was generated from the following files:
QGITemplate.h
QGITemplate.cpp