FreeCAD: Gui::SoFCUnifiedSelection Class Reference
Gui::SoFCUnifiedSelection Class Reference
#include <SoFCUnifiedSelection.h>
Public Types
enum HighlightModes { AUTO, ON, OFF }
Public Member Functions
SoFCUnifiedSelection ()
void applySettings ()
const char * getFileFormatName () const override
void write (SoWriteAction *action) override
void doAction (SoAction *action) override
void handleEvent (SoHandleEventAction *action) override
void GLRenderBelowPath (SoGLRenderAction *action) override
Static Public Member Functions
static void initClass ()
static void finish ()
static bool hasHighlight ()
Public Attributes
SoSFColor colorHighlight
SoSFColor colorSelection
SoSFEnum highlightMode
SoSFEnum selectionMode
SoSFBool selectionRole
SoSFBool useNewSelection
Protected Member Functions
~SoFCUnifiedSelection () override
Friends
class View3DInventorViewer
Detailed Description
Unified Selection node This is the new selection node for the 3D Viewer which will gradually remove all the low level selection nodes in the view provider. The handling of the highlighting and the selection will be unified here.
Author
Jürgen Riegel
Definition at line 57 of file SoFCUnifiedSelection.h.
Member Enumeration Documentation
HighlightModes
enum Gui::SoFCUnifiedSelection::HighlightModes
Enumerator
AUTO
ON
OFF
Definition at line 68 of file SoFCUnifiedSelection.h.
Constructor & Destructor Documentation
SoFCUnifiedSelection()
SoFCUnifiedSelection::SoFCUnifiedSelection ()
Constructor.
Definition at line 112 of file SoFCUnifiedSelection.cpp.
References SCL.SimpleDataTypes::f, and MeshCore::MeshIO::OFF.
~SoFCUnifiedSelection()
SoFCUnifiedSelection::~SoFCUnifiedSelection () override protected
Destructor.
Definition at line 143 of file SoFCUnifiedSelection.cpp.
Member Function Documentation
applySettings()
void SoFCUnifiedSelection::applySettings ()
Definition at line 173 of file SoFCUnifiedSelection.cpp.
References colorHighlight, colorSelection, ParameterGrp::GetBool(), Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), ParameterGrp::GetUnsigned(), highlight(), highlightMode, OpenSCADFeatures::long, OFF, Path.Dressup.Utils::selection(), and selectionMode.
Referenced by Gui::View3DInventorViewer::init().
doAction()
void SoFCUnifiedSelection::doAction (SoAction * action) override
Definition at line 313 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::SelectionChanges::AddSelection, Gui::SoSelectionElementAction::All, Gui::SoSelectionElementAction::Append, AUTO, Gui::SelectionChanges::ClrSelection, colorHighlight, colorSelection, toolbit-attributes::doc, App::GetApplication(), Base::Persistence::getClassTypeId(), Gui::ViewProvider::getDetail(), Gui::ViewProvider::getDetailPath(), App::Application::getDocument(), Gui::ViewProvider::getRoot(), Gui::Application::getViewProvider(), Gui::Document::getViewProvidersOfType(), highlightMode, SplineSurface::i, Gui::Application::Instance, Base::BaseClass::isDerivedFrom(), Data::isMappedElement(), Gui::ViewProvider::isSelectable(), Gui::SelectionSingleton::isSelected(), Gui::SoSelectionElementAction::None, OFF, App::ElementNamePair::oldName, ON, Gui::SoSelectionElementAction::Remove, App::GeoFeature::resolveElement(), Gui::SelectionChanges::RmvPreselect, Gui::SelectionChanges::RmvSelection, Gui::Selection(), selectionMode, Gui::SoHighlightElementAction::setColor(), Gui::SoSelectionElementAction::setColor(), Gui::SoHighlightElementAction::setElement(), Gui::SoSelectionElementAction::setElement(), Gui::SoHighlightElementAction::setHighlighted(), Gui::SelectionChanges::SetPreselect, Gui::SelectionChanges::SetPreselectSignal, Gui::SelectionChanges::SetSelection, Path.Post.scripts.grbl_post::type, useNewSelection, and Gui::ViewProvider::useNewSelectionModel().
finish()
void SoFCUnifiedSelection::finish () static
Definition at line 164 of file SoFCUnifiedSelection.cpp.
Referenced by drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::accept(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::accept(), draftguitools.gui_split.Split::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_subelements.SubelementHighlight::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rotate.Rotate::action(), draftguitools.gui_fillets.Fillet::action(), draftguitools.gui_move.Move::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_arcs.Arc::action(), draftguitools.gui_texts.Text::action(), draftguitools.gui_scale.Scale::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_trimex.Trimex::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_styles.ApplyStyle::Activated(), draftguitools.gui_join.Join::Activated(), draftguitools.gui_draft2sketch.Draft2Sketch::Activated(), draftguitools.gui_downgrade.Downgrade::Activated(), draftguitools.gui_upgrade.Upgrade::Activated(), draftguitools.gui_shape2dview.Shape2DView::Activated(), draftguitools.gui_facebinders.Facebinder::Activated(), draftguitools.gui_subelements.SubelementHighlight::Activated(), draftguitools.gui_wire2spline.WireToBSpline::Activated(), draftguitools.gui_clone.Clone::Activated(), draftguitools.gui_dimensions.Dimension::Activated(), draftguitools.gui_edit.Edit::Activated(), draftguitools.gui_selectplane.Draft_SelectPlane::check_selection(), DraftGui.DraftToolBar::checkSpecialChars(), draftguitools.gui_points.Point::click(), draftguitools.gui_orthoarray.OrthoArray::completed(), draftguitools.gui_polararray.PolarArray::completed(), draftguitools.gui_circulararray.CircularArray::completed(), draftguitools.gui_labels.Label::create(), bimcommands.BimText.BIM_Text::createObject(), draftguitools.gui_rectangles.Rectangle::createObject(), draftguitools.gui_ellipses.Ellipse::createObject(), draftguitools.gui_texts.Text::createObject(), draftviewproviders.view_text.ViewProviderText::createObject(), draftguitools.gui_stretch.Stretch::doStretch(), draftguitools.gui_fillets.Fillet::draw_arc(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), DraftGui.DraftToolBar::editUi(), DraftGui.DraftToolBar::escape(), draftguitools.gui_move.Move::get_object_selection(), draftguitools.gui_rotate.Rotate::get_object_selection(), draftguitools.gui_scale.Scale::get_object_selection(), draftguitools.gui_arcs.Arc_3Points::getPoint(), draftguitools.gui_edit.Edit::keyPressed(), draftguitools.gui_dimensions.Dimension::numericInput(), draftguitools.gui_offset.Offset::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), draftguitools.gui_trimex.Trimex::numericRadius(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_align(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_auto(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_center(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_front(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_move(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_next(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_previous(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_side(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_top(), bimcommands.BimShape2DView.BIM_Shape2DView::proceed(), draftguitools.gui_join.Join::proceed(), draftguitools.gui_draft2sketch.Draft2Sketch::proceed(), draftguitools.gui_subelements.SubelementHighlight::proceed(), bimcommands.BimSlab.BIM_Slab::proceed(), draftguitools.gui_upgrade.Upgrade::proceed(), draftguitools.gui_downgrade.Downgrade::proceed(), draftguitools.gui_pathtwistedarray.PathTwistedArray::proceed(), draftguitools.gui_facebinders.Facebinder::proceed(), draftguitools.gui_shape2dview.Shape2DView::proceed(), draftguitools.gui_clone.Clone::proceed(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_pointarray.PointArray::proceed(), draftguitools.gui_patharray.PathArray::proceed(), draftguitools.gui_trimex.Trimex::proceed(), draftguitools.gui_edit.Edit::proceed(), draftguitools.gui_selectplane.Draft_SelectPlane::reject(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::reject(), drafttaskpanels.task_polararray.TaskPanelPolarArray::reject(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::reject(), and draftguitools.gui_edit.Edit::setTrackers().
getFileFormatName()
const char * SoFCUnifiedSelection::getFileFormatName () const override
Definition at line 204 of file SoFCUnifiedSelection.cpp.
GLRenderBelowPath()
void SoFCUnifiedSelection::GLRenderBelowPath (SoGLRenderAction * action) override
Definition at line 790 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, SCL.SimpleDataTypes::c, Gui::SoGLWidgetElement::get(), and Init::parent.
handleEvent()
void SoFCUnifiedSelection::handleEvent (SoHandleEventAction * action) override
Definition at line 729 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, AUTO, SCL.SimpleDataTypes::e, Gui::SelectionSingleton::getSelectionStyle(), Gui::SelectionSingleton::GreedySelection, highlightMode, ON, Gui::Selection(), selectionMode, and selectionRole.
hasHighlight()
bool SoFCUnifiedSelection::hasHighlight () static
Definition at line 169 of file SoFCUnifiedSelection.cpp.
initClass()
void SoFCUnifiedSelection::initClass () static
Definition at line 159 of file SoFCUnifiedSelection.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
write()
void SoFCUnifiedSelection::write (SoWriteAction * action) override
Definition at line 209 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and feminout.exportNastranMesh::write().
Friends And Related Function Documentation
View3DInventorViewer
friend class View3DInventorViewer friend
Definition at line 92 of file SoFCUnifiedSelection.h.
Member Data Documentation
colorHighlight
SoSFColor Gui::SoFCUnifiedSelection::colorHighlight
Definition at line 75 of file SoFCUnifiedSelection.h.
Referenced by applySettings(), Gui::View3DInventorSelection::checkGroupOnTop(), and doAction().
colorSelection
SoSFColor Gui::SoFCUnifiedSelection::colorSelection
Definition at line 76 of file SoFCUnifiedSelection.h.
Referenced by applySettings(), and doAction().
highlightMode
SoSFEnum Gui::SoFCUnifiedSelection::highlightMode
Definition at line 77 of file SoFCUnifiedSelection.h.
Referenced by applySettings(), doAction(), and handleEvent().
selectionMode
SoSFEnum Gui::SoFCUnifiedSelection::selectionMode
Definition at line 78 of file SoFCUnifiedSelection.h.
Referenced by applySettings(), doAction(), handleEvent(), and PartGui::Location::~Location().
selectionRole
SoSFBool Gui::SoFCUnifiedSelection::selectionRole
Definition at line 79 of file SoFCUnifiedSelection.h.
Referenced by handleEvent().
useNewSelection
SoSFBool Gui::SoFCUnifiedSelection::useNewSelection
Definition at line 80 of file SoFCUnifiedSelection.h.
Referenced by doAction().
The documentation for this class was generated from the following files:
SoFCUnifiedSelection.h
SoFCUnifiedSelection.cpp