FreeCAD: Gui::SoSkipBoundingGroup Class Reference
Gui::SoSkipBoundingGroup Class Reference
#include <SoFCBoundingBox.h>
Public Types
enum Modes { INCLUDE_BBOX, EXCLUDE_BBOX }
Public Member Functions
SoSkipBoundingGroup ()
void getBoundingBox (SoGetBoundingBoxAction *action) override
Static Public Member Functions
static void initClass ()
static void finish ()
Public Attributes
SoSFEnum mode
Protected Member Functions
~SoSkipBoundingGroup () override
Detailed Description
This is a special group node which must be defined to ignore bounding box actions.
Author
Werner Mayer
Definition at line 101 of file SoFCBoundingBox.h.
Member Enumeration Documentation
Modes
enum Gui::SoSkipBoundingGroup::Modes
Enumerator
INCLUDE_BBOX
EXCLUDE_BBOX
Definition at line 111 of file SoFCBoundingBox.h.
Constructor & Destructor Documentation
SoSkipBoundingGroup()
SoSkipBoundingGroup::SoSkipBoundingGroup ()
Constructor.
Definition at line 238 of file SoFCBoundingBox.cpp.
~SoSkipBoundingGroup()
SoSkipBoundingGroup::~SoSkipBoundingGroup () override protected default
Destructor.
Member Function Documentation
finish()
void SoSkipBoundingGroup::finish () static
Definition at line 260 of file SoFCBoundingBox.cpp.
Referenced by drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::accept(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::accept(), draftguitools.gui_split.Split::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_subelements.SubelementHighlight::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rotate.Rotate::action(), draftguitools.gui_fillets.Fillet::action(), draftguitools.gui_move.Move::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_arcs.Arc::action(), draftguitools.gui_texts.Text::action(), draftguitools.gui_scale.Scale::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_trimex.Trimex::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_styles.ApplyStyle::Activated(), draftguitools.gui_join.Join::Activated(), draftguitools.gui_draft2sketch.Draft2Sketch::Activated(), draftguitools.gui_downgrade.Downgrade::Activated(), draftguitools.gui_upgrade.Upgrade::Activated(), draftguitools.gui_shape2dview.Shape2DView::Activated(), draftguitools.gui_facebinders.Facebinder::Activated(), draftguitools.gui_subelements.SubelementHighlight::Activated(), draftguitools.gui_wire2spline.WireToBSpline::Activated(), draftguitools.gui_clone.Clone::Activated(), draftguitools.gui_dimensions.Dimension::Activated(), draftguitools.gui_edit.Edit::Activated(), draftguitools.gui_selectplane.Draft_SelectPlane::check_selection(), DraftGui.DraftToolBar::checkSpecialChars(), draftguitools.gui_points.Point::click(), draftguitools.gui_orthoarray.OrthoArray::completed(), draftguitools.gui_polararray.PolarArray::completed(), draftguitools.gui_circulararray.CircularArray::completed(), draftguitools.gui_labels.Label::create(), bimcommands.BimText.BIM_Text::createObject(), draftguitools.gui_rectangles.Rectangle::createObject(), draftguitools.gui_ellipses.Ellipse::createObject(), draftguitools.gui_texts.Text::createObject(), draftviewproviders.view_text.ViewProviderText::createObject(), draftguitools.gui_stretch.Stretch::doStretch(), draftguitools.gui_fillets.Fillet::draw_arc(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), DraftGui.DraftToolBar::editUi(), DraftGui.DraftToolBar::escape(), draftguitools.gui_move.Move::get_object_selection(), draftguitools.gui_rotate.Rotate::get_object_selection(), draftguitools.gui_scale.Scale::get_object_selection(), draftguitools.gui_arcs.Arc_3Points::getPoint(), draftguitools.gui_edit.Edit::keyPressed(), draftguitools.gui_dimensions.Dimension::numericInput(), draftguitools.gui_offset.Offset::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), draftguitools.gui_trimex.Trimex::numericRadius(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_align(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_auto(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_center(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_front(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_move(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_next(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_previous(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_side(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_top(), bimcommands.BimShape2DView.BIM_Shape2DView::proceed(), draftguitools.gui_join.Join::proceed(), draftguitools.gui_draft2sketch.Draft2Sketch::proceed(), draftguitools.gui_subelements.SubelementHighlight::proceed(), bimcommands.BimSlab.BIM_Slab::proceed(), draftguitools.gui_upgrade.Upgrade::proceed(), draftguitools.gui_downgrade.Downgrade::proceed(), draftguitools.gui_pathtwistedarray.PathTwistedArray::proceed(), draftguitools.gui_facebinders.Facebinder::proceed(), draftguitools.gui_shape2dview.Shape2DView::proceed(), draftguitools.gui_clone.Clone::proceed(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_pointarray.PointArray::proceed(), draftguitools.gui_patharray.PathArray::proceed(), draftguitools.gui_trimex.Trimex::proceed(), draftguitools.gui_edit.Edit::proceed(), draftguitools.gui_selectplane.Draft_SelectPlane::reject(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::reject(), drafttaskpanels.task_polararray.TaskPanelPolarArray::reject(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::reject(), and draftguitools.gui_edit.Edit::setTrackers().
getBoundingBox()
void SoSkipBoundingGroup::getBoundingBox (SoGetBoundingBoxAction * action) override
Definition at line 265 of file SoFCBoundingBox.cpp.
References Path.Post.scripts.dynapath_4060_post::action, INCLUDE_BBOX, and mode.
initClass()
void SoSkipBoundingGroup::initClass () static
Definition at line 255 of file SoFCBoundingBox.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
Member Data Documentation
mode
SoSFEnum Gui::SoSkipBoundingGroup::mode
Definition at line 115 of file SoFCBoundingBox.h.
Referenced by femtaskpanels.task_constraint_bodyheatsource._TaskPanel::accept(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_lines.Line::Activated(), draftguitools.gui_lines.Line::drawSegment(), Commands.SphereCreator::enter(), getBoundingBox(), Commands.SphereCreator::leave(), femtaskpanels.task_constraint_bodyheatsource._TaskPanel::mode_changed(), draftguitools.gui_offset.Offset::numericRadius(), and draftguitools.gui_trackers.archDimTracker::setString().
The documentation for this class was generated from the following files:
SoFCBoundingBox.h
SoFCBoundingBox.cpp