FreeCAD: ifc2x3.ifcobject Class Reference
ifc2x3.ifcobject Class Reference
Public Member Functions
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, objecttype)
def objecttype ()
def isdefinedby ()
def wr1 (self)
Public Member Functions inherited from ifc2x3.ifcobjectdefinition
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description)
def hasassignments ()
def isdecomposedby ()
def decomposes ()
def hasassociations ()
Public Member Functions inherited from ifc2x3.ifcroot
def globalid ()
def ownerhistory ()
def name ()
def description ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
objecttype
Public Attributes inherited from ifc2x3.ifcroot
globalid
ownerhistory
name
description
Detailed Description
Entity ifcobject definition.
:param objecttype
:type objecttype:ifclabel
:param isdefinedby
:type isdefinedby:SET(0,None,'ifcreldefines', scope = schema_scope)
Definition at line 2192 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcobject.__init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, objecttype)
Reimplemented in ifc2x3.ifczone, ifc2x3.ifccondition, ifc2x3.ifcresource, ifc2x3.ifcprocess, ifc2x3.ifcequipmentstandard, ifc2x3.ifcfurniturestandard, ifc2x3.ifcelectricalcircuit, ifc2x3.ifcsystem, ifc2x3.ifcgroup, ifc2x3.ifccostitem, and ifc2x3.ifccontrol.
Definition at line 2201 of file ifc2x3.py.
Member Function Documentation
isdefinedby()
def ifc2x3.ifcobject.isdefinedby ()
Definition at line 2220 of file ifc2x3.py.
objecttype()
def ifc2x3.ifcobject.objecttype ()
Definition at line 2206 of file ifc2x3.py.
References ifc2x3.ifcobject._objecttype, SCL.TypeChecker.check_type(), and ifc2x3.ifcobject.objecttype.
wr1()
def ifc2x3.ifcobject.wr1 (self)
Reimplemented in ifc2x3.ifcramp, ifc2x3.ifcconditioncriterion, ifc2x3.ifcasset, ifc2x3.ifczone, ifc2x3.ifcprocedure, ifc2x3.ifcconstructionproductresource, ifc2x3.ifcconstructionmaterialresource, ifc2x3.ifcbuildingelementproxy, ifc2x3.ifcproxy, ifc2x3.ifcpile, ifc2x3.ifcmove, ifc2x3.ifcreinforcingbar, ifc2x3.ifctendon, ifc2x3.ifctask, ifc2x3.ifcstair, ifc2x3.ifcworkcontrol, ifc2x3.ifcelementassembly, ifc2x3.ifcwallstandardcase, ifc2x3.ifcroof, ifc2x3.ifcwall, ifc2x3.ifcfooting, and ifc2x3.ifcproduct.
Definition at line 2227 of file ifc2x3.py.
References SCL.Builtin.SIZEOF().
Referenced by ifc4.ifctextalignment.__init__(), ifc4.ifcspecularroughness.__init__(), ifc4.ifcheatingvaluemeasure.__init__(), ifc4.ifctexttransformation.__init__(), ifc4.ifcfontstyle.__init__(), ifc4.ifcboxalignment.__init__(), ifc4.ifcpositiveplaneanglemeasure.__init__(), ifc4.ifcdimensioncount.__init__(), ifc4.ifcfontvariant.__init__(), ifc4.ifcfontweight.__init__(), ifc4.ifcnormalisedratiomeasure.__init__(), ifc4.ifcpositivelengthmeasure.__init__(), ifc4.ifcpositiveratiomeasure.__init__(), and ifc4.ifctextdecoration.__init__().
Member Data Documentation
objecttype
ifc2x3.ifcobject.objecttype
Definition at line 2203 of file ifc2x3.py.
Referenced by ifc2x3.ifcobject.objecttype().
The documentation for this class was generated from the following file:
ifc2x3.py