FreeCAD: Base::Reference< T > Class Template Reference
Base::Reference< T > Class Template Reference
#include <Handle.h>
Public Member Functions
Reference ()
Reference (T *pointer)
Reference (const Reference< T > &ref)
~Reference ()
Reference< T > & operator= (T *pointer)
Reference< T > & operator= (const Reference< T > &ref)
T & operator* () const
T * operator-> () const
operator T* () const
bool isValid () const
Test if it handles something.
bool isNull () const
Test if it does not handle anything.
int getRefCount () const
Get number of references on the object, including this one.
Detailed Description
template<class T>
class Base::Reference< T >
Reference class Implementation of the reference counting pattern. Only able to instantiate with a class inheriting Base::Handled.
Definition at line 44 of file Handle.h.
Constructor & Destructor Documentation
Reference() [1/3]
template<class T > Base::Reference< T >::Reference () inline
Pointer and default constructor
Definition at line 51 of file Handle.h.
Reference() [2/3]
template<class T > Base::Reference< T >::Reference (T * pointer) inline
Definition at line 55 of file Handle.h.
Reference() [3/3]
template<class T > Base::Reference< T >::Reference (const Reference< T > & ref) inline
Copy constructor
Definition at line 64 of file Handle.h.
~Reference()
template<class T > Base::Reference< T >::~Reference () inline
destructor Release the reference counter which causes, in case of the last one, the referenced object to be destructed!
Definition at line 77 of file Handle.h.
Member Function Documentation
getRefCount()
template<class T > int Base::Reference< T >::getRefCount () const inline
Get number of references on the object, including this one.
Definition at line 154 of file Handle.h.
Referenced by Gui::Dialog::ParameterGroupItem::~ParameterGroupItem().
isNull()
template<class T > bool Base::Reference< T >::isNull () const inline
Test if it does not handle anything.
Definition at line 148 of file Handle.h.
Referenced by Part::PropertyPartShape::Save().
isValid()
template<class T > bool Base::Reference< T >::isValid () const inline
Test if it handles something.
Definition at line 142 of file Handle.h.
Referenced by Gui::InputField::getHistory(), Gui::InputField::getSavedValues(), Gui::InputField::paramGrpPath(), Gui::InputField::pushToHistory(), Gui::InputField::pushToSavedValues(), Gui::WindowParameter::setGroupName(), Gui::StatefulLabel::setParameterGroup(), Gui::InputField::setParamGrpPath(), and Gui::StatefulLabel::~StatefulLabel().
operator T*()
template<class T > Base::Reference< T >::operator T* () const inline
Definition at line 133 of file Handle.h.
operator*()
template<class T > T& Base::Reference< T >::operator* () const inline
Dereference operator
Definition at line 122 of file Handle.h.
operator->()
template<class T > T* Base::Reference< T >::operator-> () const inline
Dereference operator
Definition at line 128 of file Handle.h.
operator=() [1/2]
template<class T > Reference<T>& Base::Reference< T >::operator= (const Reference< T > & ref) inline
Assign operator from a handle
Definition at line 105 of file Handle.h.
operator=() [2/2]
template<class T > Reference<T>& Base::Reference< T >::operator= (T * pointer) inline
Assign operator from a pointer
Definition at line 88 of file Handle.h.
The documentation for this class was generated from the following file:
Handle.h