FreeCAD: MaterialPyImp.cpp File Reference
Mod/Material/App/MaterialPyImp.cpp File Reference
#include "PreCompiled.h"
#include <QMetaType>
#include <Base/Quantity.h>
#include <Base/QuantityPy.h>
#include <CXX/Objects.hxx>
#include <Gui/MetaTypes.h>
#include "Materials.h"
#include "Array2DPy.h"
#include "Array3DPy.h"
#include "Exceptions.h"
#include "MaterialLibrary.h"
#include "MaterialPy.h"
#include "MaterialValue.h"
#include "MaterialPy.cpp"
Functions
static PyObject * _pyObjectFromVariant (const QVariant &value)
static Py::List getList (const QVariant &value)
Function Documentation
_pyObjectFromVariant()
static PyObject * _pyObjectFromVariant (const QVariant & value) static
Definition at line 453 of file Mod/Material/App/MaterialPyImp.cpp.
References getList(), and Py::new_reference_to().
Referenced by getList().
getList()
static Py::List getList (const QVariant & value) static
Definition at line 441 of file Mod/Material/App/MaterialPyImp.cpp.
References _pyObjectFromVariant().
Referenced by _pyObjectFromVariant().