FreeCAD: App::AutoTransaction Class Reference
App::AutoTransaction Class Reference
Helper class to manager transaction (i.e. undo/redo)
#include <AutoTransaction.h>
Public Member Functions
void * operator new (std::size_t)=delete
Private new operator to prevent heap allocation.
AutoTransaction (const char *name=nullptr, bool tmpName=false)
~AutoTransaction ()
void close (bool abort=false)
Static Public Member Functions
static void setEnable (bool enable)
Detailed Description
Helper class to manager transaction (i.e. undo/redo)
Definition at line 55 of file AutoTransaction.h.
Constructor & Destructor Documentation
AutoTransaction()
AutoTransaction::AutoTransaction (const char * name = nullptr, bool tmpName = false)
Constructor
Parameters
name optional new transaction name on construction
tmpName if true and a new transaction is setup, the name given is considered as temporary, and subsequent construction of this class (or calling Application::setActiveTransaction()) can override the transaction name.
The constructor increments an internal counter (Application::_activeTransactionGuard). The counter prevents any new active transaction being setup. It also prevents close (i.e. commits) the current active transaction until it reaches zero. It does not have any effect on aborting transaction, though.
Definition at line 40 of file AutoTransaction.cpp.
References src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui::app, FC_LOG, FC_TRACE, and App::GetApplication().
~AutoTransaction()
AutoTransaction::~AutoTransaction ()
Destructor
This destructor decrease an internal counter (Application::_activeTransactionGuard), and will commit any current active transaction when the counter reaches zero.
Definition at line 70 of file AutoTransaction.cpp.
References src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui::app, SCL.SimpleDataTypes::e, FC_ERR, FC_TRACE, and App::GetApplication().
Member Function Documentation
close()
void AutoTransaction::close (bool abort = false)
Close or abort the transaction
This function can be used to explicitly close (i.e. commit) the transaction, if the current transaction ID matches the one created inside the constructor. For aborting, it will abort any current transaction
Definition at line 99 of file AutoTransaction.cpp.
References App::Application::closeActiveTransaction(), and App::GetApplication().
Referenced by femsolver.reportdialog.ReportDialog::__init__(), TechDrawTools.TaskFillTemplateFields.TaskFillTemplateFields::proceed(), femexamples.examplesgui.FemExamples::reject(), and setEnable().
operator new()
void* App::AutoTransaction::operator new (std::size_t) delete
Private new operator to prevent heap allocation.
setEnable()
void AutoTransaction::setEnable (bool enable) static
Enable/Disable any AutoTransaction instance in the current stack
Once disabled, any empty temporary named transaction is closed. If there are non-empty or non-temporary named active transaction, it will not be auto closed.
This function may be used in, for example, Gui::Document::setEdit() to allow a transaction live past any command scope.
Definition at line 107 of file AutoTransaction.cpp.
References src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui::app, close(), FC_TRACE, App::GetApplication(), and TestSpreadsheet::v.
Referenced by Gui::TreeWidget::mouseDoubleClickEvent(), App::Application::setActiveTransaction(), and Gui::ControlSingleton::showDialog().
The documentation for this class was generated from the following files:
AutoTransaction.h
AutoTransaction.cpp