FreeCAD: Base::Flags< Enum > Class Template Reference
Base::Flags< Enum > Class Template Reference
#include <Bitmask.h>
Public Member Functions
constexpr Flags (Enum f=Enum())
constexpr bool testFlag (Enum f) const
constexpr void setFlag (Enum f, bool on=true)
constexpr bool isEqual (Flags f) const
constexpr Enum getFlags () const
constexpr Flags< Enum > & operator|= (const Flags< Enum > &other)
constexpr Flags< Enum > & operator|= (const Enum &f)
constexpr Flags< Enum > operator| (const Flags< Enum > &other) const
constexpr Flags< Enum > operator| (const Enum &f) const
constexpr Flags< Enum > & operator&= (const Flags< Enum > &other)
constexpr Flags< Enum > & operator&= (const Enum &f)
constexpr Flags< Enum > operator& (const Flags< Enum > &other) const
constexpr Flags< Enum > operator& (const Enum &f) const
constexpr Flags< Enum > operator~ () const
constexpr bool operator! () const
operator bool () const
std::underlying_type< Enum >::type toUnderlyingType () const
Detailed Description
template<typename Enum>
class Base::Flags< Enum >
Definition at line 111 of file Bitmask.h.
Constructor & Destructor Documentation
Flags()
template<typename Enum > constexpr Base::Flags< Enum >::Flags (Enum f = Enum()) inline constexpr
Definition at line 117 of file Bitmask.h.
Member Function Documentation
getFlags()
template<typename Enum > constexpr Enum Base::Flags< Enum >::getFlags () const inline constexpr
Definition at line 129 of file Bitmask.h.
isEqual()
template<typename Enum > constexpr bool Base::Flags< Enum >::isEqual (Flags< Enum > f) const inline constexpr
Definition at line 125 of file Bitmask.h.
Referenced by App::ColorGradientProfile::isEqual().
operator bool()
template<typename Enum > Base::Flags< Enum >::operator bool () const inline explicit
Definition at line 168 of file Bitmask.h.
operator!()
template<typename Enum > constexpr bool Base::Flags< Enum >::operator! () const inline constexpr
Definition at line 164 of file Bitmask.h.
operator&() [1/2]
template<typename Enum > constexpr Flags<Enum> Base::Flags< Enum >::operator& (const Enum & f) const inline constexpr
Definition at line 157 of file Bitmask.h.
operator&() [2/2]
template<typename Enum > constexpr Flags<Enum> Base::Flags< Enum >::operator& (const Flags< Enum > & other) const inline constexpr
Definition at line 154 of file Bitmask.h.
operator&=() [1/2]
template<typename Enum > constexpr Flags<Enum>& Base::Flags< Enum >::operator&= (const Enum & f) inline constexpr
Definition at line 150 of file Bitmask.h.
operator&=() [2/2]
template<typename Enum > constexpr Flags<Enum>& Base::Flags< Enum >::operator&= (const Flags< Enum > & other) inline constexpr
Definition at line 146 of file Bitmask.h.
operator|() [1/2]
template<typename Enum > constexpr Flags<Enum> Base::Flags< Enum >::operator| (const Enum & f) const inline constexpr
Definition at line 143 of file Bitmask.h.
operator|() [2/2]
template<typename Enum > constexpr Flags<Enum> Base::Flags< Enum >::operator| (const Flags< Enum > & other) const inline constexpr
Definition at line 140 of file Bitmask.h.
operator|=() [1/2]
template<typename Enum > constexpr Flags<Enum>& Base::Flags< Enum >::operator|= (const Enum & f) inline constexpr
Definition at line 136 of file Bitmask.h.
operator|=() [2/2]
template<typename Enum > constexpr Flags<Enum>& Base::Flags< Enum >::operator|= (const Flags< Enum > & other) inline constexpr
Definition at line 132 of file Bitmask.h.
operator~()
template<typename Enum > constexpr Flags<Enum> Base::Flags< Enum >::operator~ () const inline constexpr
Definition at line 160 of file Bitmask.h.
setFlag()
template<typename Enum > constexpr void Base::Flags< Enum >::setFlag (Enum f, bool on = true) inline constexpr
Definition at line 122 of file Bitmask.h.
Referenced by FC_LOG_LEVEL_INIT(), App::StringHasher::getID(), Gui::Dialog::DlgSettingsColorGradientImp::getProfile(), App::StringID::mark(), and App::StringID::setPersistent().
testFlag()
template<typename Enum > constexpr bool Base::Flags< Enum >::testFlag (Enum f) const inline constexpr
Definition at line 118 of file Bitmask.h.
Referenced by PartDesign::FeatureExtrude::buildExtrusion(), FC_LOG_LEVEL_INIT(), App::StringHasher::getID(), Gui::DlgObjectSelection::getSelections(), App::StringID::isBinary(), App::StringID::isHashed(), App::StringID::isIndexed(), App::StringID::isMarked(), App::StringID::isPersistent(), App::StringID::isPostfixed(), App::StringID::isPostfixEncoded(), App::StringID::isPrefixID(), App::StringID::isPrefixIDIndex(), App::SubObjectT::normalize(), App::LinkBaseExtension::setOnChangeCopyObject(), Gui::Dialog::DlgSettingsColorGradientImp::setProfile(), and App::CellAddress::toString().
toUnderlyingType()
template<typename Enum > std::underlying_type<Enum>::type Base::Flags< Enum >::toUnderlyingType () const inline
Definition at line 171 of file Bitmask.h.
Referenced by Base::Flags< Flag >::operator bool().
The documentation for this class was generated from the following file:
Bitmask.h