FreeCAD: Wm4::PolynomialRoots< Real > Class Template Reference
Wm4::PolynomialRoots< Real > Class Template Reference
#include <Wm4PolynomialRoots.h>
Public Member Functions
PolynomialRoots (Real fEpsilon)
~PolynomialRoots ()
int GetCount () const
const Real * GetRoots () const
Real GetRoot (int i) const
Real & Epsilon ()
Real Epsilon () const
int & MaxIterations ()
int MaxIterations () const
bool FindA (Real fC0, Real fC1)
Real GetBound (Real fC0, Real fC1)
bool FindA (Real fC0, Real fC1, Real fC2)
Real GetBound (Real fC0, Real fC1, Real fC2)
bool FindA (Real fC0, Real fC1, Real fC2, Real fC3)
bool FindE (Real fC0, Real fC1, Real fC2, Real fC3, bool bDoBalancing)
Real GetBound (Real fC0, Real fC1, Real fC2, Real fC3)
Real SpecialCubic (Real fA, Real fB, Real fC)
bool FindA (Real fC0, Real fC1, Real fC2, Real fC3, Real fC4)
bool FindE (Real fC0, Real fC1, Real fC2, Real fC3, Real fC4, bool bDoBalancing)
Real GetBound (Real fC0, Real fC1, Real fC2, Real fC3, Real fC4)
bool FindB (const Polynomial1< Real > &rkPoly, int iDigits)
bool FindN (const Polynomial1< Real > &rkPoly, int iDigits)
bool FindE (const Polynomial1< Real > &rkPoly, bool bDoBalancing)
Real GetBound (const Polynomial1< Real > &rkPoly)
bool FindB (const Polynomial1< Real > &rkPoly, Real fXMin, Real fXMax, int iDigits)
bool FindN (const Polynomial1< Real > &rkPoly, Real fXMin, Real fXMax, int iDigits)
bool AllRealPartsNegative (const Polynomial1< Real > &rkPoly)
bool AllRealPartsPositive (const Polynomial1< Real > &rkPoly)
int GetRootCount (const Polynomial1< Real > &rkPoly, Real fT0, Real fT1)
Detailed Description
template<class Real>
class Wm4::PolynomialRoots< Real >
Definition at line 49 of file Wm4PolynomialRoots.h.
Constructor & Destructor Documentation
PolynomialRoots()
template<class Real > Wm4::PolynomialRoots< Real >::PolynomialRoots (Real fEpsilon)
Definition at line 24 of file Wm4PolynomialRoots.cpp.
References WM4_NEW.
~PolynomialRoots()
template<class Real > Wm4::PolynomialRoots< Real >::~PolynomialRoots
Definition at line 35 of file Wm4PolynomialRoots.cpp.
References WM4_DELETE.
Member Function Documentation
AllRealPartsNegative()
template<class Real > bool Wm4::PolynomialRoots< Real >::AllRealPartsNegative (const Polynomial1< Real > & rkPoly)
Definition at line 1208 of file Wm4PolynomialRoots.cpp.
References Wm4::Polynomial1< Real >::GetDegree(), SplineSurface::i, Wm4::System::Memcpy(), and WM4_NEW.
AllRealPartsPositive()
template<class Real > bool Wm4::PolynomialRoots< Real >::AllRealPartsPositive (const Polynomial1< Real > & rkPoly)
Definition at line 1233 of file Wm4PolynomialRoots.cpp.
References Wm4::Polynomial1< Real >::GetDegree(), SplineSurface::i, Wm4::System::Memcpy(), and WM4_NEW.
Epsilon() [1/2]
template<class Real > Real Wm4::PolynomialRoots< Real >::Epsilon
Definition at line 65 of file Wm4PolynomialRoots.cpp.
Epsilon() [2/2]
template<class Real > Real Wm4::PolynomialRoots< Real >::Epsilon () const
FindA() [1/4]
template<class Real > bool Wm4::PolynomialRoots< Real >::FindA (Real fC0, Real fC1)
Definition at line 93 of file Wm4PolynomialRoots.cpp.
FindA() [2/4]
template<class Real > bool Wm4::PolynomialRoots< Real >::FindA (Real fC0, Real fC1, Real fC2)
Definition at line 125 of file Wm4PolynomialRoots.cpp.
References Wm4::Math< Real >::Sqrt().
FindA() [3/4]
template<class Real > bool Wm4::PolynomialRoots< Real >::FindA (Real fC0, Real fC1, Real fC2, Real fC3)
Definition at line 184 of file Wm4PolynomialRoots.cpp.
References Wm4::Math< Real >::ATan2(), Wm4::Math< Real >::Cos(), Wm4::Math< Real >::Pow(), Wm4::Math< Real >::Sin(), and Wm4::Math< Real >::Sqrt().
FindA() [4/4]
template<class Real > bool Wm4::PolynomialRoots< Real >::FindA (Real fC0, Real fC1, Real fC2, Real fC3, Real fC4)
Definition at line 605 of file Wm4PolynomialRoots.cpp.
References Wm4::Math< Real >::Sqrt().
FindB() [1/2]
template<class Real > bool Wm4::PolynomialRoots< Real >::FindB (const Polynomial1< Real > & rkPoly, int iDigits)
Definition at line 1063 of file Wm4PolynomialRoots.cpp.
FindB() [2/2]
template<class Real > bool Wm4::PolynomialRoots< Real >::FindB (const Polynomial1< Real > & rkPoly, Real fXMin, Real fXMax, int iDigits)
Definition at line 1113 of file Wm4PolynomialRoots.cpp.
References Wm4::Polynomial1< Real >::GetDegree(), Wm4::Polynomial1< Real >::GetDerivative(), SplineSurface::i, WM4_DELETE, and WM4_NEW.
FindE() [1/3]
template<class Real > bool Wm4::PolynomialRoots< Real >::FindE (const Polynomial1< Real > & rkPoly, bool bDoBalancing)
Definition at line 1079 of file Wm4PolynomialRoots.cpp.
FindE() [2/3]
template<class Real > bool Wm4::PolynomialRoots< Real >::FindE (Real fC0, Real fC1, Real fC2, Real fC3, bool bDoBalancing)
Definition at line 270 of file Wm4PolynomialRoots.cpp.
FindE() [3/3]
template<class Real > bool Wm4::PolynomialRoots< Real >::FindE (Real fC0, Real fC1, Real fC2, Real fC3, Real fC4, bool bDoBalancing)
Definition at line 702 of file Wm4PolynomialRoots.cpp.
FindN() [1/2]
template<class Real > bool Wm4::PolynomialRoots< Real >::FindN (const Polynomial1< Real > & rkPoly, int iDigits)
Definition at line 1071 of file Wm4PolynomialRoots.cpp.
FindN() [2/2]
template<class Real > bool Wm4::PolynomialRoots< Real >::FindN (const Polynomial1< Real > & rkPoly, Real fXMin, Real fXMax, int iDigits)
Definition at line 1200 of file Wm4PolynomialRoots.cpp.
GetBound() [1/5]
template<class Real > Real Wm4::PolynomialRoots< Real >::GetBound (const Polynomial1< Real > & rkPoly)
Definition at line 1087 of file Wm4PolynomialRoots.cpp.
References Wm4::Polynomial1< Real >::Compress(), Wm4::Math< Real >::FAbs(), Wm4::Polynomial1< Real >::GetDegree(), and SplineSurface::i.
GetBound() [2/5]
template<class Real > Real Wm4::PolynomialRoots< Real >::GetBound (Real fC0, Real fC1)
Definition at line 107 of file Wm4PolynomialRoots.cpp.
References Wm4::Math< Real >::FAbs().
GetBound() [3/5]
template<class Real > Real Wm4::PolynomialRoots< Real >::GetBound (Real fC0, Real fC1, Real fC2)
Definition at line 164 of file Wm4PolynomialRoots.cpp.
References Wm4::Math< Real >::FAbs().
GetBound() [4/5]
template<class Real > Real Wm4::PolynomialRoots< Real >::GetBound (Real fC0, Real fC1, Real fC2, Real fC3)
Definition at line 302 of file Wm4PolynomialRoots.cpp.
References Wm4::Math< Real >::FAbs().
GetBound() [5/5]
template<class Real > Real Wm4::PolynomialRoots< Real >::GetBound (Real fC0, Real fC1, Real fC2, Real fC3, Real fC4)
Definition at line 737 of file Wm4PolynomialRoots.cpp.
References Wm4::Math< Real >::FAbs().
GetCount()
template<class Real > int Wm4::PolynomialRoots< Real >::GetCount
Definition at line 41 of file Wm4PolynomialRoots.cpp.
GetRoot()
template<class Real > Real Wm4::PolynomialRoots< Real >::GetRoot (int i) const
Definition at line 53 of file Wm4PolynomialRoots.cpp.
References SplineSurface::i.
GetRootCount()
template<class Real > int Wm4::PolynomialRoots< Real >::GetRootCount (const Polynomial1< Real > & rkPoly, Real fT0, Real fT1)
Definition at line 1312 of file Wm4PolynomialRoots.cpp.
References Wm4::Polynomial1< Real >::Divide(), Wm4::Polynomial1< Real >::GetDegree(), Wm4::Polynomial1< Real >::GetDerivative(), SplineSurface::i, WM4_DELETE, and WM4_NEW.
GetRoots()
template<class Real > const Real * Wm4::PolynomialRoots< Real >::GetRoots
Definition at line 47 of file Wm4PolynomialRoots.cpp.
MaxIterations() [1/2]
template<class Real > int Wm4::PolynomialRoots< Real >::MaxIterations
Definition at line 77 of file Wm4PolynomialRoots.cpp.
MaxIterations() [2/2]
template<class Real > int Wm4::PolynomialRoots< Real >::MaxIterations () const
SpecialCubic()
template<class Real > Real Wm4::PolynomialRoots< Real >::SpecialCubic (Real fA, Real fB, Real fC)
Definition at line 329 of file Wm4PolynomialRoots.cpp.
References Wm4::Math< Real >::Pow(), and Wm4::Math< Real >::Sqrt().
The documentation for this class was generated from the following files:
Wm4PolynomialRoots.h
Wm4PolynomialRoots.cpp