FreeCAD: ifc2x3.ifcspacethermalloadproperties Class Reference
ifc2x3.ifcspacethermalloadproperties Class Reference
Public Member Functions
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, applicablevalueratio, thermalloadsource, propertysource, sourcedescription, maximumvalue, minimumvalue, thermalloadtimeseriesvalues, userdefinedthermalloadsource, userdefinedpropertysource, thermalloadtype)
def applicablevalueratio ()
def thermalloadsource ()
def propertysource ()
def sourcedescription ()
def maximumvalue ()
def minimumvalue ()
def thermalloadtimeseriesvalues ()
def userdefinedthermalloadsource ()
def userdefinedpropertysource ()
def thermalloadtype ()
Public Member Functions inherited from ifc2x3.ifcpropertysetdefinition
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description)
def propertydefinitionof ()
def definestype ()
Public Member Functions inherited from ifc2x3.ifcpropertydefinition
def hasassociations ()
Public Member Functions inherited from ifc2x3.ifcroot
def globalid ()
def ownerhistory ()
def name ()
def description ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
applicablevalueratio
thermalloadsource
propertysource
sourcedescription
maximumvalue
minimumvalue
thermalloadtimeseriesvalues
userdefinedthermalloadsource
userdefinedpropertysource
thermalloadtype
Public Attributes inherited from ifc2x3.ifcroot
globalid
ownerhistory
name
description
Detailed Description
Entity ifcspacethermalloadproperties definition.
:param applicablevalueratio
:type applicablevalueratio:ifcpositiveratiomeasure
:param thermalloadsource
:type thermalloadsource:ifcthermalloadsourceenum
:param propertysource
:type propertysource:ifcpropertysourceenum
:param sourcedescription
:type sourcedescription:ifctext
:param maximumvalue
:type maximumvalue:ifcpowermeasure
:param minimumvalue
:type minimumvalue:ifcpowermeasure
:param thermalloadtimeseriesvalues
:type thermalloadtimeseriesvalues:ifctimeseries
:param userdefinedthermalloadsource
:type userdefinedthermalloadsource:ifclabel
:param userdefinedpropertysource
:type userdefinedpropertysource:ifclabel
:param thermalloadtype
:type thermalloadtype:ifcthermalloadtypeenum
Definition at line 12683 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcspacethermalloadproperties.__init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, applicablevalueratio, thermalloadsource, propertysource, sourcedescription, maximumvalue, minimumvalue, thermalloadtimeseriesvalues, userdefinedthermalloadsource, userdefinedpropertysource, thermalloadtype)
Definition at line 12716 of file ifc2x3.py.
Member Function Documentation
applicablevalueratio()
def ifc2x3.ifcspacethermalloadproperties.applicablevalueratio ()
Definition at line 12730 of file ifc2x3.py.
References ifc2x3.ifcspacethermalloadproperties._applicablevalueratio, ifc2x3.ifcspacethermalloadproperties.applicablevalueratio, and SCL.TypeChecker.check_type().
maximumvalue()
def ifc2x3.ifcspacethermalloadproperties.maximumvalue ()
Definition at line 12786 of file ifc2x3.py.
References ifc2x3.ifcspacethermalloadproperties._maximumvalue, SCL.TypeChecker.check_type(), and ifc2x3.ifcspacethermalloadproperties.maximumvalue.
minimumvalue()
def ifc2x3.ifcspacethermalloadproperties.minimumvalue ()
Definition at line 12800 of file ifc2x3.py.
References ifc2x3.ifcspacethermalloadproperties._minimumvalue, SCL.TypeChecker.check_type(), and ifc2x3.ifcspacethermalloadproperties.minimumvalue.
propertysource()
def ifc2x3.ifcspacethermalloadproperties.propertysource ()
Definition at line 12758 of file ifc2x3.py.
References ifc2x3.ifcspacethermalloadproperties._propertysource, SCL.TypeChecker.check_type(), and ifc2x3.ifcspacethermalloadproperties.propertysource.
sourcedescription()
def ifc2x3.ifcspacethermalloadproperties.sourcedescription ()
Definition at line 12772 of file ifc2x3.py.
References ifc2x3.ifcspacethermalloadproperties._sourcedescription, SCL.TypeChecker.check_type(), and ifc2x3.ifcspacethermalloadproperties.sourcedescription.
thermalloadsource()
def ifc2x3.ifcspacethermalloadproperties.thermalloadsource ()
Definition at line 12744 of file ifc2x3.py.
References ifc2x3.ifcspacethermalloadproperties._thermalloadsource, SCL.TypeChecker.check_type(), and ifc2x3.ifcspacethermalloadproperties.thermalloadsource.
thermalloadtimeseriesvalues()
def ifc2x3.ifcspacethermalloadproperties.thermalloadtimeseriesvalues ()
Definition at line 12814 of file ifc2x3.py.
References ifc2x3.ifcspacethermalloadproperties._thermalloadtimeseriesvalues, SCL.TypeChecker.check_type(), and ifc2x3.ifcspacethermalloadproperties.thermalloadtimeseriesvalues.
thermalloadtype()
def ifc2x3.ifcspacethermalloadproperties.thermalloadtype ()
Definition at line 12856 of file ifc2x3.py.
References ifc2x3.ifcspacethermalloadproperties._thermalloadtype, SCL.TypeChecker.check_type(), and ifc2x3.ifcspacethermalloadproperties.thermalloadtype.
userdefinedpropertysource()
def ifc2x3.ifcspacethermalloadproperties.userdefinedpropertysource ()
Definition at line 12842 of file ifc2x3.py.
References ifc2x3.ifcspacethermalloadproperties._userdefinedpropertysource, SCL.TypeChecker.check_type(), and ifc2x3.ifcspacethermalloadproperties.userdefinedpropertysource.
userdefinedthermalloadsource()
def ifc2x3.ifcspacethermalloadproperties.userdefinedthermalloadsource ()
Definition at line 12828 of file ifc2x3.py.
References ifc2x3.ifcspacethermalloadproperties._userdefinedthermalloadsource, SCL.TypeChecker.check_type(), and ifc2x3.ifcspacethermalloadproperties.userdefinedthermalloadsource.
Member Data Documentation
applicablevalueratio
ifc2x3.ifcspacethermalloadproperties.applicablevalueratio
Definition at line 12718 of file ifc2x3.py.
Referenced by ifc2x3.ifcspacethermalloadproperties.applicablevalueratio().
maximumvalue
ifc2x3.ifcspacethermalloadproperties.maximumvalue
Definition at line 12722 of file ifc2x3.py.
Referenced by ifc2x3.ifcspacethermalloadproperties.maximumvalue().
minimumvalue
ifc2x3.ifcspacethermalloadproperties.minimumvalue
Definition at line 12723 of file ifc2x3.py.
Referenced by ifc2x3.ifcspacethermalloadproperties.minimumvalue().
propertysource
ifc2x3.ifcspacethermalloadproperties.propertysource
Definition at line 12720 of file ifc2x3.py.
Referenced by ifc2x3.ifcspacethermalloadproperties.propertysource().
sourcedescription
ifc2x3.ifcspacethermalloadproperties.sourcedescription
Definition at line 12721 of file ifc2x3.py.
Referenced by ifc2x3.ifcspacethermalloadproperties.sourcedescription().
thermalloadsource
ifc2x3.ifcspacethermalloadproperties.thermalloadsource
Definition at line 12719 of file ifc2x3.py.
Referenced by ifc2x3.ifcspacethermalloadproperties.thermalloadsource().
thermalloadtimeseriesvalues
ifc2x3.ifcspacethermalloadproperties.thermalloadtimeseriesvalues
Definition at line 12724 of file ifc2x3.py.
Referenced by ifc2x3.ifcspacethermalloadproperties.thermalloadtimeseriesvalues().
thermalloadtype
ifc2x3.ifcspacethermalloadproperties.thermalloadtype
Definition at line 12727 of file ifc2x3.py.
Referenced by ifc2x3.ifcspacethermalloadproperties.thermalloadtype().
userdefinedpropertysource
ifc2x3.ifcspacethermalloadproperties.userdefinedpropertysource
Definition at line 12726 of file ifc2x3.py.
Referenced by ifc2x3.ifcspacethermalloadproperties.userdefinedpropertysource().
userdefinedthermalloadsource
ifc2x3.ifcspacethermalloadproperties.userdefinedthermalloadsource
Definition at line 12725 of file ifc2x3.py.
Referenced by ifc2x3.ifcspacethermalloadproperties.userdefinedthermalloadsource().
The documentation for this class was generated from the following file:
ifc2x3.py