FreeCAD: Gui::Dialog::DlgRevertToBackupConfigImp Class Reference
Gui::Dialog::DlgRevertToBackupConfigImp Class Reference
#include <DlgRevertToBackupConfigImp.h>
Public Slots
void accept () override
void onItemSelectionChanged ()
Public Member Functions
DlgRevertToBackupConfigImp (QWidget *parent=nullptr)
~DlgRevertToBackupConfigImp () override
Protected Member Functions
void changeEvent (QEvent *e) override
void showEvent (QShowEvent *event) override
Detailed Description
The DlgRevertToBackupConfigImp class
Author
Chris Hennes
Definition at line 77 of file DlgRevertToBackupConfigImp.h.
Constructor & Destructor Documentation
DlgRevertToBackupConfigImp()
DlgRevertToBackupConfigImp::DlgRevertToBackupConfigImp (QWidget * parent = nullptr) explicit
Definition at line 41 of file DlgRevertToBackupConfigImp.cpp.
References draftgeoutils.intersections::connect(), and onItemSelectionChanged().
~DlgRevertToBackupConfigImp()
DlgRevertToBackupConfigImp::~DlgRevertToBackupConfigImp () override default
Member Function Documentation
accept
void DlgRevertToBackupConfigImp::accept () override slot
Definition at line 88 of file DlgRevertToBackupConfigImp.cpp.
References Base::Console(), ParameterGrp::copyTo(), ParameterManager::Create(), Base::ConsoleSingleton::Error(), App::GetApplication(), ParameterGrp::GetGroup(), App::Application::GetUserParameter(), src.Mod.Test.testPathArray::items, and src.Mod.Test.testPathArray::path.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
changeEvent()
void DlgRevertToBackupConfigImp::changeEvent (QEvent * e) override protected
Sets the strings of the subwidgets using the current language.
Definition at line 64 of file DlgRevertToBackupConfigImp.cpp.
References SCL.SimpleDataTypes::e.
onItemSelectionChanged
void Gui::Dialog::DlgRevertToBackupConfigImp::onItemSelectionChanged () slot
Definition at line 51 of file DlgRevertToBackupConfigImp.cpp.
References src.Mod.Test.testPathArray::items.
Referenced by DlgRevertToBackupConfigImp().
showEvent()
void DlgRevertToBackupConfigImp::showEvent (QShowEvent * event) override protected
Definition at line 74 of file DlgRevertToBackupConfigImp.cpp.
References Gui::PreferencePackManager::configBackups(), Gui::Application::Instance, Gui::Application::prefPackManager(), and DraftVecUtils::toString().
The documentation for this class was generated from the following files:
DlgRevertToBackupConfigImp.h
DlgRevertToBackupConfigImp.cpp