FreeCAD: TechDraw::GeomFormat Class Reference
TechDraw::GeomFormat Class Reference
#include <Cosmetic.h>
Public Member Functions
GeomFormat ()
GeomFormat (const TechDraw::GeomFormat *gf)
GeomFormat (const int idx, const LineFormat &fmt)
~GeomFormat () override
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
PyObject * getPyObject () override
GeomFormat * copy () const
GeomFormat * clone () const
std::string toString () const
void dump (const char *title) const
boost::uuids::uuid getTag () const
virtual std::string getTagAsString () const
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Attributes
int m_geomIndex
LineFormat m_format
Protected Member Functions
void createNewTag ()
void assignTag (const TechDraw::GeomFormat *gf)
Protected Attributes
boost::uuids::uuid tag
Py::Object PythonObject
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 100 of file Cosmetic.h.
Constructor & Destructor Documentation
GeomFormat() [1/3]
GeomFormat::GeomFormat ()
Definition at line 366 of file Cosmetic.cpp.
References TechDraw::LineFormat::getDefEdgeColor(), TechDraw::LineFormat::getDefEdgeStyle(), TechDraw::LineFormat::getDefEdgeWidth(), and TechDraw::LineFormat::InvalidLine.
Referenced by copy().
GeomFormat() [2/3]
GeomFormat::GeomFormat (const TechDraw::GeomFormat * gf) explicit
Definition at line 378 of file Cosmetic.cpp.
References createNewTag(), TechDraw::LineFormat::getColor(), TechDraw::LineFormat::getLineNumber(), TechDraw::LineFormat::getStyle(), TechDraw::LineFormat::getVisible(), TechDraw::LineFormat::getWidth(), m_format, m_geomIndex, TechDraw::LineFormat::setColor(), TechDraw::LineFormat::setLineNumber(), TechDraw::LineFormat::setStyle(), TechDraw::LineFormat::setVisible(), and TechDraw::LineFormat::setWidth().
GeomFormat() [3/3]
GeomFormat::GeomFormat (const int idx, const LineFormat & fmt)
Definition at line 390 of file Cosmetic.cpp.
References createNewTag(), Path.Post.scripts.comparams_post::fmt(), m_format, TechDraw::LineFormat::setColor(), TechDraw::LineFormat::setLineNumber(), TechDraw::LineFormat::setStyle(), TechDraw::LineFormat::setVisible(), and TechDraw::LineFormat::setWidth().
~GeomFormat()
GeomFormat::~GeomFormat () override
Definition at line 403 of file Cosmetic.cpp.
Member Function Documentation
assignTag()
void GeomFormat::assignTag (const TechDraw::GeomFormat * gf) protected
Definition at line 511 of file Cosmetic.cpp.
References Base::Persistence::getTypeId(), and tag.
clone()
GeomFormat * GeomFormat::clone () const
Definition at line 519 of file Cosmetic.cpp.
References copy(), and tag.
Referenced by TechDraw::PropertyGeomFormatList::setValue().
copy()
GeomFormat * GeomFormat::copy () const
Definition at line 526 of file Cosmetic.cpp.
References GeomFormat(), TechDraw::LineFormat::getColor(), TechDraw::LineFormat::getLineNumber(), TechDraw::LineFormat::getStyle(), TechDraw::LineFormat::getVisible(), TechDraw::LineFormat::getWidth(), m_format, m_geomIndex, TechDraw::LineFormat::setColor(), TechDraw::LineFormat::setLineNumber(), TechDraw::LineFormat::setStyle(), TechDraw::LineFormat::setVisible(), and TechDraw::LineFormat::setWidth().
Referenced by clone().
createNewTag()
void GeomFormat::createNewTag () protected
Definition at line 491 of file Cosmetic.cpp.
References tag.
Referenced by GeomFormat().
dump()
void GeomFormat::dump (const char * title) const
Definition at line 407 of file Cosmetic.cpp.
References Base::Console(), Base::ConsoleSingleton::Message(), Plot::title(), and toString().
getMemSize()
unsigned int GeomFormat::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
Definition at line 422 of file Cosmetic.cpp.
getPyObject()
PyObject * GeomFormat::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 538 of file Cosmetic.cpp.
References Py::new_reference_to(), and PythonObject.
getTag()
boost::uuids::uuid GeomFormat::getTag () const
Definition at line 481 of file Cosmetic.cpp.
References tag.
Referenced by getTagAsString().
getTagAsString()
std::string GeomFormat::getTagAsString () const virtual
Definition at line 486 of file Cosmetic.cpp.
References getTag().
Referenced by TechDraw::CosmeticExtension::addGeomFormat(), and TechDraw::CosmeticExtension::getGeomFormat().
Restore()
void GeomFormat::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 440 of file Cosmetic.cpp.
References App::Color::fromHexString(), TechDraw::LineFormat::InvalidLine, m_format, m_geomIndex, TechDrawTools.TaskFillTemplateFields::reader, TechDraw::CosmeticVertex::restoreCosmetic(), TechDraw::LineFormat::setColor(), TechDraw::LineFormat::setLineNumber(), TechDraw::LineFormat::setStyle(), TechDraw::LineFormat::setVisible(), and TechDraw::LineFormat::setWidth().
Referenced by TechDraw::PropertyGeomFormatList::Restore().
Save()
void GeomFormat::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 427 of file Cosmetic.cpp.
References App::Color::asHexString(), TechDraw::LineFormat::getColor(), TechDraw::LineFormat::getLineNumber(), TechDraw::LineFormat::getStyle(), TechDraw::LineFormat::getVisible(), TechDraw::LineFormat::getWidth(), Base::Writer::ind(), m_format, m_geomIndex, Base::Writer::Stream(), and TestSpreadsheet::v.
toString()
std::string GeomFormat::toString () const
Definition at line 413 of file Cosmetic.cpp.
References m_format, m_geomIndex, and TechDraw::LineFormat::toString().
Referenced by dump().
Member Data Documentation
m_format
LineFormat TechDraw::GeomFormat::m_format
Definition at line 125 of file Cosmetic.h.
Referenced by copy(), TechDrawGui::QGIViewPart::drawAllEdges(), GeomFormat(), TechDrawGui::TaskLineDecor::getFormatAccessPtr(), Restore(), Save(), and toString().
m_geomIndex
int TechDraw::GeomFormat::m_geomIndex
Definition at line 124 of file Cosmetic.h.
Referenced by copy(), GeomFormat(), Restore(), Save(), and toString().
PythonObject
Py::Object TechDraw::GeomFormat::PythonObject protected
Definition at line 136 of file Cosmetic.h.
Referenced by getPyObject().
tag
boost::uuids::uuid TechDraw::GeomFormat::tag protected
Definition at line 135 of file Cosmetic.h.
Referenced by assignTag(), clone(), createNewTag(), Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.ChunkBase::dump_header(), and getTag().
The documentation for this class was generated from the following files:
Cosmetic.h
Cosmetic.cpp