FreeCAD: MatGui::DlgInspectMaterial Class Reference
MatGui::DlgInspectMaterial Class Reference
#include <DlgInspectMaterial.h>
Public Member Functions
DlgInspectMaterial (QWidget *parent=nullptr)
~DlgInspectMaterial () override
bool accept ()
void onClipboard (bool checked)
void OnChange (Gui::SelectionSingleton::SubjectType &rCaller, Gui::SelectionSingleton::MessageType Reason) override
Observer message from the Selection.
Detailed Description
Definition at line 46 of file DlgInspectMaterial.h.
Constructor & Destructor Documentation
DlgInspectMaterial()
DlgInspectMaterial::DlgInspectMaterial (QWidget * parent = nullptr) explicit
Definition at line 49 of file DlgInspectMaterial.cpp.
References Base::Subject< MsgType >::Attach(), draftgeoutils.intersections::connect(), onClipboard(), and Gui::Selection().
~DlgInspectMaterial()
DlgInspectMaterial::~DlgInspectMaterial () override
Definition at line 70 of file DlgInspectMaterial.cpp.
References Base::Subject< MsgType >::Detach(), and Gui::Selection().
Member Function Documentation
accept()
bool DlgInspectMaterial::accept ()
Definition at line 75 of file DlgInspectMaterial.cpp.
Referenced by MatGui::TaskInspectMaterial::accept(), and MaterialEditor.MaterialEditor::verify().
OnChange()
void MatGui::DlgInspectMaterial::OnChange (Gui::SelectionSingleton::SubjectType & rCaller, Gui::SelectionSingleton::MessageType Reason) override
Observer message from the Selection.
onClipboard()
void DlgInspectMaterial::onClipboard (bool checked)
Definition at line 80 of file DlgInspectMaterial.cpp.
Referenced by DlgInspectMaterial().
The documentation for this class was generated from the following files:
DlgInspectMaterial.h
DlgInspectMaterial.cpp