FreeCAD: PartDesignGui::WorkflowManager Class Reference
PartDesignGui::WorkflowManager Class Reference
#include <WorkflowManager.h>
Public Member Functions
virtual ~WorkflowManager ()
Workflow getWorkflowForDocument (App::Document *doc)
Workflow determineWorkflow (App::Document *doc)
void forceWorkflow (const App::Document *doc, Workflow wf)
Init, Destruct an Access methods
static void init ()
Creates an instance of the manager, should be called before any instance()
static WorkflowManager * instance ()
Return an instance of the WorkflofManager.
static void destruct ()
destroy the manager
Detailed Description
This class controls the workflow of each file. It has been introduced to support legacy files migrating to the new workflow.
Definition at line 46 of file WorkflowManager.h.
Constructor & Destructor Documentation
~WorkflowManager()
WorkflowManager::~WorkflowManager () virtual
Definition at line 61 of file WorkflowManager.cpp.
Member Function Documentation
destruct()
void WorkflowManager::destruct () static
destroy the manager
Definition at line 86 of file WorkflowManager.cpp.
References _instance.
Referenced by PartDesignGui::Workbench::~Workbench().
determineWorkflow()
Workflow WorkflowManager::determineWorkflow (App::Document * doc)
Asserts the workflow of the document to be determined and prompt user to migrate if it is not modern.
If workflow was already chosen return it. If the guesed workflow is Workflow::Legacy or Workflow::Mixed the user will be prompted to migrate. If the user agrees the file will be migrated and the workflow will be set as modern. If the user refuses to migrate use the old workflow.
Definition at line 126 of file WorkflowManager.cpp.
References Gui::Application::commandManager(), toolbit-attributes::doc, Gui::getMainWindow(), getWorkflowForDocument(), Gui::Application::Instance, PartDesignGui::Legacy, PartDesignGui::Modern, Gui::CommandManager::runCommandByName(), and PartDesignGui::Undetermined.
Referenced by PartDesignGui::assureLegacyWorkflow(), and PartDesignGui::assureModernWorkflow().
forceWorkflow()
void WorkflowManager::forceWorkflow (const App::Document * doc, Workflow wf)
Force the desired workflow in document
Definition at line 188 of file WorkflowManager.cpp.
References toolbit-attributes::doc.
getWorkflowForDocument()
Workflow WorkflowManager::getWorkflowForDocument (App::Document * doc)
Lookup the workflow of the document in the map. If the document not in the map yet return Workflow::Undetermined.
Definition at line 112 of file WorkflowManager.cpp.
References toolbit-attributes::doc, and PartDesignGui::Undetermined.
Referenced by determineWorkflow(), PartDesignGui::isLegacyWorkflow(), and PartDesignGui::isModernWorkflow().
init()
void WorkflowManager::init () static
Creates an instance of the manager, should be called before any instance()
Definition at line 71 of file WorkflowManager.cpp.
References _instance.
Referenced by PartDesignGui::Workbench::activated(), instance(), and DocumentObject.DocumentObject::onChanged().
instance()
WorkflowManager * WorkflowManager::instance () static
Return an instance of the WorkflofManager.
Definition at line 79 of file WorkflowManager.cpp.
References _instance, and init().
Referenced by PartDesignGui::assureLegacyWorkflow(), PartDesignGui::assureModernWorkflow(), PartDesignGui::isLegacyWorkflow(), and PartDesignGui::isModernWorkflow().
The documentation for this class was generated from the following files:
WorkflowManager.h
WorkflowManager.cpp