FreeCAD: Base::PyStreambuf Class Reference
Base::PyStreambuf Class Reference
#include <Stream.h>
Public Types
enum Type { StringIO, BytesIO, Unknown }
Public Member Functions
PyStreambuf (PyObject *o, std::size_t buf_size=256, std::size_t put_back=8)
~PyStreambuf () override
void setType (Type t)
PyStreambuf (const PyStreambuf &)=delete
PyStreambuf (PyStreambuf &&)=delete
PyStreambuf & operator= (const PyStreambuf &)=delete
PyStreambuf & operator= (PyStreambuf &&)=delete
Protected Member Functions
int_type underflow () override
int_type overflow (int_type c=EOF) override
std::streamsize xsputn (const char *s, std::streamsize num) override
int sync () override
pos_type seekoff (off_type offset, seekdir dir, openmode mode) override
pos_type seekpos (pos_type offset, openmode mode) override
Detailed Description
Definition at line 485 of file Stream.h.
Member Enumeration Documentation
Type
enum Base::PyStreambuf::Type
Enumerator
StringIO
BytesIO
Unknown
Definition at line 494 of file Stream.h.
Constructor & Destructor Documentation
PyStreambuf() [1/3]
PyStreambuf::PyStreambuf (PyObject * o, std::size_t buf_size = 256, std::size_t put_back = 8) explicit
Definition at line 558 of file Stream.cpp.
~PyStreambuf()
PyStreambuf::~PyStreambuf () override
Definition at line 572 of file Stream.cpp.
References sync().
PyStreambuf() [2/3]
Base::PyStreambuf::PyStreambuf (const PyStreambuf &) delete
PyStreambuf() [3/3]
Base::PyStreambuf::PyStreambuf (PyStreambuf &&) delete
Member Function Documentation
operator=() [1/2]
PyStreambuf& Base::PyStreambuf::operator= (const PyStreambuf &) delete
operator=() [2/2]
PyStreambuf& Base::PyStreambuf::operator= (PyStreambuf &&) delete
overflow()
PyStreambuf::int_type PyStreambuf::overflow (PyStreambuf::int_type ch = EOF) override protected
Definition at line 629 of file Stream.cpp.
References sync().
seekoff()
PyStreambuf::pos_type PyStreambuf::seekoff (PyStreambuf::off_type offset, PyStreambuf::seekdir dir, PyStreambuf::openmode mode) override protected
Definition at line 726 of file Stream.cpp.
References SCL.SimpleDataTypes::e, importers.importIFClegacy::getAttr(), and RobotExample::pos.
Referenced by seekpos().
seekpos()
PyStreambuf::pos_type PyStreambuf::seekpos (PyStreambuf::pos_type offset, PyStreambuf::openmode mode) override protected
Definition at line 765 of file Stream.cpp.
References seekoff().
setType()
void Base::PyStreambuf::setType (Type t) inline
Definition at line 503 of file Stream.h.
References InitGui::t, and Path.Post.scripts.grbl_post::type.
sync()
int PyStreambuf::sync () override protected
Definition at line 652 of file Stream.cpp.
Referenced by overflow(), and ~PyStreambuf().
underflow()
PyStreambuf::int_type PyStreambuf::underflow () override protected
Definition at line 578 of file Stream.cpp.
References importers.importWebGL::base, SCL.SimpleDataTypes::c, SCL.SimpleDataTypes::e, importers.importIFClegacy::getAttr(), and src.Mod.Test.testmakeWireString::String.
xsputn()
std::streamsize PyStreambuf::xsputn (const char * s, std::streamsize num) override protected
Definition at line 714 of file Stream.cpp.
References toolbit-attributes::s.
The documentation for this class was generated from the following files:
Stream.h
Stream.cpp