FreeCAD: MeshCore::ZipFixer Class Reference
MeshCore::ZipFixer Class Reference
Public Member Functions
ZipFixer (const char *filename)
~ZipFixer ()
Base::ifstream & getStream ()
Detailed Description
Definition at line 118 of file MeshIO.cpp.
Constructor & Destructor Documentation
ZipFixer()
MeshCore::ZipFixer::ZipFixer (const char * filename) inline
Definition at line 121 of file MeshIO.cpp.
References Base::FileInfo::getTempFileName().
~ZipFixer()
MeshCore::ZipFixer::~ZipFixer () inline
Definition at line 128 of file MeshIO.cpp.
References Base::FileInfo::deleteFile().
Member Function Documentation
getStream()
Base::ifstream& MeshCore::ZipFixer::getStream () inline
Definition at line 133 of file MeshIO.cpp.
Referenced by MeshCore::MeshInput::LoadAny().
The documentation for this class was generated from the following file:
MeshIO.cpp