FreeCAD: Gui::Dialog::ButtonModel Class Reference
Gui::Dialog::ButtonModel Class Reference
#include <DlgCustomizeSpaceball.h>
Public Member Functions
ButtonModel (QObject *parent)
int rowCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
void insertButtonRows (int number)
void setCommand (int row, QString command)
void goButtonPress (int number)
void goMacroRemoved (const QByteArray &macroName)
void goClear ()
void loadConfig (const char *RequiredDeviceName)
Detailed Description
Definition at line 56 of file DlgCustomizeSpaceball.h.
Constructor & Destructor Documentation
ButtonModel()
ButtonModel::ButtonModel (QObject * parent) explicit
Definition at line 83 of file DlgCustomizeSpaceball.cpp.
Member Function Documentation
data()
QVariant ButtonModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 199 of file DlgCustomizeSpaceball.cpp.
References Gui::BitmapFactory(), Base::Console(), ParameterGrp::GetGroups(), and Base::ConsoleSingleton::Log().
Referenced by Gui::Dialog::PrintModel::data().
goButtonPress()
void ButtonModel::goButtonPress (int number)
Definition at line 244 of file DlgCustomizeSpaceball.cpp.
References insertButtonRows().
Referenced by Gui::Dialog::DlgCustomizeSpaceball::event().
goClear()
void ButtonModel::goClear ()
Definition at line 260 of file DlgCustomizeSpaceball.cpp.
References ParameterGrp::Clear(), and rowCount().
Referenced by loadConfig().
goMacroRemoved()
void ButtonModel::goMacroRemoved (const QByteArray & macroName)
Definition at line 252 of file DlgCustomizeSpaceball.cpp.
References ParameterGrp::GetGroups().
Referenced by Gui::Dialog::DlgCustomizeSpaceball::onRemoveMacroAction().
insertButtonRows()
void ButtonModel::insertButtonRows (int number)
Definition at line 222 of file DlgCustomizeSpaceball.cpp.
References ParameterGrp::GetGroup(), ParameterGrp::GetGroups(), and ParameterGrp::SetASCII().
Referenced by goButtonPress().
loadConfig()
void ButtonModel::loadConfig (const char * RequiredDeviceName)
Definition at line 291 of file DlgCustomizeSpaceball.cpp.
References goClear().
rowCount()
int ButtonModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 193 of file DlgCustomizeSpaceball.cpp.
References ParameterGrp::GetGroups(), and Init::parent.
Referenced by src.Mod.AddonManager.package_list.PackageListItemModel::append_item(), src.Mod.AddonManager.AddonManagerOptions.CustomRepoDataModel::appendData(), src.Mod.AddonManager.package_list.PackageListItemModel::clear(), goClear(), and Gui::Dialog::PrintModel::rowCount().
setCommand()
void ButtonModel::setCommand (int row, QString command)
Definition at line 238 of file DlgCustomizeSpaceball.cpp.
References ParameterGrp::GetGroups().
Referenced by Gui::Dialog::ButtonView::goChangedCommand().
The documentation for this class was generated from the following files:
DlgCustomizeSpaceball.h
DlgCustomizeSpaceball.cpp