FreeCAD: MeshFlatteningBoostPython.cpp File Reference
MeshFlatteningBoostPython.cpp File Reference
#include "PreCompiled.h"
#include <TopoDS.hxx>
#include <TopoDS_Edge.hxx>
#include <TopoDS_Face.hxx>
#include <map>
#include <memory>
#include <stdexcept>
#include <vector>
#include <Base/Interpreter.h>
#include <Eigen/Core>
#include <Eigen/Geometry>
#include <Eigen/Sparse>
#include <Mod/Part/App/TopoShapeEdgePy.h>
#include <Mod/Part/App/TopoShapeFacePy.h>
#include <boost/python.hpp>
#include <boost/python/call.hpp>
#include <boost/python/class.hpp>
#include <boost/python/copy_const_reference.hpp>
#include <boost/python/module.hpp>
#include <boost/python/return_value_policy.hpp>
#include <boost/python/wrapper.hpp>
#include "MeshFlattening.h"
#include "MeshFlatteningLscmRelax.h"
#include "MeshFlatteningNurbs.h"
Classes
struct fm::eigen_matrix< eigen_type >
Namespaces
fm
Functions
const TopoDS_Face & getTopoDSFace (const py::object &face)
const TopoDS_Edge & getTopoDSEdge (py::object *edge)
Py::Object makeEdge (const TopoDS_Edge &edge)
std::shared_ptr< FaceUnwrapper > FaceUnwrapper_face (const py::object &face)
std::shared_ptr< FaceUnwrapper > FaceUnwrapper_mesh (const py::object &points, const py::object &facets)
boost::python::list interpolateFlatFacePy (FaceUnwrapper &instance, const py::object &face)
boost::python::list getFlatBoundaryNodesPy (FaceUnwrapper &instance)
BOOST_PYTHON_MODULE (flatmesh)
Function Documentation
BOOST_PYTHON_MODULE()
BOOST_PYTHON_MODULE (flatmesh)
Definition at line 197 of file MeshFlatteningBoostPython.cpp.
References FaceUnwrapper::A, nurbs::NurbsBase2D::computeFirstDerivatives(), nurbs::NurbsBase1D::computeFirstDerivatives(), nurbs::NurbsBase2D::degree_u, nurbs::NurbsBase1D::degree_u, FaceUnwrapper_face(), FaceUnwrapper_mesh(), FaceUnwrapper::findFlatNodes(), lscmrelax::LscmRelax::get_area(), lscmrelax::LscmRelax::get_flat_area(), lscmrelax::LscmRelax::get_flat_vertices_3D(), nurbs::NurbsBase2D::getDuMatrix(), nurbs::NurbsBase1D::getDuMatrix(), nurbs::NurbsBase2D::getDuVector(), nurbs::NurbsBase1D::getDuVector(), nurbs::NurbsBase2D::getDvMatrix(), nurbs::NurbsBase2D::getDvVector(), getFlatBoundaryNodesPy(), nurbs::NurbsBase2D::getInfluenceMatrix(), nurbs::NurbsBase1D::getInfluenceMatrix(), nurbs::NurbsBase2D::getInfluenceVector(), nurbs::NurbsBase1D::getInfluenceVector(), nurbs::NurbsBase1D::getKnotSequence(), nurbs::NurbsBase1D::getUMesh(), nurbs::NurbsBase2D::getUVMesh(), nurbs::NurbsBase1D::getWeightList(), SIM::Coin3D::Quarter::Quarter::init(), interpolateFlatFacePy(), nurbs::NurbsBase2D::interpolateUBS(), lscmrelax::LscmRelax::lscm(), lscmrelax::LscmRelax::MATRIX, lscmrelax::LscmRelax::relax(), lscmrelax::LscmRelax::rhs, lscmrelax::LscmRelax::rotate_by_min_bound_area(), fm::eigen_matrix< eigen_type >::to_python_converter(), lscmrelax::LscmRelax::transform(), FaceUnwrapper::tris, nurbs::NurbsBase2D::u_knots, nurbs::NurbsBase1D::u_knots, FaceUnwrapper::uv_nodes, nurbs::NurbsBase2D::weights, nurbs::NurbsBase1D::weights, FaceUnwrapper::xyz_nodes, FaceUnwrapper::ze_nodes, and FaceUnwrapper::ze_poles.
FaceUnwrapper_face()
std::shared_ptr<FaceUnwrapper> FaceUnwrapper_face (const py::object & face)
Definition at line 87 of file MeshFlatteningBoostPython.cpp.
References getTopoDSFace().
Referenced by BOOST_PYTHON_MODULE().
FaceUnwrapper_mesh()
std::shared_ptr<FaceUnwrapper> FaceUnwrapper_mesh (const py::object & points, const py::object & facets)
Definition at line 93 of file MeshFlatteningBoostPython.cpp.
References SCL.SimpleDataTypes::c, SCL.SimpleDataTypes::e, src.Mod.PartDesign.Scripts.Gear::l1, src.Mod.PartDesign.Scripts.Gear::l2, and TestSpreadsheet::v.
Referenced by BOOST_PYTHON_MODULE().
getFlatBoundaryNodesPy()
boost::python::list getFlatBoundaryNodesPy (FaceUnwrapper & instance)
Definition at line 149 of file MeshFlatteningBoostPython.cpp.
References SCL.SimpleDataTypes::c, FaceUnwrapper::getFlatBoundaryNodes(), SplineSurface::i, and SurfaceTests.TestBlendCurve::vec.
Referenced by BOOST_PYTHON_MODULE().
getTopoDSEdge()
const TopoDS_Edge& getTopoDSEdge (py::object * edge)
Definition at line 70 of file MeshFlatteningBoostPython.cpp.
getTopoDSFace()
const TopoDS_Face& getTopoDSFace (const py::object & face)
Definition at line 58 of file MeshFlatteningBoostPython.cpp.
Referenced by FaceUnwrapper_face(), and interpolateFlatFacePy().
interpolateFlatFacePy()
boost::python::list interpolateFlatFacePy (FaceUnwrapper & instance, const py::object & face)
Definition at line 131 of file MeshFlatteningBoostPython.cpp.
References SCL.SimpleDataTypes::c, getTopoDSFace(), SplineSurface::i, FaceUnwrapper::interpolateFlatFace(), and SurfaceTests.TestBlendCurve::vec.
Referenced by BOOST_PYTHON_MODULE().
makeEdge()
Py::Object makeEdge (const TopoDS_Edge & edge)
Definition at line 82 of file MeshFlatteningBoostPython.cpp.