FreeCAD: GCS::Curve Class Reference
GCS::Curve Class Reference abstract
A base class for all curve-based objects (line, circle/arc, ellipse/arc).
#include <Geo.h>
Public Member Functions
virtual ~Curve ()
virtual DeriVector2 CalculateNormal (const Point &p, const double *derivparam=nullptr) const =0
virtual DeriVector2 CalculateNormal (const double *param, const double *derivparam=nullptr) const
virtual DeriVector2 Value (double u, double du, const double *derivparam=nullptr) const
Value: returns point (vector) given the value of parameter.
virtual int PushOwnParams (VEC_pD &pvec)=0
virtual void ReconstructOnNewPvec (VEC_pD &pvec, int &cnt)=0
virtual Curve * Copy ()=0
Detailed Description
A base class for all curve-based objects (line, circle/arc, ellipse/arc).
Definition at line 175 of file Geo.h.
Constructor & Destructor Documentation
~Curve()
virtual GCS::Curve::~Curve () inline virtual
Definition at line 178 of file Geo.h.
Member Function Documentation
CalculateNormal() [1/2]
virtual DeriVector2 GCS::Curve::CalculateNormal (const double * param, const double * derivparam = nullptr) const inline virtual
Reimplemented in GCS::BSpline.
Definition at line 191 of file Geo.h.
CalculateNormal() [2/2]
virtual DeriVector2 GCS::Curve::CalculateNormal (const Point & p, const double * derivparam = nullptr) const pure virtual
Implemented in GCS::BSpline, GCS::Parabola, GCS::Hyperbola, GCS::Ellipse, GCS::Circle, and GCS::Line.
Referenced by GCS::System::calculateAngleViaParams(), GCS::System::calculateAngleViaPoint(), GCS::System::calculateNormalAtPoint(), GCS::ConstraintAngleViaPoint::error(), GCS::ConstraintAngleViaTwoPoints::error(), GCS::ConstraintAngleViaPointAndParam::error(), GCS::ConstraintAngleViaPointAndTwoParams::error(), GCS::ConstraintAngleViaPoint::grad(), GCS::ConstraintAngleViaTwoPoints::grad(), GCS::ConstraintAngleViaPointAndParam::grad(), and GCS::ConstraintAngleViaPointAndTwoParams::grad().
Copy()
virtual Curve* GCS::Curve::Copy () pure virtual
Implemented in GCS::BSpline, GCS::ArcOfParabola, GCS::Parabola, GCS::ArcOfHyperbola, GCS::Hyperbola, GCS::ArcOfEllipse, GCS::Ellipse, GCS::Arc, GCS::Circle, and GCS::Line.
Referenced by GCS::ConstraintAngleViaPoint::ConstraintAngleViaPoint(), GCS::ConstraintAngleViaPointAndParam::ConstraintAngleViaPointAndParam(), GCS::ConstraintAngleViaPointAndTwoParams::ConstraintAngleViaPointAndTwoParams(), GCS::ConstraintAngleViaTwoPoints::ConstraintAngleViaTwoPoints(), GCS::ConstraintCurveValue::ConstraintCurveValue(), and GCS::ConstraintSnell::ConstraintSnell().
PushOwnParams()
virtual int GCS::Curve::PushOwnParams (VEC_pD & pvec) pure virtual
Implemented in GCS::BSpline, GCS::ArcOfParabola, GCS::Parabola, GCS::ArcOfHyperbola, GCS::Hyperbola, GCS::ArcOfEllipse, GCS::Ellipse, GCS::Arc, GCS::Circle, and GCS::Line.
Referenced by GCS::ConstraintAngleViaPoint::ConstraintAngleViaPoint(), GCS::ConstraintAngleViaPointAndParam::ConstraintAngleViaPointAndParam(), GCS::ConstraintAngleViaPointAndTwoParams::ConstraintAngleViaPointAndTwoParams(), GCS::ConstraintAngleViaTwoPoints::ConstraintAngleViaTwoPoints(), GCS::ConstraintCurveValue::ConstraintCurveValue(), GCS::ConstraintEqualMajorAxesConic::ConstraintEqualMajorAxesConic(), and GCS::ConstraintSnell::ConstraintSnell().
ReconstructOnNewPvec()
virtual void GCS::Curve::ReconstructOnNewPvec (VEC_pD & pvec, int & cnt) pure virtual
Implemented in GCS::BSpline, GCS::ArcOfParabola, GCS::Parabola, GCS::ArcOfHyperbola, GCS::Hyperbola, GCS::ArcOfEllipse, GCS::Ellipse, GCS::Arc, GCS::Circle, and GCS::Line.
Value()
DeriVector2 GCS::Curve::Value (double u, double du, const double * derivparam = nullptr) const virtual
Value: returns point (vector) given the value of parameter.
Parameters
u value of parameter
du derivative of parameter by derivparam
derivparam pointer to sketch parameter to calculate the derivative for
Returns
Reimplemented in GCS::BSpline, GCS::Parabola, GCS::Hyperbola, GCS::Ellipse, GCS::Circle, and GCS::Line.
Definition at line 125 of file Geo.cpp.
The documentation for this class was generated from the following files:
Geo.h
Geo.cpp