FreeCAD: Inspection::InspectNominalMesh Class Reference
Inspection::InspectNominalMesh Class Reference
#include <InspectionFeature.h>
Public Member Functions
InspectNominalMesh (const Mesh::MeshObject &rMesh, float offset)
~InspectNominalMesh () override
float getDistance (const Base::Vector3f &) const override
Public Member Functions inherited from Inspection::InspectNominalGeometry
InspectNominalGeometry ()=default
virtual ~InspectNominalGeometry ()=default
Detailed Description
Definition at line 119 of file InspectionFeature.h.
Constructor & Destructor Documentation
InspectNominalMesh()
InspectNominalMesh::InspectNominalMesh (const Mesh::MeshObject & rMesh, float offset)
Definition at line 283 of file InspectionFeature.cpp.
References MengerSponge::box, Base::BoundBox3< Precision >::Enlarge(), MeshCore::MeshAlgorithm::GetAverageEdgeLength(), MeshCore::MeshKernel::GetBoundBox(), Mesh::MeshObject::getTransform(), Base::pow(), and Base::BoundBox3< Precision >::Transformed().
~InspectNominalMesh()
InspectNominalMesh::~InspectNominalMesh () override
Definition at line 311 of file InspectionFeature.cpp.
Member Function Documentation
getDistance()
float InspectNominalMesh::getDistance (const Base::Vector3f & point) const override virtual
Implements Inspection::InspectNominalGeometry.
Definition at line 316 of file InspectionFeature.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::MeshGeomFacet::DistanceToPoint(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshGeomFacet::GetNormal(), Base::BoundBox3< Precision >::IsInBox(), and MeshCore::MeshGeomFacet::Transform().
The documentation for this class was generated from the following files:
InspectionFeature.h
InspectionFeature.cpp