FreeCAD: Gui::Dialog::DlgSettingsImageImp Class Reference
Gui::Dialog::DlgSettingsImageImp Class Reference
#include <DlgSettingsImageImp.h>
Public Member Functions
DlgSettingsImageImp (QWidget *parent=nullptr)
~DlgSettingsImageImp () override
Image dimensions
void setImageSize (int, int)
void setImageSize (const QSize &)
QSize imageSize () const
int imageWidth () const
int imageHeight () const
Image meta information
void setMethod (const QByteArray &)
QByteArray method () const
QString comment () const
int backgroundType () const
void setBackgroundType (int)
bool addWatermark () const
void onSelectedFilter (const QString &)
void setupConnections ()
void onButtonRatioScreenClicked ()
void onButtonRatio4x3Clicked ()
void onButtonRatio16x9Clicked ()
void onButtonRatio1x1Clicked ()
void onStandardSizeBoxActivated (int)
void onComboMethodActivated (int)
void adjustImageSize (float fRatio)
void changeEvent (QEvent *e) override
Detailed Description
The DlgSettingsImageImp class implements a preference page to change settings for the Inventor viewer.
Author
Werner Mayer
Definition at line 81 of file DlgSettingsImageImp.h.
Constructor & Destructor Documentation
DlgSettingsImageImp()
DlgSettingsImageImp::DlgSettingsImageImp (QWidget * parent = nullptr) explicit
Constructs a DlgSettingsImageImp as a child of 'parent', with the name 'name' and widget flags set to 'f'.
Definition at line 42 of file DlgSettingsImageImp.cpp.
References setupConnections().
~DlgSettingsImageImp()
DlgSettingsImageImp::~DlgSettingsImageImp () override default
Destroys the object and frees any allocated resources
Member Function Documentation
addWatermark()
bool DlgSettingsImageImp::addWatermark () const
Definition at line 181 of file DlgSettingsImageImp.cpp.
adjustImageSize()
void DlgSettingsImageImp::adjustImageSize (float fRatio) protected
Definition at line 193 of file DlgSettingsImageImp.cpp.
Referenced by onButtonRatio16x9Clicked(), onButtonRatio1x1Clicked(), onButtonRatio4x3Clicked(), and onButtonRatioScreenClicked().
backgroundType()
int DlgSettingsImageImp::backgroundType () const
Definition at line 166 of file DlgSettingsImageImp.cpp.
changeEvent()
void DlgSettingsImageImp::changeEvent (QEvent * e) override protected
Definition at line 86 of file DlgSettingsImageImp.cpp.
References SCL.SimpleDataTypes::e.
comment()
QString DlgSettingsImageImp::comment () const
Returns the comment of the picture. If for the currently selected image format no comments are supported QString() is returned.
Definition at line 156 of file DlgSettingsImageImp.cpp.
imageHeight()
int DlgSettingsImageImp::imageHeight () const
Returns the currently set image height.
Definition at line 147 of file DlgSettingsImageImp.cpp.
imageSize()
QSize DlgSettingsImageImp::imageSize () const
Returns the currently set image size.
Definition at line 131 of file DlgSettingsImageImp.cpp.
imageWidth()
int DlgSettingsImageImp::imageWidth () const
Returns the currently set image width.
Definition at line 139 of file DlgSettingsImageImp.cpp.
method()
QByteArray DlgSettingsImageImp::method () const
Definition at line 267 of file DlgSettingsImageImp.cpp.
onButtonRatio16x9Clicked()
void DlgSettingsImageImp::onButtonRatio16x9Clicked () protected
Definition at line 219 of file DlgSettingsImageImp.cpp.
References adjustImageSize(), and SCL.SimpleDataTypes::f.
Referenced by setupConnections().
onButtonRatio1x1Clicked()
void DlgSettingsImageImp::onButtonRatio1x1Clicked () protected
Definition at line 224 of file DlgSettingsImageImp.cpp.
References adjustImageSize(), and SCL.SimpleDataTypes::f.
Referenced by setupConnections().
onButtonRatio4x3Clicked()
void DlgSettingsImageImp::onButtonRatio4x3Clicked () protected
Definition at line 214 of file DlgSettingsImageImp.cpp.
References adjustImageSize(), and SCL.SimpleDataTypes::f.
Referenced by setupConnections().
onButtonRatioScreenClicked()
void DlgSettingsImageImp::onButtonRatioScreenClicked () protected
Definition at line 209 of file DlgSettingsImageImp.cpp.
References adjustImageSize().
Referenced by setupConnections().
onComboMethodActivated()
void DlgSettingsImageImp::onComboMethodActivated (int index) protected
Definition at line 272 of file DlgSettingsImageImp.cpp.
Referenced by setupConnections().
onSelectedFilter
void DlgSettingsImageImp::onSelectedFilter (const QString & filter) slot
Definition at line 186 of file DlgSettingsImageImp.cpp.
onStandardSizeBoxActivated()
void DlgSettingsImageImp::onStandardSizeBoxActivated (int index) protected
Definition at line 229 of file DlgSettingsImageImp.cpp.
References RobotExample::pos, src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression, and toolbit-attributes::s.
Referenced by setupConnections().
setBackgroundType()
void DlgSettingsImageImp::setBackgroundType (int t)
Sets the image size to (w, h).
Definition at line 174 of file DlgSettingsImageImp.cpp.
References InitGui::t.
setImageSize() [1/2]
void DlgSettingsImageImp::setImageSize (const QSize & s)
Sets the image size to s.
Definition at line 114 of file DlgSettingsImageImp.cpp.
References toolbit-attributes::s.
setImageSize() [2/2]
void DlgSettingsImageImp::setImageSize (int w, int h)
Sets the image size to (w, h).
Definition at line 97 of file DlgSettingsImageImp.cpp.
References src.Mod.PartDesign.fcgear.svggear::w.
setMethod()
void DlgSettingsImageImp::setMethod (const QByteArray & m)
Definition at line 259 of file DlgSettingsImageImp.cpp.
References test::m.
setupConnections()
void DlgSettingsImageImp::setupConnections () protected
Definition at line 68 of file DlgSettingsImageImp.cpp.
References draftgeoutils.intersections::connect(), onButtonRatio16x9Clicked(), onButtonRatio1x1Clicked(), onButtonRatio4x3Clicked(), onButtonRatioScreenClicked(), onComboMethodActivated(), and onStandardSizeBoxActivated().
Referenced by DlgSettingsImageImp().
The documentation for this class was generated from the following files:
DlgSettingsImageImp.h
DlgSettingsImageImp.cpp