FreeCAD: Path.Post.scripts.fangling_post Namespace Reference
Path.Post.scripts.fangling_post Namespace Reference
Functions
def processArguments (argstring)
def export (objectslist, filename, argstring)
def linenumber ()
def parse (pathobj)
def writeFile (filename, final)
Variables
TOOLTIP
now
parser
prog
add_help
action
help = 'set commands to be issued after the last command, default="M5\nG17 G90\nM2"',
default
TOOLTIP_ARGS
OUTPUT_COMMENTS
OUTPUT_HEADER
OUTPUT_LINE_NUMBERS
SHOW_EDITOR
MODAL
USE_TLO
OUTPUT_DOUBLES
COMMAND_SPACE
LINENR
UNITS
UNIT_SPEED_FORMAT
UNIT_FORMAT
MACHINE_NAME
CORNER_MIN
CORNER_MAX
PRECISION
PREAMBLE
POSTAMBLE
PRE_OPERATION
POST_OPERATION
TOOL_CHANGE
Function Documentation
export()
def Path.Post.scripts.fangling_post.export (objectslist, filename, argstring)
Definition at line 181 of file fangling_post.py.
References Path.Post.scripts.fangling_post.linenumber(), Path.Post.scripts.fangling_post.parse(), Path.Post.scripts.fangling_post.processArguments(), Path.Post.scripts.refactored_centroid_post.str, and Path.Post.scripts.fangling_post.writeFile().
linenumber()
def Path.Post.scripts.fangling_post.linenumber ()
Definition at line 274 of file fangling_post.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.fangling_post.export(), and Path.Post.scripts.fangling_post.parse().
parse()
def Path.Post.scripts.fangling_post.parse (pathobj)
Definition at line 283 of file fangling_post.py.
References Path.Post.scripts.fangling_post.linenumber(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.fangling_post.export().
processArguments()
def Path.Post.scripts.fangling_post.processArguments (argstring)
Definition at line 130 of file fangling_post.py.
Referenced by Path.Post.scripts.fangling_post.export().
writeFile()
def Path.Post.scripts.fangling_post.writeFile (filename, final)
Definition at line 479 of file fangling_post.py.
Referenced by Path.Post.scripts.fangling_post.export().
Variable Documentation
action
Path.Post.scripts.fangling_post.action
Definition at line 60 of file fangling_post.py.
add_help
Path.Post.scripts.fangling_post.add_help
Definition at line 59 of file fangling_post.py.
COMMAND_SPACE
Path.Post.scripts.fangling_post.COMMAND_SPACE
Definition at line 95 of file fangling_post.py.
CORNER_MAX
Path.Post.scripts.fangling_post.CORNER_MAX
Definition at line 105 of file fangling_post.py.
CORNER_MIN
Path.Post.scripts.fangling_post.CORNER_MIN
Definition at line 104 of file fangling_post.py.
default
Path.Post.scripts.fangling_post.default
Definition at line 66 of file fangling_post.py.
help
string Path.Post.scripts.fangling_post.help = 'set commands to be issued after the last command, default="M5\nG17 G90\nM2"',
Definition at line 60 of file fangling_post.py.
LINENR
Path.Post.scripts.fangling_post.LINENR
Definition at line 96 of file fangling_post.py.
MACHINE_NAME
Path.Post.scripts.fangling_post.MACHINE_NAME
Definition at line 103 of file fangling_post.py.
MODAL
Path.Post.scripts.fangling_post.MODAL
Definition at line 92 of file fangling_post.py.
now
Path.Post.scripts.fangling_post.now
Definition at line 57 of file fangling_post.py.
OUTPUT_COMMENTS
Path.Post.scripts.fangling_post.OUTPUT_COMMENTS
Definition at line 88 of file fangling_post.py.
OUTPUT_DOUBLES
Path.Post.scripts.fangling_post.OUTPUT_DOUBLES
Definition at line 94 of file fangling_post.py.
OUTPUT_HEADER
Path.Post.scripts.fangling_post.OUTPUT_HEADER
Definition at line 89 of file fangling_post.py.
OUTPUT_LINE_NUMBERS
Path.Post.scripts.fangling_post.OUTPUT_LINE_NUMBERS
Definition at line 90 of file fangling_post.py.
parser
Path.Post.scripts.fangling_post.parser
Definition at line 59 of file fangling_post.py.
POST_OPERATION
Path.Post.scripts.fangling_post.POST_OPERATION
Definition at line 124 of file fangling_post.py.
POSTAMBLE
Path.Post.scripts.fangling_post.POSTAMBLE
Definition at line 115 of file fangling_post.py.
PRE_OPERATION
Path.Post.scripts.fangling_post.PRE_OPERATION
Definition at line 121 of file fangling_post.py.
PREAMBLE
Path.Post.scripts.fangling_post.PREAMBLE
Definition at line 111 of file fangling_post.py.
PRECISION
Path.Post.scripts.fangling_post.PRECISION
Definition at line 106 of file fangling_post.py.
prog
Path.Post.scripts.fangling_post.prog
Definition at line 59 of file fangling_post.py.
SHOW_EDITOR
Path.Post.scripts.fangling_post.SHOW_EDITOR
Definition at line 91 of file fangling_post.py.
TOOL_CHANGE
Path.Post.scripts.fangling_post.TOOL_CHANGE
Definition at line 127 of file fangling_post.py.
TOOLTIP
Path.Post.scripts.fangling_post.TOOLTIP
Definition at line 45 of file fangling_post.py.
TOOLTIP_ARGS
Path.Post.scripts.fangling_post.TOOLTIP_ARGS
Definition at line 85 of file fangling_post.py.
UNIT_FORMAT
Path.Post.scripts.fangling_post.UNIT_FORMAT
Definition at line 101 of file fangling_post.py.
UNIT_SPEED_FORMAT
Path.Post.scripts.fangling_post.UNIT_SPEED_FORMAT
Definition at line 100 of file fangling_post.py.
UNITS
Path.Post.scripts.fangling_post.UNITS
Definition at line 99 of file fangling_post.py.
USE_TLO
Path.Post.scripts.fangling_post.USE_TLO
Definition at line 93 of file fangling_post.py.