FreeCAD: Gui::Dialog::ParameterUInt Class Reference
Gui::Dialog::ParameterUInt Class Reference
#include <DlgParameterImp.h>
Public Member Functions
ParameterUInt (QTreeWidget *parent, QString label1, unsigned long value, const Base::Reference< ParameterGrp > &hcGrp)
Constructor.
~ParameterUInt () override
void changeValue () override
void appendToGroup () override
void removeFromGroup () override
Public Member Functions inherited from Gui::Dialog::ParameterValueItem
ParameterValueItem (QTreeWidget *parent, const Base::Reference< ParameterGrp > &hcGrp)
Constructor.
~ParameterValueItem () override
void setData (int column, int role, const QVariant &value) override
Protected Member Functions
void replace (const QString &oldName, const QString &newName) override
Additional Inherited Members
Protected Attributes inherited from Gui::Dialog::ParameterValueItem
Base::Reference< ParameterGrp > _hcGrp
Detailed Description
The ParameterUInt class allows interaction with "unsigned integer" parameter leaves.
Author
Werner Mayer
Definition at line 343 of file DlgParameterImp.h.
Constructor & Destructor Documentation
ParameterUInt()
ParameterUInt::ParameterUInt (QTreeWidget * parent, QString label1, unsigned long value, const Base::Reference< ParameterGrp > & hcGrp)
Constructor.
Definition at line 1233 of file DlgParameterImp.cpp.
References Gui::BitmapFactory().
~ParameterUInt()
ParameterUInt::~ParameterUInt () override default
Member Function Documentation
appendToGroup()
void ParameterUInt::appendToGroup () override virtual
Append this item as leaf to the parameter group.
Implements Gui::Dialog::ParameterValueItem.
Definition at line 1281 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::_hcGrp, and ParameterGrp::SetUnsigned().
changeValue()
void ParameterUInt::changeValue () override virtual
Opens an input dialog to change the value.
Implements Gui::Dialog::ParameterValueItem.
Definition at line 1247 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::_hcGrp, Gui::Dialog::DlgInputDialogImp::getUIntBox(), Gui::UIntSpinBox::setRange(), ParameterGrp::SetUnsigned(), Gui::UIntSpinBox::setValue(), and Gui::Dialog::DlgInputDialogImp::UIntBox.
removeFromGroup()
void ParameterUInt::removeFromGroup () override virtual
Remove the leaf from the parameter group.
Implements Gui::Dialog::ParameterValueItem.
Definition at line 1269 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::_hcGrp, and ParameterGrp::RemoveUnsigned().
replace()
void ParameterUInt::replace (const QString & oldName, const QString & newName) override protected virtual
Replaces the name of the leaf from oldName to newName.
Implements Gui::Dialog::ParameterValueItem.
Definition at line 1274 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::_hcGrp, ParameterGrp::GetUnsigned(), ParameterGrp::RemoveUnsigned(), ParameterGrp::SetUnsigned(), and toolbit-attributes::val.
The documentation for this class was generated from the following files:
DlgParameterImp.h
DlgParameterImp.cpp