FreeCAD: Help Namespace Reference
Help Namespace Reference
Functions
def show (page, view=None, conv=None)
def underscore_page (page)
def get_uri (location)
tuple location_url (str url_localized, str url_english)
tuple get_location (page)
def show_browser (url)
def show_dialog (html, baseurl, title, view=None)
def show_tab (html, baseurl, title, view=None)
def get_qtwebwidgets ()
def get_contents (location)
def convert (content, force=None)
def add_preferences_page ()
def add_language_path ()
def openBrowserHTML (html, baseurl, title, icon, dialog=False)
Variables
translate
QT_TRANSLATE_NOOP
WIKI_URL
MD_RAW_URL
MD_RENDERED_URL
MD_TRANSLATIONS_FOLDER
ERRORTXT
LOCTXT
LOGTXT
CONVERTTXT
PREFS
ICON
Function Documentation
add_language_path()
def Help.add_language_path ()
registers the Help translations to FreeCAD
Definition at line 435 of file Help.py.
add_preferences_page()
def Help.add_preferences_page ()
adds the Help preferences page to the UI
Definition at line 426 of file Help.py.
References QT_TRANSLATE_NOOP.
convert()
def Help.convert (content, force = None)
converts the given markdown code to html. Force can be None (automatic)
or markdown, pandoc, github or raw/builtin
Definition at line 320 of file Help.py.
References importFCMat.decode(), AssemblyImport.open(), and importers.import3DS.read().
Referenced by femsolver.elmer.equations.deformation_writer.DeformationWriter.handleDeformationMaterial(), femsolver.elmer.equations.elasticity_writer.ElasticityWriter.handleElasticityMaterial(), femsolver.elmer.equations.electrostatic_writer.ESwriter.handleElectrostaticConstants(), femsolver.elmer.equations.flow_writer.Flowwriter.handleFlowConstants(), femsolver.elmer.equations.flow_writer.Flowwriter.handleFlowMaterial(), femsolver.elmer.equations.heat_writer.Heatwriter.handleHeatConstants(), femsolver.elmer.equations.heat_writer.Heatwriter.handleHeatMaterial(), femsolver.elmer.equations.magnetodynamic2D_writer.MgDyn2Dwriter.handleMagnetodynamic2DConstants(), femsolver.elmer.equations.magnetodynamic2D_writer.MgDyn2Dwriter.handleMagnetodynamic2DMaterial(), femsolver.elmer.equations.magnetodynamic_writer.MgDynwriter.handleMagnetodynamicConstants(), femsolver.elmer.equations.magnetodynamic_writer.MgDynwriter.handleMagnetodynamicMaterial(), Gui::NetworkRetriever.setEnableConvert(), and show().
get_contents()
def Help.get_contents (location)
retrieves text contents of a given page
Definition at line 298 of file Help.py.
References importFCMat.decode(), and AssemblyImport.open().
Referenced by show().
get_location()
tuple Help.get_location (page)
retrieves the location (online or offline) of a given page. Returns the location and the page name
Definition at line 185 of file Help.py.
References location_url().
Referenced by show().
get_qtwebwidgets()
def Help.get_qtwebwidgets ()
verifies if qtwebengine is available
Definition at line 286 of file Help.py.
Referenced by show().
get_uri()
def Help.get_uri (location)
returns a valid URI from a disk or network location
Definition at line 147 of file Help.py.
Referenced by show().
location_url()
tuple Help.location_url (str url_localized, str url_english)
Returns localized documentation url and page name, if they exist,
otherwise defaults to english version.
Page name is gotten from:
  a) Name/* metadata tag on raw markdown files from github,
     Wiki translators should make sure to add it.
  b) <title> HTML tag
Definition at line 159 of file Help.py.
References importFCMat.decode().
Referenced by get_location().
openBrowserHTML()
def Help.openBrowserHTML (html, baseurl, title, icon, dialog = False)
creates a browser view and adds it as a FreeCAD MDI tab or dockable dialog
Definition at line 444 of file Help.py.
References show().
Referenced by show_dialog(), and show_tab().
show()
def Help.show (page, view = None, conv = None)
show(page,view=None, conv=None):
Opens a help viewer and shows the given help page.
The given help page can be a URL pointing to a markdown or HTML file,
a name page / command name, or a file path pointing to a markdown
or HTML file. If view is given (an instance of openBrowserHTML.HelpPage or
any other object with a 'setHtml()' method), the page will be
rendered there, otherwise a new tab/widget will be created according to
preferences settings. If conv is given (markdown, pandoc, github, builtin or
none), the corresponding markdown conversion method is used. Otherwise, the
module will use the best available.
In non-GUI mode, this function simply outputs the markdown or HTML text.
Definition at line 91 of file Help.py.
References convert(), get_contents(), get_location(), get_qtwebwidgets(), get_uri(), show_browser(), show_dialog(), show_tab(), and underscore_page().
Referenced by openBrowserHTML().
show_browser()
def Help.show_browser (url)
opens the desktop browser with the given URL
Definition at line 244 of file Help.py.
Referenced by show().
show_dialog()
def Help.show_dialog (html, baseurl, title, view = None)
opens a dock dialog with the given html
Definition at line 262 of file Help.py.
References openBrowserHTML(), and Init.parent.
Referenced by show().
show_tab()
def Help.show_tab (html, baseurl, title, view = None)
opens a MDI tab with the given html
Definition at line 274 of file Help.py.
References openBrowserHTML(), and Init.parent.
Referenced by show().
underscore_page()
def Help.underscore_page (page)
change spaces by underscores in the given page name
Definition at line 135 of file Help.py.
Referenced by show().
Variable Documentation
CONVERTTXT
Help.CONVERTTXT
Definition at line 83 of file Help.py.
ERRORTXT
Help.ERRORTXT
Definition at line 71 of file Help.py.
ICON
Help.ICON
Definition at line 88 of file Help.py.
LOCTXT
Help.LOCTXT
Definition at line 75 of file Help.py.
LOGTXT
Help.LOGTXT
Definition at line 79 of file Help.py.
MD_RAW_URL
Help.MD_RAW_URL
Definition at line 68 of file Help.py.
MD_RENDERED_URL
Help.MD_RENDERED_URL
Definition at line 69 of file Help.py.
MD_TRANSLATIONS_FOLDER
Help.MD_TRANSLATIONS_FOLDER
Definition at line 70 of file Help.py.
PREFS
Help.PREFS
Definition at line 87 of file Help.py.
QT_TRANSLATE_NOOP
Help.QT_TRANSLATE_NOOP
Definition at line 64 of file Help.py.
Referenced by add_preferences_page().
translate
Help.translate
Definition at line 63 of file Help.py.
WIKI_URL
Help.WIKI_URL
Definition at line 67 of file Help.py.