FreeCAD: Gui::PythonWorkbench Class Reference
Gui::PythonWorkbench Class Reference
#include <Workbench.h>
Public Member Functions
PythonWorkbench ()
~PythonWorkbench () override
void setupContextMenu (const char *recipient, MenuItem *) const override
void createMainWindowPopupMenu (MenuItem *) const override
Public Member Functions inherited from Gui::PythonBaseWorkbench
PythonBaseWorkbench ()
~PythonBaseWorkbench () override
PyObject * getPyObject () override
void appendMenu (const std::list< std::string > &menu, const std::list< std::string > &items) const
Appends a new menu.
void removeMenu (const std::string &menu) const
Removes a menu.
void appendContextMenu (const std::list< std::string > &menu, const std::list< std::string > &items) const
Appends new context menu items.
void removeContextMenu (const std::string &menu) const
Removes a context menu.
void clearContextMenu ()
void appendToolbar (const std::string &bar, const std::list< std::string > &items) const
Appends a new toolbar.
void removeToolbar (const std::string &bar) const
Removes a toolbar.
void appendCommandbar (const std::string &bar, const std::list< std::string > &items) const
Appends a new command bar.
void removeCommandbar (const std::string &bar) const
Removes a command bar.
Public Member Functions inherited from Gui::Workbench
Workbench ()
~Workbench () override
std::string name () const
void setName (const std::string &)
void createContextMenu (const char *recipient, MenuItem *) const
bool activate ()
void retranslate () const
virtual void activated ()
virtual void deactivated ()
void addTaskWatcher (const std::vector< Gui::TaskView::TaskWatcher * > &Watcher)
helper to add TaskWatcher to the TaskView
void removeTaskWatcher ()
remove the added TaskWatcher
std::list< std::string > listToolbars () const
std::list< std::pair< std::string, std::list< std::string > > > getToolbarItems () const
Shows a list of all toolbars and their commands.
std::list< std::string > listMenus () const
std::list< std::string > listCommandbars () const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
MenuItem * setupMenuBar () const override
ToolBarItem * setupToolBars () const override
ToolBarItem * setupCommandBars () const override
DockWindowItems * setupDockWindows () const override
Protected Member Functions inherited from Gui::PythonBaseWorkbench
Protected Member Functions inherited from Gui::Workbench
void addPermanentMenuItems (MenuItem *) const
Additional Inherited Members
Static Public Member Functions inherited from Gui::Workbench
static void createLinkMenu (MenuItem *)
static void addPermanentMenuItem (const std::string &cmd, const std::string &after)
static void removePermanentMenuItem (const std::string &cmd)
Removes the command cmd from the permanent menu items.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::PythonBaseWorkbench
MenuItem * _menuBar {nullptr}
MenuItem * _contextMenu {nullptr}
ToolBarItem * _toolBar {nullptr}
ToolBarItem * _commandBar {nullptr}
Base::PyObjectBase * _workbenchPy {nullptr}
Detailed Description
The PythonWorkbench class allows the manipulation of the workbench from Python. Therefore PythonWorkbenchPy provides the required Python interface.
Author
Werner Mayer
Definition at line 316 of file Gui/Workbench.h.
Constructor & Destructor Documentation
PythonWorkbench()
PythonWorkbench::PythonWorkbench ()
Definition at line 1238 of file Gui/Workbench.cpp.
References Gui::StdWorkbench::setupMenuBar(), and Gui::StdWorkbench::setupToolBars().
~PythonWorkbench()
PythonWorkbench::~PythonWorkbench () override default
Member Function Documentation
createMainWindowPopupMenu()
void PythonWorkbench::createMainWindowPopupMenu (MenuItem *) const override virtual
Sets up the contextmenu for the main window for this workbench. The default implementation does nothing.
Reimplemented from Gui::Workbench.
Definition at line 1277 of file Gui/Workbench.cpp.
References Gui::StdWorkbench::createMainWindowPopupMenu().
setupCommandBars()
ToolBarItem * PythonWorkbench::setupCommandBars () const override protected virtual
Returns a ToolBarItem tree structure of command bars for this workbench.
Reimplemented from Gui::PythonBaseWorkbench.
Definition at line 1259 of file Gui/Workbench.cpp.
References Gui::PythonBaseWorkbench::_commandBar, and Gui::ToolBarItem::copy().
setupContextMenu()
void PythonWorkbench::setupContextMenu (const char * recipient, MenuItem * item) const override virtual
Defines the standard context menu.
Reimplemented from Gui::PythonBaseWorkbench.
Definition at line 1270 of file Gui/Workbench.cpp.
References Gui::StdWorkbench::setupContextMenu(), and Gui::PythonBaseWorkbench::setupContextMenu().
setupDockWindows()
DockWindowItems * PythonWorkbench::setupDockWindows () const override protected virtual
Returns a DockWindowItems structure of dock windows this workbench.
Reimplemented from Gui::PythonBaseWorkbench.
Definition at line 1264 of file Gui/Workbench.cpp.
References Gui::StdWorkbench::setupDockWindows().
setupMenuBar()
MenuItem * PythonWorkbench::setupMenuBar () const override protected virtual
Returns a MenuItem tree structure of menus for this workbench.
Reimplemented from Gui::PythonBaseWorkbench.
Definition at line 1249 of file Gui/Workbench.cpp.
References Gui::PythonBaseWorkbench::_menuBar, and Gui::MenuItem::copy().
setupToolBars()
ToolBarItem * PythonWorkbench::setupToolBars () const override protected virtual
Returns a ToolBarItem tree structure of toolbars for this workbench.
Reimplemented from Gui::PythonBaseWorkbench.
Definition at line 1254 of file Gui/Workbench.cpp.
References Gui::PythonBaseWorkbench::_toolBar, and Gui::ToolBarItem::copy().
The documentation for this class was generated from the following files:
Gui/Workbench.h
Gui/Workbench.cpp