FreeCAD: Gui::EditableDatumLabel Class Reference
Gui::EditableDatumLabel Class Reference
#include <EditableDatumLabel.h>
Public Types
enum Function { Function::Positioning, Function::Dimensioning }
Signals
void valueChanged (double val)
Public Member Functions
EditableDatumLabel (View3DInventorViewer *view, const Base::Placement &plc, SbColor color, bool autoDistance=false, bool avoidMouseCursor=false)
~EditableDatumLabel () override
void activate ()
void deactivate ()
void startEdit (double val, QObject *eventFilteringObj=nullptr, bool visibleToMouse=false)
void stopEdit ()
bool isActive () const
bool isInEdit () const
double getValue () const
void setSpinboxValue (double val, const Base::Unit &unit=Base::Unit::Length)
void setPlacement (const Base::Placement &plc)
void setColor (SbColor color)
void setFocus ()
void setPoints (SbVec3f p1, SbVec3f p2)
void setPoints (Base::Vector3d p1, Base::Vector3d p2)
void setFocusToSpinbox ()
void setLabelType (SoDatumLabel::Type type, Function function=Function::Positioning)
void setLabelDistance (double val)
void setLabelStartAngle (double val)
void setLabelRange (double val)
void setLabelRecommendedDistance ()
void setLabelAutoDistanceReverse (bool val)
void setSpinboxVisibleToMouse (bool val)
Function getFunction ()
Public Attributes
SoDatumLabel * label
bool isSet
bool autoDistance
bool autoDistanceReverse
bool avoidMouseCursor
double value
Detailed Description
Definition at line 43 of file EditableDatumLabel.h.
Member Enumeration Documentation
Function
enum Gui::EditableDatumLabel::Function strong
Enumerator
Positioning
Dimensioning
Definition at line 49 of file EditableDatumLabel.h.
Constructor & Destructor Documentation
EditableDatumLabel()
EditableDatumLabel::EditableDatumLabel (View3DInventorViewer * view, const Base::Placement & plc, SbColor color, bool autoDistance = false, bool avoidMouseCursor = false)
Definition at line 47 of file EditableDatumLabel.cpp.
References autoDistance, Gui::SoDatumLabel::DISTANCE, MeshCore::MeshIO::OFF, setLabelRecommendedDistance(), and setPlacement().
~EditableDatumLabel()
EditableDatumLabel::~EditableDatumLabel () override
Definition at line 91 of file EditableDatumLabel.cpp.
References deactivate().
Member Function Documentation
activate()
void EditableDatumLabel::activate ()
Definition at line 99 of file EditableDatumLabel.cpp.
References Path.Log::info(), and isActive().
Referenced by ArchBuildingPart.ViewProviderBuildingPart::setEdit(), nativeifc.ifc_viewproviders.ifc_vp_object::setupContextMenu(), and ArchBuildingPart.ViewProviderBuildingPart::setupContextMenu().
deactivate()
void EditableDatumLabel::deactivate ()
Definition at line 120 of file EditableDatumLabel.cpp.
References stopEdit().
Referenced by CommandCreateBom.TaskAssemblyCreateBom::accept(), CommandInsertNewPart.TaskAssemblyNewPart::accept(), CommandCreateView.TaskAssemblyCreateView::accept(), CommandCreateSimulation.TaskAssemblyCreateSimulation::accept(), JointObject.TaskAssemblyCreateJoint::accept(), Gui::InteractiveScale::deactivate(), CommandCreateBom.TaskAssemblyCreateBom::reject(), CommandCreateView.TaskAssemblyCreateView::reject(), CommandCreateSimulation.TaskAssemblyCreateSimulation::reject(), JointObject.TaskAssemblyCreateJoint::reject(), and ~EditableDatumLabel().
getFunction()
EditableDatumLabel::Function EditableDatumLabel::getFunction ()
Definition at line 398 of file EditableDatumLabel.cpp.
getValue()
double EditableDatumLabel::getValue () const
Definition at line 204 of file EditableDatumLabel.cpp.
References value.
Referenced by Gui::InteractiveScale::getScaleFactor().
isActive()
bool EditableDatumLabel::isActive () const
Definition at line 193 of file EditableDatumLabel.cpp.
Referenced by activate().
isInEdit()
bool EditableDatumLabel::isInEdit () const
Definition at line 198 of file EditableDatumLabel.cpp.
Referenced by startEdit().
setColor()
void EditableDatumLabel::setColor (SbColor color)
Definition at line 319 of file EditableDatumLabel.cpp.
setFocus()
void EditableDatumLabel::setFocus ()
Definition at line 324 of file EditableDatumLabel.cpp.
References Gui::QuantitySpinBox::selectNumber().
Referenced by DraftGui.DraftToolBar::displayPoint(), DraftGui.DraftToolBar::pointUi(), DraftGui.DraftToolBar::radiusUi(), DraftGui.DraftToolBar::setNextFocus(), DraftGui.DraftToolBar::setRadiusValue(), and DraftGui.DraftToolBar::trimUi().
setFocusToSpinbox()
void EditableDatumLabel::setFocusToSpinbox ()
Definition at line 227 of file EditableDatumLabel.cpp.
References Base::Console(), Base::ConsoleSingleton::DeveloperWarning(), and Gui::QuantitySpinBox::selectNumber().
Referenced by startEdit().
setLabelAutoDistanceReverse()
void EditableDatumLabel::setLabelAutoDistanceReverse (bool val)
Definition at line 388 of file EditableDatumLabel.cpp.
References autoDistanceReverse, and toolbit-attributes::val.
setLabelDistance()
void EditableDatumLabel::setLabelDistance (double val)
Definition at line 357 of file EditableDatumLabel.cpp.
References toolbit-attributes::val.
setLabelRange()
void EditableDatumLabel::setLabelRange (double val)
Definition at line 369 of file EditableDatumLabel.cpp.
References toolbit-attributes::val.
setLabelRecommendedDistance()
void EditableDatumLabel::setLabelRecommendedDistance ()
Definition at line 374 of file EditableDatumLabel.cpp.
References autoDistanceReverse.
Referenced by EditableDatumLabel(), and setPoints().
setLabelStartAngle()
void EditableDatumLabel::setLabelStartAngle (double val)
Definition at line 363 of file EditableDatumLabel.cpp.
References toolbit-attributes::val.
setLabelType()
void EditableDatumLabel::setLabelType (SoDatumLabel::Type type, Function function = Function::Positioning)
Definition at line 350 of file EditableDatumLabel.cpp.
References Path.Post.scripts.grbl_post::type.
setPlacement()
void EditableDatumLabel::setPlacement (const Base::Placement & plc)
Definition at line 304 of file EditableDatumLabel.cpp.
References Base::Placement::getPosition(), Base::Placement::getRotation(), Base::Rotation::getValue(), Base::Rotation::multVec(), RobotExample::pos, src.Mod.PartDesign.fcgear.svggear::w, MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by EditableDatumLabel(), and Gui::InteractiveScale::setPlacement().
setPoints() [1/2]
void EditableDatumLabel::setPoints (Base::Vector3d p1, Base::Vector3d p2)
Definition at line 343 of file EditableDatumLabel.cpp.
References setPoints(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
setPoints() [2/2]
void EditableDatumLabel::setPoints (SbVec3f p1, SbVec3f p2)
Definition at line 331 of file EditableDatumLabel.cpp.
References autoDistance, and setLabelRecommendedDistance().
Referenced by setPoints().
setSpinboxValue()
void EditableDatumLabel::setSpinboxValue (double val, const Base::Unit & unit = Base::Unit::Length)
Definition at line 210 of file EditableDatumLabel.cpp.
References Base::Console(), Base::ConsoleSingleton::DeveloperWarning(), Gui::QuantitySpinBox::selectNumber(), Gui::QuantitySpinBox::setValue(), unit(), toolbit-attributes::val, and value.
Referenced by startEdit().
setSpinboxVisibleToMouse()
void EditableDatumLabel::setSpinboxVisibleToMouse (bool val)
Definition at line 393 of file EditableDatumLabel.cpp.
References toolbit-attributes::val.
Referenced by startEdit().
startEdit()
void EditableDatumLabel::startEdit (double val, QObject * eventFilteringObj = nullptr, bool visibleToMouse = false)
Definition at line 137 of file EditableDatumLabel.cpp.
References draftgeoutils.intersections::connect(), isInEdit(), isSet, Base::Unit::Length, setFocusToSpinbox(), Gui::QuantitySpinBox::setMaximum(), Gui::QuantitySpinBox::setMinimum(), setSpinboxValue(), setSpinboxVisibleToMouse(), Gui::QuantitySpinBox::setUnit(), toolbit-attributes::val, value, valueChanged(), and Gui::QuantitySpinBox::valueChanged().
stopEdit()
void EditableDatumLabel::stopEdit ()
Definition at line 176 of file EditableDatumLabel.cpp.
References Base::Quantity::getUserString(), and Gui::QuantitySpinBox::value.
Referenced by deactivate().
valueChanged
void Gui::EditableDatumLabel::valueChanged (double val) signal
Referenced by startEdit().
Member Data Documentation
autoDistance
bool Gui::EditableDatumLabel::autoDistance
Definition at line 86 of file EditableDatumLabel.h.
Referenced by EditableDatumLabel(), and setPoints().
autoDistanceReverse
bool Gui::EditableDatumLabel::autoDistanceReverse
Definition at line 87 of file EditableDatumLabel.h.
Referenced by setLabelAutoDistanceReverse(), and setLabelRecommendedDistance().
avoidMouseCursor
bool Gui::EditableDatumLabel::avoidMouseCursor
Definition at line 88 of file EditableDatumLabel.h.
isSet
bool Gui::EditableDatumLabel::isSet
Definition at line 85 of file EditableDatumLabel.h.
Referenced by startEdit().
label
SoDatumLabel* Gui::EditableDatumLabel::label
Definition at line 84 of file EditableDatumLabel.h.
Referenced by WorkingPlane.PlaneGui::align_to_obj_placement(), WorkingPlane.PlaneGui::align_to_selection(), WorkingPlane.PlaneGui::align_view(), WorkingPlane.PlaneGui::center_on_view(), Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.TrackChunk::dump_array(), Dice3DS.dom3ds.ChunkBase::dump_header(), Dice3DS.dom3ds.ChunkBase::get_chunk(), ArchSpace._ViewProviderSpace::onChanged(), WorkingPlane.PlaneGui::set_to_auto(), WorkingPlane.PlaneGui::set_to_front(), WorkingPlane.PlaneGui::set_to_position(), WorkingPlane.PlaneGui::set_to_side(), WorkingPlane.PlaneGui::set_to_top(), and WorkingPlane.PlaneGui::set_to_view().
value
double Gui::EditableDatumLabel::value
Definition at line 89 of file EditableDatumLabel.h.
Referenced by src.Mod.AddonManager.Addon.Addon.Status::__lt__(), OpenSCADUtils.OpenSCADError::__str__(), femobjects.base_fempythonobject._PropHelper::add_to_object(), Path.Base.Property.Property::displayString(), Path.Base.SetupSheetOpPrototype.Property::displayString(), Path.Base.Property.PropertyQuantity::displayString(), Path.Base.SetupSheetOpPrototype.PropertyQuantity::displayString(), src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), Path.Base.Property.Property::getValue(), Path.Base.SetupSheetOpPrototype.Property::getValue(), getValue(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), setSpinboxValue(), Path.Base.Property.Property::setValue(), Path.Base.SetupSheetOpPrototype.Property::setValue(), and startEdit().
The documentation for this class was generated from the following files:
EditableDatumLabel.h
EditableDatumLabel.cpp