FreeCAD: Gui::DialogOptions Class Reference
Gui::DialogOptions Class Reference
The DialogOptions class Helper class to control whether to use native or Qt dialogs.
#include <FileDialog.h>
Static Public Member Functions
static bool dontUseNativeFileDialog ()
static bool dontUseNativeColorDialog ()
Detailed Description
The DialogOptions class Helper class to control whether to use native or Qt dialogs.
Definition at line 48 of file FileDialog.h.
Member Function Documentation
dontUseNativeColorDialog()
bool DialogOptions::dontUseNativeColorDialog () static
Definition at line 69 of file FileDialog.cpp.
References App::GetApplication(), ParameterGrp::GetGroup(), App::Application::GetUserParameter(), and toolbit-attributes::group.
Referenced by ColorPickerPopup::getColorFromDialog(), MRichTextEdit::textBgColor(), and MRichTextEdit::textFgColor().
dontUseNativeFileDialog()
bool DialogOptions::dontUseNativeFileDialog () static
Definition at line 55 of file FileDialog.cpp.
References App::GetApplication(), ParameterGrp::GetGroup(), App::Application::GetUserParameter(), and toolbit-attributes::group.
Referenced by Gui::FileDialog::getOpenFileName(), Gui::FileDialog::getOpenFileNames(), and Gui::FileDialog::getSaveFileName().
The documentation for this class was generated from the following files:
FileDialog.h
FileDialog.cpp