FreeCAD: Application.cpp File Reference
Gui/Application.cpp File Reference
#include "PreCompiled.h"
#include <boost/interprocess/sync/file_lock.hpp>
#include <Inventor/errors/SoDebugError.h>
#include <Inventor/errors/SoError.h>
#include <QCloseEvent>
#include <QDir>
#include <QFileInfo>
#include <QLocale>
#include <QMessageBox>
#include <QMessageLogContext>
#include <QRegularExpression>
#include <QRegularExpressionMatch>
#include <QStatusBar>
#include <QStyle>
#include <QTextStream>
#include <QTimer>
#include <QWindow>
#include <QLoggingCategory>
#include <fmt/format.h>
#include <App/Document.h>
#include <App/DocumentObjectPy.h>
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/Exception.h>
#include <Base/FileInfo.h>
#include <Base/Parameter.h>
#include <Base/Stream.h>
#include <Base/Tools.h>
#include <Base/UnitsApi.h>
#include <Language/Translator.h>
#include <Quarter/Quarter.h>
#include "Application.h"
#include "ApplicationPy.h"
#include "AxisOriginPy.h"
#include "BitmapFactory.h"
#include "Command.h"
#include "CommandActionPy.h"
#include "CommandPy.h"
#include "Control.h"
#include "PreferencePages/DlgSettingsCacheDirectory.h"
#include "DocumentPy.h"
#include "DocumentRecovery.h"
#include "EditorView.h"
#include "ExpressionBindingPy.h"
#include "FileDialog.h"
#include "GuiApplication.h"
#include "GuiInitScript.h"
#include "LinkViewPy.h"
#include "MainWindow.h"
#include "Macro.h"
#include "PreferencePackManager.h"
#include "PythonConsolePy.h"
#include "PythonDebugger.h"
#include "MainWindowPy.h"
#include "MDIViewPy.h"
#include "Placement.h"
#include "SoFCDB.h"
#include "Selection.h"
#include "SelectionFilterPy.h"
#include "SoQtOffscreenRendererPy.h"
#include "SplitView3DInventor.h"
#include "StartupProcess.h"
#include "TaskView/TaskView.h"
#include "TaskView/TaskDialogPython.h"
#include "TransactionObject.h"
#include "TextDocumentEditorView.h"
#include "UiLoader.h"
#include "View3DPy.h"
#include "View3DViewerPy.h"
#include "View3DInventor.h"
#include "ViewProviderAnnotation.h"
#include "ViewProviderDocumentObject.h"
#include "ViewProviderDocumentObjectGroup.h"
#include "ViewProviderDragger.h"
#include "ViewProviderExtension.h"
#include "ViewProviderExtern.h"
#include "ViewProviderFeature.h"
#include "ViewProviderGeoFeatureGroup.h"
#include "ViewProviderGeometryObject.h"
#include "ViewProviderGeometryObjectPy.h"
#include "ViewProviderGroupExtension.h"
#include "ViewProviderSuppressibleExtension.h"
#include "ViewProviderImagePlane.h"
#include "ViewProviderInventorObject.h"
#include "ViewProviderLine.h"
#include "ViewProviderLink.h"
#include "ViewProviderLinkPy.h"
#include "ViewProviderMaterialObject.h"
#include "ViewProviderCoordinateSystem.h"
#include "ViewProviderDatum.h"
#include "ViewProviderOriginGroup.h"
#include "ViewProviderPlacement.h"
#include "ViewProviderPlane.h"
#include "ViewProviderPoint.h"
#include "ViewProviderPart.h"
#include "ViewProviderFeaturePython.h"
#include "ViewProviderTextDocument.h"
#include "ViewProviderTextureExtension.h"
#include "ViewProviderVRMLObject.h"
#include "ViewProviderVarSet.h"
#include "WaitCursor.h"
#include "Workbench.h"
#include "WorkbenchManager.h"
#include "WorkbenchManipulator.h"
#include "WidgetFactory.h"
#include "3Dconnexion/navlib/NavlibInterface.h"
Classes
class Gui::ViewProviderMap
struct Gui::ApplicationP
Namespaces
Gui
Typedefs
using _qt_msg_handler_old = void(*)(QtMsgType, const QMessageLogContext &, const QString &)
Functions
static PyObject * Gui::FreeCADGui_subgraphFromObject (PyObject *, PyObject *args)
static PyObject * Gui::FreeCADGui_exportSubgraph (PyObject *, PyObject *args)
static PyObject * Gui::FreeCADGui_getSoDBVersion (PyObject *, PyObject *args)
void messageHandler (QtMsgType type, const QMessageLogContext &context, const QString &msg)
static void init_resources ()
Variables
struct PyMethodDef Gui::FreeCADGui_methods []
_qt_msg_handler_old old_qtmsg_handler = nullptr
Typedef Documentation
_qt_msg_handler_old
using _qt_msg_handler_old = void (*)(QtMsgType, const QMessageLogContext&, const QString&)
Definition at line 1935 of file Gui/Application.cpp.
Function Documentation
init_resources()
static void init_resources () static
Definition at line 2009 of file Gui/Application.cpp.
Referenced by Gui::Application::initApplication().
messageHandler()
void messageHandler (QtMsgType type, const QMessageLogContext & context, const QString & msg)
Definition at line 1938 of file Gui/Application.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), Base::ConsoleSingleton::Log(), Base::ConsoleSingleton::Message(), Path.Op.Surface::msg, old_qtmsg_handler, Path.Post.scripts.grbl_post::type, and Base::ConsoleSingleton::Warning().
Referenced by Gui::Application::initApplication().
Variable Documentation
old_qtmsg_handler
_qt_msg_handler_old old_qtmsg_handler = nullptr
Definition at line 1936 of file Gui/Application.cpp.
Referenced by Gui::Application::initApplication(), and messageHandler().