FreeCAD: MeshCoreFit::CylinderFit Class Reference
MeshCoreFit::CylinderFit Class Reference
#include <CylinderFit.h>
Public Member Functions
CylinderFit ()
void SetApproximations (double radius, const Base::Vector3d &base, const Base::Vector3d &axis)
void SetApproximations (const Base::Vector3d &base, const Base::Vector3d &axis)
void SetConvergenceCriteria (double posConvLimit, double dirConvLimit, double vConvLimit, int maxIter)
double GetRadius () const
Base::Vector3d GetBase () const
Base::Vector3d GetAxis () const
int GetNumIterations () const
float Fit () override
float GetDistanceToCylinder (const Base::Vector3f &rcPoint) const
float GetStdDeviation () const
void ProjectToCylinder ()
Public Member Functions inherited from MeshCore::Approximation
Approximation ()
virtual ~Approximation ()
void AddPoint (const Base::Vector3f &point)
void AddPoints (const std::vector< Base::Vector3f > &points)
void AddPoints (const std::set< Base::Vector3f > &points)
void AddPoints (const std::list< Base::Vector3f > &points)
void AddPoints (const MeshPointArray &points)
const std::list< Base::Vector3f > & GetPoints () const
Base::Vector3f GetGravity () const
std::size_t CountPoints () const
void Clear ()
float GetLastResult () const
bool Done () const
Protected Types
enum SolutionD { solL = 0, solM = 1, solN = 2 }
Protected Member Functions
void ComputeApproximationsLine ()
void findBestSolDirection (SolutionD &solDir)
double meanXObs ()
double meanYObs ()
double meanZObs ()
void setupNormalEquationMatrices (SolutionD solDir, const std::vector< Base::Vector3d > &residuals, Matrix5x5 &atpa, Eigen::VectorXd &atpl) const
void setupObservation (SolutionD solDir, const Base::Vector3f &point, const Base::Vector3d &residual, DoubleArray5 &a, double &f0, double &qw, DoubleArray3 &b) const
void addObservationU (DoubleArray5 a, double li, double pi, Matrix5x5 &atpa, Eigen::VectorXd &atpl) const
void setLowerPart (Matrix5x5 &atpa) const
bool computeResiduals (SolutionD solDir, const Eigen::VectorXd &x, std::vector< Base::Vector3d > &residuals, double &sigma0, double vConvLimit, bool &vConverged) const
bool updateParameters (SolutionD solDir, const Eigen::VectorXd &x)
Protected Member Functions inherited from MeshCore::Approximation
void GetMgcVectorArray (std::vector< Wm4::Vector3< double >> &rcPts) const
Approximation (const Approximation &)=default
Approximation (Approximation &&)=default
Approximation & operator= (const Approximation &)=default
Approximation & operator= (Approximation &&)=default
Additional Inherited Members
Protected Attributes inherited from MeshCore::Approximation
std::list< Base::Vector3f > _vPoints
bool _bIsFitted {false}
float _fLastResult {FLOAT_MAX}
Detailed Description
Best-fit cylinder for a given set of points. Doesn't expect points on any top or bottom end-planes, only points on the side surface
Definition at line 63 of file CylinderFit.h.
Member Enumeration Documentation
SolutionD
enum MeshCoreFit::CylinderFit::SolutionD protected
Enumerator
solL
solM
solN
Definition at line 67 of file CylinderFit.h.
Constructor & Destructor Documentation
CylinderFit()
CylinderFit::CylinderFit ()
Construction
Definition at line 73 of file CylinderFit.cpp.
Member Function Documentation
addObservationU()
void CylinderFit::addObservationU (DoubleArray5 a, double li, double pi, Matrix5x5 & atpa, Eigen::VectorXd & atpl) const protected
Computes contribution of the given observation equation on the normal equation matrices
Definition at line 590 of file CylinderFit.cpp.
References a, SplineSurface::i, and ClipperLib::pi.
Referenced by setupNormalEquationMatrices().
ComputeApproximationsLine()
void CylinderFit::ComputeApproximationsLine () protected
Compute approximations for the parameters using all points using the line fit method
Definition at line 239 of file CylinderFit.cpp.
References MeshCore::Approximation::_bIsFitted, MeshCore::Approximation::_fLastResult, MeshCore::Approximation::_vPoints, Wm4::Line3< Real >::Direction, Base::Vector3< float_type >::DistanceToLine(), FLOAT_MAX, Wm4::Line3< Real >::Origin, Wm4::OrthogonalLineFit3(), Base::Vector3< float_type >::Set(), and TestSpreadsheet::v.
Referenced by Fit().
computeResiduals()
bool CylinderFit::computeResiduals (SolutionD solDir, const Eigen::VectorXd & x, std::vector< Base::Vector3d > & residuals, double & sigma0, double vConvLimit, bool & vConverged) const protected
Compute the residuals and sigma0 and check the residual convergence
Definition at line 621 of file CylinderFit.cpp.
References MeshCore::Approximation::_vPoints, a, SCL.SimpleDataTypes::b, SplineSurface::i, setupObservation(), KDL::sqrt(), TestSpreadsheet::v, and MovieTool::x.
Referenced by Fit().
findBestSolDirection()
void CylinderFit::findBestSolDirection (SolutionD & solDir) protected
Checks initial parameter values and defines the best solution direction to use
Definition at line 360 of file CylinderFit.cpp.
References meanXObs(), meanYObs(), meanZObs(), Base::Vector3< float_type >::Normalize(), RobotExample::pos, Base::Vector3< float_type >::Set(), solL, solM, solN, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by Fit().
Fit()
float CylinderFit::Fit () override virtual
Fit a cylinder into the given points. If the fit fails FLOAT_MAX is returned.
Implements MeshCore::Approximation.
Definition at line 266 of file CylinderFit.cpp.
References MeshCore::Approximation::_bIsFitted, MeshCore::Approximation::_fLastResult, ComputeApproximationsLine(), computeResiduals(), MeshCore::Approximation::CountPoints(), findBestSolDirection(), FLOAT_MAX, setupNormalEquationMatrices(), GCS::Success, updateParameters(), and MovieTool::x.
Referenced by MeshCore::CylinderFit::Fit().
GetAxis()
Base::Vector3d CylinderFit::GetAxis () const
Returns the axis of the fitted cylinder. If Fit() has not been called the null vector is returned.
Definition at line 151 of file CylinderFit.cpp.
References MeshCore::Approximation::_bIsFitted.
Referenced by MeshCore::CylinderFit::Fit().
GetBase()
Base::Vector3d CylinderFit::GetBase () const
Returns the base of the fitted cylinder. If Fit() has not been called the null vector is returned.
Definition at line 142 of file CylinderFit.cpp.
References MeshCore::Approximation::_bIsFitted.
Referenced by MeshCore::CylinderFit::Fit().
GetDistanceToCylinder()
float CylinderFit::GetDistanceToCylinder (const Base::Vector3f & rcPoint) const
Returns the distance from the point rcPoint to the fitted cylinder. If Fit() has not been called FLOAT_MAX is returned.
Definition at line 169 of file CylinderFit.cpp.
References MeshCore::Approximation::_bIsFitted, Base::Vector3< float_type >::DistanceToLine(), FLOAT_MAX, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by GetStdDeviation().
GetNumIterations()
int CylinderFit::GetNumIterations () const
Returns the number of iterations that Fit() needed to converge. If Fit() has not been called then zero is returned.
Definition at line 160 of file CylinderFit.cpp.
References MeshCore::Approximation::_bIsFitted.
Referenced by MeshCore::CylinderFit::Fit().
GetRadius()
double CylinderFit::GetRadius () const
Returns the radius of the fitted cylinder. If Fit() has not been called then zero is returned.
Definition at line 133 of file CylinderFit.cpp.
References MeshCore::Approximation::_bIsFitted.
Referenced by MeshCore::CylinderFit::Fit().
GetStdDeviation()
float CylinderFit::GetStdDeviation () const
Returns the standard deviation from the points to the fitted cylinder. If Fit() has not been called FLOAT_MAX is returned.
Definition at line 179 of file CylinderFit.cpp.
References MeshCore::Approximation::_bIsFitted, MeshCore::Approximation::_vPoints, MeshCore::Approximation::CountPoints(), DraftVecUtils::dist(), FLOAT_MAX, GetDistanceToCylinder(), and KDL::sqrt().
Referenced by MeshCore::CylinderFit::Fit().
meanXObs()
double CylinderFit::meanXObs () protected
Compute the mean X-value of all of the points (observed/input surface points)
Definition at line 410 of file CylinderFit.cpp.
References MeshCore::Approximation::_vPoints.
Referenced by findBestSolDirection().
meanYObs()
double CylinderFit::meanYObs () protected
Compute the mean Y-value of all of the points (observed/input surface points)
Definition at line 422 of file CylinderFit.cpp.
References MeshCore::Approximation::_vPoints.
Referenced by findBestSolDirection().
meanZObs()
double CylinderFit::meanZObs () protected
Compute the mean Z-value of all of the points (observed/input surface points)
Definition at line 434 of file CylinderFit.cpp.
References MeshCore::Approximation::_vPoints.
Referenced by findBestSolDirection().
ProjectToCylinder()
void CylinderFit::ProjectToCylinder ()
Projects the points onto the fitted cylinder.
Definition at line 202 of file CylinderFit.cpp.
References MeshCore::Approximation::_vPoints, KDL::diff(), Base::Vector3< float_type >::DistanceToLine(), Base::Vector3< float_type >::Move(), Base::Vector3< float_type >::ProjectToPlane(), MovieTool::x, and MovieTool::y.
SetApproximations() [1/2]
void CylinderFit::SetApproximations (const Base::Vector3d & base, const Base::Vector3d & axis)
Set approximations before calling Fit(). This version computes the radius using the given axis and the existing surface points.
Definition at line 94 of file CylinderFit.cpp.
References MeshCore::Approximation::_bIsFitted, MeshCore::Approximation::_fLastResult, MeshCore::Approximation::_vPoints, importers.importWebGL::base, Base::Vector3< float_type >::DistanceToLine(), FLOAT_MAX, and Base::Vector3< float_type >::Normalize().
SetApproximations() [2/2]
void CylinderFit::SetApproximations (double radius, const Base::Vector3d & base, const Base::Vector3d & axis)
Set approximations before calling Fit()
Definition at line 79 of file CylinderFit.cpp.
References MeshCore::Approximation::_bIsFitted, MeshCore::Approximation::_fLastResult, importers.importWebGL::base, FLOAT_MAX, and Base::Vector3< float_type >::Normalize().
Referenced by MeshCore::CylinderFit::Fit().
SetConvergenceCriteria()
void CylinderFit::SetConvergenceCriteria (double posConvLimit, double dirConvLimit, double vConvLimit, int maxIter)
Set iteration convergence criteria for the fit if special values are needed. The default values set in the constructor are suitable for most uses
Definition at line 113 of file CylinderFit.cpp.
setLowerPart()
void CylinderFit::setLowerPart (Matrix5x5 & atpa) const protected
Set the lower part of the normal matrix equal to the upper part
Definition at line 610 of file CylinderFit.cpp.
References SplineSurface::i.
Referenced by setupNormalEquationMatrices().
setupNormalEquationMatrices()
void CylinderFit::setupNormalEquationMatrices (SolutionD solDir, const std::vector< Base::Vector3d > & residuals, Matrix5x5 & atpa, Eigen::VectorXd & atpl) const protected
Set up the normal equations
Definition at line 449 of file CylinderFit.cpp.
References MeshCore::Approximation::_vPoints, a, addObservationU(), SCL.SimpleDataTypes::b, setLowerPart(), and setupObservation().
Referenced by Fit().
setupObservation()
void CylinderFit::setupObservation (SolutionD solDir, const Base::Vector3f & point, const Base::Vector3d & residual, DoubleArray5 & a, double & f0, double & qw, DoubleArray3 & b) const protected
Sets up contributions of given observation to the normal equation matrices.
Definition at line 485 of file CylinderFit.cpp.
References a, SCL.SimpleDataTypes::b, solL, solM, solN, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by computeResiduals(), and setupNormalEquationMatrices().
updateParameters()
bool CylinderFit::updateParameters (SolutionD solDir, const Eigen::VectorXd & x) protected
Update the parameters after solving the normal equations
Definition at line 708 of file CylinderFit.cpp.
References src.Mod.PartDesign.Scripts.Gear::l2, solL, solM, solN, KDL::sqrt(), MovieTool::x, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by Fit().
The documentation for this class was generated from the following files:
CylinderFit.h
CylinderFit.cpp