FreeCAD: Gui::DimensionWidget Class Reference
Gui::DimensionWidget Class Reference
Public Member Functions
DimensionWidget (QWidget *parent)
~DimensionWidget () override
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
void changeEvent (QEvent *event) override
void setUserSchema (int userSchema)
Detailed Description
The DimensionWidget class is aiming at providing a widget used in the status bar that will:
Allow application to display dimension information such as the viewportsize
Provide a popup menu allowing user to change the used unit schema (and update if changed elsewhere)
Definition at line 167 of file MainWindow.cpp.
Constructor & Destructor Documentation
DimensionWidget()
Gui::DimensionWidget::DimensionWidget (QWidget * parent) inline explicit
Definition at line 172 of file MainWindow.cpp.
References Path.Post.scripts.dynapath_4060_post::action, draftgeoutils.intersections::connect(), Gui::getMainWindow(), SplineSurface::i, NavigationIndicatorGui::menu, Base::NumUnitSystemTypes, NavigationIndicatorGui::retranslateUi(), and bimcommands.BimViews::show().
~DimensionWidget()
Gui::DimensionWidget::~DimensionWidget () inline override
Definition at line 205 of file MainWindow.cpp.
Member Function Documentation
changeEvent()
void Gui::DimensionWidget::changeEvent (QEvent * event) inline override
Definition at line 218 of file MainWindow.cpp.
References NavigationIndicatorGui::retranslateUi().
OnChange()
void Gui::DimensionWidget::OnChange (Base::Subject< const char * > & rCaller, const char * sReason) inline override
Definition at line 210 of file MainWindow.cpp.
setUserSchema()
void Gui::DimensionWidget::setUserSchema (int userSchema) inline
Definition at line 228 of file MainWindow.cpp.
References toolbit-attributes::doc, App::Application::getActiveDocument(), App::GetApplication(), Gui::Application::Instance, Gui::Application::onUpdate(), and Base::UnitsApi::setSchema().
Referenced by Gui::MainWindow::setUserSchema().
The documentation for this class was generated from the following file:
MainWindow.cpp