FreeCAD: TechDrawGui::DlgTemplateField Class Reference
TechDrawGui::DlgTemplateField Class Reference
#include <DlgTemplateField.h>
Public Slots
void accept () override
void reject () override
Public Member Functions
DlgTemplateField (QWidget *parent=nullptr)
~DlgTemplateField () override=default
void setFieldName (std::string name)
void setFieldLength (int length)
void setFieldContent (std::string content)
void setAutofillContent (std::string content)
QString getFieldContent ()
bool getAutofillState ()
Protected Member Functions
void changeEvent (QEvent *e) override
Detailed Description
Definition at line 56 of file DlgTemplateField.h.
Constructor & Destructor Documentation
DlgTemplateField()
DlgTemplateField::DlgTemplateField (QWidget * parent = nullptr) explicit
Definition at line 31 of file DlgTemplateField.cpp.
~DlgTemplateField()
TechDrawGui::DlgTemplateField::~DlgTemplateField () override default
Member Function Documentation
accept
void DlgTemplateField::accept () override slot
Definition at line 81 of file DlgTemplateField.cpp.
changeEvent()
void DlgTemplateField::changeEvent (QEvent * e) override protected
Definition at line 38 of file DlgTemplateField.cpp.
References SCL.SimpleDataTypes::e.
getAutofillState()
bool DlgTemplateField::getAutofillState ()
Definition at line 76 of file DlgTemplateField.cpp.
Referenced by TechDrawGui::TemplateTextField::mouseReleaseEvent().
getFieldContent()
QString DlgTemplateField::getFieldContent ()
Definition at line 71 of file DlgTemplateField.cpp.
Referenced by execInsertPrefixChar(), and TechDrawGui::TemplateTextField::mouseReleaseEvent().
reject
void DlgTemplateField::reject () override slot
Definition at line 86 of file DlgTemplateField.cpp.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action().
setAutofillContent()
void DlgTemplateField::setAutofillContent (std::string content)
Definition at line 65 of file DlgTemplateField.cpp.
Referenced by TechDrawGui::TemplateTextField::mouseReleaseEvent().
setFieldContent()
void DlgTemplateField::setFieldContent (std::string content)
Definition at line 59 of file DlgTemplateField.cpp.
Referenced by execInsertPrefixChar(), and TechDrawGui::TemplateTextField::mouseReleaseEvent().
setFieldLength()
void DlgTemplateField::setFieldLength (int length)
Definition at line 54 of file DlgTemplateField.cpp.
Referenced by execInsertPrefixChar().
setFieldName()
void DlgTemplateField::setFieldName (std::string name)
Definition at line 48 of file DlgTemplateField.cpp.
Referenced by execInsertPrefixChar(), and TechDrawGui::TemplateTextField::mouseReleaseEvent().
The documentation for this class was generated from the following files:
DlgTemplateField.h
DlgTemplateField.cpp