FreeCAD: FCSphereSheetProjector Class Reference
FCSphereSheetProjector Class Reference
Public Types
enum OrbitStyle { Turntable, Trackball, FreeTurntable }
Public Member Functions
FCSphereSheetProjector (const SbSphere &sph, const SbBool orienttoeye=true)
void setViewVolume (const SbViewVolume &vol) override
void setWorkingSpace (const SbMatrix &space) override
SbVec3f project (const SbVec2f &point) override
SbRotation getRotation (const SbVec3f &point1, const SbVec3f &point2) override
void setOrbitStyle (OrbitStyle style)
OrbitStyle getOrbitStyle () const
Static Public Attributes
static constexpr float defaultSphereRadius = 0.8F
Detailed Description
Definition at line 57 of file NavigationStyle.cpp.
Member Enumeration Documentation
OrbitStyle
enum FCSphereSheetProjector::OrbitStyle
Enumerator
Turntable
Trackball
FreeTurntable
Definition at line 61 of file NavigationStyle.cpp.
Constructor & Destructor Documentation
FCSphereSheetProjector()
FCSphereSheetProjector::FCSphereSheetProjector (const SbSphere & sph, const SbBool orienttoeye = true) inline
Definition at line 69 of file NavigationStyle.cpp.
Member Function Documentation
getOrbitStyle()
OrbitStyle FCSphereSheetProjector::getOrbitStyle () const inline
Definition at line 108 of file NavigationStyle.cpp.
Referenced by Gui::NavigationStyle::operator=().
getRotation()
SbRotation FCSphereSheetProjector::getRotation (const SbVec3f & point1, const SbVec3f & point2) inline override
Definition at line 90 of file NavigationStyle.cpp.
References importers.importIFCHelper::getRotation().
project()
SbVec3f FCSphereSheetProjector::project (const SbVec2f & point) inline override
Definition at line 85 of file NavigationStyle.cpp.
References ifctree::project.
setOrbitStyle()
void FCSphereSheetProjector::setOrbitStyle (OrbitStyle style) inline
Definition at line 103 of file NavigationStyle.cpp.
Referenced by Gui::NavigationStyle::setOrbitStyle().
setViewVolume()
void FCSphereSheetProjector::setViewVolume (const SbViewVolume & vol) inline override
Definition at line 74 of file NavigationStyle.cpp.
setWorkingSpace()
void FCSphereSheetProjector::setWorkingSpace (const SbMatrix & space) inline override
Definition at line 79 of file NavigationStyle.cpp.
Member Data Documentation
defaultSphereRadius
constexpr float FCSphereSheetProjector::defaultSphereRadius = 0.8F static constexpr
Definition at line 67 of file NavigationStyle.cpp.
Referenced by Gui::NavigationStyle::initialize(), and Gui::NavigationStyle::spin().
The documentation for this class was generated from the following file:
NavigationStyle.cpp