FreeCAD: src.Mod.AddonManager.AddonManager Namespace Reference
src.Mod.AddonManager.AddonManager Namespace Reference
Classes
class CommandAddonManager
Functions
def QT_TRANSLATE_NOOP (_, txt)
QtGui.QIcon get_icon (Addon repo, bool update=False)
Variables
translate = FreeCAD.Qt.translate
INSTANCE = None
Function Documentation
get_icon()
QtGui.QIcon src.Mod.AddonManager.AddonManager.get_icon (Addon repo, bool update = False)
Returns an icon for an Addon. Uses a cached icon if possible, unless update is True,
in which case the icon is regenerated.
Definition at line 108 of file AddonManager.py.
References AssemblyImport.open().
Referenced by src.Mod.AddonManager.AddonManager.CommandAddonManager.add_addon_repo(), and src.Mod.AddonManager.AddonManager.CommandAddonManager.on_package_updated().
QT_TRANSLATE_NOOP()
def src.Mod.AddonManager.AddonManager.QT_TRANSLATE_NOOP (_, txt)
Definition at line 78 of file AddonManager.py.
Referenced by src.Mod.AddonManager.AddonManager.CommandAddonManager.__init__(), and src.Mod.AddonManager.AddonManager.CommandAddonManager.GetResources().
Variable Documentation
INSTANCE
src.Mod.AddonManager.AddonManager.INSTANCE = None
Definition at line 105 of file AddonManager.py.
translate
src.Mod.AddonManager.AddonManager.translate = FreeCAD.Qt.translate
Definition at line 75 of file AddonManager.py.