FreeCAD: SurfaceGui::FillingPanel Class Reference
SurfaceGui::FillingPanel Class Reference
#include <TaskFilling.h>
Classes
class ShapeSelection
Public Member Functions
FillingPanel (ViewProviderFilling *vp, Surface::Filling *obj)
~FillingPanel () override
void open ()
void checkOpenCommand ()
bool accept ()
bool reject ()
void setEditedObject (Surface::Filling *obj)
void appendButtons (Gui::ButtonGroup *)
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Public Member Functions inherited from Gui::DocumentObserver
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
void attachDocument (Document *)
void detachDocument ()
Protected Types
enum SelectionMode { None = SurfaceGui::SelectionMode::None, InitFace = SurfaceGui::SelectionMode::InitFace, AppendEdge = SurfaceGui::SelectionMode::AppendEdge, RemoveEdge = SurfaceGui::SelectionMode::RemoveEdge }
Protected Member Functions
void changeEvent (QEvent *e) override
void onSelectionChanged (const Gui::SelectionChanges &msg) override
void slotUndoDocument (const Gui::Document &Doc) override
void slotRedoDocument (const Gui::Document &Doc) override
void slotDeletedObject (const Gui::ViewProviderDocumentObject &Obj) override
void modifyBoundary (bool)
Protected Attributes
SelectionMode selectionMode
App::WeakPtrT< Surface::Filling > editedObject
bool checkCommand
Detailed Description
Definition at line 68 of file TaskFilling.h.
Member Enumeration Documentation
SelectionMode
enum SurfaceGui::FillingPanel::SelectionMode protected
Enumerator
None
InitFace
AppendEdge
RemoveEdge
Definition at line 74 of file TaskFilling.h.
Constructor & Destructor Documentation
FillingPanel()
SurfaceGui::FillingPanel::FillingPanel (ViewProviderFilling * vp, Surface::Filling * obj)
Definition at line 272 of file TaskFilling.cpp.
References Path.Post.scripts.dynapath_4060_post::action, checkCommand, draftgeoutils.intersections::connect(), None, selectionMode, and setEditedObject().
~FillingPanel()
SurfaceGui::FillingPanel::~FillingPanel () override
Definition at line 302 of file TaskFilling.cpp.
Member Function Documentation
accept()
bool SurfaceGui::FillingPanel::accept ()
Definition at line 477 of file TaskFilling.cpp.
References Surface::Filling::BoundaryEdges, SurfaceGui::ViewProviderFilling::Edge, editedObject, SurfaceGui::ViewProviderFilling::Face, App::DocumentObject::getStatusString(), App::PropertyLinkSubList::getSubListValues(), App::PropertyLinkSub::getSubValues(), App::PropertyLinkSub::getValue(), SurfaceGui::ViewProviderFilling::highlightReferences(), Surface::Filling::InitialFace, App::DocumentObject::isValid(), Surface::Filling::mustExecute(), None, App::DocumentObject::recomputeFeature(), Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), selectionMode, and Path.Log::warning().
Referenced by SurfaceGui::TaskFilling::accept().
appendButtons()
void SurfaceGui::FillingPanel::appendButtons (Gui::ButtonGroup * buttonGroup)
Definition at line 328 of file TaskFilling.cpp.
References SurfaceGui::AppendEdge, SurfaceGui::InitFace, and SurfaceGui::RemoveEdge.
Referenced by SurfaceGui::TaskFilling::TaskFilling().
changeEvent()
void SurfaceGui::FillingPanel::changeEvent (QEvent * e) override protected
Definition at line 402 of file TaskFilling.cpp.
References SCL.SimpleDataTypes::e.
checkOpenCommand()
void SurfaceGui::FillingPanel::checkOpenCommand ()
Definition at line 440 of file TaskFilling.cpp.
References checkCommand, editedObject, App::PropertyString::getValue(), Gui::Command::hasPendingCommand(), App::DocumentObject::Label, FreeCADInit::Msg, and Gui::Command::openCommand().
Referenced by onSelectionChanged(), and open().
modifyBoundary()
void SurfaceGui::FillingPanel::modifyBoundary (bool on) protected
Definition at line 917 of file TaskFilling.cpp.
onSelectionChanged()
void SurfaceGui::FillingPanel::onSelectionChanged (const Gui::SelectionChanges & msg) override protected virtual
Implements Gui::SelectionObserver.
Definition at line 644 of file TaskFilling.cpp.
References Gui::SelectionChanges::AddSelection, AppendEdge, Surface::Filling::BoundaryEdges, Surface::Filling::BoundaryFaces, Surface::Filling::BoundaryOrder, checkOpenCommand(), src.Mod.AddonManager.NetworkManager::count, SurfaceGui::ViewProviderFilling::Edge, editedObject, SurfaceGui::ViewProviderFilling::Face, Gui::SelectionObject::getObject(), App::PropertyLinkSubList::getSubListValues(), App::PropertyLinkSubList::getSubValues(), App::PropertyString::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyLinkSubList::getValues(), SurfaceGui::ViewProviderFilling::highlightReferences(), SplineSurface::i, InitFace, Surface::Filling::InitialFace, App::DocumentObject::Label, Path.Op.Surface::msg, None, importers.importIFCmulticore::objects, App::DocumentObject::recomputeFeature(), RemoveEdge, Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), selectionMode, App::PropertyLinkSub::setValue(), App::PropertyListsT< T, ListT, ParentT >::setValues(), App::PropertyStringList::setValues(), and App::PropertyLinkSubList::setValues().
open()
void SurfaceGui::FillingPanel::open ()
Definition at line 412 of file TaskFilling.cpp.
References Surface::Filling::BoundaryEdges, checkOpenCommand(), Gui::SelectionSingleton::clearSelection(), SurfaceGui::ViewProviderFilling::Edge, editedObject, SurfaceGui::ViewProviderFilling::Face, Part::PropertyPartShape::getShape(), App::PropertyLinkSubList::getSubListValues(), App::PropertyLinkSub::getSubValues(), App::PropertyLinkSub::getValue(), SurfaceGui::ViewProviderFilling::highlightReferences(), Surface::Filling::InitialFace, Part::TopoShape::isNull(), Gui::Selection(), and Part::Feature::Shape.
Referenced by SurfaceGui::TaskFilling::open().
reject()
bool SurfaceGui::FillingPanel::reject ()
Definition at line 505 of file TaskFilling.cpp.
References Surface::Filling::BoundaryEdges, SurfaceGui::ViewProviderFilling::Edge, editedObject, App::WeakPtrT< T >::expired(), SurfaceGui::ViewProviderFilling::Face, App::PropertyLinkSubList::getSubListValues(), App::PropertyLinkSub::getSubValues(), App::PropertyLinkSub::getValue(), SurfaceGui::ViewProviderFilling::highlightReferences(), Surface::Filling::InitialFace, None, Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), and selectionMode.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), SurfaceGui::TaskFilling::closed(), and SurfaceGui::TaskFilling::reject().
setEditedObject()
void SurfaceGui::FillingPanel::setEditedObject (Surface::Filling * obj)
Definition at line 336 of file TaskFilling.cpp.
References Gui::DocumentObserver::attachDocument(), Surface::Filling::BoundaryEdges, Surface::Filling::BoundaryFaces, Surface::Filling::BoundaryOrder, src.Mod.AddonManager.NetworkManager::count, toolbit-attributes::doc, editedObject, App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::PropertyLinkSub::getSubValues(), App::PropertyLinkSubList::getSubValues(), App::PropertyString::getValue(), App::PropertyLinkSub::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyLinkSubList::getValues(), SplineSurface::i, Surface::Filling::InitialFace, Gui::Application::Instance, App::DocumentObject::Label, and importers.importIFCmulticore::objects.
Referenced by FillingPanel(), and SurfaceGui::TaskFilling::setEditedObject().
slotDeletedObject()
void SurfaceGui::FillingPanel::slotDeletedObject (const Gui::ViewProviderDocumentObject & Obj) override protected virtual
Notifies when the object is about to be removed.
Reimplemented from Gui::DocumentObserver.
Definition at line 460 of file TaskFilling.cpp.
References Surface::Filling::BoundaryEdges, SurfaceGui::ViewProviderFilling::Edge, editedObject, SurfaceGui::ViewProviderFilling::Face, App::PropertyLinkSubList::getSubListValues(), App::PropertyLinkSub::getSubValues(), App::PropertyLinkSub::getValue(), SurfaceGui::ViewProviderFilling::highlightReferences(), and Surface::Filling::InitialFace.
slotRedoDocument()
void SurfaceGui::FillingPanel::slotRedoDocument (const Gui::Document & Doc) override protected virtual
Notifies on redo
Reimplemented from Gui::DocumentObserver.
Definition at line 455 of file TaskFilling.cpp.
References checkCommand.
slotUndoDocument()
void SurfaceGui::FillingPanel::slotUndoDocument (const Gui::Document & Doc) override protected virtual
Notifies on undo
Reimplemented from Gui::DocumentObserver.
Definition at line 450 of file TaskFilling.cpp.
References checkCommand.
Member Data Documentation
checkCommand
bool SurfaceGui::FillingPanel::checkCommand protected
Definition at line 83 of file TaskFilling.h.
Referenced by checkOpenCommand(), FillingPanel(), slotRedoDocument(), and slotUndoDocument().
editedObject
App::WeakPtrT<Surface::Filling> SurfaceGui::FillingPanel::editedObject protected
Definition at line 82 of file TaskFilling.h.
Referenced by accept(), checkOpenCommand(), onSelectionChanged(), open(), reject(), setEditedObject(), and slotDeletedObject().
selectionMode
SelectionMode SurfaceGui::FillingPanel::selectionMode protected
Definition at line 81 of file TaskFilling.h.
Referenced by accept(), FillingPanel(), onSelectionChanged(), and reject().
The documentation for this class was generated from the following files:
TaskFilling.h
TaskFilling.cpp