FreeCAD: FemGui::DlgSettingsFemCcxImp Class Reference
FemGui::DlgSettingsFemCcxImp Class Reference
#include <DlgSettingsFemCcxImp.h>
Public Member Functions
DlgSettingsFemCcxImp (QWidget *parent=nullptr)
~DlgSettingsFemCcxImp () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Slots
void onfileNameChanged (QString FileName)
Protected Member Functions
void saveSettings () override
void loadSettings () override
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
Definition at line 59 of file DlgSettingsFemCcxImp.h.
Constructor & Destructor Documentation
DlgSettingsFemCcxImp()
DlgSettingsFemCcxImp::DlgSettingsFemCcxImp (QWidget * parent = nullptr) explicit
Definition at line 40 of file DlgSettingsFemCcxImp.cpp.
References draftgeoutils.intersections::connect(), Gui::FileChooser::fileNameChanged(), FLOAT_MAX, and onfileNameChanged().
~DlgSettingsFemCcxImp()
DlgSettingsFemCcxImp::~DlgSettingsFemCcxImp () override default
Member Function Documentation
changeEvent()
void DlgSettingsFemCcxImp::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 135 of file DlgSettingsFemCcxImp.cpp.
References SCL.SimpleDataTypes::e.
loadSettings()
void DlgSettingsFemCcxImp::loadSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 89 of file DlgSettingsFemCcxImp.cpp.
References App::GetApplication(), ParameterGrp::GetInt(), and App::Application::GetParameterGroupByPath().
onfileNameChanged
void DlgSettingsFemCcxImp::onfileNameChanged (QString FileName) protected slot
Definition at line 147 of file DlgSettingsFemCcxImp.cpp.
Referenced by DlgSettingsFemCcxImp().
saveSettings()
void DlgSettingsFemCcxImp::saveSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 57 of file DlgSettingsFemCcxImp.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetInt().
The documentation for this class was generated from the following files:
DlgSettingsFemCcxImp.h
DlgSettingsFemCcxImp.cpp