FreeCAD: Gui::SoFCColorBarBase Class Reference
Gui::SoFCColorBarBase Class Reference abstract
#include <SoFCColorBar.h>
Public Member Functions
void GLRenderBelowPath (SoGLRenderAction *action) override
virtual void setRange (float fMin, float fMax, int prec=3)=0
App::Color getColor (float fVal) const override=0
virtual bool isVisible (float fVal) const =0
virtual void setOutsideGrayed (bool bVal)=0
virtual float getMinValue () const =0
virtual float getMaxValue () const =0
virtual void customize (SoFCColorBarBase *)=0
virtual void triggerChange (SoFCColorBarBase *base)
virtual const char * getColorBarName () const =0
virtual void setFormat (const SoLabelTextFormat &fmt)
SoLabelTextFormat getFormat () const
Static Public Member Functions
static void initClass ()
static void finish ()
Protected Member Functions
virtual void applyFormat (const SoLabelTextFormat &fmt)
float getBounds (const SbVec2s &size, float &fMinX, float &fMinY, float &fMaxX, float &fMaxY)
float getBoundingWidth (const SbVec2s &size)
virtual void setViewportSize (const SbVec2s &size)=0
void setModified ()
SoFCColorBarBase ()
~SoFCColorBarBase () override
Protected Member Functions inherited from App::ValueFloatToRGB
ValueFloatToRGB ()=default
virtual ~ValueFloatToRGB ()=default
Detailed Description
The abstract color bar base class to get most important information on how to convert a scalar to an RGB color.
Author
Werner Mayer
Definition at line 56 of file SoFCColorBar.h.
Constructor & Destructor Documentation
SoFCColorBarBase()
SoFCColorBarBase::SoFCColorBarBase () protected
Constructor.
Definition at line 49 of file SoFCColorBar.cpp.
~SoFCColorBarBase()
SoFCColorBarBase::~SoFCColorBarBase () override protected default
Destructor.
Member Function Documentation
applyFormat()
void SoFCColorBarBase::applyFormat (const SoLabelTextFormat & fmt) protected virtual
Applies the format to the label text
Reimplemented in Gui::SoFCColorGradient.
Definition at line 97 of file SoFCColorBar.cpp.
References Path.Post.scripts.comparams_post::fmt().
Referenced by setFormat().
customize()
virtual void Gui::SoFCColorBarBase::customize (SoFCColorBarBase *) pure virtual
Opens a dialog to customize the current settings of the color bar.
This method must be implemented in subclasses.
Implemented in Gui::SoFCColorBar, Gui::SoFCColorGradient, and Gui::SoFCColorLegend.
Referenced by Gui::SoFCColorBar::customize().
finish()
void SoFCColorBarBase::finish () static
Definition at line 65 of file SoFCColorBar.cpp.
Referenced by drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::accept(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::accept(), draftguitools.gui_split.Split::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_subelements.SubelementHighlight::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rotate.Rotate::action(), draftguitools.gui_fillets.Fillet::action(), draftguitools.gui_move.Move::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_arcs.Arc::action(), draftguitools.gui_texts.Text::action(), draftguitools.gui_scale.Scale::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_trimex.Trimex::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_styles.ApplyStyle::Activated(), draftguitools.gui_join.Join::Activated(), draftguitools.gui_draft2sketch.Draft2Sketch::Activated(), draftguitools.gui_downgrade.Downgrade::Activated(), draftguitools.gui_upgrade.Upgrade::Activated(), draftguitools.gui_shape2dview.Shape2DView::Activated(), draftguitools.gui_facebinders.Facebinder::Activated(), draftguitools.gui_subelements.SubelementHighlight::Activated(), draftguitools.gui_wire2spline.WireToBSpline::Activated(), draftguitools.gui_clone.Clone::Activated(), draftguitools.gui_dimensions.Dimension::Activated(), draftguitools.gui_edit.Edit::Activated(), draftguitools.gui_selectplane.Draft_SelectPlane::check_selection(), DraftGui.DraftToolBar::checkSpecialChars(), draftguitools.gui_points.Point::click(), draftguitools.gui_orthoarray.OrthoArray::completed(), draftguitools.gui_polararray.PolarArray::completed(), draftguitools.gui_circulararray.CircularArray::completed(), draftguitools.gui_labels.Label::create(), bimcommands.BimText.BIM_Text::createObject(), draftguitools.gui_rectangles.Rectangle::createObject(), draftguitools.gui_ellipses.Ellipse::createObject(), draftguitools.gui_texts.Text::createObject(), draftviewproviders.view_text.ViewProviderText::createObject(), draftguitools.gui_stretch.Stretch::doStretch(), draftguitools.gui_fillets.Fillet::draw_arc(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), DraftGui.DraftToolBar::editUi(), DraftGui.DraftToolBar::escape(), Gui::SoFCDB::finish(), draftguitools.gui_move.Move::get_object_selection(), draftguitools.gui_rotate.Rotate::get_object_selection(), draftguitools.gui_scale.Scale::get_object_selection(), draftguitools.gui_arcs.Arc_3Points::getPoint(), draftguitools.gui_edit.Edit::keyPressed(), draftguitools.gui_dimensions.Dimension::numericInput(), draftguitools.gui_offset.Offset::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), draftguitools.gui_trimex.Trimex::numericRadius(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_align(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_auto(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_center(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_front(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_move(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_next(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_previous(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_side(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_top(), bimcommands.BimShape2DView.BIM_Shape2DView::proceed(), draftguitools.gui_join.Join::proceed(), draftguitools.gui_subelements.SubelementHighlight::proceed(), draftguitools.gui_draft2sketch.Draft2Sketch::proceed(), draftguitools.gui_downgrade.Downgrade::proceed(), bimcommands.BimSlab.BIM_Slab::proceed(), draftguitools.gui_upgrade.Upgrade::proceed(), draftguitools.gui_facebinders.Facebinder::proceed(), draftguitools.gui_pathtwistedarray.PathTwistedArray::proceed(), draftguitools.gui_shape2dview.Shape2DView::proceed(), draftguitools.gui_clone.Clone::proceed(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_pointarray.PointArray::proceed(), draftguitools.gui_patharray.PathArray::proceed(), draftguitools.gui_trimex.Trimex::proceed(), draftguitools.gui_edit.Edit::proceed(), draftguitools.gui_selectplane.Draft_SelectPlane::reject(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::reject(), drafttaskpanels.task_polararray.TaskPanelPolarArray::reject(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::reject(), and draftguitools.gui_edit.Edit::setTrackers().
getBoundingWidth()
float SoFCColorBarBase::getBoundingWidth (const SbVec2s & size) protected
Returns the width of the color bar and labels
Computes the occupied width of the color bar and its labels. It therefore determines the bounding box.
Definition at line 102 of file SoFCColorBar.cpp.
References MengerSponge::box, SCL.SimpleDataTypes::f, and toolbit-attributes::group.
Referenced by getBounds().
getBounds()
float SoFCColorBarBase::getBounds (const SbVec2s & size, float & fMinX, float & fMinY, float & fMaxX, float & fMaxY) protected
Computes the dimensions of the color bar and labels in coordinates with respect to the defined height of the camera. Returns the width of the bounding box
Definition at line 134 of file SoFCColorBar.cpp.
References SCL.SimpleDataTypes::f, and getBoundingWidth().
Referenced by Gui::SoFCColorLegend::setViewportSize(), and Gui::SoFCColorGradient::setViewportSize().
getColor()
App::Color Gui::SoFCColorBarBase::getColor (float fVal) const override pure virtual
Returns the associated color to the value fVal.
This method must be implemented in subclasses.
Implements App::ValueFloatToRGB.
Implemented in Gui::SoFCColorBar, Gui::SoFCColorGradient, and Gui::SoFCColorLegend.
Referenced by Gui::SoFCColorBar::getColor(), and draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::setValues().
getColorBarName()
virtual const char* Gui::SoFCColorBarBase::getColorBarName () const pure virtual
Returns the name of the color bar.
This method must be implemented in subclasses.
Implemented in Gui::SoFCColorBar, Gui::SoFCColorGradient, and Gui::SoFCColorLegend.
getFormat()
SoLabelTextFormat SoFCColorBarBase::getFormat () const
Returns the format for the label text.
Definition at line 92 of file SoFCColorBar.cpp.
getMaxValue()
virtual float Gui::SoFCColorBarBase::getMaxValue () const pure virtual
Returns the current maximum of the parameter range.
This method must be implemented in subclasses.
Implemented in Gui::SoFCColorBar, Gui::SoFCColorGradient, and Gui::SoFCColorLegend.
Referenced by Gui::SoFCColorBar::getMaxValue().
getMinValue()
virtual float Gui::SoFCColorBarBase::getMinValue () const pure virtual
Returns the current minimum of the parameter range.
This method must be implemented in subclasses.
Implemented in Gui::SoFCColorBar, Gui::SoFCColorGradient, and Gui::SoFCColorLegend.
Referenced by Gui::SoFCColorBar::getMinValue().
GLRenderBelowPath()
void SoFCColorBarBase::GLRenderBelowPath (SoGLRenderAction * action) override
Definition at line 70 of file SoFCColorBar.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and setViewportSize().
initClass()
void SoFCColorBarBase::initClass () static
Definition at line 60 of file SoFCColorBar.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
isVisible()
virtual bool Gui::SoFCColorBarBase::isVisible (float fVal) const pure virtual
Returns always true if the color bar is in mode to show colors to arbitrary values of fVal, otherwise true is returned if fVal is within the specified parameter range, if not false is returned.
This method must be implemented in subclasses.
Implemented in Gui::SoFCColorLegend, Gui::SoFCColorBar, and Gui::SoFCColorGradient.
Referenced by Gui::SoFCColorBar::isVisible(), and ArchVRM.Renderer::removeHidden().
setFormat()
void SoFCColorBarBase::setFormat (const SoLabelTextFormat & fmt) virtual
Sets the format for the label text.
Reimplemented in Gui::SoFCColorBar.
Definition at line 86 of file SoFCColorBar.cpp.
References applyFormat(), and Path.Post.scripts.comparams_post::fmt().
Referenced by Path.Main.Gui.Inspect.GCodeHighlighter::highlightBlock(), and Path.Post.Utils.GCodeHighlighter::highlightBlock().
setModified()
void SoFCColorBarBase::setModified () protected
Mark the object as modified.
Definition at line 81 of file SoFCColorBar.cpp.
Referenced by Gui::SoFCColorLegend::setLegendLabels().
setOutsideGrayed()
virtual void Gui::SoFCColorBarBase::setOutsideGrayed (bool bVal) pure virtual
Sets whether values outside the range should be in gray,
This method must be implemented in subclasses.
Implemented in Gui::SoFCColorBar, Gui::SoFCColorGradient, and Gui::SoFCColorLegend.
setRange()
virtual void Gui::SoFCColorBarBase::setRange (float fMin, float fMax, int prec = 3) pure virtual
Sets the range of the colorbar from the maximum fMax to the minimum fMin. prec indicates the post decimal positions, prec should be in between 0 and 6.
This method must be implemented in subclasses.
Implemented in Gui::SoFCColorBar, Gui::SoFCColorGradient, and Gui::SoFCColorLegend.
setViewportSize()
virtual void Gui::SoFCColorBarBase::setViewportSize (const SbVec2s & size) protected pure virtual
Sets the current viewer size to recalculate the new position.
This method must be implemented in subclasses.
Implemented in Gui::SoFCColorBar, Gui::SoFCColorGradient, and Gui::SoFCColorLegend.
Referenced by GLRenderBelowPath().
triggerChange()
virtual void Gui::SoFCColorBarBase::triggerChange (SoFCColorBarBase * base) inline virtual
Forward a triggered change
Reimplemented in Gui::SoFCColorBar.
Definition at line 113 of file SoFCColorBar.h.
Referenced by Gui::SoFCColorGradient::customize().
The documentation for this class was generated from the following files:
SoFCColorBar.h
SoFCColorBar.cpp