FreeCAD: Gui::GLFlagWindow Class Reference
Gui::GLFlagWindow Class Reference
#include <Flag.h>
Public Member Functions
GLFlagWindow (View3DInventorViewer *)
~GLFlagWindow () override
void addFlag (Flag *item, FlagLayout::Position pos)
void removeFlag (Flag *item)
void deleteFlags ()
Flag * getFlag (int) const
int countFlags () const
void paintGL () override
Public Member Functions inherited from Gui::GLGraphicsItem
GLGraphicsItem ()=default
~GLGraphicsItem () override=default
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 133 of file Flag.h.
Constructor & Destructor Documentation
GLFlagWindow()
GLFlagWindow::GLFlagWindow (View3DInventorViewer * view)
Definition at line 334 of file Flag.cpp.
~GLFlagWindow()
GLFlagWindow::~GLFlagWindow () override
Definition at line 338 of file Flag.cpp.
References deleteFlags().
Member Function Documentation
addFlag()
void GLFlagWindow::addFlag (Flag * item, FlagLayout::Position pos)
Definition at line 361 of file Flag.cpp.
References Gui::FlagLayout::addWidget(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), and RobotExample::pos.
Referenced by InspectionGui::ViewProviderProxyObject::addFlag(), and MeshGui::ViewProviderMesh::faceInfoCallback().
countFlags()
int GLFlagWindow::countFlags () const
Definition at line 391 of file Flag.cpp.
References Gui::FlagLayout::count().
deleteFlags()
void GLFlagWindow::deleteFlags ()
Definition at line 345 of file Flag.cpp.
References Gui::FlagLayout::count(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), SplineSurface::i, and Gui::FlagLayout::itemAt().
Referenced by ~GLFlagWindow().
getFlag()
Flag * GLFlagWindow::getFlag (int index) const
Definition at line 382 of file Flag.cpp.
References Gui::FlagLayout::itemAt().
paintGL()
void GLFlagWindow::paintGL () override virtual
Implements Gui::GLGraphicsItem.
Definition at line 400 of file Flag.cpp.
References Gui::FlagLayout::count(), Gui::Flag::drawLine(), SCL.SimpleDataTypes::f, Gui::Flag::getOrigin(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), SplineSurface::i, and Gui::FlagLayout::itemAt().
removeFlag()
void GLFlagWindow::removeFlag (Flag * item)
Definition at line 374 of file Flag.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager().
The documentation for this class was generated from the following files:
Flag.h
Flag.cpp