FreeCAD: nativeifc.ifc_types Namespace Reference
nativeifc.ifc_types Namespace Reference
Functions
def show_type (obj)
def is_typable (obj)
def convert_to_type (obj, keep_object=False)
def edit_type (obj)
Variables
translate = FreeCAD.Qt.translate
Function Documentation
convert_to_type()
def nativeifc.ifc_types.convert_to_type (obj, keep_object = False)
Converts an object to a type. If keep_object is
True, the original object is kept (and adopts the new type).
Definition at line 66 of file ifc_types.py.
References importDXF.addObject(), and nativeifc.ifc_types.is_typable().
edit_type()
def nativeifc.ifc_types.edit_type (obj)
Edits the type of this object
Definition at line 96 of file ifc_types.py.
is_typable()
def nativeifc.ifc_types.is_typable (obj)
Checks if an object can become a type
Definition at line 49 of file ifc_types.py.
Referenced by nativeifc.ifc_types.convert_to_type().
show_type()
def nativeifc.ifc_types.show_type (obj)
Adds the types of that object as FreeCAD objects
Definition at line 32 of file ifc_types.py.
References importDXF.addObject().
Variable Documentation
translate
nativeifc.ifc_types.translate = FreeCAD.Qt.translate
Definition at line 29 of file ifc_types.py.