FreeCAD: Command.cpp File Reference
Mod/Sandbox/Gui/Command.cpp File Reference
#include "PreCompiled.h"
#include <QApplication>
#include <QCalendarWidget>
#include <QColorDialog>
#include <QCryptographicHash>
#include <QObject>
#include <QEventLoop>
#include <QFontMetrics>
#include <QFuture>
#include <QFutureWatcher>
#include <QtConcurrentMap>
#include <QLabel>
#include <QInputDialog>
#include <QMessageBox>
#include <QTimer>
#include <QImage>
#include <QImageReader>
#include <QPainter>
#include <QPainterPath>
#include <QThread>
#include <Inventor/nodes/SoAnnotation.h>
#include <Inventor/nodes/SoImage.h>
#include <Inventor/nodes/SoCone.h>
#include <cmath>
#include <boost/thread/thread.hpp>
#include <boost/thread/mutex.hpp>
#include <boost/thread/condition_variable.hpp>
#include <boost/thread/future.hpp>
#include <boost/bind/bind.hpp>
#include <memory>
#include <Base/Console.h>
#include <Base/Sequencer.h>
#include <App/Application.h>
#include <App/Document.h>
#include <Gui/Application.h>
#include <Gui/BitmapFactory.h>
#include <Gui/Command.h>
#include <Gui/MainWindow.h>
#include <Gui/FileDialog.h>
#include <Gui/Tools.h>
#include <Gui/View3DInventor.h>
#include <Gui/View3DInventorViewer.h>
#include <Gui/WaitCursor.h>
#include <Mod/Sandbox/App/DocumentThread.h>
#include <Mod/Sandbox/App/DocumentProtector.h>
#include <Mod/Mesh/App/MeshFeature.h>
#include <Mod/Mesh/App/Core/Degeneration.h>
#include "Workbench.h"
#include "GLGraphicsView.h"
#include "TaskPanelView.h"
Classes
class CmdSandboxEventLoop
class CmdSandboxMeshLoader
struct MeshObject_greater
class MeshTestJob
class MeshThread
class RenderArea
struct Param
Namespaces
Mesh
The namespace of the Mesh Application layer library.
Typedefs
typedef Base::Reference< const MeshObject > Mesh::MeshObjectConstRef
typedef std::list< MeshObjectConstRef > Mesh::MeshObjectConstRefList
typedef std::vector< MeshObjectConstRef > Mesh::MeshObjectConstRefArray
typedef Base::Reference< Mesh::MeshObject > MeshObjectRef
Functions
Base::Reference< Mesh::MeshObject > loadMesh (const QString &s)
MeshObjectRef PlaceBox (float x, float y, float z)
MeshObjectRef Sierpinski (int level, float x0, float y0, float z0)
MeshObjectRef runSierpinski (const Param &p)
MeshObjectRef makeParallelMengerSponge (int level, float x0, float y0, float z0)
void CreateSandboxCommands ()
Variables
MeshObjectRef globalBox
Typedef Documentation
MeshObjectRef
typedef Base::Reference<Mesh::MeshObject> MeshObjectRef
Definition at line 1228 of file Mod/Sandbox/Gui/Command.cpp.
Function Documentation
CreateSandboxCommands()
void CreateSandboxCommands ()
Definition at line 1424 of file Mod/Sandbox/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
loadMesh()
Base::Reference<Mesh::MeshObject> loadMesh (const QString & s)
Definition at line 608 of file Mod/Sandbox/Gui/Command.cpp.
References Mesh2Shape::mesh, and toolbit-attributes::s.
makeParallelMengerSponge()
MeshObjectRef makeParallelMengerSponge (int level, float x0, float y0, float z0)
Definition at line 1286 of file Mod/Sandbox/Gui/Command.cpp.
References toolbit-attributes::args, draftgeoutils.intersections::connect(), SCL.SimpleDataTypes::f, SplineSurface::i, level(), Mesh2Shape::mesh, Base::pow(), and runSierpinski().
PlaceBox()
MeshObjectRef PlaceBox (float x, float y, float z)
Definition at line 1233 of file Mod/Sandbox/Gui/Command.cpp.
References globalBox, test::m, Mesh2Shape::mesh, MovieTool::x, and MovieTool::y.
Referenced by Sierpinski().
runSierpinski()
MeshObjectRef runSierpinski (const Param & p)
Definition at line 1281 of file Mod/Sandbox/Gui/Command.cpp.
References buildPsets::p, and Sierpinski().
Referenced by makeParallelMengerSponge().
Sierpinski()
MeshObjectRef Sierpinski (int level, float x0, float y0, float z0)
Definition at line 1242 of file Mod/Sandbox/Gui/Command.cpp.
References SCL.SimpleDataTypes::f, SplineSurface::i, level(), Mesh2Shape::mesh, PlaceBox(), and Base::pow().
Referenced by runSierpinski().
Variable Documentation
globalBox
MeshObjectRef globalBox
Definition at line 1230 of file Mod/Sandbox/Gui/Command.cpp.
Referenced by PlaceBox().