FreeCAD: TechDrawGui::QGIMatting Class Reference
TechDrawGui::QGIMatting Class Reference
#include <QGIMatting.h>
Public Types
enum { Type = QGraphicsItem::UserType + 205 }
Public Member Functions
QGIMatting ()
~QGIMatting () override
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QRectF boundingRect () const override
virtual void setSize (double w, double h)
virtual void setRadius (double r)
virtual void draw ()
Protected Member Functions
int getHoleStyle ()
Protected Attributes
double m_height
double m_width
double m_radius
double m_fudge
QGraphicsPathItem * m_border
QGraphicsPathItem * m_mat
Detailed Description
Definition at line 44 of file QGIMatting.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 50 of file QGIMatting.h.
Constructor & Destructor Documentation
QGIMatting()
QGIMatting::QGIMatting () explicit
Definition at line 43 of file QGIMatting.cpp.
References m_border, m_mat, and ZVALUE::MATTING.
~QGIMatting()
TechDrawGui::QGIMatting::~QGIMatting () inline override
Definition at line 48 of file QGIMatting.h.
Member Function Documentation
boundingRect()
QRectF QGIMatting::boundingRect () const override
Definition at line 112 of file QGIMatting.cpp.
draw()
void QGIMatting::draw () virtual
Definition at line 74 of file QGIMatting.cpp.
References TechDraw::LineGroup::getDefaultWidth(), getHoleStyle(), TechDrawGui::Rez::guiX(), m_border, m_fudge, m_mat, m_radius, and ZVALUE::MATTING.
Referenced by TechDrawGui::QGIViewPart::drawMatting().
getHoleStyle()
int QGIMatting::getHoleStyle () protected
Definition at line 106 of file QGIMatting.cpp.
References TechDraw::Preferences::mattingStyle().
Referenced by draw().
paint()
void QGIMatting::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 117 of file QGIMatting.cpp.
setRadius()
virtual void TechDrawGui::QGIMatting::setRadius (double r) inline virtual
Definition at line 58 of file QGIMatting.h.
Referenced by TechDrawGui::QGIViewPart::drawMatting().
setSize()
virtual void TechDrawGui::QGIMatting::setSize (double w, double h) inline virtual
Definition at line 56 of file QGIMatting.h.
References src.Mod.PartDesign.fcgear.svggear::w.
type()
int TechDrawGui::QGIMatting::type () const inline override
Definition at line 51 of file QGIMatting.h.
Member Data Documentation
m_border
QGraphicsPathItem* TechDrawGui::QGIMatting::m_border protected
Definition at line 68 of file QGIMatting.h.
Referenced by draw(), and QGIMatting().
m_fudge
double TechDrawGui::QGIMatting::m_fudge protected
Definition at line 65 of file QGIMatting.h.
Referenced by draw().
m_height
double TechDrawGui::QGIMatting::m_height protected
Definition at line 62 of file QGIMatting.h.
m_mat
QGraphicsPathItem* TechDrawGui::QGIMatting::m_mat protected
Definition at line 69 of file QGIMatting.h.
Referenced by draw(), and QGIMatting().
m_radius
double TechDrawGui::QGIMatting::m_radius protected
Definition at line 64 of file QGIMatting.h.
Referenced by draw().
m_width
double TechDrawGui::QGIMatting::m_width protected
Definition at line 63 of file QGIMatting.h.
The documentation for this class was generated from the following files:
QGIMatting.h
QGIMatting.cpp