FreeCAD: MeshCore::MeshCurvature Class Reference
MeshCore::MeshCurvature Class Reference
#include <Curvature.h>
Public Member Functions
MeshCurvature (const MeshKernel &kernel)
MeshCurvature (const MeshKernel &kernel, std::vector< FacetIndex > segm)
float GetRadius () const
void SetRadius (float r)
void ComputePerFace (bool parallel)
void ComputePerVertex ()
const std::vector< CurvatureInfo > & GetCurvature () const
Detailed Description
Definition at line 79 of file Curvature.h.
Constructor & Destructor Documentation
MeshCurvature() [1/2]
MeshCurvature::MeshCurvature (const MeshKernel & kernel) explicit
Definition at line 53 of file Curvature.cpp.
References MeshCore::MeshKernel::CountFacets(), and Path.Base.Generator.dogboneII::generate().
MeshCurvature() [2/2]
MeshCurvature::MeshCurvature (const MeshKernel & kernel, std::vector< FacetIndex > segm)
Definition at line 62 of file Curvature.cpp.
Member Function Documentation
ComputePerFace()
void MeshCurvature::ComputePerFace (bool parallel)
Definition at line 69 of file Curvature.cpp.
References draftgeoutils.faces::bind(), MeshCore::FacetCurvature::Compute(), Path.Log::info(), and Base::SequencerLauncher::next().
ComputePerVertex()
void MeshCurvature::ComputePerVertex ()
Definition at line 292 of file Curvature.cpp.
References MeshCore::CurvatureInfo::cMaxCurvDir, MeshCore::CurvatureInfo::cMinCurvDir, MeshCore::MeshKernel::CountFacets(), MeshCore::MeshKernel::CountPoints(), MeshCore::CurvatureInfo::fMaxCurvature, MeshCore::CurvatureInfo::fMinCurvature, MeshCore::MeshKernel::GetFacets(), Wm4::MeshCurvature< Real >::GetMaxCurvatures(), Wm4::MeshCurvature< Real >::GetMaxDirections(), Wm4::MeshCurvature< Real >::GetMinCurvatures(), Wm4::MeshCurvature< Real >::GetMinDirections(), SplineSurface::i, MeshCore::MeshPointIterator::Init(), MeshCore::MeshPointIterator::More(), MeshCore::MeshPointIterator::Next(), Base::Vector3< double >, DrawingExample::X, Base::Vector3< float_type >::x, DrawingExample::Y, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by MeshGui::Segmentation::accept(), ReverseEngineeringGui::Segmentation::accept(), and Mesh::Curvature::execute().
GetCurvature()
const std::vector<CurvatureInfo>& MeshCore::MeshCurvature::GetCurvature () const inline
Definition at line 94 of file Curvature.h.
Referenced by MeshGui::Segmentation::accept(), ReverseEngineeringGui::Segmentation::accept(), and Mesh::Curvature::execute().
GetRadius()
float MeshCore::MeshCurvature::GetRadius () const inline
Definition at line 84 of file Curvature.h.
SetRadius()
void MeshCore::MeshCurvature::SetRadius (float r) inline
Definition at line 88 of file Curvature.h.
The documentation for this class was generated from the following files:
Curvature.h
Curvature.cpp