FreeCAD: Gui::FileChooser Class Reference
Gui::FileChooser Class Reference
#include <FileDialog.h>
Public Types
enum Mode { File, Directory }
enum AcceptMode { AcceptOpen, AcceptSave }
Public Slots
virtual void setFileName (const QString &fn)
virtual void setMode (Gui::FileChooser::Mode m)
virtual void setFilter (const QString &)
virtual void setButtonText (const QString &)
Signals
void fileNameChanged (const QString &)
void fileNameSelected (const QString &)
void filterChanged (const QString &)
void buttonTextChanged (const QString &)
void modeChanged (Gui::FileChooser::Mode)
void acceptModeChanged (Gui::FileChooser::AcceptMode)
Public Member Functions
FileChooser (QWidget *parent=nullptr)
~FileChooser () override
QString filter () const
QString fileName () const
Mode mode () const
QString buttonText () const
void setAcceptMode (AcceptMode mode)
AcceptMode acceptMode () const
Protected Member Functions
void resizeEvent (QResizeEvent *) override
Properties
Mode mode
AcceptMode acceptMode
QString fileName
QString filter
QString buttonText
Detailed Description
The FileChooser class provides a lineedit with a button on the right side to specify a file or directory.
Author
Werner Mayer
Definition at line 154 of file FileDialog.h.
Member Enumeration Documentation
AcceptMode
enum Gui::FileChooser::AcceptMode
Enumerator
AcceptOpen
AcceptSave
Definition at line 160 of file FileDialog.h.
Mode
enum Gui::FileChooser::Mode
Enumerator
File
Directory
Definition at line 159 of file FileDialog.h.
Constructor & Destructor Documentation
FileChooser()
FileChooser::FileChooser (QWidget * parent = nullptr) explicit
Constructs a file chooser called name with the parent parent.
Definition at line 662 of file FileDialog.cpp.
References draftgeoutils.intersections::connect(), and fileNameChanged().
~FileChooser()
FileChooser::~FileChooser () override default
Member Function Documentation
acceptMode()
AcceptMode Gui::FileChooser::acceptMode () const inline
Returns the accept mode.
Definition at line 202 of file FileDialog.h.
acceptModeChanged
void Gui::FileChooser::acceptModeChanged (Gui::FileChooser::AcceptMode) signal
Referenced by setAcceptMode().
buttonText()
QString Gui::FileChooser::buttonText () const
Returns the button's text.
buttonTextChanged
void Gui::FileChooser::buttonTextChanged (const QString &) signal
Referenced by setButtonText().
fileName()
QString Gui::FileChooser::fileName () const
Returns the filename.
fileNameChanged
void Gui::FileChooser::fileNameChanged (const QString &) signal
Referenced by MatGui::BaseDelegate::createWidget(), FemGui::DlgSettingsFemCcxImp::DlgSettingsFemCcxImp(), FemGui::DlgSettingsFemElmerImp::DlgSettingsFemElmerImp(), FemGui::DlgSettingsFemGmshImp::DlgSettingsFemGmshImp(), FemGui::DlgSettingsFemMystranImp::DlgSettingsFemMystranImp(), FemGui::DlgSettingsFemZ88Imp::DlgSettingsFemZ88Imp(), and FileChooser().
fileNameSelected
void Gui::FileChooser::fileNameSelected (const QString &) signal
Referenced by Gui::PropertyEditor::PropertyFileItem::createEditor(), Gui::PropertyEditor::PropertyPathItem::createEditor(), Gui::PropertyEditor::PropertyTransientFileItem::createEditor(), MatGui::BaseDelegate::createWidget(), and Gui::Dialog::TextureMapping::TextureMapping().
filter()
QString Gui::FileChooser::filter () const
Returns the set filter.
filterChanged
void Gui::FileChooser::filterChanged (const QString &) signal
Referenced by setFilter().
mode()
Mode Gui::FileChooser::mode () const
Returns true if this widgets is set to choose a file, if it is set to choose false is returned.
modeChanged
void Gui::FileChooser::modeChanged (Gui::FileChooser::Mode) signal
Referenced by setMode().
resizeEvent()
void FileChooser::resizeEvent (QResizeEvent * e) override protected
Definition at line 700 of file FileDialog.cpp.
References SCL.SimpleDataTypes::e.
setAcceptMode()
void FileChooser::setAcceptMode (FileChooser::AcceptMode mode)
Sets the accept mode.
Definition at line 773 of file FileDialog.cpp.
References acceptModeChanged(), and mode.
setButtonText
void FileChooser::setButtonText (const QString & txt) virtual slot
Sets the browse button's text to txt.
Definition at line 827 of file FileDialog.cpp.
References buttonTextChanged(), Gui::QtTools::horizontalAdvance(), and create_qrc::txt.
setFileName
void FileChooser::setFileName (const QString & fn) virtual slot
Sets the file name fn.
Definition at line 730 of file FileDialog.cpp.
Referenced by Gui::PrefFileChooser::restorePreferences(), and MatGui::BaseDelegate::setEditorData().
setFilter
void FileChooser::setFilter (const QString & filter) virtual slot
Sets the filter for choosing a file.
Definition at line 818 of file FileDialog.cpp.
References filter, and filterChanged().
setMode
void FileChooser::setMode (Gui::FileChooser::Mode m) virtual slot
If m is File the widget is set to choose a file, otherwise it is set to choose a directory.
Definition at line 796 of file FileDialog.cpp.
References test::m, and modeChanged().
Property Documentation
acceptMode
AcceptMode Gui::FileChooser::acceptMode read write
Definition at line 165 of file FileDialog.h.
buttonText
QString FileChooser::buttonText read write
Returns the browse button's text.
Definition at line 168 of file FileDialog.h.
fileName
QString FileChooser::fileName read write
This property holds the file name. Set this property's value with setFileName() and get this property's value with fileName().
See also
fileName(), setFileName().
Definition at line 166 of file FileDialog.h.
Referenced by Gui::PrefFileChooser::restorePreferences(), Gui::PrefFileChooser::savePreferences(), MatGui::BaseDelegate::setModelData(), parttests.ColorPerFaceTest.ColorPerFaceTest::testBox(), parttests.ColorPerFaceTest.ColorPerFaceTest::testBoxAndLink(), parttests.TopoShapeListTest.TopoShapeListTest::testMakeTopoShapeList(), parttests.ColorPerFaceTest.ColorPerFaceTest::testMultiFuseSaveRestore(), and TestImportGui.ExportImportTest::testSaveLoadStepFile().
filter
QString FileChooser::filter read write
This property holds the set filter to choose a file. This property is used only if FileChooser::Mode is set to File.
See also
chooseFile(), filter(), setFilter().
Definition at line 167 of file FileDialog.h.
Referenced by setFilter().
mode
FileChooser::Mode FileChooser::mode read write
This property holds whether the widgets selects either a file or a directory. The default value of chooseFile is set to File.
See also
chooseFile(), mode(), setMode().
Definition at line 163 of file FileDialog.h.
Referenced by femtaskpanels.task_constraint_bodyheatsource._TaskPanel::accept(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_lines.Line::Activated(), draftguitools.gui_lines.Line::drawSegment(), Commands.SphereCreator::enter(), Commands.SphereCreator::leave(), femtaskpanels.task_constraint_bodyheatsource._TaskPanel::mode_changed(), draftguitools.gui_offset.Offset::numericRadius(), setAcceptMode(), and draftguitools.gui_trackers.archDimTracker::setString().
The documentation for this class was generated from the following files:
FileDialog.h
FileDialog.cpp