FreeCAD: MeshInfoWatcher Class Reference
MeshInfoWatcher Class Reference
Public Member Functions
MeshInfoWatcher ()
bool shouldShow () override
is called wenn the document or the Selection changes.
void onSelectionChanged (const Gui::SelectionChanges &) override
Public Member Functions inherited from Gui::TaskView::TaskWatcher
TaskWatcher (const char *Filter)
~TaskWatcher () override
QWidget * addTaskBox (QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBox (const QPixmap &icon, QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBoxWithoutHeader (QWidget *widget)
std::vector< QWidget * > & getWatcherContent ()
Public Member Functions inherited from Gui::SelectionFilter
SelectionFilter (const char *filter)
SelectionFilter (const std::string &filter)
virtual ~SelectionFilter ()
void setFilter (const char *filter)
Set a new filter string.
const std::string & getFilter () const
bool match ()
bool test (App::DocumentObject *pObj, const char *sSubName)
void addError (const char *e)
bool isValid () const
true if a valid filter is set
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Additional Inherited Members
Public Attributes inherited from Gui::SelectionFilter
std::vector< std::vector< SelectionObject > > Result
Protected Member Functions inherited from Gui::SelectionFilter
bool parse ()
Protected Attributes inherited from Gui::TaskView::TaskWatcher
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
Protected Attributes inherited from Gui::SelectionFilter
std::string Filter
std::string Errors
std::shared_ptr< Node_Block > Ast
Detailed Description
Definition at line 60 of file Mod/Mesh/Gui/Workbench.cpp.
Constructor & Destructor Documentation
MeshInfoWatcher()
MeshInfoWatcher::MeshInfoWatcher () inline
Definition at line 63 of file Mod/Mesh/Gui/Workbench.cpp.
References MengerSponge::box, and Plot::grid().
Member Function Documentation
onSelectionChanged()
void MeshInfoWatcher::onSelectionChanged (const Gui::SelectionChanges &) inline override virtual
Implements Gui::SelectionObserver.
Definition at line 107 of file Mod/Mesh/Gui/Workbench.cpp.
References Base::BoundBox3< Precision >::Add(), Mesh::MeshObject::countPoints(), Gui::SelectionSingleton::getObjectsOfType(), Mesh::PropertyMeshKernel::getValue(), Base::BoundBox3< Precision >::MaxX, Base::BoundBox3< Precision >::MaxY, Base::BoundBox3< Precision >::MaxZ, Mesh2Shape::mesh, Mesh::Feature::Mesh, Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, Base::BoundBox3< Precision >::MinZ, and Gui::Selection().
shouldShow()
bool MeshInfoWatcher::shouldShow () inline override virtual
is called wenn the document or the Selection changes.
Reimplemented from Gui::TaskView::TaskWatcher.
Definition at line 103 of file Mod/Mesh/Gui/Workbench.cpp.
The documentation for this class was generated from the following file:
Mod/Mesh/Gui/Workbench.cpp