FreeCAD: Gui::NotificationArea::ParameterObserver Class Reference
Gui::NotificationArea::ParameterObserver Class Reference
#include <NotificationArea.h>
Public Member Functions
ParameterObserver (NotificationArea *notificationarea)
~ParameterObserver () override
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
Detailed Description
Definition at line 69 of file NotificationArea.h.
Constructor & Destructor Documentation
ParameterObserver()
NotificationArea::ParameterObserver::ParameterObserver (NotificationArea * notificationarea) explicit
Definition at line 751 of file NotificationArea.cpp.
References Base::Subject< MsgType >::Attach(), App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), and toolbit-attributes::val.
~ParameterObserver()
NotificationArea::ParameterObserver::~ParameterObserver () override
Definition at line 843 of file NotificationArea.cpp.
Member Function Documentation
OnChange()
void NotificationArea::ParameterObserver::OnChange (Base::Subject< const char * > & rCaller, const char * sReason) override
Definition at line 848 of file NotificationArea.cpp.
The documentation for this class was generated from the following files:
NotificationArea.h
NotificationArea.cpp