FreeCAD: Gui::DockWindowItems Class Reference
Gui::DockWindowItems Class Reference
#include <DockWindowManager.h>
Public Member Functions
DockWindowItems ()
~DockWindowItems ()
void addDockWidget (const char *name, Qt::DockWidgetArea pos, bool visibility, bool tabbed)
void setDockingArea (const char *name, Qt::DockWidgetArea pos)
void setVisibility (const char *name, bool v)
void setVisibility (bool v)
const QList< DockWindowItem > & dockWidgets () const
Detailed Description
Definition at line 41 of file DockWindowManager.h.
Constructor & Destructor Documentation
DockWindowItems()
DockWindowItems::DockWindowItems () default
~DockWindowItems()
DockWindowItems::~DockWindowItems () default
Member Function Documentation
addDockWidget()
void DockWindowItems::addDockWidget (const char * name, Qt::DockWidgetArea pos, bool visibility, bool tabbed)
Definition at line 52 of file DockWindowManager.cpp.
References Gui::DockWindowItem::name, Gui::DockWindowItem::pos, RobotExample::pos, Gui::DockWindowItem::tabbed, and Gui::DockWindowItem::visibility.
Referenced by SandboxGui::Workbench::setupDockWindows().
dockWidgets()
const QList< DockWindowItem > & DockWindowItems::dockWidgets () const
Definition at line 89 of file DockWindowManager.cpp.
Referenced by Gui::DockWindowManager::loadState(), and Gui::DockWindowManager::saveState().
setDockingArea()
void DockWindowItems::setDockingArea (const char * name, Qt::DockWidgetArea pos)
Definition at line 62 of file DockWindowManager.cpp.
References RobotExample::pos.
setVisibility() [1/2]
void DockWindowItems::setVisibility (bool v)
Definition at line 82 of file DockWindowManager.cpp.
References TestSpreadsheet::v.
setVisibility() [2/2]
void DockWindowItems::setVisibility (const char * name, bool v)
Definition at line 72 of file DockWindowManager.cpp.
References TestSpreadsheet::v.
Referenced by SandboxGui::Workbench::setupDockWindows().
The documentation for this class was generated from the following files:
DockWindowManager.h
DockWindowManager.cpp