FreeCAD: Gui::Dialog::DlgMacroExecuteImp Class Reference
Gui::Dialog::DlgMacroExecuteImp Class Reference
#include <DlgMacroExecuteImp.h>
Public Member Functions
DlgMacroExecuteImp (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgMacroExecuteImp () override
void accept () override
Public Member Functions inherited from Gui::WindowParameter
WindowParameter (const char *name)
~WindowParameter () override
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
ParameterGrp::handle getWindowParameter ()
return the parameter group of this window
Protected Member Functions
void fillUpList ()
void fillUpListForDir (const QString &dirPath, bool systemWide)
QStringList filterFiles (const QString &)
Protected Member Functions inherited from Gui::WindowParameter
bool setGroupName (const char *name)
template<typename S , typename T >
void setSlotParamChanged (S slot, T *obsPtr)
connect slot to ParameterManager signal
Protected Attributes
QString macroPath
Additional Inherited Members
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter ()
get the parameters
Detailed Description
The DlgMacroExecuteImp class implements a dialog to execute or edit a recorded macro.
Author
Jürgen Riegel
Definition at line 43 of file DlgMacroExecuteImp.h.
Constructor & Destructor Documentation
DlgMacroExecuteImp()
DlgMacroExecuteImp::DlgMacroExecuteImp (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Constructs a DlgMacroExecuteImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
Definition at line 101 of file DlgMacroExecuteImp.cpp.
References fillUpList(), ParameterGrp::GetASCII(), App::Application::getUserMacroDir(), Gui::WindowParameter::getWindowParameter(), App::ExpressionParser::labels, and macroPath.
~DlgMacroExecuteImp()
DlgMacroExecuteImp::~DlgMacroExecuteImp () override default
Destroys the object and frees any allocated resources
Member Function Documentation
accept()
void DlgMacroExecuteImp::accept () override
Executes the selected macro file.
Definition at line 366 of file DlgMacroExecuteImp.cpp.
References Gui::Application::activeDocument(), Gui::MainWindow::appendRecentMacro(), SCL.SimpleDataTypes::e, Gui::MacroManager::File, Gui::Document::getDocument(), Gui::getMainWindow(), Gui::Application::Instance, Gui::Application::macroManager(), App::Document::recompute(), and Gui::MacroManager::run().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
fillUpList()
void DlgMacroExecuteImp::fillUpList () protected
Fills up the list with macro files found in all system paths and specified by user location that have been filtered by both filename and by content
Definition at line 263 of file DlgMacroExecuteImp.cpp.
References App::Application::Config(), fillUpListForDir(), App::Application::getHomePath(), and macroPath.
Referenced by DlgMacroExecuteImp().
fillUpListForDir()
void DlgMacroExecuteImp::fillUpListForDir (const QString & dirPath, bool systemWide) protected
Fills up the list with macro files found in the specified location that have been filtered by both filename and by content
Definition at line 248 of file DlgMacroExecuteImp.cpp.
References filterFiles().
Referenced by fillUpList().
filterFiles()
QStringList DlgMacroExecuteImp::filterFiles (const QString & folder) protected
Take a folder and return a StringList of the filenames in it filtered by both filename and by content, if the user has put text in one or both of the search line edits.
First filtering is done by file name, which reduces the number of files to open and read (relatively expensive operation).
Then we filter by file content after reducing the number of files to open and read. But both loops are skipped if there is no text in either of the line edits.
We do this as another function in order to reuse this code for doing both the User and System macro list boxes in the fillUpList() function.
Definition at line 183 of file DlgMacroExecuteImp.cpp.
References DrawingExample::file, Path.Preferences::filePath(), and src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression.
Referenced by fillUpListForDir().
Member Data Documentation
macroPath
QString Gui::Dialog::DlgMacroExecuteImp::macroPath protected
Definition at line 76 of file DlgMacroExecuteImp.h.
Referenced by DlgMacroExecuteImp(), and fillUpList().
The documentation for this class was generated from the following files:
DlgMacroExecuteImp.h
DlgMacroExecuteImp.cpp