FreeCAD: Wm4::BandedMatrix< Real > Class Template Reference
Wm4::BandedMatrix< Real > Class Template Reference
#include <Wm4BandedMatrix.h>
Public Member Functions
BandedMatrix (int iSize, int iLBands, int iUBands)
BandedMatrix (const BandedMatrix &rkM)
~BandedMatrix ()
BandedMatrix & operator= (const BandedMatrix &rkM)
int GetSize () const
int GetLBands () const
int GetUBands () const
Real * GetDBand ()
const Real * GetDBand () const
int GetLBandMax (int i) const
Real * GetLBand (int i)
const Real * GetLBand (int i) const
int GetUBandMax (int i) const
Real * GetUBand (int i)
const Real * GetUBand (int i) const
Real & operator() (int iRow, int iCol)
Real operator() (int iRow, int iCol) const
void SetZero ()
void SetIdentity ()
Detailed Description
template<class Real>
class Wm4::BandedMatrix< Real >
Definition at line 27 of file Wm4BandedMatrix.h.
Constructor & Destructor Documentation
BandedMatrix() [1/2]
template<class Real > Wm4::BandedMatrix< Real >::BandedMatrix (int iSize, int iLBands, int iUBands)
BandedMatrix() [2/2]
template<class Real > Wm4::BandedMatrix< Real >::BandedMatrix (const BandedMatrix< Real > & rkM)
~BandedMatrix()
template<class Real > Wm4::BandedMatrix< Real >::~BandedMatrix ()
Member Function Documentation
GetDBand() [1/2]
template<class Real > Real* Wm4::BandedMatrix< Real >::GetDBand ()
GetDBand() [2/2]
template<class Real > const Real* Wm4::BandedMatrix< Real >::GetDBand () const
GetLBand() [1/2]
template<class Real > Real* Wm4::BandedMatrix< Real >::GetLBand (int i)
GetLBand() [2/2]
template<class Real > const Real* Wm4::BandedMatrix< Real >::GetLBand (int i) const
GetLBandMax()
template<class Real > int Wm4::BandedMatrix< Real >::GetLBandMax (int i) const
GetLBands()
template<class Real > int Wm4::BandedMatrix< Real >::GetLBands () const
GetSize()
template<class Real > int Wm4::BandedMatrix< Real >::GetSize () const
Referenced by Wm4::LinearSystem< Real >::Invert(), and Wm4::LinearSystem< Real >::SolveBanded().
GetUBand() [1/2]
template<class Real > Real* Wm4::BandedMatrix< Real >::GetUBand (int i)
GetUBand() [2/2]
template<class Real > const Real* Wm4::BandedMatrix< Real >::GetUBand (int i) const
GetUBandMax()
template<class Real > int Wm4::BandedMatrix< Real >::GetUBandMax (int i) const
GetUBands()
template<class Real > int Wm4::BandedMatrix< Real >::GetUBands () const
Referenced by Wm4::LinearSystem< Real >::SolveBanded().
operator()() [1/2]
template<class Real > Real& Wm4::BandedMatrix< Real >::operator() (int iRow, int iCol)
operator()() [2/2]
template<class Real > Real Wm4::BandedMatrix< Real >::operator() (int iRow, int iCol) const
operator=()
template<class Real > BandedMatrix& Wm4::BandedMatrix< Real >::operator= (const BandedMatrix< Real > & rkM)
SetIdentity()
template<class Real > void Wm4::BandedMatrix< Real >::SetIdentity ()
SetZero()
template<class Real > void Wm4::BandedMatrix< Real >::SetZero ()
The documentation for this class was generated from the following file:
Wm4BandedMatrix.h