FreeCAD: Materials::MaterialLibrary Class Reference
Materials::MaterialLibrary Class Reference
#include <MaterialLibrary.h>
Public Member Functions
MaterialLibrary ()=default
MaterialLibrary (const MaterialLibrary &)=delete
MaterialLibrary (const QString &libraryName, const QString &dir, const QString &icon, bool readOnly=true)
~MaterialLibrary () override=default
bool operator== (const MaterialLibrary &library) const
bool operator!= (const MaterialLibrary &library) const
std::shared_ptr< Material > getMaterialByPath (const QString &path) const
void createFolder (const QString &path)
void renameFolder (const QString &oldPath, const QString &newPath)
void deleteRecursive (const QString &path)
std::shared_ptr< Material > saveMaterial (const std::shared_ptr< Material > &material, const QString &path, bool overwrite, bool saveAsCopy, bool saveInherited)
bool fileExists (const QString &path) const
std::shared_ptr< Material > addMaterial (const std::shared_ptr< Material > &material, const QString &path)
std::shared_ptr< std::map< QString, std::shared_ptr< MaterialTreeNode > > > getMaterialTree (const std::shared_ptr< Materials::MaterialFilter > &filter, const Materials::MaterialFilterOptions &options) const
bool isReadOnly () const
std::shared_ptr< MaterialLibrary > getptr ()
Public Member Functions inherited from Materials::LibraryBase
LibraryBase ()=default
LibraryBase (const QString &libraryName, const QString &dir, const QString &icon)
~LibraryBase () override=default
const QString getName () const
const QString getDirectory () const
const QString getDirectoryPath () const
const QString getIconPath () const
bool operator== (const LibraryBase &library) const
bool operator!= (const LibraryBase &library) const
QString getLocalPath (const QString &path) const
QString getRelativePath (const QString &path) const
bool isRoot (const QString &path) const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
void deleteDir (MaterialManager &manager, const QString &path)
void deleteFile (MaterialManager &manager, const QString &path)
void updatePaths (const QString &oldPath, const QString &newPath)
QString getUUIDFromPath (const QString &path) const
bool materialInTree (const std::shared_ptr< Material > &material, const std::shared_ptr< Materials::MaterialFilter > &filter, const Materials::MaterialFilterOptions &options) const
Protected Attributes
bool _readOnly
std::unique_ptr< std::map< QString, std::shared_ptr< Material > > > _materialPathMap
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 65 of file MaterialLibrary.h.
Constructor & Destructor Documentation
MaterialLibrary() [1/3]
Materials::MaterialLibrary::MaterialLibrary () default
MaterialLibrary() [2/3]
Materials::MaterialLibrary::MaterialLibrary (const MaterialLibrary &) delete
MaterialLibrary() [3/3]
MaterialLibrary::MaterialLibrary (const QString & libraryName, const QString & dir, const QString & icon, bool readOnly = true)
Definition at line 46 of file MaterialLibrary.cpp.
~MaterialLibrary()
Materials::MaterialLibrary::~MaterialLibrary () override default
Member Function Documentation
addMaterial()
std::shared_ptr< Material > MaterialLibrary::addMaterial (const std::shared_ptr< Material > & material, const QString & path)
Definition at line 231 of file MaterialLibrary.cpp.
References Path.Preferences::filePath(), getptr(), and Materials::LibraryBase::getRelativePath().
Referenced by saveMaterial().
createFolder()
void MaterialLibrary::createFolder (const QString & path)
Definition at line 55 of file MaterialLibrary.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), Path.Preferences::filePath(), and Materials::LibraryBase::getLocalPath().
deleteDir()
void MaterialLibrary::deleteDir (MaterialManager & manager, const QString & path) protected
Definition at line 69 of file MaterialLibrary.cpp.
References deleteFile(), DrawingExample::file, and Path.Preferences::filePath().
Referenced by deleteRecursive().
deleteFile()
void MaterialLibrary::deleteFile (MaterialManager & manager, const QString & path) protected
Definition at line 108 of file MaterialLibrary.cpp.
References _materialPathMap, Base::Console(), Path.Log::error(), getMaterialByPath(), Materials::LibraryBase::getRelativePath(), and Base::ConsoleSingleton::Log().
Referenced by deleteDir(), and deleteRecursive().
deleteRecursive()
void MaterialLibrary::deleteRecursive (const QString & path)
Definition at line 128 of file MaterialLibrary.cpp.
References deleteDir(), deleteFile(), Path.Preferences::filePath(), Materials::LibraryBase::getLocalPath(), Path.Log::info(), and Materials::LibraryBase::isRoot().
fileExists()
bool MaterialLibrary::fileExists (const QString & path) const
Definition at line 223 of file MaterialLibrary.cpp.
References Path.Preferences::filePath(), Materials::LibraryBase::getLocalPath(), and Path.Log::info().
getMaterialByPath()
std::shared_ptr< Material > MaterialLibrary::getMaterialByPath (const QString & path) const
Definition at line 244 of file MaterialLibrary.cpp.
References _materialPathMap, Path.Preferences::filePath(), and Materials::LibraryBase::getRelativePath().
Referenced by deleteFile().
getMaterialTree()
std::shared_ptr< std::map< QString, std::shared_ptr< MaterialTreeNode > > > MaterialLibrary::getMaterialTree (const std::shared_ptr< Materials::MaterialFilter > & filter, const Materials::MaterialFilterOptions & options) const
Definition at line 287 of file MaterialLibrary.cpp.
References _materialPathMap, Materials::MaterialLoader::getMaterialFolders(), Materials::MaterialFilterOptions::includeEmptyFolders(), and materialInTree().
getptr()
std::shared_ptr<MaterialLibrary> Materials::MaterialLibrary::getptr () inline
Definition at line 111 of file MaterialLibrary.h.
References TYPESYSTEM_HEADER_WITH_OVERRIDE.
Referenced by addMaterial(), and saveMaterial().
getUUIDFromPath()
QString MaterialLibrary::getUUIDFromPath (const QString & path) const protected
Definition at line 256 of file MaterialLibrary.cpp.
References _materialPathMap, Path.Preferences::filePath(), and Materials::LibraryBase::getRelativePath().
isReadOnly()
bool Materials::MaterialLibrary::isReadOnly () const inline
Definition at line 105 of file MaterialLibrary.h.
materialInTree()
bool MaterialLibrary::materialInTree (const std::shared_ptr< Material > & material, const std::shared_ptr< Materials::MaterialFilter > & filter, const Materials::MaterialFilterOptions & options) const protected
Definition at line 268 of file MaterialLibrary.cpp.
References Materials::MaterialFilterOptions::includeLegacy().
Referenced by getMaterialTree().
operator!=()
bool Materials::MaterialLibrary::operator!= (const MaterialLibrary & library) const inline
Definition at line 83 of file MaterialLibrary.h.
operator==()
bool Materials::MaterialLibrary::operator== (const MaterialLibrary & library) const inline
Definition at line 79 of file MaterialLibrary.h.
renameFolder()
void MaterialLibrary::renameFolder (const QString & oldPath, const QString & newPath)
Definition at line 165 of file MaterialLibrary.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), Path.Preferences::filePath(), Materials::LibraryBase::getLocalPath(), and updatePaths().
saveMaterial()
std::shared_ptr< Material > MaterialLibrary::saveMaterial (const std::shared_ptr< Material > & material, const QString & path, bool overwrite, bool saveAsCopy, bool saveInherited)
Definition at line 181 of file MaterialLibrary.cpp.
References addMaterial(), Base::Console(), Base::ConsoleSingleton::Error(), DrawingExample::file, Path.Preferences::filePath(), Materials::LibraryBase::getLocalPath(), getptr(), Materials::LibraryBase::getRelativePath(), and Path.Log::info().
updatePaths()
void MaterialLibrary::updatePaths (const QString & oldPath, const QString & newPath) protected
Definition at line 146 of file MaterialLibrary.cpp.
References _materialPathMap, Materials::LibraryBase::getRelativePath(), and Path.Post.scripts.opensbp_post::move().
Referenced by renameFolder().
Member Data Documentation
_materialPathMap
std::unique_ptr<std::map<QString, std::shared_ptr<Material> > > Materials::MaterialLibrary::_materialPathMap protected
Definition at line 127 of file MaterialLibrary.h.
Referenced by deleteFile(), getMaterialByPath(), getMaterialTree(), getUUIDFromPath(), and updatePaths().
_readOnly
bool Materials::MaterialLibrary::_readOnly protected
Definition at line 126 of file MaterialLibrary.h.
The documentation for this class was generated from the following files:
MaterialLibrary.h
MaterialLibrary.cpp