FreeCAD: Gui::SoFCColorBar Class Reference
Gui::SoFCColorBar Class Reference
#include <SoFCColorBar.h>
Public Member Functions
SoFCColorBar ()
SoFCColorBarBase * getActiveBar () const
void handleEvent (SoHandleEventAction *action) override
void setRange (float fMin, float fMax, int prec=3) override
App::Color getColor (float fVal) const override
void setOutsideGrayed (bool bVal) override
bool isVisible (float fVal) const override
float getMinValue () const override
float getMaxValue () const override
void customize (SoFCColorBarBase *) override
void triggerChange (SoFCColorBarBase *) override
const char * getColorBarName () const override
void setFormat (const SoLabelTextFormat &fmt) override
Public Member Functions inherited from Gui::SoFCColorBarBase
void GLRenderBelowPath (SoGLRenderAction *action) override
SoLabelTextFormat getFormat () const
Public Member Functions inherited from Base::Subject< int >
Subject ()=default
virtual ~Subject ()
void Attach (Observer< int > *ToObserv)
void Detach (Observer< int > *ToObserv)
void Notify (int rcReason)
Observer< int > * Get (const char *Name)
void ClearObserver ()
Static Public Member Functions
static void initClass ()
static void finish ()
Static Public Member Functions inherited from Gui::SoFCColorBarBase
static void initClass ()
static void finish ()
Protected Member Functions
void setViewportSize (const SbVec2s &size) override
~SoFCColorBar () override
Protected Member Functions inherited from Gui::SoFCColorBarBase
virtual void applyFormat (const SoLabelTextFormat &fmt)
float getBounds (const SbVec2s &size, float &fMinX, float &fMinY, float &fMaxX, float &fMaxY)
float getBoundingWidth (const SbVec2s &size)
void setModified ()
SoFCColorBarBase ()
~SoFCColorBarBase () override
Protected Member Functions inherited from App::ValueFloatToRGB
ValueFloatToRGB ()=default
virtual ~ValueFloatToRGB ()=default
Additional Inherited Members
Public Types inherited from Base::Subject< int >
using ObserverType = Observer< int >
using MessageType = int
using SubjectType = Subject< int >
Detailed Description
The color bar class that redirects all calls to its handled color bars.
Author
Werner Mayer
Definition at line 168 of file SoFCColorBar.h.
Constructor & Destructor Documentation
SoFCColorBar()
SoFCColorBar::SoFCColorBar ()
Constructor.
Definition at line 200 of file SoFCColorBar.cpp.
~SoFCColorBar()
SoFCColorBar::~SoFCColorBar () override protected default
Destructor.
Member Function Documentation
customize()
void SoFCColorBar::customize (SoFCColorBarBase * child) override virtual
Customizes the currently active color bar.
Implements Gui::SoFCColorBarBase.
Definition at line 284 of file SoFCColorBar.cpp.
References Gui::SoFCColorBarBase::customize(), and SCL.SimpleDataTypes::e.
Referenced by Gui::SoFCColorBarProxyObject::customEvent().
finish()
void SoFCColorBar::finish () static
Definition at line 230 of file SoFCColorBar.cpp.
Referenced by drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::accept(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::accept(), draftguitools.gui_split.Split::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_subelements.SubelementHighlight::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rotate.Rotate::action(), draftguitools.gui_fillets.Fillet::action(), draftguitools.gui_move.Move::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_arcs.Arc::action(), draftguitools.gui_texts.Text::action(), draftguitools.gui_scale.Scale::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_trimex.Trimex::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_styles.ApplyStyle::Activated(), draftguitools.gui_join.Join::Activated(), draftguitools.gui_draft2sketch.Draft2Sketch::Activated(), draftguitools.gui_downgrade.Downgrade::Activated(), draftguitools.gui_upgrade.Upgrade::Activated(), draftguitools.gui_shape2dview.Shape2DView::Activated(), draftguitools.gui_facebinders.Facebinder::Activated(), draftguitools.gui_subelements.SubelementHighlight::Activated(), draftguitools.gui_wire2spline.WireToBSpline::Activated(), draftguitools.gui_clone.Clone::Activated(), draftguitools.gui_dimensions.Dimension::Activated(), draftguitools.gui_edit.Edit::Activated(), draftguitools.gui_selectplane.Draft_SelectPlane::check_selection(), DraftGui.DraftToolBar::checkSpecialChars(), draftguitools.gui_points.Point::click(), draftguitools.gui_orthoarray.OrthoArray::completed(), draftguitools.gui_polararray.PolarArray::completed(), draftguitools.gui_circulararray.CircularArray::completed(), draftguitools.gui_labels.Label::create(), bimcommands.BimText.BIM_Text::createObject(), draftguitools.gui_rectangles.Rectangle::createObject(), draftguitools.gui_ellipses.Ellipse::createObject(), draftguitools.gui_texts.Text::createObject(), draftviewproviders.view_text.ViewProviderText::createObject(), draftguitools.gui_stretch.Stretch::doStretch(), draftguitools.gui_fillets.Fillet::draw_arc(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), DraftGui.DraftToolBar::editUi(), DraftGui.DraftToolBar::escape(), Gui::SoFCDB::finish(), draftguitools.gui_move.Move::get_object_selection(), draftguitools.gui_rotate.Rotate::get_object_selection(), draftguitools.gui_scale.Scale::get_object_selection(), draftguitools.gui_arcs.Arc_3Points::getPoint(), draftguitools.gui_edit.Edit::keyPressed(), draftguitools.gui_dimensions.Dimension::numericInput(), draftguitools.gui_offset.Offset::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), draftguitools.gui_trimex.Trimex::numericRadius(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_align(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_auto(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_center(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_front(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_move(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_next(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_previous(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_side(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_top(), bimcommands.BimShape2DView.BIM_Shape2DView::proceed(), draftguitools.gui_join.Join::proceed(), draftguitools.gui_subelements.SubelementHighlight::proceed(), draftguitools.gui_draft2sketch.Draft2Sketch::proceed(), draftguitools.gui_downgrade.Downgrade::proceed(), bimcommands.BimSlab.BIM_Slab::proceed(), draftguitools.gui_upgrade.Upgrade::proceed(), draftguitools.gui_facebinders.Facebinder::proceed(), draftguitools.gui_pathtwistedarray.PathTwistedArray::proceed(), draftguitools.gui_shape2dview.Shape2DView::proceed(), draftguitools.gui_clone.Clone::proceed(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_pointarray.PointArray::proceed(), draftguitools.gui_patharray.PathArray::proceed(), draftguitools.gui_trimex.Trimex::proceed(), draftguitools.gui_edit.Edit::proceed(), draftguitools.gui_selectplane.Draft_SelectPlane::reject(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::reject(), drafttaskpanels.task_polararray.TaskPanelPolarArray::reject(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::reject(), and draftguitools.gui_edit.Edit::setTrackers().
getActiveBar()
SoFCColorBarBase * SoFCColorBar::getActiveBar () const
Returns the currently active color bar object.
Definition at line 235 of file SoFCColorBar.cpp.
Referenced by Gui::SoFCColorBarProxyObject::customEvent(), getColor(), getMaxValue(), getMinValue(), handleEvent(), and isVisible().
getColor()
App::Color SoFCColorBar::getColor (float fVal) const override virtual
Returns the associated color to the value fVal of the currently active color bar.
Implements Gui::SoFCColorBarBase.
Definition at line 294 of file SoFCColorBar.cpp.
References getActiveBar(), and Gui::SoFCColorBarBase::getColor().
Referenced by InspectionGui::ViewProviderInspection::setDistances(), and draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::setValues().
getColorBarName()
const char* Gui::SoFCColorBar::getColorBarName () const inline override virtual
Returns the name of the color bar.
Implements Gui::SoFCColorBarBase.
Definition at line 221 of file SoFCColorBar.h.
getMaxValue()
float SoFCColorBar::getMaxValue () const override virtual
Returns the current maximum of the parameter range of the currently active color bar.
Implements Gui::SoFCColorBarBase.
Definition at line 274 of file SoFCColorBar.cpp.
References getActiveBar(), and Gui::SoFCColorBarBase::getMaxValue().
Referenced by InspectionGui::ViewProviderInspection::attach().
getMinValue()
float SoFCColorBar::getMinValue () const override virtual
Returns the current minimum of the parameter range of the currently active color bar.
Implements Gui::SoFCColorBarBase.
Definition at line 269 of file SoFCColorBar.cpp.
References getActiveBar(), and Gui::SoFCColorBarBase::getMinValue().
Referenced by InspectionGui::ViewProviderInspection::attach().
handleEvent()
void SoFCColorBar::handleEvent (SoHandleEventAction * action) override
Handles the mouse button events and checks if the user has clicked on the area of the currently active color bar.
Definition at line 312 of file SoFCColorBar.cpp.
References Path.Post.scripts.dynapath_4060_post::action, SCL.SimpleDataTypes::e, getActiveBar(), SplineSurface::i, SplineSurface::id, NavigationIndicatorGui::menu, RobotExample::pos, and Path.Op.Gui.Selection::select().
initClass()
void SoFCColorBar::initClass () static
Definition at line 225 of file SoFCColorBar.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
isVisible()
bool SoFCColorBar::isVisible (float fVal) const override virtual
Returns the return value of the currently active color bar.
Implements Gui::SoFCColorBarBase.
Definition at line 264 of file SoFCColorBar.cpp.
References getActiveBar(), and Gui::SoFCColorBarBase::isVisible().
Referenced by ArchVRM.Renderer::removeHidden(), and InspectionGui::ViewProviderInspection::setDistances().
setFormat()
void SoFCColorBar::setFormat (const SoLabelTextFormat & fmt) override virtual
Sets the format for the label text.
Reimplemented from Gui::SoFCColorBarBase.
Definition at line 241 of file SoFCColorBar.cpp.
References Path.Post.scripts.comparams_post::fmt().
Referenced by Path.Main.Gui.Inspect.GCodeHighlighter::highlightBlock(), and Path.Post.Utils.GCodeHighlighter::highlightBlock().
setOutsideGrayed()
void SoFCColorBar::setOutsideGrayed (bool bVal) override virtual
Sets whether values outside the range should be in gray,
Implements Gui::SoFCColorBarBase.
Definition at line 258 of file SoFCColorBar.cpp.
Referenced by InspectionGui::ViewProviderInspection::onChanged().
setRange()
void SoFCColorBar::setRange (float fMin, float fMax, int prec = 3) override virtual
Sets the range of all color bars from the maximum fMax to the minimum fMin. prec indicates the post decimal positions, prec should be in between 0 and 6.
Implements Gui::SoFCColorBarBase.
Definition at line 252 of file SoFCColorBar.cpp.
Referenced by InspectionGui::ViewProviderInspection::attach(), FemGui::ViewProviderFemPostObject::setRangeOfColorBar(), and InspectionGui::ViewProviderInspection::updateData().
setViewportSize()
void SoFCColorBar::setViewportSize (const SbVec2s & size) override protected virtual
Sets the current viewer size to all color bars to recalculate their new position.
Implements Gui::SoFCColorBarBase.
Definition at line 247 of file SoFCColorBar.cpp.
triggerChange()
void SoFCColorBar::triggerChange (SoFCColorBarBase *) override virtual
Notify observers
Reimplemented from Gui::SoFCColorBarBase.
Definition at line 279 of file SoFCColorBar.cpp.
References Base::Subject< int >::Notify().
The documentation for this class was generated from the following files:
SoFCColorBar.h
SoFCColorBar.cpp