FreeCAD: Materials::MaterialConfigLoader Class Reference
Materials::MaterialConfigLoader Class Reference
#include <MaterialConfigLoader.h>
Public Member Functions
MaterialConfigLoader ()=default
virtual ~MaterialConfigLoader ()=default
Static Public Member Functions
static bool isConfigStyle (const QString &path)
static std::shared_ptr< Material > getMaterialFromPath (const std::shared_ptr< MaterialLibrary > &library, const QString &path)
Detailed Description
Definition at line 58 of file MaterialConfigLoader.h.
Constructor & Destructor Documentation
MaterialConfigLoader()
Materials::MaterialConfigLoader::MaterialConfigLoader () default
~MaterialConfigLoader()
virtual Materials::MaterialConfigLoader::~MaterialConfigLoader () virtual default
Member Function Documentation
getMaterialFromPath()
std::shared_ptr< Material > MaterialConfigLoader::getMaterialFromPath (const std::shared_ptr< MaterialLibrary > & library, const QString & path) static
Definition at line 1037 of file MaterialConfigLoader.cpp.
References Base::Console(), ifctree::filepath, Base::ConsoleSingleton::Log(), Materials::ModelUUIDs::ModelUUID_Legacy_Father, and Materials::ModelUUIDs::ModelUUID_Legacy_MaterialStandard.
Referenced by Materials::MaterialManager::getMaterialByPath().
isConfigStyle()
bool MaterialConfigLoader::isConfigStyle (const QString & path) static
Definition at line 49 of file MaterialConfigLoader.cpp.
Referenced by Materials::MaterialManager::getMaterialByPath().
The documentation for this class was generated from the following files:
MaterialConfigLoader.h
MaterialConfigLoader.cpp