FreeCAD: FCBRepAlgoAPI_BooleanOperation Class Reference
FCBRepAlgoAPI_BooleanOperation Class Reference
#include <FCBRepAlgoAPI_BooleanOperation.h>
Public Member Functions
DEFINE_STANDARD_ALLOC Standard_EXPORT FCBRepAlgoAPI_BooleanOperation ()
Empty constructor.
void setAutoFuzzy ()
Protected Member Functions
Constructors
Standard_EXPORT FCBRepAlgoAPI_BooleanOperation (const TopoDS_Shape &theS1, const TopoDS_Shape &theS2, const BOPAlgo_Operation theOperation)
Detailed Description
Definition at line 40 of file FCBRepAlgoAPI_BooleanOperation.h.
Constructor & Destructor Documentation
FCBRepAlgoAPI_BooleanOperation() [1/2]
FCBRepAlgoAPI_BooleanOperation::FCBRepAlgoAPI_BooleanOperation ()
Empty constructor.
FCBRepAlgoAPI provides a wrapper for various OCCT functions.
Definition at line 37 of file FCBRepAlgoAPI_BooleanOperation.cpp.
FCBRepAlgoAPI_BooleanOperation() [2/2]
FCBRepAlgoAPI_BooleanOperation::FCBRepAlgoAPI_BooleanOperation (const TopoDS_Shape & theS1, const TopoDS_Shape & theS2, const BOPAlgo_Operation theOperation) protected
Constructor to perform Boolean operation on only two arguments. Obsolete
Definition at line 44 of file FCBRepAlgoAPI_BooleanOperation.cpp.
References setAutoFuzzy().
Member Function Documentation
setAutoFuzzy()
void FCBRepAlgoAPI_BooleanOperation::setAutoFuzzy ()
Definition at line 60 of file FCBRepAlgoAPI_BooleanOperation.cpp.
References FCBRepAlgoAPIHelper::setAutoFuzzy().
Referenced by Part::TopoShape::common(), Part::TopoShape::cut(), Part::MultiFuse::execute(), FCBRepAlgoAPI_BooleanOperation(), and Part::TopoShape::fuse().
The documentation for this class was generated from the following files:
FCBRepAlgoAPI_BooleanOperation.h
FCBRepAlgoAPI_BooleanOperation.cpp