FreeCAD: drafttests.test_draftgeomutils.TestDraftGeomUtils Class Reference
drafttests.test_draftgeomutils.TestDraftGeomUtils Class Reference
Public Member Functions
def check_wire (self, wire)
def test_get_extended_wire1 (self)
def test_get_extended_wire2 (self)
def test_get_extended_wire3 (self)
def test_get_extended_wire4 (self)
def test_get_extended_wire5 (self)
def test_get_extended_wire6 (self)
def test_get_extended_wire7 (self)
def test_get_extended_wire8 (self)
Public Member Functions inherited from drafttests.test_base.DraftTestCaseNoDoc
def setUp (self)
Detailed Description
Testing the functions in the file DraftGeomUtils.py
Definition at line 34 of file test_draftgeomutils.py.
Member Function Documentation
check_wire()
def drafttests.test_draftgeomutils.TestDraftGeomUtils.check_wire (self, wire)
Definition at line 37 of file test_draftgeomutils.py.
References src.Mod.Test.Document.DocumentExpressionCases.assertAlmostEqual().
Referenced by drafttests.test_draftgeomutils.TestDraftGeomUtils.test_get_extended_wire1(), drafttests.test_draftgeomutils.TestDraftGeomUtils.test_get_extended_wire2(), drafttests.test_draftgeomutils.TestDraftGeomUtils.test_get_extended_wire3(), drafttests.test_draftgeomutils.TestDraftGeomUtils.test_get_extended_wire4(), drafttests.test_draftgeomutils.TestDraftGeomUtils.test_get_extended_wire5(), drafttests.test_draftgeomutils.TestDraftGeomUtils.test_get_extended_wire6(), drafttests.test_draftgeomutils.TestDraftGeomUtils.test_get_extended_wire7(), and drafttests.test_draftgeomutils.TestDraftGeomUtils.test_get_extended_wire8().
test_get_extended_wire1()
def drafttests.test_draftgeomutils.TestDraftGeomUtils.test_get_extended_wire1 (self)
Test the DraftGeomUtils.get_extended_wire function.
Definition at line 60 of file test_draftgeomutils.py.
References drafttests.test_draftgeomutils.TestDraftGeomUtils.check_wire().
test_get_extended_wire2()
def drafttests.test_draftgeomutils.TestDraftGeomUtils.test_get_extended_wire2 (self)
Test the DraftGeomUtils.get_extended_wire function.
Definition at line 78 of file test_draftgeomutils.py.
References drafttests.test_draftgeomutils.TestDraftGeomUtils.check_wire().
test_get_extended_wire3()
def drafttests.test_draftgeomutils.TestDraftGeomUtils.test_get_extended_wire3 (self)
Test the DraftGeomUtils.get_extended_wire function.
Definition at line 97 of file test_draftgeomutils.py.
References drafttests.test_draftgeomutils.TestDraftGeomUtils.check_wire().
test_get_extended_wire4()
def drafttests.test_draftgeomutils.TestDraftGeomUtils.test_get_extended_wire4 (self)
Test the DraftGeomUtils.get_extended_wire function.
Definition at line 117 of file test_draftgeomutils.py.
References drafttests.test_draftgeomutils.TestDraftGeomUtils.check_wire().
test_get_extended_wire5()
def drafttests.test_draftgeomutils.TestDraftGeomUtils.test_get_extended_wire5 (self)
Test the DraftGeomUtils.get_extended_wire function.
Definition at line 136 of file test_draftgeomutils.py.
References drafttests.test_draftgeomutils.TestDraftGeomUtils.check_wire().
test_get_extended_wire6()
def drafttests.test_draftgeomutils.TestDraftGeomUtils.test_get_extended_wire6 (self)
Test the DraftGeomUtils.get_extended_wire function.
Definition at line 155 of file test_draftgeomutils.py.
References drafttests.test_draftgeomutils.TestDraftGeomUtils.check_wire().
test_get_extended_wire7()
def drafttests.test_draftgeomutils.TestDraftGeomUtils.test_get_extended_wire7 (self)
Test the DraftGeomUtils.get_extended_wire function.
Definition at line 175 of file test_draftgeomutils.py.
References drafttests.test_draftgeomutils.TestDraftGeomUtils.check_wire().
test_get_extended_wire8()
def drafttests.test_draftgeomutils.TestDraftGeomUtils.test_get_extended_wire8 (self)
Test the DraftGeomUtils.get_extended_wire function.
Definition at line 196 of file test_draftgeomutils.py.
References drafttests.test_draftgeomutils.TestDraftGeomUtils.check_wire().
The documentation for this class was generated from the following file:
test_draftgeomutils.py