FreeCAD: Document.cpp File Reference
App/Document.cpp File Reference
#include "PreCompiled.h"
#include <bitset>
#include <stack>
#include <boost/filesystem.hpp>
#include <boost/algorithm/string.hpp>
#include <boost/bimap.hpp>
#include <boost/graph/strong_components.hpp>
#include <boost/regex.hpp>
#include <random>
#include <unordered_map>
#include <unordered_set>
#include <QCryptographicHash>
#include <QCoreApplication>
#include <App/DocumentPy.h>
#include <Base/Interpreter.h>
#include <Base/Console.h>
#include <Base/Exception.h>
#include <Base/FileInfo.h>
#include <Base/TimeInfo.h>
#include <Base/Reader.h>
#include <Base/Writer.h>
#include <Base/Tools.h>
#include <Base/Uuid.h>
#include <Base/Sequencer.h>
#include <Base/Stream.h>
#include <Base/UnitsApi.h>
#include "Document.h"
#include "private/DocumentP.h"
#include "Application.h"
#include "AutoTransaction.h"
#include "ExpressionParser.h"
#include "GeoFeature.h"
#include "License.h"
#include "Link.h"
#include "MergeDocuments.h"
#include "StringHasher.h"
#include "Transactions.h"
#include <zipios++/zipfile.h>
#include <zipios++/zipinputstream.h>
#include <zipios++/zipoutputstream.h>
#include <zipios++/meta-iostreams.h>
Classes
struct DocExportStatus
class DocumentExporting
struct DepInfo
class App::BackupPolicy
Namespaces
App
a class to assist with exporting sketches to dxf
Macros
#define FC_ATTR_DEPENDENCIES "Dependencies"
#define FC_ELEMENT_OBJECT_DEPS "ObjectDeps"
#define FC_ATTR_DEP_COUNT "Count"
#define FC_ATTR_DEP_OBJ_NAME "Name"
#define FC_ATTR_DEP_ALLOW_PARTIAL "AllowPartial"
#define FC_ELEMENT_OBJECT_DEP "Dep"
Functions
TYPESYSTEM_SOURCE_P (App::Document) const App
static void _loadDeps (const std::string &name, std::unordered_map< std::string, bool > &objs, const std::unordered_map< std::string, DepInfo > &deps)
static std::string checkFileName (const char *file)
static void _buildDependencyList (const std::vector< App::DocumentObject * > &objectArray, int options, std::vector< App::DocumentObject * > *depObjs, DependencyList *depList, std::map< DocumentObject *, Vertex > *objectMap, bool *touchCheck=nullptr)
Variables
static bool App::globalIsRestoring
static bool App::globalIsRelabeling
static DocExportStatus _ExportStatus
Macro Definition Documentation
FC_ATTR_DEP_ALLOW_PARTIAL
#define FC_ATTR_DEP_ALLOW_PARTIAL "AllowPartial"
Definition at line 1294 of file App/Document.cpp.
FC_ATTR_DEP_COUNT
#define FC_ATTR_DEP_COUNT "Count"
Definition at line 1292 of file App/Document.cpp.
FC_ATTR_DEP_OBJ_NAME
#define FC_ATTR_DEP_OBJ_NAME "Name"
Definition at line 1293 of file App/Document.cpp.
FC_ATTR_DEPENDENCIES
#define FC_ATTR_DEPENDENCIES "Dependencies"
Definition at line 1290 of file App/Document.cpp.
FC_ELEMENT_OBJECT_DEP
#define FC_ELEMENT_OBJECT_DEP "Dep"
Definition at line 1295 of file App/Document.cpp.
FC_ELEMENT_OBJECT_DEPS
#define FC_ELEMENT_OBJECT_DEPS "ObjectDeps"
Definition at line 1291 of file App/Document.cpp.
Function Documentation
_buildDependencyList()
static void _buildDependencyList (const std::vector< App::DocumentObject * > & objectArray, int options, std::vector< App::DocumentObject * > * depObjs, DependencyList * depList, std::map< DocumentObject *, Vertex > * objectMap, bool * touchCheck = nullptr) static
Definition at line 2672 of file App/Document.cpp.
References App::Document::DepNoXLinked, replaceobj::objs, App::DocumentObject::OutListNoXLinked, and TestSpreadsheet::v.
Referenced by App::Document::_rebuildDependencyList(), App::Document::getDependencyList(), and App::Document::mustExecute().
_loadDeps()
static void _loadDeps (const std::string & name, std::unordered_map< std::string, bool > & objs, const std::unordered_map< std::string, DepInfo > & deps) static
Definition at line 1395 of file App/Document.cpp.
References replaceobj::objs.
Referenced by App::Document::readObjects().
checkFileName()
static std::string checkFileName (const char * file) static
Definition at line 1718 of file App/Document.cpp.
References create_qrc::ext, DrawingExample::file, and App::GetApplication().
Referenced by App::Document::saveAs(), and App::Document::saveCopy().
TYPESYSTEM_SOURCE_P()
TYPESYSTEM_SOURCE_P (App::Document) const
Definition at line 169 of file App/Document.cpp.
Variable Documentation
_ExportStatus
DocExportStatus _ExportStatus static
Definition at line 1210 of file App/Document.cpp.
Referenced by DocumentExporting::DocumentExporting(), App::Document::isExporting(), and DocumentExporting::~DocumentExporting().