FreeCAD: NavigationIndicatorGui.IndicatorButton Class Reference
NavigationIndicatorGui.IndicatorButton Class Reference
Public Member Functions
def __init__ (self, parent=None)
def changeEvent (self, event)
def onChange (self, paramGrp, param)
def mousePressEvent (self, event)
Detailed Description
Detect language change events.
Definition at line 39 of file NavigationIndicatorGui.py.
Constructor & Destructor Documentation
__init__()
def NavigationIndicatorGui.IndicatorButton.__init__ (self, parent = None)
Definition at line 42 of file NavigationIndicatorGui.py.
Member Function Documentation
changeEvent()
def NavigationIndicatorGui.IndicatorButton.changeEvent (self, event)
Change events.
Definition at line 45 of file NavigationIndicatorGui.py.
References Gui::WorkbenchTabWidget.adjustSize(), NavigationIndicatorGui.onTooltip(), and NavigationIndicatorGui.retranslateUi().
mousePressEvent()
def NavigationIndicatorGui.IndicatorButton.mousePressEvent (self, event)
Definition at line 57 of file NavigationIndicatorGui.py.
References NavigationIndicatorGui.RePopulateIcons().
onChange()
def NavigationIndicatorGui.IndicatorButton.onChange (self, paramGrp, param)
Definition at line 53 of file NavigationIndicatorGui.py.
References NavigationIndicatorGui.setCurrent().
The documentation for this class was generated from the following file:
NavigationIndicatorGui.py