FreeCAD: ifc2x3.ifcstructuralloadlinearforce Class Reference
ifc2x3.ifcstructuralloadlinearforce Class Reference
Public Member Functions
def __init__ (self, inherited0__name, linearforcex, linearforcey, linearforcez, linearmomentx, linearmomenty, linearmomentz)
def linearforcex ()
def linearforcey ()
def linearforcez ()
def linearmomentx ()
def linearmomenty ()
def linearmomentz ()
Public Member Functions inherited from ifc2x3.ifcstructuralloadstatic
def __init__ (self, inherited0__name)
Public Member Functions inherited from ifc2x3.ifcstructuralload
def name ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
linearforcex
linearforcey
linearforcez
linearmomentx
linearmomenty
linearmomentz
Public Attributes inherited from ifc2x3.ifcstructuralload
name
Detailed Description
Entity ifcstructuralloadlinearforce definition.
:param linearforcex
:type linearforcex:ifclinearforcemeasure
:param linearforcey
:type linearforcey:ifclinearforcemeasure
:param linearforcez
:type linearforcez:ifclinearforcemeasure
:param linearmomentx
:type linearmomentx:ifclinearmomentmeasure
:param linearmomenty
:type linearmomenty:ifclinearmomentmeasure
:param linearmomentz
:type linearmomentz:ifclinearmomentmeasure
Definition at line 34717 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcstructuralloadlinearforce.__init__ (self, inherited0__name, linearforcex, linearforcey, linearforcez, linearmomentx, linearmomenty, linearmomentz)
Definition at line 34738 of file ifc2x3.py.
Member Function Documentation
linearforcex()
def ifc2x3.ifcstructuralloadlinearforce.linearforcex ()
Definition at line 34748 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadlinearforce._linearforcex, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadlinearforce.linearforcex.
linearforcey()
def ifc2x3.ifcstructuralloadlinearforce.linearforcey ()
Definition at line 34762 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadlinearforce._linearforcey, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadlinearforce.linearforcey.
linearforcez()
def ifc2x3.ifcstructuralloadlinearforce.linearforcez ()
Definition at line 34776 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadlinearforce._linearforcez, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadlinearforce.linearforcez.
linearmomentx()
def ifc2x3.ifcstructuralloadlinearforce.linearmomentx ()
Definition at line 34790 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadlinearforce._linearmomentx, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadlinearforce.linearmomentx.
linearmomenty()
def ifc2x3.ifcstructuralloadlinearforce.linearmomenty ()
Definition at line 34804 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadlinearforce._linearmomenty, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadlinearforce.linearmomenty.
linearmomentz()
def ifc2x3.ifcstructuralloadlinearforce.linearmomentz ()
Definition at line 34818 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadlinearforce._linearmomentz, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadlinearforce.linearmomentz.
Member Data Documentation
linearforcex
ifc2x3.ifcstructuralloadlinearforce.linearforcex
Definition at line 34740 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadlinearforce.linearforcex().
linearforcey
ifc2x3.ifcstructuralloadlinearforce.linearforcey
Definition at line 34741 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadlinearforce.linearforcey().
linearforcez
ifc2x3.ifcstructuralloadlinearforce.linearforcez
Definition at line 34742 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadlinearforce.linearforcez().
linearmomentx
ifc2x3.ifcstructuralloadlinearforce.linearmomentx
Definition at line 34743 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadlinearforce.linearmomentx().
linearmomenty
ifc2x3.ifcstructuralloadlinearforce.linearmomenty
Definition at line 34744 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadlinearforce.linearmomenty().
linearmomentz
ifc2x3.ifcstructuralloadlinearforce.linearmomentz
Definition at line 34745 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadlinearforce.linearmomentz().
The documentation for this class was generated from the following file:
ifc2x3.py