FreeCAD: src.Mod.PartDesign.Scripts.RadialCopy.RadialCopy Class Reference
src.Mod.PartDesign.Scripts.RadialCopy.RadialCopy Class Reference
Public Member Functions
def __init__ (self, obj)
def execute (self, fp)
Detailed Description
Definition at line 27 of file RadialCopy.py.
Constructor & Destructor Documentation
__init__()
def src.Mod.PartDesign.Scripts.RadialCopy.RadialCopy.__init__ (self, obj)
Definition at line 28 of file RadialCopy.py.
Member Function Documentation
execute()
def src.Mod.PartDesign.Scripts.RadialCopy.RadialCopy.execute (self, fp)
Definition at line 38 of file RadialCopy.py.
References src.Mod.PartDesign.Scripts.RadialCopy.makeCopy().
Referenced by src.Mod.PartDesign.Scripts.Spring.MySpring.onChanged(), and FeaturePython.DistanceBolt.onChanged().
The documentation for this class was generated from the following file:
RadialCopy.py