FreeCAD: DrawingGui::SvgView Class Reference
DrawingGui::SvgView Class Reference
#include <DrawingView.h>
Public Types
enum RendererType { Native, OpenGL, Image }
Public Slots
void setHighQualityAntialiasing (bool highQualityAntialiasing)
void setViewBackground (bool enable)
void setViewOutline (bool enable)
Public Member Functions
SvgView (QWidget *parent=nullptr)
void openFile (const QFile &file)
void setRenderer (RendererType type=Native)
void drawBackground (QPainter *p, const QRectF &rect)
void setZoomInverted (bool on)
Protected Member Functions
void wheelEvent (QWheelEvent *event)
void paintEvent (QPaintEvent *event)
Detailed Description
Definition at line 48 of file DrawingView.h.
Member Enumeration Documentation
RendererType
enum DrawingGui::SvgView::RendererType
Enumerator
Native
OpenGL
Image
Definition at line 53 of file DrawingView.h.
Constructor & Destructor Documentation
SvgView()
SvgView::SvgView (QWidget * parent = nullptr)
Definition at line 64 of file DrawingView.cpp.
Member Function Documentation
drawBackground()
void SvgView::drawBackground (QPainter * p, const QRectF & rect)
Definition at line 88 of file DrawingView.cpp.
References buildPsets::p.
Referenced by openFile().
openFile()
void SvgView::openFile (const QFile & file)
Definition at line 96 of file DrawingView.cpp.
References drawBackground(), DrawingExample::file, and toolbit-attributes::s.
Referenced by DrawingGui::DrawingView::load().
paintEvent()
void SvgView::paintEvent (QPaintEvent * event) protected
Definition at line 179 of file DrawingView.cpp.
References buildPsets::p, and OfflineRenderingUtils::render().
setHighQualityAntialiasing
void SvgView::setHighQualityAntialiasing (bool highQualityAntialiasing) slot
Definition at line 152 of file DrawingView.cpp.
setRenderer()
void SvgView::setRenderer (RendererType type = Native)
Definition at line 138 of file DrawingView.cpp.
References OpenGL, and Path.Post.scripts.grbl_post::type.
Referenced by DrawingGui::DrawingView::setRenderer().
setViewBackground
void SvgView::setViewBackground (bool enable) slot
Definition at line 161 of file DrawingView.cpp.
setViewOutline
void SvgView::setViewOutline (bool enable) slot
Definition at line 170 of file DrawingView.cpp.
setZoomInverted()
void DrawingGui::SvgView::setZoomInverted (bool on) inline
Definition at line 65 of file DrawingView.h.
Referenced by DrawingGui::DrawingView::DrawingView().
wheelEvent()
void SvgView::wheelEvent (QWheelEvent * event) protected
Definition at line 198 of file DrawingView.cpp.
References Base::pow(), and draftfunctions.scale::scale().
The documentation for this class was generated from the following files:
DrawingView.h
DrawingView.cpp