FreeCAD: App::PropertyLinkSubList Class Reference
App::PropertyLinkSubList Class Reference
#include <PropertyLinks.h>
Public Types
using SubSet = std::pair< DocumentObject *, std::vector< std::string > >
Public Types inherited from App::PropertyLinkBase
enum LinkFlags {
LinkAllowExternal, LinkDetached, LinkRestoring, LinkAllowPartial,
LinkRestoreLabel, LinkSyncSubObject, LinkNewElement, LinkSilentRestore
}
using ShadowSub = ElementNamePair
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Public Member Functions
PropertyLinkSubList ()
~PropertyLinkSubList () override
void afterRestore () override
void onContainerRestored () override
int getSize () const
void setSize (int newSize)
void setValue (DocumentObject *, const char *)
void setValues (const std::vector< DocumentObject * > &, const std::vector< const char * > &)
void setValues (const std::vector< DocumentObject * > &, const std::vector< std::string > &, std::vector< ShadowSub > &&ShadowSubList={})
void setValues (std::vector< DocumentObject * > &&, std::vector< std::string > &&subs, std::vector< ShadowSub > &&ShadowSubList={})
void setValue (App::DocumentObject *lValue, const std::vector< std::string > &SubList=std::vector< std::string >())
setValue: PropertyLinkSub-compatible overload
void addValue (App::DocumentObject *obj, const std::vector< std::string > &SubList={}, bool reset=false)
const std::vector< DocumentObject * > & getValues () const
const std::string getPyReprString () const
DocumentObject * getValue () const
getValue emulates the action of a single-object link.
const std::vector< std::string > & getSubValues () const
std::vector< std::string > getSubValues (bool newStyle) const
const std::vector< ShadowSub > & getShadowSubs () const
int removeValue (App::DocumentObject *lValue)
Removes all occurrences of lValue in the property together with its sub-elements and returns the number of entries removed.
void setSubListValues (const std::vector< SubSet > &)
std::vector< SubSet > getSubListValues (bool newStyle=false) const
PyObject * getPyObject () override
void setPyObject (PyObject *) override
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
bool upgrade (Base::XMLReader &reader, const char *typeName)
Property * Copy () const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
const char * getEditorName () const override
Get the class name of the associated property editor item.
Property * CopyOnImportExternal (const std::map< std::string, std::string > &nameMap) const override
Return a copy of the property if any changes caused by importing external object.
Property * CopyOnLabelChange (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const override
Property * CopyOnLinkReplace (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const override
unsigned int getMemSize () const override
void updateElementReference (DocumentObject *feature, bool reverse=false, bool notify=false) override
bool referenceChanged () const override
Test if the element reference has changed after restore.
void getLinks (std::vector< App::DocumentObject * > &objs, bool all=false, std::vector< std::string > *subs=nullptr, bool newStyle=true) const override
void getLinksTo (std::vector< App::ObjectIdentifier > &identifiers, App::DocumentObject *obj, const char *subname=nullptr, bool all=false) const override
void breakLink (App::DocumentObject *obj, bool clear) override
bool adjustLink (const std::set< App::DocumentObject * > &inList) override
void setSyncSubObject (bool enable)
Public Member Functions inherited from App::PropertyLinkBase
PropertyLinkBase ()
~PropertyLinkBase () override
void unregisterElementReference ()
Clear internal element reference registration.
void registerLabelReferences (std::vector< std::string > &&labels, bool reset=true)
void checkLabelReferences (const std::vector< std::string > &subs, bool reset=true)
void unregisterLabelReferences ()
Clear internal label references registration.
virtual int checkRestore (std::string *msg=nullptr) const
std::vector< App::DocumentObject * > linkedObjects (bool all=false) const
Helper function to return all linked objects of this property.
template<class T >
void getLinkedObjects (T &inserter, bool all=false) const
Helper function to return linked objects using an std::inserter.
void getLinkedElements (std::map< App::DocumentObject *, std::vector< std::string >> &elements, bool newStyle=true, bool all=false) const
Helper function to return a map of linked object and its subname references.
std::map< App::DocumentObject *, std::vector< std::string > > linkedElements (bool newStyle=true, bool all=false) const
Helper function to return a map of linked object and its subname references.
bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
void setAllowExternal (bool allow)
bool _updateElementReference (App::DocumentObject *feature, App::DocumentObject *obj, std::string &sub, ShadowSub &shadow, bool reverse, bool notify=false)
void _registerElementReference (App::DocumentObject *obj, std::string &sub, ShadowSub &shadow)
bool testFlag (int flag) const
virtual void setAllowPartial (bool enable)
void setReturnNewElement (bool enable)
void setSilentRestore (bool enable)
Public Member Functions inherited from App::Property
Property ()
~Property () override
const char * getName () const
bool hasName () const
std::string getFullName () const
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
int64_t getID () const
virtual void beforeSave () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::ScopedLink
void setScope (LinkScope scope)
Set the links scope Allows to define what kind of links are allowed. Only in the Local GeoFeatureGroup, in this and all Childs or to all objects within the Glocal scope.
LinkScope getScope () const
Get the links scope Retrieve what kind of links are allowed. Only in the Local GeoFeatureGroup, in this and all Childs or to all objects within the Glocal scope.
Additional Inherited Members
Static Public Member Functions inherited from App::PropertyLinkBase
static std::pair< App::DocumentObject *, std::string > tryReplaceLink (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const char *sub=nullptr)
Helper functions.
static std::pair< App::DocumentObject *, std::vector< std::string > > tryReplaceLinkSubs (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const std::vector< std::string > &subs)
static void updateElementReferences (DocumentObject *feature, bool reverse=false)
Update all element references in all link properties of feature.
static const std::unordered_set< PropertyLinkBase * > & getElementReferences (DocumentObject *)
Obtain link properties that contain element references to a given object.
static void breakLinks (App::DocumentObject *link, const std::vector< App::DocumentObject * > &objs, bool clear)
static std::string tryImportSubName (const App::DocumentObject *obj, const char *sub, const App::Document *doc, const std::map< std::string, std::string > &nameMap)
static App::DocumentObject * tryImport (const App::Document *doc, const App::DocumentObject *obj, const std::map< std::string, std::string > &nameMap)
static const char * exportSubName (std::string &output, const App::DocumentObject *obj, const char *subname, bool first_obj=false)
static std::string importSubName (Base::XMLReader &reader, const char *sub, bool &restoreLabel)
static void restoreLabelReference (const App::DocumentObject *obj, std::string &sub, ShadowSub *shadow=nullptr)
static void getLabelReferences (std::vector< std::string > &labels, const char *subname)
static std::vector< std::pair< Property *, std::unique_ptr< Property > > > updateLabelReferences (App::DocumentObject *obj, const char *newLabel)
static std::string updateLabelReference (const App::DocumentObject *linked, const char *subname, App::DocumentObject *obj, const std::string &ref, const char *newLabel)
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::PropertyLinkBase
boost::signals2::signal< void(const std::string &, const std::string &)> signalUpdateElementReference
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::PropertyLinkBase
void hasSetValue () override
Gets called by all setValue() methods after the value has changed.
void setFlag (int flag, bool value=true)
void _getLinksTo (std::vector< App::ObjectIdentifier > &identifiers, App::DocumentObject *obj, const char *subname, const std::vector< std::string > &subs, const std::vector< PropertyLinkBase::ShadowSub > &shadows) const
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue ()
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::PropertyLinkBase
std::bitset< 32 > _Flags
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::ScopedLink
LinkScope _pcScope = LinkScope::Local
Detailed Description
Definition at line 1053 of file PropertyLinks.h.
Member Typedef Documentation
SubSet
using App::PropertyLinkSubList::SubSet = std::pair<DocumentObject*, std::vector<std::string> >
Definition at line 1058 of file PropertyLinks.h.
Constructor & Destructor Documentation
PropertyLinkSubList()
PropertyLinkSubList::PropertyLinkSubList () default
A constructor. A more elaborate description of the constructor.
Referenced by Copy().
~PropertyLinkSubList()
PropertyLinkSubList::~PropertyLinkSubList () override
A destructor. A more elaborate description of the destructor.
Definition at line 2175 of file PropertyLinks.cpp.
References App::ScopedLink::_pcScope, App::Destroy, Base::Persistence::getClassTypeId(), App::Property::getContainer(), App::Hidden, Base::BaseClass::isDerivedFrom(), and Init::parent.
Member Function Documentation
addValue()
void PropertyLinkSubList::addValue (App::DocumentObject * obj, const std::vector< std::string > & SubList = {}, bool reset = false)
Definition at line 2426 of file PropertyLinks.cpp.
References App::DocumentObject::_addBackLink(), App::ScopedLink::_pcScope, App::Property::aboutToSetValue(), App::PropertyLinkBase::checkLabelReferences(), App::Destroy, App::Property::getContainer(), App::PropertyLinkBase::hasSetValue(), App::Hidden, SplineSurface::i, Init::parent, importers.importIFCmulticore::subs, and updateElementReference().
adjustLink()
bool PropertyLinkSubList::adjustLink (const std::set< App::DocumentObject * > & inList) override virtual
Called to adjust the link to avoid potential cyclic dependency
Parameters
inList recursive in-list of the would-be parent
Returns
Return whether the link has been adjusted
This function tries to correct the link to avoid any (sub)object inside in-list. If the adjustment is impossible, exception will be raised
Implements App::PropertyLinkBase.
Definition at line 3238 of file PropertyLinks.cpp.
References App::ScopedLink::_pcScope, App::Hidden, RobotExample::pos, setValues(), and importers.importIFCmulticore::subs.
afterRestore()
void PropertyLinkSubList::afterRestore () override virtual
Called at the beginning of Document::afterRestore()
This function is called without dependency sorting, because some types of link property can only reconstructs the linking information inside this function.
One example use case of this function is PropertyLinkSub that uses afterRestore() to parse and restore subname references, which may contain sub-object reference from external document, and there will be special mapping required during object import.
Another example is PropertyExpressionEngine which only parse the restored expression in afterRestore(). The reason, in addition to subname mapping like PropertyLinkSub, is that it can handle document name adjustment as well. It internally relies on PropertyXLink to store the external document path for external linking. When the external document is restored, its internal name may change due to name conflict with existing documents. PropertyExpressionEngine can now auto adjust external references without any problem.
Reimplemented from App::Property.
Definition at line 2723 of file PropertyLinks.cpp.
References SplineSurface::i, App::PropertyLinkBase::LinkRestoreLabel, App::PropertyLinkBase::restoreLabelReference(), App::PropertyLinkBase::setFlag(), and App::PropertyLinkBase::testFlag().
breakLink()
void PropertyLinkSubList::breakLink (App::DocumentObject * obj, bool clear) override virtual
Called to reset this link property
Parameters
obj reset link property if it is linked to this object
clear if true, then also reset property if the owner of this property is obj
See also
breakLinks()
Implements App::PropertyLinkBase.
Definition at line 3210 of file PropertyLinks.cpp.
References Path.Op.Gui.Selection::clear(), App::Property::getContainer(), SplineSurface::i, src.Mod.Test.testPathArray::o, setValues(), and importers.importIFCmulticore::subs.
Copy()
Property * PropertyLinkSubList::Copy () const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 3104 of file PropertyLinks.cpp.
References buildPsets::p, and PropertyLinkSubList().
CopyOnImportExternal()
Property * PropertyLinkSubList::CopyOnImportExternal (const std::map< std::string, std::string > & nameMap) const override virtual
Return a copy of the property if any changes caused by importing external object.
Reimplemented from App::PropertyLinkBase.
Definition at line 2944 of file PropertyLinks.cpp.
References App::Property::getContainer(), Path.Post.scripts.opensbp_post::move(), buildPsets::p, importers.importIFCmulticore::subs, App::PropertyLinkBase::tryImport(), and App::PropertyLinkBase::tryImportSubName().
CopyOnLabelChange()
Property * PropertyLinkSubList::CopyOnLabelChange (App::DocumentObject * obj, const std::string & ref, const char * newLabel) const override virtual
Update object label reference in this property
Parameters
obj the object owner of the changing label
ref subname reference to old label
newLabel the future new label
Returns
Returns a copy of the property if its link reference is affected. The copy will later be assgiend to this property by calling its Paste().
Reimplemented from App::PropertyLinkBase.
Definition at line 2989 of file PropertyLinks.cpp.
References App::Property::getContainer(), Path.Post.scripts.opensbp_post::move(), buildPsets::p, importers.importIFCmulticore::subs, and App::PropertyLinkBase::updateLabelReference().
CopyOnLinkReplace()
Property * PropertyLinkSubList::CopyOnLinkReplace (const App::DocumentObject * parent, App::DocumentObject * oldObj, App::DocumentObject * newObj) const override virtual
Return a copy of the property if the link replacement affects this property
Parameters
owner the parent object whose link property is to be replace. Note that The parent may not be the container of this property. Link sub property can use this opportunity to adjust its relative links.
oldObj object to be replaced
newObj object to replace with
Returns
Return a copy of the property that is adjusted for the link replacement operation.
Implements App::PropertyLinkBase.
Definition at line 3035 of file PropertyLinks.cpp.
References App::Property::getContainer(), Path.Post.scripts.opensbp_post::move(), buildPsets::p, Init::parent, RobotExample::pos, importers.importIFCmulticore::subs, and App::PropertyLinkBase::tryReplaceLink().
getEditorName()
const char* App::PropertyLinkSubList::getEditorName () const inline override virtual
Get the class name of the associated property editor item.
Reimplemented from App::Property.
Definition at line 1146 of file PropertyLinks.h.
getLinks()
void PropertyLinkSubList::getLinks (std::vector< App::DocumentObject * > & objs, bool all = false, std::vector< std::string > * subs = nullptr, bool newStyle = true) const override virtual
Obtain the linked objects
Parameters
objs hold the returned linked objects on output
all if true, then return all the linked object regardless of this LinkScope. If false, then return only if the LinkScope is not hidden.
sub if given, then return subname references.
newStyle whether to return new or old style subname reference
Implements App::PropertyLinkBase.
Definition at line 3144 of file PropertyLinks.cpp.
References App::ScopedLink::_pcScope, getSubValues(), App::Hidden, App::DocumentObject::isAttachedToDocument(), Path.Post.scripts.opensbp_post::move(), replaceobj::objs, and importers.importIFCmulticore::subs.
getLinksTo()
void PropertyLinkSubList::getLinksTo (std::vector< App::ObjectIdentifier > & identifiers, App::DocumentObject * obj, const char * subname = nullptr, bool all = false) const override virtual
Obtain identifiers from this link property that link to a given object
Parameters
identifiers holds the returned identifier to reference the given object
obj the referenced object
subname optional subname reference
all if true, then return all the references regardless of this LinkScope. If false, then return only if the LinkScope is not hidden.
Implements App::PropertyLinkBase.
Definition at line 3164 of file PropertyLinks.cpp.
References App::ScopedLink::_pcScope, App::SubObjectT::getOldElementName(), App::SubObjectT::getSubObject(), App::Hidden, and SplineSurface::i.
getMemSize()
unsigned int PropertyLinkSubList::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence
See also
Base::Persistence
Reimplemented from App::Property.
Definition at line 3122 of file PropertyLinks.cpp.
References getSize(), and SplineSurface::i.
getPyObject()
PyObject * PropertyLinkSubList::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 2620 of file PropertyLinks.cpp.
References src.Mod.AddonManager.NetworkManager::count, getSubListValues(), SplineSurface::i, src.Mod.Test.testPathArray::items, Py::new_reference_to(), src.Mod.Test.testmakeWireString::String, and DraftVecUtils::tup().
getPyReprString()
const string PropertyLinkSubList::getPyReprString () const
Definition at line 2494 of file PropertyLinks.cpp.
References App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), and SplineSurface::i.
Referenced by PartGui::TaskDlgAttacher::accept(), and UnifiedDatumCommand().
getShadowSubs()
const std::vector<ShadowSub>& App::PropertyLinkSubList::getShadowSubs () const inline
Definition at line 1122 of file PropertyLinks.h.
Referenced by Attacher::AttachEngine::setReferences().
getSize()
int PropertyLinkSubList::getSize () const
Definition at line 2220 of file PropertyLinks.cpp.
Referenced by Surface::Filling::execute(), getMemSize(), Surface::GeomFillSurface::onChanged(), Save(), PartGui::TaskAttacher::TaskAttacher(), and UnifiedDatumCommand().
getSubListValues()
std::vector< PropertyLinkSubList::SubSet > PropertyLinkSubList::getSubListValues (bool newStyle = false) const
Definition at line 2589 of file PropertyLinks.cpp.
References SplineSurface::i.
Referenced by SurfaceGui::FillingEdgePanel::accept(), SurfaceGui::SectionsPanel::accept(), SurfaceGui::FillingPanel::accept(), SurfaceGui::GeomFillSurface::EdgeSelection::allow(), PartDesign::Loft::execute(), Surface::Sewing::execute(), PartDesign::Pipe::execute(), getPyObject(), PartDesign::ProfileBased::getUpToShapeFromLinkSubList(), Surface::GeomFillSurface::getWire(), FemGui::ViewProviderFemConstraintOnBoundary::highlightReferences(), SurfaceGui::ViewProviderGeomFillSurface::highlightReferences(), PartDesignGui::ViewProviderLoft::highlightSection(), SurfaceGui::FillingEdgePanel::onSelectionChanged(), SurfaceGui::FillingVertexPanel::onSelectionChanged(), SurfaceGui::FillingPanel::onSelectionChanged(), SurfaceGui::FillingEdgePanel::open(), SurfaceGui::FillingVertexPanel::open(), SurfaceGui::SectionsPanel::open(), SurfaceGui::FillingPanel::open(), SurfaceGui::FillingVertexPanel::reject(), SurfaceGui::FillingEdgePanel::reject(), SurfaceGui::SectionsPanel::reject(), SurfaceGui::FillingPanel::reject(), SurfaceGui::FillingEdgePanel::slotDeletedObject(), SurfaceGui::FillingVertexPanel::slotDeletedObject(), SurfaceGui::SectionsPanel::slotDeletedObject(), SurfaceGui::FillingPanel::slotDeletedObject(), PartDesignGui::TaskLoftParameters::TaskLoftParameters(), and PartDesignGui::TaskPipeScaling::TaskPipeScaling().
getSubValues() [1/2]
const std::vector<std::string>& App::PropertyLinkSubList::getSubValues () const inline
Definition at line 1115 of file PropertyLinks.h.
Referenced by PartDesignGui::TaskDlgDatumParameters::accept(), TechDraw::DrawViewDimExtent::checkReferences2D(), TechDrawGui::TaskLinkDim::dimReferencesSelection(), Surface::Sections::execute(), Measure::MeasureLength::execute(), Measure::MeasureArea::execute(), PartDesign::ShapeBinder::getFilteredReferences(), getLinks(), Measure::MeasureLength::getPlacement(), Measure::MeasureArea::getPlacement(), Fem::Constraint::getPoints(), Attacher::AttachEngine::getShapeType(), Fem::ConstraintTransform::onChanged(), Fem::ConstraintBearing::onChanged(), Fem::Constraint::onChanged(), FemGui::TaskFemConstraint::onReferenceDeleted(), FemGui::TaskFemConstraintBearing::onSelectionChanged(), SurfaceGui::FillingEdgePanel::onSelectionChanged(), SurfaceGui::FillingVertexPanel::onSelectionChanged(), SurfaceGui::GeomFillSurface::onSelectionChanged(), SurfaceGui::FillingPanel::onSelectionChanged(), PartDesignGui::relinkToBody(), SurfaceGui::FillingEdgePanel::setEditedObject(), SurfaceGui::FillingVertexPanel::setEditedObject(), SurfaceGui::GeomFillSurface::setEditedObject(), SurfaceGui::SectionsPanel::setEditedObject(), SurfaceGui::FillingPanel::setEditedObject(), TechDrawGui::TaskDimRepair::setUiPrimary(), SketcherGui::SuggestAutoMapMode(), PartGui::TaskAttacher::TaskAttacher(), FemGui::TaskFemConstraintBearing::TaskFemConstraintBearing(), FemGui::TaskFemConstraintContact::TaskFemConstraintContact(), FemGui::TaskFemConstraintDisplacement::TaskFemConstraintDisplacement(), FemGui::TaskFemConstraintFixed::TaskFemConstraintFixed(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), FemGui::TaskFemConstraintForce::TaskFemConstraintForce(), FemGui::TaskFemConstraintHeatflux::TaskFemConstraintHeatflux(), FemGui::TaskFemConstraintInitialTemperature::TaskFemConstraintInitialTemperature(), FemGui::TaskFemConstraintPlaneRotation::TaskFemConstraintPlaneRotation(), FemGui::TaskFemConstraintPressure::TaskFemConstraintPressure(), FemGui::TaskFemConstraintSpring::TaskFemConstraintSpring(), FemGui::TaskFemConstraintTemperature::TaskFemConstraintTemperature(), FemGui::TaskFemConstraintTransform::TaskFemConstraintTransform(), and App::PropertyXLinkSubList::upgrade().
getSubValues() [2/2]
std::vector< std::string > PropertyLinkSubList::getSubValues (bool newStyle) const
Definition at line 3132 of file PropertyLinks.cpp.
References getSubNameWithStyle(), and SplineSurface::i.
getValue()
DocumentObject * PropertyLinkSubList::getValue () const
getValue emulates the action of a single-object link.
Returns
reference to object, if the link is to only one object. NULL if the link is empty, or links to subelements of more than one document object.
Definition at line 2527 of file PropertyLinks.cpp.
References SplineSurface::i.
Referenced by PartDesignGui::TaskShapeBinder::accept(), TechDraw::DrawViewDimExtent::execute(), PartDesignGui::fixSketchSupport(), PartDesign::ProfileBased::getBaseObject(), PartDesign::ProfileBased::getSupportFace(), PartDesign::ProfileBased::getTopoShapeSupportFace(), PartDesign::ProfileBased::positionByPrevious(), SketcherGui::SketchSelection::setUp(), and UnifiedDatumCommand().
getValues()
const std::vector<DocumentObject*>& App::PropertyLinkSubList::getValues () const inline
Definition at line 1100 of file PropertyLinks.h.
Referenced by PartDesignGui::TaskDlgDatumParameters::accept(), TechDraw::DrawViewDimExtent::checkReferences2D(), PartDesignGui::ViewProviderLoft::claimChildren(), PartDesignGui::ViewProviderPipe::claimChildren(), TechDrawGui::TaskLinkDim::dimReferencesSelection(), TechDraw::LandmarkDimension::execute(), Surface::Cut::execute(), Surface::Sections::execute(), Measure::MeasureLength::execute(), Measure::MeasureArea::execute(), PartDesign::ShapeBinder::getFilteredReferences(), Measure::MeasureLength::getPlacement(), Measure::MeasureArea::getPlacement(), Fem::Constraint::getPoints(), Attacher::AttachEngine::getShapeType(), Measure::MeasureLength::getSubject(), Measure::MeasureArea::getSubject(), TechDraw::LandmarkDimension::getViewPart(), PartDesignGui::ViewProviderPipe::highlightReferences(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::loadDefaults(), Fem::ConstraintTransform::onChanged(), Fem::ConstraintBearing::onChanged(), Fem::Constraint::onChanged(), TechDraw::LandmarkDimension::onDocumentRestored(), FemGui::TaskFemConstraint::onReferenceDeleted(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle(), FemGui::TaskFemConstraintBearing::onSelectionChanged(), SurfaceGui::FillingEdgePanel::onSelectionChanged(), SurfaceGui::FillingVertexPanel::onSelectionChanged(), SurfaceGui::GeomFillSurface::onSelectionChanged(), SurfaceGui::FillingPanel::onSelectionChanged(), PartDesignGui::relinkToBody(), SurfaceGui::FillingEdgePanel::setEditedObject(), SurfaceGui::FillingVertexPanel::setEditedObject(), SurfaceGui::GeomFillSurface::setEditedObject(), SurfaceGui::SectionsPanel::setEditedObject(), SurfaceGui::FillingPanel::setEditedObject(), Attacher::AttachEngine::setReferences(), FemGui::TaskFemConstraintBearing::TaskFemConstraintBearing(), FemGui::TaskFemConstraintContact::TaskFemConstraintContact(), FemGui::TaskFemConstraintDisplacement::TaskFemConstraintDisplacement(), FemGui::TaskFemConstraintFixed::TaskFemConstraintFixed(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), FemGui::TaskFemConstraintForce::TaskFemConstraintForce(), FemGui::TaskFemConstraintHeatflux::TaskFemConstraintHeatflux(), FemGui::TaskFemConstraintInitialTemperature::TaskFemConstraintInitialTemperature(), FemGui::TaskFemConstraintPlaneRotation::TaskFemConstraintPlaneRotation(), FemGui::TaskFemConstraintPressure::TaskFemConstraintPressure(), FemGui::TaskFemConstraintSpring::TaskFemConstraintSpring(), FemGui::TaskFemConstraintTemperature::TaskFemConstraintTemperature(), FemGui::TaskFemConstraintTransform::TaskFemConstraintTransform(), Part::Part2DObject::transformPlacement(), App::PropertyXLinkSubList::upgrade(), and Attacher::AttachEngine::verifyReferencesAreSafe().
onContainerRestored()
void PropertyLinkSubList::onContainerRestored () override virtual
Called before calling DocumentObject::onDocumentRestored()
This function is called after finished calling Property::afterRestore() of all properties of objects. By then, the object dependency information is assumed ready. So, unlike Property::afterRestore(), this function is called on objects with dependency order.
Reimplemented from App::Property.
Definition at line 2735 of file PropertyLinks.cpp.
References App::PropertyLinkBase::_registerElementReference(), SplineSurface::i, and App::PropertyLinkBase::unregisterElementReference().
Paste()
void PropertyLinkSubList::Paste (const Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 3113 of file PropertyLinks.cpp.
References Base::Persistence::getClassTypeId(), Base::BaseClass::isDerivedFrom(), and setValues().
referenceChanged()
bool PropertyLinkSubList::referenceChanged () const override virtual
Test if the element reference has changed after restore.
Reimplemented from App::PropertyLinkBase.
Definition at line 2792 of file PropertyLinks.cpp.
removeValue()
int PropertyLinkSubList::removeValue (App::DocumentObject * lValue)
Removes all occurrences of lValue in the property together with its sub-elements and returns the number of entries removed.
Definition at line 2542 of file PropertyLinks.cpp.
References src.Mod.AddonManager.NetworkManager::count, SplineSurface::i, setValues(), and importers.importIFCmulticore::subs.
Referenced by UnifiedDatumCommand().
Restore()
void PropertyLinkSubList::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 2852 of file PropertyLinks.cpp.
References ATTR_MAPPED, ATTR_SHADOW, ATTR_SHADOWED, Base::Console(), src.Mod.AddonManager.NetworkManager::count, App::Property::getContainer(), App::DocumentObject::getDocument(), App::Document::getObject(), SplineSurface::i, IGNORE_SHADOW, App::PropertyLinkBase::importSubName(), App::PropertyLinkBase::LinkRestoreLabel, Path.Post.scripts.opensbp_post::move(), TechDrawTools.TaskFillTemplateFields::reader, App::PropertyLinkBase::setFlag(), setValues(), and Base::ConsoleSingleton::Warning().
Referenced by PartDesign::ShapeBinder::handleChangedPropertyType(), and App::PropertyXLinkSubList::upgrade().
Save()
void PropertyLinkSubList::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 2797 of file PropertyLinks.cpp.
References ATTR_MAPPED, ATTR_SHADOW, ATTR_SHADOWED, src.Mod.AddonManager.NetworkManager::count, Base::Writer::decInd(), Base::Persistence::encodeAttribute(), App::PropertyLinkBase::exportSubName(), App::Property::getContainer(), App::DocumentObject::getExportName(), getSize(), SplineSurface::i, Base::Writer::incInd(), Base::Writer::ind(), App::DocumentObject::isAttachedToDocument(), and Base::Writer::Stream().
setPyObject()
void PropertyLinkSubList::setPyObject (PyObject * value) override virtual
Reimplemented from Base::BaseClass.
Definition at line 2646 of file PropertyLinks.cpp.
References App::PropertyLinkSub::getSubValues(), App::PropertyString::getValue(), App::PropertyLinkSub::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), SplineSurface::i, App::PropertyListsT< T, ListT, ParentT >::setPyObject(), App::PropertyString::setPyObject(), App::PropertyLinkSub::setPyObject(), setValue(), setValues(), and importers.importIFCmulticore::subs.
setSize()
void PropertyLinkSubList::setSize (int newSize)
Definition at line 2213 of file PropertyLinks.cpp.
setSubListValues()
void PropertyLinkSubList::setSubListValues (const std::vector< SubSet > & values)
Definition at line 2567 of file PropertyLinks.cpp.
References setValues(), and importers.importIFCmulticore::subs.
setSyncSubObject()
void PropertyLinkSubList::setSyncSubObject (bool enable)
Definition at line 2196 of file PropertyLinks.cpp.
References App::PropertyLinkBase::_Flags, and App::PropertyLinkBase::LinkSyncSubObject.
setValue() [1/2]
void PropertyLinkSubList::setValue (App::DocumentObject * lValue, const std::vector< std::string > & SubList = std::vector<std::string>())
setValue: PropertyLinkSub-compatible overload
Parameters
SubList
Definition at line 2379 of file PropertyLinks.cpp.
References App::DocumentObject::_addBackLink(), App::ScopedLink::_pcScope, App::DocumentObject::_removeBackLink(), App::Property::aboutToSetValue(), App::PropertyLinkBase::checkLabelReferences(), App::Destroy, App::Property::getContainer(), App::PropertyLinkBase::hasSetValue(), App::Hidden, Init::parent, and updateElementReference().
setValue() [2/2]
void PropertyLinkSubList::setValue (DocumentObject * lValue, const char * SubName)
Sets the property. setValue(0, whatever) clears the property
Definition at line 2225 of file PropertyLinks.cpp.
References App::DocumentObject::_addBackLink(), App::ScopedLink::_pcScope, App::DocumentObject::_removeBackLink(), App::Property::aboutToSetValue(), App::PropertyLinkBase::checkLabelReferences(), App::Destroy, App::Property::getContainer(), App::PropertyLinkBase::hasSetValue(), App::Hidden, Init::parent, and updateElementReference().
Referenced by TechDraw::LandmarkDimension::execute(), Attacher::AttachEngine::getShapeType(), PartDesignGui::TaskFeaturePick::makeCopy(), setPyObject(), TechDrawGui::TaskLinkDim::updateDims(), and upgrade().
setValues() [1/3]
void PropertyLinkSubList::setValues (const std::vector< DocumentObject * > & lValue, const std::vector< const char * > & lSubNames)
Definition at line 2265 of file PropertyLinks.cpp.
References App::DocumentObject::_addBackLink(), App::ScopedLink::_pcScope, App::DocumentObject::_removeBackLink(), App::Property::aboutToSetValue(), App::PropertyLinkBase::checkLabelReferences(), App::Destroy, App::Property::getContainer(), App::PropertyLinkBase::hasSetValue(), App::Hidden, SplineSurface::i, Init::parent, and updateElementReference().
Referenced by TechDrawGui::_createLinDimension(), PartDesignGui::TaskDlgDatumParameters::accept(), adjustLink(), breakLink(), Gui::SelectionSingleton::getAsPropertyLinkSubList(), TechDraw::DrawDimHelper::makeDistDim(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle(), FemGui::TaskFemConstraint::onReferenceDeleted(), FemGui::TaskFemConstraintBearing::onSelectionChanged(), SurfaceGui::FillingEdgePanel::onSelectionChanged(), SurfaceGui::FillingVertexPanel::onSelectionChanged(), SurfaceGui::GeomFillSurface::onSelectionChanged(), SurfaceGui::FillingPanel::onSelectionChanged(), Measure::MeasureLength::parseSelection(), Measure::MeasureArea::parseSelection(), Paste(), removeValue(), Restore(), setPyObject(), setSubListValues(), TechDrawGui::TaskLinkDim::updateDims(), and upgrade().
setValues() [2/3]
void App::PropertyLinkSubList::setValues (const std::vector< DocumentObject * > & , const std::vector< std::string > & , std::vector< ShadowSub > && ShadowSubList = {})
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle().
setValues() [3/3]
void App::PropertyLinkSubList::setValues (std::vector< DocumentObject * > && , std::vector< std::string > && subs, std::vector< ShadowSub > && ShadowSubList = {})
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle().
updateElementReference()
void PropertyLinkSubList::updateElementReference (DocumentObject * feature, bool reverse = false, bool notify = false) override virtual
Link type property interface APIs These APIs are moved here so that any type of property can have the property link behavior, e.g. the PropertyExpressionEngine Called to update the element reference of this link property
See also
_updateElementReference()
Reimplemented from App::PropertyLinkBase.
Definition at line 2743 of file PropertyLinks.cpp.
References App::PropertyLinkBase::_updateElementReference(), App::Property::getContainer(), App::PropertyLinkBase::hasSetValue(), SplineSurface::i, femsolver.signal::notify(), and App::PropertyLinkBase::unregisterElementReference().
Referenced by addValue(), setValue(), and setValues().
upgrade()
bool PropertyLinkSubList::upgrade (Base::XMLReader & reader, const char * typeName)
Definition at line 2913 of file PropertyLinks.cpp.
References Base::Type::fromName(), Base::Persistence::getClassTypeId(), App::Property::getContainer(), App::PropertyListsT< T, ListT, ParentT >::getSize(), App::PropertyLinkSub::getSubValues(), App::PropertyLink::getValue(), App::PropertyLinkSub::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), TechDrawTools.TaskFillTemplateFields::reader, App::PropertyLink::Restore(), App::PropertyLinkList::Restore(), App::PropertyLinkSub::Restore(), App::Property::setContainer(), setValue(), setValues(), and Path.Post.scripts.grbl_post::type.
Referenced by PartDesign::Loft::handleChangedPropertyType(), and PartDesign::Pipe::handleChangedPropertyType().
The documentation for this class was generated from the following files:
PropertyLinks.h
PropertyLinks.cpp