FreeCAD: Gui::Dialog::DocumentRecoveryHandler Class Reference
Gui::Dialog::DocumentRecoveryHandler Class Reference
#include <DocumentRecovery.h>
Public Member Functions
void checkForPreviousCrashes (const std::function< void(QDir &, const QList< QFileInfo > &, const QString &)> &callableFunc) const
Detailed Description
Definition at line 121 of file DocumentRecovery.h.
Member Function Documentation
checkForPreviousCrashes()
void DocumentRecoveryHandler::checkForPreviousCrashes (const std::function< void(QDir &, const QList< QFileInfo > &, const QString &)> & callableFunc) const
Definition at line 646 of file DocumentRecovery.cpp.
References App::Application::applicationPid(), Base::Console(), App::Application::getExecutableName(), App::Application::getUserCachePath(), Base::ConsoleSingleton::Log(), and Path.Post.scripts.refactored_centroid_post::str.
The documentation for this class was generated from the following files:
DocumentRecovery.h
DocumentRecovery.cpp