FreeCAD: Gui::TreeWidgetItemDelegate Class Reference
Gui::TreeWidgetItemDelegate Class Reference
Public Member Functions
TreeWidgetItemDelegate (QObject *parent=nullptr)
virtual QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &, const QModelIndex &index) const
virtual QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual void initStyleOption (QStyleOptionViewItem *option, const QModelIndex &index) const
virtual void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
Detailed Description
TreeWidget item delegate for editing
Definition at line 406 of file Tree.cpp.
Constructor & Destructor Documentation
TreeWidgetItemDelegate()
TreeWidgetItemDelegate::TreeWidgetItemDelegate (QObject * parent = nullptr) explicit
Definition at line 438 of file Tree.cpp.
References Init::parent.
Member Function Documentation
createEditor()
QWidget * TreeWidgetItemDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & , const QModelIndex & index) const virtual
Definition at line 569 of file Tree.cpp.
References Gui::ExpLineEdit::bind(), Path.Post.Utils::editor(), FC_LOG, App::GetApplication(), Gui::TreeParams::getLabelExpression(), App::DocumentObject::getNameInDocument(), App::DocumentObject::Label, App::DocumentObject::Label2, Gui::TreeWidget::ObjectType, Init::parent, App::Application::setActiveTransaction(), Gui::ExpressionBinding::setAutoApply(), and Path.Post.scripts.refactored_centroid_post::str.
initStyleOption()
void TreeWidgetItemDelegate::initStyleOption (QStyleOptionViewItem * option, const QModelIndex & index) const virtual
Definition at line 507 of file Tree.cpp.
References Gui::TreeWidget::iconSize(), isOnlyNameColumnDisplayed(), Init::parent, and RobotExample::pos.
Referenced by paint().
paint()
void TreeWidgetItemDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
Definition at line 477 of file Tree.cpp.
References _TreeItemBackground, initStyleOption(), isOnlyNameColumnDisplayed(), and Init::parent.
sizeHint()
QSize TreeWidgetItemDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
Definition at line 598 of file Tree.cpp.
References Gui::TreeParams::getItemSpacing(), and KDL::max().
The documentation for this class was generated from the following file:
Tree.cpp