FreeCAD: Gui::TextEdit Class Reference
Gui::TextEdit Class Reference
#include <TextEdit.h>
Signals
void showSearchBar ()
void findNext ()
void findPrevious ()
Public Member Functions
TextEdit (QWidget *parent=nullptr)
~TextEdit () override
Protected Member Functions
void keyPressEvent (QKeyEvent *) override
void wheelEvent (QWheelEvent *e) override
Detailed Description
Definition at line 75 of file Gui/TextEdit.h.
Constructor & Destructor Documentation
TextEdit()
TextEdit::TextEdit (QWidget * parent = nullptr) explicit
Constructs a TextEdit which is a child of 'parent'.
Definition at line 46 of file Gui/TextEdit.cpp.
References draftgeoutils.intersections::connect(), findNext(), findPrevious(), and showSearchBar().
~TextEdit()
TextEdit::~TextEdit () override default
Destroys the object and frees any allocated resources
Member Function Documentation
findNext
void Gui::TextEdit::findNext () signal
Referenced by Gui::EditorView::EditorView(), and TextEdit().
findPrevious
void Gui::TextEdit::findPrevious () signal
Referenced by Gui::EditorView::EditorView(), and TextEdit().
keyPressEvent()
void TextEdit::keyPressEvent (QKeyEvent * e) override protected
Set the approproriate item of the completion box or hide it, if needed.
Definition at line 78 of file Gui/TextEdit.cpp.
References SCL.SimpleDataTypes::e.
Referenced by Gui::PythonTextEditor::keyPressEvent().
showSearchBar
void Gui::TextEdit::showSearchBar () signal
Referenced by Gui::EditorView::EditorView(), and TextEdit().
wheelEvent()
void TextEdit::wheelEvent (QWheelEvent * e) override protected
Definition at line 99 of file Gui/TextEdit.cpp.
References SCL.SimpleDataTypes::e.
The documentation for this class was generated from the following files:
Gui/TextEdit.h
Gui/TextEdit.cpp