FreeCAD: PartGui::DlgSettings3DViewPart Class Reference
PartGui::DlgSettings3DViewPart Class Reference
#include <DlgSettings3DViewPartImp.h>
Public Member Functions
DlgSettings3DViewPart (QWidget *parent=nullptr)
~DlgSettings3DViewPart () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void saveSettings () override
void loadSettings () override
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
The DlgSettings3DViewPartImp class implements a preference page to change settings for the Inventor viewer.
Author
Jürgen Riegel
Definition at line 57 of file DlgSettings3DViewPartImp.h.
Constructor & Destructor Documentation
DlgSettings3DViewPart()
DlgSettings3DViewPart::DlgSettings3DViewPart (QWidget * parent = nullptr) explicit
Constructs a DlgSettings3DViewPart which is a child of 'parent', with the name 'name' and widget flags set to 'f'
Definition at line 44 of file DlgSettings3DViewPartImp.cpp.
References draftgeoutils.intersections::connect(), App::GetApplication(), ParameterGrp::GetFloat(), and App::Application::GetParameterGroupByPath().
~DlgSettings3DViewPart()
DlgSettings3DViewPart::~DlgSettings3DViewPart () override default
Destroys the object and frees any allocated resources
Member Function Documentation
changeEvent()
void DlgSettings3DViewPart::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 135 of file DlgSettings3DViewPartImp.cpp.
References SCL.SimpleDataTypes::e.
loadSettings()
void DlgSettings3DViewPart::loadSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 126 of file DlgSettings3DViewPartImp.cpp.
saveSettings()
void DlgSettings3DViewPart::saveSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 110 of file DlgSettings3DViewPartImp.cpp.
References toolbit-attributes::doc, App::GetApplication(), Base::Persistence::getClassTypeId(), Gui::Application::getDocument(), App::Application::getDocuments(), and Gui::Application::Instance.
The documentation for this class was generated from the following files:
DlgSettings3DViewPartImp.h
DlgSettings3DViewPartImp.cpp