FreeCAD: Gui::OpenGLBuffer Class Reference
Gui::OpenGLBuffer Class Reference
#include <GLBuffer.h>
Public Member Functions
OpenGLBuffer (GLenum type)
~OpenGLBuffer ()
void setCurrentContext (uint32_t ctx)
bool create ()
bool isCreated () const
void destroy ()
void allocate (const void *data, int count)
bool bind ()
void release ()
GLuint getBufferId () const
uint32_t getBoundContext () const
int size () const
Static Public Member Functions
static bool isVBOSupported (uint32_t ctx)
OpenGLBuffer::isVBOSupported returns if the OpenGL driver supports the VBO extension. When calling this function there must be a current OpenGL context.
Detailed Description
Definition at line 53 of file GLBuffer.h.
Constructor & Destructor Documentation
OpenGLBuffer()
OpenGLBuffer::OpenGLBuffer (GLenum type)
Definition at line 53 of file GLBuffer.cpp.
~OpenGLBuffer()
OpenGLBuffer::~OpenGLBuffer ()
Definition at line 63 of file GLBuffer.cpp.
References destroy().
Member Function Documentation
allocate()
void OpenGLBuffer::allocate (const void * data, int count)
Definition at line 122 of file GLBuffer.cpp.
References src.Mod.AddonManager.NetworkManager::count.
bind()
bool OpenGLBuffer::bind ()
Definition at line 129 of file GLBuffer.cpp.
create()
bool OpenGLBuffer::create ()
Definition at line 94 of file GLBuffer.cpp.
Referenced by draftguitools.gui_labels.Label::action().
destroy()
void OpenGLBuffer::destroy ()
Definition at line 112 of file GLBuffer.cpp.
Referenced by ~OpenGLBuffer().
getBoundContext()
uint32_t OpenGLBuffer::getBoundContext () const
Definition at line 156 of file GLBuffer.cpp.
getBufferId()
GLuint OpenGLBuffer::getBufferId () const
Definition at line 151 of file GLBuffer.cpp.
isCreated()
bool OpenGLBuffer::isCreated () const
Definition at line 107 of file GLBuffer.cpp.
isVBOSupported()
bool OpenGLBuffer::isVBOSupported (uint32_t ctx) static
OpenGLBuffer::isVBOSupported returns if the OpenGL driver supports the VBO extension. When calling this function there must be a current OpenGL context.
Returns
Definition at line 76 of file GLBuffer.cpp.
References create_qrc::ext, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by MeshGui::MeshRenderer::Private::canRenderGLArray().
release()
void OpenGLBuffer::release ()
Definition at line 144 of file GLBuffer.cpp.
setCurrentContext()
void OpenGLBuffer::setCurrentContext (uint32_t ctx)
Definition at line 88 of file GLBuffer.cpp.
size()
int OpenGLBuffer::size () const
Definition at line 161 of file GLBuffer.cpp.
Referenced by Path.Post.Utils.GCodeEditorDialog::done().
The documentation for this class was generated from the following files:
GLBuffer.h
GLBuffer.cpp