FreeCAD: SketcherGui::EditModeConstraintCoinManager Class Reference
SketcherGui::EditModeConstraintCoinManager Class Reference
Class for managing the Edit mode coin nodes of ViewProviderSketch relating to constraints.
#include <EditModeConstraintCoinManager.h>
Public Member Functions
EditModeConstraintCoinManager (ViewProviderSketch &vp, DrawingParameters &drawingParams, GeometryLayerParameters &geometryLayerParams, ConstraintParameters &constraintParams, EditModeScenegraphNodes &editModeScenegraph, CoinMapping &coinMap)
~EditModeConstraintCoinManager ()
update coin nodes
void processConstraints (const GeoListFacade &geolistfacade)
void updateVirtualSpace ()
void drawConstraintIcons ()
Draw all constraint icons.
void drawConstraintIcons (const GeoListFacade &geolistfacade)
update coin colors
void updateConstraintColor (const std::vector< Sketcher::Constraint * > &constraints)
coin nodes creation
void rebuildConstraintNodes ()
change constraints selectability
void setConstraintSelectability (bool enabled=true)
std::set< int > detectPreselectionConstr (const SoPickedPoint *Point, const SbVec2s &cursorPos)
SoSeparator * getConstraintIdSeparator (int i)
void createEditModeInventorNodes ()
Detailed Description
Class for managing the Edit mode coin nodes of ViewProviderSketch relating to constraints.
To be documented.
Definition at line 80 of file EditModeConstraintCoinManager.h.
Constructor & Destructor Documentation
EditModeConstraintCoinManager()
EditModeConstraintCoinManager::EditModeConstraintCoinManager (ViewProviderSketch & vp, DrawingParameters & drawingParams, GeometryLayerParameters & geometryLayerParams, ConstraintParameters & constraintParams, EditModeScenegraphNodes & editModeScenegraph, CoinMapping & coinMap) explicit
Definition at line 74 of file EditModeConstraintCoinManager.cpp.
~EditModeConstraintCoinManager()
EditModeConstraintCoinManager::~EditModeConstraintCoinManager ()
Definition at line 89 of file EditModeConstraintCoinManager.cpp.
Member Function Documentation
createEditModeInventorNodes()
void EditModeConstraintCoinManager::createEditModeInventorNodes ()
Definition at line 2965 of file EditModeConstraintCoinManager.cpp.
References SketcherGui::EditModeScenegraphNodes::ConstraintDrawStyle, SketcherGui::EditModeScenegraphNodes::constrGroup, SketcherGui::EditModeScenegraphNodes::constrGrpSelect, SketcherGui::EditModeScenegraphNodes::EditRoot, MeshCore::MeshIO::OVERALL, SketcherGui::DrawingParameters::pixelScalingFactor, and setConstraintSelectability().
detectPreselectionConstr()
std::set< int > EditModeConstraintCoinManager::detectPreselectionConstr (const SoPickedPoint * Point, const SbVec2s & cursorPos)
Definition at line 2195 of file EditModeConstraintCoinManager.cpp.
References SketcherGui::SoZoomTranslation::abPos, SCL.SimpleDataTypes::b, Base::Console(), SketcherGui::EditModeScenegraphNodes::constrGroup, SplineSurface::i, and Base::ConsoleSingleton::Log().
drawConstraintIcons() [1/2]
void EditModeConstraintCoinManager::drawConstraintIcons ()
Draw all constraint icons.
Except maybe the radius and lock ones?
Definition at line 2370 of file EditModeConstraintCoinManager.cpp.
drawConstraintIcons() [2/2]
void EditModeConstraintCoinManager::drawConstraintIcons (const GeoListFacade & geolistfacade)
Definition at line 2377 of file EditModeConstraintCoinManager.cpp.
References Base::Console(), SketcherGui::EditModeScenegraphNodes::constrGroup, Base::ConsoleSingleton::DeveloperWarning(), Sketcher::Equal, Sketcher::Constraint::First, Sketcher::Constraint::FirstPos, Sketcher::GeoUndef, Sketcher::GeoListModel< T >::getGeometryFromGeoId(), Sketcher::GeoListModel< T >::getPoint(), Sketcher::Horizontal, Base::BaseClass::is(), Sketcher::Constraint::isInVirtualSpace, KDL::min(), Sketcher::Constraint::Name, Sketcher::none, Sketcher::Parallel, Sketcher::Perpendicular, RobotExampleTrajectoryOutOfShapes::pos1, Sketcher::Constraint::Second, Sketcher::Constraint::SecondPos, Sketcher::Symmetric, Sketcher::Tangent, Sketcher::Constraint::Third, Sketcher::Constraint::Type, Sketcher::Vertical, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
getConstraintIdSeparator()
SoSeparator * EditModeConstraintCoinManager::getConstraintIdSeparator (int i)
Definition at line 2960 of file EditModeConstraintCoinManager.cpp.
References SketcherGui::EditModeScenegraphNodes::constrGroup, and SplineSurface::i.
processConstraints()
void EditModeConstraintCoinManager::processConstraints (const GeoListFacade & geolistfacade)
Definition at line 115 of file EditModeConstraintCoinManager.cpp.
References SketcherGui::SoZoomTranslation::abPos, Base::Vector2d::Angle(), Path.Post.scripts.uccnc_post::append(), KDL::atan2(), Sketcher::Block, src.Mod.PartDesign.Scripts.Gear::c1, exportCSG::center(), Sketcher::Coincident, Base::Console(), SketcherGui::EditModeScenegraphNodes::constrGroup, KDL::cos(), Gui::SoDatumLabel::datumtype, Base::ConsoleSingleton::DeveloperError(), Sketcher::Diameter, Sketcher::Distance, Sketcher::DistanceX, Sketcher::DistanceY, Base::Vector3< float_type >::Dot(), SCL.SimpleDataTypes::e, Sketcher::Equal, Sketcher::Constraint::First, Sketcher::Constraint::FirstPos, Sketcher::GeoListModel< T >::geomlist, Sketcher::GeoUndef, Part::GeomConic::getCenter(), Part::GeomArcOfConic::getCenter(), SketcherGui::GetCirclesMinimalDistance(), Part::GeomBoundedCurve::getEndPoint(), Part::GeomLineSegment::getEndPoint(), Sketcher::GeoListModel< T >::getExternalCount(), Part::GeomArcOfParabola::getFocal(), Part::GeomArcOfParabola::getFocus(), Sketcher::GeoListModel< T >::getGeometryFromGeoId(), Sketcher::GeoListModel< T >::getInternalCount(), Part::GeomArcOfEllipse::getMajorAxisDir(), Part::GeomArcOfHyperbola::getMajorAxisDir(), Part::GeomArcOfEllipse::getMajorRadius(), Part::GeomArcOfHyperbola::getMajorRadius(), Part::GeomArcOfEllipse::getMinorRadius(), Part::GeomArcOfHyperbola::getMinorRadius(), draftgeoutils.geometry::getNormal, Sketcher::GeoListModel< T >::getPoint(), Part::GeomBSplineCurve::getPoles(), Part::GeomCircle::getRadius(), Part::GeomArcOfCircle::getRadius(), Sketcher::getRadiusCenterCircleArc(), Part::GeomArcOfEllipse::getRange(), Part::GeomArcOfHyperbola::getRange(), Part::GeomArcOfParabola::getRange(), Part::GeomBoundedCurve::getStartPoint(), Part::GeomLineSegment::getStartPoint(), Sketcher::Constraint::getValue(), Part::GeomArcOfConic::getXAxisDir(), Sketcher::Horizontal, SplineSurface::i, Sketcher::InternalAlignment, intersection(), Base::BaseClass::is(), Sketcher::isArcOfCircle(), Sketcher::isCircleOrArc(), Sketcher::isLineSegment(), src.Mod.PartDesign.Scripts.Gear::l1, Sketcher::Constraint::LabelDistance, Sketcher::Constraint::LabelPosition, Base::Vector3< float_type >::Length(), FreeCADInit::Length, M_PI, Gui::None, Sketcher::none, Base::Vector3< float_type >::Normalize(), Sketcher::NumConstraintTypes, buildPsets::p, Sketcher::Parallel, Gui::SoDatumLabel::param1, Gui::SoDatumLabel::param2, Gui::SoDatumLabel::param3, Gui::SoDatumLabel::param4, Gui::SoDatumLabel::param5, Sketcher::Perpendicular, Gui::SoDatumLabel::pnts, Sketcher::PointOnObject, RobotExample::pos, Base::Vector3< float_type >::ProjectToLine(), Sketcher::Radius, rebuildConstraintNodes(), Base::Vector3< float_type >::RotateZ(), Sketcher::Constraint::Second, Sketcher::Constraint::SecondPos, KDL::sin(), Sketcher::SnellsLaw, Gui::SoDatumLabel::string, Sketcher::Symmetric, Sketcher::Tangent, Sketcher::Constraint::Third, Sketcher::Constraint::ThirdPos, toVector2d(), Sketcher::Constraint::Type, updateVirtualSpace(), TestSpreadsheet::v, Sketcher::Vertical, src.Mod.PartDesign.fcgear.svggear::w, Sketcher::Weight, MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, Base::Vector3< float_type >::y, Base::Vector3< float_type >::z, and SketcherGui::DrawingParameters::zConstr.
rebuildConstraintNodes()
void EditModeConstraintCoinManager::rebuildConstraintNodes ()
Definition at line 1890 of file EditModeConstraintCoinManager.cpp.
Referenced by processConstraints().
setConstraintSelectability()
void EditModeConstraintCoinManager::setConstraintSelectability (bool enabled = true)
Definition at line 1897 of file EditModeConstraintCoinManager.cpp.
References SketcherGui::EditModeScenegraphNodes::constrGrpSelect.
Referenced by createEditModeInventorNodes().
updateConstraintColor()
void EditModeConstraintCoinManager::updateConstraintColor (const std::vector< Sketcher::Constraint * > & constraints)
Definition at line 1723 of file EditModeConstraintCoinManager.cpp.
References Sketcher::Constraint::AlignmentType, Sketcher::Angle, Sketcher::BSplineControlPoint, Sketcher::BSplineKnotPoint, Sketcher::Coincident, SketcherGui::DrawingParameters::ConstrDimColor, SketcherGui::EditModeScenegraphNodes::constrGroup, SketcherGui::EditModeScenegraphNodes::CurvesMaterials, SketcherGui::DrawingParameters::DeactivatedConstrDimColor, Sketcher::Diameter, Sketcher::Distance, Sketcher::DistanceX, Sketcher::DistanceY, Sketcher::EllipseFocus1, Sketcher::EllipseFocus2, Sketcher::EllipseMajorDiameter, Sketcher::EllipseMinorDiameter, SketcherGui::DrawingParameters::ExprBasedConstrDimColor, SketcherGui::MultiFieldId::fieldIndex, Sketcher::Constraint::First, Sketcher::Constraint::FirstPos, SketcherGui::GeometryLayerParameters::getCoinLayerCount(), SketcherGui::CoinMapping::getIndexLayer(), SketcherGui::GeometryLayerParameters::getSubLayerCount(), Sketcher::HyperbolaFocus, Sketcher::HyperbolaMajor, Sketcher::HyperbolaMinor, SplineSurface::i, Sketcher::InternalAlignment, SketcherGui::MultiFieldId::Invalid, Sketcher::Constraint::isActive, Sketcher::Constraint::isDriving, RobotExample::l, test::m, KDL::min(), SketcherGui::DrawingParameters::NonDrivingConstrDimColor, Sketcher::none, Sketcher::ParabolaFocalAxis, Sketcher::ParabolaFocus, SketcherGui::EditModeScenegraphNodes::PointsMaterials, RobotExample::pos, SketcherGui::DrawingParameters::PreselectColor, Sketcher::Radius, toolbit-attributes::s, Sketcher::Constraint::Second, Sketcher::Constraint::SecondPos, SketcherGui::DrawingParameters::SelectColor, Sketcher::Symmetric, InitGui::t, Path.Post.scripts.grbl_post::type, Sketcher::Constraint::Type, and Sketcher::Weight.
updateVirtualSpace()
void EditModeConstraintCoinManager::updateVirtualSpace ()
Definition at line 92 of file EditModeConstraintCoinManager.cpp.
References SketcherGui::EditModeScenegraphNodes::constrGroup, SmSwitchboard::enable, and SplineSurface::i.
Referenced by processConstraints().
The documentation for this class was generated from the following files:
EditModeConstraintCoinManager.h
EditModeConstraintCoinManager.cpp