FreeCAD: MeshCore::PlaneFit Class Reference
MeshCore::PlaneFit Class Reference
#include <Approximation.h>
Public Member Functions
PlaneFit ()
Base::Vector3f GetBase () const
Base::Vector3f GetDirU () const
Base::Vector3f GetDirV () const
Base::Vector3f GetNormal () const
float Fit () override
float GetDistanceToPlane (const Base::Vector3f &rcPoint) const
float GetStdDeviation () const
float GetSignedStdDeviation () const
void ProjectToPlane ()
void Dimension (float &length, float &width) const
std::vector< Base::Vector3f > GetLocalPoints () const
Base::BoundBox3f GetBoundings () const
Public Member Functions inherited from MeshCore::Approximation
Approximation ()
virtual ~Approximation ()
void AddPoint (const Base::Vector3f &point)
void AddPoints (const std::vector< Base::Vector3f > &points)
void AddPoints (const std::set< Base::Vector3f > &points)
void AddPoints (const std::list< Base::Vector3f > &points)
void AddPoints (const MeshPointArray &points)
const std::list< Base::Vector3f > & GetPoints () const
Base::Vector3f GetGravity () const
std::size_t CountPoints () const
void Clear ()
float GetLastResult () const
bool Done () const
Protected Attributes
Base::Vector3f _vBase
Base::Vector3f _vDirU
Base::Vector3f _vDirV
Base::Vector3f _vDirW
Protected Attributes inherited from MeshCore::Approximation
std::list< Base::Vector3f > _vPoints
bool _bIsFitted {false}
float _fLastResult {FLOAT_MAX}
Additional Inherited Members
Protected Member Functions inherited from MeshCore::Approximation
void GetMgcVectorArray (std::vector< Wm4::Vector3< double >> &rcPts) const
Approximation (const Approximation &)=default
Approximation (Approximation &&)=default
Approximation & operator= (const Approximation &)=default
Approximation & operator= (Approximation &&)=default
Detailed Description
Approximation of a plane into a given set of points.
Definition at line 213 of file Approximation.h.
Constructor & Destructor Documentation
PlaneFit()
PlaneFit::PlaneFit ()
Definition at line 135 of file Approximation.cpp.
Member Function Documentation
Dimension()
void PlaneFit::Dimension (float & length, float & width) const
Get the dimension of the fitted plane.
Definition at line 408 of file Approximation.cpp.
References _vBase, _vDirU, _vDirV, MeshCore::Approximation::_vPoints, Base::BoundBox3< Precision >::Add(), SplineSurface::bs, Base::BoundBox3< Precision >::MaxX, Base::BoundBox3< Precision >::MaxY, Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, and Base::Vector3< float_type >::TransformToCoordinateSystem().
Fit()
float PlaneFit::Fit () override virtual
Fit a plane into the given points. We must have at least three non-collinear points to succeed. If the fit fails FLOAT_MAX is returned.
Implements MeshCore::Approximation.
Reimplemented in MeshCore::SurfaceFit.
Definition at line 142 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, MeshCore::Approximation::_fLastResult, _vBase, _vDirU, _vDirV, _vDirW, MeshCore::Approximation::_vPoints, MeshCore::Approximation::CountPoints(), Wm4::Vector3< Real >::Dot(), Wm4::Matrix3< Real >::EigenDecomposition(), FLOAT_MAX, Wm4::Vector3< Real >::GenerateOrthonormalBasis(), Wm4::Matrix3< Real >::GetColumn(), SplineSurface::i, Base::Vector3< float_type >::Set(), KDL::sqrt(), buildPsets::u, TestSpreadsheet::v, src.Mod.PartDesign.fcgear.svggear::w, Wm4::Vector3< Real >::X(), Wm4::Vector3< Real >::Y(), and Wm4::Vector3< Real >::Z().
Referenced by ReverseEngineeringGui::Segmentation::accept(), MeshCore::MeshPlaneVisitor::AllowVisit(), Reen::ParameterCorrection::CalcEigenvectors(), MeshCore::MeshEigensystem::CalculateLocalSystem(), MeshCore::PlaneSurfaceFit::Fit(), MeshCore::CylinderFit::GetInitialAxisFromNormals(), MeshCore::MeshRefPointToPoints::GetNormal(), MeshGui::PlaneFitParameter::getParameter(), MeshCore::AbstractPolygonTriangulator::GetTransformToFitPlane(), MeshCore::PlaneSurfaceFit::Initialize(), ReverseEngineeringGui::SegmentationManual::onPlaneDetectClicked(), MeshCore::PlaneFitSmoothing::Smooth(), MeshCore::PlaneFitSmoothing::SmoothPoints(), and MeshCore::MeshDistancePlanarSegment::TestFacet().
GetBase()
Base::Vector3f PlaneFit::GetBase () const
Definition at line 283 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, and _vBase.
Referenced by ReverseEngineeringGui::Segmentation::accept(), MeshCore::MeshEigensystem::CalculateLocalSystem(), MeshGui::PlaneFitParameter::getParameter(), MeshCore::AbstractPolygonTriangulator::GetTransformToFitPlane(), ReverseEngineeringGui::SegmentationManual::onPlaneDetectClicked(), and MeshCore::PlaneSurfaceFit::Parameters().
GetBoundings()
Base::BoundBox3f PlaneFit::GetBoundings () const
Returns the local bounding box of the transformed points relative to the coordinate system of the plane. If this method is called before the plane is computed an invalid bounding box is returned.
Definition at line 448 of file Approximation.cpp.
References Base::BoundBox3< Precision >::Add(), and GetLocalPoints().
GetDirU()
Base::Vector3f PlaneFit::GetDirU () const
Definition at line 292 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, and _vDirU.
Referenced by Reen::ParameterCorrection::CalcEigenvectors(), MeshCore::MeshEigensystem::CalculateLocalSystem(), and MeshCore::AbstractPolygonTriangulator::GetTransformToFitPlane().
GetDirV()
Base::Vector3f PlaneFit::GetDirV () const
Definition at line 301 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, and _vDirV.
Referenced by Reen::ParameterCorrection::CalcEigenvectors(), MeshCore::MeshEigensystem::CalculateLocalSystem(), and MeshCore::AbstractPolygonTriangulator::GetTransformToFitPlane().
GetDistanceToPlane()
float PlaneFit::GetDistanceToPlane (const Base::Vector3f & rcPoint) const
Returns the distance from the point rcPoint to the fitted plane. If Fit() has not been called FLOAT_MAX is returned.
Definition at line 319 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, _vBase, _vDirW, and FLOAT_MAX.
Referenced by MeshCore::MeshPlaneVisitor::AllowVisit(), MeshCore::PlaneSurfaceFit::GetDistanceToSurface(), GetSignedStdDeviation(), GetStdDeviation(), and MeshCore::MeshDistancePlanarSegment::TestFacet().
GetLocalPoints()
std::vector< Base::Vector3f > PlaneFit::GetLocalPoints () const
Returns an array of the transformed points relative to the coordinate system of the plane. If this method is called before the plane is computed an empty array is returned.
Definition at line 426 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, MeshCore::Approximation::_fLastResult, _vBase, _vDirU, _vDirV, MeshCore::Approximation::_vPoints, SplineSurface::bs, FLOAT_MAX, Base::Vector3< float_type >::TransformToCoordinateSystem(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by GetBoundings().
GetNormal()
Base::Vector3f PlaneFit::GetNormal () const
Returns the normal of the fitted plane. If Fit() has not been called the null vector is returned.
Definition at line 310 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, and _vDirW.
Referenced by ReverseEngineeringGui::Segmentation::accept(), Reen::ParameterCorrection::CalcEigenvectors(), MeshCore::MeshEigensystem::CalculateLocalSystem(), MeshCore::FacetCurvature::Compute(), MeshCore::CylinderFit::GetInitialAxisFromNormals(), MeshCore::MeshRefPointToPoints::GetNormal(), MeshGui::PlaneFitParameter::getParameter(), GetSignedStdDeviation(), MeshCore::AbstractPolygonTriangulator::GetTransformToFitPlane(), ReverseEngineeringGui::SegmentationManual::onPlaneDetectClicked(), MeshCore::PlaneSurfaceFit::Parameters(), ProjectToPlane(), MeshCore::PlaneFitSmoothing::Smooth(), and MeshCore::PlaneFitSmoothing::SmoothPoints().
GetSignedStdDeviation()
float PlaneFit::GetSignedStdDeviation () const
Returns the standard deviation from the points to the fitted plane with respect to the orientation of the plane's normal. If Fit() has not been called FLOAT_MAX is returned.
Definition at line 353 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, MeshCore::Approximation::_vPoints, MeshCore::Approximation::CountPoints(), FLOAT_MAX, GetDistanceToPlane(), GetNormal(), FreeCADInit::Length, and KDL::sqrt().
GetStdDeviation()
float PlaneFit::GetStdDeviation () const
Returns the standard deviation from the points to the fitted plane. If Fit() has not been called FLOAT_MAX is returned.
Definition at line 328 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, MeshCore::Approximation::_vPoints, MeshCore::Approximation::CountPoints(), FLOAT_MAX, GetDistanceToPlane(), and KDL::sqrt().
ProjectToPlane()
void PlaneFit::ProjectToPlane ()
Projects the points onto the fitted plane.
Definition at line 397 of file Approximation.cpp.
References MeshCore::Approximation::_vPoints, MeshCore::Approximation::GetGravity(), and GetNormal().
Member Data Documentation
_vBase
Base::Vector3f MeshCore::PlaneFit::_vBase protected
Base vector of the plane.
Definition at line 268 of file Approximation.h.
Referenced by Dimension(), Fit(), GetBase(), GetDistanceToPlane(), GetLocalPoints(), and MeshCore::SurfaceFit::Transform().
_vDirU
Base::Vector3f MeshCore::PlaneFit::_vDirU protected
Definition at line 269 of file Approximation.h.
Referenced by Dimension(), Fit(), GetDirU(), GetLocalPoints(), and MeshCore::SurfaceFit::Transform().
_vDirV
Base::Vector3f MeshCore::PlaneFit::_vDirV protected
Definition at line 270 of file Approximation.h.
Referenced by Dimension(), Fit(), GetDirV(), GetLocalPoints(), and MeshCore::SurfaceFit::Transform().
_vDirW
Base::Vector3f MeshCore::PlaneFit::_vDirW protected
Normal of the plane.
Definition at line 271 of file Approximation.h.
Referenced by Fit(), GetDistanceToPlane(), GetNormal(), and MeshCore::SurfaceFit::Transform().
The documentation for this class was generated from the following files:
Approximation.h
Approximation.cpp