FreeCAD: MeshCore::MeshRemoveNeedles Class Reference
MeshCore::MeshRemoveNeedles Class Reference
#include <Degeneration.h>
Public Member Functions
MeshRemoveNeedles (MeshKernel &rclM, float fMinEdgeLen=0.05F)
bool Fixup () override
Public Member Functions inherited from MeshCore::MeshValidation
MeshValidation (MeshKernel &rclB)
virtual ~MeshValidation ()=default
MeshValidation (const MeshValidation &)=delete
MeshValidation (MeshValidation &&)=delete
MeshValidation & operator= (const MeshValidation &)=delete
MeshValidation & operator= (MeshValidation &&)=delete
Additional Inherited Members
Protected Attributes inherited from MeshCore::MeshValidation
MeshKernel & _rclMesh
Detailed Description
The MeshRemoveNeedles class tries to fix degenerations by removing needles. Needles are triangles where its longest edge is much longer than its shortest edge. https://graphics.uni-bielefeld.de/publications/vmv01.pdf
See also
MeshFixDegeneratedFacets
MeshFixCaps
Author
Werner Mayer
Definition at line 343 of file Degeneration.h.
Constructor & Destructor Documentation
MeshRemoveNeedles()
MeshCore::MeshRemoveNeedles::MeshRemoveNeedles (MeshKernel & rclM, float fMinEdgeLen = 0.05F) inline explicit
Construction. The
fMinEdgeLen must be in the range of 0.0 and 0.25. It defines the amount of perimeter of a triangle for which the shortest edge is considered for removal.
Definition at line 351 of file Degeneration.h.
Member Function Documentation
Fixup()
bool MeshRemoveNeedles::Fixup () override virtual
Removes all facets with an edge smaller than fMinEdgeLength without leaving holes or gaps in the mesh.
Implements MeshCore::MeshValidation.
Definition at line 536 of file Degeneration.cpp.
References MeshCore::EdgeCollapse::_adjacentFrom, MeshCore::EdgeCollapse::_adjacentTo, MeshCore::MeshFacet::_aulPoints, MeshCore::EdgeCollapse::_changeFacets, MeshCore::EdgeCollapse::_fromPoint, MeshCore::MeshValidation::_rclMesh, MeshCore::EdgeCollapse::_removeFacets, MeshCore::EdgeCollapse::_toPoint, MeshCore::MeshRefPointToFacets::AddNeighbour(), MeshCore::MeshTopoAlgorithm::Cleanup(), MeshCore::MeshTopoAlgorithm::CollapseEdge(), Base::Distance(), MeshCore::FACET_INDEX_MAX, MeshCore::MeshKernel::GetFacet(), MeshCore::MeshKernel::GetFacets(), MeshCore::MeshKernel::GetPoints(), SplineSurface::i, MeshCore::MeshTopoAlgorithm::IsCollapseEdgeLegal(), MeshCore::MeshRefPointToFacets::NeighbourPoints(), MeshCore::MeshGeomFacet::Perimeter(), MeshCore::MeshKernel::RebuildNeighbours(), MeshCore::MeshRefPointToFacets::RemoveFacet(), MeshCore::MeshRefPointToFacets::RemoveNeighbour(), MeshCore::MeshPointArray::ResetFlag(), MeshCore::MeshPointArray::ResetInvalid(), MeshCore::MeshFacetArray::ResetInvalid(), draftutils.todo::todo, and MeshCore::MeshPoint::VISIT.
Referenced by Mesh::MeshObject::removeNeedles().
The documentation for this class was generated from the following files:
Degeneration.h
Degeneration.cpp