FreeCAD: Part::TopoShape Struct Reference
Part::TopoShape Struct Reference
Parameters for TopoShape::makeElementFilledFace()
#include <TopoShape.h>
Classes
struct Mapper
Public Member Functions
TopoShape (long Tag=0, App::StringHasherRef hasher=App::StringHasherRef(), const TopoDS_Shape &shape=TopoDS_Shape())
TopoShape (const TopoDS_Shape &, long Tag=0, App::StringHasherRef hasher=App::StringHasherRef())
TopoShape (const TopoShape &)
~TopoShape () override
void setShape (const TopoDS_Shape &shape, bool resetElementMap=true)
void setShape (const TopoShape &shape)
const TopoDS_Shape & getShape () const
void operator= (const TopoShape &)
bool operator== (const TopoShape &other) const
virtual bool isSame (const Data::ComplexGeoData &other) const
Save/restore
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void SaveDocFile (Base::Writer &writer) const override
void RestoreDocFile (Base::Reader &reader) override
unsigned int getMemSize () const override
Input/Output
void read (const char *FileName)
void write (const char *FileName) const
void dump (std::ostream &out) const
void importIges (const char *FileName)
void importStep (const char *FileName)
void importBrep (const char *FileName)
void importBrep (std::istream &, int indicator=1)
void importBinary (std::istream &)
void exportIges (const char *FileName) const
void exportStep (const char *FileName) const
void exportBrep (const char *FileName) const
void exportBrep (std::ostream &) const
void exportBinary (std::ostream &) const
void exportStl (const char *FileName, double deflection) const
void exportFaceSet (double, double, const std::vector< App::Color > &, std::ostream &) const
void exportLineSet (std::ostream &) const
Query
bool isNull () const
bool isValid () const
bool analyze (bool runBopCheck, std::ostream &) const
bool isClosed () const
bool isCoplanar (const TopoShape &other, double tol=-1) const
bool findPlane (gp_Pln &plane, double tol=-1, double atol=-1) const
bool isInfinite () const
Returns true if the expansion of the shape is infinite, false otherwise.
bool isPlanar (double tol=1.0e-7) const
Checks whether the shape is a planar face.
bool isLinearEdge (Base::Vector3d *dir=nullptr, Base::Vector3d *base=nullptr) const
Check if this shape is a single linear edge, works on BSplineCurve and BezierCurve.
bool isPlanarFace (double tol=1e-7) const
Check if this shape is a single planar face, works on BSplineSurface and BezierSurface.
Boolean operation
TopoDS_Shape cut (TopoDS_Shape) const
TopoDS_Shape cut (const std::vector< TopoDS_Shape > &, Standard_Real tolerance=-1.0) const
TopoDS_Shape common (TopoDS_Shape) const
TopoDS_Shape common (const std::vector< TopoDS_Shape > &, Standard_Real tolerance=-1.0) const
TopoDS_Shape fuse (TopoDS_Shape) const
TopoDS_Shape fuse (const std::vector< TopoDS_Shape > &, Standard_Real tolerance=-1.0) const
TopoDS_Shape oldFuse (TopoDS_Shape) const
TopoDS_Shape section (TopoDS_Shape, Standard_Boolean approximate=Standard_False) const
TopoDS_Shape section (const std::vector< TopoDS_Shape > &, Standard_Real tolerance=-1.0, Standard_Boolean approximate=Standard_False) const
std::list< TopoDS_Wire > slice (const Base::Vector3d &, double) const
TopoDS_Compound slices (const Base::Vector3d &, const std::vector< double > &) const
TopoDS_Shape generalFuse (const std::vector< TopoDS_Shape > &sOthers, Standard_Real tolerance, std::vector< TopTools_ListOfShape > *mapInOut=nullptr) const
generalFuse: run general fuse algorithm between this and shapes supplied as sOthers
TopoDS_Shape makePipe (const TopoDS_Shape &profile) const
TopoDS_Shape makePipeShell (const TopTools_ListOfShape &profiles, const Standard_Boolean make_solid, const Standard_Boolean isFrenet=Standard_False, int transition=0) const
TopoDS_Shape makePrism (const gp_Vec &) const
TopoDS_Shape revolve (const gp_Ax1 &, double d, Standard_Boolean isSolid=Standard_False) const
TopoDS_Shape makeSweep (const TopoDS_Shape &profile, double, int) const
TopoDS_Shape makeTube (double radius, double tol, int cont, int maxdeg, int maxsegm) const
TopoDS_Shape makeTorus (Standard_Real radius1, Standard_Real radius2, Standard_Real angle1, Standard_Real angle2, Standard_Real angle3, Standard_Boolean isSolid=Standard_True) const
TopoDS_Shape makeHelix (Standard_Real pitch, Standard_Real height, Standard_Real radius, Standard_Real angle=0, Standard_Boolean left=Standard_False, Standard_Boolean style=Standard_False) const
TopoDS_Shape makeLongHelix (Standard_Real pitch, Standard_Real height, Standard_Real radius, Standard_Real angle=0, Standard_Boolean left=Standard_False) const
TopoDS_Shape makeSpiralHelix (Standard_Real radiusbottom, Standard_Real radiustop, Standard_Real height, Standard_Real nbturns=1, Standard_Real breakperiod=1, Standard_Boolean left=Standard_False) const
TopoDS_Shape makeThread (Standard_Real pitch, Standard_Real depth, Standard_Real height, Standard_Real radius) const
TopoDS_Shape makeLoft (const TopTools_ListOfShape &profiles, Standard_Boolean isSolid, Standard_Boolean isRuled, Standard_Boolean isClosed=Standard_False, Standard_Integer maxDegree=5) const
TopoDS_Shape makeOffsetShape (double offset, double tol, bool intersection=false, bool selfInter=false, short offsetMode=0, short join=0, bool fill=false) const
TopoDS_Shape makeOffset2D (double offset, short joinType=0, bool fill=false, bool allowOpenResult=false, bool intersection=false) const
TopoDS_Shape makeThickSolid (const TopTools_ListOfShape &remFace, double offset, double tol, bool intersection=false, bool selfInter=false, short offsetMode=0, short join=0) const
Public Member Functions inherited from Data::ComplexGeoData
ComplexGeoData ()
Constructor.
~ComplexGeoData () override=default
Destructor.
void applyTransform (const Base::Matrix4D &rclTrf)
void applyTranslation (const Base::Vector3d &)
void applyRotation (const Base::Rotation &)
void setPlacement (const Base::Placement &rclPlacement)
Base::Placement getPlacement () const
virtual Segment * getSubElementByName (const char *Name) const
get sub-element by combined name
virtual Base::Vector3d getPointFromLineIntersection (const Base::Vector3f &base, const Base::Vector3f &dir) const
virtual std::optional< Base::Vector3d > centerOfGravity () const
IndexedName getIndexedName (const MappedName &name, ElementIDRefs *sid=nullptr) const
MappedName getMappedName (const IndexedName &element, bool allowUnmapped=false, ElementIDRefs *sid=nullptr) const
MappedElement getElementName (const char *name, ElementIDRefs *sid=nullptr, bool copy=false) const
MappedName setElementName (const IndexedName &element, const MappedName &name, long masterTag, const ElementIDRefs *sid=nullptr, bool overwrite=false)
bool hasElementMap ()
std::vector< std::pair< MappedName, ElementIDRefs > > getElementMappedNames (const IndexedName &element, bool needUnmapped=false) const
void hashChildMaps ()
Hash the child element map postfixes to shorten element name from hierarchical maps.
bool hasChildElementMap () const
Check if there is child element map.
long getElementHistory (const MappedName &name, MappedName *original=nullptr, std::vector< MappedName > *history=nullptr) const
void setMappedChildElements (const std::vector< Data::ElementMap::MappedChildElements > &children)
std::vector< Data::ElementMap::MappedChildElements > getMappedChildElements () const
char elementType (const Data::MappedName &) const
char elementType (const Data::IndexedName &) const
char elementType (const char *name) const
std::vector< MappedElement > getElementMap () const
Get the entire element map.
void setElementMap (const std::vector< MappedElement > &elements)
Set the entire element map.
size_t getElementMapSize (bool flush=true) const
Get the current element map size.
virtual std::string getElementMapVersion () const
Return the current element map version.
virtual bool checkElementMapVersion (const char *ver) const
Return true to signal element map version change.
void traceElement (const MappedName &name, TraceCallback cb) const
void setPersistenceFileName (const char *name) const
virtual void beforeSave () const
bool isRestoreFailed () const
void resetRestoreFailure () const
void dumpElementMap (std::ostream &stream) const
const std::string dumpElementMap () const
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from Base::Handled
Handled ()
virtual ~Handled ()
void ref () const
void unref () const
int unrefNoDelete () const
int getRefCount () const
Handled & operator= (const Handled &)
Handled (const Handled &)=delete
Handled (Handled &&)=delete
Handled & operator= (Handled &&)=delete
Public Attributes
TopoShape surface
std::unordered_map< TopoDS_Shape, TopoShape::Continuity, ShapeHasher, ShapeHasher > orders
std::unordered_map< TopoDS_Shape, TopoDS_Shape, ShapeHasher, ShapeHasher > supports
Optional map from input shape to face used as support.
int boundary_begin = -1
Optional begin index to the input shapes to be used as the boundary of the filled face.
int boundary_end = -1
unsigned int degree = 3
The energe minimizing criterion degree;.
unsigned int ptsoncurve = 15
The number of points on the curve NbPntsOnCur.
unsigned int numiter = 2
The number of iterations NbIter.
bool anisotropy = false
The Boolean Anisotropie.
double tol2d = 1e-5
The 2D tolerance Tol2d.
double tol3d = 1e-4
The 3D tolerance Tol3d.
double tolG1 = 0.01
The angular tolerance TolAng.
double tolG2 = 0.1
The tolerance for curvature TolCur.
unsigned int maxdeg = 8
The highest polynomial degree MaxDeg.
unsigned int maxseg = 9
Public Attributes inherited from Data::ComplexGeoData
long Tag {0}
App::StringHasherRef Hasher
String hasher for element name shortening.
Placement control
void setTransform (const Base::Matrix4D &rclTrf) override
set the transformation of the CasCade Shape
Base::Matrix4D getTransform () const override
get the transformation of the CasCade Shape
Base::BoundBox3d getBoundBox () const override
Bound box from the CasCade shape.
bool getCenterOfGravity (Base::Vector3d &center) const override
static void convertTogpTrsf (const Base::Matrix4D &mtrx, gp_Trsf &trsf)
static void convertToMatrix (const gp_Trsf &trsf, Base::Matrix4D &mtrx)
static Base::Matrix4D convert (const gp_Trsf &trsf)
static gp_Trsf convert (const Base::Matrix4D &mtrx)
Getting basic geometric entities
double getAccuracy () const override
Get the standard accuracy to be used with getPoints, getLines or getFaces.
void getPoints (std::vector< Base::Vector3d > &Points, std::vector< Base::Vector3d > &Normals, double Accuracy, uint16_t flags=0) const override
void getLines (std::vector< Base::Vector3d > &Points, std::vector< Line > &lines, double Accuracy, uint16_t flags=0) const override
void getFaces (std::vector< Base::Vector3d > &Points, std::vector< Facet > &faces, double Accuracy, uint16_t flags=0) const override
void setFaces (const std::vector< Base::Vector3d > &Points, const std::vector< Facet > &faces, double tolerance=1.0e-06)
void getDomains (std::vector< Domain > &) const
Subelement management
std::vector< const char * > getElementTypes () const override
unsigned long countSubElements (const char *Type) const override
Data::Segment * getSubElement (const char *Type, unsigned long index) const override
get the subelement by type and number
void getLinesFromSubElement (const Data::Segment *segment, std::vector< Base::Vector3d > &Points, std::vector< Line > &lines) const override
void getFacesFromSubElement (const Data::Segment *segment, std::vector< Base::Vector3d > &Points, std::vector< Base::Vector3d > &PointNormals, std::vector< Facet > &faces) const override
TopoDS_Shape getSubShape (const char *Type, bool silent=false) const
TopoDS_Shape getSubShape (TopAbs_ShapeEnum type, int idx, bool silent=false) const
TopoShape getSubTopoShape (const char *Type, bool silent=false) const
TopoShape getSubTopoShape (TopAbs_ShapeEnum type, int idx, bool silent=false) const
std::vector< TopoShape > getSubTopoShapes (TopAbs_ShapeEnum type=TopAbs_SHAPE, TopAbs_ShapeEnum avoid=TopAbs_SHAPE) const
std::vector< TopoDS_Shape > getSubShapes (TopAbs_ShapeEnum type=TopAbs_SHAPE, TopAbs_ShapeEnum avoid=TopAbs_SHAPE) const
std::vector< TopoShape > getOrderedEdges (MapElement mapElement=MapElement::map) const
std::vector< TopoShape > getOrderedVertexes (MapElement mapElement=MapElement::map) const
unsigned long countSubShapes (const char *Type) const
unsigned long countSubShapes (TopAbs_ShapeEnum type) const
bool hasSubShape (const char *Type) const
bool hasSubShape (TopAbs_ShapeEnum type) const
PyObject * getPySubShape (const char *Type, bool silent=false) const
get the Topo"sub"Shape with the given name
PyObject * getPyObject () override
void setPyObject (PyObject *obj) override
static Data::MappedElement chooseMatchingSubShapeByPlaneOrLine (const TopoShape &shapeToFind, const TopoShape &shapeToLookIn)
Search to see if a SubShape matches.
static std::pair< std::string, unsigned long > getElementTypeAndIndex (const char *Name)
Manipulation
enum SplitWireReorient { NoReorient, Reorient, ReorientForward, ReorientReversed }
Wire re-orientation when calling splitWires()
void transformGeometry (const Base::Matrix4D &rclMat) override
Applies a transformation on the real geometric data type.
TopoDS_Shape transformGShape (const Base::Matrix4D &, bool copy=false) const
bool transformShape (const Base::Matrix4D &, bool copy, bool checkScale=false)
TopoDS_Shape mirror (const gp_Ax2 &) const
TopoDS_Shape toNurbs () const
TopoDS_Shape replaceShape (const std::vector< std::pair< TopoDS_Shape, TopoDS_Shape >> &s) const
TopoDS_Shape removeShape (const std::vector< TopoDS_Shape > &s) const
void sewShape (double tolerance=1.0e-06)
bool fix ()
bool fix (double, double, double)
bool fixSolidOrientation ()
bool removeInternalWires (double)
TopoDS_Shape removeSplitter () const
TopoDS_Shape defeaturing (const std::vector< TopoDS_Shape > &s) const
TopoDS_Shape makeShell (const TopoDS_Shape &) const
TopoShape::makeShell If the input shape is a compound with faces not being part of a shell it tries to make a shell. If this operation fails or if the input shape is not a compound or a compound with not only faces the input shape is returned.
TopoShape splitWires (std::vector< TopoShape > *inner=nullptr, SplitWireReorient reorient=Reorient) const
Element name mapping aware shape maker
To be complete in next batch of patches
enum PrismMode { CutFromBase = 0, FuseWithBase = 1, None = 2 }
Operation mode for makeElementPrismUntil()
TopoShape & makeCompound (const std::vector< TopoShape > &shapes, const char *op=nullptr, bool force=true)
TopoShape & makeWires (const TopoShape &shape, const char *op=nullptr, bool fix=false, double tol=0.0)
TopoShape makeWires (const char *op=nullptr, bool fix=false, double tol=0.0) const
TopoShape & makeFace (const std::vector< TopoShape > &shapes, const char *op=nullptr, const char *maker=nullptr)
TopoShape & makeFace (const TopoShape &shape, const char *op=nullptr, const char *maker=nullptr)
TopoShape makeFace (const char *op=nullptr, const char *maker=nullptr) const
bool _makeTransform (const TopoShape &shape, const Base::Matrix4D &mat, const char *op=nullptr, bool checkScale=false, bool copy=false)
TopoShape & makeTransform (const TopoShape &shape, const Base::Matrix4D &mat, const char *op=nullptr, bool checkScale=false, bool copy=false)
TopoShape makeTransform (const Base::Matrix4D &mat, const char *op=nullptr, bool checkScale=false, bool copy=false) const
TopoShape & makeTransform (const TopoShape &shape, const gp_Trsf &trsf, const char *op=nullptr, bool copy=false)
TopoShape makeTransform (const gp_Trsf &trsf, const char *op=nullptr, bool copy=false) const
void move (const TopLoc_Location &loc)
TopoShape moved (const TopLoc_Location &loc) const
void move (const gp_Trsf &trsf)
TopoShape moved (const gp_Trsf &trsf) const
void locate (const TopLoc_Location &loc)
TopoShape located (const TopLoc_Location &loc) const
void locate (const gp_Trsf &trsf)
TopoShape located (const gp_Trsf &trsf) const
TopoShape & makeGTransform (const TopoShape &shape, const Base::Matrix4D &mat, const char *op=nullptr, bool copy=false)
TopoShape makeGTransform (const Base::Matrix4D &mat, const char *op=nullptr, bool copy=false) const
TopoShape & makeElementRefine (const TopoShape &shape, const char *op=nullptr, RefineFail no_fail=RefineFail::throwException)
TopoShape makeElementRefine (const char *op=nullptr, RefineFail no_fail=RefineFail::throwException) const
TopoShape & makeRefine (const TopoShape &shape, const char *op=nullptr, RefineFail no_fail=RefineFail::throwException)
TopoShape makeRefine (const char *op=nullptr, RefineFail no_fail=RefineFail::throwException) const
TopoShape & makeElementThickSolid (const TopoShape &shape, const std::vector< TopoShape > &faces, double offset, double tol, bool intersection=false, bool selfInter=false, short offsetMode=0, JoinType join=JoinType::arc, const char *op=nullptr)
TopoShape makeElementThickSolid (const std::vector< TopoShape > &faces, double offset, double tol, bool intersection=false, bool selfInter=false, short offsetMode=0, JoinType join=JoinType::arc, const char *op=nullptr) const
TopoShape & makeElementOffset (const TopoShape &source, double offset, double tol, bool intersection=false, bool selfInter=false, short offsetMode=0, JoinType join=JoinType::arc, FillType fill=FillType::noFill, const char *op=nullptr)
TopoShape makeElementOffset (double offset, double tol, bool intersection=false, bool selfInter=false, short offsetMode=0, JoinType join=JoinType::arc, FillType fill=FillType::noFill, const char *op=nullptr) const
TopoShape & makeElementOffset2D (const TopoShape &source, double offset, JoinType join=JoinType::arc, FillType fill=FillType::noFill, OpenResult allowOpenResult=OpenResult::allowOpenResult, bool intersection=false, const char *op=nullptr)
TopoShape makeElementOffset2D (double offset, JoinType join=JoinType::arc, FillType fill=FillType::noFill, OpenResult allowOpenResult=OpenResult::allowOpenResult, bool intersection=false, const char *op=nullptr) const
TopoShape & makeElementOffsetFace (const TopoShape &source, double offset, double innerOffset, JoinType join=JoinType::arc, JoinType innerJoin=JoinType::arc, const char *op=nullptr)
TopoShape makeElementOffsetFace (double offset, double innerOffset, JoinType join=JoinType::arc, JoinType innerJoin=JoinType::arc, const char *op=nullptr) const
TopoShape & makeElementRevolve (const TopoShape &base, const gp_Ax1 &axis, double d, const char *face_maker=0, const char *op=nullptr)
TopoShape makeElementRevolve (const gp_Ax1 &axis, double d, const char *face_maker=nullptr, const char *op=nullptr) const
TopoShape & makeElementRevolution (const TopoShape &_base, const TopoDS_Shape &profile, const gp_Ax1 &axis, const TopoDS_Face &supportface, const TopoDS_Face &uptoface, const char *face_maker=nullptr, RevolMode Mode=RevolMode::None, Standard_Boolean Modify=Standard_True, const char *op=nullptr)
TopoShape & makeElementRevolution (const gp_Ax1 &axis, const TopoDS_Shape &profile, const TopoDS_Face &supportface, const TopoDS_Face &uptoface, const char *face_maker=nullptr, RevolMode Mode=RevolMode::None, Standard_Boolean Modify=Standard_True, const char *op=nullptr) const
TopoShape & makeElementPrism (const TopoShape &base, const gp_Vec &vec, const char *op=nullptr)
TopoShape makeElementPrism (const gp_Vec &vec, const char *op=nullptr) const
TopoShape & makeElementPrismUntil (const TopoShape &base, const TopoShape &profile, const TopoShape &supportFace, const TopoShape &upToFace, const gp_Dir &direction, PrismMode mode, Standard_Boolean checkLimits=Standard_True, const char *op=nullptr)
TopoShape makeElementPrismUntil (const TopoShape &profile, const TopoShape &supportFace, const TopoShape &upToFace, const gp_Dir &direction, PrismMode mode, Standard_Boolean checkLimits=Standard_True, const char *op=nullptr) const
TopoShape & makeElementPipeShell (const std::vector< TopoShape > &sources, const MakeSolid makeSolid, const Standard_Boolean isFrenet, TransitionMode transition=TransitionMode::Transformed, const char *op=nullptr, double tol3d=0.0, double tolBound=0.0, double tolAngular=0.0)
TopoShape & replaceElementShape (const TopoShape &source, const std::vector< std::pair< TopoShape, TopoShape >> &s)
TopoShape replaceElementShape (const std::vector< std::pair< TopoShape, TopoShape >> &s) const
TopoShape & removeElementShape (const TopoShape &source, const std::vector< TopoShape > &s)
TopoShape removeElementShape (const std::vector< TopoShape > &s) const
TopoShape & makeElementGeneralFuse (const std::vector< TopoShape > &sources, std::vector< std::vector< TopoShape >> &modified, double tol=-1.0, const char *op=nullptr)
TopoShape & makeElementFuse (const std::vector< TopoShape > &sources, const char *op=nullptr, double tol=-1.0)
TopoShape makeElementFuse (const TopoShape &source, const char *op=nullptr, double tol=-1.0) const
TopoShape & makeElementCut (const std::vector< TopoShape > &sources, const char *op=nullptr, double tol=-1.0)
TopoShape makeElementCut (const TopoShape &source, const char *op=nullptr, double tol=-1.0) const
bool linearize (LinearizeFace face, LinearizeEdge edge)
TopAbs_ShapeEnum shapeType (bool silent=false) const
const std::string & shapeName (bool silent=false) const
Data::MappedName setElementComboName (const Data::IndexedName &element, const std::vector< Data::MappedName > &names, const char *marker=nullptr, const char *op=nullptr, const Data::ElementIDRefs *sids=nullptr)
std::vector< Data::MappedName > decodeElementComboName (const Data::IndexedName &element, const Data::MappedName &name, const char *marker=nullptr, std::string *postfix=nullptr) const
void reTagElementMap (long tag, App::StringHasherRef hasher, const char *postfix=nullptr) override
Append the Tag (if and only if it is non zero) into the element map.
long isElementGenerated (const Data::MappedName &name, int depth=1) const
static TopoDS_Shape & move (TopoDS_Shape &tds, const TopLoc_Location &loc)
static TopoDS_Shape moved (const TopoDS_Shape &tds, const TopLoc_Location &loc)
static TopoDS_Shape & move (TopoDS_Shape &tds, const gp_Trsf &transfer)
static TopoDS_Shape moved (const TopoDS_Shape &tds, const gp_Trsf &transfer)
static TopoDS_Shape & locate (TopoDS_Shape &tds, const TopLoc_Location &loc)
static TopoDS_Shape located (const TopoDS_Shape &tds, const TopLoc_Location &loc)
static TopoDS_Shape & locate (TopoDS_Shape &tds, const gp_Trsf &transfer)
static TopoDS_Shape located (const TopoDS_Shape &tds, const gp_Trsf &transfer)
static TopAbs_ShapeEnum shapeType (const char *type, bool silent=false)
static TopAbs_ShapeEnum shapeType (char type, bool silent=false)
static const std::string & shapeName (TopAbs_ShapeEnum type, bool silent=false)
static std::pair< TopAbs_ShapeEnum, int > shapeTypeAndIndex (const char *name)
static std::pair< TopAbs_ShapeEnum, int > shapeTypeAndIndex (const Data::IndexedName &name)
sub shape cached functions
Mapped element names introduces some overhead when getting sub shapes from a shape. These functions use internal caches for sub-shape maps to improve performance.
enum SingleShapeCompoundCreationPolicy { SingleShapeCompoundCreationPolicy::returnShape, SingleShapeCompoundCreationPolicy::forceCompound }
enum ConnectionPolicy { ConnectionPolicy::requireSharedVertex, ConnectionPolicy::mergeWithTolerance }
enum Continuity {
Continuity::C0, Continuity::G1, Continuity::C1, Continuity::G2,
Continuity::C2, Continuity::C3, Continuity::CN
}
class TopoShapeCache
void initCache (int reset=0) const
int findShape (const TopoDS_Shape &subshape) const
TopoDS_Shape findShape (const char *name) const
TopoDS_Shape findShape (TopAbs_ShapeEnum type, int idx) const
int findAncestor (const TopoDS_Shape &subshape, TopAbs_ShapeEnum type) const
TopoDS_Shape findAncestorShape (const TopoDS_Shape &subshape, TopAbs_ShapeEnum type) const
std::vector< int > findAncestors (const TopoDS_Shape &subshape, TopAbs_ShapeEnum type) const
std::vector< TopoDS_Shape > findAncestorsShapes (const TopoDS_Shape &subshape, TopAbs_ShapeEnum type) const
std::vector< TopoShape > findSubShapesWithSharedVertex (const TopoShape &subshape, std::vector< std::string > *names=nullptr, Data::SearchOptions=Data::SearchOption::CheckGeometry, double tol=1e-7, double atol=1e-12) const
void copyElementMap (const TopoShape &topoShape, const char *op=nullptr)
bool canMapElement (const TopoShape &other) const
void cacheRelatedElements (const Data::MappedName &name, HistoryTraceType sameType, const QVector< Data::MappedElement > &names) const
bool getRelatedElementsCached (const Data::MappedName &name, HistoryTraceType sameType, QVector< Data::MappedElement > &names) const
void mapSubElement (const TopoShape &other, const char *op=nullptr, bool forceHasher=false)
void mapSubElement (const std::vector< TopoShape > &shapes, const char *op=nullptr)
void mapSubElementsTo (std::vector< TopoShape > &shapes, const char *op=nullptr) const
bool hasPendingElementMap () const
void flushElementMap () const override
Data::ElementMapPtr resetElementMap (Data::ElementMapPtr elementMap=Data::ElementMapPtr()) override
std::vector< Data::IndexedName > getHigherElements (const char *element, bool silent=false) const override
Return the higher level element names of the given element.
TopoShape & makeElementEvolve (const TopoShape &spine, const TopoShape &profile, JoinType join=JoinType::arc, CoordinateSystem=CoordinateSystem::global, MakeSolid solid=MakeSolid::noSolid, Spine profOnSpine=Spine::notOn, double tol=0.0, const char *op=nullptr)
TopoShape makeElementEvolve (const TopoShape &profile, JoinType join=JoinType::arc, CoordinateSystem axeProf=CoordinateSystem::global, MakeSolid solid=MakeSolid::noSolid, Spine profOnSpine=Spine::notOn, double tol=0.0, const char *op=nullptr)
TopoShape & makeElementLoft (const std::vector< TopoShape > &sources, IsSolid isSolid, IsRuled isRuled, IsClosed isClosed=IsClosed::notClosed, Standard_Integer maxDegree=5, const char *op=nullptr)
TopoShape & makeElementRuledSurface (const std::vector< TopoShape > &source, int orientation=0, const char *op=nullptr)
TopoShape & makeShapeWithElementMap (const TopoDS_Shape &shape, const Mapper &mapper, const std::vector< TopoShape > &sources, const char *op=nullptr)
TopoShape & makeElementCompound (const std::vector< TopoShape > &shapes, const char *op=nullptr, SingleShapeCompoundCreationPolicy policy=SingleShapeCompoundCreationPolicy::forceCompound)
TopoShape & makeElementWires (const std::vector< TopoShape > &shapes, const char *op=nullptr, double tol=0.0, ConnectionPolicy policy=ConnectionPolicy::mergeWithTolerance, TopoShapeMap *output=nullptr)
TopoShape & makeElementWires (const TopoShape &shape, const char *op=nullptr, double tol=0.0, ConnectionPolicy policy=ConnectionPolicy::mergeWithTolerance, TopoShapeMap *output=nullptr)
TopoShape & makeElementOrderedWires (const std::vector< TopoShape > &shapes, const char *op=nullptr, double tol=0.0, TopoShapeMap *output=nullptr)
TopoShape makeElementWires (const char *op=nullptr, double tol=0.0, ConnectionPolicy policy=ConnectionPolicy::mergeWithTolerance, TopoShapeMap *output=nullptr) const
TopoShape & makeElementGTransform (const TopoShape &source, const Base::Matrix4D &mat, const char *op=nullptr, CopyType copy=CopyType::noCopy)
TopoShape makeElementGTransform (const Base::Matrix4D &mat, const char *op=nullptr, CopyType copy=CopyType::noCopy) const
TopoShape & makeElementCopy (const TopoShape &source, const char *op=nullptr, bool copyGeom=true, bool copyMesh=false)
TopoShape makeElementCopy (const char *op=nullptr, bool copyGeom=true, bool copyMesh=false) const
TopoShape & makeElementBoolean (const char *maker, const std::vector< TopoShape > &sources, const char *op=nullptr, double tol=-1.0)
TopoShape & makeElementBoolean (const char *maker, const TopoShape &source, const char *op=nullptr, double tol=-1.0)
TopoShape makeElementBoolean (const char *maker, const char *op=nullptr, double tol=-1.0) const
TopoShape & makeElementMirror (const TopoShape &source, const gp_Ax2 &axis, const char *op=nullptr)
TopoShape makeElementMirror (const gp_Ax2 &ax, const char *op=nullptr) const
TopoShape & makeElementSlice (const TopoShape &source, const Base::Vector3d &dir, double distance, const char *op=nullptr)
TopoShape makeElementSlice (const Base::Vector3d &dir, double distance, const char *op=nullptr) const
TopoShape & makeElementSlices (const TopoShape &source, const Base::Vector3d &dir, const std::vector< double > &distances, const char *op=nullptr)
TopoShape makeElementSlices (const Base::Vector3d &dir, const std::vector< double > &distances, const char *op=nullptr) const
TopoShape & makeElementFillet (const TopoShape &source, const std::vector< TopoShape > &edges, double radius1, double radius2, const char *op=nullptr)
TopoShape makeElementFillet (const std::vector< TopoShape > &edges, double radius1, double radius2, const char *op=nullptr) const
TopoShape & makeElementChamfer (const TopoShape &source, const std::vector< TopoShape > &edges, ChamferType chamferType, double radius1, double radius2, const char *op=nullptr, Flip flipDirection=Flip::none)
TopoShape makeElementChamfer (const std::vector< TopoShape > &edges, ChamferType chamferType, double radius1, double radius2, const char *op=nullptr, Flip flipDirection=Flip::none) const
bool _makeElementTransform (const TopoShape &source, const Base::Matrix4D &mat, const char *op=nullptr, CheckScale checkScale=CheckScale::noScaleCheck, CopyType copy=CopyType::noCopy)
TopoShape & makeElementTransform (const TopoShape &source, const Base::Matrix4D &mat, const char *op=nullptr, CheckScale checkScale=CheckScale::noScaleCheck, CopyType copy=CopyType::noCopy)
TopoShape makeElementTransform (const Base::Matrix4D &mat, const char *op=nullptr, CheckScale checkScale=CheckScale::noScaleCheck, CopyType copy=CopyType::noCopy)
TopoShape & makeElementTransform (const TopoShape &shape, const gp_Trsf &trsf, const char *op=nullptr, CopyType copy=CopyType::noCopy)
TopoShape makeElementTransform (const gp_Trsf &trsf, const char *op=nullptr, CopyType copy=CopyType::noCopy)
TopoShape & makeElementDraft (const TopoShape &source, const std::vector< TopoShape > &faces, const gp_Dir &pullDirection, double angle, const gp_Pln &neutralPlane, bool retry=true, const char *op=nullptr)
TopoShape makeElementDraft (const std::vector< TopoShape > &faces, const gp_Dir &pullDirection, double angle, const gp_Pln &neutralPlane, bool retry=true, const char *op=nullptr) const
TopoShape & makeElementShell (bool silent=true, const char *op=nullptr)
TopoShape & makeElementShellFromWires (const std::vector< TopoShape > &wires, bool silent=true, const char *op=nullptr)
TopoShape & makeElementShellFromWires (bool silent=true, const char *op=nullptr)
TopoShape & makeElementFace (const std::vector< TopoShape > &shapes, const char *op=nullptr, const char *maker=nullptr, const gp_Pln *plane=nullptr)
TopoShape & makeElementFace (const TopoShape &shape, const char *op=nullptr, const char *maker=nullptr, const gp_Pln *plane=nullptr)
TopoShape makeElementFace (const char *op=nullptr, const char *maker=nullptr, const gp_Pln *plane=nullptr) const
TopoShape & makeElementBSplineFace (const std::vector< TopoShape > &input, FillingStyle style=FillingStyle::stretch, bool keepBezier=false, const char *op=nullptr)
TopoShape & makeElementBSplineFace (const TopoShape &input, FillingStyle style=FillingStyle::stretch, bool keepBezier=false, const char *op=nullptr)
TopoShape makeElementBSplineFace (FillingStyle style=FillingStyle::stretch, bool keepBezier=false, const char *op=nullptr)
TopoShape & makeElementFilledFace (const std::vector< TopoShape > &shapes, const BRepFillingParams &params, const char *op=nullptr)
TopoShape & makeElementSolid (const TopoShape &shape, const char *op=nullptr)
TopoShape makeElementSolid (const char *op=nullptr) const
TopoShape & makeElementShape (BRepBuilderAPI_MakeShape &mkShape, const std::vector< TopoShape > &sources, const char *op=nullptr)
TopoShape & makeElementShape (BRepBuilderAPI_MakeShape &mkShape, const TopoShape &source, const char *op=nullptr)
TopoShape makeElementShape (BRepBuilderAPI_MakeShape &mkShape, const char *op=nullptr) const
TopoShape & makeElementShape (BRepFeat_MakePrism &mkShape, const std::vector< TopoShape > &sources, const TopoShape &uptoface, const char *op)
Additional Inherited Members
Static Public Member Functions inherited from Data::ComplexGeoData
static std::pair< std::string, unsigned long > getTypeAndIndex (const char *Name)
static const std::string & elementMapPrefix ()
static bool isElementName (const char *subName)
Check if the given sub-name only contains an element name.
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions inherited from Data::ComplexGeoData
Base::Vector3d transformPointToOutside (const Base::Vector3f &vec) const
from local to outside
template<typename Vec >
std::vector< Base::Vector3d > transformPointsToOutside (const std::vector< Vec > &input) const
from local to outside
Base::Vector3d transformVectorToOutside (const Base::Vector3f &vec) const
template<typename Vec >
std::vector< Base::Vector3d > transformVectorsToOutside (const std::vector< Vec > &input) const
Base::Vector3f transformPointToInside (const Base::Vector3d &vec) const
from local to inside
void restoreStream (std::istream &stream, std::size_t count)
void readElements (Base::XMLReader &reader, size_t count)
Base::Vector3d transformToOutside (const Base::Vector3f &vec) const
from local to outside
Base::Vector3f transformToInside (const Base::Vector3d &vec) const
from local to inside
ElementMapPtr elementMap (bool flush=true) const
ElementMapPtr ensureElementMap (bool flush=true)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Data::ComplexGeoData
std::string _persistenceName
bool _restoreFailed = false
Detailed Description
Parameters for TopoShape::makeElementFilledFace()
The representation for a CAD Shape
Definition at line 276 of file TopoShape.h.
Member Enumeration Documentation
ConnectionPolicy
enum Part::TopoShape::ConnectionPolicy strong
Enumerator
requireSharedVertex
mergeWithTolerance
Definition at line 1676 of file TopoShape.h.
Continuity
enum Part::TopoShape::Continuity strong
Provides information about the continuity of a curve. Corresponds to OCCT type GeomAbs_Shape
Enumerator
C0
Only geometric continuity.
G1
for each point on the curve, the tangent vectors 'on the right' and 'on the left' are collinear with the same orientation.
C1
Continuity of the first derivative. The 'C1' curve is also 'G1' but, in addition, the tangent vectors 'on the right' and 'on the left' are equal.
G2
For each point on the curve, the normalized normal vectors 'on the right' and 'on the left' are equal.
C2
Continuity of the second derivative.
C3
Continuity of the third derivative.
CN
Continuity of the N-th derivative, whatever is the value given for N (infinite order of continuity). Also provides information about the continuity of a surface.
Definition at line 2401 of file TopoShape.h.
PrismMode
enum Part::TopoShape::PrismMode
Operation mode for makeElementPrismUntil()
Enumerator
CutFromBase
Remove the generated prism shape from the base shape with boolean cut.
FuseWithBase
Add generated prism shape to the base shape with fusion.
None
Return the generated prism shape without base shape.
Definition at line 1197 of file TopoShape.h.
SingleShapeCompoundCreationPolicy
enum Part::TopoShape::SingleShapeCompoundCreationPolicy strong
When given a single shape to create a compound, two results are possible: either to simply return the shape as given, or to force it to be placed in a Compound.
Enumerator
returnShape
forceCompound
Definition at line 1653 of file TopoShape.h.
SplitWireReorient
enum Part::TopoShape::SplitWireReorient
Wire re-orientation when calling splitWires()
Enumerator
NoReorient
Keep original reorientation.
Reorient
Make outer wire forward, and inner wires reversed.
ReorientForward
Make both outer and inner wires forward.
ReorientReversed
Make both outer and inner wires reversed.
Definition at line 629 of file TopoShape.h.
Constructor & Destructor Documentation
TopoShape() [1/3]
TopoShape::TopoShape (long Tag = 0, App::StringHasherRef hasher = App::StringHasherRef(), const TopoDS_Shape & shape = TopoDS_Shape())
Definition at line 285 of file TopoShape.cpp.
References Data::ComplexGeoData::Hasher, Data::ComplexGeoData::Tag, and Dice3DS.dom3ds::tag.
Referenced by FC_LOG_LEVEL_INIT(), getFacesFromSubElement(), getPyObject(), makeOffset2D(), and transformShape().
TopoShape() [2/3]
TopoShape::TopoShape (const TopoDS_Shape & shape, long Tag = 0, App::StringHasherRef hasher = App::StringHasherRef())
Definition at line 292 of file TopoShape.cpp.
References Data::ComplexGeoData::Hasher, Data::ComplexGeoData::Tag, and Dice3DS.dom3ds::tag.
TopoShape() [3/3]
TopoShape::TopoShape (const TopoShape & shape)
Definition at line 299 of file TopoShape.cpp.
~TopoShape()
TopoShape::~TopoShape () override default
Member Function Documentation
_makeElementTransform()
bool Part::TopoShape::_makeElementTransform (const TopoShape & source, const Base::Matrix4D & mat, const char * op = nullptr, CheckScale checkScale = CheckScale::noScaleCheck, CopyType copy = CopyType::noCopy)
Make a new shape with transformation
Parameters
source input shape
mat transformation matrix
op optional string to be encoded into topo naming for indicating the operation
checkScale whether to check if the transformation matrix contains scaling factor.
copy whether to perform deep copy of the shape. If noCopy, and checkScale, then the shape will be copied if there is scaling.
Returns
Returns true if scaling is performed.
The original content of this TopoShape is discarded and replaced with the new transformed shape.
Referenced by FC_LOG_LEVEL_INIT().
_makeTransform()
bool TopoShape::_makeTransform (const TopoShape & shape, const Base::Matrix4D & mat, const char * op = nullptr, bool checkScale = false, bool copy = false)
Definition at line 4111 of file TopoShape.cpp.
References Part::checkScale, Base::Console(), convert(), Base::Matrix4D::determinant3(), SCL.SimpleDataTypes::e, Base::Matrix4D::hasScale(), makeGTransform(), makeTransform(), Base::NoScaling, Path.Post.scripts.grbl_post::type, Base::Uniform, and Base::ConsoleSingleton::Warning().
Referenced by transformShape().
analyze()
bool TopoShape::analyze (bool runBopCheck, std::ostream & str) const
Definition at line 1427 of file TopoShape.cpp.
References Part::buildBOPCheckResultVector(), Part::buildShapeEnumVector(), Handle(), SplineSurface::i, result, shapeEnumToString(), Path.Post.scripts.refactored_centroid_post::str, and toolbit-attributes::val.
cacheRelatedElements()
void Part::TopoShape::cacheRelatedElements (const Data::MappedName & name, HistoryTraceType sameType, const QVector< Data::MappedElement > & names) const
Referenced by FC_LOG_LEVEL_INIT().
canMapElement()
bool Part::TopoShape::canMapElement (const TopoShape & other) const
Referenced by FC_LOG_LEVEL_INIT().
chooseMatchingSubShapeByPlaneOrLine()
static Data::MappedElement Part::TopoShape::chooseMatchingSubShapeByPlaneOrLine (const TopoShape & shapeToFind, const TopoShape & shapeToLookIn) static
Search to see if a SubShape matches.
Referenced by FC_LOG_LEVEL_INIT(), and Part::Feature::getExportElementName().
common() [1/2]
TopoDS_Shape TopoShape::common (const std::vector< TopoDS_Shape > & shapes, Standard_Real tolerance = -1.0) const
Definition at line 1744 of file TopoShape.cpp.
References makeShell(), FCBRepAlgoAPI_BooleanOperation::setAutoFuzzy(), and draftutils.utils::tolerance().
common() [2/2]
TopoDS_Shape TopoShape::common (TopoDS_Shape shape) const
Definition at line 1734 of file TopoShape.cpp.
References makeShell().
convert() [1/2]
gp_Trsf TopoShape::convert (const Base::Matrix4D & mtrx) static
Definition at line 630 of file TopoShape.cpp.
References convertTogpTrsf().
convert() [2/2]
Base::Matrix4D TopoShape::convert (const gp_Trsf & trsf) static
Definition at line 624 of file TopoShape.cpp.
References convertToMatrix().
Referenced by _makeTransform(), Import::ImpExpDxfRead::ExpandInsert(), FC_LOG_LEVEL_INIT(), Fem::Tools::getSubShapeGlobalLocation(), and setPlacement().
convertTogpTrsf()
void TopoShape::convertTogpTrsf (const Base::Matrix4D & mtrx, gp_Trsf & trsf) static
Definition at line 591 of file TopoShape.cpp.
Referenced by convert(), and setTransform().
convertToMatrix()
void TopoShape::convertToMatrix (const gp_Trsf & trsf, Base::Matrix4D & mtrx) static
Definition at line 598 of file TopoShape.cpp.
References test::m, and buildPsets::p.
Referenced by convert(), getTransform(), and Attacher::AttachEngine::placementFactory().
copyElementMap()
void Part::TopoShape::copyElementMap (const TopoShape & topoShape, const char * op = nullptr)
Referenced by FC_LOG_LEVEL_INIT().
countSubElements()
unsigned long TopoShape::countSubElements (const char * Type) const override virtual
Implements Data::ComplexGeoData.
Definition at line 326 of file TopoShape.cpp.
References countSubShapes().
Referenced by dressupGetSelected().
countSubShapes() [1/2]
unsigned long TopoShape::countSubShapes (const char * Type) const
Definition at line 353 of file TopoShape.cpp.
References shapeType(), and Path.Post.scripts.grbl_post::type.
Referenced by PartDesignGui::TaskDressUpParameters::addAllEdges(), PartDesign::FeatureExtrude::buildExtrusion(), countSubElements(), PartDesign::Thickness::execute(), Attacher::AttachEngine::extractSubShape(), FC_LOG_LEVEL_INIT(), findPlane(), PartDesign::DressUp::getAddSubShape(), PartDesign::ProfileBased::getTopoShapeVerifiedFace(), and hasSubShape().
countSubShapes() [2/2]
unsigned long TopoShape::countSubShapes (TopAbs_ShapeEnum type) const
Definition at line 365 of file TopoShape.cpp.
References src.Mod.AddonManager.NetworkManager::count.
cut() [1/2]
TopoDS_Shape TopoShape::cut (const std::vector< TopoDS_Shape > & shapes, Standard_Real tolerance = -1.0) const
Definition at line 1705 of file TopoShape.cpp.
References makeShell(), FCBRepAlgoAPI_BooleanOperation::setAutoFuzzy(), and draftutils.utils::tolerance().
cut() [2/2]
TopoDS_Shape TopoShape::cut (TopoDS_Shape shape) const
Definition at line 1695 of file TopoShape.cpp.
References makeShell().
Referenced by Surface::Cut::execute().
decodeElementComboName()
std::vector<Data::MappedName> Part::TopoShape::decodeElementComboName (const Data::IndexedName & element, const Data::MappedName & name, const char * marker = nullptr, std::string * postfix = nullptr) const
Referenced by FC_LOG_LEVEL_INIT(), and Part::Feature::getExportElementName().
defeaturing()
TopoDS_Shape TopoShape::defeaturing (const std::vector< TopoDS_Shape > & s) const
Definition at line 3669 of file TopoShape.cpp.
References toolbit-attributes::s.
dump()
void TopoShape::dump (std::ostream & out) const
Definition at line 993 of file TopoShape.cpp.
exportBinary()
void TopoShape::exportBinary (std::ostream & out) const
Definition at line 961 of file TopoShape.cpp.
References src.Mod.Test.testPathArray::orient.
Referenced by Part::PropertyPartShape::Save(), Part::PropertyTopoShapeList::SaveDocFile(), and Part::PropertyPartShape::SaveDocFile().
exportBrep() [1/2]
void TopoShape::exportBrep (const char * FileName) const
Definition at line 935 of file TopoShape.cpp.
References Part::encodeFilename().
Referenced by Part::PropertyPartShape::Save(), Part::PropertyTopoShapeList::SaveDocFile(), Part::PropertyPartShape::SaveDocFile(), write(), and MeshPartGui::Mesh2ShapeGmsh::writeProject().
exportBrep() [2/2]
void TopoShape::exportBrep (std::ostream & out) const
Definition at line 946 of file TopoShape.cpp.
exportFaceSet()
void TopoShape::exportFaceSet (double dev, double ca, const std::vector< App::Color > & colors, std::ostream & str) const
Definition at line 1009 of file TopoShape.cpp.
References Base::InventorBuilder::addNode(), Base::InventorBuilder::beginSeparator(), SCL.SimpleDataTypes::c, importers.importIFCmulticore::colors, defaultAngularDeflection(), Base::InventorBuilder::endSeparator(), Part::Tools::getTriangulation(), SplineSurface::i, Base::MaterialItem::setDiffuseColor(), Base::MaterialItem::setTransparency(), and Path.Post.scripts.refactored_centroid_post::str.
exportIges()
void TopoShape::exportIges (const char * FileName) const
Definition at line 872 of file TopoShape.cpp.
References SCL.SimpleDataTypes::e, Part::encodeFilename(), Part::Interface::writeIgesHeaderAuthor(), Part::Interface::writeIgesHeaderCompany(), and Part::Interface::writeIgesHeaderProduct().
Referenced by write().
exportLineSet()
void TopoShape::exportLineSet (std::ostream & str) const
Definition at line 1075 of file TopoShape.cpp.
References Base::InventorBuilder::addNode(), Base::InventorBuilder::beginSeparator(), Base::InventorBuilder::endSeparator(), Part::Tools::getPolygon3D(), Part::Tools::getPolygonOnTriangulation(), SplineSurface::i, Base::DrawStyle::lineWidth, buildPsets::p, and Path.Post.scripts.refactored_centroid_post::str.
exportStep()
void TopoShape::exportStep (const char * FileName) const
Definition at line 893 of file TopoShape.cpp.
References SCL.SimpleDataTypes::e, Part::encodeFilename(), Handle(), Part::Interface::Off, ClipperLib::pi, and Part::Interface::writeStepAssembly().
Referenced by write().
exportStl()
void TopoShape::exportStl (const char * FileName, double deflection) const
Definition at line 998 of file TopoShape.cpp.
References defaultAngularDeflection(), and Part::encodeFilename().
Referenced by write().
findAncestor()
int Part::TopoShape::findAncestor (const TopoDS_Shape & subshape, TopAbs_ShapeEnum type) const
Referenced by PartDesign::Thickness::execute(), and FC_LOG_LEVEL_INIT().
findAncestors()
std::vector<int> Part::TopoShape::findAncestors (const TopoDS_Shape & subshape, TopAbs_ShapeEnum type) const
Referenced by FC_LOG_LEVEL_INIT(), Part::Feature::getExportElementName(), and PartDesign::ProfileBased::getProfileNormal().
findAncestorShape()
TopoDS_Shape Part::TopoShape::findAncestorShape (const TopoDS_Shape & subshape, TopAbs_ShapeEnum type) const
Referenced by FC_LOG_LEVEL_INIT().
findAncestorsShapes()
std::vector<TopoDS_Shape> Part::TopoShape::findAncestorsShapes (const TopoDS_Shape & subshape, TopAbs_ShapeEnum type) const
Referenced by FC_LOG_LEVEL_INIT(), and PartDesign::DressUp::getContinuousEdges().
findPlane()
bool TopoShape::findPlane (gp_Pln & plane, double tol = -1, double atol = -1) const
Definition at line 3928 of file TopoShape.cpp.
References SCL.SimpleDataTypes::c, ArchCommands::check(), countSubShapes(), SCL.SimpleDataTypes::e, FC_LOG, getShape(), getSubShape(), getSubShapes(), Handle(), hasSubShape(), SplineSurface::i, WorkingPlane::plane, DrawingExample::Shape, buildPsets::u, TestSpreadsheet::v, and SurfaceTests.TestBlendCurve::vec.
Referenced by FC_LOG_LEVEL_INIT(), PartDesign::ProfileBased::getProfileNormal(), PartDesign::ProfileBased::getTopoShapeSupportFace(), and isCoplanar().
findShape() [1/3]
TopoDS_Shape Part::TopoShape::findShape (const char * name) const
findShape() [2/3]
int Part::TopoShape::findShape (const TopoDS_Shape & subshape) const
Referenced by FC_LOG_LEVEL_INIT().
findShape() [3/3]
TopoDS_Shape Part::TopoShape::findShape (TopAbs_ShapeEnum type, int idx) const
findSubShapesWithSharedVertex()
std::vector<TopoShape> Part::TopoShape::findSubShapesWithSharedVertex (const TopoShape & subshape, std::vector< std::string > * names = nullptr, Data::SearchOptions = Data::SearchOption::CheckGeometry, double tol = 1e-7, double atol = 1e-12) const
Find sub shapes with shared Vertexes.
Renamed: searchSubShape -> findSubShapesWithSharedVertex
unlike findShape(), the input shape does not have to be an actual sub-shape of this shape. The sub-shape is searched by shape geometry Note that subshape must be a Vertex, Edge, or Face.
Parameters
subshape a sub shape to search
names optional output of found sub shape indexed based name
checkGeometry whether to compare shape geometry
tol tolerance to check coincident vertices
atol tolerance to check for same angles
Referenced by FC_LOG_LEVEL_INIT().
fix() [1/2]
bool TopoShape::fix ()
Definition at line 3062 of file TopoShape.cpp.
References makeElementCopy(), and makeShapeWithElementMap().
Referenced by fix(), makeWires(), and removeInternalWires().
fix() [2/2]
bool TopoShape::fix (double precision, double mintol, double maxtol)
Definition at line 3115 of file TopoShape.cpp.
References fix(), isValid(), draftgeoutils.general::precision(), and Path.Post.scripts.grbl_post::type.
fixSolidOrientation()
bool Part::TopoShape::fixSolidOrientation ()
Referenced by FC_LOG_LEVEL_INIT().
flushElementMap()
void Part::TopoShape::flushElementMap () const override virtual
Flush an internal buffering for element mapping
Reimplemented from Data::ComplexGeoData.
Referenced by FC_LOG_LEVEL_INIT().
fuse() [1/2]
TopoDS_Shape TopoShape::fuse (const std::vector< TopoDS_Shape > & shapes, Standard_Real tolerance = -1.0) const
Definition at line 1783 of file TopoShape.cpp.
References makeShell(), FCBRepAlgoAPI_BooleanOperation::setAutoFuzzy(), and draftutils.utils::tolerance().
fuse() [2/2]
TopoDS_Shape TopoShape::fuse (TopoDS_Shape shape) const
Definition at line 1773 of file TopoShape.cpp.
References makeShell().
generalFuse()
TopoDS_Shape TopoShape::generalFuse (const std::vector< TopoDS_Shape > & sOthers, Standard_Real tolerance, std::vector< TopTools_ListOfShape > * mapInOut = nullptr) const
generalFuse: run general fuse algorithm between this and shapes supplied as sOthers
Parameters
sOthers (input): list of shapes to run the algorithm between (this is automatically added to the list)
tolerance (input): fuzzy value (pass zero to disable fuzzyness and use shape tolerances only)
mapInOut (output): pointer to list of lists, to write the info which shapes in result came from which argument shape. The length of list is equal to length of sOthers+1. First element is a list of shapes that came from shape of this, and the rest are those that come from shapes in sOthers. If the info is not needed, nullptr can be passed.
Returns
compound of slices that can be combined to reproduce results of cut, fuse, common. The shapes share edges and faces where they touch. For example, if input shapes are two intersecting spheres, GFA returns three solids: two cuts and common.
Definition at line 1901 of file TopoShape.cpp.
References FCBRepAlgoAPIHelper::setAutoFuzzy(), and draftutils.utils::tolerance().
getAccuracy()
double TopoShape::getAccuracy () const override virtual
Get the standard accuracy to be used with getPoints, getLines or getFaces.
Reimplemented from Data::ComplexGeoData.
Definition at line 3317 of file TopoShape.cpp.
References getBoundBox(), Base::BoundBox3< Precision >::IsValid(), Base::BoundBox3< Precision >::LengthX(), Base::BoundBox3< Precision >::LengthY(), and Base::BoundBox3< Precision >::LengthZ().
Referenced by Inspection::InspectActualShape::InspectActualShape().
getBoundBox()
Base::BoundBox3d TopoShape::getBoundBox () const override virtual
Bound box from the CasCade shape.
Implements Data::ComplexGeoData.
Definition at line 1115 of file TopoShape.cpp.
References KDL::Add(), MengerSponge::box, xMax, xMin, yMax, and yMin.
Referenced by PathSimulator::PathSim::BeginSimulation(), and getAccuracy().
getCenterOfGravity()
bool TopoShape::getCenterOfGravity (Base::Vector3d & center) const override virtual
Get the center of gravity If this method is implemented then true is returned and the center of gravity. The default implementation only returns false.
Reimplemented from Data::ComplexGeoData.
Definition at line 1184 of file TopoShape.cpp.
References exportCSG::center().
getDomains()
void TopoShape::getDomains (std::vector< Domain > & domains) const
Definition at line 3261 of file TopoShape.cpp.
References Data::ComplexGeoData::Domain::facets, Part::Tools::getTriangulation(), Data::ComplexGeoData::Facet::I1, Data::ComplexGeoData::Facet::I2, Data::ComplexGeoData::Facet::I3, Data::ComplexGeoData::Domain::points, DrawingExample::X, and DrawingExample::Y.
Referenced by getFaces().
getElementTypeAndIndex()
std::pair< std::string, unsigned long > TopoShape::getElementTypeAndIndex (const char * Name) static
Unlike getTypeAndIndex() this function only handles the supported element types.
Definition at line 305 of file TopoShape.cpp.
References Path.Post.scripts.refactored_centroid_post::str.
Referenced by PartGui::ViewProviderPartExt::getDetail().
getElementTypes()
std::vector< const char * > TopoShape::getElementTypes () const override virtual
Sub type list List of different subelement types it is NOT a list of the subelements itself
Implements Data::ComplexGeoData.
Definition at line 320 of file TopoShape.cpp.
getFaces()
void TopoShape::getFaces (std::vector< Base::Vector3d > & Points, std::vector< Facet > & faces, double Accuracy, uint16_t flags = 0) const override virtual
Get faces from object with given accuracy
Reimplemented from Data::ComplexGeoData.
Definition at line 3326 of file TopoShape.cpp.
References defaultAngularDeflection(), and getDomains().
getFacesFromSubElement()
void TopoShape::getFacesFromSubElement (const Data::Segment * segment, std::vector< Base::Vector3d > & Points, std::vector< Base::Vector3d > & PointNormals, std::vector< Facet > & faces) const override virtual
Get faces from segment
Reimplemented from Data::ComplexGeoData.
Definition at line 3650 of file TopoShape.cpp.
References Base::BaseClass::is(), DrawingExample::Shape, and TopoShape().
getHigherElements()
std::vector<Data::IndexedName> Part::TopoShape::getHigherElements (const char * name, bool silent = false) const override virtual
Return the higher level element names of the given element.
Reimplemented from Data::ComplexGeoData.
Referenced by FC_LOG_LEVEL_INIT().
getLines()
void TopoShape::getLines (std::vector< Base::Vector3d > & Points, std::vector< Line > & lines, double Accuracy, uint16_t flags = 0) const override virtual
Get lines from object with given accuracy
Reimplemented from Data::ComplexGeoData.
Definition at line 3516 of file TopoShape.cpp.
getLinesFromSubElement()
void TopoShape::getLinesFromSubElement (const Data::Segment * segment, std::vector< Base::Vector3d > & Points, std::vector< Line > & lines) const override virtual
Get lines from segment
Reimplemented from Data::ComplexGeoData.
Definition at line 3637 of file TopoShape.cpp.
References Base::BaseClass::is(), and DrawingExample::Shape.
getMemSize()
unsigned int TopoShape::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Reimplemented from Data::ComplexGeoData.
Definition at line 1236 of file TopoShape.cpp.
References Handle(), SplineSurface::i, surface, and TopoShape_RefCountShapes().
Referenced by Part::PropertyPartShape::getMemSize().
getOrderedEdges()
std::vector<TopoShape> Part::TopoShape::getOrderedEdges (MapElement mapElement = MapElement::map) const
Locate all the Edges in the Wires of this shape
Parameters
mapElement If True, map the subelements (Edges) found
Returns
Vector of the edges
Referenced by FC_LOG_LEVEL_INIT().
getOrderedVertexes()
std::vector<TopoShape> Part::TopoShape::getOrderedVertexes (MapElement mapElement = MapElement::map) const
Locate all the Vertexes in the Wires of this shape
Parameters
mapElement If True, map the subelements (Vertexes) found
Returns
Vector of the Vertexes
Referenced by FC_LOG_LEVEL_INIT().
getPoints()
void TopoShape::getPoints (std::vector< Base::Vector3d > & Points, std::vector< Base::Vector3d > & Normals, double Accuracy, uint16_t flags = 0) const override virtual
Get points from object with given accuracy
Reimplemented from Data::ComplexGeoData.
Definition at line 3523 of file TopoShape.cpp.
References SCL.SimpleDataTypes::e, Handle(), SplineSurface::i, KDL::max(), buildPsets::p, toolbit-attributes::s, surface, InitGui::t, src.Mod.PartDesign.Scripts.Gear::t1, src.Mod.PartDesign.Scripts.Gear::t2, buildPsets::u, TestSpreadsheet::v, and draftgeoutils.general::v1().
getPyObject()
PyObject * TopoShape::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 526 of file TopoShape.cpp.
References Base::PyObjectBase::setNotTracking(), TopoShape(), and Path.Post.scripts.grbl_post::type.
Referenced by Part::PropertyPartShape::getPyObject().
getPySubShape()
PyObject * TopoShape::getPySubShape (const char * Type, bool silent = false) const
get the Topo"sub"Shape with the given name
Definition at line 521 of file TopoShape.cpp.
References getSubShape(), Py::new_reference_to(), and Part::shape2pyshape().
getRelatedElementsCached()
bool Part::TopoShape::getRelatedElementsCached (const Data::MappedName & name, HistoryTraceType sameType, QVector< Data::MappedElement > & names) const
Referenced by FC_LOG_LEVEL_INIT().
getShape()
const TopoDS_Shape& Part::TopoShape::getShape () const inline
Definition at line 298 of file TopoShape.h.
Referenced by Part::FaceMaker::addTopoShape(), PartGui::DlgExtrusion::EdgeSelection::allow(), PartGui::SweepWidget::Private::EdgeSelection::allow(), PartGui::MirrorPlaneSelection::allow(), TechDraw::ReferenceEntry::asCanonicalTopoShape(), PartDesign::FeatureExtrude::buildExtrusion(), PartDesign::Pipe::buildPipePath(), TechDraw::GeometryMatcher::compareGeometry(), dressupGetSelected(), PartDesign::Body::execute(), Part::MultiFuse::execute(), PartDesign::Loft::execute(), PartDesign::Fillet::execute(), PartDesign::Helix::execute(), Part::Mirroring::execute(), PartDesign::Chamfer::execute(), PartDesign::Pipe::execute(), Part::Revolution::execute(), Path::FeatureArea::execute(), PartDesign::Boolean::execute(), PartDesign::Revolution::execute(), PartDesign::Groove::execute(), Drawing::FeatureProjection::execute(), TechDraw::FeatureProjection::execute(), PartDesign::Transformed::execute(), Part::Helix::execute(), Part::Spiral::execute(), FC_LOG_LEVEL_INIT(), Part::Revolution::fetchAxisLink(), Part::Extrusion::fetchAxisLink(), Part::findAllFacesCutBy(), findPlane(), PartGui::DlgScale::findShapes(), PartGui::DlgExtrusion::findShapes(), TechDraw::DimensionAutoCorrect::fixBrokenReferences(), PartDesign::FeatureExtrude::generatePrism(), PartDesign::DressUp::getAddSubShape(), Part::PropertyPartShape::getBoundingBox(), PartDesign::DressUp::getContinuousEdges(), Sketcher::SketchObject::getEdge(), TechDraw::DrawViewDimension::getEdges(), Measure::ShapeFinder::getLocatedShape(), getLocatedShape(), TechDraw::ShapeExtractor::getLocatedShape(), TechDraw::ShapeExtractor::getLocation3dFromFeat(), Fem::Constraint::getPoints(), PartDesign::ProfileBased::getReversedAngle(), Part::Datum::getShape(), Part::Feature::getShape(), Sketcher::SketchObject::getSubObject(), PartDesign::ProfileBased::getSupportFace(), PartDesign::ProfileBased::getThroughAllLength(), PartDesign::Mirrored::getTransformations(), PartDesign::ProfileBased::getUpToFace(), Part::PropertyPartShape::getValue(), TechDraw::DrawViewDimension::getVertexes(), Part::ExtrusionHelper::makeElementDraft(), makeFace(), makeRefine(), makeTransform(), makeWires(), Part::Scale::nonuniformScale(), Sketcher::SketchObject::rebuildExternalGeometry(), Part::PropertyPartShape::Restore(), Part::PropertyPartShape::SaveDocFile(), shapeType(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), and Part::Scale::uniformScale().
getSubElement()
Data::Segment * TopoShape::getSubElement (const char * Type, unsigned long index) const override virtual
get the subelement by type and number
Implements Data::ComplexGeoData.
Definition at line 331 of file TopoShape.cpp.
References getSubShape(), and Path.Post.scripts.refactored_centroid_post::str.
getSubShape() [1/2]
TopoDS_Shape TopoShape::getSubShape (const char * Type, bool silent = false) const
Locate the TopoDS_Shape associated with a Topo"sub"Shape of the given name
Parameters
Type The complete name of the subshape - for example "Face2"
silent True to suppress the exception throw if the shape isn't found
Returns
The shape or a null TopoDS_Shape
Definition at line 340 of file TopoShape.cpp.
References toolbit-attributes::s.
Referenced by PartGui::DlgRevolution::EdgeSelection::allow(), PartDesign::Pipe::buildPipePath(), Surface::Filling::execute(), Surface::Sections::execute(), PartDesign::Thickness::execute(), PartDesign::Pipe::execute(), Surface::Extend::execute(), Robot::Edge2TracObject::execute(), FC_LOG_LEVEL_INIT(), findPlane(), PartDesign::ProfileBased::getAxis(), Fem::Constraint::getBasePoint(), PartDesign::DressUp::getContinuousEdges(), Fem::Constraint::getDirection(), Part::Feature::getExportElementName(), PartDesign::ProfileBased::getFaceFromLinkSub(), Assembly::getFaceRadius(), Fem::Tools::getFeatureSubShape(), getLocatedShape(), PartDesign::ProfileBased::getProfileNormal(), PartDesign::ProfileBased::getProfileWires(), getPySubShape(), getSubElement(), PartDesign::ProfileBased::getSupportFace(), PartDesign::LinearPattern::getTransformations(), PartDesign::Mirrored::getTransformations(), PartDesign::PolarPattern::getTransformations(), PartDesignGui::TaskFeaturePick::makeCopy(), Fem::ConstraintBearing::onChanged(), FemGui::TaskFemConstraintBearing::onSelectionChanged(), FemGui::TaskFemConstraintGear::onSelectionChanged(), Sketcher::SketchObject::rebuildExternalGeometry(), and Sketcher::SketchObject::validateExternalLinks().
getSubShape() [2/2]
TopoDS_Shape TopoShape::getSubShape (TopAbs_ShapeEnum type, int idx, bool silent = false) const
Locate a subshape's TopoDS_Shape by type enum and index. See doc above.
Parameters
type Shape type enum value
idx Index number of the subshape within the shape
silent True to suppress the exception throw
Returns
The shape, or a null TopoShape.
Definition at line 346 of file TopoShape.cpp.
References toolbit-attributes::s, and Path.Post.scripts.grbl_post::type.
getSubShapes()
std::vector<TopoDS_Shape> Part::TopoShape::getSubShapes (TopAbs_ShapeEnum type = TopAbs_SHAPE, TopAbs_ShapeEnum avoid = TopAbs_SHAPE) const
Locate all of the sub TopoDS_Shapes of a given type, while avoiding a given type
Parameters
type The type to find
avoid The type to avoid
Returns
The sub TopoDS_Shapes.
Referenced by FC_LOG_LEVEL_INIT(), findPlane(), and Sketcher::SketchObject::rebuildExternalGeometry().
getSubTopoShape() [1/2]
TopoShape Part::TopoShape::getSubTopoShape (const char * Type, bool silent = false) const
Locate a subshape by name within this shape. If null or empty Type specified, try my own shapeType; if I'm not a COMPOUND OR COMPSOLID, return myself; otherwise, look to see if I have any singular SOLID, SHELL, FACE, WIRE, EDGE or VERTEX and return that. If a Type is specified, then treat it as the complete name of the subshape - for example "Face3" and try to find and return that shape.
Parameters
Type The Shape name
silent True to suppress the exception throw if the shape isn't found.
Returns
The shape or a null TopoShape.
Referenced by PartDesign::Thickness::execute(), Part::Sweep::execute(), Attacher::AttachEngine::extractSubShape(), FC_LOG_LEVEL_INIT(), PartDesign::DressUp::getAddSubShape(), Part::Feature::getExportElementName(), PartDesign::DressUp::getFaces(), Measure::ShapeFinder::getLocatedShape(), PartDesign::ProfileBased::getProfileNormal(), PartDesign::ProfileBased::getTopoShapeSupportFace(), PartDesign::ProfileBased::getTopoShapeVerifiedFace(), PartDesign::ProfileBased::getUpToFace(), and Part::Feature::onBeforeChange().
getSubTopoShape() [2/2]
TopoShape Part::TopoShape::getSubTopoShape (TopAbs_ShapeEnum type, int idx, bool silent = false) const
Locate a subshape by type enum and index. See doc above.
Parameters
type Shape type enum value
idx Index number of the subshape within the shape
silent True to suppress the exception throw
Returns
The shape, or a null TopoShape.
getSubTopoShapes()
std::vector<TopoShape> Part::TopoShape::getSubTopoShapes (TopAbs_ShapeEnum type = TopAbs_SHAPE, TopAbs_ShapeEnum avoid = TopAbs_SHAPE) const
Locate all of the sub TopoShapes of a given type, while avoiding a given type
Parameters
type The type to find
avoid The type to avoid
Returns
The sub TopoShapes.
Referenced by PartDesign::FeatureExtrude::buildExtrusion(), Part::MultiFuse::execute(), PartDesign::Fillet::execute(), PartDesign::Chamfer::execute(), FC_LOG_LEVEL_INIT(), getElements(), Part::Feature::getExportElementName(), CAMSimulator::DlgCAMSimulator::GetMeshData(), PartDesign::Loft::getSectionShape(), PartDesign::ProfileBased::getTopoShapeProfileWires(), PartDesign::ProfileBased::getTopoShapeVerifiedFace(), PartDesign::ProfileBased::getUpToShapeFromLinkSubList(), Part::ExtrusionHelper::makeElementDraft(), PartDesign::FeatureExtrude::makeShellFromUpToShape(), Sketcher::SketchObject::rebuildExternalGeometry(), and Part::FaceMaker::useTopoCompound().
getTransform()
Base::Matrix4D TopoShape::getTransform () const override virtual
get the transformation of the CasCade Shape
Implements Data::ComplexGeoData.
Definition at line 644 of file TopoShape.cpp.
References convertToMatrix().
Referenced by PartDesign::Body::execute(), PartDesign::ShapeBinder::execute(), Part::PropertyPartShape::getTransform(), PartDesign::ShapeBinder::hasPlacementChanged(), and Part::Feature::onChanged().
hasPendingElementMap()
bool Part::TopoShape::hasPendingElementMap () const
Referenced by FC_LOG_LEVEL_INIT().
hasSubShape() [1/2]
bool TopoShape::hasSubShape (const char * Type) const
Definition at line 387 of file TopoShape.cpp.
References countSubShapes(), and shapeTypeAndIndex().
Referenced by PartDesign::FeatureExtrude::buildExtrusion(), Part::Extrusion::extrudeShape(), FC_LOG_LEVEL_INIT(), findPlane(), PartDesign::DressUp::getAddSubShape(), PartDesign::ProfileBased::getProfileNormal(), PartDesign::ProfileBased::getTopoShapeSupportFace(), PartDesign::ProfileBased::getTopoShapeVerifiedFace(), PartDesign::ProfileBased::getUpToFace(), PartDesign::ProfileBased::getUpToFaceFromLinkSub(), and Part::ExtrusionHelper::makeElementDraft().
hasSubShape() [2/2]
bool TopoShape::hasSubShape (TopAbs_ShapeEnum type) const
Definition at line 378 of file TopoShape.cpp.
References KDL::exp(), and Path.Post.scripts.grbl_post::type.
importBinary()
void TopoShape::importBinary (std::istream & str)
Definition at line 825 of file TopoShape.cpp.
References src.Mod.Test.testPathArray::orient, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by Part::PropertyPartShape::Restore(), and Part::PropertyPartShape::RestoreDocFile().
importBrep() [1/2]
void TopoShape::importBrep (const char * FileName)
Definition at line 772 of file TopoShape.cpp.
References SCL.SimpleDataTypes::e, Part::encodeFilename(), Handle(), and ClipperLib::pi.
Referenced by Part::ImportBrep::execute(), read(), and Part::PropertyPartShape::Restore().
importBrep() [2/2]
void TopoShape::importBrep (std::istream & str, int indicator = 1)
Definition at line 794 of file TopoShape.cpp.
References SCL.SimpleDataTypes::e, Handle(), NavigationIndicatorGui::indicator, ClipperLib::pi, and Path.Post.scripts.refactored_centroid_post::str.
importIges()
void TopoShape::importIges (const char * FileName)
Example code to get the labels for each face in an IGES file.
#include <XSControl_WorkSession.hxx>
#include <XSControl_TransferReader.hxx>
#include <IGESData_IGESModel.hxx>
#include <IGESData_IGESEntity.hxx>
IGESControl_Reader aReader;
...
// Gets the labels of all face items if defined in the IGES file
Handle(XSControl_WorkSession) ws = aReader.WS();
Handle(XSControl_TransferReader) tr = ws->TransferReader();
std::string name;
Handle(IGESData_IGESModel) aModel = aReader.IGESModel();
Standard_Integer all = aModel->NbEntities();
TopExp_Explorer ex;
for (ex.Init(this->_Shape, TopAbs_FACE); ex.More(); ex.Next())
{
    const TopoDS_Face& aFace = TopoDS::Face(ex.Current());
    Handle(Standard_Transient) ent = tr->EntityFromShapeResult(aFace, 1);
    if (!ent.IsNull()) {
        int i = aModel->Number(ent);
        if (i > 0) {
            Handle(IGESData_IGESEntity) ie = aModel->Entity(i);
            if (ie->HasShortLabel())
                name = ie->ShortLabel()->ToCString();
        }
    }
}
Definition at line 712 of file TopoShape.cpp.
References SCL.SimpleDataTypes::e, Part::encodeFilename(), Handle(), and ClipperLib::pi.
Referenced by Part::ImportIges::execute(), and read().
importStep()
void TopoShape::importStep (const char * FileName)
Definition at line 745 of file TopoShape.cpp.
References SCL.SimpleDataTypes::e, Part::encodeFilename(), Handle(), and ClipperLib::pi.
Referenced by Part::ImportStep::execute(), and read().
initCache()
void Part::TopoShape::initCache (int reset = 0) const
Referenced by FC_LOG_LEVEL_INIT(), Part::PropertyPartShape::getComplexData(), and Part::PropertyPartShape::getShape().
isClosed()
bool TopoShape::isClosed () const
Definition at line 1643 of file TopoShape.cpp.
References Part::closed.
Referenced by FC_LOG_LEVEL_INIT(), and makeLoft().
isCoplanar()
bool TopoShape::isCoplanar (const TopoShape & other, double tol = -1) const
Definition at line 4098 of file TopoShape.cpp.
References findPlane(), and isNull().
isElementGenerated()
long Part::TopoShape::isElementGenerated (const Data::MappedName & name, int depth = 1) const
Referenced by FC_LOG_LEVEL_INIT().
isInfinite()
bool TopoShape::isInfinite () const
Returns true if the expansion of the shape is infinite, false otherwise.
Definition at line 4050 of file TopoShape.cpp.
References KDL::Add(), xMax, xMin, yMax, and yMin.
isLinearEdge()
bool Part::TopoShape::isLinearEdge (Base::Vector3d * dir = nullptr, Base::Vector3d * base = nullptr) const
Check if this shape is a single linear edge, works on BSplineCurve and BezierCurve.
Referenced by FC_LOG_LEVEL_INIT().
isNull()
bool TopoShape::isNull () const
Definition at line 1381 of file TopoShape.cpp.
Referenced by _getTopoShape(), PartGui::SweepWidget::accept(), PartGui::DlgRevolution::EdgeSelection::allow(), PartGui::DlgExtrusion::EdgeSelection::allow(), PartGui::SweepWidget::Private::EdgeSelection::allow(), TechDraw::DimensionAutoCorrect::autocorrectReferences(), Part::PropertyPartShape::beforeSave(), PartDesign::FeatureExtrude::buildExtrusion(), Sketcher::SketchObject::buildInternals(), TechDraw::GeometryMatcher::compareGeometry(), PartDesign::Hole::execute(), Part::MultiCommon::execute(), Part::MultiFuse::execute(), PartDesign::Loft::execute(), PartDesign::Fillet::execute(), PartDesign::Helix::execute(), Part::RuledSurface::execute(), PartDesign::Chamfer::execute(), PartDesign::Pipe::execute(), Part::Revolution::execute(), Part::Offset2D::execute(), PartDesign::Groove::execute(), PartDesign::Revolution::execute(), PartDesign::FeaturePrimitive::execute(), PartDesign::ShapeBinder::execute(), PartDesign::Transformed::execute(), Part::Sweep::execute(), Attacher::AttachEngine::extractSubShape(), Part::Extrusion::extrudeShape(), FC_LOG_LEVEL_INIT(), PartGui::DlgScale::findShapes(), PartGui::DlgExtrusion::findShapes(), PartDesign::DressUp::getAddSubShape(), Fem::Constraint::getDirection(), PartDesign::DressUp::getFaces(), Fem::Tools::getFeatureSubShape(), getLocatedShape(), PartDesign::ProfileBased::getProfileShape(), Part::PropertyShapeCache::getShape(), PartGui::getShapesFromSelection(), Sketcher::SketchObject::getSubObject(), PartDesign::ProfileBased::getTopoShapeSupportFace(), PartDesign::ProfileBased::getTopoShapeVerifiedFace(), PartDesign::ProfileBased::getUpToShapeFromLinkSubList(), isCoplanar(), Part::ExtrusionHelper::makeElementDraft(), makeRefine(), makeWires(), PartDesign::FeatureAddSub::onlyHasToRefine(), SurfaceGui::FillingPanel::open(), Part::PropertyPartShape::Restore(), Part::PropertyPartShape::Save(), CAMSimulator::CAMSim::SetBaseShape(), and shapeType().
isPlanar()
bool TopoShape::isPlanar (double tol = 1.0e-7) const
Checks whether the shape is a planar face.
Definition at line 4077 of file TopoShape.cpp.
References ArchCommands::check(), and Handle().
isPlanarFace()
bool Part::TopoShape::isPlanarFace (double tol = 1e-7) const
Check if this shape is a single planar face, works on BSplineSurface and BezierSurface.
Referenced by FC_LOG_LEVEL_INIT().
isSame()
virtual bool Part::TopoShape::isSame (const Data::ComplexGeoData & other) const virtual
Referenced by FC_LOG_LEVEL_INIT().
isValid()
bool TopoShape::isValid () const
Definition at line 1386 of file TopoShape.cpp.
Referenced by FC_LOG_LEVEL_INIT(), and fix().
linearize()
bool Part::TopoShape::linearize (LinearizeFace face, LinearizeEdge edge)
Try to simplify geometry of any linear/planar subshape to line/plane
Returns
Return true if the shape is modified
Referenced by FC_LOG_LEVEL_INIT().
locate() [1/4]
void Part::TopoShape::locate (const gp_Trsf & trsf) inline
Set a new transformation for the shape
Parameters
trsf OCCT transformation (must not have scale)
Any previous transformation of the shape is discarded before applying the input transformation
Definition at line 783 of file TopoShape.h.
locate() [2/4]
void Part::TopoShape::locate (const TopLoc_Location & loc) inline
Set a new location for the shape
Parameters
loc shape location
Any previous location of the shape is discarded before applying the input location
Definition at line 758 of file TopoShape.h.
Referenced by FC_LOG_LEVEL_INIT().
locate() [3/4]
static TopoDS_Shape& Part::TopoShape::locate (TopoDS_Shape & tds, const gp_Trsf & transfer) static
locate() [4/4]
static TopoDS_Shape& Part::TopoShape::locate (TopoDS_Shape & tds, const TopLoc_Location & loc) static
located() [1/4]
TopoShape Part::TopoShape::located (const gp_Trsf & trsf) const inline
Set a new transformation for the shape
Parameters
trsf OCCT transformation (must not have scale)
Any previous transformation of the shape is discarded before applying the input transformation.
Definition at line 794 of file TopoShape.h.
located() [2/4]
TopoShape Part::TopoShape::located (const TopLoc_Location & loc) const inline
ReturnSet a new location for the shape
Parameters
loc shape location
Returns
Return a shallow copy the shape in a new location. Any previous location of the shape is discarded before applying the input location
Definition at line 770 of file TopoShape.h.
Referenced by FC_LOG_LEVEL_INIT(), and Part::TopoShapeCache::Ancestry::stripLocation().
located() [3/4]
static TopoDS_Shape Part::TopoShape::located (const TopoDS_Shape & tds, const gp_Trsf & transfer) static
located() [4/4]
static TopoDS_Shape Part::TopoShape::located (const TopoDS_Shape & tds, const TopLoc_Location & loc) static
makeCompound()
TopoShape & TopoShape::makeCompound (const std::vector< TopoShape > & shapes, const char * op = nullptr, bool force = true)
Definition at line 3842 of file TopoShape.cpp.
References src.Mod.AddonManager.NetworkManager::count, HANDLE_NULL_INPUT, HANDLE_NULL_SHAPE, toolbit-attributes::s, and WARN_NULL_INPUT.
Referenced by makeWires().
makeElementBoolean() [1/3]
TopoShape Part::TopoShape::makeElementBoolean (const char * maker, const char * op = nullptr, double tol = -1.0) const inline
Generalized shape making with mapped element name from shape history
Parameters
maker op code from TopoShapeOpCodes
op optional string to be encoded into topo naming for indicating the operation
tol tolerance option available to some shape making algorithm
Returns
Returns the new shape with mappend element name generated from shape history using this shape as the source. The shape itself is not modified.
Definition at line 1912 of file TopoShape.h.
makeElementBoolean() [2/3]
TopoShape& Part::TopoShape::makeElementBoolean (const char * maker, const std::vector< TopoShape > & sources, const char * op = nullptr, double tol = -1.0)
Generalized shape making with mapped element name from shape history
Parameters
maker op code from OpCodes
sources list of source shapes.
op optional string to be encoded into topo naming for indicating the operation
tol tolerance option available to some shape making algorithm
Returns
The original content of this TopoShape is discarded and replaced with the new shape built by the shape maker. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by Part::MultiCommon::execute(), PartDesign::Loft::execute(), PartDesign::Groove::execute(), PartDesign::FeaturePrimitive::execute(), and FC_LOG_LEVEL_INIT().
makeElementBoolean() [3/3]
TopoShape& Part::TopoShape::makeElementBoolean (const char * maker, const TopoShape & source, const char * op = nullptr, double tol = -1.0)
Generalized shape making with mapped element name from shape history
Parameters
maker op code from TopoShapeOpCodes
source source shape.
op optional string to be encoded into topo naming for indicating the operation
tol tolerance option available to some shape making algorithm
Returns
The original content of this TopoShape is discarded and replaced with the new shape built by the shape maker. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
makeElementBSplineFace() [1/3]
TopoShape& Part::TopoShape::makeElementBSplineFace (const std::vector< TopoShape > & input, FillingStyle style = FillingStyle::stretch, bool keepBezier = false, const char * op = nullptr)
Make a face with BSpline (or Bezier) surface
Parameters
shapes input shapes of any type, but only edges inside the shape will be used.
style surface filling style.
See also
FillingStyle
Parameters
keepBezier whether to create Bezier surface if the input edge has Bezier curve.
op optional string to be encoded into topo naming for indicating the operation
Returns
The function creates a face with either BSpline or Bezier surface. The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by FC_LOG_LEVEL_INIT().
makeElementBSplineFace() [2/3]
TopoShape& Part::TopoShape::makeElementBSplineFace (const TopoShape & input, FillingStyle style = FillingStyle::stretch, bool keepBezier = false, const char * op = nullptr)
Make a face with BSpline (or Bezier) surface
Parameters
shape input shape of any type, but only edges inside the shape will be used.
style surface filling style.
See also
FillingStyle
Parameters
keepBezier whether to create Bezier surface if the input edge has Bezier curve.
op optional string to be encoded into topo naming for indicating the operation
Returns
The function creates a face with either BSpline or Bezier surface. The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
makeElementBSplineFace() [3/3]
TopoShape Part::TopoShape::makeElementBSplineFace (FillingStyle style = FillingStyle::stretch, bool keepBezier = false, const char * op = nullptr) inline
Make a face with BSpline (or Bezier) surface
Parameters
style surface filling style.
See also
FillingStyle
Parameters
keepBezier whether to create Bezier surface if the input edge has Bezier curve.
op optional string to be encoded into topo naming for indicating the operation
Returns
The function returns a new face with either BSpline or Bezier surface. The shape itself is not modified.
Definition at line 2388 of file TopoShape.h.
makeElementChamfer() [1/2]
TopoShape Part::TopoShape::makeElementChamfer (const std::vector< TopoShape > & edges, ChamferType chamferType, double radius1, double radius2, const char * op = nullptr, Flip flipDirection = Flip::none) const inline
Definition at line 2081 of file TopoShape.h.
makeElementChamfer() [2/2]
TopoShape& Part::TopoShape::makeElementChamfer (const TopoShape & source, const std::vector< TopoShape > & edges, ChamferType chamferType, double radius1, double radius2, const char * op = nullptr, Flip flipDirection = Flip::none)
Referenced by PartDesign::Chamfer::execute(), and FC_LOG_LEVEL_INIT().
makeElementCompound()
TopoShape& Part::TopoShape::makeElementCompound (const std::vector< TopoShape > & shapes, const char * op = nullptr, SingleShapeCompoundCreationPolicy policy = SingleShapeCompoundCreationPolicy::forceCompound)
Make a compound shape
Parameters
shapes input shapes
op optional string to be encoded into topo naming for indicating the operation
policy set behavior when only a single shape is given
Returns
The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by _getTopoShape(), PartDesign::FeatureExtrude::buildExtrusion(), FC_LOG_LEVEL_INIT(), PartDesign::ProfileBased::getProfileShape(), PartDesign::Loft::getSectionShape(), PartDesign::ProfileBased::getTopoShapeVerifiedFace(), PartDesign::ProfileBased::getUpToShapeFromLinkSubList(), Part::ExtrusionHelper::makeElementDraft(), and PartDesign::FeatureExtrude::makeShellFromUpToShape().
makeElementCopy() [1/2]
TopoShape Part::TopoShape::makeElementCopy (const char * op = nullptr, bool copyGeom = true, bool copyMesh = false) const inline
Make a deep copy of the shape
Parameters
op optional string to be encoded into topo naming for indicating the operation
copyGeom whether to copy internal geometry of the shape
copyMesh whether to copy internal meshes of the shape
Returns
Return a deep copy of the shape. The shape itself is not modified
Definition at line 1857 of file TopoShape.h.
makeElementCopy() [2/2]
TopoShape& Part::TopoShape::makeElementCopy (const TopoShape & source, const char * op = nullptr, bool copyGeom = true, bool copyMesh = false)
Make a deep copy of the shape
Parameters
source input shape
op optional string to be encoded into topo naming for indicating the operation
copyGeom whether to copy internal geometry of the shape
copyMesh whether to copy internal meshes of the shape
Returns
The original content of this TopoShape is discarded and replaced with a deep copy of the input shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by Part::Extrusion::extrudeShape(), FC_LOG_LEVEL_INIT(), fix(), and PartDesign::ProfileBased::getTopoShapeProfileWires().
makeElementCut() [1/2]
TopoShape& Part::TopoShape::makeElementCut (const std::vector< TopoShape > & sources, const char * op = nullptr, double tol = -1.0)
Make a boolean cut of this shape with an input shape
Parameters
source the source shape
op optional string to be encoded into topo naming for indicating the operation
tol tolerance for the fusion
Returns
The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by PartDesign::Transformed::execute(), FC_LOG_LEVEL_INIT(), and PartDesign::DressUp::getAddSubShape().
makeElementCut() [2/2]
TopoShape Part::TopoShape::makeElementCut (const TopoShape & source, const char * op = nullptr, double tol = -1.0) const inline
Make a boolean cut of this shape with an input shape
Parameters
source the source shape
op optional string to be encoded into topo naming for indicating the operation
tol tolerance for the fusion
Returns
Return the new shape. The TopoShape itself is not modified.
Definition at line 1418 of file TopoShape.h.
makeElementDraft() [1/2]
TopoShape Part::TopoShape::makeElementDraft (const std::vector< TopoShape > & faces, const gp_Dir & pullDirection, double angle, const gp_Pln & neutralPlane, bool retry = true, const char * op = nullptr) const inline
Definition at line 2232 of file TopoShape.h.
makeElementDraft() [2/2]
TopoShape& Part::TopoShape::makeElementDraft (const TopoShape & source, const std::vector< TopoShape > & faces, const gp_Dir & pullDirection, double angle, const gp_Pln & neutralPlane, bool retry = true, const char * op = nullptr)
Referenced by FC_LOG_LEVEL_INIT().
makeElementEvolve() [1/2]
TopoShape Part::TopoShape::makeElementEvolve (const TopoShape & profile, JoinType join = JoinType::arc, CoordinateSystem axeProf = CoordinateSystem::global, MakeSolid solid = MakeSolid::noSolid, Spine profOnSpine = Spine::notOn, double tol = 0.0, const char * op = nullptr) inline
Make an evolved shape using this shape as spine
An evolved shape is built from a planar spine (face or wire) and a profile (wire). The evolved shape is the unlooped sweep (pipe) of the profile along the spine. Self-intersections are removed.
Parameters
profile the profile wire, must be planar, or a line segment
join the join type (only support Arc at the moment)
axeProf determine the coordinate system for the profile
solid whether to make a solid
profOnSpine whether the profile is connect with the spine
op optional string to be encoded into topo naming for indicating the operation
Returns
Return the new shape. The TopoShape itself is not modified.
Definition at line 1580 of file TopoShape.h.
References Part::solid.
makeElementEvolve() [2/2]
TopoShape& Part::TopoShape::makeElementEvolve (const TopoShape & spine, const TopoShape & profile, JoinType join = JoinType::arc, CoordinateSystem = CoordinateSystem::global, MakeSolid solid = MakeSolid::noSolid, Spine profOnSpine = Spine::notOn, double tol = 0.0, const char * op = nullptr)
Make an evolved shape
An evolved shape is built from a planar spine (face or wire) and a profile (wire). The evolved shape is the unlooped sweep (pipe) of the profile along the spine. Self-intersections are removed. Note that the underlying OCCT method is very finicky about parameters and make throw "Unimplemented" exceptions for various types.
Parameters
spine the spine shape, must be planar face or wire
profile the profile wire, must be planar, or a line segment
join the join type (only support Arc at the moment)
axeProf determine the coordinate system for the profile
solid whether to make a solid
profOnSpine whether the profile is connect with the spine
op optional string to be encoded into topo naming for indicating the operation
Returns
The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by FC_LOG_LEVEL_INIT().
makeElementFace() [1/3]
TopoShape Part::TopoShape::makeElementFace (const char * op = nullptr, const char * maker = nullptr, const gp_Pln * plane = nullptr) const inline
Make a planar face using this shape
Parameters
op optional string to be encoded into topo naming for indicating the operation
maker optional type name of the face maker. If not given, default to "Part::FaceMakerBullseye"
plane optional plane of the face.
Returns
The function returns a new planar face made using the wire or edge inside this shape. The shape itself is not modified.
Definition at line 2330 of file TopoShape.h.
References WorkingPlane::plane.
makeElementFace() [2/3]
TopoShape& Part::TopoShape::makeElementFace (const std::vector< TopoShape > & shapes, const char * op = nullptr, const char * maker = nullptr, const gp_Pln * plane = nullptr)
Make a planar face with the input wires or edges
Parameters
shapes input shapes. Can be either edges, wires, or compound of those two types
op optional string to be encoded into topo naming for indicating the operation
maker optional type name of the face maker. If not given, default to "Part::FaceMakerBullseye"
plane optional plane of the face.
Returns
The function creates a planar face. The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by PartDesign::Loft::execute(), Part::Extrusion::extrudeShape(), FC_LOG_LEVEL_INIT(), PartDesign::ProfileBased::getTopoShapeVerifiedFace(), PartDesign::ProfileBased::getUpToShapeFromLinkSubList(), and Part::ExtrusionHelper::makeElementDraft().
makeElementFace() [3/3]
TopoShape& Part::TopoShape::makeElementFace (const TopoShape & shape, const char * op = nullptr, const char * maker = nullptr, const gp_Pln * plane = nullptr)
Make a planar face with the input wire or edge
Parameters
shape input shape. Can be either edge, wire, or compound of those two types
op optional string to be encoded into topo naming for indicating the operation
maker optional type name of the face maker. If not given, default to "Part::FaceMakerBullseye"
plane optional plane of the face.
Returns
The function creates a planar face. The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a reference so that multiple operations can be carried out for the same shape in the same line of code.
makeElementFilledFace()
TopoShape& Part::TopoShape::makeElementFilledFace (const std::vector< TopoShape > & shapes, const BRepFillingParams & params, const char * op = nullptr)
Make a non-planar filled face with boundary and/or constraint edge/wire
Parameters
shapes input shapes of any type. The function will automatically discover connected and closed edges to be used as the boundary of the the new face. Any other vertex, edge, and/or face will be used as constraints to fine tune the surface generation.
params
See also
BRepFillingParams
Parameters
op optional string to be encoded into topo naming for indicating the operation
Returns
The function creates a face with BSpline surface. The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
See also
OCCT BRepOffsetAPI_MakeFilling
Referenced by FC_LOG_LEVEL_INIT().
makeElementFillet() [1/2]
TopoShape Part::TopoShape::makeElementFillet (const std::vector< TopoShape > & edges, double radius1, double radius2, const char * op = nullptr) const inline
Definition at line 2041 of file TopoShape.h.
makeElementFillet() [2/2]
TopoShape& Part::TopoShape::makeElementFillet (const TopoShape & source, const std::vector< TopoShape > & edges, double radius1, double radius2, const char * op = nullptr)
Referenced by PartDesign::Fillet::execute(), and FC_LOG_LEVEL_INIT().
makeElementFuse() [1/2]
TopoShape& Part::TopoShape::makeElementFuse (const std::vector< TopoShape > & sources, const char * op = nullptr, double tol = -1.0)
Make a fusion of input shapes
Parameters
sources the source shapes
op optional string to be encoded into topo naming for indicating the operation
tol tolerance for the fusion
Returns
The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by PartDesign::FeatureExtrude::buildExtrusion(), PartDesign::Transformed::execute(), and FC_LOG_LEVEL_INIT().
makeElementFuse() [2/2]
TopoShape Part::TopoShape::makeElementFuse (const TopoShape & source, const char * op = nullptr, double tol = -1.0) const inline
Make a fusion of this shape and an input shape
Parameters
source the source shape
op optional string to be encoded into topo naming for indicating the operation
tol tolerance for the fusion
Returns
Return the new shape. The TopoShape itself is not modified.
Definition at line 1389 of file TopoShape.h.
makeElementGeneralFuse()
TopoShape& Part::TopoShape::makeElementGeneralFuse (const std::vector< TopoShape > & sources, std::vector< std::vector< TopoShape >> & modified, double tol = -1.0, const char * op = nullptr)
Make shape using generalized fusion and return the modified sub shapes
Parameters
sources the source shapes
modified return the modified sub shapes
tol tolerance
op optional string to be encoded into topo naming for indicating the operation
Returns
The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by FC_LOG_LEVEL_INIT().
makeElementGTransform() [1/2]
TopoShape Part::TopoShape::makeElementGTransform (const Base::Matrix4D & mat, const char * op = nullptr, CopyType copy = CopyType::noCopy) const inline
Make a new shape with transformation that may contain non-uniform scaling
Parameters
source input shape
mat transformation matrix
op optional string to be encoded into topo naming for indicating the operation
copy whether to perform deep copy of the shape. If false, the shape will still be copied if there is scaling.
Returns
Return a new shape with transformation. The shape itself is not modified
Definition at line 1821 of file TopoShape.h.
makeElementGTransform() [2/2]
TopoShape& Part::TopoShape::makeElementGTransform (const TopoShape & source, const Base::Matrix4D & mat, const char * op = nullptr, CopyType copy = CopyType::noCopy)
Make a new shape with transformation that may contain non-uniform scaling
Parameters
source input shape
mat transformation matrix
op optional string to be encoded into topo naming for indicating the operation
copy whether to perform deep copy of the shape. If false, the shape will still be copied if there is scaling.
Returns
The original content of this TopoShape is discarded and replaced with the new transformed shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by FC_LOG_LEVEL_INIT().
makeElementLoft()
TopoShape& Part::TopoShape::makeElementLoft (const std::vector< TopoShape > & sources, IsSolid isSolid, IsRuled isRuled, IsClosed isClosed = IsClosed::notClosed, Standard_Integer maxDegree = 5, const char * op = nullptr)
Make an loft that is a shell or solid passing through a set of sections in a given sequence
Parameters
sources the source shapes. The first shape is used as the spine, and the rest as sections. The sections can be of any type, but only wires are used. The first and last section may be vertex.
isSolid whether to make a solid
isRuled if isRuled then the faces generated between the edges of two consecutive section wires are ruled surfaces. If notRuled, then they are smoothed out by approximation
isClosed If isClosed, then the first section is duplicated to close the loft as the last section
maxDegree define the maximal U degree of the result surface
op optional string to be encoded into topo naming for indicating the operation
Returns
The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by FC_LOG_LEVEL_INIT().
makeElementMirror() [1/2]
TopoShape Part::TopoShape::makeElementMirror (const gp_Ax2 & ax, const char * op = nullptr) const inline
Make a mirrored shape
Parameters
source the source shape
axis the axis for mirroring
op optional string to be encoded into topo naming for indicating the operation
Returns
Return the new shape. The TopoShape itself is not modified.
Definition at line 1940 of file TopoShape.h.
makeElementMirror() [2/2]
TopoShape& Part::TopoShape::makeElementMirror (const TopoShape & source, const gp_Ax2 & axis, const char * op = nullptr)
Make a mirrored shape
Parameters
source the source shape
axis the axis for mirroring
op optional string to be encoded into topo naming for indicating the operation
Returns
The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by FC_LOG_LEVEL_INIT().
makeElementOffset() [1/2]
TopoShape& Part::TopoShape::makeElementOffset (const TopoShape & source, double offset, double tol, bool intersection = false, bool selfInter = false, short offsetMode = 0, JoinType join = JoinType::arc, FillType fill = FillType::noFill, const char * op = nullptr)
Make a 3D offset of a given shape
Parameters
source source shape
offset distance to offset
tol tolerance criterion for coincidence in generated shapes
intersection whether to check intersection in all generated parallel (OCCT document states the option is not fully implemented)
selfInter whether to eliminate self intersection (OCCT document states the option is not implemented)
offsetMode defines the construction type of parallels applied to free edges (OCCT document states the option is not implemented)
join join type. Only support JoinType::Arc and JoinType::Intersection.
fill whether to build a solid by fill the offset
op optional string to be encoded into topo naming for indicating the operation
Returns
The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by FC_LOG_LEVEL_INIT().
makeElementOffset() [2/2]
TopoShape Part::TopoShape::makeElementOffset (double offset, double tol, bool intersection = false, bool selfInter = false, short offsetMode = 0, JoinType join = JoinType::arc, FillType fill = FillType::noFill, const char * op = nullptr) const inline
Make a 3D offset of this shape
Parameters
offset distance to offset
tol tolerance criterion for coincidence in generated shapes
intersection whether to check intersection in all generated parallel (OCCT document states the option is not fully implemented)
selfInter whether to eliminate self intersection (OCCT document states the option is not implemented)
offsetMode defines the construction type of parallels applied to free edges (OCCT document states the option is not implemented)
fill whether to build a solid by fill the offset
join join type. Only support JoinType::Arc and JoinType::Intersection.
op optional string to be encoded into topo naming for indicating the operation
Returns
Return the new shape. The TopoShape itself is not modified.
Definition at line 956 of file TopoShape.h.
References Part::fill, and intersection().
makeElementOffset2D() [1/2]
TopoShape& Part::TopoShape::makeElementOffset2D (const TopoShape & source, double offset, JoinType join = JoinType::arc, FillType fill = FillType::noFill, OpenResult allowOpenResult = OpenResult::allowOpenResult, bool intersection = false, const char * op = nullptr)
Make a 2D offset of a given shape
Parameters
source source shape of edge, wire, face, or compound
offset distance to offset
allowOpenResult whether to allow open edge/wire
join join type. Only support JoinType::Arc and JoinType::Intersection.
intersection if true, then offset all non-compound shape together to deal with possible intersection after expanding the shape. If false, then offset each shape separately.
op optional string to be encoded into topo naming for indicating the operation
Returns
The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by FC_LOG_LEVEL_INIT().
makeElementOffset2D() [2/2]
TopoShape Part::TopoShape::makeElementOffset2D (double offset, JoinType join = JoinType::arc, FillType fill = FillType::noFill, OpenResult allowOpenResult = OpenResult::allowOpenResult, bool intersection = false, const char * op = nullptr) const inline
Make a 2D offset of a given shape
Parameters
source source shape of edge, wire, face, or compound
offset distance to offset
allowOpenResult whether to allow open edge/wire
join join type. Only support JoinType::Arc and JoinType::Intersection.
intersection if true, then offset all non-compound shape together to deal with possible intersection after expanding the shape. If false, then offset each shape separately.
op optional string to be encoded into topo naming for indicating the operation
Returns
Return the new shape. The TopoShape itself is not modified.
Definition at line 1016 of file TopoShape.h.
References Part::allowOpenResult, Part::fill, and intersection().
makeElementOffsetFace() [1/2]
TopoShape& Part::TopoShape::makeElementOffsetFace (const TopoShape & source, double offset, double innerOffset, JoinType join = JoinType::arc, JoinType innerJoin = JoinType::arc, const char * op = nullptr)
Make a 2D offset of face with separate control for outer and inner (hole) wires
Parameters
source source shape of any type, but only faces inside will be used
offset distance to offset for outer wires of the faces
innerOffset distance to offset for inner wires of the faces
join join type of outer wire. Only support JoinType::Arc and JoinType::Intersection.
innerJoin join type of inner wire. Only support JoinType::Arc and JoinType::Intersection.
op optional string to be encoded into topo naming for indicating the operation
Returns
The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by FC_LOG_LEVEL_INIT().
makeElementOffsetFace() [2/2]
TopoShape Part::TopoShape::makeElementOffsetFace (double offset, double innerOffset, JoinType join = JoinType::arc, JoinType innerJoin = JoinType::arc, const char * op = nullptr) const inline
Make a 2D offset of face with separate control for outer and inner (hole) wires
Parameters
source source shape of any type, but only faces inside will be used
offset distance to offset for outer wires of the faces
innerOffset distance to offset for inner wires of the faces
join join type of outer wire. Only support JoinType::Arc and JoinType::Intersection.
innerJoin join type of inner wire. Only support JoinType::Arc and JoinType::Intersection.
op optional string to be encoded into topo naming for indicating the operation
Returns
Return the new shape. The TopoShape itself is not modified.
Definition at line 1063 of file TopoShape.h.
makeElementOrderedWires()
TopoShape& Part::TopoShape::makeElementOrderedWires (const std::vector< TopoShape > & shapes, const char * op = nullptr, double tol = 0.0, TopoShapeMap * output = nullptr)
Make a compound of wires by connecting input edges in the given order
Parameters
shapes input shapes. Can be any type of shape. Edges will be extracted for building wires.
op optional string to be encoded into topo naming for indicating the operation
tol tolerance for checking the distance of two vertex to decide if two edges are connected
output optional output mapping from wire edges to input edge. Note that edges may be modified after adding to the wire, so the output edges may not be the same as the input ones.
Returns
Same as makeElementWires() but respects the order of the input edges. The function produces either a wire or a compound of wires. The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by FC_LOG_LEVEL_INIT().
makeElementPipeShell()
TopoShape& Part::TopoShape::makeElementPipeShell (const std::vector< TopoShape > & sources, const MakeSolid makeSolid, const Standard_Boolean isFrenet, TransitionMode transition = TransitionMode::Transformed, const char * op = nullptr, double tol3d = 0.0, double tolBound = 0.0, double tolAngular = 0.0)
Referenced by FC_LOG_LEVEL_INIT().
makeElementPrism() [1/2]
TopoShape Part::TopoShape::makeElementPrism (const gp_Vec & vec, const char * op = nullptr) const inline
Make a prism that is a linear sweep of this shape
Parameters
vec vector defines the sweep direction
op optional string to be encoded into topo naming for indicating the operation
Returns
Return the generated new shape. The TopoShape itself is not modified.
Definition at line 1192 of file TopoShape.h.
References SurfaceTests.TestBlendCurve::vec.
makeElementPrism() [2/2]
TopoShape& Part::TopoShape::makeElementPrism (const TopoShape & base, const gp_Vec & vec, const char * op = nullptr)
Make a prism that is a linear sweep of a basis shape
Parameters
base the basis shape
vec vector defines the sweep direction
op optional string to be encoded into topo naming for indicating the operation
Returns
The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by FC_LOG_LEVEL_INIT(), and PartDesign::FeatureExtrude::generatePrism().
makeElementPrismUntil() [1/2]
TopoShape& Part::TopoShape::makeElementPrismUntil (const TopoShape & base, const TopoShape & profile, const TopoShape & supportFace, const TopoShape & upToFace, const gp_Dir & direction, PrismMode mode, Standard_Boolean checkLimits = Standard_True, const char * op = nullptr)
Make a prism that is either depression or protrusion of a profile shape up to a given face
Parameters
base the base shape
profile profile shape used for sweeping to make the prism
supportFace optional face serves to determining the type of operation. If it is inside the basis shape, a local operation such as glueing can be performed.
upToFace sweep the profile up until this give face.
direction the direction to sweep the profile
mode defines what shape to return.
See also
PrismMode
Parameters
checkLimits If true, then remove limit (boundary) of up to face. If false, then the generate prism may go beyond the boundary of the up to face.
op optional string to be encoded into topo naming for indicating the operation
Returns
The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by PartDesign::FeatureExtrude::buildExtrusion(), and FC_LOG_LEVEL_INIT().
makeElementPrismUntil() [2/2]
TopoShape Part::TopoShape::makeElementPrismUntil (const TopoShape & profile, const TopoShape & supportFace, const TopoShape & upToFace, const gp_Dir & direction, PrismMode mode, Standard_Boolean checkLimits = Standard_True, const char * op = nullptr) const inline
Make a prism based on this shape that is either depression or protrusion of a profile shape up to a given face
Parameters
profile profile shape used for sweeping to make the prism
supportFace optional face serves to determining the type of operation. If it is inside the basis shape, a local operation such as glueing can be performed.
upToFace sweep the profile up until this give face.
direction the direction to sweep the profile
mode defines what shape to return.
See also
PrismMode
Parameters
checkLimits If true, then remove limit (boundary) of up to face. If false, then the generate prism may go beyond the boundary of the up to face.
op optional string to be encoded into topo naming for indicating the operation
Returns
Return the generated new shape. The TopoShape itself is not modified.
Definition at line 1252 of file TopoShape.h.
makeElementRefine() [1/2]
TopoShape Part::TopoShape::makeElementRefine (const char * op = nullptr, RefineFail no_fail = RefineFail::throwException) const inline
Refine the input shape by merging faces/edges that share the same geometry
Parameters
source input shape
op optional string to be encoded into topo naming for indicating the operation
no_fail if throwException, throw exception if failed to refine. Or else, if shapeUntouched the shape remains untouched if failed.
Returns
Return a refined shape. The shape itself is not modified
Definition at line 845 of file TopoShape.h.
makeElementRefine() [2/2]
TopoShape& Part::TopoShape::makeElementRefine (const TopoShape & shape, const char * op = nullptr, RefineFail no_fail = RefineFail::throwException)
Refine the input shape by merging faces/edges that share the same geometry
Parameters
shape input shape
op optional string to be encoded into topo naming for indicating the operation
no_fail if throwException, throw exception if failed to refine. Or else, if shapeUntouched the shape remains untouched if failed.
Returns
The original content of this TopoShape is discarded and replaced with the refined shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by Part::Boolean::execute(), FC_LOG_LEVEL_INIT(), PartDesign::Boolean::refineShapeIfActive(), PartDesign::FeatureAddSub::refineShapeIfActive(), and PartDesign::Transformed::refineShapeIfActive().
makeElementRevolution() [1/2]
TopoShape& Part::TopoShape::makeElementRevolution (const gp_Ax1 & axis, const TopoDS_Shape & profile, const TopoDS_Face & supportface, const TopoDS_Face & uptoface, const char * face_maker = nullptr, RevolMode Mode = RevolMode::None, Standard_Boolean Modify = Standard_True, const char * op = nullptr) const inline
Make revolved shell around a basis shape
Parameters
axis the revolving axis
face_maker optional type name of the the maker used to make a face from basis shape
supportface the bottom face for the revolution, or null
uptoface the upper limit face for the revolution, or null
Mode the opencascade defined modes
Modify if opencascade should modify existing shapes
op optional string to be encoded into topo naming for indicating the operation
Returns
Return the generated new shape. The TopoShape itself is not modified.
Definition at line 1150 of file TopoShape.h.
makeElementRevolution() [2/2]
TopoShape& Part::TopoShape::makeElementRevolution (const TopoShape & _base, const TopoDS_Shape & profile, const gp_Ax1 & axis, const TopoDS_Face & supportface, const TopoDS_Face & uptoface, const char * face_maker = nullptr, RevolMode Mode = RevolMode::None, Standard_Boolean Modify = Standard_True, const char * op = nullptr)
Make revolved shell around a basis shape
Parameters
base the basis shape (solid)
profile the shape to be revolved
axis the revolving axis
face_maker optional type name of the the maker used to make a face from basis shape
supportface the bottom face for the revolution, or null
uptoface the upper limit face for the revolution, or null
Mode the opencascade defined modes
Modify if opencascade should modify existing shapes
op optional string to be encoded into topo naming for indicating the operation
Returns
Return the generated new shape. The TopoShape itself is not modified.
Referenced by FC_LOG_LEVEL_INIT(), and PartDesign::Revolution::generateRevolution().
makeElementRevolve() [1/2]
TopoShape Part::TopoShape::makeElementRevolve (const gp_Ax1 & axis, double d, const char * face_maker = nullptr, const char * op = nullptr) const inline
Make revolved shell around a basis shape
Parameters
axis the revolving axis
d rotation angle in degree
face_maker optional type name of the the maker used to make a face from basis shape
op optional string to be encoded into topo naming for indicating the operation
Returns
Return the generated new shape. The TopoShape itself is not modified.
Definition at line 1104 of file TopoShape.h.
makeElementRevolve() [2/2]
TopoShape& Part::TopoShape::makeElementRevolve (const TopoShape & base, const gp_Ax1 & axis, double d, const char * face_maker = 0, const char * op = nullptr)
Make revolved shell around a basis shape
Parameters
base the base shape
axis the revolving axis
d rotation angle in degree
face_maker optional type name of the the maker used to make a face from basis shape
op optional string to be encoded into topo naming for indicating the operation
Returns
The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by Part::Revolution::execute(), FC_LOG_LEVEL_INIT(), and PartDesign::Revolution::generateRevolution().
makeElementRuledSurface()
TopoShape& Part::TopoShape::makeElementRuledSurface (const std::vector< TopoShape > & source, int orientation = 0, const char * op = nullptr)
Make a ruled surface
Parameters
sources the source shapes, each of which must contain either a single edge or a single wire.
orientation A Qt::Orientation, where Qt::Horizontal is 1 and Qt::Vertical is 2.
op optional string to be encoded into topo naming for indicating the operation
Returns
The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by Part::RuledSurface::execute(), and FC_LOG_LEVEL_INIT().
makeElementShape() [1/4]
TopoShape Part::TopoShape::makeElementShape (BRepBuilderAPI_MakeShape & mkShape, const char * op = nullptr) const inline
Generic shape making with mapped element name from shape history
Parameters
mkShape OCCT shape maker.
op optional string to be encoded into topo naming for indicating the operation
Returns
Returns the new shape built by the shape maker with mappend element name generated using this shape as the source. The shape itself is not modified.
Definition at line 2537 of file TopoShape.h.
makeElementShape() [2/4]
TopoShape& Part::TopoShape::makeElementShape (BRepBuilderAPI_MakeShape & mkShape, const std::vector< TopoShape > & sources, const char * op = nullptr)
Generic shape making with mapped element name from shape history
Parameters
mkShape OCCT shape maker.
sources list of source shapes.
op optional string to be encoded into topo naming for indicating the operation
Returns
The original content of this TopoShape is discarded and replaced with the new shape built by the shape maker. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by Part::Boolean::execute(), Part::Fillet::execute(), Part::Chamfer::execute(), and FC_LOG_LEVEL_INIT().
makeElementShape() [3/4]
TopoShape& Part::TopoShape::makeElementShape (BRepBuilderAPI_MakeShape & mkShape, const TopoShape & source, const char * op = nullptr)
Generic shape making with mapped element name from shape history
Parameters
mkShape OCCT shape maker.
source source shape.
op optional string to be encoded into topo naming for indicating the operation
Returns
The original content of this TopoShape is discarded and replaced with the new shape built by the shape maker. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
makeElementShape() [4/4]
TopoShape& Part::TopoShape::makeElementShape (BRepFeat_MakePrism & mkShape, const std::vector< TopoShape > & sources, const TopoShape & uptoface, const char * op)
Specialized shape making for BRepBuilderAPI_MakePrism with mapped element name
Parameters
mkShape OCCT shape maker.
sources list of source shapes.
op optional string to be encoded into topo naming for indicating the operation
Returns
The original content of this TopoShape is discarded and replaced with the new shape built by the shape maker. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
makeElementShell()
TopoShape& Part::TopoShape::makeElementShell (bool silent = true, const char * op = nullptr)
Referenced by FC_LOG_LEVEL_INIT().
makeElementShellFromWires() [1/2]
TopoShape& Part::TopoShape::makeElementShellFromWires (bool silent = true, const char * op = nullptr) inline
Definition at line 2274 of file TopoShape.h.
makeElementShellFromWires() [2/2]
TopoShape& Part::TopoShape::makeElementShellFromWires (const std::vector< TopoShape > & wires, bool silent = true, const char * op = nullptr)
Referenced by FC_LOG_LEVEL_INIT().
makeElementSlice() [1/2]
TopoShape Part::TopoShape::makeElementSlice (const Base::Vector3d & dir, double distance, const char * op = nullptr) const inline
Make a cross section slice
Parameters
source the source shape
dir direction of the normal of the section plane
distance distance to move the section plane
op optional string to be encoded into topo naming for indicating the operation
Returns
Return the new shape. The TopoShape itself is not modified.
Definition at line 1972 of file TopoShape.h.
makeElementSlice() [2/2]
TopoShape& Part::TopoShape::makeElementSlice (const TopoShape & source, const Base::Vector3d & dir, double distance, const char * op = nullptr)
Make a cross section slice
Parameters
source the source shape
dir direction of the normal of the section plane
distance distance to move the section plane
op optional string to be encoded into topo naming for indicating the operation
Returns
The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by FC_LOG_LEVEL_INIT().
makeElementSlices() [1/2]
TopoShape Part::TopoShape::makeElementSlices (const Base::Vector3d & dir, const std::vector< double > & distances, const char * op = nullptr) const inline
Make multiple cross section slices
Parameters
source the source shape
dir direction of the normal of the section plane
distances distances to move the section plane for making slices
op optional string to be encoded into topo naming for indicating the operation
Returns
Return the new shape. The TopoShape itself is not modified.
Definition at line 2004 of file TopoShape.h.
makeElementSlices() [2/2]
TopoShape& Part::TopoShape::makeElementSlices (const TopoShape & source, const Base::Vector3d & dir, const std::vector< double > & distances, const char * op = nullptr)
Make multiple cross section slices
Parameters
source the source shape
dir direction of the normal of the section plane
distances distances to move the section plane for making slices
op optional string to be encoded into topo naming for indicating the operation
Returns
The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by FC_LOG_LEVEL_INIT().
makeElementSolid() [1/2]
TopoShape Part::TopoShape::makeElementSolid (const char * op = nullptr) const inline
Make a solid using this shape
Parameters
op optional string to be encoded into topo naming for indicating the operation
Returns
The function returns a new solid using the shell or CompSolid inside this shape. The shape itself is not modified.
Definition at line 2490 of file TopoShape.h.
makeElementSolid() [2/2]
TopoShape& Part::TopoShape::makeElementSolid (const TopoShape & shape, const char * op = nullptr)
Make a solid using shells or CompSolid
Parameters
shapes input shapes of either shells or CompSolid.
op optional string to be encoded into topo naming for indicating the operation
Returns
The function produces a solid. The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code. Make a solid using shells or CompSolid
Parameters
shape input shape of either a shell, a compound of shells, or a CompSolid.
op optional string to be encoded into topo naming for indicating the operation
Returns
The function produces a solid. The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by FC_LOG_LEVEL_INIT().
makeElementThickSolid() [1/2]
TopoShape Part::TopoShape::makeElementThickSolid (const std::vector< TopoShape > & faces, double offset, double tol, bool intersection = false, bool selfInter = false, short offsetMode = 0, JoinType join = JoinType::arc, const char * op = nullptr) const inline
Make a hollowed solid by removing some faces from a given solid
Parameters
faces list of faces to remove, must be sub shape of the input shape
offset thickness of the walls
tol tolerance criterion for coincidence in generated shapes
intersection whether to check intersection in all generated parallel (OCCT document states the option is not fully implemented)
selfInter whether to eliminate self intersection (OCCT document states the option is not implemented)
offsetMode defines the construction type of parallels applied to free edges (OCCT document states the option is not implemented)
join join type. Only support JoinType::Arc and JoinType::Intersection.
op optional string to be encoded into topo naming for indicating the operation
Returns
Return the generated new shape. The TopoShape itself is not modified.
Definition at line 902 of file TopoShape.h.
References intersection().
makeElementThickSolid() [2/2]
TopoShape& Part::TopoShape::makeElementThickSolid (const TopoShape & shape, const std::vector< TopoShape > & faces, double offset, double tol, bool intersection = false, bool selfInter = false, short offsetMode = 0, JoinType join = JoinType::arc, const char * op = nullptr)
Make a hollowed solid by removing some faces from a given solid
Parameters
shape input shape
faces list of faces to remove, must be sub shape of the input shape
offset thickness of the walls
tol tolerance criterion for coincidence in generated shapes
intersection whether to check intersection in all generated parallel.
selfInter whether to eliminate self intersection.
offsetMode defines the construction type of parallels applied to free edges
join join type. Only support JoinType::Arc and JoinType::Intersection.
op optional string to be encoded into topo naming for indicating the operation
Returns
The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by FC_LOG_LEVEL_INIT().
makeElementTransform() [1/4]
TopoShape Part::TopoShape::makeElementTransform (const Base::Matrix4D & mat, const char * op = nullptr, CheckScale checkScale = CheckScale::noScaleCheck, CopyType copy = CopyType::noCopy) inline
Make a new shape with transformation
Parameters
source input shape
mat transformation matrix
op optional string to be encoded into topo naming for indicating the operation
checkScale whether to check if the transformation matrix contains scaling factor.
copy whether to perform deep copy of the shape. If noCopy, and checkScale, then the shape will be copied if there is scaling.
Returns
Return a new shape with transformation. The shape itself is not modified
Definition at line 2157 of file TopoShape.h.
References Part::checkScale.
makeElementTransform() [2/4]
TopoShape Part::TopoShape::makeElementTransform (const gp_Trsf & trsf, const char * op = nullptr, CopyType copy = CopyType::noCopy) inline
Make a new shape with transformation
Parameters
source input shape
trsf OCCT transformation matrix
op optional string to be encoded into topo naming for indicating the operation
copy whether to perform deep copy of the shape.
Returns
Return a new shape with transformation. The shape itself is not modified
Definition at line 2195 of file TopoShape.h.
makeElementTransform() [3/4]
TopoShape& Part::TopoShape::makeElementTransform (const TopoShape & shape, const gp_Trsf & trsf, const char * op = nullptr, CopyType copy = CopyType::noCopy)
Make a new shape with transformation
Parameters
source input shape
trsf OCCT transformation matrix
op optional string to be encoded into topo naming for indicating the operation
copy whether to perform deep copy of the shape.
Returns
The original content of this TopoShape is discarded and replaced with the new transformed shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
makeElementTransform() [4/4]
TopoShape& Part::TopoShape::makeElementTransform (const TopoShape & source, const Base::Matrix4D & mat, const char * op = nullptr, CheckScale checkScale = CheckScale::noScaleCheck, CopyType copy = CopyType::noCopy) inline
Make a new shape with transformation
Parameters
source input shape
mat transformation matrix
op optional string to be encoded into topo naming for indicating the operation
checkScale whether to check if the transformation matrix contains scaling factor.
copy whether to perform deep copy of the shape. If noCopy, and checkScale, then the shape will be copied if there is scaling.
Returns
The original content of this TopoShape is discarded and replaced with the new transformed shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Definition at line 2132 of file TopoShape.h.
References Part::checkScale.
Referenced by _getTopoShape(), PartDesign::Transformed::execute(), Part::Extrusion::extrudeShape(), and FC_LOG_LEVEL_INIT().
makeElementWires() [1/3]
TopoShape Part::TopoShape::makeElementWires (const char * op = nullptr, double tol = 0.0, ConnectionPolicy policy = ConnectionPolicy::mergeWithTolerance, TopoShapeMap * output = nullptr) const inline
Make a wire or compound of wires with the edges inside the this shape
Parameters
op optional string to be encoded into topo naming for indicating the operation
keepOrder whether to respect the order of the input edges
tol tolerance for checking the distance of two vertex to decide if two edges are connected
shared if true, then only connect edges if they shared the same vertex, or else use tol to check for connection.
output optional output mapping from wire edges to input edge. Note that edges may be modified after adding to the wire, so the output edges may not be the same as the input ones.
Returns
The function returns a new shape of either a single wire or a compound of wires. The shape itself is not modified.
Definition at line 1782 of file TopoShape.h.
makeElementWires() [2/3]
TopoShape& Part::TopoShape::makeElementWires (const std::vector< TopoShape > & shapes, const char * op = nullptr, double tol = 0.0, ConnectionPolicy policy = ConnectionPolicy::mergeWithTolerance, TopoShapeMap * output = nullptr)
Make a compound of wires by connecting input edges
Parameters
shapes input shapes. Can be any type of shape. Edges will be extracted for building wires.
op optional string to be encoded into topo naming for indicating the operation
keepOrder whether to respect the order of the input edges
tol tolerance for checking the distance of two vertex to decide if two edges are connected
shared if true, then only connect edges if they shared the same vertex, or else use tol to check for connection.
output optional output mapping from wire edges to input edge. Note that edges may be modified after adding to the wire, so the output edges may not be the same as the input ones.
Returns
The function produces either a wire or a compound of wires. The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by PartDesign::FeatureExtrude::buildExtrusion(), FC_LOG_LEVEL_INIT(), PartDesign::Loft::getSectionShape(), and PartDesign::ProfileBased::getTopoShapeVerifiedFace().
makeElementWires() [3/3]
TopoShape& Part::TopoShape::makeElementWires (const TopoShape & shape, const char * op = nullptr, double tol = 0.0, ConnectionPolicy policy = ConnectionPolicy::mergeWithTolerance, TopoShapeMap * output = nullptr)
Make a compound of wires by connecting input edges
Parameters
shape input shape. Can be any type of shape. Edges will be extracted for building wires.
op optional string to be encoded into topo naming for indicating the operation
keepOrder whether to respect the order of the input edges
tol tolerance for checking the distance of two vertex to decide if two edges are connected
policy if requireSharedVertex, then only connect edges if they shared the same vertex. If mergeWithTolerance use tol to check for connection.
output optional output mapping from wire edges to input edge. Note that edges may be modified after adding to the wire, so the output edges may not be the same as the input ones.
Returns
The function produces either a wire or a compound of wires. The original content of this TopoShape is discarded and replaced with the new shape. The function returns the TopoShape itself as a reference so that multiple operations can be carried out for the same shape in the same line of code.
makeFace() [1/3]
TopoShape Part::TopoShape::makeFace (const char * op = nullptr, const char * maker = nullptr) const inline
Definition at line 668 of file TopoShape.h.
makeFace() [2/3]
TopoShape & TopoShape::makeFace (const std::vector< TopoShape > & shapes, const char * op = nullptr, const char * maker = nullptr)
Definition at line 3884 of file TopoShape.cpp.
References Part::FaceMaker::ConstructFromType(), and toolbit-attributes::s.
Referenced by makeFace().
makeFace() [3/3]
TopoShape & TopoShape::makeFace (const TopoShape & shape, const char * op = nullptr, const char * maker = nullptr)
Definition at line 3873 of file TopoShape.cpp.
References getShape(), makeFace(), and shapeType().
makeGTransform() [1/2]
TopoShape Part::TopoShape::makeGTransform (const Base::Matrix4D & mat, const char * op = nullptr, bool copy = false) const inline
Definition at line 813 of file TopoShape.h.
makeGTransform() [2/2]
TopoShape & TopoShape::makeGTransform (const TopoShape & shape, const Base::Matrix4D & mat, const char * op = nullptr, bool copy = false)
Definition at line 4160 of file TopoShape.cpp.
References transformGShape().
Referenced by _makeTransform(), and transformGeometry().
makeHelix()
TopoDS_Shape TopoShape::makeHelix (Standard_Real pitch, Standard_Real height, Standard_Real radius, Standard_Real angle = 0, Standard_Boolean left = Standard_False, Standard_Boolean style = Standard_False) const
Definition at line 2142 of file TopoShape.cpp.
References KDL::cos(), Handle(), M_PI, Path.Post.scripts.opensbp_post::move(), KDL::sqrt(), Base::toRadians(), buildPsets::u, and TestSpreadsheet::v.
makeLoft()
TopoDS_Shape TopoShape::makeLoft (const TopTools_ListOfShape & profiles, Standard_Boolean isSolid, Standard_Boolean isRuled, Standard_Boolean isClosed = Standard_False, Standard_Integer maxDegree = 5) const
Definition at line 2402 of file TopoShape.cpp.
References Base::Console(), isClosed(), Path.Base.Util::isSolid(), and Base::ConsoleSingleton::Message().
makeLongHelix()
TopoDS_Shape TopoShape::makeLongHelix (Standard_Real pitch, Standard_Real height, Standard_Real radius, Standard_Real angle = 0, Standard_Boolean left = Standard_False) const
Definition at line 2206 of file TopoShape.cpp.
References KDL::cos(), Handle(), SplineSurface::i, M_PI, Path.Post.scripts.opensbp_post::move(), KDL::sqrt(), Base::toRadians(), buildPsets::u, and TestSpreadsheet::v.
makeOffset2D()
TopoDS_Shape TopoShape::makeOffset2D (double offset, short joinType = 0, bool fill = false, bool allowOpenResult = false, bool intersection = false) const
Definition at line 2643 of file TopoShape.cpp.
References Part::BRepOffsetAPI_MakeOffsetFix::AddWire(), Part::FaceMaker::addWire(), Part::allowOpenResult, Part::FaceMaker::Build(), Part::fill, Handle(), SplineSurface::i, intersection(), Path.Post.scripts.opensbp_post::move(), ClipperLib::Orientation(), Part::BRepOffsetAPI_MakeOffsetFix::Perform(), Part::BRepOffsetAPI_MakeOffsetFix::Replace(), result, Part::FaceMakerBullseye::setPlane(), Part::BRepOffsetAPI_MakeOffsetFix::Shape(), Path.Geom::Tolerance, TopoShape(), draftgeoutils.general::v1(), and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by Part::Offset2D::execute().
makeOffsetShape()
TopoDS_Shape TopoShape::makeOffsetShape (double offset, double tol, bool intersection = false, bool selfInter = false, short offsetMode = 0, short join = 0, bool fill = false) const
Definition at line 2519 of file TopoShape.cpp.
References Part::fill, intersection(), and Path.Op.Util::offsetWire().
makePipe()
TopoDS_Shape TopoShape::makePipe (const TopoDS_Shape & profile) const
Sweeping
Definition at line 1938 of file TopoShape.cpp.
makePipeShell()
TopoDS_Shape TopoShape::makePipeShell (const TopTools_ListOfShape & profiles, const Standard_Boolean make_solid, const Standard_Boolean isFrenet = Standard_False, int transition = 0) const
Definition at line 1950 of file TopoShape.cpp.
makePrism()
TopoDS_Shape TopoShape::makePrism (const gp_Vec & vec) const
Definition at line 2474 of file TopoShape.cpp.
References SurfaceTests.TestBlendCurve::vec.
makeRefine() [1/2]
TopoShape Part::TopoShape::makeRefine (const char * op = nullptr, RefineFail no_fail = RefineFail::throwException) const inline
Definition at line 856 of file TopoShape.h.
makeRefine() [2/2]
TopoShape & TopoShape::makeRefine (const TopoShape & shape, const char * op = nullptr, RefineFail no_fail = RefineFail::throwException)
Definition at line 3904 of file TopoShape.cpp.
References getShape(), HANDLE_NULL_SHAPE, isNull(), and Part::throwException.
makeShapeWithElementMap()
TopoShape& Part::TopoShape::makeShapeWithElementMap (const TopoDS_Shape & shape, const Mapper & mapper, const std::vector< TopoShape > & sources, const char * op = nullptr)
Core function to generate mapped element names from shape history
Parameters
shape the new shape
mapper for mapping input shapes to generated/modified shapes
sources list of source shapes.
op optional string to be encoded into topo naming for indicating the operation
Returns
The original content of this TopoShape is discarded and replaced with the given new shape. The function returns the TopoShape itself as a self reference so that multiple operations can be carried out for the same shape in the same line of code.
Referenced by Part::MultiFuse::execute(), FC_LOG_LEVEL_INIT(), and fix().
makeShell()
TopoDS_Shape TopoShape::makeShell (const TopoDS_Shape & input) const
TopoShape::makeShell If the input shape is a compound with faces not being part of a shell it tries to make a shell. If this operation fails or if the input shape is not a compound or a compound with not only faces the input shape is returned.
Returns
Shell or passed shape
Definition at line 3698 of file TopoShape.cpp.
References ArchCommands::check(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf::shell.
Referenced by common(), cut(), and fuse().
makeSpiralHelix()
TopoDS_Shape TopoShape::makeSpiralHelix (Standard_Real radiusbottom, Standard_Real radiustop, Standard_Real height, Standard_Real nbturns = 1, Standard_Real breakperiod = 1, Standard_Boolean left = Standard_False) const
Definition at line 2286 of file TopoShape.cpp.
References SCL.SimpleDataTypes::e, Handle(), SplineSurface::i, M_PI, and Path.Post.scripts.opensbp_post::move().
Referenced by PartDesign::Helix::generateHelixPath().
makeSweep()
TopoDS_Shape TopoShape::makeSweep (const TopoDS_Shape & profile, double tol, int fillMode) const
Definition at line 2061 of file TopoShape.cpp.
References Handle().
makeThickSolid()
TopoDS_Shape TopoShape::makeThickSolid (const TopTools_ListOfShape & remFace, double offset, double tol, bool intersection = false, bool selfInter = false, short offsetMode = 0, short join = 0) const
Definition at line 2961 of file TopoShape.cpp.
References intersection().
makeThread()
TopoDS_Shape TopoShape::makeThread (Standard_Real pitch, Standard_Real depth, Standard_Real height, Standard_Real radius) const
Definition at line 2340 of file TopoShape.cpp.
References Handle(), and M_PI.
makeTorus()
TopoDS_Shape TopoShape::makeTorus (Standard_Real radius1, Standard_Real radius2, Standard_Real angle1, Standard_Real angle2, Standard_Real angle3, Standard_Boolean isSolid = Standard_True) const
Definition at line 2110 of file TopoShape.cpp.
References Path.Base.Util::isSolid(), and RobotExample::pos.
Referenced by PartDesign::Torus::execute(), and Part::Torus::execute().
makeTransform() [1/4]
TopoShape Part::TopoShape::makeTransform (const Base::Matrix4D & mat, const char * op = nullptr, bool checkScale = false, bool copy = false) const inline
Definition at line 687 of file TopoShape.h.
References Part::checkScale.
makeTransform() [2/4]
TopoShape Part::TopoShape::makeTransform (const gp_Trsf & trsf, const char * op = nullptr, bool copy = false) const inline
Definition at line 699 of file TopoShape.h.
makeTransform() [3/4]
TopoShape& Part::TopoShape::makeTransform (const TopoShape & shape, const Base::Matrix4D & mat, const char * op = nullptr, bool checkScale = false, bool copy = false) inline
Definition at line 678 of file TopoShape.h.
References Part::checkScale.
Referenced by _makeTransform().
makeTransform() [4/4]
TopoShape & TopoShape::makeTransform (const TopoShape & shape, const gp_Trsf & trsf, const char * op = nullptr, bool copy = false)
Definition at line 4131 of file TopoShape.cpp.
References ClipperLib::Abs(), getShape(), and Data::ComplexGeoData::Tag.
makeTube()
TopoDS_Shape TopoShape::makeTube (double radius, double tol, int cont, int maxdeg, int maxsegm) const
Definition at line 1998 of file TopoShape.cpp.
References Handle(), M_PI, theRadius, and draftgeoutils.general::v1().
makeWires() [1/2]
TopoShape Part::TopoShape::makeWires (const char * op = nullptr, bool fix = false, double tol = 0.0) const inline
Definition at line 659 of file TopoShape.h.
makeWires() [2/2]
TopoShape & TopoShape::makeWires (const TopoShape & shape, const char * op = nullptr, bool fix = false, double tol = 0.0)
Definition at line 3771 of file TopoShape.cpp.
References fix(), getShape(), HANDLE_NULL_INPUT, SplineSurface::i, isNull(), makeCompound(), and Mesh2Shape::wires.
mapSubElement() [1/2]
void Part::TopoShape::mapSubElement (const std::vector< TopoShape > & shapes, const char * op = nullptr)
mapSubElement() [2/2]
void Part::TopoShape::mapSubElement (const TopoShape & other, const char * op = nullptr, bool forceHasher = false)
Referenced by FC_LOG_LEVEL_INIT(), Part::findAllFacesCutBy(), Part::ExtrusionHelper::makeElementDraft(), and Part::PropertyPartShape::setPyObject().
mapSubElementsTo()
void Part::TopoShape::mapSubElementsTo (std::vector< TopoShape > & shapes, const char * op = nullptr) const
Referenced by FC_LOG_LEVEL_INIT().
mirror()
TopoDS_Shape TopoShape::mirror (const gp_Ax2 & ax2) const
Definition at line 3019 of file TopoShape.cpp.
move() [1/4]
void Part::TopoShape::move (const gp_Trsf & trsf) inline
Move and/or rotate the shape
Parameters
trsf OCCT transformation (must not have scale)
The transformation is applied in addition to any current transformation of the shape
Definition at line 735 of file TopoShape.h.
References Path.Post.scripts.opensbp_post::move().
move() [2/4]
void Part::TopoShape::move (const TopLoc_Location & loc) inline
Move the shape to a new location
Parameters
loc location
The location is applied in addition to any current transformation of the shape
Definition at line 710 of file TopoShape.h.
Referenced by PartDesign::ProfileBased::addOffsetToFace(), PartDesign::FeatureExtrude::buildExtrusion(), PartDesign::Hole::execute(), PartDesign::Loft::execute(), PartDesign::Helix::execute(), PartDesign::Revolution::execute(), PartDesign::Groove::execute(), FC_LOG_LEVEL_INIT(), PartDesign::FeatureExtrude::generatePrism(), PartDesign::Revolution::generateRevolution(), and PartDesign::DressUp::getAddSubShape().
move() [3/4]
static TopoDS_Shape& Part::TopoShape::move (TopoDS_Shape & tds, const gp_Trsf & transfer) static
move() [4/4]
static TopoDS_Shape& Part::TopoShape::move (TopoDS_Shape & tds, const TopLoc_Location & loc) static
moved() [1/4]
TopoShape Part::TopoShape::moved (const gp_Trsf & trsf) const inline
Return a new transformed shape
Parameters
trsf OCCT transformation (must not have scale)
Returns
Return a shallow copy of the shape transformed to the new location that is applied in addition to any current transformation of the shape
Definition at line 747 of file TopoShape.h.
moved() [2/4]
TopoShape Part::TopoShape::moved (const TopLoc_Location & loc) const inline
Return a new shape that is moved to a new location
Parameters
loc location
Returns
Return a shallow copy of the shape moved to the new location that is applied in addition to any current transformation of the shape
Definition at line 722 of file TopoShape.h.
Referenced by PartDesign::FeaturePrimitive::execute(), FC_LOG_LEVEL_INIT(), Part::TopoShapeCache::Ancestry::find(), and Part::TopoShapeCache::findAncestor().
moved() [3/4]
static TopoDS_Shape Part::TopoShape::moved (const TopoDS_Shape & tds, const gp_Trsf & transfer) static
moved() [4/4]
static TopoDS_Shape Part::TopoShape::moved (const TopoDS_Shape & tds, const TopLoc_Location & loc) static
oldFuse()
TopoDS_Shape TopoShape::oldFuse (TopoDS_Shape shape) const
Definition at line 1812 of file TopoShape.cpp.
operator=()
void Part::TopoShape::operator= (const TopoShape &)
Referenced by FC_LOG_LEVEL_INIT().
operator==()
bool Part::TopoShape::operator== (const TopoShape & other) const inline
Definition at line 305 of file TopoShape.h.
read()
void TopoShape::read (const char * FileName)
Definition at line 654 of file TopoShape.cpp.
References Base::FileInfo::filePath(), Base::FileInfo::hasExtension(), importBrep(), importIges(), importStep(), and Base::FileInfo::isReadable().
Referenced by Part::CurveNet::execute().
removeElementShape() [1/2]
TopoShape Part::TopoShape::removeElementShape (const std::vector< TopoShape > & s) const inline
Definition at line 1341 of file TopoShape.h.
References toolbit-attributes::s.
removeElementShape() [2/2]
TopoShape& Part::TopoShape::removeElementShape (const TopoShape & source, const std::vector< TopoShape > & s)
Referenced by FC_LOG_LEVEL_INIT().
removeInternalWires()
bool TopoShape::removeInternalWires (double minArea)
Definition at line 3159 of file TopoShape.cpp.
References fix().
removeShape()
TopoDS_Shape TopoShape::removeShape (const std::vector< TopoDS_Shape > & s) const
Definition at line 3045 of file TopoShape.cpp.
References toolbit-attributes::s.
removeSplitter()
TopoDS_Shape TopoShape::removeSplitter () const
Definition at line 3168 of file TopoShape.cpp.
References ModelRefine::FaceUniter::getShell(), ModelRefine::FaceUniter::isModified(), Path.Post.scripts.opensbp_post::move(), ModelRefine::FaceUniter::process(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf::shell, and Part::solid.
Referenced by Part::Refine::execute().
replaceElementShape() [1/2]
TopoShape Part::TopoShape::replaceElementShape (const std::vector< std::pair< TopoShape, TopoShape >> & s) const inline
Definition at line 1319 of file TopoShape.h.
References toolbit-attributes::s.
replaceElementShape() [2/2]
TopoShape& Part::TopoShape::replaceElementShape (const TopoShape & source, const std::vector< std::pair< TopoShape, TopoShape >> & s)
Referenced by FC_LOG_LEVEL_INIT().
replaceShape()
TopoDS_Shape TopoShape::replaceShape (const std::vector< std::pair< TopoDS_Shape, TopoDS_Shape >> & s) const
Definition at line 3036 of file TopoShape.cpp.
References toolbit-attributes::s.
resetElementMap()
Data::ElementMapPtr Part::TopoShape::resetElementMap (Data::ElementMapPtr elementMap = Data::ElementMapPtr()) override virtual
Reset/swap the element map
Parameters
elementMap optional new element map
Returns
Returns the existing element map.
Reimplemented from Data::ComplexGeoData.
Referenced by _getTopoShape(), Sketcher::SketchObject::buildShape(), FC_LOG_LEVEL_INIT(), Sketcher::SketchObject::getEdge(), and Sketcher::SketchObject::getSubObject().
Restore()
void TopoShape::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from Data::ComplexGeoData.
Definition at line 1208 of file TopoShape.cpp.
References TechDrawTools.TaskFillTemplateFields::reader, and Data::ComplexGeoData::Restore().
Referenced by Part::PropertyPartShape::Restore().
RestoreDocFile()
void TopoShape::RestoreDocFile (Base::Reader &) override virtual
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data. Again you have to apply for the call of this method in the Restore() call:
void PropertyMeshKernel::Restore(Base::XMLReader &reader)
{
  reader.readElement("Mesh");
  std::string file (reader.getAttribute("file") );
  if(file == "")
  {
    // read XML
    MeshCore::MeshDocXML restorer(*_pcMesh);
    restorer.Restore(reader);
  }else{
    // initiate a file read
    reader.addFile(file.c_str(),this);
 }
}
After you issued the reader.addFile() your RestoreDocFile() is called:
void PropertyMeshKernel::RestoreDocFile(Base::Reader &reader)
{
    _pcMesh->Read( reader );
}
See also
Base::Reader,Base::XMLReader
Reimplemented from Data::ComplexGeoData.
Definition at line 1218 of file TopoShape.cpp.
References TechDrawTools.TaskFillTemplateFields::reader, and Data::ComplexGeoData::RestoreDocFile().
reTagElementMap()
void Part::TopoShape::reTagElementMap (long tag, App::StringHasherRef hasher, const char * postfix = nullptr) override virtual
Append the Tag (if and only if it is non zero) into the element map.
Reimplemented from Data::ComplexGeoData.
Referenced by _getTopoShape(), and FC_LOG_LEVEL_INIT().
revolve()
TopoDS_Shape TopoShape::revolve (const gp_Ax1 & axis, double d, Standard_Boolean isSolid = Standard_False) const
revolve shape. Note: isSolid is deprecated (instead, use some Part::FaceMaker to make a face, first).
Definition at line 2481 of file TopoShape.cpp.
References Base::Console(), SCL.SimpleDataTypes::e, SCL.SimpleDataTypes::f, Path.Base.Util::isSolid(), Base::ConsoleSingleton::Message(), and src.Mod.PartDesign.fcgear.svggear::w.
Save()
void TopoShape::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Reimplemented from Data::ComplexGeoData.
Definition at line 1203 of file TopoShape.cpp.
References Data::ComplexGeoData::Save().
Referenced by Part::PropertyPartShape::Save().
SaveDocFile()
void TopoShape::SaveDocFile (Base::Writer &) const override virtual
This method is used to save large amounts of data to a binary file. Sometimes it makes no sense to write property data as XML. In case the amount of data is too big or the data type has a more effective way to save itself. In this cases it is possible to write the data in a separate file inside the document archive. In case you want do so you have to re-implement SaveDocFile(). First, you have to inform the framework in Save() that you want do so. Here an example from the Mesh module which can save a (pontetionaly big) triangle mesh:
void PropertyMeshKernel::Save (Base::Writer &writer) const
{
  if (writer.isForceXML())
  {
    writer << writer.ind() << "<Mesh>" << std::endl;
    MeshCore::MeshDocXML saver(*_pcMesh);
    saver.Save(writer);
  }else{
   writer << writer.ind() << "<Mesh file=\"" << writer.addFile("MeshKernel.bms", this) <<
"\"/>" << std::endl;
}
The writer.isForceXML() is an indication to force you to write XML. Regardless of size and effectiveness. The second part informs the Base::writer through writer.addFile("MeshKernel.bms", this) that this object wants to write a file with the given name. The method addFile() returns a unique name that then is written in the XML stream. This allows your RestoreDocFile() method to identify and read the file again. Later your SaveDocFile() method is called as many times as you issued the addFile() call:
 void
PropertyMeshKernel::SaveDocFile (Base::Writer &writer) const
{
    _pcMesh->Write( writer );
}
In this method you can simply stream your content to the file (Base::Writer inheriting from ostream).
Reimplemented from Data::ComplexGeoData.
Definition at line 1213 of file TopoShape.cpp.
References Data::ComplexGeoData::SaveDocFile().
section() [1/2]
TopoDS_Shape TopoShape::section (const std::vector< TopoDS_Shape > & shapes, Standard_Real tolerance = -1.0, Standard_Boolean approximate = Standard_False) const
Definition at line 1838 of file TopoShape.cpp.
References FCBRepAlgoAPI_Section::setAutoFuzzy(), and draftutils.utils::tolerance().
section() [2/2]
TopoDS_Shape TopoShape::section (TopoDS_Shape shape, Standard_Boolean approximate = Standard_False) const
Definition at line 1822 of file TopoShape.cpp.
setElementComboName()
Data::MappedName Part::TopoShape::setElementComboName (const Data::IndexedName & element, const std::vector< Data::MappedName > & names, const char * marker = nullptr, const char * op = nullptr, const Data::ElementIDRefs * sids = nullptr)
Referenced by FC_LOG_LEVEL_INIT(), and Part::Feature::getExportElementName().
setFaces()
void TopoShape::setFaces (const std::vector< Base::Vector3d > & Points, const std::vector< Facet > & faces, double tolerance = 1.0e-06)
Definition at line 3344 of file TopoShape.cpp.
References src.Mod.PartDesign.Scripts.Gear::e1, Handle(), buildPsets::p, ClipperLib::pi, draftutils.utils::tolerance(), and TestSpreadsheet::v.
setPyObject()
void TopoShape::setPyObject (PyObject * obj) override virtual
Reimplemented from Base::BaseClass.
Definition at line 571 of file TopoShape.cpp.
References Path.Log::error().
setShape() [1/2]
void Part::TopoShape::setShape (const TopoDS_Shape & shape, bool resetElementMap = true)
Referenced by Part::MultiFuse::execute(), Part::Revolution::execute(), PartDesign::FeaturePrimitive::execute(), FC_LOG_LEVEL_INIT(), getElementSource(), Part::ExtrusionHelper::makeElementDraft(), Part::Scale::nonuniformScale(), Part::PropertyPartShape::Restore(), Part::PropertyPartShape::SaveDocFile(), Part::PropertyPartShape::setValue(), and Part::Scale::uniformScale().
setShape() [2/2]
void Part::TopoShape::setShape (const TopoShape & shape) inline
Definition at line 293 of file TopoShape.h.
setTransform()
void TopoShape::setTransform (const Base::Matrix4D & rclTrf) override virtual
set the transformation of the CasCade Shape
Implements Data::ComplexGeoData.
Definition at line 636 of file TopoShape.cpp.
References convertTogpTrsf().
Referenced by PartDesign::Fillet::execute(), PartDesign::Chamfer::execute(), PartDesign::Transformed::execute(), Part::Feature::onChanged(), and Part::PropertyPartShape::setTransform().
sewShape()
void TopoShape::sewShape (double tolerance = 1.0e-06)
Definition at line 3053 of file TopoShape.cpp.
References draftutils.utils::tolerance().
shapeName() [1/2]
const std::string & TopoShape::shapeName (bool silent = false) const
Definition at line 517 of file TopoShape.cpp.
References shapeName(), and shapeType().
shapeName() [2/2]
const std::string & TopoShape::shapeName (TopAbs_ShapeEnum type, bool silent = false) static
Definition at line 507 of file TopoShape.cpp.
References _ShapeNames, FC_THROWM, initShapeNameMap(), and Path.Post.scripts.grbl_post::type.
Referenced by Sketcher::SketchObject::addExternal(), dressupGetSelected(), FC_LOG_LEVEL_INIT(), Part::Geometry::fromShape(), PartDesign::DressUp::getContinuousEdges(), Part::Feature::getElementFromSource(), Sketcher::SketchObject::getElementTypes(), Part::Feature::getExportElementName(), PartDesign::DressUp::getFaces(), Sketcher::SketchObject::getInternalElementMap(), Part::Feature::getRelatedElements(), Import::Tools::printLabel(), shapeName(), and shapeTypeAndIndex().
shapeType() [1/3]
TopAbs_ShapeEnum TopoShape::shapeType (bool silent = false) const
Definition at line 498 of file TopoShape.cpp.
References FC_THROWM, getShape(), and isNull().
shapeType() [2/3]
TopAbs_ShapeEnum TopoShape::shapeType (char type, bool silent = false) static
Definition at line 483 of file TopoShape.cpp.
References FC_THROWM, and Path.Post.scripts.grbl_post::type.
shapeType() [3/3]
TopAbs_ShapeEnum TopoShape::shapeType (const char * type, bool silent = false) static
Definition at line 467 of file TopoShape.cpp.
References _ShapeNames, FC_THROWM, Data::hasMissingElement(), initShapeNameMap(), and Path.Post.scripts.grbl_post::type.
Referenced by countSubShapes(), Attacher::AttachEngine::extractSubShape(), FC_LOG_LEVEL_INIT(), Part::Feature::getElementFromSource(), PartDesign::DressUp::getFaces(), Part::Feature::getRelatedElements(), Sketcher::SketchObject::getSubObject(), PartDesign::ProfileBased::getTopoShapeSupportFace(), PartDesign::ProfileBased::getUpToFace(), Part::ExtrusionHelper::makeElementDraft(), makeFace(), shapeName(), and shapeTypeAndIndex().
shapeTypeAndIndex() [1/2]
std::pair< TopAbs_ShapeEnum, int > TopoShape::shapeTypeAndIndex (const char * name) static
Definition at line 428 of file TopoShape.cpp.
References shapeName(), shapeType(), and Path.Post.scripts.grbl_post::type.
Referenced by FC_LOG_LEVEL_INIT(), Sketcher::SketchObject::getElementName(), Part::Feature::getExportElementName(), and hasSubShape().
shapeTypeAndIndex() [2/2]
std::pair< TopAbs_ShapeEnum, int > TopoShape::shapeTypeAndIndex (const Data::IndexedName & name) static
Definition at line 451 of file TopoShape.cpp.
References DraftVecUtils::equals(), Data::IndexedName::getIndex(), Data::IndexedName::getType(), and shapeType().
slice()
std::list< TopoDS_Wire > TopoShape::slice (const Base::Vector3d & dir, double d) const
Definition at line 1871 of file TopoShape.cpp.
References Part::CrossSection::slice(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
slices()
TopoDS_Compound TopoShape::slices (const Base::Vector3d & dir, const std::vector< double > & d) const
Definition at line 1877 of file TopoShape.cpp.
References Part::CrossSection::slice(), src.Mod.PartDesign.fcgear.svggear::w, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
splitWires()
TopoShape Part::TopoShape::splitWires (std::vector< TopoShape > * inner = nullptr, SplitWireReorient reorient = Reorient) const
Return the outer and inner wires of a face
Parameters
inner optional output of inner wires
reorient wire reorientation, see SplitWireReorient
Returns
Return the outer wire
Referenced by FC_LOG_LEVEL_INIT(), and Part::ExtrusionHelper::makeElementDraft().
toNurbs()
TopoDS_Shape TopoShape::toNurbs () const
Definition at line 3027 of file TopoShape.cpp.
transformGeometry()
void TopoShape::transformGeometry (const Base::Matrix4D & rclMat) override virtual
Applies a transformation on the real geometric data type.
Implements Data::ComplexGeoData.
Definition at line 2973 of file TopoShape.cpp.
References SCL.SimpleDataTypes::e, and makeGTransform().
Referenced by Part::PropertyPartShape::transformGeometry().
transformGShape()
TopoDS_Shape TopoShape::transformGShape (const Base::Matrix4D & rclTrf, bool copy = false) const
Definition at line 2986 of file TopoShape.cpp.
Referenced by makeGTransform().
transformShape()
bool TopoShape::transformShape (const Base::Matrix4D & rclTrf, bool copy, bool checkScale = false)
Definition at line 3011 of file TopoShape.cpp.
References _makeTransform(), Part::checkScale, and TopoShape().
Referenced by _getTopoShape(), PartDesign::Body::execute(), and Sketcher::SketchObject::getSubObject().
write()
void TopoShape::write (const char * FileName) const
Definition at line 848 of file TopoShape.cpp.
References exportBrep(), exportIges(), exportStep(), exportStl(), Base::FileInfo::filePath(), and Base::FileInfo::hasExtension().
Friends And Related Function Documentation
TopoShapeCache
friend class TopoShapeCache friend
Definition at line 2569 of file TopoShape.h.
Member Data Documentation
anisotropy
bool Part::TopoShape::anisotropy = false
The Boolean Anisotropie.
Definition at line 282 of file TopoShapeMapper.h.
boundary_begin
int Part::TopoShape::boundary_begin = -1
Optional begin index to the input shapes to be used as the boundary of the filled face.
Definition at line 271 of file TopoShapeMapper.h.
boundary_end
int Part::TopoShape::boundary_end = -1
Optional end index (last index + 1) to the input shapes to be used as the boundary of the filled face.
Definition at line 274 of file TopoShapeMapper.h.
degree
unsigned int Part::TopoShape::degree = 3
The energe minimizing criterion degree;.
Definition at line 276 of file TopoShapeMapper.h.
maxdeg
unsigned int Part::TopoShape::maxdeg = 8
The highest polynomial degree MaxDeg.
Definition at line 292 of file TopoShapeMapper.h.
maxseg
unsigned int Part::TopoShape::maxseg = 9
The greatest number of segments MaxSeg.
If the Boolean Anistropie is true, the algorithm's performance is better in cases where the ratio of the length U and the length V indicate a great difference between the two. In other words, when the surface is, for example, extremely long.
Definition at line 300 of file TopoShapeMapper.h.
numiter
unsigned int Part::TopoShape::numiter = 2
The number of iterations NbIter.
Definition at line 280 of file TopoShapeMapper.h.
orders
std::unordered_map<TopoDS_Shape, TopoShape::Continuity, ShapeHasher, ShapeHasher> Part::TopoShape::orders
Optional map from input edge to continutity order. The default continuity order is TopoShape::Continuity::C0.
Definition at line 267 of file TopoShapeMapper.h.
ptsoncurve
unsigned int Part::TopoShape::ptsoncurve = 15
The number of points on the curve NbPntsOnCur.
Definition at line 278 of file TopoShapeMapper.h.
supports
std::unordered_map<TopoDS_Shape, TopoDS_Shape, ShapeHasher, ShapeHasher> Part::TopoShape::supports
Optional map from input shape to face used as support.
Definition at line 269 of file TopoShapeMapper.h.
surface
TopoShape Part::TopoShape::surface
Optional initial surface to begin the construction of the surface for the filled face.
It is useful if the surface resulting from construction for the algorithm is likely to be complex. The support surface of the face under construction is computed by a deformation of Surf which satisfies the given constraints. The set of bounding edges defines the wire of the face. If no initial surface is given, the algorithm computes it automatically. If the set of edges is not connected (Free constraint), missing edges are automatically computed. Important: the initial surface must have orthogonal local coordinates, i.e. partial derivatives dS/du and dS/dv must be orthogonal at each point of surface. If this condition breaks, distortions of resulting surface are possible
Definition at line 263 of file TopoShapeMapper.h.
Referenced by getMemSize(), and getPoints().
tol2d
double Part::TopoShape::tol2d = 1e-5
The 2D tolerance Tol2d.
Definition at line 284 of file TopoShapeMapper.h.
tol3d
double Part::TopoShape::tol3d = 1e-4
The 3D tolerance Tol3d.
Definition at line 286 of file TopoShapeMapper.h.
Referenced by FC_LOG_LEVEL_INIT().
tolG1
double Part::TopoShape::tolG1 = 0.01
The angular tolerance TolAng.
Definition at line 288 of file TopoShapeMapper.h.
tolG2
double Part::TopoShape::tolG2 = 0.1
The tolerance for curvature TolCur.
Definition at line 290 of file TopoShapeMapper.h.
The documentation for this struct was generated from the following files:
TopoShape.h
TopoShapeMapper.h
TopoShape.cpp