FreeCAD: TechDraw::DrawProjectSplit Class Reference
TechDraw::DrawProjectSplit Class Reference
#include <DrawProjectSplit.h>
Public Member Functions
DrawProjectSplit ()
~DrawProjectSplit ()
Static Public Member Functions
static std::vector< TopoDS_Edge > getEdgesForWalker (TopoDS_Shape shape, double scale, Base::Vector3d direction)
static TechDraw::GeometryObjectPtr buildGeometryObject (TopoDS_Shape shape, const gp_Ax2 &viewAxis)
static bool isOnEdge (TopoDS_Edge e, TopoDS_Vertex v, double &param, bool allowEnds=false)
static std::vector< TopoDS_Edge > splitEdges (std::vector< TopoDS_Edge > orig, std::vector< splitPoint > splits)
static std::vector< TopoDS_Edge > split1Edge (TopoDS_Edge e, std::vector< splitPoint > splitPoints)
static std::vector< splitPoint > sortSplits (std::vector< splitPoint > &s, bool ascend)
static bool splitCompare (const splitPoint &p1, const splitPoint &p2)
static bool splitEqual (const splitPoint &p1, const splitPoint &p2)
static std::vector< TopoDS_Edge > removeDuplicateEdges (std::vector< TopoDS_Edge > &inEdges)
static std::vector< edgeSortItem > sortEdges (std::vector< edgeSortItem > &e, bool ascend)
static std::vector< TopoDS_Edge > scrubEdges (const std::vector< BaseGeomPtr > &origEdges, std::vector< TopoDS_Edge > &closedEdges)
static std::vector< TopoDS_Edge > scrubEdges (std::vector< TopoDS_Edge > &origEdges, std::vector< TopoDS_Edge > &closedEdges)
static vertexMap getUniqueVertexes (std::vector< TopoDS_Edge > inEdges)
static std::vector< TopoDS_Edge > pruneUnconnected (vertexMap verts, std::vector< TopoDS_Edge > edges)
static std::vector< TopoDS_Edge > removeOverlapEdges (const std::vector< TopoDS_Edge > &inEdges)
static bool sameEndPoints (const TopoDS_Edge &e1, const TopoDS_Edge &e2)
static int isSubset (const TopoDS_Edge &e0, const TopoDS_Edge &e1)
static std::vector< TopoDS_Edge > fuseEdges (const TopoDS_Edge &e0, const TopoDS_Edge &e1)
static bool boxesIntersect (const TopoDS_Edge &e0, const TopoDS_Edge &e1)
static void dumpVertexMap (vertexMap verts)
Detailed Description
Definition at line 94 of file DrawProjectSplit.h.
Constructor & Destructor Documentation
DrawProjectSplit()
DrawProjectSplit::DrawProjectSplit ()
Definition at line 65 of file DrawProjectSplit.cpp.
~DrawProjectSplit()
DrawProjectSplit::~DrawProjectSplit ()
Definition at line 69 of file DrawProjectSplit.cpp.
Member Function Documentation
boxesIntersect()
bool DrawProjectSplit::boxesIntersect (const TopoDS_Edge & e0, const TopoDS_Edge & e1) static
Definition at line 705 of file DrawProjectSplit.cpp.
References KDL::Add().
Referenced by isSubset().
buildGeometryObject()
TechDraw::GeometryObjectPtr DrawProjectSplit::buildGeometryObject (TopoDS_Shape shape, const gp_Ax2 & viewAxis) static
Definition at line 109 of file DrawProjectSplit.cpp.
Referenced by getEdgesForWalker().
dumpVertexMap()
void DrawProjectSplit::dumpVertexMap (vertexMap verts) static
Definition at line 719 of file DrawProjectSplit.cpp.
References Base::Console(), TechDraw::DrawUtil::formatVector(), and Base::ConsoleSingleton::Message().
fuseEdges()
std::vector< TopoDS_Edge > DrawProjectSplit::fuseEdges (const TopoDS_Edge & e0, const TopoDS_Edge & e1) static
Definition at line 683 of file DrawProjectSplit.cpp.
References EWTOLERANCE, FUZZYADJUST, and SplineSurface::i.
Referenced by removeOverlapEdges().
getEdgesForWalker()
std::vector< TopoDS_Edge > DrawProjectSplit::getEdgesForWalker (TopoDS_Shape shape, double scale, Base::Vector3d direction) static
Definition at line 75 of file DrawProjectSplit.cpp.
References buildGeometryObject(), Base::Console(), SCL.SimpleDataTypes::e, EWTOLERANCE, TechDraw::DrawUtil::isZeroEdge(), TechDraw::ShapeUtils::legacyViewAxis1(), Base::ConsoleSingleton::Message(), and TechDraw::ShapeUtils::scaleShape().
getUniqueVertexes()
vertexMap DrawProjectSplit::getUniqueVertexes (std::vector< TopoDS_Edge > inEdges) static
Definition at line 499 of file DrawProjectSplit.cpp.
References FirstVertex(), LastVertex(), buildPsets::p, and draftgeoutils.general::v1().
Referenced by scrubEdges().
isOnEdge()
bool DrawProjectSplit::isOnEdge (TopoDS_Edge e, TopoDS_Vertex v, double & param, bool allowEnds = false) static
Definition at line 126 of file DrawProjectSplit.cpp.
References SCL.SimpleDataTypes::c, Base::Console(), DraftVecUtils::dist(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), FirstVertex(), Handle(), TechDraw::DrawUtil::isSamePoint(), LastVertex(), Init::param, TechDraw::DrawUtil::simpleMinDist(), TestSpreadsheet::v, and draftgeoutils.general::v1().
Referenced by TechDraw::DrawViewPart::findFacesOld().
isSubset()
int DrawProjectSplit::isSubset (const TopoDS_Edge & e0, const TopoDS_Edge & e1) static
Definition at line 641 of file DrawProjectSplit.cpp.
References boxesIntersect(), e0ISSUBSET, e1ISSUBSET, EDGEOVERLAP, EWTOLERANCE, FUZZYADJUST, SplineSurface::i, NOTASUBSET, and sameEndPoints().
Referenced by removeOverlapEdges().
pruneUnconnected()
std::vector< TopoDS_Edge > DrawProjectSplit::pruneUnconnected (vertexMap verts, std::vector< TopoDS_Edge > edges) static
Definition at line 527 of file DrawProjectSplit.cpp.
References FirstVertex(), LastVertex(), buildPsets::p, and draftgeoutils.general::v1().
Referenced by scrubEdges().
removeDuplicateEdges()
std::vector< TopoDS_Edge > DrawProjectSplit::removeDuplicateEdges (std::vector< TopoDS_Edge > & inEdges) static
Definition at line 289 of file DrawProjectSplit.cpp.
References TechDraw::DrawUtil::angleWithX(), Base::Console(), SCL.SimpleDataTypes::e, TechDraw::edgeSortItem::edgeEqual(), TechDraw::edgeSortItem::end, TechDraw::edgeSortItem::endAngle, FirstVertex(), TechDraw::edgeSortItem::idx, LastVertex(), Base::ConsoleSingleton::Message(), result, sortEdges(), TechDraw::edgeSortItem::start, TechDraw::edgeSortItem::startAngle, draftgeoutils.general::v1(), TechDraw::DrawUtil::vectorLess(), and TechDraw::DrawUtil::vertex2Vector().
Referenced by TechDraw::DrawViewPart::findFacesOld().
removeOverlapEdges()
std::vector< TopoDS_Edge > DrawProjectSplit::removeOverlapEdges (const std::vector< TopoDS_Edge > & inEdges) static
Definition at line 588 of file DrawProjectSplit.cpp.
References SCL.SimpleDataTypes::e, e0ISSUBSET, e1ISSUBSET, EDGEOVERLAP, fuseEdges(), and isSubset().
Referenced by TechDraw::GeometryObject::addGeomFromCompound().
sameEndPoints()
bool DrawProjectSplit::sameEndPoints (const TopoDS_Edge & e1, const TopoDS_Edge & e2) static
Definition at line 563 of file DrawProjectSplit.cpp.
References src.Mod.PartDesign.Scripts.Gear::e1, FirstVertex(), LastVertex(), and TechDraw::DrawUtil::vertexEqual().
Referenced by isSubset().
scrubEdges() [1/2]
std::vector< TopoDS_Edge > DrawProjectSplit::scrubEdges (const std::vector< BaseGeomPtr > & origEdges, std::vector< TopoDS_Edge > & closedEdges) static
Definition at line 399 of file DrawProjectSplit.cpp.
References EWTOLERANCE, and TechDraw::DrawUtil::isZeroEdge().
Referenced by TechDraw::DrawViewPart::findFacesNew().
scrubEdges() [2/2]
std::vector< TopoDS_Edge > DrawProjectSplit::scrubEdges (std::vector< TopoDS_Edge > & origEdges, std::vector< TopoDS_Edge > & closedEdges) static
Definition at line 418 of file DrawProjectSplit.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), EWTOLERANCE, importers.importIFClegacy::explorer(), FUZZYADJUST, getUniqueVertexes(), pruneUnconnected(), and Base::ConsoleSingleton::Warning().
sortEdges()
std::vector< edgeSortItem > DrawProjectSplit::sortEdges (std::vector< edgeSortItem > & e, bool ascend) static
Definition at line 332 of file DrawProjectSplit.cpp.
References SCL.SimpleDataTypes::e, and TechDraw::edgeSortItem::edgeLess().
Referenced by removeDuplicateEdges().
sortSplits()
std::vector< splitPoint > DrawProjectSplit::sortSplits (std::vector< splitPoint > & s, bool ascend) static
Definition at line 254 of file DrawProjectSplit.cpp.
References toolbit-attributes::s, and splitCompare().
Referenced by TechDraw::DrawViewPart::findFacesOld().
split1Edge()
std::vector< TopoDS_Edge > DrawProjectSplit::split1Edge (TopoDS_Edge e, std::vector< splitPoint > splitPoints) static
Definition at line 212 of file DrawProjectSplit.cpp.
References SCL.SimpleDataTypes::c, Base::Console(), SCL.SimpleDataTypes::e, src.Mod.PartDesign.Scripts.Gear::e1, Handle(), Base::ConsoleSingleton::Message(), result, and toolbit-attributes::s.
Referenced by splitEdges().
splitCompare()
bool DrawProjectSplit::splitCompare (const splitPoint & p1, const splitPoint & p2) static
Definition at line 265 of file DrawProjectSplit.cpp.
References TechDraw::splitPoint::i, and TechDraw::splitPoint::param.
Referenced by sortSplits().
splitEdges()
std::vector< TopoDS_Edge > DrawProjectSplit::splitEdges (std::vector< TopoDS_Edge > orig, std::vector< splitPoint > splits) static
Definition at line 167 of file DrawProjectSplit.cpp.
References KDL::max(), result, and split1Edge().
Referenced by TechDraw::DrawViewPart::findFacesOld().
splitEqual()
bool DrawProjectSplit::splitEqual (const splitPoint & p1, const splitPoint & p2) static
Definition at line 280 of file DrawProjectSplit.cpp.
References TechDraw::splitPoint::i, and TechDraw::splitPoint::param.
Referenced by TechDraw::DrawViewPart::findFacesOld().
The documentation for this class was generated from the following files:
DrawProjectSplit.h
DrawProjectSplit.cpp