FreeCAD: Gui::RecoveryRunnable Class Reference
Gui::RecoveryRunnable Class Reference
Public Member Functions
RecoveryRunnable (const std::set< std::string > &modes, const char *dir, const char *file, const App::Property *p)
~RecoveryRunnable () override
void run () override
Detailed Description
Definition at line 325 of file AutoSaver.cpp.
Constructor & Destructor Documentation
RecoveryRunnable()
Gui::RecoveryRunnable::RecoveryRunnable (const std::set< std::string > & modes, const char * dir, const char * file, const App::Property * p) inline
Definition at line 328 of file AutoSaver.cpp.
References DrawingExample::file, modes, Base::FileWriter::putNextEntry(), and Base::Writer::setModes().
~RecoveryRunnable()
Gui::RecoveryRunnable::~RecoveryRunnable () inline override
Definition at line 339 of file AutoSaver.cpp.
Member Function Documentation
run()
void Gui::RecoveryRunnable::run () inline override
Definition at line 343 of file AutoSaver.cpp.
References Base::FileWriter::close(), Gui::AutoSaver::instance(), and Base::Persistence::SaveDocFile().
Referenced by femexamples.examplesgui.FemExamples::clicked(), and femsolver.task.Task::protector().
The documentation for this class was generated from the following file:
AutoSaver.cpp