FreeCAD: TechDrawGui::QGIDatumLabel Class Reference
TechDrawGui::QGIDatumLabel Class Reference
#include <QGIViewDimension.h>
Public Types
enum { Type = QGraphicsItem::UserType + 107 }
Signals
void setPretty (int state)
void dragging (bool)
void hover (bool state)
void selected (bool state)
void dragFinished ()
Public Member Functions
QGIDatumLabel ()
~QGIDatumLabel () override=default
int type () const override
QRectF boundingRect () const override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
void setLabelCenter ()
void setPosFromCenter (const double &xCenter, const double &yCenter)
double X () const
double Y () const
Base::Vector2d getPosToCenterVec ()
void setFont (QFont font)
QFont getFont () const
void setDimString (QString text)
void setDimString (QString text, qreal maxWidth)
void setUnitString (QString text)
void setToleranceString ()
void setPrettySel ()
void setPrettyPre ()
void setPrettyNormal ()
void setColor (QColor color)
void setSelectability (bool val)
void setFrameColor (QColor color)
QGCustomText * getDimText ()
void setDimText (QGCustomText *newText)
QGCustomText * getTolTextOver ()
void setTolTextOver (QGCustomText *newTol)
QGCustomText * getTolTextUnder ()
void setTolTextUnder (QGCustomText *newTol)
double getTolAdjust ()
bool isFramed () const
void setFramed (bool framed)
double getLineWidth () const
void setLineWidth (double lineWidth)
void setQDim (QGIViewDimension *qDim)
Protected Member Functions
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
void updateFrameRect ()
int getPrecision ()
void snapPosition (QPointF &position)
bool getVerticalSep () const
void setVerticalSep (bool sep)
std::vector< int > getSeps () const
void setSeps (std::vector< int > newSeps)
Detailed Description
Definition at line 60 of file QGIViewDimension.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 68 of file QGIViewDimension.h.
Constructor & Destructor Documentation
QGIDatumLabel()
QGIDatumLabel::QGIDatumLabel ()
Definition at line 88 of file QGIViewDimension.cpp.
References TechDrawGui::Rez::guiX(), setSelectability(), and TechDrawGui::QGCustomText::setTightBounding().
~QGIDatumLabel()
TechDrawGui::QGIDatumLabel::~QGIDatumLabel () override default
Member Function Documentation
boundingRect()
QRectF QGIDatumLabel::boundingRect () const override
Definition at line 352 of file QGIViewDimension.cpp.
Referenced by TechDrawGui::QGIViewDimension::boundingRect(), TechDrawGui::QGIViewDimension::drawAngle(), TechDrawGui::QGIViewDimension::drawArea(), TechDrawGui::QGIViewDimension::drawAreaExecutive(), TechDrawGui::QGIViewDimension::drawDiameter(), TechDrawGui::QGIViewDimension::drawDistance(), TechDrawGui::QGIViewDimension::drawDistanceExecutive(), TechDrawGui::QGIViewDimension::drawDistanceOverride(), TechDrawGui::QGIViewDimension::drawRadius(), TechDrawGui::QGIViewDimension::drawRadiusExecutive(), and getPosToCenterVec().
dragFinished
void TechDrawGui::QGIDatumLabel::dragFinished () signal
Referenced by itemChange(), mouseReleaseEvent(), and TechDrawGui::QGIViewDimension::QGIViewDimension().
dragging
void TechDrawGui::QGIDatumLabel::dragging (bool) signal
Referenced by itemChange(), and TechDrawGui::QGIViewDimension::QGIViewDimension().
getDimText()
QGCustomText* TechDrawGui::QGIDatumLabel::getDimText () inline
Definition at line 95 of file QGIViewDimension.h.
Referenced by TechDrawGui::QGIViewDimension::getLabelText().
getFont()
QFont TechDrawGui::QGIDatumLabel::getFont () const inline
Definition at line 83 of file QGIViewDimension.h.
Referenced by TechDrawGui::QGIViewDimension::updateDim().
getLineWidth()
double TechDrawGui::QGIDatumLabel::getLineWidth () const inline
Definition at line 107 of file QGIViewDimension.h.
getPosToCenterVec()
Base::Vector2d QGIDatumLabel::getPosToCenterVec ()
Definition at line 454 of file QGIViewDimension.cpp.
References boundingRect(), and exportCSG::center().
Referenced by setLabelCenter(), setPosFromCenter(), and snapPosition().
getPrecision()
int QGIDatumLabel::getPrecision () protected
Definition at line 565 of file QGIViewDimension.cpp.
References Base::UnitsApi::getDecimals().
getSeps()
std::vector<int> TechDrawGui::QGIDatumLabel::getSeps () const inline protected
Definition at line 132 of file QGIViewDimension.h.
getTolAdjust()
double QGIDatumLabel::getTolAdjust ()
Definition at line 573 of file QGIViewDimension.cpp.
Referenced by setFont().
getTolTextOver()
QGCustomText* TechDrawGui::QGIDatumLabel::getTolTextOver () inline
Definition at line 97 of file QGIViewDimension.h.
Referenced by TechDrawGui::QGIViewDimension::getLabelText().
getTolTextUnder()
QGCustomText* TechDrawGui::QGIDatumLabel::getTolTextUnder () inline
Definition at line 99 of file QGIViewDimension.h.
Referenced by TechDrawGui::QGIViewDimension::getLabelText().
getVerticalSep()
bool TechDrawGui::QGIDatumLabel::getVerticalSep () const inline protected
Definition at line 130 of file QGIViewDimension.h.
hover
void TechDrawGui::QGIDatumLabel::hover (bool state) signal
Referenced by hoverEnterEvent(), hoverLeaveEvent(), and TechDrawGui::QGIViewDimension::QGIViewDimension().
hoverEnterEvent()
void QGIDatumLabel::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override protected
Definition at line 327 of file QGIViewDimension.cpp.
References hover(), setPrettyPre(), and setPrettySel().
hoverLeaveEvent()
void QGIDatumLabel::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override protected
Definition at line 339 of file QGIViewDimension.cpp.
References hover(), setPrettyNormal(), and setPrettySel().
isFramed()
bool TechDrawGui::QGIDatumLabel::isFramed () const inline
Definition at line 104 of file QGIViewDimension.h.
itemChange()
QVariant QGIDatumLabel::itemChange (GraphicsItemChange change, const QVariant & value) override protected
Definition at line 139 of file QGIViewDimension.cpp.
References dragFinished(), Dragging, dragging(), NoDrag, setLabelCenter(), setPrettyNormal(), setPrettySel(), and snapPosition().
mouseDoubleClickEvent()
void QGIDatumLabel::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 308 of file QGIViewDimension.cpp.
References TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), and Gui::ViewProviderDocumentObject::startDefaultEditMode().
mousePressEvent()
void QGIDatumLabel::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 287 of file QGIViewDimension.cpp.
mouseReleaseEvent()
void QGIDatumLabel::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override
Definition at line 296 of file QGIViewDimension.cpp.
References dragFinished(), Dragging, and NoDrag.
paint()
void QGIDatumLabel::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 385 of file QGIViewDimension.cpp.
selected
void TechDrawGui::QGIDatumLabel::selected (bool state) signal
Referenced by TechDrawGui::QGIViewDimension::QGIViewDimension().
setColor()
void QGIDatumLabel::setColor (QColor color)
Definition at line 612 of file QGIViewDimension.cpp.
References TechDrawGui::QGCustomText::setColor(), and setFrameColor().
Referenced by TechDrawGui::QGIViewDimension::setNormalColorAll().
setDimString() [1/2]
void QGIDatumLabel::setDimString (QString text)
Definition at line 475 of file QGIViewDimension.cpp.
References updateFrameRect().
Referenced by TechDrawGui::QGIViewDimension::updateDim().
setDimString() [2/2]
void QGIDatumLabel::setDimString (QString text, qreal maxWidth)
Definition at line 482 of file QGIViewDimension.cpp.
References updateFrameRect().
setDimText()
void TechDrawGui::QGIDatumLabel::setDimText (QGCustomText * newText) inline
Definition at line 96 of file QGIViewDimension.h.
setFont()
void QGIDatumLabel::setFont (QFont font)
Definition at line 461 of file QGIViewDimension.cpp.
References getTolAdjust(), KDL::max(), and updateFrameRect().
Referenced by TechDrawGui::QGIViewDimension::updateDim().
setFrameColor()
void QGIDatumLabel::setFrameColor (QColor color)
Definition at line 378 of file QGIViewDimension.cpp.
Referenced by setColor(), setPrettyNormal(), setPrettyPre(), and setPrettySel().
setFramed()
void QGIDatumLabel::setFramed (bool framed)
Definition at line 127 of file QGIViewDimension.cpp.
Referenced by TechDrawGui::QGIViewDimension::updateDim().
setLabelCenter()
void QGIDatumLabel::setLabelCenter ()
Definition at line 446 of file QGIViewDimension.cpp.
References getPosToCenterVec(), SurfaceTests.TestBlendCurve::vec, MovieTool::x, and MovieTool::y.
Referenced by itemChange().
setLineWidth()
void QGIDatumLabel::setLineWidth (double lineWidth)
Definition at line 371 of file QGIViewDimension.cpp.
Referenced by TechDrawGui::QGIViewDimension::updateDim().
setPosFromCenter()
void QGIDatumLabel::setPosFromCenter (const double & xCenter, const double & yCenter)
Definition at line 397 of file QGIViewDimension.cpp.
References TechDrawGui::QGCustomText::alignmentRect(), getPosToCenterVec(), TechDrawGui::QGCustomText::justifyLeftAt(), middle, TechDrawGui::QGCustomText::tightBoundingAdjust(), and SurfaceTests.TestBlendCurve::vec.
Referenced by TechDrawGui::QGIViewDimension::setViewPartFeature(), TechDrawGui::QGIViewDimension::updateDim(), and TechDrawGui::QGIViewDimension::updateView().
setPretty
void TechDrawGui::QGIDatumLabel::setPretty (int state) signal
Referenced by TechDrawGui::QGIViewDimension::QGIViewDimension(), setPrettyNormal(), setPrettyPre(), and setPrettySel().
setPrettyNormal()
void QGIDatumLabel::setPrettyNormal ()
Definition at line 601 of file QGIViewDimension.cpp.
References NORMAL, TechDrawGui::PreferencesGui::normalQColor(), setFrameColor(), setPretty(), and TechDrawGui::QGCustomText::setPrettyNormal().
Referenced by hoverLeaveEvent(), and itemChange().
setPrettyPre()
void QGIDatumLabel::setPrettyPre ()
Definition at line 590 of file QGIViewDimension.cpp.
References PRE, TechDrawGui::PreferencesGui::preselectQColor(), setFrameColor(), setPretty(), and TechDrawGui::QGCustomText::setPrettyPre().
Referenced by hoverEnterEvent().
setPrettySel()
void QGIDatumLabel::setPrettySel ()
Definition at line 579 of file QGIViewDimension.cpp.
References TechDrawGui::PreferencesGui::selectQColor(), setFrameColor(), setPretty(), and TechDrawGui::QGCustomText::setPrettySel().
Referenced by hoverEnterEvent(), hoverLeaveEvent(), and itemChange().
setQDim()
void TechDrawGui::QGIDatumLabel::setQDim (QGIViewDimension * qDim) inline
Definition at line 109 of file QGIViewDimension.h.
Referenced by TechDrawGui::QGIViewDimension::QGIViewDimension().
setSelectability()
void QGIDatumLabel::setSelectability (bool val)
Definition at line 623 of file QGIViewDimension.cpp.
References toolbit-attributes::val.
Referenced by QGIDatumLabel(), and TechDrawGui::MDIViewPage::setDimensionsSelectability().
setSeps()
void TechDrawGui::QGIDatumLabel::setSeps (std::vector< int > newSeps) inline protected
Definition at line 133 of file QGIViewDimension.h.
setToleranceString()
void QGIDatumLabel::setToleranceString ()
Definition at line 490 of file QGIViewDimension.cpp.
References TechDrawGui::QGIView::getViewObject(), and updateFrameRect().
Referenced by TechDrawGui::QGIViewDimension::updateDim().
setTolTextOver()
void TechDrawGui::QGIDatumLabel::setTolTextOver (QGCustomText * newTol) inline
Definition at line 98 of file QGIViewDimension.h.
setTolTextUnder()
void TechDrawGui::QGIDatumLabel::setTolTextUnder (QGCustomText * newTol) inline
Definition at line 100 of file QGIViewDimension.h.
setUnitString()
void QGIDatumLabel::setUnitString (QString text)
Definition at line 551 of file QGIViewDimension.cpp.
References updateFrameRect().
setVerticalSep()
void TechDrawGui::QGIDatumLabel::setVerticalSep (bool sep) inline protected
Definition at line 131 of file QGIViewDimension.h.
snapPosition()
void QGIDatumLabel::snapPosition (QPointF & position) protected
Definition at line 168 of file QGIViewDimension.cpp.
References activeDimAttributes, TechDraw::pointPair::first(), dimAttributes::getCascadeSpacing(), TechDraw::DrawViewPart::getDimensions(), getPosToCenterVec(), Gui::Application::getViewProvider(), TechDrawGui::Rez::guiX(), Gui::Application::Instance, FreeCADInit::Length, RobotExample::pos, Base::Vector2d::ProjectToLine(), TechDraw::pointPair::second(), type(), Base::Vector2d::x, Base::Vector3< float_type >::x, Base::Vector2d::y, and Base::Vector3< float_type >::y.
Referenced by itemChange().
type()
int TechDrawGui::QGIDatumLabel::type () const inline override
Definition at line 69 of file QGIViewDimension.h.
References Type.
Referenced by snapPosition().
updateFrameRect()
void QGIDatumLabel::updateFrameRect () protected
Definition at line 357 of file QGIViewDimension.cpp.
Referenced by setDimString(), setFont(), setToleranceString(), and setUnitString().
X()
double TechDrawGui::QGIDatumLabel::X () const inline
Definition at line 78 of file QGIViewDimension.h.
Referenced by TechDrawGui::QGIViewDimension::datumLabelDragFinished(), and TechDrawGui::QGIViewDimension::updateDim().
Y()
double TechDrawGui::QGIDatumLabel::Y () const inline
Definition at line 79 of file QGIViewDimension.h.
Referenced by TechDrawGui::QGIViewDimension::datumLabelDragFinished(), and TechDrawGui::QGIViewDimension::updateDim().
The documentation for this class was generated from the following files:
QGIViewDimension.h
QGIViewDimension.cpp