FreeCAD: Base::TimeInfo Class Reference
Base::TimeInfo Class Reference
#include <TimeInfo.h>
Public Member Functions
TimeInfo ()
TimeInfo (const TimeInfo &)=default
TimeInfo (TimeInfo &&)=default
~TimeInfo ()=default
void setCurrent ()
void setTime_t (std::time_t time)
std::time_t getTime_t ()
bool isNull () const
Static Public Member Functions
static float diffTimeF (const TimeInfo &start, const TimeInfo &end=TimeInfo())
static std::string diffTime (const TimeInfo &start, const TimeInfo &end=TimeInfo())
static TimeInfo null ()
Detailed Description
Definition at line 59 of file TimeInfo.h.
Constructor & Destructor Documentation
TimeInfo() [1/3]
Base::TimeInfo::TimeInfo () inline
Definition at line 65 of file TimeInfo.h.
TimeInfo() [2/3]
Base::TimeInfo::TimeInfo (const TimeInfo &) default
TimeInfo() [3/3]
Base::TimeInfo::TimeInfo (TimeInfo &&) default
~TimeInfo()
Base::TimeInfo::~TimeInfo () default
Member Function Documentation
diffTime()
static std::string Base::TimeInfo::diffTime (const TimeInfo & start, const TimeInfo & end = TimeInfo()) inline static
Definition at line 97 of file TimeInfo.h.
References Base::TimeElapsed::setCurrent(), and Base::TimeElapsed::TimeElapsed().
diffTimeF()
static float Base::TimeInfo::diffTimeF (const TimeInfo & start, const TimeInfo & end = TimeInfo()) inline static
Definition at line 91 of file TimeInfo.h.
getTime_t()
std::time_t Base::TimeInfo::getTime_t () inline
Definition at line 86 of file TimeInfo.h.
isNull()
bool Base::TimeInfo::isNull () const inline
Definition at line 105 of file TimeInfo.h.
null()
static TimeInfo Base::TimeInfo::null () inline static
Definition at line 110 of file TimeInfo.h.
References Path.Post.scripts.dumper_post::now.
Referenced by Base::FileInfo::lastModified(), and Base::FileInfo::lastRead().
setCurrent()
void Base::TimeInfo::setCurrent () inline
Definition at line 74 of file TimeInfo.h.
setTime_t()
void Base::TimeInfo::setTime_t (std::time_t time) inline
Definition at line 80 of file TimeInfo.h.
Referenced by Base::FileInfo::lastModified(), and Base::FileInfo::lastRead().
The documentation for this class was generated from the following file:
TimeInfo.h