FreeCAD: nativeifc.ifc_selftest.NativeIFCTest Class Reference
nativeifc.ifc_selftest.NativeIFCTest Class Reference
Public Member Functions
def setUp (self)
def tearDown (self)
def test01_ImportCoinSingle (self)
def test02_ImportCoinStructure (self)
def test03_ImportCoinFull (self)
def test04_ImportShapeFull (self)
def test05_ImportFreeCAD (self)
def test06_ModifyObjects (self)
def test07_CreateDocument (self)
def test08_ChangeIFCSchema (self)
def test09_CreateBIMObjects (self)
def test10_ChangePlacement (self)
def test11_ChangeGeometry (self)
def test12_RemoveObject (self)
def test13_Materials (self)
def test14_Layers (self)
def test15_Psets (self)
Detailed Description
Definition at line 92 of file ifc_selftest.py.
Member Function Documentation
setUp()
def nativeifc.ifc_selftest.NativeIFCTest.setUp (self)
Definition at line 94 of file ifc_selftest.py.
tearDown()
def nativeifc.ifc_selftest.NativeIFCTest.tearDown (self)
Definition at line 103 of file ifc_selftest.py.
Referenced by CAMTests.TestPathHelix.TestPathHelix.test03(), CAMTests.TestPathHelix.TestPathHelix.test04(), and CAMTests.TestPathHelix.TestPathHelix.testRecomputeHelixFromV021().
test01_ImportCoinSingle()
def nativeifc.ifc_selftest.NativeIFCTest.test01_ImportCoinSingle (self)
Definition at line 107 of file ifc_selftest.py.
References nativeifc.ifc_selftest.clearObjects(), and nativeifc.ifc_selftest.getIfcFilePath().
test02_ImportCoinStructure()
def nativeifc.ifc_selftest.NativeIFCTest.test02_ImportCoinStructure (self)
Definition at line 125 of file ifc_selftest.py.
References nativeifc.ifc_selftest.clearObjects(), and nativeifc.ifc_selftest.getIfcFilePath().
test03_ImportCoinFull()
def nativeifc.ifc_selftest.NativeIFCTest.test03_ImportCoinFull (self)
Definition at line 143 of file ifc_selftest.py.
References nativeifc.ifc_selftest.clearObjects(), and nativeifc.ifc_selftest.getIfcFilePath().
test04_ImportShapeFull()
def nativeifc.ifc_selftest.NativeIFCTest.test04_ImportShapeFull (self)
Definition at line 163 of file ifc_selftest.py.
References nativeifc.ifc_selftest.clearObjects(), and nativeifc.ifc_selftest.getIfcFilePath().
test05_ImportFreeCAD()
def nativeifc.ifc_selftest.NativeIFCTest.test05_ImportFreeCAD (self)
Definition at line 179 of file ifc_selftest.py.
References nativeifc.ifc_selftest.clearObjects().
test06_ModifyObjects()
def nativeifc.ifc_selftest.NativeIFCTest.test06_ModifyObjects (self)
Definition at line 191 of file ifc_selftest.py.
References nativeifc.ifc_selftest.compare().
test07_CreateDocument()
def nativeifc.ifc_selftest.NativeIFCTest.test07_CreateDocument (self)
Definition at line 206 of file ifc_selftest.py.
test08_ChangeIFCSchema()
def nativeifc.ifc_selftest.NativeIFCTest.test08_ChangeIFCSchema (self)
Definition at line 214 of file ifc_selftest.py.
References nativeifc.ifc_selftest.clearObjects(), nativeifc.ifc_selftest.getIfcFilePath(), and nativeifc.ifc_tools.recompute().
test09_CreateBIMObjects()
def nativeifc.ifc_selftest.NativeIFCTest.test09_CreateBIMObjects (self)
Definition at line 235 of file ifc_selftest.py.
References Arch.makeBuilding(), Arch.makeFloor(), Arch.makeSite(), and Arch.makeWall().
test10_ChangePlacement()
def nativeifc.ifc_selftest.NativeIFCTest.test10_ChangePlacement (self)
Definition at line 263 of file ifc_selftest.py.
References nativeifc.ifc_selftest.clearObjects(), nativeifc.ifc_selftest.getIfcFilePath(), UtilsAssembly.getObject(), and Path.Post.scripts.refactored_centroid_post.str.
test11_ChangeGeometry()
def nativeifc.ifc_selftest.NativeIFCTest.test11_ChangeGeometry (self)
Definition at line 284 of file ifc_selftest.py.
References nativeifc.ifc_selftest.clearObjects(), nativeifc.ifc_selftest.getIfcFilePath(), UtilsAssembly.getObject(), and nativeifc.ifc_tools.recompute().
test12_RemoveObject()
def nativeifc.ifc_selftest.NativeIFCTest.test12_RemoveObject (self)
Definition at line 303 of file ifc_selftest.py.
References nativeifc.ifc_selftest.clearObjects(), and nativeifc.ifc_selftest.getIfcFilePath().
test13_Materials()
def nativeifc.ifc_selftest.NativeIFCTest.test13_Materials (self)
Definition at line 324 of file ifc_selftest.py.
References nativeifc.ifc_selftest.clearObjects(), nativeifc.ifc_selftest.getIfcFilePath(), UtilsAssembly.getObject(), and Arch.makeMaterial().
test14_Layers()
def nativeifc.ifc_selftest.NativeIFCTest.test14_Layers (self)
Definition at line 349 of file ifc_selftest.py.
References nativeifc.ifc_selftest.clearObjects(), nativeifc.ifc_selftest.getIfcFilePath(), and UtilsAssembly.getObject().
test15_Psets()
def nativeifc.ifc_selftest.NativeIFCTest.test15_Psets (self)
Definition at line 371 of file ifc_selftest.py.
References nativeifc.ifc_selftest.clearObjects(), nativeifc.ifc_selftest.getIfcFilePath(), and UtilsAssembly.getObject().
The documentation for this class was generated from the following file:
ifc_selftest.py