FreeCAD: Import::ExportOCAF2 Class Reference
Import::ExportOCAF2 Class Reference
#include <ExportOCAF2.h>
Public Types
using GetShapeColorsFunc = std::function< std::map< std::string, App::Color >(App::DocumentObject *, const char *)>
using GetShapeColorsFunc = std::function< std::map< std::string, App::Color >(App::DocumentObject *, const char *)>
Public Member Functions
ExportOCAF2 (Handle(TDocStd_Document) hDoc, GetShapeColorsFunc func=GetShapeColorsFunc())
void setExportOptions (ExportOCAFOptions opts)
void setExportHiddenObject (bool enable)
void setKeepPlacement (bool enable)
void exportObjects (std::vector< App::DocumentObject * > &objs, const char *name=nullptr)
bool canFallback (std::vector< App::DocumentObject * > objs)
ExportOCAF2 (Handle(TDocStd_Document) h, GetShapeColorsFunc func=GetShapeColorsFunc())
void setExportOptions (ExportOCAFOptions opts)
void setExportHiddenObject (bool enable)
void setKeepPlacement (bool enable)
void exportObjects (std::vector< App::DocumentObject * > &objs, const char *name=nullptr)
bool canFallback (std::vector< App::DocumentObject * > objs)
Static Public Member Functions
static ExportOCAFOptions customExportOptions ()
ExportOCAF2::customExportOptions.
static ExportOCAFOptions customExportOptions ()
Detailed Description
Definition at line 59 of file ExportOCAF2.h.
Member Typedef Documentation
GetShapeColorsFunc [1/2]
using Import::ExportOCAF2::GetShapeColorsFunc = std::function<std::map<std::string, App::Color>(App::DocumentObject*, const char*)>
Definition at line 63 of file ExportOCAF2.h.
GetShapeColorsFunc [2/2]
using Import::ExportOCAF2::GetShapeColorsFunc = std::function<std::map<std::string, App::Color>(App::DocumentObject*, const char*)>
Definition at line 238 of file ImportOCAF2.h.
Constructor & Destructor Documentation
ExportOCAF2() [1/2]
ExportOCAF2::ExportOCAF2 (Handle(TDocStd_Document) hDoc, GetShapeColorsFunc func = GetShapeColorsFunc()) explicit
Definition at line 69 of file ExportOCAF2.cpp.
References Part::Interface::Auto, and Part::Interface::writeStepAssembly().
ExportOCAF2() [2/2]
Import::ExportOCAF2::ExportOCAF2 (Handle(TDocStd_Document) h, GetShapeColorsFunc func = GetShapeColorsFunc()) explicit
Member Function Documentation
canFallback() [1/2]
bool ExportOCAF2::canFallback (std::vector< App::DocumentObject * > objs)
Definition at line 610 of file ExportOCAF2.cpp.
References App::ExtensionContainer::getExtensionByType(), App::DocumentObject::getSubObject(), App::DocumentObject::getSubObjects(), SplineSurface::i, App::DocumentObject::isAttachedToDocument(), and replaceobj::objs.
canFallback() [2/2]
bool Import::ExportOCAF2::canFallback (std::vector< App::DocumentObject * > objs)
customExportOptions() [1/2]
ExportOCAFOptions ExportOCAF2::customExportOptions () static
ExportOCAF2::customExportOptions.
Returns
options from user settings
Definition at line 85 of file ExportOCAF2.cpp.
References App::Color::a, Import::ExportOCAFOptions::defaultColor, Import::ExportOCAFOptions::exportHidden, App::GetApplication(), Part::OCAF::ImportExportSettings::getExportHiddenObject(), Part::OCAF::ImportExportSettings::getExportKeepPlacement(), App::Color::getPackedValue(), App::Application::GetParameterGroupByPath(), Import::ExportOCAFOptions::keepPlacement, and App::Color::setPackedValue().
customExportOptions() [2/2]
static ExportOCAFOptions Import::ExportOCAF2::customExportOptions () static
exportObjects() [1/2]
void ExportOCAF2::exportObjects (std::vector< App::DocumentObject * > & objs, const char * name = nullptr)
Definition at line 338 of file ExportOCAF2.cpp.
References toolbit-attributes::doc, Import::Tools::dumpLabels(), FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, App::DocumentObject::getDocument(), and replaceobj::objs.
exportObjects() [2/2]
void Import::ExportOCAF2::exportObjects (std::vector< App::DocumentObject * > & objs, const char * name = nullptr)
setExportHiddenObject() [1/2]
void Import::ExportOCAF2::setExportHiddenObject (bool enable) inline
Definition at line 72 of file ExportOCAF2.h.
setExportHiddenObject() [2/2]
void Import::ExportOCAF2::setExportHiddenObject (bool enable) inline
Definition at line 247 of file ImportOCAF2.h.
setExportOptions() [1/2]
void Import::ExportOCAF2::setExportOptions (ExportOCAFOptions opts) inline
Definition at line 68 of file ExportOCAF2.h.
References src.Mod.PartDesign.fcgear.svggear::opts.
setExportOptions() [2/2]
void Import::ExportOCAF2::setExportOptions (ExportOCAFOptions opts) inline
Definition at line 243 of file ImportOCAF2.h.
References src.Mod.PartDesign.fcgear.svggear::opts.
setKeepPlacement() [1/2]
void Import::ExportOCAF2::setKeepPlacement (bool enable) inline
Definition at line 76 of file ExportOCAF2.h.
setKeepPlacement() [2/2]
void Import::ExportOCAF2::setKeepPlacement (bool enable) inline
Definition at line 251 of file ImportOCAF2.h.
The documentation for this class was generated from the following files:
ExportOCAF2.h
ImportOCAF2.h
ExportOCAF2.cpp