FreeCAD: FemGui::DlgSettingsFemMystranImp Class Reference
FemGui::DlgSettingsFemMystranImp Class Reference
#include <DlgSettingsFemMystranImp.h>
Public Member Functions
DlgSettingsFemMystranImp (QWidget *parent=nullptr)
~DlgSettingsFemMystranImp () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Slots
void onfileNameChanged (QString FileName)
Protected Member Functions
void saveSettings () override
void loadSettings () override
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
Definition at line 58 of file DlgSettingsFemMystranImp.h.
Constructor & Destructor Documentation
DlgSettingsFemMystranImp()
DlgSettingsFemMystranImp::DlgSettingsFemMystranImp (QWidget * parent = nullptr) explicit
Definition at line 36 of file DlgSettingsFemMystranImp.cpp.
References draftgeoutils.intersections::connect(), Gui::FileChooser::fileNameChanged(), and onfileNameChanged().
~DlgSettingsFemMystranImp()
DlgSettingsFemMystranImp::~DlgSettingsFemMystranImp () override default
Member Function Documentation
changeEvent()
void DlgSettingsFemMystranImp::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 67 of file DlgSettingsFemMystranImp.cpp.
References SCL.SimpleDataTypes::e.
loadSettings()
void DlgSettingsFemMystranImp::loadSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 57 of file DlgSettingsFemMystranImp.cpp.
onfileNameChanged
void DlgSettingsFemMystranImp::onfileNameChanged (QString FileName) protected slot
Definition at line 77 of file DlgSettingsFemMystranImp.cpp.
Referenced by DlgSettingsFemMystranImp().
saveSettings()
void DlgSettingsFemMystranImp::saveSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 50 of file DlgSettingsFemMystranImp.cpp.
The documentation for this class was generated from the following files:
DlgSettingsFemMystranImp.h
DlgSettingsFemMystranImp.cpp