FreeCAD: PartDesignGui::TaskFeatureParameters Class Reference
PartDesignGui::TaskFeatureParameters Class Reference
Convenience class to collect common methods for all SketchBased features.
#include <TaskFeatureParameters.h>
Public Member Functions
TaskFeatureParameters (PartDesignGui::ViewProvider *vp, QWidget *parent, const std::string &pixmapname, const QString &parname)
~TaskFeatureParameters () override=default
virtual void saveHistory ()
save field history
virtual void apply ()
apply changes made in the parameters input to the model via commands
void recomputeFeature ()
bool isUpdateBlocked () const
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Public Member Functions inherited from Gui::DocumentObserver
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
void attachDocument (Document *)
void detachDocument ()
Protected Slots
void onUpdateView (bool on)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Member Functions
template<typename T = PartDesignGui::ViewProvider>
T * getViewObject () const
template<typename T = App::DocumentObject>
T * getObject () const
Gui::Document * getGuiDocument () const
App::Document * getAppDocument () const
bool & getUpdateBlockRef ()
void setUpdateBlocked (bool value)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
Convenience class to collect common methods for all SketchBased features.
Definition at line 57 of file TaskFeatureParameters.h.
Constructor & Destructor Documentation
TaskFeatureParameters()
TaskFeatureParameters::TaskFeatureParameters (PartDesignGui::ViewProvider * vp, QWidget * parent, const std::string & pixmapname, const QString & parname)
Definition at line 47 of file TaskFeatureParameters.cpp.
References Gui::DocumentObserver::attachDocument(), toolbit-attributes::doc, and Gui::ViewProviderDocumentObject::getDocument().
~TaskFeatureParameters()
PartDesignGui::TaskFeatureParameters::~TaskFeatureParameters () override default
Member Function Documentation
apply()
virtual void PartDesignGui::TaskFeatureParameters::apply () inline virtual
apply changes made in the parameters input to the model via commands
Reimplemented in PartDesignGui::TaskRevolutionParameters, PartDesignGui::TaskHoleParameters, PartDesignGui::TaskHelixParameters, PartDesignGui::TaskPadParameters, and PartDesignGui::TaskPocketParameters.
Definition at line 90 of file TaskFeatureParameters.h.
References getObject().
getAppDocument()
App::Document* PartDesignGui::TaskFeatureParameters::getAppDocument () const inline protected
Definition at line 131 of file TaskFeatureParameters.h.
Referenced by PartDesignGui::TaskSketchBasedParameters::getFaceReference(), PartDesignGui::TaskSketchBasedParameters::objectNameByLabel(), PartDesignGui::TaskPipeParameters::referenceSelected(), and PartDesignGui::TaskSketchBasedParameters::setUpToFace().
getGuiDocument()
Gui::Document* PartDesignGui::TaskFeatureParameters::getGuiDocument () const inline protected
Definition at line 126 of file TaskFeatureParameters.h.
Referenced by PartDesignGui::TaskSketchBasedParameters::finishReferenceSelection(), PartDesignGui::TaskHelixParameters::finishReferenceSelection(), PartDesignGui::TaskPipeParameters::referenceSelected(), PartDesignGui::TaskSketchBasedParameters::startReferenceSelection(), and PartDesignGui::TaskHelixParameters::startReferenceSelection().
getObject()
template<typename T = App::DocumentObject> T* PartDesignGui::TaskFeatureParameters::getObject () const inline protected
Definition at line 115 of file TaskFeatureParameters.h.
Referenced by PartDesignGui::TaskPipeParameters::accept(), PartDesignGui::TaskHelixParameters::apply(), PartDesignGui::TaskRevolutionParameters::apply(), apply(), PartDesignGui::TaskExtrudeParameters::applyParameters(), PartDesignGui::TaskRevolutionParameters::onSelectionChanged(), PartDesignGui::TaskHelixParameters::onSelectionChanged(), recomputeFeature(), PartDesignGui::TaskPipeParameters::referenceSelected(), PartDesignGui::TaskPipeOrientation::referenceSelected(), PartDesignGui::TaskPipeScaling::referenceSelected(), and PartDesignGui::TaskHelixParameters::~TaskHelixParameters().
getUpdateBlockRef()
bool& PartDesignGui::TaskFeatureParameters::getUpdateBlockRef () inline protected
Definition at line 137 of file TaskFeatureParameters.h.
References Gui::ViewProviderDocumentObject::getObject().
Referenced by PartDesignGui::TaskRevolutionParameters::fillAxisCombo(), and PartDesignGui::TaskExtrudeParameters::fillDirectionCombo().
getViewObject()
template<typename T = PartDesignGui::ViewProvider> T* PartDesignGui::TaskFeatureParameters::getViewObject () const inline protected
Definition at line 108 of file TaskFeatureParameters.h.
Referenced by PartDesignGui::TaskHoleParameters::TaskHoleParameters().
isUpdateBlocked()
bool PartDesignGui::TaskFeatureParameters::isUpdateBlocked () const inline
Definition at line 94 of file TaskFeatureParameters.h.
onUpdateView
void TaskFeatureParameters::onUpdateView (bool on) protected slot
Definition at line 64 of file TaskFeatureParameters.cpp.
References recomputeFeature().
Referenced by PartDesignGui::TaskLoftParameters::TaskLoftParameters().
recomputeFeature()
void TaskFeatureParameters::recomputeFeature ()
Definition at line 70 of file TaskFeatureParameters.cpp.
References App::DocumentObject::getDocument(), getObject(), and App::Document::recomputeFeature().
Referenced by PartDesignGui::TaskSketchBasedParameters::onAddSelection(), PartDesignGui::TaskRevolutionParameters::onSelectionChanged(), PartDesignGui::TaskHelixParameters::onSelectionChanged(), onUpdateView(), and PartDesignGui::TaskSketchBasedParameters::setUpToFace().
saveHistory()
virtual void PartDesignGui::TaskFeatureParameters::saveHistory () inline virtual
save field history
Reimplemented in PartDesignGui::TaskExtrudeParameters.
Definition at line 88 of file TaskFeatureParameters.h.
setUpdateBlocked()
void PartDesignGui::TaskFeatureParameters::setUpdateBlocked (bool value) inline protected
Definition at line 142 of file TaskFeatureParameters.h.
Referenced by PartDesignGui::TaskRevolutionParameters::TaskRevolutionParameters().
The documentation for this class was generated from the following files:
TaskFeatureParameters.h
TaskFeatureParameters.cpp