FreeCAD: MeshGui::MeshFillHole Class Reference
MeshGui::MeshFillHole Class Reference
#include <MeshEditor.h>
Public Slots
void finishEditing ()
Public Member Functions
MeshFillHole (MeshHoleFiller &hf, Gui::View3DInventor *parent)
~MeshFillHole () override
void startEditing (ViewProviderMesh *)
Detailed Description
Display data of a mesh kernel.
Author
Werner Mayer
Definition at line 143 of file MeshEditor.h.
Constructor & Destructor Documentation
MeshFillHole()
MeshFillHole::MeshFillHole (MeshHoleFiller & hf, Gui::View3DInventor * parent)
Definition at line 449 of file MeshEditor.cpp.
References SCL.SimpleDataTypes::f.
~MeshFillHole()
MeshFillHole::~MeshFillHole () override
Definition at line 478 of file MeshEditor.cpp.
Member Function Documentation
finishEditing
void MeshFillHole::finishEditing () slot
Definition at line 511 of file MeshEditor.cpp.
References Gui::View3DInventor::getViewer(), Init::parent, and OfflineRenderingUtils::viewer().
startEditing()
void MeshFillHole::startEditing (MeshGui::ViewProviderMesh * vp)
Definition at line 486 of file MeshEditor.cpp.
References draftgeoutils.faces::bind(), Gui::coinRemoveAllChildren(), App::GetApplication(), Gui::ViewProviderDocumentObject::getObject(), Init::parent, App::Application::signalChangedObject, and OfflineRenderingUtils::viewer().
The documentation for this class was generated from the following files:
MeshEditor.h
MeshEditor.cpp