FreeCAD: Gui::OverlayGraphicsEffect Class Reference
Gui::OverlayGraphicsEffect Class Reference
#include <OverlayWidgets.h>
Public Member Functions
OverlayGraphicsEffect (QObject *parent)
void draw (QPainter *painter) override
QRectF boundingRectFor (const QRectF &rect) const override
void setSize (const QSize &size)
QSize size () const
void setOffset (const QPointF &offset)
QPointF offset () const
void setBlurRadius (qreal blurRadius)
qreal blurRadius () const
void setColor (const QColor &color)
QColor color () const
bool enabled () const
void setEnabled (bool enabled)
Detailed Description
Graphic effects for drawing shadow and outline of text on transparent background
Modified from https://stackoverflow.com/a/23752747
Definition at line 607 of file OverlayWidgets.h.
Constructor & Destructor Documentation
OverlayGraphicsEffect()
OverlayGraphicsEffect::OverlayGraphicsEffect (QObject * parent) explicit
Definition at line 2576 of file OverlayWidgets.cpp.
Member Function Documentation
blurRadius()
qreal Gui::OverlayGraphicsEffect::blurRadius () const inline
Definition at line 629 of file OverlayWidgets.h.
Referenced by draw(), and setBlurRadius().
boundingRectFor()
QRectF OverlayGraphicsEffect::boundingRectFor (const QRectF & rect) const override
Definition at line 2710 of file OverlayWidgets.cpp.
color()
QColor Gui::OverlayGraphicsEffect::color () const inline
Definition at line 632 of file OverlayWidgets.h.
Referenced by draw(), Path.Dressup.Gui.DogboneII.Marker::highlight(), Path.Dressup.Gui.Dogbone.Marker::highlight(), Path.Dressup.Gui.DogboneII.Marker::lowlight(), Path.Dressup.Gui.Dogbone.Marker::lowlight(), and setColor().
draw()
QT_END_NAMESPACE void OverlayGraphicsEffect::draw (QPainter * painter) override
Definition at line 2589 of file OverlayWidgets.cpp.
References blurRadius(), color(), src.Mod.AddonManager.NetworkManager::count, FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, Gui::getMainWindow(), SplineSurface::i, offset(), Init::parent, qt_blurImage(), Gui::MainWindow::showMessage(), size(), Sketcher::Vertical, src.Mod.PartDesign.fcgear.svggear::w, MovieTool::x, and MovieTool::y.
enabled()
bool Gui::OverlayGraphicsEffect::enabled () const inline
Definition at line 634 of file OverlayWidgets.h.
Referenced by setEnabled().
offset()
QPointF Gui::OverlayGraphicsEffect::offset () const inline
Definition at line 624 of file OverlayWidgets.h.
Referenced by draw(), Gui::OverlayTabWidget::setEffectOffsetX(), Gui::OverlayTabWidget::setEffectOffsetY(), and setOffset().
setBlurRadius()
void Gui::OverlayGraphicsEffect::setBlurRadius (qreal blurRadius) inline
Definition at line 626 of file OverlayWidgets.h.
References blurRadius().
Referenced by Gui::OverlayTabWidget::setEffectBlurRadius().
setColor()
void Gui::OverlayGraphicsEffect::setColor (const QColor & color) inline
Definition at line 631 of file OverlayWidgets.h.
References color().
Referenced by Gui::OverlayTabWidget::setEffectColor().
setEnabled()
void Gui::OverlayGraphicsEffect::setEnabled (bool enabled) inline
Definition at line 635 of file OverlayWidgets.h.
References enabled().
Referenced by Gui::OverlayTabWidget::OverlayTabWidget(), Gui::OverlayTabWidget::setOverlayMode(), Path.Dressup.Gui.Tags.HoldingTagMarker::setSelected(), and Gui::OverlayTabWidget::setState().
setOffset()
void Gui::OverlayGraphicsEffect::setOffset (const QPointF & offset) inline
Definition at line 621 of file OverlayWidgets.h.
References offset().
Referenced by ArchPipe._ArchPipeConnector::execute(), Gui::OverlayTabWidget::setEffectOffsetX(), and Gui::OverlayTabWidget::setEffectOffsetY().
setSize()
void Gui::OverlayGraphicsEffect::setSize (const QSize & size) inline
Definition at line 616 of file OverlayWidgets.h.
References size().
Referenced by Gui::OverlayTabWidget::setEffectHeight(), and Gui::OverlayTabWidget::setEffectWidth().
size()
QSize Gui::OverlayGraphicsEffect::size () const inline
Definition at line 619 of file OverlayWidgets.h.
Referenced by Path.Post.Utils.GCodeEditorDialog::done(), draw(), Gui::OverlayTabWidget::setEffectHeight(), Gui::OverlayTabWidget::setEffectWidth(), and setSize().
The documentation for this class was generated from the following files:
OverlayWidgets.h
OverlayWidgets.cpp