FreeCAD: TechDrawGui::PathBuilder Class Reference
TechDrawGui::PathBuilder Class Reference
#include <PathBuilder.h>
Public Member Functions
PathBuilder ()
PathBuilder (QGIViewPart *qvp)
~PathBuilder ()=default
QPainterPath geomToPainterPath (TechDraw::BaseGeomPtr baseGeom, double rot) const
void pathArc (QPainterPath &path, double rx, double ry, double x_axis_rotation, bool large_arc_flag, bool sweep_flag, double x, double y, double curx, double cury) const
void pathArcSegment (QPainterPath &path, double xc, double yc, double th0, double th1, double rx, double ry, double xAxisRotation) const
Detailed Description
Definition at line 57 of file PathBuilder.h.
Constructor & Destructor Documentation
PathBuilder() [1/2]
TechDrawGui::PathBuilder::PathBuilder () inline
Definition at line 79 of file PathBuilder.h.
PathBuilder() [2/2]
TechDrawGui::PathBuilder::PathBuilder (QGIViewPart * qvp) inline
Definition at line 80 of file PathBuilder.h.
~PathBuilder()
TechDrawGui::PathBuilder::~PathBuilder () default
Member Function Documentation
geomToPainterPath()
QPainterPath PathBuilder::geomToPainterPath (TechDraw::BaseGeomPtr baseGeom, double rot) const
Definition at line 37 of file PathBuilder.cpp.
References TechDraw::ARCOFCIRCLE, TechDraw::ARCOFELLIPSE, TechDraw::BEZIER, TechDraw::BSPLINE, TechDraw::CIRCLE, Base::Console(), KDL::cos(), TechDraw::ELLIPSE, Base::ConsoleSingleton::Error(), TechDraw::GENERIC, KDL::sin(), MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, and Base::Vector3< float_type >::y.
pathArc()
void PathBuilder::pathArc (QPainterPath & path, double rx, double ry, double x_axis_rotation, bool large_arc_flag, bool sweep_flag, double x, double y, double curx, double cury) const
Definition at line 265 of file PathBuilder.cpp.
References NavigationIndicatorGui::a10, ArchCommands::check(), SplineSurface::i, M_PI, MovieTool::x, and MovieTool::y.
pathArcSegment()
void PathBuilder::pathArcSegment (QPainterPath & path, double xc, double yc, double th0, double th1, double rx, double ry, double xAxisRotation) const
Definition at line 344 of file PathBuilder.cpp.
References NavigationIndicatorGui::a10, and InitGui::t.
The documentation for this class was generated from the following files:
PathBuilder.h
PathBuilder.cpp