FreeCAD: Unit.cpp File Reference
Unit.cpp File Reference
#include "PreCompiled.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <limits>
#include <sstream>
#include <utility>
#include "Unit.h"
#include "Exception.h"
#include "Quantity.h"
Classes
struct UnitSignature
Functions
static uint32_t sigVal (const std::string &op, int length, int mass, int time, int electricCurrent, int thermodynamicTemperature, int amountOfSubstance, int luminousIntensity, int angle)
Variables
constexpr int UnitSignatureLengthBits = 4
constexpr int UnitSignatureMassBits = 4
constexpr int UnitSignatureTimeBits = 4
constexpr int UnitSignatureElectricCurrentBits = 4
constexpr int UnitSignatureThermodynamicTemperatureBits = 4
constexpr int UnitSignatureAmountOfSubstanceBits = 4
constexpr int UnitSignatureLuminousIntensityBits = 4
constexpr int UnitSignatureAngleBits = 4
Function Documentation
sigVal()
static uint32_t sigVal (const std::string & op, int length, int mass, int time, int electricCurrent, int thermodynamicTemperature, int amountOfSubstance, int luminousIntensity, int angle) inline static
Definition at line 61 of file Unit.cpp.
References UnitSignature::AmountOfSubstance, UnitSignature::Angle, UnitSignature::ElectricCurrent, UnitSignature::Length, UnitSignature::LuminousIntensity, UnitSignature::Mass, UnitSignature::ThermodynamicTemperature, UnitSignature::Time, UnitSignatureAmountOfSubstanceBits, UnitSignatureAngleBits, UnitSignatureElectricCurrentBits, UnitSignatureLengthBits, UnitSignatureLuminousIntensityBits, UnitSignatureMassBits, UnitSignatureThermodynamicTemperatureBits, and UnitSignatureTimeBits.
Referenced by Base::Unit::cbrt(), Base::Unit::operator*(), Base::Unit::operator/(), Base::Unit::pow(), Base::Unit::sqrt(), and Base::Unit::Unit().
Variable Documentation
UnitSignatureAmountOfSubstanceBits
constexpr int UnitSignatureAmountOfSubstanceBits = 4 constexpr
Definition at line 46 of file Unit.cpp.
Referenced by sigVal().
UnitSignatureAngleBits
constexpr int UnitSignatureAngleBits = 4 constexpr
Definition at line 48 of file Unit.cpp.
Referenced by sigVal().
UnitSignatureElectricCurrentBits
constexpr int UnitSignatureElectricCurrentBits = 4 constexpr
Definition at line 44 of file Unit.cpp.
Referenced by sigVal().
UnitSignatureLengthBits
constexpr int UnitSignatureLengthBits = 4 constexpr
Definition at line 41 of file Unit.cpp.
Referenced by sigVal().
UnitSignatureLuminousIntensityBits
constexpr int UnitSignatureLuminousIntensityBits = 4 constexpr
Definition at line 47 of file Unit.cpp.
Referenced by sigVal().
UnitSignatureMassBits
constexpr int UnitSignatureMassBits = 4 constexpr
Definition at line 42 of file Unit.cpp.
Referenced by sigVal().
UnitSignatureThermodynamicTemperatureBits
constexpr int UnitSignatureThermodynamicTemperatureBits = 4 constexpr
Definition at line 45 of file Unit.cpp.
Referenced by sigVal().
UnitSignatureTimeBits
constexpr int UnitSignatureTimeBits = 4 constexpr
Definition at line 43 of file Unit.cpp.
Referenced by sigVal().