FreeCAD: Base::FileInfo Class Reference
Base::FileInfo Class Reference
#include <FileInfo.h>
Public Types
enum Permissions { WriteOnly = 0x01, ReadOnly = 0x02, ReadWrite = 0x03 }
Public Member Functions
FileInfo (const char *fileName="")
Construction.
FileInfo (const std::string &fileName)
void setFile (const char *name)
Set a new file name.
void setFile (const std::string &name)
Set a new file name.
extraction of information
std::string filePath () const
Returns the file name, including the path (which may be absolute or relative).
std::string dirPath () const
Returns the dir path name (which may be absolute or relative).
std::string fileName () const
Returns the name of the file, excluding the path, including the extension.
std::string fileNamePure () const
Returns the name of the file, excluding the path and the extension.
std::wstring toStdWString () const
std::string extension () const
std::string completeExtension () const
bool hasExtension (const char *Ext) const
Checks for a special extension, NOT case sensitive.
bool hasExtension (std::initializer_list< const char * > Exts) const
Checks for any of the special extensions, NOT case sensitive.
methods to test the status of the file or dir
bool exists () const
Does the file exist?
bool isReadable () const
Checks if the file exist and is readable.
bool isWritable () const
Checks if the file exist and is writable.
bool setPermissions (Permissions)
Tries to set the file permission.
bool isFile () const
Checks if it is a file (not a directory)
bool isDir () const
Checks if it is a directory (not a file)
unsigned int size () const
The size of the file.
TimeInfo lastModified () const
Returns the time when the file was last modified.
TimeInfo lastRead () const
Returns the time when the file was last read (accessed).
Directory management
bool createDirectory () const
Creates a directory. Returns true if successful; otherwise returns false.
bool createDirectories () const
std::vector< Base::FileInfo > getDirectoryContent () const
Get a list of the directory content.
bool deleteDirectory () const
Delete an empty directory.
bool deleteDirectoryRecursive () const
Delete a directory and all its content.
bool deleteFile () const
Delete the file.
bool renameFile (const char *NewName)
Rename the file.
bool copyTo (const char *NewName) const
Rename the file.
Tools
static std::string getTempFileName (const char *FileName=nullptr, const char *path=nullptr)
Get a unique File Name in the given or (if 0) in the temp path.
static const std::string & getTempPath ()
Get the path to the dir which is considered to temp files.
static std::string pathToString (const boost::filesystem::path &path)
Convert from filesystem path to string.
static boost::filesystem::path stringToPath (const std::string &str)
Convert from string to filesystem path.
Detailed Description
File name unification This class handles everything related to file names the file names are internal generally UTF-8 encoded on all platforms.
Definition at line 72 of file FileInfo.h.
Member Enumeration Documentation
Permissions
enum Base::FileInfo::Permissions
Enumerator
WriteOnly
ReadOnly
ReadWrite
Definition at line 75 of file FileInfo.h.
Constructor & Destructor Documentation
FileInfo() [1/2]
FileInfo::FileInfo (const char * fileName = "") explicit
Construction.
Definition at line 97 of file FileInfo.cpp.
References fileName(), and setFile().
Referenced by getDirectoryContent().
FileInfo() [2/2]
FileInfo::FileInfo (const std::string & fileName) explicit
Definition at line 102 of file FileInfo.cpp.
References fileName(), and setFile().
Member Function Documentation
completeExtension()
std::string FileInfo::completeExtension () const
Returns the complete extension of the file. The complete extension consists of all characters in the file after (but not including) the first '.' character.
FileInfo fi("/tmp/archive.tar.gz");
ext = fi.completeExtension();   // ext = "tar.gz"
Definition at line 315 of file FileInfo.cpp.
References RobotExample::pos.
copyTo()
bool FileInfo::copyTo (const char * NewName) const
Rename the file.
Definition at line 552 of file FileInfo.cpp.
References DrawingExample::file, and toStdWString().
Referenced by TechDraw::DrawUtil::copyFile(), and App::PropertyFileIncluded::Paste().
createDirectories()
bool FileInfo::createDirectories () const
Creates a directory and all its parent directories. Returns true if successful; otherwise returns false.
Definition at line 583 of file FileInfo.cpp.
References src.Mod.Test.testPathArray::path, and stringToPath().
Referenced by App::Document::onChanged().
createDirectory()
bool FileInfo::createDirectory () const
Creates a directory. Returns true if successful; otherwise returns false.
Definition at line 571 of file FileInfo.cpp.
References toStdWString().
Referenced by Gui::AutoSaver::slotCreateDocument(), Gui::RecoveryWriter::writeFiles(), and Base::FileWriter::writeFiles().
deleteDirectory()
bool FileInfo::deleteDirectory () const
Delete an empty directory.
Definition at line 598 of file FileInfo.cpp.
References isDir(), src.Mod.AddonManager.addonmanager_utilities::rmdir(), and toStdWString().
Referenced by deleteDirectoryRecursive().
deleteDirectoryRecursive()
bool FileInfo::deleteDirectoryRecursive () const
Delete a directory and all its content.
Definition at line 613 of file FileInfo.cpp.
References deleteDirectory(), getDirectoryContent(), isDir(), and ReadWrite.
Referenced by App::Document::~Document().
deleteFile()
bool FileInfo::deleteFile () const
Delete the file.
Definition at line 517 of file FileInfo.cpp.
References toStdWString().
Referenced by StdCmdDuplicateSelection::activated(), Gui::MainWindow::closeEvent(), TechDrawGui::TaskActiveView::createActiveView(), App::Document::importLinks(), MeshPartGui::Mesh2ShapeGmsh::loadOutput(), MeshGui::RemeshGmsh::loadOutput(), App::PropertyFileIncluded::Paste(), App::ProjectFile::readInputFile(), App::ProjectFile::replaceProjectFile(), Fem::FemMesh::RestoreDocFile(), Fem::PropertyPostDataObject::RestoreDocFile(), Fem::FemMesh::SaveDocFile(), Fem::PropertyPostDataObject::SaveDocFile(), App::PropertyFileIncluded::setValue(), and MeshCore::ZipFixer::~ZipFixer().
dirPath()
std::string FileInfo::dirPath () const
Returns the dir path name (which may be absolute or relative).
Definition at line 260 of file FileInfo.cpp.
Referenced by Import::ImportOCAF2::ImportOCAF2(), MeshCore::MeshInput::LoadOBJ(), App::VRMLObject::onChanged(), App::PropertyFileIncluded::Paste(), MeshCore::MeshOutput::SaveOBJ(), Import::ImportOCAF2::setMode(), App::PropertyFileIncluded::setValue(), and Mesh::Exporter::throwIfNoPermission().
exists()
bool FileInfo::exists () const
Does the file exist?
Definition at line 340 of file FileInfo.cpp.
References F_OK, and toStdWString().
Referenced by Gui::ViewProviderVRMLObject::addResource(), Gui::MainWindow::closeEvent(), TechDrawGui::TaskActiveView::createActiveView(), ArchReference.ArchReference::getFile(), App::PropertyFileIncluded::getUniqueFileName(), Part::ImportStepParts(), isDir(), isFile(), lastModified(), lastRead(), MeshCore::MeshInput::LoadAny(), Drawing::FeaturePage::onChanged(), App::Document::onChanged(), Drawing::FeaturePage::onDocumentRestored(), App::Application::openDocumentPrivate(), App::PropertyFileIncluded::Paste(), Import::StepShape::read(), App::ProjectFile::readInputFile(), App::PropertyFileIncluded::RestoreDocFile(), App::PropertyFileIncluded::Save(), MeshCore::MeshOutput::SaveAny(), App::VRMLObject::SaveDocFile(), App::PropertyFileIncluded::setValue(), size(), Gui::ApplicationPy::sLoadFile(), and Mesh::Exporter::throwIfNoPermission().
extension()
std::string FileInfo::extension () const
Returns the extension of the file. The extension consists of all characters in the file after (but not including) the last '.' character.
FileInfo fi("/tmp/archive.tar.gz");
ext = fi.extension();   // ext = "gz"
Definition at line 306 of file FileInfo.cpp.
References RobotExample::pos.
Referenced by Gui::Application::exportTo(), Base::Writer::getUniqueFileName(), hasExtension(), Gui::Application::importFrom(), Gui::Application::open(), App::Application::processCmdLineFiles(), Part::PropertyTopoShapeList::RestoreDocFile(), Fem::PropertyPostDataObject::RestoreDocFile(), Part::PropertyTopoShapeList::SaveDocFile(), App::PropertyFileIncluded::setValue(), and Gui::ApplicationPy::sLoadFile().
fileName()
std::string FileInfo::fileName () const
Returns the name of the file, excluding the path, including the extension.
Definition at line 255 of file FileInfo.cpp.
Referenced by Drawing::FeaturePage::execute(), Mesh::ExporterAMF::ExporterAMF(), FileInfo(), fileNamePure(), Drawing::FeaturePage::getEditableTextsFromTemplate(), Base::FileException::getFileName(), Base::FileException::getPyObject(), Drawing::FeaturePage::onDocumentRestored(), pagesize(), App::PropertyFileIncluded::Paste(), TechDrawGui::QGSPage::postProcessXml(), and App::PropertyFileIncluded::setValue().
fileNamePure()
std::string FileInfo::fileNamePure () const
Returns the name of the file, excluding the path and the extension.
Definition at line 282 of file FileInfo.cpp.
References fileName(), and RobotExample::pos.
Referenced by Base::Writer::getUniqueFileName(), Part::ImportIgesParts(), Part::ImportStepParts(), App::Application::openDocumentPrivate(), Fem::FemMesh::read(), Part::PropertyTopoShapeList::RestoreDocFile(), Gui::ApplicationPy::sAddCommand(), Mesh::MeshObject::save(), App::Document::saveAs(), Part::PropertyTopoShapeList::SaveDocFile(), App::PropertyFileIncluded::setValue(), and Fem::FemMesh::write().
filePath()
std::string FileInfo::filePath () const
Returns the file name, including the path (which may be absolute or relative).
Definition at line 250 of file FileInfo.cpp.
Referenced by App::Application::closeDocument(), App::PropertyFileIncluded::Copy(), Gui::MainWindow::createMimeDataFromSelection(), Drawing::FeaturePage::execute(), Mesh::ExporterAMF::ExporterAMF(), Gui::Application::exportTo(), App::ProjectFile::extractInputFile(), Base::FileException::FileException(), App::Application::getDocumentByPath(), Drawing::FeaturePage::getEditableTextsFromTemplate(), TechDraw::LineGenerator::getLineDescriptions(), CDxfWrite::getPlateFile(), App::PropertyFileIncluded::getUniqueFileName(), Gui::Application::importFrom(), App::Document::onChanged(), Drawing::FeaturePage::onDocumentRestored(), Gui::Application::open(), Base::ofstream::open(), Base::ifstream::open(), App::Application::openDocumentPrivate(), Gui::SoU3DVectorOutput::openFile(), Gui::SoSVGVectorOutput::openFile(), pagesize(), App::PropertyFileIncluded::Paste(), Import::ReaderIges::read(), Import::ReaderGltf::read(), Import::ReaderStep::read(), Fem::FemPostPipeline::read(), Fem::FemMesh::read(), Part::TopoShape::read(), Fem::FemMesh::RestoreDocFile(), Fem::PropertyPostDataObject::RestoreDocFile(), Gui::ApplicationPy::sAddCommand(), App::PropertyFileIncluded::Save(), Fem::FemMesh::SaveDocFile(), Fem::PropertyPostDataObject::SaveDocFile(), App::PropertyFileIncluded::setValue(), Fem::FemMesh::write(), Part::TopoShape::write(), MeshGui::RemeshGmsh::writeProject(), and Base::XMLReader::XMLReader().
getDirectoryContent()
std::vector< Base::FileInfo > FileInfo::getDirectoryContent () const
Get a list of the directory content.
Definition at line 642 of file FileInfo.cpp.
References FileInfo(), and toStdWString().
Referenced by deleteDirectoryRecursive(), and TechDraw::LineGenerator::getAvailableLineStandards().
getTempFileName()
std::string FileInfo::getTempFileName (const char * FileName = nullptr, const char * path = nullptr) static
Get a unique File Name in the given or (if 0) in the temp path.
Definition at line 141 of file FileInfo.cpp.
References DrawingExample::file, getTempPath(), Path.Post.scripts.refactored_centroid_post::str, and SurfaceTests.TestBlendCurve::vec.
Referenced by TechDrawGui::TaskActiveView::createActiveView(), App::ProjectFile::extractInputFile(), App::PropertyFileIncluded::getExchangeTempFile(), App::Application::getTempFileName(), and MeshCore::ZipFixer::ZipFixer().
getTempPath()
const std::string & FileInfo::getTempPath () static
Get the path to the dir which is considered to temp files.
Definition at line 107 of file FileInfo.cpp.
References isDir().
Referenced by getTempFileName().
hasExtension() [1/2]
bool FileInfo::hasExtension (const char * Ext) const
Checks for a special extension, NOT case sensitive.
Definition at line 324 of file FileInfo.cpp.
References extension().
Referenced by Fem::FemPostPipeline::canRead(), Gui::View3DInventorViewer::dumpToFile(), MeshCore::MeshInput::getFormat(), Gui::Application::importFrom(), TechDraw::DrawHatch::isBitmapHatch(), TechDraw::DrawHatch::isSvgHatch(), Points::PointsAlgos::Load(), MeshCore::MeshInput::LoadAny(), TechDraw::DrawViewSection::makeLineSets(), Gui::Application::open(), Fem::FemPostPipeline::read(), Fem::FemMesh::read(), Part::TopoShape::read(), Part::PropertyTopoShapeList::RestoreDocFile(), Part::PropertyPartShape::RestoreDocFile(), Part::PropertyTopoShapeList::SaveDocFile(), Gui::View3DInventorPy::saveVectorGraphic(), Fem::FemMesh::write(), Part::TopoShape::write(), and Gui::SoFCDB::writeToFile().
hasExtension() [2/2]
bool FileInfo::hasExtension (std::initializer_list< const char * > Exts) const
Checks for any of the special extensions, NOT case sensitive.
Definition at line 333 of file FileInfo.cpp.
References create_qrc::ext.
isDir()
bool FileInfo::isDir () const
Checks if it is a directory (not a file)
Definition at line 419 of file FileInfo.cpp.
References exists(), and toStdWString().
Referenced by deleteDirectory(), deleteDirectoryRecursive(), and getTempPath().
isFile()
bool FileInfo::isFile () const
Checks if it is a file (not a directory)
Definition at line 392 of file FileInfo.cpp.
References exists(), and toStdWString().
Referenced by MeshCore::MeshInput::LoadAny(), and Gui::ApplicationPy::sLoadFile().
isReadable()
bool FileInfo::isReadable () const
Checks if the file exist and is readable.
Definition at line 350 of file FileInfo.cpp.
References R_OK, and toStdWString().
Referenced by TechDraw::DrawUtil::copyFile(), TechDraw::DrawParametricTemplate::execute(), Part::ImportBrep::execute(), Part::ImportIges::execute(), Part::CurveNet::execute(), Part::ImportStep::execute(), Drawing::FeaturePage::execute(), TechDraw::DrawGeomHatch::getDecodedSpecsFromFile(), Drawing::FeaturePage::getEditableTextsFromTemplate(), CDxfWrite::getPlateFile(), Points::PointsAlgos::Load(), MeshCore::MeshInput::LoadAny(), TechDraw::DrawViewSection::makeLineSets(), pagesize(), Fem::FemPostPipeline::read(), Fem::FemMesh::read(), Part::TopoShape::read(), TechDraw::DrawHatch::replaceFileIncluded(), TechDraw::DrawTileWeld::replaceFileIncluded(), TechDraw::DrawSVGTemplate::replaceFileIncluded(), TechDraw::DrawViewImage::replaceImageIncluded(), TechDraw::DrawGeomHatch::replacePatIncluded(), TechDraw::DrawViewSection::replacePatIncluded(), TechDraw::DrawViewSection::replaceSvgIncluded(), and TechDrawGui::PreferencesGui::weldingDirectory().
isWritable()
bool FileInfo::isWritable () const
Checks if the file exist and is writable.
Definition at line 360 of file FileInfo.cpp.
References toStdWString(), and W_OK.
Referenced by App::PropertyFileIncluded::RestoreDocFile(), MeshCore::MeshOutput::SaveAny(), and Mesh::Exporter::throwIfNoPermission().
lastModified()
TimeInfo FileInfo::lastModified () const
Returns the time when the file was last modified.
Definition at line 473 of file FileInfo.cpp.
References exists(), Base::TimeInfo::null(), Base::TimeInfo::setTime_t(), and toStdWString().
lastRead()
TimeInfo FileInfo::lastRead () const
Returns the time when the file was last read (accessed).
Definition at line 495 of file FileInfo.cpp.
References exists(), Base::TimeInfo::null(), Base::TimeInfo::setTime_t(), and toStdWString().
pathToString()
std::string FileInfo::pathToString (const boost::filesystem::path & path) static
Convert from filesystem path to string.
Definition at line 222 of file FileInfo.cpp.
Referenced by Gui::PreferencePack::apply(), Gui::PreferencePack::PreferencePack(), Gui::PreferencePackManager::save(), scanForTemplateFiles(), scanForTemplateFolders(), Gui::Dialog::DlgPreferencePackManagementImp::showEvent(), and Gui::PreferencePackManager::templateFiles().
renameFile()
bool FileInfo::renameFile (const char * NewName)
Rename the file.
Definition at line 529 of file FileInfo.cpp.
References toStdWString().
Referenced by App::Document::onChanged(), App::PropertyFileIncluded::Paste(), and App::ProjectFile::replaceProjectFile().
setFile() [1/2]
void FileInfo::setFile (const char * name)
Set a new file name.
Definition at line 232 of file FileInfo.cpp.
Referenced by Drawing::FeaturePage::execute(), FileInfo(), Drawing::FeaturePage::getEditableTextsFromTemplate(), App::PropertyFileIncluded::getUniqueFileName(), Base::Writer::getUniqueFileName(), MeshCore::MeshInput::LoadOBJ(), Drawing::FeaturePage::onDocumentRestored(), pagesize(), App::PropertyFileIncluded::Paste(), App::ProjectFile::replaceProjectFile(), App::VRMLObject::SaveDocFile(), MeshCore::MeshOutput::SaveOBJ(), Base::FileException::setFileName(), and App::PropertyFileIncluded::setValue().
setFile() [2/2]
void Base::FileInfo::setFile (const std::string & name) inline
Set a new file name.
Definition at line 88 of file FileInfo.h.
setPermissions()
bool FileInfo::setPermissions (Permissions perms)
Tries to set the file permission.
Definition at line 370 of file FileInfo.cpp.
References ReadOnly, toStdWString(), and WriteOnly.
Referenced by App::PropertyFileIncluded::Copy(), App::PropertyFileIncluded::Paste(), App::PropertyFileIncluded::Restore(), App::PropertyFileIncluded::RestoreDocFile(), and App::PropertyFileIncluded::setValue().
size()
unsigned int FileInfo::size () const
The size of the file.
Definition at line 451 of file FileInfo.cpp.
References exists(), and toStdWString().
Referenced by Path.Post.Utils.GCodeEditorDialog::done().
stringToPath()
boost::filesystem::path FileInfo::stringToPath (const std::string & str) static
Convert from string to filesystem path.
Definition at line 211 of file FileInfo.cpp.
References src.Mod.Test.testPathArray::path, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by createDirectories(), getResourcePrefPacksPath(), getSavedPrefPacksPath(), Gui::PreferencePackManager::modPaths(), and Gui::PreferencePackManager::templateFiles().
toStdWString()
std::wstring FileInfo::toStdWString () const
Convert the path name into a UTF-16 encoded wide string format.
Note
: Use this function on Windows only.
Definition at line 294 of file FileInfo.cpp.
Referenced by copyTo(), createDirectory(), deleteDirectory(), deleteFile(), exists(), getDirectoryContent(), isDir(), isFile(), isReadable(), isWritable(), lastModified(), lastRead(), Base::ofstream::open(), Base::ifstream::open(), Gui::SoU3DVectorOutput::openFile(), Gui::SoSVGVectorOutput::openFile(), renameFile(), Gui::PythonDebugger::runFile(), Base::InterpreterSingleton::runFile(), setPermissions(), and size().
The documentation for this class was generated from the following files:
FileInfo.h
FileInfo.cpp