FreeCAD: Wm4::Mapper2< Real > Class Template Reference
Wm4::Mapper2< Real > Class Template Reference
#include <Wm4Mapper2.h>
Public Member Functions
Mapper2 (int iVQuantity, const Vector2< Real > *akVertex, Real fEpsilon)
~Mapper2 ()
const Vector2< Real > & GetMin () const
const Vector2< Real > & GetMax () const
Real GetMaxRange () const
int GetDimension () const
const Vector2< Real > & GetOrigin () const
const Vector2< Real > & GetDirection (int i) const
int GetExtremeIndex (int i) const
bool GetExtremeCCW () const
Detailed Description
template<class Real>
class Wm4::Mapper2< Real >
Definition at line 27 of file Wm4Mapper2.h.
Constructor & Destructor Documentation
Mapper2()
template<class Real > Wm4::Mapper2< Real >::Mapper2 (int iVQuantity, const Vector2< Real > * akVertex, Real fEpsilon)
~Mapper2()
template<class Real > Wm4::Mapper2< Real >::~Mapper2 ()
Member Function Documentation
GetDimension()
template<class Real > int Wm4::Mapper2< Real >::GetDimension () const
Referenced by Wm4::ConvexHull2< Real >::ConvexHull2(), and Wm4::Delaunay2< Real >::Delaunay2().
GetDirection()
template<class Real > const Vector2<Real>& Wm4::Mapper2< Real >::GetDirection (int i) const
Referenced by Wm4::ConvexHull2< Real >::ConvexHull2(), and Wm4::Delaunay2< Real >::Delaunay2().
GetExtremeCCW()
template<class Real > bool Wm4::Mapper2< Real >::GetExtremeCCW () const
Referenced by Wm4::ConvexHull2< Real >::ConvexHull2().
GetExtremeIndex()
template<class Real > int Wm4::Mapper2< Real >::GetExtremeIndex (int i) const
Referenced by Wm4::ConvexHull2< Real >::ConvexHull2().
GetMax()
template<class Real > const Vector2<Real>& Wm4::Mapper2< Real >::GetMax () const
Referenced by Wm4::Delaunay2< Real >::Delaunay2().
GetMaxRange()
template<class Real > Real Wm4::Mapper2< Real >::GetMaxRange () const
Referenced by Wm4::ConvexHull2< Real >::ConvexHull2(), and Wm4::Delaunay2< Real >::Delaunay2().
GetMin()
template<class Real > const Vector2<Real>& Wm4::Mapper2< Real >::GetMin () const
Referenced by Wm4::ConvexHull2< Real >::ConvexHull2(), and Wm4::Delaunay2< Real >::Delaunay2().
GetOrigin()
template<class Real > const Vector2<Real>& Wm4::Mapper2< Real >::GetOrigin () const
Referenced by Wm4::ConvexHull2< Real >::ConvexHull2(), and Wm4::Delaunay2< Real >::Delaunay2().
The documentation for this class was generated from the following file:
Wm4Mapper2.h