FreeCAD: DocumentObject.cpp File Reference
DocumentObject.cpp File Reference
#include "PreCompiled.h"
#include <stack>
#include <App/DocumentObjectPy.h>
#include <Base/Console.h>
#include <Base/Matrix.h>
#include <Base/Tools.h>
#include <Base/Writer.h>
#include "Application.h"
#include "ElementNamingUtils.h"
#include "Document.h"
#include "DocumentObject.h"
#include "DocumentObjectExtension.h"
#include "DocumentObjectGroup.h"
#include "GeoFeatureGroupExtension.h"
#include "Link.h"
#include "ObjectIdentifier.h"
#include "PropertyExpressionEngine.h"
#include "PropertyLinks.h"
Functions
TYPESYSTEM_SOURCE_P (App::DocumentObject) const App
void _getOutListRecursive (std::set< DocumentObject * > &objSet, const DocumentObject *obj, const DocumentObject *checkObj, int depth)
bool _isInInListRecursive (const DocumentObject *act, const DocumentObject *checkObj, int depth)
bool _isInOutListRecursive (const DocumentObject *act, const DocumentObject *checkObj, int depth)
Function Documentation
_getOutListRecursive()
void _getOutListRecursive (std::set< DocumentObject * > & objSet, const DocumentObject * obj, const DocumentObject * checkObj, int depth)
Definition at line 579 of file DocumentObject.cpp.
References App::DocumentObject::getOutList().
_isInInListRecursive()
bool _isInInListRecursive (const DocumentObject * act, const DocumentObject * checkObj, int depth)
Definition at line 614 of file DocumentObject.cpp.
References App::DocumentObject::getInList().
_isInOutListRecursive()
bool _isInOutListRecursive (const DocumentObject * act, const DocumentObject * checkObj, int depth)
Definition at line 661 of file DocumentObject.cpp.
References App::DocumentObject::getOutList().
TYPESYSTEM_SOURCE_P()
TYPESYSTEM_SOURCE_P (App::DocumentObject) const
Definition at line 58 of file DocumentObject.cpp.
References ADD_PROPERTY, ADD_PROPERTY_TYPE, App::Property::Output, App::Prop_Hidden, and App::Prop_Output.