FreeCAD: TechDrawGui::TaskDlgActiveView Class Reference
TechDrawGui::TaskDlgActiveView Class Reference
#include <TaskActiveView.h>
Public Member Functions
TaskDlgActiveView (TechDraw::DrawPage *pageFeat)
~TaskDlgActiveView () override
void open () override
is called the TaskView when the dialog is opened
void clicked (int) override
is called by the framework if an button is clicked which has no accept or reject role
bool accept () override
is called by the framework if the dialog is accepted (Ok)
bool reject () override
is called by the framework if the dialog is rejected (Cancel)
void helpRequested () override
is called by the framework if the user presses the help button
bool isAllowedAlterDocument () const override
void update ()
void modifyStandardButtons (QDialogButtonBox *box) override
Public Member Functions inherited from Gui::TaskView::TaskDialog
TaskDialog ()
~TaskDialog () override
QWidget * addTaskBox (QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBox (const QPixmap &icon, QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBoxWithoutHeader (QWidget *widget)
void setButtonPosition (ButtonPosition p)
ButtonPosition buttonPosition () const
const std::vector< QWidget * > & getDialogContent () const
bool canClose () const
virtual QDialogButtonBox::StandardButtons getStandardButtons () const
tells the framework which buttons are wished for the dialog
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
bool isEscapeButtonEnabled () const
void setAutoCloseOnTransactionChange (bool on)
bool isAutoCloseOnTransactionChange () const
void setAutoCloseOnDeletedDocument (bool on)
bool isAutoCloseOnDeletedDocument () const
const std::string & getDocumentName () const
void setDocumentName (const std::string &doc)
void setAutoCloseOnClosedView (bool on)
bool isAutoCloseOnClosedView () const
void associateToObject3dView (App::DocumentObject *obj)
const Gui::MDIView * getAssociatedView () const
void setAssociatedView (const Gui::MDIView *view)
virtual bool isAllowedAlterView () const
virtual bool isAllowedAlterSelection () const
virtual bool needsFullSpace () const
virtual void closed ()
is called by the framework when the dialog is closed
virtual void autoClosedOnTransactionChange ()
virtual void autoClosedOnDeletedDocument ()
virtual void autoClosedOnClosedView ()
void emitDestructionSignal ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from Gui::TaskView::TaskDialog
QPointer< QDialogButtonBox > buttonBox
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Detailed Description
Definition at line 91 of file TaskActiveView.h.
Constructor & Destructor Documentation
TaskDlgActiveView()
TaskDlgActiveView::TaskDlgActiveView (TechDraw::DrawPage * pageFeat) explicit
Definition at line 292 of file TaskActiveView.cpp.
References Gui::BitmapFactory(), Gui::TaskView::TaskDialog::Content, and QSint::ActionGroup::groupLayout().
~TaskDlgActiveView()
TaskDlgActiveView::~TaskDlgActiveView () override
Definition at line 301 of file TaskActiveView.cpp.
Member Function Documentation
accept()
bool TaskDlgActiveView::accept () override virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 320 of file TaskActiveView.cpp.
References TechDrawGui::TaskActiveView::accept().
clicked()
void TaskDlgActiveView::clicked (int) override virtual
is called by the framework if an button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 318 of file TaskActiveView.cpp.
helpRequested()
void TechDrawGui::TaskDlgActiveView::helpRequested () inline override virtual
is called by the framework if the user presses the help button
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 109 of file TaskActiveView.h.
isAllowedAlterDocument()
bool TechDrawGui::TaskDlgActiveView::isAllowedAlterDocument () const inline override virtual
Indicates whether this task dialog allows other commands to modify the document while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 110 of file TaskActiveView.h.
modifyStandardButtons()
void TaskDlgActiveView::modifyStandardButtons (QDialogButtonBox * box) override virtual
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 308 of file TaskActiveView.cpp.
References MengerSponge::box, and TechDrawGui::TaskActiveView::saveButtons().
open()
void TaskDlgActiveView::open () override virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 316 of file TaskActiveView.cpp.
reject()
bool TaskDlgActiveView::reject () override virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 326 of file TaskActiveView.cpp.
References TechDrawGui::TaskActiveView::reject().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action().
update()
void TaskDlgActiveView::update ()
Definition at line 303 of file TaskActiveView.cpp.
The documentation for this class was generated from the following files:
TaskActiveView.h
TaskActiveView.cpp