FreeCAD: Robot6Axis.cpp File Reference
Robot6Axis.cpp File Reference
#include "PreCompiled.h"
#include "kdl_cp/chainfksolverpos_recursive.hpp"
#include "kdl_cp/chainiksolverpos_nr_jl.hpp"
#include "kdl_cp/chainiksolvervel_pinv.hpp"
#include <Base/FileInfo.h>
#include <Base/Reader.h>
#include <Base/Stream.h>
#include <Base/Tools.h>
#include <Base/Writer.h>
#include "Robot6Axis.h"
#include "RobotAlgos.h"
Functions
void split (std::string const &string, const char delimiter, std::vector< std::string > &destination)
Variables
AxisDefinition KukaIR500 [6]
Function Documentation
split()
void split (std::string const & string, const char delimiter, std::vector< std::string > & destination)
Definition at line 107 of file Robot6Axis.cpp.
Referenced by ParameterGrp::GetGroup(), Gui::PreferencePackManager::modPaths(), Robot::Robot6Axis::readKinematic(), and App::StringHasher::restoreStreamNew().
Variable Documentation
KukaIR500
AxisDefinition KukaIR500[6]
Initial value:
= {
    {500  ,-90   ,1045 ,0     , -1    ,+185     ,-185     ,156         },
    {1300 ,0     ,0    ,0     , 1     ,+35      ,-155     ,156         },
    {55   ,+90   ,0    ,-90   , 1     ,+154     ,-130     ,156         },
    {0    ,-90   ,-1025,0     , 1     ,+350     ,-350     ,330         },
    {0    ,+90   ,0    ,0     , 1     ,+130     ,-130     ,330         },
    {0    ,+180  ,-300 ,0     , 1     ,+350     ,-350     ,615         }
}
Definition at line 46 of file Robot6Axis.cpp.
Referenced by Robot::Robot6Axis::Robot6Axis().