FreeCAD: SIM::Coin3D::Quarter::InputDevice Class Reference
SIM::Coin3D::Quarter::InputDevice Class Reference abstract
The InputDevice class is the base class for devices such as keyboard and mouse. It can be subclassed to support other devices.
#include <Quarter/devices/InputDevice.h>
Public Member Functions
InputDevice (QuarterWidget *quarter)
virtual ~InputDevice ()
virtual const SoEvent * translateEvent (QEvent *event)=0
void setMousePosition (const SbVec2s &pos)
void setWindowSize (const SbVec2s &size)
void setModifiers (SoEvent *soevent, const QInputEvent *qevent)
Protected Attributes
SbVec2s mousepos
SbVec2s windowsize
QuarterWidget * quarter
Detailed Description
The InputDevice class is the base class for devices such as keyboard and mouse. It can be subclassed to support other devices.
Definition at line 47 of file InputDevice.h.
Constructor & Destructor Documentation
InputDevice()
InputDevice::InputDevice (QuarterWidget * quarter) explicit
Definition at line 52 of file InputDevice.cpp.
References mousepos.
~InputDevice()
virtual SIM::Coin3D::Quarter::InputDevice::~InputDevice () inline virtual
Definition at line 50 of file InputDevice.h.
Member Function Documentation
setModifiers()
void InputDevice::setModifiers (SoEvent * soevent, const QInputEvent * qevent)
Transforms a QEvent into an SoEvent
Parameters
[in,out] SoEvent the transformed event
[in] QEvent incoming QEvent
Definition at line 87 of file InputDevice.cpp.
setMousePosition()
void InputDevice::setMousePosition (const SbVec2s & pos)
Sets the mouse position
Parameters
[in] pos position of mouse in pixel coordinates
Definition at line 64 of file InputDevice.cpp.
References mousepos, and RobotExample::pos.
Referenced by SIM::Coin3D::Quarter::EventFilterP::trackPointerPosition(), and Gui::SceneEventFilter::Private::trackPointerPosition().
setWindowSize()
void InputDevice::setWindowSize (const SbVec2s & size)
Sets the window size of the owning window
Parameters
[in] size in pixels
Definition at line 75 of file InputDevice.cpp.
References windowsize.
Referenced by SIM::Coin3D::Quarter::EventFilterP::trackWindowSize(), and Gui::SceneEventFilter::Private::trackWindowSize().
translateEvent()
virtual const SoEvent* SIM::Coin3D::Quarter::InputDevice::translateEvent (QEvent * event) pure virtual
Subclasses must override this method to provide custom event handling
Implemented in SpaceNavigatorDevice, GesturesDevice, SIM::Coin3D::Quarter::Keyboard, SIM::Coin3D::Quarter::Mouse, and SIM::Coin3D::Quarter::SpaceNavigatorDevice.
Referenced by SIM::Coin3D::Quarter::EventFilter::eventFilter(), and Gui::SceneEventFilter::eventFilter().
Member Data Documentation
mousepos
InputDevice::mousepos protected
Holds the last known position of the mouse. This should be set even for a keyboard event.
Definition at line 63 of file InputDevice.h.
Referenced by InputDevice(), setMousePosition(), and SpaceNavigatorDevice::translateEvent().
quarter
QuarterWidget* SIM::Coin3D::Quarter::InputDevice::quarter protected
Definition at line 65 of file InputDevice.h.
Referenced by SIM::Coin3D::Quarter::MouseP::mouseButtonEvent(), SIM::Coin3D::Quarter::MouseP::mouseMoveEvent(), and SIM::Coin3D::Quarter::MouseP::mouseWheelEvent().
windowsize
InputDevice::windowsize protected
Holds the size of the owning window
Definition at line 64 of file InputDevice.h.
Referenced by setWindowSize().
The documentation for this class was generated from the following files:
InputDevice.h
InputDevice.cpp