FreeCAD: ifc4.ifcboundaryfacecondition Class Reference
ifc4.ifcboundaryfacecondition Class Reference
Public Member Functions
def __init__ (self, inherited0__name, translationalstiffnessbyareax, translationalstiffnessbyareay, translationalstiffnessbyareaz)
def translationalstiffnessbyareax ()
def translationalstiffnessbyareay ()
def translationalstiffnessbyareaz ()
Public Member Functions inherited from ifc4.ifcboundarycondition
def __init__ (self, name)
def name ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
translationalstiffnessbyareax
translationalstiffnessbyareay
translationalstiffnessbyareaz
Public Attributes inherited from ifc4.ifcboundarycondition
name
Detailed Description
Entity ifcboundaryfacecondition definition.
:param translationalstiffnessbyareax
:type translationalstiffnessbyareax:ifcmodulusofsubgradereactionselect
:param translationalstiffnessbyareay
:type translationalstiffnessbyareay:ifcmodulusofsubgradereactionselect
:param translationalstiffnessbyareaz
:type translationalstiffnessbyareaz:ifcmodulusofsubgradereactionselect
Definition at line 40407 of file ifc4.py.
Constructor & Destructor Documentation
__init__()
def ifc4.ifcboundaryfacecondition.__init__ (self, inherited0__name, translationalstiffnessbyareax, translationalstiffnessbyareay, translationalstiffnessbyareaz)
Definition at line 40419 of file ifc4.py.
Member Function Documentation
translationalstiffnessbyareax()
def ifc4.ifcboundaryfacecondition.translationalstiffnessbyareax ()
Definition at line 40426 of file ifc4.py.
References ifc4.ifcboundaryfacecondition._translationalstiffnessbyareax, SCL.TypeChecker.check_type(), ifc4.ifcmodulusofsubgradereactionselect, and ifc4.ifcboundaryfacecondition.translationalstiffnessbyareax.
translationalstiffnessbyareay()
def ifc4.ifcboundaryfacecondition.translationalstiffnessbyareay ()
Definition at line 40440 of file ifc4.py.
References ifc4.ifcboundaryfacecondition._translationalstiffnessbyareay, SCL.TypeChecker.check_type(), ifc4.ifcmodulusofsubgradereactionselect, and ifc4.ifcboundaryfacecondition.translationalstiffnessbyareay.
translationalstiffnessbyareaz()
def ifc4.ifcboundaryfacecondition.translationalstiffnessbyareaz ()
Definition at line 40454 of file ifc4.py.
References ifc4.ifcboundaryfacecondition._translationalstiffnessbyareaz, SCL.TypeChecker.check_type(), ifc4.ifcmodulusofsubgradereactionselect, and ifc4.ifcboundaryfacecondition.translationalstiffnessbyareaz.
Member Data Documentation
translationalstiffnessbyareax
ifc4.ifcboundaryfacecondition.translationalstiffnessbyareax
Definition at line 40421 of file ifc4.py.
Referenced by ifc4.ifcboundaryfacecondition.translationalstiffnessbyareax().
translationalstiffnessbyareay
ifc4.ifcboundaryfacecondition.translationalstiffnessbyareay
Definition at line 40422 of file ifc4.py.
Referenced by ifc4.ifcboundaryfacecondition.translationalstiffnessbyareay().
translationalstiffnessbyareaz
ifc4.ifcboundaryfacecondition.translationalstiffnessbyareaz
Definition at line 40423 of file ifc4.py.
Referenced by ifc4.ifcboundaryfacecondition.translationalstiffnessbyareaz().
The documentation for this class was generated from the following file:
ifc4.py