FreeCAD: Gui::OutputStderr Class Reference
Gui::OutputStderr Class Reference
#include <PythonConsolePy.h>
Public Member Functions
OutputStderr ()
~OutputStderr () override
Py::Object getattr (const char *name) override
Py::Object repr () override
Py::Object write (const Py::Tuple &)
Py::Object flush (const Py::Tuple &)
Py::Object isatty ()
Static Public Member Functions
static void init_type ()
Detailed Description
Python class for redirection of stderr to FreeCAD's output console window. This allows one to report all Python errors to the report view which simplifies error tracking.
See also
PythonStdout
PythonStderr
Author
Werner Mayer
Definition at line 117 of file PythonConsolePy.h.
Constructor & Destructor Documentation
OutputStderr()
OutputStderr::OutputStderr () default
~OutputStderr()
OutputStderr::~OutputStderr () override default
Member Function Documentation
flush()
Py::Object OutputStderr::flush (const Py::Tuple &)
Definition at line 268 of file PythonConsolePy.cpp.
Referenced by init_type().
getattr()
Py::Object OutputStderr::getattr (const char * name) override
Definition at line 235 of file PythonConsolePy.cpp.
References SplineSurface::i.
init_type()
void OutputStderr::init_type () static
Definition at line 220 of file PythonConsolePy.cpp.
References flush(), isatty(), and write().
Referenced by Gui::Application::Application().
isatty()
Py::Object OutputStderr::isatty ()
Definition at line 273 of file PythonConsolePy.cpp.
References femtools.tokrules::False.
Referenced by init_type().
repr()
Py::Object OutputStderr::repr () override
Definition at line 244 of file PythonConsolePy.cpp.
References toolbit-attributes::s, and src.Mod.Test.testmakeWireString::String.
write()
Py::Object OutputStderr::write (const Py::Tuple & args)
Definition at line 252 of file PythonConsolePy.cpp.
References toolbit-attributes::args, Base::Console(), Base::ConsoleSingleton::Error(), and ArchBuildingPart::unicode.
Referenced by init_type().
The documentation for this class was generated from the following files:
PythonConsolePy.h
PythonConsolePy.cpp