FreeCAD: ArchFloor._CommandFloor Class Reference
ArchFloor._CommandFloor Class Reference
Public Member Functions
def GetResources (self)
def IsActive (self)
def Activated (self)
Detailed Description
The command definition for the Arch workbench's gui tool, Arch Floor.
A tool for creating Arch floors.
Create a floor from the objects selected by the user, if any. Exclude
objects that appear higher in the object hierarchy, such as sites or
buildings. If free linking is enabled in the BIM preferences, allow higher
hierarchy objects to be part of floors.
Find documentation on the end user usage of Arch Floor here:
https://wiki.freecad.org/Arch_Floor
Definition at line 98 of file ArchFloor.py.
Member Function Documentation
Activated()
def ArchFloor._CommandFloor.Activated (self)
Executed when Arch Floor is called.
Create a floor from the objects selected by the user, if any. Exclude
objects that appear higher in the object hierarchy, such as sites or
buildings. If free linking is enabled in the BIM preferences, allow
higher hierarchy objects to be part of floors.
Definition at line 129 of file ArchFloor.py.
References ArchCommands.printMessage().
Referenced by draftguitools.gui_rectangles.Rectangle.finish(), draftguitools.gui_ellipses.Ellipse.finish(), draftguitools.gui_texts.Text.finish(), draftguitools.gui_polygons.Polygon.finish(), draftguitools.gui_arcs.Arc.finish(), draftguitools.gui_move.Move.finish(), draftguitools.gui_points.Point.finish(), draftguitools.gui_lines.Line.finish(), draftguitools.gui_splines.BSpline.finish(), draftguitools.gui_beziers.BezCurve.finish(), draftguitools.gui_rotate.Rotate.finish(), draftguitools.gui_beziers.CubicBezCurve.finish(), draftguitools.gui_arcs.Arc_3Points.finish(), bimcommands.BimPanel.Arch_Panel.getPoint(), bimcommands.BimWall.Arch_Wall.getPoint(), and ArchStructure._CommandStructure.getPoint().
GetResources()
def ArchFloor._CommandFloor.GetResources (self)
Return a dictionary with the visual aspects of the Arch Floor tool.
Definition at line 113 of file ArchFloor.py.
References Arch.QT_TRANSLATE_NOOP.
IsActive()
def ArchFloor._CommandFloor.IsActive (self)
Determine whether or not the Arch Floor tool is active.
Inactive commands are indicated by a greyed-out icon in the menus and toolbars.
Definition at line 121 of file ArchFloor.py.
The documentation for this class was generated from the following file:
ArchFloor.py