FreeCAD: Gui::RecoveryWriter Class Reference
Gui::RecoveryWriter Class Reference
#include <AutoSaver.h>
Public Member Functions
RecoveryWriter (AutoSaveProperty &)
~RecoveryWriter () override
bool shouldWrite (const std::string &, const Base::Persistence *) const override
void writeFiles () override
process the requested file storing
Public Member Functions inherited from Base::FileWriter
FileWriter (const char *DirName)
~FileWriter () override
void putNextEntry (const char *filename, const char *objName=nullptr) override
put the next entry with a give name
void writeFiles () override
process the requested file storing
std::ostream & Stream () override
void close ()
FileWriter (const FileWriter &)=delete
FileWriter (FileWriter &&)=delete
FileWriter & operator= (const FileWriter &)=delete
FileWriter & operator= (FileWriter &&)=delete
Public Member Functions inherited from Base::Writer
Writer ()
virtual ~Writer ()
void setForceXML (bool on)
switch the writer in XML only mode (no files allowed)
bool isForceXML () const
check on state
void setFileVersion (int)
int getFileVersion () const
void insertAsciiFile (const char *FileName)
insert a file as CDATA section in the XML file
void insertBinFile (const char *FileName)
insert a binary file BASE64 coded as CDATA section in the XML file
void insertText (const std::string &str)
insert text string as CDATA
std::string addFile (const char *Name, const Base::Persistence *Object)
add a write request of a persistent object
const std::vector< std::string > & getFilenames () const
get all registered file names
void setMode (const std::string &mode)
Set mode.
void setModes (const std::set< std::string > &modes)
Set modes.
bool getMode (const std::string &mode) const
Get mode.
std::set< std::string > getModes () const
Get modes.
void clearMode (const std::string &mode)
Clear mode.
void clearModes ()
Clear modes.
void addError (const std::string &)
bool hasErrors () const
void clearErrors ()
std::vector< std::string > getErrors () const
const char * ind () const
get the current indentation
void incInd ()
increase indentation by one tab
void decInd ()
decrease indentation by one tab
std::ostream & beginCharStream (CharStreamFormat format=CharStreamFormat::Raw)
std::ostream & endCharStream ()
std::ostream & charStream ()
Return the current character output stream.
Writer (const Writer &)=delete
Writer (Writer &&)=delete
Writer & operator= (const Writer &)=delete
Writer & operator= (Writer &&)=delete
Additional Inherited Members
Public Attributes inherited from Base::Writer
std::string ObjectName
name for underlying file saves
Protected Member Functions inherited from Base::Writer
std::string getUniqueFileName (const char *Name)
Protected Attributes inherited from Base::FileWriter
std::string DirName
std::ofstream FileStream
Protected Attributes inherited from Base::Writer
std::vector< FileEntry > FileList
std::vector< std::string > FileNames
std::vector< std::string > Errors
std::set< std::string > Modes
short indent {0}
char indBuf [1024] {}
bool forceXML {false}
int fileVersion {1}
Detailed Description
Definition at line 101 of file AutoSaver.h.
Constructor & Destructor Documentation
RecoveryWriter()
RecoveryWriter::RecoveryWriter (AutoSaveProperty & saver)
Definition at line 285 of file AutoSaver.cpp.
~RecoveryWriter()
RecoveryWriter::~RecoveryWriter () override default
Member Function Documentation
shouldWrite()
bool RecoveryWriter::shouldWrite (const std::string & name, const Base::Persistence * object) const override virtual
This method can be re-implemented in sub-classes to avoid to write out certain objects. The default implementation always returns true.
Reimplemented from Base::FileWriter.
Definition at line 292 of file AutoSaver.cpp.
References Gui::AutoSaveProperty::fileMap, Base::Persistence::getClassTypeId(), App::Property::getContainer(), Base::BaseClass::isDerivedFrom(), Init::parent, Path.Post.scripts.refactored_centroid_post::str, and Gui::AutoSaveProperty::touched.
Referenced by writeFiles().
writeFiles()
void RecoveryWriter::writeFiles () override virtual
process the requested file storing
Implements Base::Writer.
Definition at line 368 of file AutoSaver.cpp.
References Base::FileInfo::createDirectory(), Base::FileWriter::DirName, Base::Writer::FileList, Base::Writer::FileEntry::FileName, Path.Preferences::filePath(), Base::FileWriter::FileStream, Base::Persistence::getClassTypeId(), Base::Writer::getModes(), Base::BaseClass::isDerivedFrom(), Base::Writer::FileEntry::Object, RobotExample::pos, Base::Persistence::SaveDocFile(), and shouldWrite().
Referenced by Gui::AutoSaver::saveDocument().
The documentation for this class was generated from the following files:
AutoSaver.h
AutoSaver.cpp