FreeCAD: Gui::Dialog::DlgMacroRecordImp Class Reference
Gui::Dialog::DlgMacroRecordImp Class Reference
#include <DlgMacroRecordImp.h>
Public Member Functions
DlgMacroRecordImp (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgMacroRecordImp () override
Public Member Functions inherited from Gui::WindowParameter
WindowParameter (const char *name)
~WindowParameter () override
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
ParameterGrp::handle getWindowParameter ()
return the parameter group of this window
Protected Member Functions
void setupConnections ()
void onButtonStartClicked ()
void onButtonStopClicked ()
void onButtonCloseClicked ()
void onButtonChooseDirClicked ()
void onMacroPathTextChanged (const QString &)
Protected Member Functions inherited from Gui::WindowParameter
bool setGroupName (const char *name)
template<typename S , typename T >
void setSlotParamChanged (S slot, T *obsPtr)
connect slot to ParameterManager signal
Additional Inherited Members
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter ()
get the parameters
Detailed Description
The DlgMacroRecordImp class implements a dialog to record a macro.
Author
Jürgen Riegel
Definition at line 60 of file DlgMacroRecordImp.h.
Constructor & Destructor Documentation
DlgMacroRecordImp()
DlgMacroRecordImp::DlgMacroRecordImp (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Constructs a DlgMacroRecordImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
Definition at line 50 of file DlgMacroRecordImp.cpp.
References App::Application::getUserMacroDir(), Gui::WindowParameter::getWindowParameter(), Gui::Application::Instance, Gui::MacroManager::isOpen(), Gui::Application::macroManager(), and setupConnections().
~DlgMacroRecordImp()
DlgMacroRecordImp::~DlgMacroRecordImp () override default
Destroys the object and frees any allocated resources
Member Function Documentation
onButtonChooseDirClicked()
void DlgMacroRecordImp::onButtonChooseDirClicked () protected
Definition at line 185 of file DlgMacroRecordImp.cpp.
References Gui::WindowParameter::getWindowParameter(), and ParameterGrp::SetASCII().
Referenced by setupConnections().
onButtonCloseClicked()
void DlgMacroRecordImp::onButtonCloseClicked () protected
Abort the macro.
Definition at line 160 of file DlgMacroRecordImp.cpp.
References Gui::MacroManager::cancel(), and Gui::MacroManager::isOpen().
Referenced by setupConnections().
onButtonStartClicked()
void DlgMacroRecordImp::onButtonStartClicked () protected
Starts the record of the macro.
Definition at line 100 of file DlgMacroRecordImp.cpp.
References DrawingExample::file, Gui::MacroManager::File, Gui::getMainWindow(), and Gui::MacroManager::open().
Referenced by setupConnections().
onButtonStopClicked()
void DlgMacroRecordImp::onButtonStopClicked () protected
Stops the record of the macro and save to the file.
Definition at line 172 of file DlgMacroRecordImp.cpp.
References Gui::MacroManager::commit(), and Gui::MacroManager::isOpen().
Referenced by setupConnections().
onMacroPathTextChanged()
void DlgMacroRecordImp::onMacroPathTextChanged (const QString & newDir) protected
Definition at line 196 of file DlgMacroRecordImp.cpp.
Referenced by setupConnections().
setupConnections()
void DlgMacroRecordImp::setupConnections () protected
Definition at line 81 of file DlgMacroRecordImp.cpp.
References draftgeoutils.intersections::connect(), onButtonChooseDirClicked(), onButtonCloseClicked(), onButtonStartClicked(), onButtonStopClicked(), and onMacroPathTextChanged().
Referenced by DlgMacroRecordImp().
The documentation for this class was generated from the following files:
DlgMacroRecordImp.h
DlgMacroRecordImp.cpp