FreeCAD: MeshCore::TaubinSmoothing Class Reference
MeshCore::TaubinSmoothing Class Reference
#include <Smoothing.h>
Public Member Functions
TaubinSmoothing (MeshKernel &)
void Smooth (unsigned int) override
void SmoothPoints (unsigned int, const std::vector< PointIndex > &) override
void SetMicro (double m)
Public Member Functions inherited from MeshCore::LaplaceSmoothing
LaplaceSmoothing (MeshKernel &)
void SetLambda (double l)
double GetLambda () const
Public Member Functions inherited from MeshCore::AbstractSmoothing
AbstractSmoothing (MeshKernel &)
virtual ~AbstractSmoothing ()
AbstractSmoothing (const AbstractSmoothing &)=delete
AbstractSmoothing (AbstractSmoothing &&)=delete
AbstractSmoothing & operator= (const AbstractSmoothing &)=delete
AbstractSmoothing & operator= (AbstractSmoothing &&)=delete
void initialize (Component comp, Continuity cont)
Additional Inherited Members
Public Types inherited from MeshCore::AbstractSmoothing
enum Component { Tangential, Normal, TangentialNormal }
enum Continuity { C0, C1, C2 }
Protected Member Functions inherited from MeshCore::LaplaceSmoothing
void Umbrella (const MeshRefPointToPoints &, const MeshRefPointToFacets &, double)
void Umbrella (const MeshRefPointToPoints &, const MeshRefPointToFacets &, double, const std::vector< PointIndex > &)
Protected Attributes inherited from MeshCore::AbstractSmoothing
MeshKernel & kernel
Component component {Normal}
Continuity continuity {C0}
Detailed Description
Definition at line 140 of file Smoothing.h.
Constructor & Destructor Documentation
TaubinSmoothing()
TaubinSmoothing::TaubinSmoothing (MeshKernel & m) explicit
Definition at line 267 of file Smoothing.cpp.
Member Function Documentation
SetMicro()
void MeshCore::TaubinSmoothing::SetMicro (double m) inline
Definition at line 146 of file Smoothing.h.
Smooth()
void TaubinSmoothing::Smooth (unsigned int) override virtual
Smooth the triangle mesh.
Reimplemented from MeshCore::LaplaceSmoothing.
Definition at line 271 of file Smoothing.cpp.
References MeshCore::LaplaceSmoothing::GetLambda(), SplineSurface::i, MeshCore::AbstractSmoothing::kernel, and MeshCore::LaplaceSmoothing::Umbrella().
SmoothPoints()
void TaubinSmoothing::SmoothPoints (unsigned int iterations, const std::vector< PointIndex > & point_indices) override virtual
Reimplemented from MeshCore::LaplaceSmoothing.
Definition at line 284 of file Smoothing.cpp.
References MeshCore::LaplaceSmoothing::GetLambda(), SplineSurface::i, MeshCore::AbstractSmoothing::kernel, and MeshCore::LaplaceSmoothing::Umbrella().
The documentation for this class was generated from the following files:
Smoothing.h
Smoothing.cpp