FreeCAD: Part::TopoShapeCache Class Reference
Part::TopoShapeCache Class Reference
#include <TopoShapeCache.h>
Classes
struct AncestorInfo
class Ancestry
Class for caching the ancestor and children shapes mapping.
Public Member Functions
TopoShapeCache (const TopoDS_Shape &tds)
void insertRelation (const ShapeRelationKey &key, const QVector< Data::MappedElement > &value)
bool isTouched (const TopoDS_Shape &tds) const
Ancestry & getAncestry (TopAbs_ShapeEnum type)
int countShape (TopAbs_ShapeEnum type)
int findShape (const TopoDS_Shape &parent, const TopoDS_Shape &subShape)
TopoDS_Shape findShape (const TopoDS_Shape &parent, TopAbs_ShapeEnum type, int index)
TopoDS_Shape findAncestor (const TopoDS_Shape &parent, const TopoDS_Shape &subShape, TopAbs_ShapeEnum type, std::vector< TopoDS_Shape > *ancestors=nullptr)
Public Attributes
Data::ElementMapPtr cachedElementMap
TopLoc_Location subLocation
Location of the original cached TopoDS_Shape.
TopoDS_Shape shape
The cached TopoDS_Shape stripped of any location (i.e. a null TopoDS_Shape::myLocation).
TopLoc_Location location
TopLoc_Location locationInverse
Inverse of location.
std::array< Ancestry, TopAbs_SHAPE+1 > shapeAncestryCache
std::map< ShapeRelationKey, QVector< Data::MappedElement > > relations
Detailed Description
Definition at line 80 of file TopoShapeCache.h.
Constructor & Destructor Documentation
TopoShapeCache()
TopoShapeCache::TopoShapeCache (const TopoDS_Shape & tds) explicit
Definition at line 155 of file TopoShapeCache.cpp.
Member Function Documentation
countShape()
int TopoShapeCache::countShape (TopAbs_ShapeEnum type)
Definition at line 195 of file TopoShapeCache.cpp.
References Part::TopoShapeCache::Ancestry::count(), getAncestry(), shape, and Path.Post.scripts.grbl_post::type.
findAncestor()
TopoDS_Shape TopoShapeCache::findAncestor (const TopoDS_Shape & parent, const TopoDS_Shape & subShape, TopAbs_ShapeEnum type, std::vector< TopoDS_Shape > * ancestors = nullptr)
Given a parent shape and a child (sub) shape, call TopExp::MapShapesAndAncestors and cache the result. Subsequent calls to this method given unchanged geometry will use the cached data rather than re-running MapShapesAndAncestors. If ancestors is given, it is cleared and overwritten with the ancestry data.
Definition at line 219 of file TopoShapeCache.cpp.
References getAncestry(), Path.Log::info(), Part::TopoShape::moved(), Init::parent, shape, and Path.Post.scripts.grbl_post::type.
findShape() [1/2]
int TopoShapeCache::findShape (const TopoDS_Shape & parent, const TopoDS_Shape & subShape)
Definition at line 203 of file TopoShapeCache.cpp.
References Part::TopoShapeCache::Ancestry::find(), getAncestry(), Init::parent, and shape.
findShape() [2/2]
TopoDS_Shape TopoShapeCache::findShape (const TopoDS_Shape & parent, TopAbs_ShapeEnum type, int index)
Definition at line 211 of file TopoShapeCache.cpp.
References Part::TopoShapeCache::Ancestry::find(), getAncestry(), Init::parent, shape, and Path.Post.scripts.grbl_post::type.
getAncestry()
TopoShapeCache::Ancestry & TopoShapeCache::getAncestry (TopAbs_ShapeEnum type)
Definition at line 176 of file TopoShapeCache.cpp.
References shape, shapeAncestryCache, and Path.Post.scripts.grbl_post::type.
Referenced by countShape(), findAncestor(), and findShape().
insertRelation()
void TopoShapeCache::insertRelation (const ShapeRelationKey & key, const QVector< Data::MappedElement > & value)
Definition at line 159 of file TopoShapeCache.cpp.
References relations.
isTouched()
bool TopoShapeCache::isTouched (const TopoDS_Shape & tds) const
Definition at line 171 of file TopoShapeCache.cpp.
References shape.
Member Data Documentation
cachedElementMap
Data::ElementMapPtr Part::TopoShapeCache::cachedElementMap
Reference counted element map for the owner TopoShape. The ElementMap of a TopoShape is normally accessed through the inherited member function ComplexGeoData::elementMap(). The extra shared pointer here is so that other TopoShape instances with the same Cache can reuse the map once generated.
Definition at line 88 of file TopoShapeCache.h.
location
TopLoc_Location Part::TopoShapeCache::location
Location of the last ancestor shape used to find this TopoShape. These two members are used to avoid repetitive inverting the location of the same ancestor.
Definition at line 98 of file TopoShapeCache.h.
Referenced by automotive_design.revolved_area_solid::axis_line(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.revolved_area_solid::axis_line(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.revolved_face_solid::axis_line(), automotive_design.surface_of_revolution::axis_line(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_of_revolution::axis_line(), automotive_design.revolved_face_solid::axis_line(), ifc2x3.ifcsurfaceofrevolution::axisline(), ifc4.ifcsurfaceofrevolution::axisline(), ifc2x3.ifcrevolvedareasolid::axisline(), ifc4.ifcrevolvedareasolid::axisline(), ifc4.ifcrevolvedareasolid::axisstartinxy(), and ifc2x3.ifcrevolvedareasolid::wr31().
locationInverse
TopLoc_Location Part::TopoShapeCache::locationInverse
Inverse of location.
Definition at line 101 of file TopoShapeCache.h.
relations
std::map<ShapeRelationKey, QVector<Data::MappedElement> > Part::TopoShapeCache::relations
Definition at line 164 of file TopoShapeCache.h.
Referenced by insertRelation().
shape
TopoDS_Shape Part::TopoShapeCache::shape
The cached TopoDS_Shape stripped of any location (i.e. a null TopoDS_Shape::myLocation).
Definition at line 94 of file TopoShapeCache.h.
Referenced by countShape(), findAncestor(), findShape(), getAncestry(), and isTouched().
shapeAncestryCache
std::array<Ancestry, TopAbs_SHAPE + 1> Part::TopoShapeCache::shapeAncestryCache
Ancestor and children shape caches of all shape types. Note that shapeAncestryCache[TopAbs_SHAPE] is also valid and stores the direct children of a compound shape.
Definition at line 162 of file TopoShapeCache.h.
Referenced by getAncestry().
subLocation
TopLoc_Location Part::TopoShapeCache::subLocation
Location of the original cached TopoDS_Shape.
Definition at line 91 of file TopoShapeCache.h.
The documentation for this class was generated from the following files:
TopoShapeCache.h
TopoShapeCache.cpp