FreeCAD: Mesh::MergeExporter Class Reference
Mesh::MergeExporter Class Reference
Creates a single mesh, in a file, from one or more objects.
#include <Exporter.h>
Public Member Functions
MergeExporter (std::string fileName, MeshCore::MeshIO::Format fmt)
~MergeExporter () override
MergeExporter (const MergeExporter &)=delete
MergeExporter (MergeExporter &&)=delete
MergeExporter & operator= (const MergeExporter &)=delete
MergeExporter & operator= (MergeExporter &&)=delete
bool addMesh (const char *name, const MeshObject &mesh) override
Public Member Functions inherited from Mesh::Exporter
Exporter ()
virtual ~Exporter ()=default
int addObject (App::DocumentObject *obj, float tol)
Add object and all subobjects and links etc. Returns the number of stuff added.
Exporter (const Exporter &)=delete
Exporter (Exporter &&)=delete
Exporter & operator= (const Exporter &)=delete
Exporter & operator= (Exporter &&)=delete
Protected Attributes
MeshObject mergingMesh
std::string fName
Protected Attributes inherited from Mesh::Exporter
std::map< const App::DocumentObject *, std::vector< std::string > > subObjectNameCache
std::map< const App::DocumentObject *, MeshObject > meshCache
Additional Inherited Members
Protected Member Functions inherited from Mesh::Exporter
void throwIfNoPermission (const std::string &)
Static Protected Member Functions inherited from Mesh::Exporter
static std::string xmlEscape (const std::string &input)
Does some simple escaping of characters for XML-type exports.
Detailed Description
Creates a single mesh, in a file, from one or more objects.
Definition at line 99 of file Exporter.h.
Constructor & Destructor Documentation
MergeExporter() [1/3]
MergeExporter::MergeExporter (std::string fileName, MeshCore::MeshIO::Format fmt)
Definition at line 164 of file Exporter.cpp.
~MergeExporter()
MergeExporter::~MergeExporter () override
Definition at line 168 of file Exporter.cpp.
MergeExporter() [2/3]
Mesh::MergeExporter::MergeExporter (const MergeExporter &) delete
MergeExporter() [3/3]
Mesh::MergeExporter::MergeExporter (MergeExporter &&) delete
Member Function Documentation
addMesh()
bool MergeExporter::addMesh (const char * name, const MeshObject & mesh) override virtual
Implements Mesh::Exporter.
Definition at line 190 of file Exporter.cpp.
References Mesh::MeshObject::addMesh(), Mesh::MeshObject::addSegment(), Mesh::MeshObject::countFacets(), Path.Base.Generator.dogboneII::generate(), Mesh::Segment::getIndices(), Mesh::Segment::getName(), SplineSurface::i, Mesh::Segment::isSaved(), mergingMesh, Mesh2Shape::mesh, Mesh::MeshObject::setKernel(), Mesh::Segment::setName(), and TestSpreadsheet::v.
operator=() [1/2]
MergeExporter& Mesh::MergeExporter::operator= (const MergeExporter &) delete
operator=() [2/2]
MergeExporter& Mesh::MergeExporter::operator= (MergeExporter &&) delete
Member Data Documentation
fName
std::string Mesh::MergeExporter::fName protected
Definition at line 119 of file Exporter.h.
mergingMesh
MeshObject Mesh::MergeExporter::mergingMesh protected
Definition at line 118 of file Exporter.h.
Referenced by addMesh().
The documentation for this class was generated from the following files:
Exporter.h
Exporter.cpp