FreeCAD: Gui::BlenderNavigationStyle Class Reference
Gui::BlenderNavigationStyle Class Reference
#include <NavigationStyle.h>
Public Member Functions
BlenderNavigationStyle ()
~BlenderNavigationStyle () override
const char * mouseButtons (ViewerMode) override
Public Member Functions inherited from Gui::UserNavigationStyle
UserNavigationStyle ()=default
~UserNavigationStyle () override=default
virtual std::string userFriendlyName () const
Public Member Functions inherited from Gui::NavigationStyle
NavigationStyle ()
~NavigationStyle () override
NavigationStyle (const NavigationStyle &)=delete
NavigationStyle & operator= (const NavigationStyle &ns)
void setViewer (View3DInventorViewer *)
void setAnimationEnabled (const SbBool enable)
Decide if it should be possible to start any animation.
void setSpinningAnimationEnabled (const SbBool enable)
Decide if it should be possible to start a spin animation of the model in the viewer by releasing the mouse button while dragging.
SbBool isAnimationEnabled () const
SbBool isSpinningAnimationEnabled () const
SbBool isAnimating () const
SbBool isSpinning () const
void startAnimating (const std::shared_ptr< NavigationAnimation > &animation, bool wait=false) const
void stopAnimating () const
void setSensitivity (float)
float getSensitivity () const
void setResetCursorPosition (SbBool)
SbBool isResetCursorPosition () const
void setZoomInverted (SbBool)
SbBool isZoomInverted () const
void setZoomStep (float)
void setZoomAtCursor (SbBool)
SbBool isZoomAtCursor () const
void zoomIn ()
void zoomOut ()
void setRotationCenterMode (RotationCenterModes)
RotationCenterModes getRotationCenterMode () const
void setRotationCenter (const SbVec3f &cnt)
SbVec3f getFocalPoint () const
SoCamera * getCamera () const
void setCameraOrientation (const SbRotation &orientation, SbBool moveToCenter=false)
void translateCamera (const SbVec3f &translation)
void findBoundingSphere ()
void reorientCamera (SoCamera *camera, const SbRotation &rotation)
void reorientCamera (SoCamera *camera, const SbRotation &rotation, const SbVec3f &rotationCenter)
void boxZoom (const SbBox2s &box)
virtual void viewAll ()
void setViewingMode (const ViewerMode newmode)
int getViewingMode () const
virtual SbBool processEvent (const SoEvent *const ev)
virtual SbBool processMotionEvent (const SoMotion3Event *const ev)
virtual SbBool processKeyboardEvent (const SoKeyboardEvent *const event)
virtual SbBool processClickEvent (const SoMouseButtonEvent *const event)
virtual SbBool processWheelEvent (const SoMouseWheelEvent *const event)
void setPopupMenuEnabled (const SbBool on)
SbBool isPopupMenuEnabled () const
void startSelection (AbstractMouseSelection *)
void startSelection (SelectionMode=Lasso)
void abortSelection ()
void stopSelection ()
SbBool isSelecting () const
const std::vector< SbVec2s > & getPolygon (SelectionRole *role=nullptr) const
void setOrbitStyle (OrbitStyle style)
OrbitStyle getOrbitStyle () const
SbBool isViewing () const
void setViewing (SbBool)
SbVec3f getRotationCenter (SbBool &) const
PyObject * getPyObject () override
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
SbBool processSoEvent (const SoEvent *const ev) override
Protected Member Functions inherited from Gui::NavigationStyle
void initialize ()
void finalize ()
void interactiveCountInc ()
void interactiveCountDec ()
int getInteractiveCount () const
SbBool isSeekMode () const
void setSeekMode (SbBool enable)
SbBool seekToPoint (const SbVec2s screenpos)
void seekToPoint (const SbVec3f &scenepos)
void lookAtPoint (const SbVec2s screenpos)
void lookAtPoint (const SbVec3f &position)
void panCamera (SoCamera *camera, float vpaspect, const SbPlane &panplane, const SbVec2f &previous, const SbVec2f &current)
void setupPanningPlane (const SoCamera *camera)
int getDelta () const
void zoom (SoCamera *camera, float diffvalue)
void zoomByCursor (const SbVec2f &thispos, const SbVec2f &prevpos)
void doZoom (SoCamera *camera, int wheeldelta, const SbVec2f &pos)
void doZoom (SoCamera *camera, float logzoomfactor, const SbVec2f &pos)
NavigationStyle::doZoom Zooms in or out by specified factor, keeping the point on screen specified by parameter pos fixed or not according to user preference (NavigationStyle::zoomAtCursor). Ignores invertZoom user preference.
void doRotate (SoCamera *camera, float angle, const SbVec2f &pos)
void spin (const SbVec2f &pointerpos)
SbBool doSpin ()
void spin_simplified (SoCamera *cam, SbVec2f curpos, SbVec2f prevpos)
NavigationStyle::spin_simplified is a simplified version of NavigationStyle::spin(..), which uses less global variables. Doesn't support starting an animated spinning.
void moveCursorPosition ()
void saveCursorPosition (const SoEvent *const ev)
SbVec2f normalizePixelPos (SbVec2s pixpos)
SbVec2f normalizePixelPos (SbVec2f pixpos)
SbBool handleEventInForeground (const SoEvent *const e)
void syncWithEvent (const SoEvent *const ev)
virtual void openPopupMenu (const SbVec2s &position)
void clearLog ()
void addToLog (const SbVec2s pos, const SbTime time)
void syncModifierKeys (const SoEvent *const ev)
Additional Inherited Members
Public Types inherited from Gui::NavigationStyle
enum ViewerMode {
IDLE, INTERACT, ZOOMING, BOXZOOM,
PANNING, DRAGGING, SPINNING, SEEK_WAIT_MODE,
SEEK_MODE, SELECTION
}
enum SelectionMode {
Lasso = 0, Rectangle = 1, Rubberband = 2, BoxZoom = 3,
Clip = 4
}
enum OrbitStyle { Turntable, Trackball, FreeTurntable }
enum RotationCenterMode { RotationCenterMode::WindowCenter = 0, RotationCenterMode::ScenePointAtCursor = 1, RotationCenterMode::FocalPointAtCursor = 2, RotationCenterMode::BoundingBoxCenter = 4 }
Static Public Member Functions inherited from Gui::UserNavigationStyle
static std::map< Base::Type, std::string > getUserFriendlyNames ()
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::NavigationStyle
struct {
short size
short historysize
SbVec2s * position
SbTime * time
} log
View3DInventorViewer * viewer {nullptr}
NavigationAnimator * animator
SbBool animationEnabled
ViewerMode currentmode
SoMouseButtonEvent mouseDownConsumedEvent
SbVec2f lastmouseposition
SbVec2s globalPos
SbVec2s localPos
SbPlane panningplane
SbTime centerTime
SbBool lockrecenter
SbBool menuenabled
SbBool ctrldown
SbBool shiftdown
SbBool altdown
SbBool button1down
SbBool button2down
SbBool button3down
SbBool invertZoom
SbBool zoomAtCursor
float zoomStep
SbBool hasDragged
SbBool hasPanned
SbBool hasZoomed
AbstractMouseSelection * mouseSelection {nullptr}
std::vector< SbVec2s > pcPolygon
SelectionRole selectedRole
SbBool spinningAnimationEnabled
int spinsamplecounter
SbRotation spinincrement
SbSphereSheetProjector * spinprojector
PyObject * pythonObject
Detailed Description
Definition at line 370 of file NavigationStyle.h.
Constructor & Destructor Documentation
BlenderNavigationStyle()
BlenderNavigationStyle::BlenderNavigationStyle ()
Definition at line 42 of file BlenderNavigationStyle.cpp.
~BlenderNavigationStyle()
BlenderNavigationStyle::~BlenderNavigationStyle () override default
Member Function Documentation
mouseButtons()
const char * BlenderNavigationStyle::mouseButtons (ViewerMode mode) override virtual
Implements Gui::UserNavigationStyle.
Definition at line 48 of file BlenderNavigationStyle.cpp.
References Gui::NavigationStyle::DRAGGING, Gui::NavigationStyle::PANNING, Gui::NavigationStyle::SELECTION, and Gui::NavigationStyle::ZOOMING.
processSoEvent()
SbBool BlenderNavigationStyle::processSoEvent (const SoEvent *const ev) override protected virtual
Reimplemented from Gui::NavigationStyle.
Definition at line 64 of file BlenderNavigationStyle.cpp.
References Gui::NavigationStyle::addToLog(), Gui::NavigationStyle::button1down, Gui::NavigationStyle::button2down, Gui::NavigationStyle::button3down, Gui::NavigationStyle::centerTime, Gui::NavigationStyle::ctrldown, Gui::NavigationStyle::currentmode, Gui::NavigationStyle::DRAGGING, Gui::NavigationStyle::getCamera(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), Gui::NavigationStyle::handleEventInForeground(), Gui::NavigationStyle::hasDragged, Gui::NavigationStyle::hasPanned, Gui::NavigationStyle::hasZoomed, Gui::NavigationStyle::IDLE, Gui::NavigationStyle::isAnimating(), Gui::View3DInventorViewer::isEditing(), Gui::NavigationStyle::isPopupMenuEnabled(), Gui::NavigationStyle::isSeekMode(), Gui::NavigationStyle::isViewing(), Gui::NavigationStyle::lastmouseposition, Gui::NavigationStyle::lockrecenter, Gui::NavigationStyle::lookAtPoint(), Gui::NavigationStyle::moveCursorPosition(), Gui::NavigationStyle::normalizePixelPos(), Gui::NavigationStyle::openPopupMenu(), Gui::NavigationStyle::panCamera(), Gui::NavigationStyle::PANNING, RobotExample::pos, Gui::NavigationStyle::processClickEvent(), Gui::NavigationStyle::processKeyboardEvent(), Gui::NavigationStyle::processMotionEvent(), Gui::NavigationStyle::processSoEvent(), Gui::NavigationStyle::saveCursorPosition(), Gui::NavigationStyle::SEEK_MODE, Gui::NavigationStyle::SEEK_WAIT_MODE, Gui::NavigationStyle::seekToPoint(), Gui::NavigationStyle::SELECTION, Gui::NavigationStyle::setupPanningPlane(), Gui::NavigationStyle::setViewing(), Gui::NavigationStyle::setViewingMode(), Gui::NavigationStyle::shiftdown, Gui::NavigationStyle::spin(), Gui::NavigationStyle::SPINNING, Gui::NavigationStyle::syncModifierKeys(), Path.Post.scripts.grbl_post::type, Gui::NavigationStyle::viewer, Gui::NavigationStyle::zoomByCursor(), and Gui::NavigationStyle::ZOOMING.
The documentation for this class was generated from the following files:
NavigationStyle.h
BlenderNavigationStyle.cpp