FreeCAD: Gui::NotificationBox Class Reference
Gui::NotificationBox Class Reference
#include <NotificationBox.h>
Public Types
enum Options { Options::None = 0x0, Options::RestrictAreaToReference = 0x1, Options::OnlyIfReferenceActive = 0x2, Options::HideIfReferenceWidgetDeactivated = 0x4 }
Public Member Functions
NotificationBox ()=delete
Static Public Member Functions
static bool showText (const QPoint &pos, const QString &text, QWidget *referenceWidget=nullptr, int displayTime=-1, unsigned int minShowTime=0, Options options=Options::None, int width=0)
static void hideText ()
Hides a notification.
static bool isVisible ()
Returns whether a notification is being shown or not.
static QString text ()
Returns the text of the notification.
static QPalette palette ()
Returns the palette.
static void setPalette (const QPalette &)
Sets the palette.
static QFont font ()
Returns the font of the notification.
static void setFont (const QFont &)
Sets the font to be used in the notification.
Detailed Description
This class provides a non-intrusive tip alike notification dialog, which unlike QToolTip, is kept shown during a time.
The notification is shown during minShowTime, unless pop out (i.e. clicked inside the notification).
The notification will show up to a maximum of displayTime. The only event that closes the notification between minShowTime and displayTime is a mouse button click (anywhere of the screen).
When displayTime is not provided, it is calculated based on the length of the text.
This class interface and its implementation are based on QT's QToolTip.
Definition at line 67 of file NotificationBox.h.
Member Enumeration Documentation
Options
enum Gui::NotificationBox::Options strong
Enumerator
None
RestrictAreaToReference
OnlyIfReferenceActive
HideIfReferenceWidgetDeactivated
Definition at line 92 of file NotificationBox.h.
Constructor & Destructor Documentation
NotificationBox()
Gui::NotificationBox::NotificationBox () delete
Member Function Documentation
font()
QFont Gui::NotificationBox::font () static
Returns the font of the notification.
Definition at line 405 of file NotificationBox.cpp.
Referenced by setFont().
hideText()
static void Gui::NotificationBox::hideText () inline static
Hides a notification.
Definition at line 127 of file NotificationBox.h.
isVisible()
bool Gui::NotificationBox::isVisible () static
Returns whether a notification is being shown or not.
Definition at line 386 of file NotificationBox.cpp.
References Gui::NotificationLabel::instance.
Referenced by ArchVRM.Renderer::removeHidden(), and showText().
palette()
QPalette Gui::NotificationBox::palette () static
Returns the palette.
Definition at line 400 of file NotificationBox.cpp.
Referenced by Gui::NotificationLabel::NotificationLabel(), and setPalette().
setFont()
void Gui::NotificationBox::setFont (const QFont & font) static
Sets the font to be used in the notification.
Definition at line 417 of file NotificationBox.cpp.
References font().
setPalette()
void Gui::NotificationBox::setPalette (const QPalette & palette) static
Sets the palette.
Definition at line 410 of file NotificationBox.cpp.
References Gui::NotificationLabel::instance, and palette().
showText()
bool Gui::NotificationBox::showText (const QPoint & pos, const QString & text, QWidget * referenceWidget = nullptr, int displayTime = -1, unsigned int minShowTime = 0, Options options = Options::None, int width = 0) static
Shows a non-intrusive notification.
Parameters
pos Position at which the notification will be shown
text Message to be shown
referenceWidget If provided, will set the reference to calculate a restrictionarea (see below options) and to prevent notifications for being shown if not active.
displayTime Time after which the notification will auto-close (unless it is closed by an event, see class documentation above)
minShowTime Time during which the notification can only be made disappear by popping it out (clicking inside it).
options Different flag options:
HideIfReferenceWidgetDeactivated - Hides a notification if the main window becomes inactive.
RestrictAreaToReference - Try to keep the NotificationBox within the QRect of the referenceWidget. if false or referenceWidget is nullptr, the whole screen is used as restriction area.
OnlyIfReferenceActive - Show only if the reference window is active.
width Fixes the width of the notification. Default value makes the width to be system determined (dependent on the text). If a fixed width is provided it is enforced over the restrictionarea.
Returns
returns whether the notification was shown or not
Definition at line 322 of file NotificationBox.cpp.
References HideIfReferenceWidgetDeactivated, Gui::NotificationLabel::instance, isVisible(), OnlyIfReferenceActive, RobotExample::pos, and RestrictAreaToReference.
text()
QString Gui::NotificationBox::text () static
Returns the text of the notification.
Definition at line 391 of file NotificationBox.cpp.
References Gui::NotificationLabel::instance.
The documentation for this class was generated from the following files:
NotificationBox.h
NotificationBox.cpp