FreeCAD: Path.Base.Gui.IconViewProvider Namespace Reference
Path.Base.Gui.IconViewProvider Namespace Reference
Classes
class ViewProvider
Functions
def Attach (vobj, name)
def RegisterViewProvider (name, provider)
Variables
translate
Function Documentation
Attach()
def Path.Base.Gui.IconViewProvider.Attach (vobj, name)
Attach(vobj, name) ... attach the appropriate view provider to the view object.
If no view provider was registered for the given name a default IconViewProvider is created.
Definition at line 105 of file IconViewProvider.py.
References Path.Log.track().
Referenced by Path.Main.Job.createResourceClone(), and Path.Main.Job.ObjectJob.setupSetupSheet().
RegisterViewProvider()
def Path.Base.Gui.IconViewProvider.RegisterViewProvider (name, provider)
RegisterViewProvider(name, provider) ... if an IconViewProvider is created for an object with the given name
an instance of provider is used instead.
Definition at line 118 of file IconViewProvider.py.
References Path.Log.track().
Variable Documentation
translate
Path.Base.Gui.IconViewProvider.translate
Definition at line 33 of file IconViewProvider.py.