FreeCAD: ifc2x3.ifcbooleanclippingresult Class Reference
ifc2x3.ifcbooleanclippingresult Class Reference
Public Member Functions
def __init__ (self, inherited0__operator, inherited1__firstoperand, inherited2__secondoperand)
def wr1 (self)
def wr2 (self)
def wr3 (self)
Public Member Functions inherited from ifc2x3.ifcbooleanresult
def operator ()
def firstoperand ()
def secondoperand ()
def dim ()
Public Member Functions inherited from ifc2x3.ifcgeometricrepresentationitem
def __init__ (self)
Public Member Functions inherited from ifc2x3.ifcrepresentationitem
def layerassignments ()
def styledbyitem ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
operator
Public Attributes inherited from ifc2x3.ifcbooleanresult
operator
firstoperand
secondoperand
dim
Detailed Description
Entity ifcbooleanclippingresult definition.
Definition at line 28620 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcbooleanclippingresult.__init__ (self, inherited0__operator, inherited1__firstoperand, inherited2__secondoperand)
Reimplemented from ifc2x3.ifcbooleanresult.
Definition at line 28623 of file ifc2x3.py.
Member Function Documentation
wr1()
def ifc2x3.ifcbooleanclippingresult.wr1 (self)
Reimplemented from ifc2x3.ifcbooleanresult.
Definition at line 28625 of file ifc2x3.py.
References ifc2x3.ifcbooleanresult.firstoperand, and SCL.Builtin.TYPEOF().
Referenced by ifc4.ifctextalignment.__init__(), ifc4.ifcspecularroughness.__init__(), ifc4.ifcheatingvaluemeasure.__init__(), ifc4.ifctexttransformation.__init__(), ifc4.ifcfontstyle.__init__(), ifc4.ifcboxalignment.__init__(), ifc4.ifcpositiveplaneanglemeasure.__init__(), ifc4.ifcdimensioncount.__init__(), ifc4.ifcfontvariant.__init__(), ifc4.ifcfontweight.__init__(), ifc4.ifcnormalisedratiomeasure.__init__(), ifc4.ifcpositivelengthmeasure.__init__(), ifc4.ifcpositiveratiomeasure.__init__(), and ifc4.ifctextdecoration.__init__().
wr2()
def ifc2x3.ifcbooleanclippingresult.wr2 (self)
Definition at line 28632 of file ifc2x3.py.
References ifc2x3.ifcbooleanresult.secondoperand, and SCL.Builtin.TYPEOF().
wr3()
def ifc2x3.ifcbooleanclippingresult.wr3 (self)
Definition at line 28639 of file ifc2x3.py.
Member Data Documentation
operator
ifc2x3.ifcbooleanclippingresult.operator
Definition at line 28640 of file ifc2x3.py.
The documentation for this class was generated from the following file:
ifc2x3.py