FreeCAD: TechDrawGui::TaskDlgCenterLine Class Reference
TechDrawGui::TaskDlgCenterLine Class Reference
#include <TaskCenterLine.h>
Public Member Functions
TaskDlgCenterLine (TechDraw::DrawViewPart *partFeat, TechDraw::DrawPage *page, std::vector< std::string > subNames, bool editMode)
TaskDlgCenterLine (TechDraw::DrawViewPart *partFeat, TechDraw::DrawPage *page, std::string edgeName, bool editMode)
~TaskDlgCenterLine () override
void open () override
is called the TaskView when the dialog is opened
void clicked (int) override
is called by the framework if an button is clicked which has no accept or reject role
bool accept () override
is called by the framework if the dialog is accepted (Ok)
bool reject () override
is called by the framework if the dialog is rejected (Cancel)
void helpRequested () override
is called by the framework if the user presses the help button
bool isAllowedAlterDocument () const override
void update ()
void modifyStandardButtons (QDialogButtonBox *box) override
Public Member Functions inherited from Gui::TaskView::TaskDialog
TaskDialog ()
~TaskDialog () override
QWidget * addTaskBox (QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBox (const QPixmap &icon, QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBoxWithoutHeader (QWidget *widget)
void setButtonPosition (ButtonPosition p)
ButtonPosition buttonPosition () const
const std::vector< QWidget * > & getDialogContent () const
bool canClose () const
virtual QDialogButtonBox::StandardButtons getStandardButtons () const
tells the framework which buttons are wished for the dialog
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
bool isEscapeButtonEnabled () const
void setAutoCloseOnTransactionChange (bool on)
bool isAutoCloseOnTransactionChange () const
void setAutoCloseOnDeletedDocument (bool on)
bool isAutoCloseOnDeletedDocument () const
const std::string & getDocumentName () const
void setDocumentName (const std::string &doc)
void setAutoCloseOnClosedView (bool on)
bool isAutoCloseOnClosedView () const
void associateToObject3dView (App::DocumentObject *obj)
const Gui::MDIView * getAssociatedView () const
void setAssociatedView (const Gui::MDIView *view)
virtual bool isAllowedAlterView () const
virtual bool isAllowedAlterSelection () const
virtual bool needsFullSpace () const
virtual void closed ()
is called by the framework when the dialog is closed
virtual void autoClosedOnTransactionChange ()
virtual void autoClosedOnDeletedDocument ()
virtual void autoClosedOnClosedView ()
void emitDestructionSignal ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from Gui::TaskView::TaskDialog
QPointer< QDialogButtonBox > buttonBox
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Detailed Description
Definition at line 125 of file TaskCenterLine.h.
Constructor & Destructor Documentation
TaskDlgCenterLine() [1/2]
TaskDlgCenterLine::TaskDlgCenterLine (TechDraw::DrawViewPart * partFeat, TechDraw::DrawPage * page, std::vector< std::string > subNames, bool editMode)
Definition at line 580 of file TaskCenterLine.cpp.
References Gui::BitmapFactory(), Gui::TaskView::TaskDialog::Content, QSint::ActionGroup::groupLayout(), and Gui::TaskView::TaskDialog::setAutoCloseOnTransactionChange().
TaskDlgCenterLine() [2/2]
TaskDlgCenterLine::TaskDlgCenterLine (TechDraw::DrawViewPart * partFeat, TechDraw::DrawPage * page, std::string edgeName, bool editMode)
Definition at line 594 of file TaskCenterLine.cpp.
References Gui::BitmapFactory(), Gui::TaskView::TaskDialog::Content, QSint::ActionGroup::groupLayout(), and Gui::TaskView::TaskDialog::setAutoCloseOnTransactionChange().
~TaskDlgCenterLine()
TaskDlgCenterLine::~TaskDlgCenterLine () override
Definition at line 608 of file TaskCenterLine.cpp.
Member Function Documentation
accept()
bool TaskDlgCenterLine::accept () override virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 633 of file TaskCenterLine.cpp.
References TechDrawGui::TaskCenterLine::accept().
clicked()
void TaskDlgCenterLine::clicked (int) override virtual
is called by the framework if an button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 629 of file TaskCenterLine.cpp.
helpRequested()
void TechDrawGui::TaskDlgCenterLine::helpRequested () inline override virtual
is called by the framework if the user presses the help button
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 150 of file TaskCenterLine.h.
isAllowedAlterDocument()
bool TechDrawGui::TaskDlgCenterLine::isAllowedAlterDocument () const inline override virtual
Indicates whether this task dialog allows other commands to modify the document while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 151 of file TaskCenterLine.h.
modifyStandardButtons()
void TaskDlgCenterLine::modifyStandardButtons (QDialogButtonBox * box) override virtual
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 617 of file TaskCenterLine.cpp.
References MengerSponge::box, and TechDrawGui::TaskCenterLine::saveButtons().
open()
void TaskDlgCenterLine::open () override virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 625 of file TaskCenterLine.cpp.
reject()
bool TaskDlgCenterLine::reject () override virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 639 of file TaskCenterLine.cpp.
References TechDrawGui::TaskCenterLine::reject().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action().
update()
void TaskDlgCenterLine::update ()
Definition at line 612 of file TaskCenterLine.cpp.
The documentation for this class was generated from the following files:
TaskCenterLine.h
TaskCenterLine.cpp