FreeCAD: Gui::SoU3DVectorOutput Class Reference
Gui::SoU3DVectorOutput Class Reference
#include <SoFCVectorizeU3DAction.h>
Public Member Functions
SoU3DVectorOutput ()
~SoU3DVectorOutput () override
SbBool openFile (const char *filename) override
void closeFile () override
std::fstream & getFileStream ()
Detailed Description
Definition at line 53 of file SoFCVectorizeU3DAction.h.
Constructor & Destructor Documentation
SoU3DVectorOutput()
SoU3DVectorOutput::SoU3DVectorOutput () default
~SoU3DVectorOutput()
SoU3DVectorOutput::~SoU3DVectorOutput () override
Definition at line 143 of file SoFCVectorizeU3DAction.cpp.
References closeFile().
Member Function Documentation
closeFile()
void SoU3DVectorOutput::closeFile () override
Definition at line 160 of file SoFCVectorizeU3DAction.cpp.
Referenced by ~SoU3DVectorOutput().
getFileStream()
std::fstream & SoU3DVectorOutput::getFileStream ()
Definition at line 166 of file SoFCVectorizeU3DAction.cpp.
Referenced by Gui::SoFCVectorizeU3DAction::printHeader().
openFile()
SbBool SoU3DVectorOutput::openFile (const char * filename) override
Definition at line 148 of file SoFCVectorizeU3DAction.cpp.
References Base::FileInfo::filePath(), and Base::FileInfo::toStdWString().
The documentation for this class was generated from the following files:
SoFCVectorizeU3DAction.h
SoFCVectorizeU3DAction.cpp