FreeCAD: Gui::WorkbenchTabWidget Class Reference
Gui::WorkbenchTabWidget Class Reference
#include <WorkbenchSelector.h>
Public Slots
void handleWorkbenchSelection (QAction *selectedWorkbenchAction)
void handleTabChange (int selectedTabIndex)
void updateLayout ()
void updateWorkbenchList ()
Signals
void directionChanged (const Qt::LayoutDirection &)
Public Member Functions
WorkbenchTabWidget (WorkbenchGroup *aGroup, QWidget *parent=nullptr)
void setToolBarArea (Gui::ToolBarArea area)
void buildPrefMenu ()
Qt::LayoutDirection direction () const
void setDirection (Qt::LayoutDirection direction)
void adjustSize ()
Protected Member Functions
int addWorkbenchTab (QAction *workbenchActivateAction, int index=-1)
void setTemporaryWorkbenchTab (QAction *workbenchActivateAction)
int temporaryWorkbenchTabIndex () const
QAction * workbenchActivateActionByTabIndex (int tabIndex) const
int tabIndexForWorkbenchActivateAction (QAction *workbenchActivateAction) const
WorkbenchItemStyle itemStyle () const
Properties
Qt::LayoutDirection direction
Detailed Description
Definition at line 86 of file WorkbenchSelector.h.
Constructor & Destructor Documentation
WorkbenchTabWidget()
WorkbenchTabWidget::WorkbenchTabWidget (WorkbenchGroup * aGroup, QWidget * parent = nullptr) explicit
Definition at line 104 of file WorkbenchSelector.cpp.
References Gui::Action::action(), Gui::BitmapFactory(), draftgeoutils.intersections::connect(), Gui::ActionGroup::groupAction(), handleTabChange(), handleWorkbenchSelection(), Init::parent, Gui::Action::toolTip(), updateLayout(), updateWorkbenchList(), and Gui::WorkbenchGroup::workbenchListRefreshed().
Member Function Documentation
addWorkbenchTab()
int WorkbenchTabWidget::addWorkbenchTab (QAction * workbenchActivateAction, int index = -1) protected
Definition at line 327 of file WorkbenchSelector.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::IconOnly, itemStyle(), and Gui::TextOnly.
Referenced by setTemporaryWorkbenchTab(), and updateWorkbenchList().
adjustSize()
void WorkbenchTabWidget::adjustSize ()
Definition at line 424 of file WorkbenchSelector.cpp.
Referenced by NavigationIndicatorGui.IndicatorButton::changeEvent(), handleTabChange(), setTemporaryWorkbenchTab(), setToolBarArea(), and updateWorkbenchList().
buildPrefMenu()
void WorkbenchTabWidget::buildPrefMenu ()
Definition at line 399 of file WorkbenchSelector.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::Dialog::DlgPreferencesImp::activateGroupPage(), draftgeoutils.intersections::connect(), Gui::WorkbenchGroup::getDisabledWbActions(), Gui::getMainWindow(), and NavigationIndicatorGui::menu.
Referenced by updateWorkbenchList().
direction()
Qt::LayoutDirection Gui::WorkbenchTabWidget::direction () const
directionChanged
void Gui::WorkbenchTabWidget::directionChanged (const Qt::LayoutDirection &) signal
Referenced by setDirection().
handleTabChange
void WorkbenchTabWidget::handleTabChange (int selectedTabIndex) slot
Definition at line 275 of file WorkbenchSelector.cpp.
References adjustSize(), setTemporaryWorkbenchTab(), temporaryWorkbenchTabIndex(), and workbenchActivateActionByTabIndex().
Referenced by WorkbenchTabWidget().
handleWorkbenchSelection
void WorkbenchTabWidget::handleWorkbenchSelection (QAction * selectedWorkbenchAction) slot
Definition at line 240 of file WorkbenchSelector.cpp.
References Gui::WorkbenchGroup::getDisabledWbActions(), setTemporaryWorkbenchTab(), tabIndexForWorkbenchActivateAction(), and updateLayout().
Referenced by WorkbenchTabWidget().
itemStyle()
WorkbenchItemStyle Gui::WorkbenchTabWidget::itemStyle () const protected
Definition at line 206 of file WorkbenchSelector.cpp.
References App::GetApplication(), ParameterGrp::GetInt(), and App::Application::GetParameterGroupByPath().
Referenced by addWorkbenchTab(), and updateWorkbenchList().
setDirection()
void WorkbenchTabWidget::setDirection (Qt::LayoutDirection direction)
Definition at line 164 of file WorkbenchSelector.cpp.
References direction, and directionChanged().
Referenced by setToolBarArea().
setTemporaryWorkbenchTab()
void WorkbenchTabWidget::setTemporaryWorkbenchTab (QAction * workbenchActivateAction) protected
Definition at line 255 of file WorkbenchSelector.cpp.
References addWorkbenchTab(), adjustSize(), and temporaryWorkbenchTabIndex().
Referenced by handleTabChange(), handleWorkbenchSelection(), and updateWorkbenchList().
setToolBarArea()
void WorkbenchTabWidget::setToolBarArea (Gui::ToolBarArea area)
Definition at line 361 of file WorkbenchSelector.cpp.
References adjustSize(), Gui::BottomToolBarArea, direction, Gui::LeftMenuToolBarArea, Gui::LeftToolBarArea, Gui::RightMenuToolBarArea, Gui::RightToolBarArea, setDirection(), Gui::StatusBarToolBarArea, and Gui::TopToolBarArea.
Referenced by updateLayout().
tabIndexForWorkbenchActivateAction()
int WorkbenchTabWidget::tabIndexForWorkbenchActivateAction (QAction * workbenchActivateAction) const protected
Definition at line 197 of file WorkbenchSelector.cpp.
References temporaryWorkbenchTabIndex().
Referenced by handleWorkbenchSelection().
temporaryWorkbenchTabIndex()
int WorkbenchTabWidget::temporaryWorkbenchTabIndex () const inline protected
Definition at line 171 of file WorkbenchSelector.cpp.
References direction.
Referenced by handleTabChange(), setTemporaryWorkbenchTab(), tabIndexForWorkbenchActivateAction(), and workbenchActivateActionByTabIndex().
updateLayout
void WorkbenchTabWidget::updateLayout () slot
Definition at line 212 of file WorkbenchSelector.cpp.
References direction, Gui::ToolBarManager::getInstance(), Sketcher::Horizontal, Gui::LeftToolBarArea, setToolBarArea(), Gui::ToolBarManager::toolBarArea(), and Gui::TopToolBarArea.
Referenced by handleWorkbenchSelection(), and WorkbenchTabWidget().
updateWorkbenchList
void WorkbenchTabWidget::updateWorkbenchList () slot
Definition at line 294 of file WorkbenchSelector.cpp.
References Path.Post.scripts.dynapath_4060_post::action, addWorkbenchTab(), adjustSize(), buildPrefMenu(), Gui::WorkbenchGroup::getEnabledWbActions(), SplineSurface::i, itemStyle(), and setTemporaryWorkbenchTab().
Referenced by WorkbenchTabWidget().
workbenchActivateActionByTabIndex()
QAction * WorkbenchTabWidget::workbenchActivateActionByTabIndex (int tabIndex) const protected
Definition at line 182 of file WorkbenchSelector.cpp.
References temporaryWorkbenchTabIndex().
Referenced by handleTabChange().
Property Documentation
direction
Qt::LayoutDirection WorkbenchTabWidget::direction inline read write
Definition at line 89 of file WorkbenchSelector.h.
Referenced by CommandCreateSimulation.TaskAssemblyCreateSimulation::animationTimerStartBackward(), CommandCreateSimulation.TaskAssemblyCreateSimulation::playAnimation(), setDirection(), setToolBarArea(), temporaryWorkbenchTabIndex(), and updateLayout().
The documentation for this class was generated from the following files:
WorkbenchSelector.h
WorkbenchSelector.cpp