FreeCAD: TechDrawGui::TaskGeomHatch Class Reference
TechDrawGui::TaskGeomHatch Class Reference
#include <TaskGeomHatch.h>
Public Member Functions
TaskGeomHatch (TechDraw::DrawGeomHatch *inHatch, TechDrawGui::ViewProviderGeomHatch *inVp, bool mode)
~TaskGeomHatch () override=default
virtual bool accept ()
virtual bool reject ()
void setCreateMode (bool mode)
bool getCreateMode () const
Protected Slots
void onFileChanged ()
Protected Member Functions
void changeEvent (QEvent *event) override
void initUi ()
void updateValues ()
void getParameters ()
QStringList listToQ (std::vector< std::string > inList)
Detailed Description
Definition at line 47 of file TaskGeomHatch.h.
Constructor & Destructor Documentation
TaskGeomHatch()
TaskGeomHatch::TaskGeomHatch (TechDraw::DrawGeomHatch * inHatch, TechDrawGui::ViewProviderGeomHatch * inVp, bool mode)
Definition at line 48 of file TaskGeomHatch.cpp.
References draftgeoutils.intersections::connect(), getParameters(), App::PropertyLinkSub::getValue(), initUi(), onFileChanged(), and TechDraw::DrawGeomHatch::Source.
~TaskGeomHatch()
TechDrawGui::TaskGeomHatch::~TaskGeomHatch () override default
Member Function Documentation
accept()
bool TaskGeomHatch::accept () virtual
Definition at line 153 of file TaskGeomHatch.cpp.
References doCommand, Gui::Command::Gui, App::DocumentObject::recomputeFeature(), TechDraw::DrawView::requestPaint(), and updateValues().
Referenced by TechDrawGui::TaskDlgGeomHatch::accept().
changeEvent()
void TaskGeomHatch::changeEvent (QEvent * event) override protected
Definition at line 232 of file TaskGeomHatch.cpp.
getCreateMode()
bool TechDrawGui::TaskGeomHatch::getCreateMode () const inline
Definition at line 58 of file TaskGeomHatch.h.
Referenced by getParameters(), and reject().
getParameters()
void TaskGeomHatch::getParameters () protected
Definition at line 184 of file TaskGeomHatch.cpp.
References TechDrawGui::ViewProviderGeomHatch::ColorPattern, TechDraw::DrawGeomHatch::FilePattern, getCreateMode(), App::PropertyVector::getValue(), App::PropertyFloat::getValue(), App::PropertyString::getValue(), App::PropertyColor::getValue(), TechDraw::DrawGeomHatch::NamePattern, TechDraw::DrawGeomHatch::PatternOffset, TechDraw::DrawGeomHatch::PatternRotation, TechDraw::DrawGeomHatch::ScalePattern, and TechDrawGui::ViewProviderGeomHatch::WeightPattern.
Referenced by TaskGeomHatch().
initUi()
void TaskGeomHatch::initUi () protected
Definition at line 62 of file TaskGeomHatch.cpp.
References App::Color::asValue(), draftgeoutils.intersections::connect(), Base::Console(), listToQ(), femtools.tokrules::names, Base::ConsoleSingleton::Warning(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by TaskGeomHatch().
listToQ()
QStringList TaskGeomHatch::listToQ (std::vector< std::string > inList) protected
Definition at line 222 of file TaskGeomHatch.cpp.
References result, and toolbit-attributes::s.
Referenced by initUi(), and onFileChanged().
onFileChanged
void TaskGeomHatch::onFileChanged () protected slot
Definition at line 94 of file TaskGeomHatch.cpp.
References TechDraw::DrawUtil::cleanFilespecBackslash(), TechDraw::DrawGeomHatch::FilePattern, listToQ(), femtools.tokrules::names, and App::PropertyString::setValue().
Referenced by TaskGeomHatch().
reject()
bool TaskGeomHatch::reject () virtual
Definition at line 164 of file TaskGeomHatch.cpp.
References TechDrawGui::ViewProviderGeomHatch::ColorPattern, doCommand, TechDraw::DrawGeomHatch::FilePattern, getCreateMode(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), Gui::Command::Gui, TechDraw::DrawGeomHatch::NamePattern, TechDraw::DrawGeomHatch::PatternOffset, TechDraw::DrawGeomHatch::PatternRotation, App::Document::recompute(), TechDraw::DrawGeomHatch::ScalePattern, App::PropertyVector::setValue(), App::PropertyFloat::setValue(), App::PropertyString::setValue(), App::PropertyColor::setValue(), App::DocumentObject::touch(), and TechDrawGui::ViewProviderGeomHatch::WeightPattern.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and TechDrawGui::TaskDlgGeomHatch::reject().
setCreateMode()
void TechDrawGui::TaskGeomHatch::setCreateMode (bool mode) inline
Definition at line 57 of file TaskGeomHatch.h.
Referenced by TechDrawGui::TaskDlgGeomHatch::setCreateMode().
updateValues()
void TaskGeomHatch::updateValues () protected
Definition at line 205 of file TaskGeomHatch.cpp.
References TechDrawGui::ViewProviderGeomHatch::ColorPattern, TechDraw::DrawGeomHatch::FilePattern, TechDraw::DrawGeomHatch::NamePattern, TechDraw::DrawGeomHatch::PatternRotation, TechDraw::DrawGeomHatch::ScalePattern, App::Color::setValue(), App::PropertyFloat::setValue(), App::PropertyString::setValue(), App::PropertyColor::setValue(), and TechDrawGui::ViewProviderGeomHatch::WeightPattern.
Referenced by accept().
The documentation for this class was generated from the following files:
TaskGeomHatch.h
TaskGeomHatch.cpp