FreeCAD: Gui::SoFCTransform Class Reference
Gui::SoFCTransform Class Reference
A temporary workaround for coin3d/coin#534.
#include <SoFCTransform.h>
Public Member Functions
SoFCTransform ()
Static Public Member Functions
static void initClass ()
Protected Member Functions
void GLRender (SoGLRenderAction *action) override
void callback (SoCallbackAction *action) override
void pick (SoPickAction *action) override
void getPrimitiveCount (SoGetPrimitiveCountAction *action) override
void getBoundingBox (SoGetBoundingBoxAction *action) override
void doAction (SoAction *action) override
Detailed Description
A temporary workaround for coin3d/coin#534.
This class is a workaround for a missing feature to reduce the OpenGL stack size. The issue was reported here: https://github.com/coin3d/coin/issues/534 And was merged here: https://github.com/coin3d/coin/pull/535
Once this feature is available in all supported versions of Coin3D, this class should be removed and all instances should revert to using SoTransform.
Definition at line 63 of file SoFCTransform.h.
Constructor & Destructor Documentation
SoFCTransform()
SoFCTransform::SoFCTransform ()
Definition at line 47 of file SoFCTransform.cpp.
Member Function Documentation
callback()
void SoFCTransform::callback (SoCallbackAction * action) override protected
Definition at line 57 of file SoFCTransform.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
Referenced by Path.Main.Gui.Camotics.CamoticsSimulation::execute().
doAction()
void SoFCTransform::doAction (SoAction * action) override protected
Definition at line 77 of file SoFCTransform.cpp.
References Path.Post.scripts.dynapath_4060_post::action.
Referenced by callback(), getBoundingBox(), getPrimitiveCount(), GLRender(), and pick().
getBoundingBox()
void SoFCTransform::getBoundingBox (SoGetBoundingBoxAction * action) override protected
Definition at line 72 of file SoFCTransform.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
getPrimitiveCount()
void SoFCTransform::getPrimitiveCount (SoGetPrimitiveCountAction * action) override protected
Definition at line 67 of file SoFCTransform.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
GLRender()
void SoFCTransform::GLRender (SoGLRenderAction * action) override protected
Definition at line 52 of file SoFCTransform.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
initClass()
void SoFCTransform::initClass () static
Definition at line 42 of file SoFCTransform.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
pick()
void SoFCTransform::pick (SoPickAction * action) override protected
Definition at line 62 of file SoFCTransform.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
The documentation for this class was generated from the following files:
SoFCTransform.h
SoFCTransform.cpp