FreeCAD: TechDrawGui::MDIViewPagePy Class Reference
TechDrawGui::MDIViewPagePy Class Reference
#include <MDIViewPage.h>
Public Types
using BaseType = Py::PythonExtension< MDIViewPagePy >
Public Member Functions
MDIViewPagePy (MDIViewPage *mdi)
~MDIViewPagePy () override
Py::Object repr () override
Py::Object getattr (const char *attrName) override
Py::Object getPage (const Py::Tuple &)
Py::Object cast_to_base (const Py::Tuple &)
MDIViewPage * getMDIViewPagePtr ()
Static Public Member Functions
static void init_type ()
Protected Attributes
Gui::MDIViewPy base
Detailed Description
Definition at line 162 of file MDIViewPage.h.
Member Typedef Documentation
BaseType
using TechDrawGui::MDIViewPagePy::BaseType = Py::PythonExtension<MDIViewPagePy>
Definition at line 165 of file MDIViewPage.h.
Constructor & Destructor Documentation
MDIViewPagePy()
MDIViewPagePy::MDIViewPagePy (MDIViewPage * mdi) explicit
Definition at line 1097 of file MDIViewPage.cpp.
~MDIViewPagePy()
MDIViewPagePy::~MDIViewPagePy () override
Definition at line 1099 of file MDIViewPage.cpp.
Member Function Documentation
cast_to_base()
Py::Object MDIViewPagePy::cast_to_base (const Py::Tuple &)
Definition at line 1154 of file MDIViewPage.cpp.
References Gui::MDIViewPy::create().
Referenced by init_type().
getattr()
Py::Object MDIViewPagePy::getattr (const char * attrName) override
Definition at line 1115 of file MDIViewPage.cpp.
References SCL.SimpleDataTypes::e, and getMDIViewPagePtr().
getMDIViewPagePtr()
MDIViewPage * MDIViewPagePy::getMDIViewPagePtr ()
Definition at line 1141 of file MDIViewPage.cpp.
Referenced by getattr(), getPage(), and repr().
getPage()
Py::Object MDIViewPagePy::getPage (const Py::Tuple & args)
Definition at line 1146 of file MDIViewPage.cpp.
References toolbit-attributes::args, and getMDIViewPagePtr().
Referenced by init_type().
init_type()
void MDIViewPagePy::init_type () static
Definition at line 1081 of file MDIViewPage.cpp.
References cast_to_base(), and getPage().
Referenced by PyMOD_INIT_FUNC().
repr()
Py::Object MDIViewPagePy::repr () override
Definition at line 1101 of file MDIViewPage.cpp.
References getMDIViewPagePtr(), and src.Mod.Test.testmakeWireString::String.
Member Data Documentation
base
Gui::MDIViewPy TechDrawGui::MDIViewPagePy::base protected
Definition at line 179 of file MDIViewPage.h.
Referenced by bimcommands.BimCutPlane.CutPlaneTaskPanel::previewCutVolume(), and automotive_design.mechanism_base_placement::representation_relationship_rep_2().
The documentation for this class was generated from the following files:
MDIViewPage.h
MDIViewPage.cpp