FreeCAD: MeshCore::MeshRefNormalToPoints Class Reference
MeshCore::MeshRefNormalToPoints Class Reference
#include <Algorithm.h>
Public Member Functions
MeshRefNormalToPoints (const MeshKernel &rclM)
Construction.
void Rebuild ()
Rebuilds up data structure.
const Base::Vector3f & operator[] (PointIndex) const
const std::vector< Base::Vector3f > & GetValues () const
Detailed Description
The MeshRefNormalToPoints builds up a structure to have access to the normal of a vertex.
Note
If the underlying mesh kernel gets changed this structure becomes invalid and must be rebuilt.
Definition at line 618 of file Algorithm.h.
Constructor & Destructor Documentation
MeshRefNormalToPoints()
MeshCore::MeshRefNormalToPoints::MeshRefNormalToPoints (const MeshKernel & rclM) inline explicit
Construction.
Definition at line 622 of file Algorithm.h.
Member Function Documentation
GetValues()
const std::vector<Base::Vector3f>& MeshCore::MeshRefNormalToPoints::GetValues () const inline
Definition at line 631 of file Algorithm.h.
Referenced by Mesh::MeshObject::getPoints().
operator[]()
const Base::Vector3f & MeshRefNormalToPoints::operator[] (PointIndex pos) const
Definition at line 2165 of file Algorithm.cpp.
References RobotExample::pos.
Rebuild()
void MeshRefNormalToPoints::Rebuild ()
Rebuilds up data structure.
Definition at line 2139 of file Algorithm.cpp.
References Base::DistanceP2(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshKernel::GetFacets(), MeshCore::MeshGeomFacet::GetNormal(), and MeshCore::MeshKernel::GetPoints().
The documentation for this class was generated from the following files:
Algorithm.h
Algorithm.cpp