FreeCAD: ifc2x3.ifctrimmedcurve Class Reference
ifc2x3.ifctrimmedcurve Class Reference
Public Member Functions
def __init__ (self, basiscurve, trim1, trim2, senseagreement, masterrepresentation)
def basiscurve ()
def trim1 ()
def trim2 ()
def senseagreement ()
def masterrepresentation ()
def wr41 (self)
def wr42 (self)
def wr43 (self)
Public Member Functions inherited from ifc2x3.ifcboundedcurve
def __init__ (self)
Public Member Functions inherited from ifc2x3.ifccurve
def dim ()
Public Member Functions inherited from ifc2x3.ifcrepresentationitem
def layerassignments ()
def styledbyitem ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
basiscurve
trim1
trim2
senseagreement
masterrepresentation
Detailed Description
Entity ifctrimmedcurve definition.
:param basiscurve
:type basiscurve:ifccurve
:param trim1
:type trim1:SET(1,2,'ifctrimmingselect', scope = schema_scope)
:param trim2
:type trim2:SET(1,2,'ifctrimmingselect', scope = schema_scope)
:param senseagreement
:type senseagreement:BOOLEAN
:param masterrepresentation
:type masterrepresentation:ifctrimmingpreference
Definition at line 7246 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifctrimmedcurve.__init__ (self, basiscurve, trim1, trim2, senseagreement, masterrepresentation)
Definition at line 7264 of file ifc2x3.py.
Member Function Documentation
basiscurve()
def ifc2x3.ifctrimmedcurve.basiscurve ()
Definition at line 7273 of file ifc2x3.py.
References ifc2x3.ifctrimmedcurve._basiscurve, ifc2x3.ifctrimmedcurve.basiscurve, and SCL.TypeChecker.check_type().
masterrepresentation()
def ifc2x3.ifctrimmedcurve.masterrepresentation ()
Definition at line 7329 of file ifc2x3.py.
References ifc2x3.ifctrimmedcurve._masterrepresentation, SCL.TypeChecker.check_type(), and ifc2x3.ifctrimmedcurve.masterrepresentation.
senseagreement()
def ifc2x3.ifctrimmedcurve.senseagreement ()
Definition at line 7315 of file ifc2x3.py.
References ifc2x3.ifctrimmedcurve._senseagreement, SCL.SimpleDataTypes.BOOLEAN, SCL.TypeChecker.check_type(), and ifc2x3.ifctrimmedcurve.senseagreement.
trim1()
def ifc2x3.ifctrimmedcurve.trim1 ()
Definition at line 7287 of file ifc2x3.py.
References ifc2x3.ifctrimmedcurve._trim1, SCL.TypeChecker.check_type(), and ifc2x3.ifctrimmedcurve.trim1.
trim2()
def ifc2x3.ifctrimmedcurve.trim2 ()
Definition at line 7301 of file ifc2x3.py.
References ifc2x3.ifctrimmedcurve._trim2, SCL.TypeChecker.check_type(), and ifc2x3.ifctrimmedcurve.trim2.
wr41()
def ifc2x3.ifctrimmedcurve.wr41 (self)
Definition at line 7341 of file ifc2x3.py.
References SCL.Builtin.HIINDEX(), ifc2x3.ifctrimmedcurve.trim1, and SCL.Builtin.TYPEOF().
wr42()
def ifc2x3.ifctrimmedcurve.wr42 (self)
Definition at line 7348 of file ifc2x3.py.
References SCL.Builtin.HIINDEX(), ifc2x3.ifctrimmedcurve.trim2, and SCL.Builtin.TYPEOF().
wr43()
def ifc2x3.ifctrimmedcurve.wr43 (self)
Definition at line 7355 of file ifc2x3.py.
References ifc2x3.ifctrimmedcurve.basiscurve, and SCL.Builtin.TYPEOF().
Member Data Documentation
basiscurve
ifc2x3.ifctrimmedcurve.basiscurve
Definition at line 7266 of file ifc2x3.py.
Referenced by ifc2x3.ifctrimmedcurve.basiscurve(), ifc2x3.ifcpointoncurve.dim(), ifc4.ifcpointoncurve.dim(), ifc4.ifctrimmedcurve.notrimofboundedcurves(), and ifc2x3.ifctrimmedcurve.wr43().
masterrepresentation
ifc2x3.ifctrimmedcurve.masterrepresentation
Definition at line 7270 of file ifc2x3.py.
Referenced by ifc2x3.ifctrimmedcurve.masterrepresentation().
senseagreement
ifc2x3.ifctrimmedcurve.senseagreement
Definition at line 7269 of file ifc2x3.py.
Referenced by ifc2x3.ifctrimmedcurve.senseagreement().
trim1
ifc2x3.ifctrimmedcurve.trim1
Definition at line 7267 of file ifc2x3.py.
Referenced by ifc2x3.ifctrimmedcurve.trim1(), ifc4.ifctrimmedcurve.trim1valuesconsistent(), and ifc2x3.ifctrimmedcurve.wr41().
trim2
ifc2x3.ifctrimmedcurve.trim2
Definition at line 7268 of file ifc2x3.py.
Referenced by ifc2x3.ifctrimmedcurve.trim2(), ifc4.ifctrimmedcurve.trim2valuesconsistent(), and ifc2x3.ifctrimmedcurve.wr42().
The documentation for this class was generated from the following file:
ifc2x3.py