FreeCAD: MeshCore::MeshInput Class Reference
MeshCore::MeshInput Class Reference
#include <MeshIO.h>
Public Member Functions
MeshInput (MeshKernel &rclM)
MeshInput (MeshKernel &rclM, Material *m)
const std::vector< std::string > & GetGroupNames () const
bool LoadAny (const char *FileName)
Loads the file, decided by extension.
bool LoadFormat (std::istream &input, MeshIO::Format fmt)
Loads from a stream and the given format.
bool LoadSTL (std::istream &input)
bool LoadAsciiSTL (std::istream &input)
bool LoadBinarySTL (std::istream &input)
bool LoadOBJ (std::istream &input)
bool LoadOBJ (std::istream &input, const char *filename)
bool LoadSMF (std::istream &input)
bool LoadOFF (std::istream &input)
bool LoadPLY (std::istream &input)
void LoadXML (Base::XMLReader &reader)
bool Load3MF (std::istream &input)
bool LoadMeshNode (std::istream &input)
bool LoadInventor (std::istream &input)
bool LoadNastran (std::istream &input)
bool LoadCadmouldFE (std::ifstream &input)
Static Public Member Functions
static std::vector< std::string > supportedMeshFormats ()
static MeshIO::Format getFormat (const char *FileName)
Detailed Description
The MeshInput class is able to read a mesh object from an input stream in various formats.
Definition at line 106 of file MeshIO.h.
Constructor & Destructor Documentation
MeshInput() [1/2]
MeshCore::MeshInput::MeshInput (MeshKernel & rclM) inline explicit
Definition at line 109 of file MeshIO.h.
MeshInput() [2/2]
MeshCore::MeshInput::MeshInput (MeshKernel & rclM, Material * m) inline
Definition at line 113 of file MeshIO.h.
Member Function Documentation
getFormat()
MeshIO::Format MeshInput::getFormat (const char * FileName) static
Definition at line 195 of file MeshIO.cpp.
References MeshCore::MeshIO::ASTL, MeshCore::MeshIO::BMS, Base::FileInfo::hasExtension(), MeshCore::MeshIO::OBJ, MeshCore::MeshIO::OFF, MeshCore::MeshIO::PLY, MeshCore::MeshIO::SMF, and MeshCore::MeshIO::STL.
GetGroupNames()
const std::vector<std::string>& MeshCore::MeshInput::GetGroupNames () const inline
Definition at line 117 of file MeshIO.h.
Referenced by Mesh::MeshObject::load().
Load3MF()
bool MeshInput::Load3MF (std::istream & input)
Loads the mesh object from a 3MF file.
Loads a 3MF file.
Definition at line 902 of file MeshIO.cpp.
References MeshCore::MeshKernel::Merge(), Mesh2Shape::mesh, TechDrawTools.TaskFillTemplateFields::reader, and MeshCore::MeshKernel::Transform().
Referenced by LoadAny(), and LoadFormat().
LoadAny()
bool MeshInput::LoadAny (const char * FileName)
Loads the file, decided by extension.
Definition at line 223 of file MeshIO.cpp.
References Base::Console(), MeshCore::MeshKernel::CountFacets(), Base::FileInfo::exists(), MeshCore::ZipFixer::getStream(), Base::FileInfo::hasExtension(), Base::FileInfo::isFile(), Base::FileInfo::isReadable(), Load3MF(), LoadInventor(), LoadNastran(), LoadOBJ(), LoadOFF(), LoadPLY(), LoadSMF(), LoadSTL(), MeshCore::MeshKernel::Read(), Path.Post.scripts.refactored_centroid_post::str, and Base::ConsoleSingleton::Warning().
Referenced by Mesh::MeshObject::load().
LoadAsciiSTL()
bool MeshInput::LoadAsciiSTL (std::istream & input)
Loads an ASCII STL file.
Definition at line 724 of file MeshIO.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::MeshFastBuilder::AddFacet(), MeshCore::MeshFastBuilder::Finish(), importOCA::getline(), MeshCore::MeshFastBuilder::Initialize(), Base::Vector3< float_type >::Set(), and MeshCore::MeshGeomFacet::SetNormal().
Referenced by LoadFormat(), and LoadSTL().
LoadBinarySTL()
bool MeshInput::LoadBinarySTL (std::istream & input)
Loads a binary STL file.
Definition at line 801 of file MeshIO.cpp.
References MeshCore::MeshFastBuilder::AddFacet(), MeshCore::MeshFastBuilder::Finish(), SplineSurface::i, and MeshCore::MeshFastBuilder::Initialize().
Referenced by LoadFormat(), MeshPartGui::Mesh2ShapeGmsh::loadOutput(), MeshGui::RemeshGmsh::loadOutput(), and LoadSTL().
LoadCadmouldFE()
bool MeshInput::LoadCadmouldFE (std::ifstream & input)
Loads a Cadmould FE file.
Definition at line 1237 of file MeshIO.cpp.
LoadFormat()
bool MeshInput::LoadFormat (std::istream & input, MeshIO::Format fmt)
Loads from a stream and the given format.
Definition at line 283 of file MeshIO.cpp.
References MeshCore::MeshIO::APLY, MeshCore::MeshIO::ASTL, MeshCore::MeshIO::BMS, MeshCore::MeshIO::BSTL, Path.Post.scripts.comparams_post::fmt(), MeshCore::MeshIO::IV, Load3MF(), LoadAsciiSTL(), LoadBinarySTL(), LoadInventor(), LoadNastran(), LoadOBJ(), LoadOFF(), LoadPLY(), LoadSMF(), LoadSTL(), MeshCore::MeshIO::NAS, MeshCore::MeshIO::OBJ, MeshCore::MeshIO::OFF, MeshCore::MeshIO::PLY, MeshCore::MeshKernel::Read(), MeshCore::MeshIO::SMF, MeshCore::MeshIO::STL, and MeshCore::MeshIO::ThreeMF.
Referenced by Mesh::MeshObject::load().
LoadInventor()
bool MeshInput::LoadInventor (std::istream & input)
Loads an OpenInventor file.
Definition at line 925 of file MeshIO.cpp.
References MeshCore::MeshKernel::Adopt(), SCL.SimpleDataTypes::f, MeshCore::MeshFixDuplicatePoints::Fixup(), Base::InventorLoader::getFaces(), Base::InventorLoader::getPoints(), Base::InventorLoader::isNonIndexed(), Base::InventorLoader::isValid(), Base::InventorLoader::read(), MeshCore::MeshCleanup::RemoveInvalids(), MeshCore::MeshPointFacetAdjacency::SetFacetNeighbourhood(), and TestSpreadsheet::v.
Referenced by LoadAny(), and LoadFormat().
LoadMeshNode()
bool MeshInput::LoadMeshNode (std::istream & input)
Loads a node from an OpenInventor file.
Definition at line 667 of file MeshIO.cpp.
References MeshCore::MeshKernel::Adopt(), MeshCore::MeshKernel::Clear(), importOCA::getline(), MeshCore::MeshCleanup::RemoveInvalids(), and MeshCore::MeshPointFacetAdjacency::SetFacetNeighbourhood().
LoadNastran()
bool MeshInput::LoadNastran (std::istream & input)
Loads a Nastran file.
Definition at line 973 of file MeshIO.cpp.
References MeshCore::MeshFacet::_aulPoints, Base::Console(), Base::ConsoleSingleton::Error(), importOCA::getline(), SplineSurface::i, MeshCore::ltrim(), MeshCore::MeshKernel::Merge(), Materials::trim_copy(), Base::ConsoleSingleton::Warning(), MovieTool::x, and MovieTool::y.
Referenced by LoadAny(), and LoadFormat().
LoadOBJ() [1/2]
bool MeshInput::LoadOBJ (std::istream & input)
Loads an OBJ Mesh file.
Loads an OBJ file.
Definition at line 384 of file MeshIO.cpp.
References TechDrawTools.TaskFillTemplateFields::reader.
Referenced by LoadAny(), and LoadFormat().
LoadOBJ() [2/2]
bool MeshInput::LoadOBJ (std::istream & input, const char * filename)
Loads an OBJ Mesh file.
Definition at line 395 of file MeshIO.cpp.
References MeshCore::Material::binding, Base::FileInfo::dirPath(), MeshCore::Material::library, MeshCore::MeshIO::PER_FACE, TechDrawTools.TaskFillTemplateFields::reader, and Base::FileInfo::setFile().
LoadOFF()
bool MeshInput::LoadOFF (std::istream & input)
Loads an OFF Mesh file.
Loads an OFF file.
Definition at line 477 of file MeshIO.cpp.
References a, MeshCore::MeshKernel::Adopt(), SCL.SimpleDataTypes::b, MeshCore::Material::binding, MeshCore::MeshKernel::Clear(), src.Mod.AddonManager.NetworkManager::count, MeshCore::Material::diffuseColor, Mesh2Shape::faces, toolbit-attributes::g, importOCA::getline(), SplineSurface::i, MeshCore::MeshIO::PER_FACE, MeshCore::MeshIO::PER_VERTEX, RobotExample::pos, MeshCore::MeshCleanup::RemoveInvalids(), MeshCore::MeshPointFacetAdjacency::SetFacetNeighbourhood(), MeshCore::MeshCleanup::SetMaterial(), MeshCore::MeshFacet::SetVertices(), and Path.Post.scripts.refactored_centroid_post::str.
Referenced by LoadAny(), and LoadFormat().
LoadPLY()
bool MeshInput::LoadPLY (std::istream & input)
Loads a PLY Mesh file.
Definition at line 661 of file MeshIO.cpp.
References TechDrawTools.TaskFillTemplateFields::reader.
Referenced by LoadAny(), and LoadFormat().
LoadSMF()
bool MeshInput::LoadSMF (std::istream & input)
Loads an SMF Mesh file.
Loads an SMF file.
Definition at line 416 of file MeshIO.cpp.
References MeshCore::MeshKernel::Adopt(), MeshCore::MeshKernel::Clear(), importOCA::getline(), MeshCore::MeshCleanup::RemoveInvalids(), MeshCore::MeshPointFacetAdjacency::SetFacetNeighbourhood(), MeshCore::MeshFacet::SetProperty(), and MeshCore::MeshFacet::SetVertices().
Referenced by LoadAny(), and LoadFormat().
LoadSTL()
bool MeshInput::LoadSTL (std::istream & input)
Loads an STL file either in binary or ASCII format. Therefore the file header gets checked to decide if the file is binary or not.
Definition at line 318 of file MeshIO.cpp.
References MeshCore::MeshKernel::Clear(), LoadAsciiSTL(), and LoadBinarySTL().
Referenced by LoadAny(), and LoadFormat().
LoadXML()
void MeshInput::LoadXML (Base::XMLReader & reader)
Loads the mesh object from an XML file.
Definition at line 862 of file MeshIO.cpp.
References MeshCore::MeshKernel::Adopt(), SplineSurface::i, and TechDrawTools.TaskFillTemplateFields::reader.
Referenced by Mesh::PropertyMeshKernel::Restore().
supportedMeshFormats()
std::vector< std::string > MeshInput::supportedMeshFormats () static
Definition at line 180 of file MeshIO.cpp.
References Path.Post.scripts.comparams_post::fmt().
The documentation for this class was generated from the following files:
MeshIO.h
MeshIO.cpp