FreeCAD: Gui::AbstractSplitViewPy Class Reference
Gui::AbstractSplitViewPy Class Reference
#include <SplitView3DInventor.h>
Public Types
using BaseType = Py::PythonExtension< AbstractSplitViewPy >
Public Member Functions
AbstractSplitViewPy (AbstractSplitView *vi)
~AbstractSplitViewPy () override
AbstractSplitView * getSplitViewPtr ()
Py::Object repr () override
Py::Object getattr (const char *) override
Py::Object cast_to_base (const Py::Tuple &)
Py::Object fitAll (const Py::Tuple &)
Py::Object viewBottom (const Py::Tuple &)
Py::Object viewFront (const Py::Tuple &)
Py::Object viewLeft (const Py::Tuple &)
Py::Object viewRear (const Py::Tuple &)
Py::Object viewRight (const Py::Tuple &)
Py::Object viewTop (const Py::Tuple &)
Py::Object viewIsometric (const Py::Tuple &)
Py::Object getViewer (const Py::Tuple &)
Py::Object sequence_item (Py_ssize_t) override
Py::Object close (const Py::Tuple &)
PyCxx_ssize_t sequence_length () override
Static Public Member Functions
static void init_type ()
Detailed Description
Definition at line 98 of file SplitView3DInventor.h.
Member Typedef Documentation
BaseType
using Gui::AbstractSplitViewPy::BaseType = Py::PythonExtension<AbstractSplitViewPy>
Definition at line 101 of file SplitView3DInventor.h.
Constructor & Destructor Documentation
AbstractSplitViewPy()
AbstractSplitViewPy::AbstractSplitViewPy (AbstractSplitView * vi)
Definition at line 295 of file SplitView3DInventor.cpp.
~AbstractSplitViewPy()
AbstractSplitViewPy::~AbstractSplitViewPy () override default
Member Function Documentation
cast_to_base()
Py::Object AbstractSplitViewPy::cast_to_base (const Py::Tuple &)
Definition at line 302 of file SplitView3DInventor.cpp.
References Gui::MDIViewPy::create().
Referenced by init_type().
close()
Py::Object AbstractSplitViewPy::close (const Py::Tuple & args)
Definition at line 559 of file SplitView3DInventor.cpp.
References toolbit-attributes::args, and getSplitViewPtr().
Referenced by femsolver.reportdialog.ReportDialog::__init__(), init_type(), TechDrawTools.TaskFillTemplateFields.TaskFillTemplateFields::proceed(), and femexamples.examplesgui.FemExamples::reject().
fitAll()
Py::Object AbstractSplitViewPy::fitAll (const Py::Tuple & args)
Definition at line 350 of file SplitView3DInventor.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, getSplitViewPtr(), and Gui::AbstractSplitView::onMsg().
Referenced by init_type().
getattr()
Py::Object AbstractSplitViewPy::getattr (const char * attr) override
Definition at line 320 of file SplitView3DInventor.cpp.
References SCL.SimpleDataTypes::e, and getSplitViewPtr().
getSplitViewPtr()
AbstractSplitView * AbstractSplitViewPy::getSplitViewPtr ()
Definition at line 342 of file SplitView3DInventor.cpp.
Referenced by close(), fitAll(), getattr(), getViewer(), repr(), sequence_item(), sequence_length(), viewBottom(), viewFront(), viewIsometric(), viewLeft(), viewRear(), viewRight(), and viewTop().
getViewer()
Py::Object AbstractSplitViewPy::getViewer (const Py::Tuple & args)
Definition at line 517 of file SplitView3DInventor.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, Gui::View3DInventorViewer::getPyObject(), getSplitViewPtr(), and Gui::AbstractSplitView::getViewer().
Referenced by init_type().
init_type()
void AbstractSplitViewPy::init_type () static
Definition at line 270 of file SplitView3DInventor.cpp.
References cast_to_base(), close(), fitAll(), getViewer(), viewBottom(), viewFront(), viewIsometric(), viewLeft(), viewRear(), viewRight(), and viewTop().
Referenced by Gui::Application::Application().
repr()
Py::Object AbstractSplitViewPy::repr () override
Definition at line 307 of file SplitView3DInventor.cpp.
References getSplitViewPtr(), and src.Mod.Test.testmakeWireString::String.
sequence_item()
Py::Object AbstractSplitViewPy::sequence_item (Py_ssize_t viewIndex) override
Definition at line 544 of file SplitView3DInventor.cpp.
References Gui::View3DInventorViewer::getPyObject(), Gui::AbstractSplitView::getSize(), getSplitViewPtr(), Gui::AbstractSplitView::getViewer(), and OfflineRenderingUtils::viewer().
sequence_length()
PyCxx_ssize_t AbstractSplitViewPy::sequence_length () override
Definition at line 553 of file SplitView3DInventor.cpp.
References Gui::AbstractSplitView::getSize(), and getSplitViewPtr().
viewBottom()
Py::Object AbstractSplitViewPy::viewBottom (const Py::Tuple & args)
Definition at line 370 of file SplitView3DInventor.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, getSplitViewPtr(), and Gui::AbstractSplitView::onMsg().
Referenced by init_type().
viewFront()
Py::Object AbstractSplitViewPy::viewFront (const Py::Tuple & args)
Definition at line 391 of file SplitView3DInventor.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, getSplitViewPtr(), and Gui::AbstractSplitView::onMsg().
Referenced by init_type().
viewIsometric()
Py::Object AbstractSplitViewPy::viewIsometric (const Py::Tuple & args)
Definition at line 496 of file SplitView3DInventor.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, getSplitViewPtr(), and Gui::AbstractSplitView::onMsg().
Referenced by init_type().
viewLeft()
Py::Object AbstractSplitViewPy::viewLeft (const Py::Tuple & args)
Definition at line 412 of file SplitView3DInventor.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, getSplitViewPtr(), and Gui::AbstractSplitView::onMsg().
Referenced by init_type().
viewRear()
Py::Object AbstractSplitViewPy::viewRear (const Py::Tuple & args)
Definition at line 433 of file SplitView3DInventor.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, getSplitViewPtr(), and Gui::AbstractSplitView::onMsg().
Referenced by init_type().
viewRight()
Py::Object AbstractSplitViewPy::viewRight (const Py::Tuple & args)
Definition at line 454 of file SplitView3DInventor.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, getSplitViewPtr(), and Gui::AbstractSplitView::onMsg().
Referenced by init_type().
viewTop()
Py::Object AbstractSplitViewPy::viewTop (const Py::Tuple & args)
Definition at line 475 of file SplitView3DInventor.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, getSplitViewPtr(), and Gui::AbstractSplitView::onMsg().
Referenced by init_type().
The documentation for this class was generated from the following files:
SplitView3DInventor.h
SplitView3DInventor.cpp