FreeCAD: AppImport.cpp File Reference
AppImport.cpp File Reference
#include "PreCompiled.h"
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include "StepShape.h"
#include "StepShapePy.h"
Namespaces
Import
Functions
PyObject * Import::initModule ()
PyMOD_INIT_FUNC (Import)
Function Documentation
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (Import)
Definition at line 38 of file AppImport.cpp.
References Base::InterpreterSingleton::addType(), Base::Console(), SCL.SimpleDataTypes::e, Import::initModule(), Base::Interpreter(), Base::InterpreterSingleton::loadModule(), Base::ConsoleSingleton::Log(), and PyMOD_Return.