FreeCAD: TechDrawGui::QGIViewAnnotation Class Reference
TechDrawGui::QGIViewAnnotation Class Reference
#include <QGIViewAnnotation.h>
Public Types
enum { Type = QGraphicsItem::UserType + 120 }
Public Types inherited from TechDrawGui::QGIView
enum { Type = QGraphicsItem::UserType + 101 }
Public Member Functions
QGIViewAnnotation ()
~QGIViewAnnotation () override=default
m_textItem belongs to this group and will be deleted by Qt
int type () const override
void updateView (bool update=false) override
void setViewAnnoFeature (TechDraw::DrawViewAnnotation *obj)
void draw () override
void rotateView () override
Public Member Functions inherited from TechDrawGui::QGIView
QGIView ()
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
const char * getViewName () const
const std::string getViewNameAsString () const
void setViewFeature (TechDraw::DrawView *obj)
TechDraw::DrawView * getViewObject () const
MDIViewPage * getMDIViewPage () const
double getScale ()
void hideFrame ()
virtual bool getFrameState ()
virtual void toggleCache (bool state)
virtual void drawBorder ()
virtual void isVisible (bool state)
virtual bool isVisible ()
virtual bool getGroupSelection ()
virtual void setGroupSelection (bool isSelected)
virtual void setGroupSelection (bool isSelected, const std::vector< std::string > &subNames)
virtual void drawCaption ()
void makeMark (double xPos, double yPos, QColor color=Qt::red)
void makeMark (Base::Vector3d pos, QColor color=Qt::red)
void makeMark (QPointF pos, QColor color=Qt::red)
void setPosition (qreal xPos, qreal yPos)
qreal getY ()
bool isInnerView () const
void isInnerView (bool state)
QGIViewClip * getClipGroup ()
bool isSnapping ()
void snapPosition (QPointF &position)
void snapSectionView (const TechDraw::DrawViewSection *sectionView, QPointF &newPosition)
Base::Vector3d projItemPagePos (TechDraw::DrawViewPart *item)
void alignTo (QGraphicsItem *, const QString &alignment)
QColor prefNormalColor ()
QColor getNormalColor ()
void setNormalColor (QColor color)
QColor getPreColor ()
QColor getSelectColor ()
QColor getCurrentColor ()
void setCurrentColor (QColor color)
QColor getSettingColor ()
void setSettingColor (QColor color)
virtual void setStack (int z)
virtual void setStackFromVP ()
QFont getFont ()
void setFont (QFont font)
virtual void removeChild (QGIView *child)
virtual void addArbitraryItem (QGraphicsItem *qgi)
virtual void switchParentItem (QGIView *targetParent)
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
Protected Member Functions
void drawAnnotation ()
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
Protected Member Functions inherited from TechDrawGui::QGIView
QGIView * getQGIVByName (std::string name)
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QRectF customChildrenBoundingRect () const
void dumpRect (const char *text, QRectF rect)
Base::Reference< ParameterGrp > getParmGroupCol ()
Protected Attributes
QGCustomText * m_textItem
QColor m_colNormal
QColor m_colSel
QColor m_colPre
Additional Inherited Members
Static Public Member Functions inherited from TechDrawGui::QGIView
static Gui::ViewProvider * getViewProvider (App::DocumentObject *obj)
static ViewProviderPage * getViewProviderPage (TechDraw::DrawView *dView)
static int calculateFontPixelSize (double sizeInMillimetres)
static int calculateFontPixelWidth (const QFont &font)
static QString getPrefFont ()
static double getPrefFontSize ()
static double getDimFontSize ()
static int exactFontSize (std::string fontFamily, double nominalSize)
Static Public Attributes inherited from TechDrawGui::QGIView
static const double DefaultFontSizeInMM = 5.0
Detailed Description
Definition at line 39 of file QGIViewAnnotation.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 48 of file QGIViewAnnotation.h.
Constructor & Destructor Documentation
QGIViewAnnotation()
QGIViewAnnotation::QGIViewAnnotation () explicit
Definition at line 55 of file QGIViewAnnotation.cpp.
References m_textItem.
~QGIViewAnnotation()
TechDrawGui::QGIViewAnnotation::~QGIViewAnnotation () override default
m_textItem belongs to this group and will be deleted by Qt
Member Function Documentation
draw()
void QGIViewAnnotation::draw () override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 93 of file QGIViewAnnotation.cpp.
References TechDrawGui::QGIView::draw(), drawAnnotation(), TechDrawGui::QGIView::isVisible(), and rotateView().
Referenced by updateView().
drawAnnotation()
void QGIViewAnnotation::drawAnnotation () protected
Definition at line 107 of file QGIViewAnnotation.cpp.
References SCL.SimpleDataTypes::c, TechDrawGui::QGCustomText::centerAt(), Base::Console(), Base::Tools::escapedUnicodeToUtf8(), TechDrawGui::QGIView::exactFontSize(), TechDraw::Preferences::getAccessibleColor(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::Rez::guiX(), m_textItem, and Base::ConsoleSingleton::Warning().
Referenced by draw().
mouseDoubleClickEvent()
void QGIViewAnnotation::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 182 of file QGIViewAnnotation.cpp.
References App::Application::closeActiveTransaction(), App::GetApplication(), Gui::getMainWindow(), TechDrawGui::DlgStringListEditor::getTexts(), App::PropertyListsT< T, ListT, ParentT >::getValues(), TechDrawGui::QGIView::getViewObject(), App::Application::setActiveTransaction(), App::PropertyStringList::setValues(), and TechDraw::DrawViewAnnotation::Text.
rotateView()
void QGIViewAnnotation::rotateView () override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 174 of file QGIViewAnnotation.cpp.
References App::PropertyQuantity::getValue(), TechDrawGui::QGIView::getViewObject(), m_textItem, and TechDraw::DrawView::Rotation.
Referenced by draw().
setViewAnnoFeature()
void QGIViewAnnotation::setViewAnnoFeature (TechDraw::DrawViewAnnotation * obj)
Definition at line 71 of file QGIViewAnnotation.cpp.
References TechDrawGui::QGIView::setViewFeature().
type()
int TechDrawGui::QGIViewAnnotation::type () const inline override
Definition at line 49 of file QGIViewAnnotation.h.
updateView()
void QGIViewAnnotation::updateView (bool update = false) override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 77 of file QGIViewAnnotation.cpp.
References draw(), TechDrawGui::QGIView::getViewObject(), and TechDrawGui::QGIView::updateView().
Member Data Documentation
m_colNormal
QColor TechDrawGui::QGIViewAnnotation::m_colNormal protected
Definition at line 63 of file QGIViewAnnotation.h.
m_colPre
QColor TechDrawGui::QGIViewAnnotation::m_colPre protected
Definition at line 65 of file QGIViewAnnotation.h.
m_colSel
QColor TechDrawGui::QGIViewAnnotation::m_colSel protected
Definition at line 64 of file QGIViewAnnotation.h.
m_textItem
QGCustomText* TechDrawGui::QGIViewAnnotation::m_textItem protected
Definition at line 62 of file QGIViewAnnotation.h.
Referenced by drawAnnotation(), QGIViewAnnotation(), and rotateView().
The documentation for this class was generated from the following files:
QGIViewAnnotation.h
QGIViewAnnotation.cpp