FreeCAD: Gui::DAG Namespace Reference
Gui::DAG Namespace Reference
Classes
class ConnectionVisitor
Get connected components.
class DigRoots
get all the roots of the templated graph. Not used right now.
class DockWindow
dock window for DAG viewer
class Edge_writer
struct EdgeProperty
Graph edge information.
class FilterBase
class FilterOrigin
class FilterTyped
struct GraphLinkRecord
class LineEdit
class Model
class RakeLeaves
get all the leaves of the templated graph. Not used right now.
class RectItem
class Vertex_writer
struct VertexProperty
Graph vertex information.
class View
view for DAG viewer
Typedefs
using ColumnMask = std::bitset< 1024 >
using vertex_prop = boost::property< boost::vertex_index_t, std::size_t, boost::property< boost::vertex_color_t, boost::default_color_type, VertexProperty > >
boost data for each vertex.
using edge_prop = boost::property< boost::edge_index_t, std::size_t, EdgeProperty >
needed to create an internal index for graph edges. needed for setS.
using Graph = boost::adjacency_list< boost::setS, boost::listS, boost::bidirectionalS, vertex_prop, edge_prop >
using Vertex = boost::graph_traits< Graph >::vertex_descriptor
using Edge = boost::graph_traits< Graph >::edge_descriptor
using VertexIterator = boost::graph_traits< Graph >::vertex_iterator
using EdgeIterator = boost::graph_traits< Graph >::edge_iterator
using InEdgeIterator = boost::graph_traits< Graph >::in_edge_iterator
using OutEdgeIterator = boost::graph_traits< Graph >::out_edge_iterator
using VertexAdjacencyIterator = boost::graph_traits< Graph >::adjacency_iterator
using GraphReversed = boost::reverse_graph< Graph, Graph & >
using Path = std::vector< Vertex >
a path or any array of vertices
using GraphLinkContainer = boost::multi_index_container< GraphLinkRecord, BMI::indexed_by< BMI::ordered_unique< BMI::tag< GraphLinkRecord::ByDObject >, BMI::member< GraphLinkRecord, const App::DocumentObject *, &GraphLinkRecord::DObject > >, BMI::ordered_unique< BMI::tag< GraphLinkRecord::ByVPDObject >, BMI::member< GraphLinkRecord, const Gui::ViewProviderDocumentObject *, &GraphLinkRecord::VPDObject > >, BMI::ordered_unique< BMI::tag< GraphLinkRecord::ByRectItem >, BMI::member< GraphLinkRecord, const RectItem *, &GraphLinkRecord::rectItem > >, BMI::ordered_unique< BMI::tag< GraphLinkRecord::ByUniqueName >, BMI::member< GraphLinkRecord, std::string, &GraphLinkRecord::uniqueName > >, BMI::ordered_unique< BMI::tag< GraphLinkRecord::ByVertex >, BMI::member< GraphLinkRecord, Vertex, &GraphLinkRecord::vertex > > > >
Enumerations
enum VisibilityState { VisibilityState::None = 0, VisibilityState::On, VisibilityState::Off }
enum FeatureState { FeatureState::None = 0, FeatureState::Pass, FeatureState::Fail, FeatureState::Pending }
Functions
template<class GraphIn >
void outputGraphviz (const GraphIn &graphIn, const std::string &filePath)
bool hasRecord (const App::DocumentObject *dObjectIn, const GraphLinkContainer &containerIn)
bool hasRecord (const ViewProviderDocumentObject *VPDObjectIn, const GraphLinkContainer &containerIn)
const GraphLinkRecord & findRecord (Vertex vertexIn, const GraphLinkContainer &containerIn)
const GraphLinkRecord & findRecord (const App::DocumentObject *dObjectIn, const GraphLinkContainer &containerIn)
const GraphLinkRecord & findRecord (const Gui::ViewProviderDocumentObject *VPDObjectIn, const GraphLinkContainer &containerIn)
const GraphLinkRecord & findRecord (const RectItem *rectIn, const GraphLinkContainer &containerIn)
const GraphLinkRecord & findRecord (const std::string &stringIn, const GraphLinkContainer &containerIn)
void eraseRecord (const Gui::ViewProviderDocumentObject *VPDObjectIn, GraphLinkContainer &containerIn)
Typedef Documentation
ColumnMask
using Gui::DAG::ColumnMask = typedef std::bitset<1024>
Definition at line 69 of file DAGModelGraph.h.
Edge
using Gui::DAG::Edge = typedef boost::graph_traits<Graph>::edge_descriptor
Definition at line 125 of file DAGModelGraph.h.
edge_prop
using Gui::DAG::edge_prop = typedef boost::property<boost::edge_index_t, std::size_t, EdgeProperty>
needed to create an internal index for graph edges. needed for setS.
Definition at line 121 of file DAGModelGraph.h.
EdgeIterator
using Gui::DAG::EdgeIterator = typedef boost::graph_traits<Graph>::edge_iterator
Definition at line 127 of file DAGModelGraph.h.
Graph
using Gui::DAG::Graph = typedef boost::adjacency_list<boost::setS, boost::listS, boost::bidirectionalS, vertex_prop, edge_prop>
Definition at line 123 of file DAGModelGraph.h.
GraphLinkContainer
using Gui::DAG::GraphLinkContainer = typedef boost::multi_index_container < GraphLinkRecord, BMI::indexed_by < BMI::ordered_unique < BMI::tag<GraphLinkRecord::ByDObject>, BMI::member<GraphLinkRecord, const App::DocumentObject*, &GraphLinkRecord::DObject> >, BMI::ordered_unique < BMI::tag<GraphLinkRecord::ByVPDObject>, BMI::member<GraphLinkRecord, const Gui::ViewProviderDocumentObject*, &GraphLinkRecord::VPDObject> >, BMI::ordered_unique < BMI::tag<GraphLinkRecord::ByRectItem>, BMI::member<GraphLinkRecord, const RectItem*, &GraphLinkRecord::rectItem> >, BMI::ordered_unique < BMI::tag<GraphLinkRecord::ByUniqueName>, BMI::member<GraphLinkRecord, std::string, &GraphLinkRecord::uniqueName> >, BMI::ordered_unique < BMI::tag<GraphLinkRecord::ByVertex>, BMI::member<GraphLinkRecord, Vertex, &GraphLinkRecord::vertex> > > >
Definition at line 284 of file DAGModelGraph.h.
GraphReversed
using Gui::DAG::GraphReversed = typedef boost::reverse_graph<Graph, Graph&>
Definition at line 131 of file DAGModelGraph.h.
InEdgeIterator
using Gui::DAG::InEdgeIterator = typedef boost::graph_traits<Graph>::in_edge_iterator
Definition at line 128 of file DAGModelGraph.h.
OutEdgeIterator
using Gui::DAG::OutEdgeIterator = typedef boost::graph_traits<Graph>::out_edge_iterator
Definition at line 129 of file DAGModelGraph.h.
Path
using Gui::DAG::Path = typedef std::vector<Vertex>
a path or any array of vertices
Definition at line 132 of file DAGModelGraph.h.
Vertex
using Gui::DAG::Vertex = typedef boost::graph_traits<Graph>::vertex_descriptor
Definition at line 124 of file DAGModelGraph.h.
vertex_prop
using Gui::DAG::vertex_prop = typedef boost::property < boost::vertex_index_t, std::size_t, boost::property <boost::vertex_color_t, boost::default_color_type, VertexProperty> >
boost data for each vertex.
needed to create an internal index for vertex. needed for listS. color is needed by some algorithms
Definition at line 100 of file DAGModelGraph.h.
VertexAdjacencyIterator
using Gui::DAG::VertexAdjacencyIterator = typedef boost::graph_traits<Graph>::adjacency_iterator
Definition at line 130 of file DAGModelGraph.h.
VertexIterator
using Gui::DAG::VertexIterator = typedef boost::graph_traits<Graph>::vertex_iterator
Definition at line 126 of file DAGModelGraph.h.
Enumeration Type Documentation
FeatureState
enum Gui::DAG::FeatureState strong
Enumerator
None
Pass
Fail
Pending
Definition at line 58 of file DAGModelGraph.h.
VisibilityState
enum Gui::DAG::VisibilityState strong
Enumerator
None
On
Off
Definition at line 51 of file DAGModelGraph.h.
Function Documentation
eraseRecord()
void Gui::DAG::eraseRecord (const Gui::ViewProviderDocumentObject * VPDObjectIn, GraphLinkContainer & containerIn)
Definition at line 111 of file DAGModelGraph.cpp.
References Path.Post.scripts.grbl_post::type.
findRecord() [1/5]
const GraphLinkRecord & Gui::DAG::findRecord (const App::DocumentObject * dObjectIn, const GraphLinkContainer & containerIn)
Definition at line 75 of file DAGModelGraph.cpp.
References Path.Post.scripts.grbl_post::type.
findRecord() [2/5]
const GraphLinkRecord & Gui::DAG::findRecord (const Gui::ViewProviderDocumentObject * VPDObjectIn, const GraphLinkContainer & containerIn)
Definition at line 84 of file DAGModelGraph.cpp.
References Path.Post.scripts.grbl_post::type.
findRecord() [3/5]
const GraphLinkRecord & Gui::DAG::findRecord (const RectItem * rectIn, const GraphLinkContainer & containerIn)
Definition at line 93 of file DAGModelGraph.cpp.
References Path.Post.scripts.grbl_post::type.
findRecord() [4/5]
const GraphLinkRecord & Gui::DAG::findRecord (const std::string & stringIn, const GraphLinkContainer & containerIn)
Definition at line 102 of file DAGModelGraph.cpp.
References Path.Post.scripts.grbl_post::type.
findRecord() [5/5]
const GraphLinkRecord & Gui::DAG::findRecord (Vertex vertexIn, const GraphLinkContainer & containerIn)
Definition at line 66 of file DAGModelGraph.cpp.
References Path.Post.scripts.grbl_post::type.
Referenced by Gui::DAG::Model::contextMenuEvent(), Gui::DAG::FilterOrigin::goFilter(), Gui::DAG::FilterTyped::goFilter(), Gui::DAG::Model::mouseDoubleClickEvent(), Gui::DAG::Model::mousePressEvent(), and Gui::DAG::Model::selectionChanged().
hasRecord() [1/2]
bool Gui::DAG::hasRecord (const App::DocumentObject * dObjectIn, const GraphLinkContainer & containerIn)
Definition at line 50 of file DAGModelGraph.cpp.
References Path.Post.scripts.grbl_post::type.
hasRecord() [2/2]
bool Gui::DAG::hasRecord (const ViewProviderDocumentObject * VPDObjectIn, const GraphLinkContainer & containerIn)
Definition at line 58 of file DAGModelGraph.cpp.
References Path.Post.scripts.grbl_post::type.
outputGraphviz()
template<class GraphIn > void Gui::DAG::outputGraphviz (const GraphIn & graphIn, const std::string & filePath)
Definition at line 165 of file DAGModelGraph.h.
References DrawingExample::file, and Path.Preferences::filePath().