FreeCAD: Data::ByteArray Struct Reference
Data::ByteArray Struct Reference
#include <IndexedName.h>
Public Member Functions
ByteArray (QByteArray other)
ByteArray (const ByteArray &other)=default
ByteArray (ByteArray &&other) noexcept
~ByteArray ()=default
void ensureUnshared () const
Guarantee that the stored QByteArray does not share its memory with another instance.
bool operator== (const ByteArray &other) const
ByteArray & operator= (const ByteArray &other)
ByteArray & operator= (ByteArray &&other) noexcept
Public Attributes
QByteArray bytes
Detailed Description
A thin wrapper around a QByteArray providing the ability to force a copy of the data at any time, even if it isn't being written to. The standard assignment operator for this class does make a copy of the data, unlike the standard assignment operator for QByteArray.
Definition at line 325 of file IndexedName.h.
Constructor & Destructor Documentation
ByteArray() [1/3]
Data::ByteArray::ByteArray (QByteArray other) inline explicit
Definition at line 327 of file IndexedName.h.
References bytes.
Referenced by Data::IndexedName::isNull().
ByteArray() [2/3]
Data::ByteArray::ByteArray (const ByteArray & other) default
ByteArray() [3/3]
Data::ByteArray::ByteArray (ByteArray && other) inline noexcept
Definition at line 333 of file IndexedName.h.
References bytes.
~ByteArray()
Data::ByteArray::~ByteArray () default
Member Function Documentation
ensureUnshared()
void Data::ByteArray::ensureUnshared () const inline
Guarantee that the stored QByteArray does not share its memory with another instance.
Definition at line 340 of file IndexedName.h.
References bytes, and Path.Post.scripts.opensbp_post::move().
operator=() [1/2]
ByteArray& Data::ByteArray::operator= (ByteArray && other) inline noexcept
Definition at line 359 of file IndexedName.h.
operator=() [2/2]
ByteArray& Data::ByteArray::operator= (const ByteArray & other) inline
Definition at line 352 of file IndexedName.h.
References bytes.
operator==()
bool Data::ByteArray::operator== (const ByteArray & other) const inline
Definition at line 347 of file IndexedName.h.
References Data::ByteArrayHasher::operator()().
Member Data Documentation
bytes
QByteArray Data::ByteArray::bytes mutable
Definition at line 365 of file IndexedName.h.
Referenced by ByteArray(), ensureUnshared(), Data::IndexedName::isNull(), and operator=().
The documentation for this struct was generated from the following file:
IndexedName.h