FreeCAD: App::PropertyMap Class Reference
App::PropertyMap Class Reference
#include <PropertyStandard.h>
Public Member Functions
PropertyMap ()
~PropertyMap () override
virtual int getSize () const
void setValue ()
void setValue (const std::string &key, const std::string &value)
void setValues (const std::map< std::string, std::string > &)
const std::string & operator[] (const std::string &key) const
index operator
void set1Value (const std::string &key, const std::string &value)
const std::map< std::string, std::string > & getValues () const
PyObject * getPyObject () override
void setPyObject (PyObject *py) override
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
Property * Copy () const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
unsigned int getMemSize () const override
bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
Public Member Functions inherited from App::Property
Property ()
~Property () override
const char * getName () const
bool hasName () const
std::string getFullName () const
virtual const char * getEditorName () const
Get the class name of the associated property editor item.
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual void afterRestore ()
virtual void onContainerRestored ()
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
int64_t getID () const
virtual void beforeSave () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::Property
virtual void hasSetValue ()
Gets called by all setValue() methods after the value has changed.
virtual void aboutToSetValue ()
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Detailed Description
implements a key/value list as property The key ought to be ASCII the Value should be treated as UTF8 to be saved.
Definition at line 468 of file PropertyStandard.h.
Constructor & Destructor Documentation
PropertyMap()
PropertyMap::PropertyMap () default
A constructor. A more elaborate description of the constructor.
~PropertyMap()
PropertyMap::~PropertyMap () override default
A destructor. A more elaborate description of the destructor.
Member Function Documentation
Copy()
Property * PropertyMap::Copy () const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 2015 of file PropertyStandard.cpp.
References buildPsets::p.
getMemSize()
unsigned int PropertyMap::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence
See also
Base::Persistence
Reimplemented from App::Property.
Definition at line 1973 of file PropertyStandard.cpp.
getPyObject()
PyObject * PropertyMap::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 1910 of file PropertyStandard.cpp.
References Path.Base.SetupSheet::dict.
getSize()
int PropertyMap::getSize () const virtual
Definition at line 1881 of file PropertyStandard.cpp.
getValues()
const std::map<std::string, std::string>& App::PropertyMap::getValues () const inline
Definition at line 502 of file PropertyStandard.h.
Referenced by TechDrawGui::QGISVGTemplate::createClickHandles(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::loadDefaults(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle(), and TechDraw::DrawSVGTemplate::processTemplate().
isSame()
bool App::PropertyMap::isSame (const Property & other) const inline override virtual
Compare if this property has the same content as the given one.
Reimplemented from App::Property.
Definition at line 521 of file PropertyStandard.h.
References Base::Persistence::getTypeId().
operator[]()
const std::string & PropertyMap::operator[] (const std::string & key) const
index operator
Definition at line 1900 of file PropertyStandard.cpp.
Paste()
void PropertyMap::Paste (const Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 2022 of file PropertyStandard.cpp.
Restore()
void PropertyMap::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 1996 of file PropertyStandard.cpp.
References src.Mod.AddonManager.NetworkManager::count, SplineSurface::i, and TechDrawTools.TaskFillTemplateFields::reader.
Save()
void PropertyMap::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 1983 of file PropertyStandard.cpp.
References Base::Writer::decInd(), Base::Writer::incInd(), Base::Writer::ind(), and Base::Writer::Stream().
set1Value()
void App::PropertyMap::set1Value (const std::string & key, const std::string & value) inline
Definition at line 497 of file PropertyStandard.h.
setPyObject()
void PropertyMap::setPyObject (PyObject * py) override virtual
Reimplemented from Base::BaseClass.
Definition at line 1927 of file PropertyStandard.cpp.
References Path.Log::error(), and SplineSurface::i.
setValue() [1/2]
void App::PropertyMap::setValue () inline
Sets the property
Definition at line 489 of file PropertyStandard.h.
Referenced by TechDrawGui::TemplateTextField::mouseReleaseEvent().
setValue() [2/2]
void PropertyMap::setValue (const std::string & key, const std::string & value)
Definition at line 1886 of file PropertyStandard.cpp.
setValues()
void PropertyMap::setValues (const std::map< std::string, std::string > & map)
Definition at line 1893 of file PropertyStandard.cpp.
Referenced by TechDraw::DrawSVGTemplate::onChanged(), and draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle().
The documentation for this class was generated from the following files:
PropertyStandard.h
PropertyStandard.cpp