FreeCAD: Gui::LinkInfo Class Reference
Gui::LinkInfo Class Reference
Public Types
using Connection = boost::signals2::scoped_connection
using Pointer = LinkInfoPtr
using NodeMap = std::unordered_map< SoNode *, Pointer >
Public Member Functions
LinkInfo (ViewProviderDocumentObject *vp)
~LinkInfo ()=default
bool checkName (const char *name) const
void remove (LinkOwner *owner)
bool isLinked () const
const char * getLinkedName () const
const char * getLinkedLabel () const
const char * getLinkedNameSafe () const
const char * getDocName () const
void detach (bool unlink)
void updateSwitch (SoSwitch *node=nullptr)
void addref ()
void release ()
bool isVisible () const
void setVisible (bool visible)
SoSeparator * getSnapshot (int type, bool update=false)
void updateData (const App::Property *prop)
void update ()
void updateChildren ()
bool getElementPicked (bool addname, int type, const SoPickedPoint *pp, std::ostream &str) const
bool getDetail (bool checkname, int type, const char *subname, SoDetail *&det, SoFullPath *path) const
void slotChangeIcon ()
QIcon getIcon (QPixmap px)
Static Public Member Functions
static ViewProviderDocumentObject * getView (App::DocumentObject *obj)
static Pointer get (App::DocumentObject *obj, Gui::LinkOwner *owner)
static Pointer get (ViewProviderDocumentObject *vp, LinkOwner *owner)
static void sensorCB (void *data, SoSensor *)
static void switchSensorCB (void *data, SoSensor *)
static void childSensorCB (void *data, SoSensor *)
static void transformSensorCB (void *data, SoSensor *)
static const char * checkSubname (App::DocumentObject *obj, const char *subname)
Public Attributes
std::atomic< int > ref
Connection connChangeIcon
ViewProviderDocumentObject * pcLinked
std::unordered_set< Gui::LinkOwner * > links
SoNodeSensor sensor
SoNodeSensor switchSensor
SoNodeSensor childSensor
SoNodeSensor transformSensor
std::array< CoinPtr< SoSeparator >, LinkView::SnapshotMax > pcSnapshots
std::array< CoinPtr< SoSwitch >, LinkView::SnapshotMax > pcSwitches
CoinPtr< SoSwitch > pcLinkedSwitch
CoinPtr< SoGroup > pcChildGroup
NodeMap nodeMap
std::map< qint64, QIcon > iconMap
Friends
void intrusive_ptr_add_ref (LinkInfo *px)
void intrusive_ptr_release (LinkInfo *px)
Detailed Description
Definition at line 109 of file ViewProviderLink.cpp.
Member Typedef Documentation
Connection
using Gui::LinkInfo::Connection = boost::signals2::scoped_connection
Definition at line 114 of file ViewProviderLink.cpp.
NodeMap
using Gui::LinkInfo::NodeMap = std::unordered_map<SoNode *, Pointer>
Definition at line 133 of file ViewProviderLink.cpp.
Pointer
using Gui::LinkInfo::Pointer = LinkInfoPtr
Definition at line 120 of file ViewProviderLink.cpp.
Constructor & Destructor Documentation
LinkInfo()
Gui::LinkInfo::LinkInfo (ViewProviderDocumentObject * vp) inline
Definition at line 194 of file ViewProviderLink.cpp.
References draftgeoutils.faces::bind(), childSensor, childSensorCB(), connChangeIcon, FC_LOG, Gui::ViewProviderDocumentObject::forceUpdate(), App::DocumentObject::getFullName(), Gui::ViewProviderDocumentObject::getObject(), pcLinked, sensor, sensorCB(), Gui::ViewProvider::signalChangeIcon, slotChangeIcon(), switchSensor, switchSensorCB(), transformSensor, and transformSensorCB().
Referenced by get().
~LinkInfo()
Gui::LinkInfo::~LinkInfo () default
Member Function Documentation
addref()
void Gui::LinkInfo::addref () inline
Definition at line 294 of file ViewProviderLink.cpp.
References ref.
checkName()
bool Gui::LinkInfo::checkName (const char * name) const inline
Definition at line 215 of file ViewProviderLink.cpp.
References getLinkedName(), and isLinked().
checkSubname()
static const char* Gui::LinkInfo::checkSubname (App::DocumentObject * obj, const char * subname) inline static
Definition at line 528 of file ViewProviderLink.cpp.
References CHECK_NAME, and App::DocumentObject::getNameInDocument().
Referenced by getDetail().
childSensorCB()
static void Gui::LinkInfo::childSensorCB (void * data, SoSensor *) inline static
Definition at line 182 of file ViewProviderLink.cpp.
References updateChildren().
Referenced by LinkInfo().
detach()
void Gui::LinkInfo::detach (bool unlink) inline
Definition at line 246 of file ViewProviderLink.cpp.
References childSensor, Gui::coinRemoveAllChildren(), connChangeIcon, FC_LOG, getLinkedNameSafe(), links, pcChildGroup, pcLinked, pcLinkedSwitch, pcSnapshots, pcSwitches, sensor, switchSensor, and transformSensor.
Referenced by release().
get() [1/2]
static Pointer Gui::LinkInfo::get (App::DocumentObject * obj, Gui::LinkOwner * owner) inline static
Definition at line 150 of file ViewProviderLink.cpp.
References getView().
Referenced by Gui::ViewProviderLink::attach(), Gui::LinkView::SubInfo::link(), Gui::LinkView::Element::link(), draftguitools.gui_trackers.editTracker::move(), Gui::ViewProviderLink::onChanged(), Gui::LinkView::setLinkViewObject(), Gui::LinkView::setOwner(), and updateChildren().
get() [2/2]
static Pointer Gui::LinkInfo::get (ViewProviderDocumentObject * vp, LinkOwner * owner) inline static
Definition at line 154 of file ViewProviderLink.cpp.
References create_qrc::ext, App::ExtensionContainer::getExtensionByType(), and LinkInfo().
Referenced by draftguitools.gui_trackers.editTracker::move().
getDetail()
bool Gui::LinkInfo::getDetail (bool checkname, int type, const char * subname, SoDetail *& det, SoFullPath * path) const inline
Definition at line 547 of file ViewProviderLink.cpp.
References appendPath, appendPathSafe(), checkSubname(), dot(), FC_ERR, Gui::ViewProvider::getChildRoot(), Gui::ViewProviderDocumentObject::getDetailPath(), Gui::ViewProviderDocumentObject::getObject(), Gui::Application::getViewProvider(), Gui::Application::Instance, isLinked(), Data::isMappedElement(), nodeMap, pcChildGroup, pcLinked, pcSnapshots, pcSwitches, Gui::LinkView::SnapshotChild, Gui::LinkView::SnapshotVisible, Path.Post.scripts.grbl_post::type, and TestSpreadsheet::v.
getDocName()
const char* Gui::LinkInfo::getDocName () const inline
Definition at line 242 of file ViewProviderLink.cpp.
References Gui::ViewProviderDocumentObject::getDocument(), Gui::Document::getDocument(), App::Document::getName(), and pcLinked.
getElementPicked()
bool Gui::LinkInfo::getElementPicked (bool addname, int type, const SoPickedPoint * pp, std::ostream & str) const inline
Definition at line 498 of file ViewProviderLink.cpp.
References Gui::ViewProviderDocumentObject::getElementPicked(), getLinkedName(), isLinked(), Gui::ViewProvider::isSelectable(), nodeMap, pcChildGroup, pcLinked, pcSwitches, Gui::LinkView::SnapshotChild, Path.Post.scripts.refactored_centroid_post::str, and Path.Post.scripts.grbl_post::type.
getIcon()
QIcon Gui::LinkInfo::getIcon (QPixmap px) inline
Definition at line 669 of file ViewProviderLink.cpp.
References Gui::BitmapFactory(), Gui::BitmapFactoryInst::BottomLeft, Gui::ViewProvider::getIcon(), iconMap, isLinked(), geoff_geometry::Normal(), geoff_geometry::On(), and pcLinked.
Referenced by ArchAxisSystem.AxisSystemTaskPanel::update(), ArchWindow._ArchWindowTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), bimcommands.BimClassification.BIM_Classification::updateByMaterial(), bimcommands.BimClassification.BIM_Classification::updateByTree(), bimcommands.BimClassification.BIM_Classification::updateByType(), and bimcommands.BimClassification.BIM_Classification::updateDefault().
getLinkedLabel()
const char* Gui::LinkInfo::getLinkedLabel () const inline
Definition at line 232 of file ViewProviderLink.cpp.
References Gui::ViewProviderDocumentObject::getObject(), App::PropertyString::getValue(), App::DocumentObject::Label, and pcLinked.
getLinkedName()
const char* Gui::LinkInfo::getLinkedName () const inline
Definition at line 228 of file ViewProviderLink.cpp.
References App::DocumentObject::getDagKey(), Gui::ViewProviderDocumentObject::getObject(), and pcLinked.
Referenced by checkName(), getElementPicked(), and getLinkedNameSafe().
getLinkedNameSafe()
const char* Gui::LinkInfo::getLinkedNameSafe () const inline
Definition at line 236 of file ViewProviderLink.cpp.
References getLinkedName(), and isLinked().
Referenced by detach(), and release().
getSnapshot()
SoSeparator* Gui::LinkInfo::getSnapshot (int type, bool update = false) inline
Definition at line 357 of file ViewProviderLink.cpp.
References Gui::coinRemoveAllChildren(), src.Mod.AddonManager.NetworkManager::count, Gui::ViewProvider::getChildRoot(), Gui::ViewProvider::getModeSwitch(), App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), Gui::ViewProvider::getRoot(), Gui::ViewProvider::getTransformNode(), SplineSurface::i, Gui::ViewParams::instance(), isLinked(), MeshCore::MeshIO::OFF, pcChildGroup, pcLinked, pcLinkedSwitch, pcSnapshots, pcSwitches, sensor, Gui::LinkView::SnapshotMax, Gui::LinkView::SnapshotTransform, switchSensor, transformSensor, Path.Post.scripts.grbl_post::type, update(), and updateSwitch().
Referenced by transformSensorCB(), and update().
getView()
static ViewProviderDocumentObject* Gui::LinkInfo::getView (App::DocumentObject * obj) inline static
Definition at line 138 of file ViewProviderLink.cpp.
References Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::Document::getViewProvider(), Gui::Application::Instance, App::DocumentObject::isAttachedToDocument(), and Base::BaseClass::isDerivedFrom().
Referenced by get().
isLinked()
bool Gui::LinkInfo::isLinked () const inline
Definition at line 223 of file ViewProviderLink.cpp.
References Gui::ViewProviderDocumentObject::getObject(), App::DocumentObject::isAttachedToDocument(), and pcLinked.
Referenced by checkName(), getDetail(), getElementPicked(), getIcon(), getLinkedNameSafe(), getSnapshot(), isVisible(), setVisible(), slotChangeIcon(), update(), updateChildren(), and updateSwitch().
isVisible()
bool Gui::LinkInfo::isVisible () const inline
Definition at line 330 of file ViewProviderLink.cpp.
References isLinked(), pcSwitches, Gui::LinkView::SnapshotTransform, and Gui::LinkView::SnapshotVisible.
Referenced by ArchVRM.Renderer::removeHidden().
release()
void Gui::LinkInfo::release () inline
Definition at line 298 of file ViewProviderLink.cpp.
References detach(), create_qrc::ext, FC_LOG, Gui::ViewProviderDocumentObject::forceUpdate(), App::ExtensionContainer::getExtensionByType(), getLinkedNameSafe(), pcLinked, and ref.
remove()
void Gui::LinkInfo::remove (LinkOwner * owner) inline
Definition at line 219 of file ViewProviderLink.cpp.
References links.
Referenced by src.Mod.AddonManager.AddonManager.CommandAddonManager::launch().
sensorCB()
static void Gui::LinkInfo::sensorCB (void * data, SoSensor *) inline static
Definition at line 174 of file ViewProviderLink.cpp.
References update().
Referenced by LinkInfo().
setVisible()
void Gui::LinkInfo::setVisible (bool visible) inline
Definition at line 343 of file ViewProviderLink.cpp.
References Gui::ViewProvider::getDefaultMode(), isLinked(), pcLinked, pcSwitches, Gui::LinkView::SnapshotTransform, and Gui::LinkView::SnapshotVisible.
slotChangeIcon()
void Gui::LinkInfo::slotChangeIcon () inline
Definition at line 660 of file ViewProviderLink.cpp.
References iconMap, isLinked(), and links.
Referenced by LinkInfo().
switchSensorCB()
static void Gui::LinkInfo::switchSensorCB (void * data, SoSensor *) inline static
Definition at line 178 of file ViewProviderLink.cpp.
References updateSwitch().
Referenced by LinkInfo().
transformSensorCB()
static void Gui::LinkInfo::transformSensorCB (void * data, SoSensor *) inline static
Definition at line 186 of file ViewProviderLink.cpp.
References getSnapshot(), SplineSurface::i, and Gui::LinkView::SnapshotTransform.
Referenced by LinkInfo().
update()
void Gui::LinkInfo::update () inline
Definition at line 451 of file ViewProviderLink.cpp.
References getSnapshot(), SplineSurface::i, isLinked(), Gui::ViewProvider::isRestoring(), pcLinked, pcSnapshots, and updateChildren().
Referenced by bimcommands.BimViews.BIM_Views::Activated(), ArchAxisSystem.AxisSystemTaskPanel::addElement(), ArchSectionPlane.SectionPlaneTaskPanel::addElement(), DraftGui.FacebinderTaskPanel::addElement(), ArchComponent.ComponentTaskPanel::addElement(), bimcommands.BimViews.BIM_Views::addLevel(), bimcommands.BimViews.BIM_Views::addProxy(), femtaskpanels.task_result_mechanical._TaskPanel::calculate(), bimcommands.BimIfcElements.BIM_IfcElements::checkMatChanged(), ArchWindow._ArchWindowTaskPanel::create(), bimcommands.BimViews.BIM_Views::delete(), draftguitools.gui_edit.Edit::endEditing(), bimcommands.BimWall.Arch_Wall::getPoint(), ArchStructure._CommandStructure::getPoint(), getSnapshot(), draftguitools.gui_trackers.boxTracker::height(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimTutorial.BIM_Tutorial::next(), bimcommands.BimIfcElements.BIM_IfcElements::onMaterialChanged(), bimcommands.BimIfcElements.BIM_IfcElements::onObjectTypeChanged(), bimcommands.BimIfcProperties.BIM_IfcProperties::onSelected(), bimcommands.BimIfcProperties.BIM_IfcProperties::onVisible(), draftguitools.gui_trackers.rectangleTracker::p3(), Plot.Plot::plot(), bimcommands.BimTutorial.BIM_Tutorial::previous(), ArchAxisSystem.AxisSystemTaskPanel::removeElement(), ArchAxis._AxisTaskPanel::removeElement(), ArchWindow._ArchWindowTaskPanel::removeElement(), ArchSectionPlane.SectionPlaneTaskPanel::removeElement(), DraftGui.FacebinderTaskPanel::removeElement(), ArchComponent.ComponentTaskPanel::removeElement(), draftguitools.gui_trackers.gridTracker::reset(), ArchRoof._RoofTaskPanel::resetObject(), ArchNesting.Nester::run(), sensorCB(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setDescription(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setHeight(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setLabel(), draftguitools.gui_trackers.gridTracker::setMainlines(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setMaterial(), draftguitools.gui_trackers.gridTracker::setSize(), draftguitools.gui_trackers.gridTracker::setSpacing(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setTag(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setWidth(), and bimcommands.BimViews.BIM_Views::update().
updateChildren()
void Gui::LinkInfo::updateChildren () inline
Definition at line 462 of file ViewProviderLink.cpp.
References childSensor, Gui::ViewProvider::claimChildren3D(), Gui::coinRemoveAllChildren(), get(), Gui::ViewProvider::getChildRoot(), Path.Log::info(), isLinked(), nodeMap, pcChildGroup, pcLinked, and Gui::LinkView::SnapshotChild.
Referenced by childSensorCB(), and update().
updateData()
void Gui::LinkInfo::updateData (const App::Property * prop) inline
Definition at line 444 of file ViewProviderLink.cpp.
References links.
Referenced by Path.Main.Gui.JobDlg.JobCreate::exec_(), draftviewproviders.view_wire.ViewProviderWire::onChanged(), draftviewproviders.view_dimension.ViewProviderLinearDimension::onChanged(), draftviewproviders.view_dimension.ViewProviderAngularDimension::onChanged(), Path.Op.Gui.Base.TaskPanelPage::pageUpdateData(), Path.Base.Gui.SetupSheet.OpTaskPanel::setupUi(), and Path.Base.Gui.PropertyBag.TaskPanel::setupUi().
updateSwitch()
void Gui::LinkInfo::updateSwitch (SoSwitch * node = nullptr) inline
Definition at line 277 of file ViewProviderLink.cpp.
References src.Mod.AddonManager.NetworkManager::count, Gui::ViewProvider::getDefaultMode(), SplineSurface::i, isLinked(), pcLinked, pcLinkedSwitch, pcSwitches, and Gui::LinkView::SnapshotChild.
Referenced by getSnapshot(), and switchSensorCB().
Friends And Related Function Documentation
intrusive_ptr_add_ref
void intrusive_ptr_add_ref (LinkInfo * px) friend
Definition at line 326 of file ViewProviderLink.cpp.
intrusive_ptr_release
void intrusive_ptr_release (LinkInfo * px) friend
Definition at line 327 of file ViewProviderLink.cpp.
Member Data Documentation
childSensor
SoNodeSensor Gui::LinkInfo::childSensor
Definition at line 124 of file ViewProviderLink.cpp.
Referenced by detach(), LinkInfo(), and updateChildren().
connChangeIcon
Connection Gui::LinkInfo::connChangeIcon
Definition at line 115 of file ViewProviderLink.cpp.
Referenced by detach(), and LinkInfo().
iconMap
std::map<qint64, QIcon> Gui::LinkInfo::iconMap
Definition at line 136 of file ViewProviderLink.cpp.
Referenced by getIcon(), and slotChangeIcon().
links
std::unordered_set<Gui::LinkOwner*> Gui::LinkInfo::links
Definition at line 118 of file ViewProviderLink.cpp.
Referenced by detach(), remove(), slotChangeIcon(), and updateData().
nodeMap
NodeMap Gui::LinkInfo::nodeMap
Definition at line 134 of file ViewProviderLink.cpp.
Referenced by getDetail(), getElementPicked(), and updateChildren().
pcChildGroup
CoinPtr<SoGroup> Gui::LinkInfo::pcChildGroup
Definition at line 132 of file ViewProviderLink.cpp.
Referenced by detach(), getDetail(), getElementPicked(), getSnapshot(), and updateChildren().
pcLinked
ViewProviderDocumentObject* Gui::LinkInfo::pcLinked
Definition at line 117 of file ViewProviderLink.cpp.
Referenced by detach(), getDetail(), getDocName(), getElementPicked(), getIcon(), getLinkedLabel(), getLinkedName(), getSnapshot(), isLinked(), LinkInfo(), release(), setVisible(), update(), updateChildren(), and updateSwitch().
pcLinkedSwitch
CoinPtr<SoSwitch> Gui::LinkInfo::pcLinkedSwitch
Definition at line 129 of file ViewProviderLink.cpp.
Referenced by detach(), getSnapshot(), and updateSwitch().
pcSnapshots
std::array<CoinPtr<SoSeparator>,LinkView::SnapshotMax> Gui::LinkInfo::pcSnapshots
Definition at line 127 of file ViewProviderLink.cpp.
Referenced by detach(), getDetail(), getSnapshot(), and update().
pcSwitches
std::array<CoinPtr<SoSwitch>,LinkView::SnapshotMax> Gui::LinkInfo::pcSwitches
Definition at line 128 of file ViewProviderLink.cpp.
Referenced by detach(), getDetail(), getElementPicked(), getSnapshot(), isVisible(), setVisible(), and updateSwitch().
ref
std::atomic<int> Gui::LinkInfo::ref
Definition at line 112 of file ViewProviderLink.cpp.
Referenced by addref(), and release().
sensor
SoNodeSensor Gui::LinkInfo::sensor
Definition at line 122 of file ViewProviderLink.cpp.
Referenced by detach(), getSnapshot(), and LinkInfo().
switchSensor
SoNodeSensor Gui::LinkInfo::switchSensor
Definition at line 123 of file ViewProviderLink.cpp.
Referenced by detach(), getSnapshot(), and LinkInfo().
transformSensor
SoNodeSensor Gui::LinkInfo::transformSensor
Definition at line 125 of file ViewProviderLink.cpp.
Referenced by detach(), getSnapshot(), and LinkInfo().
The documentation for this class was generated from the following file:
ViewProviderLink.cpp