FreeCAD: FemGui::SphereWidget Class Reference
FemGui::SphereWidget Class Reference
#include <ViewProviderFemPostFunction.h>
Public Member Functions
SphereWidget ()
~SphereWidget () override
void applyPythonCode () override
void onChange (const App::Property &p) override
void setViewProvider (ViewProviderFemPostFunction *view) override
Public Member Functions inherited from FemGui::FunctionWidget
FunctionWidget ()=default
~FunctionWidget () override=default
void onObjectsChanged (const App::DocumentObject &obj, const App::Property &)
Additional Inherited Members
Protected Member Functions inherited from FemGui::FunctionWidget
ViewProviderFemPostFunction * getView ()
Fem::FemPostFunction * getObject () const
template<class T >
T * getObject () const
bool blockObjectUpdates ()
void setBlockObjectUpdates (bool val)
Detailed Description
Definition at line 315 of file ViewProviderFemPostFunction.h.
Constructor & Destructor Documentation
SphereWidget()
SphereWidget::SphereWidget ()
Definition at line 1052 of file ViewProviderFemPostFunction.cpp.
References draftgeoutils.intersections::connect(), Base::UnitsApi::getDecimals(), and Gui::QuantitySpinBox::valueChanged().
~SphereWidget()
SphereWidget::~SphereWidget () override default
Member Function Documentation
applyPythonCode()
void SphereWidget::applyPythonCode () override virtual
Implements FemGui::FunctionWidget.
Definition at line 1088 of file ViewProviderFemPostFunction.cpp.
onChange()
void SphereWidget::onChange (const App::Property & p) override virtual
Implements FemGui::FunctionWidget.
Definition at line 1107 of file ViewProviderFemPostFunction.cpp.
References Fem::FemPostSphereFunction::Center, getValue(), buildPsets::p, Fem::FemPostSphereFunction::Radius, FemGui::FunctionWidget::setBlockObjectUpdates(), toolbit-attributes::val, and SurfaceTests.TestBlendCurve::vec.
Referenced by setViewProvider().
setViewProvider()
void SphereWidget::setViewProvider (ViewProviderFemPostFunction * view) override virtual
Reimplemented from FemGui::FunctionWidget.
Definition at line 1091 of file ViewProviderFemPostFunction.cpp.
References Fem::FemPostSphereFunction::Center, App::PropertyQuantity::getUnit(), App::PropertyVectorDistance::getUnit(), onChange(), Fem::FemPostSphereFunction::Radius, FemGui::FunctionWidget::setBlockObjectUpdates(), FemGui::FunctionWidget::setViewProvider(), and unit().
The documentation for this class was generated from the following files:
ViewProviderFemPostFunction.h
ViewProviderFemPostFunction.cpp