FreeCAD: TechDrawGui::TemplateTextField Class Reference
TechDrawGui::TemplateTextField Class Reference
QGraphicsItemGroupm-derived class for the text fields in title blocks.
#include <TemplateTextField.h>
Public Types
enum { Type = QGraphicsItem::UserType + 160 }
Public Member Functions
TemplateTextField (QGraphicsItem *parent, TechDraw::DrawTemplate *myTmplte, const std::string &myFieldName)
~TemplateTextField () override=default
int type () const override
std::string fieldName () const
Returns the field name that this TemplateTextField represents.
void setAutofill (QString autofillString)
void setRectangle (QRectF rect)
void setLine (QPointF from, QPointF to)
void setLineColor (QColor color)
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
Need this to properly handle mouse release.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
Trigger the dialog for editing template text.
Protected Attributes
TechDraw::DrawTemplate * tmplte
std::string fieldNameStr
QString m_autofillString
QGraphicsRectItem * m_rect
QGraphicsPathItem * m_line
Detailed Description
QGraphicsItemGroupm-derived class for the text fields in title blocks.
Makes an area on the drawing that's clickable, so appropriate Properties of the template can be modified.
Definition at line 43 of file TemplateTextField.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 52 of file TemplateTextField.h.
Constructor & Destructor Documentation
TemplateTextField()
TemplateTextField::TemplateTextField (QGraphicsItem * parent, TechDraw::DrawTemplate * myTmplte, const std::string & myFieldName)
Definition at line 43 of file TemplateTextField.cpp.
References m_line, and m_rect.
~TemplateTextField()
TechDrawGui::TemplateTextField::~TemplateTextField () override default
Member Function Documentation
fieldName()
std::string TechDrawGui::TemplateTextField::fieldName () const inline
Returns the field name that this TemplateTextField represents.
Definition at line 56 of file TemplateTextField.h.
Referenced by mouseReleaseEvent().
mousePressEvent()
void TemplateTextField::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected
Need this to properly handle mouse release.
Definition at line 62 of file TemplateTextField.cpp.
References m_rect, and tmplte.
mouseReleaseEvent()
void TemplateTextField::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override protected
Trigger the dialog for editing template text.
Definition at line 71 of file TemplateTextField.cpp.
References TechDraw::DrawTemplate::EditableTexts, fieldName(), fieldNameStr, TechDrawGui::DlgTemplateField::getAutofillState(), TechDrawGui::DlgTemplateField::getFieldContent(), m_autofillString, m_rect, TechDrawGui::DlgTemplateField::setAutofillContent(), TechDrawGui::DlgTemplateField::setFieldContent(), TechDrawGui::DlgTemplateField::setFieldName(), App::PropertyMap::setValue(), and tmplte.
setAutofill()
void TemplateTextField::setAutofill (QString autofillString)
Definition at line 111 of file TemplateTextField.cpp.
References m_autofillString.
setLine()
void TemplateTextField::setLine (QPointF from, QPointF to)
Definition at line 122 of file TemplateTextField.cpp.
References m_line.
setLineColor()
void TemplateTextField::setLineColor (QColor color)
Definition at line 129 of file TemplateTextField.cpp.
References m_line.
setRectangle()
void TemplateTextField::setRectangle (QRectF rect)
Definition at line 117 of file TemplateTextField.cpp.
References m_rect.
type()
int TechDrawGui::TemplateTextField::type () const inline override
Definition at line 53 of file TemplateTextField.h.
Member Data Documentation
fieldNameStr
std::string TechDrawGui::TemplateTextField::fieldNameStr protected
Definition at line 65 of file TemplateTextField.h.
Referenced by mouseReleaseEvent().
m_autofillString
QString TechDrawGui::TemplateTextField::m_autofillString protected
Definition at line 66 of file TemplateTextField.h.
Referenced by mouseReleaseEvent(), and setAutofill().
m_line
QGraphicsPathItem* TechDrawGui::TemplateTextField::m_line protected
Definition at line 75 of file TemplateTextField.h.
Referenced by setLine(), setLineColor(), and TemplateTextField().
m_rect
QGraphicsRectItem* TechDrawGui::TemplateTextField::m_rect protected
Definition at line 74 of file TemplateTextField.h.
Referenced by mousePressEvent(), mouseReleaseEvent(), setRectangle(), and TemplateTextField().
tmplte
TechDraw::DrawTemplate* TechDrawGui::TemplateTextField::tmplte protected
Definition at line 64 of file TemplateTextField.h.
Referenced by mousePressEvent(), and mouseReleaseEvent().
The documentation for this class was generated from the following files:
TemplateTextField.h
TemplateTextField.cpp