FreeCAD: FemGui::ViewProviderFemHighlighter Class Reference
FemGui::ViewProviderFemHighlighter Class Reference
#include <ViewProviderAnalysis.h>
Public Member Functions
ViewProviderFemHighlighter ()
Constructor.
~ViewProviderFemHighlighter ()
void attach (ViewProviderFemAnalysis *)
void highlightView (Gui::ViewProviderDocumentObject *)
void removeView (Gui::ViewProviderDocumentObject *)
Detailed Description
Definition at line 55 of file ViewProviderAnalysis.h.
Constructor & Destructor Documentation
ViewProviderFemHighlighter()
ViewProviderFemHighlighter::ViewProviderFemHighlighter ()
Constructor.
Definition at line 62 of file ViewProviderAnalysis.cpp.
~ViewProviderFemHighlighter()
ViewProviderFemHighlighter::~ViewProviderFemHighlighter ()
Definition at line 68 of file ViewProviderAnalysis.cpp.
Member Function Documentation
attach()
void ViewProviderFemHighlighter::attach (ViewProviderFemAnalysis * view)
Definition at line 73 of file ViewProviderAnalysis.cpp.
References Gui::ViewProvider::getRoot().
Referenced by FemGui::ViewProviderFemAnalysis::attach().
highlightView()
void ViewProviderFemHighlighter::highlightView (Gui::ViewProviderDocumentObject * view)
Definition at line 79 of file ViewProviderAnalysis.cpp.
References Gui::ViewProvider::getRoot().
Referenced by FemGui::ViewProviderFemAnalysis::highlightView().
removeView()
void ViewProviderFemHighlighter::removeView (Gui::ViewProviderDocumentObject * view)
Definition at line 88 of file ViewProviderAnalysis.cpp.
References Gui::ViewProvider::getRoot().
Referenced by FemGui::ViewProviderFemAnalysis::removeView().
The documentation for this class was generated from the following files:
ViewProviderAnalysis.h
ViewProviderAnalysis.cpp