FreeCAD: FemGui::ActiveAnalysisObserver Class Reference
FemGui::ActiveAnalysisObserver Class Reference
#include <ActiveAnalysisObserver.h>
Public Member Functions
void setActiveObject (Fem::FemAnalysis *)
Fem::FemAnalysis * getActiveObject () const
bool hasActiveObject () const
void highlightActiveObject (const Gui::HighlightMode &, bool)
Public Member Functions inherited from App::DocumentObserver
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
void attachDocument (Document *)
void detachDocument ()
Static Public Member Functions
static ActiveAnalysisObserver * instance ()
Additional Inherited Members
Protected Member Functions inherited from App::DocumentObserver
Document * getDocument () const
Detailed Description
Definition at line 44 of file ActiveAnalysisObserver.h.
Member Function Documentation
getActiveObject()
Fem::FemAnalysis * ActiveAnalysisObserver::getActiveObject () const
Definition at line 65 of file ActiveAnalysisObserver.cpp.
Referenced by getConstraintPrerequisits(), and FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary().
hasActiveObject()
bool ActiveAnalysisObserver::hasActiveObject () const
Definition at line 70 of file ActiveAnalysisObserver.cpp.
Referenced by FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary().
highlightActiveObject()
void ActiveAnalysisObserver::highlightActiveObject (const Gui::HighlightMode & mode, bool on)
Definition at line 75 of file ActiveAnalysisObserver.cpp.
References Gui::Document::signalHighlightObject.
Referenced by FemGui::Module::Module().
instance()
ActiveAnalysisObserver * ActiveAnalysisObserver::instance () static
Definition at line 37 of file ActiveAnalysisObserver.cpp.
Referenced by getConstraintPrerequisits(), FemGui::Module::Module(), and FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary().
setActiveObject()
void ActiveAnalysisObserver::setActiveObject (Fem::FemAnalysis * fem)
Definition at line 49 of file ActiveAnalysisObserver.cpp.
References App::DocumentObserver::attachDocument(), toolbit-attributes::doc, App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::Document::getViewProvider(), and Gui::Application::Instance.
Referenced by FemGui::Module::Module().
The documentation for this class was generated from the following files:
ActiveAnalysisObserver.h
ActiveAnalysisObserver.cpp