FreeCAD: TechDrawGui::QGICMark Class Reference
TechDrawGui::QGICMark Class Reference
#include <QGICMark.h>
Public Types
enum { Type = QGraphicsItem::UserType + 171 }
Public Types inherited from TechDrawGui::QGIVertex
enum { Type = QGraphicsItem::UserType + 105 }
Public Types inherited from TechDrawGui::QGIPrimPath
enum { Type = QGraphicsItem::UserType + 170 }
Public Member Functions
QGICMark (int index)
~QGICMark () override
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QRectF boundingRect () const override
QPainterPath shape () const override
void draw (void)
float getSize ()
void setSize (float s)
float getThick ()
void setThick (float t)
void setPrettyNormal () override
double getMarkFuzz (void) const
Public Member Functions inherited from TechDrawGui::QGIVertex
QGIVertex (int index)
~QGIVertex () override=default
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
int getProjIndex () const
float getRadius ()
virtual void setRadius (float r)
Public Member Functions inherited from TechDrawGui::QGIPrimPath
QGIPrimPath ()
~QGIPrimPath () override=default
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QPainterPath shape () const override
virtual void setPrettyPre ()
virtual void setPrettySel ()
virtual void setWidth (double w)
virtual double getWidth ()
Qt::PenStyle getStyle ()
void setStyle (Qt::PenStyle s)
void setStyle (int s)
virtual void setNormalColor (QColor c)
virtual void setCapStyle (Qt::PenCapStyle c)
void setFillStyle (Qt::BrushStyle f)
Qt::BrushStyle getFillStyle ()
void setFill (QColor c, Qt::BrushStyle s)
void setFill (QBrush b)
void resetFill ()
void setFillColor (QColor c)
QColor getFillColor ()
void setFillOverride (bool b)
virtual void setCurrentPen ()
Protected Member Functions
QColor getCMarkColor ()
Protected Member Functions inherited from TechDrawGui::QGIVertex
bool multiselectEligible () override
Protected Member Functions inherited from TechDrawGui::QGIPrimPath
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual QColor getNormalColor ()
virtual QColor getPreColor ()
virtual QColor getSelectColor ()
Base::Reference< ParameterGrp > getParmGroup ()
virtual Qt::PenCapStyle prefCapStyle ()
Additional Inherited Members
Protected Attributes inherited from TechDrawGui::QGIVertex
int projIndex
float m_radius
Protected Attributes inherited from TechDrawGui::QGIPrimPath
bool isHighlighted
bool multiselectActivated
QPen m_pen
QColor m_colCurrent
QColor m_colNormal
bool m_colOverride
Qt::PenStyle m_styleCurrent
Qt::PenStyle m_styleNormal
double m_width
Qt::PenCapStyle m_capStyle
QBrush m_brush
Qt::BrushStyle m_fillStyleCurrent
QColor m_fillColorCurrent
QColor m_colDefFill
QColor m_colNormalFill
Qt::BrushStyle m_fillDef
Qt::BrushStyle m_fillNormal
Qt::BrushStyle m_fillSelect
bool m_fillOverride
Detailed Description
Definition at line 53 of file QGICMark.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 79 of file QGICMark.h.
Constructor & Destructor Documentation
QGICMark()
QGICMark::QGICMark (int index) explicit
Definition at line 42 of file QGICMark.cpp.
References draw(), and TechDrawGui::QGIPrimPath::m_width.
~QGICMark()
TechDrawGui::QGICMark::~QGICMark () inline override
Definition at line 77 of file QGICMark.h.
Member Function Documentation
boundingRect()
QRectF QGICMark::boundingRect () const override
Definition at line 88 of file QGICMark.cpp.
References shape().
draw()
void QGICMark::draw (void)
Definition at line 48 of file QGICMark.cpp.
Referenced by QGICMark(), setSize(), and setThick().
getCMarkColor()
QColor QGICMark::getCMarkColor () protected
Definition at line 70 of file QGICMark.cpp.
References TechDrawGui::PreferencesGui::centerQColor().
Referenced by setPrettyNormal().
getMarkFuzz()
double QGICMark::getMarkFuzz (void) const
Definition at line 102 of file QGICMark.cpp.
Referenced by shape().
getSize()
float TechDrawGui::QGICMark::getSize () inline
Definition at line 87 of file QGICMark.h.
getThick()
float TechDrawGui::QGICMark::getThick () inline
Definition at line 89 of file QGICMark.h.
paint()
void QGICMark::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 80 of file QGICMark.cpp.
References TechDrawGui::QGIVertex::paint().
setPrettyNormal()
void QGICMark::setPrettyNormal () override virtual
Reimplemented from TechDrawGui::QGIPrimPath.
Definition at line 75 of file QGICMark.cpp.
References getCMarkColor(), and TechDrawGui::QGIPrimPath::m_colCurrent.
Referenced by TechDrawGui::QGIViewPart::drawAllVertexes().
setSize()
void QGICMark::setSize (float s)
Definition at line 58 of file QGICMark.cpp.
References draw(), and toolbit-attributes::s.
Referenced by TechDrawGui::QGIViewPart::drawAllVertexes(), TechDrawGui::QGCustomClip::makeMark(), TechDrawGui::QGIDecoration::makeMark(), TechDrawGui::QGCustomText::makeMark(), and TechDrawGui::QGIFace::makeMark().
setThick()
void QGICMark::setThick (float t)
Definition at line 64 of file QGICMark.cpp.
References draw(), TechDrawGui::QGIPrimPath::m_width, and InitGui::t.
Referenced by TechDrawGui::QGIViewPart::drawAllVertexes(), TechDrawGui::QGCustomClip::makeMark(), TechDrawGui::QGIDecoration::makeMark(), TechDrawGui::QGCustomText::makeMark(), and TechDrawGui::QGIFace::makeMark().
shape()
QPainterPath QGICMark::shape () const override
Definition at line 93 of file QGICMark.cpp.
References getMarkFuzz().
Referenced by boundingRect().
type()
int TechDrawGui::QGICMark::type () const inline override
Definition at line 80 of file QGICMark.h.
The documentation for this class was generated from the following files:
QGICMark.h
QGICMark.cpp