FreeCAD: SurfaceGui::SectionsPanel Class Reference
SurfaceGui::SectionsPanel Class Reference
#include <TaskSections.h>
Classes
class ShapeSelection
Public Member Functions
SectionsPanel (ViewProviderSections *vp, Surface::Sections *obj)
~SectionsPanel () override
void open ()
void checkOpenCommand ()
bool accept ()
bool reject ()
void setEditedObject (Surface::Sections *obj)
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Public Member Functions inherited from Gui::DocumentObserver
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
void attachDocument (Document *)
void detachDocument ()
Protected Types
enum SelectionMode { None, AppendEdge, RemoveEdge }
Protected Member Functions
void changeEvent (QEvent *e) override
void onSelectionChanged (const Gui::SelectionChanges &msg) override
void slotUndoDocument (const Gui::Document &Doc) override
void slotRedoDocument (const Gui::Document &Doc) override
void slotDeletedObject (const Gui::ViewProviderDocumentObject &Obj) override
Protected Attributes
SelectionMode selectionMode
Surface::Sections * editedObject
bool checkCommand
Detailed Description
Definition at line 66 of file TaskSections.h.
Member Enumeration Documentation
SelectionMode
enum SurfaceGui::SectionsPanel::SelectionMode protected
Enumerator
None
AppendEdge
RemoveEdge
Definition at line 72 of file TaskSections.h.
Constructor & Destructor Documentation
SectionsPanel()
SurfaceGui::SectionsPanel::SectionsPanel (ViewProviderSections * vp, Surface::Sections * obj)
Definition at line 262 of file TaskSections.cpp.
References Path.Post.scripts.dynapath_4060_post::action, SurfaceGui::AppendEdge, checkCommand, Gui::Application::commandManager(), draftgeoutils.intersections::connect(), Gui::CommandManager::getCommandByName(), Gui::Command::getShortcut(), Gui::Application::Instance, None, SurfaceGui::RemoveEdge, selectionMode, setEditedObject(), and Gui::ButtonGroup::setExclusive().
~SectionsPanel()
SurfaceGui::SectionsPanel::~SectionsPanel () override default
Member Function Documentation
accept()
bool SurfaceGui::SectionsPanel::accept ()
Definition at line 407 of file TaskSections.cpp.
References SurfaceGui::ViewProviderSections::Edge, editedObject, App::DocumentObject::getStatusString(), App::PropertyLinkSubList::getSubListValues(), SurfaceGui::ViewProviderSections::highlightReferences(), App::DocumentObject::isValid(), Part::Feature::mustExecute(), None, Surface::Sections::NSections, App::DocumentObject::recomputeFeature(), Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), selectionMode, and Path.Log::warning().
Referenced by SurfaceGui::TaskSections::accept().
changeEvent()
void SurfaceGui::SectionsPanel::changeEvent (QEvent * e) override protected
Definition at line 349 of file TaskSections.cpp.
References SCL.SimpleDataTypes::e.
checkOpenCommand()
void SurfaceGui::SectionsPanel::checkOpenCommand ()
Definition at line 376 of file TaskSections.cpp.
References checkCommand, editedObject, App::PropertyString::getValue(), Gui::Command::hasPendingCommand(), App::DocumentObject::Label, FreeCADInit::Msg, and Gui::Command::openCommand().
Referenced by onSelectionChanged(), and open().
onSelectionChanged()
void SurfaceGui::SectionsPanel::onSelectionChanged (const Gui::SelectionChanges & msg) override protected virtual
Implements Gui::SelectionObserver.
Definition at line 465 of file TaskSections.cpp.
References Gui::SelectionChanges::AddSelection, AppendEdge, checkOpenCommand(), editedObject, Gui::SelectionObject::getObject(), App::PropertyString::getValue(), SplineSurface::i, App::DocumentObject::Label, Path.Op.Surface::msg, None, App::DocumentObject::recomputeFeature(), RemoveEdge, and selectionMode.
open()
void SurfaceGui::SectionsPanel::open ()
Definition at line 359 of file TaskSections.cpp.
References checkOpenCommand(), Gui::SelectionSingleton::clearSelection(), SurfaceGui::ViewProviderSections::Edge, editedObject, App::PropertyLinkSubList::getSubListValues(), SurfaceGui::ViewProviderSections::highlightReferences(), Surface::Sections::NSections, and Gui::Selection().
Referenced by SurfaceGui::TaskSections::open().
reject()
bool SurfaceGui::SectionsPanel::reject ()
Definition at line 429 of file TaskSections.cpp.
References SurfaceGui::ViewProviderSections::Edge, editedObject, App::PropertyLinkSubList::getSubListValues(), SurfaceGui::ViewProviderSections::highlightReferences(), None, Surface::Sections::NSections, Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), and selectionMode.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and SurfaceGui::TaskSections::reject().
setEditedObject()
void SurfaceGui::SectionsPanel::setEditedObject (Surface::Sections * obj)
Definition at line 312 of file TaskSections.cpp.
References Gui::DocumentObserver::attachDocument(), src.Mod.AddonManager.NetworkManager::count, toolbit-attributes::doc, editedObject, App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::PropertyLinkSubList::getSubValues(), App::PropertyString::getValue(), App::PropertyLinkSubList::getValues(), SplineSurface::i, Gui::Application::Instance, App::DocumentObject::Label, Surface::Sections::NSections, and importers.importIFCmulticore::objects.
Referenced by SectionsPanel(), and SurfaceGui::TaskSections::setEditedObject().
slotDeletedObject()
void SurfaceGui::SectionsPanel::slotDeletedObject (const Gui::ViewProviderDocumentObject & Obj) override protected virtual
Notifies when the object is about to be removed.
Reimplemented from Gui::DocumentObserver.
Definition at line 396 of file TaskSections.cpp.
References SurfaceGui::ViewProviderSections::Edge, editedObject, App::PropertyLinkSubList::getSubListValues(), SurfaceGui::ViewProviderSections::highlightReferences(), and Surface::Sections::NSections.
slotRedoDocument()
void SurfaceGui::SectionsPanel::slotRedoDocument (const Gui::Document & Doc) override protected virtual
Notifies on redo
Reimplemented from Gui::DocumentObserver.
Definition at line 391 of file TaskSections.cpp.
References checkCommand.
slotUndoDocument()
void SurfaceGui::SectionsPanel::slotUndoDocument (const Gui::Document & Doc) override protected virtual
Notifies on undo
Reimplemented from Gui::DocumentObserver.
Definition at line 386 of file TaskSections.cpp.
References checkCommand.
Member Data Documentation
checkCommand
bool SurfaceGui::SectionsPanel::checkCommand protected
Definition at line 80 of file TaskSections.h.
Referenced by checkOpenCommand(), SectionsPanel(), slotRedoDocument(), and slotUndoDocument().
editedObject
Surface::Sections* SurfaceGui::SectionsPanel::editedObject protected
Definition at line 79 of file TaskSections.h.
Referenced by accept(), checkOpenCommand(), onSelectionChanged(), open(), reject(), setEditedObject(), and slotDeletedObject().
selectionMode
SelectionMode SurfaceGui::SectionsPanel::selectionMode protected
Definition at line 78 of file TaskSections.h.
Referenced by accept(), onSelectionChanged(), reject(), and SectionsPanel().
The documentation for this class was generated from the following files:
TaskSections.h
TaskSections.cpp