FreeCAD: SpreadsheetGui::SheetTableView Class Reference
SpreadsheetGui::SheetTableView Class Reference
#include <SheetTableView.h>
Public Slots
void mergeCells ()
void splitCell ()
void deleteSelection ()
void copySelection ()
void cutSelection ()
void pasteClipboard ()
void finishEditWithMove (int keyPressed, Qt::KeyboardModifiers modifiers, bool handleTabMotion=false)
void ModifyBlockSelection (int targetRow, int targetColumn)
Public Member Functions
SheetTableView (QWidget *parent=nullptr)
~SheetTableView () override
void edit (const QModelIndex &index)
void setSheet (Spreadsheet::Sheet *_sheet)
std::vector< App::Range > selectedRanges () const
QModelIndexList selectedIndexesRaw () const
QString toHtml () const
Protected Slots
void commitData (QWidget *editor) override
void updateCellSpan ()
void insertRows ()
void insertRowsAfter ()
void removeRows ()
void insertColumns ()
void insertColumnsAfter ()
void removeColumns ()
void cellProperties ()
void onRecompute ()
void onBind ()
void onConfSetup ()
Protected Member Functions
bool edit (const QModelIndex &index, EditTrigger trigger, QEvent *event) override
bool event (QEvent *event) override
void closeEditor (QWidget *editor, QAbstractItemDelegate::EndEditHint hint) override
void mousePressEvent (QMouseEvent *event) override
void selectionChanged (const QItemSelection &selected, const QItemSelection &deselected) override
void contextMenuEvent (QContextMenuEvent *e) override
void _copySelection (const std::vector< App::Range > &ranges, bool copy)
Protected Attributes
QModelIndex currentEditIndex
Spreadsheet::Sheet * sheet
int tabCounter
QMenu contextMenu
QAction * actionProperties
QAction * actionRecompute
QAction * actionConf
QAction * actionMerge
QAction * actionSplit
QAction * actionCopy
QAction * actionPaste
QAction * actionCut
QAction * actionDel
QAction * actionBind
QTimer timer
boost::signals2::scoped_connection cellSpanChangedConnection
std::set< App::CellAddress > spanChanges
Detailed Description
Definition at line 77 of file SheetTableView.h.
Constructor & Destructor Documentation
SheetTableView()
SheetTableView::SheetTableView (QWidget * parent = nullptr) explicit
Definition at line 111 of file SheetTableView.cpp.
References actionBind, actionConf, actionCopy, actionCut, actionDel, actionMerge, actionPaste, actionProperties, actionRecompute, actionSplit, cellProperties(), draftgeoutils.intersections::connect(), contextMenu, copySelection(), cutSelection(), deleteSelection(), Sketcher::Horizontal, AssemblyImport::insert(), insertColumns(), insertColumnsAfter(), insertRows(), insertRowsAfter(), KDL::max(), NavigationIndicatorGui::menu, mergeCells(), KDL::min(), onBind(), onConfSetup(), onRecompute(), pasteClipboard(), RobotExample::pos, removeColumns(), removeRows(), selectedMinMaxColumns(), selectedMinMaxRows(), Path.Dressup.Utils::selection(), splitCell(), timer, updateCellSpan(), and Sketcher::Vertical.
~SheetTableView()
SheetTableView::~SheetTableView () override default
Member Function Documentation
_copySelection()
void SheetTableView::_copySelection (const std::vector< App::Range > & ranges, bool copy) protected
Definition at line 699 of file SheetTableView.cpp.
References _SheetMime(), Drawing::copy(), Spreadsheet::PropertySheet::copyCells(), Spreadsheet::Sheet::getCells(), Base::StringWriter::getString(), SplineSurface::i, KDL::max(), KDL::min(), Path.Post.scripts.opensbp_post::move(), Spreadsheet::Sheet::setCopyOrCutRanges(), and sheet.
Referenced by copySelection(), cutSelection(), and pasteClipboard().
cellProperties
void SheetTableView::cellProperties () protected slot
Definition at line 261 of file SheetTableView.cpp.
References src.Mod.PartDesign.Scripts.Gear::dialog, selectedRanges(), and sheet.
Referenced by SheetTableView().
closeEditor()
void SheetTableView::closeEditor (QWidget * editor, QAbstractItemDelegate::EndEditHint hint) override protected
Definition at line 1081 of file SheetTableView.cpp.
References Path.Post.Utils::editor().
commitData
void SheetTableView::commitData (QWidget * editor) override protected slot
Definition at line 544 of file SheetTableView.cpp.
References Path.Post.Utils::editor().
contextMenuEvent()
void SheetTableView::contextMenuEvent (QContextMenuEvent * e) override protected
Definition at line 1105 of file SheetTableView.cpp.
References actionBind, actionCopy, actionCut, actionDel, actionMerge, actionPaste, actionSplit, App::ExpressionParser::column, contextMenu, Spreadsheet::Sheet::isMergedCell(), RobotExample::pos, selectedIndexesRaw(), selectedRanges(), and sheet.
copySelection
void SheetTableView::copySelection () slot
Definition at line 694 of file SheetTableView.cpp.
References _copySelection(), and selectedRanges().
Referenced by event(), and SheetTableView().
cutSelection
void SheetTableView::cutSelection () slot
Definition at line 737 of file SheetTableView.cpp.
References _copySelection(), and selectedRanges().
Referenced by event(), and SheetTableView().
deleteSelection
void SheetTableView::deleteSelection () slot
Definition at line 672 of file SheetTableView.cpp.
References Gui::Command::commitCommand(), Gui::Command::Doc, doCommand, App::DocumentObject::getNameInDocument(), SplineSurface::i, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, selectedRanges(), Path.Dressup.Utils::selection(), and sheet.
Referenced by event(), and SheetTableView().
edit() [1/2]
void SheetTableView::edit (const QModelIndex & index)
Definition at line 1099 of file SheetTableView.cpp.
References currentEditIndex.
edit() [2/2]
bool SheetTableView::edit (const QModelIndex & index, EditTrigger trigger, QEvent * event) override protected
Definition at line 549 of file SheetTableView.cpp.
References currentEditIndex, and event().
event()
bool SheetTableView::event (QEvent * event) override protected
Definition at line 559 of file SheetTableView.cpp.
References actionBind, actionConf, actionCopy, actionCut, actionDel, actionMerge, actionPaste, actionProperties, actionRecompute, actionSplit, copySelection(), cutSelection(), deleteSelection(), finishEditWithMove(), pasteClipboard(), Spreadsheet::Sheet::setCopyOrCutRanges(), and sheet.
Referenced by edit(), and mousePressEvent().
finishEditWithMove
void SheetTableView::finishEditWithMove (int keyPressed, Qt::KeyboardModifiers modifiers, bool handleTabMotion = false) slot
Definition at line 813 of file SheetTableView.cpp.
References SCL.SimpleDataTypes::c, Spreadsheet::Sheet::getAnchor(), Spreadsheet::Sheet::getCell(), Spreadsheet::Sheet::getCells(), Spreadsheet::PropertySheet::getNonEmptyCells(), Spreadsheet::Sheet::getSpans(), Spreadsheet::Sheet::isMergedCell(), Spreadsheet::Cell::isUsed(), KDL::max(), KDL::min(), ModifyBlockSelection(), App::CellAddress::row(), sheet, and tabCounter.
Referenced by event().
insertColumns
void SheetTableView::insertColumns () protected slot
Definition at line 403 of file SheetTableView.cpp.
References Gui::cmdAppObjectArgs(), Spreadsheet::columnName(), Gui::Command::commitCommand(), src.Mod.AddonManager.NetworkManager::count, Gui::Command::Doc, doCommand, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, and sheet.
Referenced by SheetTableView().
insertColumnsAfter
void SheetTableView::insertColumnsAfter () protected slot
Definition at line 442 of file SheetTableView.cpp.
References Gui::cmdAppObjectArgs(), Spreadsheet::columnName(), Gui::Command::commitCommand(), Gui::Command::Doc, doCommand, KDL::max(), KDL::min(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, selectedMinMaxColumns(), and sheet.
Referenced by SheetTableView().
insertRows
void SheetTableView::insertRows () protected slot
Definition at line 328 of file SheetTableView.cpp.
References Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), src.Mod.AddonManager.NetworkManager::count, Gui::Command::Doc, doCommand, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, Spreadsheet::rowName(), and sheet.
Referenced by SheetTableView().
insertRowsAfter
void SheetTableView::insertRowsAfter () protected slot
Definition at line 367 of file SheetTableView.cpp.
References Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Gui::Command::Doc, doCommand, KDL::max(), KDL::min(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, Spreadsheet::rowName(), selectedMinMaxRows(), and sheet.
Referenced by SheetTableView().
mergeCells
void SheetTableView::mergeCells () slot
Definition at line 1071 of file SheetTableView.cpp.
References Gui::Application::commandManager(), Gui::Application::Instance, and Gui::CommandManager::runCommandByName().
Referenced by SheetTableView().
ModifyBlockSelection
void SheetTableView::ModifyBlockSelection (int targetRow, int targetColumn) slot
Definition at line 1017 of file SheetTableView.cpp.
References KDL::max(), KDL::min(), and Path.Dressup.Utils::selection().
Referenced by finishEditWithMove().
mousePressEvent()
void SheetTableView::mousePressEvent (QMouseEvent * event) override protected
Definition at line 1086 of file SheetTableView.cpp.
References event(), and tabCounter.
onBind
void SheetTableView::onBind () protected slot
Definition at line 242 of file SheetTableView.cpp.
References selectedRanges(), and sheet.
Referenced by SheetTableView().
onConfSetup
void SheetTableView::onConfSetup () protected slot
Definition at line 251 of file SheetTableView.cpp.
References selectedRanges(), and sheet.
Referenced by SheetTableView().
onRecompute
void SheetTableView::onRecompute () protected slot
Definition at line 230 of file SheetTableView.cpp.
References Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Gui::Command::openCommand(), selectedRanges(), and sheet.
Referenced by SheetTableView().
pasteClipboard
void SheetTableView::pasteClipboard () slot
Definition at line 742 of file SheetTableView.cpp.
References _copySelection(), _SheetMime(), Spreadsheet::Sheet::clear(), App::CellAddress::col(), Drawing::copy(), SCL.SimpleDataTypes::e, App::Range::from(), App::Application::getActiveDocument(), App::GetApplication(), Spreadsheet::Sheet::getCells(), Spreadsheet::Sheet::getCopyOrCutRange(), Gui::getMainWindow(), SplineSurface::i, Spreadsheet::PropertySheet::pasteCells(), TechDrawTools.TaskFillTemplateFields::reader, App::Document::recompute(), App::CellAddress::row(), selectedRanges(), and sheet.
Referenced by event(), and SheetTableView().
removeColumns
void SheetTableView::removeColumns () protected slot
Definition at line 459 of file SheetTableView.cpp.
References Gui::cmdAppObjectArgs(), Spreadsheet::columnName(), Gui::Command::commitCommand(), Gui::Command::Doc, doCommand, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, and sheet.
Referenced by SheetTableView().
removeRows
void SheetTableView::removeRows () protected slot
Definition at line 381 of file SheetTableView.cpp.
References Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Gui::Command::Doc, doCommand, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, Spreadsheet::rowName(), and sheet.
Referenced by SheetTableView().
selectedIndexesRaw()
QModelIndexList SheetTableView::selectedIndexesRaw () const
Definition at line 323 of file SheetTableView.cpp.
Referenced by contextMenuEvent().
selectedRanges()
std::vector< Range > SheetTableView::selectedRanges () const
Definition at line 270 of file SheetTableView.cpp.
References Spreadsheet::Sheet::getCells(), Spreadsheet::PropertySheet::hasSpan(), result, Path.Dressup.Utils::selection(), and sheet.
Referenced by cellProperties(), contextMenuEvent(), copySelection(), cutSelection(), deleteSelection(), onBind(), onConfSetup(), onRecompute(), and pasteClipboard().
selectionChanged()
void SheetTableView::selectionChanged (const QItemSelection & selected, const QItemSelection & deselected) override protected
Definition at line 1092 of file SheetTableView.cpp.
References Gui::getMainWindow(), and Gui::MainWindow::updateActions().
setSheet()
void SheetTableView::setSheet (Spreadsheet::Sheet * _sheet)
Definition at line 503 of file SheetTableView.cpp.
References Spreadsheet::Sheet::cellSpanChanged, cellSpanChangedConnection, App::CellAddress::col(), Spreadsheet::Sheet::getColumnWidths(), Spreadsheet::Sheet::getRowHeights(), Spreadsheet::Sheet::getSpans(), Spreadsheet::Sheet::getUsedCells(), SplineSurface::i, Spreadsheet::Sheet::isMergedCell(), App::CellAddress::row(), sheet, spanChanges, and timer.
splitCell
void SheetTableView::splitCell () slot
Definition at line 1076 of file SheetTableView.cpp.
References Gui::Application::commandManager(), Gui::Application::Instance, and Gui::CommandManager::runCommandByName().
Referenced by SheetTableView().
toHtml()
QString SheetTableView::toHtml () const
Definition at line 1133 of file SheetTableView.cpp.
References toolbit-attributes::doc, Spreadsheet::Sheet::getCells(), Spreadsheet::Sheet::getColumnWidth(), Spreadsheet::PropertySheet::getNonEmptyCells(), Spreadsheet::Sheet::getSpans(), Sketcher::Horizontal, Spreadsheet::Sheet::isMergedCell(), KDL::max(), sheet, RobotExample::Start, and Sketcher::Vertical.
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_readme_browser.WidgetReadmeBrowser::loadResource().
updateCellSpan
void SheetTableView::updateCellSpan () protected slot
Definition at line 483 of file SheetTableView.cpp.
References Spreadsheet::Sheet::getSpans(), sheet, and spanChanges.
Referenced by SheetTableView().
Member Data Documentation
actionBind
QAction* SpreadsheetGui::SheetTableView::actionBind protected
Definition at line 143 of file SheetTableView.h.
Referenced by contextMenuEvent(), event(), and SheetTableView().
actionConf
QAction* SpreadsheetGui::SheetTableView::actionConf protected
Definition at line 136 of file SheetTableView.h.
Referenced by event(), and SheetTableView().
actionCopy
QAction* SpreadsheetGui::SheetTableView::actionCopy protected
Definition at line 139 of file SheetTableView.h.
Referenced by contextMenuEvent(), event(), and SheetTableView().
actionCut
QAction* SpreadsheetGui::SheetTableView::actionCut protected
Definition at line 141 of file SheetTableView.h.
Referenced by contextMenuEvent(), event(), and SheetTableView().
actionDel
QAction* SpreadsheetGui::SheetTableView::actionDel protected
Definition at line 142 of file SheetTableView.h.
Referenced by contextMenuEvent(), event(), and SheetTableView().
actionMerge
QAction* SpreadsheetGui::SheetTableView::actionMerge protected
Definition at line 137 of file SheetTableView.h.
Referenced by contextMenuEvent(), event(), and SheetTableView().
actionPaste
QAction* SpreadsheetGui::SheetTableView::actionPaste protected
Definition at line 140 of file SheetTableView.h.
Referenced by contextMenuEvent(), event(), and SheetTableView().
actionProperties
QAction* SpreadsheetGui::SheetTableView::actionProperties protected
Definition at line 134 of file SheetTableView.h.
Referenced by event(), and SheetTableView().
actionRecompute
QAction* SpreadsheetGui::SheetTableView::actionRecompute protected
Definition at line 135 of file SheetTableView.h.
Referenced by event(), and SheetTableView().
actionSplit
QAction* SpreadsheetGui::SheetTableView::actionSplit protected
Definition at line 138 of file SheetTableView.h.
Referenced by contextMenuEvent(), event(), and SheetTableView().
cellSpanChangedConnection
boost::signals2::scoped_connection SpreadsheetGui::SheetTableView::cellSpanChangedConnection protected
Definition at line 147 of file SheetTableView.h.
Referenced by setSheet().
contextMenu
QMenu SpreadsheetGui::SheetTableView::contextMenu protected
Definition at line 132 of file SheetTableView.h.
Referenced by contextMenuEvent(), and SheetTableView().
currentEditIndex
QModelIndex SpreadsheetGui::SheetTableView::currentEditIndex protected
Definition at line 128 of file SheetTableView.h.
Referenced by edit().
sheet
Spreadsheet::Sheet* SpreadsheetGui::SheetTableView::sheet protected
Definition at line 129 of file SheetTableView.h.
Referenced by _copySelection(), cellProperties(), contextMenuEvent(), deleteSelection(), event(), finishEditWithMove(), insertColumns(), insertColumnsAfter(), insertRows(), insertRowsAfter(), onBind(), onConfSetup(), onRecompute(), pasteClipboard(), removeColumns(), removeRows(), selectedRanges(), setSheet(), TestSpreadsheetGui.SpreadsheetGuiCases::testCopySingleCell(), toHtml(), and updateCellSpan().
spanChanges
std::set<App::CellAddress> SpreadsheetGui::SheetTableView::spanChanges protected
Definition at line 148 of file SheetTableView.h.
Referenced by setSheet(), and updateCellSpan().
tabCounter
int SpreadsheetGui::SheetTableView::tabCounter protected
Definition at line 130 of file SheetTableView.h.
Referenced by finishEditWithMove(), and mousePressEvent().
timer
QTimer SpreadsheetGui::SheetTableView::timer protected
Definition at line 145 of file SheetTableView.h.
Referenced by setSheet(), and SheetTableView().
The documentation for this class was generated from the following files:
SheetTableView.h
SheetTableView.cpp