FreeCAD: App::PropertyLinkT Class Reference
App::PropertyLinkT Class Reference
#include <DocumentObserver.h>
Public Member Functions
PropertyLinkT ()
PropertyLinkT (DocumentObject *obj)
PropertyLinkT (DocumentObject *obj, const std::vector< std::string > &subNames)
PropertyLinkT (const std::vector< DocumentObject * > &objs)
PropertyLinkT (const std::vector< DocumentObject * > &objs, const std::vector< std::string > &subNames)
std::string getPropertyPython () const
Detailed Description
The PropertyLinkT class is a helper class to create Python statements for property links.
Definition at line 319 of file App/DocumentObserver.h.
Constructor & Destructor Documentation
PropertyLinkT() [1/5]
PropertyLinkT::PropertyLinkT ()
Constructor
Definition at line 589 of file App/DocumentObserver.cpp.
PropertyLinkT() [2/5]
PropertyLinkT::PropertyLinkT (DocumentObject * obj) explicit
Constructor
Definition at line 593 of file App/DocumentObserver.cpp.
References App::DocumentObjectT::getObjectPython(), and Path.Post.scripts.refactored_centroid_post::str.
PropertyLinkT() [3/5]
PropertyLinkT::PropertyLinkT (DocumentObject * obj, const std::vector< std::string > & subNames)
Constructor
Definition at line 605 of file App/DocumentObserver.cpp.
References App::DocumentObjectT::getObjectPython(), and Path.Post.scripts.refactored_centroid_post::str.
PropertyLinkT() [4/5]
PropertyLinkT::PropertyLinkT (const std::vector< DocumentObject * > & objs) explicit
Constructor
Definition at line 621 of file App/DocumentObserver.cpp.
References App::DocumentObjectT::getObjectPython(), SplineSurface::i, replaceobj::objs, and Path.Post.scripts.refactored_centroid_post::str.
PropertyLinkT() [5/5]
PropertyLinkT::PropertyLinkT (const std::vector< DocumentObject * > & objs, const std::vector< std::string > & subNames)
Constructor
Definition at line 646 of file App/DocumentObserver.cpp.
References App::DocumentObjectT::getObjectPython(), SplineSurface::i, replaceobj::objs, and Path.Post.scripts.refactored_centroid_post::str.
Member Function Documentation
getPropertyPython()
std::string PropertyLinkT::getPropertyPython () const
Get the property as Python command.
Definition at line 679 of file App/DocumentObserver.cpp.
Referenced by PartDesignGui::TaskPipeParameters::accept().
The documentation for this class was generated from the following files:
App/DocumentObserver.h
App/DocumentObserver.cpp