FreeCAD: Measure::ResolveResult Class Reference
Measure::ResolveResult Class Reference
#include <ShapeFinder.h>
Public Member Functions
ResolveResult ()
ResolveResult (const App::DocumentObject *realTarget, const std::string &shortSubName, const App::DocumentObject *targetParent)
App::DocumentObject & getTarget () const
std::string getShortSub () const
App::DocumentObject & getTargetParent () const
Detailed Description
a class to hold the result of resolving a selection into the actual target object and traditional subElement name (Vertex1)
Definition at line 66 of file ShapeFinder.h.
Constructor & Destructor Documentation
ResolveResult() [1/2]
Measure::ResolveResult::ResolveResult ()
ResolveResult() [2/2]
ResolveResult::ResolveResult (const App::DocumentObject * realTarget, const std::string & shortSubName, const App::DocumentObject * targetParent)
ResolveResult is a class to hold the result of resolving a selection into the actual target object and traditional subElement name (Vertex1).
Definition at line 62 of file ShapeFinder.cpp.
Member Function Documentation
getShortSub()
std::string ResolveResult::getShortSub () const
Definition at line 74 of file ShapeFinder.cpp.
References App::SubObjectT::getSubName().
getTarget()
App::DocumentObject & ResolveResult::getTarget () const
Definition at line 69 of file ShapeFinder.cpp.
References App::DocumentObjectT::getObject().
getTargetParent()
App::DocumentObject & ResolveResult::getTargetParent () const
Definition at line 79 of file ShapeFinder.cpp.
References App::DocumentObjectT::getObject().
The documentation for this class was generated from the following files:
ShapeFinder.h
ShapeFinder.cpp