FreeCAD: Gui::WorkbenchManipulatorPython Class Reference
Gui::WorkbenchManipulatorPython Class Reference
#include <WorkbenchManipulatorPython.h>
Public Member Functions
WorkbenchManipulatorPython (const Py::Object &obj)
~WorkbenchManipulatorPython () override
WorkbenchManipulatorPython (const WorkbenchManipulatorPython &)=delete
WorkbenchManipulatorPython (WorkbenchManipulatorPython &&)=delete
WorkbenchManipulatorPython & operator= (const WorkbenchManipulatorPython &)=delete
WorkbenchManipulatorPython & operator= (WorkbenchManipulatorPython &&)=delete
Public Member Functions inherited from Gui::WorkbenchManipulator
WorkbenchManipulator ()=default
virtual ~WorkbenchManipulator ()=default
WorkbenchManipulator (const WorkbenchManipulator &)=delete
WorkbenchManipulator (WorkbenchManipulator &&)=delete
WorkbenchManipulator & operator= (const WorkbenchManipulator &)=delete
WorkbenchManipulator & operator= (WorkbenchManipulator &&)=delete
Static Public Member Functions
static void installManipulator (const Py::Object &obj)
static void removeManipulator (const Py::Object &obj)
Static Public Member Functions inherited from Gui::WorkbenchManipulator
static void installManipulator (const WorkbenchManipulator::Ptr &)
installManipulator Installs a new instance of WorkbenchManipulator
static void removeManipulator (const WorkbenchManipulator::Ptr &)
removeManipulator Removes an installed instance of WorkbenchManipulator
static void removeAll ()
clear Removes all instances of WorkbenchManipulator
static void changeMenuBar (MenuItem *menuBar)
changeMenuBar Calls modifyMenuBar for every installed WorkbenchManipulator
static void changeContextMenu (const char *recipient, MenuItem *menuBar)
changeContextMenu Calls modifyContextMenu for every installed WorkbenchManipulator
static void changeToolBars (ToolBarItem *toolBar)
changeToolBars Calls modifyToolBars for every installed WorkbenchManipulator
static void changeDockWindows (DockWindowItems *dockWindow)
changeDockWindows Calls modifyDockWindows for every installed WorkbenchManipulator
Protected Member Functions
void modifyMenuBar (MenuItem *menuBar) override
modifyMenuBar Method to manipulate the menu structure of a workbench.
void modifyContextMenu (const char *recipient, MenuItem *menuBar) override
modifyContextMenu Method to manipulate the contextmenu structure of a workbench.
void modifyToolBars (ToolBarItem *toolBar) override
modifyToolBars Method to manipulate the toolbar structure of a workbench
void modifyDockWindows (DockWindowItems *dockWindow) override
modifyDockWindows Method to manipulate the dock window structure of a workbench
Protected Member Functions inherited from Gui::WorkbenchManipulator
virtual void modifyMenuBar ([[maybe_unused]] MenuItem *menuBar)
modifyMenuBar Method to manipulate the menu structure of a workbench. The default implementation doesn't change anything.
virtual void modifyContextMenu ([[maybe_unused]] const char *recipient, [[maybe_unused]] MenuItem *menuBar)
modifyContextMenu Method to manipulate the contextmenu structure of a workbench. The default implementation doesn't change anything.
virtual void modifyToolBars ([[maybe_unused]] ToolBarItem *toolBar)
modifyToolBars Method to manipulate the toolbar structure of a workbench The default implementation doesn't change anything.
virtual void modifyDockWindows ([[maybe_unused]] DockWindowItems *dockWindow)
modifyDockWindows Method to manipulate the dock window structure of a workbench The default implementation doesn't change anything.
Additional Inherited Members
Public Types inherited from Gui::WorkbenchManipulator
using Ptr = std::shared_ptr< WorkbenchManipulator >
Static Protected Member Functions inherited from Gui::WorkbenchManipulator
static std::set< WorkbenchManipulator::Ptr > getManipulators ()
Detailed Description
The WorkbenchManipulatorPython class accepts an instance of a Python class that is supposed to implement any of the virtual functions.
Author
Werner Mayer
Definition at line 57 of file WorkbenchManipulatorPython.h.
Constructor & Destructor Documentation
WorkbenchManipulatorPython() [1/3]
WorkbenchManipulatorPython::WorkbenchManipulatorPython (const Py::Object & obj) explicit
Definition at line 51 of file WorkbenchManipulatorPython.cpp.
~WorkbenchManipulatorPython()
WorkbenchManipulatorPython::~WorkbenchManipulatorPython () override
Definition at line 56 of file WorkbenchManipulatorPython.cpp.
WorkbenchManipulatorPython() [2/3]
Gui::WorkbenchManipulatorPython::WorkbenchManipulatorPython (const WorkbenchManipulatorPython &) delete
WorkbenchManipulatorPython() [3/3]
Gui::WorkbenchManipulatorPython::WorkbenchManipulatorPython (WorkbenchManipulatorPython &&) delete
Member Function Documentation
installManipulator()
void WorkbenchManipulatorPython::installManipulator (const Py::Object & obj) static
Definition at line 33 of file WorkbenchManipulatorPython.cpp.
References Gui::WorkbenchManipulator::installManipulator().
Referenced by Gui::ApplicationPy::sAddWbManipulator().
modifyContextMenu()
void WorkbenchManipulatorPython::modifyContextMenu (const char * recipient, MenuItem * menuBar) override protected
modifyContextMenu Method to manipulate the contextmenu structure of a workbench.
WorkbenchManipulatorPython::modifyContextMenu.
Parameters
menuBar The Python manipulator can be implemented as
class Manipulator:
  def modifyContextMenu(self, recipient):
    if recipient == "View":
      return [{"remove" : "Standard views"},
              {"insert" : "Std_Windows", "menuItem" : "View_Measure_Toggle_All"}]
manip = Manipulator()
Gui.addWorkbenchManipulator(manip)
This manipulator removes the "Standard views sub-menu and adds the Std_Windows before the View_Measure_Toggle_All command.
Definition at line 181 of file WorkbenchManipulatorPython.cpp.
References Base::PyException::ReportException().
modifyDockWindows()
void WorkbenchManipulatorPython::modifyDockWindows (DockWindowItems * dockWindow) override protected
modifyDockWindows Method to manipulate the dock window structure of a workbench
Definition at line 322 of file WorkbenchManipulatorPython.cpp.
References Base::PyException::ReportException().
modifyMenuBar()
void WorkbenchManipulatorPython::modifyMenuBar (MenuItem * menuBar) override protected
modifyMenuBar Method to manipulate the menu structure of a workbench.
WorkbenchManipulatorPython::modifyMenuBar.
Parameters
menuBar The Python manipulator can be implemented as
class Manipulator:
  def modifyMenuBar(self):
    return [{"remove" : "Std_Quit"},
            {"append" : "Std_About", "menuItem" : "Std_DlgMacroRecord"},
            {"insert" : "Std_About", "menuItem" : "Std_DlgParameter"}
            {"insert" : "Std_Windows", "menuItem" : "Std_DlgParameter", "after" : ""}]
manip = Manipulator()
Gui.addWorkbenchManipulator(manip)
This manipulator removes the Std_Quit command, appends the Std_About command to the Macro menu, inserts it to the Tools menu before the Std_DlgParameter and adds the Std_Windows after the Std_DlgParameter command.
Definition at line 81 of file WorkbenchManipulatorPython.cpp.
References Base::PyException::ReportException().
modifyToolBars()
void WorkbenchManipulatorPython::modifyToolBars (ToolBarItem * toolBar) override protected
modifyToolBars Method to manipulate the toolbar structure of a workbench
Definition at line 219 of file WorkbenchManipulatorPython.cpp.
References Base::PyException::ReportException().
operator=() [1/2]
WorkbenchManipulatorPython& Gui::WorkbenchManipulatorPython::operator= (const WorkbenchManipulatorPython &) delete
operator=() [2/2]
WorkbenchManipulatorPython& Gui::WorkbenchManipulatorPython::operator= (WorkbenchManipulatorPython &&) delete
removeManipulator()
void WorkbenchManipulatorPython::removeManipulator (const Py::Object & obj) static
Definition at line 39 of file WorkbenchManipulatorPython.cpp.
References Gui::WorkbenchManipulator::getManipulators(), and Gui::WorkbenchManipulator::removeManipulator().
Referenced by Gui::ApplicationPy::sRemoveWbManipulator().
The documentation for this class was generated from the following files:
WorkbenchManipulatorPython.h
WorkbenchManipulatorPython.cpp