FreeCAD: ifc2x3.ifcreinforcementbarproperties Class Reference
ifc2x3.ifcreinforcementbarproperties Class Reference
Public Member Functions
def __init__ (self, totalcrosssectionarea, steelgrade, barsurface, effectivedepth, nominalbardiameter, barcount)
def totalcrosssectionarea ()
def steelgrade ()
def barsurface ()
def effectivedepth ()
def nominalbardiameter ()
def barcount ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
totalcrosssectionarea
steelgrade
barsurface
effectivedepth
nominalbardiameter
barcount
Detailed Description
Entity ifcreinforcementbarproperties definition.
:param totalcrosssectionarea
:type totalcrosssectionarea:ifcareameasure
:param steelgrade
:type steelgrade:ifclabel
:param barsurface
:type barsurface:ifcreinforcingbarsurfaceenum
:param effectivedepth
:type effectivedepth:ifclengthmeasure
:param nominalbardiameter
:type nominalbardiameter:ifcpositivelengthmeasure
:param barcount
:type barcount:ifccountmeasure
Definition at line 2953 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcreinforcementbarproperties.__init__ (self, totalcrosssectionarea, steelgrade, barsurface, effectivedepth, nominalbardiameter, barcount)
Definition at line 2974 of file ifc2x3.py.
Member Function Documentation
barcount()
def ifc2x3.ifcreinforcementbarproperties.barcount ()
Definition at line 3053 of file ifc2x3.py.
References ifc2x3.ifcreinforcementbarproperties._barcount, ifc2x3.ifcreinforcementbarproperties.barcount, and SCL.TypeChecker.check_type().
barsurface()
def ifc2x3.ifcreinforcementbarproperties.barsurface ()
Definition at line 3011 of file ifc2x3.py.
References ifc2x3.ifcreinforcementbarproperties._barsurface, ifc2x3.ifcreinforcementbarproperties.barsurface, and SCL.TypeChecker.check_type().
effectivedepth()
def ifc2x3.ifcreinforcementbarproperties.effectivedepth ()
Definition at line 3025 of file ifc2x3.py.
References ifc2x3.ifcreinforcementbarproperties._effectivedepth, SCL.TypeChecker.check_type(), and ifc2x3.ifcreinforcementbarproperties.effectivedepth.
nominalbardiameter()
def ifc2x3.ifcreinforcementbarproperties.nominalbardiameter ()
Definition at line 3039 of file ifc2x3.py.
References ifc2x3.ifcreinforcementbarproperties._nominalbardiameter, SCL.TypeChecker.check_type(), and ifc2x3.ifcreinforcementbarproperties.nominalbardiameter.
steelgrade()
def ifc2x3.ifcreinforcementbarproperties.steelgrade ()
Definition at line 2997 of file ifc2x3.py.
References ifc2x3.ifcreinforcementbarproperties._steelgrade, SCL.TypeChecker.check_type(), and ifc2x3.ifcreinforcementbarproperties.steelgrade.
totalcrosssectionarea()
def ifc2x3.ifcreinforcementbarproperties.totalcrosssectionarea ()
Definition at line 2983 of file ifc2x3.py.
References ifc2x3.ifcreinforcementbarproperties._totalcrosssectionarea, SCL.TypeChecker.check_type(), and ifc2x3.ifcreinforcementbarproperties.totalcrosssectionarea.
Member Data Documentation
barcount
ifc2x3.ifcreinforcementbarproperties.barcount
Definition at line 2980 of file ifc2x3.py.
Referenced by ifc2x3.ifcreinforcementbarproperties.barcount().
barsurface
ifc2x3.ifcreinforcementbarproperties.barsurface
Definition at line 2977 of file ifc2x3.py.
Referenced by ifc2x3.ifcreinforcementbarproperties.barsurface().
effectivedepth
ifc2x3.ifcreinforcementbarproperties.effectivedepth
Definition at line 2978 of file ifc2x3.py.
Referenced by ifc2x3.ifcreinforcementbarproperties.effectivedepth().
nominalbardiameter
ifc2x3.ifcreinforcementbarproperties.nominalbardiameter
Definition at line 2979 of file ifc2x3.py.
Referenced by ifc2x3.ifcreinforcementbarproperties.nominalbardiameter().
steelgrade
ifc2x3.ifcreinforcementbarproperties.steelgrade
Definition at line 2976 of file ifc2x3.py.
Referenced by ifc2x3.ifcreinforcementbarproperties.steelgrade().
totalcrosssectionarea
ifc2x3.ifcreinforcementbarproperties.totalcrosssectionarea
Definition at line 2975 of file ifc2x3.py.
Referenced by ifc2x3.ifcreinforcementbarproperties.totalcrosssectionarea().
The documentation for this class was generated from the following file:
ifc2x3.py