FreeCAD: Gui::Dialog::DlgCustomActionsImp Class Reference
Gui::Dialog::DlgCustomActionsImp Class Reference
#include <DlgActionsImp.h>
Signals
void addMacroAction (const QByteArray &)
void removeMacroAction (const QByteArray &)
void modifyMacroAction (const QByteArray &)
Public Member Functions
DlgCustomActionsImp (QWidget *parent=nullptr)
~DlgCustomActionsImp () override
Public Member Functions inherited from Gui::Dialog::CustomizeActionPage
CustomizeActionPage (QWidget *parent=nullptr)
~CustomizeActionPage () override
Protected Slots
void onAddMacroAction (const QByteArray &) override
void onRemoveMacroAction (const QByteArray &) override
void onModifyMacroAction (const QByteArray &) override
Protected Slots inherited from Gui::Dialog::CustomizeActionPage
virtual void onAddMacroAction (const QByteArray &)=0
virtual void onRemoveMacroAction (const QByteArray &)=0
virtual void onModifyMacroAction (const QByteArray &)=0
Protected Member Functions
bool event (QEvent *e) override
void changeEvent (QEvent *e) override
void setupConnections ()
void onActionListWidgetItemActivated (QTreeWidgetItem *i)
void onButtonChoosePixmapClicked ()
void onButtonAddActionClicked ()
void onButtonRemoveActionClicked ()
void onButtonReplaceActionClicked ()
Protected Member Functions inherited from Gui::Dialog::CustomizeActionPage
bool event (QEvent *e) override
Detailed Description
This class implements the creation of user defined actions executing a recorded macro. It is possible to use these actions in own toolbars or commandbars.
See also
Gui::Action
MacroCommand
Command
Author
Werner Mayer
Definition at line 51 of file DlgActionsImp.h.
Constructor & Destructor Documentation
DlgCustomActionsImp()
DlgCustomActionsImp::DlgCustomActionsImp (QWidget * parent = nullptr) explicit
Constructs a DlgCustomActionsImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
Definition at line 57 of file DlgActionsImp.cpp.
References App::GetApplication(), ParameterGrp::GetASCII(), App::Application::getHomePath(), App::Application::GetParameterGroupByPath(), App::Application::getUserMacroDir(), SplineSurface::i, App::ExpressionParser::labels, and setupConnections().
~DlgCustomActionsImp()
DlgCustomActionsImp::~DlgCustomActionsImp () override
Destroys the object and frees any allocated resources
Definition at line 95 of file DlgActionsImp.cpp.
References Gui::MacroCommand::save().
Member Function Documentation
addMacroAction
void Gui::Dialog::DlgCustomActionsImp::addMacroAction (const QByteArray &) signal
Referenced by event(), and onButtonAddActionClicked().
changeEvent()
void DlgCustomActionsImp::changeEvent (QEvent * e) override protected virtual
Implements Gui::Dialog::CustomizeActionPage.
Definition at line 524 of file DlgActionsImp.cpp.
References SCL.SimpleDataTypes::e.
event()
bool DlgCustomActionsImp::event (QEvent * e) override protected
Trigger for reparent event.
Definition at line 118 of file DlgActionsImp.cpp.
References addMacroAction(), draftgeoutils.intersections::connect(), SCL.SimpleDataTypes::e, modifyMacroAction(), and removeMacroAction().
modifyMacroAction
void Gui::Dialog::DlgCustomActionsImp::modifyMacroAction (const QByteArray &) signal
Referenced by event(), and onButtonReplaceActionClicked().
onActionListWidgetItemActivated()
void DlgCustomActionsImp::onActionListWidgetItemActivated (QTreeWidgetItem * i) protected
Enables/disables buttons for deletion
Definition at line 187 of file DlgActionsImp.cpp.
References Gui::BitmapFactory(), Gui::Application::commandManager(), Gui::CommandManager::getCommandByName(), SplineSurface::i, Gui::ShortcutManager::instance(), Gui::Application::Instance, buildPsets::p, and Gui::BitmapFactoryInst::pixmap().
Referenced by setupConnections().
onAddMacroAction
void DlgCustomActionsImp::onAddMacroAction (const QByteArray &) override protected slot
Definition at line 155 of file DlgActionsImp.cpp.
onButtonAddActionClicked()
void DlgCustomActionsImp::onButtonAddActionClicked () protected
Adds a custom action
Definition at line 235 of file DlgActionsImp.cpp.
References Gui::CommandManager::addCommand(), addMacroAction(), Gui::Application::commandManager(), Gui::ShortcutManager::instance(), Gui::Application::Instance, Gui::CommandManager::newMacroName(), Gui::ShortcutManager::setShortcut(), and Path.Log::warning().
Referenced by setupConnections().
onButtonChoosePixmapClicked()
void DlgCustomActionsImp::onButtonChoosePixmapClicked () protected
Opens a iconview to select a pixmap
Definition at line 506 of file DlgActionsImp.cpp.
References Gui::Dialog::IconDialog::currentItem().
Referenced by setupConnections().
onButtonRemoveActionClicked()
void DlgCustomActionsImp::onButtonRemoveActionClicked () protected
Deletes a custom action
Definition at line 391 of file DlgActionsImp.cpp.
References Gui::Application::commandManager(), Gui::CommandManager::getGroupCommands(), Gui::Application::Instance, Gui::CommandManager::removeCommand(), and removeMacroAction().
Referenced by setupConnections().
onButtonReplaceActionClicked()
void DlgCustomActionsImp::onButtonReplaceActionClicked () protected
Shows the setup of the action
Definition at line 309 of file DlgActionsImp.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::BitmapFactory(), Gui::Application::commandManager(), Gui::CommandManager::getCommandByName(), Gui::ShortcutManager::getShortcut(), Gui::ShortcutManager::instance(), Gui::Application::Instance, modifyMacroAction(), Gui::BitmapFactoryInst::pixmap(), Gui::CommandBase::setWhatsThis(), and Path.Log::warning().
Referenced by setupConnections().
onModifyMacroAction
void DlgCustomActionsImp::onModifyMacroAction (const QByteArray &) override protected slot
Definition at line 166 of file DlgActionsImp.cpp.
onRemoveMacroAction
void DlgCustomActionsImp::onRemoveMacroAction (const QByteArray & name) override protected slot
Definition at line 160 of file DlgActionsImp.cpp.
References Gui::ShortcutManager::instance(), and Gui::ShortcutManager::reset().
removeMacroAction
void Gui::Dialog::DlgCustomActionsImp::removeMacroAction (const QByteArray &) signal
Referenced by event(), and onButtonRemoveActionClicked().
setupConnections()
void DlgCustomActionsImp::setupConnections () protected
Definition at line 102 of file DlgActionsImp.cpp.
References draftgeoutils.intersections::connect(), onActionListWidgetItemActivated(), onButtonAddActionClicked(), onButtonChoosePixmapClicked(), onButtonRemoveActionClicked(), and onButtonReplaceActionClicked().
Referenced by DlgCustomActionsImp().
The documentation for this class was generated from the following files:
DlgActionsImp.h
DlgActionsImp.cpp