FreeCAD: Attacher::AttachEngine3D Class Reference
Attacher::AttachEngine3D Class Reference
#include <Attacher.h>
Public Member Functions
AttachEngine3D ()
AttachEngine3D * copy () const override
Base::Placement _calculateAttachedPlacement (const std::vector< App::DocumentObject * > &objs, const std::vector< std::string > &subs, const Base::Placement &origPlacement) const override
Public Member Functions inherited from Attacher::AttachEngine
AttachEngine ()
virtual void setUp (const App::PropertyLinkSubList &references, eMapMode mapMode=mmDeactivated, bool mapReverse=false, double attachParameter=0.0, double surfU=0.0, double surfV=0.0, const Base::Placement &attachmentOffset=Base::Placement())
virtual void setUp (const AttachEngine &another)
void setOffset (const Base::Placement &offset)
Base::Placement calculateAttachedPlacement (const Base::Placement &origPlacement, bool *subChanged=0)
void setReferences (const App::PropertyLinkSubList &references)
void setReferences (const std::vector< App::SubObjectT > &references)
Base::Placement placementFactory (const gp_Dir &ZAxis, gp_Vec XAxis, gp_Pnt Origin, gp_Pnt refOrg=gp_Pnt(), bool useRefOrg_Line=false, bool useRefOrg_Plane=false, bool makeYVertical=false, bool makeLegacyFlatFaceOrientation=false, Base::Placement *placeOfRef=nullptr) const
placementFactory calculates placement from Z axis direction, optional X axis direction, and origin point.
virtual void suggestMapModes (SuggestResult &result) const
suggestMapModes is the procedure that knows everything about mapping modes. It returns the most appropriate mapping mode, as well as list of all modes that will accept the set of references. In case no modes apply, extra information regarding reasons is returned in msg.
void EnableAllSupportedModes ()
EnableAllModes enables all modes that have shape type lists filled. The function acts on modeEnabled array.
~AttachEngine () override=default
std::vector< App::DocumentObject * > getRefObjects () const
const std::vector< std::string > & getSubValues () const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Attacher::AttachEngine
static eRefType getShapeType (const TopoDS_Shape &sh)
getShapeType by shape. Will never set rtFlagHasPlacement.
static eRefType getShapeType (const App::DocumentObject *obj, const std::string &subshape)
getShapeType by link content. Will include rtFlagHasPlacement, if applies.
static eRefType downgradeType (eRefType type)
downgradeType converts a more-specific type into a less-specific type (e.g. rtCircle->rtCurve, rtCurve->rtEdge, rtEdge->rtAnything)
static int getTypeRank (eRefType type)
getTypeRank determines, how specific is the supplied shape type. The ranks are outlined in definition of eRefType. The ranks are defined by implementation of downgradeType().
static int isShapeOfType (eRefType shapeType, eRefType requirement)
isShapeOfType tests if a shape fulfills the requirement of a mode, and returns a score of how spot on was the requirement.
static std::string getModeName (eMapMode mmode)
getModeName
static eMapMode getModeByName (const std::string &modeName)
static std::string getRefTypeName (eRefType shapeType)
static eRefType getRefTypeByName (const std::string &typeName)
static GProp_GProps getInertialPropsOfShape (const std::vector< const Part::TopoShape * > &shapes)
static void verifyReferencesAreSafe (const App::PropertyLinkSubList &references)
verifyReferencesAreSafe: checks if pointers in references still point to objects contained in open documents. This guarantees the links are valid. Throws Base::Exception if invalid links are found.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from Attacher::AttachEngine
std::string docName
std::vector< std::string > objNames
std::vector< std::string > subnames
std::vector< std::string > shadowSubs
eMapMode mapMode = mmDeactivated
bool mapReverse = false
double attachParameter = 0.0
double surfU = 0.0
double surfV = 0.0
Base::Placement attachmentOffset
std::vector< bool > modeEnabled
modeEnabled is an indicator, whether some mode is ever suggested or not. Set to false to suppress suggesting some mode, like so: modeEnabled[mmModeIDontLike] = false;
std::vector< refTypeStringList > modeRefTypes
Static Public Attributes inherited from Attacher::AttachEngine
static const char * eMapModeStrings []
static const char * eRefTypeStrings []
Protected Member Functions inherited from Attacher::AttachEngine
refTypeString cat (eRefType rt1)
refTypeString cat (eRefType rt1, eRefType rt2)
refTypeString cat (eRefType rt1, eRefType rt2, eRefType rt3)
refTypeString cat (eRefType rt1, eRefType rt2, eRefType rt3, eRefType rt4)
Static Protected Member Functions inherited from Attacher::AttachEngine
static void readLinks (const std::vector< App::DocumentObject * > &objs, const std::vector< std::string > &subs, std::vector< const Part::TopoShape * > &shapes, std::vector< Part::TopoShape > &storage, std::vector< eRefType > &types)
AttachEngine3D::readLinks.
static void throwWrongMode (eMapMode mmode)
static App::GeoFeature * extractGeoFeature (App::DocumentObject *obj)
static Part::TopoShape extractSubShape (App::DocumentObject *obj, const std::string &subname)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 487 of file Attacher.h.
Constructor & Destructor Documentation
AttachEngine3D()
AttachEngine3D::AttachEngine3D ()
Definition at line 1044 of file Attacher.cpp.
References Attacher::mmConcentric, Attacher::mmDummy_NumberOfModes, Attacher::mmFlatFace, Attacher::mmFolding, Attacher::mmFrenetNB, Attacher::mmFrenetTB, Attacher::mmFrenetTN, Attacher::mmInertialCS, Attacher::mmNormalToPath, Attacher::mmObjectXY, Attacher::mmObjectXZ, Attacher::mmObjectYZ, Attacher::mmOYX, Attacher::mmOZX, Attacher::mmParallelPlane, Attacher::mmRevolutionSection, Attacher::mmTangentPlane, Attacher::mmThreePointsNormal, Attacher::mmThreePointsPlane, Attacher::mmTranslate, Attacher::rtAnything, Attacher::rtCircle, Attacher::rtConic, Attacher::rtCurve, Attacher::rtEdge, Attacher::rtFace, Attacher::rtFlagHasPlacement, Attacher::rtFlatFace, Attacher::rtLine, Attacher::rtVertex, and toolbit-attributes::s.
Member Function Documentation
_calculateAttachedPlacement()
Base::Placement AttachEngine3D::_calculateAttachedPlacement (const std::vector< App::DocumentObject * > & objs, const std::vector< std::string > & subs, const Base::Placement & origPlacement) const override virtual
Implements Attacher::AttachEngine.
Definition at line 1159 of file Attacher.cpp.
References RobotExample::B, ArchCommands::check(), Base::Console(), D_PI, SCL.SimpleDataTypes::e, Base::Rotation::fromNormalVector(), Part::Geometry::fromShape(), App::GeoFeature::getGlobalPlacement(), Part::Tools::getNormal(), Base::Placement::getPosition(), Base::Placement::getRotation(), importers.importIFClegacy::getShape(), Handle(), SplineSurface::i, draftgeoutils.general::isNull(), Base::Rotation::makeRotationByAxes(), middle, Attacher::mmConcentric, Attacher::mmDeactivated, Attacher::mmFlatFace, Attacher::mmFolding, Attacher::mmFrenetNB, Attacher::mmFrenetTB, Attacher::mmFrenetTN, Attacher::mmInertialCS, Attacher::mmMidpoint, Attacher::mmNormalToPath, Attacher::mmObjectXY, Attacher::mmObjectXZ, Attacher::mmObjectYZ, Attacher::mmOXY, Attacher::mmOXZ, Attacher::mmOYX, Attacher::mmOYZ, Attacher::mmOZX, Attacher::mmOZY, Attacher::mmParallelPlane, Attacher::mmRevolutionSection, Attacher::mmTangentPlane, Attacher::mmThreePointsNormal, Attacher::mmThreePointsPlane, Attacher::mmTranslate, replaceobj::objs, buildPsets::p, WorkingPlane::plane, RobotExample::pos, Base::pow(), Attacher::rtConic, Attacher::rtFlagHasPlacement, Base::Placement::setPosition(), Base::Placement::setRotation(), importers.importIFCmulticore::subs, THROWM, buildPsets::u, TestSpreadsheet::v, draftgeoutils.general::v1(), SurfaceTests.TestBlendCurve::vec, Base::ConsoleSingleton::Warning(), DrawingExample::X, Base::Vector3< float_type >::x, DrawingExample::Y, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by Attacher::AttachEnginePlane::_calculateAttachedPlacement(), Attacher::AttachEngineLine::_calculateAttachedPlacement(), and Attacher::AttachEnginePoint::_calculateAttachedPlacement().
copy()
AttachEngine3D * AttachEngine3D::copy () const override virtual
Implements Attacher::AttachEngine.
Definition at line 1151 of file Attacher.cpp.
References buildPsets::p.
The documentation for this class was generated from the following files:
Attacher.h
Attacher.cpp