FreeCAD: Gui::SoFCSelectionRoot Class Reference
Gui::SoFCSelectionRoot Class Reference
#include <SoFCUnifiedSelection.h>
Classes
struct SelContext
class Stack
struct StackComp
Public Types
enum SelectStyles { Full, Box, PassThrough }
Public Member Functions
SoFCSelectionRoot (bool trackCacheMode=false)
void GLRenderBelowPath (SoGLRenderAction *action) override
void GLRenderInPath (SoGLRenderAction *action) override
void doAction (SoAction *action) override
void pick (SoPickAction *action) override
void rayPick (SoRayPickAction *action) override
void handleEvent (SoHandleEventAction *action) override
void search (SoSearchAction *action) override
void getPrimitiveCount (SoGetPrimitiveCountAction *action) override
void getBoundingBox (SoGetBoundingBoxAction *action) override
void getMatrix (SoGetMatrixAction *action) override
void callback (SoCallbackAction *action) override
void resetContext ()
bool hasColorOverride () const
void setColorOverride (App::Color c)
void removeColorOverride ()
Public Member Functions inherited from Gui::SoFCSeparator
SoFCSeparator (bool trackCacheMode=true)
void GLRenderBelowPath (SoGLRenderAction *action) override
Static Public Member Functions
static void initClass ()
static void finish ()
template<class T >
static std::shared_ptr< T > getRenderContext (SoNode *node, std::shared_ptr< T > def=std::shared_ptr< T >())
template<class T >
static std::shared_ptr< T > getRenderContext (SoNode *node, std::shared_ptr< T > def, std::shared_ptr< T > &ctx2)
template<class T >
static std::shared_ptr< T > getActionContext (SoAction *action, SoNode *node, std::shared_ptr< T > def=std::shared_ptr< T >(), bool create=true)
static bool removeActionContext (SoAction *action, SoNode *node)
template<class T >
static std::shared_ptr< T > getSecondaryActionContext (SoAction *action, SoNode *node)
static void checkSelection (bool &sel, SbColor &selColor, bool &hl, SbColor &hlColor)
static void moveActionStack (SoAction *from, SoAction *to, bool erase)
static SoNode * getCurrentRoot (bool front, SoNode *def)
static bool checkColorOverride (SoState *state)
static bool renderBBox (SoGLRenderAction *action, SoNode *node, SbColor color)
Static Public Member Functions inherited from Gui::SoFCSeparator
static void initClass ()
static void finish ()
static void setCacheMode (CacheEnabled mode)
static CacheEnabled getCacheMode ()
Public Attributes
SoSFEnum selectionStyle
Protected Types
using ContextMap = std::map< Stack, SoFCSelectionContextBasePtr, StackComp >
using SelContextPtr = std::shared_ptr< SelContext >
using ColorStack = std::vector< SbColor >
Protected Member Functions
~SoFCSelectionRoot () override
void renderPrivate (SoGLRenderAction *, bool inPath)
bool _renderPrivate (SoGLRenderAction *, bool inPath)
bool doActionPrivate (Stack &stack, SoAction *)
Static Protected Member Functions
static SoFCSelectionContextBasePtr getNodeContext (Stack &stack, SoNode *node, SoFCSelectionContextBasePtr def)
static SoFCSelectionContextBasePtr getNodeContext2 (Stack &stack, SoNode *node, SoFCSelectionContextBase::MergeFunc *merge)
static std::pair< bool, SoFCSelectionContextBasePtr * > findActionContext (SoAction *action, SoNode *node, bool create, bool erase)
Protected Attributes
ContextMap contextMap
ContextMap contextMap2
bool overrideColor = false
SbColor colorOverride
float transOverride = 0.0f
SoColorPacker shapeColorPacker
Static Protected Attributes
static Stack SelStack
static std::unordered_map< SoAction *, Stack > ActionStacks
static ColorStack SelColorStack
static ColorStack HlColorStack
static SoFCSelectionRoot * ShapeColorNode
Detailed Description
Definition at line 184 of file SoFCUnifiedSelection.h.
Member Typedef Documentation
ColorStack
using Gui::SoFCSelectionRoot::ColorStack = std::vector<SbColor> protected
Definition at line 365 of file SoFCUnifiedSelection.h.
ContextMap
using Gui::SoFCSelectionRoot::ContextMap = std::map<Stack,SoFCSelectionContextBasePtr,StackComp> protected
Definition at line 351 of file SoFCUnifiedSelection.h.
SelContextPtr
using Gui::SoFCSelectionRoot::SelContextPtr = std::shared_ptr<SelContext> protected
Definition at line 364 of file SoFCUnifiedSelection.h.
Member Enumeration Documentation
SelectStyles
enum Gui::SoFCSelectionRoot::SelectStyles
Enumerator
Full
Box
PassThrough
Definition at line 319 of file SoFCUnifiedSelection.h.
Constructor & Destructor Documentation
SoFCSelectionRoot()
SoFCSelectionRoot::SoFCSelectionRoot (bool trackCacheMode = false) explicit
Definition at line 1106 of file SoFCUnifiedSelection.cpp.
References Box, Full, PassThrough, and selectionStyle.
~SoFCSelectionRoot()
SoFCSelectionRoot::~SoFCSelectionRoot () override protected default
Member Function Documentation
_renderPrivate()
bool SoFCSelectionRoot::_renderPrivate (SoGLRenderAction * action, bool inPath) protected
Definition at line 1314 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Box, colorOverride, getNodeContext2(), HlColorStack, Gui::ViewParams::instance(), Gui::SoFCSelectionRoot::SelContext::merge, MeshCore::MeshIO::OVERALL, overrideColor, packer, PassThrough, renderBBox(), SelColorStack, selectionStyle, SelStack, ShapeColorNode, shapeColorPacker, and transOverride.
Referenced by renderPrivate().
callback()
void SoFCSelectionRoot::callback (SoCallbackAction * action) override
Definition at line 1546 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, BEGIN_ACTION, and END_ACTION.
Referenced by Path.Main.Gui.Camotics.CamoticsSimulation::execute().
checkColorOverride()
bool SoFCSelectionRoot::checkColorOverride (SoState * state) static
Definition at line 1427 of file SoFCUnifiedSelection.cpp.
References colorOverride, MeshCore::MeshIO::OVERALL, packer, ShapeColorNode, shapeColorPacker, and transOverride.
checkSelection()
void SoFCSelectionRoot::checkSelection (bool & sel, SbColor & selColor, bool & hl, SbColor & hlColor) static
Definition at line 1450 of file SoFCUnifiedSelection.cpp.
References HlColorStack, and SelColorStack.
Referenced by Gui::SoFCSelectionContext::checkGlobal(), and Gui::SoFCPathAnnotation::GLRenderBelowPath().
doAction()
void SoFCSelectionRoot::doAction (SoAction * action) override
Definition at line 1552 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, BEGIN_ACTION, doActionPrivate(), and END_ACTION.
doActionPrivate()
bool SoFCSelectionRoot::doActionPrivate (Stack & stack, SoAction * action) protected
Definition at line 1559 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::SoSelectionElementAction::All, Gui::SoSelectionElementAction::Color, getActionContext(), getNodeContext2(), Gui::SoSelectionElementAction::Hide, Gui::SoFCSelectionRoot::SelContext::merge, Gui::SoSelectionElementAction::None, removeActionContext(), resetContext(), and Gui::SoSelectionElementAction::Show.
Referenced by doAction(), getBoundingBox(), getMatrix(), pick(), and rayPick().
findActionContext()
std::pair< bool, SoFCSelectionContextBasePtr * > SoFCSelectionRoot::findActionContext (SoAction * action, SoNode * node, bool create, bool erase) static protected
Definition at line 1191 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, ActionStacks, contextMap, contextMap2, and importers.importIFClegacy::create().
finish()
void SoFCSelectionRoot::finish () static
Definition at line 1129 of file SoFCUnifiedSelection.cpp.
References so_bbox_cleanup().
Referenced by drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::accept(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::accept(), draftguitools.gui_split.Split::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_subelements.SubelementHighlight::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rotate.Rotate::action(), draftguitools.gui_fillets.Fillet::action(), draftguitools.gui_move.Move::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_arcs.Arc::action(), draftguitools.gui_texts.Text::action(), draftguitools.gui_scale.Scale::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_trimex.Trimex::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_styles.ApplyStyle::Activated(), draftguitools.gui_join.Join::Activated(), draftguitools.gui_draft2sketch.Draft2Sketch::Activated(), draftguitools.gui_downgrade.Downgrade::Activated(), draftguitools.gui_upgrade.Upgrade::Activated(), draftguitools.gui_shape2dview.Shape2DView::Activated(), draftguitools.gui_facebinders.Facebinder::Activated(), draftguitools.gui_subelements.SubelementHighlight::Activated(), draftguitools.gui_wire2spline.WireToBSpline::Activated(), draftguitools.gui_clone.Clone::Activated(), draftguitools.gui_dimensions.Dimension::Activated(), draftguitools.gui_edit.Edit::Activated(), draftguitools.gui_selectplane.Draft_SelectPlane::check_selection(), DraftGui.DraftToolBar::checkSpecialChars(), draftguitools.gui_points.Point::click(), draftguitools.gui_orthoarray.OrthoArray::completed(), draftguitools.gui_polararray.PolarArray::completed(), draftguitools.gui_circulararray.CircularArray::completed(), draftguitools.gui_labels.Label::create(), bimcommands.BimText.BIM_Text::createObject(), draftguitools.gui_rectangles.Rectangle::createObject(), draftguitools.gui_ellipses.Ellipse::createObject(), draftguitools.gui_texts.Text::createObject(), draftviewproviders.view_text.ViewProviderText::createObject(), draftguitools.gui_stretch.Stretch::doStretch(), draftguitools.gui_fillets.Fillet::draw_arc(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), DraftGui.DraftToolBar::editUi(), DraftGui.DraftToolBar::escape(), Gui::SoFCDB::finish(), draftguitools.gui_move.Move::get_object_selection(), draftguitools.gui_rotate.Rotate::get_object_selection(), draftguitools.gui_scale.Scale::get_object_selection(), draftguitools.gui_arcs.Arc_3Points::getPoint(), draftguitools.gui_edit.Edit::keyPressed(), draftguitools.gui_dimensions.Dimension::numericInput(), draftguitools.gui_offset.Offset::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), draftguitools.gui_trimex.Trimex::numericRadius(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_align(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_auto(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_center(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_front(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_move(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_next(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_previous(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_side(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_top(), bimcommands.BimShape2DView.BIM_Shape2DView::proceed(), draftguitools.gui_join.Join::proceed(), draftguitools.gui_subelements.SubelementHighlight::proceed(), draftguitools.gui_draft2sketch.Draft2Sketch::proceed(), draftguitools.gui_downgrade.Downgrade::proceed(), bimcommands.BimSlab.BIM_Slab::proceed(), draftguitools.gui_upgrade.Upgrade::proceed(), draftguitools.gui_facebinders.Facebinder::proceed(), draftguitools.gui_pathtwistedarray.PathTwistedArray::proceed(), draftguitools.gui_shape2dview.Shape2DView::proceed(), draftguitools.gui_clone.Clone::proceed(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_pointarray.PointArray::proceed(), draftguitools.gui_patharray.PathArray::proceed(), draftguitools.gui_trimex.Trimex::proceed(), draftguitools.gui_edit.Edit::proceed(), draftguitools.gui_selectplane.Draft_SelectPlane::reject(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::reject(), drafttaskpanels.task_polararray.TaskPanelPolarArray::reject(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::reject(), and draftguitools.gui_edit.Edit::setTrackers().
getActionContext()
template<class T > static std::shared_ptr<T> Gui::SoFCSelectionRoot::getActionContext (SoAction * action, SoNode * node, std::shared_ptr< T > def = std::shared_ptr<T>(), bool create = true) inline static
Get the selection context for an action.
Parameters
action the action. SoSelectionElementAction has any option to query for secondary context.
See also
getRenderContext for detail about secondary context
Parameters
node the querying node
def default context if none is found, only used if querying non-secondary context
create create a new context if none is found
Returns
If no SoFCSelectionRoot is found in the current path of action, def is returned. Otherwise a selection context returned. A new one will be created if none is found.
Definition at line 261 of file SoFCUnifiedSelection.h.
References Path.Post.scripts.dynapath_4060_post::action, and importers.importIFClegacy::create().
Referenced by PartGui::SoBrepEdgeSet::doAction(), PartGui::SoBrepPointSet::doAction(), PartGui::SoBrepFaceSet::doAction(), Gui::SoFCSelection::doAction(), and doActionPrivate().
getBoundingBox()
void SoFCSelectionRoot::getBoundingBox (SoGetBoundingBoxAction * action) override
Definition at line 1531 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, BEGIN_ACTION, doActionPrivate(), and END_ACTION.
getCurrentRoot()
SoNode * SoFCSelectionRoot::getCurrentRoot (bool front, SoNode * def) static
Definition at line 1135 of file SoFCUnifiedSelection.cpp.
References SelStack.
getMatrix()
void SoFCSelectionRoot::getMatrix (SoGetMatrixAction * action) override
Definition at line 1539 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, BEGIN_ACTION, doActionPrivate(), and END_ACTION.
getNodeContext()
SoFCSelectionContextBasePtr SoFCSelectionRoot::getNodeContext (Stack & stack, SoNode * node, SoFCSelectionContextBasePtr def) static protected
Definition at line 1141 of file SoFCUnifiedSelection.cpp.
getNodeContext2()
SoFCSelectionContextBasePtr SoFCSelectionRoot::getNodeContext2 (Stack & stack, SoNode * node, SoFCSelectionContextBase::MergeFunc * merge) static protected
Definition at line 1162 of file SoFCUnifiedSelection.cpp.
References Gui::SoFCSelectionRoot::Stack::offset.
Referenced by _renderPrivate(), and doActionPrivate().
getPrimitiveCount()
void SoFCSelectionRoot::getPrimitiveCount (SoGetPrimitiveCountAction * action) override
Definition at line 1525 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, BEGIN_ACTION, and END_ACTION.
getRenderContext() [1/2]
template<class T > static std::shared_ptr<T> Gui::SoFCSelectionRoot::getRenderContext (SoNode * node, std::shared_ptr< T > def, std::shared_ptr< T > & ctx2) inline static
Returns selection context for rendering.
Parameters
node the querying node
def default context if none is found
ctx2 secondary context output
Returns
Returned the primary context for selection, and the context is always stored in the first encountered SoFCSelectionRoot in the path. It is keyed using the entire sequence of SoFCSelectionRoot along the path to node, replacing the first SoFCSelectionRoot with the given node.
Secondary context returned in ctx2 is for customized highlighting, and is not affected by mouse event. The highlight is applied manually using SoSelectionElementAction. It is stored in the last encountered SoFCSelectionRoot, and is keyed using the querying node and (if there are more than one SoFCSelectionRoot along the path) the first SoFCSelectionRoot. The reason is so that any link to a node (new links means additional SoFCSelectionRoot added in front) with customized subelement highlight will also show the highlight. Secondary context can be chained, which why the secondary context type must provide an function called merge() for getRenderContext() to merge the context. See SoFCSelectionContext::merge() for an implementation of merging multiple context.
Note
For simplicity reason, currently secondary context is only freed when the storage SoFCSSelectionRoot node is freed.
Definition at line 240 of file SoFCUnifiedSelection.h.
getRenderContext() [2/2]
template<class T > static std::shared_ptr<T> Gui::SoFCSelectionRoot::getRenderContext (SoNode * node, std::shared_ptr< T > def = std::shared_ptr<T>()) inline static
Definition at line 208 of file SoFCUnifiedSelection.h.
Referenced by PartGui::SoBrepFaceSet::GLRender().
getSecondaryActionContext()
template<class T > static std::shared_ptr<T> Gui::SoFCSelectionRoot::getSecondaryActionContext (SoAction * action, SoNode * node) inline static
Definition at line 288 of file SoFCUnifiedSelection.h.
References Path.Post.scripts.dynapath_4060_post::action.
GLRenderBelowPath()
void SoFCSelectionRoot::GLRenderBelowPath (SoGLRenderAction * action) override
Definition at line 1417 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and renderPrivate().
Referenced by Gui::SoFCPathAnnotation::GLRender(), Gui::SoFCPathAnnotation::GLRenderInPath(), and GLRenderInPath().
GLRenderInPath()
void SoFCSelectionRoot::GLRenderInPath (SoGLRenderAction * action) override
Definition at line 1421 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, GLRenderBelowPath(), and renderPrivate().
Referenced by Gui::SoFCPathAnnotation::GLRender().
handleEvent()
void SoFCSelectionRoot::handleEvent (SoHandleEventAction * action) override
Definition at line 1513 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, BEGIN_ACTION, and END_ACTION.
hasColorOverride()
bool Gui::SoFCSelectionRoot::hasColorOverride () const inline
Definition at line 305 of file SoFCUnifiedSelection.h.
initClass()
void SoFCSelectionRoot::initClass () static
Definition at line 1119 of file SoFCUnifiedSelection.cpp.
References so_bbox_construct_data(), so_bbox_destruct_data(), and so_bbox_storage.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
moveActionStack()
void SoFCSelectionRoot::moveActionStack (SoAction * from, SoAction * to, bool erase) static
Definition at line 1463 of file SoFCUnifiedSelection.cpp.
References ActionStacks.
Referenced by Gui::SoFCPathAnnotation::getBoundingBox().
pick()
void SoFCSelectionRoot::pick (SoPickAction * action) override
Definition at line 1499 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, BEGIN_ACTION, doActionPrivate(), and END_ACTION.
rayPick()
void SoFCSelectionRoot::rayPick (SoRayPickAction * action) override
Definition at line 1506 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, BEGIN_ACTION, doActionPrivate(), and END_ACTION.
removeActionContext()
static bool Gui::SoFCSelectionRoot::removeActionContext (SoAction * action, SoNode * node) inline static
Definition at line 283 of file SoFCUnifiedSelection.h.
References Path.Post.scripts.dynapath_4060_post::action.
Referenced by PartGui::SoBrepEdgeSet::doAction(), PartGui::SoBrepPointSet::doAction(), PartGui::SoBrepFaceSet::doAction(), and doActionPrivate().
removeColorOverride()
void Gui::SoFCSelectionRoot::removeColorOverride () inline
Definition at line 315 of file SoFCUnifiedSelection.h.
renderBBox()
bool SoFCSelectionRoot::renderBBox (SoGLRenderAction * action, SoNode * node, SbColor color) static
Definition at line 1241 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, SCL.SimpleDataTypes::f, MeshCore::MeshIO::OVERALL, so_bbox_storage, MovieTool::x, and MovieTool::y.
Referenced by _renderPrivate(), and Gui::SoFCPathAnnotation::GLRenderBelowPath().
renderPrivate()
void SoFCSelectionRoot::renderPrivate (SoGLRenderAction * action, bool inPath) protected
Definition at line 1292 of file SoFCUnifiedSelection.cpp.
References _CyclicLastReported, _renderPrivate(), Path.Post.scripts.dynapath_4060_post::action, FC_ERR, Gui::ViewParams::instance(), Gui::SoFCSelectionRoot::Stack::nodeSet, SelStack, and InitGui::t.
Referenced by GLRenderBelowPath(), and GLRenderInPath().
resetContext()
void SoFCSelectionRoot::resetContext ()
Definition at line 1459 of file SoFCUnifiedSelection.cpp.
References contextMap.
Referenced by doActionPrivate().
search()
void SoFCSelectionRoot::search (SoSearchAction * action) override
Definition at line 1519 of file SoFCUnifiedSelection.cpp.
References Path.Post.scripts.dynapath_4060_post::action, BEGIN_ACTION, and END_ACTION.
Referenced by importers.importIFClegacy.IfcDocument::find().
setColorOverride()
void Gui::SoFCSelectionRoot::setColorOverride (App::Color c) inline
Definition at line 309 of file SoFCUnifiedSelection.h.
References SCL.SimpleDataTypes::c.
Member Data Documentation
ActionStacks
std::unordered_map< SoAction *, SoFCSelectionRoot::Stack > SoFCSelectionRoot::ActionStacks static protected
Definition at line 346 of file SoFCUnifiedSelection.h.
Referenced by findActionContext(), and moveActionStack().
colorOverride
SbColor Gui::SoFCSelectionRoot::colorOverride protected
Definition at line 370 of file SoFCUnifiedSelection.h.
Referenced by _renderPrivate(), and checkColorOverride().
contextMap
ContextMap Gui::SoFCSelectionRoot::contextMap protected
Definition at line 352 of file SoFCUnifiedSelection.h.
Referenced by findActionContext(), and resetContext().
contextMap2
ContextMap Gui::SoFCSelectionRoot::contextMap2 protected
Definition at line 353 of file SoFCUnifiedSelection.h.
Referenced by findActionContext().
HlColorStack
SoFCSelectionRoot::ColorStack SoFCSelectionRoot::HlColorStack static protected
Definition at line 367 of file SoFCUnifiedSelection.h.
Referenced by _renderPrivate(), and checkSelection().
overrideColor
bool Gui::SoFCSelectionRoot::overrideColor = false protected
Definition at line 369 of file SoFCUnifiedSelection.h.
Referenced by _renderPrivate().
SelColorStack
SoFCSelectionRoot::ColorStack SoFCSelectionRoot::SelColorStack static protected
Definition at line 366 of file SoFCUnifiedSelection.h.
Referenced by _renderPrivate(), and checkSelection().
selectionStyle
SoSFEnum Gui::SoFCSelectionRoot::selectionStyle
Definition at line 322 of file SoFCUnifiedSelection.h.
Referenced by _renderPrivate(), SoFCSelectionRoot(), and Gui::View3DInventorSelection::View3DInventorSelection().
SelStack
SoFCSelectionRoot::Stack SoFCSelectionRoot::SelStack static protected
Definition at line 345 of file SoFCUnifiedSelection.h.
Referenced by _renderPrivate(), getCurrentRoot(), and renderPrivate().
ShapeColorNode
SoFCSelectionRoot * SoFCSelectionRoot::ShapeColorNode static protected
Definition at line 368 of file SoFCUnifiedSelection.h.
Referenced by _renderPrivate(), and checkColorOverride().
shapeColorPacker
SoColorPacker Gui::SoFCSelectionRoot::shapeColorPacker protected
Definition at line 372 of file SoFCUnifiedSelection.h.
Referenced by _renderPrivate(), and checkColorOverride().
transOverride
float Gui::SoFCSelectionRoot::transOverride = 0.0f protected
Definition at line 371 of file SoFCUnifiedSelection.h.
Referenced by _renderPrivate(), and checkColorOverride().
The documentation for this class was generated from the following files:
SoFCUnifiedSelection.h
SoFCUnifiedSelection.cpp