FreeCAD: Path.Post.scripts.centroid_post Namespace Reference
Path.Post.scripts.centroid_post Namespace Reference
Functions
def processArguments (argstring)
def export (objectslist, filename, argstring)
def linenumber ()
def parse (pathobj)
Variables
TOOLTIP
TOOLTIP_ARGS
OUTPUT_COMMENTS
OUTPUT_HEADER
OUTPUT_LINE_NUMBERS
SHOW_EDITOR
MODAL
USE_TLO
COMMAND_SPACE
LINENR
UNITS
UNIT_FORMAT
UNIT_SPEED_FORMAT
MACHINE_NAME
CORNER_MIN
CORNER_MAX
AXIS_PRECISION
FEED_PRECISION
SPINDLE_DECIMALS
COMMENT
cam_file
HEADER
PREAMBLE
POSTAMBLE
TOOLRETURN
ZAXISRETURN
SAFETYBLOCK
PRE_OPERATION
POST_OPERATION
TOOL_CHANGE
Function Documentation
export()
def Path.Post.scripts.centroid_post.export (objectslist, filename, argstring)
Definition at line 171 of file centroid_post.py.
References Path.Post.scripts.centroid_post.linenumber(), Path.Post.scripts.centroid_post.parse(), and Path.Post.scripts.centroid_post.processArguments().
linenumber()
def Path.Post.scripts.centroid_post.linenumber ()
Definition at line 248 of file centroid_post.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.centroid_post.export(), and Path.Post.scripts.centroid_post.parse().
parse()
def Path.Post.scripts.centroid_post.parse (pathobj)
Definition at line 256 of file centroid_post.py.
References Path.Post.scripts.centroid_post.linenumber(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.centroid_post.export().
processArguments()
def Path.Post.scripts.centroid_post.processArguments (argstring)
Definition at line 130 of file centroid_post.py.
Referenced by Path.Post.scripts.centroid_post.export().
Variable Documentation
AXIS_PRECISION
Path.Post.scripts.centroid_post.AXIS_PRECISION
Definition at line 79 of file centroid_post.py.
cam_file
Path.Post.scripts.centroid_post.cam_file
Definition at line 88 of file centroid_post.py.
COMMAND_SPACE
Path.Post.scripts.centroid_post.COMMAND_SPACE
Definition at line 69 of file centroid_post.py.
COMMENT
Path.Post.scripts.centroid_post.COMMENT
Definition at line 83 of file centroid_post.py.
CORNER_MAX
Path.Post.scripts.centroid_post.CORNER_MAX
Definition at line 78 of file centroid_post.py.
CORNER_MIN
Path.Post.scripts.centroid_post.CORNER_MIN
Definition at line 77 of file centroid_post.py.
FEED_PRECISION
Path.Post.scripts.centroid_post.FEED_PRECISION
Definition at line 80 of file centroid_post.py.
HEADER
Path.Post.scripts.centroid_post.HEADER
Definition at line 92 of file centroid_post.py.
LINENR
Path.Post.scripts.centroid_post.LINENR
Definition at line 70 of file centroid_post.py.
MACHINE_NAME
Path.Post.scripts.centroid_post.MACHINE_NAME
Definition at line 76 of file centroid_post.py.
MODAL
Path.Post.scripts.centroid_post.MODAL
Definition at line 66 of file centroid_post.py.
OUTPUT_COMMENTS
Path.Post.scripts.centroid_post.OUTPUT_COMMENTS
Definition at line 59 of file centroid_post.py.
OUTPUT_HEADER
Path.Post.scripts.centroid_post.OUTPUT_HEADER
Definition at line 60 of file centroid_post.py.
OUTPUT_LINE_NUMBERS
Path.Post.scripts.centroid_post.OUTPUT_LINE_NUMBERS
Definition at line 61 of file centroid_post.py.
POST_OPERATION
Path.Post.scripts.centroid_post.POST_OPERATION
Definition at line 124 of file centroid_post.py.
POSTAMBLE
Path.Post.scripts.centroid_post.POSTAMBLE
Definition at line 105 of file centroid_post.py.
PRE_OPERATION
Path.Post.scripts.centroid_post.PRE_OPERATION
Definition at line 121 of file centroid_post.py.
PREAMBLE
Path.Post.scripts.centroid_post.PREAMBLE
Definition at line 101 of file centroid_post.py.
SAFETYBLOCK
Path.Post.scripts.centroid_post.SAFETYBLOCK
Definition at line 117 of file centroid_post.py.
SHOW_EDITOR
Path.Post.scripts.centroid_post.SHOW_EDITOR
Definition at line 63 of file centroid_post.py.
SPINDLE_DECIMALS
Path.Post.scripts.centroid_post.SPINDLE_DECIMALS
Definition at line 81 of file centroid_post.py.
TOOL_CHANGE
Path.Post.scripts.centroid_post.TOOL_CHANGE
Definition at line 127 of file centroid_post.py.
TOOLRETURN
Path.Post.scripts.centroid_post.TOOLRETURN
Definition at line 108 of file centroid_post.py.
TOOLTIP
Path.Post.scripts.centroid_post.TOOLTIP
Definition at line 35 of file centroid_post.py.
TOOLTIP_ARGS
Path.Post.scripts.centroid_post.TOOLTIP_ARGS
Definition at line 46 of file centroid_post.py.
UNIT_FORMAT
Path.Post.scripts.centroid_post.UNIT_FORMAT
Definition at line 74 of file centroid_post.py.
UNIT_SPEED_FORMAT
Path.Post.scripts.centroid_post.UNIT_SPEED_FORMAT
Definition at line 75 of file centroid_post.py.
UNITS
Path.Post.scripts.centroid_post.UNITS
Definition at line 73 of file centroid_post.py.
USE_TLO
Path.Post.scripts.centroid_post.USE_TLO
Definition at line 67 of file centroid_post.py.
ZAXISRETURN
Path.Post.scripts.centroid_post.ZAXISRETURN
Definition at line 113 of file centroid_post.py.