FreeCAD: Wm4::Polynomial1< Real > Class Template Reference
Wm4::Polynomial1< Real > Class Template Reference
#include <Wm4Polynomial1.h>
Public Member Functions
Polynomial1 (int iDegree=-1)
Polynomial1 (const Polynomial1 &rkPoly)
~Polynomial1 ()
void SetDegree (int iDegree)
int GetDegree () const
operator const Real * () const
operator Real * ()
Real operator[] (int i) const
Real & operator[] (int i)
Polynomial1 & operator= (const Polynomial1 &rkPoly)
Real operator() (Real fT) const
Polynomial1 operator+ (const Polynomial1 &rkPoly) const
Polynomial1 operator- (const Polynomial1 &rkPoly) const
Polynomial1 operator* (const Polynomial1 &rkPoly) const
Polynomial1 operator+ (Real fScalar) const
Polynomial1 operator- (Real fScalar) const
Polynomial1 operator* (Real fScalar) const
Polynomial1 operator/ (Real fScalar) const
Polynomial1 operator- () const
Polynomial1 & operator+= (const Polynomial1 &rkPoly)
Polynomial1 & operator-= (const Polynomial1 &rkPoly)
Polynomial1 & operator*= (const Polynomial1 &rkPoly)
Polynomial1 & operator+= (Real fScalar)
Polynomial1 & operator-= (Real fScalar)
Polynomial1 & operator*= (Real fScalar)
Polynomial1 & operator/= (Real fScalar)
Polynomial1 GetDerivative () const
Polynomial1 GetInversion () const
void Compress (Real fEpsilon)
void Divide (const Polynomial1 &rkDiv, Polynomial1 &rkQuot, Polynomial1 &rkRem, Real fEpsilon) const
Protected Attributes
int m_iDegree
Real * m_afCoeff
Detailed Description
template<class Real>
class Wm4::Polynomial1< Real >
Definition at line 27 of file Wm4Polynomial1.h.
Constructor & Destructor Documentation
Polynomial1() [1/2]
template<class Real > Wm4::Polynomial1< Real >::Polynomial1 (int iDegree = -1)
Polynomial1() [2/2]
template<class Real > Wm4::Polynomial1< Real >::Polynomial1 (const Polynomial1< Real > & rkPoly)
~Polynomial1()
template<class Real > Wm4::Polynomial1< Real >::~Polynomial1 ()
Member Function Documentation
Compress()
template<class Real > void Wm4::Polynomial1< Real >::Compress (Real fEpsilon)
Referenced by Wm4::PolynomialRoots< Real >::GetBound().
Divide()
template<class Real > void Wm4::Polynomial1< Real >::Divide (const Polynomial1< Real > & rkDiv, Polynomial1< Real > & rkQuot, Polynomial1< Real > & rkRem, Real fEpsilon) const
Referenced by Wm4::PolynomialRoots< Real >::GetRootCount().
GetDegree()
template<class Real > int Wm4::Polynomial1< Real >::GetDegree () const
Referenced by Wm4::PolynomialRoots< Real >::AllRealPartsNegative(), Wm4::PolynomialRoots< Real >::AllRealPartsPositive(), Wm4::PolynomialRoots< Real >::FindB(), Wm4::PolynomialRoots< Real >::GetBound(), and Wm4::PolynomialRoots< Real >::GetRootCount().
GetDerivative()
template<class Real > Polynomial1 Wm4::Polynomial1< Real >::GetDerivative () const
Referenced by Wm4::PolynomialRoots< Real >::FindB(), and Wm4::PolynomialRoots< Real >::GetRootCount().
GetInversion()
template<class Real > Polynomial1 Wm4::Polynomial1< Real >::GetInversion () const
operator const Real *()
template<class Real > Wm4::Polynomial1< Real >::operator const Real * () const
operator Real *()
template<class Real > Wm4::Polynomial1< Real >::operator Real * ()
operator()()
template<class Real > Real Wm4::Polynomial1< Real >::operator() (Real fT) const
operator*() [1/2]
template<class Real > Polynomial1 Wm4::Polynomial1< Real >::operator* (const Polynomial1< Real > & rkPoly) const
operator*() [2/2]
template<class Real > Polynomial1 Wm4::Polynomial1< Real >::operator* (Real fScalar) const
operator*=() [1/2]
template<class Real > Polynomial1& Wm4::Polynomial1< Real >::operator*= (const Polynomial1< Real > & rkPoly)
operator*=() [2/2]
template<class Real > Polynomial1& Wm4::Polynomial1< Real >::operator*= (Real fScalar)
operator+() [1/2]
template<class Real > Polynomial1 Wm4::Polynomial1< Real >::operator+ (const Polynomial1< Real > & rkPoly) const
operator+() [2/2]
template<class Real > Polynomial1 Wm4::Polynomial1< Real >::operator+ (Real fScalar) const
operator+=() [1/2]
template<class Real > Polynomial1& Wm4::Polynomial1< Real >::operator+= (const Polynomial1< Real > & rkPoly)
operator+=() [2/2]
template<class Real > Polynomial1& Wm4::Polynomial1< Real >::operator+= (Real fScalar)
operator-() [1/3]
template<class Real > Polynomial1 Wm4::Polynomial1< Real >::operator- () const
operator-() [2/3]
template<class Real > Polynomial1 Wm4::Polynomial1< Real >::operator- (const Polynomial1< Real > & rkPoly) const
operator-() [3/3]
template<class Real > Polynomial1 Wm4::Polynomial1< Real >::operator- (Real fScalar) const
operator-=() [1/2]
template<class Real > Polynomial1& Wm4::Polynomial1< Real >::operator-= (const Polynomial1< Real > & rkPoly)
operator-=() [2/2]
template<class Real > Polynomial1& Wm4::Polynomial1< Real >::operator-= (Real fScalar)
operator/()
template<class Real > Polynomial1 Wm4::Polynomial1< Real >::operator/ (Real fScalar) const
operator/=()
template<class Real > Polynomial1& Wm4::Polynomial1< Real >::operator/= (Real fScalar)
operator=()
template<class Real > Polynomial1& Wm4::Polynomial1< Real >::operator= (const Polynomial1< Real > & rkPoly)
operator[]() [1/2]
template<class Real > Real& Wm4::Polynomial1< Real >::operator[] (int i)
operator[]() [2/2]
template<class Real > Real Wm4::Polynomial1< Real >::operator[] (int i) const
SetDegree()
template<class Real > void Wm4::Polynomial1< Real >::SetDegree (int iDegree)
Member Data Documentation
m_afCoeff
template<class Real > Real* Wm4::Polynomial1< Real >::m_afCoeff protected
Definition at line 91 of file Wm4Polynomial1.h.
m_iDegree
template<class Real > int Wm4::Polynomial1< Real >::m_iDegree protected
Definition at line 90 of file Wm4Polynomial1.h.
The documentation for this class was generated from the following file:
Wm4Polynomial1.h