FreeCAD: TechDrawGui::TechDrawHandler Class Reference
TechDrawGui::TechDrawHandler Class Reference abstract
#include <TechDrawHandler.h>
Public Member Functions
TechDrawHandler ()
virtual ~TechDrawHandler ()
void activate (QGVPage *vPage)
void deactivate () override
void quit () override
virtual void mouseMoveEvent (QMouseEvent *event)=0
virtual void mousePressEvent (QMouseEvent *event)
virtual void mouseReleaseEvent (QMouseEvent *event)
virtual void keyPressEvent (QKeyEvent *event)=0
virtual void keyReleaseEvent (QKeyEvent *event)
TechDraw::DrawPage * getPage ()
Public Member Functions inherited from Gui::ToolHandler
ToolHandler ()=default
virtual ~ToolHandler ()=default
bool activate ()
void updateCursor ()
Protected Member Functions
QWidget * getCursorWidget () override
void setWidgetCursor (QCursor cursor) override
Protected Member Functions inherited from Gui::ToolHandler
virtual QString getCrosshairCursorSVGName () const
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
void unsetCursor ()
void applyCursor ()
restitutes the DSH cached cursor (without any tail due to autoconstraints, ...)
void addCursorTail (std::vector< QPixmap > &pixmaps)
unsigned long getCrosshairColor ()
returns the color to be used for the crosshair (configurable as a parameter)
qreal devicePixelRatio ()
functions to set the cursor to a given svgName (to be migrated to NVI style)
View3DInventorViewer * getViewer ()
Protected Attributes
QGVPage * viewPage
Protected Attributes inherited from Gui::ToolHandler
QCursor oldCursor
QCursor actCursor
QPixmap actCursorPixmap
Detailed Description
Definition at line 54 of file TechDrawHandler.h.
Constructor & Destructor Documentation
TechDrawHandler()
TechDrawHandler::TechDrawHandler ()
Definition at line 53 of file TechDrawHandler.cpp.
~TechDrawHandler()
TechDrawHandler::~TechDrawHandler () virtual
Definition at line 56 of file TechDrawHandler.cpp.
Member Function Documentation
activate()
void TechDrawHandler::activate (QGVPage * vPage)
Definition at line 59 of file TechDrawHandler.cpp.
References Gui::ToolHandler::activate(), Gui::MainWindow::activeWindow(), TechDrawGui::QGVPage::deactivateHandler(), TechDrawGui::MDIViewPage::enableContextualMenu(), Gui::getMainWindow(), and viewPage.
deactivate()
void TechDrawHandler::deactivate () override virtual
Reimplemented from Gui::ToolHandler.
Definition at line 74 of file TechDrawHandler.cpp.
References Gui::MainWindow::activeWindow(), Gui::ToolHandler::deactivate(), TechDrawGui::MDIViewPage::enableContextualMenu(), and Gui::getMainWindow().
getCursorWidget()
QWidget * TechDrawHandler::getCursorWidget () override protected virtual
Reimplemented from Gui::ToolHandler.
Definition at line 115 of file TechDrawHandler.cpp.
References viewPage.
getPage()
TechDraw::DrawPage * TechDrawHandler::getPage ()
Definition at line 128 of file TechDrawHandler.cpp.
References TechDrawGui::QGVPage::getDrawPage(), and viewPage.
keyPressEvent()
virtual void TechDrawGui::TechDrawHandler::keyPressEvent (QKeyEvent * event) pure virtual
Implemented in TDHandlerDimension.
keyReleaseEvent()
void TechDrawHandler::keyReleaseEvent (QKeyEvent * event) virtual
Reimplemented in TDHandlerDimension.
Definition at line 90 of file TechDrawHandler.cpp.
References quit().
Referenced by TDHandlerDimension::keyReleaseEvent().
mouseMoveEvent()
virtual void TechDrawGui::TechDrawHandler::mouseMoveEvent (QMouseEvent * event) pure virtual
Implemented in TDHandlerDimension.
mousePressEvent()
virtual void TechDrawGui::TechDrawHandler::mousePressEvent (QMouseEvent * event) inline virtual
Definition at line 67 of file TechDrawHandler.h.
mouseReleaseEvent()
void TechDrawHandler::mouseReleaseEvent (QMouseEvent * event) virtual
Reimplemented in TDHandlerDimension.
Definition at line 100 of file TechDrawHandler.cpp.
References quit().
Referenced by TDHandlerDimension::mouseReleaseEvent().
quit()
void TechDrawHandler::quit () override virtual
Reimplemented from Gui::ToolHandler.
Definition at line 110 of file TechDrawHandler.cpp.
References TechDrawGui::QGVPage::deactivateHandler(), and viewPage.
Referenced by keyReleaseEvent(), and mouseReleaseEvent().
setWidgetCursor()
void TechDrawHandler::setWidgetCursor (QCursor cursor) override protected virtual
Reimplemented from Gui::ToolHandler.
Definition at line 120 of file TechDrawHandler.cpp.
References viewPage.
Member Data Documentation
viewPage
QGVPage* TechDrawGui::TechDrawHandler::viewPage protected
Definition at line 80 of file TechDrawHandler.h.
Referenced by activate(), getCursorWidget(), getPage(), quit(), and setWidgetCursor().
The documentation for this class was generated from the following files:
TechDrawHandler.h
TechDrawHandler.cpp