FreeCAD: GCS::ConstraintCurveValue Class Reference
GCS::ConstraintCurveValue Class Reference
#include <Constraints.h>
Public Member Functions
ConstraintCurveValue (Point &p, double *pcoord, Curve &crv, double *u)
ConstraintCurveValue: solver constraint that ties parameter value with point coordinates, according to curve's parametric equation.
~ConstraintCurveValue () override
ConstraintType getTypeId () override
void rescale (double coef=1.) override
double error () override
double grad (double *) override
double maxStep (MAP_pD_D &dir, double lim=1.) override
Public Member Functions inherited from GCS::Constraint
Constraint ()
virtual ~Constraint ()
VEC_pD params ()
void redirectParams (const MAP_pD_pD &redirectionmap)
void revertParams ()
void setTag (int tagId)
int getTag ()
void setDriving (bool isdriving)
bool isDriving () const
void setInternalAlignment (Alignment isinternalalignment)
Alignment isInternalAlignment () const
int findParamInPvec (double *param)
Additional Inherited Members
Public Types inherited from GCS::Constraint
enum Alignment { Alignment::NoInternalAlignment, Alignment::InternalAlignment }
Protected Attributes inherited from GCS::Constraint
VEC_pD origpvec
VEC_pD pvec
double scale
int tag
bool pvecChangedFlag
bool driving
Alignment internalAlignment
Detailed Description
Definition at line 991 of file Constraints.h.
Constructor & Destructor Documentation
ConstraintCurveValue()
GCS::ConstraintCurveValue::ConstraintCurveValue (Point & p, double * pcoord, Curve & crv, double * u)
ConstraintCurveValue: solver constraint that ties parameter value with point coordinates, according to curve's parametric equation.
Parameters
p : endpoint to be constrained
pcoord : pointer to point coordinate to be constrained. Must be either p.x or p.y
crv : the curve (crv->Value() must be functional)
u : pointer to u parameter corresponding to the point
Definition at line 2226 of file Constraints.cpp.
References GCS::Curve::Copy(), GCS::Constraint::origpvec, GCS::Curve::PushOwnParams(), GCS::Constraint::pvec, GCS::Constraint::pvecChangedFlag, and rescale().
~ConstraintCurveValue()
GCS::ConstraintCurveValue::~ConstraintCurveValue () override
Definition at line 2239 of file Constraints.cpp.
Member Function Documentation
error()
double GCS::ConstraintCurveValue::error () override virtual
Reimplemented from GCS::Constraint.
Definition at line 2306 of file Constraints.cpp.
getTypeId()
ConstraintType GCS::ConstraintCurveValue::getTypeId () override virtual
Reimplemented from GCS::Constraint.
Definition at line 2258 of file Constraints.cpp.
References GCS::CurveValue.
grad()
double GCS::ConstraintCurveValue::grad (double * param) override virtual
Reimplemented from GCS::Constraint.
Definition at line 2313 of file Constraints.cpp.
References GCS::Constraint::findParamInPvec(), Init::param, and GCS::Constraint::scale.
maxStep()
double GCS::ConstraintCurveValue::maxStep (MAP_pD_D & dir, double lim = 1.) override virtual
Reimplemented from GCS::Constraint.
Definition at line 2326 of file Constraints.cpp.
rescale()
void GCS::ConstraintCurveValue::rescale (double coef = 1.) override virtual
Reimplemented from GCS::Constraint.
Definition at line 2263 of file Constraints.cpp.
Referenced by ConstraintCurveValue().
The documentation for this class was generated from the following files:
Constraints.h
Constraints.cpp