FreeCAD: ifc2x3.ifcconnectionpointeccentricity Class Reference
ifc2x3.ifcconnectionpointeccentricity Class Reference
Public Member Functions
def __init__ (self, inherited0__pointonrelatingelement, inherited1__pointonrelatedelement, eccentricityinx, eccentricityiny, eccentricityinz)
def eccentricityinx ()
def eccentricityiny ()
def eccentricityinz ()
Public Member Functions inherited from ifc2x3.ifcconnectionpointgeometry
def __init__ (self, pointonrelatingelement, pointonrelatedelement)
def pointonrelatingelement ()
def pointonrelatedelement ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
eccentricityinx
eccentricityiny
eccentricityinz
Public Attributes inherited from ifc2x3.ifcconnectionpointgeometry
pointonrelatingelement
pointonrelatedelement
Detailed Description
Entity ifcconnectionpointeccentricity definition.
:param eccentricityinx
:type eccentricityinx:ifclengthmeasure
:param eccentricityiny
:type eccentricityiny:ifclengthmeasure
:param eccentricityinz
:type eccentricityinz:ifclengthmeasure
Definition at line 32759 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcconnectionpointeccentricity.__init__ (self, inherited0__pointonrelatingelement, inherited1__pointonrelatedelement, eccentricityinx, eccentricityiny, eccentricityinz)
Definition at line 32771 of file ifc2x3.py.
Member Function Documentation
eccentricityinx()
def ifc2x3.ifcconnectionpointeccentricity.eccentricityinx ()
Definition at line 32778 of file ifc2x3.py.
References ifc2x3.ifcconnectionpointeccentricity._eccentricityinx, SCL.TypeChecker.check_type(), and ifc2x3.ifcconnectionpointeccentricity.eccentricityinx.
eccentricityiny()
def ifc2x3.ifcconnectionpointeccentricity.eccentricityiny ()
Definition at line 32792 of file ifc2x3.py.
References ifc2x3.ifcconnectionpointeccentricity._eccentricityiny, SCL.TypeChecker.check_type(), and ifc2x3.ifcconnectionpointeccentricity.eccentricityiny.
eccentricityinz()
def ifc2x3.ifcconnectionpointeccentricity.eccentricityinz ()
Definition at line 32806 of file ifc2x3.py.
References ifc2x3.ifcconnectionpointeccentricity._eccentricityinz, SCL.TypeChecker.check_type(), and ifc2x3.ifcconnectionpointeccentricity.eccentricityinz.
Member Data Documentation
eccentricityinx
ifc2x3.ifcconnectionpointeccentricity.eccentricityinx
Definition at line 32773 of file ifc2x3.py.
Referenced by ifc2x3.ifcconnectionpointeccentricity.eccentricityinx().
eccentricityiny
ifc2x3.ifcconnectionpointeccentricity.eccentricityiny
Definition at line 32774 of file ifc2x3.py.
Referenced by ifc2x3.ifcconnectionpointeccentricity.eccentricityiny().
eccentricityinz
ifc2x3.ifcconnectionpointeccentricity.eccentricityinz
Definition at line 32775 of file ifc2x3.py.
Referenced by ifc2x3.ifcconnectionpointeccentricity.eccentricityinz().
The documentation for this class was generated from the following file:
ifc2x3.py