FreeCAD: App::NumberExpression Class Reference
App::NumberExpression Class Reference
#include <ExpressionParser.h>
Public Member Functions
NumberExpression (const App::DocumentObject *_owner=nullptr, const Base::Quantity &quantity=Base::Quantity())
Expression * simplify () const override
void negate ()
bool isInteger (long *v=nullptr) const
Public Member Functions inherited from App::UnitExpression
UnitExpression (const App::DocumentObject *_owner=nullptr, const Base::Quantity &_quantity=Base::Quantity(), const std::string &_unitStr=std::string())
~UnitExpression () override
void setUnit (const Base::Quantity &_quantity)
void setQuantity (const Base::Quantity &_quantity)
double getValue () const
const Base::Unit & getUnit () const
const Base::Quantity & getQuantity () const
const std::string getUnitString () const
double getScaler () const
Public Member Functions inherited from App::Expression
Expression (const App::DocumentObject *_owner)
~Expression () override
virtual bool isTouched () const
Expression * eval () const
std::string toString (bool persistent=false, bool checkPriority=false, int indent=0) const
void toString (std::ostream &os, bool persistent=false, bool checkPriority=false, int indent=0) const
Expression * copy () const
virtual int priority () const
void getIdentifiers (std::map< App::ObjectIdentifier, bool > &) const
std::map< App::ObjectIdentifier, bool > getIdentifiers () const
void getDeps (ExpressionDeps &deps, int option=DepNormal) const
ExpressionDeps getDeps (int option=DepNormal) const
std::map< App::DocumentObject *, bool > getDepObjects (std::vector< std::string > *labels=nullptr) const
void getDepObjects (std::map< App::DocumentObject *, bool > &, std::vector< std::string > *labels=nullptr) const
ExpressionPtr importSubNames (const std::map< std::string, std::string > &nameMap) const
ExpressionPtr updateLabelReference (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const
ExpressionPtr replaceObject (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const
bool adjustLinks (const std::set< App::DocumentObject * > &inList)
void visit (ExpressionVisitor &v)
App::DocumentObject * getOwner () const
virtual void addComponent (Component *component)
bool hasComponent () const
boost::any getValueAsAny () const
Py::Object getPyValue () const
bool isSame (const Expression &other, bool checkComment=true) const
Component (const std::string &n)
Component (Expression *e1, Expression *e2, Expression *e3, bool isRange=false)
Component (const ObjectIdentifier::Component &comp)
Component (const Component &other)
~Component ()
Component & operator= (const Component &)=delete
void visit (ExpressionVisitor &v)
bool isTouched () const
void toString (std::ostream &ss, bool persistent) const
Component * copy () const
Component * eval () const
Py::Object get (const Expression *owner, const Py::Object &pyobj) const
void set (const Expression *owner, Py::Object &pyobj, const Py::Object &value) const
void del (const Expression *owner, Py::Object &pyobj) const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
Expression * _copy () const override
void _toString (std::ostream &ss, bool persistent, int indent) const override
Protected Member Functions inherited from App::UnitExpression
Py::Object _getPyValue () const override
Protected Member Functions inherited from App::Expression
virtual bool _isIndexable () const
virtual void _getIdentifiers (std::map< App::ObjectIdentifier, bool > &) const
virtual bool _adjustLinks (const std::set< App::DocumentObject * > &, ExpressionVisitor &)
virtual bool _updateElementReference (App::DocumentObject *, bool, ExpressionVisitor &)
virtual bool _relabeledDocument (const std::string &, const std::string &, ExpressionVisitor &)
virtual void _importSubNames (const ObjectIdentifier::SubNameMap &)
virtual void _updateLabelReference (App::DocumentObject *, const std::string &, const char *)
virtual bool _renameObjectIdentifier (const std::map< ObjectIdentifier, ObjectIdentifier > &, const ObjectIdentifier &, ExpressionVisitor &)
virtual void _collectReplacement (std::map< ObjectIdentifier, ObjectIdentifier > &, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const
virtual void _moveCells (const CellAddress &, int, int, ExpressionVisitor &)
virtual void _offsetCells (int, int, ExpressionVisitor &)
virtual void _visit (ExpressionVisitor &)
Additional Inherited Members
Public Types inherited from App::Expression
enum DepOption { DepNormal, DepHidden, DepAll }
using ComponentList = std::vector< Component * >
Static Public Member Functions inherited from App::Expression
static Expression * parse (const App::DocumentObject *owner, const std::string &buffer)
static Component * createComponent (const std::string &n)
static Component * createComponent (Expression *e1, Expression *e2=nullptr, Expression *e3=nullptr, bool isRange=false)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::Expression
std::string comment
ObjectIdentifier::Component comp
Expression * e1
Expression * e2
Expression * e3
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::UnitExpression
PyObject * cache = nullptr
Protected Attributes inherited from App::Expression
App::DocumentObject * owner
ComponentList components
Detailed Description
Class implementing a number with an optional unit
Definition at line 155 of file ExpressionParser.h.
Constructor & Destructor Documentation
NumberExpression()
NumberExpression::NumberExpression (const App::DocumentObject * _owner = nullptr, const Base::Quantity & quantity = Base::Quantity()) explicit
Definition at line 1280 of file Expression.cpp.
Referenced by _copy().
Member Function Documentation
_copy()
Expression * NumberExpression::_copy () const override protected virtual
Create and return a copy of the expression.
Reimplemented from App::UnitExpression.
Reimplemented in App::ConstantExpression.
Definition at line 1299 of file Expression.cpp.
References App::UnitExpression::getQuantity(), NumberExpression(), and App::Expression::owner.
_toString()
void NumberExpression::_toString (std::ostream & ss, bool persistent, int indent) const override protected virtual
Return a string representation, in this case the unit string. Return a string representation of the expression.
Reimplemented from App::UnitExpression.
Reimplemented in App::ConstantExpression.
Definition at line 1313 of file Expression.cpp.
References App::UnitExpression::getValue().
isInteger()
bool NumberExpression::isInteger (long * v = nullptr) const
Definition at line 1330 of file Expression.cpp.
References essentiallyInteger(), App::UnitExpression::getValue(), and RobotExample::l.
negate()
void NumberExpression::negate ()
Negate the stored value.
Definition at line 1308 of file Expression.cpp.
References App::UnitExpression::getQuantity(), and App::UnitExpression::setQuantity().
simplify()
Expression * NumberExpression::simplify () const override virtual
Simplify the expression. For NumberExpressions, we return a copy(), as it cannot be simplified any more.
Reimplemented from App::UnitExpression.
Definition at line 1290 of file Expression.cpp.
References App::Expression::copy().
The documentation for this class was generated from the following files:
ExpressionParser.h
Expression.cpp