FreeCAD: Gui::Dialog::DlgSettingsDocumentImp Class Reference
Gui::Dialog::DlgSettingsDocumentImp Class Reference
#include <DlgSettingsDocumentImp.h>
Public Member Functions
DlgSettingsDocumentImp (QWidget *parent=nullptr)
~DlgSettingsDocumentImp () override
void saveSettings () override
void loadSettings () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Slots
void onLicenseTypeChanged (int index)
Protected Member Functions
void changeEvent (QEvent *e) override
void addLicenseTypes ()
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
The DlgSettingsDocumentImp class implements a preference page to change settings for the document.
Author
Jürgen Riegel
Definition at line 79 of file DlgSettingsDocumentImp.h.
Constructor & Destructor Documentation
DlgSettingsDocumentImp()
DlgSettingsDocumentImp::DlgSettingsDocumentImp (QWidget * parent = nullptr) explicit
Constructs a DlgSettingsDocumentImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'
Definition at line 41 of file DlgSettingsDocumentImp.cpp.
References addLicenseTypes(), draftgeoutils.intersections::connect(), and onLicenseTypeChanged().
~DlgSettingsDocumentImp()
DlgSettingsDocumentImp::~DlgSettingsDocumentImp () override default
Destroys the object and frees any allocated resources
Member Function Documentation
addLicenseTypes()
void DlgSettingsDocumentImp::addLicenseTypes () protected
Definition at line 148 of file DlgSettingsDocumentImp.cpp.
References App::licenseItems, App::posnOfFullName, and src.Mod.AddonManager.Addon::translate.
Referenced by changeEvent(), and DlgSettingsDocumentImp().
changeEvent()
void DlgSettingsDocumentImp::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 135 of file DlgSettingsDocumentImp.cpp.
References addLicenseTypes(), and SCL.SimpleDataTypes::e.
loadSettings()
void DlgSettingsDocumentImp::loadSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 103 of file DlgSettingsDocumentImp.cpp.
onLicenseTypeChanged
void DlgSettingsDocumentImp::onLicenseTypeChanged (int index) protected slot
Fix Url according to changed type
Definition at line 165 of file DlgSettingsDocumentImp.cpp.
References App::countOfLicenses, App::licenseItems, and App::posnOfUrl.
Referenced by DlgSettingsDocumentImp().
saveSettings()
void DlgSettingsDocumentImp::saveSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 69 of file DlgSettingsDocumentImp.cpp.
References Gui::AutoSaver::instance(), and Gui::AutoSaver::setTimeout().
The documentation for this class was generated from the following files:
DlgSettingsDocumentImp.h
DlgSettingsDocumentImp.cpp