FreeCAD: TechDrawGui::CompassDialWidget Class Reference
TechDrawGui::CompassDialWidget Class Reference
#include <CompassDialWidget.h>
Public Slots
void slotChangeAngle (double angle)
void resetAngle ()
Public Member Functions
CompassDialWidget (QWidget *parent=nullptr)
~CompassDialWidget () override=default
QSize sizeHint () const override
QSize minimumSizeHint () const override
double angle () const
void setAngle (double newAngle)
void setSize (int newSize)
Protected Member Functions
void paintEvent (QPaintEvent *event) override
void drawWidget (QPainter &painter)
void drawNeedle (QPainter &painter)
void drawMarkings (QPainter &painter)
void drawBackground (QPainter &painter)
Detailed Description
Definition at line 54 of file CompassDialWidget.h.
Constructor & Destructor Documentation
CompassDialWidget()
CompassDialWidget::CompassDialWidget (QWidget * parent = nullptr)
Definition at line 40 of file CompassDialWidget.cpp.
~CompassDialWidget()
TechDrawGui::CompassDialWidget::~CompassDialWidget () override default
Member Function Documentation
angle()
double TechDrawGui::CompassDialWidget::angle () const inline
Definition at line 84 of file CompassDialWidget.h.
Referenced by Path.Base.Generator.dogboneII.Generator::generate().
drawBackground()
void CompassDialWidget::drawBackground (QPainter & painter) protected
Definition at line 92 of file CompassDialWidget.cpp.
References KDL::min().
Referenced by drawWidget().
drawMarkings()
void CompassDialWidget::drawMarkings (QPainter & painter) protected
Definition at line 121 of file CompassDialWidget.cpp.
References KDL::min().
Referenced by drawWidget().
drawNeedle()
void CompassDialWidget::drawNeedle (QPainter & painter) protected
Definition at line 170 of file CompassDialWidget.cpp.
References KDL::min().
Referenced by drawWidget().
drawWidget()
void CompassDialWidget::drawWidget (QPainter & painter) protected
Definition at line 78 of file CompassDialWidget.cpp.
References drawBackground(), drawMarkings(), and drawNeedle().
Referenced by paintEvent().
minimumSizeHint()
QSize CompassDialWidget::minimumSizeHint () const override
Definition at line 65 of file CompassDialWidget.cpp.
paintEvent()
void CompassDialWidget::paintEvent (QPaintEvent * event) override protected
Definition at line 70 of file CompassDialWidget.cpp.
References drawWidget().
resetAngle
void TechDrawGui::CompassDialWidget::resetAngle () inline slot
Definition at line 90 of file CompassDialWidget.h.
setAngle()
void CompassDialWidget::setAngle (double newAngle)
Definition at line 249 of file CompassDialWidget.cpp.
References Base::fmod().
Referenced by TechDrawGui::CompassWidget::setDialAngle(), and TechDrawGui::CompassWidget::slotSpinBoxEnter().
setSize()
void CompassDialWidget::setSize (int newSize)
Definition at line 255 of file CompassDialWidget.cpp.
Referenced by TechDrawGui::CompassWidget::CompassWidget().
sizeHint()
QSize CompassDialWidget::sizeHint () const override
Definition at line 60 of file CompassDialWidget.cpp.
slotChangeAngle
void TechDrawGui::CompassDialWidget::slotChangeAngle (double angle) inline slot
Definition at line 89 of file CompassDialWidget.h.
The documentation for this class was generated from the following files:
CompassDialWidget.h
CompassDialWidget.cpp