FreeCAD: Gui::NotificationLabel Class Reference
Gui::NotificationLabel Class Reference
Public Member Functions
NotificationLabel (const QString &text, const QPoint &pos, int displayTime, int minShowTime=0, int width=0)
void reuseNotification (const QString &text, int displayTime, const QPoint &pos, int width)
Reuse existing notification to show a new notification (with a new text)
void hideNotification ()
Hide notification after a hiding timer.
void updateSize (const QPoint &pos)
Update the size of the QLabel.
bool eventFilter (QObject *, QEvent *) override
Event filter.
bool notificationLabelChanged (const QString &text)
Return true if the text provided is the same as the one of an existing notification.
void placeNotificationLabel (const QPoint &pos)
Place the notification at the given position.
void setTipRect (const QRect &restrictionarea)
Set the windowrect defining an area to which the label should be constrained.
void setHideIfReferenceWidgetDeactivated (bool on)
Static Public Attributes
static qobject_delete_later_unique_ptr< NotificationLabel > instance = nullptr
The instance.
Protected Member Functions
void paintEvent (QPaintEvent *e) override
void resizeEvent (QResizeEvent *e) override
Detailed Description
Class showing the notification as a label
Definition at line 59 of file NotificationBox.cpp.
Constructor & Destructor Documentation
NotificationLabel()
Gui::NotificationLabel::NotificationLabel (const QString & text, const QPoint & pos, int displayTime, int minShowTime = 0, int width = 0)
Definition at line 106 of file NotificationBox.cpp.
References instance, Gui::NotificationBox::palette(), RobotExample::pos, and reuseNotification().
Member Function Documentation
eventFilter()
bool Gui::NotificationLabel::eventFilter (QObject * o, QEvent * e) override
Event filter.
Definition at line 234 of file NotificationBox.cpp.
References SCL.SimpleDataTypes::e, hideNotification(), and src.Mod.Test.testPathArray::o.
hideNotification()
void Gui::NotificationLabel::hideNotification ()
Hide notification after a hiding timer.
Definition at line 221 of file NotificationBox.cpp.
Referenced by eventFilter().
notificationLabelChanged()
bool Gui::NotificationLabel::notificationLabelChanged (const QString & text)
Return true if the text provided is the same as the one of an existing notification.
Definition at line 315 of file NotificationBox.cpp.
References instance.
paintEvent()
void Gui::NotificationLabel::paintEvent (QPaintEvent * e) override protected
Definition at line 197 of file NotificationBox.cpp.
References buildPsets::p.
placeNotificationLabel()
void Gui::NotificationLabel::placeNotificationLabel (const QPoint & pos)
Place the notification at the given position.
Definition at line 265 of file NotificationBox.cpp.
References Path.Post.scripts.opensbp_post::move(), buildPsets::p, and RobotExample::pos.
resizeEvent()
void Gui::NotificationLabel::resizeEvent (QResizeEvent * e) override protected
Definition at line 207 of file NotificationBox.cpp.
References SCL.SimpleDataTypes::e.
reuseNotification()
void Gui::NotificationLabel::reuseNotification (const QString & text, int displayTime, const QPoint & pos, int width)
Reuse existing notification to show a new notification (with a new text)
Definition at line 154 of file NotificationBox.cpp.
References RobotExample::pos, and updateSize().
Referenced by NotificationLabel().
setHideIfReferenceWidgetDeactivated()
void Gui::NotificationLabel::setHideIfReferenceWidgetDeactivated (bool on)
Definition at line 310 of file NotificationBox.cpp.
setTipRect()
void Gui::NotificationLabel::setTipRect (const QRect & restrictionarea)
Set the windowrect defining an area to which the label should be constrained.
Definition at line 305 of file NotificationBox.cpp.
updateSize()
void Gui::NotificationLabel::updateSize (const QPoint & pos)
Update the size of the QLabel.
Definition at line 165 of file NotificationBox.cpp.
References RobotExample::pos.
Referenced by reuseNotification().
Member Data Documentation
instance
qobject_delete_later_unique_ptr< NotificationLabel > Gui::NotificationLabel::instance = nullptr static
The instance.
Definition at line 83 of file NotificationBox.cpp.
Referenced by Gui::NotificationBox::isVisible(), NotificationLabel(), notificationLabelChanged(), Gui::NotificationBox::setPalette(), Gui::NotificationBox::showText(), and Gui::NotificationBox::text().
The documentation for this class was generated from the following file:
NotificationBox.cpp