FreeCAD: src.Mod.AddonManager.change_branch.ChangeBranchDialogModel Class Reference
src.Mod.AddonManager.change_branch.ChangeBranchDialogModel Class Reference
Public Member Functions
None __init__ (self, str path, parent=None)
int rowCount (self, QtCore.QModelIndex parent=QtCore.QModelIndex())
int columnCount (self, QtCore.QModelIndex parent=QtCore.QModelIndex())
def data (self, QtCore.QModelIndex index, int role=QtCore.Qt.DisplayRole)
def headerData (self, int section, QtCore.Qt.Orientation orientation, int role=QtCore.Qt.DisplayRole)
Public Attributes
path
branches
current_branch
dirty
Static Public Attributes
list branches = []
DataSortRole = QtCore.Qt.UserRole
int RefAccessRole = QtCore.Qt.UserRole + 1
Detailed Description
Definition at line 124 of file change_branch.py.
Constructor & Destructor Documentation
__init__()
None src.Mod.AddonManager.change_branch.ChangeBranchDialogModel.__init__ (self, str path, parent = None)
Definition at line 130 of file change_branch.py.
References src.Mod.AddonManager.addonmanager_git.initialize_git().
Referenced by draftguitools.gui_subelements.SubelementHighlight.finish().
Member Function Documentation
columnCount()
int src.Mod.AddonManager.change_branch.ChangeBranchDialogModel.columnCount (self, QtCore.QModelIndex parent = QtCore.QModelIndex())
Definition at line 145 of file change_branch.py.
data()
def src.Mod.AddonManager.change_branch.ChangeBranchDialogModel.data (self, QtCore.QModelIndex index, int role = QtCore.Qt.DisplayRole)
Definition at line 150 of file change_branch.py.
References src.Mod.AddonManager.change_branch.ChangeBranchDialogModel.branches, and DraftVecUtils.toString().
headerData()
def src.Mod.AddonManager.change_branch.ChangeBranchDialogModel.headerData (self, int section, QtCore.Qt.Orientation orientation, int role = QtCore.Qt.DisplayRole)
Definition at line 190 of file change_branch.py.
References src.Mod.AddonManager.change_branch.ChangeBranchDialogModel.branches.
rowCount()
int src.Mod.AddonManager.change_branch.ChangeBranchDialogModel.rowCount (self, QtCore.QModelIndex parent = QtCore.QModelIndex())
Definition at line 140 of file change_branch.py.
References src.Mod.AddonManager.change_branch.ChangeBranchDialogModel.branches.
Referenced by src.Mod.AddonManager.package_list.PackageListItemModel.append_item(), and src.Mod.AddonManager.package_list.PackageListItemModel.clear().
Member Data Documentation
branches [1/2]
list src.Mod.AddonManager.change_branch.ChangeBranchDialogModel.branches = [] static
Definition at line 126 of file change_branch.py.
Referenced by src.Mod.AddonManager.change_branch.ChangeBranchDialogModel.data(), src.Mod.AddonManager.change_branch.ChangeBranchDialogModel.headerData(), and src.Mod.AddonManager.change_branch.ChangeBranchDialogModel.rowCount().
branches [2/2]
src.Mod.AddonManager.change_branch.ChangeBranchDialogModel.branches
Definition at line 135 of file change_branch.py.
current_branch
src.Mod.AddonManager.change_branch.ChangeBranchDialogModel.current_branch
Definition at line 136 of file change_branch.py.
DataSortRole
src.Mod.AddonManager.change_branch.ChangeBranchDialogModel.DataSortRole = QtCore.Qt.UserRole static
Definition at line 127 of file change_branch.py.
dirty
src.Mod.AddonManager.change_branch.ChangeBranchDialogModel.dirty
Definition at line 137 of file change_branch.py.
path
src.Mod.AddonManager.change_branch.ChangeBranchDialogModel.path
Definition at line 134 of file change_branch.py.
Referenced by Path.Tool.Gui.BitLibrary.ToolBitLibrary.librarySave(), Path.Tool.Gui.BitLibrary.ToolBitLibrary.librarySaveAs(), Path.Tool.Gui.BitLibrary.ToolBitLibrary.loadData(), and TDTest.DrawHatchTest.DrawHatchTest.testMakeHatchCase().
RefAccessRole
int src.Mod.AddonManager.change_branch.ChangeBranchDialogModel.RefAccessRole = QtCore.Qt.UserRole + 1 static
Definition at line 128 of file change_branch.py.
The documentation for this class was generated from the following file:
change_branch.py