FreeCAD: SketcherGui Namespace Reference
SketcherGui Namespace Reference
Namespaces
ConstraintFilter
ConstructionMethods
StateMachines
Classes
struct AnalysisResults
Struct to hold the results of analysis performed on geometry.
struct AutoConstraint
class CarbonCopySelection
struct CoinMapping
Helper struct containing index conversions (mappings) between {GeoId, PointPos} and MF indices per layer, sublayers, and VertexId and MF indices per layer.
class ConstraintFilterList
struct ConstraintParameters
Struct adapted to store the parameters necessary to create and update constraints.
class ConstraintView
class ConstructionMethodMachine
An encapsulation of a construction method.
class ControlAmount
template class for creating a type encapsulating an int value associated to each of the possible construction modes supported by the tool.
class CurveConverter
struct DrawingParameters
Struct for storing local drawing parameters.
class DrawSketchControllableHandler
Template class intended for handlers controllable by a DrawSketchController.
class DrawSketchController
Class defining a generic handler controller operable with a DrawSketchControllableHandler.
class DrawSketchDefaultHandler
A DrawSketchHandler template for geometry creation.
class DrawSketchDefaultWidgetController
Class defining a handler controller making use of parameters provided by a widget of type SketcherToolDefaultWidget.
class DrawSketchHandler
class DrawSketchHandlerArc
class DrawSketchHandlerArcOfEllipse
class DrawSketchHandlerArcOfHyperbola
class DrawSketchHandlerArcOfParabola
class DrawSketchHandlerArcSlot
class DrawSketchHandlerBSpline
class DrawSketchHandlerCarbonCopy
class DrawSketchHandlerCircle
class DrawSketchHandlerEllipse
class DrawSketchHandlerExtend
class DrawSketchHandlerExternal
class DrawSketchHandlerFillet
class DrawSketchHandlerLine
class DrawSketchHandlerLineSet
class DrawSketchHandlerOffset
class DrawSketchHandlerPoint
class DrawSketchHandlerPolygon
class DrawSketchHandlerRectangle
class DrawSketchHandlerRotate
class DrawSketchHandlerScale
class DrawSketchHandlerSlot
class DrawSketchHandlerSplitting
class DrawSketchHandlerSymmetry
class DrawSketchHandlerTranslate
class DrawSketchHandlerTrimming
class DrawSketchKeyboardManager
class EditDatumDialog
class EditModeCoinManager
Helper class for managing the Coin nodes of ViewProviderSketch.
class EditModeConstraintCoinManager
Class for managing the Edit mode coin nodes of ViewProviderSketch relating to constraints.
class EditModeGeometryCoinConverter
Class for creating the Geometry layer into coin nodes.
class EditModeGeometryCoinManager
Class for managing the Edit mode coin nodes of ViewProviderSketch relating to geometry.
class EditModeInformationOverlayCoinConverter
Class for creating the Overlay information layer.
struct EditModeScenegraphNodes
Helper struct adapted to store the pointer to edit mode scenegraph objects.
class ElementFilterList
class ElementItem
class ElementItemDelegate
class ElementView
class ExceptionWrongInput
class ExtendSelection
class ExternalSelection
class FilletSelection
class GenericConstraintSelection
The GenericConstraintSelection class SelectionFilterGate with changeable filters. In a constraint creation mode like point on object, if the first selection object can be a point, the next has to be a curve for the constraint to make sense. Thus filters are changeable so that same filter can be kept on while in one mode.
struct GeometryLayerNodes
Struct for storing references to the scenegraph nodes necessary for geometry layers.
class GeometryLayerParameters
Helper class to store geometry layers configuration.
class Module
class MultiFieldId
Helper class to store together a field index of a coin multifield object and the coin geometry layer to which it belongs.
class OnViewParameters
Type encapsulating the number of On view parameters.
struct OverlayParameters
Struct adapted to store the parameters necessary to create and update the information overlay layer.
class PropertyConstraintListItem
class PropertyVisualLayerList
struct SelIdPair
class ShortcutListener
class SketcherRegularPolygonDialog
class SketcherSettings
class SketcherSettingsAppearance
class SketcherSettingsDisplay
class SketcherSettingsGrid
class SketcherToolDefaultWidget
class SketcherValidation
class SketchMirrorDialog
class SketchOrientationDialog
class SketchRectangularArrayDialog
struct SketchSelection
class SnapManager
class SoZoomTranslation
class SplittingSelection
class StateMachine
A state machine to encapsulate a state.
class TaskDlgEditSketch
simulation dialog for the TaskView
class TaskSketcherConstraints
class TaskSketcherElements
class TaskSketcherMessages
class TaskSketcherSolverAdvanced
class TaskSketcherTool
class TaskSketcherValidation
class TrimmingSelection
class ViewProviderCustom
class ViewProviderSketch
The Sketch ViewProvider.
class ViewProviderSketchCoinAttorney
Attorney class for limiting access to viewprovider.
class ViewProviderSketchDrawSketchHandlerAttorney
class ViewProviderSketchGeometryExtension
class ViewProviderSketchSnapAttorney
class VisualLayer
class WidgetCheckboxes
Type encapsulating the number of checkboxes in the widget.
class WidgetComboboxes
Type encapsulating the number of comboboxes in the widget.
class WidgetParameters
Type encapsulating the number of parameters in the widget.
class Workbench
Typedefs
using DSHArcController = DrawSketchDefaultWidgetController< DrawSketchHandlerArc, StateMachines::ThreeSeekEnd, 3, OnViewParameters< 5, 6 >, WidgetParameters< 0, 0 >, WidgetCheckboxes< 0, 0 >, WidgetComboboxes< 1, 1 >, ConstructionMethods::CircleEllipseConstructionMethod, true >
using DSHArcControllerBase = DSHArcController::ControllerBase
using DrawSketchHandlerArcBase = DrawSketchControllableHandler< DSHArcController >
using DSHArcSlotController = DrawSketchDefaultWidgetController< DrawSketchHandlerArcSlot, StateMachines::FourSeekEnd, 3, OnViewParameters< 6, 6 >, WidgetParameters< 0, 0 >, WidgetCheckboxes< 0, 0 >, WidgetComboboxes< 1, 1 >, ConstructionMethods::ArcSlotConstructionMethod, true >
using DSHArcSlotControllerBase = DSHArcSlotController::ControllerBase
using DrawSketchHandlerArcSlotBase = DrawSketchControllableHandler< DSHArcSlotController >
using DSHBSplineController = DrawSketchDefaultWidgetController< DrawSketchHandlerBSpline, StateMachines::TwoSeekEnd, 2, OnViewParameters< 4, 4 >, WidgetParameters< 1, 1 >, WidgetCheckboxes< 1, 1 >, WidgetComboboxes< 1, 1 >, ConstructionMethods::BSplineConstructionMethod, true >
using DSHBSplineControllerBase = DSHBSplineController::ControllerBase
using DrawSketchHandlerBSplineBase = DrawSketchControllableHandler< DSHBSplineController >
using DSHCircleController = DrawSketchDefaultWidgetController< DrawSketchHandlerCircle, StateMachines::ThreeSeekEnd, 3, OnViewParameters< 3, 6 >, WidgetParameters< 0, 0 >, WidgetCheckboxes< 0, 0 >, WidgetComboboxes< 1, 1 >, ConstructionMethods::CircleEllipseConstructionMethod, true >
using DSHCircleControllerBase = DSHCircleController::ControllerBase
using DrawSketchHandlerCircleBase = DrawSketchControllableHandler< DSHCircleController >
using DSHEllipseController = DrawSketchDefaultWidgetController< DrawSketchHandlerEllipse, StateMachines::ThreeSeekEnd, 3, OnViewParameters< 5, 6 >, WidgetParameters< 0, 0 >, WidgetCheckboxes< 0, 0 >, WidgetComboboxes< 1, 1 >, ConstructionMethods::CircleEllipseConstructionMethod, true >
using DSHEllipseControllerBase = DSHEllipseController::ControllerBase
using DrawSketchHandlerEllipseBase = DrawSketchControllableHandler< DSHEllipseController >
using DSHFilletController = DrawSketchDefaultWidgetController< DrawSketchHandlerFillet, StateMachines::TwoSeekEnd, 0, OnViewParameters< 0, 0 >, WidgetParameters< 0, 0 >, WidgetCheckboxes< 1, 1 >, WidgetComboboxes< 1, 1 >, ConstructionMethods::FilletConstructionMethod, true >
using DSHFilletControllerBase = DSHFilletController::ControllerBase
using DrawSketchHandlerFilletBase = DrawSketchControllableHandler< DSHFilletController >
using DSHLineController = DrawSketchDefaultWidgetController< DrawSketchHandlerLine, StateMachines::TwoSeekEnd, 2, OnViewParameters< 4, 4, 4 >, WidgetParameters< 0, 0, 0 >, WidgetCheckboxes< 0, 0, 0 >, WidgetComboboxes< 1, 1, 1 >, ConstructionMethods::LineConstructionMethod, true >
using DSHLineControllerBase = DSHLineController::ControllerBase
using DrawSketchHandlerLineBase = DrawSketchControllableHandler< DSHLineController >
using DSHOffsetController = DrawSketchDefaultWidgetController< DrawSketchHandlerOffset, StateMachines::OneSeekEnd, 0, OnViewParameters< 1, 1 >, WidgetParameters< 0, 0 >, WidgetCheckboxes< 2, 2 >, WidgetComboboxes< 1, 1 >, ConstructionMethods::OffsetConstructionMethod, true >
using DSHOffsetControllerBase = DSHOffsetController::ControllerBase
using DrawSketchHandlerOffsetBase = DrawSketchControllableHandler< DSHOffsetController >
using DSHPointController = DrawSketchController< DrawSketchHandlerPoint, StateMachines::OneSeekEnd, 1, OnViewParameters< 2 > >
using DrawSketchHandlerPointBase = DrawSketchControllableHandler< DSHPointController >
using DSHPolygonController = DrawSketchDefaultWidgetController< DrawSketchHandlerPolygon, StateMachines::TwoSeekEnd, 2, OnViewParameters< 4 >, WidgetParameters< 1 >, WidgetCheckboxes< 0 >, WidgetComboboxes< 0 > >
using DSHPolygonControllerBase = DSHPolygonController::ControllerBase
using DrawSketchHandlerPolygonBase = DrawSketchControllableHandler< DSHPolygonController >
using DSHRectangleController = DrawSketchDefaultWidgetController< DrawSketchHandlerRectangle, StateMachines::FiveSeekEnd, 3, OnViewParameters< 6, 6, 8, 8 >, WidgetParameters< 0, 0, 0, 0 >, WidgetCheckboxes< 2, 2, 2, 2 >, WidgetComboboxes< 1, 1, 1, 1 >, ConstructionMethods::RectangleConstructionMethod, true >
using DSHRectangleControllerBase = DSHRectangleController::ControllerBase
using DrawSketchHandlerRectangleBase = DrawSketchControllableHandler< DSHRectangleController >
using DSHRotateController = DrawSketchDefaultWidgetController< DrawSketchHandlerRotate, StateMachines::ThreeSeekEnd, 0, OnViewParameters< 4 >, WidgetParameters< 1 >, WidgetCheckboxes< 1 >, WidgetComboboxes< 0 > >
using DSHRotateControllerBase = DSHRotateController::ControllerBase
using DrawSketchHandlerRotateBase = DrawSketchControllableHandler< DSHRotateController >
using DSHScaleController = DrawSketchDefaultWidgetController< DrawSketchHandlerScale, StateMachines::ThreeSeekEnd, 0, OnViewParameters< 3 >, WidgetParameters< 0 >, WidgetCheckboxes< 1 >, WidgetComboboxes< 0 > >
using DSHScaleControllerBase = DSHScaleController::ControllerBase
using DrawSketchHandlerScaleBase = DrawSketchControllableHandler< DSHScaleController >
using DSHSlotController = DrawSketchDefaultWidgetController< DrawSketchHandlerSlot, StateMachines::ThreeSeekEnd, 2, OnViewParameters< 5 >, WidgetParameters< 0 >, WidgetCheckboxes< 0 >, WidgetComboboxes< 0 > >
using DSHSlotControllerBase = DSHSlotController::ControllerBase
using DrawSketchHandlerSlotBase = DrawSketchControllableHandler< DSHSlotController >
using DSHSymmetryController = DrawSketchDefaultWidgetController< DrawSketchHandlerSymmetry, StateMachines::OneSeekEnd, 0, OnViewParameters< 0 >, WidgetParameters< 0 >, WidgetCheckboxes< 2 >, WidgetComboboxes< 0 > >
using DSHSymmetryControllerBase = DSHSymmetryController::ControllerBase
using DrawSketchHandlerSymmetryBase = DrawSketchControllableHandler< DSHSymmetryController >
using DSHTranslateController = DrawSketchDefaultWidgetController< DrawSketchHandlerTranslate, StateMachines::ThreeSeekEnd, 0, OnViewParameters< 6 >, WidgetParameters< 2 >, WidgetCheckboxes< 1 >, WidgetComboboxes< 0 > >
using DSHTranslateControllerBase = DSHTranslateController::ControllerBase
using DrawSketchHandlerTranslateBase = DrawSketchControllableHandler< DSHTranslateController >
using GeoList = Sketcher::GeoList
using GeoListFacade = Sketcher::GeoListFacade
using ViewProviderPython = Gui::ViewProviderFeaturePythonT< ViewProviderSketch >
using ViewProviderCustomPython = Gui::ViewProviderFeaturePythonT< ViewProviderCustom >
Enumerations
enum ConstraintCreationMode { Driving, Reference }
enum SelType {
SelUnknown = 0, SelVertex = 1, SelVertexOrRoot = 64, SelRoot = 2,
SelEdge = 4, SelEdgeOrAxis = 128, SelHAxis = 8, SelVAxis = 16,
SelExternalEdge = 32
}
The SelType enum Types of sketch elements that can be (pre)selected. The root/origin and the axes are put up separately so that they can be specifically disallowed, for example, when in lock, horizontal, or vertical constraint modes.
enum GeometryCreationMode { GeometryCreationMode::Normal = 0, GeometryCreationMode::Construction = 1 }
enum SubElementType {
SubElementType::edge, SubElementType::start, SubElementType::end, SubElementType::mid,
SubElementType::none
}
Functions
PyObject * initModule ()
Attacher::eMapMode SuggestAutoMapMode (Attacher::SuggestResult::eSuggestResult *pMsgId=nullptr, QString *message=nullptr, std::vector< Attacher::eMapMode > *allmodes=nullptr)
void makeAngleBetweenTwoLines (Sketcher::SketchObject *Obj, Gui::Command *cmd, int geoId1, int geoId2)
Makes an angle constraint between 2 lines.
bool calculateAngle (Sketcher::SketchObject *Obj, int &geoId1, int &geoId2, Sketcher::PointPos &PosId1, Sketcher::PointPos &PosId2, double &ActAngle)
void makeTangentToEllipseviaNewPoint (Sketcher::SketchObject *Obj, const Part::GeomEllipse *ellipse, const Part::Geometry *geom2, int geoId1, int geoId2)
void makeTangentToArcOfEllipseviaNewPoint (Sketcher::SketchObject *Obj, const Part::GeomArcOfEllipse *aoe, const Part::Geometry *geom2, int geoId1, int geoId2)
void makeTangentToArcOfHyperbolaviaNewPoint (Sketcher::SketchObject *Obj, const Part::GeomArcOfHyperbola *aoh, const Part::Geometry *geom2, int geoId1, int geoId2)
void makeTangentToArcOfParabolaviaNewPoint (Sketcher::SketchObject *Obj, const Part::GeomArcOfParabola *aop, const Part::Geometry *geom2, int geoId1, int geoId2)
void doEndpointTangency (Sketcher::SketchObject *Obj, int GeoId1, int GeoId2, Sketcher::PointPos PosId1, Sketcher::PointPos PosId2)
Does an endpoint-to-endpoint tangency.
void doEndpointToEdgeTangency (Sketcher::SketchObject *Obj, int GeoId1, Sketcher::PointPos PosId1, int GeoId2)
Does an endpoint-edge tangency.
void notifyConstraintSubstitutions (const QString &message)
bool tryAutoRecompute (Sketcher::SketchObject *obj)
bool tryAutoRecompute (Sketcher::SketchObject *obj, bool &autoremoveredundants)
Same as the other overload, but also returns whether redundants shall be removed or not.
void tryAutoRecomputeIfNotSolve (Sketcher::SketchObject *obj)
bool ReleaseHandler (Gui::Document *doc)
std::string getStrippedPythonExceptionString (const Base::Exception &)
void getIdsFromName (const std::string &name, const Sketcher::SketchObject *Obj, int &GeoId, Sketcher::PointPos &PosId)
std::vector< int > getGeoIdsOfEdgesFromNames (const Sketcher::SketchObject *Obj, const std::vector< std::string > &names)
Returns ONLY the geometry elements when the "Edge" is selected (including GeomPoints)
bool checkBothExternal (int GeoId1, int GeoId2)
bool isPointOrSegmentFixed (const Sketcher::SketchObject *Obj, int GeoId)
bool areBothPointsOrSegmentsFixed (const Sketcher::SketchObject *Obj, int GeoId1, int GeoId2)
bool areAllPointsOrSegmentsFixed (const Sketcher::SketchObject *Obj, int GeoId1, int GeoId2, int GeoId3)
bool isVertex (int GeoId, Sketcher::PointPos PosId)
bool isEdge (int GeoId, Sketcher::PointPos PosId)
bool isSimpleVertex (const Sketcher::SketchObject *Obj, int GeoId, Sketcher::PointPos PosId)
bool isBsplineKnot (const Sketcher::SketchObject *Obj, int GeoId)
Checks if GeoId corresponds to a B-Spline knot.
bool isBsplineKnotOrEndPoint (const Sketcher::SketchObject *Obj, int GeoId, Sketcher::PointPos PosId)
bool IsPointAlreadyOnCurve (int GeoIdCurve, int GeoIdPoint, Sketcher::PointPos PosIdPoint, Sketcher::SketchObject *Obj)
bool isBsplinePole (const Part::Geometry *geo)
bool isBsplinePole (const Sketcher::SketchObject *Obj, int GeoId)
bool checkConstraint (const std::vector< Sketcher::Constraint * > &vals, Sketcher::ConstraintType type, int geoid, Sketcher::PointPos pos)
bool isConstructionMode ()
const char * constructionModeAsBooleanText ()
double GetPointAngle (const Base::Vector2d &p1, const Base::Vector2d &p2)
void GetCirclesMinimalDistance (const Part::Geometry *geom1, const Part::Geometry *geom2, Base::Vector3d &point1, Base::Vector3d &point2)
void ActivateHandler (Gui::Document *doc, std::unique_ptr< DrawSketchHandler > handler)
bool isSketchInEdit (Gui::Document *doc)
Returns if a sketch is in edit mode.
bool isCommandActive (Gui::Document *doc, bool actsOnSelection=false)
bool isSketcherBSplineActive (Gui::Document *doc, bool actsOnSelection)
SketcherGui::ViewProviderSketch * getInactiveHandlerEditModeSketchViewProvider (Gui::Document *doc)
SketcherGui::ViewProviderSketch * getInactiveHandlerEditModeSketchViewProvider ()
void removeRedundantHorizontalVertical (Sketcher::SketchObject *psketch, std::vector< AutoConstraint > &sug1, std::vector< AutoConstraint > &sug2)
void ConstraintToAttachment (Sketcher::GeoElementId element, Sketcher::GeoElementId attachment, double distance, App::DocumentObject *obj)
bool hideUnits ()
bool showCursorCoords ()
bool useSystemDecimals ()
std::string lengthToDisplayFormat (double value, int digits)
std::string angleToDisplayFormat (double value, int digits)
bool areCollinear (const Base::Vector2d &p1, const Base::Vector2d &p2, const Base::Vector2d &p3)
int indexOfGeoId (const std::vector< int > &vec, int elem)
bool operator== (VisualLayer const &lhs, VisualLayer const &rhs)
template<typename T >
void SketcherAddWorkbenchSketchActions (T &sketch)
template<>
void SketcherAddWorkbenchSketchActions (Gui::MenuItem &sketch)
template<>
void SketcherAddWorkbenchSketchActions (Gui::ToolBarItem &sketch)
template<typename T >
void SketcherAddWorkbenchSketchEditModeActions (T &sketch)
template<>
void SketcherAddWorkbenchSketchEditModeActions (Gui::MenuItem &sketch)
template<>
void SketcherAddWorkbenchSketchEditModeActions (Gui::ToolBarItem &sketch)
template<typename T >
void SketcherAddWorkbenchGeometries (T &geom)
template<typename T >
void SketcherAddWorkspaceLines (T &geom)
template<>
void SketcherAddWorkspaceLines< Gui::MenuItem > (Gui::MenuItem &geom)
template<>
void SketcherAddWorkspaceLines< Gui::ToolBarItem > (Gui::ToolBarItem &geom)
template<typename T >
void SketcherAddWorkspaceArcs (T &geom)
template<>
void SketcherAddWorkspaceArcs< Gui::MenuItem > (Gui::MenuItem &geom)
template<>
void SketcherAddWorkspaceArcs< Gui::ToolBarItem > (Gui::ToolBarItem &geom)
template<typename T >
void SketcherAddWorkspaceRegularPolygon (T &geom)
template<>
void SketcherAddWorkspaceRegularPolygon< Gui::MenuItem > (Gui::MenuItem &geom)
template<>
void SketcherAddWorkspaceRegularPolygon< Gui::ToolBarItem > (Gui::ToolBarItem &geom)
template<typename T >
void SketcherAddWorkspaceRectangles (T &geom)
template<>
void SketcherAddWorkspaceRectangles< Gui::MenuItem > (Gui::MenuItem &geom)
template<>
void SketcherAddWorkspaceRectangles< Gui::ToolBarItem > (Gui::ToolBarItem &geom)
template<typename T >
void SketcherAddWorkspaceslots (T &geom)
template<>
void SketcherAddWorkspaceslots< Gui::MenuItem > (Gui::MenuItem &geom)
template<>
void SketcherAddWorkspaceslots< Gui::ToolBarItem > (Gui::ToolBarItem &geom)
template<typename T >
void SketcherAddWorkspaceFillets (T &geom)
template<>
void SketcherAddWorkspaceFillets< Gui::MenuItem > (Gui::MenuItem &geom)
template<>
void SketcherAddWorkspaceFillets< Gui::ToolBarItem > (Gui::ToolBarItem &geom)
template<typename T >
void SketcherAddWorkspaceCurveEdition (T &geom)
template<>
void SketcherAddWorkspaceCurveEdition< Gui::MenuItem > (Gui::MenuItem &geom)
template<>
void SketcherAddWorkspaceCurveEdition< Gui::ToolBarItem > (Gui::ToolBarItem &geom)
template<typename T >
void SketcherAddWorkbenchConstraints (T &cons)
template<>
void SketcherAddWorkbenchConstraints< Gui::MenuItem > (Gui::MenuItem &cons)
template<>
void SketcherAddWorkbenchConstraints< Gui::ToolBarItem > (Gui::ToolBarItem &cons)
template<typename T >
void SketcherAddWorkbenchTools (T &consaccel)
template<>
void SketcherAddWorkbenchTools< Gui::MenuItem > (Gui::MenuItem &consaccel)
template<>
void SketcherAddWorkbenchTools< Gui::ToolBarItem > (Gui::ToolBarItem &consaccel)
template<typename T >
void SketcherAddWorkbenchBSplines (T &bspline)
template<>
void SketcherAddWorkbenchBSplines< Gui::MenuItem > (Gui::MenuItem &bspline)
template<>
void SketcherAddWorkbenchBSplines< Gui::ToolBarItem > (Gui::ToolBarItem &bspline)
template<typename T >
void SketcherAddWorkbenchVisual (T &visual)
template<>
void SketcherAddWorkbenchVisual< Gui::MenuItem > (Gui::MenuItem &visual)
template<>
void SketcherAddWorkbenchVisual< Gui::ToolBarItem > (Gui::ToolBarItem &visual)
template<typename T >
void SketcherAddWorkbenchEditTools (T &virtualspedittoolsace)
template<>
void SketcherAddWorkbenchEditTools< Gui::ToolBarItem > (Gui::ToolBarItem &edittools)
void addSketcherWorkbenchSketchActions (Gui::MenuItem &sketch)
void addSketcherWorkbenchSketchEditModeActions (Gui::MenuItem &sketch)
void addSketcherWorkbenchGeometries (Gui::MenuItem &geom)
void addSketcherWorkbenchConstraints (Gui::MenuItem &cons)
void addSketcherWorkbenchTools (Gui::MenuItem &consaccel)
void addSketcherWorkbenchBSplines (Gui::MenuItem &bspline)
void addSketcherWorkbenchVisual (Gui::MenuItem &visual)
void addSketcherWorkbenchSketchActions (Gui::ToolBarItem &sketch)
void addSketcherWorkbenchSketchEditModeActions (Gui::ToolBarItem &sketch)
void addSketcherWorkbenchGeometries (Gui::ToolBarItem &geom)
void addSketcherWorkbenchConstraints (Gui::ToolBarItem &cons)
void addSketcherWorkbenchTools (Gui::ToolBarItem &consaccel)
void addSketcherWorkbenchBSplines (Gui::ToolBarItem &bspline)
void addSketcherWorkbenchVisual (Gui::ToolBarItem &visual)
void addSketcherWorkbenchEditTools (Gui::ToolBarItem &edittools)
Variables
GeometryCreationMode geometryCreationMode = GeometryCreationMode::Normal
Typedef Documentation
DrawSketchHandlerArcBase
using SketcherGui::DrawSketchHandlerArcBase = typedef DrawSketchControllableHandler<DSHArcController>
Definition at line 66 of file DrawSketchHandlerArc.h.
DrawSketchHandlerArcSlotBase
using SketcherGui::DrawSketchHandlerArcSlotBase = typedef DrawSketchControllableHandler<DSHArcSlotController>
Definition at line 94 of file DrawSketchHandlerArcSlot.h.
DrawSketchHandlerBSplineBase
using SketcherGui::DrawSketchHandlerBSplineBase = typedef DrawSketchControllableHandler<DSHBSplineController>
Definition at line 92 of file DrawSketchHandlerBSpline.h.
DrawSketchHandlerCircleBase
using SketcherGui::DrawSketchHandlerCircleBase = typedef DrawSketchControllableHandler<DSHCircleController>
Definition at line 83 of file DrawSketchHandlerCircle.h.
DrawSketchHandlerEllipseBase
using SketcherGui::DrawSketchHandlerEllipseBase = typedef DrawSketchControllableHandler<DSHEllipseController>
Definition at line 88 of file DrawSketchHandlerEllipse.h.
DrawSketchHandlerFilletBase
using SketcherGui::DrawSketchHandlerFilletBase = typedef DrawSketchControllableHandler<DSHFilletController>
Definition at line 118 of file DrawSketchHandlerFillet.h.
DrawSketchHandlerLineBase
using SketcherGui::DrawSketchHandlerLineBase = typedef DrawSketchControllableHandler<DSHLineController>
Definition at line 93 of file DrawSketchHandlerLine.h.
DrawSketchHandlerOffsetBase
using SketcherGui::DrawSketchHandlerOffsetBase = typedef DrawSketchControllableHandler<DSHOffsetController>
Definition at line 107 of file DrawSketchHandlerOffset.h.
DrawSketchHandlerPointBase
using SketcherGui::DrawSketchHandlerPointBase = typedef DrawSketchControllableHandler<DSHPointController>
Definition at line 70 of file DrawSketchHandlerPoint.h.
DrawSketchHandlerPolygonBase
using SketcherGui::DrawSketchHandlerPolygonBase = typedef DrawSketchControllableHandler<DSHPolygonController>
Definition at line 82 of file DrawSketchHandlerPolygon.h.
DrawSketchHandlerRectangleBase
using SketcherGui::DrawSketchHandlerRectangleBase = typedef DrawSketchControllableHandler<DSHRectangleController>
Definition at line 96 of file DrawSketchHandlerRectangle.h.
DrawSketchHandlerRotateBase
using SketcherGui::DrawSketchHandlerRotateBase = typedef DrawSketchControllableHandler<DSHRotateController>
Definition at line 58 of file DrawSketchHandlerRotate.h.
DrawSketchHandlerScaleBase
using SketcherGui::DrawSketchHandlerScaleBase = typedef DrawSketchControllableHandler<DSHScaleController>
Definition at line 63 of file DrawSketchHandlerScale.h.
DrawSketchHandlerSlotBase
using SketcherGui::DrawSketchHandlerSlotBase = typedef DrawSketchControllableHandler<DSHSlotController>
Definition at line 83 of file DrawSketchHandlerSlot.h.
DrawSketchHandlerSymmetryBase
using SketcherGui::DrawSketchHandlerSymmetryBase = typedef DrawSketchControllableHandler<DSHSymmetryController>
Definition at line 63 of file DrawSketchHandlerSymmetry.h.
DrawSketchHandlerTranslateBase
using SketcherGui::DrawSketchHandlerTranslateBase = typedef DrawSketchControllableHandler<DSHTranslateController>
Definition at line 62 of file DrawSketchHandlerTranslate.h.
DSHArcController
using SketcherGui::DSHArcController = typedef DrawSketchDefaultWidgetController<DrawSketchHandlerArc, StateMachines::ThreeSeekEnd, 3, OnViewParameters<5, 6>, WidgetParameters<0, 0>, WidgetCheckboxes<0, 0>, WidgetComboboxes<1, 1>, ConstructionMethods::CircleEllipseConstructionMethod, true>
Definition at line 62 of file DrawSketchHandlerArc.h.
DSHArcControllerBase
using SketcherGui::DSHArcControllerBase = typedef DSHArcController::ControllerBase
Definition at line 64 of file DrawSketchHandlerArc.h.
DSHArcSlotController
using SketcherGui::DSHArcSlotController = typedef DrawSketchDefaultWidgetController<DrawSketchHandlerArcSlot, StateMachines::FourSeekEnd, 3, OnViewParameters<6, 6>, WidgetParameters<0, 0>, WidgetCheckboxes<0, 0>, WidgetComboboxes<1, 1>, ConstructionMethods::ArcSlotConstructionMethod, true>
Definition at line 90 of file DrawSketchHandlerArcSlot.h.
DSHArcSlotControllerBase
using SketcherGui::DSHArcSlotControllerBase = typedef DSHArcSlotController::ControllerBase
Definition at line 92 of file DrawSketchHandlerArcSlot.h.
DSHBSplineController
using SketcherGui::DSHBSplineController = typedef DrawSketchDefaultWidgetController<DrawSketchHandlerBSpline, StateMachines::TwoSeekEnd, 2, OnViewParameters<4, 4>, WidgetParameters<1, 1>, WidgetCheckboxes<1, 1>, WidgetComboboxes<1, 1>, ConstructionMethods::BSplineConstructionMethod, true>
Definition at line 88 of file DrawSketchHandlerBSpline.h.
DSHBSplineControllerBase
using SketcherGui::DSHBSplineControllerBase = typedef DSHBSplineController::ControllerBase
Definition at line 90 of file DrawSketchHandlerBSpline.h.
DSHCircleController
using SketcherGui::DSHCircleController = typedef DrawSketchDefaultWidgetController<DrawSketchHandlerCircle, StateMachines::ThreeSeekEnd, 3, OnViewParameters<3, 6>, WidgetParameters<0, 0>, WidgetCheckboxes<0, 0>, WidgetComboboxes<1, 1>, ConstructionMethods::CircleEllipseConstructionMethod, true>
Definition at line 79 of file DrawSketchHandlerCircle.h.
DSHCircleControllerBase
using SketcherGui::DSHCircleControllerBase = typedef DSHCircleController::ControllerBase
Definition at line 81 of file DrawSketchHandlerCircle.h.
DSHEllipseController
using SketcherGui::DSHEllipseController = typedef DrawSketchDefaultWidgetController<DrawSketchHandlerEllipse, StateMachines::ThreeSeekEnd, 3, OnViewParameters<5, 6>, WidgetParameters<0, 0>, WidgetCheckboxes<0, 0>, WidgetComboboxes<1, 1>, ConstructionMethods::CircleEllipseConstructionMethod, true>
Definition at line 84 of file DrawSketchHandlerEllipse.h.
DSHEllipseControllerBase
using SketcherGui::DSHEllipseControllerBase = typedef DSHEllipseController::ControllerBase
Definition at line 86 of file DrawSketchHandlerEllipse.h.
DSHFilletController
using SketcherGui::DSHFilletController = typedef DrawSketchDefaultWidgetController<DrawSketchHandlerFillet, StateMachines::TwoSeekEnd, 0, OnViewParameters<0, 0>, WidgetParameters<0, 0>, WidgetCheckboxes<1, 1>, WidgetComboboxes<1, 1>, ConstructionMethods::FilletConstructionMethod, true>
Definition at line 114 of file DrawSketchHandlerFillet.h.
DSHFilletControllerBase
using SketcherGui::DSHFilletControllerBase = typedef DSHFilletController::ControllerBase
Definition at line 116 of file DrawSketchHandlerFillet.h.
DSHLineController
using SketcherGui::DSHLineController = typedef DrawSketchDefaultWidgetController<DrawSketchHandlerLine, StateMachines::TwoSeekEnd, 2, OnViewParameters<4, 4, 4>, WidgetParameters<0, 0, 0>, WidgetCheckboxes<0, 0, 0>, WidgetComboboxes<1, 1, 1>, ConstructionMethods::LineConstructionMethod, true>
Definition at line 89 of file DrawSketchHandlerLine.h.
DSHLineControllerBase
using SketcherGui::DSHLineControllerBase = typedef DSHLineController::ControllerBase
Definition at line 91 of file DrawSketchHandlerLine.h.
DSHOffsetController
using SketcherGui::DSHOffsetController = typedef DrawSketchDefaultWidgetController<DrawSketchHandlerOffset, StateMachines::OneSeekEnd, 0, OnViewParameters<1, 1>, WidgetParameters<0, 0>, WidgetCheckboxes<2, 2>, WidgetComboboxes<1, 1>, ConstructionMethods::OffsetConstructionMethod, true>
Definition at line 103 of file DrawSketchHandlerOffset.h.
DSHOffsetControllerBase
using SketcherGui::DSHOffsetControllerBase = typedef DSHOffsetController::ControllerBase
Definition at line 105 of file DrawSketchHandlerOffset.h.
DSHPointController
using SketcherGui::DSHPointController = typedef DrawSketchController<DrawSketchHandlerPoint, StateMachines::OneSeekEnd, 1, OnViewParameters<2> >
Definition at line 68 of file DrawSketchHandlerPoint.h.
DSHPolygonController
using SketcherGui::DSHPolygonController = typedef DrawSketchDefaultWidgetController<DrawSketchHandlerPolygon, StateMachines::TwoSeekEnd, 2, OnViewParameters<4>, WidgetParameters<1>, WidgetCheckboxes<0>, WidgetComboboxes<0> >
Definition at line 78 of file DrawSketchHandlerPolygon.h.
DSHPolygonControllerBase
using SketcherGui::DSHPolygonControllerBase = typedef DSHPolygonController::ControllerBase
Definition at line 80 of file DrawSketchHandlerPolygon.h.
DSHRectangleController
using SketcherGui::DSHRectangleController = typedef DrawSketchDefaultWidgetController< DrawSketchHandlerRectangle, StateMachines::FiveSeekEnd, 3, OnViewParameters<6, 6, 8, 8>, WidgetParameters<0, 0, 0, 0>, WidgetCheckboxes<2, 2, 2, 2>, WidgetComboboxes<1, 1, 1, 1>, ConstructionMethods::RectangleConstructionMethod, true>
Definition at line 92 of file DrawSketchHandlerRectangle.h.
DSHRectangleControllerBase
using SketcherGui::DSHRectangleControllerBase = typedef DSHRectangleController::ControllerBase
Definition at line 94 of file DrawSketchHandlerRectangle.h.
DSHRotateController
using SketcherGui::DSHRotateController = typedef DrawSketchDefaultWidgetController<DrawSketchHandlerRotate, StateMachines::ThreeSeekEnd, 0, OnViewParameters<4>, WidgetParameters<1>, WidgetCheckboxes<1>, WidgetComboboxes<0> >
Definition at line 54 of file DrawSketchHandlerRotate.h.
DSHRotateControllerBase
using SketcherGui::DSHRotateControllerBase = typedef DSHRotateController::ControllerBase
Definition at line 56 of file DrawSketchHandlerRotate.h.
DSHScaleController
using SketcherGui::DSHScaleController = typedef DrawSketchDefaultWidgetController<DrawSketchHandlerScale, StateMachines::ThreeSeekEnd, 0, OnViewParameters<3>, WidgetParameters<0>, WidgetCheckboxes<1>, WidgetComboboxes<0> >
Definition at line 59 of file DrawSketchHandlerScale.h.
DSHScaleControllerBase
using SketcherGui::DSHScaleControllerBase = typedef DSHScaleController::ControllerBase
Definition at line 61 of file DrawSketchHandlerScale.h.
DSHSlotController
using SketcherGui::DSHSlotController = typedef DrawSketchDefaultWidgetController<DrawSketchHandlerSlot, StateMachines::ThreeSeekEnd, 2, OnViewParameters<5>, WidgetParameters<0>, WidgetCheckboxes<0>, WidgetComboboxes<0> >
Definition at line 79 of file DrawSketchHandlerSlot.h.
DSHSlotControllerBase
using SketcherGui::DSHSlotControllerBase = typedef DSHSlotController::ControllerBase
Definition at line 81 of file DrawSketchHandlerSlot.h.
DSHSymmetryController
using SketcherGui::DSHSymmetryController = typedef DrawSketchDefaultWidgetController<DrawSketchHandlerSymmetry, StateMachines::OneSeekEnd, 0, OnViewParameters<0>, WidgetParameters<0>, WidgetCheckboxes<2>, WidgetComboboxes<0> >
Definition at line 59 of file DrawSketchHandlerSymmetry.h.
DSHSymmetryControllerBase
using SketcherGui::DSHSymmetryControllerBase = typedef DSHSymmetryController::ControllerBase
Definition at line 61 of file DrawSketchHandlerSymmetry.h.
DSHTranslateController
using SketcherGui::DSHTranslateController = typedef DrawSketchDefaultWidgetController<DrawSketchHandlerTranslate, StateMachines::ThreeSeekEnd, 0, OnViewParameters<6>, WidgetParameters<2>, WidgetCheckboxes<1>, WidgetComboboxes<0> >
Definition at line 58 of file DrawSketchHandlerTranslate.h.
DSHTranslateControllerBase
using SketcherGui::DSHTranslateControllerBase = typedef DSHTranslateController::ControllerBase
Definition at line 60 of file DrawSketchHandlerTranslate.h.
GeoList
typedef Sketcher::GeoList SketcherGui::GeoList
Definition at line 70 of file EditModeCoinManager.h.
GeoListFacade
typedef Sketcher::GeoListFacade SketcherGui::GeoListFacade
Definition at line 71 of file EditModeCoinManager.h.
ViewProviderCustomPython
using SketcherGui::ViewProviderCustomPython = typedef Gui::ViewProviderFeaturePythonT<ViewProviderCustom>
Definition at line 70 of file Sketcher/Gui/ViewProviderPython.h.
ViewProviderPython
using SketcherGui::ViewProviderPython = typedef Gui::ViewProviderFeaturePythonT<ViewProviderSketch>
Definition at line 69 of file Sketcher/Gui/ViewProviderPython.h.
Enumeration Type Documentation
ConstraintCreationMode
enum SketcherGui::ConstraintCreationMode
Enumerator
Driving
Reference
Definition at line 67 of file CommandConstraints.cpp.
GeometryCreationMode
enum SketcherGui::GeometryCreationMode strong
Enumerator
Normal
Construction
Definition at line 49 of file GeometryCreationMode.h.
SelType
enum SketcherGui::SelType
The SelType enum Types of sketch elements that can be (pre)selected. The root/origin and the axes are put up separately so that they can be specifically disallowed, for example, when in lock, horizontal, or vertical constraint modes.
Enumerator
SelUnknown
SelVertex
SelVertexOrRoot
SelRoot
SelEdge
SelEdgeOrAxis
SelHAxis
SelVAxis
SelExternalEdge
Definition at line 891 of file CommandConstraints.cpp.
SubElementType
enum SketcherGui::SubElementType strong
Enumerator
edge
start
end
mid
none
Definition at line 51 of file TaskSketcherElements.h.
Function Documentation
ActivateHandler()
void SketcherGui::ActivateHandler (Gui::Document * doc, std::unique_ptr< DrawSketchHandler > handler)
Definition at line 478 of file Sketcher/Gui/Utils.cpp.
References SketcherGui::ViewProviderSketch::activateHandler(), toolbit-attributes::doc, Base::Persistence::getClassTypeId(), buildPsets::handler, Path.Post.scripts.opensbp_post::move(), and SketcherGui::ViewProviderSketch::purgeHandler().
Referenced by SketcherCopy::activate(), CmdSketcherConstraint::activated(), CmdSketcherConstrainLock::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadiam::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), horVerActivated(), and CmdSketcherConstrainCoincidentUnified::onActivated().
addSketcherWorkbenchBSplines() [1/2]
SketcherGuiExport void SketcherGui::addSketcherWorkbenchBSplines (Gui::MenuItem & bspline)
Definition at line 671 of file Mod/Sketcher/Gui/Workbench.cpp.
References SketcherAddWorkbenchBSplines().
Referenced by SketcherGui::Workbench::setupMenuBar(), and SketcherGui::Workbench::setupToolBars().
addSketcherWorkbenchBSplines() [2/2]
SketcherGuiExport void SketcherGui::addSketcherWorkbenchBSplines (Gui::ToolBarItem & bspline)
Definition at line 706 of file Mod/Sketcher/Gui/Workbench.cpp.
References SketcherAddWorkbenchBSplines().
addSketcherWorkbenchConstraints() [1/2]
SketcherGuiExport void SketcherGui::addSketcherWorkbenchConstraints (Gui::MenuItem & cons)
Definition at line 661 of file Mod/Sketcher/Gui/Workbench.cpp.
References SketcherAddWorkbenchConstraints().
Referenced by SketcherGui::Workbench::setupMenuBar(), and SketcherGui::Workbench::setupToolBars().
addSketcherWorkbenchConstraints() [2/2]
SketcherGuiExport void SketcherGui::addSketcherWorkbenchConstraints (Gui::ToolBarItem & cons)
Definition at line 696 of file Mod/Sketcher/Gui/Workbench.cpp.
References SketcherAddWorkbenchConstraints().
addSketcherWorkbenchEditTools()
SketcherGuiExport void SketcherGui::addSketcherWorkbenchEditTools (Gui::ToolBarItem & edittools)
Definition at line 716 of file Mod/Sketcher/Gui/Workbench.cpp.
References SketcherAddWorkbenchEditTools().
Referenced by SketcherGui::Workbench::setupToolBars().
addSketcherWorkbenchGeometries() [1/2]
SketcherGuiExport void SketcherGui::addSketcherWorkbenchGeometries (Gui::MenuItem & geom)
Definition at line 656 of file Mod/Sketcher/Gui/Workbench.cpp.
References SketcherAddWorkbenchGeometries().
Referenced by SketcherGui::Workbench::setupMenuBar(), and SketcherGui::Workbench::setupToolBars().
addSketcherWorkbenchGeometries() [2/2]
SketcherGuiExport void SketcherGui::addSketcherWorkbenchGeometries (Gui::ToolBarItem & geom)
Definition at line 691 of file Mod/Sketcher/Gui/Workbench.cpp.
References SketcherAddWorkbenchGeometries().
addSketcherWorkbenchSketchActions() [1/2]
SketcherGuiExport void SketcherGui::addSketcherWorkbenchSketchActions (Gui::MenuItem & sketch)
Definition at line 646 of file Mod/Sketcher/Gui/Workbench.cpp.
References SketcherAddWorkbenchSketchActions().
Referenced by SketcherGui::Workbench::setupMenuBar(), and SketcherGui::Workbench::setupToolBars().
addSketcherWorkbenchSketchActions() [2/2]
SketcherGuiExport void SketcherGui::addSketcherWorkbenchSketchActions (Gui::ToolBarItem & sketch)
Definition at line 681 of file Mod/Sketcher/Gui/Workbench.cpp.
References SketcherAddWorkbenchSketchActions().
addSketcherWorkbenchSketchEditModeActions() [1/2]
SketcherGuiExport void SketcherGui::addSketcherWorkbenchSketchEditModeActions (Gui::MenuItem & sketch)
Definition at line 651 of file Mod/Sketcher/Gui/Workbench.cpp.
References SketcherAddWorkbenchSketchEditModeActions().
Referenced by SketcherGui::Workbench::setupMenuBar(), and SketcherGui::Workbench::setupToolBars().
addSketcherWorkbenchSketchEditModeActions() [2/2]
SketcherGuiExport void SketcherGui::addSketcherWorkbenchSketchEditModeActions (Gui::ToolBarItem & sketch)
Definition at line 686 of file Mod/Sketcher/Gui/Workbench.cpp.
References SketcherAddWorkbenchSketchEditModeActions().
addSketcherWorkbenchTools() [1/2]
SketcherGuiExport void SketcherGui::addSketcherWorkbenchTools (Gui::MenuItem & consaccel)
Definition at line 666 of file Mod/Sketcher/Gui/Workbench.cpp.
References SketcherAddWorkbenchTools().
Referenced by SketcherGui::Workbench::setupMenuBar(), and SketcherGui::Workbench::setupToolBars().
addSketcherWorkbenchTools() [2/2]
SketcherGuiExport void SketcherGui::addSketcherWorkbenchTools (Gui::ToolBarItem & consaccel)
Definition at line 701 of file Mod/Sketcher/Gui/Workbench.cpp.
References SketcherAddWorkbenchTools().
addSketcherWorkbenchVisual() [1/2]
SketcherGuiExport void SketcherGui::addSketcherWorkbenchVisual (Gui::MenuItem & visual)
Definition at line 676 of file Mod/Sketcher/Gui/Workbench.cpp.
References SketcherAddWorkbenchVisual().
Referenced by SketcherGui::Workbench::setupMenuBar(), and SketcherGui::Workbench::setupToolBars().
addSketcherWorkbenchVisual() [2/2]
SketcherGuiExport void SketcherGui::addSketcherWorkbenchVisual (Gui::ToolBarItem & visual)
Definition at line 711 of file Mod/Sketcher/Gui/Workbench.cpp.
References SketcherAddWorkbenchVisual().
angleToDisplayFormat()
std::string SketcherGui::angleToDisplayFormat (double value, int digits)
Definition at line 770 of file Sketcher/Gui/Utils.cpp.
References Base::Unit::Angle, Base::Quantity::getUserString(), Base::UnitsApi::isMultiUnitAngle(), src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression, Base::Quantity::setUnit(), Base::Quantity::setValue(), and useSystemDecimals().
Referenced by SketcherGui::DrawSketchHandler::drawDirectionAtCursor(), SketcherGui::DrawSketchHandler::drawDoubleAtCursor(), DrawSketchHandlerCopy::mouseMove(), and DrawSketchHandlerRectangularArray::mouseMove().
areAllPointsOrSegmentsFixed()
bool SketcherGui::areAllPointsOrSegmentsFixed (const Sketcher::SketchObject * Obj, int GeoId1, int GeoId2, int GeoId3)
Definition at line 298 of file Sketcher/Gui/Utils.cpp.
References Sketcher::Block, checkConstraint(), Sketcher::SketchObject::Constraints, Sketcher::GeoUndef, Sketcher::PropertyConstraintList::getValues(), Sketcher::none, and Sketcher::RtPnt.
Referenced by CmdSketcherConstrainSymmetric::activated(), CmdSketcherConstrainSymmetric::applyConstraint(), and DrawSketchHandlerDimension::createSymmetryConstrain().
areBothPointsOrSegmentsFixed()
bool SketcherGui::areBothPointsOrSegmentsFixed (const Sketcher::SketchObject * Obj, int GeoId1, int GeoId2)
Definition at line 281 of file Sketcher/Gui/Utils.cpp.
References Sketcher::Block, checkConstraint(), Sketcher::SketchObject::Constraints, Sketcher::GeoUndef, Sketcher::PropertyConstraintList::getValues(), Sketcher::none, and Sketcher::RtPnt.
Referenced by CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainSymmetric::activated(), CmdSketcherConstrainCoincidentUnified::activatedCoincident(), CmdSketcherConstrainCoincidentUnified::activatedPointOnObject(), CmdSketcherConstrainDistance::applyConstraint(), CmdSketcherConstrainDistanceX::applyConstraint(), CmdSketcherConstrainDistanceY::applyConstraint(), CmdSketcherConstrainParallel::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), CmdSketcherConstrainCoincidentUnified::applyConstraintCoincident(), CmdSketcherConstrainCoincidentUnified::applyConstraintPointOnObject(), DrawSketchHandlerDimension::createCoincidenceConstrain(), DrawSketchHandlerDimension::createEqualityConstrain(), DrawSketchHandlerDimension::createHorizontalConstrain(), DrawSketchHandlerDimension::createSymmetryConstrain(), DrawSketchHandlerDimension::createVerticalConstrain(), DrawSketchHandlerDimension::finishDimensionCreation(), horVerApplyConstraint(), and makeAngleBetweenTwoLines().
areCollinear()
bool SketcherGui::areCollinear (const Base::Vector2d & p1, const Base::Vector2d & p2, const Base::Vector2d & p3)
Definition at line 822 of file Sketcher/Gui/Utils.cpp.
References KDL::abs(), KDL::sqrt(), buildPsets::u, TestSpreadsheet::v, and src.Mod.PartDesign.fcgear.svggear::w.
calculateAngle()
bool SketcherGui::calculateAngle (Sketcher::SketchObject * Obj, int & geoId1, int & geoId2, Sketcher::PointPos & PosId1, Sketcher::PointPos & PosId2, double & ActAngle)
Definition at line 285 of file CommandConstraints.cpp.
References KDL::atan2(), DraftVecUtils::dist(), Base::DistanceP2(), Sketcher::end, Part::GeomLineSegment::getEndPoint(), Sketcher::SketchObject::getGeometry(), Part::GeomLineSegment::getStartPoint(), SplineSurface::i, Base::Line2d::Intersect(), Base::BaseClass::is(), Base::Vector3< float_type >::Length(), toolbit-attributes::s, Sketcher::start, MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by DrawSketchHandlerDimension::createAngleConstrain(), and makeAngleBetweenTwoLines().
checkBothExternal()
bool SketcherGui::checkBothExternal (int GeoId1, int GeoId2)
Definition at line 258 of file Sketcher/Gui/Utils.cpp.
References Sketcher::GeoUndef.
checkConstraint()
bool SketcherGui::checkConstraint (const std::vector< Sketcher::Constraint * > & vals, Sketcher::ConstraintType type, int geoid, Sketcher::PointPos pos)
Checks whether there is a constraint of the given type with a First element geoid and a FirstPos PosId
Definition at line 413 of file Sketcher/Gui/Utils.cpp.
References RobotExample::pos, and Path.Post.scripts.grbl_post::type.
Referenced by CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainBlock::applyConstraint(), areAllPointsOrSegmentsFixed(), areBothPointsOrSegmentsFixed(), and isPointOrSegmentFixed().
ConstraintToAttachment()
void SketcherGui::ConstraintToAttachment (Sketcher::GeoElementId element, Sketcher::GeoElementId attachment, double distance, App::DocumentObject * obj)
Definition at line 631 of file Sketcher/Gui/Utils.cpp.
References Gui::cmdAppObjectArgs(), Sketcher::GeoElementId::GeoId, Sketcher::GeoElementId::HAxis, Sketcher::GeoElementId::isCurve(), Sketcher::GeoElementId::posIdAsInt(), and Sketcher::GeoElementId::VAxis.
constructionModeAsBooleanText()
const char* SketcherGui::constructionModeAsBooleanText () inline
Definition at line 162 of file Sketcher/Gui/Utils.h.
References Sketcher::GeometryMode::Construction, and geometryCreationMode.
Referenced by SketcherGui::DrawSketchHandlerCarbonCopy::releaseButton().
doEndpointTangency()
void SketcherGui::doEndpointTangency (Sketcher::SketchObject * Obj, int GeoId1, int GeoId2, Sketcher::PointPos PosId1, Sketcher::PointPos PosId2)
Does an endpoint-to-endpoint tangency.
Definition at line 714 of file CommandConstraints.cpp.
References Gui::cmdAppObjectArgs(), Sketcher::SketchObject::getGeometry(), and Sketcher::isBSplineCurve().
Referenced by CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainTangent::substituteConstraintCombinations(), and CmdSketcherConstrainCoincidentUnified::substituteConstraintCombinationsCoincident().
doEndpointToEdgeTangency()
void SketcherGui::doEndpointToEdgeTangency (Sketcher::SketchObject * Obj, int GeoId1, Sketcher::PointPos PosId1, int GeoId2)
Does an endpoint-edge tangency.
Definition at line 740 of file CommandConstraints.cpp.
References Gui::cmdAppObjectArgs().
Referenced by CmdSketcherConstrainTangent::substituteConstraintCombinations(), and CmdSketcherConstrainCoincidentUnified::substituteConstraintCombinationsPointOnObject().
GetCirclesMinimalDistance()
void SketcherGui::GetCirclesMinimalDistance (const Part::Geometry * geom1, const Part::Geometry * geom2, Base::Vector3d & point1, Base::Vector3d & point2)
Definition at line 440 of file Sketcher/Gui/Utils.cpp.
References Sketcher::getRadiusCenterCircleArc(), KDL::max(), TestSpreadsheet::v, and Base::Vector3< float_type >::x.
Referenced by SketcherGui::EditModeConstraintCoinManager::processConstraints().
getGeoIdsOfEdgesFromNames()
std::vector< int > SketcherGui::getGeoIdsOfEdgesFromNames (const Sketcher::SketchObject * Obj, const std::vector< std::string > & names)
Returns ONLY the geometry elements when the "Edge" is selected (including GeomPoints)
Definition at line 230 of file Sketcher/Gui/Utils.cpp.
References Sketcher::SketchObject::getGeometry(), Sketcher::SketchObject::getGeoVertexIndex(), Base::BaseClass::is(), femtools.tokrules::names, and Sketcher::RefExt.
getIdsFromName()
void SketcherGui::getIdsFromName (const std::string & name, const Sketcher::SketchObject * Obj, int & GeoId, Sketcher::PointPos & PosId)
Definition at line 200 of file Sketcher/Gui/Utils.cpp.
References Sketcher::GeoUndef, Sketcher::SketchObject::getGeoVertexIndex(), Sketcher::HAxis, Sketcher::none, Sketcher::RefExt, Sketcher::RtPnt, Sketcher::start, and Sketcher::VAxis.
Referenced by CmdSketcherConstrainLock::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), SketcherGui::ViewProviderSketch::generateContextMenu(), DrawSketchHandlerDimension::handleInitialSelection(), horVerActivated(), and CmdSketcherConstrainCoincidentUnified::onActivated().
getInactiveHandlerEditModeSketchViewProvider() [1/2]
SketcherGui::ViewProviderSketch * SketcherGui::getInactiveHandlerEditModeSketchViewProvider ()
Definition at line 548 of file Sketcher/Gui/Utils.cpp.
References Gui::Application::activeDocument(), toolbit-attributes::doc, getInactiveHandlerEditModeSketchViewProvider(), and Gui::Application::Instance.
getInactiveHandlerEditModeSketchViewProvider() [2/2]
SketcherGui::ViewProviderSketch * SketcherGui::getInactiveHandlerEditModeSketchViewProvider (Gui::Document * doc)
Definition at line 539 of file Sketcher/Gui/Utils.cpp.
References toolbit-attributes::doc.
Referenced by getInactiveHandlerEditModeSketchViewProvider(), CmdSketcherGrid::isActive(), and CmdSketcherSnap::isActive().
GetPointAngle()
double SketcherGui::GetPointAngle (const Base::Vector2d & p1, const Base::Vector2d & p2)
Definition at line 431 of file Sketcher/Gui/Utils.cpp.
References KDL::atan2(), M_PI, Base::Vector2d::x, and Base::Vector2d::y.
getStrippedPythonExceptionString()
std::string SketcherGui::getStrippedPythonExceptionString (const Base::Exception & e)
Definition at line 169 of file Sketcher/Gui/Utils.cpp.
References SCL.SimpleDataTypes::e, and Path.Op.Surface::msg.
hideUnits()
bool SketcherGui::hideUnits ()
Definition at line 674 of file Sketcher/Gui/Utils.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by lengthToDisplayFormat().
indexOfGeoId()
int SketcherGui::indexOfGeoId (const std::vector< int > & vec, int elem)
Definition at line 856 of file Sketcher/Gui/Utils.cpp.
References Sketcher::GeoUndef, SplineSurface::i, and SurfaceTests.TestBlendCurve::vec.
initModule()
PyObject* SketcherGui::initModule ()
Definition at line 78 of file AppSketcherGui.cpp.
References Base::InterpreterSingleton::addModule(), and Base::Interpreter().
Referenced by PyMOD_INIT_FUNC().
isBsplineKnot()
bool SketcherGui::isBsplineKnot (const Sketcher::SketchObject * Obj, int GeoId)
Checks if GeoId corresponds to a B-Spline knot.
Definition at line 336 of file Sketcher/Gui/Utils.cpp.
References Sketcher::InternalType::BSplineKnotPoint, and Sketcher::SketchObject::getGeometryFacade().
Referenced by CmdSketcherConstrainTangent::activated(), SketcherGui::SplittingSelection::allow(), isBsplineKnotOrEndPoint(), IsPointAlreadyOnCurve(), and CmdSketcherConstrainCoincidentUnified::substituteConstraintCombinationsCoincident().
isBsplineKnotOrEndPoint()
bool SketcherGui::isBsplineKnotOrEndPoint (const Sketcher::SketchObject * Obj, int GeoId, Sketcher::PointPos PosId)
Checks if the (GeoId, PosId) pair corresponds to a B-Spline knot, including first and last knots
Definition at line 342 of file Sketcher/Gui/Utils.cpp.
References Sketcher::end, Sketcher::SketchObject::getGeometry(), Base::BaseClass::is(), isBsplineKnot(), and Sketcher::start.
Referenced by SketcherGui::ViewProviderSketch::generateContextMenu().
isBsplinePole() [1/2]
bool SketcherGui::isBsplinePole (const Part::Geometry * geo)
Definition at line 394 of file Sketcher/Gui/Utils.cpp.
References Sketcher::BSplineControlPoint, and THROWM.
Referenced by CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadiam::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainCoincidentUnified::activatedPointOnObject(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainRadiam::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), CmdSketcherConstrainCoincidentUnified::applyConstraintPointOnObject(), DrawSketchHandlerDimension::createEqualityConstrain(), DrawSketchHandlerDimension::createRadiusDiameterConstrain(), and isBsplinePole().
isBsplinePole() [2/2]
bool SketcherGui::isBsplinePole (const Sketcher::SketchObject * Obj, int GeoId)
Definition at line 405 of file Sketcher/Gui/Utils.cpp.
References Sketcher::SketchObject::getGeometry(), and isBsplinePole().
isCommandActive()
bool SketcherGui::isCommandActive (Gui::Document * doc, bool actsOnSelection = false)
Returns whether an edit mode command should be activated or not. It is only activated if the sketcher is no special state or a sketchHandler is active.
Definition at line 501 of file Sketcher/Gui/Utils.cpp.
References Gui::SelectionSingleton::countObjectsOfType(), toolbit-attributes::doc, isSketchInEdit(), and Gui::Selection().
isConstructionMode()
bool SketcherGui::isConstructionMode () inline
Definition at line 157 of file Sketcher/Gui/Utils.h.
References Sketcher::GeometryMode::Construction, and geometryCreationMode.
isEdge()
bool SketcherGui::isEdge (int GeoId, Sketcher::PointPos PosId) inline
Definition at line 150 of file Sketcher/Gui/Utils.h.
References Sketcher::GeoUndef, and Sketcher::none.
Referenced by CmdSketcherConstrainLock::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), PartGui::MirrorPlaneSelection::allow(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), DrawSketchHandlerDimension::createSymmetryConstrain(), Part::Mirroring::execute(), DrawSketchHandlerDimension::handleInitialSelection(), horVerActivated(), and CmdSketcherConstrainCoincidentUnified::onActivated().
IsPointAlreadyOnCurve()
bool SketcherGui::IsPointAlreadyOnCurve (int GeoIdCurve, int GeoIdPoint, Sketcher::PointPos PosIdPoint, Sketcher::SketchObject * Obj)
Definition at line 361 of file Sketcher/Gui/Utils.cpp.
References Sketcher::SketchObject::Constraints, Sketcher::SketchObject::getGeometry(), Sketcher::SketchObject::getPoint(), Sketcher::PropertyConstraintList::getValues(), Sketcher::InternalAlignment, Base::BaseClass::is(), isBsplineKnot(), Sketcher::SketchObject::isPointOnCurve(), and buildPsets::p.
Referenced by CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), and CmdSketcherConstrainAngle::applyConstraint().
isPointOrSegmentFixed()
bool SketcherGui::isPointOrSegmentFixed (const Sketcher::SketchObject * Obj, int GeoId)
Definition at line 268 of file Sketcher/Gui/Utils.cpp.
References Sketcher::Block, checkConstraint(), Sketcher::SketchObject::Constraints, Sketcher::GeoUndef, Sketcher::PropertyConstraintList::getValues(), Sketcher::none, and Sketcher::RtPnt.
Referenced by CmdSketcherConstrainLock::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadiam::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainLock::applyConstraint(), CmdSketcherConstrainDistance::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainRadiam::applyConstraint(), DrawSketchHandlerDimension::finishDimensionCreation(), and horVerActivated().
isSimpleVertex()
bool SketcherGui::isSimpleVertex (const Sketcher::SketchObject * Obj, int GeoId, Sketcher::PointPos PosId)
Definition at line 318 of file Sketcher/Gui/Utils.cpp.
References Sketcher::SketchObject::getGeometry(), Sketcher::HAxis, Base::BaseClass::is(), Sketcher::mid, Sketcher::start, and Sketcher::VAxis.
Referenced by CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), and CmdSketcherConstrainTangent::applyConstraint().
isSketcherBSplineActive()
bool SketcherGui::isSketcherBSplineActive (Gui::Document * doc, bool actsOnSelection)
Definition at line 520 of file Sketcher/Gui/Utils.cpp.
References Gui::SelectionSingleton::countObjectsOfType(), toolbit-attributes::doc, Base::Persistence::getClassTypeId(), SketcherGui::ViewProviderSketch::getSketchMode(), and Gui::Selection().
isSketchInEdit()
bool SketcherGui::isSketchInEdit (Gui::Document * doc)
Returns if a sketch is in edit mode.
Definition at line 491 of file Sketcher/Gui/Utils.cpp.
References toolbit-attributes::doc.
Referenced by SketcherGui::Workbench::activated(), CmdRenderingOrder::isActive(), and isCommandActive().
isVertex()
bool SketcherGui::isVertex (int GeoId, Sketcher::PointPos PosId) inline
Definition at line 145 of file Sketcher/Gui/Utils.h.
References Sketcher::GeoUndef, and Sketcher::none.
Referenced by CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainSymmetric::activated(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), DrawSketchHandlerDimension::createSymmetryConstrain(), DrawSketchHandlerDimension::handleInitialSelection(), horVerActivated(), and CmdSketcherConstrainCoincidentUnified::onActivated().
lengthToDisplayFormat()
std::string SketcherGui::lengthToDisplayFormat (double value, int digits)
Definition at line 710 of file Sketcher/Gui/Utils.cpp.
References Base::Quantity::getUserString(), hideUnits(), Base::UnitsApi::isMultiUnitLength(), Base::Unit::Length, src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression, Base::UnitsApi::schemaTranslate(), Base::Quantity::setUnit(), Base::Quantity::setValue(), and useSystemDecimals().
Referenced by SketcherGui::DrawSketchHandler::drawDirectionAtCursor(), SketcherGui::DrawSketchHandler::drawDoubleAtCursor(), SketcherGui::DrawSketchHandler::drawWidthHeightAtCursor(), SketcherGui::DrawSketchHandlerArcOfEllipse::mouseMove(), DrawSketchHandlerCopy::mouseMove(), DrawSketchHandlerRectangularArray::mouseMove(), and SketcherGui::EditModeCoinManager::setPositionText().
makeAngleBetweenTwoLines()
void SketcherGui::makeAngleBetweenTwoLines (Sketcher::SketchObject * Obj, Gui::Command * cmd, int geoId1, int geoId2)
Makes an angle constraint between 2 lines.
Definition at line 241 of file CommandConstraints.cpp.
References areBothPointsOrSegmentsFixed(), calculateAngle(), Gui::cmdAppObjectArgs(), constraintCreationMode, Sketcher::SketchObject::Constraints, finishDatumConstraint(), Sketcher::PropertyConstraintList::getValues(), Sketcher::none, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, Reference, and Gui::TranslatedUserWarning().
Referenced by CmdSketcherConstrainAngle::activated(), and CmdSketcherConstrainAngle::applyConstraint().
makeTangentToArcOfEllipseviaNewPoint()
void SketcherGui::makeTangentToArcOfEllipseviaNewPoint (Sketcher::SketchObject * Obj, const Part::GeomArcOfEllipse * aoe, const Part::Geometry * geom2, int geoId1, int geoId2)
Makes a tangency constraint using external construction line between aoe => an arc of ellipse geom2 => any of an arc of ellipse, a circle, or an arc (of circle) geoId1 => geoid of the arc of ellipse geoId2 => geoid of geom2 NOTE: A command must be opened before calling this function, which this function commits or aborts as appropriate. The reason is for compatibility reasons with other code e.g. "Autoconstraints" in DrawSketchHandler.cpp
Makes a simple tangency constraint using extra point + tangent via point aoe => an arc of ellipse geom2 => any of an arc of ellipse, a circle, or an arc (of circle) geoId1 => geoid of the arc of ellipse geoId2 => geoid of geom2 NOTE: A command must be opened before calling this function, which this function commits or aborts as appropriate. The reason is for compatibility reasons with other code e.g. "Autoconstraints" in DrawSketchHandler.cpp
Definition at line 454 of file CommandConstraints.cpp.
References Gui::Command::abortCommand(), KDL::atan2(), exportCSG::center(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), KDL::cos(), SCL.SimpleDataTypes::e, Part::GeomArcOfConic::getCenter(), Sketcher::SketchObject::getHighestCurveIndex(), Part::GeomArcOfEllipse::getMajorAxisDir(), Part::GeomArcOfEllipse::getMajorRadius(), Part::GeomArcOfEllipse::getMinorRadius(), Sketcher::isArcOfCircle(), Sketcher::isArcOfEllipse(), TechDraw::isCircle, Gui::NotifyUserError(), Arch::QT_TRANSLATE_NOOP, KDL::sin(), Sketcher::start, tryAutoRecompute(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by CmdSketcherConstrainTangent::activated(), and SketcherGui::DrawSketchHandler::createAutoConstraints().
makeTangentToArcOfHyperbolaviaNewPoint()
void SketcherGui::makeTangentToArcOfHyperbolaviaNewPoint (Sketcher::SketchObject * Obj, const Part::GeomArcOfHyperbola * aoh, const Part::Geometry * geom2, int geoId1, int geoId2)
Makes a tangency constraint using external construction line between aoh => an arc of hyperbola geom2 => any of an arc of hyperbola, an arc of ellipse, a circle, or an arc (of circle) geoId1 => geoid of the arc of hyperbola geoId2 => geoid of geom2 NOTE: A command must be opened before calling this function, which this function commits or aborts as appropriate. The reason is for compatibility reasons with other code e.g. "Autoconstraints" in DrawSketchHandler.cpp
Makes a simple tangency constraint using extra point + tangent via point aoh => an arc of hyperbola geom2 => any of an arc of hyperbola, an arc of ellipse, a circle, or an arc (of circle) geoId1 => geoid of the arc of hyperbola geoId2 => geoid of geom2 NOTE: A command must be opened before calling this function, which this function commits or aborts as appropriate. The reason is for compatibility reasons with other code e.g. "Autoconstraints" in DrawSketchHandler.cpp
Definition at line 534 of file CommandConstraints.cpp.
References Gui::Command::abortCommand(), KDL::atan2(), exportCSG::center(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), KDL::cos(), KDL::cosh(), SCL.SimpleDataTypes::e, Part::GeomArcOfConic::getCenter(), Sketcher::SketchObject::getHighestCurveIndex(), Part::GeomArcOfHyperbola::getMajorAxisDir(), Part::GeomArcOfHyperbola::getMajorRadius(), Part::GeomArcOfHyperbola::getMinorRadius(), Sketcher::isArcOfCircle(), Sketcher::isArcOfEllipse(), Sketcher::isArcOfHyperbola(), TechDraw::isCircle, TechDraw::isEllipse, Sketcher::isLineSegment(), src.Mod.PartDesign.Scripts.Gear::l2, Gui::NotifyUserError(), Arch::QT_TRANSLATE_NOOP, KDL::sin(), KDL::sinh(), KDL::sqrt(), Sketcher::start, tryAutoRecompute(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by CmdSketcherConstrainTangent::activated(), and CmdSketcherConstrainTangent::applyConstraint().
makeTangentToArcOfParabolaviaNewPoint()
void SketcherGui::makeTangentToArcOfParabolaviaNewPoint (Sketcher::SketchObject * Obj, const Part::GeomArcOfParabola * aop, const Part::Geometry * geom2, int geoId1, int geoId2)
Makes a simple tangency constraint using extra point + tangent via point aop => an arc of parabola geom2 => any of an arc of parabola, an arc of hyperbola an arc of ellipse, a circle, or an arc (of circle) geoId1 => geoid of the arc of parabola geoId2 => geoid of geom2 NOTE: A command must be opened before calling this function, which this function commits or aborts as appropriate. The reason is for compatibility reasons with other code e.g. "Autoconstraints" in DrawSketchHandler.cpp
Definition at line 631 of file CommandConstraints.cpp.
References Gui::Command::abortCommand(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), SCL.SimpleDataTypes::e, Part::GeomArcOfParabola::getFocus(), Sketcher::SketchObject::getHighestCurveIndex(), Sketcher::isArcOfCircle(), Sketcher::isArcOfEllipse(), Sketcher::isArcOfHyperbola(), Sketcher::isArcOfParabola(), TechDraw::isCircle, TechDraw::isEllipse, Sketcher::isLineSegment(), src.Mod.PartDesign.Scripts.Gear::l2, Gui::NotifyUserError(), Arch::QT_TRANSLATE_NOOP, KDL::sqrt(), Sketcher::start, tryAutoRecompute(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by CmdSketcherConstrainTangent::activated(), and CmdSketcherConstrainTangent::applyConstraint().
makeTangentToEllipseviaNewPoint()
void SketcherGui::makeTangentToEllipseviaNewPoint (Sketcher::SketchObject * Obj, const Part::GeomEllipse * ellipse, const Part::Geometry * geom2, int geoId1, int geoId2)
Makes a tangency constraint using external construction line between ellipse => an ellipse geom2 => any of an ellipse, an arc of ellipse, a circle, or an arc (of circle) geoId1 => geoid of the ellipse geoId2 => geoid of geom2 NOTE: A command must be opened before calling this function, which this function commits or aborts as appropriate. The reason is for compatibility reasons with other code e.g. "Autoconstraints" in DrawSketchHandler.cpp
Makes a simple tangency constraint using extra point + tangent via point ellipse => an ellipse geom2 => any of an ellipse, an arc of ellipse, a circle, or an arc (of circle) geoId1 => geoid of the ellipse geoId2 => geoid of geom2 NOTE: A command must be opened before calling this function, which this function commits or aborts as appropriate. The reason is for compatibility reasons with other code e.g. "Autoconstraints" in DrawSketchHandler.cpp
Definition at line 371 of file CommandConstraints.cpp.
References Gui::Command::abortCommand(), KDL::atan2(), exportCSG::center(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), KDL::cos(), SCL.SimpleDataTypes::e, Sketcher::SketchObject::getHighestCurveIndex(), Sketcher::isArcOfCircle(), Sketcher::isArcOfEllipse(), TechDraw::isCircle, TechDraw::isEllipse, Gui::NotifyUserError(), Arch::QT_TRANSLATE_NOOP, KDL::sin(), Sketcher::start, tryAutoRecompute(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainTangent::applyConstraint(), and SketcherGui::DrawSketchHandler::createAutoConstraints().
notifyConstraintSubstitutions()
void SketcherGui::notifyConstraintSubstitutions (const QString & message)
shows constraint substitution information dialog box, enabling the user to forgo further notifications
Definition at line 752 of file CommandConstraints.cpp.
References Gui::Dialog::DlgCheckableMessageBox::showMessage().
Referenced by removeRedundantPointOnObject(), CmdSketcherConstrainTangent::substituteConstraintCombinations(), CmdSketcherConstrainCoincidentUnified::substituteConstraintCombinationsCoincident(), and CmdSketcherConstrainCoincidentUnified::substituteConstraintCombinationsPointOnObject().
operator==()
bool SketcherGui::operator== (VisualLayer const & lhs, VisualLayer const & rhs)
Definition at line 70 of file VisualLayer.h.
ReleaseHandler()
bool SketcherGui::ReleaseHandler (Gui::Document * doc)
Release any currently-active handler for the document. Returns true if a handler was released, and false if not
Definition at line 181 of file Sketcher/Gui/Utils.cpp.
References toolbit-attributes::doc, Base::Persistence::getClassTypeId(), SketcherGui::ViewProviderSketch::getSketchMode(), and SketcherGui::ViewProviderSketch::purgeHandler().
Referenced by SketcherGui::ConstraintView::contextMenuEvent(), and getSketchObject().
removeRedundantHorizontalVertical()
void SketcherGui::removeRedundantHorizontalVertical (Sketcher::SketchObject * psketch, std::vector< AutoConstraint > & sug1, std::vector< AutoConstraint > & sug2)
Definition at line 555 of file Sketcher/Gui/Utils.cpp.
References Sketcher::Coincident, create_qrc::ext, Sketcher::SketchObject::getAllCoincidentPoints(), Sketcher::Horizontal, Sketcher::none, Sketcher::PointOnObject, Sketcher::start, and Sketcher::Vertical.
showCursorCoords()
bool SketcherGui::showCursorCoords ()
Definition at line 684 of file Sketcher/Gui/Utils.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by SketcherGui::DrawSketchHandler::drawDirectionAtCursor(), SketcherGui::DrawSketchHandler::drawDoubleAtCursor(), SketcherGui::DrawSketchHandler::drawWidthHeightAtCursor(), DrawSketchHandlerCopy::mouseMove(), DrawSketchHandlerRectangularArray::mouseMove(), and SketcherGui::EditModeCoinManager::setPositionText().
SketcherAddWorkbenchBSplines()
template<typename T > void SketcherGui::SketcherAddWorkbenchBSplines (T & bspline) inline
Referenced by addSketcherWorkbenchBSplines().
SketcherAddWorkbenchBSplines< Gui::MenuItem >()
template<> void SketcherGui::SketcherAddWorkbenchBSplines< Gui::MenuItem > (Gui::MenuItem & bspline) inline
Definition at line 583 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkbenchBSplines< Gui::ToolBarItem >()
template<> void SketcherGui::SketcherAddWorkbenchBSplines< Gui::ToolBarItem > (Gui::ToolBarItem & bspline) inline
Definition at line 595 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkbenchConstraints()
template<typename T > void SketcherGui::SketcherAddWorkbenchConstraints (T & cons) inline
Referenced by addSketcherWorkbenchConstraints().
SketcherAddWorkbenchConstraints< Gui::MenuItem >()
template<> void SketcherGui::SketcherAddWorkbenchConstraints< Gui::MenuItem > (Gui::MenuItem & cons) inline
Definition at line 441 of file Mod/Sketcher/Gui/Workbench.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), and App::Application::GetParameterGroupByPath().
SketcherAddWorkbenchConstraints< Gui::ToolBarItem >()
template<> void SketcherGui::SketcherAddWorkbenchConstraints< Gui::ToolBarItem > (Gui::ToolBarItem & cons) inline
Definition at line 479 of file Mod/Sketcher/Gui/Workbench.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), and App::Application::GetParameterGroupByPath().
SketcherAddWorkbenchEditTools()
template<typename T > void SketcherGui::SketcherAddWorkbenchEditTools (T & virtualspedittoolsace) inline
Referenced by addSketcherWorkbenchEditTools().
SketcherAddWorkbenchEditTools< Gui::ToolBarItem >()
template<> void SketcherGui::SketcherAddWorkbenchEditTools< Gui::ToolBarItem > (Gui::ToolBarItem & edittools) inline
Definition at line 639 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkbenchGeometries()
template<typename T > void SketcherGui::SketcherAddWorkbenchGeometries (T & geom) inline
Definition at line 423 of file Mod/Sketcher/Gui/Workbench.cpp.
References SketcherAddWorkspaceArcs(), SketcherAddWorkspaceLines(), SketcherAddWorkspaceRectangles(), SketcherAddWorkspaceRegularPolygon(), and SketcherAddWorkspaceslots().
Referenced by addSketcherWorkbenchGeometries().
SketcherAddWorkbenchSketchActions() [1/3]
template<> void SketcherGui::SketcherAddWorkbenchSketchActions (Gui::MenuItem & sketch) inline
Definition at line 244 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkbenchSketchActions() [2/3]
template<> void SketcherGui::SketcherAddWorkbenchSketchActions (Gui::ToolBarItem & sketch) inline
Definition at line 255 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkbenchSketchActions() [3/3]
template<typename T > void SketcherGui::SketcherAddWorkbenchSketchActions (T & sketch)
Referenced by addSketcherWorkbenchSketchActions().
SketcherAddWorkbenchSketchEditModeActions() [1/3]
template<> void SketcherGui::SketcherAddWorkbenchSketchEditModeActions (Gui::MenuItem & sketch) inline
Definition at line 270 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkbenchSketchEditModeActions() [2/3]
template<> void SketcherGui::SketcherAddWorkbenchSketchEditModeActions (Gui::ToolBarItem & sketch) inline
Definition at line 278 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkbenchSketchEditModeActions() [3/3]
template<typename T > void SketcherGui::SketcherAddWorkbenchSketchEditModeActions (T & sketch)
Referenced by addSketcherWorkbenchSketchEditModeActions().
SketcherAddWorkbenchTools()
template<typename T > void SketcherGui::SketcherAddWorkbenchTools (T & consaccel) inline
Referenced by addSketcherWorkbenchTools().
SketcherAddWorkbenchTools< Gui::MenuItem >()
template<> void SketcherGui::SketcherAddWorkbenchTools< Gui::MenuItem > (Gui::MenuItem & consaccel) inline
Definition at line 536 of file Mod/Sketcher/Gui/Workbench.cpp.
References SketcherAddWorkspaceCurveEdition(), and SketcherAddWorkspaceFillets().
SketcherAddWorkbenchTools< Gui::ToolBarItem >()
template<> void SketcherGui::SketcherAddWorkbenchTools< Gui::ToolBarItem > (Gui::ToolBarItem & consaccel) inline
Definition at line 564 of file Mod/Sketcher/Gui/Workbench.cpp.
References SketcherAddWorkspaceCurveEdition(), and SketcherAddWorkspaceFillets().
SketcherAddWorkbenchVisual()
template<typename T > void SketcherGui::SketcherAddWorkbenchVisual (T & visual) inline
Referenced by addSketcherWorkbenchVisual().
SketcherAddWorkbenchVisual< Gui::MenuItem >()
template<> void SketcherGui::SketcherAddWorkbenchVisual< Gui::MenuItem > (Gui::MenuItem & visual) inline
Definition at line 609 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkbenchVisual< Gui::ToolBarItem >()
template<> void SketcherGui::SketcherAddWorkbenchVisual< Gui::ToolBarItem > (Gui::ToolBarItem & visual) inline
Definition at line 624 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkspaceArcs()
template<typename T > void SketcherGui::SketcherAddWorkspaceArcs (T & geom)
Referenced by SketcherAddWorkbenchGeometries().
SketcherAddWorkspaceArcs< Gui::MenuItem >()
template<> void SketcherGui::SketcherAddWorkspaceArcs< Gui::MenuItem > (Gui::MenuItem & geom) inline
Definition at line 309 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkspaceArcs< Gui::ToolBarItem >()
template<> void SketcherGui::SketcherAddWorkspaceArcs< Gui::ToolBarItem > (Gui::ToolBarItem & geom) inline
Definition at line 323 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkspaceCurveEdition()
template<typename T > void SketcherGui::SketcherAddWorkspaceCurveEdition (T & geom)
Referenced by SketcherAddWorkbenchTools< Gui::MenuItem >(), and SketcherAddWorkbenchTools< Gui::ToolBarItem >().
SketcherAddWorkspaceCurveEdition< Gui::MenuItem >()
template<> void SketcherGui::SketcherAddWorkspaceCurveEdition< Gui::MenuItem > (Gui::MenuItem & geom) inline
Definition at line 409 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkspaceCurveEdition< Gui::ToolBarItem >()
template<> void SketcherGui::SketcherAddWorkspaceCurveEdition< Gui::ToolBarItem > (Gui::ToolBarItem & geom) inline
Definition at line 417 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkspaceFillets()
template<typename T > void SketcherGui::SketcherAddWorkspaceFillets (T & geom)
Referenced by SketcherAddWorkbenchTools< Gui::MenuItem >(), and SketcherAddWorkbenchTools< Gui::ToolBarItem >().
SketcherAddWorkspaceFillets< Gui::MenuItem >()
template<> void SketcherGui::SketcherAddWorkspaceFillets< Gui::MenuItem > (Gui::MenuItem & geom) inline
Definition at line 393 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkspaceFillets< Gui::ToolBarItem >()
template<> void SketcherGui::SketcherAddWorkspaceFillets< Gui::ToolBarItem > (Gui::ToolBarItem & geom) inline
Definition at line 400 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkspaceLines()
template<typename T > void SketcherGui::SketcherAddWorkspaceLines (T & geom)
Referenced by SketcherAddWorkbenchGeometries().
SketcherAddWorkspaceLines< Gui::MenuItem >()
template<> void SketcherGui::SketcherAddWorkspaceLines< Gui::MenuItem > (Gui::MenuItem & geom) inline
Definition at line 292 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkspaceLines< Gui::ToolBarItem >()
template<> void SketcherGui::SketcherAddWorkspaceLines< Gui::ToolBarItem > (Gui::ToolBarItem & geom) inline
Definition at line 299 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkspaceRectangles()
template<typename T > void SketcherGui::SketcherAddWorkspaceRectangles (T & geom)
Referenced by SketcherAddWorkbenchGeometries().
SketcherAddWorkspaceRectangles< Gui::MenuItem >()
template<> void SketcherGui::SketcherAddWorkspaceRectangles< Gui::MenuItem > (Gui::MenuItem & geom) inline
Definition at line 354 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkspaceRectangles< Gui::ToolBarItem >()
template<> void SketcherGui::SketcherAddWorkspaceRectangles< Gui::ToolBarItem > (Gui::ToolBarItem & geom) inline
Definition at line 362 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkspaceRegularPolygon()
template<typename T > void SketcherGui::SketcherAddWorkspaceRegularPolygon (T & geom)
Referenced by SketcherAddWorkbenchGeometries().
SketcherAddWorkspaceRegularPolygon< Gui::MenuItem >()
template<> void SketcherGui::SketcherAddWorkspaceRegularPolygon< Gui::MenuItem > (Gui::MenuItem & geom) inline
Definition at line 333 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkspaceRegularPolygon< Gui::ToolBarItem >()
template<> void SketcherGui::SketcherAddWorkspaceRegularPolygon< Gui::ToolBarItem > (Gui::ToolBarItem & geom) inline
Definition at line 345 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkspaceslots()
template<typename T > void SketcherGui::SketcherAddWorkspaceslots (T & geom)
Referenced by SketcherAddWorkbenchGeometries().
SketcherAddWorkspaceslots< Gui::MenuItem >()
template<> void SketcherGui::SketcherAddWorkspaceslots< Gui::MenuItem > (Gui::MenuItem & geom) inline
Definition at line 371 of file Mod/Sketcher/Gui/Workbench.cpp.
SketcherAddWorkspaceslots< Gui::ToolBarItem >()
template<> void SketcherGui::SketcherAddWorkspaceslots< Gui::ToolBarItem > (Gui::ToolBarItem & geom) inline
Definition at line 382 of file Mod/Sketcher/Gui/Workbench.cpp.
SuggestAutoMapMode()
Attacher::eMapMode SketcherGui::SuggestAutoMapMode (Attacher::SuggestResult::eSuggestResult * pMsgId = nullptr, QString * message = nullptr, std::vector< Attacher::eMapMode > * allmodes = nullptr)
Definition at line 94 of file Mod/Sketcher/Gui/Command.cpp.
References Attacher::SuggestResult::allApplicableModes, Attacher::SuggestResult::bestFitMode, Gui::SelectionSingleton::getAsPropertyLinkSubList(), App::PropertyLinkSubList::getSubValues(), Attacher::SuggestResult::message, Path.Op.Surface::msg, Gui::Selection(), Attacher::AttachEngine::setUp(), Attacher::SuggestResult::srIncompatibleGeometry, Attacher::SuggestResult::srLinkBroken, Attacher::SuggestResult::srNoModesFit, Attacher::SuggestResult::srOK, Attacher::SuggestResult::srUnexpectedError, and Attacher::AttachEngine::suggestMapModes().
tryAutoRecompute() [1/2]
bool SketcherGui::tryAutoRecompute (Sketcher::SketchObject * obj)
This function tries to auto-recompute the active document if the option is set in the user parameter. If the option is not set nothing will be done
Returns
true if a recompute was undertaken, false if not.
Definition at line 149 of file Sketcher/Gui/Utils.cpp.
Referenced by CmdSketcherConstrainLock::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), CmdSketcherConstrainCoincidentUnified::activatedCoincident(), addConstraintSafely(), CmdSketcherConstrainBlock::applyConstraint(), CmdSketcherConstrainParallel::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), CmdSketcherConstrainCoincidentUnified::applyConstraintCoincident(), CmdSketcherConstrainCoincidentUnified::applyConstraintPointOnObject(), DrawSketchHandlerDimension::createBlockConstrain(), DrawSketchHandlerDimension::createHorizontalConstrain(), DrawSketchHandlerDimension::createSymmetryConstrain(), DrawSketchHandlerDimension::createVerticalConstrain(), finishDatumConstraint(), horVerActivated(), horVerApplyConstraint(), makeTangentToArcOfEllipseviaNewPoint(), makeTangentToArcOfHyperbolaviaNewPoint(), makeTangentToArcOfParabolaviaNewPoint(), makeTangentToEllipseviaNewPoint(), and tryAutoRecomputeIfNotSolve().
tryAutoRecompute() [2/2]
bool SketcherGui::tryAutoRecompute (Sketcher::SketchObject * obj, bool & autoremoveredundants)
Same as the other overload, but also returns whether redundants shall be removed or not.
Definition at line 123 of file Sketcher/Gui/Utils.cpp.
References Sketcher::SketchObject::autoRemoveRedundants(), App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), Sketcher::SketchObject::solve(), and Gui::Command::updateActive().
tryAutoRecomputeIfNotSolve()
void SketcherGui::tryAutoRecomputeIfNotSolve (Sketcher::SketchObject * obj)
This function tries to auto-recompute as tryAutoRecompute. If tryAutoRecompute is not enabled, then it solves the SketchObject.
Definition at line 156 of file Sketcher/Gui/Utils.cpp.
References Sketcher::SketchObject::autoRemoveRedundants(), Sketcher::SketchObject::solve(), and tryAutoRecompute().
Referenced by CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadiam::activated(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainRadiam::applyConstraint(), SketcherGui::ViewProviderSketch::mouseButtonPressed(), DrawSketchHandlerBSplineInsertKnot::releaseButton(), DrawSketchHandlerCopy::releaseButton(), DrawSketchHandlerRectangularArray::releaseButton(), removeRedundantPointOnObject(), and CmdSketcherConstrainTangent::substituteConstraintCombinations().
useSystemDecimals()
bool SketcherGui::useSystemDecimals ()
Definition at line 694 of file Sketcher/Gui/Utils.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by angleToDisplayFormat(), and lengthToDisplayFormat().
Variable Documentation
geometryCreationMode
GeometryCreationMode SketcherGui::geometryCreationMode = GeometryCreationMode::Normal
Definition at line 99 of file CommandCreateGeo.cpp.
Referenced by constructionModeAsBooleanText(), and isConstructionMode().