FreeCAD: Wm4::Quaternion< Real > Class Template Reference
Wm4::Quaternion< Real > Class Template Reference
#include <Wm4Quaternion.h>
Classes
class Constraints
Public Member Functions
Quaternion ()
Quaternion (Real fW, Real fX, Real fY, Real fZ)
Quaternion (const Quaternion &rkQ)
Quaternion (const Matrix3< Real > &rkRot)
Quaternion (const Vector3< Real > &rkAxis, Real fAngle)
Quaternion (const Vector3< Real > akRotColumn[3])
operator const Real * () const
operator Real * ()
Real operator[] (int i) const
Real & operator[] (int i)
Real W () const
Real & W ()
Real X () const
Real & X ()
Real Y () const
Real & Y ()
Real Z () const
Real & Z ()
Quaternion & operator= (const Quaternion &rkQ)
bool operator== (const Quaternion &rkQ) const
bool operator!= (const Quaternion &rkQ) const
bool operator< (const Quaternion &rkQ) const
bool operator<= (const Quaternion &rkQ) const
bool operator> (const Quaternion &rkQ) const
bool operator>= (const Quaternion &rkQ) const
Quaternion operator+ (const Quaternion &rkQ) const
Quaternion operator- (const Quaternion &rkQ) const
Quaternion operator* (const Quaternion &rkQ) const
Quaternion operator* (Real fScalar) const
Quaternion operator/ (Real fScalar) const
Quaternion operator- () const
Quaternion & operator+= (const Quaternion &rkQ)
Quaternion & operator-= (const Quaternion &rkQ)
Quaternion & operator*= (Real fScalar)
Quaternion & operator/= (Real fScalar)
Quaternion & FromRotationMatrix (const Matrix3< Real > &rkRot)
void ToRotationMatrix (Matrix3< Real > &rkRot) const
Quaternion & FromRotationMatrix (const Vector3< Real > akRotColumn[3])
void ToRotationMatrix (Vector3< Real > akRotColumn[3]) const
Quaternion & FromAxisAngle (const Vector3< Real > &rkAxis, Real fAngle)
void ToAxisAngle (Vector3< Real > &rkAxis, Real &rfAngle) const
Real Length () const
Real SquaredLength () const
Real Dot (const Quaternion &rkQ) const
Real Normalize ()
Quaternion Inverse () const
Quaternion Conjugate () const
Quaternion Exp () const
Quaternion Log () const
Vector3< Real > Rotate (const Vector3< Real > &rkVector) const
Quaternion & Slerp (Real fT, const Quaternion &rkP, const Quaternion &rkQ)
Quaternion & SlerpExtraSpins (Real fT, const Quaternion &rkP, const Quaternion &rkQ, int iExtraSpins)
Quaternion & Intermediate (const Quaternion &rkQ0, const Quaternion &rkQ1, const Quaternion &rkQ2)
Quaternion & Squad (Real fT, const Quaternion &rkQ0, const Quaternion &rkA0, const Quaternion &rkA1, const Quaternion &rkQ1)
Quaternion & Align (const Vector3< Real > &rkV1, const Vector3< Real > &rkV2)
void DecomposeTwistTimesSwing (const Vector3< Real > &rkV1, Quaternion &rkTwist, Quaternion &rkSwing)
void DecomposeSwingTimesTwist (const Vector3< Real > &rkV1, Quaternion &rkSwing, Quaternion &rkTwist)
Quaternion GetClosestX () const
Quaternion GetClosestY () const
Quaternion GetClosestZ () const
Quaternion GetClosestXY () const
Quaternion GetClosestYX () const
Quaternion GetClosestZX () const
Quaternion GetClosestXZ () const
Quaternion GetClosestYZ () const
Quaternion GetClosestZY () const
void FactorXYZ (Real &rfCx, Real &rfSx, Real &rfCy, Real &rfSy, Real &rfCz, Real &rfSz)
void FactorXZY (Real &rfCx, Real &rfSx, Real &rfCz, Real &rfSz, Real &rfCy, Real &rfSy)
void FactorYZX (Real &rfCy, Real &rfSy, Real &rfCz, Real &rfSz, Real &rfCx, Real &rfSx)
void FactorYXZ (Real &rfCy, Real &rfSy, Real &rfCx, Real &rfSx, Real &rfCz, Real &rfSz)
void FactorZXY (Real &rfCz, Real &rfSz, Real &rfCx, Real &rfSx, Real &rfCy, Real &rfSy)
void FactorZYX (Real &rfCz, Real &rfSz, Real &rfCy, Real &rfSy, Real &rfCx, Real &rfSx)
Quaternion GetClosestX (const Constraints &rkXCon) const
Quaternion GetClosestY (const Constraints &rkYCon) const
Quaternion GetClosestZ (const Constraints &rkZCon) const
Quaternion GetClosestXY (const Constraints &rkXCon, const Constraints &rkYCon) const
Quaternion GetClosestYX (const Constraints &rkYCon, const Constraints &rkXCon) const
Quaternion GetClosestZX (const Constraints &rkZCon, const Constraints &rkXCon) const
Quaternion GetClosestXZ (const Constraints &rkXCon, const Constraints &rkZCon) const
Quaternion GetClosestZY (const Constraints &rkZCon, const Constraints &rkYCon) const
Quaternion GetClosestYZ (const Constraints &rkYCon, const Constraints &rkZCon) const
const Quaternion< float > IDENTITY (1.0f, 0.0f, 0.0f, 0.0f)
const Quaternion< float > ZERO (0.0f, 0.0f, 0.0f, 0.0f)
const Quaternion< double > IDENTITY (1.0, 0.0, 0.0, 0.0)
const Quaternion< double > ZERO (0.0, 0.0, 0.0, 0.0)
Static Public Attributes
static const Quaternion IDENTITY
static const Quaternion ZERO
Detailed Description
template<class Real>
class Wm4::Quaternion< Real >
Definition at line 19 of file Wm4Quaternion.h.
Constructor & Destructor Documentation
Quaternion() [1/6]
template<class Real > Wm4::Quaternion< Real >::Quaternion ()
Quaternion() [2/6]
template<class Real > Wm4::Quaternion< Real >::Quaternion (Real fW, Real fX, Real fY, Real fZ)
Quaternion() [3/6]
template<class Real > Wm4::Quaternion< Real >::Quaternion (const Quaternion< Real > & rkQ)
Quaternion() [4/6]
template<class Real > Wm4::Quaternion< Real >::Quaternion (const Matrix3< Real > & rkRot)
Quaternion() [5/6]
template<class Real > Wm4::Quaternion< Real >::Quaternion (const Vector3< Real > & rkAxis, Real fAngle)
Quaternion() [6/6]
template<class Real > Wm4::Quaternion< Real >::Quaternion (const Vector3< Real > akRotColumn[3])
Member Function Documentation
Align()
template<class Real > Quaternion& Wm4::Quaternion< Real >::Align (const Vector3< Real > & rkV1, const Vector3< Real > & rkV2)
Conjugate()
template<class Real > Quaternion Wm4::Quaternion< Real >::Conjugate () const
DecomposeSwingTimesTwist()
template<class Real > void Wm4::Quaternion< Real >::DecomposeSwingTimesTwist (const Vector3< Real > & rkV1, Quaternion< Real > & rkSwing, Quaternion< Real > & rkTwist)
DecomposeTwistTimesSwing()
template<class Real > void Wm4::Quaternion< Real >::DecomposeTwistTimesSwing (const Vector3< Real > & rkV1, Quaternion< Real > & rkTwist, Quaternion< Real > & rkSwing)
Dot()
template<class Real > Real Wm4::Quaternion< Real >::Dot (const Quaternion< Real > & rkQ) const inline
Referenced by Wm4::MergeBoxes().
Exp()
template<class Real > Quaternion Wm4::Quaternion< Real >::Exp () const
FactorXYZ()
template<class Real > void Wm4::Quaternion< Real >::FactorXYZ (Real & rfCx, Real & rfSx, Real & rfCy, Real & rfSy, Real & rfCz, Real & rfSz)
FactorXZY()
template<class Real > void Wm4::Quaternion< Real >::FactorXZY (Real & rfCx, Real & rfSx, Real & rfCz, Real & rfSz, Real & rfCy, Real & rfSy)
FactorYXZ()
template<class Real > void Wm4::Quaternion< Real >::FactorYXZ (Real & rfCy, Real & rfSy, Real & rfCx, Real & rfSx, Real & rfCz, Real & rfSz)
FactorYZX()
template<class Real > void Wm4::Quaternion< Real >::FactorYZX (Real & rfCy, Real & rfSy, Real & rfCz, Real & rfSz, Real & rfCx, Real & rfSx)
FactorZXY()
template<class Real > void Wm4::Quaternion< Real >::FactorZXY (Real & rfCz, Real & rfSz, Real & rfCx, Real & rfSx, Real & rfCy, Real & rfSy)
FactorZYX()
template<class Real > void Wm4::Quaternion< Real >::FactorZYX (Real & rfCz, Real & rfSz, Real & rfCy, Real & rfSy, Real & rfCx, Real & rfSx)
FromAxisAngle()
template<class Real > Quaternion& Wm4::Quaternion< Real >::FromAxisAngle (const Vector3< Real > & rkAxis, Real fAngle)
FromRotationMatrix() [1/2]
template<class Real > Quaternion& Wm4::Quaternion< Real >::FromRotationMatrix (const Matrix3< Real > & rkRot)
Referenced by Wm4::MergeBoxes().
FromRotationMatrix() [2/2]
template<class Real > Quaternion& Wm4::Quaternion< Real >::FromRotationMatrix (const Vector3< Real > akRotColumn[3])
GetClosestX() [1/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::GetClosestX () const
GetClosestX() [2/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::GetClosestX (const Constraints & rkXCon) const
GetClosestXY() [1/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::GetClosestXY () const
GetClosestXY() [2/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::GetClosestXY (const Constraints & rkXCon, const Constraints & rkYCon) const
GetClosestXZ() [1/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::GetClosestXZ () const
GetClosestXZ() [2/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::GetClosestXZ (const Constraints & rkXCon, const Constraints & rkZCon) const
GetClosestY() [1/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::GetClosestY () const
GetClosestY() [2/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::GetClosestY (const Constraints & rkYCon) const
GetClosestYX() [1/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::GetClosestYX () const
GetClosestYX() [2/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::GetClosestYX (const Constraints & rkYCon, const Constraints & rkXCon) const
GetClosestYZ() [1/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::GetClosestYZ () const
GetClosestYZ() [2/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::GetClosestYZ (const Constraints & rkYCon, const Constraints & rkZCon) const
GetClosestZ() [1/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::GetClosestZ () const
GetClosestZ() [2/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::GetClosestZ (const Constraints & rkZCon) const
GetClosestZX() [1/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::GetClosestZX () const
GetClosestZX() [2/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::GetClosestZX (const Constraints & rkZCon, const Constraints & rkXCon) const
GetClosestZY() [1/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::GetClosestZY () const
GetClosestZY() [2/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::GetClosestZY (const Constraints & rkZCon, const Constraints & rkYCon) const
IDENTITY() [1/2]
const Quaternion< double > Wm4::Quaternion< double >::IDENTITY (1. 0, 0. 0, 0. 0, 0. 0)
IDENTITY() [2/2]
const Quaternion< float > Wm4::Quaternion< float >::IDENTITY (1. 0f, 0. 0f, 0. 0f, 0. 0f)
Intermediate()
template<class Real > Quaternion& Wm4::Quaternion< Real >::Intermediate (const Quaternion< Real > & rkQ0, const Quaternion< Real > & rkQ1, const Quaternion< Real > & rkQ2)
Inverse()
template<class Real > Quaternion Wm4::Quaternion< Real >::Inverse () const
Length()
template<class Real > Real Wm4::Quaternion< Real >::Length () const inline
Log()
template<class Real > Quaternion Wm4::Quaternion< Real >::Log () const
Normalize()
template<class Real > Real Wm4::Quaternion< Real >::Normalize () inline
operator const Real *()
template<class Real > Wm4::Quaternion< Real >::operator const Real * () const inline
operator Real *()
template<class Real > Wm4::Quaternion< Real >::operator Real * () inline
operator!=()
template<class Real > bool Wm4::Quaternion< Real >::operator!= (const Quaternion< Real > & rkQ) const
operator*() [1/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::operator* (const Quaternion< Real > & rkQ) const inline
operator*() [2/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::operator* (Real fScalar) const inline
operator*=()
template<class Real > Quaternion& Wm4::Quaternion< Real >::operator*= (Real fScalar) inline
operator+()
template<class Real > Quaternion Wm4::Quaternion< Real >::operator+ (const Quaternion< Real > & rkQ) const inline
operator+=()
template<class Real > Quaternion& Wm4::Quaternion< Real >::operator+= (const Quaternion< Real > & rkQ) inline
operator-() [1/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::operator- () const inline
operator-() [2/2]
template<class Real > Quaternion Wm4::Quaternion< Real >::operator- (const Quaternion< Real > & rkQ) const inline
operator-=()
template<class Real > Quaternion& Wm4::Quaternion< Real >::operator-= (const Quaternion< Real > & rkQ) inline
operator/()
template<class Real > Quaternion Wm4::Quaternion< Real >::operator/ (Real fScalar) const inline
operator/=()
template<class Real > Quaternion& Wm4::Quaternion< Real >::operator/= (Real fScalar) inline
operator<()
template<class Real > bool Wm4::Quaternion< Real >::operator< (const Quaternion< Real > & rkQ) const
operator<=()
template<class Real > bool Wm4::Quaternion< Real >::operator<= (const Quaternion< Real > & rkQ) const
operator=()
template<class Real > Quaternion& Wm4::Quaternion< Real >::operator= (const Quaternion< Real > & rkQ) inline
operator==()
template<class Real > bool Wm4::Quaternion< Real >::operator== (const Quaternion< Real > & rkQ) const
operator>()
template<class Real > bool Wm4::Quaternion< Real >::operator> (const Quaternion< Real > & rkQ) const
operator>=()
template<class Real > bool Wm4::Quaternion< Real >::operator>= (const Quaternion< Real > & rkQ) const
operator[]() [1/2]
template<class Real > Real& Wm4::Quaternion< Real >::operator[] (int i) inline
operator[]() [2/2]
template<class Real > Real Wm4::Quaternion< Real >::operator[] (int i) const inline
Rotate()
template<class Real > Vector3<Real> Wm4::Quaternion< Real >::Rotate (const Vector3< Real > & rkVector) const
Slerp()
template<class Real > Quaternion& Wm4::Quaternion< Real >::Slerp (Real fT, const Quaternion< Real > & rkP, const Quaternion< Real > & rkQ)
SlerpExtraSpins()
template<class Real > Quaternion& Wm4::Quaternion< Real >::SlerpExtraSpins (Real fT, const Quaternion< Real > & rkP, const Quaternion< Real > & rkQ, int iExtraSpins)
Squad()
template<class Real > Quaternion& Wm4::Quaternion< Real >::Squad (Real fT, const Quaternion< Real > & rkQ0, const Quaternion< Real > & rkA0, const Quaternion< Real > & rkA1, const Quaternion< Real > & rkQ1)
SquaredLength()
template<class Real > Real Wm4::Quaternion< Real >::SquaredLength () const inline
ToAxisAngle()
template<class Real > void Wm4::Quaternion< Real >::ToAxisAngle (Vector3< Real > & rkAxis, Real & rfAngle) const
ToRotationMatrix() [1/2]
template<class Real > void Wm4::Quaternion< Real >::ToRotationMatrix (Matrix3< Real > & rkRot) const
Referenced by Wm4::MergeBoxes().
ToRotationMatrix() [2/2]
template<class Real > void Wm4::Quaternion< Real >::ToRotationMatrix (Vector3< Real > akRotColumn[3]) const
W() [1/2]
template<class Real > Real& Wm4::Quaternion< Real >::W () inline
W() [2/2]
template<class Real > Real Wm4::Quaternion< Real >::W () const inline
X() [1/2]
template<class Real > Real& Wm4::Quaternion< Real >::X () inline
X() [2/2]
template<class Real > Real Wm4::Quaternion< Real >::X () const inline
Y() [1/2]
template<class Real > Real& Wm4::Quaternion< Real >::Y () inline
Y() [2/2]
template<class Real > Real Wm4::Quaternion< Real >::Y () const inline
Z() [1/2]
template<class Real > Real& Wm4::Quaternion< Real >::Z () inline
Z() [2/2]
template<class Real > Real Wm4::Quaternion< Real >::Z () const inline
ZERO() [1/2]
const Quaternion< double > Wm4::Quaternion< double >::ZERO (0. 0, 0. 0, 0. 0, 0. 0)
ZERO() [2/2]
const Quaternion< float > Wm4::Quaternion< float >::ZERO (0. 0f, 0. 0f, 0. 0f, 0. 0f)
Member Data Documentation
IDENTITY
template<class Real > const Quaternion Wm4::Quaternion< Real >::IDENTITY static
Definition at line 286 of file Wm4Quaternion.h.
ZERO
template<class Real > const Quaternion Wm4::Quaternion< Real >::ZERO static
Definition at line 287 of file Wm4Quaternion.h.
The documentation for this class was generated from the following file:
Wm4Quaternion.h