FreeCAD: AppAssembly.cpp File Reference
AppAssembly.cpp File Reference
#include "PreCompiled.h"
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/PyObjectBase.h>
#include "AssemblyObject.h"
#include "AssemblyLink.h"
#include "BomObject.h"
#include "BomGroup.h"
#include "JointGroup.h"
#include "ViewGroup.h"
#include "SimulationGroup.h"
Namespaces
Assembly
Functions
PyObject * Assembly::initModule ()
PyMOD_INIT_FUNC (AssemblyApp)
Function Documentation
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (AssemblyApp)
Definition at line 45 of file AppAssembly.cpp.
References Base::Console(), SCL.SimpleDataTypes::e, App::DocumentObjectExtension::init(), Base::Persistence::init(), Assembly::initModule(), Base::Interpreter(), Base::ConsoleSingleton::Log(), mod, PyMOD_Return, and Base::InterpreterSingleton::runString().