FreeCAD: MeshGui::RemoveComponentsDialog Class Reference
MeshGui::RemoveComponentsDialog Class Reference
#include <RemoveComponents.h>
Public Member Functions
RemoveComponentsDialog (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~RemoveComponentsDialog () override
void reject () override
Detailed Description
Embed the panel into a dialog.
Definition at line 103 of file RemoveComponents.h.
Constructor & Destructor Documentation
RemoveComponentsDialog()
RemoveComponentsDialog::RemoveComponentsDialog (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Definition at line 198 of file RemoveComponents.cpp.
References draftgeoutils.intersections::connect().
~RemoveComponentsDialog()
RemoveComponentsDialog::~RemoveComponentsDialog () override default
Member Function Documentation
reject()
void RemoveComponentsDialog::reject () override
Definition at line 219 of file RemoveComponents.cpp.
References MeshGui::RemoveComponents::reject().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action().
The documentation for this class was generated from the following files:
RemoveComponents.h
RemoveComponents.cpp