FreeCAD: PartGui::DlgExtrusion Class Reference
PartGui::DlgExtrusion Class Reference
#include <DlgExtrusion.h>
Classes
class EdgeSelection
Public Member Functions
DlgExtrusion (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgExtrusion () override
void accept () override
void apply ()
void reject () override
Base::Vector3d getDir () const
void setDir (Base::Vector3d newDir)
Part::Extrusion::eDirMode getDirMode () const
void setDirMode (Part::Extrusion::eDirMode newMode)
void getAxisLink (App::PropertyLinkSub &lnk) const
void setAxisLink (const App::PropertyLinkSub &lnk)
void setAxisLink (const char *objname, const char *subname)
std::vector< App::DocumentObject * > getShapesToExtrude () const
bool validate ()
void writeParametersToFeature (App::DocumentObject &feature, App::DocumentObject *base) const
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Protected Member Functions
void findShapes ()
bool canExtrude (const TopoDS_Shape &) const
void changeEvent (QEvent *e) override
void keyPressEvent (QKeyEvent *) override
Detailed Description
Definition at line 39 of file DlgExtrusion.h.
Constructor & Destructor Documentation
DlgExtrusion()
DlgExtrusion::DlgExtrusion (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
Definition at line 99 of file DlgExtrusion.cpp.
References Base::Unit::Angle, Gui::ItemViewSelection::applyFrom(), findShapes(), Base::Persistence::getClassTypeId(), Base::UnitsApi::getDecimals(), draftutils.utils::getObjectsOfType, Base::Unit::Length, and Gui::Selection().
~DlgExtrusion()
DlgExtrusion::~DlgExtrusion () override
Definition at line 134 of file DlgExtrusion.cpp.
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
accept()
void DlgExtrusion::accept () override
Definition at line 431 of file DlgExtrusion.cpp.
References apply().
Referenced by PartGui::TaskExtrusion::accept().
apply()
void DlgExtrusion::apply ()
Definition at line 441 of file DlgExtrusion.cpp.
References App::Document::commitTransaction(), copyVisual, FC_ERR, FCMD_OBJ_DOC_CMD, FCMD_OBJ_HIDE, App::GetApplication(), ParameterGrp::GetBool(), App::Application::getDocument(), ParameterGrp::GetGroup(), getShapesToExtrude(), Part::Feature::getTopoShape(), App::Application::GetUserParameter(), draftgeoutils.general::isNull(), importers.importIFCmulticore::objects, App::Document::openTransaction(), src.Mod.AddonManager.Addon::translate, Gui::Command::updateActive(), validate(), Base::Exception::what(), and writeParametersToFeature().
Referenced by accept(), and PartGui::TaskExtrusion::clicked().
canExtrude()
bool DlgExtrusion::canExtrude (const TopoDS_Shape & shape) const protected
Definition at line 405 of file DlgExtrusion.cpp.
References Path.Post.scripts.grbl_post::type.
Referenced by findShapes().
changeEvent()
void DlgExtrusion::changeEvent (QEvent * e) override protected
Definition at line 168 of file DlgExtrusion.cpp.
References SCL.SimpleDataTypes::e.
findShapes()
void DlgExtrusion::findShapes () protected
Definition at line 376 of file DlgExtrusion.cpp.
References canExtrude(), App::Application::getActiveDocument(), App::GetApplication(), Gui::Application::getDocument(), Gui::ViewProvider::getIcon(), App::Document::getName(), App::Document::getObjectsOfType(), Part::TopoShape::getShape(), Part::Feature::getTopoShape(), App::PropertyString::getValue(), Gui::Document::getViewProvider(), Gui::Application::Instance, Part::TopoShape::isNull(), App::Document::Label, and replaceobj::objs.
Referenced by DlgExtrusion().
getAxisLink()
void DlgExtrusion::getAxisLink (App::PropertyLinkSub & lnk) const
Definition at line 565 of file DlgExtrusion.cpp.
References App::Application::getActiveDocument(), App::GetApplication(), App::Document::getObject(), App::PropertyLinkSub::setValue(), and importers.importIFCmulticore::subs.
Referenced by validate(), and writeParametersToFeature().
getDir()
Base::Vector3d DlgExtrusion::getDir () const
Definition at line 521 of file DlgExtrusion.cpp.
Referenced by validate(), and writeParametersToFeature().
getDirMode()
Part::Extrusion::eDirMode DlgExtrusion::getDirMode () const
Definition at line 536 of file DlgExtrusion.cpp.
References Part::Extrusion::dmCustom, Part::Extrusion::dmEdge, and Part::Extrusion::dmNormal.
Referenced by validate(), and writeParametersToFeature().
getShapesToExtrude()
std::vector< App::DocumentObject * > DlgExtrusion::getShapesToExtrude () const
Definition at line 615 of file DlgExtrusion.cpp.
References toolbit-attributes::doc, App::GetApplication(), App::Application::getDocument(), src.Mod.Test.testPathArray::items, and importers.importIFCmulticore::objects.
Referenced by apply().
keyPressEvent()
void DlgExtrusion::keyPressEvent (QKeyEvent * ke) override protected
Definition at line 176 of file DlgExtrusion.cpp.
reject()
void DlgExtrusion::reject () override
Definition at line 513 of file DlgExtrusion.cpp.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and PartGui::TaskExtrusion::reject().
setAxisLink() [1/2]
void DlgExtrusion::setAxisLink (const App::PropertyLinkSub & lnk)
Definition at line 589 of file DlgExtrusion.cpp.
References App::DocumentObject::getNameInDocument(), App::PropertyLinkSub::getSubValues(), and App::PropertyLinkSub::getValue().
setAxisLink() [2/2]
void DlgExtrusion::setAxisLink (const char * objname, const char * subname)
Definition at line 602 of file DlgExtrusion.cpp.
References create_qrc::txt.
setDir()
void DlgExtrusion::setDir (Base::Vector3d newDir)
Definition at line 529 of file DlgExtrusion.cpp.
References Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
setDirMode()
void DlgExtrusion::setDirMode (Part::Extrusion::eDirMode newMode)
Definition at line 549 of file DlgExtrusion.cpp.
References Part::Extrusion::dmCustom, Part::Extrusion::dmEdge, and Part::Extrusion::dmNormal.
validate()
bool DlgExtrusion::validate ()
Definition at line 632 of file DlgExtrusion.cpp.
References importers.importWebGL::base, Part::Extrusion::calculateShapeNormal(), Part::Extrusion::dmCustom, Part::Extrusion::dmEdge, Part::Extrusion::dmNormal, Part::Extrusion::fetchAxisLink(), getAxisLink(), getDir(), getDirMode(), FreeCADInit::Length, App::PropertyLink::setValue(), src.Mod.AddonManager.Addon::translate, and Base::Exception::what().
Referenced by apply().
writeParametersToFeature()
void DlgExtrusion::writeParametersToFeature (App::DocumentObject & feature, App::DocumentObject * base) const
Definition at line 712 of file DlgExtrusion.cpp.
References Part::Extrusion::dmCustom, Gui::Command::Doc, doCommand, Part::Extrusion::eDirModeStrings, getAxisLink(), getDir(), getDirMode(), App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), App::PropertyLinkSub::getSubValues(), App::PropertyLinkSub::getValue(), Path.Post.scripts.refactored_centroid_post::str, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by apply().
The documentation for this class was generated from the following files:
DlgExtrusion.h
DlgExtrusion.cpp