FreeCAD: Gui::ViewerEventFilter Class Reference
Gui::ViewerEventFilter Class Reference
Public Member Functions
ViewerEventFilter ()=default
~ViewerEventFilter () override=default
bool eventFilter (QObject *obj, QEvent *event) override
Detailed Description
As ProgressBar has no chance to control the incoming Qt events of Quarter so we need to stop the event handling to prevent the scenegraph from being selected or deselected while the progress bar is running.
Definition at line 220 of file View3DInventorViewer.cpp.
Constructor & Destructor Documentation
ViewerEventFilter()
Gui::ViewerEventFilter::ViewerEventFilter () default
~ViewerEventFilter()
Gui::ViewerEventFilter::~ViewerEventFilter () override default
Member Function Documentation
eventFilter()
bool Gui::ViewerEventFilter::eventFilter (QObject * obj, QEvent * event) inline override
Definition at line 226 of file View3DInventorViewer.cpp.
References Spaceball::ButtonEvent::ButtonEventType, Base::Console(), Gui::View3DInventorViewer::getEditingViewProvider(), Base::SequencerBase::isBlocking(), Base::SequencerBase::isRunning(), Base::ConsoleSingleton::Log(), Spaceball::MotionEvent::MotionEventType, Gui::ViewProvider::selectAll(), and Base::Sequencer().
The documentation for this class was generated from the following file:
View3DInventorViewer.cpp