FreeCAD: Gui::TextEditor Class Reference
Gui::TextEditor Class Reference
#include <TextEdit.h>
Public Member Functions
TextEditor (QWidget *parent=nullptr)
~TextEditor () override
void setSyntaxHighlighter (SyntaxHighlighter *)
void OnChange (Base::Subject< const char * > &rCaller, const char *rcReason) override
void lineNumberAreaPaintEvent (QPaintEvent *)
int lineNumberAreaWidth ()
void setVisibleLineNumbers (bool value)
bool isVisibleLineNumbers () const
void setEnabledHighlightCurrentLine (bool value)
bool isEnabledHighlightCurrentLine () const
Public Member Functions inherited from Gui::TextEdit
TextEdit (QWidget *parent=nullptr)
~TextEdit () override
Public Member Functions inherited from Gui::WindowParameter
WindowParameter (const char *name)
~WindowParameter () override
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
ParameterGrp::handle getWindowParameter ()
return the parameter group of this window
Protected Member Functions
void resizeEvent (QResizeEvent *e) override
QWidget * getMarker () const
virtual void drawMarker (int line, int x, int y, QPainter *)
Protected Member Functions inherited from Gui::TextEdit
void keyPressEvent (QKeyEvent *) override
void wheelEvent (QWheelEvent *e) override
Protected Member Functions inherited from Gui::WindowParameter
bool setGroupName (const char *name)
template<typename S , typename T >
void setSlotParamChanged (S slot, T *obsPtr)
connect slot to ParameterManager signal
Friends
class SyntaxHighlighter
Additional Inherited Members
Signals inherited from Gui::TextEdit
void showSearchBar ()
void findNext ()
void findPrevious ()
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter ()
get the parameters
Detailed Description
Definition at line 105 of file Gui/TextEdit.h.
Constructor & Destructor Documentation
TextEditor()
TextEditor::TextEditor (QWidget * parent = nullptr) explicit
Constructs a TextEditor which is a child of 'parent' and does the syntax highlighting for the Python language.
Definition at line 236 of file Gui/TextEdit.cpp.
References Base::Subject< MsgType >::Attach(), draftgeoutils.intersections::connect(), Gui::WindowParameter::getWindowParameter(), geoff_geometry::Normal(), and ParameterGrp::NotifyAll().
~TextEditor()
TextEditor::~TextEditor () override
Destroys the object and frees any allocated resources
Definition at line 263 of file Gui/TextEdit.cpp.
References Base::Subject< MsgType >::Detach(), and Gui::WindowParameter::getWindowParameter().
Member Function Documentation
drawMarker()
void TextEditor::drawMarker (int line, int x, int y, QPainter * p) protected virtual
Reimplemented in Gui::PythonEditor.
Definition at line 352 of file Gui/TextEdit.cpp.
References buildPsets::p, MovieTool::x, and MovieTool::y.
Referenced by lineNumberAreaPaintEvent().
getMarker()
QWidget* Gui::TextEditor::getMarker () const inline protected
Definition at line 131 of file Gui/TextEdit.h.
Referenced by Gui::PythonEditor::hideDebugMarker(), Gui::PythonEditor::showDebugMarker(), and Gui::PythonEditor::toggleBreakpoint().
isEnabledHighlightCurrentLine()
bool TextEditor::isEnabledHighlightCurrentLine () const
Definition at line 286 of file Gui/TextEdit.cpp.
References Gui::TextEditorP::highlightLine.
isVisibleLineNumbers()
bool TextEditor::isVisibleLineNumbers () const
Definition at line 276 of file Gui/TextEdit.cpp.
References Gui::TextEditorP::visibleMarker.
Referenced by lineNumberAreaPaintEvent(), and resizeEvent().
lineNumberAreaPaintEvent()
void TextEditor::lineNumberAreaPaintEvent (QPaintEvent * event)
Draw a beam in the line where the cursor is.
Definition at line 360 of file Gui/TextEdit.cpp.
References drawMarker(), and isVisibleLineNumbers().
Referenced by Gui::LineMarker::paintEvent().
lineNumberAreaWidth()
int TextEditor::lineNumberAreaWidth ()
Definition at line 291 of file Gui/TextEdit.cpp.
References Gui::QtTools::horizontalAdvance().
Referenced by OnChange(), resizeEvent(), and Gui::LineMarker::sizeHint().
OnChange()
void TextEditor::OnChange (Base::Subject< const char * > & rCaller, const char * sReason) override
Sets the font, font size and tab size of the editor.
Definition at line 398 of file Gui/TextEdit.cpp.
References Gui::TextEditorP::colormap, ParameterGrp::GetASCII(), ParameterGrp::GetBool(), ParameterGrp::GetInt(), ParameterGrp::GetUnsigned(), Gui::WindowParameter::getWindowParameter(), Gui::QtTools::horizontalAdvance(), lineNumberAreaWidth(), and Gui::SyntaxHighlighter::setColor().
Referenced by Gui::PythonEditor::OnChange(), and Gui::PythonConsole::OnChange().
resizeEvent()
void TextEditor::resizeEvent (QResizeEvent * e) override protected
Definition at line 318 of file Gui/TextEdit.cpp.
References SCL.SimpleDataTypes::e, isVisibleLineNumbers(), and lineNumberAreaWidth().
setEnabledHighlightCurrentLine()
void TextEditor::setEnabledHighlightCurrentLine (bool value)
Definition at line 281 of file Gui/TextEdit.cpp.
References Gui::TextEditorP::highlightLine.
Referenced by Gui::PythonConsole::PythonConsole().
setSyntaxHighlighter()
void TextEditor::setSyntaxHighlighter (SyntaxHighlighter * sh)
Definition at line 391 of file Gui/TextEdit.cpp.
Referenced by Gui::PythonConsole::PythonConsole(), and Gui::PythonEditor::PythonEditor().
setVisibleLineNumbers()
void TextEditor::setVisibleLineNumbers (bool value)
Definition at line 270 of file Gui/TextEdit.cpp.
References Gui::TextEditorP::visibleMarker.
Referenced by Gui::PythonConsole::PythonConsole().
Friends And Related Function Documentation
SyntaxHighlighter
friend class SyntaxHighlighter friend
Definition at line 140 of file Gui/TextEdit.h.
The documentation for this class was generated from the following files:
Gui/TextEdit.h
Gui/TextEdit.cpp