FreeCAD: TechDrawGui::TaskActiveView Class Reference
TechDrawGui::TaskActiveView Class Reference
#include <TaskActiveView.h>
Public Member Functions
TaskActiveView (TechDraw::DrawPage *pageFeat)
~TaskActiveView () override
virtual bool accept ()
virtual bool reject ()
void updateTask ()
void saveButtons (QPushButton *btnOK, QPushButton *btnCancel)
void enableTaskButtons (bool b)
Protected Member Functions
void changeEvent (QEvent *e) override
void blockButtons (bool b)
void setUiPrimary (void)
TechDraw::DrawViewImage * createActiveView ()
void enableCrop (bool state)
Detailed Description
Definition at line 48 of file TaskActiveView.h.
Constructor & Destructor Documentation
TaskActiveView()
TaskActiveView::TaskActiveView (TechDraw::DrawPage * pageFeat)
Definition at line 60 of file TaskActiveView.cpp.
References draftgeoutils.intersections::connect(), Base::Unit::Length, and setUiPrimary().
~TaskActiveView()
TaskActiveView::~TaskActiveView () override
Definition at line 73 of file TaskActiveView.cpp.
Member Function Documentation
accept()
bool TaskActiveView::accept () virtual
Definition at line 264 of file TaskActiveView.cpp.
References Gui::Command::commitCommand(), createActiveView(), doCommand, Gui::Command::Gui, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, App::DocumentObject::recomputeFeature(), and Gui::Command::updateActive().
Referenced by TechDrawGui::TaskDlgActiveView::accept().
blockButtons()
void TaskActiveView::blockButtons (bool b) protected
Definition at line 100 of file TaskActiveView.cpp.
References SCL.SimpleDataTypes::b.
changeEvent()
void TaskActiveView::changeEvent (QEvent * e) override protected
Definition at line 82 of file TaskActiveView.cpp.
References SCL.SimpleDataTypes::e.
createActiveView()
TechDraw::DrawViewImage * TaskActiveView::createActiveView () protected
Definition at line 102 of file TaskActiveView.cpp.
References TechDraw::DrawUtil::cleanFilespecBackslash(), Base::Console(), TechDrawGui::ViewProviderImage::Crop, Base::FileInfo::deleteFile(), toolbit-attributes::doc, doCommand, Base::ConsoleSingleton::Error(), Base::FileInfo::exists(), Base::BaseClass::getClassTypeId(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::getMainWindow(), Gui::Document::getMDIViewsOfType(), App::Document::getName(), App::DocumentObject::getNameInDocument(), App::Document::getObject(), Base::FileInfo::getTempFileName(), App::Document::getUniqueObjectName(), Gui::Document::getViewProvider(), TechDrawGui::Rez::guiX(), Gui::Application::Instance, TechDrawGui::Grabber3d::quickView(), App::PropertyBool::setValue(), SXGAHeight, SXGAWidth, Path.Log::warning(), and Gui::MainWindow::windows().
Referenced by accept().
enableCrop()
void TaskActiveView::enableCrop (bool state) protected
Definition at line 242 of file TaskActiveView.cpp.
Referenced by setUiPrimary().
enableTaskButtons()
void TaskActiveView::enableTaskButtons (bool b)
Definition at line 256 of file TaskActiveView.cpp.
References SCL.SimpleDataTypes::b.
reject()
bool TaskActiveView::reject () virtual
Definition at line 281 of file TaskActiveView.cpp.
References doCommand, and Gui::Command::Gui.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and TechDrawGui::TaskDlgActiveView::reject().
saveButtons()
void TaskActiveView::saveButtons (QPushButton * btnOK, QPushButton * btnCancel)
Definition at line 250 of file TaskActiveView.cpp.
Referenced by TechDrawGui::TaskDlgActiveView::modifyStandardButtons().
setUiPrimary()
void TaskActiveView::setUiPrimary (void) protected
Definition at line 89 of file TaskActiveView.cpp.
References TechDrawGui::Rez::appX(), enableCrop(), SXGAHeight, and SXGAWidth.
Referenced by TaskActiveView().
updateTask()
void TaskActiveView::updateTask ()
Definition at line 75 of file TaskActiveView.cpp.
The documentation for this class was generated from the following files:
TaskActiveView.h
TaskActiveView.cpp