FreeCAD: Gui::SoFCColorGradient Class Reference
Gui::SoFCColorGradient Class Reference
#include <SoFCColorGradient.h>
Public Member Functions
SoFCColorGradient ()
void setRange (float fMin, float fMax, int prec=3) override
App::Color getColor (float fVal) const override
void setOutsideGrayed (bool bVal) override
bool isVisible (float fVal) const override
float getMinValue () const override
float getMaxValue () const override
void customize (SoFCColorBarBase *) override
const char * getColorBarName () const override
Public Member Functions inherited from Gui::SoFCColorBarBase
void GLRenderBelowPath (SoGLRenderAction *action) override
virtual void triggerChange (SoFCColorBarBase *base)
virtual void setFormat (const SoLabelTextFormat &fmt)
SoLabelTextFormat getFormat () const
Static Public Member Functions
static void initClass ()
static void finish ()
Static Public Member Functions inherited from Gui::SoFCColorBarBase
static void initClass ()
static void finish ()
Protected Member Functions
void applyFormat (const SoLabelTextFormat &fmt) override
void setViewportSize (const SbVec2s &size) override
~SoFCColorGradient () override
void setColorModel (std::size_t index)
void setColorStyle (App::ColorBarStyle tStyle)
void rebuildGradient ()
std::vector< float > getMarkerValues (float fMin, float fMax, int count) const
Protected Member Functions inherited from Gui::SoFCColorBarBase
float getBounds (const SbVec2s &size, float &fMinX, float &fMinY, float &fMaxX, float &fMaxY)
float getBoundingWidth (const SbVec2s &size)
void setModified ()
SoFCColorBarBase ()
~SoFCColorBarBase () override
Protected Member Functions inherited from App::ValueFloatToRGB
ValueFloatToRGB ()=default
virtual ~ValueFloatToRGB ()=default
Detailed Description
Definition at line 43 of file SoFCColorGradient.h.
Constructor & Destructor Documentation
SoFCColorGradient()
SoFCColorGradient::SoFCColorGradient ()
Constructor.
Definition at line 66 of file SoFCColorGradient.cpp.
References defaultMax, defaultMin, App::FLOW, App::ExpressionParser::labels, and setRange().
~SoFCColorGradient()
SoFCColorGradient::~SoFCColorGradient () override protected
Destructor.
Definition at line 83 of file SoFCColorGradient.cpp.
Member Function Documentation
applyFormat()
void SoFCColorGradient::applyFormat (const SoLabelTextFormat & fmt) override protected virtual
Applies the format to the label text
Reimplemented from Gui::SoFCColorBarBase.
Definition at line 106 of file SoFCColorGradient.cpp.
References Path.Post.scripts.comparams_post::fmt().
customize()
void SoFCColorGradient::customize (SoFCColorBarBase * parentNode) override virtual
Opens a dialog to customize the current settings of the color gradient bar.
Implements Gui::SoFCColorBarBase.
Definition at line 419 of file SoFCColorGradient.cpp.
References Gui::MainWindow::activeWindow(), Gui::Dialog::DlgSettingsColorGradientImp::colorModelChanged(), draftgeoutils.intersections::connect(), SCL.SimpleDataTypes::e, App::ColorGradientProfile::fMax, App::ColorGradientProfile::fMin, Gui::getMainWindow(), Gui::Dialog::DlgSettingsColorGradientImp::getProfile(), App::ColorGradient::getProfile(), App::ColorGradientProfile::isEqual(), Gui::Dialog::DlgSettingsColorGradientImp::numberOfDecimals(), Init::parent, RobotExample::pos, draftgeoutils.general::precision(), rebuildGradient(), Gui::Dialog::DlgSettingsColorGradientImp::setNumberOfDecimals(), App::ColorGradient::setProfile(), setRange(), and Gui::SoFCColorBarBase::triggerChange().
finish()
void SoFCColorGradient::finish () static
Definition at line 96 of file SoFCColorGradient.cpp.
Referenced by drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::accept(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::accept(), draftguitools.gui_split.Split::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_subelements.SubelementHighlight::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rotate.Rotate::action(), draftguitools.gui_fillets.Fillet::action(), draftguitools.gui_move.Move::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_arcs.Arc::action(), draftguitools.gui_texts.Text::action(), draftguitools.gui_scale.Scale::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_trimex.Trimex::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_styles.ApplyStyle::Activated(), draftguitools.gui_join.Join::Activated(), draftguitools.gui_draft2sketch.Draft2Sketch::Activated(), draftguitools.gui_downgrade.Downgrade::Activated(), draftguitools.gui_upgrade.Upgrade::Activated(), draftguitools.gui_shape2dview.Shape2DView::Activated(), draftguitools.gui_facebinders.Facebinder::Activated(), draftguitools.gui_subelements.SubelementHighlight::Activated(), draftguitools.gui_wire2spline.WireToBSpline::Activated(), draftguitools.gui_clone.Clone::Activated(), draftguitools.gui_dimensions.Dimension::Activated(), draftguitools.gui_edit.Edit::Activated(), draftguitools.gui_selectplane.Draft_SelectPlane::check_selection(), DraftGui.DraftToolBar::checkSpecialChars(), draftguitools.gui_points.Point::click(), draftguitools.gui_orthoarray.OrthoArray::completed(), draftguitools.gui_polararray.PolarArray::completed(), draftguitools.gui_circulararray.CircularArray::completed(), draftguitools.gui_labels.Label::create(), bimcommands.BimText.BIM_Text::createObject(), draftguitools.gui_rectangles.Rectangle::createObject(), draftguitools.gui_ellipses.Ellipse::createObject(), draftguitools.gui_texts.Text::createObject(), draftviewproviders.view_text.ViewProviderText::createObject(), draftguitools.gui_stretch.Stretch::doStretch(), draftguitools.gui_fillets.Fillet::draw_arc(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), DraftGui.DraftToolBar::editUi(), DraftGui.DraftToolBar::escape(), Gui::SoFCDB::finish(), draftguitools.gui_move.Move::get_object_selection(), draftguitools.gui_rotate.Rotate::get_object_selection(), draftguitools.gui_scale.Scale::get_object_selection(), draftguitools.gui_arcs.Arc_3Points::getPoint(), draftguitools.gui_edit.Edit::keyPressed(), draftguitools.gui_dimensions.Dimension::numericInput(), draftguitools.gui_offset.Offset::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), draftguitools.gui_trimex.Trimex::numericRadius(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_align(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_auto(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_center(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_front(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_move(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_next(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_previous(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_side(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_top(), bimcommands.BimShape2DView.BIM_Shape2DView::proceed(), draftguitools.gui_join.Join::proceed(), draftguitools.gui_subelements.SubelementHighlight::proceed(), draftguitools.gui_draft2sketch.Draft2Sketch::proceed(), draftguitools.gui_downgrade.Downgrade::proceed(), bimcommands.BimSlab.BIM_Slab::proceed(), draftguitools.gui_upgrade.Upgrade::proceed(), draftguitools.gui_facebinders.Facebinder::proceed(), draftguitools.gui_pathtwistedarray.PathTwistedArray::proceed(), draftguitools.gui_shape2dview.Shape2DView::proceed(), draftguitools.gui_clone.Clone::proceed(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_pointarray.PointArray::proceed(), draftguitools.gui_patharray.PathArray::proceed(), draftguitools.gui_trimex.Trimex::proceed(), draftguitools.gui_edit.Edit::proceed(), draftguitools.gui_selectplane.Draft_SelectPlane::reject(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::reject(), drafttaskpanels.task_polararray.TaskPanelPolarArray::reject(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::reject(), and draftguitools.gui_edit.Edit::setTrackers().
getColor()
App::Color Gui::SoFCColorGradient::getColor (float fVal) const inline override virtual
Returns the associated color to the value fVal.
Implements Gui::SoFCColorBarBase.
Definition at line 61 of file SoFCColorGradient.h.
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::setValues().
getColorBarName()
const char * SoFCColorGradient::getColorBarName () const override virtual
Returns the name of the color bar.
Implements Gui::SoFCColorBarBase.
Definition at line 101 of file SoFCColorGradient.cpp.
References Arch::QT_TRANSLATE_NOOP.
getMarkerValues()
std::vector< float > SoFCColorGradient::getMarkerValues (float fMin, float fMax, int count) const protected
Returns a list of count labels within the range [fMin, fMax].
Definition at line 261 of file SoFCColorGradient.cpp.
References src.Mod.AddonManager.NetworkManager::count, and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by setRange().
getMaxValue()
float Gui::SoFCColorGradient::getMaxValue () const inline override virtual
Returns the current maximum of the parameter range.
Implements Gui::SoFCColorBarBase.
Definition at line 72 of file SoFCColorGradient.h.
getMinValue()
float Gui::SoFCColorGradient::getMinValue () const inline override virtual
Returns the current minimum of the parameter range.
Implements Gui::SoFCColorBarBase.
Definition at line 70 of file SoFCColorGradient.h.
initClass()
void SoFCColorGradient::initClass () static
Definition at line 91 of file SoFCColorGradient.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
isVisible()
bool SoFCColorGradient::isVisible (float fVal) const override virtual
Returns always true if the gradient is in mode to show colors to arbitrary values of fVal, otherwise true is returned if fVal is within the specified parameter range, if not false is returned.
Implements Gui::SoFCColorBarBase.
Definition at line 410 of file SoFCColorGradient.cpp.
References App::ColorGradient::isOutOfRange(), and App::ColorGradient::isOutsideInvisible().
Referenced by ArchVRM.Renderer::removeHidden().
rebuildGradient()
void SoFCColorGradient::rebuildGradient () protected
Rebuild the gradient bar.
Definition at line 385 of file SoFCColorGradient.cpp.
References Gui::coinRemoveAllChildren().
Referenced by customize(), setColorModel(), and setColorStyle().
setColorModel()
void SoFCColorGradient::setColorModel (std::size_t index) protected
Sets the color model of the underlying color gradient to index.
Definition at line 310 of file SoFCColorGradient.cpp.
References rebuildGradient(), and App::ColorGradient::setColorModel().
setColorStyle()
void SoFCColorGradient::setColorStyle (App::ColorBarStyle tStyle) protected
Sets the color style of the underlying color gradient to tStyle. tStyle either can be FLOW or ZERO_BASED
Definition at line 316 of file SoFCColorGradient.cpp.
References rebuildGradient(), and App::ColorGradient::setStyle().
setOutsideGrayed()
void Gui::SoFCColorGradient::setOutsideGrayed (bool bVal) inline override virtual
Sets whether values outside the range should be in gray,
This method must be implemented in subclasses.
Implements Gui::SoFCColorBarBase.
Definition at line 62 of file SoFCColorGradient.h.
setRange()
void SoFCColorGradient::setRange (float fMin, float fMax, int prec = 3) override virtual
Sets the range of the colorbar from the maximum fMax to the minimum fMin. prec indicates the post decimal positions, prec should be in between 0 and 6.
Implements Gui::SoFCColorBarBase.
Definition at line 237 of file SoFCColorGradient.cpp.
References App::ColorGradient::getCountColors(), getMarkerValues(), SplineSurface::i, NavigationIndicatorGui::label, and App::ColorGradient::setRange().
Referenced by customize(), and SoFCColorGradient().
setViewportSize()
void SoFCColorGradient::setViewportSize (const SbVec2s & size) override protected virtual
Sets the current viewer size this color gradient is embedded into, to recalculate its new position.
Implements Gui::SoFCColorBarBase.
Definition at line 158 of file SoFCColorGradient.cpp.
References Gui::SoFCColorBarBase::getBounds(), SplineSurface::i, spaceX, and spaceY.
The documentation for this class was generated from the following files:
SoFCColorGradient.h
SoFCColorGradient.cpp