FreeCAD: App::PropertyString Class Reference
App::PropertyString Class Reference
#include <PropertyStandard.h>
Public Member Functions
PropertyString ()
~PropertyString () override
virtual void setValue (const char *sString)
void setValue (const std::string &sString)
const char * getValue () const
const std::string & getStrValue () const
bool isEmpty ()
const char * getEditorName () const override
Get the class name of the associated property editor item.
PyObject * getPyObject () override
void setPyObject (PyObject *py) override
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
Property * Copy () const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
unsigned int getMemSize () const override
void setPathValue (const App::ObjectIdentifier &path, const boost::any &value) override
Set value of property.
const boost::any getPathValue (const App::ObjectIdentifier &path) const override
Get value of property.
bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
Public Member Functions inherited from App::Property
Property ()
~Property () override
const char * getName () const
bool hasName () const
std::string getFullName () const
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual void afterRestore ()
virtual void onContainerRestored ()
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
int64_t getID () const
virtual void beforeSave () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Attributes
std::string _cValue
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::Property
virtual void hasSetValue ()
Gets called by all setValue() methods after the value has changed.
virtual void aboutToSetValue ()
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
String properties This is the father of all properties handling Strings.
Definition at line 741 of file PropertyStandard.h.
Constructor & Destructor Documentation
PropertyString()
PropertyString::PropertyString () default
A constructor. A more elaborate description of the constructor.
~PropertyString()
PropertyString::~PropertyString () override default
A destructor. A more elaborate description of the destructor.
Member Function Documentation
Copy()
Property * PropertyString::Copy () const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Reimplemented in App::PropertyPersistentObject.
Definition at line 1588 of file PropertyStandard.cpp.
References buildPsets::p.
getEditorName()
const char* App::PropertyString::getEditorName () const inline override virtual
Get the class name of the associated property editor item.
Reimplemented from App::Property.
Reimplemented in App::PropertyFont.
Definition at line 770 of file PropertyStandard.h.
getMemSize()
unsigned int PropertyString::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence
See also
Base::Persistence
Reimplemented from App::Property.
Reimplemented in App::PropertyPersistentObject.
Definition at line 1600 of file PropertyStandard.cpp.
getPathValue()
const boost::any PropertyString::getPathValue (const App::ObjectIdentifier & path) const override virtual
Get value of property.
Reimplemented from App::Property.
Definition at line 1635 of file PropertyStandard.cpp.
References src.Mod.Test.testPathArray::path.
getPyObject()
PyObject * PropertyString::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Reimplemented in App::PropertyPersistentObject.
Definition at line 1514 of file PropertyStandard.cpp.
References buildPsets::p.
Referenced by App::PropertyXLink::getPyObject(), App::PropertyXLinkSub::getPyObject(), and App::PropertyEnumeration::getPyPathValue().
getStrValue()
const std::string& App::PropertyString::getStrValue () const inline
Definition at line 761 of file PropertyStandard.h.
Referenced by ExpressionCompleterModel::_data(), TDHandlerDimension::createDistanceDimension(), execCreateHorizChamferDimension(), execCreateVertChamferDimension(), execIncreaseDecreaseDecimal(), execInsertPrefixChar(), execRemovePrefixChar(), App::FeatureTestRow::execute(), Gui::Dialog::DlgPropertyLink::formatObject(), TechDraw::DimensionFormatter::getFormattedDimensionValue(), TechDraw::DimensionFormatter::getFormattedToleranceValue(), TechDraw::DimensionFormatter::getFormattedToleranceValues(), App::Document::onChanged(), App::PropertyLinkBase::restoreLabelReference(), App::Document::saveAs(), App::Document::saveCopy(), App::ObjectIdentifier::setDocumentObjectName(), App::PropertyXLink::setPyObject(), TechDrawGui::QGIViewBalloon::setViewPartFeature(), App::PropertyLinkBase::updateLabelReferences(), App::UpdateElementReferenceExpressionVisitor< P >::visit(), and MeshPartGui::Mesh2ShapeGmsh::writeProject().
getValue()
const char * PropertyString::getValue () const
Definition at line 1509 of file PropertyStandard.cpp.
Referenced by PartGui::SweepWidget::accept(), MeshGui::Segmentation::accept(), ReverseEngineeringGui::Segmentation::accept(), MeshGui::SegmentationBestFit::accept(), Assembly::BomObject::addObjectToBom(), TechDraw::DrawProjGroup::addProjection(), App::PropertyXLinkContainer::afterRestore(), Gui::ExpressionBinding::apply(), Gui::Document::canClose(), SurfaceGui::FillingEdgePanel::checkOpenCommand(), SurfaceGui::FillingVertexPanel::checkOpenCommand(), SurfaceGui::GeomFillSurface::checkOpenCommand(), SurfaceGui::SectionsPanel::checkOpenCommand(), SurfaceGui::FillingPanel::checkOpenCommand(), TechDraw::ShapeExtractor::checkShape(), Part::Extrusion::computeFinalParameters(), Import::ExportOCAF::createNode(), Gui::Document::createView(), SpreadsheetGui::SheetModel::data(), Gui::ViewProviderIndex::data(), SpreadsheetGui::DlgBindSheet::DlgBindSheet(), Gui::DocumentObjectData::DocumentObjectData(), PartDesignGui::ViewProviderDatum::doubleClicked(), TechDrawGui::QGIViewPart::drawComplexSectionLine(), TechDrawGui::QGIViewPart::drawHighlight(), Gui::ViewProviderAnnotationLabel::drawImage(), TechDrawGui::QGIViewPart::drawSectionLine(), TechDrawGui::QGIWeldSymbol::drawTailText(), TechDrawGui::QGIWeldSymbol::drawTile(), Gui::ElementColors::ElementColors(), TechDraw::DrawParametricTemplate::execute(), Part::ImportBrep::execute(), Part::CurveNet::execute(), Part::ImportIges::execute(), Part::Face::execute(), Part::ImportStep::execute(), Drawing::FeaturePage::execute(), Part::Revolution::execute(), TechDraw::DrawViewSpreadsheet::execute(), Drawing::FeatureClip::execute(), Drawing::FeatureViewSpreadsheet::execute(), TechDraw::DrawViewDraft::execute(), TechDraw::DrawViewArch::execute(), App::FeatureTestAbsAddress::execute(), App::FeatureTestAttribute::execute(), Inspection::Feature::execute(), App::Document::exportGraphviz(), App::PropertyLinkBase::exportSubName(), App::OriginGroupExtension::extensionGetSubObject(), PartGui::FaceAppearances::FaceAppearances(), PartGui::DlgScale::findShapes(), PartGui::DlgExtrusion::findShapes(), Gui::Dialog::DlgPropertyLink::formatObject(), TechDraw::DrawTemplate::getAutofillValue(), TechDraw::DrawGeomHatch::getDecodedSpecsFromFile(), TechDraw::DrawProjGroup::getDirsFromFront(), App::Document::getFileName(), Spreadsheet::Cell::getFormattedQuantity(), Gui::LinkInfo::getLinkedLabel(), TechDraw::DrawTemplate::getPageNumbers(), TechDrawGui::TaskGeomHatch::getParameters(), TechDraw::DrawViewSpreadsheet::getSheetImage(), Import::ImportOCAF2::ImportOCAF2(), TechDraw::DrawHatch::isBitmapHatch(), App::Document::isSaved(), TechDraw::DrawHatch::isSvgHatch(), TechDraw::DrawViewSymbol::loadQDomDocument(), TechDrawGui::TaskLinkDim::loadToTree(), PartDesignGui::TaskSketchBasedParameters::make2DLabel(), TechDraw::DrawGeomHatch::makeLineSets(), TechDraw::DrawViewSection::makeLineSets(), Assembly::AssemblyObject::makeMbdJoint(), TechDraw::DrawViewSection::makeSectionCut(), TechDrawGui::QGITile::makeSymbol(), TechDrawGui::QGIRichAnno::mouseDoubleClickEvent(), PartDesignGui::TaskSketchBasedParameters::objectNameByLabel(), App::Document::onBeforeChange(), Gui::ViewProviderTextDocument::onChanged(), TechDraw::DrawGeomHatch::onChanged(), Gui::ViewProviderAnnotation::onChanged(), TechDraw::DrawViewDetail::onChanged(), TechDraw::DrawHatch::onChanged(), TechDraw::DrawSVGTemplate::onChanged(), TechDraw::DrawTileWeld::onChanged(), TechDraw::DrawViewImage::onChanged(), TechDraw::DrawViewSection::onChanged(), TechDraw::DrawPage::onChanged(), TechDrawGui::TaskWeldingSymbol::onFlipSidesClicked(), TechDraw::DrawViewPart::onHlrFinished(), TechDrawGui::TaskComplexSection::onProfileObjectsUseSelectionClicked(), Gui::MDIView::onRelabel(), DrawingGui::DrawingView::onRelabel(), PartDesignGui::TaskBooleanParameters::onSelectionChanged(), SurfaceGui::FillingVertexPanel::onSelectionChanged(), SurfaceGui::FillingEdgePanel::onSelectionChanged(), SurfaceGui::GeomFillSurface::onSelectionChanged(), SurfaceGui::SectionsPanel::onSelectionChanged(), SurfaceGui::FillingPanel::onSelectionChanged(), App::Application::openDocumentPrivate(), App::DocumentObjectT::operator=(), parseLink(), App::Document::recompute(), App::OriginGroupExtension::relinkToOrigin(), App::Document::restore(), App::Document::Restore(), Fem::PropertyPostDataObject::RestoreDocFile(), Sandbox::DocumentSaverThread::run(), Gui::Document::Save(), App::Document::save(), Gui::Document::saveAs(), App::VRMLObject::SaveDocFile(), Fem::PropertyPostDataObject::SaveDocFile(), TechDrawGui::TaskHatch::saveHatchState(), TechDrawGui::TaskSectionView::saveSectionState(), TechDrawGui::TaskComplexSection::saveSectionState(), Import::ExportOCAF::saveShape(), SurfaceGui::FillingEdgePanel::setEditedObject(), SurfaceGui::SectionsPanel::setEditedObject(), SurfaceGui::FillingPanel::setEditedObject(), Gui::ExpressionBinding::setExpression(), RobotGui::TaskEdge2TracParameter::setHideShowObject(), Import::ImportOCAF2::setMode(), Gui::Dialog::DlgInspector::setNodeNames(), App::PropertyLinkSub::setPyObject(), App::PropertyLinkSubList::setPyObject(), TechDrawGui::QGIRichAnno::setTextItem(), TechDrawGui::TaskComplexSection::setUiCommon(), TechDrawGui::TaskSectionView::setUiEdit(), TechDrawGui::TaskComplexSection::setUiEdit(), TechDrawGui::TaskRichAnno::setUiEdit(), TechDrawGui::TaskWeldingSymbol::setUiEdit(), TechDrawGui::TaskDetail::setUiFromFeat(), TechDrawGui::TaskDimRepair::setUiPrimary(), PartDesignGui::TaskRevolutionParameters::setupDialog(), PartDesignGui::TaskExtrudeParameters::setupDialog(), TechDraw::DrawHatch::setupObject(), TechDraw::DrawGeomHatch::setupObject(), TechDraw::DrawTileWeld::setupObject(), TechDraw::DrawViewImage::setupObject(), TechDraw::DrawViewSection::setupObject(), PartDesignGui::TaskTransformedParameters::setupTransaction(), DrawingGui::ViewProviderDrawingPage::showDrawingView(), Gui::AutoSaver::slotCreateDocument(), TechDrawGui::QGIViewSymbol::symbolScaler(), FemGui::TaskFemConstraintDisplacement::TaskFemConstraintDisplacement(), FemGui::TaskObjectName::TaskObjectName(), PartDesignGui::TaskPipeOrientation::TaskPipeOrientation(), PartDesignGui::TaskPipeParameters::TaskPipeParameters(), App::PropertyLinkBase::tryReplaceLink(), TechDraw::DrawProjGroupItem::unsetupObject(), PartDesign::SubShapeBinder::update(), DrawingGui::ViewProviderDrawingPage::updateData(), Gui::ViewProviderInventorObject::updateData(), App::ObjectIdentifier::updateLabelReference(), App::PropertyLinkBase::updateLabelReferences(), TechDrawGui::TaskDimRepair::updateUi(), App::Document::~Document(), TechDraw::DrawViewDetail::~DrawViewDetail(), TechDraw::DrawViewPart::~DrawViewPart(), and TechDraw::DrawViewSection::~DrawViewSection().
isEmpty()
bool App::PropertyString::isEmpty () inline
Definition at line 765 of file PropertyStandard.h.
Referenced by TechDraw::DrawGeomHatch::makeLineSets(), TechDraw::DrawViewSection::makeLineSets(), and TechDraw::DrawViewSymbol::onChanged().
isSame()
bool App::PropertyString::isSame (const Property & other) const inline override virtual
Compare if this property has the same content as the given one.
Reimplemented from App::Property.
Reimplemented in App::PropertyFont.
Definition at line 787 of file PropertyStandard.h.
References Base::Persistence::getTypeId().
Paste()
void PropertyString::Paste (const Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Reimplemented in App::PropertyPersistentObject.
Definition at line 1595 of file PropertyStandard.cpp.
Restore()
void PropertyString::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Reimplemented in App::PropertyPersistentObject.
Definition at line 1561 of file PropertyStandard.cpp.
References TechDrawTools.TaskFillTemplateFields::reader.
Save()
void PropertyString::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Reimplemented in App::PropertyPersistentObject.
Definition at line 1539 of file PropertyStandard.cpp.
References Base::Writer::ind(), Base::Writer::Stream(), and toolbit-attributes::val.
setPathValue()
void PropertyString::setPathValue (const App::ObjectIdentifier & path, const boost::any & value) override virtual
Set value of property.
Reimplemented from App::Property.
Definition at line 1605 of file PropertyStandard.cpp.
References src.Mod.Test.testPathArray::path, and App::pyObjectFromAny().
setPyObject()
void PropertyString::setPyObject (PyObject * py) override virtual
Reimplemented from Base::BaseClass.
Definition at line 1523 of file PropertyStandard.cpp.
References Path.Log::error().
Referenced by parseLink(), App::PropertyFile::setPyObject(), App::PropertyLinkSub::setPyObject(), App::PropertyLinkSubList::setPyObject(), and App::PropertyXLink::setPyObject().
setValue() [1/2]
void PropertyString::setValue (const char * sString) virtual
Reimplemented in App::PropertyPersistentObject.
Definition at line 1378 of file PropertyStandard.cpp.
References SCL.SimpleDataTypes::c, App::Application::closeActiveTransaction(), toolbit-attributes::doc, DraftVecUtils::find(), App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), Base::Tools::getUniqueName(), App::Application::GetUserParameter(), App::Document::Importing, NavigationIndicatorGui::label, replaceobj::objs, App::Document::Restoring, App::Application::setActiveTransaction(), Path.Post.scripts.refactored_centroid_post::str, and App::PropertyLinkBase::updateLabelReferences().
Referenced by App::Document::_removeObject(), Gui::Dialog::DlgProjectInformationImp::accept(), MeshGui::Segmentation::accept(), ReverseEngineeringGui::Segmentation::accept(), FemGui::TaskDlgCreateNodeSet::accept(), FemGui::TaskDlgCreateElementSet::accept(), TechDrawGui::TaskCustomizeFormat::accept(), TechDrawGui::TaskSurfaceFinishSymbols::accept(), MeshGui::SegmentationBestFit::accept(), App::Document::addObject(), App::Document::addObjects(), TechDraw::DrawProjGroup::addProjection(), TechDrawGui::TaskRichAnno::commonFeatureUpdate(), TechDrawGui::TaskRichAnno::createAnnoFeature(), TechDrawGui::QGSPage::createBalloon(), TDHandlerDimension::createDistanceDimension(), PartGui::DlgProjectionOnSurface::DlgProjectionOnSurface(), execCreateHorizChamferDimension(), execCreateVertChamferDimension(), TechDraw::DrawViewSpreadsheet::execute(), Drawing::FeatureViewSpreadsheet::execute(), App::FeatureTest::execute(), App::PropertyXLink::getPyObject(), App::PropertyXLinkSub::getPyObject(), App::PropertyEnumeration::getPyPathValue(), Part::AttachExtension::initBase(), MeshPartGui::Mesh2ShapeGmsh::loadOutput(), Import::ImportOCAF2::loadShapes(), TechDrawGui::makeArcLengthDimension(), MeshGui::MeshSplit::makeCopy(), TechDrawGui::QGIRichAnno::mouseDoubleClickEvent(), App::Application::newDocument(), TechDraw::DrawViewDetail::onChanged(), App::Document::onChanged(), TechDrawGui::TaskGeomHatch::onFileChanged(), TechDraw::DrawWeldSymbol::onSettingDocument(), App::Application::openDocumentPrivate(), TechDrawGui::TaskGeomHatch::reject(), App::Document::removeObject(), App::Document::Restore(), TechDrawGui::TaskHatch::restoreHatchState(), TechDrawGui::TaskSectionView::restoreSectionState(), TechDrawGui::TaskComplexSection::restoreSectionState(), Sandbox::DocumentTestThread::run(), App::Document::save(), App::Document::saveAs(), Gui::DocumentItem::setData(), Spreadsheet::Sheet::setStringProperty(), Part::Face::setupObject(), TechDraw::DrawHatch::translateLabel(), TechDraw::DrawGeomHatch::translateLabel(), TechDraw::DrawSVGTemplate::translateLabel(), TechDraw::DrawView::translateLabel(), TechDraw::DrawPage::translateLabel(), TechDrawGui::TaskProjGroup::turnProjGroupToView(), TechDrawGui::TaskDetail::updateDetail(), TechDraw::DrawViewSymbol::updateFieldsInSymbol(), TechDrawGui::TaskWeldingSymbol::updateTiles(), TechDrawGui::TaskGeomHatch::updateValues(), and TechDrawGui::TaskWeldingSymbol::updateWeldingSymbol().
setValue() [2/2]
void PropertyString::setValue (const std::string & sString)
Definition at line 1504 of file PropertyStandard.cpp.
Member Data Documentation
_cValue
std::string App::PropertyString::_cValue protected
Definition at line 797 of file PropertyStandard.h.
The documentation for this class was generated from the following files:
PropertyStandard.h
PropertyStandard.cpp