FreeCAD: App::StringIDRef Class Reference
App::StringIDRef Class Reference
#include <StringHasher.h>
Public Member Functions
StringIDRef ()
StringIDRef (StringID *stringID, int index=0)
StringIDRef (const StringIDRef &other)
Copy construction results in an incremented reference count for the stored StringID.
StringIDRef (StringIDRef &&other) noexcept
StringIDRef (const StringIDRef &other, int index)
~StringIDRef ()
void reset (const StringIDRef &stringID=StringIDRef())
void reset (const StringIDRef &stringID, int index)
void swap (StringIDRef &stringID)
StringIDRef & operator= (StringID *stringID)
StringIDRef & operator= (const StringIDRef &stringID)
StringIDRef & operator= (StringIDRef &&stringID) noexcept
bool operator< (const StringIDRef &stringID) const
bool operator== (const StringIDRef &stringID) const
bool operator!= (const StringIDRef &stringID) const
operator bool () const
int getRefCount () const
std::string toString () const
std::string dataToText () const
const char * constData () const
const StringID & deref () const
long value () const
QVector< StringIDRef > relatedIDs () const
bool isBinary () const
bool isHashed () const
void toBytes (QByteArray &bytes) const
PyObject * getPyObject ()
void mark () const
bool isMarked () const
bool isFromSameHasher (const StringHasherRef &hasher) const
StringHasherRef getHasher () const
void setPersistent (bool enable)
int getIndex () const
Friends
class StringHasher
Detailed Description
Counted reference to a StringID instance
Definition at line 324 of file StringHasher.h.
Constructor & Destructor Documentation
StringIDRef() [1/5]
App::StringIDRef::StringIDRef () inline
Default construction results in an empty StringIDRef object: it will evaluate to boolean "false" if queried.
Definition at line 329 of file StringHasher.h.
StringIDRef() [2/5]
App::StringIDRef::StringIDRef (StringID * stringID, int index = 0) inline
Standard construction from a heap-allocated StringID. This reference-counting class manages the lifetime of the StringID, ensuring it is deallocated when its reference count goes to zero.
Parameters
stringID A pointer to a StringID allocated with "new"
index (optional) An index value to store along with the StringID. Defaults to zero.
Definition at line 339 of file StringHasher.h.
References Base::Handled::ref().
StringIDRef() [3/5]
App::StringIDRef::StringIDRef (const StringIDRef & other) inline
Copy construction results in an incremented reference count for the stored StringID.
Definition at line 349 of file StringHasher.h.
References Base::Handled::ref().
StringIDRef() [4/5]
App::StringIDRef::StringIDRef (StringIDRef && other) inline noexcept
Move construction does NOT increase the reference count of the StringID (instead, it invalidates the pointer in the moved object).
Definition at line 360 of file StringHasher.h.
StringIDRef() [5/5]
App::StringIDRef::StringIDRef (const StringIDRef & other, int index) inline
Definition at line 367 of file StringHasher.h.
References Base::Handled::ref().
~StringIDRef()
App::StringIDRef::~StringIDRef () inline
Definition at line 376 of file StringHasher.h.
References Base::Handled::unref().
Member Function Documentation
constData()
const char* App::StringIDRef::constData () const inline
Get a reference to the data: only makes sense if index and postfix are both empty, but calling code is responsible for ensuring that.
Definition at line 512 of file StringHasher.h.
References App::StringID::data(), and App::StringID::postfix().
dataToText()
std::string App::StringIDRef::dataToText () const inline
Definition at line 502 of file StringHasher.h.
References App::StringID::dataToText().
deref()
const StringID& App::StringIDRef::deref () const inline
Definition at line 522 of file StringHasher.h.
getHasher()
StringHasherRef App::StringIDRef::getHasher () const inline
Definition at line 593 of file StringHasher.h.
References App::StringID::getHasher().
getIndex()
int App::StringIDRef::getIndex () const inline
Used predominantly by the unit test code to verify that index is set correctly. In general user code should not need to call this function.
Definition at line 610 of file StringHasher.h.
getPyObject()
PyObject* App::StringIDRef::getPyObject () inline
Definition at line 567 of file StringHasher.h.
References App::StringID::getPyObjectWithIndex().
getRefCount()
int App::StringIDRef::getRefCount () const inline
Definition at line 486 of file StringHasher.h.
References Base::Handled::getRefCount().
isBinary()
bool App::StringIDRef::isBinary () const inline
Definition at line 543 of file StringHasher.h.
References App::StringID::isBinary().
Referenced by App::StringHasher::restoreStream().
isFromSameHasher()
bool App::StringIDRef::isFromSameHasher (const StringHasherRef & hasher) const inline
Definition at line 588 of file StringHasher.h.
References App::StringID::isFromSameHasher().
isHashed()
bool App::StringIDRef::isHashed () const inline
Definition at line 551 of file StringHasher.h.
References App::StringID::isHashed().
Referenced by App::StringHasher::restoreStream().
isMarked()
bool App::StringIDRef::isMarked () const inline
Definition at line 583 of file StringHasher.h.
References App::StringID::isMarked().
mark()
void App::StringIDRef::mark () const inline
Definition at line 576 of file StringHasher.h.
References App::StringID::mark().
operator bool()
App::StringIDRef::operator bool () const inline explicit
Definition at line 481 of file StringHasher.h.
operator!=()
bool App::StringIDRef::operator!= (const StringIDRef & stringID) const inline
Definition at line 476 of file StringHasher.h.
operator<()
bool App::StringIDRef::operator< (const StringIDRef & stringID) const inline
Definition at line 450 of file StringHasher.h.
References App::StringID::compare().
operator=() [1/3]
StringIDRef& App::StringIDRef::operator= (const StringIDRef & stringID) inline
Definition at line 419 of file StringHasher.h.
References Base::Handled::ref(), and Base::Handled::unref().
operator=() [2/3]
StringIDRef& App::StringIDRef::operator= (StringID * stringID) inline
Definition at line 403 of file StringHasher.h.
References Base::Handled::ref(), and Base::Handled::unref().
operator=() [3/3]
StringIDRef& App::StringIDRef::operator= (StringIDRef && stringID) inline noexcept
Definition at line 437 of file StringHasher.h.
References Base::Handled::unref().
operator==()
bool App::StringIDRef::operator== (const StringIDRef & stringID) const inline
Definition at line 468 of file StringHasher.h.
References App::StringID::compare().
relatedIDs()
QVector<StringIDRef> App::StringIDRef::relatedIDs () const inline
Definition at line 535 of file StringHasher.h.
References App::StringID::relatedIDs().
reset() [1/2]
void App::StringIDRef::reset (const StringIDRef & stringID, int index) inline
Definition at line 388 of file StringHasher.h.
Referenced by ArchVRM.Renderer::__init__(), draftguitools.gui_trackers.gridTracker::set(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testAll(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
reset() [2/2]
void App::StringIDRef::reset (const StringIDRef & stringID = StringIDRef()) inline
Definition at line 383 of file StringHasher.h.
Referenced by ArchVRM.Renderer::__init__(), draftguitools.gui_trackers.gridTracker::set(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testAll(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
setPersistent()
void App::StringIDRef::setPersistent (bool enable) inline
Definition at line 601 of file StringHasher.h.
References App::StringID::setPersistent().
swap()
void App::StringIDRef::swap (StringIDRef & stringID) inline
Definition at line 394 of file StringHasher.h.
toBytes()
void App::StringIDRef::toBytes (QByteArray & bytes) const inline
Definition at line 559 of file StringHasher.h.
References App::StringID::dataToBytes().
Referenced by App::StringHasher::getID().
toString()
std::string App::StringIDRef::toString () const inline
Definition at line 494 of file StringHasher.h.
References App::StringID::toString().
value()
long App::StringIDRef::value () const inline
Definition at line 527 of file StringHasher.h.
References App::StringID::value().
Referenced by App::StringHasher::compact(), src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), App::StringHasher::insert(), and src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue().
Friends And Related Function Documentation
StringHasher
friend class StringHasher friend
Definition at line 615 of file StringHasher.h.
The documentation for this class was generated from the following file:
StringHasher.h