FreeCAD: PartDesignGui::TaskPocketParameters Class Reference
PartDesignGui::TaskPocketParameters Class Reference
#include <TaskPocketParameters.h>
Public Member Functions
TaskPocketParameters (ViewProviderPocket *PocketView, QWidget *parent=nullptr, bool newObj=false)
~TaskPocketParameters () override
void apply () override
apply changes made in the parameters input to the model via commands
Public Member Functions inherited from PartDesignGui::TaskExtrudeParameters
TaskExtrudeParameters (ViewProviderExtrude *ExtrudeView, QWidget *parent, const std::string &pixmapname, const QString &parname)
~TaskExtrudeParameters () override
void saveHistory () override
save field history
void fillDirectionCombo ()
void addAxisToCombo (App::DocumentObject *linkObj, std::string linkSubname, QString itemText, bool hasSketch=true)
void applyParameters (QString facename)
void setSelectionMode (SelectionMode mode)
Public Member Functions inherited from PartDesignGui::TaskSketchBasedParameters
TaskSketchBasedParameters (PartDesignGui::ViewProvider *vp, QWidget *parent, const std::string &pixmapname, const QString &parname)
~TaskSketchBasedParameters () override
Public Member Functions inherited from PartDesignGui::TaskFeatureParameters
TaskFeatureParameters (PartDesignGui::ViewProvider *vp, QWidget *parent, const std::string &pixmapname, const QString &parname)
~TaskFeatureParameters () override=default
void recomputeFeature ()
bool isUpdateBlocked () const
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Public Member Functions inherited from Gui::DocumentObserver
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
void attachDocument (Document *)
void detachDocument ()
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Additional Inherited Members
Public Types inherited from PartDesignGui::TaskExtrudeParameters
enum Type { Type::Pad, Type::Pocket }
enum Mode {
Mode::Dimension, Mode::ThroughAll, Mode::ToLast = ThroughAll, Mode::ToFirst,
Mode::ToFace, Mode::TwoDimensions, Mode::ToShape
}
enum SelectionMode {
None, SelectFace, SelectShape, SelectShapeFaces,
SelectReferenceAxis
}
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Protected Slots inherited from PartDesignGui::TaskExtrudeParameters
void onLengthChanged (double)
void onLength2Changed (double)
void onOffsetChanged (double)
void onTaperChanged (double)
void onTaper2Changed (double)
void onDirectionCBChanged (int)
void onAlongSketchNormalChanged (bool)
void onDirectionToggled (bool)
void onAllFacesToggled (bool)
void onXDirectionEditChanged (double)
void onYDirectionEditChanged (double)
void onZDirectionEditChanged (double)
void onMidplaneChanged (bool)
void onReversedChanged (bool)
void onFaceName (const QString &text)
void onSelectFaceToggle (const bool checked=true)
void onSelectShapeToggle (const bool checked=true)
void onSelectShapeFacesToggle (const bool checked)
void onUnselectShapeFacesTrigger ()
Protected Slots inherited from PartDesignGui::TaskFeatureParameters
void onUpdateView (bool on)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Member Functions inherited from PartDesignGui::TaskExtrudeParameters
void setCheckboxes (Mode mode, Type type)
void setupDialog ()
void readValuesFromHistory ()
void changeEvent (QEvent *e) override
void getReferenceAxis (App::DocumentObject *&obj, std::vector< std::string > &sub) const
double getOffset () const
bool getAlongSketchNormal () const
bool getCustom () const
std::string getReferenceAxis () const
double getXDirection () const
double getYDirection () const
double getZDirection () const
bool getReversed () const
bool getMidplane () const
int getMode () const
QString getFaceName () const
void onSelectionChanged (const Gui::SelectionChanges &msg) override
void updateDirectionEdits ()
void setDirectionMode (int index)
void handleLineFaceNameClick ()
void handleLineFaceNameNo ()
Protected Member Functions inherited from PartDesignGui::TaskSketchBasedParameters
const QString onAddSelection (const Gui::SelectionChanges &msg)
virtual void startReferenceSelection (App::DocumentObject *profile, App::DocumentObject *base)
virtual void finishReferenceSelection (App::DocumentObject *profile, App::DocumentObject *base)
void onSelectReference (AllowSelectionFlags)
onSelectReference Start reference selection mode to allow one to select objects of the type defined with AllowSelectionFlags. If AllowSelection::NONE is passed the selection mode is finished.
void exitSelectionMode ()
QVariant setUpToFace (const QString &text)
QVariant objectNameByLabel (const QString &label, const QVariant &suggest) const
QString getFaceReference (const QString &obj, const QString &sub) const
QString make2DLabel (const App::DocumentObject *section, const std::vector< std::string > &subValues)
Protected Member Functions inherited from PartDesignGui::TaskFeatureParameters
template<typename T = PartDesignGui::ViewProvider>
T * getViewObject () const
template<typename T = App::DocumentObject>
T * getObject () const
Gui::Document * getGuiDocument () const
App::Document * getAppDocument () const
bool & getUpdateBlockRef ()
void setUpdateBlocked (bool value)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Protected Attributes inherited from PartDesignGui::TaskExtrudeParameters
App::PropertyLinkSub * propReferenceAxis
QWidget * proxy
QAction * unselectShapeFaceAction
std::unique_ptr< Ui_TaskPadPocketParameters > ui
std::vector< std::unique_ptr< App::PropertyLinkSub > > axesInList
SelectionMode selectionMode = None
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
Definition at line 41 of file TaskPocketParameters.h.
Constructor & Destructor Documentation
TaskPocketParameters()
TaskPocketParameters::TaskPocketParameters (ViewProviderPocket * PocketView, QWidget * parent = nullptr, bool newObj = false) explicit
Definition at line 39 of file TaskPocketParameters.cpp.
References PartDesignGui::TaskExtrudeParameters::readValuesFromHistory(), PartDesignGui::TaskExtrudeParameters::setupDialog(), and PartDesignGui::TaskExtrudeParameters::ui.
~TaskPocketParameters()
TaskPocketParameters::~TaskPocketParameters () override default
Member Function Documentation
apply()
void TaskPocketParameters::apply () override virtual
apply changes made in the parameters input to the model via commands
Reimplemented from PartDesignGui::TaskFeatureParameters.
Definition at line 136 of file TaskPocketParameters.cpp.
References PartDesignGui::TaskExtrudeParameters::applyParameters(), PartDesignGui::TaskExtrudeParameters::getFaceName(), PartDesignGui::TaskExtrudeParameters::getMode(), and PartDesignGui::TaskExtrudeParameters::ToFace.
The documentation for this class was generated from the following files:
TaskPocketParameters.h
TaskPocketParameters.cpp