FreeCAD: Web::AppServer Class Reference
Web::AppServer Class Reference
#include <Server.h>
Public Member Functions
AppServer (bool direct=false, QObject *parent=nullptr)
Protected Member Functions
void incomingConnection (qintptr socket) override
void customEvent (QEvent *e) override
Detailed Description
The Server class implements a simple TCP server.
Definition at line 99 of file Server.h.
Constructor & Destructor Documentation
AppServer()
AppServer::AppServer (bool direct = false, QObject * parent = nullptr) explicit
Definition at line 107 of file Server.cpp.
References mod.
Member Function Documentation
customEvent()
void AppServer::customEvent (QEvent * e) override protected
Definition at line 154 of file Server.cpp.
References SCL.SimpleDataTypes::e, Path.Op.Surface::msg, Web::ServerEvent::request(), Web::ServerEvent::socket(), and Path.Post.scripts.refactored_centroid_post::str.
incomingConnection()
void AppServer::incomingConnection (qintptr socket) override protected
Definition at line 120 of file Server.cpp.
References draftgeoutils.intersections::connect().
The documentation for this class was generated from the following files:
Server.h
Server.cpp