FreeCAD: MatGui::Array3D Class Reference
MatGui::Array3D Class Reference
#include <Array3D.h>
Public Member Functions
Array3D (const QString &propertyName, const std::shared_ptr< Materials::Material > &material, QWidget *parent=nullptr)
~Array3D () override=default
void onRowsInserted (const QModelIndex &parent, int first, int last)
void onRowsRemoved (const QModelIndex &parent, int first, int last)
void onDataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight, const QVector< int > &roles=QVector< int >())
void onSelectDepth (const QItemSelection &selected, const QItemSelection &deselected)
bool onSplitter (QEvent *e)
void onDepthDelete (bool checked)
int confirmDepthDelete ()
void deleteDepthSelected ()
void on2DDelete (bool checked)
int confirm2dDelete ()
void delete2DSelected ()
void onDepthContextMenu (const QPoint &pos)
void on2DContextMenu (const QPoint &pos)
void onOk (bool checked)
void onCancel (bool checked)
Detailed Description
Definition at line 56 of file Array3D.h.
Constructor & Destructor Documentation
Array3D()
Array3D::Array3D (const QString & propertyName, const std::shared_ptr< Materials::Material > & material, QWidget * parent = nullptr)
Definition at line 41 of file Array3D.cpp.
References draftgeoutils.intersections::connect(), Base::Console(), Base::ConsoleSingleton::Log(), on2DContextMenu(), on2DDelete(), onCancel(), onDepthContextMenu(), onDepthDelete(), onOk(), onSelectDepth(), and propertyName().
~Array3D()
MatGui::Array3D::~Array3D () override default
Member Function Documentation
confirm2dDelete()
int Array3D::confirm2dDelete ()
Definition at line 331 of file Array3D.cpp.
References MengerSponge::box, and delete2DSelected().
Referenced by on2DDelete().
confirmDepthDelete()
int Array3D::confirmDepthDelete ()
Definition at line 259 of file Array3D.cpp.
References MengerSponge::box, and deleteDepthSelected().
Referenced by onDepthDelete().
delete2DSelected()
void Array3D::delete2DSelected ()
Definition at line 356 of file Array3D.cpp.
Referenced by confirm2dDelete().
deleteDepthSelected()
void Array3D::deleteDepthSelected ()
Definition at line 285 of file Array3D.cpp.
Referenced by confirmDepthDelete().
on2DContextMenu()
void Array3D::on2DContextMenu (const QPoint & pos)
Definition at line 300 of file Array3D.cpp.
References RobotExample::pos.
Referenced by Array3D().
on2DDelete()
void Array3D::on2DDelete (bool checked)
Definition at line 316 of file Array3D.cpp.
References confirm2dDelete().
Referenced by Array3D().
onCancel()
void Array3D::onCancel (bool checked)
Definition at line 373 of file Array3D.cpp.
Referenced by Array3D().
onDataChanged()
void Array3D::onDataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight, const QVector< int > & roles = QVector<int>())
Definition at line 155 of file Array3D.cpp.
onDepthContextMenu()
void Array3D::onDepthContextMenu (const QPoint & pos)
Definition at line 229 of file Array3D.cpp.
References RobotExample::pos.
Referenced by Array3D().
onDepthDelete()
void Array3D::onDepthDelete (bool checked)
Definition at line 244 of file Array3D.cpp.
References confirmDepthDelete().
Referenced by Array3D().
onOk()
void Array3D::onOk (bool checked)
Definition at line 366 of file Array3D.cpp.
Referenced by Array3D().
onRowsInserted()
void Array3D::onRowsInserted (const QModelIndex & parent, int first, int last)
Definition at line 137 of file Array3D.cpp.
References Init::parent.
onRowsRemoved()
void Array3D::onRowsRemoved (const QModelIndex & parent, int first, int last)
Definition at line 146 of file Array3D.cpp.
References Init::parent.
onSelectDepth()
void Array3D::onSelectDepth (const QItemSelection & selected, const QItemSelection & deselected)
Definition at line 206 of file Array3D.cpp.
Referenced by Array3D().
onSplitter()
bool Array3D::onSplitter (QEvent * e)
Definition at line 99 of file Array3D.cpp.
References SCL.SimpleDataTypes::e.
The documentation for this class was generated from the following files:
Array3D.h
Array3D.cpp