FreeCAD: PropertyView.cpp File Reference
PropertyView.cpp File Reference
#include "PreCompiled.h"
#include <QEvent>
#include <QGridLayout>
#include <QTimer>
#include <App/Document.h>
#include <App/DocumentObject.h>
#include <Base/Console.h>
#include <Base/Parameter.h>
#include <Base/Tools.h>
#include "PropertyView.h"
#include "Application.h"
#include "Document.h"
#include "MainWindow.h"
#include "SelectionObject.h"
#include "Tree.h"
#include "ViewParams.h"
#include "ViewProvider.h"
#include "ViewProviderDocumentObject.h"
#include "propertyeditor/PropertyEditor.h"
#include "moc_PropertyView.cpp"
Classes
struct Gui::PropertyView::PropInfo
struct Gui::PropertyView::PropFind
Functions
static ParameterGrp::handle _GetParam ()
Variables
static bool _ShowAll
Function Documentation
_GetParam()
static ParameterGrp::handle _GetParam () static
Definition at line 54 of file PropertyView.cpp.
References App::GetApplication(), and App::Application::GetParameterGroupByPath().
Referenced by Gui::PropertyView::PropertyView(), and Gui::PropertyView::tabChanged().
Variable Documentation
_ShowAll
bool _ShowAll static
Definition at line 161 of file PropertyView.cpp.
Referenced by Gui::PropertyView::setShowAll(), and Gui::PropertyView::showAll().