FreeCAD: App::ObjectIdentifier::String Class Reference
App::ObjectIdentifier::String Class Reference
#include <ObjectIdentifier.h>
Public Member Functions
String (const std::string &s="", bool _isRealString=false, bool _forceIdentifier=false)
String (std::string &&s, bool _isRealString=false, bool _forceIdentifier=false)
String (const String &)=default
String & operator= (const String &)=default
String (String &&other)
String & operator= (String &&other)
const std::string & getString () const
bool isRealString () const
bool isForceIdentifier () const
std::string toString (bool toPython=false) const
Get a string representation of this object identifier.
operator std::string () const
operator const char * () const
bool operator== (const String &other) const
bool operator!= (const String &other) const
bool operator>= (const String &other) const
bool operator< (const String &other) const
bool operator> (const String &other) const
void checkImport (const App::DocumentObject *owner, const App::DocumentObject *obj=nullptr, String *objName=nullptr)
Friends
class ObjectIdentifier
Detailed Description
Definition at line 88 of file ObjectIdentifier.h.
Constructor & Destructor Documentation
String() [1/4]
App::ObjectIdentifier::String::String (const std::string & s = "", bool _isRealString = false, bool _forceIdentifier = false) inline
Definition at line 93 of file ObjectIdentifier.h.
String() [2/4]
App::ObjectIdentifier::String::String (std::string && s, bool _isRealString = false, bool _forceIdentifier = false) inline explicit
Definition at line 99 of file ObjectIdentifier.h.
String() [3/4]
App::ObjectIdentifier::String::String (const String &) default
String() [4/4]
App::ObjectIdentifier::String::String (String && other) inline
Definition at line 105 of file ObjectIdentifier.h.
References Path.Post.scripts.opensbp_post::move(), and Path.Post.scripts.refactored_centroid_post::str.
Member Function Documentation
checkImport()
void ObjectIdentifier::String::checkImport (const App::DocumentObject * owner, const App::DocumentObject * obj = nullptr, String * objName = nullptr)
Definition at line 1650 of file ObjectIdentifier.cpp.
References FC_ERR, App::DocumentObject::getDocument(), App::ObjectIdentifier::getDocumentObject(), App::Document::getObject(), App::PropertyLinkBase::importSubName(), App::ObjectIdentifier::owner, TechDrawTools.TaskFillTemplateFields::reader, App::ExpressionParser::ExpressionImporter::reader(), App::PropertyLinkBase::restoreLabelReference(), Path.Post.scripts.refactored_centroid_post::str, and toString().
getString()
const std::string& App::ObjectIdentifier::String::getString () const inline
Returns the string
Definition at line 116 of file ObjectIdentifier.h.
References Path.Post.scripts.refactored_centroid_post::str.
Referenced by App::ObjectIdentifier::access(), Sketcher::SketchObject::carbonCopy(), App::ObjectIdentifier::getDepLabels(), App::ObjectIdentifier::getDocument(), App::ObjectIdentifier::getPropertyComponents(), App::ObjectIdentifier::getStringList(), App::ObjectIdentifier::getSubObjectName(), App::ObjectIdentifier::hasDocumentObjectName(), App::ObjectIdentifier::importSubNames(), App::ObjectIdentifier::relabeledDocument(), App::ObjectIdentifier::replaceObject(), App::ObjectIdentifier::resolve(), App::ObjectIdentifier::resolveAmbiguity(), App::ObjectIdentifier::ResolveResults::resolveErrorString(), App::ObjectIdentifier::resolveProperty(), App::ObjectIdentifier::toPersistentString(), App::ObjectIdentifier::toString(), App::ObjectIdentifier::updateElementReference(), and App::ObjectIdentifier::updateLabelReference().
isForceIdentifier()
bool App::ObjectIdentifier::String::isForceIdentifier () const inline
Definition at line 127 of file ObjectIdentifier.h.
Referenced by App::ObjectIdentifier::getDocument(), App::ObjectIdentifier::getDocumentObject(), App::ObjectIdentifier::resolveAmbiguity(), and App::ObjectIdentifier::updateLabelReference().
isRealString()
bool App::ObjectIdentifier::String::isRealString () const inline
Return true is string need to be quoted
Definition at line 122 of file ObjectIdentifier.h.
Referenced by App::ObjectIdentifier::getDepLabels(), App::ObjectIdentifier::getDocument(), App::ObjectIdentifier::getDocumentObject(), App::ObjectIdentifier::importSubNames(), App::ObjectIdentifier::relabeledDocument(), App::ObjectIdentifier::replaceObject(), App::ObjectIdentifier::resolveAmbiguity(), App::ObjectIdentifier::setDocumentObjectName(), App::ObjectIdentifier::toPersistentString(), and App::ObjectIdentifier::updateLabelReference().
operator const char *()
App::ObjectIdentifier::String::operator const char * () const inline explicit
Definition at line 142 of file ObjectIdentifier.h.
References Path.Post.scripts.refactored_centroid_post::str.
operator std::string()
App::ObjectIdentifier::String::operator std::string () const inline explicit
Definition at line 137 of file ObjectIdentifier.h.
References Path.Post.scripts.refactored_centroid_post::str.
operator!=()
bool App::ObjectIdentifier::String::operator!= (const String & other) const inline
Definition at line 152 of file ObjectIdentifier.h.
References Path.Post.scripts.refactored_centroid_post::str.
operator<()
bool App::ObjectIdentifier::String::operator< (const String & other) const inline
Definition at line 162 of file ObjectIdentifier.h.
References Path.Post.scripts.refactored_centroid_post::str.
operator=() [1/2]
String& App::ObjectIdentifier::String::operator= (const String &) default
operator=() [2/2]
String& App::ObjectIdentifier::String::operator= (String && other) inline
Definition at line 105 of file ObjectIdentifier.h.
operator==()
bool App::ObjectIdentifier::String::operator== (const String & other) const inline
Definition at line 147 of file ObjectIdentifier.h.
References Path.Post.scripts.refactored_centroid_post::str.
operator>()
bool App::ObjectIdentifier::String::operator> (const String & other) const inline
Definition at line 167 of file ObjectIdentifier.h.
References Path.Post.scripts.refactored_centroid_post::str.
operator>=()
bool App::ObjectIdentifier::String::operator>= (const String & other) const inline
Definition at line 157 of file ObjectIdentifier.h.
References Path.Post.scripts.refactored_centroid_post::str.
toString()
std::string ObjectIdentifier::String::toString (bool toPython = false) const
Get a string representation of this object identifier.
Returns a possibly quoted string
Returns
String representation.
Definition at line 1640 of file ObjectIdentifier.cpp.
References App::quote(), and Path.Post.scripts.refactored_centroid_post::str.
Referenced by checkImport(), App::ObjectIdentifier::getDocument(), App::ObjectIdentifier::getStringList(), App::ObjectIdentifier::ResolveResults::resolveErrorString(), App::ObjectIdentifier::resolveProperty(), App::ObjectIdentifier::toPersistentString(), and App::ObjectIdentifier::toString().
Friends And Related Function Documentation
ObjectIdentifier
friend class ObjectIdentifier friend
Definition at line 90 of file ObjectIdentifier.h.
The documentation for this class was generated from the following files:
ObjectIdentifier.h
ObjectIdentifier.cpp