FreeCAD: ExpressionLabel Class Reference
ExpressionLabel Class Reference
#include <QuantitySpinBox_p.h>
Signals
void clicked ()
Public Member Functions
ExpressionLabel (QWidget *parent)
void setExpressionText (const QString &text)
Protected Member Functions
void mouseReleaseEvent (QMouseEvent *event) override
Detailed Description
Definition at line 29 of file QuantitySpinBox_p.h.
Constructor & Destructor Documentation
ExpressionLabel()
ExpressionLabel::ExpressionLabel (QWidget * parent) inline
Definition at line 53 of file QuantitySpinBox_p.h.
Member Function Documentation
clicked
void ExpressionLabel::clicked () signal
Referenced by Gui::ExpLineEdit::ExpLineEdit(), and Gui::ExpressionSpinBox::ExpressionSpinBox().
mouseReleaseEvent()
void ExpressionLabel::mouseReleaseEvent (QMouseEvent * event) inline override protected
Definition at line 63 of file QuantitySpinBox_p.h.
setExpressionText()
void ExpressionLabel::setExpressionText (const QString & text) inline
Definition at line 55 of file QuantitySpinBox_p.h.
Referenced by Gui::ExpressionSpinBox::clearExpression(), Gui::ExpressionWidget::makeLabel(), Gui::ExpLineEdit::resizeEvent(), and Gui::ExpressionSpinBox::showValidExpression().
The documentation for this class was generated from the following file:
QuantitySpinBox_p.h