FreeCAD: bimcommands.BimShape2DView.BIM_Shape2DCut Class Reference
bimcommands.BimShape2DView.BIM_Shape2DCut Class Reference
Public Member Functions
def GetResources (self)
def proceed (self)
Detailed Description
Definition at line 91 of file BimShape2DView.py.
Member Function Documentation
GetResources()
def bimcommands.BimShape2DView.BIM_Shape2DCut.GetResources (self)
Reimplemented from bimcommands.BimShape2DView.BIM_Shape2DView.
Definition at line 93 of file BimShape2DView.py.
References bimcommands.BimShape2DView.QT_TRANSLATE_NOOP.
proceed()
def bimcommands.BimShape2DView.BIM_Shape2DCut.proceed (self)
Proceed with the command if one object was selected.
Reimplemented from bimcommands.BimShape2DView.BIM_Shape2DView.
Definition at line 100 of file BimShape2DView.py.
Referenced by draftguitools.gui_split.Split.action(), bimcommands.BimSlab.BIM_Slab.Activated(), draftguitools.gui_pointarray.PointArray.Activated(), draftguitools.gui_move.Move.get_object_selection(), draftguitools.gui_rotate.Rotate.get_object_selection(), draftguitools.gui_scale.Scale.get_object_selection(), and draftguitools.gui_subelements.SubelementHighlight.get_selection().
The documentation for this class was generated from the following file:
BimShape2DView.py