FreeCAD: Cloud::Module Class Reference
Cloud::Module Class Reference
#include <AppCloud.h>
Public Member Functions
Module ()
virtual ~Module ()
bool cloudSave (const char *BucketName)
bool cloudRestore (const char *BucketName)
void LinkXSetValue (std::string filename)
Public Attributes
App::PropertyString URL
App::PropertyString TCPPort
App::PropertyString TokenAuth
App::PropertyString TokenSecret
App::PropertyString ProtocolVersion
App::PropertyString Region
Detailed Description
Definition at line 136 of file AppCloud.h.
Constructor & Destructor Documentation
Module()
Cloud::Module::Module () inline
Definition at line 139 of file AppCloud.h.
~Module()
virtual Cloud::Module::~Module () inline virtual
Definition at line 175 of file AppCloud.h.
Member Function Documentation
cloudRestore()
bool Cloud::Module::cloudRestore (const char * BucketName)
Definition at line 1473 of file AppCloud.cpp.
References draftgeoutils.faces::bind(), Base::Console(), toolbit-attributes::doc, SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), Cloud::CloudReader::FileEntry::FileStream, App::Application::getActiveDocument(), App::GetApplication(), Cloud::CloudReader::GetEntry(), LinkXSetValue(), TechDrawTools.TaskFillTemplateFields::reader, readFiles(), App::Document::Restoring, App::Application::signalFinishRestoreDocument, and App::Application::signalStartRestoreDocument.
cloudSave()
bool Cloud::Module::cloudSave (const char * BucketName)
Definition at line 1349 of file AppCloud.cpp.
References Base::Tools::currentDateTimeString(), toolbit-attributes::doc, App::Application::getActiveDocument(), App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), Cloud::CloudWriter::putNextEntry(), Base::Writer::setMode(), Cloud::CloudWriter::Stream(), and Cloud::CloudWriter::writeFiles().
LinkXSetValue()
void Cloud::Module::LinkXSetValue (std::string filename)
Definition at line 1440 of file AppCloud.cpp.
References App::Application::getActiveDocument(), App::GetApplication(), App::Application::getDocuments(), App::Application::getUniqueDocumentName(), App::Application::newDocument(), src.Mod.Test.testPathArray::path, and App::Application::setActiveDocument().
Referenced by cloudRestore().
Member Data Documentation
ProtocolVersion
App::PropertyString Cloud::Module::ProtocolVersion
Definition at line 182 of file AppCloud.h.
Region
App::PropertyString Cloud::Module::Region
Definition at line 183 of file AppCloud.h.
TCPPort
App::PropertyString Cloud::Module::TCPPort
Definition at line 179 of file AppCloud.h.
TokenAuth
App::PropertyString Cloud::Module::TokenAuth
Definition at line 180 of file AppCloud.h.
TokenSecret
App::PropertyString Cloud::Module::TokenSecret
Definition at line 181 of file AppCloud.h.
URL
App::PropertyString Cloud::Module::URL
Definition at line 178 of file AppCloud.h.
The documentation for this class was generated from the following files:
AppCloud.h
AppCloud.cpp