FreeCAD: TechDrawGui::QGVPage Class Reference
TechDrawGui::QGVPage Class Reference
#include <QGVPage.h>
Classes
class Private
Public Types
enum RendererType { Native, OpenGL, Image }
Public Slots
void setHighQualityAntialiasing (bool highQualityAntialiasing)
Public Member Functions
QGVPage (ViewProviderPage *vpPage, QGSPage *scenePage, QWidget *parent=nullptr)
~QGVPage () override
void setRenderer (RendererType type=Native)
void drawBackground (QPainter *painter, const QRectF &rect) override
QGSPage * getScene ()
void startBalloonPlacing (TechDraw::DrawView *parent)
void cancelBalloonPlacing ()
TechDraw::DrawPage * getDrawPage ()
void makeGrid (int width, int height, double step)
void showGrid (bool state)
void updateViewport ()
void activateHandler (TechDrawHandler *newHandler)
void deactivateHandler ()
bool isHandlerActive ()
bool isBalloonPlacing () const
void setBalloonPlacing (bool isPlacing)
QLabel * getBalloonCursor () const
void setBalloonCursor (QLabel *label)
void kbPanScroll (int xMove=1, int yMove=1)
QPointF getBalloonCursorPos () const
void setBalloonCursorPos (QPoint pos)
void activateCursor (QCursor cursor)
void resetCursor ()
void setPanCursor ()
void setZoomCursor ()
void pseudoContextEvent ()
void centerOnPage ()
TechDraw::DrawView * getBalloonParent ()
void zoomIn ()
void zoomOut ()
Protected Member Functions
void wheelEvent (QWheelEvent *event) override
void paintEvent (QPaintEvent *event) override
void enterEvent (QEnterEvent *event) override
void leaveEvent (QEvent *event) override
void mousePressEvent (QMouseEvent *event) override
void mouseMoveEvent (QMouseEvent *event) override
void mouseReleaseEvent (QMouseEvent *event) override
void focusOutEvent (QFocusEvent *event) override
void keyPressEvent (QKeyEvent *event) override
void keyReleaseEvent (QKeyEvent *event) override
void contextMenuEvent (QContextMenuEvent *event) override
QColor getBackgroundColor ()
double getDevicePixelRatio () const
QPixmap prepareCursorPixmap (const char *iconName, QPoint &hotspot)
void drawForeground (QPainter *painter, const QRectF &rect) override
std::string getNavStyleParameter ()
Base::Type getStyleType (std::string model)
void initNavigationStyle ()
void setNavigationStyle (std::string navParm)
void createStandardCursors (double dpr)
Detailed Description
Definition at line 76 of file QGVPage.h.
Member Enumeration Documentation
RendererType
enum TechDrawGui::QGVPage::RendererType
Enumerator
Native
OpenGL
Image
Definition at line 81 of file QGVPage.h.
Constructor & Destructor Documentation
QGVPage()
QGVPage::QGVPage (ViewProviderPage * vpPage, QGSPage * scenePage, QWidget * parent = nullptr)
Definition at line 168 of file QGVPage.cpp.
References createStandardCursors(), getBackgroundColor(), TechDrawGui::ViewProviderPage::getDrawPage(), App::DocumentObject::getNameInDocument(), initNavigationStyle(), Native, NoDrag, Init::parent, prepareCursorPixmap(), resetCursor(), and setRenderer().
~QGVPage()
QGVPage::~QGVPage () override
Definition at line 217 of file QGVPage.cpp.
Member Function Documentation
activateCursor()
void QGVPage::activateCursor (QCursor cursor)
Definition at line 602 of file QGVPage.cpp.
Referenced by resetCursor(), setPanCursor(), setZoomCursor(), and startBalloonPlacing().
activateHandler()
void QGVPage::activateHandler (TechDrawHandler * newHandler)
Definition at line 286 of file QGVPage.cpp.
Referenced by activateHandler().
cancelBalloonPlacing()
void QGVPage::cancelBalloonPlacing ()
Definition at line 317 of file QGVPage.cpp.
References resetCursor().
Referenced by TechDrawGui::QGVNavStyle::handleFocusOutEvent(), and TechDrawGui::QGVNavStyle::handleKeyPressEvent().
centerOnPage()
void QGVPage::centerOnPage ()
Definition at line 224 of file QGVPage.cpp.
References TechDrawGui::ViewProviderPage::getQGSPage(), and TechDrawGui::QGSPage::getTemplateCenter().
contextMenuEvent()
void QGVPage::contextMenuEvent (QContextMenuEvent * event) override protected
Definition at line 412 of file QGVPage.cpp.
References TechDrawGui::QGVNavStyle::allowContextMenu().
createStandardCursors()
void QGVPage::createStandardCursors (double dpr) protected
Definition at line 707 of file QGVPage.cpp.
References createCursor(), pan_bitmap, PAN_HEIGHT, PAN_HOT_X, PAN_HOT_Y, pan_mask_bitmap, PAN_WIDTH, zoom_bitmap, ZOOM_HEIGHT, ZOOM_HOT_X, ZOOM_HOT_Y, zoom_mask_bitmap, and ZOOM_WIDTH.
Referenced by QGVPage().
deactivateHandler()
void QGVPage::deactivateHandler ()
Definition at line 296 of file QGVPage.cpp.
Referenced by TechDrawGui::TechDrawHandler::activate(), and TechDrawGui::TechDrawHandler::quit().
drawBackground()
void QGVPage::drawBackground (QPainter * painter, const QRectF & rect) override
Definition at line 325 of file QGVPage.cpp.
References TechDrawGui::ViewProviderPage::getDrawPage(), TechDraw::DrawPage::getPageHeight(), TechDraw::DrawPage::getPageWidth(), TechDrawGui::Rez::guiX(), TechDraw::DrawPage::hasValidTemplate(), and TechDrawGui::PreferencesGui::pageQColor().
drawForeground()
void QGVPage::drawForeground (QPainter * painter, const QRectF & rect) override protected
Definition at line 627 of file QGVPage.cpp.
References TechDrawGui::PreferencesGui::gridQColor().
enterEvent()
void QGVPage::enterEvent (QEnterEvent * event) override protected
Definition at line 495 of file QGVPage.cpp.
focusOutEvent()
void QGVPage::focusOutEvent (QFocusEvent * event) override protected
Definition at line 468 of file QGVPage.cpp.
References TechDrawGui::QGVNavStyle::handleFocusOutEvent().
getBackgroundColor()
QColor QGVPage::getBackgroundColor () protected
Definition at line 554 of file QGVPage.cpp.
References App::Color::asValue(), and App::Color::setPackedValue().
Referenced by QGVPage().
getBalloonCursor()
QLabel* TechDrawGui::QGVPage::getBalloonCursor () const inline
Definition at line 112 of file QGVPage.h.
Referenced by TechDrawGui::QGVNavStyle::handleEnterEvent(), TechDrawGui::QGVNavStyle::handleLeaveEvent(), and TechDrawGui::QGVNavStyle::placeBalloon().
getBalloonCursorPos()
QPointF TechDrawGui::QGVPage::getBalloonCursorPos () const inline
Definition at line 116 of file QGVPage.h.
Referenced by TechDrawGui::QGVNavStyle::handleLeaveEvent().
getBalloonParent()
TechDraw::DrawView* TechDrawGui::QGVPage::getBalloonParent () inline
Definition at line 128 of file QGVPage.h.
getDevicePixelRatio()
double QGVPage::getDevicePixelRatio () const protected
Definition at line 561 of file QGVPage.cpp.
References Base::BaseClass::getClassTypeId(), Gui::ViewProviderDocumentObject::getDocument(), and Gui::Document::getMDIViews().
Referenced by prepareCursorPixmap().
getDrawPage()
TechDraw::DrawPage * QGVPage::getDrawPage ()
Definition at line 552 of file QGVPage.cpp.
References TechDrawGui::ViewProviderPage::getDrawPage().
Referenced by TechDrawGui::TechDrawHandler::getPage().
getNavStyleParameter()
std::string QGVPage::getNavStyleParameter () protected
Definition at line 671 of file QGVPage.cpp.
References App::GetApplication(), ParameterGrp::GetASCII(), and App::Application::GetParameterGroupByPath().
Referenced by initNavigationStyle().
getScene()
QGSPage* TechDrawGui::QGVPage::getScene () inline
Definition at line 94 of file QGVPage.h.
Referenced by TechDrawGui::QGVNavStyle::placeBalloon().
getStyleType()
Base::Type QGVPage::getStyleType (std::string model) protected
Definition at line 680 of file QGVPage.cpp.
References Base::Type::fromName(), and Path.Post.scripts.grbl_post::type.
initNavigationStyle()
void QGVPage::initNavigationStyle () protected
Definition at line 226 of file QGVPage.cpp.
References getNavStyleParameter(), and setNavigationStyle().
Referenced by QGVPage().
isBalloonPlacing()
bool TechDrawGui::QGVPage::isBalloonPlacing () const inline
Definition at line 109 of file QGVPage.h.
isHandlerActive()
bool TechDrawGui::QGVPage::isHandlerActive () inline
Definition at line 107 of file QGVPage.h.
kbPanScroll()
void QGVPage::kbPanScroll (int xMove = 1, int yMove = 1)
Definition at line 474 of file QGVPage.cpp.
Referenced by TechDrawGui::QGVNavStyle::handleKeyPressEvent().
keyPressEvent()
void QGVPage::keyPressEvent (QKeyEvent * event) override protected
Definition at line 442 of file QGVPage.cpp.
References TechDrawGui::QGVNavStyle::handleKeyPressEvent().
keyReleaseEvent()
void QGVPage::keyReleaseEvent (QKeyEvent * event) override protected
Definition at line 455 of file QGVPage.cpp.
References TechDrawGui::QGVNavStyle::handleKeyReleaseEvent().
leaveEvent()
void QGVPage::leaveEvent (QEvent * event) override protected
Definition at line 508 of file QGVPage.cpp.
References TechDrawGui::QGVNavStyle::handleLeaveEvent().
makeGrid()
void QGVPage::makeGrid (int width, int height, double step)
Definition at line 639 of file QGVPage.cpp.
References Plot::grid(), TechDrawGui::Rez::guiX(), and SplineSurface::i.
Referenced by TechDrawGui::ViewProviderPage::setGrid().
mouseMoveEvent()
void QGVPage::mouseMoveEvent (QMouseEvent * event) override protected
Definition at line 525 of file QGVPage.cpp.
References TechDrawGui::QGVNavStyle::handleMouseMoveEvent().
mousePressEvent()
void QGVPage::mousePressEvent (QMouseEvent * event) override protected
Definition at line 514 of file QGVPage.cpp.
References TechDrawGui::QGVNavStyle::handleMousePressEvent().
mouseReleaseEvent()
void QGVPage::mouseReleaseEvent (QMouseEvent * event) override protected
Definition at line 534 of file QGVPage.cpp.
References TechDrawGui::QGVNavStyle::handleMouseReleaseEvent(), and resetCursor().
paintEvent()
void QGVPage::paintEvent (QPaintEvent * event) override protected
Definition at line 393 of file QGVPage.cpp.
References buildPsets::p, and OfflineRenderingUtils::render().
prepareCursorPixmap()
QPixmap QGVPage::prepareCursorPixmap (const char * iconName, QPoint & hotspot) protected
Definition at line 572 of file QGVPage.cpp.
References Gui::BitmapFactory(), getDevicePixelRatio(), and Gui::BitmapFactoryInst::pixmapFromSvg().
Referenced by QGVPage().
pseudoContextEvent()
void QGVPage::pseudoContextEvent ()
Definition at line 429 of file QGVPage.cpp.
References TechDrawGui::MDIViewPage::contextMenuEvent().
Referenced by TechDrawGui::QGVNavStyle::pseudoContextEvent().
resetCursor()
void QGVPage::resetCursor ()
Definition at line 608 of file QGVPage.cpp.
References activateCursor().
Referenced by cancelBalloonPlacing(), mouseReleaseEvent(), QGVPage(), TechDrawGui::QGVNavStyle::stopPan(), and TechDrawGui::QGVNavStyle::stopZoom().
setBalloonCursor()
void TechDrawGui::QGVPage::setBalloonCursor (QLabel * label) inline
Definition at line 113 of file QGVPage.h.
References NavigationIndicatorGui::label.
setBalloonCursorPos()
void TechDrawGui::QGVPage::setBalloonCursorPos (QPoint pos) inline
Definition at line 117 of file QGVPage.h.
References RobotExample::pos.
Referenced by TechDrawGui::QGVNavStyle::balloonCursorMovement().
setBalloonPlacing()
void TechDrawGui::QGVPage::setBalloonPlacing (bool isPlacing) inline
Definition at line 110 of file QGVPage.h.
Referenced by TechDrawGui::QGVNavStyle::placeBalloon().
setHighQualityAntialiasing
void QGVPage::setHighQualityAntialiasing (bool highQualityAntialiasing) slot
Definition at line 384 of file QGVPage.cpp.
setNavigationStyle()
void QGVPage::setNavigationStyle (std::string navParm) protected
Definition at line 232 of file QGVPage.cpp.
Referenced by initNavigationStyle(), and TechDrawGui::QGVPage::Private::OnChange().
setPanCursor()
void QGVPage::setPanCursor ()
Definition at line 613 of file QGVPage.cpp.
References activateCursor().
Referenced by TechDrawGui::QGVNavStyle::startPan().
setRenderer()
void QGVPage::setRenderer (RendererType type = Native)
Definition at line 368 of file QGVPage.cpp.
References OpenGL, and Path.Post.scripts.grbl_post::type.
Referenced by QGVPage().
setZoomCursor()
void QGVPage::setZoomCursor ()
Definition at line 615 of file QGVPage.cpp.
References activateCursor().
Referenced by TechDrawGui::QGVNavStyle::startZoom().
showGrid()
void TechDrawGui::QGVPage::showGrid (bool state) inline
Definition at line 102 of file QGVPage.h.
Referenced by TechDrawGui::ViewProviderPage::setGrid().
startBalloonPlacing()
void QGVPage::startBalloonPlacing (TechDraw::DrawView * parent)
Definition at line 304 of file QGVPage.cpp.
References activateCursor(), and Init::parent.
updateViewport()
void TechDrawGui::QGVPage::updateViewport () inline
Definition at line 103 of file QGVPage.h.
Referenced by TechDrawGui::ViewProviderPage::setGrid().
wheelEvent()
void QGVPage::wheelEvent (QWheelEvent * event) override protected
Definition at line 436 of file QGVPage.cpp.
References TechDrawGui::QGVNavStyle::handleWheelEvent().
zoomIn()
void QGVPage::zoomIn ()
Definition at line 617 of file QGVPage.cpp.
References TechDrawGui::QGVNavStyle::zoomIn().
zoomOut()
void QGVPage::zoomOut ()
Definition at line 622 of file QGVPage.cpp.
References TechDrawGui::QGVNavStyle::zoomOut().
The documentation for this class was generated from the following files:
QGVPage.h
QGVPage.cpp