FreeCAD: PythonStuff.cpp File Reference
PythonStuff.cpp File Reference
#include "PythonStuff.h"
#include "Area.h"
#include "Point.h"
#include "AreaDxf.h"
#include "kurve/geometry.h"
#include "Adaptive.hpp"
#include <Python.h>
#include <boost/foreach.hpp>
#include <boost_python.hpp>
#include <boost/python/module.hpp>
#include <boost/python/class.hpp>
#include <boost/python/wrapper.hpp>
#include <boost/python/call.hpp>
#include "clipper.hpp"
Classes
struct std_pair_to_tuple< T1, T2 >
Macros
#define BOOST_BIND_GLOBAL_PLACEHOLDERS
Functions
boost::python::list getVertices (const CCurve &curve)
boost::python::list getCurves (const CArea &area)
boost::python::tuple transformed_point (const geoff_geometry::Matrix &matrix, double x, double y, double z)
static void print_curve (const CCurve &c)
static void print_area (const CArea &a)
static unsigned int num_vertices (const CCurve &curve)
static CVertex FirstVertex (const CCurve &curve)
static CVertex LastVertex (const CCurve &curve)
static void set_units (double units)
static double get_units ()
static bool holes_linked ()
static CArea AreaFromDxf (const char *filepath)
static void append_point (CCurve &c, const Point &p)
static boost::python::tuple nearest_point_to_curve (CCurve &c1, const CCurve &c2)
boost::python::list MakePocketToolpath (const CArea &a, double tool_radius, double extra_offset, double stepover, bool from_center, bool use_zig_zag, double zig_angle)
boost::python::list SplitArea (const CArea &a)
void dxfArea (CArea &area, const char *)
boost::python::list getCurveSpans (const CCurve &c)
Span getFirstCurveSpan (const CCurve &c)
Span getLastCurveSpan (const CCurve &c)
bp::tuple TangentialArc (const Point &p0, const Point &p1, const Point &v0)
boost::python::list spanIntersect (const Span &span1, const Span &span2)
std::shared_ptr< geoff_geometry::Matrix > matrix_constructor (const boost::python::list &lst)
boost::python::list InsideCurves (const CArea &a, const CCurve &curve)
boost::python::list CurveIntersections (const CCurve &c1, const CCurve &c2)
boost::python::list AreaIntersections (const CArea &a, const CCurve &c2)
double AreaGetArea (const CArea &a)
bp::list AdaptiveExecute (AdaptivePath::Adaptive2d &ada, const boost::python::list &stock_paths, const boost::python::list &in_paths, boost::python::object progressCallbackFn)
boost::python::list AdaptiveOutput_AdaptivePaths (const AdaptivePath::AdaptiveOutput &ado)
BOOST_PYTHON_MODULE (area)
Macro Definition Documentation
BOOST_BIND_GLOBAL_PLACEHOLDERS
#define BOOST_BIND_GLOBAL_PLACEHOLDERS
Definition at line 33 of file PythonStuff.cpp.
Function Documentation
AdaptiveExecute()
bp::list AdaptiveExecute (AdaptivePath::Adaptive2d & ada, const boost::python::list & stock_paths, const boost::python::list & in_paths, boost::python::object progressCallbackFn)
Definition at line 332 of file PythonStuff.cpp.
References SplineSurface::i, src.Mod.Test.testPathArray::path, and result.
Referenced by BOOST_PYTHON_MODULE().
AdaptiveOutput_AdaptivePaths()
boost::python::list AdaptiveOutput_AdaptivePaths (const AdaptivePath::AdaptiveOutput & ado)
Definition at line 398 of file PythonStuff.cpp.
Referenced by BOOST_PYTHON_MODULE().
append_point()
static void append_point (CCurve & c, const Point & p) static
Definition at line 152 of file PythonStuff.cpp.
References SCL.SimpleDataTypes::c, and buildPsets::p.
Referenced by BOOST_PYTHON_MODULE().
AreaFromDxf()
static CArea AreaFromDxf (const char * filepath) static
Definition at line 144 of file PythonStuff.cpp.
References ifctree::filepath.
Referenced by BOOST_PYTHON_MODULE().
AreaGetArea()
double AreaGetArea (const CArea & a)
Definition at line 325 of file PythonStuff.cpp.
References a.
Referenced by BOOST_PYTHON_MODULE().
AreaIntersections()
boost::python::list AreaIntersections (const CArea & a, const CCurve & c2)
Definition at line 313 of file PythonStuff.cpp.
References a, and buildPsets::p.
Referenced by BOOST_PYTHON_MODULE().
BOOST_PYTHON_MODULE()
BOOST_PYTHON_MODULE (area)
Definition at line 412 of file PythonStuff.cpp.
References AdaptiveExecute(), AdaptiveOutput_AdaptivePaths(), CArea::append(), CCurve::append(), append_point(), AreaFromDxf(), AreaGetArea(), AreaIntersections(), CCurve::Break(), CCurve::ChangeEnd(), CCurve::ChangeStart(), CurveIntersections(), Point::dist(), FirstVertex(), CArea::FitArcs(), CCurve::FitArcs(), get_units(), Span::GetArea(), CCurve::GetArea(), CArea::GetBox(), Span::GetBox(), getCurves(), getCurveSpans(), getFirstCurveSpan(), getLastCurveSpan(), Span::GetVector(), getVertices(), holes_linked(), Span::IncludedAngle(), InsideCurves(), CArea::Intersect(), CCurve::IsClockwise(), CCurve::IsClosed(), LastVertex(), Point::length(), Span::Length(), CVertex::m_c, CVertex::m_p, Span::m_p, CVertex::m_type, CVertex::m_user_data, Span::m_v, MakePocketToolpath(), matrix_constructor(), CBox2D::MaxX(), CBox2D::MaxY(), Span::MidParam(), Span::MidPerim(), CBox2D::MinX(), CBox2D::MinY(), geoff_geometry::Matrix::Multiply(), nearest_point_to_curve(), CArea::NearestPoint(), Span::NearestPoint(), CCurve::NearestPoint(), Point::normalize(), CArea::num_curves(), num_vertices(), CArea::Offset(), CCurve::Offset(), CCurve::OffsetForward(), Span::On(), buildPsets::p, CCurve::Perim(), CCurve::PerimToPoint(), CCurve::PointToPerim(), print_area(), print_curve(), CArea::Reorder(), CCurve::Reverse(), Point::Rotate(), set_units(), spanIntersect(), SplitArea(), SketcherExample::StartPoint, CArea::Subtract(), TangentialArc(), CArea::Thicken(), draftutils.utils::tolerance(), Point::Transform(), transformed_point(), CCurve::UnFitArcs(), CArea::Union(), Point::x, and Point::y.
CurveIntersections()
boost::python::list CurveIntersections (const CCurve & c1, const CCurve & c2)
Definition at line 301 of file PythonStuff.cpp.
References src.Mod.PartDesign.Scripts.Gear::c1, and buildPsets::p.
Referenced by BOOST_PYTHON_MODULE().
dxfArea()
void dxfArea (CArea & area, const char *)
Definition at line 202 of file PythonStuff.cpp.
FirstVertex()
static CVertex FirstVertex (const CCurve & curve) static
Definition at line 119 of file PythonStuff.cpp.
References CCurve::m_vertices.
Referenced by BOOST_PYTHON_MODULE().
get_units()
static double get_units () static
Definition at line 134 of file PythonStuff.cpp.
References CArea::get_units().
Referenced by BOOST_PYTHON_MODULE().
getCurves()
boost::python::list getCurves (const CArea & area)
Definition at line 60 of file PythonStuff.cpp.
References CArea::m_curves.
Referenced by BOOST_PYTHON_MODULE().
getCurveSpans()
boost::python::list getCurveSpans (const CCurve & c)
Definition at line 207 of file PythonStuff.cpp.
References SCL.SimpleDataTypes::c, and CVertex::m_p.
Referenced by BOOST_PYTHON_MODULE().
getFirstCurveSpan()
Span getFirstCurveSpan (const CCurve & c)
Definition at line 225 of file PythonStuff.cpp.
References SCL.SimpleDataTypes::c, and buildPsets::p.
Referenced by BOOST_PYTHON_MODULE().
getLastCurveSpan()
Span getLastCurveSpan (const CCurve & c)
Definition at line 237 of file PythonStuff.cpp.
References SCL.SimpleDataTypes::c, and TestSpreadsheet::v.
Referenced by BOOST_PYTHON_MODULE().
getVertices()
boost::python::list getVertices (const CCurve & curve)
Definition at line 51 of file PythonStuff.cpp.
References CCurve::m_vertices.
Referenced by BOOST_PYTHON_MODULE().
holes_linked()
static bool holes_linked () static
Definition at line 139 of file PythonStuff.cpp.
References CArea::HolesLinked().
Referenced by BOOST_PYTHON_MODULE().
InsideCurves()
boost::python::list InsideCurves (const CArea & a, const CCurve & curve)
Definition at line 289 of file PythonStuff.cpp.
References a, and SCL.SimpleDataTypes::c.
Referenced by BOOST_PYTHON_MODULE().
LastVertex()
static CVertex LastVertex (const CCurve & curve) static
Definition at line 124 of file PythonStuff.cpp.
References CCurve::m_vertices.
Referenced by BOOST_PYTHON_MODULE().
MakePocketToolpath()
boost::python::list MakePocketToolpath (const CArea & a, double tool_radius, double extra_offset, double stepover, bool from_center, bool use_zig_zag, double zig_angle)
Definition at line 165 of file PythonStuff.cpp.
References a, SCL.SimpleDataTypes::c, nativeifc.ifc_observer::params, SpiralPocketMode, and ZigZagPocketMode.
Referenced by BOOST_PYTHON_MODULE().
matrix_constructor()
std::shared_ptr<geoff_geometry::Matrix> matrix_constructor (const boost::python::list & lst)
Definition at line 271 of file PythonStuff.cpp.
References SplineSurface::i, and test::m.
Referenced by BOOST_PYTHON_MODULE().
nearest_point_to_curve()
static boost::python::tuple nearest_point_to_curve (CCurve & c1, const CCurve & c2) static
Definition at line 157 of file PythonStuff.cpp.
References src.Mod.PartDesign.Scripts.Gear::c1, DraftVecUtils::dist(), and buildPsets::p.
Referenced by BOOST_PYTHON_MODULE().
num_vertices()
static unsigned int num_vertices (const CCurve & curve) static
Definition at line 114 of file PythonStuff.cpp.
References CCurve::m_vertices.
Referenced by BOOST_PYTHON_MODULE().
print_area()
static void print_area (const CArea & a) static
Definition at line 106 of file PythonStuff.cpp.
References a, and print_curve().
Referenced by BOOST_PYTHON_MODULE().
print_curve()
static void print_curve (const CCurve & c) static
Definition at line 78 of file PythonStuff.cpp.
References SCL.SimpleDataTypes::c, CArea::get_units(), SplineSurface::i, CVertex::m_c, CVertex::m_p, CVertex::m_type, Point::x, and Point::y.
Referenced by BOOST_PYTHON_MODULE(), and print_area().
set_units()
static void set_units (double units) static
Definition at line 129 of file PythonStuff.cpp.
References CArea::set_units().
Referenced by BOOST_PYTHON_MODULE().
spanIntersect()
boost::python::list spanIntersect (const Span & span1, const Span & span2)
Definition at line 259 of file PythonStuff.cpp.
References Span::Intersect(), and buildPsets::p.
Referenced by BOOST_PYTHON_MODULE().
SplitArea()
boost::python::list SplitArea (const CArea & a)
Definition at line 190 of file PythonStuff.cpp.
References a.
Referenced by BOOST_PYTHON_MODULE().
TangentialArc()
bp::tuple TangentialArc (const Point & p0, const Point & p1, const Point & v0)
Definition at line 250 of file PythonStuff.cpp.
References SCL.SimpleDataTypes::c, and tangential_arc().
Referenced by BOOST_PYTHON_MODULE().
transformed_point()
boost::python::tuple transformed_point (const geoff_geometry::Matrix & matrix, double x, double y, double z)
Definition at line 70 of file PythonStuff.cpp.
References buildPsets::p, MovieTool::x, and MovieTool::y.
Referenced by BOOST_PYTHON_MODULE().