FreeCAD: Gui::VectorTableModel Class Reference
Gui::VectorTableModel Class Reference
#include <VectorListEditor.h>
Public Member Functions
VectorTableModel (int decimals, QObject *parent=nullptr)
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
int columnCount (const QModelIndex &parent=QModelIndex()) const override
int rowCount (const QModelIndex &parent=QModelIndex()) const override
Qt::ItemFlags flags (const QModelIndex &index) const override
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
QModelIndex parent (const QModelIndex &index) const override
void setValues (const QList< Base::Vector3d > &d)
void copyToClipboard () const
void pasteFromClipboard ()
const QList< Base::Vector3d > & values () const
bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex()) override
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex()) override
Detailed Description
Definition at line 58 of file VectorListEditor.h.
Constructor & Destructor Documentation
VectorTableModel()
VectorTableModel::VectorTableModel (int decimals, QObject * parent = nullptr) explicit
Definition at line 38 of file VectorListEditor.cpp.
Member Function Documentation
columnCount()
int VectorTableModel::columnCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 61 of file VectorListEditor.cpp.
copyToClipboard()
void Gui::VectorTableModel::copyToClipboard () const
Definition at line 141 of file VectorListEditor.cpp.
data()
QVariant VectorTableModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 103 of file VectorListEditor.cpp.
References SCL.SimpleDataTypes::c, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by Gui::VectorListEditor::setValues().
flags()
Qt::ItemFlags VectorTableModel::flags (const QModelIndex & index) const override
Definition at line 71 of file VectorListEditor.cpp.
headerData()
QVariant VectorTableModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const override
Definition at line 44 of file VectorListEditor.cpp.
References Sketcher::Horizontal, and Sketcher::Vertical.
insertRows()
bool VectorTableModel::insertRows (int row, int count, const QModelIndex & parent = QModelIndex()) override
Definition at line 214 of file VectorListEditor.cpp.
References src.Mod.AddonManager.NetworkManager::count, SplineSurface::i, parent(), and TestSpreadsheet::v.
parent()
QModelIndex VectorTableModel::parent (const QModelIndex & index) const override
Definition at line 129 of file VectorListEditor.cpp.
Referenced by insertRows(), and removeRows().
pasteFromClipboard()
void Gui::VectorTableModel::pasteFromClipboard ()
Definition at line 155 of file VectorListEditor.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), Path.Op.Surface::msg, MovieTool::x, and MovieTool::y.
removeRows()
bool VectorTableModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex()) override
Definition at line 228 of file VectorListEditor.cpp.
References src.Mod.AddonManager.NetworkManager::count, SplineSurface::i, and parent().
rowCount()
int VectorTableModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 66 of file VectorListEditor.cpp.
Referenced by src.Mod.AddonManager.package_list.PackageListItemModel::append_item(), src.Mod.AddonManager.AddonManagerOptions.CustomRepoDataModel::appendData(), and src.Mod.AddonManager.package_list.PackageListItemModel::clear().
setData()
bool VectorTableModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) override
Definition at line 78 of file VectorListEditor.cpp.
References SCL.SimpleDataTypes::c.
setValues()
void VectorTableModel::setValues (const QList< Base::Vector3d > & d)
Definition at line 134 of file VectorListEditor.cpp.
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle(), and Gui::VectorListEditor::setValues().
values()
const QList< Base::Vector3d > & VectorTableModel::values () const
Definition at line 209 of file VectorListEditor.cpp.
Referenced by Gui::VectorListEditor::accept().
The documentation for this class was generated from the following files:
VectorListEditor.h
VectorListEditor.cpp