FreeCAD: Wm4::Delaunay3< Real > Class Template Reference
Wm4::Delaunay3< Real > Class Template Reference
#include <Wm4Delaunay3.h>
Public Member Functions
Delaunay3 (int iVertexQuantity, Vector3< Real > *akVertex, Real fEpsilon, bool bOwner, Query::Type eQueryType)
virtual ~Delaunay3 ()
const Vector3< Real > * GetVertices () const
int GetUniqueVertexQuantity () const
const Vector3< Real > & GetLineOrigin () const
const Vector3< Real > & GetLineDirection () const
Delaunay1< Real > * GetDelaunay1 () const
const Vector3< Real > & GetPlaneOrigin () const
const Vector3< Real > & GetPlaneDirection (int i) const
Delaunay2< Real > * GetDelaunay2 () const
bool GetHull (int &riTQuantity, int *&raiIndex) const
int GetContainingTetrahedron (const Vector3< Real > &rkP) const
int GetPathLast () const
const int * GetPath () const
int GetLastFace (int &riV0, int &riV1, int &riV2, int &riV3) const
bool GetVertexSet (int i, Vector3< Real > akV[4]) const
bool GetIndexSet (int i, int aiIndex[4]) const
bool GetAdjacentSet (int i, int aiAdjacent[4]) const
bool GetBarycentricSet (int i, const Vector3< Real > &rkP, Real afBary[4]) const
Delaunay3 (const char *acFilename)
bool Load (const char *acFilename)
bool Save (const char *acFilename) const
Public Member Functions inherited from Wm4::Delaunay< Real >
virtual ~Delaunay ()
int GetQueryType () const
int GetVertexQuantity () const
Real GetEpsilon () const
bool GetOwner () const
int GetDimension () const
int GetSimplexQuantity () const
const int * GetIndices () const
const int * GetAdjacencies () const
Additional Inherited Members
Protected Member Functions inherited from Wm4::Delaunay< Real >
Delaunay (int iVertexQuantity, Real fEpsilon, bool bOwner, Query::Type eQueryType)
bool Load (FILE *pkIFile)
bool Save (FILE *pkOFile) const
Protected Attributes inherited from Wm4::Delaunay< Real >
Query::Type m_eQueryType
int m_iVertexQuantity
int m_iDimension
int m_iSimplexQuantity
int * m_aiIndex
int * m_aiAdjacent
Real m_fEpsilon
bool m_bOwner
Detailed Description
template<class Real>
class Wm4::Delaunay3< Real >
Definition at line 30 of file Wm4Delaunay3.h.
Constructor & Destructor Documentation
Delaunay3() [1/2]
template<class Real > Wm4::Delaunay3< Real >::Delaunay3 (int iVertexQuantity, Vector3< Real > * akVertex, Real fEpsilon, bool bOwner, Query::Type eQueryType)
Definition at line 39 of file Wm4Delaunay3.cpp.
References Wm4::DelTetrahedron< Real >::A, Wm4::Mapper3< Real >::GetDimension(), Wm4::Mapper3< Real >::GetDirection(), Wm4::Mapper3< Real >::GetMax(), Wm4::Mapper3< Real >::GetMaxRange(), Wm4::Mapper3< Real >::GetMin(), Wm4::Mapper3< Real >::GetOrigin(), SplineSurface::i, Wm4::Delaunay< Real >::m_aiAdjacent, Wm4::Delaunay< Real >::m_aiIndex, Wm4::Delaunay< Real >::m_fEpsilon, Wm4::Delaunay< Real >::m_iDimension, Wm4::Delaunay< Real >::m_iSimplexQuantity, Wm4::Delaunay< Real >::m_iVertexQuantity, Wm4::System::Memcpy(), Wm4::Query::QT_FILTERED, Wm4::Query::QT_INT64, Wm4::Query::QT_INTEGER, Wm4::Query::QT_RATIONAL, Wm4::DelTetrahedron< Real >::V, WM4_DELETE, and WM4_NEW.
~Delaunay3()
template<class Real > Wm4::Delaunay3< Real >::~Delaunay3 virtual
Definition at line 258 of file Wm4Delaunay3.cpp.
References WM4_DELETE.
Delaunay3() [2/2]
template<class Real > Wm4::Delaunay3< Real >::Delaunay3 (const char * acFilename)
Definition at line 948 of file Wm4Delaunay3.cpp.
References Wm4::Delaunay3< Real >::Load().
Member Function Documentation
GetAdjacentSet()
template<class Real > bool Wm4::Delaunay3< Real >::GetAdjacentSet (int i, int aiAdjacent[4]) const
Definition at line 570 of file Wm4Delaunay3.cpp.
References SplineSurface::i.
GetBarycentricSet()
template<class Real > bool Wm4::Delaunay3< Real >::GetBarycentricSet (int i, const Vector3< Real > & rkP, Real afBary[4]) const
Definition at line 591 of file Wm4Delaunay3.cpp.
References Wm4::Vector3< Real >::GetBarycentrics(), and SplineSurface::i.
GetContainingTetrahedron()
template<class Real > int Wm4::Delaunay3< Real >::GetContainingTetrahedron (const Vector3< Real > & rkP) const
Definition at line 402 of file Wm4Delaunay3.cpp.
References SplineSurface::i.
GetDelaunay1()
template<class Real > Delaunay1< Real > * Wm4::Delaunay3< Real >::GetDelaunay1
Definition at line 294 of file Wm4Delaunay3.cpp.
References Wm4::Vector3< Real >::Dot(), SplineSurface::i, and WM4_NEW.
GetDelaunay2()
template<class Real > Delaunay2< Real > * Wm4::Delaunay3< Real >::GetDelaunay2
Definition at line 327 of file Wm4Delaunay3.cpp.
References Wm4::Vector2< Real >::Dot(), SplineSurface::i, and WM4_NEW.
GetHull()
template<class Real > bool Wm4::Delaunay3< Real >::GetHull (int & riTQuantity, int *& raiIndex) const
Definition at line 348 of file Wm4Delaunay3.cpp.
References SplineSurface::i, and WM4_NEW.
GetIndexSet()
template<class Real > bool Wm4::Delaunay3< Real >::GetIndexSet (int i, int aiIndex[4]) const
Definition at line 549 of file Wm4Delaunay3.cpp.
References SplineSurface::i.
GetLastFace()
template<class Real > int Wm4::Delaunay3< Real >::GetLastFace (int & riV0, int & riV1, int & riV2, int & riV3) const
Definition at line 517 of file Wm4Delaunay3.cpp.
GetLineDirection()
template<class Real > const Vector3< Real > & Wm4::Delaunay3< Real >::GetLineDirection
Definition at line 288 of file Wm4Delaunay3.cpp.
GetLineOrigin()
template<class Real > const Vector3< Real > & Wm4::Delaunay3< Real >::GetLineOrigin
Definition at line 282 of file Wm4Delaunay3.cpp.
GetPath()
template<class Real > const int * Wm4::Delaunay3< Real >::GetPath
Definition at line 511 of file Wm4Delaunay3.cpp.
GetPathLast()
template<class Real > int Wm4::Delaunay3< Real >::GetPathLast
Definition at line 505 of file Wm4Delaunay3.cpp.
GetPlaneDirection()
template<class Real > const Vector3< Real > & Wm4::Delaunay3< Real >::GetPlaneDirection (int i) const
Definition at line 320 of file Wm4Delaunay3.cpp.
References SplineSurface::i.
GetPlaneOrigin()
template<class Real > const Vector3< Real > & Wm4::Delaunay3< Real >::GetPlaneOrigin
Definition at line 314 of file Wm4Delaunay3.cpp.
GetUniqueVertexQuantity()
template<class Real > int Wm4::Delaunay3< Real >::GetUniqueVertexQuantity
Definition at line 276 of file Wm4Delaunay3.cpp.
GetVertexSet()
template<class Real > bool Wm4::Delaunay3< Real >::GetVertexSet (int i, Vector3< Real > akV[4]) const
Definition at line 528 of file Wm4Delaunay3.cpp.
References SplineSurface::i.
GetVertices()
template<class Real > const Vector3< Real > * Wm4::Delaunay3< Real >::GetVertices
Definition at line 270 of file Wm4Delaunay3.cpp.
Load()
template<class Real > bool Wm4::Delaunay3< Real >::Load (const char * acFilename)
Definition at line 962 of file Wm4Delaunay3.cpp.
References Wm4::System::Fclose(), Wm4::System::Fopen(), Wm4::Delaunay< Real >::Load(), Wm4::Query::QT_FILTERED, Wm4::Query::QT_INT64, Wm4::Query::QT_INTEGER, Wm4::Query::QT_RATIONAL, Wm4::Query::QT_REAL, Wm4::System::Read4le(), Wm4::System::Read8le(), WM4_DELETE, and WM4_NEW.
Referenced by Wm4::Delaunay3< Real >::Delaunay3().
Save()
template<class Real > bool Wm4::Delaunay3< Real >::Save (const char * acFilename) const
Definition at line 1050 of file Wm4Delaunay3.cpp.
References Wm4::System::Fclose(), Wm4::System::Fopen(), Wm4::Delaunay< Real >::Save(), Wm4::System::Write4le(), and Wm4::System::Write8le().
The documentation for this class was generated from the following files:
Wm4Delaunay3.h
Wm4Delaunay3.cpp