FreeCAD: TechDrawGui::DlgPrefsTechDrawGeneralImp Class Reference
TechDrawGui::DlgPrefsTechDrawGeneralImp Class Reference
#include <DlgPrefsTechDrawGeneralImp.h>
Public Member Functions
DlgPrefsTechDrawGeneralImp (QWidget *parent=nullptr)
~DlgPrefsTechDrawGeneralImp () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void saveSettings () override
void loadSettings () override
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
Definition at line 57 of file DlgPrefsTechDrawGeneralImp.h.
Constructor & Destructor Documentation
DlgPrefsTechDrawGeneralImp()
DlgPrefsTechDrawGeneralImp::DlgPrefsTechDrawGeneralImp (QWidget * parent = nullptr) explicit
Definition at line 36 of file DlgPrefsTechDrawGeneralImp.cpp.
References Base::Unit::Length.
~DlgPrefsTechDrawGeneralImp()
DlgPrefsTechDrawGeneralImp::~DlgPrefsTechDrawGeneralImp () override
Definition at line 48 of file DlgPrefsTechDrawGeneralImp.cpp.
Member Function Documentation
changeEvent()
void DlgPrefsTechDrawGeneralImp::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 137 of file DlgPrefsTechDrawGeneralImp.cpp.
References SCL.SimpleDataTypes::e.
loadSettings()
void DlgPrefsTechDrawGeneralImp::loadSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 86 of file DlgPrefsTechDrawGeneralImp.cpp.
References TechDrawGui::PreferencesGui::gridSpacing(), TechDrawGui::PreferencesGui::multiSelection(), and TechDrawGui::PreferencesGui::showGrid().
saveSettings()
void DlgPrefsTechDrawGeneralImp::saveSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 53 of file DlgPrefsTechDrawGeneralImp.cpp.
The documentation for this class was generated from the following files:
DlgPrefsTechDrawGeneralImp.h
DlgPrefsTechDrawGeneralImp.cpp