FreeCAD: importers.importSHP Namespace Reference
importers.importSHP Namespace Reference
Functions
def open (filename)
def insert (filename, docname, record=None)
def getFields (filename)
def checkShapeFileLibrary ()
Variables
translate = FreeCAD.Qt.translate
Function Documentation
checkShapeFileLibrary()
def importers.importSHP.checkShapeFileLibrary ()
Looks for and/or installs the ShapeFile library
Definition at line 120 of file importSHP.py.
Referenced by importers.importSHP.getFields(), and importers.importSHP.insert().
getFields()
def importers.importSHP.getFields (filename)
returns the fields found in the given file
Definition at line 110 of file importSHP.py.
References importers.importSHP.checkShapeFileLibrary().
Referenced by Path.Dressup.Gui.Boundary.TaskPanel.updateDressup().
insert()
def importers.importSHP.insert (filename, docname, record = None)
imports a SHP/SHX/DBF file in an existing FreeCAD document.
the record attribute is an optional string indicating the shapefile
field to use to give elevations to the different shapes. If not used,
if running in GUI mode, a dialog will pop up to ask the user which
field to use.
Definition at line 40 of file importSHP.py.
References importers.importSHP.checkShapeFileLibrary().
Referenced by importers.importSHP.open().
open()
def importers.importSHP.open (filename)
opens a SHP/SHX/DBF file in a new FreeCAD document
Definition at line 29 of file importSHP.py.
References importers.importSHP.insert().
Variable Documentation
translate
importers.importSHP.translate = FreeCAD.Qt.translate
Definition at line 27 of file importSHP.py.