FreeCAD: MatGui::ListEdit Class Reference
MatGui::ListEdit Class Reference
#include <ListEdit.h>
Public Member Functions
ListEdit (const QString &propertyName, const std::shared_ptr< Materials::Material > &material, QWidget *parent=nullptr)
~ListEdit () override=default
void onDataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight, const QVector< int > &roles=QVector< int >())
void defaultValueChanged (const Base::Quantity &value)
void onDelete (bool checked)
void onContextMenu (const QPoint &pos)
void accept () override
void reject () override
Detailed Description
Definition at line 63 of file ListEdit.h.
Constructor & Destructor Documentation
ListEdit()
ListEdit::ListEdit (const QString & propertyName, const std::shared_ptr< Materials::Material > & material, QWidget * parent = nullptr)
Definition at line 44 of file ListEdit.cpp.
References accept(), draftgeoutils.intersections::connect(), Base::Console(), Base::ConsoleSingleton::Log(), propertyName(), and reject().
~ListEdit()
MatGui::ListEdit::~ListEdit () override default
Member Function Documentation
accept()
void ListEdit::accept () override
Definition at line 171 of file ListEdit.cpp.
Referenced by ListEdit(), and MaterialEditor.MaterialEditor::verify().
defaultValueChanged()
void MatGui::ListEdit::defaultValueChanged (const Base::Quantity & value)
onContextMenu()
void MatGui::ListEdit::onContextMenu (const QPoint & pos)
onDataChanged()
void ListEdit::onDataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight, const QVector< int > & roles = QVector<int>())
Definition at line 105 of file ListEdit.cpp.
onDelete()
void ListEdit::onDelete (bool checked)
Definition at line 123 of file ListEdit.cpp.
reject()
void ListEdit::reject () override
Definition at line 177 of file ListEdit.cpp.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and ListEdit().
The documentation for this class was generated from the following files:
ListEdit.h
ListEdit.cpp