FreeCAD: MeshPart::BrepMesh Class Reference
MeshPart::BrepMesh Class Reference
Public Member Functions
BrepMesh (bool s, const std::vector< uint32_t > &c)
Mesh::MeshObject * create (const std::vector< Part::TopoShape::Domain > &domains) const
Detailed Description
Definition at line 127 of file Mesher.cpp.
Constructor & Destructor Documentation
BrepMesh()
MeshPart::BrepMesh::BrepMesh (bool s, const std::vector< uint32_t > & c) inline
Definition at line 133 of file Mesher.cpp.
References segments.
Member Function Documentation
create()
Mesh::MeshObject* MeshPart::BrepMesh::create (const std::vector< Part::TopoShape::Domain > & domains) const inline
Definition at line 138 of file Mesher.cpp.
References Mesh::Segment::addIndices(), Mesh::MeshObject::addSegment(), MeshCore::MeshKernel::Adopt(), App::Color::asHexString(), Mesh2Shape::faces, SplineSurface::i, Mesh2Shape::mesh, Mesh::Segment::save(), segments, Mesh::Segment::setColor(), Mesh::Segment::setName(), App::Color::setPackedValue(), Path.Post.scripts.refactored_centroid_post::str, and Mesh::MeshObject::swap().
The documentation for this class was generated from the following file:
Mesher.cpp