FreeCAD: QGVPage.cpp File Reference
QGVPage.cpp File Reference
#include "PreCompiled.h"
#include <cmath>
#include <QApplication>
#include <QBitmap>
#include <QContextMenuEvent>
#include <QLabel>
#include <QMouseEvent>
#include <QPaintEvent>
#include <QPainter>
#include <QScrollBar>
#include <QWheelEvent>
#include <App/Application.h>
#include <App/Document.h>
#include <Base/Parameter.h>
#include <Gui/BitmapFactory.h>
#include <Gui/Document.h>
#include <Gui/NavigationStyle.h>
#include <Gui/Selection.h>
#include <Gui/View3DInventor.h>
#include <Gui/View3DInventorViewer.h>
#include <Mod/TechDraw/App/DrawPage.h>
#include <Mod/TechDraw/App/DrawSVGTemplate.h>
#include "MDIViewPage.h"
#include "PreferencesGui.h"
#include "QGSPage.h"
#include "QGVNavStyleBlender.h"
#include "QGVNavStyleCAD.h"
#include "QGVNavStyleGesture.h"
#include "QGVNavStyleInventor.h"
#include "QGVNavStyleMaya.h"
#include "QGVNavStyleOCC.h"
#include "QGVNavStyleOpenSCAD.h"
#include "QGVNavStyleRevit.h"
#include "QGVNavStyleTinkerCAD.h"
#include "QGVNavStyleTouchpad.h"
#include "QGVPage.h"
#include "Rez.h"
#include "TechDrawHandler.h"
#include "ViewProviderPage.h"
#include <Mod/TechDraw/Gui/moc_QGVPage.cpp>
Classes
class TechDrawGui::QGVPage::Private
Macros
#define CC_NS_URI "http://creativecommons.org/ns#"
#define DC_NS_URI "http://purl.org/dc/elements/1.1/"
#define RDF_NS_URI "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
#define INKSCAPE_NS_URI "http://www.inkscape.org/namespaces/inkscape"
#define SODIPODI_NS_URI "http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
#define PAN_WIDTH 16
#define PAN_HEIGHT 16
#define PAN_BYTES ((PAN_WIDTH + 7) / 8) * PAN_HEIGHT
#define PAN_HOT_X 7
#define PAN_HOT_Y 7
#define ZOOM_WIDTH 16
#define ZOOM_HEIGHT 16
#define ZOOM_BYTES ((ZOOM_WIDTH + 7) / 8) * ZOOM_HEIGHT
#define ZOOM_HOT_X 5
#define ZOOM_HOT_Y 7
Functions
static QCursor createCursor (QBitmap &bitmap, QBitmap &mask, int hotX, int hotY, double dpr)
Variables
static unsigned char pan_bitmap [((16+7)/8) *PAN_HEIGHT]
static unsigned char pan_mask_bitmap [((16+7)/8) *PAN_HEIGHT]
static unsigned char zoom_bitmap [((16+7)/8) *ZOOM_HEIGHT]
static unsigned char zoom_mask_bitmap [((16+7)/8) *ZOOM_HEIGHT]
Macro Definition Documentation
CC_NS_URI
#define CC_NS_URI "http://creativecommons.org/ns#"
Definition at line 71 of file QGVPage.cpp.
DC_NS_URI
#define DC_NS_URI "http://purl.org/dc/elements/1.1/"
Definition at line 72 of file QGVPage.cpp.
INKSCAPE_NS_URI
#define INKSCAPE_NS_URI "http://www.inkscape.org/namespaces/inkscape"
Definition at line 74 of file QGVPage.cpp.
PAN_BYTES
#define PAN_BYTES ((PAN_WIDTH + 7) / 8) * PAN_HEIGHT
Definition at line 81 of file QGVPage.cpp.
PAN_HEIGHT
#define PAN_HEIGHT 16
Definition at line 80 of file QGVPage.cpp.
PAN_HOT_X
#define PAN_HOT_X 7
Definition at line 82 of file QGVPage.cpp.
PAN_HOT_Y
#define PAN_HOT_Y 7
Definition at line 83 of file QGVPage.cpp.
PAN_WIDTH
#define PAN_WIDTH 16
Definition at line 79 of file QGVPage.cpp.
RDF_NS_URI
#define RDF_NS_URI "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
Definition at line 73 of file QGVPage.cpp.
SODIPODI_NS_URI
#define SODIPODI_NS_URI "http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
Definition at line 75 of file QGVPage.cpp.
ZOOM_BYTES
#define ZOOM_BYTES ((ZOOM_WIDTH + 7) / 8) * ZOOM_HEIGHT
Definition at line 96 of file QGVPage.cpp.
ZOOM_HEIGHT
#define ZOOM_HEIGHT 16
Definition at line 95 of file QGVPage.cpp.
ZOOM_HOT_X
#define ZOOM_HOT_X 5
Definition at line 97 of file QGVPage.cpp.
ZOOM_HOT_Y
#define ZOOM_HOT_Y 7
Definition at line 98 of file QGVPage.cpp.
ZOOM_WIDTH
#define ZOOM_WIDTH 16
Definition at line 94 of file QGVPage.cpp.
Function Documentation
createCursor()
static QCursor createCursor (QBitmap & bitmap, QBitmap & mask, int hotX, int hotY, double dpr) static
Definition at line 686 of file QGVPage.cpp.
Referenced by TechDrawGui::QGVPage::createStandardCursors().
Variable Documentation
pan_bitmap
unsigned char pan_bitmap[((16+7)/8) *PAN_HEIGHT] static
Initial value:
= {
    0xc0, 0x03, 0x60, 0x02, 0x20, 0x04, 0x10, 0x08, 0x68, 0x16, 0x54, 0x2a, 0x73, 0xce, 0x01, 0x80,
    0x01, 0x80, 0x73, 0xce, 0x54, 0x2a, 0x68, 0x16, 0x10, 0x08, 0x20, 0x04, 0x40, 0x02, 0xc0, 0x03}
Definition at line 85 of file QGVPage.cpp.
Referenced by TechDrawGui::QGVPage::createStandardCursors().
pan_mask_bitmap
unsigned char pan_mask_bitmap[((16+7)/8) *PAN_HEIGHT] static
Initial value:
= {
    0xc0, 0x03, 0xe0, 0x03, 0xe0, 0x07, 0xf0, 0x0f, 0xe8, 0x17, 0xdc, 0x3b, 0xff, 0xff, 0xff, 0xff,
    0xff, 0xff, 0xff, 0xff, 0xdc, 0x3b, 0xe8, 0x17, 0xf0, 0x0f, 0xe0, 0x07, 0xc0, 0x03, 0xc0, 0x03}
Definition at line 89 of file QGVPage.cpp.
Referenced by TechDrawGui::QGVPage::createStandardCursors().
zoom_bitmap
unsigned char zoom_bitmap[((16+7)/8) *ZOOM_HEIGHT] static
Initial value:
= {
    0x00, 0x0f, 0x80, 0x1c, 0x40, 0x38, 0x20, 0x70, 0x90, 0xe4, 0xc0, 0xcc, 0xf0, 0xfc, 0x00, 0x0c,
    0x00, 0x0c, 0xf0, 0xfc, 0xc0, 0xcc, 0x90, 0xe4, 0x20, 0x70, 0x40, 0x38, 0x80, 0x1c, 0x00, 0x0f}
Definition at line 100 of file QGVPage.cpp.
Referenced by TechDrawGui::QGVPage::createStandardCursors().
zoom_mask_bitmap
unsigned char zoom_mask_bitmap[((16+7)/8) *ZOOM_HEIGHT] static
Initial value:
= {
    0x00, 0x0f, 0x80, 0x1f, 0xc0, 0x3f, 0xe0, 0x7f, 0xf0, 0xff, 0xf0, 0xff, 0xf0, 0xff, 0x00, 0x0f,
    0x00, 0x0f, 0xf0, 0xff, 0xf0, 0xff, 0xf0, 0xff, 0xe0, 0x7f, 0xc0, 0x3f, 0x80, 0x1f, 0x00, 0x0f}
Definition at line 104 of file QGVPage.cpp.
Referenced by TechDrawGui::QGVPage::createStandardCursors().