FreeCAD: ifc2x3.ifcrelassignstocontrol Class Reference
ifc2x3.ifcrelassignstocontrol Class Reference
Public Member Functions
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__relatedobjects, inherited5__relatedobjectstype, relatingcontrol)
def relatingcontrol ()
def wr1 (self)
Public Member Functions inherited from ifc2x3.ifcrelassigns
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, relatedobjects, relatedobjectstype)
def relatedobjects ()
def relatedobjectstype ()
Public Member Functions inherited from ifc2x3.ifcrelationship
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description)
Public Member Functions inherited from ifc2x3.ifcroot
def globalid ()
def ownerhistory ()
def name ()
def description ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
relatingcontrol
Public Attributes inherited from ifc2x3.ifcrelassigns
relatedobjects
relatedobjectstype
Public Attributes inherited from ifc2x3.ifcroot
globalid
ownerhistory
name
description
Detailed Description
Entity ifcrelassignstocontrol definition.
:param relatingcontrol
:type relatingcontrol:ifccontrol
Definition at line 2755 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcrelassignstocontrol.__init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__relatedobjects, inherited5__relatedobjectstype, relatingcontrol)
Reimplemented in ifc2x3.ifcrelassignstoprojectorder, and ifc2x3.ifcrelschedulescostitems.
Definition at line 2761 of file ifc2x3.py.
Member Function Documentation
relatingcontrol()
def ifc2x3.ifcrelassignstocontrol.relatingcontrol ()
Definition at line 2766 of file ifc2x3.py.
References ifc2x3.ifcrelassignstocontrol._relatingcontrol, SCL.TypeChecker.check_type(), and ifc2x3.ifcrelassignstocontrol.relatingcontrol.
wr1()
def ifc2x3.ifcrelassignstocontrol.wr1 (self)
Reimplemented from ifc2x3.ifcrelassigns.
Reimplemented in ifc2x3.ifcrelassignstasks.
Definition at line 2778 of file ifc2x3.py.
References SCL.Builtin.SIZEOF().
Referenced by ifc4.ifctextalignment.__init__(), ifc4.ifcspecularroughness.__init__(), ifc4.ifcheatingvaluemeasure.__init__(), ifc4.ifctexttransformation.__init__(), ifc4.ifcfontstyle.__init__(), ifc4.ifcboxalignment.__init__(), ifc4.ifcpositiveplaneanglemeasure.__init__(), ifc4.ifcdimensioncount.__init__(), ifc4.ifcfontvariant.__init__(), ifc4.ifcfontweight.__init__(), ifc4.ifcnormalisedratiomeasure.__init__(), ifc4.ifcpositivelengthmeasure.__init__(), ifc4.ifcpositiveratiomeasure.__init__(), and ifc4.ifctextdecoration.__init__().
Member Data Documentation
relatingcontrol
ifc2x3.ifcrelassignstocontrol.relatingcontrol
Definition at line 2763 of file ifc2x3.py.
Referenced by ifc2x3.ifcrelassignstocontrol.relatingcontrol().
The documentation for this class was generated from the following file:
ifc2x3.py