FreeCAD: App::ExtensionPythonT< ExtensionT > Class Template Reference
App::ExtensionPythonT< ExtensionT > Class Template Reference
#include <ExtensionPython.h>
Public Types
using Inherited = ExtensionT
Public Member Functions
virtual Base::Type getExtensionTypeId (void) const override
ExtensionPythonT ()
~ExtensionPythonT () override=default
ExtensionPythonT (const ExtensionPythonT &)=delete
ExtensionPythonT (ExtensionPythonT &&)=delete
ExtensionPythonT & operator= (const ExtensionPythonT &)=delete
ExtensionPythonT & operator= (ExtensionPythonT &&)=delete
Static Public Member Functions
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Protected Member Functions
virtual const App::PropertyData & extensionGetPropertyData (void) const override
Static Protected Member Functions
static const App::PropertyData * extensionGetPropertyDataPtr (void)
Detailed Description
template<class ExtensionT>
class App::ExtensionPythonT< ExtensionT >
Generic Python extension class which allows every extension derived class to behave as a Python extension – simply by subclassing.
Definition at line 59 of file ExtensionPython.h.
Member Typedef Documentation
Inherited
template<class ExtensionT > using App::ExtensionPythonT< ExtensionT >::Inherited = ExtensionT
Definition at line 84 of file ExtensionPython.h.
Constructor & Destructor Documentation
ExtensionPythonT() [1/3]
template<class ExtensionT > App::ExtensionPythonT< ExtensionT >::ExtensionPythonT () inline
Definition at line 86 of file ExtensionPython.h.
~ExtensionPythonT()
template<class ExtensionT > App::ExtensionPythonT< ExtensionT >::~ExtensionPythonT () override default
ExtensionPythonT() [2/3]
template<class ExtensionT > App::ExtensionPythonT< ExtensionT >::ExtensionPythonT (const ExtensionPythonT< ExtensionT > &) delete
ExtensionPythonT() [3/3]
template<class ExtensionT > App::ExtensionPythonT< ExtensionT >::ExtensionPythonT (ExtensionPythonT< ExtensionT > &&) delete
Member Function Documentation
create()
void * App::SuppressibleExtensionPython::create (void) static
Definition at line 224 of file Extension.cpp.
Referenced by draftguitools.gui_labels.Label::action().
extensionGetPropertyData()
const App::PropertyData & App::SuppressibleExtensionPython::extensionGetPropertyData (void) const override protected virtual
Definition at line 224 of file Extension.cpp.
extensionGetPropertyDataPtr()
const App::PropertyData * App::SuppressibleExtensionPython::extensionGetPropertyDataPtr (void) static protected
Definition at line 224 of file Extension.cpp.
getExtensionClassTypeId()
Base::Type App::SuppressibleExtensionPython::getExtensionClassTypeId (void) static
Definition at line 224 of file Extension.cpp.
Referenced by App::GroupExtension::getGroupOfObject().
getExtensionTypeId()
Base::Type App::SuppressibleExtensionPython::getExtensionTypeId (void) const override virtual
Definition at line 224 of file Extension.cpp.
init()
void App::SuppressibleExtensionPython::init (void) static
Definition at line 224 of file Extension.cpp.
Referenced by App::Application::initTypes(), DocumentObject.DocumentObject::onChanged(), and PyMOD_INIT_FUNC().
operator=() [1/2]
template<class ExtensionT > ExtensionPythonT& App::ExtensionPythonT< ExtensionT >::operator= (const ExtensionPythonT< ExtensionT > &) delete
operator=() [2/2]
template<class ExtensionT > ExtensionPythonT& App::ExtensionPythonT< ExtensionT >::operator= (ExtensionPythonT< ExtensionT > &&) delete
The documentation for this class was generated from the following files:
ExtensionPython.h
Extension.cpp
GeoFeatureGroupExtension.cpp
Link.cpp
SuppressibleExtension.cpp