FreeCAD: Gui::ViewProviderGeometryObject Class Reference
Gui::ViewProviderGeometryObject Class Reference
#include <ViewProviderGeometryObject.h>
Public Member Functions
ViewProviderGeometryObject ()
constructor.
~ViewProviderGeometryObject () override
destructor.
void attach (App::DocumentObject *pcObject) override
void updateData (const App::Property *) override
bool isSelectable () const override
SoPickedPointList getPickedPoints (const SbVec2s &pos, const View3DInventorViewer &viewer, bool pickAll=false) const
SoPickedPoint * getPickedPoint (const SbVec2s &pos, const View3DInventorViewer &viewer) const
Public Member Functions inherited from Gui::ViewProviderDragger
ViewProviderDragger ()
constructor.
~ViewProviderDragger () override
destructor.
Base::Placement getTransformOrigin () const
Convenience method to obtain the transform origin.
void setTransformOrigin (const Base::Placement &placement)
Convenience method to set the transform origin.
void resetTransformOrigin ()
Resets transform origin to the object origin.
bool doubleClicked () override
is called by the tree if the user double clicks on the object
void setupContextMenu (QMenu *, QObject *, const char *) override
set up the context-menu with the supported edit modes
ViewProvider * startEditing (int ModNum=0) override
void updatePlacementFromDragger ()
updates placement of object based on dragger position
void updateTransformFromDragger ()
updates transform of object based on dragger position, can be used to preview movement
Base::Placement getObjectPlacement () const
Gets object placement relative to its coordinate system.
Base::Placement getDraggerPlacement () const
Gets current dragger placement, including current dragger movement.
Base::Placement getOriginalDraggerPlacement () const
Gets original dragger placement, without current dragger movement.
void setDraggerPlacement (const Base::Placement &placement)
Sets placement of dragger relative to objects origin.
Public Member Functions inherited from Gui::ViewProviderDocumentObject
ViewProviderDocumentObject ()
constructor.
~ViewProviderDocumentObject () override
destructor.
virtual void reattach (App::DocumentObject *)
void update (const App::Property *) override
void setActiveMode ()
Set the active mode, i.e. the first item of the 'Display' property.
void hide () override
Hide the object in the view.
void show () override
Show the object in the view.
const char * getTransactionText () const override
bool canDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const override
int replaceObject (App::DocumentObject *, App::DocumentObject *) override
bool showInTree () const override
void getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &) const override
Get a list of TaskBoxes associated with this object.
void updateView ()
Run a redraw.
App::DocumentObject * getObject () const
Get the object of this ViewProvider object.
template<class T >
T * getObject () const
Get the object of this ViewProvider object as specified type.
bool canDelete (App::DocumentObject *obj) const override
Asks the view provider if the given object can be deleted.
virtual bool acceptDeletionsInEdit ()
Ask the view provider if it accepts object deletions while in edit.
Gui::Document * getDocument () const
Get the GUI document to this ViewProvider object.
bool getElementPicked (const SoPickedPoint *, std::string &subname) const override
return a hit element given the picked point which contains the full node path
bool getDetailPath (const char *subname, SoFullPath *pPath, bool append, SoDetail *&det) const override
return the coin node detail and path to the node of the subname
virtual void forceUpdate (bool enable=true)
virtual bool isUpdateForced () const
virtual void startRestoring ()
virtual void finishRestoring ()
int getTreeRank () const
void setTreeRank (int value)
bool removeDynamicProperty (const char *prop) override
App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
virtual ViewProviderDocumentObject * getLinkedViewProvider (std::string *subname=nullptr, bool recursive=false) const
std::string getFullName () const override
virtual bool allowOverride (const App::DocumentObject &) const
void setShowable (bool enable)
bool isShowable () const
void startDefaultEditMode ()
Public Member Functions inherited from Gui::ViewProvider
ViewProvider ()
constructor.
~ViewProvider () override
destructor.
virtual SoSeparator * getRoot () const
SoSwitch * getModeSwitch () const
SoTransform * getTransformNode () const
SoSeparator * getAnnotation ()
virtual SoSeparator * getFrontRoot () const
virtual SoGroup * getChildRoot () const
virtual SoSeparator * getBackRoot () const
virtual bool canAddToSceneGraph () const
Indicate whether to be added to scene graph or not.
virtual bool isPartOfPhysicalObject () const
virtual std::vector< App::DocumentObject * > claimChildren3D () const
virtual bool useNewSelectionModel () const
indicates if the ViewProvider use the new Selection model
virtual std::string getElement (const SoDetail *) const
return a hit element to the selection path or 0
virtual SoDetail * getDetail (const char *) const
return the coin node detail of the subelement
int partialRender (const std::vector< std::string > &subelements, bool clear)
virtual std::vector< Base::Vector3d > getModelPoints (const SoPickedPoint *) const
virtual std::vector< Base::Vector3d > getSelectionShape (const char *Element) const
return the highlight lines for a given element or the whole shape
Base::BoundBox3d getBoundingBox (const char *subname=nullptr, bool transform=true, MDIView *view=nullptr) const
virtual bool onDelete (const std::vector< std::string > &subNames)
virtual void beforeDelete ()
virtual bool canDragObjects () const
virtual bool canDragObject (App::DocumentObject *) const
virtual bool canDragObjectToTarget (App::DocumentObject *obj, App::DocumentObject *target) const
virtual void dragObject (App::DocumentObject *)
virtual bool canDropObjects () const
virtual bool canDropObject (App::DocumentObject *) const
virtual bool canDragAndDropObject (App::DocumentObject *) const
virtual void dropObject (App::DocumentObject *)
virtual bool acceptReorderingObjects () const
virtual std::string getDropPrefix () const
return a subname referencing the sub-object holding the dropped objects
virtual std::string dropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements)
virtual bool canRemoveChildrenFromRoot () const
std::string getActiveDisplayMode () const
virtual void setDisplayMode (const char *ModeName)
set the display mode
virtual const char * getDefaultDisplayMode () const
get the default display mode
virtual std::vector< std::string > getDisplayModes () const
returns a list of all possible display modes
virtual bool isShow () const
checks whether the view provider is visible or not
void setVisible (bool)
bool isVisible () const
void setLinkVisible (bool)
bool isLinkVisible () const
virtual void setOverrideMode (const std::string &mode)
Overrides the display mode with mode.
const std::string getOverrideMode ()
virtual bool selectAll ()
virtual bool keyPressed (bool pressed, int key)
is called when the provider is in edit and a key event occurs. Only ESC ends edit.
virtual bool mouseMove (const SbVec2s &cursorPos, View3DInventorViewer *viewer)
is called when the provider is in edit and the mouse is moved
virtual bool mouseButtonPressed (int button, bool pressed, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
is called when the Provider is in edit and the mouse is clicked
virtual bool mouseWheelEvent (int delta, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
virtual QIcon getIcon () const
deliver the icon shown in the tree view
virtual QIcon mergeColorfulOverlayIcons (const QIcon &orig) const
virtual std::vector< App::DocumentObject * > claimChildren () const
virtual std::vector< App::DocumentObject * > claimChildrenRecursive () const
bool isUpdatesEnabled () const
void setUpdatesEnabled (bool enable)
unsigned long getStatus () const
return the status bits
bool testStatus (ViewStatus pos) const
void setStatus (ViewStatus pos, bool on)
std::string toString () const
virtual std::map< std::string, App::Color > getElementColors (const char *element=nullptr) const
virtual void setElementColors (const std::map< std::string, App::Color > &colors)
bool isEditing () const
void finishEditing ()
virtual void setTransformation (const Base::Matrix4D &rcMatrix)
set the viewing transformation of the provider
virtual void setTransformation (const SbMatrix &rcMatrix)
virtual MDIView * getMDIView () const
void Restore (Base::XMLReader &reader) override
bool isRestoring ()
void addDisplayMaskMode (SoNode *node, const char *type)
Adds a new display mask mode.
void setDisplayMaskMode (const char *type)
Activates the display mask mode type.
SoNode * getDisplayMaskMode (const char *type) const
Get the node to the display mask mode type.
std::vector< std::string > getDisplayMaskModes () const
Returns a list of added display mask modes.
void setDefaultMode (int)
int getDefaultMode () const
virtual void setRenderCacheMode (int)
Public Member Functions inherited from App::TransactionalObject
TransactionalObject ()
Constructor.
~TransactionalObject () override
Public Member Functions inherited from App::ExtensionContainer
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
Property * getPropertyByName (const char *name) const override
find a property by its name
template<typename T >
T * getPropertyByName (const char *name) const
find a property by its name, dynamic cased to specified type
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void onChanged (const Property *) override
get called by the container when a property has changed
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop) override
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Attributes
App::PropertyPercent Transparency
App::PropertyMaterialList ShapeAppearance
App::PropertyBool BoundingBox
App::PropertyBool Selectable
Public Attributes inherited from Gui::ViewProviderDragger
App::PropertyPlacement TransformOrigin
Public Attributes inherited from Gui::ViewProviderDocumentObject
App::PropertyEnumeration DisplayMode
App::PropertyBool Visibility
App::PropertyBool ShowInTree
App::PropertyEnumeration OnTopWhenSelected
App::PropertyEnumeration SelectionStyle
Public Attributes inherited from Gui::ViewProvider
boost::signals2::signal< void()> signalChangeIcon
signal on icon change
boost::signals2::signal< void(const QString &)> signalChangeToolTip
signal on tooltip change
boost::signals2::signal< void(const QString &)> signalChangeStatusTip
signal on status tip change
boost::signals2::signal< void(bool, Gui::HighlightMode)> signalChangeHighlight
signal on highlight change
Edit methods
SoMaterial * pcShapeMaterial {nullptr}
SoFCBoundingBox * pcBoundingBox {nullptr}
SoSwitch * pcBoundSwitch {nullptr}
SoBaseColor * pcBoundColor {nullptr}
SoPickStyle * pickStyle {nullptr}
App::Material materialAppearance
virtual void showBoundingBox (bool)
PyObject * getPyObject () override
Get the python wrapper for that ViewProvider.
void onChanged (const App::Property *prop) override
get called by the container whenever a property has been changed
void setSelectable (bool Selectable=true)
virtual unsigned long getBoundColor () const
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container. This method is typically called if the property on file has changed its name in more recent versions.
void setCoinAppearance (const App::Material &source)
Additional Inherited Members
Public Types inherited from Gui::ViewProvider
enum EditMode { Default = 0, Transform, Cutting, Color }
Public Types inherited from App::ExtensionContainer
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Static Public Member Functions inherited from Gui::ViewProviderDragger
static void updateTransform (const Base::Placement &from, SoTransform *to)
Static Public Member Functions inherited from Gui::ViewProvider
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
static SbMatrix convert (const Base::Matrix4D &rcMatrix)
static Base::Matrix4D convert (const SbMatrix &sbMat)
static void eventCallback (void *ud, SoEventCallback *node)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions inherited from Gui::ViewProviderDragger
bool setEdit (int ModNum) override
is called by the document when the provider goes in edit mode
void unsetEdit (int ModNum) override
is called when you lose the edit mode
void setEditViewer (View3DInventorViewer *, int ModNum) override
adjust viewer settings when editing a view provider
void unsetEditViewer (View3DInventorViewer *) override
restores viewer settings when leaving editing mode
bool forwardToLink ()
virtual TaskView::TaskDialog * getTransformDialog ()
Protected Member Functions inherited from Gui::ViewProviderDocumentObject
Gui::MDIView * getActiveView () const
Gui::MDIView * getEditingView () const
Gui::MDIView * getInventorView () const
Gui::MDIView * getViewOfNode (SoNode *node) const
void onBeforeChange (const App::Property *prop) override
get called before the value is changed
SoNode * findFrontRootOfType (const SoType &type) const
bool isAttachedToDocument () const override
const char * detachFromDocument () override
void onPropertyStatusChanged (const App::Property &prop, unsigned long oldStatus) override
get called when a property status has changed
void setModeSwitch () override
Turn on mode switch.
void addDefaultAction (QMenu *, const QString &)
Protected Member Functions inherited from Gui::ViewProvider
virtual QIcon mergeGreyableOverlayIcons (const QIcon &orig) const
int getEditingMode () const
return the edit mode or -1 if nothing is being edited
bool checkRecursion (SoNode *)
SoPickedPoint * getPointOnRay (const SbVec2s &pos, const View3DInventorViewer *viewer) const
SoPickedPoint * getPointOnRay (const SbVec3f &pos, const SbVec3f &dir, const View3DInventorViewer *viewer) const
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual void onEarlyChange (const Property *)
virtual const PropertyData & getPropertyData () const
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::ViewProviderDragger
CoinPtr< SoFCCSysDragger > csysDragger = nullptr
ViewProvider * forwardedViewProvider = nullptr
Protected Attributes inherited from Gui::ViewProviderDocumentObject
App::DocumentObject * pcObject {nullptr}
Gui::Document * pcDocument {nullptr}
Protected Attributes inherited from Gui::ViewProvider
SoSeparator * pcRoot
The root Separator of the ViewProvider.
SoTransform * pcTransform
this is transformation for the provider
const char * sPixmap
SoSwitch * pcModeSwitch
this is the mode switch, all the different viewing modes are collected here
SoSeparator * pcAnnotation {nullptr}
The root separator for annotations.
ViewProviderPy * pyViewObject {nullptr}
std::string overrideMode
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Detailed Description
The base class for all view providers that display geometric data, like mesh, point clouds and shapes.
Author
Werner Mayer
Definition at line 49 of file ViewProviderGeometryObject.h.
Constructor & Destructor Documentation
ViewProviderGeometryObject()
ViewProviderGeometryObject::ViewProviderGeometryObject ()
constructor.
Definition at line 71 of file ViewProviderGeometryObject.cpp.
References ADD_PROPERTY_TYPE, BoundingBox, App::Material::getDefaultAppearance(), intPercent, pcBoundColor, pcBoundingBox, Gui::ViewProvider::pcRoot, pcShapeMaterial, pickStyle, App::Prop_None, Selectable, setCoinAppearance(), App::PropertyIntegerConstraint::setConstraints(), App::PropertyBool::setValue(), ShapeAppearance, Gui::ViewProvider::sPixmap, Transparency, and App::Material::transparency.
~ViewProviderGeometryObject()
ViewProviderGeometryObject::~ViewProviderGeometryObject () override
destructor.
Definition at line 117 of file ViewProviderGeometryObject.cpp.
References pcBoundColor, pcBoundingBox, pcShapeMaterial, and pickStyle.
Member Function Documentation
attach()
void ViewProviderGeometryObject::attach (App::DocumentObject * pcObject) override virtual
Attaches the document object to this view provider.
Reimplemented from Gui::ViewProviderDocumentObject.
Reimplemented in FemGui::ViewProviderFemMesh, PathGui::ViewProviderPath, RobotGui::ViewProviderRobotObject, RobotGui::ViewProviderTrajectory, Gui::ViewProviderImagePlane, MeshGui::ViewProviderMeshObject, MeshGui::ViewProviderIndexedFaceSet, MeshGui::ViewProviderMesh, PartDesignGui::ViewProviderSubShapeBinder, PartDesignGui::ViewProviderShapeBinder, PartDesignGui::ViewProviderDatumPlane, PartDesignGui::ViewProviderDatumPoint, MeshGui::ViewProviderMeshFaceSet, MeshGui::ViewProviderMeshTransformDemolding, MeshGui::ViewProviderMeshTransform, PartDesignGui::ViewProviderDatumCoordinateSystem, PartDesignGui::ViewProviderDatumLine, SketcherGui::ViewProviderSketch, PointsGui::ViewProviderStructured, PointsGui::ViewProviderScattered, PartDesignGui::ViewProviderBoolean, PartGui::ViewProviderPartExt, PartDesignGui::ViewProviderAddSub, PartDesignGui::ViewProviderPrimitive, Gui::ViewProviderPoint, PartGui::ViewProvider2DObjectGrid, PartGui::ViewProviderPartReference, PartDesignGui::ViewProviderBody, FemGui::ViewProviderFemConstraint, PartGui::ViewProviderCurveNet, PartDesignGui::ViewProviderDatum, Gui::ViewProviderPlacement, Gui::ViewProviderPlane, and Gui::ViewProviderLine.
Definition at line 171 of file ViewProviderGeometryObject.cpp.
References Gui::ViewProviderDocumentObject::attach().
Referenced by Path.Dressup.Gui.Boundary.DressupPathBoundaryViewProvider::__init__(), Gui::ViewProviderDatum::attach(), Gui::ViewProviderImagePlane::attach(), RobotGui::ViewProviderTrajectory::attach(), Gui::ViewProviderPlacement::attach(), and RobotGui::ViewProviderRobotObject::attach().
getBoundColor()
unsigned long ViewProviderGeometryObject::getBoundColor () const protected virtual
Reimplemented in PathGui::ViewProviderPath.
Definition at line 259 of file ViewProviderGeometryObject.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::GetUnsigned().
Referenced by showBoundingBox().
getPickedPoint()
SoPickedPoint * ViewProviderGeometryObject::getPickedPoint (const SbVec2s & pos, const View3DInventorViewer & viewer) const
This method is provided for convenience and does basically the same as getPickedPoints() unless that only the closest point to the camera will be picked.
Note
It is in the response of the client programmer to delete the returned SoPickedPoint object.
Definition at line 238 of file ViewProviderGeometryObject.cpp.
References Gui::ViewProvider::getRoot(), RobotExample::pos, and OfflineRenderingUtils::viewer().
getPickedPoints()
SoPickedPointList ViewProviderGeometryObject::getPickedPoints (const SbVec2s & pos, const View3DInventorViewer & viewer, bool pickAll = false) const
Returns a list of picked points from the geometry under getRoot(). If pickAll is false (the default) only the intersection point closest to the camera will be picked, otherwise all intersection points will be picked.
Definition at line 217 of file ViewProviderGeometryObject.cpp.
References Gui::ViewProvider::getRoot(), RobotExample::pos, and OfflineRenderingUtils::viewer().
getPyObject()
PyObject * ViewProviderGeometryObject::getPyObject () override virtual
Get the python wrapper for that ViewProvider.
Reimplemented from Gui::ViewProviderDocumentObject.
Reimplemented in MeshGui::ViewProviderMesh, PartGui::ViewProviderPartExt, FemGui::ViewProviderFemMesh, PartDesignGui::ViewProvider, and FemGui::ViewProviderFemConstraint.
Definition at line 365 of file ViewProviderGeometryObject.cpp.
References Gui::ViewProvider::pyViewObject.
handleChangedPropertyName()
void ViewProviderGeometryObject::handleChangedPropertyName (Base::XMLReader & reader, const char * TypeName, const char * PropName) override protected virtual
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container. This method is typically called if the property on file has changed its name in more recent versions.
The default implementation does nothing.
Parameters
reader The XML stream to read from.
TypeName Name of property type on file.
PropName Name of property on file that does not exist in the container anymore.
Reimplemented from App::PropertyContainer.
Reimplemented in PartGui::ViewProviderPartExt, and FemGui::ViewProviderFemConstraint.
Definition at line 374 of file ViewProviderGeometryObject.cpp.
References Base::Persistence::getClassTypeId(), App::PropertyColor::getValue(), App::PropertyMaterial::getValue(), App::ExtensionContainer::handleChangedPropertyName(), TechDrawTools.TaskFillTemplateFields::reader, App::PropertyColor::Restore(), App::PropertyMaterial::Restore(), App::PropertyMaterialList::setDiffuseColor(), App::PropertyMaterialList::setValue(), and ShapeAppearance.
Referenced by PartGui::ViewProviderPartExt::handleChangedPropertyName().
isSelectable()
bool Gui::ViewProviderGeometryObject::isSelectable () const inline override virtual
Reimplemented from Gui::ViewProvider.
Reimplemented in SketcherGui::ViewProviderSketch, PartDesignGui::ViewProviderDatum, and Gui::ViewProviderPlacement.
Definition at line 72 of file ViewProviderGeometryObject.h.
References App::PropertyBool::getValue().
Referenced by SketcherGui::ViewProviderSketch::isSelectable().
onChanged()
void ViewProviderGeometryObject::onChanged (const App::Property * prop) override protected virtual
get called by the container whenever a property has been changed
Reimplemented from Gui::ViewProviderDragger.
Reimplemented in SketcherGui::ViewProviderSketch, MeshGui::ViewProviderMesh, PartGui::ViewProviderPartExt, FemGui::ViewProviderFemMesh, PointsGui::ViewProviderPoints, PartDesignGui::ViewProviderSubShapeBinder, PartDesignGui::ViewProviderBoolean, PathGui::ViewProviderPath, PartDesignGui::ViewProviderDatumPoint, FemGui::ViewProviderFemConstraint, SketcherGui::ViewProviderCustom, PartGui::ViewProviderCustom, PartGui::ViewProviderPartReference, PartGui::ViewProvider2DObjectGrid, PartDesignGui::ViewProvider, PartDesignGui::ViewProviderBody, Gui::ViewProviderPlacement, RobotGui::ViewProviderRobotObject, Gui::ViewProviderImagePlane, and PartDesignGui::ViewProviderDatumCoordinateSystem.
Definition at line 132 of file ViewProviderGeometryObject.cpp.
References BoundingBox, App::Property::getName(), Gui::ViewProviderDocumentObject::getObject(), App::PropertyListsT< T, ListT, ParentT >::getSize(), App::PropertyMaterialList::getTransparency(), App::PropertyInteger::getValue(), App::PropertyBool::getValue(), Gui::ViewProviderDragger::onChanged(), pcShapeMaterial, Selectable, setCoinAppearance(), setSelectable(), App::PropertyMaterialList::setTransparency(), App::PropertyInteger::setValue(), ShapeAppearance, showBoundingBox(), Gui::ViewProvider::testStatus(), App::DocumentObject::touch(), App::TouchOnColorChange, and Transparency.
Referenced by draftviewproviders.view_base.ViewProviderDraft::attach(), PartDesignGui::ViewProviderDatumCoordinateSystem::onChanged(), Gui::ViewProviderImagePlane::onChanged(), RobotGui::ViewProviderRobotObject::onChanged(), Gui::ViewProviderPlacement::onChanged(), Gui::ViewProviderDatum::onChanged(), PartDesignGui::ViewProviderDatumPoint::onChanged(), ArchSpace._ViewProviderSpace::onChanged(), ArchSchedule._ArchSchedule::setProperties(), draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), ArchAxis._ViewProviderAxis::updateData(), draftviewproviders.view_dimension.ViewProviderLinearDimension::updateData(), ArchSpace._ViewProviderSpace::updateData(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchSite._ViewProviderSite::updateData(), ArchSectionPlane._ViewProviderSectionPlane::updateData(), and ArchPanel.ViewProviderPanelSheet::updateData().
setCoinAppearance()
void ViewProviderGeometryObject::setCoinAppearance (const App::Material & source) protected
Definition at line 268 of file ViewProviderGeometryObject.cpp.
References App::Material::ambientColor, App::Color::b, App::Material::diffuseColor, App::Material::emissiveColor, App::Color::g, pcShapeMaterial, App::Color::r, App::Material::shininess, App::Material::specularColor, and App::Material::transparency.
Referenced by onChanged(), PartGui::ViewProviderPartExt::setHighlightedFaces(), and ViewProviderGeometryObject().
setSelectable()
void ViewProviderGeometryObject::setSelectable (bool Selectable = true) protected
Definition at line 335 of file ViewProviderGeometryObject.cpp.
References Gui::SoFCSelection::AUTO, SplineSurface::i, Gui::SoFCSelection::NOTSELECTED, Gui::SoFCSelection::OFF, Gui::ViewProvider::pcRoot, pickStyle, Gui::SoFCSelection::SEL_OFF, Gui::SoFCSelection::SEL_ON, and Gui::SoFCSelection::selectionMode.
Referenced by onChanged().
showBoundingBox()
void ViewProviderGeometryObject::showBoundingBox (bool show) virtual
Reimplemented in PathGui::ViewProviderPath.
Definition at line 296 of file ViewProviderGeometryObject.cpp.
References blue, Gui::SoFCBoundingBox::coordsOn, Gui::SoFCBoundingBox::dimensionsOn, getBoundColor(), green, pcBoundColor, pcBoundingBox, pcBoundSwitch, Gui::ViewProvider::pcRoot, red, and Gui::ViewProviderDocumentObject::show().
Referenced by onChanged().
updateData()
void ViewProviderGeometryObject::updateData (const App::Property * prop) override virtual
Reimplemented from Gui::ViewProviderDragger.
Reimplemented in MeshGui::ViewProviderMeshObject, MeshGui::ViewProviderIndexedFaceSet, MeshGui::ViewProviderMesh, MeshGui::ViewProviderMeshFaceSet, PartDesignGui::ViewProviderBody, FemGui::ViewProviderFemConstraint, SketcherGui::ViewProviderSketch, PointsGui::ViewProviderStructured, PointsGui::ViewProviderScattered, PartGui::ViewProviderChamfer, PartGui::ViewProviderMultiCommon, PartGui::ViewProviderPartExt, PartGui::ViewProviderCompound, PartGui::ViewProviderFillet, FemGui::ViewProviderFemConstraintTransform, FemGui::ViewProviderFemConstraintDisplacement, FemGui::ViewProviderFemConstraintHeatflux, FemGui::ViewProviderFemConstraintInitialTemperature, FemGui::ViewProviderFemConstraintTemperature, FemGui::ViewProviderFemConstraintContact, FemGui::ViewProviderFemConstraintPlaneRotation, PathGui::ViewProviderAreaView, FemGui::ViewProviderFemConstraintFixed, FemGui::ViewProviderFemConstraintFluidBoundary, FemGui::ViewProviderFemConstraintForce, PartGui::ViewProviderBoolean, FemGui::ViewProviderFemConstraintBearing, FemGui::ViewProviderFemConstraintGear, FemGui::ViewProviderFemConstraintPulley, FemGui::ViewProviderFemMesh, PartGui::ViewProviderRuledSurface, PartDesignGui::ViewProviderDatumPlane, PathGui::ViewProviderArea, PartGui::ViewProviderMultiFuse, PartDesignGui::ViewProviderAddSub, FemGui::ViewProviderFemConstraintPressure, FemGui::ViewProviderFemConstraintRigidBody, FemGui::ViewProviderFemConstraintSpring, FemGui::ViewProviderFemMeshShapeNetgen, PartDesignGui::ViewProviderPrimitive, SketcherGui::ViewProviderCustom, PartGui::ViewProviderCustom, PartGui::ViewProviderPartReference, PathGui::ViewProviderPathShape, PartDesignGui::ViewProvider, PathGui::ViewProviderPath, PartGui::ViewProvider2DObjectGrid, MeshGui::ViewProviderMeshTransform, PartGui::ViewProviderCurveNet, RobotGui::ViewProviderRobotObject, RobotGui::ViewProviderTrajectory, Gui::ViewProviderPlacement, PartDesignGui::ViewProviderDatumCoordinateSystem, Gui::ViewProviderImagePlane, and PartDesignGui::ViewProviderDatumLine.
Definition at line 176 of file ViewProviderGeometryObject.cpp.
References MengerSponge::box, Gui::ViewProvider::getBoundingBox(), App::PropertyComplexGeoData::getBoundingBox(), Base::Persistence::getClassTypeId(), App::Property::getName(), App::PropertyListsT< T, ListT, ParentT >::getSize(), Base::BaseClass::isDerivedFrom(), materialAppearance, Gui::SoFCBoundingBox::maxBounds, Gui::SoFCBoundingBox::minBounds, pcBoundingBox, App::PropertyMaterialList::setValue(), ShapeAppearance, and Gui::ViewProviderDragger::updateData().
Referenced by Path.Main.Gui.JobDlg.JobCreate::exec_(), draftviewproviders.view_wire.ViewProviderWire::onChanged(), draftviewproviders.view_dimension.ViewProviderLinearDimension::onChanged(), draftviewproviders.view_dimension.ViewProviderAngularDimension::onChanged(), Path.Op.Gui.Base.TaskPanelPage::pageUpdateData(), Path.Base.Gui.SetupSheet.OpTaskPanel::setupUi(), Path.Base.Gui.PropertyBag.TaskPanel::setupUi(), PartDesignGui::ViewProviderDatumLine::updateData(), Gui::ViewProviderImagePlane::updateData(), Gui::ViewProviderPlacement::updateData(), PartDesignGui::ViewProviderDatumCoordinateSystem::updateData(), PartGui::ViewProviderCurveNet::updateData(), FemGui::ViewProviderFemMesh::updateData(), PartDesignGui::ViewProviderDatumPlane::updateData(), PartGui::ViewProviderPartExt::updateData(), PointsGui::ViewProviderScattered::updateData(), MeshGui::ViewProviderMesh::updateData(), and PointsGui::ViewProviderStructured::updateData().
Member Data Documentation
BoundingBox
App::PropertyBool Gui::ViewProviderGeometryObject::BoundingBox
Definition at line 63 of file ViewProviderGeometryObject.h.
Referenced by onChanged(), PartDesignGui::ViewProviderBody::unifyVisualProperty(), and ViewProviderGeometryObject().
materialAppearance
App::Material Gui::ViewProviderGeometryObject::materialAppearance protected
Definition at line 122 of file ViewProviderGeometryObject.h.
Referenced by updateData().
pcBoundColor
SoBaseColor* Gui::ViewProviderGeometryObject::pcBoundColor {nullptr} protected
Definition at line 119 of file ViewProviderGeometryObject.h.
Referenced by showBoundingBox(), ViewProviderGeometryObject(), and ~ViewProviderGeometryObject().
pcBoundingBox
SoFCBoundingBox* Gui::ViewProviderGeometryObject::pcBoundingBox {nullptr} protected
Definition at line 117 of file ViewProviderGeometryObject.h.
Referenced by showBoundingBox(), updateData(), ViewProviderGeometryObject(), and ~ViewProviderGeometryObject().
pcBoundSwitch
SoSwitch* Gui::ViewProviderGeometryObject::pcBoundSwitch {nullptr} protected
Definition at line 118 of file ViewProviderGeometryObject.h.
Referenced by showBoundingBox().
pcShapeMaterial
SoMaterial* Gui::ViewProviderGeometryObject::pcShapeMaterial {nullptr} protected
Definition at line 116 of file ViewProviderGeometryObject.h.
Referenced by Gui::ViewProviderDatum::attach(), Gui::ViewProviderImagePlane::attach(), PartDesignGui::ViewProviderDatum::attach(), FemGui::ViewProviderFemConstraint::attach(), MeshGui::ViewProviderMeshTransform::attach(), FemGui::ViewProviderFemMesh::attach(), PartGui::ViewProviderPartExt::attach(), MeshGui::ViewProviderMesh::attach(), MeshGui::ViewProviderMesh::deselectFacet(), MeshGui::ViewProviderMesh::exportMesh(), MeshGui::ViewProviderMesh::highlightComponents(), MeshGui::ViewProviderMesh::highlightSegments(), MeshGui::ViewProviderMesh::highlightSelection(), onChanged(), MeshGui::ViewProviderMesh::resetFacetTransparency(), MeshGui::ViewProviderMesh::selectFacet(), MeshGui::ViewProviderMesh::setAmbientColor(), setCoinAppearance(), FemGui::ViewProviderFemMesh::setColorByNodeIdHelper(), MeshGui::ViewProviderMesh::setDiffuseColor(), MeshGui::ViewProviderMesh::setEmissiveColor(), MeshGui::ViewProviderMesh::setFacetTransparency(), PartGui::ViewProviderPartExt::setHighlightedFaces(), FemGui::ViewProviderFemMesh::setMaterialByColorArray(), FemGui::ViewProviderFemMesh::setMaterialOverall(), MeshGui::ViewProviderMesh::setSpecularColor(), MeshGui::ViewProviderMesh::tryColorPerVertexOrFace(), MeshGui::ViewProviderMesh::unhighlightSelection(), ViewProviderGeometryObject(), and ~ViewProviderGeometryObject().
pickStyle
SoPickStyle* Gui::ViewProviderGeometryObject::pickStyle {nullptr} protected
Definition at line 120 of file ViewProviderGeometryObject.h.
Referenced by setSelectable(), ViewProviderGeometryObject(), and ~ViewProviderGeometryObject().
Selectable
App::PropertyBool Gui::ViewProviderGeometryObject::Selectable
Definition at line 64 of file ViewProviderGeometryObject.h.
Referenced by Gui::ViewProviderDatum::attach(), onChanged(), PartDesignGui::ViewProvider::setBodyMode(), PartDesignGui::ViewProviderBody::unifyVisualProperty(), ViewProviderGeometryObject(), and PartGui::DlgProjectionOnSurface::~DlgProjectionOnSurface().
ShapeAppearance
App::PropertyMaterialList Gui::ViewProviderGeometryObject::ShapeAppearance
Definition at line 62 of file ViewProviderGeometryObject.h.
Referenced by Gui::ViewProviderLine::attach(), Gui::ViewProviderPlane::attach(), PartDesignGui::ViewProviderDatum::attach(), MeshGui::ViewProviderFace::attach(), PartDesignGui::ViewProviderShapeBinder::attach(), PartDesignGui::ViewProviderSubShapeBinder::attach(), MeshGui::ViewProviderMesh::deselectFacet(), PartGui::ViewProviderPartExt::getElementColors(), FemGui::ViewProviderFemConstraint::handleChangedPropertyName(), handleChangedPropertyName(), FemGui::ViewProviderFemConstraintOnBoundary::highlightReferences(), SurfaceGui::ViewProviderSections::highlightReferences(), SurfaceGui::ViewProviderFilling::highlightReferences(), PartDesignGui::ViewProviderDressUp::highlightReferences(), PartDesignGui::ViewProviderShapeBinder::highlightReferences(), MeshGui::ViewProviderMesh::highlightSegments(), MeshGui::ViewProviderMesh::highlightSelection(), PartDesignGui::ViewProviderSubShapeBinder::onChanged(), onChanged(), FemGui::ViewProviderFemMesh::onChanged(), PartGui::ViewProviderPartExt::onChanged(), MeshGui::ViewProviderMesh::onChanged(), PartGui::FaceAppearances::Private::Private(), PROPERTY_SOURCE(), FemGui::ViewProviderFemMesh::resetColorByElementId(), FemGui::ViewProviderFemMesh::resetColorByNodeId(), MeshGui::ViewProviderMesh::resetFacetTransparency(), FemGui::ViewProviderFemMesh::setColorByIdHelper(), MeshGui::ViewProviderMesh::setFacetTransparency(), FemGui::ViewProviderFemMesh::setMaterialByColorArray(), FemGui::ViewProviderFemMesh::setMaterialOverall(), MeshGui::ViewProviderMesh::tryColorPerVertexOrFace(), MeshGui::ViewProviderMesh::unhighlightSelection(), PartGui::ViewProviderPartExt::unsetHighlightedFaces(), updateData(), PartGui::ViewProviderMultiFuse::updateData(), FemGui::ViewProviderFemConstraintFluidBoundary::updateData(), PartGui::ViewProviderBoolean::updateData(), PartGui::ViewProviderCompound::updateData(), PartGui::ViewProviderFillet::updateData(), PartGui::ViewProviderMultiCommon::updateData(), PartGui::ViewProviderChamfer::updateData(), PartGui::ViewProviderPartExt::updateVisual(), PartDesignGui::ViewProviderDatum::ViewProviderDatum(), FemGui::ViewProviderFemMesh::ViewProviderFemMesh(), ViewProviderGeometryObject(), and Gui::ViewProviderImagePlane::ViewProviderImagePlane().
Transparency
App::PropertyPercent Gui::ViewProviderGeometryObject::Transparency
Definition at line 61 of file ViewProviderGeometryObject.h.
Referenced by PartGui::ViewProviderPartExt::getElementColors(), PartDesignGui::ViewProviderDatumPoint::onChanged(), PartDesignGui::ViewProviderSubShapeBinder::onChanged(), onChanged(), FemGui::ViewProviderFemMesh::onChanged(), PartGui::ViewProviderPartExt::onChanged(), MeshGui::ViewProviderMesh::tryColorPerVertexOrFace(), PartGui::ViewProviderPartExt::unsetHighlightedFaces(), PartGui::ViewProviderMultiFuse::updateData(), PartGui::ViewProviderBoolean::updateData(), PartGui::ViewProviderCompound::updateData(), PartGui::ViewProviderFillet::updateData(), PartGui::ViewProviderMultiCommon::updateData(), PartGui::ViewProviderChamfer::updateData(), PartDesignGui::ViewProviderDatum::ViewProviderDatum(), FemGui::ViewProviderFemMesh::ViewProviderFemMesh(), and ViewProviderGeometryObject().
The documentation for this class was generated from the following files:
ViewProviderGeometryObject.h
ViewProviderGeometryObject.cpp