FreeCAD: Surface::BlendPoint Class Reference
Surface::BlendPoint Class Reference
#include <BlendPoint.h>
Public Member Functions
BlendPoint ()
BlendPoint (const std::vector< Base::Vector3d > &vectorList)
~BlendPoint ()=default
void multiply (double f)
void setSize (double f)
int getContinuity ()
int nbVectors ()
Public Attributes
std::vector< Base::Vector3d > vectors
Detailed Description
Create a list of vectors formed by a point and some derivatives obtained from a curve or surface
Definition at line 59 of file BlendPoint.h.
Constructor & Destructor Documentation
BlendPoint() [1/2]
BlendPoint::BlendPoint ()
Definition at line 39 of file BlendPoint.cpp.
References vectors.
BlendPoint() [2/2]
BlendPoint::BlendPoint (const std::vector< Base::Vector3d > & vectorList) explicit
Constructor
Parameters
std::vector<Base::Vector3d>
Definition at line 35 of file BlendPoint.cpp.
~BlendPoint()
Surface::BlendPoint::~BlendPoint () default
Member Function Documentation
getContinuity()
int BlendPoint::getContinuity ()
Returns
continuity of this BlendPoint
Definition at line 61 of file BlendPoint.cpp.
References vectors.
multiply()
void BlendPoint::multiply (double f)
Scale the blendpoint vectors
Parameters
double scaling factor
Definition at line 44 of file BlendPoint.cpp.
References SCL.SimpleDataTypes::f, SplineSurface::i, nbVectors(), and vectors.
Referenced by setSize().
nbVectors()
int BlendPoint::nbVectors ()
Returns
Number of vectors of this BlendPoint
Definition at line 66 of file BlendPoint.cpp.
References vectors.
Referenced by multiply(), and setSize().
setSize()
void BlendPoint::setSize (double f)
Resize the blendpoint vectors by setting the size of the first derivative
Parameters
double new size
Definition at line 51 of file BlendPoint.cpp.
References SCL.SimpleDataTypes::f, multiply(), nbVectors(), and vectors.
Member Data Documentation
vectors
std::vector<Base::Vector3d> Surface::BlendPoint::vectors
Definition at line 82 of file BlendPoint.h.
Referenced by BlendPoint(), getContinuity(), multiply(), nbVectors(), and setSize().
The documentation for this class was generated from the following files:
BlendPoint.h
BlendPoint.cpp