FreeCAD: Gui::SoHighlightElementAction Class Reference
Gui::SoHighlightElementAction Class Reference
#include <SoFCUnifiedSelection.h>
Public Member Functions
SoHighlightElementAction ()
~SoHighlightElementAction () override
void setHighlighted (SbBool)
SbBool isHighlighted () const
void setColor (const SbColor &)
const SbColor & getColor () const
void setElement (const SoDetail *)
const SoDetail * getElement () const
Static Public Member Functions
static void initClass ()
Protected Member Functions
void beginTraversal (SoNode *node) override
Detailed Description
Author
Werner Mayer
Definition at line 380 of file SoFCUnifiedSelection.h.
Constructor & Destructor Documentation
SoHighlightElementAction()
SoHighlightElementAction::SoHighlightElementAction ()
Definition at line 834 of file SoFCUnifiedSelection.cpp.
~SoHighlightElementAction()
SoHighlightElementAction::~SoHighlightElementAction () override default
Member Function Documentation
beginTraversal()
void SoHighlightElementAction::beginTraversal (SoNode * node) override protected
Definition at line 841 of file SoFCUnifiedSelection.cpp.
getColor()
const SbColor & SoHighlightElementAction::getColor () const
Definition at line 866 of file SoFCUnifiedSelection.cpp.
Referenced by PartGui::SoBrepEdgeSet::doAction(), PartGui::SoBrepPointSet::doAction(), PartGui::SoBrepFaceSet::doAction(), and draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::setValues().
getElement()
const SoDetail * SoHighlightElementAction::getElement () const
Definition at line 876 of file SoFCUnifiedSelection.cpp.
Referenced by PartGui::SoBrepEdgeSet::doAction(), PartGui::SoBrepPointSet::doAction(), and PartGui::SoBrepFaceSet::doAction().
initClass()
void SoHighlightElementAction::initClass () static
Definition at line 817 of file SoFCUnifiedSelection.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
isHighlighted()
SbBool SoHighlightElementAction::isHighlighted () const
Definition at line 856 of file SoFCUnifiedSelection.cpp.
Referenced by Gui::SoFCSelectionCounter::checkAction(), PartGui::SoBrepEdgeSet::doAction(), PartGui::SoBrepPointSet::doAction(), and PartGui::SoBrepFaceSet::doAction().
setColor()
void SoHighlightElementAction::setColor (const SbColor & c)
Definition at line 861 of file SoFCUnifiedSelection.cpp.
References SCL.SimpleDataTypes::c.
Referenced by Gui::SoFCUnifiedSelection::doAction().
setElement()
void SoHighlightElementAction::setElement (const SoDetail * det)
Definition at line 871 of file SoFCUnifiedSelection.cpp.
Referenced by Gui::SoFCUnifiedSelection::doAction().
setHighlighted()
void SoHighlightElementAction::setHighlighted (SbBool ok)
Definition at line 851 of file SoFCUnifiedSelection.cpp.
Referenced by Gui::SoFCUnifiedSelection::doAction().
The documentation for this class was generated from the following files:
SoFCUnifiedSelection.h
SoFCUnifiedSelection.cpp