FreeCAD: OverlayWidgets.cpp File Reference
OverlayWidgets.cpp File Reference
#include "PreCompiled.h"
#include <QAction>
#include <QApplication>
#include <QBoxLayout>
#include <QComboBox>
#include <QDockWidget>
#include <QHeaderView>
#include <QKeyEvent>
#include <QMdiArea>
#include <QMenu>
#include <QPainter>
#include <QPointer>
#include <QSpacerItem>
#include <QSplitter>
#include <QTabBar>
#include <QTextStream>
#include <QTimerEvent>
#include <QToolTip>
#include <QTreeView>
#include <QScrollBar>
#include <QPainterPath>
#include <QPropertyAnimation>
#include <array>
#include <unordered_map>
#include "OverlayWidgets.h"
#include <Base/Tools.h>
#include <Base/Console.h>
#include <App/Application.h>
#include "Application.h"
#include "BitmapFactory.h"
#include "Clipping.h"
#include "ComboView.h"
#include "Command.h"
#include "Control.h"
#include "MainWindow.h"
#include "MDIView.h"
#include "NaviCube.h"
#include "OverlayManager.h"
#include "OverlayParams.h"
#include "TaskView/TaskView.h"
#include "Tree.h"
#include "TreeParams.h"
#include "propertyeditor/PropertyEditor.h"
#include "moc_OverlayWidgets.cpp"
Functions
FC_LOG_LEVEL_INIT ("Dock", true, true)
static int widgetMinSize (const QWidget *widget, bool margin=false)
static bool isNear (const QPoint &a, const QPoint &b, int tol=16)
QT_BEGIN_NAMESPACE Q_WIDGETS_EXPORT void qt_blurImage (QPainter *p, QImage &blurImage, qreal radius, bool quality, bool alphaOnly, int transposed=0)
Function Documentation
FC_LOG_LEVEL_INIT()
FC_LOG_LEVEL_INIT ("Dock" , true , true)
isNear()
static bool isNear (const QPoint & a, const QPoint & b, int tol = 16) inline static
Definition at line 2046 of file OverlayWidgets.cpp.
References a, and SCL.SimpleDataTypes::b.
Referenced by Gui::OverlayTitleBar::mouseMoveEvent().
qt_blurImage()
QT_BEGIN_NAMESPACE Q_WIDGETS_EXPORT void qt_blurImage (QPainter * p, QImage & blurImage, qreal radius, bool quality, bool alphaOnly, int transposed = 0)
Referenced by Gui::OverlayGraphicsEffect::draw().
widgetMinSize()
static int widgetMinSize (const QWidget * widget, bool margin = false) inline static
Definition at line 86 of file OverlayWidgets.cpp.
Referenced by Gui::OverlaySizeGrip::OverlaySizeGrip(), Gui::OverlayTabWidget::prepareTitleWidget(), Gui::OverlayTabWidget::setupLayout(), and Gui::OverlaySplitterHandle::sizeHint().