FreeCAD: Wm4::DistVector3Triangle3< Real > Class Template Reference
Wm4::DistVector3Triangle3< Real > Class Template Reference
#include <Wm4DistVector3Triangle3.h>
Public Member Functions
DistVector3Triangle3 (const Vector3< Real > &rkVector, const Triangle3< Real > &rkTriangle)
const Vector3< Real > & GetVector () const
const Triangle3< Real > & GetTriangle () const
virtual Real Get ()
virtual Real GetSquared ()
virtual Real Get (Real fT, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
virtual Real GetSquared (Real fT, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
Real GetTriangleBary (int i) const
Public Member Functions inherited from Wm4::Distance< Real, Vector3< Real > >
virtual ~Distance ()
virtual Real Get (Real fTMin, Real fTMax, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
virtual Real GetSquared (Real fTMin, Real fTMax, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
virtual Real GetDerivative (Real fT, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
virtual Real GetDerivativeSquared (Real fT, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
void SetDifferenceStep (Real fDifferenceStep)
Real GetDifferenceStep () const
Real GetContactTime () const
const Vector3< Real > & GetClosestPoint0 () const
const Vector3< Real > & GetClosestPoint1 () const
bool HasMultipleClosestPoints0 () const
bool HasMultipleClosestPoints1 () const
Additional Inherited Members
Public Attributes inherited from Wm4::Distance< Real, Vector3< Real > >
int MaximumIterations
Real ZeroThreshold
Protected Member Functions inherited from Wm4::Distance< Real, Vector3< Real > >
Distance ()
Protected Attributes inherited from Wm4::Distance< Real, Vector3< Real > >
Real m_fContactTime
Vector3< Real > m_kClosestPoint0
Vector3< Real > m_kClosestPoint1
bool m_bHasMultipleClosestPoints0
bool m_bHasMultipleClosestPoints1
Real m_fDifferenceStep
Real m_fInvTwoDifferenceStep
Detailed Description
template<class Real>
class Wm4::DistVector3Triangle3< Real >
Definition at line 28 of file Wm4DistVector3Triangle3.h.
Constructor & Destructor Documentation
DistVector3Triangle3()
template<class Real > Wm4::DistVector3Triangle3< Real >::DistVector3Triangle3 (const Vector3< Real > & rkVector, const Triangle3< Real > & rkTriangle)
Definition at line 24 of file Wm4DistVector3Triangle3.cpp.
Member Function Documentation
Get() [1/2]
template<class Real > Real Wm4::DistVector3Triangle3< Real >::Get virtual
Implements Wm4::Distance< Real, Vector3< Real > >.
Definition at line 45 of file Wm4DistVector3Triangle3.cpp.
References Wm4::Math< Real >::Sqrt().
Referenced by MeshCore::MeshGeomFacet::DistanceToPoint(), and Wm4::DistVector3Triangle3< Real >::Get().
Get() [2/2]
template<class Real > Real Wm4::DistVector3Triangle3< Real >::Get (Real fT, const Vector3< Real > & rkVelocity0, const Vector3< Real > & rkVelocity1) virtual
Implements Wm4::Distance< Real, Vector3< Real > >.
Definition at line 289 of file Wm4DistVector3Triangle3.cpp.
References Wm4::DistVector3Triangle3< Real >::Get().
GetSquared() [1/2]
template<class Real > Real Wm4::DistVector3Triangle3< Real >::GetSquared virtual
Implements Wm4::Distance< Real, Vector3< Real > >.
Definition at line 52 of file Wm4DistVector3Triangle3.cpp.
References Wm4::Vector3< Real >::Dot(), Wm4::Math< Real >::FAbs(), and Wm4::Vector3< Real >::SquaredLength().
Referenced by Wm4::DistSegment3Triangle3< Real >::GetSquared(), and Wm4::DistVector3Triangle3< Real >::GetSquared().
GetSquared() [2/2]
template<class Real > Real Wm4::DistVector3Triangle3< Real >::GetSquared (Real fT, const Vector3< Real > & rkVelocity0, const Vector3< Real > & rkVelocity1) virtual
Implements Wm4::Distance< Real, Vector3< Real > >.
Definition at line 301 of file Wm4DistVector3Triangle3.cpp.
References Wm4::DistVector3Triangle3< Real >::GetSquared().
GetTriangle()
template<class Real > const Triangle3< Real > & Wm4::DistVector3Triangle3< Real >::GetTriangle
Definition at line 39 of file Wm4DistVector3Triangle3.cpp.
GetTriangleBary()
template<class Real > Real Wm4::DistVector3Triangle3< Real >::GetTriangleBary (int i) const
Definition at line 313 of file Wm4DistVector3Triangle3.cpp.
References SplineSurface::i.
Referenced by Wm4::DistSegment3Triangle3< Real >::GetSquared().
GetVector()
template<class Real > const Vector3< Real > & Wm4::DistVector3Triangle3< Real >::GetVector
Definition at line 33 of file Wm4DistVector3Triangle3.cpp.
The documentation for this class was generated from the following files:
Wm4DistVector3Triangle3.h
Wm4DistVector3Triangle3.cpp