FreeCAD: Mesh::ExporterAMF Class Reference
Mesh::ExporterAMF Class Reference
Used for exporting to Additive Manufacturing File (AMF) format.
#include <Exporter.h>
Classes
class VertLess
Public Member Functions
ExporterAMF (std::string fileName, const std::map< std::string, std::string > &meta, bool compress=true)
Writes AMF header.
~ExporterAMF () override
Writes AMF footer.
ExporterAMF (const ExporterAMF &)=delete
ExporterAMF (ExporterAMF &&)=delete
ExporterAMF & operator= (const ExporterAMF &)=delete
ExporterAMF & operator= (ExporterAMF &&)=delete
bool addMesh (const char *name, const MeshObject &mesh) override
Public Member Functions inherited from Mesh::Exporter
Exporter ()
virtual ~Exporter ()=default
int addObject (App::DocumentObject *obj, float tol)
Add object and all subobjects and links etc. Returns the number of stuff added.
Exporter (const Exporter &)=delete
Exporter (Exporter &&)=delete
Exporter & operator= (const Exporter &)=delete
Exporter & operator= (Exporter &&)=delete
Additional Inherited Members
Protected Member Functions inherited from Mesh::Exporter
void throwIfNoPermission (const std::string &)
Static Protected Member Functions inherited from Mesh::Exporter
static std::string xmlEscape (const std::string &input)
Does some simple escaping of characters for XML-type exports.
Protected Attributes inherited from Mesh::Exporter
std::map< const App::DocumentObject *, std::vector< std::string > > subObjectNameCache
std::map< const App::DocumentObject *, MeshObject > meshCache
Detailed Description
Used for exporting to Additive Manufacturing File (AMF) format.
The constructor and destructor write the beginning and end of the AMF, addObject() is used to add geometry
Definition at line 258 of file Exporter.h.
Constructor & Destructor Documentation
ExporterAMF() [1/3]
ExporterAMF::ExporterAMF (std::string fileName, const std::map< std::string, std::string > & meta, bool compress = true)
Writes AMF header.
meta information passed in is applied at the <amf> tag level
Definition at line 331 of file Exporter.cpp.
References Base::FileInfo::fileName(), Base::FileInfo::filePath(), and Mesh::Exporter::throwIfNoPermission().
~ExporterAMF()
ExporterAMF::~ExporterAMF () override
Writes AMF footer.
Definition at line 364 of file Exporter.cpp.
ExporterAMF() [2/3]
Mesh::ExporterAMF::ExporterAMF (const ExporterAMF &) delete
ExporterAMF() [3/3]
Mesh::ExporterAMF::ExporterAMF (ExporterAMF &&) delete
Member Function Documentation
addMesh()
bool ExporterAMF::addMesh (const char * name, const MeshObject & mesh) override virtual
Implements Mesh::Exporter.
Definition at line 407 of file Exporter.cpp.
References MeshCore::MeshFacetIterator::End(), SplineSurface::i, Mesh2Shape::mesh, and Mesh::Exporter::xmlEscape().
operator=() [1/2]
ExporterAMF& Mesh::ExporterAMF::operator= (const ExporterAMF &) delete
operator=() [2/2]
ExporterAMF& Mesh::ExporterAMF::operator= (ExporterAMF &&) delete
The documentation for this class was generated from the following files:
Exporter.h
Exporter.cpp