FreeCAD: draftguitools
draftguitools
DRAFT
Modules that define the workbench GuiCommands to perform actions.
Namespaces
gui_annotationstyleeditor
Provides GUI tools to create and edit annotation styles.
gui_arcs
Provides GUI tools to create circular arc objects.
gui_arrays
Provides GUI tools to create parametric Array objects.
gui_base
Provides the base classes for newer Draft Gui Commands.
gui_base_original
Provides the base classes for most old Draft Gui Commands.
gui_beziers
Provides GUI tools to create BezCurve objects.
gui_circles
Provides GUI tools to create Circle objects.
gui_circulararray
Provides GUI tools to create circular Array objects.
gui_clone
Provides GUI tools to create Clone objects.
gui_dimension_ops
Provides GUI tools to modify dimension objects.
gui_dimensions
Provides GUI tools to create dimension objects.
gui_downgrade
Provides GUI tools to downgrade objects.
gui_draft2sketch
Provides GUI tools to convert Draft objects to Sketches and back.
gui_edit
Provides GUI tools to start the edit mode of different objects.
gui_edit_arch_objects
Provides support functions to edit Arch objects.
gui_edit_draft_objects
Provides support functions to edit Draft objects.
gui_edit_part_objects
Provides support functions to edit Part objects.
gui_edit_sketcher_objects
Provides support functions to edit Sketch objects.
gui_ellipses
Provides GUI tools to create Ellipse objects.
gui_facebinders
Provides GUI tools to create Facebinder objects.
gui_fillet
Provides GUI tools to create Fillet objects between two lines.
gui_grid
Provides GUI tools to enable and disable the working plane grid.
gui_groups
Provides GUI tools to do various operations with groups.
gui_heal
Provides GUI tools to repair objects created with older versions.
gui_hyperlink
Provides GUI tools to open hyperlinks to internal/external documents.
gui_join
Provides GUI tools to join lines and wires.
gui_labels
Provides GUI tools to create Label objects.
gui_layers
Provides GUI tools to create Layer objects.
gui_lines
Provides GUI tools to create straight Line and Wire objects.
gui_lineslope
Provides GUI tools to change the slope of a line.
gui_mirror
Provides GUI tools to create mirrored objects.
gui_move
Provides GUI tools to move objects in the 3D space.
gui_offset
Provides GUI tools to create offsets from objects.
gui_orthoarray
Provides GUI tools to create orthogonal Array objects.
gui_patharray
Provides GUI tools to create PathArray objects.
gui_pathtwistedarray
Provides GUI tools to create PathTwistedArray objects.
gui_planeproxy
Provides GUI tools to create WorkingPlaneProxy objects.
gui_pointarray
Provides GUI tools to create PointArray objects.
gui_points
Provides GUI tools to create simple Point objects.
gui_polararray
Provides GUI tools to create polar Array objects.
gui_polygons
Provides GUI tools to create regular Polygon objects.
gui_rectangles
Provides GUI tools to create Rectangle objects.
gui_rotate
Provides GUI tools to rotate objects in the 3D space.
gui_scale
Provides GUI tools to scale objects in the 3D space.
gui_selectplane
Provides GUI tools to set up the working plane and its grid.
gui_setstyle
Provides GUI tools to set Draft styles such as color or line width.
gui_shape2dview
Provides GUI tools to project an object into a 2D plane.
gui_shapestrings
Provides GUI tools to create text shapes with a particular font.
gui_snapper
Provides the Snapper class to define the snapping tools and modes.
gui_snaps
Provides GUI tools to activate the different snapping methods.
gui_splines
Provides GUI tools to create BSpline objects.
gui_split
Provides GUI tools to split line and wire objects.
gui_stretch
Provides GUI tools to stretch Draft objects.
gui_styles
Provides GUI tools to apply styles to objects.
gui_subelements
Provides GUI tools to highlight subelements of objects.
gui_texts
Provides GUI tools to create simple Text objects.
gui_togglemodes
Provides GUI tools to set different modes of other tools.
gui_tool_utils
Provides utility functions that are used by many Draft Gui Commands.
gui_trackers
Provides Coin based objects used to preview objects being built.
gui_trimex
Provides GUI tools to trim and extend lines.
gui_upgrade
Provides GUI tools to upgrade objects.
gui_wire2spline
Provides GUI tools to convert polylines to B-splines and back.
Classes
class draftguitools.gui_annotationstyleeditor.AnnotationStyleEditor
class draftguitools.gui_arcs.Arc
class draftguitools.gui_arcs.Arc_3Points
class draftguitools.gui_arcs.ArcGroup
class draftguitools.gui_arrays.ArrayGroup
class draftguitools.gui_base.GuiCommandSimplest
class draftguitools.gui_base.GuiCommandNeedsSelection
class draftguitools.gui_base.GuiCommandBase
class draftguitools.gui_base_original.DraftTool
class draftguitools.gui_base_original.Creator
class draftguitools.gui_base_original.Modifier
class draftguitools.gui_beziers.BezCurve
class draftguitools.gui_beziers.CubicBezCurve
class draftguitools.gui_beziers.BezierGroup
class draftguitools.gui_circles.Circle
class draftguitools.gui_circulararray.CircularArray
class draftguitools.gui_clone.Clone
class draftguitools.gui_dimension_ops.FlipDimension
class draftguitools.gui_dimensions.Dimension
class draftguitools.gui_downgrade.Downgrade
class draftguitools.gui_draft2sketch.Draft2Sketch
class draftguitools.gui_edit.Edit
class draftguitools.gui_edit.GuiToolsRepository
class draftguitools.gui_edit_arch_objects.ArchWallGuiTools
class draftguitools.gui_edit_arch_objects.ArchWindowGuiTools
class draftguitools.gui_edit_arch_objects.ArchStructureGuiTools
class draftguitools.gui_edit_arch_objects.ArchSpaceGuiTools
class draftguitools.gui_edit_arch_objects.ArchPanelCutGuiTools
class draftguitools.gui_edit_arch_objects.ArchPanelSheetGuiTools
class draftguitools.gui_edit_base_object.GuiTools
class draftguitools.gui_edit_draft_objects.DraftWireGuiTools
class draftguitools.gui_edit_draft_objects.DraftBSplineGuiTools
class draftguitools.gui_edit_draft_objects.DraftRectangleGuiTools
class draftguitools.gui_edit_draft_objects.DraftCircleGuiTools
class draftguitools.gui_edit_draft_objects.DraftEllipseGuiTools
class draftguitools.gui_edit_draft_objects.DraftPolygonGuiTools
class draftguitools.gui_edit_draft_objects.DraftDimensionGuiTools
class draftguitools.gui_edit_draft_objects.DraftBezCurveGuiTools
class draftguitools.gui_edit_part_objects.PartLineGuiTools
class draftguitools.gui_edit_part_objects.PartBoxGuiTools
class draftguitools.gui_edit_part_objects.PartCylinderGuiTools
class draftguitools.gui_edit_part_objects.PartConeGuiTools
class draftguitools.gui_edit_part_objects.PartSphereGuiTools
class draftguitools.gui_edit_sketcher_objects.SketcherSketchObjectGuiTools
class draftguitools.gui_ellipses.Ellipse
class draftguitools.gui_facebinders.Facebinder
class draftguitools.gui_fillets.Fillet
class draftguitools.gui_grid.ToggleGrid
class draftguitools.gui_groups.AddToGroup
class draftguitools.gui_groups.SelectGroup
class draftguitools.gui_groups.SetAutoGroup
class draftguitools.gui_groups.AddToConstruction
class draftguitools.gui_groups.AddNamedGroup
class draftguitools.gui_groups.Ui_AddNamedGroup
class draftguitools.gui_heal.Heal
class draftguitools.gui_hyperlink.Draft_Hyperlink
class draftguitools.gui_join.Join
class draftguitools.gui_labels.Label
class draftguitools.gui_layers.Layer
class draftguitools.gui_layers.LayerManager
class draftguitools.gui_layers.Layers_Delegate
class draftguitools.gui_lines.Line
class draftguitools.gui_lines.Wire
class draftguitools.gui_lineslope.LineSlope
class draftguitools.gui_mirror.Mirror
class draftguitools.gui_move.Move
class draftguitools.gui_offset.Offset
class draftguitools.gui_orthoarray.OrthoArray
class draftguitools.gui_patharray.PathArray
class draftguitools.gui_patharray.PathLinkArray
class draftguitools.gui_pathtwistedarray.PathTwistedArray
class draftguitools.gui_pathtwistedarray.PathTwistedLinkArray
class draftguitools.gui_planeproxy.Draft_WorkingPlaneProxy
class draftguitools.gui_pointarray.PointArray
class draftguitools.gui_pointarray.PointLinkArray
class draftguitools.gui_points.Point
class draftguitools.gui_polararray.PolarArray
class draftguitools.gui_polygons.Polygon
class draftguitools.gui_rectangles.Rectangle
class draftguitools.gui_rotate.Rotate
class draftguitools.gui_scale.Scale
class draftguitools.gui_selectplane.Draft_SelectPlane
class draftguitools.gui_setstyle.Draft_SetStyle
class draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel
class draftguitools.gui_shape2dview.Shape2DView
class draftguitools.gui_shapestrings.ShapeString
class draftguitools.gui_snapper.Snapper
class draftguitools.gui_snaps.Draft_Snap_Base
class draftguitools.gui_snaps.Draft_Snap_Lock
class draftguitools.gui_snaps.Draft_Snap_Midpoint
class draftguitools.gui_snaps.Draft_Snap_Perpendicular
class draftguitools.gui_snaps.Draft_Snap_Grid
class draftguitools.gui_snaps.Draft_Snap_Intersection
class draftguitools.gui_snaps.Draft_Snap_Parallel
class draftguitools.gui_snaps.Draft_Snap_Endpoint
class draftguitools.gui_snaps.Draft_Snap_Angle
class draftguitools.gui_snaps.Draft_Snap_Center
class draftguitools.gui_snaps.Draft_Snap_Extension
class draftguitools.gui_snaps.Draft_Snap_Near
class draftguitools.gui_snaps.Draft_Snap_Ortho
class draftguitools.gui_snaps.Draft_Snap_Special
class draftguitools.gui_snaps.Draft_Snap_Dimensions
class draftguitools.gui_snaps.Draft_Snap_WorkingPlane
class draftguitools.gui_snaps.ShowSnapBar
class draftguitools.gui_splines.BSpline
class draftguitools.gui_split.Split
class draftguitools.gui_stretch.Stretch
class draftguitools.gui_styles.ApplyStyle
class draftguitools.gui_subelements.SubelementHighlight
class draftguitools.gui_texts.Text
class draftguitools.gui_togglemodes.BaseMode
class draftguitools.gui_togglemodes.ToggleConstructionMode
class draftguitools.gui_togglemodes.ToggleDisplayMode
class draftguitools.gui_trackers.Tracker
class draftguitools.gui_trackers.snapTracker
class draftguitools.gui_trackers.lineTracker
class draftguitools.gui_trackers.rectangleTracker
class draftguitools.gui_trackers.dimTracker
class draftguitools.gui_trackers.bsplineTracker
class draftguitools.gui_trackers.bezcurveTracker
class draftguitools.gui_trackers.arcTracker
class draftguitools.gui_trackers.ghostTracker
class draftguitools.gui_trackers.editTracker
class draftguitools.gui_trackers.PlaneTracker
class draftguitools.gui_trackers.wireTracker
class draftguitools.gui_trackers.gridTracker
class draftguitools.gui_trackers.boxTracker
class draftguitools.gui_trackers.radiusTracker
class draftguitools.gui_trackers.archDimTracker
class draftguitools.gui_trimex.Trimex
class draftguitools.gui_upgrade.Upgrade
class draftguitools.gui_wire2spline.WireToBSpline
Functions
def draftguitools.gui_groups.moveToGroup (group)
def draftguitools.gui_hyperlink.QT_TRANSLATE_NOOP (ctx, txt)
def draftguitools.gui_layers.getColorIcon (color)
def draftguitools.gui_setstyle.QT_TRANSLATE_NOOP (ctx, txt)
def draftguitools.gui_tool_utils.get_mod_constrain_key ()
def draftguitools.gui_tool_utils.get_mod_snap_key ()
def draftguitools.gui_tool_utils.get_mod_alt_key ()
def draftguitools.gui_tool_utils.format_unit (exp, unit="mm")
def draftguitools.gui_tool_utils.select_object (arg)
def draftguitools.gui_tool_utils.has_mod (args, mod)
def draftguitools.gui_tool_utils.set_mod (args, mod, state)
def draftguitools.gui_tool_utils.get_point (target, args, noTracker=False)
def draftguitools.gui_tool_utils.set_working_plane_to_object_under_cursor (mouseEvent)
def draftguitools.gui_tool_utils.set_working_plane_to_selected_object ()
def draftguitools.gui_tool_utils.get_support (mouseEvent=None)
def draftguitools.gui_tool_utils.redraw_3d_view ()
Variables
draftguitools.gui_arcs.Draft_Arc_3Points
draftguitools.gui_clone.Draft_Clone
draftguitools.gui_dimension_ops.Draft_FlipDimension
draftguitools.gui_edit.COLORS
draftguitools.gui_facebinders.Draft_Facebinder
draftguitools.gui_groups.Draft_AddConstruction
draftguitools.gui_groups.Draft_AddNamedGroup
draftguitools.gui_hyperlink.translate
draftguitools.gui_labels.Draft_Label
draftguitools.gui_lineslope.Draft_Slope
draftguitools.gui_setstyle.translate
draftguitools.gui_setstyle.PRESETPATH
draftguitools.gui_snapper.UNSNAPPABLES
draftguitools.gui_tool_utils.MODS
draftguitools.gui_tool_utils.formatUnit
draftguitools.gui_tool_utils.selectObject
draftguitools.gui_tool_utils.hasMod
draftguitools.gui_tool_utils.setMod
draftguitools.gui_tool_utils.getPoint
draftguitools.gui_tool_utils.setWorkingPlaneToObjectUnderCursor
draftguitools.gui_tool_utils.setWorkingPlaneToSelectedObject
draftguitools.gui_tool_utils.getSupport
draftguitools.gui_tool_utils.redraw3DView
Detailed Description
Modules that define the workbench GuiCommands to perform actions.
Function Documentation
format_unit()
def draftguitools.gui_tool_utils.format_unit (exp, unit = "mm")
Return a formatting string to set a number to the correct unit.
Definition at line 61 of file gui_tool_utils.py.
get_mod_alt_key()
def draftguitools.gui_tool_utils.get_mod_alt_key ()
Definition at line 57 of file gui_tool_utils.py.
get_mod_constrain_key()
def draftguitools.gui_tool_utils.get_mod_constrain_key ()
Definition at line 49 of file gui_tool_utils.py.
Referenced by draftguitools.gui_tool_utils.get_point().
get_mod_snap_key()
def draftguitools.gui_tool_utils.get_mod_snap_key ()
Definition at line 53 of file gui_tool_utils.py.
Referenced by draftguitools.gui_tool_utils.get_point().
get_point()
def draftguitools.gui_tool_utils.get_point (target, args, noTracker = False)
Return a constrained 3D point and its original point.
It is used by the Draft tools.
Parameters
----------
target: object (class)
    The target object with a `node` attribute. If this is present,
    return the last node, otherwise return `None`.
    In the Draft tools, `target` is essentially the same class
    of the Gui command, that is, `self`. Therefore, this method
    probably makes more sense as a class method.
args: Coin event
    The Coin event received from the 3D view.
noTracker: bool, optional
    It defaults to `False`.
    If it is `True`, the tracking line will not be displayed.
Returns
-------
CoinPoint, Base::Vector3, str
    It returns a tuple with some information.
    The first is the Coin point returned by `Snapper.snap`
    or by the `ActiveView`; the second is that same point
    turned into an `App.Vector`,
    and the third is some information of the point
    returned by the `Snapper` or by the `ActiveView`.
Definition at line 159 of file gui_tool_utils.py.
References draftguitools.gui_tool_utils.get_mod_constrain_key(), draftguitools.gui_tool_utils.get_mod_snap_key(), WorkingPlane.get_working_plane(), and draftguitools.gui_tool_utils.has_mod().
get_support()
def draftguitools.gui_tool_utils.get_support (mouseEvent = None)
"Align the working plane to a preselected face or the face under the cursor.
The working plane is only aligned if it is `'auto'`.
Parameters
----------
mouseEvent: Coin event, optional
    Defaults to `None`.
    Coin mouse event.
Returns
-------
App::DocumentObject or None
    The parent object the face belongs to, if alignment occurred, or None.
Definition at line 315 of file gui_tool_utils.py.
References draftguitools.gui_tool_utils.set_working_plane_to_object_under_cursor(), and draftguitools.gui_tool_utils.set_working_plane_to_selected_object().
getColorIcon()
def draftguitools.gui_layers.getColorIcon (color)
Definition at line 47 of file gui_layers.py.
Referenced by draftguitools.gui_layers.LayerManager.addItem(), and draftguitools.gui_layers.Layers_Delegate.setModelData().
has_mod()
def draftguitools.gui_tool_utils.has_mod (args, mod)
Check if args has a specific modifier.
Parameters
----------
args: Coin event
    The Coin event received from the 3D view.
mod: str
    A string indicating the modifier, either `'shift'`, `'ctrl'`,
    or `'alt'`.
Returns
-------
bool
    It returns `args["ShiftDown"]`, `args["CtrlDown"]`,
    or `args["AltDown"]`, depending on the passed value of `mod`.
Definition at line 102 of file gui_tool_utils.py.
Referenced by draftguitools.gui_tool_utils.get_point().
moveToGroup()
def draftguitools.gui_groups.moveToGroup (group)
Place the selected objects in the chosen group.
Definition at line 139 of file gui_groups.py.
References nativeifc.ifc_tools.recompute().
Referenced by draftguitools.gui_groups.Ui_AddNamedGroup.accept(), and draftguitools.gui_groups.AddToGroup.proceed().
QT_TRANSLATE_NOOP() [1/2]
def draftguitools.gui_hyperlink.QT_TRANSLATE_NOOP (ctx, txt)
Definition at line 41 of file gui_hyperlink.py.
Referenced by draftguitools.gui_hyperlink.Draft_Hyperlink.GetResources().
QT_TRANSLATE_NOOP() [2/2]
def draftguitools.gui_setstyle.QT_TRANSLATE_NOOP (ctx, txt)
Definition at line 43 of file gui_setstyle.py.
Referenced by draftguitools.gui_setstyle.Draft_SetStyle.GetResources().
redraw_3d_view()
def draftguitools.gui_tool_utils.redraw_3d_view ()
Force a redraw of 3D view or do nothing if it fails.
Definition at line 339 of file gui_tool_utils.py.
select_object()
def draftguitools.gui_tool_utils.select_object (arg)
Handle the selection of objects depending on buttons pressed.
This is a scene event handler, to be called from the Draft tools
when they need to select an object.
::
    self.call = self.view.addEventCallback("SoEvent", select_object)
Parameters
----------
arg: Coin event
    The Coin event received from the 3D view.
    If it is of type Keyboard and the `ESCAPE` key, it runs the `finish`
    method of the active command.
    If Ctrl key is pressed, multiple selection is enabled until the
    button is released.
    Then it runs the `proceed` method of the active command
    to continue with the command's logic.
Definition at line 69 of file gui_tool_utils.py.
set_mod()
def draftguitools.gui_tool_utils.set_mod (args, mod, state)
Set a specific modifier state in args.
Parameters
----------
args: Coin event
    The Coin event received from the 3D view.
mod: str
    A string indicating the modifier, either `'shift'`, `'ctrl'`,
    or `'alt'`.
state: bool
    The boolean value of `state` is assigned to `args["ShiftDown"]`,
    `args["CtrlDown"]`, or `args["AltDown"]`
    depending on `mod`.
Definition at line 131 of file gui_tool_utils.py.
set_working_plane_to_object_under_cursor()
def draftguitools.gui_tool_utils.set_working_plane_to_object_under_cursor (mouseEvent)
Align the working plane to the face under the cursor.
The working plane is only aligned if it is `'auto'`.
Parameters
----------
mouseEvent: Coin event
    Coin mouse event.
Returns
-------
App::DocumentObject or None
    The parent object the face belongs to, if alignment occurred, or None.
Definition at line 234 of file gui_tool_utils.py.
References WorkingPlane.get_working_plane().
Referenced by draftguitools.gui_tool_utils.get_support().
set_working_plane_to_selected_object()
def draftguitools.gui_tool_utils.set_working_plane_to_selected_object ()
Align the working plane to a preselected face.
The working plane is only aligned if it is `'auto'`.
Returns
-------
App::DocumentObject or None
    The parent object the face belongs to, if alignment occurred, or None.
Definition at line 280 of file gui_tool_utils.py.
References WorkingPlane.get_working_plane().
Referenced by draftguitools.gui_tool_utils.get_support().
Variable Documentation
COLORS
draftguitools.gui_edit.COLORS
Definition at line 56 of file gui_edit.py.
Draft_AddConstruction
draftguitools.gui_groups.Draft_AddConstruction
Definition at line 342 of file gui_groups.py.
Draft_AddNamedGroup
draftguitools.gui_groups.Draft_AddNamedGroup
Definition at line 369 of file gui_groups.py.
Draft_Arc_3Points
draftguitools.gui_arcs.Draft_Arc_3Points
Definition at line 602 of file gui_arcs.py.
Draft_Clone
draftguitools.gui_clone.Draft_Clone
Definition at line 123 of file gui_clone.py.
Draft_Facebinder
draftguitools.gui_facebinders.Draft_Facebinder
Definition at line 91 of file gui_facebinders.py.
Draft_FlipDimension
draftguitools.gui_dimension_ops.Draft_FlipDimension
Definition at line 82 of file gui_dimension_ops.py.
Draft_Label
draftguitools.gui_labels.Draft_Label
Definition at line 230 of file gui_labels.py.
Draft_Slope
draftguitools.gui_lineslope.Draft_Slope
Definition at line 147 of file gui_lineslope.py.
formatUnit
draftguitools.gui_tool_utils.formatUnit
Definition at line 66 of file gui_tool_utils.py.
getPoint
draftguitools.gui_tool_utils.getPoint
Definition at line 231 of file gui_tool_utils.py.
Referenced by draftguitools.gui_trackers.PlaneTracker.__init__(), Sketcher::SketchObject.addCopy(), Commands.SphereCreator.create(), Sketcher::SketchObject.deriveConstraintsForPieces(), draftguitools.gui_stretch.Stretch.doStretch(), Sketcher::SketchObject.fillet(), Sketcher::SketchObject.generateId(), Path.Op.SurfaceSupport.PathGeometryGenerator.generatePathGeometry(), Sketcher::SketchObject.getEdge(), App::LocalCoordinateSystem.getOrigin(), Sketcher::GeoListModel< T >.getPoint(), Sketcher::SketchObject.getPoint(), Points::PointKernel.getPoints(), Sketcher::SketchObject.getSubObject(), Sketcher::SketchObject.getSymmetric(), Part::Geom2dPoint.Save(), Sketcher::SketchObject.transferFilletConstraints(), Sketcher::SketchObject.trim(), and Sketcher::SketchObject.updateGeoHistory().
getSupport
draftguitools.gui_tool_utils.getSupport
Definition at line 336 of file gui_tool_utils.py.
Referenced by FC_LOG_LEVEL_INIT().
hasMod
draftguitools.gui_tool_utils.hasMod
Definition at line 128 of file gui_tool_utils.py.
MODS
draftguitools.gui_tool_utils.MODS
Definition at line 46 of file gui_tool_utils.py.
PRESETPATH
draftguitools.gui_setstyle.PRESETPATH
Definition at line 51 of file gui_setstyle.py.
redraw3DView
draftguitools.gui_tool_utils.redraw3DView
Definition at line 347 of file gui_tool_utils.py.
selectObject
draftguitools.gui_tool_utils.selectObject
Definition at line 99 of file gui_tool_utils.py.
setMod
draftguitools.gui_tool_utils.setMod
Definition at line 156 of file gui_tool_utils.py.
setWorkingPlaneToObjectUnderCursor
draftguitools.gui_tool_utils.setWorkingPlaneToObjectUnderCursor
Definition at line 277 of file gui_tool_utils.py.
setWorkingPlaneToSelectedObject
draftguitools.gui_tool_utils.setWorkingPlaneToSelectedObject
Definition at line 312 of file gui_tool_utils.py.
translate [1/2]
draftguitools.gui_hyperlink.translate
Definition at line 43 of file gui_hyperlink.py.
translate [2/2]
draftguitools.gui_setstyle.translate
Definition at line 45 of file gui_setstyle.py.
UNSNAPPABLES
draftguitools.gui_snapper.UNSNAPPABLES
Definition at line 63 of file gui_snapper.py.