FreeCAD: Expression.cpp File Reference
Expression.cpp File Reference
#include "PreCompiled.h"
#include <boost/algorithm/string/predicate.hpp>
#include <boost/math/special_functions/round.hpp>
#include <boost/math/special_functions/trunc.hpp>
#include <sstream>
#include <stack>
#include <string>
#include <App/Application.h>
#include <App/DocumentObject.h>
#include <App/ObjectIdentifier.h>
#include <App/PropertyUnits.h>
#include <Base/Interpreter.h>
#include <Base/MatrixPy.h>
#include <Base/PlacementPy.h>
#include <Base/QuantityPy.h>
#include <Base/RotationPy.h>
#include <Base/VectorPy.h>
#include "ExpressionParser.h"
#include "ExpressionParser.tab.c"
#include "lex.ExpressionParser.c"
Classes
struct PyObjectWrapper
class GetIdentifiersExpressionVisitor
class AdjustLinksExpressionVisitor
class ImportSubNamesExpressionVisitor
class UpdateLabelExpressionVisitor
class ReplaceObjectExpressionVisitor
struct HiddenReference
class Collector
class SumCollector
class AverageCollector
class StdDevCollector
class CountCollector
class MinCollector
class MaxCollector
class App::ExpressionParser::StringBufferCleaner
Namespaces
App
a class to assist with exporting sketches to dxf
App::ExpressionParser
Macros
#define M_PI 3.14159265358979323846
#define M_E 2.71828182845904523536
#define DOUBLE_MAX 1.7976931348623157E+308 /* max decimal value of a "double"*/
#define DOUBLE_MIN 2.2250738585072014E-308 /* min decimal value of a "double"*/
#define __EXPR_THROW(_e, _msg, _expr)
#define _EXPR_THROW(_msg, _expr) __EXPR_THROW(ExpressionError,_msg,_expr)
#define __EXPR_SET_MSG(_e, _msg, _expr)
#define _EXPR_RETHROW(_e, _msg, _expr)
#define _EXPR_PY_THROW(_msg, _expr)
#define EXPR_PY_THROW(_expr) _EXPR_PY_THROW("", _expr)
#define EXPR_THROW(_msg) _EXPR_THROW(_msg, this)
#define ARGUMENT_THROW(_msg) EXPR_THROW("Invalid number of arguments: " _msg)
#define RUNTIME_THROW(_msg) __EXPR_THROW(Base::RuntimeError, _msg, static_cast<Expression*>(nullptr))
#define TYPE_THROW(_msg) __EXPR_THROW(Base::TypeError, _msg, static_cast<Expression*>(nullptr))
#define PARSER_THROW(_msg) __EXPR_THROW(Base::ParserError, _msg, static_cast<Expression*>(nullptr))
#define PY_THROW(_msg) __EXPR_THROW(Py::RuntimeError, _msg, static_cast<Expression*>(nullptr))
#define RICH_COMPARE(_op, _pyop)
#define _BINARY_OP(_pyop)
#define BINARY_OP(_op, _pyop)
#define yylex ExpressionParserlex
#define YYTOKENTYPE
Functions
static std::ostream & operator<< (std::ostream &os, const App::Expression *expr)
template<typename T >
void copy_vector (T &dst, const T &src)
static bool is_type (const App::any &value, const std::type_info &t)
template<class T >
static const T & cast (const App::any &value)
template<class T >
static T & cast (App::any &value)
template<class T >
static T && cast (App::any &&value)
std::string unquote (const std::string &input)
template<class T >
static bool essentiallyEqual (T a, T b)
template<class T >
bool essentiallyZero (T a)
template<>
bool essentiallyZero (double a)
template<>
bool essentiallyZero (float a)
template<class T >
static bool definitelyGreaterThan (T a, T b)
template<class T >
static bool definitelyLessThan (T a, T b)
static int essentiallyInteger (double a, long &l, int &i)
static bool essentiallyInteger (double a, long &l)
static PyObjectWrapper::Pointer pyObjectWrap (PyObject *obj)
static bool isAnyPyObject (const App::any &value)
static Py::Object __pyObjectFromAny (const App::any &value)
static Py::Object _pyObjectFromAny (const App::any &value, const Expression *e)
Py::Object App::pyObjectFromAny (const App::any &value)
App::any App::pyObjectToAny (Py::Object value, bool check)
bool App::pyToQuantity (Quantity &q, const Py::Object &pyobj)
static Quantity App::pyToQuantity (const Py::Object &pyobj, const Expression *e, const char *msg=nullptr)
Py::Object App::pyFromQuantity (const Quantity &quantity)
Quantity App::anyToQuantity (const App::any &value, const char *msg)
static bool App::anyToLong (long &res, const App::any &value)
static bool App::anyToDouble (double &res, const App::any &value)
bool App::isAnyEqual (const App::any &v1, const App::any &v2)
Expression * App::expressionFromPy (const DocumentObject *owner, const Py::Object &value)
static Py::Object calc (const Expression *expr, int op, const Expression *left, const Expression *right, bool inplace)
bool App::ExpressionParser::isModuleImported (PyObject *module)
void App::ExpressionParser::ExpressionParser_yyerror (const char *errorinfo)
double App::ExpressionParser::num_change (char *yytext, char dez_delim, char grp_delim)
int App::ExpressionParser::ExpressionParserlex ()
static void App::ExpressionParser::initParser (const App::DocumentObject *owner)
std::vector< std::tuple< int, int, std::string > > App::ExpressionParser::tokenize (const std::string &str)
Variables
static int _HiddenReference
static Base::XMLReader * _Reader = nullptr
static Expression * App::ExpressionParser::ScanResult = nullptr
static const App::DocumentObject * App::ExpressionParser::DocumentObject = nullptr
static bool App::ExpressionParser::unitExpression = false
static bool App::ExpressionParser::valueExpression = false
static std::stack< std::string > App::ExpressionParser::labels
static std::map< std::string, FunctionExpression::Function > App::ExpressionParser::registered_functions
static int App::ExpressionParser::last_column
static int App::ExpressionParser::column
Macro Definition Documentation
__EXPR_SET_MSG
#define __EXPR_SET_MSG (_e, _msg, _expr)
Value:
    do {\
    std::ostringstream ss;\
    ss << _msg << _e.what() << (_expr);\
    _e.setMessage(ss.str());\
}while(0)
Definition at line 92 of file Expression.cpp.
__EXPR_THROW
#define __EXPR_THROW (_e, _msg, _expr)
Value:
    do {\
    std::ostringstream ss;\
    ss << _msg << (_expr);\
    throw _e(ss.str().c_str());\
}while(0)
Definition at line 84 of file Expression.cpp.
_BINARY_OP
#define _BINARY_OP (_pyop)
Value:
        res = inplace?PyNumber_InPlace##_pyop(l.ptr(),r.ptr()):\
                       PyNumber_##_pyop(l.ptr(),r.ptr());\
        if(!res) EXPR_PY_THROW(expr);\
        return Py::asObject(res);
_EXPR_PY_THROW
#define _EXPR_PY_THROW (_msg, _expr)
Value:
    do {\
    Base::PyException _e;\
    __EXPR_SET_MSG(_e,_msg,_expr);\
    _e.raiseException();\
}while(0)
Definition at line 103 of file Expression.cpp.
_EXPR_RETHROW
#define _EXPR_RETHROW (_e, _msg, _expr)
Value:
    do {\
    __EXPR_SET_MSG(_e,_msg,_expr);\
    throw;\
}while(0)
Definition at line 98 of file Expression.cpp.
_EXPR_THROW
#define _EXPR_THROW (_msg, _expr) __EXPR_THROW(ExpressionError,_msg,_expr)
Definition at line 90 of file Expression.cpp.
ARGUMENT_THROW
#define ARGUMENT_THROW (_msg) EXPR_THROW("Invalid number of arguments: " _msg)
Definition at line 113 of file Expression.cpp.
BINARY_OP
#define BINARY_OP (_op, _pyop)
Value:
    case OperatorExpression::_op: {\
        PyObject *res;\
        _BINARY_OP(_pyop);\
    }
DOUBLE_MAX
#define DOUBLE_MAX 1.7976931348623157E+308 /* max decimal value of a "double"*/
Definition at line 72 of file Expression.cpp.
DOUBLE_MIN
#define DOUBLE_MIN 2.2250738585072014E-308 /* min decimal value of a "double"*/
Definition at line 75 of file Expression.cpp.
EXPR_PY_THROW
#define EXPR_PY_THROW (_expr) _EXPR_PY_THROW("", _expr)
Definition at line 109 of file Expression.cpp.
EXPR_THROW
#define EXPR_THROW (_msg) _EXPR_THROW(_msg, this)
Definition at line 111 of file Expression.cpp.
M_E
#define M_E 2.71828182845904523536
Definition at line 69 of file Expression.cpp.
M_PI
#define M_PI 3.14159265358979323846
Definition at line 66 of file Expression.cpp.
PARSER_THROW
#define PARSER_THROW (_msg) __EXPR_THROW(Base::ParserError, _msg, static_cast<Expression*>(nullptr))
Definition at line 119 of file Expression.cpp.
PY_THROW
#define PY_THROW (_msg) __EXPR_THROW(Py::RuntimeError, _msg, static_cast<Expression*>(nullptr))
Definition at line 121 of file Expression.cpp.
RICH_COMPARE
#define RICH_COMPARE (_op, _pyop)
Value:
    case OperatorExpression::_op: {\
        int res = PyObject_RichCompareBool(l.ptr(),r.ptr(),Py_##_pyop);\
        if(res<0) EXPR_PY_THROW(expr);\
        return Py::Boolean(!!res);\
    }
RUNTIME_THROW
#define RUNTIME_THROW (_msg) __EXPR_THROW(Base::RuntimeError, _msg, static_cast<Expression*>(nullptr))
Definition at line 115 of file Expression.cpp.
TYPE_THROW
#define TYPE_THROW (_msg) __EXPR_THROW(Base::TypeError, _msg, static_cast<Expression*>(nullptr))
Definition at line 117 of file Expression.cpp.
yylex
#define yylex ExpressionParserlex
Definition at line 3546 of file Expression.cpp.
YYTOKENTYPE
#define YYTOKENTYPE
Definition at line 3560 of file Expression.cpp.
Function Documentation
__pyObjectFromAny()
static Py::Object __pyObjectFromAny (const App::any & value) inline static
Definition at line 415 of file Expression.cpp.
Referenced by _pyObjectFromAny(), and App::isAnyEqual().
_pyObjectFromAny()
static Py::Object _pyObjectFromAny (const App::any & value, const Expression * e) static
Definition at line 419 of file Expression.cpp.
References __pyObjectFromAny(), _EXPR_THROW, SCL.SimpleDataTypes::e, is_type(), isAnyPyObject(), src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::Quantity, and src.Mod.Test.testmakeWireString::String.
Referenced by App::pyObjectFromAny().
calc()
static Py::Object calc (const Expression * expr, int op, const Expression * left, const Expression * right, bool inplace) static
Definition at line 1367 of file Expression.cpp.
References __EXPR_THROW, _BINARY_OP, KDL::Add(), App::OperatorExpression::ADD, BINARY_OP, EQ, EXPR_PY_THROW, App::Expression::getPyValue(), GT, GTE, RobotExample::l, LT, LTE, App::OperatorExpression::MOD, KDL::Multiply(), App::OperatorExpression::NEG, NEQ, Py::new_reference_to(), App::OperatorExpression::POS, App::OperatorExpression::POW, RICH_COMPARE, SUB, KDL::Subtract(), and UNIT.
Referenced by App::OperatorExpression::_getPyValue().
cast() [1/3]
template<class T > static T&& cast (App::any && value) inline static
Definition at line 177 of file Expression.cpp.
References Path.Post.scripts.opensbp_post::move().
cast() [2/3]
template<class T > static T& cast (App::any & value) inline static
Definition at line 168 of file Expression.cpp.
cast() [3/3]
template<class T > static const T& cast (const App::any & value) inline static
Definition at line 159 of file Expression.cpp.
Referenced by TechDraw::DrawLeaderLine::getBaseView(), and makeFace().
copy_vector()
template<typename T > void copy_vector (T & dst, const T & src)
Definition at line 132 of file Expression.cpp.
References toolbit-attributes::s.
Referenced by App::Expression::copy().
definitelyGreaterThan()
template<class T > static bool definitelyGreaterThan (T a, T b) inline static
Definition at line 322 of file Expression.cpp.
References a, SCL.SimpleDataTypes::b, and KDL::epsilon.
definitelyLessThan()
template<class T > static bool definitelyLessThan (T a, T b) inline static
Definition at line 329 of file Expression.cpp.
References a, SCL.SimpleDataTypes::b, and KDL::epsilon.
essentiallyEqual()
template<class T > static bool essentiallyEqual (T a, T b) inline static
Definition at line 300 of file Expression.cpp.
References a, SCL.SimpleDataTypes::b, and KDL::epsilon.
Referenced by App::VariableExpression::addComponent(), essentiallyZero(), App::isAnyEqual(), and App::ExpressionParser::parseUnit().
essentiallyInteger() [1/2]
static bool essentiallyInteger (double a, long & l) inline static
Definition at line 362 of file Expression.cpp.
References a, and RobotExample::l.
essentiallyInteger() [2/2]
static int essentiallyInteger (double a, long & l, int & i) inline static
Definition at line 335 of file Expression.cpp.
References a, SplineSurface::i, and RobotExample::l.
Referenced by App::VariableExpression::addComponent(), App::NumberExpression::isInteger(), and App::pyFromQuantity().
essentiallyZero() [1/3]
template<> bool essentiallyZero (double a) inline
Definition at line 312 of file Expression.cpp.
References a, and essentiallyEqual().
essentiallyZero() [2/3]
template<> bool essentiallyZero (float a) inline
Definition at line 317 of file Expression.cpp.
References a, essentiallyEqual(), and SCL.SimpleDataTypes::f.
essentiallyZero() [3/3]
template<class T > bool essentiallyZero (T a) inline
Definition at line 307 of file Expression.cpp.
References a.
is_type()
static bool is_type (const App::any & value, const std::type_info & t) inline static
Definition at line 150 of file Expression.cpp.
References InitGui::t.
Referenced by _pyObjectFromAny(), App::anyToDouble(), App::anyToLong(), App::anyToQuantity(), App::isAnyEqual(), and isAnyPyObject().
isAnyPyObject()
static bool isAnyPyObject (const App::any & value) inline static
Definition at line 411 of file Expression.cpp.
References is_type().
Referenced by _pyObjectFromAny(), and App::isAnyEqual().
operator<<()
static std::ostream& operator<< (std::ostream & os, const App::Expression * expr) inline static
Definition at line 123 of file Expression.cpp.
References App::Expression::toString().
pyObjectWrap()
static PyObjectWrapper::Pointer pyObjectWrap (PyObject * obj) inline static
Definition at line 407 of file Expression.cpp.
Referenced by App::pyObjectToAny().
unquote()
std::string unquote (const std::string & input)
Definition at line 185 of file Expression.cpp.
Variable Documentation
_HiddenReference
int _HiddenReference static
Definition at line 1701 of file Expression.cpp.
Referenced by HiddenReference::check(), HiddenReference::HiddenReference(), HiddenReference::isHidden(), and HiddenReference::~HiddenReference().
_Reader
Base::XMLReader* _Reader = nullptr static
Definition at line 3473 of file Expression.cpp.
Referenced by App::ExpressionParser::ExpressionImporter::ExpressionImporter(), App::ExpressionParser::ExpressionImporter::reader(), and App::ExpressionParser::ExpressionImporter::~ExpressionImporter().