FreeCAD: SpreadsheetGui::SpreadsheetDelegate Class Reference
SpreadsheetGui::SpreadsheetDelegate Class Reference
#include <SpreadsheetDelegate.h>
Signals
void finishedWithKey (int key, Qt::KeyboardModifiers modifiers)
Public Member Functions
SpreadsheetDelegate (Spreadsheet::Sheet *sheet, QWidget *parent=nullptr)
QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &, const QModelIndex &index) const override
void setEditorData (QWidget *editor, const QModelIndex &index) const override
void setModelData (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const override
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const override
Detailed Description
Definition at line 38 of file SpreadsheetDelegate.h.
Constructor & Destructor Documentation
SpreadsheetDelegate()
SpreadsheetDelegate::SpreadsheetDelegate (Spreadsheet::Sheet * sheet, QWidget * parent = nullptr) explicit
Definition at line 45 of file SpreadsheetDelegate.cpp.
Member Function Documentation
createEditor()
QWidget * SpreadsheetDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & , const QModelIndex & index) const override
Definition at line 50 of file SpreadsheetDelegate.cpp.
References draftgeoutils.intersections::connect(), Path.Post.Utils::editor(), FC_ERR, SpreadsheetGui::LineEdit::finishedWithKey(), Spreadsheet::Sheet::getCellBinding(), Init::parent, and App::CellAddress::toString().
finishedWithKey
void SpreadsheetGui::SpreadsheetDelegate::finishedWithKey (int key, Qt::KeyboardModifiers modifiers) signal
Referenced by SpreadsheetGui::SheetView::SheetView().
paint()
void SpreadsheetDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const override
Definition at line 128 of file SpreadsheetDelegate.cpp.
References drawBorder(), Spreadsheet::Sheet::getCellBindingBorder(), and Spreadsheet::Sheet::getCopyOrCutBorder().
setEditorData()
void SpreadsheetDelegate::setEditorData (QWidget * editor, const QModelIndex & index) const override
Definition at line 70 of file SpreadsheetDelegate.cpp.
References Path.Post.Utils::editor().
setModelData()
void SpreadsheetDelegate::setModelData (QWidget * editor, QAbstractItemModel * model, const QModelIndex & index) const override
Definition at line 79 of file SpreadsheetDelegate.cpp.
References Path.Post.Utils::editor().
The documentation for this class was generated from the following files:
SpreadsheetDelegate.h
SpreadsheetDelegate.cpp