FreeCAD: ifc2x3.ifcstructuralloadtemperature Class Reference
ifc2x3.ifcstructuralloadtemperature Class Reference
Public Member Functions
def __init__ (self, inherited0__name, deltat_constant, deltat_y, deltat_z)
def deltat_constant ()
def deltat_y ()
def deltat_z ()
Public Member Functions inherited from ifc2x3.ifcstructuralloadstatic
def __init__ (self, inherited0__name)
Public Member Functions inherited from ifc2x3.ifcstructuralload
def name ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
deltat_constant
deltat_y
deltat_z
Public Attributes inherited from ifc2x3.ifcstructuralload
name
Detailed Description
Entity ifcstructuralloadtemperature definition.
:param deltat_constant
:type deltat_constant:ifcthermodynamictemperaturemeasure
:param deltat_y
:type deltat_y:ifcthermodynamictemperaturemeasure
:param deltat_z
:type deltat_z:ifcthermodynamictemperaturemeasure
Definition at line 29460 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcstructuralloadtemperature.__init__ (self, inherited0__name, deltat_constant, deltat_y, deltat_z)
Definition at line 29472 of file ifc2x3.py.
Member Function Documentation
deltat_constant()
def ifc2x3.ifcstructuralloadtemperature.deltat_constant ()
Definition at line 29479 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadtemperature._deltat_constant, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadtemperature.deltat_constant.
deltat_y()
def ifc2x3.ifcstructuralloadtemperature.deltat_y ()
Definition at line 29493 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadtemperature._deltat_y, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadtemperature.deltat_y.
deltat_z()
def ifc2x3.ifcstructuralloadtemperature.deltat_z ()
Definition at line 29507 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadtemperature._deltat_z, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadtemperature.deltat_z.
Member Data Documentation
deltat_constant
ifc2x3.ifcstructuralloadtemperature.deltat_constant
Definition at line 29474 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadtemperature.deltat_constant().
deltat_y
ifc2x3.ifcstructuralloadtemperature.deltat_y
Definition at line 29475 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadtemperature.deltat_y().
deltat_z
ifc2x3.ifcstructuralloadtemperature.deltat_z
Definition at line 29476 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadtemperature.deltat_z().
The documentation for this class was generated from the following file:
ifc2x3.py