FreeCAD: Gui::TreeWidget Class Reference
Gui::TreeWidget Class Reference
#include <Tree.h>
Classes
struct SelInfo
Public Member Functions
TreeWidget (const char *name, QWidget *parent=nullptr)
~TreeWidget () override
void selectAllInstances (const ViewProviderDocumentObject &vpd)
void selectLinkedObject (App::DocumentObject *linked)
void selectAllLinks (App::DocumentObject *obj)
void expandSelectedItems (TreeItemMode mode)
int iconHeight () const
void setIconHeight (int height)
int itemSpacing () const
void setItemSpacing (int)
bool eventFilter (QObject *, QEvent *ev) override
void markItem (const App::DocumentObject *Obj, bool mark)
void syncView (ViewProviderDocumentObject *vp)
void selectAll () override
const char * getTreeName () const
DocumentItem * getDocumentItem (const Gui::Document *) const
void startDragging ()
void resetItemSearch ()
void startItemSearch (QLineEdit *)
void itemSearch (const QString &text, bool select)
QList< QTreeWidgetItem * > childrenOfItem (const QTreeWidgetItem &item) const
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Static Public Member Functions
static void setupResizableColumn (TreeWidget *tree=nullptr)
static void scrollItemToTop ()
static int iconSize ()
static std::vector< SelInfo > getSelection (App::Document *doc=nullptr)
static TreeWidget * instance ()
static void updateStatus (bool delay=true)
static bool isObjectShowable (App::DocumentObject *obj)
static void checkTopParent (App::DocumentObject *&obj, std::string &subname)
static Gui::Document * selectedDocument ()
static void synchronizeSelectionCheckBoxes ()
static void updateVisibilityIcons ()
Static Public Attributes
static const int DocumentType = 1000
static const int ObjectType = 1001
Protected Member Functions
void onSelectionChanged (const SelectionChanges &msg) override
Observer message from the Selection.
void contextMenuEvent (QContextMenuEvent *e) override
void drawRow (QPainter *, const QStyleOptionViewItem &, const QModelIndex &) const override
Drag and drop
class DocumentItem
class DocumentObjectItem
class TreeParams
class TreeWidgetItemDelegate
void startDrag (Qt::DropActions supportedActions) override
bool dropMimeData (QTreeWidgetItem *parent, int index, const QMimeData *data, Qt::DropAction action) override
Qt::DropActions supportedDropActions () const override
void dragEnterEvent (QDragEnterEvent *event) override
void dragLeaveEvent (QDragLeaveEvent *event) override
void dragMoveEvent (QDragMoveEvent *event) override
void dropEvent (QDropEvent *event) override
bool event (QEvent *e) override
void keyPressEvent (QKeyEvent *event) override
void mousePressEvent (QMouseEvent *event) override
void mouseDoubleClickEvent (QMouseEvent *event) override
void showEvent (QShowEvent *ev) override
void hideEvent (QHideEvent *ev) override
void leaveEvent (QEvent *event) override
void onCreateGroup ()
void onRelabelObject ()
void onActivateDocument (QAction *)
void onStartEditing ()
void onFinishEditing ()
void onSelectDependents ()
void onSkipRecompute (bool on)
void onAllowPartialRecompute (bool on)
void onReloadDoc ()
void onCloseDoc ()
void onMarkRecompute ()
void onRecomputeObject ()
void onPreSelectTimer ()
void onSelectTimer ()
void onShowHidden ()
void onToggleVisibilityInTree ()
void onSearchObjects ()
void emitSearchObjects ()
Detailed Description
Tree view that allows drag & drop of document objects.
Author
Werner Mayer
Definition at line 58 of file Tree.h.
Constructor & Destructor Documentation
TreeWidget()
TreeWidget::TreeWidget (const char * name, QWidget * parent = nullptr) explicit
Definition at line 607 of file Tree.cpp.
References _LastSelectedTreeWidget, draftgeoutils.faces::bind(), Gui::BitmapFactory(), draftgeoutils.intersections::connect(), Gui::TreeParams::getHideColumn(), Gui::TreeParams::getHideInternalNames(), Gui::Application::Instance, Gui::NoResolve, onAllowPartialRecompute(), onCloseDoc(), onCreateGroup(), onFinishEditing(), Gui::TreeParams::onFontSizeChanged(), onMarkRecompute(), onPreSelectTimer(), onRecomputeObject(), onRelabelObject(), onReloadDoc(), onSearchObjects(), onSelectDependents(), onSelectTimer(), onShowHidden(), onSkipRecompute(), onToggleVisibilityInTree(), Gui::TreeParams::setColumnSize1(), Gui::TreeParams::setColumnSize2(), Gui::TreeParams::setColumnSize3(), setupResizableColumn(), Gui::Application::signalActiveDocument, Gui::Application::signalChangedObject, Gui::Application::signalDeleteDocument, Gui::Application::signalNewDocument, Gui::Application::signalRelabelDocument, Gui::Application::signalRenameDocument, Gui::Application::signalShowHidden, and TreeWidgetItemDelegate.
~TreeWidget()
TreeWidget::~TreeWidget () override
Definition at line 753 of file Tree.cpp.
References _LastSelectedTreeWidget.
Member Function Documentation
checkTopParent()
void TreeWidget::checkTopParent (App::DocumentObject *& obj, std::string & subname) static
Definition at line 803 of file Tree.cpp.
References _DisableCheckTopParent, App::DocumentObject::getDocument(), Gui::Application::Instance, App::DocumentObject::isAttachedToDocument(), and Init::parent.
Referenced by Gui::SelectionSingleton::checkSelection().
childrenOfItem()
QList< QTreeWidgetItem * > TreeWidget::childrenOfItem (const QTreeWidgetItem & item) const
Definition at line 3530 of file Tree.cpp.
References SplineSurface::i, and femsolver.elmer.sifio::isValid().
Referenced by keyPressEvent().
contextMenuEvent()
void TreeWidget::contextMenuEvent (QContextMenuEvent * e) override protected
Definition at line 1003 of file Tree.cpp.
References Path.Post.scripts.dynapath_4060_post::action, App::Document::AllowPartialRecompute, draftgeoutils.intersections::connect(), Gui::Workbench::createLinkMenu(), toolbit-attributes::doc, DocumentType, SCL.SimpleDataTypes::e, FC_ERR, App::Application::getActiveDocument(), App::GetApplication(), ParameterGrp::GetBool(), Base::Persistence::getClassTypeId(), Gui::SelectionSingleton::getCompleteSelection(), App::Application::getDocuments(), Gui::MenuManager::getInstance(), App::Application::GetParameterGroupByPath(), Gui::Application::Instance, ObjectType, onActivateDocument(), onStartEditing(), App::Document::PartialDoc, RobotExample::pos, Gui::Selection(), ParameterGrp::SetBool(), Gui::MenuManager::setupContextMenu(), Gui::Application::setupContextMenu(), bimcommands.BimViews::show(), and App::Document::SkipRecompute.
dragEnterEvent()
void TreeWidget::dragEnterEvent (QDragEnterEvent * event) override protected
Definition at line 1852 of file Tree.cpp.
References event().
dragLeaveEvent()
void TreeWidget::dragLeaveEvent (QDragLeaveEvent * event) override protected
Definition at line 1857 of file Tree.cpp.
References event().
dragMoveEvent()
void TreeWidget::dragMoveEvent (QDragMoveEvent * event) override protected
Definition at line 1977 of file Tree.cpp.
References _DragEventFilter, Gui::ViewProviderDocumentObject::canDropObjectEx(), Gui::ViewProvider::canDropObjects(), DocumentType, SCL.SimpleDataTypes::e, event(), FC_ERR, App::DocumentObject::getFullName(), src.Mod.Test.testPathArray::items, leaveEvent(), ObjectType, Path.Post.scripts.refactored_centroid_post::str, and TREE_TRACE.
drawRow()
void TreeWidget::drawRow (QPainter * painter, const QStyleOptionViewItem & options, const QModelIndex & index) const override protected
Definition at line 2834 of file Tree.cpp.
dropEvent()
void TreeWidget::dropEvent (QDropEvent * event) override protected
Definition at line 2723 of file Tree.cpp.
References DocumentType, event(), Gui::Application::getDocument(), Gui::TreeParams::getRecomputeOnDrop(), Gui::TreeParams::getSyncView(), Gui::Application::Instance, src.Mod.Test.testPathArray::items, ObjectType, and Gui::Document::setActiveView().
dropMimeData()
bool TreeWidget::dropMimeData (QTreeWidgetItem * parent, int index, const QMimeData * data, Qt::DropAction action) override protected
Definition at line 1846 of file Tree.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and Init::parent.
emitSearchObjects
void Gui::TreeWidget::emitSearchObjects () signal
Referenced by onSearchObjects(), and Gui::TreePanel::TreePanel().
event()
bool TreeWidget::event (QEvent * e) override protected
Definition at line 1607 of file Tree.cpp.
References SCL.SimpleDataTypes::e.
Referenced by dragEnterEvent(), dragLeaveEvent(), dragMoveEvent(), dropEvent(), keyPressEvent(), leaveEvent(), mouseDoubleClickEvent(), and mousePressEvent().
eventFilter()
bool TreeWidget::eventFilter (QObject * , QEvent * ev) override
Definition at line 1612 of file Tree.cpp.
References RobotExample::pos.
expandSelectedItems()
void TreeWidget::expandSelectedItems (TreeItemMode mode)
Definition at line 3284 of file Tree.cpp.
References Gui::CollapseItem, Gui::ExpandItem, Gui::ExpandPath, Gui::SelectionObserver::isSelectionAttached(), src.Mod.Test.testPathArray::items, and Gui::ToggleItem.
Referenced by StdCmdTreeCollapse::activated(), and StdCmdTreeExpand::activated().
getDocumentItem()
DocumentItem * TreeWidget::getDocumentItem (const Gui::Document * doc) const
Definition at line 1395 of file Tree.cpp.
References toolbit-attributes::doc.
Referenced by Gui::DocumentObjectItem::getParentDocument(), itemSearch(), and selectLinkedObject().
getSelection()
std::vector< TreeWidget::SelInfo > TreeWidget::getSelection (App::Document * doc = nullptr) static
Definition at line 1497 of file Tree.cpp.
References toolbit-attributes::doc, FC_LOG, FC_WARN, App::DocumentObject::getDocument(), App::DocumentObject::getFullName(), App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), instance(), App::DocumentObject::isAttachedToDocument(), Gui::SelectionObserver::isSelectionAttached(), src.Mod.Test.testPathArray::items, Gui::DocumentObjectItem::object(), ObjectType, onSelectTimer(), and Init::parent.
Referenced by femguiutils.selection_widgets._Selector::setHelpText().
getTreeName()
const char * TreeWidget::getTreeName () const
Definition at line 767 of file Tree.cpp.
Referenced by Gui::DocumentItem::DocumentItem().
hideEvent()
void TreeWidget::hideEvent (QHideEvent * ev) override protected
Definition at line 1189 of file Tree.cpp.
iconHeight()
int TreeWidget::iconHeight () const
Definition at line 1424 of file Tree.cpp.
References treeIconSize().
iconSize()
int TreeWidget::iconSize () static
Definition at line 1442 of file Tree.cpp.
References defaultSize, instance(), KDL::max(), and treeIconSize().
Referenced by Gui::TreeWidgetItemDelegate::initStyleOption(), mousePressEvent(), and setIconHeight().
instance()
TreeWidget * TreeWidget::instance () static
Definition at line 1464 of file Tree.cpp.
References _LastSelectedTreeWidget.
Referenced by getSelection(), iconSize(), Gui::Document::RestoreDocFile(), and Gui::Document::SaveDocFile().
isObjectShowable()
bool TreeWidget::isObjectShowable (App::DocumentObject * obj) static
Definition at line 786 of file Tree.cpp.
References toolbit-attributes::doc, App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::Application::Instance, and App::DocumentObject::isAttachedToDocument().
Referenced by Gui::ViewProviderDocumentObject::show().
itemSearch()
void TreeWidget::itemSearch (const QString & text, bool select)
Definition at line 865 of file Tree.cpp.
References Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::clearSelection(), toolbit-attributes::doc, FC_LOG, FC_TRACE, getDocumentItem(), Gui::Application::Instance, replaceobj::objs, Init::parent, App::ObjectIdentifier::parse(), RobotExample::pos, resetItemSearch(), Path.Op.Gui.Selection::select(), Gui::Selection(), Gui::SelectionSingleton::selStackPush(), Gui::SelectionSingleton::setPreselect(), Gui::SelectionChanges::TreeView, and create_qrc::txt.
itemSpacing()
int Gui::TreeWidget::itemSpacing () const
keyPressEvent()
void TreeWidget::keyPressEvent (QKeyEvent * event) override protected
Definition at line 1642 of file Tree.cpp.
References childrenOfItem(), event(), and onSearchObjects().
leaveEvent()
void TreeWidget::leaveEvent (QEvent * event) override protected
Definition at line 3197 of file Tree.cpp.
References event(), Gui::TreeParams::getPreSelection(), Gui::SelectionSingleton::rmvPreselect(), and Gui::Selection().
Referenced by dragMoveEvent().
markItem()
void Gui::TreeWidget::markItem (const App::DocumentObject * Obj, bool mark)
mouseDoubleClickEvent()
void TreeWidget::mouseDoubleClickEvent (QMouseEvent * event) override protected
Definition at line 1760 of file Tree.cpp.
References toolbit-attributes::doc, DocumentType, Gui::ViewProvider::doubleClicked(), SCL.SimpleDataTypes::e, Gui::Application::editDocument(), event(), FC_ERR, Base::BaseClass::getClassTypeId(), Gui::ViewProviderDocumentObject::getObject(), Gui::Command::getObjectCmd(), Gui::ViewProviderDocumentObject::getTransactionText(), Gui::MacroManager::Gui, Gui::Application::Instance, Gui::Application::macroManager(), ObjectType, onReloadDoc(), App::Document::PartialDoc, and App::AutoTransaction::setEnable().
mousePressEvent()
void TreeWidget::mousePressEvent (QMouseEvent * event) override protected
Definition at line 1704 of file Tree.cpp.
References event(), App::DocumentObject::getNameInDocument(), App::PropertyBool::getValue(), iconSize(), isSelectionCheckBoxesEnabled(), isVisibilityIconEnabled(), ObjectType, Init::parent, App::PropertyBool::setValue(), and App::DocumentObject::Visibility.
onActivateDocument
void TreeWidget::onActivateDocument (QAction * active) protected slot
Definition at line 1593 of file Tree.cpp.
References toolbit-attributes::doc, Base::BaseClass::getClassTypeId(), Gui::Application::getDocument(), and Gui::Application::Instance.
Referenced by contextMenuEvent().
onAllowPartialRecompute
void TreeWidget::onAllowPartialRecompute (bool on) protected slot
Definition at line 1345 of file Tree.cpp.
References App::Document::AllowPartialRecompute, toolbit-attributes::doc, and DocumentType.
Referenced by TreeWidget().
onCloseDoc
void TreeWidget::onCloseDoc () protected slot
Definition at line 2868 of file Tree.cpp.
References toolbit-attributes::doc, Gui::Command::Doc, doCommand, DocumentType, SCL.SimpleDataTypes::e, FC_ERR, and Draft::gui.
Referenced by TreeWidget().
onCreateGroup
void TreeWidget::onCreateGroup () protected slot
Definition at line 1197 of file Tree.cpp.
References Gui::Command::App, toolbit-attributes::doc, DocumentType, App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), ObjectType, and runCommand.
Referenced by TreeWidget().
onFinishEditing
void TreeWidget::onFinishEditing () protected slot
Definition at line 1253 of file Tree.cpp.
References toolbit-attributes::doc, App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::Application::Instance, and ObjectType.
Referenced by TreeWidget().
onMarkRecompute
void TreeWidget::onMarkRecompute () protected slot
Definition at line 1355 of file Tree.cpp.
References toolbit-attributes::doc, DocumentType, App::DocumentObject::enforceRecompute(), src.Mod.Test.testPathArray::items, and ObjectType.
Referenced by TreeWidget().
onPreSelectTimer
void TreeWidget::onPreSelectTimer () protected slot
Definition at line 3206 of file Tree.cpp.
References App::DocumentObject::getNameInDocument(), Gui::TreeParams::getPreSelection(), ObjectType, Init::parent, RobotExample::pos, App::DocumentObject::redirectSubName(), Gui::Selection(), Gui::SelectionSingleton::setPreselect(), and Gui::SelectionChanges::TreeView.
Referenced by TreeWidget().
onRecomputeObject
void TreeWidget::onRecomputeObject () protected slot
Definition at line 1378 of file Tree.cpp.
References src.Mod.Test.testPathArray::items, ObjectType, and replaceobj::objs.
Referenced by TreeWidget().
onRelabelObject
void TreeWidget::onRelabelObject () protected slot
Definition at line 1223 of file Tree.cpp.
Referenced by TreeWidget().
onReloadDoc
void TreeWidget::onReloadDoc () protected slot
Definition at line 2852 of file Tree.cpp.
References toolbit-attributes::doc, DocumentType, App::GetApplication(), Gui::Application::Instance, Gui::Application::reopen(), App::Application::setActiveDocument(), and TestSpreadsheet::v.
Referenced by mouseDoubleClickEvent(), and TreeWidget().
onSearchObjects
void TreeWidget::onSearchObjects () protected slot
Definition at line 1588 of file Tree.cpp.
References emitSearchObjects().
Referenced by keyPressEvent(), and TreeWidget().
onSelectDependents
void TreeWidget::onSelectDependents () protected slot
Definition at line 1306 of file Tree.cpp.
References Gui::SelectionSingleton::addSelection(), toolbit-attributes::doc, DocumentType, src.Mod.Test.testPathArray::items, ObjectType, and Gui::Selection().
Referenced by TreeWidget().
onSelectionChanged()
void TreeWidget::onSelectionChanged (const SelectionChanges & msg) override protected virtual
Observer message from the Selection.
Implements Gui::SelectionObserver.
Definition at line 3576 of file Tree.cpp.
References Gui::SelectionChanges::AddSelection, Gui::SelectionChanges::ClrSelection, Gui::TreeParams::getSelectionTimeout(), Path.Op.Surface::msg, Gui::SelectionChanges::RmvSelection, and Gui::SelectionChanges::SetSelection.
onSelectTimer
void TreeWidget::onSelectTimer () protected slot
Definition at line 3553 of file Tree.cpp.
References Gui::SelectionObserver::blockSelection(), Gui::TreeParams::getSyncSelection(), Gui::Selection(), Gui::DocumentItem::SR_EXPAND, Gui::DocumentItem::SR_SELECT, and TestSpreadsheet::v.
Referenced by getSelection(), selectAllInstances(), selectAllLinks(), selectLinkedObject(), and TreeWidget().
onShowHidden
void TreeWidget::onShowHidden () protected slot
Definition at line 3373 of file Tree.cpp.
References DocumentType, Gui::DocumentObjectItem::getOwnerDocument(), ObjectType, and Gui::DocumentItem::setShowHidden().
Referenced by TreeWidget().
onSkipRecompute
void TreeWidget::onSkipRecompute (bool on) protected slot
Definition at line 1335 of file Tree.cpp.
References toolbit-attributes::doc, DocumentType, and App::Document::SkipRecompute.
Referenced by TreeWidget().
onStartEditing
void TreeWidget::onStartEditing () protected slot
Definition at line 1230 of file Tree.cpp.
References Path.Post.scripts.dynapath_4060_post::action, toolbit-attributes::doc, Gui::getMainWindow(), App::DocumentObject::isAttachedToDocument(), ObjectType, and Gui::MainWindow::setActiveWindow().
Referenced by contextMenuEvent().
onToggleVisibilityInTree
void TreeWidget::onToggleVisibilityInTree () protected slot
Definition at line 3386 of file Tree.cpp.
References src.Mod.Test.testPathArray::items, Gui::DocumentObjectItem::object(), ObjectType, and Gui::ViewProviderDocumentObject::showInTree().
Referenced by TreeWidget().
resetItemSearch()
void TreeWidget::resetItemSearch ()
Definition at line 822 of file Tree.cpp.
Referenced by itemSearch(), and startItemSearch().
scrollItemToTop()
void TreeWidget::scrollItemToTop () static
Definition at line 3246 of file Tree.cpp.
References Gui::Application::activeDocument(), toolbit-attributes::doc, Gui::SelectionSingleton::hasSelection(), SplineSurface::i, Gui::Application::Instance, Gui::NoResolve, Gui::Selection(), and Gui::DocumentItem::SR_FORCE_EXPAND.
selectAll()
void TreeWidget::selectAll () override
Definition at line 772 of file Tree.cpp.
References Gui::SelectionSingleton::clearSelection(), App::GetApplication(), Gui::Application::getDocument(), Gui::TreeParams::getRecordSelection(), Gui::Application::Instance, Gui::Selection(), Gui::SelectionSingleton::selStackPush(), and Gui::SelectionSingleton::setSelection().
selectAllInstances()
void TreeWidget::selectAllInstances (const ViewProviderDocumentObject & vpd)
Definition at line 1402 of file Tree.cpp.
References Gui::SelectionObserver::isSelectionAttached(), onSelectTimer(), and TestSpreadsheet::v.
Referenced by StdCmdTreeSelectAllInstances::activated().
selectAllLinks()
void TreeWidget::selectAllLinks (App::DocumentObject * obj)
Definition at line 1557 of file Tree.cpp.
References App::GetApplication(), App::GetLinkRecursive, Gui::Application::getViewProvider(), Gui::Application::Instance, App::DocumentObject::isAttachedToDocument(), Gui::SelectionObserver::isSelectionAttached(), onSelectTimer(), TREE_ERR, and TestSpreadsheet::v.
Referenced by StdCmdLinkSelectAllLinks::activated().
selectedDocument()
Gui::Document * TreeWidget::selectedDocument () static
Definition at line 969 of file Tree.cpp.
References DocumentType.
Referenced by Gui::PropertyView::onTimer().
selectLinkedObject()
void TreeWidget::selectLinkedObject (App::DocumentObject * linked)
Definition at line 3707 of file Tree.cpp.
References App::Application::getActiveDocument(), App::GetApplication(), getDocumentItem(), Gui::Application::Instance, Gui::SelectionObserver::isSelectionAttached(), Gui::SelectionObserver::isSelectionBlocked(), onSelectTimer(), and TREE_ERR.
Referenced by StdCmdLinkSelectLinked::activated(), and StdCmdLinkSelectLinkedFinal::activated().
setIconHeight()
void TreeWidget::setIconHeight (int height)
Definition at line 1429 of file Tree.cpp.
References iconSize(), KDL::max(), and treeIconSize().
setItemSpacing()
void Gui::TreeWidget::setItemSpacing (int)
setupResizableColumn()
void TreeWidget::setupResizableColumn (TreeWidget * tree = nullptr) static
Definition at line 1476 of file Tree.cpp.
References Gui::TreeParams::getColumnSize1(), Gui::TreeParams::getColumnSize2(), Gui::TreeParams::getColumnSize3(), and Gui::TreeParams::getResizableColumn().
Referenced by TreeWidget().
showEvent()
void TreeWidget::showEvent (QShowEvent * ev) override protected
Definition at line 1193 of file Tree.cpp.
startDrag()
void TreeWidget::startDrag (Qt::DropActions supportedActions) override protected
Definition at line 1836 of file Tree.cpp.
References _DragEventFilter, and _DraggingActive.
Referenced by startDragging().
startDragging()
void TreeWidget::startDragging ()
Definition at line 1824 of file Tree.cpp.
References startDrag().
Referenced by StdTreeDrag::activated().
startItemSearch()
void TreeWidget::startItemSearch (QLineEdit * edit)
Definition at line 837 of file Tree.cpp.
References Gui::Application::activeDocument(), DocumentType, Gui::Document::getDocument(), App::Document::getObjects(), Gui::Application::Instance, ObjectType, and resetItemSearch().
supportedDropActions()
Qt::DropActions TreeWidget::supportedDropActions () const override protected
Definition at line 1602 of file Tree.cpp.
synchronizeSelectionCheckBoxes()
void TreeWidget::synchronizeSelectionCheckBoxes () static
Definition at line 3499 of file Tree.cpp.
References isSelectionCheckBoxesEnabled(), ObjectType, and Gui::DocumentObjectItem::setData().
syncView()
void TreeWidget::syncView (ViewProviderDocumentObject * vp)
Definition at line 3363 of file Tree.cpp.
References Gui::DocumentItem::document(), Gui::TreeParams::getSyncView(), and Gui::Document::setActiveView().
Referenced by Gui::DocumentItem::selectItems(), and Gui::DocumentItem::updateItemSelection().
updateStatus()
void TreeWidget::updateStatus (bool delay = true) static
Definition at line 980 of file Tree.cpp.
Referenced by Path.Main.Gui.Camotics.CAMoticsUI::initializeUI(), and Gui::Document::slotRecomputed().
updateVisibilityIcons()
void TreeWidget::updateVisibilityIcons () static
Definition at line 3516 of file Tree.cpp.
References ObjectType, and Gui::DocumentObjectItem::testStatus().
Friends And Related Function Documentation
DocumentItem
friend class DocumentItem friend
Definition at line 272 of file Tree.h.
DocumentObjectItem
friend class DocumentObjectItem friend
Definition at line 273 of file Tree.h.
TreeParams
friend class TreeParams friend
Definition at line 274 of file Tree.h.
TreeWidgetItemDelegate
friend class TreeWidgetItemDelegate friend
Definition at line 275 of file Tree.h.
Referenced by TreeWidget().
Member Data Documentation
DocumentType
const int TreeWidget::DocumentType = 1000 static
Definition at line 97 of file Tree.h.
Referenced by contextMenuEvent(), dragMoveEvent(), dropEvent(), mouseDoubleClickEvent(), onAllowPartialRecompute(), onCloseDoc(), onCreateGroup(), onMarkRecompute(), onReloadDoc(), onSelectDependents(), onShowHidden(), onSkipRecompute(), selectedDocument(), and startItemSearch().
ObjectType
const int TreeWidget::ObjectType = 1001 static
Definition at line 98 of file Tree.h.
Referenced by contextMenuEvent(), countExpandedItem(), Gui::TreeWidgetItemDelegate::createEditor(), dragMoveEvent(), dropEvent(), Gui::DocumentItem::findItem(), Gui::DocumentItem::findRootIndex(), Gui::DocumentObjectItem::getNextSibling(), Gui::DocumentObjectItem::getParentItem(), Gui::DocumentObjectItem::getPreviousSibling(), getSelection(), mouseDoubleClickEvent(), mousePressEvent(), onCreateGroup(), onFinishEditing(), onMarkRecompute(), onPreSelectTimer(), onRecomputeObject(), onSelectDependents(), onShowHidden(), onStartEditing(), onToggleVisibilityInTree(), Gui::DocumentItem::populateItem(), saveExpandedItem(), Gui::DocumentItem::showItem(), Gui::DocumentItem::sortObjectItems(), startItemSearch(), synchronizeSelectionCheckBoxes(), Gui::DocumentItem::updateItemsVisibility(), Gui::DocumentItem::updateSelection(), and updateVisibilityIcons().
The documentation for this class was generated from the following files:
Tree.h
Tree.cpp