FreeCAD: FCBRepAlgoAPIHelper Class Reference
FCBRepAlgoAPIHelper Class Reference
#include <FCBRepAlgoAPI_BooleanOperation.h>
Static Public Member Functions
static void setAutoFuzzy (BRepAlgoAPI_BooleanOperation *op)
static void setAutoFuzzy (BRepAlgoAPI_BuilderAlgo *op)
Detailed Description
FCBRepAlgoAPI provides a wrapper for various OCCT functions.
Definition at line 33 of file FCBRepAlgoAPI_BooleanOperation.h.
Member Function Documentation
setAutoFuzzy() [1/2]
void FCBRepAlgoAPIHelper::setAutoFuzzy (BRepAlgoAPI_BooleanOperation * op) static
Definition at line 66 of file FCBRepAlgoAPI_BooleanOperation.cpp.
References KDL::Add(), Part::FuzzyHelper::getBooleanFuzzy(), and KDL::sqrt().
Referenced by FC_LOG_LEVEL_INIT(), Part::TopoShape::generalFuse(), FCBRepAlgoAPI_BooleanOperation::setAutoFuzzy(), and FCBRepAlgoAPI_Section::setAutoFuzzy().
setAutoFuzzy() [2/2]
void FCBRepAlgoAPIHelper::setAutoFuzzy (BRepAlgoAPI_BuilderAlgo * op) static
Definition at line 75 of file FCBRepAlgoAPI_BooleanOperation.cpp.
References KDL::Add(), Part::FuzzyHelper::getBooleanFuzzy(), and KDL::sqrt().
The documentation for this class was generated from the following files:
FCBRepAlgoAPI_BooleanOperation.h
FCBRepAlgoAPI_BooleanOperation.cpp