FreeCAD: Mesh::PropertyMeshKernel Class Reference
Mesh::PropertyMeshKernel Class Reference
#include <MeshProperties.h>
Public Member Functions
PropertyMeshKernel ()
~PropertyMeshKernel () override
PropertyMeshKernel (const PropertyMeshKernel &)=delete
PropertyMeshKernel (PropertyMeshKernel &&)=delete
PropertyMeshKernel & operator= (const PropertyMeshKernel &)=delete
PropertyMeshKernel & operator= (PropertyMeshKernel &&)=delete
Getter/setter
void setValuePtr (MeshObject *m)
void setValue (const MeshObject &m)
void setValue (const MeshCore::MeshKernel &m)
void swapMesh (MeshObject &)
void swapMesh (MeshCore::MeshKernel &)
const MeshObject & getValue () const
const MeshObject * getValuePtr () const
unsigned int getMemSize () const override
Getting basic geometric entities
const Data::ComplexGeoData * getComplexData () const override
Base::BoundBox3d getBoundingBox () const override
Modification
MeshObject * startEditing ()
void finishEditing ()
void transformGeometry (const Base::Matrix4D &rclMat) override
Transform the real mesh data.
void setPointIndices (const std::vector< std::pair< PointIndex, Base::Vector3f >> &)
void setTransform (const Base::Matrix4D &rclTrf) override
Set the placement of the geometry.
Base::Matrix4D getTransform () const override
Get the placement of the geometry.
Python interface
PyObject * getPyObject () override
void setPyObject (PyObject *value) override
const char * getEditorName () const override
Get the class name of the associated property editor item.
Public Member Functions inherited from App::PropertyComplexGeoData
PropertyComplexGeoData ()
~PropertyComplexGeoData () override
virtual std::string getElementMapVersion (bool restored=false) const
virtual bool checkElementMapVersion (const char *ver) const
Return true to signal element map version change.
void afterRestore () override
Public Member Functions inherited from App::PropertyGeometry
PropertyGeometry ()
~PropertyGeometry () override
Public Member Functions inherited from App::Property
Property ()
~Property () override
const char * getName () const
bool hasName () const
std::string getFullName () const
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual void onContainerRestored ()
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
int64_t getID () const
virtual void beforeSave () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Save/restore
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void SaveDocFile (Base::Writer &writer) const override
void RestoreDocFile (Base::Reader &reader) override
App::Property * Copy () const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const App::Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::Property
virtual void hasSetValue ()
Gets called by all setValue() methods after the value has changed.
virtual void aboutToSetValue ()
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Detailed Description
The mesh kernel property class.
Author
Werner Mayer
Definition at line 253 of file MeshProperties.h.
Constructor & Destructor Documentation
PropertyMeshKernel() [1/3]
PropertyMeshKernel::PropertyMeshKernel ()
Definition at line 722 of file MeshProperties.cpp.
Referenced by Copy().
~PropertyMeshKernel()
PropertyMeshKernel::~PropertyMeshKernel () override
Definition at line 731 of file MeshProperties.cpp.
PropertyMeshKernel() [2/3]
Mesh::PropertyMeshKernel::PropertyMeshKernel (const PropertyMeshKernel &) delete
PropertyMeshKernel() [3/3]
Mesh::PropertyMeshKernel::PropertyMeshKernel (PropertyMeshKernel &&) delete
Member Function Documentation
Copy()
App::Property * PropertyMeshKernel::Copy () const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 934 of file MeshProperties.cpp.
References PropertyMeshKernel().
finishEditing()
void PropertyMeshKernel::finishEditing ()
Definition at line 813 of file MeshProperties.cpp.
References App::Property::hasSetValue().
Referenced by MeshGui::Segmentation::accept(), ReverseEngineeringGui::Segmentation::accept(), MeshGui::SegmentationBestFit::accept(), ReverseEngineeringGui::SegmentationManual::createSegment(), MeshGui::ViewProviderMesh::removeFacets(), MeshGui::ViewProviderMesh::segmentMesh(), and MeshGui::ViewProviderMesh::trimMesh().
getBoundingBox()
Base::BoundBox3d PropertyMeshKernel::getBoundingBox () const override virtual
Returns the bounding box around the underlying mesh kernel
Implements App::PropertyComplexGeoData.
Definition at line 794 of file MeshProperties.cpp.
getComplexData()
const Data::ComplexGeoData * PropertyMeshKernel::getComplexData () const override virtual
Implements App::PropertyComplexGeoData.
Definition at line 789 of file MeshProperties.cpp.
getEditorName()
const char* Mesh::PropertyMeshKernel::getEditorName () const inline override virtual
Get the class name of the associated property editor item.
Reimplemented from App::Property.
Definition at line 326 of file MeshProperties.h.
getMemSize()
unsigned int PropertyMeshKernel::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence
See also
Base::Persistence
Reimplemented from App::Property.
Definition at line 799 of file MeshProperties.cpp.
getPyObject()
PyObject * PropertyMeshKernel::getPyObject () override virtual
Returns a Python wrapper for the referenced mesh object. It does NOT create a copy. However, the Python wrapper is marked as immutable so that the mesh object cannot be modified from outside.
Reimplemented from Base::BaseClass.
Definition at line 846 of file MeshProperties.cpp.
getTransform()
Base::Matrix4D PropertyMeshKernel::getTransform () const override virtual
Get the placement of the geometry.
Implements App::PropertyGeometry.
Definition at line 841 of file MeshProperties.cpp.
getValue()
const MeshObject & PropertyMeshKernel::getValue () const
Returns a the attached mesh object by reference. It cannot be modified from outside.
Definition at line 779 of file MeshProperties.cpp.
Referenced by MeshPartGui::CurveOnMeshHandler::Private::createGrid(), MeshGui::MeshSelection::deleteSelection(), MeshGui::MeshSelection::deleteSelectionBorder(), Mesh::Curvature::execute(), Mesh::SetOperations::execute(), Mesh::SegmentByMesh::execute(), Mesh::HarmonizeNormals::execute(), Mesh::Export::execute(), Mesh::FlipNormals::execute(), Mesh::FixNonManifolds::execute(), Mesh::FixDuplicatedFaces::execute(), Mesh::FixDuplicatedPoints::execute(), Mesh::FixDegenerations::execute(), Mesh::FixDeformations::execute(), Mesh::FixIndices::execute(), Mesh::FillHoles::execute(), Mesh::RemoveComponents::execute(), MeshGui::ViewProviderMesh::getMeshObject(), MeshInfoWatcher::onSelectionChanged(), MeshGui::ViewProviderMesh::segmentMesh(), MeshGui::DlgEvaluateMeshImp::showInformation(), MeshGui::ViewProviderMesh::splitMesh(), and MeshGui::PropertyMeshKernelItem::value().
getValuePtr()
const MeshObject * PropertyMeshKernel::getValuePtr () const
Definition at line 784 of file MeshProperties.cpp.
Referenced by MeshGui::Segmentation::accept(), MeshGui::SegmentationBestFit::accept(), MeshGui::MeshSelection::deselectComponent(), MeshGui::MeshSelection::fullSelection(), and MeshGui::MeshSelection::selectComponent().
operator=() [1/2]
PropertyMeshKernel& Mesh::PropertyMeshKernel::operator= (const PropertyMeshKernel &) delete
operator=() [2/2]
PropertyMeshKernel& Mesh::PropertyMeshKernel::operator= (PropertyMeshKernel &&) delete
Paste()
void PropertyMeshKernel::Paste (const App::Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 942 of file MeshProperties.cpp.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
Restore()
void PropertyMeshKernel::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 896 of file MeshProperties.cpp.
References App::Property::aboutToSetValue(), MeshCore::MeshKernel::Adopt(), DrawingExample::file, App::Property::hasSetValue(), MeshCore::MeshInput::LoadXML(), and TechDrawTools.TaskFillTemplateFields::reader.
RestoreDocFile()
void PropertyMeshKernel::RestoreDocFile (Base::Reader &) override virtual
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data. Again you have to apply for the call of this method in the Restore() call:
void PropertyMeshKernel::Restore(Base::XMLReader &reader)
{
  reader.readElement("Mesh");
  std::string file (reader.getAttribute("file") );
  if(file == "")
  {
    // read XML
    MeshCore::MeshDocXML restorer(*_pcMesh);
    restorer.Restore(reader);
  }else{
    // initiate a file read
    reader.addFile(file.c_str(),this);
 }
}
After you issued the reader.addFile() your RestoreDocFile() is called:
void PropertyMeshKernel::RestoreDocFile(Base::Reader &reader)
{
    _pcMesh->Read( reader );
}
See also
Base::Reader,Base::XMLReader
Reimplemented from Base::Persistence.
Definition at line 927 of file MeshProperties.cpp.
References App::Property::aboutToSetValue(), App::Property::hasSetValue(), and TechDrawTools.TaskFillTemplateFields::reader.
Save()
void PropertyMeshKernel::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 883 of file MeshProperties.cpp.
References Base::Writer::addFile(), Base::Writer::ind(), Base::Writer::isForceXML(), MeshCore::MeshOutput::SaveXML(), and Base::Writer::Stream().
SaveDocFile()
void PropertyMeshKernel::SaveDocFile (Base::Writer &) const override virtual
This method is used to save large amounts of data to a binary file. Sometimes it makes no sense to write property data as XML. In case the amount of data is too big or the data type has a more effective way to save itself. In this cases it is possible to write the data in a separate file inside the document archive. In case you want do so you have to re-implement SaveDocFile(). First, you have to inform the framework in Save() that you want do so. Here an example from the Mesh module which can save a (pontetionaly big) triangle mesh:
void PropertyMeshKernel::Save (Base::Writer &writer) const
{
  if (writer.isForceXML())
  {
    writer << writer.ind() << "<Mesh>" << std::endl;
    MeshCore::MeshDocXML saver(*_pcMesh);
    saver.Save(writer);
  }else{
   writer << writer.ind() << "<Mesh file=\"" << writer.addFile("MeshKernel.bms", this) <<
"\"/>" << std::endl;
}
The writer.isForceXML() is an indication to force you to write XML. Regardless of size and effectiveness. The second part informs the Base::writer through writer.addFile("MeshKernel.bms", this) that this object wants to write a file with the given name. The method addFile() returns a unique name that then is written in the XML stream. This allows your RestoreDocFile() method to identify and read the file again. Later your SaveDocFile() method is called as many times as you issued the addFile() call:
 void
PropertyMeshKernel::SaveDocFile (Base::Writer &writer) const
{
    _pcMesh->Write( writer );
}
In this method you can simply stream your content to the file (Base::Writer inheriting from ostream).
Reimplemented from Base::Persistence.
Definition at line 922 of file MeshProperties.cpp.
References Base::Writer::Stream().
setPointIndices()
void PropertyMeshKernel::setPointIndices (const std::vector< std::pair< PointIndex, Base::Vector3f >> & inds)
Definition at line 825 of file MeshProperties.cpp.
References App::Property::aboutToSetValue(), App::Property::hasSetValue(), and MeshCore::MeshKernel::SetPoint().
setPyObject()
void PropertyMeshKernel::setPyObject (PyObject * value) override virtual
This method copies the content, hence creates an new mesh object to copy the data. The passed argument can be an instance of the Python wrapper for the mesh object or simply a list of triangles, i.e. a list of lists of three floats.
Reimplemented from Base::BaseClass.
Definition at line 860 of file MeshProperties.cpp.
References Mesh::MeshObject::createMeshFromList(), Path.Log::error(), Mesh2Shape::mesh, setValue(), and setValuePtr().
setTransform()
void PropertyMeshKernel::setTransform (const Base::Matrix4D & rclTrf) override virtual
Set the placement of the geometry.
Implements App::PropertyGeometry.
Definition at line 836 of file MeshProperties.cpp.
setValue() [1/2]
void PropertyMeshKernel::setValue (const MeshCore::MeshKernel & m)
This method sets the mesh by copying the data.
Definition at line 758 of file MeshProperties.cpp.
References App::Property::aboutToSetValue(), App::Property::hasSetValue(), and Mesh2Shape::mesh.
setValue() [2/2]
void PropertyMeshKernel::setValue (const MeshObject & m)
This method sets the mesh by copying the data.
Definition at line 751 of file MeshProperties.cpp.
References App::Property::aboutToSetValue(), App::Property::hasSetValue(), and Mesh2Shape::mesh.
Referenced by MeshGui::RemeshGmsh::loadOutput(), and setPyObject().
setValuePtr()
void PropertyMeshKernel::setValuePtr (MeshObject * m)
This method references the passed mesh object and takes possession of it, it does NOT create a copy. The currently referenced mesh object gets de-referenced and possibly deleted if its reference counter becomes zero. However, the mesh gets saved before if a transaction is open at this time.
Note
Make sure not to reference the internal mesh pointer pf this class in client code. This could lead to crashes if not handled properly.
Definition at line 741 of file MeshProperties.cpp.
References App::Property::aboutToSetValue(), App::Property::hasSetValue(), and Mesh2Shape::mesh.
Referenced by setPyObject().
startEditing()
MeshObject * PropertyMeshKernel::startEditing ()
Definition at line 807 of file MeshProperties.cpp.
References App::Property::aboutToSetValue().
Referenced by MeshGui::Segmentation::accept(), ReverseEngineeringGui::Segmentation::accept(), MeshGui::SegmentationBestFit::accept(), ReverseEngineeringGui::SegmentationManual::createSegment(), MeshGui::ViewProviderMesh::removeFacets(), MeshGui::ViewProviderMesh::segmentMesh(), and MeshGui::ViewProviderMesh::trimMesh().
swapMesh() [1/2]
void PropertyMeshKernel::swapMesh (MeshCore::MeshKernel & mesh)
Swaps the mesh data structure.
Definition at line 772 of file MeshProperties.cpp.
References App::Property::aboutToSetValue(), App::Property::hasSetValue(), and Mesh2Shape::mesh.
swapMesh() [2/2]
void PropertyMeshKernel::swapMesh (MeshObject & mesh)
Swaps the mesh data structure.
Definition at line 765 of file MeshProperties.cpp.
References App::Property::aboutToSetValue(), App::Property::hasSetValue(), and Mesh2Shape::mesh.
transformGeometry()
void PropertyMeshKernel::transformGeometry (const Base::Matrix4D & rclMat) override virtual
Transform the real mesh data.
Implements App::PropertyComplexGeoData.
Definition at line 818 of file MeshProperties.cpp.
References App::Property::aboutToSetValue(), and App::Property::hasSetValue().
The documentation for this class was generated from the following files:
MeshProperties.h
MeshProperties.cpp