FreeCAD: Base::TransformItem Class Reference
Base::TransformItem Class Reference
The TransformItem class supports the SoTransform node.
#include <Builder3D.h>
Public Member Functions
TransformItem (const Base::Placement &)
TransformItem (const Base::Matrix4D &)
void write (InventorOutput &out) const override
Public Member Functions inherited from Base::NodeItem
virtual ~NodeItem ()=default
Additional Inherited Members
Protected Member Functions inherited from Base::NodeItem
NodeItem ()=default
NodeItem (const NodeItem &)=default
NodeItem (NodeItem &&)=default
NodeItem & operator= (const NodeItem &)=default
NodeItem & operator= (NodeItem &&)=default
Detailed Description
The TransformItem class supports the SoTransform node.
Definition at line 657 of file Builder3D.h.
Constructor & Destructor Documentation
TransformItem() [1/2]
TransformItem::TransformItem (const Base::Placement & placement) explicit
Definition at line 916 of file Builder3D.cpp.
TransformItem() [2/2]
TransformItem::TransformItem (const Base::Matrix4D & transform) explicit
Definition at line 920 of file Builder3D.cpp.
References Base::Placement::fromMatrix().
Member Function Documentation
write()
void TransformItem::write (InventorOutput & out) const override virtual
Implements Base::NodeItem.
Definition at line 925 of file Builder3D.cpp.
References Base::Placement::getPosition(), Base::Placement::getRotation(), Base::Rotation::getValue(), Base::InventorOutput::write(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
The documentation for this class was generated from the following files:
Builder3D.h
Builder3D.cpp