FreeCAD: Gui::ItemViewSelection Class Reference
Gui::ItemViewSelection Class Reference
#include <Utilities.h>
Classes
class MatchName
Public Member Functions
ItemViewSelection (QAbstractItemView *view)
void applyFrom (const std::vector< App::DocumentObject * > objs)
Detailed Description
Definition at line 168 of file Gui/Utilities.h.
Constructor & Destructor Documentation
ItemViewSelection()
ItemViewSelection::ItemViewSelection (QAbstractItemView * view) explicit
Definition at line 145 of file Utilities.cpp.
Member Function Documentation
applyFrom()
void ItemViewSelection::applyFrom (const std::vector< App::DocumentObject * > objs)
Definition at line 150 of file Utilities.cpp.
References SplineSurface::i, and replaceobj::objs.
Referenced by PartGui::DlgExtrusion::DlgExtrusion(), PartGui::DlgRevolution::DlgRevolution(), PartGui::DlgScale::DlgScale(), and PartGui::Mirroring::Mirroring().
The documentation for this class was generated from the following files:
Gui/Utilities.h
Utilities.cpp