FreeCAD: Path::Voronoi Class Reference
Path::Voronoi Class Reference
#include <Voronoi.h>
Classes
class diagram_type
Public Types
using color_type = std::size_t
using coordinate_type = double
using vertex_type = boost::polygon::voronoi_vertex< double >
using point_type = boost::polygon::point_data< coordinate_type >
using segment_type = boost::polygon::segment_data< coordinate_type >
using voronoi_diagram_type = boost::polygon::voronoi_diagram< double >
Public Member Functions
Voronoi ()
~Voronoi () override
void addPoint (const point_type &p)
void addSegment (const segment_type &p)
long numPoints () const
long numSegments () const
void construct ()
long numCells () const
long numEdges () const
long numVertices () const
void resetColor (color_type color)
void colorExterior (color_type color)
void colorTwins (color_type color)
void colorColinear (color_type color, double degree)
template<typename T >
T * create (int index)
double getScale () const
void setScale (double scale)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Attributes
static const int InvalidIndex = INT_MAX
static const color_type ColorMask = 0x07FFFFFFul
Friends
class VoronoiPy
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 44 of file Voronoi.h.
Member Typedef Documentation
color_type
using Path::Voronoi::color_type = std::size_t
Definition at line 53 of file Voronoi.h.
coordinate_type
using Path::Voronoi::coordinate_type = double
Definition at line 58 of file Voronoi.h.
point_type
using Path::Voronoi::point_type = boost::polygon::point_data<coordinate_type>
Definition at line 60 of file Voronoi.h.
segment_type
using Path::Voronoi::segment_type = boost::polygon::segment_data<coordinate_type>
Definition at line 61 of file Voronoi.h.
vertex_type
using Path::Voronoi::vertex_type = boost::polygon::voronoi_vertex<double>
Definition at line 59 of file Voronoi.h.
voronoi_diagram_type
using Path::Voronoi::voronoi_diagram_type = boost::polygon::voronoi_diagram<double>
Definition at line 62 of file Voronoi.h.
Constructor & Destructor Documentation
Voronoi()
Voronoi::Voronoi ()
Definition at line 147 of file Voronoi.cpp.
~Voronoi()
Voronoi::~Voronoi () override
Definition at line 151 of file Voronoi.cpp.
Member Function Documentation
addPoint()
void Voronoi::addPoint (const point_type & p)
Definition at line 155 of file Voronoi.cpp.
References buildPsets::p, and ClipperLib::pi.
Referenced by draftguitools.gui_stretch.Stretch::action(), and draftguitools.gui_stretch.Stretch::numericInput().
addSegment()
void Voronoi::addSegment (const segment_type & p)
Definition at line 163 of file Voronoi.cpp.
References toolbit-attributes::s, MovieTool::x, and MovieTool::y.
Referenced by src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::addSegments().
colorColinear()
void Voronoi::colorColinear (Voronoi::color_type color, double degree)
Definition at line 293 of file Voronoi.cpp.
References a, NavigationIndicatorGui::a0, NavigationIndicatorGui::a1, M_PI, and M_PI_2.
colorExterior()
void Voronoi::colorExterior (Voronoi::color_type color)
Definition at line 230 of file Voronoi.cpp.
colorTwins()
void Voronoi::colorTwins (Voronoi::color_type color)
Definition at line 240 of file Voronoi.cpp.
construct()
void Voronoi::construct ()
Definition at line 199 of file Voronoi.cpp.
create()
template<typename T > T* Path::Voronoi::create (int index) inline
Definition at line 119 of file Voronoi.h.
References CAMTests.TestPathVoronoi::vd.
Referenced by draftguitools.gui_labels.Label::action().
getScale()
double Path::Voronoi::getScale () const inline
Definition at line 124 of file Voronoi.h.
References CAMTests.TestPathVoronoi::vd.
numCells()
long Voronoi::numCells () const
Definition at line 184 of file Voronoi.cpp.
numEdges()
long Voronoi::numEdges () const
Definition at line 189 of file Voronoi.cpp.
numPoints()
long Voronoi::numPoints () const
Definition at line 173 of file Voronoi.cpp.
numSegments()
long Voronoi::numSegments () const
Definition at line 178 of file Voronoi.cpp.
numVertices()
long Voronoi::numVertices () const
Definition at line 194 of file Voronoi.cpp.
resetColor()
void Voronoi::resetColor (Voronoi::color_type color)
Definition at line 323 of file Voronoi.cpp.
setScale()
void Path::Voronoi::setScale (double scale) inline
Definition at line 128 of file Voronoi.h.
References CAMTests.TestPathVoronoi::vd.
Friends And Related Function Documentation
VoronoiPy
friend class VoronoiPy friend
Definition at line 135 of file Voronoi.h.
Member Data Documentation
ColorMask
const color_type Path::Voronoi::ColorMask = 0x07FFFFFFul static
Definition at line 55 of file Voronoi.h.
InvalidIndex
const int Path::Voronoi::InvalidIndex = INT_MAX static
Definition at line 54 of file Voronoi.h.
Referenced by Path::VoronoiCell::isBound(), Path::VoronoiVertex::isBound(), and Path::VoronoiEdge::isBound().
The documentation for this class was generated from the following files:
Voronoi.h
Voronoi.cpp