FreeCAD: Gui::Dialog::DlgSettingsGeneral Class Reference
Gui::Dialog::DlgSettingsGeneral Class Reference
#include <DlgSettingsGeneral.h>
Public Slots
void onUnitSystemIndexChanged (int index)
Public Slots inherited from Gui::Dialog::PreferencePage
Public Member Functions
DlgSettingsGeneral (QWidget *parent=nullptr)
~DlgSettingsGeneral () override
void saveSettings () override
void loadSettings () override
void resetSettingsToDefaults () override
void saveThemes ()
void loadThemes ()
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Static Public Member Functions
static void attachObserver ()
Protected Slots
void onLoadPreferencePackClicked (const std::string &packName)
void recreatePreferencePackMenu ()
void newPreferencePackDialogAccepted ()
void onManagePreferencePacksClicked ()
void onImportConfigClicked ()
void onThemeChanged (int index)
void onLinkActivated (const QString &link)
Protected Member Functions
void changeEvent (QEvent *event) override
Detailed Description
This class implements the settings for the application. You can change window style, size of pixmaps, size of recent file list and so on
Author
Werner Mayer
Definition at line 46 of file Gui/PreferencePages/DlgSettingsGeneral.h.
Constructor & Destructor Documentation
DlgSettingsGeneral()
DlgSettingsGeneral::DlgSettingsGeneral (QWidget * parent = nullptr) explicit
Constructs a DlgSettingsGeneral which is a child of 'parent', with the name 'name' and widget flags set to 'f'
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
Definition at line 77 of file Gui/PreferencePages/DlgSettingsGeneral.cpp.
References Gui::Application::activeDocument(), Gui::PreferencePackManager::configBackups(), draftgeoutils.intersections::connect(), toolbit-attributes::doc, Base::UnitsApi::getDescription(), importers.importIFClegacy::getSchema(), Gui::View3DInventor::getViewer(), SplineSurface::i, Gui::Application::Instance, Base::NumUnitSystemTypes, onImportConfigClicked(), onLinkActivated(), onManagePreferencePacksClicked(), onThemeChanged(), onUnitSystemIndexChanged(), Gui::Application::prefPackManager(), recreatePreferencePackMenu(), and OfflineRenderingUtils::viewer().
~DlgSettingsGeneral()
DlgSettingsGeneral::~DlgSettingsGeneral () override default
Destroys the object and frees any allocated resources
Member Function Documentation
attachObserver()
void DlgSettingsGeneral::attachObserver () static
Definition at line 829 of file Gui/PreferencePages/DlgSettingsGeneral.cpp.
References Gui::ParamHandlers::addHandler(), App::GetApplication(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
changeEvent()
void DlgSettingsGeneral::changeEvent (QEvent * event) override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 546 of file Gui/PreferencePages/DlgSettingsGeneral.cpp.
loadSettings()
void DlgSettingsGeneral::loadSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 289 of file Gui/PreferencePages/DlgSettingsGeneral.cpp.
References Gui::Translator::activeLanguage(), App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetBool(), Base::UnitsApi::getDecimals(), Base::QuantityFormat::getDefaultDenominator(), Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), Gui::Translator::instance(), loadThemes(), Path.Base.Util::setProperty(), and Gui::Translator::supportedLocales().
loadThemes()
void DlgSettingsGeneral::loadThemes ()
Definition at line 444 of file Gui/PreferencePages/DlgSettingsGeneral.cpp.
References App::GetApplication(), ParameterGrp::GetASCII(), App::Application::GetParameterGroupByPath(), Gui::Application::Instance, Gui::PreferencePackManager::preferencePacks(), Gui::Application::prefPackManager(), Gui::PreferencePackManager::rescan(), and ParameterGrp::SetASCII().
Referenced by loadSettings().
newPreferencePackDialogAccepted
void DlgSettingsGeneral::newPreferencePackDialogAccepted () protected slot
Definition at line 708 of file Gui/PreferencePages/DlgSettingsGeneral.cpp.
References Gui::Application::Instance, Gui::Application::prefPackManager(), Path.Dressup.Utils::selection(), and Gui::PreferencePackManager::templateFiles().
onImportConfigClicked
void DlgSettingsGeneral::onImportConfigClicked () protected slot
Definition at line 737 of file Gui/PreferencePages/DlgSettingsGeneral.cpp.
References DraftVecUtils::find(), Gui::PreferencePackManager::importConfig(), Gui::Application::Instance, src.Mod.Test.testPathArray::path, Gui::PreferencePackManager::preferencePackNames(), Gui::Application::prefPackManager(), recreatePreferencePackMenu(), and result.
Referenced by DlgSettingsGeneral().
onLinkActivated
void DlgSettingsGeneral::onLinkActivated (const QString & link) protected slot
Definition at line 794 of file Gui/PreferencePages/DlgSettingsGeneral.cpp.
References Gui::Application::commandManager(), App::GetApplication(), App::Application::GetParameterGroupByPath(), Gui::Application::Instance, Gui::CommandManager::runCommandByName(), and ParameterGrp::SetInt().
Referenced by DlgSettingsGeneral().
onLoadPreferencePackClicked
void DlgSettingsGeneral::onLoadPreferencePackClicked (const std::string & packName) protected slot
Definition at line 762 of file Gui/PreferencePages/DlgSettingsGeneral.cpp.
References Gui::Application::Instance.
Referenced by recreatePreferencePackMenu().
onManagePreferencePacksClicked
void DlgSettingsGeneral::onManagePreferencePacksClicked () protected slot
Definition at line 727 of file Gui/PreferencePages/DlgSettingsGeneral.cpp.
References draftgeoutils.intersections::connect(), Gui::Dialog::DlgPreferencePackManagementImp::packVisibilityChanged(), and recreatePreferencePackMenu().
Referenced by DlgSettingsGeneral().
onThemeChanged
void DlgSettingsGeneral::onThemeChanged (int index) protected slot
Definition at line 789 of file Gui/PreferencePages/DlgSettingsGeneral.cpp.
Referenced by DlgSettingsGeneral().
onUnitSystemIndexChanged
void DlgSettingsGeneral::onUnitSystemIndexChanged (int index) slot
Definition at line 771 of file Gui/PreferencePages/DlgSettingsGeneral.cpp.
Referenced by DlgSettingsGeneral().
recreatePreferencePackMenu
void DlgSettingsGeneral::recreatePreferencePackMenu () protected slot
Definition at line 615 of file Gui/PreferencePages/DlgSettingsGeneral.cpp.
References Gui::Application::activeDocument(), draftgeoutils.intersections::connect(), toolbit-attributes::doc, Gui::View3DInventor::getViewer(), Gui::Application::Instance, onLoadPreferencePackClicked(), Gui::PreferencePackManager::preferencePacks(), Gui::Application::prefPackManager(), Gui::PreferencePackManager::rescan(), Dice3DS.dom3ds::tag, and OfflineRenderingUtils::viewer().
Referenced by DlgSettingsGeneral(), onImportConfigClicked(), and onManagePreferencePacksClicked().
resetSettingsToDefaults()
void DlgSettingsGeneral::resetSettingsToDefaults () override virtual
Reimplemented from Gui::Dialog::PreferencePage.
Definition at line 366 of file Gui/PreferencePages/DlgSettingsGeneral.cpp.
References App::GetApplication(), Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), App::Application::GetParameterGroupByPath(), ParameterGrp::RemoveASCII(), ParameterGrp::RemoveBool(), ParameterGrp::RemoveInt(), and Gui::Dialog::PreferencePage::resetSettingsToDefaults().
saveSettings()
void DlgSettingsGeneral::saveSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 249 of file Gui/PreferencePages/DlgSettingsGeneral.cpp.
References App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetBool(), Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), Gui::getMainWindow(), App::Application::GetParameterGroupByPath(), Gui::Dialog::PreferencePage::requireRestart(), saveThemes(), ParameterGrp::SetBool(), and ParameterGrp::SetInt().
saveThemes()
void DlgSettingsGeneral::saveThemes ()
Definition at line 404 of file Gui/PreferencePages/DlgSettingsGeneral.cpp.
References App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), Gui::Application::Instance, Gui::PreferencePackManager::preferencePacks(), Gui::Application::prefPackManager(), Gui::PreferencePackManager::rescan(), ParameterGrp::SetASCII(), and Gui::Application::setStyleSheet().
Referenced by saveSettings().
The documentation for this class was generated from the following files:
Gui/PreferencePages/DlgSettingsGeneral.h
Gui/PreferencePages/DlgSettingsGeneral.cpp