FreeCAD: MeshGui::PlaneFitParameter Class Reference
MeshGui::PlaneFitParameter Class Reference
Public Member Functions
PlaneFitParameter ()=default
std::vector< float > getParameter (FitParameter::Points pts) const override
Public Member Functions inherited from MeshGui::FitParameter
FitParameter ()=default
virtual ~FitParameter ()=default
FitParameter (const FitParameter &)=delete
FitParameter (FitParameter &&)=delete
FitParameter & operator= (const FitParameter &)=delete
FitParameter & operator= (FitParameter &&)=delete
Detailed Description
Definition at line 51 of file SegmentationBestFit.cpp.
Constructor & Destructor Documentation
PlaneFitParameter()
MeshGui::PlaneFitParameter::PlaneFitParameter () default
Member Function Documentation
getParameter()
std::vector<float> MeshGui::PlaneFitParameter::getParameter (FitParameter::Points pts) const inline override virtual
Implements MeshGui::FitParameter.
Definition at line 55 of file SegmentationBestFit.cpp.
References MeshCore::Approximation::AddPoints(), MeshCore::PlaneFit::Fit(), FLOAT_MAX, MeshCore::PlaneFit::GetBase(), MeshCore::PlaneFit::GetNormal(), MeshGui::FitParameter::Points::points, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
The documentation for this class was generated from the following file:
SegmentationBestFit.cpp