FreeCAD: CommandBody.cpp File Reference
CommandBody.cpp File Reference
#include "PreCompiled.h"
#include <QApplication>
#include <QInputDialog>
#include <QMessageBox>
#include <TopExp_Explorer.hxx>
#include <App/Document.h>
#include <App/GeoFeatureGroupExtension.h>
#include <App/Origin.h>
#include <App/Part.h>
#include <Base/Console.h>
#include <Base/Tools.h>
#include <Gui/Command.h>
#include <Gui/Control.h>
#include <Gui/Document.h>
#include <Gui/Application.h>
#include <Gui/MainWindow.h>
#include <Gui/MDIView.h>
#include <Mod/Sketcher/App/SketchObject.h>
#include <Mod/PartDesign/App/Body.h>
#include <Mod/PartDesign/App/FeatureBase.h>
#include <Mod/PartDesign/App/FeatureSketchBased.h>
#include "TaskFeaturePick.h"
#include "Utils.h"
#include "WorkflowManager.h"
Namespaces
PartDesignGui
Functions
App::Part * PartDesignGui::assertActivePart ()
Returns active part, if there is no such, creates a new part, if it fails, shows a message.
void CreatePartDesignBodyCommands ()
Function Documentation
CreatePartDesignBodyCommands()
void CreatePartDesignBodyCommands ()
Definition at line 985 of file CommandBody.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().