FreeCAD: Gui::Dialog::DlgAddProperty Class Reference
Gui::Dialog::DlgAddProperty Class Reference
#include <DlgAddProperty.h>
Public Member Functions
DlgAddProperty (QWidget *parent, std::unordered_set< App::PropertyContainer * > &&)
~DlgAddProperty () override
void accept () override
Detailed Description
Definition at line 38 of file DlgAddProperty.h.
Constructor & Destructor Documentation
DlgAddProperty()
DlgAddProperty::DlgAddProperty (QWidget * parent, std::unordered_set< App::PropertyContainer * > && c)
Definition at line 43 of file DlgAddProperty.cpp.
References a, SCL.SimpleDataTypes::b, Base::Type::fromName(), Base::Type::getAllDerivedFrom(), App::GetApplication(), Base::Persistence::getClassTypeId(), App::Application::GetParameterGroupByPath(), and Path.Post.scripts.grbl_post::type.
~DlgAddProperty()
DlgAddProperty::~DlgAddProperty () override default
Destroys the object and frees any allocated resources
Member Function Documentation
accept()
void DlgAddProperty::accept () override
Definition at line 97 of file DlgAddProperty.cpp.
References SCL.SimpleDataTypes::c, containerName(), SCL.SimpleDataTypes::e, App::GetApplication(), Base::Tools::getIdentifier(), Gui::getMainWindow(), App::Application::GetParameterGroupByPath(), toolbit-attributes::group, App::ExpressionParser::isTokenAConstant(), App::ExpressionParser::isTokenAUnit(), ParameterGrp::SetASCII(), and Path.Post.scripts.grbl_post::type.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
The documentation for this class was generated from the following files:
DlgAddProperty.h
DlgAddProperty.cpp