FreeCAD: AdaptivePath::Interpolation Class Reference
AdaptivePath::Interpolation Class Reference
Public Member Functions
void clear ()
void addPoint (double area, double angle)
double interpolateAngle (double targetArea)
double clampAngle (double angle)
double getRandomAngle ()
size_t getPointCount ()
Public Attributes
const double MIN_ANGLE = - 3.141592653589793238 / 4
const double MAX_ANGLE = 3.141592653589793238 / 4
Detailed Description
Definition at line 1096 of file Adaptive.cpp.
Member Function Documentation
addPoint()
void AdaptivePath::Interpolation::addPoint (double area, double angle) inline
Definition at line 1108 of file Adaptive.cpp.
References SplineSurface::i.
Referenced by draftguitools.gui_stretch.Stretch::action(), and draftguitools.gui_stretch.Stretch::numericInput().
clampAngle()
double AdaptivePath::Interpolation::clampAngle (double angle) inline
Definition at line 1147 of file Adaptive.cpp.
clear()
void AdaptivePath::Interpolation::clear () inline
Definition at line 1102 of file Adaptive.cpp.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), and src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__().
getPointCount()
size_t AdaptivePath::Interpolation::getPointCount () inline
Definition at line 1162 of file Adaptive.cpp.
getRandomAngle()
double AdaptivePath::Interpolation::getRandomAngle () inline
Definition at line 1158 of file Adaptive.cpp.
interpolateAngle()
double AdaptivePath::Interpolation::interpolateAngle (double targetArea) inline
Definition at line 1125 of file Adaptive.cpp.
References a, and SplineSurface::i.
Member Data Documentation
MAX_ANGLE
const double AdaptivePath::Interpolation::MAX_ANGLE = 3.141592653589793238 / 4
Definition at line 1100 of file Adaptive.cpp.
MIN_ANGLE
const double AdaptivePath::Interpolation::MIN_ANGLE = - 3.141592653589793238 / 4
Definition at line 1099 of file Adaptive.cpp.
The documentation for this class was generated from the following file:
Adaptive.cpp