FreeCAD: Gui::SoQtOffscreenRenderer Class Reference
Gui::SoQtOffscreenRenderer Class Reference
#include <SoFCOffscreenRenderer.h>
Public Member Functions
SoQtOffscreenRenderer (const SbViewportRegion &viewportregion)
SoQtOffscreenRenderer (SoGLRenderAction *action)
~SoQtOffscreenRenderer ()
void setViewportRegion (const SbViewportRegion &region)
const SbViewportRegion & getViewportRegion () const
void setBackgroundColor (const SbColor4f &color)
const SbColor4f & getBackgroundColor () const
void setGLRenderAction (SoGLRenderAction *action)
SoGLRenderAction * getGLRenderAction () const
void setNumPasses (const int num)
int getNumPasses () const
void setInternalTextureFormat (GLenum internalTextureFormat)
GLenum internalTextureFormat () const
SbBool render (SoNode *scene)
SbBool render (SoPath *scene)
void writeToImage (QImage &) const
QStringList getWriteImageFiletypeInfo () const
Detailed Description
Definition at line 125 of file SoFCOffscreenRenderer.h.
Constructor & Destructor Documentation
SoQtOffscreenRenderer() [1/2]
SoQtOffscreenRenderer::SoQtOffscreenRenderer (const SbViewportRegion & viewportregion)
Constructor. Argument is the viewportregion we should use when rendering. An internal SoGLRenderAction will be constructed.
Definition at line 428 of file SoFCOffscreenRenderer.cpp.
SoQtOffscreenRenderer() [2/2]
SoQtOffscreenRenderer::SoQtOffscreenRenderer (SoGLRenderAction * action)
Constructor. Argument is the action we should apply to the scene graph when rendering the scene. Information about the viewport is extracted from the action.
Definition at line 438 of file SoFCOffscreenRenderer.cpp.
References Path.Post.scripts.dynapath_4060_post::action.
~SoQtOffscreenRenderer()
SoQtOffscreenRenderer::~SoQtOffscreenRenderer ()
Destructor.
Definition at line 446 of file SoFCOffscreenRenderer.cpp.
Member Function Documentation
getBackgroundColor()
const SbColor4f & SoQtOffscreenRenderer::getBackgroundColor () const
Returns the background color.
Definition at line 494 of file SoFCOffscreenRenderer.cpp.
References PRIVATE.
getGLRenderAction()
SoGLRenderAction * SoQtOffscreenRenderer::getGLRenderAction () const
Returns the rendering action currently used.
Definition at line 518 of file SoFCOffscreenRenderer.cpp.
References PRIVATE.
getNumPasses()
int SoQtOffscreenRenderer::getNumPasses () const
Definition at line 530 of file SoFCOffscreenRenderer.cpp.
References PRIVATE.
getViewportRegion()
const SbViewportRegion & SoQtOffscreenRenderer::getViewportRegion () const
Returns the viewerport region.
Definition at line 472 of file SoFCOffscreenRenderer.cpp.
References PRIVATE.
getWriteImageFiletypeInfo()
QStringList SoQtOffscreenRenderer::getWriteImageFiletypeInfo () const
This method returns all image file formats supported by Coin3D (see getWriteFiletypeInfo()) with all QImage file formats that are not directly supported by Coin3D, if so.
Definition at line 736 of file SoFCOffscreenRenderer.cpp.
Referenced by StdViewScreenShot::activated().
internalTextureFormat()
GLenum SoQtOffscreenRenderer::internalTextureFormat () const
Definition at line 542 of file SoFCOffscreenRenderer.cpp.
References PRIVATE.
Referenced by setInternalTextureFormat().
render() [1/2]
SbBool SoQtOffscreenRenderer::render (SoNode * scene)
Render the scenegraph rooted at scene into our internal pixel buffer.
Important note: make sure you pass in a scene node pointer which has both a camera and at least one lightsource below it – otherwise you are likely to end up with just a blank or black image buffer.
This mistake is easily made if you use an SoQtOffscreenRenderer on a scenegraph from one of the standard viewer components, as you will often just leave the addition of a camera and a headlight lightsource to the viewer to set up. This camera and lightsource are then part of the viewer's private "super-graph" outside of the scope of the scenegraph passed in by the application programmer. To make sure the complete scenegraph (including the viewer's "private parts" (snicker)) are passed to this method, you can get the scenegraph root from the viewer's internal SoSceneManager instance instead of from the viewer's own getSceneGraph() method, like this:
SoQtOffscreenRenderer * myRenderer = new SoQtOffscreenRenderer(vpregion);
SoNode * root = myViewer->getSceneManager()->getSceneGraph();
SbBool ok = myRenderer->render(root);
// [then use image buffer in a texture, or write it to file, or whatever]
If you do this and still get a blank buffer, another common problem is to have a camera which is not actually pointing at the scene geometry you want a snapshot of. If you suspect that could be the cause of problems on your end, take a look at SoCamera::pointAt() and SoCamera::viewAll() to see how you can make a camera node guaranteed to be directed at the scene geometry.
Yet another common mistake when setting up the camera is to specify values for the SoCamera::nearDistance and SoCamera::farDistance fields which doesn't not enclose the full scene. This will result in either just the background color, or that parts at the front or the back of the scene will not be visible in the rendering.
See also
writeToImage()
Definition at line 683 of file SoFCOffscreenRenderer.cpp.
References PRIVATE.
Referenced by MeshGui::ThumbnailExtension3MF::addMesh(), MeshGui::ViewProviderMesh::getVisibleFacets(), and Gui::View3DInventorViewer::savePicture().
render() [2/2]
SbBool SoQtOffscreenRenderer::render (SoPath * scene)
Render the scene path into our internal memory buffer.
Definition at line 692 of file SoFCOffscreenRenderer.cpp.
References PRIVATE.
setBackgroundColor()
void SoQtOffscreenRenderer::setBackgroundColor (const SbColor4f & color)
Sets the background color. The buffer is cleared to this color before rendering.
Definition at line 482 of file SoFCOffscreenRenderer.cpp.
References PRIVATE.
Referenced by MeshGui::ThumbnailExtension3MF::addMesh(), MeshGui::ViewProviderMesh::getVisibleFacets(), and Gui::View3DInventorViewer::savePicture().
setGLRenderAction()
void SoQtOffscreenRenderer::setGLRenderAction (SoGLRenderAction * action)
Sets the render action. Use this if you have special rendering needs.
Definition at line 503 of file SoFCOffscreenRenderer.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and PRIVATE.
setInternalTextureFormat()
void SoQtOffscreenRenderer::setInternalTextureFormat (GLenum internalTextureFormat)
Definition at line 536 of file SoFCOffscreenRenderer.cpp.
References internalTextureFormat(), and PRIVATE.
Referenced by Gui::View3DInventorViewer::savePicture().
setNumPasses()
void SoQtOffscreenRenderer::setNumPasses (const int num)
Definition at line 524 of file SoFCOffscreenRenderer.cpp.
References PRIVATE.
Referenced by Gui::View3DInventorViewer::savePicture().
setViewportRegion()
void SoQtOffscreenRenderer::setViewportRegion (const SbViewportRegion & region)
Sets the viewport region.
This will invalidate the current buffer, if any. The buffer will not contain valid data until another call to SoOffscreenRendererQt::render() happens.
Definition at line 463 of file SoFCOffscreenRenderer.cpp.
References PRIVATE.
Referenced by Gui::SoQtOffscreenRendererPy::setViewportRegion().
writeToImage()
void SoQtOffscreenRenderer::writeToImage (QImage & img) const
Writes the rendered image buffer directly into a QImage object.
Definition at line 701 of file SoFCOffscreenRenderer.cpp.
References src.Mod.PartDesign.Scripts.Gear::c1, PRIVATE, MovieTool::x, and MovieTool::y.
Referenced by MeshGui::ThumbnailExtension3MF::addMesh(), MeshGui::ViewProviderMesh::getVisibleFacets(), and Gui::View3DInventorViewer::savePicture().
The documentation for this class was generated from the following files:
SoFCOffscreenRenderer.h
SoFCOffscreenRenderer.cpp