FreeCAD: Gui::PolyPickerSelection Class Reference
Gui::PolyPickerSelection Class Reference
#include <MouseSelection.h>
Public Member Functions
PolyPickerSelection ()
~PolyPickerSelection () override
void setLineWidth (float l)
void setColor (float r, float g, float b, float a=1.0)
void initialize () override
implement this in derived classes
void terminate (bool abort=false) override
implement this in derived classes
Public Member Functions inherited from Gui::BaseMouseSelection
BaseMouseSelection ()
~BaseMouseSelection () override=default
Public Member Functions inherited from Gui::AbstractMouseSelection
AbstractMouseSelection ()
virtual ~AbstractMouseSelection ()=default
void grabMouseModel (Gui::View3DInventorViewer *)
void releaseMouseModel (bool abort=false)
const std::vector< SbVec2s > & getPositions () const
SelectionRole selectedRole () const
int handleEvent (const SoEvent *const ev, const SbViewportRegion &vp)
Protected Member Functions
int mouseButtonEvent (const SoMouseButtonEvent *const e, const QPoint &pos) override
int locationEvent (const SoLocation2Event *const e, const QPoint &pos) override
int keyboardEvent (const SoKeyboardEvent *const e) override
void draw () override
draw the polygon
virtual int popupMenu ()
Protected Member Functions inherited from Gui::AbstractMouseSelection
Protected Attributes
Gui::Polyline polyline
bool lastConfirmed
Protected Attributes inherited from Gui::AbstractMouseSelection
Gui::View3DInventorViewer * _pcView3D {nullptr}
QCursor m_cPrevCursor
int m_iXold
int m_iYold
int m_iXnew
int m_iYnew
SelectionRole m_selectedRole
std::vector< SbVec2s > _clPoly
Additional Inherited Members
Public Types inherited from Gui::AbstractMouseSelection
enum {
Continue =0, Restart =1, Finish =2, Cancel =3,
Ignore =4
}
Detailed Description
The poly picker mouse selection class Create a polygon
Author
Werner Mayer
Definition at line 124 of file MouseSelection.h.
Constructor & Destructor Documentation
PolyPickerSelection()
PolyPickerSelection::PolyPickerSelection ()
Definition at line 160 of file MouseSelection.cpp.
References lastConfirmed.
~PolyPickerSelection()
PolyPickerSelection::~PolyPickerSelection () override default
Member Function Documentation
draw()
void PolyPickerSelection::draw () override protected virtual
draw the polygon
Reimplemented from Gui::AbstractMouseSelection.
Definition at line 200 of file MouseSelection.cpp.
References Gui::AbstractMouseSelection::_pcView3D, and SIM::Coin3D::Quarter::QuarterWidget::redraw().
Referenced by locationEvent(), and Gui::FreehandSelection::locationEvent().
initialize()
void PolyPickerSelection::initialize () override virtual
implement this in derived classes
Implements Gui::AbstractMouseSelection.
Definition at line 175 of file MouseSelection.cpp.
References Gui::AbstractMouseSelection::_pcView3D, Gui::View3DInventorViewer::addGraphicsItem(), cursor_cut_scissors, SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getWidget(), Gui::View3DInventorViewer::Image, lastConfirmed, buildPsets::p, polyline, SIM::Coin3D::Quarter::QuarterWidget::redraw(), Gui::View3DInventorViewer::setRenderType(), and Gui::Polyline::setViewer().
keyboardEvent()
int PolyPickerSelection::keyboardEvent (const SoKeyboardEvent *const e) override protected virtual
Reimplemented from Gui::AbstractMouseSelection.
Definition at line 346 of file MouseSelection.cpp.
References Gui::AbstractMouseSelection::Continue.
locationEvent()
int PolyPickerSelection::locationEvent (const SoLocation2Event *const e, const QPoint & pos) override protected virtual
Reimplemented from Gui::AbstractMouseSelection.
Reimplemented in Gui::FreehandSelection.
Definition at line 294 of file MouseSelection.cpp.
References Gui::AbstractMouseSelection::_pcView3D, Gui::Polyline::addNode(), Gui::AbstractMouseSelection::Continue, draw(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getGLWidget(), Gui::Polyline::isWorking(), lastConfirmed, Gui::AbstractMouseSelection::m_iXnew, Gui::AbstractMouseSelection::m_iYnew, polyline, Gui::Polyline::popNode(), and RobotExample::pos.
mouseButtonEvent()
int PolyPickerSelection::mouseButtonEvent (const SoMouseButtonEvent *const e, const QPoint & pos) override protected virtual
Reimplemented from Gui::AbstractMouseSelection.
Reimplemented in Gui::FreehandSelection.
Definition at line 231 of file MouseSelection.cpp.
References Gui::AbstractMouseSelection::_pcView3D, Gui::Polyline::addNode(), Gui::AbstractMouseSelection::Cancel, Gui::Polyline::clear(), Gui::AbstractMouseSelection::Continue, SCL.SimpleDataTypes::e, Gui::AbstractMouseSelection::Finish, SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getWidget(), SplineSurface::id, Gui::Polyline::isWorking(), lastConfirmed, Gui::AbstractMouseSelection::m_cPrevCursor, Gui::AbstractMouseSelection::m_iXnew, Gui::AbstractMouseSelection::m_iXold, Gui::AbstractMouseSelection::m_iYnew, Gui::AbstractMouseSelection::m_iYold, polyline, popupMenu(), RobotExample::pos, Gui::AbstractMouseSelection::releaseMouseModel(), Gui::AbstractMouseSelection::Restart, and Gui::Polyline::setWorking().
popupMenu()
int PolyPickerSelection::popupMenu () protected virtual
Reimplemented in Gui::FreehandSelection, and Gui::PolyClipSelection.
Definition at line 207 of file MouseSelection.cpp.
References Gui::AbstractMouseSelection::Cancel, Gui::AbstractMouseSelection::Finish, Gui::AbstractMouseSelection::getPositions(), NavigationIndicatorGui::menu, RobotExample::pos, and Gui::AbstractMouseSelection::Restart.
Referenced by mouseButtonEvent().
setColor()
void PolyPickerSelection::setColor (float r, float g, float b, float a = 1.0)
Definition at line 165 of file MouseSelection.cpp.
References a, SCL.SimpleDataTypes::b, toolbit-attributes::g, polyline, and Gui::Polyline::setColor().
Referenced by MeshGui::MeshSelection::prepareFreehandSelection().
setLineWidth()
void PolyPickerSelection::setLineWidth (float l)
Definition at line 170 of file MouseSelection.cpp.
References RobotExample::l, polyline, and Gui::Polyline::setLineWidth().
Referenced by MeshGui::MeshSelection::prepareFreehandSelection().
terminate()
void PolyPickerSelection::terminate (bool abort = false) override virtual
implement this in derived classes
Implements Gui::AbstractMouseSelection.
Definition at line 191 of file MouseSelection.cpp.
References Gui::AbstractMouseSelection::_pcView3D, Gui::View3DInventorViewer::Native, polyline, SIM::Coin3D::Quarter::QuarterWidget::redraw(), Gui::View3DInventorViewer::removeGraphicsItem(), and Gui::View3DInventorViewer::setRenderType().
Referenced by src.Mod.AddonManager.addonmanager_workers_startup.CacheMacroCodeWorker::update_and_advance().
Member Data Documentation
lastConfirmed
bool Gui::PolyPickerSelection::lastConfirmed protected
Definition at line 147 of file MouseSelection.h.
Referenced by initialize(), locationEvent(), mouseButtonEvent(), and PolyPickerSelection().
polyline
Gui::Polyline Gui::PolyPickerSelection::polyline protected
Definition at line 146 of file MouseSelection.h.
Referenced by initialize(), locationEvent(), Gui::FreehandSelection::locationEvent(), mouseButtonEvent(), Gui::FreehandSelection::mouseButtonEvent(), Gui::FreehandSelection::setClosed(), setColor(), setLineWidth(), terminate(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_tile_coloured_region::wr1(), config_control_design.advanced_face::wr10(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.advanced_face::wr10(), and automotive_design.advanced_face::wr10().
The documentation for this class was generated from the following files:
MouseSelection.h
MouseSelection.cpp