FreeCAD: ParameterSerializer Class Reference
ParameterSerializer Class Reference
#include <Parameter.h>
Public Member Functions
ParameterSerializer (std::string fn)
ParameterSerializer (const ParameterSerializer &)=delete
ParameterSerializer (ParameterSerializer &&)=delete
virtual ~ParameterSerializer ()
virtual void SaveDocument (const ParameterManager &)
virtual int LoadDocument (ParameterManager &)
virtual bool LoadOrCreateDocument (ParameterManager &)
const std::string & GetFileName () const
ParameterSerializer & operator= (const ParameterSerializer &)=delete
ParameterSerializer & operator= (ParameterSerializer &&)=delete
Detailed Description
The parameter serializer class This is a helper class to serialize a parameter XML document. Does loading and saving the DOM document from and to files. In sub-classes the load and saving of XML documents can be customized.
See also
ParameterManager
Definition at line 363 of file Parameter.h.
Constructor & Destructor Documentation
ParameterSerializer() [1/3]
ParameterSerializer::ParameterSerializer (std::string fn) explicit
Definition at line 1539 of file Parameter.cpp.
ParameterSerializer() [2/3]
ParameterSerializer::ParameterSerializer (const ParameterSerializer &) delete
ParameterSerializer() [3/3]
ParameterSerializer::ParameterSerializer (ParameterSerializer &&) delete
~ParameterSerializer()
ParameterSerializer::~ParameterSerializer () virtual default
Member Function Documentation
GetFileName()
const std::string& ParameterSerializer::GetFileName () const inline
Definition at line 374 of file Parameter.h.
Referenced by ParameterManager::GetSerializeFileName().
LoadDocument()
int ParameterSerializer::LoadDocument (ParameterManager & mgr) virtual
Definition at line 1550 of file Parameter.cpp.
References ParameterManager::LoadDocument().
Referenced by ParameterManager::LoadDocument().
LoadOrCreateDocument()
bool ParameterSerializer::LoadOrCreateDocument (ParameterManager & mgr) virtual
Definition at line 1555 of file Parameter.cpp.
References ParameterManager::LoadOrCreateDocument().
Referenced by ParameterManager::LoadOrCreateDocument().
operator=() [1/2]
ParameterSerializer& ParameterSerializer::operator= (const ParameterSerializer &) delete
operator=() [2/2]
ParameterSerializer& ParameterSerializer::operator= (ParameterSerializer &&) delete
SaveDocument()
void ParameterSerializer::SaveDocument (const ParameterManager & mgr) virtual
Definition at line 1545 of file Parameter.cpp.
References ParameterManager::SaveDocument().
Referenced by ParameterManager::SaveDocument().
The documentation for this class was generated from the following files:
Parameter.h
Parameter.cpp