FreeCAD: App::PropertyListsBase Class Reference
App::PropertyListsBase Class Reference abstract
#include <Property.h>
Public Member Functions
virtual void setSize (int newSize)=0
virtual int getSize () const =0
const std::set< int > & getTouchList () const
void clearTouchList ()
Protected Member Functions
virtual void setPyValues (const std::vector< PyObject * > &vals, const std::vector< int > &indices)
void _setPyObject (PyObject *)
Protected Attributes
std::set< int > _touchList
Detailed Description
Helper class to construct list like properties
This class is not derived from Property so that we can have more that one base class for list like properties, e.g. see PropertyList, and PropertyLinkListBase
Definition at line 469 of file Property.h.
Member Function Documentation
_setPyObject()
void PropertyListsBase::_setPyObject (PyObject * value) protected
Definition at line 362 of file Property.cpp.
References Path.Base.SetupSheet::dict, getSize(), and setPyValues().
clearTouchList()
void App::PropertyListsBase::clearTouchList () inline
Definition at line 480 of file Property.h.
getSize()
virtual int App::PropertyListsBase::getSize () const pure virtual
Implemented in TechDraw::PropertyCosmeticVertexList, TechDraw::PropertyCosmeticEdgeList, App::PropertyListsT< T, ListT, ParentT >, Part::PropertyFilletEdges, Points::PropertyCurvatureList, Inspection::PropertyDistanceList, Part::PropertyShapeHistory, Mesh::PropertyCurvatureList, Points::PropertyNormalList, Mesh::PropertyNormalList, Points::PropertyGreyValueList, Sketcher::PropertyConstraintList, Part::PropertyTopoShapeList, Part::PropertyGeometryList, TechDraw::PropertyGeomFormatList, and TechDraw::PropertyCenterLineList.
Referenced by _setPyObject().
getTouchList()
const std::set<int>& App::PropertyListsBase::getTouchList () const inline
Definition at line 475 of file Property.h.
setPyValues()
virtual void App::PropertyListsBase::setPyValues (const std::vector< PyObject * > & vals, const std::vector< int > & indices) inline protected virtual
Reimplemented in App::PropertyListsT< T, ListT, ParentT >, App::PropertyListsT< long >, App::PropertyListsT< Base::Vector3d >, App::PropertyListsT< double >, App::PropertyListsT< Color >, App::PropertyListsT< std::string >, App::PropertyListsT< bool, boost::dynamic_bitset<> >, App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >, App::PropertyListsT< Material >, App::PropertyListsT< Base::Placement >, and App::PropertyListsT< VisualLayer >.
Definition at line 486 of file Property.h.
Referenced by _setPyObject().
setSize()
virtual void App::PropertyListsBase::setSize (int newSize) pure virtual
Implemented in App::PropertyLinkList, App::PropertyListsT< T, ListT, ParentT >, App::PropertyListsT< long >, App::PropertyListsT< Base::Vector3d >, App::PropertyListsT< double >, App::PropertyListsT< Color >, App::PropertyListsT< std::string >, App::PropertyListsT< bool, boost::dynamic_bitset<> >, App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >, App::PropertyListsT< Material >, App::PropertyListsT< Base::Placement >, App::PropertyListsT< VisualLayer >, Part::PropertyFilletEdges, Points::PropertyCurvatureList, Inspection::PropertyDistanceList, Part::PropertyShapeHistory, Mesh::PropertyCurvatureList, Points::PropertyNormalList, Mesh::PropertyNormalList, Points::PropertyGreyValueList, Sketcher::PropertyConstraintList, Part::PropertyTopoShapeList, TechDraw::PropertyCosmeticVertexList, Part::PropertyGeometryList, TechDraw::PropertyCosmeticEdgeList, TechDraw::PropertyGeomFormatList, and TechDraw::PropertyCenterLineList.
Member Data Documentation
_touchList
std::set<int> App::PropertyListsBase::_touchList protected
Definition at line 496 of file Property.h.
Referenced by App::PropertyListsT< VisualLayer >::set1Value(), and App::PropertyListsT< VisualLayer >::setValues().
The documentation for this class was generated from the following files:
Property.h
Property.cpp