FreeCAD: TopoShapePyImp.cpp File Reference
TopoShapePyImp.cpp File Reference
#include "PreCompiled.h"
#include <sstream>
#include <boost/regex.hpp>
#include <BRep_Tool.hxx>
#include <BRepAlgo_NormalProjection.hxx>
#include <BRepBndLib.hxx>
#include <BRepBuilderAPI_Copy.hxx>
#include <BRepBuilderAPI_MakeVertex.hxx>
#include <BRepBuilderAPI_Transform.hxx>
#include <BRepClass3d_SolidClassifier.hxx>
#include <BRepExtrema_DistShapeShape.hxx>
#include <BRepExtrema_ShapeProximity.hxx>
#include <BRepExtrema_SupportType.hxx>
#include <BRepFilletAPI_MakeChamfer.hxx>
#include <BRepFilletAPI_MakeFillet.hxx>
#include <BRepGProp.hxx>
#include <BRepMesh_IncrementalMesh.hxx>
#include <BRepProj_Projection.hxx>
#include <BRepTools.hxx>
#include <Geom_Plane.hxx>
#include <gp_Ax1.hxx>
#include <gp_Ax2.hxx>
#include <gp_Dir.hxx>
#include <gp_Pln.hxx>
#include <gp_Pnt.hxx>
#include <gp_Trsf.hxx>
#include <GProp_GProps.hxx>
#include <HLRAppli_ReflectLines.hxx>
#include <Precision.hxx>
#include <Poly_Polygon3D.hxx>
#include <Poly_Triangulation.hxx>
#include <ShapeAnalysis_ShapeTolerance.hxx>
#include <ShapeFix_ShapeTolerance.hxx>
#include <Standard_Version.hxx>
#include <TopExp.hxx>
#include <TopExp_Explorer.hxx>
#include <TopLoc_Location.hxx>
#include <TopoDS.hxx>
#include <TopoDS_Iterator.hxx>
#include <TopTools_IndexedMapOfShape.hxx>
#include <TopTools_ListIteratorOfListOfShape.hxx>
#include <TopTools_ListOfShape.hxx>
#include <App/PropertyStandard.h>
#include <App/StringHasherPy.h>
#include <Base/FileInfo.h>
#include <Base/GeometryPyCXX.h>
#include <Base/MatrixPy.h>
#include <Base/PyWrapParseTupleAndKeywords.h>
#include <Base/Rotation.h>
#include <Base/Stream.h>
#include <Base/Tools.h>
#include <Base/Vector3D.h>
#include <Base/VectorPy.h>
#include <Mod/Part/App/TopoShapePy.h>
#include <Mod/Part/App/TopoShapePy.cpp>
#include <Mod/Part/App/GeometryPy.h>
#include <Mod/Part/App/PlanePy.h>
#include <Mod/Part/App/TopoShapeCompoundPy.h>
#include <Mod/Part/App/TopoShapeCompSolidPy.h>
#include <Mod/Part/App/TopoShapeEdgePy.h>
#include <Mod/Part/App/TopoShapeFacePy.h>
#include <Mod/Part/App/TopoShapeOpCode.h>
#include <Mod/Part/App/TopoShapeShellPy.h>
#include <Mod/Part/App/TopoShapeSolidPy.h>
#include <Mod/Part/App/TopoShapeVertexPy.h>
#include <Mod/Part/App/TopoShapeWirePy.h>
#include "OCCError.h"
#include "PartPyCXX.h"
#include "ShapeMapHasher.h"
#include "TopoShapeMapper.h"
Classes
struct TopoShapePyInit
struct PyShapeMapper
Namespaces
Part
Functions
static Py_hash_t _TopoShapeHash (PyObject *self)
static PyObject * makeShape (const char *op, const TopoShape &shape, PyObject *args)
static const std::map< PyTypeObject *, TopAbs_ShapeEnum > Part::mapTypeShape (vecTypeShape.begin(), vecTypeShape.end())
static TopAbs_ShapeEnum Part::ShapeTypeFromPyType (PyTypeObject *pyType)
PyObject * _getSupportIndex (const char *suppStr, TopoShape *ts, TopoDS_Shape suppShape)
static Py::List getElements (const TopoShape &sh, TopAbs_ShapeEnum type, TopAbs_ShapeEnum avoid=TopAbs_SHAPE)
Variables
struct TopoShapePyInit _TopoShapePyInit
static const std::vector< std::pair< PyTypeObject *, TopAbs_ShapeEnum > > Part::vecTypeShape
Function Documentation
_getSupportIndex()
PyObject* _getSupportIndex (const char * suppStr, TopoShape * ts, TopoDS_Shape suppShape)
Definition at line 2067 of file TopoShapePyImp.cpp.
References src.Mod.Test.UnitTests::ts().
_TopoShapeHash()
static Py_hash_t _TopoShapeHash (PyObject * self) static
Definition at line 104 of file TopoShapePyImp.cpp.
References femsolver.elmer.sifio::isValid().
Referenced by TopoShapePyInit::TopoShapePyInit().
getElements()
static Py::List getElements (const TopoShape & sh, TopAbs_ShapeEnum type, TopAbs_ShapeEnum avoid = TopAbs_SHAPE) static
Definition at line 2536 of file TopoShapePyImp.cpp.
References Part::TopoShape::getSubTopoShapes(), Part::shape2pyshape(), and Path.Post.scripts.grbl_post::type.
makeShape()
static PyObject* makeShape (const char * op, const TopoShape & shape, PyObject * args) static
Definition at line 676 of file TopoShapePyImp.cpp.
References toolbit-attributes::args, Part::getPyShapes(), Py::new_reference_to(), PY_CATCH_OCC, PY_TRY, and Part::shape2pyshape().
Referenced by PartDesign::Point::onDocumentRestored(), and PartDesign::Point::Point().
Variable Documentation
_TopoShapePyInit
struct TopoShapePyInit _TopoShapePyInit