FreeCAD: SpreadsheetGui::SheetViewPy Class Reference
SpreadsheetGui::SheetViewPy Class Reference
#include <SpreadsheetView.h>
Public Types
using BaseType = Py::PythonExtension< SheetViewPy >
Public Member Functions
SheetViewPy (SheetView *mdi)
~SheetViewPy () override
Py::Object repr () override
Py::Object getattr (const char *) override
Py::Object getSheet (const Py::Tuple &)
Py::Object cast_to_base (const Py::Tuple &)
Py::Object selectedRanges (const Py::Tuple &)
Py::Object selectedCells (const Py::Tuple &)
Py::Object select (const Py::Tuple &)
Py::Object currentIndex (const Py::Tuple &)
Py::Object setCurrentIndex (const Py::Tuple &)
SheetView * getSheetViewPtr ()
Static Public Member Functions
static void init_type ()
Protected Attributes
Gui::MDIViewPy base
Detailed Description
Definition at line 144 of file SpreadsheetView.h.
Member Typedef Documentation
BaseType
using SpreadsheetGui::SheetViewPy::BaseType = Py::PythonExtension<SheetViewPy>
Definition at line 147 of file SpreadsheetView.h.
Constructor & Destructor Documentation
SheetViewPy()
SheetViewPy::SheetViewPy (SheetView * mdi) explicit
Definition at line 632 of file SpreadsheetView.cpp.
~SheetViewPy()
SheetViewPy::~SheetViewPy () override default
Member Function Documentation
cast_to_base()
Py::Object SheetViewPy::cast_to_base (const Py::Tuple &)
Definition at line 691 of file SpreadsheetView.cpp.
References Gui::MDIViewPy::create().
Referenced by init_type().
currentIndex()
Py::Object SheetViewPy::currentIndex (const Py::Tuple & args)
Definition at line 763 of file SpreadsheetView.cpp.
References toolbit-attributes::args, SpreadsheetGui::SheetView::currentIndex(), getSheetViewPtr(), Path.Post.scripts.refactored_centroid_post::str, src.Mod.Test.testmakeWireString::String, and App::CellAddress::toString().
Referenced by init_type().
getattr()
Py::Object SheetViewPy::getattr (const char * attr) override
Definition at line 652 of file SpreadsheetView.cpp.
References SCL.SimpleDataTypes::e, and getSheetViewPtr().
getSheet()
Py::Object SheetViewPy::getSheet (const Py::Tuple & args)
Definition at line 683 of file SpreadsheetView.cpp.
References toolbit-attributes::args, and getSheetViewPtr().
Referenced by init_type().
getSheetViewPtr()
SheetView * SheetViewPy::getSheetViewPtr ()
Definition at line 678 of file SpreadsheetView.cpp.
Referenced by currentIndex(), getattr(), getSheet(), repr(), select(), selectedCells(), selectedRanges(), and setCurrentIndex().
init_type()
void SheetViewPy::init_type () static
Definition at line 596 of file SpreadsheetView.cpp.
References cast_to_base(), currentIndex(), getSheet(), select(), selectedCells(), selectedRanges(), and setCurrentIndex().
Referenced by PyMOD_INIT_FUNC().
repr()
Py::Object SheetViewPy::repr () override
Definition at line 638 of file SpreadsheetView.cpp.
References getSheetViewPtr(), and src.Mod.Test.testmakeWireString::String.
select()
Py::Object SheetViewPy::select (const Py::Tuple & _args)
Definition at line 726 of file SpreadsheetView.cpp.
References toolbit-attributes::args, getSheetViewPtr(), and SpreadsheetGui::SheetView::select().
Referenced by init_type().
selectedCells()
Py::Object SheetViewPy::selectedCells (const Py::Tuple & args)
Definition at line 711 of file SpreadsheetView.cpp.
References toolbit-attributes::args, getSheetViewPtr(), SpreadsheetGui::SheetView::selectedIndexes(), src.Mod.Test.testmakeWireString::String, and App::CellAddress::toString().
Referenced by init_type().
selectedRanges()
Py::Object SheetViewPy::selectedRanges (const Py::Tuple & args)
Definition at line 696 of file SpreadsheetView.cpp.
References toolbit-attributes::args, getSheetViewPtr(), SpreadsheetGui::SheetView::selectedRanges(), and src.Mod.Test.testmakeWireString::String.
Referenced by init_type().
setCurrentIndex()
Py::Object SheetViewPy::setCurrentIndex (const Py::Tuple & args)
Definition at line 774 of file SpreadsheetView.cpp.
References toolbit-attributes::args, getSheetViewPtr(), and SpreadsheetGui::SheetView::setCurrentIndex().
Referenced by init_type(), and src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::retranslateUi().
Member Data Documentation
base
Gui::MDIViewPy SpreadsheetGui::SheetViewPy::base protected
Definition at line 167 of file SpreadsheetView.h.
Referenced by bimcommands.BimCutPlane.CutPlaneTaskPanel::previewCutVolume(), and automotive_design.mechanism_base_placement::representation_relationship_rep_2().
The documentation for this class was generated from the following files:
SpreadsheetView.h
SpreadsheetView.cpp