FreeCAD: MatGui::BaseDelegate Class Reference
MatGui::BaseDelegate Class Reference abstract
#include <BaseDelegate.h>
Public Member Functions
BaseDelegate (QObject *parent=nullptr)
virtual ~BaseDelegate ()=default
QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const override
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const override
QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &styleOption, const QModelIndex &index) const override
void setEditorData (QWidget *editor, const QModelIndex &index) const override
void setModelData (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const override
Protected Member Functions
virtual Materials::MaterialValue::ValueType getType (const QModelIndex &index) const =0
virtual QString getUnits (const QModelIndex &index) const =0
virtual QVariant getValue (const QModelIndex &index) const =0
virtual void setValue (QAbstractItemModel *model, const QModelIndex &index, const QVariant &value) const =0
virtual void notifyChanged (const QAbstractItemModel *model, const QModelIndex &index) const =0
QString getStringValue (const QModelIndex &index) const
QRgb parseColor (const QString &color) const
void paintQuantity (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
void paintImage (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
void paintSVG (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
void paintColor (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
void paintList (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
void paintMultiLineString (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
void paintArray (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual bool newRow (const QAbstractItemModel *model, const QModelIndex &index) const
QWidget * createWidget (QWidget *parent, const QVariant &item, const QModelIndex &index) const
Detailed Description
Definition at line 58 of file BaseDelegate.h.
Constructor & Destructor Documentation
BaseDelegate()
BaseDelegate::BaseDelegate (QObject * parent = nullptr)
Definition at line 57 of file BaseDelegate.cpp.
~BaseDelegate()
virtual MatGui::BaseDelegate::~BaseDelegate () virtual default
Member Function Documentation
createEditor()
QWidget * BaseDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & styleOption, const QModelIndex & index) const override
Definition at line 388 of file BaseDelegate.cpp.
References createWidget(), Path.Post.Utils::editor(), getValue(), newRow(), and Init::parent.
createWidget()
QWidget * BaseDelegate::createWidget (QWidget * parent, const QVariant & item, const QModelIndex & index) const protected
Definition at line 409 of file BaseDelegate.cpp.
References Materials::MaterialValue::Boolean, draftgeoutils.intersections::connect(), Materials::MaterialValue::File, Materials::MaterialValue::FileList, Gui::FileChooser::fileNameChanged(), Gui::FileChooser::fileNameSelected(), Materials::MaterialValue::Float, getType(), getUnits(), Materials::MaterialValue::Integer, KDL::max(), KDL::min(), Init::parent, Materials::MaterialValue::Quantity, setModelData(), and Path.Post.scripts.grbl_post::type.
Referenced by createEditor().
getStringValue()
QString BaseDelegate::getStringValue (const QModelIndex & index) const protected
Definition at line 67 of file BaseDelegate.cpp.
References getValue().
Referenced by paintColor(), paintImage(), and paintSVG().
getType()
virtual Materials::MaterialValue::ValueType MatGui::BaseDelegate::getType (const QModelIndex & index) const protected pure virtual
Emits this signal when a property has changed
Implemented in MatGui::MaterialDelegate, and MatGui::ListDelegate.
Referenced by createWidget(), paint(), setEditorData(), setModelData(), and sizeHint().
getUnits()
virtual QString MatGui::BaseDelegate::getUnits (const QModelIndex & index) const protected pure virtual
Implemented in MatGui::MaterialDelegate, and MatGui::ListDelegate.
Referenced by createWidget().
getValue()
virtual QVariant MatGui::BaseDelegate::getValue (const QModelIndex & index) const protected pure virtual
Implemented in MatGui::MaterialDelegate, and MatGui::ListDelegate.
Referenced by createEditor(), getStringValue(), paintQuantity(), and setEditorData().
newRow()
bool BaseDelegate::newRow (const QAbstractItemModel * model, const QModelIndex & index) const protected virtual
Reimplemented in MatGui::MaterialDelegate.
Definition at line 61 of file BaseDelegate.cpp.
Referenced by createEditor(), and paintQuantity().
notifyChanged()
virtual void MatGui::BaseDelegate::notifyChanged (const QAbstractItemModel * model, const QModelIndex & index) const protected pure virtual
Implemented in MatGui::MaterialDelegate, and MatGui::ListDelegate.
Referenced by setModelData().
paint()
void BaseDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const override
Definition at line 252 of file BaseDelegate.cpp.
References Materials::MaterialValue::Array2D, Materials::MaterialValue::Array3D, Materials::MaterialValue::Color, Materials::MaterialValue::FileList, getType(), Materials::MaterialValue::Image, Materials::MaterialValue::ImageList, Materials::MaterialValue::List, Materials::MaterialValue::MultiLineString, paintArray(), paintColor(), paintImage(), paintList(), paintMultiLineString(), paintQuantity(), paintSVG(), Materials::MaterialValue::Quantity, Materials::MaterialValue::SVG, and Path.Post.scripts.grbl_post::type.
paintArray()
void BaseDelegate::paintArray (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const protected
Definition at line 231 of file BaseDelegate.cpp.
Referenced by paint(), and MatGui::MaterialDelegate::paint().
paintColor()
void BaseDelegate::paintColor (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const protected
Definition at line 160 of file BaseDelegate.cpp.
References getStringValue(), and parseColor().
Referenced by paint(), and MatGui::MaterialDelegate::paint().
paintImage()
void BaseDelegate::paintImage (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const protected
Definition at line 118 of file BaseDelegate.cpp.
References getStringValue().
Referenced by paint(), MatGui::ListDelegate::paint(), and MatGui::MaterialDelegate::paint().
paintList()
void BaseDelegate::paintList (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const protected
Definition at line 189 of file BaseDelegate.cpp.
Referenced by paint(), and MatGui::MaterialDelegate::paint().
paintMultiLineString()
void BaseDelegate::paintMultiLineString (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const protected
Definition at line 210 of file BaseDelegate.cpp.
Referenced by paint(), and MatGui::MaterialDelegate::paint().
paintQuantity()
void BaseDelegate::paintQuantity (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const protected
Definition at line 95 of file BaseDelegate.cpp.
References getValue(), and newRow().
Referenced by paint(), MatGui::ListDelegate::paint(), and MatGui::MaterialDelegate::paint().
paintSVG()
void BaseDelegate::paintSVG (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const protected
Definition at line 143 of file BaseDelegate.cpp.
References getStringValue().
Referenced by paint(), and MatGui::MaterialDelegate::paint().
parseColor()
QRgb BaseDelegate::parseColor (const QString & color) const protected
Definition at line 75 of file BaseDelegate.cpp.
References blue, green, src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression, and red.
Referenced by paintColor().
setEditorData()
void BaseDelegate::setEditorData (QWidget * editor, const QModelIndex & index) const override
Definition at line 312 of file BaseDelegate.cpp.
References Path.Post.Utils::editor(), Materials::MaterialValue::File, Materials::MaterialValue::FileList, getType(), getValue(), Materials::MaterialValue::ImageList, Materials::MaterialValue::List, Materials::MaterialValue::Quantity, Gui::FileChooser::setFileName(), Gui::QuantitySpinBox::setValue(), and Path.Post.scripts.grbl_post::type.
setModelData()
void BaseDelegate::setModelData (QWidget * editor, QAbstractItemModel * model, const QModelIndex & index) const override
Definition at line 344 of file BaseDelegate.cpp.
References Materials::MaterialValue::Boolean, Path.Post.Utils::editor(), Materials::MaterialValue::File, Materials::MaterialValue::FileList, Gui::FileChooser::fileName, Materials::MaterialValue::Float, getType(), Materials::MaterialValue::Image, Materials::MaterialValue::Integer, notifyChanged(), Materials::MaterialValue::Quantity, setValue(), Materials::MaterialValue::SVG, Path.Post.scripts.grbl_post::type, and Gui::QuantitySpinBox::value.
Referenced by createWidget().
setValue()
virtual void MatGui::BaseDelegate::setValue (QAbstractItemModel * model, const QModelIndex & index, const QVariant & value) const protected pure virtual
Implemented in MatGui::MaterialDelegate, and MatGui::ListDelegate.
Referenced by setModelData().
sizeHint()
QSize BaseDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex & index) const override
Definition at line 290 of file BaseDelegate.cpp.
References Materials::MaterialValue::Array2D, Materials::MaterialValue::Array3D, Materials::MaterialValue::Color, Materials::MaterialValue::FileList, getType(), Materials::MaterialValue::Image, Materials::MaterialValue::ImageList, Materials::MaterialValue::List, Materials::MaterialValue::MultiLineString, Materials::MaterialValue::SVG, and Path.Post.scripts.grbl_post::type.
The documentation for this class was generated from the following files:
BaseDelegate.h
BaseDelegate.cpp