FreeCAD: TechDraw::CosmeticVertex Class Reference
TechDraw::CosmeticVertex Class Reference
#include <CosmeticVertex.h>
Public Member Functions
CosmeticVertex ()
CosmeticVertex (const CosmeticVertex *cv)
CosmeticVertex (const Base::Vector3d &loc)
~CosmeticVertex () override=default
Base::Vector3d point () const
void point (Base::Vector3d newPoint)
void move (const Base::Vector3d &newPos)
void moveRelative (const Base::Vector3d &movement)
std::string toString () const
void dump (const char *title) override
Base::Vector3d scaled (const double factor)
Base::Vector3d rotatedAndScaled (const double scale, const double rotDegrees)
returns a transformed version of our coordinates (permaPoint)
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
PyObject * getPyObject () override
CosmeticVertex * copy () const
CosmeticVertex * clone () const
boost::uuids::uuid getTag () const
std::string getTagAsString () const override
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from TechDraw::Vertex
Vertex ()
Vertex (const Vertex *v)
Vertex (double x, double y)
Vertex (Base::Vector3d v)
virtual ~Vertex ()=default
bool isEqual (const Vertex &v, double tol)
Base::Vector3d point () const
void point (Base::Vector3d v)
double x ()
double y ()
boost::uuids::uuid getTag () const
bool getHlrVisible ()
void setHlrVisible (bool state)
int getRef3d ()
void setRef3d (int ref)
TopoDS_Vertex getOCCVertex ()
void setOCCVertex (TopoDS_Vertex newVertex)
bool getCosmetic ()
void setCosmetic (bool state)
std::string getCosmeticTag ()
void setCosmeticTag (std::string t)
bool isCenter ()
void isCenter (bool state)
bool isReference ()
void isReference (bool state)
Part::TopoShape asTopoShape (double scale=1.0)
Static Public Member Functions
static Base::Vector3d makeCanonicalPoint (DrawViewPart *dvp, Base::Vector3d point, bool unscale=true)
static Base::Vector3d makeCanonicalPointInverted (DrawViewPart *dvp, Base::Vector3d invertedPoint, bool unscale=true)
a version of makeCanonicalPoint that accepts and returns an invertedPoint.
static bool restoreCosmetic ()
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes
Base::Vector3d permaPoint {Base::Vector3d()}
int linkGeom {-1}
App::Color color {App::Color()}
double size {1.0}
int style {1}
bool visible {true}
Protected Member Functions
void createNewTag ()
void assignTag (const TechDraw::CosmeticVertex *cv)
Protected Member Functions inherited from TechDraw::Vertex
void createNewTag ()
void assignTag (const TechDraw::Vertex *v)
Protected Attributes
boost::uuids::uuid tag
Py::Object PythonObject
Protected Attributes inherited from TechDraw::Vertex
Base::Vector3d pnt
ExtractionType extractType
bool hlrVisible
int ref3D
bool m_center
TopoDS_Vertex occVertex
bool cosmetic
int cosmeticLink
std::string cosmeticTag
bool m_reference
boost::uuids::uuid tag
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 40 of file CosmeticVertex.h.
Constructor & Destructor Documentation
CosmeticVertex() [1/3]
CosmeticVertex::CosmeticVertex ()
Definition at line 52 of file CosmeticVertex.cpp.
References TechDraw::LineGroup::getDefaultWidth(), TechDraw::Preferences::vertexColor(), and TechDraw::Preferences::vertexScale().
Referenced by copy().
CosmeticVertex() [2/3]
CosmeticVertex::CosmeticVertex (const CosmeticVertex * cv)
Definition at line 63 of file CosmeticVertex.cpp.
References color, TechDraw::Vertex::cosmetic, createNewTag(), TechDraw::Vertex::hlrVisible, linkGeom, permaPoint, size, style, and visible.
CosmeticVertex() [3/3]
CosmeticVertex::CosmeticVertex (const Base::Vector3d & loc)
Definition at line 77 of file CosmeticVertex.cpp.
References color, TechDraw::Vertex::cosmetic, createNewTag(), TechDraw::LineGroup::getDefaultWidth(), TechDraw::Vertex::hlrVisible, linkGeom, permaPoint, size, style, TechDraw::Preferences::vertexColor(), TechDraw::Preferences::vertexScale(), and visible.
~CosmeticVertex()
TechDraw::CosmeticVertex::~CosmeticVertex () override default
Member Function Documentation
assignTag()
void CosmeticVertex::assignTag (const TechDraw::CosmeticVertex * cv) protected
Definition at line 258 of file CosmeticVertex.cpp.
References Base::Persistence::getTypeId(), and tag.
clone()
CosmeticVertex * CosmeticVertex::clone () const
Definition at line 272 of file CosmeticVertex.cpp.
References copy(), and tag.
copy()
CosmeticVertex * CosmeticVertex::copy () const
Definition at line 266 of file CosmeticVertex.cpp.
References CosmeticVertex().
Referenced by clone().
createNewTag()
void CosmeticVertex::createNewTag () protected
Definition at line 238 of file CosmeticVertex.cpp.
References tag.
Referenced by CosmeticVertex().
dump()
void CosmeticVertex::dump (const char * title) override virtual
Reimplemented from TechDraw::Vertex.
Definition at line 290 of file CosmeticVertex.cpp.
References Base::Console(), Base::ConsoleSingleton::Message(), Plot::title(), and toString().
getMemSize()
unsigned int CosmeticVertex::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
Definition at line 124 of file CosmeticVertex.cpp.
getPyObject()
PyObject * CosmeticVertex::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 280 of file CosmeticVertex.cpp.
References Py::new_reference_to(), and PythonObject.
getTag()
boost::uuids::uuid CosmeticVertex::getTag () const
Definition at line 228 of file CosmeticVertex.cpp.
References tag.
Referenced by getTagAsString().
getTagAsString()
std::string CosmeticVertex::getTagAsString () const override virtual
Reimplemented from TechDraw::Vertex.
Definition at line 233 of file CosmeticVertex.cpp.
References getTag().
Referenced by TechDraw::CosmeticExtension::add1CVToGV(), TechDraw::CosmeticExtension::addCosmeticVertex(), TechDraw::GeometryObject::addCosmeticVertex(), TechDraw::CosmeticExtension::deleteCosmeticElements(), TechDraw::CosmeticExtension::getCosmeticVertex(), Save(), and toString().
makeCanonicalPoint()
Base::Vector3d CosmeticVertex::makeCanonicalPoint (DrawViewPart * dvp, Base::Vector3d point, bool unscale = true) static
converts a point into its unscaled, unrotated form. If point is Gui space coordinates, it should be inverted (DU::invertY) before calling this method, and the result should be inverted back on return.
Definition at line 196 of file CosmeticVertex.cpp.
References DegreesHalfCircle, TechDraw::DrawView::getScale(), App::PropertyQuantity::getValue(), M_PI, point(), result, TechDraw::DrawView::Rotation, and draftfunctions.scale::scale().
Referenced by TechDraw::CosmeticEdge::makeCanonicalLine(), makeCanonicalPointInverted(), TechDraw::DrawDimHelper::makeDistDim(), TechDraw::pointPair::toCanonicalForm(), TechDraw::anglePoints::toCanonicalForm(), and TechDraw::arcPoints::toCanonicalForm().
makeCanonicalPointInverted()
Base::Vector3d CosmeticVertex::makeCanonicalPointInverted (DrawViewPart * dvp, Base::Vector3d invertedPoint, bool unscale = true) static
a version of makeCanonicalPoint that accepts and returns an invertedPoint.
Definition at line 219 of file CosmeticVertex.cpp.
References TechDraw::DrawUtil::invertY(), makeCanonicalPoint(), and result.
move()
void CosmeticVertex::move (const Base::Vector3d & newPos)
Definition at line 93 of file CosmeticVertex.cpp.
References point().
moveRelative()
void CosmeticVertex::moveRelative (const Base::Vector3d & movement)
Definition at line 98 of file CosmeticVertex.cpp.
References point().
point() [1/2]
Base::Vector3d TechDraw::CosmeticVertex::point () const inline
Definition at line 50 of file CosmeticVertex.h.
Referenced by makeCanonicalPoint(), move(), moveRelative(), and toString().
point() [2/2]
void TechDraw::CosmeticVertex::point (Base::Vector3d newPoint) inline
Definition at line 51 of file CosmeticVertex.h.
Restore()
void CosmeticVertex::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 146 of file CosmeticVertex.cpp.
References color, App::Color::fromHexString(), linkGeom, permaPoint, TechDrawTools.TaskFillTemplateFields::reader, TechDraw::Vertex::Restore(), restoreCosmetic(), size, style, tag, visible, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by TechDraw::PropertyCosmeticVertexList::Restore().
restoreCosmetic()
bool CosmeticVertex::restoreCosmetic () static
Definition at line 547 of file Cosmetic.cpp.
References ParameterGrp::GetBool(), and TechDraw::Preferences::getPreferenceGroup().
Referenced by Restore(), TechDraw::CosmeticEdge::Restore(), TechDraw::CenterLine::Restore(), and TechDraw::GeomFormat::Restore().
rotatedAndScaled()
Base::Vector3d CosmeticVertex::rotatedAndScaled (const double scale, const double rotDegrees)
returns a transformed version of our coordinates (permaPoint)
Definition at line 180 of file CosmeticVertex.cpp.
References DegreesHalfCircle, TechDraw::DrawUtil::invertY(), M_PI, Base::Vector3< float_type >::RotateZ(), and scaled().
Referenced by TechDraw::CosmeticExtension::add1CVToGV().
Save()
void CosmeticVertex::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 129 of file CosmeticVertex.cpp.
References App::Color::asHexString(), color, getTagAsString(), Base::Writer::ind(), linkGeom, permaPoint, TechDraw::Vertex::Save(), size, Base::Writer::Stream(), style, TestSpreadsheet::v, visible, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
scaled()
Base::Vector3d CosmeticVertex::scaled (const double factor)
Definition at line 174 of file CosmeticVertex.cpp.
References permaPoint.
Referenced by TechDraw::GeometryObject::addCosmeticVertex(), and rotatedAndScaled().
toString()
std::string CosmeticVertex::toString () const
Definition at line 103 of file CosmeticVertex.cpp.
References App::Color::asHexString(), color, getTagAsString(), linkGeom, point(), size, style, visible, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by dump().
Member Data Documentation
color
App::Color TechDraw::CosmeticVertex::color {App::Color()}
Definition at line 76 of file CosmeticVertex.h.
Referenced by CosmeticVertex(), Path.Dressup.Gui.DogboneII.Marker::highlight(), Path.Dressup.Gui.Dogbone.Marker::highlight(), Path.Dressup.Gui.DogboneII.Marker::lowlight(), Path.Dressup.Gui.Dogbone.Marker::lowlight(), FeaturePython.ViewProviderOctahedron::onChanged(), src.Mod.Test.unittestgui.ProgressBar::paint(), Restore(), Save(), and toString().
linkGeom
int TechDraw::CosmeticVertex::linkGeom {-1}
Definition at line 74 of file CosmeticVertex.h.
Referenced by TechDraw::CosmeticExtension::add1CVToGV(), CosmeticVertex(), Restore(), Save(), and toString().
permaPoint
Base::Vector3d TechDraw::CosmeticVertex::permaPoint {Base::Vector3d()}
Definition at line 73 of file CosmeticVertex.h.
Referenced by CosmeticVertex(), Restore(), Save(), and scaled().
PythonObject
Py::Object TechDraw::CosmeticVertex::PythonObject protected
Definition at line 91 of file CosmeticVertex.h.
Referenced by getPyObject().
size
double TechDraw::CosmeticVertex::size {1.0}
Definition at line 77 of file CosmeticVertex.h.
Referenced by CosmeticVertex(), Path.Post.Utils.GCodeEditorDialog::done(), Restore(), Save(), and toString().
style
int TechDraw::CosmeticVertex::style {1}
Definition at line 78 of file CosmeticVertex.h.
Referenced by CosmeticVertex(), Restore(), Save(), and toString().
tag
boost::uuids::uuid TechDraw::CosmeticVertex::tag protected
Definition at line 89 of file CosmeticVertex.h.
Referenced by assignTag(), clone(), createNewTag(), Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.ChunkBase::dump_header(), getTag(), and Restore().
visible
bool TechDraw::CosmeticVertex::visible {true}
Definition at line 79 of file CosmeticVertex.h.
Referenced by CosmeticVertex(), Restore(), Save(), and toString().
The documentation for this class was generated from the following files:
CosmeticVertex.h
Cosmetic.cpp
CosmeticVertex.cpp