FreeCAD: Gui::SelectModule Class Reference
Gui::SelectModule Class Reference
#include <FileDialog.h>
Public Types
using Dict = QMap< QString, QString >
Public Member Functions
SelectModule (const QString &type, const Dict &, QWidget *parent)
~SelectModule () override
QString getModule () const
Import/Export handler
These methods accepts a file name or a list of file names and return a map of file names with the associated Python module that should open the file.
void accept () override
void reject () override
static Dict exportHandler (const QString &fileName, const QString &filter=QString())
static Dict exportHandler (const QStringList &fileNames, const QString &filter=QString())
static Dict importHandler (const QString &fileName, const QString &filter=QString())
static Dict importHandler (const QStringList &fileNames, const QString &filter=QString())
Detailed Description
The SelectModule class provides a list of radio buttons to choose the module that should handle a certain file type.
Author
Werner Mayer
Definition at line 244 of file FileDialog.h.
Member Typedef Documentation
Dict
using Gui::SelectModule::Dict = QMap<QString, QString>
Definition at line 249 of file FileDialog.h.
Constructor & Destructor Documentation
SelectModule()
SelectModule::SelectModule (const QString & type, const Dict & types, QWidget * parent)
Definition at line 849 of file FileDialog.cpp.
References accept(), draftgeoutils.intersections::connect(), src.Mod.PartDesign.fcgear.svggear::module, src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression, reject(), and Path.Post.scripts.grbl_post::type.
~SelectModule()
SelectModule::~SelectModule () override default
Member Function Documentation
accept()
void SelectModule::accept () override
Definition at line 924 of file FileDialog.cpp.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), SelectModule(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
exportHandler() [1/2]
SelectModule::Dict SelectModule::exportHandler (const QString & fileName, const QString & filter = QString()) static
Definition at line 947 of file FileDialog.cpp.
exportHandler() [2/2]
SelectModule::Dict SelectModule::exportHandler (const QStringList & fileNames, const QString & filter = QString()) static
Definition at line 952 of file FileDialog.cpp.
References Path.Base.SetupSheet::dict, create_qrc::ext, DrawingExample::file, App::GetApplication(), App::Application::getExportFilters(), Gui::getMainWindow(), getModule(), mod, and src.Mod.PartDesign.fcgear.svggear::module.
getModule()
QString SelectModule::getModule () const
Definition at line 941 of file FileDialog.cpp.
Referenced by exportHandler(), and importHandler().
importHandler() [1/2]
SelectModule::Dict SelectModule::importHandler (const QString & fileName, const QString & filter = QString()) static
Definition at line 1009 of file FileDialog.cpp.
Referenced by Gui::ModuleIO::importFiles(), and Gui::ModuleIO::openFile().
importHandler() [2/2]
SelectModule::Dict SelectModule::importHandler (const QStringList & fileNames, const QString & filter = QString()) static
Definition at line 1014 of file FileDialog.cpp.
References Path.Base.SetupSheet::dict, create_qrc::ext, DrawingExample::file, App::GetApplication(), App::Application::getImportFilters(), Gui::getMainWindow(), getModule(), mod, and src.Mod.PartDesign.fcgear.svggear::module.
reject()
void SelectModule::reject () override
Definition at line 930 of file FileDialog.cpp.
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), SelectModule(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
FileDialog.h
FileDialog.cpp