FreeCAD: TechDraw::DashSpec Class Reference
TechDraw::DashSpec Class Reference
#include <HatchLine.h>
Public Member Functions
DashSpec ()
DashSpec (std::vector< double > p)
~DashSpec ()=default
double get (int i)
std::vector< double > get ()
bool empty ()
int size ()
double length ()
void dump (const char *title)
DashSpec reversed ()
Detailed Description
Definition at line 51 of file HatchLine.h.
Constructor & Destructor Documentation
DashSpec() [1/2]
TechDraw::DashSpec::DashSpec () inline
Definition at line 54 of file HatchLine.h.
Referenced by reversed().
DashSpec() [2/2]
TechDraw::DashSpec::DashSpec (std::vector< double > p) inline explicit
Definition at line 55 of file HatchLine.h.
References buildPsets::p.
~DashSpec()
TechDraw::DashSpec::~DashSpec () default
Member Function Documentation
dump()
void DashSpec::dump (const char * title)
Definition at line 465 of file HatchLine.cpp.
References Base::Console(), Base::ConsoleSingleton::Message(), buildPsets::p, and Plot::title().
Referenced by TechDraw::PATLineSpec::dump().
empty()
bool TechDraw::DashSpec::empty () inline
Definition at line 60 of file HatchLine.h.
Referenced by TechDraw::PATLineSpec::isDashed().
get() [1/2]
std::vector<double> TechDraw::DashSpec::get () inline
Definition at line 59 of file HatchLine.h.
Referenced by length(), and reversed().
get() [2/2]
double TechDraw::DashSpec::get (int i) inline
Definition at line 58 of file HatchLine.h.
References SplineSurface::i.
Referenced by TechDrawGui::PATPathMaker::decodeDashSpec().
length()
double DashSpec::length ()
Definition at line 449 of file HatchLine.cpp.
References SCL.SimpleDataTypes::c, get(), and result.
Referenced by TechDrawGui::PATPathMaker::geomToStubbyLine().
reversed()
DashSpec DashSpec::reversed ()
Definition at line 458 of file HatchLine.cpp.
References DashSpec(), get(), and buildPsets::p.
Referenced by TechDrawGui::PATPathMaker::lineSetToFillItems().
size()
int TechDraw::DashSpec::size () inline
Definition at line 61 of file HatchLine.h.
Referenced by Path.Post.Utils.GCodeEditorDialog::done().
The documentation for this class was generated from the following files:
HatchLine.h
HatchLine.cpp