FreeCAD: FemGui::TaskDlgFemConstraintTemperature Class Reference
FemGui::TaskDlgFemConstraintTemperature Class Reference
#include <TaskFemConstraintTemperature.h>
Public Member Functions
TaskDlgFemConstraintTemperature (ViewProviderFemConstraintTemperature *ConstraintView)
bool accept () override
is called by the framework if the dialog is accepted (Ok)
Public Member Functions inherited from FemGui::TaskDlgFemConstraint
void open () override
is called the TaskView when the dialog is opened
bool reject () override
is called by the framework if the dialog is rejected (Cancel)
bool isAllowedAlterDocument () const override
QDialogButtonBox::StandardButtons getStandardButtons () const override
returns for Close and Help button
ViewProviderFemConstraint * getConstraintView () const
Public Member Functions inherited from Gui::TaskView::TaskDialog
TaskDialog ()
~TaskDialog () override
QWidget * addTaskBox (QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBox (const QPixmap &icon, QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBoxWithoutHeader (QWidget *widget)
void setButtonPosition (ButtonPosition p)
ButtonPosition buttonPosition () const
const std::vector< QWidget * > & getDialogContent () const
bool canClose () const
virtual void modifyStandardButtons (QDialogButtonBox *)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
bool isEscapeButtonEnabled () const
void setAutoCloseOnTransactionChange (bool on)
bool isAutoCloseOnTransactionChange () const
void setAutoCloseOnDeletedDocument (bool on)
bool isAutoCloseOnDeletedDocument () const
const std::string & getDocumentName () const
void setDocumentName (const std::string &doc)
void setAutoCloseOnClosedView (bool on)
bool isAutoCloseOnClosedView () const
void associateToObject3dView (App::DocumentObject *obj)
const Gui::MDIView * getAssociatedView () const
void setAssociatedView (const Gui::MDIView *view)
virtual bool isAllowedAlterView () const
virtual bool isAllowedAlterSelection () const
virtual bool needsFullSpace () const
virtual void closed ()
is called by the framework when the dialog is closed
virtual void autoClosedOnTransactionChange ()
virtual void autoClosedOnDeletedDocument ()
virtual void autoClosedOnClosedView ()
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
virtual void helpRequested ()
is called by the framework if the user press the help button
void emitDestructionSignal ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from FemGui::TaskDlgFemConstraint
ViewProviderFemConstraint * ConstraintView
TaskFemConstraint * parameter
Protected Attributes inherited from Gui::TaskView::TaskDialog
QPointer< QDialogButtonBox > buttonBox
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Detailed Description
Definition at line 73 of file TaskFemConstraintTemperature.h.
Constructor & Destructor Documentation
TaskDlgFemConstraintTemperature()
TaskDlgFemConstraintTemperature::TaskDlgFemConstraintTemperature (ViewProviderFemConstraintTemperature * ConstraintView) explicit
Definition at line 346 of file TaskFemConstraintTemperature.cpp.
References FemGui::TaskDlgFemConstraint::ConstraintView, Gui::TaskView::TaskDialog::Content, and FemGui::TaskDlgFemConstraint::parameter.
Member Function Documentation
accept()
bool TaskDlgFemConstraintTemperature::accept () override virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from FemGui::TaskDlgFemConstraint.
Definition at line 358 of file TaskFemConstraintTemperature.cpp.
References FemGui::TaskDlgFemConstraint::accept(), FemGui::TaskDlgFemConstraint::ConstraintView, Gui::Command::Doc, doCommand, SCL.SimpleDataTypes::e, FemGui::TaskFemConstraintTemperature::get_cflux(), FemGui::TaskFemConstraintTemperature::get_constraint_type(), FemGui::TaskFemConstraintTemperature::get_temperature(), App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), FemGui::TaskDlgFemConstraint::parameter, Path.Post.scripts.grbl_post::type, and Path.Log::warning().
Referenced by MaterialEditor.MaterialEditor::verify().
The documentation for this class was generated from the following files:
TaskFemConstraintTemperature.h
TaskFemConstraintTemperature.cpp