FreeCAD: SpreadsheetGui::SheetTableViewAccessibleInterface Class Reference
SpreadsheetGui::SheetTableViewAccessibleInterface Class Reference
#include <SheetTableViewAccessibleInterface.h>
Public Member Functions
SheetTableViewAccessibleInterface (SpreadsheetGui::SheetTableView *view)
QString text (QAccessible::Text txt) const override
QAccessibleInterface * childAt (int x, int y) const override
int indexOfChild (const QAccessibleInterface *) const override
int childCount () const override
QAccessibleInterface * focusChild () const override
QAccessibleInterface * child (int index) const override
Static Public Member Functions
static QAccessibleInterface * ifactory (const QString &key, QObject *obj)
Detailed Description
Definition at line 63 of file SheetTableViewAccessibleInterface.h.
Constructor & Destructor Documentation
SheetTableViewAccessibleInterface()
SpreadsheetGui::SheetTableViewAccessibleInterface::SheetTableViewAccessibleInterface (SpreadsheetGui::SheetTableView * view) explicit
Definition at line 62 of file SheetTableViewAccessibleInterface.cpp.
Referenced by indexOfChild().
Member Function Documentation
child()
QAccessibleInterface * SpreadsheetGui::SheetTableViewAccessibleInterface::child (int index) const override
Definition at line 97 of file SheetTableViewAccessibleInterface.cpp.
childAt()
QAccessibleInterface * SpreadsheetGui::SheetTableViewAccessibleInterface::childAt (int x, int y) const override
Definition at line 75 of file SheetTableViewAccessibleInterface.cpp.
childCount()
int SpreadsheetGui::SheetTableViewAccessibleInterface::childCount () const override
Definition at line 87 of file SheetTableViewAccessibleInterface.cpp.
focusChild()
QAccessibleInterface * SpreadsheetGui::SheetTableViewAccessibleInterface::focusChild () const override
Definition at line 92 of file SheetTableViewAccessibleInterface.cpp.
ifactory()
QAccessibleInterface * SpreadsheetGui::SheetTableViewAccessibleInterface::ifactory (const QString & key, QObject * obj) static
Definition at line 103 of file SheetTableViewAccessibleInterface.cpp.
Referenced by PyMOD_INIT_FUNC().
indexOfChild()
int SpreadsheetGui::SheetTableViewAccessibleInterface::indexOfChild (const QAccessibleInterface *) const override
Definition at line 82 of file SheetTableViewAccessibleInterface.cpp.
References SheetTableViewAccessibleInterface().
text()
QString SpreadsheetGui::SheetTableViewAccessibleInterface::text (QAccessible::Text txt) const override
Definition at line 67 of file SheetTableViewAccessibleInterface.cpp.
The documentation for this class was generated from the following files:
SheetTableViewAccessibleInterface.h
SheetTableViewAccessibleInterface.cpp