FreeCAD: Gui::ViewProvider Class Reference
Gui::ViewProvider Class Reference
#include <ViewProvider.h>
Public Member Functions
ViewProvider ()
constructor.
~ViewProvider () override
destructor.
virtual SoSeparator * getRoot () const
SoSwitch * getModeSwitch () const
SoTransform * getTransformNode () const
SoSeparator * getAnnotation ()
virtual SoSeparator * getFrontRoot () const
virtual SoGroup * getChildRoot () const
virtual SoSeparator * getBackRoot () const
virtual bool canAddToSceneGraph () const
Indicate whether to be added to scene graph or not.
virtual bool isPartOfPhysicalObject () const
virtual std::vector< App::DocumentObject * > claimChildren3D () const
Selection handling
This group of methods do the selection handling. Here you can define how the selection for your ViewProfider works.
virtual bool useNewSelectionModel () const
indicates if the ViewProvider use the new Selection model
virtual bool isSelectable () const
virtual bool getElementPicked (const SoPickedPoint *, std::string &subname) const
return a hit element given the picked point which contains the full node path
virtual std::string getElement (const SoDetail *) const
return a hit element to the selection path or 0
virtual SoDetail * getDetail (const char *) const
return the coin node detail of the subelement
virtual bool getDetailPath (const char *subname, SoFullPath *pPath, bool append, SoDetail *&det) const
int partialRender (const std::vector< std::string > &subelements, bool clear)
virtual std::vector< Base::Vector3d > getModelPoints (const SoPickedPoint *) const
virtual std::vector< Base::Vector3d > getSelectionShape (const char *Element) const
return the highlight lines for a given element or the whole shape
Base::BoundBox3d getBoundingBox (const char *subname=nullptr, bool transform=true, MDIView *view=nullptr) const
virtual bool onDelete (const std::vector< std::string > &subNames)
virtual void beforeDelete ()
virtual bool canDelete (App::DocumentObject *obj) const
Asks the view provider if the given object that is part of its outlist can be removed from there without breaking it.
Drag and drop
To enable drag and drop you have to re-implement canDragObjects() and canDropObjects() to return true. For finer control you can also re-implement canDragObject() or canDropObject() to filter certain object types, by default these methods don't filter any types. To take action of drag and drop the method dragObject() and dropObject() must be re-implemented, too.
virtual bool canDragObjects () const
virtual bool canDragObject (App::DocumentObject *) const
virtual bool canDragObjectToTarget (App::DocumentObject *obj, App::DocumentObject *target) const
virtual void dragObject (App::DocumentObject *)
virtual bool canDropObjects () const
virtual bool canDropObject (App::DocumentObject *) const
virtual bool canDragAndDropObject (App::DocumentObject *) const
virtual void dropObject (App::DocumentObject *)
virtual bool canDropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements) const
virtual bool acceptReorderingObjects () const
virtual std::string getDropPrefix () const
return a subname referencing the sub-object holding the dropped objects
virtual std::string dropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements)
virtual int replaceObject (App::DocumentObject *oldObj, App::DocumentObject *newObj)
virtual bool showInTree () const
virtual bool canRemoveChildrenFromRoot () const
Display mode methods
std::string getActiveDisplayMode () const
virtual void setDisplayMode (const char *ModeName)
set the display mode
virtual const char * getDefaultDisplayMode () const
get the default display mode
virtual std::vector< std::string > getDisplayModes () const
returns a list of all possible display modes
virtual void hide ()
Hides the view provider.
virtual void show ()
Shows the view provider.
virtual bool isShow () const
checks whether the view provider is visible or not
void setVisible (bool)
bool isVisible () const
void setLinkVisible (bool)
bool isLinkVisible () const
virtual void setOverrideMode (const std::string &mode)
Overrides the display mode with mode.
const std::string getOverrideMode ()
Task panel
With this interface the ViewProvider can steer the appearance of widgets in the task view
virtual void getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &) const
get a list of TaskBoxes associated with this object
virtual bool selectAll ()
virtual bool keyPressed (bool pressed, int key)
is called when the provider is in edit and a key event occurs. Only ESC ends edit.
virtual const char * getTransactionText () const
virtual bool doubleClicked ()
is called by the tree if the user double clicks on the object
virtual bool mouseMove (const SbVec2s &cursorPos, View3DInventorViewer *viewer)
is called when the provider is in edit and the mouse is moved
virtual bool mouseButtonPressed (int button, bool pressed, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
is called when the Provider is in edit and the mouse is clicked
virtual bool mouseWheelEvent (int delta, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
virtual void setupContextMenu (QMenu *, QObject *, const char *)
set up the context-menu with the supported edit modes
Public Member Functions inherited from App::TransactionalObject
TransactionalObject ()
Constructor.
~TransactionalObject () override
virtual bool isAttachedToDocument () const
virtual const char * detachFromDocument ()
Public Member Functions inherited from App::ExtensionContainer
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
Property * getPropertyByName (const char *name) const override
find a property by its name
template<typename T >
T * getPropertyByName (const char *name) const
find a property by its name, dynamic cased to specified type
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void onChanged (const Property *) override
get called by the container when a property has changed
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop) override
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual std::string getFullName () const
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
virtual App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false)
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual bool removeDynamicProperty (const char *name)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
virtual void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus)
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Methods used by the Tree
If you want to take control over the viewprovider specific overlay icons, that will be grayed out together with the base icon, you can reimplement this method.
SoSeparator * pcRoot
The root Separator of the ViewProvider.
SoTransform * pcTransform
this is transformation for the provider
const char * sPixmap
SoSwitch * pcModeSwitch
this is the mode switch, all the different viewing modes are collected here
SoSeparator * pcAnnotation {nullptr}
The root separator for annotations.
ViewProviderPy * pyViewObject {nullptr}
std::string overrideMode
std::bitset< 32 > StatusBits
virtual QIcon getIcon () const
deliver the icon shown in the tree view
virtual QIcon mergeColorfulOverlayIcons (const QIcon &orig) const
virtual std::vector< App::DocumentObject * > claimChildren () const
virtual std::vector< App::DocumentObject * > claimChildrenRecursive () const
virtual QIcon mergeGreyableOverlayIcons (const QIcon &orig) const
virtual void setModeSwitch ()
Turn on mode switch.
Signals of the view provider
boost::signals2::signal< void()> signalChangeIcon
signal on icon change
boost::signals2::signal< void(const QString &)> signalChangeToolTip
signal on tooltip change
boost::signals2::signal< void(const QString &)> signalChangeStatusTip
signal on status tip change
boost::signals2::signal< void(bool, Gui::HighlightMode)> signalChangeHighlight
signal on highlight change
virtual void update (const App::Property *)
virtual void updateData (const App::Property *)
bool isUpdatesEnabled () const
void setUpdatesEnabled (bool enable)
unsigned long getStatus () const
return the status bits
bool testStatus (ViewStatus pos) const
void setStatus (ViewStatus pos, bool on)
std::string toString () const
PyObject * getPyObject () override
Color management methods
virtual std::map< std::string, App::Color > getElementColors (const char *element=nullptr) const
virtual void setElementColors (const std::map< std::string, App::Color > &colors)
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
Edit methods
if the Viewprovider goes in edit mode you can handle most of the events in the viewer by yourself
enum EditMode { Default = 0, Transform, Cutting, Color }
virtual ViewProvider * startEditing (int ModNum=0)
bool isEditing () const
void finishEditing ()
virtual void setEditViewer (View3DInventorViewer *, int ModNum)
adjust viewer settings when editing a view provider
virtual void unsetEditViewer (View3DInventorViewer *)
restores viewer settings when leaving editing mode
virtual bool setEdit (int ModNum)
is called by the document when the provider goes in edit mode
virtual void unsetEdit (int ModNum)
is called when you lose the edit mode
int getEditingMode () const
return the edit mode or -1 if nothing is being edited
direct handling methods
This group of methods is to direct influence the appearance of the viewed content. It's only for fast interactions! If you want to set the visual parameters you have to do it on the object viewed by this provider!
virtual void setTransformation (const Base::Matrix4D &rcMatrix)
set the viewing transformation of the provider
virtual void setTransformation (const SbMatrix &rcMatrix)
virtual MDIView * getMDIView () const
void Restore (Base::XMLReader &reader) override
bool isRestoring ()
static SbMatrix convert (const Base::Matrix4D &rcMatrix)
static Base::Matrix4D convert (const SbMatrix &sbMat)
static void eventCallback (void *ud, SoEventCallback *node)
Display mask modes
Mainly controls an SoSwitch node which selects the display mask modes. The number of display mask modes doesn't necessarily match with the number of display modes. E.g. various display modes like Gaussian curvature, mean curvature or gray values are displayed by one display mask mode that handles color values.
void addDisplayMaskMode (SoNode *node, const char *type)
Adds a new display mask mode.
void setDisplayMaskMode (const char *type)
Activates the display mask mode type.
SoNode * getDisplayMaskMode (const char *type) const
Get the node to the display mask mode type.
std::vector< std::string > getDisplayMaskModes () const
Returns a list of added display mask modes.
void setDefaultMode (int)
int getDefaultMode () const
virtual void setRenderCacheMode (int)
bool checkRecursion (SoNode *)
SoPickedPoint * getPointOnRay (const SbVec2s &pos, const View3DInventorViewer *viewer) const
SoPickedPoint * getPointOnRay (const SbVec3f &pos, const SbVec3f &dir, const View3DInventorViewer *viewer) const
void onBeforeChange (const App::Property *prop) override
Reimplemented from subclass.
void onChanged (const App::Property *prop) override
Reimplemented from subclass.
Additional Inherited Members
Public Types inherited from App::ExtensionContainer
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual void onEarlyChange (const Property *)
virtual const PropertyData & getPropertyData () const
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Detailed Description
General interface for all visual stuff in FreeCAD This class is used to generate and handle all around visualizing and presenting objects from the FreeCAD App layer to the user. This class and its descendents have to be implemented for any object type in order to show them in the 3DView and TreeView.
Definition at line 120 of file Gui/ViewProvider.h.
Member Enumeration Documentation
EditMode
enum Gui::ViewProvider::EditMode
Enumerator
Default
Transform
Cutting
Color
Definition at line 440 of file Gui/ViewProvider.h.
Constructor & Destructor Documentation
ViewProvider()
ViewProvider::ViewProvider ()
constructor.
Definition at line 93 of file Gui/ViewProvider.cpp.
References Gui::UpdateData.
~ViewProvider()
ViewProvider::~ViewProvider () override
destructor.
Definition at line 121 of file Gui/ViewProvider.cpp.
References pcAnnotation, pcModeSwitch, pcRoot, pcTransform, and pyViewObject.
Member Function Documentation
acceptReorderingObjects()
virtual bool Gui::ViewProvider::acceptReorderingObjects () const inline virtual
Reimplemented in Gui::ViewProviderPart, and Gui::ViewProviderDocumentObjectGroup.
Definition at line 322 of file Gui/ViewProvider.h.
Referenced by Gui::ViewProviderGroupExtension::extensionCanDropObject().
addDisplayMaskMode()
void ViewProvider::addDisplayMaskMode (SoNode * node, const char * type)
Adds a new display mask mode.
Definition at line 369 of file Gui/ViewProvider.cpp.
References pcModeSwitch, and Path.Post.scripts.grbl_post::type.
Referenced by Gui::ViewProviderVRMLObject::attach(), Gui::ViewProviderImagePlane::attach(), Gui::ViewProviderDatum::attach(), Gui::ViewProviderPlacement::attach(), PartGui::ViewProviderCurveNet::attach(), PartDesignGui::ViewProviderDatum::attach(), FemGui::ViewProviderFemConstraint::attach(), MeshGui::ViewProviderMeshTransform::attach(), Gui::ViewProviderAnnotation::attach(), InspectionGui::ViewProviderInspection::attach(), MeshGui::ViewProviderMeshTransformDemolding::attach(), MeshGui::ViewProviderFace::attach(), PartGui::ViewProviderPartReference::attach(), Gui::ViewProviderCoordinateSystem::attach(), FemGui::ViewProviderFemMesh::attach(), PartDesignGui::ViewProviderAddSub::attach(), Gui::ViewProviderInventorObject::attach(), PartGui::ViewProviderPartExt::attach(), FemGui::ViewProviderFemPostObject::attach(), Gui::ViewProviderAnnotationLabel::attach(), FemGui::ViewProviderFemPostFunction::attach(), MeshGui::ViewProviderMesh::attach(), Gui::ViewProviderLink::attach(), Gui::ViewProviderGeoFeatureGroupExtension::extensionAttach(), and Gui::ViewProviderExtern::setModeBySoInput().
beforeDelete()
void ViewProvider::beforeDelete () virtual
Called before deletion
Unlike onDelete(), this function is guaranteed to be called before deletion, either by Document::remObject(), or on document deletion.
Reimplemented in SpreadsheetGui::ViewProviderSheet.
Definition at line 994 of file Gui/ViewProvider.cpp.
References create_qrc::ext.
Referenced by Gui::ViewProviderLink::onBeforeChange(), and Gui::Document::slotDeletedObject().
canAddToSceneGraph()
virtual bool Gui::ViewProvider::canAddToSceneGraph () const inline virtual
Indicate whether to be added to scene graph or not.
Definition at line 145 of file Gui/ViewProvider.h.
Referenced by Gui::View3DInventorViewer::addViewProvider(), and Gui::Document::toggleInSceneGraph().
canDelete()
bool ViewProvider::canDelete (App::DocumentObject * obj) const virtual
Asks the view provider if the given object that is part of its outlist can be removed from there without breaking it.
Parameters
obj is part of the outlist of the object associated to the view provider
Returns
true if the removal is approved by the view provider.
Reimplemented in Gui::ViewProviderLink, TechDrawGui::ViewProviderDimension, TechDrawGui::ViewProviderPage, FemGui::ViewProviderFemPostObject, TechDrawGui::ViewProviderViewPart, FemGui::ViewProviderFemPostFunctionProvider, AssemblyGui::ViewProviderAssembly, TechDrawGui::ViewProviderBalloon, TechDrawGui::ViewProviderWeld, TechDrawGui::ViewProviderViewSection, Gui::ViewProviderDocumentObject, TechDrawGui::ViewProviderViewClip, TechDrawGui::ViewProviderProjGroupItem, TechDrawGui::ViewProviderProjGroup, FemGui::ViewProviderFemAnalysis, TechDrawGui::ViewProviderTile, TechDrawGui::ViewProviderGeomHatch, TechDrawGui::ViewProviderLeader, FemGui::ViewProviderSolver, TechDrawGui::ViewProviderHatch, TechDrawGui::ViewProviderRichAnno, and AssemblyGui::ViewProviderAssemblyLink.
Definition at line 688 of file Gui/ViewProvider.cpp.
Referenced by StdCmdDelete::activated().
canDragAndDropObject()
bool ViewProvider::canDragAndDropObject (App::DocumentObject * obj) const virtual
Return false to force drop only operation for a given object
Reimplemented in Gui::ViewProviderLink, AssemblyGui::ViewProviderAssemblyLink, AssemblyGui::ViewProviderBomGroup, AssemblyGui::ViewProviderJointGroup, AssemblyGui::ViewProviderSimulationGroup, AssemblyGui::ViewProviderViewGroup, and PartDesignGui::ViewProviderSubShapeBinder.
Definition at line 760 of file Gui/ViewProvider.cpp.
References create_qrc::ext.
canDragObject()
bool ViewProvider::canDragObject (App::DocumentObject * obj) const virtual
Check whether the object can be removed from the view provider by drag and drop
Reimplemented in TechDrawGui::ViewProviderPage, Gui::ViewProviderLink, AssemblyGui::ViewProviderAssembly, FemGui::ViewProviderFemAnalysis, PartGui::ViewProviderMultiCommon, PathGui::ViewProviderAreaView, PathGui::ViewProviderArea, PartGui::ViewProviderMultiFuse, PartGui::ViewProviderCompound, PathGui::ViewProviderPathShape, and PartGui::ViewProviderFace.
Definition at line 693 of file Gui/ViewProvider.cpp.
References create_qrc::ext.
Referenced by canDragObjectToTarget(), and draftviewproviders.view_layer.ViewProviderLayer::canDropObject().
canDragObjects()
bool ViewProvider::canDragObjects () const virtual
Check whether children can be removed from the view provider by drag and drop
Reimplemented in Gui::ViewProviderLink, FemGui::ViewProviderFemAnalysis, PartGui::ViewProviderMultiCommon, AssemblyGui::ViewProviderAssemblyLink, Gui::ViewProviderCoordinateSystem, PathGui::ViewProviderAreaView, AssemblyGui::ViewProviderBomGroup, AssemblyGui::ViewProviderJointGroup, AssemblyGui::ViewProviderSimulationGroup, AssemblyGui::ViewProviderViewGroup, PathGui::ViewProviderArea, PartGui::ViewProviderMultiFuse, PartGui::ViewProviderCompound, PathGui::ViewProviderPathShape, PathGui::ViewProviderPathCompound, TechDrawGui::ViewProviderPage, and PartGui::ViewProviderFace.
Definition at line 709 of file Gui/ViewProvider.cpp.
References create_qrc::ext.
canDragObjectToTarget()
bool ViewProvider::canDragObjectToTarget (App::DocumentObject * obj, App::DocumentObject * target) const virtual
Check whether the object can be removed from the view provider by drag and drop to a determined target
Reimplemented in AssemblyGui::ViewProviderAssembly.
Definition at line 704 of file Gui/ViewProvider.cpp.
References canDragObject().
canDropObject()
bool ViewProvider::canDropObject (App::DocumentObject * obj) const virtual
Check whether the object can be dropped to the view provider by drag and drop or drop only
Reimplemented in TechDrawGui::ViewProviderPage, FemGui::ViewProviderFemAnalysis, PartGui::ViewProviderMultiCommon, PathGui::ViewProviderAreaView, PathGui::ViewProviderArea, PartGui::ViewProviderMultiFuse, PartGui::ViewProviderCompound, PathGui::ViewProviderPathShape, PartDesignGui::ViewProviderBody, and PartGui::ViewProviderFace.
Definition at line 733 of file Gui/ViewProvider.cpp.
References Base::Console(), create_qrc::ext, and Base::ConsoleSingleton::Log().
Referenced by Gui::ViewProviderDocumentObject::canDropObjectEx(), and canDropObjectEx().
canDropObjectEx()
bool ViewProvider::canDropObjectEx (App::DocumentObject * obj, App::DocumentObject * owner, const char * subname, const std::vector< std::string > & elements) const virtual
Query object dropping with full qualified name
Tree view now calls this function instead of canDropObject(), and may query for objects from other document. The default implementation (actually in ViewProviderDocumentObject) inhibites cross document dropping, and calls canDropObject(obj) for the rest. Override this function to enable cross document linking.
Parameters
obj the object being dropped
owner the (grand)parent object of the dropping object. Maybe null. This may not be the top parent object, as tree view will try to find a parent of the dropping object relative to this object to avoid cyclic dependency
subname subname reference to the dropping object
elements non-object sub-elements, e.g. Faces, Edges, selected when the object is being dropped
Returns
Return whether the dropping action is allowed.
Reimplemented in Gui::ViewProviderLink, PartDesignGui::ViewProviderSubShapeBinder, TechDrawGui::ViewProviderPage, and Gui::ViewProviderDocumentObject.
Definition at line 782 of file Gui/ViewProvider.cpp.
References canDropObject(), and create_qrc::ext.
canDropObjects()
bool ViewProvider::canDropObjects () const virtual
Check whether objects can be added to the view provider by drag and drop or drop only
Reimplemented in Gui::ViewProviderLink, FemGui::ViewProviderFemAnalysis, PartGui::ViewProviderMultiCommon, AssemblyGui::ViewProviderAssemblyLink, PathGui::ViewProviderAreaView, AssemblyGui::ViewProviderBomGroup, AssemblyGui::ViewProviderJointGroup, AssemblyGui::ViewProviderSimulationGroup, AssemblyGui::ViewProviderViewGroup, PathGui::ViewProviderArea, PartGui::ViewProviderMultiFuse, PartGui::ViewProviderCompound, PathGui::ViewProviderPathShape, PartDesignGui::ViewProviderSubShapeBinder, PartDesignGui::ViewProviderBody, PathGui::ViewProviderPathCompound, and PartGui::ViewProviderFace.
Definition at line 750 of file Gui/ViewProvider.cpp.
References create_qrc::ext.
Referenced by Gui::TreeWidget::dragMoveEvent().
canRemoveChildrenFromRoot()
virtual bool Gui::ViewProvider::canRemoveChildrenFromRoot () const inline virtual
Tell the tree view to remove children items from the tree root
Definition at line 360 of file Gui/ViewProvider.h.
Referenced by Gui::DocumentObjectData::DocumentObjectData().
checkRecursion()
bool ViewProvider::checkRecursion (SoNode * node) protected
Helper method to check that the node is valid, i.e. it must not cause and infinite recursion.
Definition at line 597 of file Gui/ViewProvider.cpp.
References Gui::addNodes().
Referenced by Gui::ViewProviderVRMLObject::updateData().
claimChildren()
std::vector< App::DocumentObject * > ViewProvider::claimChildren () const virtual
deliver the children belonging to this object this method is used to deliver the objects to the tree framework which should be grouped under its label. Obvious is the usage in the group but it can be used for any kind of grouping needed for a special purpose.
Reimplemented in TechDrawGui::ViewProviderViewPart, TechDrawGui::ViewProviderAnnotation, PartDesignGui::ViewProviderMainPart, Gui::ViewProviderLink, PartGui::ViewProviderThickness, PartGui::ViewProviderOffset, PartGui::ViewProviderSweep, PartGui::ViewProviderLoft, TechDrawGui::ViewProviderDimension, PartGui::ViewProviderRevolution, FemGui::ViewProviderFemPostFunctionProvider, PartGui::ViewProviderChamfer, TechDrawGui::ViewProviderBalloon, PartGui::ViewProviderMultiCommon, TechDrawGui::ViewProviderViewClip, TechDrawGui::ViewProviderWeld, PartDesignGui::ViewProviderSubShapeBinder, PartGui::ViewProviderFillet, PartDesignGui::ViewProviderPipe, PartDesignGui::ViewProviderLoft, TechDrawGui::ViewProviderPage, TechDrawGui::ViewProviderProjGroup, PathGui::ViewProviderAreaView, FemGui::ViewProviderFemAnalysis, FemGui::ViewProviderFemPostPipeline, PartDesignGui::ViewProviderHelix, PartDesignGui::ViewProviderSketchBased, PartGui::ViewProviderBoolean, PartGui::ViewProviderExtrusion, PartGui::ViewProviderRuledSurface, PartGui::ViewProviderScale, PartDesignGui::ViewProviderHole, PathGui::ViewProviderArea, PartGui::ViewProviderMirror, PartDesignGui::ViewProviderMultiTransform, PartGui::ViewProviderMultiFuse, PartGui::ViewProviderCompound, RobotGui::ViewProviderTrajectoryDressUp, PathGui::ViewProviderPathShape, RobotGui::ViewProviderTrajectoryCompound, PathGui::ViewProviderPathCompound, Gui::ViewProviderCoordinateSystem, TechDrawGui::ViewProviderLeader, TechDrawGui::ViewProviderRichAnno, PartGui::ViewProviderFace, and FemGui::ViewProviderFemConstraint.
Definition at line 870 of file Gui/ViewProvider.cpp.
References create_qrc::ext, and SurfaceTests.TestBlendCurve::vec.
Referenced by Gui::Document::addRootObjectsToGroup(), FemGui::ViewProviderFemAnalysis::claimChildren(), claimChildrenRecursive(), Gui::ViewProviderGeoFeatureGroupExtension::extensionClaimChildren(), Gui::Document::getTreeRootObjects(), FemGui::ViewProviderSolver::onDelete(), femviewprovider.view_result_mechanical.VPResultMechanical::onDelete(), BOPTools.SplitFeatures.ViewProviderBooleanFragments::onDelete(), FemGui::ViewProviderFemPostObject::onDelete(), BOPTools.JoinFeatures.ViewProviderConnect::onDelete(), BOPTools.ToleranceFeatures.ViewProviderToleranceSet::onDelete(), femviewprovider.view_mesh_gmsh.VPMeshGmsh::onDelete(), CommandCreateView.ViewProviderExplodedView::onDelete(), CommandCreateSimulation.ViewProviderSimulation::onDelete(), BOPTools.SplitFeatures.ViewProviderSlice::onDelete(), BOPTools.SplitFeatures.ViewProviderXOR::onDelete(), and Gui::DocumentObjectData::updateChildren().
claimChildren3D()
std::vector< App::DocumentObject * > ViewProvider::claimChildren3D () const virtual
deliver the children belonging to this object this method is used to deliver the objects to the 3DView which should be grouped under its scene graph. This affects the visibility and the 3D position of the object.
Reimplemented in FemGui::ViewProviderFemPostFunctionProvider, FemGui::ViewProviderFemPostPipeline, and Gui::ViewProviderCoordinateSystem.
Definition at line 898 of file Gui/ViewProvider.cpp.
References create_qrc::ext, and SurfaceTests.TestBlendCurve::vec.
Referenced by Gui::LinkInfo::updateChildren().
claimChildrenRecursive()
std::vector< App::DocumentObject * > ViewProvider::claimChildrenRecursive () const virtual
deliver the children belonging to this object recursively.
Definition at line 883 of file Gui/ViewProvider.cpp.
References claimChildren(), claimChildrenRecursive(), Gui::Application::getViewProvider(), and Gui::Application::Instance.
Referenced by claimChildrenRecursive().
convert() [1/2]
SbMatrix ViewProvider::convert (const Base::Matrix4D & rcMatrix) static
Definition at line 359 of file Gui/ViewProvider.cpp.
Referenced by femsolver.elmer.writer.Writer::getDensity(), femsolver.elmer.writer.Writer::getFromUi(), setTransformation(), and Gui::ViewProviderLink::updateDataPrivate().
convert() [2/2]
Base::Matrix4D ViewProvider::convert (const SbMatrix & sbMat) static
Definition at line 364 of file Gui/ViewProvider.cpp.
Referenced by femsolver.elmer.writer.Writer::getDensity(), and femsolver.elmer.writer.Writer::getFromUi().
doubleClicked()
virtual bool Gui::ViewProvider::doubleClicked () inline virtual
is called by the tree if the user double clicks on the object
Reimplemented in TechDrawGui::ViewProviderViewPart, TechDrawGui::ViewProviderGeomHatch, DrawingGui::ViewProviderDrawingPage, SketcherGui::ViewProviderSketch, Gui::ViewProviderLink, MeshGui::ViewProviderMesh, FemGui::ViewProviderFemPostFunction, TechDrawGui::ViewProviderDimension, AssemblyGui::ViewProviderAssembly, TechDrawGui::ViewProviderBalloon, TechDrawGui::ViewProviderViewSection, FemGui::ViewProviderFemPostObject, PartGui::ViewProviderLCS, SpreadsheetGui::ViewProviderSheet, TechDrawGui::ViewProviderWeld, PartDesignGui::ViewProviderSubShapeBinder, AssemblyGui::ViewProviderAssemblyLink, TechDrawGui::ViewProviderPage, TechDrawGui::ViewProviderProjGroup, TechDrawGui::ViewProviderProjGroupItem, PartGui::ViewProviderPoint, AssemblyGui::ViewProviderBom, Gui::ViewProviderMaterialObject, PartGui::ViewProviderLine, Gui::ViewProviderPart, FemGui::ViewProviderFemAnalysis, Gui::ViewProviderVarSet, PartDesignGui::ViewProviderBase, FemGui::ViewProviderSetElementNodes, FemGui::ViewProviderSetElements, FemGui::ViewProviderSetFaces, FemGui::ViewProviderSetGeometry, FemGui::ViewProviderSetNodes, RobotGui::ViewProviderEdge2TracObject, PartGui::ViewProviderPlane, Gui::ViewProviderDragger, PartDesignGui::ViewProvider, TechDrawGui::ViewProviderLeader, PartDesignGui::ViewProviderBody, TechDrawGui::ViewProviderHatch, TechDrawGui::ViewProviderRichAnno, PartDesignGui::ViewProviderDatum, PartGui::ViewProviderPart, Gui::ViewProviderImagePlane, and Gui::ViewProviderTextDocument.
Definition at line 482 of file Gui/ViewProvider.h.
Referenced by Gui::ViewProviderLink::doubleClicked(), and Gui::TreeWidget::mouseDoubleClickEvent().
dragObject()
void ViewProvider::dragObject (App::DocumentObject * obj) virtual
Remove a child from the view provider by drag and drop
Reimplemented in TechDrawGui::ViewProviderViewClip, Gui::ViewProviderLink, FemGui::ViewProviderFemAnalysis, PartGui::ViewProviderMultiCommon, PathGui::ViewProviderAreaView, PathGui::ViewProviderArea, PartGui::ViewProviderMultiFuse, PartGui::ViewProviderCompound, PathGui::ViewProviderPathShape, PathGui::ViewProviderPathCompound, and PartGui::ViewProviderFace.
Definition at line 720 of file Gui/ViewProvider.cpp.
References create_qrc::ext.
dropObject()
void ViewProvider::dropObject (App::DocumentObject * obj) virtual
Add an object to the view provider by drag and drop
Reimplemented in TechDrawGui::ViewProviderViewClip, TechDrawGui::ViewProviderPage, TechDrawGui::ViewProviderDrawingView, FemGui::ViewProviderFemAnalysis, PartGui::ViewProviderMultiCommon, PathGui::ViewProviderAreaView, PathGui::ViewProviderArea, PartGui::ViewProviderMultiFuse, PartGui::ViewProviderCompound, PathGui::ViewProviderPathShape, PartDesignGui::ViewProviderBody, PathGui::ViewProviderPathCompound, and PartGui::ViewProviderFace.
Definition at line 772 of file Gui/ViewProvider.cpp.
References create_qrc::ext.
Referenced by dropObjectEx().
dropObjectEx()
std::string ViewProvider::dropObjectEx (App::DocumentObject * obj, App::DocumentObject * owner, const char * subname, const std::vector< std::string > & elements) virtual
Add an object with full qualified name to the view provider by drag and drop
Parameters
obj the object being dropped
owner the (grand)parent object of the dropping object. Maybe null. This may not be the top parent object, as tree view will try to find a parent of the dropping object relative to this object to avoid cyclic dependency
subname subname reference to the dropping object
elements non-object sub-elements, e.g. Faces, Edges, selected when the object is being dropped
Returns
Optionally returns a subname reference locating the dropped object, which may or may not be the actual dropped object, e.g. it may be a link.
Reimplemented in Gui::ViewProviderLink, and PartDesignGui::ViewProviderSubShapeBinder.
Definition at line 793 of file Gui/ViewProvider.cpp.
References dropObject(), and create_qrc::ext.
eventCallback()
void ViewProvider::eventCallback (void * ud, SoEventCallback * node) static
Definition at line 196 of file Gui/ViewProvider.cpp.
References Gui::Application::activeDocument(), Base::Console(), toolbit-attributes::doc, SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), FC_WARN, Gui::Application::Instance, and OfflineRenderingUtils::viewer().
Referenced by Gui::View3DInventorViewer::resetEditingViewProvider(), and Gui::View3DInventorViewer::setEditingViewProvider().
finishEditing()
void ViewProvider::finishEditing ()
Definition at line 155 of file Gui/ViewProvider.cpp.
References unsetEdit().
Referenced by Gui::Document::_resetEdit(), MeshGui::ViewProviderMesh::clipMeshCallback(), PointsGui::ViewProviderPoints::clipPointsCallback(), MeshGui::ViewProviderMesh::partMeshCallback(), MeshGui::ViewProviderMesh::segmMeshCallback(), MeshGui::ViewProviderMesh::selectGLCallback(), and MeshGui::ViewProviderMesh::trimMeshCallback().
getActiveDisplayMode()
std::string ViewProvider::getActiveDisplayMode () const
Definition at line 434 of file Gui/ViewProvider.cpp.
Referenced by PartDesignGui::ViewProviderAddSub::setPreviewDisplayMode(), PartGui::ViewProviderCustom::updateData(), and SketcherGui::ViewProviderCustom::updateData().
getAnnotation()
SoSeparator * ViewProvider::getAnnotation ()
Definition at line 295 of file Gui/ViewProvider.cpp.
References pcAnnotation, and pcRoot.
getBackRoot()
SoSeparator * ViewProvider::getBackRoot () const virtual
Definition at line 837 of file Gui/ViewProvider.cpp.
References create_qrc::ext.
Referenced by Gui::View3DInventorViewer::addViewProvider(), and Gui::View3DInventorViewer::removeViewProvider().
getBoundingBox()
Base::BoundBox3d ViewProvider::getBoundingBox (const char * subname = nullptr, bool transform = true, MDIView * view = nullptr) const
Return the bound box of this view object
This method shall work regardless whether the current view object is visible or not.
Definition at line 1005 of file Gui/ViewProvider.cpp.
References Gui::Application::activeDocument(), Gui::Application::activeView(), toolbit-attributes::doc, FC_ERR, Base::BaseClass::getClassTypeId(), getDefaultMode(), getDetailPath(), Gui::Application::Instance, pcModeSwitch, pcRoot, and OfflineRenderingUtils::viewer().
Referenced by getBoxSelection(), AssemblyGui::ViewProviderAssembly::getCenterOfBoundingBox(), Gui::ViewProviderLink::initDraggingPlacement(), and Gui::ViewProviderGeometryObject::updateData().
getChildRoot()
SoGroup * ViewProvider::getChildRoot () const virtual
Reimplemented in Gui::ViewProviderCoordinateSystem.
Definition at line 848 of file Gui/ViewProvider.cpp.
References create_qrc::ext.
Referenced by Gui::View3DInventorSelection::checkGroupOnTop(), Gui::LinkInfo::getDetail(), Gui::ViewProviderDocumentObject::getDetailPath(), Gui::ViewProviderDocumentObject::getElementPicked(), Gui::LinkInfo::getSnapshot(), and Gui::LinkInfo::updateChildren().
getDefaultDisplayMode()
const char * ViewProvider::getDefaultDisplayMode () const virtual
get the default display mode
Reimplemented in MeshGui::ViewProviderExport, PartDesignGui::ViewProviderBoolean, MeshPartGui::ViewProviderCrossSections, MeshGui::ViewProviderMeshCurvature, PartGui::ViewProviderCrossSections, MeshGui::ViewProviderFace, MeshGui::ViewProviderMeshTransformDemolding, MeshGui::ViewProviderMeshTransform, Gui::ViewProviderExtern, and PartGui::ViewProvider2DObject.
Definition at line 418 of file Gui/ViewProvider.cpp.
Referenced by Gui::ViewProviderDocumentObject::attach().
getDefaultMode()
int ViewProvider::getDefaultMode () const
Definition at line 524 of file Gui/ViewProvider.cpp.
Referenced by getBoundingBox(), Gui::ViewProviderLink::getDetailPath(), PartDesignGui::ViewProviderAddSub::setPreviewDisplayMode(), Gui::LinkInfo::setVisible(), and Gui::LinkInfo::updateSwitch().
getDetail()
virtual SoDetail* Gui::ViewProvider::getDetail (const char *) const inline virtual
return the coin node detail of the subelement
Reimplemented in PathGui::ViewProviderPath, PartDesignGui::ViewProviderDatumCoordinateSystem, PartGui::ViewProviderPartExt, FemGui::ViewProviderFemMesh, and PartDesignGui::ViewProviderDatum.
Definition at line 172 of file Gui/ViewProvider.h.
Referenced by Gui::SoFCUnifiedSelection::doAction(), getDetailPath(), and MeshPartGui::CurveOnMeshHandler::Private::vertexCallback().
getDetailPath()
bool ViewProvider::getDetailPath (const char * subname, SoFullPath * pPath, bool append, SoDetail *& det) const virtual
return the coin node detail and path to the node of the subelement
Parameters
subname dot separated string reference to the sub element
pPath output coin path leading to the returned element detail
append If true, pPath will be first appended with the root node and the mode switch node of this view provider.
Returns
the coint detail of the subelement
If this view provider links to other view provider, then the implementation of getDetailPath() shall also append all intermediate nodes starting just after the mode switch node up till the mode switch of the linked view provider.
Reimplemented in Gui::ViewProviderDocumentObject, Gui::ViewProviderLink, and Gui::ViewProviderPlacement.
Definition at line 921 of file Gui/ViewProvider.cpp.
References Path.Post.scripts.uccnc_post::append(), create_qrc::ext, getDetail(), pcModeSwitch, and pcRoot.
Referenced by Gui::SoFCUnifiedSelection::doAction(), getBoundingBox(), Gui::ViewProviderDocumentObject::getDetailPath(), and partialRender().
getDisplayMaskMode()
SoNode * ViewProvider::getDisplayMaskMode (const char * type) const
Get the node to the display mask mode type.
Definition at line 385 of file Gui/ViewProvider.cpp.
References pcModeSwitch, and Path.Post.scripts.grbl_post::type.
getDisplayMaskModes()
std::vector< std::string > ViewProvider::getDisplayMaskModes () const
Returns a list of added display mask modes.
Definition at line 395 of file Gui/ViewProvider.cpp.
getDisplayModes()
vector< std::string > ViewProvider::getDisplayModes () const virtual
returns a list of all possible display modes
Reimplemented in DrawingGui::ViewProviderDrawingClip, DrawingGui::ViewProviderDrawingView, DrawingGui::ViewProviderDrawingPage, Gui::ViewProviderLink, MeshGui::ViewProviderMesh, FemGui::ViewProviderFemPostFunction, MeshGui::ViewProviderExport, Gui::ViewProviderAnnotationLabel, MeasureGui::ViewProviderMeasureBase, FemGui::ViewProviderFemAnalysis, MeshPartGui::ViewProviderCrossSections, SpreadsheetGui::ViewProviderSheet, FemGui::ViewProviderFemPostObject, PartGui::ViewProviderCrossSections, PartGui::ViewProviderPartExt, MeshGui::ViewProviderMeshCurvature, PointsGui::ViewProviderPoints, Gui::ViewProviderInventorObject, Gui::ViewProviderDocumentObjectGroup, FemGui::ViewProviderFemMesh, PartGui::ViewProviderPrism, PartGui::ViewProviderRegularPolygon, PartGui::ViewProviderHelixParametric, PartGui::ViewProviderRuledSurface, PartGui::ViewProviderSphereParametric, PartGui::ViewProviderWedge, PartGui::ViewProviderSpiralParametric, PartGui::ViewProviderPartReference, PartGui::ViewProviderEllipsoid, Gui::ViewProviderCoordinateSystem, PathGui::ViewProviderPath, MeshGui::ViewProviderFace, MeshGui::ViewProviderMeshTransformDemolding, MeshGui::ViewProviderMeshTransform, InspectionGui::ViewProviderInspection, Gui::ViewProviderAnnotation, PartDesignGui::ViewProviderBody, FemGui::ViewProviderSolver, PartGui::ViewProviderCurveNet, PartDesignGui::ViewProviderDatum, FemGui::ViewProviderFemConstraint, RobotGui::ViewProviderRobotObject, Gui::ViewProviderPlacement, Gui::ViewProviderExtern, RobotGui::ViewProviderTrajectory, Gui::ViewProviderImagePlane, Gui::ViewProviderDatum, PartGui::ViewProvider2DObject, PartGui::ViewProviderBox, PartGui::ViewProviderCircleParametric, PartGui::ViewProviderConeParametric, PartGui::ViewProviderCylinderParametric, PartGui::ViewProviderEllipseParametric, PartGui::ViewProviderLineParametric, PartGui::ViewProviderPlaneParametric, PartGui::ViewProviderPointParametric, PartGui::ViewProviderTorusParametric, and Gui::ViewProviderVRMLObject.
Definition at line 423 of file Gui/ViewProvider.cpp.
References create_qrc::ext, and modes.
Referenced by Gui::ViewProviderDocumentObject::attach(), and Gui::ViewProviderLink::getDisplayModes().
getDropPrefix()
virtual std::string Gui::ViewProvider::getDropPrefix () const inline virtual
return a subname referencing the sub-object holding the dropped objects
Definition at line 325 of file Gui/ViewProvider.h.
getEditingMode()
int ViewProvider::getEditingMode () const protected
return the edit mode or -1 if nothing is being edited
Definition at line 145 of file Gui/ViewProvider.cpp.
Referenced by PointsGui::ViewProviderPoints::clipPointsCallback(), and isEditing().
getElement()
virtual std::string Gui::ViewProvider::getElement (const SoDetail *) const inline virtual
return a hit element to the selection path or 0
Reimplemented in PartDesignGui::ViewProviderDatumCoordinateSystem, PartGui::ViewProviderPartExt, FemGui::ViewProviderFemMesh, PathGui::ViewProviderPath, and PartDesignGui::ViewProviderDatum.
Definition at line 170 of file Gui/ViewProvider.h.
Referenced by getElementPicked().
getElementColors()
virtual std::map<std::string, App::Color> Gui::ViewProvider::getElementColors (const char * element = nullptr) const inline virtual
Reimplemented in Gui::ViewProviderLink, and PartGui::ViewProviderPartExt.
Definition at line 421 of file Gui/ViewProvider.h.
Referenced by Gui::ElementColors::Private::addItem(), and Gui::ElementColors::Private::populate().
getElementPicked()
bool ViewProvider::getElementPicked (const SoPickedPoint * pp, std::string & subname) const virtual
return a hit element given the picked point which contains the full node path
Reimplemented in Gui::ViewProviderPlacement, Gui::ViewProviderDocumentObject, and Gui::ViewProviderLink.
Definition at line 909 of file Gui/ViewProvider.cpp.
References create_qrc::ext, getElement(), and isSelectable().
Referenced by Gui::ViewProviderDocumentObject::getElementPicked(), Gui::View3DInventorPy::getObjectInfo(), Gui::View3DInventorPy::getObjectsInfo(), and Gui::View3DInventor::getObjInfoRay().
getFrontRoot()
SoSeparator * ViewProvider::getFrontRoot () const virtual
Reimplemented in FemGui::ViewProviderFemPostObject, MeshGui::ViewProviderMeshCurvature, and InspectionGui::ViewProviderInspection.
Definition at line 859 of file Gui/ViewProvider.cpp.
References create_qrc::ext.
Referenced by Gui::View3DInventorViewer::addViewProvider(), Gui::ViewProviderDocumentObject::findFrontRootOfType(), and Gui::View3DInventorViewer::removeViewProvider().
getIcon()
QIcon ViewProvider::getIcon () const virtual
deliver the icon shown in the tree view
Reimplemented in Gui::ViewProviderLink, MeshGui::ViewProviderMesh, InspectionGui::ViewProviderInspectionGroup, MeshGui::ViewProviderExport, PartGui::ViewProviderMultiCommon, SpreadsheetGui::ViewProviderSheet, AssemblyGui::ViewProviderAssembly, PartDesignGui::ViewProviderLoft, PartDesignGui::ViewProviderPipe, MeshGui::ViewProviderMeshCurvature, PointsGui::ViewProviderPoints, Gui::ViewProviderPart, PathGui::ViewProviderPathShape, PartDesignGui::ViewProviderHelix, Gui::ViewProviderDocumentObjectGroup, AssemblyGui::ViewProviderAssemblyLink, PartGui::ViewProviderSpline, PartDesignGui::ViewProviderPrimitive, AssemblyGui::ViewProviderBom, AssemblyGui::ViewProviderBomGroup, AssemblyGui::ViewProviderJointGroup, AssemblyGui::ViewProviderSimulationGroup, AssemblyGui::ViewProviderViewGroup, PartGui::ViewProviderBoolean, Gui::ViewProviderMaterialObject, PathGui::ViewProviderPathCompound, PartGui::ViewProviderMultiFuse, SurfaceGui::ViewProviderExtend, PathGui::ViewProviderPath, SurfaceGui::ViewProviderBlendCurve, InspectionGui::ViewProviderInspection, MeasureGui::ViewProviderMeasureGroup, SurfaceGui::ViewProviderFilling, SurfaceGui::ViewProviderSections, and SurfaceGui::ViewProviderGeomFillSurface.
Definition at line 316 of file Gui/ViewProvider.cpp.
References Gui::BitmapFactory(), mergeGreyableOverlayIcons(), and sPixmap.
Referenced by Gui::ViewProviderIndex::data(), PartGui::DlgScale::findShapes(), PartGui::DlgExtrusion::findShapes(), InspectionGui::ViewProviderInspection::getIcon(), PartGui::ViewProviderBoolean::getIcon(), Gui::LinkInfo::getIcon(), TechDrawGui::TaskLinkDim::loadToTree(), Gui::DocumentObjectItem::testStatus(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchWindow._ArchWindowTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), bimcommands.BimClassification.BIM_Classification::updateByMaterial(), bimcommands.BimClassification.BIM_Classification::updateByTree(), bimcommands.BimClassification.BIM_Classification::updateByType(), bimcommands.BimClassification.BIM_Classification::updateDefault(), and InspectionGui::VisualInspection::VisualInspection().
getMDIView()
virtual MDIView* Gui::ViewProvider::getMDIView () const inline virtual
Reimplemented in SpreadsheetGui::ViewProviderSheet, TechDrawGui::ViewProviderPage, TechDrawGui::ViewProviderDrawingView, TechDrawGui::ViewProviderGeomHatch, TechDrawGui::ViewProviderHatch, TechDrawGui::ViewProviderTemplate, and Gui::ViewProviderTextDocument.
Definition at line 507 of file Gui/ViewProvider.h.
Referenced by TechDrawGui::ViewProviderHatch::getMDIView(), TechDrawGui::ViewProviderGeomHatch::getMDIView(), and Gui::Document::setActiveView().
getModelPoints()
std::vector< Base::Vector3d > ViewProvider::getModelPoints (const SoPickedPoint * pp) const virtual
Reimplemented in PartGui::ViewProviderPartExt.
Definition at line 628 of file Gui/ViewProvider.cpp.
References SurfaceTests.TestBlendCurve::vec.
Referenced by Gui::ManualAlignment::applyPickedProbe().
getModeSwitch()
SoSwitch* Gui::ViewProvider::getModeSwitch () const inline
Definition at line 134 of file Gui/ViewProvider.h.
Referenced by Gui::LinkInfo::getSnapshot(), and Gui::ViewProviderDocumentObject::setShowable().
getOverrideMode()
const string ViewProvider::getOverrideMode ()
Definition at line 500 of file Gui/ViewProvider.cpp.
References overrideMode.
Referenced by PartDesignGui::ViewProviderBody::onChanged().
getPointOnRay() [1/2]
SoPickedPoint * ViewProvider::getPointOnRay (const SbVec2s & pos, const View3DInventorViewer * viewer) const protected
Helper method to get picked entities while editing. It's in the responsibility of the caller to delete the returned instance.
Definition at line 618 of file Gui/ViewProvider.cpp.
References RobotExample::pos, and OfflineRenderingUtils::viewer().
Referenced by SketcherGui::ViewProviderSketch::mouseButtonPressed(), and SketcherGui::ViewProviderSketch::mouseMove().
getPointOnRay() [2/2]
SoPickedPoint * ViewProvider::getPointOnRay (const SbVec3f & pos, const SbVec3f & dir, const View3DInventorViewer * viewer) const protected
Helper method to get picked entities while editing. It's in the responsibility of the caller to delete the returned instance.
Definition at line 623 of file Gui/ViewProvider.cpp.
References RobotExample::pos, and OfflineRenderingUtils::viewer().
getPyObject()
PyObject * ViewProvider::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Reimplemented in Gui::ViewProviderLink, AssemblyGui::ViewProviderAssembly, MeshGui::ViewProviderMesh, PartGui::ViewProviderPartExt, FemGui::ViewProviderFemMesh, SpreadsheetGui::ViewProviderSheet, Gui::ViewProviderDocumentObject, Gui::ViewProviderGeometryObject, PartDesignGui::ViewProvider, FemGui::ViewProviderFemPostPipeline, and FemGui::ViewProviderFemConstraint.
Definition at line 548 of file Gui/ViewProvider.cpp.
References pyViewObject.
getRoot()
virtual SoSeparator* Gui::ViewProvider::getRoot () const inline virtual
Reimplemented in MeshGui::ViewProviderExport.
Definition at line 132 of file Gui/ViewProvider.h.
Referenced by Gui::Document::addViewProvider(), Gui::View3DInventorViewer::addViewProvider(), FemGui::ViewProviderFemHighlighter::attach(), Gui::View3DInventorViewer::containsViewProvider(), Gui::SoFCUnifiedSelection::doAction(), Gui::ViewProviderGeometryObject::getPickedPoint(), Gui::ViewProviderGeometryObject::getPickedPoints(), Gui::View3DInventorViewer::getPointOnRay(), PartDesignGui::ViewProviderDatum::getRelevantBoundBox(), Gui::LinkInfo::getSnapshot(), Gui::Document::getViewOfViewProvider(), PartGui::TaskCheckGeometryResults::goCheck(), FemGui::ViewProviderFemHighlighter::highlightView(), PartGui::FaceAppearances::Private::isVisibleFace(), Gui::ViewProviderDocumentObject::onChanged(), FemGui::ViewProviderFemHighlighter::removeView(), Gui::View3DInventorViewer::removeViewProvider(), Gui::View3DInventorViewer::resetEditingRoot(), Gui::View3DInventorViewer::setupEditingRoot(), Gui::ApplicationPy::sExport(), PartGui::ViewProviderSplineExtension::showControlPoints(), Gui::Document::slotTransactionRemove(), Gui::Document::toggleInSceneGraph(), PartGui::ViewProviderCustom::updateData(), and SketcherGui::ViewProviderCustom::updateData().
getSelectionShape()
virtual std::vector<Base::Vector3d> Gui::ViewProvider::getSelectionShape (const char * Element) const inline virtual
return the highlight lines for a given element or the whole shape
Reimplemented in PartGui::ViewProviderPartExt, and FemGui::ViewProviderFemMesh.
Definition at line 205 of file Gui/ViewProvider.h.
getStatus()
unsigned long Gui::ViewProvider::getStatus () const inline
return the status bits
Definition at line 386 of file Gui/ViewProvider.h.
getTaskViewContent()
virtual void Gui::ViewProvider::getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &) const inline virtual
get a list of TaskBoxes associated with this object
Reimplemented in Gui::ViewProviderDocumentObject.
Definition at line 469 of file Gui/ViewProvider.h.
getTransactionText()
virtual const char* Gui::ViewProvider::getTransactionText () const inline virtual
Is called by the tree if the user double clicks on the object. It returns the string for the transaction that will be shown in the undo/redo dialog. If null is returned then no transaction will be opened.
Reimplemented in SketcherGui::ViewProviderSketch, and Gui::ViewProviderDocumentObject.
Definition at line 480 of file Gui/ViewProvider.h.
getTransformNode()
SoTransform* Gui::ViewProvider::getTransformNode () const inline
Definition at line 135 of file Gui/ViewProvider.h.
Referenced by Gui::LinkInfo::getSnapshot(), Gui::View3DInventorViewer::resetEditingRoot(), and Gui::View3DInventorViewer::setupEditingRoot().
hasHiddenMarker()
const char * ViewProvider::hasHiddenMarker (const char * subname) static
Definition at line 946 of file Gui/ViewProvider.cpp.
References App::DocumentObject::hasHiddenMarker().
Referenced by partialRender().
hiddenMarker()
const std::string & ViewProvider::hiddenMarker () static
Definition at line 942 of file Gui/ViewProvider.cpp.
References App::DocumentObject::hiddenMarker().
Referenced by Gui::ViewProviderLink::applyColors(), Gui::ViewProviderLink::getElementColors(), and partialRender().
hide()
void ViewProvider::hide () virtual
Hides the view provider.
Reimplemented in DrawingGui::ViewProviderDrawingClip, DrawingGui::ViewProviderDrawingView, DrawingGui::ViewProviderDrawingPage, FemGui::ViewProviderFemAnalysis, FemGui::ViewProviderFemPostObject, MeshGui::ViewProviderMeshCurvature, TechDrawGui::ViewProviderViewClip, TechDrawGui::ViewProviderPage, InspectionGui::ViewProviderInspection, Gui::ViewProviderDocumentObject, TechDrawGui::ViewProviderDrawingView, and TechDrawGui::ViewProviderTemplate.
Definition at line 439 of file Gui/ViewProvider.cpp.
References create_qrc::ext, and pcModeSwitch.
Referenced by DrawingGui::DrawingView::closeEvent(), TechDrawGui::MDIViewPage::closeEvent(), Gui::ViewProviderDocumentObject::hide(), src.Mod.Show.mTempoVis.TempoVis::hide_all_dependencies(), src.Mod.Show.mTempoVis.TempoVis::hide_all_dependent(), Gui::Application::hideViewProvider(), Gui::MergeDocuments::importObject(), PartDesignGui::ViewProvider::makeTemporaryVisible(), Gui::ViewProviderDocumentObject::setActiveMode(), Gui::ViewProviderDocumentObject::setShowable(), PartGui::DlgFilletEdges::setupFillet(), setVisible(), update(), and Gui::ViewProviderDocumentObject::updateView().
isEditing()
bool ViewProvider::isEditing () const
Definition at line 150 of file Gui/ViewProvider.cpp.
References getEditingMode().
Referenced by SketcherGui::ViewProviderSketch::isSelectable().
isLinkVisible()
bool ViewProvider::isLinkVisible () const
Definition at line 1066 of file Gui/ViewProvider.cpp.
References create_qrc::ext.
isPartOfPhysicalObject()
virtual bool Gui::ViewProvider::isPartOfPhysicalObject () const inline virtual
Reimplemented in MeasureGui::ViewProviderMeasureBase.
Definition at line 147 of file Gui/ViewProvider.h.
Referenced by Gui::View3DInventorViewer::addViewProvider().
isRestoring()
bool Gui::ViewProvider::isRestoring () inline
Definition at line 518 of file Gui/ViewProvider.h.
References Gui::isRestoring.
Referenced by Gui::ViewProviderDocumentObject::attach(), TechDrawGui::QGIView::itemChange(), PartDesignGui::ViewProviderSubShapeBinder::onChanged(), Gui::ViewProviderLink::onChanged(), PartDesignGui::ViewProviderBody::unifyVisualProperty(), Gui::ViewProviderDocumentObject::update(), Gui::LinkInfo::update(), and Gui::ViewProviderLink::updateData().
isSelectable()
virtual bool Gui::ViewProvider::isSelectable () const inline virtual
Reimplemented in SketcherGui::ViewProviderSketch, Gui::ViewProviderLink, Gui::ViewProviderGeometryObject, PartDesignGui::ViewProviderDatum, and Gui::ViewProviderPlacement.
Definition at line 166 of file Gui/ViewProvider.h.
Referenced by Gui::SoFCUnifiedSelection::doAction(), Gui::ViewProviderDocumentObject::getElementPicked(), getElementPicked(), Gui::LinkInfo::getElementPicked(), Gui::View3DInventorPy::getObjectInfo(), Gui::View3DInventorPy::getObjectsInfo(), and Gui::View3DInventor::getObjInfoRay().
isShow()
bool ViewProvider::isShow () const virtual
checks whether the view provider is visible or not
Reimplemented in DrawingGui::ViewProviderDrawingClip, DrawingGui::ViewProviderDrawingView, SpreadsheetGui::ViewProviderSheet, FemGui::ViewProviderFemAnalysis, Gui::ViewProviderMaterialObject, Gui::ViewProviderDocumentObjectGroup, FemGui::ViewProviderResult, TechDrawGui::ViewProviderPage, Gui::ViewProviderVarSet, TechDrawGui::ViewProviderDrawingView, TechDrawGui::ViewProviderTemplate, FemGui::ViewProviderSolver, and Gui::ViewProviderTextDocument.
Definition at line 464 of file Gui/ViewProvider.cpp.
References pcModeSwitch.
Referenced by PartGui::ViewProviderPartExt::forceUpdate(), Gui::Document::isShow(), isVisible(), PartDesignGui::ViewProvider::onDelete(), Gui::SelectionSingleton::setVisible(), Gui::DocumentObjectItem::testStatus(), update(), and Gui::ViewProviderDocumentObject::updateView().
isUpdatesEnabled()
bool ViewProvider::isUpdatesEnabled () const
Definition at line 181 of file Gui/ViewProvider.cpp.
References testStatus(), and Gui::UpdateData.
Referenced by update().
isVisible()
bool ViewProvider::isVisible () const
Definition at line 474 of file Gui/ViewProvider.cpp.
References isShow().
Referenced by PartDesignGui::ViewProviderDatum::getRelevantBoundBox(), MeshGui::MeshSelection::getViewProviders(), MeasureGui::ViewProviderMeasureBase::isSubjectVisible(), ArchVRM.Renderer::removeHidden(), Gui::ViewProviderCoordinateSystem::setTemporaryVisibility(), and FemGui::ViewProviderFemPostPipeline::updateColorBars().
keyPressed()
bool ViewProvider::keyPressed (bool pressed, int key) virtual
is called when the provider is in edit and a key event occurs. Only ESC ends edit.
Reimplemented in SketcherGui::ViewProviderSketch, and AssemblyGui::ViewProviderAssembly.
Definition at line 637 of file Gui/ViewProvider.cpp.
mergeColorfulOverlayIcons()
QIcon ViewProvider::mergeColorfulOverlayIcons (const QIcon & orig) const virtual
Reimplemented in SketcherGui::ViewProviderSketch, and PartDesignGui::ViewProvider.
Definition at line 335 of file Gui/ViewProvider.cpp.
References create_qrc::ext.
Referenced by PartDesignGui::ViewProvider::mergeColorfulOverlayIcons(), SketcherGui::ViewProviderSketch::mergeColorfulOverlayIcons(), and Gui::DocumentObjectItem::testStatus().
mergeGreyableOverlayIcons()
QIcon ViewProvider::mergeGreyableOverlayIcons (const QIcon & orig) const protected virtual
Definition at line 321 of file Gui/ViewProvider.cpp.
References create_qrc::ext.
Referenced by Gui::ViewProviderLink::_setupContextMenu(), PartDesignGui::ViewProviderPrimitive::getIcon(), Gui::ViewProviderDocumentObjectGroup::getIcon(), PartDesignGui::ViewProviderHelix::getIcon(), Gui::ViewProviderPart::getIcon(), PartDesignGui::ViewProviderPipe::getIcon(), PartDesignGui::ViewProviderLoft::getIcon(), getIcon(), Gui::ViewProviderDragger::setupContextMenu(), PartDesignGui::ViewProvider::setupContextMenu(), and PartGui::ViewProviderPartExt::setupContextMenu().
mouseButtonPressed()
bool ViewProvider::mouseButtonPressed (int button, bool pressed, const SbVec2s & cursorPos, const View3DInventorViewer * viewer) virtual
is called when the Provider is in edit and the mouse is clicked
Reimplemented in SketcherGui::ViewProviderSketch, and AssemblyGui::ViewProviderAssembly.
Definition at line 652 of file Gui/ViewProvider.cpp.
References OfflineRenderingUtils::viewer().
mouseMove()
bool ViewProvider::mouseMove (const SbVec2s & cursorPos, View3DInventorViewer * viewer) virtual
is called when the provider is in edit and the mouse is moved
Reimplemented in SketcherGui::ViewProviderSketch, and AssemblyGui::ViewProviderAssembly.
Definition at line 644 of file Gui/ViewProvider.cpp.
References OfflineRenderingUtils::viewer().
mouseWheelEvent()
bool ViewProvider::mouseWheelEvent (int delta, const SbVec2s & cursorPos, const View3DInventorViewer * viewer) virtual
Reimplemented in SketcherGui::ViewProviderSketch.
Definition at line 663 of file Gui/ViewProvider.cpp.
References OfflineRenderingUtils::viewer().
onBeforeChange()
void ViewProvider::onBeforeChange (const App::Property * prop) override protected virtual
Reimplemented from subclass.
Reimplemented from App::PropertyContainer.
Reimplemented in Gui::ViewProviderDocumentObject, and Gui::ViewProviderLink.
Definition at line 528 of file Gui/ViewProvider.cpp.
References Gui::Application::Instance, App::PropertyContainer::onBeforeChange(), and Gui::Application::signalBeforeChangeObject.
Referenced by Gui::ViewProviderDocumentObject::onBeforeChange().
onChanged()
void ViewProvider::onChanged (const App::Property * prop) override protected virtual
Reimplemented from subclass.
Reimplemented from App::PropertyContainer.
Reimplemented in SketcherGui::ViewProviderSketch, MeshGui::ViewProviderMesh, Gui::ViewProviderLink, Gui::ViewProviderDocumentObject, MeasureGui::ViewProviderMeasure, PartGui::ViewProviderPartExt, FemGui::ViewProviderFemMesh, FemGui::ViewProviderFemPostFunction, MeasureGui::ViewProviderMeasureBase, FemGui::ViewProviderFemPostFunctionProvider, TechDrawGui::ViewProviderViewPart, Gui::ViewProviderAnnotationLabel, MeshGui::ViewProviderMeshCurvature, Gui::ViewProviderDragger, PointsGui::ViewProviderPoints, Gui::ViewProviderGeometryObject, MeasureGui::ViewProviderMeasureDistance, TechDrawGui::ViewProviderBalloon, Gui::ViewProviderPart, PartDesignGui::ViewProviderSubShapeBinder, TechDrawGui::ViewProviderViewSection, FemGui::ViewProviderFemPostObject, PartDesignGui::ViewProviderBoolean, TechDrawGui::ViewProviderPage, PathGui::ViewProviderPath, TechDrawGui::ViewProviderImage, PartDesignGui::ViewProviderDatumPoint, FemGui::ViewProviderFemConstraint, FemGui::ViewProviderFemPostDataAtPoint, InspectionGui::ViewProviderInspection, SketcherGui::ViewProviderCustom, PartGui::ViewProviderCustom, PartGui::ViewProviderPartReference, PartGui::ViewProvider2DObjectGrid, PartDesignGui::ViewProvider, PartDesignGui::ViewProviderBody, TechDrawGui::ViewProviderDrawingView, Gui::ViewProviderAnnotation, Gui::ViewProviderDatum, Gui::ViewProviderPlacement, MeshGui::ViewProviderMeshDefects, RobotGui::ViewProviderRobotObject, TechDrawGui::ViewProviderGeomHatch, TechDrawGui::ViewProviderRichAnno, TechDrawGui::ViewProviderHatch, Gui::ViewProviderImagePlane, TechDrawGui::ViewProviderTemplate, Gui::ViewProviderTextDocument, TechDrawGui::ViewProviderDimension, TechDrawGui::ViewProviderWeld, TechDrawGui::ViewProviderLeader, FemGui::ViewProviderFemPostPlaneFunction, and PartDesignGui::ViewProviderDatumCoordinateSystem.
Definition at line 535 of file Gui/ViewProvider.cpp.
References Gui::Application::Instance, App::ExtensionContainer::onChanged(), Gui::Application::signalChangedObject, and Gui::Application::updateActions().
Referenced by draftviewproviders.view_base.ViewProviderDraft::attach(), Gui::ViewProviderDocumentObject::onChanged(), ArchSpace._ViewProviderSpace::onChanged(), ArchSchedule._ArchSchedule::setProperties(), draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), ArchAxis._ViewProviderAxis::updateData(), draftviewproviders.view_dimension.ViewProviderLinearDimension::updateData(), ArchSpace._ViewProviderSpace::updateData(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchSite._ViewProviderSite::updateData(), ArchSectionPlane._ViewProviderSectionPlane::updateData(), and ArchPanel.ViewProviderPanelSheet::updateData().
onDelete()
virtual bool Gui::ViewProvider::onDelete (const std::vector< std::string > & subNames) virtual
Get called if the object is about to get deleted. Here you can delete other objects, switch their visibility or prevent the deletion of the object.
Parameters
subNames list of selected subelements
Returns
true if the deletion is approved by the view provider.
Reimplemented in AssemblyGui::ViewProviderAssembly, AssemblyGui::ViewProviderAssemblyLink, PartDesignGui::ViewProviderHole, TechDrawGui::ViewProviderDimension, TechDrawGui::ViewProviderBalloon, TechDrawGui::ViewProviderProjGroup, TechDrawGui::ViewProviderLeader, FemGui::ViewProviderFemPostPipeline, SketcherGui::ViewProviderSketch, Gui::ViewProviderLink, PartGui::ViewProviderThickness, PartGui::ViewProviderOffset, PartGui::ViewProviderSweep, PartGui::ViewProviderLoft, PartGui::ViewProviderRevolution, FemGui::ViewProviderFemPostObject, PartGui::ViewProviderChamfer, TechDrawGui::ViewProviderViewPart, Gui::ViewProviderCoordinateSystem, PartGui::ViewProviderMultiCommon, FemGui::ViewProviderFemPostFunctionProvider, PartDesignGui::ViewProvider, TechDrawGui::ViewProviderWeld, AssemblyGui::ViewProviderJointGroup, TechDrawGui::ViewProviderProjGroupItem, TechDrawGui::ViewProviderPage, PartDesignGui::ViewProviderBoolean, PartDesignGui::ViewProviderPipe, PartDesignGui::ViewProviderLoft, PartGui::ViewProviderFillet, FemGui::ViewProviderFemAnalysis, PathGui::ViewProviderAreaView, PartDesignGui::ViewProviderHelix, PartGui::ViewProviderBoolean, PartDesignGui::ViewProviderSketchBased, PartGui::ViewProviderRuledSurface, PartDesignGui::ViewProviderMultiTransform, PathGui::ViewProviderArea, PartGui::ViewProviderMultiFuse, PartGui::ViewProviderMirror, PartGui::ViewProviderCompound, PathGui::ViewProviderPathShape, PartDesignGui::ViewProviderBody, Gui::ViewProviderDatum, PartDesignGui::ViewProviderTransformed, TechDrawGui::ViewProviderTemplate, FemGui::ViewProviderSolver, PartDesignGui::ViewProviderDatum, and DrawingGui::ViewProviderDrawingPage.
Referenced by StdCmdDelete::activated(), SketcherGui::ConstraintView::deleteSelectedItems(), SketcherGui::ElementView::deleteSelectedItems(), and SketcherGui::ViewProviderSketch::onDelete().
partialRender()
int ViewProvider::partialRender (const std::vector< std::string > & subelements, bool clear)
partial rendering setup
Parameters
subelements a list of dot separated string refer to the sub element
clear if true, remove the subelement from partial rendering. If else, add the subelement for rendering.
Returns
Return the number of subelement found
Partial rendering only works if there is at least one SoFCSelectRoot node in this view provider
Definition at line 950 of file Gui/ViewProvider.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::SoSelectionElementAction::Append, Path.Op.Gui.Selection::clear(), src.Mod.AddonManager.NetworkManager::count, FC_LOG, getDetailPath(), hasHiddenMarker(), hiddenMarker(), Gui::SoSelectionElementAction::Hide, Gui::SoSelectionElementAction::None, pcModeSwitch, Gui::SoSelectionElementAction::Remove, and Gui::SoSelectionElementAction::Show.
Referenced by Gui::ElementColors::leaveEvent().
replaceObject()
int ViewProvider::replaceObject (App::DocumentObject * oldObj, App::DocumentObject * newObj) virtual
Replace an object to the view provider by drag and drop
Parameters
oldObj object to be replaced
newObj object to replace with
Returns
Returns 0 if not found, 1 if succeeded, -1 if not supported
Reimplemented in Gui::ViewProviderDocumentObject.
Definition at line 805 of file Gui/ViewProvider.cpp.
References create_qrc::ext.
Referenced by Gui::ViewProviderDocumentObject::replaceObject().
Restore()
void ViewProvider::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Reimplemented in PartGui::ViewProvider2DObjectGrid.
Definition at line 818 of file Gui/ViewProvider.cpp.
References TechDrawTools.TaskFillTemplateFields::reader, and App::Restore.
Referenced by Gui::Document::importObjects(), PartGui::ViewProvider2DObjectGrid::Restore(), and Gui::Document::RestoreDocFile().
selectAll()
virtual bool Gui::ViewProvider::selectAll () inline virtual
is called when the provider is in edit and a "Select All" command was issued Provider shall return 'false' is it ignores the command, 'true' otherwise
Reimplemented in SketcherGui::ViewProviderSketch.
Definition at line 474 of file Gui/ViewProvider.h.
Referenced by Gui::ViewerEventFilter::eventFilter().
setDefaultMode()
void ViewProvider::setDefaultMode (int val)
Definition at line 517 of file Gui/ViewProvider.cpp.
References create_qrc::ext, and toolbit-attributes::val.
setDisplayMaskMode()
void ViewProvider::setDisplayMaskMode (const char * type)
Activates the display mask mode type.
Definition at line 375 of file Gui/ViewProvider.cpp.
References setModeSwitch(), and Path.Post.scripts.grbl_post::type.
Referenced by FemGui::ViewProviderFemPostObject::attach(), FemGui::ViewProviderFemPostFunction::attach(), Gui::ViewProviderLink::attach(), Gui::ViewProviderGeoFeatureGroupExtension::extensionSetDisplayMode(), PartDesignGui::ViewProviderBody::onChanged(), Gui::ViewProviderVRMLObject::setDisplayMode(), Gui::ViewProviderImagePlane::setDisplayMode(), Gui::ViewProviderDatum::setDisplayMode(), PartGui::ViewProviderCurveNet::setDisplayMode(), Gui::ViewProviderPlacement::setDisplayMode(), FemGui::ViewProviderFemConstraint::setDisplayMode(), PartDesignGui::ViewProviderDatum::setDisplayMode(), MeshPartGui::ViewProviderCurveOnMesh::setDisplayMode(), Gui::ViewProviderAnnotation::setDisplayMode(), MeshGui::ViewProviderMeshTransform::setDisplayMode(), InspectionGui::ViewProviderInspection::setDisplayMode(), MeshGui::ViewProviderMeshTransformDemolding::setDisplayMode(), MeshGui::ViewProviderFace::setDisplayMode(), PartGui::ViewProviderPartReference::setDisplayMode(), Gui::ViewProviderCoordinateSystem::setDisplayMode(), FemGui::ViewProviderFemMesh::setDisplayMode(), Gui::ViewProviderInventorObject::setDisplayMode(), PartGui::ViewProviderPartExt::setDisplayMode(), Gui::ViewProviderAnnotationLabel::setDisplayMode(), MeshGui::ViewProviderMesh::setDisplayMode(), Gui::ViewProviderExtern::setModeBySoInput(), and PartDesignGui::ViewProviderAddSub::setPreviewDisplayMode().
setDisplayMode()
void ViewProvider::setDisplayMode (const char * ModeName) virtual
set the display mode
If you add new viewing modes in getDisplayModes() then you need to reimplement also seDisplaytMode() to handle these new modes by setting the appropriate display mode.
Reimplemented in MeshGui::ViewProviderMesh, Gui::ViewProviderAnnotationLabel, MeasureGui::ViewProviderMeasureBase, FemGui::ViewProviderFemPostObject, PartGui::ViewProviderPartExt, SpreadsheetGui::ViewProviderSheet, PointsGui::ViewProviderPoints, MeshGui::ViewProviderMeshCurvature, Gui::ViewProviderInventorObject, FemGui::ViewProviderFemMesh, Gui::ViewProviderCoordinateSystem, PartGui::ViewProviderPartReference, PathGui::ViewProviderPath, MeshGui::ViewProviderFace, MeshGui::ViewProviderMeshTransformDemolding, InspectionGui::ViewProviderInspection, Gui::ViewProviderAnnotation, MeshGui::ViewProviderMeshTransform, PartDesignGui::ViewProviderBody, MeshPartGui::ViewProviderCurveOnMesh, PartDesignGui::ViewProviderDatum, FemGui::ViewProviderFemConstraint, Gui::ViewProviderPlacement, PartGui::ViewProviderCurveNet, RobotGui::ViewProviderRobotObject, RobotGui::ViewProviderTrajectory, Gui::ViewProviderDatum, Gui::ViewProviderImagePlane, Gui::ViewProviderVRMLObject, DrawingGui::ViewProviderDrawingClip, DrawingGui::ViewProviderDrawingView, and DrawingGui::ViewProviderDrawingPage.
Definition at line 408 of file Gui/ViewProvider.cpp.
References create_qrc::ext.
Referenced by Gui::ViewProviderDocumentObject::setActiveMode(), Gui::ViewProviderVRMLObject::setDisplayMode(), Gui::ViewProviderImagePlane::setDisplayMode(), Gui::ViewProviderDatum::setDisplayMode(), RobotGui::ViewProviderTrajectory::setDisplayMode(), RobotGui::ViewProviderRobotObject::setDisplayMode(), Gui::ViewProviderPlacement::setDisplayMode(), Gui::ViewProviderAnnotation::setDisplayMode(), Gui::ViewProviderCoordinateSystem::setDisplayMode(), Gui::ViewProviderInventorObject::setDisplayMode(), and Gui::ViewProviderAnnotationLabel::setDisplayMode().
setEdit()
bool ViewProvider::setEdit (int ModNum) protected virtual
is called by the document when the provider goes in edit mode
Reimplemented in Gui::ViewProviderDatum, SketcherGui::ViewProviderSketch, Gui::ViewProviderLink, MeshGui::ViewProviderMesh, PartGui::ViewProviderThickness, PartGui::ViewProviderOffset, PartGui::ViewProviderPartExt, FemGui::ViewProviderFemPostFunction, TechDrawGui::ViewProviderPage, FemGui::ViewProviderFemAnalysis, TechDrawGui::ViewProviderDimension, PartGui::ViewProviderChamfer, PartDesignGui::ViewProviderDatum, TechDrawGui::ViewProviderViewPart, AssemblyGui::ViewProviderAssembly, SpreadsheetGui::ViewProviderSheet, TechDrawGui::ViewProviderBalloon, PartDesignGui::ViewProvider, TechDrawGui::ViewProviderProjGroupItem, FemGui::ViewProviderFemPostObject, Gui::ViewProviderDragger, PartDesignGui::ViewProviderBoolean, PartDesignGui::ViewProviderLoft, TechDrawGui::ViewProviderProjGroup, TechDrawGui::ViewProviderViewSection, PartDesignGui::ViewProviderPipe, PartDesignGui::ViewProviderSubShapeBinder, PointsGui::ViewProviderPoints, PartGui::ViewProviderFillet, PartDesignGui::ViewProviderHelix, TechDrawGui::ViewProviderWeld, FemGui::ViewProviderFemConstraintTransform, FemGui::ViewProviderFemConstraintDisplacement, FemGui::ViewProviderFemConstraintHeatflux, FemGui::ViewProviderFemConstraintInitialTemperature, FemGui::ViewProviderFemConstraintTemperature, FemGui::ViewProviderFemConstraintContact, FemGui::ViewProviderFemConstraintPlaneRotation, AssemblyGui::ViewProviderAssemblyLink, FemGui::ViewProviderFemConstraint, FemGui::ViewProviderFemConstraintFixed, FemGui::ViewProviderFemConstraintFluidBoundary, FemGui::ViewProviderFemConstraintForce, FemGui::ViewProviderFemConstraintBearing, FemGui::ViewProviderFemConstraintGear, FemGui::ViewProviderFemConstraintPulley, PartDesignGui::ViewProviderHole, PartDesignGui::ViewProviderPrimitive, FemGui::ViewProviderFemMeshShapeNetgen, PartGui::ViewProviderMirror, PartGui::ViewProviderPrimitive, PartGui::ViewProviderProjectOnSurface, PathGui::ViewProviderPathCompound, FemGui::ViewProviderFemConstraintPressure, FemGui::ViewProviderFemConstraintRigidBody, FemGui::ViewProviderFemConstraintSpring, PartDesignGui::ViewProviderBase, PartDesignGui::ViewProviderShapeBinder, FemGui::ViewProviderSetElementNodes, RobotGui::ViewProviderTrajectoryDressUp, PartDesignGui::ViewProviderDressUp, RobotGui::ViewProviderTrajectoryCompound, FemGui::ViewProviderSetElements, FemGui::ViewProviderSetFaces, FemGui::ViewProviderSetGeometry, FemGui::ViewProviderSetNodes, PartGui::ViewProvider2DObjectGrid, RobotGui::ViewProviderEdge2TracObject, PartDesignGui::ViewProviderTransformed, PartGui::ViewProviderCurveNet, SurfaceGui::ViewProviderFilling, SurfaceGui::ViewProviderSections, TechDrawGui::ViewProviderLeader, TechDrawGui::ViewProviderGeomHatch, TechDrawGui::ViewProviderHatch, SurfaceGui::ViewProviderGeomFillSurface, PartGui::ViewProviderImport, and DrawingGui::ViewProviderDrawingPage.
Definition at line 161 of file Gui/ViewProvider.cpp.
Referenced by Path.Base.Gui.PropertyBag.ViewProvider::doubleClicked(), Path.Base.Gui.SetupSheet.ViewProvider::doubleClicked(), Path.Tool.Gui.Bit.ViewProvider::doubleClicked(), TechDrawGui::ViewProviderHatch::setEdit(), TechDrawGui::ViewProviderLeader::setEdit(), TechDrawGui::ViewProviderWeld::setEdit(), TechDrawGui::ViewProviderBalloon::setEdit(), TechDrawGui::ViewProviderViewPart::setEdit(), TechDrawGui::ViewProviderDimension::setEdit(), FemGui::ViewProviderFemAnalysis::setEdit(), TechDrawGui::ViewProviderPage::setEdit(), Path.Base.Gui.IconViewProvider.ViewProvider::setupContextMenu(), Path.Tool.Gui.Controller.ViewProvider::setupContextMenu(), Path.Op.Gui.Base.ViewProvider::setupContextMenu(), Path.Main.Gui.Job.ViewProvider::setupContextMenu(), and startEditing().
setEditViewer()
void ViewProvider::setEditViewer (View3DInventorViewer * , int ModNum) virtual
adjust viewer settings when editing a view provider
Reimplemented in Gui::ViewProviderLink, Gui::ViewProviderDragger, SketcherGui::ViewProviderSketch, and AssemblyGui::ViewProviderAssembly.
Definition at line 172 of file Gui/ViewProvider.cpp.
Referenced by Gui::View3DInventorViewer::setEditingViewProvider().
setElementColors()
virtual void Gui::ViewProvider::setElementColors (const std::map< std::string, App::Color > & colors) inline virtual
Reimplemented in Gui::ViewProviderLink.
Definition at line 425 of file Gui/ViewProvider.h.
References importers.importIFCmulticore::colors.
Referenced by Gui::ElementColors::Private::apply().
setLinkVisible()
void ViewProvider::setLinkVisible (bool visible)
Definition at line 1073 of file Gui/ViewProvider.cpp.
References create_qrc::ext.
setModeSwitch()
void ViewProvider::setModeSwitch () protected virtual
Turn on mode switch.
Reimplemented in Gui::ViewProviderDocumentObject.
Definition at line 505 of file Gui/ViewProvider.cpp.
References create_qrc::ext, and pcModeSwitch.
Referenced by setDisplayMaskMode(), Gui::ViewProviderDocumentObject::setModeSwitch(), setOverrideMode(), and show().
setOverrideMode()
void ViewProvider::setOverrideMode (const std::string & mode) virtual
Overrides the display mode with mode.
Reimplemented in Gui::ViewProviderLink, and PartDesignGui::ViewProviderBody.
Definition at line 479 of file Gui/ViewProvider.cpp.
References create_qrc::ext, overrideMode, pcModeSwitch, and setModeSwitch().
Referenced by Gui::View3DInventorViewer::addViewProvider(), PartDesignGui::ViewProviderBody::onChanged(), PartDesignGui::ViewProviderBody::setOverrideMode(), and Gui::ViewProviderLink::setOverrideMode().
setRenderCacheMode()
void ViewProvider::setRenderCacheMode (int mode) virtual
Definition at line 1000 of file Gui/ViewProvider.cpp.
References MeshCore::MeshIO::OFF, and pcRoot.
setStatus()
void Gui::ViewProvider::setStatus (ViewStatus pos, bool on) inline
Definition at line 388 of file Gui/ViewProvider.h.
References RobotExample::pos.
Referenced by Gui::Document::addViewProvider(), Gui::ViewProviderDocumentObject::detachFromDocument(), Gui::Document::importObjects(), setUpdatesEnabled(), Gui::Document::slotFinishRestoreObject(), PartDesignGui::ViewProviderDatumPoint::ViewProviderDatumPoint(), DrawingGui::ViewProviderDrawingClip::ViewProviderDrawingClip(), DrawingGui::ViewProviderDrawingView::ViewProviderDrawingView(), PartDesignGui::ViewProviderShapeBinder::ViewProviderShapeBinder(), and TechDrawGui::ViewProviderViewClip::ViewProviderViewClip().
setTransformation() [1/2]
void ViewProvider::setTransformation (const Base::Matrix4D & rcMatrix) virtual
set the viewing transformation of the provider
Reimplemented in Gui::ViewProviderLink.
Definition at line 349 of file Gui/ViewProvider.cpp.
References convert(), and pcTransform.
Referenced by Gui::Dialog::TransformStrategy::acceptDataTransform(), Gui::Dialog::TransformStrategy::applyViewTransform(), Gui::ViewProviderGeoFeatureGroupExtension::extensionUpdateData(), Gui::Dialog::TransformStrategy::resetViewTransform(), Gui::Document::setPos(), Gui::ViewProviderLink::setTransformation(), and RobotGui::ViewProviderRobotObject::updateData().
setTransformation() [2/2]
void ViewProvider::setTransformation (const SbMatrix & rcMatrix) virtual
Reimplemented in Gui::ViewProviderLink.
Definition at line 354 of file Gui/ViewProvider.cpp.
References pcTransform.
setupContextMenu()
void ViewProvider::setupContextMenu (QMenu * menu, QObject * receiver, const char * method) virtual
set up the context-menu with the supported edit modes
Reimplemented in SketcherGui::ViewProviderSketch, MeshGui::ViewProviderMesh, AssemblyGui::ViewProviderAssembly, TechDrawGui::ViewProviderBalloon, PartDesignGui::ViewProvider, SpreadsheetGui::ViewProviderSheet, PartDesignGui::ViewProviderSubShapeBinder, PartDesignGui::ViewProviderPrimitive, Gui::ViewProviderPart, FemGui::ViewProviderFemMeshShapeNetgen, PartGui::ViewProviderProjectOnSurface, PartDesignGui::ViewProviderHole, PartDesignGui::ViewProviderBase, PartDesignGui::ViewProviderBody, RobotGui::ViewProviderTrajectory, Gui::ViewProviderTextDocument, Gui::ViewProviderLink, PartGui::ViewProviderThickness, PartGui::ViewProviderOffset, PartGui::ViewProviderPartExt, TechDrawGui::ViewProviderDimension, AssemblyGui::ViewProviderAssemblyLink, PartGui::ViewProviderChamfer, FemGui::ViewProviderFemAnalysis, TechDrawGui::ViewProviderPage, PartDesignGui::ViewProviderBoolean, PartDesignGui::ViewProviderPipe, PartDesignGui::ViewProviderLoft, TechDrawGui::ViewProviderProjGroupItem, PartGui::ViewProviderFillet, PartDesignGui::ViewProviderDraft, PartDesignGui::ViewProviderChamfer, PartDesignGui::ViewProviderFillet, PartDesignGui::ViewProviderThickness, PartGui::ViewProviderHelixParametric, PartGui::ViewProviderPrimitive, PartDesignGui::ViewProviderMultiTransform, PartDesignGui::ViewProviderGroove, PartDesignGui::ViewProviderHelix, PartDesignGui::ViewProviderMirrored, PartDesignGui::ViewProviderPocket, PartDesignGui::ViewProviderPolarPattern, PartDesignGui::ViewProviderRevolution, PartDesignGui::ViewProviderScaled, PartGui::ViewProviderMirror, PartDesignGui::ViewProviderLinearPattern, PartDesignGui::ViewProviderPad, PartDesignGui::ViewProviderShapeBinder, PartGui::ViewProviderSpiralParametric, Gui::ViewProviderDragger, PartDesignGui::ViewProviderDressUp, PartDesignGui::ViewProviderTransformed, SurfaceGui::ViewProviderFilling, FemGui::ViewProviderFemConstraint, SurfaceGui::ViewProviderSections, Gui::ViewProviderImagePlane, PartDesignGui::ViewProviderDatum, SurfaceGui::ViewProviderGeomFillSurface, and DrawingGui::ViewProviderDrawingPage.
Definition at line 671 of file Gui/ViewProvider.cpp.
References create_qrc::ext, and NavigationIndicatorGui::menu.
Referenced by Gui::ViewProviderLink::_setupContextMenu(), Gui::ViewProviderTextDocument::setupContextMenu(), PartDesignGui::ViewProviderDatum::setupContextMenu(), Gui::ViewProviderDragger::setupContextMenu(), TechDrawGui::ViewProviderPage::setupContextMenu(), PartDesignGui::ViewProvider::setupContextMenu(), TechDrawGui::ViewProviderBalloon::setupContextMenu(), TechDrawGui::ViewProviderDimension::setupContextMenu(), and SketcherGui::ViewProviderSketch::setupContextMenu().
setUpdatesEnabled()
void ViewProvider::setUpdatesEnabled (bool enable)
Definition at line 186 of file Gui/ViewProvider.cpp.
References setStatus(), and Gui::UpdateData.
setVisible()
void ViewProvider::setVisible (bool s)
Definition at line 469 of file Gui/ViewProvider.cpp.
References hide(), toolbit-attributes::s, and show().
Referenced by FemGui::TaskDlgFemConstraint::open(), and Gui::ViewProviderCoordinateSystem::setTemporaryVisibility().
show()
void ViewProvider::show () virtual
Shows the view provider.
Reimplemented in DrawingGui::ViewProviderDrawingClip, DrawingGui::ViewProviderDrawingView, DrawingGui::ViewProviderDrawingPage, MeasureGui::ViewProviderMeasureBase, FemGui::ViewProviderFemAnalysis, MeshGui::ViewProviderMeshCurvature, FemGui::ViewProviderFemPostObject, TechDrawGui::ViewProviderViewClip, FemGui::ViewProviderFemPostDataAtPoint, TechDrawGui::ViewProviderPage, InspectionGui::ViewProviderInspection, Gui::ViewProviderDocumentObject, TechDrawGui::ViewProviderDrawingView, and TechDrawGui::ViewProviderTemplate.
Definition at line 454 of file Gui/ViewProvider.cpp.
References create_qrc::ext, and setModeSwitch().
Referenced by PartGui::DlgFilletEdges::accept(), PartDesignGui::ViewProvider::makeTemporaryVisible(), PartDesignGui::ViewProvider::onDelete(), PartGui::ViewProviderOffset::onDelete(), PartGui::ViewProviderThickness::onDelete(), PartGui::ThicknessWidget::reject(), PartGui::OffsetWidget::reject(), PartDesignGui::TaskDlgSketchBasedParameters::reject(), PartDesignGui::TaskDlgFeatureParameters::reject(), PartGui::DlgFilletEdges::setupFillet(), setVisible(), Gui::ViewProviderDocumentObject::show(), src.Mod.Show.mTempoVis.TempoVis::show_all_dependencies(), src.Mod.Show.mTempoVis.TempoVis::show_all_dependent(), Gui::Application::showViewProvider(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined(), update(), and Gui::ViewProviderDocumentObject::updateView().
showInTree()
virtual bool Gui::ViewProvider::showInTree () const inline virtual
Tell the tree view if this object should appear there
Reimplemented in Gui::ViewProviderDocumentObject.
Definition at line 358 of file Gui/ViewProvider.h.
startEditing()
ViewProvider * ViewProvider::startEditing (int ModNum = 0) virtual
Reimplemented in Gui::ViewProviderDragger, PartDesignGui::ViewProviderTransformed, Gui::ViewProviderLink, and PartDesignGui::ViewProvider.
Definition at line 136 of file Gui/ViewProvider.cpp.
References setEdit().
Referenced by Gui::ViewProviderDragger::forwardToLink(), draftguitools.gui_edit.Edit::mousePressed(), PartDesignGui::ViewProvider::setEdit(), PartDesignGui::ViewProviderTransformed::startEditing(), Gui::ViewProviderDragger::startEditing(), Gui::ViewProviderLink::startEditing(), and Gui::DocumentP::tryStartEditing().
testStatus()
bool Gui::ViewProvider::testStatus (ViewStatus pos) const inline
Definition at line 387 of file Gui/ViewProvider.h.
References RobotExample::pos.
Referenced by Gui::ViewProviderDocumentObject::isAttachedToDocument(), isUpdatesEnabled(), Gui::ViewProviderGeometryObject::onChanged(), Gui::ViewProviderDocumentObject::onChanged(), PartGui::ViewProviderPartExt::setHighlightedEdges(), PartGui::ViewProviderPartExt::setHighlightedFaces(), PartGui::ViewProviderPartExt::setHighlightedPoints(), and Gui::ViewProviderDocumentObject::updateView().
toString()
std::string ViewProvider::toString () const
Definition at line 543 of file Gui/ViewProvider.cpp.
References pcRoot, and Gui::SoFCDB::writeNodesToString().
unsetEdit()
void ViewProvider::unsetEdit (int ModNum) protected virtual
is called when you lose the edit mode
Reimplemented in Gui::ViewProviderDatum, SketcherGui::ViewProviderSketch, MeshGui::ViewProviderMesh, PartGui::ViewProviderThickness, PartGui::ViewProviderOffset, PartGui::ViewProviderPartExt, FemGui::ViewProviderFemPostFunction, FemGui::ViewProviderFemAnalysis, PartGui::ViewProviderChamfer, PartDesignGui::ViewProviderDatum, AssemblyGui::ViewProviderAssembly, TechDrawGui::ViewProviderPage, PartDesignGui::ViewProvider, FemGui::ViewProviderFemPostObject, Gui::ViewProviderDragger, PartDesignGui::ViewProviderLoft, PartDesignGui::ViewProviderPipe, PointsGui::ViewProviderPoints, PartGui::ViewProviderFillet, PartDesignGui::ViewProviderHelix, TechDrawGui::ViewProviderProjGroupItem, FemGui::ViewProviderFemConstraint, PartDesignGui::ViewProviderPrimitive, PartGui::ViewProviderMirror, PartGui::ViewProviderPrimitive, PartGui::ViewProviderProjectOnSurface, PathGui::ViewProviderPathCompound, PartDesignGui::ViewProviderBase, PartDesignGui::ViewProviderShapeBinder, FemGui::ViewProviderSetElementNodes, RobotGui::ViewProviderTrajectoryDressUp, RobotGui::ViewProviderTrajectoryCompound, FemGui::ViewProviderSetElements, FemGui::ViewProviderSetFaces, FemGui::ViewProviderSetGeometry, FemGui::ViewProviderSetNodes, PartGui::ViewProvider2DObjectGrid, RobotGui::ViewProviderEdge2TracObject, PartDesignGui::ViewProviderTransformed, PartGui::ViewProviderCurveNet, SurfaceGui::ViewProviderFilling, SurfaceGui::ViewProviderSections, SurfaceGui::ViewProviderGeomFillSurface, and PartGui::ViewProviderImport.
Definition at line 167 of file Gui/ViewProvider.cpp.
Referenced by finishEditing(), Path.Main.Gui.Job.ViewProvider::uneditObject(), and FemGui::ViewProviderFemAnalysis::unsetEdit().
unsetEditViewer()
void ViewProvider::unsetEditViewer (View3DInventorViewer *) virtual
restores viewer settings when leaving editing mode
Reimplemented in Gui::ViewProviderLink, Gui::ViewProviderDragger, and SketcherGui::ViewProviderSketch.
Definition at line 177 of file Gui/ViewProvider.cpp.
Referenced by Gui::View3DInventorViewer::resetEditingViewProvider().
update()
void ViewProvider::update (const App::Property * prop) virtual
update the content of the ViewProvider this method have to implement the recalculation of the ViewProvider. There are different reasons to update. E.g. only the view attribute has changed, or the data has manipulated.
Reimplemented in Gui::ViewProviderDocumentObject.
Definition at line 305 of file Gui/ViewProvider.cpp.
References hide(), isShow(), isUpdatesEnabled(), show(), and updateData().
Referenced by bimcommands.BimViews.BIM_Views::Activated(), ArchAxisSystem.AxisSystemTaskPanel::addElement(), ArchSectionPlane.SectionPlaneTaskPanel::addElement(), DraftGui.FacebinderTaskPanel::addElement(), ArchComponent.ComponentTaskPanel::addElement(), bimcommands.BimViews.BIM_Views::addLevel(), bimcommands.BimViews.BIM_Views::addProxy(), femtaskpanels.task_result_mechanical._TaskPanel::calculate(), bimcommands.BimIfcElements.BIM_IfcElements::checkMatChanged(), ArchWindow._ArchWindowTaskPanel::create(), bimcommands.BimViews.BIM_Views::delete(), draftguitools.gui_edit.Edit::endEditing(), bimcommands.BimWall.Arch_Wall::getPoint(), ArchStructure._CommandStructure::getPoint(), draftguitools.gui_trackers.boxTracker::height(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimTutorial.BIM_Tutorial::next(), bimcommands.BimIfcElements.BIM_IfcElements::onMaterialChanged(), bimcommands.BimIfcElements.BIM_IfcElements::onObjectTypeChanged(), bimcommands.BimIfcProperties.BIM_IfcProperties::onSelected(), bimcommands.BimIfcProperties.BIM_IfcProperties::onVisible(), draftguitools.gui_trackers.rectangleTracker::p3(), Plot.Plot::plot(), bimcommands.BimTutorial.BIM_Tutorial::previous(), ArchAxisSystem.AxisSystemTaskPanel::removeElement(), ArchAxis._AxisTaskPanel::removeElement(), ArchWindow._ArchWindowTaskPanel::removeElement(), ArchSectionPlane.SectionPlaneTaskPanel::removeElement(), DraftGui.FacebinderTaskPanel::removeElement(), ArchComponent.ComponentTaskPanel::removeElement(), draftguitools.gui_trackers.gridTracker::reset(), ArchRoof._RoofTaskPanel::resetObject(), ArchNesting.Nester::run(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setDescription(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setHeight(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setLabel(), draftguitools.gui_trackers.gridTracker::setMainlines(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setMaterial(), draftguitools.gui_trackers.gridTracker::setSize(), draftguitools.gui_trackers.gridTracker::setSpacing(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setTag(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setWidth(), Gui::Document::slotChangedObject(), Gui::ViewProviderDocumentObject::update(), and bimcommands.BimViews.BIM_Views::update().
updateData()
void ViewProvider::updateData (const App::Property * prop) virtual
Reimplemented in MeshGui::ViewProviderMeshObject, MeshGui::ViewProviderIndexedFaceSet, MeshGui::ViewProviderMesh, SpreadsheetGui::ViewProviderSheet, TechDrawGui::ViewProviderBalloon, MeasureGui::ViewProviderMeasureBase, TechDrawGui::ViewProviderPage, MeshGui::ViewProviderMeshCurvature, FemGui::ViewProviderFemPostPipeline, MeshGui::ViewProviderMeshFaceSet, PartDesignGui::ViewProviderBody, TechDrawGui::ViewProviderRichAnno, FemGui::ViewProviderFemConstraint, SketcherGui::ViewProviderSketch, FemGui::ViewProviderFemPostSphereFunction, FemGui::ViewProviderFemPostPlaneFunction, FemGui::ViewProviderFemPostCylinderFunction, FemGui::ViewProviderFemPostBoxFunction, Gui::ViewProviderLink, PointsGui::ViewProviderStructured, PointsGui::ViewProviderScattered, FemGui::ViewProviderFemPostFunctionProvider, TechDrawGui::ViewProviderDimension, PartGui::ViewProviderChamfer, Gui::ViewProviderCoordinateSystem, PartGui::ViewProviderMultiCommon, Gui::ViewProviderAnnotationLabel, PartGui::ViewProviderPartExt, TechDrawGui::ViewProviderViewSection, FemGui::ViewProviderFemPostObject, PartGui::ViewProviderCompound, PartGui::ViewProviderFillet, MeshPartGui::ViewProviderCrossSections, TechDrawGui::ViewProviderAnnotation, FemGui::ViewProviderFemConstraintTransform, TechDrawGui::ViewProviderImage, TechDrawGui::ViewProviderProjGroupItem, TechDrawGui::ViewProviderSymbol, FemGui::ViewProviderFemConstraintDisplacement, FemGui::ViewProviderFemConstraintHeatflux, FemGui::ViewProviderFemConstraintInitialTemperature, FemGui::ViewProviderFemConstraintTemperature, Gui::ViewProviderInventorObject, FemGui::ViewProviderFemConstraintContact, FemGui::ViewProviderFemConstraintPlaneRotation, PathGui::ViewProviderAreaView, PartGui::ViewProviderCrossSections, FemGui::ViewProviderFemConstraintFixed, FemGui::ViewProviderFemConstraintFluidBoundary, FemGui::ViewProviderFemConstraintForce, PartGui::ViewProviderBoolean, FemGui::ViewProviderFemConstraintBearing, FemGui::ViewProviderFemConstraintGear, FemGui::ViewProviderFemConstraintPulley, FemGui::ViewProviderFemMesh, PartGui::ViewProviderRuledSurface, PartDesignGui::ViewProviderDatumPlane, PathGui::ViewProviderArea, PartGui::ViewProviderMultiFuse, PartDesignGui::ViewProviderAddSub, FemGui::ViewProviderFemConstraintPressure, FemGui::ViewProviderFemConstraintRigidBody, FemGui::ViewProviderFemConstraintSpring, FemGui::ViewProviderFemMeshShapeNetgen, PartDesignGui::ViewProviderPrimitive, SketcherGui::ViewProviderCustom, PartGui::ViewProviderCustom, PartGui::ViewProviderPartReference, PathGui::ViewProviderPathShape, Gui::ViewProviderDragger, PartDesignGui::ViewProvider, PathGui::ViewProviderPath, PartGui::ViewProvider2DObjectGrid, MeshGui::ViewProviderMeshTransform, Gui::ViewProviderGeometryObject, InspectionGui::ViewProviderInspection, TechDrawGui::ViewProviderDrawingView, Gui::ViewProviderAnnotation, PartGui::ViewProviderCurveNet, TechDrawGui::ViewProviderHatch, RobotGui::ViewProviderRobotObject, TechDrawGui::ViewProviderGeomHatch, Gui::ViewProviderExtern, RobotGui::ViewProviderTrajectory, Gui::ViewProviderPlacement, PartDesignGui::ViewProviderDatumCoordinateSystem, TechDrawGui::ViewProviderTemplate, Gui::ViewProviderImagePlane, Gui::ViewProviderVRMLObject, PartDesignGui::ViewProviderDatumLine, DrawingGui::ViewProviderDrawingClip, DrawingGui::ViewProviderDrawingView, and DrawingGui::ViewProviderDrawingPage.
Definition at line 830 of file Gui/ViewProvider.cpp.
References create_qrc::ext.
Referenced by Path.Main.Gui.JobDlg.JobCreate::exec_(), draftviewproviders.view_wire.ViewProviderWire::onChanged(), draftviewproviders.view_dimension.ViewProviderLinearDimension::onChanged(), draftviewproviders.view_dimension.ViewProviderAngularDimension::onChanged(), Path.Op.Gui.Base.TaskPanelPage::pageUpdateData(), Path.Base.Gui.SetupSheet.OpTaskPanel::setupUi(), Path.Base.Gui.PropertyBag.TaskPanel::setupUi(), update(), TechDrawGui::ViewProviderTemplate::updateData(), TechDrawGui::ViewProviderGeomHatch::updateData(), TechDrawGui::ViewProviderHatch::updateData(), Gui::ViewProviderAnnotation::updateData(), TechDrawGui::ViewProviderDrawingView::updateData(), DrawingGui::ViewProviderDrawingPage::updateData(), Gui::ViewProviderDragger::updateData(), PartGui::ViewProviderCustom::updateData(), SketcherGui::ViewProviderCustom::updateData(), TechDrawGui::ViewProviderProjGroupItem::updateData(), TechDrawGui::ViewProviderPage::updateData(), TechDrawGui::ViewProviderBalloon::updateData(), Gui::ViewProviderAnnotationLabel::updateData(), Gui::ViewProviderCoordinateSystem::updateData(), TechDrawGui::ViewProviderDimension::updateData(), FemGui::ViewProviderFemPostFunctionProvider::updateData(), Gui::ViewProviderLink::updateData(), FemGui::ViewProviderFemPostBoxFunction::updateData(), FemGui::ViewProviderFemPostCylinderFunction::updateData(), FemGui::ViewProviderFemPostPlaneFunction::updateData(), FemGui::ViewProviderFemPostSphereFunction::updateData(), and Gui::ViewProviderDocumentObject::updateView().
useNewSelectionModel()
bool ViewProvider::useNewSelectionModel () const virtual
indicates if the ViewProvider use the new Selection model
Reimplemented in TechDrawGui::ViewProviderViewPart, TechDrawGui::ViewProviderGeomHatch, DrawingGui::ViewProviderDrawingClip, DrawingGui::ViewProviderDrawingView, DrawingGui::ViewProviderDrawingPage, Gui::ViewProviderLink, MeshGui::ViewProviderMesh, TechDrawGui::ViewProviderDimension, PartGui::ViewProviderPartExt, MeasureGui::ViewProviderMeasureBase, TechDrawGui::ViewProviderBalloon, FemGui::ViewProviderFemMesh, SpreadsheetGui::ViewProviderSheet, TechDrawGui::ViewProviderWeld, TechDrawGui::ViewProviderAnnotation, Gui::ViewProviderInventorObject, TechDrawGui::ViewProviderImage, TechDrawGui::ViewProviderSymbol, TechDrawGui::ViewProviderViewClip, TechDrawGui::ViewProviderSpreadsheet, TechDrawGui::ViewProviderProjGroupItem, TechDrawGui::ViewProviderProjGroup, TechDrawGui::ViewProviderTile, MeshGui::ViewProviderMeshCurvature, TechDrawGui::ViewProviderPage, PathGui::ViewProviderPath, PartDesignGui::ViewProviderDatum, TechDrawGui::ViewProviderDrawingView, Gui::ViewProviderPlacement, TechDrawGui::ViewProviderLeader, TechDrawGui::ViewProviderHatch, TechDrawGui::ViewProviderRichAnno, and TechDrawGui::ViewProviderTemplate.
Definition at line 990 of file Gui/ViewProvider.cpp.
References Gui::ViewParams::getUseNewSelection(), and Gui::ViewParams::instance().
Referenced by Gui::SoFCUnifiedSelection::doAction(), Gui::View3DInventorPy::getObjectInfo(), Gui::View3DInventorPy::getObjectsInfo(), and Gui::View3DInventor::getObjInfoRay().
Member Data Documentation
overrideMode
std::string Gui::ViewProvider::overrideMode protected
Definition at line 584 of file Gui/ViewProvider.h.
Referenced by getOverrideMode(), PartDesignGui::ViewProviderBody::onChanged(), PartDesignGui::ViewProviderBody::setOverrideMode(), and setOverrideMode().
pcAnnotation
SoSeparator* Gui::ViewProvider::pcAnnotation {nullptr} protected
The root separator for annotations.
Definition at line 582 of file Gui/ViewProvider.h.
Referenced by getAnnotation(), and ~ViewProvider().
pcModeSwitch
SoSwitch* Gui::ViewProvider::pcModeSwitch protected
this is the mode switch, all the different viewing modes are collected here
Definition at line 580 of file Gui/ViewProvider.h.
Referenced by addDisplayMaskMode(), Gui::ViewProviderExtern::adjustDocumentName(), PartGui::ViewProviderPartExt::attach(), getBoundingBox(), Gui::ViewProviderPlacement::getDetailPath(), Gui::ViewProviderDocumentObject::getDetailPath(), getDetailPath(), Gui::ViewProviderLink::getDetailPath(), getDisplayMaskMode(), Gui::ViewProviderDocumentObject::getElementPicked(), hide(), isShow(), Gui::ViewProviderLink::onBeforeChange(), Gui::ViewProviderLink::onChanged(), partialRender(), setModeSwitch(), setOverrideMode(), PartDesignGui::ViewProviderAddSub::setPreviewDisplayMode(), and ~ViewProvider().
pcRoot
SoSeparator* Gui::ViewProvider::pcRoot protected
The root Separator of the ViewProvider.
Definition at line 575 of file Gui/ViewProvider.h.
Referenced by PartGui::ViewProviderPartExt::attach(), Gui::ViewProviderAnnotationLabel::attach(), getAnnotation(), getBoundingBox(), Gui::ViewProviderPlacement::getDetailPath(), getDetailPath(), Gui::ViewProviderLink::getDetailPath(), PartDesignGui::ViewProviderTransformed::setEdit(), PartGui::ViewProviderMirror::setEdit(), setRenderCacheMode(), Gui::ViewProviderGeometryObject::setSelectable(), Gui::ViewProviderGeometryObject::showBoundingBox(), MeshGui::ViewProviderMeshFaceSet::showOpenEdges(), MeshGui::ViewProviderIndexedFaceSet::showOpenEdges(), MeshGui::ViewProviderMeshObject::showOpenEdges(), toString(), PartDesignGui::ViewProviderTransformed::unsetEdit(), PartGui::ViewProviderMirror::unsetEdit(), SketcherGui::ViewProviderSketch::unsetEdit(), PartGui::ViewProviderCrossSections::ViewProviderCrossSections(), MeshPartGui::ViewProviderCrossSections::ViewProviderCrossSections(), Gui::ViewProviderGeometryObject::ViewProviderGeometryObject(), and ~ViewProvider().
pcTransform
SoTransform* Gui::ViewProvider::pcTransform protected
this is transformation for the provider
Definition at line 577 of file Gui/ViewProvider.h.
Referenced by setTransformation(), Gui::ViewProviderVRMLObject::updateData(), Gui::ViewProviderDragger::updateData(), Gui::ViewProviderInventorObject::updateData(), Gui::ViewProviderLink::updateDataPrivate(), Gui::ViewProviderDragger::updateTransformFromDragger(), and ~ViewProvider().
pyViewObject
ViewProviderPy* Gui::ViewProvider::pyViewObject {nullptr} protected
Definition at line 583 of file Gui/ViewProvider.h.
Referenced by FemGui::ViewProviderFemConstraint::getPyObject(), FemGui::ViewProviderFemPostPipeline::getPyObject(), PartDesignGui::ViewProvider::getPyObject(), Gui::ViewProviderGeometryObject::getPyObject(), Gui::ViewProviderDocumentObject::getPyObject(), FemGui::ViewProviderFemMesh::getPyObject(), PartGui::ViewProviderPartExt::getPyObject(), MeshGui::ViewProviderMesh::getPyObject(), Gui::ViewProviderLink::getPyObject(), getPyObject(), and ~ViewProvider().
signalChangeHighlight
boost::signals2::signal<void (bool, Gui::HighlightMode)> Gui::ViewProvider::signalChangeHighlight
signal on highlight change
Definition at line 371 of file Gui/ViewProvider.h.
Referenced by Gui::DocumentObjectData::DocumentObjectData(), and Gui::ViewProviderSuppressibleExtension::extensionUpdateData().
signalChangeIcon
boost::signals2::signal<void ()> Gui::ViewProvider::signalChangeIcon
signal on icon change
Definition at line 365 of file Gui/ViewProvider.h.
Referenced by Gui::ViewProviderLink::checkIcon(), Gui::DocumentObjectData::DocumentObjectData(), PartGui::ViewProviderAttachExtension::extensionUpdateData(), Gui::LinkInfo::LinkInfo(), Gui::ViewProviderSuppressibleExtension::setSuppressedIcon(), PartDesignGui::ViewProvider::setTipIcon(), and Gui::ViewProviderLink::updateDataPrivate().
signalChangeStatusTip
boost::signals2::signal<void (const QString&)> Gui::ViewProvider::signalChangeStatusTip
signal on status tip change
Definition at line 369 of file Gui/ViewProvider.h.
Referenced by Gui::DocumentObjectData::DocumentObjectData().
signalChangeToolTip
boost::signals2::signal<void (const QString&)> Gui::ViewProvider::signalChangeToolTip
signal on tooltip change
Definition at line 367 of file Gui/ViewProvider.h.
Referenced by Gui::DocumentObjectData::DocumentObjectData().
sPixmap
const char* Gui::ViewProvider::sPixmap protected
Definition at line 578 of file Gui/ViewProvider.h.
Referenced by Gui::ViewProviderLink::checkIcon(), PartGui::ViewProviderSpline::getIcon(), Gui::ViewProviderDocumentObjectGroup::getIcon(), Gui::ViewProviderPart::getIcon(), Gui::ViewProviderLink::getIcon(), getIcon(), PROPERTY_SOURCE(), TechDrawGui::ViewProviderProjGroupItem::updateIcon(), PartDesignGui::ViewProviderBoolean::ViewProviderBoolean(), PartDesignGui::ViewProviderDatumCoordinateSystem::ViewProviderDatumCoordinateSystem(), FemGui::ViewProviderFemMesh::ViewProviderFemMesh(), FemGui::ViewProviderFemPostDataAtPoint::ViewProviderFemPostDataAtPoint(), FemGui::ViewProviderFemPostPlaneFunction::ViewProviderFemPostPlaneFunction(), Gui::ViewProviderGeometryObject::ViewProviderGeometryObject(), Gui::ViewProviderImagePlane::ViewProviderImagePlane(), MeasureGui::ViewProviderMeasureArea::ViewProviderMeasureArea(), MeasureGui::ViewProviderMeasureLength::ViewProviderMeasureLength(), MeasureGui::ViewProviderMeasurePosition::ViewProviderMeasurePosition(), MeasureGui::ViewProviderMeasureRadius::ViewProviderMeasureRadius(), PartGui::ViewProviderPartExt::ViewProviderPartExt(), SketcherGui::ViewProviderSketch::ViewProviderSketch(), and Gui::ViewProviderTextDocument::ViewProviderTextDocument().
StatusBits
std::bitset<32> Gui::ViewProvider::StatusBits protected
Definition at line 585 of file Gui/ViewProvider.h.
The documentation for this class was generated from the following files:
Gui/ViewProvider.h
Gui/ViewProvider.cpp