FreeCAD: MeshCore::WriterInventor Class Reference
MeshCore::WriterInventor Class Reference
#include <WriterInventor.h>
Public Member Functions
WriterInventor (const MeshKernel &kernel, const Material *)
WriterInventor.
void SetTransform (const Base::Matrix4D &)
Apply a transformation for the exported mesh.
bool Save (std::ostream &)
Save the mesh to an OpenInventor file.
Detailed Description
Saves the mesh object into OpenInventor v2.1 format.
Definition at line 54 of file WriterInventor.h.
Constructor & Destructor Documentation
WriterInventor()
WriterInventor::WriterInventor (const MeshKernel & kernel, const Material * material) explicit
WriterInventor.
Definition at line 187 of file WriterInventor.cpp.
Member Function Documentation
Save()
bool WriterInventor::Save (std::ostream & out)
Save the mesh to an OpenInventor file.
Returns
true if the data could be written successfully, false otherwise.
Definition at line 200 of file WriterInventor.cpp.
References Base::InventorBuilder::beginSeparator(), Base::InventorBuilder::endSeparator(), and WriterInventorImp::isStreamInvalid().
Referenced by MeshCore::MeshOutput::SaveInventor().
SetTransform()
void WriterInventor::SetTransform (const Base::Matrix4D & mat)
Apply a transformation for the exported mesh.
Definition at line 192 of file WriterInventor.cpp.
Referenced by MeshCore::MeshOutput::SaveInventor().
The documentation for this class was generated from the following files:
WriterInventor.h
WriterInventor.cpp