FreeCAD: AttacherGui Namespace Reference
AttacherGui Namespace Reference
Classes
class AttacherGuiPy
Typedefs
using TextSet = std::vector< QString >
Functions
TextSet TwoStrings (QString str1, QString str2)
TextSet getUIStrings (Base::Type attacherType, Attacher::eMapMode mmode)
getUIStrings
QString getShapeTypeText (eRefType type)
QStringList getRefListForMode (AttachEngine &attacher, eMapMode mmode)
Variables
struct {
const char * AttacherGui::txt
const char * AttacherGui::comment
} eRefTypeStrings []
Detailed Description
AttacherTexts.h, .cpp - files that contain user-friendly translatable names of attachment modes, as well as help texts, and the like.
Typedef Documentation
TextSet
using AttacherGui::TextSet = typedef std::vector<QString>
Definition at line 59 of file AttacherTexts.h.
Function Documentation
getRefListForMode()
QStringList PartGuiExport AttacherGui::getRefListForMode (AttachEngine & attacher, eMapMode mmode)
Definition at line 363 of file AttacherTexts.cpp.
References getShapeTypeText(), and Attacher::AttachEngine::modeRefTypes.
getShapeTypeText()
QString PartGuiExport AttacherGui::getShapeTypeText (eRefType type)
Definition at line 349 of file AttacherTexts.cpp.
References comment, eRefTypeStrings, Attacher::rtDummy_numberOfShapeTypes, Attacher::rtFlagHasPlacement, txt, and Path.Post.scripts.grbl_post::type.
Referenced by getRefListForMode(), makeHintText(), and AttacherGui::AttacherGuiPy::sGetRefTypeUserFriendlyName().
getUIStrings()
TextSet PartGuiExport AttacherGui::getUIStrings (Base::Type attacherType, Attacher::eMapMode mmode)
getUIStrings
Parameters
attacherType
mmode
Returns
vector of two QStrings: first is the name of attachment mode. e.g. "Tangent to surface"; second is tooltip-style explanation of the mode, like "Plane is tangent to a surface at vertex."
Definition at line 46 of file AttacherTexts.cpp.
References Base::Console(), Base::BaseClass::getClassTypeId(), Attacher::AttachEngine::getModeName(), Base::Type::getName(), Base::Type::isDerivedFrom(), Attacher::mm0CenterOfCurvature, Attacher::mm0CenterOfMass, Attacher::mm0Focus1, Attacher::mm0Focus2, Attacher::mm0Intersection, Attacher::mm0OnEdge, Attacher::mm0Origin, Attacher::mm0ProximityPoint1, Attacher::mm0ProximityPoint2, Attacher::mm0Vertex, Attacher::mm1Asymptote1, Attacher::mm1Asymptote2, Attacher::mm1AxisCurv, Attacher::mm1AxisInertia1, Attacher::mm1AxisInertia2, Attacher::mm1AxisInertia3, Attacher::mm1AxisX, Attacher::mm1AxisY, Attacher::mm1AxisZ, Attacher::mm1Binormal, Attacher::mm1Directrix1, Attacher::mm1Directrix2, Attacher::mm1FaceNormal, Attacher::mm1Intersection, Attacher::mm1Normal, Attacher::mm1Proximity, Attacher::mm1Tangent, Attacher::mm1TangentU, Attacher::mm1TangentV, Attacher::mm1TwoPoints, Attacher::mmConcentric, Attacher::mmDeactivated, Attacher::mmFlatFace, Attacher::mmFolding, Attacher::mmFrenetNB, Attacher::mmFrenetTB, Attacher::mmFrenetTN, Attacher::mmInertialCS, Attacher::mmNormalToPath, Attacher::mmObjectXY, Attacher::mmObjectXZ, Attacher::mmObjectYZ, Attacher::mmOXY, Attacher::mmOXZ, Attacher::mmOYX, Attacher::mmOYZ, Attacher::mmOZX, Attacher::mmOZY, Attacher::mmParallelPlane, Attacher::mmRevolutionSection, Attacher::mmTangentPlane, Attacher::mmThreePointsNormal, Attacher::mmThreePointsPlane, Attacher::mmTranslate, TwoStrings(), and Base::ConsoleSingleton::Warning().
Referenced by AttacherGui::AttacherGuiPy::sGetModeStrings().
TwoStrings()
TextSet AttacherGui::TwoStrings (QString str1, QString str2)
Definition at line 37 of file AttacherTexts.cpp.
References TestSpreadsheet::v.
Referenced by getUIStrings().
Variable Documentation
comment
const char* AttacherGui::comment
Definition at line 319 of file AttacherTexts.cpp.
Referenced by StdViewScreenShot::activated(), Gui::PythonEditor::contextMenuEvent(), StdCmdExpression::copyExpressions(), Gui::Dialog::DlgProjectInformationImp::DlgProjectInformationImp(), getShapeTypeText(), StdCmdExpression::pasteExpressions(), Gui::PythonEditor::PythonEditor(), App::PropertyExpressionEngine::Save(), Gui::MacroOutputOption::values(), writeJPEGComment(), and Gui::SoFCOffscreenRenderer::writeToImageFile().
eRefTypeStrings
struct { ... } AttacherGui::eRefTypeStrings[]
Initial value:
= {
    QT_TRANSLATE_NOOP3("Attacher", "Any", "Attacher reference type"),
    QT_TRANSLATE_NOOP3("Attacher", "Vertex", "Attacher reference type"),
    QT_TRANSLATE_NOOP3("Attacher", "Edge", "Attacher reference type"),
    QT_TRANSLATE_NOOP3("Attacher", "Face", "Attacher reference type"),
    QT_TRANSLATE_NOOP3("Attacher", "Line", "Attacher reference type"),
    QT_TRANSLATE_NOOP3("Attacher", "Curve", "Attacher reference type"),
    QT_TRANSLATE_NOOP3("Attacher", "Circle", "Attacher reference type"),
    QT_TRANSLATE_NOOP3("Attacher", "Conic", "Attacher reference type"),
    QT_TRANSLATE_NOOP3("Attacher", "Ellipse", "Attacher reference type"),
    QT_TRANSLATE_NOOP3("Attacher", "Parabola", "Attacher reference type"),
    QT_TRANSLATE_NOOP3("Attacher", "Hyperbola", "Attacher reference type"),
    QT_TRANSLATE_NOOP3("Attacher", "Plane", "Attacher reference type"),
    QT_TRANSLATE_NOOP3("Attacher", "Sphere", "Attacher reference type"),
    QT_TRANSLATE_NOOP3("Attacher", "Revolve", "Attacher reference type"),
    QT_TRANSLATE_NOOP3("Attacher", "Cylinder", "Attacher reference type"),
    QT_TRANSLATE_NOOP3("Attacher", "Torus", "Attacher reference type"),
    QT_TRANSLATE_NOOP3("Attacher", "Cone", "Attacher reference type"),
    QT_TRANSLATE_NOOP3("Attacher", "Object", "Attacher reference type"),
    QT_TRANSLATE_NOOP3("Attacher", "Solid", "Attacher reference type"),
    QT_TRANSLATE_NOOP3("Attacher", "Wire", "Attacher reference type"),
    {nullptr, nullptr},
    {nullptr, nullptr},
    {nullptr, nullptr}
}
Referenced by Attacher::AttachEngine::getRefTypeByName(), Attacher::AttachEngine::getRefTypeName(), and getShapeTypeText().
txt
const char* AttacherGui::txt
Definition at line 319 of file AttacherTexts.cpp.
Referenced by getShapeTypeText().