FreeCAD: MeshCore::MeshEvalSelfIntersection Class Reference
MeshCore::MeshEvalSelfIntersection Class Reference
#include <Evaluation.h>
Public Member Functions
MeshEvalSelfIntersection (const MeshKernel &rclB)
bool Evaluate () override
Evaluate the mesh and return if true if there are self intersections.
void GetIntersections (const std::vector< std::pair< FacetIndex, FacetIndex >> &, std::vector< std::pair< Base::Vector3f, Base::Vector3f >> &) const
collect all intersection lines
void GetIntersections (std::vector< std::pair< FacetIndex, FacetIndex >> &) const
collect the index of all facets with self intersections
Public Member Functions inherited from MeshCore::MeshEvaluation
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()=default
MeshEvaluation (const MeshEvaluation &)=delete
MeshEvaluation (MeshEvaluation &&)=delete
MeshEvaluation & operator= (const MeshEvaluation &)=delete
MeshEvaluation & operator= (MeshEvaluation &&)=delete
Additional Inherited Members
Protected Attributes inherited from MeshCore::MeshEvaluation
const MeshKernel & _rclMesh
Detailed Description
The MeshEvalSelfIntersection class checks the mesh for self intersection.
Author
Werner Mayer
Definition at line 347 of file Evaluation.h.
Constructor & Destructor Documentation
MeshEvalSelfIntersection()
MeshCore::MeshEvalSelfIntersection::MeshEvalSelfIntersection (const MeshKernel & rclB) inline explicit
Definition at line 350 of file Evaluation.h.
Member Function Documentation
Evaluate()
bool MeshEvalSelfIntersection::Evaluate () override virtual
Evaluate the mesh and return if true if there are self intersections.
Implements MeshCore::MeshEvaluation.
Definition at line 601 of file Evaluation.cpp.
References MeshCore::MeshFacet::_aulPoints, MeshCore::MeshEvaluation::_rclMesh, MeshCore::MeshFacetIterator::Begin(), MeshCore::MeshGrid::GetCtGrids(), MeshCore::MeshGridIterator::GetElements(), MeshCore::MeshKernel::GetFacets(), MeshCore::MeshGridIterator::Init(), MeshCore::MeshGeomFacet::IntersectWithFacet(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshGridIterator::More(), MeshCore::MeshFacetIterator::Next(), MeshCore::MeshGridIterator::Next(), Base::SequencerLauncher::next(), and MeshCore::MeshFacetIterator::Set().
Referenced by MeshCore::MeshKernel::HasSelfIntersections(), and Mesh::MeshObject::hasSelfIntersections().
GetIntersections() [1/2]
void MeshEvalSelfIntersection::GetIntersections (const std::vector< std::pair< FacetIndex, FacetIndex >> & indices, std::vector< std::pair< Base::Vector3f, Base::Vector3f >> & intersection) const
collect all intersection lines
Definition at line 678 of file Evaluation.cpp.
References MeshCore::MeshEvaluation::_rclMesh, MeshCore::MeshGeomFacet::GetBoundBox(), intersection(), MeshCore::MeshGeomFacet::IntersectWithFacet(), and MeshCore::MeshFacetIterator::Set().
Referenced by Mesh::MeshObject::getSelfIntersections(), MeshPart::MeshAlgos::offsetSpecial2(), Mesh::MeshObject::offsetSpecial2(), Mesh::MeshObject::removeSelfIntersections(), and MeshGui::ViewProviderMeshSelfIntersections::showDefects().
GetIntersections() [2/2]
void MeshEvalSelfIntersection::GetIntersections (std::vector< std::pair< FacetIndex, FacetIndex >> & intersection) const
collect the index of all facets with self intersections
Definition at line 703 of file Evaluation.cpp.
References MeshCore::MeshFacet::_aulPoints, MeshCore::MeshEvaluation::_rclMesh, MeshCore::MeshFacetIterator::Begin(), MeshCore::MeshGrid::GetCtGrids(), MeshCore::MeshGridIterator::GetElements(), MeshCore::MeshKernel::GetFacets(), MeshCore::MeshGridIterator::Init(), intersection(), MeshCore::MeshGeomFacet::IntersectWithFacet(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshGridIterator::More(), MeshCore::MeshFacetIterator::Next(), MeshCore::MeshGridIterator::Next(), Base::SequencerLauncher::next(), and MeshCore::MeshFacetIterator::Set().
The documentation for this class was generated from the following files:
Evaluation.h
Evaluation.cpp