FreeCAD: Gui::Dialog::DlgProjectInformationImp Class Reference
Gui::Dialog::DlgProjectInformationImp Class Reference
#include <DlgProjectInformationImp.h>
Public Member Functions
DlgProjectInformationImp (App::Document *doc, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgProjectInformationImp () override
void accept () override
Detailed Description
Definition at line 38 of file DlgProjectInformationImp.h.
Constructor & Destructor Documentation
DlgProjectInformationImp()
DlgProjectInformationImp::DlgProjectInformationImp (App::Document * doc, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
Constructs a Gui::Dialog::DlgProjectInformationImp as a child of 'parent', with the name 'name' and widget flags set to 'fl'.
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
Definition at line 67 of file DlgProjectInformationImp.cpp.
References AttacherGui::comment, draftgeoutils.intersections::connect(), toolbit-attributes::doc, Base::UnitsApi::getDescription(), SplineSurface::i, App::licenseItems, Base::NumUnitSystemTypes, App::posnOfFullName, and src.Mod.AddonManager.Addon::translate.
~DlgProjectInformationImp()
DlgProjectInformationImp::~DlgProjectInformationImp () override
Destroys the object and frees any allocated resources
Definition at line 129 of file DlgProjectInformationImp.cpp.
Member Function Documentation
accept()
void DlgProjectInformationImp::accept () override
Applies the changes to the project information of the given document.
Definition at line 138 of file DlgProjectInformationImp.cpp.
References App::Document::Comment, App::Document::Company, App::Document::CreatedBy, Gui::getMainWindow(), App::Document::LastModifiedBy, App::Document::License, App::Document::LicenseURL, Gui::MainWindow::setUserSchema(), and App::PropertyString::setValue().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
The documentation for this class was generated from the following files:
DlgProjectInformationImp.h
DlgProjectInformationImp.cpp