FreeCAD: Gui::PropertyEditor::PropertyItemFactory Class Reference
Gui::PropertyEditor::PropertyItemFactory Class Reference
#include <PropertyItem.h>
Public Member Functions
PropertyItem * createPropertyItem (const char *sName) const
Public Member Functions inherited from Base::Factory
void AddProducer (const char *sClassName, AbstractProducer *pcProducer)
Adds a new prducer instance.
bool CanProduce (const char *sClassName) const
returns true if there is a producer for this class registered
std::list< std::string > CanProduce () const
returns a list of all registered producer
virtual ~Factory ()
destruction
Static Public Member Functions
static PropertyItemFactory & instance ()
Additional Inherited Members
Protected Member Functions inherited from Base::Factory
void * Produce (const char *sClassName) const
produce a class with the given name
Factory ()=default
construction
Protected Attributes inherited from Base::Factory
std::map< const std::string, AbstractProducer * > _mpcProducers
Detailed Description
The PropertyItemFactory provides methods for the dynamic creation of property items.
Author
Werner Mayer
Definition at line 94 of file PropertyItem.h.
Member Function Documentation
createPropertyItem()
PropertyItem * PropertyItemFactory::createPropertyItem (const char * sName) const
Definition at line 93 of file PropertyItem.cpp.
Referenced by createPropertyItem().
instance()
PropertyItemFactory & PropertyItemFactory::instance () static
Definition at line 87 of file PropertyItem.cpp.
Referenced by createPropertyItem(), and Gui::PropertyEditor::PropertyItemProducer< CLASS >::PropertyItemProducer().
The documentation for this class was generated from the following files:
PropertyItem.h
PropertyItem.cpp