FreeCAD: MatGui::TextEdit Class Reference
MatGui::TextEdit Class Reference
#include <TextEdit.h>
Public Member Functions
TextEdit (const QString &propertyName, const std::shared_ptr< Materials::Material > &material, QWidget *parent=nullptr)
~TextEdit () override=default
void accept () override
void reject () override
Detailed Description
Definition at line 63 of file Mod/Material/Gui/TextEdit.h.
Constructor & Destructor Documentation
TextEdit()
TextEdit::TextEdit (const QString & propertyName, const std::shared_ptr< Materials::Material > & material, QWidget * parent = nullptr)
Definition at line 41 of file Mod/Material/Gui/TextEdit.cpp.
References accept(), draftgeoutils.intersections::connect(), Base::Console(), Base::ConsoleSingleton::Log(), propertyName(), and reject().
~TextEdit()
MatGui::TextEdit::~TextEdit () override default
Member Function Documentation
accept()
void TextEdit::accept () override
Definition at line 76 of file Mod/Material/Gui/TextEdit.cpp.
Referenced by TextEdit(), and MaterialEditor.MaterialEditor::verify().
reject()
void TextEdit::reject () override
Definition at line 86 of file Mod/Material/Gui/TextEdit.cpp.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and TextEdit().
The documentation for this class was generated from the following files:
Mod/Material/Gui/TextEdit.h
Mod/Material/Gui/TextEdit.cpp