FreeCAD: MeshCore::MeshEvalInvalids Class Reference
MeshCore::MeshEvalInvalids Class Reference
#include <Degeneration.h>
Public Member Functions
MeshEvalInvalids (const MeshKernel &rclM)
bool Evaluate () override
std::vector< FacetIndex > GetIndices () const
Public Member Functions inherited from MeshCore::MeshEvaluation
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()=default
MeshEvaluation (const MeshEvaluation &)=delete
MeshEvaluation (MeshEvaluation &&)=delete
MeshEvaluation & operator= (const MeshEvaluation &)=delete
MeshEvaluation & operator= (MeshEvaluation &&)=delete
Additional Inherited Members
Protected Attributes inherited from MeshCore::MeshEvaluation
const MeshKernel & _rclMesh
Detailed Description
The MeshEvalInvalids class searches for as 'Invalid' marked facets and points. Basically this comes from a not properly implemented algorithm that marks facets or points as 'Invalid' without removing them from the mesh kernel.
See also
MeshFixInvalids
Author
Werner Mayer
Definition at line 67 of file Degeneration.h.
Constructor & Destructor Documentation
MeshEvalInvalids()
MeshCore::MeshEvalInvalids::MeshEvalInvalids (const MeshKernel & rclM) inline explicit
Construction.
Definition at line 73 of file Degeneration.h.
Member Function Documentation
Evaluate()
bool MeshEvalInvalids::Evaluate () override virtual
Searches for as 'Invalid' marked points or facets.
Implements MeshCore::MeshEvaluation.
Definition at line 42 of file Degeneration.cpp.
References MeshCore::MeshEvaluation::_rclMesh, MeshCore::MeshKernel::GetFacets(), and MeshCore::MeshKernel::GetPoints().
GetIndices()
std::vector< FacetIndex > MeshEvalInvalids::GetIndices () const
Returns the indices of all invalid facets or facets whose points are invalid.
Definition at line 61 of file Degeneration.cpp.
References MeshCore::MeshEvaluation::_rclMesh, MeshCore::MeshKernel::GetFacets(), and MeshCore::MeshKernel::GetPoints().
The documentation for this class was generated from the following files:
Degeneration.h
Degeneration.cpp