FreeCAD: Path::PathSegmentWalker Class Reference
Path::PathSegmentWalker Class Reference
#include <PathSegmentWalker.h>
Public Member Functions
PathSegmentWalker (const Toolpath &tp_)
void walk (PathSegmentVisitor &cb, const Base::Vector3d &startPosition)
Detailed Description
PathSegmentWalker processes a path and splits all movement commands into straight segments and calls the appropriate member of the provided PathSegmentVisitor. All non-movement commands are processed accordingly if they affect the movement commands.
Definition at line 92 of file PathSegmentWalker.h.
Constructor & Destructor Documentation
PathSegmentWalker()
Path::PathSegmentWalker::PathSegmentWalker (const Toolpath & tp_)
Definition at line 127 of file PathSegmentWalker.cpp.
Member Function Documentation
walk()
void Path::PathSegmentWalker::walk (PathSegmentVisitor & cb, const Base::Vector3d & startPosition)
Definition at line 132 of file PathSegmentWalker.cpp.
References RobotExample::A, a, ARC_MIN_SEGMENTS, RobotExample::B, SCL.SimpleDataTypes::b, RobotExample::C, SCL.SimpleDataTypes::c, exportCSG::center(), Path::compensateRotation(), Base::fmod(), Path::PathSegmentVisitor::g0(), Path::PathSegmentVisitor::g1(), Path::PathSegmentVisitor::g23(), Path::PathSegmentVisitor::g38(), Path::PathSegmentVisitor::g8x(), App::GetApplication(), Path::Command::getCenter(), Path::Toolpath::getCenter(), Path::Toolpath::getCommand(), ParameterGrp::GetFloat(), App::Application::GetParameterGroupByPath(), Path::Command::getPlacement(), Base::Placement::getPosition(), Path::Toolpath::getSize(), Path::Command::getValue(), Path::Command::has(), SplineSurface::i, M_PI, KDL::max(), Base::Rotation::multVec(), Path::Command::Name, segments, Path::PathSegmentVisitor::setup(), Base::Vector3< double >::x, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, Base::Vector3< double >::y, Path::yawPitchRoll(), Base::Vector3< float_type >::z, and Base::Vector3< double >::z.
Referenced by Path::Toolpath::getBoundBox().
The documentation for this class was generated from the following files:
PathSegmentWalker.h
PathSegmentWalker.cpp