FreeCAD: Base::LogLevel Class Reference
Base::LogLevel Class Reference
#include <Console.h>
Public Member Functions
LogLevel (const char *tag, bool print_tag=true, int print_src=0, bool print_time=false, bool add_eol=true, bool refresh=false)
bool isEnabled (int lev) const
int level () const
std::stringstream & prefix (std::stringstream &str, const char *src, int line)
Public Attributes
std::string tag
int & lvl
bool print_tag
int print_src
bool print_time
bool add_eol
bool refresh
Detailed Description
LogLevel helper class
Definition at line 949 of file Console.h.
Constructor & Destructor Documentation
LogLevel()
Base::LogLevel::LogLevel (const char * tag, bool print_tag = true, int print_src = 0, bool print_time = false, bool add_eol = true, bool refresh = false) inline
Definition at line 960 of file Console.h.
Member Function Documentation
isEnabled()
bool Base::LogLevel::isEnabled (int lev) const inline
Definition at line 975 of file Console.h.
References level().
Referenced by draftguitools.gui_snapper.Snapper::setArchDims(), draftguitools.gui_snapper.Snapper::snapToAngles(), draftguitools.gui_snapper.Snapper::snapToCenter(), draftguitools.gui_snapper.Snapper::snapToCenterFace(), draftguitools.gui_snapper.Snapper::snapToCrossExtensions(), draftguitools.gui_snapper.Snapper::snapToDim(), draftguitools.gui_snapper.Snapper::snapToElines(), draftguitools.gui_snapper.Snapper::snapToEndpoints(), draftguitools.gui_snapper.Snapper::snapToExtensions(), draftguitools.gui_snapper.Snapper::snapToExtOrtho(), draftguitools.gui_snapper.Snapper::snapToExtPerpendicular(), draftguitools.gui_snapper.Snapper::snapToGrid(), draftguitools.gui_snapper.Snapper::snapToHold(), draftguitools.gui_snapper.Snapper::snapToIntersection(), draftguitools.gui_snapper.Snapper::snapToMidpoint(), draftguitools.gui_snapper.Snapper::snapToNear(), draftguitools.gui_snapper.Snapper::snapToNearFace(), draftguitools.gui_snapper.Snapper::snapToNearUnprojected(), draftguitools.gui_snapper.Snapper::snapToObject(), draftguitools.gui_snapper.Snapper::snapToOrtho(), draftguitools.gui_snapper.Snapper::snapToPerpendicular(), draftguitools.gui_snapper.Snapper::snapToPerpendicularFace(), draftguitools.gui_snapper.Snapper::snapToPolar(), draftguitools.gui_snapper.Snapper::snapToPolygon(), draftguitools.gui_snapper.Snapper::snapToSpecials(), draftguitools.gui_snapper.Snapper::snapToVertex(), and draftguitools.gui_snapper.Snapper::toWP().
level()
int Base::LogLevel::level () const inline
Definition at line 980 of file Console.h.
References Base::Console(), and Base::ConsoleSingleton::LogLevel().
prefix()
std::stringstream & LogLevel::prefix (std::stringstream & str, const char * src, int line)
Definition at line 316 of file ConsoleObserver.cpp.
References _FC_TIME_INIT, FC_TIME_POINT, Path.Post.scripts.dumper_post::now, print_src, print_tag, print_time, PyFrame_GetCode(), Path.Post.scripts.refactored_centroid_post::str, and tag.
Member Data Documentation
add_eol
bool Base::LogLevel::add_eol
Definition at line 957 of file Console.h.
lvl
int& Base::LogLevel::lvl
Definition at line 953 of file Console.h.
print_src
int Base::LogLevel::print_src
Definition at line 955 of file Console.h.
Referenced by prefix().
print_tag
bool Base::LogLevel::print_tag
Definition at line 954 of file Console.h.
Referenced by prefix().
print_time
bool Base::LogLevel::print_time
Definition at line 956 of file Console.h.
Referenced by prefix().
refresh
bool Base::LogLevel::refresh
Definition at line 958 of file Console.h.
Referenced by Path.Tool.Gui.BitEdit.ToolBitEditor::accept(), Path.Tool.Gui.Controller.ToolControllerEditor::setupUi(), and Path.Tool.Gui.BitEdit.ToolBitEditor::setupUI().
tag
std::string Base::LogLevel::tag
Definition at line 952 of file Console.h.
Referenced by Path.Dressup.Tags.MapWireToTag::add(), Path.Dressup.Tags.MapWireToTag::cleanupEdges(), Path.Dressup.Tags.MapWireToTag::commandsForEdges(), Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.ChunkBase::dump_header(), ArchPanel.PanelCut::getWires(), prefix(), and Path.Dressup.Tags.MapWireToTag::shell().
The documentation for this class was generated from the following files:
Console.h
ConsoleObserver.cpp