FreeCAD: Part::GeomTrimmedCurve Class Reference
Part::GeomTrimmedCurve Class Reference
#include <Geometry.h>
Public Member Functions
GeomTrimmedCurve ()
GeomTrimmedCurve (const Handle(Geom_TrimmedCurve)&)
~GeomTrimmedCurve () override
Geometry * copy () const override
GeomCurve * createArc (double first, double last) const override
createArc Generates a curve that is an arc of this curve between given parameters
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
PyObject * getPyObject (void) override
bool isSame (const Geometry &other, double tol, double atol) const override
virtual void setHandle (const Handle(Geom_TrimmedCurve)&)
const Handle (Geom_Geometry) &handle() const override
bool intersectBasisCurves (const GeomTrimmedCurve *c, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> &points, double tol=Precision::Confusion()) const
virtual void getRange (double &u, double &v) const
virtual void setRange (double u, double v)
Public Member Functions inherited from Part::GeomBoundedCurve
GeomBoundedCurve ()
~GeomBoundedCurve () override
virtual Base::Vector3d getStartPoint () const
virtual Base::Vector3d getEndPoint () const
Public Member Functions inherited from Part::GeomCurve
GeomCurve ()
~GeomCurve () override
bool isLinear (Base::Vector3d *dir=nullptr, Base::Vector3d *base=nullptr) const
TopoDS_Shape toShape () const override
GeomBSplineCurve * toBSpline (double first, double last) const
toBSpline Converts the curve to a B-spline
virtual GeomBSplineCurve * toNurbs (double first, double last) const
bool tangent (double u, gp_Dir &) const
bool tangent (double u, Base::Vector3d &dir) const
Base::Vector3d pointAtParameter (double u) const
Base::Vector3d firstDerivativeAtParameter (double u) const
Base::Vector3d secondDerivativeAtParameter (double u) const
bool closestParameter (const Base::Vector3d &point, double &u) const
bool closestParameterToBasisCurve (const Base::Vector3d &point, double &u) const
double getFirstParameter () const
double getLastParameter () const
double curvatureAt (double u) const
double length (double u, double v) const
bool normalAt (double u, Base::Vector3d &dir) const
bool normalAt (const Base::Vector3d &curvepoint, Base::Vector3d &dir) const
bool intersect (const GeomCurve *c, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> &points, double tol=Precision::Confusion()) const
void reverse ()
Base::Vector3d value (double u) const
GeomLine * toLine (KeepTag clone=CopyTag) const
GeomLineSegment * toLineSegment (KeepTag clone=CopyTag) const
Public Member Functions inherited from Part::Geometry
~Geometry () override
Geometry * clone () const
boost::uuids::uuid getTag () const
returns the tag of the geometry object
bool hasSameExtensions (const Geometry &other) const
std::vector< std::weak_ptr< const GeometryExtension > > getExtensions () const
bool hasExtension (const Base::Type &type) const
bool hasExtension (const std::string &name) const
std::weak_ptr< const GeometryExtension > getExtension (const Base::Type &type) const
std::weak_ptr< const GeometryExtension > getExtension (const std::string &name) const
std::weak_ptr< GeometryExtension > getExtension (const Base::Type &type)
std::weak_ptr< GeometryExtension > getExtension (const std::string &name)
void setExtension (std::unique_ptr< GeometryExtension > &&geo)
void deleteExtension (const Base::Type &type)
void deleteExtension (const std::string &name)
void mirror (const Base::Vector3d &point) const
void mirror (const Base::Vector3d &point, const Base::Vector3d &dir) const
void rotate (const Base::Placement &plm) const
void scale (const Base::Vector3d &vec, double scale) const
void transform (const Base::Matrix4D &mat) const
void translate (const Base::Vector3d &vec) const
Geometry (const Geometry &)=delete
Geometry & operator= (const Geometry &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
Handle (Geom_TrimmedCurve) myCurve
Protected Member Functions inherited from Part::Geometry
void createNewTag ()
create a new tag for the geometry object
void assignTag (const Part::Geometry *)
copies the tag from the geometry passed as a parameter to this object
void copyNonTag (const Part::Geometry *)
Geometry ()
Additional Inherited Members
Static Public Member Functions inherited from Part::GeomCurve
static bool isLinear (const Handle(Geom_Curve) &c, Base::Vector3d *dir=nullptr, Base::Vector3d *base=nullptr)
Static Public Member Functions inherited from Part::Geometry
static std::unique_ptr< Geometry > fromShape (const TopoDS_Shape &s, bool silent=false)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Part::GeomCurve
static bool intersect (const Handle(Geom_Curve)&c, const Handle(Geom_Curve)&c2, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> &points, double tol=Precision::Confusion())
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Part::Geometry
boost::uuids::uuid tag
std::vector< std::shared_ptr< GeometryExtension > > extensions
Detailed Description
Definition at line 455 of file Part/App/Geometry.h.
Constructor & Destructor Documentation
GeomTrimmedCurve() [1/2]
GeomTrimmedCurve::GeomTrimmedCurve () default
GeomTrimmedCurve() [2/2]
GeomTrimmedCurve::GeomTrimmedCurve (const Handle(Geom_TrimmedCurve)& c) explicit
Definition at line 2278 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, and setHandle().
~GeomTrimmedCurve()
GeomTrimmedCurve::~GeomTrimmedCurve () override default
Member Function Documentation
copy()
Geometry* Part::GeomTrimmedCurve::copy () const override virtual
returns a copy of this object having a new randomly generated tag. If you also want to copy the tag, you may use clone() instead. For creation of geometry with other handles, with or without the same tag, you may use the constructors and the sethandle functions. The tag of a geometry can be copied to another geometry using the assignTag function.
Implements Part::Geometry.
Reimplemented in Part::GeomArcOfConic, Part::GeomLineSegment, Part::GeomArcOfParabola, Part::GeomArcOfHyperbola, Part::GeomArcOfEllipse, and Part::GeomArcOfCircle.
createArc()
GeomCurve* Part::GeomTrimmedCurve::createArc (double first, double last) const override virtual
createArc Generates a curve that is an arc of this curve between given parameters
Parameters
first Parameter at start of arc
last Parameter at end of arc. This may be < first for periodic curves.
Returns
the new curve
Reimplemented from Part::GeomCurve.
getMemSize()
unsigned int Part::GeomTrimmedCurve::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Reimplemented from Part::Geometry.
Reimplemented in Part::GeomArcOfConic, Part::GeomLineSegment, Part::GeomArcOfParabola, Part::GeomArcOfHyperbola, Part::GeomArcOfEllipse, and Part::GeomArcOfCircle.
getPyObject()
PyObject * GeomTrimmedCurve::getPyObject (void) override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Reimplemented in Part::GeomArcOfConic, Part::GeomLineSegment, Part::GeomArcOfParabola, Part::GeomArcOfHyperbola, Part::GeomArcOfEllipse, and Part::GeomArcOfCircle.
Definition at line 2326 of file Part/App/Geometry.cpp.
References Part::Geometry::clone().
getRange()
void GeomTrimmedCurve::getRange (double & u, double & v) const virtual
Reimplemented in Part::GeomArcOfConic.
Definition at line 2375 of file Part/App/Geometry.cpp.
References Handle(), buildPsets::u, and TestSpreadsheet::v.
Referenced by isSame().
Handle() [1/2]
const Part::GeomTrimmedCurve::Handle (Geom_Geometry) const & override virtual
Implements Part::Geometry.
Reimplemented in Part::GeomArcOfConic, Part::GeomLineSegment, Part::GeomArcOfParabola, Part::GeomArcOfHyperbola, Part::GeomArcOfEllipse, and Part::GeomArcOfCircle.
Referenced by getRange(), intersectBasisCurves(), isSame(), setHandle(), and setRange().
Handle() [2/2]
Part::GeomTrimmedCurve::Handle (Geom_TrimmedCurve) protected
intersectBasisCurves()
bool GeomTrimmedCurve::intersectBasisCurves (const GeomTrimmedCurve * c, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> & points, double tol = Precision::Confusion()) const
Definition at line 2355 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, Handle(), and Part::GeomCurve::intersect().
isSame()
bool GeomTrimmedCurve::isSame (const Geometry & other, double tol, double atol) const override virtual
Implements Part::Geometry.
Definition at line 2331 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::b, getRange(), Base::Persistence::getTypeId(), Handle(), Part::makeFromCurve(), buildPsets::u, TestSpreadsheet::v, and draftgeoutils.general::v1().
Restore()
void Part::GeomTrimmedCurve::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from Part::Geometry.
Reimplemented in Part::GeomLineSegment, Part::GeomArcOfParabola, Part::GeomArcOfHyperbola, Part::GeomArcOfEllipse, and Part::GeomArcOfCircle.
Save()
void Part::GeomTrimmedCurve::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Reimplemented from Part::Geometry.
Reimplemented in Part::GeomLineSegment, Part::GeomArcOfParabola, Part::GeomArcOfHyperbola, Part::GeomArcOfEllipse, and Part::GeomArcOfCircle.
setHandle()
void GeomTrimmedCurve::setHandle (const Handle(Geom_TrimmedCurve)& c) virtual
Reimplemented in Part::GeomLineSegment, Part::GeomArcOfParabola, Part::GeomArcOfHyperbola, Part::GeomArcOfEllipse, and Part::GeomArcOfCircle.
Definition at line 2285 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, and Handle().
Referenced by GeomTrimmedCurve().
setRange()
void GeomTrimmedCurve::setRange (double u, double v) virtual
Reimplemented in Part::GeomArcOfConic.
Definition at line 2382 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::e, Handle(), THROWM, buildPsets::u, and TestSpreadsheet::v.
The documentation for this class was generated from the following files:
Part/App/Geometry.h
Part/App/Geometry.cpp