FreeCAD: Gui::MainWindow Class Reference
Gui::MainWindow Class Reference
#include <MainWindow.h>
Public Types
enum ConfirmSaveResult {
Cancel = 0, Save, SaveAll, Discard,
DiscardAll
}
Public Member Functions
MainWindow (QWidget *parent=nullptr, Qt::WindowFlags f=Qt::Window)
~MainWindow () override
bool eventFilter (QObject *o, QEvent *e) override
void addWindow (MDIView *view)
void removeWindow (MDIView *view, bool close=true)
QList< QWidget * > windows (QMdiArea::WindowOrder order=QMdiArea::CreationOrder) const
QMdiArea * getMdiArea () const
void tabChanged (MDIView *view)
MDIView * activeWindow () const
void setActiveWindow (MDIView *view)
void appendRecentFile (const QString &filename)
void appendRecentMacro (const QString &filename)
QMenu * createPopupMenu () override
Layout Methods
void loadWindowSettings ()
Loads the main window settings.
void saveWindowSettings (bool canDelay=false)
Saves the main window settings.
Menu
void setDockWindowMenu (QMenu *)
Set menu for dock windows.
void setToolBarMenu (QMenu *)
Set menu for toolbars.
void setWindowsMenu (QMenu *)
Set menu for sub-windows.
Splasher and access methods
void startSplasher ()
void stopSplasher ()
void showDocumentation (const QString &help)
static MainWindow * getInstance ()
MIME data handling
enum StatusType {
None, Err, Wrn, Pane,
Msg, Log, Tmp, Critical
}
QMimeData * createMimeDataFromSelection () const
bool canInsertFromMimeData (const QMimeData *source) const
void insertFromMimeData (const QMimeData *source)
void loadUrls (App::Document *, const QList< QUrl > &)
void setUrlHandler (const QString &scheme, UrlHandler *handler)
void unsetUrlHandler (const QString &scheme)
void updateActions (bool delay=false)
void showStatus (int type, const QString &message)
void initDockWindows (bool show)
bool isRestoringWindowState () const
void updateEditorActions ()
void setPaneText (int i, QString text)
void setUserSchema (int userSchema)
void tile ()
void cascade ()
void closeActiveWindow ()
bool closeAllDocuments (bool close=true)
int confirmSave (const char *docName, QWidget *parent=nullptr, bool addCheckBox=false)
void activateNextWindow ()
void activatePreviousWindow ()
void activateWorkbench (const QString &)
void whatsThis ()
void switchToTopLevelMode ()
void switchToDockedMode ()
void statusMessageChanged ()
void showMessage (const QString &message, int timeout=0)
void setRightSideMessage (const QString &message)
void setWindowTitle (const QString &string)
void closeEvent (QCloseEvent *e) override
void showEvent (QShowEvent *e) override
void hideEvent (QHideEvent *e) override
void timerEvent (QTimerEvent *) override
void customEvent (QEvent *e) override
bool event (QEvent *e) override
void dropEvent (QDropEvent *e) override
void dragEnterEvent (QDragEnterEvent *e) override
void changeEvent (QEvent *e) override
void timeEvent ()
void windowStateChanged (QWidget *)
void workbenchActivated (const QString &)
void mainWindowClosed ()
Detailed Description
The MainWindow class provides a main window with menu bar, toolbars, dockable windows, a status bar and mainly a workspace for the MDI windows.
Author
Werner Mayer
Definition at line 71 of file MainWindow.h.
Member Enumeration Documentation
ConfirmSaveResult
enum Gui::MainWindow::ConfirmSaveResult
Enumerator
Cancel
Save
SaveAll
Discard
DiscardAll
Definition at line 76 of file MainWindow.h.
StatusType
enum Gui::MainWindow::StatusType
Enumerator
None
Err
Wrn
Pane
Msg
Log
Tmp
Critical
Definition at line 203 of file MainWindow.h.
Constructor & Destructor Documentation
MainWindow()
MainWindow::MainWindow (QWidget * parent = nullptr, Qt::WindowFlags f = Qt::Window) explicit
Constructs an empty main window. For default parent is 0, as there usually is no toplevel window there.
Definition at line 307 of file MainWindow.cpp.
References Gui::MainWindowP::actionLabel, Gui::MainWindowP::actionTimer, Gui::MainWindowP::activeView, Gui::MainWindowP::activityTimer, Gui::MainWindowP::assistant, Path.Op.Gui.Selection::clear(), draftgeoutils.intersections::connect(), Gui::MainWindowP::connParam, DraftVecUtils::equals(), App::GetApplication(), ParameterGrp::GetBool(), Gui::getMainWindow(), App::Application::GetParameterGroupByPath(), Gui::SequencerBar::getProgressBar(), App::Application::GetUserParameter(), Gui::MainWindowP::hGrp, Gui::SequencerBar::instance(), Gui::OverlayManager::instance(), Gui::MainWindowP::mdiArea, src.Mod.AddonManager.addonmanager_pyside_interface::QObject, Gui::OverlayManager::reload(), Gui::OverlayManager::ReloadPause, Gui::MainWindowP::restoreStateTimer, Gui::MainWindowP::rightSideLabel, Gui::MainWindowP::saveStateTimer, ParameterManager::signalParamChanged, Gui::MainWindowP::sizeLabel, Gui::MainWindowP::splashscreen, Gui::MainWindowP::status, NavigationIndicatorGui::statusBar, statusMessageChanged(), Gui::MainWindowP::statusTimer, updateEditorActions(), Gui::MainWindowP::whatsthis, and Gui::MainWindowP::windowMapper.
~MainWindow()
MainWindow::~MainWindow () override
Destroys the object and frees any allocated resources.
Definition at line 456 of file MainWindow.cpp.
References Gui::MainWindowP::status.
Member Function Documentation
activateNextWindow
void MainWindow::activateNextWindow () slot
Activates the next window in the child window chain.
Definition at line 905 of file MainWindow.cpp.
References Gui::MainWindowP::mdiArea.
Referenced by StdCmdActivateNextWindow::activated().
activatePreviousWindow
void MainWindow::activatePreviousWindow () slot
Activates the previous window in the child window chain.
Definition at line 914 of file MainWindow.cpp.
References Gui::MainWindowP::mdiArea.
Referenced by StdCmdActivatePrevWindow::activated().
activateWorkbench
void MainWindow::activateWorkbench (const QString & name) slot
Just emits the workbenchActivated() signal to notify all receivers.
Definition at line 923 of file MainWindow.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), Gui::MainWindowP::mdiArea, updateActions(), and workbenchActivated().
Referenced by Gui::Application::activateWorkbench().
activeWindow()
MDIView * MainWindow::activeWindow () const
Returns the active MDI window or 0 if there is none.
Definition at line 1417 of file MainWindow.cpp.
References Gui::MainWindowP::activeView.
Referenced by TechDrawGui::TechDrawHandler::activate(), TDHandlerDimension::activated(), CmdTestMDI1::activated(), CmdTestMDI2::activated(), CmdTestMDI3::activated(), StdCmdPrint::activated(), StdCmdPrintPreview::activated(), StdCmdPrintPdf::activated(), StdCmdEdit::activated(), StdMainFullscreen::activated(), StdViewDockUndockFullscreen::activated(), StdCmdToggleNavigation::activated(), activateHandler(), changeEvent(), Gui::OverlayTabWidget::checkAutoHide(), Gui::SoFCColorGradient::customize(), TechDrawGui::TechDrawHandler::deactivate(), TDHandlerDimension::deactivated(), Gui::Dialog::DlgActivateWindowImp::DlgActivateWindowImp(), Gui::Document::getActiveView(), Gui::ToolHandler::getViewer(), Gui::OverlayProxyWidget::hitTest(), CmdTestMDI1::isActive(), CmdTestMDI2::isActive(), CmdTestMDI3::isActive(), NaviCubeDraggableCmd::isActive(), StdViewDock::isActive(), StdViewUndock::isActive(), StdViewFullscreen::isActive(), StdViewDockUndockFullscreen::isActive(), StdCmdToggleNavigation::isActive(), StdCmdTextureMapping::isActive(), StdStoreWorkingView::isActive(), StdRecallWorkingView::isActive(), Gui::OverlayTabWidget::isTransparent(), Gui::Dialog::RedoDialog::onFetchInfo(), Gui::Dialog::UndoDialog::onFetchInfo(), TechDrawGui::ViewProviderPage::removeMDIView(), Gui::Application::sendHasMsgToActiveView(), Gui::Application::sendHasMsgToFocusView(), Gui::Application::sendMsgToActiveView(), Gui::Application::sendMsgToFocusView(), Gui::Document::setActiveWindow(), SpreadsheetGui::WorkbenchHelper::setBackgroundColor(), Gui::OverlayManager::setFocusView(), SpreadsheetGui::WorkbenchHelper::setForegroundColor(), and Gui::Application::slotActiveDocument().
addWindow()
void MainWindow::addWindow (MDIView * view)
Adds an MDI window view to the main window's workspace and adds a new tab to the tab bar.
Definition at line 1119 of file MainWindow.cpp.
References Path.Post.scripts.dynapath_4060_post::action, draftgeoutils.intersections::connect(), Gui::MainWindowP::mdiArea, NavigationIndicatorGui::menu, Gui::MDIView::message(), showMessage(), Gui::MDIView::windowStateChanged(), and windowStateChanged().
Referenced by StdCmdDependencyGraph::activated(), StdViewDockUndockFullscreen::activated(), StdViewLoadImage::activated(), Gui::RecentMacrosAction::activateFile(), TechDrawGui::ViewProviderPage::createMDIViewPage(), Gui::Document::createView(), Gui::ViewProviderTextDocument::doubleClicked(), Gui::Dialog::AboutDialog::linkActivated(), Gui::ApplicationPy::sCreateViewer(), Gui::MDIView::setCurrentViewMode(), Gui::PythonDebugger::showDebugMarker(), DrawingGui::ViewProviderDrawingPage::showDrawingView(), SpreadsheetGui::ViewProviderSheet::showSpreadsheetView(), and Gui::ManualAlignment::startAlignment().
appendRecentFile()
void MainWindow::appendRecentFile (const QString & filename)
MRU: Appends file to the list of recent files.
Definition at line 1590 of file MainWindow.cpp.
Referenced by Gui::Application::exportTo(), Gui::Application::importFrom(), Gui::Application::open(), and Gui::Document::saveAs().
appendRecentMacro()
void MainWindow::appendRecentMacro (const QString & filename)
MRU: Appends macro to the list of recent macros.
Definition at line 1599 of file MainWindow.cpp.
Referenced by Gui::Dialog::DlgMacroExecuteImp::accept(), and Gui::RecentMacrosAction::activateFile().
canInsertFromMimeData()
bool MainWindow::canInsertFromMimeData (const QMimeData * source) const
Check if mime data contains object data
Definition at line 1975 of file MainWindow.cpp.
References _MimeDocObj(), _MimeDocObjFile(), _MimeDocObjX(), and _MimeDocObjXFile().
Referenced by StdCmdPaste::isActive().
cascade
void MainWindow::cascade () slot
Arranges all the child windows in a cascade pattern.
Definition at line 775 of file MainWindow.cpp.
References Gui::MainWindowP::mdiArea.
Referenced by StdCmdCascadeWindows::activated().
changeEvent()
void MainWindow::changeEvent (QEvent * e) override protected
This method is called from the Qt framework automatically whenever a QTranslator object has been installed. This allows one to translate all relevant user visible text.
Definition at line 2122 of file MainWindow.cpp.
References Gui::WorkbenchManager::active(), Gui::MainWindowP::activeView, activeWindow(), Gui::Application::commandManager(), SCL.SimpleDataTypes::e, Gui::CommandManager::getAllCommands(), Gui::getMainWindow(), Gui::WorkbenchManager::instance(), Gui::Application::Instance, Gui::MainWindowP::mdiArea, Gui::Workbench::retranslate(), Gui::MainWindowP::sizeLabel, and Gui::Application::viewActivated().
closeActiveWindow
void MainWindow::closeActiveWindow () slot
Closes the child window that is currently active.
Definition at line 780 of file MainWindow.cpp.
References Gui::MainWindowP::mdiArea.
Referenced by StdCmdCloseActiveWindow::activated().
closeAllDocuments
bool MainWindow::closeAllDocuments (bool close = true) slot
Closes all document window.
Definition at line 842 of file MainWindow.cpp.
References App::Application::closeAllDocuments(), confirmSave(), toolbit-attributes::doc, SCL.SimpleDataTypes::e, App::GetApplication(), App::Document::getDependentDocuments(), Gui::Application::getDocument(), App::Application::getDocuments(), Gui::getMainWindow(), Gui::Application::Instance, App::Document::PartialDoc, nativeifc.ifc_tools::save(), and App::Document::TempDoc.
Referenced by StdCmdCloseAllWindows::activated().
closeEvent()
void MainWindow::closeEvent (QCloseEvent * e) override protected
This method checks if the main window can be closed by checking all open documents and views.
Definition at line 1423 of file MainWindow.cpp.
References Gui::MainWindowP::activityTimer, Gui::MainWindowP::assistant, Base::FileInfo::deleteFile(), src.Mod.PartDesign.Scripts.Gear::dialog, SCL.SimpleDataTypes::e, Base::FileInfo::exists(), Gui::WorkbenchManager::instance(), Gui::Application::Instance, femsolver.elmer.sifio::isValid(), mainWindowClosed(), saveWindowSettings(), and Gui::Application::tryClose().
confirmSave
int MainWindow::confirmSave (const char * docName, QWidget * parent = nullptr, bool addCheckBox = false) slot
Pop up a message box asking for saving document
Definition at line 785 of file MainWindow.cpp.
References MengerSponge::box, App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), App::Application::GetUserParameter(), Init::parent, and ParameterGrp::SetBool().
Referenced by Gui::Document::canClose(), and closeAllDocuments().
createMimeDataFromSelection()
QMimeData * MainWindow::createMimeDataFromSelection () const
Create mime data from selected objects
Definition at line 1897 of file MainWindow.cpp.
References _MimeDocObj(), _MimeDocObjFile(), _MimeDocObjX(), _MimeDocObjXFile(), toolbit-attributes::doc, Base::FileInfo::filePath(), App::Document::getDependencyList(), Gui::getMainWindow(), Gui::DlgObjectSelection::getSelections(), App::Application::getTempFileName(), App::PropertyXLink::hasXLink(), toolbit-attributes::s, Gui::Selection(), Path.Base.Util::setProperty(), and Path.Post.scripts.refactored_centroid_post::str.
Referenced by StdCmdCopy::activated().
createPopupMenu()
QMenu * MainWindow::createPopupMenu () override
Returns true that the context menu contains the 'Customize...' menu item.
Definition at line 741 of file MainWindow.cpp.
References Gui::WorkbenchManager::active(), Gui::Command::addTo(), Gui::MenuItem::command(), Gui::Application::commandManager(), Gui::Workbench::createMainWindowPopupMenu(), Gui::CommandManager::getCommandByName(), Gui::MenuItem::getItems(), Gui::MenuItem::hasItems(), Gui::WorkbenchManager::instance(), Gui::Application::Instance, src.Mod.Test.testPathArray::items, and NavigationIndicatorGui::menu.
customEvent()
void MainWindow::customEvent (QEvent * e) override protected
Definition at line 2243 of file MainWindow.cpp.
References Gui::Application::activeDocument(), Gui::ActionStyleEvent::Clear, SCL.SimpleDataTypes::e, Gui::ActionStyleEvent::EventType, draftutils.utils::getType, Gui::Application::Instance, Log, Path.Op.Surface::msg, Gui::Document::setAnnotationViewProvider(), showMessage(), showStatus(), and Tmp.
dragEnterEvent()
void MainWindow::dragEnterEvent (QDragEnterEvent * e) override protected
Checks if a mime source object can be interpreted.
Definition at line 1880 of file MainWindow.cpp.
References SCL.SimpleDataTypes::e.
dropEvent()
void MainWindow::dropEvent (QDropEvent * e) override protected
Try to interpret dropped elements.
Drops the event e and tries to open the files.
Definition at line 1868 of file MainWindow.cpp.
References SCL.SimpleDataTypes::e, App::GetApplication(), and loadUrls().
event()
bool MainWindow::event (QEvent * e) override protected
Definition at line 960 of file MainWindow.cpp.
References KDL::abs(), Path.Post.scripts.dynapath_4060_post::action, Gui::Application::activeDocument(), Spaceball::BUTTON_PRESSED, Spaceball::ButtonEvent::ButtonEventType, Gui::Application::commandManager(), Gui::MainWindowP::currentStatusType, toolbit-attributes::doc, SCL.SimpleDataTypes::e, Gui::CommandBase::getAction(), App::GetApplication(), ParameterGrp::GetASCII(), Gui::CommandManager::getCommandByName(), ParameterGrp::GetGroup(), App::Application::GetUserParameter(), toolbit-attributes::group, Gui::Application::Instance, Spaceball::MotionEvent::MotionEventType, Gui::CommandManager::runCommandByName(), Spaceball::EventBase::setHandled(), showDocumentation(), Gui::MainWindowP::whatstext, Gui::MainWindowP::whatsthis, and Wrn.
eventFilter()
bool MainWindow::eventFilter (QObject * o, QEvent * e) override
Filters events if this object has been installed as an event filter for the watched object.
Definition at line 1038 of file MainWindow.cpp.
References SCL.SimpleDataTypes::e, src.Mod.Test.testPathArray::o, toolbit-attributes::s, src.Mod.PartDesign.fcgear.svggear::w, Gui::MainWindowP::whatstext, Gui::MainWindowP::whatsthis, and windowStateChanged().
getInstance()
MainWindow * MainWindow::getInstance () static
Gets the one and only instance.
Definition at line 463 of file MainWindow.cpp.
Referenced by Gui::PropertyEditor::PropertyEditor::closeEditor(), and Gui::getMainWindow().
getMdiArea()
QMdiArea * MainWindow::getMdiArea () const
Returns the internal QMdiArea instance.
Definition at line 2286 of file MainWindow.cpp.
References Gui::MainWindowP::mdiArea.
Referenced by Gui::OverlayTabWidget::addWidget(), Gui::OverlayManager::Private::dragDockWidget(), Gui::OverlayManager::eventFilter(), Gui::OverlayTabWidget::getAutoHideRect(), Gui::OverlayTabWidget::onSizeGripMove(), Gui::OverlayManager::Private::onTimer(), and Gui::OverlayTabWidget::setRect().
hideEvent()
void MainWindow::hideEvent (QHideEvent * e) override protected
Definition at line 1483 of file MainWindow.cpp.
References SCL.SimpleDataTypes::e.
initDockWindows()
void MainWindow::initDockWindows (bool show)
Definition at line 504 of file MainWindow.cpp.
References bimcommands.BimViews::show().
insertFromMimeData()
void MainWindow::insertFromMimeData (const QMimeData * source)
Insert the objects into the active document. If no document exists one gets created.
Definition at line 1984 of file MainWindow.cpp.
References _MimeDocObj(), _MimeDocObjFile(), _MimeDocObjX(), _MimeDocObjXFile(), toolbit-attributes::doc, App::Application::getActiveDocument(), App::GetApplication(), Gui::Application::getDocument(), Gui::getMainWindow(), Gui::SelectionSingleton::getObjectsOfType(), toolbit-attributes::grp, Draft::gui, Gui::MergeDocuments::importObjects(), Gui::Application::Instance, loadUrls(), App::Application::newDocument(), Gui::Selection(), and Path.Post.scripts.refactored_centroid_post::str.
Referenced by StdCmdPaste::activated().
isRestoringWindowState()
bool MainWindow::isRestoringWindowState () const
Definition at line 1775 of file MainWindow.cpp.
References Gui::MainWindowP::_restoring.
Referenced by saveWindowSettings().
loadUrls()
void MainWindow::loadUrls (App::Document * doc, const QList< QUrl > & urls)
Load files from the given URLs into the given document. If the document is 0 one gets created automatically if needed.
If a url handler is registered that supports its scheme it will be delegated to this handler. This mechanism allows one to change the default behaviour.
Definition at line 2066 of file MainWindow.cpp.
References Base::Console(), toolbit-attributes::doc, Gui::Dialog::DownloadManager::download(), App::GetApplication(), App::Application::getImportModules(), Gui::Dialog::DownloadManager::getInstance(), Gui::ModuleIO::importFiles(), Path.Log::info(), Base::ConsoleSingleton::Message(), src.Mod.PartDesign.fcgear.svggear::module, Gui::Dialog::DownloadManager::redirectUrl(), Gui::MainWindowP::urlHandler, and src.Mod.AddonManager.NetworkManager::urls.
Referenced by Gui::View3DInventor::dropEvent(), dropEvent(), Gui::View3DInventorViewer::dropEvent(), and insertFromMimeData().
loadWindowSettings()
void MainWindow::loadWindowSettings ()
Loads the main window settings.
Definition at line 1699 of file MainWindow.cpp.
References Gui::MainWindowP::_restoring, App::Application::Config(), ParameterGrp::GetASCII(), ParameterGrp::GetBool(), Gui::ToolBarManager::getInstance(), Gui::MainWindowP::hGrp, Gui::OverlayManager::instance(), KDL::max(), Path.Post.scripts.opensbp_post::move(), RobotExample::pos, Gui::OverlayManager::restore(), Gui::ToolBarManager::restoreState(), Gui::MainWindowP::restoreWindowState(), bimcommands.BimViews::show(), NavigationIndicatorGui::statusBar, src.Mod.PartDesign.fcgear.svggear::w, MovieTool::x, and MovieTool::y.
mainWindowClosed
void Gui::MainWindow::mainWindowClosed () signal
Referenced by closeEvent().
removeWindow()
void MainWindow::removeWindow (Gui::MDIView * view, bool close = true)
Removes an MDI window from the main window's workspace and its associated tab without deleting the widget. If the main windows does not have such a window nothing happens.
Removes the instance of Gui::MDiView from the main window and sends am event to the parent widget, a QMdiSubWindow to delete itself. If you want to avoid that the Gui::MDIView instance gets destructed too you must reparent it afterwards, e.g. set parent to NULL.
Definition at line 1164 of file MainWindow.cpp.
References Gui::MainWindowP::mdiArea, Gui::MDIView::message(), Init::parent, showMessage(), updateActions(), Gui::MDIView::windowStateChanged(), and windowStateChanged().
Referenced by CmdTestMDI1::activated(), CmdTestMDI3::activated(), SpreadsheetGui::ViewProviderSheet::beforeDelete(), TechDrawGui::ViewProviderPage::removeMDIView(), Gui::MDIView::setCurrentViewMode(), and SpreadsheetGui::ViewProviderSheet::~ViewProviderSheet().
saveWindowSettings()
void MainWindow::saveWindowSettings (bool canDelay = false)
Saves the main window settings.
Definition at line 1800 of file MainWindow.cpp.
References App::Application::Config(), Gui::MainWindowP::connParam, Gui::ToolBarManager::getInstance(), Gui::MainWindowP::hGrp, Gui::DockWindowManager::instance(), Gui::OverlayManager::instance(), isRestoringWindowState(), RobotExample::pos, Gui::OverlayManager::save(), Gui::DockWindowManager::saveState(), Gui::ToolBarManager::saveState(), Gui::MainWindowP::saveStateTimer, ParameterGrp::SetASCII(), ParameterGrp::SetBool(), and NavigationIndicatorGui::statusBar.
Referenced by Gui::DockWindowManager::addDockWindow(), and closeEvent().
setActiveWindow()
void MainWindow::setActiveWindow (MDIView * view)
Sets the active window to view.
Definition at line 1237 of file MainWindow.cpp.
References Gui::MainWindowP::activeView, Gui::Application::Instance, and Gui::Application::viewActivated().
Referenced by Gui::Dialog::DlgActivateWindowImp::accept(), Gui::MDIView::changeEvent(), DrawingGui::ViewProviderDrawingPage::doubleClicked(), Gui::DAG::Model::mouseDoubleClickEvent(), Gui::TreeView::mouseDoubleClickEvent(), Gui::Application::onLastWindowClosed(), Gui::TreeWidget::onStartEditing(), Gui::Document::openEditingView3D(), Gui::Document::setActiveView(), Gui::Document::setActiveWindow(), Gui::PythonDebugger::showDebugMarker(), SpreadsheetGui::ViewProviderSheet::showSheetMdi(), Gui::Application::slotActiveDocument(), and Gui::ApplicationPy::sSetActiveDocument().
setDockWindowMenu()
void MainWindow::setDockWindowMenu (QMenu * menu)
Set menu for dock windows.
Definition at line 1392 of file MainWindow.cpp.
References draftgeoutils.intersections::connect(), and NavigationIndicatorGui::menu.
Referenced by Gui::DockWidgetAction::addTo().
setPaneText
void MainWindow::setPaneText (int i, QString text) slot
Sets text to the pane in the status bar.
Definition at line 2226 of file MainWindow.cpp.
References SplineSurface::i, Pane, showStatus(), and Gui::MainWindowP::sizeLabel.
Referenced by MeshGui::ViewProviderMeshCurvature::curvatureInfoCallback(), InspectionGui::ViewProviderInspection::inspectCallback(), Gui::View3DInventorViewer::printDimension(), Gui::SequencerBar::resetData(), and Gui::View3DInventorViewer::~View3DInventorViewer().
setRightSideMessage
void MainWindow::setRightSideMessage (const QString & message) slot
Definition at line 2183 of file MainWindow.cpp.
References Gui::MainWindowP::rightSideLabel.
setToolBarMenu()
void MainWindow::setToolBarMenu (QMenu * menu)
Set menu for toolbars.
Definition at line 1397 of file MainWindow.cpp.
References draftgeoutils.intersections::connect(), and NavigationIndicatorGui::menu.
Referenced by Gui::ToolBarAction::addTo().
setUrlHandler()
void MainWindow::setUrlHandler (const QString & scheme, Gui::UrlHandler * handler)
Sets the handler for the given scheme. If setUrlHandler() is used to set a new handler for a scheme which already has a handler, the existing handler is simply replaced with the new one. Since MainWindow does not take ownership of handlers, no objects are deleted when a handler is replaced.
Definition at line 2056 of file MainWindow.cpp.
References buildPsets::handler, and Gui::MainWindowP::urlHandler.
setUserSchema
void MainWindow::setUserSchema (int userSchema) slot
Sets the userschema in the status bar
Definition at line 2237 of file MainWindow.cpp.
References Gui::DimensionWidget::setUserSchema(), and Gui::MainWindowP::sizeLabel.
Referenced by Gui::Dialog::DlgProjectInformationImp::accept(), Gui::Application::slotActiveDocument(), and Gui::Document::slotChangePropertyEditor().
setWindowsMenu()
void MainWindow::setWindowsMenu (QMenu * menu)
Set menu for sub-windows.
Definition at line 1402 of file MainWindow.cpp.
References draftgeoutils.intersections::connect(), and NavigationIndicatorGui::menu.
Referenced by Gui::WindowAction::addTo().
setWindowTitle
void MainWindow::setWindowTitle (const QString & string) slot
Definition at line 2291 of file MainWindow.cpp.
References App::Application::Config(), App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), SafeMode::SafeModeEnabled(), and Plot::title().
Referenced by femsolver.reportdialog.ReportDialog::__init__(), femguiutils.selection_widgets.BoundarySelector::__init__(), femguiutils.selection_widgets.SolidSelector::__init__(), femsolver.solver_taskpanel.ControlWidget::__init__(), Path.Main.Gui.Job.MaterialDialog::__init__(), Plot.Plot::__init__(), femguiutils.selection_widgets.GeometryElementsSelection::initUI(), Gui::Dialog::DlgCustomToolbarsImp::renameCustomToolbar(), OpenSCADCommands.AddSCADWidget::retranslateUi(), OpenSCADCommands.OpenSCADMeshBooleanWidget::retranslateUi(), and Gui::Application::viewActivated().
showDocumentation()
void MainWindow::showDocumentation (const QString & help)
Shows the online documentation.
Definition at line 944 of file MainWindow.cpp.
References Gui::Command::addModule(), doCommand, SCL.SimpleDataTypes::e, Gui::Command::Gui, Path.Post.scripts.dynapath_4060_post::help, and src.Mod.PartDesign.fcgear.svggear::module.
Referenced by StdCmdOnlineHelp::activated(), and event().
showEvent()
void MainWindow::showEvent (QShowEvent * e) override protected
Definition at line 1477 of file MainWindow.cpp.
References SCL.SimpleDataTypes::e.
showMessage
void MainWindow::showMessage (const QString & message, int timeout = 0) slot
Definition at line 2170 of file MainWindow.cpp.
References Gui::MainWindowP::actionLabel, Gui::MainWindowP::actionTimer, and Tmp.
Referenced by TechDrawGui::TaskCosVertex::abandonEditSession(), TechDrawGui::TaskLeaderLine::abandonEditSession(), StdCmdPrint::activated(), StdCmdPrintPdf::activated(), Gui::SelectionSingleton::addSelection(), addWindow(), Gui::ManualAlignment::align(), Gui::ManualAlignment::cancel(), Gui::ManualAlignment::continueAlignment(), customEvent(), Gui::DocumentObjectItem::displayStatusInfo(), Gui::TDragger::drag(), Gui::TPlanarDragger::drag(), Gui::RDragger::drag(), Gui::OverlayGraphicsEffect::draw(), Gui::ManualAlignment::finish(), Gui::SoFCSelection::handleEvent(), TechDrawGui::TaskCosVertex::onTrackerClicked(), TechDrawGui::TaskLeaderLine::onTrackerClicked(), TechDrawGui::TaskLeaderLine::onTrackerFinished(), Gui::printPreselectionInfo(), Gui::ManualAlignment::probePickedCallback(), removeWindow(), Gui::SequencerBar::resetData(), Gui::Document::saveAs(), Gui::Document::saveCopy(), Gui::AutoSaver::saveDocument(), Gui::SelectionSingleton::setPreselect(), Gui::SequencerBar::setText(), Gui::ManualAlignment::showInstructions(), Gui::SequencerBar::showRemainingTime(), TechDrawGui::MDIViewPage::showStatusMsg(), TechDrawGui::TaskCosVertex::startTracker(), TechDrawGui::TaskLeaderLine::startTracker(), and MeshPartGui::CurveOnMeshHandler::Private::vertexCallback().
showStatus()
void MainWindow::showStatus (int type, const QString & message)
Definition at line 2188 of file MainWindow.cpp.
References Gui::MainWindowP::actionLabel, Gui::MainWindowP::currentStatusType, Err, Path.Op.Surface::msg, Pane, Gui::MainWindowP::status, NavigationIndicatorGui::statusBar, Gui::MainWindowP::statusTimer, Path.Post.scripts.grbl_post::type, and Wrn.
Referenced by customEvent(), Gui::DocumentObjectItem::displayStatusInfo(), and setPaneText().
startSplasher()
void MainWindow::startSplasher ()
Starts the splasher at startup.
Definition at line 1832 of file MainWindow.cpp.
References App::Application::Config(), App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), App::Application::GetUserParameter(), Gui::SplashScreen::setShowMessages(), Gui::SplashScreen::splashImage(), and Gui::MainWindowP::splashscreen.
statusMessageChanged
void MainWindow::statusMessageChanged () slot
Definition at line 2158 of file MainWindow.cpp.
References Gui::MainWindowP::currentStatusType, and Gui::MainWindowP::statusTimer.
Referenced by MainWindow().
stopSplasher()
void MainWindow::stopSplasher ()
Stops the splasher after startup.
Definition at line 1856 of file MainWindow.cpp.
References Gui::MainWindowP::splashscreen.
switchToDockedMode
void MainWindow::switchToDockedMode () slot
Definition at line 1688 of file MainWindow.cpp.
References Gui::MDIView::Child.
Referenced by StdCmdUserInterface::activated().
switchToTopLevelMode
void MainWindow::switchToTopLevelMode () slot
Definition at line 1674 of file MainWindow.cpp.
References Gui::getMainWindow(), and windows().
tabChanged()
void MainWindow::tabChanged (MDIView * view)
Can be called after the caption of an MDIView has changed to update the tab's caption.
Definition at line 1208 of file MainWindow.cpp.
References updateActions().
Referenced by Gui::MDIView::changeEvent().
tile
void MainWindow::tile () slot
Arranges all child windows in a tile pattern.
Definition at line 770 of file MainWindow.cpp.
References Gui::MainWindowP::mdiArea.
Referenced by StdCmdTileWindows::activated().
timeEvent
void Gui::MainWindow::timeEvent () signal
timerEvent()
void Gui::MainWindow::timerEvent (QTimerEvent *) inline override protected
Definition at line 276 of file MainWindow.h.
unsetUrlHandler()
void MainWindow::unsetUrlHandler (const QString & scheme)
Removes a previously set URL handler for the specified scheme.
Definition at line 2061 of file MainWindow.cpp.
References Gui::MainWindowP::urlHandler.
updateActions()
void MainWindow::updateActions (bool delay = false)
Definition at line 1608 of file MainWindow.cpp.
References Gui::MainWindowP::actionUpdateDelay, and Gui::MainWindowP::activityTimer.
Referenced by activateWorkbench(), Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::addSelections(), Gui::SelectionSingleton::clearCompleteSelection(), Gui::SelectionSingleton::clearSelection(), Gui::TaskView::TaskView::removeDialog(), removeWindow(), Gui::SelectionSingleton::rmvSelection(), SpreadsheetGui::SheetTableView::selectionChanged(), Gui::SelectionSingleton::selStackGoBack(), Gui::SelectionSingleton::selStackGoForward(), Gui::SelectionSingleton::setSelection(), Gui::TaskView::TaskView::showDialog(), Gui::Document::slotChangedObject(), Gui::SelectionSingleton::slotDeletedObject(), Gui::Document::slotRecomputed(), Gui::Document::slotRedoDocument(), Gui::Document::slotTouchedObject(), Gui::Document::slotUndoDocument(), tabChanged(), and Gui::Application::updateActions().
updateEditorActions
void MainWindow::updateEditorActions () slot
Updates the standard actions of a text editor such as Cut, Copy, Paste, Undo and Redo.
Definition at line 1653 of file MainWindow.cpp.
References Gui::Application::commandManager(), Gui::CommandManager::getCommandByName(), Gui::Application::Instance, and Gui::Command::testActive().
Referenced by Gui::EditorView::EditorView(), and MainWindow().
whatsThis
void MainWindow::whatsThis () slot
Starts the what's this mode.
Definition at line 939 of file MainWindow.cpp.
Referenced by Gui::Dialog::DlgCustomizeImp::DlgCustomizeImp(), and InspectionGui::VisualInspection::VisualInspection().
windows()
QList< QWidget * > MainWindow::windows (QMdiArea::WindowOrder order = QMdiArea::CreationOrder) const
Returns a list of all MDI windows in the worpspace.
Definition at line 1407 of file MainWindow.cpp.
References Gui::MainWindowP::mdiArea.
Referenced by Gui::Dialog::DlgActivateWindowImp::accept(), TechDrawGui::TaskActiveView::createActiveView(), Gui::Dialog::DlgActivateWindowImp::DlgActivateWindowImp(), Gui::Document::getActiveView(), Gui::PythonDebugger::hideDebugMarker(), StdCmdTileWindows::isActive(), StdCmdCascadeWindows::isActive(), StdCmdCloseActiveWindow::isActive(), StdCmdCloseAllWindows::isActive(), StdCmdActivateNextWindow::isActive(), StdCmdActivatePrevWindow::isActive(), TechDrawGui::ViewProviderPage::removeMDIView(), Gui::PythonDebugger::showDebugMarker(), and switchToTopLevelMode().
windowStateChanged
void Gui::MainWindow::windowStateChanged (QWidget *) signal
Referenced by addWindow(), eventFilter(), and removeWindow().
workbenchActivated
void Gui::MainWindow::workbenchActivated (const QString &) signal
Referenced by activateWorkbench(), and Gui::WorkbenchGroup::WorkbenchGroup().
The documentation for this class was generated from the following files:
MainWindow.h
MainWindow.cpp