FreeCAD: Path Namespace Reference
Path Namespace Reference
Namespaces
Base
Dressup
Geom
GuiInit
Log
Main
Op
Post
Preferences
Tool
Classes
class Area
struct AreaParams
struct AreaStaticParams
struct CAreaConfig
struct CAreaParams
class Command
class Feature
class FeatureArea
class FeatureAreaView
class FeatureCompound
class FeatureShape
class PathSegmentVisitor
class PathSegmentWalker
class PropertyPath
class Toolpath
class Voronoi
class VoronoiCell
class VoronoiEdge
class VoronoiVertex
Typedefs
using FeatureAreaPython = App::FeaturePythonT< FeatureArea >
using FeatureAreaViewPython = App::FeaturePythonT< FeatureAreaView >
using FeaturePython = App::FeaturePythonT< Feature >
using FeatureCompoundPython = App::FeaturePythonT< FeatureCompound >
using FeatureShapePython = App::FeaturePythonT< FeatureShape >
Functions
Base::Vector3d compensateRotation (const Base::Vector3d &pt, const Base::Rotation &rot, const Base::Vector3d &center)
Base::Rotation yawPitchRoll (double a, double b, double c)
Typedef Documentation
FeatureAreaPython
using Path::FeatureAreaPython = typedef App::FeaturePythonT<FeatureArea>
Definition at line 93 of file FeatureArea.h.
FeatureAreaViewPython
using Path::FeatureAreaViewPython = typedef App::FeaturePythonT<FeatureAreaView>
Definition at line 116 of file FeatureArea.h.
FeatureCompoundPython
using Path::FeatureCompoundPython = typedef App::FeaturePythonT<FeatureCompound>
Definition at line 82 of file FeaturePathCompound.h.
FeaturePython
using Path::FeaturePython = typedef App::FeaturePythonT<Feature>
Definition at line 85 of file FeaturePath.h.
FeatureShapePython
using Path::FeatureShapePython = typedef App::FeaturePythonT<FeatureShape>
Definition at line 88 of file FeaturePathShape.h.
Function Documentation
compensateRotation()
Base::Vector3d Path::compensateRotation (const Base::Vector3d & pt, const Base::Rotation & rot, const Base::Vector3d & center)
Definition at line 46 of file PathSegmentWalker.cpp.
References exportCSG::center(), and Base::Rotation::multVec().
Referenced by Path::PathSegmentWalker::walk().
yawPitchRoll()
Base::Rotation Path::yawPitchRoll (double a, double b, double c)
Definition at line 55 of file PathSegmentWalker.cpp.
References a, SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::c, and Base::Rotation::setYawPitchRoll().
Referenced by Path::PathSegmentWalker::walk().