FreeCAD: TechDraw::Preferences Class Reference
TechDraw::Preferences Class Reference
#include <Preferences.h>
Static Public Member Functions
static Base::Reference< ParameterGrp > getPreferenceGroup (const char *Name)
static std::string labelFont ()
static QString labelFontQString ()
static double labelFontSizeMM ()
static double dimFontSizeMM ()
static double dimArrowSize ()
static App::Color normalColor ()
static App::Color selectColor ()
static App::Color preselectColor ()
static App::Color vertexColor ()
static double vertexScale ()
static int scaleType ()
static double scale ()
static bool useGlobalDecimals ()
static bool keepPagesUpToDate ()
static int projectionAngle ()
static bool groupAutoDistribute ()
static double groupSpaceX ()
static double groupSpaceY ()
static int balloonArrow ()
static double balloonKinkLength ()
static int balloonShape ()
static QString defaultTemplate ()
static QString defaultTemplateDir ()
static std::string formatSpec ()
static int altDecimals ()
static int mattingStyle ()
static bool showDetailMatting ()
static bool showDetailHighlight ()
static std::string svgFile ()
static std::string patFile ()
static QString defaultSymbolDir ()
static std::string bitmapFill ()
static double GapISO ()
static double GapASME ()
static bool reportProgress ()
static bool lightOnDark ()
static void lightOnDark (bool state)
static bool monochrome ()
static void monochrome (bool state)
static App::Color lightTextColor ()
static App::Color lightenColor (App::Color orig)
static App::Color getAccessibleColor (App::Color orig)
static bool autoCorrectDimRefs ()
static int scrubCount ()
static double svgHatchFactor ()
static bool SectionUsePreviousCut ()
static int lineStandard ()
static void setLineStandard (int index)
static std::string lineDefinitionLocation ()
static std::string lineElementsLocation ()
static std::string lineGroupFile ()
static int lineGroup ()
static int SectionLineStyle ()
static int CenterLineStyle ()
static int HighlightLineStyle ()
static int HiddenLineStyle ()
static int BreakLineStyle ()
static int LineCapStyle ()
static int LineCapIndex ()
static int LineSpacingISO ()
static std::string currentLineDefFile ()
static std::string currentElementDefFile ()
static int sectionLineConvention ()
static bool showSectionLine ()
static bool includeCutLine ()
static int BreakType ()
static bool useExactMatchOnDims ()
static bool useCameraDirection ()
static bool alwaysShowLabel ()
static bool SnapViews ()
static double SnapLimitFactor ()
static Qt::KeyboardModifiers multiselectModifiers ()
static Qt::KeyboardModifiers balloonDragModifiers ()
static void setBalloonDragModifiers (Qt::KeyboardModifiers newModifiers)
static bool enforceISODate ()
static bool switchOnClick ()
static bool checkShapesBeforeUse ()
static bool debugBadShape ()
static bool useLegacySvgScaling ()
Static Public Attributes
static const double DefaultFontSizeInMM
static const double DefaultArrowSize
Detailed Description
Definition at line 45 of file TechDraw/App/Preferences.h.
Member Function Documentation
altDecimals()
static int TechDraw::Preferences::altDecimals () static
Referenced by TechDraw::DimensionFormatter::getDefaultFormatSpec().
alwaysShowLabel()
static bool TechDraw::Preferences::alwaysShowLabel () static
autoCorrectDimRefs()
static bool TechDraw::Preferences::autoCorrectDimRefs () static
Referenced by TechDraw::DimensionAutoCorrect::autocorrectReferences(), and TechDraw::DrawViewDimension::execute().
balloonArrow()
static int TechDraw::Preferences::balloonArrow () static
Referenced by TechDraw::DrawViewBalloon::DrawViewBalloon().
balloonDragModifiers()
static Qt::KeyboardModifiers TechDraw::Preferences::balloonDragModifiers () static
Referenced by TechDrawGui::QGIBalloonLabel::mousePressEvent().
balloonKinkLength()
static double TechDraw::Preferences::balloonKinkLength () static
Referenced by TechDraw::DrawViewBalloon::DrawViewBalloon().
balloonShape()
static int TechDraw::Preferences::balloonShape () static
Referenced by TechDraw::DrawViewBalloon::DrawViewBalloon().
bitmapFill()
static std::string TechDraw::Preferences::bitmapFill () static
BreakLineStyle()
static int TechDraw::Preferences::BreakLineStyle () static
BreakType()
static int TechDraw::Preferences::BreakType () static
CenterLineStyle()
static int TechDraw::Preferences::CenterLineStyle () static
Referenced by TechDrawGui::QGIViewPart::drawCenterLines().
checkShapesBeforeUse()
static bool TechDraw::Preferences::checkShapesBeforeUse () static
Referenced by TechDraw::ShapeExtractor::checkShape().
currentElementDefFile()
static std::string TechDraw::Preferences::currentElementDefFile () static
currentLineDefFile()
static std::string TechDraw::Preferences::currentLineDefFile () static
Referenced by TechDraw::LineGenerator::getLineDescriptions().
debugBadShape()
static bool TechDraw::Preferences::debugBadShape () static
Referenced by TechDraw::ShapeExtractor::checkShape().
defaultSymbolDir()
static QString TechDraw::Preferences::defaultSymbolDir () static
defaultTemplate()
static QString TechDraw::Preferences::defaultTemplate () static
defaultTemplateDir()
static QString TechDraw::Preferences::defaultTemplateDir () static
dimArrowSize()
static double TechDraw::Preferences::dimArrowSize () static
dimFontSizeMM()
static double TechDraw::Preferences::dimFontSizeMM () static
Referenced by TechDrawGui::QGIViewPart::drawComplexSectionLine(), TechDrawGui::QGIViewPart::drawSectionLine(), and MRichTextEdit::getDefFontSizeNum().
enforceISODate()
static bool TechDraw::Preferences::enforceISODate () static
Referenced by TechDraw::DrawTemplate::getAutofillValue().
formatSpec()
static std::string TechDraw::Preferences::formatSpec () static
Referenced by TechDraw::DimensionFormatter::getDefaultFormatSpec().
GapASME()
static double TechDraw::Preferences::GapASME () static
GapISO()
static double TechDraw::Preferences::GapISO () static
getAccessibleColor()
static App::Color TechDraw::Preferences::getAccessibleColor (App::Color orig) static
Referenced by TechDrawGui::QGIViewPart::drawAllEdges(), TechDrawGui::QGIViewAnnotation::drawAnnotation(), TechDrawGui::QGIViewPart::drawComplexSectionLine(), TechDrawGui::QGIViewPart::drawHighlight(), TechDrawGui::QGIViewPart::drawSectionLine(), TechDrawGui::QGIViewPart::formatGeomFromCenterLine(), TechDrawGui::QGIViewPart::formatGeomFromCosmetic(), and TechDrawGui::QGIViewPart::prefBreaklineColor().
getPreferenceGroup()
static Base::Reference<ParameterGrp> TechDraw::Preferences::getPreferenceGroup (const char * Name) static
Referenced by TechDraw::DrawPage::AllowPageOverride(), TechDraw::DrawViewDetail::debugDetail(), TechDraw::DrawViewSection::debugSection(), TechDrawGui::QGIViewPart::drawAllVertexes(), TechDraw::DrawPage::DrawPage(), TechDraw::DrawProjGroup::DrawProjGroup(), TechDraw::DrawViewPart::DrawViewPart(), TechDrawGui::QGICenterLine::getCenterStyle(), TechDraw::DrawLeaderLine::getDefAuto(), TechDraw::LineFormat::getDefEdgeStyle(), TechDrawGui::Rez::getParameter(), TechDrawGui::ViewProviderViewSection::getParameters(), TechDraw::DrawViewSection::getParameters(), TechDraw::DrawViewDimension::getPrefixForDimType(), TechDraw::DrawPage::GlobalUpdateDrawings(), TechDraw::DrawViewPart::handleFaces(), TechDraw::DrawUtil::isCrazy(), TechDraw::DrawViewPart::newFaceFinder(), TechDraw::DrawViewSection::prefCutSurface(), TechDrawGui::QGIViewPart::prefFaceEdges(), TechDraw::DrawGeomHatch::prefGeomHatchColor(), TechDraw::DrawGeomHatch::prefGeomHatchName(), TechDrawGui::QGIViewPart::prefPrintCenters(), TechDraw::DrawView::prefScale(), TechDraw::DrawView::prefScaleType(), TechDraw::DrawHatch::prefSvgHatchColor(), TechDraw::CosmeticVertex::restoreCosmetic(), TechDraw::DrawViewSection::showSectionEdges(), TechDraw::DrawViewDimension::showUnits(), and TechDrawGui::ViewProviderViewSection::ViewProviderViewSection().
groupAutoDistribute()
static bool TechDraw::Preferences::groupAutoDistribute () static
groupSpaceX()
static double TechDraw::Preferences::groupSpaceX () static
groupSpaceY()
static double TechDraw::Preferences::groupSpaceY () static
HiddenLineStyle()
static int TechDraw::Preferences::HiddenLineStyle () static
Referenced by TechDrawGui::QGIViewPart::drawAllEdges().
HighlightLineStyle()
static int TechDraw::Preferences::HighlightLineStyle () static
includeCutLine()
static bool TechDraw::Preferences::includeCutLine () static
keepPagesUpToDate()
static bool TechDraw::Preferences::keepPagesUpToDate () static
Referenced by TechDraw::DrawPage::DrawPage().
labelFont()
static std::string TechDraw::Preferences::labelFont () static
Referenced by TechDraw::DrawViewAnnotation::DrawViewAnnotation(), and TechDraw::DrawViewSpreadsheet::DrawViewSpreadsheet().
labelFontQString()
static QString TechDraw::Preferences::labelFontQString () static
labelFontSizeMM()
static double TechDraw::Preferences::labelFontSizeMM () static
Referenced by TechDrawGui::QGIViewPart::drawHighlight(), and TechDraw::DrawViewAnnotation::DrawViewAnnotation().
lightenColor()
static App::Color TechDraw::Preferences::lightenColor (App::Color orig) static
lightOnDark() [1/2]
static bool TechDraw::Preferences::lightOnDark () static
lightOnDark() [2/2]
static void TechDraw::Preferences::lightOnDark (bool state) static
lightTextColor()
static App::Color TechDraw::Preferences::lightTextColor () static
LineCapIndex()
static int TechDraw::Preferences::LineCapIndex () static
LineCapStyle()
static int TechDraw::Preferences::LineCapStyle () static
Referenced by TechDraw::LineGenerator::getLinePen().
lineDefinitionLocation()
static std::string TechDraw::Preferences::lineDefinitionLocation () static
Referenced by TechDraw::LineGenerator::getAvailableLineStandards().
lineElementsLocation()
static std::string TechDraw::Preferences::lineElementsLocation () static
lineGroup()
static int TechDraw::Preferences::lineGroup () static
Referenced by TechDraw::LineGroup::getDefaultWidth().
lineGroupFile()
static std::string TechDraw::Preferences::lineGroupFile () static
Referenced by TechDraw::LineGroup::lineGroupFactory().
LineSpacingISO()
static int TechDraw::Preferences::LineSpacingISO () static
lineStandard()
static int TechDraw::Preferences::lineStandard () static
Referenced by TechDraw::LineGenerator::fromQtStyle(), TechDraw::LineGenerator::getLineStandardsBody(), and TechDraw::LineGenerator::isCurrentProportional().
mattingStyle()
static int TechDraw::Preferences::mattingStyle () static
Referenced by TechDrawGui::QGIMatting::getHoleStyle(), TechDrawGui::QGIHighlight::getHoleStyle(), and TechDraw::DrawViewDetail::makeDetailShape().
monochrome() [1/2]
static bool TechDraw::Preferences::monochrome () static
monochrome() [2/2]
static void TechDraw::Preferences::monochrome (bool state) static
multiselectModifiers()
static Qt::KeyboardModifiers TechDraw::Preferences::multiselectModifiers () static
Referenced by TechDrawGui::QGIBalloonLabel::mousePressEvent().
normalColor()
static App::Color TechDraw::Preferences::normalColor () static
Referenced by TechDraw::DrawViewAnnotation::DrawViewAnnotation(), and TechDraw::LineFormat::getDefEdgeColor().
patFile()
static std::string TechDraw::Preferences::patFile () static
Referenced by TechDraw::DrawGeomHatch::prefGeomHatchFile().
preselectColor()
static App::Color TechDraw::Preferences::preselectColor () static
projectionAngle()
static int TechDraw::Preferences::projectionAngle () static
Referenced by TechDraw::DrawPage::DrawPage(), and TechDraw::DrawProjGroup::getDefProjConv().
reportProgress()
static bool TechDraw::Preferences::reportProgress () static
Referenced by TechDraw::DrawView::showProgressMessage().
scale()
static double TechDraw::Preferences::scale () static
scaleType()
static int TechDraw::Preferences::scaleType () static
scrubCount()
static int TechDraw::Preferences::scrubCount () static
Referenced by TechDraw::DrawViewPart::DrawViewPart().
sectionLineConvention()
static int TechDraw::Preferences::sectionLineConvention () static
SectionLineStyle()
static int TechDraw::Preferences::SectionLineStyle () static
SectionUsePreviousCut()
static bool TechDraw::Preferences::SectionUsePreviousCut () static
Referenced by TechDraw::DrawViewSection::DrawViewSection().
selectColor()
static App::Color TechDraw::Preferences::selectColor () static
setBalloonDragModifiers()
static void TechDraw::Preferences::setBalloonDragModifiers (Qt::KeyboardModifiers newModifiers) static
setLineStandard()
static void TechDraw::Preferences::setLineStandard (int index) static
showDetailHighlight()
static bool TechDraw::Preferences::showDetailHighlight () static
Referenced by TechDraw::DrawViewDetail::DrawViewDetail().
showDetailMatting()
static bool TechDraw::Preferences::showDetailMatting () static
Referenced by TechDraw::DrawViewDetail::DrawViewDetail().
showSectionLine()
static bool TechDraw::Preferences::showSectionLine () static
SnapLimitFactor()
static double TechDraw::Preferences::SnapLimitFactor () static
SnapViews()
static bool TechDraw::Preferences::SnapViews () static
svgFile()
static std::string TechDraw::Preferences::svgFile () static
Referenced by TechDraw::DrawHatch::prefSvgHatch().
svgHatchFactor()
static double TechDraw::Preferences::svgHatchFactor () static
switchOnClick()
static bool TechDraw::Preferences::switchOnClick () static
useCameraDirection()
static bool TechDraw::Preferences::useCameraDirection () static
Referenced by TechDraw::CommandHelpers::viewDirection().
useExactMatchOnDims()
static bool TechDraw::Preferences::useExactMatchOnDims () static
Referenced by TechDraw::GeometryMatcher::compareGeometry().
useGlobalDecimals()
static bool TechDraw::Preferences::useGlobalDecimals () static
Referenced by TechDraw::DrawViewDimension::useDecimals().
useLegacySvgScaling()
static bool TechDraw::Preferences::useLegacySvgScaling () static
vertexColor()
static App::Color TechDraw::Preferences::vertexColor () static
Referenced by TechDraw::CosmeticVertex::CosmeticVertex().
vertexScale()
static double TechDraw::Preferences::vertexScale () static
Referenced by TechDraw::CosmeticVertex::CosmeticVertex().
Member Data Documentation
DefaultArrowSize
const double TechDraw::Preferences::DefaultArrowSize static
Definition at line 80 of file TechDraw/App/Preferences.h.
DefaultFontSizeInMM
const double TechDraw::Preferences::DefaultFontSizeInMM static
Definition at line 79 of file TechDraw/App/Preferences.h.
The documentation for this class was generated from the following file:
TechDraw/App/Preferences.h