FreeCAD: GetCurveItem Class Reference
GetCurveItem Class Reference
Public Member Functions
GetCurveItem (CurveTree *ct, std::list< CVertex >::iterator EIt)
void GetCurve (CCurve &output)
CVertex & back ()
Public Attributes
CurveTree * curve_tree
std::list< CVertex >::iterator EndIt
Static Public Attributes
static std::list< GetCurveItem > to_do_list
Detailed Description
Definition at line 69 of file AreaPocket.cpp.
Constructor & Destructor Documentation
GetCurveItem()
GetCurveItem::GetCurveItem (CurveTree * ct, std::list< CVertex >::iterator EIt) inline
Definition at line 76 of file AreaPocket.cpp.
Member Function Documentation
back()
CVertex& GetCurveItem::back () inline
Definition at line 82 of file AreaPocket.cpp.
References EndIt.
Referenced by GetCurve().
GetCurve()
void GetCurveItem::GetCurve (CCurve & output)
Definition at line 93 of file AreaPocket.cpp.
References back(), CurveTree::curve, curve_tree, Point::dist(), EndIt, CurveTree::inners, CVertex::m_c, CVertex::m_p, CArea::m_please_abort, CVertex::m_type, CArea::m_units, CCurve::m_vertices, Span::On(), CurveTree::point_on_parent, InitGui::t, and to_do_list.
Referenced by CArea::MakeOnePocketCurve().
Member Data Documentation
curve_tree
CurveTree* GetCurveItem::curve_tree
Definition at line 72 of file AreaPocket.cpp.
Referenced by GetCurve().
EndIt
std::list<CVertex>::iterator GetCurveItem::EndIt
Definition at line 73 of file AreaPocket.cpp.
Referenced by back(), and GetCurve().
to_do_list
std::list< GetCurveItem > GetCurveItem::to_do_list static
Definition at line 74 of file AreaPocket.cpp.
Referenced by GetCurve(), and CArea::MakeOnePocketCurve().
The documentation for this class was generated from the following file:
AreaPocket.cpp