FreeCAD: ifc2x3.ifcwaterproperties Class Reference
ifc2x3.ifcwaterproperties Class Reference
Public Member Functions
def __init__ (self, inherited0__material, ispotable, hardness, alkalinityconcentration, acidityconcentration, impuritiescontent, phlevel, dissolvedsolidscontent)
def ispotable ()
def hardness ()
def alkalinityconcentration ()
def acidityconcentration ()
def impuritiescontent ()
def phlevel ()
def dissolvedsolidscontent ()
Public Member Functions inherited from ifc2x3.ifcmaterialproperties
def __init__ (self, material)
def material ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
ispotable
hardness
alkalinityconcentration
acidityconcentration
impuritiescontent
phlevel
dissolvedsolidscontent
Public Attributes inherited from ifc2x3.ifcmaterialproperties
material
Detailed Description
Entity ifcwaterproperties definition.
:param ispotable
:type ispotable:BOOLEAN
:param hardness
:type hardness:ifcionconcentrationmeasure
:param alkalinityconcentration
:type alkalinityconcentration:ifcionconcentrationmeasure
:param acidityconcentration
:type acidityconcentration:ifcionconcentrationmeasure
:param impuritiescontent
:type impuritiescontent:ifcnormalisedratiomeasure
:param phlevel
:type phlevel:ifcphmeasure
:param dissolvedsolidscontent
:type dissolvedsolidscontent:ifcnormalisedratiomeasure
Definition at line 32162 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcwaterproperties.__init__ (self, inherited0__material, ispotable, hardness, alkalinityconcentration, acidityconcentration, impuritiescontent, phlevel, dissolvedsolidscontent)
Definition at line 32186 of file ifc2x3.py.
Member Function Documentation
acidityconcentration()
def ifc2x3.ifcwaterproperties.acidityconcentration ()
Definition at line 32239 of file ifc2x3.py.
References ifc2x3.ifcwaterproperties._acidityconcentration, ifc2x3.ifcwaterproperties.acidityconcentration, and SCL.TypeChecker.check_type().
alkalinityconcentration()
def ifc2x3.ifcwaterproperties.alkalinityconcentration ()
Definition at line 32225 of file ifc2x3.py.
References ifc2x3.ifcwaterproperties._alkalinityconcentration, ifc2x3.ifcwaterproperties.alkalinityconcentration, and SCL.TypeChecker.check_type().
dissolvedsolidscontent()
def ifc2x3.ifcwaterproperties.dissolvedsolidscontent ()
Definition at line 32281 of file ifc2x3.py.
References ifc2x3.ifcwaterproperties._dissolvedsolidscontent, SCL.TypeChecker.check_type(), and ifc2x3.ifcwaterproperties.dissolvedsolidscontent.
hardness()
def ifc2x3.ifcwaterproperties.hardness ()
Definition at line 32211 of file ifc2x3.py.
References ifc2x3.ifcwaterproperties._hardness, SCL.TypeChecker.check_type(), and ifc2x3.ifcwaterproperties.hardness.
impuritiescontent()
def ifc2x3.ifcwaterproperties.impuritiescontent ()
Definition at line 32253 of file ifc2x3.py.
References ifc2x3.ifcwaterproperties._impuritiescontent, SCL.TypeChecker.check_type(), and ifc2x3.ifcwaterproperties.impuritiescontent.
ispotable()
def ifc2x3.ifcwaterproperties.ispotable ()
Definition at line 32197 of file ifc2x3.py.
References ifc2x3.ifcwaterproperties._ispotable, SCL.SimpleDataTypes.BOOLEAN, SCL.TypeChecker.check_type(), and ifc2x3.ifcwaterproperties.ispotable.
phlevel()
def ifc2x3.ifcwaterproperties.phlevel ()
Definition at line 32267 of file ifc2x3.py.
References ifc2x3.ifcwaterproperties._phlevel, SCL.TypeChecker.check_type(), and ifc2x3.ifcwaterproperties.phlevel.
Member Data Documentation
acidityconcentration
ifc2x3.ifcwaterproperties.acidityconcentration
Definition at line 32191 of file ifc2x3.py.
Referenced by ifc2x3.ifcwaterproperties.acidityconcentration().
alkalinityconcentration
ifc2x3.ifcwaterproperties.alkalinityconcentration
Definition at line 32190 of file ifc2x3.py.
Referenced by ifc2x3.ifcwaterproperties.alkalinityconcentration().
dissolvedsolidscontent
ifc2x3.ifcwaterproperties.dissolvedsolidscontent
Definition at line 32194 of file ifc2x3.py.
Referenced by ifc2x3.ifcwaterproperties.dissolvedsolidscontent().
hardness
ifc2x3.ifcwaterproperties.hardness
Definition at line 32189 of file ifc2x3.py.
Referenced by ifc2x3.ifcwaterproperties.hardness().
impuritiescontent
ifc2x3.ifcwaterproperties.impuritiescontent
Definition at line 32192 of file ifc2x3.py.
Referenced by ifc2x3.ifcwaterproperties.impuritiescontent().
ispotable
ifc2x3.ifcwaterproperties.ispotable
Definition at line 32188 of file ifc2x3.py.
Referenced by ifc2x3.ifcwaterproperties.ispotable().
phlevel
ifc2x3.ifcwaterproperties.phlevel
Definition at line 32193 of file ifc2x3.py.
Referenced by ifc2x3.ifcwaterproperties.phlevel().
The documentation for this class was generated from the following file:
ifc2x3.py