FreeCAD: MatGui::ArrayDelegate Class Reference
MatGui::ArrayDelegate Class Reference
#include <ArrayDelegate.h>
Public Member Functions
ArrayDelegate (Materials::MaterialValue::ValueType type=Materials::MaterialValue::None, const QString &units=QString(), QObject *parent=nullptr)
virtual ~ArrayDelegate ()=default
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const override
QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &styleOption, const QModelIndex &index) const override
void setEditorData (QWidget *editor, const QModelIndex &index) const override
Detailed Description
Definition at line 58 of file ArrayDelegate.h.
Constructor & Destructor Documentation
ArrayDelegate()
ArrayDelegate::ArrayDelegate (Materials::MaterialValue::ValueType type = Materials::MaterialValue::None, const QString & units = QString(), QObject * parent = nullptr)
Definition at line 58 of file ArrayDelegate.cpp.
~ArrayDelegate()
virtual MatGui::ArrayDelegate::~ArrayDelegate () virtual default
Member Function Documentation
createEditor()
QWidget * ArrayDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & styleOption, const QModelIndex & index) const override
Definition at line 103 of file ArrayDelegate.cpp.
References Path.Post.Utils::editor(), and Init::parent.
paint()
void ArrayDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const override
Definition at line 66 of file ArrayDelegate.cpp.
References Materials::MaterialValue::Quantity.
setEditorData()
void ArrayDelegate::setEditorData (QWidget * editor, const QModelIndex & index) const override
Definition at line 89 of file ArrayDelegate.cpp.
References Path.Post.Utils::editor(), Materials::MaterialValue::Quantity, and Gui::QuantitySpinBox::setValue().
The documentation for this class was generated from the following files:
ArrayDelegate.h
ArrayDelegate.cpp