FreeCAD: PyTools.h File Reference
PyTools.h File Reference
#include <stdio.h>
#include <Python.h>
#include <FCGlobal.h>
Enumerations
enum PPStringModes { PP_EXPRESSION, PP_STATEMENT }
Functions
const char * PP_Init (const char *modname)
int PP_Make_Dummy_Module (const char *modname)
PyObject * PP_Load_Module (const char *modname)
PyObject * PP_Load_Attribute (const char *modname, const char *attrname)
int PP_Run_Command_Line (const char *prompt)
int PP_Convert_Result (PyObject *presult, const char *resFormat, void *resTarget)
int PP_Get_Global (const char *modname, const char *varname, const char *resfmt, void *cresult)
int PP_Set_Global (const char *modname, const char *varname, const char *valfmt,...)
int PP_Run_Codestr (PPStringModes mode, const char *code, const char *modname, const char *resfmt, void *cresult)
PyObject * PP_Debug_Codestr (PPStringModes mode, const char *codestring, PyObject *moddict)
PyObject * PP_Compile_Codestr (PPStringModes mode, const char *codestr)
int PP_Run_Bytecode (PyObject *codeobj, const char *modname, const char *resfmt, void *restarget)
PyObject * PP_Debug_Bytecode (PyObject *codeobject, PyObject *moddict)
BaseExport int PP_Run_Function (const char *modname, const char *funcname, const char *resfmt, void *cresult, const char *argfmt,...)
PyObject * PP_Debug_Function (PyObject *func, PyObject *args)
int PP_Run_Known_Callable (PyObject *object, const char *resfmt, void *restarget, const char *argfmt,...)
int PP_Run_Method (PyObject *pobject, const char *method, const char *resfmt, void *cresult, const char *argfmt,...)
int PP_Get_Member (PyObject *pobject, const char *attrname, const char *resfmt, void *cresult)
int PP_Set_Member (PyObject *pobject, const char *attrname, const char *valfmt,...)
void PP_Fetch_Error_Text ()
Variables
int PP_RELOAD
int PP_DEBUG
char PP_last_error_type []
char PP_last_error_info []
char PP_last_error_trace []
PyObject * PP_PyDict_Object
PyObject * PP_last_traceback
PyObject * PP_last_exception_type
Enumeration Type Documentation
PPStringModes
enum PPStringModes
Enumerator
PP_EXPRESSION
PP_STATEMENT
Definition at line 84 of file PyTools.h.
Function Documentation
PP_Compile_Codestr()
PyObject* PP_Compile_Codestr (PPStringModes mode, const char * codestr)
PP_Convert_Result()
int PP_Convert_Result (PyObject * presult, const char * resFormat, void * resTarget)
Referenced by Base::InterpreterSingleton::runMethod().
PP_Debug_Bytecode()
PyObject* PP_Debug_Bytecode (PyObject * codeobject, PyObject * moddict)
PP_Debug_Codestr()
PyObject* PP_Debug_Codestr (PPStringModes mode, const char * codestring, PyObject * moddict)
PP_Debug_Function()
PyObject* PP_Debug_Function (PyObject * func, PyObject * args)
PP_Fetch_Error_Text()
void PP_Fetch_Error_Text ()
Referenced by Base::PyException::PyException().
PP_Get_Global()
int PP_Get_Global (const char * modname, const char * varname, const char * resfmt, void * cresult)
PP_Get_Member()
int PP_Get_Member (PyObject * pobject, const char * attrname, const char * resfmt, void * cresult)
PP_Init()
const char* PP_Init (const char * modname)
PP_Load_Attribute()
PyObject* PP_Load_Attribute (const char * modname, const char * attrname)
PP_Load_Module()
PyObject* PP_Load_Module (const char * modname)
Referenced by Base::InterpreterSingleton::getValue(), Base::InterpreterSingleton::loadModule(), Base::InterpreterSingleton::runInteractiveString(), Base::InterpreterSingleton::runString(), and Base::InterpreterSingleton::runStringObject().
PP_Make_Dummy_Module()
int PP_Make_Dummy_Module (const char * modname)
PP_Run_Bytecode()
int PP_Run_Bytecode (PyObject * codeobj, const char * modname, const char * resfmt, void * restarget)
PP_Run_Codestr()
int PP_Run_Codestr (PPStringModes mode, const char * code, const char * modname, const char * resfmt, void * cresult)
PP_Run_Command_Line()
int PP_Run_Command_Line (const char * prompt)
Referenced by Base::InterpreterSingleton::runCommandLine().
PP_Run_Function()
BaseExport int PP_Run_Function (const char * modname, const char * funcname, const char * resfmt, void * cresult, const char * argfmt, ...)
PP_Run_Known_Callable()
int PP_Run_Known_Callable (PyObject * object, const char * resfmt, void * restarget, const char * argfmt, ...)
PP_Run_Method()
int PP_Run_Method (PyObject * pobject, const char * method, const char * resfmt, void * cresult, const char * argfmt, ...)
Referenced by Base::InterpreterSingleton::runMethodObject(), and Base::InterpreterSingleton::runMethodVoid().
PP_Set_Global()
int PP_Set_Global (const char * modname, const char * varname, const char * valfmt, ...)
PP_Set_Member()
int PP_Set_Member (PyObject * pobject, const char * attrname, const char * valfmt, ...)
Variable Documentation
PP_DEBUG
int PP_DEBUG
PP_last_error_info
char PP_last_error_info[]
Referenced by Base::PyException::PyException().
PP_last_error_trace
char PP_last_error_trace[]
Referenced by Base::PyException::PyException().
PP_last_error_type
char PP_last_error_type[]
Referenced by Base::PyException::PyException().
PP_last_exception_type
PyObject* PP_last_exception_type
Referenced by Base::PyException::PyException().
PP_last_traceback
PyObject* PP_last_traceback
Referenced by Base::PyException::ReportException().
PP_PyDict_Object
PyObject* PP_PyDict_Object
Referenced by Base::PyException::PyException(), and Base::PyException::raiseException().
PP_RELOAD
int PP_RELOAD