FreeCAD: SheetTableView.cpp File Reference
SheetTableView.cpp File Reference
#include "PreCompiled.h"
#include <QAction>
#include <QApplication>
#include <QClipboard>
#include <QKeyEvent>
#include <QMenu>
#include <QMessageBox>
#include <QMimeData>
#include <QTextTableCell>
#include <App/Application.h>
#include <App/AutoTransaction.h>
#include <App/Document.h>
#include <App/Range.h>
#include <Base/Reader.h>
#include <Base/Stream.h>
#include <Base/Writer.h>
#include <Gui/Application.h>
#include <Gui/CommandT.h>
#include <Gui/MainWindow.h>
#include <Mod/Spreadsheet/App/Cell.h>
#include "DlgBindSheet.h"
#include "DlgSheetConf.h"
#include "LineEdit.h"
#include "PropertiesDialog.h"
#include "SheetTableView.h"
#include "moc_SheetTableView.cpp"
Functions
static std::pair< int, int > selectedMinMaxRows (QModelIndexList list)
static std::pair< int, int > selectedMinMaxColumns (QModelIndexList list)
static const QLatin1String _SheetMime ("application/x-fc-spreadsheet")
Function Documentation
_SheetMime()
static const QLatin1String _SheetMime ("application/x-fc-spreadsheet") static
Referenced by SpreadsheetGui::SheetTableView::_copySelection(), and SpreadsheetGui::SheetTableView::pasteClipboard().
selectedMinMaxColumns()
static std::pair<int, int> selectedMinMaxColumns (QModelIndexList list) static
Definition at line 99 of file SheetTableView.cpp.
References App::ExpressionParser::column, KDL::max(), and KDL::min().
Referenced by SpreadsheetGui::SheetTableView::insertColumnsAfter(), and SpreadsheetGui::SheetTableView::SheetTableView().
selectedMinMaxRows()
static std::pair<int, int> selectedMinMaxRows (QModelIndexList list) static
Definition at line 87 of file SheetTableView.cpp.
References KDL::max(), and KDL::min().
Referenced by SpreadsheetGui::SheetTableView::insertRowsAfter(), and SpreadsheetGui::SheetTableView::SheetTableView().