FreeCAD: Gui::OutputStdout Class Reference
Gui::OutputStdout Class Reference
#include <PythonConsolePy.h>
Public Member Functions
OutputStdout ()
~OutputStdout () override
Py::Object getattr (const char *name) override
Py::Object repr () override
Py::Object write (const Py::Tuple &)
Py::Object flush (const Py::Tuple &)
Py::Object isatty ()
Static Public Member Functions
static void init_type ()
Detailed Description
Python class for redirection of stdout to FreeCAD's output console window. This allows one to report all Python output to the report view which simplifies debugging scripts.
See also
PythonStdout
PythonStderr
Author
Werner Mayer
Definition at line 94 of file PythonConsolePy.h.
Constructor & Destructor Documentation
OutputStdout()
OutputStdout::OutputStdout () default
~OutputStdout()
OutputStdout::~OutputStdout () override default
Member Function Documentation
flush()
Py::Object OutputStdout::flush (const Py::Tuple &)
Definition at line 207 of file PythonConsolePy.cpp.
Referenced by init_type().
getattr()
Py::Object OutputStdout::getattr (const char * name) override
Definition at line 174 of file PythonConsolePy.cpp.
References SplineSurface::i.
init_type()
void OutputStdout::init_type () static
Definition at line 159 of file PythonConsolePy.cpp.
References flush(), isatty(), and write().
Referenced by Gui::Application::Application().
isatty()
Py::Object OutputStdout::isatty ()
Definition at line 212 of file PythonConsolePy.cpp.
References femtools.tokrules::False.
Referenced by init_type().
repr()
Py::Object OutputStdout::repr () override
Definition at line 183 of file PythonConsolePy.cpp.
References toolbit-attributes::s, and src.Mod.Test.testmakeWireString::String.
write()
Py::Object OutputStdout::write (const Py::Tuple & args)
Definition at line 191 of file PythonConsolePy.cpp.
References toolbit-attributes::args, Base::Console(), Base::ConsoleSingleton::Message(), and ArchBuildingPart::unicode.
Referenced by init_type().
The documentation for this class was generated from the following files:
PythonConsolePy.h
PythonConsolePy.cpp