FreeCAD: SketcherGui::EditDatumDialog Class Reference
SketcherGui::EditDatumDialog Class Reference
#include <EditDatumDialog.h>
Public Member Functions
EditDatumDialog (ViewProviderSketch *vp, int ConstrNbr)
EditDatumDialog (Sketcher::SketchObject *pcSketch, int ConstrNbr)
~EditDatumDialog () override
int exec (bool atCursor=true)
bool isSuccess ()
Detailed Description
Definition at line 41 of file EditDatumDialog.h.
Constructor & Destructor Documentation
EditDatumDialog() [1/2]
EditDatumDialog::EditDatumDialog (ViewProviderSketch * vp, int ConstrNbr)
Definition at line 53 of file EditDatumDialog.cpp.
References SketcherExample::Constraints, Sketcher::SketchObject::Constraints, SketcherGui::ViewProviderSketch::getSketchObject(), and Sketcher::PropertyConstraintList::getValues().
EditDatumDialog() [2/2]
EditDatumDialog::EditDatumDialog (Sketcher::SketchObject * pcSketch, int ConstrNbr)
Definition at line 62 of file EditDatumDialog.cpp.
References SketcherExample::Constraints, Sketcher::SketchObject::Constraints, and Sketcher::PropertyConstraintList::getValues().
~EditDatumDialog()
EditDatumDialog::~EditDatumDialog () override
Definition at line 70 of file EditDatumDialog.cpp.
Member Function Documentation
exec()
int EditDatumDialog::exec (bool atCursor = true)
Definition at line 73 of file EditDatumDialog.cpp.
References Sketcher::Angle, Base::Unit::Angle, draftgeoutils.intersections::connect(), Sketcher::SketchObject::Constraints, Sketcher::PropertyConstraintList::createPath(), Sketcher::Diameter, Gui::getMainWindow(), Sketcher::Constraint::getValue(), Sketcher::SketchObject::hasConflicts(), Sketcher::Constraint::isDimensional(), Sketcher::Constraint::isDriving, Base::Unit::Length, KDL::max(), KDL::min(), Sketcher::Constraint::Name, RobotExample::pos, Sketcher::Radius, Base::Quantity::setUnit(), Base::Quantity::setValue(), Gui::QuantitySpinBox::showFormulaDialog(), Sketcher::SnellsLaw, Gui::TranslatedUserWarning(), Sketcher::Constraint::Type, Gui::QuantitySpinBox::valueChanged(), Sketcher::Weight, MovieTool::x, and MovieTool::y.
Referenced by SketcherGui::ViewProviderSketch::editDoubleClicked(), DrawSketchHandlerDimension::finalizeCommand(), finishDatumConstraint(), and SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsItemActivated().
isSuccess()
bool EditDatumDialog::isSuccess ()
Definition at line 270 of file EditDatumDialog.cpp.
Referenced by DrawSketchHandlerDimension::finalizeCommand().
The documentation for this class was generated from the following files:
EditDatumDialog.h
EditDatumDialog.cpp