FreeCAD: PathSimulator::PathSim Class Reference
PathSimulator::PathSim Class Reference
#include <PathSim.h>
Public Member Functions
PathSim ()
~PathSim ()
void BeginSimulation (Part::TopoShape *stock, float resolution)
void SetToolShape (const TopoDS_Shape &toolShape, float resolution)
Base::Placement * ApplyCommand (Base::Placement *pos, Command *cmd)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Attributes
std::unique_ptr< cStock > m_stock
std::unique_ptr< cSimTool > m_tool
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
The representation of a CNC Toolpath Simulator
Definition at line 43 of file PathSim.h.
Constructor & Destructor Documentation
PathSim()
PathSim::PathSim ()
Definition at line 33 of file PathSim.cpp.
~PathSim()
PathSim::~PathSim ()
Definition at line 36 of file PathSim.cpp.
Member Function Documentation
ApplyCommand()
Base::Placement * PathSim::ApplyCommand (Base::Placement * pos, Command * cmd)
Definition at line 56 of file PathSim.cpp.
References Path::Command::getCenter(), Path::Command::Name, RobotExample::pos, Base::Placement::setPosition(), Point3D::UpdateCmd(), SurfaceTests.TestBlendCurve::vec, Point3D::x, Point3D::y, and Point3D::z.
BeginSimulation()
void PathSim::BeginSimulation (Part::TopoShape * stock, float resolution)
Definition at line 39 of file PathSim.cpp.
References Part::TopoShape::getBoundBox(), Base::BoundBox3< Precision >::LengthX(), Base::BoundBox3< Precision >::LengthY(), Base::BoundBox3< Precision >::LengthZ(), Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, and Base::BoundBox3< Precision >::MinZ.
SetToolShape()
void PathSim::SetToolShape (const TopoDS_Shape & toolShape, float resolution)
Definition at line 51 of file PathSim.cpp.
Member Data Documentation
m_stock
std::unique_ptr<cStock> PathSimulator::PathSim::m_stock
Definition at line 56 of file PathSim.h.
m_tool
std::unique_ptr<cSimTool> PathSimulator::PathSim::m_tool
Definition at line 57 of file PathSim.h.
The documentation for this class was generated from the following files:
PathSim.h
PathSim.cpp