FreeCAD: draftguitools.gui_edit_draft_objects.DraftCircleGuiTools Class Reference
draftguitools.gui_edit_draft_objects.DraftCircleGuiTools Class Reference
DRAFT » draftguitools
Public Member Functions
def __init__ (self)
def get_edit_points (self, obj)
def update_object_from_edit_points (self, obj, node_idx, v, alt_edit_mode=0)
def get_edit_point_context_menu (self, edit_command, obj, node_idx)
def handle_move_arc (self, edit_command, obj, node_idx)
def handle_set_first_angle (self, edit_command, obj, node_idx)
def handle_set_last_angle (self, edit_command, obj, node_idx)
def handle_set_radius (self, edit_command, obj, node_idx)
def get_edit_obj_context_menu (self, edit_command, obj, position)
def init_preview_object (self, obj)
def update_preview_object (self, edit_command, obj, node_idx, v)
def getArcStart (self, obj, global_placement=False)
def getArcEnd (self, obj, global_placement=False)
def getArcMid (self, obj, global_placement=False)
def pointOnCircle (self, obj, angle, global_placement=False)
def arcInvert (self, obj)
Public Member Functions inherited from draftguitools.gui_edit_base_object.GuiTools
def get_object_style (self, obj)
def set_object_editing_style (self, obj)
def restore_object_style (self, obj, modes)
Detailed Description
Definition at line 272 of file gui_edit_draft_objects.py.
Constructor & Destructor Documentation
__init__()
def draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.__init__ (self)
Reimplemented from draftguitools.gui_edit_base_object.GuiTools.
Definition at line 274 of file gui_edit_draft_objects.py.
Member Function Documentation
arcInvert()
def draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.arcInvert (self, obj)
Definition at line 496 of file gui_edit_draft_objects.py.
Referenced by draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.get_edit_obj_context_menu().
get_edit_obj_context_menu()
def draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.get_edit_obj_context_menu (self, edit_command, obj, position)
Get the context menu associated to edited object (user is over the object)
Return a list of tuples containing menu labels and associated functions:
    return [
("action label", lambda: self.handle_action_label(edit_command, obj, position)),
    ]
Parameters:
edit_command: running Draft_Edit command
obj: the edited object
position: position of the cursor on the screen (x, y)
Reimplemented from draftguitools.gui_edit_base_object.GuiTools.
Definition at line 402 of file gui_edit_draft_objects.py.
References draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.arcInvert().
get_edit_point_context_menu()
def draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.get_edit_point_context_menu (self, edit_command, obj, node_idx)
Get the context menu associated to edit points (user is over an editpoint)
Return a list of tuples containing menu labels and associated functions:
    return [
("action label", lambda: self.handle_action_label(edit_command, obj, node_idx)),
    ]
Parameters:
edit_command: running Draft_Edit command
obj: the edited object
node_idx: number of the edited node
Reimplemented from draftguitools.gui_edit_base_object.GuiTools.
Definition at line 366 of file gui_edit_draft_objects.py.
References draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.handle_move_arc(), draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.handle_set_first_angle(), draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.handle_set_last_angle(), and draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.handle_set_radius().
get_edit_points()
def draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.get_edit_points (self, obj)
Return the list of edipoints for the given Draft Arc or Circle.
circle:
0 : Placement.Base or center
1 : radius
arc:
0 : Placement.Base or center
1 : first endpoint
2 : second endpoint
3 : midpoint
Reimplemented from draftguitools.gui_edit_base_object.GuiTools.
Definition at line 277 of file gui_edit_draft_objects.py.
getArcEnd()
def draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.getArcEnd (self, obj, global_placement = False)
Definition at line 470 of file gui_edit_draft_objects.py.
References draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.pointOnCircle().
Referenced by draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.update_object_from_edit_points(), and draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.update_preview_object().
getArcMid()
def draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.getArcMid (self, obj, global_placement = False)
Definition at line 475 of file gui_edit_draft_objects.py.
References draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.pointOnCircle().
Referenced by draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.update_object_from_edit_points(), and draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.update_preview_object().
getArcStart()
def draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.getArcStart (self, obj, global_placement = False)
Definition at line 465 of file gui_edit_draft_objects.py.
References draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.pointOnCircle().
Referenced by draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.update_object_from_edit_points(), and draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.update_preview_object().
handle_move_arc()
def draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.handle_move_arc (self, edit_command, obj, node_idx)
Definition at line 386 of file gui_edit_draft_objects.py.
Referenced by draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.get_edit_point_context_menu().
handle_set_first_angle()
def draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.handle_set_first_angle (self, edit_command, obj, node_idx)
Definition at line 390 of file gui_edit_draft_objects.py.
Referenced by draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.get_edit_point_context_menu().
handle_set_last_angle()
def draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.handle_set_last_angle (self, edit_command, obj, node_idx)
Definition at line 394 of file gui_edit_draft_objects.py.
Referenced by draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.get_edit_point_context_menu().
handle_set_radius()
def draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.handle_set_radius (self, edit_command, obj, node_idx)
Definition at line 398 of file gui_edit_draft_objects.py.
Referenced by draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.get_edit_point_context_menu().
init_preview_object()
def draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.init_preview_object (self, obj)
Reimplemented from draftguitools.gui_edit_base_object.GuiTools.
Definition at line 411 of file gui_edit_draft_objects.py.
pointOnCircle()
def draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.pointOnCircle (self, obj, angle, global_placement = False)
Definition at line 485 of file gui_edit_draft_objects.py.
Referenced by draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.getArcEnd(), draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.getArcMid(), and draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.getArcStart().
update_object_from_edit_points()
def draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.update_object_from_edit_points (self, obj, node_idx, v, alt_edit_mode = 0)
Update the object from modified Draft_Edit point.
No need to recompute at the end.
Parameters:
obj: the object
node_idx: number of the edited node
v: target vector of the node in object local coordinates system
alt_edit_mode: alternative edit mode to perform different operations
       (usually can be selected from the Draft_Edit context menu)
       default = 0
Reimplemented from draftguitools.gui_edit_base_object.GuiTools.
Definition at line 302 of file gui_edit_draft_objects.py.
References DraftVecUtils.angle(), draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.getArcEnd(), draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.getArcMid(), draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.getArcStart(), and DraftVecUtils.project().
update_preview_object()
def draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.update_preview_object (self, edit_command, obj, node_idx, v)
Reimplemented from draftguitools.gui_edit_base_object.GuiTools.
Definition at line 414 of file gui_edit_draft_objects.py.
References draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.getArcEnd(), draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.getArcMid(), draftguitools.gui_edit_draft_objects.DraftCircleGuiTools.getArcStart(), and DraftVecUtils.project().
The documentation for this class was generated from the following file:
gui_edit_draft_objects.py