FreeCAD: App::ColorGradient Class Reference
App::ColorGradient Class Reference
#include <ColorModel.h>
Public Member Functions
ColorGradient ()
ColorGradient (float fMin, float fMax, std::size_t usCtColors, ColorBarStyle tS, VisibilityFlags fl=Visibility::Default)
ColorGradient (const ColorGradient &)=default
ColorGradient & operator= (const ColorGradient &)=default
const ColorGradientProfile & getProfile () const
void setProfile (const ColorGradientProfile &pro)
void set (float fMin, float fMax, std::size_t usCt, ColorBarStyle tS, VisibilityFlags fl)
void setRange (float fMin, float fMax)
void getRange (float &rfMin, float &rfMax) const
bool isOutOfRange (float fVal) const
std::size_t getCountColors () const
void setCountColors (std::size_t usCt)
void setStyle (ColorBarStyle tS)
std::size_t getMinColors () const
ColorBarStyle getStyle () const
void setOutsideGrayed (bool value)
bool isOutsideGrayed () const
void setOutsideInvisible (bool value)
bool isOutsideInvisible () const
void setColorModel (std::size_t tModel)
std::size_t getColorModelType () const
const ColorModel & getColorModel () const
std::vector< std::string > getColorModelNames () const
float getMinValue () const
float getMaxValue () const
Color getColor (float fVal) const
std::size_t getColorIndex (float fVal) const
Protected Member Functions
void createStandardPacks ()
void rebuild ()
void setColorModel ()
Protected Attributes
ColorGradientProfile profile
ColorField colorField1
ColorField colorField2
ColorModelPack currentModelPack
std::vector< ColorModelPack > modelPacks
Detailed Description
Definition at line 407 of file ColorModel.h.
Constructor & Destructor Documentation
ColorGradient() [1/3]
ColorGradient::ColorGradient ()
Definition at line 186 of file ColorModel.cpp.
References createStandardPacks(), App::Default, SCL.SimpleDataTypes::f, set(), setColorModel(), and App::ZERO_BASED.
ColorGradient() [2/3]
ColorGradient::ColorGradient (float fMin, float fMax, std::size_t usCtColors, ColorBarStyle tS, VisibilityFlags fl = Visibility::Default)
Definition at line 193 of file ColorModel.cpp.
References createStandardPacks(), set(), and setColorModel().
ColorGradient() [3/3]
App::ColorGradient::ColorGradient (const ColorGradient &) default
Member Function Documentation
createStandardPacks()
void ColorGradient::createStandardPacks () protected
Definition at line 204 of file ColorModel.cpp.
References App::ColorModelPack::createBlackWhite(), App::ColorModelPack::createBlueGreenRed(), App::ColorModelPack::createRedGreenBlue(), App::ColorModelPack::createRedWhiteBlue(), App::ColorModelPack::createWhiteBlack(), and modelPacks.
Referenced by ColorGradient().
getColor()
Color App::ColorGradient::getColor (float fVal) const inline
Definition at line 620 of file ColorModel.h.
References App::Color::a, isOutOfRange(), and isOutsideInvisible().
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::setValues().
getColorIndex()
std::size_t App::ColorGradient::getColorIndex (float fVal) const inline
Definition at line 662 of file ColorModel.h.
References colorField1, colorField2, SCL.SimpleDataTypes::f, App::FLOW, App::ColorGradientProfile::fMax, App::ColorGradientProfile::fMin, App::ColorField::getColorIndex(), App::ColorField::getCountColors(), profile, App::ColorGradientProfile::tStyle, and App::ZERO_BASED.
getColorModel()
const ColorModel & App::ColorGradient::getColorModel () const inline
Definition at line 687 of file ColorModel.h.
References App::ColorModelPack::bottomModel, currentModelPack, App::ColorGradientProfile::fMax, App::ColorGradientProfile::fMin, profile, App::ColorModelPack::topModel, App::ColorModelPack::totalModel, App::ColorGradientProfile::tStyle, and App::ZERO_BASED.
getColorModelNames()
std::vector< std::string > ColorGradient::getColorModelNames () const
Definition at line 213 of file ColorModel.cpp.
References modelPacks, and femtools.tokrules::names.
Referenced by Gui::Dialog::DlgSettingsColorGradientImp::DlgSettingsColorGradientImp().
getColorModelType()
std::size_t App::ColorGradient::getColorModelType () const inline
Definition at line 472 of file ColorModel.h.
getCountColors()
std::size_t App::ColorGradient::getCountColors () const inline
Definition at line 438 of file ColorModel.h.
Referenced by Gui::SoFCColorGradient::setRange().
getMaxValue()
float App::ColorGradient::getMaxValue () const inline
Definition at line 482 of file ColorModel.h.
getMinColors()
std::size_t ColorGradient::getMinColors () const
Definition at line 281 of file ColorModel.cpp.
References colorField1, colorField2, App::FLOW, App::ColorGradientProfile::fMax, App::ColorGradientProfile::fMin, App::ColorField::getMinColors(), profile, App::ColorGradientProfile::tStyle, and App::ZERO_BASED.
Referenced by set().
getMinValue()
float App::ColorGradient::getMinValue () const inline
Definition at line 478 of file ColorModel.h.
getProfile()
const ColorGradientProfile& App::ColorGradient::getProfile () const inline
Definition at line 418 of file ColorModel.h.
Referenced by Gui::SoFCColorGradient::customize(), Gui::Dialog::DlgSettingsColorGradientImp::DlgSettingsColorGradientImp(), and ArchPipe._ArchPipe::execute().
getRange()
void App::ColorGradient::getRange (float & rfMin, float & rfMax) const inline
Definition at line 429 of file ColorModel.h.
getStyle()
ColorBarStyle App::ColorGradient::getStyle () const inline
Definition at line 451 of file ColorModel.h.
isOutOfRange()
bool App::ColorGradient::isOutOfRange (float fVal) const inline
Definition at line 434 of file ColorModel.h.
Referenced by getColor(), and Gui::SoFCColorGradient::isVisible().
isOutsideGrayed()
bool App::ColorGradient::isOutsideGrayed () const inline
Definition at line 459 of file ColorModel.h.
References App::Grayed.
isOutsideInvisible()
bool App::ColorGradient::isOutsideInvisible () const inline
Definition at line 467 of file ColorModel.h.
References App::Invisible.
Referenced by getColor(), and Gui::SoFCColorGradient::isVisible().
operator=()
ColorGradient& App::ColorGradient::operator= (const ColorGradient &) default
rebuild()
void ColorGradient::rebuild () protected
Definition at line 249 of file ColorModel.cpp.
References App::ColorModelPack::bottomModel, colorField1, colorField2, App::ColorGradientProfile::ctColors, currentModelPack, App::FLOW, App::ColorGradientProfile::fMax, App::ColorGradientProfile::fMin, profile, App::ColorField::set(), App::ColorModelPack::topModel, App::ColorModelPack::totalModel, App::ColorGradientProfile::tStyle, and App::ZERO_BASED.
Referenced by set(), setColorModel(), and setProfile().
set()
void ColorGradient::set (float fMin, float fMax, std::size_t usCt, ColorBarStyle tS, VisibilityFlags fl)
Definition at line 230 of file ColorModel.cpp.
References App::ColorGradientProfile::ctColors, App::ColorGradientProfile::fMax, App::ColorGradientProfile::fMin, getMinColors(), profile, rebuild(), App::ColorGradientProfile::tStyle, and App::ColorGradientProfile::visibility.
Referenced by ColorGradient(), and draftguitools.gui_trackers.editTracker::move().
setColorModel() [1/2]
void ColorGradient::setColorModel () protected
Definition at line 305 of file ColorModel.cpp.
References App::ColorModelPack::bottomModel, colorField1, colorField2, currentModelPack, App::FLOW, modelPacks, profile, App::ColorField::setColorModel(), App::ColorGradientProfile::tColorModel, App::ColorModelPack::topModel, App::ColorModelPack::totalModel, App::ColorGradientProfile::tStyle, and App::ZERO_BASED.
Referenced by ColorGradient(), setColorModel(), and setProfile().
setColorModel() [2/2]
void ColorGradient::setColorModel (std::size_t tModel)
Definition at line 298 of file ColorModel.cpp.
References profile, rebuild(), setColorModel(), and App::ColorGradientProfile::tColorModel.
Referenced by Gui::SoFCColorGradient::setColorModel().
setCountColors()
void App::ColorGradient::setCountColors (std::size_t usCt) inline
Definition at line 442 of file ColorModel.h.
setOutsideGrayed()
void App::ColorGradient::setOutsideGrayed (bool value) inline
Definition at line 455 of file ColorModel.h.
References App::Grayed.
setOutsideInvisible()
void App::ColorGradient::setOutsideInvisible (bool value) inline
Definition at line 463 of file ColorModel.h.
References App::Invisible.
setProfile()
void ColorGradient::setProfile (const ColorGradientProfile & pro)
Definition at line 223 of file ColorModel.cpp.
References profile, rebuild(), and setColorModel().
Referenced by Gui::SoFCColorGradient::customize().
setRange()
void App::ColorGradient::setRange (float fMin, float fMax) inline
Definition at line 425 of file ColorModel.h.
Referenced by Gui::SoFCColorGradient::setRange().
setStyle()
void App::ColorGradient::setStyle (ColorBarStyle tS) inline
Definition at line 446 of file ColorModel.h.
Referenced by Gui::SoFCColorGradient::setColorStyle().
Member Data Documentation
colorField1
ColorField App::ColorGradient::colorField1 protected
Definition at line 498 of file ColorModel.h.
Referenced by getColorIndex(), getMinColors(), rebuild(), and setColorModel().
colorField2
ColorField App::ColorGradient::colorField2 protected
Definition at line 498 of file ColorModel.h.
Referenced by getColorIndex(), getMinColors(), rebuild(), and setColorModel().
currentModelPack
ColorModelPack App::ColorGradient::currentModelPack protected
Definition at line 499 of file ColorModel.h.
Referenced by getColorModel(), rebuild(), and setColorModel().
modelPacks
std::vector<ColorModelPack> App::ColorGradient::modelPacks protected
Definition at line 500 of file ColorModel.h.
Referenced by createStandardPacks(), getColorModelNames(), and setColorModel().
profile
ColorGradientProfile App::ColorGradient::profile protected
Definition at line 497 of file ColorModel.h.
Referenced by getColorIndex(), getColorModel(), getMinColors(), rebuild(), set(), setColorModel(), setProfile(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_general_pocket::wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_general_protrusion::wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_general_pocket::wr2(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_general_protrusion::wr2().
The documentation for this class was generated from the following files:
ColorModel.h
ColorModel.cpp