FreeCAD: SketcherGui::ViewProviderSketch::ToolManager Class Reference
SketcherGui::ViewProviderSketch::ToolManager Class Reference
#include <ViewProviderSketch.h>
Public Member Functions
ToolManager (ViewProviderSketch *vp)
std::unique_ptr< QWidget > createToolWidget () const
Factory function returning a tool widget of the type appropriate for the current active tool. If no tool is active, expect a nullptr.
bool isWidgetVisible () const
Returns whether the current tool's widget is intended to be visible for the user.
QPixmap getToolIcon () const
Returns the intended icon for a visible tool widget (e.g. for header/title).
QString getToolWidgetText () const
Returns the intended text for a visible tool widget (e.g. for header/title).
Detailed Description
Definition at line 471 of file ViewProviderSketch.h.
Constructor & Destructor Documentation
ToolManager()
ViewProviderSketch::ToolManager::ToolManager (ViewProviderSketch * vp) explicit
Definition at line 421 of file ViewProviderSketch.cpp.
Member Function Documentation
createToolWidget()
std::unique_ptr< QWidget > ViewProviderSketch::ToolManager::createToolWidget () const
Factory function returning a tool widget of the type appropriate for the current active tool. If no tool is active, expect a nullptr.
Definition at line 424 of file ViewProviderSketch.cpp.
Referenced by SketcherGui::TaskSketcherTool::toolChanged().
getToolIcon()
QPixmap ViewProviderSketch::ToolManager::getToolIcon () const
Returns the intended icon for a visible tool widget (e.g. for header/title).
Definition at line 444 of file ViewProviderSketch.cpp.
Referenced by SketcherGui::TaskSketcherTool::toolChanged().
getToolWidgetText()
QString ViewProviderSketch::ToolManager::getToolWidgetText () const
Returns the intended text for a visible tool widget (e.g. for header/title).
Definition at line 454 of file ViewProviderSketch.cpp.
Referenced by SketcherGui::TaskSketcherTool::toolChanged().
isWidgetVisible()
bool ViewProviderSketch::ToolManager::isWidgetVisible () const
Returns whether the current tool's widget is intended to be visible for the user.
Definition at line 434 of file ViewProviderSketch.cpp.
The documentation for this class was generated from the following files:
ViewProviderSketch.h
ViewProviderSketch.cpp