FreeCAD: Part::IGES::ImportExportSettings Class Reference
Part::IGES::ImportExportSettings Class Reference
#include <ImportExportSettings.h>
Public Member Functions
ImportExportSettings ()
bool getSkipBlankEntities () const
void setSkipBlankEntities (bool) const
bool getBRepMode () const
void setBRepMode (bool) const
Interface::Unit getUnit () const
void setUnit (Interface::Unit)
std::string getCompany () const
void setCompany (const char *)
std::string getAuthor () const
void setAuthor (const char *)
std::string getProductName () const
void setProductName (const char *)
Detailed Description
Definition at line 75 of file IGES/ImportExportSettings.h.
Constructor & Destructor Documentation
ImportExportSettings()
Part::IGES::ImportExportSettings::ImportExportSettings ()
Definition at line 75 of file IGES/ImportExportSettings.cpp.
Member Function Documentation
getAuthor()
std::string Part::IGES::ImportExportSettings::getAuthor () const
Definition at line 124 of file IGES/ImportExportSettings.cpp.
Referenced by PartGui::DlgImportExportIges::loadSettings().
getBRepMode()
bool Part::IGES::ImportExportSettings::getBRepMode () const
Definition at line 90 of file IGES/ImportExportSettings.cpp.
References ParameterGrp::SetASCII(), and Part::Interface::writeIgesHeaderAuthor().
Referenced by PartGui::DlgImportExportIges::loadSettings().
getCompany()
std::string Part::IGES::ImportExportSettings::getCompany () const
Definition at line 113 of file IGES/ImportExportSettings.cpp.
Referenced by PartGui::DlgImportExportIges::loadSettings().
getProductName()
std::string Part::IGES::ImportExportSettings::getProductName () const
Definition at line 135 of file IGES/ImportExportSettings.cpp.
Referenced by PartGui::DlgImportExportIges::loadSettings().
getSkipBlankEntities()
bool Part::IGES::ImportExportSettings::getSkipBlankEntities () const
Definition at line 80 of file IGES/ImportExportSettings.cpp.
Referenced by PartGui::DlgImportExportIges::loadSettings().
getUnit()
Interface::Unit Part::IGES::ImportExportSettings::getUnit () const
Definition at line 102 of file IGES/ImportExportSettings.cpp.
Referenced by PartGui::DlgImportExportIges::loadSettings().
setAuthor()
void Part::IGES::ImportExportSettings::setAuthor (const char * name)
Definition at line 129 of file IGES/ImportExportSettings.cpp.
Referenced by PartGui::DlgImportExportIges::saveSettings().
setBRepMode()
void Part::IGES::ImportExportSettings::setBRepMode (bool on) const
Definition at line 96 of file IGES/ImportExportSettings.cpp.
References Part::Interface::writeIgesHeaderProduct().
Referenced by PartGui::DlgImportExportIges::saveSettings().
setCompany()
void Part::IGES::ImportExportSettings::setCompany (const char * name)
Definition at line 118 of file IGES/ImportExportSettings.cpp.
Referenced by PartGui::DlgImportExportIges::saveSettings().
setProductName()
void Part::IGES::ImportExportSettings::setProductName (const char * name)
Definition at line 140 of file IGES/ImportExportSettings.cpp.
setSkipBlankEntities()
void Part::IGES::ImportExportSettings::setSkipBlankEntities (bool on) const
Definition at line 85 of file IGES/ImportExportSettings.cpp.
References ParameterGrp::GetASCII(), and Part::Interface::writeIgesHeaderAuthor().
Referenced by PartGui::DlgImportExportIges::saveSettings().
setUnit()
void Part::IGES::ImportExportSettings::setUnit (Interface::Unit unit)
Definition at line 107 of file IGES/ImportExportSettings.cpp.
Referenced by PartGui::DlgImportExportIges::saveSettings().
The documentation for this class was generated from the following files:
IGES/ImportExportSettings.h
IGES/ImportExportSettings.cpp