FreeCAD: ConvertFCMat Namespace Reference
ConvertFCMat Namespace Reference
Functions
def decode (name)
def read (filename)
def yamGeneral (card)
def yamSection (card, header, uuid)
def yamMechanical (card)
def yamFluid (card)
def yamThermal (card)
def yamElectromagnetic (card)
def yamArchitectural (card)
def yamCost (card)
def yamRendering (card)
def yamVectorRendering (card)
def saveYaml (card, output)
def convert (infolder, outfolder)
Variables
parser = argparse.ArgumentParser()
help
args = parser.parse_args()
Function Documentation
convert()
def ConvertFCMat.convert (infolder, outfolder)
Definition at line 264 of file ConvertFCMat.py.
References read(), and saveYaml().
decode()
def ConvertFCMat.decode (name)
Definition at line 34 of file ConvertFCMat.py.
read()
def ConvertFCMat.read (filename)
Definition at line 46 of file ConvertFCMat.py.
References AssemblyImport.open().
Referenced by convert().
saveYaml()
def ConvertFCMat.saveYaml (card, output)
Definition at line 230 of file ConvertFCMat.py.
References AssemblyImport.open(), yamArchitectural(), yamCost(), yamElectromagnetic(), yamFluid(), yamGeneral(), yamMechanical(), yamRendering(), yamThermal(), and yamVectorRendering().
Referenced by convert().
yamArchitectural()
def ConvertFCMat.yamArchitectural (card)
Definition at line 203 of file ConvertFCMat.py.
References yamSection().
Referenced by saveYaml().
yamCost()
def ConvertFCMat.yamCost (card)
Definition at line 206 of file ConvertFCMat.py.
References yamSection().
Referenced by saveYaml().
yamElectromagnetic()
def ConvertFCMat.yamElectromagnetic (card)
Definition at line 200 of file ConvertFCMat.py.
References yamSection().
Referenced by saveYaml().
yamFluid()
def ConvertFCMat.yamFluid (card)
Definition at line 189 of file ConvertFCMat.py.
References yamSection().
Referenced by saveYaml().
yamGeneral()
def ConvertFCMat.yamGeneral (card)
Definition at line 122 of file ConvertFCMat.py.
Referenced by saveYaml().
yamMechanical()
def ConvertFCMat.yamMechanical (card)
Definition at line 164 of file ConvertFCMat.py.
References yamSection().
Referenced by saveYaml().
yamRendering()
def ConvertFCMat.yamRendering (card)
Definition at line 209 of file ConvertFCMat.py.
References yamSection().
Referenced by saveYaml().
yamSection()
def ConvertFCMat.yamSection (card, header, uuid)
Definition at line 153 of file ConvertFCMat.py.
Referenced by yamArchitectural(), yamCost(), yamElectromagnetic(), yamFluid(), yamMechanical(), yamRendering(), yamThermal(), and yamVectorRendering().
yamThermal()
def ConvertFCMat.yamThermal (card)
Definition at line 197 of file ConvertFCMat.py.
References yamSection().
Referenced by saveYaml().
yamVectorRendering()
def ConvertFCMat.yamVectorRendering (card)
Definition at line 227 of file ConvertFCMat.py.
References yamSection().
Referenced by saveYaml().
Variable Documentation
args
ConvertFCMat.args = parser.parse_args()
Definition at line 287 of file ConvertFCMat.py.
help
ConvertFCMat.help
Definition at line 285 of file ConvertFCMat.py.
parser
ConvertFCMat.parser = argparse.ArgumentParser()
Definition at line 284 of file ConvertFCMat.py.