FreeCAD: femsolver.settings Namespace Reference
femsolver.settings Namespace Reference
Classes
class _SolverDlg
class DirSetting
Functions
def get_binary (name, silent=False)
def get_cores (name)
def get_write_comments (name)
def get_custom_dir ()
def get_dir_setting ()
def get_default_solver ()
Variables
string default = "ccx",
string param_path = _PARAM_PATH + "Ccx",
string use_default = "UseStandardCcxLocation",
string custom_path = "ccxBinaryPath",
Function Documentation
get_binary()
def femsolver.settings.get_binary (name, silent = False)
Find binary of solver *name* honoring user settings.
Return the specific path set by the user in FreeCADs settings/parameter
system if set or the default binary name if no specific path is set. If no
path was found because the solver *name* is not supported ``None`` is
returned.
This method does not check whether the binary actually exists and is callable.
That check is done in DlgSettingsFem_Solver_Imp.cpp
:param name: solver id as a ``str`` (see :mod:`femsolver.settings`)
:param silent: whether to output error if binary not found
Definition at line 85 of file settings.py.
Referenced by femsolver.settings.get_default_solver().
get_cores()
def femsolver.settings.get_cores (name)
Read number of CPU cores for solver *name* honoring user settings.
Returns number of CPU cores to be used for the solver run
:param name: solver id as a ``str`` (see :mod:`femsolver.settings`)
Definition at line 110 of file settings.py.
get_custom_dir()
def femsolver.settings.get_custom_dir ()
Get value for :term:`General/CustomDirectoryPath` parameter.
Definition at line 147 of file settings.py.
get_default_solver()
def femsolver.settings.get_default_solver ()
Return default solver name.
Definition at line 169 of file settings.py.
References femsolver.settings.get_binary().
Referenced by femcommands.commands._Analysis.Activated().
get_dir_setting()
def femsolver.settings.get_dir_setting ()
Return directory setting set by the user.
Return one of the three possible values of the :class:`DirSetting` enum
depending on the setting set in FreeCAD parameter system. Result dependes
on the values of :term:`General/UseTempDirectory`,
:term:`General/UseBesideDirectory` and :term:`General/UseCustomDirectory`.
Definition at line 153 of file settings.py.
get_write_comments()
def femsolver.settings.get_write_comments (name)
Check whether "write_comments" is set for solver.
Returns ``True`` if the "write_comments" setting/parameter is set for the
solver with the id *name*. Returns ``False`` otherwise. If the solver is
not supported ``None`` is returned.
:param name: solver id as a ``str`` (see :mod:`femsolver.settings`)
Definition at line 128 of file settings.py.
Variable Documentation
custom_path
string femsolver.settings.custom_path = "ccxBinaryPath",
Definition at line 268 of file settings.py.
default
string femsolver.settings.default = "ccx",
Definition at line 265 of file settings.py.
param_path
string femsolver.settings.param_path = _PARAM_PATH + "Ccx",
Definition at line 266 of file settings.py.
use_default
string femsolver.settings.use_default = "UseStandardCcxLocation",
Definition at line 267 of file settings.py.