FreeCAD: MillSim::TextureLoader Class Reference
MillSim::TextureLoader Class Reference
#include <TextureLoader.h>
Public Member Functions
TextureLoader (std::string imgFolder, std::vector< std::string > fileNames, int textureSize)
~TextureLoader ()
unsigned int * GetRawData ()
TextureItem * GetTextureItem (int i)
Protected Member Functions
bool AddImage (TextureItem *guiItem, QImage &pixmap, unsigned int *buffPos, int stride)
Protected Attributes
unsigned int * mRawData = nullptr
std::string mImageFolder
Detailed Description
Definition at line 58 of file TextureLoader.h.
Constructor & Destructor Documentation
TextureLoader()
TextureLoader::TextureLoader (std::string imgFolder, std::vector< std::string > fileNames, int textureSize)
Definition at line 49 of file TextureLoader.cpp.
References AddImage(), SplineSurface::i, mRawData, and texItems.
~TextureLoader()
MillSim::TextureLoader::~TextureLoader ()
Definition at line 87 of file TextureLoader.cpp.
References GCS::free().
Member Function Documentation
AddImage()
bool TextureLoader::AddImage (TextureItem * guiItem, QImage & pixmap, unsigned int * buffPos, int stride) protected
Definition at line 67 of file TextureLoader.cpp.
References MillSim::TextureItem::h, SplineSurface::i, MillSim::TextureItem::tx, MillSim::TextureItem::ty, and MillSim::TextureItem::w.
Referenced by TextureLoader().
GetRawData()
unsigned int * MillSim::TextureLoader::GetRawData ()
Definition at line 94 of file TextureLoader.cpp.
Referenced by MillSim::GuiDisplay::InitGui().
GetTextureItem()
TextureItem * MillSim::TextureLoader::GetTextureItem (int i)
Definition at line 99 of file TextureLoader.cpp.
References SplineSurface::i, and texItems.
Referenced by MillSim::GuiDisplay::InitGui().
Member Data Documentation
mImageFolder
std::string MillSim::TextureLoader::mImageFolder protected
Definition at line 71 of file TextureLoader.h.
mRawData
unsigned int* MillSim::TextureLoader::mRawData = nullptr protected
Definition at line 70 of file TextureLoader.h.
Referenced by TextureLoader().
The documentation for this class was generated from the following files:
TextureLoader.h
TextureLoader.cpp