FreeCAD: Gui::Dialog::AboutDialog Class Reference
Gui::Dialog::AboutDialog Class Reference
#include <DlgAbout.h>
Public Member Functions
AboutDialog (QWidget *parent=nullptr)
~AboutDialog () override
Protected Member Functions
void setupLabels ()
void showCredits ()
void showLicenseInformation ()
QString getAdditionalLicenseInformation () const
void showLibraryInformation ()
void showCollectionInformation ()
void showPrivacyPolicy ()
void showOrHideImage (const QRect &rect)
void addModuleInfo (QTextStream &inout_str, const QString &modPath, bool &inout_first)
QPixmap aboutImage () const
virtual void copyToClipboard ()
void linkActivated (const QUrl &link)
Detailed Description
This widget provides the "About dialog" of an application. This shows the current version, the build number and date.
Author
Werner Mayer
Definition at line 115 of file DlgAbout.h.
Constructor & Destructor Documentation
AboutDialog()
AboutDialog::AboutDialog (QWidget * parent = nullptr) explicit
Constructs an AboutDialog which is a child of 'parent', with the name 'name' and widget flags set to 'WStyle_Customize|WStyle_NoBorder|WType_Modal'
The dialog will be modal.
Definition at line 155 of file DlgAbout.cpp.
References aboutImage(), draftgeoutils.intersections::connect(), copyToClipboard(), KDL::min(), setupLabels(), showCollectionInformation(), showCredits(), showLibraryInformation(), showLicenseInformation(), showOrHideImage(), showPrivacyPolicy(), and Gui::SplashScreen::splashImage().
~AboutDialog()
AboutDialog::~AboutDialog () override
Destroys the object and frees any allocated resources
Definition at line 203 of file DlgAbout.cpp.
Member Function Documentation
aboutImage()
QPixmap AboutDialog::aboutImage () const protected
Definition at line 209 of file DlgAbout.cpp.
References Gui::BitmapFactory(), App::Application::Config(), App::Application::getHomePath(), Path.Post.scripts.rml_post::home(), src.Mod.Test.testPathArray::path, and Gui::BitmapFactoryInst::pixmap().
Referenced by AboutDialog().
addModuleInfo()
void AboutDialog::addModuleInfo (QTextStream & inout_str, const QString & modPath, bool & inout_first) protected
Definition at line 537 of file DlgAbout.cpp.
References SCL.SimpleDataTypes::e, mod, src.Mod.Test.testPathArray::path, Path.Post.scripts.refactored_centroid_post::str, App::Meta::Version::str(), and App::Metadata::version().
Referenced by copyToClipboard().
copyToClipboard()
void AboutDialog::copyToClipboard () protected virtual
Definition at line 571 of file DlgAbout.cpp.
References addModuleInfo(), App::Application::Config(), App::GetApplication(), ParameterGrp::GetASCII(), App::Application::getExecutableName(), App::Application::GetParameterGroupByPath(), App::Application::getUserAppDataDir(), mod, src.Mod.Test.testPathArray::path, prettyProductInfoWrapper(), and Path.Post.scripts.refactored_centroid_post::str.
Referenced by AboutDialog().
getAdditionalLicenseInformation()
QString AboutDialog::getAdditionalLicenseInformation () const protected
Definition at line 445 of file DlgAbout.cpp.
References Path.Log::info().
Referenced by showLicenseInformation().
linkActivated()
void AboutDialog::linkActivated (const QUrl & link) protected
Definition at line 521 of file DlgAbout.cpp.
References Gui::MainWindow::addWindow(), Gui::getMainWindow(), and Plot::title().
setupLabels()
void AboutDialog::setupLabels () protected
Definition at line 244 of file DlgAbout.cpp.
References App::Application::Config(), prettyProductInfoWrapper(), and Dice3DS::version.
Referenced by AboutDialog().
showCollectionInformation()
void AboutDialog::showCollectionInformation () protected
Definition at line 478 of file DlgAbout.cpp.
References toolbit-attributes::doc, App::Application::getHelpDir(), and src.Mod.Test.testPathArray::path.
Referenced by AboutDialog().
showCredits()
void AboutDialog::showCredits () protected
Definition at line 358 of file DlgAbout.cpp.
Referenced by AboutDialog().
showLibraryInformation()
void AboutDialog::showLibraryInformation () protected
Definition at line 461 of file DlgAbout.cpp.
References App::Application::getHelpDir().
Referenced by AboutDialog().
showLicenseInformation()
void AboutDialog::showLicenseInformation () protected
Definition at line 411 of file DlgAbout.cpp.
References getAdditionalLicenseInformation(), App::Application::getHelpDir(), Path.Log::info(), and importCSG::placeholder().
Referenced by AboutDialog().
showOrHideImage()
void AboutDialog::showOrHideImage (const QRect & rect) protected
Definition at line 236 of file DlgAbout.cpp.
Referenced by AboutDialog().
showPrivacyPolicy()
void AboutDialog::showPrivacyPolicy () protected
Definition at line 496 of file DlgAbout.cpp.
Referenced by AboutDialog().
The documentation for this class was generated from the following files:
DlgAbout.h
DlgAbout.cpp