FreeCAD: Gui::PythonTracing Class Reference
Gui::PythonTracing Class Reference
#include <PythonTracing.h>
Classes
struct Private
Public Member Functions
PythonTracing ()
~PythonTracing ()
PythonTracing (const PythonTracing &)=delete
PythonTracing (PythonTracing &&)=delete
PythonTracing & operator= (const PythonTracing &)=delete
PythonTracing & operator= (PythonTracing &&)=delete
bool isActive () const
isActive Returns true if the tracing is active, false otherwise.
void activate ()
activate Activates the Python tracing.
void deactivate ()
deactivate Deactivates the Python tracing.
void fetchFromSettings ()
fetchFromSettings Fetch parameters from user settings.
bool interrupt () const
interrupt If the tracing is enabled it interrupts the Python interpreter. True is returned if the tracing is active, false otherwise.
void setTimeout (int ms)
setTimeout Sets the interval after which the Qt event loop will be processed.
int timeout () const
timeout
Detailed Description
Definition at line 55 of file PythonTracing.h.
Constructor & Destructor Documentation
PythonTracing() [1/3]
PythonTracing::PythonTracing ()
Definition at line 59 of file PythonTracing.cpp.
~PythonTracing()
PythonTracing::~PythonTracing () default
PythonTracing() [2/3]
Gui::PythonTracing::PythonTracing (const PythonTracing &) delete
PythonTracing() [3/3]
Gui::PythonTracing::PythonTracing (PythonTracing &&) delete
Member Function Documentation
activate()
void PythonTracing::activate ()
activate Activates the Python tracing.
Definition at line 71 of file PythonTracing.cpp.
Referenced by ArchBuildingPart.ViewProviderBuildingPart::setEdit(), nativeifc.ifc_viewproviders.ifc_vp_object::setupContextMenu(), and ArchBuildingPart.ViewProviderBuildingPart::setupContextMenu().
deactivate()
void PythonTracing::deactivate ()
deactivate Deactivates the Python tracing.
Definition at line 77 of file PythonTracing.cpp.
Referenced by CommandCreateBom.TaskAssemblyCreateBom::accept(), CommandInsertNewPart.TaskAssemblyNewPart::accept(), CommandCreateView.TaskAssemblyCreateView::accept(), CommandCreateSimulation.TaskAssemblyCreateSimulation::accept(), JointObject.TaskAssemblyCreateJoint::accept(), CommandCreateBom.TaskAssemblyCreateBom::reject(), CommandCreateView.TaskAssemblyCreateView::reject(), CommandCreateSimulation.TaskAssemblyCreateSimulation::reject(), and JointObject.TaskAssemblyCreateJoint::reject().
fetchFromSettings()
void PythonTracing::fetchFromSettings ()
fetchFromSettings Fetch parameters from user settings.
Definition at line 83 of file PythonTracing.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and setTimeout().
Referenced by Gui::PythonTracingWatcher::getTrace().
interrupt()
bool PythonTracing::interrupt () const
interrupt If the tracing is enabled it interrupts the Python interpreter. True is returned if the tracing is active, false otherwise.
Definition at line 93 of file PythonTracing.cpp.
References isActive().
Referenced by Gui::InteractiveInterpreter::interrupt().
isActive()
bool PythonTracing::isActive () const
isActive Returns true if the tracing is active, false otherwise.
Returns
Definition at line 66 of file PythonTracing.cpp.
Referenced by interrupt(), and Gui::InteractiveInterpreter::isOccupied().
operator=() [1/2]
PythonTracing& Gui::PythonTracing::operator= (const PythonTracing &) delete
operator=() [2/2]
PythonTracing& Gui::PythonTracing::operator= (PythonTracing &&) delete
setTimeout()
void PythonTracing::setTimeout (int ms)
setTimeout Sets the interval after which the Qt event loop will be processed.
Definition at line 103 of file PythonTracing.cpp.
Referenced by fetchFromSettings().
timeout()
int PythonTracing::timeout () const
timeout
Returns
the timeout of processing the event loop.
Definition at line 108 of file PythonTracing.cpp.
The documentation for this class was generated from the following files:
PythonTracing.h
PythonTracing.cpp