FreeCAD: Base::UnitsSchemaCentimeters Class Reference
Base::UnitsSchemaCentimeters Class Reference
#include <UnitsSchemaCentimeters.h>
Public Member Functions
std::string schemaTranslate (const Base::Quantity &quant, double &factor, std::string &unitString) override
This method translates the quantity in a string as the user may expect it.
std::string getBasicLengthUnit () const override
Public Member Functions inherited from Base::UnitsSchema
UnitsSchema ()=default
UnitsSchema (const UnitsSchema &)=default
UnitsSchema (UnitsSchema &&)=default
UnitsSchema & operator= (const UnitsSchema &)=default
UnitsSchema & operator= (UnitsSchema &&)=default
virtual ~UnitsSchema ()=default
virtual void setSchemaUnits ()
virtual void resetSchemaUnits ()
If you use setSchemaUnits() you also have to impment this method to undo your changes!
std::string toLocale (const Base::Quantity &quant, double factor, const std::string &unitString) const
virtual bool isMultiUnitLength () const
virtual bool isMultiUnitAngle () const
Detailed Description
The UnitSchema class
Definition at line 54 of file UnitsSchemaCentimeters.h.
Member Function Documentation
getBasicLengthUnit()
std::string Base::UnitsSchemaCentimeters::getBasicLengthUnit () const inline override virtual
Reimplemented from Base::UnitsSchema.
Definition at line 80 of file UnitsSchemaCentimeters.h.
schemaTranslate()
std::string UnitsSchemaCentimeters::schemaTranslate (const Base::Quantity & quant, double & factor, std::string & unitString) override virtual
This method translates the quantity in a string as the user may expect it.
Implements Base::UnitsSchema.
Definition at line 35 of file UnitsSchemaCentimeters.cpp.
References Base::Unit::Area, Base::Unit::ElectricPotential, Base::Unit::getString(), Base::Quantity::getUnit(), Base::Unit::HeatFlux, Base::Unit::Length, Base::Unit::Power, Base::UnitsSchema::toLocale(), unit(), Base::Unit::Velocity, and Base::Unit::Volume.
The documentation for this class was generated from the following files:
UnitsSchemaCentimeters.h
UnitsSchemaCentimeters.cpp