FreeCAD: geoff_geometry::CLine Class Reference
geoff_geometry::CLine Class Reference
#include <geometry.h>
Public Member Functions
CLine ()
CLine (const Point &p0, double dx, double dy, bool normalise=true)
CLine (const Point &p0, const Vector2d &v0, bool normalise=true)
CLine (const Point &p0, const Point &p1)
CLine (const Span &sp)
const CLine operator~ (void)
const CLine & operator= (const Point &p0)
double c ()
void Normalise ()
CLine Transform (Matrix &m)
Point Intof (const CLine &s)
Point Intof (int NF, const Circle &c)
Point Intof (int NF, const Circle &c, Point &otherInters)
double Dist (const Point &p1) const
CLine Bisector (const CLine &s)
Public Attributes
bool ok
Point p
Vector2d v
Friends
wostream & operator<< (wostream &op, CLine &cl)
Detailed Description
Definition at line 780 of file geometry.h.
Constructor & Destructor Documentation
CLine() [1/5]
geoff_geometry::CLine::CLine () inline
Definition at line 790 of file geometry.h.
Referenced by Bisector(), operator~(), and Transform().
CLine() [2/5]
geoff_geometry::CLine::CLine (const Point & p0, double dx, double dy, bool normalise = true) inline
Definition at line 794 of file geometry.h.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf::normalise(), buildPsets::p, and TestSpreadsheet::v.
CLine() [3/5]
geoff_geometry::CLine::CLine (const Point & p0, const Vector2d & v0, bool normalise = true) inline
Definition at line 802 of file geometry.h.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf::normalise(), buildPsets::p, and TestSpreadsheet::v.
CLine() [4/5]
geoff_geometry::CLine::CLine (const Point & p0, const Point & p1) inline
Definition at line 816 of file geometry.h.
References buildPsets::p, and TestSpreadsheet::v.
CLine() [5/5]
geoff_geometry::CLine::CLine (const Span & sp)
Definition at line 297 of file Construction.cpp.
References geoff_geometry::Span::NullSpan, ok, p, geoff_geometry::Span::p0, geoff_geometry::Span::returnSpanProperties, v, and geoff_geometry::Span::vs.
Member Function Documentation
Bisector()
CLine geoff_geometry::CLine::Bisector (const CLine & s)
Definition at line 424 of file Construction.cpp.
References CLine(), geoff_geometry::Vector2d::getx(), Intof(), toolbit-attributes::s, and v.
c()
double geoff_geometry::CLine::c ()
Definition at line 286 of file Construction.cpp.
References geoff_geometry::Vector2d::getx(), geoff_geometry::Vector2d::gety(), p, v, geoff_geometry::Point::x, and geoff_geometry::Point::y.
Referenced by Intof(), and geoff_geometry::Tanto().
Dist()
double geoff_geometry::CLine::Dist (const Point & p1) const
Definition at line 328 of file Construction.cpp.
References p, and v.
Referenced by geoff_geometry::OnSpan(), geoff_geometry::Span::OnSpan(), geoff_geometry::Kurve::Reduce(), and geoff_geometry::Tanto().
Intof() [1/3]
Point geoff_geometry::CLine::Intof (const CLine & s)
Definition at line 340 of file Construction.cpp.
References geoff_geometry::Intof(), and toolbit-attributes::s.
Referenced by Bisector(), and geoff_geometry::Span::JoinSeparateSpans().
Intof() [2/3]
Point geoff_geometry::CLine::Intof (int NF, const Circle & c)
Definition at line 346 of file Construction.cpp.
References c(), and geoff_geometry::Intof().
Intof() [3/3]
Point geoff_geometry::CLine::Intof (int NF, const Circle & c, Point & otherInters)
Definition at line 351 of file Construction.cpp.
References c(), and geoff_geometry::Intof().
Normalise()
void geoff_geometry::CLine::Normalise ()
Definition at line 291 of file Construction.cpp.
References geoff_geometry::Vector2d::normalise(), ok, geoff_geometry::TOLERANCE, and v.
operator=()
const CLine& geoff_geometry::CLine::operator= (const Point & p0) inline
Definition at line 826 of file geometry.h.
References buildPsets::p, geoff_geometry::Point::x, and geoff_geometry::Point::y.
operator~()
const CLine geoff_geometry::CLine::operator~ (void)
Definition at line 309 of file Construction.cpp.
References CLine(), p, and v.
Transform()
CLine geoff_geometry::CLine::Transform (Matrix & m)
Definition at line 319 of file Construction.cpp.
References CLine(), geoff_geometry::Vector2d::getx(), geoff_geometry::Vector2d::gety(), test::m, p, geoff_geometry::Point::Transform(), v, geoff_geometry::Point::x, and geoff_geometry::Point::y.
Friends And Related Function Documentation
operator<<
wostream& operator<< (wostream & op, CLine & cl) friend
Definition at line 86 of file Construction.cpp.
Member Data Documentation
ok
bool geoff_geometry::CLine::ok
Definition at line 785 of file geometry.h.
Referenced by geoff_geometry::Around(), CLine(), geoff_geometry::Mid(), Normalise(), geoff_geometry::operator<<(), geoff_geometry::Kurve::Reduce(), and geoff_geometry::Thro().
p
Point geoff_geometry::CLine::p
Definition at line 786 of file geometry.h.
Referenced by c(), CLine(), geoff_geometry::Point::Dist(), Dist(), geoff_geometry::Intof(), geoff_geometry::operator<<(), operator~(), geoff_geometry::Parallel(), and Transform().
v
Vector2d geoff_geometry::CLine::v
Definition at line 787 of file geometry.h.
Referenced by WorkingPlane.PlaneBase::__repr__(), WorkingPlane.PlaneBase::align_to_edge_or_wire(), WorkingPlane.PlaneBase::align_to_face(), WorkingPlane.PlaneBase::align_to_placement(), WorkingPlane.PlaneBase::align_to_point_and_axis(), WorkingPlane.PlaneBase::align_to_point_and_axis_svg(), WorkingPlane.PlaneGui::align_view(), geoff_geometry::Around(), Bisector(), c(), CLine(), geoff_geometry::Point::Dist(), Dist(), WorkingPlane.PlaneBase::get_global_coords(), WorkingPlane.PlaneBase::get_local_coords(), WorkingPlane.PlaneBase::get_placement(), draftguitools.gui_trackers.rectangleTracker::getNormal(), WorkingPlane.Plane::getRotation(), draftguitools.gui_trackers.rectangleTracker::getSize(), geoff_geometry::IncludedAngle(), geoff_geometry::Intof(), WorkingPlane.PlaneBase::is_global(), WorkingPlane.PlaneBase::is_ortho(), geoff_geometry::Mid(), Normalise(), geoff_geometry::operator<<(), operator~(), geoff_geometry::Parallel(), WorkingPlane.Plane::restore(), WorkingPlane.Plane::save(), WorkingPlane.PlaneBase::set_to_front(), WorkingPlane.PlaneBase::set_to_side(), WorkingPlane.PlaneBase::set_to_top(), WorkingPlane.PlaneGui::set_to_view(), draftguitools.gui_trackers.rectangleTracker::setPlane(), geoff_geometry::Tanto(), Transform(), and draftguitools.gui_trackers.rectangleTracker::update().
The documentation for this class was generated from the following files:
geometry.h
Construction.cpp