FreeCAD: Gui::AlignmentGroup Class Reference
Gui::AlignmentGroup Class Reference
#include <ManualAlignment.h>
Public Member Functions
void addView (App::DocumentObject *)
std::vector< App::DocumentObject * > getViews () const
bool hasView (Gui::ViewProviderDocumentObject *) const
void removeView (Gui::ViewProviderDocumentObject *)
void addToViewer (Gui::View3DInventorViewer *) const
void removeFromViewer (Gui::View3DInventorViewer *) const
void setRandomColor ()
Gui::Document * getDocument () const
void addPoint (const PickedPoint &)
void removeLastPoint ()
int countPoints () const
const std::vector< PickedPoint > & getPoints () const
void clearPoints ()
void setAlignable (bool)
void moveTo (AlignmentGroup &)
void clear ()
bool isEmpty () const
int count () const
Base::BoundBox3d getBoundingBox () const
Protected Member Functions
AlignmentGroup ()
~AlignmentGroup ()
Protected Attributes
std::vector< PickedPoint > _pickedPoints
std::vector< Gui::ViewProviderDocumentObject * > _views
Detailed Description
The AlignemntGroup class is the base for fixed and movable groups.
Author
Werner Mayer
Definition at line 55 of file ManualAlignment.h.
Constructor & Destructor Documentation
AlignmentGroup()
AlignmentGroup::AlignmentGroup () protected default
~AlignmentGroup()
AlignmentGroup::~AlignmentGroup () protected default
Member Function Documentation
addPoint()
void AlignmentGroup::addPoint (const PickedPoint & pnt)
Add a point to an array of picked points.
Definition at line 168 of file ManualAlignment.cpp.
References _pickedPoints.
Referenced by draftguitools.gui_stretch.Stretch::action(), Gui::ManualAlignment::applyPickedProbe(), and draftguitools.gui_stretch.Stretch::numericInput().
addToViewer()
void AlignmentGroup::addToViewer (Gui::View3DInventorViewer * viewer) const
Add the group and therefore all its added view providers to the Inventor tree.
Definition at line 116 of file ManualAlignment.cpp.
References _views, and OfflineRenderingUtils::viewer().
Referenced by Gui::ManualAlignment::align(), and Gui::ManualAlignment::startAlignment().
addView()
void AlignmentGroup::addView (App::DocumentObject * pView)
Add a mesh to the group.
Definition at line 70 of file ManualAlignment.cpp.
References _views, Gui::Application::getDocument(), Gui::Document::getViewProvider(), Gui::Application::Instance, and NavigationIndicatorGui::pView.
Referenced by StdCmdAlignment::activated().
clear()
void AlignmentGroup::clear ()
Clear the list of added views.
Definition at line 221 of file ManualAlignment.cpp.
References _pickedPoints, and _views.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__(), Gui::ManualAlignment::clearAll(), Gui::ManualAlignment::onClear(), and Gui::ManualAlignment::reset().
clearPoints()
void AlignmentGroup::clearPoints ()
Clear all picked points.
Definition at line 188 of file ManualAlignment.cpp.
References _pickedPoints.
Referenced by Gui::ManualAlignment::continueAlignment().
count()
int AlignmentGroup::count () const
Return the number of added views.
Definition at line 232 of file ManualAlignment.cpp.
References _views.
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::set_status_filter().
countPoints()
int AlignmentGroup::countPoints () const
Count the number of picked points.
Definition at line 178 of file ManualAlignment.cpp.
References _pickedPoints.
Referenced by Gui::ManualAlignment::align(), Gui::ManualAlignment::applyPickedProbe(), Gui::ManualAlignment::canAlign(), Gui::ManualAlignment::onRemoveLastPointFixed(), Gui::ManualAlignment::onRemoveLastPointMoveable(), and Gui::ManualAlignment::showInstructions().
getBoundingBox()
Base::BoundBox3d AlignmentGroup::getBoundingBox () const
Get the overall bounding box of all views.
Definition at line 237 of file ManualAlignment.cpp.
References _views, MengerSponge::box, and Base::Persistence::getClassTypeId().
getDocument()
Gui::Document * AlignmentGroup::getDocument () const
Returns the document of the added views.
Definition at line 154 of file ManualAlignment.cpp.
References _views, Gui::Application::getDocument(), Gui::Application::Instance, and NavigationIndicatorGui::pView.
Referenced by Gui::ManualAlignment::setFixedGroup().
getPoints()
const std::vector< PickedPoint > & AlignmentGroup::getPoints () const
Return an array of picked points.
Definition at line 183 of file ManualAlignment.cpp.
References _pickedPoints.
Referenced by Gui::ManualAlignment::align().
getViews()
std::vector< App::DocumentObject * > AlignmentGroup::getViews () const
Definition at line 81 of file ManualAlignment.cpp.
References _views, and NavigationIndicatorGui::pView.
Referenced by Gui::ManualAlignment::align(), and bimcommands.BimViews.BIM_Views::update().
hasView()
bool AlignmentGroup::hasView (Gui::ViewProviderDocumentObject * pView) const
Checks for the view provider of one of the added views.
Definition at line 94 of file ManualAlignment.cpp.
References _views, and NavigationIndicatorGui::pView.
Referenced by Gui::ManualAlignment::applyPickedProbe(), and Gui::ManualAlignment::slotDeletedObject().
isEmpty()
bool AlignmentGroup::isEmpty () const
Checks whether the list of added views is empty or not.
Definition at line 227 of file ManualAlignment.cpp.
References _views.
Referenced by Gui::ManualAlignment::startAlignment().
moveTo()
void AlignmentGroup::moveTo (AlignmentGroup & that)
Definition at line 212 of file ManualAlignment.cpp.
References _views.
Referenced by Gui::ManualAlignment::align(), Path.Dressup.Gui.Dogbone.Chord::moveBy(), and Path.Dressup.Gui.Dogbone.Chord::moveToParameters().
removeFromViewer()
void AlignmentGroup::removeFromViewer (Gui::View3DInventorViewer * viewer) const
Remove all the view providers from the Inventor tree.
Definition at line 125 of file ManualAlignment.cpp.
References _views, and OfflineRenderingUtils::viewer().
Referenced by Gui::ManualAlignment::align().
removeLastPoint()
void AlignmentGroup::removeLastPoint ()
Remove last point from array of picked points.
Definition at line 173 of file ManualAlignment.cpp.
References _pickedPoints.
Referenced by Gui::ManualAlignment::onRemoveLastPointFixed(), and Gui::ManualAlignment::onRemoveLastPointMoveable().
removeView()
void AlignmentGroup::removeView (Gui::ViewProviderDocumentObject * pView)
Remove a previously added view by its view provider.
Definition at line 105 of file ManualAlignment.cpp.
References _views, and NavigationIndicatorGui::pView.
setAlignable()
void AlignmentGroup::setAlignable (bool align)
Set or unset the alignable mode for the added views. If a view is not alignable it also not pickable.
Definition at line 193 of file ManualAlignment.cpp.
References _views, App::PropertyBool::setValue(), and App::Property::touch().
Referenced by Gui::ManualAlignment::align(), Gui::ManualAlignment::reset(), and Gui::ManualAlignment::startAlignment().
setRandomColor()
void AlignmentGroup::setRandomColor ()
Definition at line 132 of file ManualAlignment.cpp.
References _views, SCL.SimpleDataTypes::b, toolbit-attributes::g, and Base::Persistence::getClassTypeId().
Member Data Documentation
_pickedPoints
std::vector<PickedPoint> Gui::AlignmentGroup::_pickedPoints protected
Definition at line 131 of file ManualAlignment.h.
Referenced by addPoint(), clear(), clearPoints(), countPoints(), getPoints(), and removeLastPoint().
_views
std::vector<Gui::ViewProviderDocumentObject*> Gui::AlignmentGroup::_views protected
Definition at line 132 of file ManualAlignment.h.
Referenced by addToViewer(), addView(), clear(), count(), getBoundingBox(), getDocument(), getViews(), hasView(), isEmpty(), moveTo(), removeFromViewer(), removeView(), setAlignable(), and setRandomColor().
The documentation for this class was generated from the following files:
ManualAlignment.h
ManualAlignment.cpp