FreeCAD: exportDRAWEXE Namespace Reference
exportDRAWEXE Namespace Reference
Classes
class Drawexporter
Functions
def quaternionToString (rot)
def f2s (n, angle=False, axis=False)
def ax2_xdir (normal)
def occversiontuple ()
def polygonstr (r, pcount)
def formatobjtype (ob)
def placement2draw (placement, name='object')
def saveShape (csg, filename, shape, name, hasplacement=True, cleanshape=False)
def isDraftFeature (ob)
def isDraftClone (ob)
def isDraftCircle (ob)
def isDraftEllipse (ob)
def isDraftPolygon (ob)
def isDraftPoint (ob)
def isDraftWire (ob)
def isDraftShape2DView (ob)
def isOpenSCADFeature (ob)
def isOpenSCADMultMatrixFeature (ob)
def isDeform (ob)
def export (exportList, filename)
Function Documentation
ax2_xdir()
def exportDRAWEXE.ax2_xdir (normal)
Definition at line 63 of file exportDRAWEXE.py.
References KDL.abs().
Referenced by exportDRAWEXE.Drawexporter.process_object().
export()
def exportDRAWEXE.export (exportList, filename)
Definition at line 847 of file exportDRAWEXE.py.
f2s()
def exportDRAWEXE.f2s (n, angle = False, axis = False)
convert to numerical value to string
try to remove no significant digits, by guessing a former rounding
Definition at line 44 of file exportDRAWEXE.py.
References KDL.abs().
Referenced by exportDRAWEXE.Drawexporter.export_annotations(), placement2draw(), polygonstr(), and exportDRAWEXE.Drawexporter.process_object().
formatobjtype()
def exportDRAWEXE.formatobjtype (ob)
Definition at line 103 of file exportDRAWEXE.py.
Referenced by exportDRAWEXE.Drawexporter.process_object().
isDeform()
def exportDRAWEXE.isDeform (ob)
tests whether the object is a Matrix transformation
that does a non-uniform scaling
Definition at line 240 of file exportDRAWEXE.py.
References isOpenSCADMultMatrixFeature().
Referenced by exportDRAWEXE.Drawexporter.process_object().
isDraftCircle()
def exportDRAWEXE.isDraftCircle (ob)
Definition at line 188 of file exportDRAWEXE.py.
References isDraftFeature().
Referenced by exportDRAWEXE.Drawexporter.process_object().
isDraftClone()
def exportDRAWEXE.isDraftClone (ob)
Definition at line 180 of file exportDRAWEXE.py.
Referenced by exportDRAWEXE.Drawexporter.process_object().
isDraftEllipse()
def exportDRAWEXE.isDraftEllipse (ob)
Definition at line 193 of file exportDRAWEXE.py.
References isDraftFeature().
Referenced by exportDRAWEXE.Drawexporter.process_object().
isDraftFeature()
def exportDRAWEXE.isDraftFeature (ob)
Definition at line 173 of file exportDRAWEXE.py.
Referenced by isDraftCircle(), isDraftEllipse(), isDraftPoint(), isDraftPolygon(), isDraftShape2DView(), and isDraftWire().
isDraftPoint()
def exportDRAWEXE.isDraftPoint (ob)
Definition at line 203 of file exportDRAWEXE.py.
References isDraftFeature().
Referenced by TechDraw::ShapeExtractor.isPointType(), and exportDRAWEXE.Drawexporter.process_object().
isDraftPolygon()
def exportDRAWEXE.isDraftPolygon (ob)
Definition at line 198 of file exportDRAWEXE.py.
References isDraftFeature().
Referenced by exportDRAWEXE.Drawexporter.process_object().
isDraftShape2DView()
def exportDRAWEXE.isDraftShape2DView (ob)
Definition at line 222 of file exportDRAWEXE.py.
References isDraftFeature().
Referenced by exportDRAWEXE.Drawexporter.process_object().
isDraftWire()
def exportDRAWEXE.isDraftWire (ob)
Definition at line 208 of file exportDRAWEXE.py.
References isDraftFeature().
Referenced by exportDRAWEXE.Drawexporter.process_object().
isOpenSCADFeature()
def exportDRAWEXE.isOpenSCADFeature (ob)
Definition at line 227 of file exportDRAWEXE.py.
isOpenSCADMultMatrixFeature()
def exportDRAWEXE.isOpenSCADMultMatrixFeature (ob)
Definition at line 233 of file exportDRAWEXE.py.
Referenced by isDeform().
occversiontuple()
def exportDRAWEXE.occversiontuple ()
Definition at line 85 of file exportDRAWEXE.py.
Referenced by exportDRAWEXE.Drawexporter.process_object().
placement2draw()
def exportDRAWEXE.placement2draw (placement, name = 'object')
converts a FreeCAD Placement to trotate and ttranslate commands
Definition at line 114 of file exportDRAWEXE.py.
References f2s().
Referenced by exportDRAWEXE.Drawexporter.process_object().
polygonstr()
def exportDRAWEXE.polygonstr (r, pcount)
Definition at line 90 of file exportDRAWEXE.py.
References f2s().
Referenced by exportDRAWEXE.Drawexporter.process_object().
quaternionToString()
def exportDRAWEXE.quaternionToString (rot)
Definition at line 35 of file exportDRAWEXE.py.
References OpenSCADUtils.shorthexfloat().
saveShape()
def exportDRAWEXE.saveShape (csg, filename, shape, name, hasplacement = True, cleanshape = False)
Definition at line 142 of file exportDRAWEXE.py.
Referenced by exportDRAWEXE.Drawexporter.process_object(), and exportDRAWEXE.Drawexporter.saveSweep().