FreeCAD: GCS::ArcOfParabola Class Reference
GCS::ArcOfParabola Class Reference
#include <Geo.h>
Public Member Functions
ArcOfParabola ()
~ArcOfParabola () override
int PushOwnParams (VEC_pD &pvec) override
void ReconstructOnNewPvec (VEC_pD &pvec, int &cnt) override
ArcOfParabola * Copy () override
Public Member Functions inherited from GCS::Parabola
Parabola ()
~Parabola () override
DeriVector2 CalculateNormal (const Point &p, const double *derivparam=nullptr) const override
DeriVector2 Value (double u, double du, const double *derivparam=nullptr) const override
Value: returns point (vector) given the value of parameter.
Public Member Functions inherited from GCS::Curve
virtual ~Curve ()
virtual DeriVector2 CalculateNormal (const double *param, const double *derivparam=nullptr) const
Public Attributes
double * startAngle
double * endAngle
Point start
Point end
Public Attributes inherited from GCS::Parabola
Point vertex
Point focus1
Detailed Description
Definition at line 404 of file Geo.h.
Constructor & Destructor Documentation
ArcOfParabola()
GCS::ArcOfParabola::ArcOfParabola () inline
Definition at line 407 of file Geo.h.
Referenced by Copy().
~ArcOfParabola()
GCS::ArcOfParabola::~ArcOfParabola () inline override
Definition at line 412 of file Geo.h.
Member Function Documentation
Copy()
ArcOfParabola * GCS::ArcOfParabola::Copy () override virtual
Reimplemented from GCS::Parabola.
Definition at line 723 of file Geo.cpp.
References ArcOfParabola().
PushOwnParams()
int GCS::ArcOfParabola::PushOwnParams (VEC_pD & pvec) override virtual
Reimplemented from GCS::Parabola.
Definition at line 689 of file Geo.cpp.
References end, endAngle, GCS::Parabola::PushOwnParams(), start, startAngle, GCS::Point::x, and GCS::Point::y.
Referenced by GCS::ConstraintEqualFocalDistance::ConstraintEqualFocalDistance().
ReconstructOnNewPvec()
void GCS::ArcOfParabola::ReconstructOnNewPvec (VEC_pD & pvec, int & cnt) override virtual
Reimplemented from GCS::Parabola.
Definition at line 707 of file Geo.cpp.
References end, endAngle, GCS::Parabola::ReconstructOnNewPvec(), start, startAngle, GCS::Point::x, and GCS::Point::y.
Member Data Documentation
end
Point GCS::ArcOfParabola::end
Definition at line 418 of file Geo.h.
Referenced by PushOwnParams(), and ReconstructOnNewPvec().
endAngle
double* GCS::ArcOfParabola::endAngle
Definition at line 416 of file Geo.h.
Referenced by PushOwnParams(), and ReconstructOnNewPvec().
start
Point GCS::ArcOfParabola::start
Definition at line 417 of file Geo.h.
Referenced by PushOwnParams(), and ReconstructOnNewPvec().
startAngle
double* GCS::ArcOfParabola::startAngle
Definition at line 415 of file Geo.h.
Referenced by PushOwnParams(), and ReconstructOnNewPvec().
The documentation for this class was generated from the following files:
Geo.h
Geo.cpp