FreeCAD: SpreadsheetGui::WorkbenchHelper Class Reference
SpreadsheetGui::WorkbenchHelper Class Reference
#include <Workbench.h>
Public Slots
void setForegroundColor (const QColor &color)
void setBackgroundColor (const QColor &color)
Detailed Description
Author
Eivind Kvedalen
Definition at line 41 of file Mod/Spreadsheet/Gui/Workbench.h.
Member Function Documentation
setBackgroundColor
void WorkbenchHelper::setBackgroundColor (const QColor & color) slot
Definition at line 159 of file Mod/Spreadsheet/Gui/Workbench.cpp.
References Gui::Application::activeDocument(), Gui::MainWindow::activeWindow(), Gui::Command::commitCommand(), toolbit-attributes::doc, Gui::Command::Doc, doCommand, Gui::getMainWindow(), App::DocumentObject::getNameInDocument(), SpreadsheetGui::SheetView::getSheet(), SplineSurface::i, Gui::Application::Instance, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, and SpreadsheetGui::SheetView::selectedRanges().
setForegroundColor
void WorkbenchHelper::setForegroundColor (const QColor & color) slot
Definition at line 125 of file Mod/Spreadsheet/Gui/Workbench.cpp.
References Gui::Application::activeDocument(), Gui::MainWindow::activeWindow(), Gui::Command::commitCommand(), toolbit-attributes::doc, Gui::Command::Doc, doCommand, Gui::getMainWindow(), App::DocumentObject::getNameInDocument(), SpreadsheetGui::SheetView::getSheet(), SplineSurface::i, Gui::Application::Instance, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, and SpreadsheetGui::SheetView::selectedRanges().
The documentation for this class was generated from the following files:
Mod/Spreadsheet/Gui/Workbench.h
Mod/Spreadsheet/Gui/Workbench.cpp