FreeCAD: Gui::Dialog::DlgParameterImp Class Reference
Gui::Dialog::DlgParameterImp Class Reference
#include <DlgParameterImp.h>
Public Member Functions
DlgParameterImp (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgParameterImp () override
void accept () override
void reject () override
void activateParameterSet (const char *)
Protected Member Functions
void setupConnections ()
void onChangeParameterSet (int)
void onButtonFindClicked ()
void onFindGroupTtextChanged (const QString &SearchStr)
void onButtonSaveToDiskClicked ()
void onGroupSelected (QTreeWidgetItem *)
void onCloseButtonClicked ()
void onCheckSortToggled (bool)
void changeEvent (QEvent *e) override
void showEvent (QShowEvent *) override
void closeEvent (QCloseEvent *) override
Protected Attributes
QTreeWidget * paramGroup
QTreeWidget * paramValue
Ui_DlgParameter * ui
QPointer< DlgParameterFind > finder
Detailed Description
The DlgParameterImp class implements a dialog showing all parameters in a list view.
Author
Jürgen Riegel
Definition at line 85 of file DlgParameterImp.h.
Constructor & Destructor Documentation
DlgParameterImp()
DlgParameterImp::DlgParameterImp (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Constructs a DlgParameterImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
Definition at line 59 of file DlgParameterImp.cpp.
References draftgeoutils.intersections::connect(), App::GetApplication(), App::Application::GetParameterSet(), App::Application::GetParameterSetList(), onChangeParameterSet(), onGroupSelected(), paramGroup, paramValue, setupConnections(), and ui.
~DlgParameterImp()
DlgParameterImp::~DlgParameterImp () override
Destroys the object and frees any allocated resources
Definition at line 132 of file DlgParameterImp.cpp.
References ui.
Member Function Documentation
accept()
void DlgParameterImp::accept () override
Definition at line 268 of file DlgParameterImp.cpp.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
activateParameterSet()
void DlgParameterImp::activateParameterSet (const char * config)
Switches the type of parameters with name config.
Definition at line 377 of file DlgParameterImp.cpp.
References onChangeParameterSet(), and ui.
changeEvent()
void DlgParameterImp::changeEvent (QEvent * e) override protected
Sets the strings of the subwidgets using the current language.
Definition at line 238 of file DlgParameterImp.cpp.
References SCL.SimpleDataTypes::e, paramGroup, paramValue, and ui.
closeEvent()
void DlgParameterImp::closeEvent (QCloseEvent *) override protected
Definition at line 295 of file DlgParameterImp.cpp.
References App::GetApplication(), ParameterGrp::GetGroup(), App::Application::GetUserParameter(), paramGroup, Init::parent, ParameterGrp::SetASCII(), and Path.Post.scripts.refactored_centroid_post::str.
onButtonFindClicked()
void DlgParameterImp::onButtonFindClicked () protected
Definition at line 154 of file DlgParameterImp.cpp.
References finder.
Referenced by setupConnections().
onButtonSaveToDiskClicked()
void DlgParameterImp::onButtonSaveToDiskClicked () protected
Definition at line 452 of file DlgParameterImp.cpp.
References App::GetApplication(), App::Application::GetParameterSet(), ParameterManager::SaveDocument(), and ui.
Referenced by setupConnections().
onChangeParameterSet()
void DlgParameterImp::onChangeParameterSet (int itemPos) protected
Switches the type of parameters either to user or system parameters.
Definition at line 387 of file DlgParameterImp.cpp.
References ParameterManager::CheckDocument(), App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetGroup(), ParameterGrp::GetGroups(), App::Application::GetParameterSet(), App::Application::GetUserParameter(), toolbit-attributes::grp, ParameterManager::HasSerializer(), paramGroup, paramValue, Init::parent, and ui.
Referenced by activateParameterSet(), and DlgParameterImp().
onCheckSortToggled()
void DlgParameterImp::onCheckSortToggled (bool on) protected
Definition at line 252 of file DlgParameterImp.cpp.
References paramGroup, and paramValue.
Referenced by setupConnections().
onCloseButtonClicked()
void DlgParameterImp::onCloseButtonClicked () protected
Definition at line 263 of file DlgParameterImp.cpp.
Referenced by setupConnections().
onFindGroupTtextChanged()
void DlgParameterImp::onFindGroupTtextChanged (const QString & SearchStr) protected
Definition at line 162 of file DlgParameterImp.cpp.
References Gui::ExpandItem, SplineSurface::i, paramGroup, and ui.
Referenced by setupConnections().
onGroupSelected()
void DlgParameterImp::onGroupSelected (QTreeWidgetItem * item) protected
Definition at line 320 of file DlgParameterImp.cpp.
References ParameterGrp::GetASCIIMap(), ParameterGrp::GetBoolMap(), ParameterGrp::GetFloatMap(), ParameterGrp::GetIntMap(), ParameterGrp::GetUnsignedMap(), and paramValue.
Referenced by DlgParameterImp().
reject()
void DlgParameterImp::reject () override
Definition at line 273 of file DlgParameterImp.cpp.
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
setupConnections()
void DlgParameterImp::setupConnections () protected
Definition at line 138 of file DlgParameterImp.cpp.
References draftgeoutils.intersections::connect(), onButtonFindClicked(), onButtonSaveToDiskClicked(), onCheckSortToggled(), onCloseButtonClicked(), onFindGroupTtextChanged(), and ui.
Referenced by DlgParameterImp().
showEvent()
void DlgParameterImp::showEvent (QShowEvent *) override protected
Definition at line 278 of file DlgParameterImp.cpp.
References App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetGroup(), App::Application::GetUserParameter(), and Path.Post.scripts.refactored_centroid_post::str.
Member Data Documentation
finder
QPointer<DlgParameterFind> Gui::Dialog::DlgParameterImp::finder protected
Definition at line 118 of file DlgParameterImp.h.
Referenced by onButtonFindClicked().
paramGroup
QTreeWidget* Gui::Dialog::DlgParameterImp::paramGroup protected
Definition at line 115 of file DlgParameterImp.h.
Referenced by changeEvent(), closeEvent(), DlgParameterImp(), onChangeParameterSet(), onCheckSortToggled(), and onFindGroupTtextChanged().
paramValue
QTreeWidget* Gui::Dialog::DlgParameterImp::paramValue protected
Definition at line 116 of file DlgParameterImp.h.
Referenced by changeEvent(), DlgParameterImp(), onChangeParameterSet(), onCheckSortToggled(), and onGroupSelected().
ui
Ui_DlgParameter* Gui::Dialog::DlgParameterImp::ui protected
Definition at line 117 of file DlgParameterImp.h.
Referenced by draftguitools.gui_splines.BSpline::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_texts.Text::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_split.Split::Activated(), draftguitools.gui_rectangles.Rectangle::Activated(), draftguitools.gui_join.Join::Activated(), draftguitools.gui_draft2sketch.Draft2Sketch::Activated(), draftguitools.gui_polygons.Polygon::Activated(), draftguitools.gui_downgrade.Downgrade::Activated(), draftguitools.gui_upgrade.Upgrade::Activated(), draftguitools.gui_ellipses.Ellipse::Activated(), draftguitools.gui_shape2dview.Shape2DView::Activated(), draftguitools.gui_facebinders.Facebinder::Activated(), draftguitools.gui_texts.Text::Activated(), draftguitools.gui_move.Move::Activated(), draftguitools.gui_points.Point::Activated(), draftguitools.gui_rotate.Rotate::Activated(), draftguitools.gui_arcs.Arc::Activated(), draftguitools.gui_lines.Line::Activated(), draftguitools.gui_orthoarray.OrthoArray::Activated(), draftguitools.gui_polararray.PolarArray::Activated(), draftguitools.gui_circulararray.CircularArray::Activated(), draftguitools.gui_shapestrings.ShapeString::Activated(), draftguitools.gui_fillets.Fillet::Activated(), draftguitools.gui_scale.Scale::Activated(), draftguitools.gui_clone.Clone::Activated(), draftguitools.gui_dimensions.Dimension::Activated(), activateParameterSet(), draftguitools.gui_stretch.Stretch::addPoint(), draftguitools.gui_rectangles.Rectangle::appendPoint(), draftguitools.gui_ellipses.Ellipse::appendPoint(), src.Mod.AddonManager.addonmanager_package_details_controller.PackageDetailsController::branch_changed(), src.Mod.AddonManager.addonmanager_package_details_controller.PackageDetailsController::change_branch_clicked(), changeEvent(), DraftGui.DraftToolBar::changeEvent(), draftguitools.gui_orthoarray.OrthoArray::click(), draftguitools.gui_polararray.PolarArray::click(), draftguitools.gui_circulararray.CircularArray::click(), draftguitools.gui_dimensions.Dimension::createObject(), src.Mod.AddonManager.addonmanager_package_details_controller.PackageDetailsController::disable_clicked(), DlgParameterImp(), draftguitools.gui_polygons.Polygon::drawPolygon(), src.Mod.AddonManager.addonmanager_package_details_controller.PackageDetailsController::enable_clicked(), draftguitools.gui_edit.Edit::endEditing(), src.Mod.AddonManager.change_branch.ChangeBranchDialog::exec(), draftguitools.gui_rectangles.Rectangle::finish(), draftguitools.gui_ellipses.Ellipse::finish(), draftguitools.gui_texts.Text::finish(), draftguitools.gui_polygons.Polygon::finish(), draftguitools.gui_arcs.Arc::finish(), draftguitools.gui_move.Move::finish(), draftguitools.gui_points.Point::finish(), draftguitools.gui_lines.Line::finish(), draftguitools.gui_base_original.DraftTool::finish(), draftguitools.gui_splines.BSpline::finish(), draftguitools.gui_dimensions.Dimension::finish(), draftguitools.gui_beziers.BezCurve::finish(), draftguitools.gui_rotate.Rotate::finish(), draftguitools.gui_edit.Edit::finish(), draftguitools.gui_beziers.CubicBezCurve::finish(), draftguitools.gui_trimex.Trimex::finish(), draftguitools.gui_move.Move::get_object_selection(), draftguitools.gui_rotate.Rotate::get_object_selection(), draftguitools.gui_scale.Scale::get_object_selection(), draftguitools.gui_subelements.SubelementHighlight::get_selection(), draftguitools.gui_base_original.DraftTool::getStrings(), draftguitools.gui_move.Move::handle_mouse_click_event(), draftguitools.gui_polararray.PolarArray::move(), draftguitools.gui_circulararray.CircularArray::move(), draftguitools.gui_move.Move::move(), draftguitools.gui_polygons.Polygon::numericInput(), draftguitools.gui_rotate.Rotate::numericInput(), draftguitools.gui_arcs.Arc::numericInput(), draftguitools.gui_offset.Offset::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), draftguitools.gui_arcs.Arc::numericRadius(), onButtonSaveToDiskClicked(), onChangeParameterSet(), onFindGroupTtextChanged(), draftguitools.gui_groups.AddToGroup::proceed(), draftguitools.gui_groups.SetAutoGroup::proceed(), draftguitools.gui_edit.Edit::proceed(), draftguitools.gui_rotate.Rotate::rotate(), src.Mod.AddonManager.package_list.PackageList::select_addon(), draftguitools.gui_fillets.Fillet::set_chamfer(), src.Mod.AddonManager.addonmanager_package_details_controller.PackageDetailsController::set_change_branch_button_state(), draftguitools.gui_fillets.Fillet::set_delete(), draftguitools.gui_move.Move::set_ghosts(), draftguitools.gui_rotate.Rotate::set_ghosts(), src.Mod.AddonManager.package_list.PackageList::set_loading(), draftguitools.gui_rotate.Rotate::set_start_point(), src.Mod.AddonManager.package_list.PackageList::set_view_style(), src.Mod.AddonManager.package_list.PackageList::setModel(), setupConnections(), src.Mod.AddonManager.addonmanager_package_details_controller.PackageDetailsController::show_repo(), draftguitools.gui_edit.Edit::startEditing(), src.Mod.AddonManager.package_list.PackageList::update_loading_progress(), draftguitools.gui_edit.Edit::updateTrackerAndGhost(), and ~DlgParameterImp().
The documentation for this class was generated from the following files:
DlgParameterImp.h
DlgParameterImp.cpp