FreeCAD: Gui::SelectionObject Class Reference
Gui::SelectionObject Class Reference
#include <SelectionObject.h>
Public Member Functions
SelectionObject ()
SelectionObject (const SelectionChanges &msg)
SelectionObject (const App::DocumentObject *)
~SelectionObject () override
PyObject * getPyObject () override
const std::vector< std::string > & getSubNames () const
get the SubElement name of this SelectionObject
bool hasSubNames () const
are there any SubNames selected
const char * getDocName () const
get the name of the Document of this SelctionObject
const char * getFeatName () const
get the name of the Document Object of this SelectionObject
const char * getTypeName () const
get the Type of the selected Object
const std::vector< Base::Vector3d > getPickedPoints () const
get the selection points
const App::DocumentObject * getObject () const
returns the selected DocumentObject or NULL if the object is already deleted
template<class T >
const T * getObject () const
returns the selected DocumentObject or NULL if the object is already deleted
App::DocumentObject * getObject ()
returns the selected DocumentObject or NULL if the object is already deleted
template<class T >
T * getObject ()
returns the selected DocumentObject if it is of T type or null otherwise
bool isObjectTypeOf (const Base::Type &typeId) const
check the selected object is a special type or derived of
std::string getAsPropertyLinkSubString () const
returns python expreasion sutably for assigning to a LinkSub property
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Attributes
std::vector< std::string > SubNames
std::string DocName
std::string FeatName
std::string TypeName
std::vector< Base::Vector3d > SelPoses
Friends
class SelectionSingleton
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
The Selection object class
Definition at line 43 of file SelectionObject.h.
Constructor & Destructor Documentation
SelectionObject() [1/3]
SelectionObject::SelectionObject () default
Constructs a SelectionObject object.
Referenced by getPyObject().
SelectionObject() [2/3]
SelectionObject::SelectionObject (const SelectionChanges & msg) explicit
Constructs a SelectionObject from the SelectionChanges structure.
Definition at line 45 of file SelectionObject.cpp.
References DocName, FeatName, Path.Op.Surface::msg, SelPoses, SubNames, and TypeName.
SelectionObject() [3/3]
SelectionObject::SelectionObject (const App::DocumentObject * obj) explicit
Definition at line 56 of file SelectionObject.cpp.
References DocName, FeatName, App::DocumentObject::getDocument(), Base::Type::getName(), App::Document::getName(), App::DocumentObject::getNameInDocument(), Base::Persistence::getTypeId(), and TypeName.
~SelectionObject()
SelectionObject::~SelectionObject () override default
Member Function Documentation
getAsPropertyLinkSubString()
std::string SelectionObject::getAsPropertyLinkSubString () const
returns python expreasion sutably for assigning to a LinkSub property
Definition at line 91 of file SelectionObject.cpp.
References getObject(), Gui::Command::getObjectCmd(), Path.Post.scripts.refactored_centroid_post::str, and SubNames.
getDocName()
const char* Gui::SelectionObject::getDocName () const inline
get the name of the Document of this SelctionObject
Definition at line 65 of file SelectionObject.h.
Referenced by Gui::SelectionSingleton::addSelection(), and TechDrawGui::MDIViewPage::removeUnselectedTreeSelection().
getFeatName()
const char* Gui::SelectionObject::getFeatName () const inline
get the name of the Document Object of this SelectionObject
Definition at line 67 of file SelectionObject.h.
Referenced by Gui::SelectionSingleton::addSelection().
getObject() [1/4]
App::DocumentObject* Gui::SelectionObject::getObject ()
returns the selected DocumentObject or NULL if the object is already deleted
getObject() [2/4]
template<class T > T* Gui::SelectionObject::getObject () inline
returns the selected DocumentObject if it is of T type or null otherwise
Definition at line 82 of file SelectionObject.h.
References getObject().
Referenced by getObject().
getObject() [3/4]
App::DocumentObject * SelectionObject::getObject () const
returns the selected DocumentObject or NULL if the object is already deleted
Definition at line 65 of file SelectionObject.cpp.
References toolbit-attributes::doc, DocName, FeatName, App::GetApplication(), and App::Application::getDocument().
Referenced by dressupGetSelected(), getAsPropertyLinkSubString(), isObjectTypeOf(), makeChamferOrFillet(), SurfaceGui::FillingVertexPanel::onSelectionChanged(), SurfaceGui::FillingEdgePanel::onSelectionChanged(), SurfaceGui::GeomFillSurface::onSelectionChanged(), SurfaceGui::SectionsPanel::onSelectionChanged(), SurfaceGui::FillingPanel::onSelectionChanged(), PartGui::DlgFilletEdges::Private::SelectionObjectCompare::operator()(), and TechDrawGui::MDIViewPage::removeUnselectedTreeSelection().
getObject() [4/4]
template<class T > const T* Gui::SelectionObject::getObject () const inline
returns the selected DocumentObject or NULL if the object is already deleted
Definition at line 77 of file SelectionObject.h.
References getObject().
Referenced by getObject().
getPickedPoints()
const std::vector<Base::Vector3d> Gui::SelectionObject::getPickedPoints () const inline
get the selection points
Definition at line 71 of file SelectionObject.h.
Referenced by Gui::SelectionSingleton::addSelection().
getPyObject()
PyObject * SelectionObject::getPyObject () override virtual
The default implementation returns an instance of SelectionObjectPy.
Reimplemented from Base::BaseClass.
Definition at line 101 of file SelectionObject.cpp.
References SelectionObject().
Referenced by Gui::SelectionSingleton::sGetCompleteSelection(), Gui::SelectionSingleton::sGetPreselection(), and Gui::SelectionSingleton::sGetSelectionObject().
getSubNames()
const std::vector<std::string>& Gui::SelectionObject::getSubNames () const inline
get the SubElement name of this SelectionObject
Definition at line 61 of file SelectionObject.h.
Referenced by Gui::SelectionSingleton::addSelection(), makeChamferOrFillet(), and TechDrawGui::MDIViewPage::removeUnselectedTreeSelection().
getTypeName()
const char* Gui::SelectionObject::getTypeName () const inline
get the Type of the selected Object
Definition at line 69 of file SelectionObject.h.
hasSubNames()
bool Gui::SelectionObject::hasSubNames () const inline
are there any SubNames selected
Definition at line 63 of file SelectionObject.h.
isObjectTypeOf()
bool SelectionObject::isObjectTypeOf (const Base::Type & typeId) const
check the selected object is a special type or derived of
Definition at line 85 of file SelectionObject.cpp.
References getObject(), Base::Persistence::getTypeId(), and Base::Type::isDerivedFrom().
Referenced by dressupGetSelected().
Friends And Related Function Documentation
SelectionSingleton
friend class SelectionSingleton friend
Definition at line 90 of file SelectionObject.h.
Member Data Documentation
DocName
std::string Gui::SelectionObject::DocName protected
Definition at line 94 of file SelectionObject.h.
Referenced by getObject(), SelectionObject(), Gui::SelectionSingleton::sGetSelectionObject(), src.Mod.Test.Document.DocumentPlatformCases::testColorList(), src.Mod.Test.Document.DocumentPlatformCases::testFloatList(), src.Mod.Test.Document.DocumentPlatformCases::testPoints(), and src.Mod.Test.Document.DocumentPlatformCases::testVectorList().
FeatName
std::string Gui::SelectionObject::FeatName protected
Definition at line 95 of file SelectionObject.h.
Referenced by getObject(), SelectionObject(), and Gui::SelectionSingleton::sGetSelectionObject().
SelPoses
std::vector<Base::Vector3d> Gui::SelectionObject::SelPoses protected
Definition at line 97 of file SelectionObject.h.
Referenced by SelectionObject(), and Gui::SelectionSingleton::sGetSelectionObject().
SubNames
std::vector<std::string> Gui::SelectionObject::SubNames protected
Definition at line 93 of file SelectionObject.h.
Referenced by getAsPropertyLinkSubString(), SelectionObject(), and Gui::SelectionSingleton::sGetSelectionObject().
TypeName
std::string Gui::SelectionObject::TypeName protected
Definition at line 96 of file SelectionObject.h.
Referenced by SelectionObject().
The documentation for this class was generated from the following files:
SelectionObject.h
SelectionObject.cpp