FreeCAD: MatGui Namespace Reference
MatGui Namespace Reference
Classes
class AbstractArrayModel
class AppearancePreview
class AppearanceSettings
class Array2D
class Array2DModel
class Array3D
class Array3DDepthModel
class Array3DModel
class ArrayDelegate
class BaseDelegate
class ColorWidget
class DlgDisplayPropertiesImp
class DlgInspectAppearance
class DlgInspectMaterial
class DlgMaterialImp
class DlgSettingsDefaultMaterial
class DlgSettingsMaterial
class ImageEdit
class ImageLabel
class ListDelegate
class ListEdit
class ListModel
class MaterialDelegate
class MaterialSave
class MaterialsEditor
class MaterialTreeWidget
class ModelSelect
class Module
class PrefMaterialTreeWidget
class TaskDisplayProperties
class TaskInspectAppearance
class TaskInspectMaterial
class TaskMaterial
class TextEdit
class Workbench
class WorkbenchManipulator
Functions
PyObject * initModule ()
Function Documentation
initModule()
PyObject* MatGui::initModule ()
Definition at line 68 of file AppMatGui.cpp.
References Base::InterpreterSingleton::addModule(), and Base::Interpreter().
Referenced by PyMOD_INIT_FUNC().