FreeCAD: Gui::NetworkRetriever Class Reference
Gui::NetworkRetriever Class Reference
#include <NetworkRetriever.h>
Signals
void wgetExited ()
Public Member Functions
NetworkRetriever (QObject *parent=nullptr)
~NetworkRetriever () override
void setNumberOfTries (int)
void setOutputFile (const QString &)
void setEnableTimestamp (bool)
void setProxy (const QString &, const QString &=QString(), const QString &=QString())
void setEnableRecursive (bool, int=0)
void setFollowRelative (bool)
void setEnableConvert (bool)
void setFetchImages (bool)
void setEnableHTMLExtension (bool)
void setNoParent (bool)
void setOutputDirectory (const QString &)
bool startDownload (const QString &)
bool isDownloading () const
void abort ()
Static Public Member Functions
static bool testWget ()
Detailed Description
The NetworkRetriever class encapsulates the GNU tool wget. wget is a non-interactive network retriever to download e.g. the whole file structure from a server.
Author
Werner Mayer
Definition at line 60 of file NetworkRetriever.h.
Constructor & Destructor Documentation
NetworkRetriever()
NetworkRetriever::NetworkRetriever (QObject * parent = nullptr)
Definition at line 77 of file NetworkRetriever.cpp.
References draftgeoutils.intersections::connect(), Gui::NetworkRetrieverP::convert, Gui::NetworkRetrieverP::folRel, Gui::NetworkRetrieverP::html, Gui::NetworkRetrieverP::img, Gui::NetworkRetrieverP::level, Gui::NetworkRetrieverP::nop, Gui::NetworkRetrieverP::recurse, Gui::NetworkRetrieverP::timeStamp, and Gui::NetworkRetrieverP::tries.
~NetworkRetriever()
NetworkRetriever::~NetworkRetriever () override
Definition at line 101 of file NetworkRetriever.cpp.
Member Function Documentation
abort()
void NetworkRetriever::abort ()
Kills wget if it is still running.
Definition at line 350 of file NetworkRetriever.cpp.
Referenced by Gui::StdCmdDownloadOnlineHelp::activated(), PathPythonGui.simple_edit_panel.SimpleEditPanel::clicked(), and femsolver.run.Machine::run().
isDownloading()
bool NetworkRetriever::isDownloading () const
Returns true if wget is still downloading, otherwise returns false.
Definition at line 342 of file NetworkRetriever.cpp.
Referenced by Gui::StdCmdDownloadOnlineHelp::activated().
setEnableConvert()
void NetworkRetriever::setEnableConvert (bool convert)
If convert is true all non-relative links are converted to relative links. As default the convert property is true.
Definition at line 191 of file NetworkRetriever.cpp.
References Gui::NetworkRetrieverP::convert, and Help::convert().
Referenced by Gui::StdCmdDownloadOnlineHelp::StdCmdDownloadOnlineHelp().
setEnableHTMLExtension()
void NetworkRetriever::setEnableHTMLExtension (bool html)
Saves all text/html documents with .html extionsion if html is true. As default the html property is false.
Definition at line 209 of file NetworkRetriever.cpp.
References bimcommands.BimTutorial::html, and Gui::NetworkRetrieverP::html.
Referenced by Gui::StdCmdDownloadOnlineHelp::StdCmdDownloadOnlineHelp().
setEnableRecursive()
void NetworkRetriever::setEnableRecursive (bool recursive, int level = 0)
If recursive is true all referenced files are downloaded recursively. As default recursion is disabled. level specifies the maximum recursion depth. If level is 0 the recursion depth is infinite. As default the level property is 1.
Note
: Use this with care!
Definition at line 172 of file NetworkRetriever.cpp.
References Gui::NetworkRetrieverP::level, level(), and Gui::NetworkRetrieverP::recurse.
Referenced by Gui::StdCmdDownloadOnlineHelp::StdCmdDownloadOnlineHelp().
setEnableTimestamp()
void NetworkRetriever::setEnableTimestamp (bool ts)
If ts is true the timestamping is enabled, otherwise timestamping is disabled. If timestamping is enabled files are no more re-retrieved unless they are newer than the local files. As default the timestamping property is disabled.
Definition at line 148 of file NetworkRetriever.cpp.
References Gui::NetworkRetrieverP::timeStamp, and src.Mod.Test.UnitTests::ts().
Referenced by Gui::StdCmdDownloadOnlineHelp::StdCmdDownloadOnlineHelp().
setFetchImages()
void NetworkRetriever::setFetchImages (bool img)
If img is true wget tries to get all needed image files to display the HTML page. As default this behaviour is disabled..
Definition at line 200 of file NetworkRetriever.cpp.
References Gui::NetworkRetrieverP::img.
Referenced by Gui::StdCmdDownloadOnlineHelp::StdCmdDownloadOnlineHelp().
setFollowRelative()
void NetworkRetriever::setFollowRelative (bool folRel)
If folRel is true wget follows relative links only. As default the follows relative property is false.
Definition at line 182 of file NetworkRetriever.cpp.
References Gui::NetworkRetrieverP::folRel.
Referenced by Gui::StdCmdDownloadOnlineHelp::StdCmdDownloadOnlineHelp().
setNoParent()
void NetworkRetriever::setNoParent (bool nop)
Do not ever ascend to the parent directory when retrieving recursively.
Definition at line 217 of file NetworkRetriever.cpp.
References Gui::NetworkRetrieverP::nop.
Referenced by Gui::StdCmdDownloadOnlineHelp::StdCmdDownloadOnlineHelp().
setNumberOfTries()
void NetworkRetriever::setNumberOfTries (int tries)
Sets the number of retries to tries. If tries is 0 the number of tries is unlimited. The default value of the tries property is set to 3.
Definition at line 130 of file NetworkRetriever.cpp.
References Gui::NetworkRetrieverP::tries.
Referenced by Gui::StdCmdDownloadOnlineHelp::StdCmdDownloadOnlineHelp().
setOutputDirectory()
void NetworkRetriever::setOutputDirectory (const QString & dir)
Sets the output directory to dir where all downloaded are written into.
Definition at line 225 of file NetworkRetriever.cpp.
References Gui::NetworkRetrieverP::dir.
Referenced by Gui::StdCmdDownloadOnlineHelp::activated().
setOutputFile()
void NetworkRetriever::setOutputFile (const QString & out)
Sets output file to out where documents are written to.
Definition at line 138 of file NetworkRetriever.cpp.
References Gui::NetworkRetrieverP::outputFile.
setProxy()
void NetworkRetriever::setProxy (const QString & proxy, const QString & user = QString(), const QString & passwd = QString())
If you are behind a proxy server then you have to specify your proxy url with proxy. Moreover, if the proxy requires user authentication then you can specify the username with user and the password with passwd.
Definition at line 158 of file NetworkRetriever.cpp.
References Gui::NetworkRetrieverP::passwd, Gui::NetworkRetrieverP::proxy, and Gui::NetworkRetrieverP::user.
Referenced by Gui::StdCmdDownloadOnlineHelp::activated().
startDownload()
bool NetworkRetriever::startDownload (const QString & startUrl)
wget starts to download startUrl and all referenced pages.
Definition at line 233 of file NetworkRetriever.cpp.
References Base::Console(), Gui::NetworkRetrieverP::convert, Gui::NetworkRetrieverP::dir, Base::ConsoleSingleton::Error(), Gui::NetworkRetrieverP::folRel, Gui::NetworkRetrieverP::html, Gui::NetworkRetrieverP::img, Gui::NetworkRetrieverP::level, Gui::NetworkRetrieverP::nop, Gui::NetworkRetrieverP::outputFile, Gui::NetworkRetrieverP::passwd, Gui::NetworkRetrieverP::proxy, Gui::NetworkRetrieverP::recurse, NavigationIndicatorGui::setCurrent(), Gui::NetworkRetrieverP::startUrl, testWget(), Gui::NetworkRetrieverP::timeStamp, Gui::NetworkRetrieverP::tries, and Gui::NetworkRetrieverP::user.
Referenced by Gui::StdCmdDownloadOnlineHelp::activated().
testWget()
bool NetworkRetriever::testWget () static
This is a test if wget is in PATH environment or not. If the test succeeds true is returned, false otherwise.
Definition at line 374 of file NetworkRetriever.cpp.
Referenced by startDownload().
wgetExited
void Gui::NetworkRetriever::wgetExited () signal
Referenced by Gui::StdCmdDownloadOnlineHelp::StdCmdDownloadOnlineHelp().
The documentation for this class was generated from the following files:
NetworkRetriever.h
NetworkRetriever.cpp