FreeCAD: Gui::Dialog::TaskPlacement Class Reference
Gui::Dialog::TaskPlacement Class Reference
#include <Placement.h>
Public Slots
void slotPlacementChanged (const QVariant &, bool, bool)
Signals
void placementChanged (const QVariant &, bool, bool)
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Public Member Functions
TaskPlacement ()
~TaskPlacement () override
void setPropertyName (const QString &)
void setPlacement (const Base::Placement &)
void setSelection (const std::vector< SelectionObject > &)
TaskPlacement::setSelection Sets the array of selection objects.
void clearSelection ()
TaskPlacement::clearSelection Clears the array of selection objects.
void bindObject ()
TaskPlacement::bindObject Binds the spin boxes to the placement components of the first object of the selection. This requires the call of setSelection() beforehand.
void setPlacementAndBindObject (const App::DocumentObject *obj, const std::string &propertyName)
bool accept () override
is called by the framework if the dialog is accepted (Ok)
bool reject () override
is called by the framework if the dialog is rejected (Cancel)
void clicked (int id) override
is called by the framework if a button is clicked which has no accept or reject role
void open () override
is called by the framework when the dialog is opened
bool isAllowedAlterDocument () const override
bool isAllowedAlterView () const override
bool isAllowedAlterSelection () const override
QDialogButtonBox::StandardButtons getStandardButtons () const override
tells the framework which buttons are wished for the dialog
Public Member Functions inherited from Gui::TaskView::TaskDialog
TaskDialog ()
~TaskDialog () override
QWidget * addTaskBox (QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBox (const QPixmap &icon, QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBoxWithoutHeader (QWidget *widget)
void setButtonPosition (ButtonPosition p)
ButtonPosition buttonPosition () const
const std::vector< QWidget * > & getDialogContent () const
bool canClose () const
virtual void modifyStandardButtons (QDialogButtonBox *)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
bool isEscapeButtonEnabled () const
void setAutoCloseOnTransactionChange (bool on)
bool isAutoCloseOnTransactionChange () const
void setAutoCloseOnDeletedDocument (bool on)
bool isAutoCloseOnDeletedDocument () const
const std::string & getDocumentName () const
void setDocumentName (const std::string &doc)
void setAutoCloseOnClosedView (bool on)
bool isAutoCloseOnClosedView () const
void associateToObject3dView (App::DocumentObject *obj)
const Gui::MDIView * getAssociatedView () const
void setAssociatedView (const Gui::MDIView *view)
virtual bool needsFullSpace () const
virtual void closed ()
is called by the framework when the dialog is closed
virtual void autoClosedOnTransactionChange ()
virtual void autoClosedOnDeletedDocument ()
virtual void autoClosedOnClosedView ()
virtual void helpRequested ()
is called by the framework if the user press the help button
void emitDestructionSignal ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Protected Attributes inherited from Gui::TaskView::TaskDialog
QPointer< QDialogButtonBox > buttonBox
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Detailed Description
Definition at line 191 of file Gui/Placement.h.
Constructor & Destructor Documentation
TaskPlacement()
TaskPlacement::TaskPlacement ()
Definition at line 1132 of file Gui/Placement.cpp.
References Gui::TaskView::TaskDialog::addTaskBox(), draftgeoutils.intersections::connect(), Gui::Dialog::Placement::placementChanged(), Gui::TaskView::TaskDialog::setButtonPosition(), Gui::Dialog::Placement::showDefaultButtons(), slotPlacementChanged(), and Gui::TaskView::TaskDialog::South.
~TaskPlacement()
TaskPlacement::~TaskPlacement () override default
Member Function Documentation
accept()
bool TaskPlacement::accept () override virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 1206 of file Gui/Placement.cpp.
References Gui::Dialog::Placement::accept().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
bindObject()
void TaskPlacement::bindObject ()
TaskPlacement::bindObject Binds the spin boxes to the placement components of the first object of the selection. This requires the call of setSelection() beforehand.
Definition at line 1168 of file Gui/Placement.cpp.
References Gui::Dialog::Placement::bindObject().
clearSelection()
void TaskPlacement::clearSelection ()
TaskPlacement::clearSelection Clears the array of selection objects.
Definition at line 1158 of file Gui/Placement.cpp.
References Gui::Dialog::Placement::setSelection().
clicked()
void TaskPlacement::clicked (int) override virtual
is called by the framework if a button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 1218 of file Gui/Placement.cpp.
References Gui::Dialog::Placement::onApplyButtonClicked().
getStandardButtons()
QDialogButtonBox::StandardButtons TaskPlacement::getStandardButtons () const override virtual
tells the framework which buttons are wished for the dialog
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 1189 of file Gui/Placement.cpp.
isAllowedAlterDocument()
bool Gui::Dialog::TaskPlacement::isAllowedAlterDocument () const inline override virtual
Indicates whether this task dialog allows other commands to modify the document while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 212 of file Gui/Placement.h.
isAllowedAlterSelection()
bool Gui::Dialog::TaskPlacement::isAllowedAlterSelection () const inline override virtual
Indicates whether this task dialog allows other commands to modify the selection while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 216 of file Gui/Placement.h.
isAllowedAlterView()
bool Gui::Dialog::TaskPlacement::isAllowedAlterView () const inline override virtual
Indicates whether this task dialog allows other commands to modify the 3d view while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 214 of file Gui/Placement.h.
open()
void TaskPlacement::open () override virtual
is called by the framework when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 1179 of file Gui/Placement.cpp.
References Gui::Dialog::Placement::open().
placementChanged
void Gui::Dialog::TaskPlacement::placementChanged (const QVariant & , bool , bool) signal
Referenced by slotPlacementChanged().
reject()
bool TaskPlacement::reject () override virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 1212 of file Gui/Placement.cpp.
References Gui::Dialog::Placement::reject().
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
setPlacement()
void TaskPlacement::setPlacement (const Base::Placement & p)
Definition at line 1196 of file Gui/Placement.cpp.
References buildPsets::p, and Gui::Dialog::Placement::setPlacement().
setPlacementAndBindObject()
void TaskPlacement::setPlacementAndBindObject (const App::DocumentObject * obj, const std::string & propertyName)
Definition at line 1173 of file Gui/Placement.cpp.
References propertyName(), and Gui::Dialog::Placement::setPlacementAndBindObject().
setPropertyName()
void TaskPlacement::setPropertyName (const QString & name)
Definition at line 1184 of file Gui/Placement.cpp.
References Gui::Dialog::Placement::setPropertyName().
setSelection()
void TaskPlacement::setSelection (const std::vector< SelectionObject > & selection)
TaskPlacement::setSelection Sets the array of selection objects.
Parameters
selection
Definition at line 1149 of file Gui/Placement.cpp.
References Path.Dressup.Utils::selection(), and Gui::Dialog::Placement::setSelection().
slotPlacementChanged
void TaskPlacement::slotPlacementChanged (const QVariant & p, bool incr, bool data) slot
Definition at line 1201 of file Gui/Placement.cpp.
References buildPsets::p, and placementChanged().
Referenced by TaskPlacement().
The documentation for this class was generated from the following files:
Gui/Placement.h
Gui/Placement.cpp