FreeCAD: geoff_geometry::Vector2d Class Reference
geoff_geometry::Vector2d Class Reference
#include <geometry.h>
Public Member Functions
Vector2d ()
Vector2d (const Vector3d &v)
Vector2d (double x, double y)
Vector2d (const Point &p0, const Point &p1)
Vector2d (const Point *p0, const Point *p1)
Vector2d (const Point &p)
Vector2d (double angle)
Vector2d operator+ (const Vector2d &v) const
Point operator+ (const Point &p) const
Vector2d operator+ (const double d)
const Vector2d & operator+= (const Vector2d &v)
Vector2d operator- (const Vector2d &v) const
const Vector2d & operator-= (const Vector2d &v)
Vector2d operator- (const double d)
const Vector2d operator- (void) const
double operator* (const Vector2d &v) const
Vector2d operator* (double c) const
const Vector2d & operator*= (double c)
Vector2d operator* (int c) const
double operator^ (const Vector2d &v) const
Vector2d operator~ (void) const
bool operator== (const Vector2d &v) const
bool operator!= (const Vector2d &v) const
void get (double xyz[2])
double getx () const
double gety () const
void putx (double x)
void puty (double y)
double normalise ()
double magnitudesqd (void) const
double magnitude (void) const
void Rotate (double cosa, double sina)
void Rotate (double angle)
void Transform (const Matrix &m)
Friends
wostream & operator<< (wostream &op, Vector2d &v)
Detailed Description
Definition at line 383 of file geometry.h.
Constructor & Destructor Documentation
Vector2d() [1/7]
geoff_geometry::Vector2d::Vector2d () inline
Definition at line 392 of file geometry.h.
Vector2d() [2/7]
geoff_geometry::Vector2d::Vector2d (const Vector3d & v)
Definition at line 544 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References geoff_geometry::FAILURE(), geoff_geometry::FEQZ(), and TestSpreadsheet::v.
Vector2d() [3/7]
geoff_geometry::Vector2d::Vector2d (double x, double y) inline
Definition at line 399 of file geometry.h.
References MovieTool::x, and MovieTool::y.
Vector2d() [4/7]
geoff_geometry::Vector2d::Vector2d (const Point & p0, const Point & p1) inline
Definition at line 403 of file geometry.h.
References geoff_geometry::Point::x, and geoff_geometry::Point::y.
Vector2d() [5/7]
geoff_geometry::Vector2d::Vector2d (const Point * p0, const Point * p1) inline
Definition at line 408 of file geometry.h.
References geoff_geometry::Point::x, and geoff_geometry::Point::y.
Vector2d() [6/7]
geoff_geometry::Vector2d::Vector2d (const Point & p) inline
Definition at line 413 of file geometry.h.
References buildPsets::p.
Vector2d() [7/7]
geoff_geometry::Vector2d::Vector2d (double angle) inline
Definition at line 418 of file geometry.h.
References KDL::cos(), DegreesToRadians, and KDL::sin().
Member Function Documentation
get()
void geoff_geometry::Vector2d::get (double xyz[2]) inline
Definition at line 507 of file geometry.h.
Referenced by draftguitools.gui_trackers.editTracker::move().
getx()
double geoff_geometry::Vector2d::getx () const inline
Definition at line 512 of file geometry.h.
Referenced by geoff_geometry::Around(), geoff_geometry::CLine::Bisector(), geoff_geometry::CLine::c(), geoff_geometry::Span::Offset(), geoff_geometry::Parallel(), geoff_geometry::Span::SplitMatrix(), geoff_geometry::Tanto(), and geoff_geometry::CLine::Transform().
gety()
double geoff_geometry::Vector2d::gety () const inline
Definition at line 516 of file geometry.h.
Referenced by geoff_geometry::Around(), geoff_geometry::CLine::c(), geoff_geometry::Span::Offset(), geoff_geometry::Parallel(), geoff_geometry::Span::SplitMatrix(), geoff_geometry::Tanto(), and geoff_geometry::CLine::Transform().
magnitude()
double geoff_geometry::Vector2d::magnitude (void) const inline
Definition at line 543 of file geometry.h.
References KDL::sqrt().
Referenced by ifc4.ifcaxis2placement3d::axistorefdirposition(), geoff_geometry::tangential_arc(), ifc2x3.ifcaxis2placement3d::wr4(), config_control_design.axis2_placement_3d::wr4(), automotive_design.axis2_placement_3d::wr4(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.axis2_placement_3d::wr4().
magnitudesqd()
double geoff_geometry::Vector2d::magnitudesqd (void) const inline
Definition at line 539 of file geometry.h.
Referenced by geoff_geometry::Intof(), and geoff_geometry::LineArcIntof().
normalise()
double geoff_geometry::Vector2d::normalise () inline
Definition at line 528 of file geometry.h.
References test::m, and geoff_geometry::TIGHT_TOLERANCE.
Referenced by geoff_geometry::CLine::Normalise(), geoff_geometry::Span::SetProperties(), and Transform().
operator!=()
bool geoff_geometry::Vector2d::operator!= (const Vector2d & v) const inline
Definition at line 500 of file geometry.h.
References TestSpreadsheet::v.
operator*() [1/3]
double geoff_geometry::Vector2d::operator* (const Vector2d & v) const inline
Definition at line 471 of file geometry.h.
References TestSpreadsheet::v.
operator*() [2/3]
Vector2d geoff_geometry::Vector2d::operator* (double c) const inline
Definition at line 475 of file geometry.h.
References SCL.SimpleDataTypes::c.
operator*() [3/3]
Vector2d geoff_geometry::Vector2d::operator* (int c) const inline
Definition at line 485 of file geometry.h.
References SCL.SimpleDataTypes::c.
operator*=()
const Vector2d& geoff_geometry::Vector2d::operator*= (double c) inline
Definition at line 479 of file geometry.h.
References SCL.SimpleDataTypes::c.
operator+() [1/3]
Vector2d geoff_geometry::Vector2d::operator+ (const double d) inline
Definition at line 440 of file geometry.h.
operator+() [2/3]
Point geoff_geometry::Vector2d::operator+ (const Point & p) const inline
Definition at line 436 of file geometry.h.
References buildPsets::p.
operator+() [3/3]
Vector2d geoff_geometry::Vector2d::operator+ (const Vector2d & v) const inline
Definition at line 432 of file geometry.h.
References TestSpreadsheet::v.
operator+=()
const Vector2d& geoff_geometry::Vector2d::operator+= (const Vector2d & v) inline
Definition at line 445 of file geometry.h.
References TestSpreadsheet::v.
operator-() [1/3]
Vector2d geoff_geometry::Vector2d::operator- (const double d) inline
Definition at line 461 of file geometry.h.
operator-() [2/3]
Vector2d geoff_geometry::Vector2d::operator- (const Vector2d & v) const inline
Definition at line 451 of file geometry.h.
References TestSpreadsheet::v.
operator-() [3/3]
const Vector2d geoff_geometry::Vector2d::operator- (void) const inline
Definition at line 466 of file geometry.h.
operator-=()
const Vector2d& geoff_geometry::Vector2d::operator-= (const Vector2d & v) inline
Definition at line 455 of file geometry.h.
References TestSpreadsheet::v.
operator==()
bool geoff_geometry::Vector2d::operator== (const Vector2d & v) const
Definition at line 553 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References geoff_geometry::FEQ(), and TestSpreadsheet::v.
operator^()
double geoff_geometry::Vector2d::operator^ (const Vector2d & v) const inline
Definition at line 490 of file geometry.h.
References TestSpreadsheet::v.
operator~()
Vector2d geoff_geometry::Vector2d::operator~ (void) const inline
Definition at line 494 of file geometry.h.
putx()
void geoff_geometry::Vector2d::putx (double x) inline
Definition at line 520 of file geometry.h.
References MovieTool::x.
puty()
void geoff_geometry::Vector2d::puty (double y) inline
Definition at line 524 of file geometry.h.
References MovieTool::y.
Rotate() [1/2]
void geoff_geometry::Vector2d::Rotate (double angle) inline
Definition at line 553 of file geometry.h.
References KDL::cos(), geoff_geometry::FEQZ(), and KDL::sin().
Rotate() [2/2]
void geoff_geometry::Vector2d::Rotate (double cosa, double sina) inline
Definition at line 547 of file geometry.h.
Transform()
void geoff_geometry::Vector2d::Transform (const Matrix & m)
Definition at line 558 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References test::m, and normalise().
Friends And Related Function Documentation
operator<<
wostream& operator<< (wostream & op, Vector2d & v) friend
Definition at line 120 of file Construction.cpp.
The documentation for this class was generated from the following files:
geometry.h
Mod/CAM/libarea/kurve/Matrix.cpp