FreeCAD: Gui::ExpressionWidget Class Reference
Gui::ExpressionWidget Class Reference
#include <ExpressionBinding.h>
Public Member Functions
ExpressionWidget ()
QPixmap getIcon (const char *name, const QSize &size) const
Public Member Functions inherited from Gui::ExpressionBinding
ExpressionBinding ()
virtual ~ExpressionBinding ()
virtual void bind (const App::ObjectIdentifier &_path)
virtual void bind (const App::Property &prop)
bool isBound () const
void unbind ()
virtual bool apply (const std::string &propName)
virtual bool apply ()
bool hasExpression () const
bool autoApply () const
void setAutoApply (bool value)
Protected Member Functions
void makeLabel (QLineEdit *parent)
Protected Member Functions inherited from Gui::ExpressionBinding
const App::ObjectIdentifier & getPath () const
std::shared_ptr< App::Expression > getExpression () const
std::string getExpressionString (bool no_throw=true) const
std::string getEscapedExpressionString () const
bool assignToProperty (const std::string &propName, double)
virtual void setExpression (std::shared_ptr< App::Expression > expr)
virtual void onChange ()
void expressionChange (const App::ObjectIdentifier &id)
void objectDeleted (const App::DocumentObject &)
Protected Attributes
ExpressionLabel * iconLabel {nullptr}
QPalette defaultPalette
int iconHeight {-1}
Protected Attributes inherited from Gui::ExpressionBinding
boost::signals2::scoped_connection expressionchanged
boost::signals2::scoped_connection objectdeleted
bool m_autoApply {false}
Detailed Description
Definition at line 84 of file ExpressionBinding.h.
Constructor & Destructor Documentation
ExpressionWidget()
ExpressionWidget::ExpressionWidget () default
Member Function Documentation
getIcon()
QPixmap ExpressionWidget::getIcon (const char * name, const QSize & size) const
Definition at line 282 of file ExpressionBinding.cpp.
References Gui::BitmapFactory(), DraftVecUtils::find(), AssemblyImport::insert(), and Gui::BitmapFactoryInst::pixmapFromSvg().
Referenced by Gui::ExpressionSpinBox::clearExpression(), makeLabel(), Gui::ExpLineEdit::resizeEvent(), Gui::ExpressionSpinBox::showValidExpression(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchWindow._ArchWindowTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), bimcommands.BimClassification.BIM_Classification::updateByMaterial(), bimcommands.BimClassification.BIM_Classification::updateByTree(), bimcommands.BimClassification.BIM_Classification::updateByType(), and bimcommands.BimClassification.BIM_Classification::updateDefault().
makeLabel()
void ExpressionWidget::makeLabel (QLineEdit * parent) protected
Definition at line 298 of file ExpressionBinding.cpp.
References defaultPalette, getIcon(), iconHeight, iconLabel, and ExpressionLabel::setExpressionText().
Referenced by Gui::ExpLineEdit::ExpLineEdit(), and Gui::ExpressionSpinBox::ExpressionSpinBox().
Member Data Documentation
defaultPalette
QPalette Gui::ExpressionWidget::defaultPalette protected
Definition at line 95 of file ExpressionBinding.h.
Referenced by Gui::ExpressionSpinBox::clearExpression(), makeLabel(), and Gui::ExpLineEdit::resizeEvent().
iconHeight
int Gui::ExpressionWidget::iconHeight {-1} protected
Definition at line 96 of file ExpressionBinding.h.
Referenced by Gui::ExpressionSpinBox::clearExpression(), makeLabel(), Gui::ExpLineEdit::resizeEvent(), Gui::ExpressionSpinBox::showValidExpression(), and Gui::QuantitySpinBox::sizeForText().
iconLabel
ExpressionLabel* Gui::ExpressionWidget::iconLabel {nullptr} protected
Definition at line 94 of file ExpressionBinding.h.
Referenced by Gui::ExpLineEdit::bind(), Gui::ExpressionSpinBox::clearExpression(), Gui::ExpLineEdit::ExpLineEdit(), Gui::ExpressionSpinBox::ExpressionSpinBox(), Gui::InputField::InputField(), makeLabel(), Gui::InputField::newInput(), Gui::InputField::resizeEvent(), Gui::ExpLineEdit::resizeEvent(), Gui::ExpressionSpinBox::resizeWidget(), Gui::ExpLineEdit::setExpression(), Gui::ExpressionSpinBox::showIcon(), Gui::QuantitySpinBox::showIcon(), Gui::ExpressionSpinBox::showInvalidExpression(), Gui::ExpressionSpinBox::showValidExpression(), and Gui::InputField::updateIconLabel().
The documentation for this class was generated from the following files:
ExpressionBinding.h
ExpressionBinding.cpp