FreeCAD: Gui::Dialog::DlgCustomToolbarsImp Class Reference
Gui::Dialog::DlgCustomToolbarsImp Class Reference
#include <DlgToolbarsImp.h>
Public Member Functions
DlgCustomToolbarsImp (QWidget *parent=nullptr)
~DlgCustomToolbarsImp () override
Public Member Functions inherited from Gui::Dialog::DlgCustomToolbars
void activateWorkbenchBox (int index)
Public Member Functions inherited from Gui::Dialog::CustomizeActionPage
CustomizeActionPage (QWidget *parent=nullptr)
~CustomizeActionPage () override
Protected Member Functions
void showEvent (QShowEvent *e) override
void changeEvent (QEvent *e) override
void addCustomToolbar (const QString &) override
void removeCustomToolbar (const QString &) override
void renameCustomToolbar (const QString &, const QString &) override
void addCustomCommand (const QString &, const QByteArray &) override
void removeCustomCommand (const QString &, const QByteArray &) override
void moveUpCustomCommand (const QString &, const QByteArray &) override
void moveDownCustomCommand (const QString &, const QByteArray &) override
Protected Member Functions inherited from Gui::Dialog::DlgCustomToolbars
DlgCustomToolbars (Type, QWidget *parent=nullptr)
~DlgCustomToolbars () override
void setupConnections ()
void onWorkbenchBoxActivated (int index)
void onMoveActionRightButtonClicked ()
void onMoveActionLeftButtonClicked ()
void onMoveActionUpButtonClicked ()
void onMoveActionDownButtonClicked ()
void onNewButtonClicked ()
void onRenameButtonClicked ()
void onDeleteButtonClicked ()
void hideEvent (QHideEvent *event) override
void onActivateCategoryBox ()
Protected Member Functions inherited from Gui::Dialog::CustomizeActionPage
bool event (QEvent *e) override
Additional Inherited Members
Protected Types inherited from Gui::Dialog::DlgCustomToolbars
enum Type { Toolbar, Toolboxbar }
Protected Slots inherited from Gui::Dialog::DlgCustomToolbars
void onAddMacroAction (const QByteArray &) override
void onRemoveMacroAction (const QByteArray &) override
void onModifyMacroAction (const QByteArray &) override
Protected Slots inherited from Gui::Dialog::CustomizeActionPage
virtual void onAddMacroAction (const QByteArray &)=0
virtual void onRemoveMacroAction (const QByteArray &)=0
virtual void onModifyMacroAction (const QByteArray &)=0
Protected Attributes inherited from Gui::Dialog::DlgCustomToolbars
std::unique_ptr< Ui_DlgCustomToolbars > ui
Detailed Description
This class implements the creation of user defined toolbars.
See also
DlgCustomToolbars
DlgCustomCmdbarsImp
Author
Werner Mayer
Definition at line 102 of file DlgToolbarsImp.h.
Constructor & Destructor Documentation
DlgCustomToolbarsImp()
DlgCustomToolbarsImp::DlgCustomToolbarsImp (QWidget * parent = nullptr) explicit
Constructs a DlgCustomToolbarsImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
Definition at line 597 of file DlgToolbarsImp.cpp.
~DlgCustomToolbarsImp()
DlgCustomToolbarsImp::~DlgCustomToolbarsImp () override default
Destroys the object and frees any allocated resources
Member Function Documentation
addCustomCommand()
void DlgCustomToolbarsImp::addCustomCommand (const QString & name, const QByteArray & cmd) override protected virtual
Reimplemented from Gui::Dialog::DlgCustomToolbars.
Definition at line 690 of file DlgToolbarsImp.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::WorkbenchManager::active(), Gui::CommandManager::addTo(), Gui::Application::commandManager(), Gui::getMainWindow(), Gui::WorkbenchManager::instance(), Gui::Application::Instance, Gui::Dialog::DlgCustomToolbars::ui, and src.Mod.PartDesign.fcgear.svggear::w.
addCustomToolbar()
void DlgCustomToolbarsImp::addCustomToolbar (const QString & name) override protected virtual
Reimplemented from Gui::Dialog::DlgCustomToolbars.
Definition at line 604 of file DlgToolbarsImp.cpp.
References Gui::WorkbenchManager::active(), Gui::getMainWindow(), Gui::WorkbenchManager::instance(), Gui::Dialog::DlgCustomToolbars::ui, and src.Mod.PartDesign.fcgear.svggear::w.
changeEvent()
void DlgCustomToolbarsImp::changeEvent (QEvent * e) override protected virtual
Reimplemented from Gui::Dialog::DlgCustomToolbars.
Definition at line 858 of file DlgToolbarsImp.cpp.
References Gui::Dialog::DlgCustomToolbars::changeEvent(), and SCL.SimpleDataTypes::e.
moveDownCustomCommand()
void DlgCustomToolbarsImp::moveDownCustomCommand (const QString & name, const QByteArray & userdata) override protected virtual
Reimplemented from Gui::Dialog::DlgCustomToolbars.
Definition at line 794 of file DlgToolbarsImp.cpp.
References Gui::WorkbenchManager::active(), Gui::getMainWindow(), toolbit-attributes::group, Gui::WorkbenchManager::instance(), Gui::Dialog::DlgCustomToolbars::ui, and src.Mod.PartDesign.fcgear.svggear::w.
moveUpCustomCommand()
void DlgCustomToolbarsImp::moveUpCustomCommand (const QString & name, const QByteArray & userdata) override protected virtual
Reimplemented from Gui::Dialog::DlgCustomToolbars.
Definition at line 751 of file DlgToolbarsImp.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::WorkbenchManager::active(), Gui::getMainWindow(), toolbit-attributes::group, Gui::WorkbenchManager::instance(), Gui::Dialog::DlgCustomToolbars::ui, and src.Mod.PartDesign.fcgear.svggear::w.
removeCustomCommand()
void DlgCustomToolbarsImp::removeCustomCommand (const QString & name, const QByteArray & userdata) override protected virtual
Reimplemented from Gui::Dialog::DlgCustomToolbars.
Definition at line 719 of file DlgToolbarsImp.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::WorkbenchManager::active(), Gui::getMainWindow(), Gui::WorkbenchManager::instance(), Gui::Dialog::DlgCustomToolbars::ui, and src.Mod.PartDesign.fcgear.svggear::w.
removeCustomToolbar()
void DlgCustomToolbarsImp::removeCustomToolbar (const QString & name) override protected virtual
Reimplemented from Gui::Dialog::DlgCustomToolbars.
Definition at line 614 of file DlgToolbarsImp.cpp.
References Gui::WorkbenchManager::active(), Gui::getMainWindow(), Gui::WorkbenchManager::instance(), Gui::Dialog::DlgCustomToolbars::ui, and src.Mod.PartDesign.fcgear.svggear::w.
renameCustomToolbar()
void DlgCustomToolbarsImp::renameCustomToolbar (const QString & old_name, const QString & new_name) override protected virtual
Reimplemented from Gui::Dialog::DlgCustomToolbars.
Definition at line 630 of file DlgToolbarsImp.cpp.
References Gui::WorkbenchManager::active(), Gui::getMainWindow(), Gui::WorkbenchManager::instance(), Gui::MainWindow::setWindowTitle(), Gui::Dialog::DlgCustomToolbars::ui, and src.Mod.PartDesign.fcgear.svggear::w.
showEvent()
void DlgCustomToolbarsImp::showEvent (QShowEvent * e) override protected
Definition at line 847 of file DlgToolbarsImp.cpp.
References Gui::Dialog::CustomizeActionPage::event(), and Gui::Dialog::DlgCustomToolbars::ui.
The documentation for this class was generated from the following files:
DlgToolbarsImp.h
DlgToolbarsImp.cpp