FreeCAD: WireJoiner.cpp File Reference
WireJoiner.cpp File Reference
#include "PreCompiled.h"
#include <boost/core/ignore_unused.hpp>
#include <boost/geometry/geometries/register/point.hpp>
#include <boost/graph/graph_concepts.hpp>
#include <BRepLib.hxx>
#include <BRep_Builder.hxx>
#include <BRep_Tool.hxx>
#include <BRepBndLib.hxx>
#include <BRepBuilderAPI_Copy.hxx>
#include <BRepBuilderAPI_MakeEdge.hxx>
#include <BRepBuilderAPI_MakeWire.hxx>
#include <BRepBuilderAPI_MakeFace.hxx>
#include <BRepClass_FaceClassifier.hxx>
#include <BRepExtrema_DistShapeShape.hxx>
#include <BRepGProp.hxx>
#include <BRepTools.hxx>
#include <BRepTools_WireExplorer.hxx>
#include <gp_Pln.hxx>
#include <GeomAdaptor_Curve.hxx>
#include <GeomLProp_CLProps.hxx>
#include <GProp_GProps.hxx>
#include <ShapeAnalysis_Wire.hxx>
#include <ShapeFix_ShapeTolerance.hxx>
#include <ShapeExtend_WireData.hxx>
#include <ShapeFix_Wire.hxx>
#include <ShapeFix_Shape.hxx>
#include <TopExp.hxx>
#include <TopExp_Explorer.hxx>
#include <TopTools_HSequenceOfShape.hxx>
#include <BRepTools_History.hxx>
#include <ShapeBuild_ReShape.hxx>
#include <unordered_map>
#include <unordered_set>
#include <deque>
#include <boost_geometry.hpp>
#include <utility>
#include <Base/Console.h>
#include <Base/Exception.h>
#include <Base/Tools.h>
#include <Base/Sequencer.h>
#include <Base/Parameter.h>
#include <App/Application.h>
#include "WireJoiner.h"
#include "Geometry.h"
#include "PartFeature.h"
#include "TopoShapeOpCode.h"
#include "TopoShapeMapper.h"
Classes
class WireJoiner::WireJoinerP
struct WireJoiner::WireJoinerP::EdgeInfo
struct WireJoiner::WireJoinerP::VectorSet< T >
struct WireJoiner::WireJoinerP::VertexInfo
struct WireJoiner::WireJoinerP::StackInfo
struct WireJoiner::WireJoinerP::WireInfo
struct WireJoiner::WireJoinerP::EdgeSet
struct WireJoiner::WireJoinerP::WireSet
struct WireJoiner::WireJoinerP::PntGetter
struct WireJoiner::WireJoinerP::BoxGetter
struct WireJoiner::WireJoinerP::IntersectInfo
struct WireJoiner::WireJoinerP::SplitInfo
Typedefs
using RParameters = bgi::linear< RParametersNumber >
Functions
BOOST_GEOMETRY_REGISTER_POINT_3D_GET_SET (gp_Pnt, double, bg::cs::cartesian, X, Y, Z, SetX, SetY, SetZ) using namespace Part
static void getEndPoints (const TopoDS_Edge &eForEndPoints, gp_Pnt &p1, gp_Pnt &p2)
static void getEndPoints (const TopoDS_Wire &wire, gp_Pnt &p1, gp_Pnt &p2)
Variables
const size_t RParametersNumber = 16UL
Typedef Documentation
RParameters
using RParameters = bgi::linear<RParametersNumber>
Definition at line 83 of file WireJoiner.cpp.
Function Documentation
BOOST_GEOMETRY_REGISTER_POINT_3D_GET_SET()
BOOST_GEOMETRY_REGISTER_POINT_3D_GET_SET (gp_Pnt , double , bg::cs::cartesian , X , Y , Z , SetX , SetY , SetZ)
getEndPoints() [1/2]
static void getEndPoints (const TopoDS_Edge & eForEndPoints, gp_Pnt & p1, gp_Pnt & p2) inline static
Definition at line 92 of file WireJoiner.cpp.
References FirstVertex(), and LastVertex().
Referenced by WireJoiner::WireJoinerP::add(), and WireJoiner::WireJoinerP::checkIntersectionMakeWire().
getEndPoints() [2/2]
static void getEndPoints (const TopoDS_Wire & wire, gp_Pnt & p1, gp_Pnt & p2) inline static
Definition at line 97 of file WireJoiner.cpp.
Variable Documentation
RParametersNumber
const size_t RParametersNumber = 16UL
Definition at line 82 of file WireJoiner.cpp.