FreeCAD: Base::UnitsSchema Class Reference
Base::UnitsSchema Class Reference abstract
#include <UnitsSchema.h>
Public Member Functions
UnitsSchema ()=default
UnitsSchema (const UnitsSchema &)=default
UnitsSchema (UnitsSchema &&)=default
UnitsSchema & operator= (const UnitsSchema &)=default
UnitsSchema & operator= (UnitsSchema &&)=default
virtual ~UnitsSchema ()=default
virtual void setSchemaUnits ()
virtual void resetSchemaUnits ()
If you use setSchemaUnits() you also have to impment this method to undo your changes!
virtual std::string schemaTranslate (const Base::Quantity &quant, double &factor, std::string &unitString)=0
This method translates the quantity in a string as the user may expect it.
std::string toLocale (const Base::Quantity &quant, double factor, const std::string &unitString) const
virtual bool isMultiUnitLength () const
virtual bool isMultiUnitAngle () const
virtual std::string getBasicLengthUnit () const
Detailed Description
The UnitSchema class The subclasses of this class define the stuff for a certain units schema.
Definition at line 74 of file UnitsSchema.h.
Constructor & Destructor Documentation
UnitsSchema() [1/3]
Base::UnitsSchema::UnitsSchema () default
UnitsSchema() [2/3]
Base::UnitsSchema::UnitsSchema (const UnitsSchema &) default
UnitsSchema() [3/3]
Base::UnitsSchema::UnitsSchema (UnitsSchema &&) default
~UnitsSchema()
virtual Base::UnitsSchema::~UnitsSchema () virtual default
Member Function Documentation
getBasicLengthUnit()
virtual std::string Base::UnitsSchema::getBasicLengthUnit () const inline virtual
Reimplemented in Base::UnitsSchemaImperialCivil, Base::UnitsSchemaImperialBuilding, Base::UnitsSchemaMeterDecimal, Base::UnitsSchemaCentimeters, Base::UnitsSchemaImperial1, and Base::UnitsSchemaImperialDecimal.
Definition at line 113 of file UnitsSchema.h.
isMultiUnitAngle()
virtual bool Base::UnitsSchema::isMultiUnitAngle () const inline virtual
Reimplemented in Base::UnitsSchemaImperialCivil.
Definition at line 107 of file UnitsSchema.h.
isMultiUnitLength()
virtual bool Base::UnitsSchema::isMultiUnitLength () const inline virtual
Reimplemented in Base::UnitsSchemaImperialBuilding.
Definition at line 101 of file UnitsSchema.h.
operator=() [1/2]
UnitsSchema& Base::UnitsSchema::operator= (const UnitsSchema &) default
operator=() [2/2]
UnitsSchema& Base::UnitsSchema::operator= (UnitsSchema &&) default
resetSchemaUnits()
virtual void Base::UnitsSchema::resetSchemaUnits () inline virtual
If you use setSchemaUnits() you also have to impment this method to undo your changes!
Definition at line 90 of file UnitsSchema.h.
schemaTranslate()
virtual std::string Base::UnitsSchema::schemaTranslate (const Base::Quantity & quant, double & factor, std::string & unitString) pure virtual
This method translates the quantity in a string as the user may expect it.
Implemented in Base::UnitsSchemaImperialCivil, Base::UnitsSchemaImperialBuilding, Base::UnitsSchemaFemMilliMeterNewton, Base::UnitsSchemaMeterDecimal, Base::UnitsSchemaInternal, Base::UnitsSchemaMmMin, Base::UnitsSchemaImperial1, Base::UnitsSchemaCentimeters, Base::UnitsSchemaMKS, and Base::UnitsSchemaImperialDecimal.
Referenced by Base::Quantity::getUserString().
setSchemaUnits()
virtual void Base::UnitsSchema::setSchemaUnits () inline virtual
Gets called if this schema gets activated. Here it's theoretically possible that you can change the static factors for certain units (e.g. mi = 1,8km instead of mi=1.6km).
Definition at line 87 of file UnitsSchema.h.
toLocale()
std::string UnitsSchema::toLocale (const Base::Quantity & quant, double factor, const std::string & unitString) const
Definition at line 35 of file UnitsSchema.cpp.
References Base::Quantity::getFormat(), Base::Quantity::getValue(), Base::QuantityFormat::None, Base::QuantityFormat::option, Base::QuantityFormat::precision, and Base::QuantityFormat::toFormat().
Referenced by Base::UnitsSchemaImperialDecimal::schemaTranslate(), Base::UnitsSchemaCentimeters::schemaTranslate(), Base::UnitsSchemaMKS::schemaTranslate(), Base::UnitsSchemaImperial1::schemaTranslate(), Base::UnitsSchemaMmMin::schemaTranslate(), Base::UnitsSchemaInternal::schemaTranslate(), Base::UnitsSchemaFemMilliMeterNewton::schemaTranslate(), Base::UnitsSchemaMeterDecimal::schemaTranslate(), Base::UnitsSchemaImperialBuilding::schemaTranslate(), and Base::UnitsSchemaImperialCivil::schemaTranslate().
The documentation for this class was generated from the following files:
UnitsSchema.h
UnitsSchema.cpp