FreeCAD: Part::PrismExtension Class Reference
Part::PrismExtension Class Reference
#include <PrismExtension.h>
Public Member Functions
PrismExtension ()
~PrismExtension () override
TopoDS_Shape makePrism (double height, const TopoDS_Face &face) const
short int extensionMustExecute () override
App::DocumentObjectExecReturn * extensionExecute () override
Public Member Functions inherited from App::DocumentObjectExtension
virtual Base::Type getExtensionTypeId (void) const override
DocumentObjectExtension ()
~DocumentObjectExtension () override
App::DocumentObject * getExtendedObject ()
const App::DocumentObject * getExtendedObject () const
virtual void onExtendedSettingDocument ()
get called after setting the document
virtual void onExtendedDocumentRestored ()
get called after a document has been fully restored
virtual void onExtendedSetupObject ()
get called after a brand new object was created
virtual void onExtendedUnsetupObject ()
get called when object is going to be removed from the document
PyObject * getExtensionPyObject () override
virtual const char * getViewProviderExtensionName () const
virtual bool extensionGetSubObject (DocumentObject *&ret, const char *subname, PyObject **pyObj, Base::Matrix4D *mat, bool transform, int depth) const
virtual bool extensionGetSubObjects (std::vector< std::string > &ret, int reason) const
virtual bool extensionGetLinkedObject (DocumentObject *&ret, bool recursive, Base::Matrix4D *mat, bool transform, int depth) const
virtual int extensionSetElementVisible (const char *, bool)
virtual int extensionIsElementVisible (const char *)
virtual bool extensionHasChildElement () const
Public Member Functions inherited from App::Extension
Extension ()=default
virtual ~Extension ()
virtual void initExtension (App::ExtensionContainer *obj)
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Public Attributes
App::PropertyAngle FirstAngle
App::PropertyAngle SecondAngle
Protected Member Functions
void extensionOnChanged (const App::Property *) override
Protected Member Functions inherited from App::DocumentObjectExtension
virtual const App::PropertyData & extensionGetPropertyData (void) const override
Protected Member Functions inherited from App::Extension
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
returns true if the property name change was handled by the extension.
virtual bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
returns true if the property type change was handled by the extension.
void initExtensionType (Base::Type type)
Additional Inherited Members
Static Public Member Functions inherited from App::DocumentObjectExtension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Static Public Member Functions inherited from App::Extension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Static Protected Member Functions inherited from App::DocumentObjectExtension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
Static Protected Member Functions inherited from App::Extension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Detailed Description
Definition at line 56 of file PrismExtension.h.
Constructor & Destructor Documentation
PrismExtension()
PrismExtension::PrismExtension ()
Definition at line 37 of file PrismExtension.cpp.
References EXTENSION_ADD_PROPERTY_TYPE, SCL.SimpleDataTypes::f, App::DocumentObjectExtension::getExtensionClassTypeId(), and App::Prop_None.
~PrismExtension()
PrismExtension::~PrismExtension () override default
Member Function Documentation
extensionExecute()
App::DocumentObjectExecReturn * PrismExtension::extensionExecute () override virtual
Reimplemented from App::DocumentObjectExtension.
Definition at line 60 of file PrismExtension.cpp.
References App::DocumentObjectExtension::extensionExecute().
extensionMustExecute()
short int PrismExtension::extensionMustExecute () override virtual
Reimplemented from App::DocumentObjectExtension.
Definition at line 51 of file PrismExtension.cpp.
References FirstAngle, App::Property::isTouched(), and SecondAngle.
extensionOnChanged()
void PrismExtension::extensionOnChanged (const App::Property * prop) override protected virtual
Reimplemented from App::Extension.
Definition at line 65 of file PrismExtension.cpp.
References App::Extension::extensionOnChanged().
makePrism()
TopoDS_Shape PrismExtension::makePrism (double height, const TopoDS_Face & face) const
Definition at line 70 of file PrismExtension.cpp.
References FirstAngle, App::PropertyQuantity::getValue(), SecondAngle, and KDL::tan().
Referenced by PartDesign::Cylinder::execute(), Part::Cylinder::execute(), Part::Prism::execute(), and PartDesign::Prism::execute().
Member Data Documentation
FirstAngle
App::PropertyAngle Part::PrismExtension::FirstAngle
Definition at line 84 of file PrismExtension.h.
Referenced by PartGui::CylinderPrimitive::changeValue(), PartGui::PrismPrimitive::changeValue(), PartGui::CylinderPrimitive::CylinderPrimitive(), extensionMustExecute(), makePrism(), and PartGui::PrismPrimitive::PrismPrimitive().
SecondAngle
App::PropertyAngle Part::PrismExtension::SecondAngle
Definition at line 85 of file PrismExtension.h.
Referenced by PartGui::CylinderPrimitive::changeValue(), PartGui::PrismPrimitive::changeValue(), PartGui::CylinderPrimitive::CylinderPrimitive(), extensionMustExecute(), makePrism(), and PartGui::PrismPrimitive::PrismPrimitive().
The documentation for this class was generated from the following files:
PrismExtension.h
PrismExtension.cpp