FreeCAD: Base::Matrix4D Class Reference
Base::Matrix4D Class Reference
#include <Matrix.h>
Public Member Functions
Matrix4D ()
Default constructor.
Matrix4D (float a11, float a12, float a13, float a14, float a21, float a22, float a23, float a24, float a31, float a32, float a33, float a34, float a41, float a42, float a43, float a44)
Construction.
Matrix4D (double a11, double a12, double a13, double a14, double a21, double a22, double a23, double a24, double a31, double a32, double a33, double a34, double a41, double a42, double a43, double a44)
Construction.
Matrix4D (const Matrix4D &mat)
Construction.
Matrix4D (const Vector3f &rclBase, const Vector3f &rclDir, float fAngle)
Construction with an Axis.
Matrix4D (const Vector3d &rclBase, const Vector3d &rclDir, double fAngle)
~Matrix4D ()=default
Destruction.
Operators
Matrix4D operator+ (const Matrix4D &mat) const
Matrix addition.
Matrix4D & operator+= (const Matrix4D &mat)
Matrix4D operator- (const Matrix4D &mat) const
Matrix subtraction.
Matrix4D & operator-= (const Matrix4D &mat)
Matrix4D & operator*= (const Matrix4D &mat)
Matrix multiplication.
Matrix4D & operator= (const Matrix4D &mat)
Assignment.
Matrix4D operator* (const Matrix4D &mat) const
Matrix multiplication.
Vector3f operator* (const Vector3f &vec) const
Multiplication matrix with vector.
Vector3d operator* (const Vector3d &vec) const
void multVec (const Vector3d &src, Vector3d &dst) const
void multVec (const Vector3f &src, Vector3f &dst) const
Matrix4D operator* (double scalar) const
Matrix4D & operator*= (double scalar)
bool operator!= (const Matrix4D &mat) const
Comparison.
bool operator== (const Matrix4D &mat) const
Comparison.
double * operator[] (unsigned short usNdx)
Index operator.
const double * operator[] (unsigned short usNdx) const
Index operator.
Vector3d getRow (unsigned short usNdx) const
Get vector of row.
Vector3d getCol (unsigned short usNdx) const
Get vector of column.
Vector3d diagonal () const
Get vector of diagonal.
double trace3 () const
Get trace of the 3x3 matrix.
double trace () const
Get trace of the 4x4 matrix.
void setRow (unsigned short usNdx, const Vector3d &vec)
Set row to vector.
void setCol (unsigned short usNdx, const Vector3d &vec)
Set column to vector.
void setDiagonal (const Vector3d &vec)
Set diagonal to vector.
double determinant () const
Compute the determinant of the matrix.
double determinant3 () const
Compute the determinant of the 3x3 sub-matrix.
std::string analyse () const
Analyse the transformation.
Matrix4D & Outer (const Vector3f &rV1, const Vector3f &rV2)
Outer product (Dyadic product)
Matrix4D & Outer (const Vector3d &rV1, const Vector3d &rV2)
Matrix4D & Hat (const Vector3f &rV)
Hat operator (skew symmetric)
Matrix4D & Hat (const Vector3d &rV)
void getMatrix (double dMtrx[16]) const
void setMatrix (const double dMtrx[16])
void getGLMatrix (double dMtrx[16]) const
get the matrix in OpenGL style
void setGLMatrix (const double dMtrx[16])
set the matrix in OpenGL style
unsigned long getMemSpace ()
Manipulation
void setToUnity ()
Makes unity matrix.
bool isUnity () const
Checks if this is the unit matrix.
bool isUnity (double tol) const
Checks if this is the unit matrix.
void nullify ()
Makes a null matrix.
bool isNull () const
Checks if this is the null matrix.
void move (float x, float y, float z)
moves the coordinatesystem for the x,y,z value
void move (double x, double y, double z)
void move (const Vector3f &vec)
moves the coordinatesystem for the vector
void move (const Vector3d &vec)
void scale (float x, float y, float z)
scale for the vector
void scale (double x, double y, double z)
void scale (const Vector3f &vec)
scale for the x,y,z value
void scale (const Vector3d &vec)
void scale (float scalexyz)
uniform scale
void scale (double scalexyz)
ScaleType hasScale (double tol=0.0) const
Check for scaling factor.
std::array< Matrix4D, 4 > decompose () const
Decompose matrix into pure shear, scale, rotation and move.
void rotX (double fAngle)
Rotate around the X axis (in transformed space) for the given value in radians.
void rotY (double fAngle)
Rotate around the Y axis (in transformed space) for the given value in radians.
void rotZ (double fAngle)
Rotate around the Z axis (in transformed space) for the given value in radians.
void rotLine (const Vector3f &vec, float fAngle)
Rotate around an arbitrary axis passing the origin in radians.
void rotLine (const Vector3d &vec, double fAngle)
Rotate around an arbitrary axis passing the origin in radians.
void rotLine (const Vector3f &rclBase, const Vector3f &rclDir, float fAngle)
Rotate around an arbitrary axis that needn't necessarily pass the origin in radians.
void rotLine (const Vector3d &rclBase, const Vector3d &rclDir, double fAngle)
Rotate around an arbitrary axis that needn't necessarily pass the origin in radians.
bool toAxisAngle (Vector3f &rclBase, Vector3f &rclDir, float &fAngle, float &fTranslation) const
Extract the rotation axis and angle. Therefore the 3x3 submatrix must be orthogonal.
bool toAxisAngle (Vector3d &rclBase, Vector3d &rclDir, double &fAngle, double &fTranslation) const
void transform (const Vector3f &vec, const Matrix4D &mat)
transform (move,scale,rotate) around a point
void transform (const Vector3d &vec, const Matrix4D &mat)
void inverse ()
Matrix is expected to have a 3x3 rotation submatrix.
void inverseOrthogonal ()
Matrix is expected to have a 3x3 rotation submatrix.
void inverseGauss ()
Arbitrary, non-singular matrix.
void transpose ()
void Print () const
std::string toString () const
write the 16 double of the matrix into a string
void fromString (const std::string &str)
read the 16 double of the matrix from a string
Detailed Description
The Matrix4D class.
Definition at line 71 of file Matrix.h.
Constructor & Destructor Documentation
Matrix4D() [1/6]
Matrix4D::Matrix4D ()
Default constructor.
Initialises to an identity matrix
Definition at line 37 of file Base/Matrix.cpp.
Referenced by getMemSpace().
Matrix4D() [2/6]
Matrix4D::Matrix4D (float a11, float a12, float a13, float a14, float a21, float a22, float a23, float a24, float a31, float a32, float a33, float a34, float a41, float a42, float a43, float a44)
Construction.
Definition at line 44 of file Base/Matrix.cpp.
Matrix4D() [3/6]
Matrix4D::Matrix4D (double a11, double a12, double a13, double a14, double a21, double a22, double a23, double a24, double a31, double a32, double a33, double a34, double a41, double a42, double a43, double a44)
Construction.
Definition at line 54 of file Base/Matrix.cpp.
Matrix4D() [4/6]
Matrix4D::Matrix4D (const Matrix4D & mat)
Construction.
Definition at line 65 of file Base/Matrix.cpp.
Matrix4D() [5/6]
Matrix4D::Matrix4D (const Vector3f & rclBase, const Vector3f & rclDir, float fAngle)
Construction with an Axis.
Definition at line 71 of file Base/Matrix.cpp.
References rotLine().
Matrix4D() [6/6]
Matrix4D::Matrix4D (const Vector3d & rclBase, const Vector3d & rclDir, double fAngle)
Definition at line 77 of file Base/Matrix.cpp.
References rotLine().
~Matrix4D()
Base::Matrix4D::~Matrix4D () default
Destruction.
Member Function Documentation
analyse()
std::string Matrix4D::analyse () const
Analyse the transformation.
Definition at line 751 of file Base/Matrix.cpp.
References determinant(), SplineSurface::i, KDL::sqrt(), and transpose().
decompose()
std::array< Matrix4D, 4 > Matrix4D::decompose () const
Decompose matrix into pure shear, scale, rotation and move.
Definition at line 955 of file Base/Matrix.cpp.
References KDL::abs(), Base::Vector3< float_type >::Cross(), D_PI, SCL.SimpleDataTypes::e, getCol(), SplineSurface::i, inverseGauss(), Base::Vector3< float_type >::IsNull(), move(), Base::Vector3< float_type >::Normalize(), rotZ(), and setCol().
determinant()
double Matrix4D::determinant () const
Compute the determinant of the matrix.
Definition at line 163 of file Base/Matrix.cpp.
Referenced by analyse().
determinant3()
double Matrix4D::determinant3 () const
Compute the determinant of the 3x3 sub-matrix.
Definition at line 181 of file Base/Matrix.cpp.
References CAMTests.TestPathVoronoi::vd.
Referenced by Part::TopoShape::_makeTransform(), and hasScale().
diagonal()
Vector3d Base::Matrix4D::diagonal () const inline
Get vector of diagonal.
Definition at line 467 of file Matrix.h.
fromString()
void Matrix4D::fromString (const std::string & str)
read the 16 double of the matrix from a string
Definition at line 736 of file Base/Matrix.cpp.
References SplineSurface::i, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by Points::PropertyPointKernel::Restore().
getCol()
Vector3d Base::Matrix4D::getCol (unsigned short usNdx) const inline
Get vector of column.
Definition at line 462 of file Matrix.h.
References SurfaceTests.TestBlendCurve::vec.
Referenced by decompose(), and hasScale().
getGLMatrix()
void Matrix4D::getGLMatrix (double dMtrx[16]) const
get the matrix in OpenGL style
Definition at line 670 of file Base/Matrix.cpp.
Referenced by inverseGauss(), Gui::View3DInventorViewer::setEditingTransform(), and Gui::LinkView::setTransform().
getMatrix()
void Matrix4D::getMatrix (double dMtrx[16]) const
Definition at line 652 of file Base/Matrix.cpp.
getMemSpace()
unsigned long Matrix4D::getMemSpace ()
Definition at line 688 of file Base/Matrix.cpp.
References Matrix4D().
getRow()
Vector3d Base::Matrix4D::getRow (unsigned short usNdx) const inline
Get vector of row.
Definition at line 457 of file Matrix.h.
Referenced by Assembly::AssemblyObject::doDragStep(), hasScale(), Assembly::AssemblyObject::makeMbdMarker(), and Assembly::AssemblyObject::makeMbdPart().
hasScale()
ScaleType Matrix4D::hasScale (double tol = 0.0) const
Check for scaling factor.
Definition at line 896 of file Base/Matrix.cpp.
References determinant3(), SCL.SimpleDataTypes::e, getCol(), getRow(), Base::NonUniformLeft, Base::NonUniformRight, Base::NoScaling, Base::Other, Base::Vector3< float_type >::Sqr(), KDL::sqrt(), and Base::Uniform.
Referenced by _getTopoShape(), Part::TopoShape::_makeTransform(), and FC_LOG_LEVEL_INIT().
Hat() [1/2]
Matrix4D & Matrix4D::Hat (const Vector3d & rV)
Definition at line 877 of file Base/Matrix.cpp.
References setToUnity(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Hat() [2/2]
Matrix4D & Matrix4D::Hat (const Vector3f & rV)
Hat operator (skew symmetric)
Definition at line 868 of file Base/Matrix.cpp.
References setToUnity().
inverse()
void Matrix4D::inverse ()
Matrix is expected to have a 3x3 rotation submatrix.
Definition at line 518 of file Base/Matrix.cpp.
Referenced by PathGui::PathSelectionObserver::onSelectionChanged(), Data::ComplexGeoData::transformPointToInside(), Data::ComplexGeoData::transformToInside(), Mesh::MeshObject::trim(), and Base::ViewOrthoProjMatrix::ViewOrthoProjMatrix().
inverseGauss()
void Matrix4D::inverseGauss ()
Arbitrary, non-singular matrix.
Definition at line 636 of file Base/Matrix.cpp.
References getGLMatrix(), Matrix_gauss(), and setGLMatrix().
Referenced by decompose(), PartDesign::SubShapeBinder::update(), and Base::ViewProjMatrix::ViewProjMatrix().
inverseOrthogonal()
void Matrix4D::inverseOrthogonal ()
Matrix is expected to have a 3x3 rotation submatrix.
Definition at line 623 of file Base/Matrix.cpp.
References operator*(), transpose(), and SurfaceTests.TestBlendCurve::vec.
isNull()
bool Matrix4D::isNull () const
Checks if this is the null matrix.
Definition at line 148 of file Base/Matrix.cpp.
References SplineSurface::i.
isUnity() [1/2]
bool Matrix4D::isUnity () const
Checks if this is the unit matrix.
Definition at line 103 of file Base/Matrix.cpp.
isUnity() [2/2]
bool Matrix4D::isUnity (double tol) const
Checks if this is the unit matrix.
Definition at line 108 of file Base/Matrix.cpp.
References SplineSurface::i.
move() [1/4]
void Matrix4D::move (const Vector3d & vec)
Definition at line 198 of file Base/Matrix.cpp.
References SurfaceTests.TestBlendCurve::vec.
Referenced by draftguitools.gui_circulararray.CircularArray::Activated(), and draftguitools.gui_polararray.PolarArray::Activated().
move() [2/4]
void Matrix4D::move (const Vector3f & vec)
moves the coordinatesystem for the vector
Definition at line 193 of file Base/Matrix.cpp.
References move(), and SurfaceTests.TestBlendCurve::vec.
Referenced by draftguitools.gui_circulararray.CircularArray::Activated(), and draftguitools.gui_polararray.PolarArray::Activated().
move() [3/4]
void Base::Matrix4D::move (double x, double y, double z) inline
Definition at line 187 of file Matrix.h.
References draftfunctions.scale::scale().
Referenced by draftguitools.gui_circulararray.CircularArray::Activated(), and draftguitools.gui_polararray.PolarArray::Activated().
move() [4/4]
void Base::Matrix4D::move (float x, float y, float z) inline
moves the coordinatesystem for the x,y,z value
Definition at line 183 of file Matrix.h.
Referenced by draftguitools.gui_circulararray.CircularArray::Activated(), draftguitools.gui_polararray.PolarArray::Activated(), Data::ComplexGeoData::applyTranslation(), decompose(), App::FunctionExpression::evaluate(), Import::ImpExpDxfRead::ExpandInsert(), Base::ViewProjMatrix::getProjectionMatrix(), move(), Import::ImpExpDxfRead::OnReadText(), transform(), App::FunctionExpression::translationMatrix(), and Base::ViewProjMatrix::ViewProjMatrix().
multVec() [1/2]
void Base::Matrix4D::multVec (const Vector3d & src, Vector3d & dst) const inline
Definition at line 377 of file Matrix.h.
Referenced by Inspection::InspectActualMesh::getPoint(), Base::ViewProjMatrix::inverse(), Base::ViewProjMatrix::operator()(), perspectiveTransform(), MeshCore::MeshOutput::SaveAsymptote(), Base::Line3< float >::Transform(), Base::Polygon3< float_type >::Transform(), MeshCore::MeshGeomFacet::Transform(), MeshCore::MeshPointArray::Transform(), Points::PointKernel::transformGeometry(), Points::PropertyNormalList::transformGeometry(), and Base::ViewProjMethod::transformInput().
multVec() [2/2]
void Base::Matrix4D::multVec (const Vector3f & src, Vector3f & dst) const inline
Definition at line 387 of file Matrix.h.
nullify()
void Matrix4D::nullify ()
Makes a null matrix.
Definition at line 128 of file Base/Matrix.cpp.
operator!=()
bool Base::Matrix4D::operator!= (const Matrix4D & mat) const inline
Comparison.
Definition at line 436 of file Matrix.h.
operator*() [1/4]
Matrix4D Base::Matrix4D::operator* (const Matrix4D & mat) const inline
Matrix multiplication.
Definition at line 325 of file Matrix.h.
Referenced by inverseOrthogonal().
operator*() [2/4]
Vector3d Base::Matrix4D::operator* (const Vector3d & vec) const inline
Definition at line 368 of file Matrix.h.
References Base::Vector3< float_type >::Set().
operator*() [3/4]
Vector3f Base::Matrix4D::operator* (const Vector3f & vec) const inline
Multiplication matrix with vector.
Definition at line 356 of file Matrix.h.
References Base::Vector3< float_type >::Set().
operator*() [4/4]
Matrix4D Base::Matrix4D::operator* (double scalar) const inline
Definition at line 399 of file Matrix.h.
operator*=() [1/2]
Matrix4D & Base::Matrix4D::operator*= (const Matrix4D & mat) inline
Matrix multiplication.
Definition at line 307 of file Matrix.h.
operator*=() [2/2]
Matrix4D & Base::Matrix4D::operator*= (double scalar) inline
Definition at line 411 of file Matrix.h.
operator+()
Matrix4D Base::Matrix4D::operator+ (const Matrix4D & mat) const inline
Matrix addition.
Definition at line 259 of file Matrix.h.
operator+=()
Matrix4D & Base::Matrix4D::operator+= (const Matrix4D & mat) inline
Definition at line 272 of file Matrix.h.
operator-()
Matrix4D Base::Matrix4D::operator- (const Matrix4D & mat) const inline
Matrix subtraction.
Definition at line 283 of file Matrix.h.
operator-=()
Matrix4D & Base::Matrix4D::operator-= (const Matrix4D & mat) inline
Definition at line 296 of file Matrix.h.
operator=()
Matrix4D & Base::Matrix4D::operator= (const Matrix4D & mat) inline
Assignment.
Definition at line 341 of file Matrix.h.
operator==()
bool Base::Matrix4D::operator== (const Matrix4D & mat) const inline
Comparison.
Definition at line 423 of file Matrix.h.
operator[]() [1/2]
double * Base::Matrix4D::operator[] (unsigned short usNdx) inline
Index operator.
Definition at line 447 of file Matrix.h.
operator[]() [2/2]
const double * Base::Matrix4D::operator[] (unsigned short usNdx) const inline
Index operator.
Definition at line 452 of file Matrix.h.
Outer() [1/2]
Matrix4D & Matrix4D::Outer (const Vector3d & rV1, const Vector3d & rV2)
Definition at line 849 of file Base/Matrix.cpp.
References setToUnity(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Outer() [2/2]
Matrix4D & Matrix4D::Outer (const Vector3f & rV1, const Vector3f & rV2)
Outer product (Dyadic product)
Definition at line 840 of file Base/Matrix.cpp.
References setToUnity().
Print()
void Matrix4D::Print () const
Definition at line 693 of file Base/Matrix.cpp.
References SplineSurface::i.
rotLine() [1/4]
void Matrix4D::rotLine (const Vector3d & rclBase, const Vector3d & rclDir, double fAngle)
Rotate around an arbitrary axis that needn't necessarily pass the origin in radians.
Definition at line 332 of file Base/Matrix.cpp.
References rotLine(), and transform().
rotLine() [2/4]
void Matrix4D::rotLine (const Vector3d & vec, double fAngle)
Rotate around an arbitrary axis passing the origin in radians.
Definition at line 268 of file Base/Matrix.cpp.
References KDL::cos(), Base::Vector3< float_type >::Normalize(), KDL::sin(), SurfaceTests.TestBlendCurve::vec, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
rotLine() [3/4]
void Matrix4D::rotLine (const Vector3f & rclBase, const Vector3f & rclDir, float fAngle)
Rotate around an arbitrary axis that needn't necessarily pass the origin in radians.
Definition at line 339 of file Base/Matrix.cpp.
References rotLine().
rotLine() [4/4]
void Matrix4D::rotLine (const Vector3f & vec, float fAngle)
Rotate around an arbitrary axis passing the origin in radians.
Definition at line 326 of file Base/Matrix.cpp.
References SurfaceTests.TestBlendCurve::vec.
Referenced by Matrix4D(), rotLine(), and TechDraw::DrawUtil::vecRotate().
rotX()
void Matrix4D::rotX (double fAngle)
Rotate around the X axis (in transformed space) for the given value in radians.
Definition at line 220 of file Base/Matrix.cpp.
References KDL::cos(), and KDL::sin().
rotY()
void Matrix4D::rotY (double fAngle)
Rotate around the Y axis (in transformed space) for the given value in radians.
Definition at line 236 of file Base/Matrix.cpp.
References KDL::cos(), and KDL::sin().
rotZ()
void Matrix4D::rotZ (double fAngle)
Rotate around the Z axis (in transformed space) for the given value in radians.
Definition at line 252 of file Base/Matrix.cpp.
References KDL::cos(), and KDL::sin().
Referenced by decompose(), Part::Prism::execute(), Part::RegularPolygon::execute(), PartDesign::Prism::execute(), Import::ImpExpDxfRead::ExpandInsert(), and Import::ImpExpDxfRead::OnReadText().
scale() [1/6]
void Matrix4D::scale (const Vector3d & vec)
Definition at line 210 of file Base/Matrix.cpp.
References SurfaceTests.TestBlendCurve::vec.
scale() [2/6]
void Matrix4D::scale (const Vector3f & vec)
scale for the x,y,z value
Definition at line 205 of file Base/Matrix.cpp.
References scale(), and SurfaceTests.TestBlendCurve::vec.
scale() [3/6]
void Base::Matrix4D::scale (double scalexyz) inline
Definition at line 211 of file Matrix.h.
scale() [4/6]
void Base::Matrix4D::scale (double x, double y, double z) inline
Definition at line 199 of file Matrix.h.
scale() [5/6]
void Base::Matrix4D::scale (float scalexyz) inline
uniform scale
Definition at line 207 of file Matrix.h.
scale() [6/6]
void Base::Matrix4D::scale (float x, float y, float z) inline
scale for the vector
Definition at line 195 of file Matrix.h.
Referenced by App::FunctionExpression::evaluate(), Import::ImpExpDxfRead::ExpandInsert(), Base::ViewProjMatrix::getProjectionMatrix(), Measure::ShapeFinder::getScale(), TechDraw::ShapeExtractor::getShapeFromXLink(), TechDraw::ShapeExtractor::getXShapes(), Part::Scale::nonuniformScale(), scale(), and Base::ViewProjMatrix::ViewProjMatrix().
setCol()
void Base::Matrix4D::setCol (unsigned short usNdx, const Vector3d & vec) inline
Set column to vector.
Definition at line 489 of file Matrix.h.
Referenced by decompose(), Data::ComplexGeoData::transformVectorsToOutside(), and Data::ComplexGeoData::transformVectorToOutside().
setDiagonal()
void Base::Matrix4D::setDiagonal (const Vector3d & vec) inline
Set diagonal to vector.
Definition at line 496 of file Matrix.h.
setGLMatrix()
void Matrix4D::setGLMatrix (const double dMtrx[16])
set the matrix in OpenGL style
Definition at line 679 of file Base/Matrix.cpp.
Referenced by inverseGauss().
setMatrix()
void Matrix4D::setMatrix (const double dMtrx[16])
Definition at line 661 of file Base/Matrix.cpp.
setRow()
void Base::Matrix4D::setRow (unsigned short usNdx, const Vector3d & vec) inline
Set row to vector.
Definition at line 482 of file Matrix.h.
setToUnity()
void Matrix4D::setToUnity ()
Makes unity matrix.
Definition at line 83 of file Base/Matrix.cpp.
Referenced by MeshCore::FunctionContainer::GetHessian(), MeshCore::AbstractPolygonTriangulator::GetTransformToFitPlane(), Hat(), Outer(), Mesh::PropertyNormalList::transformGeometry(), Points::PropertyNormalList::transformGeometry(), Mesh::PropertyCurvatureList::transformGeometry(), and Points::PropertyCurvatureList::transformGeometry().
toAxisAngle() [1/2]
bool Matrix4D::toAxisAngle (Vector3d & rclBase, Vector3d & rclDir, double & fAngle, double & fTranslation) const
Definition at line 379 of file Base/Matrix.cpp.
References KDL::acos(), D_PI, SplineSurface::i, Base::Vector3< float_type >::Normalize(), KDL::sin(), KDL::sqrt(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
toAxisAngle() [2/2]
bool Matrix4D::toAxisAngle (Vector3f & rclBase, Vector3f & rclDir, float & rfAngle, float & fTranslation) const
Extract the rotation axis and angle. Therefore the 3x3 submatrix must be orthogonal.
If this matrix describes a rotation around an arbitrary axis with a translation (in axis direction) then the base point of the axis, its direction, the rotation angle and the translation part get calculated. In this case the return value is set to true, if this matrix doesn't describe a rotation false is returned.
The translation vector can be calculated with fTranslation * rclDir, whereas the length of rclDir is normalized to 1.
Note: In case the fTranslation part is zero then passing rclBase, rclDir and rfAngle to a new matrix object creates an identical matrix.
Definition at line 358 of file Base/Matrix.cpp.
toString()
std::string Matrix4D::toString () const
write the 16 double of the matrix into a string
Definition at line 721 of file Base/Matrix.cpp.
References SplineSurface::i, and Path.Post.scripts.refactored_centroid_post::str.
trace()
double Base::Matrix4D::trace () const inline
Get trace of the 4x4 matrix.
Definition at line 477 of file Matrix.h.
References SurfaceTests.TestBlendCurve::vec.
trace3()
double Base::Matrix4D::trace3 () const inline
Get trace of the 3x3 matrix.
Definition at line 472 of file Matrix.h.
transform() [1/2]
void Matrix4D::transform (const Vector3d & vec, const Matrix4D & mat)
Definition at line 511 of file Base/Matrix.cpp.
References move(), and SurfaceTests.TestBlendCurve::vec.
Referenced by ArchIFCView.IfcContextView::setupContextMenu(), draftviewproviders.view_hatch.ViewProviderDraftHatch::setupContextMenu(), draftviewproviders.view_base.ViewProviderDraft::setupContextMenu(), ArchAxis._ViewProviderAxis::setupContextMenu(), and ArchSite._ViewProviderSite::setupContextMenu().
transform() [2/2]
void Matrix4D::transform (const Vector3f & vec, const Matrix4D & mat)
transform (move,scale,rotate) around a point
Definition at line 504 of file Base/Matrix.cpp.
References move(), and SurfaceTests.TestBlendCurve::vec.
Referenced by rotLine(), ArchIFCView.IfcContextView::setupContextMenu(), draftviewproviders.view_hatch.ViewProviderDraftHatch::setupContextMenu(), draftviewproviders.view_base.ViewProviderDraft::setupContextMenu(), ArchAxis._ViewProviderAxis::setupContextMenu(), and ArchSite._ViewProviderSite::setupContextMenu().
transpose()
void Matrix4D::transpose ()
Definition at line 706 of file Base/Matrix.cpp.
References SplineSurface::i.
Referenced by analyse(), and inverseOrthogonal().
The documentation for this class was generated from the following files:
Matrix.h
Base/Matrix.cpp