FreeCAD: SoGesturePinchEvent Class Reference
SoGesturePinchEvent Class Reference
#include <SoTouchEvents.h>
Public Member Functions
SoGesturePinchEvent ()
SoGesturePinchEvent (QPinchGesture *qpinch, QWidget *widget)
~SoGesturePinchEvent () override=default
SbBool isSoGesturePinchEvent (const SoEvent *ev) const
Public Member Functions inherited from SoGestureEvent
SoGestureEvent ()=default
~SoGestureEvent () override=default
SbBool isSoGestureEvent (const SoEvent *ev) const
Static Public Member Functions
static void initClass ()
static double unbranchAngle (double ang)
SoGesturePinchEvent::unbranchAngle : utility function to bring an angle into -pi..pi region.
Static Public Member Functions inherited from SoGestureEvent
static void initClass ()
Public Attributes
SbVec2f startCenter
SbVec2f curCenter
SbVec2f deltaCenter
double deltaZoom
double totalZoom
double deltaAngle
double totalAngle
Public Attributes inherited from SoGestureEvent
SbGestureState state {SbGSNoGesture}
Additional Inherited Members
Public Types inherited from SoGestureEvent
enum SbGestureState {
SbGSNoGesture = Qt::NoGesture, SbGSStart = Qt::GestureStarted, SbGSUpdate = Qt::GestureUpdated, SbGSEnd = Qt::GestureFinished,
SbGsCanceled = Qt::GestureCanceled
}
Detailed Description
Definition at line 71 of file SoTouchEvents.h.
Constructor & Destructor Documentation
SoGesturePinchEvent() [1/2]
SoGesturePinchEvent::SoGesturePinchEvent () inline
Definition at line 77 of file SoTouchEvents.h.
SoGesturePinchEvent() [2/2]
SoGesturePinchEvent::SoGesturePinchEvent (QPinchGesture * qpinch, QWidget * widget)
Definition at line 68 of file SoTouchEvents.cpp.
References curCenter, deltaAngle, deltaCenter, deltaZoom, M_PI, startCenter, SoGestureEvent::state, totalAngle, totalZoom, unbranchAngle(), and MovieTool::x.
~SoGesturePinchEvent()
SoGesturePinchEvent::~SoGesturePinchEvent () override default
Member Function Documentation
initClass()
static void SoGesturePinchEvent::initClass () inline static
Definition at line 74 of file SoTouchEvents.h.
Referenced by GesturesDevice::GesturesDevice(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
isSoGesturePinchEvent()
SbBool SoGesturePinchEvent::isSoGesturePinchEvent (const SoEvent * ev) const
Definition at line 102 of file SoTouchEvents.cpp.
unbranchAngle()
double SoGesturePinchEvent::unbranchAngle (double ang) static
SoGesturePinchEvent::unbranchAngle : utility function to bring an angle into -pi..pi region.
Parameters
ang - in radians
Returns
Definition at line 112 of file SoTouchEvents.cpp.
References M_PI.
Referenced by SoGesturePinchEvent().
Member Data Documentation
curCenter
SbVec2f SoGesturePinchEvent::curCenter
Definition at line 86 of file SoTouchEvents.h.
Referenced by SoGesturePinchEvent().
deltaAngle
double SoGesturePinchEvent::deltaAngle
Definition at line 90 of file SoTouchEvents.h.
Referenced by SoGesturePinchEvent().
deltaCenter
SbVec2f SoGesturePinchEvent::deltaCenter
Definition at line 87 of file SoTouchEvents.h.
Referenced by SoGesturePinchEvent().
deltaZoom
double SoGesturePinchEvent::deltaZoom
Definition at line 88 of file SoTouchEvents.h.
Referenced by SoGesturePinchEvent().
startCenter
SbVec2f SoGesturePinchEvent::startCenter
Definition at line 85 of file SoTouchEvents.h.
Referenced by SoGesturePinchEvent().
totalAngle
double SoGesturePinchEvent::totalAngle
Definition at line 91 of file SoTouchEvents.h.
Referenced by SoGesturePinchEvent().
totalZoom
double SoGesturePinchEvent::totalZoom
Definition at line 89 of file SoTouchEvents.h.
Referenced by SoGesturePinchEvent().
The documentation for this class was generated from the following files:
SoTouchEvents.h
SoTouchEvents.cpp