FreeCAD: Path.Post.UtilsArguments Namespace Reference
Path.Post.UtilsArguments Namespace Reference
Functions
None add_flag_type_arguments (argument_group, bool default_flag, str true_argument, str false_argument, str true_help, str false_help, bool visible=True)
None init_argument_defaults (Dict[str, bool] argument_defaults)
None init_arguments_visible (Dict[str, bool] arguments_visible)
Parser init_shared_arguments (Values values, Dict[str, bool] argument_defaults, Dict[str, bool] arguments_visible)
None init_shared_values (Values values)
Tuple[bool, Union[str, argparse.Namespace]] process_shared_arguments (Values values, Parser parser, str argstring, Parser all_visible, str filename)
Variables
PathParameter
PathParameters
Parser
Values
ParameterFunction
Function Documentation
add_flag_type_arguments()
None Path.Post.UtilsArguments.add_flag_type_arguments (argument_group, bool default_flag, str true_argument, str false_argument, str true_help, str false_help, bool visible = True)
Create an argument specification for an argument that is a flag.
Definition at line 51 of file UtilsArguments.py.
Referenced by Path.Post.UtilsArguments.init_shared_arguments().
init_argument_defaults()
None Path.Post.UtilsArguments.init_argument_defaults (Dict[str, bool] argument_defaults)
Initialize which argument to show as the default in flag-type arguments.
Definition at line 72 of file UtilsArguments.py.
init_arguments_visible()
None Path.Post.UtilsArguments.init_arguments_visible (Dict[str, bool] arguments_visible)
Initialize the flags for which arguments are visible in the arguments tooltip.
Definition at line 89 of file UtilsArguments.py.
init_shared_arguments()
Parser Path.Post.UtilsArguments.init_shared_arguments (Values values, Dict[str, bool] argument_defaults, Dict[str, bool] arguments_visible)
Initialize the arguments for postprocessors.
Definition at line 113 of file UtilsArguments.py.
References Path.Post.UtilsArguments.add_flag_type_arguments().
init_shared_values()
None Path.Post.UtilsArguments.init_shared_values (Values values)
Initialize the default values in postprocessors.
Definition at line 323 of file UtilsArguments.py.
process_shared_arguments()
Tuple[bool, Union[str, argparse.Namespace]] Path.Post.UtilsArguments.process_shared_arguments (Values values, Parser parser, str argstring, Parser all_visible, str filename)
Process the arguments to the postprocessor.
Definition at line 603 of file UtilsArguments.py.
References AssemblyImport.open().
Variable Documentation
ParameterFunction
Path.Post.UtilsArguments.ParameterFunction
Definition at line 48 of file UtilsArguments.py.
Parser
Path.Post.UtilsArguments.Parser
Definition at line 45 of file UtilsArguments.py.
PathParameter
Path.Post.UtilsArguments.PathParameter
Definition at line 43 of file UtilsArguments.py.
PathParameters
Path.Post.UtilsArguments.PathParameters
Definition at line 44 of file UtilsArguments.py.
Values
Path.Post.UtilsArguments.Values
Definition at line 46 of file UtilsArguments.py.