FreeCAD: Materials::MaterialLoader Class Reference
Materials::MaterialLoader Class Reference
#include <MaterialLoader.h>
Public Member Functions
MaterialLoader (const std::shared_ptr< std::map< QString, std::shared_ptr< Material >>> &materialMap, const std::shared_ptr< std::list< std::shared_ptr< MaterialLibrary >>> &libraryList)
~MaterialLoader ()=default
std::shared_ptr< std::list< std::shared_ptr< MaterialLibrary > > > getMaterialLibraries ()
Static Public Member Functions
static std::shared_ptr< std::list< QString > > getMaterialFolders (const MaterialLibrary &library)
static void showYaml (const YAML::Node &yaml)
static void dereference (const std::shared_ptr< std::map< QString, std::shared_ptr< Material >>> &materialMap, const std::shared_ptr< Material > &material)
static std::shared_ptr< MaterialEntry > getMaterialFromYAML (const std::shared_ptr< MaterialLibrary > &library, YAML::Node &yamlroot, const QString &path)
Detailed Description
Definition at line 129 of file MaterialLoader.h.
Constructor & Destructor Documentation
MaterialLoader()
MaterialLoader::MaterialLoader (const std::shared_ptr< std::map< QString, std::shared_ptr< Material >>> & materialMap, const std::shared_ptr< std::list< std::shared_ptr< MaterialLibrary >>> & libraryList)
Definition at line 344 of file MaterialLoader.cpp.
~MaterialLoader()
Materials::MaterialLoader::~MaterialLoader () default
Referenced by Materials::MaterialYamlEntry::getModelPtr().
Member Function Documentation
dereference()
void MaterialLoader::dereference (const std::shared_ptr< std::map< QString, std::shared_ptr< Material >>> & materialMap, const std::shared_ptr< Material > & material) static
Definition at line 442 of file MaterialLoader.cpp.
References Base::Console(), Base::ConsoleSingleton::Log(), and Init::parent.
Referenced by Materials::MaterialManager::dereference(), and Materials::MaterialYamlEntry::getModelPtr().
getMaterialFolders()
std::shared_ptr< std::list< QString > > MaterialLoader::getMaterialFolders (const MaterialLibrary & library) static
Definition at line 643 of file MaterialLoader.cpp.
References DrawingExample::file, and Materials::LibraryBase::getDirectory().
Referenced by Materials::MaterialManager::getMaterialFolders(), Materials::MaterialLibrary::getMaterialTree(), and Materials::MaterialYamlEntry::getModelPtr().
getMaterialFromYAML()
std::shared_ptr< MaterialEntry > MaterialLoader::getMaterialFromYAML (const std::shared_ptr< MaterialLibrary > & library, YAML::Node & yamlroot, const QString & path) static
Definition at line 359 of file MaterialLoader.cpp.
References Base::Console(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), ifctree::filepath, and showYaml().
Referenced by Materials::MaterialYamlEntry::getModelPtr().
getMaterialLibraries()
std::shared_ptr< std::list< std::shared_ptr< MaterialLibrary > > > MaterialLoader::getMaterialLibraries ()
Definition at line 558 of file MaterialLoader.cpp.
References Base::Console(), App::GetApplication(), App::Application::GetParameterGroupByPath(), App::Application::getResourceDir(), App::Application::getUserAppDataDir(), toolbit-attributes::group, Base::ConsoleSingleton::Log(), and Init::param.
Referenced by Materials::MaterialYamlEntry::getModelPtr().
showYaml()
void MaterialLoader::showYaml (const YAML::Node & yaml) static
Definition at line 432 of file MaterialLoader.cpp.
References Base::Console(), and Base::ConsoleSingleton::Log().
Referenced by getMaterialFromYAML(), and Materials::MaterialYamlEntry::getModelPtr().
The documentation for this class was generated from the following files:
MaterialLoader.h
MaterialLoader.cpp