FreeCAD: Gui::ParamHandlers Class Reference
Gui::ParamHandlers Class Reference
#include <ParamHandler.h>
Public Member Functions
ParamHandlers ()
virtual ~ParamHandlers ()
void addHandler (const ParamKey &key, const std::shared_ptr< ParamHandler > &handler)
void addHandler (const char *path, const char *key, const std::shared_ptr< ParamHandler > &handler)
void addHandler (ParameterGrp *hGrp, const char *key, const std::shared_ptr< ParamHandler > &handler)
void addHandler (const std::vector< ParamKey > &keys, const std::shared_ptr< ParamHandler > &handler)
void addHandler (const char *path, const std::vector< const char * > &keys, const std::shared_ptr< ParamHandler > &handler)
void addHandler (ParameterGrp *hGrp, const std::vector< const char * > &keys, const std::shared_ptr< ParamHandler > &handler)
template<class Func >
std::shared_ptr< ParamHandler > addHandler (const char *path, const char *key, Func func)
template<class Func >
std::shared_ptr< ParamHandler > addHandler (ParameterGrp *hGrp, const char *key, Func func)
template<class Func >
std::shared_ptr< ParamHandler > addDelayedHandler (const char *path, const char *key, Func func)
template<class Func >
std::shared_ptr< ParamHandler > addDelayedHandler (ParameterGrp *hGrp, const char *key, Func func)
template<class Func >
std::shared_ptr< ParamHandler > addDelayedHandler (const char *path, const std::vector< const char * > &keys, Func func)
template<class Func >
std::shared_ptr< ParamHandler > addDelayedHandler (ParameterGrp::handle hGrp, const std::vector< const char * > &keys, Func func)
Protected Attributes
std::map< ParamKey, std::shared_ptr< ParamHandler > > handlers
std::set< std::shared_ptr< ParamHandler > > pendings
boost::signals2::scoped_connection conn
QTimer timer
Detailed Description
Definition at line 147 of file ParamHandler.h.
Constructor & Destructor Documentation
ParamHandlers()
ParamHandlers::ParamHandlers ()
Definition at line 30 of file ParamHandler.cpp.
~ParamHandlers()
ParamHandlers::~ParamHandlers () virtual
Definition at line 34 of file ParamHandler.cpp.
Member Function Documentation
addDelayedHandler() [1/4]
template<class Func > std::shared_ptr<ParamHandler> Gui::ParamHandlers::addDelayedHandler (const char * path, const char * key, Func func) inline
Definition at line 192 of file ParamHandler.h.
References App::GetApplication(), ParameterGrp::GetGroup(), App::Application::GetUserParameter(), and buildPsets::handler.
Referenced by Gui::Dialog::DlgSettingsUI::attachObserver().
addDelayedHandler() [2/4]
template<class Func > std::shared_ptr<ParamHandler> Gui::ParamHandlers::addDelayedHandler (const char * path, const std::vector< const char * > & keys, Func func) inline
Definition at line 213 of file ParamHandler.h.
addDelayedHandler() [3/4]
template<class Func > std::shared_ptr<ParamHandler> Gui::ParamHandlers::addDelayedHandler (ParameterGrp * hGrp, const char * key, Func func) inline
Definition at line 203 of file ParamHandler.h.
addDelayedHandler() [4/4]
template<class Func > std::shared_ptr<ParamHandler> Gui::ParamHandlers::addDelayedHandler (ParameterGrp::handle hGrp, const std::vector< const char * > & keys, Func func) inline
Definition at line 228 of file ParamHandler.h.
addHandler() [1/8]
void Gui::ParamHandlers::addHandler (const char * path, const char * key, const std::shared_ptr< ParamHandler > & handler) inline
Definition at line 154 of file ParamHandler.h.
addHandler() [2/8]
template<class Func > std::shared_ptr<ParamHandler> Gui::ParamHandlers::addHandler (const char * path, const char * key, Func func) inline
Definition at line 178 of file ParamHandler.h.
addHandler() [3/8]
void Gui::ParamHandlers::addHandler (const char * path, const std::vector< const char * > & keys, const std::shared_ptr< ParamHandler > & handler) inline
Definition at line 167 of file ParamHandler.h.
addHandler() [4/8]
void ParamHandlers::addHandler (const ParamKey & key, const std::shared_ptr< ParamHandler > & handler)
Definition at line 38 of file ParamHandler.cpp.
References conn, draftgeoutils.intersections::connect(), App::GetApplication(), App::Application::GetUserParameter(), buildPsets::handler, handlers, pendings, ParameterManager::signalParamChanged, timer, and TestSpreadsheet::v.
Referenced by Gui::Dialog::DlgSettingsGeneral::attachObserver(), and Gui::Dialog::DlgSettingsUI::attachObserver().
addHandler() [5/8]
void Gui::ParamHandlers::addHandler (const std::vector< ParamKey > & keys, const std::shared_ptr< ParamHandler > & handler) inline
Definition at line 162 of file ParamHandler.h.
addHandler() [6/8]
void Gui::ParamHandlers::addHandler (ParameterGrp * hGrp, const char * key, const std::shared_ptr< ParamHandler > & handler) inline
Definition at line 158 of file ParamHandler.h.
References buildPsets::handler.
addHandler() [7/8]
template<class Func > std::shared_ptr<ParamHandler> Gui::ParamHandlers::addHandler (ParameterGrp * hGrp, const char * key, Func func) inline
Definition at line 185 of file ParamHandler.h.
addHandler() [8/8]
void Gui::ParamHandlers::addHandler (ParameterGrp * hGrp, const std::vector< const char * > & keys, const std::shared_ptr< ParamHandler > & handler) inline
Definition at line 172 of file ParamHandler.h.
References App::GetApplication(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Member Data Documentation
conn
boost::signals2::scoped_connection Gui::ParamHandlers::conn protected
Definition at line 244 of file ParamHandler.h.
Referenced by addHandler().
handlers
std::map<ParamKey, std::shared_ptr<ParamHandler> > Gui::ParamHandlers::handlers protected
Definition at line 242 of file ParamHandler.h.
Referenced by importers.importSH3DHelper.SH3DImporter::add_wall(), addHandler(), and importers.importSH3DHelper.SH3DImporter::import_sh3d_from_filename().
pendings
std::set<std::shared_ptr<ParamHandler> > Gui::ParamHandlers::pendings protected
Definition at line 243 of file ParamHandler.h.
Referenced by addHandler().
timer
QTimer Gui::ParamHandlers::timer protected
Definition at line 245 of file ParamHandler.h.
Referenced by femtaskpanels.base_femmeshtaskpanel._BaseMeshTaskPanel::accept(), addHandler(), ArchReference.ViewProviderArchReference::checkChanges(), Path.Main.Gui.Simulator.PathSimulation::EndSimulation(), ArchReference.ViewProviderArchReference::onDelete(), Path.Main.Gui.Simulator.PathSimulation::onSpeedBarChange(), femtaskpanels.base_femmeshtaskpanel._BaseMeshTaskPanel::reject(), src.Mod.AddonManager.AddonManagerTest.gui.gui_mocks.DialogInteractor::run(), femtaskpanels.base_femmeshtaskpanel._BaseMeshTaskPanel::setup_connections(), Path.Main.Gui.Simulator.PathSimulation::SimFF(), Path.Main.Gui.Simulator.PathSimulation::SimPause(), Path.Main.Gui.Simulator.PathSimulation::SimPlay(), and femtaskpanels.base_femmeshtaskpanel._BaseMeshTaskPanel::stop_timer().
The documentation for this class was generated from the following files:
ParamHandler.h
ParamHandler.cpp