FreeCAD: Base::Polygon3< float_type > Class Template Reference
Base::Polygon3< float_type > Class Template Reference
#include <Tools3D.h>
Public Member Functions
Polygon3 ()=default
~Polygon3 ()=default
Polygon3 (const Polygon3< float_type > &poly)=default
Polygon3 (Polygon3< float_type > &&poly) noexcept=default
Polygon3 & operator= (const Polygon3< float_type > &poly)=default
Polygon3 & operator= (Polygon3< float_type > &&poly) noexcept=default
size_t GetSize () const
void Add (const Vector3< float_type > &pnt)
const Vector3< float_type > & operator[] (size_t pos) const
const Vector3< float_type > & At (size_t pos) const
Vector3< float_type > & operator[] (size_t pos)
Vector3< float_type > & At (size_t pos)
bool Remove (size_t pos)
void Clear ()
BoundBox3< float_type > CalcBoundBox () const
void Transform (const Base::Matrix4D &)
void Transform (const Base::Placement &)
void Transform (const Base::Rotation &)
Polygon3 Transformed (const Base::Matrix4D &) const
Polygon3 Transformed (const Base::Placement &) const
Polygon3 Transformed (const Base::Rotation &) const
Detailed Description
template<class float_type>
class Base::Polygon3< float_type >
Polygon3 3D polygon class.
Definition at line 129 of file Tools3D.h.
Constructor & Destructor Documentation
Polygon3() [1/3]
template<class float_type > Base::Polygon3< float_type >::Polygon3 () default
~Polygon3()
template<class float_type > Base::Polygon3< float_type >::~Polygon3 () default
Polygon3() [2/3]
template<class float_type > Base::Polygon3< float_type >::Polygon3 (const Polygon3< float_type > & poly) default
Polygon3() [3/3]
template<class float_type > Base::Polygon3< float_type >::Polygon3 (Polygon3< float_type > && poly) default noexcept
Member Function Documentation
Add()
template<typename float_type > void Polygon3::Add (const Vector3< float_type > & pnt)
Definition at line 163 of file Tools3D.cpp.
At() [1/2]
template<typename float_type > Vector3< float_type > & Polygon3::At (size_t pos)
Definition at line 187 of file Tools3D.cpp.
References RobotExample::pos.
At() [2/2]
template<typename float_type > const Vector3< float_type > & Polygon3::At (size_t pos) const
Definition at line 175 of file Tools3D.cpp.
References RobotExample::pos.
CalcBoundBox()
template<typename float_type > BoundBox3< float_type > Polygon3::CalcBoundBox
Definition at line 212 of file Tools3D.cpp.
References MengerSponge::box.
Clear()
template<typename float_type > void Polygon3::Clear
Definition at line 206 of file Tools3D.cpp.
GetSize()
template<typename float_type > size_t Polygon3::GetSize
Definition at line 157 of file Tools3D.cpp.
operator=() [1/2]
template<class float_type > Polygon3& Base::Polygon3< float_type >::operator= (const Polygon3< float_type > & poly) default
operator=() [2/2]
template<class float_type > Polygon3& Base::Polygon3< float_type >::operator= (Polygon3< float_type > && poly) default noexcept
operator[]() [1/2]
template<typename float_type > Vector3< float_type > & Polygon3::operator[] (size_t pos)
Definition at line 181 of file Tools3D.cpp.
References RobotExample::pos.
operator[]() [2/2]
template<typename float_type > const Vector3< float_type > & Polygon3::operator[] (size_t pos) const
Definition at line 169 of file Tools3D.cpp.
References RobotExample::pos.
Remove()
template<typename float_type > bool Polygon3::Remove (size_t pos)
Definition at line 193 of file Tools3D.cpp.
References RobotExample::pos.
Transform() [1/3]
template<typename float_type > void Polygon3::Transform (const Base::Matrix4D & mat)
Definition at line 222 of file Tools3D.cpp.
References Base::Matrix4D::multVec().
Referenced by Base::Polygon3< float_type >::Transformed().
Transform() [2/3]
template<typename float_type > void Polygon3::Transform (const Base::Placement & plm)
Definition at line 230 of file Tools3D.cpp.
References Base::Placement::multVec().
Transform() [3/3]
template<typename float_type > void Polygon3::Transform (const Base::Rotation & rot)
Definition at line 238 of file Tools3D.cpp.
References Base::Rotation::multVec().
Transformed() [1/3]
template<typename float_type > Polygon3< float_type > Polygon3::Transformed (const Base::Matrix4D & mat) const
Definition at line 246 of file Tools3D.cpp.
References Base::Polygon3< float_type >::Transform().
Transformed() [2/3]
template<typename float_type > Polygon3< float_type > Polygon3::Transformed (const Base::Placement & plm) const
Definition at line 254 of file Tools3D.cpp.
References Base::Polygon3< float_type >::Transform().
Transformed() [3/3]
template<typename float_type > Polygon3< float_type > Polygon3::Transformed (const Base::Rotation & rot) const
Definition at line 262 of file Tools3D.cpp.
References Base::Polygon3< float_type >::Transform().
The documentation for this class was generated from the following files:
Tools3D.h
Tools3D.cpp