FreeCAD: ifc2x3.ifchygroscopicmaterialproperties Class Reference
ifc2x3.ifchygroscopicmaterialproperties Class Reference
Public Member Functions
def __init__ (self, inherited0__material, uppervaporresistancefactor, lowervaporresistancefactor, isothermalmoisturecapacity, vaporpermeability, moisturediffusivity)
def uppervaporresistancefactor ()
def lowervaporresistancefactor ()
def isothermalmoisturecapacity ()
def vaporpermeability ()
def moisturediffusivity ()
Public Member Functions inherited from ifc2x3.ifcmaterialproperties
def __init__ (self, material)
def material ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
uppervaporresistancefactor
lowervaporresistancefactor
isothermalmoisturecapacity
vaporpermeability
moisturediffusivity
Public Attributes inherited from ifc2x3.ifcmaterialproperties
material
Detailed Description
Entity ifchygroscopicmaterialproperties definition.
:param uppervaporresistancefactor
:type uppervaporresistancefactor:ifcpositiveratiomeasure
:param lowervaporresistancefactor
:type lowervaporresistancefactor:ifcpositiveratiomeasure
:param isothermalmoisturecapacity
:type isothermalmoisturecapacity:ifcisothermalmoisturecapacitymeasure
:param vaporpermeability
:type vaporpermeability:ifcvaporpermeabilitymeasure
:param moisturediffusivity
:type moisturediffusivity:ifcmoisturediffusivitymeasure
Definition at line 2604 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifchygroscopicmaterialproperties.__init__ (self, inherited0__material, uppervaporresistancefactor, lowervaporresistancefactor, isothermalmoisturecapacity, vaporpermeability, moisturediffusivity)
Definition at line 2622 of file ifc2x3.py.
Member Function Documentation
isothermalmoisturecapacity()
def ifc2x3.ifchygroscopicmaterialproperties.isothermalmoisturecapacity ()
Definition at line 2659 of file ifc2x3.py.
References ifc2x3.ifchygroscopicmaterialproperties._isothermalmoisturecapacity, SCL.TypeChecker.check_type(), and ifc2x3.ifchygroscopicmaterialproperties.isothermalmoisturecapacity.
lowervaporresistancefactor()
def ifc2x3.ifchygroscopicmaterialproperties.lowervaporresistancefactor ()
Definition at line 2645 of file ifc2x3.py.
References ifc2x3.ifchygroscopicmaterialproperties._lowervaporresistancefactor, SCL.TypeChecker.check_type(), and ifc2x3.ifchygroscopicmaterialproperties.lowervaporresistancefactor.
moisturediffusivity()
def ifc2x3.ifchygroscopicmaterialproperties.moisturediffusivity ()
Definition at line 2687 of file ifc2x3.py.
References ifc2x3.ifchygroscopicmaterialproperties._moisturediffusivity, SCL.TypeChecker.check_type(), and ifc2x3.ifchygroscopicmaterialproperties.moisturediffusivity.
uppervaporresistancefactor()
def ifc2x3.ifchygroscopicmaterialproperties.uppervaporresistancefactor ()
Definition at line 2631 of file ifc2x3.py.
References ifc2x3.ifchygroscopicmaterialproperties._uppervaporresistancefactor, SCL.TypeChecker.check_type(), and ifc2x3.ifchygroscopicmaterialproperties.uppervaporresistancefactor.
vaporpermeability()
def ifc2x3.ifchygroscopicmaterialproperties.vaporpermeability ()
Definition at line 2673 of file ifc2x3.py.
References ifc2x3.ifchygroscopicmaterialproperties._vaporpermeability, SCL.TypeChecker.check_type(), and ifc2x3.ifchygroscopicmaterialproperties.vaporpermeability.
Member Data Documentation
isothermalmoisturecapacity
ifc2x3.ifchygroscopicmaterialproperties.isothermalmoisturecapacity
Definition at line 2626 of file ifc2x3.py.
Referenced by ifc2x3.ifchygroscopicmaterialproperties.isothermalmoisturecapacity().
lowervaporresistancefactor
ifc2x3.ifchygroscopicmaterialproperties.lowervaporresistancefactor
Definition at line 2625 of file ifc2x3.py.
Referenced by ifc2x3.ifchygroscopicmaterialproperties.lowervaporresistancefactor().
moisturediffusivity
ifc2x3.ifchygroscopicmaterialproperties.moisturediffusivity
Definition at line 2628 of file ifc2x3.py.
Referenced by ifc2x3.ifchygroscopicmaterialproperties.moisturediffusivity().
uppervaporresistancefactor
ifc2x3.ifchygroscopicmaterialproperties.uppervaporresistancefactor
Definition at line 2624 of file ifc2x3.py.
Referenced by ifc2x3.ifchygroscopicmaterialproperties.uppervaporresistancefactor().
vaporpermeability
ifc2x3.ifchygroscopicmaterialproperties.vaporpermeability
Definition at line 2627 of file ifc2x3.py.
Referenced by ifc2x3.ifchygroscopicmaterialproperties.vaporpermeability().
The documentation for this class was generated from the following file:
ifc2x3.py