FreeCAD: MeshCore::MeshFixNaNPoints Class Reference
MeshCore::MeshFixNaNPoints Class Reference
#include <Degeneration.h>
Public Member Functions
MeshFixNaNPoints (MeshKernel &rclM)
bool Fixup () override
Public Member Functions inherited from MeshCore::MeshValidation
MeshValidation (MeshKernel &rclB)
virtual ~MeshValidation ()=default
MeshValidation (const MeshValidation &)=delete
MeshValidation (MeshValidation &&)=delete
MeshValidation & operator= (const MeshValidation &)=delete
MeshValidation & operator= (MeshValidation &&)=delete
Additional Inherited Members
Protected Attributes inherited from MeshCore::MeshValidation
MeshKernel & _rclMesh
Detailed Description
The MeshFixNaNPoints class removes all points with a coordinate that is NaN.
See also
MeshEvalNaNPoints
Author
Werner Mayer
Definition at line 184 of file Degeneration.h.
Constructor & Destructor Documentation
MeshFixNaNPoints()
MeshCore::MeshFixNaNPoints::MeshFixNaNPoints (MeshKernel & rclM) inline explicit
Construction.
Definition at line 190 of file Degeneration.h.
Member Function Documentation
Fixup()
bool MeshFixNaNPoints::Fixup () override virtual
Merges duplicated points.
Implements MeshCore::MeshValidation.
Definition at line 254 of file Degeneration.cpp.
References MeshCore::MeshValidation::_rclMesh, MeshCore::MeshKernel::DeletePoints(), MeshCore::MeshKernel::GetPoints(), and MeshCore::MeshKernel::RebuildNeighbours().
The documentation for this class was generated from the following files:
Degeneration.h
Degeneration.cpp