FreeCAD: Gui::SoFCDocumentObjectAction Class Reference
Gui::SoFCDocumentObjectAction Class Reference
#include <SoFCSelectionAction.h>
Public Member Functions
SoFCDocumentObjectAction ()
~SoFCDocumentObjectAction () override
void setHandled ()
SbBool isHandled () const
Static Public Member Functions
static void initClass ()
static void finish ()
Public Attributes
SbString documentName
SbString objectName
SbString componentName
Protected Member Functions
void beginTraversal (SoNode *node) override
Detailed Description
The SoFCDocumentObjectAction class is used to get the name of the document, object and component at a certain position of an SoFCSelection node.
Author
Werner Mayer
Definition at line 220 of file SoFCSelectionAction.h.
Constructor & Destructor Documentation
SoFCDocumentObjectAction()
SoFCDocumentObjectAction::SoFCDocumentObjectAction ()
Definition at line 695 of file SoFCSelectionAction.cpp.
~SoFCDocumentObjectAction()
SoFCDocumentObjectAction::~SoFCDocumentObjectAction () override default
Member Function Documentation
beginTraversal()
void SoFCDocumentObjectAction::beginTraversal (SoNode * node) override protected
Definition at line 702 of file SoFCSelectionAction.cpp.
finish()
void SoFCDocumentObjectAction::finish () static
Definition at line 690 of file SoFCSelectionAction.cpp.
Referenced by drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::accept(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::accept(), draftguitools.gui_split.Split::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_subelements.SubelementHighlight::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rotate.Rotate::action(), draftguitools.gui_fillets.Fillet::action(), draftguitools.gui_move.Move::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_arcs.Arc::action(), draftguitools.gui_texts.Text::action(), draftguitools.gui_scale.Scale::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_trimex.Trimex::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_styles.ApplyStyle::Activated(), draftguitools.gui_join.Join::Activated(), draftguitools.gui_draft2sketch.Draft2Sketch::Activated(), draftguitools.gui_downgrade.Downgrade::Activated(), draftguitools.gui_upgrade.Upgrade::Activated(), draftguitools.gui_shape2dview.Shape2DView::Activated(), draftguitools.gui_facebinders.Facebinder::Activated(), draftguitools.gui_subelements.SubelementHighlight::Activated(), draftguitools.gui_wire2spline.WireToBSpline::Activated(), draftguitools.gui_clone.Clone::Activated(), draftguitools.gui_dimensions.Dimension::Activated(), draftguitools.gui_edit.Edit::Activated(), draftguitools.gui_selectplane.Draft_SelectPlane::check_selection(), DraftGui.DraftToolBar::checkSpecialChars(), draftguitools.gui_points.Point::click(), draftguitools.gui_orthoarray.OrthoArray::completed(), draftguitools.gui_polararray.PolarArray::completed(), draftguitools.gui_circulararray.CircularArray::completed(), draftguitools.gui_labels.Label::create(), bimcommands.BimText.BIM_Text::createObject(), draftguitools.gui_rectangles.Rectangle::createObject(), draftguitools.gui_ellipses.Ellipse::createObject(), draftguitools.gui_texts.Text::createObject(), draftviewproviders.view_text.ViewProviderText::createObject(), draftguitools.gui_stretch.Stretch::doStretch(), draftguitools.gui_fillets.Fillet::draw_arc(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), DraftGui.DraftToolBar::editUi(), DraftGui.DraftToolBar::escape(), Gui::SoFCDB::finish(), draftguitools.gui_move.Move::get_object_selection(), draftguitools.gui_rotate.Rotate::get_object_selection(), draftguitools.gui_scale.Scale::get_object_selection(), draftguitools.gui_arcs.Arc_3Points::getPoint(), draftguitools.gui_edit.Edit::keyPressed(), draftguitools.gui_dimensions.Dimension::numericInput(), draftguitools.gui_offset.Offset::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), draftguitools.gui_trimex.Trimex::numericRadius(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_align(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_auto(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_center(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_front(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_move(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_next(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_previous(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_side(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_top(), bimcommands.BimShape2DView.BIM_Shape2DView::proceed(), draftguitools.gui_join.Join::proceed(), draftguitools.gui_subelements.SubelementHighlight::proceed(), draftguitools.gui_draft2sketch.Draft2Sketch::proceed(), draftguitools.gui_downgrade.Downgrade::proceed(), bimcommands.BimSlab.BIM_Slab::proceed(), draftguitools.gui_upgrade.Upgrade::proceed(), draftguitools.gui_facebinders.Facebinder::proceed(), draftguitools.gui_pathtwistedarray.PathTwistedArray::proceed(), draftguitools.gui_shape2dview.Shape2DView::proceed(), draftguitools.gui_clone.Clone::proceed(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_pointarray.PointArray::proceed(), draftguitools.gui_patharray.PathArray::proceed(), draftguitools.gui_trimex.Trimex::proceed(), draftguitools.gui_edit.Edit::proceed(), draftguitools.gui_selectplane.Draft_SelectPlane::reject(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::reject(), drafttaskpanels.task_polararray.TaskPanelPolarArray::reject(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::reject(), and draftguitools.gui_edit.Edit::setTrackers().
initClass()
void SoFCDocumentObjectAction::initClass () static
The order of the defined SO_ACTION_ADD_METHOD statements is very important. First the base classes and afterwards subclasses of them must be listed, otherwise the registered methods of subclasses will be overridden. For more details see the thread in the Coin3d forum https://www.coin3d.org/pipermail/coin-discuss/2004-May/004346.html. This means that SoSwitch must be listed after SoGroup and SoFCSelection after SoSeparator because both classes inherits the others.
Definition at line 651 of file SoFCSelectionAction.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
isHandled()
SbBool SoFCDocumentObjectAction::isHandled () const
Definition at line 717 of file SoFCSelectionAction.cpp.
Referenced by Gui::View3DInventorPy::getObjectInfo(), Gui::View3DInventorPy::getObjectsInfo(), and Gui::View3DInventor::getObjInfoRay().
setHandled()
void SoFCDocumentObjectAction::setHandled ()
Definition at line 712 of file SoFCSelectionAction.cpp.
Member Data Documentation
componentName
SbString Gui::SoFCDocumentObjectAction::componentName
Definition at line 243 of file SoFCSelectionAction.h.
Referenced by Gui::View3DInventorPy::getObjectInfo(), Gui::View3DInventorPy::getObjectsInfo(), and Gui::View3DInventor::getObjInfoRay().
documentName
SbString Gui::SoFCDocumentObjectAction::documentName
Definition at line 241 of file SoFCSelectionAction.h.
Referenced by Gui::SoFCSelection::doAction(), Gui::View3DInventorPy::getObjectInfo(), Gui::View3DInventorPy::getObjectsInfo(), and Gui::View3DInventor::getObjInfoRay().
objectName
SbString Gui::SoFCDocumentObjectAction::objectName
Definition at line 242 of file SoFCSelectionAction.h.
Referenced by Gui::View3DInventorPy::getObjectInfo(), Gui::View3DInventorPy::getObjectsInfo(), and Gui::View3DInventor::getObjInfoRay().
The documentation for this class was generated from the following files:
SoFCSelectionAction.h
SoFCSelectionAction.cpp