FreeCAD: Spreadsheet::SheetObserver Class Reference
Spreadsheet::SheetObserver Class Reference
#include <SheetObserver.h>
Public Member Functions
SheetObserver (App::Document *document, PropertySheet *_sheet)
~SheetObserver () override=default
void slotCreatedObject (const App::DocumentObject &Obj) override
void slotDeletedObject (const App::DocumentObject &Obj) override
void slotChangedObject (const App::DocumentObject &Obj, const App::Property &Prop) override
void ref ()
bool unref ()
App::Document * getDocument () const
Public Member Functions inherited from App::DocumentObserver
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
void attachDocument (Document *)
void detachDocument ()
Additional Inherited Members
Protected Member Functions inherited from App::DocumentObserver
Document * getDocument () const
Detailed Description
Definition at line 54 of file SheetObserver.h.
Constructor & Destructor Documentation
SheetObserver()
SheetObserver::SheetObserver (App::Document * document, PropertySheet * _sheet)
The SheetObserver constructor.
Parameters
document The Document we are observing
_sheet The sheet owning this observer.
Definition at line 40 of file SheetObserver.cpp.
~SheetObserver()
Spreadsheet::SheetObserver::~SheetObserver () override default
Member Function Documentation
getDocument()
App::Document* Spreadsheet::SheetObserver::getDocument () const inline
Definition at line 64 of file SheetObserver.h.
ref()
void SheetObserver::ref ()
Increase reference count.
Definition at line 96 of file SheetObserver.cpp.
slotChangedObject()
void SheetObserver::slotChangedObject (const App::DocumentObject & Obj, const App::Property & Prop) override virtual
Invoke the sheets recomputeDependants when a change to a Property occurs.
Reimplemented from App::DocumentObserver.
Definition at line 71 of file SheetObserver.cpp.
References App::Property::getName(), App::ExtensionContainer::getPropertyName(), and App::DocumentObject::Label.
slotCreatedObject()
void SheetObserver::slotCreatedObject (const App::DocumentObject & Obj) override virtual
Invalidate cells that depend on this document object.
Reimplemented from App::DocumentObserver.
Definition at line 50 of file SheetObserver.cpp.
References Spreadsheet::PropertySheet::invalidateDependants().
slotDeletedObject()
void SheetObserver::slotDeletedObject (const App::DocumentObject & Obj) override virtual
Invalidate cells that depend on this document object.
Reimplemented from App::DocumentObserver.
Definition at line 60 of file SheetObserver.cpp.
References Spreadsheet::PropertySheet::deletedDocumentObject(), and Spreadsheet::PropertySheet::invalidateDependants().
unref()
bool SheetObserver::unref ()
Decrease reference count.
Definition at line 106 of file SheetObserver.cpp.
The documentation for this class was generated from the following files:
SheetObserver.h
SheetObserver.cpp