FreeCAD: draftviewproviders.view_dimension.ViewProviderDimensionBase Class Reference
draftviewproviders.view_dimension.ViewProviderDimensionBase Class Reference
DRAFT » draftviewproviders
Public Member Functions
def set_text_properties (self, vobj, properties)
def set_units_properties (self, vobj, properties)
def set_graphics_properties (self, vobj, properties)
def getIcon (self)
Public Member Functions inherited from draftviewproviders.view_draft_annotation.ViewProviderDraftAnnotation
def __init__ (self, vobj)
def set_properties (self, vobj)
def set_annotation_properties (self, vobj, properties)
def dumps (self)
def loads (self, state)
def attach (self, vobj)
def updateData (self, obj, prop)
def getDisplayModes (self, vobj)
def getDefaultDisplayMode (self)
def setDisplayMode (self, mode)
def onChanged (self, vobj, prop)
def execute (self, vobj)
def setEdit (self, vobj, mode)
def unsetEdit (self, vobj, mode)
def doubleClicked (self, vobj)
def setupContextMenu (self, vobj, menu)
def edit (self)
Additional Inherited Members
Public Attributes inherited from draftviewproviders.view_draft_annotation.ViewProviderDraftAnnotation
Object
wb_before_edit
Detailed Description
The base viewprovider for the Draft Dimensions object.
This class is not used directly, but inherited by dimension
viewproviders like linear, radial, and angular.
Dimension nomeclature
---------------------
The dimension object depends on various variables to draw the lines
that are drawn on 3D view.
::
        |              txt               |      e
    ----b---------a----------------------b----
        |                                |
        |                                |      d
        |                                |
    c  (t)                              (t)   c
From the object class
* `a`, `Dimline`, point through which the dimension line goes through
From the viewprovider class
* `b`, `ArrowType` and `ArrowSize`, the symbol shown on the endpoints
* `c`, `DimOvershoot`, extension to the dimension line going through `a`
* `d`, `ExtLines`, distance to target `(t)`
* `e`, `ExtOvershoot`, extension in the opposite direction to `(t)`
* `txt`, text label showing the value of the measurement
Coin object structure
---------------------
The scenegraph is set from two main nodes.
::
    vobj.node_wld.linecolor
                 .drawstyle
                 .lineswitch_wld.coords
                                .line
                                .marks
                                .marksDimOvershoot
                                .marksExtOvershoot
                 .label_wld.textpos
                           .textcolor
                           .font
                           .text_wld
    vobj.node_scr.linecolor
                 .drawstyle
                 .lineswitch_scr.coords
                                .line
                                .marks
                                .marksDimOvershoot
                                .marksExtOvershoot
                 .label_scr.textpos
                           .textcolor
                           .font
                           .text_scr
Definition at line 57 of file view_dimension.py.
Member Function Documentation
getIcon()
def draftviewproviders.view_dimension.ViewProviderDimensionBase.getIcon (self)
Return the path to the icon used by the viewprovider.
Reimplemented from draftviewproviders.view_draft_annotation.ViewProviderDraftAnnotation.
Reimplemented in draftviewproviders.view_dimension.ViewProviderAngularDimension, and draftviewproviders.view_dimension.ViewProviderLinearDimension.
Definition at line 264 of file view_dimension.py.
set_graphics_properties()
def draftviewproviders.view_dimension.ViewProviderDimensionBase.set_graphics_properties (self, vobj, properties)
Set graphics properties only if they don't already exist.
Reimplemented from draftviewproviders.view_draft_annotation.ViewProviderDraftAnnotation.
Definition at line 193 of file view_dimension.py.
References Arch.QT_TRANSLATE_NOOP.
Referenced by draftviewproviders.view_draft_annotation.ViewProviderDraftAnnotation.set_properties().
set_text_properties()
def draftviewproviders.view_dimension.ViewProviderDimensionBase.set_text_properties (self, vobj, properties)
Set text properties only if they don't already exist.
Reimplemented from draftviewproviders.view_draft_annotation.ViewProviderDraftAnnotation.
Definition at line 117 of file view_dimension.py.
References Arch.QT_TRANSLATE_NOOP.
Referenced by draftviewproviders.view_draft_annotation.ViewProviderDraftAnnotation.set_properties().
set_units_properties()
def draftviewproviders.view_dimension.ViewProviderDimensionBase.set_units_properties (self, vobj, properties)
Set unit properties only if they don't already exist.
Reimplemented from draftviewproviders.view_draft_annotation.ViewProviderDraftAnnotation.
Definition at line 160 of file view_dimension.py.
References Arch.QT_TRANSLATE_NOOP.
Referenced by draftviewproviders.view_draft_annotation.ViewProviderDraftAnnotation.set_properties().
The documentation for this class was generated from the following file:
view_dimension.py