FreeCAD: App::LinkExtension Class Reference
App::LinkExtension Class Reference
#include <Link.h>
Public Member Functions
virtual Base::Type getExtensionTypeId (void) const override
LinkExtension ()
~LinkExtension () override=default
Helpers for defining extended parameter
extended parameter definition (Name, Type, Property_Type, Default, Document, Property_Name, Derived_Property_Type, App_Property_Type, Group)
This helper simply reuses Name as Property_Name, Property_Type as Derived_Property_type, Prop_None as App_Propert_Type
Note: Because PropertyView will merge linked object's properties into ours, we set the default group name as ' Link' with a leading space to try to make our group before others
BOOST_PP_SEQ_FOR_EACH (LINK_PROP_DEFINE, _, BOOST_PP_EXPAND(((Scale, double, App::PropertyFloat, 1.0, "Scale factor", Scale, App::PropertyFloat, App::Prop_None, " Link"))) BOOST_PP_EXPAND(((ScaleVector, Base::Vector3d, App::PropertyVector, Base::Vector3d(1, 1, 1), "Scale factors", ScaleVector, App::PropertyVector, App::Prop_Hidden, " Link"))) BOOST_PP_EXPAND(((ScaleList, std::vector< Base::Vector3d >, App::PropertyVectorList, std::vector< Base::Vector3d >(), "The scale factors for each link element", ScaleList, App::PropertyVectorList, App::Prop_None, " Link"))) BOOST_PP_EXPAND(((VisibilityList, boost::dynamic_bitset<>, App::PropertyBoolList, boost::dynamic_bitset<>(), "The visibility state of each link element", VisibilityList, App::PropertyBoolList, App::Prop_None, " Link"))) BOOST_PP_EXPAND(((PlacementList, std::vector< Base::Placement >, App::PropertyPlacementList, std::vector< Base::Placement >(), "The placement for each link element", PlacementList, App::PropertyPlacementList, App::Prop_None, " Link"))) BOOST_PP_EXPAND(((ElementList, std::vector< App::DocumentObject * >, App::PropertyLinkList, std::vector< App::DocumentObject * >(), "The link element object list", ElementList, App::PropertyLinkList, App::Prop_None, " Link")))) void onExtendedDocumentRestored() override
Public Member Functions inherited from App::LinkBaseExtension
LinkBaseExtension ()
~LinkBaseExtension () override=default
virtual void setProperty (int idx, Property *prop)
Property * getProperty (int idx)
Property * getProperty (const char *)
virtual const std::vector< PropInfo > & getPropertyInfo () const
virtual const PropInfoMap & getPropertyInfoMap () const
PropertyLinkList * _getElementListProperty () const
const std::vector< App::DocumentObject * > & _getElementListValue () const
PropertyBool * _getShowElementProperty () const
bool _getShowElementValue () const
PropertyInteger * _getElementCountProperty () const
int _getElementCountValue () const
std::vector< DocumentObject * > getLinkedChildren (bool filter=true) const
const char * flattenSubname (const char *subname) const
void expandSubname (std::string &subname) const
DocumentObject * getLink (int depth=0) const
Base::Matrix4D getTransform (bool transform) const
Base::Vector3d getScaleVector () const
App::GroupExtension * linkedPlainGroup () const
bool linkTransform () const
const char * getSubName () const
const std::vector< std::string > & getSubElements () const
bool extensionGetSubObject (DocumentObject *&ret, const char *subname, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=false, int depth=0) const override
bool extensionGetSubObjects (std::vector< std::string > &ret, int reason) const override
bool extensionGetLinkedObject (DocumentObject *&ret, bool recurse, Base::Matrix4D *mat, bool transform, int depth) const override
App::DocumentObjectExecReturn * extensionExecute () override
short extensionMustExecute () override
void extensionOnChanged (const Property *p) override
void onExtendedUnsetupObject () override
get called when object is going to be removed from the document
void onExtendedDocumentRestored () override
get called after a document has been fully restored
int extensionSetElementVisible (const char *, bool) override
int extensionIsElementVisible (const char *) override
bool extensionHasChildElement () const override
PyObject * getExtensionPyObject () override
Property * extensionGetPropertyByName (const char *name) const override
find a property by its name
int getElementIndex (const char *subname, const char **psubname=nullptr) const
void elementNameFromIndex (int idx, std::ostream &ss) const
DocumentObject * getContainer ()
const DocumentObject * getContainer () const
void setLink (int index, DocumentObject *obj, const char *subname=nullptr, const std::vector< std::string > &subs=std::vector< std::string >())
DocumentObject * getTrueLinkedObject (bool recurse, Base::Matrix4D *mat=nullptr, int depth=0, bool noElement=false) const
bool hasPlacement () const
void cacheChildLabel (int enable=-1) const
void syncCopyOnChange ()
void setOnChangeCopyObject (App::DocumentObject *obj, OnChangeCopyOptions options)
std::vector< App::DocumentObject * > getOnChangeCopyObjects (std::vector< App::DocumentObject * > *excludes=nullptr, App::DocumentObject *src=nullptr)
bool isLinkedToConfigurableObject () const
void monitorOnChangeCopyObjects (const std::vector< App::DocumentObject * > &objs)
bool isLinkMutated () const
Check if the linked object is a copy on change.
Public Member Functions inherited from App::DocumentObjectExtension
DocumentObjectExtension ()
~DocumentObjectExtension () override
App::DocumentObject * getExtendedObject ()
const App::DocumentObject * getExtendedObject () const
virtual void onExtendedSettingDocument ()
get called after setting the document
virtual void onExtendedSetupObject ()
get called after a brand new object was created
virtual const char * getViewProviderExtensionName () const
Public Member Functions inherited from App::Extension
Extension ()=default
virtual ~Extension ()
virtual void initExtension (App::ExtensionContainer *obj)
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Static Public Member Functions
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Static Public Member Functions inherited from App::LinkBaseExtension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
static int getArrayIndex (const char *subname, const char **psubname=nullptr)
static bool setupCopyOnChange (App::DocumentObject *obj, App::DocumentObject *linked, std::vector< boost::signals2::scoped_connection > *copyOnChangeConns, bool checkExisting)
static bool isCopyOnChangeProperty (App::DocumentObject *obj, const Property &prop)
Static Public Member Functions inherited from App::DocumentObjectExtension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Static Public Member Functions inherited from App::Extension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Protected Member Functions
virtual const App::PropertyData & extensionGetPropertyData (void) const override
Protected Member Functions inherited from App::LinkBaseExtension
void _handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
void parseSubName () const
void update (App::DocumentObject *parent, const Property *prop)
void checkCopyOnChange (App::DocumentObject *parent, const App::Property &prop)
void setupCopyOnChange (App::DocumentObject *parent, bool checkSource=false)
App::DocumentObject * makeCopyOnChange ()
void syncElementList ()
void detachElement (App::DocumentObject *obj)
void detachElements ()
void checkGeoElementMap (const App::DocumentObject *obj, const App::DocumentObject *linked, PyObject **pyObj, const char *postfix) const
void updateGroup ()
void slotChangedPlainGroup (const App::DocumentObject &, const App::Property &)
Protected Member Functions inherited from App::Extension
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
returns true if the property name change was handled by the extension.
virtual bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
returns true if the property type change was handled by the extension.
void initExtensionType (Base::Type type)
Static Protected Member Functions
static const App::PropertyData * extensionGetPropertyDataPtr (void)
Static Protected Member Functions inherited from App::LinkBaseExtension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
Static Protected Member Functions inherited from App::DocumentObjectExtension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
Static Protected Member Functions inherited from App::Extension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Additional Inherited Members
Public Types inherited from App::LinkBaseExtension
enum { LinkModeNone, LinkModeAutoDelete, LinkModeAutoLink, LinkModeAutoUnlink }
enum PropIndex { BOOST_PP_SEQ_FOR_EACH =(LINK_PINDEX_DEFINE, _, ((Placement, Base::Placement, App::PropertyPlacement, Base::Placement(), "Alias to LinkPlacement to make the link object compatibale with other objects",)) ((LinkPlacement, Base::Placement, App::PropertyPlacement, Base::Placement(), "Link placement",)) ((LinkedObject, App::DocumentObject*, App::PropertyLink, 0, "Linked object",)) ((LinkClaimChild, bool, App::PropertyBool, false, "Claim the linked object as a child",)) ((LinkTransform, bool, App::PropertyBool, false, "Set to false to override linked object's placement",)) ((Scale, double, App::PropertyFloat, 1.0, "Scale factor",)) ((ScaleVector, Base::Vector3d, App::PropertyVector, Base::Vector3d(1, 1, 1), "Scale factors",)) ((PlacementList, std::vector<Base::Placement>, App::PropertyPlacementList, std::vector<Base::Placement>(), "The placement for each link element",)) ((ScaleList, std::vector<Base::Vector3d>, App::PropertyVectorList, std::vector<Base::Vector3d>(), "The scale factors for each link element",)) ((VisibilityList, boost::dynamic_bitset<>, App::PropertyBoolList, boost::dynamic_bitset<>(), "The visibility state of each link element",)) ((ElementCount, int, App::PropertyInteger, 0, "Link element count",)) ((ElementList, std::vector<App::DocumentObject*>, App::PropertyLinkList, std::vector<App::DocumentObject*>(), "The link element object list",)) ((ShowElement, bool, App::PropertyBool, true, "Enable link element list",)) ((LinkMode, long, App::PropertyEnumeration, ((long)0), "Link group mode",)) ((LinkExecute, const char*, App::PropertyString, (""), "Link execute function. Default to 'appLinkExecute'. 'None' to disable.",)) ((ColoredElements, App::DocumentObject*, App::PropertyLinkSubHidden, 0, "Link colored elements",)) ((LinkCopyOnChange, long, App::PropertyEnumeration, ((long)0), "Disabled: disable copy on change\n" "Enabled: enable copy linked object on change of any of its properties marked as " "CopyOnChange\n" "Owned: indicate the linked object has been copied and is own owned by the link. And the\n" " the link will try to sync any change of the original linked object back to the " "copy.",)) ((LinkCopyOnChangeSource, App::DocumentObject*, App::PropertyLink, 0, "The copy on change source object",)) ((LinkCopyOnChangeGroup, App::DocumentObject*, App::PropertyLink, 0, "Linked to a internal group object for holding on change copies",)) ((LinkCopyOnChangeTouched, bool, App::PropertyBool, 0, "Indicating the copy on change source object has been changed",))) PropMax }
enum LinkCopyOnChangeType { CopyOnChangeDisabled = 0, CopyOnChangeEnabled = 1, CopyOnChangeOwned = 2, CopyOnChangeTracking = 3 }
enum OnChangeCopyOptions { OnChangeCopyOptions::None = 0, OnChangeCopyOptions::Exclude = 1, OnChangeCopyOptions::ApplyAll = 2 }
using PropInfoMap = std::map< std::string, PropInfo >
using LinkPropMap = std::map< const Property *, std::pair< LinkBaseExtension *, int > >
Public Attributes inherited from App::LinkBaseExtension
PropertyBool _LinkTouched
PropertyInteger _LinkOwner
PropertyLinkList _ChildCache
Protected Attributes inherited from App::LinkBaseExtension
std::vector< Property * > props
std::unordered_set< const App::DocumentObject * > myHiddenElements
std::vector< std::string > mySubElements
std::string mySubName
std::unordered_map< const App::DocumentObject *, boost::signals2::scoped_connection > plainGroupConns
long prevLinkedObjectID = 0
std::unordered_map< std::string, int > myLabelCache
bool enableLabelCache {false}
bool hasOldSubElement {false}
std::vector< boost::signals2::scoped_connection > copyOnChangeConns
std::vector< boost::signals2::scoped_connection > copyOnChangeSrcConns
bool hasCopyOnChange {true}
bool checkingProperty = false
bool pauseCopyOnChange = false
boost::signals2::scoped_connection connCopyOnChangeSource
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Detailed Description
Definition at line 509 of file Link.h.
Constructor & Destructor Documentation
LinkExtension()
LinkExtension::LinkExtension ()
Definition at line 2601 of file Link.cpp.
References getExtensionClassTypeId(), LINK_PARAMS_EXT, and LINK_PROPS_ADD_EXTENSION.
~LinkExtension()
App::LinkExtension::~LinkExtension () override default
Member Function Documentation
BOOST_PP_SEQ_FOR_EACH()
App::LinkExtension::BOOST_PP_SEQ_FOR_EACH (LINK_PROP_DEFINE , _ , BOOST_PP_EXPAND(((Scale, double, App::PropertyFloat, 1.0, "Scale factor", Scale, App::PropertyFloat, App::Prop_None, " Link"))) BOOST_PP_EXPAND(((ScaleVector, Base::Vector3d, App::PropertyVector, Base::Vector3d(1, 1, 1), "Scale factors", ScaleVector, App::PropertyVector, App::Prop_Hidden, " Link"))) BOOST_PP_EXPAND(((ScaleList, std::vector< Base::Vector3d >, App::PropertyVectorList, std::vector< Base::Vector3d >(), "The scale factors for each link element", ScaleList, App::PropertyVectorList, App::Prop_None, " Link"))) BOOST_PP_EXPAND(((VisibilityList, boost::dynamic_bitset<>, App::PropertyBoolList, boost::dynamic_bitset<>(), "The visibility state of each link element", VisibilityList, App::PropertyBoolList, App::Prop_None, " Link"))) BOOST_PP_EXPAND(((PlacementList, std::vector< Base::Placement >, App::PropertyPlacementList, std::vector< Base::Placement >(), "The placement for each link element", PlacementList, App::PropertyPlacementList, App::Prop_None, " Link"))) BOOST_PP_EXPAND(((ElementList, std::vector< App::DocumentObject * >, App::PropertyLinkList, std::vector< App::DocumentObject * >(), "The link element object list", ElementList, App::PropertyLinkList, App::Prop_None, " Link")))) inline override
Definition at line 607 of file Link.h.
References LINK_PARAMS_EXT, and LINK_PROPS_SET.
create()
void * App::LinkExtension::create (void) static
Definition at line 2599 of file Link.cpp.
Referenced by draftguitools.gui_labels.Label::action().
extensionGetPropertyData()
const App::PropertyData & App::LinkExtension::extensionGetPropertyData (void) const override protected virtual
Reimplemented from App::LinkBaseExtension.
Definition at line 2599 of file Link.cpp.
extensionGetPropertyDataPtr()
const App::PropertyData * App::LinkExtension::extensionGetPropertyDataPtr (void) static protected
Definition at line 2599 of file Link.cpp.
getExtensionClassTypeId()
Base::Type App::LinkExtension::getExtensionClassTypeId (void) static
Definition at line 2599 of file Link.cpp.
Referenced by LinkExtension().
getExtensionTypeId()
Base::Type App::LinkExtension::getExtensionTypeId (void) const override virtual
Reimplemented from App::LinkBaseExtension.
Definition at line 2599 of file Link.cpp.
init()
void App::LinkExtension::init (void) static
Definition at line 2599 of file Link.cpp.
Referenced by App::Application::initTypes(), and DocumentObject.DocumentObject::onChanged().
The documentation for this class was generated from the following files:
Link.h
Link.cpp