FreeCAD: Import::WriterIges Class Reference
Import::WriterIges Class Reference
#include <WriterIges.h>
Public Member Functions
WriterIges (const Base::FileInfo &file)
void write (Handle(TDocStd_Document) hDoc) const
Detailed Description
Definition at line 53 of file WriterIges.h.
Constructor & Destructor Documentation
WriterIges()
WriterIges::WriterIges (const Base::FileInfo & file) explicit
Definition at line 42 of file WriterIges.cpp.
Member Function Documentation
write()
void WriterIges::write (Handle(TDocStd_Document) hDoc) const
Definition at line 46 of file WriterIges.cpp.
References Part::encodeFilename(), DrawingExample::file, Part::Interface::writeIgesHeaderAuthor(), Part::Interface::writeIgesHeaderCompany(), and Part::Interface::writeIgesHeaderProduct().
The documentation for this class was generated from the following files:
WriterIges.h
WriterIges.cpp