FreeCAD: Path.Post.scripts.philips_post Namespace Reference
Path.Post.scripts.philips_post Namespace Reference
Functions
def processArguments (argstring)
def mkHeader (selection)
def angleUnder180 (command, lastX, lastY, x, y, i, j)
def mapGCode (command)
def linenumberify (GCodeString)
def export (objectslist, filename, argstring)
Variables
TOOLTIP
COMMAND_SPACE
MACHINE_NAME
CORNER_MIN
CORNER_MAX
UNITS
UNITS_INCLUDED
COMMENT
SHOW_EDITOR
LINENUMBERS
STARTLINENR
LINENUMBER_INCREMENT
MODAL
MODALPARAMS
SWAP_G2_G3
SWAP_Y_Z
ABSOLUTE_CIRCLE_CENTER
USE_RADIUS_IF_POSSIBLE
RADIUS_COMMENT
GCODE_MAP
AXIS_DECIMALS
FEED_DECIMALS
SPINDLE_DECIMALS
SUPPRESS_ZERO_FEED
parser
prog
add_help
action = "store_true",
help = "don't pop up editor before writing output",
TOOLTIP_ARGS
GCODE_HEADER
GCODE_FOOTER
linenr
Function Documentation
angleUnder180()
def Path.Post.scripts.philips_post.angleUnder180 (command, lastX, lastY, x, y, i, j)
Definition at line 293 of file philips_post.py.
Referenced by Path.Post.scripts.philips_post.export().
export()
def Path.Post.scripts.philips_post.export (objectslist, filename, argstring)
Definition at line 354 of file philips_post.py.
References Path.Post.scripts.philips_post.angleUnder180(), Path.Base.SetupSheet.dict, Path.Post.scripts.philips_post.linenumberify(), Path.Post.scripts.philips_post.mapGCode(), Path.Post.scripts.philips_post.mkHeader(), and Path.Post.scripts.refactored_centroid_post.str.
linenumberify()
def Path.Post.scripts.philips_post.linenumberify (GCodeString)
Definition at line 334 of file philips_post.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.philips_post.export(), and Path.Post.scripts.philips_post.mkHeader().
mapGCode()
def Path.Post.scripts.philips_post.mapGCode (command)
Definition at line 321 of file philips_post.py.
Referenced by Path.Post.scripts.philips_post.export().
mkHeader()
def Path.Post.scripts.philips_post.mkHeader (selection)
Definition at line 246 of file philips_post.py.
References Path.Post.scripts.philips_post.linenumberify().
Referenced by Path.Post.scripts.philips_post.export().
processArguments()
def Path.Post.scripts.philips_post.processArguments (argstring)
Definition at line 231 of file philips_post.py.
Variable Documentation
ABSOLUTE_CIRCLE_CENTER
Path.Post.scripts.philips_post.ABSOLUTE_CIRCLE_CENTER
Definition at line 140 of file philips_post.py.
action
string Path.Post.scripts.philips_post.action = "store_true",
Definition at line 210 of file philips_post.py.
add_help
Path.Post.scripts.philips_post.add_help
Definition at line 209 of file philips_post.py.
AXIS_DECIMALS
Path.Post.scripts.philips_post.AXIS_DECIMALS
Definition at line 182 of file philips_post.py.
COMMAND_SPACE
Path.Post.scripts.philips_post.COMMAND_SPACE
Definition at line 49 of file philips_post.py.
COMMENT
Path.Post.scripts.philips_post.COMMENT
Definition at line 68 of file philips_post.py.
CORNER_MAX
Path.Post.scripts.philips_post.CORNER_MAX
Definition at line 53 of file philips_post.py.
CORNER_MIN
Path.Post.scripts.philips_post.CORNER_MIN
Definition at line 52 of file philips_post.py.
FEED_DECIMALS
Path.Post.scripts.philips_post.FEED_DECIMALS
Definition at line 186 of file philips_post.py.
GCODE_FOOTER
Path.Post.scripts.philips_post.GCODE_FOOTER
Definition at line 281 of file philips_post.py.
GCODE_HEADER
Path.Post.scripts.philips_post.GCODE_HEADER
Definition at line 273 of file philips_post.py.
GCODE_MAP
Path.Post.scripts.philips_post.GCODE_MAP
Definition at line 166 of file philips_post.py.
help
string Path.Post.scripts.philips_post.help = "don't pop up editor before writing output",
Definition at line 210 of file philips_post.py.
linenr
Path.Post.scripts.philips_post.linenr
Definition at line 290 of file philips_post.py.
LINENUMBER_INCREMENT
Path.Post.scripts.philips_post.LINENUMBER_INCREMENT
Definition at line 97 of file philips_post.py.
LINENUMBERS
Path.Post.scripts.philips_post.LINENUMBERS
Definition at line 84 of file philips_post.py.
MACHINE_NAME
Path.Post.scripts.philips_post.MACHINE_NAME
Definition at line 51 of file philips_post.py.
MODAL
Path.Post.scripts.philips_post.MODAL
Definition at line 103 of file philips_post.py.
MODALPARAMS
Path.Post.scripts.philips_post.MODALPARAMS
Definition at line 113 of file philips_post.py.
parser
Path.Post.scripts.philips_post.parser
Definition at line 209 of file philips_post.py.
prog
Path.Post.scripts.philips_post.prog
Definition at line 209 of file philips_post.py.
RADIUS_COMMENT
Path.Post.scripts.philips_post.RADIUS_COMMENT
Definition at line 158 of file philips_post.py.
SHOW_EDITOR
Path.Post.scripts.philips_post.SHOW_EDITOR
Definition at line 79 of file philips_post.py.
SPINDLE_DECIMALS
Path.Post.scripts.philips_post.SPINDLE_DECIMALS
Definition at line 190 of file philips_post.py.
STARTLINENR
Path.Post.scripts.philips_post.STARTLINENR
Definition at line 90 of file philips_post.py.
SUPPRESS_ZERO_FEED
Path.Post.scripts.philips_post.SUPPRESS_ZERO_FEED
Definition at line 194 of file philips_post.py.
SWAP_G2_G3
Path.Post.scripts.philips_post.SWAP_G2_G3
Definition at line 124 of file philips_post.py.
SWAP_Y_Z
Path.Post.scripts.philips_post.SWAP_Y_Z
Definition at line 131 of file philips_post.py.
TOOLTIP
Path.Post.scripts.philips_post.TOOLTIP
Definition at line 35 of file philips_post.py.
TOOLTIP_ARGS
Path.Post.scripts.philips_post.TOOLTIP_ARGS
Definition at line 228 of file philips_post.py.
UNITS
Path.Post.scripts.philips_post.UNITS
Definition at line 55 of file philips_post.py.
UNITS_INCLUDED
Path.Post.scripts.philips_post.UNITS_INCLUDED
Definition at line 61 of file philips_post.py.
USE_RADIUS_IF_POSSIBLE
Path.Post.scripts.philips_post.USE_RADIUS_IF_POSSIBLE
Definition at line 145 of file philips_post.py.