FreeCAD: MeshCore::MeshSegmentAlgorithm Class Reference
MeshCore::MeshSegmentAlgorithm Class Reference
#include <Segmentation.h>
Public Member Functions
MeshSegmentAlgorithm (const MeshKernel &kernel)
void FindSegments (std::vector< MeshSurfaceSegmentPtr > &)
Detailed Description
Definition at line 407 of file Mesh/App/Core/Segmentation.h.
Constructor & Destructor Documentation
MeshSegmentAlgorithm()
MeshCore::MeshSegmentAlgorithm::MeshSegmentAlgorithm (const MeshKernel & kernel) inline explicit
Definition at line 410 of file Mesh/App/Core/Segmentation.h.
Member Function Documentation
FindSegments()
void MeshSegmentAlgorithm::FindSegments (std::vector< MeshSurfaceSegmentPtr > & segm)
Definition at line 556 of file Mesh/App/Core/Segmentation.cpp.
References MeshCore::MeshAlgorithm::CountFacetFlag(), SCL.SimpleDataTypes::f, MeshCore::FACET_INDEX_MAX, MeshCore::MeshKernel::GetFacets(), MeshCore::MeshAlgorithm::ResetFacetFlag(), MeshCore::MeshAlgorithm::ResetFacetsFlag(), MeshCore::MeshFacet::VISIT, and MeshCore::MeshKernel::VisitNeighbourFacets().
Referenced by MeshGui::Segmentation::accept(), ReverseEngineeringGui::Segmentation::accept(), MeshGui::SegmentationBestFit::accept(), ReverseEngineeringGui::SegmentationManual::Private::findGeometry(), and Mesh::MeshObject::getSegmentsOfType().
The documentation for this class was generated from the following files:
Mesh/App/Core/Segmentation.h
Mesh/App/Core/Segmentation.cpp