FreeCAD: SketcherGui::Workbench Class Reference
SketcherGui::Workbench Class Reference
#include <Workbench.h>
Public Member Functions
Workbench ()
~Workbench () override
Public Member Functions inherited from Gui::StdWorkbench
StdWorkbench ()
~StdWorkbench () override
void setupContextMenu (const char *recipient, MenuItem *) const override
void createMainWindowPopupMenu (MenuItem *) const override
Public Member Functions inherited from Gui::Workbench
Workbench ()
~Workbench () override
std::string name () const
void setName (const std::string &)
PyObject * getPyObject () override
void createContextMenu (const char *recipient, MenuItem *) const
bool activate ()
void retranslate () const
virtual void deactivated ()
void addTaskWatcher (const std::vector< Gui::TaskView::TaskWatcher * > &Watcher)
helper to add TaskWatcher to the TaskView
void removeTaskWatcher ()
remove the added TaskWatcher
std::list< std::string > listToolbars () const
std::list< std::pair< std::string, std::list< std::string > > > getToolbarItems () const
Shows a list of all toolbars and their commands.
std::list< std::string > listMenus () const
std::list< std::string > listCommandbars () const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static void enterEditMode ()
static void leaveEditMode ()
Static Public Member Functions inherited from Gui::Workbench
static void createLinkMenu (MenuItem *)
static void addPermanentMenuItem (const std::string &cmd, const std::string &after)
static void removePermanentMenuItem (const std::string &cmd)
Removes the command cmd from the permanent menu items.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions
Gui::MenuItem * setupMenuBar () const override
Gui::ToolBarItem * setupToolBars () const override
Gui::ToolBarItem * setupCommandBars () const override
void activated () override
Protected Member Functions inherited from Gui::StdWorkbench
DockWindowItems * setupDockWindows () const override
Protected Member Functions inherited from Gui::Workbench
void addPermanentMenuItems (MenuItem *) const
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Author
Werner Mayer
Definition at line 59 of file Mod/Sketcher/Gui/Workbench.h.
Constructor & Destructor Documentation
Workbench()
Workbench::Workbench ()
Definition at line 53 of file Mod/Sketcher/Gui/Workbench.cpp.
~Workbench()
Workbench::~Workbench () override
Definition at line 56 of file Mod/Sketcher/Gui/Workbench.cpp.
Member Function Documentation
activated()
void Workbench::activated () override protected virtual
Run some actions when the workbench gets activated.
Reimplemented from Gui::Workbench.
Definition at line 178 of file Mod/Sketcher/Gui/Workbench.cpp.
References Gui::Application::activeDocument(), toolbit-attributes::doc, Gui::ToolBarManager::ForceAvailable, Gui::ToolBarManager::getInstance(), Gui::Application::Instance, SketcherGui::isSketchInEdit(), and Gui::ToolBarManager::setState().
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::set_status_filter().
enterEditMode()
void Workbench::enterEditMode () static
Definition at line 201 of file Mod/Sketcher/Gui/Workbench.cpp.
References Gui::ToolBarManager::ForceAvailable, Gui::ToolBarManager::ForceHidden, Gui::ToolBarManager::getInstance(), Gui::ToolBarManager::SaveState, and Gui::ToolBarManager::setState().
Referenced by SketcherGui::ViewProviderSketch::setEdit().
leaveEditMode()
void Workbench::leaveEditMode () static
Definition at line 215 of file Mod/Sketcher/Gui/Workbench.cpp.
References Gui::WorkbenchManager::active(), Gui::ToolBarManager::getInstance(), Gui::WorkbenchManager::instance(), Gui::ToolBarManager::RestoreDefault, Gui::ToolBarManager::SaveState, and Gui::ToolBarManager::setState().
Referenced by SketcherGui::ViewProviderSketch::unsetEdit().
setupCommandBars()
Gui::ToolBarItem * Workbench::setupCommandBars () const override protected virtual
Defines the standard command bars.
Reimplemented from Gui::StdWorkbench.
Definition at line 151 of file Mod/Sketcher/Gui/Workbench.cpp.
setupMenuBar()
Gui::MenuItem * Workbench::setupMenuBar () const override protected virtual
Defines the standard menus.
Reimplemented from Gui::StdWorkbench.
Definition at line 59 of file Mod/Sketcher/Gui/Workbench.cpp.
References SketcherGui::addSketcherWorkbenchBSplines(), SketcherGui::addSketcherWorkbenchConstraints(), SketcherGui::addSketcherWorkbenchGeometries(), SketcherGui::addSketcherWorkbenchSketchActions(), SketcherGui::addSketcherWorkbenchSketchEditModeActions(), SketcherGui::addSketcherWorkbenchTools(), SketcherGui::addSketcherWorkbenchVisual(), Gui::MenuItem::findItem(), Gui::MenuItem::insertItem(), and Gui::MenuItem::setCommand().
setupToolBars()
Gui::ToolBarItem * Workbench::setupToolBars () const override protected virtual
Defines the standard toolbars.
Reimplemented from Gui::StdWorkbench.
Definition at line 105 of file Mod/Sketcher/Gui/Workbench.cpp.
References SketcherGui::addSketcherWorkbenchBSplines(), SketcherGui::addSketcherWorkbenchConstraints(), SketcherGui::addSketcherWorkbenchEditTools(), SketcherGui::addSketcherWorkbenchGeometries(), SketcherGui::addSketcherWorkbenchSketchActions(), SketcherGui::addSketcherWorkbenchSketchEditModeActions(), SketcherGui::addSketcherWorkbenchTools(), SketcherGui::addSketcherWorkbenchVisual(), Gui::ToolBarItem::setCommand(), and Gui::ToolBarItem::Unavailable.
The documentation for this class was generated from the following files:
Mod/Sketcher/Gui/Workbench.h
Mod/Sketcher/Gui/Workbench.cpp