FreeCAD: ImportGui::ImpExpDxfReadGui Class Reference
ImportGui::ImpExpDxfReadGui Class Reference
#include <ImpExpDxfGui.h>
Public Member Functions
ImpExpDxfReadGui (const std::string &filepath, App::Document *pcDoc)
Public Member Functions inherited from Import::ImpExpDxfRead
ImpExpDxfRead (const std::string &filepath, App::Document *pcDoc)
ImpExpDxfRead (const ImpExpDxfRead &)=delete
ImpExpDxfRead (ImpExpDxfRead &&)=delete
void operator= (const ImpExpDxfRead &)=delete
void operator= (ImpExpDxfRead &&)=delete
~ImpExpDxfRead () override
bool ReadEntitiesSection () override
bool OnReadBlock (const std::string &name, int flags) override
void OnReadLine (const Base::Vector3d &start, const Base::Vector3d &end, bool hidden) override
void OnReadPoint (const Base::Vector3d &start) override
void OnReadText (const Base::Vector3d &point, double height, const std::string &text, double rotation) override
void OnReadArc (const Base::Vector3d &start, const Base::Vector3d &end, const Base::Vector3d &center, bool dir, bool hidden) override
void OnReadCircle (const Base::Vector3d &start, const Base::Vector3d &center, bool dir, bool hidden) override
void OnReadEllipse (const Base::Vector3d &center, double major_radius, double minor_radius, double rotation, double start_angle, double end_angle, bool dir) override
void OnReadSpline (struct SplineData &sd) override
void OnReadInsert (const Base::Vector3d &point, const Base::Vector3d &scale, const std::string &name, double rotation) override
void ExpandInsert (const std::string &name, const Base::Matrix4D &transform, const Base::Vector3d &point, double rotation, const Base::Vector3d &scale)
void OnReadDimension (const Base::Vector3d &start, const Base::Vector3d &end, const Base::Vector3d &point, double rotation) override
void OnReadPolyline (std::list< VertexInfo > &, int flags) override
std::string Deformat (const char *text)
std::string getOptionSource ()
void setOptionSource (const std::string &sourceName)
void setOptions ()
Public Member Functions inherited from CDxfRead
CDxfRead (const std::string &filepath)
CDxfRead (const CDxfRead &)=delete
CDxfRead (const CDxfRead &&)=delete
CDxfRead & operator= (const CDxfRead &)=delete
CDxfRead & operator= (const CDxfRead &&)=delete
virtual ~CDxfRead ()
bool Failed () const
void DoRead (bool ignore_errors=false)
virtual void StartImport ()
virtual void FinishImport ()
bool IgnoreErrors () const
bool LineTypeIsHidden () const
Protected Member Functions
void ApplyGuiStyles (Part::Feature *object) const override
void ApplyGuiStyles (App::FeaturePython *object) const override
Protected Member Functions inherited from Import::ImpExpDxfRead
PyObject * getDraftModule ()
CDxfRead::Layer * MakeLayer (const std::string &name, ColorIndex_t color, std::string &&lineType) override
Protected Member Functions inherited from CDxfRead
void SetAdditionalScaling (double scaling)
bool ExplodePolyline (std::list< VertexInfo > &, int flags)
bool ReadBlockContents ()
bool SkipBlockContents ()
template<typename... args>
void UnsupportedFeature (const char *format, args &&... argValues)
Additional Inherited Members
Static Public Member Functions inherited from CDxfRead
static App::Color ObjectColor (ColorIndex_t colorIndex)
Protected Types inherited from Import::ImpExpDxfRead
using FeaturePythonBuilder = std::function< App::FeaturePython *(const Base::Matrix4D &transform)>
Protected Types inherited from CDxfRead
using eEntityMergeType_t = enum { MergeShapes, SingleShapes, DraftObjects }
Static Protected Member Functions inherited from CDxfRead
template<typename... args>
static void ImportError (const char *format, args &&... argValues)
template<typename... args>
static void ImportObservation (const char *format, args &&... argValues)
Protected Attributes inherited from CDxfRead
bool m_preserveLayers = true
bool m_preserveColors = true
eEntityMergeType_t m_mergeOption = DraftObjects
bool m_importAnnotations = true
bool m_importPoints = true
bool m_importPaperSpaceEntities = false
bool m_importHiddenBlocks = false
bool m_importFrozenLayers = false
bool m_importHiddenLayers = true
eDXFVersion_t m_version = RUnknown
std::map< std::string, Layer * > Layers
CommonEntityAttributes m_entityAttributes
Base::Matrix4D OCSOrientationTransform
Detailed Description
Definition at line 57 of file ImpExpDxfGui.h.
Constructor & Destructor Documentation
ImpExpDxfReadGui()
ImpExpDxfReadGui::ImpExpDxfReadGui (const std::string & filepath, App::Document * pcDoc)
Definition at line 64 of file ImpExpDxfGui.cpp.
Member Function Documentation
ApplyGuiStyles() [1/2]
void ImpExpDxfReadGui::ApplyGuiStyles (App::FeaturePython * object) const override protected virtual
Reimplemented from Import::ImpExpDxfRead.
Definition at line 80 of file ImpExpDxfGui.cpp.
References Base::Persistence::getClassTypeId(), Gui::Document::getViewProvider(), CDxfRead::CommonEntityAttributes::m_Color, CDxfRead::m_entityAttributes, and CDxfRead::ObjectColor().
ApplyGuiStyles() [2/2]
void ImpExpDxfReadGui::ApplyGuiStyles (Part::Feature * object) const override protected virtual
Reimplemented from Import::ImpExpDxfRead.
Definition at line 69 of file ImpExpDxfGui.cpp.
References Gui::Document::getViewProvider(), CDxfRead::CommonEntityAttributes::m_Color, CDxfRead::m_entityAttributes, and CDxfRead::ObjectColor().
The documentation for this class was generated from the following files:
ImpExpDxfGui.h
ImpExpDxfGui.cpp