FreeCAD: TechDrawGui::QGIViewPart Class Reference
TechDrawGui::QGIViewPart Class Reference
#include <QGIViewPart.h>
Public Types
enum { Type = QGraphicsItem::UserType + 102 }
Public Types inherited from TechDrawGui::QGIView
enum { Type = QGraphicsItem::UserType + 101 }
Public Member Functions
QGIViewPart ()
~QGIViewPart () override
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
bool sceneEventFilter (QGraphicsItem *watched, QEvent *event) override
void toggleCache (bool state) override
void toggleCosmeticLines (bool state)
void setViewPartFeature (TechDraw::DrawViewPart *obj)
void updateView (bool update=false) override
void tidy ()
QRectF boundingRect () const override
virtual void drawAllFaces ()
virtual void drawAllEdges ()
virtual void drawAllVertexes ()
bool showThisEdge (TechDraw::BaseGeomPtr geom)
virtual void drawAllSectionLines ()
virtual void drawSectionLine (TechDraw::DrawViewSection *s, bool b)
virtual void drawComplexSectionLine (TechDraw::DrawViewSection *viewSection, bool b)
virtual void drawCenterLines (bool b)
virtual void drawAllHighlights ()
virtual void drawHighlight (TechDraw::DrawViewDetail *viewDetail, bool b)
virtual void drawMatting ()
virtual void drawBreakLines ()
if this is a broken view, draw the break lines.
void draw () override
void rotateView () override
virtual void highlightMoved (QGIHighlight *highlight, QPointF newPos)
bool getGroupSelection () override
void setGroupSelection (bool isSelected) override
void setGroupSelection (bool isSelected, const std::vector< std::string > &subNames) override
virtual QGraphicsItem * getQGISubItemByName (const std::string &subName) const
virtual bool removeSelectedCosmetic () const
Public Member Functions inherited from TechDrawGui::QGIView
QGIView ()
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
const char * getViewName () const
const std::string getViewNameAsString () const
void setViewFeature (TechDraw::DrawView *obj)
TechDraw::DrawView * getViewObject () const
MDIViewPage * getMDIViewPage () const
double getScale ()
void hideFrame ()
virtual bool getFrameState ()
virtual void drawBorder ()
virtual void isVisible (bool state)
virtual bool isVisible ()
virtual void drawCaption ()
void makeMark (double xPos, double yPos, QColor color=Qt::red)
void makeMark (Base::Vector3d pos, QColor color=Qt::red)
void makeMark (QPointF pos, QColor color=Qt::red)
void setPosition (qreal xPos, qreal yPos)
qreal getY ()
bool isInnerView () const
void isInnerView (bool state)
QGIViewClip * getClipGroup ()
bool isSnapping ()
void snapPosition (QPointF &position)
void snapSectionView (const TechDraw::DrawViewSection *sectionView, QPointF &newPosition)
Base::Vector3d projItemPagePos (TechDraw::DrawViewPart *item)
void alignTo (QGraphicsItem *, const QString &alignment)
QColor prefNormalColor ()
QColor getNormalColor ()
void setNormalColor (QColor color)
QColor getPreColor ()
QColor getSelectColor ()
QColor getCurrentColor ()
void setCurrentColor (QColor color)
QColor getSettingColor ()
void setSettingColor (QColor color)
virtual void setStack (int z)
virtual void setStackFromVP ()
QFont getFont ()
void setFont (QFont font)
virtual void removeChild (QGIView *child)
virtual void addArbitraryItem (QGraphicsItem *qgi)
virtual void switchParentItem (QGIView *targetParent)
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
Static Public Member Functions
static QPainterPath geomToPainterPath (TechDraw::BaseGeomPtr baseGeom, double rotation=0.0)
static void pathArcSegment (QPainterPath &path, double xc, double yc, double th0, double th1, double rx, double ry, double xAxisRotation)
Helper for pathArc()
static void pathArc (QPainterPath &path, double rx, double ry, double x_axis_rotation, bool large_arc_flag, bool sweep_flag, double x, double y, double curx, double cury)
Draws an arc using QPainterPath path.
Static Public Member Functions inherited from TechDrawGui::QGIView
static Gui::ViewProvider * getViewProvider (App::DocumentObject *obj)
static ViewProviderPage * getViewProviderPage (TechDraw::DrawView *dView)
static int calculateFontPixelSize (double sizeInMillimetres)
static int calculateFontPixelWidth (const QFont &font)
static QString getPrefFont ()
static double getPrefFontSize ()
static double getDimFontSize ()
static int exactFontSize (std::string fontFamily, double nominalSize)
Public Attributes
bool showSection
Protected Member Functions
QPainterPath drawPainterPath (TechDraw::BaseGeomPtr baseGeom) const
void drawViewPart ()
QGIFace * drawFace (TechDraw::FacePtr f, int idx)
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
TechDraw::DrawHatch * faceIsHatched (int i, std::vector< TechDraw::DrawHatch * > hatchObjs) const
TechDraw::DrawGeomHatch * faceIsGeomHatched (int i, std::vector< TechDraw::DrawGeomHatch * > geomObjs) const
void dumpPath (const char *text, QPainterPath path)
void removePrimitives ()
Remove all existing QGIPrimPath items(Vertex, Edge, Face)
void removeDecorations ()
Remove all existing QGIDecoration items(SectionLine, SectionMark, ...)
bool prefFaceEdges ()
bool prefPrintCenters ()
App::Color prefBreaklineColor ()
bool formatGeomFromCosmetic (std::string cTag, QGIEdge *item)
bool formatGeomFromCenterLine (std::string cTag, QGIEdge *item)
bool showCenterMarks ()
bool showVertices ()
Protected Member Functions inherited from TechDrawGui::QGIView
QGIView * getQGIVByName (std::string name)
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QRectF customChildrenBoundingRect () const
void dumpRect (const char *text, QRectF rect)
Base::Reference< ParameterGrp > getParmGroupCol ()
Additional Inherited Members
Static Public Attributes inherited from TechDrawGui::QGIView
static const double DefaultFontSizeInMM = 5.0
Detailed Description
Definition at line 59 of file QGIViewPart.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 66 of file QGIViewPart.h.
Constructor & Destructor Documentation
QGIViewPart()
QGIViewPart::QGIViewPart () explicit
Definition at line 80 of file QGIViewPart.cpp.
~QGIViewPart()
QGIViewPart::~QGIViewPart () override
Definition at line 96 of file QGIViewPart.cpp.
Member Function Documentation
boundingRect()
QRectF QGIViewPart::boundingRect () const override
Definition at line 1172 of file QGIViewPart.cpp.
draw()
void QGIViewPart::draw () override virtual
Reimplemented from TechDrawGui::QGIView.
Reimplemented in TechDrawGui::QGIViewSection.
Definition at line 204 of file QGIViewPart.cpp.
References toolbit-attributes::doc.
Referenced by TechDrawGui::QGIViewSection::draw().
drawAllEdges()
void QGIViewPart::drawAllEdges () virtual
Definition at line 345 of file QGIViewPart.cpp.
References App::Color::asValue(), TechDraw::CENTERLINE, Base::Console(), COSMETICEDGE, TechDraw::ecUVISO, ZVALUE::EDGE, TechDraw::Preferences::getAccessibleColor(), TechDraw::LineFormat::getColor(), TechDraw::LineFormat::getLineNumber(), TechDraw::LineFormat::getStyle(), TechDraw::LineFormat::getVisible(), TechDraw::LineFormat::getWidth(), TechDraw::Preferences::HiddenLineStyle(), ZVALUE::HIDEDGE, TechDraw::GeomFormat::m_format, Base::ConsoleSingleton::Message(), TechDrawGui::QGIEdge::setHiddenEdge(), TechDrawGui::QGIEdge::setLinePen(), TechDrawGui::QGIPrimPath::setNormalColor(), TechDrawGui::QGIEdge::setPrettyNormal(), TechDrawGui::QGIEdge::setSource(), and TechDrawGui::QGIPrimPath::setWidth().
drawAllFaces()
void QGIViewPart::drawAllFaces () virtual
Definition at line 260 of file QGIViewPart.cpp.
References TechDrawGui::QGIFace::addLineSet(), App::Color::asValue(), TechDrawGui::QGIFace::clearLineSets(), TechDrawGui::ViewProviderGeomHatch::ColorPattern, TechDrawGui::QGIFace::draw(), importDXF::drawFace(), ZVALUE::FACE, TechDrawGui::ViewProviderViewPart::FaceColor, TechDraw::DrawGeomHatch::getTrimmedLines(), App::PropertyVector::getValue(), App::PropertyFileIncluded::getValue(), App::PropertyFloat::getValue(), App::PropertyColor::getValue(), TechDrawGui::ViewProviderHatch::HatchColor, TechDrawGui::ViewProviderHatch::HatchOffset, TechDrawGui::ViewProviderHatch::HatchRotation, TechDrawGui::ViewProviderHatch::HatchScale, App::PropertyFileIncluded::isEmpty(), TechDrawGui::QGIFace::isHatched(), TechDraw::DrawHatch::isSvgHatch(), TechDraw::DrawGeomHatch::PatIncluded, TechDraw::DrawGeomHatch::PatternOffset, TechDraw::DrawGeomHatch::PatternRotation, TechDraw::DrawGeomHatch::ScalePattern, TechDrawGui::QGIFace::setDrawEdges(), TechDrawGui::QGIPrimPath::setFillColor(), TechDrawGui::QGIFace::setFillMode(), TechDrawGui::QGIFace::setHatchColor(), TechDrawGui::QGIFace::setHatchFile(), TechDrawGui::QGIFace::setHatchOffset(), TechDrawGui::QGIFace::setHatchRotation(), TechDrawGui::QGIFace::setHatchScale(), TechDrawGui::QGIFace::setLineWeight(), TechDrawGui::QGIFace::setPrettyNormal(), TechDraw::DrawHatch::SvgIncluded, and TechDrawGui::ViewProviderGeomHatch::WeightPattern.
drawAllHighlights()
void QGIViewPart::drawAllHighlights () virtual
Definition at line 926 of file QGIViewPart.cpp.
drawAllSectionLines()
void QGIViewPart::drawAllSectionLines () virtual
Definition at line 674 of file QGIViewPart.cpp.
References Base::Persistence::getClassTypeId(), and TechDraw::DrawViewPart::getSectionRefs().
drawAllVertexes()
void QGIViewPart::drawAllVertexes () virtual
Definition at line 433 of file QGIViewPart.cpp.
References ParameterGrp::GetFloat(), TechDraw::Preferences::getPreferenceGroup(), SplineSurface::i, lineScaleFactor, TechDrawGui::QGIPrimPath::setFillColor(), TechDrawGui::QGIPrimPath::setNormalColor(), TechDrawGui::QGIPrimPath::setPrettyNormal(), TechDrawGui::QGICMark::setPrettyNormal(), TechDrawGui::QGIVertex::setRadius(), TechDrawGui::QGICMark::setSize(), TechDrawGui::QGICMark::setThick(), and ZVALUE::VERTEX.
drawBreakLines()
void QGIViewPart::drawBreakLines () virtual
if this is a broken view, draw the break lines.
Definition at line 1036 of file QGIViewPart.cpp.
References App::Color::asValue(), TechDrawGui::ViewProviderViewPart::BreakLineType, TechDrawGui::QGIBreakLine::draw(), App::PropertyEnumeration::getValue(), TechDraw::DrawUtil::invertY(), ZVALUE::SECTIONLINE, TechDrawGui::QGIBreakLine::setBounds(), TechDrawGui::QGIBreakLine::setBreakColor(), TechDrawGui::QGIBreakLine::setBreakType(), TechDrawGui::QGIBreakLine::setDirection(), TechDrawGui::QGIBreakLine::setLinePen(), and TechDrawGui::QGIDecoration::setWidth().
drawCenterLines()
void QGIViewPart::drawCenterLines (bool b) virtual
Definition at line 871 of file QGIViewPart.cpp.
References SCL.SimpleDataTypes::b, TechDraw::Preferences::CenterLineStyle(), TechDrawGui::QGICenterLine::draw(), TechDraw::DrawViewPart::getBoxX(), TechDraw::DrawViewPart::getBoxY(), App::PropertyBool::getValue(), TechDrawGui::ViewProviderViewPart::HorizCenterLine, ZVALUE::SECTIONLINE, TechDrawGui::QGICenterLine::setBounds(), TechDrawGui::QGIDecoration::setColor(), TechDrawGui::QGICenterLine::setIntersection(), TechDrawGui::QGICenterLine::setLinePen(), and TechDrawGui::QGIDecoration::setWidth().
drawComplexSectionLine()
void QGIViewPart::drawComplexSectionLine (TechDraw::DrawViewSection * viewSection, bool b) virtual
Definition at line 782 of file QGIViewPart.cpp.
References App::Color::asValue(), SCL.SimpleDataTypes::b, TechDrawGui::QGISectionLine::clearChangePoints(), Base::Console(), TechDraw::Preferences::dimFontSizeMM(), TechDrawGui::QGISectionLine::draw(), EWTOLERANCE, TechDraw::Preferences::getAccessibleColor(), App::PropertyQuantity::getValue(), App::PropertyVector::getValue(), App::PropertyString::getValue(), SplineSurface::i, TechDraw::DrawUtil::invertY(), Base::Vector3< float_type >::IsEqual(), Base::ConsoleSingleton::Message(), TechDraw::DrawViewPart::projectPoint(), TechDraw::DrawView::Rotation, ZVALUE::SECTIONLINE, TechDraw::DrawComplexSection::sectionLineEnds(), TechDraw::DrawViewSection::SectionNormal, TechDraw::DrawViewSection::SectionSymbol, TechDrawGui::QGISectionLine::setArrowDirections(), TechDrawGui::QGISectionLine::setChangePoints(), TechDrawGui::QGISectionLine::setDirection(), TechDrawGui::QGISectionLine::setEnds(), TechDrawGui::QGISectionLine::setFont(), TechDrawGui::QGISectionLine::setLinePen(), TechDrawGui::QGISectionLine::setPath(), TechDrawGui::QGISectionLine::setPathMode(), TechDrawGui::QGISectionLine::setSectionColor(), TechDrawGui::QGISectionLine::setShowLine(), TechDrawGui::QGISectionLine::setSymbol(), TechDrawGui::QGIDecoration::setWidth(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
drawFace()
QGIFace * QGIViewPart::drawFace (TechDraw::FacePtr f, int idx) protected
Definition at line 579 of file QGIViewPart.cpp.
References SCL.SimpleDataTypes::f, and TechDrawGui::QGIFace::setOutline().
Referenced by TechDrawGui::QGIViewSection::drawSectionFace().
drawHighlight()
void QGIViewPart::drawHighlight (TechDraw::DrawViewDetail * viewDetail, bool b) virtual
Definition at line 937 of file QGIViewPart.cpp.
References TechDraw::DrawViewDetail::AnchorPoint, App::Color::asValue(), SCL.SimpleDataTypes::b, exportCSG::center(), TechDraw::Preferences::getAccessibleColor(), App::DocumentObject::getNameInDocument(), TechDraw::DrawView::getScale(), App::PropertyQuantity::getValue(), App::PropertyVector::getValue(), App::PropertyFloat::getValue(), App::PropertyString::getValue(), App::PropertyBool::getValue(), ZVALUE::HIGHLIGHT, highlight(), TechDraw::Preferences::labelFontSizeMM(), M_PI, TechDraw::DrawViewDetail::Radius, TechDraw::DrawViewDetail::Reference, TechDraw::DrawView::Rotation, and TechDraw::DrawViewDetail::ShowHighlight.
drawMatting()
void QGIViewPart::drawMatting () virtual
Definition at line 1009 of file QGIViewPart.cpp.
References TechDrawGui::QGIMatting::draw(), Base::Persistence::getClassTypeId(), TechDraw::DrawView::getScale(), App::PropertyFloat::getValue(), App::PropertyBool::getValue(), TechDraw::DrawViewDetail::Radius, draftfunctions.scale::scale(), TechDrawGui::QGIMatting::setRadius(), and TechDraw::DrawViewDetail::ShowMatting.
drawPainterPath()
QPainterPath QGIViewPart::drawPainterPath (TechDraw::BaseGeomPtr baseGeom) const protected
Definition at line 183 of file QGIViewPart.cpp.
drawSectionLine()
void QGIViewPart::drawSectionLine (TechDraw::DrawViewSection * s, bool b) virtual
Definition at line 698 of file QGIViewPart.cpp.
References App::Color::asValue(), SCL.SimpleDataTypes::b, TechDrawGui::QGISectionLine::clearChangePoints(), Base::Console(), TechDraw::Preferences::dimFontSizeMM(), TechDrawGui::QGISectionLine::draw(), EWTOLERANCE, TechDraw::Preferences::getAccessibleColor(), TechDraw::DrawViewSection::getChangePointsFromSectionLine(), TechDraw::DrawView::getScale(), App::PropertyQuantity::getValue(), App::PropertyVector::getValue(), App::PropertyString::getValue(), TechDraw::DrawViewPart::hasGeometry(), src.Mod.PartDesign.Scripts.Gear::l1, src.Mod.PartDesign.Scripts.Gear::l2, Base::ConsoleSingleton::Message(), Base::Vector3< float_type >::Normalize(), TechDraw::DrawViewPart::projectPoint(), TechDraw::DrawView::Rotation, draftfunctions.scale::scale(), ZVALUE::SECTIONLINE, TechDraw::DrawViewSection::sectionLineEnds(), TechDraw::DrawViewSection::SectionNormal, TechDraw::DrawViewSection::SectionSymbol, TechDrawGui::QGISectionLine::setChangePoints(), TechDrawGui::QGISectionLine::setDirection(), TechDrawGui::QGISectionLine::setEnds(), TechDrawGui::QGISectionLine::setFont(), TechDrawGui::QGISectionLine::setLinePen(), TechDrawGui::QGISectionLine::setPathMode(), TechDrawGui::QGISectionLine::setSectionColor(), TechDrawGui::QGISectionLine::setShowLine(), TechDrawGui::QGISectionLine::setSymbol(), TechDrawGui::QGIDecoration::setWidth(), TechDraw::DrawUtil::toQPointF(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
drawViewPart()
void QGIViewPart::drawViewPart () protected
Definition at line 231 of file QGIViewPart.cpp.
dumpPath()
void QGIViewPart::dumpPath (const char * text, QPainterPath path) protected
Definition at line 1147 of file QGIViewPart.cpp.
References Base::Console(), and Base::ConsoleSingleton::Message().
faceIsGeomHatched()
TechDraw::DrawGeomHatch * QGIViewPart::faceIsGeomHatched (int i, std::vector< TechDraw::DrawGeomHatch * > geomObjs) const protected
Definition at line 1124 of file QGIViewPart.cpp.
References TechDraw::DrawUtil::getIndexFromName(), SplineSurface::i, and result.
faceIsHatched()
TechDraw::DrawHatch * QGIViewPart::faceIsHatched (int i, std::vector< TechDraw::DrawHatch * > hatchObjs) const protected
Definition at line 1101 of file QGIViewPart.cpp.
References TechDraw::DrawUtil::getIndexFromName(), SplineSurface::i, result, and toolbit-attributes::s.
formatGeomFromCenterLine()
bool QGIViewPart::formatGeomFromCenterLine (std::string cTag, QGIEdge * item) protected
Definition at line 561 of file QGIViewPart.cpp.
References App::Color::asValue(), TechDraw::Preferences::getAccessibleColor(), TechDraw::LineFormat::getColor(), TechDraw::LineFormat::getLineNumber(), TechDraw::LineFormat::getStyle(), TechDraw::LineFormat::getVisible(), TechDraw::LineFormat::getWidth(), TechDraw::CenterLine::m_format, result, TechDrawGui::QGIEdge::setLinePen(), TechDrawGui::QGIPrimPath::setNormalColor(), and TechDrawGui::QGIPrimPath::setWidth().
formatGeomFromCosmetic()
bool QGIViewPart::formatGeomFromCosmetic (std::string cTag, QGIEdge * item) protected
Definition at line 542 of file QGIViewPart.cpp.
References App::Color::asValue(), TechDraw::Preferences::getAccessibleColor(), TechDraw::LineFormat::getColor(), TechDraw::LineFormat::getLineNumber(), TechDraw::LineFormat::getStyle(), TechDraw::LineFormat::getVisible(), TechDraw::LineFormat::getWidth(), TechDraw::CosmeticEdge::m_format, result, TechDrawGui::QGIEdge::setLinePen(), TechDrawGui::QGIPrimPath::setNormalColor(), and TechDrawGui::QGIPrimPath::setWidth().
geomToPainterPath()
static QPainterPath TechDrawGui::QGIViewPart::geomToPainterPath (TechDraw::BaseGeomPtr baseGeom, double rotation = 0.0) static
getGroupSelection()
bool QGIViewPart::getGroupSelection () override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 1271 of file QGIViewPart.cpp.
getQGISubItemByName()
QGraphicsItem * QGIViewPart::getQGISubItemByName (const std::string & subName) const virtual
Definition at line 1209 of file QGIViewPart.cpp.
References TechDraw::DrawUtil::getGeomTypeFromName(), and TechDraw::DrawUtil::getIndexFromName().
highlightMoved()
void QGIViewPart::highlightMoved (QGIHighlight * highlight, QPointF newPos) virtual
Definition at line 995 of file QGIViewPart.cpp.
References TechDraw::DrawViewDetail::AnchorPoint, toolbit-attributes::doc, App::PropertyVector::getValue(), highlight(), TechDraw::DrawUtil::invertY(), and TechDraw::DrawUtil::toVector3d().
Referenced by TechDrawGui::QGIHighlight::onDragFinished().
itemChange()
QVariant QGIViewPart::itemChange (GraphicsItemChange change, const QVariant & value) override protected
Definition at line 103 of file QGIViewPart.cpp.
paint()
void QGIViewPart::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 1178 of file QGIViewPart.cpp.
pathArc()
static void TechDrawGui::QGIViewPart::pathArc (QPainterPath & path, double rx, double ry, double x_axis_rotation, bool large_arc_flag, bool sweep_flag, double x, double y, double curx, double cury) static
Draws an arc using QPainterPath path.
x_axis_rotation is in radian
pathArcSegment()
static void TechDrawGui::QGIViewPart::pathArcSegment (QPainterPath & path, double xc, double yc, double th0, double th1, double rx, double ry, double xAxisRotation) static
Helper for pathArc()
x_axis_rotation is in radian
prefBreaklineColor()
App::Color QGIViewPart::prefBreaklineColor () protected
Definition at line 1204 of file QGIViewPart.cpp.
References TechDraw::Preferences::getAccessibleColor().
prefFaceEdges()
bool QGIViewPart::prefFaceEdges () protected
Definition at line 1191 of file QGIViewPart.cpp.
References ParameterGrp::GetBool(), TechDraw::Preferences::getPreferenceGroup(), and result.
prefPrintCenters()
bool QGIViewPart::prefPrintCenters () protected
Definition at line 1198 of file QGIViewPart.cpp.
References ParameterGrp::GetBool(), and TechDraw::Preferences::getPreferenceGroup().
removeDecorations()
void QGIViewPart::removeDecorations () protected
Remove all existing QGIDecoration items(SectionLine, SectionMark, ...)
Definition at line 655 of file QGIViewPart.cpp.
References SCL.SimpleDataTypes::c.
removePrimitives()
void QGIViewPart::removePrimitives () protected
Remove all existing QGIPrimPath items(Vertex, Edge, Face)
Definition at line 634 of file QGIViewPart.cpp.
References SCL.SimpleDataTypes::c.
removeSelectedCosmetic()
bool QGIViewPart::removeSelectedCosmetic () const virtual
called when a DEL shortcut event is received. If a cosmetic edge or vertex is selected, remove it from the view.
Definition at line 138 of file QGIViewPart.cpp.
References Base::Persistence::getClassTypeId(), Gui::SelectionSingleton::getSelectionEx(), Gui::OldStyleElement, and Gui::Selection().
rotateView()
void QGIViewPart::rotateView () override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 1189 of file QGIViewPart.cpp.
sceneEventFilter()
bool QGIViewPart::sceneEventFilter (QGraphicsItem * watched, QEvent * event) override
Definition at line 114 of file QGIViewPart.cpp.
setGroupSelection() [1/2]
void QGIViewPart::setGroupSelection (bool isSelected) override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 1275 of file QGIViewPart.cpp.
setGroupSelection() [2/2]
void QGIViewPart::setGroupSelection (bool isSelected, const std::vector< std::string > & subNames) override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 1279 of file QGIViewPart.cpp.
setViewPartFeature()
void QGIViewPart::setViewPartFeature (TechDraw::DrawViewPart * obj)
Definition at line 175 of file QGIViewPart.cpp.
showCenterMarks()
bool QGIViewPart::showCenterMarks () protected
Definition at line 517 of file QGIViewPart.cpp.
showThisEdge()
bool QGIViewPart::showThisEdge (TechDraw::BaseGeomPtr geom)
Definition at line 472 of file QGIViewPart.cpp.
References TechDraw::ecHARD, TechDraw::ecOUTLINE, TechDraw::ecSEAM, TechDraw::ecSMOOTH, and TechDraw::ecUVISO.
showVertices()
bool QGIViewPart::showVertices () protected
Definition at line 498 of file QGIViewPart.cpp.
tidy()
void QGIViewPart::tidy ()
Definition at line 166 of file QGIViewPart.cpp.
toggleCache()
void QGIViewPart::toggleCache (bool state) override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 1078 of file QGIViewPart.cpp.
References src.Mod.Test.testPathArray::items.
toggleCosmeticLines()
void QGIViewPart::toggleCosmeticLines (bool state)
Definition at line 1089 of file QGIViewPart.cpp.
References src.Mod.Test.testPathArray::items.
type()
int TechDrawGui::QGIViewPart::type () const inline override
Definition at line 67 of file QGIViewPart.h.
updateView()
void QGIViewPart::updateView (bool update = false) override virtual
Reimplemented from TechDrawGui::QGIView.
Reimplemented in TechDrawGui::QGIViewSection.
Definition at line 189 of file QGIViewPart.cpp.
Member Data Documentation
showSection
bool TechDrawGui::QGIViewPart::showSection
Definition at line 95 of file QGIViewPart.h.
The documentation for this class was generated from the following files:
QGIViewPart.h
QGIViewPart.cpp