FreeCAD: SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT > Class Template Reference
SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT > Class Template Reference
Class defining a generic handler controller operable with a DrawSketchControllableHandler.
#include <DrawSketchController.h>
Public Member Functions
functions NOT intended for specialisation offering a NVI for extension
void initControls (QWidget *widget)
Initialises controls, such as the widget and the on-view parameters via NVI.
void resetControls ()
Resets the controls, such as the widget and the on-view parameters.
void mouseMoved (Base::Vector2d originalSketchPosition)
function triggered by the handler when the mouse has been moved
void enforceControlParameters (Base::Vector2d &onSketchPos)
function triggered by the handler to ensure its operating position takes into account widget mandated parameters
void onConstructionMethodChanged ()
virtual bool resetOnConstructionMethodeChanged ()
functions NOT intended for specialisation offering specialisation interface for
extension
void onViewValueChanged (int onviewparameterindex, double value)
void tryViewValueChanged (int onviewparameterindex, double value)
void adaptParameters ()
Specialisation Interface
void adaptDrawingToOnViewParameterChange (int onviewparameterindex, double value)
Change DSH to reflect a value entered in the view.
auto getState (int parameterindex) const
virtual void addConstraints ()
function to create constraints based on control information.
void configureOnViewParameters ()
Configures on-view parameters.
virtual void doChangeDrawSketchHandlerMode ()
void onHandlerModeChanged ()
virtual void adaptParameters (Base::Vector2d onSketchPos)
void doEnforceControlParameters (Base::Vector2d &onSketchPos)
virtual void firstKeyShortcut ()
virtual void secondKeyShortcut ()
virtual void thirdKeyShortcut ()
virtual void fourthKeyShortcut ()
virtual void tabShortcut ()
virtual void afterHandlerModeChanged ()
triggered by the controllable DSH after a mode change has been effected
void drawPositionAtCursor (const Base::Vector2d &position)
void drawDirectionAtCursor (const Base::Vector2d &position, const Base::Vector2d &origin)
void drawWidthHeightAtCursor (const Base::Vector2d &position, const double val1, const double val2)
void drawDoubleAtCursor (const Base::Vector2d &position, const double radius, Base::Unit unit=Base::Unit::Length)
Protected Member Functions
NVI for extension of controller functionality in derived classes
virtual void doInitControls (QWidget *widget)
virtual void doResetControls ()
virtual void onMouseMoved (Base::Vector2d originalSketchPosition)
virtual void afterEnforceControlParameters ()
virtual void doConstructionMethodChanged ()
Meta-programming definitions and members
using ControllerBase = void
using HandlerType = HandlerT
using SelectModeType = SelectModeT
using ContructionMethodType = ConstructionMethodT
static constexpr const int AutoConstraintInitialSize = PAutoConstraintSize
Convenience definitions
using DSDefaultHandler = DrawSketchDefaultHandler< HandlerT, SelectModeT, PAutoConstraintSize, ConstructionMethodT >
using ConstructionMachine = ConstructionMethodMachine< ConstructionMethodT >
using ConstructionMethod = ConstructionMethodT
using SelectMode = SelectModeT
HandlerT * handler
std::vector< std::unique_ptr< Gui::EditableDatumLabel > > onViewParameters
bool init = false
int parameterWithFocus = 0
Named indices for controlling on-view controls
enum OnViewParameter {
First, Second, Third, Fourth,
Fifth, Sixth, Seventh, Eighth,
Ninth, Tenth, nOnViewParameters
}
DrawSketchController (HandlerT *dshandler)
DrawSketchController (const DrawSketchController &)=delete
DrawSketchController (DrawSketchController &&)=delete
DrawSketchController & operator= (const DrawSketchController &)=delete
DrawSketchController & operator= (DrawSketchController &&)=delete
virtual ~DrawSketchController ()
helper functions
bool focusAutoPassing = true
template<typename T >
void setMode (T &modeenum, int modevalue)
void finishControlsChanged ()
void initNOnViewParameters (int n)
Initialises on-screen parameters.
void unsetOnViewParameter (Gui::EditableDatumLabel *onViewParameter)
Allows a on-view parameter to take any mouse mandated value (as opposed to enforce one)
void setOnViewParameterValue (OnViewParameter index, double val, const Base::Unit &unit=Base::Unit::Length)
void setModeOnViewParameters ()
bool setFocusToOnViewParameter (unsigned int onviewparameterindex)
This function gives the focus to a spinbox and tracks the focus.
void passFocusToNextOnViewParameter ()
Switches focus to the next parameter in the current state machine.
bool isOnViewParameterOfCurrentMode (unsigned int onviewparameterindex) const
bool isOnViewParameterOfPreviousMode (unsigned int onviewparameterindex) const
bool isOnViewParameterVisible (unsigned int onviewparameterindex)
void resetOnViewParameters ()
DrawSketchKeyboardManager * getKeyManager ()
Detailed Description
template<typename HandlerT, typename SelectModeT, int PAutoConstraintSize, typename OnViewParametersT, typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod>
class SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >
Class defining a generic handler controller operable with a DrawSketchControllableHandler.
This class is intended as a parent for controller classes. This controller class provides the essential controller functionalities, including on-view parameters. This controller class does NOT control based on (taskbox) widgets.
For an example of a tool using directly this class see DrawSketchHandlerPoint.
Controls based on taskbox widgets may derive from this class and add on top any widget mandated functionality. For the default widget (SketcherToolDefaultWidget), see DrawSketchDefaultWidgetController. For custom widgets, an appropriate class, preferably deriving from this controller needs to be provided.
Definition at line 118 of file DrawSketchController.h.
Member Typedef Documentation
ConstructionMachine
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> using SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::ConstructionMachine = ConstructionMethodMachine<ConstructionMethodT>
Definition at line 135 of file DrawSketchController.h.
ConstructionMethod
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> using SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::ConstructionMethod = ConstructionMethodT
Definition at line 137 of file DrawSketchController.h.
ControllerBase
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> using SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::ControllerBase = void
Definition at line 123 of file DrawSketchController.h.
ContructionMethodType
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> using SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::ContructionMethodType = ConstructionMethodT
Definition at line 127 of file DrawSketchController.h.
DSDefaultHandler
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> using SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::DSDefaultHandler = DrawSketchDefaultHandler<HandlerT, SelectModeT, PAutoConstraintSize, ConstructionMethodT>
Definition at line 134 of file DrawSketchController.h.
HandlerType
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> using SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::HandlerType = HandlerT
Definition at line 125 of file DrawSketchController.h.
SelectMode
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> using SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::SelectMode = SelectModeT
Definition at line 138 of file DrawSketchController.h.
SelectModeType
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> using SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::SelectModeType = SelectModeT
Definition at line 126 of file DrawSketchController.h.
Member Enumeration Documentation
OnViewParameter
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> enum SketcherGui::DrawSketchController::OnViewParameter protected
Enumerator
First
Second
Third
Fourth
Fifth
Sixth
Seventh
Eighth
Ninth
Tenth
nOnViewParameters
Definition at line 152 of file DrawSketchController.h.
Constructor & Destructor Documentation
DrawSketchController() [1/3]
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::DrawSketchController (HandlerT * dshandler) inline explicit
Creates the controller.
Parameters
dshandler a controllable DSH handler
Definition at line 278 of file DrawSketchController.h.
DrawSketchController() [2/3]
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::DrawSketchController (const DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT > &) delete
DrawSketchController() [3/3]
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::DrawSketchController (DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT > &&) delete
~DrawSketchController()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> virtual SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::~DrawSketchController () inline virtual
Definition at line 288 of file DrawSketchController.h.
Member Function Documentation
adaptDrawingToOnViewParameterChange()
void SketcherGui::DSHPointController::adaptDrawingToOnViewParameterChange (int onviewparameterindex, double value) inline
Change DSH to reflect a value entered in the view.
These functions offer a specialisation interface. Non-virtual functions are specific to this controller. Virtual functions may depend on input from a derived controller, and thus the specialisation needs to be of an overridden version (so as to be able to access members of the derived controller).
Definition at line 431 of file DrawSketchController.h.
adaptParameters() [1/2]
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::adaptParameters () inline
Definition at line 417 of file DrawSketchController.h.
adaptParameters() [2/2]
void SketcherGui::DSHPointController::adaptParameters (Base::Vector2d onSketchPos) inline virtual
function that is called by the handler with a Vector2d position to update the widget
It MUST be specialised if you want the parameters to update on mouseMove
Reimplemented in SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >.
Definition at line 469 of file DrawSketchController.h.
addConstraints()
void SketcherGui::DSHPointController::addConstraints inline virtual
function to create constraints based on control information.
Reimplemented in SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >.
Definition at line 446 of file DrawSketchController.h.
afterEnforceControlParameters()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> virtual void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::afterEnforceControlParameters () inline protected virtual
Definition at line 565 of file DrawSketchController.h.
afterHandlerModeChanged()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> virtual void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::afterHandlerModeChanged () inline virtual
triggered by the controllable DSH after a mode change has been effected
Definition at line 506 of file DrawSketchController.h.
configureOnViewParameters()
void SketcherGui::DSHPointController::configureOnViewParameters inline
Configures on-view parameters.
Definition at line 450 of file DrawSketchController.h.
Referenced by SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::isOnViewParameterOfCurrentMode().
doChangeDrawSketchHandlerMode()
void SketcherGui::DSHPointController::doChangeDrawSketchHandlerMode inline virtual
Change DSH to reflect the SelectMode it should be in based on values entered in the controls
Reimplemented in SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >.
Definition at line 456 of file DrawSketchController.h.
doConstructionMethodChanged()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> virtual void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::doConstructionMethodChanged () inline protected virtual
Reimplemented in SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >.
Definition at line 573 of file DrawSketchController.h.
doEnforceControlParameters()
void SketcherGui::DSHTranslateControllerBase::doEnforceControlParameters (Base::Vector2d & onSketchPos) inline
function that is called by the handler with a mouse position, enabling the widget to override it having regard to the widget information.
It MUST be specialised if you want to override mouse position based on parameters.
Definition at line 479 of file DrawSketchController.h.
doInitControls()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> virtual void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::doInitControls (QWidget * widget) inline protected virtual
Reimplemented in SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >.
Definition at line 547 of file DrawSketchController.h.
Referenced by SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::DrawSketchController().
doResetControls()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> virtual void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::doResetControls () inline protected virtual
Reimplemented in SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >.
Definition at line 552 of file DrawSketchController.h.
Referenced by SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::~DrawSketchController().
drawDirectionAtCursor()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::drawDirectionAtCursor (const Base::Vector2d & position, const Base::Vector2d & origin) inline
Definition at line 520 of file DrawSketchController.h.
drawDoubleAtCursor()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::drawDoubleAtCursor (const Base::Vector2d & position, const double radius, Base::Unit unit = Base::Unit::Length) inline
Definition at line 535 of file DrawSketchController.h.
drawPositionAtCursor()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::drawPositionAtCursor (const Base::Vector2d & position) inline
Definition at line 513 of file DrawSketchController.h.
drawWidthHeightAtCursor()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::drawWidthHeightAtCursor (const Base::Vector2d & position, const double val1, const double val2) inline
Definition at line 528 of file DrawSketchController.h.
enforceControlParameters()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::enforceControlParameters (Base::Vector2d & onSketchPos) inline
function triggered by the handler to ensure its operating position takes into account widget mandated parameters
Definition at line 329 of file DrawSketchController.h.
finishControlsChanged()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::finishControlsChanged () inline protected
function to redraw before and after any eventual mode change in reaction to a control change
Definition at line 597 of file DrawSketchController.h.
Referenced by SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::parameterTabOrEnterPressed().
firstKeyShortcut()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> virtual void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::firstKeyShortcut () inline virtual
on first shortcut, it toggles the first checkbox if there is go. Must be specialised if this is not intended
Reimplemented in SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >.
Definition at line 486 of file DrawSketchController.h.
fourthKeyShortcut()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> virtual void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::fourthKeyShortcut () inline virtual
Reimplemented in SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >.
Definition at line 495 of file DrawSketchController.h.
getKeyManager()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> DrawSketchKeyboardManager* SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::getKeyManager () inline protected
Definition at line 786 of file DrawSketchController.h.
getState()
auto SketcherGui::DSHTranslateControllerBase::getState (int parameterindex) const inline
Returns the state to which the on-view parameter corresponds in the current construction method.
Definition at line 439 of file DrawSketchController.h.
initControls()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::initControls (QWidget * widget) inline
Initialises controls, such as the widget and the on-view parameters via NVI.
These functions offer a NVI to ensure the order on initialisation. It is heavily encouraged to extend functionality using the NVI interface (by overriding the NVI functions).
Definition at line 298 of file DrawSketchController.h.
initNOnViewParameters()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::initNOnViewParameters (int n) inline protected
Initialises on-screen parameters.
Definition at line 619 of file DrawSketchController.h.
Referenced by SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::isOnViewParameterOfCurrentMode().
isOnViewParameterOfCurrentMode()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> bool SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::isOnViewParameterOfCurrentMode (unsigned int onviewparameterindex) const inline protected
Returns whether the provided on-view parameter index belongs to the current state of the state machine
Definition at line 754 of file DrawSketchController.h.
Referenced by SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::setOnViewParameterValue().
isOnViewParameterOfPreviousMode()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> bool SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::isOnViewParameterOfPreviousMode (unsigned int onviewparameterindex) const inline protected
Returns whether the provided on-view parameter index belongs to the previous state of the state machine
Definition at line 762 of file DrawSketchController.h.
isOnViewParameterVisible()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> bool SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::isOnViewParameterVisible (unsigned int onviewparameterindex) inline protected
Definition at line 768 of file DrawSketchController.h.
mouseMoved()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::mouseMoved (Base::Vector2d originalSketchPosition) inline
function triggered by the handler when the mouse has been moved
Definition at line 318 of file DrawSketchController.h.
onConstructionMethodChanged()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::onConstructionMethodChanged () inline
function that is called by the handler when the construction mode changed
Definition at line 341 of file DrawSketchController.h.
onHandlerModeChanged()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::onHandlerModeChanged () inline
function that is called by the handler when the selection mode changed
Definition at line 460 of file DrawSketchController.h.
onMouseMoved()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> virtual void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::onMouseMoved (Base::Vector2d originalSketchPosition) inline protected virtual
Definition at line 556 of file DrawSketchController.h.
Referenced by SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::initControls().
onViewValueChanged()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::onViewValueChanged (int onviewparameterindex, double value) inline
These functions offer a specialisation interface to ensure the order on initialisation. It is heavily encouraged to extend functionality using the specialisation interface (by specialising the NVI functions). slot triggering when a on view parameter has changed It is intended to remote control the DrawSketchDefaultWidgetHandler
Definition at line 373 of file DrawSketchController.h.
Referenced by SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::initNOnViewParameters().
operator=() [1/2]
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> DrawSketchController& SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::operator= (const DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT > &) delete
operator=() [2/2]
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> DrawSketchController& SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::operator= (DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT > &&) delete
passFocusToNextOnViewParameter()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::passFocusToNextOnViewParameter () inline protected
Switches focus to the next parameter in the current state machine.
Definition at line 723 of file DrawSketchController.h.
Referenced by SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::doEnforceControlParameters().
resetControls()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::resetControls () inline
Resets the controls, such as the widget and the on-view parameters.
Definition at line 307 of file DrawSketchController.h.
Referenced by SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::DrawSketchController().
resetOnConstructionMethodeChanged()
bool SketcherGui::DSHBSplineControllerBase::resetOnConstructionMethodeChanged inline virtual
function that define if the handler should be reset on construction methode change
Definition at line 356 of file DrawSketchController.h.
resetOnViewParameters()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::resetOnViewParameters () inline protected
Resets the on-view parameter controls
Definition at line 774 of file DrawSketchController.h.
secondKeyShortcut()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> virtual void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::secondKeyShortcut () inline virtual
Reimplemented in SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >.
Definition at line 489 of file DrawSketchController.h.
setFocusToOnViewParameter()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> bool SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::setFocusToOnViewParameter (unsigned int onviewparameterindex) inline protected
This function gives the focus to a spinbox and tracks the focus.
Definition at line 707 of file DrawSketchController.h.
Referenced by SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::doInitControls().
setMode()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> template<typename T > void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::setMode (T & modeenum, int modevalue) inline protected
function to assist in adaptDrawingToComboboxChange specialisation assigns the modevalue to the modeenum it also triggers an update of the cursor
Definition at line 584 of file DrawSketchController.h.
setModeOnViewParameters()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::setModeOnViewParameters () inline protected
Activates the correct set of on-view parameters corresponding to current mode. It may be specialized if necessary.
Definition at line 669 of file DrawSketchController.h.
setOnViewParameterValue()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::setOnViewParameterValue (OnViewParameter index, double val, const Base::Unit & unit = Base::Unit::Length) inline protected
Definition at line 656 of file DrawSketchController.h.
tabShortcut()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> virtual void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::tabShortcut () inline virtual
Reimplemented in SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >.
Definition at line 498 of file DrawSketchController.h.
thirdKeyShortcut()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> virtual void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::thirdKeyShortcut () inline virtual
Reimplemented in SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >.
Definition at line 492 of file DrawSketchController.h.
tryViewValueChanged()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::tryViewValueChanged (int onviewparameterindex, double value) inline
Definition at line 388 of file DrawSketchController.h.
Referenced by SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::resetOnConstructionMethodeChanged().
unsetOnViewParameter()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> void SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::unsetOnViewParameter (Gui::EditableDatumLabel * onViewParameter) inline protected
Allows a on-view parameter to take any mouse mandated value (as opposed to enforce one)
Definition at line 650 of file DrawSketchController.h.
Member Data Documentation
AutoConstraintInitialSize
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> constexpr const int SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::AutoConstraintInitialSize = PAutoConstraintSize static constexpr
Definition at line 128 of file DrawSketchController.h.
Referenced by SketcherGui::ControlAmount< sizes... >::defaultMethodSize().
focusAutoPassing
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> bool SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::focusAutoPassing = true protected
Definition at line 791 of file DrawSketchController.h.
handler
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> HandlerT* SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::handler protected
Definition at line 143 of file DrawSketchController.h.
Referenced by SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::afterEnforceControlParameters(), SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::afterHandlerModeChanged(), SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::finishControlsChanged(), SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::firstKeyShortcut(), SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::fourthKeyShortcut(), SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::isOnViewParameterOfCurrentMode(), SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::setOnViewParameterValue(), and SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::~DrawSketchController().
init
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> bool SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::init = false protected
Definition at line 147 of file DrawSketchController.h.
Referenced by SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::DrawSketchController(), and DocumentObject.DocumentObject::onChanged().
onViewParameters
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> std::vector<std::unique_ptr<Gui::EditableDatumLabel> > SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::onViewParameters protected
Definition at line 144 of file DrawSketchController.h.
Referenced by SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::doInitControls(), SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::finishControlsChanged(), and SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::setOnViewParameterValue().
parameterWithFocus
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod> int SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::parameterWithFocus = 0 protected
Definition at line 148 of file DrawSketchController.h.
Referenced by SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::doConstructionMethodChanged(), SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::doInitControls(), SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::isOnViewParameterOfCurrentMode(), SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::setOnViewParameterValue(), and SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::unsetOnViewParameter().
The documentation for this class was generated from the following files:
DrawSketchController.h
DrawSketchHandlerArc.h
DrawSketchHandlerArcSlot.h
DrawSketchHandlerBSpline.h
DrawSketchHandlerCircle.h
DrawSketchHandlerEllipse.h
DrawSketchHandlerLine.h
DrawSketchHandlerOffset.h
DrawSketchHandlerPoint.h
DrawSketchHandlerPolygon.h
DrawSketchHandlerRectangle.h
DrawSketchHandlerRotate.h
DrawSketchHandlerScale.h
DrawSketchHandlerSlot.h
DrawSketchHandlerTranslate.h