FreeCAD: MeshGui::DockEvaluateMeshImp Class Reference
MeshGui::DockEvaluateMeshImp Class Reference
#include <DlgEvaluateMeshImp.h>
Public Member Functions
QSize sizeHint () const override
Public Member Functions inherited from MeshGui::DlgEvaluateMeshImp
DlgEvaluateMeshImp (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgEvaluateMeshImp () override
void setMesh (Mesh::Feature *)
Public Member Functions inherited from App::DocumentObserver
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
void attachDocument (Document *)
void detachDocument ()
Static Public Member Functions
static DockEvaluateMeshImp * instance ()
static void destruct ()
static bool hasInstance ()
Protected Member Functions
DockEvaluateMeshImp (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DockEvaluateMeshImp () override
void closeEvent (QCloseEvent *e) override
Protected Member Functions inherited from MeshGui::DlgEvaluateMeshImp
void refreshList ()
void showInformation ()
void cleanInformation ()
void addViewProvider (const char *vp, const std::vector< Mesh::ElementIndex > &indices)
void removeViewProvider (const char *vp)
void removeViewProviders ()
void changeEvent (QEvent *e) override
Protected Member Functions inherited from App::DocumentObserver
Document * getDocument () const
Detailed Description
The DockEvaluateMeshImp class creates a single instance and embeds it into a dock window.
Author
Werner Mayer
Definition at line 151 of file DlgEvaluateMeshImp.h.
Constructor & Destructor Documentation
DockEvaluateMeshImp()
DockEvaluateMeshImp::DockEvaluateMeshImp (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit protected
Constructs a DockEvaluateMeshImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'
Definition at line 1362 of file DlgEvaluateMeshImp.cpp.
References Gui::DockWindowManager::addDockWindow(), Gui::DockWindowManager::instance(), and TechDraw::Plain.
Referenced by instance().
~DockEvaluateMeshImp()
DockEvaluateMeshImp::~DockEvaluateMeshImp () override protected
Destroys the object and frees any allocated resources
Definition at line 1384 of file DlgEvaluateMeshImp.cpp.
Member Function Documentation
closeEvent()
void DockEvaluateMeshImp::closeEvent (QCloseEvent * event) override protected
Destroys the dock window this object is embedded into without destroying itself.
Definition at line 1392 of file DlgEvaluateMeshImp.cpp.
References Gui::DockWindowManager::instance(), and Gui::DockWindowManager::removeDockWindow().
destruct()
void DockEvaluateMeshImp::destruct () static
Definition at line 1344 of file DlgEvaluateMeshImp.cpp.
hasInstance()
bool DockEvaluateMeshImp::hasInstance () static
Definition at line 1353 of file DlgEvaluateMeshImp.cpp.
instance()
DockEvaluateMeshImp * DockEvaluateMeshImp::instance () static
Definition at line 1333 of file DlgEvaluateMeshImp.cpp.
References DockEvaluateMeshImp(), and Gui::getMainWindow().
sizeHint()
QSize DockEvaluateMeshImp::sizeHint () const override
Returns an appropriate size hint for the dock window.
Definition at line 1407 of file DlgEvaluateMeshImp.cpp.
The documentation for this class was generated from the following files:
DlgEvaluateMeshImp.h
DlgEvaluateMeshImp.cpp