FreeCAD: TechDraw::DrawDimHelper Class Reference
TechDraw::DrawDimHelper Class Reference
Additional functions for working with Dimensions.
#include <DrawDimHelper.h>
Static Public Member Functions
static DrawViewDimension * makeExtentDim (DrawViewPart *dvp, const std::string &dimType, ReferenceVector references2d)
static DrawViewDimension * makeExtentDim (DrawViewPart *dvp, std::vector< std::string > edgeNames, int direction)
static void makeExtentDim3d (DrawViewPart *dvp, const std::string &dimType, ReferenceVector references2d)
static void makeExtentDim3d (DrawViewPart *dvp, ReferenceVector references, int direction)
static gp_Pnt findClosestPoint (std::vector< TopoDS_Edge > inEdges, TopoDS_Edge &boundary)
static DrawViewDimension * makeDistDim (DrawViewPart *dvp, std::string dimType, Base::Vector3d refMin, Base::Vector3d refMax, bool extent=false)
static std::pair< Base::Vector3d, Base::Vector3d > minMax (DrawViewPart *dvp, std::vector< std::string > edgeNames, int direction)
static std::pair< Base::Vector3d, Base::Vector3d > minMax3d (DrawViewPart *dvp, ReferenceVector references, int direction)
Detailed Description
Additional functions for working with Dimensions.
Definition at line 65 of file DrawDimHelper.h.
Member Function Documentation
findClosestPoint()
gp_Pnt DrawDimHelper::findClosestPoint (std::vector< TopoDS_Edge > inEdges, TopoDS_Edge & boundary) static
Definition at line 297 of file DrawDimHelper.cpp.
References Base::Console(), KDL::max(), and Base::ConsoleSingleton::Warning().
Referenced by minMax(), and minMax3d().
makeDistDim()
DrawViewDimension * DrawDimHelper::makeDistDim (DrawViewPart * dvp, std::string dimType, Base::Vector3d refMin, Base::Vector3d refMax, bool extent = false) static
Definition at line 417 of file DrawDimHelper.cpp.
References TechDraw::CosmeticExtension::add1CVToGV(), TechDraw::CosmeticExtension::addCosmeticVertex(), toolbit-attributes::doc, TechDraw::DrawView::findParentPage(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), TechDraw::DrawViewPart::getVertexGeometry(), Base::Interpreter(), TechDraw::DrawUtil::invertY(), TechDraw::CosmeticVertex::makeCanonicalPoint(), replaceobj::objs, TechDraw::DrawViewDimension::References2D, TechDraw::DrawView::requestPaint(), Base::InterpreterSingleton::runStringArg(), App::PropertyLinkSubList::setValues(), and importers.importIFCmulticore::subs.
makeExtentDim() [1/2]
DrawViewDimension * DrawDimHelper::makeExtentDim (DrawViewPart * dvp, const std::string & dimType, ReferenceVector references2d) static
Definition at line 62 of file DrawDimHelper.cpp.
References draftgeoutils.general::geomType(), and TechDraw::DrawUtil::getGeomTypeFromName().
makeExtentDim() [2/2]
DrawViewDimension * DrawDimHelper::makeExtentDim (DrawViewPart * dvp, std::vector< std::string > edgeNames, int direction) static
Definition at line 80 of file DrawDimHelper.cpp.
References toolbit-attributes::doc, TechDraw::DrawView::findParentPage(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), Base::Interpreter(), LENGTH, Base::InterpreterSingleton::runStringArg(), and VERTICAL.
makeExtentDim3d() [1/2]
void DrawDimHelper::makeExtentDim3d (DrawViewPart * dvp, const std::string & dimType, ReferenceVector references2d) static
Definition at line 141 of file DrawDimHelper.cpp.
makeExtentDim3d() [2/2]
void DrawDimHelper::makeExtentDim3d (DrawViewPart * dvp, ReferenceVector references, int direction) static
Definition at line 147 of file DrawDimHelper.cpp.
References toolbit-attributes::doc, TechDraw::DrawView::findParentPage(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), Base::Interpreter(), Base::InterpreterSingleton::runStringArg(), and VERTICAL.
minMax()
std::pair< Base::Vector3d, Base::Vector3d > DrawDimHelper::minMax (DrawViewPart * dvp, std::vector< std::string > edgeNames, int direction) static
Definition at line 205 of file DrawDimHelper.cpp.
References KDL::Add(), findClosestPoint(), draftgeoutils.general::geomType(), TechDraw::DrawViewPart::getEdgeGeometry(), TechDraw::DrawViewPart::getGeomByIndex(), TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::DrawUtil::getIndexFromName(), Handle(), HORIZONTAL, SplineSurface::i, result, and VERTICAL.
Referenced by TechDraw::DrawViewDimExtent::getPointsExtent().
minMax3d()
std::pair< Base::Vector3d, Base::Vector3d > DrawDimHelper::minMax3d (DrawViewPart * dvp, ReferenceVector references, int direction) static
Definition at line 325 of file DrawDimHelper.cpp.
References KDL::Add(), TechDraw::DrawViewPart::centerScaleRotate(), findClosestPoint(), TechDraw::DrawViewPart::getOriginalCentroid(), TechDraw::DrawViewPart::getProjectionCS(), Handle(), HORIZONTAL, result, and VERTICAL.
Referenced by TechDraw::DrawViewDimExtent::getPointsExtent().
The documentation for this class was generated from the following files:
DrawDimHelper.h
DrawDimHelper.cpp