FreeCAD: GCS::ConstraintPointOnBSpline Class Reference
GCS::ConstraintPointOnBSpline Class Reference
#include <Constraints.h>
Public Member Functions
ConstraintPointOnBSpline (double *point, double *initparam, int coordidx, BSpline &b)
ConstraintType getTypeId () override
void rescale (double coef=1.) override
double error () override
double grad (double *) override
Public Member Functions inherited from GCS::Constraint
Constraint ()
virtual ~Constraint ()
VEC_pD params ()
void redirectParams (const MAP_pD_pD &redirectionmap)
void revertParams ()
void setTag (int tagId)
int getTag ()
void setDriving (bool isdriving)
bool isDriving () const
void setInternalAlignment (Alignment isinternalalignment)
Alignment isInternalAlignment () const
virtual double maxStep (MAP_pD_D &dir, double lim=1.)
int findParamInPvec (double *param)
Public Attributes
size_t numpoints
BSpline & bsp
size_t startpole
Additional Inherited Members
Public Types inherited from GCS::Constraint
enum Alignment { Alignment::NoInternalAlignment, Alignment::InternalAlignment }
Protected Attributes inherited from GCS::Constraint
VEC_pD origpvec
VEC_pD pvec
double scale
int tag
bool pvecChangedFlag
bool driving
Alignment internalAlignment
Detailed Description
Definition at line 325 of file Constraints.h.
Constructor & Destructor Documentation
ConstraintPointOnBSpline()
GCS::ConstraintPointOnBSpline::ConstraintPointOnBSpline (double * point, double * initparam, int coordidx, BSpline & b)
TODO: Explain how it's provided coordidx = 0 if x, 1 if y
Definition at line 504 of file Constraints.cpp.
References SCL.SimpleDataTypes::b, bsp, GCS::BSpline::degree, GCS::BSpline::flattenedknots, SplineSurface::i, numpoints, GCS::Constraint::origpvec, GCS::Constraint::pvec, rescale(), and GCS::BSpline::setupFlattenedKnots().
Member Function Documentation
error()
double GCS::ConstraintPointOnBSpline::error () override virtual
Reimplemented from GCS::Constraint.
Definition at line 563 of file Constraints.cpp.
References bsp, GCS::BSpline::degree, GCS::BSpline::flattenedknots, SplineSurface::i, numpoints, GCS::BSpline::splineValue(), and startpole.
getTypeId()
ConstraintType GCS::ConstraintPointOnBSpline::getTypeId () override virtual
Reimplemented from GCS::Constraint.
Definition at line 539 of file Constraints.cpp.
References GCS::PointOnBSpline.
grad()
double GCS::ConstraintPointOnBSpline::grad (double * gcsparam) override virtual
Reimplemented from GCS::Constraint.
Definition at line 597 of file Constraints.cpp.
References bsp, GCS::BSpline::degree, GCS::BSpline::flattenedknots, GCS::BSpline::getLinCombFactor(), SplineSurface::i, numpoints, GCS::BSpline::splineValue(), and startpole.
rescale()
void GCS::ConstraintPointOnBSpline::rescale (double coef = 1.) override virtual
Reimplemented from GCS::Constraint.
Definition at line 558 of file Constraints.cpp.
Referenced by ConstraintPointOnBSpline().
Member Data Documentation
bsp
BSpline& GCS::ConstraintPointOnBSpline::bsp
Definition at line 356 of file Constraints.h.
Referenced by ConstraintPointOnBSpline(), error(), and grad().
numpoints
size_t GCS::ConstraintPointOnBSpline::numpoints
Definition at line 355 of file Constraints.h.
Referenced by ConstraintPointOnBSpline(), error(), and grad().
startpole
size_t GCS::ConstraintPointOnBSpline::startpole
Definition at line 357 of file Constraints.h.
Referenced by error(), and grad().
The documentation for this class was generated from the following files:
Constraints.h
Constraints.cpp