FreeCAD: Gui::GraphvizView Class Reference
Gui::GraphvizView Class Reference
#include <GraphvizView.h>
Public Member Functions
GraphvizView (App::Document &_doc, QWidget *parent=nullptr)
~GraphvizView () override
QByteArray exportGraph (const QString &filter)
bool onMsg (const char *pMsg, const char **ppReturn) override
Message handler.
bool onHasMsg (const char *pMsg) const override
Message handler test.
Public Member Functions inherited from Gui::MDIView
MDIView (Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
~MDIView () override
void onRelabel (Gui::Document *pDoc) override
get called when the document is updated
virtual void viewAll ()
QString buildWindowTitle () const
build window title
bool onMsg (const char *pMsg, const char **ppReturn) override
Message handler.
bool onHasMsg (const char *pMsg) const override
Message handler test.
bool canClose () override
overwrite when checking on close state
void deleteSelf () override
delete itself
PyObject * getPyObject () override
virtual QStringList undoActions () const
virtual QStringList redoActions () const
QSize minimumSizeHint () const override
virtual void setCurrentViewMode (ViewMode mode)
ViewMode currentViewMode () const
template<typename _T >
_T getActiveObject (const char *name, App::DocumentObject **parent=nullptr, std::string *subname=nullptr) const
access getter for the active object list
void setActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr)
bool hasActiveObject (const char *n) const
bool isActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr) const
virtual bool containsViewProvider (const ViewProvider *) const
containsViewProvider Checks if the given view provider is part of this view. The default implementation returns false.
void savePrinterSettings (QPrinter *printer)
void restorePrinterSettings (QPrinter *printer)
Public Member Functions inherited from Gui::BaseView
BaseView (Gui::Document *pcDocument=nullptr)
~BaseView () override
void setDocument (Gui::Document *pcDocument)
sets the view to another document (called by Application)
void onClose ()
is sent from the document in order to close the document
Gui::Document * getGuiDocument () const
returns the document the view is attached to
App::Document * getAppDocument () const
returns the document the view is attached to
bool isPassive () const
indicates if the view is in passive mode
virtual void onUpdate ()
get called when the document is updated
virtual void onRename (Gui::Document *)
get called when the document is renamed (change of its internal name)
virtual const char * getName () const
returns the name of the view (important for messages)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Printing
void print (QPrinter *printer) override
void print () override
void printPdf () override
void printPreview () override
Additional Inherited Members
Public Types inherited from Gui::MDIView
enum ViewMode { Child, TopLevel, FullScreen }
MDI view mode enum.
Public Slots inherited from Gui::MDIView
virtual void setOverrideCursor (const QCursor &)
virtual void restoreOverrideCursor ()
Signals inherited from Gui::MDIView
void message (const QString &, int)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Slots inherited from Gui::MDIView
virtual void windowStateChanged (QWidget *)
Protected Member Functions inherited from Gui::MDIView
void closeEvent (QCloseEvent *e) override
void changeEvent (QEvent *e) override
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::MDIView
PyObject * pythonObject
Protected Attributes inherited from Gui::BaseView
Gui::Document * _pcDocument
bool bIsDetached {false}
bool bIsPassive {false}
Detailed Description
Definition at line 40 of file GraphvizView.h.
Constructor & Destructor Documentation
GraphvizView()
GraphvizView::GraphvizView (App::Document & _doc, QWidget * parent = nullptr) explicit
Definition at line 220 of file GraphvizView.cpp.
References draftgeoutils.faces::bind(), draftgeoutils.intersections::connect(), Gui::GraphvizWorker::emitFinished(), Gui::GraphvizWorker::error(), App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), GraphicsViewZoom::set_modifiers(), GraphicsViewZoom::set_zoom_inverted(), App::Document::signalRecomputed, App::Document::signalRedo, App::Document::signalUndo, and Gui::GraphvizWorker::svgFileRead().
~GraphvizView()
GraphvizView::~GraphvizView () override
Definition at line 265 of file GraphvizView.cpp.
Member Function Documentation
exportGraph()
QByteArray GraphvizView::exportGraph (const QString & filter)
Definition at line 389 of file GraphvizView.cpp.
References toolbit-attributes::args, App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetBool(), and App::Application::GetParameterGroupByPath().
Referenced by onMsg(), and printPdf().
onHasMsg()
bool GraphvizView::onHasMsg (const char * pMsg) const override virtual
Message handler test.
Implements Gui::BaseView.
Definition at line 504 of file GraphvizView.cpp.
onMsg()
bool GraphvizView::onMsg (const char * pMsg, const char ** ppReturn) override virtual
Message handler.
Implements Gui::BaseView.
Definition at line 441 of file GraphvizView.cpp.
References exportGraph(), DrawingExample::file, Gui::FileDialog::getSaveFileName(), print(), printPdf(), printPreview(), and Path.Post.scripts.refactored_centroid_post::str.
print() [1/2]
void GraphvizView::print () override virtual
Print content of view
Reimplemented from Gui::MDIView.
Definition at line 532 of file GraphvizView.cpp.
Referenced by onMsg(), and printPreview().
print() [2/2]
void GraphvizView::print (QPrinter * printer) override virtual
Reimplemented from Gui::MDIView.
Definition at line 521 of file GraphvizView.cpp.
References buildPsets::p.
printPdf()
void GraphvizView::printPdf () override virtual
Print to PDF file
Reimplemented from Gui::MDIView.
Definition at line 543 of file GraphvizView.cpp.
References exportGraph(), DrawingExample::file, and Gui::FileDialog::getSaveFileName().
Referenced by onMsg().
printPreview()
void GraphvizView::printPreview () override virtual
Show a preview dialog
Reimplemented from Gui::MDIView.
Definition at line 562 of file GraphvizView.cpp.
References draftgeoutils.intersections::connect(), and print().
Referenced by onMsg().
The documentation for this class was generated from the following files:
GraphvizView.h
GraphvizView.cpp