FreeCAD: Path.Main.Gui.Job Namespace Reference
Path.Main.Gui.Job Namespace Reference
Classes
class MaterialDialog
class StockCreateBoxEdit
class StockCreateCylinderEdit
class StockEdit
class StockFromBaseBoundBoxEdit
class StockFromExistingEdit
class TaskPanel
class ViewProvider
Functions
def selectionEx ()
def Create (base, template=None, openTaskPanel=True)
Variables
Draft
Part
DraftVecUtils
translate
Function Documentation
Create()
def Path.Main.Gui.Job.Create (base, template = None, openTaskPanel = True)
Create(base, template) ... creates a job instance for the given base object
using template to configure it.
Definition at line 1671 of file Gui/Job.py.
References Path.Log.error().
selectionEx()
def Path.Main.Gui.Job.selectionEx ()
Definition at line 82 of file Gui/Job.py.
Referenced by Path.Main.Gui.Job.TaskPanel.modelMove(), Path.Main.Gui.Job.TaskPanel.modelRotate(), Path.Main.Gui.Job.TaskPanel.modelSet0(), and Path.Main.Gui.Job.TaskPanel.modelSetAxis().
Variable Documentation
Draft
Path.Main.Gui.Job.Draft
Definition at line 52 of file Gui/Job.py.
DraftVecUtils
Path.Main.Gui.Job.DraftVecUtils
Definition at line 54 of file Gui/Job.py.
Part
Path.Main.Gui.Job.Part
Definition at line 53 of file Gui/Job.py.
translate
Path.Main.Gui.Job.translate
Definition at line 56 of file Gui/Job.py.