FreeCAD: Gui::Dialog::DlgUnitsCalculator Class Reference
Gui::Dialog::DlgUnitsCalculator Class Reference
#include <DlgUnitsCalculatorImp.h>
Public Member Functions
DlgUnitsCalculator (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgUnitsCalculator () override
Protected Member Functions
void accept () override
void reject () override
void textChanged (const QString)
void valueChanged (const Base::Quantity &)
void onUnitsBoxActivated (int)
void onComboBoxSchemeActivated (int)
void onSpinBoxDecimalsValueChanged (int)
void copy ()
void returnPressed ()
void parseError (const QString &errorText)
Detailed Description
The DlgUnitsCalculator provides a unit conversion dialog
Author
Juergen Riegel
Definition at line 80 of file DlgUnitsCalculatorImp.h.
Constructor & Destructor Documentation
DlgUnitsCalculator()
DlgUnitsCalculator::DlgUnitsCalculator (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Constructs a DlgUnitsCalculator which is a child of 'parent', with the name 'name' and widget flags set to 'f'
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
Definition at line 46 of file DlgUnitsCalculatorImp.cpp.
References Base::Unit::Acceleration, accept(), Base::Unit::AmountOfSubstance, Base::Unit::Angle, Base::Unit::Area, draftgeoutils.intersections::connect(), copy(), Base::Unit::CurrentDensity, Base::Unit::Density, Base::Unit::DissipationRate, Base::Unit::DynamicViscosity, Base::Unit::ElectricalCapacitance, Base::Unit::ElectricalConductance, Base::Unit::ElectricalConductivity, Base::Unit::ElectricalInductance, Base::Unit::ElectricalResistance, Base::Unit::ElectricCharge, Base::Unit::ElectricCurrent, Base::Unit::ElectricPotential, Base::Unit::Force, Base::Unit::Frequency, Base::UnitsApi::getDecimals(), Base::UnitsApi::getDescription(), Base::Unit::HeatFlux, SplineSurface::i, Base::Unit::InverseArea, Base::Unit::InverseLength, Base::Unit::InverseVolume, Base::Unit::KinematicViscosity, Base::Unit::Length, Base::Unit::LuminousIntensity, Base::Unit::MagneticFieldStrength, Base::Unit::MagneticFlux, Base::Unit::MagneticFluxDensity, Base::Unit::Magnetization, Base::Unit::Mass, Base::NumUnitSystemTypes, onComboBoxSchemeActivated(), onSpinBoxDecimalsValueChanged(), onUnitsBoxActivated(), parseError(), Gui::InputField::parseError(), Base::Unit::Power, Base::Unit::Pressure, returnPressed(), Base::Unit::SpecificEnergy, Base::Unit::SpecificHeat, Base::Unit::Stiffness, Base::Unit::Temperature, textChanged(), Base::Unit::ThermalConductivity, Base::Unit::ThermalExpansionCoefficient, Base::Unit::ThermalTransferCoefficient, Base::Unit::TimeSpan, Base::Unit::VacuumPermittivity, valueChanged(), Gui::InputField::valueChanged(), Base::Unit::Velocity, Base::Unit::Volume, Base::Unit::VolumeFlowRate, Base::Unit::VolumetricThermalExpansionCoefficient, and Base::Unit::Work.
~DlgUnitsCalculator()
DlgUnitsCalculator::~DlgUnitsCalculator () override default
Destroys the object and frees any allocated resources
Member Function Documentation
accept()
void DlgUnitsCalculator::accept () override protected
Definition at line 119 of file DlgUnitsCalculatorImp.cpp.
Referenced by femexamples.examplesgui.FemExamples::clicked(), DlgUnitsCalculator(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
copy()
void DlgUnitsCalculator::copy () protected
Definition at line 185 of file DlgUnitsCalculatorImp.cpp.
Referenced by DlgUnitsCalculator().
onComboBoxSchemeActivated()
void DlgUnitsCalculator::onComboBoxSchemeActivated (int index) protected
Definition at line 213 of file DlgUnitsCalculatorImp.cpp.
Referenced by DlgUnitsCalculator().
onSpinBoxDecimalsValueChanged()
void DlgUnitsCalculator::onSpinBoxDecimalsValueChanged (int value) protected
Definition at line 224 of file DlgUnitsCalculatorImp.cpp.
Referenced by DlgUnitsCalculator().
onUnitsBoxActivated()
void DlgUnitsCalculator::onUnitsBoxActivated (int index) protected
Definition at line 200 of file DlgUnitsCalculatorImp.cpp.
References Base::Quantity::getUnit(), Base::Quantity::getValue(), Base::Unit::length(), Base::pow(), and unit().
Referenced by DlgUnitsCalculator().
parseError()
void DlgUnitsCalculator::parseError (const QString & errorText) protected
Definition at line 179 of file DlgUnitsCalculatorImp.cpp.
Referenced by DlgUnitsCalculator().
reject()
void DlgUnitsCalculator::reject () override protected
Definition at line 124 of file DlgUnitsCalculatorImp.cpp.
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
returnPressed()
void DlgUnitsCalculator::returnPressed () protected
Definition at line 191 of file DlgUnitsCalculatorImp.cpp.
Referenced by DlgUnitsCalculator().
textChanged()
void DlgUnitsCalculator::textChanged (const QString) protected
Definition at line 129 of file DlgUnitsCalculatorImp.cpp.
References unit(), and valueChanged().
Referenced by DlgUnitsCalculator().
valueChanged()
void DlgUnitsCalculator::valueChanged (const Base::Quantity & quant) protected
Definition at line 135 of file DlgUnitsCalculatorImp.cpp.
References Base::UnitsApi::getDecimals(), Base::Unit::getTypeString(), Base::Quantity::getUnit(), Base::Quantity::getValue(), Base::Quantity::parse(), and toolbit-attributes::val.
Referenced by DlgUnitsCalculator(), and textChanged().
The documentation for this class was generated from the following files:
DlgUnitsCalculatorImp.h
DlgUnitsCalculatorImp.cpp