FreeCAD: MatGui::Array3DDepthModel Class Reference
MatGui::Array3DDepthModel Class Reference
#include <ArrayModel.h>
Public Member Functions
Array3DDepthModel (const std::shared_ptr< Materials::MaterialProperty > &property=nullptr, const std::shared_ptr< Materials::Material3DArray > &value=nullptr, QObject *parent=nullptr)
~Array3DDepthModel () override=default
int rowCount (const QModelIndex &parent=QModelIndex()) const override
bool newRow (const QModelIndex &index) const override
void deleteRow (const QModelIndex &index)
int columnCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override
Qt::ItemFlags flags (const QModelIndex &index) const override
bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex()) override
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex()) override
bool insertColumns (int column, int count, const QModelIndex &parent=QModelIndex()) override
bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex()) override
Public Member Functions inherited from MatGui::AbstractArrayModel
AbstractArrayModel (QObject *parent=nullptr)
~AbstractArrayModel () override=default
Detailed Description
Definition at line 96 of file ArrayModel.h.
Constructor & Destructor Documentation
Array3DDepthModel()
Array3DDepthModel::Array3DDepthModel (const std::shared_ptr< Materials::MaterialProperty > & property = nullptr, const std::shared_ptr< Materials::Material3DArray > & value = nullptr, QObject * parent = nullptr) explicit
Definition at line 201 of file ArrayModel.cpp.
~Array3DDepthModel()
MatGui::Array3DDepthModel::~Array3DDepthModel () override default
Member Function Documentation
columnCount()
int MatGui::Array3DDepthModel::columnCount (const QModelIndex & parent = QModelIndex()) const inline override
Definition at line 109 of file ArrayModel.h.
data()
QVariant Array3DDepthModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 229 of file ArrayModel.cpp.
References Materials::MaterialValue::getQuantityFormat(), src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::Quantity, and Base::Quantity::setFormat().
deleteRow()
void Array3DDepthModel::deleteRow (const QModelIndex & index)
Definition at line 223 of file ArrayModel.cpp.
References removeRows().
flags()
Qt::ItemFlags Array3DDepthModel::flags (const QModelIndex & index) const override
Definition at line 284 of file ArrayModel.cpp.
headerData()
QVariant Array3DDepthModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const override
Definition at line 251 of file ArrayModel.cpp.
References App::ExpressionParser::column, Sketcher::Horizontal, rowCount(), and Sketcher::Vertical.
insertColumns()
bool Array3DDepthModel::insertColumns (int column, int count, const QModelIndex & parent = QModelIndex()) override
Definition at line 319 of file ArrayModel.cpp.
References App::ExpressionParser::column, src.Mod.AddonManager.NetworkManager::count, and Init::parent.
insertRows()
bool Array3DDepthModel::insertRows (int row, int count, const QModelIndex & parent = QModelIndex()) override
Definition at line 291 of file ArrayModel.cpp.
References src.Mod.AddonManager.NetworkManager::count, Materials::MaterialValue::getQuantityFormat(), SplineSurface::i, Init::parent, and src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::Quantity.
Referenced by setData().
newRow()
bool Array3DDepthModel::newRow (const QModelIndex & index) const override virtual
Implements MatGui::AbstractArrayModel.
Definition at line 218 of file ArrayModel.cpp.
removeColumns()
bool Array3DDepthModel::removeColumns (int column, int count, const QModelIndex & parent = QModelIndex()) override
Definition at line 328 of file ArrayModel.cpp.
References App::ExpressionParser::column, src.Mod.AddonManager.NetworkManager::count, and Init::parent.
removeRows()
bool Array3DDepthModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex()) override
Definition at line 306 of file ArrayModel.cpp.
References src.Mod.AddonManager.NetworkManager::count, SplineSurface::i, and Init::parent.
Referenced by deleteRow().
rowCount()
int Array3DDepthModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 209 of file ArrayModel.cpp.
References Init::parent.
Referenced by headerData().
setData()
bool Array3DDepthModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) override
Definition at line 270 of file ArrayModel.cpp.
References insertRows().
The documentation for this class was generated from the following files:
ArrayModel.h
ArrayModel.cpp