FreeCAD: MeshCore::MeshEvalOrientation Class Reference
MeshCore::MeshEvalOrientation Class Reference
#include <Evaluation.h>
Public Member Functions
MeshEvalOrientation (const MeshKernel &rclM)
bool Evaluate () override
std::vector< FacetIndex > GetIndices () const
Public Member Functions inherited from MeshCore::MeshEvaluation
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()=default
MeshEvaluation (const MeshEvaluation &)=delete
MeshEvaluation (MeshEvaluation &&)=delete
MeshEvaluation & operator= (const MeshEvaluation &)=delete
MeshEvaluation & operator= (MeshEvaluation &&)=delete
Additional Inherited Members
Protected Attributes inherited from MeshCore::MeshEvaluation
const MeshKernel & _rclMesh
Detailed Description
The MeshEvalOrientation class checks the mesh kernel for consistent facet normals.
Author
Werner Mayer
Definition at line 179 of file Evaluation.h.
Constructor & Destructor Documentation
MeshEvalOrientation()
MeshEvalOrientation::MeshEvalOrientation (const MeshKernel & rclM) explicit
Definition at line 127 of file Evaluation.cpp.
Member Function Documentation
Evaluate()
bool MeshEvalOrientation::Evaluate () override virtual
Evaluates the mesh kernel with respect to certain criteria. Must be reimplemented by every subclass. This pure virtual function returns false if the mesh kernel is invalid according to this criterion and true if the mesh kernel is correct.
Implements MeshCore::MeshEvaluation.
Definition at line 131 of file Evaluation.cpp.
References MeshCore::MeshFacet::_aulPoints, MeshCore::MeshEvaluation::_rclMesh, MeshCore::FACET_INDEX_MAX, MeshCore::MeshKernel::GetFacets(), and SplineSurface::i.
Referenced by MeshCore::MeshFixOrientation::Fixup().
GetIndices()
std::vector< FacetIndex > MeshEvalOrientation::GetIndices () const
Definition at line 185 of file Evaluation.cpp.
References MeshCore::MeshEvaluation::_rclMesh, MeshCore::MeshKernel::CountFacets(), KDL::diff(), SCL.SimpleDataTypes::f, MeshCore::FACET_INDEX_MAX, MeshCore::MeshKernel::GetFacets(), MeshCore::MeshAlgorithm::ResetFacetFlag(), MeshCore::MeshAlgorithm::ResetFacetsFlag(), MeshCore::MeshAlgorithm::SetFacetsFlag(), MeshCore::MeshFacet::TMP0, MeshCore::MeshFacet::VISIT, and MeshCore::MeshKernel::VisitNeighbourFacets().
Referenced by Mesh::MeshObject::countNonUniformOrientedFacets(), and MeshCore::MeshTopoAlgorithm::HarmonizeNormals().
The documentation for this class was generated from the following files:
Evaluation.h
Evaluation.cpp