FreeCAD: Gui::Inventor::SoDrawingGrid Class Reference
Gui::Inventor::SoDrawingGrid Class Reference
#include <SoDrawingGrid.h>
Public Member Functions
SoDrawingGrid ()
void GLRender (SoGLRenderAction *action) override
void GLRenderBelowPath (SoGLRenderAction *action) override
void GLRenderInPath (SoGLRenderAction *action) override
void GLRenderOffPath (SoGLRenderAction *action) override
void computeBBox (SoAction *action, SbBox3f &box, SbVec3f &center) override
void generatePrimitives (SoAction *action) override
Static Public Member Functions
static void initClass ()
Detailed Description
Definition at line 71 of file SoDrawingGrid.h.
Constructor & Destructor Documentation
SoDrawingGrid()
SoDrawingGrid::SoDrawingGrid ()
Definition at line 59 of file SoDrawingGrid.cpp.
Member Function Documentation
computeBBox()
void SoDrawingGrid::computeBBox (SoAction * action, SbBox3f & box, SbVec3f & center) override
Definition at line 184 of file SoDrawingGrid.cpp.
References Path.Post.scripts.dynapath_4060_post::action, MengerSponge::box, and exportCSG::center().
generatePrimitives()
void SoDrawingGrid::generatePrimitives (SoAction * action) override
Definition at line 178 of file SoDrawingGrid.cpp.
References Path.Post.scripts.dynapath_4060_post::action.
GLRender()
void SoDrawingGrid::GLRender (SoGLRenderAction * action) override
Definition at line 120 of file SoDrawingGrid.cpp.
References Path.Post.scripts.dynapath_4060_post::action, GLRenderBelowPath(), and GLRenderInPath().
GLRenderBelowPath()
void SoDrawingGrid::GLRenderBelowPath (SoGLRenderAction * action) override
Definition at line 139 of file SoDrawingGrid.cpp.
References Path.Post.scripts.dynapath_4060_post::action, glDisable, and glEnable.
Referenced by GLRender().
GLRenderInPath()
void SoDrawingGrid::GLRenderInPath (SoGLRenderAction * action) override
Definition at line 156 of file SoDrawingGrid.cpp.
References Path.Post.scripts.dynapath_4060_post::action, glDisable, and glEnable.
Referenced by GLRender().
GLRenderOffPath()
void SoDrawingGrid::GLRenderOffPath (SoGLRenderAction * action) override
Definition at line 173 of file SoDrawingGrid.cpp.
initClass()
void SoDrawingGrid::initClass () static
Definition at line 54 of file SoDrawingGrid.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
The documentation for this class was generated from the following files:
SoDrawingGrid.h
SoDrawingGrid.cpp