FreeCAD: TechDrawGui::TaskRichAnno Class Reference
TechDrawGui::TaskRichAnno Class Reference
#include <TaskRichAnno.h>
Public Slots
void onEditorClicked (bool clicked)
Public Member Functions
TaskRichAnno (TechDraw::DrawView *baseFeat, TechDraw::DrawPage *page)
TaskRichAnno (TechDrawGui::ViewProviderRichAnno *annoVP)
~TaskRichAnno () override=default
virtual bool accept ()
virtual bool reject ()
virtual void setCreateMode (bool mode)
virtual bool getCreateMode ()
void updateTask ()
void saveButtons (QPushButton *btnOK, QPushButton *btnCancel)
void enableTaskButtons (bool enable)
Protected Slots
void onSaveAndExit (QString)
void onEditorExit ()
Protected Member Functions
void changeEvent (QEvent *event) override
void createAnnoFeature ()
void updateAnnoFeature ()
void commonFeatureUpdate ()
void removeFeature ()
QPointF calcTextStartPos (double scale)
void setUiPrimary ()
void setUiEdit ()
void enableTextUi (bool enable)
void enableVPUi (bool enable)
double prefWeight () const
App::Color prefLineColor ()
Detailed Description
Definition at line 53 of file TaskRichAnno.h.
Constructor & Destructor Documentation
TaskRichAnno() [1/2]
TaskRichAnno::TaskRichAnno (TechDraw::DrawView * baseFeat, TechDraw::DrawPage * page)
Definition at line 113 of file TaskRichAnno.cpp.
References draftgeoutils.intersections::connect(), TechDrawGui::QGSPage::findQViewForDocObj(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), TechDrawGui::ViewProviderPage::getQGSPage(), Gui::Document::getViewProvider(), Gui::Application::Instance, onEditorClicked(), and setUiPrimary().
TaskRichAnno() [2/2]
TaskRichAnno::TaskRichAnno (TechDrawGui::ViewProviderRichAnno * annoVP) explicit
Definition at line 58 of file TaskRichAnno.cpp.
References TechDraw::DrawRichAnno::AnnoParent, draftgeoutils.intersections::connect(), Base::Console(), Base::ConsoleSingleton::Error(), TechDraw::DrawRichAnno::findParentPage(), TechDrawGui::QGSPage::findQViewForDocObj(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), TechDrawGui::ViewProviderRichAnno::getFeature(), TechDrawGui::ViewProviderPage::getQGSPage(), App::PropertyQuantity::getValue(), App::PropertyLink::getValue(), Gui::Document::getViewProvider(), TechDrawGui::Rez::guiX(), Gui::Application::Instance, Base::BaseClass::isDerivedFrom(), onEditorClicked(), setUiEdit(), TechDraw::DrawView::X, and TechDraw::DrawView::Y.
~TaskRichAnno()
TechDrawGui::TaskRichAnno::~TaskRichAnno () override default
Member Function Documentation
accept()
bool TaskRichAnno::accept () virtual
Definition at line 467 of file TaskRichAnno.cpp.
References createAnnoFeature(), toolbit-attributes::doc, doCommand, getCreateMode(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::Command::Gui, Gui::Application::Instance, TechDraw::DrawView::requestPaint(), and updateAnnoFeature().
Referenced by TechDrawGui::TaskDlgRichAnno::accept().
calcTextStartPos()
QPointF TaskRichAnno::calcTextStartPos (double scale) protected
Definition at line 401 of file TaskRichAnno.cpp.
References Base::Console(), Base::Persistence::getClassTypeId(), TechDraw::DrawPage::getPageHeight(), TechDraw::DrawPage::getPageWidth(), App::PropertyFloat::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), TechDrawGui::Rez::guiX(), Base::BaseClass::isDerivedFrom(), TechDraw::DrawRichAnno::MaxWidth, Base::ConsoleSingleton::Message(), src.Mod.PartDesign.fcgear.svggear::w, and TechDraw::DrawLeaderLine::WayPoints.
Referenced by createAnnoFeature().
changeEvent()
void TaskRichAnno::changeEvent (QEvent * event) override protected
Definition at line 154 of file TaskRichAnno.cpp.
commonFeatureUpdate()
void TaskRichAnno::commonFeatureUpdate () protected
Definition at line 363 of file TaskRichAnno.cpp.
References TechDraw::DrawRichAnno::AnnoText, TechDrawGui::Rez::appX(), TechDraw::DrawRichAnno::MaxWidth, TechDraw::DrawView::setPosition(), App::PropertyFloat::setValue(), App::PropertyString::setValue(), App::PropertyBool::setValue(), TechDraw::DrawRichAnno::ShowFrame, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by createAnnoFeature(), and updateAnnoFeature().
createAnnoFeature()
void TaskRichAnno::createAnnoFeature () protected
Definition at line 279 of file TaskRichAnno.cpp.
References TechDrawGui::Rez::appX(), calcTextStartPos(), Gui::Command::commitCommand(), commonFeatureUpdate(), doCommand, Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::Document::getObject(), TechDraw::DrawPage::getPageHeight(), TechDraw::DrawPage::getPageWidth(), TechDraw::DrawView::getScale(), App::Document::getUniqueObjectName(), TechDrawGui::QGIView::getViewProvider(), Base::BaseClass::isDerivedFrom(), App::DocumentObject::Label, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, TechDraw::DrawView::requestPaint(), App::PropertyQuantity::setValue(), App::Color::setValue(), App::PropertyString::setValue(), App::DocumentObject::touch(), Gui::Command::updateActive(), TechDraw::DrawView::X, Base::Vector3< float_type >::x, TechDraw::DrawView::Y, and Base::Vector3< float_type >::y.
Referenced by accept().
enableTaskButtons()
void TaskRichAnno::enableTaskButtons (bool enable)
Definition at line 459 of file TaskRichAnno.cpp.
enableTextUi()
void TaskRichAnno::enableTextUi (bool enable) protected
Definition at line 183 of file TaskRichAnno.cpp.
Referenced by setUiEdit().
enableVPUi()
void TaskRichAnno::enableVPUi (bool enable) protected
Definition at line 191 of file TaskRichAnno.cpp.
Referenced by setUiEdit(), and setUiPrimary().
getCreateMode()
virtual bool TechDrawGui::TaskRichAnno::getCreateMode () inline virtual
Definition at line 66 of file TaskRichAnno.h.
Referenced by accept(), and reject().
onEditorClicked
void TaskRichAnno::onEditorClicked (bool clicked) slot
Definition at line 225 of file TaskRichAnno.cpp.
References draftgeoutils.intersections::connect(), MRichTextEdit::editorFinished(), onEditorExit(), onSaveAndExit(), and MRichTextEdit::saveText().
Referenced by TaskRichAnno().
onEditorExit
void TaskRichAnno::onEditorExit () protected slot
Definition at line 260 of file TaskRichAnno.cpp.
Referenced by onEditorClicked().
onSaveAndExit
void TaskRichAnno::onSaveAndExit (QString qs) protected slot
Definition at line 251 of file TaskRichAnno.cpp.
Referenced by onEditorClicked().
prefLineColor()
App::Color TaskRichAnno::prefLineColor () protected
Definition at line 272 of file TaskRichAnno.cpp.
References TechDrawGui::PreferencesGui::leaderColor().
Referenced by setUiPrimary().
prefWeight()
double TaskRichAnno::prefWeight () const protected
Definition at line 267 of file TaskRichAnno.cpp.
References TechDraw::LineGroup::getDefaultWidth().
Referenced by setUiPrimary().
reject()
bool TaskRichAnno::reject () virtual
Definition at line 493 of file TaskRichAnno.cpp.
References toolbit-attributes::doc, doCommand, getCreateMode(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::Command::Gui, Gui::Application::Instance, and removeFeature().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and TechDrawGui::TaskDlgRichAnno::reject().
removeFeature()
void TaskRichAnno::removeFeature () protected
Definition at line 372 of file TaskRichAnno.cpp.
References Gui::Application::activeDocument(), Base::Console(), doCommand, App::DocumentObject::getNameInDocument(), Gui::Document::getUndoVector(), Gui::Command::Gui, Gui::Command::hasPendingCommand(), Gui::Application::Instance, Gui::Document::undo(), and Base::ConsoleSingleton::Warning().
Referenced by reject().
saveButtons()
void TaskRichAnno::saveButtons (QPushButton * btnOK, QPushButton * btnCancel)
Definition at line 452 of file TaskRichAnno.cpp.
Referenced by TechDrawGui::TaskDlgRichAnno::modifyStandardButtons().
setCreateMode()
virtual void TechDrawGui::TaskRichAnno::setCreateMode (bool mode) inline virtual
Definition at line 65 of file TaskRichAnno.h.
setUiEdit()
void TaskRichAnno::setUiEdit () protected
Definition at line 199 of file TaskRichAnno.cpp.
References TechDraw::DrawRichAnno::AnnoParent, TechDraw::DrawRichAnno::AnnoText, App::Color::asValue(), enableTextUi(), enableVPUi(), App::DocumentObject::getNameInDocument(), App::PropertyQuantity::getValue(), App::PropertyEnumeration::getValue(), App::PropertyFloat::getValue(), App::PropertyLink::getValue(), App::PropertyString::getValue(), App::PropertyBool::getValue(), App::PropertyColor::getValue(), TechDrawGui::ViewProviderRichAnno::LineColor, TechDrawGui::ViewProviderRichAnno::LineStyle, TechDrawGui::ViewProviderRichAnno::LineWidth, TechDraw::DrawRichAnno::MaxWidth, and TechDraw::DrawRichAnno::ShowFrame.
Referenced by TaskRichAnno().
setUiPrimary()
void TaskRichAnno::setUiPrimary () protected
Definition at line 161 of file TaskRichAnno.cpp.
References enableVPUi(), App::DocumentObject::getNameInDocument(), Base::Unit::Length, prefLineColor(), and prefWeight().
Referenced by TaskRichAnno().
updateAnnoFeature()
void TaskRichAnno::updateAnnoFeature () protected
Definition at line 348 of file TaskRichAnno.cpp.
References Gui::Command::commitCommand(), commonFeatureUpdate(), TechDrawGui::ViewProviderRichAnno::LineColor, TechDrawGui::ViewProviderRichAnno::LineStyle, TechDrawGui::ViewProviderRichAnno::LineWidth, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, App::PropertyQuantity::setValue(), App::PropertyEnumeration::setValue(), App::Color::setValue(), App::PropertyColor::setValue(), and Gui::Command::updateActive().
Referenced by accept().
updateTask()
void TaskRichAnno::updateTask ()
Definition at line 147 of file TaskRichAnno.cpp.
The documentation for this class was generated from the following files:
TaskRichAnno.h
TaskRichAnno.cpp