FreeCAD: TimingInfo Struct Reference
TimingInfo Struct Reference
Public Member Functions
TimingInfo (FC_DURATION &d)
~TimingInfo ()
void stop ()
void reset ()
Public Attributes
bool timed = false
FC_TIME_POINT t
FC_DURATION & d
Detailed Description
Definition at line 167 of file Tree.cpp.
Constructor & Destructor Documentation
TimingInfo()
TimingInfo::TimingInfo (FC_DURATION & d) inline explicit
Definition at line 171 of file Tree.cpp.
References _FC_TIME_INIT, and InitGui::t.
~TimingInfo()
TimingInfo::~TimingInfo () inline
Definition at line 176 of file Tree.cpp.
Member Function Documentation
reset()
void TimingInfo::reset () inline
Definition at line 185 of file Tree.cpp.
References _FC_TIME_INIT, and InitGui::t.
Referenced by ArchVRM.Renderer::__init__(), draftguitools.gui_trackers.gridTracker::set(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testAll(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
stop()
void TimingInfo::stop () inline
Definition at line 179 of file Tree.cpp.
References FC_DURATION_PLUS, and InitGui::t.
Referenced by bimcommands.BimPanel.NestTaskPanel::accept(), and bimcommands.BimPanel.NestTaskPanel::reject().
Member Data Documentation
d
FC_DURATION& TimingInfo::d
Definition at line 170 of file Tree.cpp.
t
FC_TIME_POINT TimingInfo::t
Definition at line 169 of file Tree.cpp.
timed
bool TimingInfo::timed = false
Definition at line 168 of file Tree.cpp.
The documentation for this struct was generated from the following file:
Tree.cpp