FreeCAD: Gui::So3DAnnotation Class Reference
Gui::So3DAnnotation Class Reference
3D Annotation Node - Annotation with depth buffer
#include <So3DAnnotation.h>
Public Member Functions
So3DAnnotation ()
virtual void GLRender (SoGLRenderAction *action)
virtual void GLRenderBelowPath (SoGLRenderAction *action)
virtual void GLRenderInPath (SoGLRenderAction *action)
virtual void GLRenderOffPath (SoGLRenderAction *action)
Static Public Member Functions
static void initClass ()
Protected Member Functions
virtual ~So3DAnnotation ()=default
Detailed Description
3D Annotation Node - Annotation with depth buffer
This class is just like SoAnnotation with the difference that it does not disable the depth buffer instead it clears it and renders on top of everything with proper depth control.
It should be used with caution as it does clear the depth buffer for each annotation!
Definition at line 60 of file So3DAnnotation.h.
Constructor & Destructor Documentation
So3DAnnotation()
So3DAnnotation::So3DAnnotation ()
Definition at line 40 of file So3DAnnotation.cpp.
~So3DAnnotation()
virtual Gui::So3DAnnotation::~So3DAnnotation () protected virtual default
Member Function Documentation
GLRender()
void So3DAnnotation::GLRender (SoGLRenderAction * action) virtual
Definition at line 50 of file So3DAnnotation.cpp.
References Path.Post.scripts.dynapath_4060_post::action, GLRenderBelowPath(), and GLRenderInPath().
GLRenderBelowPath()
void So3DAnnotation::GLRenderBelowPath (SoGLRenderAction * action) virtual
Definition at line 66 of file So3DAnnotation.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and glClear.
Referenced by GLRender().
GLRenderInPath()
void So3DAnnotation::GLRenderInPath (SoGLRenderAction * action) virtual
Definition at line 78 of file So3DAnnotation.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and glClear.
Referenced by GLRender().
GLRenderOffPath()
void So3DAnnotation::GLRenderOffPath (SoGLRenderAction * action) virtual
Definition at line 90 of file So3DAnnotation.cpp.
initClass()
void So3DAnnotation::initClass () static
Definition at line 45 of file So3DAnnotation.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
The documentation for this class was generated from the following files:
So3DAnnotation.h
So3DAnnotation.cpp