FreeCAD: MeshCore::FacetCurvature Class Reference
MeshCore::FacetCurvature Class Reference
#include <Curvature.h>
Public Member Functions
FacetCurvature (const MeshKernel &kernel, const MeshRefPointToFacets &search, float, unsigned long)
CurvatureInfo Compute (FacetIndex index) const
Detailed Description
Definition at line 63 of file Curvature.h.
Constructor & Destructor Documentation
FacetCurvature()
FacetCurvature::FacetCurvature (const MeshKernel & kernel, const MeshRefPointToFacets & search, float r, unsigned long pt)
Definition at line 374 of file Curvature.cpp.
Member Function Documentation
Compute()
CurvatureInfo FacetCurvature::Compute (FacetIndex index) const
Definition at line 384 of file Curvature.cpp.
References MeshCore::Approximation::AddPoints(), MeshCore::SurfaceFit::Fit(), MeshCore::SurfaceFit::GetCurvatureInfo(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshGeomFacet::GetGravityPoint(), MeshCore::PlaneFit::GetNormal(), MeshCore::MeshGeomFacet::GetNormal(), MeshCore::MeshKernel::GetPoints(), Path.Log::info(), MeshCore::MeshRefPointToFacets::Neighbours(), and KDL::sqrt().
Referenced by MeshCore::MeshCurvature::ComputePerFace().
The documentation for this class was generated from the following files:
Curvature.h
Curvature.cpp