FreeCAD: Gui::SplashObserver Class Reference
Gui::SplashObserver Class Reference
Public Member Functions
SplashObserver (const SplashObserver &)=delete
SplashObserver (SplashObserver &&)=delete
SplashObserver & operator= (const SplashObserver &)=delete
SplashObserver & operator= (SplashObserver &&)=delete
SplashObserver (QSplashScreen *splasher=nullptr)
~SplashObserver () override
const char * Name () override
void SendLog (const std::string &notifiername, const std::string &msg, Base::LogStyle level, Base::IntendedRecipient recipient, Base::ContentType content) override
void Log (const std::string &text)
Public Member Functions inherited from Base::ILogger
ILogger ()=default
ILogger (const ILogger &)=delete
ILogger (ILogger &&)=delete
ILogger & operator= (const ILogger &)=delete
ILogger & operator= (ILogger &&)=delete
virtual ~ILogger ()=0
bool isActive (Base::LogStyle category) const
Additional Inherited Members
Public Attributes inherited from Base::ILogger
bool bErr {true}
bool bMsg {true}
bool bLog {true}
bool bWrn {true}
bool bCritical {true}
bool bNotification {false}
Detailed Description
Displays all messages at startup inside the splash screen.
Author
Werner Mayer
Definition at line 55 of file SplashScreen.cpp.
Constructor & Destructor Documentation
SplashObserver() [1/3]
Gui::SplashObserver::SplashObserver (const SplashObserver &) delete
SplashObserver() [2/3]
Gui::SplashObserver::SplashObserver (SplashObserver &&) delete
SplashObserver() [3/3]
Gui::SplashObserver::SplashObserver (QSplashScreen * splasher = nullptr) inline explicit
Definition at line 63 of file SplashScreen.cpp.
References Base::ConsoleSingleton::AttachObserver(), black, App::Application::Config(), and Base::Console().
~SplashObserver()
Gui::SplashObserver::~SplashObserver () inline override
Definition at line 108 of file SplashScreen.cpp.
References Base::Console(), and Base::ConsoleSingleton::DetachObserver().
Member Function Documentation
Log()
void Gui::SplashObserver::Log (const std::string & text) inline
Definition at line 135 of file SplashScreen.cpp.
References Path.Op.Surface::msg, and src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression.
Referenced by SendLog().
Name()
const char* Gui::SplashObserver::Name () inline override virtual
Reimplemented from Base::ILogger.
Definition at line 112 of file SplashScreen.cpp.
operator=() [1/2]
SplashObserver& Gui::SplashObserver::operator= (const SplashObserver &) delete
operator=() [2/2]
SplashObserver& Gui::SplashObserver::operator= (SplashObserver &&) delete
SendLog()
void Gui::SplashObserver::SendLog (const std::string & notifiername, const std::string & msg, Base::LogStyle level, Base::IntendedRecipient recipient, Base::ContentType content) inline override virtual
Used to send a Log message at the given level.
Parameters
notifiername A string identifying the entity generating the notification. It may be the Label of the App::Document or the full label of the App::DocumentObject.
msg The message to be notified.
level A valid level (Log, Message, Error, Notification, CriticalNotification, ...)
recipient A valid intended recipient (All, Developer, User). Observers may decide to process only notifications when a certain recipient is intended.
content A valid content property (Untranslated, Translatable, Untranslatable). Observers may decide not to process notifications if they are not translated or cannot be translated (are untranslatable). Or conversely, may decide not to process already translated notifications. It is up to the intended behaviour of the observer.
Implements Base::ILogger.
Definition at line 116 of file SplashScreen.cpp.
References level(), Log(), Base::Log, and Path.Op.Surface::msg.
The documentation for this class was generated from the following file:
SplashScreen.cpp