FreeCAD: FemGui::FunctionWidget Class Reference
FemGui::FunctionWidget Class Reference abstract
#include <ViewProviderFemPostFunction.h>
Public Member Functions
FunctionWidget ()=default
~FunctionWidget () override=default
virtual void applyPythonCode ()=0
virtual void setViewProvider (ViewProviderFemPostFunction *view)
void onObjectsChanged (const App::DocumentObject &obj, const App::Property &)
Protected Member Functions
ViewProviderFemPostFunction * getView ()
Fem::FemPostFunction * getObject () const
template<class T >
T * getObject () const
bool blockObjectUpdates ()
void setBlockObjectUpdates (bool val)
virtual void onChange (const App::Property &p)=0
Detailed Description
Definition at line 52 of file ViewProviderFemPostFunction.h.
Constructor & Destructor Documentation
FunctionWidget()
FemGui::FunctionWidget::FunctionWidget () default
~FunctionWidget()
FemGui::FunctionWidget::~FunctionWidget () override default
Member Function Documentation
applyPythonCode()
virtual void FemGui::FunctionWidget::applyPythonCode () pure virtual
Implemented in FemGui::SphereWidget, FemGui::PlaneWidget, FemGui::CylinderWidget, and FemGui::BoxWidget.
blockObjectUpdates()
bool FemGui::FunctionWidget::blockObjectUpdates () inline protected
Definition at line 78 of file ViewProviderFemPostFunction.h.
getObject() [1/2]
Fem::FemPostFunction* FemGui::FunctionWidget::getObject () const inline protected
Definition at line 68 of file ViewProviderFemPostFunction.h.
getObject() [2/2]
template<class T > T* FemGui::FunctionWidget::getObject () const inline protected
Definition at line 73 of file ViewProviderFemPostFunction.h.
References UtilsAssembly::getObject().
getView()
ViewProviderFemPostFunction* FemGui::FunctionWidget::getView () inline protected
Definition at line 64 of file ViewProviderFemPostFunction.h.
onChange()
virtual void FemGui::FunctionWidget::onChange (const App::Property & p) protected pure virtual
Implemented in FemGui::SphereWidget, FemGui::PlaneWidget, FemGui::CylinderWidget, and FemGui::BoxWidget.
Referenced by onObjectsChanged().
onObjectsChanged()
void FunctionWidget::onObjectsChanged (const App::DocumentObject & obj, const App::Property & p)
Definition at line 80 of file ViewProviderFemPostFunction.cpp.
References onChange(), and buildPsets::p.
Referenced by setViewProvider().
setBlockObjectUpdates()
void FemGui::FunctionWidget::setBlockObjectUpdates (bool val) inline protected
Definition at line 82 of file ViewProviderFemPostFunction.h.
References toolbit-attributes::val.
Referenced by FemGui::BoxWidget::onChange(), FemGui::CylinderWidget::onChange(), FemGui::PlaneWidget::onChange(), FemGui::SphereWidget::onChange(), FemGui::BoxWidget::setViewProvider(), FemGui::CylinderWidget::setViewProvider(), FemGui::PlaneWidget::setViewProvider(), and FemGui::SphereWidget::setViewProvider().
setViewProvider()
void FunctionWidget::setViewProvider (ViewProviderFemPostFunction * view) virtual
Reimplemented in FemGui::SphereWidget, FemGui::PlaneWidget, FemGui::CylinderWidget, and FemGui::BoxWidget.
Definition at line 70 of file ViewProviderFemPostFunction.cpp.
References draftgeoutils.faces::bind(), App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), onObjectsChanged(), and App::Document::signalChangedObject.
Referenced by FemGui::BoxWidget::setViewProvider(), FemGui::CylinderWidget::setViewProvider(), FemGui::PlaneWidget::setViewProvider(), and FemGui::SphereWidget::setViewProvider().
The documentation for this class was generated from the following files:
ViewProviderFemPostFunction.h
ViewProviderFemPostFunction.cpp