FreeCAD: Part::GeomCurve Class Reference
Part::GeomCurve Class Reference
#include <Geometry.h>
Public Member Functions
GeomCurve ()
~GeomCurve () override
bool isLinear (Base::Vector3d *dir=nullptr, Base::Vector3d *base=nullptr) const
TopoDS_Shape toShape () const override
GeomBSplineCurve * toBSpline (double first, double last) const
toBSpline Converts the curve to a B-spline
virtual GeomBSplineCurve * toNurbs (double first, double last) const
virtual GeomCurve * createArc (double first, double last) const
createArc Generates a curve that is an arc of this curve between given parameters
bool tangent (double u, gp_Dir &) const
bool tangent (double u, Base::Vector3d &dir) const
Base::Vector3d pointAtParameter (double u) const
Base::Vector3d firstDerivativeAtParameter (double u) const
Base::Vector3d secondDerivativeAtParameter (double u) const
bool closestParameter (const Base::Vector3d &point, double &u) const
bool closestParameterToBasisCurve (const Base::Vector3d &point, double &u) const
double getFirstParameter () const
double getLastParameter () const
double curvatureAt (double u) const
double length (double u, double v) const
bool normalAt (double u, Base::Vector3d &dir) const
bool normalAt (const Base::Vector3d &curvepoint, Base::Vector3d &dir) const
bool intersect (const GeomCurve *c, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> &points, double tol=Precision::Confusion()) const
void reverse ()
Base::Vector3d value (double u) const
GeomLine * toLine (KeepTag clone=CopyTag) const
GeomLineSegment * toLineSegment (KeepTag clone=CopyTag) const
Public Member Functions inherited from Part::Geometry
~Geometry () override
virtual const Handle (Geom_Geometry) &handle() const =0
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
virtual Geometry * copy () const =0
Geometry * clone () const
boost::uuids::uuid getTag () const
returns the tag of the geometry object
virtual bool isSame (const Geometry &other, double tol, double atol) const =0
bool hasSameExtensions (const Geometry &other) const
std::vector< std::weak_ptr< const GeometryExtension > > getExtensions () const
bool hasExtension (const Base::Type &type) const
bool hasExtension (const std::string &name) const
std::weak_ptr< const GeometryExtension > getExtension (const Base::Type &type) const
std::weak_ptr< const GeometryExtension > getExtension (const std::string &name) const
std::weak_ptr< GeometryExtension > getExtension (const Base::Type &type)
std::weak_ptr< GeometryExtension > getExtension (const std::string &name)
void setExtension (std::unique_ptr< GeometryExtension > &&geo)
void deleteExtension (const Base::Type &type)
void deleteExtension (const std::string &name)
void mirror (const Base::Vector3d &point) const
void mirror (const Base::Vector3d &point, const Base::Vector3d &dir) const
void rotate (const Base::Placement &plm) const
void scale (const Base::Vector3d &vec, double scale) const
void transform (const Base::Matrix4D &mat) const
void translate (const Base::Vector3d &vec) const
Geometry (const Geometry &)=delete
Geometry & operator= (const Geometry &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static bool isLinear (const Handle(Geom_Curve) &c, Base::Vector3d *dir=nullptr, Base::Vector3d *base=nullptr)
Static Public Member Functions inherited from Part::Geometry
static std::unique_ptr< Geometry > fromShape (const TopoDS_Shape &s, bool silent=false)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions
static bool intersect (const Handle(Geom_Curve)&c, const Handle(Geom_Curve)&c2, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> &points, double tol=Precision::Confusion())
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Additional Inherited Members
Protected Member Functions inherited from Part::Geometry
void createNewTag ()
create a new tag for the geometry object
void assignTag (const Part::Geometry *)
copies the tag from the geometry passed as a parameter to this object
void copyNonTag (const Part::Geometry *)
Geometry ()
Protected Attributes inherited from Part::Geometry
boost::uuids::uuid tag
std::vector< std::shared_ptr< GeometryExtension > > extensions
Detailed Description
Definition at line 211 of file Part/App/Geometry.h.
Constructor & Destructor Documentation
GeomCurve()
GeomCurve::GeomCurve () default
~GeomCurve()
GeomCurve::~GeomCurve () override default
Member Function Documentation
closestParameter()
bool GeomCurve::closestParameter (const Base::Vector3d & point, double & u) const
Definition at line 973 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle(), FreeCADInit::Length, pointAtParameter(), THROWM, and buildPsets::u.
Referenced by Sketcher::Sketch::addAngleAtPointConstraint(), Sketcher::Sketch::addPointOnObjectConstraint(), Sketcher::SketchObject::calculateAngleViaPoint(), closestParameterToBasisCurve(), Sketcher::SketchObject::deriveConstraintsForPieces(), Sketcher::SketchObject::fillet(), Sketcher::Sketch::initBSplinePieceMove(), normalAt(), SketcherGui::SnapManager::snapToObject(), Sketcher::SketchObject::split(), and Sketcher::SketchObject::trim().
closestParameterToBasisCurve()
bool GeomCurve::closestParameterToBasisCurve (const Base::Vector3d & point, double & u) const
Definition at line 1006 of file Part/App/Geometry.cpp.
References closestParameter(), Part::Geometry::Handle(), THROWM, and buildPsets::u.
createArc()
GeomCurve * GeomCurve::createArc (double first, double last) const virtual
createArc Generates a curve that is an arc of this curve between given parameters
Parameters
first Parameter at start of arc
last Parameter at end of arc. This may be < first for periodic curves.
Returns
the new curve
Reimplemented in Part::GeomParabola, Part::GeomHyperbola, Part::GeomEllipse, Part::GeomCircle, Part::GeomTrimmedCurve, and Part::GeomBSplineCurve.
Definition at line 798 of file Part/App/Geometry.cpp.
References THROWM.
curvatureAt()
double GeomCurve::curvatureAt (double u) const
Definition at line 1060 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle(), THROWM, and buildPsets::u.
firstDerivativeAtParameter()
Base::Vector3d GeomCurve::firstDerivativeAtParameter (double u) const
Definition at line 847 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle(), buildPsets::u, and SurfaceTests.TestBlendCurve::vec.
Referenced by Sketcher::SketchObject::fillet().
getFirstParameter()
double GeomCurve::getFirstParameter () const
Definition at line 1032 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle(), and THROWM.
Referenced by Sketcher::SketchObject::convertToNURBS(), Sketcher::SketchObject::fillet(), Sketcher::SketchObject::insertBSplineKnot(), Sketcher::SketchObject::split(), toLine(), toLineSegment(), Part::GeomBSplineCurve::Trim(), and Sketcher::SketchObject::trim().
getLastParameter()
double GeomCurve::getLastParameter () const
Definition at line 1046 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle(), and THROWM.
Referenced by Sketcher::SketchObject::convertToNURBS(), Sketcher::SketchObject::insertBSplineKnot(), Sketcher::SketchObject::split(), toLine(), toLineSegment(), and Part::GeomBSplineCurve::Trim().
intersect() [1/2]
bool GeomCurve::intersect (const GeomCurve * c, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> & points, double tol = Precision::Confusion()) const
Definition at line 900 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle().
Referenced by Sketcher::SketchObject::fillet(), and Part::GeomTrimmedCurve::intersectBasisCurves().
intersect() [2/2]
bool GeomCurve::intersect (const Handle(Geom_Curve)& c, const Handle(Geom_Curve)& c2, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> & points, double tol = Precision::Confusion()) static protected
Definition at line 915 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle(), and THROWM.
isLinear() [1/2]
bool GeomCurve::isLinear (Base::Vector3d * dir = nullptr, Base::Vector3d * base = nullptr) const
Definition at line 703 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle(), and isLinear().
isLinear() [2/2]
bool GeomCurve::isLinear (const Handle(Geom_Curve) & c, Base::Vector3d * dir = nullptr, Base::Vector3d * base = nullptr) static
Definition at line 709 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::e, Part::Geometry::Handle(), IsLinear(), and THROWM.
Referenced by FC_LOG_LEVEL_INIT(), isLinear(), Part::GeomBSplineCurve::isSame(), toLine(), and toLineSegment().
length()
double GeomCurve::length (double u, double v) const
Definition at line 1074 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle(), FreeCADInit::Length, THROWM, buildPsets::u, and TestSpreadsheet::v.
Referenced by src.Mod.PartDesign.Scripts.FilletArc.Vector::norm(), and Part::GeomParabola::setFocal().
normalAt() [1/2]
bool GeomCurve::normalAt (const Base::Vector3d & curvepoint, Base::Vector3d & dir) const
Definition at line 892 of file Part/App/Geometry.cpp.
References closestParameter(), normalAt(), and buildPsets::u.
normalAt() [2/2]
bool GeomCurve::normalAt (double u, Base::Vector3d & dir) const
Definition at line 867 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle(), Base::Vector3< float_type >::Set(), THROWM, and buildPsets::u.
Referenced by normalAt().
pointAtParameter()
Base::Vector3d GeomCurve::pointAtParameter (double u) const
Definition at line 837 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle(), and buildPsets::u.
Referenced by closestParameter(), Sketcher::SketchObject::exposeInternalGeometry(), Sketcher::SketchObject::fillet(), toLine(), and toLineSegment().
reverse()
void GeomCurve::reverse ()
Definition at line 1089 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle(), and THROWM.
secondDerivativeAtParameter()
Base::Vector3d GeomCurve::secondDerivativeAtParameter (double u) const
Definition at line 857 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle(), buildPsets::u, and SurfaceTests.TestBlendCurve::vec.
tangent() [1/2]
bool GeomCurve::tangent (double u, Base::Vector3d & dir) const
Definition at line 815 of file Part/App/Geometry.cpp.
References tangent(), and buildPsets::u.
tangent() [2/2]
bool GeomCurve::tangent (double u, gp_Dir & dir) const
Definition at line 803 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle(), and buildPsets::u.
Referenced by Sketcher::SketchObject::fillet(), and tangent().
toBSpline()
GeomBSplineCurve * GeomCurve::toBSpline (double first, double last) const
toBSpline Converts the curve to a B-spline
Parameters
This is the start parameter of the curve
This is the end parameter of the curve
Returns
a B-spline curve
Definition at line 783 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, Part::Geometry::Handle(), and THROWM.
Referenced by toNurbs().
toLine()
GeomLine * GeomCurve::toLine (KeepTag clone = CopyTag) const
Definition at line 746 of file Part/App/Geometry.cpp.
References Part::CopyTag, getFirstParameter(), getLastParameter(), isLinear(), pointAtParameter(), and Part::Geometry::tag.
Referenced by Part::Feature::getCameraAlignmentDirection(), and Part::GeomLine::isSame().
toLineSegment()
GeomLineSegment * GeomCurve::toLineSegment (KeepTag clone = CopyTag) const
Definition at line 761 of file Part/App/Geometry.cpp.
References Part::CopyTag, Base::Persistence::getClassTypeId(), getFirstParameter(), getLastParameter(), Base::BaseClass::isDerivedFrom(), isLinear(), pointAtParameter(), Part::GeomLineSegment::setPoints(), and Part::Geometry::tag.
Referenced by Part::GeomBSplineCurve::isSame().
toNurbs()
GeomBSplineCurve * GeomCurve::toNurbs (double first, double last) const virtual
The default implementation does the same as toBSpline. In sub-classes this can be reimplemented to create a real NURBS curve and not just an approximation.
Reimplemented in Part::GeomArcOfParabola, Part::GeomParabola, Part::GeomArcOfHyperbola, Part::GeomHyperbola, Part::GeomArcOfEllipse, Part::GeomEllipse, Part::GeomArcOfCircle, Part::GeomCircle, and Part::GeomConic.
Definition at line 793 of file Part/App/Geometry.cpp.
References toBSpline().
Referenced by Sketcher::SketchObject::convertToNURBS(), and Part::GeomParabola::toNurbs().
toShape()
TopoDS_Shape GeomCurve::toShape () const override virtual
Implements Part::Geometry.
Definition at line 665 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, and Part::Geometry::Handle().
value()
Base::Vector3d GeomCurve::value (double u) const
Definition at line 828 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle(), and buildPsets::u.
Referenced by src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), and src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue().
The documentation for this class was generated from the following files:
Part/App/Geometry.h
Part/App/Geometry.cpp