FreeCAD: Assembly Namespace Reference
Assembly Namespace Reference
Classes
class AssemblyLink
class AssemblyObject
class BomDataElement
class BomGroup
class BomObject
class JointGroup
class Module
struct ObjRef
class SimulationGroup
class ViewGroup
Enumerations
enum JointType {
JointType::Fixed, JointType::Revolute, JointType::Cylindrical, JointType::Slider,
JointType::Ball, JointType::Distance, JointType::Parallel, JointType::Perpendicular,
JointType::Angle, JointType::RackPinion, JointType::Screw, JointType::Gears,
JointType::Belt
}
enum GeometryType {
GeometryType::Point = 0, GeometryType::Line = 1, GeometryType::Curve = 2, GeometryType::Circle = 3,
GeometryType::Place = 4, GeometryType::Cylinder = 5, GeometryType::Sphere = 6, GeometryType::Cone = 7,
GeometryType::Torus = 8
}
enum DistanceType {
DistanceType::PointPoint, DistanceType::LineLine, DistanceType::LineCircle, DistanceType::CircleCircle,
DistanceType::PlanePlane, DistanceType::PlaneCylinder, DistanceType::PlaneSphere, DistanceType::PlaneCone,
DistanceType::PlaneTorus, DistanceType::CylinderCylinder, DistanceType::CylinderSphere, DistanceType::CylinderCone,
DistanceType::CylinderTorus, DistanceType::ConeCone, DistanceType::ConeTorus, DistanceType::ConeSphere,
DistanceType::TorusTorus, DistanceType::TorusSphere, DistanceType::SphereSphere, DistanceType::PointPlane,
DistanceType::PointCylinder, DistanceType::PointSphere, DistanceType::PointCone, DistanceType::PointTorus,
DistanceType::LinePlane, DistanceType::LineCylinder, DistanceType::LineSphere, DistanceType::LineCone,
DistanceType::LineTorus, DistanceType::CurvePlane, DistanceType::CurveCylinder, DistanceType::CurveSphere,
DistanceType::CurveCone, DistanceType::CurveTorus, DistanceType::PointLine, DistanceType::PointCurve,
DistanceType::Other
}
Functions
PyObject * initModule ()
void swapJCS (const App::DocumentObject *joint)
bool isEdgeType (const App::DocumentObject *obj, const std::string &elName, const GeomAbs_CurveType type)
bool isFaceType (const App::DocumentObject *obj, const std::string &elName, const GeomAbs_SurfaceType type)
double getFaceRadius (const App::DocumentObject *obj, const std::string &elt)
double getEdgeRadius (const App::DocumentObject *obj, const std::string &elt)
DistanceType getDistanceType (App::DocumentObject *joint)
JointGroup * getJointGroup (const App::Part *part)
void setJointActivated (const App::DocumentObject *joint, bool val)
bool getJointActivated (const App::DocumentObject *joint)
double getJointDistance (const App::DocumentObject *joint, const char *propertyName)
double getJointDistance (const App::DocumentObject *joint)
double getJointDistance2 (const App::DocumentObject *joint)
JointType getJointType (const App::DocumentObject *joint)
std::vector< std::string > getSubAsList (const App::PropertyXLinkSub *prop)
std::vector< std::string > getSubAsList (const App::DocumentObject *obj, const char *pName)
std::string getElementFromProp (const App::DocumentObject *obj, const char *pName)
std::string getElementTypeFromProp (const App::DocumentObject *obj, const char *propName)
App::DocumentObject * getObjFromProp (const App::DocumentObject *joint, const char *pName)
App::DocumentObject * getObjFromRef (const App::DocumentObject *obj, const std::string &sub)
App::DocumentObject * getObjFromRef (const App::PropertyXLinkSub *prop)
App::DocumentObject * getObjFromRef (const App::DocumentObject *joint, const char *pName)
App::DocumentObject * getLinkedObjFromRef (const App::DocumentObject *joint, const char *pObj)
App::DocumentObject * getMovingPartFromRef (const AssemblyObject *assemblyObject, App::DocumentObject *obj, const std::string &sub)
App::DocumentObject * getMovingPartFromRef (const AssemblyObject *assemblyObject, App::PropertyXLinkSub *prop)
App::DocumentObject * getMovingPartFromRef (const AssemblyObject *assemblyObject, App::DocumentObject *joint, const char *pName)
AssemblyExport App::DocumentObject * getMovingPartFromRef (const AssemblyObject *assemblyObject, const App::PropertyXLinkSub *prop)
Enumeration Type Documentation
DistanceType
enum Assembly::DistanceType strong
Enumerator
PointPoint
LineLine
LineCircle
CircleCircle
PlanePlane
PlaneCylinder
PlaneSphere
PlaneCone
PlaneTorus
CylinderCylinder
CylinderSphere
CylinderCone
CylinderTorus
ConeCone
ConeTorus
ConeSphere
TorusTorus
TorusSphere
SphereSphere
PointPlane
PointCylinder
PointSphere
PointCone
PointTorus
LinePlane
LineCylinder
LineSphere
LineCone
LineTorus
CurvePlane
CurveCylinder
CurveSphere
CurveCone
CurveTorus
PointLine
PointCurve
Other
Definition at line 85 of file AssemblyUtils.h.
GeometryType
enum Assembly::GeometryType strong
Enumerator
Point
Line
Curve
Circle
Place
Cylinder
Sphere
Cone
Torus
Definition at line 68 of file AssemblyUtils.h.
JointType
enum Assembly::JointType strong
Enumerator
Fixed
Revolute
Cylindrical
Slider
Ball
Distance
Parallel
Perpendicular
Angle
RackPinion
Screw
Gears
Belt
Definition at line 51 of file AssemblyUtils.h.
Function Documentation
getDistanceType()
AssemblyExport DistanceType Assembly::getDistanceType (App::DocumentObject * joint)
Definition at line 181 of file AssemblyUtils.cpp.
Referenced by AssemblyGui::ViewProviderAssembly::findDragMode(), and Assembly::AssemblyObject::makeMbdJointDistance().
getEdgeRadius()
AssemblyExport double Assembly::getEdgeRadius (const App::DocumentObject * obj, const std::string & elt)
Definition at line 165 of file AssemblyUtils.cpp.
Referenced by Assembly::AssemblyObject::makeMbdJointDistance().
getElementFromProp()
AssemblyExport std::string Assembly::getElementFromProp (const App::DocumentObject * obj, const char * pName)
Definition at line 505 of file AssemblyUtils.cpp.
Referenced by Assembly::AssemblyObject::makeMbdJointDistance().
getElementTypeFromProp()
AssemblyExport std::string Assembly::getElementTypeFromProp (const App::DocumentObject * obj, const char * propName)
Definition at line 519 of file AssemblyUtils.cpp.
getFaceRadius()
AssemblyExport double Assembly::getFaceRadius (const App::DocumentObject * obj, const std::string & elt)
Definition at line 146 of file AssemblyUtils.cpp.
References Part::TopoShape::getSubShape().
Referenced by Assembly::AssemblyObject::makeMbdJointDistance().
getJointActivated()
AssemblyExport bool Assembly::getJointActivated (const App::DocumentObject * joint)
Definition at line 433 of file AssemblyUtils.cpp.
Referenced by Assembly::AssemblyObject::getDownstreamParts(), and Assembly::AssemblyObject::isJointConnectingPartToGround().
getJointDistance() [1/2]
AssemblyExport double Assembly::getJointDistance (const App::DocumentObject * joint)
Definition at line 459 of file AssemblyUtils.cpp.
getJointDistance() [2/2]
double Assembly::getJointDistance (const App::DocumentObject * joint, const char * propertyName)
Definition at line 445 of file AssemblyUtils.cpp.
Referenced by Assembly::AssemblyObject::makeMbdJointDistance(), and Assembly::AssemblyObject::makeMbdJointOfType().
getJointDistance2()
AssemblyExport double Assembly::getJointDistance2 (const App::DocumentObject * joint)
Definition at line 464 of file AssemblyUtils.cpp.
Referenced by Assembly::AssemblyObject::makeMbdJointOfType().
getJointGroup()
AssemblyExport JointGroup * Assembly::getJointGroup (const App::Part * part)
Definition at line 402 of file AssemblyUtils.cpp.
References App::ExtensionContainer::getPropertyByName(), and toolbit-attributes::val.
Referenced by Assembly::AssemblyLink::ensureJointGroup(), Assembly::AssemblyLink::ensureNoJointGroup(), Assembly::AssemblyObject::getJointGroup(), and Assembly::AssemblyLink::getJoints().
getJointType()
AssemblyExport JointType Assembly::getJointType (const App::DocumentObject * joint)
Definition at line 469 of file AssemblyUtils.cpp.
Referenced by AssemblyGui::ViewProviderAssembly::findDragMode(), Assembly::AssemblyObject::getMbDData(), Assembly::AssemblyObject::getUpstreamMovingPart(), Assembly::AssemblyObject::isJointTypeConnecting(), Assembly::AssemblyObject::makeMbdJoint(), and Assembly::AssemblyObject::slidingPartIndex().
getLinkedObjFromRef()
AssemblyExport App::DocumentObject * Assembly::getLinkedObjFromRef (const App::DocumentObject * joint, const char * pObj)
Definition at line 654 of file AssemblyUtils.cpp.
Referenced by Assembly::AssemblyObject::makeMbdJointDistance().
getMovingPartFromRef() [1/4]
AssemblyExport App::DocumentObject * Assembly::getMovingPartFromRef (const AssemblyObject * assemblyObject, App::DocumentObject * joint, const char * pName)
Definition at line 742 of file AssemblyUtils.cpp.
getMovingPartFromRef() [2/4]
AssemblyExport App::DocumentObject * Assembly::getMovingPartFromRef (const AssemblyObject * assemblyObject, App::DocumentObject * obj, const std::string & sub)
Definition at line 666 of file AssemblyUtils.cpp.
References toolbit-attributes::doc, App::DocumentObject::getDocument(), and App::DocumentObject::getLinkedObject().
Referenced by AssemblyGui::ViewProviderAssembly::canDragObjectToTarget(), Assembly::AssemblyObject::getConnectedParts(), Assembly::AssemblyObject::getJointOfPartConnectingToGround(), Assembly::AssemblyObject::getJoints(), Assembly::AssemblyObject::getJointsOfPart(), Assembly::AssemblyObject::getMbDData(), getMovingPartFromRef(), Assembly::AssemblyObject::getRackPinionMarkers(), AssemblyGui::ViewProviderAssembly::getSelectedObjectsWithinAssembly(), Assembly::AssemblyObject::getUpstreamMovingPart(), Assembly::AssemblyObject::getUpstreamParts(), Assembly::AssemblyObject::handleOneSideOfJoint(), Assembly::AssemblyObject::isJointConnectingPartToGround(), and Assembly::AssemblyObject::slidingPartIndex().
getMovingPartFromRef() [3/4]
App::DocumentObject* Assembly::getMovingPartFromRef (const AssemblyObject * assemblyObject, App::PropertyXLinkSub * prop)
Definition at line 722 of file AssemblyUtils.cpp.
References getMovingPartFromRef(), and App::ExtensionContainer::getPropertyByName().
getMovingPartFromRef() [4/4]
AssemblyExport App::DocumentObject* Assembly::getMovingPartFromRef (const AssemblyObject * assemblyObject, const App::PropertyXLinkSub * prop)
getObjFromProp()
AssemblyExport App::DocumentObject * Assembly::getObjFromProp (const App::DocumentObject * joint, const char * pName)
Definition at line 531 of file AssemblyUtils.cpp.
Referenced by AssemblyGui::ViewProviderAssembly::canDragObjectToTarget().
getObjFromRef() [1/3]
AssemblyExport App::DocumentObject * Assembly::getObjFromRef (const App::DocumentObject * joint, const char * pName)
Definition at line 644 of file AssemblyUtils.cpp.
getObjFromRef() [2/3]
AssemblyExport App::DocumentObject * Assembly::getObjFromRef (const App::DocumentObject * obj, const std::string & sub)
Definition at line 545 of file AssemblyUtils.cpp.
References App::DocumentObject::getOutList(), UtilsAssembly::isBodySubObject(), and femtools.tokrules::names.
Referenced by AssemblyGui::ViewProviderAssembly::canDragObjectToTarget(), AssemblyGui::ViewProviderAssembly::findDragMode(), Assembly::AssemblyObject::getJointsOfObj(), getObjFromRef(), Assembly::AssemblyObject::getRackPinionMarkers(), AssemblyGui::ViewProviderAssembly::getSelectedObjectsWithinAssembly(), Assembly::AssemblyLink::handleJointReference(), Assembly::AssemblyObject::handleOneSideOfJoint(), and Assembly::AssemblyObject::slidingPartIndex().
getObjFromRef() [3/3]
AssemblyExport App::DocumentObject * Assembly::getObjFromRef (const App::PropertyXLinkSub * prop)
Definition at line 625 of file AssemblyUtils.cpp.
References getObjFromRef(), and App::ExtensionContainer::getPropertyByName().
getSubAsList() [1/2]
AssemblyExport std::vector< std::string > Assembly::getSubAsList (const App::DocumentObject * obj, const char * pName)
Definition at line 497 of file AssemblyUtils.cpp.
getSubAsList() [2/2]
AssemblyExport std::vector< std::string > Assembly::getSubAsList (const App::PropertyXLinkSub * prop)
Definition at line 483 of file AssemblyUtils.cpp.
initModule()
PyObject * Assembly::initModule ()
Definition at line 62 of file AppAssemblyPy.cpp.
Referenced by PyMOD_INIT_FUNC().
isEdgeType()
AssemblyExport bool Assembly::isEdgeType (const App::DocumentObject * obj, const std::string & elName, const GeomAbs_CurveType type)
Definition at line 110 of file AssemblyUtils.cpp.
References Path.Post.scripts.grbl_post::type.
Referenced by TechDraw::ShapeExtractor::is2dObject().
isFaceType()
AssemblyExport bool Assembly::isFaceType (const App::DocumentObject * obj, const std::string & elName, const GeomAbs_SurfaceType type)
Definition at line 128 of file AssemblyUtils.cpp.
setJointActivated()
AssemblyExport void Assembly::setJointActivated (const App::DocumentObject * joint, bool val)
Definition at line 422 of file AssemblyUtils.cpp.
Referenced by Assembly::AssemblyObject::getDownstreamParts(), and Assembly::AssemblyObject::isJointConnectingPartToGround().
swapJCS()
AssemblyExport void Assembly::swapJCS (const App::DocumentObject * joint)
Definition at line 84 of file AssemblyUtils.cpp.
Referenced by Assembly::AssemblyObject::getRackPinionMarkers(), and Assembly::AssemblyObject::makeMbdJointOfType().