FreeCAD: MeshCore::MeshTopFacetVisitor Class Reference
MeshCore::MeshTopFacetVisitor Class Reference
#include <Visitor.h>
Public Member Functions
MeshTopFacetVisitor (std::vector< FacetIndex > &raulNB)
~MeshTopFacetVisitor () override=default
bool Visit (const MeshFacet &rclFacet, const MeshFacet &rclFrom, FacetIndex ulFInd, unsigned long) override
Public Member Functions inherited from MeshCore::MeshFacetVisitor
MeshFacetVisitor ()=default
Construction.
virtual ~MeshFacetVisitor ()=default
Denstruction.
virtual bool AllowVisit (const MeshFacet &rclFacet, const MeshFacet &rclFrom, FacetIndex ulFInd, unsigned long ulLevel, unsigned short neighbourIndex)
Protected Attributes
std::vector< FacetIndex > & _raulNeighbours
Detailed Description
The MeshTopFacetVisitor just collects the indices of all visited facets.
Definition at line 155 of file Visitor.h.
Constructor & Destructor Documentation
MeshTopFacetVisitor()
MeshCore::MeshTopFacetVisitor::MeshTopFacetVisitor (std::vector< FacetIndex > & raulNB) inline explicit
Definition at line 158 of file Visitor.h.
References MeshCore::MeshPlaneVisitor::AllowVisit(), MeshCore::MeshPlaneVisitor::indices, MeshCore::MeshPlaneVisitor::mesh, MeshCore::MeshPlaneVisitor::MeshPlaneVisitor(), and MeshCore::MeshPlaneVisitor::~MeshPlaneVisitor().
~MeshTopFacetVisitor()
MeshCore::MeshTopFacetVisitor::~MeshTopFacetVisitor () override default
Member Function Documentation
Visit()
bool MeshCore::MeshTopFacetVisitor::Visit (const MeshFacet & rclFacet, const MeshFacet & rclFrom, FacetIndex ulFInd, unsigned long) inline override virtual
Collects the facet indices.
Implements MeshCore::MeshFacetVisitor.
Definition at line 163 of file Visitor.h.
Member Data Documentation
_raulNeighbours
std::vector<FacetIndex>& MeshCore::MeshTopFacetVisitor::_raulNeighbours protected
Indices of all visited facets.
Definition at line 175 of file Visitor.h.
The documentation for this class was generated from the following file:
Visitor.h