FreeCAD: App::Range Class Reference
App::Range Class Reference
The Range class is a spreadsheet range iterator. It takes a starting (row, col) and an ending (row, col). Notice that ranges are always at least one element. The next() functions is therefore used e.g as follows:
#include <Range.h>
Public Member Functions
Range (const char *range, bool normalize=false)
Range (int _row_begin, int _col_begin, int _row_end, int _col_end, bool normalize=false)
Range (const CellAddress &from, const CellAddress &to, bool normalize=false)
bool next ()
void normalize ()
int row () const
int column () const
int rowCount () const
int colCount () const
CellAddress from () const
CellAddress to () const
std::string fromCellString () const
std::string toCellString () const
std::string address () const
std::string rangeString () const
CellAddress operator* () const
bool operator< (const Range &other) const
int size () const
Detailed Description
The Range class is a spreadsheet range iterator. It takes a starting (row, col) and an ending (row, col). Notice that ranges are always at least one element. The next() functions is therefore used e.g as follows:
do { ... while (range.next());
Definition at line 181 of file Range.h.
Constructor & Destructor Documentation
Range() [1/3]
Range::Range (const char * range, bool normalize = false) explicit
Definition at line 56 of file Range.cpp.
References App::CellAddress::col(), from(), normalize(), App::CellAddress::row(), toolbit-attributes::s, and to().
Range() [2/3]
Range::Range (int _row_begin, int _col_begin, int _row_end, int _col_end, bool normalize = false)
Definition at line 88 of file Range.cpp.
References normalize().
Range() [3/3]
Range::Range (const CellAddress & from, const CellAddress & to, bool normalize = false)
Definition at line 101 of file Range.cpp.
References normalize().
Member Function Documentation
address()
std::string App::Range::address () const inline
Current cell as a string
Definition at line 244 of file Range.h.
Referenced by App::RangeExpression::_getPyValue(), SpreadsheetGui::DlgSheetConf::accept(), App::FunctionExpression::evalAggregate(), Spreadsheet::PropertySheet::getPyValue(), and Spreadsheet::PropertySheet::setPathValue().
colCount()
int App::Range::colCount () const inline
Column count
Definition at line 214 of file Range.h.
Referenced by SpreadsheetGui::DlgSheetConf::accept(), SpreadsheetGui::DlgSheetConf::DlgSheetConf(), SpreadsheetGui::DlgSheetConf::onDiscard(), Spreadsheet::PropertySheet::pasteCells(), and Spreadsheet::PropertySheet::setPathValue().
column()
int App::Range::column () const inline
Current column
Definition at line 202 of file Range.h.
Referenced by Spreadsheet::PropertySheet::pasteCells().
from()
CellAddress App::Range::from () const inline
Position of start of range
Definition at line 220 of file Range.h.
Referenced by SpreadsheetGui::DlgSheetConf::accept(), SpreadsheetGui::DlgBindSheet::DlgBindSheet(), SpreadsheetGui::DlgSheetConf::DlgSheetConf(), Spreadsheet::PropertySheet::getBinding(), Spreadsheet::PropertySheet::getPyValue(), Spreadsheet::Sheet::mergeCells(), Spreadsheet::PropertySheet::pasteCells(), SpreadsheetGui::SheetTableView::pasteClipboard(), Range(), and Spreadsheet::PropertySheet::setPathValue().
fromCellString()
std::string App::Range::fromCellString () const inline
Start of range as a string
Definition at line 232 of file Range.h.
next()
bool Range::next ()
Definition at line 124 of file Range.cpp.
Referenced by App::RangeExpression::_getPyValue(), SpreadsheetGui::DlgSheetConf::accept(), App::FunctionExpression::evalAggregate(), Spreadsheet::Sheet::getCellBinding(), Spreadsheet::PropertySheet::getPyValue(), Spreadsheet::PropertySheet::pasteCells(), Spreadsheet::Sheet::recomputeCells(), Spreadsheet::PropertySheet::setPathValue(), and Spreadsheet::Sheet::touchCells().
normalize()
void Range::normalize ()
Make sure the range starts from top left and ends with bottom right corner
Definition at line 114 of file Range.cpp.
Referenced by Spreadsheet::Sheet::getCellBinding(), and Range().
operator*()
CellAddress App::Range::operator* () const inline
Definition at line 256 of file Range.h.
operator<()
bool App::Range::operator< (const Range & other) const inline
Definition at line 261 of file Range.h.
rangeString()
std::string App::Range::rangeString () const inline
The raneg as a string
Definition at line 250 of file Range.h.
row()
int App::Range::row () const inline
Current row
Definition at line 196 of file Range.h.
Referenced by Spreadsheet::PropertySheet::pasteCells().
rowCount()
int App::Range::rowCount () const inline
Row count
Definition at line 208 of file Range.h.
Referenced by SpreadsheetGui::DlgSheetConf::accept(), src.Mod.AddonManager.package_list.PackageListItemModel::append_item(), src.Mod.AddonManager.AddonManagerOptions.CustomRepoDataModel::appendData(), src.Mod.AddonManager.package_list.PackageListItemModel::clear(), SpreadsheetGui::DlgSheetConf::onDiscard(), Spreadsheet::PropertySheet::pasteCells(), and Spreadsheet::PropertySheet::setPathValue().
size()
int App::Range::size () const inline
Number of elements in range
Definition at line 273 of file Range.h.
Referenced by SpreadsheetGui::DlgBindSheet::accept(), Path.Post.Utils.GCodeEditorDialog::done(), Spreadsheet::PropertySheet::getPyValue(), and Spreadsheet::PropertySheet::setPathValue().
to()
CellAddress App::Range::to () const inline
Position of end of range
Definition at line 226 of file Range.h.
Referenced by SpreadsheetGui::DlgSheetConf::accept(), SpreadsheetGui::DlgBindSheet::DlgBindSheet(), SpreadsheetGui::DlgSheetConf::DlgSheetConf(), Spreadsheet::PropertySheet::getBinding(), Spreadsheet::PropertySheet::getPyValue(), Spreadsheet::Sheet::mergeCells(), Range(), and Spreadsheet::PropertySheet::setPathValue().
toCellString()
std::string App::Range::toCellString () const inline
End of range as a string
Definition at line 238 of file Range.h.
The documentation for this class was generated from the following files:
Range.h
Range.cpp