FreeCAD: ReenGui::FitBSplineCurveWidget Class Reference
ReenGui::FitBSplineCurveWidget Class Reference
#include <FitBSplineCurve.h>
Classes
class Private
Public Member Functions
FitBSplineCurveWidget (const App::DocumentObjectT &, QWidget *parent=nullptr)
~FitBSplineCurveWidget () override
bool accept ()
Protected Member Functions
void changeEvent (QEvent *e) override
Detailed Description
Definition at line 53 of file FitBSplineCurve.h.
Constructor & Destructor Documentation
FitBSplineCurveWidget()
FitBSplineCurveWidget::FitBSplineCurveWidget (const App::DocumentObjectT & obj, QWidget * parent = nullptr) explicit
Definition at line 48 of file FitBSplineCurve.cpp.
References draftgeoutils.intersections::connect(), ReenGui::FitBSplineCurveWidget::Private::obj, Init::parent, and ReenGui::FitBSplineCurveWidget::Private::ui.
~FitBSplineCurveWidget()
FitBSplineCurveWidget::~FitBSplineCurveWidget () override
Definition at line 63 of file FitBSplineCurve.cpp.
Member Function Documentation
accept()
bool FitBSplineCurveWidget::accept ()
Definition at line 84 of file FitBSplineCurve.cpp.
References Gui::Command::abortCommand(), SCL.SimpleDataTypes::e, and Path.Log::warning().
Referenced by ReenGui::TaskFitBSplineCurve::accept().
changeEvent()
void FitBSplineCurveWidget::changeEvent (QEvent * e) override protected
Definition at line 157 of file FitBSplineCurve.cpp.
References SCL.SimpleDataTypes::e, and ReenGui::FitBSplineCurveWidget::Private::ui.
The documentation for this class was generated from the following files:
FitBSplineCurve.h
FitBSplineCurve.cpp