FreeCAD: SketcherGui::CurveConverter Class Reference
SketcherGui::CurveConverter Class Reference final
#include <DrawSketchHandler.h>
Public Member Functions
CurveConverter ()
~CurveConverter () override
std::vector< Base::Vector2d > toVector2D (const Part::Geometry *geometry)
std::list< std::vector< Base::Vector2d > > toVector2DList (const std::vector< Part::Geometry * > &geometries)
Detailed Description
Class to convert Part::Geometry to Vector2d based collections
Definition at line 62 of file DrawSketchHandler.h.
Constructor & Destructor Documentation
CurveConverter()
CurveConverter::CurveConverter ()
Definition at line 167 of file DrawSketchHandler.cpp.
References Base::Subject< MsgType >::Attach(), Base::Console(), Base::ConsoleSingleton::DeveloperError(), SCL.SimpleDataTypes::e, App::GetApplication(), and App::Application::GetParameterGroupByPath().
~CurveConverter()
CurveConverter::~CurveConverter () override
Definition at line 184 of file DrawSketchHandler.cpp.
Member Function Documentation
toVector2D()
std::vector< Base::Vector2d > CurveConverter::toVector2D (const Part::Geometry * geometry)
Definition at line 193 of file DrawSketchHandler.cpp.
References Base::Persistence::getClassTypeId(), SplineSurface::i, updateLeaderLines::point, Path.Post.scripts.grbl_post::type, and exportCSG::vector2d().
toVector2DList()
std::list< std::vector< Base::Vector2d > > CurveConverter::toVector2DList (const std::vector< Part::Geometry * > & geometries)
Definition at line 231 of file DrawSketchHandler.cpp.
The documentation for this class was generated from the following files:
DrawSketchHandler.h
DrawSketchHandler.cpp