FreeCAD: Gui::Dialog::DlgCustomizeSpNavSettings Class Reference
Gui::Dialog::DlgCustomizeSpNavSettings Class Reference
#include <DlgCustomizeSpNavSettings.h>
Public Member Functions
DlgCustomizeSpNavSettings (QWidget *parent=nullptr)
~DlgCustomizeSpNavSettings () override
Public Member Functions inherited from Gui::Dialog::CustomizeActionPage
CustomizeActionPage (QWidget *parent=nullptr)
~CustomizeActionPage () override
Protected Slots
void onAddMacroAction (const QByteArray &) override
void onRemoveMacroAction (const QByteArray &) override
void onModifyMacroAction (const QByteArray &) override
Protected Slots inherited from Gui::Dialog::CustomizeActionPage
virtual void onAddMacroAction (const QByteArray &)=0
virtual void onRemoveMacroAction (const QByteArray &)=0
virtual void onModifyMacroAction (const QByteArray &)=0
Protected Member Functions
void setupConnections ()
void on_CBDominant_clicked ()
void on_CBFlipYZ_clicked ()
void on_CBRotations_clicked ()
void on_CBTranslations_clicked ()
void on_SliderGlobal_sliderReleased ()
void on_CBEnablePanLR_clicked ()
void on_CBReversePanLR_clicked ()
void on_SliderPanLR_sliderReleased ()
void on_CBEnablePanUD_clicked ()
void on_CBReversePanUD_clicked ()
void on_SliderPanUD_sliderReleased ()
void on_CBEnableZoom_clicked ()
void on_CBReverseZoom_clicked ()
void on_SliderZoom_sliderReleased ()
void on_CBEnableTilt_clicked ()
void on_CBReverseTilt_clicked ()
void on_SliderTilt_sliderReleased ()
void on_CBEnableRoll_clicked ()
void on_CBReverseRoll_clicked ()
void on_SliderRoll_sliderReleased ()
void on_CBEnableSpin_clicked ()
void on_CBReverseSpin_clicked ()
void on_SliderSpin_sliderReleased ()
void on_ButtonDefaultSpNavMotions_clicked ()
void on_ButtonCalibrate_clicked ()
void changeEvent (QEvent *e) override
Protected Member Functions inherited from Gui::Dialog::CustomizeActionPage
bool event (QEvent *e) override
Detailed Description
Definition at line 37 of file DlgCustomizeSpNavSettings.h.
Constructor & Destructor Documentation
DlgCustomizeSpNavSettings()
DlgCustomizeSpNavSettings::DlgCustomizeSpNavSettings (QWidget * parent = nullptr) explicit
Definition at line 33 of file DlgCustomizeSpNavSettings.cpp.
References src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui::app, and setupConnections().
~DlgCustomizeSpNavSettings()
DlgCustomizeSpNavSettings::~DlgCustomizeSpNavSettings () override default
Member Function Documentation
changeEvent()
void DlgCustomizeSpNavSettings::changeEvent (QEvent * e) override protected virtual
Implements Gui::Dialog::CustomizeActionPage.
Definition at line 124 of file DlgCustomizeSpNavSettings.cpp.
References SCL.SimpleDataTypes::e.
on_ButtonCalibrate_clicked()
void DlgCustomizeSpNavSettings::on_ButtonCalibrate_clicked () protected
Definition at line 151 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetBool().
Referenced by setupConnections().
on_ButtonDefaultSpNavMotions_clicked()
void DlgCustomizeSpNavSettings::on_ButtonDefaultSpNavMotions_clicked () protected
Definition at line 211 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::Clear().
Referenced by setupConnections().
on_CBDominant_clicked()
void DlgCustomizeSpNavSettings::on_CBDominant_clicked () protected
Definition at line 217 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetBool().
Referenced by setupConnections().
on_CBEnablePanLR_clicked()
void DlgCustomizeSpNavSettings::on_CBEnablePanLR_clicked () protected
Definition at line 264 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetBool().
Referenced by setupConnections().
on_CBEnablePanUD_clicked()
void DlgCustomizeSpNavSettings::on_CBEnablePanUD_clicked () protected
Definition at line 282 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetBool().
Referenced by setupConnections().
on_CBEnableRoll_clicked()
void DlgCustomizeSpNavSettings::on_CBEnableRoll_clicked () protected
Definition at line 336 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetBool().
Referenced by setupConnections().
on_CBEnableSpin_clicked()
void DlgCustomizeSpNavSettings::on_CBEnableSpin_clicked () protected
Definition at line 354 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetBool().
Referenced by setupConnections().
on_CBEnableTilt_clicked()
void DlgCustomizeSpNavSettings::on_CBEnableTilt_clicked () protected
Definition at line 318 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetBool().
Referenced by setupConnections().
on_CBEnableZoom_clicked()
void DlgCustomizeSpNavSettings::on_CBEnableZoom_clicked () protected
Definition at line 300 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetBool().
Referenced by setupConnections().
on_CBFlipYZ_clicked()
void DlgCustomizeSpNavSettings::on_CBFlipYZ_clicked () protected
Definition at line 222 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetBool().
Referenced by setupConnections().
on_CBReversePanLR_clicked()
void DlgCustomizeSpNavSettings::on_CBReversePanLR_clicked () protected
Definition at line 272 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetBool().
Referenced by setupConnections().
on_CBReversePanUD_clicked()
void DlgCustomizeSpNavSettings::on_CBReversePanUD_clicked () protected
Definition at line 290 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetBool().
Referenced by setupConnections().
on_CBReverseRoll_clicked()
void DlgCustomizeSpNavSettings::on_CBReverseRoll_clicked () protected
Definition at line 344 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetBool().
Referenced by setupConnections().
on_CBReverseSpin_clicked()
void DlgCustomizeSpNavSettings::on_CBReverseSpin_clicked () protected
Definition at line 362 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetBool().
Referenced by setupConnections().
on_CBReverseTilt_clicked()
void DlgCustomizeSpNavSettings::on_CBReverseTilt_clicked () protected
Definition at line 326 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetBool().
Referenced by setupConnections().
on_CBReverseZoom_clicked()
void DlgCustomizeSpNavSettings::on_CBReverseZoom_clicked () protected
Definition at line 308 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetBool().
Referenced by setupConnections().
on_CBRotations_clicked()
void DlgCustomizeSpNavSettings::on_CBRotations_clicked () protected
Definition at line 227 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetBool().
Referenced by setupConnections().
on_CBTranslations_clicked()
void DlgCustomizeSpNavSettings::on_CBTranslations_clicked () protected
Definition at line 242 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetBool().
Referenced by setupConnections().
on_SliderGlobal_sliderReleased()
void DlgCustomizeSpNavSettings::on_SliderGlobal_sliderReleased () protected
Definition at line 259 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetInt().
Referenced by setupConnections().
on_SliderPanLR_sliderReleased()
void DlgCustomizeSpNavSettings::on_SliderPanLR_sliderReleased () protected
Definition at line 277 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetInt().
Referenced by setupConnections().
on_SliderPanUD_sliderReleased()
void DlgCustomizeSpNavSettings::on_SliderPanUD_sliderReleased () protected
Definition at line 295 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetInt().
Referenced by setupConnections().
on_SliderRoll_sliderReleased()
void DlgCustomizeSpNavSettings::on_SliderRoll_sliderReleased () protected
Definition at line 349 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetInt().
Referenced by setupConnections().
on_SliderSpin_sliderReleased()
void DlgCustomizeSpNavSettings::on_SliderSpin_sliderReleased () protected
Definition at line 367 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetInt().
Referenced by setupConnections().
on_SliderTilt_sliderReleased()
void DlgCustomizeSpNavSettings::on_SliderTilt_sliderReleased () protected
Definition at line 331 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetInt().
Referenced by setupConnections().
on_SliderZoom_sliderReleased()
void DlgCustomizeSpNavSettings::on_SliderZoom_sliderReleased () protected
Definition at line 313 of file DlgCustomizeSpNavSettings.cpp.
References ParameterGrp::SetInt().
Referenced by setupConnections().
onAddMacroAction
void DlgCustomizeSpNavSettings::onAddMacroAction (const QByteArray & macroName) override protected slot
Definition at line 372 of file DlgCustomizeSpNavSettings.cpp.
onModifyMacroAction
void DlgCustomizeSpNavSettings::onModifyMacroAction (const QByteArray & macroName) override protected slot
Definition at line 384 of file DlgCustomizeSpNavSettings.cpp.
onRemoveMacroAction
void DlgCustomizeSpNavSettings::onRemoveMacroAction (const QByteArray & macroName) override protected slot
Definition at line 378 of file DlgCustomizeSpNavSettings.cpp.
setupConnections()
void DlgCustomizeSpNavSettings::setupConnections () protected
Definition at line 56 of file DlgCustomizeSpNavSettings.cpp.
References draftgeoutils.intersections::connect(), on_ButtonCalibrate_clicked(), on_ButtonDefaultSpNavMotions_clicked(), on_CBDominant_clicked(), on_CBEnablePanLR_clicked(), on_CBEnablePanUD_clicked(), on_CBEnableRoll_clicked(), on_CBEnableSpin_clicked(), on_CBEnableTilt_clicked(), on_CBEnableZoom_clicked(), on_CBFlipYZ_clicked(), on_CBReversePanLR_clicked(), on_CBReversePanUD_clicked(), on_CBReverseRoll_clicked(), on_CBReverseSpin_clicked(), on_CBReverseTilt_clicked(), on_CBReverseZoom_clicked(), on_CBRotations_clicked(), on_CBTranslations_clicked(), on_SliderGlobal_sliderReleased(), on_SliderPanLR_sliderReleased(), on_SliderPanUD_sliderReleased(), on_SliderRoll_sliderReleased(), on_SliderSpin_sliderReleased(), on_SliderTilt_sliderReleased(), and on_SliderZoom_sliderReleased().
Referenced by DlgCustomizeSpNavSettings().
The documentation for this class was generated from the following files:
DlgCustomizeSpNavSettings.h
DlgCustomizeSpNavSettings.cpp