FreeCAD: SandboxGui::DrawingPlane Class Reference
SandboxGui::DrawingPlane Class Reference
#include <Overlay.h>
Public Member Functions
DrawingPlane ()
virtual ~DrawingPlane ()
Public Member Functions inherited from Gui::BaseMouseSelection
BaseMouseSelection ()
~BaseMouseSelection () override=default
Public Member Functions inherited from Gui::AbstractMouseSelection
AbstractMouseSelection ()
virtual ~AbstractMouseSelection ()=default
virtual void terminate (bool abort=false)=0
implement this in derived classes
void grabMouseModel (Gui::View3DInventorViewer *)
void releaseMouseModel (bool abort=false)
const std::vector< SbVec2s > & getPositions () const
SelectionRole selectedRole () const
int handleEvent (const SoEvent *const ev, const SbViewportRegion &vp)
Protected Member Functions
void initialize ()
implement this in derived classes
void terminate ()
virtual int mouseButtonEvent (const SoMouseButtonEvent *const e, const QPoint &pos)
virtual int locationEvent (const SoLocation2Event *const e, const QPoint &pos)
virtual int keyboardEvent (const SoKeyboardEvent *const e)
void draw ()
drawing stuff
Protected Member Functions inherited from Gui::AbstractMouseSelection
Additional Inherited Members
Public Types inherited from Gui::AbstractMouseSelection
enum {
Continue =0, Restart =1, Finish =2, Cancel =3,
Ignore =4
}
Protected Attributes inherited from Gui::AbstractMouseSelection
Gui::View3DInventorViewer * _pcView3D {nullptr}
QCursor m_cPrevCursor
int m_iXold
int m_iYold
int m_iXnew
int m_iYnew
SelectionRole m_selectedRole
std::vector< SbVec2s > _clPoly
Detailed Description
Definition at line 54 of file Overlay.h.
Constructor & Destructor Documentation
DrawingPlane()
DrawingPlane::DrawingPlane ()
Definition at line 315 of file Overlay.cpp.
References SCL.SimpleDataTypes::b, toolbit-attributes::g, and buildPsets::p.
~DrawingPlane()
DrawingPlane::~DrawingPlane () virtual
Definition at line 328 of file Overlay.cpp.
References terminate().
Member Function Documentation
draw()
void DrawingPlane::draw () protected virtual
drawing stuff
Reimplemented from Gui::AbstractMouseSelection.
Definition at line 352 of file Overlay.cpp.
References Gui::AbstractMouseSelection::_pcView3D, SCL.SimpleDataTypes::f, SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getGLWidget(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), glDepthFunc, glDepthMask, glDisable, glEnable, glLineWidth, and glMatrixMode.
Referenced by locationEvent().
initialize()
void DrawingPlane::initialize () protected virtual
implement this in derived classes
Implements Gui::AbstractMouseSelection.
Definition at line 333 of file Overlay.cpp.
keyboardEvent()
int DrawingPlane::keyboardEvent (const SoKeyboardEvent *const e) protected virtual
Reimplemented from Gui::AbstractMouseSelection.
Definition at line 456 of file Overlay.cpp.
References Gui::AbstractMouseSelection::Continue.
locationEvent()
int DrawingPlane::locationEvent (const SoLocation2Event *const e, const QPoint & pos) protected virtual
Reimplemented from Gui::AbstractMouseSelection.
Definition at line 435 of file Overlay.cpp.
References KDL::abs(), Gui::AbstractMouseSelection::Continue, draw(), and RobotExample::pos.
mouseButtonEvent()
int DrawingPlane::mouseButtonEvent (const SoMouseButtonEvent *const e, const QPoint & pos) protected virtual
Reimplemented from Gui::AbstractMouseSelection.
Definition at line 400 of file Overlay.cpp.
References Gui::AbstractMouseSelection::Continue, SCL.SimpleDataTypes::e, Gui::AbstractMouseSelection::Finish, and RobotExample::pos.
terminate()
void DrawingPlane::terminate () protected
Definition at line 338 of file Overlay.cpp.
References Gui::AbstractMouseSelection::_pcView3D, a, SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), glClear, and glEnable.
Referenced by ~DrawingPlane().
The documentation for this class was generated from the following files:
Overlay.h
Overlay.cpp