FreeCAD: Gui::PropertyEditor::PropertyMatrixItem Class Reference
Gui::PropertyEditor::PropertyMatrixItem Class Reference
#include <PropertyItem.h>
Public Member Functions
QWidget * createEditor (QWidget *parent, const std::function< void()> &method) const override
void setEditorData (QWidget *editor, const QVariant &data) const override
QVariant editorData (QWidget *editor) const override
double getA11 () const
void setA11 (double A11)
double getA12 () const
void setA12 (double A12)
double getA13 () const
void setA13 (double A13)
double getA14 () const
void setA14 (double A14)
double getA21 () const
void setA21 (double A21)
double getA22 () const
void setA22 (double A22)
double getA23 () const
void setA23 (double A23)
double getA24 () const
void setA24 (double A24)
double getA31 () const
void setA31 (double A31)
double getA32 () const
void setA32 (double A32)
double getA33 () const
void setA33 (double A33)
double getA34 () const
void setA34 (double A34)
double getA41 () const
void setA41 (double A41)
double getA42 () const
void setA42 (double A42)
double getA43 () const
void setA43 (double A43)
double getA44 () const
void setA44 (double A44)
Public Member Functions inherited from Gui::PropertyEditor::PropertyItem
~PropertyItem () override
void setPropertyData (const std::vector< App::Property * > &)
void updateData ()
const std::vector< App::Property * > & getPropertyData () const
bool hasProperty (const App::Property *) const
virtual void assignProperty (const App::Property *)
bool removeProperty (const App::Property *)
App::Property * getFirstProperty ()
const App::Property * getFirstProperty () const
virtual bool isSeparator () const
QWidget * createExpressionEditor (QWidget *parent, const std::function< void()> &method) const
void setExpressionEditorData (QWidget *editor, const QVariant &data) const
QVariant expressionEditorData (QWidget *editor) const
PropertyEditorWidget * createPropertyEditorWidget (QWidget *parent) const
void bind (const App::Property &prop) override
void bind (const App::ObjectIdentifier &_path) override
virtual void propertyBound ()
QString expressionAsString () const
void setParent (PropertyItem *parent)
PropertyItem * parent () const
void appendChild (PropertyItem *child)
void insertChild (int, PropertyItem *child)
void moveChild (int from, int to)
void removeChildren (int from, int to)
PropertyItem::removeChildren Deletes the children in the range of [from, to].
PropertyItem * takeChild (int)
PropertyItem::takeChild Removes the child at index row but doesn't delete it.
void setReadOnly (bool)
bool isReadOnly () const
bool testStatus (App::Property::Status pos) const
void setDecimals (int)
int decimals () const
void setLinked (bool)
bool isLinked () const
bool isExpanded () const
void setExpanded (bool e)
PropertyItem * child (int row)
int childCount () const
int columnCount () const
QString propertyName () const
void setPropertyName (const QString &name, const QString &realName=QString())
void setPropertyValue (const QString &)
virtual QVariant data (int column, int role) const
bool setData (const QVariant &value)
Qt::ItemFlags flags (int column) const
virtual int row () const
void reset ()
bool hasAnyExpression () const
Public Member Functions inherited from Gui::ExpressionBinding
ExpressionBinding ()
virtual ~ExpressionBinding ()
bool isBound () const
void unbind ()
virtual bool apply (const std::string &propName)
virtual bool apply ()
bool hasExpression () const
bool autoApply () const
void setAutoApply (bool value)
Static Public Member Functions
static void * create (void)
static void init (void)
Static Public Member Functions inherited from Gui::PropertyEditor::PropertyItem
static void * create (void)
static void init (void)
Protected Member Functions
QVariant toString (const QVariant &) const override
QVariant value (const App::Property *) const override
void setValue (const QVariant &) override
PropertyMatrixItem ()
QVariant toolTip (const App::Property *) const override
Protected Member Functions inherited from Gui::PropertyEditor::PropertyItem
PropertyItem ()
void setPropertyValue (const std::string &value)
virtual QVariant displayName () const
virtual QVariant decoration (const QVariant &) const
virtual void initialize ()
void onChange () override
Protected Member Functions inherited from Gui::ExpressionBinding
const App::ObjectIdentifier & getPath () const
std::shared_ptr< App::Expression > getExpression () const
std::string getExpressionString (bool no_throw=true) const
std::string getEscapedExpressionString () const
bool assignToProperty (const std::string &propName, double)
virtual void setExpression (std::shared_ptr< App::Expression > expr)
void expressionChange (const App::ObjectIdentifier &id)
void objectDeleted (const App::DocumentObject &)
Properties
double A11
double A12
double A13
double A14
double A21
double A22
double A23
double A24
double A31
double A32
double A33
double A34
double A41
double A42
double A43
double A44
Additional Inherited Members
Protected Attributes inherited from Gui::PropertyEditor::PropertyItem
QString propName
QString displayText
std::vector< App::Property * > propertyItems
PropertyItem * parentItem
QList< PropertyItem * > childItems
bool readonly
int precision
bool linked
bool expanded
Protected Attributes inherited from Gui::ExpressionBinding
boost::signals2::scoped_connection expressionchanged
boost::signals2::scoped_connection objectdeleted
bool m_autoApply {false}
Detailed Description
Definition at line 689 of file PropertyItem.h.
Constructor & Destructor Documentation
PropertyMatrixItem()
PropertyMatrixItem::PropertyMatrixItem () protected
Definition at line 1884 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyFloatItem::create(), and Gui::PropertyEditor::PropertyItem::setParent().
Member Function Documentation
create()
void * Gui::PropertyEditor::PropertyMatrixItem::create (void) static
Definition at line 1882 of file PropertyItem.cpp.
Referenced by draftguitools.gui_labels.Label::action().
createEditor()
QWidget * PropertyMatrixItem::createEditor (QWidget * parent, const std::function< void()> & method) const override virtual
Creates the appropriate editor for this item and sets the editor to the value of overrideValue().
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 2041 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::parent().
editorData()
QVariant PropertyMatrixItem::editorData (QWidget * editor) const override virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 2077 of file PropertyItem.cpp.
References Path.Post.Utils::editor().
getA11()
double PropertyMatrixItem::getA11 () const
Definition at line 2084 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data().
Referenced by setA12(), setA13(), setA14(), setA21(), setA22(), setA23(), setA24(), setA31(), setA32(), setA33(), setA34(), setA41(), setA42(), setA43(), and setA44().
getA12()
double PropertyMatrixItem::getA12 () const
Definition at line 2097 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data().
Referenced by setA11(), setA13(), setA14(), setA21(), setA22(), setA23(), setA24(), setA31(), setA32(), setA33(), setA34(), setA41(), setA42(), setA43(), and setA44().
getA13()
double PropertyMatrixItem::getA13 () const
Definition at line 2110 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data().
Referenced by setA11(), setA12(), setA14(), setA21(), setA22(), setA23(), setA24(), setA31(), setA32(), setA33(), setA34(), setA41(), setA42(), setA43(), and setA44().
getA14()
double PropertyMatrixItem::getA14 () const
Definition at line 2123 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data().
Referenced by setA11(), setA12(), setA13(), setA21(), setA22(), setA23(), setA24(), setA31(), setA32(), setA33(), setA34(), setA41(), setA42(), setA43(), and setA44().
getA21()
double PropertyMatrixItem::getA21 () const
Definition at line 2136 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data().
Referenced by setA11(), setA12(), setA13(), setA14(), setA22(), setA23(), setA24(), setA31(), setA32(), setA33(), setA34(), setA41(), setA42(), setA43(), and setA44().
getA22()
double PropertyMatrixItem::getA22 () const
Definition at line 2149 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data().
Referenced by setA11(), setA12(), setA13(), setA14(), setA21(), setA23(), setA24(), setA31(), setA32(), setA33(), setA34(), setA41(), setA42(), setA43(), and setA44().
getA23()
double PropertyMatrixItem::getA23 () const
Definition at line 2162 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data().
Referenced by setA11(), setA12(), setA13(), setA14(), setA21(), setA22(), setA24(), setA31(), setA32(), setA33(), setA34(), setA41(), setA42(), setA43(), and setA44().
getA24()
double PropertyMatrixItem::getA24 () const
Definition at line 2175 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data().
Referenced by setA11(), setA12(), setA13(), setA14(), setA21(), setA22(), setA23(), setA31(), setA32(), setA33(), setA34(), setA41(), setA42(), setA43(), and setA44().
getA31()
double PropertyMatrixItem::getA31 () const
Definition at line 2188 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data().
Referenced by setA11(), setA12(), setA13(), setA14(), setA21(), setA22(), setA23(), setA24(), setA32(), setA33(), setA34(), setA41(), setA42(), setA43(), and setA44().
getA32()
double PropertyMatrixItem::getA32 () const
Definition at line 2201 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data().
Referenced by setA11(), setA12(), setA13(), setA14(), setA21(), setA22(), setA23(), setA24(), setA31(), setA33(), setA34(), setA41(), setA42(), setA43(), and setA44().
getA33()
double PropertyMatrixItem::getA33 () const
Definition at line 2214 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data().
Referenced by setA11(), setA12(), setA13(), setA14(), setA21(), setA22(), setA23(), setA24(), setA31(), setA32(), setA34(), setA41(), setA42(), setA43(), and setA44().
getA34()
double PropertyMatrixItem::getA34 () const
Definition at line 2227 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data().
Referenced by setA11(), setA12(), setA13(), setA14(), setA21(), setA22(), setA23(), setA24(), setA31(), setA32(), setA33(), setA41(), setA42(), setA43(), and setA44().
getA41()
double PropertyMatrixItem::getA41 () const
Definition at line 2240 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data().
Referenced by setA11(), setA12(), setA13(), setA14(), setA21(), setA22(), setA23(), setA24(), setA31(), setA32(), setA33(), setA34(), setA42(), setA43(), and setA44().
getA42()
double PropertyMatrixItem::getA42 () const
Definition at line 2253 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data().
Referenced by setA11(), setA12(), setA13(), setA14(), setA21(), setA22(), setA23(), setA24(), setA31(), setA32(), setA33(), setA34(), setA41(), setA43(), and setA44().
getA43()
double PropertyMatrixItem::getA43 () const
Definition at line 2266 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data().
Referenced by setA11(), setA12(), setA13(), setA14(), setA21(), setA22(), setA23(), setA24(), setA31(), setA32(), setA33(), setA34(), setA41(), setA42(), and setA44().
getA44()
double PropertyMatrixItem::getA44 () const
Definition at line 2279 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data().
Referenced by setA11(), setA12(), setA13(), setA14(), setA21(), setA22(), setA23(), setA24(), setA31(), setA32(), setA33(), setA34(), setA41(), setA42(), and setA43().
init()
void Gui::PropertyEditor::PropertyMatrixItem::init (void) static
Definition at line 1882 of file PropertyItem.cpp.
Referenced by DocumentObject.DocumentObject::onChanged().
setA11()
void PropertyMatrixItem::setA11 (double A11)
Definition at line 2089 of file PropertyItem.cpp.
References A11, getA12(), getA13(), getA14(), getA21(), getA22(), getA23(), getA24(), getA31(), getA32(), getA33(), getA34(), getA41(), getA42(), getA43(), getA44(), and Gui::PropertyEditor::PropertyItem::setData().
setA12()
void PropertyMatrixItem::setA12 (double A12)
Definition at line 2102 of file PropertyItem.cpp.
References A12, getA11(), getA13(), getA14(), getA21(), getA22(), getA23(), getA24(), getA31(), getA32(), getA33(), getA34(), getA41(), getA42(), getA43(), getA44(), and Gui::PropertyEditor::PropertyItem::setData().
setA13()
void PropertyMatrixItem::setA13 (double A13)
Definition at line 2115 of file PropertyItem.cpp.
References A13, getA11(), getA12(), getA14(), getA21(), getA22(), getA23(), getA24(), getA31(), getA32(), getA33(), getA34(), getA41(), getA42(), getA43(), getA44(), and Gui::PropertyEditor::PropertyItem::setData().
setA14()
void PropertyMatrixItem::setA14 (double A14)
Definition at line 2128 of file PropertyItem.cpp.
References A14, getA11(), getA12(), getA13(), getA21(), getA22(), getA23(), getA24(), getA31(), getA32(), getA33(), getA34(), getA41(), getA42(), getA43(), getA44(), and Gui::PropertyEditor::PropertyItem::setData().
setA21()
void PropertyMatrixItem::setA21 (double A21)
Definition at line 2141 of file PropertyItem.cpp.
References A21, getA11(), getA12(), getA13(), getA14(), getA22(), getA23(), getA24(), getA31(), getA32(), getA33(), getA34(), getA41(), getA42(), getA43(), getA44(), and Gui::PropertyEditor::PropertyItem::setData().
setA22()
void PropertyMatrixItem::setA22 (double A22)
Definition at line 2154 of file PropertyItem.cpp.
References A22, getA11(), getA12(), getA13(), getA14(), getA21(), getA23(), getA24(), getA31(), getA32(), getA33(), getA34(), getA41(), getA42(), getA43(), getA44(), and Gui::PropertyEditor::PropertyItem::setData().
setA23()
void PropertyMatrixItem::setA23 (double A23)
Definition at line 2167 of file PropertyItem.cpp.
References A23, getA11(), getA12(), getA13(), getA14(), getA21(), getA22(), getA24(), getA31(), getA32(), getA33(), getA34(), getA41(), getA42(), getA43(), getA44(), and Gui::PropertyEditor::PropertyItem::setData().
setA24()
void PropertyMatrixItem::setA24 (double A24)
Definition at line 2180 of file PropertyItem.cpp.
References A24, getA11(), getA12(), getA13(), getA14(), getA21(), getA22(), getA23(), getA31(), getA32(), getA33(), getA34(), getA41(), getA42(), getA43(), getA44(), and Gui::PropertyEditor::PropertyItem::setData().
setA31()
void PropertyMatrixItem::setA31 (double A31)
Definition at line 2193 of file PropertyItem.cpp.
References A31, getA11(), getA12(), getA13(), getA14(), getA21(), getA22(), getA23(), getA24(), getA32(), getA33(), getA34(), getA41(), getA42(), getA43(), getA44(), and Gui::PropertyEditor::PropertyItem::setData().
setA32()
void PropertyMatrixItem::setA32 (double A32)
Definition at line 2206 of file PropertyItem.cpp.
References A32, getA11(), getA12(), getA13(), getA14(), getA21(), getA22(), getA23(), getA24(), getA31(), getA33(), getA34(), getA41(), getA42(), getA43(), getA44(), and Gui::PropertyEditor::PropertyItem::setData().
setA33()
void PropertyMatrixItem::setA33 (double A33)
Definition at line 2219 of file PropertyItem.cpp.
References A33, getA11(), getA12(), getA13(), getA14(), getA21(), getA22(), getA23(), getA24(), getA31(), getA32(), getA34(), getA41(), getA42(), getA43(), getA44(), and Gui::PropertyEditor::PropertyItem::setData().
setA34()
void PropertyMatrixItem::setA34 (double A34)
Definition at line 2232 of file PropertyItem.cpp.
References A34, getA11(), getA12(), getA13(), getA14(), getA21(), getA22(), getA23(), getA24(), getA31(), getA32(), getA33(), getA41(), getA42(), getA43(), getA44(), and Gui::PropertyEditor::PropertyItem::setData().
setA41()
void PropertyMatrixItem::setA41 (double A41)
Definition at line 2245 of file PropertyItem.cpp.
References A41, getA11(), getA12(), getA13(), getA14(), getA21(), getA22(), getA23(), getA24(), getA31(), getA32(), getA33(), getA34(), getA42(), getA43(), getA44(), and Gui::PropertyEditor::PropertyItem::setData().
setA42()
void PropertyMatrixItem::setA42 (double A42)
Definition at line 2258 of file PropertyItem.cpp.
References A42, getA11(), getA12(), getA13(), getA14(), getA21(), getA22(), getA23(), getA24(), getA31(), getA32(), getA33(), getA34(), getA41(), getA43(), getA44(), and Gui::PropertyEditor::PropertyItem::setData().
setA43()
void PropertyMatrixItem::setA43 (double A43)
Definition at line 2271 of file PropertyItem.cpp.
References A43, getA11(), getA12(), getA13(), getA14(), getA21(), getA22(), getA23(), getA24(), getA31(), getA32(), getA33(), getA34(), getA41(), getA42(), getA44(), and Gui::PropertyEditor::PropertyItem::setData().
setA44()
void PropertyMatrixItem::setA44 (double A44)
Definition at line 2284 of file PropertyItem.cpp.
References A44, getA11(), getA12(), getA13(), getA14(), getA21(), getA22(), getA23(), getA24(), getA31(), getA32(), getA33(), getA34(), getA41(), getA42(), getA43(), and Gui::PropertyEditor::PropertyItem::setData().
setEditorData()
void PropertyMatrixItem::setEditorData (QWidget * editor, const QVariant & data) const override virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 2050 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), Path.Post.Utils::editor(), and value().
setValue()
void PropertyMatrixItem::setValue (const QVariant & value) override protected virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 2011 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), Gui::ExpressionBinding::hasExpression(), Gui::PropertyEditor::PropertyItem::setPropertyValue(), toolbit-attributes::val, and value().
toolTip()
QVariant PropertyMatrixItem::toolTip (const App::Property * prop) const override protected virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 2003 of file PropertyItem.cpp.
References getValue(), Base::BaseClass::isDerivedFrom(), and value().
toString()
QVariant PropertyMatrixItem::toString (const QVariant & prop) const override protected virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 1969 of file PropertyItem.cpp.
References value().
value()
QVariant PropertyMatrixItem::value (const App::Property * prop) const override protected virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 1995 of file PropertyItem.cpp.
References getValue(), and Base::BaseClass::isDerivedFrom().
Referenced by src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), setEditorData(), setValue(), toolTip(), and toString().
Property Documentation
A11
double Gui::PropertyEditor::PropertyMatrixItem::A11 read write
Definition at line 693 of file PropertyItem.h.
Referenced by setA11().
A12
double Gui::PropertyEditor::PropertyMatrixItem::A12 read write
Definition at line 694 of file PropertyItem.h.
Referenced by setA12().
A13
double Gui::PropertyEditor::PropertyMatrixItem::A13 read write
Definition at line 695 of file PropertyItem.h.
Referenced by setA13().
A14
double Gui::PropertyEditor::PropertyMatrixItem::A14 read write
Definition at line 696 of file PropertyItem.h.
Referenced by setA14().
A21
double Gui::PropertyEditor::PropertyMatrixItem::A21 read write
Definition at line 697 of file PropertyItem.h.
Referenced by setA21().
A22
double Gui::PropertyEditor::PropertyMatrixItem::A22 read write
Definition at line 698 of file PropertyItem.h.
Referenced by setA22().
A23
double Gui::PropertyEditor::PropertyMatrixItem::A23 read write
Definition at line 699 of file PropertyItem.h.
Referenced by setA23().
A24
double Gui::PropertyEditor::PropertyMatrixItem::A24 read write
Definition at line 700 of file PropertyItem.h.
Referenced by setA24().
A31
double Gui::PropertyEditor::PropertyMatrixItem::A31 read write
Definition at line 701 of file PropertyItem.h.
Referenced by setA31().
A32
double Gui::PropertyEditor::PropertyMatrixItem::A32 read write
Definition at line 702 of file PropertyItem.h.
Referenced by setA32().
A33
double Gui::PropertyEditor::PropertyMatrixItem::A33 read write
Definition at line 703 of file PropertyItem.h.
Referenced by setA33().
A34
double Gui::PropertyEditor::PropertyMatrixItem::A34 read write
Definition at line 704 of file PropertyItem.h.
Referenced by setA34().
A41
double Gui::PropertyEditor::PropertyMatrixItem::A41 read write
Definition at line 705 of file PropertyItem.h.
Referenced by setA41().
A42
double Gui::PropertyEditor::PropertyMatrixItem::A42 read write
Definition at line 706 of file PropertyItem.h.
Referenced by setA42().
A43
double Gui::PropertyEditor::PropertyMatrixItem::A43 read write
Definition at line 707 of file PropertyItem.h.
Referenced by setA43().
A44
double Gui::PropertyEditor::PropertyMatrixItem::A44 read write
Definition at line 708 of file PropertyItem.h.
Referenced by setA44().
The documentation for this class was generated from the following files:
PropertyItem.h
PropertyItem.cpp