FreeCAD: Gui::PropertyEditor::PropertyPlacementItem Class Reference
Gui::PropertyEditor::PropertyPlacementItem Class Reference
#include <PropertyItem.h>
Public Member Functions
QWidget * createEditor (QWidget *parent, const std::function< void()> &method) const override
void setEditorData (QWidget *editor, const QVariant &data) const override
QVariant editorData (QWidget *editor) const override
void propertyBound () override
void assignProperty (const App::Property *) override
Base::Quantity getAngle () const
void setAngle (Base::Quantity)
Base::Vector3d getAxis () const
void setAxis (const Base::Vector3d &)
Base::Vector3d getPosition () const
void setPosition (const Base::Vector3d &)
Public Member Functions inherited from Gui::PropertyEditor::PropertyItem
~PropertyItem () override
void setPropertyData (const std::vector< App::Property * > &)
void updateData ()
const std::vector< App::Property * > & getPropertyData () const
bool hasProperty (const App::Property *) const
bool removeProperty (const App::Property *)
App::Property * getFirstProperty ()
const App::Property * getFirstProperty () const
virtual bool isSeparator () const
QWidget * createExpressionEditor (QWidget *parent, const std::function< void()> &method) const
void setExpressionEditorData (QWidget *editor, const QVariant &data) const
QVariant expressionEditorData (QWidget *editor) const
PropertyEditorWidget * createPropertyEditorWidget (QWidget *parent) const
void bind (const App::Property &prop) override
void bind (const App::ObjectIdentifier &_path) override
QString expressionAsString () const
void setParent (PropertyItem *parent)
PropertyItem * parent () const
void appendChild (PropertyItem *child)
void insertChild (int, PropertyItem *child)
void moveChild (int from, int to)
void removeChildren (int from, int to)
PropertyItem::removeChildren Deletes the children in the range of [from, to].
PropertyItem * takeChild (int)
PropertyItem::takeChild Removes the child at index row but doesn't delete it.
void setReadOnly (bool)
bool isReadOnly () const
bool testStatus (App::Property::Status pos) const
void setDecimals (int)
int decimals () const
void setLinked (bool)
bool isLinked () const
bool isExpanded () const
void setExpanded (bool e)
PropertyItem * child (int row)
int childCount () const
int columnCount () const
QString propertyName () const
void setPropertyName (const QString &name, const QString &realName=QString())
void setPropertyValue (const QString &)
virtual QVariant data (int column, int role) const
bool setData (const QVariant &value)
Qt::ItemFlags flags (int column) const
virtual int row () const
void reset ()
bool hasAnyExpression () const
Public Member Functions inherited from Gui::ExpressionBinding
ExpressionBinding ()
virtual ~ExpressionBinding ()
bool isBound () const
void unbind ()
virtual bool apply (const std::string &propName)
virtual bool apply ()
bool hasExpression () const
bool autoApply () const
void setAutoApply (bool value)
Static Public Member Functions
static void * create (void)
static void init (void)
Static Public Member Functions inherited from Gui::PropertyEditor::PropertyItem
static void * create (void)
static void init (void)
Protected Member Functions
PropertyPlacementItem ()
~PropertyPlacementItem () override
QVariant toolTip (const App::Property *) const override
QVariant toString (const QVariant &) const override
QVariant value (const App::Property *) const override
void setValue (const QVariant &) override
Protected Member Functions inherited from Gui::PropertyEditor::PropertyItem
PropertyItem ()
void setPropertyValue (const std::string &value)
virtual QVariant displayName () const
virtual QVariant decoration (const QVariant &) const
virtual void initialize ()
void onChange () override
Protected Member Functions inherited from Gui::ExpressionBinding
const App::ObjectIdentifier & getPath () const
std::shared_ptr< App::Expression > getExpression () const
std::string getExpressionString (bool no_throw=true) const
std::string getEscapedExpressionString () const
bool assignToProperty (const std::string &propName, double)
virtual void setExpression (std::shared_ptr< App::Expression > expr)
void expressionChange (const App::ObjectIdentifier &id)
void objectDeleted (const App::DocumentObject &)
Properties
Base::Quantity Angle
Base::Vector3d Axis
Base::Vector3d Position
Additional Inherited Members
Protected Attributes inherited from Gui::PropertyEditor::PropertyItem
QString propName
QString displayText
std::vector< App::Property * > propertyItems
PropertyItem * parentItem
QList< PropertyItem * > childItems
bool readonly
int precision
bool linked
bool expanded
Protected Attributes inherited from Gui::ExpressionBinding
boost::signals2::scoped_connection expressionchanged
boost::signals2::scoped_connection objectdeleted
bool m_autoApply {false}
Detailed Description
Edit properties of placement type.
Author
Werner Mayer
Definition at line 862 of file PropertyItem.h.
Constructor & Destructor Documentation
PropertyPlacementItem()
PropertyPlacementItem::PropertyPlacementItem () protected
Definition at line 2673 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyUnitItem::create(), Gui::PropertyEditor::PropertyVectorItem::create(), Gui::PropertyEditor::PropertyVectorDistanceItem::create(), Arch::QT_TRANSLATE_NOOP, and Gui::PropertyEditor::PropertyItem::setParent().
~PropertyPlacementItem()
PropertyPlacementItem::~PropertyPlacementItem () override protected default
Member Function Documentation
assignProperty()
void PropertyPlacementItem::assignProperty (const App::Property * prop) override virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 2760 of file PropertyItem.cpp.
References Gui::PropertyEditor::RotationHelper::assignProperty(), Gui::PropertyEditor::PropertyItem::decimals(), getValue(), Base::BaseClass::isDerivedFrom(), Base::pow(), and value().
create()
void * Gui::PropertyEditor::PropertyPlacementItem::create (void) static
Definition at line 2671 of file PropertyItem.cpp.
Referenced by draftguitools.gui_labels.Label::action().
createEditor()
QWidget * PropertyPlacementItem::createEditor (QWidget * parent, const std::function< void()> & method) const override virtual
Creates the appropriate editor for this item and sets the editor to the value of overrideValue().
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 2890 of file PropertyItem.cpp.
References draftgeoutils.intersections::connect(), Gui::PropertyEditor::PropertyItem::getFirstProperty(), Gui::PropertyEditor::PropertyItem::isReadOnly(), Gui::PropertyEditor::PropertyItem::propertyName(), Gui::PropertyEditor::PropertyItem::readonly, and Gui::LabelButton::valueChanged().
editorData()
QVariant PropertyPlacementItem::editorData (QWidget * editor) const override virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 2911 of file PropertyItem.cpp.
References Path.Post.Utils::editor().
getAngle()
Base::Quantity PropertyPlacementItem::getAngle () const
Definition at line 2693 of file PropertyItem.cpp.
References Base::Unit::Angle, Gui::PropertyEditor::PropertyItem::data(), Gui::PropertyEditor::RotationHelper::getAngle(), src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::Quantity, toolbit-attributes::val, and value().
Referenced by Path.Dressup.Gui.Dogbone.Chord::getAngleXY(), draftguitools.gui_trackers.arcTracker::setEndPoint(), and draftguitools.gui_trackers.arcTracker::setStartPoint().
getAxis()
Base::Vector3d PropertyPlacementItem::getAxis () const
Definition at line 2718 of file PropertyItem.cpp.
References Gui::PropertyEditor::RotationHelper::getAxis().
getPosition()
Base::Vector3d PropertyPlacementItem::getPosition () const
Definition at line 2737 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), toolbit-attributes::val, and value().
init()
void Gui::PropertyEditor::PropertyPlacementItem::init (void) static
Definition at line 2671 of file PropertyItem.cpp.
Referenced by DocumentObject.DocumentObject::onChanged().
propertyBound()
void PropertyPlacementItem::propertyBound () override virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 2917 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::bind(), Gui::ExpressionBinding::getPath(), and Gui::ExpressionBinding::isBound().
setAngle()
void PropertyPlacementItem::setAngle (Base::Quantity angle)
Definition at line 2705 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), Gui::PropertyEditor::RotationHelper::setAngle(), setValue(), toolbit-attributes::val, and value().
setAxis()
void PropertyPlacementItem::setAxis (const Base::Vector3d & axis)
Definition at line 2723 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), Gui::PropertyEditor::RotationHelper::setAxis(), setValue(), toolbit-attributes::val, and value().
setEditorData()
void PropertyPlacementItem::setEditorData (QWidget * editor, const QVariant & data) const override virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 2905 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), and Path.Post.Utils::editor().
setPosition()
void PropertyPlacementItem::setPosition (const Base::Vector3d & pos)
Definition at line 2747 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), RobotExample::pos, Gui::PropertyEditor::RotationHelper::setChanged(), setValue(), toolbit-attributes::val, and value().
setValue()
void PropertyPlacementItem::setValue (const QVariant & value) override protected virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 2858 of file PropertyItem.cpp.
References Base::QuantityFormat::Default, Gui::PropertyEditor::RotationHelper::getValue(), Gui::PropertyEditor::RotationHelper::hasChangedAndReset(), Gui::ExpressionBinding::hasExpression(), RobotExample::pos, Gui::PropertyEditor::PropertyItem::setPropertyValue(), Path.Post.scripts.refactored_centroid_post::str, Base::UnitsApi::toNumber(), toolbit-attributes::val, value(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by setAngle(), setAxis(), and setPosition().
toolTip()
QVariant PropertyPlacementItem::toolTip (const App::Property * prop) const override protected virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 2808 of file PropertyItem.cpp.
References Base::Unit::Angle, Gui::PropertyEditor::PropertyItem::data(), Gui::PropertyEditor::PropertyItem::decimals(), Base::Quantity::getUserString(), getValue(), Base::BaseClass::isDerivedFrom(), Base::Unit::Length, buildPsets::p, RobotExample::pos, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
toString()
QVariant PropertyPlacementItem::toString (const QVariant & prop) const override protected virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 2835 of file PropertyItem.cpp.
References Base::Unit::Angle, Gui::PropertyEditor::PropertyItem::data(), Base::Quantity::getUserString(), Base::Unit::Length, buildPsets::p, RobotExample::pos, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
value()
QVariant PropertyPlacementItem::value (const App::Property * prop) const override protected virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 2771 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::child(), Gui::PropertyEditor::PropertyItem::expressionAsString(), getValue(), Gui::ExpressionBinding::hasExpression(), Gui::PropertyEditor::RotationHelper::isAxisInitialized(), Base::BaseClass::isDerivedFrom(), Gui::PropertyEditor::RotationHelper::setValue(), Path.Post.scripts.refactored_centroid_post::str, Base::toDegrees(), MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by assignProperty(), src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), getAngle(), getPosition(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), setAngle(), setAxis(), setPosition(), and setValue().
Property Documentation
Angle
Base::Quantity Gui::PropertyEditor::PropertyPlacementItem::Angle read write
Definition at line 866 of file PropertyItem.h.
Axis
Base::Vector3d Gui::PropertyEditor::PropertyPlacementItem::Axis read write
Definition at line 867 of file PropertyItem.h.
Position
Base::Vector3d Gui::PropertyEditor::PropertyPlacementItem::Position read write
Definition at line 868 of file PropertyItem.h.
The documentation for this class was generated from the following files:
PropertyItem.h
PropertyItem.cpp