FreeCAD: FemGui::DlgSettingsFemGmshImp Class Reference
FemGui::DlgSettingsFemGmshImp Class Reference
#include <DlgSettingsFemGmshImp.h>
Public Member Functions
DlgSettingsFemGmshImp (QWidget *parent=nullptr)
~DlgSettingsFemGmshImp () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Slots
void onfileNameChanged (QString FileName)
Protected Member Functions
void saveSettings () override
void loadSettings () override
void changeEvent (QEvent *e) override
void populateLogVerbosity ()
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
Definition at line 57 of file DlgSettingsFemGmshImp.h.
Constructor & Destructor Documentation
DlgSettingsFemGmshImp()
DlgSettingsFemGmshImp::DlgSettingsFemGmshImp (QWidget * parent = nullptr) explicit
Definition at line 38 of file DlgSettingsFemGmshImp.cpp.
References draftgeoutils.intersections::connect(), Gui::FileChooser::fileNameChanged(), and onfileNameChanged().
~DlgSettingsFemGmshImp()
DlgSettingsFemGmshImp::~DlgSettingsFemGmshImp () override default
Member Function Documentation
changeEvent()
void DlgSettingsFemGmshImp::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 77 of file DlgSettingsFemGmshImp.cpp.
References SCL.SimpleDataTypes::e.
loadSettings()
void DlgSettingsFemGmshImp::loadSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 60 of file DlgSettingsFemGmshImp.cpp.
References App::GetApplication(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), and populateLogVerbosity().
onfileNameChanged
void DlgSettingsFemGmshImp::onfileNameChanged (QString FileName) protected slot
Definition at line 87 of file DlgSettingsFemGmshImp.cpp.
Referenced by DlgSettingsFemGmshImp().
populateLogVerbosity()
void DlgSettingsFemGmshImp::populateLogVerbosity () protected
Definition at line 98 of file DlgSettingsFemGmshImp.cpp.
References App::GetApplication(), ParameterGrp::GetASCII(), App::Application::GetParameterGroupByPath(), and toolbit-attributes::val.
Referenced by loadSettings().
saveSettings()
void DlgSettingsFemGmshImp::saveSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 52 of file DlgSettingsFemGmshImp.cpp.
The documentation for this class was generated from the following files:
DlgSettingsFemGmshImp.h
DlgSettingsFemGmshImp.cpp