FreeCAD: TechDraw::CommandHelpers Namespace Reference
TechDraw::CommandHelpers Namespace Reference
Functions
TechDraw::DrawView * firstViewInSelection (Gui::Command *cmd)
find the first DrawView in the current selection for use as a base view (owner)
TechDraw::DrawView * firstNonSpreadsheetInSelection (Gui::Command *cmd)
find the first DrawView in the current selection for use as a base view (owner)
std::vector< std::string > getSelectedSubElements (Gui::Command *cmd, TechDraw::DrawViewPart *&dvp, std::string subType="Edge")
void getSelectedShapes (Gui::Command *cmd, std::vector< App::DocumentObject * > &shapes, std::vector< App::DocumentObject * > &xShapes, App::DocumentObject *faceObj, std::string &faceName)
std::pair< App::DocumentObject *, std::string > faceFromSelection ()
std::pair< Base::Vector3d, Base::Vector3d > viewDirection ()
Function Documentation
faceFromSelection()
std::pair< App::DocumentObject *, std::string > TechDraw::CommandHelpers::faceFromSelection ()
Definition at line 210 of file CommandHelpers.cpp.
References Base::Persistence::getClassTypeId(), TechDraw::DrawUtil::getGeomTypeFromName(), Gui::SelectionSingleton::getSelectionEx(), Gui::NoResolve, Path.Dressup.Utils::selection(), and Gui::Selection().
Referenced by viewDirection(), and viewDirection().
firstNonSpreadsheetInSelection()
TechDraw::DrawView * TechDraw::CommandHelpers::firstNonSpreadsheetInSelection (Gui::Command * cmd)
find the first DrawView in the current selection for use as a base view (owner)
Definition at line 74 of file CommandHelpers.cpp.
References Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), and Path.Dressup.Utils::selection().
firstViewInSelection()
TechDraw::DrawView * TechDraw::CommandHelpers::firstViewInSelection (Gui::Command * cmd)
find the first DrawView in the current selection for use as a base view (owner)
Definition at line 57 of file CommandHelpers.cpp.
References Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), and Path.Dressup.Utils::selection().
getSelectedShapes()
void TechDraw::CommandHelpers::getSelectedShapes (Gui::Command * cmd, std::vector< App::DocumentObject * > & shapes, std::vector< App::DocumentObject * > & xShapes, App::DocumentObject * faceObj, std::string & faceName)
extract the selected shapes and xShapes and determine if a face has been selected to define the projection direction
Definition at line 134 of file CommandHelpers.cpp.
References Base::Persistence::getClassTypeId(), Gui::Command::getDocument(), TechDraw::DrawUtil::getGeomTypeFromName(), Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), Gui::OldStyleElement, Init::parent, and Path.Dressup.Utils::selection().
getSelectedSubElements()
std::vector< std::string > TechDraw::CommandHelpers::getSelectedSubElements (Gui::Command * cmd, TechDraw::DrawViewPart *& dvp, std::string subType = "Edge")
Definition at line 93 of file CommandHelpers.cpp.
References Base::Persistence::getClassTypeId(), TechDraw::DrawUtil::getGeomTypeFromName(), Gui::getMainWindow(), Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), toolbit-attributes::s, Path.Dressup.Utils::selection(), and Path.Log::warning().
Referenced by exec2LineCenterLine(), execMidpoints(), and execQuadrants().
viewDirection()
std::pair< Base::Vector3d, Base::Vector3d > TechDraw::CommandHelpers::viewDirection ()
Definition at line 196 of file CommandHelpers.cpp.
References faceFromSelection(), and TechDraw::Preferences::useCameraDirection().
Referenced by MeasureGui::ViewProviderMeasureBase::getTextDirection().