FreeCAD: Gui::WidgetFactorySupplier Class Reference
Gui::WidgetFactorySupplier Class Reference
#include <WidgetFactory.h>
Static Public Member Functions
static WidgetFactorySupplier & instance ()
static void destruct ()
Friends
WidgetFactorySupplier & GetWidgetFactorySupplier ()
Detailed Description
The widget factory supplier class registers all kinds of preference pages and widgets.
Author
Werner Mayer
Definition at line 233 of file WidgetFactory.h.
Member Function Documentation
destruct()
void WidgetFactorySupplier::destruct () static
Definition at line 196 of file WidgetFactory.cpp.
References Gui::WidgetFactoryInst::destruct().
Referenced by Gui::Application::~Application().
instance()
WidgetFactorySupplier & WidgetFactorySupplier::instance () static
Definition at line 188 of file WidgetFactory.cpp.
Referenced by Gui::GetWidgetFactorySupplier().
Friends And Related Function Documentation
GetWidgetFactorySupplier
WidgetFactorySupplier& GetWidgetFactorySupplier () friend
Definition at line 246 of file WidgetFactory.h.
The documentation for this class was generated from the following files:
WidgetFactory.h
resource.cpp
WidgetFactory.cpp