FreeCAD: Path.Post.UtilsParse Namespace Reference
Path.Post.UtilsParse Namespace Reference
Functions
str check_for_an_adaptive_op (Values values, str command, CommandLine command_line, Tuple[bool, float, float] adaptive_op_variables)
bool check_for_drill_translate (Values values, Gcode gcode, str command, CommandLine command_line, PathParameters params, PathParameters motion_location, str drill_retract_mode)
None check_for_machine_specific_commands (Values values, Gcode gcode, str command)
None check_for_spindle_wait (Values values, Gcode gcode, str command, CommandLine command_line)
bool check_for_suppressed_commands (Values values, Gcode gcode, str command, CommandLine command_line)
None check_for_tlo (Values values, Gcode gcode, str command, PathParameters params)
bool check_for_tool_change (Values values, Gcode gcode, str command, CommandLine command_line)
str create_comment (Values values, str comment_string)
str default_axis_parameter (Values values, str command, str param, PathParameter param_value, PathParameters current_location)
str default_D_parameter (Values values, str command, str param, PathParameter param_value, PathParameters current_location)
str default_F_parameter (Values values, str command, str param, PathParameter param_value, PathParameters current_location)
str default_int_parameter (Values values, str command, str param, PathParameter param_value, PathParameters current_location)
str default_length_parameter (Values values, str command, str param, PathParameter param_value, PathParameters current_location)
str default_P_parameter (Values values, str command, str param, PathParameter param_value, PathParameters current_location)
str default_Q_parameter (Values values, str command, str param, PathParameter param_value, PathParameters current_location)
str default_rotary_parameter (Values values, str command, str param, PathParameter param_value, PathParameters current_location)
str default_S_parameter (Values values, str command, str param, PathParameter param_value, PathParameters current_location)
Tuple[bool, float, float] determine_adaptive_op (Values values, pathobj)
None drill_translate (Values values, Gcode gcode, str command, PathParameters params, PathParameters motion_location, str drill_retract_mode)
str format_command_line (Values values, CommandLine command_line)
str format_for_axis (Values values, number)
str format_for_feed (Values values, number)
str format_for_spindle (Values values, number)
None init_parameter_functions (Dict[str, ParameterFunction] parameter_functions)
str linenumber (Values values, Union[str, None] space=None)
None output_G73_G83_drill_moves (Values values, Gcode gcode, str command, PathParameters params, float drill_z, float retract_z, str F_feedrate, str G0_retract_z)
None output_G81_G82_drill_moves (Values values, Gcode gcode, str command, PathParameters params, float drill_z, str F_feedrate, str G0_retract_z)
None parse_a_group (Values values, Gcode gcode, pathobj)
None parse_a_path (Values values, Gcode gcode, pathobj)
None set_adaptive_op_speed (Values values, str command, CommandLine command_line, PathParameters params, Tuple[bool, float, float] adaptive_op_variables)
Variables
CommandLine
Gcode
PathParameter
PathParameters
Values
ParameterFunction
Function Documentation
check_for_an_adaptive_op()
str Path.Post.UtilsParse.check_for_an_adaptive_op (Values values, str command, CommandLine command_line, Tuple[bool, float, float] adaptive_op_variables)
Check to see if the current command is an adaptive op.
Definition at line 48 of file UtilsParse.py.
Referenced by Path.Post.UtilsParse.parse_a_path().
check_for_drill_translate()
bool Path.Post.UtilsParse.check_for_drill_translate (Values values, Gcode gcode, str command, CommandLine command_line, PathParameters params, PathParameters motion_location, str drill_retract_mode)
Check for drill commands to translate.
Definition at line 68 of file UtilsParse.py.
References Path.Post.UtilsParse.create_comment(), Path.Post.UtilsParse.drill_translate(), and Path.Post.UtilsParse.format_command_line().
Referenced by Path.Post.UtilsParse.parse_a_path().
check_for_machine_specific_commands()
None Path.Post.UtilsParse.check_for_machine_specific_commands (Values values, Gcode gcode, str command)
Check for comments containing machine-specific commands.
Definition at line 111 of file UtilsParse.py.
Referenced by Path.Post.UtilsParse.parse_a_path().
check_for_spindle_wait()
None Path.Post.UtilsParse.check_for_spindle_wait (Values values, Gcode gcode, str command, CommandLine command_line)
Check for commands that might need a wait command after them.
Definition at line 125 of file UtilsParse.py.
References Path.Post.UtilsParse.format_command_line().
Referenced by Path.Post.UtilsParse.parse_a_path().
check_for_suppressed_commands()
bool Path.Post.UtilsParse.check_for_suppressed_commands (Values values, Gcode gcode, str command, CommandLine command_line)
Check for commands that will be suppressed.
Definition at line 138 of file UtilsParse.py.
References Path.Post.UtilsParse.create_comment(), and Path.Post.UtilsParse.format_command_line().
Referenced by Path.Post.UtilsParse.parse_a_path().
check_for_tlo()
None Path.Post.UtilsParse.check_for_tlo (Values values, Gcode gcode, str command, PathParameters params)
Output a tool length command if USE_TLO is True.
Definition at line 160 of file UtilsParse.py.
References Path.Post.UtilsParse.format_command_line().
Referenced by Path.Post.UtilsParse.parse_a_path().
check_for_tool_change()
bool Path.Post.UtilsParse.check_for_tool_change (Values values, Gcode gcode, str command, CommandLine command_line)
Check for a tool change.
Definition at line 169 of file UtilsParse.py.
References Path.Post.UtilsParse.create_comment(), and Path.Post.UtilsParse.format_command_line().
Referenced by Path.Post.UtilsParse.parse_a_path().
create_comment()
str Path.Post.UtilsParse.create_comment (Values values, str comment_string)
Create a comment from a string using the correct comment symbol.
Definition at line 198 of file UtilsParse.py.
Referenced by Path.Post.UtilsParse.check_for_drill_translate(), Path.Post.UtilsParse.check_for_suppressed_commands(), Path.Post.UtilsParse.check_for_tool_change(), Path.Post.UtilsParse.drill_translate(), Path.Post.UtilsParse.parse_a_group(), and Path.Post.UtilsParse.parse_a_path().
default_axis_parameter()
str Path.Post.UtilsParse.default_axis_parameter (Values values, str command, str param, PathParameter param_value, PathParameters current_location)
Process an axis parameter.
Definition at line 205 of file UtilsParse.py.
References Path.Post.UtilsParse.format_for_axis().
default_D_parameter()
str Path.Post.UtilsParse.default_D_parameter (Values values, str command, str param, PathParameter param_value, PathParameters current_location)
Process the D parameter.
Definition at line 222 of file UtilsParse.py.
References Path.Post.UtilsParse.format_for_axis(), Path.Post.UtilsParse.format_for_spindle(), and Path.Post.scripts.refactored_centroid_post.str.
default_F_parameter()
str Path.Post.UtilsParse.default_F_parameter (Values values, str command, str param, PathParameter param_value, PathParameters current_location)
Process the F parameter.
Definition at line 240 of file UtilsParse.py.
References Path.Post.UtilsParse.format_for_feed().
default_int_parameter()
str Path.Post.UtilsParse.default_int_parameter (Values values, str command, str param, PathParameter param_value, PathParameters current_location)
Process a parameter that is treated like an integer.
Definition at line 266 of file UtilsParse.py.
References Path.Post.scripts.refactored_centroid_post.str.
default_length_parameter()
str Path.Post.UtilsParse.default_length_parameter (Values values, str command, str param, PathParameter param_value, PathParameters current_location)
Process a parameter that is treated like a length.
Definition at line 277 of file UtilsParse.py.
References Path.Post.UtilsParse.format_for_axis().
default_P_parameter()
str Path.Post.UtilsParse.default_P_parameter (Values values, str command, str param, PathParameter param_value, PathParameters current_location)
Process the P parameter.
Definition at line 288 of file UtilsParse.py.
References Path.Post.UtilsParse.format_for_axis(), and Path.Post.scripts.refactored_centroid_post.str.
default_Q_parameter()
str Path.Post.UtilsParse.default_Q_parameter (Values values, str command, str param, PathParameter param_value, PathParameters current_location)
Process the Q parameter.
Definition at line 306 of file UtilsParse.py.
References Path.Post.UtilsParse.format_for_axis(), and Path.Post.scripts.refactored_centroid_post.str.
default_rotary_parameter()
str Path.Post.UtilsParse.default_rotary_parameter (Values values, str command, str param, PathParameter param_value, PathParameters current_location)
Process a rotarty parameter (such as A, B, and C).
Definition at line 321 of file UtilsParse.py.
References Path.Post.scripts.refactored_centroid_post.str.
default_S_parameter()
str Path.Post.UtilsParse.default_S_parameter (Values values, str command, str param, PathParameter param_value, PathParameters current_location)
Process the S parameter.
Definition at line 340 of file UtilsParse.py.
References Path.Post.UtilsParse.format_for_spindle().
determine_adaptive_op()
Tuple[bool, float, float] Path.Post.UtilsParse.determine_adaptive_op (Values values, pathobj)
Determine if the pathobj contains an Adaptive operation.
Definition at line 351 of file UtilsParse.py.
Referenced by Path.Post.UtilsParse.parse_a_path().
drill_translate()
None Path.Post.UtilsParse.drill_translate (Values values, Gcode gcode, str command, PathParameters params, PathParameters motion_location, str drill_retract_mode)
Translate drill cycles.
Currently only cycles in XY are provided (G17).
XZ (G18) and YZ (G19) are not dealt with.
In other words only Z drilling can be translated.
Definition at line 375 of file UtilsParse.py.
References Path.Post.UtilsParse.create_comment(), Path.Post.UtilsParse.format_command_line(), Path.Post.UtilsParse.format_for_feed(), Path.Post.UtilsParse.output_G73_G83_drill_moves(), and Path.Post.UtilsParse.output_G81_G82_drill_moves().
Referenced by Path.Post.UtilsParse.check_for_drill_translate().
format_command_line()
str Path.Post.UtilsParse.format_command_line (Values values, CommandLine command_line)
Construct the command line for the final output.
Definition at line 455 of file UtilsParse.py.
Referenced by Path.Post.UtilsParse.check_for_drill_translate(), Path.Post.UtilsParse.check_for_spindle_wait(), Path.Post.UtilsParse.check_for_suppressed_commands(), Path.Post.UtilsParse.check_for_tlo(), Path.Post.UtilsParse.check_for_tool_change(), Path.Post.UtilsParse.drill_translate(), Path.Post.UtilsParse.output_G73_G83_drill_moves(), and Path.Post.UtilsParse.output_G81_G82_drill_moves().
format_for_axis()
str Path.Post.UtilsParse.format_for_axis (Values values, number)
Format a number using the precision for an axis value.
Definition at line 460 of file UtilsParse.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.UtilsParse.default_axis_parameter(), Path.Post.UtilsParse.default_D_parameter(), Path.Post.UtilsParse.default_length_parameter(), Path.Post.UtilsParse.default_P_parameter(), and Path.Post.UtilsParse.default_Q_parameter().
format_for_feed()
str Path.Post.UtilsParse.format_for_feed (Values values, number)
Format a number using the precision for a feed rate.
Definition at line 470 of file UtilsParse.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.UtilsParse.default_F_parameter(), Path.Post.UtilsParse.drill_translate(), and Path.Post.UtilsParse.set_adaptive_op_speed().
format_for_spindle()
str Path.Post.UtilsParse.format_for_spindle (Values values, number)
Format a number using the precision for a spindle speed.
Definition at line 480 of file UtilsParse.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.UtilsParse.default_D_parameter(), and Path.Post.UtilsParse.default_S_parameter().
init_parameter_functions()
None Path.Post.UtilsParse.init_parameter_functions (Dict[str, ParameterFunction] parameter_functions)
Initialize a list of parameter functions.
These functions are called in the UtilsParse.parse_a_path
function to return the appropriate parameter value.
Definition at line 485 of file UtilsParse.py.
linenumber()
str Path.Post.UtilsParse.linenumber (Values values, Union[str, None] space = None)
Output the next line number if appropriate.
Definition at line 527 of file UtilsParse.py.
References Path.Post.scripts.refactored_centroid_post.str.
output_G73_G83_drill_moves()
None Path.Post.UtilsParse.output_G73_G83_drill_moves (Values values, Gcode gcode, str command, PathParameters params, float drill_z, float retract_z, str F_feedrate, str G0_retract_z)
Output the movement G code for G73 and G83.
Definition at line 540 of file UtilsParse.py.
References Path.Post.UtilsParse.format_command_line().
Referenced by Path.Post.UtilsParse.drill_translate().
output_G81_G82_drill_moves()
None Path.Post.UtilsParse.output_G81_G82_drill_moves (Values values, Gcode gcode, str command, PathParameters params, float drill_z, str F_feedrate, str G0_retract_z)
Output the movement G code for G81 and G82.
Definition at line 602 of file UtilsParse.py.
References Path.Post.UtilsParse.format_command_line().
Referenced by Path.Post.UtilsParse.drill_translate().
parse_a_group()
None Path.Post.UtilsParse.parse_a_group (Values values, Gcode gcode, pathobj)
Parse a Group (compound, project, or simple path).
Definition at line 624 of file UtilsParse.py.
References Path.Post.UtilsParse.create_comment(), and Path.Post.UtilsParse.parse_a_path().
parse_a_path()
None Path.Post.UtilsParse.parse_a_path (Values values, Gcode gcode, pathobj)
Parse a simple Path.
Definition at line 645 of file UtilsParse.py.
References Path.Post.UtilsParse.check_for_an_adaptive_op(), Path.Post.UtilsParse.check_for_drill_translate(), Path.Post.UtilsParse.check_for_machine_specific_commands(), Path.Post.UtilsParse.check_for_spindle_wait(), Path.Post.UtilsParse.check_for_suppressed_commands(), Path.Post.UtilsParse.check_for_tlo(), Path.Post.UtilsParse.check_for_tool_change(), Path.Post.UtilsParse.create_comment(), Path.Post.UtilsParse.determine_adaptive_op(), and Path.Post.UtilsParse.set_adaptive_op_speed().
Referenced by Path.Post.UtilsParse.parse_a_group().
set_adaptive_op_speed()
None Path.Post.UtilsParse.set_adaptive_op_speed (Values values, str command, CommandLine command_line, PathParameters params, Tuple[bool, float, float] adaptive_op_variables)
Set the appropriate feed speed for an adaptive op.
Definition at line 730 of file UtilsParse.py.
References Path.Post.UtilsParse.format_for_feed().
Referenced by Path.Post.UtilsParse.parse_a_path().
Variable Documentation
CommandLine
Path.Post.UtilsParse.CommandLine
Definition at line 39 of file UtilsParse.py.
Gcode
Path.Post.UtilsParse.Gcode
Definition at line 40 of file UtilsParse.py.
ParameterFunction
Path.Post.UtilsParse.ParameterFunction
Definition at line 45 of file UtilsParse.py.
PathParameter
Path.Post.UtilsParse.PathParameter
Definition at line 41 of file UtilsParse.py.
PathParameters
Path.Post.UtilsParse.PathParameters
Definition at line 42 of file UtilsParse.py.
Values
Path.Post.UtilsParse.Values
Definition at line 43 of file UtilsParse.py.