FreeCAD: Gui::FileOptionsDialog Class Reference
Gui::FileOptionsDialog Class Reference
#include <FileDialog.h>
Public Types
enum ExtensionPosition { ExtensionRight = 0, ExtensionBottom = 1 }
Public Member Functions
FileOptionsDialog (QWidget *parent, Qt::WindowFlags)
~FileOptionsDialog () override
void accept () override
void setOptionsWidget (ExtensionPosition pos, QWidget *, bool show=false)
QWidget * getOptionsWidget () const
Protected Slots
void toggleExtension ()
Detailed Description
The FileOptionsDialog class provides an extensible file dialog with an additional widget either at the right or at the bottom, that can be shown or hidden with the 'Extended' button.
Author
Werner Mayer
Definition at line 102 of file FileDialog.h.
Member Enumeration Documentation
ExtensionPosition
enum Gui::FileOptionsDialog::ExtensionPosition
Enumerator
ExtensionRight
ExtensionBottom
Definition at line 107 of file FileDialog.h.
Constructor & Destructor Documentation
FileOptionsDialog()
FileOptionsDialog::FileOptionsDialog (QWidget * parent, Qt::WindowFlags fl)
Definition at line 448 of file FileDialog.cpp.
References draftgeoutils.intersections::connect(), Plot::grid(), and toggleExtension().
~FileOptionsDialog()
FileOptionsDialog::~FileOptionsDialog () override default
Member Function Documentation
accept()
void FileOptionsDialog::accept () override
Definition at line 470 of file FileDialog.cpp.
References create_qrc::ext, and src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
getOptionsWidget()
QWidget * FileOptionsDialog::getOptionsWidget () const
Definition at line 585 of file FileDialog.cpp.
setOptionsWidget()
void FileOptionsDialog::setOptionsWidget (FileOptionsDialog::ExtensionPosition pos, QWidget * w, bool show = false)
Definition at line 554 of file FileDialog.cpp.
References ExtensionBottom, ExtensionRight, Plot::grid(), RobotExample::pos, bimcommands.BimViews::show(), toggleExtension(), and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by StdViewScreenShot::activated(), and DrawingGui::DrawingView::printPdf().
toggleExtension
void FileOptionsDialog::toggleExtension () protected slot
Definition at line 529 of file FileDialog.cpp.
References ExtensionRight, and toolbit-attributes::s.
Referenced by FileOptionsDialog(), and setOptionsWidget().
The documentation for this class was generated from the following files:
FileDialog.h
FileDialog.cpp