FreeCAD: Gui::ToolHandler Class Reference
Gui::ToolHandler Class Reference
#include <ToolHandler.h>
Public Member Functions
ToolHandler ()=default
virtual ~ToolHandler ()=default
bool activate ()
virtual void deactivate ()
virtual void quit ()
void updateCursor ()
Protected Member Functions
virtual QString getCrosshairCursorSVGName () const
Icon helpers
Sets a cursor for 3D inventor view. pixmap as a cursor image in device independent pixels.
Parameters
autoScale - set this to false if pixmap already scaled for HiDPI
QCursor oldCursor
QCursor actCursor
QPixmap actCursorPixmap
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
void unsetCursor ()
void applyCursor ()
restitutes the DSH cached cursor (without any tail due to autoconstraints, ...)
void addCursorTail (std::vector< QPixmap > &pixmaps)
unsigned long getCrosshairColor ()
returns the color to be used for the crosshair (configurable as a parameter)
qreal devicePixelRatio ()
functions to set the cursor to a given svgName (to be migrated to NVI style)
View3DInventorViewer * getViewer ()
virtual QWidget * getCursorWidget ()
virtual void setWidgetCursor (QCursor cursor)
Detailed Description
Definition at line 60 of file ToolHandler.h.
Constructor & Destructor Documentation
ToolHandler()
Gui::ToolHandler::ToolHandler () default
~ToolHandler()
virtual Gui::ToolHandler::~ToolHandler () virtual default
Member Function Documentation
activate()
bool ToolHandler::activate ()
Definition at line 54 of file ToolHandler.cpp.
References getCursorWidget(), oldCursor, and updateCursor().
Referenced by TechDrawGui::TechDrawHandler::activate(), SketcherGui::DrawSketchHandler::activate(), ArchBuildingPart.ViewProviderBuildingPart::setEdit(), nativeifc.ifc_viewproviders.ifc_vp_object::setupContextMenu(), and ArchBuildingPart.ViewProviderBuildingPart::setupContextMenu().
addCursorTail()
void ToolHandler::addCursorTail (std::vector< QPixmap > & pixmaps) protected
Definition at line 180 of file ToolHandler.cpp.
References actCursor, actCursorPixmap, applyCursor(), and buildPsets::p.
Referenced by SketcherGui::DrawSketchHandler::renderSuggestConstraintsCursor().
applyCursor()
void ToolHandler::applyCursor () protected
restitutes the DSH cached cursor (without any tail due to autoconstraints, ...)
Definition at line 238 of file ToolHandler.cpp.
References actCursor.
Referenced by addCursorTail(), DrawSketchHandlerBSplineInsertKnot::mouseMove(), DrawSketchHandlerCopy::mouseMove(), DrawSketchHandlerRectangularArray::mouseMove(), DrawSketchHandlerBSplineInsertKnot::releaseButton(), and SketcherGui::DrawSketchHandler::seekAndRenderAutoConstraint().
deactivate()
void ToolHandler::deactivate () virtual
Reimplemented in SketcherGui::DrawSketchHandler, and TechDrawGui::TechDrawHandler.
Definition at line 71 of file ToolHandler.cpp.
References unsetCursor().
Referenced by CommandCreateBom.TaskAssemblyCreateBom::accept(), CommandInsertNewPart.TaskAssemblyNewPart::accept(), CommandCreateView.TaskAssemblyCreateView::accept(), CommandCreateSimulation.TaskAssemblyCreateSimulation::accept(), JointObject.TaskAssemblyCreateJoint::accept(), TechDrawGui::TechDrawHandler::deactivate(), SketcherGui::DrawSketchHandler::deactivate(), CommandCreateBom.TaskAssemblyCreateBom::reject(), CommandCreateView.TaskAssemblyCreateView::reject(), CommandCreateSimulation.TaskAssemblyCreateSimulation::reject(), and JointObject.TaskAssemblyCreateJoint::reject().
devicePixelRatio()
qreal ToolHandler::devicePixelRatio () protected
functions to set the cursor to a given svgName (to be migrated to NVI style)
Definition at line 253 of file ToolHandler.cpp.
References getCursorWidget().
Referenced by setCursor().
getCrosshairColor()
unsigned long ToolHandler::getCrosshairColor () protected
returns the color to be used for the crosshair (configurable as a parameter)
Definition at line 82 of file ToolHandler.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::GetUnsigned().
getCrosshairCursorSVGName()
QString ToolHandler::getCrosshairCursorSVGName () const protected virtual
Reimplemented in SketcherGui::DrawSketchControllableHandler< ControllerT >.
Definition at line 49 of file ToolHandler.cpp.
Referenced by updateCursor().
getCursorWidget()
QWidget * ToolHandler::getCursorWidget () protected virtual
Reimplemented in TechDrawGui::TechDrawHandler.
Definition at line 264 of file ToolHandler.cpp.
References getViewer(), and OfflineRenderingUtils::viewer().
Referenced by activate(), devicePixelRatio(), setCursor(), and setWidgetCursor().
getViewer()
Gui::View3DInventorViewer * ToolHandler::getViewer () protected
Definition at line 281 of file ToolHandler.cpp.
References Gui::MainWindow::activeWindow(), Base::BaseClass::getClassTypeId(), Gui::getMainWindow(), and Base::BaseClass::isDerivedFrom().
Referenced by getCursorWidget(), and SketcherGui::DrawSketchHandler::suggestedConstraintsPixmaps().
quit()
virtual void Gui::ToolHandler::quit () inline virtual
Reimplemented in DrawSketchHandlerDimension, SketcherGui::DrawSketchHandlerLineSet, SketcherGui::DrawSketchHandler, and TechDrawGui::TechDrawHandler.
Definition at line 69 of file ToolHandler.h.
setCursor()
void ToolHandler::setCursor (const QPixmap & pixmap, int x, int y, bool autoScale = true) protected
Definition at line 144 of file ToolHandler.cpp.
References actCursor, actCursorPixmap, devicePixelRatio(), getCursorWidget(), buildPsets::p, setWidgetCursor(), MovieTool::x, and MovieTool::y.
Referenced by draftguitools.gui_snapper.Snapper::off(), draftguitools.gui_snapper.Snapper::setSelectMode(), draftguitools.gui_snapper.Snapper::snapToCrossExtensions(), draftguitools.gui_snapper.Snapper::snapToExtensions(), draftguitools.gui_snapper.Snapper::snapToGrid(), draftguitools.gui_snapper.Snapper::snapToObject(), and draftguitools.gui_snapper.Snapper::snapToPolar().
setWidgetCursor()
void ToolHandler::setWidgetCursor (QCursor cursor) protected virtual
Reimplemented in TechDrawGui::TechDrawHandler.
Definition at line 273 of file ToolHandler.cpp.
References getCursorWidget().
Referenced by setCursor(), and unsetCursor().
unsetCursor()
void ToolHandler::unsetCursor () protected
Definition at line 248 of file ToolHandler.cpp.
References oldCursor, and setWidgetCursor().
Referenced by deactivate(), SketcherGui::DrawSketchDefaultHandler< ControllerT::HandlerType, ControllerT::SelectModeType, ControllerT::AutoConstraintInitialSize, ControllerT::ContructionMethodType >::pressRightButton(), DrawSketchHandlerCopy::releaseButton(), and DrawSketchHandlerRectangularArray::releaseButton().
updateCursor()
void ToolHandler::updateCursor ()
updates the actCursor with the icon by calling getCrosshairCursorSVGName(), enabling to set data member dependent icons (i.e. for different construction methods)
Definition at line 229 of file ToolHandler.cpp.
References getCrosshairCursorSVGName().
Referenced by activate().
Member Data Documentation
actCursor
QCursor Gui::ToolHandler::actCursor protected
Definition at line 139 of file ToolHandler.h.
Referenced by addCursorTail(), applyCursor(), and setCursor().
actCursorPixmap
QPixmap Gui::ToolHandler::actCursorPixmap protected
Definition at line 140 of file ToolHandler.h.
Referenced by addCursorTail(), and setCursor().
oldCursor
QCursor Gui::ToolHandler::oldCursor protected
Definition at line 138 of file ToolHandler.h.
Referenced by activate(), and unsetCursor().
The documentation for this class was generated from the following files:
ToolHandler.h
ToolHandler.cpp