FreeCAD: importers.exportIFC Namespace Reference
importers.exportIFC Namespace Reference
Functions
def getPreferences ()
def export (exportList, filename, colors=None, preferences=None)
def getPropertyData (key, value, preferences)
def isStandardCase (obj, ifctype)
def getIfcTypeFromObj (obj)
def exportIFC2X3Attributes (obj, kwargs, scale=0.001)
def exportIfcAttributes (obj, kwargs, scale=0.001)
def buildAddress (obj, ifcfile)
def createCurve (ifcfile, wire, scaling=1.0)
def createCurveWithArcs (ifcfile, wire, scaling=1.0)
def getEdgesAngle (edge1, edge2)
def checkRectangle (edges)
def getProfile (ifcfile, p)
def getRepresentation (ifcfile, context, obj, forcebrep=False, subtraction=False, tessellation=1, colors=None, preferences=None, forceclone=False, skipshape=False)
def getBrepFlag (obj, preferences)
def createProduct (ifcfile, obj, ifctype, uid, history, name, description, placement, representation, preferences)
def getUID (obj, preferences)
def getText (field, obj)
def getAxisContext (ifcfile)
def createAxis (ifcfile, obj, preferences, delta=None)
def writeJson (filename, ifcfile)
def create_annotation (anno, ifcfile, context, history, preferences)
Variables
PARAMS = FreeCAD.ParamGet("User parameter:BaseApp/Preferences/Mod/BIM")
dictionary translationtable
string ifctemplate
Function Documentation
buildAddress()
def importers.exportIFC.buildAddress (obj, ifcfile)
Definition at line 1704 of file exportIFC.py.
Referenced by importers.exportIFC.createProduct().
checkRectangle()
def importers.exportIFC.checkRectangle (edges)
checkRectangle(edges=[]): This function checks whether the given form is a rectangle
   or not. It will return True when edges form a rectangular shape or return False
   when edges do not form a rectangular shape.
Definition at line 1818 of file exportIFC.py.
References importers.exportIFC.getEdgesAngle().
Referenced by importers.exportIFC.getProfile().
create_annotation()
def importers.exportIFC.create_annotation (anno, ifcfile, context, history, preferences)
Creates an annotation object
Definition at line 2498 of file exportIFC.py.
References importers.exportIFC.createCurve().
Referenced by importers.exportIFC.export().
createAxis()
def importers.exportIFC.createAxis (ifcfile, obj, preferences, delta = None)
Creates an axis for a given wall, if applicable
Definition at line 2456 of file exportIFC.py.
References importers.exportIFC.createCurve(), and importers.exportIFC.getAxisContext().
Referenced by importers.exportIFC.getRepresentation().
createCurve()
def importers.exportIFC.createCurve (ifcfile, wire, scaling = 1.0)
creates an IfcIndexdPolyCurve from a wire
if possible, or defects to createCurveWithArcs
Definition at line 1718 of file exportIFC.py.
References importers.exportIFC.createCurveWithArcs().
Referenced by importers.exportIFC.create_annotation(), importers.exportIFC.createAxis(), importers.exportIFC.getProfile(), and importers.exportIFC.getRepresentation().
createCurveWithArcs()
def importers.exportIFC.createCurveWithArcs (ifcfile, wire, scaling = 1.0)
Definition at line 1736 of file exportIFC.py.
References DraftVecUtils.angle(), and DraftVecUtils.equals().
Referenced by importers.exportIFC.createCurve().
createProduct()
def importers.exportIFC.createProduct (ifcfile, obj, ifctype, uid, history, name, description, placement, representation, preferences)
creates a product in the given IFC file
Definition at line 2371 of file exportIFC.py.
References importers.exportIFC.buildAddress(), importers.importIFCHelper.dd2dms(), importers.exportIFC.exportIFC2X3Attributes(), and importers.exportIFC.exportIfcAttributes().
Referenced by importers.exportIFC.export().
export()
def importers.exportIFC.export (exportList, filename, colors = None, preferences = None)
Export the selected objects to IFC format.
Parameters
----------
colors:
    It defaults to `None`.
    It is an optional dictionary of `objName:shapeColorTuple`
    or `objName:diffuseColorList` elements to be used in non-GUI mode
    if you want to be able to export colors.
Definition at line 184 of file exportIFC.py.
References Path.Post.scripts.uccnc_post.append(), importers.exportIFC.create_annotation(), importers.exportIFC.createProduct(), importers.exportIFC.getBrepFlag(), Arch.getDocumentMaterials(), importers.exportIFC.getIfcTypeFromObj(), importers.exportIFC.getPreferences(), importers.exportIFC.getPropertyData(), importers.exportIFC.getRepresentation(), importers.exportIFC.getText(), importers.exportIFC.getUID(), importers.exportIFC.isStandardCase(), Path.Post.scripts.refactored_centroid_post.str, Path.Post.scripts.grbl_post.type, and importers.exportIFC.writeJson().
exportIFC2X3Attributes()
def importers.exportIFC.exportIFC2X3Attributes (obj, kwargs, scale = 0.001)
Definition at line 1654 of file exportIFC.py.
References importers.exportIFC.getIfcTypeFromObj().
Referenced by importers.exportIFC.createProduct().
exportIfcAttributes()
def importers.exportIFC.exportIfcAttributes (obj, kwargs, scale = 0.001)
Definition at line 1687 of file exportIFC.py.
References importers.exportIFC.getIfcTypeFromObj().
Referenced by importers.exportIFC.createProduct().
getAxisContext()
def importers.exportIFC.getAxisContext (ifcfile)
gets or creates an axis context
Definition at line 2441 of file exportIFC.py.
Referenced by importers.exportIFC.createAxis().
getBrepFlag()
def importers.exportIFC.getBrepFlag (obj, preferences)
returns True if the object must be exported as BREP
Definition at line 2359 of file exportIFC.py.
Referenced by importers.exportIFC.export().
getEdgesAngle()
def importers.exportIFC.getEdgesAngle (edge1, edge2)
getEdgesAngle(edge1, edge2): returns a angle between two edges.
Definition at line 1808 of file exportIFC.py.
References SurfaceTests.TestBlendCurve.vec.
Referenced by importers.exportIFC.checkRectangle().
getIfcTypeFromObj()
def importers.exportIFC.getIfcTypeFromObj (obj)
Definition at line 1623 of file exportIFC.py.
Referenced by importers.exportIFC.export(), importers.exportIFC.exportIFC2X3Attributes(), and importers.exportIFC.exportIfcAttributes().
getPreferences()
def importers.exportIFC.getPreferences ()
Retrieve the IFC preferences available in import and export.
Definition at line 107 of file exportIFC.py.
Referenced by importers.exportIFC.export().
getProfile()
def importers.exportIFC.getProfile (ifcfile, p)
returns an IFC profile definition from a shape
Definition at line 1837 of file exportIFC.py.
References importers.exportIFC.checkRectangle(), importers.exportIFC.createCurve(), and SurfaceTests.TestBlendCurve.vec.
Referenced by importers.exportIFC.getRepresentation().
getPropertyData()
def importers.exportIFC.getPropertyData (key, value, preferences)
Definition at line 1556 of file exportIFC.py.
Referenced by Gui::PropertyEditor::PropertyItem.createPropertyEditorWidget(), importers.exportIFC.export(), and SketcherGui::PropertyConstraintListItem.initialize().
getRepresentation()
def importers.exportIFC.getRepresentation (ifcfile, context, obj, forcebrep = False, subtraction = False, tessellation = 1, colors = None, preferences = None, forceclone = False, skipshape = False)
returns an IfcShapeRepresentation object or None. forceclone can be False (does nothing),
"store" or True (stores the object as clone base) or a Vector (creates a clone)
Definition at line 1909 of file exportIFC.py.
References DraftVecUtils.angle(), importers.exportIFC.createAxis(), importers.exportIFC.createCurve(), importers.exportIFC.getProfile(), DraftVecUtils.isNull(), DraftVecUtils.neg(), ArchComponent.Component.rebase(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by importers.exportIFC.export().
getText()
def importers.exportIFC.getText (field, obj)
Returns the value of a text property of an object
Definition at line 2430 of file exportIFC.py.
Referenced by Gui::Dialog::ParameterText.changeValue(), Gui::PropertyEditor::PropertyEditor.contextMenuEvent(), SpreadsheetGui::DlgBindSheet.DlgBindSheet(), importers.exportIFC.export(), Spreadsheet::Cell.getStringContent(), Gui::Dialog::ParameterValue.onCreateBoolItem(), Gui::Dialog::ParameterValue.onCreateFloatItem(), Gui::Dialog::ParameterValue.onCreateIntItem(), Gui::Dialog::ParameterGroup.onCreateSubgroup(), Gui::Dialog::ParameterValue.onCreateTextItem(), Gui::Dialog::ParameterValue.onCreateUIntItem(), Gui::Dialog::DlgCustomToolbars.onNewButtonClicked(), Gui::Dialog::DlgCustomToolbars.onRenameButtonClicked(), and MRichTextEdit.textLink().
getUID()
def importers.exportIFC.getUID (obj, preferences)
gets or creates an UUID for an object
Definition at line 2405 of file exportIFC.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by importers.exportIFC.export().
isStandardCase()
def importers.exportIFC.isStandardCase (obj, ifctype)
Definition at line 1614 of file exportIFC.py.
Referenced by importers.exportIFC.export().
writeJson()
def importers.exportIFC.writeJson (filename, ifcfile)
writes an .ifcjson file
Definition at line 2477 of file exportIFC.py.
Referenced by importers.exportIFC.export().
Variable Documentation
ifctemplate
string importers.exportIFC.ifctemplate
Initial value:
 =  """ISO-10303-21;
 HEADER;
 FILE_DESCRIPTION(('ViewDefinition [CoordinationView]'),'2;1');
 FILE_NAME('$filename','$timestamp',('$owner','$email'),('$company'),'IfcOpenShell','IfcOpenShell','');
 FILE_SCHEMA(('$ifcschema'));
 ENDSEC;
 DATA;
 #1=IFCPERSON($,$,'$owner',$,$,$,$,$);
 #2=IFCORGANIZATION($,'$company',$,$,$);
 #3=IFCPERSONANDORGANIZATION(#1,#2,$);
 #4=IFCAPPLICATION(#2,'$version','FreeCAD','118df2cf_ed21_438e_a41');
 #5=IFCOWNERHISTORY(#3,#4,$,.ADDED.,$now,#3,#4,$now);
 #6=IFCDIRECTION((1.,0.,0.));
 #7=IFCDIRECTION((0.,0.,1.));
 #8=IFCCARTESIANPOINT((0.,0.,0.));
 #9=IFCAXIS2PLACEMENT3D(#8,#7,#6);
 #10=IFCDIRECTION((0.,1.,0.));
 #12=IFCDIMENSIONALEXPONENTS(0,0,0,0,0,0,0);
 #13=IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);
 #14=IFCSIUNIT(*,.AREAUNIT.,$,.SQUARE_METRE.);
 #15=IFCSIUNIT(*,.VOLUMEUNIT.,$,.CUBIC_METRE.);
 #16=IFCSIUNIT(*,.PLANEANGLEUNIT.,$,.RADIAN.);
 #17=IFCMEASUREWITHUNIT(IFCPLANEANGLEMEASURE(0.017453292519943295),#16);
 #18=IFCCONVERSIONBASEDUNIT(#12,.PLANEANGLEUNIT.,'DEGREE',#17);
 ENDSEC;
 END-ISO-10303-21;
 """
Definition at line 78 of file exportIFC.py.
PARAMS
importers.exportIFC.PARAMS = FreeCAD.ParamGet("User parameter:BaseApp/Preferences/Mod/BIM")
Definition at line 57 of file exportIFC.py.
translationtable
dictionary importers.exportIFC.translationtable
Initial value:
 =  {
     "Foundation": "Footing",
     "Floor": "BuildingStorey",
     "Rebar": "ReinforcingBar",
     "HydroEquipment": "SanitaryTerminal",
     "ElectricEquipment": "ElectricAppliance",
     "Furniture": "FurnishingElement",
     "Stair Flight": "StairFlight",
     "Curtain Wall": "CurtainWall",
     "Pipe Segment": "PipeSegment",
     "Pipe Fitting": "PipeFitting",
     "VisGroup": "Group",
     "Undefined": "BuildingElementProxy",
 }
Definition at line 61 of file exportIFC.py.