FreeCAD: SketcherGui::SketcherRegularPolygonDialog Class Reference
SketcherGui::SketcherRegularPolygonDialog Class Reference
#include <SketcherRegularPolygonDialog.h>
Public Member Functions
SketcherRegularPolygonDialog ()
~SketcherRegularPolygonDialog () override
void accept () override
Public Attributes
int sides
Protected Member Functions
void updateValues ()
Detailed Description
Definition at line 53 of file SketcherRegularPolygonDialog.h.
Constructor & Destructor Documentation
SketcherRegularPolygonDialog()
SketcherRegularPolygonDialog::SketcherRegularPolygonDialog ()
Definition at line 36 of file SketcherRegularPolygonDialog.cpp.
References updateValues().
~SketcherRegularPolygonDialog()
SketcherRegularPolygonDialog::~SketcherRegularPolygonDialog () override
Definition at line 47 of file SketcherRegularPolygonDialog.cpp.
Member Function Documentation
accept()
void SketcherRegularPolygonDialog::accept () override
Definition at line 50 of file SketcherRegularPolygonDialog.cpp.
References updateValues().
updateValues()
void SketcherRegularPolygonDialog::updateValues () protected
Definition at line 59 of file SketcherRegularPolygonDialog.cpp.
References sides.
Referenced by accept(), and SketcherRegularPolygonDialog().
Member Data Documentation
sides
int SketcherGui::SketcherRegularPolygonDialog::sides
Definition at line 63 of file SketcherRegularPolygonDialog.h.
Referenced by updateValues().
The documentation for this class was generated from the following files:
SketcherRegularPolygonDialog.h
SketcherRegularPolygonDialog.cpp