FreeCAD: MeshCore::MeshIntersection Class Reference
MeshCore::MeshIntersection Class Reference
#include <SetOperations.h>
Classes
struct Pair
struct Triple
struct Tuple
Public Member Functions
MeshIntersection (const MeshKernel &m1, const MeshKernel &m2, float dist)
bool hasIntersection () const
void getIntersection (std::list< Tuple > &) const
void connectLines (bool onlyclosed, const std::list< Tuple > &, std::list< std::list< Triple >> &)
Detailed Description
Determine the intersections between two meshes.
Definition at line 220 of file SetOperations.h.
Constructor & Destructor Documentation
MeshIntersection()
MeshCore::MeshIntersection::MeshIntersection (const MeshKernel & m1, const MeshKernel & m2, float dist) inline
Definition at line 239 of file SetOperations.h.
Member Function Documentation
connectLines()
void MeshIntersection::connectLines (bool onlyclosed, const std::list< Tuple > & , std::list< std::list< Triple >> &)
From an unsorted list of intersection points make a list of sorted intersection points. If parameter onlyclosed is set to true then only closed intersection curves are taken and all other curves are filtered out.
Definition at line 733 of file SetOperations.cpp.
References Base::DistanceP2(), MeshCore::MeshIntersection::Triple::f1, MeshCore::MeshIntersection::Triple::f2, and MeshCore::MeshIntersection::Triple::p.
Referenced by Mesh::MeshObject::section().
getIntersection()
void MeshIntersection::getIntersection (std::list< Tuple > &) const
Definition at line 628 of file SetOperations.cpp.
References MeshCore::MeshFacetIterator::Begin(), MeshCore::MeshIntersection::Tuple::f1, MeshCore::MeshIntersection::Tuple::f2, MeshCore::MeshKernel::GetFacets(), MeshCore::MeshGrid::Inside(), MeshCore::MeshGeomFacet::IntersectWithFacet(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), Base::SequencerLauncher::next(), MeshCore::MeshIntersection::Tuple::p1, MeshCore::MeshIntersection::Tuple::p2, and MeshCore::MeshFacetIterator::Set().
Referenced by Mesh::MeshObject::section().
hasIntersection()
bool MeshIntersection::hasIntersection () const
Definition at line 617 of file SetOperations.cpp.
References MeshCore::MeshKernel::GetBoundBox().
The documentation for this class was generated from the following files:
SetOperations.h
SetOperations.cpp