FreeCAD: TechDrawGui::QGIViewSection Class Reference
TechDrawGui::QGIViewSection Class Reference
#include <QGIViewSection.h>
Public Types
enum { Type = QGraphicsItem::UserType + 108 }
Public Types inherited from TechDrawGui::QGIViewPart
enum { Type = QGraphicsItem::UserType + 102 }
Public Types inherited from TechDrawGui::QGIView
enum { Type = QGraphicsItem::UserType + 101 }
Public Member Functions
QGIViewSection ()=default
~QGIViewSection () override=default
void draw () override
void updateView (bool update=false) override
int type () const override
Public Member Functions inherited from TechDrawGui::QGIViewPart
QGIViewPart ()
~QGIViewPart () override
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
bool sceneEventFilter (QGraphicsItem *watched, QEvent *event) override
void toggleCache (bool state) override
void toggleCosmeticLines (bool state)
void setViewPartFeature (TechDraw::DrawViewPart *obj)
void tidy ()
QRectF boundingRect () const override
virtual void drawAllFaces ()
virtual void drawAllEdges ()
virtual void drawAllVertexes ()
bool showThisEdge (TechDraw::BaseGeomPtr geom)
virtual void drawAllSectionLines ()
virtual void drawSectionLine (TechDraw::DrawViewSection *s, bool b)
virtual void drawComplexSectionLine (TechDraw::DrawViewSection *viewSection, bool b)
virtual void drawCenterLines (bool b)
virtual void drawAllHighlights ()
virtual void drawHighlight (TechDraw::DrawViewDetail *viewDetail, bool b)
virtual void drawMatting ()
virtual void drawBreakLines ()
if this is a broken view, draw the break lines.
void rotateView () override
virtual void highlightMoved (QGIHighlight *highlight, QPointF newPos)
bool getGroupSelection () override
void setGroupSelection (bool isSelected) override
void setGroupSelection (bool isSelected, const std::vector< std::string > &subNames) override
virtual QGraphicsItem * getQGISubItemByName (const std::string &subName) const
virtual bool removeSelectedCosmetic () const
Public Member Functions inherited from TechDrawGui::QGIView
QGIView ()
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
const char * getViewName () const
const std::string getViewNameAsString () const
void setViewFeature (TechDraw::DrawView *obj)
TechDraw::DrawView * getViewObject () const
MDIViewPage * getMDIViewPage () const
double getScale ()
void hideFrame ()
virtual bool getFrameState ()
virtual void drawBorder ()
virtual void isVisible (bool state)
virtual bool isVisible ()
virtual void drawCaption ()
void makeMark (double xPos, double yPos, QColor color=Qt::red)
void makeMark (Base::Vector3d pos, QColor color=Qt::red)
void makeMark (QPointF pos, QColor color=Qt::red)
void setPosition (qreal xPos, qreal yPos)
qreal getY ()
bool isInnerView () const
void isInnerView (bool state)
QGIViewClip * getClipGroup ()
bool isSnapping ()
void snapPosition (QPointF &position)
void snapSectionView (const TechDraw::DrawViewSection *sectionView, QPointF &newPosition)
Base::Vector3d projItemPagePos (TechDraw::DrawViewPart *item)
void alignTo (QGraphicsItem *, const QString &alignment)
QColor prefNormalColor ()
QColor getNormalColor ()
void setNormalColor (QColor color)
QColor getPreColor ()
QColor getSelectColor ()
QColor getCurrentColor ()
void setCurrentColor (QColor color)
QColor getSettingColor ()
void setSettingColor (QColor color)
virtual void setStack (int z)
virtual void setStackFromVP ()
QFont getFont ()
void setFont (QFont font)
virtual void removeChild (QGIView *child)
virtual void addArbitraryItem (QGraphicsItem *qgi)
virtual void switchParentItem (QGIView *targetParent)
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
Protected Member Functions
void drawSectionFace ()
Protected Member Functions inherited from TechDrawGui::QGIViewPart
QPainterPath drawPainterPath (TechDraw::BaseGeomPtr baseGeom) const
void drawViewPart ()
QGIFace * drawFace (TechDraw::FacePtr f, int idx)
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
TechDraw::DrawHatch * faceIsHatched (int i, std::vector< TechDraw::DrawHatch * > hatchObjs) const
TechDraw::DrawGeomHatch * faceIsGeomHatched (int i, std::vector< TechDraw::DrawGeomHatch * > geomObjs) const
void dumpPath (const char *text, QPainterPath path)
void removePrimitives ()
Remove all existing QGIPrimPath items(Vertex, Edge, Face)
void removeDecorations ()
Remove all existing QGIDecoration items(SectionLine, SectionMark, ...)
bool prefFaceEdges ()
bool prefPrintCenters ()
App::Color prefBreaklineColor ()
bool formatGeomFromCosmetic (std::string cTag, QGIEdge *item)
bool formatGeomFromCenterLine (std::string cTag, QGIEdge *item)
bool showCenterMarks ()
bool showVertices ()
Protected Member Functions inherited from TechDrawGui::QGIView
QGIView * getQGIVByName (std::string name)
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QRectF customChildrenBoundingRect () const
void dumpRect (const char *text, QRectF rect)
Base::Reference< ParameterGrp > getParmGroupCol ()
Additional Inherited Members
Static Public Member Functions inherited from TechDrawGui::QGIViewPart
static QPainterPath geomToPainterPath (TechDraw::BaseGeomPtr baseGeom, double rotation=0.0)
static void pathArcSegment (QPainterPath &path, double xc, double yc, double th0, double th1, double rx, double ry, double xAxisRotation)
Helper for pathArc()
static void pathArc (QPainterPath &path, double rx, double ry, double x_axis_rotation, bool large_arc_flag, bool sweep_flag, double x, double y, double curx, double cury)
Draws an arc using QPainterPath path.
Static Public Member Functions inherited from TechDrawGui::QGIView
static Gui::ViewProvider * getViewProvider (App::DocumentObject *obj)
static ViewProviderPage * getViewProviderPage (TechDraw::DrawView *dView)
static int calculateFontPixelSize (double sizeInMillimetres)
static int calculateFontPixelWidth (const QFont &font)
static QString getPrefFont ()
static double getPrefFontSize ()
static double getDimFontSize ()
static int exactFontSize (std::string fontFamily, double nominalSize)
Public Attributes inherited from TechDrawGui::QGIViewPart
bool showSection
Static Public Attributes inherited from TechDrawGui::QGIView
static const double DefaultFontSizeInMM = 5.0
Detailed Description
Definition at line 53 of file QGIViewSection.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 82 of file QGIViewSection.h.
Constructor & Destructor Documentation
QGIViewSection()
TechDrawGui::QGIViewSection::QGIViewSection () default
~QGIViewSection()
TechDrawGui::QGIViewSection::~QGIViewSection () override default
Member Function Documentation
draw()
void QGIViewSection::draw () override virtual
Reimplemented from TechDrawGui::QGIViewPart.
Definition at line 38 of file QGIViewSection.cpp.
References TechDrawGui::QGIViewPart::draw(), drawSectionFace(), and TechDrawGui::QGIView::isVisible().
Referenced by updateView().
drawSectionFace()
void QGIViewSection::drawSectionFace () protected
Definition at line 48 of file QGIViewSection.cpp.
References TechDrawGui::QGIFace::addLineSet(), TechDrawGui::QGIFace::clearLineSets(), Base::Console(), TechDrawGui::ViewProviderViewSection::CutSurfaceColor, TechDrawGui::ViewProviderViewSection::CutSurfaceTransparency, TechDrawGui::QGIFace::draw(), TechDrawGui::QGIViewPart::drawFace(), TechDrawGui::ViewProviderViewSection::GeomHatchColor, TechDrawGui::QGIFace::GeomHatchFill, App::PropertyInteger::getValue(), App::PropertyQuantity::getValue(), App::PropertyFloat::getValue(), App::PropertyColor::getValue(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), TechDrawGui::ViewProviderViewSection::HatchColor, SplineSurface::i, TechDrawGui::QGIFace::isHatched(), TechDrawGui::ViewProviderViewPart::LineWidth, TechDrawGui::QGIFace::NoFill, TechDrawGui::QGIFace::PlainFill, ZVALUE::SECTIONFACE, TechDrawGui::QGIFace::setDrawEdges(), TechDrawGui::QGIPrimPath::setFillColor(), TechDrawGui::QGIFace::setFillMode(), TechDrawGui::QGIFace::setHatchColor(), TechDrawGui::QGIFace::setHatchFile(), TechDrawGui::QGIFace::setHatchOffset(), TechDrawGui::QGIFace::setHatchRotation(), TechDrawGui::QGIFace::setHatchScale(), TechDrawGui::QGIFace::setLineWeight(), TechDrawGui::QGIFace::setPrettyNormal(), TechDrawGui::QGIPrimPath::setStyle(), TechDrawGui::QGIPrimPath::setWidth(), TechDrawGui::QGIFace::SvgFill, Base::ConsoleSingleton::Warning(), and TechDrawGui::ViewProviderViewSection::WeightPattern.
Referenced by draw().
type()
int TechDrawGui::QGIViewSection::type () const inline override
Definition at line 83 of file QGIViewSection.h.
updateView()
void QGIViewSection::updateView (bool update = false) override virtual
Reimplemented from TechDrawGui::QGIViewPart.
Definition at line 131 of file QGIViewSection.cpp.
References draw(), TechDrawGui::QGIView::getViewObject(), and TechDrawGui::QGIView::updateView().
The documentation for this class was generated from the following files:
QGIViewSection.h
QGIViewSection.cpp