FreeCAD: Materials::Material3DArray Class Reference
Materials::Material3DArray Class Reference
#include <MaterialValue.h>
Public Member Functions
Material3DArray ()
~Material3DArray () override=default
bool isNull () const override
const QList< std::pair< Base::Quantity, std::shared_ptr< QList< std::shared_ptr< QList< Base::Quantity > > > > > > & getArray () const
void validateDepth (int level) const
void validateColumn (int column) const
void validateRow (int level, int row) const
const std::shared_ptr< QList< std::shared_ptr< QList< Base::Quantity > > > > & getTable (const Base::Quantity &depth) const
const std::shared_ptr< QList< std::shared_ptr< QList< Base::Quantity > > > > & getTable (int depthIndex) const
std::shared_ptr< QList< Base::Quantity > > getRow (int depth, int row) const
std::shared_ptr< QList< Base::Quantity > > getRow (int row) const
std::shared_ptr< QList< Base::Quantity > > getRow (int depth, int row)
std::shared_ptr< QList< Base::Quantity > > getRow (int row)
void addRow (int depth, const std::shared_ptr< QList< Base::Quantity >> &row)
void addRow (const std::shared_ptr< QList< Base::Quantity >> &row)
int addDepth (int depth, const Base::Quantity &value)
int addDepth (const Base::Quantity &value)
void deleteDepth (int depth)
void insertRow (int depth, int row, const std::shared_ptr< QList< Base::Quantity >> &rowData)
void insertRow (int row, const std::shared_ptr< QList< Base::Quantity >> &rowData)
void deleteRow (int depth, int row)
void deleteRow (int row)
void deleteRows (int depth)
void deleteRows ()
int depth () const
int rows (int depth) const
int rows () const
int columns () const
void setColumns (int size)
void setValue (int depth, int row, int column, const Base::Quantity &value)
void setValue (int row, int column, const Base::Quantity &value)
void setDepthValue (int depth, const Base::Quantity &value)
void setDepthValue (const Base::Quantity &value)
Base::Quantity getValue (int depth, int row, int column) const
Base::Quantity getValue (int row, int column) const
Base::Quantity getDepthValue (int depth) const
int currentDepth () const
void setCurrentDepth (int depth)
QString getYAMLString () const override
Public Member Functions inherited from Materials::MaterialValue
MaterialValue ()
MaterialValue (const MaterialValue &other)
MaterialValue (ValueType type)
virtual ~MaterialValue ()=default
MaterialValue & operator= (const MaterialValue &other)
virtual bool operator== (const MaterialValue &other) const
bool operator!= (const MaterialValue &other) const
ValueType getType () const
QVariant getValue () const
QList< QVariant > getList ()
const QList< QVariant > getList () const
virtual const QVariant getValueAt (const QVariant &value) const
void setValue (const QVariant &value)
void setList (const QList< QVariant > &value)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Attributes
QList< std::pair< Base::Quantity, std::shared_ptr< QList< std::shared_ptr< QList< Base::Quantity > > > > > > _rowMap
int _currentDepth
int _columns
Protected Attributes inherited from Materials::MaterialValue
ValueType _valueType
QVariant _value
Additional Inherited Members
Public Types inherited from Materials::MaterialValue
enum ValueType {
None = 0, String = 1, Boolean = 2, Integer = 3,
Float = 4, Quantity = 5, Distribution = 6, List = 7,
Array2D = 8, Array3D = 9, Color = 10, Image = 11,
File = 12, URL = 13, MultiLineString = 14, FileList = 15,
ImageList = 16, SVG
}
Static Public Member Functions inherited from Materials::MaterialValue
static QString escapeString (const QString &source)
static ValueType mapType (const QString &stringType)
static const Base::QuantityFormat getQuantityFormat ()
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Attributes inherited from Materials::MaterialValue
static const int PRECISION = 6
Protected Member Functions inherited from Materials::MaterialValue
MaterialValue (ValueType type, ValueType inherited)
void setType (ValueType type)
void setInitialValue (ValueType inherited)
QString getYAMLStringImage () const
QString getYAMLStringList () const
QString getYAMLStringImageList () const
QString getYAMLStringMultiLine () const
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 210 of file MaterialValue.h.
Constructor & Destructor Documentation
Material3DArray()
Material3DArray::Material3DArray ()
Definition at line 517 of file MaterialValue.cpp.
~Material3DArray()
Materials::Material3DArray::~Material3DArray () override default
Member Function Documentation
addDepth() [1/2]
int Material3DArray::addDepth (const Base::Quantity & value)
Definition at line 643 of file MaterialValue.cpp.
References _rowMap, and depth().
addDepth() [2/2]
int Material3DArray::addDepth (int depth, const Base::Quantity & value)
Definition at line 627 of file MaterialValue.cpp.
References _rowMap, and depth().
addRow() [1/2]
void Material3DArray::addRow (const std::shared_ptr< QList< Base::Quantity >> & row)
Definition at line 622 of file MaterialValue.cpp.
References _currentDepth, and addRow().
addRow() [2/2]
void Material3DArray::addRow (int depth, const std::shared_ptr< QList< Base::Quantity >> & row)
Definition at line 612 of file MaterialValue.cpp.
References depth(), and getTable().
Referenced by addRow().
columns()
int Materials::Material3DArray::columns () const inline
Definition at line 259 of file MaterialValue.h.
Referenced by validateColumn().
currentDepth()
int Material3DArray::currentDepth () const
Definition at line 778 of file MaterialValue.cpp.
References _currentDepth.
deleteDepth()
void Material3DArray::deleteDepth (int depth)
Definition at line 652 of file MaterialValue.cpp.
References _rowMap, deleteRows(), and depth().
deleteRow() [1/2]
void Material3DArray::deleteRow (int depth, int row)
Definition at line 676 of file MaterialValue.cpp.
References depth(), and getTable().
Referenced by deleteRow().
deleteRow() [2/2]
void Material3DArray::deleteRow (int row)
Definition at line 685 of file MaterialValue.cpp.
References _currentDepth, and deleteRow().
deleteRows() [1/2]
void Material3DArray::deleteRows ()
Definition at line 696 of file MaterialValue.cpp.
References _currentDepth.
Referenced by deleteDepth().
deleteRows() [2/2]
void Material3DArray::deleteRows (int depth)
Definition at line 690 of file MaterialValue.cpp.
References depth(), and getTable().
depth()
int Materials::Material3DArray::depth () const inline
Definition at line 250 of file MaterialValue.h.
Referenced by addDepth(), addRow(), deleteDepth(), deleteRow(), deleteRows(), getDepthValue(), getRow(), getTable(), getValue(), getYAMLString(), insertRow(), isNull(), rows(), setCurrentDepth(), setDepthValue(), setValue(), and validateDepth().
getArray()
const QList< std::pair<Base::Quantity, std::shared_ptr<QList<std::shared_ptr<QList<Base::Quantity> > > > > >& Materials::Material3DArray::getArray () const inline
Definition at line 222 of file MaterialValue.h.
getDepthValue()
Base::Quantity Material3DArray::getDepthValue (int depth) const
Definition at line 766 of file MaterialValue.cpp.
References _rowMap, depth(), and validateDepth().
Referenced by getYAMLString().
getRow() [1/4]
std::shared_ptr< QList< Base::Quantity > > Material3DArray::getRow (int depth, int row)
Definition at line 595 of file MaterialValue.cpp.
References depth(), getTable(), and validateRow().
getRow() [2/4]
std::shared_ptr< QList< Base::Quantity > > Material3DArray::getRow (int depth, int row) const
Definition at line 577 of file MaterialValue.cpp.
References depth(), getTable(), and validateRow().
Referenced by getRow(), getValue(), and setValue().
getRow() [3/4]
std::shared_ptr< QList< Base::Quantity > > Material3DArray::getRow (int row)
Definition at line 607 of file MaterialValue.cpp.
References _currentDepth, and getRow().
getRow() [4/4]
std::shared_ptr< QList< Base::Quantity > > Material3DArray::getRow (int row) const
Definition at line 589 of file MaterialValue.cpp.
References _currentDepth, and getRow().
getTable() [1/2]
const std::shared_ptr< QList< std::shared_ptr< QList< Base::Quantity > > > > & Material3DArray::getTable (const Base::Quantity & depth) const
Definition at line 555 of file MaterialValue.cpp.
References _rowMap, and depth().
Referenced by addRow(), deleteRow(), deleteRows(), getRow(), getYAMLString(), insertRow(), rows(), and setDepthValue().
getTable() [2/2]
const std::shared_ptr< QList< std::shared_ptr< QList< Base::Quantity > > > > & Material3DArray::getTable (int depthIndex) const
Definition at line 567 of file MaterialValue.cpp.
References _rowMap.
getValue() [1/2]
Base::Quantity Material3DArray::getValue (int depth, int row, int column) const
Definition at line 747 of file MaterialValue.cpp.
References App::ExpressionParser::column, depth(), getRow(), toolbit-attributes::val, and validateColumn().
getValue() [2/2]
Base::Quantity Material3DArray::getValue (int row, int column) const
Definition at line 761 of file MaterialValue.cpp.
References _currentDepth, App::ExpressionParser::column, and Materials::MaterialValue::getValue().
getYAMLString()
QString Material3DArray::getYAMLString () const override virtual
Reimplemented from Materials::MaterialValue.
Definition at line 798 of file MaterialValue.cpp.
References App::ExpressionParser::column, depth(), getDepthValue(), getTable(), isNull(), and rows().
insertRow() [1/2]
void Material3DArray::insertRow (int depth, int row, const std::shared_ptr< QList< Base::Quantity >> & rowData)
Definition at line 658 of file MaterialValue.cpp.
References depth(), and getTable().
Referenced by insertRow().
insertRow() [2/2]
void Material3DArray::insertRow (int row, const std::shared_ptr< QList< Base::Quantity >> & rowData)
Definition at line 671 of file MaterialValue.cpp.
References _currentDepth, and insertRow().
isNull()
bool Material3DArray::isNull () const override virtual
Reimplemented from Materials::MaterialValue.
Definition at line 526 of file MaterialValue.cpp.
References depth().
Referenced by getYAMLString().
rows() [1/2]
int Materials::Material3DArray::rows () const inline
Definition at line 255 of file MaterialValue.h.
Referenced by getYAMLString(), and validateRow().
rows() [2/2]
int Material3DArray::rows (int depth) const
Definition at line 701 of file MaterialValue.cpp.
References depth(), getTable(), and validateDepth().
setColumns()
void Materials::Material3DArray::setColumns (int size) inline
Definition at line 263 of file MaterialValue.h.
setCurrentDepth()
void Material3DArray::setCurrentDepth (int depth)
Definition at line 783 of file MaterialValue.cpp.
References _currentDepth, _rowMap, depth(), and validateDepth().
setDepthValue() [1/2]
void Material3DArray::setDepthValue (const Base::Quantity & value)
Definition at line 741 of file MaterialValue.cpp.
References _currentDepth, and setDepthValue().
setDepthValue() [2/2]
void Material3DArray::setDepthValue (int depth, const Base::Quantity & value)
Definition at line 730 of file MaterialValue.cpp.
References _rowMap, depth(), and getTable().
Referenced by setDepthValue().
setValue() [1/2]
void Material3DArray::setValue (int depth, int row, int column, const Base::Quantity & value)
Definition at line 711 of file MaterialValue.cpp.
References App::ExpressionParser::column, depth(), getRow(), toolbit-attributes::val, validateColumn(), and validateRow().
Referenced by setValue().
setValue() [2/2]
void Material3DArray::setValue (int row, int column, const Base::Quantity & value)
Definition at line 725 of file MaterialValue.cpp.
References _currentDepth, App::ExpressionParser::column, and setValue().
validateColumn()
void Material3DArray::validateColumn (int column) const
Definition at line 538 of file MaterialValue.cpp.
References columns().
Referenced by getValue(), and setValue().
validateDepth()
void Material3DArray::validateDepth (int level) const
Definition at line 531 of file MaterialValue.cpp.
References depth().
Referenced by getDepthValue(), rows(), setCurrentDepth(), and validateRow().
validateRow()
void Material3DArray::validateRow (int level, int row) const
Definition at line 545 of file MaterialValue.cpp.
References level(), rows(), and validateDepth().
Referenced by getRow(), and setValue().
Member Data Documentation
_columns
int Materials::Material3DArray::_columns protected
Definition at line 285 of file MaterialValue.h.
_currentDepth
int Materials::Material3DArray::_currentDepth protected
Definition at line 284 of file MaterialValue.h.
Referenced by addRow(), currentDepth(), deleteRow(), deleteRows(), getRow(), getValue(), insertRow(), setCurrentDepth(), setDepthValue(), and setValue().
_rowMap
QList<std::pair<Base::Quantity, std::shared_ptr<QList<std::shared_ptr<QList<Base::Quantity> > > > > > Materials::Material3DArray::_rowMap protected
Definition at line 283 of file MaterialValue.h.
Referenced by addDepth(), deleteDepth(), getDepthValue(), getTable(), setCurrentDepth(), and setDepthValue().
The documentation for this class was generated from the following files:
MaterialValue.h
MaterialValue.cpp