FreeCAD: Gui::TaskView::TaskWatcherPython Class Reference
Gui::TaskView::TaskWatcherPython Class Reference
#include <TaskDialogPython.h>
Public Member Functions
TaskWatcherPython (const Py::Object &)
~TaskWatcherPython () override
bool shouldShow () override
is called wenn the document or the Selection changes.
Public Member Functions inherited from Gui::TaskView::TaskWatcher
TaskWatcher (const char *Filter)
~TaskWatcher () override
QWidget * addTaskBox (QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBox (const QPixmap &icon, QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBoxWithoutHeader (QWidget *widget)
std::vector< QWidget * > & getWatcherContent ()
Public Member Functions inherited from Gui::SelectionFilter
SelectionFilter (const char *filter)
SelectionFilter (const std::string &filter)
virtual ~SelectionFilter ()
void setFilter (const char *filter)
Set a new filter string.
const std::string & getFilter () const
bool match ()
bool test (App::DocumentObject *pObj, const char *sSubName)
void addError (const char *e)
bool isValid () const
true if a valid filter is set
Additional Inherited Members
Public Attributes inherited from Gui::SelectionFilter
std::vector< std::vector< SelectionObject > > Result
Protected Member Functions inherited from Gui::SelectionFilter
bool parse ()
Protected Attributes inherited from Gui::TaskView::TaskWatcher
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
Protected Attributes inherited from Gui::SelectionFilter
std::string Filter
std::string Errors
std::shared_ptr< Node_Block > Ast
Detailed Description
Definition at line 100 of file TaskDialogPython.h.
Constructor & Destructor Documentation
TaskWatcherPython()
TaskWatcherPython::TaskWatcherPython (const Py::Object & o) explicit
Definition at line 221 of file TaskDialogPython.cpp.
References Gui::BitmapFactory(), SCL.SimpleDataTypes::c, Gui::Application::commandManager(), Gui::TaskView::TaskWatcher::Content, Gui::CommandManager::getCommandByName(), QSint::ActionGroup::groupLayout(), Gui::Application::Instance, Gui::PythonWrapper::loadCoreModule(), Gui::BitmapFactoryInst::pixmap(), src.Mod.AddonManager.addonmanager_pyside_interface::QObject, toolbit-attributes::s, Gui::SelectionFilter::setFilter(), src.Mod.Test.testmakeWireString::String, Plot::title(), Gui::PythonWrapper::toQObject(), and src.Mod.PartDesign.fcgear.svggear::w.
~TaskWatcherPython()
TaskWatcherPython::~TaskWatcherPython () override
Definition at line 283 of file TaskDialogPython.cpp.
References Gui::TaskView::TaskWatcher::Content.
Member Function Documentation
shouldShow()
bool TaskWatcherPython::shouldShow () override virtual
is called wenn the document or the Selection changes.
Reimplemented from Gui::TaskView::TaskWatcher.
Definition at line 293 of file TaskDialogPython.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, Gui::SelectionFilter::Filter, Gui::SelectionFilter::match(), and Gui::TaskView::TaskWatcher::shouldShow().
The documentation for this class was generated from the following files:
TaskDialogPython.h
TaskDialogPython.cpp