FreeCAD: TechDrawGui::TaskSurfaceFinishSymbols Class Reference
TechDrawGui::TaskSurfaceFinishSymbols Class Reference
#include <TaskSurfaceFinishSymbols.h>
Public Member Functions
TaskSurfaceFinishSymbols (const std::string &ownerName)
~TaskSurfaceFinishSymbols () override=default
virtual bool accept ()
virtual bool reject ()
void updateTask ()
Protected Member Functions
void changeEvent (QEvent *event) override
void setUiEdit ()
Protected Attributes
App::DocumentObject * owner
Base::Vector3d placement
Detailed Description
Definition at line 76 of file TaskSurfaceFinishSymbols.h.
Constructor & Destructor Documentation
TaskSurfaceFinishSymbols()
TaskSurfaceFinishSymbols::TaskSurfaceFinishSymbols (const std::string & ownerName) explicit
Definition at line 88 of file TaskSurfaceFinishSymbols.cpp.
References toolbit-attributes::doc, dot(), App::Application::getActiveDocument(), App::GetApplication(), owner, placement, setUiEdit(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
~TaskSurfaceFinishSymbols()
TechDrawGui::TaskSurfaceFinishSymbols::~TaskSurfaceFinishSymbols () override default
Member Function Documentation
accept()
bool TaskSurfaceFinishSymbols::accept () virtual
Definition at line 395 of file TaskSurfaceFinishSymbols.cpp.
References TechDraw::DrawPage::addView(), Gui::Command::commitCommand(), ZVALUE::DIMENSION, toolbit-attributes::doc, TechDrawGui::QGIView::getViewProvider(), Instance, Gui::Command::openCommand(), TechDraw::DrawViewSymbol::Owner, owner, placement, Arch::QT_TRANSLATE_NOOP, TechDraw::DrawView::Rotation, App::PropertyInteger::setValue(), App::PropertyQuantity::setValue(), App::PropertyLink::setValue(), App::PropertyString::setValue(), TechDrawGui::ViewProviderDrawingView::StackOrder, TechDraw::DrawViewSymbol::Symbol, TechDraw::DrawView::X, Base::Vector3< float_type >::x, TechDraw::DrawView::Y, and Base::Vector3< float_type >::y.
Referenced by TechDrawGui::TaskDlgSurfaceFinishSymbols::accept().
changeEvent()
void TaskSurfaceFinishSymbols::changeEvent (QEvent * event) override protected
Definition at line 236 of file TaskSurfaceFinishSymbols.cpp.
reject()
bool TaskSurfaceFinishSymbols::reject () virtual
Definition at line 427 of file TaskSurfaceFinishSymbols.cpp.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and TechDrawGui::TaskDlgSurfaceFinishSymbols::reject().
setUiEdit()
void TaskSurfaceFinishSymbols::setUiEdit () protected
Definition at line 243 of file TaskSurfaceFinishSymbols.cpp.
References draftgeoutils.intersections::connect(), and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by TaskSurfaceFinishSymbols().
updateTask()
void TaskSurfaceFinishSymbols::updateTask ()
Definition at line 228 of file TaskSurfaceFinishSymbols.cpp.
Member Data Documentation
owner
App::DocumentObject* TechDrawGui::TaskSurfaceFinishSymbols::owner protected
Definition at line 92 of file TaskSurfaceFinishSymbols.h.
Referenced by accept(), and TaskSurfaceFinishSymbols().
placement
Base::Vector3d TechDrawGui::TaskSurfaceFinishSymbols::placement protected
Definition at line 93 of file TaskSurfaceFinishSymbols.h.
Referenced by accept(), and TaskSurfaceFinishSymbols().
The documentation for this class was generated from the following files:
TaskSurfaceFinishSymbols.h
TaskSurfaceFinishSymbols.cpp