FreeCAD: Gui::WorkbenchManager Class Reference
Gui::WorkbenchManager Class Reference
#include <WorkbenchManager.h>
Public Member Functions
Workbench * createWorkbench (const std::string &name, const std::string &className)
void removeWorkbench (const std::string &name)
Workbench * getWorkbench (const std::string &name) const
bool activate (const std::string &name, const std::string &className)
Workbench * active () const
std::string activeName () const
std::list< std::string > workbenches () const
Static Public Member Functions
static WorkbenchManager * instance ()
static void destruct ()
Protected Member Functions
WorkbenchManager ()
~WorkbenchManager ()
Detailed Description
The WorkbenchManager class manages all workbench objects.
Author
Werner Mayer
Definition at line 60 of file WorkbenchManager.h.
Constructor & Destructor Documentation
WorkbenchManager()
WorkbenchManager::WorkbenchManager () protected default
Referenced by instance().
~WorkbenchManager()
WorkbenchManager::~WorkbenchManager () protected
Definition at line 53 of file WorkbenchManager.cpp.
References Gui::DockWindowManager::destruct(), Gui::MenuManager::destruct(), and Gui::ToolBarManager::destruct().
Member Function Documentation
activate()
bool WorkbenchManager::activate (const std::string & name, const std::string & className)
Activates the workbench with name name.
Definition at line 113 of file WorkbenchManager.cpp.
References Gui::Workbench::activate(), and createWorkbench().
Referenced by ArchBuildingPart.ViewProviderBuildingPart::setEdit(), nativeifc.ifc_viewproviders.ifc_vp_object::setupContextMenu(), and ArchBuildingPart.ViewProviderBuildingPart::setupContextMenu().
active()
Workbench * WorkbenchManager::active () const
Returns the active workbench.
Definition at line 125 of file WorkbenchManager.cpp.
Referenced by Gui::Command::_assureWorkbench(), StdCmdWorkbench::activated(), Gui::Application::activateWorkbench(), Gui::Dialog::DlgCustomToolbarsImp::addCustomCommand(), Gui::Dialog::DlgCustomToolbarsImp::addCustomToolbar(), Gui::MainWindow::changeEvent(), Gui::MainWindow::createPopupMenu(), Gui::Dialog::DlgCustomToolbars::DlgCustomToolbars(), SketcherGui::Workbench::leaveEditMode(), Gui::Dialog::DlgCustomToolbarsImp::moveDownCustomCommand(), Gui::Dialog::DlgCustomToolbarsImp::moveUpCustomCommand(), Gui::Dialog::wbListItem::onLoadClicked(), Gui::Dialog::DlgCustomToolbarsImp::removeCustomCommand(), Gui::Dialog::DlgCustomToolbarsImp::removeCustomToolbar(), Gui::Dialog::DlgCustomToolbarsImp::renameCustomToolbar(), Gui::ApplicationPy::sActiveWorkbenchHandler(), and Gui::Application::setupContextMenu().
activeName()
std::string WorkbenchManager::activeName () const
Returns the name of the active workbench.
Definition at line 130 of file WorkbenchManager.cpp.
References Gui::Workbench::name().
Referenced by Gui::WorkbenchGroup::refreshWorkbenchList().
createWorkbench()
Workbench * WorkbenchManager::createWorkbench (const std::string & name, const std::string & className)
Searches for and returns an existing workbench object with name name. If no such workbench exists then a workbench of class className gets created, if possible. If the workbench cannot be created 0 is returned.
Definition at line 66 of file WorkbenchManager.cpp.
References Base::BaseClass::getClassTypeId(), Base::Type::getTypeIfDerivedFrom(), getWorkbench(), Gui::Workbench::setName(), Path.Post.scripts.refactored_centroid_post::str, and Path.Post.scripts.grbl_post::type.
Referenced by activate(), and Gui::Application::activateWorkbench().
destruct()
void WorkbenchManager::destruct () static
Definition at line 45 of file WorkbenchManager.cpp.
Referenced by Gui::Application::~Application().
getWorkbench()
Workbench * WorkbenchManager::getWorkbench (const std::string & name) const
Returns an instance of the workbench with name name. If there is no such workbench 0 is returned.
Definition at line 100 of file WorkbenchManager.cpp.
Referenced by Gui::Application::activateWorkbench(), createWorkbench(), and Gui::Dialog::wbListItem::wbListItem().
instance()
WorkbenchManager * WorkbenchManager::instance () static
Creates the only instance of the WorkbenchManager.
Definition at line 38 of file WorkbenchManager.cpp.
References WorkbenchManager().
Referenced by Gui::Command::_assureWorkbench(), StdCmdWorkbench::activated(), Gui::Application::activateWorkbench(), Gui::Dialog::DlgCustomToolbarsImp::addCustomCommand(), Gui::Dialog::DlgCustomToolbarsImp::addCustomToolbar(), Gui::MainWindow::changeEvent(), Gui::MainWindow::closeEvent(), Gui::MainWindow::createPopupMenu(), Gui::Dialog::DlgCustomToolbars::DlgCustomToolbars(), SketcherGui::Workbench::leaveEditMode(), Gui::Dialog::DlgCustomToolbarsImp::moveDownCustomCommand(), Gui::Dialog::DlgCustomToolbarsImp::moveUpCustomCommand(), Gui::Dialog::wbListItem::onLoadClicked(), Gui::WorkbenchGroup::refreshWorkbenchList(), Gui::Dialog::DlgCustomToolbarsImp::removeCustomCommand(), Gui::Dialog::DlgCustomToolbarsImp::removeCustomToolbar(), Gui::Dialog::DlgCustomToolbarsImp::renameCustomToolbar(), Gui::ApplicationPy::sActiveWorkbenchHandler(), Gui::Application::setupContextMenu(), Gui::ApplicationPy::sRemoveWorkbenchHandler(), and Gui::Dialog::wbListItem::wbListItem().
removeWorkbench()
void WorkbenchManager::removeWorkbench (const std::string & name)
Removes the workbench with name name. If there is no such workbench exists nothing happens.
Definition at line 88 of file WorkbenchManager.cpp.
Referenced by Gui::ApplicationPy::sRemoveWorkbenchHandler().
workbenches()
std::list< std::string > WorkbenchManager::workbenches () const
Returns a list of all created workbench objects.
Definition at line 139 of file WorkbenchManager.cpp.
The documentation for this class was generated from the following files:
WorkbenchManager.h
WorkbenchManager.cpp