FreeCAD: Gui::StartupProcess Class Reference
Gui::StartupProcess Class Reference
#include <StartupProcess.h>
Public Member Functions
StartupProcess ()
void execute ()
Static Public Member Functions
static void setupApplication ()
Detailed Description
Definition at line 37 of file StartupProcess.h.
Constructor & Destructor Documentation
StartupProcess()
StartupProcess::StartupProcess () default
Member Function Documentation
execute()
void StartupProcess::execute ()
Definition at line 112 of file StartupProcess.cpp.
Referenced by draftobjects.facebinder.Facebinder::addSubobjects(), Path.Dressup.Gui.Dogbone.ObjectDressup::boneStateList(), Path.Dressup.Tags.ObjectTagDressup::generateTags(), ArchRoof._Roof::getSubVolume(), ArchPanel.PanelCut::getWires(), src.Mod.PartDesign.Scripts.Spring.MySpring::onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid::onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped::onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt::onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder::onChanged(), MeasureCOM.MeasureCOM::onChanged(), Path.Main.Stock.StockFromBase::onChanged(), Path.Main.Stock.StockCreateBox::onChanged(), Path.Main.Stock.StockCreateCylinder::onChanged(), FeaturePython.DistanceBolt::onChanged(), draftobjects.draftlink.DraftLink::onDocumentRestored(), ArchSchedule._ArchSchedule::setSpreadsheetData(), and draftobjects.array.Array::update_properties_0v21().
setupApplication()
void StartupProcess::setupApplication () static
Definition at line 54 of file StartupProcess.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), and App::Application::GetParameterGroupByPath().
Referenced by Gui::Application::runApplication().
The documentation for this class was generated from the following files:
StartupProcess.h
StartupProcess.cpp