FreeCAD: OpenSCADFeatures.RefineShape Class Reference
OpenSCADFeatures.RefineShape Class Reference
Public Member Functions
def __init__ (self, obj, child=None)
def onChanged (self, fp, prop)
def execute (self, fp)
Detailed Description
return a refined shape
Definition at line 257 of file OpenSCADFeatures.py.
Constructor & Destructor Documentation
__init__()
def OpenSCADFeatures.RefineShape.__init__ (self, obj, child = None)
Definition at line 259 of file OpenSCADFeatures.py.
Member Function Documentation
execute()
def OpenSCADFeatures.RefineShape.execute (self, fp)
Definition at line 269 of file OpenSCADFeatures.py.
Referenced by src.Mod.PartDesign.Scripts.Spring.MySpring.onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped.onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder.onChanged(), and FeaturePython.DistanceBolt.onChanged().
onChanged()
def OpenSCADFeatures.RefineShape.onChanged (self, fp, prop)
Definition at line 265 of file OpenSCADFeatures.py.
The documentation for this class was generated from the following file:
OpenSCADFeatures.py