FreeCAD: App::ExpressionTokenizer Class Reference
App::ExpressionTokenizer Class Reference
#include <ExpressionTokenizer.h>
Public Member Functions
QString perform (const QString &text, int pos)
void getPrefixRange (int &start, int &end) const
void updatePrefixEnd (int end)
Detailed Description
Definition at line 52 of file ExpressionTokenizer.h.
Member Function Documentation
getPrefixRange()
void App::ExpressionTokenizer::getPrefixRange (int & start, int & end) const inline
Definition at line 77 of file ExpressionTokenizer.h.
perform()
QString ExpressionTokenizer::perform (const QString & text, int pos)
Definition at line 38 of file ExpressionTokenizer.cpp.
References SplineSurface::i, IDENTIFIER, INTEGER, LT, ONE, RobotExample::pos, result, STRING, App::ExpressionParser::tokenize(), femtools.tokrules::tokens, Materials::trim(), and UNIT.
Referenced by Gui::ExpressionCompleter::slotUpdate().
updatePrefixEnd()
void App::ExpressionTokenizer::updatePrefixEnd (int end) inline
Definition at line 83 of file ExpressionTokenizer.h.
The documentation for this class was generated from the following files:
ExpressionTokenizer.h
ExpressionTokenizer.cpp