FreeCAD: MeshCore::MeshFacetGrid Class Reference
MeshCore::MeshFacetGrid Class Reference
#include <Grid.h>
Public Member Functions
Construction
MeshFacetGrid (const MeshKernel &rclM)
Construction.
MeshFacetGrid ()=default
Construction.
MeshFacetGrid (const MeshKernel &rclM, unsigned long ulX, unsigned long ulY, unsigned long ulZ)
Construction.
MeshFacetGrid (const MeshKernel &rclM, int iCtGridPerAxis)
Construction.
MeshFacetGrid (const MeshKernel &rclM, float fGridLen)
Construction.
MeshFacetGrid (const MeshFacetGrid &)=default
MeshFacetGrid (MeshFacetGrid &&)=default
~MeshFacetGrid () override=default
Destruction.
MeshFacetGrid & operator= (const MeshFacetGrid &)=default
MeshFacetGrid & operator= (MeshFacetGrid &&)=default
Public Member Functions inherited from MeshCore::MeshGrid
virtual unsigned long Inside (const Base::BoundBox3f &rclBB, std::vector< ElementIndex > &raulElements, bool bDelDoubles=true) const
virtual unsigned long Inside (const Base::BoundBox3f &rclBB, std::set< ElementIndex > &raulElementss) const
virtual unsigned long Inside (const Base::BoundBox3f &rclBB, std::vector< ElementIndex > &raulElements, const Base::Vector3f &rclOrg, float fMaxDist, bool bDelDoubles=true) const
void SearchNearestFromPoint (const Base::Vector3f &pnt, std::set< ElementIndex > &indices) const
unsigned long GetElements (unsigned long ulX, unsigned long ulY, unsigned long ulZ, std::set< ElementIndex > &raclInd) const
unsigned long GetElements (const Base::Vector3f &rclPoint, std::vector< ElementIndex > &aulFacets) const
virtual void GetGridLengths (float &rfLenX, float &rfLenY, float &rfLenZ) const
virtual void GetCtGrids (unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
Base::BoundBox3f GetBoundBox (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
Base::BoundBox3f GetBoundBox () const
Base::BoundBox3f GetMeshBoundBox () const
unsigned long GetIndexToPosition (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
bool GetPositionToIndex (unsigned long id, unsigned long &ulX, unsigned long &ulY, unsigned long &ulZ) const
unsigned long GetCtElements (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
bool CheckPosition (const Base::Vector3f &rclPoint, unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
virtual void Position (const Base::Vector3f &rclPoint, unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
bool CheckPos (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
void GetHull (unsigned long ulX, unsigned long ulY, unsigned long ulZ, unsigned long ulDistance, std::set< ElementIndex > &raclInd) const
virtual ~MeshGrid ()=default
Destruction.
virtual void Attach (const MeshKernel &rclM)
virtual void Rebuild (int iCtGridPerAxis=20)
virtual void Rebuild (unsigned long ulX, unsigned long ulY, unsigned long ulZ)
Search
unsigned long SearchNearestFromPoint (const Base::Vector3f &rclPt) const
unsigned long SearchNearestFromPoint (const Base::Vector3f &rclPt, float fMaxSearchArea) const
void SearchNearestFacetInGrid (unsigned long ulX, unsigned long ulY, unsigned long ulZ, const Base::Vector3f &rclPt, float &rfMinDist, ElementIndex &rulFacetInd) const
void SearchNearestFacetInHull (unsigned long ulX, unsigned long ulY, unsigned long ulZ, unsigned long ulDistance, const Base::Vector3f &rclPt, ElementIndex &rulFacetInd, float &rfMinDist) const
void Validate (const MeshKernel &rclM) override
virtual void Validate ()
bool Verify () const override
void Pos (const Base::Vector3f &rclPoint, unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
void PosWithCheck (const Base::Vector3f &rclPoint, unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
void AddFacet (const MeshGeomFacet &rclFacet, ElementIndex ulFacetIndex, float fEpsilon=0.0F)
unsigned long HasElements () const override
void RebuildGrid () override
Additional Inherited Members
Protected Member Functions inherited from MeshCore::MeshGrid
virtual void InitGrid ()
virtual void Clear ()
virtual void CalculateGridLength (int iCtGridPerAxis)
MeshGrid (const MeshKernel &rclM)
Construction.
MeshGrid ()
Construction.
MeshGrid (const MeshGrid &)=default
MeshGrid (MeshGrid &&)=default
MeshGrid & operator= (const MeshGrid &)=default
MeshGrid & operator= (MeshGrid &&)=default
Protected Attributes inherited from MeshCore::MeshGrid
std::vector< std::vector< std::vector< std::set< ElementIndex > > > > _aulGrid
const MeshKernel * _pclMesh
unsigned long _ulCtElements
unsigned long _ulCtGridsX
unsigned long _ulCtGridsY
unsigned long _ulCtGridsZ
float _fGridLenX
float _fGridLenY
float _fGridLenZ
float _fMinX
float _fMinY
float _fMinZ
Detailed Description
Special grid class that stores facet indices of the mesh object in its grids.
Definition at line 221 of file Grid.h.
Constructor & Destructor Documentation
MeshFacetGrid() [1/7]
MeshFacetGrid::MeshFacetGrid (const MeshKernel & rclM) explicit
Construction.
Definition at line 668 of file Grid.cpp.
References RebuildGrid().
MeshFacetGrid() [2/7]
MeshCore::MeshFacetGrid::MeshFacetGrid () default
Construction.
MeshFacetGrid() [3/7]
MeshFacetGrid::MeshFacetGrid (const MeshKernel & rclM, unsigned long ulX, unsigned long ulY, unsigned long ulZ)
Construction.
Definition at line 680 of file Grid.cpp.
References MeshCore::MeshGrid::Rebuild().
MeshFacetGrid() [4/7]
MeshFacetGrid::MeshFacetGrid (const MeshKernel & rclM, int iCtGridPerAxis)
Construction.
Definition at line 674 of file Grid.cpp.
References MeshCore::MeshGrid::Rebuild().
MeshFacetGrid() [5/7]
MeshFacetGrid::MeshFacetGrid (const MeshKernel & rclM, float fGridLen)
Construction.
Definition at line 689 of file Grid.cpp.
References MeshCore::MeshGrid::_pclMesh, MeshCore::MeshKernel::GetBoundBox(), Base::BoundBox3< Precision >::LengthX(), Base::BoundBox3< Precision >::LengthY(), Base::BoundBox3< Precision >::LengthZ(), and MeshCore::MeshGrid::Rebuild().
MeshFacetGrid() [6/7]
MeshCore::MeshFacetGrid::MeshFacetGrid (const MeshFacetGrid &) default
MeshFacetGrid() [7/7]
MeshCore::MeshFacetGrid::MeshFacetGrid (MeshFacetGrid &&) default
~MeshFacetGrid()
MeshCore::MeshFacetGrid::~MeshFacetGrid () override default
Destruction.
Member Function Documentation
AddFacet()
void MeshCore::MeshFacetGrid::AddFacet (const MeshGeomFacet & rclFacet, ElementIndex ulFacetIndex, float fEpsilon = 0.0F) inline protected
Adds a new facet element to the grid structure. rclFacet is the geometric facet and ulFacetIndex the corresponding index in the mesh kernel. The facet is added to each grid element that intersects the facet.
Definition at line 563 of file Grid.h.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::MeshGrid::_aulGrid, Base::BoundBox3< Precision >::Add(), MeshCore::MeshGrid::GetBoundBox(), MeshCore::MeshGeomFacet::IntersectBoundingBox(), Base::BoundBox3< Precision >::MaxX, Base::BoundBox3< Precision >::MaxY, Base::BoundBox3< Precision >::MaxZ, Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, Base::BoundBox3< Precision >::MinZ, and Pos().
Referenced by RebuildGrid().
HasElements()
unsigned long MeshCore::MeshFacetGrid::HasElements () const inline override protected virtual
Returns the number of stored elements.
Implements MeshCore::MeshGrid.
Definition at line 293 of file Grid.h.
operator=() [1/2]
MeshFacetGrid& MeshCore::MeshFacetGrid::operator= (const MeshFacetGrid &) default
operator=() [2/2]
MeshFacetGrid& MeshCore::MeshFacetGrid::operator= (MeshFacetGrid &&) default
Pos()
void MeshCore::MeshFacetGrid::Pos (const Base::Vector3f & rclPoint, unsigned long & rulX, unsigned long & rulY, unsigned long & rulZ) const inline protected
Returns the grid numbers to the given point rclPoint.
Definition at line 513 of file Grid.h.
References MeshCore::MeshGrid::_fGridLenX, MeshCore::MeshGrid::_fGridLenY, MeshCore::MeshGrid::_fGridLenZ, MeshCore::MeshGrid::_fMinX, MeshCore::MeshGrid::_fMinY, MeshCore::MeshGrid::_fMinZ, MeshCore::MeshGrid::_ulCtGridsX, MeshCore::MeshGrid::_ulCtGridsY, MeshCore::MeshGrid::_ulCtGridsZ, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by AddFacet().
PosWithCheck()
void MeshCore::MeshFacetGrid::PosWithCheck (const Base::Vector3f & rclPoint, unsigned long & rulX, unsigned long & rulY, unsigned long & rulZ) const inline protected
Returns the grid numbers to the given point rclPoint.
Definition at line 525 of file Grid.h.
References MeshCore::MeshGrid::_fGridLenX, MeshCore::MeshGrid::_fGridLenY, MeshCore::MeshGrid::_fGridLenZ, MeshCore::MeshGrid::_fMinX, MeshCore::MeshGrid::_fMinY, MeshCore::MeshGrid::_fMinZ, MeshCore::MeshGrid::_ulCtGridsX, MeshCore::MeshGrid::_ulCtGridsY, MeshCore::MeshGrid::_ulCtGridsZ, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
RebuildGrid()
void MeshFacetGrid::RebuildGrid () override protected virtual
Rebuilds the grid structure.
Implements MeshCore::MeshGrid.
Definition at line 744 of file Grid.cpp.
References MeshCore::MeshGrid::_pclMesh, MeshCore::MeshGrid::_ulCtElements, AddFacet(), MeshCore::MeshKernel::CountFacets(), SplineSurface::i, MeshCore::MeshFacetIterator::Init(), MeshCore::MeshGrid::InitGrid(), MeshCore::MeshFacetIterator::More(), and MeshCore::MeshFacetIterator::Next().
Referenced by MeshFacetGrid(), and Validate().
SearchNearestFacetInGrid()
void MeshFacetGrid::SearchNearestFacetInGrid (unsigned long ulX, unsigned long ulY, unsigned long ulZ, const Base::Vector3f & rclPt, float & rfMinDist, ElementIndex & rulFacetInd) const
Searches for the nearest facet in a given grid element and returns the facet index and the actual distance.
Definition at line 981 of file Grid.cpp.
References MeshCore::MeshGrid::_aulGrid, MeshCore::MeshGrid::_pclMesh, MeshCore::MeshGeomFacet::DistanceToPoint(), and MeshCore::MeshKernel::GetFacet().
Referenced by SearchNearestFacetInHull(), and SearchNearestFromPoint().
SearchNearestFacetInHull()
void MeshFacetGrid::SearchNearestFacetInHull (unsigned long ulX, unsigned long ulY, unsigned long ulZ, unsigned long ulDistance, const Base::Vector3f & rclPt, ElementIndex & rulFacetInd, float & rfMinDist) const
Does basically the same as the method above unless that grid neighbours up to the order of ulDistance are introduced into the search.
Definition at line 898 of file Grid.cpp.
References MeshCore::MeshGrid::_ulCtGridsX, MeshCore::MeshGrid::_ulCtGridsY, MeshCore::MeshGrid::_ulCtGridsZ, SplineSurface::i, and SearchNearestFacetInGrid().
Referenced by SearchNearestFromPoint().
SearchNearestFromPoint() [1/2]
unsigned long MeshFacetGrid::SearchNearestFromPoint (const Base::Vector3f & rclPt) const
Searches for the nearest facet from a point.
Definition at line 760 of file Grid.cpp.
References MeshCore::MeshGrid::_fGridLenX, MeshCore::MeshGrid::_fGridLenY, MeshCore::MeshGrid::_fGridLenZ, MeshCore::MeshGrid::_ulCtGridsX, MeshCore::MeshGrid::_ulCtGridsY, MeshCore::MeshGrid::_ulCtGridsZ, Base::BoundBox3< Precision >::BACK, Base::BoundBox3< Precision >::BOTTOM, MeshCore::ELEMENT_INDEX_MAX, FLOAT_MAX, Base::BoundBox3< Precision >::FRONT, MeshCore::MeshGrid::GetBoundBox(), Base::BoundBox3< Precision >::GetCenter(), Base::BoundBox3< Precision >::GetSideFromRay(), SplineSurface::i, Base::BoundBox3< Precision >::IsInBox(), Base::BoundBox3< Precision >::LEFT, Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, Base::BoundBox3< Precision >::MinZ, MeshCore::MeshGrid::Position(), Base::BoundBox3< Precision >::RIGHT, SearchNearestFacetInGrid(), SearchNearestFacetInHull(), Base::BoundBox3< Precision >::TOP, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by MeshCore::MeshAlgorithm::NearestPointFromPoint().
SearchNearestFromPoint() [2/2]
unsigned long MeshFacetGrid::SearchNearestFromPoint (const Base::Vector3f & rclPt, float fMaxSearchArea) const
Searches for the nearest facet from a point with the maximum search area.
Definition at line 868 of file Grid.cpp.
References MeshCore::MeshGrid::_pclMesh, MeshCore::MeshAlgorithm::Distance(), MeshCore::ELEMENT_INDEX_MAX, MeshCore::MeshGrid::Inside(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Validate() [1/2]
void MeshFacetGrid::Validate () virtual
Validates the grid structure and rebuilds it if needed.
Definition at line 708 of file Grid.cpp.
References MeshCore::MeshGrid::_pclMesh, MeshCore::MeshGrid::_ulCtElements, MeshCore::MeshKernel::CountFacets(), and RebuildGrid().
Validate() [2/2]
void MeshFacetGrid::Validate (const MeshKernel & rclM) override virtual
Validates the grid structure and rebuilds it if needed.
Implements MeshCore::MeshGrid.
Definition at line 698 of file Grid.cpp.
References MeshCore::MeshGrid::_pclMesh, MeshCore::MeshGrid::_ulCtElements, MeshCore::MeshGrid::Attach(), MeshCore::MeshKernel::CountFacets(), and RebuildGrid().
Verify()
bool MeshFacetGrid::Verify () const override virtual
Verifies the grid structure and returns false if inconsistencies are found.
Implements MeshCore::MeshGrid.
Definition at line 719 of file Grid.cpp.
References MeshCore::MeshGrid::_pclMesh, MeshCore::MeshGrid::_ulCtElements, MeshCore::MeshKernel::CountFacets(), MeshCore::MeshGridIterator::GetBoundBox(), MeshCore::MeshGridIterator::GetElements(), MeshCore::MeshGridIterator::Init(), MeshCore::MeshGeomFacet::IntersectBoundingBox(), MeshCore::MeshGridIterator::More(), MeshCore::MeshGridIterator::Next(), and MeshCore::MeshFacetIterator::Set().
The documentation for this class was generated from the following files:
Grid.h
Grid.cpp