FreeCAD: ifc2x3.ifcarbitraryprofiledefwithvoids Class Reference
ifc2x3.ifcarbitraryprofiledefwithvoids Class Reference
Public Member Functions
def __init__ (self, inherited0__profiletype, inherited1__profilename, inherited2__outercurve, innercurves)
def innercurves ()
def wr1 (self)
def wr2 (self)
def wr3 (self)
Public Member Functions inherited from ifc2x3.ifcarbitraryclosedprofiledef
def __init__ (self, inherited0__profiletype, inherited1__profilename, outercurve)
def outercurve ()
Public Member Functions inherited from ifc2x3.ifcprofiledef
def __init__ (self, profiletype, profilename)
def profiletype ()
def profilename ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
innercurves
profiletype
Public Attributes inherited from ifc2x3.ifcarbitraryclosedprofiledef
outercurve
dim
Public Attributes inherited from ifc2x3.ifcprofiledef
profiletype
profilename
Detailed Description
Entity ifcarbitraryprofiledefwithvoids definition.
:param innercurves
:type innercurves:SET(1,None,'ifccurve', scope = schema_scope)
Definition at line 23852 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcarbitraryprofiledefwithvoids.__init__ (self, inherited0__profiletype, inherited1__profilename, inherited2__outercurve, innercurves)
Definition at line 23858 of file ifc2x3.py.
Member Function Documentation
innercurves()
def ifc2x3.ifcarbitraryprofiledefwithvoids.innercurves ()
Definition at line 23863 of file ifc2x3.py.
References ifc2x3.ifcarbitraryprofiledefwithvoids._innercurves, SCL.TypeChecker.check_type(), and ifc2x3.ifcarbitraryprofiledefwithvoids.innercurves.
wr1()
def ifc2x3.ifcarbitraryprofiledefwithvoids.wr1 (self)
Reimplemented from ifc2x3.ifcarbitraryclosedprofiledef.
Definition at line 23875 of file ifc2x3.py.
Referenced by ifc4.ifctextalignment.__init__(), ifc4.ifcspecularroughness.__init__(), ifc4.ifcheatingvaluemeasure.__init__(), ifc4.ifctexttransformation.__init__(), ifc4.ifcfontstyle.__init__(), ifc4.ifcboxalignment.__init__(), ifc4.ifcpositiveplaneanglemeasure.__init__(), ifc4.ifcdimensioncount.__init__(), ifc4.ifcfontvariant.__init__(), ifc4.ifcfontweight.__init__(), ifc4.ifcnormalisedratiomeasure.__init__(), ifc4.ifcpositivelengthmeasure.__init__(), ifc4.ifcpositiveratiomeasure.__init__(), and ifc4.ifctextdecoration.__init__().
wr2()
def ifc2x3.ifcarbitraryprofiledefwithvoids.wr2 (self)
Reimplemented from ifc2x3.ifcarbitraryclosedprofiledef.
Definition at line 23882 of file ifc2x3.py.
References SCL.Builtin.SIZEOF().
wr3()
def ifc2x3.ifcarbitraryprofiledefwithvoids.wr3 (self)
Reimplemented from ifc2x3.ifcarbitraryclosedprofiledef.
Definition at line 23889 of file ifc2x3.py.
References SCL.Builtin.SIZEOF().
Member Data Documentation
innercurves
ifc2x3.ifcarbitraryprofiledefwithvoids.innercurves
Definition at line 23860 of file ifc2x3.py.
Referenced by ifc2x3.ifcarbitraryprofiledefwithvoids.innercurves().
profiletype
ifc2x3.ifcarbitraryprofiledefwithvoids.profiletype
Definition at line 23876 of file ifc2x3.py.
The documentation for this class was generated from the following file:
ifc2x3.py