FreeCAD: Materials::MaterialFilterOptions Class Reference
Materials::MaterialFilterOptions Class Reference
#include <MaterialFilter.h>
Public Member Functions
MaterialFilterOptions ()
virtual ~MaterialFilterOptions ()=default
bool includeFavorites () const
void setIncludeFavorites (bool value)
bool includeRecent () const
void setIncludeRecent (bool value)
bool includeEmptyFolders () const
void setIncludeEmptyFolders (bool value)
bool includeEmptyLibraries () const
void setIncludeEmptyLibraries (bool value)
bool includeLegacy () const
void setIncludeLegacy (bool legacy)
Protected Attributes
bool _includeFavorites
bool _includeRecent
bool _includeFolders
bool _includeLibraries
bool _includeLegacy
Detailed Description
Definition at line 63 of file MaterialFilter.h.
Constructor & Destructor Documentation
MaterialFilterOptions()
MaterialFilterOptions::MaterialFilterOptions ()
Definition at line 36 of file MaterialFilter.cpp.
References _includeFavorites, _includeFolders, _includeLegacy, _includeLibraries, _includeRecent, App::GetApplication(), App::Application::GetParameterGroupByPath(), and Init::param.
~MaterialFilterOptions()
virtual Materials::MaterialFilterOptions::~MaterialFilterOptions () virtual default
Member Function Documentation
includeEmptyFolders()
bool Materials::MaterialFilterOptions::includeEmptyFolders () const inline
Definition at line 100 of file MaterialFilter.h.
Referenced by Materials::MaterialLibrary::getMaterialTree().
includeEmptyLibraries()
bool Materials::MaterialFilterOptions::includeEmptyLibraries () const inline
Definition at line 113 of file MaterialFilter.h.
Referenced by MatGui::MaterialTreeWidget::fillMaterialTree().
includeFavorites()
bool Materials::MaterialFilterOptions::includeFavorites () const inline
Definition at line 74 of file MaterialFilter.h.
Referenced by MatGui::MaterialTreeWidget::fillMaterialTree().
includeLegacy()
bool Materials::MaterialFilterOptions::includeLegacy () const inline
Definition at line 126 of file MaterialFilter.h.
Referenced by Materials::MaterialLibrary::materialInTree().
includeRecent()
bool Materials::MaterialFilterOptions::includeRecent () const inline
Definition at line 87 of file MaterialFilter.h.
Referenced by MatGui::MaterialTreeWidget::fillMaterialTree().
setIncludeEmptyFolders()
void Materials::MaterialFilterOptions::setIncludeEmptyFolders (bool value) inline
Definition at line 104 of file MaterialFilter.h.
setIncludeEmptyLibraries()
void Materials::MaterialFilterOptions::setIncludeEmptyLibraries (bool value) inline
Definition at line 117 of file MaterialFilter.h.
setIncludeFavorites()
void Materials::MaterialFilterOptions::setIncludeFavorites (bool value) inline
Definition at line 78 of file MaterialFilter.h.
setIncludeLegacy()
void Materials::MaterialFilterOptions::setIncludeLegacy (bool legacy) inline
Definition at line 130 of file MaterialFilter.h.
setIncludeRecent()
void Materials::MaterialFilterOptions::setIncludeRecent (bool value) inline
Definition at line 91 of file MaterialFilter.h.
Member Data Documentation
_includeFavorites
bool Materials::MaterialFilterOptions::_includeFavorites protected
Definition at line 136 of file MaterialFilter.h.
Referenced by MaterialFilterOptions(), and Materials::MaterialFilterTreeWidgetOptions::MaterialFilterTreeWidgetOptions().
_includeFolders
bool Materials::MaterialFilterOptions::_includeFolders protected
Definition at line 138 of file MaterialFilter.h.
Referenced by MaterialFilterOptions(), and Materials::MaterialFilterTreeWidgetOptions::MaterialFilterTreeWidgetOptions().
_includeLegacy
bool Materials::MaterialFilterOptions::_includeLegacy protected
Definition at line 140 of file MaterialFilter.h.
Referenced by MaterialFilterOptions(), and Materials::MaterialFilterTreeWidgetOptions::MaterialFilterTreeWidgetOptions().
_includeLibraries
bool Materials::MaterialFilterOptions::_includeLibraries protected
Definition at line 139 of file MaterialFilter.h.
Referenced by MaterialFilterOptions(), and Materials::MaterialFilterTreeWidgetOptions::MaterialFilterTreeWidgetOptions().
_includeRecent
bool Materials::MaterialFilterOptions::_includeRecent protected
Definition at line 137 of file MaterialFilter.h.
Referenced by MaterialFilterOptions(), and Materials::MaterialFilterTreeWidgetOptions::MaterialFilterTreeWidgetOptions().
The documentation for this class was generated from the following files:
MaterialFilter.h
MaterialFilter.cpp