FreeCAD: ModelRefine::FaceAdjacencySplitter Class Reference
ModelRefine::FaceAdjacencySplitter Class Reference
#include <modelRefine.h>
Public Member Functions
FaceAdjacencySplitter (const TopoDS_Shell &shell)
void split (const FaceVectorType &facesIn)
std::size_t getGroupCount () const
const FaceVectorType & getGroup (const std::size_t &index) const
Detailed Description
Definition at line 148 of file modelRefine.h.
Constructor & Destructor Documentation
FaceAdjacencySplitter()
FaceAdjacencySplitter::FaceAdjacencySplitter (const TopoDS_Shell & shell)
Definition at line 184 of file modelRefine.cpp.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf::shell.
Member Function Documentation
getGroup()
const FaceVectorType& ModelRefine::FaceAdjacencySplitter::getGroup (const std::size_t & index) const inline
Definition at line 154 of file modelRefine.h.
Referenced by ModelRefine::FaceUniter::process().
getGroupCount()
std::size_t ModelRefine::FaceAdjacencySplitter::getGroupCount () const inline
Definition at line 153 of file modelRefine.h.
Referenced by ModelRefine::FaceUniter::process().
split()
void FaceAdjacencySplitter::split (const FaceVectorType & facesIn)
Definition at line 199 of file modelRefine.cpp.
Referenced by ModelRefine::FaceUniter::process().
The documentation for this class was generated from the following files:
modelRefine.h
modelRefine.cpp