FreeCAD: Gui::Dialog::DlgAddPropertyVarSet Class Reference
Gui::Dialog::DlgAddPropertyVarSet Class Reference
#include <DlgAddPropertyVarSet.h>
Public Slots
void valueChanged ()
Public Member Functions
DlgAddPropertyVarSet (QWidget *parent, ViewProviderVarSet *viewProvider)
~DlgAddPropertyVarSet () override
void changeEvent (QEvent *e) override
void accept () override
void reject () override
Static Public Attributes
static const std::string GROUP_BASE = "Base"
Detailed Description
Definition at line 86 of file DlgAddPropertyVarSet.h.
Constructor & Destructor Documentation
DlgAddPropertyVarSet()
DlgAddPropertyVarSet::DlgAddPropertyVarSet (QWidget * parent, ViewProviderVarSet * viewProvider)
Definition at line 53 of file DlgAddPropertyVarSet.cpp.
~DlgAddPropertyVarSet()
DlgAddPropertyVarSet::~DlgAddPropertyVarSet () override default
Member Function Documentation
accept()
void DlgAddPropertyVarSet::accept () override
Definition at line 528 of file DlgAddPropertyVarSet.cpp.
References COMMIT, App::GetApplication(), App::Application::GetParameterGroupByPath(), toolbit-attributes::group, ParameterGrp::SetASCII(), and Path.Post.scripts.grbl_post::type.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
changeEvent()
void DlgAddPropertyVarSet::changeEvent (QEvent * e) override
Definition at line 225 of file DlgAddPropertyVarSet.cpp.
References SCL.SimpleDataTypes::e.
reject()
void DlgAddPropertyVarSet::reject () override
Definition at line 549 of file DlgAddPropertyVarSet.cpp.
References ABORT.
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
valueChanged
void DlgAddPropertyVarSet::valueChanged () slot
Definition at line 501 of file DlgAddPropertyVarSet.cpp.
References Gui::PropertyEditor::PropertyItem::editorData(), and Gui::PropertyEditor::PropertyItem::setData().
Member Data Documentation
GROUP_BASE
const std::string DlgAddPropertyVarSet::GROUP_BASE = "Base" static
Definition at line 91 of file DlgAddPropertyVarSet.h.
The documentation for this class was generated from the following files:
DlgAddPropertyVarSet.h
DlgAddPropertyVarSet.cpp