FreeCAD: MeshCore::MeshFixDeformedFacets Class Reference
MeshCore::MeshFixDeformedFacets Class Reference
#include <Degeneration.h>
Public Member Functions
MeshFixDeformedFacets (MeshKernel &rclM, float fMinAngle, float fMaxAngle, float fSwapAngle, float fEps)
bool Fixup () override
Public Member Functions inherited from MeshCore::MeshValidation
MeshValidation (MeshKernel &rclB)
virtual ~MeshValidation ()=default
MeshValidation (const MeshValidation &)=delete
MeshValidation (MeshValidation &&)=delete
MeshValidation & operator= (const MeshValidation &)=delete
MeshValidation & operator= (MeshValidation &&)=delete
Additional Inherited Members
Protected Attributes inherited from MeshCore::MeshValidation
MeshKernel & _rclMesh
Detailed Description
The MeshFixDeformedFacets class tries to fix deformed facets by swapping the common edge with one of their neighbours.
Note
Degenerated facets are also deformed facet but this algorithm tries to fix deformed facets that or not degenerated. The removal of degenerated facets is done by MeshFixDegeneratedFacets.
See also
MeshEvalDeformedFacets
Author
Werner Mayer
Definition at line 439 of file Degeneration.h.
Constructor & Destructor Documentation
MeshFixDeformedFacets()
MeshCore::MeshFixDeformedFacets::MeshFixDeformedFacets (MeshKernel & rclM, float fMinAngle, float fMaxAngle, float fSwapAngle, float fEps) inline
Construction.
Definition at line 445 of file Degeneration.h.
Member Function Documentation
Fixup()
bool MeshFixDeformedFacets::Fixup () override virtual
Removes deformed facets.
Implements MeshCore::MeshValidation.
Definition at line 745 of file Degeneration.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::MeshFacet::_aulNeighbours, MeshCore::MeshValidation::_rclMesh, KDL::cos(), MeshCore::FACET_INDEX_MAX, MeshCore::MeshFacetIterator::GetReference(), SplineSurface::i, MeshCore::MeshFacetIterator::Init(), MeshCore::MeshGeomFacet::IsDegenerated(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), MeshCore::MeshFacetIterator::Position(), MeshCore::MeshTopoAlgorithm::ShouldSwapEdge(), MeshCore::MeshTopoAlgorithm::SwapEdge(), buildPsets::u, and TestSpreadsheet::v.
Referenced by Mesh::MeshObject::validateDeformations().
The documentation for this class was generated from the following files:
Degeneration.h
Degeneration.cpp