FreeCAD: Gui::PythonWrapper Class Reference
Gui::PythonWrapper Class Reference
#include <PythonWrapper.h>
Public Member Functions
PythonWrapper ()
bool loadCoreModule ()
bool loadGuiModule ()
bool loadWidgetsModule ()
bool loadPrintSupportModule ()
bool loadUiToolsModule ()
bool toCString (const Py::Object &, std::string &)
QObject * toQObject (const Py::Object &)
qsizetype toEnum (PyObject *pyPtr)
qsizetype toEnum (const Py::Object &pyobject)
Py::Object toStandardButton (qsizetype)
QGraphicsItem * toQGraphicsItem (PyObject *ptr)
QGraphicsItem * toQGraphicsItem (const Py::Object &pyObject)
QGraphicsObject * toQGraphicsObject (PyObject *pyPtr)
QGraphicsObject * toQGraphicsObject (const Py::Object &pyObject)
Py::Object fromQAction (QAction *)
Py::Object fromQPrinter (QPrinter *)
Py::Object fromQObject (QObject *, const char *className=nullptr)
Py::Object fromQWidget (QWidget *, const char *className=nullptr)
const char * getWrapperName (QObject *) const
Py::Object fromQImage (const QImage &)
QImage * toQImage (PyObject *pyobj)
Py::Object fromQIcon (const QIcon *)
QIcon * toQIcon (PyObject *pyobj)
Py::Object fromQDir (const QDir &)
QDir * toQDir (PyObject *pyobj)
Static Public Member Functions
static void createChildrenNameAttributes (PyObject *root, QObject *object)
static void setParent (PyObject *pyWdg, QObject *parent)
Detailed Description
Definition at line 45 of file PythonWrapper.h.
Constructor & Destructor Documentation
PythonWrapper()
PythonWrapper::PythonWrapper ()
Definition at line 549 of file PythonWrapper.cpp.
References SIM::Coin3D::Quarter::Quarter::init().
Member Function Documentation
createChildrenNameAttributes()
void PythonWrapper::createChildrenNameAttributes (PyObject * root, QObject * object) static
Definition at line 897 of file PythonWrapper.cpp.
References src.Mod.AddonManager.addonmanager_pyside_interface::QObject, and Gui::qt_identifyType().
Referenced by Gui::UiLoaderPy::load().
fromQAction()
Py::Object PythonWrapper::fromQAction (QAction * action)
Definition at line 733 of file PythonWrapper.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and Path.Post.scripts.grbl_post::type.
Referenced by Gui::CommandActionPy::getAction().
fromQDir()
Py::Object PythonWrapper::fromQDir (const QDir & dir)
Definition at line 709 of file PythonWrapper.cpp.
References Path.Post.scripts.grbl_post::type.
fromQIcon()
Py::Object PythonWrapper::fromQIcon (const QIcon * icon)
Create a Python wrapper for the icon. The icon must be created on the heap and the Python wrapper takes ownership of it.
Definition at line 685 of file PythonWrapper.cpp.
References Path.Post.scripts.grbl_post::type.
Referenced by Gui::ApplicationPy::sGetIcon().
fromQImage()
Py::Object PythonWrapper::fromQImage (const QImage & img)
Definition at line 662 of file PythonWrapper.cpp.
References Path.Post.scripts.grbl_post::type.
Referenced by Gui::View3DInventorViewerPy::grabFramebuffer().
fromQObject()
Py::Object PythonWrapper::fromQObject (QObject * object, const char * className = nullptr)
Definition at line 788 of file PythonWrapper.cpp.
References Path.Post.scripts.grbl_post::type.
fromQPrinter()
Py::Object PythonWrapper::fromQPrinter (QPrinter * printer)
Definition at line 758 of file PythonWrapper.cpp.
References Path.Post.scripts.grbl_post::type.
Referenced by Gui::MDIViewPyWrapImp::printDocument().
fromQWidget()
Py::Object PythonWrapper::fromQWidget (QWidget * widget, const char * className = nullptr)
Definition at line 818 of file PythonWrapper.cpp.
References Path.Post.scripts.grbl_post::type.
Referenced by Gui::MainWindowPy::createWrapper(), Gui::Dialog::TaskPlacementPy::getattr(), Gui::TaskView::TaskDialogPy::getDialogContent(), Gui::View3DInventorPy::graphicsView(), Gui::UiLoaderPy::load(), Gui::TaskView::TaskDialogPython::modifyStandardButtons(), and Gui::ViewProviderFeaturePythonImp::setupContextMenu().
getWrapperName()
const char * PythonWrapper::getWrapperName (QObject * obj) const
Definition at line 845 of file PythonWrapper.cpp.
References femtools.tokrules::names.
Referenced by Gui::UiLoaderPy::load().
loadCoreModule()
bool PythonWrapper::loadCoreModule ()
Definition at line 872 of file PythonWrapper.cpp.
References Gui::loadPySideModule(), and SbkPySide_QtCoreTypes.
Referenced by Gui::UiLoaderPy::addPluginPath(), Gui::MainWindowPy::createWrapper(), Gui::UiLoaderPy::load(), Gui::Dialog::PreferencePagePython::PreferencePagePython(), Gui::UiLoaderPy::setWorkingDirectory(), and Gui::TaskView::TaskWatcherPython::TaskWatcherPython().
loadGuiModule()
bool PythonWrapper::loadGuiModule ()
Definition at line 877 of file PythonWrapper.cpp.
References Gui::loadPySideModule(), and SbkPySide_QtGuiTypes.
Referenced by Gui::MainWindowPy::createWrapper(), Gui::ViewProviderFeaturePythonImp::getIcon(), Gui::View3DInventorViewerPy::grabFramebuffer(), Gui::UiLoaderPy::load(), Gui::TaskView::TaskDialogPython::modifyStandardButtons(), Gui::ViewProviderFeaturePythonImp::setupContextMenu(), and Gui::ApplicationPy::sGetIcon().
loadPrintSupportModule()
bool PythonWrapper::loadPrintSupportModule ()
Definition at line 887 of file PythonWrapper.cpp.
References Gui::loadPySideModule(), and SbkPySide_QtPrintSupportTypes.
Referenced by Gui::MDIViewPyWrapImp::printDocument().
loadUiToolsModule()
bool PythonWrapper::loadUiToolsModule ()
Definition at line 892 of file PythonWrapper.cpp.
References Gui::loadPySideModule(), and SbkPySide_QtUiToolsTypes.
loadWidgetsModule()
bool PythonWrapper::loadWidgetsModule ()
Definition at line 882 of file PythonWrapper.cpp.
References Gui::loadPySideModule(), and SbkPySide_QtWidgetsTypes.
Referenced by Gui::MainWindowPy::createWrapper(), Gui::ExpressionBindingPy::ExpressionBindingPy(), Gui::CommandActionPy::getAction(), Gui::Dialog::TaskPlacementPy::getattr(), Gui::TaskView::TaskDialogPy::getDialogContent(), Gui::ViewProviderFeaturePythonImp::getIcon(), Gui::TaskView::TaskDialogPython::getStandardButtons(), Gui::View3DInventorPy::graphicsView(), Gui::UiLoaderPy::load(), Gui::TaskView::TaskDialogPython::modifyStandardButtons(), Gui::ViewProviderFeaturePythonImp::setupContextMenu(), Gui::ApplicationPy::sGetIcon(), and Gui::MDIViewPyWrapImp::widget().
setParent()
void PythonWrapper::setParent (PyObject * pyWdg, QObject * parent) static
Definition at line 931 of file PythonWrapper.cpp.
References Init::parent.
Referenced by Gui::UiLoaderPy::load().
toCString()
bool PythonWrapper::toCString (const Py::Object & pyobject, std::string & str)
Definition at line 560 of file PythonWrapper.cpp.
References ArchCommands::check(), toolbit-attributes::s, Path.Post.scripts.refactored_centroid_post::str, and ArchBuildingPart::unicode.
Referenced by Gui::UiLoaderPy::addPluginPath(), Gui::UiLoaderPy::load(), and Gui::UiLoaderPy::setWorkingDirectory().
toEnum() [1/2]
qsizetype PythonWrapper::toEnum (const Py::Object & pyobject)
Definition at line 618 of file PythonWrapper.cpp.
References toEnum().
toEnum() [2/2]
qsizetype PythonWrapper::toEnum (PyObject * pyPtr)
Definition at line 606 of file PythonWrapper.cpp.
References SCL.SimpleDataTypes::e.
Referenced by Gui::TaskView::TaskDialogPython::getStandardButtons(), and toEnum().
toQDir()
QDir * PythonWrapper::toQDir (PyObject * pyobj)
Definition at line 728 of file PythonWrapper.cpp.
toQGraphicsItem() [1/2]
QGraphicsItem * PythonWrapper::toQGraphicsItem (const Py::Object & pyObject)
Definition at line 647 of file PythonWrapper.cpp.
References toQGraphicsItem().
toQGraphicsItem() [2/2]
QGraphicsItem * PythonWrapper::toQGraphicsItem (PyObject * ptr)
Definition at line 642 of file PythonWrapper.cpp.
Referenced by toQGraphicsItem().
toQGraphicsObject() [1/2]
QGraphicsObject * PythonWrapper::toQGraphicsObject (const Py::Object & pyObject)
Definition at line 657 of file PythonWrapper.cpp.
References toQGraphicsObject().
toQGraphicsObject() [2/2]
QGraphicsObject * PythonWrapper::toQGraphicsObject (PyObject * pyPtr)
Definition at line 652 of file PythonWrapper.cpp.
Referenced by toQGraphicsObject().
toQIcon()
QIcon * PythonWrapper::toQIcon (PyObject * pyobj)
Definition at line 704 of file PythonWrapper.cpp.
Referenced by Gui::ViewProviderFeaturePythonImp::getIcon().
toQImage()
QImage * PythonWrapper::toQImage (PyObject * pyobj)
Definition at line 680 of file PythonWrapper.cpp.
toQObject()
QObject * PythonWrapper::toQObject (const Py::Object & pyobject)
Definition at line 582 of file PythonWrapper.cpp.
Referenced by Gui::ExpressionBindingPy::ExpressionBindingPy(), Gui::UiLoaderPy::load(), Gui::Dialog::PreferencePagePython::PreferencePagePython(), Gui::TaskView::TaskWatcherPython::TaskWatcherPython(), and Gui::MDIViewPyWrapImp::widget().
toStandardButton()
Py::Object PythonWrapper::toStandardButton (qsizetype value)
Definition at line 631 of file PythonWrapper.cpp.
References SCL.SimpleDataTypes::e.
Referenced by Gui::TaskView::TaskDialogPython::clicked().
The documentation for this class was generated from the following files:
PythonWrapper.h
PythonWrapper.cpp