FreeCAD: SketcherSettings.cpp File Reference
SketcherSettings.cpp File Reference
#include "PreCompiled.h"
#include <QMessageBox>
#include <QPainter>
#include <QPixmap>
#include <App/Application.h>
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Gui/Command.h>
#include "SketcherSettings.h"
#include "ui_SketcherSettings.h"
#include "ui_SketcherSettingsAppearance.h"
#include "ui_SketcherSettingsDisplay.h"
#include "ui_SketcherSettingsGrid.h"
#include "moc_SketcherSettings.cpp"
Functions
QList< int > getPenStyles ()
const QVector< qreal > binaryPatternToDashPattern (int binaryPattern)
Function Documentation
binaryPatternToDashPattern()
const QVector<qreal> binaryPatternToDashPattern (int binaryPattern)
Definition at line 59 of file SketcherSettings.cpp.
References src.Mod.AddonManager.NetworkManager::count, and SplineSurface::i.
Referenced by SketcherGui::SketcherSettingsAppearance::SketcherSettingsAppearance(), and SketcherGui::SketcherSettingsGrid::SketcherSettingsGrid().
getPenStyles()
QList<int> getPenStyles ()
Definition at line 46 of file SketcherSettings.cpp.
Referenced by SketcherGui::SketcherSettingsAppearance::SketcherSettingsAppearance(), and SketcherGui::SketcherSettingsGrid::SketcherSettingsGrid().