FreeCAD: Import::ImpExpDxfWrite Class Reference
Import::ImpExpDxfWrite Class Reference
#include <ImpExpDxf.h>
Public Member Functions
ImpExpDxfWrite (std::string filepath)
ImpExpDxfWrite (const ImpExpDxfWrite &)=delete
ImpExpDxfWrite (const ImpExpDxfWrite &&)=delete
ImpExpDxfWrite & operator= (const ImpExpDxfWrite &)=delete
ImpExpDxfWrite & operator= (const ImpExpDxfWrite &&)=delete
~ImpExpDxfWrite ()
void exportShape (TopoDS_Shape input)
std::string getOptionSource ()
void setOptionSource (const std::string &s)
void setOptions ()
void exportText (const char *text, Base::Vector3d position1, Base::Vector3d position2, double size, int just)
void exportLinearDim (Base::Vector3d textLocn, Base::Vector3d lineLocn, Base::Vector3d extLine1Start, Base::Vector3d extLine2Start, char *dimText, int type)
void exportAngularDim (Base::Vector3d textLocn, Base::Vector3d lineLocn, Base::Vector3d extLine1End, Base::Vector3d extLine2End, Base::Vector3d apexPoint, char *dimText)
void exportRadialDim (Base::Vector3d centerPoint, Base::Vector3d textLocn, Base::Vector3d arcPoint, char *dimText)
void exportDiametricDim (Base::Vector3d textLocn, Base::Vector3d arcPoint1, Base::Vector3d arcPoint2, char *dimText)
Public Member Functions inherited from CDxfWrite
CDxfWrite (const char *filepath)
CDxfWrite (const CDxfWrite &)=delete
CDxfWrite (const CDxfWrite &&)=delete
CDxfWrite & operator= (const CDxfWrite &)=delete
CDxfWrite & operator= (const CDxfWrite &&)=delete
~CDxfWrite ()
void init ()
void endRun ()
assemble pieces into output file
bool Failed () const
std::string getLayerName ()
void setLayerName (std::string name)
void setVersion (int version)
void setPolyOverride (bool setting)
void addBlockName (const std::string &name, const std::string &blkRecordHandle)
void writeLine (const double *start, const double *end)
void writePoint (const double *)
void writeArc (const double *start, const double *end, const double *center, bool dir)
void writeEllipse (const double *center, double major_radius, double minor_radius, double rotation, double start_angle, double end_angle, bool endIsCW)
void writeCircle (const double *center, double radius)
void writeSpline (const SplineDataOut &sd)
void writeLWPolyLine (const LWPolyDataOut &pd)
void writePolyline (const LWPolyDataOut &pd)
void writeVertex (double x, double y, double z)
void writeText (const char *text, const double *location1, const double *location2, double height, int horizJust)
void writeLinearDim (const double *textMidPoint, const double *lineDefPoint, const double *extLine1, const double *extLine2, const char *dimText, int type)
void writeLinearDimBlock (const double *textMidPoint, const double *lineDefPoint, const double *extLine1, const double *extLine2, const char *dimText, int type)
void writeAngularDim (const double *textMidPoint, const double *lineDefPoint, const double *startExt1, const double *endExt1, const double *startExt2, const double *endExt2, const char *dimText)
void writeAngularDimBlock (const double *textMidPoint, const double *lineDefPoint, const double *startExt1, const double *endExt1, const double *startExt2, const double *endExt2, const char *dimText)
void writeRadialDim (const double *centerPoint, const double *textMidPoint, const double *arcPoint, const char *dimText)
void writeRadialDimBlock (const double *centerPoint, const double *textMidPoint, const double *arcPoint, const char *dimText)
void writeDiametricDim (const double *textMidPoint, const double *arcPoint1, const double *arcPoint2, const char *dimText)
void writeDiametricDimBlock (const double *textMidPoint, const double *arcPoint1, const double *arcPoint2, const char *dimText)
void writeDimBlockPreamble ()
void writeBlockTrailer ()
void writeHeaderSection ()
void writeTablesSection ()
void writeBlocksSection ()
void writeEntitiesSection ()
void writeObjectsSection ()
void writeClassesSection ()
void makeLayerTable ()
void makeBlockRecordTableHead ()
void makeBlockRecordTableBody ()
void makeBlockSectionHead ()
Static Public Member Functions
static bool gp_PntEqual (gp_Pnt p1, gp_Pnt p2)
static bool gp_PntCompare (gp_Pnt p1, gp_Pnt p2)
Protected Member Functions
void exportCircle (BRepAdaptor_Curve &c)
void exportEllipse (BRepAdaptor_Curve &c)
void exportArc (BRepAdaptor_Curve &c)
void exportEllipseArc (BRepAdaptor_Curve &c)
void exportBSpline (BRepAdaptor_Curve &c)
void exportBCurve (BRepAdaptor_Curve &c)
void exportLine (BRepAdaptor_Curve &c)
void exportLWPoly (BRepAdaptor_Curve &c)
void exportPolyline (BRepAdaptor_Curve &c)
Protected Member Functions inherited from CDxfWrite
void putLine (const Base::Vector3d &start, const Base::Vector3d &end, std::ostringstream *outStream, const std::string &handle, const std::string &ownerHandle)
void putText (const char *text, const Base::Vector3d &location1, const Base::Vector3d &location2, double height, int horizJust, std::ostringstream *outStream, const std::string &handle, const std::string &ownerHandle)
void putArrow (Base::Vector3d &arrowPos, Base::Vector3d &barb1Pos, Base::Vector3d &barb2Pos, std::ostringstream *outStream, const std::string &handle, const std::string &ownerHandle)
std::string getPlateFile (std::string fileSpec)
copy boiler plate file
void setDataDir (const std::string &dirName)
std::string getHandle ()
std::string getEntityHandle ()
std::string getLayerHandle ()
std::string getBlockHandle ()
std::string getBlkRecordHandle ()
Protected Attributes
double optionMaxLength
bool optionPolyLine
bool optionExpPoints
Protected Attributes inherited from CDxfWrite
std::string m_optionSource
int m_version
int m_handle
int m_entityHandle
int m_layerHandle
int m_blockHandle
int m_blkRecordHandle
bool m_polyOverride
std::string m_saveModelSpaceHandle
std::string m_savePaperSpaceHandle
std::string m_saveBlockRecordTableHandle
std::string m_saveBlkRecordHandle
std::string m_currentBlock
std::string m_dataDir
std::string m_layerName
std::vector< std::string > m_layerList
std::vector< std::string > m_blockList
std::vector< std::string > m_blkRecordList
Additional Inherited Members
Static Protected Member Functions inherited from CDxfWrite
static Base::Vector3d toVector3d (const double *coordinatesXYZ)
Detailed Description
Definition at line 352 of file ImpExpDxf.h.
Constructor & Destructor Documentation
ImpExpDxfWrite() [1/3]
ImpExpDxfWrite::ImpExpDxfWrite (std::string filepath) explicit
Definition at line 770 of file ImpExpDxf.cpp.
References setOptions(), and setOptionSource().
ImpExpDxfWrite() [2/3]
Import::ImpExpDxfWrite::ImpExpDxfWrite (const ImpExpDxfWrite &) delete
ImpExpDxfWrite() [3/3]
Import::ImpExpDxfWrite::ImpExpDxfWrite (const ImpExpDxfWrite &&) delete
~ImpExpDxfWrite()
ImpExpDxfWrite::~ImpExpDxfWrite () default
Member Function Documentation
exportAngularDim()
void ImpExpDxfWrite::exportAngularDim (Base::Vector3d textLocn, Base::Vector3d lineLocn, Base::Vector3d extLine1End, Base::Vector3d extLine2End, Base::Vector3d apexPoint, char * dimText)
Definition at line 1247 of file ImpExpDxf.cpp.
References CDxfWrite::writeAngularDim(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
exportArc()
void ImpExpDxfWrite::exportArc (BRepAdaptor_Curve & c) protected
Definition at line 986 of file ImpExpDxf.cpp.
References a, SCL.SimpleDataTypes::c, exportCSG::center(), SCL.SimpleDataTypes::e, SCL.SimpleDataTypes::f, gPntToTuple(), RobotExample::l, test::m, buildPsets::p, toolbit-attributes::s, draftgeoutils.general::v1(), and CDxfWrite::writeArc().
Referenced by exportShape().
exportBCurve()
void ImpExpDxfWrite::exportBCurve (BRepAdaptor_Curve & c) protected
Definition at line 1134 of file ImpExpDxf.cpp.
References SCL.SimpleDataTypes::c, Base::Console(), and Base::ConsoleSingleton::Message().
Referenced by exportShape().
exportBSpline()
void ImpExpDxfWrite::exportBSpline (BRepAdaptor_Curve & c) protected
Definition at line 1052 of file ImpExpDxf.cpp.
References SCL.SimpleDataTypes::c, Base::Console(), SplineDataOut::control, SplineDataOut::control_points, SplineDataOut::degree, SplineDataOut::endtan, SCL.SimpleDataTypes::f, SplineDataOut::flag, gPntTopoint3D(), Handle(), SplineSurface::i, SplineDataOut::knot, SplineDataOut::knots, RobotExample::l, test::m, Base::ConsoleSingleton::Message(), SplineDataOut::norm, buildPsets::p, toolbit-attributes::s, SplineDataOut::starttan, CDxfWrite::writeSpline(), point3D::x, point3D::y, and point3D::z.
Referenced by exportShape().
exportCircle()
void ImpExpDxfWrite::exportCircle (BRepAdaptor_Curve & c) protected
Definition at line 955 of file ImpExpDxf.cpp.
References SCL.SimpleDataTypes::c, exportCSG::center(), gPntToTuple(), buildPsets::p, and CDxfWrite::writeCircle().
Referenced by exportShape().
exportDiametricDim()
void ImpExpDxfWrite::exportDiametricDim (Base::Vector3d textLocn, Base::Vector3d arcPoint1, Base::Vector3d arcPoint2, char * dimText)
Definition at line 1297 of file ImpExpDxf.cpp.
References CDxfWrite::writeDiametricDim(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
exportEllipse()
void ImpExpDxfWrite::exportEllipse (BRepAdaptor_Curve & c) protected
Definition at line 967 of file ImpExpDxf.cpp.
References SCL.SimpleDataTypes::c, exportCSG::center(), gPntToTuple(), buildPsets::p, and CDxfWrite::writeEllipse().
Referenced by exportShape().
exportEllipseArc()
void ImpExpDxfWrite::exportEllipseArc (BRepAdaptor_Curve & c) protected
Definition at line 1012 of file ImpExpDxf.cpp.
References a, SCL.SimpleDataTypes::c, exportCSG::center(), SCL.SimpleDataTypes::e, SCL.SimpleDataTypes::f, Base::fmod(), gPntToTuple(), RobotExample::l, test::m, M_PI, buildPsets::p, toolbit-attributes::s, draftgeoutils.general::v1(), and CDxfWrite::writeEllipse().
Referenced by exportShape().
exportLine()
void ImpExpDxfWrite::exportLine (BRepAdaptor_Curve & c) protected
Definition at line 1140 of file ImpExpDxf.cpp.
References SCL.SimpleDataTypes::c, SCL.SimpleDataTypes::e, SCL.SimpleDataTypes::f, gPntToTuple(), RobotExample::l, toolbit-attributes::s, and CDxfWrite::writeLine().
Referenced by exportShape().
exportLinearDim()
void ImpExpDxfWrite::exportLinearDim (Base::Vector3d textLocn, Base::Vector3d lineLocn, Base::Vector3d extLine1Start, Base::Vector3d extLine2Start, char * dimText, int type)
Definition at line 1221 of file ImpExpDxf.cpp.
References Path.Post.scripts.grbl_post::type, CDxfWrite::writeLinearDim(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
exportLWPoly()
void ImpExpDxfWrite::exportLWPoly (BRepAdaptor_Curve & c) protected
Definition at line 1153 of file ImpExpDxf.cpp.
References SCL.SimpleDataTypes::c, LWPolyDataOut::Elev, LWPolyDataOut::Extr, LWPolyDataOut::Flag, gPntTopoint3D(), SplineSurface::i, LWPolyDataOut::nVert, optionMaxLength, buildPsets::p, LWPolyDataOut::Thick, LWPolyDataOut::Verts, CDxfWrite::writeLWPolyLine(), point3D::x, point3D::y, and point3D::z.
Referenced by exportShape().
exportPolyline()
void ImpExpDxfWrite::exportPolyline (BRepAdaptor_Curve & c) protected
Definition at line 1178 of file ImpExpDxf.cpp.
References SCL.SimpleDataTypes::c, LWPolyDataOut::Elev, LWPolyDataOut::Extr, LWPolyDataOut::Flag, gPntTopoint3D(), SplineSurface::i, LWPolyDataOut::nVert, optionMaxLength, buildPsets::p, LWPolyDataOut::Thick, LWPolyDataOut::Verts, CDxfWrite::writePolyline(), point3D::x, point3D::y, and point3D::z.
Referenced by exportShape().
exportRadialDim()
void ImpExpDxfWrite::exportRadialDim (Base::Vector3d centerPoint, Base::Vector3d textLocn, Base::Vector3d arcPoint, char * dimText)
Definition at line 1277 of file ImpExpDxf.cpp.
References exportCSG::center(), CDxfWrite::writeRadialDim(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
exportShape()
void ImpExpDxfWrite::exportShape (TopoDS_Shape input)
Definition at line 791 of file ImpExpDxf.cpp.
References Base::Console(), SCL.SimpleDataTypes::e, exportArc(), exportBCurve(), exportBSpline(), exportCircle(), exportEllipse(), exportEllipseArc(), exportLine(), exportLWPoly(), exportPolyline(), SCL.SimpleDataTypes::f, gp_PntCompare(), gp_PntEqual(), gPntToTuple(), SplineSurface::i, RobotExample::l, CDxfWrite::m_polyOverride, CDxfWrite::m_version, optionExpPoints, optionPolyLine, buildPsets::p, TestSpreadsheet::v, Base::ConsoleSingleton::Warning(), and CDxfWrite::writePoint().
exportText()
void ImpExpDxfWrite::exportText (const char * text, Base::Vector3d position1, Base::Vector3d position2, double size, int just)
Definition at line 1203 of file ImpExpDxf.cpp.
References CDxfWrite::writeText(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
getOptionSource()
std::string Import::ImpExpDxfWrite::getOptionSource () inline
Definition at line 363 of file ImpExpDxf.h.
Referenced by setOptions().
gp_PntCompare()
bool ImpExpDxfWrite::gp_PntCompare (gp_Pnt p1, gp_Pnt p2) static
Definition at line 937 of file ImpExpDxf.cpp.
References result.
Referenced by exportShape().
gp_PntEqual()
bool ImpExpDxfWrite::gp_PntEqual (gp_Pnt p1, gp_Pnt p2) static
Definition at line 927 of file ImpExpDxf.cpp.
References result.
Referenced by exportShape().
operator=() [1/2]
ImpExpDxfWrite& Import::ImpExpDxfWrite::operator= (const ImpExpDxfWrite &&) delete
operator=() [2/2]
ImpExpDxfWrite& Import::ImpExpDxfWrite::operator= (const ImpExpDxfWrite &) delete
setOptions()
void ImpExpDxfWrite::setOptions ()
Definition at line 779 of file ImpExpDxf.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetFloat(), ParameterGrp::GetInt(), getOptionSource(), App::Application::GetParameterGroupByPath(), App::Application::getResourceDir(), CDxfWrite::m_polyOverride, CDxfWrite::m_version, optionExpPoints, optionMaxLength, optionPolyLine, and CDxfWrite::setDataDir().
Referenced by ImpExpDxfWrite().
setOptionSource()
void Import::ImpExpDxfWrite::setOptionSource (const std::string & s) inline
Definition at line 367 of file ImpExpDxf.h.
References toolbit-attributes::s.
Referenced by ImpExpDxfWrite().
Member Data Documentation
optionExpPoints
bool Import::ImpExpDxfWrite::optionExpPoints protected
Definition at line 417 of file ImpExpDxf.h.
Referenced by exportShape(), and setOptions().
optionMaxLength
double Import::ImpExpDxfWrite::optionMaxLength protected
Definition at line 415 of file ImpExpDxf.h.
Referenced by exportLWPoly(), exportPolyline(), and setOptions().
optionPolyLine
bool Import::ImpExpDxfWrite::optionPolyLine protected
Definition at line 416 of file ImpExpDxf.h.
Referenced by exportShape(), and setOptions().
The documentation for this class was generated from the following files:
ImpExpDxf.h
ImpExpDxf.cpp