FreeCAD: SketcherGui::SketchSelection Struct Reference
SketcherGui::SketchSelection Struct Reference
Classes
struct SketchSelectionItem
Public Types
enum GeoType { Point, Line, Circle, Arc }
Public Member Functions
int setUp ()
Public Attributes
std::list< SketchSelectionItem > Items
QString ErrorMsg
Detailed Description
Definition at line 807 of file CommandConstraints.cpp.
Member Enumeration Documentation
GeoType
enum SketcherGui::SketchSelection::GeoType
Enumerator
Point
Line
Circle
Arc
Definition at line 809 of file CommandConstraints.cpp.
Member Function Documentation
setUp()
int SketcherGui::SketchSelection::setUp ()
Definition at line 827 of file CommandConstraints.cpp.
References Part::AttachExtension::AttachmentSupport, UtilsAssembly::getObject(), Gui::SelectionSingleton::getSelectionEx(), App::PropertyLinkSubList::getValue(), Path.Dressup.Utils::selection(), and Gui::Selection().
Member Data Documentation
ErrorMsg
QString SketcherGui::SketchSelection::ErrorMsg
Definition at line 824 of file CommandConstraints.cpp.
Items
std::list<SketchSelectionItem> SketcherGui::SketchSelection::Items
Definition at line 823 of file CommandConstraints.cpp.
The documentation for this struct was generated from the following file:
CommandConstraints.cpp