FreeCAD: AppMaterial.cpp File Reference
AppMaterial.cpp File Reference
#include "PreCompiled.h"
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/PyObjectBase.h>
#include <App/CleanupProcess.h>
#include "MaterialFilterPy.h"
#include "MaterialLoader.h"
#include "MaterialManagerPy.h"
#include "MaterialPy.h"
#include "ModelManagerPy.h"
#include "ModelPropertyPy.h"
#include "ModelPy.h"
#include "UUIDsPy.h"
#include "PropertyMaterial.h"
Classes
class Materials::Module
Namespaces
Materials
Functions
PyObject * Materials::initModule ()
PyMOD_INIT_FUNC (Materials)
Function Documentation
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (Materials)
Definition at line 65 of file AppMaterial.cpp.
References Materials::MaterialManager::cleanup(), Materials::ModelManager::cleanup(), Base::Console(), Materials::initModule(), Base::ConsoleSingleton::Log(), src.Mod.PartDesign.fcgear.svggear::module, and App::CleanupProcess::registerCleanup().