FreeCAD: Surface::BlendCurve Class Reference
Surface::BlendCurve Class Reference
#include <BlendCurve.h>
Public Member Functions
BlendCurve ()=default
BlendCurve (const std::vector< BlendPoint > &blendPointsList)
~BlendCurve ()=default
Handle (Geom_BezierCurve) compute()
void setSize (int, double, bool)
Public Attributes
std::vector< BlendPoint > blendPoints
Detailed Description
Create a BezierCurve interpolating a list of BlendPoints
Definition at line 55 of file BlendCurve.h.
Constructor & Destructor Documentation
BlendCurve() [1/2]
Surface::BlendCurve::BlendCurve () default
BlendCurve() [2/2]
BlendCurve::BlendCurve (const std::vector< BlendPoint > & blendPointsList) explicit
Constructor
Parameters
std::vector<BlendPoint>
Definition at line 42 of file BlendCurve.cpp.
References blendPoints.
~BlendCurve()
Surface::BlendCurve::~BlendCurve () default
Member Function Documentation
Handle()
Surface::BlendCurve::Handle (Geom_BezierCurve)
Perform the interpolate algorithm
Returns
the BezierCurve
Referenced by Handle().
setSize()
void BlendCurve::setSize (int i, double f, bool relative)
Set the size of the first derivative of a BlendPoint
Parameters
int index of the BlendPoint to modify
double new size
bool interpret new size relative to chordlength
Definition at line 139 of file BlendCurve.cpp.
References blendPoints, KDL::diff(), SCL.SimpleDataTypes::e, SCL.SimpleDataTypes::f, SplineSurface::i, and Base::PyExc_FC_CADKernelError.
Referenced by Surface::FeatureBlendCurve::execute().
Member Data Documentation
blendPoints
std::vector<BlendPoint> Surface::BlendCurve::blendPoints
Definition at line 78 of file BlendCurve.h.
Referenced by BlendCurve(), Handle(), and setSize().
The documentation for this class was generated from the following files:
BlendCurve.h
BlendCurve.cpp