FreeCAD: PartDesignGui Namespace Reference
PartDesignGui Namespace Reference
Classes
class CombineSelectionFilterGates
class ComboLinks
The ComboLinks class is a helper class that binds to a combo box and provides an interface to add links, retrieve links and select items by link value.
class DlgActiveBody
class Module
class NoDependentsSelection
class ReferenceSelection
class SketchWorkflow
class StateHandlerTaskPipe
Convenience class to maintain states between the various task boxes for pipe.
class TaskBooleanParameters
class TaskBoxPrimitives
class TaskChamferParameters
class TaskDatumParameters
class TaskDlgBooleanParameters
simulation dialog for the TaskView
class TaskDlgChamferParameters
simulation dialog for the TaskView
class TaskDlgDatumParameters
simulation dialog for the TaskView
class TaskDlgDraftParameters
simulation dialog for the TaskView
class TaskDlgDressUpParameters
simulation dialog for the TaskView
class TaskDlgExtrudeParameters
class TaskDlgFeatureParameters
A common base for sketch based, dressup and other solid parameters dialogs.
class TaskDlgFeaturePick
simulation dialog for the TaskView
class TaskDlgFilletParameters
simulation dialog for the TaskView
class TaskDlgGrooveParameters
class TaskDlgHelixParameters
simulation dialog for the TaskView
class TaskDlgHoleParameters
simulation dialog for the TaskView
class TaskDlgLinearPatternParameters
simulation dialog for the TaskView
class TaskDlgLoftParameters
simulation dialog for the TaskView
class TaskDlgMirroredParameters
simulation dialog for the TaskView
class TaskDlgMultiTransformParameters
simulation dialog for the TaskView
class TaskDlgPadParameters
simulation dialog for the TaskView
class TaskDlgPipeParameters
simulation dialog for the TaskView
class TaskDlgPocketParameters
simulation dialog for the TaskView
class TaskDlgPolarPatternParameters
simulation dialog for the TaskView
class TaskDlgRevolutionParameters
class TaskDlgScaledParameters
simulation dialog for the TaskView
class TaskDlgShapeBinder
simulation dialog for the TaskView
class TaskDlgSketchBasedParameters
class TaskDlgThicknessParameters
simulation dialog for the TaskView
class TaskDlgTransformedParameters
simulation dialog for the TaskView
class TaskDraftParameters
class TaskDressUpParameters
class TaskExtrudeParameters
class TaskFeatureParameters
Convenience class to collect common methods for all SketchBased features.
class TaskFeaturePick
class TaskFilletParameters
class TaskHelixParameters
class TaskHoleParameters
class TaskLinearPatternParameters
class TaskLoftParameters
class TaskMirroredParameters
class TaskMultiTransformParameters
class TaskPadParameters
class TaskPipeOrientation
class TaskPipeParameters
class TaskPipeScaling
class TaskPocketParameters
class TaskPolarPatternParameters
class TaskPrimitiveParameters
class TaskRevolutionParameters
class TaskScaledParameters
class TaskShapeBinder
class TaskSketchBasedParameters
Convenience class to collect common methods for all SketchBased features.
class TaskThicknessParameters
class TaskTransformedMessages
class TaskTransformedParameters
class ViewProvider
class ViewProviderAddSub
class ViewProviderBase
class ViewProviderBody
class ViewProviderBoolean
class ViewProviderChamfer
class ViewProviderDatum
class ViewProviderDatumCoordinateSystem
class ViewProviderDatumLine
class ViewProviderDatumPlane
class ViewProviderDatumPoint
class ViewProviderDraft
class ViewProviderDressUp
class ViewProviderExtrude
class ViewProviderFillet
class ViewProviderGroove
class ViewProviderHelix
class ViewProviderHole
class ViewProviderLinearPattern
class ViewProviderLoft
class ViewProviderMainPart
class ViewProviderMirrored
class ViewProviderMultiTransform
class ViewProviderPad
class ViewProviderPipe
class ViewProviderPocket
class ViewProviderPolarPattern
class ViewProviderPrimitive
class ViewProviderRevolution
class ViewProviderScaled
class ViewProviderShapeBinder
class ViewProviderSketchBased
class ViewProviderSubShapeBinder
class ViewProviderThickness
class ViewProviderTransformed
class Workbench
class WorkflowManager
Typedefs
using ViewProviderPython = Gui::ViewProviderFeaturePythonT< ViewProvider >
using ViewProviderSubShapeBinderPython = Gui::ViewProviderFeaturePythonT< ViewProviderSubShapeBinder >
Enumerations
enum AllowSelection {
AllowSelection::NONE = 0, AllowSelection::EDGE = 1 << 0, AllowSelection::FACE = 1 << 1, AllowSelection::PLANAR = 1 << 2,
AllowSelection::CIRCLE = 1 << 3, AllowSelection::POINT = 1 << 4, AllowSelection::OTHERBODY = 1 << 5, AllowSelection::WHOLE = 1 << 6
}
enum Workflow { Workflow::Undetermined = 0, Workflow::Legacy = 1<<0, Workflow::Modern = 1<<1 }
Functions
PyObject * initModule ()
App::Part * assertActivePart ()
Returns active part, if there is no such, creates a new part, if it fails, shows a message.
bool getReferencedSelection (const App::DocumentObject *thisObj, const Gui::SelectionChanges &msg, App::DocumentObject *&selObj, std::vector< std::string > &selSub)
Extract reference from Selection.
QString getRefStr (const App::DocumentObject *obj, const std::vector< std::string > &sub)
Return reference as string for UI elements (format <obj>:<subelement>
std::string buildLinkSubPythonStr (const App::DocumentObject *obj, const std::vector< std::string > &subs)
Return reference as string for python in the format (<obj> ["sub1", "sub2", ...])
std::string buildLinkSingleSubPythonStr (const App::DocumentObject *obj, const std::vector< std::string > &subs)
Return reference as string for python in the format (<obj> ["sub"?])
std::string buildLinkListPythonStr (const std::vector< App::DocumentObject * > &objs)
Return reference as string for python in the format [obj1, obj2, ...,].
std::string buildLinkSubListPythonStr (const std::vector< App::DocumentObject * > &objs, const std::vector< std::string > &subs)
Returns sub reference list as a python string in the format [(obj1,"sub1"),(obj2,"sub2"),...].
App::DocumentObject * getParent (App::DocumentObject *obj, std::string &subname)
bool setEdit (App::DocumentObject *obj, PartDesign::Body *body=nullptr)
Activate edit mode of the given object.
PartDesign::Body * getBody (bool messageIfNot, bool autoActivate, bool assertModern, App::DocumentObject **topParent, std::string *subname)
Return active body or show a warning message. If autoActivate is true (the default) then if there is only single body in the document it will be activated.
PartDesign::Body * makeBodyActive (App::DocumentObject *body, App::Document *doc, App::DocumentObject **topParent, std::string *subname)
void needActiveBodyError ()
Display error when there are existing Body objects, but none are active.
PartDesign::Body * makeBody (App::Document *doc)
Create a Body object in doc, set it active, and return pointer to it.
PartDesign::Body * getBodyFor (const App::DocumentObject *obj, bool messageIfNot, bool autoActivate, bool assertModern, App::DocumentObject **topParent, std::string *subname)
App::Part * getActivePart ()
App::Part * getPartFor (const App::DocumentObject *obj, bool messageIfNot)
void fixSketchSupport (Sketcher::SketchObject *sketch)
Fix sketch support after moving a free sketch into a body.
bool isPartDesignAwareObjecta (App::DocumentObject *obj, bool respectGroups=false)
bool isAnyNonPartDesignLinksTo (PartDesign::Feature *feature, bool respectGroups)
void relinkToBody (PartDesign::Feature *feature)
Relink all nonPartDesign features to the body instead of the given partDesign Feature.
bool isFeatureMovable (App::DocumentObject *feature)
Check if feature is dependent on anything except movable sketches and datums.
std::vector< App::DocumentObject * > collectMovableDependencies (std::vector< App::DocumentObject * > &features)
Collect dependencies of the features during the move. Dependencies should only be dependent on origin.
void relinkToOrigin (App::DocumentObject *feature, PartDesign::Body *body)
Relink sketches and datums to target body's origin.
PartDesign::Body * needActiveBodyMessage (App::Document *doc, const QString &infoText=QString())
Display a dialog to select or create a Body object when none is active.
bool assureLegacyWorkflow (App::Document *doc)
Assures that workflow of the given document is determined and returns true if it is Workflow::Legacy.
bool assureModernWorkflow (App::Document *doc)
Assures that workflow of the given document is determined and returns true if it is Workflow::Modern.
bool isLegacyWorkflow (App::Document *doc)
Returns true if the workflow of the given document is Workflow::Legacy.
bool isModernWorkflow (App::Document *doc)
Returns true if the workflow of the given document is Workflow::Modern.
Typedef Documentation
ViewProviderPython
using PartDesignGui::ViewProviderPython = typedef Gui::ViewProviderFeaturePythonT<ViewProvider>
Definition at line 118 of file Mod/PartDesign/Gui/ViewProvider.h.
ViewProviderSubShapeBinderPython
using PartDesignGui::ViewProviderSubShapeBinderPython = typedef Gui::ViewProviderFeaturePythonT<ViewProviderSubShapeBinder>
Definition at line 107 of file ViewProviderShapeBinder.h.
Enumeration Type Documentation
AllowSelection
enum PartDesignGui::AllowSelection strong
Enumerator
NONE
This is used to indicate to stop the selection
EDGE
Allow picking edges
FACE
Allow picking faces
PLANAR
Allow only linear edges and planar faces
CIRCLE
Allow picking circular edges (incl arcs)
POINT
Allow picking datum points
OTHERBODY
Allow picking objects from another body in the same part
WHOLE
Allow whole object selection
Definition at line 53 of file EnumFlags.h.
Workflow
enum PartDesignGui::Workflow strong
Defines allowded tool set provided by the workbench Legacy mode provides a free PartDesign features but forbids bodies and parts
Enumerator
Undetermined
No workflow was chosen yet.
Legacy
Old-style workflow with free features and no bodies.
Modern
New-style workflow with bodies, parts etc.
Definition at line 36 of file WorkflowManager.h.
Function Documentation
assertActivePart()
App::Part* PartDesignGui::assertActivePart ()
Returns active part, if there is no such, creates a new part, if it fails, shows a message.
Definition at line 81 of file CommandBody.cpp.
assureLegacyWorkflow()
bool PartDesignGui::assureLegacyWorkflow (App::Document * doc) inline
Assures that workflow of the given document is determined and returns true if it is Workflow::Legacy.
Definition at line 106 of file WorkflowManager.h.
References PartDesignGui::WorkflowManager::determineWorkflow(), toolbit-attributes::doc, PartDesignGui::WorkflowManager::instance(), and Legacy.
assureModernWorkflow()
bool PartDesignGui::assureModernWorkflow (App::Document * doc) inline
Assures that workflow of the given document is determined and returns true if it is Workflow::Modern.
Definition at line 111 of file WorkflowManager.h.
References PartDesignGui::WorkflowManager::determineWorkflow(), toolbit-attributes::doc, PartDesignGui::WorkflowManager::instance(), and Modern.
buildLinkListPythonStr()
std::string PartDesignGui::buildLinkListPythonStr (const std::vector< App::DocumentObject * > & objs)
Return reference as string for python in the format [obj1, obj2, ...,].
Definition at line 384 of file ReferenceSelection.cpp.
References Gui::Command::getObjectCmd(), replaceobj::objs, and result.
Referenced by relinkToBody().
buildLinkSingleSubPythonStr()
std::string PartDesignGui::buildLinkSingleSubPythonStr (const App::DocumentObject * obj, const std::vector< std::string > & subs)
Return reference as string for python in the format (<obj> ["sub"?])
Definition at line 372 of file ReferenceSelection.cpp.
References Gui::Command::getObjectCmd(), PartDesign::Feature::isDatum(), and importers.importIFCmulticore::subs.
Referenced by PartDesignGui::TaskDlgDraftParameters::accept(), PartDesignGui::TaskHelixParameters::apply(), PartDesignGui::TaskRevolutionParameters::apply(), PartDesignGui::TaskMirroredParameters::apply(), PartDesignGui::TaskLinearPatternParameters::apply(), PartDesignGui::TaskPolarPatternParameters::apply(), and PartDesignGui::TaskExtrudeParameters::getReferenceAxis().
buildLinkSubListPythonStr()
std::string PartDesignGui::buildLinkSubListPythonStr (const std::vector< App::DocumentObject * > & objs, const std::vector< std::string > & subs)
Returns sub reference list as a python string in the format [(obj1,"sub1"),(obj2,"sub2"),...].
Definition at line 399 of file ReferenceSelection.cpp.
References Gui::Command::getObjectCmd(), SplineSurface::i, replaceobj::objs, result, and importers.importIFCmulticore::subs.
Referenced by relinkToBody().
buildLinkSubPythonStr()
std::string PartDesignGui::buildLinkSubPythonStr (const App::DocumentObject * obj, const std::vector< std::string > & subs)
Return reference as string for python in the format (<obj> ["sub1", "sub2", ...])
Definition at line 358 of file ReferenceSelection.cpp.
References result, and importers.importIFCmulticore::subs.
Referenced by relinkToBody().
collectMovableDependencies()
std::vector< App::DocumentObject * > PartDesignGui::collectMovableDependencies (std::vector< App::DocumentObject * > & features)
Collect dependencies of the features during the move. Dependencies should only be dependent on origin.
Definition at line 527 of file PartDesign/Gui/Utils.cpp.
References Base::BaseClass::isDerivedFrom(), and result.
Referenced by PartDesignGui::ViewProviderBody::dropObject().
fixSketchSupport()
void PartDesignGui::fixSketchSupport (Sketcher::SketchObject * sketch)
Fix sketch support after moving a free sketch into a body.
Definition at line 276 of file PartDesign/Gui/Utils.cpp.
References a, Part::AttachExtension::AttachmentSupport, toolbit-attributes::doc, FCMD_DOC_CMD, FCMD_OBJ_CMD, Base::Vector3< float_type >::GetAngle(), getBodyFor(), App::DocumentObject::getDocument(), Attacher::AttachEngine::getModeName(), Gui::Command::getObjectCmd(), App::OriginGroupExtension::getOrigin(), Base::Placement::getPosition(), Base::Placement::getRotation(), App::PropertyPlacement::getValue(), App::PropertyLinkSubList::getValue(), App::LocalCoordinateSystem::getXY(), App::LocalCoordinateSystem::getXZ(), App::LocalCoordinateSystem::getYZ(), M_PI_2, Attacher::mmFlatFace, Base::Rotation::multVec(), App::GeoFeature::Placement, WorkingPlane::plane, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by PartDesignGui::TaskFeaturePick::buildFeatures().
getActivePart()
App::Part * PartDesignGui::getActivePart ()
Definition at line 231 of file PartDesign/Gui/Utils.cpp.
References Gui::Application::activeView(), Gui::MDIView::getActiveObject(), Gui::Application::Instance, and PARTKEY.
Referenced by PartDesignGui::ViewProviderBody::canDropObject().
getBody()
PartDesign::Body * PartDesignGui::getBody (bool messageIfNot, bool autoActivate, bool assertModern, App::DocumentObject ** topParent, std::string * subname)
Return active body or show a warning message. If autoActivate is true (the default) then if there is only single body in the document it will be activated.
Return active body or show a warning message.
Parameters
messageIfNot
autoActivate
Returns
Body
Definition at line 116 of file PartDesign/Gui/Utils.cpp.
References Gui::Application::activeView(), toolbit-attributes::doc, PartDesignGui::DlgActiveBody::getActiveBody(), Gui::MDIView::getActiveObject(), Gui::BaseView::getAppDocument(), Base::Persistence::getClassTypeId(), Gui::getMainWindow(), Gui::Application::Instance, makeBodyActive(), and PDBODYKEY.
Referenced by PartDesignGui::ReferenceSelection::allow(), PartDesignGui::TaskFeaturePick::buildFeatures(), dressupGetSelected(), finishFeature(), getBodyFor(), makeChamferOrFillet(), prepareProfileBased(), prepareTransformed(), UnifiedDatumCommand(), and validateSketches().
getBodyFor()
PartDesign::Body * PartDesignGui::getBodyFor (const App::DocumentObject * , bool messageIfNot, bool autoActivate = true, bool assertModern = true, App::DocumentObject ** topParent = nullptr, std::string * subname = nullptr)
Finds a body for the given feature. And shows a message if not found Also unlike Body::findBodyFor it checks if the active body has the feature first.
Definition at line 207 of file PartDesign/Gui/Utils.cpp.
References PartDesign::Body::findBodyOf(), getBody(), Gui::getMainWindow(), App::OriginGroupExtension::hasObject(), and Path.Log::warning().
Referenced by PartDesignGui::TaskDlgDatumParameters::accept(), PartDesignGui::TaskPipeParameters::accept(), PartDesignGui::TaskFeaturePick::buildFeatures(), PartDesignGui::ViewProviderDatum::doubleClicked(), dressupGetSelected(), finishDressupFeature(), finishFeature(), fixSketchSupport(), getPartFor(), getReferencedSelection(), prepareProfileBased(), prepareTransformed(), setEdit(), and PartDesignGui::Workbench::setupContextMenu().
getParent()
App::DocumentObject* PartDesignGui::getParent (App::DocumentObject * obj, std::string & subname)
Definition at line 59 of file PartDesign/Gui/Utils.cpp.
References App::DocumentObjectExtension::getExtensionClassTypeId(), App::DocumentObject::getInList(), App::DocumentObject::getNameInDocument(), and Init::parent.
getPartFor()
App::Part * PartDesignGui::getPartFor (const App::DocumentObject * obj, bool messageIfNot)
Definition at line 240 of file PartDesign/Gui/Utils.cpp.
References getBodyFor(), App::DocumentObject::getDocument(), Gui::getMainWindow(), App::Document::getObjectsOfType(), buildPsets::p, and Path.Log::warning().
Referenced by PartDesignGui::TaskDlgDatumParameters::accept(), PartDesignGui::TaskFeaturePick::buildFeatures(), prepareProfileBased(), and validateSketches().
getReferencedSelection()
bool PartDesignGui::getReferencedSelection (const App::DocumentObject * thisObj, const Gui::SelectionChanges & msg, App::DocumentObject *& selObj, std::vector< std::string > & selSub)
Extract reference from Selection.
Definition at line 284 of file ReferenceSelection.cpp.
References PartDesign::Body::addObject(), getBodyFor(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), Gui::getMainWindow(), App::Document::getName(), App::Document::getObject(), PartDesign::Feature::isDatum(), Base::BaseClass::isDerivedFrom(), PartDesignGui::TaskFeaturePick::makeCopy(), Path.Op.Surface::msg, App::Document::openTransaction(), and result.
Referenced by PartDesignGui::TaskDraftParameters::onSelectionChanged(), PartDesignGui::TaskMirroredParameters::onSelectionChanged(), PartDesignGui::TaskPolarPatternParameters::onSelectionChanged(), PartDesignGui::TaskLinearPatternParameters::onSelectionChanged(), PartDesignGui::TaskRevolutionParameters::onSelectionChanged(), and PartDesignGui::TaskHelixParameters::onSelectionChanged().
getRefStr()
QString PartDesignGui::getRefStr (const App::DocumentObject * obj, const std::vector< std::string > & sub)
Return reference as string for UI elements (format <obj>:<subelement>
Definition at line 341 of file ReferenceSelection.cpp.
References App::DocumentObject::getNameInDocument(), and PartDesign::Feature::isDatum().
Referenced by PartDesignGui::TaskRevolutionParameters::fillAxisCombo(), PartDesignGui::TaskExtrudeParameters::fillDirectionCombo(), PartDesignGui::TaskDraftParameters::onSelectionChanged(), and PartDesignGui::TaskDraftParameters::TaskDraftParameters().
initModule()
PyObject* PartDesignGui::initModule ()
Definition at line 93 of file AppPartDesignGui.cpp.
References Base::InterpreterSingleton::addModule(), and Base::Interpreter().
Referenced by PyMOD_INIT_FUNC().
isAnyNonPartDesignLinksTo()
bool PartDesignGui::isAnyNonPartDesignLinksTo (PartDesign::Feature * feature, bool respectGroups = false)
Returns true if document has any non-PartDesign objects that links to the given object. If respectGroups is true don't count links from App::GeoFeatureGroup-derived objects (default is false)
Definition at line 357 of file PartDesign/Gui/Utils.cpp.
References toolbit-attributes::doc, DraftVecUtils::find(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), App::PropertyContainer::getPropertyList(), getValue(), and isPartDesignAwareObjecta().
isFeatureMovable()
bool PartDesignGui::isFeatureMovable (App::DocumentObject *const feat)
Check if feature is dependent on anything except movable sketches and datums.
Definition at line 457 of file PartDesign/Gui/Utils.cpp.
References App::ExtensionContainer::getExtensionByType(), App::DocumentObjectExtension::getExtensionClassTypeId(), and App::ExtensionContainer::hasExtension().
Referenced by PartDesignGui::ViewProviderBody::dropObject().
isLegacyWorkflow()
bool PartDesignGui::isLegacyWorkflow (App::Document * doc) inline
Returns true if the workflow of the given document is Workflow::Legacy.
Definition at line 116 of file WorkflowManager.h.
References toolbit-attributes::doc, PartDesignGui::WorkflowManager::getWorkflowForDocument(), PartDesignGui::WorkflowManager::instance(), and Legacy.
isModernWorkflow()
bool PartDesignGui::isModernWorkflow (App::Document * doc) inline
Returns true if the workflow of the given document is Workflow::Modern.
Definition at line 121 of file WorkflowManager.h.
References toolbit-attributes::doc, PartDesignGui::WorkflowManager::getWorkflowForDocument(), PartDesignGui::WorkflowManager::instance(), and Modern.
isPartDesignAwareObjecta()
bool PartDesignGui::isPartDesignAwareObjecta (App::DocumentObject * obj, bool respectGroups = false)
Definition at line 347 of file PartDesign/Gui/Utils.cpp.
References Base::Persistence::getClassTypeId(), App::DocumentObjectExtension::getExtensionClassTypeId(), App::ExtensionContainer::hasExtension(), PartDesign::Body::isAllowed(), and Base::BaseClass::isDerivedFrom().
Referenced by isAnyNonPartDesignLinksTo(), and relinkToBody().
makeBody()
PartDesign::Body * PartDesignGui::makeBody (App::Document * doc)
Create a Body object in doc, set it active, and return pointer to it.
Definition at line 194 of file PartDesign/Gui/Utils.cpp.
References toolbit-attributes::doc, Gui::Command::Doc, doCommand, and makeBodyActive().
Referenced by PartDesignGui::DlgActiveBody::accept().
makeBodyActive()
PartDesign::Body * PartDesignGui::makeBodyActive (App::DocumentObject * body, App::Document * doc, App::DocumentObject ** topParent = nullptr, std::string * subname = nullptr)
Set given body active, and return pointer to it.
Parameters
body the pointer to the body
doc the pointer to the document in question
topParent and
subname to be passed under certain circumstances (currently only subshapebinder)
Definition at line 154 of file PartDesign/Gui/Utils.cpp.
References Gui::Application::activeView(), Gui::cmdGuiDocument(), toolbit-attributes::doc, App::DocumentObject::getDocument(), Gui::Command::getObjectCmd(), App::DocumentObject::getParents(), Gui::Application::Instance, Init::parent, PDBODYKEY, and TestSpreadsheet::v.
Referenced by PartDesignGui::DlgActiveBody::accept(), getBody(), and makeBody().
needActiveBodyError()
void PartDesignGui::needActiveBodyError ()
Display error when there are existing Body objects, but none are active.
Definition at line 185 of file PartDesign/Gui/Utils.cpp.
References Gui::getMainWindow(), and Path.Log::warning().
needActiveBodyMessage()
PartDesign::Body* PartDesignGui::needActiveBodyMessage (App::Document * doc, const QString & infoText = QString())
Display a dialog to select or create a Body object when none is active.
relinkToBody()
void PartDesignGui::relinkToBody (PartDesign::Feature * feature)
Relink all nonPartDesign features to the body instead of the given partDesign Feature.
Definition at line 391 of file PartDesign/Gui/Utils.cpp.
References buildLinkListPythonStr(), buildLinkSubListPythonStr(), buildLinkSubPythonStr(), toolbit-attributes::doc, FCMD_OBJ_CMD, PartDesign::Body::findBodyOf(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), Gui::Command::getObjectCmd(), App::PropertyLinkSub::getSubValues(), App::PropertyLinkSubList::getSubValues(), App::PropertyLink::getValue(), App::PropertyLinkSub::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyLinkSubList::getValues(), and isPartDesignAwareObjecta().
relinkToOrigin()
void PartDesignGui::relinkToOrigin (App::DocumentObject * feat, PartDesign::Body * targetbody)
Relink sketches and datums to target body's origin.
Definition at line 576 of file PartDesign/Gui/Utils.cpp.
References App::LocalCoordinateSystem::getDatumElement(), App::ExtensionContainer::getExtensionByType(), App::DocumentObjectExtension::getExtensionClassTypeId(), App::OriginGroupExtension::getOrigin(), App::ExtensionContainer::hasExtension(), and Base::BaseClass::isDerivedFrom().
setEdit()
bool PartDesignGui::setEdit (App::DocumentObject * obj, PartDesign::Body * body)
Activate edit mode of the given object.
Definition at line 75 of file PartDesign/Gui/Utils.cpp.
References Gui::Application::activeView(), Gui::cmdGuiDocument(), FC_ERR, getBodyFor(), App::DocumentObject::getNameInDocument(), Gui::Command::getObjectCmd(), Gui::Application::Instance, App::DocumentObject::isAttachedToDocument(), Init::parent, and PDBODYKEY.
Referenced by PartDesignGui::ViewProviderDatum::doubleClicked(), TechDrawGui::ViewProviderRichAnno::doubleClicked(), TechDrawGui::ViewProviderGeomHatch::doubleClicked(), TechDrawGui::ViewProviderLeader::doubleClicked(), TechDrawGui::ViewProviderWeld::doubleClicked(), TechDrawGui::ViewProviderViewSection::doubleClicked(), TechDrawGui::ViewProviderViewPart::doubleClicked(), src.Mod.PartDesign.WizardShaft.Shaft.Shaft::editConstraint(), finishFeature(), SurfaceGui::ViewProviderGeomFillSurface::setEdit(), SurfaceGui::ViewProviderSections::setEdit(), SurfaceGui::ViewProviderFilling::setEdit(), PartDesignGui::ViewProviderShapeBinder::setEdit(), FemGui::ViewProviderFemMeshShapeNetgen::setEdit(), AssemblyGui::ViewProviderAssemblyLink::setEdit(), FemGui::ViewProviderFemConstraintTransform::setEdit(), PointsGui::ViewProviderPoints::setEdit(), PartDesignGui::ViewProviderSubShapeBinder::setEdit(), TechDrawGui::ViewProviderViewSection::setEdit(), FemGui::ViewProviderFemPostObject::setEdit(), AssemblyGui::ViewProviderAssembly::setEdit(), FemGui::ViewProviderFemPostFunction::setEdit(), MeshGui::ViewProviderMesh::setEdit(), Gui::ViewProviderFeaturePythonT< ViewProviderT >::setEdit(), and UnifiedDatumCommand().