FreeCAD: SIM::Coin3D::Quarter::SoQTQuarterAdaptor Class Reference
SIM::Coin3D::Quarter::SoQTQuarterAdaptor Class Reference
#include <SoQTQuarterAdaptor.h>
Public Member Functions
SoQTQuarterAdaptor (QWidget *parent=nullptr, const QtGLWidget *sharewidget=nullptr, Qt::WindowFlags flags=Qt::WindowFlags())
SoQTQuarterAdaptor (const QtGLFormat &format, QWidget *parent=nullptr, const QtGLWidget *shareWidget=nullptr, Qt::WindowFlags flags=Qt::WindowFlags())
SoQTQuarterAdaptor (QtGLContext *context, QWidget *parent=nullptr, const QtGLWidget *sharewidget=nullptr, Qt::WindowFlags flags=Qt::WindowFlags())
~SoQTQuarterAdaptor () override
QWidget * getWidget ()
QWidget * getGLWidget ()
QWidget * getWidget () const
QWidget * getGLWidget () const
virtual void setCameraType (SoType type)
SoCamera * getCamera () const
const SbViewportRegion & getViewportRegion () const
virtual void setViewing (bool enable)
bool isViewing () const
void interactiveCountInc ()
void interactiveCountDec ()
int getInteractiveCount () const
void addStartCallback (SoQTQuarterAdaptorCB *func, void *data=nullptr)
void addFinishCallback (SoQTQuarterAdaptorCB *func, void *data=nullptr)
void removeStartCallback (SoQTQuarterAdaptorCB *func, void *data=nullptr)
void removeFinishCallback (SoQTQuarterAdaptorCB *func, void *data=nullptr)
virtual void setSeekMode (bool enable)
bool isSeekMode () const
bool seekToPoint (const SbVec2s &screenpos)
void seekToPoint (const SbVec3f &scenepos)
void setSeekTime (float seconds)
float getSeekTime () const
void setSeekDistance (float distance)
float getSeekDistance () const
void setSeekValueAsPercentage (bool on)
bool isSeekValuePercentage () const
virtual float getPickRadius () const
virtual void setPickRadius (float pickRadius)
virtual void saveHomePosition ()
virtual void resetToHomePosition ()
virtual bool hasHomePosition () const
void setSceneGraph (SoNode *root) override
bool processSoEvent (const SoEvent *event) override
void paintEvent (QPaintEvent *event) override
virtual void afterRealizeHook ()
Public Member Functions inherited from SIM::Coin3D::Quarter::QuarterWidget
QuarterWidget (QWidget *parent=nullptr, const QtGLWidget *sharewidget=nullptr, Qt::WindowFlags f=Qt::WindowFlags())
QuarterWidget (QtGLContext *context, QWidget *parent=nullptr, const QtGLWidget *sharewidget=nullptr, Qt::WindowFlags f=Qt::WindowFlags())
QuarterWidget (const QtGLFormat &format, QWidget *parent=nullptr, const QtGLWidget *shareWidget=nullptr, Qt::WindowFlags f=Qt::WindowFlags())
~QuarterWidget () override
TransparencyType transparencyType () const
RenderMode renderMode () const
StereoMode stereoMode () const
void setBackgroundColor (const QColor &color)
QColor backgroundColor () const
qreal devicePixelRatio () const
void resetNavigationModeFile ()
void setNavigationModeFile (const QUrl &url=QUrl(QString::fromLatin1(DEFAULT_NAVIGATIONFILE)))
const QUrl & navigationModeFile () const
void setupDefaultCursors ()
void setContextMenuEnabled (bool yes)
bool contextMenuEnabled () const
QMenu * getContextMenu () const
bool headlightEnabled () const
void setHeadlightEnabled (bool onoff)
SoDirectionalLight * getHeadlight () const
bool clearZBuffer () const
void setClearZBuffer (bool onoff)
bool clearWindow () const
void setClearWindow (bool onoff)
bool interactionModeEnabled () const
void setInteractionModeEnabled (bool onoff)
bool interactionModeOn () const
void setInteractionModeOn (bool onoff)
void setStateCursor (const SbName &state, const QCursor &cursor)
QCursor stateCursor (const SbName &state)
uint32_t getCacheContextId () const
virtual SoNode * getSceneGraph () const
void setSoEventManager (SoEventManager *manager)
SoEventManager * getSoEventManager () const
void setSoRenderManager (SoRenderManager *manager)
SoRenderManager * getSoRenderManager () const
EventFilter * getEventFilter () const
void addStateMachine (SoScXMLStateMachine *statemachine)
void removeStateMachine (SoScXMLStateMachine *statemachine)
QSize minimumSizeHint () const override
QList< QAction * > transparencyTypeActions () const
QList< QAction * > stereoModeActions () const
QList< QAction * > renderModeActions () const
Static Protected Member Functions
static void draw2DString (const char *str, SbVec2s glsize, SbVec2f position)
static void printString (const char *str)
Protected Attributes
SbVec2f framesPerSecond
Additional Inherited Members
Public Types inherited from SIM::Coin3D::Quarter::QuarterWidget
enum TransparencyType {
SCREEN_DOOR = SoGLRenderAction::SCREEN_DOOR, ADD = SoGLRenderAction::ADD, DELAYED_ADD = SoGLRenderAction::DELAYED_ADD, SORTED_OBJECT_ADD = SoGLRenderAction::SORTED_OBJECT_ADD,
BLEND = SoGLRenderAction::BLEND, DELAYED_BLEND = SoGLRenderAction::DELAYED_BLEND, SORTED_OBJECT_BLEND = SoGLRenderAction::SORTED_OBJECT_BLEND, SORTED_OBJECT_SORTED_TRIANGLE_ADD = SoGLRenderAction::SORTED_OBJECT_SORTED_TRIANGLE_ADD,
SORTED_OBJECT_SORTED_TRIANGLE_BLEND = SoGLRenderAction::SORTED_OBJECT_SORTED_TRIANGLE_BLEND, NONE = SoGLRenderAction::NONE, SORTED_LAYERS_BLEND = SoGLRenderAction::SORTED_LAYERS_BLEND
}
enum RenderMode {
AS_IS = SoRenderManager::AS_IS, WIREFRAME = SoRenderManager::WIREFRAME, WIREFRAME_OVERLAY = SoRenderManager::WIREFRAME_OVERLAY, POINTS = SoRenderManager::POINTS,
HIDDEN_LINE = SoRenderManager::HIDDEN_LINE, BOUNDING_BOX = SoRenderManager::BOUNDING_BOX
}
enum StereoMode {
MONO = SoRenderManager::MONO, ANAGLYPH = SoRenderManager::ANAGLYPH, QUAD_BUFFER = SoRenderManager::QUAD_BUFFER, INTERLEAVED_ROWS = SoRenderManager::INTERLEAVED_ROWS,
INTERLEAVED_COLUMNS = SoRenderManager::INTERLEAVED_COLUMNS
}
Public Slots inherited from SIM::Coin3D::Quarter::QuarterWidget
virtual void viewAll ()
virtual void seek ()
void redraw ()
void setRenderMode (SIM::Coin3D::Quarter::QuarterWidget::RenderMode mode)
void setStereoMode (SIM::Coin3D::Quarter::QuarterWidget::StereoMode mode)
void setTransparencyType (SIM::Coin3D::Quarter::QuarterWidget::TransparencyType type)
Signals inherited from SIM::Coin3D::Quarter::QuarterWidget
void devicePixelRatioChanged (qreal dev_pixel_ratio)
Protected Member Functions inherited from SIM::Coin3D::Quarter::QuarterWidget
void paintEvent (QPaintEvent *) override
void resizeEvent (QResizeEvent *) override
bool viewportEvent (QEvent *event) override
virtual void actualRedraw ()
virtual bool updateDevicePixelRatio ()
Properties inherited from SIM::Coin3D::Quarter::QuarterWidget
QUrl navigationModeFile
QColor backgroundColor
bool contextMenuEnabled
bool headlightEnabled
bool clearZBuffer
bool clearWindow
bool interactionModeEnabled
bool interactionModeOn
TransparencyType transparencyType
RenderMode renderMode
StereoMode stereoMode
qreal devicePixelRatio
Detailed Description
Definition at line 45 of file SoQTQuarterAdaptor.h.
Constructor & Destructor Documentation
SoQTQuarterAdaptor() [1/3]
SIM::Coin3D::Quarter::SoQTQuarterAdaptor::SoQTQuarterAdaptor (QWidget * parent = nullptr, const QtGLWidget * sharewidget = nullptr, Qt::WindowFlags flags = Qt::WindowFlags()) explicit
Definition at line 150 of file SoQTQuarterAdaptor.cpp.
SoQTQuarterAdaptor() [2/3]
SIM::Coin3D::Quarter::SoQTQuarterAdaptor::SoQTQuarterAdaptor (const QtGLFormat & format, QWidget * parent = nullptr, const QtGLWidget * shareWidget = nullptr, Qt::WindowFlags flags = Qt::WindowFlags()) explicit
Definition at line 159 of file SoQTQuarterAdaptor.cpp.
SoQTQuarterAdaptor() [3/3]
SIM::Coin3D::Quarter::SoQTQuarterAdaptor::SoQTQuarterAdaptor (QtGLContext * context, QWidget * parent = nullptr, const QtGLWidget * sharewidget = nullptr, Qt::WindowFlags flags = Qt::WindowFlags()) explicit
Definition at line 169 of file SoQTQuarterAdaptor.cpp.
~SoQTQuarterAdaptor()
SIM::Coin3D::Quarter::SoQTQuarterAdaptor::~SoQTQuarterAdaptor () override
Definition at line 179 of file SoQTQuarterAdaptor.cpp.
Member Function Documentation
addFinishCallback()
void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::addFinishCallback (SoQTQuarterAdaptorCB * func, void * data = nullptr)
Definition at line 388 of file SoQTQuarterAdaptor.cpp.
Referenced by Gui::View3DInventorViewer::init().
addStartCallback()
void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::addStartCallback (SoQTQuarterAdaptorCB * func, void * data = nullptr)
Definition at line 378 of file SoQTQuarterAdaptor.cpp.
Referenced by Gui::View3DInventorViewer::init().
afterRealizeHook()
virtual void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::afterRealizeHook () inline virtual
Reimplemented in Gui::View3DInventorViewer.
Definition at line 116 of file SoQTQuarterAdaptor.h.
Referenced by Gui::View3DInventorViewer::afterRealizeHook().
draw2DString()
void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::draw2DString (const char * str, SbVec2s glsize, SbVec2f position) static protected
Definition at line 638 of file SoQTQuarterAdaptor.cpp.
References glDisable, glMatrixMode, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by Gui::View3DInventorViewer::renderScene().
getCamera()
SoCamera * SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getCamera () const
Definition at line 324 of file SoQTQuarterAdaptor.cpp.
Referenced by Gui::View3DInventorViewer::alignToSelection(), Gui::NavigationStyle::getCamera(), Gui::View3DInventorViewer::getPointOnRay(), Gui::NavigationStyle::lookAtPoint(), Gui::View3DInventorViewer::moveCameraTo(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::View3DInventorViewer::setViewDirection(), and Gui::View3DInventorPy::viewDefaultOrientation().
getGLWidget() [1/2]
QWidget * SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getGLWidget ()
Definition at line 211 of file SoQTQuarterAdaptor.cpp.
Referenced by SandboxGui::DrawingPlane::draw(), Gui::View3DInventor::focusInEvent(), InspectionGui::ViewProviderInspection::inspectCallback(), Gui::PolyPickerSelection::locationEvent(), Gui::FreehandSelection::locationEvent(), Gui::NavigationStyle::openPopupMenu(), Gui::View3DInventorViewer::renderScene(), Gui::View3DInventorViewer::savePicture(), Gui::View3DInventorViewer::screenCoordsOfPath(), and Gui::View3DInventor::setCurrentViewMode().
getGLWidget() [2/2]
QWidget* SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getGLWidget () const
getInteractiveCount()
int SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getInteractiveCount () const
Definition at line 372 of file SoQTQuarterAdaptor.cpp.
Referenced by Gui::NavigationStyle::getInteractiveCount().
getPickRadius()
virtual float SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getPickRadius () const inline virtual
Definition at line 97 of file SoQTQuarterAdaptor.h.
Referenced by Gui::View3DInventorPy::getObjectInfo(), Gui::View3DInventorPy::getObjectsInfo(), Gui::View3DInventorViewerPy::getPickRadius(), Gui::View3DInventorViewer::getPointOnRay(), Gui::NavigationStyle::handleEventInForeground(), Gui::GestureNavigationStyle::isDraggerUnderCursor(), Gui::NavigationStyle::lookAtPoint(), and Gui::NavigationStyle::saveCursorPosition().
getSeekDistance()
float SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getSeekDistance () const
Definition at line 399 of file SoQTQuarterAdaptor.cpp.
getSeekTime()
float SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getSeekTime () const
Definition at line 404 of file SoQTQuarterAdaptor.cpp.
getViewportRegion()
const SbViewportRegion & SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getViewportRegion () const
Definition at line 329 of file SoQTQuarterAdaptor.cpp.
Referenced by Gui::View3DInventorViewer::getDimensions(), Gui::View3DInventorViewer::getPointOnRay(), Gui::NavigationStyle::lookAtPoint(), Gui::View3DInventorViewer::pickPoint(), Gui::View3DInventorViewer::savePicture(), Gui::View3DInventorViewer::screenCoordsOfPath(), Gui::NavigationStyle::setupPanningPlane(), Gui::View3DInventorViewer::viewAll(), and Gui::View3DInventorViewer::viewSelection().
getWidget() [1/2]
QWidget * SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getWidget ()
Definition at line 204 of file SoQTQuarterAdaptor.cpp.
Referenced by Gui::AbstractMouseSelection::grabMouseModel(), Gui::PolyPickerSelection::initialize(), InspectionGui::ViewProviderInspection::inspectCallback(), Gui::PolyPickerSelection::mouseButtonEvent(), Gui::FreehandSelection::mouseButtonEvent(), Gui::NavigationStyle::openPopupMenu(), Gui::AbstractMouseSelection::releaseMouseModel(), Gui::View3DInventor::restoreOverrideCursor(), Gui::View3DInventorViewer::setComponentCursor(), Gui::View3DInventorViewer::setEditing(), Gui::View3DInventorViewer::setEditingCursor(), and Gui::View3DInventor::setOverrideCursor().
getWidget() [2/2]
QWidget* SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getWidget () const
hasHomePosition()
virtual bool SIM::Coin3D::Quarter::SoQTQuarterAdaptor::hasHomePosition () const inline virtual
Definition at line 102 of file SoQTQuarterAdaptor.h.
Referenced by StdRecallWorkingView::activated(), and StdRecallWorkingView::isActive().
interactiveCountDec()
void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::interactiveCountDec ()
Definition at line 364 of file SoQTQuarterAdaptor.cpp.
Referenced by Gui::NavigationStyle::interactiveCountDec().
interactiveCountInc()
void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::interactiveCountInc ()
Definition at line 354 of file SoQTQuarterAdaptor.cpp.
Referenced by Gui::NavigationStyle::interactiveCountInc().
isSeekMode()
bool SIM::Coin3D::Quarter::SoQTQuarterAdaptor::isSeekMode () const
Definition at line 409 of file SoQTQuarterAdaptor.cpp.
Referenced by Gui::NavigationStyle::isSeekMode().
isSeekValuePercentage()
bool SIM::Coin3D::Quarter::SoQTQuarterAdaptor::isSeekValuePercentage () const
Definition at line 414 of file SoQTQuarterAdaptor.cpp.
Referenced by Gui::View3DInventorViewer::init().
isViewing()
bool SIM::Coin3D::Quarter::SoQTQuarterAdaptor::isViewing () const
Definition at line 349 of file SoQTQuarterAdaptor.cpp.
Referenced by Gui::NavigationStyle::isViewing(), Gui::View3DInventorViewer::setFeedbackSize(), Gui::View3DInventorViewer::setFeedbackVisibility(), Gui::View3DInventorViewer::setSeekMode(), and Gui::View3DInventorViewer::setViewing().
paintEvent()
void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::paintEvent (QPaintEvent * event) override
Overridden from QuarterWidget to render the scenegraph
Definition at line 758 of file SoQTQuarterAdaptor.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::paintEvent().
printString()
void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::printString (const char * str) static protected
Definition at line 685 of file SoQTQuarterAdaptor.cpp.
References fps2dfont, SplineSurface::i, and Path.Post.scripts.refactored_centroid_post::str.
processSoEvent()
bool SIM::Coin3D::Quarter::SoQTQuarterAdaptor::processSoEvent (const SoEvent * event) override virtual
Passes an event to the event manager.
Parameters
[in] event to pass
Return values
Returns true if the event was successfully processed
Reimplemented from SIM::Coin3D::Quarter::QuarterWidget.
Reimplemented in Gui::View3DInventorViewer.
Definition at line 719 of file SoQTQuarterAdaptor.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::processSoEvent(), and Path.Post.scripts.grbl_post::type.
Referenced by Gui::View3DInventorViewer::processSoEvent(), and Gui::View3DInventorViewer::processSoEventBase().
removeFinishCallback()
void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::removeFinishCallback (SoQTQuarterAdaptorCB * func, void * data = nullptr)
Definition at line 393 of file SoQTQuarterAdaptor.cpp.
removeStartCallback()
void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::removeStartCallback (SoQTQuarterAdaptorCB * func, void * data = nullptr)
Definition at line 383 of file SoQTQuarterAdaptor.cpp.
resetToHomePosition()
void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::resetToHomePosition () virtual
Definition at line 597 of file SoQTQuarterAdaptor.cpp.
References OfflineRenderingUtils::getCamera().
Referenced by StdRecallWorkingView::activated().
saveHomePosition()
void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::saveHomePosition () virtual
Definition at line 576 of file SoQTQuarterAdaptor.cpp.
References Path.Post.scripts.grbl_post::type.
Referenced by StdStoreWorkingView::activated().
seekToPoint() [1/2]
bool SIM::Coin3D::Quarter::SoQTQuarterAdaptor::seekToPoint (const SbVec2s & screenpos)
Definition at line 431 of file SoQTQuarterAdaptor.cpp.
Referenced by Gui::View3DInventorViewer::pubSeekToPoint(), Gui::View3DInventorViewerPy::seekToPoint(), and Gui::NavigationStyle::seekToPoint().
seekToPoint() [2/2]
void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::seekToPoint (const SbVec3f & scenepos)
Definition at line 454 of file SoQTQuarterAdaptor.cpp.
References OfflineRenderingUtils::getCamera().
setCameraType()
void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::setCameraType (SoType type) virtual
Reimplemented in Gui::View3DInventorViewer.
Definition at line 228 of file SoQTQuarterAdaptor.cpp.
References Base::Console(), Init::parent, Path.Post.scripts.grbl_post::type, and Base::ConsoleSingleton::Warning().
Referenced by Gui::View3DInventorViewer::setCameraType().
setPickRadius()
void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::setPickRadius (float pickRadius) virtual
Definition at line 419 of file SoQTQuarterAdaptor.cpp.
Referenced by Gui::View3DInventorViewerPy::setPickRadius().
setSceneGraph()
void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::setSceneGraph (SoNode * node) inline override virtual
Sets the Inventor scenegraph to be rendered
Reimplemented from SIM::Coin3D::Quarter::QuarterWidget.
Reimplemented in Gui::View3DInventorViewer.
Definition at line 107 of file SoQTQuarterAdaptor.h.
References SIM::Coin3D::Quarter::QuarterWidget::setSceneGraph().
Referenced by Gui::View3DInventorViewer::setSceneGraph().
setSeekDistance()
void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::setSeekDistance (float distance)
Definition at line 500 of file SoQTQuarterAdaptor.cpp.
Referenced by Gui::View3DInventorViewer::init().
setSeekMode()
void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::setSeekMode (bool enable) virtual
Reimplemented in Gui::View3DInventorViewer.
Definition at line 505 of file SoQTQuarterAdaptor.cpp.
Referenced by Gui::View3DInventorViewer::setSeekMode().
setSeekTime()
void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::setSeekTime (float seconds)
Definition at line 515 of file SoQTQuarterAdaptor.cpp.
Referenced by Gui::View3DInventorViewer::init().
setSeekValueAsPercentage()
void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::setSeekValueAsPercentage (bool on)
Definition at line 520 of file SoQTQuarterAdaptor.cpp.
Referenced by Gui::View3DInventorViewer::init().
setViewing()
void SIM::Coin3D::Quarter::SoQTQuarterAdaptor::setViewing (bool enable) virtual
Reimplemented in Gui::View3DInventorViewer.
Definition at line 334 of file SoQTQuarterAdaptor.cpp.
References Path.Post.scripts.dynapath_4060_post::action.
Referenced by Gui::View3DInventorViewer::setViewing().
Member Data Documentation
framesPerSecond
SbVec2f SIM::Coin3D::Quarter::SoQTQuarterAdaptor::framesPerSecond protected
Definition at line 155 of file SoQTQuarterAdaptor.h.
Referenced by Gui::View3DInventorViewer::renderScene().
The documentation for this class was generated from the following files:
SoQTQuarterAdaptor.h
SoQTQuarterAdaptor.cpp