FreeCAD: MeshGui::Segmentation Class Reference
MeshGui::Segmentation Class Reference
#include <Segmentation.h>
Public Member Functions
Segmentation (Mesh::Feature *mesh, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~Segmentation () override
void accept ()
Protected Member Functions
void changeEvent (QEvent *e) override
Detailed Description
Definition at line 45 of file Mesh/Gui/Segmentation.h.
Constructor & Destructor Documentation
Segmentation()
Segmentation::Segmentation (Mesh::Feature * mesh, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Definition at line 42 of file Mesh/Gui/Segmentation.cpp.
~Segmentation()
Segmentation::~Segmentation () override
Definition at line 64 of file Mesh/Gui/Segmentation.cpp.
Member Function Documentation
accept()
void Segmentation::accept ()
Definition at line 70 of file Mesh/Gui/Segmentation.cpp.
References App::Document::addObject(), App::Document::commitTransaction(), MeshCore::MeshCurvature::ComputePerVertex(), MeshCore::MeshSegmentAlgorithm::FindSegments(), Mesh::PropertyMeshKernel::finishEditing(), App::Application::getActiveDocument(), App::GetApplication(), MeshCore::MeshCurvature::GetCurvature(), App::DocumentObject::getNameInDocument(), App::PropertyString::getValue(), Mesh::PropertyMeshKernel::getValuePtr(), toolbit-attributes::group, App::DocumentObject::Label, NavigationIndicatorGui::label, Mesh2Shape::mesh, Mesh::Feature::Mesh, App::Document::openTransaction(), App::PropertyString::setValue(), MeshCore::LaplaceSmoothing::Smooth(), Mesh::PropertyMeshKernel::startEditing(), and Mesh::MeshObject::swap().
Referenced by MeshGui::TaskSegmentation::accept().
changeEvent()
void Segmentation::changeEvent (QEvent * e) override protected
Definition at line 147 of file Mesh/Gui/Segmentation.cpp.
References SCL.SimpleDataTypes::e.
The documentation for this class was generated from the following files:
Mesh/Gui/Segmentation.h
Mesh/Gui/Segmentation.cpp