FreeCAD: Path.Op.SurfaceSupport Namespace Reference
Path.Op.SurfaceSupport Namespace Reference
Classes
class FindUnifiedRegions
class OCL_Tool
class PathGeometryGenerator
class ProcessSelectedFaces
Functions
def getExtrudedShape (wire)
def getShapeSlice (shape)
def getProjectedFace (tempGroup, wire)
def getCrossSection (shape)
def getShapeEnvelope (shape)
def getSliceFromEnvelope (env)
def pathGeomToLinesPointSet (self, obj, compGeoShp)
def pathGeomToZigzagPointSet (self, obj, compGeoShp)
def pathGeomToCircularPointSet (self, obj, compGeoShp)
def pathGeomToSpiralPointSet (obj, compGeoShp)
def pathGeomToOffsetPointSet (obj, compGeoShp)
def makeExtendedBoundBox (wBB, bbBfr, zDep)
Variables
Part
translate
closedGap
CutClimb
Function Documentation
getCrossSection()
def Path.Op.SurfaceSupport.getCrossSection (shape)
Definition at line 1097 of file SurfaceSupport.py.
References Path.Log.debug().
Referenced by Path.Op.SurfaceSupport.FindUnifiedRegions.getUnifiedRegions(), and Path.Op.SurfaceSupport.ProcessSelectedFaces.preProcessModel().
getExtrudedShape()
def Path.Op.SurfaceSupport.getExtrudedShape (wire)
Definition at line 1009 of file SurfaceSupport.py.
References Path.Log.debug(), and Path.Log.error().
Referenced by Path.Op.SurfaceSupport.FindUnifiedRegions.getUnifiedRegions().
getProjectedFace()
def Path.Op.SurfaceSupport.getProjectedFace (tempGroup, wire)
Definition at line 1072 of file SurfaceSupport.py.
References Path.Log.debug(), Path.Log.error(), and Path.Post.scripts.refactored_centroid_post.str.
getShapeEnvelope()
def Path.Op.SurfaceSupport.getShapeEnvelope (shape)
Definition at line 1122 of file SurfaceSupport.py.
References Path.Log.debug(), and Path.Post.scripts.refactored_centroid_post.str.
getShapeSlice()
def Path.Op.SurfaceSupport.getShapeSlice (shape)
Definition at line 1024 of file SurfaceSupport.py.
References Path.Log.debug().
Referenced by Path.Op.SurfaceSupport.ProcessSelectedFaces.preProcessModel().
getSliceFromEnvelope()
def Path.Op.SurfaceSupport.getSliceFromEnvelope (env)
Definition at line 1141 of file SurfaceSupport.py.
References importDXF.addObject(), Path.Log.debug(), Path.Log.error(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Op.SurfaceSupport.ProcessSelectedFaces.preProcessModel().
makeExtendedBoundBox()
def Path.Op.SurfaceSupport.makeExtendedBoundBox (wBB, bbBfr, zDep)
Definition at line 2708 of file SurfaceSupport.py.
References Path.Log.debug().
pathGeomToCircularPointSet()
def Path.Op.SurfaceSupport.pathGeomToCircularPointSet (self, obj, compGeoShp)
pathGeomToCircularPointSet(self, obj, compGeoShp)...
Convert a compound set of arcs/circles to a set of directionally-oriented arc end points
and the corresponding center point.
Definition at line 1504 of file SurfaceSupport.py.
References Path.Log.debug().
pathGeomToLinesPointSet()
def Path.Op.SurfaceSupport.pathGeomToLinesPointSet (self, obj, compGeoShp)
pathGeomToLinesPointSet(self, obj, compGeoShp)...
Convert a compound set of sequential line segments to directionally-oriented collinear groupings.
Definition at line 1278 of file SurfaceSupport.py.
References KDL.abs(), and Path.Log.debug().
pathGeomToOffsetPointSet()
def Path.Op.SurfaceSupport.pathGeomToOffsetPointSet (obj, compGeoShp)
pathGeomToOffsetPointSet(obj, compGeoShp)...
Convert a compound set of 3D profile segmented wires to 2D segments, applying linear optimization.
Definition at line 1793 of file SurfaceSupport.py.
References Path.Log.debug().
pathGeomToSpiralPointSet()
def Path.Op.SurfaceSupport.pathGeomToSpiralPointSet (obj, compGeoShp)
_pathGeomToSpiralPointSet(obj, compGeoShp)...
Convert a compound set of sequential line segments to directional, connected groupings.
Definition at line 1742 of file SurfaceSupport.py.
References Path.Log.debug().
pathGeomToZigzagPointSet()
def Path.Op.SurfaceSupport.pathGeomToZigzagPointSet (self, obj, compGeoShp)
_pathGeomToZigzagPointSet(self, obj, compGeoShp)...
Convert a compound set of sequential line segments to directionally-oriented collinear groupings
with a ZigZag directional indicator included for each collinear group.
Definition at line 1383 of file SurfaceSupport.py.
References KDL.abs(), Path.Log.debug(), and AssemblyImport.insert().
Variable Documentation
closedGap
Path.Op.SurfaceSupport.closedGap
Definition at line 1346 of file SurfaceSupport.py.
CutClimb
Path.Op.SurfaceSupport.CutClimb
Definition at line 1534 of file SurfaceSupport.py.
Part
Path.Op.SurfaceSupport.Part
Definition at line 40 of file SurfaceSupport.py.
translate
Path.Op.SurfaceSupport.translate
Definition at line 50 of file SurfaceSupport.py.