FreeCAD: Py::SmartPtr Class Reference
Py::SmartPtr Class Reference
This is a stripped-down version of Py::Object. The purpose of this class is to avoid to include any other header file and therefore the PyObject is forward declared and the implementation is separated from the class declaration.
#include <SmartPtrPy.h>
Public Member Functions
SmartPtr ()
SmartPtr (PyObject *pyob, bool owned=false)
SmartPtr (const SmartPtr &ob)
SmartPtr & operator= (const SmartPtr &rhs)
SmartPtr & operator= (const Object &rhs)
SmartPtr & operator= (PyObject *rhsp)
virtual ~SmartPtr ()
PyObject * operator* () const
PyObject * ptr () const
bool is (PyObject *pother) const
bool is (const SmartPtr &other) const
bool isNull () const
Protected Member Functions
void set (PyObject *pyob, bool owned=false)
void release ()
Detailed Description
This is a stripped-down version of Py::Object. The purpose of this class is to avoid to include any other header file and therefore the PyObject is forward declared and the implementation is separated from the class declaration.
Author
Werner Mayer
Definition at line 44 of file SmartPtrPy.h.
Constructor & Destructor Documentation
SmartPtr() [1/3]
Py::SmartPtr::SmartPtr ()
Definition at line 71 of file SmartPtrPy.cpp.
References ptr(), and set().
SmartPtr() [2/3]
Py::SmartPtr::SmartPtr (PyObject * pyob, bool owned = false) explicit
Definition at line 77 of file SmartPtrPy.cpp.
References set().
SmartPtr() [3/3]
Py::SmartPtr::SmartPtr (const SmartPtr & ob)
Definition at line 85 of file SmartPtrPy.cpp.
References set().
~SmartPtr()
Py::SmartPtr::~SmartPtr () virtual
Definition at line 112 of file SmartPtrPy.cpp.
Member Function Documentation
is() [1/2]
bool Py::SmartPtr::is (const SmartPtr & other) const
Definition at line 132 of file SmartPtrPy.cpp.
is() [2/2]
bool Py::SmartPtr::is (PyObject * pother) const
Definition at line 127 of file SmartPtrPy.cpp.
Referenced by App::DocumentObjectExtension::getExtensionPyObject(), Gui::ViewProviderExtension::getExtensionPyObject(), App::GroupExtension::getExtensionPyObject(), App::Extension::getExtensionPyObject(), App::LinkBaseExtension::getExtensionPyObject(), TechDraw::DrawHatch::getPyObject(), TechDraw::DrawParametricTemplate::getPyObject(), Assembly::BomObject::getPyObject(), Assembly::AssemblyLink::getPyObject(), TechDraw::DrawGeomHatch::getPyObject(), Part::Feature::getPyObject(), TechDraw::DrawWeldSymbol::getPyObject(), Assembly::AssemblyObject::getPyObject(), TechDraw::DrawLeaderLine::getPyObject(), Assembly::JointGroup::getPyObject(), Assembly::BomGroup::getPyObject(), Assembly::SimulationGroup::getPyObject(), Assembly::ViewGroup::getPyObject(), Part::Primitive::getPyObject(), Mesh::Feature::getPyObject(), TechDraw::DrawTemplate::getPyObject(), TechDraw::DrawViewSymbol::getPyObject(), App::DocumentObjectGroup::getPyObject(), App::VRMLObject::getPyObject(), App::InventorObject::getPyObject(), TechDraw::DrawRichAnno::getPyObject(), TechDraw::DrawTile::getPyObject(), Path::Feature::getPyObject(), TechDraw::DrawTileWeld::getPyObject(), TechDraw::DrawViewDimExtent::getPyObject(), TechDraw::DrawSVGTemplate::getPyObject(), TechDraw::DrawBrokenView::getPyObject(), Measure::MeasureBase::getPyObject(), TechDraw::DrawProjGroupItem::getPyObject(), TechDraw::DrawView::getPyObject(), App::GeoFeature::getPyObject(), TechDraw::DrawViewClip::getPyObject(), TechDraw::DrawPage::getPyObject(), TechDraw::DrawProjGroup::getPyObject(), PartDesign::Body::getPyObject(), TechDraw::DrawViewPart::getPyObject(), Spreadsheet::Sheet::getPyObject(), Spreadsheet::PropertySheet::getPyObject(), PartDesign::PYTHON_TYPE_DEF(), and App::Extension::~Extension().
isNull()
bool Py::SmartPtr::isNull () const
Definition at line 137 of file SmartPtrPy.cpp.
operator*()
PyObject * Py::SmartPtr::operator* () const
Definition at line 117 of file SmartPtrPy.cpp.
operator=() [1/3]
SmartPtr & Py::SmartPtr::operator= (const Object & rhs)
Definition at line 97 of file SmartPtrPy.cpp.
operator=() [2/3]
SmartPtr & Py::SmartPtr::operator= (const SmartPtr & rhs)
Definition at line 91 of file SmartPtrPy.cpp.
References release().
operator=() [3/3]
SmartPtr & Py::SmartPtr::operator= (PyObject * rhsp)
Definition at line 103 of file SmartPtrPy.cpp.
ptr()
PyObject * Py::SmartPtr::ptr () const
Definition at line 122 of file SmartPtrPy.cpp.
References ptr().
Referenced by ptr(), Spreadsheet::PropertySheet::setPyObject(), SmartPtr(), and App::Extension::~Extension().
release()
void Py::SmartPtr::release () protected
Definition at line 64 of file SmartPtrPy.cpp.
Referenced by operator=().
set()
void Py::SmartPtr::set (PyObject * pyob, bool owned = false) protected
Definition at line 55 of file SmartPtrPy.cpp.
Referenced by draftguitools.gui_trackers.editTracker::move(), and SmartPtr().
The documentation for this class was generated from the following files:
SmartPtrPy.h
SmartPtrPy.cpp