FreeCAD: Gui::SoFCVectorizeSVGAction Class Reference
Gui::SoFCVectorizeSVGAction Class Reference
#include <SoFCVectorizeSVGAction.h>
Public Member Functions
SoFCVectorizeSVGAction ()
~SoFCVectorizeSVGAction () override
SoSVGVectorOutput * getSVGOutput () const
virtual void setBackgroundState (bool b)
virtual bool getBackgroundState () const
virtual void setLineWidth (double w)
virtual double getLineWidth () const
virtual void setUseMM (bool b)
virtual bool getUseMM () const
Static Public Member Functions
static void initClass ()
Protected Member Functions
void printHeader () const override
void printFooter () const override
void printBackground () const override
void printItem (const SoVectorizeItem *item) const override
void printViewport () const override
Friends
class SoFCVectorizeSVGActionP
Detailed Description
Definition at line 72 of file SoFCVectorizeSVGAction.h.
Constructor & Destructor Documentation
SoFCVectorizeSVGAction()
SoFCVectorizeSVGAction::SoFCVectorizeSVGAction ()
Definition at line 379 of file SoFCVectorizeSVGAction.cpp.
References SoFCVectorizeSVGActionP.
~SoFCVectorizeSVGAction()
SoFCVectorizeSVGAction::~SoFCVectorizeSVGAction () override
Definition at line 386 of file SoFCVectorizeSVGAction.cpp.
Member Function Documentation
getBackgroundState()
virtual bool Gui::SoFCVectorizeSVGAction::getBackgroundState () const inline virtual
Definition at line 85 of file SoFCVectorizeSVGAction.h.
Referenced by printBackground().
getLineWidth()
virtual double Gui::SoFCVectorizeSVGAction::getLineWidth () const inline virtual
Definition at line 87 of file SoFCVectorizeSVGAction.h.
Referenced by printBackground(), Gui::SoFCVectorizeSVGActionP::printLine(), and Gui::SoFCVectorizeSVGActionP::printTriangle().
getSVGOutput()
SoSVGVectorOutput * SoFCVectorizeSVGAction::getSVGOutput () const
Definition at line 392 of file SoFCVectorizeSVGAction.cpp.
Referenced by printBackground(), printFooter(), printHeader(), Gui::SoFCVectorizeSVGActionP::printLine(), Gui::SoFCVectorizeSVGActionP::printText(), and Gui::SoFCVectorizeSVGActionP::printTriangle().
getUseMM()
virtual bool Gui::SoFCVectorizeSVGAction::getUseMM () const inline virtual
Definition at line 89 of file SoFCVectorizeSVGAction.h.
Referenced by printHeader().
initClass()
void SoFCVectorizeSVGAction::initClass () static
Definition at line 374 of file SoFCVectorizeSVGAction.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
printBackground()
void SoFCVectorizeSVGAction::printBackground () const override protected
Definition at line 430 of file SoFCVectorizeSVGAction.cpp.
References getBackgroundState(), Gui::SoSVGVectorOutput::getFileStream(), getLineWidth(), getSVGOutput(), Path.Post.scripts.refactored_centroid_post::str, MovieTool::x, and MovieTool::y.
printFooter()
void SoFCVectorizeSVGAction::printFooter () const override protected
Definition at line 419 of file SoFCVectorizeSVGAction.cpp.
References Gui::SoSVGVectorOutput::getFileStream(), getSVGOutput(), and Path.Post.scripts.refactored_centroid_post::str.
printHeader()
void SoFCVectorizeSVGAction::printHeader () const override protected
Definition at line 397 of file SoFCVectorizeSVGAction.cpp.
References Gui::SoSVGVectorOutput::getFileStream(), getSVGOutput(), getUseMM(), and Path.Post.scripts.refactored_centroid_post::str.
printItem()
void SoFCVectorizeSVGAction::printItem (const SoVectorizeItem * item) const override protected
Definition at line 465 of file SoFCVectorizeSVGAction.cpp.
References SoVectorizeItem::IMAGE, SoVectorizeItem::LINE, SoVectorizeItem::POINT, Gui::SoFCVectorizeSVGActionP::printImage(), Gui::SoFCVectorizeSVGActionP::printLine(), Gui::SoFCVectorizeSVGActionP::printPoint(), Gui::SoFCVectorizeSVGActionP::printText(), Gui::SoFCVectorizeSVGActionP::printTriangle(), SoVectorizeItem::TEXT, SoVectorizeItem::TRIANGLE, and SoVectorizeItem::type.
printViewport()
void SoFCVectorizeSVGAction::printViewport () const override protected
Definition at line 426 of file SoFCVectorizeSVGAction.cpp.
setBackgroundState()
virtual void Gui::SoFCVectorizeSVGAction::setBackgroundState (bool b) inline virtual
Definition at line 84 of file SoFCVectorizeSVGAction.h.
setLineWidth()
virtual void Gui::SoFCVectorizeSVGAction::setLineWidth (double w) inline virtual
Definition at line 86 of file SoFCVectorizeSVGAction.h.
setUseMM()
virtual void Gui::SoFCVectorizeSVGAction::setUseMM (bool b) inline virtual
Definition at line 88 of file SoFCVectorizeSVGAction.h.
Friends And Related Function Documentation
SoFCVectorizeSVGActionP
friend class SoFCVectorizeSVGActionP friend
Definition at line 100 of file SoFCVectorizeSVGAction.h.
Referenced by SoFCVectorizeSVGAction().
The documentation for this class was generated from the following files:
SoFCVectorizeSVGAction.h
SoFCVectorizeSVGAction.cpp