FreeCAD: geoff_geometry::Plane Class Reference
geoff_geometry::Plane Class Reference
#include <geometry.h>
Public Member Functions
Plane ()
Plane (double dist, const Vector3d &n)
Plane (const Point3d &p0, const Point3d &p1, const Point3d &p2)
Plane (const Point3d &p0, const Vector3d &n, bool normalise=true)
double Dist (const Point3d &p) const
bool Intof (const Line &l, Point3d &intof, double &t) const
bool Intof (const Plane &pl, Line &intof) const
bool Intof (const Plane &pl0, const Plane &pl1, Point3d &intof) const
Point3d Near (const Point3d &p) const
void Mirrored (Matrix *m)
Public Attributes
bool ok
double d
Vector3d normal
Friends
wostream & operator<< (wostream &op, Plane &pl)
Detailed Description
Definition at line 1237 of file geometry.h.
Constructor & Destructor Documentation
Plane() [1/4]
geoff_geometry::Plane::Plane () inline
Definition at line 1246 of file geometry.h.
Plane() [2/4]
geoff_geometry::Plane::Plane (double dist, const Vector3d & n)
Definition at line 970 of file Construction.cpp.
References d, DraftVecUtils::dist(), normal, geoff_geometry::Vector3d::normalise(), NULL_VECTOR, and ok.
Plane() [3/4]
geoff_geometry::Plane::Plane (const Point3d & p0, const Point3d & p1, const Point3d & p2)
Definition at line 950 of file Construction.cpp.
References d, normal, geoff_geometry::Vector3d::normalise(), NULL_VECTOR, and ok.
Plane() [4/4]
geoff_geometry::Plane::Plane (const Point3d & p0, const Vector3d & n, bool normalise = true)
Definition at line 959 of file Construction.cpp.
References d, normal, geoff_geometry::Vector3d::normalise(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf::normalise(), NULL_VECTOR, ok, and TestSpreadsheet::v.
Member Function Documentation
Dist()
double geoff_geometry::Plane::Dist (const Point3d & p) const
Definition at line 983 of file Construction.cpp.
References d, normal, and buildPsets::p.
Referenced by Near().
Intof() [1/3]
bool geoff_geometry::Plane::Intof (const Line & l, Point3d & intof, double & t) const
Definition at line 995 of file Construction.cpp.
References d, RobotExample::l, normal, InitGui::t, and geoff_geometry::UNIT_VECTOR_TOLERANCE.
Referenced by Intof(), and geoff_geometry::tangential_arc().
Intof() [2/3]
bool geoff_geometry::Plane::Intof (const Plane & pl, Line & intof) const
Definition at line 1012 of file Construction.cpp.
References a, SCL.SimpleDataTypes::b, d, dot(), geoff_geometry::Line::length, normal, NULL_VECTOR, geoff_geometry::Line::ok, geoff_geometry::Line::p0, and geoff_geometry::Line::v.
Intof() [3/3]
bool geoff_geometry::Plane::Intof (const Plane & pl0, const Plane & pl1, Point3d & intof) const
Definition at line 1035 of file Construction.cpp.
References Intof(), and InitGui::t.
Mirrored()
void geoff_geometry::Plane::Mirrored (Matrix * m)
Definition at line 645 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References d, geoff_geometry::Matrix::e, geoff_geometry::Vector3d::getx(), geoff_geometry::Vector3d::gety(), geoff_geometry::Vector3d::getz(), geoff_geometry::Matrix::m_mirrored, geoff_geometry::Matrix::m_unit, normal, and geoff_geometry::Matrix::Unit().
Near()
Point3d geoff_geometry::Plane::Near (const Point3d & p) const
Definition at line 989 of file Construction.cpp.
References Dist(), normal, and buildPsets::p.
Friends And Related Function Documentation
operator<<
wostream& operator<< (wostream & op, Plane & pl) friend
Definition at line 98 of file Construction.cpp.
Member Data Documentation
d
double geoff_geometry::Plane::d
Definition at line 1243 of file geometry.h.
Referenced by Dist(), Intof(), Mirrored(), geoff_geometry::operator<<(), and Plane().
normal
Vector3d geoff_geometry::Plane::normal
Definition at line 1244 of file geometry.h.
Referenced by Dist(), draftguitools.gui_trackers.arcTracker::getAngle(), draftguitools.gui_trackers.arcTracker::getDeviation(), ArchRoof._Roof::getPerpendicular(), Intof(), Mirrored(), Near(), geoff_geometry::operator<<(), Plane(), draftguitools.gui_trackers.arcTracker::recompute(), and draftguitools.gui_trackers.arcTracker::setBy3Points().
ok
bool geoff_geometry::Plane::ok
Definition at line 1242 of file geometry.h.
Referenced by geoff_geometry::operator<<(), and Plane().
The documentation for this class was generated from the following files:
geometry.h
Construction.cpp
Mod/CAM/libarea/kurve/Matrix.cpp