FreeCAD: AppPartGui.cpp File Reference
AppPartGui.cpp File Reference
#include "PreCompiled.h"
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/PyObjectBase.h>
#include <Gui/Application.h>
#include <Gui/BitmapFactory.h>
#include <Gui/DlgPreferencesImp.h>
#include <Gui/WidgetFactory.h>
#include <Gui/Language/Translator.h>
#include "AttacherTexts.h"
#include "PropertyEnumAttacherItem.h"
#include "DlgSettings3DViewPartImp.h"
#include "DlgSettingsGeneral.h"
#include "DlgSettingsObjectColor.h"
#include "SoBrepEdgeSet.h"
#include "SoBrepFaceSet.h"
#include "SoBrepPointSet.h"
#include "SoFCShapeObject.h"
#include "ViewProvider.h"
#include "ViewProvider2DObject.h"
#include "ViewProviderAttachExtension.h"
#include "ViewProviderDatum.h"
#include "ViewProviderGridExtension.h"
#include "ViewProviderBoolean.h"
#include "ViewProviderBox.h"
#include "ViewProviderCircleParametric.h"
#include "ViewProviderCompound.h"
#include "ViewProviderConeParametric.h"
#include "ViewProviderCurveNet.h"
#include "ViewProviderCylinderParametric.h"
#include "ViewProviderEllipseParametric.h"
#include "ViewProviderExt.h"
#include "ViewProviderExtrusion.h"
#include "ViewProviderScale.h"
#include "ViewProviderHelixParametric.h"
#include "ViewProviderPrimitive.h"
#include "ViewProviderPython.h"
#include "ViewProviderImport.h"
#include "ViewProviderLineParametric.h"
#include "ViewProviderMirror.h"
#include "ViewProviderPlaneParametric.h"
#include "ViewProviderPointParametric.h"
#include "ViewProviderPrism.h"
#include "ViewProviderProjectOnSurface.h"
#include "ViewProviderRegularPolygon.h"
#include "ViewProviderRuledSurface.h"
#include "ViewProviderSphereParametric.h"
#include "ViewProviderSpline.h"
#include "ViewProviderTorusParametric.h"
#include "Workbench.h"
#include "WorkbenchManipulator.h"
Classes
class PartGui::Module
Namespaces
PartGui
Functions
void CreatePartCommands ()
void CreateSimplePartCommands ()
void CreateParamPartCommands ()
void CreatePartSelectCommands ()
void loadPartResource ()
PyObject * PartGui::initModule ()
PyMOD_INIT_FUNC (PartGui)
Function Documentation
CreateParamPartCommands()
void CreateParamPartCommands ()
Definition at line 268 of file CommandParametric.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
CreatePartCommands()
void CreatePartCommands ()
Definition at line 2398 of file Mod/Part/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
CreatePartSelectCommands()
void CreatePartSelectCommands ()
Definition at line 263 of file CommandFilter.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
CreateSimplePartCommands()
void CreateSimplePartCommands ()
Definition at line 480 of file CommandSimple.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
loadPartResource()
void loadPartResource ()
Definition at line 88 of file AppPartGui.cpp.
References Gui::Translator::instance(), and Gui::Translator::refresh().
Referenced by PyMOD_INIT_FUNC().
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (PartGui)
Definition at line 117 of file AppPartGui.cpp.
References Gui::ViewProviderBuilder::add(), Gui::BitmapFactoryInst::addPath(), Gui::BitmapFactory(), Base::Console(), CreateParamPartCommands(), CreatePartCommands(), CreatePartSelectCommands(), CreateSimplePartCommands(), SCL.SimpleDataTypes::e, Base::Persistence::getClassTypeId(), SIM::Coin3D::Quarter::Quarter::init(), Base::Persistence::init(), Base::BaseClass::init(), App::Extension::init(), Gui::PropertyEditor::PropertyEnumItem::init(), PartGui::SoBrepEdgeSet::initClass(), PartGui::SoBrepPointSet::initClass(), PartGui::SoFCControlPoints::initClass(), PartGui::SoBrepFaceSet::initClass(), PartGui::initModule(), Gui::WorkbenchManipulator::installManipulator(), Gui::Application::Instance, Base::Interpreter(), loadPartResource(), Base::ConsoleSingleton::Log(), AttacherGui::AttacherGuiPy::Methods, PyMOD_Return, Arch::QT_TRANSLATE_NOOP, Base::PyException::ReportException(), Base::InterpreterSingleton::runString(), Base::InterpreterSingleton::runStringObject(), and Gui::Dialog::DlgPreferencesImp::setGroupData().