FreeCAD: ViewProvider.cpp File Reference
Gui/ViewProvider.cpp File Reference
#include "PreCompiled.h"
#include <QApplication>
#include <QTimer>
#include <Inventor/SoPickedPoint.h>
#include <Inventor/actions/SoGetBoundingBoxAction.h>
#include <Inventor/details/SoDetail.h>
#include <Inventor/events/SoKeyboardEvent.h>
#include <Inventor/events/SoLocation2Event.h>
#include <Inventor/events/SoMouseButtonEvent.h>
#include <Inventor/nodes/SoSeparator.h>
#include <Inventor/nodes/SoSwitch.h>
#include <Inventor/nodes/SoTransform.h>
#include <Base/BoundBox.h>
#include <Base/Console.h>
#include <Base/Exception.h>
#include <Base/Matrix.h>
#include "Inventor/SoMouseWheelEvent.h"
#include "Inventor/SoFCTransform.h"
#include "ViewProvider.h"
#include "ActionFunction.h"
#include "Application.h"
#include "BitmapFactory.h"
#include "Document.h"
#include "SoFCDB.h"
#include "View3DInventor.h"
#include "View3DInventorViewer.h"
#include "ViewParams.h"
#include "ViewProviderExtension.h"
#include "ViewProviderLink.h"
#include "ViewProviderPy.h"
#include <Utilities.h>
#include <boost/graph/topological_sort.hpp>
Namespaces
Gui
Typedefs
using Gui::Graph = boost::adjacency_list< boost::vecS, boost::vecS, boost::directedS, boost::no_property, boost::no_property, boost::no_property, boost::listS >
using Gui::Vertex = boost::graph_traits< Graph >::vertex_descriptor
using Gui::Edge = boost::graph_traits< Graph >::edge_descriptor
Functions
void Gui::coinRemoveAllChildren (SoGroup *group)
void highlight (const HighlightMode &high)
void Gui::addNodes (Graph &graph, std::map< SoNode *, Vertex > &vertexNodeMap, SoNode *node)
Function Documentation
highlight()
void highlight (const HighlightMode & high)
Definition at line 191 of file Gui/ViewProvider.cpp.
Referenced by Gui::SoFCUnifiedSelection::applySettings(), Gui::SoFCSelection::applySettings(), Gui::ViewProviderDatum::attach(), Gui::ViewProviderAnnotation::attach(), Gui::ViewProviderBuilder::createSelection(), TechDrawGui::QGIViewPart::drawHighlight(), TechDrawGui::QGIViewPart::highlightMoved(), Gui::View3DSettings::OnChange(), and Gui::DocumentObjectItem::setHighlight().