FreeCAD: Gui::MDIViewPyWrap Class Reference
Gui::MDIViewPyWrap Class Reference
#include <MDIViewPyWrap.h>
Public Member Functions
MDIViewPyWrap (const Py::Object &py, Gui::Document *pcDocument, QWidget *parent=nullptr, Qt::WindowFlags wflags=Qt::WindowFlags())
~MDIViewPyWrap () override
bool onMsg (const char *pMsg, const char **ppReturn) override
Message handler.
bool onHasMsg (const char *pMsg) const override
Message handler test.
bool canClose () override
overwrite when checking on close state
PyObject * getPyObject () override
Public Member Functions inherited from Gui::MDIView
MDIView (Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
~MDIView () override
void onRelabel (Gui::Document *pDoc) override
get called when the document is updated
virtual void viewAll ()
QString buildWindowTitle () const
build window title
void deleteSelf () override
delete itself
void savePrinterSettings (QPrinter *printer)
void restorePrinterSettings (QPrinter *printer)
QSize minimumSizeHint () const override
virtual void setCurrentViewMode (ViewMode mode)
ViewMode currentViewMode () const
template<typename _T >
_T getActiveObject (const char *name, App::DocumentObject **parent=nullptr, std::string *subname=nullptr) const
access getter for the active object list
void setActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr)
bool hasActiveObject (const char *n) const
bool isActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr) const
virtual bool containsViewProvider (const ViewProvider *) const
containsViewProvider Checks if the given view provider is part of this view. The default implementation returns false.
Public Member Functions inherited from Gui::BaseView
BaseView (Gui::Document *pcDocument=nullptr)
~BaseView () override
void setDocument (Gui::Document *pcDocument)
sets the view to another document (called by Application)
void onClose ()
is sent from the document in order to close the document
Gui::Document * getGuiDocument () const
returns the document the view is attached to
App::Document * getAppDocument () const
returns the document the view is attached to
bool isPassive () const
indicates if the view is in passive mode
virtual void onUpdate ()
get called when the document is updated
virtual void onRename (Gui::Document *)
get called when the document is renamed (change of its internal name)
virtual const char * getName () const
returns the name of the view (important for messages)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Printing
void print () override
void printPdf () override
void printPreview () override
void print (QPrinter *printer) override
Undo/Redo actions
QStringList undoActions () const override
QStringList redoActions () const override
Additional Inherited Members
Public Types inherited from Gui::MDIView
enum ViewMode { Child, TopLevel, FullScreen }
MDI view mode enum.
Public Slots inherited from Gui::MDIView
virtual void print (QPrinter *printer)
virtual void setOverrideCursor (const QCursor &)
virtual void restoreOverrideCursor ()
Signals inherited from Gui::MDIView
void message (const QString &, int)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Slots inherited from Gui::MDIView
virtual void windowStateChanged (QWidget *)
Protected Member Functions inherited from Gui::MDIView
void closeEvent (QCloseEvent *e) override
void changeEvent (QEvent *e) override
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::MDIView
PyObject * pythonObject
Protected Attributes inherited from Gui::BaseView
Gui::Document * _pcDocument
bool bIsDetached {false}
bool bIsPassive {false}
Detailed Description
Definition at line 55 of file MDIViewPyWrap.h.
Constructor & Destructor Documentation
MDIViewPyWrap()
MDIViewPyWrap::MDIViewPyWrap (const Py::Object & py, Gui::Document * pcDocument, QWidget * parent = nullptr, Qt::WindowFlags wflags = Qt::WindowFlags()) explicit
View constructor Attach the view to the given document. If the document is zero the view will attach to the active document. Be aware, there isn't always an active document.
Definition at line 168 of file MDIViewPyWrap.cpp.
References Base::PyException::ReportException(), and Plot::title().
~MDIViewPyWrap()
MDIViewPyWrap::~MDIViewPyWrap () override
View destructor Detach the view from the document, if attached.
Definition at line 189 of file MDIViewPyWrap.cpp.
Member Function Documentation
canClose()
bool MDIViewPyWrap::canClose () override virtual
overwrite when checking on close state
Reimplemented from Gui::MDIView.
Definition at line 237 of file MDIViewPyWrap.cpp.
References Gui::MDIView::canClose(), and Base::PyException::ReportException().
getPyObject()
PyObject * MDIViewPyWrap::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Gui::MDIView.
Definition at line 194 of file MDIViewPyWrap.cpp.
References Gui::MDIView::getPyObject().
Referenced by Gui::MainWindowPy::addWindow().
onHasMsg()
bool MDIViewPyWrap::onHasMsg (const char * pMsg) const override virtual
Message handler test.
Reimplemented from Gui::MDIView.
Definition at line 218 of file MDIViewPyWrap.cpp.
References Gui::MDIView::onHasMsg(), and Base::PyException::ReportException().
onMsg()
bool MDIViewPyWrap::onMsg (const char * pMsg, const char ** ppReturn) override virtual
Message handler.
Reimplemented from Gui::MDIView.
Definition at line 199 of file MDIViewPyWrap.cpp.
References Gui::MDIView::onMsg(), and Base::PyException::ReportException().
print() [1/2]
void MDIViewPyWrap::print () override virtual
Print content of view
Reimplemented from Gui::MDIView.
Definition at line 268 of file MDIViewPyWrap.cpp.
References Gui::MDIView::print(), and Base::PyException::ReportException().
print [2/2]
void MDIViewPyWrap::print (QPrinter * printer) override slot
Definition at line 253 of file MDIViewPyWrap.cpp.
References Gui::MDIView::print(), and Base::PyException::ReportException().
printPdf()
void MDIViewPyWrap::printPdf () override virtual
Print to PDF file
Reimplemented from Gui::MDIView.
Definition at line 283 of file MDIViewPyWrap.cpp.
References Gui::MDIView::printPdf(), and Base::PyException::ReportException().
printPreview()
void MDIViewPyWrap::printPreview () override virtual
Show a preview dialog
Reimplemented from Gui::MDIView.
Definition at line 298 of file MDIViewPyWrap.cpp.
References Gui::MDIView::printPreview(), and Base::PyException::ReportException().
redoActions()
QStringList MDIViewPyWrap::redoActions () const override virtual
Reimplemented from Gui::MDIView.
Definition at line 329 of file MDIViewPyWrap.cpp.
References Gui::MDIView::redoActions(), and Base::PyException::ReportException().
undoActions()
QStringList MDIViewPyWrap::undoActions () const override virtual
Reimplemented from Gui::MDIView.
Definition at line 313 of file MDIViewPyWrap.cpp.
References Base::PyException::ReportException(), and Gui::MDIView::undoActions().
The documentation for this class was generated from the following files:
MDIViewPyWrap.h
MDIViewPyWrap.cpp