FreeCAD: Gui::SoAxisCrossKit Class Reference
Gui::SoAxisCrossKit Class Reference
#include <SoAxisCrossKit.h>
Public Member Functions
SoAxisCrossKit ()
SbBool affectsState () const override
void addWriteReference (SoOutput *out, SbBool isfromfield=false) override
void getBoundingBox (SoGetBoundingBoxAction *action) override
Static Public Member Functions
static void initClass ()
Detailed Description
Definition at line 62 of file SoAxisCrossKit.h.
Constructor & Destructor Documentation
SoAxisCrossKit()
SoAxisCrossKit::SoAxisCrossKit ()
Definition at line 125 of file SoAxisCrossKit.cpp.
Member Function Documentation
addWriteReference()
void SoAxisCrossKit::addWriteReference (SoOutput * out, SbBool isfromfield = false) override
Definition at line 158 of file SoAxisCrossKit.cpp.
affectsState()
SbBool SoAxisCrossKit::affectsState () const override
Definition at line 153 of file SoAxisCrossKit.cpp.
getBoundingBox()
void SoAxisCrossKit::getBoundingBox (SoGetBoundingBoxAction * action) override
Definition at line 163 of file SoAxisCrossKit.cpp.
References Path.Post.scripts.dynapath_4060_post::action.
initClass()
void SoAxisCrossKit::initClass () static
Definition at line 120 of file SoAxisCrossKit.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
The documentation for this class was generated from the following files:
SoAxisCrossKit.h
SoAxisCrossKit.cpp