FreeCAD: Robot::Simulation Class Reference
Robot::Simulation Class Reference
#include <Simulation.h>
Public Member Functions
Simulation (const Trajectory &Trac, Robot6Axis &Rob)
Constructor.
virtual ~Simulation ()
double getLength ()
double getDuration ()
Base::Placement getPosition ()
double getVelocity ()
void step (double tick)
void setToWaypoint (unsigned int n)
void setToTime (float t)
void reset ()
Public Attributes
double Pos {0.0}
double Axis [6] {}
double startAxis [6] {}
Trajectory Trac
Robot6Axis & Rob
Base::Placement Tool
Detailed Description
Algo class for projecting shapes and creating SVG output of it
Definition at line 57 of file Simulation.h.
Constructor & Destructor Documentation
Simulation()
Simulation::Simulation (const Trajectory & Trac, Robot::Robot6Axis & Rob)
Constructor.
Definition at line 36 of file Simulation.cpp.
References Robot::Robot6Axis::getAxis(), Robot::Trajectory::getSize(), Rob, setToTime(), startAxis, and Trac.
~Simulation()
Simulation::~Simulation () virtual default
Member Function Documentation
getDuration()
double Robot::Simulation::getDuration () inline
Definition at line 89 of file Simulation.h.
getLength()
double Robot::Simulation::getLength () inline
Definition at line 85 of file Simulation.h.
getPosition()
Base::Placement Robot::Simulation::getPosition () inline
Definition at line 94 of file Simulation.h.
getVelocity()
double Robot::Simulation::getVelocity () inline
Definition at line 98 of file Simulation.h.
reset()
void Simulation::reset ()
Definition at line 78 of file Simulation.cpp.
References Axis, Robot::Robot6Axis::getAxis(), Robot::Trajectory::getPosition(), Base::Placement::inverse(), Rob, Robot::Robot6Axis::setAxis(), Robot::Robot6Axis::setTo(), startAxis, Tool, and Trac.
Referenced by RobotGui::TaskTrajectory::setTo().
setToTime()
void Simulation::setToTime (float t)
Definition at line 64 of file Simulation.cpp.
References Axis, Robot::Robot6Axis::getAxis(), Robot::Trajectory::getPosition(), Base::Placement::inverse(), Pos, Rob, Robot::Robot6Axis::setTo(), InitGui::t, Tool, and Trac.
Referenced by RobotGui::TrajectorySimulate::setTo(), RobotGui::TaskTrajectory::setTo(), and Simulation().
setToWaypoint()
void Simulation::setToWaypoint (unsigned int n)
Definition at line 61 of file Simulation.cpp.
step()
void Simulation::step (double tick)
Definition at line 56 of file Simulation.cpp.
References Pos.
Member Data Documentation
Axis
double Robot::Simulation::Axis[6] {}
Definition at line 110 of file Simulation.h.
Referenced by reset(), RobotGui::TrajectorySimulate::setTo(), RobotGui::TaskTrajectory::setTo(), and setToTime().
Pos
double Robot::Simulation::Pos {0.0}
Definition at line 109 of file Simulation.h.
Referenced by setToTime(), and step().
Rob
Robot6Axis& Robot::Simulation::Rob
Definition at line 114 of file Simulation.h.
Referenced by reset(), RobotGui::TrajectorySimulate::setTo(), RobotGui::TaskTrajectory::setTo(), setToTime(), and Simulation().
startAxis
double Robot::Simulation::startAxis[6] {}
Definition at line 111 of file Simulation.h.
Referenced by reset(), and Simulation().
Tool
Base::Placement Robot::Simulation::Tool
Definition at line 115 of file Simulation.h.
Referenced by reset(), RobotGui::TaskTrajectory::setTo(), setToTime(), RobotGui::TaskTrajectory::TaskTrajectory(), and RobotGui::TrajectorySimulate::TrajectorySimulate().
Trac
Trajectory Robot::Simulation::Trac
Definition at line 113 of file Simulation.h.
Referenced by reset(), setToTime(), and Simulation().
The documentation for this class was generated from the following files:
Simulation.h
Simulation.cpp