FreeCAD: TechDraw::GeometryObject Class Reference
TechDraw::GeometryObject Class Reference
#include <GeometryObject.h>
Public Member Functions
GeometryObject (const std::string &parent, TechDraw::DrawView *parentObj)
Constructor.
virtual ~GeometryObject ()
void clear ()
Base::BoundBox3d calcBoundingBox () const
Returns 2D bounding box.
const std::vector< VertexPtr > & getVertexGeometry () const
const BaseGeomPtrVector & getEdgeGeometry () const
const BaseGeomPtrVector getVisibleFaceEdges (bool smooth, bool seam) const
const std::vector< FacePtr > & getFaceGeometry () const
void setVertexGeometry (std::vector< VertexPtr > newVerts)
void setEdgeGeometry (BaseGeomPtrVector newGeoms)
void projectShape (const TopoDS_Shape &input, const gp_Ax2 &viewAxis)
void projectShapeWithPolygonAlgo (const TopoDS_Shape &input, const gp_Ax2 &viewAxis)
set up a hidden line remover and project a shape with it
void makeTDGeometry ()
void extractGeometry (edgeClass category, bool visible)
add edges meeting filter criteria for category, visibility
void addFaceGeom (FacePtr f)
add a Face to Face Geometry
void clearFaceGeom ()
empty Face geometry
void setIsoCount (int i)
void setParentName (std::string n)
void isPerspective (bool b)
bool isPerspective ()
void usePolygonHLR (bool b)
bool usePolygonHLR () const
void setFocus (double f)
double getFocus ()
void setScrubCount (int count)
void pruneVertexGeom (Base::Vector3d center, double radius)
TopoDS_Shape getVisHard ()
TopoDS_Shape getVisOutline ()
TopoDS_Shape getVisSmooth ()
TopoDS_Shape getVisSeam ()
TopoDS_Shape getVisIso ()
TopoDS_Shape getHidHard ()
TopoDS_Shape getHidOutline ()
TopoDS_Shape getHidSmooth ()
TopoDS_Shape getHidSeam ()
TopoDS_Shape getHidIso ()
void addVertex (TechDraw::VertexPtr v)
void addEdge (TechDraw::BaseGeomPtr bg)
int addCosmeticVertex (CosmeticVertex *cv)
int addCosmeticVertex (Base::Vector3d pos)
int addCosmeticVertex (Base::Vector3d pos, std::string tagString)
int addCosmeticEdge (CosmeticEdge *ce)
int addCosmeticEdge (Base::Vector3d start, Base::Vector3d end)
int addCosmeticEdge (Base::Vector3d start, Base::Vector3d end, std::string tagString)
int addCosmeticEdge (TechDraw::BaseGeomPtr base, std::string tagString)
int addCenterLine (TechDraw::BaseGeomPtr bg, std::string tag)
Static Public Member Functions
static TopoDS_Shape projectSimpleShape (const TopoDS_Shape &shape, const gp_Ax2 &CS)
static TopoDS_Shape simpleProjection (const TopoDS_Shape &shape, const gp_Ax2 &projCS)
static TopoDS_Shape projectFace (const TopoDS_Shape &face, const gp_Ax2 &CS)
Protected Member Functions
void addGeomFromCompound (TopoDS_Shape edgeCompound, edgeClass category, bool visible)
update edgeGeom and vertexGeom from Compound of edges
TechDraw::DrawViewDetail * isParentDetail ()
bool isWithinArc (double theta, double first, double last, bool cw) const
bool findVertex (Base::Vector3d v)
does this GeometryObject already have this vertex
Protected Attributes
TopoDS_Shape visHard
TopoDS_Shape visOutline
TopoDS_Shape visSmooth
TopoDS_Shape visSeam
TopoDS_Shape visIso
TopoDS_Shape hidHard
TopoDS_Shape hidOutline
TopoDS_Shape hidSmooth
TopoDS_Shape hidSeam
TopoDS_Shape hidIso
BaseGeomPtrVector edgeGeom
std::vector< VertexPtr > vertexGeom
std::vector< FacePtr > faceGeom
std::string m_parentName
TechDraw::DrawView * m_parent
int m_isoCount
bool m_isPersp
double m_focus
bool m_usePolygonHLR
int m_scrubCount
Detailed Description
Definition at line 63 of file GeometryObject.h.
Constructor & Destructor Documentation
GeometryObject()
GeometryObject::GeometryObject (const std::string & parent, TechDraw::DrawView * parentObj)
Constructor.
Definition at line 84 of file GeometryObject.cpp.
~GeometryObject()
GeometryObject::~GeometryObject () virtual
Definition at line 90 of file GeometryObject.cpp.
References clear().
Member Function Documentation
addCenterLine()
int GeometryObject::addCenterLine (TechDraw::BaseGeomPtr bg, std::string tag)
Definition at line 730 of file GeometryObject.cpp.
References edgeGeom, and Dice3DS.dom3ds::tag.
addCosmeticEdge() [1/4]
int GeometryObject::addCosmeticEdge (Base::Vector3d start, Base::Vector3d end)
Definition at line 685 of file GeometryObject.cpp.
References TechDraw::BaseGeom::baseFactory(), SCL.SimpleDataTypes::e, and edgeGeom.
addCosmeticEdge() [2/4]
int GeometryObject::addCosmeticEdge (Base::Vector3d start, Base::Vector3d end, std::string tagString)
Definition at line 701 of file GeometryObject.cpp.
References TechDraw::BaseGeom::baseFactory(), and edgeGeom.
addCosmeticEdge() [3/4]
int GeometryObject::addCosmeticEdge (CosmeticEdge * ce)
Definition at line 670 of file GeometryObject.cpp.
References SCL.SimpleDataTypes::e, edgeGeom, TechDraw::DrawView::getScale(), TechDraw::CosmeticEdge::getTagAsString(), m_parent, and TechDraw::CosmeticEdge::scaledGeometry().
addCosmeticEdge() [4/4]
int GeometryObject::addCosmeticEdge (TechDraw::BaseGeomPtr base, std::string tagString)
Definition at line 717 of file GeometryObject.cpp.
References edgeGeom.
addCosmeticVertex() [1/3]
int GeometryObject::addCosmeticVertex (Base::Vector3d pos)
Definition at line 643 of file GeometryObject.cpp.
References RobotExample::pos, TestSpreadsheet::v, and vertexGeom.
addCosmeticVertex() [2/3]
int GeometryObject::addCosmeticVertex (Base::Vector3d pos, std::string tagString)
Definition at line 654 of file GeometryObject.cpp.
References RobotExample::pos, TestSpreadsheet::v, and vertexGeom.
addCosmeticVertex() [3/3]
int GeometryObject::addCosmeticVertex (CosmeticVertex * cv)
Definition at line 628 of file GeometryObject.cpp.
References TechDraw::DrawView::getScale(), TechDraw::CosmeticVertex::getTagAsString(), m_parent, RobotExample::pos, TechDraw::CosmeticVertex::scaled(), TestSpreadsheet::v, and vertexGeom.
addEdge()
void GeometryObject::addEdge (TechDraw::BaseGeomPtr bg)
Definition at line 620 of file GeometryObject.cpp.
References edgeGeom.
addFaceGeom()
void GeometryObject::addFaceGeom (FacePtr f)
add a Face to Face Geometry
Definition at line 748 of file GeometryObject.cpp.
References SCL.SimpleDataTypes::f, and faceGeom.
addGeomFromCompound()
void GeometryObject::addGeomFromCompound (TopoDS_Shape edgeCompound, edgeClass category, bool visible) protected
update edgeGeom and vertexGeom from Compound of edges
Definition at line 512 of file GeometryObject.cpp.
References importers.importWebGL::base, TechDraw::BaseGeom::baseFactory(), src.Mod.PartDesign.Scripts.Gear::c1, edgeGeom, SplineSurface::i, TechDraw::DrawUtil::isCrazy(), TechDraw::DrawUtil::isZeroEdge(), m_scrubCount, TechDraw::DrawProjectSplit::removeOverlapEdges(), TechDraw::DrawUtil::shapeToVector(), draftgeoutils.general::v1(), TechDraw::DrawUtil::vectorToCompound(), and vertexGeom.
Referenced by extractGeometry().
addVertex()
void GeometryObject::addVertex (TechDraw::VertexPtr v)
Definition at line 618 of file GeometryObject.cpp.
References TestSpreadsheet::v, and vertexGeom.
calcBoundingBox()
Base::BoundBox3d GeometryObject::calcBoundingBox () const
Returns 2D bounding box.
Definition at line 801 of file GeometryObject.cpp.
References edgeGeom, xMax, xMin, yMax, and yMin.
clear()
void GeometryObject::clear ()
Definition at line 134 of file GeometryObject.cpp.
References edgeGeom, faceGeom, and vertexGeom.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__(), projectShape(), projectShapeWithPolygonAlgo(), and ~GeometryObject().
clearFaceGeom()
void GeometryObject::clearFaceGeom ()
empty Face geometry
Definition at line 745 of file GeometryObject.cpp.
References faceGeom.
extractGeometry()
void GeometryObject::extractGeometry (edgeClass category, bool visible)
add edges meeting filter criteria for category, visibility
Definition at line 455 of file GeometryObject.cpp.
References addGeomFromCompound(), Base::Console(), TechDraw::ecHARD, TechDraw::ecOUTLINE, TechDraw::ecSEAM, TechDraw::ecSMOOTH, TechDraw::ecUVISO, hidHard, hidIso, hidOutline, hidSeam, hidSmooth, visHard, visIso, visOutline, visSeam, visSmooth, and Base::ConsoleSingleton::Warning().
Referenced by makeTDGeometry().
findVertex()
bool GeometryObject::findVertex (Base::Vector3d v) protected
does this GeometryObject already have this vertex
Definition at line 838 of file GeometryObject.cpp.
References DraftVecUtils::dist(), FreeCADInit::Length, TestSpreadsheet::v, and vertexGeom.
getEdgeGeometry()
const BaseGeomPtrVector& TechDraw::GeometryObject::getEdgeGeometry () const inline
Definition at line 76 of file GeometryObject.h.
getFaceGeometry()
const std::vector<FacePtr>& TechDraw::GeometryObject::getFaceGeometry () const inline
Definition at line 78 of file GeometryObject.h.
getFocus()
double TechDraw::GeometryObject::getFocus () inline
Definition at line 99 of file GeometryObject.h.
getHidHard()
TopoDS_Shape TechDraw::GeometryObject::getHidHard () inline
Definition at line 110 of file GeometryObject.h.
getHidIso()
TopoDS_Shape TechDraw::GeometryObject::getHidIso () inline
Definition at line 114 of file GeometryObject.h.
getHidOutline()
TopoDS_Shape TechDraw::GeometryObject::getHidOutline () inline
Definition at line 111 of file GeometryObject.h.
getHidSeam()
TopoDS_Shape TechDraw::GeometryObject::getHidSeam () inline
Definition at line 113 of file GeometryObject.h.
getHidSmooth()
TopoDS_Shape TechDraw::GeometryObject::getHidSmooth () inline
Definition at line 112 of file GeometryObject.h.
getVertexGeometry()
const std::vector<VertexPtr>& TechDraw::GeometryObject::getVertexGeometry () const inline
Definition at line 75 of file GeometryObject.h.
Referenced by pruneVertexGeom().
getVisHard()
TopoDS_Shape TechDraw::GeometryObject::getVisHard () inline
Definition at line 105 of file GeometryObject.h.
getVisibleFaceEdges()
const BaseGeomPtrVector GeometryObject::getVisibleFaceEdges (bool smooth, bool seam) const
Definition at line 92 of file GeometryObject.cpp.
References SCL.SimpleDataTypes::e, TechDraw::ecHARD, TechDraw::ecOUTLINE, TechDraw::ecSEAM, TechDraw::ecSMOOTH, edgeGeom, and result.
getVisIso()
TopoDS_Shape TechDraw::GeometryObject::getVisIso () inline
Definition at line 109 of file GeometryObject.h.
getVisOutline()
TopoDS_Shape TechDraw::GeometryObject::getVisOutline () inline
Definition at line 106 of file GeometryObject.h.
getVisSeam()
TopoDS_Shape TechDraw::GeometryObject::getVisSeam () inline
Definition at line 108 of file GeometryObject.h.
getVisSmooth()
TopoDS_Shape TechDraw::GeometryObject::getVisSmooth () inline
Definition at line 107 of file GeometryObject.h.
isParentDetail()
TechDraw::DrawViewDetail * GeometryObject::isParentDetail () protected
Definition at line 750 of file GeometryObject.cpp.
References m_parent.
isPerspective() [1/2]
bool TechDraw::GeometryObject::isPerspective () inline
Definition at line 95 of file GeometryObject.h.
isPerspective() [2/2]
void TechDraw::GeometryObject::isPerspective (bool b) inline
Definition at line 94 of file GeometryObject.h.
References SCL.SimpleDataTypes::b.
isWithinArc()
bool GeometryObject::isWithinArc (double theta, double first, double last, bool cw) const protected
Returns true iff angle theta is in [first, last], where the arc goes clockwise (cw=true) or counterclockwise (cw=false) from first to last.
Definition at line 760 of file GeometryObject.cpp.
References Base::fmod(), and M_PI.
makeTDGeometry()
void GeometryObject::makeTDGeometry ()
Definition at line 251 of file GeometryObject.cpp.
References TechDraw::ecHARD, TechDraw::ecOUTLINE, TechDraw::ecSEAM, TechDraw::ecSMOOTH, TechDraw::ecUVISO, extractGeometry(), App::PropertyInteger::getValue(), App::PropertyBool::getValue(), TechDraw::DrawViewPart::HardHidden, TechDraw::DrawViewPart::IsoCount, TechDraw::DrawViewPart::IsoHidden, TechDraw::DrawViewPart::IsoVisible, m_parent, TechDraw::DrawViewPart::SeamHidden, TechDraw::DrawViewPart::SeamVisible, TechDraw::DrawViewPart::SmoothHidden, and TechDraw::DrawViewPart::SmoothVisible.
Referenced by projectShape(), and projectShapeWithPolygonAlgo().
projectFace()
TopoDS_Shape GeometryObject::projectFace (const TopoDS_Shape & face, const gp_Ax2 & CS) static
Definition at line 432 of file GeometryObject.cpp.
References TechDraw::ShapeUtils::invertGeometry().
projectShape()
void GeometryObject::projectShape (const TopoDS_Shape & input, const gp_Ax2 & viewAxis)
Definition at line 143 of file GeometryObject.cpp.
References clear(), Base::Console(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), Handle(), hidHard, hidIso, hidOutline, hidSeam, hidSmooth, TechDraw::ShapeUtils::invertGeometry(), m_focus, m_isoCount, m_isPersp, makeTDGeometry(), KDL::max(), visHard, visIso, visOutline, visSeam, and visSmooth.
projectShapeWithPolygonAlgo()
void GeometryObject::projectShapeWithPolygonAlgo (const TopoDS_Shape & input, const gp_Ax2 & viewAxis)
set up a hidden line remover and project a shape with it
Definition at line 290 of file GeometryObject.cpp.
References clear(), Base::Console(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), TechDraw::ShapeUtils::findCentroid(), Handle(), hidHard, hidOutline, hidSeam, hidSmooth, TechDraw::ShapeUtils::invertGeometry(), m_focus, m_isPersp, makeTDGeometry(), KDL::max(), TechDraw::ShapeUtils::moveShape(), visHard, visOutline, visSeam, and visSmooth.
projectSimpleShape()
TopoDS_Shape GeometryObject::projectSimpleShape (const TopoDS_Shape & shape, const gp_Ax2 & CS) static
Definition at line 398 of file GeometryObject.cpp.
References TechDraw::ShapeUtils::invertGeometry().
Referenced by TechDraw::DrawComplexSection::getChangePointsFromSectionLine(), TechDraw::DrawComplexSection::makeSectionLineGeometry(), and TechDraw::DrawViewSection::mapToPage().
pruneVertexGeom()
void GeometryObject::pruneVertexGeom (Base::Vector3d center, double radius)
Definition at line 820 of file GeometryObject.cpp.
References exportCSG::center(), getVertexGeometry(), FreeCADInit::Length, TestSpreadsheet::v, and vertexGeom.
setEdgeGeometry()
void TechDraw::GeometryObject::setEdgeGeometry (BaseGeomPtrVector newGeoms) inline
Definition at line 81 of file GeometryObject.h.
setFocus()
void TechDraw::GeometryObject::setFocus (double f) inline
Definition at line 98 of file GeometryObject.h.
References SCL.SimpleDataTypes::f.
setIsoCount()
void TechDraw::GeometryObject::setIsoCount (int i) inline
Definition at line 92 of file GeometryObject.h.
References SplineSurface::i.
setParentName()
void TechDraw::GeometryObject::setParentName (std::string n)
setScrubCount()
void TechDraw::GeometryObject::setScrubCount (int count) inline
Definition at line 100 of file GeometryObject.h.
References src.Mod.AddonManager.NetworkManager::count.
setVertexGeometry()
void TechDraw::GeometryObject::setVertexGeometry (std::vector< VertexPtr > newVerts) inline
Definition at line 80 of file GeometryObject.h.
simpleProjection()
TopoDS_Shape GeometryObject::simpleProjection (const TopoDS_Shape & shape, const gp_Ax2 & projCS) static
Definition at line 422 of file GeometryObject.cpp.
References WorkingPlane::plane.
usePolygonHLR() [1/2]
bool TechDraw::GeometryObject::usePolygonHLR () const inline
Definition at line 97 of file GeometryObject.h.
usePolygonHLR() [2/2]
void TechDraw::GeometryObject::usePolygonHLR (bool b) inline
Definition at line 96 of file GeometryObject.h.
References SCL.SimpleDataTypes::b.
Member Data Documentation
edgeGeom
BaseGeomPtrVector TechDraw::GeometryObject::edgeGeom protected
Definition at line 155 of file GeometryObject.h.
Referenced by addCenterLine(), addCosmeticEdge(), addEdge(), addGeomFromCompound(), calcBoundingBox(), clear(), and getVisibleFaceEdges().
faceGeom
std::vector<FacePtr> TechDraw::GeometryObject::faceGeom protected
Definition at line 157 of file GeometryObject.h.
Referenced by addFaceGeom(), clear(), and clearFaceGeom().
hidHard
TopoDS_Shape TechDraw::GeometryObject::hidHard protected
Definition at line 138 of file GeometryObject.h.
Referenced by extractGeometry(), projectShape(), and projectShapeWithPolygonAlgo().
hidIso
TopoDS_Shape TechDraw::GeometryObject::hidIso protected
Definition at line 142 of file GeometryObject.h.
Referenced by extractGeometry(), and projectShape().
hidOutline
TopoDS_Shape TechDraw::GeometryObject::hidOutline protected
Definition at line 139 of file GeometryObject.h.
Referenced by extractGeometry(), projectShape(), and projectShapeWithPolygonAlgo().
hidSeam
TopoDS_Shape TechDraw::GeometryObject::hidSeam protected
Definition at line 141 of file GeometryObject.h.
Referenced by extractGeometry(), projectShape(), and projectShapeWithPolygonAlgo().
hidSmooth
TopoDS_Shape TechDraw::GeometryObject::hidSmooth protected
Definition at line 140 of file GeometryObject.h.
Referenced by extractGeometry(), projectShape(), and projectShapeWithPolygonAlgo().
m_focus
double TechDraw::GeometryObject::m_focus protected
Definition at line 165 of file GeometryObject.h.
Referenced by projectShape(), and projectShapeWithPolygonAlgo().
m_isoCount
int TechDraw::GeometryObject::m_isoCount protected
Definition at line 163 of file GeometryObject.h.
Referenced by projectShape().
m_isPersp
bool TechDraw::GeometryObject::m_isPersp protected
Definition at line 164 of file GeometryObject.h.
Referenced by projectShape(), and projectShapeWithPolygonAlgo().
m_parent
TechDraw::DrawView* TechDraw::GeometryObject::m_parent protected
Definition at line 162 of file GeometryObject.h.
Referenced by addCosmeticEdge(), addCosmeticVertex(), isParentDetail(), and makeTDGeometry().
m_parentName
std::string TechDraw::GeometryObject::m_parentName protected
Definition at line 161 of file GeometryObject.h.
m_scrubCount
int TechDraw::GeometryObject::m_scrubCount protected
Definition at line 167 of file GeometryObject.h.
Referenced by addGeomFromCompound().
m_usePolygonHLR
bool TechDraw::GeometryObject::m_usePolygonHLR protected
Definition at line 166 of file GeometryObject.h.
vertexGeom
std::vector<VertexPtr> TechDraw::GeometryObject::vertexGeom protected
Definition at line 156 of file GeometryObject.h.
Referenced by addCosmeticVertex(), addGeomFromCompound(), addVertex(), clear(), findVertex(), and pruneVertexGeom().
visHard
TopoDS_Shape TechDraw::GeometryObject::visHard protected
Definition at line 133 of file GeometryObject.h.
Referenced by extractGeometry(), projectShape(), and projectShapeWithPolygonAlgo().
visIso
TopoDS_Shape TechDraw::GeometryObject::visIso protected
Definition at line 137 of file GeometryObject.h.
Referenced by extractGeometry(), and projectShape().
visOutline
TopoDS_Shape TechDraw::GeometryObject::visOutline protected
Definition at line 134 of file GeometryObject.h.
Referenced by extractGeometry(), projectShape(), and projectShapeWithPolygonAlgo().
visSeam
TopoDS_Shape TechDraw::GeometryObject::visSeam protected
Definition at line 136 of file GeometryObject.h.
Referenced by extractGeometry(), projectShape(), and projectShapeWithPolygonAlgo().
visSmooth
TopoDS_Shape TechDraw::GeometryObject::visSmooth protected
Definition at line 135 of file GeometryObject.h.
Referenced by extractGeometry(), projectShape(), and projectShapeWithPolygonAlgo().
The documentation for this class was generated from the following files:
GeometryObject.h
GeometryObject.cpp