FreeCAD: Path::PathSegmentVisitor Class Reference
Path::PathSegmentVisitor Class Reference
#include <PathSegmentWalker.h>
Public Member Functions
virtual ~PathSegmentVisitor ()
virtual void setup (const Base::Vector3d &last)
virtual void g0 (int id, const Base::Vector3d &last, const Base::Vector3d &next, const std::deque< Base::Vector3d > &pts)
virtual void g1 (int id, const Base::Vector3d &last, const Base::Vector3d &next, const std::deque< Base::Vector3d > &pts)
virtual void g23 (int id, const Base::Vector3d &last, const Base::Vector3d &next, const std::deque< Base::Vector3d > &pts, const Base::Vector3d &center)
virtual void g8x (int id, const Base::Vector3d &last, const Base::Vector3d &next, const std::deque< Base::Vector3d > &pts, const std::deque< Base::Vector3d > &p, const std::deque< Base::Vector3d > &q)
virtual void g38 (int id, const Base::Vector3d &last, const Base::Vector3d &next)
Detailed Description
PathSegmentVisitor is the companion class to PathSegmentWalker. Its members are called with the segmented points of each command.
Definition at line 58 of file PathSegmentWalker.h.
Constructor & Destructor Documentation
~PathSegmentVisitor()
Path::PathSegmentVisitor::~PathSegmentVisitor () virtual
Definition at line 62 of file PathSegmentWalker.cpp.
Member Function Documentation
g0()
void Path::PathSegmentVisitor::g0 (int id, const Base::Vector3d & last, const Base::Vector3d & next, const std::deque< Base::Vector3d > & pts) virtual
Reimplemented in VisualPathSegmentVisitor.
Definition at line 70 of file PathSegmentWalker.cpp.
Referenced by Path::PathSegmentWalker::walk().
g1()
void Path::PathSegmentVisitor::g1 (int id, const Base::Vector3d & last, const Base::Vector3d & next, const std::deque< Base::Vector3d > & pts) virtual
Reimplemented in VisualPathSegmentVisitor.
Definition at line 81 of file PathSegmentWalker.cpp.
Referenced by Path::PathSegmentWalker::walk().
g23()
void Path::PathSegmentVisitor::g23 (int id, const Base::Vector3d & last, const Base::Vector3d & next, const std::deque< Base::Vector3d > & pts, const Base::Vector3d & center) virtual
Reimplemented in VisualPathSegmentVisitor.
Definition at line 92 of file PathSegmentWalker.cpp.
References exportCSG::center().
Referenced by Path::PathSegmentWalker::walk().
g38()
void Path::PathSegmentVisitor::g38 (int id, const Base::Vector3d & last, const Base::Vector3d & next) virtual
Reimplemented in VisualPathSegmentVisitor, and BoundBoxSegmentVisitor.
Definition at line 120 of file PathSegmentWalker.cpp.
Referenced by Path::PathSegmentWalker::walk().
g8x()
void Path::PathSegmentVisitor::g8x (int id, const Base::Vector3d & last, const Base::Vector3d & next, const std::deque< Base::Vector3d > & pts, const std::deque< Base::Vector3d > & p, const std::deque< Base::Vector3d > & q) virtual
Reimplemented in VisualPathSegmentVisitor.
Definition at line 105 of file PathSegmentWalker.cpp.
References buildPsets::p.
Referenced by Path::PathSegmentWalker::walk().
setup()
void Path::PathSegmentVisitor::setup (const Base::Vector3d & last) virtual
Reimplemented in VisualPathSegmentVisitor.
Definition at line 65 of file PathSegmentWalker.cpp.
Referenced by Path.Dressup.Tags.ObjectTagDressup::doExecute(), Path.Dressup.Gui.Dogbone.ObjectDressup::execute(), Path.Dressup.Tags.ObjectTagDressup::generateTags(), Path.Dressup.Tags.ObjectTagDressup::pointAtBottom(), Path.Dressup.Tags.ObjectTagDressup::pointIsOnPath(), Path.Dressup.Tags.ObjectTagDressup::setXyEnabled(), Path.Dressup.Tags.ObjectTagDressup::supportsTagGeneration(), and Path::PathSegmentWalker::walk().
The documentation for this class was generated from the following files:
PathSegmentWalker.h
PathSegmentWalker.cpp