FreeCAD: Gui::TaskView::TaskDialog Class Reference
Gui::TaskView::TaskDialog Class Reference
Father class of content with header and Icon.
#include <TaskDialog.h>
Public Types
enum ButtonPosition { North, South }
Signals
void aboutToBeDestroyed ()
Public Member Functions
TaskDialog ()
~TaskDialog () override
QWidget * addTaskBox (QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBox (const QPixmap &icon, QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBoxWithoutHeader (QWidget *widget)
void setButtonPosition (ButtonPosition p)
ButtonPosition buttonPosition () const
const std::vector< QWidget * > & getDialogContent () const
bool canClose () const
virtual QDialogButtonBox::StandardButtons getStandardButtons () const
tells the framework which buttons are wished for the dialog
virtual void modifyStandardButtons (QDialogButtonBox *)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
bool isEscapeButtonEnabled () const
void setAutoCloseOnTransactionChange (bool on)
bool isAutoCloseOnTransactionChange () const
void setAutoCloseOnDeletedDocument (bool on)
bool isAutoCloseOnDeletedDocument () const
const std::string & getDocumentName () const
void setDocumentName (const std::string &doc)
void setAutoCloseOnClosedView (bool on)
bool isAutoCloseOnClosedView () const
void associateToObject3dView (App::DocumentObject *obj)
const Gui::MDIView * getAssociatedView () const
void setAssociatedView (const Gui::MDIView *view)
virtual bool isAllowedAlterDocument () const
virtual bool isAllowedAlterView () const
virtual bool isAllowedAlterSelection () const
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
virtual void closed ()
is called by the framework when the dialog is closed
virtual void autoClosedOnTransactionChange ()
virtual void autoClosedOnDeletedDocument ()
virtual void autoClosedOnClosedView ()
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
virtual bool accept ()
is called by the framework if the dialog is accepted (Ok)
virtual bool reject ()
is called by the framework if the dialog is rejected (Cancel)
virtual void helpRequested ()
is called by the framework if the user press the help button
void emitDestructionSignal ()
Protected Attributes
QPointer< QDialogButtonBox > buttonBox
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Friends
class TaskDialogAttorney
Detailed Description
Father class of content with header and Icon.
Definition at line 49 of file Gui/TaskView/TaskDialog.h.
Member Enumeration Documentation
ButtonPosition
enum Gui::TaskView::TaskDialog::ButtonPosition
Enumerator
North
South
Definition at line 54 of file Gui/TaskView/TaskDialog.h.
Constructor & Destructor Documentation
TaskDialog()
TaskDialog::TaskDialog ()
Definition at line 48 of file Gui/TaskView/TaskDialog.cpp.
~TaskDialog()
TaskDialog::~TaskDialog () override
Definition at line 58 of file Gui/TaskView/TaskDialog.cpp.
References Content.
Member Function Documentation
aboutToBeDestroyed
void Gui::TaskView::TaskDialog::aboutToBeDestroyed () signal
accept()
bool TaskDialog::accept () virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented in PartGui::TaskPrimitivesEdit, PartGui::TaskPrimitives, PartDesignGui::TaskDlgTransformedParameters, PartGui::TaskProjectOnSurface, Gui::TaskView::TaskDialogPython, FemGui::TaskDlgPost, Gui::Dialog::TaskPlacement, PartDesignGui::TaskDlgPipeParameters, PartGui::TaskChamferEdges, PartGui::TaskProjectionOnSurface, TechDrawGui::TaskDlgWeldingSymbol, PartGui::TaskDlgAttacher, PartDesignGui::TaskDlgExtrudeParameters, TechDrawGui::TaskDlgComplexSection, Gui::TaskCSysDragger, TechDrawGui::TaskDlgLeaderLine, PartGui::TaskFilletEdges, TechDrawGui::TaskDlgProjGroup, TechDrawGui::TaskDlgSectionView, Gui::Dialog::TaskTransform, TechDrawGui::TaskDlgLineDecor, TechDrawGui::TaskDlgCenterLine, TechDrawGui::TaskDlgDetail, PartDesignGui::TaskDlgFeatureParameters, PartDesignGui::TaskDlgFeaturePick, Gui::TaskImageDialog, SurfaceGui::TaskFilling, MeshGui::TaskSegmentationBestFit, PartDesignGui::TaskDlgDressUpParameters, TechDrawGui::TaskDlgRichAnno, MeshGui::TaskRemoveComponents, MeshPartGui::TaskTessellation, TechDrawGui::TaskDlgSurfaceFinishSymbols, PartDesignGui::TaskPrimitiveParameters, SurfaceGui::TaskSections, TechDrawGui::TaskDlgSelectLineAttributes, SurfaceGui::TaskGeomFillSurface, TechDrawGui::TaskDlgCosVertex, MeshGui::TaskSmoothing, FemGui::TaskDlgFemConstraintFluidBoundary, TechDrawGui::TaskDlgGeomHatch, PartGui::TaskRevolution, TechDrawGui::TaskDlgDimension, TechDrawGui::TaskDlgHatch, PartGui::TaskExtrusion, TechDrawGui::TaskDlgCosmeticCircle, ReverseEngineeringGui::TaskSegmentationManual, TechDrawGui::TaskDlgCosmeticLine, MatGui::TaskInspectMaterial, FemGui::TaskDlgFemConstraint, TechDrawGui::TaskDlgActiveView, FemGui::TaskDlgFemConstraintDisplacement, Gui::TaskElementColors, TechDrawGui::TaskDlgCustomizeFormat, MeshPartGui::TaskCrossSections, PartDesignGui::TaskDlgBooleanParameters, PartDesignGui::TaskDlgShapeBinder, TechDrawGui::TaskDlgDimReference, MatGui::TaskInspectAppearance, PartGui::TaskShapeBuilder, TechDrawGui::TaskDlgBalloon, FemGui::TaskDlgFemConstraintForce, RobotGui::TaskDlgSimulate, FemGui::TaskDlgFemConstraintGear, PartDesignGui::TaskDlgLoftParameters, PartGui::TaskCrossSections, PartDesignGui::TaskDlgThicknessParameters, FemGui::TaskDlgFemConstraintBearing, MeshGui::TaskDecimating, Gui::TaskDlgRelocation, FemGui::TaskDlgFemConstraintPulley, PartDesignGui::TaskDlgSketchBasedParameters, ReenGui::TaskFitBSplineCurve, TechDrawGui::TaskDlgLinkDim, Gui::TaskOrientationDialog, PartGui::TaskFaceAppearances, PartDesignGui::TaskDlgChamferParameters, ReenGui::TaskFitBSplineSurface, FemGui::TaskDlgFemConstraintHeatflux, FemGui::TaskDlgFemConstraintRigidBody, ReenGui::TaskPoisson, FemGui::TaskDlgFemConstraintTransform, PartGui::TaskScale, FemGui::TaskDlgFemConstraintTemperature, TechDrawGui::TaskDlgProjection, FemGui::TaskDlgFemConstraintContact, PartDesignGui::TaskDlgDraftParameters, Gui::Dialog::TaskTextureMapping, PathGui::TaskDlgPathCompound, FemGui::TaskDlgFemConstraintPressure, MeshGui::TaskSegmentation, PartGui::TaskOffset, PartGui::TaskSweep, PartGui::TaskThickness, ReverseEngineeringGui::TaskSegmentation, FemGui::TaskDlgFemConstraintSpring, PartDesignGui::TaskDlgFilletParameters, FemGui::TaskDlgFemConstraintPlaneRotation, PartGui::TaskMirroring, FemGui::TaskDlgFemConstraintFixed, PartGui::TaskLoft, PartDesignGui::TaskDlgDatumParameters, FemGui::TaskDlgFemConstraintInitialTemperature, SketcherGui::TaskDlgEditSketch, FemGui::TaskDlgCreateElementSet, FemGui::TaskDlgCreateNodeSet, RobotGui::TaskDlgEdge2Trac, RobotGui::TaskDlgTrajectoryDressUp, FemGui::TaskDlgMeshShapeNetgen, RobotGui::TaskDlgTrajectoryCompound, FemGui::TaskDlgAnalysis, DrawingGui::TaskDlgOrthoViews, and DrawingGui::TaskProjection.
Definition at line 159 of file Gui/TaskView/TaskDialog.cpp.
Referenced by Gui::TaskCSysDragger::accept(), Gui::TaskView::TaskView::accept(), Gui::TaskView::TaskDialogPython::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
addTaskBox() [1/2]
QWidget * TaskDialog::addTaskBox (const QPixmap & icon, QWidget * widget, bool expandable = true, QWidget * parent = nullptr)
Definition at line 73 of file Gui/TaskView/TaskDialog.cpp.
References Content, and Init::parent.
addTaskBox() [2/2]
QWidget * TaskDialog::addTaskBox (QWidget * widget, bool expandable = true, QWidget * parent = nullptr)
Definition at line 68 of file Gui/TaskView/TaskDialog.cpp.
References Init::parent.
Referenced by PartGui::TaskBooleanOperation::TaskBooleanOperation(), PartGui::TaskChamferEdges::TaskChamferEdges(), PartGui::TaskCrossSections::TaskCrossSections(), MeshPartGui::TaskCrossSections::TaskCrossSections(), MeshPartGui::TaskCurveOnMesh::TaskCurveOnMesh(), MeshGui::TaskDecimating::TaskDecimating(), MatGui::TaskDisplayProperties::TaskDisplayProperties(), DrawingGui::TaskDlgOrthoViews::TaskDlgOrthoViews(), Gui::TaskElementColors::TaskElementColors(), PartGui::TaskExtrusion::TaskExtrusion(), PartGui::TaskFaceAppearances::TaskFaceAppearances(), PartGui::TaskFilletEdges::TaskFilletEdges(), SurfaceGui::TaskFilling::TaskFilling(), ReenGui::TaskFitBSplineSurface::TaskFitBSplineSurface(), MatGui::TaskInspectAppearance::TaskInspectAppearance(), MatGui::TaskInspectMaterial::TaskInspectMaterial(), PartGui::TaskLoft::TaskLoft(), PartGui::TaskMirroring::TaskMirroring(), PartGui::TaskOffset::TaskOffset(), Gui::TaskOrientationDialog::TaskOrientationDialog(), Gui::Dialog::TaskPlacement::TaskPlacement(), ReenGui::TaskPoisson::TaskPoisson(), PartGui::TaskPrimitives::TaskPrimitives(), PartGui::TaskPrimitivesEdit::TaskPrimitivesEdit(), DrawingGui::TaskProjection::TaskProjection(), MeshGui::TaskRemeshGmsh::TaskRemeshGmsh(), MeshGui::TaskRemoveComponents::TaskRemoveComponents(), PartGui::TaskRevolution::TaskRevolution(), PartGui::TaskScale::TaskScale(), SurfaceGui::TaskSections::TaskSections(), ReverseEngineeringGui::TaskSegmentation::TaskSegmentation(), MeshGui::TaskSegmentation::TaskSegmentation(), MeshGui::TaskSegmentationBestFit::TaskSegmentationBestFit(), ReverseEngineeringGui::TaskSegmentationManual::TaskSegmentationManual(), PartGui::TaskShapeBuilder::TaskShapeBuilder(), MeshGui::TaskSmoothing::TaskSmoothing(), PartGui::TaskSweep::TaskSweep(), MeshPartGui::TaskTessellation::TaskTessellation(), Gui::Dialog::TaskTextureMapping::TaskTextureMapping(), PartGui::TaskThickness::TaskThickness(), and Gui::Dialog::TaskTransform::TaskTransform().
addTaskBoxWithoutHeader()
QWidget * TaskDialog::addTaskBoxWithoutHeader (QWidget * widget)
Definition at line 84 of file Gui/TaskView/TaskDialog.cpp.
References Content.
Referenced by MeshGui::TaskSmoothing::TaskSmoothing().
associateToObject3dView()
void TaskDialog::associateToObject3dView (App::DocumentObject * obj)
Definition at line 108 of file Gui/TaskView/TaskDialog.cpp.
References App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::Application::getViewProvider(), Gui::Application::Instance, Gui::Document::openEditingView3D(), setAssociatedView(), and setAutoCloseOnClosedView().
Referenced by SketcherGui::TaskDlgEditSketch::TaskDlgEditSketch().
autoClosedOnClosedView()
void TaskDialog::autoClosedOnClosedView () virtual
is called by the framework when the dialog is automatically closed due to closing of associated view
Reimplemented in SketcherGui::TaskDlgEditSketch.
Definition at line 149 of file Gui/TaskView/TaskDialog.cpp.
autoClosedOnDeletedDocument()
void TaskDialog::autoClosedOnDeletedDocument () virtual
is called by the framework when the dialog is automatically closed due to deleting the document
Reimplemented in Gui::TaskView::TaskDialogPython.
Definition at line 144 of file Gui/TaskView/TaskDialog.cpp.
autoClosedOnTransactionChange()
void TaskDialog::autoClosedOnTransactionChange () virtual
is called by the framework when the dialog is automatically closed due to changing the active transaction
Reimplemented in Gui::TaskView::TaskDialogPython.
Definition at line 139 of file Gui/TaskView/TaskDialog.cpp.
buttonPosition()
ButtonPosition Gui::TaskView::TaskDialog::buttonPosition () const inline
Definition at line 67 of file Gui/TaskView/TaskDialog.h.
References RobotExample::pos.
Referenced by Gui::TaskView::TaskView::showDialog().
canClose()
bool TaskDialog::canClose () const
Definition at line 97 of file Gui/TaskView/TaskDialog.cpp.
Referenced by PartGui::ViewProviderOffset::setEdit(), and PartGui::ViewProviderThickness::setEdit().
clicked()
void TaskDialog::clicked (int) virtual
is called by the framework if a button is clicked which has no accept or reject role
Reimplemented in Gui::TaskView::TaskDialogPython, FemGui::TaskDlgPost, PartGui::TaskChamferEdges, TechDrawGui::TaskDlgWeldingSymbol, PartGui::TaskDlgAttacher, PartGui::TaskFilletEdges, TechDrawGui::TaskDlgLeaderLine, Gui::Dialog::TaskTransform, TechDrawGui::TaskDlgLineDecor, TechDrawGui::TaskDlgCenterLine, TechDrawGui::TaskDlgDetail, PartDesignGui::TaskDlgFeaturePick, TechDrawGui::TaskDlgRichAnno, MeshGui::TaskRemoveComponents, MeshPartGui::TaskTessellation, TechDrawGui::TaskDlgSurfaceFinishSymbols, TechDrawGui::TaskDlgSelectLineAttributes, TechDrawGui::TaskDlgCosVertex, MeshGui::TaskRemeshGmsh, TechDrawGui::TaskDlgGeomHatch, PartGui::TaskExtrusion, TechDrawGui::TaskDlgDimension, TechDrawGui::TaskDlgHatch, ReverseEngineeringGui::TaskSegmentationManual, MatGui::TaskInspectMaterial, TechDrawGui::TaskDlgCosmeticCircle, TechDrawGui::TaskDlgCosmeticLine, Gui::TaskElementColors, TechDrawGui::TaskDlgActiveView, MatGui::TaskInspectAppearance, PartGui::TaskShapeBuilder, TechDrawGui::TaskDlgCustomizeFormat, PartDesignGui::TaskDlgBooleanParameters, TechDrawGui::TaskDlgDimReference, TechDrawGui::TaskDlgBalloon, RobotGui::TaskDlgSimulate, PartGui::TaskFaceAppearances, Gui::TaskDlgRelocation, TechDrawGui::TaskDlgLinkDim, PartGui::TaskScale, PartGui::TaskBooleanOperation, TechDrawGui::TaskDlgProjection, PartGui::TaskOffset, PartGui::TaskSweep, PartGui::TaskThickness, PathGui::TaskDlgPathCompound, PartGui::TaskLoft, SketcherGui::TaskDlgEditSketch, RobotGui::TaskDlgEdge2Trac, RobotGui::TaskDlgTrajectoryDressUp, FemGui::TaskDlgMeshShapeNetgen, DrawingGui::TaskDlgOrthoViews, TechDrawGui::TaskDlgProjGroup, Gui::Dialog::TaskPlacement, PartGui::TaskProjectionOnSurface, MeshPartGui::TaskCrossSections, and PartGui::TaskCrossSections.
Definition at line 154 of file Gui/TaskView/TaskDialog.cpp.
Referenced by Gui::TaskView::TaskView::clicked().
closed()
void TaskDialog::closed () virtual
is called by the framework when the dialog is closed
Reimplemented in SurfaceGui::TaskFilling.
Definition at line 134 of file Gui/TaskView/TaskDialog.cpp.
Referenced by Gui::TaskView::TaskView::removeDialog().
emitDestructionSignal()
void Gui::TaskView::TaskDialog::emitDestructionSignal () inline
Definition at line 168 of file Gui/TaskView/TaskDialog.h.
Referenced by Gui::TaskView::TaskView::removeDialog().
getAssociatedView()
const Gui::MDIView* Gui::TaskView::TaskDialog::getAssociatedView () const inline
Definition at line 119 of file Gui/TaskView/TaskDialog.h.
getDialogContent()
const std::vector< QWidget * > & TaskDialog::getDialogContent () const
Definition at line 92 of file Gui/TaskView/TaskDialog.cpp.
References Content.
Referenced by PartDesignGui::TaskDlgFeatureParameters::accept(), PartDesignGui::TaskDlgFeatureParameters::reject(), Gui::TaskView::TaskView::removeDialog(), and Gui::TaskView::TaskView::showDialog().
getDocumentName()
const std::string& Gui::TaskView::TaskDialog::getDocumentName () const inline
Definition at line 104 of file Gui/TaskView/TaskDialog.h.
Referenced by PartGui::TaskDlgAttacher::accept(), FemGui::TaskDlgPost::accept(), DrawingGui::TaskDlgOrthoViews::accept(), PartGui::TaskPrimitivesEdit::accept(), Gui::Document::canClose(), Gui::TaskView::TaskView::keyPressEvent(), SketcherGui::TaskDlgEditSketch::reject(), PartGui::TaskDlgAttacher::reject(), FemGui::TaskDlgPost::reject(), DrawingGui::TaskDlgOrthoViews::reject(), and PartGui::TaskPrimitivesEdit::reject().
getStandardButtons()
virtual QDialogButtonBox::StandardButtons Gui::TaskView::TaskDialog::getStandardButtons () const inline virtual
tells the framework which buttons are wished for the dialog
Reimplemented in PartGui::TaskPrimitivesEdit, PartGui::TaskPrimitives, PartGui::TaskProjectOnSurface, FemGui::TaskDlgPost, Gui::Dialog::TaskPlacement, PartGui::TaskChamferEdges, Gui::TaskView::TaskDialogPython, PartGui::TaskProjectionOnSurface, PartGui::TaskDlgAttacher, PartGui::TaskFilletEdges, Gui::TaskCSysDragger, TechDrawGui::TaskDlgSectionView, Gui::Dialog::TaskTransform, PartDesignGui::TaskDlgFeaturePick, TechDrawGui::TaskDlgProjGroup, PartGui::TaskCheckGeometryDialog, Gui::TaskImageDialog, SurfaceGui::TaskFilling, MeshGui::TaskSegmentationBestFit, MeshGui::TaskRemoveComponents, MeshPartGui::TaskTessellation, SurfaceGui::TaskSections, SurfaceGui::TaskGeomFillSurface, PartDesignGui::TaskPrimitiveParameters, MatGui::TaskDisplayProperties, MeshGui::TaskSmoothing, MeshGui::TaskRemeshGmsh, PartGui::TaskRevolution, PartGui::TaskExtrusion, FemGui::TaskDlgFemConstraint, ReverseEngineeringGui::TaskSegmentationManual, MatGui::TaskInspectMaterial, MatGui::TaskMaterial, PartDesignGui::TaskDlgBooleanParameters, Gui::TaskElementColors, MeshPartGui::TaskCrossSections, MatGui::TaskInspectAppearance, PartGui::TaskShapeBuilder, RobotGui::TaskDlgSimulate, Gui::TaskDlgRelocation, PartGui::TaskCrossSections, Gui::TaskMeasure, MeshGui::TaskDecimating, Gui::TaskOrientationDialog, PartGui::TaskFaceAppearances, ReenGui::TaskFitBSplineCurve, ReenGui::TaskFitBSplineSurface, SketcherGui::TaskSketcherValidation, PartGui::TaskScale, ReenGui::TaskPoisson, PathGui::TaskDlgPathCompound, PartGui::TaskBooleanOperation, PartGui::TaskOffset, PartGui::TaskSweep, PartGui::TaskThickness, Gui::Dialog::TaskTextureMapping, MeshPartGui::TaskCurveOnMesh, MeshGui::TaskSegmentation, ReverseEngineeringGui::TaskSegmentation, SketcherGui::TaskDlgEditSketch, PartGui::TaskMirroring, PartGui::TaskLoft, FemGui::TaskDlgCreateElementSet, FemGui::TaskDlgCreateNodeSet, RobotGui::TaskDlgEdge2Trac, RobotGui::TaskDlgTrajectoryDressUp, FemGui::TaskDlgMeshShapeNetgen, RobotGui::TaskDlgTrajectoryCompound, FemGui::TaskDlgAnalysis, and DrawingGui::TaskProjection.
Definition at line 73 of file Gui/TaskView/TaskDialog.h.
Referenced by PartDesignGui::TaskPrimitiveParameters::getStandardButtons(), Gui::TaskView::TaskDialogPython::getStandardButtons(), and Gui::TaskView::TaskView::showDialog().
helpRequested()
void TaskDialog::helpRequested () virtual
is called by the framework if the user press the help button
Reimplemented in Gui::TaskView::TaskDialogPython, TechDrawGui::TaskDlgLineDecor, TechDrawGui::TaskDlgCenterLine, TechDrawGui::TaskDlgDimension, TechDrawGui::TaskDlgHatch, TechDrawGui::TaskDlgCosmeticCircle, TechDrawGui::TaskDlgCosmeticLine, TechDrawGui::TaskDlgActiveView, TechDrawGui::TaskDlgCustomizeFormat, TechDrawGui::TaskDlgDimReference, TechDrawGui::TaskDlgBalloon, RobotGui::TaskDlgSimulate, Gui::TaskDlgRelocation, TechDrawGui::TaskDlgProjection, PathGui::TaskDlgPathCompound, FemGui::TaskDlgCreateElementSet, FemGui::TaskDlgCreateNodeSet, RobotGui::TaskDlgEdge2Trac, RobotGui::TaskDlgTrajectoryDressUp, FemGui::TaskDlgMeshShapeNetgen, RobotGui::TaskDlgTrajectoryCompound, and FemGui::TaskDlgAnalysis.
Definition at line 169 of file Gui/TaskView/TaskDialog.cpp.
Referenced by Gui::TaskView::TaskView::helpRequested().
isAllowedAlterDocument()
virtual bool Gui::TaskView::TaskDialog::isAllowedAlterDocument () const inline virtual
Indicates whether this task dialog allows other commands to modify the document while it is open.
Reimplemented in DrawingGui::TaskProjection, FemGui::TaskDlgPost, Gui::Dialog::TaskPlacement, Gui::TaskView::TaskDialogPython, TechDrawGui::TaskDlgWeldingSymbol, PartGui::TaskDlgAttacher, TechDrawGui::TaskDlgComplexSection, TechDrawGui::TaskDlgLeaderLine, TechDrawGui::TaskDlgProjGroup, TechDrawGui::TaskDlgSectionView, TechDrawGui::TaskDlgLineDecor, PartGui::TaskCheckGeometryDialog, TechDrawGui::TaskDlgCenterLine, TechDrawGui::TaskDlgDetail, PartDesignGui::TaskDlgFeaturePick, TechDrawGui::TaskDlgRichAnno, MeshGui::TaskRemoveComponents, TechDrawGui::TaskDlgSurfaceFinishSymbols, TechDrawGui::TaskDlgSelectLineAttributes, TechDrawGui::TaskDlgCosVertex, MeshGui::TaskSmoothing, MeshGui::TaskRemeshGmsh, TechDrawGui::TaskDlgDimension, TechDrawGui::TaskDlgGeomHatch, TechDrawGui::TaskDlgHatch, ReverseEngineeringGui::TaskSegmentationManual, MatGui::TaskDisplayProperties, TechDrawGui::TaskDlgCosmeticCircle, TechDrawGui::TaskDlgCosmeticLine, TechDrawGui::TaskDlgActiveView, FemGui::TaskDlgFemConstraint, TechDrawGui::TaskDlgDimReference, TechDrawGui::TaskDlgCustomizeFormat, PartDesignGui::TaskDlgBooleanParameters, TechDrawGui::TaskDlgBalloon, MatGui::TaskMaterial, MeshGui::TaskDecimating, TechDrawGui::TaskDlgLinkDim, PartGui::TaskBooleanOperation, PartGui::TaskMirroring, and SketcherGui::TaskDlgEditSketch.
Definition at line 128 of file Gui/TaskView/TaskDialog.h.
Referenced by Gui::TaskView::TaskDialogPython::isAllowedAlterDocument().
isAllowedAlterSelection()
virtual bool Gui::TaskView::TaskDialog::isAllowedAlterSelection () const inline virtual
Indicates whether this task dialog allows other commands to modify the selection while it is open.
Reimplemented in Gui::Dialog::TaskPlacement, Gui::TaskView::TaskDialogPython, TechDrawGui::TaskDlgSectionView, MatGui::TaskDisplayProperties, and MatGui::TaskMaterial.
Definition at line 140 of file Gui/TaskView/TaskDialog.h.
Referenced by Gui::TaskView::TaskDialogPython::isAllowedAlterSelection().
isAllowedAlterView()
virtual bool Gui::TaskView::TaskDialog::isAllowedAlterView () const inline virtual
Indicates whether this task dialog allows other commands to modify the 3d view while it is open.
Reimplemented in Gui::Dialog::TaskPlacement, Gui::TaskView::TaskDialogPython, MatGui::TaskDisplayProperties, and MatGui::TaskMaterial.
Definition at line 134 of file Gui/TaskView/TaskDialog.h.
Referenced by Gui::TaskView::TaskDialogPython::isAllowedAlterView().
isAutoCloseOnClosedView()
bool Gui::TaskView::TaskDialog::isAutoCloseOnClosedView () const inline
Definition at line 114 of file Gui/TaskView/TaskDialog.h.
isAutoCloseOnDeletedDocument()
bool Gui::TaskView::TaskDialog::isAutoCloseOnDeletedDocument () const inline
Definition at line 100 of file Gui/TaskView/TaskDialog.h.
isAutoCloseOnTransactionChange()
bool Gui::TaskView::TaskDialog::isAutoCloseOnTransactionChange () const inline
Definition at line 91 of file Gui/TaskView/TaskDialog.h.
isEscapeButtonEnabled()
bool Gui::TaskView::TaskDialog::isEscapeButtonEnabled () const inline
Definition at line 82 of file Gui/TaskView/TaskDialog.h.
Referenced by Gui::TaskView::TaskView::keyPressEvent().
modifyStandardButtons()
virtual void Gui::TaskView::TaskDialog::modifyStandardButtons (QDialogButtonBox *) inline virtual
Reimplemented in TechDrawGui::TaskDlgWeldingSymbol, TechDrawGui::TaskDlgLeaderLine, TechDrawGui::TaskDlgCenterLine, TechDrawGui::TaskDlgProjGroup, TechDrawGui::TaskDlgDetail, TechDrawGui::TaskDlgRichAnno, TechDrawGui::TaskDlgCosVertex, TechDrawGui::TaskDlgActiveView, Gui::TaskMeasure, PartGui::TaskPrimitives, FemGui::TaskDlgPost, Gui::TaskView::TaskDialogPython, MeshGui::TaskRemoveComponents, and ReverseEngineeringGui::TaskSegmentationManual.
Definition at line 75 of file Gui/TaskView/TaskDialog.h.
Referenced by Gui::TaskView::TaskView::showDialog().
needsFullSpace()
virtual bool Gui::TaskView::TaskDialog::needsFullSpace () const inline virtual
Reimplemented in Gui::TaskView::TaskDialogPython, PartGui::TaskChamferEdges, PartGui::TaskFilletEdges, PartGui::TaskCheckGeometryDialog, PartGui::TaskBooleanOperation, and PartGui::TaskMirroring.
Definition at line 142 of file Gui/TaskView/TaskDialog.h.
Referenced by Gui::TaskView::TaskDialogPython::needsFullSpace(), and Gui::TaskView::TaskView::showDialog().
open()
void TaskDialog::open () virtual
is called by the framework when the dialog is opened
Reimplemented in Gui::Dialog::TaskPlacement, Gui::TaskView::TaskDialogPython, FemGui::TaskDlgPost, PartGui::TaskChamferEdges, TechDrawGui::TaskDlgWeldingSymbol, PartGui::TaskDlgAttacher, TechDrawGui::TaskDlgComplexSection, Gui::TaskCSysDragger, PartGui::TaskFilletEdges, TechDrawGui::TaskDlgLeaderLine, TechDrawGui::TaskDlgProjGroup, TechDrawGui::TaskDlgSectionView, TechDrawGui::TaskDlgLineDecor, TechDrawGui::TaskDlgCenterLine, TechDrawGui::TaskDlgDetail, Gui::TaskImageDialog, PartDesignGui::TaskDlgFeaturePick, SurfaceGui::TaskFilling, TechDrawGui::TaskDlgRichAnno, MeshPartGui::TaskTessellation, SurfaceGui::TaskSections, TechDrawGui::TaskDlgSurfaceFinishSymbols, SurfaceGui::TaskGeomFillSurface, TechDrawGui::TaskDlgSelectLineAttributes, TechDrawGui::TaskDlgCosVertex, TechDrawGui::TaskDlgGeomHatch, TechDrawGui::TaskDlgDimension, TechDrawGui::TaskDlgHatch, MatGui::TaskInspectMaterial, TechDrawGui::TaskDlgCosmeticCircle, TechDrawGui::TaskDlgCosmeticLine, TechDrawGui::TaskDlgActiveView, Gui::TaskElementColors, FemGui::TaskDlgFemConstraint, TechDrawGui::TaskDlgCustomizeFormat, MatGui::TaskInspectAppearance, PartGui::TaskShapeBuilder, PartDesignGui::TaskDlgBooleanParameters, TechDrawGui::TaskDlgDimReference, TechDrawGui::TaskDlgBalloon, RobotGui::TaskDlgSimulate, ReenGui::TaskFitBSplineCurve, Gui::TaskOrientationDialog, Gui::TaskDlgRelocation, PartGui::TaskFaceAppearances, ReenGui::TaskFitBSplineSurface, TechDrawGui::TaskDlgLinkDim, ReenGui::TaskPoisson, TechDrawGui::TaskDlgProjection, PartGui::TaskOffset, PartGui::TaskSweep, PartGui::TaskThickness, PathGui::TaskDlgPathCompound, PartGui::TaskLoft, FemGui::TaskDlgCreateElementSet, SketcherGui::TaskDlgEditSketch, FemGui::TaskDlgCreateNodeSet, RobotGui::TaskDlgEdge2Trac, RobotGui::TaskDlgTrajectoryDressUp, FemGui::TaskDlgMeshShapeNetgen, RobotGui::TaskDlgTrajectoryCompound, FemGui::TaskDlgAnalysis, and DrawingGui::TaskDlgOrthoViews.
Definition at line 129 of file Gui/TaskView/TaskDialog.cpp.
Referenced by Gui::TaskCSysDragger::open(), and Gui::TaskView::TaskView::showDialog().
reject()
bool TaskDialog::reject () virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented in PartGui::TaskPrimitivesEdit, PartGui::TaskPrimitives, PartDesignGui::TaskDlgTransformedParameters, PartGui::TaskProjectOnSurface, Gui::TaskView::TaskDialogPython, FemGui::TaskDlgPost, Gui::Dialog::TaskPlacement, PartGui::TaskChamferEdges, PartGui::TaskProjectionOnSurface, TechDrawGui::TaskDlgWeldingSymbol, PartGui::TaskDlgAttacher, PartDesignGui::TaskDlgExtrudeParameters, TechDrawGui::TaskDlgComplexSection, Gui::TaskCSysDragger, TechDrawGui::TaskDlgLeaderLine, TechDrawGui::TaskDlgProjGroup, PartGui::TaskFilletEdges, TechDrawGui::TaskDlgSectionView, Gui::Dialog::TaskTransform, TechDrawGui::TaskDlgLineDecor, TechDrawGui::TaskDlgCenterLine, TechDrawGui::TaskDlgDetail, PartDesignGui::TaskDlgFeatureParameters, PartDesignGui::TaskDlgFeaturePick, Gui::TaskImageDialog, SurfaceGui::TaskFilling, TechDrawGui::TaskDlgRichAnno, PartDesignGui::TaskDlgDressUpParameters, TechDrawGui::TaskDlgSurfaceFinishSymbols, MeshPartGui::TaskTessellation, PartDesignGui::TaskPrimitiveParameters, SurfaceGui::TaskSections, TechDrawGui::TaskDlgSelectLineAttributes, TechDrawGui::TaskDlgCosVertex, SurfaceGui::TaskGeomFillSurface, TechDrawGui::TaskDlgGeomHatch, TechDrawGui::TaskDlgDimension, TechDrawGui::TaskDlgHatch, MatGui::TaskDisplayProperties, TechDrawGui::TaskDlgCosmeticCircle, PartGui::TaskExtrusion, TechDrawGui::TaskDlgCosmeticLine, FemGui::TaskDlgFemConstraint, TechDrawGui::TaskDlgActiveView, Gui::TaskMeasure, TechDrawGui::TaskDlgCustomizeFormat, Gui::TaskElementColors, PartDesignGui::TaskDlgBooleanParameters, PartDesignGui::TaskDlgShapeBinder, TechDrawGui::TaskDlgDimReference, PartGui::TaskShapeBuilder, TechDrawGui::TaskDlgBalloon, MatGui::TaskMaterial, RobotGui::TaskDlgSimulate, Gui::TaskDlgRelocation, PartDesignGui::TaskDlgSketchBasedParameters, TechDrawGui::TaskDlgLinkDim, Gui::TaskOrientationDialog, PartGui::TaskFaceAppearances, PartGui::TaskScale, TechDrawGui::TaskDlgProjection, PathGui::TaskDlgPathCompound, Gui::Dialog::TaskTextureMapping, MeshPartGui::TaskCurveOnMesh, PartGui::TaskOffset, PartGui::TaskSweep, PartGui::TaskThickness, PartGui::TaskMirroring, PartGui::TaskLoft, PartDesignGui::TaskDlgDatumParameters, SketcherGui::TaskDlgEditSketch, FemGui::TaskDlgCreateElementSet, FemGui::TaskDlgCreateNodeSet, RobotGui::TaskDlgEdge2Trac, RobotGui::TaskDlgTrajectoryDressUp, FemGui::TaskDlgMeshShapeNetgen, RobotGui::TaskDlgTrajectoryCompound, FemGui::TaskDlgAnalysis, and DrawingGui::TaskDlgOrthoViews.
Definition at line 164 of file Gui/TaskView/TaskDialog.cpp.
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), Gui::TaskCSysDragger::reject(), Gui::TaskView::TaskView::reject(), Gui::TaskView::TaskDialogPython::reject(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
setAssociatedView()
void Gui::TaskView::TaskDialog::setAssociatedView (const Gui::MDIView * view) inline
Definition at line 121 of file Gui/TaskView/TaskDialog.h.
Referenced by associateToObject3dView().
setAutoCloseOnClosedView()
void Gui::TaskView::TaskDialog::setAutoCloseOnClosedView (bool on) inline
Defines whether a task dialog must be closed if the associated view is deleted.
Definition at line 111 of file Gui/TaskView/TaskDialog.h.
Referenced by associateToObject3dView().
setAutoCloseOnDeletedDocument()
void Gui::TaskView::TaskDialog::setAutoCloseOnDeletedDocument (bool on) inline
Defines whether a task dialog must be closed if the document is deleted.
Definition at line 97 of file Gui/TaskView/TaskDialog.h.
Referenced by Gui::TaskMeasure::TaskMeasure().
setAutoCloseOnTransactionChange()
void Gui::TaskView::TaskDialog::setAutoCloseOnTransactionChange (bool on) inline
Defines whether a task dialog must be closed if the document changed the active transaction.
Definition at line 88 of file Gui/TaskView/TaskDialog.h.
Referenced by TechDrawGui::TaskDlgBalloon::TaskDlgBalloon(), TechDrawGui::TaskDlgCenterLine::TaskDlgCenterLine(), TechDrawGui::TaskDlgDimension::TaskDlgDimension(), and TechDrawGui::TaskDlgProjection::TaskDlgProjection().
setButtonPosition()
void Gui::TaskView::TaskDialog::setButtonPosition (ButtonPosition p) inline
Definition at line 65 of file Gui/TaskView/TaskDialog.h.
References buildPsets::p, and RobotExample::pos.
Referenced by PartGui::TaskCheckGeometryDialog::TaskCheckGeometryDialog(), MatGui::TaskDisplayProperties::TaskDisplayProperties(), MatGui::TaskMaterial::TaskMaterial(), Gui::TaskMeasure::TaskMeasure(), Gui::Dialog::TaskPlacement::TaskPlacement(), and Gui::Dialog::TaskTransform::TaskTransform().
setDocumentName()
void Gui::TaskView::TaskDialog::setDocumentName (const std::string & doc) inline
Definition at line 106 of file Gui/TaskView/TaskDialog.h.
References toolbit-attributes::doc.
Referenced by Gui::DocumentP::setDocumentNameOfTaskDialog(), PartGui::TaskDlgAttacher::TaskDlgAttacher(), and PartGui::TaskProjectOnSurface::TaskProjectOnSurface().
setEscapeButtonEnabled()
void Gui::TaskView::TaskDialog::setEscapeButtonEnabled (bool on) inline
Defines whether a task dialog can be rejected by pressing Esc.
Definition at line 79 of file Gui/TaskView/TaskDialog.h.
Referenced by SketcherGui::TaskDlgEditSketch::TaskDlgEditSketch().
Friends And Related Function Documentation
TaskDialogAttorney
friend class TaskDialogAttorney friend
Definition at line 189 of file Gui/TaskView/TaskDialog.h.
Member Data Documentation
buttonBox
QPointer<QDialogButtonBox> Gui::TaskView::TaskDialog::buttonBox protected
Definition at line 176 of file Gui/TaskView/TaskDialog.h.
Referenced by Gui::TaskMeasure::eventFilter(), Path.Base.Gui.GetPoint.TaskPanel::getPoint(), Path.Dressup.Gui.Boundary.TaskPanel::modifyStandardButtons(), Path.Dressup.Gui.Tags.PathDressupTagTaskPanel::modifyStandardButtons(), Gui::TaskView::TaskDialogPython::modifyStandardButtons(), Path.Op.Gui.Base.TaskPanel::modifyStandardButtons(), Path.Op.Gui.Base.TaskPanel::pageDirtyChanged(), Path.Base.Gui.GetPoint.TaskPanel::pointFinish(), Path.Dressup.Gui.Boundary.TaskPanel::setClean(), and Path.Dressup.Gui.Boundary.TaskPanel::setDirty().
Content
std::vector<QWidget*> Gui::TaskView::TaskDialog::Content protected
List of TaskBoxes of that dialog.
Definition at line 178 of file Gui/TaskView/TaskDialog.h.
Referenced by PartDesignGui::TaskDlgFeatureParameters::accept(), addTaskBox(), addTaskBoxWithoutHeader(), FemGui::TaskDlgPost::appendBox(), getDialogContent(), PartGui::TaskCheckGeometryDialog::TaskCheckGeometryDialog(), Gui::TaskCSysDragger::TaskCSysDragger(), TechDrawGui::TaskDlgActiveView::TaskDlgActiveView(), FemGui::TaskDlgAnalysis::TaskDlgAnalysis(), PartGui::TaskDlgAttacher::TaskDlgAttacher(), TechDrawGui::TaskDlgBalloon::TaskDlgBalloon(), PartDesignGui::TaskDlgBooleanParameters::TaskDlgBooleanParameters(), TechDrawGui::TaskDlgCenterLine::TaskDlgCenterLine(), PartDesignGui::TaskDlgChamferParameters::TaskDlgChamferParameters(), TechDrawGui::TaskDlgComplexSection::TaskDlgComplexSection(), TechDrawGui::TaskDlgCosmeticCircle::TaskDlgCosmeticCircle(), TechDrawGui::TaskDlgCosmeticLine::TaskDlgCosmeticLine(), TechDrawGui::TaskDlgCosVertex::TaskDlgCosVertex(), FemGui::TaskDlgCreateElementSet::TaskDlgCreateElementSet(), FemGui::TaskDlgCreateNodeSet::TaskDlgCreateNodeSet(), TechDrawGui::TaskDlgCustomizeFormat::TaskDlgCustomizeFormat(), PartDesignGui::TaskDlgDatumParameters::TaskDlgDatumParameters(), TechDrawGui::TaskDlgDetail::TaskDlgDetail(), TechDrawGui::TaskDlgDimension::TaskDlgDimension(), TechDrawGui::TaskDlgDimReference::TaskDlgDimReference(), PartDesignGui::TaskDlgDraftParameters::TaskDlgDraftParameters(), RobotGui::TaskDlgEdge2Trac::TaskDlgEdge2Trac(), SketcherGui::TaskDlgEditSketch::TaskDlgEditSketch(), PartDesignGui::TaskDlgFeaturePick::TaskDlgFeaturePick(), FemGui::TaskDlgFemConstraintBearing::TaskDlgFemConstraintBearing(), FemGui::TaskDlgFemConstraintContact::TaskDlgFemConstraintContact(), FemGui::TaskDlgFemConstraintDisplacement::TaskDlgFemConstraintDisplacement(), FemGui::TaskDlgFemConstraintFixed::TaskDlgFemConstraintFixed(), FemGui::TaskDlgFemConstraintFluidBoundary::TaskDlgFemConstraintFluidBoundary(), FemGui::TaskDlgFemConstraintForce::TaskDlgFemConstraintForce(), FemGui::TaskDlgFemConstraintGear::TaskDlgFemConstraintGear(), FemGui::TaskDlgFemConstraintHeatflux::TaskDlgFemConstraintHeatflux(), FemGui::TaskDlgFemConstraintInitialTemperature::TaskDlgFemConstraintInitialTemperature(), FemGui::TaskDlgFemConstraintPlaneRotation::TaskDlgFemConstraintPlaneRotation(), FemGui::TaskDlgFemConstraintPressure::TaskDlgFemConstraintPressure(), FemGui::TaskDlgFemConstraintPulley::TaskDlgFemConstraintPulley(), FemGui::TaskDlgFemConstraintRigidBody::TaskDlgFemConstraintRigidBody(), FemGui::TaskDlgFemConstraintSpring::TaskDlgFemConstraintSpring(), FemGui::TaskDlgFemConstraintTemperature::TaskDlgFemConstraintTemperature(), FemGui::TaskDlgFemConstraintTransform::TaskDlgFemConstraintTransform(), PartDesignGui::TaskDlgFilletParameters::TaskDlgFilletParameters(), TechDrawGui::TaskDlgGeomHatch::TaskDlgGeomHatch(), PartDesignGui::TaskDlgGrooveParameters::TaskDlgGrooveParameters(), TechDrawGui::TaskDlgHatch::TaskDlgHatch(), PartDesignGui::TaskDlgHelixParameters::TaskDlgHelixParameters(), PartDesignGui::TaskDlgHoleParameters::TaskDlgHoleParameters(), TechDrawGui::TaskDlgLeaderLine::TaskDlgLeaderLine(), PartDesignGui::TaskDlgLinearPatternParameters::TaskDlgLinearPatternParameters(), TechDrawGui::TaskDlgLineDecor::TaskDlgLineDecor(), TechDrawGui::TaskDlgLinkDim::TaskDlgLinkDim(), PartDesignGui::TaskDlgLoftParameters::TaskDlgLoftParameters(), FemGui::TaskDlgMeshShapeNetgen::TaskDlgMeshShapeNetgen(), PartDesignGui::TaskDlgMirroredParameters::TaskDlgMirroredParameters(), PartDesignGui::TaskDlgMultiTransformParameters::TaskDlgMultiTransformParameters(), PartDesignGui::TaskDlgPadParameters::TaskDlgPadParameters(), PathGui::TaskDlgPathCompound::TaskDlgPathCompound(), PartDesignGui::TaskDlgPipeParameters::TaskDlgPipeParameters(), PartDesignGui::TaskDlgPocketParameters::TaskDlgPocketParameters(), PartDesignGui::TaskDlgPolarPatternParameters::TaskDlgPolarPatternParameters(), TechDrawGui::TaskDlgProjection::TaskDlgProjection(), TechDrawGui::TaskDlgProjGroup::TaskDlgProjGroup(), PartDesignGui::TaskDlgRevolutionParameters::TaskDlgRevolutionParameters(), TechDrawGui::TaskDlgRichAnno::TaskDlgRichAnno(), PartDesignGui::TaskDlgScaledParameters::TaskDlgScaledParameters(), TechDrawGui::TaskDlgSectionView::TaskDlgSectionView(), TechDrawGui::TaskDlgSelectLineAttributes::TaskDlgSelectLineAttributes(), PartDesignGui::TaskDlgShapeBinder::TaskDlgShapeBinder(), RobotGui::TaskDlgSimulate::TaskDlgSimulate(), TechDrawGui::TaskDlgSurfaceFinishSymbols::TaskDlgSurfaceFinishSymbols(), PartDesignGui::TaskDlgThicknessParameters::TaskDlgThicknessParameters(), RobotGui::TaskDlgTrajectoryCompound::TaskDlgTrajectoryCompound(), RobotGui::TaskDlgTrajectoryDressUp::TaskDlgTrajectoryDressUp(), PartDesignGui::TaskDlgTransformedParameters::TaskDlgTransformedParameters(), TechDrawGui::TaskDlgWeldingSymbol::TaskDlgWeldingSymbol(), MatGui::TaskMaterial::TaskMaterial(), Gui::TaskMeasure::TaskMeasure(), PartDesignGui::TaskPrimitiveParameters::TaskPrimitiveParameters(), PartGui::TaskProjectionOnSurface::TaskProjectionOnSurface(), PartGui::TaskProjectOnSurface::TaskProjectOnSurface(), SketcherGui::TaskSketcherValidation::TaskSketcherValidation(), ~TaskDialog(), Gui::TaskView::TaskDialogPython::~TaskDialogPython(), SketcherGui::TaskDlgEditSketch::~TaskDlgEditSketch(), and PartDesignGui::TaskDlgFeaturePick::~TaskDlgFeaturePick().
pos
ButtonPosition Gui::TaskView::TaskDialog::pos protected
Definition at line 179 of file Gui/TaskView/TaskDialog.h.
Referenced by draftguitools.gui_splines.BSpline::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_beziers.CubicBezCurve::action(), src.Mod.PartDesign.fcgear.svggear.SVGWireBuilder::arc(), src.Mod.PartDesign.fcsprocket.fcsprocket.FCWireBuilder::arc(), src.Mod.PartDesign.fcgear.fcgear.FCWireBuilder::arc(), src.Mod.PartDesign.fcgear.svggear.SVGWireBuilder::curve(), src.Mod.PartDesign.fcsprocket.fcsprocket.FCWireBuilder::curve(), src.Mod.PartDesign.fcgear.fcgear.FCWireBuilder::curve(), src.Mod.PartDesign.fcgear.svggear.SVGWireBuilder::line(), src.Mod.PartDesign.fcsprocket.fcsprocket.FCWireBuilder::line(), src.Mod.PartDesign.fcgear.fcgear.FCWireBuilder::line(), src.Mod.PartDesign.fcgear.svggear.SVGWireBuilder::move(), src.Mod.PartDesign.fcsprocket.fcsprocket.FCWireBuilder::move(), src.Mod.PartDesign.fcgear.fcgear.FCWireBuilder::move(), Path.Dressup.DogboneII.BoneState::position(), and draftguitools.gui_trackers.boxTracker::update().
The documentation for this class was generated from the following files:
Gui/TaskView/TaskDialog.h
Gui/TaskView/TaskDialog.cpp