FreeCAD: AdaptivePath::BoundBox Class Reference
AdaptivePath::BoundBox Class Reference
Public Member Functions
BoundBox ()
BoundBox (const IntPoint &p1)
void SetFirstPoint (const IntPoint &p1)
void AddPoint (const IntPoint &pt)
BoundBox (const IntPoint &p1, const IntPoint &p2)
BoundBox (const IntPoint &center, long radius)
bool CollidesWith (const BoundBox &bb2)
bool Contains (const BoundBox &bb2)
Public Attributes
ClipperLib::cInt minX
ClipperLib::cInt maxX
ClipperLib::cInt minY
ClipperLib::cInt maxY
Detailed Description
Definition at line 181 of file Adaptive.cpp.
Constructor & Destructor Documentation
BoundBox() [1/4]
AdaptivePath::BoundBox::BoundBox () inline
Definition at line 184 of file Adaptive.cpp.
BoundBox() [2/4]
AdaptivePath::BoundBox::BoundBox (const IntPoint & p1) inline
Definition at line 193 of file Adaptive.cpp.
BoundBox() [3/4]
AdaptivePath::BoundBox::BoundBox (const IntPoint & p1, const IntPoint & p2) inline
Definition at line 219 of file Adaptive.cpp.
BoundBox() [4/4]
AdaptivePath::BoundBox::BoundBox (const IntPoint & center, long radius) inline
Definition at line 240 of file Adaptive.cpp.
References exportCSG::center().
Member Function Documentation
AddPoint()
void AdaptivePath::BoundBox::AddPoint (const IntPoint & pt) inline
Definition at line 210 of file Adaptive.cpp.
References KDL::max(), and KDL::min().
Referenced by AdaptivePath::IntersectionPoint().
CollidesWith()
bool AdaptivePath::BoundBox::CollidesWith (const BoundBox & bb2) inline
Definition at line 249 of file Adaptive.cpp.
References maxX, maxY, minX, and minY.
Referenced by AdaptivePath::ClearedArea::GetBoundedClearedPaths(), AdaptivePath::IntersectionPoint(), and AdaptivePath::Line2CircleIntersect().
Contains()
bool AdaptivePath::BoundBox::Contains (const BoundBox & bb2) inline
Definition at line 255 of file Adaptive.cpp.
References maxX, maxY, minX, and minY.
SetFirstPoint()
void AdaptivePath::BoundBox::SetFirstPoint (const IntPoint & p1) inline
Definition at line 201 of file Adaptive.cpp.
Member Data Documentation
maxX
ClipperLib::cInt AdaptivePath::BoundBox::maxX
Definition at line 261 of file Adaptive.cpp.
Referenced by CollidesWith(), and Contains().
maxY
ClipperLib::cInt AdaptivePath::BoundBox::maxY
Definition at line 263 of file Adaptive.cpp.
Referenced by CollidesWith(), and Contains().
minX
ClipperLib::cInt AdaptivePath::BoundBox::minX
Definition at line 260 of file Adaptive.cpp.
Referenced by CollidesWith(), and Contains().
minY
ClipperLib::cInt AdaptivePath::BoundBox::minY
Definition at line 262 of file Adaptive.cpp.
Referenced by CollidesWith(), and Contains().
The documentation for this class was generated from the following file:
Adaptive.cpp