FreeCAD: CAMTests.TestPathRotationGenerator.TestPathRotationGenerator Class Reference
CAMTests.TestPathRotationGenerator.TestPathRotationGenerator Class Reference
Public Member Functions
def test00 (self)
def test10 (self)
def test20 (self)
def test30 (self)
def test40 (self)
def test50 (self)
Public Member Functions inherited from CAMTests.PathTestUtils.PathTestBase
def assertRoughly (self, f1, f2, error=0.00001)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertPlacement (self, p1, p2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertArc (self, edge, pt1, pt2, direction="CW")
def assertCircle (self, edge, pt, r)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCommandEqual (self, c1, c2)
def assertEqualLocale (self, s1, s2)
def assertEdgeShapesMatch (self, e1, e2)
def assertPointsMatch (self, pts0, pts1)
def assertSuccessfulRecompute (self, doc, *objs, msg=None)
Detailed Description
Definition at line 33 of file TestPathRotationGenerator.py.
Member Function Documentation
test00()
def CAMTests.TestPathRotationGenerator.TestPathRotationGenerator.test00 (self)
Test relAngle function
Definition at line 34 of file TestPathRotationGenerator.py.
Referenced by CAMTests.TestPathToolController.TestPathToolController.test01().
test10()
def CAMTests.TestPathRotationGenerator.TestPathRotationGenerator.test10 (self)
Test Basic Rotation Generator Return
Definition at line 51 of file TestPathRotationGenerator.py.
References Path.Log.debug(), and Path.Post.scripts.grbl_post.type.
test20()
def CAMTests.TestPathRotationGenerator.TestPathRotationGenerator.test20 (self)
Test non-zero rotation
Definition at line 79 of file TestPathRotationGenerator.py.
References Path.Log.debug(), and Path.Log.track().
test30()
def CAMTests.TestPathRotationGenerator.TestPathRotationGenerator.test30 (self)
Test A limits
Definition at line 100 of file TestPathRotationGenerator.py.
References Path.Log.debug().
test40()
def CAMTests.TestPathRotationGenerator.TestPathRotationGenerator.test40 (self)
Test C limits
Definition at line 128 of file TestPathRotationGenerator.py.
References Path.Log.debug().
test50()
def CAMTests.TestPathRotationGenerator.TestPathRotationGenerator.test50 (self)
Test handling of no valid solution
Definition at line 156 of file TestPathRotationGenerator.py.
The documentation for this class was generated from the following file:
TestPathRotationGenerator.py