FreeCAD: PathGui::DlgProcessorChooser Class Reference
PathGui::DlgProcessorChooser Class Reference
#include <DlgProcessorChooser.h>
Public Member Functions
DlgProcessorChooser (std::vector< std::string > &scriptnames, bool withArguments=false)
~DlgProcessorChooser () override
std::string getProcessor ()
std::string getArguments ()
void accept () override
Detailed Description
Definition at line 34 of file DlgProcessorChooser.h.
Constructor & Destructor Documentation
DlgProcessorChooser()
DlgProcessorChooser::DlgProcessorChooser (std::vector< std::string > & scriptnames, bool withArguments = false) explicit
Definition at line 38 of file DlgProcessorChooser.cpp.
~DlgProcessorChooser()
DlgProcessorChooser::~DlgProcessorChooser () override
Definition at line 55 of file DlgProcessorChooser.cpp.
Member Function Documentation
accept()
void DlgProcessorChooser::accept () override
Definition at line 70 of file DlgProcessorChooser.cpp.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
getArguments()
std::string DlgProcessorChooser::getArguments ()
Definition at line 65 of file DlgProcessorChooser.cpp.
getProcessor()
std::string DlgProcessorChooser::getProcessor ()
Definition at line 60 of file DlgProcessorChooser.cpp.
The documentation for this class was generated from the following files:
DlgProcessorChooser.h
DlgProcessorChooser.cpp