FreeCAD: FemGui::TaskDlgMeshShapeNetgen Class Reference
FemGui::TaskDlgMeshShapeNetgen Class Reference
simulation dialog for the TaskView
#include <TaskDlgMeshShapeNetgen.h>
Public Member Functions
TaskDlgMeshShapeNetgen (FemGui::ViewProviderFemMeshShapeNetgen *)
~TaskDlgMeshShapeNetgen () override
void open () override
is called the TaskView when the dialog is opened
void clicked (int) override
is called by the framework if an button is clicked which has no accept or rject role
bool accept () override
is called by the framework if the dialog is accepted (Ok)
bool reject () override
is called by the framework if the dialog is rejected (Cancel)
void helpRequested () override
is called by the framework if the user press the help button
QDialogButtonBox::StandardButtons getStandardButtons () const override
returns for Close and Help button
Public Member Functions inherited from Gui::TaskView::TaskDialog
TaskDialog ()
~TaskDialog () override
QWidget * addTaskBox (QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBox (const QPixmap &icon, QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBoxWithoutHeader (QWidget *widget)
void setButtonPosition (ButtonPosition p)
ButtonPosition buttonPosition () const
const std::vector< QWidget * > & getDialogContent () const
bool canClose () const
virtual void modifyStandardButtons (QDialogButtonBox *)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
bool isEscapeButtonEnabled () const
void setAutoCloseOnTransactionChange (bool on)
bool isAutoCloseOnTransactionChange () const
void setAutoCloseOnDeletedDocument (bool on)
bool isAutoCloseOnDeletedDocument () const
const std::string & getDocumentName () const
void setDocumentName (const std::string &doc)
void setAutoCloseOnClosedView (bool on)
bool isAutoCloseOnClosedView () const
void associateToObject3dView (App::DocumentObject *obj)
const Gui::MDIView * getAssociatedView () const
void setAssociatedView (const Gui::MDIView *view)
virtual bool isAllowedAlterDocument () const
virtual bool isAllowedAlterView () const
virtual bool isAllowedAlterSelection () const
virtual bool needsFullSpace () const
virtual void closed ()
is called by the framework when the dialog is closed
virtual void autoClosedOnTransactionChange ()
virtual void autoClosedOnDeletedDocument ()
virtual void autoClosedOnClosedView ()
void emitDestructionSignal ()
Protected Attributes
TaskTetParameter * param
Fem::FemMeshShapeNetgenObject * FemMeshShapeNetgenObject
FemGui::ViewProviderFemMeshShapeNetgen * ViewProviderFemMeshShapeNetgen
Protected Attributes inherited from Gui::TaskView::TaskDialog
QPointer< QDialogButtonBox > buttonBox
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Detailed Description
simulation dialog for the TaskView
Definition at line 42 of file TaskDlgMeshShapeNetgen.h.
Constructor & Destructor Documentation
TaskDlgMeshShapeNetgen()
TaskDlgMeshShapeNetgen::TaskDlgMeshShapeNetgen (FemGui::ViewProviderFemMeshShapeNetgen * obj) explicit
Definition at line 50 of file TaskDlgMeshShapeNetgen.cpp.
References Gui::TaskView::TaskDialog::Content, FemMeshShapeNetgenObject, Gui::ViewProviderDocumentObject::getObject(), and param.
~TaskDlgMeshShapeNetgen()
TaskDlgMeshShapeNetgen::~TaskDlgMeshShapeNetgen () override default
Member Function Documentation
accept()
bool TaskDlgMeshShapeNetgen::accept () override virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 92 of file TaskDlgMeshShapeNetgen.cpp.
References Gui::cmdAppDocument(), Gui::cmdGuiDocument(), Gui::Command::commitCommand(), Base::Console(), toolbit-attributes::doc, SCL.SimpleDataTypes::e, FemMeshShapeNetgenObject, App::DocumentObject::getDocument(), Gui::getMainWindow(), App::DocumentObject::getStatusString(), App::PropertyLink::getValue(), Gui::Application::hideViewProvider(), Gui::Application::Instance, param, App::DocumentObject::recomputeFeature(), Gui::WaitCursor::restoreCursor(), Fem::FemMeshShapeBaseObject::Shape, FemGui::TaskTetParameter::touched, and Base::ConsoleSingleton::Warning().
Referenced by MaterialEditor.MaterialEditor::verify().
clicked()
void TaskDlgMeshShapeNetgen::clicked (int button) override virtual
is called by the framework if an button is clicked which has no accept or rject role
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 76 of file TaskDlgMeshShapeNetgen.cpp.
References Base::Console(), SCL.SimpleDataTypes::e, Fem::FemMeshShapeNetgenObject::execute(), FemMeshShapeNetgenObject, param, FemGui::TaskTetParameter::setInfo(), FemGui::TaskTetParameter::touched, and Base::ConsoleSingleton::Warning().
getStandardButtons()
QDialogButtonBox::StandardButtons FemGui::TaskDlgMeshShapeNetgen::getStandardButtons () const inline override virtual
returns for Close and Help button
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 63 of file TaskDlgMeshShapeNetgen.h.
helpRequested()
void TaskDlgMeshShapeNetgen::helpRequested () override virtual
is called by the framework if the user press the help button
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 144 of file TaskDlgMeshShapeNetgen.cpp.
open()
void TaskDlgMeshShapeNetgen::open () override virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 67 of file TaskDlgMeshShapeNetgen.cpp.
References Gui::Command::hasPendingCommand(), Path.Op.Surface::msg, and Gui::Command::openCommand().
reject()
bool TaskDlgMeshShapeNetgen::reject () override virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 129 of file TaskDlgMeshShapeNetgen.cpp.
References Gui::Command::abortCommand(), Gui::cmdAppDocument(), Gui::cmdGuiDocument(), toolbit-attributes::doc, FemMeshShapeNetgenObject, and App::DocumentObject::getDocument().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action().
Member Data Documentation
FemMeshShapeNetgenObject
Fem::FemMeshShapeNetgenObject* FemGui::TaskDlgMeshShapeNetgen::FemMeshShapeNetgenObject protected
Definition at line 71 of file TaskDlgMeshShapeNetgen.h.
Referenced by accept(), clicked(), reject(), and TaskDlgMeshShapeNetgen().
param
TaskTetParameter* FemGui::TaskDlgMeshShapeNetgen::param protected
Definition at line 69 of file TaskDlgMeshShapeNetgen.h.
Referenced by accept(), clicked(), and TaskDlgMeshShapeNetgen().
ViewProviderFemMeshShapeNetgen
FemGui::ViewProviderFemMeshShapeNetgen* FemGui::TaskDlgMeshShapeNetgen::ViewProviderFemMeshShapeNetgen protected
Definition at line 72 of file TaskDlgMeshShapeNetgen.h.
The documentation for this class was generated from the following files:
TaskDlgMeshShapeNetgen.h
TaskDlgMeshShapeNetgen.cpp