FreeCAD: PyShapeMapper Struct Reference
PyShapeMapper Struct Reference
Public Member Functions
bool populate (MappingStatus status, PyObject *pyobj)
void init (PyObject *g, PyObject *m)
Public Member Functions inherited from Part::ShapeMapper
virtual ~ShapeMapper () noexcept=default
void populate (MappingStatus status, const TopoShape &src, const TopTools_ListOfShape &dst)
void populate (MappingStatus status, const TopTools_ListOfShape &src, const TopTools_ListOfShape &dst)
void populate (MappingStatus status, const std::vector< TopoShape > &src, const std::vector< TopoShape > &dst)
void populate (MappingStatus status, const TopoShape &src, const std::vector< TopoShape > &dst)
void expand (const TopoDS_Shape &d, std::vector< TopoDS_Shape > &shapes)
void insert (MappingStatus status, const TopoDS_Shape &s, const std::vector< TopoDS_Shape > &d)
void insert (MappingStatus status, const TopoDS_Shape &s, const TopoDS_Shape &d)
const std::vector< TopoDS_Shape > & generated (const TopoDS_Shape &s) const override
Return a list of shape generated from the given input shape.
const std::vector< TopoDS_Shape > & modified (const TopoDS_Shape &s) const override
Return a list of shape modified from the given input shape.
Public Member Functions inherited from Part::TopoShape::Mapper
virtual ~Mapper ()
Additional Inherited Members
Public Types inherited from Part::ShapeMapper
typedef std::unordered_map< TopoDS_Shape, ShapeValue, ShapeHasher, ShapeHasher > ShapeMap
Public Attributes inherited from Part::ShapeMapper
std::vector< TopoShape > shapes
std::unordered_set< TopoDS_Shape, ShapeHasher, ShapeHasher > shapeSet
ShapeMap _generated
std::unordered_set< TopoDS_Shape, ShapeHasher, ShapeHasher > _generatedShapes
ShapeMap _modified
std::unordered_set< TopoDS_Shape, ShapeHasher, ShapeHasher > _modifiedShapes
Public Attributes inherited from Part::TopoShape::Mapper
std::vector< TopoDS_Shape > _res
Helper vector for temporary storage of both generated and modified shapes.
Detailed Description
Definition at line 2669 of file TopoShapePyImp.cpp.
Member Function Documentation
init()
void PyShapeMapper::init (PyObject * g, PyObject * m) inline
Definition at line 2696 of file TopoShapePyImp.cpp.
References toolbit-attributes::g, Part::Generated, test::m, Part::Modified, and Path.Op.Surface::msg.
Referenced by DocumentObject.DocumentObject::onChanged().
populate()
bool PyShapeMapper::populate (MappingStatus status, PyObject * pyobj) inline
Definition at line 2671 of file TopoShapePyImp.cpp.
References src.Mod.AddonManager.NetworkManager::count, Part::getPyShapes(), SplineSurface::i, and Part::ShapeMapper::populate().
The documentation for this struct was generated from the following file:
TopoShapePyImp.cpp