FreeCAD: Gui::Dialog::DownloadModel Class Reference
Gui::Dialog::DownloadModel Class Reference
#include <DownloadManager.h>
Public Member Functions
DownloadModel (DownloadManager *downloadManager, QObject *parent=nullptr)
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
int rowCount (const QModelIndex &parent=QModelIndex()) const override
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex()) override
Friends
class DownloadManager
Detailed Description
Definition at line 104 of file DownloadManager.h.
Constructor & Destructor Documentation
DownloadModel()
DownloadModel::DownloadModel (DownloadManager * downloadManager, QObject * parent = nullptr) explicit
Definition at line 304 of file DownloadManager.cpp.
Member Function Documentation
data()
QVariant DownloadModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 310 of file DownloadManager.cpp.
References rowCount().
removeRows()
bool DownloadModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex()) override
Definition at line 325 of file DownloadManager.cpp.
References src.Mod.AddonManager.NetworkManager::count, SplineSurface::i, and Init::parent.
Referenced by Gui::Dialog::DownloadManager::cleanup().
rowCount()
int DownloadModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 320 of file DownloadManager.cpp.
References Init::parent.
Referenced by src.Mod.AddonManager.package_list.PackageListItemModel::append_item(), src.Mod.AddonManager.AddonManagerOptions.CustomRepoDataModel::appendData(), src.Mod.AddonManager.package_list.PackageListItemModel::clear(), and data().
Friends And Related Function Documentation
DownloadManager
friend class DownloadManager friend
Definition at line 106 of file DownloadManager.h.
The documentation for this class was generated from the following files:
DownloadManager.h
DownloadManager.cpp