FreeCAD: Gui::SearchBar Class Reference
Gui::SearchBar Class Reference
#include <EditorView.h>
Public Slots
void activate ()
void deactivate ()
void findPrevious ()
void findNext ()
void findCurrent ()
Public Member Functions
SearchBar (QWidget *parent=nullptr)
void setEditor (QPlainTextEdit *textEdit)
Protected Member Functions
void keyPressEvent (QKeyEvent *) override
void changeEvent (QEvent *) override
Detailed Description
Definition at line 147 of file EditorView.h.
Constructor & Destructor Documentation
SearchBar()
SearchBar::SearchBar (QWidget * parent = nullptr) explicit
Definition at line 739 of file EditorView.cpp.
References draftgeoutils.intersections::connect(), deactivate(), findCurrent(), findNext(), findPrevious(), and ArchFence::hide().
Member Function Documentation
activate
void SearchBar::activate () slot
Definition at line 815 of file EditorView.cpp.
References bimcommands.BimViews::show().
Referenced by Gui::EditorView::EditorView(), ArchBuildingPart.ViewProviderBuildingPart::setEdit(), nativeifc.ifc_viewproviders.ifc_vp_object::setupContextMenu(), and ArchBuildingPart.ViewProviderBuildingPart::setupContextMenu().
changeEvent()
void SearchBar::changeEvent (QEvent * event) override protected
Definition at line 911 of file EditorView.cpp.
deactivate
void SearchBar::deactivate () slot
Definition at line 822 of file EditorView.cpp.
References ArchFence::hide().
Referenced by CommandCreateBom.TaskAssemblyCreateBom::accept(), CommandInsertNewPart.TaskAssemblyNewPart::accept(), CommandCreateView.TaskAssemblyCreateView::accept(), CommandCreateSimulation.TaskAssemblyCreateSimulation::accept(), JointObject.TaskAssemblyCreateJoint::accept(), CommandCreateBom.TaskAssemblyCreateBom::reject(), CommandCreateView.TaskAssemblyCreateView::reject(), CommandCreateSimulation.TaskAssemblyCreateSimulation::reject(), JointObject.TaskAssemblyCreateJoint::reject(), and SearchBar().
findCurrent
void SearchBar::findCurrent () slot
Definition at line 840 of file EditorView.cpp.
Referenced by SearchBar().
findNext
void SearchBar::findNext () slot
Definition at line 835 of file EditorView.cpp.
Referenced by Gui::EditorView::EditorView(), and SearchBar().
findPrevious
void SearchBar::findPrevious () slot
Definition at line 830 of file EditorView.cpp.
Referenced by Gui::EditorView::EditorView(), and SearchBar().
keyPressEvent()
void SearchBar::keyPressEvent (QKeyEvent * event) override protected
Definition at line 797 of file EditorView.cpp.
References ArchFence::hide().
setEditor()
void SearchBar::setEditor (QPlainTextEdit * textEdit)
Definition at line 792 of file EditorView.cpp.
The documentation for this class was generated from the following files:
EditorView.h
EditorView.cpp