FreeCAD: DrawingPatterns Namespace Reference
DrawingPatterns Namespace Reference
Functions
def buildPattern (name, scale=5, thickness=1, color="#000000")
def buildTextureImage (name, scale=5, thickness=1, color="#000000", size=64)
def buildSwatch (name, scale=5, thickness=1, color="#000000", size=64)
def buildFileSwatch (name, scale=5, thickness=1, color="#000000", size=64, png=False)
def saveTestImage (filename, scales=[2.5, 5], thicknesses=[0.1, 0.2, 1])
def decodeName (name, scale, thickness)
def getPatternNames ()
Variables
Patterns
AutocadPatterns
Function Documentation
buildFileSwatch()
def DrawingPatterns.buildFileSwatch (name, scale = 5, thickness = 1, color = "#000000", size = 64, png = False)
buildFileSwatch(name,scale,thickness,color="#000000",size=64,png=False)
builds a 64x64 SVG image filled with the given texture, a
white background and a border, to serve as a sample. The image
is saved as a temp file, the filepath is returned
Definition at line 228 of file DrawingPatterns.py.
References buildSwatch(), and AssemblyImport.open().
buildPattern()
def DrawingPatterns.buildPattern (name, scale = 5, thickness = 1, color = "#000000")
buildPattern(name,scale=5,thickness=1,color="#000000")
builds an SVG <pattern> fragment from a name and path data
Definition at line 137 of file DrawingPatterns.py.
References decodeName(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by buildSwatch(), buildTextureImage(), and saveTestImage().
buildSwatch()
def DrawingPatterns.buildSwatch (name, scale = 5, thickness = 1, color = "#000000", size = 64)
buildSwatch(name,scale,thickness,color="#000000",size=64)
builds a 64x64 SVG image filled with the given texture, a
white background and a border, to serve as a sample
Definition at line 190 of file DrawingPatterns.py.
References buildPattern(), decodeName(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by buildFileSwatch().
buildTextureImage()
def DrawingPatterns.buildTextureImage (name, scale = 5, thickness = 1, color = "#000000", size = 64)
buildTextureImage(name,scale,thickness,color="#000000",size=64)
builds a 64x64 SVG image filled with the given texture
Definition at line 159 of file DrawingPatterns.py.
References buildPattern(), decodeName(), and Path.Post.scripts.refactored_centroid_post.str.
decodeName()
def DrawingPatterns.decodeName (name, scale, thickness)
decodeName(name,scale,thickness) : decodes names written in the form 'name_5_1'
Definition at line 293 of file DrawingPatterns.py.
Referenced by buildPattern(), buildSwatch(), and buildTextureImage().
getPatternNames()
def DrawingPatterns.getPatternNames ()
getPatternNames : returns available pattern names
Definition at line 310 of file DrawingPatterns.py.
saveTestImage()
def DrawingPatterns.saveTestImage (filename, scales = [2.5, 5], thicknesses = [0.1, 0.2, 1])
saveTestImage(filename,scales=[2.5,5],thicknesses=[0.1,0.2,1])
builds a test SVG file showing all available patterns at given scales and thicknesses
Definition at line 254 of file DrawingPatterns.py.
References buildPattern(), AssemblyImport.open(), and Path.Post.scripts.refactored_centroid_post.str.
Variable Documentation
AutocadPatterns
DrawingPatterns.AutocadPatterns
Definition at line 64 of file DrawingPatterns.py.
Patterns
DrawingPatterns.Patterns
Definition at line 32 of file DrawingPatterns.py.