FreeCAD: SketcherGui::ConstraintFilterList Class Reference
SketcherGui::ConstraintFilterList Class Reference
#include <TaskSketcherConstraints.h>
Public Member Functions
ConstraintFilterList (QWidget *parent=nullptr)
~ConstraintFilterList () override
void setPartiallyChecked ()
FilterValueBitset getMultiFilter ()
Public Attributes
int normalFilterCount
int selectedFilterIndex
int associatedFilterIndex
Protected Member Functions
void changeEvent (QEvent *e) override
void languageChange ()
Detailed Description
Definition at line 85 of file TaskSketcherConstraints.h.
Constructor & Destructor Documentation
ConstraintFilterList()
ConstraintFilterList::ConstraintFilterList (QWidget * parent = nullptr) explicit
Definition at line 718 of file TaskSketcherConstraints.cpp.
References associatedFilterIndex, App::GetApplication(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), languageChange(), normalFilterCount, selectedFilterIndex, and setPartiallyChecked().
~ConstraintFilterList()
ConstraintFilterList::~ConstraintFilterList () override
Definition at line 745 of file TaskSketcherConstraints.cpp.
Member Function Documentation
changeEvent()
void ConstraintFilterList::changeEvent (QEvent * e) override protected
Definition at line 748 of file TaskSketcherConstraints.cpp.
References SCL.SimpleDataTypes::e, and languageChange().
getMultiFilter()
FilterValueBitset ConstraintFilterList::getMultiFilter ()
Definition at line 800 of file TaskSketcherConstraints.cpp.
References SplineSurface::i, and normalFilterCount.
languageChange()
void ConstraintFilterList::languageChange () protected
Definition at line 756 of file TaskSketcherConstraints.cpp.
References src.Mod.AddonManager.NetworkManager::count, and SplineSurface::i.
Referenced by changeEvent(), and ConstraintFilterList().
setPartiallyChecked()
void ConstraintFilterList::setPartiallyChecked ()
Definition at line 768 of file TaskSketcherConstraints.cpp.
References SketcherGui::ConstraintFilter::filterAggregates, SketcherGui::ConstraintFilter::FilterValueLength, SplineSurface::i, and normalFilterCount.
Referenced by ConstraintFilterList(), and SketcherGui::TaskSketcherConstraints::onFilterListItemChanged().
Member Data Documentation
associatedFilterIndex
int SketcherGui::ConstraintFilterList::associatedFilterIndex
Definition at line 99 of file TaskSketcherConstraints.h.
Referenced by ConstraintFilterList(), and SketcherGui::TaskSketcherConstraints::onFilterListItemChanged().
normalFilterCount
int SketcherGui::ConstraintFilterList::normalFilterCount
Definition at line 97 of file TaskSketcherConstraints.h.
Referenced by ConstraintFilterList(), getMultiFilter(), SketcherGui::TaskSketcherConstraints::onFilterListItemChanged(), and setPartiallyChecked().
selectedFilterIndex
int SketcherGui::ConstraintFilterList::selectedFilterIndex
Definition at line 98 of file TaskSketcherConstraints.h.
Referenced by ConstraintFilterList(), and SketcherGui::TaskSketcherConstraints::onFilterListItemChanged().
The documentation for this class was generated from the following files:
TaskSketcherConstraints.h
TaskSketcherConstraints.cpp