FreeCAD: AppInspection.cpp File Reference
AppInspection.cpp File Reference
#include "PreCompiled.h"
#include <Base/Console.h>
#include <Base/PyObjectBase.h>
#include "InspectionFeature.h"
Classes
class Inspection::Module
Namespaces
Inspection
Functions
PyObject * Inspection::initModule ()
PyMOD_INIT_FUNC (Inspection)
Function Documentation
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (Inspection)
Definition at line 54 of file AppInspection.cpp.
References Base::Console(), App::DocumentObjectExtension::init(), Base::Persistence::init(), Inspection::initModule(), Base::ConsoleSingleton::Log(), and mod.