FreeCAD: Gui::FormatString Class Reference
Gui::FormatString Class Reference
#include <CommandT.h>
Static Public Member Functions
static std::string str (const std::string &s)
static std::string str (const char *s)
static std::string str (const QString &s)
static std::string str (const std::stringstream &s)
static std::string str (const std::ostringstream &s)
static std::string str (const std::ostream &s)
static std::string toStr (boost::format &f)
template<typename T , typename... Args>
static std::string toStr (boost::format &f, T &&t, Args &&... args)
Detailed Description
Definition at line 58 of file CommandT.h.
Member Function Documentation
str() [1/6]
static std::string Gui::FormatString::str (const char * s) inline static
Definition at line 84 of file CommandT.h.
str() [2/6]
static std::string Gui::FormatString::str (const QString & s) inline static
Definition at line 87 of file CommandT.h.
str() [3/6]
static std::string Gui::FormatString::str (const std::ostream & s) inline static
Definition at line 96 of file CommandT.h.
str() [4/6]
static std::string Gui::FormatString::str (const std::ostringstream & s) inline static
Definition at line 93 of file CommandT.h.
References toolbit-attributes::doc.
str() [5/6]
static std::string Gui::FormatString::str (const std::string & s) inline static
Definition at line 81 of file CommandT.h.
str() [6/6]
static std::string Gui::FormatString::str (const std::stringstream & s) inline static
Definition at line 90 of file CommandT.h.
toStr() [1/2]
static std::string Gui::FormatString::toStr (boost::format & f) inline static
Definition at line 103 of file CommandT.h.
Referenced by bimcommands.BimNudge.BIM_Nudge_Up::Activated(), bimcommands.BimNudge.BIM_Nudge_Down::Activated(), bimcommands.BimNudge.BIM_Nudge_Left::Activated(), bimcommands.BimNudge.BIM_Nudge_Right::Activated(), bimcommands.BimNudge.BIM_Nudge_RotateLeft::Activated(), bimcommands.BimNudge.BIM_Nudge_RotateRight::Activated(), Gui::cmdAppDocument(), and Gui::cmdAppObjectShow().
toStr() [2/2]
template<typename T , typename... Args> static std::string Gui::FormatString::toStr (boost::format & f, T && t, Args &&... args) inline static
Definition at line 108 of file CommandT.h.
Referenced by bimcommands.BimNudge.BIM_Nudge_Up::Activated(), bimcommands.BimNudge.BIM_Nudge_Down::Activated(), bimcommands.BimNudge.BIM_Nudge_Left::Activated(), bimcommands.BimNudge.BIM_Nudge_Right::Activated(), bimcommands.BimNudge.BIM_Nudge_RotateLeft::Activated(), and bimcommands.BimNudge.BIM_Nudge_RotateRight::Activated().
The documentation for this class was generated from the following file:
CommandT.h