FreeCAD: ifc4.ifcreference Class Reference
ifc4.ifcreference Class Reference
Public Member Functions
def __init__ (self, typeidentifier, attributeidentifier, instancename, listpositions, innerreference)
def typeidentifier ()
def attributeidentifier ()
def instancename ()
def listpositions ()
def innerreference ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
typeidentifier
attributeidentifier
instancename
listpositions
innerreference
Detailed Description
Entity ifcreference definition.
:param typeidentifier
:type typeidentifier:ifcidentifier
:param attributeidentifier
:type attributeidentifier:ifcidentifier
:param instancename
:type instancename:ifclabel
:param listpositions
:type listpositions:LIST(1,None,'INTEGER', scope = schema_scope)
:param innerreference
:type innerreference:ifcreference
Definition at line 36693 of file ifc4.py.
Constructor & Destructor Documentation
__init__()
def ifc4.ifcreference.__init__ (self, typeidentifier, attributeidentifier, instancename, listpositions, innerreference)
Definition at line 36711 of file ifc4.py.
Member Function Documentation
attributeidentifier()
def ifc4.ifcreference.attributeidentifier ()
Definition at line 36733 of file ifc4.py.
References ifc4.ifcreference._attributeidentifier, ifc4.ifcreference.attributeidentifier, and SCL.TypeChecker.check_type().
innerreference()
def ifc4.ifcreference.innerreference ()
Definition at line 36775 of file ifc4.py.
References ifc4.ifcreference._innerreference, SCL.TypeChecker.check_type(), and ifc4.ifcreference.innerreference.
instancename()
def ifc4.ifcreference.instancename ()
Definition at line 36747 of file ifc4.py.
References ifc4.ifcreference._instancename, SCL.TypeChecker.check_type(), and ifc4.ifcreference.instancename.
listpositions()
def ifc4.ifcreference.listpositions ()
Definition at line 36761 of file ifc4.py.
References ifc4.ifcreference._listpositions, SCL.TypeChecker.check_type(), and ifc4.ifcreference.listpositions.
typeidentifier()
def ifc4.ifcreference.typeidentifier ()
Definition at line 36719 of file ifc4.py.
References ifc4.ifcreference._typeidentifier, SCL.TypeChecker.check_type(), and ifc4.ifcreference.typeidentifier.
Member Data Documentation
attributeidentifier
ifc4.ifcreference.attributeidentifier
Definition at line 36713 of file ifc4.py.
Referenced by ifc4.ifcreference.attributeidentifier().
innerreference
ifc4.ifcreference.innerreference
Definition at line 36716 of file ifc4.py.
Referenced by ifc4.ifcreference.innerreference().
instancename
ifc4.ifcreference.instancename
Definition at line 36714 of file ifc4.py.
Referenced by ifc4.ifcreference.instancename().
listpositions
ifc4.ifcreference.listpositions
Definition at line 36715 of file ifc4.py.
Referenced by ifc4.ifcreference.listpositions().
typeidentifier
ifc4.ifcreference.typeidentifier
Definition at line 36712 of file ifc4.py.
Referenced by ifc4.ifcreference.typeidentifier().
The documentation for this class was generated from the following file:
ifc4.py