FreeCAD: PartGui::DlgExtrusion::EdgeSelection Class Reference
PartGui::DlgExtrusion::EdgeSelection Class Reference
Public Member Functions
EdgeSelection ()
bool allow (App::Document *, App::DocumentObject *pObj, const char *sSubName) override
Public Member Functions inherited from Gui::SelectionFilterGate
SelectionFilterGate (const char *filter)
construct with the filter string
SelectionFilterGate (SelectionFilter *filter)
~SelectionFilterGate () override
Public Member Functions inherited from Gui::SelectionGate
virtual ~SelectionGate ()=default
Public Attributes
bool canSelect
Public Attributes inherited from Gui::SelectionGate
std::string notAllowedReason
notAllowedReason is a string that sets the message to be displayed in statusbar for cluing the user on why is the selection not allowed. Set this variable in allow() implementation. Enclose the literal into QT_TR_NOOP() for translatability.
Additional Inherited Members
Protected Member Functions inherited from Gui::SelectionFilterGate
SelectionFilterGate ()
Static Protected Member Functions inherited from Gui::SelectionFilterGate
static SelectionFilter * nullPointer ()
static const char * nullString ()
Protected Attributes inherited from Gui::SelectionFilterGate
SelectionFilter * Filter
Detailed Description
Definition at line 58 of file DlgExtrusion.cpp.
Constructor & Destructor Documentation
EdgeSelection()
PartGui::DlgExtrusion::EdgeSelection::EdgeSelection () inline
Definition at line 63 of file DlgExtrusion.cpp.
Member Function Documentation
allow()
bool PartGui::DlgExtrusion::EdgeSelection::allow (App::Document * , App::DocumentObject * pObj, const char * sSubName) inline override virtual
Reimplemented from Gui::SelectionFilterGate.
Definition at line 68 of file DlgExtrusion.cpp.
References Part::TopoShape::getShape(), Part::Feature::getTopoShape(), and Part::TopoShape::isNull().
Member Data Documentation
canSelect
bool PartGui::DlgExtrusion::EdgeSelection::canSelect
Definition at line 61 of file DlgExtrusion.cpp.
The documentation for this class was generated from the following file:
DlgExtrusion.cpp