FreeCAD: Gui::MDIViewPyWrapImp Class Reference
Gui::MDIViewPyWrapImp Class Reference
Public Member Functions
MDIViewPyWrapImp (Py::Object pyobject)
~MDIViewPyWrapImp ()
QWidget * widget ()
bool onMsg (const char *pMsg)
bool onHasMsg (const char *pMsg)
bool canClose ()
void printDocument (QPrinter *printer)
void print ()
void printPdf ()
void printPreview ()
QStringList undoActions ()
QStringList redoActions ()
Detailed Description
Definition at line 41 of file MDIViewPyWrap.cpp.
Constructor & Destructor Documentation
MDIViewPyWrapImp()
Gui::MDIViewPyWrapImp::MDIViewPyWrapImp (Py::Object pyobject) inline
Definition at line 44 of file MDIViewPyWrap.cpp.
~MDIViewPyWrapImp()
Gui::MDIViewPyWrapImp::~MDIViewPyWrapImp () inline
Definition at line 57 of file MDIViewPyWrap.cpp.
Member Function Documentation
canClose()
bool Gui::MDIViewPyWrapImp::canClose () inline
Definition at line 93 of file MDIViewPyWrap.cpp.
References result.
onHasMsg()
bool Gui::MDIViewPyWrapImp::onHasMsg (const char * pMsg) inline
Definition at line 85 of file MDIViewPyWrap.cpp.
References result, and src.Mod.Test.testmakeWireString::String.
onMsg()
bool Gui::MDIViewPyWrapImp::onMsg (const char * pMsg) inline
Definition at line 77 of file MDIViewPyWrap.cpp.
References result, and src.Mod.Test.testmakeWireString::String.
print()
void Gui::MDIViewPyWrapImp::print () inline
Definition at line 111 of file MDIViewPyWrap.cpp.
printDocument()
void Gui::MDIViewPyWrapImp::printDocument (QPrinter * printer) inline
Definition at line 101 of file MDIViewPyWrap.cpp.
References Gui::PythonWrapper::fromQPrinter(), and Gui::PythonWrapper::loadPrintSupportModule().
printPdf()
void Gui::MDIViewPyWrapImp::printPdf () inline
Definition at line 118 of file MDIViewPyWrap.cpp.
printPreview()
void Gui::MDIViewPyWrapImp::printPreview () inline
Definition at line 125 of file MDIViewPyWrap.cpp.
redoActions()
QStringList Gui::MDIViewPyWrapImp::redoActions () inline
Definition at line 145 of file MDIViewPyWrap.cpp.
References Path.Post.scripts.refactored_centroid_post::str, and src.Mod.Test.testmakeWireString::String.
undoActions()
QStringList Gui::MDIViewPyWrapImp::undoActions () inline
Definition at line 132 of file MDIViewPyWrap.cpp.
References Path.Post.scripts.refactored_centroid_post::str, and src.Mod.Test.testmakeWireString::String.
widget()
QWidget* Gui::MDIViewPyWrapImp::widget () inline
Definition at line 64 of file MDIViewPyWrap.cpp.
References Gui::PythonWrapper::loadWidgetsModule(), and Gui::PythonWrapper::toQObject().
The documentation for this class was generated from the following file:
MDIViewPyWrap.cpp