FreeCAD: MeshCore::MeshRefPointToPoints Class Reference
MeshCore::MeshRefPointToPoints Class Reference
#include <Algorithm.h>
Public Member Functions
MeshRefPointToPoints (const MeshKernel &rclM)
Construction.
void Rebuild ()
Rebuilds up data structure.
const std::set< PointIndex > & operator[] (PointIndex) const
Base::Vector3f GetNormal (PointIndex) const
float GetAverageEdgeLength (PointIndex) const
void AddNeighbour (PointIndex, PointIndex)
void RemoveNeighbour (PointIndex, PointIndex)
Detailed Description
The MeshRefPointToPoints builds up a structure to have access to all neighbour points of a point. Two points are neighbours if there is an edge indexing both points.
Note
If the underlying mesh kernel gets changed this structure becomes invalid and must be rebuilt.
Definition at line 546 of file Algorithm.h.
Constructor & Destructor Documentation
MeshRefPointToPoints()
MeshCore::MeshRefPointToPoints::MeshRefPointToPoints (const MeshKernel & rclM) inline explicit
Construction.
Definition at line 550 of file Algorithm.h.
Member Function Documentation
AddNeighbour()
void MeshRefPointToPoints::AddNeighbour (PointIndex pos, PointIndex facet)
Definition at line 2097 of file Algorithm.cpp.
References RobotExample::pos.
GetAverageEdgeLength()
float MeshRefPointToPoints::GetAverageEdgeLength (PointIndex index) const
Definition at line 2080 of file Algorithm.cpp.
References Base::Distance(), MeshCore::MeshKernel::GetPoints(), and buildPsets::p.
GetNormal()
Base::Vector3f MeshRefPointToPoints::GetNormal (PointIndex pos) const
Definition at line 2061 of file Algorithm.cpp.
References MeshCore::Approximation::AddPoint(), exportCSG::center(), MeshCore::PlaneFit::Fit(), MeshCore::PlaneFit::GetNormal(), MeshCore::MeshKernel::GetPoints(), Base::Vector3< float_type >::Normalize(), and RobotExample::pos.
operator[]()
const std::set< PointIndex > & MeshRefPointToPoints::operator[] (PointIndex pos) const
Definition at line 2092 of file Algorithm.cpp.
References RobotExample::pos.
Rebuild()
void MeshRefPointToPoints::Rebuild ()
Rebuilds up data structure.
Definition at line 2039 of file Algorithm.cpp.
References MeshCore::MeshKernel::GetFacets(), and MeshCore::MeshKernel::GetPoints().
RemoveNeighbour()
void MeshRefPointToPoints::RemoveNeighbour (PointIndex pos, PointIndex facet)
Definition at line 2102 of file Algorithm.cpp.
References RobotExample::pos.
The documentation for this class was generated from the following files:
Algorithm.h
Algorithm.cpp