FreeCAD: TechDrawGui::TaskWeldingSymbol Class Reference
TechDrawGui::TaskWeldingSymbol Class Reference
#include <TaskWeldingSymbol.h>
Public Slots
void symbolDialog (const char *source)
void onArrowSymbolCreateClicked ()
void onArrowSymbolClicked ()
void onOtherSymbolCreateClicked ()
void onOtherSymbolClicked ()
void onOtherEraseCreateClicked ()
void onOtherEraseClicked ()
void onFlipSidesCreateClicked ()
void onFlipSidesClicked ()
void onArrowTextChanged ()
void onOtherTextChanged ()
void onWeldingChanged ()
void onDirectorySelected (const QString &newDir)
void onSymbolSelected (QString symbolPath, QString source)
Public Member Functions
TaskWeldingSymbol (TechDraw::DrawLeaderLine *leadFeat)
TaskWeldingSymbol (TechDraw::DrawWeldSymbol *weldFeat)
~TaskWeldingSymbol () override
virtual bool accept ()
virtual bool reject ()
void updateTask ()
void saveButtons (QPushButton *btnOK, QPushButton *btnCancel)
void enableTaskButtons (bool enable)
Protected Member Functions
void changeEvent (QEvent *event) override
void setUiPrimary ()
void setUiEdit ()
TechDraw::DrawWeldSymbol * createWeldingSymbol ()
void updateWeldingSymbol ()
void getTileFeats ()
void updateTiles ()
void collectArrowData ()
void collectOtherData ()
std::string prefSymbolDir ()
Protected Attributes
QString m_currDir
Detailed Description
Definition at line 93 of file TaskWeldingSymbol.h.
Constructor & Destructor Documentation
TaskWeldingSymbol() [1/2]
TaskWeldingSymbol::TaskWeldingSymbol (TechDraw::DrawLeaderLine * leadFeat)
Definition at line 52 of file TaskWeldingSymbol.cpp.
References draftgeoutils.intersections::connect(), onArrowSymbolCreateClicked(), onDirectorySelected(), onFlipSidesCreateClicked(), onOtherEraseCreateClicked(), onOtherSymbolCreateClicked(), and setUiPrimary().
TaskWeldingSymbol() [2/2]
TaskWeldingSymbol::TaskWeldingSymbol (TechDraw::DrawWeldSymbol * weldFeat)
Definition at line 82 of file TaskWeldingSymbol.cpp.
References draftgeoutils.intersections::connect(), Base::Console(), Base::ConsoleSingleton::Error(), Base::Persistence::getClassTypeId(), App::PropertyLink::getValue(), Base::BaseClass::isDerivedFrom(), TechDraw::DrawWeldSymbol::Leader, onArrowSymbolClicked(), onArrowTextChanged(), onDirectorySelected(), onFlipSidesClicked(), onOtherEraseClicked(), onOtherSymbolClicked(), onOtherTextChanged(), onWeldingChanged(), and setUiEdit().
~TaskWeldingSymbol()
TaskWeldingSymbol::~TaskWeldingSymbol () override
Definition at line 145 of file TaskWeldingSymbol.cpp.
Member Function Documentation
accept()
bool TaskWeldingSymbol::accept () virtual
Definition at line 557 of file TaskWeldingSymbol.cpp.
References Gui::Command::commitCommand(), Base::Console(), createWeldingSymbol(), doCommand, Base::ConsoleSingleton::Error(), Gui::Command::Gui, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, App::DocumentObject::recomputeFeature(), Gui::Command::updateActive(), updateTiles(), and updateWeldingSymbol().
Referenced by TechDrawGui::TaskDlgWeldingSymbol::accept().
changeEvent()
void TaskWeldingSymbol::changeEvent (QEvent * event) override protected
Definition at line 156 of file TaskWeldingSymbol.cpp.
collectArrowData()
void TaskWeldingSymbol::collectArrowData () protected
Definition at line 400 of file TaskWeldingSymbol.cpp.
References TechDrawGui::TileImage::arrowSide, TechDrawGui::TileImage::centerText, TechDrawGui::TileImage::col, TechDrawGui::TileImage::leftText, TechDrawGui::TileImage::rightText, TechDrawGui::TileImage::row, TechDrawGui::TileImage::symbolPath, TechDrawGui::TileImage::tileName, and TechDrawGui::TileImage::toBeSaved.
Referenced by updateTiles().
collectOtherData()
void TaskWeldingSymbol::collectOtherData () protected
Definition at line 414 of file TaskWeldingSymbol.cpp.
References TechDrawGui::TileImage::arrowSide, TechDrawGui::TileImage::centerText, TechDrawGui::TileImage::col, TechDrawGui::TileImage::leftText, TechDrawGui::TileImage::rightText, TechDrawGui::TileImage::row, TechDrawGui::TileImage::symbolPath, TechDrawGui::TileImage::tileName, and TechDrawGui::TileImage::toBeSaved.
Referenced by updateTiles().
createWeldingSymbol()
TechDraw::DrawWeldSymbol * TaskWeldingSymbol::createWeldingSymbol () protected
Definition at line 456 of file TaskWeldingSymbol.cpp.
References TechDraw::DrawPage::addView(), toolbit-attributes::doc, TechDraw::DrawView::findParentPage(), and Instance.
Referenced by accept().
enableTaskButtons()
void TaskWeldingSymbol::enableTaskButtons (bool enable)
Definition at line 549 of file TaskWeldingSymbol.cpp.
getTileFeats()
void TaskWeldingSymbol::getTileFeats () protected
Definition at line 428 of file TaskWeldingSymbol.cpp.
References TechDraw::DrawWeldSymbol::getTiles(), App::PropertyInteger::getValue(), and TechDraw::DrawTile::TileRow.
Referenced by setUiEdit(), and updateTiles().
onArrowSymbolClicked
void TaskWeldingSymbol::onArrowSymbolClicked () slot
Definition at line 258 of file TaskWeldingSymbol.cpp.
References TechDraw::DrawView::requestPaint(), symbolDialog(), and updateTiles().
Referenced by TaskWeldingSymbol().
onArrowSymbolCreateClicked
void TaskWeldingSymbol::onArrowSymbolCreateClicked () slot
Definition at line 253 of file TaskWeldingSymbol.cpp.
References symbolDialog().
Referenced by TaskWeldingSymbol().
onArrowTextChanged
void TaskWeldingSymbol::onArrowTextChanged () slot
Definition at line 352 of file TaskWeldingSymbol.cpp.
References TechDraw::DrawView::requestPaint(), and updateTiles().
Referenced by TaskWeldingSymbol().
onDirectorySelected
void TaskWeldingSymbol::onDirectorySelected (const QString & newDir) slot
Definition at line 371 of file TaskWeldingSymbol.cpp.
References m_currDir.
Referenced by TaskWeldingSymbol().
onFlipSidesClicked
void TaskWeldingSymbol::onFlipSidesClicked () slot
Definition at line 325 of file TaskWeldingSymbol.cpp.
References App::PropertyString::getValue(), TechDraw::DrawView::requestPaint(), TechDraw::DrawTileWeld::SymbolFile, and updateTiles().
Referenced by TaskWeldingSymbol().
onFlipSidesCreateClicked
void TaskWeldingSymbol::onFlipSidesCreateClicked () slot
Definition at line 302 of file TaskWeldingSymbol.cpp.
Referenced by TaskWeldingSymbol().
onOtherEraseClicked
void TaskWeldingSymbol::onOtherEraseClicked () slot
Definition at line 288 of file TaskWeldingSymbol.cpp.
References TechDrawGui::TileImage::init(), TechDraw::DrawView::requestPaint(), and updateTiles().
Referenced by TaskWeldingSymbol().
onOtherEraseCreateClicked
void TaskWeldingSymbol::onOtherEraseCreateClicked () slot
Definition at line 277 of file TaskWeldingSymbol.cpp.
References TechDrawGui::TileImage::init().
Referenced by TaskWeldingSymbol().
onOtherSymbolClicked
void TaskWeldingSymbol::onOtherSymbolClicked () slot
Definition at line 270 of file TaskWeldingSymbol.cpp.
References TechDraw::DrawView::requestPaint(), symbolDialog(), and updateTiles().
Referenced by TaskWeldingSymbol().
onOtherSymbolCreateClicked
void TaskWeldingSymbol::onOtherSymbolCreateClicked () slot
Definition at line 265 of file TaskWeldingSymbol.cpp.
References symbolDialog().
Referenced by TaskWeldingSymbol().
onOtherTextChanged
void TaskWeldingSymbol::onOtherTextChanged () slot
Definition at line 358 of file TaskWeldingSymbol.cpp.
References TechDraw::DrawView::requestPaint(), and updateTiles().
Referenced by TaskWeldingSymbol().
onSymbolSelected
void TaskWeldingSymbol::onSymbolSelected (QString symbolPath, QString source) slot
Definition at line 377 of file TaskWeldingSymbol.cpp.
Referenced by symbolDialog().
onWeldingChanged
void TaskWeldingSymbol::onWeldingChanged () slot
Definition at line 365 of file TaskWeldingSymbol.cpp.
References TechDraw::DrawView::requestPaint(), and updateWeldingSymbol().
Referenced by TaskWeldingSymbol().
prefSymbolDir()
std::string TechDrawGui::TaskWeldingSymbol::prefSymbolDir () protected
reject()
bool TaskWeldingSymbol::reject () virtual
Definition at line 588 of file TaskWeldingSymbol.cpp.
References doCommand, and Gui::Command::Gui.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and TechDrawGui::TaskDlgWeldingSymbol::reject().
saveButtons()
void TaskWeldingSymbol::saveButtons (QPushButton * btnOK, QPushButton * btnCancel)
Definition at line 542 of file TaskWeldingSymbol.cpp.
Referenced by TechDrawGui::TaskDlgWeldingSymbol::modifyStandardButtons().
setUiEdit()
void TaskWeldingSymbol::setUiEdit () protected
Definition at line 182 of file TaskWeldingSymbol.cpp.
References TechDraw::DrawWeldSymbol::AllAround, TechDraw::DrawWeldSymbol::AlternatingWeld, TechDraw::DrawTileWeld::CenterText, TechDraw::DrawWeldSymbol::FieldWeld, getTileFeats(), App::PropertyString::getValue(), App::PropertyBool::getValue(), TechDraw::DrawTileWeld::LeftText, m_currDir, TechDraw::DrawTileWeld::RightText, TechDraw::DrawTileWeld::SymbolFile, TechDraw::DrawWeldSymbol::TailText, and TechDrawGui::PreferencesGui::weldingDirectory().
Referenced by TaskWeldingSymbol().
setUiPrimary()
void TaskWeldingSymbol::setUiPrimary () protected
Definition at line 163 of file TaskWeldingSymbol.cpp.
References TechDrawGui::TileImage::init(), m_currDir, and TechDrawGui::PreferencesGui::weldingDirectory().
Referenced by TaskWeldingSymbol().
symbolDialog
void TaskWeldingSymbol::symbolDialog (const char * source) slot
Definition at line 243 of file TaskWeldingSymbol.cpp.
References draftgeoutils.intersections::connect(), m_currDir, onSymbolSelected(), and TechDrawGui::SymbolChooser::symbolSelected().
Referenced by onArrowSymbolClicked(), onArrowSymbolCreateClicked(), onOtherSymbolClicked(), and onOtherSymbolCreateClicked().
updateTask()
void TaskWeldingSymbol::updateTask ()
Definition at line 149 of file TaskWeldingSymbol.cpp.
updateTiles()
void TaskWeldingSymbol::updateTiles () protected
Definition at line 487 of file TaskWeldingSymbol.cpp.
References TechDrawGui::TileImage::centerText, TechDrawGui::TileImage::col, collectArrowData(), collectOtherData(), Base::Console(), doCommand, Base::Tools::escapeEncodeString(), App::DocumentObject::getNameInDocument(), getTileFeats(), TechDrawGui::TileImage::leftText, Base::ConsoleSingleton::Message(), TechDrawGui::TileImage::rightText, App::PropertyString::setValue(), TechDraw::DrawTileWeld::SymbolFile, TechDrawGui::TileImage::symbolPath, and TechDrawGui::TileImage::toBeSaved.
Referenced by accept(), onArrowSymbolClicked(), onArrowTextChanged(), onFlipSidesClicked(), onOtherEraseClicked(), onOtherSymbolClicked(), and onOtherTextChanged().
updateWeldingSymbol()
void TaskWeldingSymbol::updateWeldingSymbol () protected
Definition at line 479 of file TaskWeldingSymbol.cpp.
References TechDraw::DrawWeldSymbol::AllAround, TechDraw::DrawWeldSymbol::AlternatingWeld, TechDraw::DrawWeldSymbol::FieldWeld, App::PropertyString::setValue(), App::PropertyBool::setValue(), and TechDraw::DrawWeldSymbol::TailText.
Referenced by accept(), and onWeldingChanged().
Member Data Documentation
m_currDir
QString TechDrawGui::TaskWeldingSymbol::m_currDir protected
Definition at line 141 of file TaskWeldingSymbol.h.
Referenced by onDirectorySelected(), setUiEdit(), setUiPrimary(), and symbolDialog().
The documentation for this class was generated from the following files:
TaskWeldingSymbol.h
TaskWeldingSymbol.cpp