FreeCAD: Gui::MovableGroupModel Class Reference
Gui::MovableGroupModel Class Reference
#include <ManualAlignment.h>
Public Member Functions
MovableGroupModel ()
~MovableGroupModel ()
void addGroup (const MovableGroup &)
void addGroups (const std::map< int, MovableGroup > &)
MovableGroup & activeGroup ()
const MovableGroup & activeGroup () const
void continueAlignment ()
void clear ()
bool isEmpty () const
int count () const
const MovableGroup & getGroup (int i) const
Base::BoundBox3d getBoundingBox () const
Protected Member Functions
void removeActiveGroup ()
Detailed Description
The MovableGroupModel class keeps an array of movable groups.
Author
Werner Mayer
Definition at line 161 of file ManualAlignment.h.
Constructor & Destructor Documentation
MovableGroupModel()
MovableGroupModel::MovableGroupModel () default
~MovableGroupModel()
MovableGroupModel::~MovableGroupModel () default
Member Function Documentation
activeGroup() [1/2]
const MovableGroup & MovableGroupModel::activeGroup ()
Definition at line 286 of file ManualAlignment.cpp.
Referenced by Gui::ManualAlignment::align(), Gui::ManualAlignment::applyPickedProbe(), Gui::ManualAlignment::canAlign(), Gui::ManualAlignment::continueAlignment(), Gui::ManualAlignment::onClear(), Gui::ManualAlignment::onRemoveLastPointMoveable(), Gui::ManualAlignment::reset(), Gui::ManualAlignment::showInstructions(), and Gui::ManualAlignment::slotDeletedObject().
activeGroup() [2/2]
const MovableGroup& Gui::MovableGroupModel::activeGroup () const
addGroup()
void MovableGroupModel::addGroup (const MovableGroup & grp)
Definition at line 270 of file ManualAlignment.cpp.
References toolbit-attributes::grp.
addGroups()
void MovableGroupModel::addGroups (const std::map< int, MovableGroup > & grps)
Definition at line 275 of file ManualAlignment.cpp.
References toolbit-attributes::grp.
Referenced by StdCmdAlignment::activated().
clear()
void MovableGroupModel::clear ()
Definition at line 308 of file ManualAlignment.cpp.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__(), Gui::ManualAlignment::clearAll(), and Gui::ManualAlignment::reset().
continueAlignment()
void MovableGroupModel::continueAlignment ()
Definition at line 302 of file ManualAlignment.cpp.
References isEmpty(), and removeActiveGroup().
Referenced by Gui::ManualAlignment::align().
count()
int MovableGroupModel::count () const
Definition at line 318 of file ManualAlignment.cpp.
Referenced by getGroup(), and src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::set_status_filter().
getBoundingBox()
Base::BoundBox3d MovableGroupModel::getBoundingBox () const
Definition at line 330 of file ManualAlignment.cpp.
References MengerSponge::box.
getGroup()
const MovableGroup & MovableGroupModel::getGroup (int i) const
Definition at line 323 of file ManualAlignment.cpp.
References count(), and SplineSurface::i.
isEmpty()
bool MovableGroupModel::isEmpty () const
Definition at line 313 of file ManualAlignment.cpp.
Referenced by continueAlignment(), Gui::ManualAlignment::continueAlignment(), Gui::ManualAlignment::reset(), and Gui::ManualAlignment::startAlignment().
removeActiveGroup()
void MovableGroupModel::removeActiveGroup () protected
Definition at line 281 of file ManualAlignment.cpp.
Referenced by continueAlignment().
The documentation for this class was generated from the following files:
ManualAlignment.h
ManualAlignment.cpp