FreeCAD: TechDrawGui::TaskDetail Class Reference
TechDrawGui::TaskDetail Class Reference
#include <TaskDetail.h>
Public Slots
void onDraggerClicked (bool clicked)
void onHighlightMoved (QPointF dragEnd)
void onXEdit ()
void onYEdit ()
void onRadiusEdit ()
void onScaleTypeEdit ()
void onScaleEdit ()
void onReferenceEdit ()
Public Member Functions
TaskDetail (TechDraw::DrawViewPart *baseFeat)
TaskDetail (TechDraw::DrawViewDetail *detailFeat)
~TaskDetail () override=default
virtual bool accept ()
virtual bool reject ()
void updateTask ()
void saveButtons (QPushButton *btnOK, QPushButton *btnCancel)
void enableTaskButtons (bool button)
Protected Member Functions
void changeEvent (QEvent *event) override
void startDragger ()
void createDetail ()
void updateDetail ()
void editByHighlight ()
void blockButtons (bool isBlocked)
void setUiFromFeat ()
void updateUi (QPointF pos)
void enableInputFields (bool isEnabled)
void saveDetailState ()
void restoreDetailState ()
QPointF getAnchorScene ()
TechDraw::DrawViewPart * getBaseFeat ()
TechDraw::DrawViewDetail * getDetailFeat ()
Detailed Description
Definition at line 51 of file TaskDetail.h.
Constructor & Destructor Documentation
TaskDetail() [1/2]
TaskDetail::TaskDetail (TechDraw::DrawViewPart * baseFeat) explicit
Definition at line 56 of file TaskDetail.cpp.
References draftgeoutils.intersections::connect(), Base::Console(), createDetail(), Base::ConsoleSingleton::Error(), TechDraw::DrawView::findParentPage(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), App::DocumentObject::getNameInDocument(), TechDrawGui::ViewProviderPage::getQGSPage(), Gui::Document::getViewProvider(), Gui::Application::Instance, onDraggerClicked(), onHighlightMoved(), onRadiusEdit(), onReferenceEdit(), onScaleEdit(), onScaleTypeEdit(), onXEdit(), onYEdit(), TechDrawGui::QGIGhostHighlight::positionChange(), and setUiFromFeat().
TaskDetail() [2/2]
TaskDetail::TaskDetail (TechDraw::DrawViewDetail * detailFeat) explicit
Definition at line 126 of file TaskDetail.cpp.
References TechDraw::DrawViewDetail::BaseView, draftgeoutils.intersections::connect(), Base::Console(), Base::ConsoleSingleton::Error(), TechDraw::DrawView::findParentPage(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), App::DocumentObject::getNameInDocument(), TechDrawGui::ViewProviderPage::getQGSPage(), App::PropertyLink::getValue(), Gui::Document::getViewProvider(), Gui::Application::Instance, onDraggerClicked(), onHighlightMoved(), onRadiusEdit(), onReferenceEdit(), onScaleEdit(), onScaleTypeEdit(), onXEdit(), onYEdit(), TechDrawGui::QGIGhostHighlight::positionChange(), saveDetailState(), and setUiFromFeat().
~TaskDetail()
TechDrawGui::TaskDetail::~TaskDetail () override default
Member Function Documentation
accept()
bool TaskDetail::accept () virtual
Definition at line 582 of file TaskDetail.cpp.
References toolbit-attributes::doc, doCommand, getBaseFeat(), getDetailFeat(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::Command::Gui, Gui::Application::Instance, and TechDraw::DrawView::requestPaint().
Referenced by TechDrawGui::TaskDlgDetail::accept().
blockButtons()
void TechDrawGui::TaskDetail::blockButtons (bool isBlocked) protected
changeEvent()
void TaskDetail::changeEvent (QEvent * event) override protected
Definition at line 212 of file TaskDetail.cpp.
References SCL.SimpleDataTypes::e.
createDetail()
void TaskDetail::createDetail () protected
Definition at line 431 of file TaskDetail.cpp.
References Gui::Command::commitCommand(), doCommand, getBaseFeat(), App::DocumentObject::getDocument(), App::Document::getObject(), App::Document::getUniqueObjectName(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, TechDraw::DrawView::requestPaint(), App::PropertyLinkList::setValues(), DrawingExample::Source, TechDraw::DrawViewPart::Source, and Gui::Command::updateActive().
Referenced by TaskDetail().
editByHighlight()
void TaskDetail::editByHighlight () protected
Definition at line 365 of file TaskDetail.cpp.
References Base::Console(), TechDrawGui::QGIHighlight::draw(), Base::ConsoleSingleton::Error(), getAnchorScene(), getBaseFeat(), TechDrawGui::ViewProviderPage::getQGSPage(), TechDraw::DrawView::getScale(), and TechDrawGui::QGIGhostHighlight::setRadius().
Referenced by onDraggerClicked().
enableInputFields()
void TaskDetail::enableInputFields (bool isEnabled) protected
Definition at line 289 of file TaskDetail.cpp.
Referenced by onDraggerClicked(), and onHighlightMoved().
enableTaskButtons()
void TaskDetail::enableTaskButtons (bool button)
Definition at line 424 of file TaskDetail.cpp.
getAnchorScene()
QPointF TaskDetail::getAnchorScene () protected
Definition at line 504 of file TaskDetail.cpp.
References TechDraw::DrawViewDetail::AnchorPoint, Base::Console(), getBaseFeat(), getDetailFeat(), TechDraw::DrawProjGroupItem::getPGroup(), TechDraw::DrawProjGroupItem::getScale(), TechDraw::DrawView::getScale(), App::PropertyQuantity::getValue(), App::PropertyVector::getValue(), TechDrawGui::Rez::guiX(), Base::ConsoleSingleton::Message(), draftfunctions.scale::scale(), MovieTool::x, TechDraw::DrawView::X, Base::Vector3< float_type >::x, MovieTool::y, TechDraw::DrawView::Y, and Base::Vector3< float_type >::y.
Referenced by editByHighlight().
getBaseFeat()
DrawViewPart * TaskDetail::getBaseFeat () protected
Definition at line 542 of file TaskDetail.cpp.
References App::Document::getObject(), and Path.Op.Surface::msg.
Referenced by accept(), createDetail(), editByHighlight(), getAnchorScene(), onHighlightMoved(), reject(), setUiFromFeat(), and updateDetail().
getDetailFeat()
DrawViewDetail * TaskDetail::getDetailFeat () protected
Definition at line 561 of file TaskDetail.cpp.
References App::DocumentObject::getDocument(), App::Document::getObject(), and Path.Op.Surface::msg.
Referenced by accept(), getAnchorScene(), onScaleTypeEdit(), reject(), restoreDetailState(), saveDetailState(), setUiFromFeat(), and updateDetail().
onDraggerClicked
void TaskDetail::onDraggerClicked (bool clicked) slot
Definition at line 356 of file TaskDetail.cpp.
References editByHighlight(), and enableInputFields().
Referenced by TaskDetail().
onHighlightMoved
void TaskDetail::onHighlightMoved (QPointF dragEnd) slot
Definition at line 383 of file TaskDetail.cpp.
References TechDrawGui::Rez::appX(), Base::Console(), enableInputFields(), getBaseFeat(), TechDraw::DrawProjGroupItem::getPGroup(), TechDraw::DrawView::getScale(), App::PropertyQuantity::getValue(), TechDrawGui::Rez::guiX(), Base::ConsoleSingleton::Message(), updateDetail(), updateUi(), MovieTool::x, DrawingExample::X, TechDraw::DrawView::X, MovieTool::y, DrawingExample::Y, and TechDraw::DrawView::Y.
Referenced by TaskDetail().
onRadiusEdit
void TaskDetail::onRadiusEdit () slot
Definition at line 309 of file TaskDetail.cpp.
References updateDetail().
Referenced by TaskDetail().
onReferenceEdit
void TaskDetail::onReferenceEdit () slot
Definition at line 351 of file TaskDetail.cpp.
References updateDetail().
Referenced by TaskDetail().
onScaleEdit
void TaskDetail::onScaleEdit () slot
Definition at line 346 of file TaskDetail.cpp.
References updateDetail().
Referenced by TaskDetail().
onScaleTypeEdit
void TaskDetail::onScaleTypeEdit () slot
Definition at line 314 of file TaskDetail.cpp.
References getDetailFeat(), App::PropertyFloat::getValue(), TechDraw::DrawView::Scale, TechDraw::DrawPage::Scale, TechDraw::DrawView::ScaleType, App::PropertyEnumeration::setValue(), App::PropertyFloat::setValue(), and updateDetail().
Referenced by TaskDetail().
onXEdit
void TaskDetail::onXEdit () slot
Definition at line 299 of file TaskDetail.cpp.
References updateDetail().
Referenced by TaskDetail().
onYEdit
void TaskDetail::onYEdit () slot
Definition at line 304 of file TaskDetail.cpp.
References updateDetail().
Referenced by TaskDetail().
reject()
bool TaskDetail::reject () virtual
Definition at line 598 of file TaskDetail.cpp.
References CREATEMODE(), toolbit-attributes::doc, doCommand, getBaseFeat(), getDetailFeat(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::Command::Gui, Gui::Application::Instance, App::DocumentObject::recomputeFeature(), TechDraw::DrawView::requestPaint(), and restoreDetailState().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and TechDrawGui::TaskDlgDetail::reject().
restoreDetailState()
void TaskDetail::restoreDetailState () protected
Definition at line 229 of file TaskDetail.cpp.
References TechDraw::DrawViewDetail::AnchorPoint, getDetailFeat(), TechDraw::DrawViewDetail::Radius, App::PropertyVector::setValue(), and App::PropertyFloat::setValue().
Referenced by reject().
saveButtons()
void TaskDetail::saveButtons (QPushButton * btnOK, QPushButton * btnCancel)
Definition at line 417 of file TaskDetail.cpp.
Referenced by TechDrawGui::TaskDlgDetail::modifyStandardButtons().
saveDetailState()
void TaskDetail::saveDetailState () protected
Definition at line 220 of file TaskDetail.cpp.
References TechDraw::DrawViewDetail::AnchorPoint, getDetailFeat(), App::PropertyVector::getValue(), App::PropertyFloat::getValue(), and TechDraw::DrawViewDetail::Radius.
Referenced by TaskDetail().
setUiFromFeat()
void TaskDetail::setUiFromFeat () protected
Definition at line 239 of file TaskDetail.cpp.
References TechDraw::DrawViewDetail::AnchorPoint, getBaseFeat(), Base::UnitsApi::getDecimals(), getDetailFeat(), App::DocumentObject::getNameInDocument(), App::PropertyVector::getValue(), App::PropertyEnumeration::getValue(), App::PropertyFloat::getValue(), App::PropertyString::getValue(), App::DocumentObject::Label, Base::Unit::Length, TechDraw::DrawViewDetail::Radius, TechDraw::DrawViewDetail::Reference, TechDraw::DrawView::Scale, TechDraw::DrawView::ScaleType, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by TaskDetail().
startDragger()
void TechDrawGui::TaskDetail::startDragger () protected
updateDetail()
void TaskDetail::updateDetail () protected
Definition at line 472 of file TaskDetail.cpp.
References TechDraw::DrawViewDetail::AnchorPoint, Gui::Command::commitCommand(), Base::Console(), Base::ConsoleSingleton::Error(), getBaseFeat(), getDetailFeat(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, TechDraw::DrawViewDetail::Radius, App::DocumentObject::recomputeFeature(), TechDraw::DrawViewDetail::Reference, TechDraw::DrawView::requestPaint(), TechDraw::DrawView::Scale, App::PropertyVector::setValue(), App::PropertyFloat::setValue(), App::PropertyString::setValue(), Gui::Command::updateActive(), MovieTool::x, and MovieTool::y.
Referenced by onHighlightMoved(), onRadiusEdit(), onReferenceEdit(), onScaleEdit(), onScaleTypeEdit(), onXEdit(), and onYEdit().
updateTask()
void TaskDetail::updateTask ()
Definition at line 205 of file TaskDetail.cpp.
updateUi()
void TaskDetail::updateUi (QPointF pos) protected
Definition at line 283 of file TaskDetail.cpp.
References RobotExample::pos.
Referenced by onHighlightMoved().
The documentation for this class was generated from the following files:
TaskDetail.h
TaskDetail.cpp