FreeCAD: Part::GeometryMigrationExtension Class Reference
Part::GeometryMigrationExtension Class Reference
#include <GeometryMigrationExtension.h>
Public Types
enum MigrationType {
None = 0, Construction = 1, GeometryId = 2, ExternalReference = 3,
NumMigrationType
}
Public Member Functions
GeometryMigrationExtension ()=default
~GeometryMigrationExtension () override=default
std::unique_ptr< Part::GeometryExtension > copy () const override
PyObject * getPyObject () override
virtual bool getConstruction () const
virtual void setConstruction (bool construction)
long getId () const
void setId (long id)
const std::string & getRef () const
int getRefIndex () const
unsigned long getFlags () const
void setReference (const char *ref, int index, unsigned long flags)
virtual bool testMigrationType (int flag) const
virtual void setMigrationType (int flag, bool v=true)
Public Member Functions inherited from Part::GeometryExtension
~GeometryExtension () override=default
PyObject * copyPyObject () const
void setName (const std::string &str)
const std::string & getName () const
virtual void notifyAttachment (Part::Geometry *)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
void copyAttributes (Part::GeometryExtension *cpy) const override
Protected Member Functions inherited from Part::GeometryExtension
GeometryExtension ()
GeometryExtension (const GeometryExtension &obj)=default
GeometryExtension & operator= (const GeometryExtension &obj)=default
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 61 of file GeometryMigrationExtension.h.
Member Enumeration Documentation
MigrationType
enum Part::GeometryMigrationExtension::MigrationType
Enumerator
None
Construction
GeometryId
ExternalReference
NumMigrationType
Definition at line 89 of file GeometryMigrationExtension.h.
Constructor & Destructor Documentation
GeometryMigrationExtension()
Part::GeometryMigrationExtension::GeometryMigrationExtension () default
~GeometryMigrationExtension()
Part::GeometryMigrationExtension::~GeometryMigrationExtension () override default
Member Function Documentation
copy()
std::unique_ptr< Part::GeometryExtension > GeometryMigrationExtension::copy () const override virtual
Implements Part::GeometryExtension.
Definition at line 49 of file GeometryMigrationExtension.cpp.
References copyAttributes(), and Path.Post.scripts.opensbp_post::move().
copyAttributes()
void GeometryMigrationExtension::copyAttributes (Part::GeometryExtension * cpy) const override protected virtual
Reimplemented from Part::GeometryExtension.
Definition at line 38 of file GeometryMigrationExtension.cpp.
References Part::GeometryExtension::copyAttributes().
Referenced by copy().
getConstruction()
virtual bool Part::GeometryMigrationExtension::getConstruction () const inline virtual
Definition at line 105 of file GeometryMigrationExtension.h.
getFlags()
unsigned long Part::GeometryMigrationExtension::getFlags () const inline
Definition at line 123 of file GeometryMigrationExtension.h.
getId()
long Part::GeometryMigrationExtension::getId () const inline
Definition at line 112 of file GeometryMigrationExtension.h.
getPyObject()
PyObject * GeometryMigrationExtension::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
Definition at line 62 of file GeometryMigrationExtension.cpp.
References THROWM.
getRef()
const std::string& Part::GeometryMigrationExtension::getRef () const inline
Definition at line 119 of file GeometryMigrationExtension.h.
getRefIndex()
int Part::GeometryMigrationExtension::getRefIndex () const inline
Definition at line 121 of file GeometryMigrationExtension.h.
setConstruction()
virtual void Part::GeometryMigrationExtension::setConstruction (bool construction) inline virtual
Definition at line 107 of file GeometryMigrationExtension.h.
setId()
void Part::GeometryMigrationExtension::setId (long id) inline
Definition at line 114 of file GeometryMigrationExtension.h.
setMigrationType()
virtual void Part::GeometryMigrationExtension::setMigrationType (int flag, bool v = true) inline virtual
Definition at line 133 of file GeometryMigrationExtension.h.
setReference()
void Part::GeometryMigrationExtension::setReference (const char * ref, int index, unsigned long flags) inline
Definition at line 125 of file GeometryMigrationExtension.h.
testMigrationType()
virtual bool Part::GeometryMigrationExtension::testMigrationType (int flag) const inline virtual
Definition at line 132 of file GeometryMigrationExtension.h.
The documentation for this class was generated from the following files:
GeometryMigrationExtension.h
GeometryMigrationExtension.cpp