FreeCAD: GCS::SolverReportingManager Class Reference
GCS::SolverReportingManager Class Reference
Public Member Functions
SolverReportingManager (SolverReportingManager const &)=delete
SolverReportingManager (SolverReportingManager &&)=delete
SolverReportingManager & operator= (SolverReportingManager const &)=delete
SolverReportingManager & operator= (SolverReportingManager &&)=delete
void LogString (const std::string &str)
void LogToConsole (const std::string &str)
void LogToFile (const std::string &str)
void LogQRSystemInformation (const System &system, int paramsNum=0, int constrNum=0, int rank=0)
void LogGroupOfConstraints (const std::string &str, std::vector< std::vector< Constraint * >> constraintgroups)
void LogSetOfConstraints (const std::string &str, std::set< Constraint * > constraintset)
void LogGroupOfParameters (const std::string &str, std::vector< std::vector< double * >> parametergroups)
void LogMatrix (const std::string str, Eigen::MatrixXd matrix)
void LogMatrix (const std::string str, MatrixIndexType matrix)
Static Public Member Functions
static SolverReportingManager & Manager ()
Detailed Description
Definition at line 222 of file GCS.cpp.
Constructor & Destructor Documentation
SolverReportingManager() [1/2]
GCS::SolverReportingManager::SolverReportingManager (SolverReportingManager const &) delete
SolverReportingManager() [2/2]
GCS::SolverReportingManager::SolverReportingManager (SolverReportingManager &&) delete
Member Function Documentation
LogGroupOfConstraints()
void GCS::SolverReportingManager::LogGroupOfConstraints (const std::string & str, std::vector< std::vector< Constraint * >> constraintgroups)
Definition at line 368 of file GCS.cpp.
References SCL.SimpleDataTypes::c, toolbit-attributes::group, LogString(), and Path.Post.scripts.refactored_centroid_post::str.
LogGroupOfParameters()
void GCS::SolverReportingManager::LogGroupOfParameters (const std::string & str, std::vector< std::vector< double * >> parametergroups)
Definition at line 405 of file GCS.cpp.
References SplineSurface::i, LogString(), buildPsets::p, and Path.Post.scripts.refactored_centroid_post::str.
LogMatrix() [1/2]
void GCS::SolverReportingManager::LogMatrix (const std::string str, Eigen::MatrixXd matrix)
LogMatrix() [2/2]
void GCS::SolverReportingManager::LogMatrix (const std::string str, MatrixIndexType matrix)
LogQRSystemInformation()
void GCS::SolverReportingManager::LogQRSystemInformation (const System & system, int paramsNum = 0, int constrNum = 0, int rank = 0)
Definition at line 331 of file GCS.cpp.
References GCS::EigenDenseQR, GCS::EigenSparseQR, LogString(), GCS::System::qrAlgorithm, and GCS::System::qrpivotThreshold.
LogSetOfConstraints()
void GCS::SolverReportingManager::LogSetOfConstraints (const std::string & str, std::set< Constraint * > constraintset)
Definition at line 389 of file GCS.cpp.
References SCL.SimpleDataTypes::c, LogString(), and Path.Post.scripts.refactored_centroid_post::str.
LogString()
void GCS::SolverReportingManager::LogString (const std::string & str) inline
Definition at line 322 of file GCS.cpp.
References LogToConsole(), LogToFile(), and Path.Post.scripts.refactored_centroid_post::str.
Referenced by LogGroupOfConstraints(), LogGroupOfParameters(), LogQRSystemInformation(), and LogSetOfConstraints().
LogToConsole()
void GCS::SolverReportingManager::LogToConsole (const std::string & str) inline
Definition at line 303 of file GCS.cpp.
References Base::Console(), Base::ConsoleSingleton::Log(), and Path.Post.scripts.refactored_centroid_post::str.
Referenced by LogString(), and LogToFile().
LogToFile()
void GCS::SolverReportingManager::LogToFile (const std::string & str) inline
Definition at line 308 of file GCS.cpp.
References LogToConsole(), and Path.Post.scripts.refactored_centroid_post::str.
Referenced by GCS::System::diagnose(), and LogString().
Manager()
SolverReportingManager & GCS::SolverReportingManager::Manager () static
Definition at line 296 of file GCS.cpp.
Referenced by GCS::System::diagnose().
operator=() [1/2]
SolverReportingManager& GCS::SolverReportingManager::operator= (SolverReportingManager &&) delete
operator=() [2/2]
SolverReportingManager& GCS::SolverReportingManager::operator= (SolverReportingManager const &) delete
The documentation for this class was generated from the following file:
GCS.cpp