FreeCAD: AppStartGui.cpp File Reference
AppStartGui.cpp File Reference
#include "PreCompiled.h"
#include <QString>
#include <QTimer>
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/PyObjectBase.h>
#include <Gui/Language/Translator.h>
#include <Gui/Command.h>
#include <Gui/MainWindow.h>
#include <gsl/pointers>
#include "Manipulator.h"
#include "StartView.h"
Classes
class StartGui::Module
class StartGui::StartLauncher
Namespaces
StartGui
Functions
void loadStartResource ()
PyObject * StartGui::initModule ()
PyMOD_INIT_FUNC (StartGui)
Function Documentation
loadStartResource()
void loadStartResource ()
Definition at line 43 of file AppStartGui.cpp.
References Gui::Translator::instance(), and Gui::Translator::refresh().
Referenced by PyMOD_INIT_FUNC().
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (StartGui)
Definition at line 115 of file AppStartGui.cpp.
References Base::Console(), StartGui::initModule(), Gui::WorkbenchManipulator::installManipulator(), loadStartResource(), Base::ConsoleSingleton::Log(), mod, and PyMOD_Return.