FreeCAD: TechDrawGui::TaskLeaderLine Class Reference
TechDrawGui::TaskLeaderLine Class Reference
#include <TaskLeaderLine.h>
Public Slots
void onTrackerClicked (bool clicked)
void onCancelEditClicked (bool clicked)
void onTrackerFinished (std::vector< QPointF > pts, TechDrawGui::QGIView *qgParent)
Public Member Functions
TaskLeaderLine (TechDraw::DrawView *baseFeat, TechDraw::DrawPage *page)
TaskLeaderLine (TechDrawGui::ViewProviderLeader *leadVP)
~TaskLeaderLine () override=default
virtual bool accept ()
virtual bool reject ()
virtual void setCreateMode (bool mode)
virtual bool getCreateMode ()
void updateTask ()
void saveButtons (QPushButton *btnOK, QPushButton *btnCancel)
void enableTaskButtons (bool enable)
void recomputeFeature ()
Protected Slots
void onPointEditComplete ()
point edit session completed. reset ui to initial state.
Protected Member Functions
std::vector< Base::Vector3d > scenePointsToDeltas (std::vector< QPointF > pts)
void changeEvent (QEvent *event) override
void startTracker ()
void removeTracker ()
void abandonEditSession ()
void createLeaderFeature (std::vector< Base::Vector3d > sceneDeltas)
void updateLeaderFeature ()
void commonFeatureUpdate ()
void removeFeature ()
void setUiPrimary ()
void setUiEdit ()
void enableVPUi (bool enable)
void setEditCursor (const QCursor &cursor)
QGIView * findParentQGIV ()
void saveState ()
void restoreState ()
void dumpTrackerPoints (std::vector< Base::Vector3d > &tPoints) const
Detailed Description
Definition at line 53 of file TaskLeaderLine.h.
Constructor & Destructor Documentation
TaskLeaderLine() [1/2]
TaskLeaderLine::TaskLeaderLine (TechDraw::DrawView * baseFeat, TechDraw::DrawPage * page)
Definition at line 138 of file TaskLeaderLine.cpp.
References draftgeoutils.intersections::connect(), TechDrawGui::QGSPage::findQViewForDocObj(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), TechDrawGui::ViewProviderPage::getMDIViewPage(), TechDrawGui::ViewProviderPage::getQGSPage(), Gui::Document::getViewProvider(), Gui::Application::Instance, TechDraw::Line, Gui::None, onCancelEditClicked(), onTrackerClicked(), and setUiPrimary().
TaskLeaderLine() [2/2]
TaskLeaderLine::TaskLeaderLine (TechDrawGui::ViewProviderLeader * leadVP) explicit
Definition at line 66 of file TaskLeaderLine.cpp.
References draftgeoutils.intersections::connect(), Base::Console(), Base::ConsoleSingleton::Error(), TechDraw::DrawView::findParentPage(), TechDrawGui::QGSPage::findQViewForDocObj(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), TechDrawGui::ViewProviderPage::getMDIViewPage(), TechDrawGui::ViewProviderPage::getQGSPage(), App::PropertyQuantity::getValue(), App::PropertyLink::getValue(), Gui::Document::getViewProvider(), TechDrawGui::Rez::guiX(), Gui::Application::Instance, Base::BaseClass::isDerivedFrom(), TechDraw::DrawLeaderLine::LeaderParent, TechDraw::Line, onCancelEditClicked(), onTrackerClicked(), saveState(), setUiEdit(), TechDraw::DrawView::X, and TechDraw::DrawView::Y.
~TaskLeaderLine()
TechDrawGui::TaskLeaderLine::~TaskLeaderLine () override default
Member Function Documentation
abandonEditSession()
void TaskLeaderLine::abandonEditSession () protected
give up on the current point editing session. reset the ui so we are in a state to start editing points again. leave the existing tracker instance in place.
Definition at line 768 of file TaskLeaderLine.cpp.
References TechDrawGui::QGILeaderLine::abandonEdit(), TechDrawGui::EDIT, enableTaskButtons(), Gui::getMainWindow(), Path.Op.Surface::msg, setEditCursor(), and Gui::MainWindow::showMessage().
Referenced by accept(), onCancelEditClicked(), and reject().
accept()
bool TaskLeaderLine::accept () virtual
Definition at line 804 of file TaskLeaderLine.cpp.
References abandonEditSession(), createLeaderFeature(), toolbit-attributes::doc, doCommand, getCreateMode(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), TechDrawGui::ViewProviderPage::getMDIViewPage(), Gui::Command::Gui, Gui::Application::Instance, Gui::None, removeTracker(), and updateLeaderFeature().
Referenced by TechDrawGui::TaskDlgLeaderLine::accept().
changeEvent()
void TaskLeaderLine::changeEvent (QEvent * event) override protected
Definition at line 209 of file TaskLeaderLine.cpp.
commonFeatureUpdate()
void TaskLeaderLine::commonFeatureUpdate () protected
Definition at line 451 of file TaskLeaderLine.cpp.
References TechDraw::DrawLeaderLine::EndSymbol, App::PropertyEnumeration::setValue(), and TechDraw::DrawLeaderLine::StartSymbol.
Referenced by createLeaderFeature(), and updateLeaderFeature().
createLeaderFeature()
void TaskLeaderLine::createLeaderFeature (std::vector< Base::Vector3d > sceneDeltas) protected
sceneDeltas are vector from first picked scene point (0,0) to the ith point. sceneDeltas are in Qt scene coords (Rez and inverted Y).
Definition at line 338 of file TaskLeaderLine.cpp.
References TechDrawGui::Rez::appX(), Gui::Command::commitCommand(), commonFeatureUpdate(), doCommand, Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::Document::getObject(), App::Document::getUniqueObjectName(), App::PropertyQuantity::getValue(), TechDrawGui::QGIView::getViewProvider(), TechDraw::DrawUtil::invertY(), Base::BaseClass::isDerivedFrom(), TechDraw::DrawLeaderLine::makeCanonicalPointsInverted(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, TechDraw::DrawView::requestPaint(), TechDraw::DrawView::Rotation, TechDraw::DrawView::setPosition(), App::Color::setValue(), App::PropertyListsT< T, ListT, ParentT >::setValues(), Base::toRadians(), App::DocumentObject::touch(), Gui::Command::updateActive(), TechDraw::DrawLeaderLine::WayPoints, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by accept().
dumpTrackerPoints()
void TaskLeaderLine::dumpTrackerPoints (std::vector< Base::Vector3d > & tPoints) const protected
Definition at line 421 of file TaskLeaderLine.cpp.
References Base::Console(), TechDraw::DrawUtil::formatVector(), and Base::ConsoleSingleton::Message().
enableTaskButtons()
void TaskLeaderLine::enableTaskButtons (bool enable)
Definition at line 796 of file TaskLeaderLine.cpp.
Referenced by abandonEditSession(), onCancelEditClicked(), onPointEditComplete(), onTrackerClicked(), and onTrackerFinished().
enableVPUi()
void TaskLeaderLine::enableVPUi (bool enable) protected
Definition at line 251 of file TaskLeaderLine.cpp.
Referenced by setUiEdit(), and setUiPrimary().
findParentQGIV()
QGIView * TaskLeaderLine::findParentQGIV () protected
Definition at line 696 of file TaskLeaderLine.cpp.
References TechDrawGui::ViewProviderDrawingView::getQView(), and TechDrawGui::QGIView::getViewProvider().
getCreateMode()
virtual bool TechDrawGui::TaskLeaderLine::getCreateMode () inline virtual
Definition at line 67 of file TaskLeaderLine.h.
Referenced by accept(), onTrackerClicked(), and reject().
onCancelEditClicked
void TaskLeaderLine::onCancelEditClicked (bool clicked) slot
Definition at line 677 of file TaskLeaderLine.cpp.
References abandonEditSession(), TechDrawGui::EDIT, enableTaskButtons(), TechDraw::DrawView::requestPaint(), and setEditCursor().
Referenced by TaskLeaderLine().
onPointEditComplete
void TaskLeaderLine::onPointEditComplete () protected slot
point edit session completed. reset ui to initial state.
Definition at line 753 of file TaskLeaderLine.cpp.
References TechDrawGui::EDIT, and enableTaskButtons().
Referenced by onTrackerClicked().
onTrackerClicked
void TaskLeaderLine::onTrackerClicked (bool clicked) slot
Definition at line 487 of file TaskLeaderLine.cpp.
References TechDrawGui::QGILeaderLine::closeEdit(), draftgeoutils.intersections::connect(), Base::Console(), TechDrawGui::QGILeaderLine::editComplete(), enableTaskButtons(), Base::ConsoleSingleton::Error(), TechDrawGui::QGSPage::findQViewForDocObj(), getCreateMode(), Gui::getMainWindow(), TechDrawGui::ViewProviderPage::getMDIViewPage(), TechDrawGui::ViewProviderPage::getQGSPage(), TechDraw::DrawLeaderLine::getScaledAndRotatedPoints(), TechDraw::Line, Base::ConsoleSingleton::Message(), MessageDisplayTime, Path.Op.Surface::msg, onPointEditComplete(), TechDrawGui::PICK, TechDrawGui::SAVE, setEditCursor(), Gui::MainWindow::showMessage(), startTracker(), TechDrawGui::QGTracker::terminateDrawing(), and TechDrawGui::DrawGuiUtil::toSceneCoords().
Referenced by TaskLeaderLine().
onTrackerFinished
void TaskLeaderLine::onTrackerFinished (std::vector< QPointF > pts, TechDrawGui::QGIView * qgParent) slot
Definition at line 623 of file TaskLeaderLine.cpp.
References Base::Console(), enableTaskButtons(), Base::ConsoleSingleton::Error(), Gui::getMainWindow(), TechDrawGui::QGIView::getScale(), Base::ConsoleSingleton::Message(), MessageDisplayTime, Path.Op.Surface::msg, draftfunctions.scale::scale(), scenePointsToDeltas(), setEditCursor(), Gui::MainWindow::showMessage(), and TechDrawGui::QGTracker::sleep().
Referenced by startTracker().
recomputeFeature()
void TaskLeaderLine::recomputeFeature ()
Definition at line 295 of file TaskLeaderLine.cpp.
References App::DocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), and App::Document::recomputeFeature().
reject()
bool TaskLeaderLine::reject () virtual
Definition at line 836 of file TaskLeaderLine.cpp.
References abandonEditSession(), toolbit-attributes::doc, doCommand, getCreateMode(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), TechDrawGui::ViewProviderPage::getMDIViewPage(), Gui::Command::Gui, Gui::Application::Instance, Gui::None, removeFeature(), removeTracker(), and restoreState().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and TechDrawGui::TaskDlgLeaderLine::reject().
removeFeature()
void TaskLeaderLine::removeFeature () protected
Definition at line 459 of file TaskLeaderLine.cpp.
References Gui::Application::activeDocument(), Base::Console(), doCommand, App::DocumentObject::getNameInDocument(), Gui::Document::getUndoVector(), Gui::Command::Gui, Gui::Command::hasPendingCommand(), Gui::Application::Instance, Base::ConsoleSingleton::Message(), and Gui::Document::undo().
Referenced by reject().
removeTracker()
void TaskLeaderLine::removeTracker () protected
Definition at line 664 of file TaskLeaderLine.cpp.
References TechDrawGui::ViewProviderPage::getQGSPage().
Referenced by accept(), and reject().
restoreState()
void TaskLeaderLine::restoreState () protected
Definition at line 193 of file TaskLeaderLine.cpp.
References App::PropertyQuantity::setValue(), App::PropertyListsT< T, ListT, ParentT >::setValues(), TechDraw::DrawLeaderLine::WayPoints, TechDraw::DrawView::X, and TechDraw::DrawView::Y.
Referenced by reject().
saveButtons()
void TaskLeaderLine::saveButtons (QPushButton * btnOK, QPushButton * btnCancel)
Definition at line 789 of file TaskLeaderLine.cpp.
Referenced by TechDrawGui::TaskDlgLeaderLine::modifyStandardButtons().
saveState()
void TaskLeaderLine::saveState () protected
Definition at line 184 of file TaskLeaderLine.cpp.
References App::PropertyQuantity::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), TechDraw::DrawLeaderLine::WayPoints, TechDraw::DrawView::X, and TechDraw::DrawView::Y.
Referenced by TaskLeaderLine().
scenePointsToDeltas()
std::vector< Base::Vector3d > TaskLeaderLine::scenePointsToDeltas (std::vector< QPointF > pts) protected
Definition at line 723 of file TaskLeaderLine.cpp.
References App::PropertyQuantity::getValue(), TechDraw::DrawUtil::invertY(), result, TechDraw::DrawView::Rotation, Base::toRadians(), and TechDraw::DrawUtil::toVector3d().
Referenced by onTrackerFinished().
setCreateMode()
virtual void TechDrawGui::TaskLeaderLine::setCreateMode (bool mode) inline virtual
Definition at line 66 of file TaskLeaderLine.h.
setEditCursor()
void TaskLeaderLine::setEditCursor (const QCursor & cursor) protected
Definition at line 711 of file TaskLeaderLine.cpp.
References TechDrawGui::QGSPage::findQViewForDocObj(), and TechDrawGui::ViewProviderPage::getQGSPage().
Referenced by abandonEditSession(), onCancelEditClicked(), onTrackerClicked(), onTrackerFinished(), and startTracker().
setUiEdit()
void TaskLeaderLine::setUiEdit () protected
Definition at line 258 of file TaskLeaderLine.cpp.
References App::Color::asValue(), TechDrawGui::ViewProviderLeader::Color, draftgeoutils.intersections::connect(), enableVPUi(), TechDraw::DrawLeaderLine::EndSymbol, TechDrawGui::ViewProviderPage::getMDIViewPage(), App::DocumentObject::getNameInDocument(), App::PropertyQuantity::getValue(), App::PropertyEnumeration::getValue(), App::PropertyLink::getValue(), App::PropertyColor::getValue(), TechDraw::DrawLeaderLine::LeaderParent, TechDrawGui::ViewProviderLeader::LineStyle, TechDrawGui::ViewProviderLeader::LineWidth, TechDrawGui::DrawGuiUtil::loadArrowBox(), and TechDraw::DrawLeaderLine::StartSymbol.
Referenced by TaskLeaderLine().
setUiPrimary()
void TaskLeaderLine::setUiPrimary () protected
Definition at line 216 of file TaskLeaderLine.cpp.
References TechDrawGui::PreferencesGui::dimArrowStyle(), enableVPUi(), TechDraw::LineGroup::getDefaultWidth(), TechDrawGui::ViewProviderPage::getMDIViewPage(), App::DocumentObject::getNameInDocument(), TechDrawGui::PreferencesGui::leaderColor(), Base::Unit::Length, TechDrawGui::DrawGuiUtil::loadArrowBox(), and NONE.
Referenced by TaskLeaderLine().
startTracker()
void TaskLeaderLine::startTracker () protected
Definition at line 596 of file TaskLeaderLine.cpp.
References draftgeoutils.intersections::connect(), TechDrawGui::QGTracker::drawingFinished(), Gui::getMainWindow(), TechDrawGui::ViewProviderPage::getQGSPage(), MessageDisplayTime, Path.Op.Surface::msg, Gui::None, onTrackerFinished(), setEditCursor(), and Gui::MainWindow::showMessage().
Referenced by onTrackerClicked().
updateLeaderFeature()
void TaskLeaderLine::updateLeaderFeature () protected
Definition at line 430 of file TaskLeaderLine.cpp.
References TechDrawGui::ViewProviderLeader::Color, Gui::Command::commitCommand(), commonFeatureUpdate(), TechDrawGui::ViewProviderLeader::LineStyle, TechDrawGui::ViewProviderLeader::LineWidth, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, TechDraw::DrawView::requestPaint(), App::PropertyQuantity::setValue(), App::PropertyEnumeration::setValue(), App::Color::setValue(), App::PropertyColor::setValue(), and Gui::Command::updateActive().
Referenced by accept().
updateTask()
void TaskLeaderLine::updateTask ()
Definition at line 202 of file TaskLeaderLine.cpp.
The documentation for this class was generated from the following files:
TaskLeaderLine.h
TaskLeaderLine.cpp