FreeCAD: Sandbox::DocumentReceiver Class Reference
Sandbox::DocumentReceiver Class Reference
Public Member Functions
DocumentReceiver (QObject *parent=0)
~DocumentReceiver ()
Static Public Member Functions
static DocumentReceiver * globalInstance ()
Protected Member Functions
void customEvent (QEvent *)
void postEventAndWait (QEvent *)
Friends
class DocumentProtector
class DocumentObjectProtector
Detailed Description
Definition at line 182 of file DocumentProtector.cpp.
Constructor & Destructor Documentation
DocumentReceiver()
Sandbox::DocumentReceiver::DocumentReceiver (QObject * parent = 0) inline
Definition at line 185 of file DocumentProtector.cpp.
~DocumentReceiver()
Sandbox::DocumentReceiver::~DocumentReceiver () inline
Definition at line 188 of file DocumentProtector.cpp.
Member Function Documentation
customEvent()
void Sandbox::DocumentReceiver::customEvent (QEvent * e) protected
Definition at line 232 of file DocumentProtector.cpp.
References SCL.SimpleDataTypes::e, and Sandbox::QT_CUSTOM_EVENT_PROTECTOR.
globalInstance()
DocumentReceiver * Sandbox::DocumentReceiver::globalInstance () static
Definition at line 205 of file DocumentProtector.cpp.
Referenced by Sandbox::DocumentProtector::addObject(), Sandbox::DocumentObjectProtector::execute(), Sandbox::DocumentProtector::init(), Sandbox::DocumentObjectProtector::purgeTouched(), Sandbox::DocumentProtector::recompute(), Sandbox::DocumentProtector::removeObject(), and Sandbox::DocumentObjectProtector::setProperty().
postEventAndWait()
void Sandbox::DocumentReceiver::postEventAndWait (QEvent * e) protected
Definition at line 211 of file DocumentProtector.cpp.
References SCL.SimpleDataTypes::e.
Referenced by Sandbox::DocumentProtector::addObject(), Sandbox::DocumentObjectProtector::execute(), Sandbox::DocumentObjectProtector::purgeTouched(), Sandbox::DocumentProtector::recompute(), Sandbox::DocumentProtector::removeObject(), and Sandbox::DocumentObjectProtector::setProperty().
Friends And Related Function Documentation
DocumentObjectProtector
friend class DocumentObjectProtector friend
Definition at line 200 of file DocumentProtector.cpp.
DocumentProtector
friend class DocumentProtector friend
Definition at line 199 of file DocumentProtector.cpp.
The documentation for this class was generated from the following file:
DocumentProtector.cpp