FreeCAD: App::DocumentObjectWeakPtrT::Private Class Reference
App::DocumentObjectWeakPtrT::Private Class Reference
Public Types
using Connection = boost::signals2::scoped_connection
Public Member Functions
Private (App::DocumentObject *obj)
void deletedDocument (const App::Document &doc)
void createdObject (const App::DocumentObject &obj) noexcept
void deletedObject (const App::DocumentObject &obj) noexcept
void reset ()
void set (App::DocumentObject *obj)
App::DocumentObject * get () const noexcept
Public Attributes
App::DocumentObject * object
bool indocument {false}
Connection connectApplicationDeletedDocument
Connection connectDocumentCreatedObject
Connection connectDocumentDeletedObject
Detailed Description
Definition at line 745 of file App/DocumentObserver.cpp.
Member Typedef Documentation
Connection
using App::DocumentObjectWeakPtrT::Private::Connection = boost::signals2::scoped_connection
Definition at line 804 of file App/DocumentObserver.cpp.
Constructor & Destructor Documentation
Private()
App::DocumentObjectWeakPtrT::Private::Private (App::DocumentObject * obj) inline explicit
Definition at line 748 of file App/DocumentObserver.cpp.
References App::DocumentObjectWeakPtrT::Private::set().
Member Function Documentation
createdObject()
void App::DocumentObjectWeakPtrT::Private::createdObject (const App::DocumentObject & obj) inline noexcept
Definition at line 760 of file App/DocumentObserver.cpp.
References App::DocumentObjectWeakPtrT::Private::indocument.
Referenced by App::DocumentObjectWeakPtrT::Private::set().
deletedDocument()
void App::DocumentObjectWeakPtrT::Private::deletedDocument (const App::Document & doc) inline
Definition at line 753 of file App/DocumentObserver.cpp.
References toolbit-attributes::doc, App::DocumentObject::getDocument(), App::DocumentObjectWeakPtrT::Private::object, and App::DocumentObjectWeakPtrT::Private::reset().
Referenced by App::DocumentObjectWeakPtrT::Private::set().
deletedObject()
void App::DocumentObjectWeakPtrT::Private::deletedObject (const App::DocumentObject & obj) inline noexcept
Definition at line 767 of file App/DocumentObserver.cpp.
References App::DocumentObjectWeakPtrT::Private::indocument.
Referenced by App::DocumentObjectWeakPtrT::Private::set().
get()
App::DocumentObject* App::DocumentObjectWeakPtrT::Private::get () const inline noexcept
Definition at line 797 of file App/DocumentObserver.cpp.
References App::DocumentObjectWeakPtrT::Private::indocument, and App::DocumentObjectWeakPtrT::Private::object.
Referenced by draftguitools.gui_trackers.editTracker::move().
reset()
void App::DocumentObjectWeakPtrT::Private::reset () inline
Definition at line 773 of file App/DocumentObserver.cpp.
References App::DocumentObjectWeakPtrT::Private::connectApplicationDeletedDocument, App::DocumentObjectWeakPtrT::Private::connectDocumentCreatedObject, App::DocumentObjectWeakPtrT::Private::connectDocumentDeletedObject, and App::DocumentObjectWeakPtrT::Private::indocument.
Referenced by ArchVRM.Renderer::__init__(), App::DocumentObjectWeakPtrT::Private::deletedDocument(), draftguitools.gui_trackers.gridTracker::set(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testAll(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
set()
void App::DocumentObjectWeakPtrT::Private::set (App::DocumentObject * obj) inline
Definition at line 781 of file App/DocumentObserver.cpp.
References draftgeoutils.faces::bind(), App::DocumentObjectWeakPtrT::Private::connectApplicationDeletedDocument, App::DocumentObjectWeakPtrT::Private::connectDocumentCreatedObject, App::DocumentObjectWeakPtrT::Private::connectDocumentDeletedObject, App::DocumentObjectWeakPtrT::Private::createdObject(), App::DocumentObjectWeakPtrT::Private::deletedDocument(), App::DocumentObjectWeakPtrT::Private::deletedObject(), toolbit-attributes::doc, App::GetApplication(), App::DocumentObject::getDocument(), App::DocumentObjectWeakPtrT::Private::indocument, and App::Application::signalDeleteDocument.
Referenced by draftguitools.gui_trackers.editTracker::move(), and App::DocumentObjectWeakPtrT::Private::Private().
Member Data Documentation
connectApplicationDeletedDocument
Connection App::DocumentObjectWeakPtrT::Private::connectApplicationDeletedDocument
Definition at line 805 of file App/DocumentObserver.cpp.
Referenced by App::DocumentObjectWeakPtrT::Private::reset(), and App::DocumentObjectWeakPtrT::Private::set().
connectDocumentCreatedObject
Connection App::DocumentObjectWeakPtrT::Private::connectDocumentCreatedObject
Definition at line 806 of file App/DocumentObserver.cpp.
Referenced by App::DocumentObjectWeakPtrT::Private::reset(), and App::DocumentObjectWeakPtrT::Private::set().
connectDocumentDeletedObject
Connection App::DocumentObjectWeakPtrT::Private::connectDocumentDeletedObject
Definition at line 807 of file App/DocumentObserver.cpp.
Referenced by App::DocumentObjectWeakPtrT::Private::reset(), and App::DocumentObjectWeakPtrT::Private::set().
indocument
bool App::DocumentObjectWeakPtrT::Private::indocument {false}
Definition at line 803 of file App/DocumentObserver.cpp.
Referenced by App::DocumentObjectWeakPtrT::Private::createdObject(), App::DocumentObjectWeakPtrT::Private::deletedObject(), App::DocumentObjectWeakPtrT::Private::get(), App::DocumentObjectWeakPtrT::Private::reset(), and App::DocumentObjectWeakPtrT::Private::set().
object
App::DocumentObject* App::DocumentObjectWeakPtrT::Private::object
Definition at line 802 of file App/DocumentObserver.cpp.
Referenced by ArchIFCView.IfcContextUI::accept(), App::DocumentObjectWeakPtrT::Private::deletedDocument(), App::DocumentObjectWeakPtrT::Private::get(), ArchIFCView.IfcContextUI::prefillMapConversionForm(), importers.importIFCHelper.ProjectImporter::setAttributes(), and importers.importIFCHelper.ProjectImporter::setComplexAttributes().
The documentation for this class was generated from the following file:
App/DocumentObserver.cpp