FreeCAD: ifc2x3.ifctextstylewithboxcharacteristics Class Reference
ifc2x3.ifctextstylewithboxcharacteristics Class Reference
Public Member Functions
def __init__ (self, boxheight, boxwidth, boxslantangle, boxrotateangle, characterspacing)
def boxheight ()
def boxwidth ()
def boxslantangle ()
def boxrotateangle ()
def characterspacing ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
boxheight
boxwidth
boxslantangle
boxrotateangle
characterspacing
Detailed Description
Entity ifctextstylewithboxcharacteristics definition.
:param boxheight
:type boxheight:ifcpositivelengthmeasure
:param boxwidth
:type boxwidth:ifcpositivelengthmeasure
:param boxslantangle
:type boxslantangle:ifcplaneanglemeasure
:param boxrotateangle
:type boxrotateangle:ifcplaneanglemeasure
:param characterspacing
:type characterspacing:ifcsizeselect
Definition at line 30053 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifctextstylewithboxcharacteristics.__init__ (self, boxheight, boxwidth, boxslantangle, boxrotateangle, characterspacing)
Definition at line 30071 of file ifc2x3.py.
Member Function Documentation
boxheight()
def ifc2x3.ifctextstylewithboxcharacteristics.boxheight ()
Definition at line 30079 of file ifc2x3.py.
References ifc2x3.ifctextstylewithboxcharacteristics._boxheight, ifc2x3.ifctextstylewithboxcharacteristics.boxheight, and SCL.TypeChecker.check_type().
boxrotateangle()
def ifc2x3.ifctextstylewithboxcharacteristics.boxrotateangle ()
Definition at line 30121 of file ifc2x3.py.
References ifc2x3.ifctextstylewithboxcharacteristics._boxrotateangle, ifc2x3.ifctextstylewithboxcharacteristics.boxrotateangle, and SCL.TypeChecker.check_type().
boxslantangle()
def ifc2x3.ifctextstylewithboxcharacteristics.boxslantangle ()
Definition at line 30107 of file ifc2x3.py.
References ifc2x3.ifctextstylewithboxcharacteristics._boxslantangle, ifc2x3.ifctextstylewithboxcharacteristics.boxslantangle, and SCL.TypeChecker.check_type().
boxwidth()
def ifc2x3.ifctextstylewithboxcharacteristics.boxwidth ()
Definition at line 30093 of file ifc2x3.py.
References ifc2x3.ifctextstylewithboxcharacteristics._boxwidth, ifc2x3.ifctextstylewithboxcharacteristics.boxwidth, and SCL.TypeChecker.check_type().
characterspacing()
def ifc2x3.ifctextstylewithboxcharacteristics.characterspacing ()
Definition at line 30135 of file ifc2x3.py.
References ifc2x3.ifctextstylewithboxcharacteristics._characterspacing, ifc2x3.ifctextstylewithboxcharacteristics.characterspacing, SCL.TypeChecker.check_type(), and ifc2x3.ifcsizeselect.
Member Data Documentation
boxheight
ifc2x3.ifctextstylewithboxcharacteristics.boxheight
Definition at line 30072 of file ifc2x3.py.
Referenced by ifc2x3.ifctextstylewithboxcharacteristics.boxheight().
boxrotateangle
ifc2x3.ifctextstylewithboxcharacteristics.boxrotateangle
Definition at line 30075 of file ifc2x3.py.
Referenced by ifc2x3.ifctextstylewithboxcharacteristics.boxrotateangle().
boxslantangle
ifc2x3.ifctextstylewithboxcharacteristics.boxslantangle
Definition at line 30074 of file ifc2x3.py.
Referenced by ifc2x3.ifctextstylewithboxcharacteristics.boxslantangle().
boxwidth
ifc2x3.ifctextstylewithboxcharacteristics.boxwidth
Definition at line 30073 of file ifc2x3.py.
Referenced by ifc2x3.ifctextstylewithboxcharacteristics.boxwidth().
characterspacing
ifc2x3.ifctextstylewithboxcharacteristics.characterspacing
Definition at line 30076 of file ifc2x3.py.
Referenced by ifc2x3.ifctextstylewithboxcharacteristics.characterspacing().
The documentation for this class was generated from the following file:
ifc2x3.py