FreeCAD: CAMTests.TestPathAdaptive Namespace Reference
CAMTests.TestPathAdaptive Namespace Reference
Classes
class TestPathAdaptive
Functions
def setDepthsAndHeights (op, strDep=20.0, finDep=0.0)
def getGcodeMoves (cmdList, includeRapids=True, includeLines=True, includeArcs=True)
def pathOriginatesInBox (cmd, minPoint, maxPoint)
Variables
string expected_moves_test01
Function Documentation
getGcodeMoves()
def CAMTests.TestPathAdaptive.getGcodeMoves (cmdList, includeRapids = True, includeLines = True, includeArcs = True)
getGcodeMoves(cmdList, includeRapids=True, includeLines=True, includeArcs=True)...
Accepts command dict and returns point string coordinate.
Definition at line 420 of file TestPathAdaptive.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by CAMTests.TestPathProfile.TestPathProfile.test02(), and CAMTests.TestPathProfile.TestPathProfile.test03().
pathOriginatesInBox()
def CAMTests.TestPathAdaptive.pathOriginatesInBox (cmd, minPoint, maxPoint)
Definition at line 500 of file TestPathAdaptive.py.
Referenced by CAMTests.TestPathAdaptive.TestPathAdaptive.test06(), and CAMTests.TestPathAdaptive.TestPathAdaptive.test07().
setDepthsAndHeights()
def CAMTests.TestPathAdaptive.setDepthsAndHeights (op, strDep = 20.0, finDep = 0.0)
setDepthsAndHeights(op, strDep=20.0, finDep=0.0)... Sets default depths and heights for `op` passed to it
Definition at line 403 of file TestPathAdaptive.py.
Variable Documentation
expected_moves_test01
string CAMTests.TestPathAdaptive.expected_moves_test01
Initial value:
 =  "G1 X32.5 Y32.5 Z5.0;  \
 G1 X17.5 Y32.5 Z5.0;  \
 G1 X17.5 Y30.0 Z5.0;  \
 G1 X32.5 Y30.0 Z5.0;  \
 G1 X32.5 Y27.5 Z5.0;  \
 G1 X17.5 Y27.5 Z5.0;  \
 G1 X17.5 Y25.0 Z5.0;  \
 G1 X32.5 Y25.0 Z5.0;  \
 G1 X32.5 Y22.5 Z5.0;  \
 G1 X17.5 Y22.5 Z5.0;  \
 G1 X17.5 Y20.0 Z5.0;  \
 G1 X32.5 Y20.0 Z5.0;  \
 G1 X32.5 Y17.5 Z5.0;  \
 G1 X17.5 Y17.5 Z5.0"
Definition at line 521 of file TestPathAdaptive.py.