FreeCAD: SoMouseWheelEvent Class Reference
SoMouseWheelEvent Class Reference
The SoMouseWheelEvent class is a temporary replacement for SoMouseWheelEvent from Coin, for until freecad stops using Coin version that doesn't have one (coin v 4.0.0a doesn't have SoMouseWheelEvent).
#include <SoMouseWheelEvent.h>
Public Member Functions
SoMouseWheelEvent ()
SoMouseWheelEvent (int delta)
int getDelta () const
void setDelta (int delta)
~SoMouseWheelEvent () override=default
Static Public Member Functions
static void initClass ()
Detailed Description
The SoMouseWheelEvent class is a temporary replacement for SoMouseWheelEvent from Coin, for until freecad stops using Coin version that doesn't have one (coin v 4.0.0a doesn't have SoMouseWheelEvent).
Definition at line 36 of file SoMouseWheelEvent.h.
Constructor & Destructor Documentation
SoMouseWheelEvent() [1/2]
SoMouseWheelEvent::SoMouseWheelEvent () inline
Definition at line 62 of file SoMouseWheelEvent.h.
SoMouseWheelEvent() [2/2]
SoMouseWheelEvent::SoMouseWheelEvent (int delta) inline
Definition at line 63 of file SoMouseWheelEvent.h.
~SoMouseWheelEvent()
SoMouseWheelEvent::~SoMouseWheelEvent () override default
Member Function Documentation
getDelta()
int SoMouseWheelEvent::getDelta () const inline
returns wheel position change. One click is usually 120 units, smaller values come from high-resolution devices like touchpads
Definition at line 66 of file SoMouseWheelEvent.h.
Referenced by bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseMove(), and Gui::NavigationStyle::processWheelEvent().
initClass()
static void SoMouseWheelEvent::initClass () inline static
Definition at line 59 of file SoMouseWheelEvent.h.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
setDelta()
void SoMouseWheelEvent::setDelta (int delta) inline
Definition at line 67 of file SoMouseWheelEvent.h.
Referenced by SIM::Coin3D::Quarter::MouseP::mouseWheelEvent().
The documentation for this class was generated from the following file:
SoMouseWheelEvent.h