FreeCAD: Gui::Dialog::DlgSettingsNotificationArea Class Reference
Gui::Dialog::DlgSettingsNotificationArea Class Reference
#include <DlgSettingsNotificationArea.h>
Public Member Functions
DlgSettingsNotificationArea (QWidget *parent=nullptr)
~DlgSettingsNotificationArea () override
void saveSettings () override
void loadSettings () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
The DlgSettingsNotificationArea class implements a preference page to change settings for the Notification Area.
Definition at line 78 of file DlgSettingsNotificationArea.h.
Constructor & Destructor Documentation
DlgSettingsNotificationArea()
DlgSettingsNotificationArea::DlgSettingsNotificationArea (QWidget * parent = nullptr) explicit
Definition at line 39 of file DlgSettingsNotificationArea.cpp.
References draftgeoutils.intersections::connect().
~DlgSettingsNotificationArea()
DlgSettingsNotificationArea::~DlgSettingsNotificationArea () override default
Member Function Documentation
changeEvent()
void DlgSettingsNotificationArea::changeEvent (QEvent * e) override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 104 of file DlgSettingsNotificationArea.cpp.
References SCL.SimpleDataTypes::e.
loadSettings()
void DlgSettingsNotificationArea::loadSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 81 of file DlgSettingsNotificationArea.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), and App::Application::GetParameterGroupByPath().
saveSettings()
void DlgSettingsNotificationArea::saveSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 57 of file DlgSettingsNotificationArea.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetBool().
The documentation for this class was generated from the following files:
DlgSettingsNotificationArea.h
DlgSettingsNotificationArea.cpp