FreeCAD: materialtools.MaterialModels Namespace Reference
materialtools.MaterialModels Namespace Reference
Functions
def getPreferredSaveDirectory ()
def getModelLibraries ()
def getModel (uuid)
def getModelFromPath (filePath)
def saveModel (model, path)
Variables
unicode = str
Function Documentation
getModel()
def materialtools.MaterialModels.getModel (uuid)
    Retrieve the specified model.
Definition at line 117 of file MaterialModels.py.
References materialtools.MaterialModels.getModelLibraries().
Referenced by materialtests.TestModels.ModelTestCases.testModelLoad().
getModelFromPath()
def materialtools.MaterialModels.getModelFromPath (filePath)
    Retrieve the model at the specified path.
    This may not need public exposure?
Definition at line 128 of file MaterialModels.py.
References AssemblyImport.open().
getModelLibraries()
def materialtools.MaterialModels.getModelLibraries ()
Definition at line 105 of file MaterialModels.py.
Referenced by materialtools.MaterialModels.getModel().
getPreferredSaveDirectory()
def materialtools.MaterialModels.getPreferredSaveDirectory ()
Definition at line 102 of file MaterialModels.py.
saveModel()
def materialtools.MaterialModels.saveModel (model, path)
    Write the model to the specified path
Definition at line 160 of file MaterialModels.py.
Variable Documentation
unicode
materialtools.MaterialModels.unicode = str
Definition at line 34 of file MaterialModels.py.