FreeCAD: MatGui::DlgDisplayPropertiesImp::Private Class Reference
MatGui::DlgDisplayPropertiesImp::Private Class Reference
Static Public Member Functions
static void setElementColor (const std::vector< Gui::ViewProvider * > &views, const char *property, Gui::ColorButton *buttonColor)
static void setElementAppearance (const std::vector< Gui::ViewProvider * > &views, const char *property, Gui::ColorButton *buttonColor)
static void setDrawStyle (const std::vector< Gui::ViewProvider * > &views, const char *property, QSpinBox *spinbox)
static void setTransparency (const std::vector< Gui::ViewProvider * > &views, const char *property, QSpinBox *spinbox, QSlider *slider)
Public Attributes
Ui::DlgDisplayProperties ui
DlgDisplayPropertiesImp_Connection connectChangedObject
Detailed Description
Definition at line 52 of file DlgDisplayPropertiesImp.cpp.
Member Function Documentation
setDrawStyle()
static void MatGui::DlgDisplayPropertiesImp::Private::setDrawStyle (const std::vector< Gui::ViewProvider * > & views, const char * property, QSpinBox * spinbox) inline static
Definition at line 97 of file DlgDisplayPropertiesImp.cpp.
setElementAppearance()
static void MatGui::DlgDisplayPropertiesImp::Private::setElementAppearance (const std::vector< Gui::ViewProvider * > & views, const char * property, Gui::ColorButton * buttonColor) inline static
Definition at line 78 of file DlgDisplayPropertiesImp.cpp.
References App::Color::asValue(), and Gui::ColorButton::setColor().
setElementColor()
static void MatGui::DlgDisplayPropertiesImp::Private::setElementColor (const std::vector< Gui::ViewProvider * > & views, const char * property, Gui::ColorButton * buttonColor) inline static
Definition at line 60 of file DlgDisplayPropertiesImp.cpp.
References App::Color::asValue(), and Gui::ColorButton::setColor().
setTransparency()
static void MatGui::DlgDisplayPropertiesImp::Private::setTransparency (const std::vector< Gui::ViewProvider * > & views, const char * property, QSpinBox * spinbox, QSlider * slider) inline static
Definition at line 114 of file DlgDisplayPropertiesImp.cpp.
Member Data Documentation
connectChangedObject
DlgDisplayPropertiesImp_Connection MatGui::DlgDisplayPropertiesImp::Private::connectChangedObject
Definition at line 58 of file DlgDisplayPropertiesImp.cpp.
ui
Ui::DlgDisplayProperties MatGui::DlgDisplayPropertiesImp::Private::ui
Definition at line 57 of file DlgDisplayPropertiesImp.cpp.
Referenced by DraftGui.DraftToolBar::changeEvent().
The documentation for this class was generated from the following file:
DlgDisplayPropertiesImp.cpp