FreeCAD: Gui::ViewProviderWeakPtrT Class Reference
Gui::ViewProviderWeakPtrT Class Reference
The ViewProviderWeakPtrT class.
#include <DocumentObserver.h>
Classes
class Private
Public Member Functions
ViewProviderWeakPtrT (ViewProviderDocumentObject *)
~ViewProviderWeakPtrT ()
void reset ()
reset Releases the reference to the managed object. After the call *this manages no object.
bool expired () const noexcept
expired
ViewProviderWeakPtrT & operator= (ViewProviderDocumentObject *p)
operator = Assignment operator
ViewProviderDocumentObject * operator* () const noexcept
operator *
ViewProviderDocumentObject * operator-> () const noexcept
operator ->
bool operator== (const ViewProviderWeakPtrT &p) const noexcept
operator ==
bool operator!= (const ViewProviderWeakPtrT &p) const noexcept
operator !=
template<typename T >
T * get () const noexcept
ViewProviderWeakPtrT (const ViewProviderWeakPtrT &)=delete
ViewProviderWeakPtrT & operator= (const ViewProviderWeakPtrT &)=delete
Detailed Description
The ViewProviderWeakPtrT class.
Definition at line 173 of file Gui/DocumentObserver.h.
Constructor & Destructor Documentation
ViewProviderWeakPtrT() [1/2]
ViewProviderWeakPtrT::ViewProviderWeakPtrT (ViewProviderDocumentObject * obj) explicit
Definition at line 348 of file Gui/DocumentObserver.cpp.
~ViewProviderWeakPtrT()
ViewProviderWeakPtrT::~ViewProviderWeakPtrT () default
ViewProviderWeakPtrT() [2/2]
Gui::ViewProviderWeakPtrT::ViewProviderWeakPtrT (const ViewProviderWeakPtrT &) delete
Member Function Documentation
expired()
bool ViewProviderWeakPtrT::expired () const noexcept
expired
Returns
true if the managed object has already been deleted, false otherwise.
Definition at line 365 of file Gui/DocumentObserver.cpp.
get()
template<typename T > T* Gui::ViewProviderWeakPtrT::get () const inline noexcept
Get a pointer to the object or 0 if it doesn't exist any more or the type doesn't match.
Definition at line 216 of file Gui/DocumentObserver.h.
Referenced by FemGui::TaskPostBox::getTypedView(), and draftguitools.gui_trackers.editTracker::move().
operator!=()
bool ViewProviderWeakPtrT::operator!= (const ViewProviderWeakPtrT & p) const noexcept
operator !=
Returns
true if both objects are inequal, false otherwise
Definition at line 392 of file Gui/DocumentObserver.cpp.
References buildPsets::p.
operator*()
ViewProviderDocumentObject * ViewProviderWeakPtrT::operator* () const noexcept
operator *
Returns
pointer to the document
Definition at line 377 of file Gui/DocumentObserver.cpp.
operator->()
ViewProviderDocumentObject * ViewProviderWeakPtrT::operator-> () const noexcept
operator ->
Returns
pointer to the document
Definition at line 382 of file Gui/DocumentObserver.cpp.
operator=() [1/2]
ViewProviderWeakPtrT& Gui::ViewProviderWeakPtrT::operator= (const ViewProviderWeakPtrT &) delete
operator=() [2/2]
ViewProviderWeakPtrT & ViewProviderWeakPtrT::operator= (ViewProviderDocumentObject * p)
operator = Assignment operator
Definition at line 370 of file Gui/DocumentObserver.cpp.
References buildPsets::p.
operator==()
bool ViewProviderWeakPtrT::operator== (const ViewProviderWeakPtrT & p) const noexcept
operator ==
Returns
true if both objects are equal, false otherwise
Definition at line 387 of file Gui/DocumentObserver.cpp.
References buildPsets::p.
reset()
void ViewProviderWeakPtrT::reset ()
reset Releases the reference to the managed object. After the call *this manages no object.
Definition at line 360 of file Gui/DocumentObserver.cpp.
Referenced by ArchVRM.Renderer::__init__(), draftguitools.gui_trackers.gridTracker::set(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testAll(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
The documentation for this class was generated from the following files:
Gui/DocumentObserver.h
Gui/DocumentObserver.cpp