FreeCAD: ifc2x3.ifcdimensioncurve Class Reference
ifc2x3.ifcdimensioncurve Class Reference
Public Member Functions
def __init__ (self, inherited0__item, inherited1__styles, inherited2__name)
def annotatedbysymbols ()
def wr51 (self)
def wr52 (self)
def wr53 (self)
Public Member Functions inherited from ifc2x3.ifcannotationcurveoccurrence
def wr31 (self)
Public Member Functions inherited from ifc2x3.ifcstyleditem
def item ()
def styles ()
def name ()
def wr11 (self)
def wr12 (self)
Public Member Functions inherited from ifc2x3.ifcrepresentationitem
def layerassignments ()
def styledbyitem ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Additional Inherited Members
Public Attributes inherited from ifc2x3.ifcstyleditem
item
styles
name
Detailed Description
Entity ifcdimensioncurve definition.
:param annotatedbysymbols
:type annotatedbysymbols:SET(0,2,'ifcterminatorsymbol', scope = schema_scope)
Definition at line 16906 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcdimensioncurve.__init__ (self, inherited0__item, inherited1__styles, inherited2__name)
Reimplemented from ifc2x3.ifcannotationcurveoccurrence.
Definition at line 16912 of file ifc2x3.py.
Member Function Documentation
annotatedbysymbols()
def ifc2x3.ifcdimensioncurve.annotatedbysymbols ()
Definition at line 16916 of file ifc2x3.py.
wr51()
def ifc2x3.ifcdimensioncurve.wr51 (self)
Definition at line 16923 of file ifc2x3.py.
References SCL.Builtin.SIZEOF(), and SCL.Builtin.USEDIN().
wr52()
def ifc2x3.ifcdimensioncurve.wr52 (self)
Definition at line 16930 of file ifc2x3.py.
References SCL.Builtin.SIZEOF().
wr53()
def ifc2x3.ifcdimensioncurve.wr53 (self)
Definition at line 16937 of file ifc2x3.py.
References SCL.Builtin.SIZEOF().
The documentation for this class was generated from the following file:
ifc2x3.py