FreeCAD: MeshGui Namespace Reference
MeshGui Namespace Reference
The namespace of the Mesh Graphical interface layer library.
Classes
class Annotation
class CleanupHandler
class CylinderFitParameter
class DlgDecimating
class DlgEvaluateMeshImp
class DlgEvaluateSettings
class DlgRegularSolidImp
class DlgSettingsImportExport
class DlgSettingsMeshView
class DlgSmoothing
class DockEvaluateMeshImp
class FitParameter
class GmshWidget
class MeshFaceAddition
class MeshFillHole
class MeshHoleFiller
class MeshRenderer
class MeshSelection
class MeshSplit
class Module
struct NofFacetsCompare
class ParametersDialog
class PlaneFitParameter
class PropertyMeshKernelItem
class RemeshGmsh
class RemoveComponents
class RemoveComponentsDialog
class Segmentation
class SegmentationBestFit
class Selection
class SmoothingDialog
class SoFCIndexedFaceSet
The SoFCIndexedFaceSet class is designed to optimize redrawing a mesh during user interaction.
class SoFCMaterialEngine
The SoFCMaterialEngine class is used to notify an SoFCIndexedFaceSet node about material changes.
class SoFCMeshGridNode
class SoFCMeshObjectBoundary
class SoFCMeshObjectElement
class SoFCMeshObjectNode
class SoFCMeshObjectShape
The SoFCMeshObjectShape class is designed to render huge meshes.
class SoFCMeshPickNode
class SoFCMeshSegmentShape
class SoPolygon
class SoSFMeshObject
class SphereFitParameter
class TaskDecimating
class TaskRemeshGmsh
class TaskRemoveComponents
class TaskSegmentation
class TaskSegmentationBestFit
class TaskSmoothing
class ThumbnailExtension3MF
class ThumbnailExtensionProducer
class Vertex
class ViewProviderExport
class ViewProviderFace
class ViewProviderIndexedFaceSet
class ViewProviderMesh
class ViewProviderMeshBuilder
class ViewProviderMeshCurvature
class ViewProviderMeshDefects
class ViewProviderMeshDegenerations
class ViewProviderMeshDuplicatedFaces
class ViewProviderMeshDuplicatedPoints
class ViewProviderMeshFaceSet
class ViewProviderMeshFolds
class ViewProviderMeshIndices
class ViewProviderMeshNonManifoldPoints
class ViewProviderMeshNonManifolds
class ViewProviderMeshObject
class ViewProviderMeshOrientation
class ViewProviderMeshSelfIntersections
class ViewProviderMeshTransform
class ViewProviderMeshTransformDemolding
class Workbench
Typedefs
using ParameterList = std::list< std::pair< QString, float > >
using ViewProviderPython = Gui::ViewProviderFeaturePythonT< ViewProviderMeshFaceSet >
Functions
PyObject * initModule ()
Detailed Description
The namespace of the Mesh Graphical interface layer library.
This namespace includes the graphical interface of FreeCAD such as:
The main window
3D View
Tree
and so on......
Typedef Documentation
ParameterList
using MeshGui::ParameterList = typedef std::list<std::pair<QString, float> >
Definition at line 65 of file SegmentationBestFit.h.
ViewProviderPython
using MeshGui::ViewProviderPython = typedef Gui::ViewProviderFeaturePythonT<ViewProviderMeshFaceSet>
Definition at line 53 of file Mesh/Gui/ViewProviderPython.h.
Function Documentation
initModule()
PyObject* MeshGui::initModule ()
Definition at line 114 of file AppMeshGui.cpp.
References Base::InterpreterSingleton::addModule(), and Base::Interpreter().
Referenced by PyMOD_INIT_FUNC().