FreeCAD: Measure::SubnameHelper Class Reference
Measure::SubnameHelper Class Reference
a class to perform common operations on subelement names.
#include <SubnameHelper.h>
Static Public Member Functions
static std::string getLastTerm (const std::string &inString)
return the last term of a dot separated string - A.B.C returns C
static std::string getFirstTerm (const std::string &inString)
return the first term of a dot separated string - A.B.C returns A
static std::string namesToLongSub (const std::vector< std::string > &pathElementNames)
static std::string pruneLastTerm (const std::string &inString)
return a dot separated string without its last term - A.B.C returns A.B.
static std::string pruneFirstTerm (const std::string &inString)
remove the first term of a dot separated string - A.B.C returns B.C
static std::string removeGeometryTerm (const std::string &longSubname)
static std::string pathToLongSub (std::list< App::DocumentObject * > path)
static std::string removeTnpInfo (const std::string &inString)
Detailed Description
a class to perform common operations on subelement names.
Definition at line 62 of file SubnameHelper.h.
Member Function Documentation
getFirstTerm()
std::string SubnameHelper::getFirstTerm (const std::string & inString) static
return the first term of a dot separated string - A.B.C returns A
Definition at line 79 of file SubnameHelper.cpp.
References result.
getLastTerm()
std::string SubnameHelper::getLastTerm (const std::string & inString) static
return the last term of a dot separated string - A.B.C returns C
Definition at line 68 of file SubnameHelper.cpp.
References result.
Referenced by removeGeometryTerm(), removeTnpInfo(), and Measure::ShapeFinder::resolveSelection().
namesToLongSub()
std::string SubnameHelper::namesToLongSub (const std::vector< std::string > & pathElementNames) static
construct dot separated long subelement name from a list of elements. the elements should be in topological order.
Definition at line 57 of file SubnameHelper.cpp.
References result.
Referenced by pathToLongSub().
pathToLongSub()
std::string SubnameHelper::pathToLongSub (std::list< App::DocumentObject * > path) static
Definition at line 41 of file SubnameHelper.cpp.
References namesToLongSub().
pruneFirstTerm()
std::string SubnameHelper::pruneFirstTerm (const std::string & inString) static
remove the first term of a dot separated string - A.B.C returns B.C
Definition at line 90 of file SubnameHelper.cpp.
References result.
pruneLastTerm()
std::string SubnameHelper::pruneLastTerm (const std::string & inString) static
return a dot separated string without its last term - A.B.C returns A.B.
Definition at line 102 of file SubnameHelper.cpp.
References result.
Referenced by Measure::ShapeFinder::crawlPlacementChain(), and removeGeometryTerm().
removeGeometryTerm()
std::string SubnameHelper::removeGeometryTerm (const std::string & longSubname) static
remove that part of a long subelement name that refers to a geometric subshape. "myObj.Vertex1" would return "myObj.", "myObj.mySubObj." would return itself unchanged. If there is no geometric reference the original input is returned.
Definition at line 125 of file SubnameHelper.cpp.
References getLastTerm(), RobotExample::pos, and pruneLastTerm().
Referenced by Measure::ShapeFinder::getGlobalTransform().
removeTnpInfo()
std::string SubnameHelper::removeTnpInfo (const std::string & inString) static
remove the tnp information from a selection sub name returning a dot separated path Array001.Array001_i0.Array_i1.;Vertex33;:H1116,V.Vertex33 to Array001.Array001_i0.Array_i1.Vertex33
Definition at line 166 of file SubnameHelper.cpp.
References getLastTerm(), and result.
Referenced by Measure::ShapeFinder::getLocatedShape().
The documentation for this class was generated from the following files:
SubnameHelper.h
SubnameHelper.cpp