FreeCAD: Gui::SoGLVBOActivatedElement Class Reference
Gui::SoGLVBOActivatedElement Class Reference
#include <SoFCInteractiveElement.h>
Public Member Functions
void init (SoState *state) override
void push (SoState *state) override
void pop (SoState *state, const SoElement *prevTopElement) override
SbBool matches (const SoElement *element) const override
SoElement * copyMatchInfo () const override
Static Public Member Functions
static void initClass ()
static void set (SoState *state, SbBool)
static void get (SoState *state, SbBool &active)
Protected Member Functions
~SoGLVBOActivatedElement () override
Protected Attributes
SbBool active
Detailed Description
Definition at line 149 of file SoFCInteractiveElement.h.
Constructor & Destructor Documentation
~SoGLVBOActivatedElement()
SoGLVBOActivatedElement::~SoGLVBOActivatedElement () override protected default
Member Function Documentation
copyMatchInfo()
SoElement * SoGLVBOActivatedElement::copyMatchInfo () const override
Definition at line 271 of file SoFCInteractiveElement.cpp.
get()
void SoGLVBOActivatedElement::get (SoState * state, SbBool & active) static
Definition at line 239 of file SoFCInteractiveElement.cpp.
References active.
Referenced by PartGui::SoBrepFaceSet::GLRender(), MeshGui::SoFCIndexedFaceSet::GLRender(), and draftguitools.gui_trackers.editTracker::move().
init()
void SoGLVBOActivatedElement::init (SoState * state) override
Definition at line 224 of file SoFCInteractiveElement.cpp.
References active, and SIM::Coin3D::Quarter::Quarter::init().
Referenced by DocumentObject.DocumentObject::onChanged().
initClass()
void SoGLVBOActivatedElement::initClass () static
Definition at line 217 of file SoFCInteractiveElement.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
matches()
SbBool SoGLVBOActivatedElement::matches (const SoElement * element) const override
Definition at line 266 of file SoFCInteractiveElement.cpp.
pop()
void SoGLVBOActivatedElement::pop (SoState * state, const SoElement * prevTopElement) override
Definition at line 261 of file SoFCInteractiveElement.cpp.
push()
void SoGLVBOActivatedElement::push (SoState * state) override
Definition at line 256 of file SoFCInteractiveElement.cpp.
set()
void SoGLVBOActivatedElement::set (SoState * state, SbBool active) static
Definition at line 232 of file SoFCInteractiveElement.cpp.
References active.
Referenced by draftguitools.gui_trackers.editTracker::move(), and Gui::View3DInventorViewer::renderScene().
Member Data Documentation
active
SbBool Gui::SoGLVBOActivatedElement::active protected
Definition at line 171 of file SoFCInteractiveElement.h.
Referenced by draftguitools.gui_texts.Text::action(), get(), init(), PathCommands._CommandSelectLoop::IsActive(), and set().
The documentation for this class was generated from the following files:
SoFCInteractiveElement.h
SoFCInteractiveElement.cpp