FreeCAD: Path.Post.scripts.KineticNCBeamicon2_post Namespace Reference
Path.Post.scripts.KineticNCBeamicon2_post Namespace Reference
Functions
def processArguments (argstring)
def export (objectslist, filename, argstring)
def linenumber ()
def parse (pathobj)
Variables
TOOLTIP
now
parser
prog
add_help
action = "store_true",
help = "don't pop up editor before writing output",
default
TOOLTIP_ARGS
OUTPUT_COMMENTS
OUTPUT_HEADER
OUTPUT_LINE_NUMBERS
SHOW_EDITOR
MODAL
OUTPUT_DOUBLES
COMMAND_SPACE
LINENR
UNITS
UNIT_SPEED_FORMAT
UNIT_FORMAT
MACHINE_NAME
CORNER_MIN
CORNER_MAX
PRECISION
PREAMBLE
POSTAMBLE
PRE_OPERATION
POST_OPERATION
TOOL_CHANGE
Function Documentation
export()
def Path.Post.scripts.KineticNCBeamicon2_post.export (objectslist, filename, argstring)
Definition at line 179 of file KineticNCBeamicon2_post.py.
References Path.Post.scripts.KineticNCBeamicon2_post.linenumber(), Path.Post.scripts.KineticNCBeamicon2_post.parse(), Path.Post.scripts.KineticNCBeamicon2_post.processArguments(), and Path.Post.scripts.refactored_centroid_post.str.
linenumber()
def Path.Post.scripts.KineticNCBeamicon2_post.linenumber ()
Definition at line 274 of file KineticNCBeamicon2_post.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.KineticNCBeamicon2_post.export(), and Path.Post.scripts.KineticNCBeamicon2_post.parse().
parse()
def Path.Post.scripts.KineticNCBeamicon2_post.parse (pathobj)
Definition at line 282 of file KineticNCBeamicon2_post.py.
References Path.Post.scripts.KineticNCBeamicon2_post.linenumber(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.KineticNCBeamicon2_post.export().
processArguments()
def Path.Post.scripts.KineticNCBeamicon2_post.processArguments (argstring)
Definition at line 132 of file KineticNCBeamicon2_post.py.
Referenced by Path.Post.scripts.KineticNCBeamicon2_post.export().
Variable Documentation
action
string Path.Post.scripts.KineticNCBeamicon2_post.action = "store_true",
Definition at line 60 of file KineticNCBeamicon2_post.py.
add_help
Path.Post.scripts.KineticNCBeamicon2_post.add_help
Definition at line 59 of file KineticNCBeamicon2_post.py.
COMMAND_SPACE
Path.Post.scripts.KineticNCBeamicon2_post.COMMAND_SPACE
Definition at line 96 of file KineticNCBeamicon2_post.py.
CORNER_MAX
Path.Post.scripts.KineticNCBeamicon2_post.CORNER_MAX
Definition at line 106 of file KineticNCBeamicon2_post.py.
CORNER_MIN
Path.Post.scripts.KineticNCBeamicon2_post.CORNER_MIN
Definition at line 105 of file KineticNCBeamicon2_post.py.
default
Path.Post.scripts.KineticNCBeamicon2_post.default
Definition at line 68 of file KineticNCBeamicon2_post.py.
help
string Path.Post.scripts.KineticNCBeamicon2_post.help = "don't pop up editor before writing output",
Definition at line 60 of file KineticNCBeamicon2_post.py.
LINENR
Path.Post.scripts.KineticNCBeamicon2_post.LINENR
Definition at line 97 of file KineticNCBeamicon2_post.py.
MACHINE_NAME
Path.Post.scripts.KineticNCBeamicon2_post.MACHINE_NAME
Definition at line 104 of file KineticNCBeamicon2_post.py.
MODAL
Path.Post.scripts.KineticNCBeamicon2_post.MODAL
Definition at line 94 of file KineticNCBeamicon2_post.py.
now
Path.Post.scripts.KineticNCBeamicon2_post.now
Definition at line 57 of file KineticNCBeamicon2_post.py.
OUTPUT_COMMENTS
Path.Post.scripts.KineticNCBeamicon2_post.OUTPUT_COMMENTS
Definition at line 90 of file KineticNCBeamicon2_post.py.
OUTPUT_DOUBLES
Path.Post.scripts.KineticNCBeamicon2_post.OUTPUT_DOUBLES
Definition at line 95 of file KineticNCBeamicon2_post.py.
OUTPUT_HEADER
Path.Post.scripts.KineticNCBeamicon2_post.OUTPUT_HEADER
Definition at line 91 of file KineticNCBeamicon2_post.py.
OUTPUT_LINE_NUMBERS
Path.Post.scripts.KineticNCBeamicon2_post.OUTPUT_LINE_NUMBERS
Definition at line 92 of file KineticNCBeamicon2_post.py.
parser
Path.Post.scripts.KineticNCBeamicon2_post.parser
Definition at line 59 of file KineticNCBeamicon2_post.py.
POST_OPERATION
Path.Post.scripts.KineticNCBeamicon2_post.POST_OPERATION
Definition at line 125 of file KineticNCBeamicon2_post.py.
POSTAMBLE
Path.Post.scripts.KineticNCBeamicon2_post.POSTAMBLE
Definition at line 116 of file KineticNCBeamicon2_post.py.
PRE_OPERATION
Path.Post.scripts.KineticNCBeamicon2_post.PRE_OPERATION
Definition at line 122 of file KineticNCBeamicon2_post.py.
PREAMBLE
Path.Post.scripts.KineticNCBeamicon2_post.PREAMBLE
Definition at line 110 of file KineticNCBeamicon2_post.py.
PRECISION
Path.Post.scripts.KineticNCBeamicon2_post.PRECISION
Definition at line 107 of file KineticNCBeamicon2_post.py.
prog
Path.Post.scripts.KineticNCBeamicon2_post.prog
Definition at line 59 of file KineticNCBeamicon2_post.py.
SHOW_EDITOR
Path.Post.scripts.KineticNCBeamicon2_post.SHOW_EDITOR
Definition at line 93 of file KineticNCBeamicon2_post.py.
TOOL_CHANGE
Path.Post.scripts.KineticNCBeamicon2_post.TOOL_CHANGE
Definition at line 128 of file KineticNCBeamicon2_post.py.
TOOLTIP
Path.Post.scripts.KineticNCBeamicon2_post.TOOLTIP
Definition at line 45 of file KineticNCBeamicon2_post.py.
TOOLTIP_ARGS
Path.Post.scripts.KineticNCBeamicon2_post.TOOLTIP_ARGS
Definition at line 87 of file KineticNCBeamicon2_post.py.
UNIT_FORMAT
Path.Post.scripts.KineticNCBeamicon2_post.UNIT_FORMAT
Definition at line 102 of file KineticNCBeamicon2_post.py.
UNIT_SPEED_FORMAT
Path.Post.scripts.KineticNCBeamicon2_post.UNIT_SPEED_FORMAT
Definition at line 101 of file KineticNCBeamicon2_post.py.
UNITS
Path.Post.scripts.KineticNCBeamicon2_post.UNITS
Definition at line 100 of file KineticNCBeamicon2_post.py.