FreeCAD: feminout.importVTKResults Namespace Reference
feminout.importVTKResults Namespace Reference
Functions
def open (filename)
def insert (filename, docname)
def export (objectslist, filename)
def importVtk (filename, object_name=None, object_type=None)
def importVtkVtkResult (filename, resultname)
def importVtkFemMesh (filename, meshname)
def importVtkFCResult (filename, resultname, analysis=None, result_name_prefix=None)
Function Documentation
export()
def feminout.importVTKResults.export (objectslist, filename)
Definition at line 61 of file importVTKResults.py.
importVtk()
def feminout.importVTKResults.importVtk (filename, object_name = None, object_type = None)
Definition at line 82 of file importVTKResults.py.
References feminout.importVTKResults.importVtkFCResult(), feminout.importVTKResults.importVtkFemMesh(), and feminout.importVTKResults.importVtkVtkResult().
Referenced by feminout.importVTKResults.insert().
importVtkFCResult()
def feminout.importVTKResults.importVtkFCResult (filename, resultname, analysis = None, result_name_prefix = None)
Definition at line 120 of file importVTKResults.py.
References ObjectsFem.makeResultMechanical().
Referenced by feminout.importVTKResults.importVtk().
importVtkFemMesh()
def feminout.importVTKResults.importVtkFemMesh (filename, meshname)
Definition at line 112 of file importVTKResults.py.
Referenced by feminout.importVTKResults.importVtk().
importVtkVtkResult()
def feminout.importVTKResults.importVtkVtkResult (filename, resultname)
Definition at line 101 of file importVTKResults.py.
Referenced by feminout.importVTKResults.importVtk().
insert()
def feminout.importVTKResults.insert (filename, docname)
Definition at line 51 of file importVTKResults.py.
References feminout.importVTKResults.importVtk().
Referenced by feminout.importVTKResults.open().
open()
def feminout.importVTKResults.open (filename)
Definition at line 45 of file importVTKResults.py.
References feminout.importVTKResults.insert().