FreeCAD: Path.Op.ThreadMilling Namespace Reference
Path.Op.ThreadMilling Namespace Reference
Classes
class ObjectThreadMilling
Functions
def threadSetupInternal (obj, zTop, zBottom)
def threadSetupExternal (obj, zTop, zBottom)
def threadSetup (obj)
def threadRadii (internal, majorDia, minorDia, toolDia, toolCrest)
def threadPasses (count, radii, internal, majorDia, minorDia, toolDia, toolCrest)
def elevatorRadius (obj, center, internal, tool)
def SetupProperties ()
def Create (name, obj=None, parentJob=None)
Variables
SQRT_3_DIVIDED_BY_2
translate
LeftHand
RightHand
ThreadTypeCustomExternal
ThreadTypeCustomInternal
ThreadTypeImperialExternal2A
ThreadTypeImperialExternal3A
ThreadTypeImperialInternal2B
ThreadTypeImperialInternal3B
ThreadTypeMetricExternal4G6G
ThreadTypeMetricExternal6G
ThreadTypeMetricInternal6H
DirectionClimb
DirectionConventional
ThreadOrientations
ThreadTypeData
ThreadTypesExternal
ThreadTypesInternal
ThreadTypesImperial
ThreadTypesMetric
ThreadTypes
Directions
Function Documentation
Create()
def Path.Op.ThreadMilling.Create (name, obj = None, parentJob = None)
Create(name) ... Creates and returns a thread milling operation.
Definition at line 532 of file ThreadMilling.py.
elevatorRadius()
def Path.Op.ThreadMilling.elevatorRadius (obj, center, internal, tool)
elevatorLocation(obj, center, internal, tool) ... return suitable location for the tool elevator
Definition at line 207 of file ThreadMilling.py.
References Path.Log.error(), and Path.Log.track().
Referenced by Path.Op.ThreadMilling.ObjectThreadMilling.executeThreadMill().
SetupProperties()
def Path.Op.ThreadMilling.SetupProperties ()
Definition at line 516 of file ThreadMilling.py.
threadPasses()
def Path.Op.ThreadMilling.threadPasses (count, radii, internal, majorDia, minorDia, toolDia, toolCrest)
Definition at line 179 of file ThreadMilling.py.
References Path.Log.debug(), CAMTests.TestPathThreadMilling.radii(), and Path.Log.track().
Referenced by Path.Op.ThreadMilling.ObjectThreadMilling.executeThreadMill().
threadRadii()
def Path.Op.ThreadMilling.threadRadii (internal, majorDia, minorDia, toolDia, toolCrest)
threadRadii(majorDia, minorDia, toolDia, toolCrest) ... returns the minimum and maximum radius for thread.
Definition at line 151 of file ThreadMilling.py.
References Path.Log.track().
threadSetup()
def Path.Op.ThreadMilling.threadSetup (obj)
Return (cmd, zbegin, zend) of thread milling operation
Definition at line 138 of file ThreadMilling.py.
References Path.Op.ThreadMilling.threadSetupExternal(), Path.Op.ThreadMilling.threadSetupInternal(), and Path.Log.track().
Referenced by Path.Op.ThreadMilling.ObjectThreadMilling.circularHoleExecute().
threadSetupExternal()
def Path.Op.ThreadMilling.threadSetupExternal (obj, zTop, zBottom)
Definition at line 123 of file ThreadMilling.py.
References Path.Log.track().
Referenced by Path.Op.ThreadMilling.threadSetup().
threadSetupInternal()
def Path.Op.ThreadMilling.threadSetupInternal (obj, zTop, zBottom)
Definition at line 107 of file ThreadMilling.py.
References Path.Log.track().
Referenced by Path.Op.ThreadMilling.threadSetup().
Variable Documentation
DirectionClimb
Path.Op.ThreadMilling.DirectionClimb
Definition at line 60 of file ThreadMilling.py.
DirectionConventional
Path.Op.ThreadMilling.DirectionConventional
Definition at line 61 of file ThreadMilling.py.
Directions
Path.Op.ThreadMilling.Directions
Definition at line 100 of file ThreadMilling.py.
LeftHand
Path.Op.ThreadMilling.LeftHand
Definition at line 49 of file ThreadMilling.py.
RightHand
Path.Op.ThreadMilling.RightHand
Definition at line 50 of file ThreadMilling.py.
SQRT_3_DIVIDED_BY_2
Path.Op.ThreadMilling.SQRT_3_DIVIDED_BY_2
Definition at line 38 of file ThreadMilling.py.
ThreadOrientations
Path.Op.ThreadMilling.ThreadOrientations
Definition at line 63 of file ThreadMilling.py.
ThreadTypeCustomExternal
Path.Op.ThreadMilling.ThreadTypeCustomExternal
Definition at line 51 of file ThreadMilling.py.
ThreadTypeCustomInternal
Path.Op.ThreadMilling.ThreadTypeCustomInternal
Definition at line 52 of file ThreadMilling.py.
ThreadTypeData
Path.Op.ThreadMilling.ThreadTypeData
Definition at line 65 of file ThreadMilling.py.
ThreadTypeImperialExternal2A
Path.Op.ThreadMilling.ThreadTypeImperialExternal2A
Definition at line 53 of file ThreadMilling.py.
ThreadTypeImperialExternal3A
Path.Op.ThreadMilling.ThreadTypeImperialExternal3A
Definition at line 54 of file ThreadMilling.py.
ThreadTypeImperialInternal2B
Path.Op.ThreadMilling.ThreadTypeImperialInternal2B
Definition at line 55 of file ThreadMilling.py.
ThreadTypeImperialInternal3B
Path.Op.ThreadMilling.ThreadTypeImperialInternal3B
Definition at line 56 of file ThreadMilling.py.
ThreadTypeMetricExternal4G6G
Path.Op.ThreadMilling.ThreadTypeMetricExternal4G6G
Definition at line 57 of file ThreadMilling.py.
ThreadTypeMetricExternal6G
Path.Op.ThreadMilling.ThreadTypeMetricExternal6G
Definition at line 58 of file ThreadMilling.py.
ThreadTypeMetricInternal6H
Path.Op.ThreadMilling.ThreadTypeMetricInternal6H
Definition at line 59 of file ThreadMilling.py.
ThreadTypes
Path.Op.ThreadMilling.ThreadTypes
Definition at line 99 of file ThreadMilling.py.
ThreadTypesExternal
Path.Op.ThreadMilling.ThreadTypesExternal
Definition at line 75 of file ThreadMilling.py.
ThreadTypesImperial
Path.Op.ThreadMilling.ThreadTypesImperial
Definition at line 88 of file ThreadMilling.py.
ThreadTypesInternal
Path.Op.ThreadMilling.ThreadTypesInternal
Definition at line 82 of file ThreadMilling.py.
ThreadTypesMetric
Path.Op.ThreadMilling.ThreadTypesMetric
Definition at line 94 of file ThreadMilling.py.
translate
Path.Op.ThreadMilling.translate
Definition at line 46 of file ThreadMilling.py.