FreeCAD: MeshCoreFit::SphereFit Class Reference
MeshCoreFit::SphereFit Class Reference
#include <SphereFit.h>
Public Member Functions
SphereFit ()
void SetApproximations (double radius, const Base::Vector3d &center)
void SetConvergenceCriteria (double posConvLimit, double vConvLimit, int maxIter)
double GetRadius () const
Base::Vector3d GetCenter () const
int GetNumIterations () const
void ComputeApproximations ()
float Fit () override
float GetDistanceToSphere (const Base::Vector3f &rcPoint) const
float GetStdDeviation () const
void ProjectToSphere ()
Public Member Functions inherited from MeshCore::Approximation
Approximation ()
virtual ~Approximation ()
void AddPoint (const Base::Vector3f &point)
void AddPoints (const std::vector< Base::Vector3f > &points)
void AddPoints (const std::set< Base::Vector3f > &points)
void AddPoints (const std::list< Base::Vector3f > &points)
void AddPoints (const MeshPointArray &points)
const std::list< Base::Vector3f > & GetPoints () const
Base::Vector3f GetGravity () const
std::size_t CountPoints () const
void Clear ()
float GetLastResult () const
bool Done () const
Protected Member Functions
void setupNormalEquationMatrices (const std::vector< Base::Vector3d > &residuals, Matrix4x4 &atpa, Eigen::VectorXd &atpl) const
void setupObservation (const Base::Vector3f &point, const Base::Vector3d &residual, double a[4], double &f0, double &qw, double b[3]) const
void addObservationU (double a[4], double li, double pi, Matrix4x4 &atpa, Eigen::VectorXd &atpl) const
void setLowerPart (Matrix4x4 &atpa) const
bool computeResiduals (const Eigen::VectorXd &x, std::vector< Base::Vector3d > &residuals, double &sigma0, double vConvLimit, bool &vConverged) const
Protected Member Functions inherited from MeshCore::Approximation
void GetMgcVectorArray (std::vector< Wm4::Vector3< double >> &rcPts) const
Approximation (const Approximation &)=default
Approximation (Approximation &&)=default
Approximation & operator= (const Approximation &)=default
Approximation & operator= (Approximation &&)=default
Additional Inherited Members
Protected Attributes inherited from MeshCore::Approximation
std::list< Base::Vector3f > _vPoints
bool _bIsFitted {false}
float _fLastResult {FLOAT_MAX}
Detailed Description
Best-fit sphere for a given set of points.
Definition at line 59 of file SphereFit.h.
Constructor & Destructor Documentation
SphereFit()
SphereFit::SphereFit ()
Construction
Definition at line 36 of file SphereFit.cpp.
Member Function Documentation
addObservationU()
void SphereFit::addObservationU (double a[4], double li, double pi, Matrix4x4 & atpa, Eigen::VectorXd & atpl) const protected
Computes contribution of the given observation equation on the normal equation matrices
Definition at line 338 of file SphereFit.cpp.
References a, SplineSurface::i, and ClipperLib::pi.
Referenced by setupNormalEquationMatrices().
ComputeApproximations()
void SphereFit::ComputeApproximations ()
Compute approximations for the parameters using all points
Definition at line 156 of file SphereFit.cpp.
References MeshCore::Approximation::_bIsFitted, MeshCore::Approximation::_fLastResult, MeshCore::Approximation::_vPoints, KDL::diff(), FLOAT_MAX, Base::Vector3< float_type >::Set(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by Fit(), and MeshCore::SphereFit::Fit().
computeResiduals()
bool SphereFit::computeResiduals (const Eigen::VectorXd & x, std::vector< Base::Vector3d > & residuals, double & sigma0, double vConvLimit, bool & vConverged) const protected
Compute the residuals and sigma0 and check the residual convergence
Definition at line 367 of file SphereFit.cpp.
References MeshCore::Approximation::_vPoints, a, SCL.SimpleDataTypes::b, SplineSurface::i, setupObservation(), KDL::sqrt(), TestSpreadsheet::v, and MovieTool::x.
Referenced by Fit().
Fit()
float SphereFit::Fit () override virtual
Fit a sphere onto the given points. If the fit fails FLOAT_MAX is returned.
Implements MeshCore::Approximation.
Definition at line 182 of file SphereFit.cpp.
References MeshCore::Approximation::_bIsFitted, MeshCore::Approximation::_fLastResult, ComputeApproximations(), computeResiduals(), MeshCore::Approximation::CountPoints(), FLOAT_MAX, setupNormalEquationMatrices(), GCS::Success, MovieTool::x, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by MeshCore::SphereFit::Fit().
GetCenter()
Base::Vector3d SphereFit::GetCenter () const
Returns the center of the fitted sphere. If Fit() has not been called the null vector is returned.
Definition at line 75 of file SphereFit.cpp.
References MeshCore::Approximation::_bIsFitted.
Referenced by MeshCore::SphereFit::Fit().
GetDistanceToSphere()
float SphereFit::GetDistanceToSphere (const Base::Vector3f & rcPoint) const
Returns the distance from the point rcPoint to the fitted sphere. If Fit() has not been called FLOAT_MAX is returned.
Definition at line 93 of file SphereFit.cpp.
References MeshCore::Approximation::_bIsFitted, FLOAT_MAX, Base::Vector3< float_type >::Length(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by GetStdDeviation().
GetNumIterations()
int SphereFit::GetNumIterations () const
Returns the number of iterations that Fit() needed to converge. If Fit() has not been called then zero is returned.
Definition at line 84 of file SphereFit.cpp.
References MeshCore::Approximation::_bIsFitted.
Referenced by MeshCore::SphereFit::Fit().
GetRadius()
double SphereFit::GetRadius () const
Returns the radius of the fitted sphere. If Fit() has not been called then zero is returned.
Definition at line 66 of file SphereFit.cpp.
References MeshCore::Approximation::_bIsFitted.
Referenced by MeshCore::SphereFit::Fit().
GetStdDeviation()
float SphereFit::GetStdDeviation () const
Returns the standard deviation from the points to the fitted sphere. If Fit() has not been called FLOAT_MAX is returned.
Definition at line 106 of file SphereFit.cpp.
References MeshCore::Approximation::_bIsFitted, MeshCore::Approximation::_vPoints, MeshCore::Approximation::CountPoints(), DraftVecUtils::dist(), FLOAT_MAX, GetDistanceToSphere(), and KDL::sqrt().
Referenced by MeshCore::SphereFit::Fit().
ProjectToSphere()
void SphereFit::ProjectToSphere ()
Projects the points onto the fitted sphere.
Definition at line 127 of file SphereFit.cpp.
References MeshCore::Approximation::_vPoints, KDL::diff(), length(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
SetApproximations()
void SphereFit::SetApproximations (double radius, const Base::Vector3d & center)
Set approximations before calling Fit()
Definition at line 41 of file SphereFit.cpp.
References MeshCore::Approximation::_bIsFitted, MeshCore::Approximation::_fLastResult, exportCSG::center(), and FLOAT_MAX.
SetConvergenceCriteria()
void SphereFit::SetConvergenceCriteria (double posConvLimit, double vConvLimit, int maxIter)
Set iteration convergence criteria for the fit if special values are needed. The default values set in the constructor are suitable for most uses
Definition at line 52 of file SphereFit.cpp.
setLowerPart()
void SphereFit::setLowerPart (Matrix4x4 & atpa) const protected
Set the lower part of the normal matrix equal to the upper part
Definition at line 357 of file SphereFit.cpp.
References SplineSurface::i.
Referenced by setupNormalEquationMatrices().
setupNormalEquationMatrices()
void SphereFit::setupNormalEquationMatrices (const std::vector< Base::Vector3d > & residuals, Matrix4x4 & atpa, Eigen::VectorXd & atpl) const protected
Set up the normal equations
Definition at line 257 of file SphereFit.cpp.
References MeshCore::Approximation::_vPoints, a, addObservationU(), SCL.SimpleDataTypes::b, setLowerPart(), and setupObservation().
Referenced by Fit().
setupObservation()
void SphereFit::setupObservation (const Base::Vector3f & point, const Base::Vector3d & residual, double a[4], double & f0, double & qw, double b[3]) const protected
Sets up contributions of given observation to the normal equation matrices.
Definition at line 288 of file SphereFit.cpp.
References a, SCL.SimpleDataTypes::b, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by computeResiduals(), and setupNormalEquationMatrices().
The documentation for this class was generated from the following files:
SphereFit.h
SphereFit.cpp