FreeCAD: Gui::TaskView::TaskSelectLinkProperty Class Reference
Gui::TaskView::TaskSelectLinkProperty Class Reference
#include <TaskSelectLinkProperty.h>
Signals
void emitSelectionFit ()
void emitSelectionMisfit ()
Public Member Functions
TaskSelectLinkProperty (const char *, App::Property *, QWidget *parent=nullptr)
~TaskSelectLinkProperty () override
void OnChange (Gui::SelectionSingleton::SubjectType &rCaller, Gui::SelectionSingleton::MessageType Reason) override
Observer message from the Selection.
bool setFilter (const char *)
set the filter criterion (same as in constructor)
void activate ()
set the TaskSelectLinkProperty active, means setting the selection and control it
bool accept ()
call this to accept the changes the user has made and send back to the Property (Ok)
bool reject ()
This discards the changes of the user and leaves the Property untouched (Cancel)
void sendSelection2Property ()
send the selection to the Property for e.g. forced recomputation of a feature
bool isSelectionValid () const
checks if the filter is currently met
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Protected Member Functions
void changeEvent (QEvent *e) override
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
General Link/Selection editor for the Task view This can be used as part of a TaskDialog to alter the content of a LinkProperty by user input/selection. If set active it reflects the selection to the Property given and acts due the selection filter given to the constructor. It will allow only allowed elements to be selected (SelectionFilter) and shows by the background color if the selection criterion is met. With the call of accept() or reject() the result gets permanent or discarded in the given Property.
Definition at line 54 of file TaskSelectLinkProperty.h.
Constructor & Destructor Documentation
TaskSelectLinkProperty()
TaskSelectLinkProperty::TaskSelectLinkProperty (const char * sFilter, App::Property * prop, QWidget * parent = nullptr)
Definition at line 40 of file TaskSelectLinkProperty.cpp.
References Base::Subject< MsgType >::Attach(), Gui::BitmapFactory(), Base::Console(), QSint::ActionGroup::groupLayout(), Base::BaseClass::isDerivedFrom(), Gui::Selection(), setFilter(), and Base::ConsoleSingleton::Warning().
~TaskSelectLinkProperty()
TaskSelectLinkProperty::~TaskSelectLinkProperty () override
Definition at line 85 of file TaskSelectLinkProperty.cpp.
References Base::Subject< MsgType >::Detach(), and Gui::Selection().
Member Function Documentation
accept()
bool Gui::TaskView::TaskSelectLinkProperty::accept ()
call this to accept the changes the user has made and send back to the Property (Ok)
Referenced by RobotGui::TaskDlgTrajectoryCompound::accept(), RobotGui::TaskDlgEdge2Trac::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
activate()
void Gui::TaskView::TaskSelectLinkProperty::activate ()
set the TaskSelectLinkProperty active, means setting the selection and control it
Referenced by RobotGui::TaskDlgTrajectoryCompound::open(), RobotGui::TaskDlgEdge2Trac::open(), ArchBuildingPart.ViewProviderBuildingPart::setEdit(), nativeifc.ifc_viewproviders.ifc_vp_object::setupContextMenu(), and ArchBuildingPart.ViewProviderBuildingPart::setupContextMenu().
changeEvent()
void TaskSelectLinkProperty::changeEvent (QEvent * e) override protected
Definition at line 105 of file TaskSelectLinkProperty.cpp.
References SCL.SimpleDataTypes::e.
emitSelectionFit
void Gui::TaskView::TaskSelectLinkProperty::emitSelectionFit () signal
emitSelectionMisfit
void Gui::TaskView::TaskSelectLinkProperty::emitSelectionMisfit () signal
isSelectionValid()
bool Gui::TaskView::TaskSelectLinkProperty::isSelectionValid () const inline
checks if the filter is currently met
Definition at line 78 of file TaskSelectLinkProperty.h.
Referenced by RobotGui::TaskDlgTrajectoryCompound::accept(), RobotGui::TaskDlgEdge2Trac::accept(), and RobotGui::TaskDlgEdge2Trac::clicked().
OnChange()
void Gui::TaskView::TaskSelectLinkProperty::OnChange (Gui::SelectionSingleton::SubjectType & rCaller, Gui::SelectionSingleton::MessageType Reason) override
Observer message from the Selection.
reject()
bool Gui::TaskView::TaskSelectLinkProperty::reject ()
This discards the changes of the user and leaves the Property untouched (Cancel)
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), RobotGui::TaskDlgTrajectoryCompound::reject(), RobotGui::TaskDlgEdge2Trac::reject(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
sendSelection2Property()
void Gui::TaskView::TaskSelectLinkProperty::sendSelection2Property ()
send the selection to the Property for e.g. forced recomputation of a feature
Referenced by RobotGui::TaskDlgEdge2Trac::clicked().
setFilter()
bool Gui::TaskView::TaskSelectLinkProperty::setFilter (const char *)
set the filter criterion (same as in constructor)
Referenced by TaskSelectLinkProperty().
The documentation for this class was generated from the following files:
TaskSelectLinkProperty.h
TaskSelectLinkProperty.cpp