FreeCAD: TechDraw::PATLineSpec Class Reference
TechDraw::PATLineSpec Class Reference
PATLineSpec is the result of parsing a singleline from PAT file into accessible parameters.
#include <HatchLine.h>
Public Member Functions
PATLineSpec ()
PATLineSpec (std::string &lineSpec)
~PATLineSpec ()
void load (std::string &lineSpec)
double getAngle ()
Base::Vector3d getOrigin ()
double getInterval ()
double getIntervalX ()
X component of distance between lines.
double getIntervalY ()
Y component of distance between lines.
double getOffset ()
double getSlope ()
double getLength ()
DashSpec getDashParms ()
bool isDashed ()
void dump (const char *title)
Static Public Member Functions
static std::vector< PATLineSpec > getSpecsForPattern (std::string &parmFile, std::string &parmName)
static bool findPatternStart (std::ifstream &inFile, std::string &parmName)
static std::vector< std::string > loadPatternDef (std::ifstream &inFile)
static std::vector< std::string > getPatternList (std::string &parmFile)
Detailed Description
PATLineSpec is the result of parsing a singleline from PAT file into accessible parameters.
Definition at line 71 of file HatchLine.h.
Constructor & Destructor Documentation
PATLineSpec() [1/2]
PATLineSpec::PATLineSpec ()
Definition at line 217 of file HatchLine.cpp.
PATLineSpec() [2/2]
PATLineSpec::PATLineSpec (std::string & lineSpec) explicit
Definition at line 222 of file HatchLine.cpp.
References load().
~PATLineSpec()
PATLineSpec::~PATLineSpec ()
Definition at line 229 of file HatchLine.cpp.
Member Function Documentation
dump()
void PATLineSpec::dump (const char * title)
Definition at line 278 of file HatchLine.cpp.
References Base::Console(), TechDraw::DashSpec::dump(), TechDraw::DrawUtil::formatVector(), Base::ConsoleSingleton::Message(), and Plot::title().
findPatternStart()
bool PATLineSpec::findPatternStart (std::ifstream & inFile, std::string & parmName) static
Definition at line 322 of file HatchLine.cpp.
References importOCA::getline().
Referenced by getSpecsForPattern().
getAngle()
double TechDraw::PATLineSpec::getAngle () inline
Definition at line 80 of file HatchLine.h.
Referenced by TechDraw::LineSet::calcApparentStart(), getIntervalX(), getIntervalY(), getSlope(), and TechDraw::DrawGeomHatch::makeEdgeOverlay().
getDashParms()
DashSpec TechDraw::PATLineSpec::getDashParms () inline
Definition at line 88 of file HatchLine.h.
getInterval()
double TechDraw::PATLineSpec::getInterval () inline
Definition at line 82 of file HatchLine.h.
Referenced by getIntervalX(), getIntervalY(), and TechDraw::DrawGeomHatch::makeEdgeOverlay().
getIntervalX()
double PATLineSpec::getIntervalX ()
X component of distance between lines.
Definition at line 421 of file HatchLine.cpp.
References KDL::cos(), getAngle(), getInterval(), and M_PI.
Referenced by TechDraw::DrawGeomHatch::makeEdgeOverlay().
getIntervalY()
double PATLineSpec::getIntervalY ()
Y component of distance between lines.
Definition at line 434 of file HatchLine.cpp.
References getAngle(), getInterval(), M_PI, and KDL::tan().
getLength()
double TechDraw::PATLineSpec::getLength () inline
Definition at line 87 of file HatchLine.h.
getOffset()
double TechDraw::PATLineSpec::getOffset () inline
Definition at line 85 of file HatchLine.h.
getOrigin()
Base::Vector3d TechDraw::PATLineSpec::getOrigin () inline
Definition at line 81 of file HatchLine.h.
Referenced by TechDraw::DrawGeomHatch::makeEdgeOverlay().
getPatternList()
std::vector< std::string > PATLineSpec::getPatternList (std::string & parmFile) static
Definition at line 372 of file HatchLine.cpp.
References Base::Console(), importOCA::getline(), Base::ConsoleSingleton::Message(), Base::ifstream::open(), and result.
getSlope()
double PATLineSpec::getSlope ()
Definition at line 402 of file HatchLine.cpp.
References getAngle(), M_PI, and KDL::tan().
Referenced by TechDraw::LineSet::calcApparentStart(), and TechDraw::DrawGeomHatch::makeEdgeOverlay().
getSpecsForPattern()
std::vector< PATLineSpec > PATLineSpec::getSpecsForPattern (std::string & parmFile, std::string & parmName) static
Definition at line 295 of file HatchLine.cpp.
References Base::Console(), findPatternStart(), RobotExample::l, loadPatternDef(), Base::ConsoleSingleton::Message(), Base::ifstream::open(), and result.
Referenced by TechDraw::DrawGeomHatch::getDecodedSpecsFromFile().
isDashed()
bool PATLineSpec::isDashed ()
Definition at line 415 of file HatchLine.cpp.
References TechDraw::DashSpec::empty().
Referenced by TechDraw::LineSet::isDashed().
load()
void PATLineSpec::load (std::string & lineSpec)
Definition at line 241 of file HatchLine.cpp.
References Base::Console(), and Base::ConsoleSingleton::Message().
Referenced by PATLineSpec().
loadPatternDef()
std::vector< std::string > PATLineSpec::loadPatternDef (std::ifstream & inFile) static
Definition at line 352 of file HatchLine.cpp.
References importOCA::getline(), and result.
Referenced by getSpecsForPattern().
The documentation for this class was generated from the following files:
HatchLine.h
HatchLine.cpp