FreeCAD: Gui::ViewProviderLink Class Reference
Gui::ViewProviderLink Class Reference
#include <ViewProviderLink.h>
Classes
struct DraggerContext
Public Member Functions
ViewProviderLink ()
~ViewProviderLink () override
void attach (App::DocumentObject *pcObj) override
void reattach (App::DocumentObject *pcObj) override
bool isSelectable () const override
bool useNewSelectionModel () const override
indicates if the ViewProvider use the new Selection model
void updateData (const App::Property *) override
void onChanged (const App::Property *prop) override
Gets called by the container whenever a property has been changed.
std::vector< App::DocumentObject * > claimChildren () const override
bool getElementPicked (const SoPickedPoint *, std::string &) const override
return a hit element given the picked point which contains the full node path
bool getDetailPath (const char *, SoFullPath *, bool, SoDetail *&) const override
return the coin node detail and path to the node of the subname
void finishRestoring () override
QIcon getIcon () const override
deliver the icon shown in the tree view
bool canDragObjects () const override
bool canDragObject (App::DocumentObject *) const override
void dragObject (App::DocumentObject *) override
bool canDropObjects () const override
bool canDragAndDropObject (App::DocumentObject *) const override
bool canDropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &subElements) const override
std::string dropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *subname, const std::vector< std::string > &subElements) override
bool onDelete (const std::vector< std::string > &) override
bool canDelete (App::DocumentObject *obj) const override
Asks the view provider if the given object can be deleted.
std::vector< std::string > getDisplayModes () const override
returns a list of all possible display modes
void setupContextMenu (QMenu *, QObject *, const char *) override
set up the context-menu with the supported edit modes
virtual QPixmap getOverlayPixmap () const
ViewProvider * startEditing (int ModNum) override
bool doubleClicked () override
is called by the tree if the user double clicks on the object
PyObject * getPyObject () override
Get the python wrapper for that ViewProvider.
PyObject * getPyLinkView ()
std::map< std::string, App::Color > getElementColors (const char *subname=nullptr) const override
void setElementColors (const std::map< std::string, App::Color > &colors) override
void setOverrideMode (const std::string &mode) override
Overrides the display mode with mode.
void onBeforeChange (const App::Property *) override
get called before the value is changed
ViewProviderDocumentObject * getChildViewProvider () const
App::Property * getPropertyByName (const char *name) const override
find a property by its name
void getPropertyMap (std::map< std::string, App::Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< App::Property * > &List) const override
get all properties of the class (including properties of the parent)
ViewProviderDocumentObject * getLinkedViewProvider (std::string *subname=nullptr, bool recursive=false) const override
bool allowOverride (const App::DocumentObject &) const override
void setTransformation (const Base::Matrix4D &rcMatrix) override
set the viewing transformation of the provider
void setTransformation (const SbMatrix &rcMatrix) override
Public Member Functions inherited from Gui::ViewProviderDragger
ViewProviderDragger ()
constructor.
~ViewProviderDragger () override
destructor.
Base::Placement getTransformOrigin () const
Convenience method to obtain the transform origin.
void setTransformOrigin (const Base::Placement &placement)
Convenience method to set the transform origin.
void resetTransformOrigin ()
Resets transform origin to the object origin.
void updatePlacementFromDragger ()
updates placement of object based on dragger position
void updateTransformFromDragger ()
updates transform of object based on dragger position, can be used to preview movement
Base::Placement getObjectPlacement () const
Gets object placement relative to its coordinate system.
Base::Placement getDraggerPlacement () const
Gets current dragger placement, including current dragger movement.
Base::Placement getOriginalDraggerPlacement () const
Gets original dragger placement, without current dragger movement.
void setDraggerPlacement (const Base::Placement &placement)
Sets placement of dragger relative to objects origin.
Public Member Functions inherited from Gui::ViewProviderDocumentObject
ViewProviderDocumentObject ()
constructor.
~ViewProviderDocumentObject () override
destructor.
void update (const App::Property *) override
void setActiveMode ()
Set the active mode, i.e. the first item of the 'Display' property.
void hide () override
Hide the object in the view.
void show () override
Show the object in the view.
const char * getTransactionText () const override
int replaceObject (App::DocumentObject *, App::DocumentObject *) override
bool showInTree () const override
void getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &) const override
Get a list of TaskBoxes associated with this object.
void updateView ()
Run a redraw.
App::DocumentObject * getObject () const
Get the object of this ViewProvider object.
template<class T >
T * getObject () const
Get the object of this ViewProvider object as specified type.
virtual bool acceptDeletionsInEdit ()
Ask the view provider if it accepts object deletions while in edit.
Gui::Document * getDocument () const
Get the GUI document to this ViewProvider object.
virtual void forceUpdate (bool enable=true)
virtual bool isUpdateForced () const
virtual void startRestoring ()
int getTreeRank () const
void setTreeRank (int value)
bool removeDynamicProperty (const char *prop) override
App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
std::string getFullName () const override
void setShowable (bool enable)
bool isShowable () const
void startDefaultEditMode ()
Public Member Functions inherited from Gui::ViewProvider
ViewProvider ()
constructor.
~ViewProvider () override
destructor.
virtual SoSeparator * getRoot () const
SoSwitch * getModeSwitch () const
SoTransform * getTransformNode () const
SoSeparator * getAnnotation ()
virtual SoSeparator * getFrontRoot () const
virtual SoGroup * getChildRoot () const
virtual SoSeparator * getBackRoot () const
virtual bool canAddToSceneGraph () const
Indicate whether to be added to scene graph or not.
virtual bool isPartOfPhysicalObject () const
virtual std::vector< App::DocumentObject * > claimChildren3D () const
virtual std::string getElement (const SoDetail *) const
return a hit element to the selection path or 0
virtual SoDetail * getDetail (const char *) const
return the coin node detail of the subelement
int partialRender (const std::vector< std::string > &subelements, bool clear)
virtual std::vector< Base::Vector3d > getModelPoints (const SoPickedPoint *) const
virtual std::vector< Base::Vector3d > getSelectionShape (const char *Element) const
return the highlight lines for a given element or the whole shape
Base::BoundBox3d getBoundingBox (const char *subname=nullptr, bool transform=true, MDIView *view=nullptr) const
virtual void beforeDelete ()
virtual bool canDragObjectToTarget (App::DocumentObject *obj, App::DocumentObject *target) const
virtual bool canDropObject (App::DocumentObject *) const
virtual void dropObject (App::DocumentObject *)
virtual bool acceptReorderingObjects () const
virtual std::string getDropPrefix () const
return a subname referencing the sub-object holding the dropped objects
virtual bool canRemoveChildrenFromRoot () const
std::string getActiveDisplayMode () const
virtual void setDisplayMode (const char *ModeName)
set the display mode
virtual const char * getDefaultDisplayMode () const
get the default display mode
virtual bool isShow () const
checks whether the view provider is visible or not
void setVisible (bool)
bool isVisible () const
void setLinkVisible (bool)
bool isLinkVisible () const
const std::string getOverrideMode ()
virtual bool selectAll ()
virtual bool keyPressed (bool pressed, int key)
is called when the provider is in edit and a key event occurs. Only ESC ends edit.
virtual bool mouseMove (const SbVec2s &cursorPos, View3DInventorViewer *viewer)
is called when the provider is in edit and the mouse is moved
virtual bool mouseButtonPressed (int button, bool pressed, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
is called when the Provider is in edit and the mouse is clicked
virtual bool mouseWheelEvent (int delta, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
virtual QIcon mergeColorfulOverlayIcons (const QIcon &orig) const
virtual std::vector< App::DocumentObject * > claimChildrenRecursive () const
bool isUpdatesEnabled () const
void setUpdatesEnabled (bool enable)
unsigned long getStatus () const
return the status bits
bool testStatus (ViewStatus pos) const
void setStatus (ViewStatus pos, bool on)
std::string toString () const
bool isEditing () const
void finishEditing ()
virtual MDIView * getMDIView () const
void Restore (Base::XMLReader &reader) override
bool isRestoring ()
void addDisplayMaskMode (SoNode *node, const char *type)
Adds a new display mask mode.
void setDisplayMaskMode (const char *type)
Activates the display mask mode type.
SoNode * getDisplayMaskMode (const char *type) const
Get the node to the display mask mode type.
std::vector< std::string > getDisplayMaskModes () const
Returns a list of added display mask modes.
void setDefaultMode (int)
int getDefaultMode () const
virtual void setRenderCacheMode (int)
Public Member Functions inherited from App::TransactionalObject
TransactionalObject ()
Constructor.
~TransactionalObject () override
Public Member Functions inherited from App::ExtensionContainer
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
Property * getPropertyByName (const char *name) const override
find a property by its name
template<typename T >
T * getPropertyByName (const char *name) const
find a property by its name, dynamic cased to specified type
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void onChanged (const Property *) override
get called by the container when a property has changed
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop) override
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static void updateLinks (ViewProvider *vp)
Static Public Member Functions inherited from Gui::ViewProviderDragger
static void updateTransform (const Base::Placement &from, SoTransform *to)
Static Public Member Functions inherited from Gui::ViewProvider
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
static SbMatrix convert (const Base::Matrix4D &rcMatrix)
static Base::Matrix4D convert (const SbMatrix &sbMat)
static void eventCallback (void *ud, SoEventCallback *node)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes
App::PropertyBool OverrideMaterial
App::PropertyMaterial ShapeMaterial
App::PropertyEnumeration DrawStyle
App::PropertyFloatConstraint LineWidth
App::PropertyFloatConstraint PointSize
App::PropertyMaterialList MaterialList
App::PropertyBoolList OverrideMaterialList
App::PropertyBool Selectable
App::PropertyColorList OverrideColorList
App::PropertyPersistentObject ChildViewProvider
Public Attributes inherited from Gui::ViewProviderDragger
App::PropertyPlacement TransformOrigin
Public Attributes inherited from Gui::ViewProviderDocumentObject
App::PropertyEnumeration DisplayMode
App::PropertyBool Visibility
App::PropertyBool ShowInTree
App::PropertyEnumeration OnTopWhenSelected
App::PropertyEnumeration SelectionStyle
Public Attributes inherited from Gui::ViewProvider
boost::signals2::signal< void()> signalChangeIcon
signal on icon change
boost::signals2::signal< void(const QString &)> signalChangeToolTip
signal on tooltip change
boost::signals2::signal< void(const QString &)> signalChangeStatusTip
signal on status tip change
boost::signals2::signal< void(bool, Gui::HighlightMode)> signalChangeHighlight
signal on highlight change
Protected Types
enum LinkType { LinkTypeNone, LinkTypeNormal, LinkTypeSubs }
Protected Member Functions
bool setEdit (int ModNum) override
is called by the document when the provider goes in edit mode
void setEditViewer (View3DInventorViewer *, int ModNum) override
adjust viewer settings when editing a view provider
void unsetEditViewer (View3DInventorViewer *) override
restores viewer settings when leaving editing mode
bool linkEdit (const App::LinkBaseExtension *ext=nullptr) const
void _setupContextMenu (App::LinkBaseExtension *ext, QMenu *, QObject *, const char *)
bool hasElements (const App::LinkBaseExtension *ext=nullptr) const
bool isGroup (const App::LinkBaseExtension *ext=nullptr, bool plainGroup=false) const
const App::LinkBaseExtension * getLinkExtension () const
App::LinkBaseExtension * getLinkExtension ()
void updateDataPrivate (App::LinkBaseExtension *ext, const App::Property *)
void updateElementList (App::LinkBaseExtension *ext)
bool setLinkType (App::LinkBaseExtension *ext)
void onChangeIcon () const
std::vector< App::DocumentObject * > claimChildrenPrivate () const
void applyMaterial ()
void applyColors ()
void checkIcon (const App::LinkBaseExtension *ext=nullptr)
ViewProvider * getLinkedView (bool real, const App::LinkBaseExtension *ext=nullptr) const
bool initDraggingPlacement ()
bool callDraggerProxy (const char *fname)
Protected Member Functions inherited from Gui::ViewProviderDragger
void unsetEdit (int ModNum) override
is called when you lose the edit mode
bool forwardToLink ()
virtual TaskView::TaskDialog * getTransformDialog ()
Protected Member Functions inherited from Gui::ViewProviderDocumentObject
Gui::MDIView * getActiveView () const
Gui::MDIView * getEditingView () const
Gui::MDIView * getInventorView () const
Gui::MDIView * getViewOfNode (SoNode *node) const
SoNode * findFrontRootOfType (const SoType &type) const
bool isAttachedToDocument () const override
const char * detachFromDocument () override
void onPropertyStatusChanged (const App::Property &prop, unsigned long oldStatus) override
get called when a property status has changed
void setModeSwitch () override
Turn on mode switch.
void addDefaultAction (QMenu *, const QString &)
Protected Member Functions inherited from Gui::ViewProvider
virtual QIcon mergeGreyableOverlayIcons (const QIcon &orig) const
int getEditingMode () const
return the edit mode or -1 if nothing is being edited
bool checkRecursion (SoNode *)
SoPickedPoint * getPointOnRay (const SbVec2s &pos, const View3DInventorViewer *viewer) const
SoPickedPoint * getPointOnRay (const SbVec3f &pos, const SbVec3f &dir, const View3DInventorViewer *viewer) const
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual void onEarlyChange (const Property *)
virtual const PropertyData & getPropertyData () const
Protected Attributes
LinkView * linkView
LinkType linkType
bool hasSubName
bool hasSubElement
std::unique_ptr< DraggerContext > dragCtx
ViewProviderDocumentObject * childVp
LinkInfoPtr childVpLink
qint64 overlayCacheKey
Protected Attributes inherited from Gui::ViewProviderDragger
CoinPtr< SoFCCSysDragger > csysDragger = nullptr
ViewProvider * forwardedViewProvider = nullptr
Protected Attributes inherited from Gui::ViewProviderDocumentObject
App::DocumentObject * pcObject {nullptr}
Gui::Document * pcDocument {nullptr}
Protected Attributes inherited from Gui::ViewProvider
SoSeparator * pcRoot
The root Separator of the ViewProvider.
SoTransform * pcTransform
this is transformation for the provider
const char * sPixmap
SoSwitch * pcModeSwitch
this is the mode switch, all the different viewing modes are collected here
SoSeparator * pcAnnotation {nullptr}
The root separator for annotations.
ViewProviderPy * pyViewObject {nullptr}
std::string overrideMode
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Additional Inherited Members
Public Types inherited from Gui::ViewProvider
enum EditMode { Default = 0, Transform, Cutting, Color }
Public Types inherited from App::ExtensionContainer
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 187 of file ViewProviderLink.h.
Member Enumeration Documentation
LinkType
enum Gui::ViewProviderLink::LinkType protected
Enumerator
LinkTypeNone
LinkTypeNormal
LinkTypeSubs
Definition at line 282 of file ViewProviderLink.h.
Constructor & Destructor Documentation
ViewProviderLink()
ViewProviderLink::ViewProviderLink ()
Definition at line 1625 of file ViewProviderLink.cpp.
References _LinkIcon, ADD_PROPERTY, ADD_PROPERTY_TYPE, App::Material::DEFAULT, App::Material::diffuseColor, Gui::ViewParams::getDefaultShapeLineWidth(), App::Property::Hidden, Gui::ViewParams::instance(), App::Property::MaterialEdit, App::Property::NoMaterialListEdit, App::Prop_None, and App::Color::setPackedValue().
~ViewProviderLink()
ViewProviderLink::~ViewProviderLink () override
Definition at line 1667 of file ViewProviderLink.cpp.
References linkView, and Gui::LinkView::setInvalid().
Member Function Documentation
_setupContextMenu()
void ViewProviderLink::_setupContextMenu (App::LinkBaseExtension * ext, QMenu * menu, QObject * receiver, const char * member) protected
Definition at line 2582 of file ViewProviderLink.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::BitmapFactory(), Gui::ViewProvider::Color, Gui::Application::commandManager(), SCL.SimpleDataTypes::e, create_qrc::ext, Gui::CommandManager::getCommandByName(), Gui::LinkView::getLinkedView(), Gui::Application::Instance, linkEdit(), linkView, NavigationIndicatorGui::menu, Gui::ViewProvider::mergeGreyableOverlayIcons(), Arch::QT_TRANSLATE_NOOP, Gui::ViewProvider::setupContextMenu(), Gui::ViewProvider::Transform, and Gui::Command::updateActive().
Referenced by setupContextMenu().
allowOverride()
bool Gui::ViewProviderLink::allowOverride (const App::DocumentObject &) const inline override virtual
Allow this class to be used as an override for the original view provider of the given object
See also
App::DocumentObject::getViewProviderNameOverride()
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 268 of file ViewProviderLink.h.
applyColors()
void ViewProviderLink::applyColors () protected
Definition at line 3177 of file ViewProviderLink.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::SoSelectionElementAction::Color, importers.importIFCmulticore::colors, create_qrc::ext, getDetailPath(), getElementColors(), getLinkExtension(), Gui::LinkView::getLinkRoot(), Gui::ViewProviderDocumentObject::getObject(), Gui::ViewProvider::hiddenMarker(), Gui::SoSelectionElementAction::Hide, linkView, App::DocumentObject::resolve(), and TestSpreadsheet::v.
Referenced by finishRestoring(), onChanged(), ArchFence._ViewProviderFence::onChanged(), ArchFence._ViewProviderFence::updateData(), updateDataPrivate(), and updateElementList().
applyMaterial()
void ViewProviderLink::applyMaterial () protected
Definition at line 2053 of file ViewProviderLink.cpp.
References Gui::LinkView::getSize(), App::PropertyListsT< T, ListT, ParentT >::getSize(), App::PropertyBool::getValue(), App::PropertyMaterial::getValue(), SplineSurface::i, linkView, MaterialList, OverrideMaterial, OverrideMaterialList, Gui::LinkView::setMaterial(), and ShapeMaterial.
Referenced by finishRestoring(), onChanged(), and updateDataPrivate().
attach()
void ViewProviderLink::attach (App::DocumentObject * pcObj) override virtual
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 1676 of file ViewProviderLink.cpp.
References Gui::ViewProvider::addDisplayMaskMode(), Gui::ViewProviderDocumentObject::attach(), checkIcon(), childVp, childVpLink, Gui::LinkInfo::get(), Base::Persistence::getClassTypeId(), App::DocumentObject::getFullName(), Gui::LinkView::getLinkRoot(), Gui::ViewProviderDocumentObject::hide(), Base::BaseClass::isDerivedFrom(), linkView, Gui::ViewProvider::setDisplayMaskMode(), Gui::LinkView::setOwner(), and Gui::LinkView::SnapshotTransform.
Referenced by Path.Dressup.Gui.Boundary.DressupPathBoundaryViewProvider::__init__().
callDraggerProxy()
bool ViewProviderLink::callDraggerProxy (const char * fname) protected
Definition at line 2864 of file ViewProviderLink.cpp.
References toolbit-attributes::args, Gui::ViewProviderDragger::csysDragger, SCL.SimpleDataTypes::e, getPropertyByName(), and getValue().
canDelete()
bool ViewProviderLink::canDelete (App::DocumentObject * obj) const override virtual
Asks the view provider if the given object can be deleted.
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 2405 of file ViewProviderLink.cpp.
References create_qrc::ext, getLinkedView(), getLinkExtension(), hasElements(), hasSubElement, and isGroup().
canDragAndDropObject()
bool ViewProviderLink::canDragAndDropObject (App::DocumentObject * obj) const override virtual
Return false to force drop only operation for a given object
Reimplemented from Gui::ViewProvider.
Definition at line 2280 of file ViewProviderLink.cpp.
References create_qrc::ext, App::DocumentObject::getDocument(), getLinkedView(), getLinkExtension(), Gui::ViewProviderDocumentObject::getObject(), hasElements(), hasSubName, isGroup(), and App::LinkBaseExtension::LinkModeAutoLink.
canDragObject()
bool ViewProviderLink::canDragObject (App::DocumentObject * obj) const override virtual
Check whether the object can be removed from the view provider by drag and drop
Reimplemented from Gui::ViewProvider.
Definition at line 2158 of file ViewProviderLink.cpp.
References create_qrc::ext, getLinkedView(), getLinkExtension(), hasElements(), and isGroup().
Referenced by draftviewproviders.view_layer.ViewProviderLayer::canDropObject().
canDragObjects()
bool ViewProviderLink::canDragObjects () const override virtual
Check whether children can be removed from the view provider by drag and drop
Reimplemented from Gui::ViewProvider.
Definition at line 2170 of file ViewProviderLink.cpp.
References create_qrc::ext, getLinkedView(), getLinkExtension(), hasElements(), and isGroup().
canDropObjectEx()
bool ViewProviderLink::canDropObjectEx (App::DocumentObject * obj, App::DocumentObject * owner, const char * subname, const std::vector< std::string > & elements) const override virtual
Query object dropping with full qualified name
Tree view now calls this function instead of canDropObject(), and may query for objects from other document. The default implementation (actually in ViewProviderDocumentObject) inhibites cross document dropping, and calls canDropObject(obj) for the rest. Override this function to enable cross document linking.
Parameters
obj the object being dropped
owner the (grand)parent object of the dropping object. Maybe null. This may not be the top parent object, as tree view will try to find a parent of the dropping object relative to this object to avoid cyclic dependency
subname subname reference to the dropping object
elements non-object sub-elements, e.g. Faces, Edges, selected when the object is being dropped
Returns
Return whether the dropping action is allowed.
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 2217 of file ViewProviderLink.cpp.
References create_qrc::ext, Gui::ViewProviderDocumentObject::getDocument(), App::DocumentObject::getDocument(), getLinkedView(), getLinkExtension(), Gui::ViewProviderDocumentObject::getObject(), hasElements(), hasSubName, isGroup(), Gui::LinkView::isLinked(), linkView, and Gui::ViewProviderDocumentObject::pcObject.
canDropObjects()
bool ViewProviderLink::canDropObjects () const override virtual
Check whether objects can be added to the view provider by drag and drop or drop only
Reimplemented from Gui::ViewProvider.
Definition at line 2201 of file ViewProviderLink.cpp.
References create_qrc::ext, getLinkedView(), getLinkExtension(), hasElements(), hasSubElement, hasSubName, and isGroup().
checkIcon()
void ViewProviderLink::checkIcon (const App::LinkBaseExtension * ext = nullptr) protected
Definition at line 2028 of file ViewProviderLink.cpp.
References _LinkElementIcon, _LinkGroupIcon, _LinkIcon, create_qrc::ext, getLinkExtension(), Gui::ViewProviderDocumentObject::getObject(), getOverlayPixmap(), overlayCacheKey, Gui::ViewProvider::signalChangeIcon, and Gui::ViewProvider::sPixmap.
Referenced by attach(), and updateDataPrivate().
claimChildren()
std::vector< App::DocumentObject * > ViewProviderLink::claimChildren () const override virtual
deliver the children belonging to this object this method is used to deliver the objects to the tree framework which should be grouped under its label. Obvious is the usage in the group but it can be used for any kind of grouping needed for a special purpose.
Reimplemented from Gui::ViewProvider.
Definition at line 2127 of file ViewProviderLink.cpp.
References create_qrc::ext, getLinkedView(), getLinkExtension(), hasElements(), hasSubName, and isGroup().
Referenced by femviewprovider.view_result_mechanical.VPResultMechanical::onDelete(), BOPTools.SplitFeatures.ViewProviderBooleanFragments::onDelete(), BOPTools.JoinFeatures.ViewProviderConnect::onDelete(), BOPTools.ToleranceFeatures.ViewProviderToleranceSet::onDelete(), femviewprovider.view_mesh_gmsh.VPMeshGmsh::onDelete(), CommandCreateView.ViewProviderExplodedView::onDelete(), CommandCreateSimulation.ViewProviderSimulation::onDelete(), BOPTools.SplitFeatures.ViewProviderSlice::onDelete(), and BOPTools.SplitFeatures.ViewProviderXOR::onDelete().
claimChildrenPrivate()
std::vector<App::DocumentObject*> Gui::ViewProviderLink::claimChildrenPrivate () const protected
doubleClicked()
bool ViewProviderLink::doubleClicked () override virtual
is called by the tree if the user double clicks on the object
Reimplemented from Gui::ViewProviderDragger.
Definition at line 2429 of file ViewProviderLink.cpp.
References Gui::ViewProvider::doubleClicked(), Gui::ViewProviderDocumentObject::getDocument(), Gui::LinkView::getLinkedView(), linkEdit(), linkView, Gui::Document::setEdit(), and Gui::ViewProvider::Transform.
dragObject()
void ViewProviderLink::dragObject (App::DocumentObject * obj) override virtual
Remove a child from the view provider by drag and drop
Reimplemented from Gui::ViewProvider.
Definition at line 2182 of file ViewProviderLink.cpp.
References create_qrc::ext, getLinkedView(), getLinkExtension(), hasElements(), SplineSurface::i, isGroup(), and replaceobj::objs.
dropObjectEx()
std::string ViewProviderLink::dropObjectEx (App::DocumentObject * obj, App::DocumentObject * owner, const char * subname, const std::vector< std::string > & elements) override virtual
Add an object with full qualified name to the view provider by drag and drop
Parameters
obj the object being dropped
owner the (grand)parent object of the dropping object. Maybe null. This may not be the top parent object, as tree view will try to find a parent of the dropping object relative to this object to avoid cyclic dependency
subname subname reference to the dropping object
elements non-object sub-elements, e.g. Faces, Edges, selected when the object is being dropped
Returns
Optionally returns a subname reference locating the dropped object, which may or may not be the actual dropped object, e.g. it may be a link.
Reimplemented from Gui::ViewProvider.
Definition at line 2246 of file ViewProviderLink.cpp.
References create_qrc::ext, getLinkedView(), getLinkExtension(), hasElements(), hasSubName, and isGroup().
finishRestoring()
void ViewProviderLink::finishRestoring () override virtual
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 2068 of file ViewProviderLink.cpp.
References applyColors(), applyMaterial(), childVp, create_qrc::ext, FC_TRACE, Gui::ViewProviderDocumentObject::finishRestoring(), Gui::ViewProviderDocumentObject::getDocument(), getLinkExtension(), App::PropertyFloat::getValue(), LineWidth, linkView, PointSize, Gui::LinkView::setDrawStyle(), Gui::Document::signalChangedObject, and updateDataPrivate().
getChildViewProvider()
ViewProviderDocumentObject* Gui::ViewProviderLink::getChildViewProvider () const inline
Definition at line 257 of file ViewProviderLink.h.
getDetailPath()
bool ViewProviderLink::getDetailPath (const char * subname, SoFullPath * pPath, bool append, SoDetail *& det) const override virtual
return the coin node detail and path to the node of the subname
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 2330 of file ViewProviderLink.cpp.
References Path.Post.scripts.uccnc_post::append(), appendPath, childVpLink, dot(), DraftVecUtils::equals(), create_qrc::ext, Gui::ViewProvider::getDefaultMode(), getLinkExtension(), hasElements(), isGroup(), Gui::LinkView::linkGetDetailPath(), linkView, Gui::ViewProvider::pcModeSwitch, Gui::ViewProvider::pcRoot, and Gui::LinkView::SnapshotTransform.
Referenced by applyColors().
getDisplayModes()
std::vector< std::string > ViewProviderLink::getDisplayModes () const override virtual
returns a list of all possible display modes
Reimplemented from Gui::ViewProvider.
Definition at line 1701 of file ViewProviderLink.cpp.
References Gui::ViewProvider::getDisplayModes().
getElementColors()
std::map< std::string, App::Color > ViewProviderLink::getElementColors (const char * subname = nullptr) const override virtual
Reimplemented from Gui::ViewProvider.
Definition at line 2940 of file ViewProviderLink.cpp.
References SCL.SimpleDataTypes::c, importers.importIFCmulticore::colors, App::Material::diffuseColor, dot(), create_qrc::ext, App::DocumentObject::getLinkedObject(), getLinkExtension(), Gui::ViewProviderDocumentObject::getObject(), App::PropertyListsT< T, ListT, ParentT >::getSize(), App::PropertyBool::getValue(), App::PropertyMaterial::getValue(), Gui::Application::getViewProvider(), Gui::ViewProvider::hiddenMarker(), SplineSurface::i, Gui::Application::Instance, OverrideColorList, OverrideMaterial, RobotExample::pos, App::DocumentObject::resolve(), App::Color::setTransparency(), ShapeMaterial, importers.importIFCmulticore::subs, App::Material::transparency, and TestSpreadsheet::v.
Referenced by applyColors().
getElementPicked()
bool ViewProviderLink::getElementPicked (const SoPickedPoint * pp, std::string & subname) const override virtual
return a hit element given the picked point which contains the full node path
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 2298 of file ViewProviderLink.cpp.
References childVp, childVpLink, create_qrc::ext, App::LinkBaseExtension::getArrayIndex(), Gui::ViewProviderDocumentObject::getElementPicked(), getLinkExtension(), isGroup(), isSelectable(), Gui::LinkView::linkGetElementPicked(), linkView, and Gui::LinkView::SnapshotTransform.
getIcon()
QIcon ViewProviderLink::getIcon () const override virtual
deliver the icon shown in the tree view
Reimplemented from Gui::ViewProvider.
Definition at line 1709 of file ViewProviderLink.cpp.
References Gui::BitmapFactory(), create_qrc::ext, Gui::LinkView::getLinkedIcon(), getLinkExtension(), Gui::ViewProviderDocumentObject::getObject(), getOverlayPixmap(), linkView, nativeifc.ifc_viewproviders::overlay(), overlayCacheKey, Gui::BitmapFactoryInst::pixmap(), and Gui::ViewProvider::sPixmap.
Referenced by ArchAxisSystem.AxisSystemTaskPanel::update(), ArchWindow._ArchWindowTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), bimcommands.BimClassification.BIM_Classification::updateByMaterial(), bimcommands.BimClassification.BIM_Classification::updateByTree(), bimcommands.BimClassification.BIM_Classification::updateByType(), and bimcommands.BimClassification.BIM_Classification::updateDefault().
getLinkedView()
ViewProvider * ViewProviderLink::getLinkedView (bool real, const App::LinkBaseExtension * ext = nullptr) const protected
Definition at line 2115 of file ViewProviderLink.cpp.
References create_qrc::ext, App::DocumentObject::getLinkedObject(), getLinkExtension(), Gui::ViewProviderDocumentObject::getObject(), Gui::Application::getViewProvider(), and Gui::Application::Instance.
Referenced by canDelete(), canDragAndDropObject(), canDragObject(), canDragObjects(), canDropObjectEx(), canDropObjects(), claimChildren(), dragObject(), dropObjectEx(), and updateDataPrivate().
getLinkedViewProvider()
ViewProviderDocumentObject * ViewProviderLink::getLinkedViewProvider (std::string * subname = nullptr, bool recursive = false) const override virtual
Return the linked view object
This function is mainly used for GUI navigation (e.g. StdCmdLinkSelectLinked).
Parameters
subname output as the subname referencing the linked object
recursive whether to follow the link recursively
Returns
Returns the linked view provider. If none, it shall return itself.
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 3301 of file ViewProviderLink.cpp.
References create_qrc::ext, getLinkExtension(), Gui::Application::Instance, and toolbit-attributes::s.
Referenced by getPropertyByName().
getLinkExtension() [1/2]
App::LinkBaseExtension* Gui::ViewProviderLink::getLinkExtension () protected
getLinkExtension() [2/2]
const App::LinkBaseExtension * ViewProviderLink::getLinkExtension () const protected
Definition at line 1803 of file ViewProviderLink.cpp.
References App::ExtensionContainer::getExtensionByType(), App::DocumentObject::isAttachedToDocument(), and Gui::ViewProviderDocumentObject::pcObject.
Referenced by applyColors(), canDelete(), canDragAndDropObject(), canDragObject(), canDragObjects(), canDropObjectEx(), canDropObjects(), checkIcon(), claimChildren(), dragObject(), dropObjectEx(), finishRestoring(), getDetailPath(), getElementColors(), getElementPicked(), getIcon(), getLinkedView(), getLinkedViewProvider(), getOverlayPixmap(), hasElements(), initDraggingPlacement(), isGroup(), linkEdit(), onDelete(), setEdit(), setElementColors(), setOverrideMode(), setTransformation(), setupContextMenu(), startEditing(), and updateData().
getOverlayPixmap()
QPixmap ViewProviderLink::getOverlayPixmap () const virtual
Definition at line 1725 of file ViewProviderLink.cpp.
References Gui::BitmapFactory(), create_qrc::ext, getLinkExtension(), Gui::getMainWindow(), hasSubElement, hasSubName, and Gui::BitmapFactoryInst::pixmapFromSvg().
Referenced by checkIcon(), and getIcon().
getPropertyByName()
App::Property * ViewProviderLink::getPropertyByName (const char * name) const override virtual
find a property by its name
Reimplemented from App::PropertyContainer.
Definition at line 3259 of file ViewProviderLink.cpp.
References App::DocumentObject::canLinkProperties(), childVp, getLinkedViewProvider(), App::ExtensionContainer::getPropertyByName(), App::Property::Hidden, isExcludedProperties(), and Gui::ViewProviderDocumentObject::pcObject.
Referenced by callDraggerProxy(), and initDraggingPlacement().
getPropertyList()
void ViewProviderLink::getPropertyList (std::vector< App::Property * > & List) const override virtual
get all properties of the class (including properties of the parent)
Reimplemented from App::PropertyContainer.
Definition at line 3293 of file ViewProviderLink.cpp.
References getPropertyMap(), and TestSpreadsheet::v.
getPropertyMap()
void ViewProviderLink::getPropertyMap (std::map< std::string, App::Property * > & Map) const override virtual
get all properties of the class (including properties of the parent)
Reimplemented from App::PropertyContainer.
Definition at line 3277 of file ViewProviderLink.cpp.
References childVp, App::ExtensionContainer::getPropertyMap(), App::Property::Hidden, and TestSpreadsheet::v.
Referenced by getPropertyList().
getPyLinkView()
PyObject * ViewProviderLink::getPyLinkView ()
Definition at line 2936 of file ViewProviderLink.cpp.
References Gui::LinkView::getPyObject(), and linkView.
getPyObject()
PyObject * ViewProviderLink::getPyObject () override virtual
Get the python wrapper for that ViewProvider.
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 2929 of file ViewProviderLink.cpp.
References Gui::ViewProvider::pyViewObject.
hasElements()
bool ViewProviderLink::hasElements (const App::LinkBaseExtension * ext = nullptr) const protected
Definition at line 2095 of file ViewProviderLink.cpp.
References create_qrc::ext, and getLinkExtension().
Referenced by canDelete(), canDragAndDropObject(), canDragObject(), canDragObjects(), canDropObjectEx(), canDropObjects(), claimChildren(), dragObject(), dropObjectEx(), getDetailPath(), and linkEdit().
initDraggingPlacement()
bool ViewProviderLink::initDraggingPlacement () protected
Definition at line 2648 of file ViewProviderLink.cpp.
References toolbit-attributes::doc, dragCtx, SCL.SimpleDataTypes::e, Gui::Application::editDocument(), create_qrc::ext, FC_ERR, Gui::ViewProvider::getBoundingBox(), getLinkExtension(), getPropertyByName(), App::PropertyPlacement::getValue(), getValue(), Gui::LinkView::hasSubs(), Gui::Application::Instance, Base::Placement::inverse(), linkView, and Base::Placement::toMatrix().
Referenced by startEditing().
isGroup()
bool ViewProviderLink::isGroup (const App::LinkBaseExtension * ext = nullptr, bool plainGroup = false) const protected
Definition at line 2105 of file ViewProviderLink.cpp.
References create_qrc::ext, and getLinkExtension().
Referenced by canDelete(), canDragAndDropObject(), canDragObject(), canDragObjects(), canDropObjectEx(), canDropObjects(), claimChildren(), dragObject(), dropObjectEx(), getDetailPath(), getElementPicked(), and linkEdit().
isSelectable()
bool ViewProviderLink::isSelectable () const override virtual
Reimplemented from Gui::ViewProvider.
Definition at line 1672 of file ViewProviderLink.cpp.
References App::PropertyBool::getValue(), and Selectable.
Referenced by getElementPicked().
linkEdit()
bool ViewProviderLink::linkEdit (const App::LinkBaseExtension * ext = nullptr) const protected
Definition at line 2415 of file ViewProviderLink.cpp.
References create_qrc::ext, getLinkExtension(), hasElements(), hasSubName, isGroup(), Gui::LinkView::isLinked(), and linkView.
Referenced by _setupContextMenu(), doubleClicked(), and startEditing().
onBeforeChange()
void ViewProviderLink::onBeforeChange (const App::Property * prop) override virtual
get called before the value is changed
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 3241 of file ViewProviderLink.cpp.
References Gui::ViewProvider::beforeDelete(), ChildViewProvider, childVp, childVpLink, Gui::LinkView::getLinkRoot(), linkView, Gui::ViewProviderDocumentObject::onBeforeChange(), and Gui::ViewProvider::pcModeSwitch.
onChanged()
void ViewProviderLink::onChanged (const App::Property * prop) override virtual
Gets called by the container whenever a property has been changed.
Reimplemented from Gui::ViewProviderDragger.
Definition at line 1738 of file ViewProviderLink.cpp.
References Gui::ViewProviderDocumentObject::allowOverride(), applyColors(), applyMaterial(), Gui::ViewProviderDocumentObject::attach(), ChildViewProvider, childVp, childVpLink, FC_ERR, Gui::LinkInfo::get(), Gui::ViewProviderDocumentObject::getFullName(), Base::Type::getName(), Gui::ViewProviderDocumentObject::getObject(), App::PropertyPersistentObject::getObject(), Base::Persistence::getTypeId(), App::PropertyFloat::getValue(), App::PropertyBool::getValue(), Gui::ViewProvider::isRestoring(), LineWidth, linkView, MaterialList, Gui::ViewProviderDragger::onChanged(), OverrideColorList, OverrideMaterial, OverrideMaterialList, Gui::ViewProvider::pcModeSwitch, PointSize, Gui::ViewProviderDocumentObject::setActiveMode(), Gui::LinkView::setDrawStyle(), App::PropertyContainer::setPropertyPrefix(), App::PropertyBool::setValue(), ShapeMaterial, Gui::LinkView::SnapshotTransform, Gui::ViewProviderDocumentObject::updateView(), and Gui::ViewProviderDocumentObject::Visibility.
Referenced by draftviewproviders.view_base.ViewProviderDraft::attach(), ArchSpace._ViewProviderSpace::onChanged(), ArchSchedule._ArchSchedule::setProperties(), draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), ArchAxis._ViewProviderAxis::updateData(), draftviewproviders.view_dimension.ViewProviderLinearDimension::updateData(), ArchSpace._ViewProviderSpace::updateData(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchSite._ViewProviderSite::updateData(), ArchSectionPlane._ViewProviderSectionPlane::updateData(), and ArchPanel.ViewProviderPanelSheet::updateData().
onChangeIcon()
void Gui::ViewProviderLink::onChangeIcon () const protected
onDelete()
bool ViewProviderLink::onDelete (const std::vector< std::string > & subNames) override virtual
Get called if the object is about to get deleted. Here you can delete other objects, switch their visibility or prevent the deletion of the object.
Parameters
subNames list of selected subelements
Returns
true if the deletion is approved by the view provider.
Reimplemented from Gui::ViewProvider.
Definition at line 2380 of file ViewProviderLink.cpp.
References toolbit-attributes::doc, create_qrc::ext, getLinkExtension(), and replaceobj::objs.
reattach()
void ViewProviderLink::reattach (App::DocumentObject * pcObj) override virtual
Reimplemented from Gui::ViewProviderDocumentObject.
Definition at line 1694 of file ViewProviderLink.cpp.
References childVp, linkView, Gui::ViewProviderDocumentObject::reattach(), and Gui::LinkView::setOwner().
setEdit()
bool ViewProviderLink::setEdit (int ModNum) override protected virtual
is called by the document when the provider goes in edit mode
Reimplemented from Gui::ViewProviderDragger.
Definition at line 2829 of file ViewProviderLink.cpp.
References Gui::ControlSingleton::activeDialog(), Gui::SelectionSingleton::clearSelection(), Gui::ViewProvider::Color, Gui::Control(), create_qrc::ext, getLinkExtension(), Gui::Selection(), Gui::ViewProviderDragger::setEdit(), and Gui::ControlSingleton::showDialog().
Referenced by Path.Base.Gui.PropertyBag.ViewProvider::doubleClicked(), Path.Base.Gui.SetupSheet.ViewProvider::doubleClicked(), Path.Tool.Gui.Bit.ViewProvider::doubleClicked(), Path.Base.Gui.IconViewProvider.ViewProvider::setupContextMenu(), Path.Tool.Gui.Controller.ViewProvider::setupContextMenu(), Path.Op.Gui.Base.ViewProvider::setupContextMenu(), and Path.Main.Gui.Job.ViewProvider::setupContextMenu().
setEditViewer()
void ViewProviderLink::setEditViewer (Gui::View3DInventorViewer * , int ModNum) override protected virtual
adjust viewer settings when editing a view provider
Reimplemented from Gui::ViewProviderDragger.
Definition at line 2847 of file ViewProviderLink.cpp.
References Gui::ViewProvider::Color, Gui::Control(), Gui::ViewProviderDragger::setEditViewer(), Gui::ControlSingleton::showDialog(), and OfflineRenderingUtils::viewer().
setElementColors()
void ViewProviderLink::setElementColors (const std::map< std::string, App::Color > & colors) override virtual
Reimplemented from Gui::ViewProvider.
Definition at line 3105 of file ViewProviderLink.cpp.
References importers.importIFCmulticore::colors, App::Material::diffuseColor, dot(), create_qrc::ext, getLinkExtension(), Gui::ViewProviderDocumentObject::getObject(), App::PropertyMaterial::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), OverrideColorList, OverrideMaterial, App::Property::setStatus(), App::PropertyBool::setValue(), App::PropertyMaterial::setValue(), App::PropertyListsT< T, ListT, ParentT >::setValues(), ShapeMaterial, importers.importIFCmulticore::subs, App::Color::transparency(), App::Property::User3, and TestSpreadsheet::v.
setLinkType()
bool ViewProviderLink::setLinkType (App::LinkBaseExtension * ext) protected
Definition at line 1777 of file ViewProviderLink.cpp.
References create_qrc::ext, hasSubName, linkType, LinkTypeNormal, LinkTypeSubs, linkView, Gui::LinkView::setNodeType(), Gui::LinkView::SnapshotContainer, Gui::LinkView::SnapshotContainerTransform, Gui::LinkView::SnapshotTransform, Gui::LinkView::SnapshotVisible, and Path.Post.scripts.grbl_post::type.
Referenced by updateDataPrivate().
setOverrideMode()
void ViewProviderLink::setOverrideMode (const std::string & mode) override virtual
Overrides the display mode with mode.
Reimplemented from Gui::ViewProvider.
Definition at line 3228 of file ViewProviderLink.cpp.
References childVp, create_qrc::ext, getLinkExtension(), Gui::ViewProviderDocumentObject::getObject(), Gui::Application::getViewProvider(), Gui::Application::Instance, and Gui::ViewProvider::setOverrideMode().
setTransformation() [1/2]
void ViewProviderLink::setTransformation (const Base::Matrix4D & rcMatrix) override virtual
set the viewing transformation of the provider
Reimplemented from Gui::ViewProvider.
Definition at line 3325 of file ViewProviderLink.cpp.
References create_qrc::ext, getLinkExtension(), Gui::ViewProvider::setTransformation(), and updateDataPrivate().
setTransformation() [2/2]
void ViewProviderLink::setTransformation (const SbMatrix & rcMatrix) override virtual
Reimplemented from Gui::ViewProvider.
Definition at line 3337 of file ViewProviderLink.cpp.
References create_qrc::ext, getLinkExtension(), Gui::ViewProvider::setTransformation(), and updateDataPrivate().
setupContextMenu()
void ViewProviderLink::setupContextMenu (QMenu * menu, QObject * receiver, const char * method) override virtual
set up the context-menu with the supported edit modes
Reimplemented from Gui::ViewProviderDragger.
Definition at line 2435 of file ViewProviderLink.cpp.
References _setupContextMenu(), App::LinkBaseExtension::ApplyAll, MengerSponge::box, SCL.SimpleDataTypes::e, App::LinkBaseExtension::Exclude, create_qrc::ext, App::LinkParams::getCopyOnChangeApplyToAll(), App::Document::getDependencyList(), getLinkExtension(), Gui::getMainWindow(), Gui::DlgObjectSelection::InvertSort, NavigationIndicatorGui::menu, App::LinkBaseExtension::None, src.Mod.Test.testPathArray::o, replaceobj::objs, App::LinkParams::setCopyOnChangeApplyToAll(), Gui::DlgObjectSelection::setMessage(), Gui::ActionFunction::trigger(), and Gui::Command::updateActive().
startEditing()
ViewProvider * ViewProviderLink::startEditing (int ModNum) override virtual
Reimplemented from Gui::ViewProviderDragger.
Definition at line 2754 of file ViewProviderLink.cpp.
References Gui::ViewProvider::Color, Gui::ViewProviderDragger::csysDragger, toolbit-attributes::doc, dragCtx, Gui::Application::editDocument(), create_qrc::ext, FC_ERR, App::DocumentObject::getLinkedObject(), Gui::LinkView::getLinkedView(), getLinkExtension(), Gui::ViewProviderDocumentObject::getObject(), initDraggingPlacement(), Gui::Application::Instance, linkEdit(), linkView, result, Gui::ViewProviderDragger::setDraggerPlacement(), Gui::ViewProviderDragger::startEditing(), Gui::ViewProvider::startEditing(), and Gui::ViewProvider::Transform.
Referenced by draftguitools.gui_edit.Edit::mousePressed().
unsetEditViewer()
void ViewProviderLink::unsetEditViewer (Gui::View3DInventorViewer *) override protected virtual
restores viewer settings when leaving editing mode
Reimplemented from Gui::ViewProviderDragger.
Definition at line 2857 of file ViewProviderLink.cpp.
References dragCtx, Gui::ViewProviderDragger::unsetEditViewer(), and OfflineRenderingUtils::viewer().
updateData()
void ViewProviderLink::updateData (const App::Property * prop) override virtual
Reimplemented from Gui::ViewProviderDragger.
Definition at line 1815 of file ViewProviderLink.cpp.
References childVp, create_qrc::ext, getLinkExtension(), App::DocumentObject::isRestoring(), Gui::ViewProvider::isRestoring(), Gui::ViewProviderDocumentObject::pcObject, Gui::ViewProviderDragger::updateData(), Gui::ViewProvider::updateData(), and updateDataPrivate().
Referenced by Path.Main.Gui.JobDlg.JobCreate::exec_(), draftviewproviders.view_wire.ViewProviderWire::onChanged(), draftviewproviders.view_dimension.ViewProviderLinearDimension::onChanged(), draftviewproviders.view_dimension.ViewProviderAngularDimension::onChanged(), Path.Op.Gui.Base.TaskPanelPage::pageUpdateData(), Path.Base.Gui.SetupSheet.OpTaskPanel::setupUi(), and Path.Base.Gui.PropertyBag.TaskPanel::setupUi().
updateDataPrivate()
void ViewProviderLink::updateDataPrivate (App::LinkBaseExtension * ext, const App::Property * prop) protected
Definition at line 1829 of file ViewProviderLink.cpp.
References applyColors(), applyMaterial(), canScale(), checkIcon(), Gui::ViewProvider::convert(), SCL.SimpleDataTypes::e, create_qrc::ext, Gui::ViewProviderDocumentObject::getDocument(), getLinkedView(), Gui::LinkView::getSize(), App::PropertyMaterial::getValue(), toolbit-attributes::group, hasSubElement, hasSubName, Gui::LinkView::hasSubs(), SplineSurface::i, Gui::Application::Instance, linkView, MaterialList, importers.importIFCmulticore::materials, OverrideMaterialList, Gui::ViewProvider::pcTransform, Gui::LinkView::renderDoubleSide(), toolbit-attributes::s, Gui::LinkView::setElementVisible(), Gui::LinkView::setLink(), setLinkType(), Gui::LinkView::setSize(), App::Property::setStatus(), Gui::LinkView::setTransform(), App::PropertyListsT< T, ListT, ParentT >::setValue(), App::PropertyMaterialList::setValue(), ShapeMaterial, Gui::ViewProvider::signalChangeIcon, importers.importIFCmulticore::subs, App::Property::testStatus(), updateElementList(), Gui::LinkView::updateLink(), App::Property::User3, and TestSpreadsheet::v.
Referenced by finishRestoring(), setTransformation(), and updateData().
updateElementList()
void ViewProviderLink::updateElementList (App::LinkBaseExtension * ext) protected
Definition at line 2007 of file ViewProviderLink.cpp.
References applyColors(), create_qrc::ext, App::PropertyListsT< T, ListT, ParentT >::getSize(), SplineSurface::i, Gui::Application::Instance, linkView, MaterialList, OverrideMaterialList, Gui::LinkView::setChildren(), and App::PropertyListsT< T, ListT, ParentT >::setSize().
Referenced by updateDataPrivate().
updateLinks()
void ViewProviderLink::updateLinks (ViewProvider * vp) static
Definition at line 2915 of file ViewProviderLink.cpp.
References SCL.SimpleDataTypes::e, create_qrc::ext, and App::ExtensionContainer::getExtensionByType().
Referenced by Gui::View3DInventorViewer::resetEditingRoot(), and Gui::View3DInventorViewer::setupEditingRoot().
useNewSelectionModel()
bool Gui::ViewProviderLink::useNewSelectionModel () const inline override virtual
indicates if the ViewProvider use the new Selection model
Reimplemented from Gui::ViewProvider.
Definition at line 212 of file ViewProviderLink.h.
Member Data Documentation
ChildViewProvider
App::PropertyPersistentObject Gui::ViewProviderLink::ChildViewProvider
Definition at line 202 of file ViewProviderLink.h.
Referenced by onBeforeChange(), and onChanged().
childVp
ViewProviderDocumentObject* Gui::ViewProviderLink::childVp protected
Definition at line 330 of file ViewProviderLink.h.
Referenced by attach(), finishRestoring(), getElementPicked(), getPropertyByName(), getPropertyMap(), onBeforeChange(), onChanged(), reattach(), setOverrideMode(), and updateData().
childVpLink
LinkInfoPtr Gui::ViewProviderLink::childVpLink protected
Definition at line 331 of file ViewProviderLink.h.
Referenced by attach(), getDetailPath(), getElementPicked(), onBeforeChange(), and onChanged().
dragCtx
std::unique_ptr<DraggerContext> Gui::ViewProviderLink::dragCtx protected
Definition at line 329 of file ViewProviderLink.h.
Referenced by initDraggingPlacement(), startEditing(), and unsetEditViewer().
DrawStyle
App::PropertyEnumeration Gui::ViewProviderLink::DrawStyle
Definition at line 195 of file ViewProviderLink.h.
hasSubElement
bool Gui::ViewProviderLink::hasSubElement protected
Definition at line 320 of file ViewProviderLink.h.
Referenced by canDelete(), canDropObjects(), getOverlayPixmap(), and updateDataPrivate().
hasSubName
bool Gui::ViewProviderLink::hasSubName protected
Definition at line 319 of file ViewProviderLink.h.
Referenced by canDragAndDropObject(), canDropObjectEx(), canDropObjects(), claimChildren(), dropObjectEx(), getOverlayPixmap(), linkEdit(), setLinkType(), and updateDataPrivate().
LineWidth
App::PropertyFloatConstraint Gui::ViewProviderLink::LineWidth
Definition at line 196 of file ViewProviderLink.h.
Referenced by finishRestoring(), and onChanged().
linkType
LinkType Gui::ViewProviderLink::linkType protected
Definition at line 318 of file ViewProviderLink.h.
Referenced by setLinkType().
linkView
LinkView* Gui::ViewProviderLink::linkView protected
Definition at line 317 of file ViewProviderLink.h.
Referenced by _setupContextMenu(), applyColors(), applyMaterial(), attach(), canDropObjectEx(), doubleClicked(), finishRestoring(), getDetailPath(), getElementPicked(), getIcon(), getPyLinkView(), initDraggingPlacement(), linkEdit(), onBeforeChange(), onChanged(), reattach(), setLinkType(), startEditing(), updateDataPrivate(), updateElementList(), and ~ViewProviderLink().
MaterialList
App::PropertyMaterialList Gui::ViewProviderLink::MaterialList
Definition at line 198 of file ViewProviderLink.h.
Referenced by applyMaterial(), onChanged(), updateDataPrivate(), and updateElementList().
overlayCacheKey
qint64 Gui::ViewProviderLink::overlayCacheKey mutable protected
Definition at line 332 of file ViewProviderLink.h.
Referenced by checkIcon(), and getIcon().
OverrideColorList
App::PropertyColorList Gui::ViewProviderLink::OverrideColorList
Definition at line 201 of file ViewProviderLink.h.
Referenced by getElementColors(), onChanged(), and setElementColors().
OverrideMaterial
App::PropertyBool Gui::ViewProviderLink::OverrideMaterial
Definition at line 193 of file ViewProviderLink.h.
Referenced by applyMaterial(), getElementColors(), onChanged(), and setElementColors().
OverrideMaterialList
App::PropertyBoolList Gui::ViewProviderLink::OverrideMaterialList
Definition at line 199 of file ViewProviderLink.h.
Referenced by applyMaterial(), onChanged(), updateDataPrivate(), and updateElementList().
PointSize
App::PropertyFloatConstraint Gui::ViewProviderLink::PointSize
Definition at line 197 of file ViewProviderLink.h.
Referenced by finishRestoring(), and onChanged().
Selectable
App::PropertyBool Gui::ViewProviderLink::Selectable
Definition at line 200 of file ViewProviderLink.h.
Referenced by isSelectable().
ShapeMaterial
App::PropertyMaterial Gui::ViewProviderLink::ShapeMaterial
Definition at line 194 of file ViewProviderLink.h.
Referenced by applyMaterial(), getElementColors(), onChanged(), setElementColors(), and updateDataPrivate().
The documentation for this class was generated from the following files:
ViewProviderLink.h
ViewProviderLink.cpp