FreeCAD: DrawingGui::DrawingView Class Reference
DrawingGui::DrawingView Class Reference
#include <DrawingView.h>
Public Slots
void load (const QString &path=QString())
void setRenderer (QAction *action)
void viewAll ()
Public Slots inherited from Gui::MDIView
virtual void setOverrideCursor (const QCursor &)
virtual void restoreOverrideCursor ()
Public Member Functions
DrawingView (Gui::Document *doc, QWidget *parent=nullptr)
virtual ~DrawingView ()
bool onMsg (const char *pMsg, const char **ppReturn)
Message handler.
bool onHasMsg (const char *pMsg) const
Message handler test.
void onRelabel (Gui::Document *pDoc)
get called when the document is updated
void print ()
void printPdf ()
void printPreview ()
void print (QPrinter *printer)
void setDocumentObject (const std::string &)
PyObject * getPyObject ()
Public Member Functions inherited from Gui::MDIView
MDIView (Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
~MDIView () override
virtual void viewAll ()
QString buildWindowTitle () const
build window title
bool canClose () override
overwrite when checking on close state
void deleteSelf () override
delete itself
virtual QStringList undoActions () const
virtual QStringList redoActions () const
QSize minimumSizeHint () const override
virtual void setCurrentViewMode (ViewMode mode)
ViewMode currentViewMode () const
template<typename _T >
_T getActiveObject (const char *name, App::DocumentObject **parent=nullptr, std::string *subname=nullptr) const
access getter for the active object list
void setActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr)
bool hasActiveObject (const char *n) const
bool isActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr) const
virtual bool containsViewProvider (const ViewProvider *) const
containsViewProvider Checks if the given view provider is part of this view. The default implementation returns false.
void savePrinterSettings (QPrinter *printer)
void restorePrinterSettings (QPrinter *printer)
Public Member Functions inherited from Gui::BaseView
BaseView (Gui::Document *pcDocument=nullptr)
~BaseView () override
void setDocument (Gui::Document *pcDocument)
sets the view to another document (called by Application)
void onClose ()
is sent from the document in order to close the document
Gui::Document * getGuiDocument () const
returns the document the view is attached to
App::Document * getAppDocument () const
returns the document the view is attached to
bool isPassive () const
indicates if the view is in passive mode
virtual void onUpdate ()
get called when the document is updated
virtual void onRename (Gui::Document *)
get called when the document is renamed (change of its internal name)
virtual const char * getName () const
returns the name of the view (important for messages)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *event)
void closeEvent (QCloseEvent *)
void findPrinterSettings (const QString &)
QPageSize::PageSizeId getPageSize (int w, int h) const
Protected Member Functions inherited from Gui::MDIView
void closeEvent (QCloseEvent *e) override
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Types inherited from Gui::MDIView
enum ViewMode { Child, TopLevel, FullScreen }
MDI view mode enum.
Signals inherited from Gui::MDIView
void message (const QString &, int)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Slots inherited from Gui::MDIView
virtual void windowStateChanged (QWidget *)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::MDIView
PyObject * pythonObject
Protected Attributes inherited from Gui::BaseView
Gui::Document * _pcDocument
bool bIsDetached {false}
bool bIsPassive {false}
Detailed Description
Definition at line 90 of file DrawingView.h.
Constructor & Destructor Documentation
DrawingView()
DrawingView::DrawingView (Gui::Document * doc, QWidget * parent = nullptr)
Definition at line 213 of file DrawingView.cpp.
References draftgeoutils.intersections::connect(), App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), setRenderer(), and DrawingGui::SvgView::setZoomInverted().
~DrawingView()
DrawingView::~DrawingView () virtual
Definition at line 269 of file DrawingView.cpp.
Member Function Documentation
closeEvent()
void DrawingView::closeEvent (QCloseEvent * ev) protected
Definition at line 345 of file DrawingView.cpp.
References Gui::BaseView::_pcDocument, toolbit-attributes::doc, Gui::Document::getDocument(), Gui::Document::getViewProvider(), and Gui::ViewProvider::hide().
contextMenuEvent()
void DrawingView::contextMenuEvent (QContextMenuEvent * event) protected
Definition at line 365 of file DrawingView.cpp.
References NavigationIndicatorGui::menu.
findPrinterSettings()
void DrawingView::findPrinterSettings (const QString & fileName) protected
Definition at line 300 of file DrawingView.cpp.
Referenced by load().
getPageSize()
QPageSize::PageSizeId DrawingView::getPageSize (int w, int h) const protected
Definition at line 651 of file DrawingView.cpp.
References KDL::abs(), SplineSurface::i, and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by print().
getPyObject()
PyObject * DrawingView::getPyObject () virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Gui::MDIView.
Definition at line 707 of file DrawingView.cpp.
References Gui::MDIView::getPyObject().
load
void DrawingView::load (const QString & path = QString()) slot
Definition at line 272 of file DrawingView.cpp.
References DrawingExample::file, findPrinterSettings(), and DrawingGui::SvgView::openFile().
onHasMsg()
bool DrawingView::onHasMsg (const char * pMsg) const virtual
Message handler test.
Reimplemented from Gui::MDIView.
Definition at line 436 of file DrawingView.cpp.
References toolbit-attributes::doc, Gui::BaseView::getAppDocument(), and Gui::BaseView::getGuiDocument().
onMsg()
bool DrawingView::onMsg (const char * pMsg, const char ** ppReturn) virtual
Message handler.
receive a message
Reimplemented from Gui::MDIView.
Definition at line 399 of file DrawingView.cpp.
References toolbit-attributes::doc, Gui::BaseView::getGuiDocument(), and viewAll().
onRelabel()
void DrawingView::onRelabel (Gui::Document * pDoc) virtual
get called when the document is updated
Reimplemented from Gui::MDIView.
Definition at line 470 of file DrawingView.cpp.
References Gui::BaseView::bIsPassive, Gui::Document::getDocument(), App::PropertyString::getValue(), and App::Document::Label.
print() [1/2]
void DrawingView::print () virtual
Print content of view
Reimplemented from Gui::MDIView.
Definition at line 543 of file DrawingView.cpp.
Referenced by printPdf(), and printPreview().
print() [2/2]
void DrawingView::print (QPrinter * printer) virtual
Reimplemented from Gui::MDIView.
Definition at line 570 of file DrawingView.cpp.
References getPageSize(), buildPsets::p, src.Mod.PartDesign.fcgear.svggear::w, and Path.Log::warning().
printPdf()
void DrawingView::printPdf () virtual
Print to PDF file
Reimplemented from Gui::MDIView.
Definition at line 480 of file DrawingView.cpp.
References Gui::FileOptionsDialog::ExtensionRight, SplineSurface::i, src.Mod.Test.testPathArray::items, print(), and Gui::FileOptionsDialog::setOptionsWidget().
printPreview()
void DrawingView::printPreview () virtual
Show a preview dialog
Reimplemented from Gui::MDIView.
Definition at line 557 of file DrawingView.cpp.
References draftgeoutils.intersections::connect(), and print().
setDocumentObject()
void DrawingView::setDocumentObject (const std::string & name)
Definition at line 340 of file DrawingView.cpp.
setRenderer
void DrawingView::setRenderer (QAction * action) slot
Definition at line 379 of file DrawingView.cpp.
References Path.Post.scripts.dynapath_4060_post::action, DrawingGui::SvgView::Image, DrawingGui::SvgView::Native, DrawingGui::SvgView::OpenGL, and DrawingGui::SvgView::setRenderer().
Referenced by DrawingView().
viewAll
void DrawingView::viewAll () slot
Definition at line 702 of file DrawingView.cpp.
Referenced by onMsg().
The documentation for this class was generated from the following files:
DrawingView.h
DrawingView.cpp