FreeCAD: Base::Subject< MsgType > Class Template Reference
Base::Subject< MsgType > Class Template Reference
#include <Observer.h>
Public Types
using ObserverType = Observer< MsgType >
using MessageType = MsgType
using SubjectType = Subject< MsgType >
Public Member Functions
Subject ()=default
virtual ~Subject ()
void Attach (Observer< MsgType > *ToObserv)
void Detach (Observer< MsgType > *ToObserv)
void Notify (MsgType rcReason)
Observer< MsgType > * Get (const char *Name)
void ClearObserver ()
Detailed Description
template<class MsgType>
class Base::Subject< MsgType >
Subject class Implementation of the well known Observer Design Pattern. The observed object, which inherit FCSubject, will call all its observers in case of changes. A observer class has to Attach itself to the observed object.
See also
FCObserver
Definition at line 60 of file Observer.h.
Member Typedef Documentation
MessageType
template<class MsgType > using Base::Subject< MsgType >::MessageType = MsgType
Definition at line 131 of file Observer.h.
ObserverType
template<class MsgType > using Base::Subject< MsgType >::ObserverType = Observer<MsgType>
Definition at line 130 of file Observer.h.
SubjectType
template<class MsgType > using Base::Subject< MsgType >::SubjectType = Subject<MsgType>
Definition at line 132 of file Observer.h.
Constructor & Destructor Documentation
Subject()
template<class MsgType > Base::Subject< MsgType >::Subject () default
A constructor. No special function so far.
~Subject()
template<class MsgType > virtual Base::Subject< MsgType >::~Subject () inline virtual
A destructor. No special function so far.
Definition at line 144 of file Observer.h.
Member Function Documentation
Attach()
template<class MsgType > void Base::Subject< MsgType >::Attach (Observer< MsgType > * ToObserv) inline
Attach an Observer Attach an Observer to the list of Observers which get called when Notify is called.
Parameters
ToObserv A pointer to a concrete Observer
See also
Notify
Definition at line 158 of file Observer.h.
Referenced by InspectionGui::ViewProviderInspection::attach(), FemGui::ViewProviderFemPostObject::attach(), CmdRenderingOrder::CmdRenderingOrder(), CmdSketcherSnap::CmdSketcherSnap(), SketcherGui::CurveConverter::CurveConverter(), MatGui::DlgDisplayPropertiesImp::DlgDisplayPropertiesImp(), MatGui::DlgInspectAppearance::DlgInspectAppearance(), MatGui::DlgInspectMaterial::DlgInspectMaterial(), MatGui::DlgMaterialImp::DlgMaterialImp(), Gui::EditorView::EditorView(), Gui::GraphicsView3D::GraphicsView3D(), Gui::MacroManager::MacroManager(), Gui::NotificationArea::ParameterObserver::ParameterObserver(), TechDrawGui::QGVPage::Private::Private(), Gui::RecentFilesAction::Private::Private(), Gui::PythonConsole::PythonConsole(), Gui::DockWnd::ReportOutput::ReportOutput(), Gui::StatefulLabel::setParameterGroup(), Gui::PrefWidget::setParamGrpPath(), Gui::ShortcutManager::ShortcutManager(), Gui::StatefulLabel::StatefulLabel(), Gui::StatusBarObserver::StatusBarObserver(), Gui::TaskView::TaskAppearance::TaskAppearance(), Gui::TaskView::TaskSelectLinkProperty::TaskSelectLinkProperty(), Gui::TaskView::TaskSketcherCreateCommands::TaskSketcherCreateCommands(), Gui::TaskView::TaskView::TaskView(), Gui::TextEditor::TextEditor(), Gui::View3DSettings::View3DSettings(), Gui::ViewParams::ViewParams(), FemGui::ViewProviderFemPostObject::ViewProviderFemPostObject(), InspectionGui::ViewProviderInspection::ViewProviderInspection(), and MeshGui::ViewProviderMeshCurvature::ViewProviderMeshCurvature().
ClearObserver()
template<class MsgType > void Base::Subject< MsgType >::ClearObserver () inline
Clears the list of all registered observers.
Note
Using this function in your code may be an indication of design problems.
Definition at line 247 of file Observer.h.
Referenced by Gui::Dialog::ParameterGroupItem::~ParameterGroupItem().
Detach()
template<class MsgType > void Base::Subject< MsgType >::Detach (Observer< MsgType > * ToObserv) inline
Detach an Observer Detach an Observer from the list of Observers which get called when Notify is called.
Parameters
ToObserv A pointer to a concrete Observer
See also
Notify
Definition at line 179 of file Observer.h.
Referenced by TechDrawGui::QGVPage::Private::detach(), Gui::StatefulLabel::setParameterGroup(), CmdRenderingOrder::~CmdRenderingOrder(), CmdSketcherSnap::~CmdSketcherSnap(), MatGui::DlgDisplayPropertiesImp::~DlgDisplayPropertiesImp(), MatGui::DlgInspectAppearance::~DlgInspectAppearance(), MatGui::DlgInspectMaterial::~DlgInspectMaterial(), MatGui::DlgMaterialImp::~DlgMaterialImp(), Gui::EditorView::~EditorView(), Gui::GraphicsView3D::~GraphicsView3D(), Gui::MacroManager::~MacroManager(), Gui::PrefWidget::~PrefWidget(), Gui::RecentFilesAction::Private::~Private(), Gui::PythonConsole::~PythonConsole(), Gui::DockWnd::ReportOutput::~ReportOutput(), Gui::ShortcutManager::~ShortcutManager(), Gui::StatefulLabel::~StatefulLabel(), Gui::StatusBarObserver::~StatusBarObserver(), Gui::TaskView::TaskAppearance::~TaskAppearance(), Gui::TaskView::TaskSelectLinkProperty::~TaskSelectLinkProperty(), SketcherGui::TaskSketcherConstraints::~TaskSketcherConstraints(), Gui::TaskView::TaskSketcherCreateCommands::~TaskSketcherCreateCommands(), Gui::TaskView::TaskView::~TaskView(), Gui::TextEditor::~TextEditor(), and Gui::View3DSettings::~View3DSettings().
Get()
template<class MsgType > Observer<MsgType>* Base::Subject< MsgType >::Get (const char * Name) inline
Get an Observer by name Get a observer by name if the observer reimplements the Name() mthode.
See also
Observer
Definition at line 229 of file Observer.h.
Referenced by src.Mod.AddonManager.AddonManagerTest.app.mocks.MockPref::GetBool(), src.Mod.AddonManager.AddonManagerTest.app.mocks.MockPref::GetInt(), and src.Mod.AddonManager.AddonManagerTest.app.mocks.MockPref::GetString().
Notify()
template<class MsgType > void Base::Subject< MsgType >::Notify (MsgType rcReason) inline
Notify all Observers Send a message to all Observers attached to this subject. The Message depends on the implementation of a concrete Oberserver and Subject.
See also
Notify
Definition at line 200 of file Observer.h.
Referenced by Gui::SoFCColorBarNotifier::attach(), InspectionGui::ViewProviderInspection::attach(), FemGui::ViewProviderFemPostObject::attach(), InspectionGui::ViewProviderInspection::onChanged(), Gui::PrefWidget::onSave(), Gui::DockWnd::ReportOutput::ReportOutput(), and InspectionGui::ViewProviderInspection::updateData().
The documentation for this class was generated from the following file:
Observer.h