FreeCAD: MatGui::MaterialDelegate Class Reference
MatGui::MaterialDelegate Class Reference
#include <MaterialDelegate.h>
Signals
void propertyChange (const QString &property, const QVariant &value)
Public Member Functions
MaterialDelegate (QObject *parent=nullptr)
~MaterialDelegate () override=default
QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &styleOption, const QModelIndex &index) const override
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const override
Public Member Functions inherited from MatGui::BaseDelegate
BaseDelegate (QObject *parent=nullptr)
virtual ~BaseDelegate ()=default
QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const override
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const override
QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &styleOption, const QModelIndex &index) const override
void setEditorData (QWidget *editor, const QModelIndex &index) const override
void setModelData (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const override
Protected Member Functions
bool editorEvent (QEvent *event, QAbstractItemModel *model, const QStyleOptionViewItem &option, const QModelIndex &index) override
Materials::MaterialValue::ValueType getType (const QModelIndex &index) const override
QString getUnits (const QModelIndex &index) const override
QVariant getValue (const QModelIndex &index) const override
void setValue (QAbstractItemModel *model, const QModelIndex &index, const QVariant &value) const override
void notifyChanged (const QAbstractItemModel *model, const QModelIndex &index) const override
bool newRow (const QAbstractItemModel *model, const QModelIndex &index) const override
Protected Member Functions inherited from MatGui::BaseDelegate
QString getStringValue (const QModelIndex &index) const
QRgb parseColor (const QString &color) const
void paintQuantity (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
void paintImage (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
void paintSVG (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
void paintColor (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
void paintList (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
void paintMultiLineString (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
void paintArray (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
QWidget * createWidget (QWidget *parent, const QVariant &item, const QModelIndex &index) const
Detailed Description
Definition at line 60 of file MaterialDelegate.h.
Constructor & Destructor Documentation
MaterialDelegate()
MaterialDelegate::MaterialDelegate (QObject * parent = nullptr) explicit
Definition at line 61 of file MaterialDelegate.cpp.
~MaterialDelegate()
MatGui::MaterialDelegate::~MaterialDelegate () override default
Member Function Documentation
createEditor()
QWidget * MaterialDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & styleOption, const QModelIndex & index) const override
Definition at line 392 of file MaterialDelegate.cpp.
References Path.Post.Utils::editor(), toolbit-attributes::group, and Init::parent.
editorEvent()
bool MaterialDelegate::editorEvent (QEvent * event, QAbstractItemModel * model, const QStyleOptionViewItem & option, const QModelIndex & index) override protected
Definition at line 175 of file MaterialDelegate.cpp.
References Materials::MaterialValue::Array2D, Materials::MaterialValue::Array3D, Materials::MaterialValue::Color, Materials::MaterialValue::FileList, getType(), toolbit-attributes::group, Materials::MaterialValue::Image, Materials::MaterialValue::ImageList, Materials::MaterialValue::List, Materials::MaterialValue::MultiLineString, propertyName(), Materials::MaterialValue::SVG, and Path.Post.scripts.grbl_post::type.
getType()
Materials::MaterialValue::ValueType MaterialDelegate::getType (const QModelIndex & index) const override protected virtual
Emits this signal when a property has changed
Implements MatGui::BaseDelegate.
Definition at line 74 of file MaterialDelegate.cpp.
References toolbit-attributes::group, and Materials::MaterialValue::mapType().
Referenced by editorEvent(), and paint().
getUnits()
QString MaterialDelegate::getUnits (const QModelIndex & index) const override protected virtual
Implements MatGui::BaseDelegate.
Definition at line 92 of file MaterialDelegate.cpp.
References toolbit-attributes::group.
getValue()
QVariant MaterialDelegate::getValue (const QModelIndex & index) const override protected virtual
Implements MatGui::BaseDelegate.
Definition at line 109 of file MaterialDelegate.cpp.
References toolbit-attributes::group, and propertyName().
newRow()
bool MaterialDelegate::newRow (const QAbstractItemModel * model, const QModelIndex & index) const override protected virtual
Reimplemented from MatGui::BaseDelegate.
Definition at line 65 of file MaterialDelegate.cpp.
notifyChanged()
void MaterialDelegate::notifyChanged (const QAbstractItemModel * model, const QModelIndex & index) const override protected virtual
Implements MatGui::BaseDelegate.
Definition at line 153 of file MaterialDelegate.cpp.
References toolbit-attributes::group, propertyChange(), and propertyName().
Referenced by setValue().
paint()
void MaterialDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const override
Definition at line 339 of file MaterialDelegate.cpp.
References Materials::MaterialValue::Array2D, Materials::MaterialValue::Array3D, Materials::MaterialValue::Color, Materials::MaterialValue::FileList, getType(), toolbit-attributes::group, Materials::MaterialValue::Image, Materials::MaterialValue::ImageList, Materials::MaterialValue::List, Materials::MaterialValue::MultiLineString, MatGui::BaseDelegate::paintArray(), MatGui::BaseDelegate::paintColor(), MatGui::BaseDelegate::paintImage(), MatGui::BaseDelegate::paintList(), MatGui::BaseDelegate::paintMultiLineString(), MatGui::BaseDelegate::paintQuantity(), MatGui::BaseDelegate::paintSVG(), Materials::MaterialValue::Quantity, Materials::MaterialValue::SVG, and Path.Post.scripts.grbl_post::type.
propertyChange
void MatGui::MaterialDelegate::propertyChange (const QString & property, const QVariant & value) signal
Emits this signal when a property has changed
Referenced by notifyChanged().
setValue()
void MaterialDelegate::setValue (QAbstractItemModel * model, const QModelIndex & index, const QVariant & value) const override protected virtual
Implements MatGui::BaseDelegate.
Definition at line 129 of file MaterialDelegate.cpp.
References toolbit-attributes::group, notifyChanged(), and propertyName().
The documentation for this class was generated from the following files:
MaterialDelegate.h
MaterialDelegate.cpp