FreeCAD: Start::RecentFilesModel Class Reference
Start::RecentFilesModel Class Reference
#include <RecentFilesModel.h>
Public Member Functions
RecentFilesModel (QObject *parent=nullptr)
void loadRecentFiles ()
Public Member Functions inherited from Start::DisplayedFilesModel
DisplayedFilesModel (QObject *parent=nullptr)
int rowCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
void addFile (const QString &filePath)
void clear ()
Additional Inherited Members
Protected Member Functions inherited from Start::DisplayedFilesModel
QHash< int, QByteArray > roleNames () const override
void reCacheFileInfo ()
Detailed Description
A model for displaying a list of files including a thumbnail or icon, plus various file statistics.
Definition at line 58 of file RecentFilesModel.h.
Constructor & Destructor Documentation
RecentFilesModel()
RecentFilesModel::RecentFilesModel (QObject * parent = nullptr) explicit
Definition at line 34 of file RecentFilesModel.cpp.
References App::GetApplication(), and App::Application::GetParameterGroupByPath().
Member Function Documentation
loadRecentFiles()
void RecentFilesModel::loadRecentFiles ()
Definition at line 41 of file RecentFilesModel.cpp.
References Start::DisplayedFilesModel::addFile(), Start::DisplayedFilesModel::clear(), ParameterGrp::GetASCII(), ParameterGrp::GetInt(), and SplineSurface::i.
Referenced by StartGui::StartView::configureRecentFilesListWidget().
The documentation for this class was generated from the following files:
RecentFilesModel.h
RecentFilesModel.cpp