FreeCAD: Gui::Dialog::PreferenceUiForm Class Reference
Gui::Dialog::PreferenceUiForm Class Reference
#include <PropertyPage.h>
Public Member Functions
PreferenceUiForm (const QString &fn, QWidget *parent=nullptr)
~PreferenceUiForm () override
void loadSettings () override
void saveSettings () override
QWidget * form ()
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
Subclass that embeds a form from a UI file.
Author
Werner Mayer
Definition at line 138 of file PropertyPage.h.
Constructor & Destructor Documentation
PreferenceUiForm()
PreferenceUiForm::PreferenceUiForm (const QString & fn, QWidget * parent = nullptr) explicit
Definition at line 125 of file PropertyPage.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), DrawingExample::file, and Gui::UiLoader::newInstance().
~PreferenceUiForm()
PreferenceUiForm::~PreferenceUiForm () override default
Member Function Documentation
changeEvent()
void PreferenceUiForm::changeEvent (QEvent * e) override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 150 of file PropertyPage.cpp.
References SCL.SimpleDataTypes::e.
form()
QWidget * Gui::Dialog::PreferenceUiForm::form ()
Definition at line 213 of file PropertyPage.cpp.
Referenced by Path.Op.Gui.CircularHoleBase.TaskPanelHoleGeometryPage::checkedChanged(), Path.Op.Gui.FeatureExtension.TaskPanelExtensionPage::createItemForBaseModel(), Path.Op.Gui.FeatureExtension.TaskPanelExtensionPage::currentExtensions(), Path.Op.Gui.Slot.TaskPanelOpPage::customizeReference_1(), Path.Op.Gui.Slot.TaskPanelOpPage::customizeReference_2(), Path.Op.Gui.CircularHoleBase.TaskPanelHoleGeometryPage::deleteBase(), Path.Op.Gui.Custom.TaskPanelOpPage::getFields(), Path.Op.Gui.Probe.TaskPanelOpPage::getFields(), Path.Op.Gui.Helix.TaskPanelOpPage::getFields(), Path.Op.Gui.Waterline.TaskPanelOpPage::getFields(), Path.Op.Gui.Profile.TaskPanelOpPage::getFields(), Path.Op.Gui.Surface.TaskPanelOpPage::getFields(), Path.Op.Gui.Deburr.TaskPanelOpPage::getFields(), Path.Op.Gui.ThreadMilling.TaskPanelOpPage::getFields(), Path.Op.Gui.Tapping.TaskPanelOpPage::getFields(), Path.Op.Gui.PocketBase.TaskPanelOpPage::getFields(), Path.Op.Gui.Adaptive.TaskPanelOpPage::getFields(), Path.Op.Gui.Slot.TaskPanelOpPage::getFields(), Path.Op.Gui.Drilling.TaskPanelOpPage::getFields(), Path.Op.Gui.Engrave.TaskPanelOpPage::getFields(), Path.Op.Gui.Vcarve.TaskPanelOpPage::getFields(), Path.Op.Gui.FeatureExtension.TaskPanelExtensionPage::getFields(), Path.Op.Gui.Adaptive.TaskPanelOpPage::getSignalsForUpdate(), Path.Op.Gui.Custom.TaskPanelOpPage::getSignalsForUpdate(), Path.Op.Gui.Probe.TaskPanelOpPage::getSignalsForUpdate(), Path.Op.Gui.Helix.TaskPanelOpPage::getSignalsForUpdate(), Path.Op.Gui.Deburr.TaskPanelOpPage::getSignalsForUpdate(), Path.Op.Gui.Waterline.TaskPanelOpPage::getSignalsForUpdate(), Path.Op.Gui.Profile.TaskPanelOpPage::getSignalsForUpdate(), Path.Op.Gui.Slot.TaskPanelOpPage::getSignalsForUpdate(), Path.Op.Gui.Engrave.TaskPanelOpPage::getSignalsForUpdate(), Path.Op.Gui.Tapping.TaskPanelOpPage::getSignalsForUpdate(), Path.Op.Gui.PocketBase.TaskPanelOpPage::getSignalsForUpdate(), Path.Op.Gui.Drilling.TaskPanelOpPage::getSignalsForUpdate(), Path.Op.Gui.Vcarve.TaskPanelOpPage::getSignalsForUpdate(), Path.Op.Gui.Surface.TaskPanelOpPage::getSignalsForUpdate(), Path.Op.Gui.ThreadMilling.TaskPanelOpPage::getSignalsForUpdate(), Path.Op.Gui.FeatureExtension.TaskPanelExtensionPage::getSignalsForUpdate(), Path.Op.Gui.Adaptive.TaskPanelOpPage::initPage(), Path.Op.Gui.CircularHoleBase.TaskPanelHoleGeometryPage::itemActivated(), Path.Op.Gui.Drilling.TaskPanelOpPage::registerSignalHandlers(), Path.Op.Gui.Tapping.TaskPanelOpPage::registerSignalHandlers(), Path.Op.Gui.Deburr.TaskPanelOpPage::registerSignalHandlers(), Path.Op.Gui.Vcarve.TaskPanelOpPage::registerSignalHandlers(), Path.Op.Gui.CircularHoleBase.TaskPanelHoleGeometryPage::registerSignalHandlers(), Path.Op.Gui.Waterline.TaskPanelOpPage::registerSignalHandlers(), Path.Op.Gui.Profile.TaskPanelOpPage::registerSignalHandlers(), Path.Op.Gui.ThreadMilling.TaskPanelOpPage::registerSignalHandlers(), Path.Op.Gui.Surface.TaskPanelOpPage::registerSignalHandlers(), Path.Op.Gui.FeatureExtension.TaskPanelExtensionPage::registerSignalHandlers(), Path.Op.Gui.FeatureExtension.TaskPanelExtensionPage::restoreSelection(), Path.Op.Gui.Drilling.TaskPanelOpPage::setChipBreakControl(), Path.Op.Gui.FeatureExtension.TaskPanelExtensionPage::setExtensions(), Path.Op.Gui.Custom.TaskPanelOpPage::setFields(), Path.Op.Gui.CircularHoleBase.TaskPanelHoleGeometryPage::setFields(), Path.Op.Gui.Slot.TaskPanelOpPage::setFields(), Path.Op.Gui.Adaptive.TaskPanelOpPage::setFields(), Path.Op.Gui.Helix.TaskPanelOpPage::setFields(), Path.Op.Gui.Probe.TaskPanelOpPage::setFields(), Path.Op.Gui.Waterline.TaskPanelOpPage::setFields(), Path.Op.Gui.Profile.TaskPanelOpPage::setFields(), Path.Op.Gui.Vcarve.TaskPanelBaseGeometryPage::setFields(), Path.Op.Gui.Deburr.TaskPanelOpPage::setFields(), Path.Op.Gui.Engrave.TaskPanelBaseGeometryPage::setFields(), Path.Op.Gui.ThreadMilling.TaskPanelOpPage::setFields(), Path.Op.Gui.Tapping.TaskPanelOpPage::setFields(), Path.Op.Gui.Drilling.TaskPanelOpPage::setFields(), Path.Op.Gui.Surface.TaskPanelOpPage::setFields(), Path.Op.Gui.Engrave.TaskPanelOpPage::setFields(), Path.Op.Gui.PocketBase.TaskPanelOpPage::setFields(), Path.Op.Gui.Vcarve.TaskPanelOpPage::setFields(), Path.Op.Gui.FeatureExtension.TaskPanelExtensionPage::setFields(), Path.Op.Gui.Custom.TaskPanelOpPage::setGCode(), Path.Op.Gui.Probe.TaskPanelOpPage::SetOutputFileName(), Path.Op.Gui.FeatureExtension.TaskPanelExtensionPage::showHideExtension(), Path.Op.Gui.Vcarve.TaskPanelBaseGeometryPage::updateBase(), Path.Op.Gui.Engrave.TaskPanelBaseGeometryPage::updateBase(), Path.Op.Gui.CircularHoleBase.TaskPanelHoleGeometryPage::updateBase(), Path.Op.Gui.FeatureExtension.TaskPanelExtensionPage::updateData(), Path.Op.Gui.Deburr.TaskPanelOpPage::updateExtraDepth(), Path.Op.Gui.Vcarve.TaskPanelOpPage::updateFormCallback(), Path.Op.Gui.PocketBase.TaskPanelOpPage::updateMinTravel(), Path.Op.Gui.Waterline.TaskPanelOpPage::updateVisibility(), Path.Op.Gui.Profile.TaskPanelOpPage::updateVisibility(), Path.Op.Gui.Slot.TaskPanelOpPage::updateVisibility(), Path.Op.Gui.Surface.TaskPanelOpPage::updateVisibility(), Path.Op.Gui.Deburr.TaskPanelOpPage::updateWidth(), and Path.Op.Gui.PocketBase.TaskPanelOpPage::updateZigZagAngle().
loadSettings()
void PreferenceUiForm::loadSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 171 of file PropertyPage.cpp.
saveSettings()
void PreferenceUiForm::saveSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 192 of file PropertyPage.cpp.
The documentation for this class was generated from the following files:
PropertyPage.h
PropertyPage.cpp