FreeCAD: Gui::InteractiveInterpreter Class Reference
Gui::InteractiveInterpreter Class Reference
#include <PythonConsole.h>
Public Member Functions
InteractiveInterpreter ()
~InteractiveInterpreter ()
bool isOccupied () const
bool interrupt () const
bool push (const char *)
int compileCommand (const char *) const
bool hasPendingInput () const
void setBuffer (const QStringList &)
QStringList getBuffer () const
void clearBuffer ()
Detailed Description
This class implements an interactive Python interpreter.
Author
Werner Mayer
Definition at line 40 of file PythonConsole.h.
Constructor & Destructor Documentation
InteractiveInterpreter()
InteractiveInterpreter::InteractiveInterpreter ()
Definition at line 117 of file PythonConsole.cpp.
References toolbit-attributes::args, Gui::InteractiveInterpreterP::interpreter, and src.Mod.PartDesign.fcgear.svggear::module.
~InteractiveInterpreter()
InteractiveInterpreter::~InteractiveInterpreter ()
Definition at line 140 of file PythonConsole.cpp.
References Gui::InteractiveInterpreterP::interpreter, and Gui::InteractiveInterpreterP::sysmodule.
Member Function Documentation
clearBuffer()
void InteractiveInterpreter::clearBuffer ()
Definition at line 412 of file PythonConsole.cpp.
References Gui::InteractiveInterpreterP::buffer.
compileCommand()
int InteractiveInterpreter::compileCommand (const char * source) const
Compile a command and determine whether it is incomplete.
The source string may contain line feeds and/or carriage returns.
Return value:
Return 1 if the command is incomplete
Return 0 if the command is complete and valid
Return -1 if the command is a syntax error
(OverflowError and ValueError can be produced by malformed literals).
Definition at line 211 of file PythonConsole.cpp.
References toolbit-attributes::args, and Gui::InteractiveInterpreterP::interpreter.
getBuffer()
QStringList InteractiveInterpreter::getBuffer () const
Definition at line 402 of file PythonConsole.cpp.
References Gui::InteractiveInterpreterP::buffer.
hasPendingInput()
bool InteractiveInterpreter::hasPendingInput () const
Definition at line 397 of file PythonConsole.cpp.
References Gui::InteractiveInterpreterP::buffer.
Referenced by Gui::PythonConsole::keyPressEvent().
interrupt()
bool InteractiveInterpreter::interrupt () const
Definition at line 293 of file PythonConsole.cpp.
References Gui::PythonTracing::interrupt(), and Gui::InteractiveInterpreterP::trace.
Referenced by Gui::PythonConsole::keyPressEvent().
isOccupied()
bool InteractiveInterpreter::isOccupied () const
Definition at line 288 of file PythonConsole.cpp.
References Gui::PythonTracing::isActive(), and Gui::InteractiveInterpreterP::trace.
push()
bool InteractiveInterpreter::push (const char * line)
Store the line into the internal buffer and compile the total buffer. In case it is a complete Python command the buffer is emptied.
Definition at line 372 of file PythonConsole.cpp.
References Gui::InteractiveInterpreterP::buffer.
setBuffer()
void InteractiveInterpreter::setBuffer (const QStringList & buf)
Definition at line 407 of file PythonConsole.cpp.
References Gui::InteractiveInterpreterP::buffer.
The documentation for this class was generated from the following files:
PythonConsole.h
PythonConsole.cpp