FreeCAD: NotificationItem Class Reference
NotificationItem Class Reference
Public Member Functions
NotificationItem (Base::LogStyle notificationtype, QString notifiername, QString message)
QVariant data (int column, int role) const override
void addRepetition ()
bool isRepeated (Base::LogStyle notificationtype, const QString &notifiername, const QString &message) const
bool isType (Base::LogStyle notificationtype) const
bool isUnread () const
bool isNotifying () const
bool isShown () const
int getRepetitions () const
void setNotified ()
void resetNotified ()
void setShown ()
void resetShown ()
void setRead ()
void setUnread ()
QString getMessage () const
const QString & getNotifier ()
Detailed Description
Specialised Item class for the Widget notifications/errors/warnings It holds all item specific data, including visualisation data and controls how the item should appear in the widget.
Definition at line 319 of file NotificationArea.cpp.
Constructor & Destructor Documentation
NotificationItem()
NotificationItem::NotificationItem (Base::LogStyle notificationtype, QString notifiername, QString message) inline
Definition at line 322 of file NotificationArea.cpp.
Member Function Documentation
addRepetition()
void NotificationItem::addRepetition () inline
Definition at line 371 of file NotificationArea.cpp.
Referenced by NotificationsAction::resetLastNotificationStatus().
data()
QVariant NotificationItem::data (int column, int role) const inline override
Definition at line 328 of file NotificationArea.cpp.
References App::ExpressionParser::column, Base::Critical, ResourceManager::CriticalPixmap(), Base::Error, ResourceManager::ErrorPixmap(), getMessage(), ResourceManager::InfoPixmap(), Path.Post.scripts.opensbp_post::move(), Base::Warning, and ResourceManager::WarningPixmap().
getMessage()
QString NotificationItem::getMessage () const inline
Definition at line 426 of file NotificationArea.cpp.
Referenced by data().
getNotifier()
const QString& NotificationItem::getNotifier () inline
Definition at line 435 of file NotificationArea.cpp.
getRepetitions()
int NotificationItem::getRepetitions () const inline
Definition at line 398 of file NotificationArea.cpp.
isNotifying()
bool NotificationItem::isNotifying () const inline
Definition at line 390 of file NotificationArea.cpp.
isRepeated()
bool NotificationItem::isRepeated (Base::LogStyle notificationtype, const QString & notifiername, const QString & message) const inline
Definition at line 378 of file NotificationArea.cpp.
Referenced by NotificationsAction::isSameNotification().
isShown()
bool NotificationItem::isShown () const inline
Definition at line 394 of file NotificationArea.cpp.
isType()
bool NotificationItem::isType (Base::LogStyle notificationtype) const inline
Definition at line 382 of file NotificationArea.cpp.
isUnread()
bool NotificationItem::isUnread () const inline
Definition at line 386 of file NotificationArea.cpp.
resetNotified()
void NotificationItem::resetNotified () inline
Definition at line 406 of file NotificationArea.cpp.
resetShown()
void NotificationItem::resetShown () inline
Definition at line 414 of file NotificationArea.cpp.
setNotified()
void NotificationItem::setNotified () inline
Definition at line 402 of file NotificationArea.cpp.
setRead()
void NotificationItem::setRead () inline
Definition at line 418 of file NotificationArea.cpp.
Referenced by NotificationsAction::clearUnreadFlag().
setShown()
void NotificationItem::setShown () inline
Definition at line 410 of file NotificationArea.cpp.
setUnread()
void NotificationItem::setUnread () inline
Definition at line 422 of file NotificationArea.cpp.
The documentation for this class was generated from the following file:
NotificationArea.cpp