FreeCAD: Gui::RubberbandSelection Class Reference
Gui::RubberbandSelection Class Reference
#include <MouseSelection.h>
Public Member Functions
RubberbandSelection ()
~RubberbandSelection () override
void setColor (float r, float g, float b, float a=1.0)
void initialize () override
implement this in derived classes
void terminate (bool abort=false) override
implement this in derived classes
Public Member Functions inherited from Gui::BaseMouseSelection
BaseMouseSelection ()
~BaseMouseSelection () override=default
Public Member Functions inherited from Gui::AbstractMouseSelection
AbstractMouseSelection ()
virtual ~AbstractMouseSelection ()=default
void grabMouseModel (Gui::View3DInventorViewer *)
void releaseMouseModel (bool abort=false)
const std::vector< SbVec2s > & getPositions () const
SelectionRole selectedRole () const
int handleEvent (const SoEvent *const ev, const SbViewportRegion &vp)
Protected Member Functions
int mouseButtonEvent (const SoMouseButtonEvent *const e, const QPoint &pos) override
int locationEvent (const SoLocation2Event *const e, const QPoint &pos) override
int keyboardEvent (const SoKeyboardEvent *const e) override
void draw () override
draw the rectangle
Protected Member Functions inherited from Gui::AbstractMouseSelection
Protected Attributes
Gui::Rubberband rubberband
Protected Attributes inherited from Gui::AbstractMouseSelection
Gui::View3DInventorViewer * _pcView3D {nullptr}
QCursor m_cPrevCursor
int m_iXold
int m_iYold
int m_iXnew
int m_iYnew
SelectionRole m_selectedRole
std::vector< SbVec2s > _clPoly
Additional Inherited Members
Public Types inherited from Gui::AbstractMouseSelection
enum {
Continue =0, Restart =1, Finish =2, Cancel =3,
Ignore =4
}
Detailed Description
The selection mouse model class Draws a rectangle for selection
Author
Werner Mayer
Definition at line 204 of file MouseSelection.h.
Constructor & Destructor Documentation
RubberbandSelection()
RubberbandSelection::RubberbandSelection ()
Definition at line 561 of file MouseSelection.cpp.
References rubberband, and Gui::Rubberband::setColor().
~RubberbandSelection()
RubberbandSelection::~RubberbandSelection () override default
Member Function Documentation
draw()
void RubberbandSelection::draw () override protected virtual
draw the rectangle
Reimplemented from Gui::AbstractMouseSelection.
Definition at line 595 of file MouseSelection.cpp.
References Gui::AbstractMouseSelection::_pcView3D, and SIM::Coin3D::Quarter::QuarterWidget::redraw().
Referenced by locationEvent().
initialize()
void RubberbandSelection::initialize () override virtual
implement this in derived classes
Implements Gui::AbstractMouseSelection.
Definition at line 573 of file MouseSelection.cpp.
References Gui::AbstractMouseSelection::_pcView3D, Gui::View3DInventorViewer::addGraphicsItem(), Gui::View3DInventorViewer::Image, SIM::Coin3D::Quarter::QuarterWidget::redraw(), rubberband, Gui::View3DInventorViewer::setRenderType(), Gui::Rubberband::setViewer(), and Gui::Rubberband::setWorking().
keyboardEvent()
int RubberbandSelection::keyboardEvent (const SoKeyboardEvent *const e) override protected virtual
Reimplemented from Gui::AbstractMouseSelection.
Definition at line 645 of file MouseSelection.cpp.
References Gui::AbstractMouseSelection::Continue.
locationEvent()
int RubberbandSelection::locationEvent (const SoLocation2Event *const e, const QPoint & pos) override protected virtual
Reimplemented from Gui::AbstractMouseSelection.
Definition at line 636 of file MouseSelection.cpp.
References Gui::AbstractMouseSelection::Continue, draw(), Gui::AbstractMouseSelection::m_iXnew, Gui::AbstractMouseSelection::m_iXold, Gui::AbstractMouseSelection::m_iYnew, Gui::AbstractMouseSelection::m_iYold, RobotExample::pos, rubberband, and Gui::Rubberband::setCoords().
mouseButtonEvent()
int RubberbandSelection::mouseButtonEvent (const SoMouseButtonEvent *const e, const QPoint & pos) override protected virtual
Reimplemented from Gui::AbstractMouseSelection.
Definition at line 600 of file MouseSelection.cpp.
References Gui::AbstractMouseSelection::_clPoly, Gui::AbstractMouseSelection::Continue, SCL.SimpleDataTypes::e, Gui::AbstractMouseSelection::Finish, Gui::AbstractMouseSelection::m_iXnew, Gui::AbstractMouseSelection::m_iXold, Gui::AbstractMouseSelection::m_iYnew, Gui::AbstractMouseSelection::m_iYold, RobotExample::pos, Gui::AbstractMouseSelection::releaseMouseModel(), rubberband, and Gui::Rubberband::setWorking().
setColor()
void RubberbandSelection::setColor (float r, float g, float b, float a = 1.0)
Definition at line 568 of file MouseSelection.cpp.
References a, SCL.SimpleDataTypes::b, toolbit-attributes::g, rubberband, and Gui::Rubberband::setColor().
terminate()
void RubberbandSelection::terminate (bool abort = false) override virtual
implement this in derived classes
Implements Gui::AbstractMouseSelection.
Reimplemented in Gui::BoxZoomSelection.
Definition at line 584 of file MouseSelection.cpp.
References Gui::AbstractMouseSelection::_pcView3D, Gui::View3DInventorViewer::Native, SIM::Coin3D::Quarter::QuarterWidget::redraw(), Gui::View3DInventorViewer::removeGraphicsItem(), rubberband, and Gui::View3DInventorViewer::setRenderType().
Referenced by Gui::BoxZoomSelection::terminate(), and src.Mod.AddonManager.addonmanager_workers_startup.CacheMacroCodeWorker::update_and_advance().
Member Data Documentation
rubberband
Gui::Rubberband Gui::RubberbandSelection::rubberband protected
Definition at line 224 of file MouseSelection.h.
Referenced by initialize(), locationEvent(), mouseButtonEvent(), Gui::RectangleSelection::RectangleSelection(), RubberbandSelection(), setColor(), and terminate().
The documentation for this class was generated from the following files:
MouseSelection.h
MouseSelection.cpp