FreeCAD: SoFCDB.cpp File Reference
SoFCDB.cpp File Reference
#include "PreCompiled.h"
#include <Inventor/SbSphere.h>
#include <Inventor/SbString.h>
#include <Inventor/SoInteraction.h>
#include <Inventor/actions/SoGetBoundingBoxAction.h>
#include <Inventor/actions/SoToVRML2Action.h>
#include <Inventor/actions/SoWriteAction.h>
#include <Inventor/fields/SoMFNode.h>
#include <Inventor/fields/SoSFNode.h>
#include <Inventor/nodes/SoGroup.h>
#include <Inventor/VRMLnodes/SoVRMLGroup.h>
#include <Inventor/VRMLnodes/SoVRMLIndexedFaceSet.h>
#include <Inventor/VRMLnodes/SoVRMLNormal.h>
#include <Inventor/VRMLnodes/SoVRMLParent.h>
#include <Inventor/VRMLnodes/SoVRMLShape.h>
#include <QDir>
#include <QProcess>
#include <QTemporaryFile>
#include <sstream>
#include <Base/FileInfo.h>
#include <Base/Stream.h>
#include <Base/Tools.h>
#include <zipios++/gzipoutputstream.h>
#include "SoFCDB.h"
#include "Camera.h"
#include "Flag.h"
#include "GestureNavigationStyle.h"
#include "NavigationStyle.h"
#include "SelectionObject.h"
#include "SoDevicePixelRatioElement.h"
#include "SoFCColorBar.h"
#include "SoFCColorGradient.h"
#include "SoFCColorLegend.h"
#include "SoFCCSysDragger.h"
#include "SoFCInteractiveElement.h"
#include "SoFCSelection.h"
#include "SoFCSelectionAction.h"
#include "SoFCUnifiedSelection.h"
#include "SoFCVectorizeSVGAction.h"
#include "SoFCVectorizeU3DAction.h"
#include "SoTextLabel.h"
#include "SoDatumLabel.h"
#include "Inventor/MarkerBitmaps.h"
#include "Inventor/SmSwitchboard.h"
#include "Inventor/So3DAnnotation.h"
#include "Inventor/SoAutoZoomTranslation.h"
#include "Inventor/SoAxisCrossKit.h"
#include "Inventor/SoDrawingGrid.h"
#include "Inventor/SoFCBackgroundGradient.h"
#include "Inventor/SoFCBoundingBox.h"
#include "Inventor/SoMouseWheelEvent.h"
#include "Inventor/SoFCTransform.h"
#include "propertyeditor/PropertyItem.h"
#include "ArcEngine.h"
Functions
SoNode * replaceSwitches (SoNodeList *children, SoGroup *parent)
SoNode * replaceSwitchesInSceneGraph (SoNode *node)
Variables
static SbBool init_done = false
static SoGroup * storage = nullptr
Function Documentation
replaceSwitches()
SoNode* replaceSwitches (SoNodeList * children, SoGroup * parent)
Definition at line 274 of file SoFCDB.cpp.
References SCL.SimpleDataTypes::c, toolbit-attributes::group, SplineSurface::i, and Init::parent.
Referenced by replaceSwitchesInSceneGraph().
replaceSwitchesInSceneGraph()
SoNode* replaceSwitchesInSceneGraph (SoNode * node)
Definition at line 316 of file SoFCDB.cpp.
References replaceSwitches().
Referenced by Gui::View3DInventor::dump(), Gui::SoFCDB::replaceSwitches(), Gui::SoFCDB::writeToVRML(), and Gui::SoFCDB::writeToX3D().
Variable Documentation
init_done
SbBool init_done = false static
Definition at line 87 of file SoFCDB.cpp.
Referenced by Gui::SoFCDB::init(), and Gui::SoFCDB::isInitialized().
storage
SoGroup* storage = nullptr static
Definition at line 88 of file SoFCDB.cpp.
Referenced by Gui::SoFCDB::finish(), Gui::SoFCDB::getStorage(), Gui::SoFCDB::init(), TechDraw::DrawUtil::mergeBoundedPoint(), KDL::operator<<(), and Attacher::AttachEngine::readLinks().