FreeCAD: TechDrawGui::QGIArrow Class Reference
TechDrawGui::QGIArrow Class Reference
#include <QGIArrow.h>
Public Types
enum { Type = QGraphicsItem::UserType + 109 }
Public Types inherited from TechDrawGui::QGIPrimPath
enum { Type = QGraphicsItem::UserType + 170 }
Public Member Functions
QGIArrow ()
~QGIArrow () override
int type () const override
void draw ()
bool isFlipped ()
void setFlipped (bool flipped)
void flip ()
double getSize ()
void setSize (double s)
int getStyle ()
void setStyle (int s)
bool getDirMode ()
void setDirMode (bool b)
Base::Vector3d getDirection (void)
void setDirection (Base::Vector3d v)
void setDirection (double angle)
Public Member Functions inherited from TechDrawGui::QGIPrimPath
QGIPrimPath ()
~QGIPrimPath () override=default
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QPainterPath shape () const override
virtual void setPrettyNormal ()
virtual void setPrettyPre ()
virtual void setPrettySel ()
virtual void setWidth (double w)
virtual double getWidth ()
Qt::PenStyle getStyle ()
void setStyle (Qt::PenStyle s)
void setStyle (int s)
virtual void setNormalColor (QColor c)
virtual void setCapStyle (Qt::PenCapStyle c)
void setFillStyle (Qt::BrushStyle f)
Qt::BrushStyle getFillStyle ()
void setFill (QColor c, Qt::BrushStyle s)
void setFill (QBrush b)
void resetFill ()
void setFillColor (QColor c)
QColor getFillColor ()
void setFillOverride (bool b)
virtual void setCurrentPen ()
Static Public Member Functions
static int getPrefArrowStyle ()
static double getPrefArrowSize ()
static double getOverlapAdjust (int style, double size)
Protected Member Functions
QPainterPath makeFilledTriangle (double length, double width, bool flipped)
QPainterPath makeFilledTriangle (Base::Vector3d dir, double length, double width)
QPainterPath makeOpenArrow (double length, double width, bool flipped)
QPainterPath makeOpenArrow (Base::Vector3d dir, double length, double width)
QPainterPath makeHashMark (double length, double width, bool flipped)
QPainterPath makeHashMark (Base::Vector3d dir, double length, double width)
QPainterPath makeDot (double length, double width, bool flipped)
QPainterPath makeOpenDot (double length, double width, bool flipped)
QPainterPath makeForkArrow (double length, double width, bool flipped)
QPainterPath makeForkArrow (Base::Vector3d dir, double length, double width)
QPainterPath makePyramid (double length, bool flipped)
QPainterPath makePyramid (Base::Vector3d dir, double length)
Protected Member Functions inherited from TechDrawGui::QGIPrimPath
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
virtual bool multiselectEligible ()
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual QColor getNormalColor ()
virtual QColor getPreColor ()
virtual QColor getSelectColor ()
Base::Reference< ParameterGrp > getParmGroup ()
virtual Qt::PenCapStyle prefCapStyle ()
Additional Inherited Members
Protected Attributes inherited from TechDrawGui::QGIPrimPath
bool isHighlighted
bool multiselectActivated
QPen m_pen
QColor m_colCurrent
QColor m_colNormal
bool m_colOverride
Qt::PenStyle m_styleCurrent
Qt::PenStyle m_styleNormal
double m_width
Qt::PenCapStyle m_capStyle
QBrush m_brush
Qt::BrushStyle m_fillStyleCurrent
QColor m_fillColorCurrent
QColor m_colDefFill
QColor m_colNormalFill
Qt::BrushStyle m_fillDef
Qt::BrushStyle m_fillNormal
Qt::BrushStyle m_fillSelect
bool m_fillOverride
Detailed Description
Definition at line 51 of file QGIArrow.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 57 of file QGIArrow.h.
Constructor & Destructor Documentation
QGIArrow()
QGIArrow::QGIArrow () explicit
Definition at line 39 of file QGIArrow.cpp.
References TechDrawGui::QGIPrimPath::getNormalColor(), TechDrawGui::QGIPrimPath::m_colDefFill, TechDrawGui::QGIPrimPath::m_colNormalFill, TechDrawGui::QGIPrimPath::setFillStyle(), and setFlipped().
~QGIArrow()
TechDrawGui::QGIArrow::~QGIArrow () inline override
Definition at line 55 of file QGIArrow.h.
Member Function Documentation
draw()
void QGIArrow::draw ()
Definition at line 58 of file QGIArrow.cpp.
References DOT, TechDraw::FILLED_ARROW, TechDraw::FILLED_TRIANGLE, TechDraw::FORK, getDirection(), isFlipped(), makeDot(), makeFilledTriangle(), makeForkArrow(), makeHashMark(), makeOpenArrow(), makeOpenDot(), makePyramid(), TechDraw::OPEN_ARROW, TechDraw::OPEN_CIRCLE, and TechDraw::TICK.
Referenced by TechDrawGui::QGIViewDimension::drawArrows(), TechDrawGui::QGIViewBalloon::drawBalloon(), TechDrawGui::QGISectionLine::makeArrowsISO(), TechDrawGui::QGISectionLine::makeArrowsTrad(), and TechDrawGui::QGILeaderLine::setArrows().
flip()
void TechDrawGui::QGIArrow::flip () inline
Definition at line 64 of file QGIArrow.h.
getDirection()
Base::Vector3d TechDrawGui::QGIArrow::getDirection (void) inline
Definition at line 71 of file QGIArrow.h.
Referenced by draw().
getDirMode()
bool TechDrawGui::QGIArrow::getDirMode () inline
Definition at line 69 of file QGIArrow.h.
getOverlapAdjust()
double QGIArrow::getOverlapAdjust (int style, double size) static
Definition at line 313 of file QGIArrow.cpp.
References DOT, TechDraw::FILLED_ARROW, TechDraw::FILLED_TRIANGLE, TechDraw::FORK, NONE, TechDraw::OPEN_ARROW, TechDraw::OPEN_CIRCLE, and TechDraw::TICK.
Referenced by TechDrawGui::QGIViewBalloon::drawBalloon(), and TechDrawGui::QGILeaderLine::makeLeaderPath().
getPrefArrowSize()
double QGIArrow::getPrefArrowSize () static
Definition at line 308 of file QGIArrow.cpp.
References TechDrawGui::PreferencesGui::dimArrowSize().
Referenced by TechDrawGui::QGIViewBalloon::drawBalloon(), TechDrawGui::QGISectionLine::extensionEndsISO(), TechDrawGui::QGISectionLine::getArrowPosition(), TechDrawGui::QGISectionLine::makeArrowsISO(), TechDrawGui::QGISectionLine::makeArrowsTrad(), TechDrawGui::QGISectionLine::makeChangePointMarks(), TechDrawGui::QGILeaderLine::makeLeaderPath(), TechDrawGui::QGISectionLine::QGISectionLine(), and TechDrawGui::QGILeaderLine::setArrows().
getPrefArrowStyle()
int QGIArrow::getPrefArrowStyle () static
Definition at line 303 of file QGIArrow.cpp.
References TechDrawGui::PreferencesGui::dimArrowStyle().
Referenced by TechDrawGui::QGIViewDimension::drawArrows().
getSize()
double TechDrawGui::QGIArrow::getSize () inline
Definition at line 65 of file QGIArrow.h.
getStyle()
int TechDrawGui::QGIArrow::getStyle () inline
Definition at line 67 of file QGIArrow.h.
isFlipped()
bool TechDrawGui::QGIArrow::isFlipped () inline
Definition at line 62 of file QGIArrow.h.
Referenced by draw().
makeDot()
QPainterPath QGIArrow::makeDot (double length, double width, bool flipped) protected
Definition at line 207 of file QGIArrow.cpp.
References TechDrawGui::Rez::guiX(), and TechDrawGui::QGIPrimPath::setFillStyle().
Referenced by draw().
makeFilledTriangle() [1/2]
QPainterPath QGIArrow::makeFilledTriangle (Base::Vector3d dir, double length, double width) protected
Definition at line 122 of file QGIArrow.cpp.
References TechDrawGui::Rez::guiX(), Base::Vector3< float_type >::Normalize(), TechDrawGui::QGIPrimPath::setFillStyle(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
makeFilledTriangle() [2/2]
QPainterPath QGIArrow::makeFilledTriangle (double length, double width, bool flipped) protected
Definition at line 106 of file QGIArrow.cpp.
References TechDrawGui::Rez::guiX(), and TechDrawGui::QGIPrimPath::setFillStyle().
Referenced by draw().
makeForkArrow() [1/2]
QPainterPath QGIArrow::makeForkArrow (Base::Vector3d dir, double length, double width) protected
Definition at line 242 of file QGIArrow.cpp.
References TechDrawGui::Rez::guiX(), Base::Vector3< float_type >::Normalize(), TechDrawGui::QGIPrimPath::setFillStyle(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
makeForkArrow() [2/2]
QPainterPath QGIArrow::makeForkArrow (double length, double width, bool flipped) protected
Definition at line 227 of file QGIArrow.cpp.
References TechDrawGui::Rez::guiX(), and TechDrawGui::QGIPrimPath::setFillStyle().
Referenced by draw().
makeHashMark() [1/2]
QPainterPath QGIArrow::makeHashMark (Base::Vector3d dir, double length, double width) protected
Definition at line 189 of file QGIArrow.cpp.
References TechDrawGui::Rez::guiX(), Base::Vector3< float_type >::Normalize(), TechDrawGui::QGIPrimPath::setFillStyle(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
makeHashMark() [2/2]
QPainterPath QGIArrow::makeHashMark (double length, double width, bool flipped) protected
Definition at line 174 of file QGIArrow.cpp.
References TechDrawGui::Rez::guiX(), and TechDrawGui::QGIPrimPath::setFillStyle().
Referenced by draw().
makeOpenArrow() [1/2]
QPainterPath QGIArrow::makeOpenArrow (Base::Vector3d dir, double length, double width) protected
Definition at line 156 of file QGIArrow.cpp.
References TechDrawGui::Rez::guiX(), Base::Vector3< float_type >::Normalize(), TechDrawGui::QGIPrimPath::setFillStyle(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
makeOpenArrow() [2/2]
QPainterPath QGIArrow::makeOpenArrow (double length, double width, bool flipped) protected
Definition at line 141 of file QGIArrow.cpp.
References TechDrawGui::Rez::guiX(), and TechDrawGui::QGIPrimPath::setFillStyle().
Referenced by draw().
makeOpenDot()
QPainterPath QGIArrow::makeOpenDot (double length, double width, bool flipped) protected
Definition at line 217 of file QGIArrow.cpp.
References TechDrawGui::Rez::guiX(), and TechDrawGui::QGIPrimPath::setFillStyle().
Referenced by draw().
makePyramid() [1/2]
QPainterPath QGIArrow::makePyramid (Base::Vector3d dir, double length) protected
Definition at line 282 of file QGIArrow.cpp.
References TechDrawGui::Rez::guiX(), Base::Vector3< float_type >::Normalize(), TechDrawGui::QGIPrimPath::setFillStyle(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
makePyramid() [2/2]
QPainterPath QGIArrow::makePyramid (double length, bool flipped) protected
Definition at line 261 of file QGIArrow.cpp.
References TechDrawGui::Rez::guiX(), and TechDrawGui::QGIPrimPath::setFillStyle().
Referenced by draw().
setDirection() [1/2]
void TechDrawGui::QGIArrow::setDirection (Base::Vector3d v) inline
Definition at line 72 of file QGIArrow.h.
References TestSpreadsheet::v.
Referenced by TechDrawGui::QGIViewDimension::drawArrows(), and TechDrawGui::QGILeaderLine::setArrows().
setDirection() [2/2]
void TechDrawGui::QGIArrow::setDirection (double angle) inline
Definition at line 73 of file QGIArrow.h.
References KDL::cos(), and KDL::sin().
setDirMode()
void TechDrawGui::QGIArrow::setDirMode (bool b) inline
Definition at line 70 of file QGIArrow.h.
References SCL.SimpleDataTypes::b.
Referenced by TechDrawGui::QGIViewDimension::resetArrows(), and TechDrawGui::QGILeaderLine::setArrows().
setFlipped()
void TechDrawGui::QGIArrow::setFlipped (bool flipped) inline
Definition at line 63 of file QGIArrow.h.
Referenced by TechDrawGui::QGIViewDimension::drawArrows(), QGIArrow(), and TechDrawGui::QGIViewDimension::resetArrows().
setSize()
void QGIArrow::setSize (double s)
Definition at line 100 of file QGIArrow.cpp.
References toolbit-attributes::s.
Referenced by TechDrawGui::QGIViewDimension::drawArrows(), TechDrawGui::QGIViewBalloon::drawBalloon(), TechDrawGui::QGISectionLine::makeArrowsISO(), TechDrawGui::QGISectionLine::makeArrowsTrad(), and TechDrawGui::QGILeaderLine::setArrows().
setStyle()
void TechDrawGui::QGIArrow::setStyle (int s) inline
Definition at line 68 of file QGIArrow.h.
References toolbit-attributes::s.
Referenced by TechDrawGui::QGIViewDimension::drawArrows(), TechDrawGui::QGIViewBalloon::drawBalloon(), TechDrawGui::QGISectionLine::makeArrowsISO(), TechDrawGui::QGISectionLine::makeArrowsTrad(), TechDrawGui::QGIViewBalloon::QGIViewBalloon(), and TechDrawGui::QGILeaderLine::setArrows().
type()
int TechDrawGui::QGIArrow::type () const inline override
Definition at line 58 of file QGIArrow.h.
The documentation for this class was generated from the following files:
QGIArrow.h
QGIArrow.cpp