FreeCAD: MeshCore::MeshEvalRangeFacet Class Reference
MeshCore::MeshEvalRangeFacet Class Reference
#include <Degeneration.h>
Public Member Functions
MeshEvalRangeFacet (const MeshKernel &rclM)
bool Evaluate () override
std::vector< FacetIndex > GetIndices () const
Public Member Functions inherited from MeshCore::MeshEvaluation
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()=default
MeshEvaluation (const MeshEvaluation &)=delete
MeshEvaluation (MeshEvaluation &&)=delete
MeshEvaluation & operator= (const MeshEvaluation &)=delete
MeshEvaluation & operator= (MeshEvaluation &&)=delete
Additional Inherited Members
Protected Attributes inherited from MeshCore::MeshEvaluation
const MeshKernel & _rclMesh
Detailed Description
The MeshEvalRangeFacet class checks whether a facet points to neighbour facets that are out of range. All errors detected by this class would also be implicitly found by MeshEvalNeighbourhood. However, MeshEvalRangeFacet is used for a very fast search while MeshEvalNeighbourhood needs much more time because it can detect more errors.
See also
MeshFixRangeFacet
Author
Werner Mayer
Definition at line 622 of file Degeneration.h.
Constructor & Destructor Documentation
MeshEvalRangeFacet()
MeshCore::MeshEvalRangeFacet::MeshEvalRangeFacet (const MeshKernel & rclM) inline explicit
Construction.
Definition at line 628 of file Degeneration.h.
Member Function Documentation
Evaluate()
bool MeshEvalRangeFacet::Evaluate () override virtual
Searches for facets that has neighbour facet indices out of range.
Implements MeshCore::MeshEvaluation.
Definition at line 1068 of file Degeneration.cpp.
References MeshCore::MeshEvaluation::_rclMesh, MeshCore::FACET_INDEX_MAX, and MeshCore::MeshKernel::GetFacets().
Referenced by Mesh::MeshObject::hasFacetsOutOfRange(), and Mesh::MeshObject::validateIndices().
GetIndices()
std::vector< FacetIndex > MeshEvalRangeFacet::GetIndices () const
Returns the indices of all facets with invalid neighbour indices.
Definition at line 1084 of file Degeneration.cpp.
References MeshCore::MeshEvaluation::_rclMesh, MeshCore::FACET_INDEX_MAX, and MeshCore::MeshKernel::GetFacets().
The documentation for this class was generated from the following files:
Degeneration.h
Degeneration.cpp