FreeCAD: MeshCore::PolynomialFit Class Reference
MeshCore::PolynomialFit Class Reference
#include <Approximation.h>
Public Member Functions
PolynomialFit ()
float Fit () override
float Value (float x, float y) const
Public Member Functions inherited from MeshCore::Approximation
Approximation ()
virtual ~Approximation ()
void AddPoint (const Base::Vector3f &point)
void AddPoints (const std::vector< Base::Vector3f > &points)
void AddPoints (const std::set< Base::Vector3f > &points)
void AddPoints (const std::list< Base::Vector3f > &points)
void AddPoints (const MeshPointArray &points)
const std::list< Base::Vector3f > & GetPoints () const
Base::Vector3f GetGravity () const
std::size_t CountPoints () const
void Clear ()
float GetLastResult () const
bool Done () const
Additional Inherited Members
Protected Member Functions inherited from MeshCore::Approximation
void GetMgcVectorArray (std::vector< Wm4::Vector3< double >> &rcPts) const
Approximation (const Approximation &)=default
Approximation (Approximation &&)=default
Approximation & operator= (const Approximation &)=default
Approximation & operator= (Approximation &&)=default
Protected Attributes inherited from MeshCore::Approximation
std::list< Base::Vector3f > _vPoints
bool _bIsFitted {false}
float _fLastResult {FLOAT_MAX}
Detailed Description
Definition at line 703 of file Approximation.h.
Constructor & Destructor Documentation
PolynomialFit()
PolynomialFit::PolynomialFit ()
Definition at line 1513 of file Approximation.cpp.
Member Function Documentation
Fit()
float PolynomialFit::Fit () override virtual
Pure virtual function to fit the geometry to the given points. This function must be implemented by every subclass.
Implements MeshCore::Approximation.
Definition at line 1517 of file Approximation.cpp.
References MeshCore::Approximation::_vPoints, FLOAT_MAX, SplineSurface::i, Wm4::PolyFit3< float >(), MovieTool::x, and MovieTool::y.
Referenced by MeshCore::AbstractPolygonTriangulator::PostProcessing().
Value()
float PolynomialFit::Value (float x, float y) const
Definition at line 1542 of file Approximation.cpp.
References MovieTool::x, and MovieTool::y.
Referenced by MeshCore::AbstractPolygonTriangulator::PostProcessing().
The documentation for this class was generated from the following files:
Approximation.h
Approximation.cpp