FreeCAD: OverlayInfo Struct Reference
OverlayInfo Struct Reference
Public Member Functions
OverlayInfo (QWidget *parent, const char *name, Qt::DockWidgetArea pos, std::unordered_map< QDockWidget *, OverlayInfo * > &map)
bool addWidget (QDockWidget *dock, bool forced=true)
void removeWidget ()
void save ()
void restore ()
Public Attributes
const char * name
OverlayTabWidget * tabWidget
Qt::DockWidgetArea dockArea
std::unordered_map< QDockWidget *, OverlayInfo * > & overlayMap
ParameterGrp::handle hGrp
boost::signals2::scoped_connection conn
Detailed Description
Definition at line 185 of file OverlayManager.cpp.
Constructor & Destructor Documentation
OverlayInfo()
OverlayInfo::OverlayInfo (QWidget * parent, const char * name, Qt::DockWidgetArea pos, std::unordered_map< QDockWidget *, OverlayInfo * > & map) inline
Definition at line 193 of file OverlayManager.cpp.
References App::GetApplication(), ParameterGrp::GetGroup(), Gui::OverlayTabWidget::getProxyWidget(), App::Application::GetUserParameter(), Gui::OverlayTabWidget::isSaving(), Init::parent, and ParameterManager::signalParamChanged.
Member Function Documentation
addWidget()
bool OverlayInfo::addWidget (QDockWidget * dock, bool forced = true) inline
Definition at line 216 of file OverlayManager.cpp.
References Gui::OverlayTabWidget::addWidget(), Gui::OverlayTabWidget::dockWidgetIndex(), findTabWidget(), Gui::getMainWindow(), NavigationIndicatorGui::mw, Gui::OverlayTabWidget::saveTabs(), and Gui::OverlayTabWidget::setCurrent().
removeWidget()
void OverlayInfo::removeWidget () inline
Definition at line 255 of file OverlayManager.cpp.
References Gui::OverlayTabWidget::currentDockWidget(), Gui::OverlayTabWidget::dockWidget(), Gui::OverlayTabWidget::removeWidget(), and Gui::OverlayTabWidget::saveTabs().
restore()
void OverlayInfo::restore () inline
Definition at line 286 of file OverlayManager.cpp.
References SCL.SimpleDataTypes::c, Gui::OverlayTabWidget::dockWidget(), SplineSurface::i, and Gui::OverlayTabWidget::restore().
Referenced by src.Mod.Show.mTempoVis.TempoVis::__del__(), and Gui::OverlayManager::Private::restore().
save()
void OverlayInfo::save () inline
Definition at line 282 of file OverlayManager.cpp.
Referenced by src.Mod.Show.mTempoVis.TempoVis::modify(), src.Mod.Show.mTempoVis.TempoVis::modifyVPProperty(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle(), Gui::OverlayManager::Private::save(), src.Mod.Show.mTempoVis.TempoVis::saveCamera(), and nativeifc.ifc_viewproviders.ifc_vp_document::setupContextMenu().
Member Data Documentation
conn
boost::signals2::scoped_connection OverlayInfo::conn
Definition at line 191 of file OverlayManager.cpp.
dockArea
Qt::DockWidgetArea OverlayInfo::dockArea
Definition at line 188 of file OverlayManager.cpp.
hGrp
ParameterGrp::handle OverlayInfo::hGrp
Definition at line 190 of file OverlayManager.cpp.
name
const char* OverlayInfo::name
Definition at line 186 of file OverlayManager.cpp.
Referenced by prototype.Node::__nonzero__(), prototype.Node::__repr__(), femsolver.elmer.sifio.Section::__repr__(), draftguitools.gui_groups.Ui_AddNamedGroup::accept(), femobjects.base_fempythonobject._PropHelper::add_to_object(), prototype.Node::addtofreecad(), src.Mod.AddonManager.Addon.Addon::disable(), src.Mod.AddonManager.Addon.Addon::enable(), src.Mod.AddonManager.Addon.Addon::extract_metadata_dependencies(), src.Mod.AddonManager.addonmanager_macro.Macro::filename(), src.Mod.AddonManager.addonmanager_macro.Macro::fill_details_from_code(), src.Mod.AddonManager.addonmanager_macro.Macro::fill_details_from_wiki(), src.Mod.AddonManager.Addon.Addon::get_workbench_name(), femobjects.base_fempythonobject._PropHelper::handle_change_type(), ifc4.ifcapproval::hasidentifierorname(), src.Mod.AddonManager.addonmanager_macro.Macro::install(), src.Mod.AddonManager.Addon.Addon::is_disabled(), src.Mod.AddonManager.Addon.Addon::load_metadata_file(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.si_unit::named_unit_dimensions(), automotive_design.si_unit::named_unit_dimensions(), src.Mod.AddonManager.addonmanager_licenses.SPDXLicenseManager::normalize(), src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::output(), prototype.Node::pprint(), prototype.Node::pprint2(), Path.Base.Gui.SetupSheet.OpTaskPanel::propertyGroup(), Path.Base.Gui.SetupSheet.OpTaskPanel::propertyName(), Path.Main.Gui.Job.TaskPanel::reject(), src.Mod.AddonManager.Addon.Addon::to_cache(), src.Mod.AddonManager.Addon.Addon::try_find_wbname_in_files(), ifc2x3.ifcexternalreference::wr1(), ifc4.ifcexternalreference::wr1(), ifc2x3.ifcdocumentreference::wr1(), ifc4.ifcdocumentreference::wr1(), automotive_design.general_property_association::wr2(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.general_property_association::wr2().
overlayMap
std::unordered_map<QDockWidget*, OverlayInfo*>& OverlayInfo::overlayMap
Definition at line 189 of file OverlayManager.cpp.
tabWidget
OverlayTabWidget* OverlayInfo::tabWidget
Definition at line 187 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::Private::onTimer().
The documentation for this struct was generated from the following file:
OverlayManager.cpp