FreeCAD: Part::STEP::ImportExportSettings Class Reference
Part::STEP::ImportExportSettings Class Reference
#include <ImportExportSettings.h>
Public Member Functions
ImportExportSettings ()
void setVisibleExportDialog (bool)
bool isVisibleExportDialog () const
void setVisibleImportDialog (bool)
bool isVisibleImportDialog () const
void setWriteSurfaceCurveMode (bool)
bool getWriteSurfaceCurveMode () const
std::string getScheme () const
void setScheme (const char *)
Interface::Unit getUnit () const
void setUnit (Interface::Unit)
std::string getCompany () const
void setCompany (const char *)
std::string getAuthor () const
void setAuthor (const char *)
std::string getProductName () const
void setProductName (const char *)
Detailed Description
Definition at line 75 of file STEP/ImportExportSettings.h.
Constructor & Destructor Documentation
ImportExportSettings()
Part::STEP::ImportExportSettings::ImportExportSettings ()
Definition at line 75 of file STEP/ImportExportSettings.cpp.
References ParameterGrp::GetASCII().
Member Function Documentation
getAuthor()
std::string Part::STEP::ImportExportSettings::getAuthor () const
Definition at line 147 of file STEP/ImportExportSettings.cpp.
Referenced by PartGui::DlgExportHeaderStep::loadSettings().
getCompany()
std::string Part::STEP::ImportExportSettings::getCompany () const
Definition at line 137 of file STEP/ImportExportSettings.cpp.
Referenced by PartGui::DlgExportHeaderStep::loadSettings().
getProductName()
std::string Part::STEP::ImportExportSettings::getProductName () const
Definition at line 157 of file STEP/ImportExportSettings.cpp.
Referenced by PartGui::DlgExportHeaderStep::loadSettings().
getScheme()
std::string Part::STEP::ImportExportSettings::getScheme () const
Definition at line 115 of file STEP/ImportExportSettings.cpp.
Referenced by PartGui::DlgExportStep::loadSettings().
getUnit()
Interface::Unit Part::STEP::ImportExportSettings::getUnit () const
Definition at line 126 of file STEP/ImportExportSettings.cpp.
Referenced by PartGui::DlgExportStep::loadSettings().
getWriteSurfaceCurveMode()
bool Part::STEP::ImportExportSettings::getWriteSurfaceCurveMode () const
Definition at line 107 of file STEP/ImportExportSettings.cpp.
References ParameterGrp::GetASCII().
Referenced by PartGui::DlgExportStep::loadSettings().
isVisibleExportDialog()
bool Part::STEP::ImportExportSettings::isVisibleExportDialog () const
Definition at line 85 of file STEP/ImportExportSettings.cpp.
References ParameterGrp::GetInt().
Referenced by PartGui::TaskExportStep::showDialog().
isVisibleImportDialog()
bool Part::STEP::ImportExportSettings::isVisibleImportDialog () const
Definition at line 95 of file STEP/ImportExportSettings.cpp.
Referenced by PartGui::TaskImportStep::showDialog().
setAuthor()
void Part::STEP::ImportExportSettings::setAuthor (const char * name)
Definition at line 152 of file STEP/ImportExportSettings.cpp.
Referenced by PartGui::DlgExportHeaderStep::saveSettings().
setCompany()
void Part::STEP::ImportExportSettings::setCompany (const char * name)
Definition at line 142 of file STEP/ImportExportSettings.cpp.
Referenced by PartGui::DlgExportHeaderStep::saveSettings().
setProductName()
void Part::STEP::ImportExportSettings::setProductName (const char * name)
Definition at line 162 of file STEP/ImportExportSettings.cpp.
setScheme()
void Part::STEP::ImportExportSettings::setScheme (const char * scheme)
Definition at line 120 of file STEP/ImportExportSettings.cpp.
Referenced by PartGui::DlgExportStep::saveSettings().
setUnit()
void Part::STEP::ImportExportSettings::setUnit (Interface::Unit unit)
Definition at line 131 of file STEP/ImportExportSettings.cpp.
Referenced by PartGui::DlgExportStep::saveSettings().
setVisibleExportDialog()
void Part::STEP::ImportExportSettings::setVisibleExportDialog (bool on)
Definition at line 80 of file STEP/ImportExportSettings.cpp.
References ParameterGrp::SetASCII().
Referenced by PartGui::TaskExportStep::accept().
setVisibleImportDialog()
void Part::STEP::ImportExportSettings::setVisibleImportDialog (bool on)
Definition at line 90 of file STEP/ImportExportSettings.cpp.
References ParameterGrp::SetInt(), unit(), and Part::Interface::writeStepUnit().
Referenced by PartGui::TaskImportStep::accept().
setWriteSurfaceCurveMode()
void Part::STEP::ImportExportSettings::setWriteSurfaceCurveMode (bool on)
Definition at line 100 of file STEP/ImportExportSettings.cpp.
Referenced by PartGui::DlgExportStep::saveSettings().
The documentation for this class was generated from the following files:
STEP/ImportExportSettings.h
STEP/ImportExportSettings.cpp