FreeCAD: Gui::PythonDebugStdout Class Reference
Gui::PythonDebugStdout Class Reference
#include <PythonDebugger.h>
Public Member Functions
PythonDebugStdout ()
~PythonDebugStdout () override
Py::Object repr () override
Py::Object write (const Py::Tuple &)
Py::Object flush (const Py::Tuple &)
Static Public Member Functions
static void init_type ()
Detailed Description
Author
Werner Mayer
Definition at line 135 of file PythonDebugger.h.
Constructor & Destructor Documentation
PythonDebugStdout()
PythonDebugStdout::PythonDebugStdout () default
~PythonDebugStdout()
PythonDebugStdout::~PythonDebugStdout () override default
Member Function Documentation
flush()
Py::Object PythonDebugStdout::flush (const Py::Tuple &)
Definition at line 196 of file PythonDebugger.cpp.
Referenced by init_type().
init_type()
void PythonDebugStdout::init_type () static
Definition at line 154 of file PythonDebugger.cpp.
References flush(), and write().
Referenced by Gui::PythonDebugModule::init_module().
repr()
Py::Object PythonDebugStdout::repr () override
Definition at line 168 of file PythonDebugger.cpp.
References toolbit-attributes::s, and src.Mod.Test.testmakeWireString::String.
write()
Py::Object PythonDebugStdout::write (const Py::Tuple & args)
Definition at line 176 of file PythonDebugger.cpp.
References toolbit-attributes::args, and Path.Op.Surface::msg.
Referenced by init_type().
The documentation for this class was generated from the following files:
PythonDebugger.h
PythonDebugger.cpp