FreeCAD: Gui::View3DInventorPy Class Reference
Gui::View3DInventorPy Class Reference
#include <View3DPy.h>
Public Types
using BaseType = Py::PythonExtension< View3DInventorPy >
Public Member Functions
View3DInventorPy (View3DInventor *vi)
~View3DInventorPy () override
View3DInventor * getView3DInventorPtr ()
Py::Object repr () override
Py::Object getattr (const char *) override
int setattr (const char *, const Py::Object &) override
Py::Object cast_to_base ()
Py::Object fitAll (const Py::Tuple &)
Py::Object boxZoom (const Py::Tuple &, const Py::Dict &)
Py::Object viewBottom ()
Py::Object viewFront ()
Py::Object viewLeft ()
Py::Object viewRear ()
Py::Object viewRight ()
Py::Object viewTop ()
Py::Object viewIsometric ()
Py::Object viewDimetric ()
Py::Object viewTrimetric ()
Py::Object viewDefaultOrientation (const Py::Tuple &)
Py::Object viewPosition (const Py::Tuple &)
Py::Object viewRotateLeft ()
Py::Object viewRotateRight ()
Py::Object zoomIn ()
Py::Object zoomOut ()
Py::Object startAnimating (const Py::Tuple &)
Py::Object stopAnimating ()
Py::Object setAnimationEnabled (const Py::Tuple &)
Py::Object isAnimationEnabled ()
Py::Object setPopupMenuEnabled (const Py::Tuple &)
Py::Object isPopupMenuEnabled ()
Py::Object dump (const Py::Tuple &)
Py::Object dumpNode (const Py::Tuple &)
Py::Object setStereoType (const Py::Tuple &)
Py::Object getStereoType ()
Py::Object listStereoTypes ()
Py::Object saveImage (const Py::Tuple &)
Py::Object saveVectorGraphic (const Py::Tuple &)
Py::Object getCamera ()
Py::Object getViewDirection ()
Py::Object getUpDirection ()
Py::Object setViewDirection (const Py::Tuple &)
Py::Object setCamera (const Py::Tuple &)
Py::Object setCameraOrientation (const Py::Tuple &)
Py::Object getCameraOrientation ()
Py::Object getCameraType ()
Py::Object setCameraType (const Py::Tuple &)
Py::Object getCameraNode ()
Py::Object listCameraTypes ()
Py::Object getCursorPos ()
Py::Object getObjectInfo (const Py::Tuple &)
Py::Object getObjectsInfo (const Py::Tuple &)
Py::Object getSize ()
Py::Object getObjectInfoRay (const Py::Tuple &)
Py::Object getPointOnFocalPlane (const Py::Tuple &)
Py::Object projectPointToLine (const Py::Tuple &)
Py::Object getPointOnViewport (const Py::Tuple &)
Py::Object addEventCallback (const Py::Tuple &)
Py::Object removeEventCallback (const Py::Tuple &)
Py::Object setAnnotation (const Py::Tuple &)
Py::Object removeAnnotation (const Py::Tuple &)
Py::Object getSceneGraph ()
Py::Object getViewer ()
Py::Object addEventCallbackPivy (const Py::Tuple &)
Py::Object removeEventCallbackPivy (const Py::Tuple &)
Py::Object listNavigationTypes ()
Py::Object getNavigationType ()
Py::Object setNavigationType (const Py::Tuple &)
Py::Object setAxisCross (const Py::Tuple &)
Py::Object hasAxisCross ()
Py::Object addDraggerCallback (const Py::Tuple &)
Py::Object removeDraggerCallback (const Py::Tuple &)
Py::Object getViewProvidersOfType (const Py::Tuple &)
Py::Object redraw ()
Py::Object setName (const Py::Tuple &)
Py::Object toggleClippingPlane (const Py::Tuple &args, const Py::Dict &)
Py::Object hasClippingPlane ()
Py::Object graphicsView ()
Py::Object setCornerCrossVisible (const Py::Tuple &args)
Py::Object isCornerCrossVisible ()
Py::Object setCornerCrossSize (const Py::Tuple &args)
Py::Object getCornerCrossSize ()
Static Public Member Functions
static void init_type ()
Detailed Description
Definition at line 38 of file View3DPy.h.
Member Typedef Documentation
BaseType
using Gui::View3DInventorPy::BaseType = Py::PythonExtension<View3DInventorPy>
Definition at line 41 of file View3DPy.h.
Constructor & Destructor Documentation
View3DInventorPy()
View3DInventorPy::View3DInventorPy (View3DInventor * vi) explicit
Definition at line 238 of file View3DPy.cpp.
~View3DInventorPy()
View3DInventorPy::~View3DInventorPy () override
Definition at line 243 of file View3DPy.cpp.
Member Function Documentation
addDraggerCallback()
Py::Object View3DInventorPy::addDraggerCallback (const Py::Tuple & args)
Definition at line 2358 of file View3DPy.cpp.
References toolbit-attributes::args, Base::InterpreterSingleton::convertSWIGPointerObj(), Base::Interpreter(), toolbit-attributes::s, and Path.Post.scripts.grbl_post::type.
Referenced by init_type().
addEventCallback()
Py::Object View3DInventorPy::addEventCallback (const Py::Tuple & args)
Definition at line 2040 of file View3DPy.cpp.
References Gui::View3DInventorViewer::addEventCallback(), toolbit-attributes::args, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), and toolbit-attributes::s.
Referenced by init_type().
addEventCallbackPivy()
Py::Object View3DInventorPy::addEventCallbackPivy (const Py::Tuple & args)
Definition at line 2222 of file View3DPy.cpp.
References Gui::View3DInventorViewer::addEventCallback(), toolbit-attributes::args, Base::InterpreterSingleton::convertSWIGPointerObj(), SCL.SimpleDataTypes::e, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Base::Interpreter(), and toolbit-attributes::s.
Referenced by init_type().
boxZoom()
Py::Object View3DInventorPy::boxZoom (const Py::Tuple & args, const Py::Dict & kwds)
Definition at line 376 of file View3DPy.cpp.
References toolbit-attributes::args, MengerSponge::box, Gui::View3DInventorViewer::boxZoom(), getView3DInventorPtr(), Gui::View3DInventor::getViewer(), and Base::Wrapped_ParseTupleAndKeywords().
Referenced by init_type().
cast_to_base()
Py::Object View3DInventorPy::cast_to_base ()
Definition at line 2571 of file View3DPy.cpp.
References Gui::MDIViewPy::create(), and getView3DInventorPtr().
Referenced by init_type().
dump()
Py::Object View3DInventorPy::dump (const Py::Tuple & args)
Definition at line 1152 of file View3DPy.cpp.
References toolbit-attributes::args, Base::asBoolean(), Gui::View3DInventor::dump(), SCL.SimpleDataTypes::e, and getView3DInventorPtr().
Referenced by init_type().
dumpNode()
Py::Object View3DInventorPy::dumpNode (const Py::Tuple & args)
Definition at line 1174 of file View3DPy.cpp.
References toolbit-attributes::args, Base::InterpreterSingleton::convertSWIGPointerObj(), SCL.SimpleDataTypes::e, Base::Interpreter(), src.Mod.Test.testmakeWireString::String, and Gui::SoFCDB::writeNodesToString().
Referenced by init_type().
fitAll()
Py::Object View3DInventorPy::fitAll (const Py::Tuple & args)
Definition at line 355 of file View3DPy.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::viewAll().
Referenced by init_type().
getattr()
Py::Object View3DInventorPy::getattr (const char * attr) override
Definition at line 313 of file View3DPy.cpp.
References Gui::MDIView::getActiveObject(), App::DocumentObject::getPyObject(), and getView3DInventorPtr().
getCamera()
Py::Object View3DInventorPy::getCamera ()
Definition at line 962 of file View3DPy.cpp.
References SCL.SimpleDataTypes::e, SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), getView3DInventorPtr(), Gui::View3DInventor::getViewer(), and src.Mod.Test.testmakeWireString::String.
Referenced by init_type().
getCameraNode()
Py::Object View3DInventorPy::getCameraNode ()
Definition at line 944 of file View3DPy.cpp.
References Base::InterpreterSingleton::createSWIGPointerObj(), SCL.SimpleDataTypes::e, SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Base::Interpreter(), and Path.Post.scripts.grbl_post::type.
Referenced by init_type().
getCameraOrientation()
Py::Object View3DInventorPy::getCameraOrientation ()
Definition at line 778 of file View3DPy.cpp.
References Gui::View3DInventorViewer::getCameraOrientation(), getView3DInventorPtr(), and Gui::View3DInventor::getViewer().
Referenced by init_type().
getCameraType()
Py::Object View3DInventorPy::getCameraType ()
Definition at line 1083 of file View3DPy.cpp.
References CameraTypeEnums, SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), getView3DInventorPtr(), Gui::View3DInventor::getViewer(), and src.Mod.Test.testmakeWireString::String.
Referenced by init_type().
getCornerCrossSize()
Py::Object View3DInventorPy::getCornerCrossSize ()
Definition at line 2565 of file View3DPy.cpp.
References Gui::View3DInventorViewer::getFeedbackSize(), getView3DInventorPtr(), and Gui::View3DInventor::getViewer().
Referenced by init_type().
getCursorPos()
Py::Object View3DInventorPy::getCursorPos ()
Definition at line 1278 of file View3DPy.cpp.
References getView3DInventorPtr(), Gui::View3DInventor::getViewer(), RobotExample::pos, SurfaceTests.TestBlendCurve::vec, and OfflineRenderingUtils::viewer().
Referenced by init_type().
getNavigationType()
Py::Object View3DInventorPy::getNavigationType ()
Definition at line 1664 of file View3DPy.cpp.
References Base::Type::getName(), Base::BaseClass::getTypeId(), getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Gui::View3DInventorViewer::navigationStyle(), and src.Mod.Test.testmakeWireString::String.
Referenced by init_type().
getObjectInfo()
Py::Object View3DInventorPy::getObjectInfo (const Py::Tuple & args)
Definition at line 1294 of file View3DPy.cpp.
References Path.Post.scripts.dynapath_4060_post::action, toolbit-attributes::args, Gui::SoFCDocumentObjectAction::componentName, Path.Base.SetupSheet::dict, Gui::SoFCDocumentObjectAction::documentName, Base::Persistence::getClassTypeId(), Gui::ViewProvider::getElementPicked(), Gui::ViewProviderDocumentObject::getObject(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getPickRadius(), getSceneGraph(), getView3DInventorPtr(), getViewer(), Gui::View3DInventor::getViewer(), Gui::View3DInventorViewer::getViewProviderByPath(), Base::BaseClass::isDerivedFrom(), Gui::SoFCDocumentObjectAction::isHandled(), Gui::ViewProvider::isSelectable(), App::ElementNamePair::newName, Gui::SoFCDocumentObjectAction::objectName, App::ElementNamePair::oldName, App::GeoFeature::resolveElement(), src.Mod.Test.testmakeWireString::String, Gui::ViewProvider::useNewSelectionModel(), MovieTool::x, and MovieTool::y.
Referenced by init_type().
getObjectInfoRay()
Py::Object View3DInventorPy::getObjectInfoRay (const Py::Tuple & args)
Definition at line 1512 of file View3DPy.cpp.
References toolbit-attributes::args, Gui::RayPickInfo::component, Path.Base.SetupSheet::dict, Gui::RayPickInfo::document, Gui::View3DInventor::getObjInfoRay(), getView3DInventorPtr(), Gui::RayPickInfo::isValid, Gui::RayPickInfo::object, Gui::RayPickInfo::parentObject, Gui::RayPickInfo::point, src.Mod.Test.testmakeWireString::String, Gui::RayPickInfo::subName, and CAMTests.TestPathVoronoi::vd.
Referenced by init_type().
getObjectsInfo()
Py::Object View3DInventorPy::getObjectsInfo (const Py::Tuple & args)
Definition at line 1400 of file View3DPy.cpp.
References Path.Post.scripts.dynapath_4060_post::action, toolbit-attributes::args, Gui::SoFCDocumentObjectAction::componentName, Path.Base.SetupSheet::dict, Gui::SoFCDocumentObjectAction::documentName, Base::Persistence::getClassTypeId(), Gui::ViewProvider::getElementPicked(), Gui::ViewProviderDocumentObject::getObject(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getPickRadius(), getSceneGraph(), getView3DInventorPtr(), getViewer(), Gui::View3DInventor::getViewer(), Gui::View3DInventorViewer::getViewProviderByPath(), SplineSurface::i, Base::BaseClass::isDerivedFrom(), Gui::SoFCDocumentObjectAction::isHandled(), Gui::ViewProvider::isSelectable(), App::ElementNamePair::newName, Gui::SoFCDocumentObjectAction::objectName, App::ElementNamePair::oldName, App::GeoFeature::resolveElement(), src.Mod.Test.testmakeWireString::String, Gui::ViewProvider::useNewSelectionModel(), MovieTool::x, and MovieTool::y.
Referenced by init_type().
getPointOnFocalPlane()
Py::Object View3DInventorPy::getPointOnFocalPlane (const Py::Tuple & args)
Definition at line 1574 of file View3DPy.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, Gui::View3DInventorViewer::getPointOnFocalPlane(), getView3DInventorPtr(), Gui::View3DInventor::getViewer(), InitGui::t, MovieTool::x, and MovieTool::y.
Referenced by init_type().
getPointOnViewport()
Py::Object View3DInventorPy::getPointOnViewport (const Py::Tuple & args)
Definition at line 1595 of file View3DPy.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, Gui::View3DInventorViewer::getPointOnViewport(), getView3DInventorPtr(), Gui::View3DInventor::getViewer(), TestSpreadsheet::v, and SurfaceTests.TestBlendCurve::vec.
Referenced by init_type().
getSceneGraph()
Py::Object View3DInventorPy::getSceneGraph ()
Definition at line 2134 of file View3DPy.cpp.
References Base::InterpreterSingleton::createSWIGPointerObj(), SCL.SimpleDataTypes::e, SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph(), getView3DInventorPtr(), Gui::View3DInventor::getViewer(), and Base::Interpreter().
Referenced by getObjectInfo(), getObjectsInfo(), and init_type().
getSize()
Py::Object View3DInventorPy::getSize ()
Definition at line 1560 of file View3DPy.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), getView3DInventorPtr(), and Gui::View3DInventor::getViewer().
Referenced by init_type().
getStereoType()
Py::Object View3DInventorPy::getStereoType ()
Definition at line 1238 of file View3DPy.cpp.
References SCL.SimpleDataTypes::e, getView3DInventorPtr(), getViewer(), StereoTypeEnums, and src.Mod.Test.testmakeWireString::String.
Referenced by init_type().
getUpDirection()
Py::Object View3DInventorPy::getUpDirection ()
Definition at line 1004 of file View3DPy.cpp.
References SCL.SimpleDataTypes::e, Gui::View3DInventorViewer::getUpDirection(), getView3DInventorPtr(), and Gui::View3DInventor::getViewer().
Referenced by init_type().
getView3DInventorPtr()
View3DInventor * View3DInventorPy::getView3DInventorPtr ()
Definition at line 250 of file View3DPy.cpp.
Referenced by addEventCallback(), addEventCallbackPivy(), boxZoom(), cast_to_base(), dump(), fitAll(), getattr(), getCamera(), getCameraNode(), getCameraOrientation(), getCameraType(), getCornerCrossSize(), getCursorPos(), getNavigationType(), getObjectInfo(), getObjectInfoRay(), getObjectsInfo(), getPointOnFocalPlane(), getPointOnViewport(), getSceneGraph(), getSize(), getStereoType(), getUpDirection(), getViewDirection(), getViewer(), getViewProvidersOfType(), graphicsView(), hasAxisCross(), hasClippingPlane(), isAnimationEnabled(), isCornerCrossVisible(), isPopupMenuEnabled(), projectPointToLine(), redraw(), removeAnnotation(), removeEventCallback(), removeEventCallbackPivy(), repr(), saveImage(), saveVectorGraphic(), setAnimationEnabled(), setAnnotation(), setattr(), setAxisCross(), setCamera(), setCameraOrientation(), setCameraType(), setCornerCrossSize(), setCornerCrossVisible(), setName(), setNavigationType(), setPopupMenuEnabled(), setStereoType(), setViewDirection(), startAnimating(), stopAnimating(), toggleClippingPlane(), viewBottom(), viewDefaultOrientation(), viewDimetric(), viewFront(), viewIsometric(), viewLeft(), viewPosition(), viewRear(), viewRight(), viewRotateLeft(), viewRotateRight(), viewTop(), viewTrimetric(), zoomIn(), and zoomOut().
getViewDirection()
Py::Object View3DInventorPy::getViewDirection ()
Definition at line 986 of file View3DPy.cpp.
References SCL.SimpleDataTypes::e, getView3DInventorPtr(), Gui::View3DInventorViewer::getViewDirection(), and Gui::View3DInventor::getViewer().
Referenced by init_type().
getViewer()
Py::Object View3DInventorPy::getViewer ()
Definition at line 2148 of file View3DPy.cpp.
References getView3DInventorPtr(), Gui::View3DInventor::getViewer(), and OfflineRenderingUtils::viewer().
Referenced by getObjectInfo(), getObjectsInfo(), getStereoType(), graphicsView(), hasClippingPlane(), and init_type().
getViewProvidersOfType()
Py::Object View3DInventorPy::getViewProvidersOfType (const Py::Tuple & args)
Definition at line 2464 of file View3DPy.cpp.
References toolbit-attributes::args, Base::Type::fromName(), getView3DInventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::getViewProvidersOfType().
Referenced by init_type().
graphicsView()
Py::Object View3DInventorPy::graphicsView ()
Definition at line 2532 of file View3DPy.cpp.
References Gui::PythonWrapper::fromQWidget(), getView3DInventorPtr(), getViewer(), and Gui::PythonWrapper::loadWidgetsModule().
Referenced by init_type().
hasAxisCross()
Py::Object View3DInventorPy::hasAxisCross ()
Definition at line 2321 of file View3DPy.cpp.
References getView3DInventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::hasAxisCross().
Referenced by init_type().
hasClippingPlane()
Py::Object View3DInventorPy::hasClippingPlane ()
Definition at line 2527 of file View3DPy.cpp.
References getView3DInventorPtr(), and getViewer().
Referenced by init_type().
init_type()
void View3DInventorPy::init_type () static
Definition at line 75 of file View3DPy.cpp.
References addDraggerCallback(), addEventCallback(), addEventCallbackPivy(), boxZoom(), cast_to_base(), dump(), dumpNode(), fitAll(), getCamera(), getCameraNode(), getCameraOrientation(), getCameraType(), getCornerCrossSize(), getCursorPos(), getNavigationType(), getObjectInfo(), getObjectInfoRay(), getObjectsInfo(), getPointOnFocalPlane(), getPointOnViewport(), getSceneGraph(), getSize(), getStereoType(), getUpDirection(), getViewDirection(), getViewer(), getViewProvidersOfType(), graphicsView(), hasAxisCross(), hasClippingPlane(), isAnimationEnabled(), isCornerCrossVisible(), isPopupMenuEnabled(), listCameraTypes(), listNavigationTypes(), listStereoTypes(), projectPointToLine(), redraw(), removeAnnotation(), removeDraggerCallback(), removeEventCallback(), removeEventCallbackPivy(), saveImage(), saveVectorGraphic(), setAnimationEnabled(), setAnnotation(), setAxisCross(), setCamera(), setCameraOrientation(), setCameraType(), setCornerCrossSize(), setCornerCrossVisible(), setName(), setNavigationType(), setPopupMenuEnabled(), setStereoType(), setViewDirection(), startAnimating(), stopAnimating(), toggleClippingPlane(), viewBottom(), viewDefaultOrientation(), viewDimetric(), viewFront(), viewIsometric(), viewLeft(), viewPosition(), viewRear(), viewRight(), viewRotateLeft(), viewRotateRight(), viewTop(), viewTrimetric(), zoomIn(), and zoomOut().
Referenced by Gui::Application::Application().
isAnimationEnabled()
Py::Object View3DInventorPy::isAnimationEnabled ()
Definition at line 844 of file View3DPy.cpp.
References getView3DInventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::isAnimationEnabled().
Referenced by init_type().
isCornerCrossVisible()
Py::Object View3DInventorPy::isCornerCrossVisible ()
Definition at line 2549 of file View3DPy.cpp.
References getView3DInventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::isFeedbackVisible().
Referenced by init_type().
isPopupMenuEnabled()
Py::Object View3DInventorPy::isPopupMenuEnabled ()
Definition at line 859 of file View3DPy.cpp.
References getView3DInventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::isPopupMenuEnabled().
Referenced by init_type().
listCameraTypes()
Py::Object View3DInventorPy::listCameraTypes ()
Definition at line 1132 of file View3DPy.cpp.
References CameraTypeEnums, SCL.SimpleDataTypes::e, SplineSurface::i, and src.Mod.Test.testmakeWireString::String.
Referenced by init_type().
listNavigationTypes()
Py::Object View3DInventorPy::listNavigationTypes ()
Definition at line 1653 of file View3DPy.cpp.
References Base::Type::getAllDerivedFrom(), Base::BaseClass::getClassTypeId(), and src.Mod.Test.testmakeWireString::String.
Referenced by init_type().
listStereoTypes()
Py::Object View3DInventorPy::listStereoTypes ()
Definition at line 1257 of file View3DPy.cpp.
References SCL.SimpleDataTypes::e, SplineSurface::i, StereoTypeEnums, and src.Mod.Test.testmakeWireString::String.
Referenced by init_type().
projectPointToLine()
Py::Object View3DInventorPy::projectPointToLine (const Py::Tuple & args)
Definition at line 1628 of file View3DPy.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Gui::View3DInventorViewer::projectPointToLine(), InitGui::t, MovieTool::x, and MovieTool::y.
Referenced by init_type().
redraw()
Py::Object View3DInventorPy::redraw ()
Definition at line 2479 of file View3DPy.cpp.
References getView3DInventorPtr(), Gui::View3DInventor::getViewer(), and SIM::Coin3D::Quarter::QuarterWidget::redraw().
Referenced by init_type(), and draftguitools.gui_trimex.Trimex::trimObject().
removeAnnotation()
Py::Object View3DInventorPy::removeAnnotation (const Py::Tuple & args)
Definition at line 2115 of file View3DPy.cpp.
References toolbit-attributes::args, Gui::Document::getAnnotationViewProvider(), Gui::BaseView::getGuiDocument(), getView3DInventorPtr(), Gui::Document::removeAnnotationViewProvider(), and toolbit-attributes::s.
Referenced by init_type().
removeDraggerCallback()
Py::Object View3DInventorPy::removeDraggerCallback (const Py::Tuple & args)
Definition at line 2414 of file View3DPy.cpp.
References toolbit-attributes::args, Base::InterpreterSingleton::convertSWIGPointerObj(), Base::Interpreter(), toolbit-attributes::s, and Path.Post.scripts.grbl_post::type.
Referenced by init_type().
removeEventCallback()
Py::Object View3DInventorPy::removeEventCallback (const Py::Tuple & args)
Definition at line 2068 of file View3DPy.cpp.
References toolbit-attributes::args, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Gui::View3DInventorViewer::removeEventCallback(), and toolbit-attributes::s.
Referenced by init_type().
removeEventCallbackPivy()
Py::Object View3DInventorPy::removeEventCallbackPivy (const Py::Tuple & args)
Definition at line 2267 of file View3DPy.cpp.
References toolbit-attributes::args, Base::InterpreterSingleton::convertSWIGPointerObj(), SCL.SimpleDataTypes::e, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Base::Interpreter(), Gui::View3DInventorViewer::removeEventCallback(), and toolbit-attributes::s.
Referenced by init_type().
repr()
Py::Object View3DInventorPy::repr () override
Definition at line 255 of file View3DPy.cpp.
References getView3DInventorPtr(), toolbit-attributes::s, and src.Mod.Test.testmakeWireString::String.
saveImage()
Py::Object View3DInventorPy::saveImage (const Py::Tuple & args)
Definition at line 865 of file View3DPy.cpp.
References toolbit-attributes::args, Gui::View3DInventorViewer::getNumSamples(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Gui::SoFCOffscreenRenderer::instance(), toolbit-attributes::s, Gui::View3DInventorViewer::savePicture(), src.Mod.PartDesign.fcgear.svggear::w, and Gui::SoFCOffscreenRenderer::writeToImageFile().
Referenced by init_type().
saveVectorGraphic()
Py::Object View3DInventorPy::saveVectorGraphic (const Py::Tuple & args)
Definition at line 900 of file View3DPy.cpp.
References toolbit-attributes::args, SIM::Coin3D::Quarter::QuarterWidget::backgroundColor, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Base::FileInfo::hasExtension(), and Gui::View3DInventorViewer::saveGraphic().
Referenced by init_type().
setAnimationEnabled()
Py::Object View3DInventorPy::setAnimationEnabled (const Py::Tuple & args)
Definition at line 835 of file View3DPy.cpp.
References toolbit-attributes::args, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::setAnimationEnabled().
Referenced by init_type().
setAnnotation()
Py::Object View3DInventorPy::setAnnotation (const Py::Tuple & args)
Definition at line 2096 of file View3DPy.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, Gui::BaseView::getGuiDocument(), getView3DInventorPtr(), Gui::Document::setAnnotationViewProvider(), and Gui::ViewProviderExtern::setModeByString().
Referenced by init_type().
setattr()
int View3DInventorPy::setattr (const char * attr, const Py::Object & value) override
Definition at line 342 of file View3DPy.cpp.
References getView3DInventorPtr(), and toolbit-attributes::s.
setAxisCross()
Py::Object View3DInventorPy::setAxisCross (const Py::Tuple & args)
Definition at line 2312 of file View3DPy.cpp.
References toolbit-attributes::args, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::setAxisCross().
Referenced by init_type().
setCamera()
Py::Object View3DInventorPy::setCamera (const Py::Tuple & args)
Definition at line 1059 of file View3DPy.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, getView3DInventorPtr(), and Gui::View3DInventor::setCamera().
Referenced by init_type().
setCameraOrientation()
Py::Object View3DInventorPy::setCameraOrientation (const Py::Tuple & args)
Definition at line 736 of file View3DPy.cpp.
References toolbit-attributes::args, Base::asBoolean(), SCL.SimpleDataTypes::e, Base::Rotation::getValue(), getView3DInventorPtr(), Gui::View3DInventor::getViewer(), test::m, src.Mod.Test.testPathArray::o, and Gui::View3DInventorViewer::setCameraOrientation().
Referenced by init_type().
setCameraType()
Py::Object View3DInventorPy::setCameraType (const Py::Tuple & args)
Definition at line 1100 of file View3DPy.cpp.
References toolbit-attributes::args, CameraTypeEnums, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), SplineSurface::i, toolbit-attributes::s, and Gui::View3DInventorViewer::setCameraType().
Referenced by init_type().
setCornerCrossSize()
Py::Object View3DInventorPy::setCornerCrossSize (const Py::Tuple & args)
Definition at line 2555 of file View3DPy.cpp.
References toolbit-attributes::args, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), SIM::Coin3D::Quarter::QuarterWidget::redraw(), and Gui::View3DInventorViewer::setFeedbackSize().
Referenced by init_type().
setCornerCrossVisible()
Py::Object View3DInventorPy::setCornerCrossVisible (const Py::Tuple & args)
Definition at line 2539 of file View3DPy.cpp.
References toolbit-attributes::args, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), SIM::Coin3D::Quarter::QuarterWidget::redraw(), and Gui::View3DInventorViewer::setFeedbackVisibility().
Referenced by init_type().
setName()
Py::Object View3DInventorPy::setName (const Py::Tuple & args)
Definition at line 2485 of file View3DPy.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, and getView3DInventorPtr().
Referenced by init_type().
setNavigationType()
Py::Object View3DInventorPy::setNavigationType (const Py::Tuple & args)
Definition at line 1670 of file View3DPy.cpp.
References toolbit-attributes::args, Base::Type::fromName(), getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Gui::View3DInventorViewer::setNavigationType(), and Path.Post.scripts.grbl_post::type.
Referenced by init_type().
setPopupMenuEnabled()
Py::Object View3DInventorPy::setPopupMenuEnabled (const Py::Tuple & args)
Definition at line 850 of file View3DPy.cpp.
References toolbit-attributes::args, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::setPopupMenuEnabled().
Referenced by init_type().
setStereoType()
Py::Object View3DInventorPy::setStereoType (const Py::Tuple & args)
Definition at line 1197 of file View3DPy.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), SplineSurface::i, toolbit-attributes::s, SIM::Coin3D::Quarter::QuarterWidget::setStereoMode(), and StereoTypeEnums.
Referenced by init_type().
setViewDirection()
Py::Object View3DInventorPy::setViewDirection (const Py::Tuple & args)
Definition at line 1021 of file View3DPy.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Gui::View3DInventorViewer::setViewDirection(), MovieTool::x, and MovieTool::y.
Referenced by init_type().
startAnimating()
Py::Object View3DInventorPy::startAnimating (const Py::Tuple & args)
Definition at line 819 of file View3DPy.cpp.
References toolbit-attributes::args, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Gui::View3DInventorViewer::startSpinningAnimation(), MovieTool::x, and MovieTool::y.
Referenced by init_type().
stopAnimating()
Py::Object View3DInventorPy::stopAnimating ()
Definition at line 829 of file View3DPy.cpp.
References getView3DInventorPtr(), Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::stopAnimating().
Referenced by init_type().
toggleClippingPlane()
Py::Object View3DInventorPy::toggleClippingPlane (const Py::Tuple & args, const Py::Dict & kwds)
Definition at line 2506 of file View3DPy.cpp.
References toolbit-attributes::args, Base::asBoolean(), getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Gui::View3DInventorViewer::toggleClippingPlane(), and Base::Wrapped_ParseTupleAndKeywords().
Referenced by init_type().
viewBottom()
Py::Object View3DInventorPy::viewBottom ()
Definition at line 390 of file View3DPy.cpp.
References Gui::Camera::Bottom, SCL.SimpleDataTypes::e, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Gui::Camera::rotation(), and Gui::View3DInventorViewer::setCameraOrientation().
Referenced by init_type().
viewDefaultOrientation()
Py::Object View3DInventorPy::viewDefaultOrientation (const Py::Tuple & args)
Definition at line 552 of file View3DPy.cpp.
References toolbit-attributes::args, Gui::Camera::Bottom, Gui::Camera::Dimetric, SCL.SimpleDataTypes::e, Gui::Camera::Front, App::GetApplication(), ParameterGrp::GetASCII(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getCamera(), ParameterGrp::GetFloat(), App::Application::GetParameterGroupByPath(), getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Gui::Camera::Isometric, Gui::Camera::Left, Gui::Camera::Rear, Gui::Camera::Right, Gui::Camera::rotation(), Gui::Camera::Top, and Gui::Camera::Trimetric.
Referenced by init_type().
viewDimetric()
Py::Object View3DInventorPy::viewDimetric ()
Definition at line 516 of file View3DPy.cpp.
References Gui::Camera::Dimetric, SCL.SimpleDataTypes::e, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Gui::Camera::rotation(), and Gui::View3DInventorViewer::setCameraOrientation().
Referenced by init_type().
viewFront()
Py::Object View3DInventorPy::viewFront ()
Definition at line 408 of file View3DPy.cpp.
References SCL.SimpleDataTypes::e, Gui::Camera::Front, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Gui::Camera::rotation(), and Gui::View3DInventorViewer::setCameraOrientation().
Referenced by init_type().
viewIsometric()
Py::Object View3DInventorPy::viewIsometric ()
Definition at line 498 of file View3DPy.cpp.
References SCL.SimpleDataTypes::e, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Gui::Camera::Isometric, Gui::Camera::rotation(), and Gui::View3DInventorViewer::setCameraOrientation().
Referenced by init_type().
viewLeft()
Py::Object View3DInventorPy::viewLeft ()
Definition at line 426 of file View3DPy.cpp.
References SCL.SimpleDataTypes::e, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Gui::Camera::Left, Gui::Camera::rotation(), and Gui::View3DInventorViewer::setCameraOrientation().
Referenced by init_type().
viewPosition()
Py::Object View3DInventorPy::viewPosition (const Py::Tuple & args)
Definition at line 786 of file View3DPy.cpp.
References toolbit-attributes::args, Base::Placement::getPosition(), Base::Placement::getRotation(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), Base::Rotation::getValue(), getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Gui::View3DInventorViewer::moveCameraTo(), buildPsets::p, and RobotExample::pos.
Referenced by init_type().
viewRear()
Py::Object View3DInventorPy::viewRear ()
Definition at line 444 of file View3DPy.cpp.
References SCL.SimpleDataTypes::e, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Gui::Camera::Rear, Gui::Camera::rotation(), and Gui::View3DInventorViewer::setCameraOrientation().
Referenced by init_type().
viewRight()
Py::Object View3DInventorPy::viewRight ()
Definition at line 462 of file View3DPy.cpp.
References SCL.SimpleDataTypes::e, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Gui::Camera::Right, Gui::Camera::rotation(), and Gui::View3DInventorViewer::setCameraOrientation().
Referenced by init_type().
viewRotateLeft()
Py::Object View3DInventorPy::viewRotateLeft ()
Definition at line 654 of file View3DPy.cpp.
References SCL.SimpleDataTypes::e, SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), getView3DInventorPtr(), Gui::View3DInventor::getViewer(), and M_PI.
Referenced by init_type().
viewRotateRight()
Py::Object View3DInventorPy::viewRotateRight ()
Definition at line 677 of file View3DPy.cpp.
References SCL.SimpleDataTypes::e, SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), getView3DInventorPtr(), Gui::View3DInventor::getViewer(), and M_PI.
Referenced by init_type().
viewTop()
Py::Object View3DInventorPy::viewTop ()
Definition at line 480 of file View3DPy.cpp.
References SCL.SimpleDataTypes::e, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Gui::Camera::rotation(), Gui::View3DInventorViewer::setCameraOrientation(), and Gui::Camera::Top.
Referenced by init_type().
viewTrimetric()
Py::Object View3DInventorPy::viewTrimetric ()
Definition at line 534 of file View3DPy.cpp.
References SCL.SimpleDataTypes::e, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Gui::Camera::rotation(), Gui::View3DInventorViewer::setCameraOrientation(), and Gui::Camera::Trimetric.
Referenced by init_type().
zoomIn()
Py::Object View3DInventorPy::zoomIn ()
Definition at line 700 of file View3DPy.cpp.
References SCL.SimpleDataTypes::e, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Gui::View3DInventorViewer::navigationStyle(), and Gui::NavigationStyle::zoomIn().
Referenced by init_type().
zoomOut()
Py::Object View3DInventorPy::zoomOut ()
Definition at line 718 of file View3DPy.cpp.
References SCL.SimpleDataTypes::e, getView3DInventorPtr(), Gui::View3DInventor::getViewer(), Gui::View3DInventorViewer::navigationStyle(), and Gui::NavigationStyle::zoomOut().
Referenced by init_type().
The documentation for this class was generated from the following files:
View3DPy.h
View3DPy.cpp