FreeCAD: Path.Post.scripts.heidenhain_post Namespace Reference
Path.Post.scripts.heidenhain_post Namespace Reference
Functions
def processArguments (argstring)
def export (objectslist, filename, argstring)
def HEIDEN_Begin (ActualJob)
def HEIDEN_End (ActualJob)
def HEIDEN_ToolCall (tool_Params)
def HEIDEN_Line (line_Params, line_comp, line_feed, line_rapid, line_M_funct, Cmd_Number)
def HEIDEN_Arc (arc_Params, arc_direction, arc_comp, arc_feed, arc_rapid, arc_M_funct, Cmd_Number)
def HEIDEN_PolarArc (pol_cc_X, pol_cc_Y, pol_X, pol_Y, pol_Z, pol_Axis, pol_Incr)
def HEIDEN_Drill (drill_Obj, drill_Params, drill_Type, drill_feed)
def HEIDEN_Format (formatType, formatValue)
def HEIDEN_Numberize (GCodeStrings)
def HEIDEN_LBL_Get (GetPoint=None, GetLevel=None, GetAddit=0)
def HEIDEN_LBL_Replace ()
Variables
MACHINE_SKIP_PARAMS
MACHINE_USE_FMAX
FEED_MAX_SPEED
AXIS_DECIMALS
FEED_DECIMALS
SPINDLE_DECIMALS
FIRST_LBL
MACHINE_CYCLE_DEF
SOLVE_COMPENSATION_ACTIVE
SHOW_EDITOR
SKIP_WARNS
UNITS
LINENUMBERS
STARTLINENR
LINENUMBER_INCREMENT
POSTGCODE
G_FUNCTION_STORE
MACHINE_WORK_AXIS
MACHINE_SPINDLE_DIRECTION
MACHINE_LAST_POSITION
MACHINE_LAST_CENTER
MACHINE_TRASL_ROT
MACHINE_STORED_PARAMS
STORED_COMPENSATED_OBJ
STORED_CANNED_PARAMS
STORED_LBL
COMPENSATION_DIFF_STATUS
LBLIZE_ACTIVE
LBLIZE_STAUS
LBLIZE_PATH_LEVEL
TOOLTIP
parser
prog
add_help
string action = "store_true",
string help = "suppress R F M parameters where already stored",
default = "0",
TOOLTIP_ARGS
Function Documentation
export()
def Path.Post.scripts.heidenhain_post.export (objectslist, filename, argstring)
Definition at line 290 of file heidenhain_post.py.
References Path.Post.scripts.heidenhain_post.HEIDEN_Arc(), Path.Post.scripts.heidenhain_post.HEIDEN_Begin(), Path.Post.scripts.heidenhain_post.HEIDEN_Drill(), Path.Post.scripts.heidenhain_post.HEIDEN_End(), Path.Post.scripts.heidenhain_post.HEIDEN_LBL_Replace(), Path.Post.scripts.heidenhain_post.HEIDEN_Line(), Path.Post.scripts.heidenhain_post.HEIDEN_Numberize(), Path.Post.scripts.heidenhain_post.HEIDEN_ToolCall(), Path.Post.scripts.heidenhain_post.processArguments(), and Path.Post.scripts.refactored_centroid_post.str.
HEIDEN_Arc()
def Path.Post.scripts.heidenhain_post.HEIDEN_Arc (arc_Params, arc_direction, arc_comp, arc_feed, arc_rapid, arc_M_funct, Cmd_Number)
Definition at line 688 of file heidenhain_post.py.
References Path.Post.scripts.heidenhain_post.HEIDEN_Format(), Path.Post.scripts.heidenhain_post.HEIDEN_LBL_Get(), and Path.Post.scripts.heidenhain_post.HEIDEN_PolarArc().
Referenced by Path.Post.scripts.heidenhain_post.export().
HEIDEN_Begin()
def Path.Post.scripts.heidenhain_post.HEIDEN_Begin (ActualJob)
Definition at line 536 of file heidenhain_post.py.
Referenced by Path.Post.scripts.heidenhain_post.export().
HEIDEN_Drill()
def Path.Post.scripts.heidenhain_post.HEIDEN_Drill (drill_Obj, drill_Params, drill_Type, drill_feed)
Definition at line 903 of file heidenhain_post.py.
References Path.Post.scripts.heidenhain_post.HEIDEN_Format(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.heidenhain_post.export().
HEIDEN_End()
def Path.Post.scripts.heidenhain_post.HEIDEN_End (ActualJob)
Definition at line 546 of file heidenhain_post.py.
Referenced by Path.Post.scripts.heidenhain_post.export().
HEIDEN_Format()
def Path.Post.scripts.heidenhain_post.HEIDEN_Format (formatType, formatValue)
Definition at line 1038 of file heidenhain_post.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.heidenhain_post.HEIDEN_Arc(), Path.Post.scripts.heidenhain_post.HEIDEN_Drill(), Path.Post.scripts.heidenhain_post.HEIDEN_Line(), Path.Post.scripts.heidenhain_post.HEIDEN_PolarArc(), and Path.Post.scripts.heidenhain_post.HEIDEN_ToolCall().
HEIDEN_LBL_Get()
def Path.Post.scripts.heidenhain_post.HEIDEN_LBL_Get (GetPoint = None, GetLevel = None, GetAddit = 0)
Definition at line 1070 of file heidenhain_post.py.
References Path.Post.scripts.uccnc_post.append().
Referenced by Path.Post.scripts.heidenhain_post.HEIDEN_Arc(), and Path.Post.scripts.heidenhain_post.HEIDEN_Line().
HEIDEN_LBL_Replace()
def Path.Post.scripts.heidenhain_post.HEIDEN_LBL_Replace ()
Definition at line 1091 of file heidenhain_post.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.heidenhain_post.export().
HEIDEN_Line()
def Path.Post.scripts.heidenhain_post.HEIDEN_Line (line_Params, line_comp, line_feed, line_rapid, line_M_funct, Cmd_Number)
Definition at line 595 of file heidenhain_post.py.
References Path.Post.scripts.heidenhain_post.HEIDEN_Format(), and Path.Post.scripts.heidenhain_post.HEIDEN_LBL_Get().
Referenced by Path.Post.scripts.heidenhain_post.export().
HEIDEN_Numberize()
def Path.Post.scripts.heidenhain_post.HEIDEN_Numberize (GCodeStrings)
Definition at line 1054 of file heidenhain_post.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.heidenhain_post.export().
HEIDEN_PolarArc()
def Path.Post.scripts.heidenhain_post.HEIDEN_PolarArc (pol_cc_X, pol_cc_Y, pol_X, pol_Y, pol_Z, pol_Axis, pol_Incr)
Definition at line 865 of file heidenhain_post.py.
References Path.Post.scripts.heidenhain_post.HEIDEN_Format().
Referenced by Path.Post.scripts.heidenhain_post.HEIDEN_Arc().
HEIDEN_ToolCall()
def Path.Post.scripts.heidenhain_post.HEIDEN_ToolCall (tool_Params)
Definition at line 560 of file heidenhain_post.py.
References Path.Post.scripts.heidenhain_post.HEIDEN_Format(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.heidenhain_post.export().
processArguments()
def Path.Post.scripts.heidenhain_post.processArguments (argstring)
Definition at line 247 of file heidenhain_post.py.
Referenced by Path.Post.scripts.heidenhain_post.export().
Variable Documentation
action
string Path.Post.scripts.heidenhain_post.action = "store_true",
Definition at line 202 of file heidenhain_post.py.
add_help
Path.Post.scripts.heidenhain_post.add_help
Definition at line 199 of file heidenhain_post.py.
AXIS_DECIMALS
Path.Post.scripts.heidenhain_post.AXIS_DECIMALS
Definition at line 53 of file heidenhain_post.py.
COMPENSATION_DIFF_STATUS
Path.Post.scripts.heidenhain_post.COMPENSATION_DIFF_STATUS
Definition at line 180 of file heidenhain_post.py.
default
string Path.Post.scripts.heidenhain_post.default = "0",
Definition at line 211 of file heidenhain_post.py.
FEED_DECIMALS
Path.Post.scripts.heidenhain_post.FEED_DECIMALS
Definition at line 57 of file heidenhain_post.py.
FEED_MAX_SPEED
Path.Post.scripts.heidenhain_post.FEED_MAX_SPEED
Definition at line 49 of file heidenhain_post.py.
FIRST_LBL
Path.Post.scripts.heidenhain_post.FIRST_LBL
Definition at line 65 of file heidenhain_post.py.
G_FUNCTION_STORE
Path.Post.scripts.heidenhain_post.G_FUNCTION_STORE
Definition at line 136 of file heidenhain_post.py.
help
string Path.Post.scripts.heidenhain_post.help = "suppress R F M parameters where already stored",
Definition at line 203 of file heidenhain_post.py.
LBLIZE_ACTIVE
Path.Post.scripts.heidenhain_post.LBLIZE_ACTIVE
Definition at line 181 of file heidenhain_post.py.
LBLIZE_PATH_LEVEL
Path.Post.scripts.heidenhain_post.LBLIZE_PATH_LEVEL
Definition at line 183 of file heidenhain_post.py.
LBLIZE_STAUS
Path.Post.scripts.heidenhain_post.LBLIZE_STAUS
Definition at line 182 of file heidenhain_post.py.
LINENUMBER_INCREMENT
Path.Post.scripts.heidenhain_post.LINENUMBER_INCREMENT
Definition at line 123 of file heidenhain_post.py.
LINENUMBERS
Path.Post.scripts.heidenhain_post.LINENUMBERS
Definition at line 114 of file heidenhain_post.py.
MACHINE_CYCLE_DEF
Path.Post.scripts.heidenhain_post.MACHINE_CYCLE_DEF
Definition at line 71 of file heidenhain_post.py.
MACHINE_LAST_CENTER
Path.Post.scripts.heidenhain_post.MACHINE_LAST_CENTER
Definition at line 158 of file heidenhain_post.py.
MACHINE_LAST_POSITION
Path.Post.scripts.heidenhain_post.MACHINE_LAST_POSITION
Definition at line 150 of file heidenhain_post.py.
MACHINE_SKIP_PARAMS
Path.Post.scripts.heidenhain_post.MACHINE_SKIP_PARAMS
Definition at line 37 of file heidenhain_post.py.
MACHINE_SPINDLE_DIRECTION
Path.Post.scripts.heidenhain_post.MACHINE_SPINDLE_DIRECTION
Definition at line 149 of file heidenhain_post.py.
MACHINE_STORED_PARAMS
Path.Post.scripts.heidenhain_post.MACHINE_STORED_PARAMS
Definition at line 164 of file heidenhain_post.py.
MACHINE_TRASL_ROT
Path.Post.scripts.heidenhain_post.MACHINE_TRASL_ROT
Definition at line 163 of file heidenhain_post.py.
MACHINE_USE_FMAX
Path.Post.scripts.heidenhain_post.MACHINE_USE_FMAX
Definition at line 43 of file heidenhain_post.py.
MACHINE_WORK_AXIS
Path.Post.scripts.heidenhain_post.MACHINE_WORK_AXIS
Definition at line 148 of file heidenhain_post.py.
parser
Path.Post.scripts.heidenhain_post.parser
Definition at line 199 of file heidenhain_post.py.
POSTGCODE
Path.Post.scripts.heidenhain_post.POSTGCODE
Definition at line 135 of file heidenhain_post.py.
prog
Path.Post.scripts.heidenhain_post.prog
Definition at line 199 of file heidenhain_post.py.
SHOW_EDITOR
Path.Post.scripts.heidenhain_post.SHOW_EDITOR
Definition at line 96 of file heidenhain_post.py.
SKIP_WARNS
Path.Post.scripts.heidenhain_post.SKIP_WARNS
Definition at line 101 of file heidenhain_post.py.
SOLVE_COMPENSATION_ACTIVE
Path.Post.scripts.heidenhain_post.SOLVE_COMPENSATION_ACTIVE
Definition at line 90 of file heidenhain_post.py.
SPINDLE_DECIMALS
Path.Post.scripts.heidenhain_post.SPINDLE_DECIMALS
Definition at line 61 of file heidenhain_post.py.
STARTLINENR
Path.Post.scripts.heidenhain_post.STARTLINENR
Definition at line 119 of file heidenhain_post.py.
STORED_CANNED_PARAMS
Path.Post.scripts.heidenhain_post.STORED_CANNED_PARAMS
Definition at line 169 of file heidenhain_post.py.
STORED_COMPENSATED_OBJ
Path.Post.scripts.heidenhain_post.STORED_COMPENSATED_OBJ
Definition at line 168 of file heidenhain_post.py.
STORED_LBL
Path.Post.scripts.heidenhain_post.STORED_LBL
Definition at line 176 of file heidenhain_post.py.
TOOLTIP
Path.Post.scripts.heidenhain_post.TOOLTIP
Definition at line 188 of file heidenhain_post.py.
TOOLTIP_ARGS
Path.Post.scripts.heidenhain_post.TOOLTIP_ARGS
Definition at line 244 of file heidenhain_post.py.
UNITS
Path.Post.scripts.heidenhain_post.UNITS
Definition at line 108 of file heidenhain_post.py.