FreeCAD: Gui::Dialog::DlgSettingsEditor Class Reference
Gui::Dialog::DlgSettingsEditor Class Reference
#include <DlgSettingsEditor.h>
Public Member Functions
DlgSettingsEditor (QWidget *parent=nullptr)
~DlgSettingsEditor () override
void saveSettings () override
void loadSettings () override
void resetSettingsToDefaults () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void changeEvent (QEvent *e) override
void setEditorTabWidth (int)
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
Detailed Description
Definition at line 43 of file DlgSettingsEditor.h.
Constructor & Destructor Documentation
DlgSettingsEditor()
DlgSettingsEditor::DlgSettingsEditor (QWidget * parent = nullptr) explicit
Constructs a DlgSettingsEditor which is a child of 'parent', with the name 'name' and widget flags set to 'f'
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
Definition at line 70 of file DlgSettingsEditor.cpp.
References Gui::Dialog::DlgSettingsEditorP::colormap, and App::ExpressionParser::labels.
~DlgSettingsEditor()
DlgSettingsEditor::~DlgSettingsEditor () override
Destroys the object and frees any allocated resources
Definition at line 162 of file DlgSettingsEditor.cpp.
Member Function Documentation
changeEvent()
void DlgSettingsEditor::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 338 of file DlgSettingsEditor.cpp.
References Gui::Dialog::DlgSettingsEditorP::colormap, and SCL.SimpleDataTypes::e.
loadSettings()
void DlgSettingsEditor::loadSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 245 of file DlgSettingsEditor.cpp.
References Gui::Dialog::DlgSettingsEditorP::colormap, ParameterGrp::GetASCII(), Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), ParameterGrp::GetUnsigned(), Gui::SyntaxHighlighter::setColor(), and setEditorTabWidth().
resetSettingsToDefaults()
void DlgSettingsEditor::resetSettingsToDefaults () override virtual
Reimplemented from Gui::Dialog::PreferencePage.
Definition at line 318 of file DlgSettingsEditor.cpp.
References Gui::Dialog::DlgSettingsEditorP::colormap, Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), ParameterGrp::RemoveASCII(), ParameterGrp::RemoveInt(), ParameterGrp::RemoveUnsigned(), and Gui::Dialog::PreferencePage::resetSettingsToDefaults().
saveSettings()
void DlgSettingsEditor::saveSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 223 of file DlgSettingsEditor.cpp.
References Gui::Dialog::DlgSettingsEditorP::colormap, Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), ParameterGrp::SetASCII(), setEditorTabWidth(), ParameterGrp::SetInt(), and ParameterGrp::SetUnsigned().
setEditorTabWidth()
void DlgSettingsEditor::setEditorTabWidth (int tabWidth) protected
Definition at line 212 of file DlgSettingsEditor.cpp.
References Gui::QtTools::horizontalAdvance().
Referenced by loadSettings(), and saveSettings().
The documentation for this class was generated from the following files:
DlgSettingsEditor.h
DlgSettingsEditor.cpp