FreeCAD: MillSim::Shape Class Reference
MillSim::Shape Class Reference
#include <SimShapes.h>
Public Member Functions
Shape ()
~Shape ()
void Render ()
void Render (mat4x4 modelMat, mat4x4 normallMat)
void FreeResources ()
void SetModelData (std::vector< Vertex > &vbuffer, std::vector< GLushort > &ibuffer)
void RotateProfile (float *profPoints, int nPoints, float distance, float deltaHeight, int nSlices, bool isHalfTurn)
void ExtrudeProfileRadial (float *profPoints, int nPoints, float radius, float angleRad, float deltaHeight, bool capStart, bool capEnd)
void ExtrudeProfileLinear (float *profPoints, int nPoints, float fromX, float toX, float fromZ, float toZ, bool capStart, bool capEnd)
Static Public Member Functions
static void GenerateSinTable (int nSlices)
Public Attributes
uint vao = 0
uint vbo = 0
uint ibo = 0
int numIndices = 0
Static Public Attributes
static std::vector< float > sinTable
static std::vector< float > cosTable
static int lastNumSlices = 0
Protected Member Functions
void GenerateModel (float *vbuffer, GLushort *ibuffer, int numVerts, int numIndices)
void CalculateExtrudeBufferSizes (int nProfilePoints, bool capStart, bool capEnd, int *numVerts, int *numIndices, int *vc1idx, int *vc2idx, int *ic1idx, int *ic2idx)
Detailed Description
Definition at line 69 of file SimShapes.h.
Constructor & Destructor Documentation
Shape()
MillSim::Shape::Shape () inline
Definition at line 72 of file SimShapes.h.
~Shape()
Shape::~Shape ()
Definition at line 368 of file SimShapes.cpp.
References FreeResources().
Member Function Documentation
CalculateExtrudeBufferSizes()
void Shape::CalculateExtrudeBufferSizes (int nProfilePoints, bool capStart, bool capEnd, int * numVerts, int * numIndices, int * vc1idx, int * vc2idx, int * ic1idx, int * ic2idx) protected
Definition at line 124 of file SimShapes.cpp.
References numIndices.
Referenced by ExtrudeProfileLinear(), and ExtrudeProfileRadial().
ExtrudeProfileLinear()
void Shape::ExtrudeProfileLinear (float * profPoints, int nPoints, float fromX, float toX, float fromZ, float toZ, bool capStart, bool capEnd)
Definition at line 244 of file SimShapes.cpp.
References CalculateExtrudeBufferSizes(), SplineSurface::i, numIndices, SET_TRIPLE, and SetModelData().
Referenced by MillSim::StockObject::GenerateBoxStock(), and MillSim::EndMill::GenerateDisplayLists().
ExtrudeProfileRadial()
void Shape::ExtrudeProfileRadial (float * profPoints, int nPoints, float radius, float angleRad, float deltaHeight, bool capStart, bool capEnd)
Definition at line 150 of file SimShapes.cpp.
References CalculateExtrudeBufferSizes(), SplineSurface::i, numIndices, SET_TRIPLE, and SetModelData().
Referenced by MillSim::EndMill::GenerateArcSegmentDL().
FreeResources()
void Shape::FreeResources ()
Definition at line 360 of file SimShapes.cpp.
References glBindVertexArray, GLDELETE_BUFFER, GLDELETE_VERTEXARRAY, ibo, vao, and vbo.
Referenced by MillSim::EndMill::~EndMill(), MillSim::MillPathSegment::~MillPathSegment(), ~Shape(), and MillSim::SolidObject::~SolidObject().
GenerateModel()
void Shape::GenerateModel (float * vbuffer, GLushort * ibuffer, int numVerts, int numIndices) protected
Definition at line 315 of file SimShapes.cpp.
References glBindBuffer, glBindVertexArray, glBufferData, MillSim::GLClearError(), glEnableVertexAttribArray, glGenBuffers, glGenVertexArrays, MillSim::GLLogError(), glVertexAttribPointer, ibo, numIndices, vao, vbo, and MovieTool::x.
GenerateSinTable()
void Shape::GenerateSinTable (int nSlices) static
Definition at line 36 of file SimShapes.cpp.
References cosTable, SplineSurface::i, lastNumSlices, PI, sinTable, and BOPTools.SplitAPI::slice().
Referenced by RotateProfile().
Render() [1/2]
void Shape::Render ()
Definition at line 347 of file SimShapes.cpp.
References glBindBuffer, glBindVertexArray, glDrawElements, ibo, numIndices, and vao.
Referenced by MillSim::MillPathSegment::render(), MillSim::SolidObject::render(), and Render().
Render() [2/2]
void Shape::Render (mat4x4 modelMat, mat4x4 normallMat)
Definition at line 354 of file SimShapes.cpp.
References MillSim::CurrentShader, Render(), and MillSim::Shader::UpdateModelMat().
RotateProfile()
void Shape::RotateProfile (float * profPoints, int nPoints, float distance, float deltaHeight, int nSlices, bool isHalfTurn)
Definition at line 54 of file SimShapes.cpp.
References cosTable, GenerateSinTable(), SplineSurface::i, numIndices, RobotExample::pos, SET_TRIPLE, SetModelData(), and sinTable.
Referenced by MillSim::EndMill::GenerateDisplayLists().
SetModelData()
void MillSim::Shape::SetModelData (std::vector< Vertex > & vbuffer, std::vector< GLushort > & ibuffer)
Definition at line 342 of file SimShapes.cpp.
Referenced by ExtrudeProfileLinear(), ExtrudeProfileRadial(), MillSim::SolidObject::GenerateSolid(), and RotateProfile().
Member Data Documentation
cosTable
std::vector< float > Shape::cosTable static
Definition at line 111 of file SimShapes.h.
Referenced by GenerateSinTable(), and RotateProfile().
ibo
uint MillSim::Shape::ibo = 0
Definition at line 79 of file SimShapes.h.
Referenced by FreeResources(), GenerateModel(), and Render().
lastNumSlices
int Shape::lastNumSlices = 0 static
Definition at line 112 of file SimShapes.h.
Referenced by GenerateSinTable().
numIndices
int MillSim::Shape::numIndices = 0
Definition at line 80 of file SimShapes.h.
Referenced by CalculateExtrudeBufferSizes(), ExtrudeProfileLinear(), ExtrudeProfileRadial(), GenerateModel(), Render(), and RotateProfile().
sinTable
std::vector< float > Shape::sinTable static
Definition at line 110 of file SimShapes.h.
Referenced by GenerateSinTable(), and RotateProfile().
vao
uint MillSim::Shape::vao = 0
Definition at line 77 of file SimShapes.h.
Referenced by FreeResources(), GenerateModel(), and Render().
vbo
uint MillSim::Shape::vbo = 0
Definition at line 78 of file SimShapes.h.
Referenced by FreeResources(), and GenerateModel().
The documentation for this class was generated from the following files:
SimShapes.h
SimShapes.cpp