FreeCAD: Spreadsheet::Sheet Class Reference
Spreadsheet::Sheet Class Reference
#include <Sheet.h>
Public Types
enum Border {
BorderTop = 1, BorderLeft = 2, BorderBottom = 4, BorderRight = 8,
BorderAll = 15
}
Public Types inherited from App::DocumentObject
enum OutListOption { OutListNoExpression = 1, OutListNoHidden = 2, OutListNoXLinked = 4 }
OutList options.
enum GSReason { GS_DEFAULT, GS_SELECT }
reason of calling getSubObjects()
Public Types inherited from App::ExtensionContainer
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Public Member Functions
Sheet ()
Constructor.
~Sheet () override
Sheet::~Sheet.
const char * getViewProviderName () const override
returns the type name of the ViewProvider
bool importFromFile (const std::string &filename, char delimiter='\t', char quoteChar='\0', char escapeChar='\\')
bool getCharsFromPrefs (char &delimiter, char &quote, char &escape, std::string &errMsg)
bool exportToFile (const std::string &filename, char delimiter='\t', char quoteChar='\0', char escapeChar='\\') const
bool mergeCells (const App::Range &range)
void splitCell (App::CellAddress address)
Cell * getCell (App::CellAddress address)
Cell * getNewCell (App::CellAddress address)
unsigned getCellBindingBorder (App::CellAddress address) const
PropertySheet::BindingType getCellBinding (App::Range &range, App::ExpressionPtr *pStart=nullptr, App::ExpressionPtr *pEnd=nullptr, App::ObjectIdentifier *pTarget=nullptr) const
void setCell (const char *address, const char *value)
void setCell (App::CellAddress address, const char *value)
void clearAll ()
void clear (App::CellAddress address, bool all=true)
void getSpans (App::CellAddress address, int &rows, int &cols) const
bool isMergedCell (App::CellAddress address) const
App::CellAddress getAnchor (App::CellAddress address) const
void setColumnWidth (int col, int width)
Set column with of column col to width-.
int getColumnWidth (int col) const
Get column with of column at index col.
void setRowHeight (int row, int height)
Set row height of row given by index in row to height.
int getRowHeight (int row) const
Get height of row at index row.
std::vector< std::string > getUsedCells () const
void insertColumns (int col, int count)
void removeColumns (int col, int count)
void insertRows (int row, int count)
void removeRows (int row, int count)
void setContent (App::CellAddress address, const char *value)
Set content of cell at address to value.
void setAlignment (App::CellAddress address, int alignment)
Set alignment of content in cell at address to alignment.
void setStyle (App::CellAddress address, const std::set< std::string > &style)
Set style of cell at address to style.
void setForeground (App::CellAddress address, const App::Color &color)
Set foreground (text color) of cell at address address to color.
void setBackground (App::CellAddress address, const App::Color &color)
Set background color of cell at address address to color.
void setDisplayUnit (App::CellAddress address, const std::string &unit)
Set display unit of cell at address address to unit.
void setComputedUnit (App::CellAddress address, const Base::Unit &unit)
Set computed unit for cell at address address to unit.
void setAlias (App::CellAddress address, const std::string &alias)
Set alias for cell at address address to alias. If the alias is an empty string, the existing alias is removed.
std::string getAddressFromAlias (const std::string &alias) const
Get cell given an alias string.
bool isValidAlias (const std::string &candidate)
Determine whether a given alias candidate is valid or not.
void setSpans (App::CellAddress address, int rows, int columns)
Set row and column span for the cell at address address to rows and columns.
std::set< std::string > dependsOn (App::CellAddress address) const
Return a set of dependencies links for cell at address.
void providesTo (App::CellAddress address, std::set< std::string > &result) const
Compute links to cells that cell at address provides input to.
bool hasCell (const std::vector< App::Range > &ranges) const
PyObject * getPyObject () override
PropertySheet * getCells ()
App::Property * getPropertyByName (const char *name) const override
App::Property * getDynamicPropertyByName (const char *name) const override
void getPropertyNamedList (std::vector< std::pair< const char *, App::Property * >> &List) const override
short mustExecute () const override
App::DocumentObjectExecReturn * execute () override
bool getCellAddress (const App::Property *prop, App::CellAddress &address)
App::CellAddress getCellAddress (const char *name, bool silent=false) const
App::Range getRange (const char *name, bool silent=false) const
std::tuple< App::CellAddress, App::CellAddress > getUsedRange () const
std::map< int, int > getColumnWidths () const
Get a map with column indices and widths.
std::map< int, int > getRowHeights () const
Get a map with row indices and heights.
std::string getRow (int offset=0) const
std::string getColumn (int offset=0) const
void touchCells (App::Range range)
void recomputeCells (App::Range range)
void observeDocument (App::Document *document)
Create a document observer for this sheet. Used to track changes.
void renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &paths) override
void setCopyOrCutRanges (const std::vector< App::Range > &ranges, bool copy=true)
const std::vector< App::Range > & getCopyOrCutRange (bool copy=true) const
unsigned getCopyOrCutBorder (App::CellAddress address, bool copy=true) const
Public Member Functions inherited from App::DocumentObject
virtual const char * getViewProviderNameOverride () const
DocumentObject ()
Constructor.
~DocumentObject () override
const char * getDagKey () const
returns a value that uniquely identifies this DocumentObject.
const char * getNameInDocument () const
returns the name which is set in the document for this object (not the name property!)
long getID () const
Return the object ID that is unique within its owner document.
std::string getExportName (bool forced=false) const
returns the name that is safe to be exported to other document
std::string getFullName () const override
Return the object full name of the form DocName::ObjName.
std::string getFullLabel () const
Return the object full label in the form DocName::ObjName.
bool isAttachedToDocument () const override
const char * detachFromDocument () override
App::Document * getDocument () const
gets the document in which this Object is handled
void touch (bool noRecompute=false)
set this document object touched (cause recomputation on dependent features)
bool isTouched () const
test if this document object is touched
void enforceRecompute ()
Enforce this document object to be recomputed.
bool mustRecompute () const
Test if this document object must be recomputed.
void purgeTouched ()
reset this document object touched
bool isError () const
set this feature to error
bool isValid () const
void purgeError ()
remove the error from the object
bool isRecomputing () const
returns true if this objects is currently recomputing
bool isRestoring () const
returns true if this objects is currently restoring from file
bool isRemoving () const
returns true if this objects is currently removed from the document
void freeze ()
set this document object freezed (prevent recomputation)
void unfreeze (bool noRecompute=false)
set this document object unfreezed (and touch it)
bool isFreezed () const
returns true if this objects is currently freezed
unsigned long getStatus () const
return the status bits
bool testStatus (ObjectStatus pos) const
void setStatus (ObjectStatus pos, bool on)
int isExporting () const
virtual int setElementVisible (const char *element, bool visible)
virtual int isElementVisible (const char *element) const
virtual bool hasChildElement () const
return true to activate tree view group object handling and element visibility
const std::vector< App::DocumentObject * > & getOutList () const
returns a list of objects this object is pointing to by Links
std::vector< App::DocumentObject * > getOutList (int option) const
void getOutList (int option, std::vector< App::DocumentObject * > &res) const
std::vector< App::DocumentObject * > getOutListOfProperty (App::Property *) const
returns a list of objects linked by the property
std::vector< App::DocumentObject * > getOutListRecursive () const
returns a list of objects this object is pointing to by Links and all further descended
void clearOutListCache () const
clear internal out list cache
std::vector< std::list< App::DocumentObject * > > getPathsByOutList (App::DocumentObject *to) const
get all possible paths from this to another object following the OutList
const std::vector< App::DocumentObject * > & getInList () const
std::vector< App::DocumentObject * > getInListRecursive () const
get all objects link directly or indirectly to this object
void getInListEx (std::set< App::DocumentObject * > &inSet, bool recursive, std::vector< App::DocumentObject * > *inList=nullptr) const
std::set< App::DocumentObject * > getInListEx (bool recursive) const
DocumentObjectGroup * getGroup () const
get group if object is part of a group, otherwise 0 is returned
bool isInInListRecursive (DocumentObject *objToTest) const
test if this object is in the InList and recursive further down
bool isInInList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the InList
bool isInOutListRecursive (DocumentObject *objToTest) const
test if the given object is in the OutList and recursive further down
bool isInOutList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the OutList
void _removeBackLink (DocumentObject *)
internal, used by PropertyLink to maintain DAG back links
void _addBackLink (DocumentObject *)
internal, used by PropertyLink to maintain DAG back links
bool testIfLinkDAGCompatible (DocumentObject *linkTo) const
testIfLinkIsDAG tests a link that is about to be created for circular references.
bool testIfLinkDAGCompatible (const std::vector< DocumentObject * > &linksTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSubList &linksTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSub &linkTo) const
virtual std::string getElementMapVersion (const App::Property *prop, bool restored=false) const
virtual bool checkElementMapVersion (const App::Property *prop, const char *ver) const
Return true to signal re-generation of geometry element names.
bool recomputeFeature (bool recursive=false)
const char * getStatusString () const
get the status Message
virtual void onLostLinkToObject (DocumentObject *)
virtual DocumentObject * getSubObject (const char *subname, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
std::vector< DocumentObject * > getSubObjectList (const char *subname, std::vector< int > *subsizes=nullptr, bool flatten=false) const
virtual std::vector< std::string > getSubObjects (int reason=0) const
std::vector< std::pair< App::DocumentObject *, std::string > > getParents (int depth=0) const
Obtain top parents and subnames of this object using its InList.
App::DocumentObject * getFirstParent () const
Obtain the first parent group of this object.
virtual DocumentObject * getLinkedObject (bool recurse=true, Base::Matrix4D *mat=nullptr, bool transform=false, int depth=0) const
virtual bool canLinkProperties () const
virtual bool isLink () const
virtual bool isLinkGroup () const
virtual bool allowDuplicateLabel () const
virtual void onBeforeChangeLabel (std::string &newLabel)
void Save (Base::Writer &writer) const override
virtual void setExpression (const ObjectIdentifier &path, std::shared_ptr< App::Expression > expr)
void clearExpression (const ObjectIdentifier &path)
virtual const PropertyExpressionEngine::ExpressionInfo getExpression (const ObjectIdentifier &path) const
const std::string & getOldLabel () const
const char * getViewProviderNameStored () const
bool removeDynamicProperty (const char *prop) override
App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
App::DocumentObject * resolve (const char *subname, App::DocumentObject **parent=nullptr, std::string *childName=nullptr, const char **subElement=nullptr, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
App::DocumentObject * resolveRelativeLink (std::string &subname, App::DocumentObject *&link, std::string &linkSub) const
virtual bool adjustRelativeLinks (const std::set< App::DocumentObject * > &inList, std::set< App::DocumentObject * > *visited=nullptr)
virtual int canLoadPartial () const
virtual void onUpdateElementReference (const Property *)
virtual bool redirectSubName (std::ostringstream &ss, DocumentObject *topParent, DocumentObject *child) const
Public Member Functions inherited from App::TransactionalObject
TransactionalObject ()
Constructor.
~TransactionalObject () override
Public Member Functions inherited from App::ExtensionContainer
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop) override
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual std::vector< std::string > getDynamicPropertyNames () const
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Attributes
boost::signals2::signal< void(App::CellAddress)> cellUpdated
boost::signals2::signal< void(App::Range)> rangeUpdated
boost::signals2::signal< void(App::CellAddress)> cellSpanChanged
boost::signals2::signal< void(int, int)> columnWidthChanged
boost::signals2::signal< void(int, int)> rowHeightChanged
Public Attributes inherited from App::DocumentObject
PropertyString Label
PropertyString Label2
PropertyExpressionEngine ExpressionEngine
PropertyBool Visibility
Allow control visibility status in App name space.
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalBeforeChange
signal before changing a property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalChanged
signal on changed property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalEarlyChanged
signal on changed property of this object before document scoped signalChangedObject
Protected Types
using ObserverMap = std::map< std::string, SheetObserver * >
Protected Member Functions
void onChanged (const App::Property *prop) override
get called by the container when a property was changed
void updateColumnsOrRows (bool horizontal, int section, int count)
std::set< App::CellAddress > providesTo (App::CellAddress address) const
Compute links to cells that cell at address provides input to.
void onDocumentRestored () override
get called after a document has been fully restored
void recomputeCell (App::CellAddress p)
Recompute cell at address p.
App::Property * getProperty (App::CellAddress key) const
App::Property * getProperty (const char *addr) const
Get a dynamic property.
void updateProperty (App::CellAddress key)
App::Property * setStringProperty (App::CellAddress key, const std::string &value)
App::Property * setObjectProperty (App::CellAddress key, Py::Object obj)
App::Property * setFloatProperty (App::CellAddress key, double value)
App::Property * setIntegerProperty (App::CellAddress key, long value)
App::Property * setQuantityProperty (App::CellAddress key, double value, const Base::Unit &unit)
void onSettingDocument () override
void updateBindings ()
Protected Member Functions inherited from App::DocumentObject
virtual App::DocumentObjectExecReturn * recompute ()
recompute only this object
App::DocumentObjectExecReturn * executeExtensions ()
void setError ()
void resetError ()
void setDocument (App::Document *doc)
void onBeforeChange (const Property *prop) override
get called before the value is changed
void onEarlyChange (const Property *prop) override
get called by the container when a property was changed
virtual void onUndoRedoFinished ()
get called after an undo/redo transaction is finished
virtual void setupObject ()
get called after a brand new object was created
virtual void unsetupObject ()
get called when object is going to be removed from the document
void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus) override
get called when a property status has changed
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData () const
Protected Attributes
App::DynamicProperty & props
std::map< const App::Property *, App::CellAddress > propAddress
std::set< App::CellAddress > cellErrors
PropertySheet cells
PropertyColumnWidths columnWidths
PropertyRowHeights rowHeights
ObserverMap observers
int currentRow = -1
int currentCol = -1
std::vector< App::Range > boundRanges
std::vector< App::Range > copyCutRanges
bool hasCopyRange = false
Protected Attributes inherited from App::DocumentObject
std::bitset< 32 > StatusBits
Py::SmartPtr PythonObject
python object of this class and all descendent
App::Document * _pDoc {nullptr}
pointer to the document this object belongs to
std::string oldLabel
Old label; used for renaming expressions.
const std::string * pcNameInDocument {nullptr}
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Friends
class SheetObserver
class PropertySheet
Additional Inherited Members
Static Public Member Functions inherited from App::DocumentObject
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
Check if the subname reference ends with hidden marker.
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Attributes inherited from App::DocumentObject
static DocumentObjectExecReturn * StdReturn
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 89 of file Sheet.h.
Member Typedef Documentation
ObserverMap
using Spreadsheet::Sheet::ObserverMap = std::map<std::string, SheetObserver*> protected
Definition at line 309 of file Sheet.h.
Member Enumeration Documentation
Border
enum Spreadsheet::Sheet::Border
Enumerator
BorderTop
BorderLeft
BorderBottom
BorderRight
BorderAll
Definition at line 124 of file Sheet.h.
Constructor & Destructor Documentation
Sheet()
Sheet::Sheet ()
Constructor.
Construct a new Sheet object.
Definition at line 72 of file Sheet.cpp.
References ADD_PROPERTY_TYPE, App::Prop_Hidden, App::Prop_Output, and App::Prop_ReadOnly.
~Sheet()
Sheet::~Sheet () override
Sheet::~Sheet.
The destructor; clear properties to release all memory.
Definition at line 105 of file Sheet.cpp.
References clearAll().
Member Function Documentation
clear()
void Sheet::clear (App::CellAddress address, bool all = true)
Clear the cell at address. If all is false, only the text or expression contents are cleared. If all is true everything in the cell is cleared, including color, style, etc.
Parameters
address Address of cell to clear
all Whether we should clear all or not.
Definition at line 1212 of file Sheet.cpp.
References cells, Spreadsheet::PropertySheet::clear(), getCell(), App::DynamicProperty::getDynamicPropertyByName(), propAddress, props, App::DocumentObject::removeDynamicProperty(), and App::CellAddress::toString().
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__(), Spreadsheet::PropertySheet::pasteCells(), SpreadsheetGui::SheetTableView::pasteClipboard(), setCell(), and updateProperty().
clearAll()
void Sheet::clearAll ()
Clear all cells in the sheet. These are implemented as dynamic properties, for example "A1" is added as a dynamic property. Since now users may add dynamic properties, we need to try to avoid removing those, too, so we check whether the dynamic property name is a valid cell address name before removing it.
Definition at line 118 of file Sheet.cpp.
References cellErrors, cells, Spreadsheet::PropertyColumnWidths::clear(), Spreadsheet::PropertyRowHeights::clear(), Spreadsheet::PropertySheet::clear(), columnWidths, App::DynamicProperty::getDynamicPropertyNames(), Spreadsheet::PropertySheet::isValidCellAddressName(), observers, propAddress, props, App::DocumentObject::removeDynamicProperty(), and rowHeights.
Referenced by Assembly::BomObject::generateBOM(), importFromFile(), and ~Sheet().
dependsOn()
std::set< std::string > Sheet::dependsOn (App::CellAddress address) const
Return a set of dependencies links for cell at address.
Parameters
address Address of cell
Returns
Set of dependencies.
Definition at line 1597 of file Sheet.cpp.
References cells, and Spreadsheet::PropertySheet::getDeps().
Referenced by SpreadsheetGui::SheetModel::data().
execute()
DocumentObjectExecReturn * Sheet::execute () override virtual
Update the document properties.
Reimplemented from App::DocumentObject.
Definition at line 1027 of file Sheet.cpp.
References cellErrors, cells, cellUpdated, Spreadsheet::PropertyRowHeights::clearDirty(), Spreadsheet::PropertyColumnWidths::clearDirty(), columnWidthChanged, columnWidths, Base::Console(), src.Mod.AddonManager.NetworkManager::count, Base::ConsoleSingleton::Error(), FC_LOG, FC_TRACE, Spreadsheet::PropertyColumnWidths::getDirty(), Spreadsheet::PropertyRowHeights::getDirty(), Spreadsheet::PropertySheet::getDirty(), App::DocumentObject::getFullName(), Spreadsheet::PropertyRowHeights::getValue(), Spreadsheet::PropertyColumnWidths::getValue(), Spreadsheet::PropertySheet::getValue(), Path.Op.Surface::msg, App::DocumentObject::pcNameInDocument, RobotExample::pos, providesTo(), recomputeCell(), Spreadsheet::PropertySheet::recomputeDependencies(), rowHeightChanged, rowHeights, Spreadsheet::Cell::setException(), updateBindings(), and TestSpreadsheet::v.
Referenced by Assembly::BomObject::execute(), FeaturePython.DistanceBolt::onChanged(), and onDocumentRestored().
exportToFile()
bool Sheet::exportToFile (const std::string & filename, char delimiter = '\t', char quoteChar = '\0', char escapeChar = '\\') const
Export spreadsheet data to file.
Parameters
filename Filename to store data to.
delimiter Field delimiter
quoteChar Quote character ('\0' to disable)
escapeChar Escape character ('\0' to disable)
Returns
True if store is successful, false if something failed.
Definition at line 297 of file Sheet.cpp.
References cells, DrawingExample::file, Spreadsheet::PropertySheet::getNonEmptyCells(), getProperty(), SplineSurface::i, Base::BaseClass::isDerivedFrom(), Path.Post.scripts.refactored_centroid_post::str, and writeEscaped().
getAddressFromAlias()
std::string Sheet::getAddressFromAlias (const std::string & alias) const
Get cell given an alias string.
Parameters
alias Alias for cell
Returns
Name of cell, or empty string if not defined
Definition at line 1540 of file Sheet.cpp.
References cells, Spreadsheet::Cell::getAddress(), Spreadsheet::PropertySheet::getValueFromAlias(), and App::CellAddress::toString().
Referenced by isValidAlias(), and setAlias().
getAnchor()
App::CellAddress Spreadsheet::Sheet::getAnchor (App::CellAddress address) const
Definition at line 1258 of file Sheet.cpp.
References cells, and Spreadsheet::PropertySheet::getAnchor().
Referenced by SpreadsheetGui::SheetTableView::finishEditWithMove().
getCell()
Cell * Sheet::getCell (App::CellAddress address)
Get contents of the cell specified by address, or 0 if it is not defined
Returns
A CellContent object or 0.
Definition at line 401 of file Sheet.cpp.
References cells, and Spreadsheet::PropertySheet::getValue().
Referenced by SpreadsheetGui::DlgSheetConf::accept(), clear(), SpreadsheetGui::SheetModel::data(), Drawing::FeatureViewSpreadsheet::execute(), SpreadsheetGui::SheetTableView::finishEditWithMove(), getNewCell(), TechDraw::DrawViewSpreadsheet::getSheetImage(), Spreadsheet::PropertySheet::pasteCells(), SpreadsheetGui::DlgSheetConf::prepare(), removeColumns(), removeRows(), SpreadsheetGui::SheetModel::setData(), and updateProperty().
getCellAddress() [1/2]
bool Sheet::getCellAddress (const App::Property * prop, App::CellAddress & address)
Get the address as address of the Property prop. This function throws an exception if the property is not found.
Definition at line 504 of file Sheet.cpp.
References SplineSurface::i, and propAddress.
Referenced by getDynamicPropertyByName(), getPropertyByName(), and SpreadsheetGui::DlgSheetConf::prepare().
getCellAddress() [2/2]
App::CellAddress Sheet::getCellAddress (const char * name, bool silent = false) const
Definition at line 515 of file Sheet.cpp.
References cells, Spreadsheet::PropertySheet::getCellAddress(), and Base::silent.
getCellBinding()
PropertySheet::BindingType Sheet::getCellBinding (App::Range & range, App::ExpressionPtr * pStart = nullptr, App::ExpressionPtr * pEnd = nullptr, App::ObjectIdentifier * pTarget = nullptr) const
Definition at line 933 of file Sheet.cpp.
References Spreadsheet::PropertySheet::BindingNone, boundRanges, cells, App::CellAddress::col(), Spreadsheet::PropertySheet::getBinding(), App::Range::next(), App::Range::normalize(), and App::CellAddress::row().
Referenced by SpreadsheetGui::DlgSheetConf::accept(), SpreadsheetGui::SpreadsheetDelegate::createEditor(), SpreadsheetGui::DlgBindSheet::DlgBindSheet(), and SpreadsheetGui::DlgSheetConf::onDiscard().
getCellBindingBorder()
unsigned Sheet::getCellBindingBorder (App::CellAddress address) const
Definition at line 990 of file Sheet.cpp.
References _getBorder(), and boundRanges.
Referenced by SpreadsheetGui::SpreadsheetDelegate::paint().
getCells()
PropertySheet* Spreadsheet::Sheet::getCells () inline
Definition at line 200 of file Sheet.h.
Referenced by SpreadsheetGui::SheetTableView::_copySelection(), SpreadsheetGui::SheetModel::data(), SpreadsheetGui::SheetTableView::finishEditWithMove(), SpreadsheetGui::SheetTableView::pasteClipboard(), SpreadsheetGui::SheetTableView::selectedRanges(), and SpreadsheetGui::SheetTableView::toHtml().
getCharsFromPrefs()
bool Sheet::getCharsFromPrefs (char & delimiter, char & quote, char & escape, std::string & errMsg)
Definition at line 142 of file Sheet.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), toolbit-attributes::group, App::DocumentObject::isValid(), and Spreadsheet::quote().
getColumn()
std::string Sheet::getColumn (int offset = 0) const
Definition at line 1695 of file Sheet.cpp.
References currentCol, and create_qrc::txt.
getColumnWidth()
int Sheet::getColumnWidth (int col) const
Get column with of column at index col.
Parameters
col
Returns
Definition at line 1280 of file Sheet.cpp.
References columnWidths, and Spreadsheet::PropertyColumnWidths::getValue().
Referenced by Drawing::FeatureViewSpreadsheet::execute(), TechDraw::DrawViewSpreadsheet::getSheetImage(), SpreadsheetGui::SheetModel::headerData(), and SpreadsheetGui::SheetTableView::toHtml().
getColumnWidths()
std::map< int, int > Sheet::getColumnWidths () const
Get a map with column indices and widths.
Returns
Map with results.
Definition at line 535 of file Sheet.cpp.
References columnWidths, and Spreadsheet::PropertyColumnWidths::getValues().
Referenced by SpreadsheetGui::SheetTableView::setSheet().
getCopyOrCutBorder()
unsigned Sheet::getCopyOrCutBorder (App::CellAddress address, bool copy = true) const
Definition at line 1754 of file Sheet.cpp.
References _getBorder(), copyCutRanges, and hasCopyRange.
Referenced by SpreadsheetGui::SpreadsheetDelegate::paint().
getCopyOrCutRange()
const std::vector< Range > & Sheet::getCopyOrCutRange (bool copy = true) const
Definition at line 1745 of file Sheet.cpp.
References copyCutRanges, and hasCopyRange.
Referenced by SpreadsheetGui::SheetTableView::pasteClipboard().
getDynamicPropertyByName()
Property * Sheet::getDynamicPropertyByName (const char * name) const override virtual
Reimplemented from App::PropertyContainer.
Definition at line 848 of file Sheet.cpp.
References getCellAddress(), getProperty(), and App::CellAddress::isValid().
getNewCell()
Cell * Sheet::getNewCell (App::CellAddress address)
Get cell contents specified by address.
Parameters
address
Definition at line 412 of file Sheet.cpp.
References cells, Spreadsheet::PropertySheet::createCell(), and getCell().
Referenced by Spreadsheet::PropertySheet::pasteCells(), and SpreadsheetGui::PropertiesDialog::PropertiesDialog().
getProperty() [1/2]
Property * Sheet::getProperty (App::CellAddress key) const protected
Get the Cell Property for the cell at key.
Returns
The Property object.
Definition at line 482 of file Sheet.cpp.
References App::DynamicProperty::getDynamicPropertyByName(), props, and App::CellAddress::toString().
Referenced by exportToFile(), getDynamicPropertyByName(), getPropertyByName(), and getPropertyNamedList().
getProperty() [2/2]
Property * Sheet::getProperty (const char * addr) const protected
Get a dynamic property.
Parameters
addr Name of dynamic propeerty.
Returns
Pointer to property, or 0 if it does not exist.
Definition at line 493 of file Sheet.cpp.
References App::DynamicProperty::getDynamicPropertyByName(), and props.
getPropertyByName()
Property * Sheet::getPropertyByName (const char * name) const override virtual
Retrieve a specific Property given by name. This function might throw an exception if something fails, but might also return 0 in case the property is not found.
Returns
The property, or 0 if not found.
Reimplemented from App::ExtensionContainer.
Definition at line 833 of file Sheet.cpp.
References getCellAddress(), getProperty(), and App::CellAddress::isValid().
Referenced by SpreadsheetGui::SheetModel::data(), Drawing::FeatureViewSpreadsheet::execute(), Spreadsheet::Cell::getFormattedQuantity(), TechDraw::DrawViewSpreadsheet::getSheetImage(), and isValidAlias().
getPropertyNamedList()
void Sheet::getPropertyNamedList (std::vector< std::pair< const char *, App::Property * >> & List) const override
Definition at line 863 of file Sheet.cpp.
References cells, getProperty(), and TestSpreadsheet::v.
getPyObject()
PyObject * Sheet::getPyObject () override virtual
Get the Python object for the Sheet.
Returns
The Python object.
Reimplemented from App::DocumentObject.
Definition at line 466 of file Sheet.cpp.
References Py::SmartPtr::is(), Py::new_reference_to(), and App::DocumentObject::PythonObject.
getRange()
App::Range Sheet::getRange (const char * name, bool silent = false) const
Definition at line 520 of file Sheet.cpp.
References cells, Spreadsheet::PropertySheet::getRange(), and Base::silent.
Referenced by SpreadsheetGui::DlgSheetConf::accept().
getRow()
std::string Sheet::getRow (int offset = 0) const
Definition at line 1683 of file Sheet.cpp.
References currentRow.
getRowHeight()
int Sheet::getRowHeight (int row) const
Get height of row at index row.
Parameters
row Index of row.
Returns
Height
Definition at line 1302 of file Sheet.cpp.
References Spreadsheet::PropertyRowHeights::getValue(), and rowHeights.
Referenced by Drawing::FeatureViewSpreadsheet::execute(), TechDraw::DrawViewSpreadsheet::getSheetImage(), and SpreadsheetGui::SheetModel::headerData().
getRowHeights()
std::map< int, int > Sheet::getRowHeights () const
Get a map with row indices and heights.
Returns
Map with results
Definition at line 545 of file Sheet.cpp.
References Spreadsheet::PropertyRowHeights::getValues(), and rowHeights.
Referenced by SpreadsheetGui::SheetTableView::setSheet().
getSpans()
void Sheet::getSpans (App::CellAddress address, int & rows, int & cols) const
Get row an column span for the cell at (row, col).
Parameters
address Address of cell
rows The number of unit cells this cell spans
cols The number of unit rows this cell spans
Definition at line 1239 of file Sheet.cpp.
References cells, and Spreadsheet::PropertySheet::getSpans().
Referenced by _getBorder(), SpreadsheetGui::SheetTableView::finishEditWithMove(), SpreadsheetGui::SheetTableView::setSheet(), SpreadsheetGui::SheetTableView::toHtml(), and SpreadsheetGui::SheetTableView::updateCellSpan().
getUsedCells()
std::vector< std::string > Sheet::getUsedCells () const
Get a vector of strings with addresses of all used cells.
Returns
vector of strings.
Definition at line 1314 of file Sheet.cpp.
References cells, and Spreadsheet::PropertySheet::getUsedCells().
Referenced by SpreadsheetGui::SheetTableView::setSheet().
getUsedRange()
std::tuple< App::CellAddress, App::CellAddress > Sheet::getUsedRange () const
Definition at line 525 of file Sheet.cpp.
References cells, and Spreadsheet::PropertySheet::getUsedRange().
Referenced by Assembly::BomObject::saveCustomColumnData().
getViewProviderName()
const char* Spreadsheet::Sheet::getViewProviderName () const inline override virtual
returns the type name of the ViewProvider
Reimplemented from App::DocumentObject.
Definition at line 99 of file Sheet.h.
hasCell()
bool Sheet::hasCell (const std::vector< App::Range > & ranges) const
Definition at line 1671 of file Sheet.cpp.
References cells, and Spreadsheet::PropertySheet::getValue().
importFromFile()
bool Sheet::importFromFile (const std::string & filename, char delimiter = '\t', char quoteChar = '\0', char escapeChar = '\\')
Import a file into the spreadsheet object.
Parameters
filename Name of file to import
delimiter The field delimiter character used.
quoteChar Quote character, if any (set to '\0' to disable).
escapeChar The escape character used, if any (set to '0' to disable).
Returns
True if successful, false if something failed.
Definition at line 203 of file Sheet.cpp.
References Spreadsheet::PropertySheet::AtomicPropertyChange, cells, clearAll(), SCL.SimpleDataTypes::e, DrawingExample::file, importOCA::getline(), SplineSurface::i, and setCell().
insertColumns()
void Sheet::insertColumns (int col, int count)
Insert count columns at before column col in the spreadsheet.
Parameters
col Address of column where the columns are inserted.
count Number of columns to insert
Definition at line 1360 of file Sheet.cpp.
References cells, src.Mod.AddonManager.NetworkManager::count, Spreadsheet::PropertySheet::insertColumns(), and updateColumnsOrRows().
insertRows()
void Sheet::insertRows (int row, int count)
Insert count rows at row row.
Parameters
row Address of row where the rows are inserted.
count Number of rows to insert.
Definition at line 1397 of file Sheet.cpp.
References cells, src.Mod.AddonManager.NetworkManager::count, Spreadsheet::PropertySheet::insertRows(), and updateColumnsOrRows().
isMergedCell()
bool Sheet::isMergedCell (App::CellAddress address) const
Determine whether this cell is merged with another or not.
Parameters
address
Returns
True if cell is merged, false if not.
Definition at line 1253 of file Sheet.cpp.
References cells, and Spreadsheet::PropertySheet::isMergedCell().
Referenced by SpreadsheetGui::SheetTableView::contextMenuEvent(), SpreadsheetGui::SheetTableView::finishEditWithMove(), SpreadsheetGui::SheetTableView::setSheet(), and SpreadsheetGui::SheetTableView::toHtml().
isValidAlias()
bool Sheet::isValidAlias (const std::string & candidate)
Determine whether a given alias candidate is valid or not.
A candidate is valid is the string is syntactically correct, and the alias does not conflict with an existing property.
Definition at line 1558 of file Sheet.cpp.
References cells, getAddressFromAlias(), getPropertyByName(), and Spreadsheet::PropertySheet::isValidAlias().
Referenced by setAlias().
mergeCells()
bool Sheet::mergeCells (const App::Range & range)
Merge a rectangle specified by range into one logical cell. Data in all but the upper right cell are cleared when the cells are merged.
Parameters
range Range to merge.
Returns
True if the cells were merged, false if the merge was unsuccessful.
Definition at line 377 of file Sheet.cpp.
References cells, App::Range::from(), Spreadsheet::PropertySheet::mergeCells(), and App::Range::to().
mustExecute()
short Sheet::mustExecute () const override virtual
Determine whether this object needs to be executed to update internal structures.
Reimplemented from App::DocumentObject.
Definition at line 1193 of file Sheet.cpp.
References cellErrors, cells, and Spreadsheet::PropertySheet::isDirty().
observeDocument()
void Sheet::observeDocument (App::Document * document)
Create a document observer for this sheet. Used to track changes.
Parameters
document document to observer.
Definition at line 1643 of file Sheet.cpp.
References cells, App::Document::getName(), observers, and SheetObserver.
onChanged()
void Sheet::onChanged (const App::Property * prop) override protected virtual
get called by the container when a property was changed
Reimplemented from App::DocumentObject.
Definition at line 1719 of file Sheet.cpp.
References cells, copyCutRanges, App::DocumentObject::onChanged(), and rangeUpdated.
onDocumentRestored()
void Sheet::onDocumentRestored () override protected virtual
get called after a document has been fully restored
Reimplemented from App::DocumentObject.
Definition at line 1629 of file Sheet.cpp.
References execute(), FC_ERR, and App::DocumentObject::getFullName().
onSettingDocument()
void Sheet::onSettingDocument () override protected virtual
Update internal structure when document is set for this property.
Reimplemented from App::DocumentObject.
Definition at line 555 of file Sheet.cpp.
References cells, and Spreadsheet::PropertySheet::documentSet().
providesTo() [1/2]
std::set< CellAddress > Sheet::providesTo (App::CellAddress address) const protected
Compute links to cells that cell at address provides input to.
Parameters
address Address of cell
result Set of links.
Definition at line 1624 of file Sheet.cpp.
References cells, Spreadsheet::PropertySheet::getDeps(), App::DocumentObject::getFullName(), and App::CellAddress::toString().
providesTo() [2/2]
void Sheet::providesTo (App::CellAddress address, std::set< std::string > & result) const
Compute links to cells that cell at address provides input to.
Parameters
address Address of cell
result Set of links.
Definition at line 1608 of file Sheet.cpp.
References cells, Spreadsheet::PropertySheet::getDeps(), App::DocumentObject::getFullName(), SplineSurface::i, result, and App::CellAddress::toString().
Referenced by SpreadsheetGui::SheetModel::data(), and execute().
recomputeCell()
void Sheet::recomputeCell (App::CellAddress p) protected
Recompute cell at address p.
Parameters
p Address of cell.
Definition at line 894 of file Sheet.cpp.
References cellErrors, cells, cellUpdated, Spreadsheet::PropertySheet::clearDirty(), SCL.SimpleDataTypes::e, Base::AbortException::getClassTypeId(), Spreadsheet::Cell::getStringContent(), Spreadsheet::PropertySheet::getValue(), Spreadsheet::Cell::hasException(), Path.Op.Surface::msg, buildPsets::p, Spreadsheet::Cell::setContent(), Spreadsheet::Cell::setException(), setStringProperty(), and updateProperty().
Referenced by execute(), and recomputeCells().
recomputeCells()
void Sheet::recomputeCells (App::Range range)
Definition at line 882 of file Sheet.cpp.
References App::Range::next(), and recomputeCell().
removeColumns()
void Sheet::removeColumns (int col, int count)
Remove count columns at column col.
Parameters
col Address of first column to remove.
count Number of columns to remove.
Definition at line 1374 of file Sheet.cpp.
References cells, src.Mod.AddonManager.NetworkManager::count, getCell(), Spreadsheet::PropertySheet::getColumns(), Spreadsheet::PropertySheet::removeColumns(), App::DocumentObject::removeDynamicProperty(), and updateColumnsOrRows().
removeRows()
void Sheet::removeRows (int row, int count)
Remove count rows starting at row from the spreadsheet.
Parameters
row Address of first row to remove.
count Number of rows to remove.
Definition at line 1411 of file Sheet.cpp.
References cells, src.Mod.AddonManager.NetworkManager::count, getCell(), Spreadsheet::PropertySheet::getRows(), App::DocumentObject::removeDynamicProperty(), Spreadsheet::PropertySheet::removeRows(), and updateColumnsOrRows().
renameObjectIdentifiers()
void Sheet::renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > & paths) override virtual
Reimplemented from App::DocumentObject.
Definition at line 1665 of file Sheet.cpp.
References cells, and Spreadsheet::PropertySheet::renameObjectIdentifiers().
setAlias()
void Sheet::setAlias (App::CellAddress address, const std::string & alias)
Set alias for cell at address address to alias. If the alias is an empty string, the existing alias is removed.
Parameters
address Address of cell
alias New alias.
Definition at line 1510 of file Sheet.cpp.
References cells, getAddressFromAlias(), isValidAlias(), Spreadsheet::PropertySheet::setAlias(), and App::CellAddress::toString().
setAlignment()
void Sheet::setAlignment (App::CellAddress address, int alignment)
Set alignment of content in cell at address to alignment.
Parameters
address Address of cell
alignment New alignment
Definition at line 1443 of file Sheet.cpp.
References cells, and Spreadsheet::PropertySheet::setAlignment().
setBackground()
void Sheet::setBackground (App::CellAddress address, const App::Color & color)
Set background color of cell at address address to color.
Parameters
address Address of cell
color New color
Definition at line 1476 of file Sheet.cpp.
References cells, and Spreadsheet::PropertySheet::setBackground().
setCell() [1/2]
void Sheet::setCell (App::CellAddress address, const char * value)
Set cell at address to value. If a merged cell is specified, the upper right corner of the merged cell must be specified.
Parameters
address Row position of cell.
value String value of expression.
Definition at line 447 of file Sheet.cpp.
References clear(), and setContent().
setCell() [2/2]
void Sheet::setCell (const char * address, const char * contents)
Set cell given by address to contents.
Parameters
address Address of cell to set.
contents New contents of given cell.
Definition at line 431 of file Sheet.cpp.
Referenced by Assembly::BomObject::addObjectChildrenToBom(), Assembly::BomObject::addObjectToBom(), Assembly::BomObject::generateBOM(), and importFromFile().
setColumnWidth()
void Sheet::setColumnWidth (int col, int width)
Set column with of column col to width-.
Parameters
col Index of column.
width New width of column.
Definition at line 1269 of file Sheet.cpp.
References columnWidths, and Spreadsheet::PropertyColumnWidths::setValue().
setComputedUnit()
void Sheet::setComputedUnit (App::CellAddress address, const Base::Unit & unit)
Set computed unit for cell at address address to unit.
Parameters
address Address of cell
unit New unit.
Definition at line 1498 of file Sheet.cpp.
References cells, Spreadsheet::PropertySheet::setComputedUnit(), and unit().
setContent()
void Sheet::setContent (App::CellAddress address, const char * value)
Set content of cell at address to value.
Parameters
address Address of cell
value New value
Definition at line 1432 of file Sheet.cpp.
References cells, and Spreadsheet::PropertySheet::setContent().
Referenced by setCell().
setCopyOrCutRanges()
void Sheet::setCopyOrCutRanges (const std::vector< App::Range > & ranges, bool copy = true)
Definition at line 1734 of file Sheet.cpp.
References copyCutRanges, hasCopyRange, and rangeUpdated.
Referenced by SpreadsheetGui::SheetTableView::_copySelection(), and SpreadsheetGui::SheetTableView::event().
setDisplayUnit()
void Sheet::setDisplayUnit (App::CellAddress address, const std::string & unit)
Set display unit of cell at address address to unit.
Parameters
address Address of cell
unit New unit
Definition at line 1487 of file Sheet.cpp.
References cells, Spreadsheet::PropertySheet::setDisplayUnit(), and unit().
setFloatProperty()
Property * Sheet::setFloatProperty (App::CellAddress key, double value) protected
Set the property for cell key to a PropertyFloat with the value value. If the Property exists, but of wrong type, the previous Property is destroyed and recreated as the correct type.
Parameters
key The address of the cell we want to create a Property for
value The value we want to assign to the Property.
Definition at line 570 of file Sheet.cpp.
References App::DocumentObject::addDynamicProperty(), App::DynamicProperty::getDynamicPropertyByName(), Base::Persistence::getTypeId(), App::Prop_Hidden, App::Prop_NoPersist, App::Prop_ReadOnly, propAddress, props, App::DocumentObject::removeDynamicProperty(), App::PropertyFloat::setValue(), and App::CellAddress::toString().
Referenced by updateProperty().
setForeground()
void Sheet::setForeground (App::CellAddress address, const App::Color & color)
Set foreground (text color) of cell at address address to color.
Parameters
address Address of cell
color New color
Definition at line 1465 of file Sheet.cpp.
References cells, and Spreadsheet::PropertySheet::setForeground().
setIntegerProperty()
Property * Sheet::setIntegerProperty (App::CellAddress key, long value) protected
Definition at line 598 of file Sheet.cpp.
References App::DocumentObject::addDynamicProperty(), App::DynamicProperty::getDynamicPropertyByName(), Base::Persistence::getTypeId(), App::Prop_Hidden, App::Prop_NoPersist, App::Prop_ReadOnly, propAddress, props, App::DocumentObject::removeDynamicProperty(), App::PropertyInteger::setValue(), and App::CellAddress::toString().
Referenced by updateProperty().
setObjectProperty()
Property * Sheet::setObjectProperty (App::CellAddress key, Py::Object obj) protected
Definition at line 704 of file Sheet.cpp.
References App::DocumentObject::addDynamicProperty(), App::DynamicProperty::getDynamicPropertyByName(), App::Prop_Hidden, App::Prop_NoPersist, App::Prop_ReadOnly, propAddress, props, App::DocumentObject::removeDynamicProperty(), App::PropertyPythonObject::setValue(), and App::CellAddress::toString().
Referenced by updateProperty().
setQuantityProperty()
Property * Sheet::setQuantityProperty (App::CellAddress key, double value, const Base::Unit & unit) protected
Set the property for cell key to a PropertyQuantity with value and unit. If the Property exists, but of wrong type, the previous Property is destroyed and recreated as the correct type.
Parameters
key The address of the cell we want to create a Property for
value The value we want to assign to the Property.
unit The associated unit for value.
Definition at line 638 of file Sheet.cpp.
References App::DocumentObject::addDynamicProperty(), cells, Base::Persistence::getClassTypeId(), App::DynamicProperty::getDynamicPropertyByName(), Base::Persistence::getTypeId(), buildPsets::p, App::Prop_Hidden, App::Prop_NoPersist, App::Prop_ReadOnly, propAddress, props, App::DocumentObject::removeDynamicProperty(), Spreadsheet::PropertySheet::setComputedUnit(), App::PropertyQuantity::setUnit(), App::PropertyQuantity::setValue(), App::CellAddress::toString(), and unit().
Referenced by updateProperty().
setRowHeight()
void Sheet::setRowHeight (int row, int height)
Set row height of row given by index in row to height.
Parameters
row Row index.
height New height of row.
Definition at line 1291 of file Sheet.cpp.
References rowHeights, and Spreadsheet::PropertyRowHeights::setValue().
setSpans()
void Sheet::setSpans (App::CellAddress address, int rows, int columns)
Set row and column span for the cell at address address to rows and columns.
Parameters
address Address to upper right corner of cell
rows Rows to span
columns Columns to span
Definition at line 1586 of file Sheet.cpp.
References cells, and Spreadsheet::PropertySheet::setSpans().
setStringProperty()
Property * Sheet::setStringProperty (App::CellAddress key, const std::string & value) protected
Set the property for cell key to a PropertyString with value. If the Property exists, but of wrong type, the previous Property is destroyed and recreated as the correct type.
Parameters
key The address of the cell we want to create a Property for
value The value we want to assign to the Property.
Definition at line 679 of file Sheet.cpp.
References App::DocumentObject::addDynamicProperty(), App::DynamicProperty::getDynamicPropertyByName(), App::Prop_Hidden, App::Prop_NoPersist, App::Prop_ReadOnly, propAddress, props, App::DocumentObject::removeDynamicProperty(), App::PropertyString::setValue(), and App::CellAddress::toString().
Referenced by recomputeCell(), and updateProperty().
setStyle()
void Sheet::setStyle (App::CellAddress address, const std::set< std::string > & style)
Set style of cell at address to style.
Parameters
address Address of cell
style New style
Definition at line 1454 of file Sheet.cpp.
References cells, and Spreadsheet::PropertySheet::setStyle().
splitCell()
void Sheet::splitCell (App::CellAddress address)
Split a previously merged cell specified by address into its individual cells. The address can point to any of the cells that make up the merged cell.
Parameters
address Address of cell to split
Definition at line 390 of file Sheet.cpp.
References cells, and Spreadsheet::PropertySheet::splitCell().
touchCells()
void Sheet::touchCells (App::Range range)
Definition at line 875 of file Sheet.cpp.
References cells, App::Range::next(), and Spreadsheet::PropertySheet::setDirty().
updateBindings()
void Sheet::updateBindings () protected
Definition at line 995 of file Sheet.cpp.
References boundRanges, cells, App::DocumentObject::ExpressionEngine, App::PropertyExpressionEngine::getExpressions(), Spreadsheet::PropertySheet::isBindingPath(), rangeUpdated, and TestSpreadsheet::v.
Referenced by execute().
updateColumnsOrRows()
void Sheet::updateColumnsOrRows (bool horizontal, int section, int count) protected
Definition at line 1324 of file Sheet.cpp.
References columnWidths, src.Mod.AddonManager.NetworkManager::count, Spreadsheet::PropertyColumnWidths::getValues(), Spreadsheet::PropertyRowHeights::getValues(), rowHeights, Spreadsheet::PropertyColumnWidths::setValues(), and Spreadsheet::PropertyRowHeights::setValues().
Referenced by insertColumns(), insertRows(), removeColumns(), and removeRows().
updateProperty()
void Sheet::updateProperty (App::CellAddress key) protected
Update the Property given by key. This will also eventually trigger recomputations of cells depending on key.
Parameters
key The address of the cell we want to recompute.
Definition at line 756 of file Sheet.cpp.
References cellUpdated, clear(), currentCol, currentRow, App::Expression::eval(), getCell(), Spreadsheet::Cell::getExpression(), Spreadsheet::Cell::getStringContent(), RobotExample::l, App::DocumentObject::removeDynamicProperty(), toolbit-attributes::s, setFloatProperty(), setIntegerProperty(), setObjectProperty(), setQuantityProperty(), setStringProperty(), and App::CellAddress::toString().
Referenced by recomputeCell().
Friends And Related Function Documentation
PropertySheet
friend class PropertySheet friend
Definition at line 322 of file Sheet.h.
SheetObserver
friend class SheetObserver friend
Definition at line 320 of file Sheet.h.
Referenced by observeDocument().
Member Data Documentation
boundRanges
std::vector<App::Range> Spreadsheet::Sheet::boundRanges protected
Definition at line 315 of file Sheet.h.
Referenced by getCellBinding(), getCellBindingBorder(), and updateBindings().
cellErrors
std::set<App::CellAddress> Spreadsheet::Sheet::cellErrors protected
Definition at line 295 of file Sheet.h.
Referenced by clearAll(), execute(), mustExecute(), and recomputeCell().
cells
PropertySheet Spreadsheet::Sheet::cells protected
Definition at line 300 of file Sheet.h.
Referenced by clear(), clearAll(), dependsOn(), execute(), exportToFile(), getAddressFromAlias(), getAnchor(), getCell(), getCellAddress(), getCellBinding(), getNewCell(), getPropertyNamedList(), getRange(), getSpans(), getUsedCells(), getUsedRange(), hasCell(), importFromFile(), insertColumns(), insertRows(), isMergedCell(), isValidAlias(), mergeCells(), mustExecute(), observeDocument(), onChanged(), onSettingDocument(), providesTo(), recomputeCell(), removeColumns(), removeRows(), renameObjectIdentifiers(), setAlias(), setAlignment(), setBackground(), setComputedUnit(), setContent(), setDisplayUnit(), setForeground(), setQuantityProperty(), setSpans(), setStyle(), splitCell(), touchCells(), and updateBindings().
cellSpanChanged
boost::signals2::signal<void(App::CellAddress)> Spreadsheet::Sheet::cellSpanChanged
Definition at line 242 of file Sheet.h.
Referenced by Spreadsheet::PropertySheet::Paste(), SpreadsheetGui::SheetTableView::setSheet(), and Spreadsheet::PropertySheet::setSpans().
cellUpdated
boost::signals2::signal<void(App::CellAddress)> Spreadsheet::Sheet::cellUpdated
Definition at line 238 of file Sheet.h.
Referenced by execute(), recomputeCell(), SpreadsheetGui::SheetModel::SheetModel(), and updateProperty().
columnWidthChanged
boost::signals2::signal<void(int, int)> Spreadsheet::Sheet::columnWidthChanged
Definition at line 244 of file Sheet.h.
Referenced by execute().
columnWidths
PropertyColumnWidths Spreadsheet::Sheet::columnWidths protected
Definition at line 303 of file Sheet.h.
Referenced by clearAll(), execute(), getColumnWidth(), getColumnWidths(), setColumnWidth(), and updateColumnsOrRows().
copyCutRanges
std::vector<App::Range> Spreadsheet::Sheet::copyCutRanges protected
Definition at line 317 of file Sheet.h.
Referenced by getCopyOrCutBorder(), getCopyOrCutRange(), onChanged(), and setCopyOrCutRanges().
currentCol
int Spreadsheet::Sheet::currentCol = -1 protected
Definition at line 313 of file Sheet.h.
Referenced by getColumn(), and updateProperty().
currentRow
int Spreadsheet::Sheet::currentRow = -1 protected
Definition at line 312 of file Sheet.h.
Referenced by getRow(), and updateProperty().
hasCopyRange
bool Spreadsheet::Sheet::hasCopyRange = false protected
Definition at line 318 of file Sheet.h.
Referenced by getCopyOrCutBorder(), getCopyOrCutRange(), and setCopyOrCutRanges().
observers
ObserverMap Spreadsheet::Sheet::observers protected
Definition at line 310 of file Sheet.h.
Referenced by clearAll(), and observeDocument().
propAddress
std::map<const App::Property*, App::CellAddress> Spreadsheet::Sheet::propAddress protected
Definition at line 292 of file Sheet.h.
Referenced by clear(), clearAll(), getCellAddress(), setFloatProperty(), setIntegerProperty(), setObjectProperty(), setQuantityProperty(), and setStringProperty().
props
App::DynamicProperty& Spreadsheet::Sheet::props protected
Definition at line 289 of file Sheet.h.
Referenced by clear(), clearAll(), getProperty(), setFloatProperty(), setIntegerProperty(), setObjectProperty(), setQuantityProperty(), and setStringProperty().
rangeUpdated
boost::signals2::signal<void(App::Range)> Spreadsheet::Sheet::rangeUpdated
Definition at line 240 of file Sheet.h.
Referenced by onChanged(), Spreadsheet::PropertySheet::pasteCells(), setCopyOrCutRanges(), SpreadsheetGui::SheetModel::SheetModel(), and updateBindings().
rowHeightChanged
boost::signals2::signal<void(int, int)> Spreadsheet::Sheet::rowHeightChanged
Definition at line 246 of file Sheet.h.
Referenced by execute().
rowHeights
PropertyRowHeights Spreadsheet::Sheet::rowHeights protected
Definition at line 306 of file Sheet.h.
Referenced by clearAll(), execute(), getRowHeight(), getRowHeights(), setRowHeight(), and updateColumnsOrRows().
The documentation for this class was generated from the following files:
Sheet.h
Sheet.cpp