FreeCAD: Part::GeomElementarySurface Class Reference
Part::GeomElementarySurface Class Reference
#include <Geometry.h>
Public Member Functions
~GeomElementarySurface () override
Base::Vector3d getLocation () const
Base::Vector3d getDir () const
Base::Vector3d getXDir () const
Base::Vector3d getYDir () const
bool isSame (const Geometry &other, double tol, double atol) const override
Public Member Functions inherited from Part::GeomSurface
GeomSurface ()
~GeomSurface () override
bool isPlanar (gp_Pln *pln=nullptr, double tol=1e-7) const
TopoDS_Shape toShape () const override
GeomPlane * toPlane (bool clone=true, double tol=1e-7) const
virtual std::optional< Base::Rotation > getRotation () const
bool tangentU (double u, double v, gp_Dir &dirU) const
bool tangentV (double u, double v, gp_Dir &dirV) const
bool normal (double u, double v, gp_Dir &dir) const
virtual gp_Vec getDN (double u, double v, int Nu, int Nv) const
bool isUmbillic (double u, double v) const
double curvature (double u, double v, Curvature) const
void curvatureDirections (double u, double v, gp_Dir &maxD, gp_Dir &minD) const
Public Member Functions inherited from Part::Geometry
~Geometry () override
virtual const Handle (Geom_Geometry) &handle() const =0
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
virtual Geometry * copy () const =0
Geometry * clone () const
boost::uuids::uuid getTag () const
returns the tag of the geometry object
bool hasSameExtensions (const Geometry &other) const
std::vector< std::weak_ptr< const GeometryExtension > > getExtensions () const
bool hasExtension (const Base::Type &type) const
bool hasExtension (const std::string &name) const
std::weak_ptr< const GeometryExtension > getExtension (const Base::Type &type) const
std::weak_ptr< const GeometryExtension > getExtension (const std::string &name) const
std::weak_ptr< GeometryExtension > getExtension (const Base::Type &type)
std::weak_ptr< GeometryExtension > getExtension (const std::string &name)
void setExtension (std::unique_ptr< GeometryExtension > &&geo)
void deleteExtension (const Base::Type &type)
void deleteExtension (const std::string &name)
void mirror (const Base::Vector3d &point) const
void mirror (const Base::Vector3d &point, const Base::Vector3d &dir) const
void rotate (const Base::Placement &plm) const
void scale (const Base::Vector3d &vec, double scale) const
void transform (const Base::Matrix4D &mat) const
void translate (const Base::Vector3d &vec) const
Geometry (const Geometry &)=delete
Geometry & operator= (const Geometry &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
GeomElementarySurface ()
Protected Member Functions inherited from Part::Geometry
void createNewTag ()
create a new tag for the geometry object
void assignTag (const Part::Geometry *)
copies the tag from the geometry passed as a parameter to this object
void copyNonTag (const Part::Geometry *)
Geometry ()
Additional Inherited Members
Public Types inherited from Part::GeomSurface
enum Curvature { Maximum, Minimum, Mean, Gaussian }
Static Public Member Functions inherited from Part::GeomSurface
static bool isPlanar (const Handle(Geom_Surface) &s, gp_Pln *pln=nullptr, double tol=1e-7)
Static Public Member Functions inherited from Part::Geometry
static std::unique_ptr< Geometry > fromShape (const TopoDS_Shape &s, bool silent=false)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Part::Geometry
boost::uuids::uuid tag
std::vector< std::shared_ptr< GeometryExtension > > extensions
Detailed Description
Definition at line 977 of file Part/App/Geometry.h.
Constructor & Destructor Documentation
GeomElementarySurface()
GeomElementarySurface::GeomElementarySurface () protected
Definition at line 5197 of file Part/App/Geometry.cpp.
~GeomElementarySurface()
GeomElementarySurface::~GeomElementarySurface () override
Definition at line 5201 of file Part/App/Geometry.cpp.
Member Function Documentation
getDir()
Base::Vector3d GeomElementarySurface::getDir () const
Definition at line 5227 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle().
Referenced by isSame().
getLocation()
Base::Vector3d GeomElementarySurface::getLocation () const
Definition at line 5205 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle().
Referenced by isSame().
getXDir()
Base::Vector3d GeomElementarySurface::getXDir () const
Definition at line 5234 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle().
Referenced by isSame().
getYDir()
Base::Vector3d GeomElementarySurface::getYDir () const
Definition at line 5241 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle().
Referenced by isSame().
isSame()
bool GeomElementarySurface::isSame (const Geometry & other, double tol, double atol) const override virtual
Implements Part::Geometry.
Reimplemented in Part::GeomPlane, Part::GeomToroid, Part::GeomSphere, Part::GeomCone, and Part::GeomCylinder.
Definition at line 5248 of file Part/App/Geometry.cpp.
References Base::DistanceP2(), Base::Vector3< float_type >::GetAngle(), Base::Persistence::getClassTypeId(), getDir(), getLocation(), getXDir(), getYDir(), and Base::BaseClass::isDerivedFrom().
Referenced by Part::GeomCylinder::isSame(), Part::GeomCone::isSame(), Part::GeomSphere::isSame(), Part::GeomToroid::isSame(), and Part::GeomPlane::isSame().
The documentation for this class was generated from the following files:
Part/App/Geometry.h
Part/App/Geometry.cpp