FreeCAD: Gui::ViewProviderBuilder Class Reference
Gui::ViewProviderBuilder Class Reference abstract
#include <ViewProviderBuilder.h>
Public Member Functions
ViewProviderBuilder ()
Constructor.
virtual ~ViewProviderBuilder ()
virtual void buildNodes (const App::Property *, std::vector< SoNode * > &) const =0
Static Public Member Functions
static void add (const Base::Type &, const Base::Type &)
static ViewProvider * create (const Base::Type &)
static SoFCSelection * createSelection ()
Detailed Description
Definition at line 42 of file ViewProviderBuilder.h.
Constructor & Destructor Documentation
ViewProviderBuilder()
ViewProviderBuilder::ViewProviderBuilder () default
Constructor.
~ViewProviderBuilder()
ViewProviderBuilder::~ViewProviderBuilder () virtual default
Member Function Documentation
add()
void ViewProviderBuilder::add (const Base::Type & prop, const Base::Type & view) static
Definition at line 44 of file ViewProviderBuilder.cpp.
Referenced by PyMOD_INIT_FUNC().
buildNodes()
virtual void Gui::ViewProviderBuilder::buildNodes (const App::Property * , std::vector< SoNode * > &) const pure virtual
Implemented in MeshGui::ViewProviderMeshBuilder, PointsGui::ViewProviderPointsBuilder, Gui::ViewProviderColorBuilder, FemGui::ViewProviderFEMMeshBuilder, and PartGui::ViewProviderShapeBuilder.
create()
ViewProvider * ViewProviderBuilder::create (const Base::Type & type) static
Definition at line 49 of file ViewProviderBuilder.cpp.
References Path.Post.scripts.grbl_post::type.
Referenced by draftguitools.gui_labels.Label::action(), PartGui::ViewProviderCustom::updateData(), and SketcherGui::ViewProviderCustom::updateData().
createSelection()
Gui::SoFCSelection * ViewProviderBuilder::createSelection () static
Definition at line 57 of file ViewProviderBuilder.cpp.
References ParameterGrp::GetBool(), Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), ParameterGrp::GetUnsigned(), highlight(), OpenSCADFeatures::long, Gui::SoFCSelection::OFF, Gui::SoFCSelection::SEL_OFF, and Path.Dressup.Utils::selection().
Referenced by PartDesignGui::ViewProviderDatumPoint::attach(), and PointsGui::ViewProviderPoints::ViewProviderPoints().
The documentation for this class was generated from the following files:
ViewProviderBuilder.h
ViewProviderBuilder.cpp