FreeCAD: PartGui::Workbench Class Reference
PartGui::Workbench Class Reference
#include <Workbench.h>
Public Member Functions
Workbench ()
~Workbench () override
Public Member Functions inherited from Gui::StdWorkbench
StdWorkbench ()
~StdWorkbench () override
void setupContextMenu (const char *recipient, MenuItem *) const override
void createMainWindowPopupMenu (MenuItem *) const override
Public Member Functions inherited from Gui::Workbench
Workbench ()
~Workbench () override
std::string name () const
void setName (const std::string &)
PyObject * getPyObject () override
void createContextMenu (const char *recipient, MenuItem *) const
bool activate ()
void retranslate () const
virtual void activated ()
virtual void deactivated ()
void addTaskWatcher (const std::vector< Gui::TaskView::TaskWatcher * > &Watcher)
helper to add TaskWatcher to the TaskView
void removeTaskWatcher ()
remove the added TaskWatcher
std::list< std::string > listToolbars () const
std::list< std::pair< std::string, std::list< std::string > > > getToolbarItems () const
Shows a list of all toolbars and their commands.
std::list< std::string > listMenus () const
std::list< std::string > listCommandbars () const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
Gui::MenuItem * setupMenuBar () const override
Gui::ToolBarItem * setupToolBars () const override
Gui::ToolBarItem * setupCommandBars () const override
Protected Member Functions inherited from Gui::StdWorkbench
DockWindowItems * setupDockWindows () const override
Protected Member Functions inherited from Gui::Workbench
void addPermanentMenuItems (MenuItem *) const
Additional Inherited Members
Static Public Member Functions inherited from Gui::Workbench
static void createLinkMenu (MenuItem *)
static void addPermanentMenuItem (const std::string &cmd, const std::string &after)
static void removePermanentMenuItem (const std::string &cmd)
Removes the command cmd from the permanent menu items.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Author
Werner Mayer
Definition at line 55 of file Mod/Part/Gui/Workbench.h.
Constructor & Destructor Documentation
Workbench()
Workbench::Workbench ()
If we are to have Sketcher_NewSketch as command in toolbar and menu, then we must assure SketcherGui has already been loaded. By putting this in a try/except block we avoid creating a dependency on sketcher workbench as the import will silently fail if sketcher wb is not built. Note that BUILD_SKETCHER is a cmake-gui option.
Definition at line 50 of file Mod/Part/Gui/Workbench.cpp.
References Base::Interpreter(), result, and Base::InterpreterSingleton::runStringWithKey().
~Workbench()
Workbench::~Workbench () override default
Member Function Documentation
setupCommandBars()
Gui::ToolBarItem * Workbench::setupCommandBars () const override protected virtual
Defines the standard command bars.
Reimplemented from Gui::StdWorkbench.
Definition at line 231 of file Mod/Part/Gui/Workbench.cpp.
setupMenuBar()
Gui::MenuItem * Workbench::setupMenuBar () const override protected virtual
Defines the standard menus.
Reimplemented from Gui::StdWorkbench.
Definition at line 72 of file Mod/Part/Gui/Workbench.cpp.
References Gui::MenuItem::afterItem(), Gui::MenuItem::findItem(), Gui::MenuItem::insertItem(), and Gui::MenuItem::setCommand().
setupToolBars()
Gui::ToolBarItem * Workbench::setupToolBars () const override protected virtual
Defines the standard toolbars.
Reimplemented from Gui::StdWorkbench.
Definition at line 179 of file Mod/Part/Gui/Workbench.cpp.
References Gui::ToolBarItem::setCommand().
The documentation for this class was generated from the following files:
Mod/Part/Gui/Workbench.h
Mod/Part/Gui/Workbench.cpp