FreeCAD: ExpressionCompleterModel Class Reference
ExpressionCompleterModel Class Reference
Classes
struct Info
union InfoPtrEncoding
Public Member Functions
ExpressionCompleterModel (QObject *parent, bool noProperty)
void setNoProperty (bool enabled)
void setDocumentObject (const App::DocumentObject *obj, bool checkInList)
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
void _data (const Info &info, int row, QVariant *v, int *count, bool sep=false) const
QModelIndex parent (const QModelIndex &index) const override
bool modelIndexToParentInfo (QModelIndex element, Info &info) const
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const override
int rowCount (const QModelIndex &parent=QModelIndex()) const override
int columnCount (const QModelIndex &) const override
Static Public Member Functions
static void * infoId (const Info &info)
static Info getInfo (const QModelIndex &index)
static std::vector< App::ObjectIdentifier > retrieveSubPaths (const App::Property *prop)
Static Public Attributes
static const quint64 k_numBitsProp = 16ULL
static const quint64 k_numBitsObj = 24ULL
static const quint64 k_numBitsContextualHierarchy = 1
static const quint64 k_numBitsDocuments = 23ULL
static const quint64 k_offsetProp = 0
static const quint64 k_offsetObj = k_offsetProp + k_numBitsProp
static const quint64 k_offsetContextualHierarchy = k_offsetObj + k_numBitsObj
static const quint64 k_offsetDocuments
static const quint64 k_maskProp = ((1ULL << k_numBitsProp) - 1)
static const quint64 k_maskObj = ((1ULL << k_numBitsObj) - 1)
static const quint64 k_maskContextualHierarchy = ((1ULL << k_numBitsContextualHierarchy) - 1)
static const quint64 k_maskDocuments = ((1ULL << k_numBitsDocuments) - 1)
Detailed Description
Definition at line 52 of file ExpressionCompleter.cpp.
Constructor & Destructor Documentation
ExpressionCompleterModel()
ExpressionCompleterModel::ExpressionCompleterModel (QObject * parent, bool noProperty) inline
Definition at line 55 of file ExpressionCompleter.cpp.
Member Function Documentation
_data()
void ExpressionCompleterModel::_data (const Info & info, int row, QVariant * v, int * count, bool sep = false) const inline
Definition at line 298 of file ExpressionCompleter.cpp.
References src.Mod.AddonManager.NetworkManager::count, toolbit-attributes::doc, App::GetApplication(), App::Application::getDocument(), App::Application::getDocuments(), App::DocumentObject::getNameInDocument(), App::PropertyContainer::getPropertyNamedList(), App::PropertyString::getStrValue(), Path.Log::info(), App::DocumentObject::Label, replaceobj::objs, App::quote(), Path.Post.scripts.refactored_centroid_post::str, and TestSpreadsheet::v.
columnCount()
int ExpressionCompleterModel::columnCount (const QModelIndex &) const inline override
Definition at line 672 of file ExpressionCompleter.cpp.
data()
QVariant ExpressionCompleterModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const inline override
Definition at line 254 of file ExpressionCompleter.cpp.
References FC_TRACE, and Path.Log::info().
getInfo()
static Info ExpressionCompleterModel::getInfo (const QModelIndex & index) inline static
Definition at line 248 of file ExpressionCompleter.cpp.
References ExpressionCompleterModel::InfoPtrEncoding::DecodeInfo().
index()
QModelIndex ExpressionCompleterModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const inline override
Definition at line 632 of file ExpressionCompleter.cpp.
References App::ExpressionParser::column, and Init::parent.
Referenced by src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::addSegment(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::begin(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::interval(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::length(), automotive_design.index_expression::wr1(), and automotive_design.index_expression::wr2().
infoId()
static void* ExpressionCompleterModel::infoId (const Info & info) inline static
Definition at line 242 of file ExpressionCompleter.cpp.
References Path.Log::info(), and ExpressionCompleterModel::InfoPtrEncoding::ptr.
modelIndexToParentInfo()
bool ExpressionCompleterModel::modelIndexToParentInfo (QModelIndex element, Info & info) const inline
Definition at line 564 of file ExpressionCompleter.cpp.
References ExpressionCompleterModel::Info::contextualHierarchy, ExpressionCompleterModel::Info::doc, App::GetApplication(), App::Application::getDocument(), App::Application::getDocuments(), Path.Log::info(), ExpressionCompleterModel::Info::obj, and ExpressionCompleterModel::Info::prop.
parent()
QModelIndex ExpressionCompleterModel::parent (const QModelIndex & index) const inline override
Definition at line 522 of file ExpressionCompleter.cpp.
References ExpressionCompleterModel::Info::contextualHierarchy, ExpressionCompleterModel::Info::doc, ExpressionCompleterModel::Info::obj, and ExpressionCompleterModel::Info::prop.
retrieveSubPaths()
static std::vector<App::ObjectIdentifier> ExpressionCompleterModel::retrieveSubPaths (const App::Property * prop) inline static
Definition at line 267 of file ExpressionCompleter.cpp.
References App::Property::getPaths(), src.Mod.Test.testPathArray::path, and result.
rowCount()
int ExpressionCompleterModel::rowCount (const QModelIndex & parent = QModelIndex()) const inline override
Definition at line 648 of file ExpressionCompleter.cpp.
References src.Mod.AddonManager.NetworkManager::count, FC_TRACE, Path.Log::info(), and Init::parent.
Referenced by src.Mod.AddonManager.package_list.PackageListItemModel::append_item(), src.Mod.AddonManager.AddonManagerOptions.CustomRepoDataModel::appendData(), and src.Mod.AddonManager.package_list.PackageListItemModel::clear().
setDocumentObject()
void ExpressionCompleterModel::setDocumentObject (const App::DocumentObject * obj, bool checkInList) inline
Definition at line 65 of file ExpressionCompleter.cpp.
References App::DocumentObject::getDocument(), App::DocumentObject::getInListEx(), App::Document::getName(), and App::DocumentObject::getNameInDocument().
setNoProperty()
void ExpressionCompleterModel::setNoProperty (bool enabled) inline
Definition at line 60 of file ExpressionCompleter.cpp.
Member Data Documentation
k_maskContextualHierarchy
const quint64 ExpressionCompleterModel::k_maskContextualHierarchy = ((1ULL << k_numBitsContextualHierarchy) - 1) static
Definition at line 184 of file ExpressionCompleter.cpp.
k_maskDocuments
const quint64 ExpressionCompleterModel::k_maskDocuments = ((1ULL << k_numBitsDocuments) - 1) static
Definition at line 185 of file ExpressionCompleter.cpp.
k_maskObj
const quint64 ExpressionCompleterModel::k_maskObj = ((1ULL << k_numBitsObj) - 1) static
Definition at line 183 of file ExpressionCompleter.cpp.
k_maskProp
const quint64 ExpressionCompleterModel::k_maskProp = ((1ULL << k_numBitsProp) - 1) static
Definition at line 182 of file ExpressionCompleter.cpp.
k_numBitsContextualHierarchy
const quint64 ExpressionCompleterModel::k_numBitsContextualHierarchy = 1 static
Definition at line 173 of file ExpressionCompleter.cpp.
k_numBitsDocuments
const quint64 ExpressionCompleterModel::k_numBitsDocuments = 23ULL static
Definition at line 174 of file ExpressionCompleter.cpp.
k_numBitsObj
const quint64 ExpressionCompleterModel::k_numBitsObj = 24ULL static
Definition at line 172 of file ExpressionCompleter.cpp.
k_numBitsProp
const quint64 ExpressionCompleterModel::k_numBitsProp = 16ULL static
Definition at line 171 of file ExpressionCompleter.cpp.
k_offsetContextualHierarchy
const quint64 ExpressionCompleterModel::k_offsetContextualHierarchy = k_offsetObj + k_numBitsObj static
Definition at line 178 of file ExpressionCompleter.cpp.
k_offsetDocuments
const quint64 ExpressionCompleterModel::k_offsetDocuments static
Initial value:
=
        k_offsetContextualHierarchy + k_numBitsContextualHierarchy
Definition at line 179 of file ExpressionCompleter.cpp.
k_offsetObj
const quint64 ExpressionCompleterModel::k_offsetObj = k_offsetProp + k_numBitsProp static
Definition at line 177 of file ExpressionCompleter.cpp.
k_offsetProp
const quint64 ExpressionCompleterModel::k_offsetProp = 0 static
Definition at line 176 of file ExpressionCompleter.cpp.
The documentation for this class was generated from the following file:
ExpressionCompleter.cpp