FreeCAD: src.Mod.PartDesign.InvoluteGearFeature._InvoluteGear Class Reference
src.Mod.PartDesign.InvoluteGearFeature._InvoluteGear Class Reference
Public Member Functions
def __init__ (self, obj)
def onDocumentRestored (self, obj)
def execute (self, obj)
Public Attributes
Type
Detailed Description
Definition at line 75 of file InvoluteGearFeature.py.
Constructor & Destructor Documentation
__init__()
def src.Mod.PartDesign.InvoluteGearFeature._InvoluteGear.__init__ (self, obj)
Definition at line 77 of file InvoluteGearFeature.py.
Member Function Documentation
execute()
def src.Mod.PartDesign.InvoluteGearFeature._InvoluteGear.execute (self, obj)
Definition at line 130 of file InvoluteGearFeature.py.
References src.Mod.PartDesign.fcgear.svggear.generator_func.
Referenced by src.Mod.PartDesign.Scripts.Spring.MySpring.onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped.onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder.onChanged(), and FeaturePython.DistanceBolt.onChanged().
onDocumentRestored()
def src.Mod.PartDesign.InvoluteGearFeature._InvoluteGear.onDocumentRestored (self, obj)
hook used to migrate older versions of this object
Definition at line 82 of file InvoluteGearFeature.py.
References src.Mod.PartDesign.InvoluteGearFeature._InvoluteGear._ensure_properties(), and Path.Post.scripts.dynapath_4060_post.default.
Member Data Documentation
Type
src.Mod.PartDesign.InvoluteGearFeature._InvoluteGear.Type
Definition at line 78 of file InvoluteGearFeature.py.
The documentation for this class was generated from the following file:
InvoluteGearFeature.py