FreeCAD: ArchComponent Namespace Reference
ArchComponent Namespace Reference
Arch
The base class of all Arch objects.
Classes
class ArchSelectionObserver
class Component
class ComponentTaskPanel
class IfcEditorDelegate
class SelectionTaskPanel
class ViewProviderComponent
Functions
def addToComponent (compobject, addobject, mod=None)
def removeFromComponent (compobject, subobject)
Detailed Description
The base class of all Arch objects.
This module provides the base Arch component class, that is shared by all of the Arch BIM objects
Function Documentation
addToComponent()
def ArchComponent.addToComponent (compobject, addobject, mod = None)
Add an object to a component's properties.
Does not run if the addobject already exists in the component's properties.
Adds the object to the first property found of Base, Group, or Hosts.
If mod is provided, adds the object to that property instead.
Parameters
----------
compobject: <ArchComponent.Component>
    The component object to add the object to.
addobject: <App::DocumentObject>
    The object to add to the component.
mod: str, optional
    The property to add the object to.
Definition at line 59 of file ArchComponent.py.
Referenced by ArchSectionPlane.SectionPlaneTaskPanel.addElement(), and ArchComponent.ComponentTaskPanel.addElement().
removeFromComponent()
def ArchComponent.removeFromComponent (compobject, subobject)
Remove the object from the given component.
Try to find the object in the component's properties. If found, remove the
object.
If the object is not found, add the object in the component's Subtractions
property.
Parameters
----------
compobject: <ArchComponent.Component>
    The component to remove the object from.
subobject: <App::DocumentObject>
    The object to remove from the component.
Definition at line 119 of file ArchComponent.py.
References ArchCommands.setAsSubcomponent().
Referenced by ArchSectionPlane.SectionPlaneTaskPanel.removeElement(), and ArchComponent.ComponentTaskPanel.removeElement().