FreeCAD: Gui::ToolBar Class Reference
Gui::ToolBar Class Reference
#include <ToolBarManager.h>
Public Member Functions
ToolBar ()
ToolBar (QWidget *parent)
virtual ~ToolBar ()=default
void undock ()
void updateCustomGripVisibility ()
Protected Member Functions
void setupConnections ()
Friends
class ToolBarGrip
Detailed Description
QToolBar from Qt lacks few abilities like ability to float toolbar from code. This class allows us to provide custom behaviors for toolbars if needed.
Definition at line 120 of file ToolBarManager.h.
Constructor & Destructor Documentation
ToolBar() [1/2]
ToolBar::ToolBar ()
Definition at line 170 of file ToolBarManager.cpp.
References setupConnections().
ToolBar() [2/2]
ToolBar::ToolBar (QWidget * parent) explicit
Definition at line 176 of file ToolBarManager.cpp.
References setupConnections().
~ToolBar()
virtual Gui::ToolBar::~ToolBar () virtual default
Member Function Documentation
setupConnections()
void Gui::ToolBar::setupConnections () protected
Definition at line 223 of file ToolBarManager.cpp.
References draftgeoutils.intersections::connect(), and updateCustomGripVisibility().
Referenced by ToolBar().
undock()
void ToolBar::undock ()
Definition at line 182 of file ToolBarManager.cpp.
References Gui::ToolBarManager::getInstance(), and Gui::getMainWindow().
updateCustomGripVisibility()
void ToolBar::updateCustomGripVisibility ()
Definition at line 203 of file ToolBarManager.cpp.
References Gui::ToolBarManager::getInstance(), Gui::ToolBarManager::toolBarAreaWidget(), and ToolBarGrip.
Referenced by setupConnections().
Friends And Related Function Documentation
ToolBarGrip
friend class ToolBarGrip friend
Definition at line 124 of file ToolBarManager.h.
Referenced by updateCustomGripVisibility().
The documentation for this class was generated from the following files:
ToolBarManager.h
ToolBarManager.cpp