FreeCAD: Gui::StatusBarObserver Class Reference
Gui::StatusBarObserver Class Reference
#include <MainWindow.h>
Public Member Functions
StatusBarObserver ()
~StatusBarObserver () override
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
void SendLog (const std::string &notifiername, const std::string &msg, Base::LogStyle level, Base::IntendedRecipient recipient, Base::ContentType content) override
const char * Name () override
name of the observer
Public Member Functions inherited from Gui::WindowParameter
WindowParameter (const char *name)
~WindowParameter () override
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
ParameterGrp::handle getWindowParameter ()
return the parameter group of this window
Public Member Functions inherited from Base::ILogger
ILogger ()=default
ILogger (const ILogger &)=delete
ILogger (ILogger &&)=delete
ILogger & operator= (const ILogger &)=delete
ILogger & operator= (ILogger &&)=delete
virtual ~ILogger ()=0
bool isActive (Base::LogStyle category) const
Friends
class MainWindow
Additional Inherited Members
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter ()
get the parameters
Public Attributes inherited from Base::ILogger
bool bErr {true}
bool bMsg {true}
bool bLog {true}
bool bWrn {true}
bool bCritical {true}
bool bNotification {false}
Protected Member Functions inherited from Gui::WindowParameter
bool setGroupName (const char *name)
template<typename S , typename T >
void setSlotParamChanged (S slot, T *obsPtr)
connect slot to ParameterManager signal
Detailed Description
The status bar observer displays the text on the status bar of the main window in an appropriate color. Normal text messages are black, warnings are orange and error messages are in red. Log messages are completely ignored. The class is implemented to be thread-safe.
See also
Console
ILogger
Author
Werner Mayer
Definition at line 382 of file MainWindow.h.
Constructor & Destructor Documentation
StatusBarObserver()
StatusBarObserver::StatusBarObserver ()
Definition at line 2330 of file MainWindow.cpp.
References Base::Subject< MsgType >::Attach(), Base::ConsoleSingleton::AttachObserver(), Base::Console(), Gui::WindowParameter::getWindowParameter(), and ParameterGrp::NotifyAll().
~StatusBarObserver()
StatusBarObserver::~StatusBarObserver () override
Definition at line 2341 of file MainWindow.cpp.
References Base::Console(), Base::Subject< MsgType >::Detach(), Base::ConsoleSingleton::DetachObserver(), and Gui::WindowParameter::getWindowParameter().
Member Function Documentation
Name()
const char* Gui::StatusBarObserver::Name () inline override virtual
name of the observer
Reimplemented from Base::ILogger.
Definition at line 395 of file MainWindow.h.
OnChange()
void StatusBarObserver::OnChange (Base::Subject< const char * > & rCaller, const char * sReason) override
Observes its parameter group.
Definition at line 2347 of file MainWindow.cpp.
References ParameterGrp::GetUnsigned().
SendLog()
void StatusBarObserver::SendLog (const std::string & notifiername, const std::string & msg, Base::LogStyle level, Base::IntendedRecipient recipient, Base::ContentType content) override virtual
Used to send a Log message at the given level.
Parameters
notifiername A string identifying the entity generating the notification. It may be the Label of the App::Document or the full label of the App::DocumentObject.
msg The message to be notified.
level A valid level (Log, Message, Error, Notification, CriticalNotification, ...)
recipient A valid intended recipient (All, Developer, User). Observers may decide to process only notifications when a certain recipient is intended.
content A valid content property (Untranslated, Translatable, Untranslatable). Observers may decide not to process notifications if they are not translated or cannot be translated (are untranslatable). Or conversely, may decide not to process already translated notifications. It is up to the intended behaviour of the observer.
Implements Base::ILogger.
Definition at line 2370 of file MainWindow.cpp.
References Gui::MainWindow::Critical, Base::Critical, Base::Developer, Gui::MainWindow::Err, Base::Error, Gui::getMainWindow(), level(), Gui::MainWindow::Log, Base::Log, Base::Message, Gui::MainWindow::Msg, Base::Untranslatable, Base::Untranslated, Base::Warning, and Gui::MainWindow::Wrn.
Friends And Related Function Documentation
MainWindow
friend class MainWindow friend
Definition at line 397 of file MainWindow.h.
The documentation for this class was generated from the following files:
MainWindow.h
MainWindow.cpp