FreeCAD: TechDrawGui::QGCustomImage Class Reference
TechDrawGui::QGCustomImage Class Reference
#include <QGCustomImage.h>
Public Types
enum { Type = QGraphicsItem::UserType + 201 }
Public Member Functions
QGCustomImage ()
~QGCustomImage () override
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
virtual void centerAt (QPointF centerPos)
virtual void centerAt (double cX, double cY)
virtual bool load (QString fileSpec)
virtual bool load (QPixmap map)
virtual QSize imageSize ()
Protected Attributes
QPixmap m_px
Detailed Description
Definition at line 43 of file QGCustomImage.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 49 of file QGCustomImage.h.
Constructor & Destructor Documentation
QGCustomImage()
QGCustomImage::QGCustomImage () explicit
Definition at line 36 of file QGCustomImage.cpp.
~QGCustomImage()
QGCustomImage::~QGCustomImage () override
Definition at line 45 of file QGCustomImage.cpp.
Member Function Documentation
centerAt() [1/2]
void QGCustomImage::centerAt (double cX, double cY) virtual
Definition at line 54 of file QGCustomImage.cpp.
References draftfunctions.scale::scale().
centerAt() [2/2]
void QGCustomImage::centerAt (QPointF centerPos) virtual
Definition at line 49 of file QGCustomImage.cpp.
Referenced by TechDrawGui::QGIFace::buildPixHatch(), TechDrawGui::QGIViewImage::drawImage(), and TechDrawGui::QGIViewImage::QGIViewImage().
imageSize()
QSize QGCustomImage::imageSize () virtual
Definition at line 83 of file QGCustomImage.cpp.
References m_px, and draftfunctions.scale::scale().
Referenced by TechDrawGui::QGIViewImage::draw(), and TechDrawGui::QGIView::QGIView().
load() [1/2]
bool QGCustomImage::load (QPixmap map) virtual
Definition at line 74 of file QGCustomImage.cpp.
References m_px.
load() [2/2]
bool QGCustomImage::load (QString fileSpec) virtual
Definition at line 64 of file QGCustomImage.cpp.
References m_px.
Referenced by TechDrawGui::QGIFace::buildPixHatch(), TechDrawGui::QGIViewImage::drawImage(), and TechDrawGui::QGIView::QGIView().
paint()
void QGCustomImage::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 88 of file QGCustomImage.cpp.
type()
int TechDrawGui::QGCustomImage::type () const inline override
Definition at line 50 of file QGCustomImage.h.
Member Data Documentation
m_px
QPixmap TechDrawGui::QGCustomImage::m_px protected
Definition at line 62 of file QGCustomImage.h.
Referenced by imageSize(), and load().
The documentation for this class was generated from the following files:
QGCustomImage.h
QGCustomImage.cpp