FreeCAD: Path.Op.Gui.Stop._ViewProviderStop Class Reference
Path.Op.Gui.Stop._ViewProviderStop Class Reference
Public Member Functions
def __init__ (self, vobj)
def dumps (self)
def loads (self, state)
def getIcon (self)
def onChanged (self, vobj, prop)
Detailed Description
Definition at line 68 of file Stop.py.
Constructor & Destructor Documentation
__init__()
def Path.Op.Gui.Stop._ViewProviderStop.__init__ (self, vobj)
Definition at line 69 of file Stop.py.
Referenced by draftguitools.gui_subelements.SubelementHighlight.finish().
Member Function Documentation
dumps()
def Path.Op.Gui.Stop._ViewProviderStop.dumps (self)
Definition at line 82 of file Stop.py.
getIcon()
def Path.Op.Gui.Stop._ViewProviderStop.getIcon (self)
Definition at line 88 of file Stop.py.
loads()
def Path.Op.Gui.Stop._ViewProviderStop.loads (self, state)
Definition at line 85 of file Stop.py.
onChanged()
def Path.Op.Gui.Stop._ViewProviderStop.onChanged (self, vobj, prop)
Definition at line 91 of file Stop.py.
Referenced by draftviewproviders.view_base.ViewProviderDraft.attach(), draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy.updateData(), draftviewproviders.view_layer.ViewProviderLayer.updateData(), draftviewproviders.view_label.ViewProviderLabel.updateData(), and draftviewproviders.view_dimension.ViewProviderLinearDimension.updateData().
The documentation for this class was generated from the following file:
Stop.py