FreeCAD: AppMeasureGui.cpp File Reference
AppMeasureGui.cpp File Reference
#include "PreCompiled.h"
#include <QApplication>
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/PyObjectBase.h>
#include <Base/Tools.h>
#include <Gui/Application.h>
#include <Gui/Language/Translator.h>
#include <Gui/WidgetFactory.h>
#include "DlgPrefsMeasureAppearanceImp.h"
#include "QuickMeasure.h"
#include "QuickMeasurePy.h"
#include "ViewProviderMeasureAngle.h"
#include "ViewProviderMeasureDistance.h"
#include "ViewProviderMeasureBase.h"
#include "WorkbenchManipulator.h"
Classes
class MeasureGui::Module
Namespaces
MeasureGui
Functions
void CreateMeasureCommands ()
PyObject * MeasureGui::initModule ()
PyMOD_INIT_FUNC (MeasureGui)
Function Documentation
CreateMeasureCommands()
void CreateMeasureCommands ()
Definition at line 79 of file Mod/Measure/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (MeasureGui)
Definition at line 71 of file AppMeasureGui.cpp.
References Base::InterpreterSingleton::addType(), Base::Console(), CreateMeasureCommands(), SCL.SimpleDataTypes::e, Base::Persistence::init(), App::Extension::init(), MeasureGui::DimensionLinear::initClass(), MeasureGui::initModule(), Gui::WorkbenchManipulator::installManipulator(), Gui::Application::Instance, Base::Interpreter(), Base::InterpreterSingleton::loadModule(), Base::ConsoleSingleton::Log(), mod, PyMOD_Return, and Arch::QT_TRANSLATE_NOOP.