FreeCAD: CDxfWrite Class Reference
CDxfWrite Class Reference
#include <dxf.h>
Public Member Functions
CDxfWrite (const char *filepath)
CDxfWrite (const CDxfWrite &)=delete
CDxfWrite (const CDxfWrite &&)=delete
CDxfWrite & operator= (const CDxfWrite &)=delete
CDxfWrite & operator= (const CDxfWrite &&)=delete
~CDxfWrite ()
void init ()
void endRun ()
assemble pieces into output file
bool Failed () const
std::string getLayerName ()
void setLayerName (std::string name)
void setVersion (int version)
void setPolyOverride (bool setting)
void addBlockName (const std::string &name, const std::string &blkRecordHandle)
void writeLine (const double *start, const double *end)
void writePoint (const double *)
void writeArc (const double *start, const double *end, const double *center, bool dir)
void writeEllipse (const double *center, double major_radius, double minor_radius, double rotation, double start_angle, double end_angle, bool endIsCW)
void writeCircle (const double *center, double radius)
void writeSpline (const SplineDataOut &sd)
void writeLWPolyLine (const LWPolyDataOut &pd)
void writePolyline (const LWPolyDataOut &pd)
void writeVertex (double x, double y, double z)
void writeText (const char *text, const double *location1, const double *location2, double height, int horizJust)
void writeLinearDim (const double *textMidPoint, const double *lineDefPoint, const double *extLine1, const double *extLine2, const char *dimText, int type)
void writeLinearDimBlock (const double *textMidPoint, const double *lineDefPoint, const double *extLine1, const double *extLine2, const char *dimText, int type)
void writeAngularDim (const double *textMidPoint, const double *lineDefPoint, const double *startExt1, const double *endExt1, const double *startExt2, const double *endExt2, const char *dimText)
void writeAngularDimBlock (const double *textMidPoint, const double *lineDefPoint, const double *startExt1, const double *endExt1, const double *startExt2, const double *endExt2, const char *dimText)
void writeRadialDim (const double *centerPoint, const double *textMidPoint, const double *arcPoint, const char *dimText)
void writeRadialDimBlock (const double *centerPoint, const double *textMidPoint, const double *arcPoint, const char *dimText)
void writeDiametricDim (const double *textMidPoint, const double *arcPoint1, const double *arcPoint2, const char *dimText)
void writeDiametricDimBlock (const double *textMidPoint, const double *arcPoint1, const double *arcPoint2, const char *dimText)
void writeDimBlockPreamble ()
void writeBlockTrailer ()
void writeHeaderSection ()
void writeTablesSection ()
void writeBlocksSection ()
void writeEntitiesSection ()
void writeObjectsSection ()
void writeClassesSection ()
void makeLayerTable ()
void makeBlockRecordTableHead ()
void makeBlockRecordTableBody ()
void makeBlockSectionHead ()
Protected Member Functions
void putLine (const Base::Vector3d &start, const Base::Vector3d &end, std::ostringstream *outStream, const std::string &handle, const std::string &ownerHandle)
void putText (const char *text, const Base::Vector3d &location1, const Base::Vector3d &location2, double height, int horizJust, std::ostringstream *outStream, const std::string &handle, const std::string &ownerHandle)
void putArrow (Base::Vector3d &arrowPos, Base::Vector3d &barb1Pos, Base::Vector3d &barb2Pos, std::ostringstream *outStream, const std::string &handle, const std::string &ownerHandle)
std::string getPlateFile (std::string fileSpec)
copy boiler plate file
void setDataDir (const std::string &dirName)
std::string getHandle ()
std::string getEntityHandle ()
std::string getLayerHandle ()
std::string getBlockHandle ()
std::string getBlkRecordHandle ()
Static Protected Member Functions
static Base::Vector3d toVector3d (const double *coordinatesXYZ)
Protected Attributes
std::string m_optionSource
int m_version
int m_handle
int m_entityHandle
int m_layerHandle
int m_blockHandle
int m_blkRecordHandle
bool m_polyOverride
std::string m_saveModelSpaceHandle
std::string m_savePaperSpaceHandle
std::string m_saveBlockRecordTableHandle
std::string m_saveBlkRecordHandle
std::string m_currentBlock
std::string m_dataDir
std::string m_layerName
std::vector< std::string > m_layerList
std::vector< std::string > m_blockList
std::vector< std::string > m_blkRecordList
Detailed Description
Definition at line 254 of file dxf.h.
Constructor & Destructor Documentation
CDxfWrite() [1/3]
CDxfWrite::CDxfWrite (const char * filepath) explicit
Definition at line 35 of file dxf.cpp.
References ifctree::filepath.
CDxfWrite() [2/3]
CDxfWrite::CDxfWrite (const CDxfWrite &) delete
CDxfWrite() [3/3]
CDxfWrite::CDxfWrite (const CDxfWrite &&) delete
~CDxfWrite()
CDxfWrite::~CDxfWrite ()
Definition at line 72 of file dxf.cpp.
Member Function Documentation
addBlockName()
void CDxfWrite::addBlockName (const std::string & name, const std::string & blkRecordHandle)
Definition at line 504 of file dxf.cpp.
References m_blkRecordList, and m_blockList.
Referenced by writeDimBlockPreamble().
endRun()
void CDxfWrite::endRun ()
assemble pieces into output file
Definition at line 89 of file dxf.cpp.
References makeBlockRecordTableBody(), makeLayerTable(), writeBlocksSection(), writeClassesSection(), writeEntitiesSection(), writeObjectsSection(), and writeTablesSection().
Failed()
bool CDxfWrite::Failed () const inline
Definition at line 336 of file dxf.h.
getBlkRecordHandle()
std::string CDxfWrite::getBlkRecordHandle () protected
Definition at line 494 of file dxf.cpp.
References getHandle().
Referenced by makeBlockRecordTableHead(), and writeDimBlockPreamble().
getBlockHandle()
std::string CDxfWrite::getBlockHandle () protected
Definition at line 484 of file dxf.cpp.
References getHandle().
Referenced by makeBlockSectionHead(), writeAngularDimBlock(), writeBlockTrailer(), writeDiametricDimBlock(), writeDimBlockPreamble(), writeLinearDimBlock(), and writeRadialDimBlock().
getEntityHandle()
std::string CDxfWrite::getEntityHandle () protected
Definition at line 464 of file dxf.cpp.
References getHandle().
Referenced by writeAngularDim(), writeArc(), writeCircle(), writeDiametricDim(), writeEllipse(), writeLine(), writeLinearDim(), writeLWPolyLine(), writePoint(), writePolyline(), writeRadialDim(), writeSpline(), writeText(), and writeVertex().
getHandle()
std::string CDxfWrite::getHandle () protected
Definition at line 455 of file dxf.cpp.
References m_handle.
Referenced by getBlkRecordHandle(), getBlockHandle(), getEntityHandle(), and getLayerHandle().
getLayerHandle()
std::string CDxfWrite::getLayerHandle () protected
Definition at line 474 of file dxf.cpp.
References getHandle().
Referenced by makeLayerTable().
getLayerName()
std::string CDxfWrite::getLayerName () inline
Definition at line 342 of file dxf.h.
Referenced by putLine(), putText(), writeAngularDim(), writeArc(), writeBlockTrailer(), writeCircle(), writeDiametricDim(), writeDimBlockPreamble(), writeEllipse(), writeLinearDim(), writeLWPolyLine(), writePoint(), writePolyline(), writeRadialDim(), writeSpline(), and writeVertex().
getPlateFile()
std::string CDxfWrite::getPlateFile (std::string fileSpec) protected
copy boiler plate file
Definition at line 434 of file dxf.cpp.
References Base::Console(), Base::FileInfo::filePath(), importOCA::getline(), Base::FileInfo::isReadable(), and Base::ConsoleSingleton::Message().
Referenced by writeBlocksSection(), writeClassesSection(), writeEntitiesSection(), writeHeaderSection(), writeObjectsSection(), and writeTablesSection().
init()
void CDxfWrite::init ()
Definition at line 81 of file dxf.cpp.
References makeBlockRecordTableHead(), makeBlockSectionHead(), and writeHeaderSection().
Referenced by DocumentObject.DocumentObject::onChanged().
makeBlockRecordTableBody()
void CDxfWrite::makeBlockRecordTableBody ()
Definition at line 298 of file dxf.cpp.
References SCL.SimpleDataTypes::b, m_blkRecordList, m_blockList, m_saveBlockRecordTableHandle, and m_version.
Referenced by endRun().
makeBlockRecordTableHead()
void CDxfWrite::makeBlockRecordTableHead ()
Definition at line 242 of file dxf.cpp.
References getBlkRecordHandle(), m_blockList, m_saveBlockRecordTableHandle, m_saveModelSpaceHandle, m_savePaperSpaceHandle, and m_version.
Referenced by init().
makeBlockSectionHead()
void CDxfWrite::makeBlockSectionHead ()
Definition at line 327 of file dxf.cpp.
References getBlockHandle(), m_currentBlock, m_saveModelSpaceHandle, m_savePaperSpaceHandle, and m_version.
Referenced by init().
makeLayerTable()
void CDxfWrite::makeLayerTable ()
Definition at line 174 of file dxf.cpp.
References getLayerHandle(), RobotExample::l, m_layerList, and m_version.
Referenced by endRun().
operator=() [1/2]
CDxfWrite& CDxfWrite::operator= (const CDxfWrite &&) delete
operator=() [2/2]
CDxfWrite& CDxfWrite::operator= (const CDxfWrite &) delete
putArrow()
void CDxfWrite::putArrow (Base::Vector3d & arrowPos, Base::Vector3d & barb1Pos, Base::Vector3d & barb2Pos, std::ostringstream * outStream, const std::string & handle, const std::string & ownerHandle) protected
Definition at line 1043 of file dxf.cpp.
References m_version, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by writeAngularDimBlock(), writeDiametricDimBlock(), writeLinearDimBlock(), and writeRadialDimBlock().
putLine()
void CDxfWrite::putLine (const Base::Vector3d & start, const Base::Vector3d & end, std::ostringstream * outStream, const std::string & handle, const std::string & ownerHandle) protected
Definition at line 525 of file dxf.cpp.
References getLayerName(), and m_version.
Referenced by writeDiametricDimBlock(), writeLine(), writeLinearDimBlock(), and writeRadialDimBlock().
putText()
void CDxfWrite::putText (const char * text, const Base::Vector3d & location1, const Base::Vector3d & location2, double height, int horizJust, std::ostringstream * outStream, const std::string & handle, const std::string & ownerHandle) protected
Definition at line 971 of file dxf.cpp.
References getLayerName(), m_version, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by writeAngularDimBlock(), writeDiametricDimBlock(), writeLinearDimBlock(), writeRadialDimBlock(), and writeText().
setDataDir()
void CDxfWrite::setDataDir (const std::string & dirName) inline protected
Definition at line 294 of file dxf.h.
Referenced by Import::ImpExpDxfWrite::setOptions().
setLayerName()
void CDxfWrite::setLayerName (std::string name)
Definition at line 510 of file dxf.cpp.
References m_layerList, and m_layerName.
setPolyOverride()
void CDxfWrite::setPolyOverride (bool setting) inline
Definition at line 351 of file dxf.h.
setVersion()
void CDxfWrite::setVersion (int version) inline
Definition at line 347 of file dxf.h.
References Dice3DS::version.
toVector3d()
static Base::Vector3d CDxfWrite::toVector3d (const double * coordinatesXYZ) inline static protected
Definition at line 265 of file dxf.h.
Referenced by writeAngularDimBlock(), writeDiametricDimBlock(), writeLine(), writeLinearDimBlock(), writeRadialDimBlock(), and writeText().
writeAngularDim()
void CDxfWrite::writeAngularDim (const double * textMidPoint, const double * lineDefPoint, const double * startExt1, const double * endExt1, const double * startExt2, const double * endExt2, const char * dimText)
Definition at line 1187 of file dxf.cpp.
References getEntityHandle(), getLayerName(), m_saveModelSpaceHandle, m_version, writeAngularDimBlock(), writeBlockTrailer(), and writeDimBlockPreamble().
Referenced by Import::ImpExpDxfWrite::exportAngularDim().
writeAngularDimBlock()
void CDxfWrite::writeAngularDimBlock (const double * textMidPoint, const double * lineDefPoint, const double * startExt1, const double * endExt1, const double * startExt2, const double * endExt2, const char * dimText)
Definition at line 1567 of file dxf.cpp.
References KDL::atan2(), KDL::cos(), src.Mod.PartDesign.Scripts.Gear::e1, getBlockHandle(), FreeCADInit::Length, M_PI, m_saveBlkRecordHandle, m_version, MakeVector3d(), Base::Vector3< float_type >::Normalize(), putArrow(), putText(), KDL::sin(), Base::toDegrees(), toVector3d(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by writeAngularDim().
writeArc()
void CDxfWrite::writeArc (const double * start, const double * end, const double * center, bool dir)
arc from 3 points - start, end, center. dir true if arc is AntiClockwise. unspecified assumption is that points are on XY plane in coord system OXYZ.
Definition at line 701 of file dxf.cpp.
References KDL::atan2(), exportCSG::center(), getEntityHandle(), getLayerName(), m_saveModelSpaceHandle, m_version, KDL::sqrt(), and Base::toDegrees().
Referenced by Import::ImpExpDxfWrite::exportArc().
writeBlocksSection()
void CDxfWrite::writeBlocksSection ()
Definition at line 1752 of file dxf.cpp.
References getPlateFile(), m_dataDir, and m_version.
Referenced by endRun().
writeBlockTrailer()
void CDxfWrite::writeBlockTrailer ()
Definition at line 1458 of file dxf.cpp.
References getBlockHandle(), getLayerName(), m_saveBlkRecordHandle, and m_version.
Referenced by writeAngularDim(), writeDiametricDim(), writeLinearDim(), and writeRadialDim().
writeCircle()
void CDxfWrite::writeCircle (const double * center, double radius)
Definition at line 754 of file dxf.cpp.
References exportCSG::center(), getEntityHandle(), getLayerName(), m_saveModelSpaceHandle, and m_version.
Referenced by Import::ImpExpDxfWrite::exportCircle().
writeClassesSection()
void CDxfWrite::writeClassesSection ()
Definition at line 129 of file dxf.cpp.
References getPlateFile(), m_dataDir, and m_version.
Referenced by endRun().
writeDiametricDim()
void CDxfWrite::writeDiametricDim (const double * textMidPoint, const double * arcPoint1, const double * arcPoint2, const char * dimText)
Definition at line 1348 of file dxf.cpp.
References getEntityHandle(), getLayerName(), m_saveModelSpaceHandle, m_version, writeBlockTrailer(), writeDiametricDimBlock(), and writeDimBlockPreamble().
Referenced by Import::ImpExpDxfWrite::exportDiametricDim().
writeDiametricDimBlock()
void CDxfWrite::writeDiametricDimBlock (const double * textMidPoint, const double * arcPoint1, const double * arcPoint2, const char * dimText)
Definition at line 1710 of file dxf.cpp.
References NavigationIndicatorGui::a1, NavigationIndicatorGui::a2, getBlockHandle(), m_saveBlkRecordHandle, MakeVector3d(), Base::Vector3< float_type >::Normalize(), putArrow(), putLine(), putText(), toVector3d(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by writeDiametricDim().
writeDimBlockPreamble()
void CDxfWrite::writeDimBlockPreamble ()
Definition at line 1413 of file dxf.cpp.
References addBlockName(), getBlkRecordHandle(), getBlockHandle(), getLayerName(), m_currentBlock, m_saveBlkRecordHandle, and m_version.
Referenced by writeAngularDim(), writeDiametricDim(), writeLinearDim(), and writeRadialDim().
writeEllipse()
void CDxfWrite::writeEllipse (const double * center, double major_radius, double minor_radius, double rotation, double start_angle, double end_angle, bool endIsCW)
Definition at line 782 of file dxf.cpp.
References exportCSG::center(), KDL::cos(), getEntityHandle(), getLayerName(), test::m, m_saveModelSpaceHandle, m_version, and KDL::sin().
Referenced by Import::ImpExpDxfWrite::exportEllipse(), and Import::ImpExpDxfWrite::exportEllipseArc().
writeEntitiesSection()
void CDxfWrite::writeEntitiesSection ()
Definition at line 1771 of file dxf.cpp.
References getPlateFile(), m_dataDir, and m_version.
Referenced by endRun().
writeHeaderSection()
void CDxfWrite::writeHeaderSection ()
Definition at line 107 of file dxf.cpp.
References App::Application::Config(), getPlateFile(), m_dataDir, and m_version.
Referenced by init().
writeLine()
void CDxfWrite::writeLine (const double * start, const double * end)
Definition at line 516 of file dxf.cpp.
References getEntityHandle(), m_saveModelSpaceHandle, putLine(), and toVector3d().
Referenced by Import::ImpExpDxfWrite::exportLine().
writeLinearDim()
void CDxfWrite::writeLinearDim (const double * textMidPoint, const double * lineDefPoint, const double * extLine1, const double * extLine2, const char * dimText, int type)
Definition at line 1100 of file dxf.cpp.
References ALIGNED, getEntityHandle(), getLayerName(), HORIZONTAL, m_saveModelSpaceHandle, m_version, Path.Post.scripts.grbl_post::type, VERTICAL, writeBlockTrailer(), writeDimBlockPreamble(), and writeLinearDimBlock().
Referenced by Import::ImpExpDxfWrite::exportLinearDim().
writeLinearDimBlock()
void CDxfWrite::writeLinearDimBlock (const double * textMidPoint, const double * lineDefPoint, const double * extLine1, const double * extLine2, const char * dimText, int type)
Definition at line 1483 of file dxf.cpp.
References ALIGNED, Base::Vector3< float_type >::DistanceToLineSegment(), getBlockHandle(), HORIZONTAL, m_saveBlkRecordHandle, MakeVector3d(), Base::Vector3< float_type >::Normalize(), putArrow(), putLine(), putText(), toVector3d(), Path.Post.scripts.grbl_post::type, VERTICAL, MovieTool::x, and MovieTool::y.
Referenced by writeLinearDim().
writeLWPolyLine()
void CDxfWrite::writeLWPolyLine (const LWPolyDataOut & pd)
Definition at line 565 of file dxf.cpp.
References SCL.SimpleDataTypes::b, LWPolyDataOut::Bulge, SCL.SimpleDataTypes::e, LWPolyDataOut::EndWidth, LWPolyDataOut::Flag, getEntityHandle(), getLayerName(), m_saveModelSpaceHandle, m_version, LWPolyDataOut::nVert, buildPsets::p, toolbit-attributes::s, LWPolyDataOut::StartWidth, and LWPolyDataOut::Verts.
Referenced by Import::ImpExpDxfWrite::exportLWPoly().
writeObjectsSection()
void CDxfWrite::writeObjectsSection ()
Definition at line 1789 of file dxf.cpp.
References getPlateFile(), m_dataDir, and m_version.
Referenced by endRun().
writePoint()
void CDxfWrite::writePoint (const double * point)
Definition at line 673 of file dxf.cpp.
References getEntityHandle(), getLayerName(), m_saveModelSpaceHandle, and m_version.
Referenced by Import::ImpExpDxfWrite::exportShape().
writePolyline()
void CDxfWrite::writePolyline (const LWPolyDataOut & pd)
Definition at line 623 of file dxf.cpp.
References getEntityHandle(), getLayerName(), m_saveModelSpaceHandle, m_version, buildPsets::p, and LWPolyDataOut::Verts.
Referenced by Import::ImpExpDxfWrite::exportPolyline().
writeRadialDim()
void CDxfWrite::writeRadialDim (const double * centerPoint, const double * textMidPoint, const double * arcPoint, const char * dimText)
Definition at line 1283 of file dxf.cpp.
References getEntityHandle(), getLayerName(), m_saveModelSpaceHandle, m_version, writeBlockTrailer(), writeDimBlockPreamble(), and writeRadialDimBlock().
Referenced by Import::ImpExpDxfWrite::exportRadialDim().
writeRadialDimBlock()
void CDxfWrite::writeRadialDimBlock (const double * centerPoint, const double * textMidPoint, const double * arcPoint, const char * dimText)
Definition at line 1673 of file dxf.cpp.
References a, exportCSG::center(), getBlockHandle(), m_saveBlkRecordHandle, MakeVector3d(), Base::Vector3< float_type >::Normalize(), putArrow(), putLine(), putText(), toVector3d(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by writeRadialDim().
writeSpline()
void CDxfWrite::writeSpline (const SplineDataOut & sd)
Definition at line 844 of file dxf.cpp.
References exportCSG::center(), SplineDataOut::control, SplineDataOut::control_points, SplineDataOut::degree, SCL.SimpleDataTypes::f, SplineDataOut::fit, SplineDataOut::flag, getEntityHandle(), getLayerName(), SplineDataOut::knot, SplineDataOut::knots, m_saveModelSpaceHandle, m_version, src.Mod.PartDesign.fcgear.svggear::w, and SplineDataOut::weight.
Referenced by Import::ImpExpDxfWrite::exportBSpline().
writeTablesSection()
void CDxfWrite::writeTablesSection ()
Definition at line 145 of file dxf.cpp.
References getPlateFile(), m_dataDir, and m_version.
Referenced by endRun().
writeText()
void CDxfWrite::writeText (const char * text, const double * location1, const double * location2, double height, int horizJust)
Definition at line 952 of file dxf.cpp.
References getEntityHandle(), m_saveModelSpaceHandle, putText(), and toVector3d().
Referenced by Import::ImpExpDxfWrite::exportText().
writeVertex()
void CDxfWrite::writeVertex (double x, double y, double z)
Definition at line 924 of file dxf.cpp.
References getEntityHandle(), getLayerName(), m_saveModelSpaceHandle, m_version, MovieTool::x, and MovieTool::y.
Member Data Documentation
m_blkRecordHandle
int CDxfWrite::m_blkRecordHandle protected
Definition at line 310 of file dxf.h.
m_blkRecordList
std::vector<std::string> CDxfWrite::m_blkRecordList protected
Definition at line 322 of file dxf.h.
Referenced by addBlockName(), and makeBlockRecordTableBody().
m_blockHandle
int CDxfWrite::m_blockHandle protected
Definition at line 309 of file dxf.h.
m_blockList
std::vector<std::string> CDxfWrite::m_blockList protected
Definition at line 321 of file dxf.h.
Referenced by addBlockName(), makeBlockRecordTableBody(), and makeBlockRecordTableHead().
m_currentBlock
std::string CDxfWrite::m_currentBlock protected
Definition at line 317 of file dxf.h.
Referenced by makeBlockSectionHead(), and writeDimBlockPreamble().
m_dataDir
std::string CDxfWrite::m_dataDir protected
Definition at line 318 of file dxf.h.
Referenced by writeBlocksSection(), writeClassesSection(), writeEntitiesSection(), writeHeaderSection(), writeObjectsSection(), and writeTablesSection().
m_entityHandle
int CDxfWrite::m_entityHandle protected
Definition at line 307 of file dxf.h.
m_handle
int CDxfWrite::m_handle protected
Definition at line 306 of file dxf.h.
Referenced by getHandle().
m_layerHandle
int CDxfWrite::m_layerHandle protected
Definition at line 308 of file dxf.h.
m_layerList
std::vector<std::string> CDxfWrite::m_layerList protected
Definition at line 320 of file dxf.h.
Referenced by makeLayerTable(), and setLayerName().
m_layerName
std::string CDxfWrite::m_layerName protected
Definition at line 319 of file dxf.h.
Referenced by setLayerName().
m_optionSource
std::string CDxfWrite::m_optionSource protected
Definition at line 304 of file dxf.h.
m_polyOverride
bool CDxfWrite::m_polyOverride protected
Definition at line 311 of file dxf.h.
Referenced by Import::ImpExpDxfWrite::exportShape(), and Import::ImpExpDxfWrite::setOptions().
m_saveBlkRecordHandle
std::string CDxfWrite::m_saveBlkRecordHandle protected
Definition at line 316 of file dxf.h.
Referenced by writeAngularDimBlock(), writeBlockTrailer(), writeDiametricDimBlock(), writeDimBlockPreamble(), writeLinearDimBlock(), and writeRadialDimBlock().
m_saveBlockRecordTableHandle
std::string CDxfWrite::m_saveBlockRecordTableHandle protected
Definition at line 315 of file dxf.h.
Referenced by makeBlockRecordTableBody(), and makeBlockRecordTableHead().
m_saveModelSpaceHandle
std::string CDxfWrite::m_saveModelSpaceHandle protected
Definition at line 313 of file dxf.h.
Referenced by makeBlockRecordTableHead(), makeBlockSectionHead(), writeAngularDim(), writeArc(), writeCircle(), writeDiametricDim(), writeEllipse(), writeLine(), writeLinearDim(), writeLWPolyLine(), writePoint(), writePolyline(), writeRadialDim(), writeSpline(), writeText(), and writeVertex().
m_savePaperSpaceHandle
std::string CDxfWrite::m_savePaperSpaceHandle protected
Definition at line 314 of file dxf.h.
Referenced by makeBlockRecordTableHead(), and makeBlockSectionHead().
m_version
int CDxfWrite::m_version protected
Definition at line 305 of file dxf.h.
Referenced by Import::ImpExpDxfWrite::exportShape(), makeBlockRecordTableBody(), makeBlockRecordTableHead(), makeBlockSectionHead(), makeLayerTable(), putArrow(), putLine(), putText(), Import::ImpExpDxfWrite::setOptions(), writeAngularDim(), writeAngularDimBlock(), writeArc(), writeBlocksSection(), writeBlockTrailer(), writeCircle(), writeClassesSection(), writeDiametricDim(), writeDimBlockPreamble(), writeEllipse(), writeEntitiesSection(), writeHeaderSection(), writeLinearDim(), writeLWPolyLine(), writeObjectsSection(), writePoint(), writePolyline(), writeRadialDim(), writeSpline(), writeTablesSection(), and writeVertex().
The documentation for this class was generated from the following files:
dxf.h
dxf.cpp