FreeCAD: TechDraw::ShapeExtractor Class Reference
TechDraw::ShapeExtractor Class Reference
#include <ShapeExtractor.h>
Static Public Member Functions
static TopoDS_Shape getShapes (const std::vector< App::DocumentObject * > links, bool include2d=true)
static std::vector< TopoDS_Shape > getShapes2d (const std::vector< App::DocumentObject * > links)
static std::vector< TopoDS_Shape > getXShapes (const App::Link *xLink)
static TopoDS_Shape getShapesFused (const std::vector< App::DocumentObject * > links)
static TopoDS_Shape getShapeFromXLink (const App::Link *xLink)
static std::vector< TopoDS_Shape > getShapesFromXRoot (const App::DocumentObject *xLinkRoot)
static std::vector< TopoDS_Shape > getShapesFromObject (const App::DocumentObject *docObj)
static bool is2dObject (const App::DocumentObject *obj)
static bool isEdgeType (const App::DocumentObject *obj)
static bool isPointType (const App::DocumentObject *obj)
static bool isDraftPoint (const App::DocumentObject *obj)
static bool isDatumPoint (const App::DocumentObject *obj)
static bool isSketchObject (const App::DocumentObject *obj)
static bool isExplodedAssembly (const App::DocumentObject *obj)
static Base::Vector3d getLocation3dFromFeat (const App::DocumentObject *obj)
get the location of a point object
static TopoDS_Shape getLocatedShape (const App::DocumentObject *docObj)
get the located and oriented version of docObj shape
static bool checkShape (const App::DocumentObject *shapeObj, TopoDS_Shape shape)
static App::DocumentObject * getExplodedAssembly (std::vector< TopoDS_Shape > &sourceShapes, App::DocumentObject *link)
static void restoreExplodedAssembly (App::DocumentObject *link)
static App::DocumentObject * getLinkedObject (const App::DocumentObject *root)
Detailed Description
Definition at line 59 of file ShapeExtractor.h.
Member Function Documentation
checkShape()
bool ShapeExtractor::checkShape (const App::DocumentObject * shapeObj, TopoDS_Shape shape) static
true if shape fails validity check. A fail here is not a guarantee of later problems, but invalid shapes are known to cause issues with HLR_Algo and boolean ops.
Definition at line 505 of file ShapeExtractor.cpp.
References TechDraw::Preferences::checkShapesBeforeUse(), Base::Console(), TechDraw::Preferences::debugBadShape(), App::DocumentObject::getNameInDocument(), App::PropertyString::getValue(), App::DocumentObject::Label, and Base::ConsoleSingleton::Warning().
getExplodedAssembly()
static App::DocumentObject* TechDraw::ShapeExtractor::getExplodedAssembly (std::vector< TopoDS_Shape > & sourceShapes, App::DocumentObject * link) static
getLinkedObject()
static App::DocumentObject* TechDraw::ShapeExtractor::getLinkedObject (const App::DocumentObject * root) static
getLocatedShape()
TopoDS_Shape ShapeExtractor::getLocatedShape (const App::DocumentObject * docObj) static
get the located and oriented version of docObj shape
Definition at line 477 of file ShapeExtractor.cpp.
References Part::TopoShape::getShape(), Part::Feature::getTopoShape(), App::GeoFeature::globalPlacement(), and Data::ComplexGeoData::setPlacement().
Referenced by TechDraw::DrawBrokenView::breakBoundsFromObj(), TechDraw::DrawBrokenView::breaklineLength(), TechDraw::DrawBrokenView::breakPointsFromObj(), TechDraw::DrawBrokenView::isBreakObject(), and TechDraw::DrawBrokenView::isBreakObjectSketch().
getLocation3dFromFeat()
Base::Vector3d ShapeExtractor::getLocation3dFromFeat (const App::DocumentObject * obj) static
get the location of a point object
Definition at line 453 of file ShapeExtractor.cpp.
References Part::PropertyPartShape::getShape(), Part::TopoShape::getShape(), App::GeoFeature::globalPlacement(), Data::ComplexGeoData::setPlacement(), Part::Feature::Shape, src.Mod.Test.UnitTests::ts(), TestSpreadsheet::v, and TechDraw::DrawUtil::vertex2Vector().
Referenced by TechDraw::LandmarkDimension::execute(), and TechDraw::LandmarkDimension::onDocumentRestored().
getShapeFromXLink()
TopoDS_Shape ShapeExtractor::getShapeFromXLink (const App::Link * xLink) static
Definition at line 269 of file ShapeExtractor.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), App::LinkBaseExtension::getLink(), App::DocumentObject::getNameInDocument(), App::LinkBaseExtension::getScaleVector(), Part::Feature::getShape(), App::LinkBaseExtension::hasPlacement(), Base::Matrix4D::scale(), and src.Mod.Test.UnitTests::ts().
getShapes()
TopoDS_Shape ShapeExtractor::getShapes (const std::vector< App::DocumentObject * > links, bool include2d = true) static
get the located and oriented shapes corresponding to the the links. If the shapes are to be fused, include2d should be false as 2d & 3d shapes may not fuse.
Definition at line 86 of file ShapeExtractor.cpp.
References toolbit-attributes::args, Base::Persistence::getClassTypeId(), getLocatedShape(), Part::Feature::getShape(), Base::BaseClass::isDerivedFrom(), TechDraw::ShapeUtils::isShapeReallyNull(), RobotExample::l, and toolbit-attributes::s.
Referenced by TechDraw::DrawViewPart::getSourceShape().
getShapes2d()
std::vector< TopoDS_Shape > ShapeExtractor::getShapes2d (const std::vector< App::DocumentObject * > links) static
pick out the 2d document objects in the list of links and return a vector of their shapes Note that point objects will not make it through the hlr/projection process.
Definition at line 66 of file ShapeExtractor.cpp.
References Base::Persistence::getClassTypeId(), getLocatedShape(), and RobotExample::l.
Referenced by TechDraw::DrawViewPart::addPoints().
getShapesFromObject()
std::vector< TopoDS_Shape > ShapeExtractor::getShapesFromObject (const App::DocumentObject * docObj) static
Definition at line 310 of file ShapeExtractor.cpp.
References getLocatedShape(), App::ExtensionContainer::getPropertyByName(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::GroupExtension::Group, Base::BaseClass::isDerivedFrom(), replaceobj::objs, and result.
Referenced by TechDraw::isValidMultiEdge3d().
getShapesFromXRoot()
static std::vector<TopoDS_Shape> TechDraw::ShapeExtractor::getShapesFromXRoot (const App::DocumentObject * xLinkRoot) static
getShapesFused()
TopoDS_Shape ShapeExtractor::getShapesFused (const std::vector< App::DocumentObject * > links) static
Definition at line 351 of file ShapeExtractor.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), importDXF::getShapes(), and TechDraw::DrawUtil::shapeVectorToCompound().
Referenced by TechDraw::DrawViewPart::getSourceShape().
getXShapes()
std::vector< TopoDS_Shape > ShapeExtractor::getXShapes (const App::Link * xLink) static
Definition at line 190 of file ShapeExtractor.cpp.
References Base::Console(), App::LinkBaseExtension::getLinkedChildren(), App::LinkBaseExtension::getScaleVector(), Part::Feature::getShape(), App::LinkBaseExtension::hasPlacement(), RobotExample::l, Base::ConsoleSingleton::Message(), Base::Matrix4D::scale(), Base::Placement::toMatrix(), and src.Mod.Test.UnitTests::ts().
is2dObject()
bool ShapeExtractor::is2dObject (const App::DocumentObject * obj) static
Definition at line 385 of file ShapeExtractor.cpp.
References Assembly::isEdgeType().
isDatumPoint()
bool ShapeExtractor::isDatumPoint (const App::DocumentObject * obj) static
Definition at line 441 of file ShapeExtractor.cpp.
References Base::Type::getName(), and Base::Persistence::getTypeId().
isDraftPoint()
bool ShapeExtractor::isDraftPoint (const App::DocumentObject * obj) static
Definition at line 428 of file ShapeExtractor.cpp.
References App::ExtensionContainer::getPropertyByName(), and App::PropertyPythonObject::toString().
isEdgeType()
bool ShapeExtractor::isEdgeType (const App::DocumentObject * obj) static
Definition at line 398 of file ShapeExtractor.cpp.
References Base::Persistence::getClassTypeId(), Base::Persistence::getTypeId(), and InitGui::t.
isExplodedAssembly()
static bool TechDraw::ShapeExtractor::isExplodedAssembly (const App::DocumentObject * obj) static
isPointType()
bool ShapeExtractor::isPointType (const App::DocumentObject * obj) static
Definition at line 413 of file ShapeExtractor.cpp.
References Base::Persistence::getClassTypeId(), Base::Persistence::getTypeId(), exportDRAWEXE::isDraftPoint(), and InitGui::t.
isSketchObject()
bool ShapeExtractor::isSketchObject (const App::DocumentObject * obj) static
Definition at line 487 of file ShapeExtractor.cpp.
References Base::Type::getName(), and Base::Persistence::getTypeId().
Referenced by TechDraw::DrawBrokenView::breakBoundsFromObj(), TechDraw::DrawBrokenView::breaklineLength(), TechDraw::DrawBrokenView::breakPointsFromObj(), and TechDraw::DrawBrokenView::isBreakObject().
restoreExplodedAssembly()
static void TechDraw::ShapeExtractor::restoreExplodedAssembly (App::DocumentObject * link) static
The documentation for this class was generated from the following files:
ShapeExtractor.h
ShapeExtractor.cpp