FreeCAD: Area.cpp File Reference
libarea/Area.cpp File Reference
#include "Area.h"
#include "AreaOrderer.h"
#include <map>
Classes
class ZigZag
class ThickLine
Macros
#define _CAREA_PARAM_DEFINE(_class, _type, _name)
#define CAREA_PARAM_DEFINE(_type, _name)
Functions
static Point rotated_point (const Point &p)
static Point unrotated_point (const Point &p)
static CVertex rotated_vertex (const CVertex &v)
static CVertex unrotated_vertex (const CVertex &v)
static void rotate_area (CArea &a)
void test_y_point (int i, const Point &p, Point &best_p, bool &found, int &best_index, double y, bool left_not_right)
static void make_zig_curve (const CCurve &input_curve, double y0, double y)
void make_zig (const CArea &a, double y0, double y)
void add_reorder_zig (ZigZag &zigzag)
void reorder_zigs ()
static void zigzag (const CArea &input_a)
eOverlapType GetOverlapType (const CCurve &c1, const CCurve &c2)
eOverlapType GetOverlapType (const CArea &a1, const CArea &a2)
bool IsInside (const Point &p, const CCurve &c)
bool IsInside (const Point &p, const CArea &a)
Variables
static double stepover_for_pocket = 0.0
static std::list< ZigZag > zigzag_list_for_zigs
static std::list< CCurve > * curve_list_for_zigs = NULL
static bool rightward_for_zigs = true
static double sin_angle_for_zigs = 0.0
static double cos_angle_for_zigs = 0.0
static double sin_minus_angle_for_zigs = 0.0
static double cos_minus_angle_for_zigs = 0.0
static double one_over_units = 0.0
std::list< std::list< ZigZag > > reorder_zig_list_list
Macro Definition Documentation
_CAREA_PARAM_DEFINE
#define _CAREA_PARAM_DEFINE (_class, _type, _name)
Value:
    _type CArea::get_##_name()                                                                     \
    {                                                                                              \
        return _class::_name;                                                                      \
    }                                                                                              \
    void CArea::set_##_name(_type _name)                                                           \
    {                                                                                              \
        _class::_name = _name;                                                                     \
    }
Definition at line 27 of file libarea/Area.cpp.
CAREA_PARAM_DEFINE
#define CAREA_PARAM_DEFINE (_type, _name)
Value:
    _type CArea::get_##_name()                                                                     \
    {                                                                                              \
        return m_##_name;                                                                          \
    }                                                                                              \
    void CArea::set_##_name(_type _name)                                                           \
    {                                                                                              \
        m_##_name = _name;                                                                         \
    }
Definition at line 37 of file libarea/Area.cpp.
Function Documentation
add_reorder_zig()
void add_reorder_zig (ZigZag & zigzag)
Definition at line 447 of file libarea/Area.cpp.
References SCL.SimpleDataTypes::e, CCurve::m_vertices, one_over_units, reorder_zig_list_list, TestSpreadsheet::v, Point::x, Point::y, ZigZag::zig, and zigzag().
Referenced by reorder_zigs().
GetOverlapType() [1/2]
eOverlapType GetOverlapType (const CArea & a1, const CArea & a2)
Definition at line 852 of file libarea/Area.cpp.
References NavigationIndicatorGui::a1, NavigationIndicatorGui::a2, eCrossing, eInside, eOutside, eSiblings, CArea::Intersect(), CArea::m_curves, and CArea::Subtract().
GetOverlapType() [2/2]
eOverlapType GetOverlapType (const CCurve & c1, const CCurve & c2)
Definition at line 842 of file libarea/Area.cpp.
References NavigationIndicatorGui::a1, NavigationIndicatorGui::a2, src.Mod.PartDesign.Scripts.Gear::c1, and GetOverlapType().
Referenced by GetOverlapType(), CInnerCurves::Insert(), and MarkOverlappingOffsetIslands().
IsInside() [1/2]
bool IsInside (const Point & p, const CArea & a)
Definition at line 883 of file libarea/Area.cpp.
References a, NavigationIndicatorGui::a2, SCL.SimpleDataTypes::c, and buildPsets::p.
IsInside() [2/2]
bool IsInside (const Point & p, const CCurve & c)
Definition at line 876 of file libarea/Area.cpp.
References a, SCL.SimpleDataTypes::c, IsInside(), and buildPsets::p.
Referenced by CArea::InsideCurves(), and IsInside().
make_zig()
void make_zig (const CArea & a, double y0, double y)
Definition at line 437 of file libarea/Area.cpp.
References a, make_zig_curve(), and MovieTool::y.
Referenced by zigzag().
make_zig_curve()
static void make_zig_curve (const CCurve & input_curve, double y0, double y) static
Definition at line 302 of file libarea/Area.cpp.
References SplineSurface::i, CCurve::IsClockwise(), CVertex::m_p, CCurve::m_vertices, CCurve::Reverse(), rightward_for_zigs, test_y_point(), unrotated_vertex(), MovieTool::y, and zigzag_list_for_zigs.
Referenced by make_zig().
reorder_zigs()
void reorder_zigs ()
Definition at line 499 of file libarea/Area.cpp.
References add_reorder_zig(), curve_list_for_zigs, reorder_zig_list_list, TestSpreadsheet::v, zigzag(), and zigzag_list_for_zigs.
Referenced by zigzag().
rotate_area()
static void rotate_area (CArea & a) static
Definition at line 254 of file libarea/Area.cpp.
References a, CCurve::m_vertices, and rotated_vertex().
Referenced by zigzag().
rotated_point()
static Point rotated_point (const Point & p) static
Definition at line 226 of file libarea/Area.cpp.
References cos_angle_for_zigs, buildPsets::p, and sin_angle_for_zigs.
Referenced by rotated_vertex().
rotated_vertex()
static CVertex rotated_vertex (const CVertex & v) static
Definition at line 238 of file libarea/Area.cpp.
References rotated_point(), and TestSpreadsheet::v.
Referenced by rotate_area().
test_y_point()
void test_y_point (int i, const Point & p, Point & best_p, bool & found, int & best_index, double y, bool left_not_right)
Definition at line 267 of file libarea/Area.cpp.
References SplineSurface::i, one_over_units, buildPsets::p, Point::x, and MovieTool::y.
Referenced by make_zig_curve().
unrotated_point()
static Point unrotated_point (const Point & p) static
Definition at line 232 of file libarea/Area.cpp.
References cos_minus_angle_for_zigs, buildPsets::p, and sin_minus_angle_for_zigs.
Referenced by unrotated_vertex().
unrotated_vertex()
static CVertex unrotated_vertex (const CVertex & v) static
Definition at line 246 of file libarea/Area.cpp.
References unrotated_point(), and TestSpreadsheet::v.
Referenced by make_zig_curve().
zigzag()
static void zigzag (const CArea & input_a) static
Definition at line 548 of file libarea/Area.cpp.
References a, NavigationIndicatorGui::a2, SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::c, SplineSurface::i, CArea::m_curves, CArea::m_please_abort, CArea::m_processing_done, CArea::m_single_area_processing_length, CArea::m_units, make_zig(), one_over_units, reorder_zigs(), rightward_for_zigs, rotate_area(), stepover_for_pocket, and MovieTool::y.
Referenced by add_reorder_zig(), CArea::MakePocketToolpath(), and reorder_zigs().
Variable Documentation
cos_angle_for_zigs
double cos_angle_for_zigs = 0.0 static
Definition at line 221 of file libarea/Area.cpp.
Referenced by CArea::MakePocketToolpath(), and rotated_point().
cos_minus_angle_for_zigs
double cos_minus_angle_for_zigs = 0.0 static
Definition at line 223 of file libarea/Area.cpp.
Referenced by CArea::MakePocketToolpath(), and unrotated_point().
curve_list_for_zigs
std::list<CCurve>* curve_list_for_zigs = NULL static
Definition at line 218 of file libarea/Area.cpp.
Referenced by CArea::MakePocketToolpath(), and reorder_zigs().
one_over_units
double one_over_units = 0.0 static
Definition at line 224 of file libarea/Area.cpp.
Referenced by add_reorder_zig(), test_y_point(), and zigzag().
reorder_zig_list_list
std::list<std::list<ZigZag> > reorder_zig_list_list
Definition at line 445 of file libarea/Area.cpp.
Referenced by add_reorder_zig(), and reorder_zigs().
rightward_for_zigs
bool rightward_for_zigs = true static
Definition at line 219 of file libarea/Area.cpp.
Referenced by make_zig_curve(), and zigzag().
sin_angle_for_zigs
double sin_angle_for_zigs = 0.0 static
Definition at line 220 of file libarea/Area.cpp.
Referenced by CArea::MakePocketToolpath(), and rotated_point().
sin_minus_angle_for_zigs
double sin_minus_angle_for_zigs = 0.0 static
Definition at line 222 of file libarea/Area.cpp.
Referenced by CArea::MakePocketToolpath(), and unrotated_point().
stepover_for_pocket
double stepover_for_pocket = 0.0 static
Definition at line 216 of file libarea/Area.cpp.
Referenced by CArea::MakePocketToolpath(), and zigzag().
zigzag_list_for_zigs
std::list<ZigZag> zigzag_list_for_zigs static
Definition at line 217 of file libarea/Area.cpp.
Referenced by make_zig_curve(), and reorder_zigs().