FreeCAD: App::PropertyInteger Class Reference
App::PropertyInteger Class Reference
#include <PropertyStandard.h>
Public Member Functions
PropertyInteger ()
~PropertyInteger () override
void setValue (long)
long getValue () const
const char * getEditorName () const override
Get the class name of the associated property editor item.
PyObject * getPyObject () override
void setPyObject (PyObject *py) override
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
Property * Copy () const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
unsigned int getMemSize () const override
void setPathValue (const App::ObjectIdentifier &path, const boost::any &value) override
Set value of property.
const boost::any getPathValue (const App::ObjectIdentifier &) const override
Get value of property.
bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
Public Member Functions inherited from App::Property
Property ()
~Property () override
const char * getName () const
bool hasName () const
std::string getFullName () const
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual void afterRestore ()
virtual void onContainerRestored ()
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
int64_t getID () const
virtual void beforeSave () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Attributes
long _lValue
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::Property
virtual void hasSetValue ()
Gets called by all setValue() methods after the value has changed.
virtual void aboutToSetValue ()
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Integer properties This is the father of all properties handling Integers.
Definition at line 54 of file PropertyStandard.h.
Constructor & Destructor Documentation
PropertyInteger()
PropertyInteger::PropertyInteger ()
Definition at line 62 of file PropertyStandard.cpp.
~PropertyInteger()
PropertyInteger::~PropertyInteger () override default
Member Function Documentation
Copy()
Property * PropertyInteger::Copy () const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 118 of file PropertyStandard.cpp.
References buildPsets::p.
getEditorName()
const char* App::PropertyInteger::getEditorName () const inline override virtual
Get the class name of the associated property editor item.
Reimplemented from App::Property.
Reimplemented in App::PropertyIntegerConstraint.
Definition at line 69 of file PropertyStandard.h.
getMemSize()
unsigned int App::PropertyInteger::getMemSize () const inline override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence
See also
Base::Persistence
Reimplemented from App::Property.
Definition at line 83 of file PropertyStandard.h.
References OpenSCADFeatures::long.
getPathValue()
const boost::any App::PropertyInteger::getPathValue (const App::ObjectIdentifier & path) const inline override virtual
Get value of property.
Reimplemented from App::Property.
Definition at line 89 of file PropertyStandard.h.
getPyObject()
PyObject * PropertyInteger::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 86 of file PropertyStandard.cpp.
getValue()
long PropertyInteger::getValue () const
This method returns a string representation of the property
Definition at line 81 of file PropertyStandard.cpp.
Referenced by StdCmdToggleTransparency::activated(), TechDraw::DrawViewPart::buildGeometryObject(), App::LinkElement::canDelete(), TechDrawGui::QGIViewSection::drawSectionFace(), TechDrawGui::QGIWeldSymbol::drawTile(), App::FunctionExpression::evalAggregate(), Surface::Filling::execute(), Points::Structured::execute(), Surface::Extend::execute(), Part::Loft::execute(), App::FeatureTest::execute(), Mesh::FillHoles::execute(), Mesh::RemoveComponents::execute(), PartDesign::Prism::execute(), App::LinkBaseExtension::extensionExecute(), PartGui::ViewProviderPartExt::getElementColors(), TechDraw::DrawPage::getNextBalloonIndex(), TechDraw::DrawViewDimExtent::getPointsExtent(), TechDrawGui::QGIWeldSymbol::getTileFeats(), TechDrawGui::TaskWeldingSymbol::getTileFeats(), PartDesign::LinearPattern::getTransformations(), PartDesign::PolarPattern::getTransformations(), PartDesign::Scaled::getTransformations(), TechDrawGui::ViewProviderDrawingView::getZ(), TechDrawGui::ViewProviderLeader::handleChangedPropertyType(), TechDrawGui::ViewProviderRichAnno::handleChangedPropertyType(), TechDraw::DrawTile::handleChangedPropertyType(), PartDesign::LinearPattern::handleChangedPropertyType(), PartDesign::PolarPattern::handleChangedPropertyType(), TechDraw::DrawViewAnnotation::handleChangedPropertyType(), TechDraw::GeometryObject::makeTDGeometry(), PartDesignGui::ViewProviderDatumCoordinateSystem::onChanged(), PartDesignGui::ViewProviderDatumPoint::onChanged(), Sandbox::SandboxObject::onChanged(), PartDesign::LinearPattern::onChanged(), Gui::ViewProviderGeometryObject::onChanged(), Surface::FeatureBlendCurve::onChanged(), FemGui::ViewProviderFemMesh::onChanged(), PartGui::ViewProviderPartExt::onChanged(), MeshGui::ViewProviderMesh::onChanged(), PartDesign::SubShapeBinder::onDocumentRestored(), PartGui::PolygonPrimitive::PolygonPrimitive(), PartGui::PrismPrimitive::PrismPrimitive(), TechDrawGui::ViewProviderDrawingView::stackBottom(), TechDrawGui::ViewProviderDrawingView::stackTop(), FemGui::TaskTetParameter::TaskTetParameter(), MeshGui::ViewProviderMesh::tryColorPerVertexOrFace(), PartDesign::SubShapeBinder::update(), PartGui::ViewProviderMultiFuse::updateData(), FemGui::ViewProviderFemMesh::updateData(), PartGui::ViewProviderBoolean::updateData(), PartGui::ViewProviderCompound::updateData(), PartGui::ViewProviderFillet::updateData(), PartGui::ViewProviderMultiCommon::updateData(), PartGui::ViewProviderChamfer::updateData(), Gui::PropertyEditor::PropertyIntegerItem::value(), Gui::PropertyEditor::PropertyIntegerConstraintItem::value(), and PartDesignGui::ViewProviderDatumCoordinateSystem::ViewProviderDatumCoordinateSystem().
isSame()
bool App::PropertyInteger::isSame (const Property & other) const inline override virtual
Compare if this property has the same content as the given one.
Reimplemented from App::Property.
Definition at line 94 of file PropertyStandard.h.
References Base::Persistence::getTypeId(), and getValue().
Paste()
void PropertyInteger::Paste (const Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 125 of file PropertyStandard.cpp.
Restore()
void PropertyInteger::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 110 of file PropertyStandard.cpp.
References TechDrawTools.TaskFillTemplateFields::reader.
Referenced by TechDrawGui::ViewProviderLeader::handleChangedPropertyType(), TechDrawGui::ViewProviderRichAnno::handleChangedPropertyType(), TechDraw::DrawTile::handleChangedPropertyType(), PartDesign::LinearPattern::handleChangedPropertyType(), PartDesign::PolarPattern::handleChangedPropertyType(), and TechDraw::DrawViewAnnotation::handleChangedPropertyType().
Save()
void PropertyInteger::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 105 of file PropertyStandard.cpp.
References Base::Writer::ind(), and Base::Writer::Stream().
setPathValue()
void PropertyInteger::setPathValue (const App::ObjectIdentifier & path, const boost::any & value) override virtual
Set value of property.
Reimplemented from App::Property.
Definition at line 132 of file PropertyStandard.cpp.
References getValue(), and src.Mod.Test.testPathArray::path.
setPyObject()
void PropertyInteger::setPyObject (PyObject * py) override virtual
Reimplemented from Base::BaseClass.
Reimplemented in App::PropertyIntegerConstraint.
Definition at line 91 of file PropertyStandard.cpp.
References Path.Log::error().
setValue()
void PropertyInteger::setValue (long lValue)
Sets the property
Definition at line 74 of file PropertyStandard.cpp.
Referenced by TechDrawGui::TaskSurfaceFinishSymbols::accept(), StdCmdToggleTransparency::activated(), PartGui::PrismPrimitive::changeValue(), PartGui::PolygonPrimitive::changeValue(), App::FeatureTest::execute(), App::FeatureTestColumn::execute(), App::FeatureTestRow::execute(), TechDraw::DrawPage::getNextBalloonIndex(), TechDraw::DrawTile::handleChangedPropertyType(), PartDesign::LinearPattern::handleChangedPropertyType(), PartDesign::PolarPattern::handleChangedPropertyType(), TechDraw::DrawViewAnnotation::handleChangedPropertyType(), PartDesignGui::ViewProviderDatumPoint::onChanged(), PartDesignGui::ViewProviderSubShapeBinder::onChanged(), Gui::ViewProviderGeometryObject::onChanged(), Surface::FeatureBlendCurve::onChanged(), FemGui::ViewProviderFemMesh::onChanged(), TechDraw::DrawWeldSymbol::onSettingDocument(), Sandbox::SandboxObject::resetValue(), Sandbox::DocumentTestThread::run(), Spreadsheet::Sheet::setIntegerProperty(), Sandbox::SandboxObject::setIntValue(), App::LinkBaseExtension::setLink(), PartDesign::SubShapeBinder::setupObject(), PartDesignGui::ViewProviderDatum::ViewProviderDatum(), and FemGui::ViewProviderFemMesh::ViewProviderFemMesh().
Member Data Documentation
_lValue
long App::PropertyInteger::_lValue protected
Definition at line 104 of file PropertyStandard.h.
The documentation for this class was generated from the following files:
PropertyStandard.h
PropertyStandard.cpp