FreeCAD: InspectionGui Namespace Reference
InspectionGui Namespace Reference
Classes
class Module
class SingleSelectionItem
class ViewProviderInspection
class ViewProviderInspectionGroup
class ViewProviderProxyObject
class VisualInspection
class Workbench
Functions
PyObject * initModule ()
float calcArea (const SbVec3f &v1, const SbVec3f &v2, const SbVec3f &v3)
bool calcWeights (const SbVec3f &v1, const SbVec3f &v2, const SbVec3f &v3, const SbVec3f &p, float &w0, float &w1, float &w2)
Function Documentation
calcArea()
float InspectionGui::calcArea (const SbVec3f & v1, const SbVec3f & v2, const SbVec3f & v3)
Definition at line 632 of file ViewProviderInspection.cpp.
References a, SCL.SimpleDataTypes::b, and draftgeoutils.general::v1().
Referenced by calcWeights().
calcWeights()
bool InspectionGui::calcWeights (const SbVec3f & v1, const SbVec3f & v2, const SbVec3f & v3, const SbVec3f & p, float & w0, float & w1, float & w2)
Definition at line 639 of file ViewProviderInspection.cpp.
References calcArea(), SCL.SimpleDataTypes::f, buildPsets::p, and draftgeoutils.general::v1().
Referenced by InspectionGui::ViewProviderInspection::inspectDistance().
initModule()
PyObject* InspectionGui::initModule ()
Definition at line 52 of file AppInspectionGui.cpp.
References Base::InterpreterSingleton::addModule(), and Base::Interpreter().
Referenced by PyMOD_INIT_FUNC().