FreeCAD: Gui::SoColorBarLabel Class Reference
Gui::SoColorBarLabel Class Reference
#include <SoTextLabel.h>
Public Member Functions
SoColorBarLabel ()
Static Public Member Functions
static void initClass ()
Protected Member Functions
void computeBBox (SoAction *action, SbBox3f &box, SbVec3f &center) override
Detailed Description
A text label for the color bar.
Author
Werner Mayer
Definition at line 88 of file SoTextLabel.h.
Constructor & Destructor Documentation
SoColorBarLabel()
SoColorBarLabel::SoColorBarLabel ()
Definition at line 269 of file SoTextLabel.cpp.
Member Function Documentation
computeBBox()
void SoColorBarLabel::computeBBox (SoAction * action, SbBox3f & box, SbVec3f & center) override protected
Definition at line 274 of file SoTextLabel.cpp.
References Path.Post.scripts.dynapath_4060_post::action, MengerSponge::box, exportCSG::center(), and SCL.SimpleDataTypes::f.
initClass()
void SoColorBarLabel::initClass () static
Definition at line 264 of file SoTextLabel.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
The documentation for this class was generated from the following files:
SoTextLabel.h
SoTextLabel.cpp