FreeCAD: Base::NormalBindingItem Class Reference
Base::NormalBindingItem Class Reference
The MaterialBindingItem class supports the SoMaterialBinding node.
#include <Builder3D.h>
Public Member Functions
NormalBindingItem ()=default
void setValue (BindingElement::Binding bind)
void write (InventorOutput &out) const override
Public Member Functions inherited from Base::NodeItem
virtual ~NodeItem ()=default
Additional Inherited Members
Protected Member Functions inherited from Base::NodeItem
NodeItem ()=default
NodeItem (const NodeItem &)=default
NodeItem (NodeItem &&)=default
NodeItem & operator= (const NodeItem &)=default
NodeItem & operator= (NodeItem &&)=default
Detailed Description
The MaterialBindingItem class supports the SoMaterialBinding node.
Definition at line 570 of file Builder3D.h.
Constructor & Destructor Documentation
NormalBindingItem()
Base::NormalBindingItem::NormalBindingItem () default
Member Function Documentation
setValue()
void NormalBindingItem::setValue (BindingElement::Binding bind)
Definition at line 813 of file Builder3D.cpp.
References draftgeoutils.faces::bind(), and Base::BindingElement::value.
Referenced by WriterInventorImp::addNormalNode().
write()
void NormalBindingItem::write (InventorOutput & out) const override virtual
Implements Base::NodeItem.
Definition at line 818 of file Builder3D.cpp.
References Base::BindingElement::bindingAsString(), and Base::InventorOutput::write().
The documentation for this class was generated from the following files:
Builder3D.h
Builder3D.cpp