FreeCAD: ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship Class Reference
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship Class Reference
Public Member Functions
def __init__ (self, inherited0__id, inherited1__name, inherited2__description, inherited3__relating_product_definition, inherited4__related_product_definition, class_, constituent_amount, composition_basis, determination_method)
def class_ ()
def constituent_amount ()
def composition_basis ()
def determination_method ()
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_definition_relationship
def __init__ (self, id, name, description, relating_product_definition, related_product_definition)
def id ()
def name ()
def description ()
def relating_product_definition ()
def related_product_definition ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
class_
constituent_amount
composition_basis
determination_method
Public Attributes inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_definition_relationship
id
name
description
relating_product_definition
related_product_definition
Detailed Description
Entity product_material_composition_relationship definition.
:param class_
:type class_:label
:param constituent_amount
:type constituent_amount:SET(1,None,'characterized_product_composition_value', scope = schema_scope)
:param composition_basis
:type composition_basis:label
:param determination_method
:type determination_method:text
Definition at line 31709 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Constructor & Destructor Documentation
__init__()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship.__init__ (self, inherited0__id, inherited1__name, inherited2__description, inherited3__relating_product_definition, inherited4__related_product_definition, class_, constituent_amount, composition_basis, determination_method)
Definition at line 31724 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Member Function Documentation
class_()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship.class_ ()
Definition at line 31732 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship._class_, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship.class_.
composition_basis()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship.composition_basis ()
Definition at line 31760 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship._composition_basis, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship.composition_basis.
constituent_amount()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship.constituent_amount ()
Definition at line 31746 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship._constituent_amount, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship.constituent_amount.
determination_method()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship.determination_method ()
Definition at line 31774 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship._determination_method, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship.determination_method.
Member Data Documentation
class_
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship.class_
Definition at line 31726 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship.class_().
composition_basis
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship.composition_basis
Definition at line 31728 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship.composition_basis().
constituent_amount
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship.constituent_amount
Definition at line 31727 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship.constituent_amount().
determination_method
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship.determination_method
Definition at line 31729 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_material_composition_relationship.determination_method().
The documentation for this class was generated from the following file:
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py