FreeCAD: Gui::ToolBarGrip Class Reference
Gui::ToolBarGrip Class Reference
#include <ToolBarManager.h>
Public Member Functions
ToolBarGrip (QToolBar *)
void attach ()
void detach ()
bool isAttached () const
Protected Member Functions
void paintEvent (QPaintEvent *)
void mouseMoveEvent (QMouseEvent *)
void mousePressEvent (QMouseEvent *)
void mouseReleaseEvent (QMouseEvent *)
void updateSize ()
Detailed Description
Definition at line 92 of file ToolBarManager.h.
Constructor & Destructor Documentation
ToolBarGrip()
ToolBarGrip::ToolBarGrip (QToolBar * parent) explicit
Definition at line 231 of file ToolBarManager.cpp.
References updateSize().
Member Function Documentation
attach()
void ToolBarGrip::attach ()
Definition at line 237 of file ToolBarManager.cpp.
References isAttached(), and Init::parent.
Referenced by Path.Dressup.Gui.Boundary.DressupPathBoundaryViewProvider::__init__().
detach()
void ToolBarGrip::detach ()
Definition at line 262 of file ToolBarManager.cpp.
References isAttached(), and Init::parent.
isAttached()
bool ToolBarGrip::isAttached () const
Definition at line 277 of file ToolBarManager.cpp.
Referenced by attach(), and detach().
mouseMoveEvent()
void ToolBarGrip::mouseMoveEvent (QMouseEvent * me) protected
Definition at line 299 of file ToolBarManager.cpp.
References Gui::ToolBarManager::getInstance(), RobotExample::pos, and Gui::ToolBarManager::toolBarAreaWidget().
mousePressEvent()
void ToolBarGrip::mousePressEvent (QMouseEvent *) protected
Definition at line 358 of file ToolBarManager.cpp.
mouseReleaseEvent()
void ToolBarGrip::mouseReleaseEvent (QMouseEvent *) protected
Definition at line 363 of file ToolBarManager.cpp.
paintEvent()
void ToolBarGrip::paintEvent (QPaintEvent *) protected
Definition at line 282 of file ToolBarManager.cpp.
updateSize()
void ToolBarGrip::updateSize () protected
Definition at line 368 of file ToolBarManager.cpp.
References Init::parent.
Referenced by ToolBarGrip().
The documentation for this class was generated from the following files:
ToolBarManager.h
ToolBarManager.cpp