FreeCAD: Gui::PropertyEditor::PropertyItemProducer< CLASS > Class Template Reference
Gui::PropertyEditor::PropertyItemProducer< CLASS > Class Template Reference
#include <PropertyItem.h>
Public Member Functions
PropertyItemProducer (const char *className)
~PropertyItemProducer () override=default
void * Produce () const override
overwritten by a concrete producer to produce the needed object
Public Member Functions inherited from Base::AbstractProducer
AbstractProducer ()=default
virtual ~AbstractProducer ()=default
Detailed Description
template<class CLASS>
class Gui::PropertyEditor::PropertyItemProducer< CLASS >
Definition at line 107 of file PropertyItem.h.
Constructor & Destructor Documentation
PropertyItemProducer()
template<class CLASS > Gui::PropertyEditor::PropertyItemProducer< CLASS >::PropertyItemProducer (const char * className) inline explicit
Definition at line 110 of file PropertyItem.h.
References Base::Factory::AddProducer(), and Gui::PropertyEditor::PropertyItemFactory::instance().
~PropertyItemProducer()
template<class CLASS > Gui::PropertyEditor::PropertyItemProducer< CLASS >::~PropertyItemProducer () override default
Member Function Documentation
Produce()
template<class CLASS > void* Gui::PropertyEditor::PropertyItemProducer< CLASS >::Produce () const inline override virtual
overwritten by a concrete producer to produce the needed object
Implements Base::AbstractProducer.
Definition at line 115 of file PropertyItem.h.
References importers.importIFClegacy::create().
The documentation for this class was generated from the following file:
PropertyItem.h