FreeCAD: Gui::Dialog::TaskPlacementPy Class Reference
Gui::Dialog::TaskPlacementPy Class Reference
#include <Placement.h>
Public Types
using BaseType = Py::PythonExtension< TaskPlacementPy >
Public Member Functions
TaskPlacementPy ()
~TaskPlacementPy () override
Py::Object repr () override
Py::Object getattr (const char *name) override
int setattr (const char *name, const Py::Object &) override
Py::Object setPropertyName (const Py::Tuple &)
Py::Object setPlacement (const Py::Tuple &)
Py::Object setSelection (const Py::Tuple &)
Py::Object bindObject (const Py::Tuple &)
Py::Object setPlacementAndBindObject (const Py::Tuple &)
Py::Object setIgnoreTransactions (const Py::Tuple &)
Py::Object showDefaultButtons (const Py::Tuple &)
Py::Object accept (const Py::Tuple &)
Py::Object reject (const Py::Tuple &)
Py::Object clicked (const Py::Tuple &)
Py::Object open (const Py::Tuple &)
Py::Object isAllowedAlterDocument (const Py::Tuple &)
Py::Object isAllowedAlterView (const Py::Tuple &)
Py::Object isAllowedAlterSelection (const Py::Tuple &)
Py::Object getStandardButtons (const Py::Tuple &)
Static Public Member Functions
static void init_type ()
Detailed Description
Definition at line 230 of file Gui/Placement.h.
Member Typedef Documentation
BaseType
using Gui::Dialog::TaskPlacementPy::BaseType = Py::PythonExtension<TaskPlacementPy>
Definition at line 233 of file Gui/Placement.h.
Constructor & Destructor Documentation
TaskPlacementPy()
TaskPlacementPy::TaskPlacementPy ()
Definition at line 1280 of file Gui/Placement.cpp.
~TaskPlacementPy()
TaskPlacementPy::~TaskPlacementPy () override default
Member Function Documentation
accept()
Py::Object TaskPlacementPy::accept (const Py::Tuple & args)
Definition at line 1403 of file Gui/Placement.cpp.
References toolbit-attributes::args.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), init_type(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
bindObject()
Py::Object TaskPlacementPy::bindObject (const Py::Tuple & args)
Definition at line 1356 of file Gui/Placement.cpp.
References toolbit-attributes::args.
Referenced by init_type().
clicked()
Py::Object TaskPlacementPy::clicked (const Py::Tuple & args)
Definition at line 1431 of file Gui/Placement.cpp.
References toolbit-attributes::args.
Referenced by init_type().
getattr()
Py::Object TaskPlacementPy::getattr (const char * name) override
Definition at line 1292 of file Gui/Placement.cpp.
References Gui::PythonWrapper::fromQWidget(), and Gui::PythonWrapper::loadWidgetsModule().
getStandardButtons()
Py::Object TaskPlacementPy::getStandardButtons (const Py::Tuple & args)
Definition at line 1480 of file Gui/Placement.cpp.
References toolbit-attributes::args.
Referenced by init_type().
init_type()
void TaskPlacementPy::init_type () static
Definition at line 1227 of file Gui/Placement.cpp.
References accept(), bindObject(), clicked(), getStandardButtons(), isAllowedAlterDocument(), isAllowedAlterSelection(), isAllowedAlterView(), open(), reject(), setIgnoreTransactions(), setPlacement(), setPlacementAndBindObject(), setPropertyName(), setSelection(), and showDefaultButtons().
Referenced by Gui::Application::Application().
isAllowedAlterDocument()
Py::Object TaskPlacementPy::isAllowedAlterDocument (const Py::Tuple & args)
Definition at line 1456 of file Gui/Placement.cpp.
References toolbit-attributes::args.
Referenced by init_type().
isAllowedAlterSelection()
Py::Object TaskPlacementPy::isAllowedAlterSelection (const Py::Tuple & args)
Definition at line 1472 of file Gui/Placement.cpp.
References toolbit-attributes::args.
Referenced by init_type().
isAllowedAlterView()
Py::Object TaskPlacementPy::isAllowedAlterView (const Py::Tuple & args)
Definition at line 1464 of file Gui/Placement.cpp.
References toolbit-attributes::args.
Referenced by init_type().
open()
Py::Object TaskPlacementPy::open (const Py::Tuple & args)
Definition at line 1444 of file Gui/Placement.cpp.
References toolbit-attributes::args.
Referenced by init_type().
reject()
Py::Object TaskPlacementPy::reject (const Py::Tuple & args)
Definition at line 1417 of file Gui/Placement.cpp.
References toolbit-attributes::args.
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), init_type(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
repr()
Py::Object TaskPlacementPy::repr () override
Definition at line 1287 of file Gui/Placement.cpp.
References src.Mod.Test.testmakeWireString::String.
setattr()
int TaskPlacementPy::setattr (const char * name, const Py::Object & attr) override
Definition at line 1302 of file Gui/Placement.cpp.
setIgnoreTransactions()
Py::Object TaskPlacementPy::setIgnoreTransactions (const Py::Tuple & args)
Definition at line 1387 of file Gui/Placement.cpp.
References toolbit-attributes::args.
Referenced by init_type().
setPlacement()
Py::Object TaskPlacementPy::setPlacement (const Py::Tuple & args)
Definition at line 1325 of file Gui/Placement.cpp.
References toolbit-attributes::args.
Referenced by init_type().
setPlacementAndBindObject()
Py::Object TaskPlacementPy::setPlacementAndBindObject (const Py::Tuple & args)
Definition at line 1369 of file Gui/Placement.cpp.
References toolbit-attributes::args, and src.Mod.Test.testmakeWireString::String.
Referenced by init_type().
setPropertyName()
Py::Object TaskPlacementPy::setPropertyName (const Py::Tuple & args)
Definition at line 1312 of file Gui/Placement.cpp.
References toolbit-attributes::args.
Referenced by init_type().
setSelection()
Py::Object TaskPlacementPy::setSelection (const Py::Tuple & args)
Definition at line 1338 of file Gui/Placement.cpp.
References toolbit-attributes::args, and toolbit-attributes::doc.
Referenced by init_type().
showDefaultButtons()
Py::Object TaskPlacementPy::showDefaultButtons (const Py::Tuple & args)
Definition at line 1395 of file Gui/Placement.cpp.
References toolbit-attributes::args.
Referenced by init_type().
The documentation for this class was generated from the following files:
Gui/Placement.h
Gui/Placement.cpp