FreeCAD: TechDrawGui::TaskDlgHatch Class Reference
TechDrawGui::TaskDlgHatch Class Reference
#include <TaskHatch.h>
Public Member Functions
TaskDlgHatch (TechDraw::DrawViewPart *inDvp, std::vector< std::string > subs)
TaskDlgHatch (TechDrawGui::ViewProviderHatch *inVp)
~TaskDlgHatch () override
void open () override
is called the TaskView when the dialog is opened
void clicked (int) override
is called by the framework if an button is clicked which has no accept or reject role
bool accept () override
is called by the framework if the dialog is accepted (Ok)
bool reject () override
is called by the framework if the dialog is rejected (Cancel)
void helpRequested () override
is called by the framework if the user presses the help button
bool isAllowedAlterDocument () const override
void update ()
Public Member Functions inherited from Gui::TaskView::TaskDialog
TaskDialog ()
~TaskDialog () override
QWidget * addTaskBox (QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBox (const QPixmap &icon, QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBoxWithoutHeader (QWidget *widget)
void setButtonPosition (ButtonPosition p)
ButtonPosition buttonPosition () const
const std::vector< QWidget * > & getDialogContent () const
bool canClose () const
virtual QDialogButtonBox::StandardButtons getStandardButtons () const
tells the framework which buttons are wished for the dialog
virtual void modifyStandardButtons (QDialogButtonBox *)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
bool isEscapeButtonEnabled () const
void setAutoCloseOnTransactionChange (bool on)
bool isAutoCloseOnTransactionChange () const
void setAutoCloseOnDeletedDocument (bool on)
bool isAutoCloseOnDeletedDocument () const
const std::string & getDocumentName () const
void setDocumentName (const std::string &doc)
void setAutoCloseOnClosedView (bool on)
bool isAutoCloseOnClosedView () const
void associateToObject3dView (App::DocumentObject *obj)
const Gui::MDIView * getAssociatedView () const
void setAssociatedView (const Gui::MDIView *view)
virtual bool isAllowedAlterView () const
virtual bool isAllowedAlterSelection () const
virtual bool needsFullSpace () const
virtual void closed ()
is called by the framework when the dialog is closed
virtual void autoClosedOnTransactionChange ()
virtual void autoClosedOnDeletedDocument ()
virtual void autoClosedOnClosedView ()
void emitDestructionSignal ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from Gui::TaskView::TaskDialog
QPointer< QDialogButtonBox > buttonBox
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Detailed Description
Definition at line 100 of file TaskHatch.h.
Constructor & Destructor Documentation
TaskDlgHatch() [1/2]
TaskDlgHatch::TaskDlgHatch (TechDraw::DrawViewPart * inDvp, std::vector< std::string > subs)
Definition at line 283 of file TaskHatch.cpp.
References Gui::BitmapFactory(), Gui::TaskView::TaskDialog::Content, QSint::ActionGroup::groupLayout(), and importers.importIFCmulticore::subs.
TaskDlgHatch() [2/2]
TaskDlgHatch::TaskDlgHatch (TechDrawGui::ViewProviderHatch * inVp) explicit
Definition at line 293 of file TaskHatch.cpp.
References Gui::BitmapFactory(), Gui::TaskView::TaskDialog::Content, and QSint::ActionGroup::groupLayout().
~TaskDlgHatch()
TaskDlgHatch::~TaskDlgHatch () override
Definition at line 303 of file TaskHatch.cpp.
Member Function Documentation
accept()
bool TaskDlgHatch::accept () override virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 322 of file TaskHatch.cpp.
References TechDrawGui::TaskHatch::accept().
clicked()
void TaskDlgHatch::clicked (int i) override virtual
is called by the framework if an button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 317 of file TaskHatch.cpp.
References SplineSurface::i.
helpRequested()
void TechDrawGui::TaskDlgHatch::helpRequested () inline override virtual
is called by the framework if the user presses the help button
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 118 of file TaskHatch.h.
isAllowedAlterDocument()
bool TechDrawGui::TaskDlgHatch::isAllowedAlterDocument () const inline override virtual
Indicates whether this task dialog allows other commands to modify the document while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 119 of file TaskHatch.h.
open()
void TaskDlgHatch::open () override virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 313 of file TaskHatch.cpp.
reject()
bool TaskDlgHatch::reject () override virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 328 of file TaskHatch.cpp.
References TechDrawGui::TaskHatch::reject().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action().
update()
void TaskDlgHatch::update ()
Definition at line 307 of file TaskHatch.cpp.
The documentation for this class was generated from the following files:
TaskHatch.h
TaskHatch.cpp