FreeCAD: GCS::ConstraintP2LDistance Class Reference
GCS::ConstraintP2LDistance Class Reference
#include <Constraints.h>
Public Member Functions
ConstraintP2LDistance (Point &p, Line &l, double *d)
ConstraintType getTypeId () override
void rescale (double coef=1.) override
double error () override
double grad (double *) override
double maxStep (MAP_pD_D &dir, double lim=1.) override
double abs (double darea)
Public Member Functions inherited from GCS::Constraint
Constraint ()
virtual ~Constraint ()
VEC_pD params ()
void redirectParams (const MAP_pD_pD &redirectionmap)
void revertParams ()
void setTag (int tagId)
int getTag ()
void setDriving (bool isdriving)
bool isDriving () const
void setInternalAlignment (Alignment isinternalalignment)
Alignment isInternalAlignment () const
int findParamInPvec (double *param)
Additional Inherited Members
Public Types inherited from GCS::Constraint
enum Alignment { Alignment::NoInternalAlignment, Alignment::InternalAlignment }
Protected Attributes inherited from GCS::Constraint
VEC_pD origpvec
VEC_pD pvec
double scale
int tag
bool pvecChangedFlag
bool driving
Alignment internalAlignment
Detailed Description
Definition at line 463 of file Constraints.h.
Constructor & Destructor Documentation
ConstraintP2LDistance()
GCS::ConstraintP2LDistance::ConstraintP2LDistance (Point & p, Line & l, double * d)
Definition at line 880 of file Constraints.cpp.
References RobotExample::l, GCS::Constraint::origpvec, buildPsets::p, GCS::Constraint::pvec, and rescale().
Member Function Documentation
abs()
double GCS::ConstraintP2LDistance::abs (double darea)
error()
double GCS::ConstraintP2LDistance::error () override virtual
Reimplemented from GCS::Constraint.
Definition at line 903 of file Constraints.cpp.
References KDL::abs(), DraftVecUtils::dist(), and KDL::sqrt().
getTypeId()
ConstraintType GCS::ConstraintP2LDistance::getTypeId () override virtual
Reimplemented from GCS::Constraint.
Definition at line 893 of file Constraints.cpp.
References GCS::P2LDistance.
grad()
double GCS::ConstraintP2LDistance::grad (double * param) override virtual
Reimplemented from GCS::Constraint.
Definition at line 915 of file Constraints.cpp.
References Init::param, and KDL::sqrt().
maxStep()
double GCS::ConstraintP2LDistance::maxStep (MAP_pD_D & dir, double lim = 1.) override virtual
Reimplemented from GCS::Constraint.
Definition at line 957 of file Constraints.cpp.
References KDL::abs(), KDL::max(), KDL::min(), and KDL::sqrt().
rescale()
void GCS::ConstraintP2LDistance::rescale (double coef = 1.) override virtual
Reimplemented from GCS::Constraint.
Definition at line 898 of file Constraints.cpp.
Referenced by ConstraintP2LDistance().
The documentation for this class was generated from the following files:
Constraints.h
Constraints.cpp