FreeCAD: Gui::ExpressionCompleter Class Reference
Gui::ExpressionCompleter Class Reference
The ExpressionCompleter class extends the QCompleter class to provide a completer model of documentobject names and properties.
#include <ExpressionCompleter.h>
Public Slots
void slotUpdate (const QString &prefix, int pos)
Public Member Functions
ExpressionCompleter (const App::DocumentObject *currentDocObj, QObject *parent=nullptr, bool noProperty=false, bool checkInList=true)
Construct an ExpressionCompleter object.
void getPrefixRange (int &start, int &end) const
void updatePrefixEnd (int end)
void setDocumentObject (const App::DocumentObject *, bool checkInList=true)
void setNoProperty (bool enabled=true)
Detailed Description
The ExpressionCompleter class extends the QCompleter class to provide a completer model of documentobject names and properties.
Definition at line 48 of file ExpressionCompleter.h.
Constructor & Destructor Documentation
ExpressionCompleter()
ExpressionCompleter::ExpressionCompleter (const App::DocumentObject * currentDocObj, QObject * parent = nullptr, bool noProperty = false, bool checkInList = true)
Construct an ExpressionCompleter object.
Parameters
currentDoc Current document to generate the model from.
currentDocObj Current document object to generate model from.
parent Parent object owning the completer.
Definition at line 693 of file ExpressionCompleter.cpp.
Member Function Documentation
getPrefixRange()
void Gui::ExpressionCompleter::getPrefixRange (int & start, int & end) const inline
Definition at line 55 of file ExpressionCompleter.h.
Referenced by Gui::ExpressionLineEdit::slotCompleteText(), and Gui::ExpressionTextEdit::slotCompleteText().
setDocumentObject()
void ExpressionCompleter::setDocumentObject (const App::DocumentObject * obj, bool checkInList = true)
Definition at line 716 of file ExpressionCompleter.cpp.
References App::DocumentObject::isAttachedToDocument(), and test::m.
Referenced by Gui::ExpressionLineEdit::setDocumentObject(), and Gui::ExpressionTextEdit::setDocumentObject().
setNoProperty()
void ExpressionCompleter::setNoProperty (bool enabled = true)
Definition at line 732 of file ExpressionCompleter.cpp.
References test::m.
Referenced by Gui::ExpressionLineEdit::setNoProperty().
slotUpdate
void ExpressionCompleter::slotUpdate (const QString & prefix, int pos) slot
Definition at line 865 of file ExpressionCompleter.cpp.
References FC_TRACE, App::ExpressionTokenizer::perform(), and RobotExample::pos.
Referenced by Gui::ExpressionLineEdit::setDocumentObject(), and Gui::ExpressionTextEdit::setDocumentObject().
updatePrefixEnd()
void Gui::ExpressionCompleter::updatePrefixEnd (int end) inline
Definition at line 59 of file ExpressionCompleter.h.
Referenced by Gui::ExpressionLineEdit::slotCompleteText(), and Gui::ExpressionTextEdit::slotCompleteText().
The documentation for this class was generated from the following files:
ExpressionCompleter.h
ExpressionCompleter.cpp