FreeCAD: Base::FileException Class Reference
Base::FileException Class Reference
#include <Exception.h>
Public Member Functions
FileException (const char *sMessage, const char *sFileName=nullptr)
With massage and file name.
FileException (const char *sMessage, const FileInfo &File)
With massage and file name.
FileException ()
standard construction
FileException (const FileException &)=default
FileException (FileException &&)=default
~FileException () noexcept override=default
Destruction.
FileException & operator= (const FileException &)=default
Assignment operator.
FileException & operator= (FileException &&)=default
const char * what () const noexcept override
Description of the exception.
void ReportException () const override
Report generation.
std::string getFileName () const
Get file name for use with translatable message.
PyObject * getPyObject () override
returns a Python dictionary containing the exception data
void setPyObject (PyObject *pydict) override
returns sets the exception data from a Python dictionary
PyObject * getPyExceptionType () const override
returns the corresponding python exception type
Public Member Functions inherited from Base::Exception
Base::Type getTypeId (void) const override
~Exception () noexcept override=default
Exception & operator= (const Exception &inst)
Exception & operator= (Exception &&inst) noexcept
void setMessage (const char *sMessage)
void setMessage (const std::string &sMessage)
std::string getMessage () const
std::string getFile () const
int getLine () const
std::string getFunction () const
bool getTranslatable () const
bool getReported () const
void setDebugInformation (const std::string &file, int line, const std::string &function)
void setTranslatable (bool translatable)
void setReported (bool reported)
virtual void setPyException () const
Sets the Python error indicator and an error message.
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
void setFileName (const char *sFileName=nullptr)
Protected Member Functions inherited from Base::Exception
Exception (const char *sMessage)
Exception (std::string sMessage)
Exception ()
Exception (const Exception &inst)
Exception (Exception &&inst) noexcept
Protected Attributes
FileInfo file
std::string _sErrMsgAndFileName
Protected Attributes inherited from Base::Exception
std::string _sErrMsg
std::string _file
int _line
std::string _function
bool _isTranslatable
bool _isReported
Additional Inherited Members
Static Public Member Functions inherited from Base::Exception
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
File exception handling class This class is specialized to go with exception thrown in case of File IO Problems.
Author
Juergen Riegel
Definition at line 371 of file Exception.h.
Constructor & Destructor Documentation
FileException() [1/5]
FileException::FileException (const char * sMessage, const char * sFileName = nullptr) explicit
With massage and file name.
Definition at line 269 of file Exception.cpp.
References setFileName().
FileException() [2/5]
FileException::FileException (const char * sMessage, const FileInfo & File)
With massage and file name.
Definition at line 276 of file Exception.cpp.
References Base::FileInfo::filePath(), and setFileName().
FileException() [3/5]
FileException::FileException ()
standard construction
Definition at line 283 of file Exception.cpp.
FileException() [4/5]
Base::FileException::FileException (const FileException &) default
FileException() [5/5]
Base::FileException::FileException (FileException &&) default
~FileException()
Base::FileException::~FileException () override default noexcept
Destruction.
Member Function Documentation
getFileName()
std::string FileException::getFileName () const
Get file name for use with translatable message.
Definition at line 298 of file Exception.cpp.
References file, and Base::FileInfo::fileName().
getPyExceptionType()
PyObject * FileException::getPyExceptionType () const override virtual
returns the corresponding python exception type
Reimplemented from Base::Exception.
Definition at line 350 of file Exception.cpp.
getPyObject()
PyObject * FileException::getPyObject () override virtual
returns a Python dictionary containing the exception data
Reimplemented from Base::Exception.
Definition at line 331 of file Exception.cpp.
References file, Base::FileInfo::fileName(), Base::Exception::getPyObject(), Py::new_reference_to(), and src.Mod.Test.testmakeWireString::String.
operator=() [1/2]
FileException& Base::FileException::operator= (const FileException &) default
Assignment operator.
operator=() [2/2]
FileException& Base::FileException::operator= (FileException &&) default
ReportException()
void FileException::ReportException () const override virtual
Report generation.
Reimplemented from Base::Exception.
Definition at line 308 of file Exception.cpp.
References _FC_ERR, Base::Exception::_file, Base::Exception::_function, Base::Exception::_isReported, Base::Exception::_line, _sErrMsgAndFileName, and Path.Op.Surface::msg.
setFileName()
void FileException::setFileName (const char * sFileName = nullptr) protected
Definition at line 288 of file Exception.cpp.
References Base::Exception::_sErrMsg, _sErrMsgAndFileName, file, and Base::FileInfo::setFile().
Referenced by FileException(), and setPyObject().
setPyObject()
void FileException::setPyObject (PyObject * pydict) override virtual
returns sets the exception data from a Python dictionary
Reimplemented from Base::Exception.
Definition at line 338 of file Exception.cpp.
References setFileName(), Base::Exception::setPyObject(), and src.Mod.Test.testmakeWireString::String.
what()
const char * FileException::what () const override virtual noexcept
Description of the exception.
Reimplemented from Base::Exception.
Definition at line 303 of file Exception.cpp.
References _sErrMsgAndFileName.
Member Data Documentation
_sErrMsgAndFileName
std::string Base::FileException::_sErrMsgAndFileName protected
Definition at line 405 of file Exception.h.
Referenced by ReportException(), setFileName(), and what().
file
FileInfo Base::FileException::file protected
Definition at line 402 of file Exception.h.
Referenced by importers.exportIFCHelper.ContextCreator::createAutomaticProject(), importers.exportIFCHelper.ContextCreator::createCustomProject(), importers.exportIFCHelper.ContextCreator::createGeometricRepresentationContext(), importers.exportIFCHelper.ContextCreator::createGeometricRepresentationSubContext(), importers.exportIFCHelper.ContextCreator::createMapConversion(), importers.exportIFCHelper.ContextCreator::createTargetCRS(), importers.exportIFCHelper.ContextCreator::createTrueNorth(), getFileName(), getPyObject(), importers.importIFClegacy.IfcFile::read(), and setFileName().
The documentation for this class was generated from the following files:
Exception.h
Exception.cpp