FreeCAD: PartGui::ResultModel Class Reference
PartGui::ResultModel Class Reference
#include <TaskCheckGeometry.h>
Public Member Functions
ResultModel (QObject *parent=nullptr)
~ResultModel () override
QModelIndex index (int row, int column, const QModelIndex &parent) const override
QModelIndex parent (const QModelIndex &child) const override
int rowCount (const QModelIndex &parent) const override
int columnCount (const QModelIndex &parent) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
void setResults (ResultEntry *resultsIn)
ResultEntry * getEntry (const QModelIndex &index)
Detailed Description
Definition at line 81 of file TaskCheckGeometry.h.
Constructor & Destructor Documentation
ResultModel()
ResultModel::ResultModel (QObject * parent = nullptr) explicit
Definition at line 264 of file TaskCheckGeometry.cpp.
~ResultModel()
ResultModel::~ResultModel () override
Definition at line 269 of file TaskCheckGeometry.cpp.
Member Function Documentation
columnCount()
int ResultModel::columnCount (const QModelIndex & parent) const override
Definition at line 308 of file TaskCheckGeometry.cpp.
References parent().
data()
QVariant ResultModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 314 of file TaskCheckGeometry.cpp.
References PartGui::ResultEntry::error, index(), PartGui::ResultEntry::name, and PartGui::ResultEntry::type.
getEntry()
ResultEntry * ResultModel::getEntry (const QModelIndex & index)
Definition at line 358 of file TaskCheckGeometry.cpp.
References index().
headerData()
QVariant ResultModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const override
Definition at line 333 of file TaskCheckGeometry.cpp.
References Sketcher::Horizontal.
index()
QModelIndex ResultModel::index (int row, int column, const QModelIndex & parent) const override
Definition at line 275 of file TaskCheckGeometry.cpp.
References PartGui::ResultEntry::children, App::ExpressionParser::column, and parent().
Referenced by src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::addSegment(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::begin(), data(), getEntry(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::interval(), and src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::length().
parent()
QModelIndex ResultModel::parent (const QModelIndex & child) const override
Definition at line 285 of file TaskCheckGeometry.cpp.
References PartGui::ResultEntry::children, and PartGui::ResultEntry::parent.
Referenced by columnCount(), index(), and rowCount().
rowCount()
int ResultModel::rowCount (const QModelIndex & parent) const override
Definition at line 300 of file TaskCheckGeometry.cpp.
References PartGui::ResultEntry::children, and parent().
setResults()
void ResultModel::setResults (ResultEntry * resultsIn)
Definition at line 349 of file TaskCheckGeometry.cpp.
Referenced by PartGui::TaskCheckGeometryResults::goCheck().
The documentation for this class was generated from the following files:
TaskCheckGeometry.h
TaskCheckGeometry.cpp