FreeCAD: CommandCreateDims.cpp File Reference
CommandCreateDims.cpp File Reference
#include "PreCompiled.h"
#include <string>
#include <vector>
#include <QApplication>
#include <QMessageBox>
#include <QKeyEvent>
#include <QMouseEvent>
#include <QPoint>
#include <QPixmap>
#include <App/AutoTransaction.h>
#include <App/Document.h>
#include <App/DocumentObject.h>
#include <Base/Console.h>
#include <Base/Tools.h>
#include <Gui/Action.h>
#include <Gui/Application.h>
#include <Gui/BitmapFactory.h>
#include <Gui/Command.h>
#include <Gui/Control.h>
#include <Gui/Document.h>
#include <Gui/MainWindow.h>
#include <Gui/Selection.h>
#include <Gui/SelectionObject.h>
#include <Gui/View3DInventor.h>
#include <Gui/View3DInventorViewer.h>
#include <Mod/TechDraw/App/DrawDimHelper.h>
#include <Mod/TechDraw/App/DrawPage.h>
#include <Mod/TechDraw/App/DrawUtil.h>
#include <Mod/TechDraw/App/DrawViewDimension.h>
#include <Mod/TechDraw/App/DrawViewBalloon.h>
#include <Mod/TechDraw/App/DrawViewPart.h>
#include <Mod/TechDraw/App/Geometry.h>
#include <Mod/TechDraw/App/LandmarkDimension.h>
#include <Mod/TechDraw/App/Preferences.h>
#include "CommandExtensionDims.h"
#include "DimensionValidators.h"
#include "DrawGuiUtil.h"
#include "QGIViewDimension.h"
#include "QGVPage.h"
#include "MDIViewPage.h"
#include "TaskDimRepair.h"
#include "TaskLinkDim.h"
#include "TaskSelectLineAttributes.h"
#include "TechDrawHandler.h"
#include "ViewProviderDimension.h"
#include "ViewProviderDrawingView.h"
Classes
class GeomSelectionSizes
class TDHandlerDimension
class CmdTechDrawCompDimensionTools
Typedefs
using DimensionType = TechDraw::DrawViewDimension::DimensionType
Functions
bool _checkSelection (Gui::Command *cmd, unsigned maxObjs)
common checks of Selection for Dimension commands
bool _checkDrawViewPart (Gui::Command *cmd)
bool isDimCmdActive (Gui::Command *cmd)
void execDistance (Gui::Command *cmd)
void execDistanceX (Gui::Command *cmd)
void execDistanceY (Gui::Command *cmd)
void execAngle (Gui::Command *cmd)
void execAngle3Pt (Gui::Command *cmd)
void execRadius (Gui::Command *cmd)
void execDiameter (Gui::Command *cmd)
void execArea (Gui::Command *cmd)
void execDim (Gui::Command *cmd, std::string type, StringVector acceptableGeometry, std::vector< int > minimumCounts, std::vector< DimensionGeometryType > acceptableDimensionGeometrys)
void execExtent (Gui::Command *cmd, const std::string &dimType)
DrawViewDimension * dimensionMaker (TechDraw::DrawViewPart *dvp, std::string dimType, ReferenceVector references2d, ReferenceVector references3d)
DrawViewDimension * dimMaker (TechDraw::DrawViewPart *dvp, std::string dimType, ReferenceVector references2d, ReferenceVector references3d)
void positionDimText (DrawViewDimension *dim, int indexOffset=0)
void activateHandler (TechDrawHandler *newHandler)
void CreateTechDrawCommandsDims ()
Typedef Documentation
DimensionType
using DimensionType = TechDraw::DrawViewDimension::DimensionType
Definition at line 80 of file CommandCreateDims.cpp.
Function Documentation
_checkDrawViewPart()
bool _checkDrawViewPart (Gui::Command * cmd)
Definition at line 2574 of file CommandCreateDims.cpp.
References Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), and Path.Dressup.Utils::selection().
Referenced by execDim(), and execExtent().
_checkSelection()
bool _checkSelection (Gui::Command * cmd, unsigned maxObjs = 2)
common checks of Selection for Dimension commands
Definition at line 2545 of file CommandCreateDims.cpp.
References Base::Persistence::getClassTypeId(), Gui::Command::getDocument(), Gui::getMainWindow(), App::Document::getObjectsOfType(), Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), Path.Dressup.Utils::selection(), and Path.Log::warning().
Referenced by execCascadeHorizDimension(), execCascadeObliqueDimension(), execCascadeVertDimension(), execIncreaseDecreaseDecimal(), execPosHorizChainDimension(), execPosObliqueChainDimension(), execPosVertChainDimension(), and execRemovePrefixChar().
activateHandler()
void activateHandler (TechDrawHandler * newHandler)
Definition at line 117 of file CommandCreateDims.cpp.
References TechDrawGui::QGVPage::activateHandler(), Gui::MainWindow::activeWindow(), Gui::getMainWindow(), TechDrawGui::ViewProviderPage::getQGVPage(), and TechDrawGui::ViewProviderPageExtension::getViewProviderPage().
CreateTechDrawCommandsDims()
void CreateTechDrawCommandsDims ()
Definition at line 2356 of file CommandCreateDims.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
dimensionMaker()
DrawViewDimension * dimensionMaker (TechDraw::DrawViewPart * dvp, std::string dimType, ReferenceVector references2d, ReferenceVector references3d)
Definition at line 2469 of file CommandCreateDims.cpp.
References Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), dimMaker(), App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, Gui::Selection(), and App::DocumentObject::touch().
Referenced by execDim().
dimMaker()
DrawViewDimension * dimMaker (TechDraw::DrawViewPart * dvp, std::string dimType, ReferenceVector references2d, ReferenceVector references3d)
Definition at line 2488 of file CommandCreateDims.cpp.
References Gui::Command::Doc, doCommand, TechDraw::DrawView::findParentPage(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::Document::getObject(), App::Document::getUniqueObjectName(), App::DocumentObject::recomputeFeature(), TechDraw::DrawViewDimension::setReferences2d(), and TechDraw::DrawViewDimension::setReferences3d().
Referenced by TDHandlerDimension::create3pAngleDimension(), TDHandlerDimension::createAngleDimension(), TDHandlerDimension::createAreaDimension(), TDHandlerDimension::createChainDimension(), TDHandlerDimension::createCoordDimension(), TDHandlerDimension::createDistanceDimension(), TDHandlerDimension::createRadiusDiameterDimension(), and dimensionMaker().
execAngle()
void execAngle (Gui::Command * cmd)
Definition at line 1767 of file CommandCreateDims.cpp.
References execDim(), and TechDraw::isAngle.
execAngle3Pt()
void execAngle3Pt (Gui::Command * cmd)
Definition at line 1814 of file CommandCreateDims.cpp.
References execDim(), and TechDraw::isAngle3Pt.
execArea()
void execArea (Gui::Command * cmd)
Definition at line 1861 of file CommandCreateDims.cpp.
References execDim(), and TechDraw::isFace.
execDiameter()
void execDiameter (Gui::Command * cmd)
Definition at line 1576 of file CommandCreateDims.cpp.
References execDim(), TechDraw::isBSpline, TechDraw::isBSplineCircle, TechDraw::isCircle, and TechDraw::isEllipse.
execDim()
void execDim (Gui::Command * cmd, std::string type, StringVector acceptableGeometry, std::vector< int > minimumCounts, std::vector< DimensionGeometryType > acceptableDimensionGeometrys)
Definition at line 2382 of file CommandCreateDims.cpp.
References _checkDrawViewPart(), dimensionMaker(), Gui::getMainWindow(), TechDraw::getReferencesFromSelection(), TechDraw::isBSpline, TechDraw::isBSplineCircle, TechDraw::isEllipse, TechDraw::isInvalid, TechDraw::isViewReference, positionDimText(), result, Path.Post.scripts.grbl_post::type, TechDraw::validateDimSelection(), TechDraw::validateDimSelection3d(), and Path.Log::warning().
Referenced by execAngle(), execAngle3Pt(), execArea(), execDiameter(), execDistance(), execDistanceX(), execDistanceY(), and execRadius().
execDistance()
void execDistance (Gui::Command * cmd)
Definition at line 1624 of file CommandCreateDims.cpp.
References execDim(), TechDraw::isDiagonal, TechDraw::isHorizontal, TechDraw::isHybrid, and TechDraw::isVertical.
execDistanceX()
void execDistanceX (Gui::Command * cmd)
Definition at line 1672 of file CommandCreateDims.cpp.
References execDim(), TechDraw::isDiagonal, TechDraw::isHorizontal, and TechDraw::isHybrid.
execDistanceY()
void execDistanceY (Gui::Command * cmd)
Definition at line 1720 of file CommandCreateDims.cpp.
References execDim(), TechDraw::isDiagonal, TechDraw::isHybrid, and TechDraw::isVertical.
execExtent()
void execExtent (Gui::Command * cmd, const std::string & dimType)
Definition at line 2088 of file CommandCreateDims.cpp.
References _checkDrawViewPart(), Gui::getMainWindow(), TechDraw::getReferencesFromSelection(), TechDraw::isBSpline, TechDraw::isBSplineCircle, TechDraw::isCircle, TechDraw::isDiagonal, TechDraw::isEllipse, TechDraw::isHorizontal, TechDraw::isInvalid, TechDraw::isMultiEdge, TechDraw::isVertical, TechDraw::isViewReference, TechDraw::isZLimited, result, TechDraw::validateDimSelection(), TechDraw::validateDimSelection3d(), and Path.Log::warning().
execRadius()
void execRadius (Gui::Command * cmd)
Definition at line 1528 of file CommandCreateDims.cpp.
References execDim(), TechDraw::isBSpline, TechDraw::isBSplineCircle, TechDraw::isCircle, and TechDraw::isEllipse.
isDimCmdActive()
bool isDimCmdActive (Gui::Command * cmd)
Definition at line 90 of file CommandCreateDims.cpp.
References TechDrawTools.TDToolsUtil::havePage(), TechDrawTools.TDToolsUtil::haveView(), TechDrawGui::DrawGuiUtil::needPage(), and TechDrawGui::DrawGuiUtil::needView().
Referenced by CmdTechDrawCompDimensionTools::isActive().
positionDimText()
void positionDimText (DrawViewDimension * dim, int indexOffset = 0)
Definition at line 2531 of file CommandCreateDims.cpp.
References TechDraw::pointPair::first(), TechDraw::DrawViewDimension::getLinearPoints(), TechDraw::pointPair::second(), App::PropertyQuantity::setValue(), TechDraw::DrawView::X, and TechDraw::DrawView::Y.
Referenced by TDHandlerDimension::createChainDimension(), TDHandlerDimension::createCoordDimension(), and execDim().