FreeCAD: ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient_diffuse_specular Class Reference
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient_diffuse_specular Class Reference
Public Member Functions
def __init__ (self, inherited0__ambient_reflectance, inherited1__diffuse_reflectance, specular_reflectance, specular_exponent, specular_colour)
def specular_reflectance ()
def specular_exponent ()
def specular_colour ()
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient_diffuse
def __init__ (self, inherited0__ambient_reflectance, diffuse_reflectance)
def diffuse_reflectance ()
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient
def __init__ (self, ambient_reflectance)
def ambient_reflectance ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
specular_reflectance
specular_exponent
specular_colour
Public Attributes inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient_diffuse
diffuse_reflectance
Public Attributes inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient
ambient_reflectance
Detailed Description
Entity surface_style_reflectance_ambient_diffuse_specular definition.
:param specular_reflectance
:type specular_reflectance:REAL
:param specular_exponent
:type specular_exponent:REAL
:param specular_colour
:type specular_colour:colour
Definition at line 29454 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Constructor & Destructor Documentation
__init__()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient_diffuse_specular.__init__ (self, inherited0__ambient_reflectance, inherited1__diffuse_reflectance, specular_reflectance, specular_exponent, specular_colour)
Definition at line 29466 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Member Function Documentation
specular_colour()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient_diffuse_specular.specular_colour ()
Definition at line 29501 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient_diffuse_specular._specular_colour, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient_diffuse_specular.specular_colour.
specular_exponent()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient_diffuse_specular.specular_exponent ()
Definition at line 29487 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient_diffuse_specular._specular_exponent, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient_diffuse_specular.specular_exponent.
specular_reflectance()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient_diffuse_specular.specular_reflectance ()
Definition at line 29473 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient_diffuse_specular._specular_reflectance, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient_diffuse_specular.specular_reflectance.
Member Data Documentation
specular_colour
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient_diffuse_specular.specular_colour
Definition at line 29470 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient_diffuse_specular.specular_colour().
specular_exponent
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient_diffuse_specular.specular_exponent
Definition at line 29469 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient_diffuse_specular.specular_exponent().
specular_reflectance
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient_diffuse_specular.specular_reflectance
Definition at line 29468 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_reflectance_ambient_diffuse_specular.specular_reflectance().
The documentation for this class was generated from the following file:
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py