FreeCAD: App::Property Class Reference
App::Property Class Reference abstract
#include <Property.h>
Public Types
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Public Member Functions
Property ()
~Property () override
unsigned int getMemSize () const override
const char * getName () const
bool hasName () const
std::string getFullName () const
virtual const char * getEditorName () const
Get the class name of the associated property editor item.
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual void afterRestore ()
virtual void onContainerRestored ()
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
virtual Property * Copy () const =0
Returns a new copy of the property (mainly for Undo/Redo and transactions)
virtual void Paste (const Property &from)=0
Paste the value from the property (mainly for Undo/Redo and transactions)
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
int64_t getID () const
virtual void beforeSave () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void Save (Writer &) const =0
virtual void Restore (XMLReader &)=0
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions
virtual void hasSetValue ()
Gets called by all setValue() methods after the value has changed.
virtual void aboutToSetValue ()
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Protected Attributes
std::bitset< 32 > StatusBits
Friends
class PropertyContainer
struct PropertyData
class DynamicProperty
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Base class of all properties This is the father of all properties. Properties are objects which are used in the document tree to parametrize e.g. features and their graphical output. They are also used to gain access from the scripting facility. /par This abstract base class defines all methods shared by all possible properties. It is also possible to define user properties and use them in the framework...
Definition at line 56 of file Property.h.
Member Enumeration Documentation
Status
enum App::Property::Status
Enumerator
Touched
Immutable
ReadOnly
Hidden
Transient
MaterialEdit
NoMaterialListEdit
Output
LockDynamic
NoModify
PartialTrigger
NoRecompute
Single
Ordered
EvalOnRestore
Busy
CopyOnChange
UserEdit
PropStaticBegin
PropDynamic
PropNoPersist
PropNoRecompute
PropReadOnly
PropTransient
PropHidden
PropOutput
PropStaticEnd
User1
User2
User3
User4
Definition at line 61 of file Property.h.
Constructor & Destructor Documentation
Property() [1/2]
Property::Property ()
Definition at line 56 of file Property.cpp.
~Property()
Property::~Property () override default
Property() [2/2]
App::Property::Property (const Property &) delete
Member Function Documentation
aboutToSetChildValue()
virtual void App::Property::aboutToSetChildValue (Property &) inline virtual
Called before a child property changing value.
Reimplemented in App::PropertyXLinkSubList, and App::PropertyXLinkContainer.
Definition at line 270 of file Property.h.
Referenced by App::PropertyXLink::aboutToSetValue().
aboutToSetValue()
void Property::aboutToSetValue () protected virtual
Gets called by all setValue() methods before the value has changed.
Reimplemented in App::PropertyXLink, and App::PropertyFileIncluded.
Definition at line 283 of file Property.cpp.
References App::PropertyContainer::onBeforeChange().
Referenced by App::PropertyLinkBase::_updateElementReference(), App::PropertyXLinkSubList::aboutToSetChildValue(), App::PropertyFileIncluded::aboutToSetValue(), App::PropertyXLink::aboutToSetValue(), App::PropertyLinkSubList::addValue(), App::PropertyXLinkContainer::breakLink(), App::PropertyPythonObject::Paste(), Path::PropertyPath::Paste(), Points::PropertyPointKernel::Paste(), Mesh::PropertyNormalList::Paste(), Robot::PropertyTrajectory::Paste(), Fem::PropertyPostDataObject::Paste(), Fem::PropertyFemMesh::Paste(), Mesh::PropertyCurvatureList::Paste(), Part::PropertyShapeHistory::Paste(), Inspection::PropertyDistanceList::Paste(), Mesh::PropertyMaterial::Paste(), Part::PropertyFilletEdges::Paste(), Mesh::PropertyMeshKernel::Paste(), App::PropertyXLinkSubList::Paste(), App::PropertyPythonObject::Restore(), Part::PropertyPartShape::Restore(), Points::PropertyPointKernel::Restore(), Mesh::PropertyMeshKernel::Restore(), App::PropertyPythonObject::RestoreDocFile(), Path::PropertyPath::RestoreDocFile(), Fem::PropertyPostDataObject::RestoreDocFile(), Points::PropertyPointKernel::RestoreDocFile(), Fem::PropertyFemMesh::RestoreDocFile(), Mesh::PropertyMeshKernel::RestoreDocFile(), Fem::PropertyPostDataObject::scale(), Mesh::PropertyMaterial::setAmbientColor(), Mesh::PropertyMaterial::setBinding(), Mesh::PropertyMaterial::setDiffuseColor(), Mesh::PropertyMaterial::setEmissiveColor(), Mesh::PropertyMeshKernel::setPointIndices(), App::PropertyPythonObject::setPyObject(), Mesh::PropertyMaterial::setShininess(), Mesh::PropertyMaterial::setSpecularColor(), Mesh::PropertyMaterial::setTransparency(), App::PropertyPythonObject::setValue(), Materials::PropertyMaterial::setValue(), Part::PropertyPartShape::setValue(), Mesh::PropertyNormalList::setValue(), Points::PropertyPointKernel::setValue(), Path::PropertyPath::setValue(), Robot::PropertyTrajectory::setValue(), Fem::PropertyFemMesh::setValue(), Fem::PropertyPostDataObject::setValue(), Mesh::PropertyCurvatureList::setValue(), Part::PropertyShapeHistory::setValue(), Inspection::PropertyDistanceList::setValue(), Mesh::PropertyMaterial::setValue(), Part::PropertyFilletEdges::setValue(), Mesh::PropertyMeshKernel::setValue(), App::PropertyLink::setValue(), App::PropertyLinkSubList::setValue(), Fem::PropertyFemMesh::setValuePtr(), Mesh::PropertyMeshKernel::setValuePtr(), Mesh::PropertyNormalList::setValues(), Mesh::PropertyCurvatureList::setValues(), Part::PropertyShapeHistory::setValues(), Inspection::PropertyDistanceList::setValues(), Part::PropertyFilletEdges::setValues(), App::PropertyLinkSubList::setValues(), Points::PropertyPointKernel::startEditing(), Mesh::PropertyMeshKernel::startEditing(), Mesh::PropertyMeshKernel::swapMesh(), Part::PropertyPartShape::transformGeometry(), Fem::PropertyFemMesh::transformGeometry(), Mesh::PropertyNormalList::transformGeometry(), Points::PropertyPointKernel::transformGeometry(), Mesh::PropertyCurvatureList::transformGeometry(), and Mesh::PropertyMeshKernel::transformGeometry().
afterRestore()
virtual void App::Property::afterRestore () inline virtual
Called at the beginning of Document::afterRestore()
This function is called without dependency sorting, because some types of link property can only reconstructs the linking information inside this function.
One example use case of this function is PropertyLinkSub that uses afterRestore() to parse and restore subname references, which may contain sub-object reference from external document, and there will be special mapping required during object import.
Another example is PropertyExpressionEngine which only parse the restored expression in afterRestore(). The reason, in addition to subname mapping like PropertyLinkSub, is that it can handle document name adjustment as well. It internally relies on PropertyXLink to store the external document path for external linking. When the external document is restored, its internal name may change due to name conflict with existing documents. PropertyExpressionEngine can now auto adjust external references without any problem.
Reimplemented in App::PropertyXLinkContainer, App::PropertyXLinkSubList, App::PropertyXLink, App::PropertyLinkSubList, App::PropertyLinkSub, App::PropertyComplexGeoData, App::PropertyExpressionEngine, Part::PropertyPartShape, Part::PropertyTopoShapeList, and Spreadsheet::PropertySheet.
Definition at line 203 of file Property.h.
Referenced by Part::PropertyTopoShapeList::afterRestore(), and App::PropertyComplexGeoData::afterRestore().
beforeSave()
virtual void App::Property::beforeSave () const inline virtual
Reimplemented in Part::PropertyPartShape.
Definition at line 289 of file Property.h.
canonicalPath()
ObjectIdentifier Property::canonicalPath (const App::ObjectIdentifier & p) const virtual
Convert p to a canonical representation of it.
Reimplemented in App::PropertyExpressionEngine, and Sketcher::PropertyConstraintList.
Definition at line 182 of file Property.cpp.
References buildPsets::p.
Referenced by Gui::ExpressionBinding::bind().
Copy()
Property * Property::Copy () const pure virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implemented in Part::PropertyShapeCache, App::PropertyXLinkSubList, App::PropertyPersistentObject, App::PropertyXLink, App::PropertyMaterialList, App::PropertyMaterial, App::PropertyLinkSubList, App::PropertyColorList, App::PropertyColor, App::PropertyBoolList, App::PropertyLinkSub, App::PropertyBool, App::PropertyStringList, App::PropertyUUID, App::PropertyLinkList, App::PropertyString, App::PropertyFloatList, App::PropertyLink, App::PropertyFloat, App::PropertyMap, App::PropertyRotation, App::PropertyIntegerSet, App::PropertyPlacementList, App::PropertyPlacementLink, App::PropertyIntegerList, App::PropertyPlacement, Mesh::PropertyMeshKernel, App::PropertyMatrix, Part::PropertyFilletEdges, App::PropertyEnumeration, Points::PropertyCurvatureList, Mesh::PropertyMaterial, App::PropertyVectorList, Inspection::PropertyDistanceList, Part::PropertyShapeHistory, Mesh::PropertyCurvatureList, Points::PropertyNormalList, App::PropertyPath, Sketcher::PropertyConstraintList, App::PropertyExpressionEngine, Fem::PropertyFemMesh, Fem::PropertyPostDataObject, Part::PropertyPartShape, Robot::PropertyTrajectory, Mesh::PropertyNormalList, Points::PropertyGreyValueList, Points::PropertyPointKernel, Path::PropertyPath, App::PropertyFileIncluded, Spreadsheet::PropertyColumnWidths, Spreadsheet::PropertyRowHeights, App::PropertyVector, Spreadsheet::PropertySheet, Part::PropertyTopoShapeList, Part::PropertyGeometryList, Spreadsheet::PropertySpreadsheetQuantity, TechDraw::PropertyCosmeticVertexList, TechDraw::PropertyCosmeticEdgeList, App::PropertyInteger, TechDraw::PropertyGeomFormatList, Materials::PropertyMaterial, TechDraw::PropertyCenterLineList, App::PropertyPythonObject, and SketcherGui::PropertyVisualLayerList.
Definition at line 295 of file Property.cpp.
Referenced by App::TransactionObject::addOrRemoveProperty(), App::LinkBaseExtension::checkCopyOnChange(), PartGui::ViewProviderCustom::onChanged(), SketcherGui::ViewProviderCustom::onChanged(), and App::TransactionObject::setProperty().
destroy()
void Property::destroy (Property * p) static
For safe deleting of a dynamic property.
Definition at line 243 of file Property.cpp.
References App::PropertyCleaner::add(), and buildPsets::p.
Referenced by App::DynamicProperty::removeDynamicProperty().
getContainer()
PropertyContainer* App::Property::getContainer () const inline
Get a pointer to the PropertyContainer derived class the property belongs to.
Definition at line 160 of file Property.h.
Referenced by App::TransactionObject::addOrRemoveProperty(), App::PropertyLinkSubList::addValue(), Part::PropertyPartShape::beforeSave(), App::PropertyLink::breakLink(), App::PropertyLinkList::breakLink(), App::PropertyLinkSub::breakLink(), App::PropertyLinkSubList::breakLink(), App::PropertyXLinkSubList::breakLink(), App::PropertyXLinkContainer::breakLink(), App::PropertyExpressionEngine::canonicalPath(), App::PropertyXLinkContainer::clearDeps(), App::PropertyLinkSub::CopyOnImportExternal(), App::PropertyLinkSubList::CopyOnImportExternal(), App::PropertyXLink::CopyOnImportExternal(), App::PropertyLinkSub::CopyOnLabelChange(), App::PropertyLinkSubList::CopyOnLabelChange(), App::PropertyXLink::CopyOnLabelChange(), App::PropertyLink::CopyOnLinkReplace(), App::PropertyLinkList::CopyOnLinkReplace(), App::PropertyLinkSub::CopyOnLinkReplace(), App::PropertyLinkSubList::CopyOnLinkReplace(), App::PropertyXLink::CopyOnLinkReplace(), App::PropertyExpressionEngine::execute(), Spreadsheet::PropertySheet::getLinksTo(), Part::PropertyPartShape::getPaths(), getPaths(), Part::PropertyPartShape::getShape(), App::PropertyLinkBase::hasSetValue(), importExternalElements(), Spreadsheet::PropertySheet::insertColumns(), Spreadsheet::PropertySheet::insertRows(), App::LinkBaseExtension::isCopyOnChangeProperty(), App::GeoFeatureGroupExtension::isLinkValid(), App::ObjectIdentifier::ObjectIdentifier(), Part::Feature::onBeforeChange(), PartGui::PropertyEnumAttacherItem::openTask(), App::DocumentObjectT::operator=(), Spreadsheet::PropertySheet::Paste(), propertyName(), Spreadsheet::PropertySheet::removeColumns(), Spreadsheet::PropertySheet::removeRows(), App::PropertyLink::resetLink(), Part::PropertyPartShape::Restore(), App::PropertyLink::Restore(), App::PropertyLinkList::Restore(), App::PropertyLinkSub::Restore(), App::PropertyLinkSubList::Restore(), App::PropertyXLink::Restore(), Path::PropertyPath::RestoreDocFile(), Fem::PropertyPostDataObject::RestoreDocFile(), App::PropertyXLink::restoreLink(), Part::PropertyPartShape::Save(), App::PropertyLinkSub::Save(), App::PropertyLinkSubList::Save(), App::PropertyXLink::Save(), App::PropertyXLinkContainer::Save(), Fem::PropertyPostDataObject::SaveDocFile(), App::PropertyLinkList::set1Value(), Spreadsheet::Cell::setAlias(), App::PropertyXLink::setAllowPartial(), Spreadsheet::PropertySheet::setPathValue(), App::TransactionObject::setProperty(), App::LinkBaseExtension::setProperty(), Gui::PropertyEditor::PropertyItem::setPropertyData(), Part::PropertyPartShape::setPyObject(), App::PropertyLinkList::setSize(), Part::PropertyPartShape::setValue(), App::PropertyLink::setValue(), App::PropertyLinkSubList::setValue(), App::PropertyLinkList::setValues(), App::PropertyLinkSubList::setValues(), Gui::RecoveryWriter::shouldWrite(), App::PropertyXLinkContainer::updateDeps(), Spreadsheet::PropertySheet::updateElementReference(), App::PropertyLinkSubList::updateElementReference(), updateLinkReference(), App::PropertyLinkSubList::upgrade(), App::PropertyXLinkSub::upgrade(), App::PropertyXLinkSubList::upgrade(), App::PropertyLinkList::~PropertyLinkList(), App::PropertyLinkSub::~PropertyLinkSub(), and App::PropertyLinkSubList::~PropertyLinkSubList().
getDocumentation()
const char * Property::getDocumentation () const
Get the documentation of this property.
Definition at line 157 of file Property.cpp.
References App::PropertyContainer::getPropertyDocumentation().
Referenced by App::DynamicProperty::addProperty(), and Gui::PropertyEditor::PropertyItem::toolTip().
getEditorName()
virtual const char* App::Property::getEditorName () const inline virtual
Get the class name of the associated property editor item.
Reimplemented in App::PropertyXLinkSubList, App::PropertyXLinkSub, App::PropertyMaterialList, App::PropertyMaterial, App::PropertyLinkSubList, App::PropertyColor, App::PropertyLinkSub, App::PropertyBool, App::PropertyStringList, App::PropertyFont, App::PropertyLinkList, App::PropertyString, App::PropertyFloatList, App::PropertyLink, App::PropertyPrecision, App::PropertyFloatConstraint, App::PropertyFloat, App::PropertyRotation, App::PropertyIntegerList, App::PropertyPlacement, App::PropertyIntegerConstraint, Mesh::PropertyMeshKernel, App::PropertyMatrix, App::PropertyVectorList, Mesh::PropertyMaterial, App::PropertyEnumeration, App::PropertyDirection, App::PropertyAngle, App::PropertyPosition, App::PropertyVectorDistance, App::PropertyQuantityConstraint, App::PropertyPath, Fem::PropertyFemMesh, App::PropertyFileIncluded, App::PropertyVector, Materials::PropertyMaterial, App::PropertyInteger, Sketcher::PropertyConstraintList, App::PropertyQuantity, and App::PropertyFile.
Definition at line 142 of file Property.h.
Referenced by createPropertyItem().
getFileName()
std::string Property::getFileName (const char * postfix = 0, const char * prefix = 0) const protected
Return a file name suitable for saving this property.
Definition at line 95 of file Property.cpp.
References getFullName(), and RobotExample::pos.
Referenced by Part::PropertyPartShape::Restore(), and Part::PropertyPartShape::Save().
getFullName()
std::string Property::getFullName () const
Definition at line 77 of file Property.cpp.
References App::PropertyContainer::getFullName().
Referenced by App::Document::_checkTransaction(), App::PropertyXLinkContainer::_onBreakLink(), SpreadsheetGui::DlgSheetConf::accept(), App::PropertyExpressionEngine::execute(), getFileName(), Gui::ViewProviderDocumentObject::onChanged(), Spreadsheet::PropertySheet::pasteCells(), propertyName(), Part::PropertyPartShape::Restore(), Spreadsheet::PropertySheet::setPathValue(), Gui::Document::slotChangedObject(), and Gui::Document::slotChangePropertyEditor().
getGroup()
const char * Property::getGroup () const
Get the group of this property.
Definition at line 152 of file Property.cpp.
References App::PropertyContainer::getPropertyGroup().
Referenced by App::DynamicProperty::addProperty(), App::LinkBaseExtension::isCopyOnChangeProperty(), and Part::Primitive::onChanged().
getID()
int64_t App::Property::getID () const inline
Return a unique ID for the property
The ID of a property is generated from a monotonically increasing internal counter. The intention of the ID is to be used as a key for mapping, instead of using the raw pointer. Because, it is possible for the runtime memory allocator to reuse just deleted memory, which will cause hard to debug problem if use pointer as key.
Definition at line 284 of file Property.h.
Referenced by App::TransactionObject::addOrRemoveProperty(), and App::TransactionObject::setProperty().
getMemSize()
unsigned int App::Property::getMemSize () const inline override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence
See also
Base::Persistence
Implements Base::Persistence.
Reimplemented in TechDraw::PropertyCosmeticEdgeList, App::PropertyXLinkSubList, App::PropertyPersistentObject, App::PropertyMaterialList, App::PropertyLinkSubList, App::PropertyMaterial, App::PropertyColorList, App::PropertyColor, App::PropertyBoolList, App::PropertyLinkSub, App::PropertyBool, App::PropertyStringList, App::PropertyUUID, App::PropertyLinkList, App::PropertyString, App::PropertyFloatList, App::PropertyLink, App::PropertyFloat, App::PropertyMap, App::PropertyRotation, App::PropertyIntegerSet, App::PropertyPlacementList, App::PropertyIntegerList, App::PropertyPlacement, App::PropertyMatrix, Mesh::PropertyMeshKernel, Part::PropertyFilletEdges, Points::PropertyCurvatureList, Mesh::PropertyMaterial, App::PropertyVectorList, Inspection::PropertyDistanceList, Part::PropertyShapeHistory, Spreadsheet::PropertySheet, Mesh::PropertyCurvatureList, Points::PropertyNormalList, App::PropertyPath, Sketcher::PropertyConstraintList, Fem::PropertyFemMesh, Fem::PropertyPostDataObject, Part::PropertyPartShape, App::PropertyExpressionEngine, Robot::PropertyTrajectory, Mesh::PropertyNormalList, Points::PropertyGreyValueList, Points::PropertyPointKernel, Path::PropertyPath, App::PropertyFileIncluded, App::PropertyVector, Part::PropertyTopoShapeList, Part::PropertyGeometryList, TechDraw::PropertyCosmeticVertexList, App::PropertyInteger, TechDraw::PropertyGeomFormatList, Materials::PropertyMaterial, TechDraw::PropertyCenterLineList, App::PropertyPythonObject, and SketcherGui::PropertyVisualLayerList.
Definition at line 118 of file Property.h.
Referenced by App::PropertyFileIncluded::getMemSize(), and isSame().
getName()
const char * Property::getName () const
Get the name of this property in the belonging container With hasName() it can be checked beforehand if a valid name is set.
Note
If no name is set this function returns an empty string, i.e. "".
Definition at line 62 of file Property.cpp.
Referenced by App::DynamicProperty::addProperty(), Gui::PropertyEditor::PropertyModel::appendProperty(), PartDesignGui::TaskHoleParameters::changedObject(), PartDesign::SubShapeBinder::checkCopyOnChange(), App::LinkBaseExtension::checkCopyOnChange(), PartGui::ViewProviderSplineExtension::extensionUpdateData(), Part::PropertyPartShape::getPaths(), getPaths(), TechDraw::DrawView::handleChangedPropertyType(), importExternalElements(), Spreadsheet::PropertySheet::isBindingPath(), App::ObjectIdentifier::ObjectIdentifier(), PartGui::ViewProviderCustom::onChanged(), SketcherGui::ViewProviderCustom::onChanged(), PartDesign::Boolean::onChanged(), Gui::ViewProviderGeometryObject::onChanged(), MeasureGui::ViewProviderMeasureBase::onSubjectVisibilityChanged(), Gui::PropertyView::onTimer(), App::DocumentObjectT::operator=(), App::PropertyContainer::Restore(), Mesh::PropertyNormalList::Save(), Mesh::PropertyCurvatureList::Save(), Inspection::PropertyDistanceList::Save(), Mesh::PropertyMaterial::Save(), Part::PropertyFilletEdges::Save(), App::LinkBaseExtension::setProperty(), App::LinkBaseExtension::setupCopyOnChange(), Spreadsheet::SheetObserver::slotChangedObject(), Gui::Document::slotChangedObject(), PartDesignGui::ViewProviderBody::unifyVisualProperty(), PartDesignGui::ViewProviderDatumLine::updateData(), Gui::ViewProviderVRMLObject::updateData(), PartDesignGui::ViewProviderDatumCoordinateSystem::updateData(), Gui::ViewProviderAnnotation::updateData(), Gui::ViewProviderGeometryObject::updateData(), InspectionGui::ViewProviderInspection::updateData(), PartDesignGui::ViewProvider::updateData(), Gui::ViewProviderDragger::updateData(), PartDesignGui::ViewProviderDatumPlane::updateData(), Gui::ViewProviderInventorObject::updateData(), MeasureGui::ViewProviderMeasureBase::updateData(), PartGui::ViewProviderPartExt::updateData(), Gui::ViewProviderAnnotationLabel::updateData(), App::PropertyXLink::upgrade(), App::PropertyXLinkSub::upgrade(), App::PropertyXLinkSubList::upgrade(), and App::ObjectIdentifier::verify().
getPaths()
void Property::getPaths (std::vector< App::ObjectIdentifier > & paths) const virtual
Get valid paths for this property; used by auto completer.
Reimplemented in App::PropertyRotation, App::PropertyPlacement, App::PropertyVector, Sketcher::PropertyConstraintList, Fem::PropertyPostDataObject, and Part::PropertyPartShape.
Definition at line 177 of file Property.cpp.
References getContainer(), and getName().
Referenced by ExpressionCompleterModel::retrieveSubPaths(), and Gui::PropertyEditor::PropertyItem::setPropertyData().
getPathValue()
const boost::any Property::getPathValue (const App::ObjectIdentifier & path) const virtual
Get value of property.
Reimplemented in App::PropertyRotation, App::PropertyPlacement, App::PropertyVector, App::PropertyBool, App::PropertyString, App::PropertyFloat, Spreadsheet::PropertySheet, Sketcher::PropertyConstraintList, App::PropertyExpressionEngine, App::PropertyQuantity, App::PropertyEnumeration, and App::PropertyInteger.
Definition at line 172 of file Property.cpp.
Referenced by App::PropertyExpressionEngine::execute(), App::PropertyVector::getPathValue(), App::PropertyPlacement::getPathValue(), App::PropertyRotation::getPathValue(), and App::ObjectIdentifier::getValue().
getPyPathValue()
virtual bool App::Property::getPyPathValue (const App::ObjectIdentifier & , Py::Object &) const inline virtual
Get Python value of property.
Reimplemented in App::PropertyRotation, App::PropertyPlacement, App::PropertyVector, App::PropertyEnumeration, and Sketcher::PropertyConstraintList.
Definition at line 172 of file Property.h.
Referenced by App::ObjectIdentifier::getPyValue().
getStatus()
unsigned long App::Property::getStatus () const inline
return the status bits
Definition at line 232 of file Property.h.
Referenced by App::TransactionObject::addOrRemoveProperty(), App::TransactionObject::setProperty(), and App::LinkBaseExtension::setupCopyOnChange().
getType()
short Property::getType () const
Get the type of the property in the container.
Definition at line 120 of file Property.cpp.
References GET_PTYPE, Hidden, NoRecompute, Output, ReadOnly, Transient, and Path.Post.scripts.grbl_post::type.
Referenced by App::DynamicProperty::addProperty(), App::PropertyExpressionEngine::execute(), App::DynamicProperty::getPropertyType(), App::PropertyContainer::getPropertyType(), Gui::PropertyView::isPropertyHidden(), Gui::LinkView::onLinkedUpdateData(), and App::LinkBaseExtension::update().
hasName()
bool Property::hasName () const
Check if the property has a name set. If no name is set then getName() will return an empty string
Definition at line 67 of file Property.cpp.
References isValidName().
Referenced by App::DynamicProperty::addProperty(), App::ObjectIdentifier::ObjectIdentifier(), App::DocumentObjectT::operator=(), and propertyName().
hasSetChildValue()
virtual void App::Property::hasSetChildValue (Property &) inline virtual
Called when a child property has changed value.
Reimplemented in App::PropertyXLinkSubList, and Spreadsheet::PropertySheet.
Definition at line 267 of file Property.h.
Referenced by App::PropertyXLink::hasSetValue().
hasSetValue()
void Property::hasSetValue () protected virtual
Gets called by all setValue() methods after the value has changed.
Reimplemented in App::PropertyXLink, App::PropertyLinkBase, Spreadsheet::PropertySheet, and App::PropertyExpressionEngine.
Definition at line 270 of file Property.cpp.
References Busy, App::PropertyContainer::onChanged(), signalChanged, StatusBits, testStatus(), and Touched.
Referenced by Points::PropertyPointKernel::finishEditing(), Mesh::PropertyMeshKernel::finishEditing(), App::PropertyLinkBase::hasSetValue(), App::PropertyPythonObject::Paste(), Path::PropertyPath::Paste(), Points::PropertyPointKernel::Paste(), Mesh::PropertyNormalList::Paste(), Robot::PropertyTrajectory::Paste(), Fem::PropertyPostDataObject::Paste(), Fem::PropertyFemMesh::Paste(), Mesh::PropertyCurvatureList::Paste(), Part::PropertyShapeHistory::Paste(), Inspection::PropertyDistanceList::Paste(), Mesh::PropertyMaterial::Paste(), Part::PropertyFilletEdges::Paste(), Mesh::PropertyMeshKernel::Paste(), App::PropertyPythonObject::Restore(), Part::PropertyPartShape::Restore(), Points::PropertyPointKernel::Restore(), Mesh::PropertyMeshKernel::Restore(), App::PropertyPythonObject::RestoreDocFile(), Path::PropertyPath::RestoreDocFile(), Fem::PropertyPostDataObject::RestoreDocFile(), Points::PropertyPointKernel::RestoreDocFile(), Fem::PropertyFemMesh::RestoreDocFile(), Mesh::PropertyMeshKernel::RestoreDocFile(), Fem::PropertyPostDataObject::scale(), Mesh::PropertyMaterial::setAmbientColor(), Mesh::PropertyMaterial::setBinding(), Mesh::PropertyMaterial::setDiffuseColor(), Mesh::PropertyMaterial::setEmissiveColor(), Mesh::PropertyMeshKernel::setPointIndices(), App::PropertyPythonObject::setPyObject(), Mesh::PropertyMaterial::setShininess(), Mesh::PropertyMaterial::setSpecularColor(), Mesh::PropertyMaterial::setTransparency(), App::PropertyPythonObject::setValue(), Materials::PropertyMaterial::setValue(), Part::PropertyPartShape::setValue(), Mesh::PropertyNormalList::setValue(), Points::PropertyPointKernel::setValue(), Path::PropertyPath::setValue(), Robot::PropertyTrajectory::setValue(), Fem::PropertyFemMesh::setValue(), Fem::PropertyPostDataObject::setValue(), Mesh::PropertyCurvatureList::setValue(), Part::PropertyShapeHistory::setValue(), Inspection::PropertyDistanceList::setValue(), Mesh::PropertyMaterial::setValue(), Part::PropertyFilletEdges::setValue(), Mesh::PropertyMeshKernel::setValue(), Fem::PropertyFemMesh::setValuePtr(), Mesh::PropertyMeshKernel::setValuePtr(), Mesh::PropertyNormalList::setValues(), Mesh::PropertyCurvatureList::setValues(), Part::PropertyShapeHistory::setValues(), Inspection::PropertyDistanceList::setValues(), Part::PropertyFilletEdges::setValues(), Mesh::PropertyMeshKernel::swapMesh(), Part::PropertyPartShape::transformGeometry(), Fem::PropertyFemMesh::transformGeometry(), Mesh::PropertyNormalList::transformGeometry(), Points::PropertyPointKernel::transformGeometry(), Mesh::PropertyCurvatureList::transformGeometry(), and Mesh::PropertyMeshKernel::transformGeometry().
isReadOnly()
bool App::Property::isReadOnly () const inline
Definition at line 244 of file Property.h.
References ReadOnly.
Referenced by Gui::ExpressionBinding::apply(), Gui::ExpressionBinding::assignToProperty(), and PartDesignGui::TaskHoleParameters::changedObject().
isSame()
bool Property::isSame (const Property & other) const virtual
Compare if this property has the same content as the given one.
Reimplemented in App::PropertyMaterial, App::PropertyColor, App::PropertyBool, App::PropertyFont, App::PropertyUUID, App::PropertyString, App::PropertyListsT< T, ListT, ParentT >, App::PropertyListsT< long >, App::PropertyListsT< Base::Vector3d >, App::PropertyListsT< double >, App::PropertyListsT< Color >, App::PropertyListsT< std::string >, App::PropertyListsT< bool, boost::dynamic_bitset<> >, App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >, App::PropertyListsT< Material >, App::PropertyListsT< Base::Placement >, App::PropertyListsT< VisualLayer >, App::PropertyFloat, App::PropertyMap, App::PropertyIntegerSet, App::PropertyPlacement, App::PropertyLinkBase, App::PropertyMatrix, App::PropertyEnumeration, App::PropertyPath, App::PropertyVector, App::PropertyFileIncluded, App::PropertyInteger, and App::PropertyQuantity.
Definition at line 342 of file Property.cpp.
References getMemSize(), Base::StringWriter::getString(), Base::Persistence::getTypeId(), and Base::Persistence::Save().
isSinglePrecision()
bool App::Property::isSinglePrecision () const inline
Gets precision of properties using floating point numbers.
Definition at line 255 of file Property.h.
References Single.
isTouched()
bool App::Property::isTouched () const inline
Test if this property is touched.
Definition at line 222 of file Property.h.
Referenced by Part::PrismExtension::extensionMustExecute(), SketcherGui::ViewProviderSketch::finishRestoring(), App::RangeExpression::isTouched(), Part::Boolean::mustExecute(), PartDesign::Body::mustExecute(), PartDesign::FeatureExtrude::mustExecute(), TechDraw::DrawViewMulti::mustExecute(), TechDraw::DrawViewBalloon::mustExecute(), PartDesign::ProfileBased::mustExecute(), TechDraw::DrawViewDetail::mustExecute(), Surface::Filling::mustExecute(), PartDesign::LinearPattern::mustExecute(), TechDraw::DrawViewSymbol::mustExecute(), TechDraw::DrawLeaderLine::mustExecute(), PartDesign::PolarPattern::mustExecute(), Part::MultiCommon::mustExecute(), Part::MultiFuse::mustExecute(), PartDesign::Mirrored::mustExecute(), PartDesign::MultiTransform::mustExecute(), Part::CurveNet::mustExecute(), Part::ImportBrep::mustExecute(), Part::Compound::mustExecute(), Part::ImportIges::mustExecute(), Surface::Cut::mustExecute(), Part::Face::mustExecute(), PartDesign::Scaled::mustExecute(), PartDesign::Loft::mustExecute(), Part::Section::mustExecute(), PartDesign::Hole::mustExecute(), Part::ImportStep::mustExecute(), PartDesign::Fillet::mustExecute(), Part::Box::mustExecute(), Sketcher::SketchObjectSF::mustExecute(), TechDraw::DrawRichAnno::mustExecute(), PartDesign::Helix::mustExecute(), Part::Circle::mustExecute(), Part::Polygon::mustExecute(), Part::RuledSurface::mustExecute(), Part::Mirroring::mustExecute(), Surface::Sewing::mustExecute(), PartDesign::Thickness::mustExecute(), TechDraw::DrawView::mustExecute(), Part::Vertex::mustExecute(), TechDraw::DrawViewCollection::mustExecute(), PartDesign::FeatureAddSub::mustExecute(), PartDesign::Chamfer::mustExecute(), PartDesign::Pipe::mustExecute(), Mesh::Curvature::mustExecute(), Part::Offset::mustExecute(), Surface::Extend::mustExecute(), Part::Revolution::mustExecute(), Surface::GeomFillSurface::mustExecute(), TechDraw::DrawViewSpreadsheet::mustExecute(), Sandbox::SandboxObject::mustExecute(), Mesh::FixDefects::mustExecute(), Surface::FeatureBlendCurve::mustExecute(), Part::Offset2D::mustExecute(), PartDesign::Boolean::mustExecute(), TechDraw::DrawViewClip::mustExecute(), TechDraw::DrawBrokenView::mustExecute(), Part::Extrusion::mustExecute(), PartDesign::Revolution::mustExecute(), PartDesign::Groove::mustExecute(), TechDraw::DrawProjGroup::mustExecute(), PartDesign::Box::mustExecute(), Part::Loft::mustExecute(), TechDraw::DrawPage::mustExecute(), PartDesign::ShapeBinder::mustExecute(), Part::Scale::mustExecute(), TechDraw::DrawViewDraft::mustExecute(), TechDraw::DrawViewArch::mustExecute(), TechDraw::DrawViewAnnotation::mustExecute(), TechDraw::DrawViewPart::mustExecute(), Part::Line::mustExecute(), TechDraw::DrawViewSection::mustExecute(), PartDesign::Transformed::mustExecute(), Part::Sweep::mustExecute(), PartDesign::Cylinder::mustExecute(), Part::Plane::mustExecute(), Part::Sphere::mustExecute(), Part::Thickness::mustExecute(), PartDesign::Sphere::mustExecute(), Part::Ellipsoid::mustExecute(), App::LocalCoordinateSystem::mustExecute(), Part::Cylinder::mustExecute(), Part::FilletBase::mustExecute(), PartDesign::Cone::mustExecute(), Part::Prism::mustExecute(), PartDesign::Ellipsoid::mustExecute(), Inspection::Feature::mustExecute(), Part::RegularPolygon::mustExecute(), Part::Cone::mustExecute(), PartDesign::Torus::mustExecute(), Part::Torus::mustExecute(), PartDesign::Prism::mustExecute(), Part::Helix::mustExecute(), Part::Spiral::mustExecute(), PartDesign::Wedge::mustExecute(), Part::Wedge::mustExecute(), Part::Ellipse::mustExecute(), PartDesign::FeatureAddSub::onlyHasToRefine(), and TechDrawGui::QGSPage::updateTemplate().
isValidName()
bool Property::isValidName (const char * name) static
Check if the passed name is valid. If name is null or an empty string it's considered invalid, and valid otherwise.
Definition at line 72 of file Property.cpp.
Referenced by hasName(), and App::LinkBaseExtension::setProperty().
onContainerRestored()
virtual void App::Property::onContainerRestored () inline virtual
Called before calling DocumentObject::onDocumentRestored()
This function is called after finished calling Property::afterRestore() of all properties of objects. By then, the object dependency information is assumed ready. So, unlike Property::afterRestore(), this function is called on objects with dependency order.
Reimplemented in App::PropertyXLinkSubList, App::PropertyXLink, App::PropertyLinkSubList, App::PropertyLinkSub, App::PropertyExpressionEngine, and Spreadsheet::PropertySheet.
Definition at line 213 of file Property.h.
operator=()
Property& App::Property::operator= (const Property &) delete
Paste()
void Property::Paste (const Property & from) pure virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implemented in App::PropertyXLinkSubList, App::PropertyPersistentObject, App::PropertyXLink, App::PropertyMaterialList, App::PropertyMaterial, App::PropertyLinkSubList, App::PropertyColorList, App::PropertyColor, App::PropertyBoolList, App::PropertyLinkSub, App::PropertyBool, App::PropertyStringList, App::PropertyUUID, App::PropertyLinkList, App::PropertyString, App::PropertyFloatList, App::PropertyLink, App::PropertyFloat, App::PropertyMap, App::PropertyRotation, App::PropertyIntegerSet, App::PropertyPlacementList, App::PropertyPlacementLink, App::PropertyIntegerList, App::PropertyPlacement, App::PropertyMatrix, App::PropertyEnumeration, App::PropertyVectorList, App::PropertyPath, App::PropertyExpressionEngine, App::PropertyFileIncluded, App::PropertyVector, App::PropertyInteger, App::PropertyPythonObject, Mesh::PropertyMeshKernel, Points::PropertyCurvatureList, Mesh::PropertyCurvatureList, Points::PropertyNormalList, Sketcher::PropertyConstraintList, Fem::PropertyFemMesh, Fem::PropertyPostDataObject, Part::PropertyPartShape, Robot::PropertyTrajectory, Mesh::PropertyNormalList, Points::PropertyGreyValueList, Points::PropertyPointKernel, Path::PropertyPath, Spreadsheet::PropertyRowHeights, Part::PropertyTopoShapeList, Part::PropertyGeometryList, TechDraw::PropertyCosmeticVertexList, TechDraw::PropertyCosmeticEdgeList, TechDraw::PropertyGeomFormatList, TechDraw::PropertyCenterLineList, and Part::PropertyShapeCache.
Definition at line 302 of file Property.cpp.
Referenced by PartDesignGui::TaskFeaturePick::makeCopy(), PartGui::ViewProviderCustom::onChanged(), and SketcherGui::ViewProviderCustom::onChanged().
purgeTouched()
void App::Property::purgeTouched () inline
Reset this property touched.
Definition at line 227 of file Property.h.
Referenced by TechDraw::DrawProjGroup::addProjection(), TechDraw::DrawView::checkScale(), TechDraw::DrawViewDetail::execute(), TechDraw::DrawProjGroupItem::execute(), TechDraw::DrawViewSection::execute(), TechDraw::DrawViewPart::execute(), TechDraw::DrawViewBalloon::handleXYLock(), TechDraw::DrawView::handleXYLock(), TechDraw::DrawView::onChanged(), TechDraw::DrawViewDetail::postHlrTasks(), TechDraw::DrawViewSection::postHlrTasks(), TechDraw::DrawViewPart::postHlrTasks(), and TechDrawGui::TaskProjGroup::turnViewToProjGroup().
setContainer()
void Property::setContainer (PropertyContainer * Father)
Is called by the framework to set the father (container)
Definition at line 162 of file Property.cpp.
Referenced by App::LinkBaseExtension::_handleChangedPropertyName(), App::DynamicProperty::addDynamicProperty(), Part::AttachExtension::extensionHandleChangedPropertyName(), TechDraw::DrawView::handleChangedPropertyType(), TechDraw::DrawPage::handleChangedPropertyType(), App::PropertyLinkSubList::upgrade(), App::PropertyXLinkSub::upgrade(), App::PropertyXLinkSubList::upgrade(), and Gui::ViewProviderDocumentObject::~ViewProviderDocumentObject().
setPathValue()
void Property::setPathValue (const App::ObjectIdentifier & path, const boost::any & value) virtual
Set value of property.
Reimplemented in App::PropertyRotation, App::PropertyPlacement, App::PropertyBool, App::PropertyString, App::PropertyFloat, App::PropertyEnumeration, Spreadsheet::PropertySheet, Sketcher::PropertyConstraintList, App::PropertyInteger, and App::PropertyQuantity.
Definition at line 167 of file Property.cpp.
Referenced by App::PropertyExpressionEngine::execute(), App::PropertyPlacement::setPathValue(), and App::PropertyRotation::setPathValue().
setReadOnly()
void Property::setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
Definition at line 265 of file Property.cpp.
References ReadOnly, and setStatus().
Referenced by PartDesign::FeatureExtrude::computeDirection(), Part::Helix::Helix(), PartDesign::Hole::Hole(), Part::Revolution::onChanged(), PartDesign::Hole::onChanged(), PartDesign::FeatureExtrude::updateProperties(), PartDesign::Groove::updateProperties(), and PartDesign::Revolution::updateProperties().
setSinglePrecision()
void App::Property::setSinglePrecision (bool single) inline
Sets precision of properties using floating point numbers to single, the default is double.
Definition at line 250 of file Property.h.
References Single.
setStatus()
void Property::setStatus (Status pos, bool on)
Definition at line 335 of file Property.cpp.
References RobotExample::pos, setStatusValue(), and StatusBits.
Referenced by SpreadsheetGui::DlgSheetConf::accept(), TechDraw::DrawProjGroup::addProjection(), MeshGui::ViewProviderMesh::attach(), TechDraw::DrawViewAnnotation::DrawViewAnnotation(), TechDraw::DrawViewBalloon::DrawViewBalloon(), PartDesign::Transformed::execute(), Part::Circle::handleChangedPropertyName(), Part::Ellipse::handleChangedPropertyName(), TechDraw::DrawViewBalloon::handleXYLock(), TechDraw::DrawView::handleXYLock(), Gui::ViewProviderDocumentObject::hide(), Part::AttachExtension::initBase(), Part::Box::onChanged(), Part::Mirroring::onChanged(), TechDraw::DrawViewSection::onChanged(), TechDraw::DrawView::onChanged(), PartDesign::ProfileBased::onChanged(), Gui::ViewProviderDocumentObject::onChanged(), SketcherGui::ViewProviderSketch::onChanged(), PartDesign::Body::onDocumentRestored(), Part::FilletBase::onUpdateElementReference(), Part::Box::Restore(), Gui::ViewProviderLink::setElementColors(), App::LinkBaseExtension::setProperty(), setReadOnly(), TechDraw::DrawView::setScaleAttribute(), Gui::ViewProviderDocumentObject::show(), SketcherGui::ViewProviderSketch::startRestoring(), PartDesign::Transformed::Transformed(), TechDrawGui::TaskProjGroup::turnProjGroupToView(), App::LinkBaseExtension::update(), MeshGui::ViewProviderMesh::updateData(), Gui::ViewProviderLink::updateDataPrivate(), PartDesign::Chamfer::updateProperties(), PartDesignGui::ViewProviderDatum::ViewProviderDatum(), and Gui::ViewProviderTextDocument::ViewProviderTextDocument().
setStatusValue()
void Property::setStatusValue (unsigned long status)
Definition at line 308 of file Property.cpp.
References Busy, Hidden, App::PropertyContainer::onPropertyStatusChanged(), PropDynamic, PropHidden, PropNoPersist, PropNoRecompute, PropOutput, PropReadOnly, PropTransient, ReadOnly, and StatusBits.
Referenced by App::TransactionObject::applyChn(), Part::Box::Restore(), App::PropertyContainer::Restore(), and setStatus().
testStatus()
bool App::Property::testStatus (Status pos) const inline
Definition at line 236 of file Property.h.
References RobotExample::pos.
Referenced by App::Document::_checkTransaction(), Gui::PropertyEditor::PropertyModel::appendProperty(), PartDesign::SubShapeBinder::collapseGeoChildren(), App::PropertyExpressionEngine::execute(), App::GeoFeatureGroupExtension::extensionOnChanged(), App::GroupExtension::extensionOnChanged(), App::LinkBaseExtension::extensionOnChanged(), Materials::PropertyMaterial::getEditorName(), TechDraw::DrawViewBalloon::handleXYLock(), TechDraw::DrawView::handleXYLock(), hasSetValue(), Gui::ViewProviderDocumentObject::hide(), App::LinkBaseExtension::isCopyOnChangeProperty(), Gui::PropertyView::isPropertyHidden(), Part::Box::onChanged(), PartDesign::LinearPattern::onChanged(), PartDesign::SubShapeBinder::onChanged(), Gui::ViewProviderDocumentObject::onChanged(), Part::FilletBase::onChanged(), Sketcher::SketchObject::onChanged(), Gui::LinkView::onLinkedUpdateData(), Gui::PropertyView::onTimer(), Gui::ViewProviderDocumentObject::removeDynamicProperty(), Part::Circle::Restore(), Part::Ellipse::Restore(), Gui::ViewProviderDocumentObject::show(), Gui::Document::slotChangedObject(), App::LinkBaseExtension::update(), and Gui::ViewProviderLink::updateDataPrivate().
touch()
void Property::touch ()
Set the property touched.
Property status handling
Definition at line 255 of file Property.cpp.
References App::PropertyContainer::onChanged(), App::PropertyContainer::onEarlyChange(), StatusBits, and Touched.
Referenced by Spreadsheet::PropertySheet::afterRestore(), Gui::ViewProviderFeaturePythonImp::attach(), App::Document::Document(), Gui::ViewProviderTextDocument::doubleClicked(), Fem::Constraint::execute(), Part::Feature::execute(), App::GroupExtension::extensionExecute(), App::LinkBaseExtension::extensionExecute(), MeshGui::ViewProviderMesh::finishRestoring(), Spreadsheet::PropertySheet::invalidateDependants(), PartDesignGui::ViewProviderBody::onChanged(), Fem::ConstraintGear::onChanged(), Fem::ConstraintPulley::onChanged(), Fem::ConstraintBearing::onChanged(), TechDraw::DrawPage::onChanged(), PartDesign::Body::onDocumentRestored(), Fem::Constraint::onDocumentRestored(), App::Document::saveAs(), Gui::AlignmentGroup::setAlignable(), PartGui::ViewProviderPartExt::unsetHighlightedEdges(), PartGui::ViewProviderPartExt::unsetHighlightedFaces(), PartGui::ViewProviderPartExt::unsetHighlightedPoints(), and PartGui::ViewProviderPartExt::ViewProviderPartExt().
verifyPath()
void Property::verifyPath (const App::ObjectIdentifier & p) const protected virtual
Verify a path for the current property.
Definition at line 290 of file Property.cpp.
References buildPsets::p.
Friends And Related Function Documentation
DynamicProperty
friend class DynamicProperty friend
Definition at line 294 of file Property.h.
PropertyContainer
friend class PropertyContainer friend
Definition at line 292 of file Property.h.
PropertyData
friend struct PropertyData friend
Definition at line 293 of file Property.h.
Member Data Documentation
signalChanged
boost::signals2::signal<void(const App::Property&)> App::Property::signalChanged
Definition at line 335 of file Property.h.
Referenced by hasSetValue().
StatusBits
std::bitset<32> App::Property::StatusBits protected
Status bits of the property The first 8 bits are used for the base system the rest can be used in descendent classes to mark special statuses on the objects. The bits and their meaning are listed below: 0 - object is marked as 'touched' 1 - object is marked as 'immutable' 2 - object is marked as 'read-only' (for property editor) 3 - object is marked as 'hidden' (for property editor)
Definition at line 306 of file Property.h.
Referenced by App::DynamicProperty::addDynamicProperty(), hasSetValue(), App::PropertyContainer::Restore(), setStatus(), setStatusValue(), and touch().
The documentation for this class was generated from the following files:
Property.h
Property.cpp