FreeCAD: Gui::DAG::FilterOrigin Class Reference
Gui::DAG::FilterOrigin Class Reference
#include <DAGFilter.h>
Public Member Functions
FilterOrigin ()
bool goFilter (const Vertex &vertexIn, const Graph &graphIn, const GraphLinkContainer &linkIn) const override
Public Member Functions inherited from Gui::DAG::FilterBase
FilterBase ()
Additional Inherited Members
Public Types inherited from Gui::DAG::FilterBase
enum Type { Type::None = 0, Type::Inclusion, Type::Exclusion }
Public Attributes inherited from Gui::DAG::FilterBase
QString name
bool enabled = true
Type type = Type::Exclusion
Detailed Description
Hide all children of app::origin that are not used by subsequent features
Definition at line 75 of file DAGFilter.h.
Constructor & Destructor Documentation
FilterOrigin()
FilterOrigin::FilterOrigin ()
Definition at line 39 of file DAGFilter.cpp.
References Gui::DAG::FilterBase::name.
Member Function Documentation
goFilter()
bool FilterOrigin::goFilter (const Vertex & vertexIn, const Graph & graphIn, const GraphLinkContainer & linkIn) const override virtual
Returns
is whether we have a match or not.
Implements Gui::DAG::FilterBase.
Definition at line 44 of file DAGFilter.cpp.
References Base::Type::badType(), Gui::DAG::GraphLinkRecord::DObject, Gui::DAG::findRecord(), Base::Type::fromName(), and Base::Persistence::getTypeId().
The documentation for this class was generated from the following files:
DAGFilter.h
DAGFilter.cpp