FreeCAD: PartGui::HelixPrimitive Class Reference
PartGui::HelixPrimitive Class Reference
#include <DlgPrimitives.h>
Public Member Functions
HelixPrimitive (std::shared_ptr< Ui_DlgPrimitives > ui, Part::Helix *feature=nullptr)
const char * getDefaultName () const override
QString create (const QString &objectName, const QString &placement) const override
QString change (const QString &objectName, const QString &placement) const override
void changeValue (QObject *) override
Public Member Functions inherited from PartGui::AbstractPrimitive
AbstractPrimitive (Part::Primitive *feature=nullptr)
~AbstractPrimitive () override=default
bool hasValidPrimitive () const
Additional Inherited Members
Protected Member Functions inherited from PartGui::AbstractPrimitive
void connectSignalMapper (QSignalMapper *mapper)
Protected Attributes inherited from PartGui::AbstractPrimitive
App::DocumentObjectWeakPtrT featurePtr
Detailed Description
Definition at line 262 of file DlgPrimitives.h.
Constructor & Destructor Documentation
HelixPrimitive()
HelixPrimitive::HelixPrimitive (std::shared_ptr< Ui_DlgPrimitives > ui, Part::Helix * feature = nullptr)
Definition at line 1154 of file DlgPrimitives.cpp.
References Part::Helix::Angle, PartGui::connectMapSignalMapper(), PartGui::AbstractPrimitive::connectSignalMapper(), App::PropertyQuantity::getQuantityValue(), App::PropertyEnumeration::getValue(), Part::Helix::Height, Part::Helix::LocalCoord, Part::Helix::Pitch, Part::Helix::Radius, and Gui::QuantitySpinBox::valueChanged().
Member Function Documentation
change()
QString HelixPrimitive::change (const QString & objectName, const QString & placement) const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 1211 of file DlgPrimitives.cpp.
References PartGui::safeQuantityQString().
changeValue()
void HelixPrimitive::changeValue (QObject * widget) override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 1229 of file DlgPrimitives.cpp.
References Part::Helix::Angle, App::DocumentObjectWeakPtrT::expired(), PartGui::AbstractPrimitive::featurePtr, App::DocumentObjectWeakPtrT::get(), Part::Helix::Height, Part::Helix::LocalCoord, Part::Helix::Pitch, Part::Helix::Radius, App::DocumentObject::recomputeFeature(), App::PropertyQuantity::setValue(), and App::PropertyEnumeration::setValue().
create()
QString HelixPrimitive::create (const QString & objectName, const QString & placement) const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 1189 of file DlgPrimitives.cpp.
References PartGui::safeQuantityQString().
getDefaultName()
const char * HelixPrimitive::getDefaultName () const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 1184 of file DlgPrimitives.cpp.
The documentation for this class was generated from the following files:
DlgPrimitives.h
DlgPrimitives.cpp