FreeCAD: Assembly::BomObject Class Reference
Assembly::BomObject Class Reference
#include <BomObject.h>
Public Member Functions
BomObject ()
~BomObject () override
PyObject * getPyObject () override
const char * getViewProviderName () const override
returns the type name of the ViewProvider
App::DocumentObjectExecReturn * execute () override
void generateBOM ()
void addObjectToBom (App::DocumentObject *obj, size_t row, std::string index)
void addObjectChildrenToBom (std::vector< App::DocumentObject * > objs, size_t &row, std::string index)
void saveCustomColumnData ()
AssemblyObject * getAssembly ()
bool hasQuantityColumn ()
int getColumnIndex (std::string name)
std::string getText (size_t row, size_t col)
Public Member Functions inherited from Spreadsheet::Sheet
Sheet ()
Constructor.
~Sheet () override
Sheet::~Sheet.
const char * getViewProviderName () const override
returns the type name of the ViewProvider
bool importFromFile (const std::string &filename, char delimiter='\t', char quoteChar='\0', char escapeChar='\\')
bool getCharsFromPrefs (char &delimiter, char &quote, char &escape, std::string &errMsg)
bool exportToFile (const std::string &filename, char delimiter='\t', char quoteChar='\0', char escapeChar='\\') const
bool mergeCells (const App::Range &range)
void splitCell (App::CellAddress address)
Cell * getCell (App::CellAddress address)
Cell * getNewCell (App::CellAddress address)
unsigned getCellBindingBorder (App::CellAddress address) const
PropertySheet::BindingType getCellBinding (App::Range &range, App::ExpressionPtr *pStart=nullptr, App::ExpressionPtr *pEnd=nullptr, App::ObjectIdentifier *pTarget=nullptr) const
void setCell (const char *address, const char *value)
void setCell (App::CellAddress address, const char *value)
void clearAll ()
void clear (App::CellAddress address, bool all=true)
void getSpans (App::CellAddress address, int &rows, int &cols) const
bool isMergedCell (App::CellAddress address) const
App::CellAddress getAnchor (App::CellAddress address) const
void setColumnWidth (int col, int width)
Set column with of column col to width-.
int getColumnWidth (int col) const
Get column with of column at index col.
void setRowHeight (int row, int height)
Set row height of row given by index in row to height.
int getRowHeight (int row) const
Get height of row at index row.
std::vector< std::string > getUsedCells () const
void insertColumns (int col, int count)
void removeColumns (int col, int count)
void insertRows (int row, int count)
void removeRows (int row, int count)
void setContent (App::CellAddress address, const char *value)
Set content of cell at address to value.
void setAlignment (App::CellAddress address, int alignment)
Set alignment of content in cell at address to alignment.
void setStyle (App::CellAddress address, const std::set< std::string > &style)
Set style of cell at address to style.
void setForeground (App::CellAddress address, const App::Color &color)
Set foreground (text color) of cell at address address to color.
void setBackground (App::CellAddress address, const App::Color &color)
Set background color of cell at address address to color.
void setDisplayUnit (App::CellAddress address, const std::string &unit)
Set display unit of cell at address address to unit.
void setComputedUnit (App::CellAddress address, const Base::Unit &unit)
Set computed unit for cell at address address to unit.
void setAlias (App::CellAddress address, const std::string &alias)
Set alias for cell at address address to alias. If the alias is an empty string, the existing alias is removed.
std::string getAddressFromAlias (const std::string &alias) const
Get cell given an alias string.
bool isValidAlias (const std::string &candidate)
Determine whether a given alias candidate is valid or not.
void setSpans (App::CellAddress address, int rows, int columns)
Set row and column span for the cell at address address to rows and columns.
std::set< std::string > dependsOn (App::CellAddress address) const
Return a set of dependencies links for cell at address.
void providesTo (App::CellAddress address, std::set< std::string > &result) const
Compute links to cells that cell at address provides input to.
bool hasCell (const std::vector< App::Range > &ranges) const
PyObject * getPyObject () override
PropertySheet * getCells ()
App::Property * getPropertyByName (const char *name) const override
App::Property * getDynamicPropertyByName (const char *name) const override
void getPropertyNamedList (std::vector< std::pair< const char *, App::Property * >> &List) const override
short mustExecute () const override
App::DocumentObjectExecReturn * execute () override
bool getCellAddress (const App::Property *prop, App::CellAddress &address)
App::CellAddress getCellAddress (const char *name, bool silent=false) const
App::Range getRange (const char *name, bool silent=false) const
std::tuple< App::CellAddress, App::CellAddress > getUsedRange () const
std::map< int, int > getColumnWidths () const
Get a map with column indices and widths.
std::map< int, int > getRowHeights () const
Get a map with row indices and heights.
std::string getRow (int offset=0) const
std::string getColumn (int offset=0) const
void touchCells (App::Range range)
void recomputeCells (App::Range range)
void observeDocument (App::Document *document)
Create a document observer for this sheet. Used to track changes.
void renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &paths) override
void setCopyOrCutRanges (const std::vector< App::Range > &ranges, bool copy=true)
const std::vector< App::Range > & getCopyOrCutRange (bool copy=true) const
unsigned getCopyOrCutBorder (App::CellAddress address, bool copy=true) const
Public Member Functions inherited from App::DocumentObject
virtual const char * getViewProviderNameOverride () const
DocumentObject ()
Constructor.
~DocumentObject () override
const char * getDagKey () const
returns a value that uniquely identifies this DocumentObject.
const char * getNameInDocument () const
returns the name which is set in the document for this object (not the name property!)
long getID () const
Return the object ID that is unique within its owner document.
std::string getExportName (bool forced=false) const
returns the name that is safe to be exported to other document
std::string getFullName () const override
Return the object full name of the form DocName::ObjName.
std::string getFullLabel () const
Return the object full label in the form DocName::ObjName.
bool isAttachedToDocument () const override
const char * detachFromDocument () override
App::Document * getDocument () const
gets the document in which this Object is handled
void touch (bool noRecompute=false)
set this document object touched (cause recomputation on dependent features)
bool isTouched () const
test if this document object is touched
void enforceRecompute ()
Enforce this document object to be recomputed.
bool mustRecompute () const
Test if this document object must be recomputed.
void purgeTouched ()
reset this document object touched
bool isError () const
set this feature to error
bool isValid () const
void purgeError ()
remove the error from the object
bool isRecomputing () const
returns true if this objects is currently recomputing
bool isRestoring () const
returns true if this objects is currently restoring from file
bool isRemoving () const
returns true if this objects is currently removed from the document
void freeze ()
set this document object freezed (prevent recomputation)
void unfreeze (bool noRecompute=false)
set this document object unfreezed (and touch it)
bool isFreezed () const
returns true if this objects is currently freezed
unsigned long getStatus () const
return the status bits
bool testStatus (ObjectStatus pos) const
void setStatus (ObjectStatus pos, bool on)
int isExporting () const
virtual int setElementVisible (const char *element, bool visible)
virtual int isElementVisible (const char *element) const
virtual bool hasChildElement () const
return true to activate tree view group object handling and element visibility
const std::vector< App::DocumentObject * > & getOutList () const
returns a list of objects this object is pointing to by Links
std::vector< App::DocumentObject * > getOutList (int option) const
void getOutList (int option, std::vector< App::DocumentObject * > &res) const
std::vector< App::DocumentObject * > getOutListOfProperty (App::Property *) const
returns a list of objects linked by the property
std::vector< App::DocumentObject * > getOutListRecursive () const
returns a list of objects this object is pointing to by Links and all further descended
void clearOutListCache () const
clear internal out list cache
std::vector< std::list< App::DocumentObject * > > getPathsByOutList (App::DocumentObject *to) const
get all possible paths from this to another object following the OutList
const std::vector< App::DocumentObject * > & getInList () const
std::vector< App::DocumentObject * > getInListRecursive () const
get all objects link directly or indirectly to this object
void getInListEx (std::set< App::DocumentObject * > &inSet, bool recursive, std::vector< App::DocumentObject * > *inList=nullptr) const
std::set< App::DocumentObject * > getInListEx (bool recursive) const
DocumentObjectGroup * getGroup () const
get group if object is part of a group, otherwise 0 is returned
bool isInInListRecursive (DocumentObject *objToTest) const
test if this object is in the InList and recursive further down
bool isInInList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the InList
bool isInOutListRecursive (DocumentObject *objToTest) const
test if the given object is in the OutList and recursive further down
bool isInOutList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the OutList
void _removeBackLink (DocumentObject *)
internal, used by PropertyLink to maintain DAG back links
void _addBackLink (DocumentObject *)
internal, used by PropertyLink to maintain DAG back links
bool testIfLinkDAGCompatible (DocumentObject *linkTo) const
testIfLinkIsDAG tests a link that is about to be created for circular references.
bool testIfLinkDAGCompatible (const std::vector< DocumentObject * > &linksTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSubList &linksTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSub &linkTo) const
virtual std::string getElementMapVersion (const App::Property *prop, bool restored=false) const
virtual bool checkElementMapVersion (const App::Property *prop, const char *ver) const
Return true to signal re-generation of geometry element names.
bool recomputeFeature (bool recursive=false)
const char * getStatusString () const
get the status Message
virtual void onLostLinkToObject (DocumentObject *)
virtual DocumentObject * getSubObject (const char *subname, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
std::vector< DocumentObject * > getSubObjectList (const char *subname, std::vector< int > *subsizes=nullptr, bool flatten=false) const
virtual std::vector< std::string > getSubObjects (int reason=0) const
std::vector< std::pair< App::DocumentObject *, std::string > > getParents (int depth=0) const
Obtain top parents and subnames of this object using its InList.
App::DocumentObject * getFirstParent () const
Obtain the first parent group of this object.
virtual DocumentObject * getLinkedObject (bool recurse=true, Base::Matrix4D *mat=nullptr, bool transform=false, int depth=0) const
virtual bool canLinkProperties () const
virtual bool isLink () const
virtual bool isLinkGroup () const
virtual bool allowDuplicateLabel () const
virtual void onBeforeChangeLabel (std::string &newLabel)
void Save (Base::Writer &writer) const override
virtual void setExpression (const ObjectIdentifier &path, std::shared_ptr< App::Expression > expr)
void clearExpression (const ObjectIdentifier &path)
virtual const PropertyExpressionEngine::ExpressionInfo getExpression (const ObjectIdentifier &path) const
const std::string & getOldLabel () const
const char * getViewProviderNameStored () const
bool removeDynamicProperty (const char *prop) override
App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
App::DocumentObject * resolve (const char *subname, App::DocumentObject **parent=nullptr, std::string *childName=nullptr, const char **subElement=nullptr, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
App::DocumentObject * resolveRelativeLink (std::string &subname, App::DocumentObject *&link, std::string &linkSub) const
virtual bool adjustRelativeLinks (const std::set< App::DocumentObject * > &inList, std::set< App::DocumentObject * > *visited=nullptr)
virtual int canLoadPartial () const
virtual void onUpdateElementReference (const Property *)
virtual bool redirectSubName (std::ostringstream &ss, DocumentObject *topParent, DocumentObject *child) const
Public Member Functions inherited from App::TransactionalObject
TransactionalObject ()
Constructor.
~TransactionalObject () override
Public Member Functions inherited from App::ExtensionContainer
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop) override
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual std::vector< std::string > getDynamicPropertyNames () const
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Attributes
App::PropertyStringList columnsNames
App::PropertyBool detailSubAssemblies
App::PropertyBool detailParts
App::PropertyBool onlyParts
std::vector< BomDataElement > dataElements
std::vector< App::DocumentObject * > obj_list
Public Attributes inherited from Spreadsheet::Sheet
boost::signals2::signal< void(App::CellAddress)> cellUpdated
boost::signals2::signal< void(App::Range)> rangeUpdated
boost::signals2::signal< void(App::CellAddress)> cellSpanChanged
boost::signals2::signal< void(int, int)> columnWidthChanged
boost::signals2::signal< void(int, int)> rowHeightChanged
Public Attributes inherited from App::DocumentObject
PropertyString Label
PropertyString Label2
PropertyExpressionEngine ExpressionEngine
PropertyBool Visibility
Allow control visibility status in App name space.
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalBeforeChange
signal before changing a property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalChanged
signal on changed property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalEarlyChanged
signal on changed property of this object before document scoped signalChangedObject
Additional Inherited Members
Public Types inherited from Spreadsheet::Sheet
enum Border {
BorderTop = 1, BorderLeft = 2, BorderBottom = 4, BorderRight = 8,
BorderAll = 15
}
Public Types inherited from App::DocumentObject
enum OutListOption { OutListNoExpression = 1, OutListNoHidden = 2, OutListNoXLinked = 4 }
OutList options.
enum GSReason { GS_DEFAULT, GS_SELECT }
reason of calling getSubObjects()
Public Types inherited from App::ExtensionContainer
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Static Public Member Functions inherited from App::DocumentObject
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
Check if the subname reference ends with hidden marker.
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Attributes inherited from App::DocumentObject
static DocumentObjectExecReturn * StdReturn
Protected Types inherited from Spreadsheet::Sheet
using ObserverMap = std::map< std::string, SheetObserver * >
Protected Member Functions inherited from Spreadsheet::Sheet
void onChanged (const App::Property *prop) override
get called by the container when a property was changed
void updateColumnsOrRows (bool horizontal, int section, int count)
std::set< App::CellAddress > providesTo (App::CellAddress address) const
Compute links to cells that cell at address provides input to.
void onDocumentRestored () override
get called after a document has been fully restored
void recomputeCell (App::CellAddress p)
Recompute cell at address p.
App::Property * getProperty (App::CellAddress key) const
App::Property * getProperty (const char *addr) const
Get a dynamic property.
void updateProperty (App::CellAddress key)
App::Property * setStringProperty (App::CellAddress key, const std::string &value)
App::Property * setObjectProperty (App::CellAddress key, Py::Object obj)
App::Property * setFloatProperty (App::CellAddress key, double value)
App::Property * setIntegerProperty (App::CellAddress key, long value)
App::Property * setQuantityProperty (App::CellAddress key, double value, const Base::Unit &unit)
void onSettingDocument () override
void updateBindings ()
Protected Member Functions inherited from App::DocumentObject
virtual App::DocumentObjectExecReturn * recompute ()
recompute only this object
App::DocumentObjectExecReturn * executeExtensions ()
void setError ()
void resetError ()
void setDocument (App::Document *doc)
void onBeforeChange (const Property *prop) override
get called before the value is changed
void onEarlyChange (const Property *prop) override
get called by the container when a property was changed
virtual void onUndoRedoFinished ()
get called after an undo/redo transaction is finished
virtual void setupObject ()
get called after a brand new object was created
virtual void unsetupObject ()
get called when object is going to be removed from the document
void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus) override
get called when a property status has changed
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData () const
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Spreadsheet::Sheet
App::DynamicProperty & props
std::map< const App::Property *, App::CellAddress > propAddress
std::set< App::CellAddress > cellErrors
PropertySheet cells
PropertyColumnWidths columnWidths
PropertyRowHeights rowHeights
ObserverMap observers
int currentRow = -1
int currentCol = -1
std::vector< App::Range > boundRanges
std::vector< App::Range > copyCutRanges
bool hasCopyRange = false
Protected Attributes inherited from App::DocumentObject
std::bitset< 32 > StatusBits
Py::SmartPtr PythonObject
python object of this class and all descendent
App::Document * _pDoc {nullptr}
pointer to the document this object belongs to
std::string oldLabel
Old label; used for renaming expressions.
const std::string * pcNameInDocument {nullptr}
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Detailed Description
Definition at line 61 of file BomObject.h.
Constructor & Destructor Documentation
BomObject()
BomObject::BomObject ()
Definition at line 59 of file BomObject.cpp.
References ADD_PROPERTY_TYPE, and App::Prop_None.
~BomObject()
BomObject::~BomObject () override default
Member Function Documentation
addObjectChildrenToBom()
void BomObject::addObjectChildrenToBom (std::vector< App::DocumentObject * > objs, size_t & row, std::string index)
Definition at line 161 of file BomObject.cpp.
References addObjectToBom(), detailParts, detailSubAssemblies, getColumnIndex(), App::DocumentObject::getLinkedObject(), getText(), App::PropertyBool::getValue(), hasQuantityColumn(), SplineSurface::i, Base::BaseClass::isDerivedFrom(), obj_list, replaceobj::objs, onlyParts, and Spreadsheet::Sheet::setCell().
Referenced by generateBOM().
addObjectToBom()
void BomObject::addObjectToBom (App::DocumentObject * obj, size_t row, std::string index)
Definition at line 225 of file BomObject.cpp.
References Spreadsheet::columnName(), columnsNames, dataElements, App::DocumentObject::getDocument(), App::Document::getFileName(), App::PropertyString::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::DocumentObject::Label, obj_list, and Spreadsheet::Sheet::setCell().
Referenced by addObjectChildrenToBom().
execute()
App::DocumentObjectExecReturn * BomObject::execute () override virtual
get called by the document to recompute this feature Normally this method get called in the processing of Document::recompute(). In execute() the output properties get recomputed with the data from linked objects and objects own properties.
Reimplemented from App::DocumentObject.
Definition at line 98 of file BomObject.cpp.
References Spreadsheet::Sheet::execute(), and generateBOM().
Referenced by draftobjects.facebinder.Facebinder::addSubobjects(), Path.Dressup.Gui.Dogbone.ObjectDressup::boneStateList(), Path.Dressup.Tags.ObjectTagDressup::generateTags(), ArchRoof._Roof::getSubVolume(), ArchPanel.PanelCut::getWires(), src.Mod.PartDesign.Scripts.Spring.MySpring::onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid::onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped::onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt::onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder::onChanged(), MeasureCOM.MeasureCOM::onChanged(), Path.Main.Stock.StockFromBase::onChanged(), Path.Main.Stock.StockCreateBox::onChanged(), Path.Main.Stock.StockCreateCylinder::onChanged(), FeaturePython.DistanceBolt::onChanged(), draftobjects.draftlink.DraftLink::onDocumentRestored(), ArchSchedule._ArchSchedule::setSpreadsheetData(), and draftobjects.array.Array::update_properties_0v21().
generateBOM()
void BomObject::generateBOM ()
Definition at line 137 of file BomObject.cpp.
References addObjectChildrenToBom(), Spreadsheet::Sheet::clearAll(), Spreadsheet::columnName(), columnsNames, getAssembly(), App::DocumentObject::getDocument(), App::PropertyListsT< T, ListT, ParentT >::getValues(), obj_list, saveCustomColumnData(), and Spreadsheet::Sheet::setCell().
Referenced by execute().
getAssembly()
AssemblyObject * BomObject::getAssembly ()
Definition at line 255 of file BomObject.cpp.
References App::DocumentObject::getInList().
Referenced by JointObject.Joint::flipOnePart(), generateBOM(), JointObject.Joint::onChanged(), JointObject.Joint::preSolve(), JointObject.Joint::preventParallel(), and CommandCreateView.ExplodedView::restoreAssembly().
getColumnIndex()
int BomObject::getColumnIndex (std::string name)
Definition at line 291 of file BomObject.cpp.
References Spreadsheet::columnName(), columnsNames, and App::PropertyListsT< T, ListT, ParentT >::getValues().
Referenced by addObjectChildrenToBom(), and saveCustomColumnData().
getPyObject()
PyObject * BomObject::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from App::DocumentObject.
Definition at line 89 of file BomObject.cpp.
References Py::SmartPtr::is(), Py::new_reference_to(), and App::DocumentObject::PythonObject.
getText()
std::string Assembly::BomObject::getText (size_t row, size_t col)
Definition at line 275 of file BomObject.cpp.
References Spreadsheet::Cell::getStringContent().
Referenced by addObjectChildrenToBom(), and saveCustomColumnData().
getViewProviderName()
const char* Assembly::BomObject::getViewProviderName () const inline override virtual
returns the type name of the ViewProvider
Reimplemented from App::DocumentObject.
Definition at line 71 of file BomObject.h.
hasQuantityColumn()
bool BomObject::hasQuantityColumn ()
Definition at line 265 of file BomObject.cpp.
References Spreadsheet::columnName(), columnsNames, and App::PropertyListsT< T, ListT, ParentT >::getValues().
Referenced by addObjectChildrenToBom().
saveCustomColumnData()
void BomObject::saveCustomColumnData ()
Definition at line 105 of file BomObject.cpp.
References Spreadsheet::columnName(), columnsNames, dataElements, getColumnIndex(), getText(), Spreadsheet::Sheet::getUsedRange(), App::PropertyListsT< T, ListT, ParentT >::getValues(), and SplineSurface::i.
Referenced by generateBOM().
Member Data Documentation
columnsNames
App::PropertyStringList Assembly::BomObject::columnsNames
Definition at line 90 of file BomObject.h.
Referenced by addObjectToBom(), generateBOM(), getColumnIndex(), hasQuantityColumn(), and saveCustomColumnData().
dataElements
std::vector<BomDataElement> Assembly::BomObject::dataElements
Definition at line 95 of file BomObject.h.
Referenced by addObjectToBom(), and saveCustomColumnData().
detailParts
App::PropertyBool Assembly::BomObject::detailParts
Definition at line 92 of file BomObject.h.
Referenced by addObjectChildrenToBom().
detailSubAssemblies
App::PropertyBool Assembly::BomObject::detailSubAssemblies
Definition at line 91 of file BomObject.h.
Referenced by addObjectChildrenToBom().
obj_list
std::vector<App::DocumentObject*> Assembly::BomObject::obj_list
Definition at line 96 of file BomObject.h.
Referenced by addObjectChildrenToBom(), addObjectToBom(), and generateBOM().
onlyParts
App::PropertyBool Assembly::BomObject::onlyParts
Definition at line 93 of file BomObject.h.
Referenced by addObjectChildrenToBom().
The documentation for this class was generated from the following files:
BomObject.h
BomObject.cpp