FreeCAD: Gui::PrefPagePyProducer Class Reference
Gui::PrefPagePyProducer Class Reference
#include <WidgetFactory.h>
Public Member Functions
PrefPagePyProducer (const Py::Object &, const char *group)
~PrefPagePyProducer () override
void * Produce () const override
Public Member Functions inherited from Base::AbstractProducer
AbstractProducer ()=default
virtual ~AbstractProducer ()=default
Detailed Description
The PrefPagePyProducer class provides the ability to create preference pages dynamically from a Python class.
Author
Werner Mayer
Definition at line 170 of file WidgetFactory.h.
Constructor & Destructor Documentation
PrefPagePyProducer()
PrefPagePyProducer::PrefPagePyProducer (const Py::Object & p, const char * group)
Register a special type of preference page to the WidgetFactoryInst.
Definition at line 223 of file WidgetFactory.cpp.
References Gui::Dialog::DlgPreferencesImp::addPage(), Base::Factory::AddProducer(), toolbit-attributes::group, Gui::WidgetFactoryInst::instance(), Path.Post.scripts.refactored_centroid_post::str, and src.Mod.Test.testmakeWireString::String.
~PrefPagePyProducer()
PrefPagePyProducer::~PrefPagePyProducer () override
Definition at line 236 of file WidgetFactory.cpp.
Member Function Documentation
Produce()
void * PrefPagePyProducer::Produce () const override virtual
Creates an instance of the specified widget.
Implements Base::AbstractProducer.
Definition at line 242 of file WidgetFactory.cpp.
References toolbit-attributes::args.
The documentation for this class was generated from the following files:
WidgetFactory.h
WidgetFactory.cpp