FreeCAD: ViewProviderSketch.cpp File Reference
ViewProviderSketch.cpp File Reference
#include "PreCompiled.h"
#include <boost/core/ignore_unused.hpp>
#include <Inventor/SbBox3f.h>
#include <Inventor/SbLine.h>
#include <Inventor/SbTime.h>
#include <Inventor/SoPickedPoint.h>
#include <Inventor/actions/SoGetBoundingBoxAction.h>
#include <Inventor/details/SoPointDetail.h>
#include <Inventor/events/SoKeyboardEvent.h>
#include <Inventor/nodes/SoCamera.h>
#include <QApplication>
#include <QFontMetricsF>
#include <QMenu>
#include <QMessageBox>
#include <QScreen>
#include <QTextStream>
#include <Base/Console.h>
#include <Base/Vector3D.h>
#include <Gui/Application.h>
#include <Gui/BitmapFactory.h>
#include <Gui/CommandT.h>
#include <Gui/Control.h>
#include <Gui/Document.h>
#include <Gui/MainWindow.h>
#include <Gui/MenuManager.h>
#include <Gui/Selection.h>
#include <Gui/SelectionObject.h>
#include <Gui/SoFCUnifiedSelection.h>
#include <Gui/Utilities.h>
#include <Gui/View3DInventor.h>
#include <Gui/View3DInventorViewer.h>
#include <Mod/Part/App/Geometry.h>
#include <Mod/Sketcher/App/GeoList.h>
#include <Mod/Sketcher/App/GeometryFacade.h>
#include <Mod/Sketcher/App/SketchObject.h>
#include <Mod/Sketcher/App/SolverGeometryExtension.h>
#include "DrawSketchHandler.h"
#include "EditDatumDialog.h"
#include "EditModeCoinManager.h"
#include "SnapManager.h"
#include "TaskDlgEditSketch.h"
#include "TaskSketcherValidation.h"
#include "Utils.h"
#include "ViewProviderSketch.h"
#include "ViewProviderSketchGeometryExtension.h"
#include "Workbench.h"
Functions
template<typename T >
T getSketcherGeneralParameter (const std::string &string, T defaultvalue)
template<typename T >
T getPreferencesViewParameter (const std::string &string, T defaultvalue)
QString intListHelper (const std::vector< int > &ints)
Function Documentation
getPreferencesViewParameter()
template<typename T > T getPreferencesViewParameter (const std::string & string, T defaultvalue)
Definition at line 100 of file ViewProviderSketch.cpp.
References App::GetApplication(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), and ParameterGrp::GetUnsigned().
getSketcherGeneralParameter()
template<typename T > T getSketcherGeneralParameter (const std::string & string, T defaultvalue)
Definition at line 86 of file ViewProviderSketch.cpp.
References App::GetApplication(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), and ParameterGrp::GetUnsigned().
intListHelper()
QString intListHelper (const std::vector< int > & ints) inline
Definition at line 3198 of file ViewProviderSketch.cpp.
References SplineSurface::i, and src.Mod.AddonManager.Addon::translate.
Referenced by SketcherGui::ViewProviderSketch::UpdateSolverInformation().