FreeCAD: Gui::ExpressionTextEdit Class Reference
Gui::ExpressionTextEdit Class Reference
#include <ExpressionCompleter.h>
Public Slots
void slotTextChanged ()
void slotCompleteText (const QString &completionPrefix)
Signals
void textChanged2 (QString text, int pos)
Public Member Functions
ExpressionTextEdit (QWidget *parent=nullptr)
void setDocumentObject (const App::DocumentObject *currentDocObj)
bool completerActive () const
void hideCompleter ()
void setExactMatch (bool enabled=true)
Protected Member Functions
void keyPressEvent (QKeyEvent *event) override
void contextMenuEvent (QContextMenuEvent *event) override
Detailed Description
Definition at line 112 of file ExpressionCompleter.h.
Constructor & Destructor Documentation
ExpressionTextEdit()
ExpressionTextEdit::ExpressionTextEdit (QWidget * parent = nullptr)
Definition at line 1044 of file ExpressionCompleter.cpp.
References draftgeoutils.intersections::connect(), and slotTextChanged().
Member Function Documentation
completerActive()
bool ExpressionTextEdit::completerActive () const
Definition at line 1090 of file ExpressionCompleter.cpp.
contextMenuEvent()
void ExpressionTextEdit::contextMenuEvent (QContextMenuEvent * event) override protected
Definition at line 1131 of file ExpressionCompleter.cpp.
References Path.Post.scripts.dynapath_4060_post::action, NavigationIndicatorGui::menu, and setExactMatch().
hideCompleter()
void ExpressionTextEdit::hideCompleter ()
Definition at line 1095 of file ExpressionCompleter.cpp.
keyPressEvent()
void ExpressionTextEdit::keyPressEvent (QKeyEvent * event) override protected
Definition at line 1125 of file ExpressionCompleter.cpp.
References SCL.SimpleDataTypes::e.
setDocumentObject()
void ExpressionTextEdit::setDocumentObject (const App::DocumentObject * currentDocObj)
Definition at line 1061 of file ExpressionCompleter.cpp.
References draftgeoutils.intersections::connect(), Gui::ExpressionCompleter::setDocumentObject(), slotCompleteText(), Gui::ExpressionCompleter::slotUpdate(), and textChanged2().
setExactMatch()
void ExpressionTextEdit::setExactMatch (bool enabled = true)
Definition at line 1053 of file ExpressionCompleter.cpp.
Referenced by contextMenuEvent().
slotCompleteText
void ExpressionTextEdit::slotCompleteText (const QString & completionPrefix) slot
Definition at line 1110 of file ExpressionCompleter.cpp.
References Gui::ExpressionCompleter::getPrefixRange(), RobotExample::pos, and Gui::ExpressionCompleter::updatePrefixEnd().
Referenced by setDocumentObject().
slotTextChanged
void ExpressionTextEdit::slotTextChanged () slot
Definition at line 1102 of file ExpressionCompleter.cpp.
References textChanged2().
Referenced by ExpressionTextEdit().
textChanged2
void Gui::ExpressionTextEdit::textChanged2 (QString text, int pos) signal
Referenced by setDocumentObject(), and slotTextChanged().
The documentation for this class was generated from the following files:
ExpressionCompleter.h
ExpressionCompleter.cpp