FreeCAD: dxf.cpp File Reference
dxf.cpp File Reference
#include "PreCompiled.h"
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include "dxf.h"
#include <App/Application.h>
#include <App/Color.h>
#include <Base/Console.h>
#include <Base/FileInfo.h>
#include <Base/Interpreter.h>
#include <Base/Stream.h>
#include <Base/Tools.h>
#include <Base/Vector3D.h>
Macros
#define _USE_MATH_DEFINES
#define ALIGNED 0
#define HORIZONTAL 1
#define VERTICAL 2
#define ANSI_ENCODING_PREFIX "ansi_"
Functions
static Base::Vector3d MakeVector3d (const double coordinates[3])
static double level (int distance, double blackLevel)
static App::Color wheel (int hue, double blackLevel, double multiplier=1.0)
Macro Definition Documentation
_USE_MATH_DEFINES
#define _USE_MATH_DEFINES
Definition at line 9 of file dxf.cpp.
ALIGNED
#define ALIGNED 0
Definition at line 1097 of file dxf.cpp.
ANSI_ENCODING_PREFIX
#define ANSI_ENCODING_PREFIX "ansi_"
HORIZONTAL
#define HORIZONTAL 1
Definition at line 1098 of file dxf.cpp.
VERTICAL
#define VERTICAL 2
Definition at line 1099 of file dxf.cpp.
Function Documentation
level()
static double level (int distance, double blackLevel) inline static
Definition at line 3006 of file dxf.cpp.
Referenced by MeshGui::ViewProviderMesh::fillHole(), MeshCore::MeshAlgorithm::FillupHole(), Mesh::MeshObject::fillupHoles(), MeshCore::MeshTopoAlgorithm::FillupHoles(), Base::LogLevel::isEnabled(), NotificationsAction::isSameNotification(), Base::ConsoleSingleton::LogLevel(), makeParallelMengerSponge(), myPreactionCB_CollectFacets(), myPreactionCB_PrintName(), MeshCore::MeshRefPointToFacets::NeighbourPoints(), printBrep(), printMaterial(), printShape(), printWrep(), printXform(), Gui::NotificationArea::pushNotification(), Base::XMLReader::readEndElement(), recur(), Gui::DocumentItem::ExpandInfo::restore(), Base::ConsoleObserverFile::SendLog(), Gui::GUIConsole::SendLog(), Base::ConsoleObserverStd::SendLog(), Gui::SplashObserver::SendLog(), Gui::DockWnd::ReportOutput::SendLog(), NotificationAreaObserver::SendLog(), Gui::StatusBarObserver::SendLog(), Gui::TestConsoleObserver::SendLog(), Gui::NetworkRetriever::setEnableRecursive(), Sierpinski(), Materials::Material3DArray::validateRow(), and wheel().
MakeVector3d()
static Base::Vector3d MakeVector3d (const double coordinates[3]) static
Definition at line 28 of file dxf.cpp.
Referenced by CDxfWrite::writeAngularDimBlock(), CDxfWrite::writeDiametricDimBlock(), CDxfWrite::writeLinearDimBlock(), and CDxfWrite::writeRadialDimBlock().
wheel()
static App::Color wheel (int hue, double blackLevel, double multiplier = 1.0) inline static
Definition at line 3030 of file dxf.cpp.
References level().
Referenced by CDxfRead::ObjectColor(), and SIM::Coin3D::Quarter::QuarterWidget::viewportEvent().