FreeCAD: MatGui::DlgMaterialImp Class Reference
MatGui::DlgMaterialImp Class Reference
#include <DlgMaterialImp.h>
Classes
class Private
Public Member Functions
DlgMaterialImp (bool floating, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgMaterialImp () override
void OnChange (Gui::SelectionSingleton::SubjectType &rCaller, Gui::SelectionSingleton::MessageType Reason) override
Observer message from the Selection.
void showDefaultButtons (bool)
void reject () override
Protected Member Functions
void changeEvent (QEvent *e) override
Detailed Description
The DlgMaterialImp class implements a dialog containing all available document templates to create a new document.
Author
Jürgen Riegel
Definition at line 54 of file DlgMaterialImp.h.
Constructor & Destructor Documentation
DlgMaterialImp()
DlgMaterialImp::DlgMaterialImp (bool floating, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Constructs a DlgMaterialImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
Definition at line 77 of file DlgMaterialImp.cpp.
References Gui::DockWindowManager::addDockWindow(), Base::Subject< MsgType >::Attach(), draftgeoutils.faces::bind(), Gui::DockWindowManager::instance(), Gui::Application::Instance, importers.importIFCmulticore::objects, Gui::Selection(), and Gui::Application::signalChangedObject.
~DlgMaterialImp()
DlgMaterialImp::~DlgMaterialImp () override
Destroys the object and frees any allocated resources
Definition at line 116 of file DlgMaterialImp.cpp.
References Base::Subject< MsgType >::Detach(), and Gui::Selection().
Member Function Documentation
changeEvent()
void DlgMaterialImp::changeEvent (QEvent * e) override protected
Definition at line 131 of file DlgMaterialImp.cpp.
References SCL.SimpleDataTypes::e.
OnChange()
void MatGui::DlgMaterialImp::OnChange (Gui::SelectionSingleton::SubjectType & rCaller, Gui::SelectionSingleton::MessageType Reason) override
Observer message from the Selection.
reject()
void DlgMaterialImp::reject () override
Destroys the dock window this object is embedded into without destroying itself.
Definition at line 187 of file DlgMaterialImp.cpp.
References Gui::DockWindowManager::instance(), and Gui::DockWindowManager::removeDockWindow().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and MatGui::TaskMaterial::reject().
showDefaultButtons()
void MatGui::DlgMaterialImp::showDefaultButtons (bool)
The documentation for this class was generated from the following files:
DlgMaterialImp.h
DlgMaterialImp.cpp