FreeCAD: Gui::MacroOutputOption Class Reference
Gui::MacroOutputOption Class Reference
#include <Macro.h>
Public Member Functions
MacroOutputOption ()
std::tuple< bool, bool > values (int type) const
Static Public Member Functions
static bool isComment (int type)
static bool isGuiCommand (int type)
static bool isAppCommand (int type)
Public Attributes
bool recordGui {true}
bool guiAsComment {true}
bool scriptToPyConsole {true}
Detailed Description
Definition at line 102 of file Macro.h.
Constructor & Destructor Documentation
MacroOutputOption()
MacroOutputOption::MacroOutputOption () default
Member Function Documentation
isAppCommand()
bool MacroOutputOption::isAppCommand (int type) static
Definition at line 199 of file Macro.cpp.
References Gui::MacroManager::App, and Path.Post.scripts.grbl_post::type.
isComment()
bool MacroOutputOption::isComment (int type) static
Definition at line 189 of file Macro.cpp.
References Gui::MacroManager::Cmt, and Path.Post.scripts.grbl_post::type.
Referenced by Gui::MacroOutputBuffer::addPendingLineIfComment(), Gui::MacroOutputBuffer::incrementIfNoComment(), and values().
isGuiCommand()
bool MacroOutputOption::isGuiCommand (int type) static
Definition at line 194 of file Macro.cpp.
References Gui::MacroManager::Gui, and Path.Post.scripts.grbl_post::type.
Referenced by values().
values()
std::tuple< bool, bool > MacroOutputOption::values (int type) const
Definition at line 171 of file Macro.cpp.
References AttacherGui::comment, guiAsComment, isComment(), isGuiCommand(), recordGui, and Path.Post.scripts.grbl_post::type.
Member Data Documentation
guiAsComment
bool Gui::MacroOutputOption::guiAsComment {true}
Definition at line 113 of file Macro.h.
Referenced by Gui::MacroManager::OnChange(), and values().
recordGui
bool Gui::MacroOutputOption::recordGui {true}
Definition at line 112 of file Macro.h.
Referenced by Gui::MacroManager::OnChange(), and values().
scriptToPyConsole
bool Gui::MacroOutputOption::scriptToPyConsole {true}
Definition at line 114 of file Macro.h.
Referenced by Gui::MacroManager::OnChange().
The documentation for this class was generated from the following files:
Macro.h
Macro.cpp