FreeCAD: TechDrawGui::QGIDrawingTemplate Class Reference
TechDrawGui::QGIDrawingTemplate Class Reference
#include <QGIDrawingTemplate.h>
Public Types
enum { Type = QGraphicsItem::UserType + 151 }
Public Types inherited from TechDrawGui::QGITemplate
enum { Type = QGraphicsItem::UserType + 150 }
Public Member Functions
QGIDrawingTemplate (QGSPage *)
~QGIDrawingTemplate () override
int type () const override
void clearContents ()
void draw () override
void updateView (bool update=false) override
Public Member Functions inherited from TechDrawGui::QGITemplate
QGITemplate (QGSPage *)
~QGITemplate () override
int type () const override
void clearContents ()
void setTemplate (TechDraw::DrawTemplate *obj)
TechDraw::DrawTemplate * getTemplate ()
qreal getY ()
std::vector< TemplateTextField * > getTextFields ()
Protected Member Functions
TechDraw::DrawParametricTemplate * getParametricTemplate ()
Protected Attributes
QGraphicsPathItem * pathItem
Protected Attributes inherited from TechDrawGui::QGITemplate
TechDraw::DrawTemplate * pageTemplate
std::vector< TemplateTextField * > textFields
Detailed Description
Definition at line 43 of file QGIDrawingTemplate.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 51 of file QGIDrawingTemplate.h.
Constructor & Destructor Documentation
QGIDrawingTemplate()
QGIDrawingTemplate::QGIDrawingTemplate (QGSPage * scene) explicit
Definition at line 36 of file QGIDrawingTemplate.cpp.
References pathItem.
~QGIDrawingTemplate()
QGIDrawingTemplate::~QGIDrawingTemplate () override
Definition at line 50 of file QGIDrawingTemplate.cpp.
References pathItem.
Member Function Documentation
clearContents()
void QGIDrawingTemplate::clearContents ()
Definition at line 55 of file QGIDrawingTemplate.cpp.
draw()
void QGIDrawingTemplate::draw () override virtual
Implements TechDrawGui::QGITemplate.
Definition at line 68 of file QGIDrawingTemplate.cpp.
References TechDraw::GENERIC, TechDraw::DrawParametricTemplate::getGeometry(), getParametricTemplate(), and pathItem.
Referenced by updateView().
getParametricTemplate()
TechDraw::DrawParametricTemplate * QGIDrawingTemplate::getParametricTemplate () protected
Definition at line 60 of file QGIDrawingTemplate.cpp.
References Base::Persistence::getClassTypeId(), Base::BaseClass::isDerivedFrom(), and TechDrawGui::QGITemplate::pageTemplate.
Referenced by draw().
type()
int TechDrawGui::QGIDrawingTemplate::type () const inline override
Definition at line 52 of file QGIDrawingTemplate.h.
updateView()
void QGIDrawingTemplate::updateView (bool update = false) override virtual
Reimplemented from TechDrawGui::QGITemplate.
Definition at line 110 of file QGIDrawingTemplate.cpp.
References draw().
Member Data Documentation
pathItem
QGraphicsPathItem* TechDrawGui::QGIDrawingTemplate::pathItem protected
Definition at line 62 of file QGIDrawingTemplate.h.
Referenced by draw(), QGIDrawingTemplate(), and ~QGIDrawingTemplate().
The documentation for this class was generated from the following files:
QGIDrawingTemplate.h
QGIDrawingTemplate.cpp