FreeCAD: SketcherGui::ViewProviderSketchGeometryExtension Class Reference
SketcherGui::ViewProviderSketchGeometryExtension Class Reference
#include <ViewProviderSketchGeometryExtension.h>
Public Member Functions
ViewProviderSketchGeometryExtension ()
~ViewProviderSketchGeometryExtension () override=default
std::unique_ptr< Part::GeometryExtension > copy () const override
PyObject * getPyObject () override
double getRepresentationFactor () const
void setRepresentationFactor (double representationFactor)
int getVisualLayerId () const
void setVisualLayerId (int visuallayerid)
Public Member Functions inherited from Part::GeometryPersistenceExtension
~GeometryPersistenceExtension () override=default
void Save (Base::Writer &) const
void Restore (Base::XMLReader &)
bool isSame (const GeometryPersistenceExtension &other) const
Public Member Functions inherited from Part::GeometryExtension
~GeometryExtension () override=default
PyObject * copyPyObject () const
void setName (const std::string &str)
const std::string & getName () const
virtual void notifyAttachment (Part::Geometry *)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
void copyAttributes (Part::GeometryExtension *cpy) const override
void restoreAttributes (Base::XMLReader &reader) override
void saveAttributes (Base::Writer &writer) const override
Protected Member Functions inherited from Part::GeometryExtension
GeometryExtension ()
GeometryExtension (const GeometryExtension &obj)=default
GeometryExtension & operator= (const GeometryExtension &obj)=default
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 53 of file ViewProviderSketchGeometryExtension.h.
Constructor & Destructor Documentation
ViewProviderSketchGeometryExtension()
SketcherGui::ViewProviderSketchGeometryExtension::ViewProviderSketchGeometryExtension ()
Referenced by getPyObject().
~ViewProviderSketchGeometryExtension()
SketcherGui::ViewProviderSketchGeometryExtension::~ViewProviderSketchGeometryExtension () override default
Member Function Documentation
copy()
std::unique_ptr< Part::GeometryExtension > ViewProviderSketchGeometryExtension::copy () const override virtual
Implements Part::GeometryExtension.
Definition at line 54 of file ViewProviderSketchGeometryExtension.cpp.
References copyAttributes(), and Path.Post.scripts.opensbp_post::move().
copyAttributes()
void ViewProviderSketchGeometryExtension::copyAttributes (Part::GeometryExtension * cpy) const override protected virtual
Reimplemented from Part::GeometryExtension.
Definition at line 46 of file ViewProviderSketchGeometryExtension.cpp.
References Part::GeometryExtension::copyAttributes().
Referenced by copy().
getPyObject()
PyObject * ViewProviderSketchGeometryExtension::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
Definition at line 84 of file ViewProviderSketchGeometryExtension.cpp.
References ViewProviderSketchGeometryExtension().
getRepresentationFactor()
double SketcherGui::ViewProviderSketchGeometryExtension::getRepresentationFactor () const inline
Definition at line 94 of file ViewProviderSketchGeometryExtension.h.
getVisualLayerId()
int SketcherGui::ViewProviderSketchGeometryExtension::getVisualLayerId () const inline
Definition at line 103 of file ViewProviderSketchGeometryExtension.h.
restoreAttributes()
void ViewProviderSketchGeometryExtension::restoreAttributes (Base::XMLReader & reader) override protected virtual
Reimplemented from Part::GeometryPersistenceExtension.
Definition at line 67 of file ViewProviderSketchGeometryExtension.cpp.
References TechDrawTools.TaskFillTemplateFields::reader, and Part::GeometryPersistenceExtension::restoreAttributes().
saveAttributes()
void ViewProviderSketchGeometryExtension::saveAttributes (Base::Writer & writer) const override protected virtual
Reimplemented from Part::GeometryPersistenceExtension.
Definition at line 76 of file ViewProviderSketchGeometryExtension.cpp.
References Part::GeometryPersistenceExtension::saveAttributes(), and Base::Writer::Stream().
setRepresentationFactor()
void SketcherGui::ViewProviderSketchGeometryExtension::setRepresentationFactor (double representationFactor) inline
Definition at line 98 of file ViewProviderSketchGeometryExtension.h.
setVisualLayerId()
void SketcherGui::ViewProviderSketchGeometryExtension::setVisualLayerId (int visuallayerid) inline
Definition at line 107 of file ViewProviderSketchGeometryExtension.h.
The documentation for this class was generated from the following files:
ViewProviderSketchGeometryExtension.h
ViewProviderSketchGeometryExtension.cpp