FreeCAD: OpenSCAD2Dgeom.Overlappingfaces Class Reference
OpenSCAD2Dgeom.Overlappingfaces Class Reference
Public Member Functions
def __init__ (self, facelist)
def builddepdict (self)
def findrootdepth (self)
def hasnoparent (self, faceindex)
def makefeatures (self, doc)
def makeshape (self)
Static Public Member Functions
def dofacesoverlapboundbox (bigface, smallface)
def dofacesoverlapallverts (bigface, smallface)
def dofacesoverlapproximity (bigface, smallface)
def dofacesoverlapboolean (bigface, smallface)
def finddepth (dict1, faceidx, curdepth=0)
def hasnoparentstatic (isinsidedict, faceindex)
def directchildren (isinsidedict, parent)
def printtree (isinsidedict, facenum)
Public Attributes
sortedfaces
isinsidedict
Detailed Description
combines overlapping faces together
Definition at line 32 of file OpenSCAD2Dgeom.py.
Constructor & Destructor Documentation
__init__()
def OpenSCAD2Dgeom.Overlappingfaces.__init__ (self, facelist)
Definition at line 34 of file OpenSCAD2Dgeom.py.
Member Function Documentation
builddepdict()
def OpenSCAD2Dgeom.Overlappingfaces.builddepdict (self)
Definition at line 58 of file OpenSCAD2Dgeom.py.
directchildren()
def OpenSCAD2Dgeom.Overlappingfaces.directchildren (isinsidedict, parent) static
Definition at line 105 of file OpenSCAD2Dgeom.py.
dofacesoverlapallverts()
def OpenSCAD2Dgeom.Overlappingfaces.dofacesoverlapallverts (bigface, smallface) static
Definition at line 43 of file OpenSCAD2Dgeom.py.
dofacesoverlapboolean()
def OpenSCAD2Dgeom.Overlappingfaces.dofacesoverlapboolean (bigface, smallface) static
Definition at line 55 of file OpenSCAD2Dgeom.py.
dofacesoverlapboundbox()
def OpenSCAD2Dgeom.Overlappingfaces.dofacesoverlapboundbox (bigface, smallface) static
Definition at line 39 of file OpenSCAD2Dgeom.py.
dofacesoverlapproximity()
def OpenSCAD2Dgeom.Overlappingfaces.dofacesoverlapproximity (bigface, smallface) static
Definition at line 50 of file OpenSCAD2Dgeom.py.
finddepth()
def OpenSCAD2Dgeom.Overlappingfaces.finddepth (dict1, faceidx, curdepth = 0) static
Definition at line 84 of file OpenSCAD2Dgeom.py.
References KDL.max().
findrootdepth()
def OpenSCAD2Dgeom.Overlappingfaces.findrootdepth (self)
Definition at line 90 of file OpenSCAD2Dgeom.py.
References OpenSCAD2Dgeom.Overlappingfaces.isinsidedict, KDL.max(), and OpenSCAD2Dgeom.Overlappingfaces.sortedfaces.
hasnoparent()
def OpenSCAD2Dgeom.Overlappingfaces.hasnoparent (self, faceindex)
Definition at line 93 of file OpenSCAD2Dgeom.py.
References OpenSCAD2Dgeom.Overlappingfaces.isinsidedict.
Referenced by OpenSCAD2Dgeom.Overlappingfaces.makefeatures(), and OpenSCAD2Dgeom.Overlappingfaces.makeshape().
hasnoparentstatic()
def OpenSCAD2Dgeom.Overlappingfaces.hasnoparentstatic (isinsidedict, faceindex) static
Definition at line 97 of file OpenSCAD2Dgeom.py.
makefeatures()
def OpenSCAD2Dgeom.Overlappingfaces.makefeatures (self, doc)
Definition at line 133 of file OpenSCAD2Dgeom.py.
References OpenSCAD2Dgeom.Overlappingfaces.hasnoparent(), OpenSCAD2Dgeom.Overlappingfaces.isinsidedict, and OpenSCAD2Dgeom.Overlappingfaces.sortedfaces.
makeshape()
def OpenSCAD2Dgeom.Overlappingfaces.makeshape (self)
Definition at line 166 of file OpenSCAD2Dgeom.py.
References OpenSCAD2Dgeom.fusefaces(), OpenSCAD2Dgeom.Overlappingfaces.hasnoparent(), OpenSCAD2Dgeom.Overlappingfaces.isinsidedict, and OpenSCAD2Dgeom.Overlappingfaces.sortedfaces.
printtree()
def OpenSCAD2Dgeom.Overlappingfaces.printtree (isinsidedict, facenum) static
Definition at line 119 of file OpenSCAD2Dgeom.py.
Member Data Documentation
isinsidedict
OpenSCAD2Dgeom.Overlappingfaces.isinsidedict
Definition at line 61 of file OpenSCAD2Dgeom.py.
Referenced by OpenSCAD2Dgeom.Overlappingfaces.findrootdepth(), OpenSCAD2Dgeom.Overlappingfaces.hasnoparent(), OpenSCAD2Dgeom.Overlappingfaces.makefeatures(), and OpenSCAD2Dgeom.Overlappingfaces.makeshape().
sortedfaces
OpenSCAD2Dgeom.Overlappingfaces.sortedfaces
Definition at line 35 of file OpenSCAD2Dgeom.py.
Referenced by OpenSCAD2Dgeom.Overlappingfaces.findrootdepth(), OpenSCAD2Dgeom.Overlappingfaces.makefeatures(), and OpenSCAD2Dgeom.Overlappingfaces.makeshape().
The documentation for this class was generated from the following file:
OpenSCAD2Dgeom.py