FreeCAD: Part::PropertyPartShape Class Reference
Part::PropertyPartShape Class Reference
#include <PropertyTopoShape.h>
Public Member Functions
PropertyPartShape ()
~PropertyPartShape () override
Getter/setter
void setValue (const TopoShape &)
set the part shape
void setValue (const TopoDS_Shape &, bool resetElementMap=true)
set the part shape
const TopoDS_Shape & getValue () const
get the part shape
const TopoShape & getShape () const
const Data::ComplexGeoData * getComplexData () const override
Modification
void setTransform (const Base::Matrix4D &rclTrf) override
Set the placement of the geometry.
Base::Matrix4D getTransform () const override
Get the placement of the geometry.
void transformGeometry (const Base::Matrix4D &rclMat) override
Transform the real shape data.
Getting basic geometric entities
Base::BoundBox3d getBoundingBox () const override
Python interface
PyObject * getPyObject () override
void setPyObject (PyObject *value) override
Public Member Functions inherited from App::PropertyComplexGeoData
PropertyComplexGeoData ()
~PropertyComplexGeoData () override
virtual bool checkElementMapVersion (const char *ver) const
Return true to signal element map version change.
Public Member Functions inherited from App::PropertyGeometry
PropertyGeometry ()
~PropertyGeometry () override
Public Member Functions inherited from App::Property
Property ()
~Property () override
const char * getName () const
bool hasName () const
std::string getFullName () const
virtual const char * getEditorName () const
Get the class name of the associated property editor item.
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void onContainerRestored ()
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
int64_t getID () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Save/restore
class Feature
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const override
void SaveDocFile (Base::Writer &writer) const override
void RestoreDocFile (Base::Reader &reader) override
App::Property * Copy () const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const App::Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
unsigned int getMemSize () const override
void getPaths (std::vector< App::ObjectIdentifier > &paths) const override
Get valid paths for this property; used by auto completer.
std::string getElementMapVersion (bool restored) const override
void resetElementMapVersion ()
void afterRestore () override
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::Property
virtual void hasSetValue ()
Gets called by all setValue() methods after the value has changed.
virtual void aboutToSetValue ()
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Detailed Description
The part shape property class.
Author
Werner Mayer
Definition at line 62 of file PropertyTopoShape.h.
Constructor & Destructor Documentation
PropertyPartShape()
PropertyPartShape::PropertyPartShape () default
Referenced by Copy().
~PropertyPartShape()
PropertyPartShape::~PropertyPartShape () override default
Member Function Documentation
afterRestore()
void PropertyPartShape::afterRestore () override virtual
Called at the beginning of Document::afterRestore()
This function is called without dependency sorting, because some types of link property can only reconstructs the linking information inside this function.
One example use case of this function is PropertyLinkSub that uses afterRestore() to parse and restore subname references, which may contain sub-object reference from external document, and there will be special mapping required during object import.
Another example is PropertyExpressionEngine which only parse the restored expression in afterRestore(). The reason, in addition to subname mapping like PropertyLinkSub, is that it can handle document name adjustment as well. It internally relies on PropertyXLink to store the external document path for external linking. When the external document is restored, its internal name may change due to name conflict with existing documents. PropertyExpressionEngine can now auto adjust external references without any problem.
Reimplemented from App::PropertyComplexGeoData.
Definition at line 407 of file PropertyTopoShape.cpp.
References Data::ComplexGeoData::getElementMapSize(), Data::ComplexGeoData::Hasher, and Data::ComplexGeoData::isRestoreFailed().
beforeSave()
void PropertyPartShape::beforeSave () const override virtual
Reimplemented from App::Property.
Definition at line 248 of file PropertyTopoShape.cpp.
References Data::ComplexGeoData::beforeSave(), App::Property::getContainer(), Data::ComplexGeoData::getElementMapSize(), Data::ComplexGeoData::Hasher, and Part::TopoShape::isNull().
Copy()
App::Property * PropertyPartShape::Copy () const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 204 of file PropertyTopoShape.cpp.
References PropertyPartShape().
getBoundingBox()
Base::BoundBox3d PropertyPartShape::getBoundingBox () const override virtual
Returns the bounding box around the underlying mesh kernel
Implements App::PropertyComplexGeoData.
Definition at line 125 of file PropertyTopoShape.cpp.
References KDL::Add(), MengerSponge::box, Part::TopoShape::getShape(), xMax, xMin, yMax, and yMin.
Referenced by PartGui::ViewProviderMirror::setEdit().
getComplexData()
const Data::ComplexGeoData * PropertyPartShape::getComplexData () const override virtual
Implements App::PropertyComplexGeoData.
Definition at line 119 of file PropertyTopoShape.cpp.
References Part::TopoShape::initCache().
getElementMapVersion()
std::string PropertyPartShape::getElementMapVersion (bool restored) const override virtual
Return the element map version
Parameters
persisted if true, return the restored element map version. Or else, return the current element map version
Reimplemented from App::PropertyComplexGeoData.
Definition at line 313 of file PropertyTopoShape.cpp.
getMemSize()
unsigned int PropertyPartShape::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence
See also
Base::Persistence
Reimplemented from App::Property.
Definition at line 229 of file PropertyTopoShape.cpp.
References Part::TopoShape::getMemSize().
getPaths()
void PropertyPartShape::getPaths (std::vector< App::ObjectIdentifier > & paths) const override virtual
Get valid paths for this property; used by auto completer.
Reimplemented from App::Property.
Definition at line 234 of file PropertyTopoShape.cpp.
References App::Property::getContainer(), App::Property::getName(), and App::ObjectIdentifier::Component::SimpleComponent().
getPyObject()
PyObject * PropertyPartShape::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 168 of file PropertyTopoShape.cpp.
References Part::TopoShape::getPyObject(), and Base::PyObjectBase::setConst().
getShape()
const TopoShape & PropertyPartShape::getShape () const
Definition at line 103 of file PropertyTopoShape.cpp.
References App::Property::getContainer(), Part::TopoShape::initCache(), Init::parent, and Data::ComplexGeoData::Tag.
Referenced by PartDesign::FeatureExtrude::buildExtrusion(), PartDesign::Body::execute(), Surface::Filling::execute(), Surface::Sections::execute(), Surface::Cut::execute(), Surface::Sewing::execute(), PartDesign::Pipe::execute(), Surface::Extend::execute(), Path::FeatureArea::execute(), PartDesign::Boolean::execute(), Drawing::FeatureProjection::execute(), TechDraw::FeatureProjection::execute(), PartDesign::Transformed::execute(), Part::Refine::execute(), Inspection::Feature::execute(), Part::Helix::execute(), Part::Spiral::execute(), PartDesign::FeatureAddSub::getAddSubShape(), PartDesign::DressUp::getAddSubShape(), PartDesign::ProfileBased::getAxis(), Fem::Constraint::getBasePoint(), Fem::Constraint::getDirection(), Part::Feature::getExportElementName(), PartDesign::ProfileBased::getFaceFromLinkSub(), Fem::Tools::getFeatureSubShape(), TechDraw::ShapeExtractor::getLocation3dFromFeat(), Fem::Constraint::getPoints(), PartDesign::ProfileBased::getProfileWires(), Part::Feature::getSubObject(), PartDesign::ProfileBased::getSupportFace(), Part::Feature::getTopoShape(), PartDesign::LinearPattern::getTransformations(), PartDesign::PolarPattern::getTransformations(), Surface::GeomFillSurface::getWire(), PartDesignGui::TaskFeaturePick::makeCopy(), Part::Feature::onBeforeChange(), Fem::ConstraintBearing::onChanged(), Part::Feature::onChanged(), FemGui::TaskFemConstraintBearing::onSelectionChanged(), FemGui::TaskFemConstraintGear::onSelectionChanged(), SurfaceGui::FillingPanel::open(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), and Sketcher::SketchObject::validateExternalLinks().
getTransform()
Base::Matrix4D PropertyPartShape::getTransform () const override virtual
Get the placement of the geometry.
Implements App::PropertyGeometry.
Definition at line 156 of file PropertyTopoShape.cpp.
References Part::TopoShape::getTransform().
getValue()
const TopoDS_Shape & PropertyPartShape::getValue () const
get the part shape
Definition at line 98 of file PropertyTopoShape.cpp.
References Part::TopoShape::getShape().
Referenced by PartGui::CrossSections::apply(), PartDesign::ShapeBinder::buildShapeFromReferences(), Fem::FemMeshShapeObject::execute(), PartDesign::Pipe::execute(), Fem::FemMeshShapeNetgenObject::execute(), Inspection::Feature::execute(), Sketcher::SketchAnalysis::getOpenVertices(), PartDesign::ProfileBased::getProfileWires(), PartDesignGui::TaskFeaturePick::makeCopy(), Part::Feature::onChanged(), Import::ExportOCAF::reallocateFreeShape(), Import::ExportOCAF::saveShape(), PartDesign::SubShapeBinder::update(), PartGui::ViewProviderMultiFuse::updateData(), PartGui::ViewProviderBoolean::updateData(), PartGui::ViewProviderCompound::updateData(), PartGui::ViewProviderFillet::updateData(), PartGui::ViewProviderMultiCommon::updateData(), PartGui::ViewProviderChamfer::updateData(), and validateSketches().
Paste()
void PropertyPartShape::Paste (const App::Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 220 of file PropertyTopoShape.cpp.
References setValue().
resetElementMapVersion()
void Part::PropertyPartShape::resetElementMapVersion () inline
Definition at line 123 of file PropertyTopoShape.h.
Restore()
void PropertyPartShape::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 319 of file PropertyTopoShape.cpp.
References App::Property::aboutToSetValue(), Data::ComplexGeoData::checkElementMapVersion(), FC_WARN, DrawingExample::file, App::Property::getContainer(), Data::ComplexGeoData::getElementMapSize(), Data::ComplexGeoData::getElementMapVersion(), App::Property::getFileName(), App::Property::getFullName(), Part::TopoShape::getShape(), Data::ComplexGeoData::Hasher, App::Property::hasSetValue(), Part::TopoShape::importBinary(), Part::TopoShape::importBrep(), Part::TopoShape::isNull(), App::Document::PartialDoc, Base::Raw, TechDrawTools.TaskFillTemplateFields::reader, Part::TopoShape::Restore(), Data::ComplexGeoData::setPersistenceFileName(), and Part::TopoShape::setShape().
RestoreDocFile()
void PropertyPartShape::RestoreDocFile (Base::Reader &) override virtual
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data. Again you have to apply for the call of this method in the Restore() call:
void PropertyMeshKernel::Restore(Base::XMLReader &reader)
{
  reader.readElement("Mesh");
  std::string file (reader.getAttribute("file") );
  if(file == "")
  {
    // read XML
    MeshCore::MeshDocXML restorer(*_pcMesh);
    restorer.Restore(reader);
  }else{
    // initiate a file read
    reader.addFile(file.c_str(),this);
 }
}
After you issued the reader.addFile() your RestoreDocFile() is called:
void PropertyMeshKernel::RestoreDocFile(Base::Reader &reader)
{
    _pcMesh->Read( reader );
}
See also
Base::Reader,Base::XMLReader
Reimplemented from Base::Persistence.
Definition at line 588 of file PropertyTopoShape.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), Base::FileInfo::hasExtension(), Part::TopoShape::importBinary(), TechDrawTools.TaskFillTemplateFields::reader, and setValue().
Save()
void PropertyPartShape::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 260 of file PropertyTopoShape.cpp.
References Base::Writer::addFile(), Base::Base64Encoded, Base::Writer::beginCharStream(), Base::Writer::endCharStream(), Part::TopoShape::exportBinary(), Part::TopoShape::exportBrep(), App::Property::getContainer(), Data::ComplexGeoData::getElementMapSize(), Data::ComplexGeoData::getElementMapVersion(), App::Property::getFileName(), Base::Writer::getMode(), Data::ComplexGeoData::Hasher, Base::Writer::ind(), Base::Writer::isForceXML(), Base::Reference< T >::isNull(), Part::TopoShape::isNull(), Base::Raw, Part::TopoShape::Save(), Data::ComplexGeoData::setPersistenceFileName(), Base::Writer::Stream(), and Dice3DS::version.
SaveDocFile()
void PropertyPartShape::SaveDocFile (Base::Writer &) const override virtual
This method is used to save large amounts of data to a binary file. Sometimes it makes no sense to write property data as XML. In case the amount of data is too big or the data type has a more effective way to save itself. In this cases it is possible to write the data in a separate file inside the document archive. In case you want do so you have to re-implement SaveDocFile(). First, you have to inform the framework in Save() that you want do so. Here an example from the Mesh module which can save a (pontetionaly big) triangle mesh:
void PropertyMeshKernel::Save (Base::Writer &writer) const
{
  if (writer.isForceXML())
  {
    writer << writer.ind() << "<Mesh>" << std::endl;
    MeshCore::MeshDocXML saver(*_pcMesh);
    saver.Save(writer);
  }else{
   writer << writer.ind() << "<Mesh file=\"" << writer.addFile("MeshKernel.bms", this) <<
"\"/>" << std::endl;
}
The writer.isForceXML() is an indication to force you to write XML. Regardless of size and effectiveness. The second part informs the Base::writer through writer.addFile("MeshKernel.bms", this) that this object wants to write a file with the given name. The method addFile() returns a unique name that then is written in the XML stream. This allows your RestoreDocFile() method to identify and read the file again. Later your SaveDocFile() method is called as many times as you issued the addFile() call:
 void
PropertyMeshKernel::SaveDocFile (Base::Writer &writer) const
{
    _pcMesh->Write( writer );
}
In this method you can simply stream your content to the file (Base::Writer inheriting from ostream).
Reimplemented from Base::Persistence.
Definition at line 562 of file PropertyTopoShape.cpp.
References Part::TopoShape::exportBinary(), Part::TopoShape::exportBrep(), App::GetApplication(), ParameterGrp::GetBool(), Base::Writer::getMode(), App::Application::GetParameterGroupByPath(), Part::TopoShape::getShape(), Part::TopoShape::setShape(), and Base::Writer::Stream().
setPyObject()
void PropertyPartShape::setPyObject (PyObject * value) override virtual
Reimplemented from Base::BaseClass.
Definition at line 176 of file PropertyTopoShape.cpp.
References Path.Log::error(), App::Property::getContainer(), Part::TopoShape::mapSubElement(), setValue(), and Data::ComplexGeoData::Tag.
setTransform()
void PropertyPartShape::setTransform (const Base::Matrix4D & rclTrf) override virtual
Set the placement of the geometry.
Implements App::PropertyGeometry.
Definition at line 151 of file PropertyTopoShape.cpp.
References Part::TopoShape::setTransform().
setValue() [1/2]
void PropertyPartShape::setValue (const TopoDS_Shape & sh, bool resetElementMap = true)
set the part shape
Definition at line 87 of file PropertyTopoShape.cpp.
References App::Property::aboutToSetValue(), App::Property::getContainer(), App::Property::hasSetValue(), Part::TopoShape::setShape(), and Data::ComplexGeoData::Tag.
setValue() [2/2]
void PropertyPartShape::setValue (const TopoShape & sh)
set the part shape
Definition at line 66 of file PropertyTopoShape.cpp.
References Dice3DS.dom3ds::tag.
Referenced by ReverseEngineeringGui::Segmentation::accept(), Import::ImpExpDxfRead::DrawingEntityCollector::AddObject(), PartGui::CrossSections::apply(), MeshPartGui::CrossSections::apply(), PartDesign::FeatureExtrude::buildExtrusion(), Part::Feature::create(), Surface::GeomFillSurface::createFace(), Part::Boolean::execute(), PartDesign::Body::execute(), Surface::Filling::execute(), PartDesign::Hole::execute(), Part::MultiCommon::execute(), Part::MultiFuse::execute(), Part::Fillet::execute(), Part::Chamfer::execute(), Part::CurveNet::execute(), Part::ImportBrep::execute(), Part::ImportIges::execute(), Surface::Cut::execute(), Surface::Sections::execute(), Part::Face::execute(), Part::FeatureGeometrySet::execute(), PartDesign::Loft::execute(), Part::ImportStep::execute(), Part::Compound::execute(), PartDesign::Fillet::execute(), Part::Box::execute(), PartDesign::Helix::execute(), Part::Circle::execute(), Part::Mirroring::execute(), Part::RuledSurface::execute(), Surface::Sewing::execute(), PartDesign::Thickness::execute(), Part::Vertex::execute(), PartDesign::Chamfer::execute(), PartDesign::Pipe::execute(), Surface::Extend::execute(), Part::Offset::execute(), Path::FeatureArea::execute(), Part::Revolution::execute(), Surface::FeatureBlendCurve::execute(), PartDesign::Boolean::execute(), Part::Offset2D::execute(), PartDesign::Revolution::execute(), PartDesign::Groove::execute(), Part::Extrusion::execute(), Drawing::FeatureProjection::execute(), TechDraw::FeatureProjection::execute(), Part::Loft::execute(), PartDesign::FeaturePrimitive::execute(), Part::Scale::execute(), PartDesign::ShapeBinder::execute(), Part::Line::execute(), PartDesign::Transformed::execute(), Part::Sweep::execute(), Part::Plane::execute(), Part::Sphere::execute(), Part::Thickness::execute(), Part::Ellipsoid::execute(), Part::Refine::execute(), Part::Cylinder::execute(), Part::Reverse::execute(), Part::Prism::execute(), Part::RegularPolygon::execute(), Part::Cone::execute(), Part::Torus::execute(), Part::Helix::execute(), Part::Spiral::execute(), Part::Wedge::execute(), Part::Ellipse::execute(), PartDesign::DressUp::getAddSubShape(), Part::ImportIgesParts(), Part::ImportStepParts(), Import::ImportOCAF2::loadShapes(), PartDesignGui::TaskFeaturePick::makeCopy(), PartDesign::DressUp::onChanged(), Part::Feature::onChanged(), Paste(), RestoreDocFile(), PartDesign::SubShapeBinder::setLinks(), setPyObject(), and PartDesign::SubShapeBinder::update().
transformGeometry()
void PropertyPartShape::transformGeometry (const Base::Matrix4D & rclMat) override virtual
Transform the real shape data.
Implements App::PropertyComplexGeoData.
Definition at line 161 of file PropertyTopoShape.cpp.
References App::Property::aboutToSetValue(), App::Property::hasSetValue(), and Part::TopoShape::transformGeometry().
Friends And Related Function Documentation
Feature
friend class Feature friend
Definition at line 127 of file PropertyTopoShape.h.
The documentation for this class was generated from the following files:
PropertyTopoShape.h
PropertyTopoShape.cpp