FreeCAD: TechDraw::Circle Class Reference
TechDraw::Circle Class Reference
#include <Geometry.h>
Public Member Functions
Circle ()
Circle (const TopoDS_Edge &e)
Circle (Base::Vector3d center, double radius)
~Circle () override=default
std::string toString () const override
void Save (Base::Writer &w) const override
void Restore (Base::XMLReader &r) override
Public Member Functions inherited from TechDraw::BaseGeom
BaseGeom ()
virtual ~BaseGeom ()=default
std::vector< Base::Vector3d > findEndPoints ()
Base::Vector3d getStartPoint ()
Base::Vector3d getEndPoint ()
Base::Vector3d getMidPoint ()
std::vector< Base::Vector3d > getQuads ()
double minDist (Base::Vector3d p)
Base::Vector3d nearPoint (Base::Vector3d p)
Base::Vector3d nearPoint (const BaseGeomPtr p)
find point on me nearest to p
bool closed ()
virtual BaseGeomPtr copy ()
std::string dump ()
std::vector< Base::Vector3d > intersection (TechDraw::BaseGeomPtr geom2)
boost::uuids::uuid getTag () const
virtual std::string getTagAsString () const
std::string geomTypeName ()
BaseGeomPtr inverted ()
GeomType getGeomType ()
void setGeomType (GeomType type)
edgeClass getClassOfEdge ()
void setClassOfEdge (edgeClass newClass)
bool getHlrVisible ()
void setHlrVisible (bool state)
bool getReversed ()
void setReversed (bool state)
int getRef3d ()
void setRef3d (int ref)
TopoDS_Edge getOCCEdge ()
void setOCCEdge (TopoDS_Edge newEdge)
bool getCosmetic ()
void setCosmetic (bool state)
int source ()
void source (int s)
int sourceIndex ()
void sourceIndex (int si)
std::string getCosmeticTag ()
void setCosmeticTag (std::string t)
Part::TopoShape asTopoShape (double scale=1.0)
virtual double getStartAngle ()
virtual double getEndAngle ()
virtual bool clockwiseAngle ()
virtual void clockwiseAngle (bool direction)
Public Attributes
Base::Vector3d center
double radius
Additional Inherited Members
Static Public Member Functions inherited from TechDraw::BaseGeom
static BaseGeomPtr baseFactory (TopoDS_Edge edge, bool isCosmetic=false)
Convert 1 OCC edge into 1 BaseGeom (static factory method)
static bool validateEdge (TopoDS_Edge edge)
static TopoDS_Edge completeEdge (const TopoDS_Edge &edge)
Protected Member Functions inherited from TechDraw::BaseGeom
void createNewTag ()
Protected Attributes inherited from TechDraw::BaseGeom
GeomType geomType
ExtractionType extractType
edgeClass classOfEdge
bool hlrVisible
bool reversed
int ref3D
TopoDS_Edge occEdge
bool cosmetic
int m_source
int m_sourceIndex
std::string cosmeticTag
boost::uuids::uuid tag
Detailed Description
Definition at line 179 of file TechDraw/App/Geometry.h.
Constructor & Destructor Documentation
Circle() [1/3]
TechDraw::Circle::Circle ()
Circle() [2/3]
Circle::Circle (const TopoDS_Edge & e) explicit
Definition at line 754 of file TechDraw/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, center, TechDraw::CIRCLE, SCL.SimpleDataTypes::e, TechDraw::BaseGeom::geomType, TechDraw::BaseGeom::occEdge, buildPsets::p, and radius.
Circle() [3/3]
TechDraw::Circle::Circle (Base::Vector3d center, double radius)
~Circle()
TechDraw::Circle::~Circle () override default
Member Function Documentation
Restore()
void TechDraw::Circle::Restore (Base::XMLReader & r) override virtual
Reimplemented from TechDraw::BaseGeom.
Reimplemented in TechDraw::AOC.
Referenced by TechDraw::AOC::Restore().
Save()
void Circle::Save (Base::Writer & w) const override virtual
Reimplemented from TechDraw::BaseGeom.
Reimplemented in TechDraw::AOC.
Definition at line 777 of file TechDraw/App/Geometry.cpp.
References center, Base::Writer::ind(), radius, TechDraw::BaseGeom::Save(), Base::Writer::Stream(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by TechDraw::AOC::Save().
toString()
std::string Circle::toString () const override virtual
Reimplemented from TechDraw::BaseGeom.
Reimplemented in TechDraw::AOC.
Definition at line 766 of file TechDraw/App/Geometry.cpp.
References center, radius, TechDraw::BaseGeom::toString(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by TechDraw::AOC::toString().
Member Data Documentation
center
Base::Vector3d TechDraw::Circle::center
Definition at line 192 of file TechDraw/App/Geometry.h.
Referenced by TechDraw::AOC::AOC(), Circle(), Path.Dressup.Gui.AxisMap.ObjectDressup::execute(), Path.Dressup.Gui.AxisMap.ObjectDressup::onChanged(), Save(), and toString().
radius
double TechDraw::Circle::radius
Definition at line 193 of file TechDraw/App/Geometry.h.
Referenced by TechDraw::AOC::AOC(), Path.Op.PocketBase.ObjectPocket::areaOpAreaParams(), Path.Op.Profile.ObjectProfile::areaOpAreaParams(), Path.Op.PocketBase.ObjectPocket::areaOpPathParams(), Path.Op.Profile.ObjectProfile::areaOpPathParams(), Circle(), Save(), and toString().
The documentation for this class was generated from the following files:
TechDraw/App/Geometry.h
TechDraw/App/Geometry.cpp