FreeCAD: TechDraw::pointPair Class Reference
TechDraw::pointPair Class Reference
#include <DimensionGeometry.h>
Public Member Functions
pointPair ()=default
pointPair (const Base::Vector3d &point0, const Base::Vector3d &point1)
pointPair (const Base::Vector3d &point0, const Base::Vector3d &point1, const Base::Vector3d &extensionPoint0, const Base::Vector3d &extensionPoint1)
pointPair (const pointPair &pp)
pointPair & operator= (const pointPair &pp)
Base::Vector3d first () const
void first (Base::Vector3d newFirst)
Base::Vector3d second () const
void second (Base::Vector3d newSecond)
Base::Vector3d extensionLineFirst () const
void overrideFirst (Base::Vector3d newFirst)
Base::Vector3d extensionLineSecond () const
void overrideSecond (Base::Vector3d newSecond)
void setExtensionLine (const pointPair &pp)
void move (const Base::Vector3d &offset)
void project (const DrawViewPart *dvp)
void mapToPage (const DrawViewPart *dvp)
void invertY ()
void scale (double factor)
void dump (const std::string &text) const
pointPair toCanonicalForm (DrawViewPart *dvp) const
pointPair toDisplayForm (DrawViewPart *dvp) const
Detailed Description
Definition at line 57 of file DimensionGeometry.h.
Constructor & Destructor Documentation
pointPair() [1/4]
TechDraw::pointPair::pointPair () default
pointPair() [2/4]
TechDraw::pointPair::pointPair (const Base::Vector3d & point0, const Base::Vector3d & point1) inline
Definition at line 61 of file DimensionGeometry.h.
pointPair() [3/4]
TechDraw::pointPair::pointPair (const Base::Vector3d & point0, const Base::Vector3d & point1, const Base::Vector3d & extensionPoint0, const Base::Vector3d & extensionPoint1) inline
Definition at line 65 of file DimensionGeometry.h.
pointPair() [4/4]
pointPair::pointPair (const pointPair & pp)
Definition at line 42 of file DimensionGeometry.cpp.
References extensionLineFirst(), extensionLineSecond(), first(), overrideFirst(), overrideSecond(), and second().
Member Function Documentation
dump()
void pointPair::dump (const std::string & text) const
Definition at line 114 of file DimensionGeometry.cpp.
References Base::Console(), first(), TechDraw::DrawUtil::formatVector(), Base::ConsoleSingleton::Message(), and second().
extensionLineFirst()
Base::Vector3d TechDraw::pointPair::extensionLineFirst () const inline
Definition at line 89 of file DimensionGeometry.h.
Referenced by TechDrawGui::QGIViewDimension::drawDistance(), and pointPair().
extensionLineSecond()
Base::Vector3d TechDraw::pointPair::extensionLineSecond () const inline
Definition at line 91 of file DimensionGeometry.h.
Referenced by TechDrawGui::QGIViewDimension::drawDistance(), and pointPair().
first() [1/2]
Base::Vector3d TechDraw::pointPair::first () const inline
Definition at line 84 of file DimensionGeometry.h.
Referenced by TechDraw::anglePoints::anglePoints(), TechDraw::arcPoints::arcPoints(), TechDraw::DrawViewDimension::arcPointsFromBaseGeom(), TechDraw::DrawViewDimension::arcPointsFromEdge(), TDHandlerDimension::createDistanceDimension(), TechDrawGui::QGIViewDimension::drawDistance(), TechDrawGui::QGIViewDimension::drawRadius(), dump(), TechDraw::arcPoints::dump(), execCascadeHorizDimension(), execCascadeObliqueDimension(), execCascadeVertDimension(), execCreateHorizChainDimension(), execCreateHorizChamferDimension(), execCreateHorizCoordDimension(), execCreateVertChainDimension(), execCreateVertChamferDimension(), execCreateVertCoordDimension(), execPosHorizChainDimension(), execPosObliqueChainDimension(), execPosVertChainDimension(), TDHandlerDimension::getDimPositionToBe(), TechDraw::DrawViewDimension::getProjectedDimValue(), TechDrawGui::makeArcLengthDimension(), TechDrawGui::makeObliqueChainDimension(), TechDrawGui::makeObliqueCoordDimension(), TechDraw::arcPoints::mapToPage(), TDHandlerDimension::mouseMoveEvent(), TechDraw::arcPoints::move(), pointPair(), positionDimText(), TechDraw::arcPoints::project(), setExtensionLine(), TechDrawGui::QGIDatumLabel::snapPosition(), TDHandlerDimension::updateChainDistanceType(), TDHandlerDimension::updateDistanceType(), and TDHandlerDimension::updateExtentDistanceType().
first() [2/2]
void TechDraw::pointPair::first (Base::Vector3d newFirst) inline
Definition at line 85 of file DimensionGeometry.h.
invertY()
void pointPair::invertY ()
Definition at line 108 of file DimensionGeometry.cpp.
References TechDraw::DrawUtil::invertY().
Referenced by TechDraw::DrawViewDimension::getProjectedDimValue(), TechDraw::anglePoints::invertY(), and TechDraw::arcPoints::invertY().
mapToPage()
void pointPair::mapToPage (const DrawViewPart * dvp)
Definition at line 94 of file DimensionGeometry.cpp.
References TechDraw::DrawViewPart::getRotatedCS(), TechDraw::DrawUtil::togp_Vec(), and TechDraw::DrawUtil::toVector3d().
Referenced by TechDraw::anglePoints::mapToPage().
move()
void pointPair::move (const Base::Vector3d & offset)
Definition at line 57 of file DimensionGeometry.cpp.
Referenced by TechDraw::DrawViewDimension::getPointsEdgeVert(), TechDraw::DrawViewDimension::getPointsOneEdge(), TechDraw::DrawViewDimension::getPointsTwoEdges(), TechDraw::DrawViewDimension::getPointsTwoVerts(), and TechDraw::anglePoints::move().
operator=()
pointPair& TechDraw::pointPair::operator= (const pointPair & pp) inline
Definition at line 76 of file DimensionGeometry.h.
overrideFirst()
void TechDraw::pointPair::overrideFirst (Base::Vector3d newFirst) inline
Definition at line 90 of file DimensionGeometry.h.
Referenced by pointPair(), and setExtensionLine().
overrideSecond()
void TechDraw::pointPair::overrideSecond (Base::Vector3d newSecond) inline
Definition at line 92 of file DimensionGeometry.h.
Referenced by pointPair(), and setExtensionLine().
project()
void pointPair::project (const DrawViewPart * dvp)
Definition at line 75 of file DimensionGeometry.cpp.
References TechDraw::DrawView::getScale(), and TechDraw::DrawViewPart::projectPoint().
Referenced by TechDraw::DrawViewDimension::getPointsEdgeVert(), TechDraw::DrawViewDimension::getPointsOneEdge(), TechDraw::DrawViewDimension::getPointsTwoEdges(), TechDraw::DrawViewDimension::getPointsTwoVerts(), and TechDraw::anglePoints::project().
scale()
void pointPair::scale (double factor)
Definition at line 66 of file DimensionGeometry.cpp.
Referenced by TechDraw::DrawViewDimension::getProjectedDimValue().
second() [1/2]
Base::Vector3d TechDraw::pointPair::second () const inline
Definition at line 86 of file DimensionGeometry.h.
Referenced by TechDraw::anglePoints::anglePoints(), TechDraw::arcPoints::arcPoints(), TechDraw::DrawViewDimension::arcPointsFromBaseGeom(), TechDraw::DrawViewDimension::arcPointsFromEdge(), TDHandlerDimension::createDistanceDimension(), TechDrawGui::QGIViewDimension::drawDistance(), TechDrawGui::QGIViewDimension::drawRadius(), dump(), TechDraw::arcPoints::dump(), execCascadeHorizDimension(), execCascadeObliqueDimension(), execCascadeVertDimension(), execCreateHorizChainDimension(), execCreateHorizChamferDimension(), execCreateHorizCoordDimension(), execCreateVertChainDimension(), execCreateVertChamferDimension(), execCreateVertCoordDimension(), execPosHorizChainDimension(), execPosObliqueChainDimension(), execPosVertChainDimension(), TechDraw::DrawViewDimension::getProjectedDimValue(), TechDrawGui::makeArcLengthDimension(), TechDrawGui::makeObliqueChainDimension(), TechDrawGui::makeObliqueCoordDimension(), TechDraw::arcPoints::mapToPage(), TDHandlerDimension::mouseMoveEvent(), TechDraw::arcPoints::move(), pointPair(), positionDimText(), TechDraw::arcPoints::project(), setExtensionLine(), TechDrawGui::QGIDatumLabel::snapPosition(), TDHandlerDimension::updateChainDistanceType(), TDHandlerDimension::updateDistanceType(), and TDHandlerDimension::updateExtentDistanceType().
second() [2/2]
void TechDraw::pointPair::second (Base::Vector3d newSecond) inline
Definition at line 87 of file DimensionGeometry.h.
setExtensionLine()
void pointPair::setExtensionLine (const pointPair & pp)
Definition at line 51 of file DimensionGeometry.cpp.
References first(), overrideFirst(), overrideSecond(), and second().
toCanonicalForm()
pointPair pointPair::toCanonicalForm (DrawViewPart * dvp) const
return unscaled, unrotated version of this pointPair. caller is responsible for for ensuring this pointPair is in scaled, rotated form before calling this method.
Definition at line 123 of file DimensionGeometry.cpp.
References TechDraw::CosmeticVertex::makeCanonicalPoint(), and result.
Referenced by TechDraw::anglePoints::toCanonicalForm(), and TechDraw::arcPoints::toCanonicalForm().
toDisplayForm()
pointPair pointPair::toDisplayForm (DrawViewPart * dvp) const
return scaled and rotated version of this pointPair. caller is responsible for for ensuring this pointPair is in canonical form before calling this method.
Definition at line 136 of file DimensionGeometry.cpp.
References TechDraw::DrawView::getScale(), App::PropertyQuantity::getValue(), result, TechDraw::DrawView::Rotation, and Base::toRadians().
Referenced by TechDraw::anglePoints::toDisplayForm(), and TechDraw::arcPoints::toDisplayForm().
The documentation for this class was generated from the following files:
DimensionGeometry.h
DimensionGeometry.cpp