FreeCAD: ModelRefine::FaceUniter Class Reference
ModelRefine::FaceUniter Class Reference
#include <modelRefine.h>
Public Member Functions
FaceUniter (const TopoDS_Shell &shellIn)
bool process ()
const TopoDS_Shell & getShell () const
bool isModified ()
const std::vector< ShapePairType > & getModifiedShapes () const
const ShapeVectorType & getDeletedShapes () const
Detailed Description
Definition at line 179 of file modelRefine.h.
Constructor & Destructor Documentation
FaceUniter()
FaceUniter::FaceUniter (const TopoDS_Shell & shellIn)
Definition at line 1024 of file modelRefine.cpp.
Member Function Documentation
getDeletedShapes()
const ShapeVectorType& ModelRefine::FaceUniter::getDeletedShapes () const inline
Definition at line 190 of file modelRefine.h.
getModifiedShapes()
const std::vector<ShapePairType>& ModelRefine::FaceUniter::getModifiedShapes () const inline
Definition at line 188 of file modelRefine.h.
getShell()
const TopoDS_Shell& ModelRefine::FaceUniter::getShell () const inline
Definition at line 186 of file modelRefine.h.
Referenced by Part::BRepBuilderAPI_RefineModel::Build(), and Part::TopoShape::removeSplitter().
isModified()
bool ModelRefine::FaceUniter::isModified () inline
Definition at line 187 of file modelRefine.h.
Referenced by Part::BRepBuilderAPI_RefineModel::Build(), and Part::TopoShape::removeSplitter().
process()
bool FaceUniter::process ()
Definition at line 1029 of file modelRefine.cpp.
References ModelRefine::FaceTypeSplitter::addShell(), ArchCommands::check(), collectConicEdges(), SCL.SimpleDataTypes::f, ModelRefine::getBSplineObject(), ModelRefine::getCylinderObject(), ModelRefine::FaceAdjacencySplitter::getGroup(), ModelRefine::FaceEqualitySplitter::getGroup(), ModelRefine::FaceAdjacencySplitter::getGroupCount(), ModelRefine::FaceEqualitySplitter::getGroupCount(), ModelRefine::getPlaneObject(), ModelRefine::FaceTypeSplitter::getTypedFaceVector(), ModelRefine::FaceTypeSplitter::registerType(), ModelRefine::removeFaces(), ModelRefine::FaceTypeSplitter::split(), ModelRefine::FaceAdjacencySplitter::split(), and ModelRefine::FaceEqualitySplitter::split().
Referenced by Part::BRepBuilderAPI_RefineModel::Build(), and Part::TopoShape::removeSplitter().
The documentation for this class was generated from the following files:
modelRefine.h
modelRefine.cpp