FreeCAD: Gui::SoVRMLAction Class Reference
Gui::SoVRMLAction Class Reference
#include <SoFCUnifiedSelection.h>
Public Member Functions
SoVRMLAction ()
~SoVRMLAction () override
void setOverrideMode (SbBool)
SbBool isOverrideMode () const
Static Public Member Functions
static void initClass ()
Detailed Description
Author
Werner Mayer
Definition at line 466 of file SoFCUnifiedSelection.h.
Constructor & Destructor Documentation
SoVRMLAction()
SoVRMLAction::SoVRMLAction ()
Definition at line 974 of file SoFCUnifiedSelection.cpp.
~SoVRMLAction()
SoVRMLAction::~SoVRMLAction () override default
Member Function Documentation
initClass()
void SoVRMLAction::initClass () static
Definition at line 951 of file SoFCUnifiedSelection.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
isOverrideMode()
SbBool SoVRMLAction::isOverrideMode () const
Definition at line 986 of file SoFCUnifiedSelection.cpp.
setOverrideMode()
void SoVRMLAction::setOverrideMode (SbBool on)
Definition at line 981 of file SoFCUnifiedSelection.cpp.
Referenced by Gui::SoFCDB::writeToVRML(), and Gui::SoFCDB::writeToX3D().
The documentation for this class was generated from the following files:
SoFCUnifiedSelection.h
SoFCUnifiedSelection.cpp