FreeCAD: Wm4::DistSegment3Triangle3< Real > Class Template Reference
Wm4::DistSegment3Triangle3< Real > Class Template Reference
#include <Wm4DistSegment3Triangle3.h>
Public Member Functions
DistSegment3Triangle3 (const Segment3< Real > &rkSegment, const Triangle3< Real > &rkTriangle)
const Segment3< Real > & GetSegment () const
const Triangle3< Real > & GetTriangle () const
virtual Real Get ()
virtual Real GetSquared ()
virtual Real Get (Real fT, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
virtual Real GetSquared (Real fT, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
Real GetSegmentParameter () const
Real GetTriangleBary (int i) const
Public Member Functions inherited from Wm4::Distance< Real, Vector3< Real > >
virtual ~Distance ()
virtual Real Get (Real fTMin, Real fTMax, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
virtual Real GetSquared (Real fTMin, Real fTMax, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
virtual Real GetDerivative (Real fT, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
virtual Real GetDerivativeSquared (Real fT, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
void SetDifferenceStep (Real fDifferenceStep)
Real GetDifferenceStep () const
Real GetContactTime () const
const Vector3< Real > & GetClosestPoint0 () const
const Vector3< Real > & GetClosestPoint1 () const
bool HasMultipleClosestPoints0 () const
bool HasMultipleClosestPoints1 () const
Additional Inherited Members
Public Attributes inherited from Wm4::Distance< Real, Vector3< Real > >
int MaximumIterations
Real ZeroThreshold
Protected Member Functions inherited from Wm4::Distance< Real, Vector3< Real > >
Distance ()
Protected Attributes inherited from Wm4::Distance< Real, Vector3< Real > >
Real m_fContactTime
Vector3< Real > m_kClosestPoint0
Vector3< Real > m_kClosestPoint1
bool m_bHasMultipleClosestPoints0
bool m_bHasMultipleClosestPoints1
Real m_fDifferenceStep
Real m_fInvTwoDifferenceStep
Detailed Description
template<class Real>
class Wm4::DistSegment3Triangle3< Real >
Definition at line 29 of file Wm4DistSegment3Triangle3.h.
Constructor & Destructor Documentation
DistSegment3Triangle3()
template<class Real > Wm4::DistSegment3Triangle3< Real >::DistSegment3Triangle3 (const Segment3< Real > & rkSegment, const Triangle3< Real > & rkTriangle)
Definition at line 26 of file Wm4DistSegment3Triangle3.cpp.
Member Function Documentation
Get() [1/2]
template<class Real > Real Wm4::DistSegment3Triangle3< Real >::Get virtual
Implements Wm4::Distance< Real, Vector3< Real > >.
Definition at line 47 of file Wm4DistSegment3Triangle3.cpp.
References Wm4::Math< Real >::Sqrt().
Referenced by MeshCore::MeshGeomFacet::DistanceToLineSegment(), and Wm4::DistSegment3Triangle3< Real >::Get().
Get() [2/2]
template<class Real > Real Wm4::DistSegment3Triangle3< Real >::Get (Real fT, const Vector3< Real > & rkVelocity0, const Vector3< Real > & rkVelocity1) virtual
Implements Wm4::Distance< Real, Vector3< Real > >.
Definition at line 101 of file Wm4DistSegment3Triangle3.cpp.
References Wm4::DistSegment3Triangle3< Real >::Get().
GetSegment()
template<class Real > const Segment3< Real > & Wm4::DistSegment3Triangle3< Real >::GetSegment
Definition at line 35 of file Wm4DistSegment3Triangle3.cpp.
GetSegmentParameter()
template<class Real > Real Wm4::DistSegment3Triangle3< Real >::GetSegmentParameter
Definition at line 129 of file Wm4DistSegment3Triangle3.cpp.
GetSquared() [1/2]
template<class Real > Real Wm4::DistSegment3Triangle3< Real >::GetSquared virtual
Implements Wm4::Distance< Real, Vector3< Real > >.
Definition at line 54 of file Wm4DistSegment3Triangle3.cpp.
References Wm4::Distance< Real, Vector3< Real > >::GetClosestPoint0(), Wm4::Distance< Real, Vector3< Real > >::GetClosestPoint1(), Wm4::DistLine3Triangle3< Real >::GetLineParameter(), Wm4::DistVector3Triangle3< Real >::GetSquared(), Wm4::DistLine3Triangle3< Real >::GetSquared(), Wm4::DistVector3Triangle3< Real >::GetTriangleBary(), and Wm4::DistLine3Triangle3< Real >::GetTriangleBary().
Referenced by Wm4::DistSegment3Triangle3< Real >::GetSquared().
GetSquared() [2/2]
template<class Real > Real Wm4::DistSegment3Triangle3< Real >::GetSquared (Real fT, const Vector3< Real > & rkVelocity0, const Vector3< Real > & rkVelocity1) virtual
Implements Wm4::Distance< Real, Vector3< Real > >.
Definition at line 115 of file Wm4DistSegment3Triangle3.cpp.
References Wm4::DistSegment3Triangle3< Real >::GetSquared().
GetTriangle()
template<class Real > const Triangle3< Real > & Wm4::DistSegment3Triangle3< Real >::GetTriangle
Definition at line 41 of file Wm4DistSegment3Triangle3.cpp.
GetTriangleBary()
template<class Real > Real Wm4::DistSegment3Triangle3< Real >::GetTriangleBary (int i) const
Definition at line 135 of file Wm4DistSegment3Triangle3.cpp.
References SplineSurface::i.
The documentation for this class was generated from the following files:
Wm4DistSegment3Triangle3.h
Wm4DistSegment3Triangle3.cpp