FreeCAD: TechDrawGui::TaskRestoreLines Class Reference
TechDrawGui::TaskRestoreLines Class Reference
#include <TaskLineDecor.h>
Public Member Functions
TaskRestoreLines (TechDraw::DrawViewPart *partFeat, TechDrawGui::TaskLineDecor *parent)
~TaskRestoreLines () override
virtual bool accept ()
virtual bool reject ()
Protected Slots
void onAllPressed ()
void onGeometryPressed ()
void onCosmeticPressed ()
void onCenterPressed ()
Protected Member Functions
void changeEvent (QEvent *e) override
void initUi ()
int countInvisibleLines ()
int countInvisibleGeoms ()
int countInvisibleCosmetics ()
int countInvisibleCenters ()
void restoreInvisibleLines ()
void restoreInvisibleGeoms ()
void restoreInvisibleCosmetics ()
void restoreInvisibleCenters ()
Detailed Description
Definition at line 96 of file TaskLineDecor.h.
Constructor & Destructor Documentation
TaskRestoreLines()
TaskRestoreLines::TaskRestoreLines (TechDraw::DrawViewPart * partFeat, TechDrawGui::TaskLineDecor * parent)
Definition at line 281 of file TaskLineDecor.cpp.
References draftgeoutils.intersections::connect(), initUi(), onAllPressed(), onCenterPressed(), onCosmeticPressed(), and onGeometryPressed().
~TaskRestoreLines()
TaskRestoreLines::~TaskRestoreLines () override
Definition at line 297 of file TaskLineDecor.cpp.
Member Function Documentation
accept()
bool TaskRestoreLines::accept () virtual
Definition at line 430 of file TaskLineDecor.cpp.
changeEvent()
void TaskRestoreLines::changeEvent (QEvent * e) override protected
Definition at line 442 of file TaskLineDecor.cpp.
References SCL.SimpleDataTypes::e.
countInvisibleCenters()
int TaskRestoreLines::countInvisibleCenters () protected
Definition at line 374 of file TaskLineDecor.cpp.
References SCL.SimpleDataTypes::c, TechDraw::CosmeticExtension::CenterLines, and TechDraw::PropertyCenterLineList::getValues().
Referenced by countInvisibleLines(), and initUi().
countInvisibleCosmetics()
int TaskRestoreLines::countInvisibleCosmetics () protected
Definition at line 362 of file TaskLineDecor.cpp.
References SCL.SimpleDataTypes::c, TechDraw::CosmeticExtension::CosmeticEdges, and TechDraw::PropertyCosmeticEdgeList::getValues().
Referenced by countInvisibleLines(), and initUi().
countInvisibleGeoms()
int TaskRestoreLines::countInvisibleGeoms () protected
Definition at line 350 of file TaskLineDecor.cpp.
References toolbit-attributes::g, TechDraw::CosmeticExtension::GeomFormats, and TechDraw::PropertyGeomFormatList::getValues().
Referenced by countInvisibleLines(), and initUi().
countInvisibleLines()
int TaskRestoreLines::countInvisibleLines () protected
Definition at line 341 of file TaskLineDecor.cpp.
References countInvisibleCenters(), countInvisibleCosmetics(), countInvisibleGeoms(), and result.
Referenced by initUi(), onCenterPressed(), onCosmeticPressed(), and onGeometryPressed().
initUi()
void TaskRestoreLines::initUi () protected
Definition at line 301 of file TaskLineDecor.cpp.
References countInvisibleCenters(), countInvisibleCosmetics(), countInvisibleGeoms(), and countInvisibleLines().
Referenced by TaskRestoreLines().
onAllPressed
void TaskRestoreLines::onAllPressed () protected slot
Definition at line 309 of file TaskLineDecor.cpp.
References onCenterPressed(), onCosmeticPressed(), and onGeometryPressed().
Referenced by TaskRestoreLines().
onCenterPressed
void TaskRestoreLines::onCenterPressed () protected slot
Definition at line 333 of file TaskLineDecor.cpp.
References countInvisibleLines(), and restoreInvisibleCenters().
Referenced by onAllPressed(), and TaskRestoreLines().
onCosmeticPressed
void TaskRestoreLines::onCosmeticPressed () protected slot
Definition at line 325 of file TaskLineDecor.cpp.
References countInvisibleLines(), and restoreInvisibleCosmetics().
Referenced by onAllPressed(), and TaskRestoreLines().
onGeometryPressed
void TaskRestoreLines::onGeometryPressed () protected slot
Definition at line 317 of file TaskLineDecor.cpp.
References countInvisibleLines(), and restoreInvisibleGeoms().
Referenced by onAllPressed(), and TaskRestoreLines().
reject()
bool TaskRestoreLines::reject () virtual
Definition at line 436 of file TaskLineDecor.cpp.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action().
restoreInvisibleCenters()
void TaskRestoreLines::restoreInvisibleCenters () protected
Definition at line 417 of file TaskLineDecor.cpp.
References TechDrawGui::TaskLineDecor::apply(), SCL.SimpleDataTypes::c, TechDraw::CosmeticExtension::CenterLines, TechDraw::PropertyCenterLineList::getValues(), and TechDraw::PropertyCenterLineList::setValues().
Referenced by onCenterPressed(), and restoreInvisibleLines().
restoreInvisibleCosmetics()
void TaskRestoreLines::restoreInvisibleCosmetics () protected
Definition at line 405 of file TaskLineDecor.cpp.
References TechDrawGui::TaskLineDecor::apply(), SCL.SimpleDataTypes::c, TechDraw::CosmeticExtension::CosmeticEdges, TechDraw::PropertyCosmeticEdgeList::getValues(), and TechDraw::PropertyCosmeticEdgeList::setValues().
Referenced by onCosmeticPressed(), and restoreInvisibleLines().
restoreInvisibleGeoms()
void TaskRestoreLines::restoreInvisibleGeoms () protected
Definition at line 393 of file TaskLineDecor.cpp.
References TechDrawGui::TaskLineDecor::apply(), toolbit-attributes::g, TechDraw::CosmeticExtension::GeomFormats, TechDraw::PropertyGeomFormatList::getValues(), and TechDraw::PropertyGeomFormatList::setValues().
Referenced by onGeometryPressed(), and restoreInvisibleLines().
restoreInvisibleLines()
void TaskRestoreLines::restoreInvisibleLines () protected
Definition at line 386 of file TaskLineDecor.cpp.
References restoreInvisibleCenters(), restoreInvisibleCosmetics(), and restoreInvisibleGeoms().
The documentation for this class was generated from the following files:
TaskLineDecor.h
TaskLineDecor.cpp