FreeCAD: Part::FaceMaker Class Reference
Part::FaceMaker Class Reference abstract
FaceMaker class is the base class for implementing various "smart" face making routines. This was created to address the problem of multiple private implementations of making faces with holes, which are quite complex. The two most important facemaking routines then was: one in Part Extrude, and one in PartDesign (there, it is used in every sketch-based feature). Plus, another one (new) was needed for filling 2D offset.
#include <FaceMaker.h>
Public Member Functions
FaceMaker ()
~FaceMaker () override
void addTopoShape (const TopoShape &s)
void useTopoCompound (const TopoShape &comp)
const TopoShape & getTopoShape () const
const TopoShape & TopoFace () const
virtual void addWire (const TopoDS_Wire &w)
virtual void addShape (const TopoDS_Shape &sh)
addShape: add another wire, edge, or compound. If compound is added, its internals will be treated as isolated from the rest, and the compounding structure of result will follow.
virtual void useCompound (const TopoDS_Compound &comp)
useCompound: add children of compound to the FaceMaker. Note that this is different from addShape(comp) - structure is lost. The compound is NOT expanded recursively.
virtual void setPlane (const gp_Pln &)
virtual const TopoDS_Face & Face ()
Face: returns the face (result). If result is not a single face, throws Base::TypeError. (hint: use .Shape() instead)
void Build () override
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static std::unique_ptr< FaceMaker > ConstructFromType (const char *className)
static std::unique_ptr< FaceMaker > ConstructFromType (Base::Type type)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes
const char * MyOp = 0
App::StringHasherRef MyHasher
Protected Member Functions
virtual void Build_Essence ()=0
Build_Essence: build routine that can assume there is no nesting.
void postBuild ()
Static Protected Member Functions
static void throwNotImplemented ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes
std::vector< TopoShape > mySourceShapes
std::vector< TopoDS_Wire > myWires
std::vector< TopoShape > myTopoWires
std::vector< TopoDS_Compound > myCompounds
std::vector< TopoDS_Shape > myShapesToReturn
std::vector< TopoDS_Shape > myInputFaces
TopoShape myTopoShape
int minElementNames = 1
Detailed Description
FaceMaker class is the base class for implementing various "smart" face making routines. This was created to address the problem of multiple private implementations of making faces with holes, which are quite complex. The two most important facemaking routines then was: one in Part Extrude, and one in PartDesign (there, it is used in every sketch-based feature). Plus, another one (new) was needed for filling 2D offset.
Definition at line 71 of file FaceMaker.h.
Constructor & Destructor Documentation
FaceMaker()
Part::FaceMaker::FaceMaker () inline
Definition at line 97 of file FaceMaker.h.
~FaceMaker()
Part::FaceMaker::~FaceMaker () inline override
Definition at line 98 of file FaceMaker.h.
Member Function Documentation
addShape()
void Part::FaceMaker::addShape (const TopoDS_Shape & sh) virtual
addShape: add another wire, edge, or compound. If compound is added, its internals will be treated as isolated from the rest, and the compounding structure of result will follow.
Parameters
sh
Definition at line 49 of file FaceMaker.cpp.
References addTopoShape().
addTopoShape()
void Part::FaceMaker::addTopoShape (const TopoShape & s)
Definition at line 54 of file FaceMaker.cpp.
References Part::TopoShape::getShape().
Referenced by addShape().
addWire()
void Part::FaceMaker::addWire (const TopoDS_Wire & w) virtual
Definition at line 44 of file FaceMaker.cpp.
References src.Mod.PartDesign.fcgear.svggear::w.
Referenced by Part::TopoShape::makeOffset2D().
Build()
void Part::FaceMaker::Build () override
Definition at line 121 of file FaceMaker.cpp.
References ConstructFromType().
Referenced by Part::TopoShape::makeOffset2D().
Build_Essence()
virtual void Part::FaceMaker::Build_Essence () protected pure virtual
Build_Essence: build routine that can assume there is no nesting.
Implementing instructions: Add new faces (or whatever) to myShapesToReturn. The rest is done by base class's Build(). Please ignore contents of myCompounds in implementation. If special handling of nesting is required, override whole Build().
Implemented in Part::FaceMakerSimple, Part::FaceMakerExtrusion, Part::FaceMakerCheese, and Part::FaceMakerBullseye.
ConstructFromType() [1/2]
std::unique_ptr< Part::FaceMaker > Part::FaceMaker::ConstructFromType (Base::Type type) static
Definition at line 249 of file FaceMaker.cpp.
References Base::BaseClass::getClassTypeId(), and Path.Post.scripts.grbl_post::type.
ConstructFromType() [2/2]
std::unique_ptr< Part::FaceMaker > Part::FaceMaker::ConstructFromType (const char * className) static
Definition at line 238 of file FaceMaker.cpp.
References Base::Type::fromName(), and Base::Type::isBad().
Referenced by Build(), Part::Face::execute(), FC_LOG_LEVEL_INIT(), and Part::TopoShape::makeFace().
Face()
const TopoDS_Face & Part::FaceMaker::Face () virtual
Face: returns the face (result). If result is not a single face, throws Base::TypeError. (hint: use .Shape() instead)
Returns
Definition at line 99 of file FaceMaker.cpp.
References importers.importIFClegacy::getShape().
getTopoShape()
const Part::TopoShape & Part::FaceMaker::getTopoShape () const
Definition at line 112 of file FaceMaker.cpp.
postBuild()
void Part::FaceMaker::postBuild () protected
Definition at line 187 of file FaceMaker.cpp.
References src.Mod.AddonManager.NetworkManager::count, SCL.SimpleDataTypes::e, Part::OpCodes::Face, Data::IndexedName::fromConst(), and femtools.tokrules::names.
setPlane()
virtual void Part::FaceMaker::setPlane (const gp_Pln &) inline virtual
Reimplemented in Part::FaceMakerBullseye.
Definition at line 121 of file FaceMaker.h.
throwNotImplemented()
void Part::FaceMaker::throwNotImplemented () static protected
Definition at line 265 of file FaceMaker.cpp.
TopoFace()
const Part::TopoShape & Part::FaceMaker::TopoFace () const
Definition at line 104 of file FaceMaker.cpp.
useCompound()
void Part::FaceMaker::useCompound (const TopoDS_Compound & comp) virtual
useCompound: add children of compound to the FaceMaker. Note that this is different from addShape(comp) - structure is lost. The compound is NOT expanded recursively.
Parameters
comp
Definition at line 85 of file FaceMaker.cpp.
useTopoCompound()
void Part::FaceMaker::useTopoCompound (const TopoShape & comp)
Definition at line 93 of file FaceMaker.cpp.
References Part::TopoShape::getSubTopoShapes(), and toolbit-attributes::s.
Member Data Documentation
minElementNames
int Part::FaceMaker::minElementNames = 1 protected
Definition at line 155 of file FaceMaker.h.
myCompounds
std::vector<TopoDS_Compound> Part::FaceMaker::myCompounds protected
Definition at line 151 of file FaceMaker.h.
MyHasher
App::StringHasherRef Part::FaceMaker::MyHasher
Definition at line 145 of file FaceMaker.h.
myInputFaces
std::vector<TopoDS_Shape> Part::FaceMaker::myInputFaces protected
Definition at line 153 of file FaceMaker.h.
MyOp
const char* Part::FaceMaker::MyOp = 0
Definition at line 144 of file FaceMaker.h.
myShapesToReturn
std::vector<TopoDS_Shape> Part::FaceMaker::myShapesToReturn protected
Definition at line 152 of file FaceMaker.h.
Referenced by Part::FaceMakerBullseye::Build_Essence(), and Part::FaceMakerCheese::Build_Essence().
mySourceShapes
std::vector<TopoShape> Part::FaceMaker::mySourceShapes protected
Definition at line 148 of file FaceMaker.h.
myTopoShape
TopoShape Part::FaceMaker::myTopoShape protected
Definition at line 154 of file FaceMaker.h.
myTopoWires
std::vector<TopoShape> Part::FaceMaker::myTopoWires protected
Definition at line 150 of file FaceMaker.h.
myWires
std::vector<TopoDS_Wire> Part::FaceMaker::myWires protected
Definition at line 149 of file FaceMaker.h.
Referenced by Part::FaceMakerBullseye::Build_Essence(), and Part::FaceMakerCheese::Build_Essence().
The documentation for this class was generated from the following files:
FaceMaker.h
FaceMaker.cpp