FreeCAD: Path.cpp File Reference
Mod/CAM/App/Path.cpp File Reference
#include "PreCompiled.h"
#include <App/Application.h>
#include <Base/Console.h>
#include <Base/Reader.h>
#include <Base/Stream.h>
#include <Base/Writer.h>
#include <Mod/CAM/App/PathSegmentWalker.h>
#include "Path.h"
Classes
class BoundBoxSegmentVisitor
Functions
static void bulkAddCommand (const std::string &gcodestr, std::vector< Command * > &commands, bool &inches)
static void saveCenter (Writer &writer, const Base::Vector3d &center)
Function Documentation
bulkAddCommand()
static void bulkAddCommand (const std::string & gcodestr, std::vector< Command * > & commands, bool & inches) static
Definition at line 308 of file Mod/CAM/App/Path.cpp.
References Path.Op.Gui.Adaptive::Command, Path::Command::Name, Path::Command::scaleBy(), and Path::Command::setFromGCode().
Referenced by Path::Toolpath::setFromGCode().
saveCenter()
static void saveCenter (Writer & writer, const Base::Vector3d & center) static
Definition at line 470 of file Mod/CAM/App/Path.cpp.
References exportCSG::center(), Base::Writer::ind(), and Base::Writer::Stream().
Referenced by Path::Toolpath::Save().