FreeCAD: geoff_geometry::Box3d Class Reference
geoff_geometry::Box3d Class Reference
#include <geometry.h>
Public Member Functions
Box3d ()
Box3d (const Point3d &pmin, const Point3d &pmax)
bool outside (const Box3d &b) const
void combine (const Box3d &b)
Public Attributes
Point3d min
Point3d max
bool ok
Detailed Description
Definition at line 927 of file geometry.h.
Constructor & Destructor Documentation
Box3d() [1/2]
geoff_geometry::Box3d::Box3d () inline
Definition at line 934 of file geometry.h.
References KDL::max(), and KDL::min().
Box3d() [2/2]
geoff_geometry::Box3d::Box3d (const Point3d & pmin, const Point3d & pmax) inline
Definition at line 940 of file geometry.h.
References KDL::max(), and KDL::min().
Member Function Documentation
combine()
void geoff_geometry::Box3d::combine (const Box3d & b)
Definition at line 626 of file Finite.cpp.
References SCL.SimpleDataTypes::b, max, min, geoff_geometry::Point3d::x, geoff_geometry::Point3d::y, and geoff_geometry::Point3d::z.
outside()
bool geoff_geometry::Box3d::outside (const Box3d & b) const
Definition at line 648 of file Finite.cpp.
References SCL.SimpleDataTypes::b, max, min, geoff_geometry::Point3d::x, geoff_geometry::Point3d::y, and geoff_geometry::Point3d::z.
Referenced by geoff_geometry::Intof(), and geoff_geometry::Triangle3d::Intof().
Member Data Documentation
max
Point3d geoff_geometry::Box3d::max
Definition at line 931 of file geometry.h.
Referenced by combine(), geoff_geometry::Line::Line(), geoff_geometry::Line::minmax(), outside(), and geoff_geometry::Triangle3d::Triangle3d().
min
Point3d geoff_geometry::Box3d::min
Definition at line 930 of file geometry.h.
Referenced by combine(), geoff_geometry::Line::Line(), geoff_geometry::Line::minmax(), outside(), and geoff_geometry::Triangle3d::Triangle3d().
ok
bool geoff_geometry::Box3d::ok
Definition at line 932 of file geometry.h.
The documentation for this class was generated from the following files:
geometry.h
Finite.cpp