FreeCAD: Gui::SoTextLabel Class Reference
Gui::SoTextLabel Class Reference
#include <SoTextLabel.h>
Public Member Functions
SoTextLabel ()
Static Public Member Functions
static void initClass ()
Public Attributes
SoSFColor backgroundColor
SoSFBool background
SoSFFloat frameSize
Protected Member Functions
~SoTextLabel () override=default
void GLRender (SoGLRenderAction *action) override
Detailed Description
A text label with a background color.
Author
Werner Mayer
Definition at line 66 of file SoTextLabel.h.
Constructor & Destructor Documentation
SoTextLabel()
SoTextLabel::SoTextLabel ()
Definition at line 103 of file SoTextLabel.cpp.
References background, backgroundColor, SCL.SimpleDataTypes::f, and frameSize.
~SoTextLabel()
Gui::SoTextLabel::~SoTextLabel () override protected default
Member Function Documentation
GLRender()
void SoTextLabel::GLRender (SoGLRenderAction * action) override protected
Renders the label.
Definition at line 114 of file SoTextLabel.cpp.
References Path.Post.scripts.dynapath_4060_post::action, background, backgroundColor, MengerSponge::box, exportCSG::center(), SCL.SimpleDataTypes::f, frameSize, exportCSG::fs, glMatrixMode, and draftgeoutils.general::v1().
initClass()
void SoTextLabel::initClass () static
s="""
  #Inventor V2.1 ascii
  Annotation {
    Translation { translation 4 0 0 }
    FontStyle {
        size 20
        style BOLD
    }
    BaseColor {
        rgb 0.0 0.0 0.0
    }
    SoTextLabel { string ["Text label", "Second line"] backgroundColor 1.0 0.447059 0.337255}
  }
"""
App.ActiveDocument.addObject("App::InventorObject","iv").Buffer=s
Definition at line 98 of file SoTextLabel.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
Member Data Documentation
background
SoSFBool Gui::SoTextLabel::background
Definition at line 96 of file SoTextLabel.h.
Referenced by GLRender(), and SoTextLabel().
backgroundColor
SoSFColor Gui::SoTextLabel::backgroundColor
Definition at line 95 of file SoTextLabel.h.
Referenced by GLRender(), and SoTextLabel().
frameSize
SoSFFloat Gui::SoTextLabel::frameSize
Definition at line 97 of file SoTextLabel.h.
Referenced by GLRender(), and SoTextLabel().
The documentation for this class was generated from the following files:
SoTextLabel.h
SoTextLabel.cpp