FreeCAD: MeshGui::CylinderFitParameter Class Reference
MeshGui::CylinderFitParameter Class Reference
Public Member Functions
CylinderFitParameter ()=default
std::vector< float > getParameter (FitParameter::Points pts) const override
Public Member Functions inherited from MeshGui::FitParameter
FitParameter ()=default
virtual ~FitParameter ()=default
FitParameter (const FitParameter &)=delete
FitParameter (FitParameter &&)=delete
FitParameter & operator= (const FitParameter &)=delete
FitParameter & operator= (FitParameter &&)=delete
Detailed Description
Definition at line 74 of file SegmentationBestFit.cpp.
Constructor & Destructor Documentation
CylinderFitParameter()
MeshGui::CylinderFitParameter::CylinderFitParameter () default
Member Function Documentation
getParameter()
std::vector<float> MeshGui::CylinderFitParameter::getParameter (FitParameter::Points pts) const inline override virtual
Implements MeshGui::FitParameter.
Definition at line 78 of file SegmentationBestFit.cpp.
References MeshCore::Approximation::AddPoints(), Gui::Command::App, importers.importWebGL::base, Base::Console(), Base::Distance(), doCommand, MeshCore::CylinderFit::Fit(), FLOAT_MAX, MeshCore::CylinderFit::GetAxis(), MeshCore::CylinderFit::GetBounding(), MeshCore::Approximation::GetGravity(), MeshCore::CylinderFit::GetInitialAxisFromNormals(), MeshCore::CylinderFit::GetRadius(), Base::ConsoleSingleton::Message(), MeshGui::FitParameter::Points::normals, MeshGui::FitParameter::Points::points, MeshCore::CylinderFit::SetInitialValues(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
The documentation for this class was generated from the following file:
SegmentationBestFit.cpp