FreeCAD: importers.importSH3DHelper.BaseFurnitureHandler Class Reference
importers.importSH3DHelper.BaseFurnitureHandler Class Reference
Public Member Functions
def __init__ (self, SH3DImporter importer)
def set_furniture_common_properties (self, obj, elm)
def set_piece_of_furniture_common_properties (self, obj, elm)
def set_piece_of_furniture_horizontal_rotation_properties (self, obj, elm)
Public Member Functions inherited from importers.importSH3DHelper.BaseHandler
def setp (self, obj, type_, name, description, value=None, valid_values=None)
def get_fc_object (self, id, sh_type)
def get_floor (self, level_id)
Additional Inherited Members
Public Attributes inherited from importers.importSH3DHelper.BaseHandler
importer
Detailed Description
The base class for importing different class of furnitures.
Definition at line 1229 of file importSH3DHelper.py.
Constructor & Destructor Documentation
__init__()
def importers.importSH3DHelper.BaseFurnitureHandler.__init__ (self, SH3DImporter importer)
Reimplemented from importers.importSH3DHelper.BaseHandler.
Reimplemented in importers.importSH3DHelper.LightHandler, importers.importSH3DHelper.FurnitureHandler, and importers.importSH3DHelper.DoorOrWindowHandler.
Definition at line 1232 of file importSH3DHelper.py.
Referenced by draftguitools.gui_subelements.SubelementHighlight.finish().
Member Function Documentation
set_furniture_common_properties()
def importers.importSH3DHelper.BaseFurnitureHandler.set_furniture_common_properties (self, obj, elm)
Definition at line 1235 of file importSH3DHelper.py.
References importers.importSH3DHelper.BaseHandler.setp().
Referenced by importers.importSH3DHelper.DoorOrWindowHandler.process(), and importers.importSH3DHelper.FurnitureHandler.process().
set_piece_of_furniture_common_properties()
def importers.importSH3DHelper.BaseFurnitureHandler.set_piece_of_furniture_common_properties (self, obj, elm)
Definition at line 1252 of file importSH3DHelper.py.
References importers.importSH3DHelper.BaseHandler.setp(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by importers.importSH3DHelper.DoorOrWindowHandler.process(), and importers.importSH3DHelper.FurnitureHandler.process().
set_piece_of_furniture_horizontal_rotation_properties()
def importers.importSH3DHelper.BaseFurnitureHandler.set_piece_of_furniture_horizontal_rotation_properties (self, obj, elm)
Definition at line 1273 of file importSH3DHelper.py.
References importers.importSH3DHelper.BaseHandler.importer, importers.importSH3DHelper.BaseHandler.setp(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by importers.importSH3DHelper.FurnitureHandler.process().
The documentation for this class was generated from the following file:
importSH3DHelper.py