FreeCAD: PartGui::SoBrepEdgeSet Class Reference
PartGui::SoBrepEdgeSet Class Reference
#include <SoBrepEdgeSet.h>
Classes
struct SelContext
Public Member Functions
SoBrepEdgeSet ()
Static Public Member Functions
static void initClass ()
Protected Member Functions
~SoBrepEdgeSet () override=default
void GLRender (SoGLRenderAction *action) override
void GLRenderBelowPath (SoGLRenderAction *action) override
void doAction (SoAction *action) override
SoDetail * createLineSegmentDetail (SoRayPickAction *action, const SoPrimitiveVertex *v1, const SoPrimitiveVertex *v2, SoPickedPoint *pp) override
void getBoundingBox (SoGetBoundingBoxAction *action) override
Detailed Description
Definition at line 39 of file SoBrepEdgeSet.h.
Constructor & Destructor Documentation
SoBrepEdgeSet()
SoBrepEdgeSet::SoBrepEdgeSet ()
Definition at line 66 of file SoBrepEdgeSet.cpp.
~SoBrepEdgeSet()
PartGui::SoBrepEdgeSet::~SoBrepEdgeSet () override protected default
Member Function Documentation
createLineSegmentDetail()
SoDetail * SoBrepEdgeSet::createLineSegmentDetail (SoRayPickAction * action, const SoPrimitiveVertex * v1, const SoPrimitiveVertex * v2, SoPickedPoint * pp) override protected
Definition at line 456 of file SoBrepEdgeSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and draftgeoutils.general::v1().
doAction()
void SoBrepEdgeSet::doAction (SoAction * action) override protected
Definition at line 314 of file SoBrepEdgeSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::SoSelectionElementAction::All, Gui::SoSelectionElementAction::Append, Gui::SoFCSelectionCounter::checkAction(), Path.Post.scripts.dynapath_4060_post::default, Gui::SoFCSelectionRoot::getActionContext(), Gui::SoHighlightElementAction::getColor(), Gui::SoSelectionElementAction::getColor(), Gui::SoHighlightElementAction::getElement(), Gui::SoSelectionElementAction::getElement(), Gui::SoSelectionElementAction::getType(), SplineSurface::i, Gui::SoHighlightElementAction::isHighlighted(), Gui::SoSelectionElementAction::isSecondary(), Gui::SoSelectionElementAction::None, Gui::SoSelectionElementAction::Remove, and Gui::SoFCSelectionRoot::removeActionContext().
getBoundingBox()
void SoBrepEdgeSet::getBoundingBox (SoGetBoundingBoxAction * action) override protected
Definition at line 154 of file SoBrepEdgeSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and SplineSurface::i.
GLRender()
void SoBrepEdgeSet::GLRender (SoGLRenderAction * action) override protected
Definition at line 73 of file SoBrepEdgeSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and Gui::SoFCSelectionCounter::checkRenderCache().
GLRenderBelowPath()
void SoBrepEdgeSet::GLRenderBelowPath (SoGLRenderAction * action) override protected
Definition at line 149 of file SoBrepEdgeSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action.
initClass()
void SoBrepEdgeSet::initClass () static
Definition at line 61 of file SoBrepEdgeSet.cpp.
Referenced by PyMOD_INIT_FUNC().
The documentation for this class was generated from the following files:
SoBrepEdgeSet.h
SoBrepEdgeSet.cpp