FreeCAD: Gui::SoSelectionElementAction Class Reference
Gui::SoSelectionElementAction Class Reference
#include <SoFCUnifiedSelection.h>
Public Types
enum Type {
None, Append, Remove, All,
Color, Hide, Show
}
Public Member Functions
SoSelectionElementAction (Type=None, bool secondary=false)
~SoSelectionElementAction () override
Type getType () const
void setType (Type type)
void setColor (const SbColor &)
const SbColor & getColor () const
void setElement (const SoDetail *)
const SoDetail * getElement () const
bool isSecondary () const
void setSecondary (bool enable)
const std::map< std::string, App::Color > & getColors () const
void setColors (const std::map< std::string, App::Color > &colors)
void swapColors (std::map< std::string, App::Color > &colors)
Static Public Member Functions
static void initClass ()
Protected Member Functions
void beginTraversal (SoNode *node) override
Detailed Description
Author
Werner Mayer
Definition at line 412 of file SoFCUnifiedSelection.h.
Member Enumeration Documentation
Type
enum Gui::SoSelectionElementAction::Type
Enumerator
None
Append
Remove
All
Color
Hide
Show
Definition at line 417 of file SoFCUnifiedSelection.h.
Constructor & Destructor Documentation
SoSelectionElementAction()
SoSelectionElementAction::SoSelectionElementAction (Type t = None, bool secondary = false) explicit
Definition at line 903 of file SoFCUnifiedSelection.cpp.
~SoSelectionElementAction()
SoSelectionElementAction::~SoSelectionElementAction () override default
Member Function Documentation
beginTraversal()
void SoSelectionElementAction::beginTraversal (SoNode * node) override protected
Definition at line 911 of file SoFCUnifiedSelection.cpp.
getColor()
const SbColor & SoSelectionElementAction::getColor () const
Definition at line 932 of file SoFCUnifiedSelection.cpp.
Referenced by PartGui::SoBrepEdgeSet::doAction(), PartGui::SoBrepPointSet::doAction(), PartGui::SoBrepFaceSet::doAction(), and draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::setValues().
getColors()
const std::map<std::string,App::Color>& Gui::SoSelectionElementAction::getColors () const inline
Definition at line 437 of file SoFCUnifiedSelection.h.
Referenced by PartGui::SoBrepFaceSet::doAction(), and ArchBuildingPart.ViewProviderBuildingPart::updateData().
getElement()
const SoDetail * SoSelectionElementAction::getElement () const
Definition at line 942 of file SoFCUnifiedSelection.cpp.
Referenced by PartGui::SoBrepEdgeSet::doAction(), PartGui::SoBrepPointSet::doAction(), and PartGui::SoBrepFaceSet::doAction().
getType()
SoSelectionElementAction::Type SoSelectionElementAction::getType () const
Definition at line 922 of file SoFCUnifiedSelection.cpp.
Referenced by Gui::SoFCSelectionCounter::checkAction(), PartGui::SoBrepEdgeSet::doAction(), PartGui::SoBrepPointSet::doAction(), and PartGui::SoBrepFaceSet::doAction().
initClass()
void SoSelectionElementAction::initClass () static
Definition at line 885 of file SoFCUnifiedSelection.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
isSecondary()
bool Gui::SoSelectionElementAction::isSecondary () const inline
Definition at line 432 of file SoFCUnifiedSelection.h.
Referenced by Gui::SoFCSelectionCounter::checkAction(), PartGui::SoBrepEdgeSet::doAction(), PartGui::SoBrepPointSet::doAction(), and PartGui::SoBrepFaceSet::doAction().
setColor()
void SoSelectionElementAction::setColor (const SbColor & c)
Definition at line 927 of file SoFCUnifiedSelection.cpp.
References SCL.SimpleDataTypes::c.
Referenced by Gui::SoFCUnifiedSelection::doAction().
setColors()
void Gui::SoSelectionElementAction::setColors (const std::map< std::string, App::Color > & colors) inline
Definition at line 440 of file SoFCUnifiedSelection.h.
References importers.importIFCmulticore::colors.
setElement()
void SoSelectionElementAction::setElement (const SoDetail * det)
Definition at line 937 of file SoFCUnifiedSelection.cpp.
Referenced by Gui::SoFCUnifiedSelection::doAction().
setSecondary()
void Gui::SoSelectionElementAction::setSecondary (bool enable) inline
Definition at line 433 of file SoFCUnifiedSelection.h.
setType()
void Gui::SoSelectionElementAction::setType (Type type) inline
Definition at line 423 of file SoFCUnifiedSelection.h.
References Path.Post.scripts.grbl_post::type.
swapColors()
void Gui::SoSelectionElementAction::swapColors (std::map< std::string, App::Color > & colors) inline
Definition at line 443 of file SoFCUnifiedSelection.h.
References importers.importIFCmulticore::colors.
The documentation for this class was generated from the following files:
SoFCUnifiedSelection.h
SoFCUnifiedSelection.cpp