FreeCAD: expandplacements Namespace Reference
expandplacements Namespace Reference
Functions
def likeprimitive (obj, extrusion=False)
def expandplacementsmatrix (obj, matrix)
def expandplacements (obj, placement)
Function Documentation
expandplacements()
def expandplacements.expandplacements (obj, placement)
Definition at line 93 of file expandplacements.py.
References expandplacementsmatrix(), likeprimitive(), and OpenSCADUtils.mirror2mat().
Referenced by OpenSCADCommands.ExpandPlacements.Activated().
expandplacementsmatrix()
def expandplacements.expandplacementsmatrix (obj, matrix)
expand afine transformation down the feature tree
Definition at line 45 of file expandplacements.py.
References OpenSCADUtils.isspecialorthogonal(), likeprimitive(), and replaceobj.replaceobj().
Referenced by expandplacements().
likeprimitive()
def expandplacements.likeprimitive (obj, extrusion = False)
we can't push the matrix transformation further down
Definition at line 37 of file expandplacements.py.
Referenced by expandplacements(), and expandplacementsmatrix().