FreeCAD: MeshCore::MeshPointFacetAdjacency Class Reference
MeshCore::MeshPointFacetAdjacency Class Reference
#include <MeshIO.h>
Public Member Functions
MeshPointFacetAdjacency (std::size_t p, MeshFacetArray &f)
Construction.
void SetFacetNeighbourhood ()
Set the neighbourhood of two adjacent facets.
Detailed Description
The MeshPointFacetAdjacency class is a helper class to get all facets per vertex and set the neighbourhood of the facets. At this point the MeshFacetArray only references the points but does not have set the neighbourhood of two adjacent facets.
Definition at line 320 of file MeshIO.h.
Constructor & Destructor Documentation
MeshPointFacetAdjacency()
MeshPointFacetAdjacency::MeshPointFacetAdjacency (std::size_t p, MeshFacetArray & f)
Construction.
Parameters
p – the number of points
f – the facet array
Definition at line 2915 of file MeshIO.cpp.
Member Function Documentation
SetFacetNeighbourhood()
void MeshPointFacetAdjacency::SetFacetNeighbourhood ()
Set the neighbourhood of two adjacent facets.
Definition at line 2944 of file MeshIO.cpp.
References MeshCore::MeshFacet::_aulNeighbours, MeshCore::MeshFacet::_aulPoints, MeshCore::FACET_INDEX_MAX, MeshCore::MeshFacet::HasPoint(), and SplineSurface::i.
Referenced by MeshCore::ReaderOBJ::Load(), MeshCore::MeshInput::LoadInventor(), MeshCore::MeshInput::LoadMeshNode(), MeshCore::MeshInput::LoadOFF(), and MeshCore::MeshInput::LoadSMF().
The documentation for this class was generated from the following files:
MeshIO.h
MeshIO.cpp