FreeCAD: RenderingOrderAction Class Reference
RenderingOrderAction Class Reference
Public Member Functions
RenderingOrderAction (QObject *parent)
void updateWidget ()
void languageChange ()
Protected Member Functions
QWidget * createWidget (QWidget *parent) override
Detailed Description
Definition at line 1612 of file Mod/Sketcher/Gui/Command.cpp.
Constructor & Destructor Documentation
RenderingOrderAction()
RenderingOrderAction::RenderingOrderAction (QObject * parent) inline
Definition at line 1616 of file Mod/Sketcher/Gui/Command.cpp.
Member Function Documentation
createWidget()
QWidget* RenderingOrderAction::createWidget (QWidget * parent) inline override protected
Definition at line 1665 of file Mod/Sketcher/Gui/Command.cpp.
References draftgeoutils.intersections::connect(), languageChange(), and Init::parent.
languageChange()
void RenderingOrderAction::languageChange () inline
Definition at line 1659 of file Mod/Sketcher/Gui/Command.cpp.
References updateWidget().
Referenced by createWidget(), and CmdRenderingOrder::languageChange().
updateWidget()
void RenderingOrderAction::updateWidget () inline
Definition at line 1622 of file Mod/Sketcher/Gui/Command.cpp.
Referenced by CmdRenderingOrder::createAction(), and languageChange().
The documentation for this class was generated from the following file:
Mod/Sketcher/Gui/Command.cpp