FreeCAD: StdDevCollector Class Reference
StdDevCollector Class Reference
Public Member Functions
StdDevCollector ()
void collect (Quantity value) override
Quantity getQuantity () const override
Public Member Functions inherited from Collector
Collector ()=default
virtual ~Collector ()=default
Additional Inherited Members
Protected Attributes inherited from Collector
bool first {true}
Quantity q
Detailed Description
Definition at line 1918 of file Expression.cpp.
Constructor & Destructor Documentation
StdDevCollector()
StdDevCollector::StdDevCollector () inline
Definition at line 1920 of file Expression.cpp.
Member Function Documentation
collect()
void StdDevCollector::collect (Quantity value) inline override virtual
Reimplemented from Collector.
Definition at line 1922 of file Expression.cpp.
References Collector::collect(), Base::Quantity::getUnit(), and src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::Quantity.
getQuantity()
Quantity StdDevCollector::getQuantity () const inline override virtual
Reimplemented from Collector.
Definition at line 1937 of file Expression.cpp.
References getValue(), Base::pow(), and src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::Quantity.
Referenced by materialtests.TestMaterials.MaterialTestCases::test2DArray(), materialtests.TestMaterials.MaterialTestCases::test3DArray(), materialtests.TestMaterials.MaterialTestCases::testCalculiXSteel(), and materialtests.TestMaterialCreation.MaterialCreationTestCases::testCreateMaterial().
The documentation for this class was generated from the following file:
Expression.cpp