FreeCAD: MeshCore::MeshFixCorruptedFacets Class Reference
MeshCore::MeshFixCorruptedFacets Class Reference
#include <Degeneration.h>
Public Member Functions
MeshFixCorruptedFacets (MeshKernel &rclM)
bool Fixup () override
Public Member Functions inherited from MeshCore::MeshValidation
MeshValidation (MeshKernel &rclB)
virtual ~MeshValidation ()=default
MeshValidation (const MeshValidation &)=delete
MeshValidation (MeshValidation &&)=delete
MeshValidation & operator= (const MeshValidation &)=delete
MeshValidation & operator= (MeshValidation &&)=delete
Additional Inherited Members
Protected Attributes inherited from MeshCore::MeshValidation
MeshKernel & _rclMesh
Detailed Description
The MeshFixCorruptedFacets class fixes corrupted facets by removing them from the mesh structure.
See also
MeshEvalCorruptedFacets
Author
Werner Mayer
Definition at line 736 of file Degeneration.h.
Constructor & Destructor Documentation
MeshFixCorruptedFacets()
MeshCore::MeshFixCorruptedFacets::MeshFixCorruptedFacets (MeshKernel & rclM) inline explicit
Construction.
Definition at line 742 of file Degeneration.h.
Member Function Documentation
Fixup()
bool MeshFixCorruptedFacets::Fixup () override virtual
Removes corrupted facets.
Implements MeshCore::MeshValidation.
Definition at line 1204 of file Degeneration.cpp.
References MeshCore::MeshValidation::_rclMesh, MeshCore::MeshFacetIterator::GetReference(), MeshCore::MeshFacetIterator::Init(), MeshCore::MeshFacet::IsDegenerated(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), MeshCore::MeshFacetIterator::Position(), MeshCore::MeshTopoAlgorithm::RemoveCorruptedFacet(), and MeshCore::MeshFacetIterator::Set().
Referenced by Mesh::MeshObject::validateIndices().
The documentation for this class was generated from the following files:
Degeneration.h
Degeneration.cpp