FreeCAD: Sandbox::DocumentTestThread Class Reference
Sandbox::DocumentTestThread Class Reference
#include <DocumentThread.h>
Public Member Functions
DocumentTestThread (QObject *parent=0)
~DocumentTestThread ()
Protected Member Functions
void run ()
Detailed Description
Definition at line 106 of file DocumentThread.h.
Constructor & Destructor Documentation
DocumentTestThread()
DocumentTestThread::DocumentTestThread (QObject * parent = 0)
Definition at line 207 of file DocumentThread.cpp.
~DocumentTestThread()
DocumentTestThread::~DocumentTestThread ()
Definition at line 212 of file DocumentThread.cpp.
Member Function Documentation
run()
void DocumentTestThread::run () protected
Definition at line 216 of file DocumentThread.cpp.
References Sandbox::DocumentProtector::addObject(), Base::Console(), toolbit-attributes::doc, Sandbox::DocumentObjectProtector::execute(), App::Application::getActiveDocument(), App::GetApplication(), Base::ConsoleSingleton::Message(), Sandbox::DocumentProtector::recompute(), Sandbox::DocumentObjectProtector::setProperty(), App::PropertyInteger::setValue(), and App::PropertyString::setValue().
The documentation for this class was generated from the following files:
DocumentThread.h
DocumentThread.cpp