FreeCAD: PartDesignGui::TaskTransformedParameters Class Reference
PartDesignGui::TaskTransformedParameters Class Reference abstract
#include <TaskTransformedParameters.h>
Public Member Functions
TaskTransformedParameters (ViewProviderTransformed *TransformedView, QWidget *parent=nullptr)
Constructor for task with ViewProvider.
TaskTransformedParameters (TaskMultiTransformParameters *parentTask)
Constructor for task with parent task (MultiTransform mode)
~TaskTransformedParameters () override
virtual void apply ()=0
Apply changes for python console.
void setEnabledTransaction (bool)
setEnabledTransaction The transaction handling of this panel can be disabled if there is another instance that does it already, e.g. TaskDlgMultiTransformParameters. By default, transactions are enabled.
void exitSelectionMode ()
Exit the selection mode of the associated task panel.
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Public Member Functions inherited from Gui::DocumentObserver
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
void attachDocument (Document *)
void detachDocument ()
Static Public Member Functions
static void removeItemFromListWidget (QListWidget *widget, const QString &itemstr)
Protected Types
enum SelectionMode { SelectionMode::None, SelectionMode::AddFeature, SelectionMode::RemoveFeature, SelectionMode::Reference }
Protected Member Functions
void setupUI ()
PartDesign::Transformed * getObject () const
template<class T >
T * getObject () const
App::DocumentObject * getSketchObject () const
bool originalSelected (const Gui::SelectionChanges &msg)
void recomputeFeature ()
Recompute either this feature or the parent MultiTransform feature.
void hideObject ()
Hide the top transformed object (see getTopTransformedObject())
void showObject ()
Show the top transformed object (see getTopTransformedObject())
void hideBase ()
Hide the base transformation object (see getObject())
void showBase ()
Show the base transformation object (see getObject())
void addReferenceSelectionGate (AllowSelectionFlags)
int getUpdateViewTimeout () const
void slotDeletedObject (const Gui::ViewProviderDocumentObject &Obj) override
void onSelectionChanged (const Gui::SelectionChanges &msg) override
void fillAxisCombo (ComboLinks &combolinks, Part::Part2DObject *sketch)
Fill combobox with the axis from the sketch and the own bodys origin axis.
void fillPlanesCombo (ComboLinks &combolinks, Part::Part2DObject *sketch)
Fill combobox with the planes from the sketch and the own bodys origin planes.
PartDesign::Transformed * getTopTransformedObject () const
bool isEnabledTransaction () const
void setupTransaction ()
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Protected Attributes
ViewProviderTransformed * TransformedView = nullptr
SelectionMode selectionMode = SelectionMode::None
bool blockUpdate = false
Lock updateUI(), applying changes to the underlying feature and calling recomputeFeature()
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
The transformed subclasses will be used in two different modes:
As a stand-alone feature
As a container that stores transformation info for a MultiTransform feature. In this case the flag insideMultiTransform is set to true. Because in the second case there is no ViewProvider, some special methods are required to access the underlying FeatureTransformed object in two different ways.
Definition at line 138 of file TaskTransformedParameters.h.
Member Enumeration Documentation
SelectionMode
enum PartDesignGui::TaskTransformedParameters::SelectionMode strong protected
Enumerator
None
AddFeature
RemoveFeature
Reference
Definition at line 267 of file TaskTransformedParameters.h.
Constructor & Destructor Documentation
TaskTransformedParameters() [1/2]
TaskTransformedParameters::TaskTransformedParameters (ViewProviderTransformed * TransformedView, QWidget * parent = nullptr) explicit
Constructor for task with ViewProvider.
Definition at line 57 of file TaskTransformedParameters.cpp.
References toolbit-attributes::doc, App::Application::getActiveTransaction(), and App::GetApplication().
TaskTransformedParameters() [2/2]
TaskTransformedParameters::TaskTransformedParameters (TaskMultiTransformParameters * parentTask) explicit
Constructor for task with parent task (MultiTransform mode)
Definition at line 73 of file TaskTransformedParameters.cpp.
~TaskTransformedParameters()
TaskTransformedParameters::~TaskTransformedParameters () override
Definition at line 79 of file TaskTransformedParameters.cpp.
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
addReferenceSelectionGate()
void TaskTransformedParameters::addReferenceSelectionGate (AllowSelectionFlags allow) protected
Definition at line 585 of file TaskTransformedParameters.cpp.
References Gui::SelectionSingleton::addSelectionGate(), getTopTransformedObject(), and Gui::Selection().
apply()
virtual void PartDesignGui::TaskTransformedParameters::apply () pure virtual
Apply changes for python console.
Implemented in PartDesignGui::TaskMultiTransformParameters, PartDesignGui::TaskLinearPatternParameters, PartDesignGui::TaskMirroredParameters, PartDesignGui::TaskPolarPatternParameters, and PartDesignGui::TaskScaledParameters.
Referenced by PartDesignGui::TaskDlgTransformedParameters::accept().
exitSelectionMode()
void TaskTransformedParameters::exitSelectionMode ()
Exit the selection mode of the associated task panel.
Definition at line 572 of file TaskTransformedParameters.cpp.
References None, Base::Exception::ReportException(), Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), selectionMode, and showObject().
Referenced by PartDesignGui::TaskDlgTransformedParameters::accept(), PartDesignGui::TaskLinearPatternParameters::onSelectionChanged(), PartDesignGui::TaskMirroredParameters::onSelectionChanged(), PartDesignGui::TaskPolarPatternParameters::onSelectionChanged(), onSelectionChanged(), and PartDesignGui::TaskDlgTransformedParameters::reject().
fillAxisCombo()
void TaskTransformedParameters::fillAxisCombo (ComboLinks & combolinks, Part::Part2DObject * sketch) protected
Fill combobox with the axis from the sketch and the own bodys origin axis.
Definition at line 402 of file TaskTransformedParameters.cpp.
References PartDesignGui::ComboLinks::addLink(), PartDesignGui::ComboLinks::clear(), Base::Console(), Base::ConsoleSingleton::Error(), PartDesign::Body::findBodyOf(), Part::Part2DObject::getAxisCount(), getObject(), App::OriginGroupExtension::getOrigin(), App::LocalCoordinateSystem::getX(), App::LocalCoordinateSystem::getY(), App::LocalCoordinateSystem::getZ(), SplineSurface::i, and Base::Exception::what().
fillPlanesCombo()
void TaskTransformedParameters::fillPlanesCombo (ComboLinks & combolinks, Part::Part2DObject * sketch) protected
Fill combobox with the planes from the sketch and the own bodys origin planes.
Definition at line 439 of file TaskTransformedParameters.cpp.
References PartDesignGui::ComboLinks::addLink(), PartDesignGui::ComboLinks::clear(), Base::Console(), Base::ConsoleSingleton::Error(), PartDesign::Body::findBodyOf(), Part::Part2DObject::getAxisCount(), getObject(), App::OriginGroupExtension::getOrigin(), App::LocalCoordinateSystem::getXY(), App::LocalCoordinateSystem::getXZ(), App::LocalCoordinateSystem::getYZ(), SplineSurface::i, and Base::Exception::what().
getObject() [1/2]
PartDesign::Transformed * TaskTransformedParameters::getObject () const protected
Returns the base transformation For standalone features it will be object associated with the view provider For features inside MultiTransform it will be the parent MultiTransform's sub feature object
Definition at line 497 of file TaskTransformedParameters.cpp.
References Gui::ViewProviderDocumentObject::getObject(), PartDesignGui::TaskMultiTransformParameters::getSubFeature(), and TransformedView.
Referenced by PartDesignGui::TaskScaledParameters::apply(), PartDesignGui::TaskLinearPatternParameters::apply(), PartDesignGui::TaskPolarPatternParameters::apply(), PartDesignGui::TaskMirroredParameters::apply(), fillAxisCombo(), fillPlanesCombo(), originalSelected(), setupTransaction(), PartDesignGui::TaskLinearPatternParameters::~TaskLinearPatternParameters(), PartDesignGui::TaskMirroredParameters::~TaskMirroredParameters(), and PartDesignGui::TaskPolarPatternParameters::~TaskPolarPatternParameters().
getObject() [2/2]
template<class T > T* PartDesignGui::TaskTransformedParameters::getObject () const inline protected
Definition at line 182 of file TaskTransformedParameters.h.
References getObject().
Referenced by getObject().
getSketchObject()
App::DocumentObject * TaskTransformedParameters::getSketchObject () const protected
Get the sketch object of the first original either of the object associated with this feature or with the parent feature (MultiTransform mode)
Definition at line 526 of file TaskTransformedParameters.cpp.
References PartDesign::Transformed::getSketchObject(), and getTopTransformedObject().
getTopTransformedObject()
PartDesign::Transformed * TaskTransformedParameters::getTopTransformedObject () const protected
Returns the base transformed objectfromStdString For stand alone features it will be objects associated with this object For features inside multitransform it will be the base multitransform object
Definition at line 485 of file TaskTransformedParameters.cpp.
References Gui::ViewProviderDocumentObject::getObject(), and Base::BaseClass::isDerivedFrom().
Referenced by addReferenceSelectionGate(), getSketchObject(), hideObject(), and showObject().
getUpdateViewTimeout()
int TaskTransformedParameters::getUpdateViewTimeout () const protected
Definition at line 202 of file TaskTransformedParameters.cpp.
hideBase()
void TaskTransformedParameters::hideBase () protected
Hide the base transformation object (see getObject())
Definition at line 552 of file TaskTransformedParameters.cpp.
References SCL.SimpleDataTypes::e, and FCMD_OBJ_HIDE.
hideObject()
void TaskTransformedParameters::hideObject () protected
Hide the top transformed object (see getTopTransformedObject())
Definition at line 532 of file TaskTransformedParameters.cpp.
References SCL.SimpleDataTypes::e, FCMD_OBJ_HIDE, and getTopTransformedObject().
isEnabledTransaction()
bool TaskTransformedParameters::isEnabledTransaction () const protected
Definition at line 299 of file TaskTransformedParameters.cpp.
Referenced by setupTransaction().
onSelectionChanged()
void TaskTransformedParameters::onSelectionChanged (const Gui::SelectionChanges & msg) override protected virtual
Implements Gui::SelectionObserver.
Definition at line 184 of file TaskTransformedParameters.cpp.
References exitSelectionMode(), Path.Op.Surface::msg, and originalSelected().
originalSelected()
bool TaskTransformedParameters::originalSelected (const Gui::SelectionChanges & msg) protected
Handle adding/removing of selected features Returns true if a selected feature was added/removed.
Definition at line 224 of file TaskTransformedParameters.cpp.
References AddFeature, Gui::SelectionChanges::AddSelection, DraftVecUtils::find(), App::DocumentObject::getDocument(), getObject(), App::Document::getObject(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Base::BaseClass::isDerivedFrom(), Path.Op.Surface::msg, PartDesign::Transformed::Originals, recomputeFeature(), RemoveFeature, selectionMode, setupTransaction(), and App::PropertyLinkList::setValues().
Referenced by PartDesignGui::TaskLinearPatternParameters::onSelectionChanged(), PartDesignGui::TaskMirroredParameters::onSelectionChanged(), PartDesignGui::TaskPolarPatternParameters::onSelectionChanged(), and onSelectionChanged().
recomputeFeature()
void TaskTransformedParameters::recomputeFeature () protected
Recompute either this feature or the parent MultiTransform feature.
Definition at line 475 of file TaskTransformedParameters.cpp.
References PartDesignGui::ViewProviderTransformed::recomputeFeature().
Referenced by PartDesignGui::TaskLinearPatternParameters::onSelectionChanged(), PartDesignGui::TaskMirroredParameters::onSelectionChanged(), PartDesignGui::TaskPolarPatternParameters::onSelectionChanged(), and originalSelected().
removeItemFromListWidget()
void TaskTransformedParameters::removeItemFromListWidget (QListWidget * widget, const QString & itemstr) static
Definition at line 391 of file TaskTransformedParameters.cpp.
References src.Mod.Test.testPathArray::items.
setEnabledTransaction()
void TaskTransformedParameters::setEnabledTransaction (bool on)
setEnabledTransaction The transaction handling of this panel can be disabled if there is another instance that does it already, e.g. TaskDlgMultiTransformParameters. By default, transactions are enabled.
Definition at line 294 of file TaskTransformedParameters.cpp.
Referenced by PartDesignGui::TaskDlgMultiTransformParameters::TaskDlgMultiTransformParameters().
setupTransaction()
void TaskTransformedParameters::setupTransaction () protected
Definition at line 271 of file TaskTransformedParameters.cpp.
References App::Application::getActiveTransaction(), App::GetApplication(), getObject(), App::PropertyString::getValue(), isEnabledTransaction(), App::DocumentObject::Label, and App::Application::setActiveTransaction().
Referenced by PartDesignGui::TaskLinearPatternParameters::onSelectionChanged(), PartDesignGui::TaskMirroredParameters::onSelectionChanged(), PartDesignGui::TaskPolarPatternParameters::onSelectionChanged(), and originalSelected().
setupUI()
void TaskTransformedParameters::setupUI () protected
Setup the standalone UI. Call this in the derived destructor with ViewProvider.
Definition at line 87 of file TaskTransformedParameters.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::Application::commandManager(), draftgeoutils.intersections::connect(), Gui::CommandManager::getCommandByName(), Gui::Command::getShortcut(), QSint::ActionGroup::groupLayout(), and Gui::Application::Instance.
Referenced by PartDesignGui::TaskLinearPatternParameters::TaskLinearPatternParameters(), PartDesignGui::TaskMirroredParameters::TaskMirroredParameters(), PartDesignGui::TaskMultiTransformParameters::TaskMultiTransformParameters(), PartDesignGui::TaskPolarPatternParameters::TaskPolarPatternParameters(), and PartDesignGui::TaskScaledParameters::TaskScaledParameters().
showBase()
void TaskTransformedParameters::showBase () protected
Show the base transformation object (see getObject())
Definition at line 562 of file TaskTransformedParameters.cpp.
References SCL.SimpleDataTypes::e, and FCMD_OBJ_SHOW.
showObject()
void TaskTransformedParameters::showObject () protected
Show the top transformed object (see getTopTransformedObject())
Definition at line 542 of file TaskTransformedParameters.cpp.
References SCL.SimpleDataTypes::e, FCMD_OBJ_SHOW, and getTopTransformedObject().
Referenced by exitSelectionMode().
slotDeletedObject()
void TaskTransformedParameters::slotDeletedObject (const Gui::ViewProviderDocumentObject & Obj) override protected virtual
Notifies when the object is about to be removed.
Reimplemented from Gui::DocumentObserver.
Definition at line 168 of file TaskTransformedParameters.cpp.
References TransformedView.
Member Data Documentation
blockUpdate
bool PartDesignGui::TaskTransformedParameters::blockUpdate = false protected
Lock updateUI(), applying changes to the underlying feature and calling recomputeFeature()
Definition at line 279 of file TaskTransformedParameters.h.
selectionMode
SelectionMode PartDesignGui::TaskTransformedParameters::selectionMode = SelectionMode::None protected
Definition at line 276 of file TaskTransformedParameters.h.
Referenced by exitSelectionMode(), PartDesignGui::TaskMirroredParameters::onSelectionChanged(), PartDesignGui::TaskLinearPatternParameters::onSelectionChanged(), PartDesignGui::TaskPolarPatternParameters::onSelectionChanged(), and originalSelected().
TransformedView
ViewProviderTransformed* PartDesignGui::TaskTransformedParameters::TransformedView = nullptr protected
Definition at line 275 of file TaskTransformedParameters.h.
Referenced by PartDesignGui::TaskMultiTransformParameters::apply(), getObject(), and slotDeletedObject().
The documentation for this class was generated from the following files:
TaskTransformedParameters.h
TaskTransformedParameters.cpp