FreeCAD: Gui::ToolBarItem Class Reference
Gui::ToolBarItem Class Reference
#include <ToolBarManager.h>
Public Types
enum DefaultVisibility { DefaultVisibility::Visible, DefaultVisibility::Hidden, DefaultVisibility::Unavailable }
Public Member Functions
ToolBarItem ()
ToolBarItem (ToolBarItem *item, DefaultVisibility visibilityPolicy=DefaultVisibility::Visible)
~ToolBarItem ()
void setCommand (const std::string &)
const std::string & command () const
bool hasItems () const
ToolBarItem * findItem (const std::string &)
ToolBarItem * copy () const
uint count () const
void appendItem (ToolBarItem *item)
bool insertItem (ToolBarItem *, ToolBarItem *item)
void removeItem (ToolBarItem *item)
void clear ()
ToolBarItem & operator<< (ToolBarItem *item)
ToolBarItem & operator<< (const std::string &command)
QList< ToolBarItem * > getItems () const
Public Attributes
DefaultVisibility visibilityPolicy
Detailed Description
Definition at line 49 of file ToolBarManager.h.
Member Enumeration Documentation
DefaultVisibility
enum Gui::ToolBarItem::DefaultVisibility strong
Manages the default visibility status of a toolbar item, as well as the default status of the toggleViewAction usable by the contextual menu to enable and disable its visibility
Enumerator
Visible
Hidden
Unavailable
Definition at line 55 of file ToolBarManager.h.
Constructor & Destructor Documentation
ToolBarItem() [1/2]
ToolBarItem::ToolBarItem ()
Definition at line 53 of file ToolBarManager.cpp.
Referenced by copy(), and operator<<().
ToolBarItem() [2/2]
ToolBarItem::ToolBarItem (ToolBarItem * item, DefaultVisibility visibilityPolicy = DefaultVisibility::Visible) explicit
Definition at line 57 of file ToolBarManager.cpp.
References appendItem().
~ToolBarItem()
ToolBarItem::~ToolBarItem ()
Definition at line 64 of file ToolBarManager.cpp.
References clear().
Member Function Documentation
appendItem()
void ToolBarItem::appendItem (ToolBarItem * item)
Definition at line 117 of file ToolBarManager.cpp.
Referenced by operator<<(), and ToolBarItem().
clear()
void ToolBarItem::clear ()
Definition at line 141 of file ToolBarManager.cpp.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__(), and ~ToolBarItem().
command()
const std::string & ToolBarItem::command () const
Definition at line 74 of file ToolBarManager.cpp.
Referenced by copy(), and operator<<().
copy()
ToolBarItem * ToolBarItem::copy () const
Definition at line 99 of file ToolBarManager.cpp.
References command(), getItems(), src.Mod.Test.testPathArray::items, and ToolBarItem().
Referenced by Gui::PythonBaseWorkbench::setupCommandBars(), Gui::PythonWorkbench::setupCommandBars(), Gui::PythonBaseWorkbench::setupToolBars(), and Gui::PythonWorkbench::setupToolBars().
count()
uint ToolBarItem::count () const
Definition at line 112 of file ToolBarManager.cpp.
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::set_status_filter().
findItem()
ToolBarItem * ToolBarItem::findItem (const std::string & name)
Definition at line 84 of file ToolBarManager.cpp.
Referenced by Gui::PythonBaseWorkbench::appendCommandbar(), Gui::PythonBaseWorkbench::appendToolbar(), MeasureGui::WorkbenchManipulator::modifyToolBars(), Gui::PythonBaseWorkbench::removeCommandbar(), and Gui::PythonBaseWorkbench::removeToolbar().
getItems()
QList< ToolBarItem * > ToolBarItem::getItems () const
Definition at line 163 of file ToolBarManager.cpp.
Referenced by copy(), Gui::ToolBoxManager::setup(), and Gui::ToolBarManager::setup().
hasItems()
bool ToolBarItem::hasItems () const
Definition at line 79 of file ToolBarManager.cpp.
insertItem()
bool ToolBarItem::insertItem (ToolBarItem * before, ToolBarItem * item)
Definition at line 122 of file ToolBarManager.cpp.
References RobotExample::pos.
operator<<() [1/2]
ToolBarItem & ToolBarItem::operator<< (const std::string & command)
Definition at line 156 of file ToolBarManager.cpp.
References command(), and ToolBarItem().
operator<<() [2/2]
ToolBarItem & ToolBarItem::operator<< (ToolBarItem * item)
Definition at line 150 of file ToolBarManager.cpp.
References appendItem().
removeItem()
void ToolBarItem::removeItem (ToolBarItem * item)
Definition at line 133 of file ToolBarManager.cpp.
References RobotExample::pos.
Referenced by Gui::PythonBaseWorkbench::removeCommandbar(), and Gui::PythonBaseWorkbench::removeToolbar().
setCommand()
void ToolBarItem::setCommand (const std::string & name)
Definition at line 69 of file ToolBarManager.cpp.
Referenced by Gui::PythonBaseWorkbench::appendCommandbar(), Gui::PythonBaseWorkbench::appendToolbar(), SpreadsheetGui::Workbench::setupCommandBars(), DrawingGui::Workbench::setupCommandBars(), PointsGui::Workbench::setupCommandBars(), TechDrawGui::Workbench::setupCommandBars(), PartDesignGui::Workbench::setupToolBars(), SpreadsheetGui::Workbench::setupToolBars(), SurfaceGui::Workbench::setupToolBars(), MatGui::Workbench::setupToolBars(), MeshPartGui::Workbench::setupToolBars(), ReverseEngineeringGui::Workbench::setupToolBars(), PointsGui::Workbench::setupToolBars(), DrawingGui::Workbench::setupToolBars(), TechDrawGui::Workbench::setupToolBars(), FemGui::Workbench::setupToolBars(), PartGui::Workbench::setupToolBars(), MeshGui::Workbench::setupToolBars(), RobotGui::Workbench::setupToolBars(), and SketcherGui::Workbench::setupToolBars().
Member Data Documentation
visibilityPolicy
DefaultVisibility Gui::ToolBarItem::visibilityPolicy
Definition at line 85 of file ToolBarManager.h.
The documentation for this class was generated from the following files:
ToolBarManager.h
ToolBarManager.cpp