FreeCAD: Path.Post.scripts.gcode_pre Namespace Reference
Path.Post.scripts.gcode_pre Namespace Reference
Classes
class PathNoActiveDocumentException
class PathNoJobException
Functions
def open (filename)
def matchToolController (op, toolnumber)
def parse (inputstring)
def insert (filename, docname=None)
Variables
PathCustom
translate
Function Documentation
insert()
def Path.Post.scripts.gcode_pre.insert (filename, docname = None)
called when freecad imports a file
Definition at line 215 of file gcode_pre.py.
References Path.Log.error(), Path.Post.scripts.gcode_pre.matchToolController(), and Path.Log.track().
Referenced by Path.Post.scripts.gcode_pre.open().
matchToolController()
def Path.Post.scripts.gcode_pre.matchToolController (op, toolnumber)
Try to match a tool controller in the job by number
Definition at line 92 of file gcode_pre.py.
Referenced by Path.Post.scripts.gcode_pre.insert().
open()
def Path.Post.scripts.gcode_pre.open (filename)
called when freecad opens a file.
Definition at line 84 of file gcode_pre.py.
References Path.Post.scripts.gcode_pre.insert(), and Path.Log.track().
parse()
def Path.Post.scripts.gcode_pre.parse (inputstring)
Definition at line 118 of file gcode_pre.py.
References Path.Log.track().
Variable Documentation
PathCustom
Path.Post.scripts.gcode_pre.PathCustom
Definition at line 56 of file gcode_pre.py.
translate
Path.Post.scripts.gcode_pre.translate
Definition at line 60 of file gcode_pre.py.