FreeCAD: TechDrawGui::DlgPageChooser Class Reference
TechDrawGui::DlgPageChooser Class Reference
#include <DlgPageChooser.h>
Public Member Functions
DlgPageChooser (const std::vector< std::string > labels, const std::vector< std::string > names, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgPageChooser () override
std::string getSelection () const
void accept () override
void reject () override
Detailed Description
Definition at line 52 of file DlgPageChooser.h.
Constructor & Destructor Documentation
DlgPageChooser()
DlgPageChooser::DlgPageChooser (const std::vector< std::string > labels, const std::vector< std::string > names, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
Definition at line 41 of file DlgPageChooser.cpp.
References draftgeoutils.intersections::connect(), App::ExpressionParser::labels, and femtools.tokrules::names.
~DlgPageChooser()
DlgPageChooser::~DlgPageChooser () override
Destroys the object and frees any allocated resources
Definition at line 59 of file DlgPageChooser.cpp.
Member Function Documentation
accept()
void DlgPageChooser::accept () override
Definition at line 93 of file DlgPageChooser.cpp.
getSelection()
std::string DlgPageChooser::getSelection () const
Definition at line 82 of file DlgPageChooser.cpp.
Referenced by TechDrawGui::DrawGuiUtil::findPage().
reject()
void DlgPageChooser::reject () override
Definition at line 97 of file DlgPageChooser.cpp.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action().
The documentation for this class was generated from the following files:
DlgPageChooser.h
DlgPageChooser.cpp