FreeCAD: Gui::ViewProviderExtern Class Reference
Gui::ViewProviderExtern Class Reference
#include <ViewProviderExtern.h>
Public Member Functions
ViewProviderExtern ()
constructor.
~ViewProviderExtern () override
destructor.
void setModeByString (const char *name, const char *ivFragment)
void setModeByFile (const char *name, const char *ivFileName)
void setModeBySoInput (const char *name, SoInput &ivFileInput)
void adjustDocumentName (const char *docname)
const char * getDefaultDisplayMode () const override
get the default display mode
std::vector< std::string > getDisplayModes () const override
returns a list of all possible display modes
void updateData (const App::Property *) override
Public Member Functions inherited from Gui::ViewProvider
ViewProvider ()
constructor.
~ViewProvider () override
destructor.
virtual SoSeparator * getRoot () const
SoSwitch * getModeSwitch () const
SoTransform * getTransformNode () const
SoSeparator * getAnnotation ()
virtual SoSeparator * getFrontRoot () const
virtual SoGroup * getChildRoot () const
virtual SoSeparator * getBackRoot () const
virtual bool canAddToSceneGraph () const
Indicate whether to be added to scene graph or not.
virtual bool isPartOfPhysicalObject () const
virtual std::vector< App::DocumentObject * > claimChildren3D () const
virtual bool useNewSelectionModel () const
indicates if the ViewProvider use the new Selection model
virtual bool isSelectable () const
virtual bool getElementPicked (const SoPickedPoint *, std::string &subname) const
return a hit element given the picked point which contains the full node path
virtual std::string getElement (const SoDetail *) const
return a hit element to the selection path or 0
virtual SoDetail * getDetail (const char *) const
return the coin node detail of the subelement
virtual bool getDetailPath (const char *subname, SoFullPath *pPath, bool append, SoDetail *&det) const
int partialRender (const std::vector< std::string > &subelements, bool clear)
virtual std::vector< Base::Vector3d > getModelPoints (const SoPickedPoint *) const
virtual std::vector< Base::Vector3d > getSelectionShape (const char *Element) const
return the highlight lines for a given element or the whole shape
Base::BoundBox3d getBoundingBox (const char *subname=nullptr, bool transform=true, MDIView *view=nullptr) const
virtual bool onDelete (const std::vector< std::string > &subNames)
virtual void beforeDelete ()
virtual bool canDelete (App::DocumentObject *obj) const
Asks the view provider if the given object that is part of its outlist can be removed from there without breaking it.
virtual bool canDragObjects () const
virtual bool canDragObject (App::DocumentObject *) const
virtual bool canDragObjectToTarget (App::DocumentObject *obj, App::DocumentObject *target) const
virtual void dragObject (App::DocumentObject *)
virtual bool canDropObjects () const
virtual bool canDropObject (App::DocumentObject *) const
virtual bool canDragAndDropObject (App::DocumentObject *) const
virtual void dropObject (App::DocumentObject *)
virtual bool canDropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements) const
virtual bool acceptReorderingObjects () const
virtual std::string getDropPrefix () const
return a subname referencing the sub-object holding the dropped objects
virtual std::string dropObjectEx (App::DocumentObject *obj, App::DocumentObject *owner, const char *subname, const std::vector< std::string > &elements)
virtual int replaceObject (App::DocumentObject *oldObj, App::DocumentObject *newObj)
virtual bool showInTree () const
virtual bool canRemoveChildrenFromRoot () const
std::string getActiveDisplayMode () const
virtual void setDisplayMode (const char *ModeName)
set the display mode
virtual void hide ()
Hides the view provider.
virtual void show ()
Shows the view provider.
virtual bool isShow () const
checks whether the view provider is visible or not
void setVisible (bool)
bool isVisible () const
void setLinkVisible (bool)
bool isLinkVisible () const
virtual void setOverrideMode (const std::string &mode)
Overrides the display mode with mode.
const std::string getOverrideMode ()
virtual void getTaskViewContent (std::vector< Gui::TaskView::TaskContent * > &) const
get a list of TaskBoxes associated with this object
virtual bool selectAll ()
virtual bool keyPressed (bool pressed, int key)
is called when the provider is in edit and a key event occurs. Only ESC ends edit.
virtual const char * getTransactionText () const
virtual bool doubleClicked ()
is called by the tree if the user double clicks on the object
virtual bool mouseMove (const SbVec2s &cursorPos, View3DInventorViewer *viewer)
is called when the provider is in edit and the mouse is moved
virtual bool mouseButtonPressed (int button, bool pressed, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
is called when the Provider is in edit and the mouse is clicked
virtual bool mouseWheelEvent (int delta, const SbVec2s &cursorPos, const View3DInventorViewer *viewer)
virtual void setupContextMenu (QMenu *, QObject *, const char *)
set up the context-menu with the supported edit modes
virtual QIcon getIcon () const
deliver the icon shown in the tree view
virtual QIcon mergeColorfulOverlayIcons (const QIcon &orig) const
virtual std::vector< App::DocumentObject * > claimChildren () const
virtual std::vector< App::DocumentObject * > claimChildrenRecursive () const
virtual void update (const App::Property *)
bool isUpdatesEnabled () const
void setUpdatesEnabled (bool enable)
unsigned long getStatus () const
return the status bits
bool testStatus (ViewStatus pos) const
void setStatus (ViewStatus pos, bool on)
std::string toString () const
PyObject * getPyObject () override
virtual std::map< std::string, App::Color > getElementColors (const char *element=nullptr) const
virtual void setElementColors (const std::map< std::string, App::Color > &colors)
virtual ViewProvider * startEditing (int ModNum=0)
bool isEditing () const
void finishEditing ()
virtual void setEditViewer (View3DInventorViewer *, int ModNum)
adjust viewer settings when editing a view provider
virtual void unsetEditViewer (View3DInventorViewer *)
restores viewer settings when leaving editing mode
virtual void setTransformation (const Base::Matrix4D &rcMatrix)
set the viewing transformation of the provider
virtual void setTransformation (const SbMatrix &rcMatrix)
virtual MDIView * getMDIView () const
void Restore (Base::XMLReader &reader) override
bool isRestoring ()
void addDisplayMaskMode (SoNode *node, const char *type)
Adds a new display mask mode.
void setDisplayMaskMode (const char *type)
Activates the display mask mode type.
SoNode * getDisplayMaskMode (const char *type) const
Get the node to the display mask mode type.
std::vector< std::string > getDisplayMaskModes () const
Returns a list of added display mask modes.
void setDefaultMode (int)
int getDefaultMode () const
virtual void setRenderCacheMode (int)
Public Member Functions inherited from App::TransactionalObject
TransactionalObject ()
Constructor.
~TransactionalObject () override
virtual bool isAttachedToDocument () const
virtual const char * detachFromDocument ()
Public Member Functions inherited from App::ExtensionContainer
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
Property * getPropertyByName (const char *name) const override
find a property by its name
template<typename T >
T * getPropertyByName (const char *name) const
find a property by its name, dynamic cased to specified type
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void onChanged (const Property *) override
get called by the container when a property has changed
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop) override
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual std::string getFullName () const
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
virtual App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false)
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual bool removeDynamicProperty (const char *name)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
virtual void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus)
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Attributes
std::vector< std::string > modes
Protected Attributes inherited from Gui::ViewProvider
SoSeparator * pcRoot
The root Separator of the ViewProvider.
SoTransform * pcTransform
this is transformation for the provider
const char * sPixmap
SoSwitch * pcModeSwitch
this is the mode switch, all the different viewing modes are collected here
SoSeparator * pcAnnotation {nullptr}
The root separator for annotations.
ViewProviderPy * pyViewObject {nullptr}
std::string overrideMode
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Additional Inherited Members
Public Types inherited from Gui::ViewProvider
enum EditMode { Default = 0, Transform, Cutting, Color }
Public Types inherited from App::ExtensionContainer
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Static Public Member Functions inherited from Gui::ViewProvider
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
static SbMatrix convert (const Base::Matrix4D &rcMatrix)
static Base::Matrix4D convert (const SbMatrix &sbMat)
static void eventCallback (void *ud, SoEventCallback *node)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from Gui::ViewProvider
boost::signals2::signal< void()> signalChangeIcon
signal on icon change
boost::signals2::signal< void(const QString &)> signalChangeToolTip
signal on tooltip change
boost::signals2::signal< void(const QString &)> signalChangeStatusTip
signal on status tip change
boost::signals2::signal< void(bool, Gui::HighlightMode)> signalChangeHighlight
signal on highlight change
Protected Member Functions inherited from Gui::ViewProvider
virtual QIcon mergeGreyableOverlayIcons (const QIcon &orig) const
virtual void setModeSwitch ()
Turn on mode switch.
virtual bool setEdit (int ModNum)
is called by the document when the provider goes in edit mode
virtual void unsetEdit (int ModNum)
is called when you lose the edit mode
int getEditingMode () const
return the edit mode or -1 if nothing is being edited
bool checkRecursion (SoNode *)
SoPickedPoint * getPointOnRay (const SbVec2s &pos, const View3DInventorViewer *viewer) const
SoPickedPoint * getPointOnRay (const SbVec3f &pos, const SbVec3f &dir, const View3DInventorViewer *viewer) const
void onBeforeChange (const App::Property *prop) override
Reimplemented from subclass.
void onChanged (const App::Property *prop) override
Reimplemented from subclass.
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual void onEarlyChange (const Property *)
virtual const PropertyData & getPropertyData () const
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 36 of file ViewProviderExtern.h.
Constructor & Destructor Documentation
ViewProviderExtern()
ViewProviderExtern::ViewProviderExtern () default
constructor.
~ViewProviderExtern()
ViewProviderExtern::~ViewProviderExtern () override default
destructor.
Member Function Documentation
adjustDocumentName()
void ViewProviderExtern::adjustDocumentName (const char * docname)
Definition at line 112 of file ViewProviderExtern.cpp.
References SplineSurface::i, and Gui::ViewProvider::pcModeSwitch.
getDefaultDisplayMode()
const char * ViewProviderExtern::getDefaultDisplayMode () const override virtual
get the default display mode
Reimplemented from Gui::ViewProvider.
Definition at line 134 of file ViewProviderExtern.cpp.
References modes.
getDisplayModes()
std::vector< std::string > ViewProviderExtern::getDisplayModes () const override virtual
returns a list of all possible display modes
Reimplemented from Gui::ViewProvider.
Definition at line 140 of file ViewProviderExtern.cpp.
References modes.
setModeByFile()
void ViewProviderExtern::setModeByFile (const char * name, const char * ivFileName)
Definition at line 58 of file ViewProviderExtern.cpp.
References SCL.SimpleDataTypes::c, DrawingExample::file, and setModeBySoInput().
setModeBySoInput()
void ViewProviderExtern::setModeBySoInput (const char * name, SoInput & ivFileInput)
Definition at line 86 of file ViewProviderExtern.cpp.
References Gui::ViewProvider::addDisplayMaskMode(), modes, RobotExample::pos, and Gui::ViewProvider::setDisplayMaskMode().
Referenced by setModeByFile(), and setModeByString().
setModeByString()
void ViewProviderExtern::setModeByString (const char * name, const char * ivFragment)
Definition at line 51 of file ViewProviderExtern.cpp.
References setModeBySoInput().
Referenced by Gui::View3DInventorPy::setAnnotation().
updateData()
void Gui::ViewProviderExtern::updateData (const App::Property *) inline override virtual
Reimplemented from Gui::ViewProvider.
Definition at line 54 of file ViewProviderExtern.h.
Referenced by Path.Main.Gui.JobDlg.JobCreate::exec_(), draftviewproviders.view_wire.ViewProviderWire::onChanged(), draftviewproviders.view_dimension.ViewProviderLinearDimension::onChanged(), draftviewproviders.view_dimension.ViewProviderAngularDimension::onChanged(), Path.Op.Gui.Base.TaskPanelPage::pageUpdateData(), Path.Base.Gui.SetupSheet.OpTaskPanel::setupUi(), and Path.Base.Gui.PropertyBag.TaskPanel::setupUi().
Member Data Documentation
modes
std::vector<std::string> Gui::ViewProviderExtern::modes protected
Definition at line 60 of file ViewProviderExtern.h.
Referenced by getDefaultDisplayMode(), getDisplayModes(), and setModeBySoInput().
The documentation for this class was generated from the following files:
ViewProviderExtern.h
ViewProviderExtern.cpp