FreeCAD: App::ObjectIdentifier::Component Class Reference
App::ObjectIdentifier::Component Class Reference
A component is a part of a Path object, and is used to either name a property or a field within a property. A component can be either a single entry, and array, or a map to other sub-fields.
#include <ObjectIdentifier.h>
Public Member Functions
Component (const Component &)=default
Component & operator= (const Component &)=default
Component (Component &&other)
Component & operator= (Component &&other)
Component (const String &_name=String(), typeEnum _type=SIMPLE, int begin=INT_MAX, int end=INT_MAX, int step=1)
Construct a Component part.
Component (String &&_name, typeEnum _type=SIMPLE, int begin=INT_MAX, int end=INT_MAX, int step=1)
bool isSimple () const
bool isMap () const
bool isArray () const
bool isRange () const
void toString (std::ostream &ss, bool toPython=false) const
Create a string representation of a component.
const std::string & getName () const
int getIndex () const
size_t getIndex (size_t count) const
int getBegin () const
int getEnd () const
int getStep () const
bool operator== (const Component &other) const
Comparison operator for Component objects.
bool operator< (const Component &other) const
Py::Object get (const Py::Object &pyobj) const
void set (Py::Object &pyobj, const Py::Object &value) const
void del (Py::Object &pyobj) const
Static Public Member Functions
static Component SimpleComponent (const char *_component)
Create a simple component part with the given name.
static Component SimpleComponent (const String &_component)
Create a simple component part with the given name.
static Component SimpleComponent (String &&_component)
static Component ArrayComponent (int _index)
Create an array component with given name and index.
static Component RangeComponent (int _begin, int _end=INT_MAX, int _step=1)
Create a range component with given begin and end.
static Component MapComponent (const String &_key)
Create a map component with given name and key.
static Component MapComponent (String &&_key)
Friends
class ObjectIdentifier
Detailed Description
A component is a part of a Path object, and is used to either name a property or a field within a property. A component can be either a single entry, and array, or a map to other sub-fields.
Definition at line 188 of file ObjectIdentifier.h.
Constructor & Destructor Documentation
Component() [1/4]
App::ObjectIdentifier::Component::Component (const Component &) default
Component() [2/4]
App::ObjectIdentifier::Component::Component (Component && other) inline
Definition at line 202 of file ObjectIdentifier.h.
Component() [3/4]
ObjectIdentifier::Component::Component (const String & _name = String(), typeEnum _type = SIMPLE, int _begin = INT_MAX, int _end = INT_MAX, int _step = 1)
Construct a Component part.
Parameters
_name Name of component
_type Type; simple, array, range or map
_begin Array index or beginning of a Range, or INT_MAX for other type.
_end ending of a Range, or INT_MAX for other type.
Definition at line 643 of file ObjectIdentifier.cpp.
Component() [4/4]
ObjectIdentifier::Component::Component (String && _name, typeEnum _type = SIMPLE, int begin = INT_MAX, int end = INT_MAX, int step = 1)
Definition at line 655 of file ObjectIdentifier.cpp.
Member Function Documentation
ArrayComponent()
ObjectIdentifier::Component ObjectIdentifier::Component::ArrayComponent (int _index) static
Create an array component with given name and index.
Parameters
_component Name of component
_index Index of component
Returns
A new Component object.
Definition at line 819 of file ObjectIdentifier.cpp.
References src.Mod.Test.testmakeWireString::String.
del()
void ObjectIdentifier::Component::del (Py::Object & pyobj) const
Definition at line 755 of file ObjectIdentifier.cpp.
References BOPTools.SplitAPI::slice(), and Base::PyException::ThrowException().
get()
Py::Object ObjectIdentifier::Component::get (const Py::Object & pyobj) const
Definition at line 684 of file ObjectIdentifier.cpp.
References FC_THROWM, App::ExpressionParser::isModuleImported(), BOPTools.SplitAPI::slice(), and Base::PyException::ThrowException().
Referenced by draftguitools.gui_trackers.editTracker::move().
getBegin()
int App::ObjectIdentifier::Component::getBegin () const inline
Definition at line 272 of file ObjectIdentifier.h.
getEnd()
int App::ObjectIdentifier::Component::getEnd () const inline
Definition at line 276 of file ObjectIdentifier.h.
getIndex() [1/2]
int App::ObjectIdentifier::Component::getIndex () const inline
Definition at line 266 of file ObjectIdentifier.h.
getIndex() [2/2]
size_t ObjectIdentifier::Component::getIndex (size_t count) const
Definition at line 668 of file ObjectIdentifier.cpp.
References src.Mod.AddonManager.NetworkManager::count, and FC_THROWM.
getName()
const std::string& App::ObjectIdentifier::Component::getName () const inline
Definition at line 261 of file ObjectIdentifier.h.
Referenced by App::VariableExpression::_moveCells(), and App::VariableExpression::_offsetCells().
getStep()
int App::ObjectIdentifier::Component::getStep () const inline
Definition at line 280 of file ObjectIdentifier.h.
isArray()
bool App::ObjectIdentifier::Component::isArray () const inline
Definition at line 247 of file ObjectIdentifier.h.
References Path.Post.scripts.grbl_post::type.
isMap()
bool App::ObjectIdentifier::Component::isMap () const inline
Definition at line 242 of file ObjectIdentifier.h.
References Path.Post.scripts.grbl_post::type.
isRange()
bool App::ObjectIdentifier::Component::isRange () const inline
Definition at line 252 of file ObjectIdentifier.h.
References Path.Post.scripts.grbl_post::type.
isSimple()
bool App::ObjectIdentifier::Component::isSimple () const inline
Definition at line 237 of file ObjectIdentifier.h.
References Path.Post.scripts.grbl_post::type.
MapComponent() [1/2]
ObjectIdentifier::Component ObjectIdentifier::Component::MapComponent (const String & _key) static
Create a map component with given name and key.
Parameters
_component Name of component
_key Key of component
Returns
A new Component object.
Definition at line 831 of file ObjectIdentifier.cpp.
MapComponent() [2/2]
ObjectIdentifier::Component ObjectIdentifier::Component::MapComponent (String && _key) static
Definition at line 836 of file ObjectIdentifier.cpp.
References Path.Post.scripts.opensbp_post::move().
operator<()
bool App::ObjectIdentifier::Component::operator< (const Component & other) const
operator=() [1/2]
Component& App::ObjectIdentifier::Component::operator= (Component && other) inline
Definition at line 202 of file ObjectIdentifier.h.
References Path.Post.scripts.opensbp_post::move(), and Path.Post.scripts.grbl_post::type.
operator=() [2/2]
Component& App::ObjectIdentifier::Component::operator= (const Component &) default
operator==()
bool ObjectIdentifier::Component::operator== (const Component & other) const
Comparison operator for Component objects.
Parameters
other The object we want to compare to.
Returns
true if they are equal, false if not.
Definition at line 861 of file ObjectIdentifier.cpp.
References Path.Post.scripts.grbl_post::type.
RangeComponent()
ObjectIdentifier::Component ObjectIdentifier::Component::RangeComponent (int _begin, int _end = INT_MAX, int _step = 1) static
Create a range component with given begin and end.
Parameters
_begin beginning index of the range
_end ending index of the range
Returns
A new Component object.
Definition at line 850 of file ObjectIdentifier.cpp.
References src.Mod.Test.testmakeWireString::String.
set()
void ObjectIdentifier::Component::set (Py::Object & pyobj, const Py::Object & value) const
Definition at line 725 of file ObjectIdentifier.cpp.
References BOPTools.SplitAPI::slice(), and Base::PyException::ThrowException().
Referenced by draftguitools.gui_trackers.editTracker::move().
SimpleComponent() [1/3]
ObjectIdentifier::Component ObjectIdentifier::Component::SimpleComponent (const char * _component) static
Create a simple component part with the given name.
Parameters
_component Name of component.
Returns
A new Component object.
Definition at line 789 of file ObjectIdentifier.cpp.
References src.Mod.Test.testmakeWireString::String.
Referenced by Part::PropertyPartShape::getPaths(), and Gui::QuantitySpinBox::setBoundToByName().
SimpleComponent() [2/3]
ObjectIdentifier::Component ObjectIdentifier::Component::SimpleComponent (const String & _component) static
Create a simple component part with the given name.
Parameters
_component Name of component.
Returns
A new Component object.
Definition at line 801 of file ObjectIdentifier.cpp.
SimpleComponent() [3/3]
ObjectIdentifier::Component ObjectIdentifier::Component::SimpleComponent (ObjectIdentifier::String && _component) static
Definition at line 807 of file ObjectIdentifier.cpp.
References Path.Post.scripts.opensbp_post::move().
toString()
void ObjectIdentifier::Component::toString (std::ostream & ss, bool toPython = false) const
Create a string representation of a component.
Returns
A string representing the component.
Definition at line 886 of file ObjectIdentifier.cpp.
References Path.Post.scripts.grbl_post::type.
Friends And Related Function Documentation
ObjectIdentifier
friend class ObjectIdentifier friend
Definition at line 300 of file ObjectIdentifier.h.
The documentation for this class was generated from the following files:
ObjectIdentifier.h
ObjectIdentifier.cpp