FreeCAD: Materials::MaterialValue Class Reference
Materials::MaterialValue Class Reference
#include <MaterialValue.h>
Public Types
enum ValueType {
None = 0, String = 1, Boolean = 2, Integer = 3,
Float = 4, Quantity = 5, Distribution = 6, List = 7,
Array2D = 8, Array3D = 9, Color = 10, Image = 11,
File = 12, URL = 13, MultiLineString = 14, FileList = 15,
ImageList = 16, SVG
}
Public Member Functions
MaterialValue ()
MaterialValue (const MaterialValue &other)
MaterialValue (ValueType type)
virtual ~MaterialValue ()=default
MaterialValue & operator= (const MaterialValue &other)
virtual bool operator== (const MaterialValue &other) const
bool operator!= (const MaterialValue &other) const
ValueType getType () const
QVariant getValue () const
QList< QVariant > getList ()
const QList< QVariant > getList () const
virtual bool isNull () const
virtual const QVariant getValueAt (const QVariant &value) const
void setValue (const QVariant &value)
void setList (const QList< QVariant > &value)
virtual QString getYAMLString () const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static QString escapeString (const QString &source)
static ValueType mapType (const QString &stringType)
static const Base::QuantityFormat getQuantityFormat ()
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Attributes
static const int PRECISION = 6
Protected Member Functions
MaterialValue (ValueType type, ValueType inherited)
void setType (ValueType type)
void setInitialValue (ValueType inherited)
QString getYAMLStringImage () const
QString getYAMLStringList () const
QString getYAMLStringImageList () const
QString getYAMLStringMultiLine () const
Protected Attributes
ValueType _valueType
QVariant _value
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 57 of file MaterialValue.h.
Member Enumeration Documentation
ValueType
enum Materials::MaterialValue::ValueType
Enumerator
None
String
Boolean
Integer
Float
Quantity
Distribution
List
Array2D
Array3D
Color
Image
File
URL
MultiLineString
FileList
ImageList
SVG
Definition at line 81 of file MaterialValue.h.
Constructor & Destructor Documentation
MaterialValue() [1/4]
MaterialValue::MaterialValue ()
Definition at line 62 of file MaterialValue.cpp.
References None, and setInitialValue().
MaterialValue() [2/4]
MaterialValue::MaterialValue (const MaterialValue & other) explicit
Definition at line 68 of file MaterialValue.cpp.
MaterialValue() [3/4]
MaterialValue::MaterialValue (ValueType type) explicit
Definition at line 73 of file MaterialValue.cpp.
References None, and setInitialValue().
~MaterialValue()
virtual Materials::MaterialValue::~MaterialValue () virtual default
MaterialValue() [4/4]
MaterialValue::MaterialValue (ValueType type, ValueType inherited) protected
Definition at line 79 of file MaterialValue.cpp.
References setInitialValue().
Member Function Documentation
escapeString()
QString MaterialValue::escapeString (const QString & source) static
Definition at line 106 of file MaterialValue.cpp.
Referenced by getYAMLString(), getYAMLStringList(), Materials::Material::saveAppearanceModels(), Materials::Material::saveGeneral(), and Materials::Material::saveModels().
getList() [1/2]
QList<QVariant> Materials::MaterialValue::getList () inline
Definition at line 123 of file MaterialValue.h.
Referenced by getYAMLString(), getYAMLStringImageList(), and getYAMLStringList().
getList() [2/2]
const QList<QVariant> Materials::MaterialValue::getList () const inline
Definition at line 127 of file MaterialValue.h.
getQuantityFormat()
const Base::QuantityFormat MaterialValue::getQuantityFormat () static
Definition at line 314 of file MaterialValue.cpp.
References PRECISION.
Referenced by MatGui::Array2DModel::data(), MatGui::Array3DDepthModel::data(), MatGui::Array3DModel::data(), MatGui::Array3DDepthModel::insertRows(), and Materials::MaterialProperty::setQuantity().
getType()
ValueType Materials::MaterialValue::getType () const inline
Definition at line 114 of file MaterialValue.h.
Referenced by getYAMLString().
getValue()
QVariant Materials::MaterialValue::getValue () const inline
Definition at line 119 of file MaterialValue.h.
References Path.Post.scripts.grbl_post::type.
Referenced by Materials::Material3DArray::getValue(), getYAMLString(), getYAMLStringImage(), and getYAMLStringMultiLine().
getValueAt()
virtual const QVariant Materials::MaterialValue::getValueAt (const QVariant & value) const inline virtual
Definition at line 133 of file MaterialValue.h.
getYAMLString()
QString MaterialValue::getYAMLString () const virtual
Reimplemented in Materials::Material3DArray, and Materials::Material2DArray.
Definition at line 273 of file MaterialValue.cpp.
References escapeString(), FileList, Float, getList(), getType(), getValue(), getYAMLStringImage(), getYAMLStringImageList(), getYAMLStringList(), getYAMLStringMultiLine(), Image, ImageList, isNull(), List, MultiLineString, Quantity, and SVG.
getYAMLStringImage()
QString MaterialValue::getYAMLStringImage () const protected
Definition at line 225 of file MaterialValue.cpp.
References getValue().
Referenced by getYAMLString().
getYAMLStringImageList()
QString MaterialValue::getYAMLStringImageList () const protected
Definition at line 247 of file MaterialValue.cpp.
References getList().
Referenced by getYAMLString().
getYAMLStringList()
QString MaterialValue::getYAMLStringList () const protected
Definition at line 237 of file MaterialValue.cpp.
References escapeString(), and getList().
Referenced by getYAMLString().
getYAMLStringMultiLine()
QString MaterialValue::getYAMLStringMultiLine () const protected
Definition at line 261 of file MaterialValue.cpp.
References getValue(), and src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression.
Referenced by getYAMLString().
isNull()
bool MaterialValue::isNull () const virtual
Reimplemented in Materials::Material3DArray, and Materials::Material2DArray.
Definition at line 208 of file MaterialValue.cpp.
References _value, _valueType, FileList, ImageList, femsolver.elmer.sifio::isValid(), List, and Quantity.
Referenced by getYAMLString().
mapType()
MaterialValue::ValueType MaterialValue::mapType (const QString & stringType) static
Definition at line 114 of file MaterialValue.cpp.
References None.
Referenced by MatGui::MaterialDelegate::getType(), and Materials::MaterialProperty::setType().
operator!=()
bool Materials::MaterialValue::operator!= (const MaterialValue & other) const inline
Definition at line 109 of file MaterialValue.h.
operator=()
MaterialValue & MaterialValue::operator= (const MaterialValue & other)
Definition at line 85 of file MaterialValue.cpp.
References _value, and _valueType.
Referenced by Materials::Material2DArray::operator=().
operator==()
bool MaterialValue::operator== (const MaterialValue & other) const virtual
Definition at line 97 of file MaterialValue.cpp.
References _value, and _valueType.
setInitialValue()
void MaterialValue::setInitialValue (ValueType inherited) protected
Definition at line 120 of file MaterialValue.cpp.
References _value, _valueType, Array3D, Boolean, Color, File, FileList, Float, ImageList, Integer, List, MultiLineString, None, Quantity, Base::Quantity::setInvalid(), String, SVG, and URL.
Referenced by MaterialValue().
setList()
void MaterialValue::setList (const QList< QVariant > & value)
Definition at line 203 of file MaterialValue.cpp.
References _value.
setType()
void Materials::MaterialValue::setType (ValueType type) inline protected
Definition at line 156 of file MaterialValue.h.
setValue()
void Materials::MaterialValue::setValue (const QVariant & value) inline
Definition at line 138 of file MaterialValue.h.
Member Data Documentation
_value
QVariant Materials::MaterialValue::_value protected
Definition at line 168 of file MaterialValue.h.
Referenced by isNull(), operator=(), operator==(), setInitialValue(), and setList().
_valueType
ValueType Materials::MaterialValue::_valueType protected
Definition at line 167 of file MaterialValue.h.
Referenced by isNull(), operator=(), operator==(), and setInitialValue().
PRECISION
const int Materials::MaterialValue::PRECISION = 6 static
Definition at line 151 of file MaterialValue.h.
Referenced by Materials::MaterialProperty::getDictionaryString(), getQuantityFormat(), Materials::MaterialProperty::getString(), and Materials::Material::getValueString().
The documentation for this class was generated from the following files:
MaterialValue.h
MaterialValue.cpp