FreeCAD: Wm4 Namespace Reference
Wm4 Namespace Reference
The namespace of the WildMagic library.
Classes
class BandedMatrix
class Box2
class Box3
class ConvexHull
class ConvexHull1
class ConvexHull2
class ConvexHull3
class CylinderFit3
class Delaunay
class Delaunay1
class Delaunay2
class Delaunay3
class DelPolygonEdge
class DelPolyhedronFace
class DelTetrahedron
class DelTriangle
class Distance
class DistLine3Segment3
class DistLine3Triangle3
class DistSegment3Segment3
class DistSegment3Triangle3
class DistVector3Plane3
class DistVector3Segment3
class DistVector3Triangle3
class EdgeKey
class Eigen
class ETManifoldMesh
class GMatrix
class GVector
class ImplicitSurface
class Intersector
class Intersector1
class IntrLine3Box3
class IntrLine3Plane3
class IntrSegment3Box3
class IntrSegment3Plane3
class IntrTriangle2Triangle2
class IntrTriangle3Triangle3
class LinComp
class Line3
class LinearSystem
class Mapper2
class Mapper3
class Math
class Matrix2
class Matrix3
class Matrix4
class MeshCurvature
class MeshSmoother
class ParametricSurface
class Plane3
class Polynomial1
class PolynomialRoots
class PolynomialSurface
class QuadricSurface
class Quaternion
class Query
class Query2
class Query2Filtered
class Query2Int64
class Query2TInteger
class Query2TRational
class Query3
class Query3Filtered
class Query3Int64
class Query3TInteger
class Query3TRational
class RVector2
class RVector3
class Segment3
class Sphere3
class Surface
class System
class THashSet
class THashTable
class TInteger
class TMinHeap
class TMinHeapRecord
class TRational
class Triangle2
class Triangle3
class TriangleKey
class TriangulateEC
class TRVector
class TSmallUnorderedSet
class TStringHashTable
class TTuple
class UniqueVerticesTriangles
class Vector2
class Vector3
class Vector4
class VEManifoldMesh
Typedefs
typedef CylinderFit3< float > CylinderFit3f
typedef CylinderFit3< double > CylinderFit3d
typedef BandedMatrix< float > BandedMatrixf
typedef BandedMatrix< double > BandedMatrixd
typedef Box2< float > Box2f
typedef Box2< double > Box2d
typedef Box3< float > Box3f
typedef Box3< double > Box3d
typedef ConvexHull< float > ConvexHullf
typedef ConvexHull< double > ConvexHulld
typedef ConvexHull1< float > ConvexHull1f
typedef ConvexHull1< double > ConvexHull1d
typedef ConvexHull2< float > ConvexHull2f
typedef ConvexHull2< double > ConvexHull2d
typedef ConvexHull3< float > ConvexHull3f
typedef ConvexHull3< double > ConvexHull3d
typedef Delaunay< float > Delaunayf
typedef Delaunay< double > Delaunayd
typedef Delaunay1< float > Delaunay1f
typedef Delaunay1< double > Delaunay1d
typedef Delaunay2< float > Delaunay2f
typedef Delaunay2< double > Delaunay2d
typedef Delaunay3< float > Delaunay3f
typedef Delaunay3< double > Delaunay3d
typedef DelPolygonEdge< float > DelPolygonEdgef
typedef DelPolygonEdge< double > DelPolygonEdged
typedef DelPolyhedronFace< float > DelPolyhedronFacef
typedef DelPolyhedronFace< double > DelPolyhedronFaced
typedef DelTetrahedron< float > DelTetrahedronf
typedef DelTetrahedron< double > DelTetrahedrond
typedef DelTriangle< float > DelTrianglef
typedef DelTriangle< double > DelTriangled
typedef Distance< float, Vector2f > Distance2f
typedef Distance< float, Vector3f > Distance3f
typedef Distance< double, Vector2d > Distance2d
typedef Distance< double, Vector3d > Distance3d
typedef DistLine3Segment3< float > DistLine3Segment3f
typedef DistLine3Segment3< double > DistLine3Segment3d
typedef DistLine3Triangle3< float > DistLine3Triangle3f
typedef DistLine3Triangle3< double > DistLine3Triangle3d
typedef DistSegment3Segment3< float > DistSegment3Segment3f
typedef DistSegment3Segment3< double > DistSegment3Segment3d
typedef DistSegment3Triangle3< float > DistSegment3Triangle3f
typedef DistSegment3Triangle3< double > DistSegment3Triangle3d
typedef DistVector3Plane3< float > DistVector3Plane3f
typedef DistVector3Plane3< double > DistVector3Plane3d
typedef DistVector3Segment3< float > DistVector3Segment3f
typedef DistVector3Segment3< double > DistVector3Segment3d
typedef DistVector3Triangle3< float > DistVector3Triangle3f
typedef DistVector3Triangle3< double > DistVector3Triangle3d
typedef Eigen< float > Eigenf
typedef Eigen< double > Eigend
typedef GMatrix< float > GMatrixf
typedef GMatrix< double > GMatrixd
typedef GVector< float > GVectorf
typedef GVector< double > GVectord
typedef ImplicitSurface< float > ImplicitSurfacef
typedef ImplicitSurface< double > ImplicitSurfaced
typedef Intersector< float, Vector2< float > > Intersector2f
typedef Intersector< float, Vector3< float > > Intersector3f
typedef Intersector< double, Vector2< double > > Intersector2d
typedef Intersector< double, Vector3< double > > Intersector3d
typedef Intersector1< float > Intersector1f
typedef Intersector1< double > Intersector1d
typedef IntrLine3Box3< float > IntrLine3Box3f
typedef IntrLine3Box3< double > IntrLine3Box3d
typedef IntrLine3Plane3< float > IntrLine3Plane3f
typedef IntrLine3Plane3< double > IntrLine3Plane3d
typedef IntrSegment3Box3< float > IntrSegment3Box3f
typedef IntrSegment3Box3< double > IntrSegment3Box3d
typedef IntrSegment3Plane3< float > IntrSegment3Plane3f
typedef IntrSegment3Plane3< double > IntrSegment3Plane3d
typedef IntrTriangle2Triangle2< float > IntrTriangle2Triangle2f
typedef IntrTriangle2Triangle2< double > IntrTriangle2Triangle2d
typedef IntrTriangle3Triangle3< float > IntrTriangle3Triangle3f
typedef IntrTriangle3Triangle3< double > IntrTriangle3Triangle3d
typedef LinComp< float > LinCompf
typedef LinComp< double > LinCompd
typedef Line3< float > Line3f
typedef Line3< double > Line3d
typedef LinearSystem< float > LinearSystemf
typedef LinearSystem< double > LinearSystemd
typedef Mapper2< float > Mapper2f
typedef Mapper2< double > Mapper2d
typedef Mapper3< float > Mapper3f
typedef Mapper3< double > Mapper3d
typedef Math< float > Mathf
typedef Math< double > Mathd
typedef Matrix2< float > Matrix2f
typedef Matrix2< double > Matrix2d
typedef Matrix3< float > Matrix3f
typedef Matrix3< double > Matrix3d
typedef Matrix4< float > Matrix4f
typedef Matrix4< double > Matrix4d
typedef MeshCurvature< float > MeshCurvaturef
typedef MeshCurvature< double > MeshCurvatured
typedef MeshSmoother< float > MeshSmootherf
typedef MeshSmoother< double > MeshSmootherd
typedef ParametricSurface< float > ParametricSurfacef
typedef ParametricSurface< double > ParametricSurfaced
typedef Plane3< float > Plane3f
typedef Plane3< double > Plane3d
typedef Polynomial1< float > Polynomial1f
typedef Polynomial1< double > Polynomial1d
typedef PolynomialRoots< float > PolynomialRootsf
typedef PolynomialRoots< double > PolynomialRootsd
typedef QuadricSurface< float > QuadricSurfacef
typedef QuadricSurface< double > QuadricSurfaced
typedef Quaternion< float > Quaternionf
typedef Quaternion< double > Quaterniond
typedef Query2< float > Query2f
typedef Query2< double > Query2d
typedef Query2Filtered< float > Query2Filteredf
typedef Query2Filtered< double > Query2Filteredd
typedef Query2Int64< float > Query2Int64f
typedef Query2Int64< double > Query2Int64d
typedef Query2TInteger< float > Query2TIntegerf
typedef Query2TInteger< double > Query2TIntegerd
typedef Query2TRational< float > Query2TRationalf
typedef Query2TRational< double > Query2TRationald
typedef Query3< float > Query3f
typedef Query3< double > Query3d
typedef Query3Filtered< float > Query3Filteredf
typedef Query3Filtered< double > Query3Filteredd
typedef Query3Int64< float > Query3Int64f
typedef Query3Int64< double > Query3Int64d
typedef Query3TInteger< float > Query3TIntegerf
typedef Query3TInteger< double > Query3TIntegerd
typedef Query3TRational< float > Query3TRationalf
typedef Query3TRational< double > Query3TRationald
typedef Segment3< float > Segment3f
typedef Segment3< double > Segment3d
typedef Sphere3< float > Sphere3f
typedef Sphere3< double > Sphere3d
typedef Surface< float > Surfacef
typedef Surface< double > Surfaced
typedef Triangle2< float > Triangle2f
typedef Triangle2< double > Triangle2d
typedef Triangle3< float > Triangle3f
typedef Triangle3< double > Triangle3d
typedef Vector2< float > Vector2f
typedef Vector2< double > Vector2d
typedef Vector3< float > Vector3f
typedef Vector3< double > Vector3d
typedef Vector4< float > Vector4f
typedef Vector4< double > Vector4d
Functions
template<class Real >
Box2< Real > GaussPointsFit2 (int iQuantity, const Vector2< Real > *akPoint)
template Box2< float > GaussPointsFit2< float > (int, const Vector2< float > *)
template Box2< double > GaussPointsFit2< double > (int, const Vector2< double > *)
template<class Real >
Box3< Real > GaussPointsFit3 (int iQuantity, const Vector3< Real > *akPoint)
template Box3< float > GaussPointsFit3< float > (int, const Vector3< float > *)
template Box3< double > GaussPointsFit3< double > (int, const Vector3< double > *)
template<class Real >
Line3< Real > OrthogonalLineFit3 (int iQuantity, const Vector3< Real > *akPoint)
template Line3< float > OrthogonalLineFit3< float > (int, const Vector3< float > *)
template Line3< double > OrthogonalLineFit3< double > (int, const Vector3< double > *)
template<class Real >
bool HeightPlaneFit3 (int iQuantity, const Vector3< Real > *akPoint, Real &rfA, Real &rfB, Real &rfC)
template<class Real >
Plane3< Real > OrthogonalPlaneFit3 (int iQuantity, const Vector3< Real > *akPoint)
template bool HeightPlaneFit3< float > (int, const Vector3< float > *, float &, float &, float &)
template Plane3< float > OrthogonalPlaneFit3< float > (int, const Vector3< float > *)
template bool HeightPlaneFit3< double > (int, const Vector3< double > *, double &, double &, double &)
template Plane3< double > OrthogonalPlaneFit3< double > (int, const Vector3< double > *)
template<class Real >
Real * PolyFit3 (int iSamples, const Real *afX, const Real *afY, const Real *afW, int iXDegree, int iYDegree)
template float * PolyFit3< float > (int, const float *, const float *, const float *, int, int)
template double * PolyFit3< double > (int, const double *, const double *, const double *, int, int)
template<class Real >
Real QuadraticFit3 (int iQuantity, const Vector3< Real > *akPoint, Real afCoeff[10])
template<class Real >
Real QuadraticSphereFit3 (int iQuantity, const Vector3< Real > *akPoint, Vector3< Real > &rkCenter, Real &rfRadius)
template float QuadraticFit3< float > (int, const Vector3< float > *, float[10])
template float QuadraticSphereFit3< float > (int, const Vector3< float > *, Vector3< float > &, float &)
template double QuadraticFit3< double > (int, const Vector3< double > *, double[10])
template double QuadraticSphereFit3< double > (int, const Vector3< double > *, Vector3< double > &, double &)
template<class Real >
bool SphereFit3 (int iQuantity, const Vector3< Real > *akPoint, int iMaxIterations, Sphere3< Real > &rkSphere, bool bInitialCenterIsAverage)
template bool SphereFit3< float > (int, const Vector3< float > *, int, Sphere3< float > &, bool)
template bool SphereFit3< double > (int, const Vector3< double > *, int, Sphere3< double > &, bool)
template<class Real >
Box2< Real > ContAlignedBox (int iQuantity, const Vector2< Real > *akPoint)
template<class Real >
Box2< Real > ContOrientedBox (int iQuantity, const Vector2< Real > *akPoint)
template<class Real >
static void UpdateBox (const Vector2< Real > &rkLPoint, const Vector2< Real > &rkRPoint, const Vector2< Real > &rkBPoint, const Vector2< Real > &rkTPoint, const Vector2< Real > &rkU, const Vector2< Real > &rkV, Real &rfMinAreaDiv4, Box2< Real > &rkBox)
template<class Real >
Box2< Real > ContMinBox (int iQuantity, const Vector2< Real > *akPoint, Real fEpsilon, Query::Type eQueryType, bool bIsConvexPolygon)
template<class Real >
bool InBox (const Vector2< Real > &rkPoint, const Box2< Real > &rkBox)
template<class Real >
Box2< Real > MergeBoxes (const Box2< Real > &rkBox0, const Box2< Real > &rkBox1)
template Box2< float > ContAlignedBox< float > (int, const Vector2< float > *)
template Box2< float > ContOrientedBox< float > (int, const Vector2< float > *)
template Box2< float > ContMinBox< float > (int, const Vector2< float > *, float, Query::Type, bool)
template bool InBox< float > (const Vector2< float > &, const Box2< float > &)
template Box2< float > MergeBoxes< float > (const Box2< float > &, const Box2< float > &)
template Box2< double > ContAlignedBox< double > (int, const Vector2< double > *)
template Box2< double > ContOrientedBox< double > (int, const Vector2< double > *)
template Box2< double > ContMinBox< double > (int, const Vector2< double > *, double, Query::Type, bool)
template bool InBox< double > (const Vector2< double > &, const Box2< double > &)
template Box2< double > MergeBoxes< double > (const Box2< double > &, const Box2< double > &)
template<class Real >
Box3< Real > ContAlignedBox (int iQuantity, const Vector3< Real > *akPoint)
template<class Real >
Box3< Real > ContOrientedBox (int iQuantity, const Vector3< Real > *akPoint)
template<class Real >
Box3< Real > ContMinBox (int iQuantity, const Vector3< Real > *akPoint, Real fEpsilon, Query::Type eQueryType)
template<class Real >
bool InBox (const Vector3< Real > &rkPoint, const Box3< Real > &rkBox)
template<class Real >
Box3< Real > MergeBoxes (const Box3< Real > &rkBox0, const Box3< Real > &rkBox1)
template Box3< float > ContAlignedBox< float > (int, const Vector3< float > *)
template Box3< float > ContOrientedBox< float > (int, const Vector3< float > *)
template Box3< float > ContMinBox< float > (int, const Vector3< float > *, float, Query::Type)
template bool InBox< float > (const Vector3< float > &, const Box3< float > &)
template Box3< float > MergeBoxes< float > (const Box3< float > &, const Box3< float > &)
template Box3< double > ContAlignedBox< double > (int, const Vector3< double > *)
template Box3< double > ContOrientedBox< double > (int, const Vector3< double > *)
template Box3< double > ContMinBox< double > (int, const Vector3< double > *, double, Query::Type)
template bool InBox< double > (const Vector3< double > &, const Box3< double > &)
template Box3< double > MergeBoxes< double > (const Box3< double > &, const Box3< double > &)
template<class Real >
GMatrix< Real > operator* (Real fScalar, const GMatrix< Real > &rkM)
template<class Real >
GVector< Real > operator* (const GVector< Real > &rkV, const GMatrix< Real > &rkM)
template<class Real >
GVector< Real > operator* (Real fScalar, const GVector< Real > &rkV)
template<class Real >
Matrix2< Real > operator* (Real fScalar, const Matrix2< Real > &rkM)
template<class Real >
Vector2< Real > operator* (const Vector2< Real > &rkV, const Matrix2< Real > &rkM)
template<class Real >
Matrix3< Real > operator* (Real fScalar, const Matrix3< Real > &rkM)
template<class Real >
Vector3< Real > operator* (const Vector3< Real > &rkV, const Matrix3< Real > &rkM)
template<class Real >
Matrix4< Real > operator* (Real fScalar, const Matrix4< Real > &rkM)
template<class Real >
Vector4< Real > operator* (const Vector4< Real > &rkV, const Matrix4< Real > &rkM)
template<class Real >
Polynomial1< Real > operator* (Real fScalar, const Polynomial1< Real > &rkPoly)
template<class Real >
Quaternion< Real > operator* (Real fScalar, const Quaternion< Real > &rkQ)
template<class T >
void Allocate (int iCols, int iRows, T **&raatArray)
template<class T >
static void Deallocate (T **&raatArray)
template<class T >
void Allocate (int iCols, int iRows, int iSlices, T ***&raaatArray)
template<class T >
void Deallocate (T ***&raaatArray)
template<int N>
TInteger< N > operator* (int i, const TInteger< N > &rkI)
template<int N>
TRational< N > operator+ (const TInteger< N > &rkI, const TRational< N > &rkR)
template<int N>
TRational< N > operator- (const TInteger< N > &rkI, const TRational< N > &rkR)
template<int N>
TRational< N > operator* (const TInteger< N > &rkI, const TRational< N > &rkR)
template<int N>
TRational< N > operator/ (const TInteger< N > &rkI, const TRational< N > &rkR)
template<int VSIZE, int ISIZE>
TRVector< VSIZE, ISIZE > operator* (const TRational< ISIZE > &rkR, const TRVector< VSIZE, ISIZE > &rkV)
template<class Real >
Vector2< Real > operator* (Real fScalar, const Vector2< Real > &rkV)
template<class Real >
std::ostream & operator<< (std::ostream &rkOStr, const Vector2< Real > &rkV)
template<class Real >
Vector3< Real > operator* (Real fScalar, const Vector3< Real > &rkV)
template<class Real >
std::ostream & operator<< (std::ostream &rkOStr, const Vector3< Real > &rkV)
template<class Real >
Vector4< Real > operator* (Real fScalar, const Vector4< Real > &rkV)
template<class Real >
std::ostream & operator<< (std::ostream &rkOStr, const Vector4< Real > &rkV)
Detailed Description
The namespace of the WildMagic library.
Typedef Documentation
BandedMatrixd
typedef BandedMatrix<double> Wm4::BandedMatrixd
Definition at line 74 of file Wm4BandedMatrix.h.
BandedMatrixf
typedef BandedMatrix<float> Wm4::BandedMatrixf
Definition at line 73 of file Wm4BandedMatrix.h.
Box2d
typedef Box2<double> Wm4::Box2d
Definition at line 44 of file Wm4Box2.h.
Box2f
typedef Box2<float> Wm4::Box2f
Definition at line 43 of file Wm4Box2.h.
Box3d
typedef Box3<double> Wm4::Box3d
Definition at line 57 of file Wm4Box3.h.
Box3f
typedef Box3<float> Wm4::Box3f
Definition at line 56 of file Wm4Box3.h.
ConvexHull1d
typedef ConvexHull1<double> Wm4::ConvexHull1d
Definition at line 69 of file Wm4ConvexHull1.h.
ConvexHull1f
typedef ConvexHull1<float> Wm4::ConvexHull1f
Definition at line 68 of file Wm4ConvexHull1.h.
ConvexHull2d
typedef ConvexHull2<double> Wm4::ConvexHull2d
Definition at line 92 of file Wm4ConvexHull2.h.
ConvexHull2f
typedef ConvexHull2<float> Wm4::ConvexHull2f
Definition at line 91 of file Wm4ConvexHull2.h.
ConvexHull3d
typedef ConvexHull3<double> Wm4::ConvexHull3d
Definition at line 122 of file Wm4ConvexHull3.h.
ConvexHull3f
typedef ConvexHull3<float> Wm4::ConvexHull3f
Definition at line 121 of file Wm4ConvexHull3.h.
ConvexHulld
typedef ConvexHull<double> Wm4::ConvexHulld
Definition at line 96 of file Wm4ConvexHull.h.
ConvexHullf
typedef ConvexHull<float> Wm4::ConvexHullf
Definition at line 95 of file Wm4ConvexHull.h.
CylinderFit3d
typedef CylinderFit3<double> Wm4::CylinderFit3d
Definition at line 78 of file Wm4ApprCylinderFit3.h.
CylinderFit3f
typedef CylinderFit3<float> Wm4::CylinderFit3f
Definition at line 77 of file Wm4ApprCylinderFit3.h.
Delaunay1d
typedef Delaunay1<double> Wm4::Delaunay1d
Definition at line 113 of file Wm4Delaunay1.h.
Delaunay1f
typedef Delaunay1<float> Wm4::Delaunay1f
Definition at line 112 of file Wm4Delaunay1.h.
Delaunay2d
typedef Delaunay2<double> Wm4::Delaunay2d
Definition at line 171 of file Wm4Delaunay2.h.
Delaunay2f
typedef Delaunay2<float> Wm4::Delaunay2f
Definition at line 170 of file Wm4Delaunay2.h.
Delaunay3d
typedef Delaunay3<double> Wm4::Delaunay3d
Definition at line 186 of file Wm4Delaunay3.h.
Delaunay3f
typedef Delaunay3<float> Wm4::Delaunay3f
Definition at line 185 of file Wm4Delaunay3.h.
Delaunayd
typedef Delaunay<double> Wm4::Delaunayd
Definition at line 165 of file Wm4Delaunay.h.
Delaunayf
typedef Delaunay<float> Wm4::Delaunayf
Definition at line 164 of file Wm4Delaunay.h.
DelPolygonEdged
typedef DelPolygonEdge<double> Wm4::DelPolygonEdged
Definition at line 41 of file Wm4DelPolygonEdge.h.
DelPolygonEdgef
typedef DelPolygonEdge<float> Wm4::DelPolygonEdgef
Definition at line 40 of file Wm4DelPolygonEdge.h.
DelPolyhedronFaced
typedef DelPolyhedronFace<double> Wm4::DelPolyhedronFaced
Definition at line 41 of file Wm4DelPolyhedronFace.h.
DelPolyhedronFacef
typedef DelPolyhedronFace<float> Wm4::DelPolyhedronFacef
Definition at line 40 of file Wm4DelPolyhedronFace.h.
DelTetrahedrond
typedef DelTetrahedron<double> Wm4::DelTetrahedrond
Definition at line 44 of file Wm4DelTetrahedron.h.
DelTetrahedronf
typedef DelTetrahedron<float> Wm4::DelTetrahedronf
Definition at line 43 of file Wm4DelTetrahedron.h.
DelTriangled
typedef DelTriangle<double> Wm4::DelTriangled
Definition at line 44 of file Wm4DelTriangle.h.
DelTrianglef
typedef DelTriangle<float> Wm4::DelTrianglef
Definition at line 43 of file Wm4DelTriangle.h.
Distance2d
typedef Distance<double,Vector2d> Wm4::Distance2d
Definition at line 95 of file Wm4Distance.h.
Distance2f
typedef Distance<float,Vector2f> Wm4::Distance2f
Definition at line 93 of file Wm4Distance.h.
Distance3d
typedef Distance<double,Vector3d> Wm4::Distance3d
Definition at line 96 of file Wm4Distance.h.
Distance3f
typedef Distance<float,Vector3f> Wm4::Distance3f
Definition at line 94 of file Wm4Distance.h.
DistLine3Segment3d
typedef DistLine3Segment3<double> Wm4::DistLine3Segment3d
Definition at line 67 of file Wm4DistLine3Segment3.h.
DistLine3Segment3f
typedef DistLine3Segment3<float> Wm4::DistLine3Segment3f
Definition at line 66 of file Wm4DistLine3Segment3.h.
DistLine3Triangle3d
typedef DistLine3Triangle3<double> Wm4::DistLine3Triangle3d
Definition at line 67 of file Wm4DistLine3Triangle3.h.
DistLine3Triangle3f
typedef DistLine3Triangle3<float> Wm4::DistLine3Triangle3f
Definition at line 66 of file Wm4DistLine3Triangle3.h.
DistSegment3Segment3d
typedef DistSegment3Segment3<double> Wm4::DistSegment3Segment3d
Definition at line 66 of file Wm4DistSegment3Segment3.h.
DistSegment3Segment3f
typedef DistSegment3Segment3<float> Wm4::DistSegment3Segment3f
Definition at line 65 of file Wm4DistSegment3Segment3.h.
DistSegment3Triangle3d
typedef DistSegment3Triangle3<double> Wm4::DistSegment3Triangle3d
Definition at line 67 of file Wm4DistSegment3Triangle3.h.
DistSegment3Triangle3f
typedef DistSegment3Triangle3<float> Wm4::DistSegment3Triangle3f
Definition at line 66 of file Wm4DistSegment3Triangle3.h.
DistVector3Plane3d
typedef DistVector3Plane3<double> Wm4::DistVector3Plane3d
Definition at line 58 of file Wm4DistVector3Plane3.h.
DistVector3Plane3f
typedef DistVector3Plane3<float> Wm4::DistVector3Plane3f
Definition at line 57 of file Wm4DistVector3Plane3.h.
DistVector3Segment3d
typedef DistVector3Segment3<double> Wm4::DistVector3Segment3d
Definition at line 64 of file Wm4DistVector3Segment3.h.
DistVector3Segment3f
typedef DistVector3Segment3<float> Wm4::DistVector3Segment3f
Definition at line 63 of file Wm4DistVector3Segment3.h.
DistVector3Triangle3d
typedef DistVector3Triangle3<double> Wm4::DistVector3Triangle3d
Definition at line 64 of file Wm4DistVector3Triangle3.h.
DistVector3Triangle3f
typedef DistVector3Triangle3<float> Wm4::DistVector3Triangle3f
Definition at line 63 of file Wm4DistVector3Triangle3.h.
Eigend
typedef Eigen<double> Wm4::Eigend
Definition at line 111 of file Wm4Eigen.h.
Eigenf
typedef Eigen<float> Wm4::Eigenf
Definition at line 110 of file Wm4Eigen.h.
GMatrixd
typedef GMatrix<double> Wm4::GMatrixd
Definition at line 146 of file Wm4GMatrix.h.
GMatrixf
typedef GMatrix<float> Wm4::GMatrixf
Definition at line 145 of file Wm4GMatrix.h.
GVectord
typedef GVector<double> Wm4::GVectord
Definition at line 92 of file Wm4GVector.h.
GVectorf
typedef GVector<float> Wm4::GVectorf
Definition at line 91 of file Wm4GVector.h.
ImplicitSurfaced
typedef ImplicitSurface<double> Wm4::ImplicitSurfaced
Definition at line 80 of file Wm4ImplicitSurface.h.
ImplicitSurfacef
typedef ImplicitSurface<float> Wm4::ImplicitSurfacef
Definition at line 79 of file Wm4ImplicitSurface.h.
Intersector1d
typedef Intersector1<double> Wm4::Intersector1d
Definition at line 71 of file Wm4Intersector1.h.
Intersector1f
typedef Intersector1<float> Wm4::Intersector1f
Definition at line 70 of file Wm4Intersector1.h.
Intersector2d
typedef Intersector<double, Vector2<double> > Wm4::Intersector2d
Definition at line 79 of file Wm4Intersector.h.
Intersector2f
typedef Intersector<float, Vector2<float> > Wm4::Intersector2f
Definition at line 77 of file Wm4Intersector.h.
Intersector3d
typedef Intersector<double, Vector3<double> > Wm4::Intersector3d
Definition at line 80 of file Wm4Intersector.h.
Intersector3f
typedef Intersector<float, Vector3<float> > Wm4::Intersector3f
Definition at line 78 of file Wm4Intersector.h.
IntrLine3Box3d
typedef IntrLine3Box3<double> Wm4::IntrLine3Box3d
Definition at line 72 of file Wm4IntrLine3Box3.h.
IntrLine3Box3f
typedef IntrLine3Box3<float> Wm4::IntrLine3Box3f
Definition at line 71 of file Wm4IntrLine3Box3.h.
IntrLine3Plane3d
typedef IntrLine3Plane3<double> Wm4::IntrLine3Plane3d
Definition at line 62 of file Wm4IntrLine3Plane3.h.
IntrLine3Plane3f
typedef IntrLine3Plane3<float> Wm4::IntrLine3Plane3f
Definition at line 61 of file Wm4IntrLine3Plane3.h.
IntrSegment3Box3d
typedef IntrSegment3Box3<double> Wm4::IntrSegment3Box3d
Definition at line 62 of file Wm4IntrSegment3Box3.h.
IntrSegment3Box3f
typedef IntrSegment3Box3<float> Wm4::IntrSegment3Box3f
Definition at line 61 of file Wm4IntrSegment3Box3.h.
IntrSegment3Plane3d
typedef IntrSegment3Plane3<double> Wm4::IntrSegment3Plane3d
Definition at line 64 of file Wm4IntrSegment3Plane3.h.
IntrSegment3Plane3f
typedef IntrSegment3Plane3<float> Wm4::IntrSegment3Plane3f
Definition at line 63 of file Wm4IntrSegment3Plane3.h.
IntrTriangle2Triangle2d
typedef IntrTriangle2Triangle2<double> Wm4::IntrTriangle2Triangle2d
Definition at line 104 of file Wm4IntrTriangle2Triangle2.h.
IntrTriangle2Triangle2f
typedef IntrTriangle2Triangle2<float> Wm4::IntrTriangle2Triangle2f
Definition at line 103 of file Wm4IntrTriangle2Triangle2.h.
IntrTriangle3Triangle3d
typedef IntrTriangle3Triangle3<double> Wm4::IntrTriangle3Triangle3d
Definition at line 140 of file Wm4IntrTriangle3Triangle3.h.
IntrTriangle3Triangle3f
typedef IntrTriangle3Triangle3<float> Wm4::IntrTriangle3Triangle3f
Definition at line 139 of file Wm4IntrTriangle3Triangle3.h.
LinCompd
typedef LinComp<double> Wm4::LinCompd
Definition at line 121 of file Wm4LinComp.h.
LinCompf
typedef LinComp<float> Wm4::LinCompf
Definition at line 120 of file Wm4LinComp.h.
Line3d
typedef Line3<double> Wm4::Line3d
Definition at line 48 of file Wm4Line3.h.
Line3f
typedef Line3<float> Wm4::Line3f
Definition at line 47 of file Wm4Line3.h.
LinearSystemd
typedef LinearSystem<double> Wm4::LinearSystemd
Definition at line 143 of file Wm4LinearSystem.h.
LinearSystemf
typedef LinearSystem<float> Wm4::LinearSystemf
Definition at line 142 of file Wm4LinearSystem.h.
Mapper2d
typedef Mapper2<double> Wm4::Mapper2d
Definition at line 99 of file Wm4Mapper2.h.
Mapper2f
typedef Mapper2<float> Wm4::Mapper2f
Definition at line 98 of file Wm4Mapper2.h.
Mapper3d
typedef Mapper3<double> Wm4::Mapper3d
Definition at line 105 of file Wm4Mapper3.h.
Mapper3f
typedef Mapper3<float> Wm4::Mapper3f
Definition at line 104 of file Wm4Mapper3.h.
Mathd
typedef Math<double> Wm4::Mathd
Definition at line 153 of file Wm4Math.h.
Mathf
typedef Math<float> Wm4::Mathf
Definition at line 152 of file Wm4Math.h.
Matrix2d
typedef Matrix2<double> Wm4::Matrix2d
Definition at line 185 of file Wm4Matrix2.h.
Matrix2f
typedef Matrix2<float> Wm4::Matrix2f
Definition at line 184 of file Wm4Matrix2.h.
Matrix3d
typedef Matrix3<double> Wm4::Matrix3d
Definition at line 257 of file Wm4Matrix3.h.
Matrix3f
typedef Matrix3<float> Wm4::Matrix3f
Definition at line 256 of file Wm4Matrix3.h.
Matrix4d
typedef Matrix4<double> Wm4::Matrix4d
Definition at line 161 of file Wm4Matrix4.h.
Matrix4f
typedef Matrix4<float> Wm4::Matrix4f
Definition at line 160 of file Wm4Matrix4.h.
MeshCurvatured
typedef MeshCurvature<double> Wm4::MeshCurvatured
Definition at line 64 of file Wm4MeshCurvature.h.
MeshCurvaturef
typedef MeshCurvature<float> Wm4::MeshCurvaturef
Definition at line 63 of file Wm4MeshCurvature.h.
MeshSmootherd
typedef MeshSmoother<double> Wm4::MeshSmootherd
Definition at line 73 of file Wm4MeshSmoother.h.
MeshSmootherf
typedef MeshSmoother<float> Wm4::MeshSmootherf
Definition at line 72 of file Wm4MeshSmoother.h.
ParametricSurfaced
typedef ParametricSurface<double> Wm4::ParametricSurfaced
Definition at line 75 of file Wm4ParametricSurface.h.
ParametricSurfacef
typedef ParametricSurface<float> Wm4::ParametricSurfacef
Definition at line 74 of file Wm4ParametricSurface.h.
Plane3d
typedef Plane3<double> Wm4::Plane3d
Definition at line 76 of file Wm4Plane3.h.
Plane3f
typedef Plane3<float> Wm4::Plane3f
Definition at line 75 of file Wm4Plane3.h.
Polynomial1d
typedef Polynomial1<double> Wm4::Polynomial1d
Definition at line 104 of file Wm4Polynomial1.h.
Polynomial1f
typedef Polynomial1<float> Wm4::Polynomial1f
Definition at line 103 of file Wm4Polynomial1.h.
PolynomialRootsd
typedef PolynomialRoots<double> Wm4::PolynomialRootsd
Definition at line 160 of file Wm4PolynomialRoots.h.
PolynomialRootsf
typedef PolynomialRoots<float> Wm4::PolynomialRootsf
Definition at line 159 of file Wm4PolynomialRoots.h.
QuadricSurfaced
typedef QuadricSurface<double> Wm4::QuadricSurfaced
Definition at line 155 of file Wm4QuadricSurface.h.
QuadricSurfacef
typedef QuadricSurface<float> Wm4::QuadricSurfacef
Definition at line 154 of file Wm4QuadricSurface.h.
Quaterniond
typedef Quaternion<double> Wm4::Quaterniond
Definition at line 322 of file Wm4Quaternion.h.
Quaternionf
typedef Quaternion<float> Wm4::Quaternionf
Definition at line 321 of file Wm4Quaternion.h.
Query2d
typedef Query2<double> Wm4::Query2d
Definition at line 87 of file Wm4Query2.h.
Query2f
typedef Query2<float> Wm4::Query2f
Definition at line 86 of file Wm4Query2.h.
Query2Filteredd
typedef Query2Filtered<double> Wm4::Query2Filteredd
Definition at line 68 of file Wm4Query2Filtered.h.
Query2Filteredf
typedef Query2Filtered<float> Wm4::Query2Filteredf
Definition at line 67 of file Wm4Query2Filtered.h.
Query2Int64d
typedef Query2Int64<double> Wm4::Query2Int64d
Definition at line 66 of file Wm4Query2Int64.h.
Query2Int64f
typedef Query2Int64<float> Wm4::Query2Int64f
Definition at line 65 of file Wm4Query2Int64.h.
Query2TIntegerd
typedef Query2TInteger<double> Wm4::Query2TIntegerd
Definition at line 70 of file Wm4Query2TInteger.h.
Query2TIntegerf
typedef Query2TInteger<float> Wm4::Query2TIntegerf
Definition at line 69 of file Wm4Query2TInteger.h.
Query2TRationald
typedef Query2TRational<double> Wm4::Query2TRationald
Definition at line 88 of file Wm4Query2TRational.h.
Query2TRationalf
typedef Query2TRational<float> Wm4::Query2TRationalf
Definition at line 87 of file Wm4Query2TRational.h.
Query3d
typedef Query3<double> Wm4::Query3d
Definition at line 93 of file Wm4Query3.h.
Query3f
typedef Query3<float> Wm4::Query3f
Definition at line 92 of file Wm4Query3.h.
Query3Filteredd
typedef Query3Filtered<double> Wm4::Query3Filteredd
Definition at line 69 of file Wm4Query3Filtered.h.
Query3Filteredf
typedef Query3Filtered<float> Wm4::Query3Filteredf
Definition at line 68 of file Wm4Query3Filtered.h.
Query3Int64d
typedef Query3Int64<double> Wm4::Query3Int64d
Definition at line 70 of file Wm4Query3Int64.h.
Query3Int64f
typedef Query3Int64<float> Wm4::Query3Int64f
Definition at line 69 of file Wm4Query3Int64.h.
Query3TIntegerd
typedef Query3TInteger<double> Wm4::Query3TIntegerd
Definition at line 76 of file Wm4Query3TInteger.h.
Query3TIntegerf
typedef Query3TInteger<float> Wm4::Query3TIntegerf
Definition at line 75 of file Wm4Query3TInteger.h.
Query3TRationald
typedef Query3TRational<double> Wm4::Query3TRationald
Definition at line 96 of file Wm4Query3TRational.h.
Query3TRationalf
typedef Query3TRational<float> Wm4::Query3TRationalf
Definition at line 95 of file Wm4Query3TRational.h.
Segment3d
typedef Segment3<double> Wm4::Segment3d
Definition at line 58 of file Wm4Segment3.h.
Segment3f
typedef Segment3<float> Wm4::Segment3f
Definition at line 57 of file Wm4Segment3.h.
Sphere3d
typedef Sphere3<double> Wm4::Sphere3d
Definition at line 51 of file Wm4Sphere3.h.
Sphere3f
typedef Sphere3<float> Wm4::Sphere3f
Definition at line 50 of file Wm4Sphere3.h.
Surfaced
typedef Surface<double> Wm4::Surfaced
Definition at line 38 of file Wm4Surface.h.
Surfacef
typedef Surface<float> Wm4::Surfacef
Definition at line 37 of file Wm4Surface.h.
Triangle2d
typedef Triangle2<double> Wm4::Triangle2d
Definition at line 52 of file Wm4Triangle2.h.
Triangle2f
typedef Triangle2<float> Wm4::Triangle2f
Definition at line 51 of file Wm4Triangle2.h.
Triangle3d
typedef Triangle3<double> Wm4::Triangle3d
Definition at line 52 of file Wm4Triangle3.h.
Triangle3f
typedef Triangle3<float> Wm4::Triangle3f
Definition at line 51 of file Wm4Triangle3.h.
Vector2d
typedef Vector2<double> Wm4::Vector2d
Definition at line 131 of file Wm4Vector2.h.
Vector2f
typedef Vector2<float> Wm4::Vector2f
Definition at line 130 of file Wm4Vector2.h.
Vector3d
typedef Vector3<double> Wm4::Vector3d
Definition at line 144 of file Wm4Vector3.h.
Vector3f
typedef Vector3<float> Wm4::Vector3f
Definition at line 143 of file Wm4Vector3.h.
Vector4d
typedef Vector4<double> Wm4::Vector4d
Definition at line 110 of file Wm4Vector4.h.
Vector4f
typedef Vector4<float> Wm4::Vector4f
Definition at line 109 of file Wm4Vector4.h.
Function Documentation
Allocate() [1/2]
template<class T > void Wm4::Allocate (int iCols, int iRows, int iSlices, T ***& raaatArray)
Allocate() [2/2]
template<class T > void Wm4::Allocate (int iCols, int iRows, T **& raatArray)
ContAlignedBox() [1/2]
template<class Real > Box2< Real > Wm4::ContAlignedBox (int iQuantity, const Vector2< Real > * akPoint)
Definition at line 18 of file Wm4ContBox2.cpp.
References Wm4::Box2< Real >::Axis, Wm4::Box2< Real >::Center, Wm4::Vector2< Real >::ComputeExtremes(), Wm4::Box2< Real >::Extent, and SplineSurface::i.
ContAlignedBox() [2/2]
template<class Real > Box3< Real > Wm4::ContAlignedBox (int iQuantity, const Vector3< Real > * akPoint)
Definition at line 21 of file Wm4ContBox3.cpp.
References Wm4::Box3< Real >::Axis, Wm4::Box3< Real >::Center, Wm4::Vector3< Real >::ComputeExtremes(), Wm4::Box3< Real >::Extent, and SplineSurface::i.
ContAlignedBox< double >() [1/2]
template Box2<double> Wm4::ContAlignedBox< double > (int , const Vector2< double > *)
ContAlignedBox< double >() [2/2]
template Box3<double> Wm4::ContAlignedBox< double > (int , const Vector3< double > *)
ContAlignedBox< float >() [1/2]
template Box2<float> Wm4::ContAlignedBox< float > (int , const Vector2< float > *)
ContAlignedBox< float >() [2/2]
template Box3<float> Wm4::ContAlignedBox< float > (int , const Vector3< float > *)
ContMinBox() [1/2]
template<class Real > Box2< Real > Wm4::ContMinBox (int iQuantity, const Vector2< Real > * akPoint, Real fEpsilon, Query::Type eQueryType, bool bIsConvexPolygon)
Definition at line 102 of file Wm4ContBox2.cpp.
References Wm4::Box2< Real >::Axis, Wm4::Box2< Real >::Center, Wm4::Vector2< Real >::Dot(), Wm4::Box2< Real >::Extent, Wm4::ConvexHull2< Real >::GetConvexHull1(), Wm4::ConvexHull< Real >::GetDimension(), Wm4::ConvexHull< Real >::GetIndices(), Wm4::ConvexHull< Real >::GetSimplexQuantity(), SplineSurface::i, Wm4::Vector2< Real >::Normalize(), Wm4::Vector2< Real >::Perp(), UpdateBox(), WM4_DELETE, WM4_NEW, DrawingExample::X, and DrawingExample::Y.
ContMinBox() [2/2]
template<class Real > Box3< Real > Wm4::ContMinBox (int iQuantity, const Vector3< Real > * akPoint, Real fEpsilon, Query::Type eQueryType)
Definition at line 86 of file Wm4ContBox3.cpp.
References Wm4::Box2< Real >::Axis, Wm4::Box3< Real >::Axis, Wm4::Box2< Real >::Center, Wm4::Box3< Real >::Center, Wm4::Vector3< Real >::Dot(), Wm4::Box2< Real >::Extent, Wm4::Box3< Real >::Extent, Wm4::Vector3< Real >::GenerateComplementBasis(), Wm4::ConvexHull3< Real >::GetConvexHull1(), Wm4::ConvexHull< Real >::GetDimension(), Wm4::ConvexHull< Real >::GetIndices(), Wm4::ConvexHull3< Real >::GetPlaneDirection(), Wm4::ConvexHull3< Real >::GetPlaneOrigin(), Wm4::ConvexHull< Real >::GetSimplexQuantity(), SplineSurface::i, Wm4::Vector3< Real >::Normalize(), Wm4::Vector3< Real >::UnitCross(), WM4_DELETE, WM4_NEW, Wm4::Vector2< Real >::X(), and Wm4::Vector2< Real >::Y().
ContMinBox< double >() [1/2]
template Box2<double> Wm4::ContMinBox< double > (int , const Vector2< double > * , double , Query::Type , bool)
ContMinBox< double >() [2/2]
template Box3<double> Wm4::ContMinBox< double > (int , const Vector3< double > * , double , Query::Type)
ContMinBox< float >() [1/2]
template Box2<float> Wm4::ContMinBox< float > (int , const Vector2< float > * , float , Query::Type , bool)
ContMinBox< float >() [2/2]
template Box3<float> Wm4::ContMinBox< float > (int , const Vector3< float > * , float , Query::Type)
ContOrientedBox() [1/2]
template<class Real > Box2< Real > Wm4::ContOrientedBox (int iQuantity, const Vector2< Real > * akPoint)
Definition at line 37 of file Wm4ContBox2.cpp.
References Wm4::Box2< Real >::Axis, Wm4::Box2< Real >::Center, Wm4::Vector2< Real >::Dot(), Wm4::Box2< Real >::Extent, and SplineSurface::i.
ContOrientedBox() [2/2]
template<class Real > Box3< Real > Wm4::ContOrientedBox (int iQuantity, const Vector3< Real > * akPoint)
Definition at line 41 of file Wm4ContBox3.cpp.
References Wm4::Box3< Real >::Axis, Wm4::Box3< Real >::Center, Wm4::Vector3< Real >::Dot(), Wm4::Box3< Real >::Extent, and SplineSurface::i.
ContOrientedBox< double >() [1/2]
template Box2<double> Wm4::ContOrientedBox< double > (int , const Vector2< double > *)
ContOrientedBox< double >() [2/2]
template Box3<double> Wm4::ContOrientedBox< double > (int , const Vector3< double > *)
ContOrientedBox< float >() [1/2]
template Box2<float> Wm4::ContOrientedBox< float > (int , const Vector2< float > *)
ContOrientedBox< float >() [2/2]
template Box3<float> Wm4::ContOrientedBox< float > (int , const Vector3< float > *)
Deallocate() [1/2]
template<class T > static void Wm4::Deallocate (T **& raatArray) static
Deallocate() [2/2]
template<class T > void Wm4::Deallocate (T ***& raaatArray)
GaussPointsFit2()
template<class Real > Box2< Real > Wm4::GaussPointsFit2 (int iQuantity, const Vector2< Real > * akPoint)
Definition at line 17 of file Wm4ApprGaussPointsFit2.cpp.
References Wm4::Box2< Real >::Axis, Wm4::Box2< Real >::Center, Wm4::Box2< Real >::Extent, Wm4::Eigen< Real >::GetEigenvalue(), Wm4::Eigen< Real >::GetEigenvector(), SplineSurface::i, Wm4::Eigen< Real >::IncrSortEigenStuff2(), Wm4::Vector2< Real >::X(), and Wm4::Vector2< Real >::Y().
GaussPointsFit2< double >()
template Box2<double> Wm4::GaussPointsFit2< double > (int , const Vector2< double > *)
GaussPointsFit2< float >()
template Box2<float> Wm4::GaussPointsFit2< float > (int , const Vector2< float > *)
GaussPointsFit3()
template<class Real > Box3< Real > Wm4::GaussPointsFit3 (int iQuantity, const Vector3< Real > * akPoint)
Definition at line 17 of file Wm4ApprGaussPointsFit3.cpp.
References Wm4::Box3< Real >::Axis, Wm4::Box3< Real >::Center, Wm4::Box3< Real >::Extent, Wm4::Eigen< Real >::GetEigenvalue(), Wm4::Eigen< Real >::GetEigenvector(), SplineSurface::i, Wm4::Eigen< Real >::IncrSortEigenStuff3(), Wm4::Vector3< Real >::X(), Wm4::Vector3< Real >::Y(), and Wm4::Vector3< Real >::Z().
GaussPointsFit3< double >()
template Box3<double> Wm4::GaussPointsFit3< double > (int , const Vector3< double > *)
GaussPointsFit3< float >()
template Box3<float> Wm4::GaussPointsFit3< float > (int , const Vector3< float > *)
HeightPlaneFit3()
template<class Real > bool Wm4::HeightPlaneFit3 (int iQuantity, const Vector3< Real > * akPoint, Real & rfA, Real & rfB, Real & rfC)
Definition at line 26 of file Wm4ApprPlaneFit3.cpp.
References SplineSurface::i, Wm4::LinearSystem< Real >::Solve3(), Wm4::Vector3< Real >::X(), Wm4::Vector3< Real >::Y(), and Wm4::Vector3< Real >::Z().
HeightPlaneFit3< double >()
template bool Wm4::HeightPlaneFit3< double > (int , const Vector3< double > * , double & , double & , double &)
HeightPlaneFit3< float >()
template bool Wm4::HeightPlaneFit3< float > (int , const Vector3< float > * , float & , float & , float &)
InBox() [1/2]
template<class Real > bool Wm4::InBox (const Vector2< Real > & rkPoint, const Box2< Real > & rkBox)
Definition at line 404 of file Wm4ContBox2.cpp.
References Wm4::Box2< Real >::Axis, Wm4::Box2< Real >::Center, Wm4::Vector2< Real >::Dot(), Wm4::Box2< Real >::Extent, and SplineSurface::i.
InBox() [2/2]
template<class Real > bool Wm4::InBox (const Vector3< Real > & rkPoint, const Box3< Real > & rkBox)
Definition at line 387 of file Wm4ContBox3.cpp.
References Wm4::Box3< Real >::Axis, Wm4::Box3< Real >::Center, Wm4::Vector3< Real >::Dot(), Wm4::Box3< Real >::Extent, and SplineSurface::i.
InBox< double >() [1/2]
template bool Wm4::InBox< double > (const Vector2< double > & , const Box2< double > &)
InBox< double >() [2/2]
template bool Wm4::InBox< double > (const Vector3< double > & , const Box3< double > &)
InBox< float >() [1/2]
template bool Wm4::InBox< float > (const Vector2< float > & , const Box2< float > &)
InBox< float >() [2/2]
template bool Wm4::InBox< float > (const Vector3< float > & , const Box3< float > &)
MergeBoxes() [1/2]
template<class Real > Box2< Real > Wm4::MergeBoxes (const Box2< Real > & rkBox0, const Box2< Real > & rkBox1)
Definition at line 419 of file Wm4ContBox2.cpp.
References Wm4::Box2< Real >::Axis, Wm4::Box2< Real >::Center, Wm4::Box2< Real >::ComputeVertices(), Wm4::Vector2< Real >::Dot(), Wm4::Box2< Real >::Extent, and SplineSurface::i.
MergeBoxes() [2/2]
template<class Real > Box3< Real > Wm4::MergeBoxes (const Box3< Real > & rkBox0, const Box3< Real > & rkBox1)
Definition at line 402 of file Wm4ContBox3.cpp.
References Wm4::Box3< Real >::Axis, Wm4::Box3< Real >::Center, Wm4::Box3< Real >::ComputeVertices(), Wm4::Vector3< Real >::Dot(), Wm4::Quaternion< Real >::Dot(), Wm4::Box3< Real >::Extent, Wm4::Quaternion< Real >::FromRotationMatrix(), SplineSurface::i, Wm4::Math< Real >::InvSqrt(), and Wm4::Quaternion< Real >::ToRotationMatrix().
MergeBoxes< double >() [1/2]
template Box2<double> Wm4::MergeBoxes< double > (const Box2< double > & , const Box2< double > &)
MergeBoxes< double >() [2/2]
template Box3<double> Wm4::MergeBoxes< double > (const Box3< double > & , const Box3< double > &)
MergeBoxes< float >() [1/2]
template Box2<float> Wm4::MergeBoxes< float > (const Box2< float > & , const Box2< float > &)
MergeBoxes< float >() [2/2]
template Box3<float> Wm4::MergeBoxes< float > (const Box3< float > & , const Box3< float > &)
operator*() [1/17]
template<class Real > GVector<Real> Wm4::operator* (const GVector< Real > & rkV, const GMatrix< Real > & rkM)
operator*() [2/17]
template<int N> TRational<N> Wm4::operator* (const TInteger< N > & rkI, const TRational< N > & rkR)
operator*() [3/17]
template<int VSIZE, int ISIZE> TRVector<VSIZE,ISIZE> Wm4::operator* (const TRational< ISIZE > & rkR, const TRVector< VSIZE, ISIZE > & rkV)
operator*() [4/17]
template<class Real > Vector2<Real> Wm4::operator* (const Vector2< Real > & rkV, const Matrix2< Real > & rkM)
operator*() [5/17]
template<class Real > Vector3<Real> Wm4::operator* (const Vector3< Real > & rkV, const Matrix3< Real > & rkM)
operator*() [6/17]
template<class Real > Vector4<Real> Wm4::operator* (const Vector4< Real > & rkV, const Matrix4< Real > & rkM)
operator*() [7/17]
template<int N> TInteger<N> Wm4::operator* (int i, const TInteger< N > & rkI)
operator*() [8/17]
template<class Real > GMatrix<Real> Wm4::operator* (Real fScalar, const GMatrix< Real > & rkM)
operator*() [9/17]
template<class Real > GVector<Real> Wm4::operator* (Real fScalar, const GVector< Real > & rkV)
operator*() [10/17]
template<class Real > Matrix2<Real> Wm4::operator* (Real fScalar, const Matrix2< Real > & rkM)
operator*() [11/17]
template<class Real > Matrix3<Real> Wm4::operator* (Real fScalar, const Matrix3< Real > & rkM)
operator*() [12/17]
template<class Real > Matrix4<Real> Wm4::operator* (Real fScalar, const Matrix4< Real > & rkM)
operator*() [13/17]
template<class Real > Polynomial1<Real> Wm4::operator* (Real fScalar, const Polynomial1< Real > & rkPoly)
operator*() [14/17]
template<class Real > Quaternion<Real> Wm4::operator* (Real fScalar, const Quaternion< Real > & rkQ) inline
operator*() [15/17]
template<class Real > Vector2<Real> Wm4::operator* (Real fScalar, const Vector2< Real > & rkV)
operator*() [16/17]
template<class Real > Vector3<Real> Wm4::operator* (Real fScalar, const Vector3< Real > & rkV)
operator*() [17/17]
template<class Real > Vector4<Real> Wm4::operator* (Real fScalar, const Vector4< Real > & rkV)
operator+()
template<int N> TRational<N> Wm4::operator+ (const TInteger< N > & rkI, const TRational< N > & rkR)
operator-()
template<int N> TRational<N> Wm4::operator- (const TInteger< N > & rkI, const TRational< N > & rkR)
operator/()
template<int N> TRational<N> Wm4::operator/ (const TInteger< N > & rkI, const TRational< N > & rkR)
operator<<() [1/3]
template<class Real > std::ostream& Wm4::operator<< (std::ostream & rkOStr, const Vector2< Real > & rkV)
operator<<() [2/3]
template<class Real > std::ostream& Wm4::operator<< (std::ostream & rkOStr, const Vector3< Real > & rkV)
operator<<() [3/3]
template<class Real > std::ostream& Wm4::operator<< (std::ostream & rkOStr, const Vector4< Real > & rkV)
OrthogonalLineFit3()
template<class Real > Line3< Real > Wm4::OrthogonalLineFit3 (int iQuantity, const Vector3< Real > * akPoint)
Definition at line 25 of file Wm4ApprLineFit3.cpp.
References Wm4::Eigen< Real >::DecrSortEigenStuff3(), Wm4::Line3< Real >::Direction, Wm4::Eigen< Real >::GetEigenvector(), SplineSurface::i, Wm4::Line3< Real >::Origin, Wm4::Vector3< Real >::X(), Wm4::Vector3< Real >::Y(), and Wm4::Vector3< Real >::Z().
Referenced by MeshCoreFit::CylinderFit::ComputeApproximationsLine(), and Wm4::CylinderFit3< Real >::CylinderFit3().
OrthogonalLineFit3< double >()
template Line3<double> Wm4::OrthogonalLineFit3< double > (int , const Vector3< double > *)
OrthogonalLineFit3< float >()
template Line3<float> Wm4::OrthogonalLineFit3< float > (int , const Vector3< float > *)
OrthogonalPlaneFit3()
template<class Real > Plane3< Real > Wm4::OrthogonalPlaneFit3 (int iQuantity, const Vector3< Real > * akPoint)
Definition at line 85 of file Wm4ApprPlaneFit3.cpp.
References Wm4::Eigen< Real >::DecrSortEigenStuff3(), Wm4::Eigen< Real >::GetEigenvector(), SplineSurface::i, Wm4::Vector3< Real >::X(), Wm4::Vector3< Real >::Y(), and Wm4::Vector3< Real >::Z().
OrthogonalPlaneFit3< double >()
template Plane3<double> Wm4::OrthogonalPlaneFit3< double > (int , const Vector3< double > *)
OrthogonalPlaneFit3< float >()
template Plane3<float> Wm4::OrthogonalPlaneFit3< float > (int , const Vector3< float > *)
PolyFit3()
template<class Real > Real * Wm4::PolyFit3 (int iSamples, const Real * afX, const Real * afY, const Real * afW, int iXDegree, int iYDegree)
Definition at line 25 of file Wm4ApprPolyFit3.cpp.
References Wm4::LinearSystem< Real >::Solve(), WM4_DELETE, and WM4_NEW.
PolyFit3< double >()
template double* Wm4::PolyFit3< double > (int , const double * , const double * , const double * , int , int)
PolyFit3< float >()
template float* Wm4::PolyFit3< float > (int , const float * , const float * , const float * , int , int)
Referenced by MeshCore::PolynomialFit::Fit().
QuadraticFit3()
template<class Real > Real Wm4::QuadraticFit3 (int iQuantity, const Vector3< Real > * akPoint, Real afCoeff[10])
Definition at line 25 of file Wm4ApprQuadraticFit3.cpp.
References Wm4::Math< Real >::FAbs(), Wm4::Eigen< Real >::GetEigenvalue(), Wm4::Eigen< Real >::GetEigenvector(), SplineSurface::i, Wm4::Eigen< Real >::IncrSortEigenStuffN(), Wm4::System::Memcpy(), Wm4::Vector3< Real >::X(), Wm4::Vector3< Real >::Y(), and Wm4::Vector3< Real >::Z().
QuadraticFit3< double >()
template double Wm4::QuadraticFit3< double > (int , const Vector3< double > * , double [10])
Referenced by MeshCore::QuadraticFit::Fit().
QuadraticFit3< float >()
template float Wm4::QuadraticFit3< float > (int , const Vector3< float > * , float [10])
QuadraticSphereFit3()
template<class Real > Real Wm4::QuadraticSphereFit3 (int iQuantity, const Vector3< Real > * akPoint, Vector3< Real > & rkCenter, Real & rfRadius)
Definition at line 164 of file Wm4ApprQuadraticFit3.cpp.
References Wm4::Math< Real >::FAbs(), Wm4::Eigen< Real >::GetEigenvalue(), Wm4::Eigen< Real >::GetEigenvector(), SplineSurface::i, Wm4::Eigen< Real >::IncrSortEigenStuffN(), Wm4::Math< Real >::Sqrt(), Wm4::Vector3< Real >::X(), Wm4::Vector3< Real >::Y(), and Wm4::Vector3< Real >::Z().
QuadraticSphereFit3< double >()
template double Wm4::QuadraticSphereFit3< double > (int , const Vector3< double > * , Vector3< double > & , double &)
QuadraticSphereFit3< float >()
template float Wm4::QuadraticSphereFit3< float > (int , const Vector3< float > * , Vector3< float > & , float &)
SphereFit3()
template<class Real > bool Wm4::SphereFit3 (int iQuantity, const Vector3< Real > * akPoint, int iMaxIterations, Sphere3< Real > & rkSphere, bool bInitialCenterIsAverage)
Definition at line 25 of file Wm4ApprSphereFit3.cpp.
References Wm4::Sphere3< Real >::Center, Wm4::Vector3< Real >::Length(), Wm4::Sphere3< Real >::Radius, Wm4::Vector3< Real >::X(), Wm4::Vector3< Real >::Y(), and Wm4::Vector3< Real >::Z().
SphereFit3< double >()
template bool Wm4::SphereFit3< double > (int , const Vector3< double > * , int , Sphere3< double > & , bool)
Referenced by MeshCore::SphereFit::Fit().
SphereFit3< float >()
template bool Wm4::SphereFit3< float > (int , const Vector3< float > * , int , Sphere3< float > & , bool)
UpdateBox()
template<class Real > static void Wm4::UpdateBox (const Vector2< Real > & rkLPoint, const Vector2< Real > & rkRPoint, const Vector2< Real > & rkBPoint, const Vector2< Real > & rkTPoint, const Vector2< Real > & rkU, const Vector2< Real > & rkV, Real & rfMinAreaDiv4, Box2< Real > & rkBox) static
Definition at line 78 of file Wm4ContBox2.cpp.
References Wm4::Box2< Real >::Axis, Wm4::Box2< Real >::Center, Wm4::Vector2< Real >::Dot(), and Wm4::Box2< Real >::Extent.
Referenced by ContMinBox().