FreeCAD: nativeifc.ifc_generator Namespace Reference
nativeifc.ifc_generator Namespace Reference
Functions
def generate_geometry (obj, cached=False)
def generate_shape (ifcfile, elements, cached=False)
def generate_coin (ifcfile, elements, cached=False)
def get_decomposition (obj)
def filter_types (elements, obj_ids=[])
def get_decomposed_elements (element, obj=None)
def get_geom_iterator (ifcfile, elements, brep_mode)
def get_cache (ifcfile)
def set_cache (ifcfile, cache)
def set_representation (vobj, node)
def print_debug (obj)
def apply_placement (node, placement)
def unify (nodes)
def create_ghost (document, ifcfile, project)
def delete_ghost (document)
def get_annotation_shape (annotation, ifcfile, coin=False)
Function Documentation
apply_placement()
def nativeifc.ifc_generator.apply_placement (node, placement)
Applies the given placement to the verts in the given node
Definition at line 532 of file ifc_generator.py.
Referenced by nativeifc.ifc_generator.generate_coin().
create_ghost()
def nativeifc.ifc_generator.create_ghost (document, ifcfile, project)
Creates a coin representation of the given ifcfile in the given document
Definition at line 557 of file ifc_generator.py.
References nativeifc.ifc_generator.delete_ghost(), nativeifc.ifc_generator.filter_types(), nativeifc.ifc_generator.generate_coin(), and nativeifc.ifc_generator.get_decomposed_elements().
delete_ghost()
def nativeifc.ifc_generator.delete_ghost (document)
Deletes the associated ghost of the document
Definition at line 573 of file ifc_generator.py.
Referenced by nativeifc.ifc_generator.create_ghost().
filter_types()
def nativeifc.ifc_generator.filter_types (elements, obj_ids = [])
Remove unrenderable (for now) elements from the given list
Definition at line 360 of file ifc_generator.py.
Referenced by nativeifc.ifc_generator.create_ghost(), and nativeifc.ifc_generator.get_decomposition().
generate_coin()
def nativeifc.ifc_generator.generate_coin (ifcfile, elements, cached = False)
Returns coin node data (verts,face and edge index) and a Placement
from a list of ifc elements
Definition at line 231 of file ifc_generator.py.
References nativeifc.ifc_generator.apply_placement(), nativeifc.ifc_generator.get_cache(), nativeifc.ifc_generator.get_geom_iterator(), nativeifc.ifc_generator.set_cache(), Path.Post.scripts.refactored_centroid_post.str, and nativeifc.ifc_generator.unify().
Referenced by nativeifc.ifc_generator.create_ghost(), and nativeifc.ifc_generator.generate_geometry().
generate_geometry()
def nativeifc.ifc_generator.generate_geometry (obj, cached = False)
Sets the geometry of the given object from a corresponding IFC element.
This is the main function called by the execute method of FreeCAD document objects
It is only meant to be called form there, as it is always the responsibility of the
NativeIFC document object to know when it needs to regenerate its geometry.
The generate_geometry will call either generate_shape or generate_coin, depending
on the type of representation it wants.
obj: FreeCAD document object
[cached]: If we should try to use the cached version. The document object knows when
to use this.
Definition at line 43 of file ifc_generator.py.
References nativeifc.ifc_generator.generate_coin(), nativeifc.ifc_generator.generate_shape(), nativeifc.ifc_generator.get_annotation_shape(), nativeifc.ifc_generator.get_decomposition(), nativeifc.ifc_generator.print_debug(), and nativeifc.ifc_generator.set_representation().
generate_shape()
def nativeifc.ifc_generator.generate_shape (ifcfile, elements, cached = False)
Returns a Part shape and a list of colors for a list of elements
Definition at line 120 of file ifc_generator.py.
References nativeifc.ifc_generator.get_cache(), nativeifc.ifc_generator.get_geom_iterator(), nativeifc.ifc_generator.set_cache(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by nativeifc.ifc_generator.generate_geometry().
get_annotation_shape()
def nativeifc.ifc_generator.get_annotation_shape (annotation, ifcfile, coin = False)
Returns a shape or a coin node form an IFC annotation.
Returns [colors, verts, faces, edges], colors and faces
being normally None for 2D shapes.
Definition at line 583 of file ifc_generator.py.
References nativeifc.ifc_generator.unify().
Referenced by nativeifc.ifc_generator.generate_geometry().
get_cache()
def nativeifc.ifc_generator.get_cache (ifcfile)
Returns the shape cache dictionary associated with this ifc file
Definition at line 432 of file ifc_generator.py.
Referenced by nativeifc.ifc_generator.generate_coin(), and nativeifc.ifc_generator.generate_shape().
get_decomposed_elements()
def nativeifc.ifc_generator.get_decomposed_elements (element, obj = None)
Returns a list of renderable elements form a base element
Definition at line 372 of file ifc_generator.py.
Referenced by nativeifc.ifc_generator.create_ghost(), and nativeifc.ifc_generator.get_decomposition().
get_decomposition()
def nativeifc.ifc_generator.get_decomposition (obj)
Gets the elements we need to render this object
Definition at line 348 of file ifc_generator.py.
References nativeifc.ifc_generator.filter_types(), and nativeifc.ifc_generator.get_decomposed_elements().
Referenced by nativeifc.ifc_generator.generate_geometry().
get_geom_iterator()
def nativeifc.ifc_generator.get_geom_iterator (ifcfile, elements, brep_mode)
Prepares and returns an ifcopenshell iterator instance
from the given ifcfile and elements list. brep_mode indicates
if we want brep data or not
Definition at line 400 of file ifc_generator.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by nativeifc.ifc_generator.generate_coin(), and nativeifc.ifc_generator.generate_shape().
print_debug()
def nativeifc.ifc_generator.print_debug (obj)
Prints some debug info when an element could not be rendered
Definition at line 515 of file ifc_generator.py.
Referenced by nativeifc.ifc_generator.generate_geometry().
set_cache()
def nativeifc.ifc_generator.set_cache (ifcfile, cache)
Sets the given dictionary as shape cache for the given ifc file
Definition at line 449 of file ifc_generator.py.
Referenced by nativeifc.ifc_generator.generate_coin(), and nativeifc.ifc_generator.generate_shape().
set_representation()
def nativeifc.ifc_generator.set_representation (vobj, node)
Sets the correct coin nodes for the given Part object
Definition at line 464 of file ifc_generator.py.
Referenced by nativeifc.ifc_generator.generate_geometry().
unify()
def nativeifc.ifc_generator.unify (nodes)
group the subcomponents of a node into one single set of verts, faces, edges
Definition at line 539 of file ifc_generator.py.
Referenced by nativeifc.ifc_generator.generate_coin(), and nativeifc.ifc_generator.get_annotation_shape().