FreeCAD: PartGui::Location Class Reference
PartGui::Location Class Reference
#include <DlgPrimitives.h>
Public Member Functions
Location (QWidget *parent=nullptr, Part::Feature *feature=nullptr)
~Location () override
QString toPlacement () const
Detailed Description
Definition at line 421 of file DlgPrimitives.h.
Constructor & Destructor Documentation
Location()
Location::Location (QWidget * parent = nullptr, Part::Feature * feature = nullptr) explicit
Definition at line 1987 of file DlgPrimitives.cpp.
References Base::Unit::Angle, draftgeoutils.intersections::connect(), and Base::Unit::Length.
~Location()
Location::~Location () override
Definition at line 2010 of file DlgPrimitives.cpp.
References Gui::SoFCUnifiedSelection::selectionMode, and OfflineRenderingUtils::viewer().
Member Function Documentation
toPlacement()
QString Location::toPlacement () const
Definition at line 2161 of file DlgPrimitives.cpp.
References Base::UnitsApi::getDecimals(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by PartGui::TaskPrimitives::accept(), and PartGui::TaskPrimitivesEdit::accept().
The documentation for this class was generated from the following files:
DlgPrimitives.h
DlgPrimitives.cpp