FreeCAD: LinkBaseExtensionPyImp.cpp File Reference
LinkBaseExtensionPyImp.cpp File Reference
#include "PreCompiled.h"
#include <sstream>
#include "DocumentObjectPy.h"
#include "LinkBaseExtensionPy.h"
#include "LinkBaseExtensionPy.cpp"
Typedefs
using PropTmpMap = std::map< std::string, std::pair< int, Property * > >
using PropMap = std::map< std::string, Property * >
Functions
static bool getProperty (PropTmpMap &props, const LinkBaseExtension::PropInfoMap &infoMap, const PropMap &propMap, PyObject *key, PyObject *value)
void parseLink (LinkBaseExtension *ext, int index, PyObject *value)
Typedef Documentation
PropMap
using PropMap = std::map<std::string, Property*>
Definition at line 44 of file LinkBaseExtensionPyImp.cpp.
PropTmpMap
using PropTmpMap = std::map<std::string, std::pair<int, Property*> >
Definition at line 43 of file LinkBaseExtensionPyImp.cpp.
Function Documentation
getProperty()
static bool getProperty (PropTmpMap & props, const LinkBaseExtension::PropInfoMap & infoMap, const PropMap & propMap, PyObject * key, PyObject * value) static
Definition at line 46 of file LinkBaseExtensionPyImp.cpp.
References Base::Type::getName(), Base::Persistence::getTypeId(), Path.Log::info(), Base::BaseClass::isDerivedFrom(), and Path.Post.scripts.refactored_centroid_post::str.
Referenced by Path.Base.Gui.SetupSheet.OpTaskPanel::accept(), Gui::ExpressionBindingPy::bind(), Gui::InputField::bind(), Gui::ExpressionSpinBox::openFormulaDialog(), Gui::PropertyEditor::PropertyItem::setPropertyData(), and Path.Base.Gui.SetupSheet.OpTaskPanel::setupUi().
parseLink()
void parseLink (LinkBaseExtension * ext, int index, PyObject * value)
Definition at line 215 of file LinkBaseExtensionPyImp.cpp.
References create_qrc::ext, App::PropertyString::getValue(), App::PropertyString::setPyObject(), and importers.importIFCmulticore::subs.