FreeCAD: Points::PlyReader Class Reference
Points::PlyReader Class Reference
#include <PointsAlgos.h>
Public Member Functions
PlyReader ()
void read (const std::string &filename) override
Public Member Functions inherited from Points::Reader
Reader ()
virtual ~Reader ()
void clear ()
const PointKernel & getPoints () const
bool hasProperties () const
const std::vector< float > & getIntensities () const
bool hasIntensities () const
const std::vector< App::Color > & getColors () const
bool hasColors () const
const std::vector< Base::Vector3f > & getNormals () const
bool hasNormals () const
bool isStructured () const
int getWidth () const
int getHeight () const
Reader (const Reader &)=delete
Reader (Reader &&)=delete
Reader & operator= (const Reader &)=delete
Reader & operator= (Reader &&)=delete
Additional Inherited Members
Protected Attributes inherited from Points::Reader
PointKernel points
std::vector< float > intensity
std::vector< App::Color > colors
std::vector< Base::Vector3f > normals
int width {0}
int height {1}
Detailed Description
Definition at line 111 of file PointsAlgos.h.
Constructor & Destructor Documentation
PlyReader()
PlyReader::PlyReader () default
Member Function Documentation
read()
void PlyReader::read (const std::string & filename) override virtual
Implements Points::Reader.
Definition at line 548 of file PointsAlgos.cpp.
References a, SCL.SimpleDataTypes::b, blue, Points::Reader::clear(), Points::Reader::colors, DraftVecUtils::find(), toolbit-attributes::g, green, Points::Reader::height, SplineSurface::i, Points::Reader::intensity, KDL::max(), Points::Reader::normals, Points::Reader::points, Points::PointKernel::push_back(), red, Points::PointKernel::reserve(), Points::Reader::width, MovieTool::x, and MovieTool::y.
The documentation for this class was generated from the following files:
PointsAlgos.h
PointsAlgos.cpp