FreeCAD: MeshCore::MeshOutput Class Reference
MeshCore::MeshOutput Class Reference
#include <MeshIO.h>
Public Member Functions
MeshOutput (const MeshKernel &rclM)
MeshOutput (const MeshKernel &rclM, const Material *m)
void SetObjectName (const std::string &n)
void SetGroups (const std::vector< Group > &g)
void Transform (const Base::Matrix4D &)
bool SaveAny (const char *FileName, MeshIO::Format f=MeshIO::Undefined) const
Saves the file, decided by extension if not explicitly given.
bool SaveFormat (std::ostream &str, MeshIO::Format fmt) const
Saves to a stream and the given format.
bool SaveAsciiSTL (std::ostream &output) const
bool SaveBinarySTL (std::ostream &output) const
bool SaveOBJ (std::ostream &output) const
bool SaveOBJ (std::ostream &output, const char *filename) const
bool SaveSMF (std::ostream &output) const
bool SaveOFF (std::ostream &output) const
bool SaveBinaryPLY (std::ostream &output) const
bool SaveAsciiPLY (std::ostream &output) const
bool SaveAsymptote (std::ostream &output) const
void SaveXML (Base::Writer &writer) const
bool Save3MF (std::ostream &output) const
bool SaveMeshNode (std::ostream &output)
bool SaveIDTF (std::ostream &str) const
bool SaveMGL (std::ostream &str) const
bool SaveInventor (std::ostream &output) const
bool SaveX3D (std::ostream &output) const
bool SaveX3DOM (std::ostream &output) const
bool SaveVRML (std::ostream &output) const
bool SaveNastran (std::ostream &output) const
bool SaveCadmouldFE (std::ostream &output) const
bool SavePython (std::ostream &str) const
Static Public Member Functions
static void SetSTLHeaderData (const std::string &)
static void SetAsymptoteSize (const std::string &, const std::string &)
static MeshIO::Format GetFormat (const char *FileName)
Determine the mesh format by file extension.
static std::vector< std::string > supportedMeshFormats ()
Protected Member Functions
bool SaveX3DContent (std::ostream &out, bool exportViewpoints) const
Detailed Description
The MeshOutput class is able to write a mesh object to an output stream on various formats.
Definition at line 170 of file MeshIO.h.
Constructor & Destructor Documentation
MeshOutput() [1/2]
MeshCore::MeshOutput::MeshOutput (const MeshKernel & rclM) inline explicit
Definition at line 173 of file MeshIO.h.
MeshOutput() [2/2]
MeshCore::MeshOutput::MeshOutput (const MeshKernel & rclM, const Material * m) inline
Definition at line 178 of file MeshIO.h.
Member Function Documentation
GetFormat()
MeshIO::Format MeshOutput::GetFormat (const char * FileName) static
Determine the mesh format by file extension.
Definition at line 1302 of file MeshIO.cpp.
References MeshCore::MeshIO::AMF, MeshCore::MeshIO::ASTL, MeshCore::MeshIO::ASY, MeshCore::MeshIO::BMS, MeshCore::MeshIO::BSTL, DrawingExample::file, MeshCore::MeshIO::IDTF, MeshCore::MeshIO::IV, MeshCore::MeshIO::MGL, MeshCore::MeshIO::NAS, MeshCore::MeshIO::OBJ, MeshCore::MeshIO::OFF, MeshCore::MeshIO::PLY, MeshCore::MeshIO::PY, MeshCore::MeshIO::SMF, MeshCore::MeshIO::ThreeMF, MeshCore::MeshIO::Undefined, MeshCore::MeshIO::VRML, MeshCore::MeshIO::WRZ, MeshCore::MeshIO::X3D, MeshCore::MeshIO::X3DOM, and MeshCore::MeshIO::X3DZ.
Referenced by MeshGui::ViewProviderMesh::exportMesh(), and SaveAny().
Save3MF()
bool MeshOutput::Save3MF (std::ostream & output) const
Saves the mesh object into a 3MF file.
Definition at line 2170 of file MeshIO.cpp.
References MeshCore::Writer3MF::AddMesh(), and MeshCore::Writer3MF::Save().
Referenced by SaveAny(), and SaveFormat().
SaveAny()
bool MeshOutput::SaveAny (const char * FileName, MeshIO::Format f = MeshIO::Undefined) const
Saves the file, decided by extension if not explicitly given.
Save in a file, format is decided by the extension if not explicitly given.
Definition at line 1370 of file MeshIO.cpp.
References MeshCore::MeshIO::APLY, MeshCore::MeshIO::ASTL, MeshCore::MeshIO::ASY, MeshCore::MeshIO::BMS, MeshCore::MeshIO::BSTL, Base::FileInfo::exists(), DrawingExample::file, GetFormat(), MeshCore::MeshIO::IDTF, Base::FileInfo::isWritable(), MeshCore::MeshIO::IV, MeshCore::MeshIO::MGL, MeshCore::MeshIO::NAS, MeshCore::MeshIO::OBJ, MeshCore::MeshIO::OFF, MeshCore::MeshIO::PLY, MeshCore::MeshIO::PY, Save3MF(), SaveAsciiPLY(), SaveAsciiSTL(), SaveAsymptote(), SaveBinaryPLY(), SaveBinarySTL(), SaveIDTF(), SaveInventor(), SaveMGL(), SaveNastran(), SaveOBJ(), SaveOFF(), SavePython(), SaveSMF(), SaveVRML(), SaveX3D(), SaveX3DOM(), SetObjectName(), MeshCore::MeshIO::SMF, Path.Post.scripts.refactored_centroid_post::str, MeshCore::MeshIO::ThreeMF, Transform(), MeshCore::MeshIO::Undefined, MeshCore::MeshIO::VRML, MeshCore::MeshKernel::Write(), MeshCore::MeshIO::WRZ, MeshCore::MeshIO::X3D, MeshCore::MeshIO::X3DOM, and MeshCore::MeshIO::X3DZ.
Referenced by Mesh::MeshObject::save().
SaveAsciiPLY()
bool MeshOutput::SaveAsciiPLY (std::ostream & output) const
Saves the mesh object into an ASCII PLY file.
Definition at line 2008 of file MeshIO.cpp.
References SCL.SimpleDataTypes::b, MeshCore::Material::binding, SCL.SimpleDataTypes::c, MeshCore::Material::diffuseColor, SCL.SimpleDataTypes::f, toolbit-attributes::g, MeshCore::MeshKernel::GetFacets(), MeshCore::MeshKernel::GetPoints(), SplineSurface::i, buildPsets::p, MeshCore::MeshIO::PER_VERTEX, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by SaveAny(), and SaveFormat().
SaveAsciiSTL()
bool MeshOutput::SaveAsciiSTL (std::ostream & output) const
Saves the mesh object into an ASCII STL file.
Saves the mesh object into an ASCII file.
Definition at line 1579 of file MeshIO.cpp.
References MeshCore::MeshKernel::CountFacets(), MeshCore::MeshFacetIterator::End(), and Base::SequencerLauncher::next().
Referenced by SaveAny(), and SaveFormat().
SaveAsymptote()
bool MeshOutput::SaveAsymptote (std::ostream & out) const
Saves the mesh object into an asymptote file.
Saves an Asymptote file.
Definition at line 1756 of file MeshIO.cpp.
References MeshCore::MeshFacet::_aulPoints, App::Color::b, MeshCore::Material::binding, SCL.SimpleDataTypes::c, exportCSG::center(), MeshCore::Material::diffuseColor, MeshCore::MeshFacetIterator::End(), App::Color::g, MeshCore::MeshKernel::GetBoundBox(), Base::BoundBox3< Precision >::GetCenter(), MeshCore::MeshKernel::GetFacets(), MeshCore::MeshKernel::GetPoints(), SplineSurface::i, Base::BoundBox3< Precision >::LengthX(), Base::BoundBox3< Precision >::LengthY(), Base::BoundBox3< Precision >::LengthZ(), Base::Matrix4D::multVec(), MeshCore::MeshIO::OVERALL, MeshCore::MeshIO::PER_FACE, MeshCore::MeshIO::PER_VERTEX, App::Color::r, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by SaveAny(), and SaveFormat().
SaveBinaryPLY()
bool MeshOutput::SaveBinaryPLY (std::ostream & output) const
Saves the mesh object into a binary PLY file.
Definition at line 1947 of file MeshIO.cpp.
References SCL.SimpleDataTypes::b, MeshCore::Material::binding, SCL.SimpleDataTypes::c, MeshCore::Material::diffuseColor, SCL.SimpleDataTypes::f, toolbit-attributes::g, MeshCore::MeshKernel::GetFacets(), MeshCore::MeshKernel::GetPoints(), SplineSurface::i, Base::Stream::LittleEndian, buildPsets::p, MeshCore::MeshIO::PER_VERTEX, Base::Stream::setByteOrder(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by SaveAny(), and SaveFormat().
SaveBinarySTL()
bool MeshOutput::SaveBinarySTL (std::ostream & output) const
Saves the mesh object into a binary STL file.
Saves the mesh object into a binary file.
Definition at line 1628 of file MeshIO.cpp.
References MeshCore::MeshKernel::CountFacets(), MeshCore::MeshFacetIterator::End(), SplineSurface::i, Base::SequencerLauncher::next(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by SaveAny(), SaveFormat(), and MeshGui::RemeshGmsh::writeProject().
SaveCadmouldFE()
bool MeshOutput::SaveCadmouldFE (std::ostream & output) const
Writes a Cadmould FE file.
Definition at line 2612 of file MeshIO.cpp.
SaveFormat()
bool MeshOutput::SaveFormat (std::ostream & str, MeshIO::Format fmt) const
Saves to a stream and the given format.
Definition at line 1530 of file MeshIO.cpp.
References MeshCore::MeshIO::APLY, MeshCore::MeshIO::ASTL, MeshCore::MeshIO::ASY, MeshCore::MeshIO::BMS, MeshCore::MeshIO::BSTL, Path.Post.scripts.comparams_post::fmt(), MeshCore::MeshIO::IDTF, MeshCore::MeshIO::IV, MeshCore::MeshIO::MGL, MeshCore::MeshIO::NAS, MeshCore::MeshIO::OBJ, MeshCore::MeshIO::OFF, MeshCore::MeshIO::PLY, MeshCore::MeshIO::PY, Save3MF(), SaveAsciiPLY(), SaveAsciiSTL(), SaveAsymptote(), SaveBinaryPLY(), SaveBinarySTL(), SaveIDTF(), SaveInventor(), SaveMGL(), SaveNastran(), SaveOBJ(), SaveOFF(), SavePython(), SaveSMF(), SaveVRML(), SaveX3D(), SaveX3DOM(), MeshCore::MeshIO::SMF, Path.Post.scripts.refactored_centroid_post::str, MeshCore::MeshIO::ThreeMF, MeshCore::MeshIO::VRML, MeshCore::MeshKernel::Write(), MeshCore::MeshIO::WRZ, MeshCore::MeshIO::X3D, and MeshCore::MeshIO::X3DOM.
Referenced by Mesh::MeshObject::save().
SaveIDTF()
bool MeshOutput::SaveIDTF (std::ostream & str) const
Writes an IDTF file.
Definition at line 2178 of file MeshIO.cpp.
References MeshCore::MeshKernel::CountFacets(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshKernel::GetFacets(), MeshCore::MeshGeomFacet::GetNormal(), MeshCore::MeshKernel::GetPoints(), Path.Post.scripts.refactored_centroid_post::str, Base::tabs(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by SaveAny(), and SaveFormat().
SaveInventor()
bool MeshOutput::SaveInventor (std::ostream & output) const
Writes an OpenInventor file.
Definition at line 2328 of file MeshIO.cpp.
References MeshCore::WriterInventor::Save(), and MeshCore::WriterInventor::SetTransform().
Referenced by SaveAny(), and SaveFormat().
SaveMeshNode()
bool MeshOutput::SaveMeshNode (std::ostream & output)
Saves a node to an OpenInventor file.
Definition at line 2082 of file MeshIO.cpp.
References MeshCore::MeshKernel::GetFacets(), MeshCore::MeshKernel::GetPoints(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
SaveMGL()
bool MeshOutput::SaveMGL (std::ostream & str) const
Writes an MGL file.
Definition at line 2275 of file MeshIO.cpp.
References MeshCore::MeshKernel::CountFacets(), MeshCore::MeshKernel::GetFacets(), MeshCore::MeshKernel::GetPoints(), and Path.Post.scripts.refactored_centroid_post::str.
Referenced by SaveAny(), and SaveFormat().
SaveNastran()
bool MeshOutput::SaveNastran (std::ostream & output) const
Writes a Nastran file.
Definition at line 2559 of file MeshIO.cpp.
References MeshCore::MeshFacet::_aulPoints, MeshCore::MeshKernel::CountFacets(), MeshCore::MeshFacetIterator::GetIndices(), MeshCore::MeshFacetIterator::Init(), MeshCore::MeshPointIterator::Init(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshPointIterator::More(), MeshCore::MeshFacetIterator::Next(), MeshCore::MeshPointIterator::Next(), Base::SequencerLauncher::next(), MeshCore::MeshPointIterator::Transform(), MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by SaveAny(), and SaveFormat().
SaveOBJ() [1/2]
bool MeshOutput::SaveOBJ (std::ostream & out) const
Saves the mesh object into an OBJ file.
Saves an OBJ file.
Definition at line 1678 of file MeshIO.cpp.
References MeshCore::WriterOBJ::Save(), MeshCore::WriterOBJ::SetGroups(), and MeshCore::WriterOBJ::SetTransform().
Referenced by SaveAny(), and SaveFormat().
SaveOBJ() [2/2]
bool MeshOutput::SaveOBJ (std::ostream & output, const char * filename) const
Saves the mesh object into an OBJ file.
Definition at line 1686 of file MeshIO.cpp.
References MeshCore::Material::binding, Base::FileInfo::dirPath(), MeshCore::Material::library, MeshCore::MeshIO::PER_FACE, MeshCore::WriterOBJ::Save(), MeshCore::WriterOBJ::SaveMaterial(), Base::FileInfo::setFile(), MeshCore::WriterOBJ::SetGroups(), and MeshCore::WriterOBJ::SetTransform().
SaveOFF()
bool MeshOutput::SaveOFF (std::ostream & out) const
Saves the mesh object into an OFF file.
Saves an OFF file.
Definition at line 1858 of file MeshIO.cpp.
References a, SCL.SimpleDataTypes::b, MeshCore::Material::binding, SCL.SimpleDataTypes::c, Base::Console(), MeshCore::MeshKernel::CountFacets(), MeshCore::MeshKernel::CountPoints(), MeshCore::Material::diffuseColor, toolbit-attributes::g, MeshCore::MeshKernel::GetFacets(), MeshCore::MeshKernel::GetPoints(), Base::SequencerLauncher::next(), MeshCore::MeshIO::OVERALL, MeshCore::MeshIO::PER_FACE, MeshCore::MeshIO::PER_VERTEX, Base::Vector3< float_type >::Set(), Base::ConsoleSingleton::Warning(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by SaveAny(), and SaveFormat().
SavePython()
bool MeshOutput::SavePython (std::ostream & str) const
Writes a python module which creates a mesh
Writes a Python module
Definition at line 2618 of file MeshIO.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::MeshKernel::CountFacets(), MeshCore::MeshFacetIterator::Init(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), Path.Post.scripts.refactored_centroid_post::str, and MeshCore::MeshFacetIterator::Transform().
Referenced by SaveAny(), and SaveFormat().
SaveSMF()
bool MeshOutput::SaveSMF (std::ostream & out) const
Saves the mesh object into an SMF file.
Saves an SMF file.
Definition at line 1708 of file MeshIO.cpp.
References MeshCore::MeshKernel::CountFacets(), MeshCore::MeshKernel::CountPoints(), MeshCore::MeshKernel::GetFacets(), MeshCore::MeshKernel::GetPoints(), Base::SequencerLauncher::next(), Base::Vector3< float_type >::Set(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by SaveAny(), and SaveFormat().
SaveVRML()
bool MeshOutput::SaveVRML (std::ostream & output) const
Writes a VRML file.
Definition at line 2644 of file MeshIO.cpp.
References MeshCore::MeshFacet::_aulPoints, MeshCore::Material::binding, SCL.SimpleDataTypes::c, MeshCore::MeshKernel::CountFacets(), MeshCore::MeshKernel::CountPoints(), MeshCore::Material::diffuseColor, MeshCore::MeshKernel::GetBoundBox(), MeshCore::MeshFacetIterator::GetIndices(), SplineSurface::i, MeshCore::MeshFacetIterator::Init(), MeshCore::MeshPointIterator::Init(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshPointIterator::More(), MeshCore::MeshFacetIterator::Next(), MeshCore::MeshPointIterator::Next(), Base::SequencerLauncher::next(), MeshCore::MeshIO::OVERALL, MeshCore::MeshIO::PER_VERTEX, MeshCore::MeshFacetIterator::Transform(), MeshCore::MeshPointIterator::Transform(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by SaveAny(), and SaveFormat().
SaveX3D()
bool MeshOutput::SaveX3D (std::ostream & out) const
Writes an X3D file.
Definition at line 2336 of file MeshIO.cpp.
References MeshCore::MeshKernel::CountFacets(), and SaveX3DContent().
Referenced by SaveAny(), and SaveFormat().
SaveX3DContent()
bool MeshOutput::SaveX3DContent (std::ostream & out, bool exportViewpoints) const protected
Writes an X3D file.
Definition at line 2349 of file MeshIO.cpp.
References App::Color::b, MeshCore::Material::binding, SCL.SimpleDataTypes::c, Base::BoundBox3< Precision >::CalcDiagonalLength(), MeshCore::MeshKernel::CountFacets(), MeshCore::Material::diffuseColor, DraftVecUtils::dist(), App::Color::g, MeshCore::MeshKernel::GetBoundBox(), Base::BoundBox3< Precision >::GetCenter(), MeshCore::MeshKernel::GetFacets(), MeshCore::MeshKernel::GetPoints(), Base::Rotation::getValue(), MeshCore::MeshIO::OVERALL, buildPsets::p, MeshCore::MeshIO::PER_FACE, MeshCore::MeshIO::PER_VERTEX, RobotExample::pos, App::Color::r, Base::BoundBox3< Precision >::Transformed(), TestSpreadsheet::v, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by SaveX3D(), and SaveX3DOM().
SaveX3DOM()
bool MeshOutput::SaveX3DOM (std::ostream & out) const
Writes an X3dom file.
Writes an X3DOM file.
Definition at line 2508 of file MeshIO.cpp.
References MeshCore::MeshKernel::CountFacets(), and SaveX3DContent().
Referenced by SaveAny(), and SaveFormat().
SaveXML()
void MeshOutput::SaveXML (Base::Writer & writer) const
Saves the mesh object into an XML file.
Definition at line 2116 of file MeshIO.cpp.
References MeshCore::MeshKernel::CountFacets(), MeshCore::MeshKernel::CountPoints(), Base::Writer::decInd(), MeshCore::MeshKernel::GetFacets(), MeshCore::MeshKernel::GetPoints(), Base::Writer::incInd(), Base::Writer::ind(), Base::Writer::Stream(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by Mesh::PropertyMeshKernel::Save().
SetAsymptoteSize()
void MeshOutput::SetAsymptoteSize (const std::string & w, const std::string & h) static
Change the image size of the asymptote output.
Definition at line 1268 of file MeshIO.cpp.
References src.Mod.PartDesign.fcgear.svggear::w.
Referenced by PyMOD_INIT_FUNC(), and MeshGui::DlgSettingsImportExport::saveSettings().
SetGroups()
void MeshCore::MeshOutput::SetGroups (const std::vector< Group > & g) inline
Definition at line 187 of file MeshIO.h.
References toolbit-attributes::g.
Referenced by Mesh::MeshObject::save().
SetObjectName()
void MeshCore::MeshOutput::SetObjectName (const std::string & n) inline
Definition at line 183 of file MeshIO.h.
Referenced by Mesh::MeshObject::save(), and SaveAny().
SetSTLHeaderData()
void MeshOutput::SetSTLHeaderData (const std::string & header) static
Set custom data to the header of a binary STL. If the data exceeds 80 characters then the characters too much are ignored. If the data has less than 80 characters they are automatically filled up with spaces.
Definition at line 1251 of file MeshIO.cpp.
supportedMeshFormats()
std::vector< std::string > MeshOutput::supportedMeshFormats () static
Definition at line 1282 of file MeshIO.cpp.
References Path.Post.scripts.comparams_post::fmt().
Transform()
void MeshOutput::Transform (const Base::Matrix4D & mat)
Definition at line 1274 of file MeshIO.cpp.
Referenced by Mesh::MeshObject::save(), and SaveAny().
The documentation for this class was generated from the following files:
MeshIO.h
MeshIO.cpp