FreeCAD: JtReader.h File Reference
JtReader.h File Reference
Classes
struct SimpleMeshFacet
Functions
void readFile (const char *FileName, int iLods=0)
void writeAsciiSTL (const char *FileName)
const SimpleMeshFacet * iterStart (void)
const SimpleMeshFacet * iterGetNext (void)
unsigned int iterSize (void)
void clearData (void)
Function Documentation
clearData()
void clearData (void)
clears the internal structure
Definition at line 654 of file JtReader.cpp.
References InfoOut, my_level, result, and resultIt.
iterGetNext()
const SimpleMeshFacet* iterGetNext (void)
get the faces or 0 at end
Definition at line 637 of file JtReader.cpp.
References result, and resultIt.
iterSize()
unsigned int iterSize (void)
size of the result
Definition at line 647 of file JtReader.cpp.
References result.
iterStart()
const SimpleMeshFacet* iterStart (void)
start the iterator on the result
Definition at line 626 of file JtReader.cpp.
References result, and resultIt.
readFile()
void readFile (const char * FileName, int iLods = 0)
Reads a JT File an build up the internal data structure imports all the meshes of all Parts, recursing the Assamblies.
Definition at line 580 of file JtReader.cpp.
References iLod, myPreactionCB_CollectFacets(), and testLicence().
Referenced by Gui::GraphicsScene::setNavigationModeFile(), and SIM::Coin3D::Quarter::QuarterWidget::setNavigationModeFile().
writeAsciiSTL()
void writeAsciiSTL (const char * FileName)
Write the read Part to a file