FreeCAD: App::PropertyLinkSub Class Reference
App::PropertyLinkSub Class Reference
#include <PropertyLinks.h>
Public Member Functions
PropertyLinkSub ()
~PropertyLinkSub () override
void afterRestore () override
void onContainerRestored () override
void setValue (App::DocumentObject *, const std::vector< std::string > &SubList, std::vector< ShadowSub > &&ShadowSubList={})
void setValue (App::DocumentObject *, std::vector< std::string > &&SubList={}, std::vector< ShadowSub > &&ShadowSubList={})
App::DocumentObject * getValue () const
const std::vector< std::string > & getSubValues () const
return the list of sub elements
const std::vector< ShadowSub > & getShadowSubs () const
return the list of sub elements with mapped names
std::vector< std::string > getSubValues (bool newStyle) const
std::vector< std::string > getSubValuesStartsWith (const char *, bool newStyle=false) const
return the list of sub elements starts with a special string
App::DocumentObject * getValue (Base::Type t) const
template<typename _type >
_type getValue () const
PyObject * getPyObject () override
void setPyObject (PyObject *value) override
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
Property * Copy () const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
const char * getEditorName () const override
Get the class name of the associated property editor item.
Property * CopyOnImportExternal (const std::map< std::string, std::string > &nameMap) const override
Return a copy of the property if any changes caused by importing external object.
Property * CopyOnLabelChange (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const override
Property * CopyOnLinkReplace (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const override
unsigned int getMemSize () const override
void updateElementReference (DocumentObject *feature, bool reverse=false, bool notify=false) override
bool referenceChanged () const override
Test if the element reference has changed after restore.
void getLinks (std::vector< App::DocumentObject * > &objs, bool all=false, std::vector< std::string > *subs=nullptr, bool newStyle=true) const override
void getLinksTo (std::vector< App::ObjectIdentifier > &identifiers, App::DocumentObject *obj, const char *subname=nullptr, bool all=false) const override
void breakLink (App::DocumentObject *obj, bool clear) override
bool adjustLink (const std::set< App::DocumentObject * > &inList) override
void setSyncSubObject (bool enable)
Public Member Functions inherited from App::PropertyLinkBase
PropertyLinkBase ()
~PropertyLinkBase () override
void unregisterElementReference ()
Clear internal element reference registration.
void registerLabelReferences (std::vector< std::string > &&labels, bool reset=true)
void checkLabelReferences (const std::vector< std::string > &subs, bool reset=true)
void unregisterLabelReferences ()
Clear internal label references registration.
virtual int checkRestore (std::string *msg=nullptr) const
std::vector< App::DocumentObject * > linkedObjects (bool all=false) const
Helper function to return all linked objects of this property.
template<class T >
void getLinkedObjects (T &inserter, bool all=false) const
Helper function to return linked objects using an std::inserter.
void getLinkedElements (std::map< App::DocumentObject *, std::vector< std::string >> &elements, bool newStyle=true, bool all=false) const
Helper function to return a map of linked object and its subname references.
std::map< App::DocumentObject *, std::vector< std::string > > linkedElements (bool newStyle=true, bool all=false) const
Helper function to return a map of linked object and its subname references.
bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
void setAllowExternal (bool allow)
bool _updateElementReference (App::DocumentObject *feature, App::DocumentObject *obj, std::string &sub, ShadowSub &shadow, bool reverse, bool notify=false)
void _registerElementReference (App::DocumentObject *obj, std::string &sub, ShadowSub &shadow)
bool testFlag (int flag) const
virtual void setAllowPartial (bool enable)
void setReturnNewElement (bool enable)
void setSilentRestore (bool enable)
Public Member Functions inherited from App::Property
Property ()
~Property () override
const char * getName () const
bool hasName () const
std::string getFullName () const
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
int64_t getID () const
virtual void beforeSave () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::ScopedLink
void setScope (LinkScope scope)
Set the links scope Allows to define what kind of links are allowed. Only in the Local GeoFeatureGroup, in this and all Childs or to all objects within the Glocal scope.
LinkScope getScope () const
Get the links scope Retrieve what kind of links are allowed. Only in the Local GeoFeatureGroup, in this and all Childs or to all objects within the Glocal scope.
Protected Attributes
App::DocumentObject * _pcLinkSub {nullptr}
std::vector< std::string > _cSubList
std::vector< ShadowSub > _ShadowSubList
std::vector< int > _mapped
bool _restoreLabel {false}
Protected Attributes inherited from App::PropertyLinkBase
std::bitset< 32 > _Flags
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::ScopedLink
LinkScope _pcScope = LinkScope::Local
Additional Inherited Members
Public Types inherited from App::PropertyLinkBase
enum LinkFlags {
LinkAllowExternal, LinkDetached, LinkRestoring, LinkAllowPartial,
LinkRestoreLabel, LinkSyncSubObject, LinkNewElement, LinkSilentRestore
}
using ShadowSub = ElementNamePair
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Static Public Member Functions inherited from App::PropertyLinkBase
static std::pair< App::DocumentObject *, std::string > tryReplaceLink (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const char *sub=nullptr)
Helper functions.
static std::pair< App::DocumentObject *, std::vector< std::string > > tryReplaceLinkSubs (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const std::vector< std::string > &subs)
static void updateElementReferences (DocumentObject *feature, bool reverse=false)
Update all element references in all link properties of feature.
static const std::unordered_set< PropertyLinkBase * > & getElementReferences (DocumentObject *)
Obtain link properties that contain element references to a given object.
static void breakLinks (App::DocumentObject *link, const std::vector< App::DocumentObject * > &objs, bool clear)
static std::string tryImportSubName (const App::DocumentObject *obj, const char *sub, const App::Document *doc, const std::map< std::string, std::string > &nameMap)
static App::DocumentObject * tryImport (const App::Document *doc, const App::DocumentObject *obj, const std::map< std::string, std::string > &nameMap)
static const char * exportSubName (std::string &output, const App::DocumentObject *obj, const char *subname, bool first_obj=false)
static std::string importSubName (Base::XMLReader &reader, const char *sub, bool &restoreLabel)
static void restoreLabelReference (const App::DocumentObject *obj, std::string &sub, ShadowSub *shadow=nullptr)
static void getLabelReferences (std::vector< std::string > &labels, const char *subname)
static std::vector< std::pair< Property *, std::unique_ptr< Property > > > updateLabelReferences (App::DocumentObject *obj, const char *newLabel)
static std::string updateLabelReference (const App::DocumentObject *linked, const char *subname, App::DocumentObject *obj, const std::string &ref, const char *newLabel)
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::PropertyLinkBase
boost::signals2::signal< void(const std::string &, const std::string &)> signalUpdateElementReference
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::PropertyLinkBase
void hasSetValue () override
Gets called by all setValue() methods after the value has changed.
void setFlag (int flag, bool value=true)
void _getLinksTo (std::vector< App::ObjectIdentifier > &identifiers, App::DocumentObject *obj, const char *subname, const std::vector< std::string > &subs, const std::vector< PropertyLinkBase::ShadowSub > &shadows) const
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue ()
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
the Link Property with sub elements This property links an object and a defined sequence of sub elements. These subelements (like Edges of a Shape) are stored as names, which can be resolved by the ComplexGeoDataType interface to concrete sub objects.
Definition at line 894 of file PropertyLinks.h.
Constructor & Destructor Documentation
PropertyLinkSub()
PropertyLinkSub::PropertyLinkSub () default
A constructor. A more elaborate description of the constructor.
Referenced by Copy(), CopyOnImportExternal(), CopyOnLabelChange(), and CopyOnLinkReplace().
~PropertyLinkSub()
PropertyLinkSub::~PropertyLinkSub () override
A destructor. A more elaborate description of the destructor.
Definition at line 1297 of file PropertyLinks.cpp.
References _pcLinkSub, App::ScopedLink::_pcScope, App::DocumentObject::_removeBackLink(), App::Destroy, Base::Persistence::getClassTypeId(), App::Property::getContainer(), App::Hidden, Base::BaseClass::isDerivedFrom(), and Init::parent.
Member Function Documentation
adjustLink()
bool PropertyLinkSub::adjustLink (const std::set< App::DocumentObject * > & inList) override virtual
Called to adjust the link to avoid potential cyclic dependency
Parameters
inList recursive in-list of the would-be parent
Returns
Return whether the link has been adjusted
This function tries to correct the link to avoid any (sub)object inside in-list. If the adjustment is impossible, exception will be raised
Implements App::PropertyLinkBase.
Definition at line 2143 of file PropertyLinks.cpp.
References _cSubList, _pcLinkSub, App::ScopedLink::_pcScope, adjustLinkSubs(), App::Hidden, App::DocumentObject::isAttachedToDocument(), Path.Post.scripts.opensbp_post::move(), setValue(), and importers.importIFCmulticore::subs.
Referenced by App::ObjectIdentifier::adjustLinks().
afterRestore()
void PropertyLinkSub::afterRestore () override virtual
Called at the beginning of Document::afterRestore()
This function is called without dependency sorting, because some types of link property can only reconstructs the linking information inside this function.
One example use case of this function is PropertyLinkSub that uses afterRestore() to parse and restore subname references, which may contain sub-object reference from external document, and there will be special mapping required during object import.
Another example is PropertyExpressionEngine which only parse the restored expression in afterRestore(). The reason, in addition to subname mapping like PropertyLinkSub, is that it can handle document name adjustment as well. It internally relies on PropertyXLink to store the external document path for external linking. When the external document is restored, its internal name may change due to name conflict with existing documents. PropertyExpressionEngine can now auto adjust external references without any problem.
Reimplemented from App::Property.
Definition at line 1562 of file PropertyLinks.cpp.
References _cSubList, _pcLinkSub, _ShadowSubList, SplineSurface::i, App::DocumentObject::isAttachedToDocument(), App::PropertyLinkBase::LinkRestoreLabel, App::PropertyLinkBase::restoreLabelReference(), App::PropertyLinkBase::setFlag(), and App::PropertyLinkBase::testFlag().
breakLink()
void PropertyLinkSub::breakLink (App::DocumentObject * obj, bool clear) override virtual
Called to reset this link property
Parameters
obj reset link property if it is linked to this object
clear if true, then also reset property if the owner of this property is obj
See also
breakLinks()
Implements App::PropertyLinkBase.
Definition at line 2091 of file PropertyLinks.cpp.
References _pcLinkSub, Path.Op.Gui.Selection::clear(), App::Property::getContainer(), and setValue().
Copy()
Property * PropertyLinkSub::Copy () const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 2046 of file PropertyLinks.cpp.
References _cSubList, _pcLinkSub, _ShadowSubList, buildPsets::p, and PropertyLinkSub().
CopyOnImportExternal()
Property * PropertyLinkSub::CopyOnImportExternal (const std::map< std::string, std::string > & nameMap) const override virtual
Return a copy of the property if any changes caused by importing external object.
Reimplemented from App::PropertyLinkBase.
Definition at line 1981 of file PropertyLinks.cpp.
References _cSubList, _pcLinkSub, App::Property::getContainer(), App::DocumentObject::isAttachedToDocument(), Path.Post.scripts.opensbp_post::move(), buildPsets::p, PropertyLinkSub(), importers.importIFCmulticore::subs, App::PropertyLinkBase::tryImport(), App::PropertyLinkBase::tryImportSubName(), and updateLinkSubs().
CopyOnLabelChange()
Property * PropertyLinkSub::CopyOnLabelChange (App::DocumentObject * obj, const std::string & ref, const char * newLabel) const override virtual
Update object label reference in this property
Parameters
obj the object owner of the changing label
ref subname reference to old label
newLabel the future new label
Returns
Returns a copy of the property if its link reference is affected. The copy will later be assgiend to this property by calling its Paste().
Reimplemented from App::PropertyLinkBase.
Definition at line 2009 of file PropertyLinks.cpp.
References _cSubList, _pcLinkSub, App::Property::getContainer(), App::DocumentObject::isAttachedToDocument(), Path.Post.scripts.opensbp_post::move(), buildPsets::p, PropertyLinkSub(), importers.importIFCmulticore::subs, App::PropertyLinkBase::updateLabelReference(), and updateLinkSubs().
CopyOnLinkReplace()
Property * PropertyLinkSub::CopyOnLinkReplace (const App::DocumentObject * parent, App::DocumentObject * oldObj, App::DocumentObject * newObj) const override virtual
Return a copy of the property if the link replacement affects this property
Parameters
owner the parent object whose link property is to be replace. Note that The parent may not be the container of this property. Link sub property can use this opportunity to adjust its relative links.
oldObj object to be replaced
newObj object to replace with
Returns
Return a copy of the property that is adjusted for the link replacement operation.
Implements App::PropertyLinkBase.
Definition at line 2032 of file PropertyLinks.cpp.
References _cSubList, _pcLinkSub, App::Property::getContainer(), Path.Post.scripts.opensbp_post::move(), buildPsets::p, Init::parent, PropertyLinkSub(), and App::PropertyLinkBase::tryReplaceLinkSubs().
getEditorName()
const char* App::PropertyLinkSub::getEditorName () const inline override virtual
Get the class name of the associated property editor item.
Reimplemented from App::Property.
Definition at line 962 of file PropertyLinks.h.
getLinks()
void PropertyLinkSub::getLinks (std::vector< App::DocumentObject * > & objs, bool all = false, std::vector< std::string > * subs = nullptr, bool newStyle = true) const override virtual
Obtain the linked objects
Parameters
objs hold the returned linked objects on output
all if true, then return all the linked object regardless of this LinkScope. If false, then return only if the LinkScope is not hidden.
sub if given, then return subname references.
newStyle whether to return new or old style subname reference
Implements App::PropertyLinkBase.
Definition at line 2064 of file PropertyLinks.cpp.
References _pcLinkSub, App::ScopedLink::_pcScope, getSubValues(), App::Hidden, App::DocumentObject::isAttachedToDocument(), replaceobj::objs, and importers.importIFCmulticore::subs.
getLinksTo()
void PropertyLinkSub::getLinksTo (std::vector< App::ObjectIdentifier > & identifiers, App::DocumentObject * obj, const char * subname = nullptr, bool all = false) const override virtual
Obtain identifiers from this link property that link to a given object
Parameters
identifiers holds the returned identifier to reference the given object
obj the referenced object
subname optional subname reference
all if true, then return all the references regardless of this LinkScope. If false, then return only if the LinkScope is not hidden.
Implements App::PropertyLinkBase.
Definition at line 2079 of file PropertyLinks.cpp.
References _cSubList, App::PropertyLinkBase::_getLinksTo(), _pcLinkSub, App::ScopedLink::_pcScope, _ShadowSubList, and App::Hidden.
getMemSize()
unsigned int App::PropertyLinkSub::getMemSize () const inline override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence
See also
Base::Persistence
Reimplemented from App::Property.
Definition at line 979 of file PropertyLinks.h.
getPyObject()
PyObject * PropertyLinkSub::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 1436 of file PropertyLinks.cpp.
References _cSubList, _pcLinkSub, App::DocumentObject::getPyObject(), getSubValues(), SplineSurface::i, App::PropertyLinkBase::LinkNewElement, Py::new_reference_to(), src.Mod.Test.testmakeWireString::String, App::PropertyLinkBase::testFlag(), and DraftVecUtils::tup().
getShadowSubs()
const std::vector<ShadowSub>& App::PropertyLinkSub::getShadowSubs () const inline
return the list of sub elements with mapped names
Definition at line 931 of file PropertyLinks.h.
Referenced by Part::Chamfer::execute(), and Part::Fillet::execute().
getSubValues() [1/2]
const std::vector< std::string > & PropertyLinkSub::getSubValues () const
return the list of sub elements
Definition at line 1374 of file PropertyLinks.cpp.
References _cSubList.
Referenced by PartGui::DlgRevolution::accept(), SurfaceGui::FillingPanel::accept(), PartDesignGui::TaskDressUpParameters::addAllEdges(), App::ObjectIdentifier::adjustLinks(), TechDraw::DrawHatch::affectsFace(), PartDesign::FeatureExtrude::buildExtrusion(), PartDesign::FeatureExtrude::computeDirection(), PartDesignGui::TaskDressUpParameters::deleteRef(), TechDraw::DrawHatch::empty(), Surface::Filling::execute(), Measure::MeasureDistance::execute(), Part::Chamfer::execute(), Part::Fillet::execute(), PartDesign::Loft::execute(), Part::Mirroring::execute(), Part::RuledSurface::execute(), PartDesign::Pipe::execute(), Surface::Extend::execute(), Measure::MeasurePosition::execute(), Measure::MeasureAngle::execute(), Part::Thickness::execute(), Part::AttachExtension::extensionHandleChangedPropertyName(), Part::Revolution::fetchAxisLink(), Part::Extrusion::fetchAxisLink(), PartDesignGui::TaskRevolutionParameters::fillAxisCombo(), PartDesignGui::TaskExtrudeParameters::fillDirectionCombo(), Fem::Constraint::getBasePoint(), Fem::Constraint::getDirection(), PartDesign::ProfileBased::getFaceFromLinkSub(), getLinks(), PartDesign::ProfileBased::getProfileShape(), PartDesign::ProfileBased::getProfileWires(), getPyObject(), PartDesignGui::TaskRevolutionParameters::getReferenceAxis(), PartDesignGui::TaskHelixParameters::getReferenceAxis(), PartDesignGui::TaskExtrudeParameters::getReferenceAxis(), PartDesignGui::TaskDressUpParameters::getReferences(), Measure::MeasureDistance::getShape(), PartDesign::ProfileBased::getTopoShapeVerifiedFace(), PartDesign::LinearPattern::getTransformations(), PartDesign::Mirrored::getTransformations(), PartDesign::PolarPattern::getTransformations(), PartDesign::ProfileBased::getUpToFaceFromLinkSub(), PartDesignGui::ViewProviderLoft::highlightProfile(), importExternalElements(), Measure::MeasureAngle::location1(), Measure::MeasureAngle::location2(), Fem::ConstraintBearing::onChanged(), PartDesignGui::TaskExtrudeParameters::onDirectionCBChanged(), Part::FilletBase::onDocumentRestored(), Part::FilletBase::onUpdateElementReference(), SurfaceGui::FillingPanel::open(), PartDesignGui::TaskDressUpParameters::referenceSelected(), SurfaceGui::FillingPanel::reject(), PartDesignGui::relinkToBody(), TechDraw::DrawHatch::removeSub(), PartGui::DlgExtrusion::setAxisLink(), PartGui::DlgRevolution::setAxisLink(), PartDesignGui::ComboLinks::setCurrentLink(), SurfaceGui::FillingPanel::setEditedObject(), App::PropertyLinkSubList::setPyObject(), App::PropertyXLinkSubList::setPyObject(), PartDesignGui::TaskRevolutionParameters::setupDialog(), SurfaceGui::FillingPanel::slotDeletedObject(), PartDesignGui::TaskChamferParameters::TaskChamferParameters(), PartDesignGui::TaskDraftParameters::TaskDraftParameters(), FemGui::TaskFemConstraintBearing::TaskFemConstraintBearing(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), FemGui::TaskFemConstraintForce::TaskFemConstraintForce(), FemGui::TaskFemConstraintGear::TaskFemConstraintGear(), PartDesignGui::TaskFilletParameters::TaskFilletParameters(), PartDesignGui::TaskLoftParameters::TaskLoftParameters(), PartDesignGui::TaskPipeOrientation::TaskPipeOrientation(), PartDesignGui::TaskPipeParameters::TaskPipeParameters(), PartDesign::Helix::updateAxis(), PartDesign::Revolution::updateAxis(), PartDesign::Groove::updateAxis(), App::PropertyLinkSubList::upgrade(), App::PropertyXLinkSub::upgrade(), Measure::MeasureAngle::vector1(), Measure::MeasureAngle::vector2(), and PartGui::DlgExtrusion::writeParametersToFeature().
getSubValues() [2/2]
std::vector< std::string > PropertyLinkSub::getSubValues (bool newStyle) const
Definition at line 1403 of file PropertyLinks.cpp.
References _cSubList, _ShadowSubList, getSubNameWithStyle(), and SplineSurface::i.
getSubValuesStartsWith()
std::vector< std::string > PropertyLinkSub::getSubValuesStartsWith (const char * starter, bool newStyle = false) const
return the list of sub elements starts with a special string
Definition at line 1415 of file PropertyLinks.cpp.
References _cSubList, _ShadowSubList, Data::findElementName(), getSubNameWithStyle(), and SplineSurface::i.
Referenced by PartDesignGui::ViewProviderDressUp::highlightReferences(), and PartDesignGui::ViewProviderPipe::highlightReferences().
getValue() [1/3]
App::DocumentObject * PropertyLinkSub::getValue () const
This method returns the linked DocumentObject
Definition at line 1369 of file PropertyLinks.cpp.
References _pcLinkSub.
Referenced by PartGui::DlgRevolution::accept(), SurfaceGui::FillingPanel::accept(), PartDesignGui::TaskDressUpParameters::addAllEdges(), PartDesignGui::ComboLinks::addLink(), App::ObjectIdentifier::adjustLinks(), PartDesignGui::ViewProviderPipe::claimChildren(), PartDesign::FeatureExtrude::computeDirection(), Surface::Filling::execute(), Measure::MeasureDistance::execute(), PartDesign::Loft::execute(), Part::Mirroring::execute(), Part::RuledSurface::execute(), PartDesign::Pipe::execute(), Surface::Extend::execute(), Measure::MeasurePosition::execute(), Measure::MeasureAngle::execute(), Part::Thickness::execute(), Part::AttachExtension::extensionHandleChangedPropertyName(), Part::Revolution::fetchAxisLink(), Part::Extrusion::fetchAxisLink(), PartDesignGui::TaskRevolutionParameters::fillAxisCombo(), PartDesignGui::TaskExtrudeParameters::fillDirectionCombo(), PartDesign::ProfileBased::getAxis(), Fem::Constraint::getBasePoint(), Fem::Constraint::getDirection(), PartDesign::ProfileBased::getFaceFromLinkSub(), PartDesign::ProfileBased::getProfileShape(), PartDesign::ProfileBased::getProfileWires(), PartDesignGui::TaskRevolutionParameters::getReferenceAxis(), PartDesignGui::TaskHelixParameters::getReferenceAxis(), PartDesignGui::TaskExtrudeParameters::getReferenceAxis(), Measure::MeasureDistance::getShape(), PartDesign::ProfileBased::getSketchAxisCount(), TechDraw::DrawHatch::getSourceView(), TechDraw::DrawGeomHatch::getSourceView(), Measure::MeasureAngle::getSubject(), Measure::MeasurePosition::getSubject(), Measure::MeasureRadius::getSubject(), PartDesign::ProfileBased::getSupportFace(), PartDesign::ProfileBased::getTopoShapeVerifiedFace(), PartDesign::LinearPattern::getTransformations(), PartDesign::Mirrored::getTransformations(), PartDesign::PolarPattern::getTransformations(), PartDesign::ProfileBased::getUpToFaceFromLinkSub(), PartDesign::ProfileBased::getVerifiedFace(), PartDesign::ProfileBased::getVerifiedObject(), PartDesign::ProfileBased::getVerifiedSketch(), PartDesignGui::ViewProviderLoft::highlightProfile(), PartDesignGui::ViewProviderPipe::highlightReferences(), importExternalElements(), Measure::MeasureAngle::location1(), Measure::MeasureAngle::location2(), Part::Revolution::onChanged(), Part::Mirroring::onChanged(), Fem::ConstraintForce::onChanged(), Fem::ConstraintBearing::onChanged(), Fem::ConstraintFluidBoundary::onChanged(), PartDesign::ProfileBased::onChanged(), PartGui::ViewProviderRuledSurface::onDelete(), PartDesignGui::ViewProviderHole::onDelete(), PartDesignGui::ViewProviderSketchBased::onDelete(), PartDesignGui::ViewProviderHelix::onDelete(), PartGui::ViewProviderThickness::onDelete(), PartDesignGui::TaskExtrudeParameters::onDirectionCBChanged(), SurfaceGui::FillingPanel::open(), PartGui::ThicknessWidget::reject(), SurfaceGui::FillingPanel::reject(), PartDesignGui::relinkToBody(), TechDraw::DrawHatch::removeSub(), PartGui::DlgExtrusion::setAxisLink(), PartGui::DlgRevolution::setAxisLink(), PartDesignGui::ComboLinks::setCurrentLink(), PartGui::ViewProviderMirror::setEdit(), SurfaceGui::FillingPanel::setEditedObject(), RobotGui::TaskEdge2TracParameter::setHideShowObject(), App::PropertyLinkSubList::setPyObject(), App::PropertyXLinkSubList::setPyObject(), PartGui::ViewProviderMirror::setupContextMenu(), PartDesignGui::TaskRevolutionParameters::setupDialog(), SurfaceGui::FillingPanel::slotDeletedObject(), PartDesignGui::TaskDraftParameters::TaskDraftParameters(), FemGui::TaskFemConstraintBearing::TaskFemConstraintBearing(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), FemGui::TaskFemConstraintForce::TaskFemConstraintForce(), FemGui::TaskFemConstraintGear::TaskFemConstraintGear(), TechDrawGui::TaskGeomHatch::TaskGeomHatch(), TechDrawGui::TaskHatch::TaskHatch(), PartDesignGui::TaskLoftParameters::TaskLoftParameters(), PartDesignGui::TaskPipeOrientation::TaskPipeOrientation(), PartDesignGui::TaskPipeParameters::TaskPipeParameters(), TechDraw::DrawHatch::unsetupObject(), TechDraw::DrawGeomHatch::unsetupObject(), PartDesign::Helix::updateAxis(), PartDesign::Revolution::updateAxis(), PartDesign::Groove::updateAxis(), PartDesignGui::TaskDressUpParameters::updateFeature(), App::PropertyLinkSubList::upgrade(), App::PropertyXLinkSub::upgrade(), Measure::MeasureAngle::vector1(), Measure::MeasureAngle::vector2(), and PartGui::DlgExtrusion::writeParametersToFeature().
getValue() [2/3]
template<typename _type > _type App::PropertyLinkSub::getValue () const inline
Returns the link type checked
Definition at line 948 of file PropertyLinks.h.
getValue() [3/3]
App::DocumentObject * PropertyLinkSub::getValue (Base::Type t) const
Returns the link type checked
Definition at line 1431 of file PropertyLinks.cpp.
References _pcLinkSub, Base::Persistence::getTypeId(), Base::Type::isDerivedFrom(), and InitGui::t.
onContainerRestored()
void PropertyLinkSub::onContainerRestored () override virtual
Called before calling DocumentObject::onDocumentRestored()
This function is called after finished calling Property::afterRestore() of all properties of objects. By then, the object dependency information is assumed ready. So, unlike Property::afterRestore(), this function is called on objects with dependency order.
Reimplemented from App::Property.
Definition at line 1574 of file PropertyLinks.cpp.
References _cSubList, _pcLinkSub, App::PropertyLinkBase::_registerElementReference(), _ShadowSubList, SplineSurface::i, App::DocumentObject::isAttachedToDocument(), and App::PropertyLinkBase::unregisterElementReference().
Paste()
void PropertyLinkSub::Paste (const Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 2055 of file PropertyLinks.cpp.
References Base::Persistence::getClassTypeId(), Base::BaseClass::isDerivedFrom(), and setValue().
Referenced by PartDesignGui::ComboLinks::addLink(), and PartDesignGui::TaskExtrudeParameters::onDirectionCBChanged().
referenceChanged()
bool PropertyLinkSub::referenceChanged () const override virtual
Test if the element reference has changed after restore.
Reimplemented from App::PropertyLinkBase.
Definition at line 1602 of file PropertyLinks.cpp.
References _mapped.
Restore()
void PropertyLinkSub::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 1893 of file PropertyLinks.cpp.
References _mapped, ATTR_MAPPED, ATTR_SHADOW, ATTR_SHADOWED, src.Mod.AddonManager.NetworkManager::count, FC_WARN, App::Property::getContainer(), App::Document::getObject(), SplineSurface::i, IGNORE_SHADOW, App::PropertyLinkBase::importSubName(), App::PropertyLinkBase::LinkRestoreLabel, Path.Post.scripts.opensbp_post::move(), TechDrawTools.TaskFillTemplateFields::reader, App::PropertyLinkBase::setFlag(), and setValue().
Referenced by Part::AttachExtension::extensionHandleChangedPropertyName(), App::PropertyLinkSubList::upgrade(), and App::PropertyXLinkSub::upgrade().
Save()
void PropertyLinkSub::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 1842 of file PropertyLinks.cpp.
References _cSubList, _pcLinkSub, _ShadowSubList, ATTR_MAPPED, ATTR_SHADOW, ATTR_SHADOWED, Base::Writer::decInd(), Base::Persistence::encodeAttribute(), App::PropertyLinkBase::exportSubName(), App::Property::getContainer(), App::DocumentObject::getExportName(), SplineSurface::i, Base::Writer::incInd(), Base::Writer::ind(), App::DocumentObject::isAttachedToDocument(), and Base::Writer::Stream().
setPyObject()
void PropertyLinkSub::setPyObject (PyObject * value) override virtual
Reimplemented from Base::BaseClass.
Definition at line 1454 of file PropertyLinks.cpp.
References Path.Log::error(), App::PropertyString::getValue(), SplineSurface::i, Path.Post.scripts.opensbp_post::move(), App::PropertyString::setPyObject(), and setValue().
Referenced by App::PropertyLinkSubList::setPyObject(), and App::PropertyXLinkSubList::setPyObject().
setSyncSubObject()
void PropertyLinkSub::setSyncSubObject (bool enable)
Definition at line 1315 of file PropertyLinks.cpp.
References App::PropertyLinkBase::_Flags, and App::PropertyLinkBase::LinkSyncSubObject.
setValue() [1/2]
void App::PropertyLinkSub::setValue (App::DocumentObject * , const std::vector< std::string > & SubList, std::vector< ShadowSub > && ShadowSubList = {})
Sets the property
Referenced by PartDesignGui::TaskDressUpParameters::addAllEdges(), PartDesignGui::TaskRevolutionParameters::addAxisToCombo(), PartDesignGui::TaskExtrudeParameters::addAxisToCombo(), PartDesignGui::ComboLinks::addLink(), adjustLink(), App::ObjectIdentifier::adjustLinks(), breakLink(), TechDrawGui::TaskHatch::createHatch(), PartGui::DlgExtrusion::getAxisLink(), PartGui::DlgRevolution::getAxisLink(), PartDesign::ProfileBased::handleChangedPropertyName(), importExternalElements(), FemGui::TaskFemConstraintBearing::onSelectionChanged(), PartDesignGui::TaskRevolutionParameters::onSelectionChanged(), PartDesignGui::TaskHelixParameters::onSelectionChanged(), FemGui::TaskFemConstraintGear::onSelectionChanged(), SurfaceGui::FillingPanel::onSelectionChanged(), Measure::MeasureDistance::parseSelection(), Measure::MeasureRadius::parseSelection(), Measure::MeasurePosition::parseSelection(), Measure::MeasureAngle::parseSelection(), Paste(), TechDraw::DrawHatch::removeSub(), Restore(), setPyObject(), Part::FilletBase::syncEdgeLink(), and PartDesignGui::TaskDressUpParameters::updateFeature().
setValue() [2/2]
void App::PropertyLinkSub::setValue (App::DocumentObject * , std::vector< std::string > && SubList = {}, std::vector< ShadowSub > && ShadowSubList = {})
updateElementReference()
void PropertyLinkSub::updateElementReference (DocumentObject * feature, bool reverse = false, bool notify = false) override virtual
Link type property interface APIs These APIs are moved here so that any type of property can have the property link behavior, e.g. the PropertyExpressionEngine Called to update the element reference of this link property
See also
_updateElementReference()
Reimplemented from App::PropertyLinkBase.
Definition at line 1585 of file PropertyLinks.cpp.
References _cSubList, _mapped, _pcLinkSub, _ShadowSubList, App::PropertyLinkBase::hasSetValue(), femsolver.signal::notify(), and updateLinkReference().
Member Data Documentation
_cSubList
std::vector<std::string> App::PropertyLinkSub::_cSubList protected
Definition at line 1008 of file PropertyLinks.h.
Referenced by adjustLink(), afterRestore(), Copy(), CopyOnImportExternal(), CopyOnLabelChange(), CopyOnLinkReplace(), getLinksTo(), getPyObject(), getSubValues(), getSubValuesStartsWith(), onContainerRestored(), Save(), and updateElementReference().
_mapped
std::vector<int> App::PropertyLinkSub::_mapped protected
Definition at line 1010 of file PropertyLinks.h.
Referenced by referenceChanged(), Restore(), and updateElementReference().
_pcLinkSub
App::DocumentObject* App::PropertyLinkSub::_pcLinkSub {nullptr} protected
Definition at line 1007 of file PropertyLinks.h.
Referenced by adjustLink(), afterRestore(), breakLink(), Copy(), CopyOnImportExternal(), CopyOnLabelChange(), CopyOnLinkReplace(), getLinks(), getLinksTo(), getPyObject(), getValue(), onContainerRestored(), Save(), updateElementReference(), and ~PropertyLinkSub().
_restoreLabel
bool App::PropertyLinkSub::_restoreLabel {false} protected
Definition at line 1011 of file PropertyLinks.h.
_ShadowSubList
std::vector<ShadowSub> App::PropertyLinkSub::_ShadowSubList protected
Definition at line 1009 of file PropertyLinks.h.
Referenced by afterRestore(), Copy(), getLinksTo(), getSubValues(), getSubValuesStartsWith(), onContainerRestored(), Save(), and updateElementReference().
The documentation for this class was generated from the following files:
PropertyLinks.h
PropertyLinks.cpp