FreeCAD: TechDraw::BaseGeom Class Reference
TechDraw::BaseGeom Class Reference
#include <Geometry.h>
Public Member Functions
BaseGeom ()
virtual ~BaseGeom ()=default
virtual void Save (Base::Writer &w) const
virtual void Restore (Base::XMLReader &r)
std::vector< Base::Vector3d > findEndPoints ()
Base::Vector3d getStartPoint ()
Base::Vector3d getEndPoint ()
Base::Vector3d getMidPoint ()
std::vector< Base::Vector3d > getQuads ()
double minDist (Base::Vector3d p)
Base::Vector3d nearPoint (Base::Vector3d p)
Base::Vector3d nearPoint (const BaseGeomPtr p)
find point on me nearest to p
bool closed ()
virtual BaseGeomPtr copy ()
std::string dump ()
virtual std::string toString () const
std::vector< Base::Vector3d > intersection (TechDraw::BaseGeomPtr geom2)
boost::uuids::uuid getTag () const
virtual std::string getTagAsString () const
std::string geomTypeName ()
BaseGeomPtr inverted ()
GeomType getGeomType ()
void setGeomType (GeomType type)
edgeClass getClassOfEdge ()
void setClassOfEdge (edgeClass newClass)
bool getHlrVisible ()
void setHlrVisible (bool state)
bool getReversed ()
void setReversed (bool state)
int getRef3d ()
void setRef3d (int ref)
TopoDS_Edge getOCCEdge ()
void setOCCEdge (TopoDS_Edge newEdge)
bool getCosmetic ()
void setCosmetic (bool state)
int source ()
void source (int s)
int sourceIndex ()
void sourceIndex (int si)
std::string getCosmeticTag ()
void setCosmeticTag (std::string t)
Part::TopoShape asTopoShape (double scale=1.0)
virtual double getStartAngle ()
virtual double getEndAngle ()
virtual bool clockwiseAngle ()
virtual void clockwiseAngle (bool direction)
Static Public Member Functions
static BaseGeomPtr baseFactory (TopoDS_Edge edge, bool isCosmetic=false)
Convert 1 OCC edge into 1 BaseGeom (static factory method)
static bool validateEdge (TopoDS_Edge edge)
static TopoDS_Edge completeEdge (const TopoDS_Edge &edge)
Protected Member Functions
void createNewTag ()
Protected Attributes
GeomType geomType
ExtractionType extractType
edgeClass classOfEdge
bool hlrVisible
bool reversed
int ref3D
TopoDS_Edge occEdge
bool cosmetic
int m_source
int m_sourceIndex
std::string cosmeticTag
boost::uuids::uuid tag
Detailed Description
Definition at line 97 of file TechDraw/App/Geometry.h.
Constructor & Destructor Documentation
BaseGeom()
BaseGeom::BaseGeom ()
Definition at line 197 of file TechDraw/App/Geometry.cpp.
References cosmeticTag, occEdge, and tag.
~BaseGeom()
virtual TechDraw::BaseGeom::~BaseGeom () virtual default
Member Function Documentation
asTopoShape()
TopoShape BaseGeom::asTopoShape (double scale = 1.0)
Definition at line 644 of file TechDraw/App/Geometry.cpp.
References getOCCEdge(), and TechDraw::ShapeUtils::scaleShape().
baseFactory()
BaseGeomPtr BaseGeom::baseFactory (TopoDS_Edge edge, bool isCosmetic = false) static
Convert 1 OCC edge into 1 BaseGeom (static factory method)
Definition at line 484 of file TechDraw/App/Geometry.cpp.
References Base::Console(), SCL.SimpleDataTypes::e, SCL.SimpleDataTypes::f, Handle(), RobotExample::l, Base::ConsoleSingleton::Log(), Base::ConsoleSingleton::Message(), result, toolbit-attributes::s, and validateEdge().
Referenced by TechDraw::GeometryObject::addCosmeticEdge(), TechDraw::GeometryObject::addGeomFromCompound(), TechDraw::CenterLine::BaseGeomPtrFromVectors(), copy(), TechDraw::DrawGeomHatch::getFaceOverlay(), TechDraw::DrawGeomHatch::getTrimmedLines(), inverted(), TechDraw::CosmeticEdge::makeCanonicalLine(), TechDraw::CosmeticEdge::makeLineFromCanonicalPoints(), TechDraw::DrawComplexSection::makeSectionLineGeometry(), TechDraw::DrawViewSection::makeTDSectionFaces(), TechDraw::DrawViewPart::projectEdge(), TechDraw::CosmeticEdge::scaledAndRotatedGeometry(), TechDraw::CenterLine::scaledAndRotatedGeometry(), TechDraw::CosmeticEdge::scaledGeometry(), TechDraw::CenterLine::scaledGeometry(), TechDrawGui::TaskCosmeticLine::updateCosmeticLine(), and TechDraw::Wire::Wire().
clockwiseAngle() [1/2]
virtual bool TechDraw::BaseGeom::clockwiseAngle () inline virtual
Reimplemented in TechDraw::AOC, and TechDraw::AOE.
Definition at line 156 of file TechDraw/App/Geometry.h.
clockwiseAngle() [2/2]
virtual void TechDraw::BaseGeom::clockwiseAngle (bool direction) inline virtual
Reimplemented in TechDraw::AOC, and TechDraw::AOE.
Definition at line 157 of file TechDraw/App/Geometry.h.
closed()
bool BaseGeom::closed ()
Definition at line 438 of file TechDraw/App/Geometry.cpp.
References getEndPoint(), getStartPoint(), MovieTool::x, and MovieTool::y.
completeEdge()
TopoDS_Edge BaseGeom::completeEdge (const TopoDS_Edge & edge) static
Definition at line 582 of file TechDraw/App/Geometry.cpp.
References Base::Console(), SCL.SimpleDataTypes::e, and Base::ConsoleSingleton::Error().
Referenced by intersection().
copy()
BaseGeomPtr BaseGeom::copy () virtual
Reimplemented in TechDraw::AOC.
Definition at line 213 of file TechDraw/App/Geometry.cpp.
References baseFactory(), classOfEdge, cosmetic, cosmeticTag, extractType, hlrVisible, m_source, m_sourceIndex, occEdge, ref3D, result, and reversed.
Referenced by TechDraw::AOC::copy().
createNewTag()
void TechDraw::BaseGeom::createNewTag () protected
dump()
std::string BaseGeom::dump ()
Definition at line 427 of file TechDraw/App/Geometry.cpp.
References classOfEdge, cosmetic, geomType, getEndPoint(), getStartPoint(), hlrVisible, reversed, source(), and sourceIndex().
findEndPoints()
std::vector< Base::Vector3d > BaseGeom::findEndPoints ()
Definition at line 303 of file TechDraw/App/Geometry.cpp.
References Base::Console(), FirstVertex(), LastVertex(), Base::ConsoleSingleton::Message(), occEdge, buildPsets::p, and result.
Referenced by getEndPoint(), and getStartPoint().
geomTypeName()
std::string BaseGeom::geomTypeName ()
Definition at line 462 of file TechDraw/App/Geometry.cpp.
References geomType.
getClassOfEdge()
edgeClass TechDraw::BaseGeom::getClassOfEdge () inline
Definition at line 134 of file TechDraw/App/Geometry.h.
getCosmetic()
bool TechDraw::BaseGeom::getCosmetic () inline
Definition at line 144 of file TechDraw/App/Geometry.h.
getCosmeticTag()
std::string TechDraw::BaseGeom::getCosmeticTag () inline
Definition at line 150 of file TechDraw/App/Geometry.h.
getEndAngle()
virtual double TechDraw::BaseGeom::getEndAngle () inline virtual
Reimplemented in TechDraw::BSpline, TechDraw::AOC, and TechDraw::AOE.
Definition at line 155 of file TechDraw/App/Geometry.h.
getEndPoint()
Base::Vector3d BaseGeom::getEndPoint ()
Definition at line 335 of file TechDraw/App/Geometry.cpp.
References Base::Console(), findEndPoints(), and Base::ConsoleSingleton::Message().
Referenced by TechDraw::Generic::asVector(), closed(), and dump().
getGeomType()
GeomType TechDraw::BaseGeom::getGeomType () inline
Definition at line 132 of file TechDraw/App/Geometry.h.
References draftgeoutils.general::geomType().
getHlrVisible()
bool TechDraw::BaseGeom::getHlrVisible () inline
Definition at line 136 of file TechDraw/App/Geometry.h.
getMidPoint()
Base::Vector3d BaseGeom::getMidPoint ()
Definition at line 348 of file TechDraw/App/Geometry.cpp.
References FreeCADInit::Length, and occEdge.
getOCCEdge()
TopoDS_Edge TechDraw::BaseGeom::getOCCEdge () inline
Definition at line 142 of file TechDraw/App/Geometry.h.
Referenced by asTopoShape(), and intersection().
getQuads()
std::vector< Base::Vector3d > BaseGeom::getQuads ()
Definition at line 374 of file TechDraw/App/Geometry.cpp.
References occEdge, result, buildPsets::u, and TestSpreadsheet::v.
getRef3d()
int TechDraw::BaseGeom::getRef3d () inline
Definition at line 140 of file TechDraw/App/Geometry.h.
getReversed()
bool TechDraw::BaseGeom::getReversed () inline
Definition at line 138 of file TechDraw/App/Geometry.h.
getStartAngle()
virtual double TechDraw::BaseGeom::getStartAngle () inline virtual
Reimplemented in TechDraw::BSpline, TechDraw::AOC, and TechDraw::AOE.
Definition at line 154 of file TechDraw/App/Geometry.h.
getStartPoint()
Base::Vector3d BaseGeom::getStartPoint ()
Definition at line 321 of file TechDraw/App/Geometry.cpp.
References Base::Console(), findEndPoints(), and Base::ConsoleSingleton::Message().
Referenced by TechDraw::Generic::asVector(), closed(), and dump().
getTag()
boost::uuids::uuid BaseGeom::getTag () const
Definition at line 251 of file TechDraw/App/Geometry.cpp.
References tag.
Referenced by getTagAsString().
getTagAsString()
std::string BaseGeom::getTagAsString () const virtual
Reimplemented in TechDraw::CosmeticEdge.
Definition at line 256 of file TechDraw/App/Geometry.cpp.
References getTag().
intersection()
std::vector< Base::Vector3d > BaseGeom::intersection (TechDraw::BaseGeomPtr geom2)
Definition at line 608 of file TechDraw/App/Geometry.cpp.
References completeEdge(), EWTOLERANCE, importers.importIFClegacy::explorer(), FUZZYADJUST, getOCCEdge(), and TechDraw::DrawUtil::toVector3d().
inverted()
BaseGeomPtr BaseGeom::inverted ()
Definition at line 453 of file TechDraw/App/Geometry.cpp.
References baseFactory(), TechDraw::ShapeUtils::invertGeometry(), and occEdge.
minDist()
double BaseGeom::minDist (Base::Vector3d p)
Definition at line 396 of file TechDraw/App/Geometry.cpp.
References occEdge, buildPsets::p, TechDraw::DrawUtil::simpleMinDist(), and TestSpreadsheet::v.
Referenced by TechDraw::AOC::distToArc(), TechDraw::AOC::intersectsArc(), TechDraw::BSpline::intersectsArc(), and TechDraw::AOC::isOnArc().
nearPoint() [1/2]
Base::Vector3d BaseGeom::nearPoint (Base::Vector3d p)
Definition at line 415 of file TechDraw/App/Geometry.cpp.
References occEdge, buildPsets::p, and TestSpreadsheet::v.
nearPoint() [2/2]
Base::Vector3d BaseGeom::nearPoint (const BaseGeomPtr p)
find point on me nearest to p
Definition at line 404 of file TechDraw/App/Geometry.cpp.
References occEdge, and buildPsets::p.
Restore()
void BaseGeom::Restore (Base::XMLReader & r) virtual
Reimplemented in TechDraw::Generic, TechDraw::AOC, TechDraw::Circle, and TechDraw::CosmeticEdge.
Definition at line 279 of file TechDraw/App/Geometry.cpp.
References classOfEdge, cosmetic, cosmeticTag, extractType, geomType, hlrVisible, m_source, m_sourceIndex, TechDrawTools.TaskFillTemplateFields::reader, ref3D, and reversed.
Referenced by TechDraw::Generic::Restore().
Save()
void BaseGeom::Save (Base::Writer & w) const virtual
Reimplemented in TechDraw::Generic, TechDraw::AOC, TechDraw::Circle, and TechDraw::CosmeticEdge.
Definition at line 261 of file TechDraw/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, classOfEdge, cosmetic, cosmeticTag, extractType, geomType, hlrVisible, Base::Writer::ind(), m_source, m_sourceIndex, ref3D, reversed, Base::Writer::Stream(), and TestSpreadsheet::v.
Referenced by TechDraw::Circle::Save(), and TechDraw::Generic::Save().
setClassOfEdge()
void TechDraw::BaseGeom::setClassOfEdge (edgeClass newClass) inline
Definition at line 135 of file TechDraw/App/Geometry.h.
setCosmetic()
void TechDraw::BaseGeom::setCosmetic (bool state) inline
Definition at line 145 of file TechDraw/App/Geometry.h.
setCosmeticTag()
void TechDraw::BaseGeom::setCosmeticTag (std::string t) inline
Definition at line 151 of file TechDraw/App/Geometry.h.
References InitGui::t.
setGeomType()
void TechDraw::BaseGeom::setGeomType (GeomType type) inline
Definition at line 133 of file TechDraw/App/Geometry.h.
References draftgeoutils.general::geomType(), and Path.Post.scripts.grbl_post::type.
setHlrVisible()
void TechDraw::BaseGeom::setHlrVisible (bool state) inline
Definition at line 137 of file TechDraw/App/Geometry.h.
setOCCEdge()
void TechDraw::BaseGeom::setOCCEdge (TopoDS_Edge newEdge) inline
Definition at line 143 of file TechDraw/App/Geometry.h.
setRef3d()
void TechDraw::BaseGeom::setRef3d (int ref) inline
Definition at line 141 of file TechDraw/App/Geometry.h.
setReversed()
void TechDraw::BaseGeom::setReversed (bool state) inline
Definition at line 139 of file TechDraw/App/Geometry.h.
source() [1/2]
int TechDraw::BaseGeom::source () inline
Definition at line 146 of file TechDraw/App/Geometry.h.
Referenced by dump().
source() [2/2]
void TechDraw::BaseGeom::source (int s) inline
Definition at line 147 of file TechDraw/App/Geometry.h.
References toolbit-attributes::s.
sourceIndex() [1/2]
int TechDraw::BaseGeom::sourceIndex () inline
Definition at line 148 of file TechDraw/App/Geometry.h.
Referenced by dump().
sourceIndex() [2/2]
void TechDraw::BaseGeom::sourceIndex (int si) inline
Definition at line 149 of file TechDraw/App/Geometry.h.
toString()
std::string BaseGeom::toString () const virtual
Reimplemented in TechDraw::Generic, TechDraw::AOC, TechDraw::Circle, and TechDraw::CosmeticEdge.
Definition at line 236 of file TechDraw/App/Geometry.cpp.
References classOfEdge, cosmetic, extractType, geomType, hlrVisible, m_source, m_sourceIndex, ref3D, and reversed.
Referenced by TechDraw::Circle::toString(), and TechDraw::Generic::toString().
validateEdge()
bool BaseGeom::validateEdge (TopoDS_Edge edge) static
Definition at line 577 of file TechDraw/App/Geometry.cpp.
References TechDraw::DrawUtil::isCrazy().
Referenced by baseFactory().
Member Data Documentation
classOfEdge
edgeClass TechDraw::BaseGeom::classOfEdge protected
Definition at line 164 of file TechDraw/App/Geometry.h.
Referenced by copy(), dump(), Restore(), Save(), and toString().
cosmetic
bool TechDraw::BaseGeom::cosmetic protected
Definition at line 169 of file TechDraw/App/Geometry.h.
Referenced by copy(), dump(), Restore(), Save(), and toString().
cosmeticTag
std::string TechDraw::BaseGeom::cosmeticTag protected
Definition at line 173 of file TechDraw/App/Geometry.h.
Referenced by BaseGeom(), copy(), Restore(), and Save().
extractType
ExtractionType TechDraw::BaseGeom::extractType protected
Definition at line 163 of file TechDraw/App/Geometry.h.
Referenced by copy(), Restore(), Save(), and toString().
geomType
GeomType TechDraw::BaseGeom::geomType protected
Definition at line 162 of file TechDraw/App/Geometry.h.
Referenced by TechDraw::AOC::AOC(), TechDraw::AOE::AOE(), TechDraw::BezierSegment::BezierSegment(), TechDraw::BSpline::BSpline(), TechDraw::Circle::Circle(), dump(), TechDraw::Ellipse::Ellipse(), TechDraw::Generic::Generic(), geomTypeName(), Restore(), Save(), and toString().
hlrVisible
bool TechDraw::BaseGeom::hlrVisible protected
Definition at line 165 of file TechDraw/App/Geometry.h.
Referenced by copy(), dump(), Restore(), Save(), and toString().
m_source
int TechDraw::BaseGeom::m_source protected
Definition at line 171 of file TechDraw/App/Geometry.h.
Referenced by copy(), Restore(), Save(), and toString().
m_sourceIndex
int TechDraw::BaseGeom::m_sourceIndex protected
Definition at line 172 of file TechDraw/App/Geometry.h.
Referenced by copy(), Restore(), Save(), and toString().
occEdge
TopoDS_Edge TechDraw::BaseGeom::occEdge protected
Definition at line 168 of file TechDraw/App/Geometry.h.
Referenced by TechDraw::AOC::AOC(), TechDraw::BSpline::asCircle(), BaseGeom(), TechDraw::BezierSegment::BezierSegment(), TechDraw::BSpline::BSpline(), TechDraw::Circle::Circle(), copy(), TechDraw::Ellipse::Ellipse(), findEndPoints(), TechDraw::Generic::Generic(), getMidPoint(), getQuads(), TechDraw::AOC::intersectsArc(), TechDraw::BSpline::intersectsArc(), inverted(), TechDraw::BSpline::isCircle(), TechDraw::BSpline::isLine(), TechDraw::AOC::isOnArc(), minDist(), and nearPoint().
ref3D
int TechDraw::BaseGeom::ref3D protected
Definition at line 167 of file TechDraw/App/Geometry.h.
Referenced by copy(), Restore(), Save(), and toString().
reversed
bool TechDraw::BaseGeom::reversed protected
Definition at line 166 of file TechDraw/App/Geometry.h.
Referenced by TechDraw::AOC::AOC(), TechDraw::AOE::AOE(), TechDraw::BezierSegment::BezierSegment(), TechDraw::BSpline::BSpline(), copy(), dump(), TechDraw::Generic::Generic(), Restore(), Save(), and toString().
tag
boost::uuids::uuid TechDraw::BaseGeom::tag protected
Definition at line 174 of file TechDraw/App/Geometry.h.
Referenced by BaseGeom(), Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.ChunkBase::dump_header(), and getTag().
The documentation for this class was generated from the following files:
TechDraw/App/Geometry.h
TechDraw/App/Geometry.cpp