FreeCAD: Gui::MergeDocuments Class Reference
Gui::MergeDocuments Class Reference
#include <MergeDocuments.h>
Public Member Functions
MergeDocuments (App::Document *doc)
~MergeDocuments () override
unsigned int getMemSize () const override
std::vector< App::DocumentObject * > importObjects (std::istream &)
void importObject (const std::vector< App::DocumentObject * > &o, Base::XMLReader &r)
void exportObject (const std::vector< App::DocumentObject * > &o, Base::Writer &w)
void Save (Base::Writer &w) const override
void Restore (Base::XMLReader &r) override
void SaveDocFile (Base::Writer &w) const override
void RestoreDocFile (Base::Reader &r) override
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 42 of file Gui/MergeDocuments.h.
Constructor & Destructor Documentation
MergeDocuments()
MergeDocuments::MergeDocuments (App::Document * doc) explicit
Definition at line 77 of file Gui/MergeDocuments.cpp.
References draftgeoutils.faces::bind(), toolbit-attributes::doc, exportObject(), Gui::Application::getDocument(), importObject(), and Gui::Application::Instance.
~MergeDocuments()
MergeDocuments::~MergeDocuments () override
Definition at line 88 of file Gui/MergeDocuments.cpp.
Member Function Documentation
exportObject()
void MergeDocuments::exportObject (const std::vector< App::DocumentObject * > & o, Base::Writer & w)
Definition at line 125 of file Gui/MergeDocuments.cpp.
References src.Mod.Test.testPathArray::o, Save(), and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by MergeDocuments().
getMemSize()
unsigned int MergeDocuments::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
Definition at line 94 of file Gui/MergeDocuments.cpp.
importObject()
void MergeDocuments::importObject (const std::vector< App::DocumentObject * > & o, Base::XMLReader & r)
Definition at line 113 of file Gui/MergeDocuments.cpp.
References Gui::Document::getViewProvider(), Gui::ViewProvider::hide(), src.Mod.Test.testPathArray::o, Base::XMLReader::readFiles(), and Restore().
Referenced by MergeDocuments().
importObjects()
std::vector< App::DocumentObject * > MergeDocuments::importObjects (std::istream & input)
Definition at line 100 of file Gui/MergeDocuments.cpp.
References App::Document::importObjects(), replaceobj::objs, and TechDrawTools.TaskFillTemplateFields::reader.
Referenced by StdCmdMergeProjects::activated(), StdCmdDuplicateSelection::activated(), and Gui::MainWindow::insertFromMimeData().
Restore()
void MergeDocuments::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 136 of file Gui/MergeDocuments.cpp.
References Base::XMLReader::addFile().
Referenced by importObject().
RestoreDocFile()
void MergeDocuments::RestoreDocFile (Base::Reader &) override virtual
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data. Again you have to apply for the call of this method in the Restore() call:
void PropertyMeshKernel::Restore(Base::XMLReader &reader)
{
  reader.readElement("Mesh");
  std::string file (reader.getAttribute("file") );
  if(file == "")
  {
    // read XML
    MeshCore::MeshDocXML restorer(*_pcMesh);
    restorer.Restore(reader);
  }else{
    // initiate a file read
    reader.addFile(file.c_str(),this);
 }
}
After you issued the reader.addFile() your RestoreDocFile() is called:
void PropertyMeshKernel::RestoreDocFile(Base::Reader &reader)
{
    _pcMesh->Read( reader );
}
See also
Base::Reader,Base::XMLReader
Reimplemented from Base::Persistence.
Definition at line 146 of file Gui/MergeDocuments.cpp.
References Gui::Document::importObjects().
Save()
void MergeDocuments::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 131 of file Gui/MergeDocuments.cpp.
References src.Mod.PartDesign.fcgear.svggear::w.
Referenced by exportObject().
SaveDocFile()
void MergeDocuments::SaveDocFile (Base::Writer &) const override virtual
This method is used to save large amounts of data to a binary file. Sometimes it makes no sense to write property data as XML. In case the amount of data is too big or the data type has a more effective way to save itself. In this cases it is possible to write the data in a separate file inside the document archive. In case you want do so you have to re-implement SaveDocFile(). First, you have to inform the framework in Save() that you want do so. Here an example from the Mesh module which can save a (pontetionaly big) triangle mesh:
void PropertyMeshKernel::Save (Base::Writer &writer) const
{
  if (writer.isForceXML())
  {
    writer << writer.ind() << "<Mesh>" << std::endl;
    MeshCore::MeshDocXML saver(*_pcMesh);
    saver.Save(writer);
  }else{
   writer << writer.ind() << "<Mesh file=\"" << writer.addFile("MeshKernel.bms", this) <<
"\"/>" << std::endl;
}
The writer.isForceXML() is an indication to force you to write XML. Regardless of size and effectiveness. The second part informs the Base::writer through writer.addFile("MeshKernel.bms", this) that this object wants to write a file with the given name. The method addFile() returns a unique name that then is written in the XML stream. This allows your RestoreDocFile() method to identify and read the file again. Later your SaveDocFile() method is called as many times as you issued the addFile() call:
 void
PropertyMeshKernel::SaveDocFile (Base::Writer &writer) const
{
    _pcMesh->Write( writer );
}
In this method you can simply stream your content to the file (Base::Writer inheriting from ostream).
Reimplemented from Base::Persistence.
Definition at line 141 of file Gui/MergeDocuments.cpp.
References Gui::Document::exportObjects(), and src.Mod.PartDesign.fcgear.svggear::w.
The documentation for this class was generated from the following files:
Gui/MergeDocuments.h
Gui/MergeDocuments.cpp