FreeCAD: ModelRefine::FaceTypedBase Class Reference
ModelRefine::FaceTypedBase Class Reference abstract
#include <modelRefine.h>
Public Member Functions
virtual bool isEqual (const TopoDS_Face &faceOne, const TopoDS_Face &faceTwo) const =0
virtual GeomAbs_SurfaceType getType () const =0
virtual TopoDS_Face buildFace (const FaceVectorType &faces) const =0
Static Public Member Functions
static GeomAbs_SurfaceType getFaceType (const TopoDS_Face &faceIn)
Protected Member Functions
FaceTypedBase (const GeomAbs_SurfaceType &typeIn)
virtual void boundarySplit (const FaceVectorType &facesIn, std::vector< EdgeVectorType > &boundariesOut) const
Protected Attributes
GeomAbs_SurfaceType surfaceType
Detailed Description
Definition at line 76 of file modelRefine.h.
Constructor & Destructor Documentation
FaceTypedBase()
ModelRefine::FaceTypedBase::FaceTypedBase (const GeomAbs_SurfaceType & typeIn) inline protected
Definition at line 81 of file modelRefine.h.
Member Function Documentation
boundarySplit()
void FaceTypedBase::boundarySplit (const FaceVectorType & facesIn, std::vector< EdgeVectorType > & boundariesOut) const protected virtual
Reimplemented in ModelRefine::FaceTypedCylinder.
Definition at line 300 of file modelRefine.cpp.
References ModelRefine::boundaryEdges(), FirstVertex(), and LastVertex().
Referenced by ModelRefine::FaceTypedPlane::buildFace(), and ModelRefine::FaceTypedBSpline::buildFace().
buildFace()
virtual TopoDS_Face ModelRefine::FaceTypedBase::buildFace (const FaceVectorType & faces) const pure virtual
Implemented in ModelRefine::FaceTypedBSpline, ModelRefine::FaceTypedCylinder, and ModelRefine::FaceTypedPlane.
getFaceType()
GeomAbs_SurfaceType FaceTypedBase::getFaceType (const TopoDS_Face & faceIn) static
Definition at line 293 of file modelRefine.cpp.
References Handle().
Referenced by ModelRefine::FaceTypeSplitter::split().
getType()
virtual GeomAbs_SurfaceType ModelRefine::FaceTypedBase::getType () const pure virtual
Implemented in ModelRefine::FaceTypedBSpline, ModelRefine::FaceTypedCylinder, and ModelRefine::FaceTypedPlane.
isEqual()
virtual bool ModelRefine::FaceTypedBase::isEqual (const TopoDS_Face & faceOne, const TopoDS_Face & faceTwo) const pure virtual
Implemented in ModelRefine::FaceTypedBSpline, ModelRefine::FaceTypedCylinder, and ModelRefine::FaceTypedPlane.
Referenced by ModelRefine::FaceEqualitySplitter::split().
Member Data Documentation
surfaceType
GeomAbs_SurfaceType ModelRefine::FaceTypedBase::surfaceType protected
Definition at line 91 of file modelRefine.h.
The documentation for this class was generated from the following files:
modelRefine.h
modelRefine.cpp