FreeCAD: SketcherGui::GeometryLayerParameters Class Reference
SketcherGui::GeometryLayerParameters Class Reference
Helper class to store geometry layers configuration.
#include <EditModeCoinManagerParameters.h>
Public Types
enum SubLayer { SubLayer::Normal = 0, SubLayer::Construction = 1, SubLayer::Internal = 2, SubLayer::External = 3 }
Public Member Functions
GeometryLayerParameters ()
void reset ()
int getSafeCoinLayer (int coinlayer)
int getCoinLayerCount () const
void setCoinLayerCount (int layernumber)
int getSubLayerCount () const
int getSubLayerIndex (const int geoId, const Sketcher::GeometryFacade *geom) const
bool isNormalSubLayer (int t) const
bool isConstructionSubLayer (int t) const
bool isInternalSubLayer (int t) const
bool isExternalSubLayer (int t) const
Detailed Description
Helper class to store geometry layers configuration.
CoinLayers is the number of * Coin * Geometry Layers. This is not necessarily the number of Geometry layers (logical layers).
Logical layers (as stored in GeometryFacade) define a grouping of geometries. However, this does not mean that they are represented in coin in different layers. Only when there is a reason for such mapping is done so. For example, when the geometry have different drawing parameters.
This means that there may be:
A N:N relationship between logical layers and coin layers.
A M:N relationship between logical layers and coin layers (M<N), including a 1:N relationship.
Definition at line 253 of file EditModeCoinManagerParameters.h.
Member Enumeration Documentation
SubLayer
enum SketcherGui::GeometryLayerParameters::SubLayer strong
Enumerator
Normal
Construction
Internal
External
Definition at line 270 of file EditModeCoinManagerParameters.h.
Constructor & Destructor Documentation
GeometryLayerParameters()
SketcherGui::GeometryLayerParameters::GeometryLayerParameters () inline
Definition at line 257 of file EditModeCoinManagerParameters.h.
References reset().
Member Function Documentation
getCoinLayerCount()
int SketcherGui::GeometryLayerParameters::getCoinLayerCount () const inline
Definition at line 292 of file EditModeCoinManagerParameters.h.
Referenced by SketcherGui::EditModeGeometryCoinConverter::convert(), SketcherGui::EditModeCoinManager::detectPreselection(), SketcherGui::EditModeGeometryCoinManager::processGeometry(), SketcherGui::EditModeConstraintCoinManager::updateConstraintColor(), and SketcherGui::EditModeGeometryCoinManager::updateGeometryColor().
getSafeCoinLayer()
int SketcherGui::GeometryLayerParameters::getSafeCoinLayer (int coinlayer) inline
Definition at line 283 of file EditModeCoinManagerParameters.h.
Referenced by SketcherGui::EditModeGeometryCoinConverter::convert().
getSubLayerCount()
int SketcherGui::GeometryLayerParameters::getSubLayerCount () const inline
Definition at line 302 of file EditModeCoinManagerParameters.h.
Referenced by SketcherGui::EditModeGeometryCoinConverter::convert(), SketcherGui::EditModeCoinManager::detectPreselection(), SketcherGui::EditModeGeometryCoinManager::processGeometry(), SketcherGui::EditModeConstraintCoinManager::updateConstraintColor(), and SketcherGui::EditModeGeometryCoinManager::updateGeometryColor().
getSubLayerIndex()
int GeometryLayerParameters::getSubLayerIndex (const int geoId, const Sketcher::GeometryFacade * geom) const
Definition at line 32 of file EditModeCoinManagerParameters.cpp.
References Sketcher::GeometryFacade::clone(), Construction, Sketcher::ExternalGeometryExtension::Defining, External, Sketcher::GeometryFacade::getConstruction(), Sketcher::ExternalGeometryFacade::getFacade(), Internal, Sketcher::GeometryFacade::isInternalAligned(), Normal, and Sketcher::RefExt.
Referenced by SketcherGui::EditModeGeometryCoinConverter::convert().
isConstructionSubLayer()
bool SketcherGui::GeometryLayerParameters::isConstructionSubLayer (int t) const inline
Definition at line 314 of file EditModeCoinManagerParameters.h.
References Construction, and InitGui::t.
Referenced by SketcherGui::EditModeGeometryCoinManager::updateGeometryColor().
isExternalSubLayer()
bool SketcherGui::GeometryLayerParameters::isExternalSubLayer (int t) const inline
Definition at line 324 of file EditModeCoinManagerParameters.h.
References External, and InitGui::t.
isInternalSubLayer()
bool SketcherGui::GeometryLayerParameters::isInternalSubLayer (int t) const inline
Definition at line 319 of file EditModeCoinManagerParameters.h.
References Internal, and InitGui::t.
Referenced by SketcherGui::EditModeGeometryCoinManager::updateGeometryColor().
isNormalSubLayer()
bool SketcherGui::GeometryLayerParameters::isNormalSubLayer (int t) const inline
Definition at line 309 of file EditModeCoinManagerParameters.h.
References Normal, and InitGui::t.
reset()
void SketcherGui::GeometryLayerParameters::reset () inline
Definition at line 278 of file EditModeCoinManagerParameters.h.
Referenced by GeometryLayerParameters().
setCoinLayerCount()
void SketcherGui::GeometryLayerParameters::setCoinLayerCount (int layernumber) inline
Definition at line 297 of file EditModeCoinManagerParameters.h.
Referenced by SketcherGui::EditModeGeometryCoinManager::createEditModeInventorNodes(), and SketcherGui::EditModeGeometryCoinManager::updateGeometryLayersConfiguration().
The documentation for this class was generated from the following files:
EditModeCoinManagerParameters.h
EditModeCoinManagerParameters.cpp