FreeCAD: PartGui::TaskExportStep Class Reference
PartGui::TaskExportStep Class Reference
#include <DlgExportStep.h>
Public Member Functions
TaskExportStep (QWidget *parent=nullptr)
~TaskExportStep () override
bool showDialog () const
void accept () override
StepSettings getSettings () const
Detailed Description
Definition at line 89 of file DlgExportStep.h.
Constructor & Destructor Documentation
TaskExportStep()
TaskExportStep::TaskExportStep (QWidget * parent = nullptr) explicit
Definition at line 194 of file DlgExportStep.cpp.
References accept(), and draftgeoutils.intersections::connect().
~TaskExportStep()
TaskExportStep::~TaskExportStep () override
Definition at line 219 of file DlgExportStep.cpp.
Member Function Documentation
accept()
void TaskExportStep::accept () override
Definition at line 224 of file DlgExportStep.cpp.
References Part::STEP::ImportExportSettings::setVisibleExportDialog().
Referenced by TaskExportStep().
getSettings()
StepSettings TaskExportStep::getSettings () const
Definition at line 239 of file DlgExportStep.cpp.
showDialog()
bool TaskExportStep::showDialog () const
Definition at line 233 of file DlgExportStep.cpp.
References Part::STEP::ImportExportSettings::isVisibleExportDialog().
The documentation for this class was generated from the following files:
DlgExportStep.h
DlgExportStep.cpp