FreeCAD: ifc2x3.ifcsite Class Reference
ifc2x3.ifcsite Class Reference
Public Member Functions
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__objecttype, inherited5__objectplacement, inherited6__representation, inherited7__longname, inherited8__compositiontype, reflatitude, reflongitude, refelevation, landtitlenumber, siteaddress)
def reflatitude ()
def reflongitude ()
def refelevation ()
def landtitlenumber ()
def siteaddress ()
Public Member Functions inherited from ifc2x3.ifcspatialstructureelement
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__objecttype, inherited5__objectplacement, inherited6__representation, longname, compositiontype)
def longname ()
def compositiontype ()
def referenceselements ()
def servicedbysystems ()
def containselements ()
def wr41 (self)
Public Member Functions inherited from ifc2x3.ifcproduct
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__objecttype, objectplacement, representation)
def objectplacement ()
def representation ()
def referencedby ()
def wr1 (self)
Public Member Functions inherited from ifc2x3.ifcobject
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, objecttype)
def objecttype ()
def isdefinedby ()
Public Member Functions inherited from ifc2x3.ifcobjectdefinition
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description)
def hasassignments ()
def isdecomposedby ()
def decomposes ()
def hasassociations ()
Public Member Functions inherited from ifc2x3.ifcroot
def globalid ()
def ownerhistory ()
def name ()
def description ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
reflatitude
reflongitude
refelevation
landtitlenumber
siteaddress
Public Attributes inherited from ifc2x3.ifcspatialstructureelement
longname
compositiontype
Public Attributes inherited from ifc2x3.ifcproduct
objectplacement
representation
Public Attributes inherited from ifc2x3.ifcobject
objecttype
Public Attributes inherited from ifc2x3.ifcroot
globalid
ownerhistory
name
description
Detailed Description
Entity ifcsite definition.
:param reflatitude
:type reflatitude:LIST(3,4,'INTEGER', scope = schema_scope)
:param reflongitude
:type reflongitude:LIST(3,4,'INTEGER', scope = schema_scope)
:param refelevation
:type refelevation:ifclengthmeasure
:param landtitlenumber
:type landtitlenumber:ifclabel
:param siteaddress
:type siteaddress:ifcpostaladdress
Definition at line 25150 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcsite.__init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__objecttype, inherited5__objectplacement, inherited6__representation, inherited7__longname, inherited8__compositiontype, reflatitude, reflongitude, refelevation, landtitlenumber, siteaddress)
Definition at line 25168 of file ifc2x3.py.
Member Function Documentation
landtitlenumber()
def ifc2x3.ifcsite.landtitlenumber ()
Definition at line 25219 of file ifc2x3.py.
References ifc2x3.ifcsite._landtitlenumber, SCL.TypeChecker.check_type(), and ifc2x3.ifcsite.landtitlenumber.
refelevation()
def ifc2x3.ifcsite.refelevation ()
Definition at line 25205 of file ifc2x3.py.
References ifc2x3.ifcsite._refelevation, SCL.TypeChecker.check_type(), and ifc2x3.ifcsite.refelevation.
reflatitude()
def ifc2x3.ifcsite.reflatitude ()
Definition at line 25177 of file ifc2x3.py.
References ifc2x3.ifcsite._reflatitude, SCL.TypeChecker.check_type(), and ifc2x3.ifcsite.reflatitude.
reflongitude()
def ifc2x3.ifcsite.reflongitude ()
Definition at line 25191 of file ifc2x3.py.
References ifc2x3.ifcsite._reflongitude, SCL.TypeChecker.check_type(), and ifc2x3.ifcsite.reflongitude.
siteaddress()
def ifc2x3.ifcsite.siteaddress ()
Definition at line 25233 of file ifc2x3.py.
References ifc2x3.ifcsite._siteaddress, SCL.TypeChecker.check_type(), and ifc2x3.ifcsite.siteaddress.
Member Data Documentation
landtitlenumber
ifc2x3.ifcsite.landtitlenumber
Definition at line 25173 of file ifc2x3.py.
Referenced by ifc2x3.ifcsite.landtitlenumber().
refelevation
ifc2x3.ifcsite.refelevation
Definition at line 25172 of file ifc2x3.py.
Referenced by ifc2x3.ifcsite.refelevation().
reflatitude
ifc2x3.ifcsite.reflatitude
Definition at line 25170 of file ifc2x3.py.
Referenced by ifc2x3.ifcsite.reflatitude().
reflongitude
ifc2x3.ifcsite.reflongitude
Definition at line 25171 of file ifc2x3.py.
Referenced by ifc2x3.ifcsite.reflongitude().
siteaddress
ifc2x3.ifcsite.siteaddress
Definition at line 25174 of file ifc2x3.py.
Referenced by ifc2x3.ifcsite.siteaddress().
The documentation for this class was generated from the following file:
ifc2x3.py