FreeCAD: ifc2x3.ifcdocumentinformationrelationship Class Reference
ifc2x3.ifcdocumentinformationrelationship Class Reference
Public Member Functions
def __init__ (self, relatingdocument, relateddocuments, relationshiptype)
def relatingdocument ()
def relateddocuments ()
def relationshiptype ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
relatingdocument
relateddocuments
relationshiptype
Detailed Description
Entity ifcdocumentinformationrelationship definition.
:param relatingdocument
:type relatingdocument:ifcdocumentinformation
:param relateddocuments
:type relateddocuments:SET(1,None,'ifcdocumentinformation', scope = schema_scope)
:param relationshiptype
:type relationshiptype:ifclabel
Definition at line 26621 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcdocumentinformationrelationship.__init__ (self, relatingdocument, relateddocuments, relationshiptype)
Definition at line 26633 of file ifc2x3.py.
Member Function Documentation
relateddocuments()
def ifc2x3.ifcdocumentinformationrelationship.relateddocuments ()
Definition at line 26653 of file ifc2x3.py.
References ifc2x3.ifcdocumentinformationrelationship._relateddocuments, SCL.TypeChecker.check_type(), and ifc2x3.ifcdocumentinformationrelationship.relateddocuments.
relatingdocument()
def ifc2x3.ifcdocumentinformationrelationship.relatingdocument ()
Definition at line 26639 of file ifc2x3.py.
References ifc2x3.ifcdocumentinformationrelationship._relatingdocument, SCL.TypeChecker.check_type(), and ifc2x3.ifcdocumentinformationrelationship.relatingdocument.
relationshiptype()
def ifc2x3.ifcdocumentinformationrelationship.relationshiptype ()
Definition at line 26667 of file ifc2x3.py.
References ifc2x3.ifcdocumentinformationrelationship._relationshiptype, SCL.TypeChecker.check_type(), and ifc2x3.ifcdocumentinformationrelationship.relationshiptype.
Member Data Documentation
relateddocuments
ifc2x3.ifcdocumentinformationrelationship.relateddocuments
Definition at line 26635 of file ifc2x3.py.
Referenced by ifc2x3.ifcdocumentinformationrelationship.relateddocuments().
relatingdocument
ifc2x3.ifcdocumentinformationrelationship.relatingdocument
Definition at line 26634 of file ifc2x3.py.
Referenced by ifc2x3.ifcdocumentinformationrelationship.relatingdocument().
relationshiptype
ifc2x3.ifcdocumentinformationrelationship.relationshiptype
Definition at line 26636 of file ifc2x3.py.
Referenced by ifc2x3.ifcdocumentinformationrelationship.relationshiptype().
The documentation for this class was generated from the following file:
ifc2x3.py