FreeCAD: TechDrawGui::QGISectionLine Class Reference
TechDrawGui::QGISectionLine Class Reference
#include <QGISectionLine.h>
Public Types
enum { Type = QGraphicsItem::UserType + 172 }
Public Types inherited from TechDrawGui::QGIDecoration
enum { Type = QGraphicsItem::UserType + 173 }
Public Member Functions
QGISectionLine ()
~QGISectionLine () override=default
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
void setEnds (Base::Vector3d l1, Base::Vector3d l2)
void setBounds (double x1, double y1, double x2, double y2)
void setPath (QPainterPath &path)
void setSymbol (char *sym)
void setDirection (double xDir, double yDir)
void setDirection (Base::Vector3d dir)
void setArrowDirections (Base::Vector3d dir1, Base::Vector3d dir2)
void setFont (QFont f, double fsize)
void setSectionColor (QColor c)
void setPathMode (bool mode)
void setShowLine (bool state)
bool pathMode ()
void setChangePoints (TechDraw::ChangePointVector changePoints)
void clearChangePoints ()
void draw () override
void setLinePen (QPen isoPen)
Public Member Functions inherited from TechDrawGui::QGIDecoration
QGIDecoration ()
~QGIDecoration () override=default
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual void onDragFinished ()
void setWidth (double w)
double getWidth ()
void setStyle (Qt::PenStyle s)
void setColor (QColor c)
QColor getColor ()
void setFill (Qt::BrushStyle bs)
void makeMark (double x, double y)
void makeMark (Base::Vector3d v)
Protected Member Functions
QColor getSectionColor ()
Qt::PenStyle getSectionStyle ()
void makeSectionLine ()
void makeExtensionLine ()
void makeArrows ()
void makeArrowsTrad ()
void makeArrowsISO ()
void makeSymbols ()
void makeSymbolsTrad ()
void makeSymbolsISO ()
void makeChangePointMarks ()
void setTools ()
void extensionEndsISO ()
void extensionEndsTrad ()
double getArrowRotation (Base::Vector3d arrowDir)
QPointF getArrowPosition (Base::Vector3d arrowDir, QPointF refPoint)
void clearChangePointMarks ()
Protected Member Functions inherited from TechDrawGui::QGIDecoration
void setPrettyNormal ()
void setPrettyPre ()
void setPrettySel ()
virtual QColor prefNormalColor ()
virtual QColor prefPreColor ()
virtual QColor prefSelectColor ()
Static Protected Member Functions
static QPointF normalizeQPointF (QPointF inPoint)
Additional Inherited Members
Protected Attributes inherited from TechDrawGui::QGIDecoration
QPen m_pen
QBrush m_brush
QColor m_colCurrent
QColor m_colNormal
double m_width
Qt::PenStyle m_styleCurrent
Qt::BrushStyle m_brushCurrent
int m_dragState
Detailed Description
Definition at line 66 of file QGISectionLine.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 72 of file QGISectionLine.h.
Constructor & Destructor Documentation
QGISectionLine()
QGISectionLine::QGISectionLine () explicit
Definition at line 53 of file QGISectionLine.cpp.
References TechDrawGui::QGIArrow::getPrefArrowSize(), getSectionColor(), TechDrawGui::Rez::guiX(), TechDrawGui::QGIDecoration::setColor(), and TechDrawGui::QGIDecoration::setWidth().
~QGISectionLine()
TechDrawGui::QGISectionLine::~QGISectionLine () override default
Member Function Documentation
clearChangePointMarks()
void QGISectionLine::clearChangePointMarks () protected
Definition at line 445 of file QGISectionLine.cpp.
Referenced by clearChangePoints(), and setChangePoints().
clearChangePoints()
void QGISectionLine::clearChangePoints ()
Definition at line 439 of file QGISectionLine.cpp.
References clearChangePointMarks().
Referenced by TechDrawGui::QGIViewPart::drawComplexSectionLine(), and TechDrawGui::QGIViewPart::drawSectionLine().
draw()
void QGISectionLine::draw () override virtual
Reimplemented from TechDrawGui::QGIDecoration.
Definition at line 81 of file QGISectionLine.cpp.
References ANSISTANDARD, extensionEndsISO(), extensionEndsTrad(), makeArrows(), makeChangePointMarks(), makeExtensionLine(), makeSectionLine(), makeSymbols(), and pathMode().
Referenced by TechDrawGui::QGIViewPart::drawComplexSectionLine(), and TechDrawGui::QGIViewPart::drawSectionLine().
extensionEndsISO()
void QGISectionLine::extensionEndsISO () protected
Definition at line 289 of file QGISectionLine.cpp.
References TechDrawGui::QGIArrow::getPrefArrowSize(), TechDrawGui::Rez::guiX(), normalizeQPointF(), SINGLEDIRECTIONMODE, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by draw().
extensionEndsTrad()
void QGISectionLine::extensionEndsTrad () protected
Definition at line 267 of file QGISectionLine.cpp.
References getArrowPosition(), normalizeQPointF(), SINGLEDIRECTIONMODE, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by draw().
getArrowPosition()
QPointF QGISectionLine::getArrowPosition (Base::Vector3d arrowDir, QPointF refPoint) protected
Definition at line 411 of file QGISectionLine.cpp.
References TechDrawGui::QGIArrow::getPrefArrowSize(), TechDrawGui::Rez::guiX(), normalizeQPointF(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by extensionEndsTrad(), and makeArrowsTrad().
getArrowRotation()
double QGISectionLine::getArrowRotation (Base::Vector3d arrowDir) protected
Definition at line 400 of file QGISectionLine.cpp.
References M_PI, Base::Vector3< float_type >::Normalize(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by makeArrowsISO(), and makeArrowsTrad().
getSectionColor()
QColor QGISectionLine::getSectionColor () protected
Definition at line 471 of file QGISectionLine.cpp.
References TechDrawGui::QGIDecoration::getColor().
Referenced by makeChangePointMarks(), makeExtensionLine(), and QGISectionLine().
getSectionStyle()
Qt::PenStyle TechDrawGui::QGISectionLine::getSectionStyle () protected
makeArrows()
void QGISectionLine::makeArrows () protected
Definition at line 131 of file QGISectionLine.cpp.
References ANSISTANDARD, makeArrowsISO(), and makeArrowsTrad().
Referenced by draw().
makeArrowsISO()
void QGISectionLine::makeArrowsISO () protected
Definition at line 142 of file QGISectionLine.cpp.
References TechDrawGui::QGIArrow::draw(), getArrowRotation(), TechDrawGui::QGIArrow::getPrefArrowSize(), TechDrawGui::QGIArrow::setSize(), TechDrawGui::QGIArrow::setStyle(), and SINGLEDIRECTIONMODE.
Referenced by makeArrows().
makeArrowsTrad()
void QGISectionLine::makeArrowsTrad () protected
Definition at line 166 of file QGISectionLine.cpp.
References TechDrawGui::QGIArrow::draw(), getArrowPosition(), getArrowRotation(), TechDrawGui::QGIArrow::getPrefArrowSize(), TechDrawGui::QGIArrow::setSize(), TechDrawGui::QGIArrow::setStyle(), and SINGLEDIRECTIONMODE.
Referenced by makeArrows().
makeChangePointMarks()
void QGISectionLine::makeChangePointMarks () protected
Definition at line 321 of file QGISectionLine.cpp.
References TechDrawGui::QGIArrow::getPrefArrowSize(), getSectionColor(), TechDrawGui::QGIDecoration::getWidth(), TechDrawGui::Rez::guiPt(), and ZVALUE::SECTIONLINE.
Referenced by draw().
makeExtensionLine()
void QGISectionLine::makeExtensionLine () protected
Definition at line 101 of file QGISectionLine.cpp.
References getSectionColor(), and TechDrawGui::QGIDecoration::getWidth().
Referenced by draw().
makeSectionLine()
void QGISectionLine::makeSectionLine () protected
Definition at line 121 of file QGISectionLine.cpp.
Referenced by draw().
makeSymbols()
void QGISectionLine::makeSymbols () protected
Definition at line 196 of file QGISectionLine.cpp.
References ANSISTANDARD, makeSymbolsISO(), and makeSymbolsTrad().
Referenced by draw().
makeSymbolsISO()
void QGISectionLine::makeSymbolsISO () protected
Definition at line 237 of file QGISectionLine.cpp.
References TechDrawGui::QGCustomText::centerAt(), TechDrawGui::QGIView::exactFontSize(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by makeSymbols().
makeSymbolsTrad()
void QGISectionLine::makeSymbolsTrad () protected
Definition at line 207 of file QGISectionLine.cpp.
References TechDrawGui::QGCustomText::centerAt(), TechDrawGui::QGIView::exactFontSize(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by makeSymbols().
normalizeQPointF()
QPointF QGISectionLine::normalizeQPointF (QPointF inPoint) static protected
Definition at line 458 of file QGISectionLine.cpp.
References KDL::sqrt().
Referenced by extensionEndsISO(), extensionEndsTrad(), and getArrowPosition().
paint()
void QGISectionLine::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 476 of file QGISectionLine.cpp.
References TechDrawGui::QGIDecoration::paint(), and setTools().
pathMode()
bool TechDrawGui::QGISectionLine::pathMode () inline
Definition at line 88 of file QGISectionLine.h.
Referenced by draw().
setArrowDirections()
void QGISectionLine::setArrowDirections (Base::Vector3d dir1, Base::Vector3d dir2)
Definition at line 390 of file QGISectionLine.cpp.
References MULTIDIRECTIONMODE, and Base::Vector3< float_type >::Normalize().
Referenced by TechDrawGui::QGIViewPart::drawComplexSectionLine().
setBounds()
void QGISectionLine::setBounds (double x1, double y1, double x2, double y2)
Definition at line 362 of file QGISectionLine.cpp.
setChangePoints()
void QGISectionLine::setChangePoints (TechDraw::ChangePointVector changePoints)
Definition at line 433 of file QGISectionLine.cpp.
References clearChangePointMarks().
Referenced by TechDrawGui::QGIViewPart::drawComplexSectionLine(), and TechDrawGui::QGIViewPart::drawSectionLine().
setDirection() [1/2]
void QGISectionLine::setDirection (Base::Vector3d dir)
Definition at line 379 of file QGISectionLine.cpp.
References Base::Vector3< float_type >::Normalize(), and SINGLEDIRECTIONMODE.
setDirection() [2/2]
void QGISectionLine::setDirection (double xDir, double yDir)
Definition at line 373 of file QGISectionLine.cpp.
Referenced by TechDrawGui::QGIViewPart::drawComplexSectionLine(), and TechDrawGui::QGIViewPart::drawSectionLine().
setEnds()
void QGISectionLine::setEnds (Base::Vector3d l1, Base::Vector3d l2)
Definition at line 354 of file QGISectionLine.cpp.
References src.Mod.PartDesign.Scripts.Gear::l1, and src.Mod.PartDesign.Scripts.Gear::l2.
Referenced by TechDrawGui::QGIViewPart::drawComplexSectionLine(), and TechDrawGui::QGIViewPart::drawSectionLine().
setFont()
void QGISectionLine::setFont (QFont f, double fsize)
Definition at line 422 of file QGISectionLine.cpp.
References SCL.SimpleDataTypes::f.
Referenced by TechDrawGui::QGIViewPart::drawComplexSectionLine(), and TechDrawGui::QGIViewPart::drawSectionLine().
setLinePen()
void QGISectionLine::setLinePen (QPen isoPen)
Definition at line 505 of file QGISectionLine.cpp.
References TechDrawGui::QGIDecoration::m_pen.
Referenced by TechDrawGui::QGIViewPart::drawComplexSectionLine(), and TechDrawGui::QGIViewPart::drawSectionLine().
setPath()
void QGISectionLine::setPath (QPainterPath & path)
Definition at line 428 of file QGISectionLine.cpp.
Referenced by TechDrawGui::QGIViewPart::drawComplexSectionLine().
setPathMode()
void TechDrawGui::QGISectionLine::setPathMode (bool mode) inline
Definition at line 86 of file QGISectionLine.h.
Referenced by TechDrawGui::QGIViewPart::drawComplexSectionLine(), and TechDrawGui::QGIViewPart::drawSectionLine().
setSectionColor()
void QGISectionLine::setSectionColor (QColor c)
Definition at line 466 of file QGISectionLine.cpp.
References SCL.SimpleDataTypes::c, and TechDrawGui::QGIDecoration::setColor().
Referenced by TechDrawGui::QGIViewPart::drawComplexSectionLine(), and TechDrawGui::QGIViewPart::drawSectionLine().
setShowLine()
void TechDrawGui::QGISectionLine::setShowLine (bool state) inline
Definition at line 87 of file QGISectionLine.h.
Referenced by TechDrawGui::QGIViewPart::drawComplexSectionLine(), and TechDrawGui::QGIViewPart::drawSectionLine().
setSymbol()
void QGISectionLine::setSymbol (char * sym)
Definition at line 368 of file QGISectionLine.cpp.
Referenced by TechDrawGui::QGIViewPart::drawComplexSectionLine(), and TechDrawGui::QGIViewPart::drawSectionLine().
setTools()
void QGISectionLine::setTools () protected
Definition at line 484 of file QGISectionLine.cpp.
References TechDrawGui::QGIDecoration::m_brush, TechDrawGui::QGIDecoration::m_brushCurrent, TechDrawGui::QGIDecoration::m_colCurrent, TechDrawGui::QGIDecoration::m_pen, TechDrawGui::QGIDecoration::m_width, TechDrawGui::QGIPrimPath::setFillColor(), TechDrawGui::QGIPrimPath::setNormalColor(), and TechDrawGui::QGIPrimPath::setPrettyNormal().
Referenced by paint().
type()
int TechDrawGui::QGISectionLine::type () const inline override
Definition at line 73 of file QGISectionLine.h.
The documentation for this class was generated from the following files:
QGISectionLine.h
QGISectionLine.cpp