FreeCAD: TechDraw::Vertex Class Reference
TechDraw::Vertex Class Reference
#include <Geometry.h>
Public Member Functions
Vertex ()
Vertex (const Vertex *v)
Vertex (double x, double y)
Vertex (Base::Vector3d v)
virtual ~Vertex ()=default
virtual void Save (Base::Writer &) const
virtual void Restore (Base::XMLReader &)
virtual void dump (const char *title="")
bool isEqual (const Vertex &v, double tol)
Base::Vector3d point () const
void point (Base::Vector3d v)
double x ()
double y ()
boost::uuids::uuid getTag () const
virtual std::string getTagAsString () const
bool getHlrVisible ()
void setHlrVisible (bool state)
int getRef3d ()
void setRef3d (int ref)
TopoDS_Vertex getOCCVertex ()
void setOCCVertex (TopoDS_Vertex newVertex)
bool getCosmetic ()
void setCosmetic (bool state)
std::string getCosmeticTag ()
void setCosmeticTag (std::string t)
bool isCenter ()
void isCenter (bool state)
bool isReference ()
void isReference (bool state)
Part::TopoShape asTopoShape (double scale=1.0)
Protected Member Functions
void createNewTag ()
void assignTag (const TechDraw::Vertex *v)
Protected Attributes
Base::Vector3d pnt
ExtractionType extractType
bool hlrVisible
int ref3D
bool m_center
TopoDS_Vertex occVertex
bool cosmetic
int cosmeticLink
std::string cosmeticTag
bool m_reference
boost::uuids::uuid tag
Detailed Description
Definition at line 361 of file TechDraw/App/Geometry.h.
Constructor & Destructor Documentation
Vertex() [1/4]
TechDraw::Vertex::Vertex ()
Vertex() [2/4]
Vertex::Vertex (const Vertex * v) explicit
Definition at line 1295 of file TechDraw/App/Geometry.cpp.
References cosmetic, cosmeticLink, cosmeticTag, createNewTag(), extractType, hlrVisible, m_center, m_reference, occVertex, pnt, ref3D, and TestSpreadsheet::v.
Vertex() [3/4]
Vertex::Vertex (double x, double y)
Definition at line 1310 of file TechDraw/App/Geometry.cpp.
References cosmetic, cosmeticLink, cosmeticTag, createNewTag(), extractType, hlrVisible, m_center, m_reference, occVertex, TechDraw::Plain, pnt, ref3D, x(), and y().
Vertex() [4/4]
Vertex::Vertex (Base::Vector3d v) explicit
Definition at line 1326 of file TechDraw/App/Geometry.cpp.
~Vertex()
virtual TechDraw::Vertex::~Vertex () virtual default
Member Function Documentation
assignTag()
void TechDraw::Vertex::assignTag (const TechDraw::Vertex * v) protected
asTopoShape()
TopoShape Vertex::asTopoShape (double scale = 1.0)
Definition at line 1441 of file TechDraw/App/Geometry.cpp.
References getOCCVertex(), draftfunctions.scale::scale(), TechDraw::DrawUtil::togp_Pnt(), and TechDraw::DrawUtil::toVector3d().
createNewTag()
void Vertex::createNewTag () protected
Definition at line 1404 of file TechDraw/App/Geometry.cpp.
References tag.
Referenced by Vertex().
dump()
void Vertex::dump (const char * title = "") virtual
Reimplemented in TechDraw::CosmeticVertex.
Definition at line 1434 of file TechDraw/App/Geometry.cpp.
References Base::Console(), cosmetic, cosmeticLink, cosmeticTag, TechDraw::DrawUtil::formatVector(), hlrVisible, Base::ConsoleSingleton::Message(), pnt, and Plot::title().
getCosmetic()
bool TechDraw::Vertex::getCosmetic () inline
Definition at line 391 of file TechDraw/App/Geometry.h.
getCosmeticTag()
std::string TechDraw::Vertex::getCosmeticTag () inline
Definition at line 393 of file TechDraw/App/Geometry.h.
getHlrVisible()
bool TechDraw::Vertex::getHlrVisible () inline
Definition at line 385 of file TechDraw/App/Geometry.h.
getOCCVertex()
TopoDS_Vertex TechDraw::Vertex::getOCCVertex () inline
Definition at line 389 of file TechDraw/App/Geometry.h.
Referenced by asTopoShape().
getRef3d()
int TechDraw::Vertex::getRef3d () inline
Definition at line 387 of file TechDraw/App/Geometry.h.
getTag()
boost::uuids::uuid Vertex::getTag () const
Definition at line 1424 of file TechDraw/App/Geometry.cpp.
References tag.
Referenced by getTagAsString().
getTagAsString()
std::string Vertex::getTagAsString () const virtual
Reimplemented in TechDraw::CosmeticVertex.
Definition at line 1429 of file TechDraw/App/Geometry.cpp.
References getTag().
Referenced by Save().
isCenter() [1/2]
bool TechDraw::Vertex::isCenter () inline
Definition at line 395 of file TechDraw/App/Geometry.h.
isCenter() [2/2]
void TechDraw::Vertex::isCenter (bool state) inline
Definition at line 396 of file TechDraw/App/Geometry.h.
isEqual()
bool Vertex::isEqual (const Vertex & v, double tol)
Definition at line 1333 of file TechDraw/App/Geometry.cpp.
References DraftVecUtils::dist(), pnt, and TestSpreadsheet::v.
isReference() [1/2]
bool TechDraw::Vertex::isReference () inline
Definition at line 397 of file TechDraw/App/Geometry.h.
isReference() [2/2]
void TechDraw::Vertex::isReference (bool state) inline
Definition at line 398 of file TechDraw/App/Geometry.h.
point() [1/2]
Base::Vector3d TechDraw::Vertex::point () const inline
Definition at line 375 of file TechDraw/App/Geometry.h.
point() [2/2]
void TechDraw::Vertex::point (Base::Vector3d v) inline
Definition at line 376 of file TechDraw/App/Geometry.h.
References TestSpreadsheet::v.
Restore()
void Vertex::Restore (Base::XMLReader & reader) virtual
Reimplemented in TechDraw::CosmeticVertex.
Definition at line 1368 of file TechDraw/App/Geometry.cpp.
References cosmetic, cosmeticLink, cosmeticTag, extractType, hlrVisible, occVertex, pnt, TechDrawTools.TaskFillTemplateFields::reader, ref3D, tag, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by TechDraw::CosmeticVertex::Restore().
Save()
void Vertex::Save (Base::Writer & writer) const virtual
Reimplemented in TechDraw::CosmeticVertex.
Definition at line 1342 of file TechDraw/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, cosmetic, cosmeticLink, cosmeticTag, extractType, getTagAsString(), hlrVisible, Base::Writer::ind(), m_center, pnt, ref3D, Base::Writer::Stream(), TestSpreadsheet::v, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by TechDraw::CosmeticVertex::Save().
setCosmetic()
void TechDraw::Vertex::setCosmetic (bool state) inline
Definition at line 392 of file TechDraw/App/Geometry.h.
setCosmeticTag()
void TechDraw::Vertex::setCosmeticTag (std::string t) inline
Definition at line 394 of file TechDraw/App/Geometry.h.
References InitGui::t.
setHlrVisible()
void TechDraw::Vertex::setHlrVisible (bool state) inline
Definition at line 386 of file TechDraw/App/Geometry.h.
setOCCVertex()
void TechDraw::Vertex::setOCCVertex (TopoDS_Vertex newVertex) inline
Definition at line 390 of file TechDraw/App/Geometry.h.
setRef3d()
void TechDraw::Vertex::setRef3d (int ref) inline
Definition at line 388 of file TechDraw/App/Geometry.h.
x()
double TechDraw::Vertex::x () inline
Definition at line 378 of file TechDraw/App/Geometry.h.
Referenced by Path.Main.Gui.Inspect.GCodeEditorDialog::cleanup(), Path.Post.Utils.GCodeEditorDialog::done(), and Vertex().
y()
double TechDraw::Vertex::y () inline
Definition at line 379 of file TechDraw/App/Geometry.h.
Referenced by Path.Main.Gui.Inspect.GCodeEditorDialog::cleanup(), Path.Post.Utils.GCodeEditorDialog::done(), and Vertex().
Member Data Documentation
cosmetic
bool TechDraw::Vertex::cosmetic protected
Definition at line 413 of file TechDraw/App/Geometry.h.
Referenced by TechDraw::CosmeticVertex::CosmeticVertex(), dump(), Restore(), Save(), and Vertex().
cosmeticLink
int TechDraw::Vertex::cosmeticLink protected
Definition at line 414 of file TechDraw/App/Geometry.h.
Referenced by dump(), Restore(), Save(), and Vertex().
cosmeticTag
std::string TechDraw::Vertex::cosmeticTag protected
Definition at line 415 of file TechDraw/App/Geometry.h.
Referenced by dump(), Restore(), Save(), and Vertex().
extractType
ExtractionType TechDraw::Vertex::extractType protected
Definition at line 408 of file TechDraw/App/Geometry.h.
Referenced by Restore(), Save(), and Vertex().
hlrVisible
bool TechDraw::Vertex::hlrVisible protected
Definition at line 409 of file TechDraw/App/Geometry.h.
Referenced by TechDraw::CosmeticVertex::CosmeticVertex(), dump(), Restore(), Save(), and Vertex().
m_center
bool TechDraw::Vertex::m_center protected
Definition at line 411 of file TechDraw/App/Geometry.h.
Referenced by Save(), and Vertex().
m_reference
bool TechDraw::Vertex::m_reference protected
Definition at line 416 of file TechDraw/App/Geometry.h.
Referenced by Vertex().
occVertex
TopoDS_Vertex TechDraw::Vertex::occVertex protected
Definition at line 412 of file TechDraw/App/Geometry.h.
Referenced by Restore(), and Vertex().
pnt
Base::Vector3d TechDraw::Vertex::pnt protected
Definition at line 407 of file TechDraw/App/Geometry.h.
Referenced by dump(), isEqual(), Restore(), Save(), and Vertex().
ref3D
int TechDraw::Vertex::ref3D protected
Definition at line 410 of file TechDraw/App/Geometry.h.
Referenced by Restore(), Save(), and Vertex().
tag
boost::uuids::uuid TechDraw::Vertex::tag protected
Definition at line 418 of file TechDraw/App/Geometry.h.
Referenced by createNewTag(), Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.ChunkBase::dump_header(), getTag(), and Restore().
The documentation for this class was generated from the following files:
TechDraw/App/Geometry.h
TechDraw/App/Geometry.cpp