FreeCAD: AttachExtension.cpp File Reference
AttachExtension.cpp File Reference
#include "PreCompiled.h"
#include <Base/Console.h>
#include <Base/Tools.h>
#include "AttachExtension.h"
#include "AttachExtensionPy.h"
Namespaces
App
a class to assist with exporting sketches to dxf
Functions
template<class T >
static bool getProp (bool force, T *&prop, Base::Type type, App::PropertyContainer *owner, const char *name, const char *doc)
template<class T >
static bool getProp (bool force, T *&prop, App::PropertyContainer *owner, const char *name, const char *doc)
Function Documentation
getProp() [1/2]
template<class T > static bool getProp (bool force, T *& prop, App::PropertyContainer * owner, const char * name, const char * doc) inline static
Definition at line 186 of file AttachExtension.cpp.
References toolbit-attributes::doc, and getProp().
getProp() [2/2]
template<class T > static bool getProp (bool force, T *& prop, Base::Type type, App::PropertyContainer * owner, const char * name, const char * doc) inline static
Definition at line 164 of file AttachExtension.cpp.
References App::PropertyContainer::addDynamicProperty(), toolbit-attributes::doc, FC_THROWM, App::PropertyContainer::getDynamicPropertyByName(), App::PropertyContainer::getFullName(), and Path.Post.scripts.grbl_post::type.
Referenced by getProp().