FreeCAD: Gui::ElementColors Class Reference
Gui::ElementColors Class Reference
#include <TaskElementColors.h>
Classes
class Private
Public Member Functions
ElementColors (ViewProviderDocumentObject *vp, bool noHide=false)
~ElementColors () override
bool accept ()
bool reject ()
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Protected Member Functions
void onSelectionChanged (const SelectionChanges &msg) override
void changeEvent (QEvent *e) override
void leaveEvent (QEvent *) override
void slotDeleteDocument (const Document &)
void slotDeleteObject (const ViewProvider &)
Detailed Description
Definition at line 56 of file TaskElementColors.h.
Constructor & Destructor Documentation
ElementColors()
ElementColors::ElementColors (ViewProviderDocumentObject * vp, bool noHide = false) explicit
Definition at line 350 of file TaskElementColors.cpp.
References Gui::SelectionSingleton::addSelectionGate(), draftgeoutils.faces::bind(), Gui::ElementColors::Private::connectDelDoc, Gui::ElementColors::Private::connectDelObj, App::GetApplication(), ParameterGrp::GetBool(), Gui::ViewProviderDocumentObject::getObject(), App::Application::GetParameterGroupByPath(), App::PropertyString::getValue(), Gui::Application::Instance, App::DocumentObject::Label, Gui::NoResolve, Gui::ViewProviderDocumentObject::OnTopWhenSelected, Gui::ElementColors::Private::populate(), Gui::Selection(), App::PropertyEnumeration::setValue(), Gui::Application::signalDeletedObject, Gui::Application::signalDeleteDocument, slotDeleteDocument(), slotDeleteObject(), Gui::ElementColors::Private::ui, and Gui::ElementColors::Private::vpParent.
~ElementColors()
ElementColors::~ElementColors () override
Definition at line 385 of file TaskElementColors.cpp.
References Gui::ElementColors::Private::connectDelDoc, Gui::ElementColors::Private::connectDelObj, Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
accept()
bool ElementColors::accept ()
Definition at line 537 of file TaskElementColors.cpp.
References Gui::ElementColors::Private::accept(), Gui::Application::Instance, and Gui::Application::setEditDocument().
Referenced by Gui::TaskElementColors::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
changeEvent()
void ElementColors::changeEvent (QEvent * e) override protected
Definition at line 551 of file TaskElementColors.cpp.
References SCL.SimpleDataTypes::e, and Gui::ElementColors::Private::ui.
leaveEvent()
void ElementColors::leaveEvent (QEvent * e) override protected
Definition at line 559 of file TaskElementColors.cpp.
References SCL.SimpleDataTypes::e, Gui::ElementColors::Private::hiddenSub, Gui::ViewProvider::partialRender(), Gui::SelectionSingleton::rmvPreselect(), Gui::Selection(), and Gui::ElementColors::Private::vp.
onSelectionChanged()
void ElementColors::onSelectionChanged (const SelectionChanges & msg) override protected virtual
Implements Gui::SelectionObserver.
Definition at line 600 of file TaskElementColors.cpp.
References Path.Op.Surface::msg, and Gui::ElementColors::Private::onSelectionChanged().
reject()
bool ElementColors::reject ()
Definition at line 544 of file TaskElementColors.cpp.
References Gui::Application::Instance, Gui::ElementColors::Private::reset(), and Gui::Application::setEditDocument().
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), Gui::TaskElementColors::reject(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
slotDeleteDocument()
void ElementColors::slotDeleteDocument (const Document & Doc) protected
Definition at line 433 of file TaskElementColors.cpp.
References Gui::ControlSingleton::closeDialog(), Gui::Control(), Gui::ElementColors::Private::editDoc, Gui::Document::getDocument(), App::Document::getName(), and Gui::ElementColors::Private::vpDoc.
Referenced by ElementColors().
slotDeleteObject()
void ElementColors::slotDeleteObject (const ViewProvider & obj) protected
Definition at line 440 of file TaskElementColors.cpp.
References Gui::ControlSingleton::closeDialog(), Gui::Control(), and Gui::ElementColors::Private::vp.
Referenced by ElementColors().
The documentation for this class was generated from the following files:
TaskElementColors.h
TaskElementColors.cpp