FreeCAD: Part::GeomSurface Class Reference
Part::GeomSurface Class Reference
#include <Geometry.h>
Public Types
enum Curvature { Maximum, Minimum, Mean, Gaussian }
Public Member Functions
GeomSurface ()
~GeomSurface () override
bool isPlanar (gp_Pln *pln=nullptr, double tol=1e-7) const
TopoDS_Shape toShape () const override
GeomPlane * toPlane (bool clone=true, double tol=1e-7) const
virtual std::optional< Base::Rotation > getRotation () const
bool tangentU (double u, double v, gp_Dir &dirU) const
bool tangentV (double u, double v, gp_Dir &dirV) const
bool normal (double u, double v, gp_Dir &dir) const
virtual gp_Vec getDN (double u, double v, int Nu, int Nv) const
Curvature information
bool isUmbillic (double u, double v) const
double curvature (double u, double v, Curvature) const
void curvatureDirections (double u, double v, gp_Dir &maxD, gp_Dir &minD) const
Public Member Functions inherited from Part::Geometry
~Geometry () override
virtual const Handle (Geom_Geometry) &handle() const =0
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
virtual Geometry * copy () const =0
Geometry * clone () const
boost::uuids::uuid getTag () const
returns the tag of the geometry object
virtual bool isSame (const Geometry &other, double tol, double atol) const =0
bool hasSameExtensions (const Geometry &other) const
std::vector< std::weak_ptr< const GeometryExtension > > getExtensions () const
bool hasExtension (const Base::Type &type) const
bool hasExtension (const std::string &name) const
std::weak_ptr< const GeometryExtension > getExtension (const Base::Type &type) const
std::weak_ptr< const GeometryExtension > getExtension (const std::string &name) const
std::weak_ptr< GeometryExtension > getExtension (const Base::Type &type)
std::weak_ptr< GeometryExtension > getExtension (const std::string &name)
void setExtension (std::unique_ptr< GeometryExtension > &&geo)
void deleteExtension (const Base::Type &type)
void deleteExtension (const std::string &name)
void mirror (const Base::Vector3d &point) const
void mirror (const Base::Vector3d &point, const Base::Vector3d &dir) const
void rotate (const Base::Placement &plm) const
void scale (const Base::Vector3d &vec, double scale) const
void transform (const Base::Matrix4D &mat) const
void translate (const Base::Vector3d &vec) const
Geometry (const Geometry &)=delete
Geometry & operator= (const Geometry &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static bool isPlanar (const Handle(Geom_Surface) &s, gp_Pln *pln=nullptr, double tol=1e-7)
Static Public Member Functions inherited from Part::Geometry
static std::unique_ptr< Geometry > fromShape (const TopoDS_Shape &s, bool silent=false)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Additional Inherited Members
Protected Member Functions inherited from Part::Geometry
void createNewTag ()
create a new tag for the geometry object
void assignTag (const Part::Geometry *)
copies the tag from the geometry passed as a parameter to this object
void copyNonTag (const Part::Geometry *)
Geometry ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Part::Geometry
boost::uuids::uuid tag
std::vector< std::shared_ptr< GeometryExtension > > extensions
Detailed Description
Definition at line 886 of file Part/App/Geometry.h.
Member Enumeration Documentation
Curvature
enum Part::GeomSurface::Curvature
Enumerator
Maximum
Minimum
Mean
Gaussian
Definition at line 890 of file Part/App/Geometry.h.
Constructor & Destructor Documentation
GeomSurface()
GeomSurface::GeomSurface () default
~GeomSurface()
GeomSurface::~GeomSurface () override default
Member Function Documentation
curvature()
double GeomSurface::curvature (double u, double v, Curvature type) const
Definition at line 4908 of file Part/App/Geometry.cpp.
References Gaussian, Part::Geometry::Handle(), Maximum, Mean, Minimum, toolbit-attributes::s, THROWM, Path.Post.scripts.grbl_post::type, buildPsets::u, and TestSpreadsheet::v.
curvatureDirections()
void GeomSurface::curvatureDirections (double u, double v, gp_Dir & maxD, gp_Dir & minD) const
Definition at line 4935 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle(), toolbit-attributes::s, THROWM, buildPsets::u, and TestSpreadsheet::v.
getDN()
gp_Vec GeomSurface::getDN (double u, double v, int Nu, int Nv) const virtual
Computes the derivative of order Nu in the direction U and Nv in the direction V at the point P(U, V).
Reimplemented in Part::GeomCone.
Definition at line 4891 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle(), toolbit-attributes::s, buildPsets::u, and TestSpreadsheet::v.
Referenced by Part::GeomCone::getDN().
getRotation()
std::optional< Base::Rotation > GeomSurface::getRotation () const virtual
Reimplemented in Part::GeomPlane.
Definition at line 4841 of file Part/App/Geometry.cpp.
isPlanar() [1/2]
bool GeomSurface::isPlanar (const Handle(Geom_Surface) & s, gp_Pln * pln = nullptr, double tol = 1e-7) static
Definition at line 4807 of file Part/App/Geometry.cpp.
References ArchCommands::check(), and toolbit-attributes::s.
Referenced by FC_LOG_LEVEL_INIT(), isPlanar(), Part::GeomBSplineSurface::isSame(), and toPlane().
isPlanar() [2/2]
bool GeomSurface::isPlanar (gp_Pln * pln = nullptr, double tol = 1e-7) const
Definition at line 4801 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle(), isPlanar(), and toolbit-attributes::s.
isUmbillic()
bool GeomSurface::isUmbillic (double u, double v) const
Definition at line 4897 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle(), toolbit-attributes::s, THROWM, buildPsets::u, and TestSpreadsheet::v.
normal()
bool GeomSurface::normal (double u, double v, gp_Dir & dir) const
Definition at line 4878 of file Part/App/Geometry.cpp.
References Part::Tools::getNormal(), Part::Geometry::Handle(), toolbit-attributes::s, buildPsets::u, and TestSpreadsheet::v.
Referenced by ArchRoof._Roof::getPerpendicular().
tangentU()
bool GeomSurface::tangentU (double u, double v, gp_Dir & dirU) const
Definition at line 4855 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle(), toolbit-attributes::s, buildPsets::u, and TestSpreadsheet::v.
tangentV()
bool GeomSurface::tangentV (double u, double v, gp_Dir & dirV) const
Definition at line 4866 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle(), toolbit-attributes::s, buildPsets::u, and TestSpreadsheet::v.
toPlane()
GeomPlane * GeomSurface::toPlane (bool clone = true, double tol = 1e-7) const
Definition at line 4817 of file Part/App/Geometry.cpp.
References Part::Geometry::clone(), Part::Geometry::copy(), Base::Persistence::getClassTypeId(), Base::BaseClass::isDerivedFrom(), isPlanar(), and Part::Geometry::tag.
Referenced by Part::GeomBSplineSurface::isSame(), and Part::GeomPlane::isSame().
toShape()
TopoDS_Shape GeomSurface::toShape () const override virtual
Implements Part::Geometry.
Definition at line 4846 of file Part/App/Geometry.cpp.
References Part::Geometry::Handle(), toolbit-attributes::s, and draftgeoutils.general::v1().
The documentation for this class was generated from the following files:
Part/App/Geometry.h
Part/App/Geometry.cpp