FreeCAD: Gui::VectorTableDelegate Class Reference
Gui::VectorTableDelegate Class Reference
#include <VectorListEditor.h>
Public Member Functions
VectorTableDelegate (int decimals, QObject *parent=nullptr)
QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &option, const QModelIndex &index) const override
void setEditorData (QWidget *editor, const QModelIndex &index) const override
void setModelData (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const override
void updateEditorGeometry (QWidget *editor, const QStyleOptionViewItem &option, const QModelIndex &index) const override
Detailed Description
Definition at line 84 of file VectorListEditor.h.
Constructor & Destructor Documentation
VectorTableDelegate()
VectorTableDelegate::VectorTableDelegate (int decimals, QObject * parent = nullptr) explicit
Definition at line 243 of file VectorListEditor.cpp.
Member Function Documentation
createEditor()
QWidget * VectorTableDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & option, const QModelIndex & index) const override
Definition at line 249 of file VectorListEditor.cpp.
References Path.Post.Utils::editor(), and Init::parent.
setEditorData()
void VectorTableDelegate::setEditorData (QWidget * editor, const QModelIndex & index) const override
Definition at line 261 of file VectorListEditor.cpp.
References Path.Post.Utils::editor().
setModelData()
void VectorTableDelegate::setModelData (QWidget * editor, QAbstractItemModel * model, const QModelIndex & index) const override
Definition at line 269 of file VectorListEditor.cpp.
References Path.Post.Utils::editor().
updateEditorGeometry()
void VectorTableDelegate::updateEditorGeometry (QWidget * editor, const QStyleOptionViewItem & option, const QModelIndex & index) const override
Definition at line 278 of file VectorListEditor.cpp.
References Path.Post.Utils::editor().
The documentation for this class was generated from the following files:
VectorListEditor.h
VectorListEditor.cpp