FreeCAD: Part::GeomCylinder Class Reference
Part::GeomCylinder Class Reference
#include <Geometry.h>
Public Member Functions
GeomCylinder ()
GeomCylinder (const Handle(Geom_CylindricalSurface)&)
~GeomCylinder () override
Geometry * copy () const override
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
PyObject * getPyObject () override
double getRadius () const
bool isSame (const Geometry &other, double tol, double atol) const override
void setHandle (const Handle(Geom_CylindricalSurface)&)
const Handle (Geom_Geometry) &handle() const override
Public Member Functions inherited from Part::GeomElementarySurface
~GeomElementarySurface () override
Base::Vector3d getLocation () const
Base::Vector3d getDir () const
Base::Vector3d getXDir () const
Base::Vector3d getYDir () const
Public Member Functions inherited from Part::GeomSurface
GeomSurface ()
~GeomSurface () override
bool isPlanar (gp_Pln *pln=nullptr, double tol=1e-7) const
TopoDS_Shape toShape () const override
GeomPlane * toPlane (bool clone=true, double tol=1e-7) const
virtual std::optional< Base::Rotation > getRotation () const
bool tangentU (double u, double v, gp_Dir &dirU) const
bool tangentV (double u, double v, gp_Dir &dirV) const
bool normal (double u, double v, gp_Dir &dir) const
virtual gp_Vec getDN (double u, double v, int Nu, int Nv) const
bool isUmbillic (double u, double v) const
double curvature (double u, double v, Curvature) const
void curvatureDirections (double u, double v, gp_Dir &maxD, gp_Dir &minD) const
Public Member Functions inherited from Part::Geometry
~Geometry () override
Geometry * clone () const
boost::uuids::uuid getTag () const
returns the tag of the geometry object
bool hasSameExtensions (const Geometry &other) const
std::vector< std::weak_ptr< const GeometryExtension > > getExtensions () const
bool hasExtension (const Base::Type &type) const
bool hasExtension (const std::string &name) const
std::weak_ptr< const GeometryExtension > getExtension (const Base::Type &type) const
std::weak_ptr< const GeometryExtension > getExtension (const std::string &name) const
std::weak_ptr< GeometryExtension > getExtension (const Base::Type &type)
std::weak_ptr< GeometryExtension > getExtension (const std::string &name)
void setExtension (std::unique_ptr< GeometryExtension > &&geo)
void deleteExtension (const Base::Type &type)
void deleteExtension (const std::string &name)
void mirror (const Base::Vector3d &point) const
void mirror (const Base::Vector3d &point, const Base::Vector3d &dir) const
void rotate (const Base::Placement &plm) const
void scale (const Base::Vector3d &vec, double scale) const
void transform (const Base::Matrix4D &mat) const
void translate (const Base::Vector3d &vec) const
Geometry (const Geometry &)=delete
Geometry & operator= (const Geometry &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Public Types inherited from Part::GeomSurface
enum Curvature { Maximum, Minimum, Mean, Gaussian }
Static Public Member Functions inherited from Part::GeomSurface
static bool isPlanar (const Handle(Geom_Surface) &s, gp_Pln *pln=nullptr, double tol=1e-7)
Static Public Member Functions inherited from Part::Geometry
static std::unique_ptr< Geometry > fromShape (const TopoDS_Shape &s, bool silent=false)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions inherited from Part::GeomElementarySurface
GeomElementarySurface ()
Protected Member Functions inherited from Part::Geometry
void createNewTag ()
create a new tag for the geometry object
void assignTag (const Part::Geometry *)
copies the tag from the geometry passed as a parameter to this object
void copyNonTag (const Part::Geometry *)
Geometry ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Part::Geometry
boost::uuids::uuid tag
std::vector< std::shared_ptr< GeometryExtension > > extensions
Detailed Description
Definition at line 996 of file Part/App/Geometry.h.
Constructor & Destructor Documentation
GeomCylinder() [1/2]
GeomCylinder::GeomCylinder ()
Definition at line 5270 of file Part/App/Geometry.cpp.
References Handle(), and toolbit-attributes::s.
GeomCylinder() [2/2]
GeomCylinder::GeomCylinder (const Handle(Geom_CylindricalSurface)& c) explicit
Definition at line 5276 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, and setHandle().
~GeomCylinder()
GeomCylinder::~GeomCylinder () override default
Member Function Documentation
copy()
Geometry* Part::GeomCylinder::copy () const override virtual
returns a copy of this object having a new randomly generated tag. If you also want to copy the tag, you may use clone() instead. For creation of geometry with other handles, with or without the same tag, you may use the constructors and the sethandle functions. The tag of a geometry can be copied to another geometry using the assignTag function.
Implements Part::Geometry.
getMemSize()
unsigned int Part::GeomCylinder::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Reimplemented from Part::Geometry.
getPyObject()
PyObject * GeomCylinder::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 5317 of file Part/App/Geometry.cpp.
References Part::Geometry::clone().
getRadius()
double GeomCylinder::getRadius () const
Definition at line 5322 of file Part/App/Geometry.cpp.
Referenced by isSame().
Handle()
const Part::GeomCylinder::Handle (Geom_Geometry) const & override virtual
Implements Part::Geometry.
Referenced by setHandle().
isSame()
bool GeomCylinder::isSame (const Geometry & other, double tol, double atol) const override virtual
Reimplemented from Part::GeomElementarySurface.
Definition at line 5327 of file Part/App/Geometry.cpp.
References getRadius(), Base::Persistence::getTypeId(), and Part::GeomElementarySurface::isSame().
Restore()
void Part::GeomCylinder::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from Part::Geometry.
Save()
void Part::GeomCylinder::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Reimplemented from Part::Geometry.
setHandle()
void GeomCylinder::setHandle (const Handle(Geom_CylindricalSurface)& s)
Definition at line 5283 of file Part/App/Geometry.cpp.
References Handle(), and toolbit-attributes::s.
Referenced by GeomCylinder().
The documentation for this class was generated from the following files:
Part/App/Geometry.h
Part/App/Geometry.cpp