FreeCAD: Gui::EditorView Class Reference
Gui::EditorView Class Reference
#include <EditorView.h>
Public Types
enum DisplayName { FullName, FileName, BaseName }
Public Types inherited from Gui::MDIView
enum ViewMode { Child, TopLevel, FullScreen }
MDI view mode enum.
Public Member Functions
EditorView (TextEdit *editor, QWidget *parent)
~EditorView () override
QPlainTextEdit * getEditor () const
void setDisplayName (DisplayName)
void OnChange (Base::Subject< const char * > &rCaller, const char *rcReason) override
const char * getName () const override
returns the name of the view (important for messages)
void onUpdate () override
get called when the document is updated
bool onMsg (const char *pMsg, const char **ppReturn) override
bool onHasMsg (const char *pMsg) const override
bool canClose () override
Public Member Functions inherited from Gui::MDIView
MDIView (Gui::Document *pcDocument, QWidget *parent, Qt::WindowFlags wflags=Qt::WindowFlags())
~MDIView () override
void onRelabel (Gui::Document *pDoc) override
get called when the document is updated
virtual void viewAll ()
QString buildWindowTitle () const
build window title
bool onMsg (const char *pMsg, const char **ppReturn) override
Message handler.
bool onHasMsg (const char *pMsg) const override
Message handler test.
bool canClose () override
overwrite when checking on close state
void deleteSelf () override
delete itself
PyObject * getPyObject () override
QSize minimumSizeHint () const override
virtual void setCurrentViewMode (ViewMode mode)
ViewMode currentViewMode () const
template<typename _T >
_T getActiveObject (const char *name, App::DocumentObject **parent=nullptr, std::string *subname=nullptr) const
access getter for the active object list
void setActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr)
bool hasActiveObject (const char *n) const
bool isActiveObject (App::DocumentObject *o, const char *n, const char *subname=nullptr) const
virtual bool containsViewProvider (const ViewProvider *) const
containsViewProvider Checks if the given view provider is part of this view. The default implementation returns false.
void savePrinterSettings (QPrinter *printer)
void restorePrinterSettings (QPrinter *printer)
Public Member Functions inherited from Gui::BaseView
BaseView (Gui::Document *pcDocument=nullptr)
~BaseView () override
void setDocument (Gui::Document *pcDocument)
sets the view to another document (called by Application)
void onClose ()
is sent from the document in order to close the document
Gui::Document * getGuiDocument () const
returns the document the view is attached to
App::Document * getAppDocument () const
returns the document the view is attached to
bool isPassive () const
indicates if the view is in passive mode
virtual void onRename (Gui::Document *)
get called when the document is renamed (change of its internal name)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from Gui::WindowParameter
WindowParameter (const char *name)
~WindowParameter () override
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
ParameterGrp::handle getWindowParameter ()
return the parameter group of this window
Standard actions of the editor
bool open (const QString &f)
bool saveAs ()
void cut ()
void copy ()
void paste ()
void undo ()
void redo ()
void print () override
void printPdf () override
void printPreview () override
void print (QPrinter *) override
QStringList undoActions () const override
QStringList redoActions () const override
QString fileName () const
void focusInEvent (QFocusEvent *e) override
void showEvent (QShowEvent *) override
void hideEvent (QHideEvent *) override
void closeEvent (QCloseEvent *) override
void changeFileName (const QString &)
Additional Inherited Members
Public Slots inherited from Gui::MDIView
virtual void setOverrideCursor (const QCursor &)
virtual void restoreOverrideCursor ()
Signals inherited from Gui::MDIView
void message (const QString &, int)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter ()
get the parameters
Protected Slots inherited from Gui::MDIView
virtual void windowStateChanged (QWidget *)
Protected Member Functions inherited from Gui::MDIView
void closeEvent (QCloseEvent *e) override
void changeEvent (QEvent *e) override
Protected Member Functions inherited from Gui::WindowParameter
bool setGroupName (const char *name)
template<typename S , typename T >
void setSlotParamChanged (S slot, T *obsPtr)
connect slot to ParameterManager signal
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::MDIView
PyObject * pythonObject
Protected Attributes inherited from Gui::BaseView
Gui::Document * _pcDocument
bool bIsDetached {false}
bool bIsPassive {false}
Detailed Description
A special view class which sends the messages from the application to the editor and embeds it in a window.
Author
Werner Mayer
Definition at line 51 of file EditorView.h.
Member Enumeration Documentation
DisplayName
enum Gui::EditorView::DisplayName
Enumerator
FullName
FileName
BaseName
Definition at line 58 of file EditorView.h.
Constructor & Destructor Documentation
EditorView()
EditorView::EditorView (TextEdit * editor, QWidget * parent)
Constructs a EditorView which is a child of 'parent', with the name 'name'.
Definition at line 90 of file EditorView.cpp.
References Gui::SearchBar::activate(), Base::Subject< MsgType >::Attach(), draftgeoutils.intersections::connect(), Path.Post.Utils::editor(), Gui::TextEdit::findNext(), Gui::SearchBar::findNext(), Gui::TextEdit::findPrevious(), Gui::SearchBar::findPrevious(), FullName, Gui::getMainWindow(), Gui::EditorViewP::lock, NavigationIndicatorGui::mw, ParameterGrp::NotifyAll(), Gui::TextEdit::showSearchBar(), and Gui::MainWindow::updateEditorActions().
~EditorView()
EditorView::~EditorView () override
Destroys the object and frees any allocated resources
Definition at line 156 of file EditorView.cpp.
References Gui::EditorViewP::activityTimer, Base::Subject< MsgType >::Detach(), and Gui::WindowParameter::getWindowParameter().
Member Function Documentation
canClose()
bool EditorView::canClose () override virtual
Checking on close state.
Reimplemented from Gui::BaseView.
Definition at line 336 of file EditorView.cpp.
References Gui::EditorViewP::textEdit.
changeFileName
void Gui::EditorView::changeFileName (const QString &) signal
Referenced by Gui::PythonEditorView::PythonEditorView().
closeEvent()
void EditorView::closeEvent (QCloseEvent * event) override protected
Definition at line 181 of file EditorView.cpp.
References Gui::EditorViewP::aboutToClose, Gui::MDIView::closeEvent(), Gui::getMainWindow(), and NavigationIndicatorGui::mw.
copy()
void EditorView::copy ()
Copies any selected text to the clipboard.
Definition at line 422 of file EditorView.cpp.
References Gui::EditorViewP::textEdit.
Referenced by onMsg().
cut()
void EditorView::cut ()
Copies the selected text to the clipboard and deletes it from the text edit. If there is no selected text nothing happens.
Definition at line 414 of file EditorView.cpp.
References Gui::EditorViewP::textEdit.
Referenced by onMsg().
fileName()
QString EditorView::fileName () const
Definition at line 550 of file EditorView.cpp.
References Gui::EditorViewP::fileName.
Referenced by Gui::PythonEditorView::executeScript(), Gui::PythonDebugger::hideDebugMarker(), open(), and Gui::PythonDebugger::showDebugMarker().
focusInEvent()
void EditorView::focusInEvent (QFocusEvent * e) override protected
Definition at line 633 of file EditorView.cpp.
References Gui::EditorViewP::textEdit.
getEditor()
QPlainTextEdit * EditorView::getEditor () const
Definition at line 164 of file EditorView.cpp.
References Gui::EditorViewP::textEdit.
getName()
const char* Gui::EditorView::getName () const inline override virtual
returns the name of the view (important for messages)
Reimplemented from Gui::BaseView.
Definition at line 71 of file EditorView.h.
hideEvent()
void EditorView::hideEvent (QHideEvent * event) override protected
Definition at line 176 of file EditorView.cpp.
OnChange()
void EditorView::OnChange (Base::Subject< const char * > & rCaller, const char * rcReason) override
Definition at line 191 of file EditorView.cpp.
References Gui::WindowParameter::getWindowParameter().
onHasMsg()
bool EditorView::onHasMsg (const char * pMsg) const override virtual
Checks if the action pMsg is available. This is for enabling/disabling the corresponding buttons or menu items for this action.
Implements Gui::BaseView.
Reimplemented in Gui::PythonEditorView.
Definition at line 278 of file EditorView.cpp.
References Gui::EditorViewP::aboutToClose, and Gui::EditorViewP::textEdit.
Referenced by Gui::PythonEditorView::executeScript(), and Gui::PythonEditorView::onHasMsg().
onMsg()
bool EditorView::onMsg (const char * pMsg, const char ** ppReturn) override virtual
Runs the action specified by pMsg.
Implements Gui::BaseView.
Reimplemented in Gui::PythonEditorView.
Definition at line 231 of file EditorView.cpp.
References Gui::EditorViewP::aboutToClose, copy(), cut(), paste(), redo(), saveAs(), and undo().
Referenced by Gui::PythonEditorView::executeScript(), and Gui::PythonEditorView::onMsg().
onUpdate()
void Gui::EditorView::onUpdate () inline override virtual
get called when the document is updated
Reimplemented from Gui::BaseView.
Definition at line 72 of file EditorView.h.
open()
bool EditorView::open (const QString & fileName)
Opens the file fileName.
Definition at line 384 of file EditorView.cpp.
References Gui::EditorViewP::activityTimer, DrawingExample::file, fileName(), Gui::EditorViewP::lock, Gui::EditorViewP::redos, Gui::EditorViewP::textEdit, Gui::EditorViewP::timeStamp, and Gui::EditorViewP::undos.
Referenced by Gui::PythonDebugger::showDebugMarker().
paste()
void EditorView::paste ()
Pastes the text from the clipboard into the text edit at the current cursor position. If there is no text in the clipboard nothing happens.
Definition at line 431 of file EditorView.cpp.
References Gui::EditorViewP::textEdit.
Referenced by onMsg().
print() [1/2]
void EditorView::print () override virtual
Shows the printer dialog.
Reimplemented from Gui::MDIView.
Definition at line 471 of file EditorView.cpp.
References Gui::EditorViewP::textEdit.
Referenced by printPreview().
print() [2/2]
void EditorView::print (QPrinter * printer) override virtual
Reimplemented from Gui::MDIView.
Definition at line 492 of file EditorView.cpp.
References Gui::EditorViewP::textEdit.
printPdf()
void EditorView::printPdf () override virtual
Prints the document into a Pdf file.
Reimplemented from Gui::MDIView.
Definition at line 500 of file EditorView.cpp.
References Gui::FileDialog::getSaveFileName(), and Gui::EditorViewP::textEdit.
printPreview()
void EditorView::printPreview () override virtual
Show a preview dialog
Reimplemented from Gui::MDIView.
Definition at line 481 of file EditorView.cpp.
References draftgeoutils.intersections::connect(), and print().
redo()
void EditorView::redo ()
Redoes the last operation. If there is no operation to undo, i.e. there is no undo step in the undo/redo history, nothing happens.
Definition at line 457 of file EditorView.cpp.
References Gui::EditorViewP::lock, Gui::EditorViewP::redos, Gui::EditorViewP::textEdit, and Gui::EditorViewP::undos.
Referenced by onMsg().
redoActions()
QStringList EditorView::redoActions () const override virtual
Get the redo history.
Reimplemented from Gui::MDIView.
Definition at line 627 of file EditorView.cpp.
References Gui::EditorViewP::redos.
saveAs()
bool EditorView::saveAs ()
Saves the content of the editor to a file specified by the appearing file dialog.
Definition at line 367 of file EditorView.cpp.
References Gui::FileDialog::getSaveFileName().
Referenced by onMsg().
setDisplayName()
void EditorView::setDisplayName (EditorView::DisplayName type)
Definition at line 359 of file EditorView.cpp.
References Gui::EditorViewP::displayName, and Path.Post.scripts.grbl_post::type.
showEvent()
void EditorView::showEvent (QShowEvent * event) override protected
Definition at line 169 of file EditorView.cpp.
References Gui::getMainWindow(), and NavigationIndicatorGui::mw.
undo()
void EditorView::undo ()
Undoes the last operation. If there is no operation to undo, i.e. there is no undo step in the undo/redo history, nothing happens.
Definition at line 441 of file EditorView.cpp.
References Gui::EditorViewP::lock, Gui::EditorViewP::redos, Gui::EditorViewP::textEdit, and Gui::EditorViewP::undos.
Referenced by onMsg().
undoActions()
QStringList EditorView::undoActions () const override virtual
Get the undo history.
Reimplemented from Gui::MDIView.
Definition at line 619 of file EditorView.cpp.
References Gui::EditorViewP::undos.
The documentation for this class was generated from the following files:
EditorView.h
EditorView.cpp