FreeCAD: src.Mod.AddonManager.Widgets.addonmanager_colors Namespace Reference
src.Mod.AddonManager.Widgets.addonmanager_colors Namespace Reference
Functions
bool is_darkmode ()
str warning_color_string ()
str bright_color_string ()
str attention_color_string ()
Function Documentation
attention_color_string()
str src.Mod.AddonManager.Widgets.addonmanager_colors.attention_color_string ()
A shade of orange, adapted to darkmode if possible. Targets a minimum 7:1 contrast ratio.
Definition at line 46 of file addonmanager_colors.py.
References src.Mod.AddonManager.Widgets.addonmanager_colors.is_darkmode().
bright_color_string()
str src.Mod.AddonManager.Widgets.addonmanager_colors.bright_color_string ()
A shade of green, adapted to darkmode if possible. Targets a minimum 7:1 contrast ratio.
Definition at line 41 of file addonmanager_colors.py.
References src.Mod.AddonManager.Widgets.addonmanager_colors.is_darkmode().
is_darkmode()
bool src.Mod.AddonManager.Widgets.addonmanager_colors.is_darkmode ()
Heuristics to determine if we are in a darkmode stylesheet
Definition at line 30 of file addonmanager_colors.py.
Referenced by src.Mod.AddonManager.Widgets.addonmanager_colors.attention_color_string(), src.Mod.AddonManager.Widgets.addonmanager_colors.bright_color_string(), and src.Mod.AddonManager.Widgets.addonmanager_colors.warning_color_string().
warning_color_string()
str src.Mod.AddonManager.Widgets.addonmanager_colors.warning_color_string ()
A shade of red, adapted to darkmode if possible. Targets a minimum 7:1 contrast ratio.
Definition at line 36 of file addonmanager_colors.py.
References src.Mod.AddonManager.Widgets.addonmanager_colors.is_darkmode().