FreeCAD: AppMeshPartGui.cpp File Reference
AppMeshPartGui.cpp File Reference
#include "PreCompiled.h"
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/PyObjectBase.h>
#include <Gui/Application.h>
#include <Gui/Language/Translator.h>
#include "CurveOnMesh.h"
#include "Workbench.h"
Classes
class MeshPartGui::Module
Namespaces
MeshPartGui
Functions
void CreateMeshPartCommands ()
void loadMeshPartResource ()
PyObject * MeshPartGui::initModule ()
PyMOD_INIT_FUNC (MeshPartGui)
Function Documentation
CreateMeshPartCommands()
void CreateMeshPartCommands ()
Definition at line 342 of file Mod/MeshPart/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
loadMeshPartResource()
void loadMeshPartResource ()
Definition at line 38 of file AppMeshPartGui.cpp.
References Gui::Translator::instance(), and Gui::Translator::refresh().
Referenced by PyMOD_INIT_FUNC().
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (MeshPartGui)
Definition at line 69 of file AppMeshPartGui.cpp.
References Base::Console(), CreateMeshPartCommands(), Base::Persistence::init(), Base::BaseClass::init(), MeshPartGui::initModule(), Gui::Application::Instance, loadMeshPartResource(), Base::ConsoleSingleton::Log(), mod, and PyMOD_Return.