FreeCAD: Gui::ViewProviderIndex Class Reference
Gui::ViewProviderIndex Class Reference
Public Member Functions
ViewProviderIndex (const Gui::ViewProviderDocumentObject &v, DocumentIndex *d)
~ViewProviderIndex () override
ViewProviderIndex * clone () const
void findViewProviders (const ViewProviderDocumentObject &, QList< ViewProviderIndex * > &) const
QVariant data (int role) const override
Public Member Functions inherited from Gui::DocumentModelIndex
~DocumentModelIndex () override
void setParent (DocumentModelIndex *parent)
DocumentModelIndex * parent () const
void appendChild (DocumentModelIndex *child)
void removeChild (int row)
QList< DocumentModelIndex * > removeAll ()
DocumentModelIndex * child (int row)
int row () const
int childCount () const
virtual bool setData (const QVariant &value, int role)
virtual Qt::ItemFlags flags () const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Attributes
const Gui::ViewProviderDocumentObject & v
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions inherited from Gui::DocumentModelIndex
void reset ()
DocumentModelIndex ()=default
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::DocumentModelIndex
DocumentModelIndex * parentItem {nullptr}
QList< DocumentModelIndex * > childItems
Detailed Description
Definition at line 158 of file DocumentModel.cpp.
Constructor & Destructor Documentation
ViewProviderIndex()
Gui::ViewProviderIndex::ViewProviderIndex (const Gui::ViewProviderDocumentObject & v, DocumentIndex * d)
Definition at line 279 of file DocumentModel.cpp.
Referenced by clone().
~ViewProviderIndex()
Gui::ViewProviderIndex::~ViewProviderIndex () override
Definition at line 285 of file DocumentModel.cpp.
Member Function Documentation
clone()
ViewProviderIndex * Gui::ViewProviderIndex::clone () const
Definition at line 290 of file DocumentModel.cpp.
References SCL.SimpleDataTypes::c, Gui::DocumentModelIndex::childItems, v, and ViewProviderIndex().
Referenced by ArchPrecast._Precast::execute(), ArchFrame._Frame::execute(), ArchPrecast._PrecastBeam::execute(), ArchPanel._Panel::execute(), ArchPipe._ArchPipe::execute(), ArchTruss.Truss::execute(), ArchCurtainWall.CurtainWall::execute(), ArchRebar._Rebar::execute(), ArchEquipment._Equipment::execute(), ArchPrecast._PrecastIbeam::execute(), ArchComponent.Component::execute(), ArchSpace._Space::execute(), ArchStairs._Stairs::execute(), ArchPipe._ArchPipeConnector::execute(), ArchPrecast._PrecastPillar::execute(), ArchWall._Wall::execute(), ArchWindow._Window::execute(), ArchPrecast._PrecastPanel::execute(), ArchPrecast._PrecastSlab::execute(), ArchRoof._Roof::execute(), ArchPrecast._PrecastStairs::execute(), ArchStructure._Structure::execute(), src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated(), src.Mod.AddonManager.addonmanager_git.GitManager::repair(), and src.Mod.AddonManager.addonmanager_git.GitManager::update().
data()
QVariant Gui::ViewProviderIndex::data (int role) const override virtual
Reimplemented from Gui::DocumentModelIndex.
Definition at line 312 of file DocumentModel.cpp.
References App::Document::getActiveObject(), App::DocumentObject::getDocument(), Gui::ViewProvider::getIcon(), Gui::ViewProviderDocumentObject::getObject(), App::PropertyString::getValue(), App::DocumentObject::Label, and v.
findViewProviders()
void Gui::ViewProviderIndex::findViewProviders (const ViewProviderDocumentObject & vp, QList< ViewProviderIndex * > & index) const
Definition at line 300 of file DocumentModel.cpp.
References Gui::DocumentModelIndex::childItems, and v.
Member Data Documentation
v
const Gui::ViewProviderDocumentObject& Gui::ViewProviderIndex::v
Definition at line 163 of file DocumentModel.cpp.
Referenced by WorkingPlane.PlaneBase::__repr__(), WorkingPlane.PlaneBase::align_to_edge_or_wire(), WorkingPlane.PlaneBase::align_to_face(), WorkingPlane.PlaneBase::align_to_placement(), WorkingPlane.PlaneBase::align_to_point_and_axis(), WorkingPlane.PlaneBase::align_to_point_and_axis_svg(), WorkingPlane.PlaneGui::align_view(), clone(), data(), findViewProviders(), WorkingPlane.PlaneBase::get_global_coords(), WorkingPlane.PlaneBase::get_local_coords(), WorkingPlane.PlaneBase::get_placement(), draftguitools.gui_trackers.rectangleTracker::getNormal(), WorkingPlane.Plane::getRotation(), draftguitools.gui_trackers.rectangleTracker::getSize(), WorkingPlane.PlaneBase::is_global(), WorkingPlane.PlaneBase::is_ortho(), WorkingPlane.Plane::restore(), WorkingPlane.Plane::save(), WorkingPlane.PlaneBase::set_to_front(), WorkingPlane.PlaneBase::set_to_side(), WorkingPlane.PlaneBase::set_to_top(), WorkingPlane.PlaneGui::set_to_view(), draftguitools.gui_trackers.rectangleTracker::setPlane(), and draftguitools.gui_trackers.rectangleTracker::update().
The documentation for this class was generated from the following file:
DocumentModel.cpp