FreeCAD: linmath.h File Reference
linmath.h File Reference
#include <string.h>
#include <math.h>
Macros
#define LINMATH_H_FUNC static inline
#define LINMATH_H_DEFINE_VEC(n)
#define quat_add vec4_add
#define quat_sub vec4_sub
#define quat_norm vec4_norm
#define quat_scale vec4_scale
#define quat_mul_inner vec4_mul_inner
Typedefs
typedef float vec2[2]
typedef float vec3[3]
typedef float vec4[4]
typedef vec4 mat4x4[4]
typedef float quat[4]
Functions
static void vec2_add (vec2 r, vec2 const a, vec2 const b)
LINMATH_H_FUNC void vec2_sub (vec2 r, vec2 const a, vec2 const b)
LINMATH_H_FUNC void vec2_scale (vec2 r, vec2 const v, float const s)
LINMATH_H_FUNC float vec2_mul_inner (vec2 const a, vec2 const b)
LINMATH_H_FUNC float vec2_len (vec2 const v)
LINMATH_H_FUNC void vec2_norm (vec2 r, vec2 const v)
LINMATH_H_FUNC void vec2_min (vec2 r, vec2 const a, vec2 const b)
LINMATH_H_FUNC void vec2_max (vec2 r, vec2 const a, vec2 const b)
LINMATH_H_FUNC void vec2_dup (vec2 r, vec2 const src)
static void vec3_add (vec3 r, vec3 const a, vec3 const b)
LINMATH_H_FUNC void vec3_sub (vec3 r, vec3 const a, vec3 const b)
LINMATH_H_FUNC void vec3_scale (vec3 r, vec3 const v, float const s)
LINMATH_H_FUNC float vec3_mul_inner (vec3 const a, vec3 const b)
LINMATH_H_FUNC float vec3_len (vec3 const v)
LINMATH_H_FUNC void vec3_norm (vec3 r, vec3 const v)
LINMATH_H_FUNC void vec3_min (vec3 r, vec3 const a, vec3 const b)
LINMATH_H_FUNC void vec3_max (vec3 r, vec3 const a, vec3 const b)
LINMATH_H_FUNC void vec3_dup (vec3 r, vec3 const src)
static void vec4_add (vec4 r, vec4 const a, vec4 const b)
LINMATH_H_FUNC void vec4_sub (vec4 r, vec4 const a, vec4 const b)
LINMATH_H_FUNC void vec4_scale (vec4 r, vec4 const v, float const s)
LINMATH_H_FUNC float vec4_mul_inner (vec4 const a, vec4 const b)
LINMATH_H_FUNC float vec4_len (vec4 const v)
LINMATH_H_FUNC void vec4_norm (vec4 r, vec4 const v)
LINMATH_H_FUNC void vec4_min (vec4 r, vec4 const a, vec4 const b)
LINMATH_H_FUNC void vec4_max (vec4 r, vec4 const a, vec4 const b)
LINMATH_H_FUNC void vec4_dup (vec4 r, vec4 const src)
static void vec3_set (vec3 r, float x, float y, float z)
static void vec3_mul_cross (vec3 r, vec3 const a, vec3 const b)
static void vec3_reflect (vec3 r, vec3 const v, vec3 const n)
static void vec4_mul_cross (vec4 r, vec4 const a, vec4 const b)
static void vec4_reflect (vec4 r, vec4 const v, vec4 const n)
static void mat4x4_identity (mat4x4 M)
static void mat4x4_dup (mat4x4 M, mat4x4 const N)
static void mat4x4_row (vec4 r, mat4x4 const M, int i)
static void mat4x4_col (vec4 r, mat4x4 const M, int i)
static void mat4x4_transpose (mat4x4 M, mat4x4 const N)
static void mat4x4_add (mat4x4 M, mat4x4 const a, mat4x4 const b)
static void mat4x4_sub (mat4x4 M, mat4x4 const a, mat4x4 const b)
static void mat4x4_scale (mat4x4 M, mat4x4 const a, float k)
static void mat4x4_scale_aniso (mat4x4 M, mat4x4 const a, float x, float y, float z)
static void mat4x4_mul (mat4x4 M, mat4x4 const a, mat4x4 const b)
static void mat4x4_mul_vec4 (vec4 r, mat4x4 const M, vec4 const v)
static void mat4x4_translate (mat4x4 T, float x, float y, float z)
static void mat4x4_translate_in_place (mat4x4 M, float x, float y, float z)
static void mat4x4_translate_in_place_v (mat4x4 M, vec3 v)
static void mat4x4_from_vec3_mul_outer (mat4x4 M, vec3 const a, vec3 const b)
static void mat4x4_rotate (mat4x4 R, mat4x4 const M, float x, float y, float z, float angle)
static void mat4x4_rotate_X (mat4x4 Q, mat4x4 const M, float angle)
static void mat4x4_rotate_Y (mat4x4 Q, mat4x4 const M, float angle)
static void mat4x4_rotate_Z (mat4x4 Q, mat4x4 const M, float angle)
static void mat4x4_invert (mat4x4 T, mat4x4 const M)
static void mat4x4_orthonormalize (mat4x4 R, mat4x4 const M)
static void mat4x4_frustum (mat4x4 M, float l, float r, float b, float t, float n, float f)
static void mat4x4_ortho (mat4x4 M, float l, float r, float b, float t, float n, float f)
static void mat4x4_perspective (mat4x4 m, float y_fov, float aspect, float n, float f)
static void mat4x4_look_at (mat4x4 m, vec3 const eye, vec3 const center, vec3 const up)
static void quat_identity (quat q)
static void quat_mul (quat r, quat const p, quat const q)
static void quat_conj (quat r, quat const q)
static void quat_rotate (quat r, float angle, vec3 const axis)
static void quat_mul_vec3 (vec3 r, quat const q, vec3 const v)
static void mat4x4_from_quat (mat4x4 M, quat const q)
static void mat4x4o_mul_quat (mat4x4 R, mat4x4 const M, quat const q)
static void quat_from_mat4x4 (quat q, mat4x4 const M)
static void mat4x4_arcball (mat4x4 R, mat4x4 const M, vec2 const _a, vec2 const _b, float s)
Macro Definition Documentation
LINMATH_H_DEFINE_VEC
#define LINMATH_H_DEFINE_VEC (n)
Definition at line 16 of file linmath.h.
LINMATH_H_FUNC
#define LINMATH_H_FUNC static inline
Definition at line 13 of file linmath.h.
quat_add
#define quat_add vec4_add
Definition at line 463 of file linmath.h.
quat_mul_inner
#define quat_mul_inner vec4_mul_inner
Definition at line 467 of file linmath.h.
quat_norm
#define quat_norm vec4_norm
Definition at line 465 of file linmath.h.
quat_scale
#define quat_scale vec4_scale
Definition at line 466 of file linmath.h.
quat_sub
#define quat_sub vec4_sub
Definition at line 464 of file linmath.h.
Typedef Documentation
mat4x4
typedef vec4 mat4x4[4]
Definition at line 116 of file linmath.h.
quat
typedef float quat[4]
Definition at line 462 of file linmath.h.
vec2
typedef float vec2[2]
Definition at line 72 of file linmath.h.
vec3
typedef float vec3[3]
Definition at line 73 of file linmath.h.
vec4
typedef float vec4[4]
Definition at line 74 of file linmath.h.
Function Documentation
mat4x4_add()
static void mat4x4_add (mat4x4 M, mat4x4 const a, mat4x4 const b) inline static
Definition at line 158 of file linmath.h.
References a, SCL.SimpleDataTypes::b, SplineSurface::i, and vec4_add().
Referenced by mat4x4_rotate().
mat4x4_arcball()
static void mat4x4_arcball (mat4x4 R, mat4x4 const M, vec2 const _a, vec2 const _b, float s) inline static
Definition at line 599 of file linmath.h.
References a, DraftVecUtils::angle(), SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::f, mat4x4_rotate(), CAMTests.TestPathStock::R, toolbit-attributes::s, vec2_len(), vec2_mul_inner(), vec2_norm(), vec3_mul_cross(), and vec3_mul_inner().
mat4x4_col()
static void mat4x4_col (vec4 r, mat4x4 const M, int i) inline static
Definition at line 140 of file linmath.h.
References SplineSurface::i.
mat4x4_dup()
static void mat4x4_dup (mat4x4 M, mat4x4 const N) inline static
Definition at line 126 of file linmath.h.
References SplineSurface::i, and vec4_dup().
Referenced by mat4x4_mul(), mat4x4_orthonormalize(), mat4x4_rotate(), and MillSim::MillPathSegment::render().
mat4x4_from_quat()
static void mat4x4_from_quat (mat4x4 M, quat const q) inline static
Definition at line 524 of file linmath.h.
References a, NavigationIndicatorGui::a2, SCL.SimpleDataTypes::b, and SCL.SimpleDataTypes::c.
mat4x4_from_vec3_mul_outer()
static void mat4x4_from_vec3_mul_outer (mat4x4 M, vec3 const a, vec3 const b) inline static
Definition at line 237 of file linmath.h.
References a, SCL.SimpleDataTypes::b, and SplineSurface::i.
Referenced by mat4x4_rotate().
mat4x4_frustum()
static void mat4x4_frustum (mat4x4 M, float l, float r, float b, float t, float n, float f) inline static
Definition at line 362 of file linmath.h.
References SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::f, RobotExample::l, and InitGui::t.
mat4x4_identity()
static void mat4x4_identity (mat4x4 M) inline static
Definition at line 117 of file linmath.h.
References SplineSurface::i.
Referenced by mat4x4_rotate(), mat4x4_translate(), MillSim::MillPathSegment::MillPathSegment(), MillSim::MillPathSegment::render(), and MillSim::SolidObject::SolidObject().
mat4x4_invert()
static void mat4x4_invert (mat4x4 T, mat4x4 const M) inline static
Definition at line 297 of file linmath.h.
References SCL.SimpleDataTypes::c, and toolbit-attributes::s.
mat4x4_look_at()
static void mat4x4_look_at (mat4x4 m, vec3 const eye, vec3 const center, vec3 const up) inline static
Definition at line 420 of file linmath.h.
References exportCSG::center(), SCL.SimpleDataTypes::f, test::m, mat4x4_translate_in_place(), toolbit-attributes::s, InitGui::t, vec3_mul_cross(), vec3_norm(), and vec3_sub().
mat4x4_mul()
static void mat4x4_mul (mat4x4 M, mat4x4 const a, mat4x4 const b) inline static
Definition at line 186 of file linmath.h.
References a, SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::c, and mat4x4_dup().
Referenced by mat4x4_rotate(), mat4x4_rotate_X(), mat4x4_rotate_Y(), mat4x4_rotate_Z(), and MillSim::MillPathSegment::render().
mat4x4_mul_vec4()
static void mat4x4_mul_vec4 (vec4 r, mat4x4 const M, vec4 const v) inline static
Definition at line 200 of file linmath.h.
References SplineSurface::i, and TestSpreadsheet::v.
mat4x4_ortho()
static void mat4x4_ortho (mat4x4 M, float l, float r, float b, float t, float n, float f) inline static
Definition at line 378 of file linmath.h.
References SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::f, RobotExample::l, and InitGui::t.
mat4x4_orthonormalize()
static void mat4x4_orthonormalize (mat4x4 R, mat4x4 const M) inline static
Definition at line 339 of file linmath.h.
References mat4x4_dup(), CAMTests.TestPathStock::R, toolbit-attributes::s, vec3_mul_inner(), vec3_norm(), vec3_scale(), and vec3_sub().
mat4x4_perspective()
static void mat4x4_perspective (mat4x4 m, float y_fov, float aspect, float n, float f) inline static
Definition at line 394 of file linmath.h.
References a, SCL.SimpleDataTypes::f, and test::m.
mat4x4_rotate()
static void mat4x4_rotate (mat4x4 R, mat4x4 const M, float x, float y, float z, float angle) inline static
Definition at line 246 of file linmath.h.
References DraftVecUtils::angle(), RobotExample::C, SCL.SimpleDataTypes::c, SCL.SimpleDataTypes::e, mat4x4_add(), mat4x4_dup(), mat4x4_from_vec3_mul_outer(), mat4x4_identity(), mat4x4_mul(), mat4x4_scale(), mat4x4_sub(), CAMTests.TestPathStock::R, toolbit-attributes::s, buildPsets::u, vec3_len(), vec3_norm(), MovieTool::x, and MovieTool::y.
Referenced by mat4x4_arcball().
mat4x4_rotate_X()
static void mat4x4_rotate_X (mat4x4 Q, mat4x4 const M, float angle) inline static
Definition at line 276 of file linmath.h.
References DraftVecUtils::angle(), SCL.SimpleDataTypes::c, mat4x4_mul(), AttachmentEditor.TaskAttachmentEditor::Q, CAMTests.TestPathStock::R, and toolbit-attributes::s.
mat4x4_rotate_Y()
static void mat4x4_rotate_Y (mat4x4 Q, mat4x4 const M, float angle) inline static
Definition at line 283 of file linmath.h.
References DraftVecUtils::angle(), SCL.SimpleDataTypes::c, mat4x4_mul(), AttachmentEditor.TaskAttachmentEditor::Q, CAMTests.TestPathStock::R, and toolbit-attributes::s.
mat4x4_rotate_Z()
static void mat4x4_rotate_Z (mat4x4 Q, mat4x4 const M, float angle) inline static
Definition at line 290 of file linmath.h.
References DraftVecUtils::angle(), SCL.SimpleDataTypes::c, mat4x4_mul(), AttachmentEditor.TaskAttachmentEditor::Q, CAMTests.TestPathStock::R, and toolbit-attributes::s.
Referenced by MillSim::MillPathSegment::render().
mat4x4_row()
static void mat4x4_row (vec4 r, mat4x4 const M, int i) inline static
Definition at line 133 of file linmath.h.
References SplineSurface::i.
Referenced by mat4x4_translate_in_place(), and mat4x4_translate_in_place_v().
mat4x4_scale()
static void mat4x4_scale (mat4x4 M, mat4x4 const a, float k) inline static
Definition at line 172 of file linmath.h.
References a, SplineSurface::i, and vec4_scale().
Referenced by mat4x4_rotate().
mat4x4_scale_aniso()
static void mat4x4_scale_aniso (mat4x4 M, mat4x4 const a, float x, float y, float z) inline static
Definition at line 179 of file linmath.h.
References a, vec4_dup(), vec4_scale(), MovieTool::x, and MovieTool::y.
Referenced by MillSim::MillPathSegment::render().
mat4x4_sub()
static void mat4x4_sub (mat4x4 M, mat4x4 const a, mat4x4 const b) inline static
Definition at line 165 of file linmath.h.
References a, SCL.SimpleDataTypes::b, SplineSurface::i, and vec4_sub().
Referenced by mat4x4_rotate().
mat4x4_translate()
static void mat4x4_translate (mat4x4 T, float x, float y, float z) inline static
Definition at line 210 of file linmath.h.
References mat4x4_identity(), MovieTool::x, and MovieTool::y.
Referenced by MillSim::MillSimulation::RenderTool(), and MillSim::SolidObject::SetPosition().
mat4x4_translate_in_place()
static void mat4x4_translate_in_place (mat4x4 M, float x, float y, float z) inline static
Definition at line 217 of file linmath.h.
References SplineSurface::i, mat4x4_row(), InitGui::t, vec4_mul_inner(), MovieTool::x, and MovieTool::y.
Referenced by mat4x4_look_at(), and MillSim::MillPathSegment::render().
mat4x4_translate_in_place_v()
static void mat4x4_translate_in_place_v (mat4x4 M, vec3 v) inline static
Definition at line 227 of file linmath.h.
References SplineSurface::i, mat4x4_row(), InitGui::t, TestSpreadsheet::v, and vec4_mul_inner().
Referenced by MillSim::MillPathSegment::render().
mat4x4_transpose()
static void mat4x4_transpose (mat4x4 M, mat4x4 const N) inline static
Definition at line 147 of file linmath.h.
References SplineSurface::i.
mat4x4o_mul_quat()
static void mat4x4o_mul_quat (mat4x4 R, mat4x4 const M, quat const q) inline static
Definition at line 554 of file linmath.h.
References quat_mul_vec3(), and CAMTests.TestPathStock::R.
quat_conj()
static void quat_conj (quat r, quat const q) inline static
Definition at line 487 of file linmath.h.
References SplineSurface::i.
quat_from_mat4x4()
static void quat_from_mat4x4 (quat q, mat4x4 const M) inline static
Definition at line 568 of file linmath.h.
References SCL.SimpleDataTypes::e, SCL.SimpleDataTypes::f, SplineSurface::i, test::m, and buildPsets::p.
quat_identity()
static void quat_identity (quat q) inline static
Definition at line 469 of file linmath.h.
quat_mul()
static void quat_mul (quat r, quat const p, quat const q) inline static
Definition at line 474 of file linmath.h.
References buildPsets::p, vec3_add(), vec3_dup(), vec3_mul_cross(), vec3_mul_inner(), vec3_scale(), and src.Mod.PartDesign.fcgear.svggear::w.
quat_mul_vec3()
static void quat_mul_vec3 (vec3 r, quat const q, vec3 const v) inline static
Definition at line 504 of file linmath.h.
References InitGui::t, buildPsets::u, TestSpreadsheet::v, vec3_add(), vec3_mul_cross(), and vec3_scale().
Referenced by mat4x4o_mul_quat().
quat_rotate()
static void quat_rotate (quat r, float angle, vec3 const axis) inline static
Definition at line 495 of file linmath.h.
References DraftVecUtils::angle(), SCL.SimpleDataTypes::c, toolbit-attributes::s, vec3_norm(), and vec3_scale().
vec2_add()
static void vec2_add (vec2 r, vec2 const a, vec2 const b) inline static
Definition at line 72 of file linmath.h.
vec2_dup()
LINMATH_H_FUNC void vec2_dup (vec2 r, vec2 const src)
Definition at line 72 of file linmath.h.
vec2_len()
LINMATH_H_FUNC float vec2_len (vec2 const v)
Definition at line 72 of file linmath.h.
Referenced by mat4x4_arcball().
vec2_max()
LINMATH_H_FUNC void vec2_max (vec2 r, vec2 const a, vec2 const b)
Definition at line 72 of file linmath.h.
vec2_min()
LINMATH_H_FUNC void vec2_min (vec2 r, vec2 const a, vec2 const b)
Definition at line 72 of file linmath.h.
vec2_mul_inner()
LINMATH_H_FUNC float vec2_mul_inner (vec2 const a, vec2 const b)
Definition at line 72 of file linmath.h.
Referenced by mat4x4_arcball().
vec2_norm()
LINMATH_H_FUNC void vec2_norm (vec2 r, vec2 const v)
Definition at line 72 of file linmath.h.
Referenced by mat4x4_arcball().
vec2_scale()
LINMATH_H_FUNC void vec2_scale (vec2 r, vec2 const v, float const s)
Definition at line 72 of file linmath.h.
vec2_sub()
LINMATH_H_FUNC void vec2_sub (vec2 r, vec2 const a, vec2 const b)
Definition at line 72 of file linmath.h.
vec3_add()
static void vec3_add (vec3 r, vec3 const a, vec3 const b) inline static
Definition at line 73 of file linmath.h.
Referenced by MillSim::MillPathSegment::GetHeadPosition(), quat_mul(), and quat_mul_vec3().
vec3_dup()
LINMATH_H_FUNC void vec3_dup (vec3 r, vec3 const src)
Definition at line 73 of file linmath.h.
Referenced by MillSim::MillPathSegment::GetHeadPosition(), and quat_mul().
vec3_len()
LINMATH_H_FUNC float vec3_len (vec3 const v)
Definition at line 73 of file linmath.h.
Referenced by mat4x4_rotate().
vec3_max()
LINMATH_H_FUNC void vec3_max (vec3 r, vec3 const a, vec3 const b)
Definition at line 73 of file linmath.h.
vec3_min()
LINMATH_H_FUNC void vec3_min (vec3 r, vec3 const a, vec3 const b)
Definition at line 73 of file linmath.h.
vec3_mul_cross()
static void vec3_mul_cross (vec3 r, vec3 const a, vec3 const b) inline static
Definition at line 83 of file linmath.h.
References a, and SCL.SimpleDataTypes::b.
Referenced by mat4x4_arcball(), mat4x4_look_at(), quat_mul(), and quat_mul_vec3().
vec3_mul_inner()
LINMATH_H_FUNC float vec3_mul_inner (vec3 const a, vec3 const b)
Definition at line 73 of file linmath.h.
Referenced by mat4x4_arcball(), mat4x4_orthonormalize(), quat_mul(), and vec3_reflect().
vec3_norm()
LINMATH_H_FUNC void vec3_norm (vec3 r, vec3 const v)
Definition at line 73 of file linmath.h.
Referenced by mat4x4_look_at(), mat4x4_orthonormalize(), mat4x4_rotate(), and quat_rotate().
vec3_reflect()
static void vec3_reflect (vec3 r, vec3 const v, vec3 const n) inline static
Definition at line 90 of file linmath.h.
References SplineSurface::i, buildPsets::p, TestSpreadsheet::v, and vec3_mul_inner().
vec3_scale()
LINMATH_H_FUNC void vec3_scale (vec3 r, vec3 const v, float const s)
Definition at line 73 of file linmath.h.
Referenced by MillSim::MillPathSegment::GetHeadPosition(), mat4x4_orthonormalize(), MillSim::MillPathSegment::MillPathSegment(), quat_mul(), quat_mul_vec3(), and quat_rotate().
vec3_set()
static void vec3_set (vec3 r, float x, float y, float z) inline static
Definition at line 76 of file linmath.h.
References MovieTool::x, and MovieTool::y.
Referenced by MillSim::StockObject::GenerateBoxStock(), MillSim::SolidObject::GenerateSolid(), MillSim::MillPathSegment::GetHeadPosition(), and MillSim::SolidObject::SolidObject().
vec3_sub()
LINMATH_H_FUNC void vec3_sub (vec3 r, vec3 const a, vec3 const b)
Definition at line 73 of file linmath.h.
Referenced by mat4x4_look_at(), mat4x4_orthonormalize(), and MillSim::MillPathSegment::MillPathSegment().
vec4_add()
static void vec4_add (vec4 r, vec4 const a, vec4 const b) inline static
Definition at line 74 of file linmath.h.
Referenced by mat4x4_add().
vec4_dup()
LINMATH_H_FUNC void vec4_dup (vec4 r, vec4 const src)
Definition at line 74 of file linmath.h.
Referenced by mat4x4_dup(), and mat4x4_scale_aniso().
vec4_len()
LINMATH_H_FUNC float vec4_len (vec4 const v)
Definition at line 74 of file linmath.h.
vec4_max()
LINMATH_H_FUNC void vec4_max (vec4 r, vec4 const a, vec4 const b)
Definition at line 74 of file linmath.h.
vec4_min()
LINMATH_H_FUNC void vec4_min (vec4 r, vec4 const a, vec4 const b)
Definition at line 74 of file linmath.h.
vec4_mul_cross()
static void vec4_mul_cross (vec4 r, vec4 const a, vec4 const b) inline static
Definition at line 99 of file linmath.h.
References a, and SCL.SimpleDataTypes::b.
vec4_mul_inner()
LINMATH_H_FUNC float vec4_mul_inner (vec4 const a, vec4 const b)
Definition at line 74 of file linmath.h.
Referenced by mat4x4_translate_in_place(), mat4x4_translate_in_place_v(), and vec4_reflect().
vec4_norm()
LINMATH_H_FUNC void vec4_norm (vec4 r, vec4 const v)
Definition at line 74 of file linmath.h.
vec4_reflect()
static void vec4_reflect (vec4 r, vec4 const v, vec4 const n) inline static
Definition at line 107 of file linmath.h.
References SplineSurface::i, buildPsets::p, TestSpreadsheet::v, and vec4_mul_inner().
vec4_scale()
LINMATH_H_FUNC void vec4_scale (vec4 r, vec4 const v, float const s)
Definition at line 74 of file linmath.h.
Referenced by mat4x4_scale(), and mat4x4_scale_aniso().
vec4_sub()
LINMATH_H_FUNC void vec4_sub (vec4 r, vec4 const a, vec4 const b)
Definition at line 74 of file linmath.h.
Referenced by mat4x4_sub().