FreeCAD: Gui::Dialog::ParameterValue Class Reference
Gui::Dialog::ParameterValue Class Reference
#include <DlgParameterImp.h>
Public Member Functions
ParameterValue (QWidget *parent=nullptr)
~ParameterValue () override
void setCurrentGroup (const Base::Reference< ParameterGrp > &_hcGrp)
Base::Reference< ParameterGrp > currentGroup () const
Protected Slots
void onChangeSelectedItem (QTreeWidgetItem *, int)
void onChangeSelectedItem ()
void onDeleteSelectedItem ()
void onRenameSelectedItem ()
void onCreateTextItem ()
void onCreateIntItem ()
void onCreateUIntItem ()
void onCreateFloatItem ()
void onCreateBoolItem ()
bool edit (const QModelIndex &index, QAbstractItemView::EditTrigger trigger, QEvent *event) override
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *event) override
void keyPressEvent (QKeyEvent *event) override
void resizeEvent (QResizeEvent *) override
Detailed Description
The ParameterValue class displays all leaves of a parameter group. A leaf is represented by the ParameterValueItem class.
Author
Werner Mayer
Definition at line 186 of file DlgParameterImp.h.
Constructor & Destructor Documentation
ParameterValue()
ParameterValue::ParameterValue (QWidget * parent = nullptr) explicit
Definition at line 687 of file DlgParameterImp.cpp.
References draftgeoutils.intersections::connect(), onChangeSelectedItem(), onCreateBoolItem(), onCreateFloatItem(), onCreateIntItem(), onCreateTextItem(), onCreateUIntItem(), onDeleteSelectedItem(), and onRenameSelectedItem().
~ParameterValue()
ParameterValue::~ParameterValue () override default
Member Function Documentation
contextMenuEvent()
void ParameterValue::contextMenuEvent (QContextMenuEvent * event) override protected
Shows the context menu.
Definition at line 734 of file DlgParameterImp.cpp.
currentGroup()
Base::Reference< ParameterGrp > ParameterValue::currentGroup () const
Returns the current parameter group that is displayed.
Definition at line 721 of file DlgParameterImp.cpp.
edit
bool ParameterValue::edit (const QModelIndex & index, QAbstractItemView::EditTrigger trigger, QEvent * event) override protected slot
Defines that the first column is editable.
Note
We need to reimplement this method as QTreeWidgetItem::flags() doesn't have an int parameter.
Definition at line 726 of file DlgParameterImp.cpp.
Referenced by ArchComponent.ViewProviderComponent::contextMenuAddEdit(), ArchAxisSystem._ViewProviderAxisSystem::doubleClicked(), draftviewproviders.view_draft_annotation.ViewProviderDraftAnnotation::doubleClicked(), ArchSchedule._ViewProviderArchSchedule::doubleClicked(), ArchMaterial._ViewProviderArchMultiMaterial::doubleClicked(), ArchSectionPlane._ViewProviderSectionPlane::doubleClicked(), onCreateUIntItem(), ArchIFCView.IfcContextView::setupContextMenu(), draftviewproviders.view_hatch.ViewProviderDraftHatch::setupContextMenu(), ArchAxisSystem._ViewProviderAxisSystem::setupContextMenu(), draftviewproviders.view_draft_annotation.ViewProviderDraftAnnotation::setupContextMenu(), ArchGrid.ViewProviderArchGrid::setupContextMenu(), ArchMaterial._ViewProviderArchMaterial::setupContextMenu(), draftviewproviders.view_base.ViewProviderDraft::setupContextMenu(), ArchAxis._ViewProviderAxis::setupContextMenu(), ArchSchedule._ViewProviderArchSchedule::setupContextMenu(), ArchReference.ViewProviderArchReference::setupContextMenu(), ArchMaterial._ViewProviderArchMultiMaterial::setupContextMenu(), ArchSite._ViewProviderSite::setupContextMenu(), and ArchSectionPlane._ViewProviderSectionPlane::setupContextMenu().
keyPressEvent()
void ParameterValue::keyPressEvent (QKeyEvent * event) override protected
Invokes onDeleteSelectedItem() if the "Del" key was pressed.
Definition at line 750 of file DlgParameterImp.cpp.
References onDeleteSelectedItem().
onChangeSelectedItem [1/2]
void ParameterValue::onChangeSelectedItem () protected slot
Definition at line 777 of file DlgParameterImp.cpp.
Referenced by ParameterValue().
onChangeSelectedItem [2/2]
void ParameterValue::onChangeSelectedItem (QTreeWidgetItem * item, int col) protected slot
Changes the value of the leaf of the selected item.
Definition at line 770 of file DlgParameterImp.cpp.
onCreateBoolItem
void ParameterValue::onCreateBoolItem () protected slot
Creates and appends a new "boolean" leaf.
Definition at line 966 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::appendToGroup(), ParameterGrp::GetBoolMap(), importers.exportIFC::getText(), geoff_geometry::Normal(), toolbit-attributes::val, and Gui::validateInput().
Referenced by ParameterValue().
onCreateFloatItem
void ParameterValue::onCreateFloatItem () protected slot
Creates and appends a new "float" leaf.
Definition at line 925 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::appendToGroup(), ParameterGrp::GetFloatMap(), importers.exportIFC::getText(), geoff_geometry::Normal(), toolbit-attributes::val, and Gui::validateInput().
Referenced by ParameterValue().
onCreateIntItem
void ParameterValue::onCreateIntItem () protected slot
Creates and appends a new "integer" leaf.
Definition at line 839 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::appendToGroup(), ParameterGrp::GetIntMap(), importers.exportIFC::getText(), geoff_geometry::Normal(), toolbit-attributes::val, and Gui::validateInput().
Referenced by ParameterValue().
onCreateTextItem
void ParameterValue::onCreateTextItem () protected slot
Creates and appends a new "text" leaf.
Definition at line 800 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::appendToGroup(), ParameterGrp::GetASCIIMap(), importers.exportIFC::getText(), geoff_geometry::Normal(), toolbit-attributes::val, and Gui::validateInput().
Referenced by ParameterValue().
onCreateUIntItem
void ParameterValue::onCreateUIntItem () protected slot
Creates and appends a new "unsigned integer" leaf.
Definition at line 881 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::appendToGroup(), edit(), importers.exportIFC::getText(), Gui::Dialog::DlgInputDialogImp::getUIntBox(), ParameterGrp::GetUnsignedMap(), geoff_geometry::Normal(), Gui::Dialog::DlgInputDialogImp::UIntBox, toolbit-attributes::val, and Gui::validateInput().
Referenced by ParameterValue().
onDeleteSelectedItem
void ParameterValue::onDeleteSelectedItem () protected slot
Remove the underlying leaf from the parameter group. The selected item is also removed and destroyed.
Definition at line 782 of file DlgParameterImp.cpp.
Referenced by keyPressEvent(), and ParameterValue().
onRenameSelectedItem
void ParameterValue::onRenameSelectedItem () protected slot
Changes the name of the leaf of the selected item.
Definition at line 792 of file DlgParameterImp.cpp.
Referenced by ParameterValue().
resizeEvent()
void ParameterValue::resizeEvent (QResizeEvent * event) override protected
Definition at line 760 of file DlgParameterImp.cpp.
setCurrentGroup()
void ParameterValue::setCurrentGroup (const Base::Reference< ParameterGrp > & _hcGrp)
Sets the current parameter group that is displayed.
Definition at line 716 of file DlgParameterImp.cpp.
The documentation for this class was generated from the following files:
DlgParameterImp.h
DlgParameterImp.cpp