FreeCAD: importers.importIFCHelper Namespace Reference
importers.importIFCHelper Namespace Reference
Classes
class ProjectImporter
Functions
def dd2dms (dd)
def dms2dd (degrees, minutes, seconds, milliseconds=0)
def getPreferences ()
def buildRelProductsAnnotations (ifcfile, root_element='IfcProduct')
def buildRelProductRepresentation (ifcfile)
def buildRelAdditions (ifcfile)
def buildRelGroups (ifcfile)
def buildRelSubtractions (ifcfile)
def buildRelMattable (ifcfile)
def buildRelColors (ifcfile, prodrepr)
def buildRelProductColors (ifcfile, prodrepr)
def buildRelMaterialColors (ifcfile, prodrepr)
def getColorFromProduct (product)
def getColorFromMaterial (material)
def color2colorRGB (color_data)
def getColorFromStyledItem (styled_item)
def predefined_to_rgb (rgb_color)
def buildRelProperties (ifcfile)
def getIfcPropertySets (ifcfile, pid)
def getIfcProperties (ifcfile, pid, psets, d)
def getIfcPsetProperties (ifcfile, pid)
def getUnit (unit)
def getScaling (ifcfile)
def getRotation (entity)
def getPlacement (entity, scaling=1000)
def getVector (entity, scaling=1000)
def get2DShape (representation, scaling=1000, notext=False)
def getProfileCenterPoint (sweptsolid)
def isRectangle (verts)
def createFromProperties (propsets, ifcfile, parametrics)
def applyColorDict (doc, colordict=None)
def getParents (ifcobj)
def createAnnotation (annotation, doc, ifcscale, preferences)
Variables
dictionary PREDEFINED_RGB
bool DEBUG_prod_repr = False
bool DEBUG_prod_colors = False
Function Documentation
applyColorDict()
def importers.importIFCHelper.applyColorDict (doc, colordict = None)
applies the contents of a color dict to the objects in the given doc.
If no colordict is given, the doc Meta property is searched for a "colordict" entry.
Definition at line 1049 of file importIFCHelper.py.
buildRelAdditions()
def importers.importIFCHelper.buildRelAdditions (ifcfile)
Build the additions relation table.
Definition at line 242 of file importIFCHelper.py.
buildRelColors()
def importers.importIFCHelper.buildRelColors (ifcfile, prodrepr)
Build the colors relation table.
Returns all IfcStyledItem colors, material and product colors.
Returns
-------
dict
    A dictionary with `{id: (r,g,b), ...}` values.
Definition at line 300 of file importIFCHelper.py.
References SplineSurface.id.
buildRelGroups()
def importers.importIFCHelper.buildRelGroups (ifcfile)
Build the groups relation table.
Definition at line 254 of file importIFCHelper.py.
buildRelMaterialColors()
def importers.importIFCHelper.buildRelMaterialColors (ifcfile, prodrepr)
Definition at line 423 of file importIFCHelper.py.
buildRelMattable()
def importers.importIFCHelper.buildRelMattable (ifcfile)
Build the mattable relation table.
Definition at line 274 of file importIFCHelper.py.
buildRelProductColors()
def importers.importIFCHelper.buildRelProductColors (ifcfile, prodrepr)
Build the colors relation table from a product.
Returns
-------
dict
    A dictionary with `{id: (r,g,b), ...}` values.
Definition at line 370 of file importIFCHelper.py.
References Path.Base.SetupSheet.dict, importers.importIFCHelper.getColorFromStyledItem(), and SplineSurface.id.
buildRelProductRepresentation()
def importers.importIFCHelper.buildRelProductRepresentation (ifcfile)
Build the product/representations relation table.
Definition at line 213 of file importIFCHelper.py.
References Path.Post.scripts.uccnc_post.append(), and Path.Base.SetupSheet.dict.
buildRelProductsAnnotations()
def importers.importIFCHelper.buildRelProductsAnnotations (ifcfile, root_element = 'IfcProduct')
Build the products and annotations relation table.
Definition at line 195 of file importIFCHelper.py.
buildRelProperties()
def importers.importIFCHelper.buildRelProperties (ifcfile)
Builds and returns a dictionary of {object:[properties]} from an IFC file
Definition at line 599 of file importIFCHelper.py.
buildRelSubtractions()
def importers.importIFCHelper.buildRelSubtractions (ifcfile)
Build the subtractions relation table.
Definition at line 264 of file importIFCHelper.py.
color2colorRGB()
def importers.importIFCHelper.color2colorRGB (color_data)
Definition at line 450 of file importIFCHelper.py.
createAnnotation()
def importers.importIFCHelper.createAnnotation (annotation, doc, ifcscale, preferences)
creates an annotation object
Definition at line 1083 of file importIFCHelper.py.
References importers.importIFCHelper.get2DShape(), importers.importIFCHelper.getPlacement(), Arch.makeAxis(), Arch.makeAxisSystem(), and Path.Post.scripts.refactored_centroid_post.str.
createFromProperties()
def importers.importIFCHelper.createFromProperties (propsets, ifcfile, parametrics)
Creates a FreeCAD parametric object from a set of properties.
Definition at line 962 of file importIFCHelper.py.
dd2dms()
def importers.importIFCHelper.dd2dms (dd)
Convert decimal degrees to degrees, minutes, seconds.
Used in export.
Definition at line 50 of file importIFCHelper.py.
References KDL.abs().
Referenced by importers.exportIFC.createProduct().
dms2dd()
def importers.importIFCHelper.dms2dd (degrees, minutes, seconds, milliseconds = 0)
Convert degrees, minutes, seconds to decimal degrees.
Used in import.
Definition at line 68 of file importIFCHelper.py.
get2DShape()
def importers.importIFCHelper.get2DShape (representation, scaling = 1000, notext = False)
Returns a shape from a 2D IfcShapeRepresentation
if notext is True, no Draft text is created
Definition at line 777 of file importIFCHelper.py.
References DraftVecUtils.angle(), draftfunctions.svgshapes.getCircle(), getLine(), importers.importIFCHelper.getPlacement(), importers.importIFCHelper.getRotation(), and importers.importIFCHelper.getVector().
Referenced by importers.importIFCHelper.createAnnotation(), and importers.importIFCHelper.getProfileCenterPoint().
getColorFromMaterial()
def importers.importIFCHelper.getColorFromMaterial (material)
Definition at line 439 of file importIFCHelper.py.
References importers.importIFCHelper.getColorFromStyledItem().
getColorFromProduct()
def importers.importIFCHelper.getColorFromProduct (product)
Definition at line 428 of file importIFCHelper.py.
getColorFromStyledItem()
def importers.importIFCHelper.getColorFromStyledItem (styled_item)
Get color from the IfcStyledItem.
Returns
-------
float, float, float, int
    A tuple with the red, green, blue, and transparency values.
    If the `IfcStyledItem` is a `IfcDraughtingPreDefinedColour`
    the transparency is set to 0.
    The first three values range from 0 to 1.0, while the transparency
    varies from 0 to 100.
None
    Return `None` if `styled_item` is not of type `'IfcStyledItem'`
    or if there is any other problem getting a color.
Definition at line 464 of file importIFCHelper.py.
References importers.importIFCHelper.predefined_to_rgb().
Referenced by importers.importIFCHelper.buildRelProductColors(), and importers.importIFCHelper.getColorFromMaterial().
getIfcProperties()
def importers.importIFCHelper.getIfcProperties (ifcfile, pid, psets, d)
builds valid property values for FreeCAD
Definition at line 637 of file importIFCHelper.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by importers.importIFCHelper.getIfcPsetProperties().
getIfcPropertySets()
def importers.importIFCHelper.getIfcPropertySets (ifcfile, pid)
Returns a dictionary of {pset_id:[prop_id, prop_id...]} for an IFC object
Definition at line 621 of file importIFCHelper.py.
Referenced by importers.importIFCHelper.getIfcPsetProperties().
getIfcPsetProperties()
def importers.importIFCHelper.getIfcPsetProperties (ifcfile, pid)
directly build the property table from pid and ifcfile for FreeCAD
Definition at line 661 of file importIFCHelper.py.
References importers.importIFCHelper.getIfcProperties(), and importers.importIFCHelper.getIfcPropertySets().
getParents()
def importers.importIFCHelper.getParents (ifcobj)
finds the parent entities of an IFC entity
Definition at line 1069 of file importIFCHelper.py.
getPlacement()
def importers.importIFCHelper.getPlacement (entity, scaling = 1000)
returns a placement from the given entity
Definition at line 719 of file importIFCHelper.py.
References DraftVecUtils.getPlaneRotation(), and importers.importIFCHelper.getVector().
Referenced by importers.importIFCHelper.createAnnotation(), importers.importIFCHelper.get2DShape(), importers.importIFCHelper.getProfileCenterPoint(), Part::AttachExtension.isAttacherActive(), Part::AttachExtension.positionBySupport(), Path::Command.transform(), and Part::AttachExtension.updateSinglePropertyStatus().
getPreferences()
def importers.importIFCHelper.getPreferences ()
Retrieve the IFC preferences available in import and export.
MERGE_MODE_ARCH:
    0 = parametric BIM objects
    1 = non-parametric BIM objects
    2 = Part shapes
    3 = One compound per storey
Definition at line 77 of file importIFCHelper.py.
References Path.Post.scripts.uccnc_post.append().
getProfileCenterPoint()
def importers.importIFCHelper.getProfileCenterPoint (sweptsolid)
returns the center point of the profile of an extrusion
Definition at line 928 of file importIFCHelper.py.
References importers.importIFCHelper.get2DShape(), and importers.importIFCHelper.getPlacement().
getRotation()
def importers.importIFCHelper.getRotation (entity)
returns a FreeCAD rotation from an IfcProduct with a IfcMappedItem representation
Definition at line 708 of file importIFCHelper.py.
Referenced by importers.importIFCHelper.get2DShape(), and FCSphereSheetProjector.getRotation().
getScaling()
def importers.importIFCHelper.getScaling (ifcfile)
Return a scaling factor from the IFC file; units to mm.
Definition at line 690 of file importIFCHelper.py.
References importers.importIFCHelper.getUnit().
getUnit()
def importers.importIFCHelper.getUnit (unit)
Get the unit multiplier for different decimal prefixes.
Only for when the unit is METRE.
When no Prefix is provided, return 1000, that is, mm x 1000 = metre.
For other cases, return 1.0.
Definition at line 667 of file importIFCHelper.py.
Referenced by App::PropertyVector.getPathValue(), App::PropertyVector.getPyPathValue(), and importers.importIFCHelper.getScaling().
getVector()
def importers.importIFCHelper.getVector (entity, scaling = 1000)
returns a vector from the given entity
Definition at line 756 of file importIFCHelper.py.
Referenced by importers.importIFCHelper.get2DShape(), and importers.importIFCHelper.getPlacement().
isRectangle()
def importers.importIFCHelper.isRectangle (verts)
returns True if the given 4 vertices form a rectangle
Definition at line 945 of file importIFCHelper.py.
References KDL.abs().
predefined_to_rgb()
def importers.importIFCHelper.predefined_to_rgb (rgb_color)
Transform a predefined color name to its [r, g, b] representation.
TODO: at the moment it doesn't handle 'by layer'.
See: `IfcDraughtingPreDefinedColour` and `IfcPresentationLayerWithStyle`.
Definition at line 578 of file importIFCHelper.py.
Referenced by importers.importIFCHelper.getColorFromStyledItem().
Variable Documentation
DEBUG_prod_colors
bool importers.importIFCHelper.DEBUG_prod_colors = False
Definition at line 47 of file importIFCHelper.py.
DEBUG_prod_repr
bool importers.importIFCHelper.DEBUG_prod_repr = False
Definition at line 46 of file importIFCHelper.py.
PREDEFINED_RGB
dictionary importers.importIFCHelper.PREDEFINED_RGB
Initial value:
 =  {"black": (0, 0, 0),
                   "red": (1.0, 0, 0),
                   "green": (0, 1.0, 0),
                   "blue": (0, 0, 1.0),
                   "yellow": (1.0, 1.0, 0),
                   "magenta": (1.0, 0, 1.0),
                   "cyan": (0, 1.0, 1.0),
                   "white": (1.0, 1.0, 1.0)}
Definition at line 36 of file importIFCHelper.py.