FreeCAD: Gui::Flag Class Reference
Gui::Flag Class Reference
#include <Flag.h>
Public Member Functions
Flag (QWidget *parent=nullptr)
~Flag () override
QSize sizeHint () const override
void setOrigin (const SbVec3f &)
const SbVec3f & getOrigin () const
void drawLine (Gui::View3DInventorViewer *, int tox, int toy)
void setText (const QString &)
Protected Member Functions
void initializeGL () override
void resizeGL (int width, int height) override
void paintGL () override
void paintEvent (QPaintEvent *) override
void mouseMoveEvent (QMouseEvent *) override
void mousePressEvent (QMouseEvent *) override
void resizeEvent (QResizeEvent *) override
void contextMenuEvent (QContextMenuEvent *) override
Detailed Description
Author
Werner Mayer
Definition at line 59 of file Flag.h.
Constructor & Destructor Documentation
Flag()
Flag::Flag (QWidget * parent = nullptr)
Definition at line 45 of file Flag.cpp.
~Flag()
Flag::~Flag () override default
Member Function Documentation
contextMenuEvent()
void Flag::contextMenuEvent (QContextMenuEvent * e) override protected
Definition at line 157 of file Flag.cpp.
References SCL.SimpleDataTypes::e, NavigationIndicatorGui::menu, and Path.Op.Gui.Selection::select().
drawLine()
void Flag::drawLine (Gui::View3DInventorViewer * v, int tox, int toy)
Definition at line 96 of file Flag.cpp.
References SCL.SimpleDataTypes::f, buildPsets::p, RobotExample::pos, toolbit-attributes::s, and TestSpreadsheet::v.
Referenced by Gui::GLFlagWindow::paintGL().
getOrigin()
const SbVec3f & Flag::getOrigin () const
Definition at line 91 of file Flag.cpp.
Referenced by Gui::GLFlagWindow::paintGL().
initializeGL()
void Flag::initializeGL () override protected
Definition at line 54 of file Flag.cpp.
References SCL.SimpleDataTypes::c, glClearColor, and buildPsets::p.
mouseMoveEvent()
void Flag::mouseMoveEvent (QMouseEvent * e) override protected
Definition at line 130 of file Flag.cpp.
References SCL.SimpleDataTypes::e, Path.Post.scripts.opensbp_post::move(), and OfflineRenderingUtils::viewer().
mousePressEvent()
void Flag::mousePressEvent (QMouseEvent * e) override protected
Definition at line 145 of file Flag.cpp.
References SCL.SimpleDataTypes::e.
paintEvent()
void Flag::paintEvent (QPaintEvent * e) override protected
Definition at line 66 of file Flag.cpp.
References SCL.SimpleDataTypes::c, SCL.SimpleDataTypes::e, and buildPsets::p.
paintGL()
void Flag::paintGL () override protected
Definition at line 61 of file Flag.cpp.
resizeEvent()
void Flag::resizeEvent (QResizeEvent * e) override protected
Definition at line 125 of file Flag.cpp.
References SCL.SimpleDataTypes::e.
resizeGL()
void Flag::resizeGL (int width, int height) override protected
Definition at line 80 of file Flag.cpp.
setOrigin()
void Flag::setOrigin (const SbVec3f & v)
Definition at line 86 of file Flag.cpp.
References TestSpreadsheet::v.
Referenced by InspectionGui::ViewProviderProxyObject::addFlag().
setText()
void Flag::setText (const QString & t)
Definition at line 120 of file Flag.cpp.
References InitGui::t.
Referenced by InspectionGui::ViewProviderProxyObject::addFlag(), MeshGui::ViewProviderMesh::faceInfoCallback(), and src.Mod.AddonManager.Widgets.addonmanager_widget_readme_browser.WidgetReadmeBrowser::setMarkdown().
sizeHint()
QSize Flag::sizeHint () const override
Definition at line 176 of file Flag.cpp.
References src.Mod.PartDesign.fcgear.svggear::w.
The documentation for this class was generated from the following files:
Flag.h
Flag.cpp