FreeCAD: GCS::Ellipse Class Reference
GCS::Ellipse Class Reference
#include <Geo.h>
Public Member Functions
Ellipse ()
~Ellipse () override
double getRadMaj (const DeriVector2 &center, const DeriVector2 &f1, double b, double db, double &ret_dRadMaj) const override
double getRadMaj (double *derivparam, double &ret_dRadMaj) const override
double getRadMaj () const override
DeriVector2 CalculateNormal (const Point &p, const double *derivparam=nullptr) const override
DeriVector2 Value (double u, double du, const double *derivparam=nullptr) const override
Value: returns point (vector) given the value of parameter.
int PushOwnParams (VEC_pD &pvec) override
void ReconstructOnNewPvec (VEC_pD &pvec, int &cnt) override
Ellipse * Copy () override
Public Member Functions inherited from GCS::MajorRadiusConic
~MajorRadiusConic () override
Public Member Functions inherited from GCS::Curve
virtual ~Curve ()
virtual DeriVector2 CalculateNormal (const double *param, const double *derivparam=nullptr) const
Public Attributes
Point center
Point focus1
double * radmin
Detailed Description
Definition at line 290 of file Geo.h.
Constructor & Destructor Documentation
Ellipse()
GCS::Ellipse::Ellipse () inline
Definition at line 293 of file Geo.h.
Referenced by Copy().
~Ellipse()
GCS::Ellipse::~Ellipse () inline override
Definition at line 297 of file Geo.h.
Member Function Documentation
CalculateNormal()
DeriVector2 GCS::Ellipse::CalculateNormal (const Point & p, const double * derivparam = nullptr) const override virtual
Implements GCS::Curve.
Definition at line 311 of file Geo.cpp.
References center, focus1, GCS::DeriVector2::getNormalized(), GCS::DeriVector2::linCombi(), buildPsets::p, GCS::DeriVector2::subtr(), and GCS::DeriVector2::sum().
Copy()
Ellipse * GCS::Ellipse::Copy () override virtual
Implements GCS::Curve.
Reimplemented in GCS::ArcOfEllipse.
Definition at line 394 of file Geo.cpp.
References Ellipse().
getRadMaj() [1/3]
double GCS::Ellipse::getRadMaj () const override virtual
Implements GCS::MajorRadiusConic.
Definition at line 305 of file Geo.cpp.
References getRadMaj().
Referenced by getRadMaj(), and Value().
getRadMaj() [2/3]
double GCS::Ellipse::getRadMaj (const DeriVector2 & center, const DeriVector2 & f1, double b, double db, double & ret_dRadMaj) const override virtual
Implements GCS::MajorRadiusConic.
Definition at line 279 of file Geo.cpp.
References SCL.SimpleDataTypes::b, center, GCS::DeriVector2::length(), and GCS::DeriVector2::subtr().
getRadMaj() [3/3]
double GCS::Ellipse::getRadMaj (double * derivparam, double & ret_dRadMaj) const override virtual
Implements GCS::MajorRadiusConic.
Definition at line 297 of file Geo.cpp.
References SCL.SimpleDataTypes::c, center, focus1, getRadMaj(), and radmin.
PushOwnParams()
int GCS::Ellipse::PushOwnParams (VEC_pD & pvec) override virtual
Implements GCS::Curve.
Reimplemented in GCS::ArcOfEllipse.
Definition at line 366 of file Geo.cpp.
References center, focus1, radmin, GCS::Point::x, and GCS::Point::y.
Referenced by GCS::ConstraintEllipseTangentLine::ConstraintEllipseTangentLine(), GCS::ConstraintInternalAlignmentPoint2Ellipse::ConstraintInternalAlignmentPoint2Ellipse(), and GCS::ArcOfEllipse::PushOwnParams().
ReconstructOnNewPvec()
void GCS::Ellipse::ReconstructOnNewPvec (VEC_pD & pvec, int & cnt) override virtual
Implements GCS::Curve.
Reimplemented in GCS::ArcOfEllipse.
Definition at line 381 of file Geo.cpp.
References center, focus1, radmin, GCS::Point::x, and GCS::Point::y.
Referenced by GCS::ArcOfEllipse::ReconstructOnNewPvec().
Value()
DeriVector2 GCS::Ellipse::Value (double u, double du, const double * derivparam = nullptr) const override virtual
Value: returns point (vector) given the value of parameter.
Parameters
u value of parameter
du derivative of parameter by derivparam
derivparam pointer to sketch parameter to calculate the derivative for
Returns
Reimplemented from GCS::Curve.
Definition at line 331 of file Geo.cpp.
References a, SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::c, center, KDL::cos(), focus1, GCS::DeriVector2::getNormalized(), getRadMaj(), GCS::DeriVector2::multD(), radmin, GCS::DeriVector2::rotate90ccw(), KDL::sin(), GCS::DeriVector2::subtr(), GCS::DeriVector2::sum(), and buildPsets::u.
Member Data Documentation
center
Point GCS::Ellipse::center
Definition at line 299 of file Geo.h.
Referenced by CalculateNormal(), Path.Dressup.Gui.AxisMap.ObjectDressup::execute(), getRadMaj(), Path.Dressup.Gui.AxisMap.ObjectDressup::onChanged(), PushOwnParams(), ReconstructOnNewPvec(), and Value().
focus1
Point GCS::Ellipse::focus1
Definition at line 300 of file Geo.h.
Referenced by CalculateNormal(), getRadMaj(), PushOwnParams(), ReconstructOnNewPvec(), and Value().
radmin
double* GCS::Ellipse::radmin
Definition at line 301 of file Geo.h.
Referenced by GCS::System::addConstraintEqualRadii(), getRadMaj(), PushOwnParams(), ReconstructOnNewPvec(), and Value().
The documentation for this class was generated from the following files:
Geo.h
Geo.cpp