FreeCAD: ArchSite Namespace Reference
ArchSite Namespace Reference
Arch
The Site object and tools.
Classes
class _Site
class _ViewProviderSite
class Compass
Functions
def toNode (shape)
def makeSolarDiagram (longitude, latitude, scale=1, complete=False, tz=None)
def makeWindRose (epwfile, scale=1, sectors=24)
Variables
int COMPASS_POINTER_LENGTH = 1000
int COMPASS_POINTER_WIDTH = 100
Detailed Description
The Site object and tools.
This module provides tools to build Site objects. Sites are containers for Arch objects, and also define a terrain surface
Function Documentation
makeSolarDiagram()
def ArchSite.makeSolarDiagram (longitude, latitude, scale = 1, complete = False, tz = None)
makeSolarDiagram(longitude,latitude,[scale,complete,tz]):
returns a solar diagram as a pivy node. If complete is
True, the 12 months are drawn. Tz is the timezone related to
UTC (ex: -3 = UTC-3)
Definition at line 88 of file ArchSite.py.
References Path.Post.scripts.uccnc_post.append(), Path.Post.scripts.refactored_centroid_post.str, and toNode().
makeWindRose()
def ArchSite.makeWindRose (epwfile, scale = 1, sectors = 24)
makeWindRose(site,sectors):
returns a wind rose diagram as a pivy node
Definition at line 273 of file ArchSite.py.
References KDL.abs(), KDL.max(), KDL.min(), and toNode().
toNode()
def ArchSite.toNode (shape)
builds a linear pivy node from a shape
Definition at line 63 of file ArchSite.py.
Referenced by makeSolarDiagram(), and makeWindRose().
Variable Documentation
COMPASS_POINTER_LENGTH
int ArchSite.COMPASS_POINTER_LENGTH = 1000
Definition at line 334 of file ArchSite.py.
COMPASS_POINTER_WIDTH
int ArchSite.COMPASS_POINTER_WIDTH = 100
Definition at line 335 of file ArchSite.py.