FreeCAD: Collector Class Reference
Collector Class Reference
Public Member Functions
Collector ()=default
virtual ~Collector ()=default
virtual void collect (Quantity value)
virtual Quantity getQuantity () const
Protected Attributes
bool first {true}
Quantity q
Detailed Description
Definition at line 1873 of file Expression.cpp.
Constructor & Destructor Documentation
Collector()
Collector::Collector () default
~Collector()
virtual Collector::~Collector () virtual default
Member Function Documentation
collect()
virtual void Collector::collect (Quantity value) inline virtual
Reimplemented in MaxCollector, MinCollector, CountCollector, StdDevCollector, AverageCollector, and SumCollector.
Definition at line 1877 of file Expression.cpp.
References Base::Quantity::getUnit().
Referenced by SumCollector::collect(), AverageCollector::collect(), StdDevCollector::collect(), CountCollector::collect(), MinCollector::collect(), and MaxCollector::collect().
getQuantity()
virtual Quantity Collector::getQuantity () const inline virtual
Reimplemented in CountCollector, StdDevCollector, and AverageCollector.
Definition at line 1881 of file Expression.cpp.
Referenced by materialtests.TestMaterials.MaterialTestCases::test2DArray(), materialtests.TestMaterials.MaterialTestCases::test3DArray(), materialtests.TestMaterials.MaterialTestCases::testCalculiXSteel(), and materialtests.TestMaterialCreation.MaterialCreationTestCases::testCreateMaterial().
Member Data Documentation
first
bool Collector::first {true} protected
Definition at line 1885 of file Expression.cpp.
Referenced by draftguitools.gui_layers.Layers_Delegate::createEditor(), bimcommands.BimLayers.BIM_Layers_Delegate::createEditor(), draftguitools.gui_layers.Layers_Delegate::setEditorData(), and bimcommands.BimLayers.BIM_Layers_Delegate::setEditorData().
q
Quantity Collector::q protected
Definition at line 1886 of file Expression.cpp.
Referenced by Path.Main.Gui.Camotics.CamoticsSimulation::callback(), Path.Main.Gui.Camotics.CamoticsSimulation::isDone(), and Path.Main.Gui.Camotics.CamoticsSimulation::worker().
The documentation for this class was generated from the following file:
Expression.cpp