FreeCAD: Gui::QtTools Class Reference
Gui::QtTools Class Reference
The QtTools class Helper class to reduce adding a lot of extra QT_VERSION checks to client code.
#include <Tools.h>
Static Public Member Functions
static int horizontalAdvance (const QFontMetrics &fm, QChar ch)
static int horizontalAdvance (const QFontMetrics &fm, const QString &text, int len=-1)
static bool matches (QKeyEvent *ke, const QKeySequence &ks)
Detailed Description
The QtTools class Helper class to reduce adding a lot of extra QT_VERSION checks to client code.
Definition at line 57 of file Gui/Tools.h.
Member Function Documentation
horizontalAdvance() [1/2]
static int Gui::QtTools::horizontalAdvance (const QFontMetrics & fm, const QString & text, int len = -1) inline static
Definition at line 86 of file Gui/Tools.h.
horizontalAdvance() [2/2]
static int Gui::QtTools::horizontalAdvance (const QFontMetrics & fm, QChar ch) inline static
Definition at line 79 of file Gui/Tools.h.
Referenced by TechDrawGui::QGIView::calculateFontPixelWidth(), Gui::Action::createToolTip(), Gui::Dialog::DlgSettingsColorGradientImp::DlgSettingsColorGradientImp(), Gui::ViewProviderAnnotationLabel::drawImage(), Gui::TextEditor::lineNumberAreaWidth(), Gui::PropertyListEditor::lineNumberAreaWidth(), Gui::TextEditor::OnChange(), Gui::DockWnd::ReportOutput::OnChange(), SqueezeLabel::paintEvent(), Gui::renderDevBuildWarning(), Gui::FileChooser::setButtonText(), Gui::LabelEditor::setButtonText(), Gui::Dialog::DlgSettingsEditor::setEditorTabWidth(), Gui::AlignmentView::setupHeadUpDisplay(), Gui::QuantitySpinBox::sizeForText(), Gui::SplashScreen::splashImage(), TechDrawGui::QGIViewBalloon::updateBalloon(), and PartGui::FaceAppearances::updatePanel().
matches()
static bool Gui::QtTools::matches (QKeyEvent * ke, const QKeySequence & ks) inline static
Definition at line 93 of file Gui/Tools.h.
Referenced by PartDesignGui::TaskDressUpParameters::event(), and PartDesignGui::TaskDressUpParameters::keyPressEvent().
The documentation for this class was generated from the following file:
Gui/Tools.h