FreeCAD: GCS::ConstraintL2LAngle Class Reference
GCS::ConstraintL2LAngle Class Reference
#include <Constraints.h>
Public Member Functions
ConstraintL2LAngle (Line &l1, Line &l2, double *a)
ConstraintL2LAngle (Point &l1p1, Point &l1p2, Point &l2p1, Point &l2p2, double *a)
ConstraintType getTypeId () override
void rescale (double coef=1.) override
double error () override
double grad (double *) override
double maxStep (MAP_pD_D &dir, double lim=1.) override
Public Member Functions inherited from GCS::Constraint
Constraint ()
virtual ~Constraint ()
VEC_pD params ()
void redirectParams (const MAP_pD_pD &redirectionmap)
void revertParams ()
void setTag (int tagId)
int getTag ()
void setDriving (bool isdriving)
bool isDriving () const
void setInternalAlignment (Alignment isinternalalignment)
Alignment isInternalAlignment () const
int findParamInPvec (double *param)
Additional Inherited Members
Public Types inherited from GCS::Constraint
enum Alignment { Alignment::NoInternalAlignment, Alignment::InternalAlignment }
Protected Attributes inherited from GCS::Constraint
VEC_pD origpvec
VEC_pD pvec
double scale
int tag
bool pvecChangedFlag
bool driving
Alignment internalAlignment
Detailed Description
Definition at line 694 of file Constraints.h.
Constructor & Destructor Documentation
ConstraintL2LAngle() [1/2]
GCS::ConstraintL2LAngle::ConstraintL2LAngle (Line & l1, Line & l2, double * a)
Definition at line 1334 of file Constraints.cpp.
References a, src.Mod.PartDesign.Scripts.Gear::l1, src.Mod.PartDesign.Scripts.Gear::l2, GCS::Constraint::origpvec, GCS::Constraint::pvec, and rescale().
ConstraintL2LAngle() [2/2]
GCS::ConstraintL2LAngle::ConstraintL2LAngle (Point & l1p1, Point & l1p2, Point & l2p1, Point & l2p2, double * a)
Definition at line 1349 of file Constraints.cpp.
References a, GCS::Constraint::origpvec, GCS::Constraint::pvec, rescale(), GCS::Point::x, and GCS::Point::y.
Member Function Documentation
error()
double GCS::ConstraintL2LAngle::error () override virtual
Reimplemented from GCS::Constraint.
Definition at line 1378 of file Constraints.cpp.
References a, KDL::atan2(), KDL::cos(), and KDL::sin().
getTypeId()
ConstraintType GCS::ConstraintL2LAngle::getTypeId () override virtual
Reimplemented from GCS::Constraint.
Definition at line 1368 of file Constraints.cpp.
References GCS::L2LAngle.
grad()
double GCS::ConstraintL2LAngle::grad (double * param) override virtual
Reimplemented from GCS::Constraint.
Definition at line 1392 of file Constraints.cpp.
References a, KDL::atan2(), KDL::cos(), Init::param, and KDL::sin().
maxStep()
double GCS::ConstraintL2LAngle::maxStep (MAP_pD_D & dir, double lim = 1.) override virtual
Reimplemented from GCS::Constraint.
Definition at line 1445 of file Constraints.cpp.
References KDL::abs(), KDL::min(), and GCS::pi_18.
rescale()
void GCS::ConstraintL2LAngle::rescale (double coef = 1.) override virtual
Reimplemented from GCS::Constraint.
Definition at line 1373 of file Constraints.cpp.
Referenced by ConstraintL2LAngle().
The documentation for this class was generated from the following files:
Constraints.h
Constraints.cpp