FreeCAD: WireJoiner::WireJoinerP Class Reference
WireJoiner::WireJoinerP Class Reference
Classes
struct BoxGetter
struct EdgeInfo
struct EdgeSet
struct IntersectInfo
struct PntGetter
struct SplitInfo
struct StackInfo
struct VectorSet
struct VertexInfo
struct WireInfo
struct WireSet
Public Types
using Box = bg::model::box< gp_Pnt >
using Edges = std::list< EdgeInfo >
Public Member Functions
bool checkBBox (const Bnd_Box &box) const
WireJoinerP ()
bool getBBox (const TopoDS_Shape &eForBBox, Bnd_Box &bound)
bool getBBox (const TopoDS_Shape &eForBBox, Box &box)
Handle (BRepTools_History) aHistory
const Bnd_Box & getWireBound (const WireInfo &wireInfo) const
bool initWireInfoWireClosed (const WireInfo &wireInfo)
bool initWireInfoFaceDone (WireInfo &wireInfo)
bool initWireInfo (WireInfo &wireInfo)
bool isInside (const WireInfo &wireInfo, gp_Pnt &pt) const
bool isOutside (const WireInfo &wireInfo, gp_Pnt &pt) const
Handle (ShapeExtend_WireData) wireData
void clear ()
Edges::iterator remove (Edges::iterator it)
void remove (EdgeInfo *info)
void add (Edges::iterator it)
int add (const TopoDS_Edge &eToAdd, bool queryBBox=false)
int add (const TopoDS_Edge &eToAdd, bool queryBBox, Edges::iterator &it)
bool addNoDuplicates (const TopoDS_Edge &eToAdd, TopoDS_Vertex &v2, TopoDS_Edge &ev2, const bool isLinear, const VertexInfo &vinfo, std::unique_ptr< Geometry > &geo)
bool addValidEdges (const TopoDS_Edge &eToAdd, const gp_Pnt p1, const double tol, TopoDS_Vertex &v1, TopoDS_Edge &ev1, const gp_Pnt p2, TopoDS_Vertex &v2, TopoDS_Edge &ev2, const bool isLinear)
bool add (const TopoDS_Edge &eToAdd, bool queryBBox, const Box &bbox, Edges::iterator &it)
void add (const TopoDS_Shape &shape, bool queryBBox=false)
void joinMakeWire (const int idx, BRepBuilderAPI_MakeWire &mkWire, const Edges::iterator it, bool &done)
void join ()
void checkSelfIntersection (const EdgeInfo &info, std::set< IntersectInfo > &params) const
bool checkIntersectionPlanar (const EdgeInfo &info, const EdgeInfo &other, std::set< IntersectInfo > &params1, std::set< IntersectInfo > &params2)
void checkIntersection (const EdgeInfo &info, const EdgeInfo &other, std::set< IntersectInfo > &params1, std::set< IntersectInfo > &params2)
void pushIntersection (std::set< IntersectInfo > &params, double param, const gp_Pnt &pt, const TopoDS_Shape &shape)
void splitEdgesMakeEdge (const std::set< IntersectInfo >::iterator &itParam, const EdgeInfo &info, std::vector< SplitInfo > &splits, std::set< IntersectInfo >::iterator &itPrevParam, const TopoDS_Shape &intersectShape)
void splitEdgesMakeEdges (std::set< IntersectInfo >::iterator &itParam, const std::set< IntersectInfo > &params, const EdgeInfo &info, std::vector< SplitInfo > &splits)
void splitEdges ()
void findSuperEdgeFromAdjacent (std::deque< VertexInfo > &vertices, const int direction)
void findSuperEdge (std::deque< VertexInfo > &vertices, const Edges::iterator it)
void findSuperEdgesUpdateFirst (std::deque< VertexInfo > vertices)
void findSuperEdges ()
void buildAdjacentListPopulate ()
void buildAdjacentListSkipEdges ()
void buildAdjacentList ()
void findClosedWires (bool tightBound=false)
void checkWireInfo (const WireInfo &wireInfo)
void _findClosedWiresBeginEdge (const std::shared_ptr< WireInfo > &wireInfo, const EdgeInfo &beginInfo, int &idx)
int _findClosedWiresWithExisting (int *idxVertex, const std::shared_ptr< WireInfo > &wireInfo, int *const stackPos, bool &proceed, const VertexInfo &vinfo, const int ic, StackInfo &stackBack, const EdgeInfo &beginInfo, EdgeInfo &info)
void _findClosedWiresUpdateStack (int *idxVertex, const std::shared_ptr< WireInfo > &wireInfo, int *stackPos, const EdgeInfo *currentInfo, const int currentIdx, bool &proceed, const EdgeInfo &beginInfo)
bool _findClosedWiresUpdateEdges (VertexInfo &currentVertex, gp_Pnt &pend, EdgeInfo *currentInfo, int &currentIdx, const size_t stackEnd)
bool _findClosedWiresIsClosed (const VertexInfo &beginVertex, const TopoDS_Wire &wire, const EdgeInfo &beginInfo)
TopoDS_Wire _findClosedWires (VertexInfo beginVertex, VertexInfo currentVertex, int *idxVertex=nullptr, const std::shared_ptr< WireInfo > &wireInfo=std::shared_ptr< WireInfo >(), int *stackPos=nullptr)
void findTightBoundSplitWire (const std::shared_ptr< WireInfo > &wireInfo, const EdgeInfo &beginInfo, const std::vector< VertexInfo > &wireVertices, std::shared_ptr< WireInfo > &splitWire, const int idxV, int &idxStart, const int idxEnd)
void findTightBoundWithSplit (const std::vector< VertexInfo > &wireVertices, const int idxV, const std::shared_ptr< WireInfo > &splitWire, const int idxStart, const int idxEnd, const int stackPos, const int stackStart)
void findTightBoundByVertices (EdgeInfo &beginInfo, const std::vector< VertexInfo > &wireVertices, int &idxV, const int iteration2, const gp_Pnt &pstart, const std::shared_ptr< WireInfo > &wireInfo, const VertexInfo &beginVertex, std::shared_ptr< WireInfo > &newWire)
void findTightBoundUpdateVertices (EdgeInfo &beginInfo)
void findTightBound ()
void exhaustTightBoundUpdateVertex (const int iteration2, const VertexInfo &beginVertex, const int idxV, const gp_Pnt &pstart, const std::vector< VertexInfo > &wireVertices, std::shared_ptr< WireInfo > &newWire, const std::shared_ptr< WireInfo > &wireInfo)
void exhaustTightBoundUpdateEdge (const int iteration2, const VertexInfo &beginVertex, const std::vector< VertexInfo > &wireVertices, const gp_Pnt &pstart, std::shared_ptr< WireInfo > &wireInfo)
void exhaustTightBoundWithAdjacent (const EdgeInfo &info, int &iteration2, const VertexInfo beginVertex, const EdgeInfo *check)
void exhaustTightBoundUpdateWire (const EdgeInfo &info, int &iteration2)
void exhaustTightBound ()
void printHistoryInit (const Handle_BRepTools_History &newHistory, const std::vector< TopoShape > &inputEdges)
void printHistoryFinal ()
TopoDS_Wire makeCleanWire (bool fixGap=true)
template<class T >
void printHistoryOfShape (const Handle(BRepTools_History)&hist, const T &shape)
template<class T >
void printHistory (Handle(BRepTools_History) hist, const T &input)
bool canShowShape (int idx=-1, bool forced=false) const
void showShape (const EdgeInfo *info, const char *name, int idx=-1, bool forced=false) const
void showShape (WireInfo &wireInfo, const char *name, int idx=-1, bool forced=false)
void showShape (const TopoDS_Shape &sToShow, const char *name, int idx=-1, bool forced=false) const
void buildClosedWire ()
void build ()
void addWire (std::shared_ptr< WireInfo > &wireInfo)
bool getOpenWires (TopoShape &shape, const char *op, bool noOriginal)
bool getResultWires (TopoShape &shape, const char *op)
Static Public Member Functions
static bool checkIntersectionEdgeDone (const BRepBuilderAPI_MakeEdge &mkEdge)
static bool checkIntersectionWireDone (const BRepBuilderAPI_MakeWire &mkWire)
static bool checkIntersectionMakeWire (const EdgeInfo &info, const EdgeInfo &other, int &idx, TopoDS_Wire &wire)
static bool checkIntersectionFaceDone (const BRepBuilderAPI_MakeFace &mkFace)
Public Attributes
double myTol = Precision::Confusion()
double myTol2 = myTol * myTol
double myAngularTol = Precision::Angular()
bool doSplitEdge = true
bool doMergeEdge = true
bool doOutline = false
bool doTightBound = true
std::string catchObject
int catchIteration {}
int iteration = 0
Edges edges {}
std::map< EdgeInfo *, Edges::iterator > edgesTable {}
std::vector< StackInfo > stack {}
std::vector< VertexInfo > vertexStack {}
std::vector< VertexInfo > tmpVertices {}
std::vector< VertexInfo > adjacentList {}
EdgeSet edgeSet
WireSet wireSet
bgi::rtree< VertexInfo, RParameters, PntGetter > vmap {}
bgi::rtree< Edges::iterator, RParameters, BoxGetter > boxMap {}
BRep_Builder builder
TopoDS_Compound compound
std::unordered_set< TopoShape, ShapeHasher, ShapeHasher > sourceEdges {}
std::vector< TopoShape > sourceEdgeArray {}
TopoDS_Compound openWireCompound
Detailed Description
Definition at line 111 of file WireJoiner.cpp.
Member Typedef Documentation
Box
using WireJoiner::WireJoinerP::Box = bg::model::box<gp_Pnt>
Definition at line 125 of file WireJoiner.cpp.
Edges
using WireJoiner::WireJoinerP::Edges = std::list<EdgeInfo>
Definition at line 394 of file WireJoiner.cpp.
Constructor & Destructor Documentation
WireJoinerP()
WireJoiner::WireJoinerP::WireJoinerP () inline
Definition at line 142 of file WireJoiner.cpp.
Member Function Documentation
_findClosedWires()
TopoDS_Wire WireJoiner::WireJoinerP::_findClosedWires (VertexInfo beginVertex, VertexInfo currentVertex, int * idxVertex = nullptr, const std::shared_ptr< WireInfo > & wireInfo = std::shared_ptr<WireInfo>(), int * stackPos = nullptr) inline
Definition at line 1966 of file WireJoiner.cpp.
References _findClosedWiresIsClosed(), _findClosedWiresUpdateEdges(), _findClosedWiresUpdateStack(), Base::SequencerBase::checkAbort(), WireJoiner::WireJoinerP::VertexInfo::edgeInfo(), Path.Log::info(), Base::SequencerBase::Instance(), WireJoiner::WireJoinerP::VertexInfo::it, iteration, WireJoiner::WireJoinerP::EdgeInfo::iteration, makeCleanWire(), myTol2, src.Mod.PartDesign.Scripts.Gear::proceed(), WireJoiner::WireJoinerP::VertexInfo::pt(), WireJoiner::WireJoinerP::VertexInfo::ptOther(), WireJoiner::WireJoinerP::EdgeInfo::shape(), showShape(), stack, WireJoiner::WireJoinerP::VertexInfo::start, and vertexStack.
Referenced by exhaustTightBoundUpdateVertex(), exhaustTightBoundWithAdjacent(), findClosedWires(), and findTightBoundByVertices().
_findClosedWiresBeginEdge()
void WireJoiner::WireJoinerP::_findClosedWiresBeginEdge (const std::shared_ptr< WireInfo > & wireInfo, const EdgeInfo & beginInfo, int & idx) inline
Definition at line 1746 of file WireJoiner.cpp.
References Path.Log::info(), iteration, showShape(), stack, and vertexStack.
Referenced by _findClosedWiresWithExisting().
_findClosedWiresIsClosed()
bool WireJoiner::WireJoinerP::_findClosedWiresIsClosed (const VertexInfo & beginVertex, const TopoDS_Wire & wire, const EdgeInfo & beginInfo) inline
Definition at line 1943 of file WireJoiner.cpp.
References FC_WARN, Path.Log::info(), iteration, WireJoiner::WireJoinerP::EdgeInfo::shape(), showShape(), stack, WireJoiner::WireJoinerP::VertexInfo::start, and vertexStack.
Referenced by _findClosedWires().
_findClosedWiresUpdateEdges()
bool WireJoiner::WireJoinerP::_findClosedWiresUpdateEdges (VertexInfo & currentVertex, gp_Pnt & pend, EdgeInfo * currentInfo, int & currentIdx, const size_t stackEnd) inline
Definition at line 1901 of file WireJoiner.cpp.
References WireJoiner::WireJoinerP::VertexInfo::edgeInfo(), edgeSet, WireJoiner::WireJoinerP::VectorSet< T >::empty(), WireJoiner::WireJoinerP::VectorSet< T >::erase(), WireJoiner::WireJoinerP::VectorSet< T >::insert(), iteration, WireJoiner::WireJoinerP::VertexInfo::ptOther(), showShape(), stack, WireJoiner::WireJoinerP::VertexInfo::start, vertexStack, WireJoiner::WireJoinerP::EdgeInfo::wireInfo, and wireSet.
Referenced by _findClosedWires().
_findClosedWiresUpdateStack()
void WireJoiner::WireJoinerP::_findClosedWiresUpdateStack (int * idxVertex, const std::shared_ptr< WireInfo > & wireInfo, int * stackPos, const EdgeInfo * currentInfo, const int currentIdx, bool & proceed, const EdgeInfo & beginInfo) inline
Definition at line 1826 of file WireJoiner.cpp.
References _findClosedWiresWithExisting(), adjacentList, WireJoiner::WireJoinerP::VectorSet< T >::contains(), edgeSet, WireJoiner::WireJoinerP::VectorSet< T >::empty(), SplineSurface::i, Path.Log::info(), WireJoiner::WireJoinerP::EdgeInfo::iStart, iteration, src.Mod.PartDesign.Scripts.Gear::proceed(), showShape(), stack, vertexStack, WireJoiner::WireJoinerP::EdgeInfo::wireInfo2, and wireSet.
Referenced by _findClosedWires().
_findClosedWiresWithExisting()
int WireJoiner::WireJoinerP::_findClosedWiresWithExisting (int * idxVertex, const std::shared_ptr< WireInfo > & wireInfo, int *const stackPos, bool & proceed, const VertexInfo & vinfo, const int ic, StackInfo & stackBack, const EdgeInfo & beginInfo, EdgeInfo & info) inline
Definition at line 1775 of file WireJoiner.cpp.
References _findClosedWiresBeginEdge(), adjacentList, WireJoiner::WireJoinerP::StackInfo::iCurrent, WireJoiner::WireJoinerP::StackInfo::iEnd, Path.Log::info(), isOutside(), WireJoiner::WireJoinerP::VertexInfo::it, iteration, src.Mod.PartDesign.Scripts.Gear::proceed(), showShape(), stack, WireJoiner::WireJoinerP::VertexInfo::start, and vertexStack.
Referenced by _findClosedWiresUpdateStack().
add() [1/5]
bool WireJoiner::WireJoinerP::add (const TopoDS_Edge & eToAdd, bool queryBBox, const Box & bbox, Edges::iterator & it) inline
Definition at line 814 of file WireJoiner.cpp.
References add(), addValidEdges(), FirstVertex(), getEndPoints(), LastVertex(), KDL::max(), myTol, myTol2, showShape(), sourceEdges, Path.Geom::Tolerance, draftgeoutils.general::v1(), and vmap.
add() [2/5]
int WireJoiner::WireJoinerP::add (const TopoDS_Edge & eToAdd, bool queryBBox, Edges::iterator & it) inline
Definition at line 734 of file WireJoiner.cpp.
References add(), getBBox(), and showShape().
add() [3/5]
int WireJoiner::WireJoinerP::add (const TopoDS_Edge & eToAdd, bool queryBBox = false) inline
Definition at line 728 of file WireJoiner.cpp.
References add().
add() [4/5]
void WireJoiner::WireJoinerP::add (const TopoDS_Shape & shape, bool queryBBox = false) inline
Definition at line 898 of file WireJoiner.cpp.
References add().
add() [5/5]
void WireJoiner::WireJoinerP::add (Edges::iterator it) inline
Definition at line 718 of file WireJoiner.cpp.
References boxMap, showShape(), and vmap.
Referenced by add(), build(), and splitEdges().
addNoDuplicates()
bool WireJoiner::WireJoinerP::addNoDuplicates (const TopoDS_Edge & eToAdd, TopoDS_Vertex & v2, TopoDS_Edge & ev2, const bool isLinear, const VertexInfo & vinfo, std::unique_ptr< Geometry > & geo) inline
Definition at line 746 of file WireJoiner.cpp.
References WireJoiner::WireJoinerP::VertexInfo::edge(), WireJoiner::WireJoinerP::VertexInfo::edgeInfo(), WireJoiner::WireJoinerP::EdgeInfo::geometry(), WireJoiner::WireJoinerP::EdgeInfo::isLinear, myAngularTol, myTol, WireJoiner::WireJoinerP::VertexInfo::otherVertex(), and showShape().
Referenced by addValidEdges().
addValidEdges()
bool WireJoiner::WireJoinerP::addValidEdges (const TopoDS_Edge & eToAdd, const gp_Pnt p1, const double tol, TopoDS_Vertex & v1, TopoDS_Edge & ev1, const gp_Pnt p2, TopoDS_Vertex & v2, TopoDS_Edge & ev2, const bool isLinear) inline
Definition at line 776 of file WireJoiner.cpp.
References addNoDuplicates(), canShowShape(), FC_MSG, draftgeoutils.general::v1(), and vmap.
Referenced by add().
addWire()
void WireJoiner::WireJoinerP::addWire (std::shared_ptr< WireInfo > & wireInfo) inline
Definition at line 2987 of file WireJoiner.cpp.
References builder, compound, initWireInfo(), WireJoiner::WireJoinerP::VectorSet< T >::insertUnique(), and wireSet.
Referenced by buildClosedWire().
build()
void WireJoiner::WireJoinerP::build () inline
Definition at line 2945 of file WireJoiner.cpp.
References add(), buildAdjacentList(), buildClosedWire(), builder, clear(), doOutline, doSplitEdge, doTightBound, findClosedWires(), Path.Log::info(), openWireCompound, sourceEdgeArray, sourceEdges, and splitEdges().
buildAdjacentList()
void WireJoiner::WireJoinerP::buildAdjacentList () inline
Definition at line 1644 of file WireJoiner.cpp.
References adjacentList, buildAdjacentListPopulate(), buildAdjacentListSkipEdges(), builder, compound, and Path.Log::info().
Referenced by build().
buildAdjacentListPopulate()
void WireJoiner::WireJoinerP::buildAdjacentListPopulate () inline
Definition at line 1529 of file WireJoiner.cpp.
References adjacentList, builder, compound, doTightBound, SplineSurface::i, Path.Log::info(), myTol2, showShape(), and vmap.
Referenced by buildAdjacentList().
buildAdjacentListSkipEdges()
void WireJoiner::WireJoinerP::buildAdjacentListSkipEdges () inline
Definition at line 1606 of file WireJoiner.cpp.
References adjacentList, doMergeEdge, doTightBound, findSuperEdges(), Path.Log::info(), and showShape().
Referenced by buildAdjacentList().
buildClosedWire()
void WireJoiner::WireJoinerP::buildClosedWire () inline
Definition at line 2876 of file WireJoiner.cpp.
References addWire(), builder, WireJoiner::WireJoinerP::VectorSet< T >::clear(), compound, doOutline, exhaustTightBound(), findClosedWires(), findTightBound(), Path.Log::info(), iteration, showShape(), Mesh2Shape::wires, and wireSet.
Referenced by build().
canShowShape()
bool WireJoiner::WireJoinerP::canShowShape (int idx = -1, bool forced = false) const inline
Definition at line 2823 of file WireJoiner.cpp.
References FC_LOG_INSTANCE, and FC_LOGLEVEL_TRACE.
Referenced by addValidEdges(), and showShape().
checkBBox()
bool WireJoiner::WireJoinerP::checkBBox (const Bnd_Box & box) const inline
Definition at line 127 of file WireJoiner.cpp.
References MengerSponge::box, myTol, xMax, xMin, yMax, and yMin.
Referenced by getBBox().
checkIntersection()
void WireJoiner::WireJoinerP::checkIntersection (const EdgeInfo & info, const EdgeInfo & other, std::set< IntersectInfo > & params1, std::set< IntersectInfo > & params2) inline
Definition at line 1169 of file WireJoiner.cpp.
References checkIntersectionFaceDone(), checkIntersectionMakeWire(), checkIntersectionPlanar(), WireJoiner::WireJoinerP::EdgeInfo::edge, src.Mod.PartDesign.fcgear.svggear::errors, SplineSurface::i, Path.Log::info(), myTol, and pushIntersection().
Referenced by splitEdges().
checkIntersectionEdgeDone()
static bool WireJoiner::WireJoinerP::checkIntersectionEdgeDone (const BRepBuilderAPI_MakeEdge & mkEdge) inline static
Definition at line 1088 of file WireJoiner.cpp.
References FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, and FC_WARN.
Referenced by checkIntersectionMakeWire().
checkIntersectionFaceDone()
static bool WireJoiner::WireJoinerP::checkIntersectionFaceDone (const BRepBuilderAPI_MakeFace & mkFace) inline static
Definition at line 1158 of file WireJoiner.cpp.
References FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, and FC_WARN.
Referenced by checkIntersection().
checkIntersectionMakeWire()
static bool WireJoiner::WireJoinerP::checkIntersectionMakeWire (const EdgeInfo & info, const EdgeInfo & other, int & idx, TopoDS_Wire & wire) inline static
Definition at line 1114 of file WireJoiner.cpp.
References checkIntersectionEdgeDone(), checkIntersectionWireDone(), WireJoiner::WireJoinerP::EdgeInfo::edge, getEndPoints(), Path.Log::info(), and WireJoiner::WireJoinerP::EdgeInfo::p1.
Referenced by checkIntersection().
checkIntersectionPlanar()
bool WireJoiner::WireJoinerP::checkIntersectionPlanar (const EdgeInfo & info, const EdgeInfo & other, std::set< IntersectInfo > & params1, std::set< IntersectInfo > & params2) inline
Definition at line 1045 of file WireJoiner.cpp.
References builder, WireJoiner::WireJoinerP::EdgeInfo::edge, SplineSurface::i, Path.Log::info(), myTol, and pushIntersection().
Referenced by checkIntersection().
checkIntersectionWireDone()
static bool WireJoiner::WireJoinerP::checkIntersectionWireDone (const BRepBuilderAPI_MakeWire & mkWire) inline static
Definition at line 1101 of file WireJoiner.cpp.
References FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, and FC_WARN.
Referenced by checkIntersectionMakeWire().
checkSelfIntersection()
void WireJoiner::WireJoinerP::checkSelfIntersection (const EdgeInfo & info, std::set< IntersectInfo > & params) const inline
Definition at line 1003 of file WireJoiner.cpp.
References src.Mod.PartDesign.fcgear.svggear::errors, SplineSurface::i, Path.Log::info(), myTol, and nativeifc.ifc_observer::params.
Referenced by splitEdges().
checkWireInfo()
void WireJoiner::WireJoinerP::checkWireInfo (const WireInfo & wireInfo) inline
Definition at line 1726 of file WireJoiner.cpp.
References FC_LOG_INSTANCE, FC_LOGLEVEL_TRACE, and Path.Log::info().
Referenced by exhaustTightBoundUpdateVertex(), findTightBound(), findTightBoundByVertices(), and findTightBoundUpdateVertices().
clear()
void WireJoiner::WireJoinerP::clear () inline
Definition at line 677 of file WireJoiner.cpp.
References adjacentList, boxMap, builder, WireJoiner::WireJoinerP::VectorSet< T >::clear(), compound, edgeSet, iteration, openWireCompound, stack, tmpVertices, vertexStack, vmap, and wireSet.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__(), and build().
exhaustTightBound()
void WireJoiner::WireJoinerP::exhaustTightBound () inline
Definition at line 2662 of file WireJoiner.cpp.
References WireJoiner::WireJoinerP::VectorSet< T >::clear(), exhaustTightBoundUpdateWire(), Path.Log::info(), iteration, showShape(), and wireSet.
Referenced by buildClosedWire().
exhaustTightBoundUpdateEdge()
void WireJoiner::WireJoinerP::exhaustTightBoundUpdateEdge (const int iteration2, const VertexInfo & beginVertex, const std::vector< VertexInfo > & wireVertices, const gp_Pnt & pstart, std::shared_ptr< WireInfo > & wireInfo) inline
Definition at line 2470 of file WireJoiner.cpp.
References edgeSet, exhaustTightBoundUpdateVertex(), WireJoiner::WireJoinerP::VectorSet< T >::insert(), iteration, showShape(), stack, and vertexStack.
Referenced by exhaustTightBoundWithAdjacent().
exhaustTightBoundUpdateVertex()
void WireJoiner::WireJoinerP::exhaustTightBoundUpdateVertex (const int iteration2, const VertexInfo & beginVertex, const int idxV, const gp_Pnt & pstart, const std::vector< VertexInfo > & wireVertices, std::shared_ptr< WireInfo > & newWire, const std::shared_ptr< WireInfo > & wireInfo) inline
Definition at line 2393 of file WireJoiner.cpp.
References _findClosedWires(), adjacentList, checkWireInfo(), WireJoiner::WireJoinerP::VertexInfo::edgeInfo(), edgeSet, WireJoiner::WireJoinerP::VectorSet< T >::erase(), initWireInfo(), WireJoiner::WireJoinerP::VectorSet< T >::insert(), isInside(), iteration, myTol2, WireJoiner::WireJoinerP::VertexInfo::ptOther(), showShape(), stack, vertexStack, and wireSet.
Referenced by exhaustTightBoundUpdateEdge().
exhaustTightBoundUpdateWire()
void WireJoiner::WireJoinerP::exhaustTightBoundUpdateWire (const EdgeInfo & info, int & iteration2) inline
Definition at line 2634 of file WireJoiner.cpp.
References ArchCommands::check(), src.Mod.AddonManager.NetworkManager::count, exhaustTightBoundWithAdjacent(), Path.Log::info(), iteration, showShape(), and WireJoiner::WireJoinerP::VertexInfo::start.
Referenced by exhaustTightBound().
exhaustTightBoundWithAdjacent()
void WireJoiner::WireJoinerP::exhaustTightBoundWithAdjacent (const EdgeInfo & info, int & iteration2, const VertexInfo beginVertex, const EdgeInfo * check) inline
Definition at line 2517 of file WireJoiner.cpp.
References _findClosedWires(), adjacentList, ArchCommands::check(), WireJoiner::WireJoinerP::VectorSet< T >::clear(), WireJoiner::WireJoinerP::VertexInfo::edgeInfo(), edgeSet, exhaustTightBoundUpdateEdge(), SplineSurface::i, Path.Log::info(), initWireInfo(), WireJoiner::WireJoinerP::VectorSet< T >::insert(), iteration, myTol2, WireJoiner::WireJoinerP::VertexInfo::pt(), WireJoiner::WireJoinerP::VertexInfo::ptOther(), showShape(), stack, WireJoiner::WireJoinerP::VertexInfo::start, vertexStack, and wireSet.
Referenced by exhaustTightBoundUpdateWire().
findClosedWires()
void WireJoiner::WireJoinerP::findClosedWires (bool tightBound = false) inline
Definition at line 1662 of file WireJoiner.cpp.
References _findClosedWires(), builder, WireJoiner::WireJoinerP::VectorSet< T >::clear(), compound, edgeSet, Path.Log::info(), iteration, showShape(), stack, and vertexStack.
Referenced by build(), and buildClosedWire().
findSuperEdge()
void WireJoiner::WireJoinerP::findSuperEdge (std::deque< VertexInfo > & vertices, const Edges::iterator it) inline
Definition at line 1441 of file WireJoiner.cpp.
References WireJoiner::WireJoinerP::VectorSet< T >::clear(), edgeSet, and findSuperEdgeFromAdjacent().
Referenced by findSuperEdges().
findSuperEdgeFromAdjacent()
void WireJoiner::WireJoinerP::findSuperEdgeFromAdjacent (std::deque< VertexInfo > & vertices, const int direction) inline
Definition at line 1386 of file WireJoiner.cpp.
References adjacentList, WireJoiner::WireJoinerP::VectorSet< T >::contains(), edgeSet, SplineSurface::i, and WireJoiner::WireJoinerP::VectorSet< T >::insert().
Referenced by findSuperEdge().
findSuperEdges()
void WireJoiner::WireJoinerP::findSuperEdges () inline
Definition at line 1496 of file WireJoiner.cpp.
References findSuperEdge(), findSuperEdgesUpdateFirst(), Path.Log::info(), and iteration.
Referenced by buildAdjacentListSkipEdges().
findSuperEdgesUpdateFirst()
void WireJoiner::WireJoinerP::findSuperEdgesUpdateFirst (std::deque< VertexInfo > vertices) inline
Definition at line 1454 of file WireJoiner.cpp.
References adjacentList, SplineSurface::i, iteration, makeCleanWire(), myTol, and showShape().
Referenced by findSuperEdges().
findTightBound()
void WireJoiner::WireJoinerP::findTightBound () inline
Definition at line 2312 of file WireJoiner.cpp.
References checkWireInfo(), WireJoiner::WireJoinerP::VectorSet< T >::clear(), edgeSet, findTightBoundByVertices(), findTightBoundUpdateVertices(), Path.Log::info(), initWireInfo(), WireJoiner::WireJoinerP::VectorSet< T >::insert(), WireJoiner::WireJoinerP::VertexInfo::it, iteration, WireJoiner::WireJoinerP::VertexInfo::pt(), showShape(), stack, and vertexStack.
Referenced by buildClosedWire().
findTightBoundByVertices()
void WireJoiner::WireJoinerP::findTightBoundByVertices (EdgeInfo & beginInfo, const std::vector< VertexInfo > & wireVertices, int & idxV, const int iteration2, const gp_Pnt & pstart, const std::shared_ptr< WireInfo > & wireInfo, const VertexInfo & beginVertex, std::shared_ptr< WireInfo > & newWire) inline
Definition at line 2147 of file WireJoiner.cpp.
References _findClosedWires(), adjacentList, checkWireInfo(), WireJoiner::WireJoinerP::VertexInfo::edgeInfo(), edgeSet, WireJoiner::WireJoinerP::VectorSet< T >::erase(), findTightBoundSplitWire(), findTightBoundWithSplit(), initWireInfo(), WireJoiner::WireJoinerP::VectorSet< T >::insert(), isInside(), iteration, myTol2, WireJoiner::WireJoinerP::VertexInfo::ptOther(), showShape(), stack, vertexStack, and WireJoiner::WireJoinerP::EdgeInfo::wireInfo.
Referenced by findTightBound().
findTightBoundSplitWire()
void WireJoiner::WireJoinerP::findTightBoundSplitWire (const std::shared_ptr< WireInfo > & wireInfo, const EdgeInfo & beginInfo, const std::vector< VertexInfo > & wireVertices, std::shared_ptr< WireInfo > & splitWire, const int idxV, int & idxStart, const int idxEnd) inline
Definition at line 2047 of file WireJoiner.cpp.
References Path.Log::info(), iteration, and showShape().
Referenced by findTightBoundByVertices().
findTightBoundUpdateVertices()
void WireJoiner::WireJoinerP::findTightBoundUpdateVertices (EdgeInfo & beginInfo) inline
Definition at line 2265 of file WireJoiner.cpp.
References checkWireInfo(), Path.Log::info(), iteration, showShape(), tmpVertices, and WireJoiner::WireJoinerP::EdgeInfo::wireInfo.
Referenced by findTightBound().
findTightBoundWithSplit()
void WireJoiner::WireJoinerP::findTightBoundWithSplit (const std::vector< VertexInfo > & wireVertices, const int idxV, const std::shared_ptr< WireInfo > & splitWire, const int idxStart, const int idxEnd, const int stackPos, const int stackStart) inline
Definition at line 2079 of file WireJoiner.cpp.
References SplineSurface::i, iteration, myTol2, showShape(), splitEdges(), stack, and vertexStack.
Referenced by findTightBoundByVertices().
getBBox() [1/2]
bool WireJoiner::WireJoinerP::getBBox (const TopoDS_Shape & eForBBox, Bnd_Box & bound) inline
Definition at line 152 of file WireJoiner.cpp.
References checkBBox(), FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, FC_WARN, myTol, myTol2, and showShape().
Referenced by add(), getBBox(), and splitEdgesMakeEdge().
getBBox() [2/2]
bool WireJoiner::WireJoinerP::getBBox (const TopoDS_Shape & eForBBox, Box & box) inline
Definition at line 170 of file WireJoiner.cpp.
References MengerSponge::box, getBBox(), xMax, xMin, yMax, and yMin.
getOpenWires()
bool WireJoiner::WireJoinerP::getOpenWires (TopoShape & shape, const char * op, bool noOriginal) inline
Definition at line 2996 of file WireJoiner.cpp.
References importers.importIFClegacy::getShape(), openWireCompound, sourceEdgeArray, and sourceEdges.
getResultWires()
bool WireJoiner::WireJoinerP::getResultWires (TopoShape & shape, const char * op) inline
Definition at line 3038 of file WireJoiner.cpp.
References compound, and sourceEdges.
getWireBound()
const Bnd_Box& WireJoiner::WireJoinerP::getWireBound (const WireInfo & wireInfo) const inline
Definition at line 566 of file WireJoiner.cpp.
References KDL::Add(), WireJoiner::WireJoinerP::WireInfo::box, myTol, and WireJoiner::WireJoinerP::WireInfo::vertices.
Referenced by initWireInfo(), isInside(), and isOutside().
Handle() [1/2]
WireJoiner::WireJoinerP::Handle (BRepTools_History)
Referenced by makeCleanWire().
Handle() [2/2]
WireJoiner::WireJoinerP::Handle (ShapeExtend_WireData)
initWireInfo()
bool WireJoiner::WireJoinerP::initWireInfo (WireInfo & wireInfo) inline
Definition at line 606 of file WireJoiner.cpp.
References WireJoiner::WireJoinerP::WireInfo::face, getWireBound(), initWireInfoFaceDone(), initWireInfoWireClosed(), makeCleanWire(), WireJoiner::WireJoinerP::WireInfo::vertices, and WireJoiner::WireJoinerP::WireInfo::wire.
Referenced by addWire(), exhaustTightBoundUpdateVertex(), exhaustTightBoundWithAdjacent(), findTightBound(), findTightBoundByVertices(), and showShape().
initWireInfoFaceDone()
bool WireJoiner::WireJoinerP::initWireInfoFaceDone (WireInfo & wireInfo) inline
Definition at line 594 of file WireJoiner.cpp.
References WireJoiner::WireJoinerP::WireInfo::face, FC_ERR, showShape(), and WireJoiner::WireJoinerP::WireInfo::wire.
Referenced by initWireInfo().
initWireInfoWireClosed()
bool WireJoiner::WireJoinerP::initWireInfoWireClosed (const WireInfo & wireInfo) inline
Definition at line 579 of file WireJoiner.cpp.
References FC_ERR, iteration, showShape(), WireJoiner::WireJoinerP::WireInfo::vertices, and WireJoiner::WireJoinerP::WireInfo::wire.
Referenced by initWireInfo().
isInside()
bool WireJoiner::WireJoinerP::isInside (const WireInfo & wireInfo, gp_Pnt & pt) const inline
Definition at line 631 of file WireJoiner.cpp.
References WireJoiner::WireJoinerP::WireInfo::face, getWireBound(), and myTol.
Referenced by exhaustTightBoundUpdateVertex(), and findTightBoundByVertices().
isOutside()
bool WireJoiner::WireJoinerP::isOutside (const WireInfo & wireInfo, gp_Pnt & pt) const inline
Definition at line 640 of file WireJoiner.cpp.
References WireJoiner::WireJoinerP::WireInfo::face, getWireBound(), and myTol.
Referenced by _findClosedWiresWithExisting().
join()
void WireJoiner::WireJoinerP::join () inline
Definition at line 972 of file WireJoiner.cpp.
References builder, compound, joinMakeWire(), and remove().
joinMakeWire()
void WireJoiner::WireJoinerP::joinMakeWire (const int idx, BRepBuilderAPI_MakeWire & mkWire, const Edges::iterator it, bool & done) inline
Definition at line 906 of file WireJoiner.cpp.
References DraftVecUtils::dist(), Path.Log::info(), myTol2, remove(), and vmap.
Referenced by join().
makeCleanWire()
TopoDS_Wire WireJoiner::WireJoinerP::makeCleanWire (bool fixGap = true) inline
Definition at line 2746 of file WireJoiner.cpp.
References FC_LOG_INSTANCE, FC_LOGLEVEL_TRACE, Handle(), SplineSurface::i, myTol, printHistoryFinal(), printHistoryInit(), and result.
Referenced by _findClosedWires(), findSuperEdgesUpdateFirst(), and initWireInfo().
printHistory()
template<class T > void WireJoiner::WireJoinerP::printHistory (Handle(BRepTools_History) hist, const T & input) inline
Definition at line 2815 of file WireJoiner.cpp.
References FC_MSG, and printHistoryOfShape().
Referenced by printHistoryFinal(), and printHistoryInit().
printHistoryFinal()
void WireJoiner::WireJoinerP::printHistoryFinal () inline
Definition at line 2732 of file WireJoiner.cpp.
References FC_MSG, SplineSurface::i, printHistory(), and sourceEdges.
Referenced by makeCleanWire().
printHistoryInit()
void WireJoiner::WireJoinerP::printHistoryInit (const Handle_BRepTools_History & newHistory, const std::vector< TopoShape > & inputEdges) inline
Definition at line 2714 of file WireJoiner.cpp.
References FC_MSG, printHistory(), and sourceEdges.
Referenced by makeCleanWire().
printHistoryOfShape()
template<class T > void WireJoiner::WireJoinerP::printHistoryOfShape (const Handle(BRepTools_History)& hist, const T & shape) inline
Definition at line 2798 of file WireJoiner.cpp.
References FC_MSG.
Referenced by printHistory().
pushIntersection()
void WireJoiner::WireJoinerP::pushIntersection (std::set< IntersectInfo > & params, double param, const gp_Pnt & pt, const TopoDS_Shape & shape) inline
Definition at line 1213 of file WireJoiner.cpp.
References Path.Log::info(), myTol2, Init::param, and nativeifc.ifc_observer::params.
Referenced by checkIntersection(), and checkIntersectionPlanar().
remove() [1/2]
void WireJoiner::WireJoinerP::remove (EdgeInfo * info) inline
Definition at line 704 of file WireJoiner.cpp.
References edgesTable, Path.Log::info(), and remove().
remove() [2/2]
Edges::iterator WireJoiner::WireJoinerP::remove (Edges::iterator it) inline
Definition at line 694 of file WireJoiner.cpp.
References boxMap, and vmap.
Referenced by join(), joinMakeWire(), remove(), and splitEdges().
showShape() [1/3]
void WireJoiner::WireJoinerP::showShape (const EdgeInfo * info, const char * name, int idx = -1, bool forced = false) const inline
Definition at line 2833 of file WireJoiner.cpp.
References canShowShape(), and Path.Log::info().
Referenced by _findClosedWires(), _findClosedWiresBeginEdge(), _findClosedWiresIsClosed(), _findClosedWiresUpdateEdges(), _findClosedWiresUpdateStack(), _findClosedWiresWithExisting(), add(), addNoDuplicates(), buildAdjacentListPopulate(), buildAdjacentListSkipEdges(), buildClosedWire(), exhaustTightBound(), exhaustTightBoundUpdateEdge(), exhaustTightBoundUpdateVertex(), exhaustTightBoundUpdateWire(), exhaustTightBoundWithAdjacent(), findClosedWires(), findSuperEdgesUpdateFirst(), findTightBound(), findTightBoundByVertices(), findTightBoundSplitWire(), findTightBoundUpdateVertices(), findTightBoundWithSplit(), getBBox(), initWireInfoFaceDone(), initWireInfoWireClosed(), showShape(), and splitEdges().
showShape() [2/3]
void WireJoiner::WireJoinerP::showShape (const TopoDS_Shape & sToShow, const char * name, int idx = -1, bool forced = false) const inline
Definition at line 2852 of file WireJoiner.cpp.
References canShowShape(), catchObject, importers.importIFClegacy::create(), and FC_MSG.
showShape() [3/3]
void WireJoiner::WireJoinerP::showShape (WireInfo & wireInfo, const char * name, int idx = -1, bool forced = false) inline
Definition at line 2841 of file WireJoiner.cpp.
References canShowShape(), initWireInfo(), showShape(), and WireJoiner::WireJoinerP::WireInfo::wire.
splitEdges()
void WireJoiner::WireJoinerP::splitEdges () inline
Definition at line 1296 of file WireJoiner.cpp.
References add(), boxMap, checkIntersection(), checkSelfIntersection(), Path.Log::info(), myTol2, nativeifc.ifc_observer::params, remove(), showShape(), and splitEdgesMakeEdges().
Referenced by build(), and findTightBoundWithSplit().
splitEdgesMakeEdge()
void WireJoiner::WireJoinerP::splitEdgesMakeEdge (const std::set< IntersectInfo >::iterator & itParam, const EdgeInfo & info, std::vector< SplitInfo > & splits, std::set< IntersectInfo >::iterator & itPrevParam, const TopoDS_Shape & intersectShape) inline
Definition at line 1243 of file WireJoiner.cpp.
References FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, FC_WARN, FC_XYZ, getBBox(), and Path.Log::info().
Referenced by splitEdgesMakeEdges().
splitEdgesMakeEdges()
void WireJoiner::WireJoinerP::splitEdgesMakeEdges (std::set< IntersectInfo >::iterator & itParam, const std::set< IntersectInfo > & params, const EdgeInfo & info, std::vector< SplitInfo > & splits) inline
Definition at line 1278 of file WireJoiner.cpp.
References Path.Log::info(), nativeifc.ifc_observer::params, and splitEdgesMakeEdge().
Referenced by splitEdges().
Member Data Documentation
adjacentList
std::vector<VertexInfo> WireJoiner::WireJoinerP::adjacentList {}
Definition at line 463 of file WireJoiner.cpp.
Referenced by _findClosedWiresUpdateStack(), _findClosedWiresWithExisting(), buildAdjacentList(), buildAdjacentListPopulate(), buildAdjacentListSkipEdges(), clear(), exhaustTightBoundUpdateVertex(), exhaustTightBoundWithAdjacent(), findSuperEdgeFromAdjacent(), findSuperEdgesUpdateFirst(), and findTightBoundByVertices().
boxMap
bgi::rtree<Edges::iterator, RParameters, BoxGetter> WireJoiner::WireJoinerP::boxMap {}
Definition at line 666 of file WireJoiner.cpp.
Referenced by add(), clear(), remove(), and splitEdges().
builder
BRep_Builder WireJoiner::WireJoinerP::builder
Definition at line 668 of file WireJoiner.cpp.
Referenced by addWire(), build(), buildAdjacentList(), buildAdjacentListPopulate(), buildClosedWire(), checkIntersectionPlanar(), clear(), findClosedWires(), and join().
catchIteration
int WireJoiner::WireJoinerP::catchIteration {}
Definition at line 122 of file WireJoiner.cpp.
catchObject
std::string WireJoiner::WireJoinerP::catchObject
Definition at line 121 of file WireJoiner.cpp.
Referenced by showShape().
compound
TopoDS_Compound WireJoiner::WireJoinerP::compound
Definition at line 669 of file WireJoiner.cpp.
Referenced by addWire(), buildAdjacentList(), buildAdjacentListPopulate(), buildClosedWire(), clear(), findClosedWires(), getResultWires(), and join().
doMergeEdge
bool WireJoiner::WireJoinerP::doMergeEdge = true
Definition at line 117 of file WireJoiner.cpp.
Referenced by buildAdjacentListSkipEdges().
doOutline
bool WireJoiner::WireJoinerP::doOutline = false
Definition at line 118 of file WireJoiner.cpp.
Referenced by build(), and buildClosedWire().
doSplitEdge
bool WireJoiner::WireJoinerP::doSplitEdge = true
Definition at line 116 of file WireJoiner.cpp.
Referenced by build().
doTightBound
bool WireJoiner::WireJoinerP::doTightBound = true
Definition at line 119 of file WireJoiner.cpp.
Referenced by build(), buildAdjacentListPopulate(), and buildAdjacentListSkipEdges().
edges
Edges WireJoiner::WireJoinerP::edges {}
Definition at line 395 of file WireJoiner.cpp.
edgeSet
EdgeSet WireJoiner::WireJoinerP::edgeSet
Definition at line 560 of file WireJoiner.cpp.
Referenced by _findClosedWiresUpdateEdges(), _findClosedWiresUpdateStack(), clear(), exhaustTightBoundUpdateEdge(), exhaustTightBoundUpdateVertex(), exhaustTightBoundWithAdjacent(), findClosedWires(), findSuperEdge(), findSuperEdgeFromAdjacent(), findTightBound(), and findTightBoundByVertices().
edgesTable
std::map<EdgeInfo*, Edges::iterator> WireJoiner::WireJoinerP::edgesTable {}
Definition at line 397 of file WireJoiner.cpp.
Referenced by remove().
iteration
int WireJoiner::WireJoinerP::iteration = 0
Definition at line 123 of file WireJoiner.cpp.
Referenced by _findClosedWires(), _findClosedWiresBeginEdge(), _findClosedWiresIsClosed(), _findClosedWiresUpdateEdges(), _findClosedWiresUpdateStack(), _findClosedWiresWithExisting(), buildClosedWire(), clear(), exhaustTightBound(), exhaustTightBoundUpdateEdge(), exhaustTightBoundUpdateVertex(), exhaustTightBoundUpdateWire(), exhaustTightBoundWithAdjacent(), findClosedWires(), findSuperEdges(), findSuperEdgesUpdateFirst(), findTightBound(), findTightBoundByVertices(), findTightBoundSplitWire(), findTightBoundUpdateVertices(), findTightBoundWithSplit(), and initWireInfoWireClosed().
myAngularTol
double WireJoiner::WireJoinerP::myAngularTol = Precision::Angular()
Definition at line 115 of file WireJoiner.cpp.
Referenced by addNoDuplicates().
myTol
double WireJoiner::WireJoinerP::myTol = Precision::Confusion()
Definition at line 113 of file WireJoiner.cpp.
Referenced by add(), addNoDuplicates(), checkBBox(), checkIntersection(), checkIntersectionPlanar(), checkSelfIntersection(), findSuperEdgesUpdateFirst(), getBBox(), getWireBound(), isInside(), isOutside(), and makeCleanWire().
myTol2
double WireJoiner::WireJoinerP::myTol2 = myTol * myTol
Definition at line 114 of file WireJoiner.cpp.
Referenced by _findClosedWires(), add(), buildAdjacentListPopulate(), exhaustTightBoundUpdateVertex(), exhaustTightBoundWithAdjacent(), findTightBoundByVertices(), findTightBoundWithSplit(), getBBox(), joinMakeWire(), pushIntersection(), and splitEdges().
openWireCompound
TopoDS_Compound WireJoiner::WireJoinerP::openWireCompound
Definition at line 673 of file WireJoiner.cpp.
Referenced by build(), clear(), and getOpenWires().
sourceEdgeArray
std::vector<TopoShape> WireJoiner::WireJoinerP::sourceEdgeArray {}
Definition at line 672 of file WireJoiner.cpp.
Referenced by build(), and getOpenWires().
sourceEdges
std::unordered_set<TopoShape, ShapeHasher, ShapeHasher> WireJoiner::WireJoinerP::sourceEdges {}
Definition at line 671 of file WireJoiner.cpp.
Referenced by add(), build(), getOpenWires(), getResultWires(), printHistoryFinal(), and printHistoryInit().
stack
std::vector<StackInfo> WireJoiner::WireJoinerP::stack {}
Definition at line 460 of file WireJoiner.cpp.
Referenced by src.Mod.Show.TVStack.TVStack::__getitem__(), src.Mod.Show.TVStack.TVStack::__init__(), src.Mod.Show.TVStack.TVStack::__iter__(), src.Mod.Show.TVStack.TVStack::__len__(), src.Mod.Show.TVStack.TVStack::__reversed__(), _findClosedWires(), _findClosedWiresBeginEdge(), _findClosedWiresIsClosed(), _findClosedWiresUpdateEdges(), _findClosedWiresUpdateStack(), _findClosedWiresWithExisting(), src.Mod.Show.mTempoVis.TempoVis::activateWorkbench(), src.Mod.Show.TVStack.TVStack::byTag(), clear(), src.Mod.Show.TVStack.TVStack::dissolve(), exhaustTightBoundUpdateEdge(), exhaustTightBoundUpdateVertex(), exhaustTightBoundWithAdjacent(), findClosedWires(), findTightBound(), findTightBoundByVertices(), findTightBoundWithSplit(), src.Mod.Show.mTempoVis.TempoVis::forget(), src.Mod.Show.TVStack.TVStack::getSplitSequence(), src.Mod.Show.TVStack.TVStack::insert(), src.Mod.Show.mTempoVis.TempoVis::is_in_stack(), src.Mod.Show.TVStack.TVStack::purge_dead(), src.Mod.Show.TVStack.TVStack::rebuild_index(), src.Mod.Show.mTempoVis.TempoVis::restore(), src.Mod.Show.TVStack.TVStack::restoreAll(), src.Mod.Show.TVStack.TVStack::unwindForSaving(), src.Mod.Show.TVStack.TVStack::value_after(), and src.Mod.Show.TVStack.TVStack::withdraw().
tmpVertices
std::vector<VertexInfo> WireJoiner::WireJoinerP::tmpVertices {}
Definition at line 462 of file WireJoiner.cpp.
Referenced by clear(), and findTightBoundUpdateVertices().
vertexStack
std::vector<VertexInfo> WireJoiner::WireJoinerP::vertexStack {}
Definition at line 461 of file WireJoiner.cpp.
Referenced by _findClosedWires(), _findClosedWiresBeginEdge(), _findClosedWiresIsClosed(), _findClosedWiresUpdateEdges(), _findClosedWiresUpdateStack(), _findClosedWiresWithExisting(), clear(), exhaustTightBoundUpdateEdge(), exhaustTightBoundUpdateVertex(), exhaustTightBoundWithAdjacent(), findClosedWires(), findTightBound(), findTightBoundByVertices(), and findTightBoundWithSplit().
vmap
bgi::rtree<VertexInfo, RParameters, PntGetter> WireJoiner::WireJoinerP::vmap {}
Definition at line 657 of file WireJoiner.cpp.
Referenced by add(), addValidEdges(), buildAdjacentListPopulate(), clear(), joinMakeWire(), and remove().
wireSet
WireSet WireJoiner::WireJoinerP::wireSet
Definition at line 564 of file WireJoiner.cpp.
Referenced by _findClosedWiresUpdateEdges(), _findClosedWiresUpdateStack(), addWire(), buildClosedWire(), clear(), exhaustTightBound(), exhaustTightBoundUpdateVertex(), and exhaustTightBoundWithAdjacent().
The documentation for this class was generated from the following file:
WireJoiner.cpp