FreeCAD: GCS::Constraint Class Reference
GCS::Constraint Class Reference
#include <Constraints.h>
Public Types
enum Alignment { Alignment::NoInternalAlignment, Alignment::InternalAlignment }
Public Member Functions
Constraint ()
virtual ~Constraint ()
VEC_pD params ()
void redirectParams (const MAP_pD_pD &redirectionmap)
void revertParams ()
void setTag (int tagId)
int getTag ()
void setDriving (bool isdriving)
bool isDriving () const
void setInternalAlignment (Alignment isinternalalignment)
Alignment isInternalAlignment () const
virtual ConstraintType getTypeId ()
virtual void rescale (double coef=1.)
virtual double error ()
virtual double grad (double *)
virtual double maxStep (MAP_pD_D &dir, double lim=1.)
int findParamInPvec (double *param)
Protected Attributes
VEC_pD origpvec
VEC_pD pvec
double scale
int tag
bool pvecChangedFlag
bool driving
Alignment internalAlignment
Detailed Description
Definition at line 110 of file Constraints.h.
Member Enumeration Documentation
Alignment
enum GCS::Constraint::Alignment strong
Enumerator
NoInternalAlignment
InternalAlignment
Definition at line 114 of file Constraints.h.
Constructor & Destructor Documentation
Constraint()
GCS::Constraint::Constraint ()
Definition at line 48 of file Constraints.cpp.
~Constraint()
virtual GCS::Constraint::~Constraint () inline virtual
Definition at line 133 of file Constraints.h.
Member Function Documentation
error()
double GCS::Constraint::error () virtual
Reimplemented in GCS::ConstraintArcLength, GCS::ConstraintP2CDistance, GCS::ConstraintC2LDistance, GCS::ConstraintC2CDistance, GCS::ConstraintEqualLineLength, GCS::ConstraintAngleViaPointAndTwoParams, GCS::ConstraintAngleViaPointAndParam, GCS::ConstraintSnell, GCS::ConstraintAngleViaTwoPoints, GCS::ConstraintAngleViaPoint, GCS::ConstraintPointOnParabola, GCS::ConstraintPointOnHyperbola, GCS::ConstraintCurveValue, GCS::ConstraintEqualFocalDistance, GCS::ConstraintEqualMajorAxesConic, GCS::ConstraintInternalAlignmentPoint2Hyperbola, GCS::ConstraintInternalAlignmentPoint2Ellipse, GCS::ConstraintEllipseTangentLine, GCS::ConstraintPointOnEllipse, GCS::ConstraintTangentCircumf, GCS::ConstraintMidpointOnLine, GCS::ConstraintL2LAngle, GCS::ConstraintPerpendicular, GCS::ConstraintParallel, GCS::ConstraintPointOnPerpBisector, GCS::ConstraintPointOnLine, GCS::ConstraintP2LDistance, GCS::ConstraintP2PAngle, GCS::ConstraintP2PDistance, GCS::ConstraintDifference, GCS::ConstraintPointOnBSpline, GCS::ConstraintSlopeAtBSplineKnot, GCS::ConstraintWeightedLinearCombination, GCS::ConstraintCenterOfGravity, and GCS::ConstraintEqual.
Definition at line 86 of file Constraints.cpp.
findParamInPvec()
int GCS::Constraint::findParamInPvec (double * param)
Definition at line 101 of file Constraints.cpp.
References SplineSurface::i, Init::param, and pvec.
Referenced by GCS::ConstraintPointOnPerpBisector::grad(), GCS::ConstraintEllipseTangentLine::grad(), GCS::ConstraintInternalAlignmentPoint2Ellipse::grad(), GCS::ConstraintInternalAlignmentPoint2Hyperbola::grad(), GCS::ConstraintEqualMajorAxesConic::grad(), GCS::ConstraintEqualFocalDistance::grad(), GCS::ConstraintCurveValue::grad(), GCS::ConstraintPointOnParabola::grad(), GCS::ConstraintAngleViaPoint::grad(), GCS::ConstraintAngleViaTwoPoints::grad(), GCS::ConstraintSnell::grad(), GCS::ConstraintAngleViaPointAndParam::grad(), GCS::ConstraintAngleViaPointAndTwoParams::grad(), GCS::ConstraintEqualLineLength::grad(), GCS::ConstraintC2CDistance::grad(), GCS::ConstraintC2LDistance::grad(), GCS::ConstraintP2CDistance::grad(), and GCS::ConstraintArcLength::grad().
getTag()
int GCS::Constraint::getTag () inline
Definition at line 147 of file Constraints.h.
References Dice3DS.dom3ds::tag.
Referenced by GCS::System::addConstraint(), and GCS::System::removeConstraint().
getTypeId()
ConstraintType GCS::Constraint::getTypeId () virtual
Reimplemented in GCS::ConstraintArcLength, GCS::ConstraintP2CDistance, GCS::ConstraintC2LDistance, GCS::ConstraintC2CDistance, GCS::ConstraintEqualLineLength, GCS::ConstraintAngleViaPointAndTwoParams, GCS::ConstraintAngleViaPointAndParam, GCS::ConstraintSnell, GCS::ConstraintAngleViaTwoPoints, GCS::ConstraintAngleViaPoint, GCS::ConstraintPointOnParabola, GCS::ConstraintPointOnHyperbola, GCS::ConstraintCurveValue, GCS::ConstraintEqualFocalDistance, GCS::ConstraintEqualMajorAxesConic, GCS::ConstraintInternalAlignmentPoint2Hyperbola, GCS::ConstraintInternalAlignmentPoint2Ellipse, GCS::ConstraintEllipseTangentLine, GCS::ConstraintPointOnEllipse, GCS::ConstraintTangentCircumf, GCS::ConstraintMidpointOnLine, GCS::ConstraintL2LAngle, GCS::ConstraintPerpendicular, GCS::ConstraintParallel, GCS::ConstraintPointOnPerpBisector, GCS::ConstraintPointOnLine, GCS::ConstraintP2LDistance, GCS::ConstraintP2PAngle, GCS::ConstraintP2PDistance, GCS::ConstraintDifference, GCS::ConstraintPointOnBSpline, GCS::ConstraintSlopeAtBSplineKnot, GCS::ConstraintWeightedLinearCombination, GCS::ConstraintCenterOfGravity, and GCS::ConstraintEqual.
Definition at line 76 of file Constraints.cpp.
References GCS::None.
grad()
double GCS::Constraint::grad (double *) virtual
Reimplemented in GCS::ConstraintArcLength, GCS::ConstraintP2CDistance, GCS::ConstraintC2LDistance, GCS::ConstraintC2CDistance, GCS::ConstraintEqualLineLength, GCS::ConstraintAngleViaPointAndTwoParams, GCS::ConstraintAngleViaPointAndParam, GCS::ConstraintSnell, GCS::ConstraintAngleViaTwoPoints, GCS::ConstraintAngleViaPoint, GCS::ConstraintPointOnParabola, GCS::ConstraintPointOnHyperbola, GCS::ConstraintCurveValue, GCS::ConstraintEqualFocalDistance, GCS::ConstraintEqualMajorAxesConic, GCS::ConstraintInternalAlignmentPoint2Hyperbola, GCS::ConstraintInternalAlignmentPoint2Ellipse, GCS::ConstraintEllipseTangentLine, GCS::ConstraintPointOnEllipse, GCS::ConstraintTangentCircumf, GCS::ConstraintMidpointOnLine, GCS::ConstraintL2LAngle, GCS::ConstraintPerpendicular, GCS::ConstraintParallel, GCS::ConstraintPointOnPerpBisector, GCS::ConstraintPointOnLine, GCS::ConstraintP2LDistance, GCS::ConstraintP2PAngle, GCS::ConstraintP2PDistance, GCS::ConstraintDifference, GCS::ConstraintPointOnBSpline, GCS::ConstraintSlopeAtBSplineKnot, GCS::ConstraintWeightedLinearCombination, GCS::ConstraintCenterOfGravity, and GCS::ConstraintEqual.
Definition at line 91 of file Constraints.cpp.
isDriving()
bool GCS::Constraint::isDriving () const inline
Definition at line 156 of file Constraints.h.
isInternalAlignment()
Alignment GCS::Constraint::isInternalAlignment () const inline
Definition at line 165 of file Constraints.h.
maxStep()
double GCS::Constraint::maxStep (MAP_pD_D & dir, double lim = 1.) virtual
Reimplemented in GCS::ConstraintCurveValue, GCS::ConstraintL2LAngle, GCS::ConstraintP2LDistance, GCS::ConstraintP2PAngle, and GCS::ConstraintP2PDistance.
Definition at line 96 of file Constraints.cpp.
params()
VEC_pD GCS::Constraint::params () inline
Definition at line 136 of file Constraints.h.
Referenced by GCS::System::addConstraint().
redirectParams()
void GCS::Constraint::redirectParams (const MAP_pD_pD & redirectionmap)
Definition at line 58 of file Constraints.cpp.
References SplineSurface::i, origpvec, Init::param, pvec, and pvecChangedFlag.
rescale()
void GCS::Constraint::rescale (double coef = 1.) virtual
Reimplemented in GCS::ConstraintArcLength, GCS::ConstraintP2CDistance, GCS::ConstraintC2LDistance, GCS::ConstraintC2CDistance, GCS::ConstraintEqualLineLength, GCS::ConstraintAngleViaPointAndTwoParams, GCS::ConstraintAngleViaPointAndParam, GCS::ConstraintSnell, GCS::ConstraintAngleViaTwoPoints, GCS::ConstraintAngleViaPoint, GCS::ConstraintPointOnParabola, GCS::ConstraintPointOnHyperbola, GCS::ConstraintCurveValue, GCS::ConstraintEqualFocalDistance, GCS::ConstraintEqualMajorAxesConic, GCS::ConstraintInternalAlignmentPoint2Hyperbola, GCS::ConstraintInternalAlignmentPoint2Ellipse, GCS::ConstraintEllipseTangentLine, GCS::ConstraintPointOnEllipse, GCS::ConstraintTangentCircumf, GCS::ConstraintMidpointOnLine, GCS::ConstraintL2LAngle, GCS::ConstraintPerpendicular, GCS::ConstraintParallel, GCS::ConstraintPointOnPerpBisector, GCS::ConstraintPointOnLine, GCS::ConstraintP2LDistance, GCS::ConstraintP2PAngle, GCS::ConstraintP2PDistance, GCS::ConstraintDifference, GCS::ConstraintPointOnBSpline, GCS::ConstraintSlopeAtBSplineKnot, GCS::ConstraintWeightedLinearCombination, GCS::ConstraintCenterOfGravity, and GCS::ConstraintEqual.
Definition at line 81 of file Constraints.cpp.
revertParams()
void GCS::Constraint::revertParams ()
Definition at line 70 of file Constraints.cpp.
References origpvec, pvec, and pvecChangedFlag.
setDriving()
void GCS::Constraint::setDriving (bool isdriving) inline
Definition at line 152 of file Constraints.h.
Referenced by GCS::System::addConstraintAngleViaPoint(), GCS::System::addConstraintAngleViaPointAndParam(), GCS::System::addConstraintAngleViaPointAndTwoParams(), GCS::System::addConstraintAngleViaTwoPoints(), GCS::System::addConstraintArcLength(), GCS::System::addConstraintC2CDistance(), GCS::System::addConstraintC2LDistance(), GCS::System::addConstraintCurveValue(), GCS::System::addConstraintDifference(), GCS::System::addConstraintEqual(), GCS::System::addConstraintEqualFocus(), GCS::System::addConstraintEqualLength(), GCS::System::addConstraintEqualRadii(), GCS::System::addConstraintInternalAlignmentKnotPoint(), GCS::System::addConstraintInternalAlignmentPoint2Ellipse(), GCS::System::addConstraintInternalAlignmentPoint2Hyperbola(), GCS::System::addConstraintL2LAngle(), GCS::System::addConstraintMidpointOnLine(), GCS::System::addConstraintP2CDistance(), GCS::System::addConstraintP2LDistance(), GCS::System::addConstraintP2PAngle(), GCS::System::addConstraintP2PDistance(), GCS::System::addConstraintParallel(), GCS::System::addConstraintPerpendicular(), GCS::System::addConstraintPointOnBSpline(), GCS::System::addConstraintPointOnEllipse(), GCS::System::addConstraintPointOnHyperbolicArc(), GCS::System::addConstraintPointOnLine(), GCS::System::addConstraintPointOnParabolicArc(), GCS::System::addConstraintPointOnPerpBisector(), GCS::System::addConstraintProportional(), GCS::System::addConstraintSnellsLaw(), GCS::System::addConstraintTangent(), GCS::System::addConstraintTangentAtBSplineKnot(), and GCS::System::addConstraintTangentCircumf().
setInternalAlignment()
void GCS::Constraint::setInternalAlignment (Alignment isinternalalignment) inline
Definition at line 161 of file Constraints.h.
Referenced by GCS::System::addConstraintEqual(), GCS::System::addConstraintInternalAlignmentKnotPoint(), GCS::System::addConstraintInternalAlignmentPoint2Ellipse(), and GCS::System::addConstraintInternalAlignmentPoint2Hyperbola().
setTag()
void GCS::Constraint::setTag (int tagId) inline
Definition at line 143 of file Constraints.h.
References Dice3DS.dom3ds::tag.
Referenced by GCS::System::addConstraintAngleViaPoint(), GCS::System::addConstraintAngleViaPointAndParam(), GCS::System::addConstraintAngleViaPointAndTwoParams(), GCS::System::addConstraintAngleViaTwoPoints(), GCS::System::addConstraintArcLength(), GCS::System::addConstraintC2CDistance(), GCS::System::addConstraintC2LDistance(), GCS::System::addConstraintCurveValue(), GCS::System::addConstraintDifference(), GCS::System::addConstraintEqual(), GCS::System::addConstraintEqualFocus(), GCS::System::addConstraintEqualLength(), GCS::System::addConstraintEqualRadii(), GCS::System::addConstraintInternalAlignmentKnotPoint(), GCS::System::addConstraintInternalAlignmentPoint2Ellipse(), GCS::System::addConstraintInternalAlignmentPoint2Hyperbola(), GCS::System::addConstraintL2LAngle(), GCS::System::addConstraintMidpointOnLine(), GCS::System::addConstraintP2CDistance(), GCS::System::addConstraintP2LDistance(), GCS::System::addConstraintP2PAngle(), GCS::System::addConstraintP2PDistance(), GCS::System::addConstraintParallel(), GCS::System::addConstraintPerpendicular(), GCS::System::addConstraintPointOnBSpline(), GCS::System::addConstraintPointOnEllipse(), GCS::System::addConstraintPointOnHyperbolicArc(), GCS::System::addConstraintPointOnLine(), GCS::System::addConstraintPointOnParabolicArc(), GCS::System::addConstraintPointOnPerpBisector(), GCS::System::addConstraintProportional(), GCS::System::addConstraintSnellsLaw(), GCS::System::addConstraintTangent(), GCS::System::addConstraintTangentAtBSplineKnot(), and GCS::System::addConstraintTangentCircumf().
Member Data Documentation
driving
bool GCS::Constraint::driving protected
Definition at line 128 of file Constraints.h.
internalAlignment
Alignment GCS::Constraint::internalAlignment protected
Definition at line 129 of file Constraints.h.
origpvec
VEC_pD GCS::Constraint::origpvec protected
Definition at line 121 of file Constraints.h.
Referenced by GCS::ConstraintAngleViaPoint::ConstraintAngleViaPoint(), GCS::ConstraintAngleViaPointAndParam::ConstraintAngleViaPointAndParam(), GCS::ConstraintAngleViaPointAndTwoParams::ConstraintAngleViaPointAndTwoParams(), GCS::ConstraintAngleViaTwoPoints::ConstraintAngleViaTwoPoints(), GCS::ConstraintArcLength::ConstraintArcLength(), GCS::ConstraintC2CDistance::ConstraintC2CDistance(), GCS::ConstraintC2LDistance::ConstraintC2LDistance(), GCS::ConstraintCenterOfGravity::ConstraintCenterOfGravity(), GCS::ConstraintCurveValue::ConstraintCurveValue(), GCS::ConstraintDifference::ConstraintDifference(), GCS::ConstraintEllipseTangentLine::ConstraintEllipseTangentLine(), GCS::ConstraintEqual::ConstraintEqual(), GCS::ConstraintEqualFocalDistance::ConstraintEqualFocalDistance(), GCS::ConstraintEqualLineLength::ConstraintEqualLineLength(), GCS::ConstraintEqualMajorAxesConic::ConstraintEqualMajorAxesConic(), GCS::ConstraintInternalAlignmentPoint2Ellipse::ConstraintInternalAlignmentPoint2Ellipse(), GCS::ConstraintInternalAlignmentPoint2Hyperbola::ConstraintInternalAlignmentPoint2Hyperbola(), GCS::ConstraintL2LAngle::ConstraintL2LAngle(), GCS::ConstraintMidpointOnLine::ConstraintMidpointOnLine(), GCS::ConstraintP2CDistance::ConstraintP2CDistance(), GCS::ConstraintP2LDistance::ConstraintP2LDistance(), GCS::ConstraintP2PAngle::ConstraintP2PAngle(), GCS::ConstraintP2PDistance::ConstraintP2PDistance(), GCS::ConstraintParallel::ConstraintParallel(), GCS::ConstraintPerpendicular::ConstraintPerpendicular(), GCS::ConstraintPointOnBSpline::ConstraintPointOnBSpline(), GCS::ConstraintPointOnEllipse::ConstraintPointOnEllipse(), GCS::ConstraintPointOnHyperbola::ConstraintPointOnHyperbola(), GCS::ConstraintPointOnLine::ConstraintPointOnLine(), GCS::ConstraintPointOnParabola::ConstraintPointOnParabola(), GCS::ConstraintPointOnPerpBisector::ConstraintPointOnPerpBisector(), GCS::ConstraintSlopeAtBSplineKnot::ConstraintSlopeAtBSplineKnot(), GCS::ConstraintSnell::ConstraintSnell(), GCS::ConstraintTangentCircumf::ConstraintTangentCircumf(), GCS::ConstraintWeightedLinearCombination::ConstraintWeightedLinearCombination(), redirectParams(), and revertParams().
pvec
VEC_pD GCS::Constraint::pvec protected
Definition at line 122 of file Constraints.h.
Referenced by GCS::ConstraintAngleViaPoint::ConstraintAngleViaPoint(), GCS::ConstraintAngleViaPointAndParam::ConstraintAngleViaPointAndParam(), GCS::ConstraintAngleViaPointAndTwoParams::ConstraintAngleViaPointAndTwoParams(), GCS::ConstraintAngleViaTwoPoints::ConstraintAngleViaTwoPoints(), GCS::ConstraintArcLength::ConstraintArcLength(), GCS::ConstraintC2CDistance::ConstraintC2CDistance(), GCS::ConstraintC2LDistance::ConstraintC2LDistance(), GCS::ConstraintCenterOfGravity::ConstraintCenterOfGravity(), GCS::ConstraintCurveValue::ConstraintCurveValue(), GCS::ConstraintDifference::ConstraintDifference(), GCS::ConstraintEllipseTangentLine::ConstraintEllipseTangentLine(), GCS::ConstraintEqual::ConstraintEqual(), GCS::ConstraintEqualFocalDistance::ConstraintEqualFocalDistance(), GCS::ConstraintEqualLineLength::ConstraintEqualLineLength(), GCS::ConstraintEqualMajorAxesConic::ConstraintEqualMajorAxesConic(), GCS::ConstraintInternalAlignmentPoint2Ellipse::ConstraintInternalAlignmentPoint2Ellipse(), GCS::ConstraintInternalAlignmentPoint2Hyperbola::ConstraintInternalAlignmentPoint2Hyperbola(), GCS::ConstraintL2LAngle::ConstraintL2LAngle(), GCS::ConstraintMidpointOnLine::ConstraintMidpointOnLine(), GCS::ConstraintP2CDistance::ConstraintP2CDistance(), GCS::ConstraintP2LDistance::ConstraintP2LDistance(), GCS::ConstraintP2PAngle::ConstraintP2PAngle(), GCS::ConstraintP2PDistance::ConstraintP2PDistance(), GCS::ConstraintParallel::ConstraintParallel(), GCS::ConstraintPerpendicular::ConstraintPerpendicular(), GCS::ConstraintPointOnBSpline::ConstraintPointOnBSpline(), GCS::ConstraintPointOnEllipse::ConstraintPointOnEllipse(), GCS::ConstraintPointOnHyperbola::ConstraintPointOnHyperbola(), GCS::ConstraintPointOnLine::ConstraintPointOnLine(), GCS::ConstraintPointOnParabola::ConstraintPointOnParabola(), GCS::ConstraintPointOnPerpBisector::ConstraintPointOnPerpBisector(), GCS::ConstraintSlopeAtBSplineKnot::ConstraintSlopeAtBSplineKnot(), GCS::ConstraintSnell::ConstraintSnell(), GCS::ConstraintTangentCircumf::ConstraintTangentCircumf(), GCS::ConstraintWeightedLinearCombination::ConstraintWeightedLinearCombination(), findParamInPvec(), redirectParams(), and revertParams().
pvecChangedFlag
bool GCS::Constraint::pvecChangedFlag protected
Definition at line 127 of file Constraints.h.
Referenced by GCS::ConstraintAngleViaPoint::ConstraintAngleViaPoint(), GCS::ConstraintAngleViaPointAndParam::ConstraintAngleViaPointAndParam(), GCS::ConstraintAngleViaPointAndTwoParams::ConstraintAngleViaPointAndTwoParams(), GCS::ConstraintAngleViaTwoPoints::ConstraintAngleViaTwoPoints(), GCS::ConstraintArcLength::ConstraintArcLength(), GCS::ConstraintC2CDistance::ConstraintC2CDistance(), GCS::ConstraintC2LDistance::ConstraintC2LDistance(), GCS::ConstraintCurveValue::ConstraintCurveValue(), GCS::ConstraintEllipseTangentLine::ConstraintEllipseTangentLine(), GCS::ConstraintEqualFocalDistance::ConstraintEqualFocalDistance(), GCS::ConstraintEqualLineLength::ConstraintEqualLineLength(), GCS::ConstraintEqualMajorAxesConic::ConstraintEqualMajorAxesConic(), GCS::ConstraintP2CDistance::ConstraintP2CDistance(), GCS::ConstraintPointOnParabola::ConstraintPointOnParabola(), GCS::ConstraintSnell::ConstraintSnell(), GCS::ConstraintAngleViaPoint::error(), GCS::ConstraintAngleViaTwoPoints::error(), GCS::ConstraintAngleViaPointAndParam::error(), GCS::ConstraintAngleViaPointAndTwoParams::error(), GCS::ConstraintAngleViaPoint::grad(), GCS::ConstraintAngleViaTwoPoints::grad(), GCS::ConstraintAngleViaPointAndParam::grad(), GCS::ConstraintAngleViaPointAndTwoParams::grad(), redirectParams(), and revertParams().
scale
double GCS::Constraint::scale protected
Definition at line 123 of file Constraints.h.
Referenced by GCS::ConstraintPointOnPerpBisector::grad(), GCS::ConstraintEllipseTangentLine::grad(), GCS::ConstraintInternalAlignmentPoint2Ellipse::grad(), GCS::ConstraintInternalAlignmentPoint2Hyperbola::grad(), GCS::ConstraintEqualMajorAxesConic::grad(), GCS::ConstraintEqualFocalDistance::grad(), GCS::ConstraintCurveValue::grad(), GCS::ConstraintPointOnParabola::grad(), GCS::ConstraintEqualLineLength::grad(), GCS::ConstraintC2CDistance::grad(), GCS::ConstraintC2LDistance::grad(), GCS::ConstraintP2CDistance::grad(), and GCS::ConstraintArcLength::grad().
tag
int GCS::Constraint::tag protected
Definition at line 124 of file Constraints.h.
Referenced by Dice3DS.dom3ds.ChunkBase::document_html(), and Dice3DS.dom3ds.ChunkBase::dump_header().
The documentation for this class was generated from the following files:
Constraints.h
Constraints.cpp