FreeCAD: XMLTools Class Reference
XMLTools Class Reference
#include <XMLTools.h>
Static Public Member Functions
static std::string toStdString (const XMLCh *const toTranscode)
static std::basic_string< XMLCh > toXMLString (const char *const fromTranscode)
static void initialize ()
static void terminate ()
Detailed Description
Definition at line 52 of file XMLTools.h.
Member Function Documentation
initialize()
void XMLTools::initialize () static
Definition at line 38 of file XMLTools.cpp.
terminate()
void XMLTools::terminate () static
Definition at line 126 of file XMLTools.cpp.
Referenced by ParameterManager::Terminate(), and src.Mod.AddonManager.addonmanager_workers_startup.CacheMacroCodeWorker::update_and_advance().
toStdString()
std::string XMLTools::toStdString (const XMLCh *const toTranscode) static
Definition at line 53 of file XMLTools.cpp.
References Path.Post.scripts.refactored_centroid_post::str.
Referenced by StrXUTF8::StrXUTF8().
toXMLString()
std::basic_string< XMLCh > XMLTools::toXMLString (const char *const fromTranscode) static
Definition at line 87 of file XMLTools.cpp.
References Path.Post.scripts.refactored_centroid_post::str.
Referenced by XUTF8Str::XUTF8Str().
The documentation for this class was generated from the following files:
XMLTools.h
XMLTools.cpp