FreeCAD: SketcherGui::SoZoomTranslation Class Reference
SketcherGui::SoZoomTranslation Class Reference
#include <SoZoomTranslation.h>
Public Member Functions
SoZoomTranslation ()
float getScaleFactor () const
Static Public Member Functions
static void initClass ()
Public Attributes
SoSFVec3f abPos
Protected Member Functions
~SoZoomTranslation () override
void doAction (SoAction *action) override
void getPrimitiveCount (SoGetPrimitiveCountAction *action) override
void getMatrix (SoGetMatrixAction *action) override
void GLRender (SoGLRenderAction *action) override
void getBoundingBox (SoGetBoundingBoxAction *action) override
void callback (SoCallbackAction *action) override
void pick (SoPickAction *action) override
float calculateScaleFactor (SoAction *action) const
Protected Attributes
float scaleFactor
Detailed Description
Definition at line 54 of file SoZoomTranslation.h.
Constructor & Destructor Documentation
SoZoomTranslation()
SoZoomTranslation::SoZoomTranslation ()
Definition at line 78 of file SoZoomTranslation.cpp.
References abPos, and SCL.SimpleDataTypes::f.
~SoZoomTranslation()
SketcherGui::SoZoomTranslation::~SoZoomTranslation () inline override protected
Definition at line 90 of file SoZoomTranslation.h.
Member Function Documentation
calculateScaleFactor()
float SoZoomTranslation::calculateScaleFactor (SoAction * action) const protected
Definition at line 69 of file SoZoomTranslation.cpp.
References Path.Post.scripts.dynapath_4060_post::action, SCL.SimpleDataTypes::f, and scaleFactor.
Referenced by doAction(), and getMatrix().
callback()
void SoZoomTranslation::callback (SoCallbackAction * action) override protected
Definition at line 139 of file SoZoomTranslation.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
doAction()
void SoZoomTranslation::doAction (SoAction * action) override protected
Definition at line 91 of file SoZoomTranslation.cpp.
References abPos, Path.Post.scripts.dynapath_4060_post::action, calculateScaleFactor(), SCL.SimpleDataTypes::f, and TestSpreadsheet::v.
Referenced by callback(), getBoundingBox(), getPrimitiveCount(), GLRender(), and pick().
getBoundingBox()
void SoZoomTranslation::getBoundingBox (SoGetBoundingBoxAction * action) override protected
Definition at line 144 of file SoZoomTranslation.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
getMatrix()
void SoZoomTranslation::getMatrix (SoGetMatrixAction * action) override protected
Definition at line 113 of file SoZoomTranslation.cpp.
References abPos, Path.Post.scripts.dynapath_4060_post::action, calculateScaleFactor(), SCL.SimpleDataTypes::f, test::m, and TestSpreadsheet::v.
getPrimitiveCount()
void SoZoomTranslation::getPrimitiveCount (SoGetPrimitiveCountAction * action) override protected
Definition at line 155 of file SoZoomTranslation.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
getScaleFactor()
float SketcherGui::SoZoomTranslation::getScaleFactor () const inline
Definition at line 84 of file SoZoomTranslation.h.
GLRender()
void SoZoomTranslation::GLRender (SoGLRenderAction * action) override protected
Definition at line 85 of file SoZoomTranslation.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
initClass()
void SoZoomTranslation::initClass () static
Definition at line 47 of file SoZoomTranslation.cpp.
Referenced by PyMOD_INIT_FUNC().
pick()
void SoZoomTranslation::pick (SoPickAction * action) override protected
Definition at line 149 of file SoZoomTranslation.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
Member Data Documentation
abPos
SoSFVec3f SketcherGui::SoZoomTranslation::abPos
Definition at line 83 of file SoZoomTranslation.h.
Referenced by SketcherGui::EditModeConstraintCoinManager::detectPreselectionConstr(), doAction(), getMatrix(), SketcherGui::EditModeConstraintCoinManager::processConstraints(), and SoZoomTranslation().
scaleFactor
float SketcherGui::SoZoomTranslation::scaleFactor mutable protected
Definition at line 101 of file SoZoomTranslation.h.
Referenced by calculateScaleFactor().
The documentation for this class was generated from the following files:
SoZoomTranslation.h
SoZoomTranslation.cpp