FreeCAD: App::Metadata Class Reference
App::Metadata Class Reference
Reads data from a metadata file.
#include <Metadata.h>
Public Member Functions
Metadata ()
Metadata (const boost::filesystem::path &metadataFile)
Metadata (const XERCES_CPP_NAMESPACE::DOMNode *domNode, int format)
Metadata (const std::string &rawData)
~Metadata ()
std::string name () const
std::string type () const
Meta::Version version () const
std::string date () const
std::string description () const
std::vector< Meta::Contact > maintainer () const
std::vector< Meta::License > license () const
std::vector< Meta::Url > url () const
std::vector< Meta::Contact > author () const
std::vector< Meta::Dependency > depend () const
std::vector< Meta::Dependency > conflict () const
std::vector< Meta::Dependency > replace () const
std::vector< std::string > tag () const
boost::filesystem::path icon () const
std::string classname () const
boost::filesystem::path subdirectory () const
std::vector< boost::filesystem::path > file () const
Meta::Version freecadmin () const
Meta::Version freecadmax () const
Meta::Version pythonmin () const
std::multimap< std::string, Metadata > content () const
std::vector< Meta::GenericMetadata > operator[] (const std::string &tag) const
XERCES_CPP_NAMESPACE::DOMElement * dom () const
void setName (const std::string &name)
void setType (const std::string &type)
void setVersion (const Meta::Version &version)
void setDate (const std::string &date)
void setDescription (const std::string &description)
void addMaintainer (const Meta::Contact &maintainer)
void addLicense (const Meta::License &license)
void addUrl (const Meta::Url &url)
void addAuthor (const Meta::Contact &author)
void addDepend (const Meta::Dependency &dep)
void addConflict (const Meta::Dependency &dep)
void addReplace (const Meta::Dependency &dep)
void addTag (const std::string &tag)
void setIcon (const boost::filesystem::path &path)
void setClassname (const std::string &name)
void setSubdirectory (const boost::filesystem::path &path)
void addFile (const boost::filesystem::path &path)
void addContentItem (const std::string &tag, const Metadata &item)
void setFreeCADMin (const Meta::Version &version)
void setFreeCADMax (const Meta::Version &version)
void setPythonMin (const Meta::Version &version)
void addGenericMetadata (const std::string &tag, const Meta::GenericMetadata &genericMetadata)
void removeContentItem (const std::string &tag, const std::string &itemName)
void removeMaintainer (const Meta::Contact &maintainer)
void removeLicense (const Meta::License &license)
void removeUrl (const Meta::Url &url)
void removeAuthor (const Meta::Contact &author)
void removeDepend (const Meta::Dependency &dep)
void removeConflict (const Meta::Dependency &dep)
void removeReplace (const Meta::Dependency &dep)
void removeTag (const std::string &tag)
void removeFile (const boost::filesystem::path &path)
void clearContent ()
void clearMaintainer ()
void clearLicense ()
void clearUrl ()
void clearAuthor ()
void clearDepend ()
void clearConflict ()
void clearReplace ()
void clearTag ()
void clearFile ()
void write (const boost::filesystem::path &file) const
bool satisfies (const Meta::Dependency &)
bool supportsCurrentFreeCAD () const
Detailed Description
Reads data from a metadata file.
The metadata format is based on https://ros.org/reps/rep-0149.html, modified for FreeCAD use. Full format documentation is available at the FreeCAD Wiki: https://wiki.freecad.org/Package_Metadata
Definition at line 217 of file Metadata.h.
Constructor & Destructor Documentation
Metadata() [1/4]
Metadata::Metadata ()
Definition at line 110 of file Metadata.cpp.
Metadata() [2/4]
App::Metadata::Metadata (const boost::filesystem::path & metadataFile) explicit
Read the data from a file on disk
This constructor takes a path to an XML file and loads the XML from that file as metadata.
Metadata() [3/4]
App::Metadata::Metadata (const XERCES_CPP_NAMESPACE::DOMNode * domNode, int format)
Construct a Metadata object from a DOM node.
This node may have any tag name: it is only accessed via its children, which are expected to follow the standard Metadata format for the contents of the <package> element.
Metadata() [4/4]
App::Metadata::Metadata (const std::string & rawData) explicit
Treat the incoming rawData as metadata to be parsed.
Definition at line 130 of file Metadata.cpp.
~Metadata()
Metadata::~Metadata () default
Member Function Documentation
addAuthor()
void Metadata::addAuthor (const Meta::Contact & author)
Definition at line 338 of file Metadata.cpp.
References author().
addConflict()
void Metadata::addConflict (const Meta::Dependency & dep)
Definition at line 348 of file Metadata.cpp.
addContentItem()
void Metadata::addContentItem (const std::string & tag, const Metadata & item)
Definition at line 383 of file Metadata.cpp.
References tag().
addDepend()
void Metadata::addDepend (const Meta::Dependency & dep)
Definition at line 343 of file Metadata.cpp.
addFile()
void Metadata::addFile (const boost::filesystem::path & path)
Definition at line 378 of file Metadata.cpp.
addGenericMetadata()
void Metadata::addGenericMetadata (const std::string & tag, const Meta::GenericMetadata & genericMetadata)
Definition at line 403 of file Metadata.cpp.
References tag().
addLicense()
void Metadata::addLicense (const Meta::License & license)
Definition at line 328 of file Metadata.cpp.
References license().
addMaintainer()
void Metadata::addMaintainer (const Meta::Contact & maintainer)
Definition at line 323 of file Metadata.cpp.
References maintainer().
addReplace()
void Metadata::addReplace (const Meta::Dependency & dep)
Definition at line 353 of file Metadata.cpp.
addTag()
void Metadata::addTag (const std::string & tag)
Definition at line 358 of file Metadata.cpp.
References tag().
addUrl()
void Metadata::addUrl (const Meta::Url & url)
Definition at line 333 of file Metadata.cpp.
References url().
author()
std::vector< Meta::Contact > Metadata::author () const
Definition at line 214 of file Metadata.cpp.
Referenced by addAuthor(), and removeAuthor().
classname()
std::string Metadata::classname () const
Definition at line 244 of file Metadata.cpp.
clearAuthor()
void Metadata::clearAuthor ()
Definition at line 505 of file Metadata.cpp.
clearConflict()
void Metadata::clearConflict ()
Definition at line 515 of file Metadata.cpp.
clearContent()
void Metadata::clearContent ()
Definition at line 485 of file Metadata.cpp.
clearDepend()
void Metadata::clearDepend ()
Definition at line 510 of file Metadata.cpp.
clearFile()
void Metadata::clearFile ()
Definition at line 530 of file Metadata.cpp.
clearLicense()
void Metadata::clearLicense ()
Definition at line 495 of file Metadata.cpp.
clearMaintainer()
void Metadata::clearMaintainer ()
Definition at line 490 of file Metadata.cpp.
clearReplace()
void Metadata::clearReplace ()
Definition at line 520 of file Metadata.cpp.
clearTag()
void Metadata::clearTag ()
Definition at line 525 of file Metadata.cpp.
clearUrl()
void Metadata::clearUrl ()
Definition at line 500 of file Metadata.cpp.
conflict()
std::vector< Meta::Dependency > Metadata::conflict () const
Definition at line 224 of file Metadata.cpp.
content()
std::multimap< std::string, Metadata > Metadata::content () const
Access the metadata for the content elements of this package
In addition to the overall package metadata, this class reads in metadata contained in a <content> element. Each entry in the content element is an element representing some type of package content (e.g. add-on, macro, theme, etc.). This class places no restriction on the types, it is up to client code to place requirements on the metadata included here.
For example, themes might be specified: <content> <theme> <name>High Contrast</name> </theme> </content>
Definition at line 274 of file Metadata.cpp.
Referenced by Gui::PreferencePackManager::getPacksFromDirectory().
date()
std::string App::Metadata::date () const
Definition at line 189 of file Metadata.cpp.
depend()
std::vector< Meta::Dependency > Metadata::depend () const
Definition at line 219 of file Metadata.cpp.
description()
std::string Metadata::description () const
Definition at line 194 of file Metadata.cpp.
Referenced by setDescription().
dom()
XERCES_CPP_NAMESPACE::DOMElement * Metadata::dom () const
Directly access the DOM tree to support unrecognized multi-level metadata
Definition at line 289 of file Metadata.cpp.
file()
std::vector< fs::path > Metadata::file () const
Definition at line 254 of file Metadata.cpp.
Referenced by write().
freecadmax()
Meta::Version Metadata::freecadmax () const
Definition at line 264 of file Metadata.cpp.
freecadmin()
Meta::Version Metadata::freecadmin () const
Definition at line 259 of file Metadata.cpp.
icon()
fs::path Metadata::icon () const
Definition at line 239 of file Metadata.cpp.
license()
std::vector< Meta::License > Metadata::license () const
Definition at line 204 of file Metadata.cpp.
Referenced by addLicense(), and removeLicense().
maintainer()
std::vector< Meta::Contact > Metadata::maintainer () const
Definition at line 199 of file Metadata.cpp.
Referenced by addMaintainer(), and removeMaintainer().
name()
std::string Metadata::name () const
Definition at line 174 of file Metadata.cpp.
Referenced by Gui::PreferencePack::name(), src.Mod.AddonManager.addonmanager_licenses.SPDXLicenseManager::normalize(), setClassname(), and setName().
operator[]()
std::vector< Meta::GenericMetadata > Metadata::operator[] (const std::string & tag) const
Convenience accessor for unrecognized simple metadata.
If the XML parser encounters tags that it does not recognize, and those tags have no children, a GenericMetadata object is created. Those objects can be accessed using operator[], which returns a (potentially empty) vector containing all instances of the given tag. It cannot be used to create a new tag, however. See addGenericMetadata().
Definition at line 279 of file Metadata.cpp.
References tag().
pythonmin()
Meta::Version Metadata::pythonmin () const
Definition at line 269 of file Metadata.cpp.
removeAuthor()
void Metadata::removeAuthor (const Meta::Contact & author)
Definition at line 439 of file Metadata.cpp.
References author().
removeConflict()
void Metadata::removeConflict (const Meta::Dependency & dep)
Definition at line 460 of file Metadata.cpp.
removeContentItem()
void Metadata::removeContentItem (const std::string & tag, const std::string & itemName)
Definition at line 409 of file Metadata.cpp.
References ArchCommands::check(), and tag().
removeDepend()
void Metadata::removeDepend (const Meta::Dependency & dep)
Definition at line 445 of file Metadata.cpp.
References ArchCommands::check().
removeFile()
void Metadata::removeFile (const boost::filesystem::path & path)
Definition at line 478 of file Metadata.cpp.
removeLicense()
void Metadata::removeLicense (const Meta::License & license)
Definition at line 427 of file Metadata.cpp.
References license().
removeMaintainer()
void Metadata::removeMaintainer (const Meta::Contact & maintainer)
Definition at line 421 of file Metadata.cpp.
References maintainer().
removeReplace()
void Metadata::removeReplace (const Meta::Dependency & dep)
Definition at line 466 of file Metadata.cpp.
removeTag()
void Metadata::removeTag (const std::string & tag)
Definition at line 472 of file Metadata.cpp.
References tag().
removeUrl()
void Metadata::removeUrl (const Meta::Url & url)
Definition at line 433 of file Metadata.cpp.
References url().
replace()
std::vector< Meta::Dependency > Metadata::replace () const
Definition at line 229 of file Metadata.cpp.
satisfies()
bool Metadata::satisfies (const Meta::Dependency & dep)
Determine whether this package satisfies the given dependency
Definition at line 663 of file Metadata.cpp.
References App::Meta::Dependency::condition, App::Application::Config(), App::Meta::Dependency::package, App::Expression::parse(), RobotExample::pos, result, src.Mod.AddonManager.addonmanager_freecad_interface::Version, App::Meta::Dependency::version_eq, App::Meta::Dependency::version_gt, App::Meta::Dependency::version_gte, App::Meta::Dependency::version_lt, and App::Meta::Dependency::version_lte.
setClassname()
void Metadata::setClassname (const std::string & name)
Definition at line 368 of file Metadata.cpp.
References name().
setDate()
void App::Metadata::setDate (const std::string & date)
Definition at line 313 of file Metadata.cpp.
setDescription()
void Metadata::setDescription (const std::string & description)
Definition at line 318 of file Metadata.cpp.
References description().
setFreeCADMax()
void Metadata::setFreeCADMax (const Meta::Version & version)
Definition at line 398 of file Metadata.cpp.
References version().
setFreeCADMin()
void Metadata::setFreeCADMin (const Meta::Version & version)
Definition at line 388 of file Metadata.cpp.
References version().
setIcon()
void Metadata::setIcon (const boost::filesystem::path & path)
Definition at line 363 of file Metadata.cpp.
setName()
void Metadata::setName (const std::string & name)
Definition at line 294 of file Metadata.cpp.
References name().
setPythonMin()
void Metadata::setPythonMin (const Meta::Version & version)
Definition at line 393 of file Metadata.cpp.
References version().
setSubdirectory()
void Metadata::setSubdirectory (const boost::filesystem::path & path)
Definition at line 373 of file Metadata.cpp.
setType()
void Metadata::setType (const std::string & type)
Definition at line 303 of file Metadata.cpp.
References type().
setVersion()
void Metadata::setVersion (const Meta::Version & version)
Definition at line 308 of file Metadata.cpp.
References version().
subdirectory()
boost::filesystem::path Metadata::subdirectory () const
Definition at line 249 of file Metadata.cpp.
supportsCurrentFreeCAD()
bool Metadata::supportsCurrentFreeCAD () const
Determine whether the current metadata specifies support for the currently-running version of FreeCAD. Does not interrogate content items, which must be queried individually.
Definition at line 721 of file Metadata.cpp.
References App::Application::Config(), and src.Mod.AddonManager.addonmanager_freecad_interface::Version.
tag()
std::vector< std::string > Metadata::tag () const
Definition at line 234 of file Metadata.cpp.
Referenced by addContentItem(), addGenericMetadata(), addTag(), Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.ChunkBase::dump_header(), operator[](), removeContentItem(), and removeTag().
type()
std::string Metadata::type () const
Definition at line 179 of file Metadata.cpp.
Referenced by setType().
url()
std::vector< Meta::Url > Metadata::url () const
Definition at line 209 of file Metadata.cpp.
Referenced by addUrl(), and removeUrl().
version()
Meta::Version Metadata::version () const
Definition at line 184 of file Metadata.cpp.
Referenced by Gui::Dialog::AboutDialog::addModuleInfo(), setFreeCADMax(), setFreeCADMin(), setPythonMin(), and setVersion().
write()
void Metadata::write (const boost::filesystem::path & file) const
Write the metadata to an XML file
Definition at line 608 of file Metadata.cpp.
References toolbit-attributes::doc, and file().
The documentation for this class was generated from the following files:
Metadata.h
Metadata.cpp