FreeCAD: App::PropertyXLinkSubList Class Reference
App::PropertyXLinkSubList Class Reference
#include <PropertyLinks.h>
Public Types
using atomic_change = typename AtomicPropertyChangeInterface< PropertyXLinkSubList >::AtomicPropertyChange
Public Types inherited from App::PropertyLinkBase
enum LinkFlags {
LinkAllowExternal, LinkDetached, LinkRestoring, LinkAllowPartial,
LinkRestoreLabel, LinkSyncSubObject, LinkNewElement, LinkSilentRestore
}
using ShadowSub = ElementNamePair
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Public Member Functions
PropertyXLinkSubList ()
~PropertyXLinkSubList () override
void afterRestore () override
void onContainerRestored () override
int getSize () const
void setValue (DocumentObject *, const char *)
void setValues (const std::vector< DocumentObject * > &)
void set1Value (int idx, DocumentObject *value, const std::vector< std::string > &SubList={})
void setValues (const std::vector< DocumentObject * > &, const std::vector< const char * > &)
void setValues (const std::vector< DocumentObject * > &, const std::vector< std::string > &)
void setValues (std::map< App::DocumentObject *, std::vector< std::string >> &&)
void setValues (const std::map< App::DocumentObject *, std::vector< std::string >> &)
void addValue (App::DocumentObject *obj, const std::vector< std::string > &SubList={}, bool reset=false)
void addValue (App::DocumentObject *obj, std::vector< std::string > &&SubList={}, bool reset=false)
void setValue (App::DocumentObject *lValue, const std::vector< std::string > &SubList={})
setValue: PropertyLinkSub-compatible overload
std::vector< DocumentObject * > getValues () const
const std::string getPyReprString () const
DocumentObject * getValue () const
const std::vector< std::string > & getSubValues (App::DocumentObject *obj) const
std::vector< std::string > getSubValues (App::DocumentObject *obj, bool newStyle) const
const std::vector< ShadowSub > & getShadowSubs (App::DocumentObject *obj) const
int removeValue (App::DocumentObject *lValue)
Removes all occurrences of lValue in the property together with its sub-elements and returns the number of entries removed.
void setSubListValues (const std::vector< PropertyLinkSubList::SubSet > &)
const std::list< PropertyXLinkSub > & getSubListValues () const
PyObject * getPyObject () override
void setPyObject (PyObject *value) override
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
Property * Copy () const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
const char * getEditorName () const override
Get the class name of the associated property editor item.
Property * CopyOnImportExternal (const std::map< std::string, std::string > &nameMap) const override
Property * CopyOnLabelChange (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const override
Property * CopyOnLinkReplace (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const override
unsigned int getMemSize () const override
void updateElementReference (DocumentObject *feature, bool reverse=false, bool notify=false) override
bool referenceChanged () const override
Test if the element reference has changed after restore.
void getLinks (std::vector< App::DocumentObject * > &objs, bool all=false, std::vector< std::string > *subs=nullptr, bool newStyle=true) const override
void getLinksTo (std::vector< App::ObjectIdentifier > &identifiers, App::DocumentObject *obj, const char *subname=nullptr, bool all=false) const override
void breakLink (App::DocumentObject *obj, bool clear) override
bool adjustLink (const std::set< App::DocumentObject * > &inList) override
bool upgrade (Base::XMLReader &reader, const char *typeName)
int checkRestore (std::string *msg=nullptr) const override
void setAllowPartial (bool enable) override
void hasSetChildValue (Property &) override
Called when a child property has changed value.
void aboutToSetChildValue (Property &) override
Called before a child property changing value.
void setSyncSubObject (bool enable)
Public Member Functions inherited from App::PropertyLinkBase
PropertyLinkBase ()
~PropertyLinkBase () override
void unregisterElementReference ()
Clear internal element reference registration.
void registerLabelReferences (std::vector< std::string > &&labels, bool reset=true)
void checkLabelReferences (const std::vector< std::string > &subs, bool reset=true)
void unregisterLabelReferences ()
Clear internal label references registration.
std::vector< App::DocumentObject * > linkedObjects (bool all=false) const
Helper function to return all linked objects of this property.
template<class T >
void getLinkedObjects (T &inserter, bool all=false) const
Helper function to return linked objects using an std::inserter.
void getLinkedElements (std::map< App::DocumentObject *, std::vector< std::string >> &elements, bool newStyle=true, bool all=false) const
Helper function to return a map of linked object and its subname references.
std::map< App::DocumentObject *, std::vector< std::string > > linkedElements (bool newStyle=true, bool all=false) const
Helper function to return a map of linked object and its subname references.
bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
void setAllowExternal (bool allow)
bool _updateElementReference (App::DocumentObject *feature, App::DocumentObject *obj, std::string &sub, ShadowSub &shadow, bool reverse, bool notify=false)
void _registerElementReference (App::DocumentObject *obj, std::string &sub, ShadowSub &shadow)
bool testFlag (int flag) const
void setReturnNewElement (bool enable)
void setSilentRestore (bool enable)
Public Member Functions inherited from App::Property
Property ()
~Property () override
const char * getName () const
bool hasName () const
std::string getFullName () const
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
int64_t getID () const
virtual void beforeSave () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::ScopedLink
void setScope (LinkScope scope)
Set the links scope Allows to define what kind of links are allowed. Only in the Local GeoFeatureGroup, in this and all Childs or to all objects within the Glocal scope.
LinkScope getScope () const
Get the links scope Retrieve what kind of links are allowed. Only in the Local GeoFeatureGroup, in this and all Childs or to all objects within the Glocal scope.
Public Attributes
friend atomic_change
Public Attributes inherited from App::PropertyLinkBase
boost::signals2::signal< void(const std::string &, const std::string &)> signalUpdateElementReference
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions
void _getLinksToList (std::vector< App::ObjectIdentifier > &identifiers, App::DocumentObject *obj, const char *subname, const std::vector< std::string > &subs, const std::vector< PropertyLinkBase::ShadowSub > &shadows) const
Protected Member Functions inherited from App::PropertyLinkBase
void hasSetValue () override
Gets called by all setValue() methods after the value has changed.
void setFlag (int flag, bool value=true)
void _getLinksTo (std::vector< App::ObjectIdentifier > &identifiers, App::DocumentObject *obj, const char *subname, const std::vector< std::string > &subs, const std::vector< PropertyLinkBase::ShadowSub > &shadows) const
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue ()
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Protected Member Functions inherited from App::AtomicPropertyChangeInterface< PropertyXLinkSubList >
AtomicPropertyChangeInterface ()=default
Protected Attributes
std::list< PropertyXLinkSub > _Links
Protected Attributes inherited from App::PropertyLinkBase
std::bitset< 32 > _Flags
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::ScopedLink
LinkScope _pcScope = LinkScope::Local
Protected Attributes inherited from App::AtomicPropertyChangeInterface< PropertyXLinkSubList >
int signalCounter
bool hasChanged
Additional Inherited Members
Static Public Member Functions inherited from App::PropertyLinkBase
static std::pair< App::DocumentObject *, std::string > tryReplaceLink (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const char *sub=nullptr)
Helper functions.
static std::pair< App::DocumentObject *, std::vector< std::string > > tryReplaceLinkSubs (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const std::vector< std::string > &subs)
static void updateElementReferences (DocumentObject *feature, bool reverse=false)
Update all element references in all link properties of feature.
static const std::unordered_set< PropertyLinkBase * > & getElementReferences (DocumentObject *)
Obtain link properties that contain element references to a given object.
static void breakLinks (App::DocumentObject *link, const std::vector< App::DocumentObject * > &objs, bool clear)
static std::string tryImportSubName (const App::DocumentObject *obj, const char *sub, const App::Document *doc, const std::map< std::string, std::string > &nameMap)
static App::DocumentObject * tryImport (const App::Document *doc, const App::DocumentObject *obj, const std::map< std::string, std::string > &nameMap)
static const char * exportSubName (std::string &output, const App::DocumentObject *obj, const char *subname, bool first_obj=false)
static std::string importSubName (Base::XMLReader &reader, const char *sub, bool &restoreLabel)
static void restoreLabelReference (const App::DocumentObject *obj, std::string &sub, ShadowSub *shadow=nullptr)
static void getLabelReferences (std::vector< std::string > &labels, const char *subname)
static std::vector< std::pair< Property *, std::unique_ptr< Property > > > updateLabelReferences (App::DocumentObject *obj, const char *newLabel)
static std::string updateLabelReference (const App::DocumentObject *linked, const char *subname, App::DocumentObject *obj, const std::string &ref, const char *newLabel)
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Link to one or more (sub)object(s) of one or more object(s) from the same or different document
Definition at line 1430 of file PropertyLinks.h.
Member Typedef Documentation
atomic_change
using App::PropertyXLinkSubList::atomic_change = typename AtomicPropertyChangeInterface<PropertyXLinkSubList>::AtomicPropertyChange
Definition at line 1437 of file PropertyLinks.h.
Constructor & Destructor Documentation
PropertyXLinkSubList()
PropertyXLinkSubList::PropertyXLinkSubList ()
Definition at line 4788 of file PropertyLinks.cpp.
References App::Global.
Referenced by Copy().
~PropertyXLinkSubList()
PropertyXLinkSubList::~PropertyXLinkSubList () override default
Member Function Documentation
_getLinksToList()
void PropertyXLinkSubList::_getLinksToList (std::vector< App::ObjectIdentifier > & identifiers, App::DocumentObject * obj, const char * subname, const std::vector< std::string > & subs, const std::vector< PropertyLinkBase::ShadowSub > & shadows) const protected
Definition at line 5398 of file PropertyLinks.cpp.
References App::SubObjectT::getOldElementName(), App::SubObjectT::getSubObject(), SplineSurface::i, and importers.importIFCmulticore::subs.
Referenced by getLinksTo().
aboutToSetChildValue()
void PropertyXLinkSubList::aboutToSetChildValue (Property &) override virtual
Called before a child property changing value.
Reimplemented from App::Property.
Definition at line 5580 of file PropertyLinks.cpp.
References App::Property::aboutToSetValue(), App::AtomicPropertyChangeInterface< PropertyXLinkSubList >::hasChanged, and App::AtomicPropertyChangeInterface< PropertyXLinkSubList >::signalCounter.
addValue() [1/2]
void PropertyXLinkSubList::addValue (App::DocumentObject * obj, const std::vector< std::string > & SubList = {}, bool reset = false)
Definition at line 4896 of file PropertyLinks.cpp.
References importers.importIFCmulticore::subs.
Referenced by set1Value().
addValue() [2/2]
void PropertyXLinkSubList::addValue (App::DocumentObject * obj, std::vector< std::string > && SubList = {}, bool reset = false)
Definition at line 4903 of file PropertyLinks.cpp.
References _Links, FC_THROWM, App::DocumentObject::isAttachedToDocument(), RobotExample::l, App::PropertyLinkBase::LinkAllowPartial, Path.Post.scripts.opensbp_post::move(), toolbit-attributes::s, importers.importIFCmulticore::subs, and App::PropertyLinkBase::testFlag().
adjustLink()
bool PropertyXLinkSubList::adjustLink (const std::set< App::DocumentObject * > & inList) override virtual
Called to adjust the link to avoid potential cyclic dependency
Parameters
inList recursive in-list of the would-be parent
Returns
Return whether the link has been adjusted
This function tries to correct the link to avoid any (sub)object inside in-list. If the adjustment is impossible, exception will be raised
Implements App::PropertyLinkBase.
Definition at line 5482 of file PropertyLinks.cpp.
References _Links, App::ScopedLink::_pcScope, adjustLinkSubs(), src.Mod.AddonManager.NetworkManager::count, App::Hidden, App::DocumentObject::isAttachedToDocument(), RobotExample::l, Path.Post.scripts.opensbp_post::move(), and setValues().
afterRestore()
void PropertyXLinkSubList::afterRestore () override virtual
Called at the beginning of Document::afterRestore()
This function is called without dependency sorting, because some types of link property can only reconstructs the linking information inside this function.
One example use case of this function is PropertyLinkSub that uses afterRestore() to parse and restore subname references, which may contain sub-object reference from external document, and there will be special mapping required during object import.
Another example is PropertyExpressionEngine which only parse the restored expression in afterRestore(). The reason, in addition to subname mapping like PropertyLinkSub, is that it can handle document name adjustment as well. It internally relies on PropertyXLink to store the external document path for external linking. When the external document is restored, its internal name may change due to name conflict with existing documents. PropertyExpressionEngine can now auto adjust external references without any problem.
Reimplemented from App::Property.
Definition at line 5093 of file PropertyLinks.cpp.
References _Links, and RobotExample::l.
breakLink()
void PropertyXLinkSubList::breakLink (App::DocumentObject * obj, bool clear) override virtual
Called to reset this link property
Parameters
obj reset link property if it is linked to this object
clear if true, then also reset property if the owner of this property is obj
See also
breakLinks()
Implements App::PropertyLinkBase.
Definition at line 5466 of file PropertyLinks.cpp.
References _Links, Path.Op.Gui.Selection::clear(), App::Property::getContainer(), RobotExample::l, and setValue().
checkRestore()
int PropertyXLinkSubList::checkRestore (std::string * msg = nullptr) const override virtual
Test if the link is restored unchanged
Parameters
msg optional error message
Returns
For external linked object, return 2 in case the link is missing, and 1 if the time stamp has changed.
Reimplemented from App::PropertyLinkBase.
Definition at line 5518 of file PropertyLinks.cpp.
References _Links, RobotExample::l, and Path.Op.Surface::msg.
Copy()
Property * PropertyXLinkSubList::Copy () const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 5290 of file PropertyLinks.cpp.
References _Links, RobotExample::l, App::PropertyLinkBase::LinkAllowPartial, buildPsets::p, PropertyXLinkSubList(), and App::PropertyLinkBase::testFlag().
CopyOnImportExternal()
Property * PropertyXLinkSubList::CopyOnImportExternal (const std::map< std::string, std::string > & nameMap) const override virtual
Return a copy of the property if any changes caused by importing external linked object
Parameters
nameMap a map from the original external object name to the imported new object name
Returns
Returns a copy of the property with the updated link reference if affected. The copy will later be assgiend to this property by calling its Paste().
Reimplemented from App::PropertyLinkBase.
Definition at line 5158 of file PropertyLinks.cpp.
References _Links, App::PropertyXLink::copyTo(), and buildPsets::p.
CopyOnLabelChange()
Property * PropertyXLinkSubList::CopyOnLabelChange (App::DocumentObject * obj, const std::string & ref, const char * newLabel) const override virtual
Update object label reference in this property
Parameters
obj the object owner of the changing label
ref subname reference to old label
newLabel the future new label
Returns
Returns a copy of the property if its link reference is affected. The copy will later be assgiend to this property by calling its Paste().
Reimplemented from App::PropertyLinkBase.
Definition at line 5191 of file PropertyLinks.cpp.
References _Links, App::PropertyXLink::copyTo(), and buildPsets::p.
CopyOnLinkReplace()
Property * PropertyXLinkSubList::CopyOnLinkReplace (const App::DocumentObject * parent, App::DocumentObject * oldObj, App::DocumentObject * newObj) const override virtual
Return a copy of the property if the link replacement affects this property
Parameters
owner the parent object whose link property is to be replace. Note that The parent may not be the container of this property. Link sub property can use this opportunity to adjust its relative links.
oldObj object to be replaced
newObj object to replace with
Returns
Return a copy of the property that is adjusted for the link replacement operation.
Implements App::PropertyLinkBase.
Definition at line 5226 of file PropertyLinks.cpp.
References _Links, App::PropertyXLink::_SubList, App::PropertyXLink::copyTo(), App::PropertyXLink::getSubValues(), App::PropertyLink::getValue(), buildPsets::p, Init::parent, and importers.importIFCmulticore::subs.
getEditorName()
const char* App::PropertyXLinkSubList::getEditorName () const inline override virtual
Get the class name of the associated property editor item.
Reimplemented from App::Property.
Definition at line 1506 of file PropertyLinks.h.
getLinks()
void PropertyXLinkSubList::getLinks (std::vector< App::DocumentObject * > & objs, bool all = false, std::vector< std::string > * subs = nullptr, bool newStyle = true) const override virtual
Obtain the linked objects
Parameters
objs hold the returned linked objects on output
all if true, then return all the linked object regardless of this LinkScope. If false, then return only if the LinkScope is not hidden.
sub if given, then return subname references.
newStyle whether to return new or old style subname reference
Implements App::PropertyLinkBase.
Definition at line 5345 of file PropertyLinks.cpp.
References _Links, App::ScopedLink::_pcScope, src.Mod.AddonManager.NetworkManager::count, App::Hidden, App::DocumentObject::isAttachedToDocument(), RobotExample::l, KDL::max(), Path.Post.scripts.opensbp_post::move(), replaceobj::objs, and importers.importIFCmulticore::subs.
Referenced by TechDraw::DrawProjGroup::getAllSources(), and getValues().
getLinksTo()
void PropertyXLinkSubList::getLinksTo (std::vector< App::ObjectIdentifier > & identifiers, App::DocumentObject * obj, const char * subname = nullptr, bool all = false) const override virtual
Obtain identifiers from this link property that link to a given object
Parameters
identifiers holds the returned identifier to reference the given object
obj the referenced object
subname optional subname reference
all if true, then return all the references regardless of this LinkScope. If false, then return only if the LinkScope is not hidden.
Implements App::PropertyLinkBase.
Definition at line 5451 of file PropertyLinks.cpp.
References _getLinksToList(), _Links, App::ScopedLink::_pcScope, App::Hidden, and RobotExample::l.
getMemSize()
unsigned int PropertyXLinkSubList::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence
See also
Base::Persistence
Reimplemented from App::Property.
Definition at line 5315 of file PropertyLinks.cpp.
References _Links, and RobotExample::l.
getPyObject()
PyObject * PropertyXLinkSubList::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Reimplemented in App::PropertyXLinkList.
Definition at line 5034 of file PropertyLinks.cpp.
References _Links, App::DocumentObject::getPyObject(), App::DocumentObject::isAttachedToDocument(), src.Mod.Test.testPathArray::items, Py::new_reference_to(), src.Mod.Test.testmakeWireString::String, importers.importIFCmulticore::subs, and DraftVecUtils::tup().
Referenced by App::PropertyXLinkList::getPyObject().
getPyReprString()
const string PropertyXLinkSubList::getPyReprString () const
Definition at line 4979 of file PropertyLinks.cpp.
References _Links, App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), App::DocumentObject::isAttachedToDocument(), and importers.importIFCmulticore::subs.
getShadowSubs()
const std::vector<ShadowSub>& App::PropertyXLinkSubList::getShadowSubs (App::DocumentObject * obj) const
getSize()
int PropertyXLinkSubList::getSize () const
Definition at line 4801 of file PropertyLinks.cpp.
References _Links.
Referenced by set1Value().
getSubListValues()
const std::list<PropertyXLinkSub>& App::PropertyXLinkSubList::getSubListValues () const inline
Definition at line 1492 of file PropertyLinks.h.
Referenced by PartDesign::SubShapeBinder::checkCopyOnChange(), PartDesign::SubShapeBinder::collapseGeoChildren(), PartDesign::SubShapeBinder::getSubObject(), PartDesign::SubShapeBinder::onChanged(), PartDesign::SubShapeBinder::setLinks(), PartDesign::SubShapeBinder::setupCopyOnChange(), and PartDesign::SubShapeBinder::update().
getSubValues() [1/2]
const std::vector< std::string > & PropertyXLinkSubList::getSubValues (App::DocumentObject * obj) const
Definition at line 5324 of file PropertyLinks.cpp.
References _Links, FC_THROWM, and RobotExample::l.
getSubValues() [2/2]
std::vector< std::string > PropertyXLinkSubList::getSubValues (App::DocumentObject * obj, bool newStyle) const
Definition at line 5334 of file PropertyLinks.cpp.
References _Links, and RobotExample::l.
getValue()
DocumentObject * PropertyXLinkSubList::getValue () const
Definition at line 5008 of file PropertyLinks.cpp.
References _Links.
getValues()
std::vector< App::DocumentObject * > PropertyXLinkSubList::getValues () const
Definition at line 5590 of file PropertyLinks.cpp.
References getLinks().
Referenced by TechDraw::DrawProjGroup::addProjection(), TechDraw::DrawViewPart::getAllSources(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::loadDefaults(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle(), TechDrawGui::TaskComplexSection::saveSectionState(), TechDrawGui::TaskComplexSection::TaskComplexSection(), and TechDraw::DrawProjGroup::updateChildrenSource().
hasSetChildValue()
void PropertyXLinkSubList::hasSetChildValue (Property &) override virtual
Called when a child property has changed value.
Reimplemented from App::Property.
Definition at line 5573 of file PropertyLinks.cpp.
References App::PropertyLinkBase::hasSetValue(), and App::AtomicPropertyChangeInterface< PropertyXLinkSubList >::signalCounter.
onContainerRestored()
void PropertyXLinkSubList::onContainerRestored () override virtual
Called before calling DocumentObject::onDocumentRestored()
This function is called after finished calling Property::afterRestore() of all properties of objects. By then, the object dependency information is assumed ready. So, unlike Property::afterRestore(), this function is called on objects with dependency order.
Reimplemented from App::Property.
Definition at line 5100 of file PropertyLinks.cpp.
References _Links, and RobotExample::l.
Paste()
void PropertyXLinkSubList::Paste (const Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 5300 of file PropertyLinks.cpp.
References _Links, App::Property::aboutToSetValue(), Base::Persistence::getClassTypeId(), App::PropertyLinkBase::hasSetValue(), Base::BaseClass::isDerivedFrom(), RobotExample::l, App::PropertyLinkBase::LinkAllowPartial, and App::PropertyLinkBase::testFlag().
referenceChanged()
bool PropertyXLinkSubList::referenceChanged () const override virtual
Test if the element reference has changed after restore.
Reimplemented from App::PropertyLinkBase.
Definition at line 5116 of file PropertyLinks.cpp.
References _Links, and RobotExample::l.
removeValue()
int PropertyXLinkSubList::removeValue (App::DocumentObject * lValue)
Removes all occurrences of lValue in the property together with its sub-elements and returns the number of entries removed.
Definition at line 5016 of file PropertyLinks.cpp.
References _Links.
Referenced by PartDesign::SubShapeBinder::collapseGeoChildren().
Restore()
void PropertyXLinkSubList::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 5141 of file PropertyLinks.cpp.
References _Links, src.Mod.AddonManager.NetworkManager::count, SplineSurface::i, App::PropertyLinkBase::LinkAllowPartial, TechDrawTools.TaskFillTemplateFields::reader, and App::PropertyLinkBase::setFlag().
Save()
void PropertyXLinkSubList::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 5126 of file PropertyLinks.cpp.
References _Links, Base::Writer::decInd(), Base::Writer::incInd(), Base::Writer::ind(), RobotExample::l, App::PropertyLinkBase::LinkAllowPartial, Base::Writer::Stream(), and App::PropertyLinkBase::testFlag().
set1Value()
void PropertyXLinkSubList::set1Value (int idx, DocumentObject * value, const std::vector< std::string > & SubList = {})
Definition at line 4952 of file PropertyLinks.cpp.
References _Links, addValue(), getSize(), App::PropertyLinkBase::LinkAllowPartial, and App::PropertyLinkBase::testFlag().
setAllowPartial()
void PropertyXLinkSubList::setAllowPartial (bool enable) override virtual
Reimplemented from App::PropertyLinkBase.
Definition at line 5565 of file PropertyLinks.cpp.
References _Links, RobotExample::l, App::PropertyLinkBase::LinkAllowPartial, and App::PropertyLinkBase::setFlag().
Referenced by PartDesign::SubShapeBinder::checkPropertyStatus().
setPyObject()
void PropertyXLinkSubList::setPyObject (PyObject * value) override virtual
Reimplemented from Base::BaseClass.
Reimplemented in App::PropertyXLinkList.
Definition at line 5057 of file PropertyLinks.cpp.
References App::PropertyLinkSub::getSubValues(), App::PropertyLinkSub::getValue(), SplineSurface::i, Path.Post.scripts.opensbp_post::move(), toolbit-attributes::s, App::PropertyLinkBase::setAllowExternal(), App::PropertyLinkSub::setPyObject(), setValue(), setValues(), and importers.importIFCmulticore::subs.
Referenced by App::PropertyXLinkList::setPyObject().
setSubListValues()
void PropertyXLinkSubList::setSubListValues (const std::vector< PropertyLinkSubList::SubSet > & svalues)
Definition at line 4850 of file PropertyLinks.cpp.
References Path.Post.scripts.opensbp_post::move(), toolbit-attributes::s, setValues(), and TestSpreadsheet::v.
setSyncSubObject()
void PropertyXLinkSubList::setSyncSubObject (bool enable)
Definition at line 4796 of file PropertyLinks.cpp.
References App::PropertyLinkBase::_Flags, and App::PropertyLinkBase::LinkSyncSubObject.
setValue() [1/2]
void PropertyXLinkSubList::setValue (App::DocumentObject * lValue, const std::vector< std::string > & SubList = {})
setValue: PropertyLinkSub-compatible overload
Parameters
SubList
Definition at line 4932 of file PropertyLinks.cpp.
References Path.Post.scripts.opensbp_post::move(), and setValues().
setValue() [2/2]
void PropertyXLinkSubList::setValue (DocumentObject * lValue, const char * SubName)
Sets the property. setValue(0, whatever) clears the property
Definition at line 4806 of file PropertyLinks.cpp.
References Path.Post.scripts.opensbp_post::move(), setValues(), and importers.importIFCmulticore::subs.
Referenced by breakLink(), PartDesign::SubShapeBinder::onChanged(), PartDesign::SubShapeBinder::setLinks(), and setPyObject().
setValues() [1/5]
void PropertyXLinkSubList::setValues (const std::map< App::DocumentObject *, std::vector< std::string >> & values)
Definition at line 4861 of file PropertyLinks.cpp.
References setValues().
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle().
setValues() [2/5]
void PropertyXLinkSubList::setValues (const std::vector< DocumentObject * > & values)
Definition at line 4941 of file PropertyLinks.cpp.
References _Links, App::PropertyLinkBase::LinkAllowPartial, and App::PropertyLinkBase::testFlag().
Referenced by TechDraw::DrawProjGroup::addProjection(), adjustLink(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle(), PartDesign::SubShapeBinder::setLinks(), setPyObject(), App::PropertyXLinkList::setPyObject(), setSubListValues(), setValue(), setValues(), TechDrawGui::TaskProjGroup::turnViewToProjGroup(), and upgrade().
setValues() [3/5]
void PropertyXLinkSubList::setValues (const std::vector< DocumentObject * > & lValue, const std::vector< const char * > & lSubNames)
Definition at line 4818 of file PropertyLinks.cpp.
References CHECK_SUB_SIZE, SplineSurface::i, Path.Post.scripts.opensbp_post::move(), and setValues().
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle().
setValues() [4/5]
void PropertyXLinkSubList::setValues (const std::vector< DocumentObject * > & lValue, const std::vector< std::string > & lSubNames)
Definition at line 4838 of file PropertyLinks.cpp.
References CHECK_SUB_SIZE, SplineSurface::i, Path.Post.scripts.opensbp_post::move(), and setValues().
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle().
setValues() [5/5]
void PropertyXLinkSubList::setValues (std::map< App::DocumentObject *, std::vector< std::string >> && values)
Definition at line 4867 of file PropertyLinks.cpp.
References _Links, FC_THROWM, App::PropertyLinkBase::LinkAllowPartial, Path.Post.scripts.opensbp_post::move(), App::PropertyLinkBase::testFlag(), and TestSpreadsheet::v.
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle().
updateElementReference()
void PropertyXLinkSubList::updateElementReference (DocumentObject * feature, bool reverse = false, bool notify = false) override virtual
Link type property interface APIs These APIs are moved here so that any type of property can have the property link behavior, e.g. the PropertyExpressionEngine Called to update the element reference of this link property
See also
_updateElementReference()
Reimplemented from App::PropertyLinkBase.
Definition at line 5107 of file PropertyLinks.cpp.
References _Links, RobotExample::l, and femsolver.signal::notify().
upgrade()
bool PropertyXLinkSubList::upgrade (Base::XMLReader & reader, const char * typeName)
Definition at line 5529 of file PropertyLinks.cpp.
References _Links, Base::Persistence::getClassTypeId(), App::Property::getContainer(), App::Property::getName(), App::PropertyLinkSubList::getSubValues(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyLinkSubList::getValues(), SplineSurface::i, App::PropertyLinkBase::LinkAllowPartial, Path.Post.scripts.opensbp_post::move(), replaceobj::objs, TechDrawTools.TaskFillTemplateFields::reader, App::PropertyLinkList::Restore(), App::PropertyLinkSubList::Restore(), App::Property::setContainer(), setValues(), importers.importIFCmulticore::subs, and App::PropertyLinkBase::testFlag().
Referenced by PartDesign::SubShapeBinder::handleChangedPropertyType().
Member Data Documentation
_Links
std::list<PropertyXLinkSub> App::PropertyXLinkSubList::_Links protected
Definition at line 1563 of file PropertyLinks.h.
Referenced by addValue(), adjustLink(), afterRestore(), breakLink(), checkRestore(), Copy(), CopyOnImportExternal(), CopyOnLabelChange(), CopyOnLinkReplace(), getLinks(), getLinksTo(), getMemSize(), getPyObject(), App::PropertyXLinkList::getPyObject(), getPyReprString(), getSize(), getSubValues(), getValue(), onContainerRestored(), Paste(), referenceChanged(), removeValue(), Restore(), Save(), set1Value(), setAllowPartial(), setValues(), updateElementReference(), and upgrade().
atomic_change
friend App::PropertyXLinkSubList::atomic_change
Definition at line 1438 of file PropertyLinks.h.
The documentation for this class was generated from the following files:
PropertyLinks.h
PropertyLinks.cpp