FreeCAD: MatGui::ImageEdit Class Reference
MatGui::ImageEdit Class Reference
#include <ImageEdit.h>
Public Member Functions
ImageEdit (const QString &propertyName, const std::shared_ptr< Materials::Material > &material, QWidget *parent=nullptr)
~ImageEdit () override=default
void accept () override
void reject () override
Detailed Description
Definition at line 87 of file ImageEdit.h.
Constructor & Destructor Documentation
ImageEdit()
ImageEdit::ImageEdit (const QString & propertyName, const std::shared_ptr< Materials::Material > & material, QWidget * parent = nullptr)
Definition at line 108 of file ImageEdit.cpp.
References accept(), draftgeoutils.intersections::connect(), Base::Console(), Base::ConsoleSingleton::Log(), propertyName(), reject(), and Materials::MaterialValue::SVG.
~ImageEdit()
MatGui::ImageEdit::~ImageEdit () override default
Member Function Documentation
accept()
void ImageEdit::accept () override
Definition at line 236 of file ImageEdit.cpp.
References Materials::MaterialValue::SVG.
Referenced by ImageEdit(), and MaterialEditor.MaterialEditor::verify().
reject()
void ImageEdit::reject () override
Definition at line 254 of file ImageEdit.cpp.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and ImageEdit().
The documentation for this class was generated from the following files:
ImageEdit.h
ImageEdit.cpp