FreeCAD: PartGui::CircleFromThreePoints Class Reference
PartGui::CircleFromThreePoints Class Reference
Public Member Functions
CircleFromThreePoints ()
bool pickedPoint (const SoPickedPoint *point) override
QString command (App::Document *doc) const override
Public Member Functions inherited from PartGui::Picker
virtual ~Picker ()=default
void createPrimitive (QWidget *widget, const QString &, Gui::Document *)
QString toPlacement (const gp_Ax2 &) const
Additional Inherited Members
Public Attributes inherited from PartGui::Picker
int exitCode {-1}
QEventLoop loop
Detailed Description
Definition at line 164 of file DlgPrimitives.cpp.
Constructor & Destructor Documentation
CircleFromThreePoints()
PartGui::CircleFromThreePoints::CircleFromThreePoints () inline
Definition at line 167 of file DlgPrimitives.cpp.
Member Function Documentation
command()
QString PartGui::CircleFromThreePoints::command (App::Document * doc) const inline override virtual
Implements PartGui::Picker.
Definition at line 176 of file DlgPrimitives.cpp.
References toolbit-attributes::doc, PartGui::gce_ErrorStatusText(), Base::UnitsApi::getDecimals(), Handle(), Base::toDegrees(), PartGui::Picker::toPlacement(), and Materials::trim().
pickedPoint()
bool PartGui::CircleFromThreePoints::pickedPoint (const SoPickedPoint * point) inline override virtual
Implements PartGui::Picker.
Definition at line 170 of file DlgPrimitives.cpp.
The documentation for this class was generated from the following file:
DlgPrimitives.cpp