FreeCAD: App::ProjectFile Class Reference
App::ProjectFile Class Reference
#include <ProjectFile.h>
Classes
struct Metadata
struct Object
struct PropertyFile
Public Member Functions
ProjectFile ()
ProjectFile (std::string zipArchive)
~ProjectFile ()
ProjectFile (const ProjectFile &)=delete
ProjectFile (ProjectFile &&)=delete
ProjectFile & operator= (const ProjectFile &)=delete
ProjectFile & operator= (ProjectFile &&)=delete
void setProjectFile (const std::string &zipArchive)
bool loadDocument ()
Metadata getMetadata () const
std::list< Object > getObjects () const
std::list< std::string > getObjectsOfType (const Base::Type &) const
bool restoreObject (const std::string &name, App::PropertyContainer *, bool verbose=true)
Base::Type getTypeId (const std::string &name) const
std::list< PropertyFile > getPropertyFiles (const std::string &name) const
bool containsFile (const std::string &name) const
std::list< std::string > getInputFiles (const std::string &name) const
std::string extractInputFile (const std::string &name)
void readInputFile (const std::string &name, std::ostream &str)
void readInputFileDirect (const std::string &name, std::ostream &str)
std::string replaceInputFile (const std::string &name, std::istream &inp)
std::string replaceInputFiles (const std::map< std::string, std::istream * > &inp)
std::string replacePropertyFiles (const std::map< std::string, App::Property * > &props)
bool replaceProjectFile (const std::string &name, bool keepfile=false)
Detailed Description
ProjectFile proj(project.fcstd);
if (proj.loadDocument()) {
    std::list<std::string> names = proj.getObjects();
    std::list<std::string> files = proj.getInputFiles(names.front().name);
    std::string meshFile = proj.extractInputFile(files.front());
    std::ifstream str(meshFile.c_str(), std::ios::in | std::ios::binary);
    Mesh::MeshObject mesh;
    mesh.load(str);
}
Definition at line 71 of file ProjectFile.h.
Constructor & Destructor Documentation
ProjectFile() [1/4]
ProjectFile::ProjectFile ()
Default constructor
Definition at line 188 of file ProjectFile.cpp.
ProjectFile() [2/4]
ProjectFile::ProjectFile (std::string zipArchive) explicit
Creates an instance of ProjectFile pointing to a project file. You have to call loadDocument() afterwards.
Definition at line 192 of file ProjectFile.cpp.
~ProjectFile()
ProjectFile::~ProjectFile ()
Destructor
Definition at line 197 of file ProjectFile.cpp.
ProjectFile() [3/4]
App::ProjectFile::ProjectFile (const ProjectFile &) delete
Copy/move constructor & assignment
ProjectFile() [4/4]
App::ProjectFile::ProjectFile (ProjectFile &&) delete
Member Function Documentation
containsFile()
bool ProjectFile::containsFile (const std::string & name) const
If the project file contains the file name true is returned and false otherwise
Definition at line 466 of file ProjectFile.cpp.
References ifctree::project.
extractInputFile()
std::string ProjectFile::extractInputFile (const std::string & name)
Extracts an input file of name and saves it as file to the disk. It's up to the client code to delete the file if needed.
Definition at line 528 of file ProjectFile.cpp.
References DrawingExample::file, Base::FileInfo::filePath(), Base::FileInfo::getTempFileName(), ifctree::project, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by readInputFile().
getInputFiles()
std::list< std::string > ProjectFile::getInputFiles (const std::string & name) const
Retrieves a list of input file names referenced to the given object name. This method does the same as getPropertyFiles() unless that it only returns the file names.
Definition at line 473 of file ProjectFile.cpp.
References StrX::c_str(), SplineSurface::i, and XStr::unicodeForm().
getMetadata()
ProjectFile::Metadata ProjectFile::getMetadata () const
Return the meta data of the loaded document.
Definition at line 245 of file ProjectFile.cpp.
References TechDrawTools.TaskFillTemplateFields::reader.
getObjects()
std::list< ProjectFile::Object > ProjectFile::getObjects () const
Returns a list of all object names with their type ids which are part of the project file.
Definition at line 256 of file ProjectFile.cpp.
References StrX::c_str(), Base::Type::fromName(), SplineSurface::i, App::ProjectFile::Object::name, femtools.tokrules::names, App::ProjectFile::Object::type, and XStr::unicodeForm().
Referenced by bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
getObjectsOfType()
std::list< std::string > ProjectFile::getObjectsOfType (const Base::Type & typeId) const
Returns a list of object names of a given type id which are part of the project file.
Definition at line 288 of file ProjectFile.cpp.
References StrX::c_str(), Base::Type::fromName(), SplineSurface::i, femtools.tokrules::names, and XStr::unicodeForm().
getPropertyFiles()
std::list< ProjectFile::PropertyFile > ProjectFile::getPropertyFiles (const std::string & name) const
Retrieves a list of input file names and their associated property names and type ids to the given object name.
See also
getInputFiles().
Definition at line 394 of file ProjectFile.cpp.
References StrX::c_str(), SplineSurface::i, and XStr::unicodeForm().
getTypeId()
Base::Type ProjectFile::getTypeId (const std::string & name) const
Retrieves the type id of a given object name.
Definition at line 360 of file ProjectFile.cpp.
References Base::Type::badType(), StrX::c_str(), Base::Type::fromName(), SplineSurface::i, and XStr::unicodeForm().
loadDocument()
bool ProjectFile::loadDocument ()
Loads the embedded document file of the project file. This is needed to query any information about objects, their type ids or any referenced input files.
Definition at line 209 of file ProjectFile.cpp.
References getIfcElements::parser, ifctree::project, and Path.Post.scripts.refactored_centroid_post::str.
operator=() [1/2]
ProjectFile& App::ProjectFile::operator= (const ProjectFile &) delete
operator=() [2/2]
ProjectFile& App::ProjectFile::operator= (ProjectFile &&) delete
readInputFile()
void ProjectFile::readInputFile (const std::string & name, std::ostream & str)
Extracts, via a temporary file the content of an input file of name.
Definition at line 547 of file ProjectFile.cpp.
References Base::FileInfo::deleteFile(), Base::FileInfo::exists(), extractInputFile(), DrawingExample::file, and Path.Post.scripts.refactored_centroid_post::str.
readInputFileDirect()
void ProjectFile::readInputFileDirect (const std::string & name, std::ostream & str)
Directly extracts the content of an input file of name.
Definition at line 560 of file ProjectFile.cpp.
References ifctree::project, and Path.Post.scripts.refactored_centroid_post::str.
replaceInputFile()
std::string ProjectFile::replaceInputFile (const std::string & name, std::istream & inp)
Replaces the input file name with the content of the given stream. The method returns the file name of the newly created project file.
Definition at line 569 of file ProjectFile.cpp.
References Base::Uuid::createUuid(), DrawingExample::file, ifctree::project, and Path.Post.scripts.refactored_centroid_post::str.
replaceInputFiles()
std::string ProjectFile::replaceInputFiles (const std::map< std::string, std::istream * > & inp)
Replaces the input files with the streams of inp. The method returns the file name of the newly created project file. If you want to replace the original project file you must call the method replaceProjectFile() with the returned file name as argument.
Definition at line 609 of file ProjectFile.cpp.
References Base::Uuid::createUuid(), DrawingExample::file, ifctree::project, and Path.Post.scripts.refactored_centroid_post::str.
replaceProjectFile()
bool ProjectFile::replaceProjectFile (const std::string & name, bool keepfile = false)
Replaces the project file with the given name. If keepfile is true then the renamed original file won't be deleted. Returns true if the replacement succeeded and false otherwise. If you want to replace the original project file you must call the method replaceProjectFile() with the returned file name as argument.
Definition at line 693 of file ProjectFile.cpp.
References Base::Uuid::createUuid(), Base::FileInfo::deleteFile(), Base::FileInfo::renameFile(), and Base::FileInfo::setFile().
replacePropertyFiles()
std::string ProjectFile::replacePropertyFiles (const std::map< std::string, App::Property * > & props)
Replaces the property files with the content of the properties in props. The method returns the file name of the newly created project file. If you want to replace the original project file you must call the method replaceProjectFile() with the returned file name as argument.
Definition at line 651 of file ProjectFile.cpp.
References Base::Uuid::createUuid(), DrawingExample::file, ifctree::project, Base::ZipWriter::putNextEntry(), Base::ZipWriter::setComment(), Base::ZipWriter::setLevel(), Path.Post.scripts.refactored_centroid_post::str, and Base::ZipWriter::Stream().
restoreObject()
bool ProjectFile::restoreObject (const std::string & name, App::PropertyContainer * obj, bool verbose = true)
Restores the object identified by its name and loads all properties of prop that match with the saved properties.
Definition at line 319 of file ProjectFile.cpp.
References DrawingExample::file, SplineSurface::i, TechDrawTools.TaskFillTemplateFields::reader, and App::PropertyContainer::Restore().
setProjectFile()
void ProjectFile::setProjectFile (const std::string & zipArchive)
Assigns the file name of another project file. This clears any internal data, thus loadDocument() needs to be called afterwards.
Definition at line 202 of file ProjectFile.cpp.
The documentation for this class was generated from the following files:
ProjectFile.h
ProjectFile.cpp