FreeCAD: CmdSketcherConstrainCoincidentUnified Class Reference
CmdSketcherConstrainCoincidentUnified Class Reference
Public Member Functions
CmdSketcherConstrainCoincidentUnified (const char *initName="Sketcher_ConstrainCoincidentUnified")
~CmdSketcherConstrainCoincidentUnified () override
const char * className () const override
The C++ class name is needed as context for the translation framework.
Public Member Functions inherited from CmdSketcherConstraint
CmdSketcherConstraint (const char *name)
~CmdSketcherConstraint () override
Public Member Functions inherited from Gui::Command
const char * beginCmdHelp ()
returns the begin of a online help page
const char * endCmdHelp ()
returns the end of a online help page
virtual const char * getHelpUrl () const
Get the help URL.
bool hasActiveDocument () const
true when there is a document
bool hasObject (const char *Name)
true when there is a document and a Feature with Name
const char * getAppModuleName () const
returns the name to which the command belongs
void setAppModuleName (const char *)
const char * getName () const
Get the command name.
const char * getGroupName () const
Get the name of the grouping of the command.
void setGroupName (const char *)
QString translatedGroupName () const
virtual void setShortcut (const QString &)
Override shortcut of this command.
virtual QString getShortcut () const
Obtain the current shortcut of this command.
void testActive ()
Get somtile called to check the state of the command.
void setEnabled (bool)
Enables or disables the command.
TriggerSource triggerSource () const
Return the current command trigger source.
void invoke (int index, TriggerSource trigger=TriggerNone)
void addTo (QWidget *)
adds this command to arbitrary widgets
void addToGroup (ActionGroup *, bool checkable)
void addToGroup (ActionGroup *)
void initAction ()
Create the action if not exist.
void adjustCameraPosition ()
Gui::Document * getActiveGuiDocument () const
Get pointer to the active gui document.
App::Document * getDocument (const char *Name=nullptr) const
bool isViewOfType (Base::Type t) const
checks if the active view is of a special type or derived
App::DocumentObject * getObject (const char *Name) const
returns the named feature or the active one from the active document or NULL
std::string getUniqueObjectName (const char *BaseName, const App::DocumentObject *obj=nullptr) const
void languageChange () override
Translate command.
void updateAction (int mode) override
Updates the QAction with respect to the passed mode.
void setupCheckable (int iMsg)
Setup checkable actions based on current TriggerSource.
const std::string strToPython (const char *Str)
translate a string to a python string literal (needed e.g. in file names for windows...)
const std::string strToPython (const std::string &Str)
Public Member Functions inherited from Gui::CommandBase
Action * getAction () const
virtual const char * getMenuText () const
virtual const char * getToolTipText () const
virtual const char * getStatusTip () const
virtual const char * getWhatsThis () const
virtual const char * getPixmap () const
virtual const char * getAccel () const
void setWhatsThis (const char *)
void setMenuText (const char *)
void setToolTipText (const char *)
void setStatusTip (const char *)
void setPixmap (const char *)
void setAccel (const char *)
Protected Types
enum CoincicenceType { CoincicenceType::Coincident, CoincicenceType::PointOnObject, CoincicenceType::Both }
Protected Types inherited from Gui::Command
enum CmdType {
AlterDoc = 1, Alter3DView = 2, AlterSelection = 4, ForEdit = 8,
NoTransaction = 16
}
Protected Member Functions
void activated (int iMsg) override
Methods which gets called when activated, needs to be reimplemented!
void onActivated (CoincicenceType type)
void activatedCoincident (SketchObject *obj, std::vector< SelIdPair > points, std::vector< SelIdPair > curves)
void activatedPointOnObject (SketchObject *obj, std::vector< SelIdPair > points, std::vector< SelIdPair > curves)
void applyConstraint (std::vector< SelIdPair > &selSeq, int seqIndex) override
void applyConstraintCoincident (std::vector< SelIdPair > &selSeq, int seqIndex)
void applyConstraintPointOnObject (std::vector< SelIdPair > &selSeq, int seqIndex)
Protected Member Functions inherited from CmdSketcherConstraint
bool isActive () override
Override this method if your Cmd is not always active.
Protected Member Functions inherited from Gui::Command
Command (const char *name)
~Command () override
Action * createAction () override
Creates the used Action.
void applyCommandData (const char *context, Action *)
Applies the menu text, tool and status tip to the passed action object.
const char * keySequenceToAccel (int) const
void printConflictingAccelerators () const
Protected Member Functions inherited from Gui::CommandBase
CommandBase (const char *sMenu, const char *sToolTip=nullptr, const char *sWhat=nullptr, const char *sStatus=nullptr, const char *sPixmap=nullptr, const char *sAccel=nullptr)
virtual ~CommandBase ()
Static Protected Member Functions
static bool substituteConstraintCombinationsPointOnObject (SketchObject *Obj, int GeoId1, PointPos PosId1, int GeoId2)
static bool substituteConstraintCombinationsCoincident (SketchObject *Obj, int GeoId1, PointPos PosId1, int GeoId2, PointPos PosId2)
Additional Inherited Members
Public Types inherited from Gui::Command
enum TriggerSource { TriggerNone, TriggerAction, TriggerChildAction }
Command trigger source.
enum DoCmd_Type { Doc, App, Gui }
types of application level actions for DoCommand()
Static Public Member Functions inherited from Gui::Command
static void blockCommand (bool)
Blocks all command objects.
static void printPyCaller ()
Print to Python console the current Python calling source file and line number.
static void printCaller (const char *file, int line)
Print to Python console the current calling source file and line number.
static void _doCommand (const char *file, int line, DoCmd_Type eType, const char *sCmd,...)
Run a App level Action.
static void _runCommand (const char *file, int line, DoCmd_Type eType, const char *sCmd)
Run a App level Action.
static void _runCommand (const char *file, int line, DoCmd_Type eType, const QByteArray &sCmd)
Run a App level Action.
static void addModule (DoCmd_Type eType, const char *sModuleName)
import an external (or own) module only once
static std::string _assureWorkbench (const char *file, int line, const char *sName)
static Application * getGuiApplication ()
Get pointer to the Application Window.
static Gui::SelectionSingleton & getSelection ()
Get a reference to the selection.
static std::string getObjectCmd (const char *Name, const App::Document *doc=nullptr, const char *prefix=nullptr, const char *postfix=nullptr, bool gui=false)
returns a python command string to retrieve an object from a document
static std::string getObjectCmd (const App::DocumentObject *obj, const char *prefix=nullptr, const char *postfix=nullptr, bool gui=false)
returns a python command string to retrieve the given object
static void openCommand (const char *sName=nullptr)
Open a new Undo transaction on the active document.
static void commitCommand ()
Commit the Undo transaction on the active document.
static void abortCommand ()
Abort the Undo transaction on the active document.
static bool hasPendingCommand ()
Check if an Undo transaction is open on the active document.
static void updateActive ()
Updates the (active) document (propagate changes)
static void updateAll (std::list< Gui::Document * > cList)
Updates the (all or listed) documents (propagate changes)
static bool isActiveObjectValid ()
Checks if the active object of the active document is valid.
static void _copyVisual (const char *file, int line, const char *to, const char *attr, const char *from)
static void _copyVisual (const char *file, int line, const char *to, const char *attr_to, const char *from, const char *attr_from)
static void _copyVisual (const char *file, int line, const App::DocumentObject *to, const char *attr, const App::DocumentObject *from)
static void _copyVisual (const char *file, int line, const App::DocumentObject *to, const char *attr_to, const App::DocumentObject *from, const char *attr_from)
static std::string getPythonTuple (const std::string &name, const std::vector< std::string > &subnames)
Get Python tuple from object and sub-elements.
Protected Attributes inherited from CmdSketcherConstraint
std::vector< std::vector< SketcherGui::SelType > > allowedSelSequences
allowedSelSequences Each element is a vector representing sequence of selections allowable. DrawSketchHandlerGenConstraint will use these to filter elements and generate sequences to be passed to applyConstraint(). Whenever any sequence is completed, applyConstraint() is called, so it's best to keep them prefix-free. Be mindful that when SelVertex and SelRoot are given preference over SelVertexOrRoot, and similar for edges/axes. Thus if a vertex is selected when SelVertex and SelVertexOrRoot are both applicable, only sequences with SelVertex will be continue.
Protected Attributes inherited from Gui::Command
const char * sAppModule
const char * sGroup
const char * sName
const char * sHelpUrl
int eType
bool bCanLog
Indicate if the command shall log to MacroManager.
Protected Attributes inherited from Gui::CommandBase
const char * sMenuText
const char * sToolTipText
const char * sWhatsThis
const char * sStatusTip
const char * sPixmap
const char * sAccel
Action * _pcAction
std::string displayText
Detailed Description
Definition at line 3738 of file CommandConstraints.cpp.
Member Enumeration Documentation
CoincicenceType
enum CmdSketcherConstrainCoincidentUnified::CoincicenceType strong protected
Enumerator
Coincident
PointOnObject
Both
Definition at line 3750 of file CommandConstraints.cpp.
Constructor & Destructor Documentation
CmdSketcherConstrainCoincidentUnified()
CmdSketcherConstrainCoincidentUnified::CmdSketcherConstrainCoincidentUnified (const char * initName = "Sketcher_ConstrainCoincidentUnified")
Definition at line 3770 of file CommandConstraints.cpp.
References CmdSketcherConstraint::allowedSelSequences, Gui::Command::eType, Gui::Command::ForEdit, App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), Gui::CommandBase::sAccel, Gui::Command::sAppModule, SketcherGui::SelEdge, SketcherGui::SelEdgeOrAxis, SketcherGui::SelExternalEdge, SketcherGui::SelRoot, SketcherGui::SelVertex, SketcherGui::SelVertexOrRoot, Gui::Command::sGroup, Gui::CommandBase::sMenuText, Gui::CommandBase::sPixmap, Gui::CommandBase::sStatusTip, Gui::CommandBase::sToolTipText, and Gui::CommandBase::sWhatsThis.
~CmdSketcherConstrainCoincidentUnified()
CmdSketcherConstrainCoincidentUnified::~CmdSketcherConstrainCoincidentUnified () inline override
Definition at line 3742 of file CommandConstraints.cpp.
Member Function Documentation
activated()
void CmdSketcherConstrainCoincidentUnified::activated (int iMsg) override protected virtual
Methods which gets called when activated, needs to be reimplemented!
Reimplemented from CmdSketcherConstraint.
Reimplemented in CmdSketcherConstrainPointOnObject, and CmdSketcherConstrainCoincident.
Definition at line 3904 of file CommandConstraints.cpp.
References Both, and onActivated().
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::set_status_filter().
activatedCoincident()
void CmdSketcherConstrainCoincidentUnified::activatedCoincident (SketchObject * obj, std::vector< SelIdPair > points, std::vector< SelIdPair > curves) protected
Definition at line 4029 of file CommandConstraints.cpp.
References Gui::Command::abortCommand(), SketcherGui::areBothPointsOrSegmentsFixed(), Sketcher::SketchObject::arePointsCoincident(), Gui::SelectionSingleton::clearSelection(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Sketcher::SketchObject::getGeometry(), Gui::Command::getSelection(), SplineSurface::i, isGeoConcentricCompatible(), Sketcher::mid, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, showNoConstraintBetweenFixedGeometry(), substituteConstraintCombinationsCoincident(), Gui::TranslatedUserWarning(), and SketcherGui::tryAutoRecompute().
Referenced by onActivated().
activatedPointOnObject()
void CmdSketcherConstrainCoincidentUnified::activatedPointOnObject (SketchObject * obj, std::vector< SelIdPair > points, std::vector< SelIdPair > curves) protected
Definition at line 3973 of file CommandConstraints.cpp.
References Gui::Command::abortCommand(), SketcherGui::areBothPointsOrSegmentsFixed(), Gui::SelectionSingleton::clearSelection(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Sketcher::SketchObject::getGeometry(), Gui::Command::getSelection(), SketcherGui::isBsplinePole(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, showNoConstraintBetweenFixedGeometry(), substituteConstraintCombinationsPointOnObject(), and Gui::TranslatedUserWarning().
Referenced by onActivated().
applyConstraint()
void CmdSketcherConstrainCoincidentUnified::applyConstraint (std::vector< SelIdPair > & selSeq, int seqIndex) override protected virtual
Reimplemented from CmdSketcherConstraint.
Reimplemented in CmdSketcherConstrainPointOnObject, and CmdSketcherConstrainCoincident.
Definition at line 4106 of file CommandConstraints.cpp.
References applyConstraintCoincident(), and applyConstraintPointOnObject().
applyConstraintCoincident()
void CmdSketcherConstrainCoincidentUnified::applyConstraintCoincident (std::vector< SelIdPair > & selSeq, int seqIndex) protected
Definition at line 4206 of file CommandConstraints.cpp.
References Gui::Command::abortCommand(), SketcherGui::areBothPointsOrSegmentsFixed(), Sketcher::SketchObject::arePointsCoincident(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Gui::Command::getActiveGuiDocument(), Sketcher::SketchObject::getGeometry(), Gui::Document::getInEdit(), Gui::ViewProviderDocumentObject::getObject(), SketcherGui::ViewProviderSketch::getSketchObject(), isGeoConcentricCompatible(), Sketcher::mid, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, showNoConstraintBetweenFixedGeometry(), substituteConstraintCombinationsCoincident(), Gui::TranslatedUserWarning(), and SketcherGui::tryAutoRecompute().
Referenced by applyConstraint(), and CmdSketcherConstrainCoincident::applyConstraint().
applyConstraintPointOnObject()
void CmdSketcherConstrainCoincidentUnified::applyConstraintPointOnObject (std::vector< SelIdPair > & selSeq, int seqIndex) protected
Definition at line 4130 of file CommandConstraints.cpp.
References Gui::Command::abortCommand(), SketcherGui::areBothPointsOrSegmentsFixed(), Gui::cmdAppObjectArgs(), Gui::Command::commitCommand(), Gui::Command::getActiveGuiDocument(), Sketcher::SketchObject::getGeometry(), Gui::Document::getInEdit(), Gui::ViewProviderDocumentObject::getObject(), SketcherGui::ViewProviderSketch::getSketchObject(), SketcherGui::isBsplinePole(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, showNoConstraintBetweenFixedGeometry(), substituteConstraintCombinationsPointOnObject(), Gui::TranslatedUserWarning(), and SketcherGui::tryAutoRecompute().
Referenced by applyConstraint(), and CmdSketcherConstrainPointOnObject::applyConstraint().
className()
const char* CmdSketcherConstrainCoincidentUnified::className () const inline override virtual
The C++ class name is needed as context for the translation framework.
Reimplemented from CmdSketcherConstraint.
Reimplemented in CmdSketcherConstrainPointOnObject, and CmdSketcherConstrainCoincident.
Definition at line 3744 of file CommandConstraints.cpp.
onActivated()
void CmdSketcherConstrainCoincidentUnified::onActivated (CoincicenceType type) protected
Definition at line 3910 of file CommandConstraints.cpp.
References activatedCoincident(), activatedPointOnObject(), SketcherGui::ActivateHandler(), Gui::SelectionSingleton::clearSelection(), Coincident, Gui::Command::getActiveGuiDocument(), App::GetApplication(), ParameterGrp::GetBool(), Base::Persistence::getClassTypeId(), SketcherGui::getIdsFromName(), App::Application::GetParameterGroupByPath(), Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), SplineSurface::i, SplineSurface::id, SketcherGui::isEdge(), SketcherGui::isVertex(), PointOnObject, Path.Dressup.Utils::selection(), Gui::TranslatedUserWarning(), and Path.Post.scripts.grbl_post::type.
Referenced by activated(), CmdSketcherConstrainCoincident::activated(), and CmdSketcherConstrainPointOnObject::activated().
substituteConstraintCombinationsCoincident()
bool CmdSketcherConstrainCoincidentUnified::substituteConstraintCombinationsCoincident (SketchObject * Obj, int GeoId1, PointPos PosId1, int GeoId2, PointPos PosId2) static protected
Definition at line 3834 of file CommandConstraints.cpp.
References Sketcher::SketchObject::arePointsCoincident(), Gui::SelectionSingleton::clearSelection(), Gui::cmdAppObjectArgs(), Sketcher::SketchObject::Constraints, SketcherGui::doEndpointTangency(), Sketcher::end, Sketcher::GeoUndef, Gui::Command::getSelection(), Sketcher::PropertyConstraintList::getValues(), SketcherGui::isBsplineKnot(), Sketcher::none, SketcherGui::notifyConstraintSubstitutions(), Sketcher::start, and Sketcher::Tangent.
Referenced by activatedCoincident(), and applyConstraintCoincident().
substituteConstraintCombinationsPointOnObject()
bool CmdSketcherConstrainCoincidentUnified::substituteConstraintCombinationsPointOnObject (SketchObject * Obj, int GeoId1, PointPos PosId1, int GeoId2) static protected
Definition at line 3802 of file CommandConstraints.cpp.
References Gui::SelectionSingleton::clearSelection(), Gui::cmdAppObjectArgs(), Sketcher::SketchObject::Constraints, SketcherGui::doEndpointToEdgeTangency(), Sketcher::end, Sketcher::GeoUndef, Gui::Command::getSelection(), Sketcher::PropertyConstraintList::getValues(), Sketcher::none, SketcherGui::notifyConstraintSubstitutions(), Sketcher::start, and Sketcher::Tangent.
Referenced by activatedPointOnObject(), and applyConstraintPointOnObject().
The documentation for this class was generated from the following file:
CommandConstraints.cpp