FreeCAD: ColorPickerButton Class Reference
ColorPickerButton Class Reference
Signals
void clicked ()
Public Member Functions
ColorPickerButton (QWidget *parent)
Protected Member Functions
void mousePressEvent (QMouseEvent *e) override
void mouseMoveEvent (QMouseEvent *e) override
void mouseReleaseEvent (QMouseEvent *e) override
void keyPressEvent (QKeyEvent *e) override
void keyReleaseEvent (QKeyEvent *e) override
void paintEvent (QPaintEvent *e) override
void focusInEvent (QFocusEvent *e) override
void focusOutEvent (QFocusEvent *e) override
Detailed Description
Definition at line 147 of file qtcolorpicker.cpp.
Constructor & Destructor Documentation
ColorPickerButton()
ColorPickerButton::ColorPickerButton (QWidget * parent) explicit
Definition at line 1047 of file qtcolorpicker.cpp.
Member Function Documentation
clicked
void ColorPickerButton::clicked () signal
Referenced by ColorPickerPopup::ColorPickerPopup(), keyReleaseEvent(), and mouseReleaseEvent().
focusInEvent()
void ColorPickerButton::focusInEvent (QFocusEvent * e) override protected
Definition at line 1122 of file qtcolorpicker.cpp.
References SCL.SimpleDataTypes::e.
focusOutEvent()
void ColorPickerButton::focusOutEvent (QFocusEvent * e) override protected
Definition at line 1132 of file qtcolorpicker.cpp.
References SCL.SimpleDataTypes::e.
keyPressEvent()
void ColorPickerButton::keyPressEvent (QKeyEvent * e) override protected
Definition at line 1084 of file qtcolorpicker.cpp.
References SCL.SimpleDataTypes::e, and Init::parent.
keyReleaseEvent()
void ColorPickerButton::keyReleaseEvent (QKeyEvent * e) override protected
Definition at line 1102 of file qtcolorpicker.cpp.
References clicked(), SCL.SimpleDataTypes::e, and Init::parent.
mouseMoveEvent()
void ColorPickerButton::mouseMoveEvent (QMouseEvent * e) override protected
Definition at line 1065 of file qtcolorpicker.cpp.
mousePressEvent()
void ColorPickerButton::mousePressEvent (QMouseEvent * e) override protected
Definition at line 1056 of file qtcolorpicker.cpp.
mouseReleaseEvent()
void ColorPickerButton::mouseReleaseEvent (QMouseEvent * e) override protected
Definition at line 1074 of file qtcolorpicker.cpp.
References clicked().
paintEvent()
void ColorPickerButton::paintEvent (QPaintEvent * e) override protected
Definition at line 1142 of file qtcolorpicker.cpp.
References SCL.SimpleDataTypes::e, and buildPsets::p.
The documentation for this class was generated from the following file:
qtcolorpicker.cpp