FreeCAD: Gui::ViewProviderTextureExtension Class Reference
Gui::ViewProviderTextureExtension Class Reference
#include <ViewProviderTextureExtension.h>
Public Member Functions
ViewProviderTextureExtension ()
Constructor.
~ViewProviderTextureExtension () override
void setup (SoMaterial *)
void setCoinAppearance (SoMaterial *pcShapeMaterial, const App::Material &source)
SoSwitch * getAppearance () const
SoGroup * getTextureGroup3D () const
void activateMaterial ()
void activateTexture2D ()
void activateTexture3D ()
void activateMixed3D ()
Public Member Functions inherited from Gui::ViewProviderExtension
ViewProviderExtension ()
~ViewProviderExtension () override
Gui::ViewProviderDocumentObject * getExtendedViewProvider ()
const Gui::ViewProviderDocumentObject * getExtendedViewProvider () const
virtual std::vector< App::DocumentObject * > extensionClaimChildren3D () const
virtual bool extensionOnDelete (const std::vector< std::string > &)
virtual void extensionBeforeDelete ()
virtual std::vector< App::DocumentObject * > extensionClaimChildren () const
virtual bool extensionCanDragObjects () const
virtual bool extensionCanDragObject (App::DocumentObject *) const
virtual void extensionDragObject (App::DocumentObject *)
virtual bool extensionCanDropObjects () const
virtual bool extensionCanDropObject (App::DocumentObject *) const
virtual bool extensionCanDragAndDropObject (App::DocumentObject *) const
virtual void extensionDropObject (App::DocumentObject *)
virtual bool extensionCanDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const
virtual std::string extensionDropObjectEx (App::DocumentObject *obj, App::DocumentObject *, const char *, const std::vector< std::string > &)
virtual int extensionReplaceObject (App::DocumentObject *, App::DocumentObject *)
virtual void extensionHide ()
Hides the view provider.
virtual void extensionShow ()
Shows the view provider.
virtual void extensionModeSwitchChange ()
virtual SoSeparator * extensionGetFrontRoot () const
virtual SoGroup * extensionGetChildRoot () const
virtual SoSeparator * extensionGetBackRoot () const
virtual void extensionAttach (App::DocumentObject *)
virtual void extensionReattach (App::DocumentObject *)
virtual void extensionSetDisplayMode (const char *)
virtual std::vector< std::string > extensionGetDisplayModes () const
virtual void extensionSetupContextMenu (QMenu *, QObject *, const char *)
virtual void extensionUpdateData (const App::Property *)
PyObject * getExtensionPyObject () override
void setIgnoreOverlayIcon (bool on)
bool ignoreOverlayIcon () const
virtual QIcon extensionMergeGreyableOverlayIcons (const QIcon &orig) const
virtual QIcon extensionMergeColorfullOverlayIcons (const QIcon &orig) const
virtual void extensionStartRestoring ()
virtual void extensionFinishRestoring ()
virtual bool extensionGetElementPicked (const SoPickedPoint *, std::string &) const
virtual bool extensionGetDetailPath (const char *, SoFullPath *, SoDetail *&) const
Public Member Functions inherited from App::Extension
virtual Base::Type getExtensionTypeId (void) const
Extension ()=default
virtual ~Extension ()
virtual void initExtension (App::ExtensionContainer *obj)
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Additional Inherited Members
Static Public Member Functions inherited from App::Extension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Protected Member Functions inherited from App::Extension
virtual const App::PropertyData & extensionGetPropertyData (void) const
virtual void extensionOnChanged (const Property *p)
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
returns true if the property name change was handled by the extension.
virtual bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
returns true if the property type change was handled by the extension.
void initExtensionType (Base::Type type)
Static Protected Member Functions inherited from App::Extension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Detailed Description
Definition at line 46 of file ViewProviderTextureExtension.h.
Constructor & Destructor Documentation
ViewProviderTextureExtension()
ViewProviderTextureExtension::ViewProviderTextureExtension ()
Constructor.
Definition at line 45 of file ViewProviderTextureExtension.cpp.
References App::Extension::getExtensionClassTypeId().
~ViewProviderTextureExtension()
ViewProviderTextureExtension::~ViewProviderTextureExtension () override
Definition at line 76 of file ViewProviderTextureExtension.cpp.
Member Function Documentation
activateMaterial()
void ViewProviderTextureExtension::activateMaterial ()
Select which appearance type is active Material only
Definition at line 131 of file ViewProviderTextureExtension.cpp.
Referenced by setCoinAppearance(), and PartGui::ViewProviderPartExt::setHighlightedFaces().
activateMixed3D()
void ViewProviderTextureExtension::activateMixed3D ()
Mix of material and 3D textures
Definition at line 149 of file ViewProviderTextureExtension.cpp.
activateTexture2D()
void ViewProviderTextureExtension::activateTexture2D ()
2D Texture
Definition at line 137 of file ViewProviderTextureExtension.cpp.
Referenced by setCoinAppearance().
activateTexture3D()
void ViewProviderTextureExtension::activateTexture3D ()
3D texture only
Definition at line 143 of file ViewProviderTextureExtension.cpp.
getAppearance()
SoSwitch * ViewProviderTextureExtension::getAppearance () const
Definition at line 84 of file ViewProviderTextureExtension.cpp.
Referenced by PartGui::ViewProviderPartExt::attach().
getTextureGroup3D()
SoGroup * ViewProviderTextureExtension::getTextureGroup3D () const
Definition at line 89 of file ViewProviderTextureExtension.cpp.
Referenced by Gui::ViewProviderFaceTexture::setup().
setCoinAppearance()
void ViewProviderTextureExtension::setCoinAppearance (SoMaterial * pcShapeMaterial, const App::Material & source)
Definition at line 94 of file ViewProviderTextureExtension.cpp.
References activateMaterial(), activateTexture2D(), App::Material::ambientColor, App::Color::b, Gui::BitmapFactory(), Base::Console(), Gui::BitmapFactoryInst::convert(), App::Material::diffuseColor, App::Material::emissiveColor, App::Color::g, App::Material::image, Base::ConsoleSingleton::Log(), App::Color::r, App::Material::shininess, App::Material::specularColor, and App::Material::transparency.
setup()
void ViewProviderTextureExtension::setup (SoMaterial * pcShapeMaterial)
Definition at line 65 of file ViewProviderTextureExtension.cpp.
Referenced by Path.Dressup.Tags.ObjectTagDressup::doExecute(), Path.Dressup.Gui.Dogbone.ObjectDressup::execute(), Path.Dressup.Tags.ObjectTagDressup::generateTags(), Path.Dressup.Tags.ObjectTagDressup::pointAtBottom(), Path.Dressup.Tags.ObjectTagDressup::pointIsOnPath(), Gui::ViewProviderFaceTexture::setup(), Path.Dressup.Tags.ObjectTagDressup::setXyEnabled(), and Path.Dressup.Tags.ObjectTagDressup::supportsTagGeneration().
The documentation for this class was generated from the following files:
ViewProviderTextureExtension.h
ViewProviderTextureExtension.cpp