FreeCAD: Gui::PropertyEditor::PropertyItem Class Reference
Gui::PropertyEditor::PropertyItem Class Reference
#include <PropertyItem.h>
Public Member Functions
~PropertyItem () override
void setPropertyData (const std::vector< App::Property * > &)
void updateData ()
const std::vector< App::Property * > & getPropertyData () const
bool hasProperty (const App::Property *) const
virtual void assignProperty (const App::Property *)
bool removeProperty (const App::Property *)
App::Property * getFirstProperty ()
const App::Property * getFirstProperty () const
virtual QWidget * createEditor (QWidget *parent, const std::function< void()> &method) const
virtual void setEditorData (QWidget *editor, const QVariant &data) const
virtual QVariant editorData (QWidget *editor) const
virtual bool isSeparator () const
QWidget * createExpressionEditor (QWidget *parent, const std::function< void()> &method) const
void setExpressionEditorData (QWidget *editor, const QVariant &data) const
QVariant expressionEditorData (QWidget *editor) const
PropertyEditorWidget * createPropertyEditorWidget (QWidget *parent) const
void bind (const App::Property &prop) override
void bind (const App::ObjectIdentifier &_path) override
virtual void propertyBound ()
QString expressionAsString () const
void setParent (PropertyItem *parent)
PropertyItem * parent () const
void appendChild (PropertyItem *child)
void insertChild (int, PropertyItem *child)
void moveChild (int from, int to)
void removeChildren (int from, int to)
PropertyItem::removeChildren Deletes the children in the range of [from, to].
PropertyItem * takeChild (int)
PropertyItem::takeChild Removes the child at index row but doesn't delete it.
void setReadOnly (bool)
bool isReadOnly () const
bool testStatus (App::Property::Status pos) const
void setDecimals (int)
int decimals () const
void setLinked (bool)
bool isLinked () const
bool isExpanded () const
void setExpanded (bool e)
PropertyItem * child (int row)
int childCount () const
int columnCount () const
QString propertyName () const
void setPropertyName (const QString &name, const QString &realName=QString())
void setPropertyValue (const QString &)
virtual QVariant data (int column, int role) const
bool setData (const QVariant &value)
Qt::ItemFlags flags (int column) const
virtual int row () const
void reset ()
bool hasAnyExpression () const
Public Member Functions inherited from Gui::ExpressionBinding
ExpressionBinding ()
virtual ~ExpressionBinding ()
bool isBound () const
void unbind ()
virtual bool apply (const std::string &propName)
virtual bool apply ()
bool hasExpression () const
bool autoApply () const
void setAutoApply (bool value)
Static Public Member Functions
static void * create (void)
static void init (void)
Protected Member Functions
PropertyItem ()
void setPropertyValue (const std::string &value)
virtual QVariant displayName () const
virtual QVariant decoration (const QVariant &) const
virtual QVariant toolTip (const App::Property *) const
virtual QVariant toString (const QVariant &) const
virtual QVariant value (const App::Property *) const
virtual void setValue (const QVariant &)
virtual void initialize ()
void onChange () override
Protected Member Functions inherited from Gui::ExpressionBinding
const App::ObjectIdentifier & getPath () const
std::shared_ptr< App::Expression > getExpression () const
std::string getExpressionString (bool no_throw=true) const
std::string getEscapedExpressionString () const
bool assignToProperty (const std::string &propName, double)
virtual void setExpression (std::shared_ptr< App::Expression > expr)
void expressionChange (const App::ObjectIdentifier &id)
void objectDeleted (const App::DocumentObject &)
Protected Attributes
QString propName
QString displayText
std::vector< App::Property * > propertyItems
PropertyItem * parentItem
QList< PropertyItem * > childItems
bool readonly
int precision
bool linked
bool expanded
Protected Attributes inherited from Gui::ExpressionBinding
boost::signals2::scoped_connection expressionchanged
boost::signals2::scoped_connection objectdeleted
bool m_autoApply {false}
Friends
class PropertyItemAttorney
Detailed Description
Definition at line 127 of file PropertyItem.h.
Constructor & Destructor Documentation
~PropertyItem()
PropertyItem::~PropertyItem () override
Definition at line 121 of file PropertyItem.cpp.
PropertyItem()
PropertyItem::PropertyItem () protected
Definition at line 111 of file PropertyItem.cpp.
Member Function Documentation
appendChild()
void PropertyItem::appendChild (PropertyItem * child)
Definition at line 258 of file PropertyItem.cpp.
Referenced by SketcherGui::PropertyConstraintListItem::initialize().
assignProperty()
void PropertyItem::assignProperty (const App::Property * prop) virtual
Reimplemented in Gui::PropertyEditor::PropertyPlacementItem, and Gui::PropertyEditor::PropertyRotationItem.
Definition at line 217 of file PropertyItem.cpp.
Referenced by Gui::PropertyEditor::PropertyModel::updateProperty().
bind() [1/2]
void PropertyItem::bind (const App::ObjectIdentifier & _path) override virtual
Reimplemented from Gui::ExpressionBinding.
Definition at line 803 of file PropertyItem.cpp.
References Gui::ExpressionBinding::bind().
bind() [2/2]
void PropertyItem::bind (const App::Property & prop) override virtual
override the bind functions to ensure we issue the propertyBound() call, which is then overloaded by childs which like to be informed of a binding
Reimplemented from Gui::ExpressionBinding.
Definition at line 809 of file PropertyItem.cpp.
References Gui::ExpressionBinding::bind().
Referenced by SketcherGui::PropertyConstraintListItem::initialize(), Gui::PropertyEditor::PropertyVectorDistanceItem::propertyBound(), Gui::PropertyEditor::PropertyRotationItem::propertyBound(), Gui::PropertyEditor::PropertyPlacementItem::propertyBound(), and Gui::PropertyEditor::PropertyEnumItem::propertyBound().
child()
PropertyItem * PropertyItem::child (int row)
Definition at line 297 of file PropertyItem.cpp.
References value().
Referenced by Gui::PropertyEditor::PropertyModel::appendProperty(), Gui::PropertyEditor::PropertyModel::index(), Gui::PropertyEditor::PropertyModel::propertyIndexFromPath(), SketcherGui::PropertyConstraintListItem::value(), Gui::PropertyEditor::PropertyRotationItem::value(), and Gui::PropertyEditor::PropertyPlacementItem::value().
childCount()
int PropertyItem::childCount () const
Definition at line 302 of file PropertyItem.cpp.
Referenced by Gui::PropertyEditor::PropertyModel::propertyIndexFromPath(), and Gui::PropertyEditor::PropertyModel::rowCount().
columnCount()
int PropertyItem::columnCount () const
Definition at line 307 of file PropertyItem.cpp.
Referenced by Gui::PropertyEditor::PropertyModel::columnCount().
create()
static void* Gui::PropertyEditor::PropertyItem::create (void) static
Referenced by draftguitools.gui_labels.Label::action(), SketcherGui::PropertyConstraintListItem::initialize(), and Gui::PropertyEditor::PropertyModel::PropertyModel().
createEditor()
QWidget * PropertyItem::createEditor (QWidget * parent, const std::function< void()> & method) const virtual
Creates the appropriate editor for this item and sets the editor to the value of overrideValue().
Reimplemented in Gui::PropertyEditor::PropertyLinkItem, Gui::PropertyEditor::PropertyTransientFileItem, Gui::PropertyEditor::PropertyPathItem, Gui::PropertyEditor::PropertyFileItem, Gui::PropertyEditor::PropertyMaterialListItem, Gui::PropertyEditor::PropertyMaterialItem, Gui::PropertyEditor::PropertyColorItem, Gui::PropertyEditor::PropertyIntegerListItem, Gui::PropertyEditor::PropertyFloatListItem, Gui::PropertyEditor::PropertyStringListItem, Gui::PropertyEditor::PropertyEnumItem, Gui::PropertyEditor::PropertyPlacementItem, Gui::PropertyEditor::PropertyRotationItem, Gui::PropertyEditor::PropertyMatrixItem, Gui::PropertyEditor::PropertyVectorDistanceItem, Gui::PropertyEditor::PropertyVectorListItem, Gui::PropertyEditor::PropertyVectorItem, Gui::PropertyEditor::PropertyBoolItem, Gui::PropertyEditor::PropertyFloatConstraintItem, Gui::PropertyEditor::PropertyUnitItem, Gui::PropertyEditor::PropertyFloatItem, Gui::PropertyEditor::PropertyIntegerConstraintItem, Gui::PropertyEditor::PropertyIntegerItem, Gui::PropertyEditor::PropertySeparatorItem, Gui::PropertyEditor::PropertyFontItem, Gui::PropertyEditor::PropertyStringItem, and PartGui::PropertyEnumAttacherItem.
Definition at line 502 of file PropertyItem.cpp.
createExpressionEditor()
QWidget * PropertyItem::createExpressionEditor (QWidget * parent, const std::function< void()> & method) const
Definition at line 516 of file PropertyItem.cpp.
References draftgeoutils.intersections::connect(), draftfunctions.svgshapes::getPath(), and Init::parent.
createPropertyEditorWidget()
PropertyEditorWidget * PropertyItem::createPropertyEditorWidget (QWidget * parent) const
Definition at line 548 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyEditorWidget::buttonClick(), draftgeoutils.intersections::connect(), Path.Post.Utils::editor(), importers.exportIFC::getPropertyData(), Init::parent, and App::Property::UserEdit.
data()
QVariant PropertyItem::data (int column, int role) const virtual
Reimplemented in Gui::PropertyEditor::PropertyLinkItem.
Definition at line 754 of file PropertyItem.cpp.
References App::ExpressionParser::column.
Referenced by Gui::PropertyEditor::PropertyModel::data(), Gui::PropertyEditor::PropertyLinkItem::data(), Gui::PropertyEditor::PropertyMaterialItem::editorData(), Gui::PropertyEditor::PropertyMaterialListItem::editorData(), Gui::PropertyEditor::PropertyMatrixItem::getA11(), Gui::PropertyEditor::PropertyMatrixItem::getA12(), Gui::PropertyEditor::PropertyMatrixItem::getA13(), Gui::PropertyEditor::PropertyMatrixItem::getA14(), Gui::PropertyEditor::PropertyMatrixItem::getA21(), Gui::PropertyEditor::PropertyMatrixItem::getA22(), Gui::PropertyEditor::PropertyMatrixItem::getA23(), Gui::PropertyEditor::PropertyMatrixItem::getA24(), Gui::PropertyEditor::PropertyMatrixItem::getA31(), Gui::PropertyEditor::PropertyMatrixItem::getA32(), Gui::PropertyEditor::PropertyMatrixItem::getA33(), Gui::PropertyEditor::PropertyMatrixItem::getA34(), Gui::PropertyEditor::PropertyMatrixItem::getA41(), Gui::PropertyEditor::PropertyMatrixItem::getA42(), Gui::PropertyEditor::PropertyMatrixItem::getA43(), Gui::PropertyEditor::PropertyMatrixItem::getA44(), Gui::PropertyEditor::PropertyMaterialItem::getAmbientColor(), Gui::PropertyEditor::PropertyMaterialListItem::getAmbientColor(), Gui::PropertyEditor::PropertyRotationItem::getAngle(), Gui::PropertyEditor::PropertyPlacementItem::getAngle(), Gui::PropertyEditor::PropertyMaterialItem::getDiffuseColor(), Gui::PropertyEditor::PropertyMaterialListItem::getDiffuseColor(), Gui::PropertyEditor::PropertyMaterialItem::getEmissiveColor(), Gui::PropertyEditor::PropertyMaterialListItem::getEmissiveColor(), Gui::PropertyEditor::PropertyPlacementItem::getPosition(), Gui::PropertyEditor::PropertyMaterialItem::getShininess(), Gui::PropertyEditor::PropertyMaterialListItem::getShininess(), Gui::PropertyEditor::PropertyMaterialItem::getSpecularColor(), Gui::PropertyEditor::PropertyMaterialListItem::getSpecularColor(), Gui::PropertyEditor::PropertyMaterialItem::getTransparency(), Gui::PropertyEditor::PropertyMaterialListItem::getTransparency(), Gui::PropertyEditor::PropertyMaterialItem::setAmbientColor(), Gui::PropertyEditor::PropertyMaterialListItem::setAmbientColor(), Gui::PropertyEditor::PropertyRotationItem::setAngle(), Gui::PropertyEditor::PropertyPlacementItem::setAngle(), Gui::PropertyEditor::PropertyRotationItem::setAxis(), Gui::PropertyEditor::PropertyPlacementItem::setAxis(), Gui::PropertyEditor::PropertyMaterialItem::setDiffuseColor(), Gui::PropertyEditor::PropertyMaterialListItem::setDiffuseColor(), PartGui::PropertyEnumAttacherItem::setEditorData(), Gui::PropertyEditor::PropertyVectorListItem::setEditorData(), Gui::PropertyEditor::PropertyVectorDistanceItem::setEditorData(), Gui::PropertyEditor::PropertyMatrixItem::setEditorData(), Gui::PropertyEditor::PropertyRotationItem::setEditorData(), Gui::PropertyEditor::PropertyPlacementItem::setEditorData(), Gui::PropertyEditor::PropertyEnumItem::setEditorData(), Gui::PropertyEditor::PropertyStringListItem::setEditorData(), Gui::PropertyEditor::PropertyFloatListItem::setEditorData(), Gui::PropertyEditor::PropertyIntegerListItem::setEditorData(), Gui::PropertyEditor::PropertyColorItem::setEditorData(), Gui::PropertyEditor::PropertyMaterialItem::setEditorData(), Gui::PropertyEditor::PropertyMaterialListItem::setEditorData(), Gui::PropertyEditor::PropertyFileItem::setEditorData(), Gui::PropertyEditor::PropertyPathItem::setEditorData(), Gui::PropertyEditor::PropertyTransientFileItem::setEditorData(), Gui::PropertyEditor::PropertyMaterialItem::setEmissiveColor(), Gui::PropertyEditor::PropertyMaterialListItem::setEmissiveColor(), Gui::PropertyEditor::PropertyPlacementItem::setPosition(), Gui::PropertyEditor::PropertyMaterialItem::setShininess(), Gui::PropertyEditor::PropertyMaterialListItem::setShininess(), Gui::PropertyEditor::PropertyMaterialItem::setSpecularColor(), Gui::PropertyEditor::PropertyMaterialListItem::setSpecularColor(), Gui::PropertyEditor::PropertyMaterialItem::setTransparency(), Gui::PropertyEditor::PropertyMaterialListItem::setTransparency(), Gui::PropertyEditor::PropertyVectorListItem::setValue(), Gui::PropertyEditor::PropertyMatrixItem::setValue(), Gui::PropertyEditor::PropertyFloatListItem::setValue(), Gui::PropertyEditor::PropertyIntegerListItem::setValue(), Gui::PropertyEditor::PropertyColorItem::setValue(), Gui::PropertyEditor::PropertyMaterialItem::setValue(), Gui::PropertyEditor::PropertyMaterialListItem::setValue(), Gui::PropertyEditor::PropertyRotationItem::toolTip(), Gui::PropertyEditor::PropertyPlacementItem::toolTip(), Gui::PropertyEditor::PropertyMaterialItem::toolTip(), Gui::PropertyEditor::PropertyMaterialListItem::toolTip(), Gui::PropertyEditor::PropertyVectorListItem::toString(), Gui::PropertyEditor::PropertyRotationItem::toString(), and Gui::PropertyEditor::PropertyPlacementItem::toString().
decimals()
int PropertyItem::decimals () const
Definition at line 364 of file PropertyItem.cpp.
References draftgeoutils.general::precision().
Referenced by Gui::PropertyEditor::PropertyRotationItem::assignProperty(), Gui::PropertyEditor::PropertyPlacementItem::assignProperty(), Gui::PropertyEditor::PropertyVectorListItem::createEditor(), Gui::PropertyEditor::PropertyVectorDistanceItem::createEditor(), Gui::PropertyEditor::PropertyMaterialItem::setValue(), Gui::PropertyEditor::PropertyMaterialListItem::setValue(), Gui::PropertyEditor::PropertyRotationItem::toolTip(), Gui::PropertyEditor::PropertyPlacementItem::toolTip(), and Gui::PropertyEditor::PropertyFloatListItem::value().
decoration()
QVariant PropertyItem::decoration (const QVariant & value) const protected virtual
Reimplemented in Gui::PropertyEditor::PropertyMaterialListItem, Gui::PropertyEditor::PropertyMaterialItem, and Gui::PropertyEditor::PropertyColorItem.
Definition at line 380 of file PropertyItem.cpp.
displayName()
QVariant PropertyItem::displayName () const protected virtual
Definition at line 369 of file PropertyItem.cpp.
editorData()
QVariant PropertyItem::editorData (QWidget * editor) const virtual
Reimplemented in Gui::PropertyEditor::PropertyLinkItem, Gui::PropertyEditor::PropertyTransientFileItem, Gui::PropertyEditor::PropertyPathItem, Gui::PropertyEditor::PropertyFileItem, Gui::PropertyEditor::PropertyMaterialListItem, Gui::PropertyEditor::PropertyMaterialItem, Gui::PropertyEditor::PropertyColorItem, Gui::PropertyEditor::PropertyIntegerListItem, Gui::PropertyEditor::PropertyFloatListItem, Gui::PropertyEditor::PropertyStringListItem, Gui::PropertyEditor::PropertyEnumItem, Gui::PropertyEditor::PropertyPlacementItem, Gui::PropertyEditor::PropertyRotationItem, Gui::PropertyEditor::PropertyMatrixItem, Gui::PropertyEditor::PropertyVectorDistanceItem, Gui::PropertyEditor::PropertyVectorListItem, Gui::PropertyEditor::PropertyVectorItem, Gui::PropertyEditor::PropertyBoolItem, Gui::PropertyEditor::PropertyFloatConstraintItem, Gui::PropertyEditor::PropertyUnitItem, Gui::PropertyEditor::PropertyFloatItem, Gui::PropertyEditor::PropertyIntegerConstraintItem, Gui::PropertyEditor::PropertyIntegerItem, Gui::PropertyEditor::PropertyFontItem, Gui::PropertyEditor::PropertyStringItem, and PartGui::PropertyEnumAttacherItem.
Definition at line 511 of file PropertyItem.cpp.
Referenced by Gui::Dialog::DlgAddPropertyVarSet::valueChanged().
expressionAsString()
QString PropertyItem::expressionAsString () const
Definition at line 815 of file PropertyItem.cpp.
References SCL.SimpleDataTypes::e, and result.
Referenced by Gui::PropertyEditor::PropertyRotationItem::value(), and Gui::PropertyEditor::PropertyPlacementItem::value().
expressionEditorData()
QVariant PropertyItem::expressionEditorData (QWidget * editor) const
Definition at line 539 of file PropertyItem.cpp.
References Path.Post.Utils::editor().
Referenced by Gui::PropertyEditor::PropertyItemDelegate::setModelData().
flags()
Qt::ItemFlags PropertyItem::flags (int column) const
Definition at line 784 of file PropertyItem.cpp.
References App::ExpressionParser::column.
Referenced by Gui::PropertyEditor::PropertyModel::flags().
getFirstProperty() [1/2]
const App::Property * PropertyItem::getFirstProperty ()
Definition at line 232 of file PropertyItem.cpp.
Referenced by Gui::PropertyEditor::PropertyModel::appendProperty(), Gui::PropertyEditor::PropertyPlacementItem::createEditor(), Gui::PropertyEditor::PropertyEnumItem::getEnum(), PartGui::PropertyEnumAttacherItem::openTask(), Gui::PropertyEditor::PropertyFileItem::setEditorData(), and Gui::PropertyEditor::PropertyTransientFileItem::setEditorData().
getFirstProperty() [2/2]
const App::Property* Gui::PropertyEditor::PropertyItem::getFirstProperty () const
getPropertyData()
const std::vector< App::Property * > & PropertyItem::getPropertyData () const
Definition at line 206 of file PropertyItem.cpp.
Referenced by MeshGui::PropertyMeshKernelItem::value(), and FemGui::PropertyFemMeshItem::value().
hasAnyExpression()
bool PropertyItem::hasAnyExpression () const
Definition at line 151 of file PropertyItem.cpp.
References Gui::ExpressionBinding::hasExpression().
hasProperty()
bool PropertyItem::hasProperty (const App::Property * prop) const
Definition at line 211 of file PropertyItem.cpp.
References DraftVecUtils::find().
init()
void Gui::PropertyEditor::PropertyItem::init (void) static
Definition at line 109 of file PropertyItem.cpp.
Referenced by DocumentObject.DocumentObject::onChanged(), and PyMOD_INIT_FUNC().
initialize()
void PropertyItem::initialize () protected virtual
Reimplemented in FemGui::PropertyFemMeshItem, MeshGui::PropertyMeshKernelItem, and SketcherGui::PropertyConstraintListItem.
Definition at line 126 of file PropertyItem.cpp.
insertChild()
void PropertyItem::insertChild (int index, PropertyItem * child)
Definition at line 263 of file PropertyItem.cpp.
isExpanded()
bool PropertyItem::isExpanded () const
Definition at line 343 of file PropertyItem.cpp.
isLinked()
bool PropertyItem::isLinked () const
Definition at line 333 of file PropertyItem.cpp.
isReadOnly()
bool PropertyItem::isReadOnly () const
Definition at line 320 of file PropertyItem.cpp.
Referenced by PartGui::PropertyEnumAttacherItem::createEditor(), Gui::PropertyEditor::PropertyVectorListItem::createEditor(), Gui::PropertyEditor::PropertyPlacementItem::createEditor(), Gui::PropertyEditor::PropertyEnumItem::createEditor(), Gui::PropertyEditor::PropertyStringListItem::createEditor(), Gui::PropertyEditor::PropertyFloatListItem::createEditor(), Gui::PropertyEditor::PropertyIntegerListItem::createEditor(), Gui::PropertyEditor::PropertyColorItem::createEditor(), Gui::PropertyEditor::PropertyMaterialItem::createEditor(), Gui::PropertyEditor::PropertyMaterialListItem::createEditor(), Gui::PropertyEditor::PropertyFileItem::createEditor(), Gui::PropertyEditor::PropertyPathItem::createEditor(), Gui::PropertyEditor::PropertyTransientFileItem::createEditor(), and Gui::PropertyEditor::PropertyLinkItem::createEditor().
isSeparator()
virtual bool Gui::PropertyEditor::PropertyItem::isSeparator () const inline virtual
Reimplemented in Gui::PropertyEditor::PropertySeparatorItem.
Definition at line 150 of file PropertyItem.h.
moveChild()
void PropertyItem::moveChild (int from, int to)
Definition at line 281 of file PropertyItem.cpp.
onChange()
void PropertyItem::onChange () override protected virtual
Reimplemented from Gui::ExpressionBinding.
Definition at line 135 of file PropertyItem.cpp.
parent()
PropertyItem * PropertyItem::parent () const
Definition at line 253 of file PropertyItem.cpp.
Referenced by PartGui::PropertyEnumAttacherItem::createEditor(), Gui::PropertyEditor::PropertyVectorListItem::createEditor(), Gui::PropertyEditor::PropertyVectorDistanceItem::createEditor(), Gui::PropertyEditor::PropertyMatrixItem::createEditor(), Gui::PropertyEditor::PropertyRotationItem::createEditor(), Gui::PropertyEditor::PropertyEnumItem::createEditor(), Gui::PropertyEditor::PropertyStringListItem::createEditor(), Gui::PropertyEditor::PropertyFloatListItem::createEditor(), Gui::PropertyEditor::PropertyIntegerListItem::createEditor(), Gui::PropertyEditor::PropertyColorItem::createEditor(), Gui::PropertyEditor::PropertyMaterialItem::createEditor(), Gui::PropertyEditor::PropertyMaterialListItem::createEditor(), Gui::PropertyEditor::PropertyFileItem::createEditor(), Gui::PropertyEditor::PropertyPathItem::createEditor(), Gui::PropertyEditor::PropertyTransientFileItem::createEditor(), Gui::PropertyEditor::PropertyLinkItem::createEditor(), PartGui::PropertyEnumAttacherItem::openTask(), Gui::PropertyEditor::PropertyModel::parent(), Gui::PropertyEditor::PropertyModel::removeProperty(), and Gui::PropertyEditor::PropertyModel::updateProperty().
propertyBound()
virtual void Gui::PropertyEditor::PropertyItem::propertyBound () inline virtual
Reimplemented in Gui::PropertyEditor::PropertyMaterialListItem, Gui::PropertyEditor::PropertyMaterialItem, Gui::PropertyEditor::PropertyEnumItem, Gui::PropertyEditor::PropertyPlacementItem, Gui::PropertyEditor::PropertyRotationItem, Gui::PropertyEditor::PropertyVectorDistanceItem, and Gui::PropertyEditor::PropertyVectorItem.
Definition at line 165 of file PropertyItem.h.
propertyName()
QString PropertyItem::propertyName () const
Definition at line 561 of file PropertyItem.cpp.
References Arch::QT_TRANSLATE_NOOP.
Referenced by Path.Base.Gui.SetupSheet.OpTaskPanel::accept(), Gui::PropertyEditor::PropertyModel::appendProperty(), Gui::PropertyEditor::PropertyPlacementItem::createEditor(), and Path.Base.Gui.SetupSheet.OpTaskPanel::setupUi().
removeChildren()
void PropertyItem::removeChildren (int from, int to)
PropertyItem::removeChildren Deletes the children in the range of [from, to].
Definition at line 272 of file PropertyItem.cpp.
References src.Mod.AddonManager.NetworkManager::count, and SplineSurface::i.
Referenced by Gui::PropertyEditor::PropertyModel::removeRows().
removeProperty()
bool PropertyItem::removeProperty (const App::Property * prop)
Definition at line 222 of file PropertyItem.cpp.
References DraftVecUtils::find().
Referenced by Gui::PropertyEditor::PropertyModel::removeProperty().
reset()
void PropertyItem::reset ()
Definition at line 129 of file PropertyItem.cpp.
Referenced by ArchVRM.Renderer::__init__(), draftguitools.gui_trackers.gridTracker::set(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testAll(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
row()
int PropertyItem::row () const virtual
Reimplemented in Gui::PropertyEditor::PropertySeparatorItem.
Definition at line 794 of file PropertyItem.cpp.
Referenced by Gui::PropertyEditor::PropertyModel::parent(), Gui::PropertyEditor::PropertyModel::propertyIndexFromPath(), Gui::PropertyEditor::PropertyModel::removeProperty(), Gui::PropertyEditor::PropertySeparatorItem::row(), and Gui::PropertyEditor::PropertyModel::updateProperty().
setData()
bool PropertyItem::setData (const QVariant & value)
Definition at line 764 of file PropertyItem.cpp.
References Init::parent.
Referenced by Gui::PropertyEditor::PropertyMatrixItem::setA11(), Gui::PropertyEditor::PropertyMatrixItem::setA12(), Gui::PropertyEditor::PropertyMatrixItem::setA13(), Gui::PropertyEditor::PropertyMatrixItem::setA14(), Gui::PropertyEditor::PropertyMatrixItem::setA21(), Gui::PropertyEditor::PropertyMatrixItem::setA22(), Gui::PropertyEditor::PropertyMatrixItem::setA23(), Gui::PropertyEditor::PropertyMatrixItem::setA24(), Gui::PropertyEditor::PropertyMatrixItem::setA31(), Gui::PropertyEditor::PropertyMatrixItem::setA32(), Gui::PropertyEditor::PropertyMatrixItem::setA33(), Gui::PropertyEditor::PropertyMatrixItem::setA34(), Gui::PropertyEditor::PropertyMatrixItem::setA41(), Gui::PropertyEditor::PropertyMatrixItem::setA42(), Gui::PropertyEditor::PropertyMatrixItem::setA43(), Gui::PropertyEditor::PropertyMatrixItem::setA44(), Gui::PropertyEditor::PropertyEnumItem::setEnum(), Gui::PropertyEditor::PropertyVectorDistanceItem::setX(), Gui::PropertyEditor::PropertyVectorDistanceItem::setY(), Gui::PropertyEditor::PropertyVectorDistanceItem::setZ(), and Gui::Dialog::DlgAddPropertyVarSet::valueChanged().
setDecimals()
void PropertyItem::setDecimals (int prec)
Definition at line 359 of file PropertyItem.cpp.
References draftgeoutils.general::precision().
setEditorData()
void PropertyItem::setEditorData (QWidget * editor, const QVariant & data) const virtual
Reimplemented in Gui::PropertyEditor::PropertyLinkItem, Gui::PropertyEditor::PropertyTransientFileItem, Gui::PropertyEditor::PropertyPathItem, Gui::PropertyEditor::PropertyFileItem, Gui::PropertyEditor::PropertyMaterialListItem, Gui::PropertyEditor::PropertyMaterialItem, Gui::PropertyEditor::PropertyColorItem, Gui::PropertyEditor::PropertyIntegerListItem, Gui::PropertyEditor::PropertyFloatListItem, Gui::PropertyEditor::PropertyStringListItem, Gui::PropertyEditor::PropertyEnumItem, Gui::PropertyEditor::PropertyPlacementItem, Gui::PropertyEditor::PropertyRotationItem, Gui::PropertyEditor::PropertyMatrixItem, Gui::PropertyEditor::PropertyVectorDistanceItem, Gui::PropertyEditor::PropertyVectorListItem, Gui::PropertyEditor::PropertyVectorItem, Gui::PropertyEditor::PropertyBoolItem, Gui::PropertyEditor::PropertyAngleItem, Gui::PropertyEditor::PropertyFloatConstraintItem, Gui::PropertyEditor::PropertyUnitConstraintItem, Gui::PropertyEditor::PropertyUnitItem, Gui::PropertyEditor::PropertyFloatItem, Gui::PropertyEditor::PropertyIntegerConstraintItem, Gui::PropertyEditor::PropertyIntegerItem, Gui::PropertyEditor::PropertyFontItem, Gui::PropertyEditor::PropertyStringItem, and PartGui::PropertyEnumAttacherItem.
Definition at line 508 of file PropertyItem.cpp.
setExpanded()
void PropertyItem::setExpanded (bool e)
Definition at line 338 of file PropertyItem.cpp.
Referenced by Gui::PropertyEditor::PropertyEditor::onItemCollapsed(), and Gui::PropertyEditor::PropertyEditor::onItemExpanded().
setExpressionEditorData()
void PropertyItem::setExpressionEditorData (QWidget * editor, const QVariant & data) const
Definition at line 531 of file PropertyItem.cpp.
References Path.Post.Utils::editor().
setLinked()
void PropertyItem::setLinked (bool value)
Definition at line 325 of file PropertyItem.cpp.
setParent()
void PropertyItem::setParent (PropertyItem * parent)
Definition at line 248 of file PropertyItem.cpp.
References Init::parent.
Referenced by SketcherGui::PropertyConstraintListItem::initialize(), Gui::PropertyEditor::PropertyEnumItem::PropertyEnumItem(), FemGui::PropertyFemMeshItem::PropertyFemMeshItem(), Gui::PropertyEditor::PropertyMaterialItem::PropertyMaterialItem(), Gui::PropertyEditor::PropertyMaterialListItem::PropertyMaterialListItem(), Gui::PropertyEditor::PropertyMatrixItem::PropertyMatrixItem(), MeshGui::PropertyMeshKernelItem::PropertyMeshKernelItem(), Gui::PropertyEditor::PropertyPlacementItem::PropertyPlacementItem(), Gui::PropertyEditor::PropertyRotationItem::PropertyRotationItem(), Gui::PropertyEditor::PropertyVectorDistanceItem::PropertyVectorDistanceItem(), Gui::PropertyEditor::PropertyVectorItem::PropertyVectorItem(), and takeChild().
setPropertyData()
void PropertyItem::setPropertyData (const std::vector< App::Property * > & items)
Sets the current property objects.
Definition at line 162 of file PropertyItem.cpp.
References draftgeoutils.faces::bind(), App::Property::getContainer(), App::Property::getPaths(), getProperty(), SplineSurface::id, and src.Mod.Test.testPathArray::items.
Referenced by Gui::PropertyEditor::PropertyModel::appendProperty().
setPropertyName()
void PropertyItem::setPropertyName (const QString & name, const QString & realName = QString())
Definition at line 569 of file PropertyItem.cpp.
References femsolver.report::display(), SplineSurface::i, Path.Post.scripts.refactored_centroid_post::str, and src.Mod.AddonManager.Addon::translate.
Referenced by SketcherGui::PropertyConstraintListItem::initialize(), and setPropertyItemName().
setPropertyValue() [1/2]
void PropertyItem::setPropertyValue (const QString & value)
Definition at line 658 of file PropertyItem.cpp.
Referenced by Gui::PropertyEditor::PropertyVectorListItem::setValue(), Gui::PropertyEditor::PropertyVectorDistanceItem::setValue(), Gui::PropertyEditor::PropertyMatrixItem::setValue(), Gui::PropertyEditor::PropertyRotationItem::setValue(), Gui::PropertyEditor::PropertyPlacementItem::setValue(), Gui::PropertyEditor::PropertyEnumItem::setValue(), Gui::PropertyEditor::PropertyStringListItem::setValue(), Gui::PropertyEditor::PropertyFloatListItem::setValue(), Gui::PropertyEditor::PropertyIntegerListItem::setValue(), Gui::PropertyEditor::PropertyColorItem::setValue(), Gui::PropertyEditor::PropertyMaterialItem::setValue(), Gui::PropertyEditor::PropertyMaterialListItem::setValue(), Gui::PropertyEditor::PropertyFileItem::setValue(), Gui::PropertyEditor::PropertyPathItem::setValue(), Gui::PropertyEditor::PropertyTransientFileItem::setValue(), and Gui::PropertyEditor::PropertyLinkItem::setValue().
setPropertyValue() [2/2]
void PropertyItem::setPropertyValue (const std::string & value) protected
Definition at line 602 of file PropertyItem.cpp.
References Gui::Command::App, Base::Console(), toolbit-attributes::doc, SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), UtilsAssembly::getObject(), Init::parent, App::Property::ReadOnly, and runCommand.
setReadOnly()
void PropertyItem::setReadOnly (bool ro)
Definition at line 312 of file PropertyItem.cpp.
Referenced by MeshGui::PropertyMeshKernelItem::initialize(), and FemGui::PropertyFemMeshItem::initialize().
setValue()
void PropertyItem::setValue (const QVariant &) protected virtual
Reimplemented in Gui::PropertyEditor::PropertyLinkItem, Gui::PropertyEditor::PropertyTransientFileItem, Gui::PropertyEditor::PropertyPathItem, Gui::PropertyEditor::PropertyFileItem, Gui::PropertyEditor::PropertyMaterialListItem, Gui::PropertyEditor::PropertyMaterialItem, Gui::PropertyEditor::PropertyColorItem, Gui::PropertyEditor::PropertyIntegerListItem, Gui::PropertyEditor::PropertyFloatListItem, Gui::PropertyEditor::PropertyStringListItem, Gui::PropertyEditor::PropertyEnumItem, Gui::PropertyEditor::PropertyPlacementItem, Gui::PropertyEditor::PropertyRotationItem, Gui::PropertyEditor::PropertyMatrixItem, Gui::PropertyEditor::PropertyVectorDistanceItem, Gui::PropertyEditor::PropertyVectorListItem, Gui::PropertyEditor::PropertyVectorItem, Gui::PropertyEditor::PropertyBoolItem, Gui::PropertyEditor::PropertyFloatConstraintItem, Gui::PropertyEditor::PropertyUnitItem, Gui::PropertyEditor::PropertyFloatItem, Gui::PropertyEditor::PropertyIntegerConstraintItem, Gui::PropertyEditor::PropertyIntegerItem, Gui::PropertyEditor::PropertyFontItem, Gui::PropertyEditor::PropertyStringItem, FemGui::PropertyFemMeshItem, MeshGui::PropertyMeshKernelItem, and SketcherGui::PropertyConstraintListItem.
Definition at line 499 of file PropertyItem.cpp.
takeChild()
PropertyItem * PropertyItem::takeChild (int row)
PropertyItem::takeChild Removes the child at index row but doesn't delete it.
Definition at line 290 of file PropertyItem.cpp.
References setParent().
testStatus()
bool PropertyItem::testStatus (App::Property::Status pos) const
Definition at line 348 of file PropertyItem.cpp.
References RobotExample::pos.
toolTip()
QVariant PropertyItem::toolTip (const App::Property * prop) const protected virtual
Reimplemented in Gui::PropertyEditor::PropertyTransientFileItem, Gui::PropertyEditor::PropertyPathItem, Gui::PropertyEditor::PropertyFileItem, Gui::PropertyEditor::PropertyMaterialListItem, Gui::PropertyEditor::PropertyMaterialItem, Gui::PropertyEditor::PropertyPlacementItem, Gui::PropertyEditor::PropertyRotationItem, Gui::PropertyEditor::PropertyMatrixItem, FemGui::PropertyFemMeshItem, and MeshGui::PropertyMeshKernelItem.
Definition at line 374 of file PropertyItem.cpp.
References App::Property::getDocumentation(), Path.Post.scripts.refactored_centroid_post::str, and src.Mod.AddonManager.Addon::translate.
toString()
QVariant PropertyItem::toString (const QVariant & prop) const protected virtual
Reimplemented in Gui::PropertyEditor::PropertyLinkItem, Gui::PropertyEditor::PropertyMaterialListItem, Gui::PropertyEditor::PropertyMaterialItem, Gui::PropertyEditor::PropertyColorItem, Gui::PropertyEditor::PropertyIntegerListItem, Gui::PropertyEditor::PropertyFloatListItem, Gui::PropertyEditor::PropertyStringListItem, Gui::PropertyEditor::PropertyPlacementItem, Gui::PropertyEditor::PropertyRotationItem, Gui::PropertyEditor::PropertyMatrixItem, Gui::PropertyEditor::PropertyVectorDistanceItem, Gui::PropertyEditor::PropertyVectorListItem, Gui::PropertyEditor::PropertyVectorItem, Gui::PropertyEditor::PropertyAngleItem, Gui::PropertyEditor::PropertyFloatConstraintItem, Gui::PropertyEditor::PropertyUnitItem, Gui::PropertyEditor::PropertyFloatItem, Gui::PropertyEditor::PropertyIntegerConstraintItem, Gui::PropertyEditor::PropertyIntegerItem, and SketcherGui::PropertyConstraintListItem.
Definition at line 461 of file PropertyItem.cpp.
References SCL.SimpleDataTypes::e, and DraftVecUtils::toString().
Referenced by Gui::PropertyEditor::PropertyItemAttorney::toString(), Gui::PropertyEditor::PropertyIntegerItem::toString(), and Gui::PropertyEditor::PropertyIntegerConstraintItem::toString().
updateData()
void PropertyItem::updateData ()
Definition at line 194 of file PropertyItem.cpp.
References Init::parent, and App::Property::ReadOnly.
Referenced by Path.Main.Gui.JobDlg.JobCreate::exec_(), draftviewproviders.view_wire.ViewProviderWire::onChanged(), draftviewproviders.view_dimension.ViewProviderLinearDimension::onChanged(), draftviewproviders.view_dimension.ViewProviderAngularDimension::onChanged(), Path.Op.Gui.Base.TaskPanelPage::pageUpdateData(), Path.Base.Gui.SetupSheet.OpTaskPanel::setupUi(), Path.Base.Gui.PropertyBag.TaskPanel::setupUi(), and Gui::PropertyEditor::PropertyModel::updateProperty().
value()
QVariant PropertyItem::value (const App::Property *) const protected virtual
Reimplemented in Gui::PropertyEditor::PropertyLinkItem, Gui::PropertyEditor::PropertyTransientFileItem, Gui::PropertyEditor::PropertyPathItem, Gui::PropertyEditor::PropertyFileItem, Gui::PropertyEditor::PropertyMaterialListItem, Gui::PropertyEditor::PropertyMaterialItem, Gui::PropertyEditor::PropertyColorItem, Gui::PropertyEditor::PropertyIntegerListItem, Gui::PropertyEditor::PropertyFloatListItem, Gui::PropertyEditor::PropertyStringListItem, Gui::PropertyEditor::PropertyEnumItem, Gui::PropertyEditor::PropertyPlacementItem, Gui::PropertyEditor::PropertyRotationItem, Gui::PropertyEditor::PropertyMatrixItem, Gui::PropertyEditor::PropertyVectorDistanceItem, Gui::PropertyEditor::PropertyVectorListItem, Gui::PropertyEditor::PropertyVectorItem, Gui::PropertyEditor::PropertyBoolItem, Gui::PropertyEditor::PropertyFloatConstraintItem, Gui::PropertyEditor::PropertyUnitItem, Gui::PropertyEditor::PropertyFloatItem, Gui::PropertyEditor::PropertyIntegerConstraintItem, Gui::PropertyEditor::PropertyIntegerItem, Gui::PropertyEditor::PropertyFontItem, Gui::PropertyEditor::PropertyStringItem, FemGui::PropertyFemMeshItem, MeshGui::PropertyMeshKernelItem, and SketcherGui::PropertyConstraintListItem.
Definition at line 494 of file PropertyItem.cpp.
Referenced by child(), src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), and src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue().
Friends And Related Function Documentation
PropertyItemAttorney
friend class PropertyItemAttorney friend
Definition at line 238 of file PropertyItem.h.
Member Data Documentation
childItems
QList<PropertyItem*> Gui::PropertyEditor::PropertyItem::childItems protected
Definition at line 232 of file PropertyItem.h.
displayText
QString Gui::PropertyEditor::PropertyItem::displayText protected
Definition at line 229 of file PropertyItem.h.
expanded
bool Gui::PropertyEditor::PropertyItem::expanded protected
Definition at line 236 of file PropertyItem.h.
Referenced by src.Mod.AddonManager.package_list.PackageListItemDelegate::update_content().
linked
bool Gui::PropertyEditor::PropertyItem::linked protected
Definition at line 235 of file PropertyItem.h.
Referenced by bimcommands.BimLibrary.BIM_Library_TaskPanel::link().
parentItem
PropertyItem* Gui::PropertyEditor::PropertyItem::parentItem protected
Definition at line 231 of file PropertyItem.h.
precision
int Gui::PropertyEditor::PropertyItem::precision protected
Definition at line 234 of file PropertyItem.h.
Referenced by ifc2x3.ifcgeometricrepresentationsubcontext::ifcgeometricrepresentationcontext_precision(), and ifc4.ifcgeometricrepresentationsubcontext::ifcgeometricrepresentationcontext_precision().
propertyItems
std::vector<App::Property*> Gui::PropertyEditor::PropertyItem::propertyItems protected
Definition at line 230 of file PropertyItem.h.
Referenced by Gui::PropertyEditor::PropertyLinkItem::createEditor(), Gui::PropertyEditor::PropertyLinkItem::data(), and Gui::PropertyEditor::PropertyLinkItem::toString().
propName
QString Gui::PropertyEditor::PropertyItem::propName protected
Definition at line 228 of file PropertyItem.h.
readonly
bool Gui::PropertyEditor::PropertyItem::readonly protected
Definition at line 233 of file PropertyItem.h.
Referenced by Gui::PropertyEditor::PropertyPlacementItem::createEditor().
The documentation for this class was generated from the following files:
PropertyItem.h
PropertyItem.cpp