FreeCAD: Gui::SoBoxSelectionRenderAction Class Reference
Gui::SoBoxSelectionRenderAction Class Reference
#include <SoFCSelectionAction.h>
Public Member Functions
SoBoxSelectionRenderAction ()
SoBoxSelectionRenderAction (const SbViewportRegion &viewportregion)
~SoBoxSelectionRenderAction () override
void apply (SoNode *node) override
void apply (SoPath *path) override
void apply (const SoPathList &pathlist, SbBool obeysrules=false) override
void setVisible (SbBool b)
SbBool isVisible () const
void setColor (const SbColor &color)
const SbColor & getColor ()
void setLinePattern (unsigned short pattern)
unsigned short getLinePattern () const
void setLineWidth (const float width)
float getLineWidth () const
Static Public Member Functions
static void initClass ()
Protected Attributes
SbBool hlVisible
Detailed Description
The SoBoxSelectionRenderAction class renders the scene with highlighted boxes around selections.
Author
Werner Mayer
Definition at line 313 of file SoFCSelectionAction.h.
Constructor & Destructor Documentation
SoBoxSelectionRenderAction() [1/2]
SoBoxSelectionRenderAction::SoBoxSelectionRenderAction ()
Definition at line 1060 of file SoFCSelectionAction.cpp.
SoBoxSelectionRenderAction() [2/2]
SoBoxSelectionRenderAction::SoBoxSelectionRenderAction (const SbViewportRegion & viewportregion)
Definition at line 1066 of file SoFCSelectionAction.cpp.
~SoBoxSelectionRenderAction()
SoBoxSelectionRenderAction::~SoBoxSelectionRenderAction () override
Definition at line 1101 of file SoFCSelectionAction.cpp.
References PRIVATE.
Member Function Documentation
apply() [1/3]
void SoBoxSelectionRenderAction::apply (const SoPathList & pathlist, SbBool obeysrules = false) override
Definition at line 1228 of file SoFCSelectionAction.cpp.
apply() [2/3]
void SoBoxSelectionRenderAction::apply (SoNode * node) override
Definition at line 1118 of file SoFCSelectionAction.cpp.
References Gui::SoFCSelection::BOX, hlVisible, SplineSurface::i, Gui::SoFCSelection::NOTSELECTED, PRIVATE, and Path.Dressup.Utils::selection().
Referenced by Gui::View3DInventorViewer::renderToFramebuffer().
apply() [3/3]
void SoBoxSelectionRenderAction::apply (SoPath * path) override
Definition at line 1183 of file SoFCSelectionAction.cpp.
References Gui::SoFCSelection::BOX, Gui::SoFCSelection::NOTSELECTED, PRIVATE, and Path.Dressup.Utils::selection().
getColor()
const SbColor & SoBoxSelectionRenderAction::getColor ()
Definition at line 1241 of file SoFCSelectionAction.cpp.
References PRIVATE.
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::setValues().
getLinePattern()
unsigned short SoBoxSelectionRenderAction::getLinePattern () const
Definition at line 1253 of file SoFCSelectionAction.cpp.
References PRIVATE.
getLineWidth()
float SoBoxSelectionRenderAction::getLineWidth () const
Definition at line 1265 of file SoFCSelectionAction.cpp.
References PRIVATE.
initClass()
void SoBoxSelectionRenderAction::initClass () static
Definition at line 1055 of file SoFCSelectionAction.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
isVisible()
SbBool Gui::SoBoxSelectionRenderAction::isVisible () const inline
Definition at line 329 of file SoFCSelectionAction.h.
Referenced by ArchVRM.Renderer::removeHidden().
setColor()
void SoBoxSelectionRenderAction::setColor (const SbColor & color)
Definition at line 1235 of file SoFCSelectionAction.cpp.
References PRIVATE.
setLinePattern()
void SoBoxSelectionRenderAction::setLinePattern (unsigned short pattern)
Definition at line 1247 of file SoFCSelectionAction.cpp.
References PRIVATE.
setLineWidth()
void SoBoxSelectionRenderAction::setLineWidth (const float width)
Definition at line 1259 of file SoFCSelectionAction.cpp.
References PRIVATE.
setVisible()
void Gui::SoBoxSelectionRenderAction::setVisible (SbBool b) inline
Definition at line 328 of file SoFCSelectionAction.h.
References SCL.SimpleDataTypes::b.
Member Data Documentation
hlVisible
SbBool Gui::SoBoxSelectionRenderAction::hlVisible protected
Definition at line 338 of file SoFCSelectionAction.h.
Referenced by apply().
The documentation for this class was generated from the following files:
SoFCSelectionAction.h
SoFCSelectionAction.cpp