FreeCAD: App::PropertyEnumeration Class Reference
App::PropertyEnumeration Class Reference
Property wrapper around an Enumeration object.
#include <PropertyStandard.h>
Public Member Functions
PropertyEnumeration ()
Standard constructor.
PropertyEnumeration (const Enumeration &e)
Obvious constructor.
~PropertyEnumeration () override
destructor
void setEnums (const char **plEnums)
Enumeration methods.
void setEnums (const std::vector< std::string > &Enums)
void setValue (const char *value)
void setValue (long)
void setValue (const Enumeration &source)
Setter using Enumeration.
long getValue () const
Returns current value of the enumeration as an integer.
bool isValue (const char *value) const
checks if the property is set to a certain string value
bool isPartOf (const char *value) const
checks if a string is included in the enumeration
const char * getValueAsString () const
get the value as string
const Enumeration & getEnum () const
Returns Enumeration object.
std::vector< std::string > getEnumVector () const
get all possible enum values as vector of strings
void setEnumVector (const std::vector< std::string > &)
set enum values as vector of strings
bool hasEnums () const
get the pointer to the enum list
bool isValid () const
Returns true if the instance is in a usable state.
const char * getEditorName () const override
Get the class name of the associated property editor item.
void setEditorName (const char *name)
PyObject * getPyObject () override
void setPyObject (PyObject *py) override
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
Property * Copy () const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
void setPathValue (const App::ObjectIdentifier &path, const boost::any &value) override
Set value of property.
virtual bool setPyPathValue (const App::ObjectIdentifier &path, const Py::Object &value)
const boost::any getPathValue (const App::ObjectIdentifier &) const override
Get value of property.
bool getPyPathValue (const ObjectIdentifier &path, Py::Object &r) const override
Get Python value of property.
bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
Public Member Functions inherited from App::Property
Property ()
~Property () override
unsigned int getMemSize () const override
const char * getName () const
bool hasName () const
std::string getFullName () const
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual void afterRestore ()
virtual void onContainerRestored ()
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
int64_t getID () const
virtual void beforeSave () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::Property
virtual void hasSetValue ()
Gets called by all setValue() methods after the value has changed.
virtual void aboutToSetValue ()
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Detailed Description
Property wrapper around an Enumeration object.
Definition at line 160 of file PropertyStandard.h.
Constructor & Destructor Documentation
PropertyEnumeration() [1/2]
PropertyEnumeration::PropertyEnumeration ()
Standard constructor.
Definition at line 279 of file PropertyStandard.cpp.
PropertyEnumeration() [2/2]
PropertyEnumeration::PropertyEnumeration (const Enumeration & e) explicit
Obvious constructor.
Definition at line 284 of file PropertyStandard.cpp.
References SCL.SimpleDataTypes::e.
~PropertyEnumeration()
PropertyEnumeration::~PropertyEnumeration () override default
destructor
Member Function Documentation
Copy()
Property * PropertyEnumeration::Copy () const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 524 of file PropertyStandard.cpp.
getEditorName()
const char* App::PropertyEnumeration::getEditorName () const inline override virtual
Get the class name of the associated property editor item.
Reimplemented from App::Property.
Definition at line 233 of file PropertyStandard.h.
getEnum()
const Enumeration & PropertyEnumeration::getEnum () const
Returns Enumeration object.
Definition at line 355 of file PropertyStandard.cpp.
Referenced by App::FeatureTest::execute().
getEnumVector()
std::vector< std::string > PropertyEnumeration::getEnumVector () const
get all possible enum values as vector of strings
Definition at line 360 of file PropertyStandard.cpp.
Referenced by FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), FemGui::TaskFemConstraintRigidBody::TaskFemConstraintRigidBody(), FemGui::TaskFemConstraintSpring::TaskFemConstraintSpring(), FemGui::TaskFemConstraintTemperature::TaskFemConstraintTemperature(), and FemGui::TaskPostBox::updateEnumerationList().
getPathValue()
const boost::any PropertyEnumeration::getPathValue (const App::ObjectIdentifier & path) const override virtual
Get value of property.
Reimplemented from App::Property.
Definition at line 574 of file PropertyStandard.cpp.
References getValue(), buildPsets::p, src.Mod.Test.testPathArray::path, App::pyObjectToAny(), and TestSpreadsheet::v.
getPyObject()
PyObject * PropertyEnumeration::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 449 of file PropertyStandard.cpp.
References Py_Return.
getPyPathValue()
bool PropertyEnumeration::getPyPathValue (const ObjectIdentifier & , Py::Object &) const override virtual
Get Python value of property.
Reimplemented from App::Property.
Definition at line 592 of file PropertyStandard.cpp.
References enums, App::PropertyString::getPyObject(), getValue(), SplineSurface::i, buildPsets::p, src.Mod.Test.testPathArray::path, App::PropertyString::setValue(), src.Mod.Test.testmakeWireString::String, and TestSpreadsheet::v.
getValue()
long PropertyEnumeration::getValue () const
Returns current value of the enumeration as an integer.
Definition at line 332 of file PropertyStandard.cpp.
Referenced by PartGui::TaskDlgAttacher::accept(), PartDesignGui::TaskHelixParameters::apply(), SurfaceGui::GeomFillSurface::changeFillType(), PartDesign::SubShapeBinder::checkCopyOnChange(), Gui::View3DInventorSelection::checkGroupOnTop(), Part::Extrusion::computeFinalParameters(), TechDrawGui::QGIViewDimension::drawAngle(), TechDrawGui::QGIViewDimension::drawArea(), TechDrawGui::QGIViewBalloon::drawBalloon(), TechDrawGui::QGIViewPart::drawBreakLines(), TechDrawGui::QGIViewDimension::drawDiameter(), TechDrawGui::QGIViewDimension::drawDistance(), Gui::ViewProviderAnnotationLabel::drawImage(), TechDrawGui::QGIViewDimension::drawRadius(), PartDesign::Helix::execute(), Part::RuledSurface::execute(), PartDesign::Thickness::execute(), PartDesign::Pipe::execute(), PartDesign::Chamfer::execute(), Part::Offset::execute(), Part::Offset2D::execute(), TechDraw::DrawViewArch::execute(), PartDesign::Transformed::execute(), Part::Sweep::execute(), PartDesign::SubShapeBinder::execute(), Part::Thickness::execute(), Part::Helix::execute(), Surface::GeomFillSurface::getFillingStyle(), TechDraw::DrawPage::getOrientation(), TechDraw::DrawProjGroupItem::getScaleType(), PartDesign::ProfileBased::getSupportFace(), PartDesign::ProfileBased::getTopoShapeSupportFace(), PartGui::HelixPrimitive::HelixPrimitive(), TechDrawGui::TaskProjGroup::initializeUi(), PartDesign::Transformed::isMultiTransformChild(), TechDrawGui::QGILeaderLine::makeLeaderPath(), PartDesign::Chamfer::mustExecute(), Gui::ViewProviderImagePlane::onChanged(), Gui::ViewProviderAnnotation::onChanged(), PartDesignGui::ViewProviderBody::onChanged(), PartDesignGui::ViewProviderBoolean::onChanged(), PartDesign::Hole::onChanged(), PartDesign::Helix::onChanged(), PartDesign::SubShapeBinder::onChanged(), FemGui::ViewProviderFemMesh::onChanged(), PartGui::ViewProviderPartExt::onChanged(), Gui::ViewProviderDocumentObject::onChanged(), MeshGui::ViewProviderMesh::onChanged(), Gui::ElementColors::Private::Private(), PartDesign::Helix::safePitch(), TechDrawGui::TaskDimRepair::saveDimState(), TechDrawGui::QGILeaderLine::setArrows(), PartDesignGui::ViewProviderBody::setDisplayMode(), SurfaceGui::GeomFillSurface::setEditedObject(), PartDesignGui::ViewProviderDatumLine::setExtents(), PartDesignGui::ViewProviderDatumPlane::setExtents(), PartDesignGui::ViewProviderBody::setOverrideMode(), TechDrawGui::TaskComplexSection::setUiEdit(), TechDrawGui::TaskRichAnno::setUiEdit(), TechDrawGui::TaskLeaderLine::setUiEdit(), TechDrawGui::TaskDetail::setUiFromFeat(), PartDesign::Pipe::setupAlgorithm(), PartDesign::SubShapeBinder::setupCopyOnChange(), Gui::Application::slotActiveDocument(), PartGui::TaskAttacher::TaskAttacher(), PartDesignGui::TaskBooleanParameters::TaskBooleanParameters(), TechDrawGui::TaskDimension::TaskDimension(), FemGui::TaskFemConstraintSpring::TaskFemConstraintSpring(), FemGui::TaskFemConstraintTemperature::TaskFemConstraintTemperature(), PartDesignGui::TaskPipeOrientation::TaskPipeOrientation(), PartDesignGui::TaskPipeParameters::TaskPipeParameters(), PartDesignGui::TaskPipeScaling::TaskPipeScaling(), FemGui::TaskTetParameter::TaskTetParameter(), RobotGui::TaskTrajectoryDressUpParameter::TaskTrajectoryDressUpParameter(), PartGui::ThicknessWidget::ThicknessWidget(), TechDrawGui::TaskProjGroup::turnProjGroupToView(), PartDesign::SubShapeBinder::update(), PartDesignGui::ViewProviderDatumLine::updateData(), PartDesignGui::ViewProviderDatumPlane::updateData(), FemGui::TaskPostBox::updateEnumerationList(), PartDesign::Chamfer::updateProperties(), and TechDrawGui::TaskProjGroup::updateTask().
getValueAsString()
const char * PropertyEnumeration::getValueAsString () const
get the value as string
Definition at line 347 of file PropertyStandard.cpp.
Referenced by TechDrawGui::_getDimensions(), FemGui::TaskDlgFemConstraintFluidBoundary::accept(), TechDraw::DrawProjGroup::arrangeViewPointers(), TechDraw::DrawProjGroupItem::autoPosition(), TechDrawGui::QGIViewBalloon::drawBalloon(), PartDesign::Hole::execute(), PartDesign::Boolean::execute(), PartDesign::Helix::generateHelixPath(), TechDraw::DrawProjGroup::getDirsFromFront(), Assembly::AssemblyObject::getGroundedParts(), TechDraw::DrawPage::getPageOrientation(), FemGui::TaskFemConstraintFluidBoundary::getTurbulenceModel(), TechDraw::DrawProjGroup::getViewIndex(), TechDraw::DrawViewSection::getXDirection(), PartDesignGui::ViewProviderBody::onChanged(), FemGui::ViewProviderFemPostObject::onChanged(), Fem::ConstraintTransform::onChanged(), Fem::ConstraintFluidBoundary::onChanged(), PartDesign::Hole::onChanged(), TechDraw::DrawProjGroup::purgeProjections(), TechDrawGui::TaskProjGroup::saveGroupState(), TechDrawGui::TaskSectionView::saveSectionState(), TechDrawGui::TaskComplexSection::saveSectionState(), Gui::ViewProviderDocumentObject::setActiveMode(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), FemGui::TaskFemConstraintHeatflux::TaskFemConstraintHeatflux(), FemGui::TaskFemConstraintTransform::TaskFemConstraintTransform(), TechDrawGui::TaskSectionView::TaskSectionView(), TechDraw::DrawProjGroupItem::unsetupObject(), FemGui::ViewProviderFemConstraintFluidBoundary::updateData(), TechDrawGui::ViewProviderProjGroupItem::updateIcon(), and TechDraw::DrawProjGroup::usedProjectionType().
hasEnums()
bool PropertyEnumeration::hasEnums () const
get the pointer to the enum list
Definition at line 380 of file PropertyStandard.cpp.
isPartOf()
bool PropertyEnumeration::isPartOf (const char * value) const
checks if a string is included in the enumeration
Definition at line 342 of file PropertyStandard.cpp.
isSame()
bool App::PropertyEnumeration::isSame (const Property & other) const inline override virtual
Compare if this property has the same content as the given one.
Reimplemented from App::Property.
Definition at line 256 of file PropertyStandard.h.
References Base::Persistence::getTypeId().
isValid()
bool PropertyEnumeration::isValid () const
Returns true if the instance is in a usable state.
Definition at line 385 of file PropertyStandard.cpp.
Referenced by PartDesign::Hole::onChanged(), and Gui::ViewProviderDocumentObject::setActiveMode().
isValue()
bool PropertyEnumeration::isValue (const char * value) const
checks if the property is set to a certain string value
Definition at line 337 of file PropertyStandard.cpp.
Referenced by TechDraw::DrawProjGroup::arrangeViewPointers(), TechDraw::DrawView::checkScale(), TechDraw::DrawViewDimExtent::execute(), TechDraw::DrawProjGroup::execute(), TechDraw::DimensionFormatter::formatValue(), TechDraw::DrawView::getScale(), TechDraw::DrawProjGroup::getViewIndex(), TechDrawGui::TaskProjGroup::initializeUi(), TechDraw::DimensionFormatter::isMultiValueSchema(), TechDraw::DrawViewSection::onChanged(), TechDraw::DrawView::onChanged(), TechDraw::DrawProjGroup::onChanged(), TechDraw::DrawViewDetail::postHlrTasks(), TechDraw::DrawViewSection::postHlrTasks(), TechDraw::DrawViewPart::postHlrTasks(), TechDraw::DrawView::prefScale(), TechDrawGui::TaskProjGroup::scaleManuallyChanged(), TechDraw::DrawView::setScaleAttribute(), TechDrawGui::TaskSectionView::setUiEdit(), TechDraw::DrawView::validateScale(), and TechDrawGui::TaskProjGroup::viewToggled().
Paste()
void PropertyEnumeration::Paste (const Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 529 of file PropertyStandard.cpp.
Restore()
void PropertyEnumeration::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 411 of file PropertyStandard.cpp.
References Base::Console(), src.Mod.AddonManager.NetworkManager::count, Base::ConsoleSingleton::DeveloperWarning(), getValue(), SplineSurface::i, TechDrawTools.TaskFillTemplateFields::reader, and toolbit-attributes::val.
Referenced by TechDraw::DrawViewBalloon::handleChangedPropertyName().
Save()
void PropertyEnumeration::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 390 of file PropertyStandard.cpp.
References Base::Writer::decInd(), Base::Writer::incInd(), Base::Writer::ind(), src.Mod.Test.testPathArray::items, Base::Writer::Stream(), and toolbit-attributes::val.
setEditorName()
void App::PropertyEnumeration::setEditorName (const char * name) inline
Definition at line 237 of file PropertyStandard.h.
Referenced by Part::AttachExtension::initBase().
setEnums() [1/2]
void PropertyEnumeration::setEnums (const char ** plEnums)
Enumeration methods.
These all function as per documentation in Enumeration setting the enumeration string list The list is a NULL terminated array of pointers to a const char* string
const char enums[] = {"Black","White","Other",NULL}
Definition at line 291 of file PropertyStandard.cpp.
References femsolver.signal::notify().
Referenced by Gui::ViewProviderDocumentObject::attach(), PartDesign::Boolean::Boolean(), PartDesign::Chamfer::Chamfer(), Fem::ConstraintFluidBoundary::ConstraintFluidBoundary(), Fem::ConstraintHeatflux::ConstraintHeatflux(), Fem::ConstraintRigidBody::ConstraintRigidBody(), Fem::ConstraintTemperature::ConstraintTemperature(), Fem::ConstraintTransform::ConstraintTransform(), App::Document::Document(), TechDraw::DrawPage::DrawPage(), TechDraw::DrawTemplate::DrawTemplate(), TechDraw::DrawViewAnnotation::DrawViewAnnotation(), TechDraw::DrawViewArch::DrawViewArch(), TechDraw::DrawViewBalloon::DrawViewBalloon(), Part::Extrusion::Extrusion(), App::FeatureTest::FeatureTest(), Surface::GeomFillSurface::GeomFillSurface(), PartDesign::Helix::Helix(), Part::Helix::Helix(), PartDesign::Hole::Hole(), Part::AttachExtension::initBase(), Fem::ConstraintFluidBoundary::onChanged(), PartDesign::Hole::onChanged(), Part::ProjectOnSurface::ProjectOnSurface(), Part::RuledSurface::RuledSurface(), App::LinkBaseExtension::setProperty(), PartDesign::Transformed::Transformed(), PartDesignGui::ViewProviderBoolean::ViewProviderBoolean(), FemGui::ViewProviderFemMesh::ViewProviderFemMesh(), Gui::ViewProviderImagePlane::ViewProviderImagePlane(), PartGui::ViewProviderPartExt::ViewProviderPartExt(), and Gui::ViewProviderDocumentObject::~ViewProviderDocumentObject().
setEnums() [2/2]
void PropertyEnumeration::setEnums (const std::vector< std::string > & Enums)
setting the enumeration string as vector of strings This makes the enumeration custom.
Definition at line 306 of file PropertyStandard.cpp.
setEnumVector()
void PropertyEnumeration::setEnumVector (const std::vector< std::string > & values)
set enum values as vector of strings
Definition at line 365 of file PropertyStandard.cpp.
References femsolver.signal::notify().
setPathValue()
void PropertyEnumeration::setPathValue (const App::ObjectIdentifier & path, const boost::any & value) override virtual
Set value of property.
Reimplemented from App::Property.
Definition at line 535 of file PropertyStandard.cpp.
References App::pyObjectFromAny().
setPyObject()
void PropertyEnumeration::setPyObject (PyObject * py) override virtual
Reimplemented from Base::BaseClass.
Definition at line 458 of file PropertyStandard.cpp.
References SCL.SimpleDataTypes::e, FC_THROWM, SplineSurface::i, Path.Post.scripts.refactored_centroid_post::str, TestSpreadsheet::v, and toolbit-attributes::val.
setPyPathValue()
bool PropertyEnumeration::setPyPathValue (const App::ObjectIdentifier & path, const Py::Object & value) virtual
Definition at line 568 of file PropertyStandard.cpp.
setValue() [1/3]
void PropertyEnumeration::setValue (const char * value)
set the enum by a string is slower than setValue(long). Use long if possible
Definition at line 311 of file PropertyStandard.cpp.
Referenced by TechDraw::DrawProjGroup::addProjection(), Gui::ViewProviderDocumentObject::attach(), SurfaceGui::GeomFillSurface::changeFillType(), PartGui::HelixPrimitive::changeValue(), PartDesign::SubShapeBinder::checkCopyOnChange(), TechDrawGui::TaskLeaderLine::commonFeatureUpdate(), App::Document::Document(), TechDraw::DrawViewArch::DrawViewArch(), Gui::ElementColors::ElementColors(), TechDraw::DrawSVGTemplate::extractTemplateAttributes(), PartDesignGui::TaskFeaturePick::makeCopy(), Fem::ConstraintFluidBoundary::onChanged(), TechDrawGui::TaskDetail::onScaleTypeEdit(), TechDrawGui::TaskProjGroup::projectionTypeChanged(), TechDrawGui::TaskProjGroup::restoreGroupState(), TechDrawGui::TaskSectionView::restoreSectionState(), TechDrawGui::TaskComplexSection::restoreSectionState(), TechDrawGui::TaskProjGroup::scaleTypeChanged(), TechDrawGui::TaskProjGroup::turnProjGroupToView(), TechDrawGui::TaskProjGroup::turnViewToProjGroup(), TechDrawGui::TaskRichAnno::updateAnnoFeature(), TechDrawGui::TaskLeaderLine::updateLeaderFeature(), TechDraw::DrawView::validateScale(), PartDesignGui::ViewProviderDatumCoordinateSystem::ViewProviderDatumCoordinateSystem(), RobotGui::TaskTrajectoryDressUpParameter::writeValues(), and Gui::ElementColors::Private::~Private().
setValue() [2/3]
void PropertyEnumeration::setValue (const Enumeration & source)
Setter using Enumeration.
Definition at line 325 of file PropertyStandard.cpp.
setValue() [3/3]
void PropertyEnumeration::setValue (long value)
set directly the enum value In DEBUG checks for boundaries. Is faster than using setValue(const char*).
Definition at line 318 of file PropertyStandard.cpp.
The documentation for this class was generated from the following files:
PropertyStandard.h
PropertyStandard.cpp