FreeCAD: Path.Post.scripts.dxf_post Namespace Reference
Path.Post.scripts.dxf_post Namespace Reference
Functions
def processArguments (argstring)
def export (objectslist, filename, argstring)
def dxfWrite (objlist, filename)
def parse (pathobj)
Variables
TOOLTIP
TOOLTIP_ARGS
now
OUTPUT_HEADER
Function Documentation
dxfWrite()
def Path.Post.scripts.dxf_post.dxfWrite (objlist, filename)
Definition at line 85 of file dxf_post.py.
References importDXF.export().
export()
def Path.Post.scripts.dxf_post.export (objectslist, filename, argstring)
Definition at line 67 of file dxf_post.py.
parse()
def Path.Post.scripts.dxf_post.parse (pathobj)
accepts a Path object.  Returns a list of wires
Definition at line 89 of file dxf_post.py.
References Path.Log.debug(), and Path.Geom.edgeForCmd().
processArguments()
def Path.Post.scripts.dxf_post.processArguments (argstring)
Definition at line 62 of file dxf_post.py.
Variable Documentation
now
Path.Post.scripts.dxf_post.now
Definition at line 49 of file dxf_post.py.
OUTPUT_HEADER
Path.Post.scripts.dxf_post.OUTPUT_HEADER
Definition at line 52 of file dxf_post.py.
TOOLTIP
Path.Post.scripts.dxf_post.TOOLTIP
Definition at line 32 of file dxf_post.py.
TOOLTIP_ARGS
Path.Post.scripts.dxf_post.TOOLTIP_ARGS
Definition at line 46 of file dxf_post.py.