FreeCAD: DrawingGui::TaskOrthoViews Class Reference
DrawingGui::TaskOrthoViews Class Reference
#include <TaskOrthoViews.h>
Public Member Functions
TaskOrthoViews (QWidget *parent=nullptr)
~TaskOrthoViews ()
bool user_input ()
void clean_up ()
Protected Slots
void ShowContextMenu (const QPoint &pos)
void setPrimary (int dir)
void cb_toggled (bool toggle)
void projectionChanged (int index)
void hidden (int i)
void smooth (int i)
void toggle_auto (int i)
void data_entered (const QString &text)
void change_axo (int p=3)
void axo_button ()
void axo_scale (const QString &text)
void text_return ()
Protected Member Functions
void changeEvent (QEvent *e)
Detailed Description
Definition at line 202 of file TaskOrthoViews.h.
Constructor & Destructor Documentation
TaskOrthoViews()
TaskOrthoViews::TaskOrthoViews (QWidget * parent = nullptr)
Definition at line 926 of file TaskOrthoViews.cpp.
References KDL::abs(), axo_button(), axo_scale(), cb_toggled(), change_axo(), draftgeoutils.intersections::connect(), data_entered(), toolbit-attributes::doc, App::Application::getActiveDocument(), App::GetApplication(), Base::Persistence::getClassTypeId(), Gui::SelectionSingleton::getObjectsOfType(), hidden(), SplineSurface::i, Init::parent, projectionChanged(), Gui::Selection(), DrawingGui::OrthoViews::set_primary(), setPrimary(), ShowContextMenu(), smooth(), text_return(), and toggle_auto().
~TaskOrthoViews()
TaskOrthoViews::~TaskOrthoViews ()
Definition at line 1025 of file TaskOrthoViews.cpp.
Member Function Documentation
axo_button
void TaskOrthoViews::axo_button () protected slot
Definition at line 1359 of file TaskOrthoViews.cpp.
References change_axo().
Referenced by TaskOrthoViews().
axo_scale
void TaskOrthoViews::axo_scale (const QString & text) protected slot
Definition at line 1364 of file TaskOrthoViews.cpp.
References DrawingGui::OrthoViews::set_Axo_scale().
Referenced by TaskOrthoViews().
cb_toggled
void TaskOrthoViews::cb_toggled (bool toggle) protected slot
Definition at line 1098 of file TaskOrthoViews.cpp.
References DrawingGui::OrthoViews::add_view(), DrawingGui::OrthoViews::del_view(), and DrawingGui::OrthoViews::is_Ortho().
Referenced by TaskOrthoViews().
change_axo
void TaskOrthoViews::change_axo (int p = 3) protected slot
Definition at line 1308 of file TaskOrthoViews.cpp.
References SplineSurface::i, src.Mod.Test.testPathArray::items, RobotExample::pos, and DrawingGui::OrthoViews::set_Axo().
Referenced by axo_button(), and TaskOrthoViews().
changeEvent()
void TaskOrthoViews::changeEvent (QEvent * e) protected
Definition at line 1091 of file TaskOrthoViews.cpp.
References SCL.SimpleDataTypes::e.
clean_up()
void TaskOrthoViews::clean_up ()
Definition at line 1248 of file TaskOrthoViews.cpp.
References DrawingGui::OrthoViews::del_all().
Referenced by DrawingGui::TaskDlgOrthoViews::reject().
data_entered
void TaskOrthoViews::data_entered (const QString & text) protected slot
Definition at line 1229 of file TaskOrthoViews.cpp.
References DrawingGui::OrthoViews::set_configs().
Referenced by TaskOrthoViews().
hidden
void TaskOrthoViews::hidden (int i) protected slot
Definition at line 1192 of file TaskOrthoViews.cpp.
References SplineSurface::i, and DrawingGui::OrthoViews::set_hidden().
Referenced by TaskOrthoViews().
projectionChanged
void TaskOrthoViews::projectionChanged (int index) protected slot
Definition at line 1135 of file TaskOrthoViews.cpp.
References DrawingGui::OrthoViews::set_projection().
Referenced by TaskOrthoViews().
setPrimary
void TaskOrthoViews::setPrimary (int dir) protected slot
Definition at line 1143 of file TaskOrthoViews.cpp.
References draftgeoutils.intersections::connect(), SplineSurface::i, src.Mod.Test.testPathArray::items, RobotExample::pos, and DrawingGui::OrthoViews::set_primary().
Referenced by TaskOrthoViews().
ShowContextMenu
void TaskOrthoViews::ShowContextMenu (const QPoint & pos) protected slot
Definition at line 1031 of file TaskOrthoViews.cpp.
References DrawingGui::OrthoViews::is_Ortho(), RobotExample::pos, DrawingGui::OrthoViews::set_Axo(), and DrawingGui::OrthoViews::set_Ortho().
Referenced by TaskOrthoViews().
smooth
void TaskOrthoViews::smooth (int i) protected slot
Definition at line 1198 of file TaskOrthoViews.cpp.
References SplineSurface::i, and DrawingGui::OrthoViews::set_smooth().
Referenced by TaskOrthoViews().
text_return
void TaskOrthoViews::text_return () protected slot
Definition at line 1396 of file TaskOrthoViews.cpp.
Referenced by TaskOrthoViews().
toggle_auto
void TaskOrthoViews::toggle_auto (int i) protected slot
Definition at line 1203 of file TaskOrthoViews.cpp.
References DrawingGui::OrthoViews::auto_dims(), and SplineSurface::i.
Referenced by TaskOrthoViews().
user_input()
bool TaskOrthoViews::user_input ()
Definition at line 1383 of file TaskOrthoViews.cpp.
Referenced by DrawingGui::TaskDlgOrthoViews::accept().
The documentation for this class was generated from the following files:
TaskOrthoViews.h
TaskOrthoViews.cpp