FreeCAD: Surface::ShapeValidator Class Reference
Surface::ShapeValidator Class Reference
#include <FeatureGeomFillSurface.h>
Public Member Functions
ShapeValidator ()
void initValidator ()
void checkEdge (const TopoDS_Shape &shape)
void checkAndAdd (const TopoDS_Shape &shape, Handle(ShapeExtend_WireData) *aWD=nullptr)
void checkAndAdd (const Part::TopoShape &ts, const char *subName, Handle(ShapeExtend_WireData) *aWire=nullptr)
bool isBezier () const
int numEdges () const
Protected Attributes
bool willBezier
int edgeCount
Detailed Description
Definition at line 60 of file FeatureGeomFillSurface.h.
Constructor & Destructor Documentation
ShapeValidator()
ShapeValidator::ShapeValidator ()
Definition at line 57 of file FeatureGeomFillSurface.cpp.
References initValidator().
Member Function Documentation
checkAndAdd() [1/2]
void ShapeValidator::checkAndAdd (const Part::TopoShape & ts, const char * subName, Handle(ShapeExtend_WireData) * aWire = nullptr)
Definition at line 101 of file FeatureGeomFillSurface.cpp.
References checkAndAdd(), and src.Mod.Test.UnitTests::ts().
checkAndAdd() [2/2]
void ShapeValidator::checkAndAdd (const TopoDS_Shape & shape, Handle(ShapeExtend_WireData) * aWD = nullptr)
Definition at line 91 of file FeatureGeomFillSurface.cpp.
References checkEdge().
Referenced by checkAndAdd(), and Surface::GeomFillSurface::getWire().
checkEdge()
void ShapeValidator::checkEdge (const TopoDS_Shape & shape)
Definition at line 69 of file FeatureGeomFillSurface.cpp.
References edgeCount, Handle(), and willBezier.
Referenced by checkAndAdd().
initValidator()
void ShapeValidator::initValidator ()
Definition at line 62 of file FeatureGeomFillSurface.cpp.
References edgeCount, and willBezier.
Referenced by ShapeValidator().
isBezier()
bool Surface::ShapeValidator::isBezier () const inline
Definition at line 96 of file FeatureGeomFillSurface.h.
Referenced by Surface::GeomFillSurface::getWire().
numEdges()
int Surface::ShapeValidator::numEdges () const inline
Definition at line 100 of file FeatureGeomFillSurface.h.
Referenced by Surface::GeomFillSurface::getWire().
Member Data Documentation
edgeCount
int Surface::ShapeValidator::edgeCount protected
Definition at line 85 of file FeatureGeomFillSurface.h.
Referenced by checkEdge(), and initValidator().
willBezier
bool Surface::ShapeValidator::willBezier protected
Definition at line 84 of file FeatureGeomFillSurface.h.
Referenced by checkEdge(), and initValidator().
The documentation for this class was generated from the following files:
FeatureGeomFillSurface.h
FeatureGeomFillSurface.cpp