FreeCAD: TechDrawGui::VectorEditWidget Class Reference
TechDrawGui::VectorEditWidget Class Reference
#include <VectorEditWidget.h>
Public Slots
void setValue (Base::Vector3d newValue)
void setValueNoNotify (Base::Vector3d newValue)
Signals
void valueChanged (Base::Vector3d newValue)
Public Member Functions
VectorEditWidget (QWidget *parent=0)
~VectorEditWidget () override=default
QSize minimumSizeHint () const override
bool eventFilter (QObject *target, QEvent *event) override
void setLabel (std::string newLabel)
void setLabel (QString newLabel)
Base::Vector3d value () const
Protected Slots
void slotExpandButtonToggled (bool checked)
void slotXValueChanged (double newValue)
void slotYValueChanged (double newValue)
void slotZValueChanged (double newValue)
void updateDisplay ()
Protected Member Functions
void buildWidget ()
Detailed Description
Definition at line 48 of file VectorEditWidget.h.
Constructor & Destructor Documentation
VectorEditWidget()
VectorEditWidget::VectorEditWidget (QWidget * parent = 0)
Definition at line 57 of file VectorEditWidget.cpp.
References buildWidget(), draftgeoutils.intersections::connect(), slotExpandButtonToggled(), slotXValueChanged(), slotYValueChanged(), and slotZValueChanged().
~VectorEditWidget()
TechDrawGui::VectorEditWidget::~VectorEditWidget () override default
Member Function Documentation
buildWidget()
void VectorEditWidget::buildWidget () protected
Definition at line 189 of file VectorEditWidget.cpp.
References Base::UnitsApi::getDecimals(), and KDL::max().
Referenced by VectorEditWidget().
eventFilter()
bool VectorEditWidget::eventFilter (QObject * target, QEvent * event) override
Definition at line 78 of file VectorEditWidget.cpp.
minimumSizeHint()
QSize VectorEditWidget::minimumSizeHint () const override
Definition at line 184 of file VectorEditWidget.cpp.
setLabel() [1/2]
void VectorEditWidget::setLabel (QString newLabel)
Definition at line 102 of file VectorEditWidget.cpp.
setLabel() [2/2]
void VectorEditWidget::setLabel (std::string newLabel)
Definition at line 96 of file VectorEditWidget.cpp.
Referenced by TechDrawGui::TaskSectionView::setUiCommon(), and TechDrawGui::TaskComplexSection::setUiCommon().
setValue
void VectorEditWidget::setValue (Base::Vector3d newValue) slot
Definition at line 107 of file VectorEditWidget.cpp.
References updateDisplay(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by TechDrawGui::TaskComplexSection::setUiEdit(), and TechDrawGui::TaskComplexSection::setUiPrimary().
setValueNoNotify
void VectorEditWidget::setValueNoNotify (Base::Vector3d newValue) slot
Definition at line 117 of file VectorEditWidget.cpp.
References updateDisplay(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by TechDrawGui::TaskSectionView::onDownClicked(), TechDrawGui::TaskComplexSection::onDownClicked(), TechDrawGui::TaskSectionView::onLeftClicked(), TechDrawGui::TaskComplexSection::onLeftClicked(), TechDrawGui::TaskSectionView::onRightClicked(), TechDrawGui::TaskComplexSection::onRightClicked(), TechDrawGui::TaskSectionView::onUpClicked(), TechDrawGui::TaskComplexSection::onUpClicked(), TechDrawGui::TaskSectionView::setUiEdit(), TechDrawGui::TaskComplexSection::setUiEdit(), TechDrawGui::TaskSectionView::setUiPrimary(), TechDrawGui::TaskComplexSection::setUiPrimary(), TechDrawGui::TaskSectionView::slotChangeAngle(), and TechDrawGui::TaskComplexSection::slotChangeAngle().
slotExpandButtonToggled
void VectorEditWidget::slotExpandButtonToggled (bool checked) protected slot
Definition at line 129 of file VectorEditWidget.cpp.
Referenced by VectorEditWidget().
slotXValueChanged
void VectorEditWidget::slotXValueChanged (double newValue) protected slot
Definition at line 146 of file VectorEditWidget.cpp.
References updateDisplay(), valueChanged(), and Base::Vector3< float_type >::x.
Referenced by VectorEditWidget().
slotYValueChanged
void VectorEditWidget::slotYValueChanged (double newValue) protected slot
Definition at line 156 of file VectorEditWidget.cpp.
References updateDisplay(), valueChanged(), and Base::Vector3< float_type >::y.
Referenced by VectorEditWidget().
slotZValueChanged
void VectorEditWidget::slotZValueChanged (double newValue) protected slot
Definition at line 166 of file VectorEditWidget.cpp.
References updateDisplay(), valueChanged(), and Base::Vector3< float_type >::z.
Referenced by VectorEditWidget().
updateDisplay
void VectorEditWidget::updateDisplay () protected slot
Definition at line 177 of file VectorEditWidget.cpp.
Referenced by setValue(), setValueNoNotify(), slotXValueChanged(), slotYValueChanged(), and slotZValueChanged().
value()
Base::Vector3d TechDrawGui::VectorEditWidget::value () const inline
Definition at line 61 of file VectorEditWidget.h.
Referenced by TechDrawGui::TaskComplexSection::apply(), TechDrawGui::TaskSectionView::createSectionView(), and TechDrawGui::TaskSectionView::updateSectionView().
valueChanged
void TechDrawGui::VectorEditWidget::valueChanged (Base::Vector3d newValue) signal
Referenced by TechDrawGui::TaskSectionView::setUiCommon(), TechDrawGui::TaskComplexSection::setUiCommon(), slotXValueChanged(), slotYValueChanged(), and slotZValueChanged().
The documentation for this class was generated from the following files:
VectorEditWidget.h
VectorEditWidget.cpp