FreeCAD: ifc4.ifctriangulatedfaceset Class Reference
ifc4.ifctriangulatedfaceset Class Reference
Public Member Functions
def __init__ (self, inherited0__coordinates, inherited1__normals, inherited2__closed, coordindex, normalindex)
def coordindex ()
def normalindex ()
def numberoftriangles ()
Public Member Functions inherited from ifc4.ifctessellatedfaceset
def __init__ (self, coordinates, normals, closed)
def coordinates ()
def normals ()
def closed ()
def hascolours ()
def hastextures ()
Public Member Functions inherited from ifc4.ifctessellateditem
def __init__ (self)
Public Member Functions inherited from ifc4.ifcrepresentationitem
def layerassignment ()
def styledbyitem ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
coordindex
normalindex
Public Attributes inherited from ifc4.ifctessellatedfaceset
coordinates
normals
closed
Detailed Description
Entity ifctriangulatedfaceset definition.
:param coordindex
:type coordindex:LIST(1,None,LIST(3,3,'INTEGER', scope = schema_scope))
:param normalindex
:type normalindex:LIST(1,None,LIST(3,3,'INTEGER', scope = schema_scope))
:param numberoftriangles
:type numberoftriangles:INTEGER
Definition at line 34042 of file ifc4.py.
Constructor & Destructor Documentation
__init__()
def ifc4.ifctriangulatedfaceset.__init__ (self, inherited0__coordinates, inherited1__normals, inherited2__closed, coordindex, normalindex)
Definition at line 34054 of file ifc4.py.
Member Function Documentation
coordindex()
def ifc4.ifctriangulatedfaceset.coordindex ()
Definition at line 34060 of file ifc4.py.
References ifc4.ifctriangulatedfaceset._coordindex, SCL.TypeChecker.check_type(), and ifc4.ifctriangulatedfaceset.coordindex.
normalindex()
def ifc4.ifctriangulatedfaceset.normalindex ()
Definition at line 34074 of file ifc4.py.
References ifc4.ifctriangulatedfaceset._normalindex, SCL.TypeChecker.check_type(), and ifc4.ifctriangulatedfaceset.normalindex.
numberoftriangles()
def ifc4.ifctriangulatedfaceset.numberoftriangles ()
Definition at line 34088 of file ifc4.py.
References ifc4.ifctriangulatedfaceset.coordindex, and SCL.Builtin.SIZEOF().
Member Data Documentation
coordindex
ifc4.ifctriangulatedfaceset.coordindex
Definition at line 34056 of file ifc4.py.
Referenced by ifc4.ifctriangulatedfaceset.coordindex(), and ifc4.ifctriangulatedfaceset.numberoftriangles().
normalindex
ifc4.ifctriangulatedfaceset.normalindex
Definition at line 34057 of file ifc4.py.
Referenced by ifc4.ifctriangulatedfaceset.normalindex().
The documentation for this class was generated from the following file:
ifc4.py