FreeCAD: TechDrawGui::DirectionEditDialog Class Reference
TechDrawGui::DirectionEditDialog Class Reference
#include <TaskProjGroup.h>
Public Member Functions
DirectionEditDialog (QWidget *parent=nullptr)
void setDirection (const Base::Vector3d &pos)
Base::Vector3d getDirection () const
void setAngle (double val)
double getAngle () const
Protected Member Functions
void showEvent (QShowEvent *event) override
Detailed Description
Definition at line 181 of file TaskProjGroup.h.
Constructor & Destructor Documentation
DirectionEditDialog()
DirectionEditDialog::DirectionEditDialog (QWidget * parent = nullptr) explicit
Definition at line 906 of file TaskProjGroup.cpp.
Member Function Documentation
getAngle()
double DirectionEditDialog::getAngle () const
Definition at line 925 of file TaskProjGroup.cpp.
References Base::Quantity::getValue(), and Gui::QuantitySpinBox::value.
getDirection()
Base::Vector3d DirectionEditDialog::getDirection () const
Definition at line 917 of file TaskProjGroup.cpp.
References Base::Quantity::getValue(), and Gui::QuantitySpinBox::value.
setAngle()
void DirectionEditDialog::setAngle (double val)
Definition at line 921 of file TaskProjGroup.cpp.
References Gui::QuantitySpinBox::setValue(), and toolbit-attributes::val.
setDirection()
void DirectionEditDialog::setDirection (const Base::Vector3d & pos)
Definition at line 911 of file TaskProjGroup.cpp.
References RobotExample::pos, and Gui::QuantitySpinBox::setValue().
showEvent()
void DirectionEditDialog::showEvent (QShowEvent * event) override protected
Definition at line 929 of file TaskProjGroup.cpp.
References Path.Post.scripts.opensbp_post::move(), RobotExample::pos, MovieTool::x, and MovieTool::y.
The documentation for this class was generated from the following files:
TaskProjGroup.h
TaskProjGroup.cpp