FreeCAD: PartGui::ConePrimitive Class Reference
PartGui::ConePrimitive Class Reference
#include <DlgPrimitives.h>
Public Member Functions
ConePrimitive (std::shared_ptr< Ui_DlgPrimitives > ui, Part::Cone *feature=nullptr)
const char * getDefaultName () const override
QString create (const QString &objectName, const QString &placement) const override
QString change (const QString &objectName, const QString &placement) const override
void changeValue (QObject *) override
Public Member Functions inherited from PartGui::AbstractPrimitive
AbstractPrimitive (Part::Primitive *feature=nullptr)
~AbstractPrimitive () override=default
bool hasValidPrimitive () const
Additional Inherited Members
Protected Member Functions inherited from PartGui::AbstractPrimitive
void connectSignalMapper (QSignalMapper *mapper)
Protected Attributes inherited from PartGui::AbstractPrimitive
App::DocumentObjectWeakPtrT featurePtr
Detailed Description
Definition at line 154 of file DlgPrimitives.h.
Constructor & Destructor Documentation
ConePrimitive()
ConePrimitive::ConePrimitive (std::shared_ptr< Ui_DlgPrimitives > ui, Part::Cone * feature = nullptr)
Definition at line 491 of file DlgPrimitives.cpp.
References Part::Cone::Angle, PartGui::connectMapSignalMapper(), PartGui::AbstractPrimitive::connectSignalMapper(), App::PropertyQuantity::getQuantityValue(), Part::Cone::Height, Part::Cone::Radius1, Part::Cone::Radius2, and Gui::QuantitySpinBox::valueChanged().
Member Function Documentation
change()
QString ConePrimitive::change (const QString & objectName, const QString & placement) const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 543 of file DlgPrimitives.cpp.
References PartGui::safeQuantityQString().
changeValue()
void ConePrimitive::changeValue (QObject * widget) override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 559 of file DlgPrimitives.cpp.
References Part::Cone::Angle, App::DocumentObjectWeakPtrT::expired(), PartGui::AbstractPrimitive::featurePtr, App::DocumentObjectWeakPtrT::get(), Part::Cone::Height, Part::Cone::Radius1, Part::Cone::Radius2, App::DocumentObject::recomputeFeature(), and App::PropertyQuantity::setValue().
create()
QString ConePrimitive::create (const QString & objectName, const QString & placement) const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 524 of file DlgPrimitives.cpp.
References PartGui::safeQuantityQString().
getDefaultName()
const char * ConePrimitive::getDefaultName () const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 519 of file DlgPrimitives.cpp.
The documentation for this class was generated from the following files:
DlgPrimitives.h
DlgPrimitives.cpp