FreeCAD: draftobjects.bezcurve.BezCurve Class Reference
draftobjects.bezcurve.BezCurve Class Reference
DRAFT » draftobjects
Public Member Functions
def __init__ (self, obj)
def onDocumentRestored (self, obj)
def execute (self, fp)
def resetcontinuity (self, fp)
def onChanged (self, fp, prop)
def createGeometry (self, fp)
def symmetricpoles (cls, knot, p1, p2)
def tangentpoles (cls, knot, p1, p2, allowsameside=False)
Public Member Functions inherited from draftobjects.base.DraftObject
def __init__ (self, obj, tp="Unknown")
def dumps (self)
def loads (self, state)
def props_changed_store (self, prop)
def props_changed_clear (self)
def props_changed_placement_only (self, obj=None)
Static Public Member Functions
def modifysymmetricpole (knot, p1)
def modifytangentpole (knot, p1, oldp2)
Additional Inherited Members
Public Attributes inherited from draftobjects.base.DraftObject
Type
props_changed
Detailed Description
The BezCurve object
Definition at line 38 of file bezcurve.py.
Constructor & Destructor Documentation
__init__()
def draftobjects.bezcurve.BezCurve.__init__ (self, obj)
Definition at line 41 of file bezcurve.py.
References Arch.QT_TRANSLATE_NOOP.
Member Function Documentation
createGeometry()
def draftobjects.bezcurve.BezCurve.createGeometry (self, fp)
Definition at line 139 of file bezcurve.py.
References draftobjects.bezcurve.BezCurve._segpoleslst().
Referenced by draftobjects.bezcurve.BezCurve.execute(), and draftobjects.bezcurve.BezCurve.onChanged().
execute()
def draftobjects.bezcurve.BezCurve.execute (self, obj)
Run this method when the object is created or recomputed.
Override this method to produce effects when the object
is newly created, and whenever the document is recomputed.
By default it does nothing.
Parameters
----------
obj : the scripted object.
    This commonly may be of types `Part::Part2DObjectPython`,
    `Part::FeaturePython`, or `App::FeaturePython`.
Reimplemented from draftobjects.base.DraftObject.
Definition at line 85 of file bezcurve.py.
References draftobjects.bezcurve.BezCurve.createGeometry(), draftobjects.base.DraftObject.props_changed_clear(), and draftobjects.base.DraftObject.props_changed_placement_only().
Referenced by src.Mod.PartDesign.Scripts.Spring.MySpring.onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped.onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder.onChanged(), MeasureCOM.MeasureCOM.onChanged(), and FeaturePython.DistanceBolt.onChanged().
modifysymmetricpole()
def draftobjects.bezcurve.BezCurve.modifysymmetricpole (knot, p1) static
calculate the coordinates of the opposite pole
of a symmetric knot
Definition at line 195 of file bezcurve.py.
modifytangentpole()
def draftobjects.bezcurve.BezCurve.modifytangentpole (knot, p1, oldp2) static
calculate the coordinates of the opposite pole
of a tangent knot
Definition at line 201 of file bezcurve.py.
onChanged()
def draftobjects.bezcurve.BezCurve.onChanged (self, obj, prop)
Run this method when a property is changed.
Override this method to handle the behavior
of the object depending on changes that occur to its properties.
By default it does nothing.
Parameters
----------
obj : the scripted object.
    This commonly may be of types `Part::Part2DObjectPython`,
    `Part::FeaturePython`, or `App::FeaturePython`.
prop : str
    Name of the property that was modified.
Reimplemented from draftobjects.base.DraftObject.
Definition at line 113 of file bezcurve.py.
References draftobjects.bezcurve.BezCurve._segpoleslst(), draftobjects.bezcurve.BezCurve.createGeometry(), draftobjects.base.DraftObject.props_changed_store(), and draftobjects.bezcurve.BezCurve.resetcontinuity().
Referenced by draftviewproviders.view_base.ViewProviderDraft.attach(), draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy.updateData(), draftviewproviders.view_layer.ViewProviderLayer.updateData(), draftviewproviders.view_label.ViewProviderLabel.updateData(), and draftviewproviders.view_dimension.ViewProviderLinearDimension.updateData().
onDocumentRestored()
def draftobjects.bezcurve.BezCurve.onDocumentRestored (self, obj)
Reimplemented from draftobjects.base.DraftObject.
Definition at line 79 of file bezcurve.py.
resetcontinuity()
def draftobjects.bezcurve.BezCurve.resetcontinuity (self, fp)
Definition at line 107 of file bezcurve.py.
References draftobjects.bezcurve.BezCurve._segpoleslst().
Referenced by draftobjects.bezcurve.BezCurve.onChanged().
symmetricpoles()
def draftobjects.bezcurve.BezCurve.symmetricpoles (cls, knot, p1, p2)
Make two poles symmetric respective to the knot.
Definition at line 170 of file bezcurve.py.
Referenced by draftobjects.bezcurve.BezCurve.tangentpoles().
tangentpoles()
def draftobjects.bezcurve.BezCurve.tangentpoles (cls, knot, p1, p2, allowsameside = False)
Make two poles have the same tangent at knot.
Definition at line 179 of file bezcurve.py.
References draftobjects.bezcurve.BezCurve.symmetricpoles().
The documentation for this class was generated from the following file:
bezcurve.py