FreeCAD: StrXUTF8 Class Reference
StrXUTF8 Class Reference
#include <XMLTools.h>
Public Member Functions
StrXUTF8 (const XMLCh *const toTranscode)
const char * c_str () const
Getter method.
Public Attributes
std::string str
string which holds the UTF-8 form
Detailed Description
Definition at line 113 of file XMLTools.h.
Constructor & Destructor Documentation
StrXUTF8()
StrXUTF8::StrXUTF8 (const XMLCh *const toTranscode) inline explicit
Definition at line 130 of file XMLTools.h.
References str, and XMLTools::toStdString().
Member Function Documentation
c_str()
const char * StrXUTF8::c_str () const inline
Getter method.
Definition at line 138 of file XMLTools.h.
References str.
Referenced by ParameterGrp::GetASCII(), ParameterGrp::GetASCIIMap(), ParameterGrp::GetASCIIs(), operator<<(), ParameterGrp::SetASCII(), and Base::XMLReader::startElement().
Member Data Documentation
str
std::string StrXUTF8::str
string which holds the UTF-8 form
Definition at line 121 of file XMLTools.h.
Referenced by c_str(), App::Meta::Contact::Contact(), App::Meta::Dependency::Dependency(), App::Meta::GenericMetadata::GenericMetadata(), App::Meta::License::License(), StrXUTF8(), and App::Meta::Url::Url().
The documentation for this class was generated from the following file:
XMLTools.h