FreeCAD: AppTestGui.cpp File Reference
AppTestGui.cpp File Reference
#include "PreCompiled.h"
#include <Base/Console.h>
#include <Base/ConsoleObserver.h>
#include <Base/Interpreter.h>
#include <Gui/Language/Translator.h>
#include "UnitTestImp.h"
#include "UnitTestPy.h"
Classes
class ILoggerBlockerTest
class TestGui::Module
Namespaces
TestGui
Functions
PyObject * TestGui::initModule ()
void loadTestResource ()
PyMOD_INIT_FUNC (QtUnitGui)
Function Documentation
loadTestResource()
void loadTestResource ()
Definition at line 235 of file AppTestGui.cpp.
References Gui::Translator::instance(), Gui::Translator::refresh(), and src.Mod.Test.TestApp::Test().
Referenced by PyMOD_INIT_FUNC().
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (QtUnitGui)
Definition at line 244 of file AppTestGui.cpp.
References Base::Console(), TestGui::initModule(), loadTestResource(), Base::ConsoleSingleton::Log(), mod, and PyMOD_Return.