FreeCAD: Mesh::MeshTexture Class Reference
Mesh::MeshTexture Class Reference
#include <MeshTexture.h>
Public Member Functions
MeshTexture (const Mesh::MeshObject &mesh, const MeshCore::Material &material)
void apply (const Mesh::MeshObject &mesh, const App::Color &defaultColor, MeshCore::Material &material)
void apply (const Mesh::MeshObject &mesh, const App::Color &defaultColor, float max_dist, MeshCore::Material &material)
void apply (const Mesh::MeshObject &mesh, MeshCore::Material &material)
void apply (const Mesh::MeshObject &mesh, float max_dist, MeshCore::Material &material)
Detailed Description
The MeshTexture class. This algorithm is useful to update the material after a mesh has been modified by removing points or facets. If the coordinates of points have changed or if new points have been added then a predefined color will be set.
Author
Werner Mayer
Definition at line 63 of file MeshTexture.h.
Constructor & Destructor Documentation
MeshTexture()
MeshTexture::MeshTexture (const Mesh::MeshObject & mesh, const MeshCore::Material & material)
A mesh with material. The number of points or facets must match with the number of colors.
Definition at line 30 of file MeshTexture.cpp.
References Mesh2Shape::mesh.
Member Function Documentation
apply() [1/4]
void MeshTexture::apply (const Mesh::MeshObject & mesh, const App::Color & defaultColor, float max_dist, MeshCore::Material & material)
Find common points or facets of this to the original mesh. For points or facets that don't match defaultColor will be used instead, otherwise the color of the original material is used.
Definition at line 56 of file MeshTexture.cpp.
References apply(), and Mesh2Shape::mesh.
apply() [2/4]
void MeshTexture::apply (const Mesh::MeshObject & mesh, const App::Color & defaultColor, MeshCore::Material & material)
Find common points or facets of this to the original mesh. For points or facets that don't match defaultColor will be used instead, otherwise the color of the original material is used.
Definition at line 49 of file MeshTexture.cpp.
References Mesh2Shape::mesh.
Referenced by apply().
apply() [3/4]
void MeshTexture::apply (const Mesh::MeshObject & mesh, float max_dist, MeshCore::Material & material)
Find common points or facets of this to the original mesh and use the color of the original material. If for a point of mesh no matching point of the original mesh can be found the texture mapping will fail.
Definition at line 70 of file MeshTexture.cpp.
References apply(), and Mesh2Shape::mesh.
apply() [4/4]
void MeshTexture::apply (const Mesh::MeshObject & mesh, MeshCore::Material & material)
Find common points or facets of this to the original mesh and use the color of the original material. If for a point of mesh no matching point of the original mesh can be found the texture mapping will fail.
Definition at line 64 of file MeshTexture.cpp.
References apply(), and Mesh2Shape::mesh.
The documentation for this class was generated from the following files:
MeshTexture.h
MeshTexture.cpp