FreeCAD: Gui::ToolTip Class Reference
Gui::ToolTip Class Reference
#include <Widgets.h>
Static Public Member Functions
static void showText (const QPoint &pos, const QString &text, QWidget *w=nullptr)
static void hideText ()
Protected Member Functions
ToolTip ()
~ToolTip () override
void timerEvent (QTimerEvent *e) override
bool eventFilter (QObject *o, QEvent *e) override
void installEventFilter ()
void removeEventFilter ()
Static Protected Member Functions
static ToolTip * instance ()
Detailed Description
Qt's tooltip does not work as expected with some classes, e.g. when showing it in the 3d view it immediately receives a timer event to destroy itself. This class is thought to circumvent this behaviour by filtering the internal timer events.
Author
Werner Mayer
Definition at line 448 of file Widgets.h.
Constructor & Destructor Documentation
ToolTip()
ToolTip::ToolTip () protected
Definition at line 1130 of file Widgets.cpp.
Referenced by instance().
~ToolTip()
ToolTip::~ToolTip () override protected default
Member Function Documentation
eventFilter()
bool ToolTip::eventFilter (QObject * o, QEvent * e) override protected
Definition at line 1186 of file Widgets.cpp.
References SCL.SimpleDataTypes::e, hideText(), and src.Mod.Test.testPathArray::o.
hideText()
void ToolTip::hideText () static
Definition at line 1170 of file Widgets.cpp.
References instance().
Referenced by eventFilter(), Gui::OverlayProxyWidget::hitTest(), and showText().
installEventFilter()
void ToolTip::installEventFilter () protected
Definition at line 1136 of file Widgets.cpp.
Referenced by showText().
instance()
ToolTip * ToolTip::instance () static protected
Definition at line 1123 of file Widgets.cpp.
References ToolTip().
Referenced by hideText(), and showText().
removeEventFilter()
void ToolTip::removeEventFilter () protected
Definition at line 1144 of file Widgets.cpp.
showText()
void ToolTip::showText (const QPoint & pos, const QString & text, QWidget * w = nullptr) static
Definition at line 1152 of file Widgets.cpp.
References hideText(), installEventFilter(), and instance().
Referenced by MeshGui::ViewProviderMeshCurvature::curvatureInfoCallback(), Gui::OverlayProxyWidget::hitTest(), and InspectionGui::ViewProviderInspection::inspectCallback().
timerEvent()
void ToolTip::timerEvent (QTimerEvent * e) override protected
Definition at line 1177 of file Widgets.cpp.
References SCL.SimpleDataTypes::e.
The documentation for this class was generated from the following files:
Widgets.h
Widgets.cpp