FreeCAD: Gui::HistoryList Class Reference
Gui::HistoryList Class Reference
Public Member Functions
const QStringList & asStringList () const
int maximumSize () const
void setMaximumSize (int num)
void clear ()
void append (const QString &value)
Detailed Description
Definition at line 598 of file PrefWidgets.cpp.
Member Function Documentation
append()
void Gui::HistoryList::append (const QString & value) inline
Definition at line 616 of file PrefWidgets.cpp.
References DraftVecUtils::find().
Referenced by Gui::PrefQuantitySpinBoxPrivate::restoreHistory().
asStringList()
const QStringList& Gui::HistoryList::asStringList () const inline
Definition at line 602 of file PrefWidgets.cpp.
Referenced by Gui::PrefQuantitySpinBoxPrivate::saveHistory().
clear()
void Gui::HistoryList::clear () inline
Definition at line 613 of file PrefWidgets.cpp.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), and src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__().
maximumSize()
int Gui::HistoryList::maximumSize () const inline
Definition at line 605 of file PrefWidgets.cpp.
setMaximumSize()
void Gui::HistoryList::setMaximumSize (int num) inline
Definition at line 608 of file PrefWidgets.cpp.
The documentation for this class was generated from the following file:
PrefWidgets.cpp