FreeCAD: AppMesh.cpp File Reference
AppMesh.cpp File Reference
#include "PreCompiled.h"
#include <App/Application.h>
#include <App/MeasureManager.h>
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include "EdgePy.h"
#include "Exporter.h"
#include "FacetPy.h"
#include "FeatureMeshCurvature.h"
#include "FeatureMeshDefects.h"
#include "FeatureMeshExport.h"
#include "FeatureMeshImport.h"
#include "FeatureMeshSegmentByMesh.h"
#include "FeatureMeshSetOperations.h"
#include "FeatureMeshSolid.h"
#include "FeatureMeshTransform.h"
#include "FeatureMeshTransformDemolding.h"
#include "Mesh.h"
#include "MeshFeaturePy.h"
#include "MeshPointPy.h"
#include "MeshPy.h"
Namespaces
Mesh
The namespace of the Mesh Application layer library.
Functions
PyObject * Mesh::initModule ()
PyMOD_INIT_FUNC (Mesh)
Function Documentation
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (Mesh)
Definition at line 54 of file AppMesh.cpp.
References App::MeasureManager::addMeasureHandler(), Mesh::Extension3MFFactory::addProducer(), Base::InterpreterSingleton::addType(), Base::Console(), App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetGroup(), App::Application::GetParameterGroupByPath(), SIM::Coin3D::Quarter::Quarter::init(), Base::Persistence::init(), Base::BaseClass::init(), Mesh::initModule(), Base::Interpreter(), App::INVALID, Base::ConsoleSingleton::Log(), PyMOD_Return, and MeshCore::MeshOutput::SetAsymptoteSize().