FreeCAD: SketcherGui::ElementView Class Reference
SketcherGui::ElementView Class Reference
#include <TaskSketcherElements.h>
Signals
void onItemHovered (QListWidgetItem *)
Public Member Functions
ElementView (QWidget *parent=nullptr)
~ElementView () override
ElementItem * itemFromIndex (const QModelIndex &index)
Protected Slots
void doPointCoincidence ()
void doPointOnObjectConstraint ()
void doVerticalDistance ()
void doHorizontalDistance ()
void doParallelConstraint ()
void doPerpendicularConstraint ()
void doTangentConstraint ()
void doEqualConstraint ()
void doSymmetricConstraint ()
void doBlockConstraint ()
void doLockConstraint ()
void doHorizontalConstraint ()
void doVerticalConstraint ()
void doLengthConstraint ()
void doRadiusConstraint ()
void doDiameterConstraint ()
void doRadiamConstraint ()
void doAngleConstraint ()
void doToggleConstruction ()
void doSelectConstraints ()
void doSelectOrigin ()
void doSelectHAxis ()
void doSelectVAxis ()
void deleteSelectedItems ()
void onIndexHovered (QModelIndex index)
void onIndexChecked (QModelIndex, Qt::CheckState state)
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *event) override
Detailed Description
Definition at line 60 of file TaskSketcherElements.h.
Constructor & Destructor Documentation
ElementView()
ElementView::ElementView (QWidget * parent = nullptr) explicit
Definition at line 555 of file TaskSketcherElements.cpp.
References draftgeoutils.intersections::connect(), SketcherGui::ElementItemDelegate::itemChecked(), SketcherGui::ElementItemDelegate::itemHovered(), onIndexChecked(), and onIndexHovered().
~ElementView()
ElementView::~ElementView () override
Definition at line 568 of file TaskSketcherElements.cpp.
Member Function Documentation
contextMenuEvent()
void ElementView::contextMenuEvent (QContextMenuEvent * event) override protected
Definition at line 658 of file TaskSketcherElements.cpp.
References Path.Post.scripts.dynapath_4060_post::action, CONTEXT_ITEM, deleteSelectedItems(), doAngleConstraint(), doBlockConstraint(), doDiameterConstraint(), doEqualConstraint(), doHorizontalConstraint(), doHorizontalDistance(), doLengthConstraint(), doLockConstraint(), doParallelConstraint(), doPerpendicularConstraint(), doPointCoincidence(), doPointOnObjectConstraint(), doRadiamConstraint(), doRadiusConstraint(), doSelectConstraints(), doSelectHAxis(), doSelectOrigin(), doSelectVAxis(), doSymmetricConstraint(), doTangentConstraint(), doToggleConstruction(), doVerticalConstraint(), doVerticalDistance(), src.Mod.Test.testPathArray::items, and NavigationIndicatorGui::menu.
deleteSelectedItems
void ElementView::deleteSelectedItems () protected slot
Definition at line 836 of file TaskSketcherElements.cpp.
References toolbit-attributes::doc, App::Application::getActiveDocument(), App::GetApplication(), Gui::SelectionSingleton::getSelectionEx(), Gui::Application::getViewProvider(), Gui::Application::Instance, Gui::ViewProvider::onDelete(), and Gui::Selection().
Referenced by contextMenuEvent().
doAngleConstraint
void ElementView::doAngleConstraint () protected slot
Definition at line 826 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doBlockConstraint
void ElementView::doBlockConstraint () protected slot
Definition at line 818 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doDiameterConstraint
void ElementView::doDiameterConstraint () protected slot
Definition at line 825 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doEqualConstraint
void ElementView::doEqualConstraint () protected slot
Definition at line 816 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doHorizontalConstraint
void ElementView::doHorizontalConstraint () protected slot
Definition at line 811 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doHorizontalDistance
void ElementView::doHorizontalDistance () protected slot
Definition at line 820 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doLengthConstraint
void ElementView::doLengthConstraint () protected slot
Definition at line 822 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doLockConstraint
void ElementView::doLockConstraint () protected slot
Definition at line 827 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doParallelConstraint
void ElementView::doParallelConstraint () protected slot
Definition at line 813 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doPerpendicularConstraint
void ElementView::doPerpendicularConstraint () protected slot
Definition at line 814 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doPointCoincidence
void ElementView::doPointCoincidence () protected slot
Definition at line 809 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doPointOnObjectConstraint
void ElementView::doPointOnObjectConstraint () protected slot
Definition at line 810 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doRadiamConstraint
void ElementView::doRadiamConstraint () protected slot
Definition at line 823 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doRadiusConstraint
void ElementView::doRadiusConstraint () protected slot
Definition at line 824 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doSelectConstraints
void ElementView::doSelectConstraints () protected slot
Definition at line 831 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doSelectHAxis
void ElementView::doSelectHAxis () protected slot
Definition at line 833 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doSelectOrigin
void ElementView::doSelectOrigin () protected slot
Definition at line 832 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doSelectVAxis
void ElementView::doSelectVAxis () protected slot
Definition at line 834 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doSymmetricConstraint
void ElementView::doSymmetricConstraint () protected slot
Definition at line 817 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doTangentConstraint
void ElementView::doTangentConstraint () protected slot
Definition at line 815 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doToggleConstruction
void ElementView::doToggleConstruction () protected slot
Definition at line 829 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doVerticalConstraint
void ElementView::doVerticalConstraint () protected slot
Definition at line 812 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
doVerticalDistance
void ElementView::doVerticalDistance () protected slot
Definition at line 821 of file TaskSketcherElements.cpp.
Referenced by contextMenuEvent().
itemFromIndex()
ElementItem * ElementView::itemFromIndex (const QModelIndex & index)
Definition at line 867 of file TaskSketcherElements.cpp.
Referenced by SketcherGui::ElementItemDelegate::getElementItem(), onIndexChecked(), and onIndexHovered().
onIndexChecked
void ElementView::onIndexChecked (QModelIndex index, Qt::CheckState state) protected slot
Definition at line 860 of file TaskSketcherElements.cpp.
References SketcherGui::ElementItem::Default, SketcherGui::ElementItem::Hidden, and itemFromIndex().
Referenced by ElementView().
onIndexHovered
void ElementView::onIndexHovered (QModelIndex index) protected slot
Definition at line 853 of file TaskSketcherElements.cpp.
References itemFromIndex(), and onItemHovered().
Referenced by ElementView().
onItemHovered
void SketcherGui::ElementView::onItemHovered (QListWidgetItem *) signal
Referenced by onIndexHovered().
The documentation for this class was generated from the following files:
TaskSketcherElements.h
TaskSketcherElements.cpp