FreeCAD: App::StringHasher Class Reference
App::StringHasher Class Reference
A bidirectional map of strings and their integer identifier.
#include <StringHasher.h>
Classes
class HashMap
Public Types
enum Option { Option::None = 0, Option::Binary = 1 << 0, Option::Hashable = 1 << 1, Option::NoCopy = 1 << 2 }
Options for string string data.
using Options = Base::Flags< Option >
Public Member Functions
StringHasher ()
~StringHasher () override
StringHasher (const StringHasher &)=delete
StringHasher (StringHasher &&) noexcept=delete
StringHasher & operator= (StringHasher &other)=delete
StringHasher & operator= (StringHasher &&other) noexcept=delete
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
void SaveDocFile (Base::Writer &) const override
void RestoreDocFile (Base::Reader &) override
void setPersistenceFileName (const char *name) const
const std::string & getPersistenceFileName () const
StringIDRef getID (const char *text, int len=-1, bool hashable=false)
StringIDRef getID (const QByteArray &data, Options options=Option::Hashable)
StringIDRef getID (const Data::MappedName &name, const QVector< StringIDRef > &sids)
StringIDRef getID (long id, int index=0) const
StringIDRef getID (const StringID::IndexID &id) const
std::map< long, StringIDRef > getIDMap () const
void clear ()
Clear all string hashes.
size_t size () const
Size of the hash table.
size_t count () const
Return the number of hashes that are used by others.
PyObject * getPyObject () override
void setSaveAll (bool enable)
bool getSaveAll () const
void setThreshold (int threshold)
int getThreshold () const
void clearMarks () const
void compact ()
Compact string storage by eliminating unused strings from the table.
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from Base::Handled
Handled ()
virtual ~Handled ()
void ref () const
void unref () const
int unrefNoDelete () const
int getRefCount () const
Handled & operator= (const Handled &)
Handled (const Handled &)=delete
Handled (Handled &&)=delete
Handled & operator= (Handled &&)=delete
Protected Member Functions
StringID * insert (const StringIDRef &sid)
long lastID () const
void saveStream (std::ostream &stream) const
void restoreStream (std::istream &stream, std::size_t count)
void restoreStreamNew (std::istream &stream, std::size_t count)
Friends
class StringID
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
A bidirectional map of strings and their integer identifier.
Maps an arbitrary text string to a unique integer ID, maintaining a reference-counted shared pointer for each. This permits elimination of unused strings based on their reference count. If a duplicate string is added, no additional copy is made, and a new reference to the original storage is returned (incrementing the reference counter of the instance).
If the string is longer than a given threshold, instead of storing the string, its SHA1 hash is stored (and the original string discarded). This allows an upper threshold on the length of a stored string, while still effectively guaranteeing uniqueness in the table.
Definition at line 633 of file StringHasher.h.
Member Typedef Documentation
Options
using App::StringHasher::Options = Base::Flags<Option>
Definition at line 694 of file StringHasher.h.
Member Enumeration Documentation
Option
enum App::StringHasher::Option strong
Options for string string data.
Enumerator
None
No option is set.
Binary
The input data is binary.
Hashable
Hashing is permitted for this input data. If the data length is longer than the threshold setting of the StringHasher, it will be sha1 hashed before storing, and the original content of the string is discarded.
NoCopy
Do not copy the data: assume it is constant and exists for the lifetime of this hasher. If this option is not set, the data will be copied before storing.
Definition at line 677 of file StringHasher.h.
Constructor & Destructor Documentation
StringHasher() [1/3]
StringHasher::StringHasher ()
Definition at line 174 of file StringHasher.cpp.
~StringHasher()
StringHasher::~StringHasher () override
Definition at line 178 of file StringHasher.cpp.
References clear().
StringHasher() [2/3]
App::StringHasher::StringHasher (const StringHasher &) delete
StringHasher() [3/3]
App::StringHasher::StringHasher (StringHasher &&) delete noexcept
Member Function Documentation
clear()
void StringHasher::clear ()
Clear all string hashes.
Definition at line 763 of file StringHasher.cpp.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__(), App::Document::Restore(), Restore(), and ~StringHasher().
clearMarks()
void StringHasher::clearMarks () const
Clear internal marks
The internal marks on internally stored StringID instances are used to check if the StringID is used.
Definition at line 863 of file StringHasher.cpp.
References App::StringID::Marked.
Referenced by App::Document::addStringHasher().
compact()
void StringHasher::compact ()
Compact string storage by eliminating unused strings from the table.
Definition at line 192 of file StringHasher.cpp.
References Base::Handled::unref(), and App::StringIDRef::value().
Referenced by setSaveAll().
count()
size_t StringHasher::count () const
Return the number of hashes that are used by others.
Definition at line 777 of file StringHasher.cpp.
Referenced by getMemSize(), Restore(), RestoreDocFile(), restoreStream(), restoreStreamNew(), Save(), SaveDocFile(), and src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::set_status_filter().
getID() [1/5]
StringIDRef StringHasher::getID (const char * text, int len = -1, bool hashable = false)
Maps an arbitrary string to an integer
Parameters
text input string.
len length of the string: optional if the string is null-terminated.
hashable whether hashing the string is permitted.
Returns
A shared pointer to the internally-stored StringID.
Maps an arbitrary text string to a unique integer ID, returning a reference-counted shared pointer to the StringID. This permits elimination of unused strings based on their reference count. If a duplicate string is added, no additional copy is made, and a new reference to the original storage is returned (incrementing the reference counter of the instance).
If hashable is true and the string is longer than the threshold setting of this StringHasher, only the SHA1 hash of the string is stored: the original content of the string is discarded. If hashable is false, the string is copied and stored inside a StringID instance.
The purpose of this function is to provide a short form of a stable string identification.
Definition at line 254 of file StringHasher.cpp.
References Hashable, and None.
Referenced by getID(), and restoreStreamNew().
getID() [2/5]
StringIDRef StringHasher::getID (const Data::MappedName & name, const QVector< StringIDRef > & sids)
Map geometry element name to an integer
Definition at line 301 of file StringHasher.cpp.
References Data::MappedName::dataBytes(), App::StringID::fromString(), getID(), Data::IndexedName::getIndex(), Data::IndexedName::getType(), SplineSurface::i, App::StringID::IndexID::id, App::StringID::IndexID::index, App::StringID::Indexed, insert(), App::StringID::isPostfixEncoded(), Data::MappedName::isRaw(), lastID(), Data::MappedName::postfixBytes(), App::StringID::Postfixed, App::StringID::PostfixEncoded, App::StringID::PrefixID, App::StringID::PrefixIDIndex, Base::Flags< Enum >::setFlag(), Data::IndexedName::setIndex(), StringID, and App::StringIDRef::toBytes().
getID() [3/5]
StringIDRef StringHasher::getID (const QByteArray & data, Options options = Option::Hashable)
Map text or binary data to an integer
Parameters
data input data.
options options describing how to store the data.
Returns
A shared pointer to the internally stored StringID.
See also
getID (const char*, int, bool);
Definition at line 262 of file StringHasher.cpp.
References App::StringID::Binary, Binary, Hashable, App::StringID::Hashed, insert(), lastID(), NoCopy, App::StringID::None, Base::Flags< Enum >::setFlag(), StringID, and Base::Flags< Enum >::testFlag().
getID() [4/5]
StringIDRef App::StringHasher::getID (const StringID::IndexID & id) const inline
Obtain the reference counted StringID object from numerical id and index
Parameters
id string ID with index
Returns
Return a shared pointer to the internally stored StringID.
Definition at line 726 of file StringHasher.h.
getID() [5/5]
StringIDRef StringHasher::getID (long id, int index = 0) const
Obtain the reference counted StringID object from numerical id
Parameters
id string ID
index optional index of the string ID
Returns
Return a shared pointer to the internally stored StringID.
This function exists because the stored string may be one way hashed, and the original text is not persistent. The caller use this function to retrieve the reference count ID object after restore
Definition at line 435 of file StringHasher.cpp.
getIDMap()
std::map< long, StringIDRef > StringHasher::getIDMap () const
Definition at line 854 of file StringHasher.cpp.
getMemSize()
unsigned int StringHasher::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
Definition at line 844 of file StringHasher.cpp.
References count(), and size().
Referenced by App::Document::getMemSize().
getPersistenceFileName()
const std::string & StringHasher::getPersistenceFileName () const
Definition at line 457 of file StringHasher.cpp.
getPyObject()
PyObject * StringHasher::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 849 of file StringHasher.cpp.
getSaveAll()
bool StringHasher::getSaveAll () const
Definition at line 229 of file StringHasher.cpp.
getThreshold()
int StringHasher::getThreshold () const
Definition at line 239 of file StringHasher.cpp.
insert()
StringID * StringHasher::insert (const StringIDRef & sid) protected
Definition at line 729 of file StringHasher.cpp.
References Base::Handled::ref(), and App::StringIDRef::value().
Referenced by getID(), Restore(), restoreStream(), and restoreStreamNew().
lastID()
long StringHasher::lastID () const protected
Definition at line 244 of file StringHasher.cpp.
Referenced by getID(), and saveStream().
operator=() [1/2]
StringHasher& App::StringHasher::operator= (StringHasher && other) delete noexcept
operator=() [2/2]
StringHasher& App::StringHasher::operator= (StringHasher & other) delete
Restore()
void StringHasher::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 788 of file StringHasher.cpp.
References clear(), count(), SCL.SimpleDataTypes::e, FC_ERR, DrawingExample::file, App::StringID::Hashed, SplineSurface::i, insert(), TechDrawTools.TaskFillTemplateFields::reader, restoreStream(), restoreStreamNew(), and StringID.
Referenced by App::Document::Restore().
RestoreDocFile()
void StringHasher::RestoreDocFile (Base::Reader &) override virtual
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data. Again you have to apply for the call of this method in the Restore() call:
void PropertyMeshKernel::Restore(Base::XMLReader &reader)
{
  reader.readElement("Mesh");
  std::string file (reader.getAttribute("file") );
  if(file == "")
  {
    // read XML
    MeshCore::MeshDocXML restorer(*_pcMesh);
    restorer.Restore(reader);
  }else{
    // initiate a file read
    reader.addFile(file.c_str(),this);
 }
}
After you issued the reader.addFile() your RestoreDocFile() is called:
void PropertyMeshKernel::RestoreDocFile(Base::Reader &reader)
{
    _pcMesh->Read( reader );
}
See also
Base::Reader,Base::XMLReader
Reimplemented from Base::Persistence.
Definition at line 594 of file StringHasher.cpp.
References count(), FC_WARN, TechDrawTools.TaskFillTemplateFields::reader, restoreStream(), and restoreStreamNew().
restoreStream()
void StringHasher::restoreStream (std::istream & stream, std::size_t count) protected
Definition at line 744 of file StringHasher.cpp.
References count(), SplineSurface::i, insert(), App::StringIDRef::isBinary(), App::StringIDRef::isHashed(), StringID, and Path.Post.scripts.grbl_post::type.
Referenced by Restore(), and RestoreDocFile().
restoreStreamNew()
void StringHasher::restoreStreamNew (std::istream & stream, std::size_t count) protected
Definition at line 613 of file StringHasher.cpp.
References count(), FC_THROWM, getID(), SplineSurface::i, SplineSurface::id, insert(), App::StringID::isBinary(), App::StringID::isHashed(), App::StringID::isIndexed(), App::StringID::isPostfixed(), App::StringID::isPostfixEncoded(), App::StringID::isPrefixID(), App::StringID::isPrefixIDIndex(), test::m, split(), StringID, and femtools.tokrules::tokens.
Referenced by Restore(), and RestoreDocFile().
Save()
void StringHasher::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 462 of file StringHasher.cpp.
References Base::Writer::addFile(), Base::Writer::beginCharStream(), count(), Base::Writer::endCharStream(), Base::Writer::ind(), saveStream(), and Base::Writer::Stream().
Referenced by App::Document::Save().
SaveDocFile()
void StringHasher::SaveDocFile (Base::Writer &) const override virtual
This method is used to save large amounts of data to a binary file. Sometimes it makes no sense to write property data as XML. In case the amount of data is too big or the data type has a more effective way to save itself. In this cases it is possible to write the data in a separate file inside the document archive. In case you want do so you have to re-implement SaveDocFile(). First, you have to inform the framework in Save() that you want do so. Here an example from the Mesh module which can save a (pontetionaly big) triangle mesh:
void PropertyMeshKernel::Save (Base::Writer &writer) const
{
  if (writer.isForceXML())
  {
    writer << writer.ind() << "<Mesh>" << std::endl;
    MeshCore::MeshDocXML saver(*_pcMesh);
    saver.Save(writer);
  }else{
   writer << writer.ind() << "<Mesh file=\"" << writer.addFile("MeshKernel.bms", this) <<
"\"/>" << std::endl;
}
The writer.isForceXML() is an indication to force you to write XML. Regardless of size and effectiveness. The second part informs the Base::writer through writer.addFile("MeshKernel.bms", this) that this object wants to write a file with the given name. The method addFile() returns a unique name that then is written in the XML stream. This allows your RestoreDocFile() method to identify and read the file again. Later your SaveDocFile() method is called as many times as you issued the addFile() call:
 void
PropertyMeshKernel::SaveDocFile (Base::Writer &writer) const
{
    _pcMesh->Write( writer );
}
In this method you can simply stream your content to the file (Base::Writer inheriting from ostream).
Reimplemented from Base::Persistence.
Definition at line 490 of file StringHasher.cpp.
References count(), saveStream(), size(), and Base::Writer::Stream().
saveStream()
void StringHasher::saveStream (std::ostream & stream) const protected
Definition at line 497 of file StringHasher.cpp.
References App::StringID::fromString(), SplineSurface::id, App::StringID::IndexID::id, lastID(), test::m, and App::StringID::Marked.
Referenced by Save(), and SaveDocFile().
setPersistenceFileName()
void StringHasher::setPersistenceFileName (const char * name) const
Definition at line 449 of file StringHasher.cpp.
Referenced by App::Document::Save().
setSaveAll()
void StringHasher::setSaveAll (bool enable)
Enable/disable saving all string ID
If saveAll is true, then compact() does nothing even when called explicitly. Setting saveAll it to false causes compact() to be run immediately.
Definition at line 183 of file StringHasher.cpp.
References compact().
setThreshold()
void StringHasher::setThreshold (int threshold)
Set threshold of string hashing
For hashable strings that are longer than this threshold, the string will be replaced by its sha1 hash.
Definition at line 234 of file StringHasher.cpp.
size()
size_t StringHasher::size () const
Size of the hash table.
Definition at line 772 of file StringHasher.cpp.
Referenced by Path.Post.Utils.GCodeEditorDialog::done(), getMemSize(), and SaveDocFile().
Friends And Related Function Documentation
StringID
friend class StringID friend
Definition at line 770 of file StringHasher.h.
Referenced by getID(), Restore(), restoreStream(), and restoreStreamNew().
The documentation for this class was generated from the following files:
StringHasher.h
StringHasher.cpp