FreeCAD: App::RangeExpression Class Reference
App::RangeExpression Class Reference
#include <ExpressionParser.h>
Public Member Functions
RangeExpression (const App::DocumentObject *_owner=nullptr, const std::string &begin=std::string(), const std::string &end=std::string())
~RangeExpression () override=default
bool isTouched () const override
App::Expression * simplify () const override
Range getRange () const
Public Member Functions inherited from App::Expression
Expression (const App::DocumentObject *_owner)
~Expression () override
Expression * eval () const
std::string toString (bool persistent=false, bool checkPriority=false, int indent=0) const
void toString (std::ostream &os, bool persistent=false, bool checkPriority=false, int indent=0) const
Expression * copy () const
virtual int priority () const
void getIdentifiers (std::map< App::ObjectIdentifier, bool > &) const
std::map< App::ObjectIdentifier, bool > getIdentifiers () const
void getDeps (ExpressionDeps &deps, int option=DepNormal) const
ExpressionDeps getDeps (int option=DepNormal) const
std::map< App::DocumentObject *, bool > getDepObjects (std::vector< std::string > *labels=nullptr) const
void getDepObjects (std::map< App::DocumentObject *, bool > &, std::vector< std::string > *labels=nullptr) const
ExpressionPtr importSubNames (const std::map< std::string, std::string > &nameMap) const
ExpressionPtr updateLabelReference (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const
ExpressionPtr replaceObject (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const
bool adjustLinks (const std::set< App::DocumentObject * > &inList)
void visit (ExpressionVisitor &v)
App::DocumentObject * getOwner () const
virtual void addComponent (Component *component)
bool hasComponent () const
boost::any getValueAsAny () const
Py::Object getPyValue () const
bool isSame (const Expression &other, bool checkComment=true) const
Component (const std::string &n)
Component (Expression *e1, Expression *e2, Expression *e3, bool isRange=false)
Component (const ObjectIdentifier::Component &comp)
Component (const Component &other)
~Component ()
Component & operator= (const Component &)=delete
void visit (ExpressionVisitor &v)
bool isTouched () const
void toString (std::ostream &ss, bool persistent) const
Component * copy () const
Component * eval () const
Py::Object get (const Expression *owner, const Py::Object &pyobj) const
void set (const Expression *owner, Py::Object &pyobj, const Py::Object &value) const
void del (const Expression *owner, Py::Object &pyobj) const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
Expression * _copy () const override
void _toString (std::ostream &ss, bool persistent, int indent) const override
Py::Object _getPyValue () const override
void _getIdentifiers (std::map< App::ObjectIdentifier, bool > &) const override
bool _renameObjectIdentifier (const std::map< ObjectIdentifier, ObjectIdentifier > &, const ObjectIdentifier &, ExpressionVisitor &) override
void _moveCells (const CellAddress &, int, int, ExpressionVisitor &) override
void _offsetCells (int, int, ExpressionVisitor &) override
Protected Member Functions inherited from App::Expression
virtual bool _isIndexable () const
virtual bool _adjustLinks (const std::set< App::DocumentObject * > &, ExpressionVisitor &)
virtual bool _updateElementReference (App::DocumentObject *, bool, ExpressionVisitor &)
virtual bool _relabeledDocument (const std::string &, const std::string &, ExpressionVisitor &)
virtual void _importSubNames (const ObjectIdentifier::SubNameMap &)
virtual void _updateLabelReference (App::DocumentObject *, const std::string &, const char *)
virtual void _collectReplacement (std::map< ObjectIdentifier, ObjectIdentifier > &, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const
virtual void _visit (ExpressionVisitor &)
Protected Attributes
std::string begin
std::string end
Protected Attributes inherited from App::Expression
App::DocumentObject * owner
ComponentList components
Additional Inherited Members
Public Types inherited from App::Expression
enum DepOption { DepNormal, DepHidden, DepAll }
using ComponentList = std::vector< Component * >
Static Public Member Functions inherited from App::Expression
static Expression * parse (const App::DocumentObject *owner, const std::string &buffer)
static Component * createComponent (const std::string &n)
static Component * createComponent (Expression *e1, Expression *e2=nullptr, Expression *e3=nullptr, bool isRange=false)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::Expression
std::string comment
ObjectIdentifier::Component comp
Expression * e1
Expression * e2
Expression * e3
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 585 of file ExpressionParser.h.
Constructor & Destructor Documentation
RangeExpression()
RangeExpression::RangeExpression (const App::DocumentObject * _owner = nullptr, const std::string & begin = std::string(), const std::string & end = std::string()) explicit
Definition at line 3301 of file Expression.cpp.
Referenced by _copy().
~RangeExpression()
App::RangeExpression::~RangeExpression () override default
Member Function Documentation
_copy()
Expression * RangeExpression::_copy () const override protected virtual
Implements App::Expression.
Definition at line 3336 of file Expression.cpp.
References begin, end, App::Expression::owner, and RangeExpression().
_getIdentifiers()
void RangeExpression::_getIdentifiers (std::map< App::ObjectIdentifier, bool > & deps) const override protected virtual
Reimplemented from App::Expression.
Definition at line 3346 of file Expression.cpp.
References getRange(), SplineSurface::i, HiddenReference::isHidden(), and App::Expression::owner.
_getPyValue()
Py::Object RangeExpression::_getPyValue () const override protected virtual
Implements App::Expression.
Definition at line 3320 of file Expression.cpp.
References App::Range::address(), App::ExtensionContainer::getPropertyByName(), getRange(), App::Range::next(), App::Expression::owner, and buildPsets::p.
_moveCells()
void RangeExpression::_moveCells (const CellAddress & address, int rowCount, int colCount, ExpressionVisitor & v) override protected virtual
Reimplemented from App::Expression.
Definition at line 3421 of file Expression.cpp.
References begin, App::CellAddress::col(), end, App::CellAddress::isValid(), App::CellAddress::row(), App::CellAddress::setCol(), App::CellAddress::setRow(), App::stringToAddress(), App::CellAddress::toString(), and TestSpreadsheet::v.
_offsetCells()
void RangeExpression::_offsetCells (int rowOffset, int colOffset, ExpressionVisitor & v) override protected virtual
Reimplemented from App::Expression.
Definition at line 3448 of file Expression.cpp.
References begin, App::CellAddress::col(), end, App::CellAddress::isAbsoluteCol(), App::CellAddress::isAbsoluteRow(), App::CellAddress::isValid(), App::CellAddress::row(), App::CellAddress::setCol(), App::CellAddress::setRow(), App::stringToAddress(), App::CellAddress::toString(), and TestSpreadsheet::v.
_renameObjectIdentifier()
bool RangeExpression::_renameObjectIdentifier (const std::map< ObjectIdentifier, ObjectIdentifier > & paths, const ObjectIdentifier & path, ExpressionVisitor & v) override protected virtual
Reimplemented from App::Expression.
Definition at line 3400 of file Expression.cpp.
References begin, end, App::Expression::owner, and TestSpreadsheet::v.
_toString()
void RangeExpression::_toString (std::ostream & ss, bool persistent, int indent) const override protected virtual
Implements App::Expression.
Definition at line 3331 of file Expression.cpp.
References begin, and end.
getRange()
Range RangeExpression::getRange () const
Definition at line 3362 of file Expression.cpp.
References _EXPR_PY_THROW, _EXPR_RETHROW, begin, src.Mod.PartDesign.Scripts.Gear::c1, SCL.SimpleDataTypes::e, end, EXPR_THROW, App::DocumentObject::getPyObject(), App::Expression::owner, src.Mod.Test.testmakeWireString::String, and App::stringToAddress().
Referenced by _getIdentifiers(), _getPyValue(), App::FunctionExpression::evalAggregate(), and isTouched().
isTouched()
bool RangeExpression::isTouched () const override virtual
Reimplemented from App::Expression.
Definition at line 3306 of file Expression.cpp.
References App::ExtensionContainer::getPropertyByName(), getRange(), SplineSurface::i, App::Property::isTouched(), and App::Expression::owner.
simplify()
Expression * RangeExpression::simplify () const override virtual
Implements App::Expression.
Definition at line 3341 of file Expression.cpp.
References App::Expression::copy().
Member Data Documentation
begin
std::string App::RangeExpression::begin protected
Definition at line 614 of file ExpressionParser.h.
Referenced by _copy(), _moveCells(), _offsetCells(), _renameObjectIdentifier(), _toString(), getRange(), Path.Base.Language.Instruction::isPlunge(), Path.Base.Language.Instruction::positionBegin(), Path.Base.Language.Maneuver::positionBegin(), Path.Base.Language.Instruction::positionEnd(), Path.Base.Language.Instruction::setPositionBegin(), Path.Base.Language.Instruction::xyBegin(), Path.Base.Language.MoveArc::xyCenter(), and Path.Base.Language.Instruction::xyEnd().
end
std::string App::RangeExpression::end protected
Definition at line 615 of file ExpressionParser.h.
Referenced by _copy(), _moveCells(), _offsetCells(), _renameObjectIdentifier(), _toString(), Dice3DS.dom3ds.FileLikeBuffer::advance(), getRange(), Dice3DS.dom3ds.FileLikeBuffer::read_rest(), Dice3DS.dom3ds.FileLikeBuffer::read_to_nul(), Dice3DS.dom3ds.FileLikeBuffer::room_for_chunks(), and Dice3DS.dom3ds.FileLikeBuffer::seek().
The documentation for this class was generated from the following files:
ExpressionParser.h
Expression.cpp