FreeCAD: Gui::SoFCVectorizeSVGActionP Class Reference
Gui::SoFCVectorizeSVGActionP Class Reference
Public Member Functions
SoFCVectorizeSVGActionP (SoFCVectorizeSVGAction *p)
void printCircle (const SbVec3f &v, const SbColor &c, const float radius) const
void printSquare (const SbVec3f &v, const SbColor &c, const float size) const
void printTriangle (const SbVec3f *v, const SbColor *c) const
void printTriangle (const SoVectorizeTriangle *item) const
void printLine (const SoVectorizeLine *item) const
void printPoint (const SoVectorizePoint *item) const
void printText (const SoVectorizeText *item) const
void printImage (const SoVectorizeImage *item) const
Detailed Description
Definition at line 173 of file SoFCVectorizeSVGAction.cpp.
Constructor & Destructor Documentation
SoFCVectorizeSVGActionP()
Gui::SoFCVectorizeSVGActionP::SoFCVectorizeSVGActionP (SoFCVectorizeSVGAction * p) inline
Definition at line 176 of file SoFCVectorizeSVGAction.cpp.
References buildPsets::p.
Member Function Documentation
printCircle()
void SoFCVectorizeSVGActionP::printCircle (const SbVec3f & v, const SbColor & c, const float radius) const
Definition at line 313 of file SoFCVectorizeSVGAction.cpp.
References SCL.SimpleDataTypes::c, and TestSpreadsheet::v.
printImage()
void SoFCVectorizeSVGActionP::printImage (const SoVectorizeImage * item) const
Definition at line 364 of file SoFCVectorizeSVGAction.cpp.
Referenced by Gui::SoFCVectorizeSVGAction::printItem().
printLine()
void SoFCVectorizeSVGActionP::printLine (const SoVectorizeLine * item) const
Definition at line 329 of file SoFCVectorizeSVGAction.cpp.
References SCL.SimpleDataTypes::c, SoVectorizeLine::col, Gui::SoSVGVectorOutput::getFileStream(), Gui::SoFCVectorizeSVGAction::getLineWidth(), Gui::SoFCVectorizeSVGAction::getSVGOutput(), SplineSurface::i, Path.Post.scripts.refactored_centroid_post::str, InitGui::t, TestSpreadsheet::v, and SoVectorizeLine::vidx.
Referenced by Gui::SoFCVectorizeSVGAction::printItem().
printPoint()
void SoFCVectorizeSVGActionP::printPoint (const SoVectorizePoint * item) const
Definition at line 358 of file SoFCVectorizeSVGAction.cpp.
Referenced by Gui::SoFCVectorizeSVGAction::printItem().
printSquare()
void SoFCVectorizeSVGActionP::printSquare (const SbVec3f & v, const SbColor & c, const float size) const
Definition at line 321 of file SoFCVectorizeSVGAction.cpp.
References SCL.SimpleDataTypes::c, and TestSpreadsheet::v.
printText()
void SoFCVectorizeSVGActionP::printText (const SoVectorizeText * item) const
Definition at line 194 of file SoFCVectorizeSVGAction.cpp.
References SoVectorizeText::fontsize, Gui::SoSVGVectorOutput::getFileStream(), Gui::SoFCVectorizeSVGAction::getSVGOutput(), SoVectorizeText::pos, Path.Post.scripts.refactored_centroid_post::str, and SoVectorizeText::string.
Referenced by Gui::SoFCVectorizeSVGAction::printItem().
printTriangle() [1/2]
void SoFCVectorizeSVGActionP::printTriangle (const SbVec3f * v, const SbColor * c) const
Definition at line 293 of file SoFCVectorizeSVGAction.cpp.
References SCL.SimpleDataTypes::c, Gui::SoSVGVectorOutput::getFileStream(), Gui::SoFCVectorizeSVGAction::getLineWidth(), Gui::SoFCVectorizeSVGAction::getSVGOutput(), Path.Post.scripts.refactored_centroid_post::str, and TestSpreadsheet::v.
Referenced by Gui::SoFCVectorizeSVGAction::printItem(), and printTriangle().
printTriangle() [2/2]
void SoFCVectorizeSVGActionP::printTriangle (const SoVectorizeTriangle * item) const
Definition at line 207 of file SoFCVectorizeSVGAction.cpp.
References SCL.SimpleDataTypes::c, SoVectorizeTriangle::col, SplineSurface::i, printTriangle(), InitGui::t, TestSpreadsheet::v, and SoVectorizeTriangle::vidx.
The documentation for this class was generated from the following file:
SoFCVectorizeSVGAction.cpp