FreeCAD: SCL.Part21.Part21Population Class Reference
SCL.Part21.Part21Population Class Reference
Public Member Functions
def __init__ (self, part21_loader)
def create_entity_instances (self)
def create_entity_instance (self, instance_id)
Detailed Description
Definition at line 182 of file Part21.py.
Constructor & Destructor Documentation
__init__()
def SCL.Part21.Part21Population.__init__ (self, part21_loader)
Take a part21_loader a tries to create entities
Definition at line 183 of file Part21.py.
References SCL.Part21.Part21Population._aggr_scope, SCL.Part21.Part21Population._aggregate_scope, SCL.Part21.Part21Population._part21_loader, and SCL.Part21.Part21Population.create_entity_instances().
Member Function Documentation
create_entity_instance()
def SCL.Part21.Part21Population.create_entity_instance (self, instance_id)
Definition at line 198 of file Part21.py.
References SCL.Part21.Part21Population._part21_loader.
Referenced by SCL.Part21.Part21Population.create_entity_instances().
create_entity_instances()
def SCL.Part21.Part21Population.create_entity_instances (self)
Starts entity instances creation
Definition at line 190 of file Part21.py.
References SCL.Part21.Part21Population._part21_loader, and SCL.Part21.Part21Population.create_entity_instance().
Referenced by SCL.Part21.Part21Population.__init__().
The documentation for this class was generated from the following file:
Part21.py