FreeCAD: Gui::PyResource Class Reference
Gui::PyResource Class Reference
#include <WidgetFactory.h>
Public Member Functions
PyResource ()
~PyResource () override
void load (const char *name)
bool connect (const char *sender, const char *signal, PyObject *cb)
Py::Object repr () override
Py::Object value (const Py::Tuple &)
Py::Object setValue (const Py::Tuple &)
Py::Object show (const Py::Tuple &)
Py::Object connect (const Py::Tuple &)
Static Public Member Functions
static void init_type ()
Detailed Description
The PyResource class provides an interface to create widgets or to load .ui files from Python. With
d = Gui.createDialog("test.ui")
you can create a PyResource object containing the widget. If a relative file name is given PyResource looks first in the current working directory and afterwards in the home path where FreeCAD resides.
If the appropriate .ui file cannot be found or creation fails an exception is thrown. In case the widget in the .ui file does not inherit from QDialog it is embedded in a ContainerDialog object. To show the widget you can call
d.Show()
Furthermore it is possible to get or set values from any widgets inside the parent widget or to connect a Python callback function with a widget.
Remarks
The callback function must have exactly one parameter. This parameter points to the dialog you have just created.
# define a callback function with one argument
def TestCall(obj):
     # sets the value from lineedit if "Button_Name" was pressed
     obj.setValue("lineedit", "text", "Show this text here!")
     print "Button clicked"
d = Gui.createDialog("test.ui")
d.connect("Button_Name", "clicked()", TestCall)
d.show()
If the button with the name "Button_Name" is clicked the message "Button clicked" is printed. For example if you have a QLineEdit inside your widget you can set the text with
# sets "Show this text here!" to the text property
d.setValue("lineedit", "text", "Show this text here!")
d.show()
or retrieve the entered text with
f = d.getValue("lineedit", "text")
print f
Author
Werner Mayer
Definition at line 329 of file WidgetFactory.h.
Constructor & Destructor Documentation
PyResource()
PyResource::PyResource ()
Definition at line 401 of file WidgetFactory.cpp.
~PyResource()
PyResource::~PyResource () override
Definition at line 405 of file WidgetFactory.cpp.
Member Function Documentation
connect() [1/2]
bool PyResource::connect (const char * sender, const char * signal, PyObject * cb)
Makes a connection between the sender widget sender and its signal signal of the created resource and Python callback function cb. If the sender widget does not exist or no resource has been loaded this method returns false, otherwise it returns true.
Definition at line 487 of file WidgetFactory.cpp.
References draftgeoutils.intersections::connect(), and src.Mod.AddonManager.addonmanager_pyside_interface::QObject.
Referenced by connect(), and init_type().
connect() [2/2]
Py::Object PyResource::connect (const Py::Tuple & args)
Searches for the sender, the signal and the callback function to connect with in the argument object args. In the case it fails nullptr is returned.
Definition at line 690 of file WidgetFactory.cpp.
References toolbit-attributes::args, and connect().
init_type()
void PyResource::init_type () static
Definition at line 387 of file WidgetFactory.cpp.
References connect(), setValue(), show(), and value().
Referenced by Gui::Application::Application().
load()
void PyResource::load (const char * name)
Loads an .ui file with the name name. If the .ui file cannot be found or the QWidgetFactory cannot create an instance an exception is thrown. If the created resource does not inherit from QDialog an instance of ContainerDialog is created to embed it.
Definition at line 419 of file WidgetFactory.cpp.
References DrawingExample::file, App::Application::getHomePath(), Path.Post.scripts.rml_post::home(), Gui::UiLoader::newInstance(), and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::loadDefaults(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle(), and draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle().
repr()
Py::Object PyResource::repr () override
Definition at line 518 of file WidgetFactory.cpp.
References toolbit-attributes::s, and src.Mod.Test.testmakeWireString::String.
setValue()
Py::Object PyResource::setValue (const Py::Tuple & args)
Searches for a widget, its value name and the new value in the argument object args to set even this new value. In the case it fails nullptr is returned.
Definition at line 602 of file WidgetFactory.cpp.
References toolbit-attributes::args, SplineSurface::i, src.Mod.AddonManager.addonmanager_pyside_interface::QObject, Path.Post.scripts.refactored_centroid_post::str, TestSpreadsheet::v, and toolbit-attributes::val.
Referenced by init_type().
show()
Py::Object PyResource::show (const Py::Tuple &)
If any resource has been loaded this methods shows it as a modal dialog.
Definition at line 665 of file WidgetFactory.cpp.
Referenced by init_type(), src.Mod.Show.mTempoVis.TempoVis::show_all_dependencies(), src.Mod.Show.mTempoVis.TempoVis::show_all_dependent(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
value()
Py::Object PyResource::value (const Py::Tuple & args)
Searches for a widget and its value in the argument object args to returns its value as Python object. In the case it fails nullptr is returned.
Definition at line 531 of file WidgetFactory.cpp.
References toolbit-attributes::args, SplineSurface::i, src.Mod.AddonManager.addonmanager_pyside_interface::QObject, Path.Post.scripts.refactored_centroid_post::str, src.Mod.Test.testmakeWireString::String, and TestSpreadsheet::v.
Referenced by src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), init_type(), and src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue().
The documentation for this class was generated from the following files:
WidgetFactory.h
WidgetFactory.cpp