FreeCAD: MeshCore::MeshGeomFacet Class Reference
MeshCore::MeshGeomFacet Class Reference
#include <Elements.h>
Construction
Base::Vector3f _aclPoints [3]
unsigned char _ucFlag
unsigned long _ulProp
MeshGeomFacet ()
default constructor
MeshGeomFacet (const Base::Vector3f &v1, const Base::Vector3f &v2, const Base::Vector3f &v3)
Constructor with the corner points.
MeshGeomFacet (const MeshGeomFacet &)=default
MeshGeomFacet (MeshGeomFacet &&)=default
~MeshGeomFacet ()=default
Destruction.
MeshGeomFacet & operator= (const MeshGeomFacet &)=default
MeshGeomFacet & operator= (MeshGeomFacet &&)=default
bool IsPointOf (const Base::Vector3f &rclPoint, float fDistance) const
bool IsPointOf (const Base::Vector3f &P) const
bool IsPointOfFace (const Base::Vector3f &rclP, float fDistance) const
bool Weights (const Base::Vector3f &rclP, float &w0, float &w1, float &w2) const
float DistancePlaneToPoint (const Base::Vector3f &rclPoint) const
void ProjectPointToPlane (const Base::Vector3f &rclPoint, Base::Vector3f &rclProj) const
void ProjectFacetToPlane (MeshGeomFacet &rclFacet) const
bool IsDegenerated (float epsilon) const
bool IsDeformed (float fCosOfMinAngle, float fCosOfMaxAngle) const
void Enlarge (float fDist)
void CalcNormal () const
void ArrangeNormal (const Base::Vector3f &rclN)
void AdjustCirculationDirection ()
void NormalInvalid ()
bool IsFlag (MeshFacet::TFlagType tF) const
void SetFlag (MeshFacet::TFlagType tF)
void ResetFlag (MeshFacet::TFlagType tF)
Base::Vector3f GetGravityPoint () const
Base::Vector3f GetNormal () const
void SetNormal (const Base::Vector3f &rclNormal)
Base::BoundBox3f GetBoundBox () const
float Perimeter () const
float Area () const
float MaximumAngle () const
float MinimumAngle () const
bool ContainedByOrIntersectBoundingBox (const Base::BoundBox3f &rcBB) const
bool IntersectBoundingBox (const Base::BoundBox3f &rclBB) const
bool IntersectWithFacet (const MeshGeomFacet &rclFacet) const
int IntersectWithFacet (const MeshGeomFacet &facet, Base::Vector3f &rclPt0, Base::Vector3f &rclPt1) const
float DistanceToLineSegment (const Base::Vector3f &rcP1, const Base::Vector3f &rcP2) const
float DistanceToPoint (const Base::Vector3f &rcPt) const
float DistanceToPoint (const Base::Vector3f &rclPt, Base::Vector3f &rclNt) const
bool IntersectWithLine (const Base::Vector3f &rclPt, const Base::Vector3f &rclDir, Base::Vector3f &rclRes) const
bool Foraminate (const Base::Vector3f &P, const Base::Vector3f &dir, Base::Vector3f &I, float fMaxAngle=Mathf::PI) const
bool IntersectWithPlane (const Base::Vector3f &rclBase, const Base::Vector3f &rclNormal, Base::Vector3f &rclP1, Base::Vector3f &rclP2) const
bool IntersectWithPlane (const Base::Vector3f &rclBase, const Base::Vector3f &rclNormal) const
bool IntersectPlaneWithLine (const Base::Vector3f &rclPt, const Base::Vector3f &rclDir, Base::Vector3f &rclRes) const
float VolumeOfPrism (const MeshGeomFacet &rclF) const
void SubSample (float fStep, std::vector< Base::Vector3f > &rclPoints) const
float CenterOfInscribedCircle (Base::Vector3f &rclCenter) const
float CenterOfCircumCircle (Base::Vector3f &rclCenter) const
unsigned short NearestEdgeToPoint (const Base::Vector3f &rclPt) const
void NearestEdgeToPoint (const Base::Vector3f &rclPt, float &fDistance, unsigned short &side) const
MeshGeomEdge GetEdge (short side) const
bool IsPointOfSphere (const Base::Vector3f &rP) const
bool IsPointOfSphere (const MeshGeomFacet &rFacet) const
float AspectRatio () const
float AspectRatio2 () const
float Roundness () const
void Transform (const Base::Matrix4D &)
bool IsCoplanar (const MeshGeomFacet &facet) const
Detailed Description
The MeshGeomFacet class is geometric counterpart to MeshFacet that holds the geometric data points of a triangle.
Definition at line 456 of file Elements.h.
Constructor & Destructor Documentation
MeshGeomFacet() [1/4]
MeshGeomFacet::MeshGeomFacet ()
default constructor
Definition at line 461 of file Elements.cpp.
Referenced by Weights().
MeshGeomFacet() [2/4]
MeshGeomFacet::MeshGeomFacet (const Base::Vector3f & v1, const Base::Vector3f & v2, const Base::Vector3f & v3)
Constructor with the corner points.
Definition at line 468 of file Elements.cpp.
References _aclPoints, and draftgeoutils.general::v1().
MeshGeomFacet() [3/4]
MeshCore::MeshGeomFacet::MeshGeomFacet (const MeshGeomFacet &) default
MeshGeomFacet() [4/4]
MeshCore::MeshGeomFacet::MeshGeomFacet (MeshGeomFacet &&) default
~MeshGeomFacet()
MeshCore::MeshGeomFacet::~MeshGeomFacet () default
Destruction.
Member Function Documentation
AdjustCirculationDirection()
void MeshCore::MeshGeomFacet::AdjustCirculationDirection () inline
Adjusts the facet's orientation to its normal.
Definition at line 956 of file Elements.h.
Area()
float MeshCore::MeshGeomFacet::Area () const inline
Calculates the area of a facet.
Definition at line 978 of file Elements.h.
Referenced by CenterOfCircumCircle(), CenterOfInscribedCircle(), MeshGui::ViewProviderMesh::createToolMesh(), MeshCore::MeshKernel::GetSurface(), Roundness(), MeshCore::MeshAlgorithm::Surface(), and Weights().
ArrangeNormal()
void MeshCore::MeshGeomFacet::ArrangeNormal (const Base::Vector3f & rclN) inline
Arrange the facet normal so the both vectors have the same orientation.
Definition at line 943 of file Elements.h.
References _aclPoints.
AspectRatio()
float MeshGeomFacet::AspectRatio () const
The aspect ratio is the longest edge length divided by its height.
Definition at line 1562 of file Elements.cpp.
References _aclPoints, NavigationIndicatorGui::a2, src.Mod.PartDesign.Scripts.Gear::l2, Base::Vector3< float_type >::Sqr(), and KDL::sqrt().
AspectRatio2()
float MeshGeomFacet::AspectRatio2 () const
The alternative aspect ration is the ratio of the radius of the circum-circle and twice the radius of the in-circle.
Definition at line 1583 of file Elements.cpp.
References _aclPoints, a, SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::c, and Base::Distance().
CalcNormal()
void MeshCore::MeshGeomFacet::CalcNormal () const inline
Calculates the facet normal for storing internally.
Definition at line 918 of file Elements.h.
Referenced by Mesh::MeshObject::createCube(), Mesh::MeshObject::createMeshFromList(), MeshGui::ViewProviderMesh::createToolMesh(), and MeshCore::MeshKernel::GetFacet().
CenterOfCircumCircle()
float MeshGeomFacet::CenterOfCircumCircle (Base::Vector3f & rclCenter) const
Calculates the center and radius of the circum circle of the facet.
Definition at line 1272 of file Elements.cpp.
References _aclPoints, Area(), KDL::sqrt(), buildPsets::u, TestSpreadsheet::v, src.Mod.PartDesign.fcgear.svggear::w, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by MeshCore::MeshTopoAlgorithm::DelaunayFlip(), and IsPointOfSphere().
CenterOfInscribedCircle()
float MeshGeomFacet::CenterOfInscribedCircle (Base::Vector3f & rclCenter) const
Calculates the center and radius of the inscribed circle of the facet.
Definition at line 1249 of file Elements.cpp.
References _aclPoints, a, Area(), SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::c, Base::Distance(), src.Mod.PartDesign.fcgear.svggear::w, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
ContainedByOrIntersectBoundingBox()
bool MeshCore::MeshGeomFacet::ContainedByOrIntersectBoundingBox (const Base::BoundBox3f & rcBB) const inline
Checks if the facet is inside the bounding box or intersects with it.
Definition at line 983 of file Elements.h.
DistancePlaneToPoint()
float MeshCore::MeshGeomFacet::DistancePlaneToPoint (const Base::Vector3f & rclPoint) const inline
Calculates the distance of a point to the plane defined by the triangle.
Definition at line 912 of file Elements.h.
References Base::Vector3< float_type >::Sqr().
Referenced by IsCoplanar(), and IsPointOf().
DistanceToLineSegment()
float MeshGeomFacet::DistanceToLineSegment (const Base::Vector3f & rcP1, const Base::Vector3f & rcP2) const
Calculates the shortest distance from the line segment defined by rcP1 and rcP2 to this facet.
Definition at line 956 of file Elements.cpp.
References _aclPoints, RobotExample::A, RobotExample::B, Wm4::DistSegment3Triangle3< Real >::Get(), Wm4::Vector3< Real >::Length(), Wm4::Vector3< Real >::Normalize(), buildPsets::p, MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by MeshCore::MeshAlgorithm::SearchFacetsFromPolyline().
DistanceToPoint() [1/2]
float MeshGeomFacet::DistanceToPoint (const Base::Vector3f & rclPt, Base::Vector3f & rclNt) const
Calculates the shortest distance from the point rcPt to the facet. rclNt is the point of the facet with shortest distance.
Definition at line 981 of file Elements.cpp.
References _aclPoints, Wm4::DistVector3Triangle3< Real >::Get(), Wm4::Distance< Real, Vector3< Real > >::GetClosestPoint1(), Base::Vector3< float_type >::Set(), MovieTool::x, Wm4::Vector3< Real >::X(), Base::Vector3< float_type >::x, MovieTool::y, Wm4::Vector3< Real >::Y(), Base::Vector3< float_type >::y, Wm4::Vector3< Real >::Z(), and Base::Vector3< float_type >::z.
DistanceToPoint() [2/2]
float MeshCore::MeshGeomFacet::DistanceToPoint (const Base::Vector3f & rcPt) const inline
Calculates the shortest distance from the point rcPt to the facet.
Definition at line 597 of file Elements.h.
Referenced by MeshCore::MeshAlgorithm::Distance(), Inspection::InspectNominalMesh::getDistance(), Inspection::InspectNominalFastMesh::getDistance(), MeshCore::MeshAlgorithm::NearestPointFromPoint(), and MeshCore::MeshFacetGrid::SearchNearestFacetInGrid().
Enlarge()
void MeshGeomFacet::Enlarge (float fDist)
Enlarges the triangle.
Definition at line 609 of file Elements.cpp.
References _aclPoints, Base::Vector3< float_type >::GetAngle(), SplineSurface::i, Base::Vector3< float_type >::Normalize(), Base::Vector3< float_type >::Scale(), and KDL::sin().
Foraminate()
bool MeshGeomFacet::Foraminate (const Base::Vector3f & P, const Base::Vector3f & dir, Base::Vector3f & I, float fMaxAngle = Mathf::PI) const
Calculates the intersection point of the line defined by the base rclPt and the direction rclDir with the facet. The intersection must be inside the facet. If there is no intersection false is returned. This does actually the same as IntersectWithLine() with one additionally constraint that the angle between the direction of the line and the normal of the plane must not exceed fMaxAngle.
Definition at line 880 of file Elements.cpp.
References _aclPoints, SCL.SimpleDataTypes::e, Base::Vector3< float_type >::GetAngle(), GetNormal(), toolbit-attributes::s, InitGui::t, buildPsets::u, TestSpreadsheet::v, and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by MeshPart::CurveProjectorShape::findStartPoint(), MeshPart::CurveProjectorSimple::findStartPoint(), Mesh::MeshObject::foraminate(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), MeshCore::MeshAlgorithm::NearestFacetOnRay(), MeshCore::MeshAlgorithm::RayNearestField(), and MeshCore::MeshAlgorithm::Surround().
GetBoundBox()
Base::BoundBox3f MeshCore::MeshGeomFacet::GetBoundBox () const inline
Returns the wrapping bounding box.
Definition at line 964 of file Elements.h.
Referenced by MeshCore::MeshEvalSelfIntersection::GetIntersections(), IntersectWithFacet(), and MeshCore::MeshProjection::projectLineOnMesh().
GetEdge()
MeshGeomEdge MeshGeomFacet::GetEdge (short side) const
Returns the edge for side.
Definition at line 1454 of file Elements.cpp.
References _aclPoints.
Referenced by IntersectWithFacet().
GetGravityPoint()
Base::Vector3f MeshCore::MeshGeomFacet::GetGravityPoint () const inline
Calculates the facet's gravity point.
Definition at line 951 of file Elements.h.
Referenced by MeshCore::MeshDistancePlanarSegment::AddFacet(), MeshCore::PlaneSurfaceFit::AddTriangle(), MeshCore::FacetCurvature::Compute(), Mesh::SegmentByMesh::execute(), MeshCore::MeshDistancePlanarSegment::Initialize(), MeshCore::PlaneSurfaceFit::Initialize(), IntersectPlaneWithLine(), MeshCore::MeshPlaneVisitor::MeshPlaneVisitor(), MeshCore::MeshRefPointToFacets::Neighbours(), MeshCore::MeshSearchNeighbours::NeighboursFacetFromFacet(), MeshCore::MeshSearchNeighbours::NeighboursFromFacet(), MeshCore::MeshSearchNeighbours::NeighboursFromSampledFacets(), MeshPart::MeshAlgos::offsetSpecial2(), Mesh::MeshObject::offsetSpecial2(), Mesh::MeshObject::refine(), MeshCore::MeshRefPointToFacets::SearchNeighbours(), SubSample(), MeshCore::MeshAlgorithm::SubSampleByDist(), and MeshCore::MeshPlaneVisitor::Visit().
GetNormal()
Base::Vector3f MeshCore::MeshGeomFacet::GetNormal () const inline
Returns the normal of the facet.
Definition at line 925 of file Elements.h.
Referenced by MeshCore::MeshBuilder::AddFacet(), MeshCore::MeshKernel::AddFacet(), WriterInventorImp::addNormalNode(), MeshCore::MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection(), MeshGui::ViewProviderMeshTransformDemolding::calcNormalVector(), MeshCore::FacetCurvature::Compute(), MeshGui::ViewProviderMesh::createToolMesh(), MeshCore::MeshEvalDentsOnSurface::Evaluate(), MeshCore::MeshEvalFoldsOnSurface::Evaluate(), MeshCore::MeshEvalFoldsOnBoundary::Evaluate(), MeshCore::MeshEvalFoldOversOnSurface::Evaluate(), MeshCore::MeshAlgorithm::FillupHole(), MeshPart::CurveProjectorShape::findStartPoint(), MeshPart::CurveProjectorSimple::findStartPoint(), Foraminate(), Inspection::InspectNominalMesh::getDistance(), Inspection::InspectNominalFastMesh::getDistance(), MeshCore::MeshDistancePlanarSegment::Initialize(), MeshCore::PlaneSurfaceFit::Initialize(), IntersectPlaneWithLine(), IntersectWithFacet(), MeshCore::MeshTopoAlgorithm::IsCollapseEdgeLegal(), IsCoplanar(), IsPointOf(), MeshPart::CurveProjectorWithToolMesh::makeToolMesh(), MeshCore::MeshPlaneVisitor::MeshPlaneVisitor(), MeshPart::MeshAlgos::offsetSpecial2(), Mesh::MeshObject::offsetSpecial2(), MeshCore::MeshPoint::operator==(), MeshPart::CurveProjectorShape::projectCurve(), MeshPart::CurveProjectorSimple::projectCurve(), MeshPart::MeshProjection::projectEdgeToEdge(), ProjectFacetToPlane(), ProjectPointToPlane(), MeshCore::MeshRefNormalToPoints::Rebuild(), MeshCore::MeshOutput::SaveIDTF(), MeshCore::MeshTopoAlgorithm::ShouldSwapEdge(), MeshGui::ViewProviderMeshOrientation::showDefects(), MeshGui::ViewProviderMeshDuplicatedFaces::showDefects(), MeshGui::ViewProviderMeshIndices::showDefects(), MeshGui::ViewProviderMeshFolds::showDefects(), and MeshCore::CylinderSurfaceFit::TestTriangle().
IntersectBoundingBox()
bool MeshGeomFacet::IntersectBoundingBox (const Base::BoundBox3f & rclBB) const
Checks if the facet intersects with the given bounding box.
Definition at line 698 of file Elements.cpp.
References _aclPoints, exportCSG::center(), Base::BoundBox3< Precision >::GetCenter(), Base::BoundBox3< Precision >::IsInBox(), FreeCADInit::Length, Base::BoundBox3< Precision >::LengthX(), Base::BoundBox3< Precision >::LengthY(), Base::BoundBox3< Precision >::LengthZ(), Wm4::Vector3< Real >::Normalize(), Wm4::IntrSegment3Box3< Real >::Test(), draftgeoutils.general::v1(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by Inspection::MeshInspectGrid::AddFacet(), MeshCore::MeshFacetGrid::AddFacet(), and MeshCore::MeshFacetGrid::Verify().
IntersectPlaneWithLine()
bool MeshGeomFacet::IntersectPlaneWithLine (const Base::Vector3f & rclPt, const Base::Vector3f & rclDir, Base::Vector3f & rclRes) const
Checks if the plane defined by the facet rclFacet intersects with the line defined by the base rclBase and the direction rclNormal and returns the intersection point rclRes if possible.
Definition at line 930 of file Elements.cpp.
References SCL.SimpleDataTypes::e, GetGravityPoint(), GetNormal(), and toolbit-attributes::s.
Referenced by IntersectWithLine(), ProjectFacetToPlane(), and MeshPart::MeshProjection::projectOnMesh().
IntersectWithFacet() [1/2]
int MeshGeomFacet::IntersectWithFacet (const MeshGeomFacet & rclFacet, Base::Vector3f & rclPt0, Base::Vector3f & rclPt1) const
Intersect the facet with the other facet The result is line given by two points (if intersected). Return is the number of intersections points: 0: no intersection, 1: one intersection point (rclPt0), 2: two intersections points (rclPt0, rclPt1)
Fast Triangle-Triangle Intersection Test by Tomas Moeller http://www.acm.org/jgt/papers/Moller97/tritri.html http://www.cs.lth.se/home/Tomas_Akenine_Moller/code/
Definition at line 1102 of file Elements.cpp.
References _aclPoints, Base::BoundBox3< Precision >::Enlarge(), GetBoundBox(), GetEdge(), GetNormal(), SplineSurface::i, MeshCore::MeshGeomEdge::IntersectWithEdge(), IsCoplanar(), Base::BoundBox3< Precision >::IsInBox(), IsPointOf(), updateLeaderLines::point, tri_tri_intersect_with_isectline(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
IntersectWithFacet() [2/2]
bool MeshGeomFacet::IntersectWithFacet (const MeshGeomFacet & rclFacet) const
This method checks if both facets intersect.
Fast Triangle-Triangle Intersection Test by Tomas Moeller http://www.acm.org/jgt/papers/Moller97/tritri.html http://www.cs.lth.se/home/Tomas_Akenine_Moller/code/
Definition at line 1079 of file Elements.cpp.
References _aclPoints, SplineSurface::i, tri_tri_intersect(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by MeshCore::MeshEvalSelfIntersection::Evaluate(), MeshCore::MeshIntersection::getIntersection(), MeshCore::MeshEvalSelfIntersection::GetIntersections(), and MeshCore::MeshAlgorithm::Surround().
IntersectWithLine()
bool MeshGeomFacet::IntersectWithLine (const Base::Vector3f & rclPt, const Base::Vector3f & rclDir, Base::Vector3f & rclRes) const
Calculates the intersection point of the line defined by the base rclPt and the direction rclDir with the facet. The intersection must be inside the facet. If there is no intersection false is returned.
Definition at line 945 of file Elements.cpp.
References SCL.SimpleDataTypes::e, IntersectPlaneWithLine(), and IsPointOfFace().
Referenced by MeshCore::MeshEvalDentsOnSurface::Evaluate(), MeshPart::CurveProjectorWithToolMesh::makeToolMesh(), and MeshPart::CurveProjectorSimple::projectCurve().
IntersectWithPlane() [1/2]
bool MeshCore::MeshGeomFacet::IntersectWithPlane (const Base::Vector3f & rclBase, const Base::Vector3f & rclNormal) const inline
Checks if the facet intersects with the plane defined by the base rclBase and the normal rclNormal.
Definition at line 1006 of file Elements.h.
IntersectWithPlane() [2/2]
bool MeshGeomFacet::IntersectWithPlane (const Base::Vector3f & rclBase, const Base::Vector3f & rclNormal, Base::Vector3f & rclP1, Base::Vector3f & rclP2) const
Checks if the facet intersects with the plane defined by the base rclBase and the normal rclNormal and returns true if two points are found, false otherwise.
Definition at line 756 of file Elements.cpp.
References _aclPoints, Base::Vector3< float_type >::DistanceToPlane(), SCL.SimpleDataTypes::e, Wm4::IntrSegment3Plane3< Real >::Find(), Wm4::IntrSegment3Plane3< Real >::GetSegmentT(), FreeCADInit::Length, Wm4::Vector3< Real >::Normalize(), buildPsets::p, Base::Vector3< float_type >::Set(), draftgeoutils.general::v1(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by MeshCore::MeshTrimByPlane::CheckFacets(), MeshCore::MeshAlgorithm::CutWithPlane(), MeshCore::MeshAlgorithm::GetFacetsFromPlane(), and MeshCore::MeshProjection::projectLineOnMesh().
IsCoplanar()
bool MeshGeomFacet::IsCoplanar (const MeshGeomFacet & facet) const
Checks if the two triangles are coplanar.
Definition at line 1065 of file Elements.cpp.
References _aclPoints, DraftVecUtils::dist(), DistancePlaneToPoint(), SCL.SimpleDataTypes::e, GetNormal(), and unit().
Referenced by IntersectWithFacet().
IsDeformed()
bool MeshGeomFacet::IsDeformed (float fCosOfMinAngle, float fCosOfMaxAngle) const
Checks whether the triangle is deformed. A triangle is deformed if an angle exceeds a given maximum angle or falls below a given minimum angle. For performance reasons the cosine of minimum and maximum angle is expected.
Definition at line 677 of file Elements.cpp.
References _aclPoints, SplineSurface::i, buildPsets::u, and TestSpreadsheet::v.
Referenced by MeshCore::MeshEvalDeformedFacets::Evaluate(), MeshCore::MeshEvalDeformedFacets::GetIndices(), and Mesh::MeshObject::refine().
IsDegenerated()
bool MeshGeomFacet::IsDegenerated (float epsilon) const
Checks whether the triangle is degenerated. A triangle is degenerated if its area is less than an epsilon.
Definition at line 634 of file Elements.cpp.
References _aclPoints, KDL::epsilon, buildPsets::u, and TestSpreadsheet::v.
Referenced by MeshCore::MeshEvalDegeneratedFacets::Evaluate(), MeshCore::MeshFixDegeneratedFacets::Fixup(), MeshCore::MeshFixDeformedFacets::Fixup(), MeshCore::MeshEvalDegeneratedFacets::GetIndices(), and MeshCore::MeshTopoAlgorithm::IsSwapEdgeLegal().
IsFlag()
bool MeshCore::MeshGeomFacet::IsFlag (MeshFacet::TFlagType tF) const inline
Query the flag state of the facet.
Definition at line 546 of file Elements.h.
Referenced by MeshPart::MeshAlgos::offsetSpecial2(), and Mesh::MeshObject::offsetSpecial2().
IsPointOf() [1/2]
bool MeshGeomFacet::IsPointOf (const Base::Vector3f & P) const
Checks if the point is inside or at the border of the facet. The point must already exactly lie on the plane defined by the facet, which is not checked. This method is very efficient.
Definition at line 1214 of file Elements.cpp.
References _aclPoints, SCL.SimpleDataTypes::e, toolbit-attributes::s, InitGui::t, buildPsets::u, TestSpreadsheet::v, and src.Mod.PartDesign.fcgear.svggear::w.
IsPointOf() [2/2]
bool MeshGeomFacet::IsPointOf (const Base::Vector3f & rclPoint, float fDistance) const
Checks if the point is part of the facet. A point is regarded as part of a facet if the distance is lower fDistance and the projected point in the facet normal direction is inside the triangle.
Definition at line 481 of file Elements.cpp.
References _aclPoints, DistancePlaneToPoint(), Base::Vector3< float_type >::DistanceToLine(), and GetNormal().
Referenced by IntersectWithFacet().
IsPointOfFace()
bool MeshGeomFacet::IsPointOfFace (const Base::Vector3f & rclP, float fDistance) const
Checks whether the given point is inside the facet with tolerance fDistance. This method does actually the same as IsPointOf() but this implementation is done more effective through comparison of normals.
Definition at line 544 of file Elements.cpp.
References _aclPoints, a, SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::c, Base::Vector3< float_type >::Length(), buildPsets::p, MovieTool::x, and MovieTool::y.
Referenced by MeshCore::MeshAlgorithm::FirstFacetToVertex(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), IntersectWithLine(), MeshPart::MeshProjection::projectOnMesh(), and MeshCore::MeshAlgorithm::Surround().
IsPointOfSphere() [1/2]
bool MeshGeomFacet::IsPointOfSphere (const Base::Vector3f & rP) const
The center and radius of the circum circle define a sphere in 3D. If the point rP is part of this sphere true is returned, otherwise false.
Definition at line 1534 of file Elements.cpp.
References exportCSG::center(), CenterOfCircumCircle(), DraftVecUtils::dist(), and Base::DistanceP2().
IsPointOfSphere() [2/2]
bool MeshGeomFacet::IsPointOfSphere (const MeshGeomFacet & rFacet) const
This is an overloaded member function, provided for convenience. It behaves essentially like the above function. If one of the facet's points is inside the sphere true is returned, otherwise false.
Definition at line 1545 of file Elements.cpp.
References _aclPoints, exportCSG::center(), CenterOfCircumCircle(), DraftVecUtils::dist(), and Base::DistanceP2().
MaximumAngle()
float MeshGeomFacet::MaximumAngle () const
Calculates the maximum angle of a facet.
Definition at line 1502 of file Elements.cpp.
References _aclPoints, Base::Vector3< float_type >::GetAngle(), and SplineSurface::i.
Referenced by MeshCore::MeshTopoAlgorithm::ShouldSwapEdge(), and MeshCore::QuasiDelaunayTriangulator::Triangulate().
MinimumAngle()
float MeshGeomFacet::MinimumAngle () const
Calculates the minimum angle of a facet.
Definition at line 1518 of file Elements.cpp.
References _aclPoints, Base::Vector3< float_type >::GetAngle(), SplineSurface::i, and MeshCore::Math< Prec >::PI.
NearestEdgeToPoint() [1/2]
unsigned short MeshGeomFacet::NearestEdgeToPoint (const Base::Vector3f & rclPt) const
Returns the edge number of the facet that is nearest to the point rclPt.
Definition at line 1304 of file Elements.cpp.
References _aclPoints, Base::Distance(), FLOAT_MAX, and InitGui::t.
Referenced by MeshCore::MeshAlgorithm::FirstFacetToVertex().
NearestEdgeToPoint() [2/2]
void MeshGeomFacet::NearestEdgeToPoint (const Base::Vector3f & rclPt, float & fDistance, unsigned short & side) const
Returns the edge number side of the facet and the distance to the edge that is nearest to the point rclPt.
Definition at line 1378 of file Elements.cpp.
References _aclPoints, Base::Distance(), FLOAT_MAX, and InitGui::t.
NormalInvalid()
void MeshCore::MeshGeomFacet::NormalInvalid () inline
Invalidate the normal. It will be recomputed when querying it.
Definition at line 541 of file Elements.h.
Referenced by Transform().
operator=() [1/2]
MeshGeomFacet& MeshCore::MeshGeomFacet::operator= (const MeshGeomFacet &) default
Referenced by Mesh::Facet::operator=().
operator=() [2/2]
MeshGeomFacet& MeshCore::MeshGeomFacet::operator= (MeshGeomFacet &&) default
Perimeter()
float MeshCore::MeshGeomFacet::Perimeter () const inline
Calculates the perimeter of the facet.
Definition at line 969 of file Elements.h.
Referenced by MeshCore::MeshRemoveNeedles::Fixup().
ProjectFacetToPlane()
void MeshGeomFacet::ProjectFacetToPlane (MeshGeomFacet & rclFacet) const
Calculates the projection of a facet onto the plane defined by the triangle.
Definition at line 601 of file Elements.cpp.
References _aclPoints, GetNormal(), and IntersectPlaneWithLine().
ProjectPointToPlane()
void MeshGeomFacet::ProjectPointToPlane (const Base::Vector3f & rclPoint, Base::Vector3f & rclProj) const
Calculates the projection of a point onto the plane defined by the triangle.
Definition at line 595 of file Elements.cpp.
References _aclPoints, GetNormal(), and Base::Vector3< float_type >::ProjectToPlane().
Referenced by MeshCore::MeshAlgorithm::FirstFacetToVertex().
ResetFlag()
void MeshCore::MeshGeomFacet::ResetFlag (MeshFacet::TFlagType tF) inline
Reset flag state
Definition at line 556 of file Elements.h.
Roundness()
float MeshGeomFacet::Roundness () const
The roundness is in the range between 0.0 (colinear) and 1.0 (equilateral).
Definition at line 1597 of file Elements.cpp.
References _aclPoints, Area(), and Base::Vector3< float_type >::Sqr().
SetFlag()
void MeshCore::MeshGeomFacet::SetFlag (MeshFacet::TFlagType tF) inline
Set flag state
Definition at line 551 of file Elements.h.
SetNormal()
void MeshCore::MeshGeomFacet::SetNormal (const Base::Vector3f & rclNormal) inline
Sets the facet's normal.
Definition at line 933 of file Elements.h.
Referenced by MeshCore::MeshInput::LoadAsciiSTL().
SubSample()
void MeshGeomFacet::SubSample (float fStep, std::vector< Base::Vector3f > & rclPoints) const
Subsamples the facet into points with resolution fStep.
Definition at line 1000 of file Elements.cpp.
References _aclPoints, RobotExample::A, RobotExample::B, RobotExample::C, SCL.SimpleDataTypes::f, GetGravityPoint(), Base::Vector3< float_type >::Length(), Base::Vector3< float_type >::Normalize(), KDL::sin(), KDL::sqrt(), buildPsets::u, TestSpreadsheet::v, and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by MeshCore::MeshSearchNeighbours::SampleAllFacets(), and MeshCore::MeshAlgorithm::SubSampleByDist().
Transform()
void MeshGeomFacet::Transform (const Base::Matrix4D & mat)
Apply a transformation on the triangle.
Definition at line 1609 of file Elements.cpp.
References _aclPoints, Base::Matrix4D::multVec(), and NormalInvalid().
Referenced by Inspection::InspectNominalMesh::getDistance(), and Inspection::InspectNominalFastMesh::getDistance().
VolumeOfPrism()
float MeshGeomFacet::VolumeOfPrism (const MeshGeomFacet & rclF) const
Calculates the volume of the prism defined by two facets.
Note
The two facets must not intersect.
Definition at line 1462 of file Elements.cpp.
References _aclPoints, and FreeCADInit::Length.
Weights()
bool MeshGeomFacet::Weights (const Base::Vector3f & rclP, float & w0, float & w1, float & w2) const
Calculates the weights w1, ..., w3 of the corners to get the point rclP, i.e. rclP = w0*v0 + w1*v1 + w2*v2 (v0-v2 are the corners corners). If w0+w1+w2==1.0 then the point rclP lies on the plane that is spanned by the facet, otherwise the point doesn't lie on the plane. If the sum of wi is 1 and if each wi is between [0,1] than the point lies inside the facet or on the border, respectively.
If the point doesn't lie on the plane false is returned, true otherwise.
Definition at line 581 of file Elements.cpp.
References _aclPoints, Area(), and MeshGeomFacet().
Member Data Documentation
_aclPoints
Base::Vector3f MeshCore::MeshGeomFacet::_aclPoints[3]
Geometric corner points.
Definition at line 694 of file Elements.h.
Referenced by MeshCore::MeshBuilder::AddFacet(), Inspection::MeshInspectGrid::AddFacet(), MeshCore::MeshFastBuilder::AddFacet(), MeshCore::MeshFacetGrid::AddFacet(), MeshCore::MeshKernel::AddFacet(), MeshCore::CylinderSurfaceFit::AddTriangle(), MeshCore::SphereSurfaceFit::AddTriangle(), MeshCore::MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection(), MeshCore::MeshPlaneVisitor::AllowVisit(), ArrangeNormal(), AspectRatio(), AspectRatio2(), CenterOfCircumCircle(), CenterOfInscribedCircle(), MeshCore::MeshTrimByPlane::CheckFacets(), MeshCore::MeshAlgorithm::CheckFacets(), MeshCore::MeshEvalDegeneratedFacets::CountEdgeTooSmall(), Mesh::MeshObject::createCube(), Mesh::MeshObject::createMeshFromList(), MeshGui::ViewProviderMesh::createToolMesh(), MeshCore::MeshTopoAlgorithm::DelaunayFlip(), DistanceToLineSegment(), DistanceToPoint(), Enlarge(), MeshGui::ViewProviderMesh::faceInfo(), Mesh::Facet::Facet(), MeshCore::MeshAlgorithm::FillupHole(), MeshCore::MeshFixDeformedFacets::Fixup(), Foraminate(), MeshCore::MeshAlgorithm::GetAverageEdgeLength(), Inspection::InspectNominalMesh::getDistance(), Inspection::InspectNominalFastMesh::getDistance(), Mesh::Facet::getEdge(), GetEdge(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshAlgorithm::GetFacetsFromPlane(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), MeshCore::MeshAlgorithm::GetMaximumEdgeLength(), MeshCore::MeshAlgorithm::GetMinimumEdgeLength(), MeshCore::AbstractPolygonTriangulator::GetTriangle(), MeshCore::MeshKernel::GetVolume(), MeshCore::MeshDistancePlanarSegment::Initialize(), MeshCore::PlaneSurfaceFit::Initialize(), MeshCore::CylinderSurfaceFit::Initialize(), MeshCore::SphereSurfaceFit::Initialize(), IntersectBoundingBox(), IntersectWithFacet(), IntersectWithPlane(), IsCoplanar(), IsDeformed(), IsDegenerated(), IsPointOf(), IsPointOfFace(), IsPointOfSphere(), MeshCore::MeshInput::LoadAsciiSTL(), MaximumAngle(), MeshGeomFacet(), MeshCore::MeshPlaneVisitor::MeshPlaneVisitor(), MinimumAngle(), NearestEdgeToPoint(), MeshCore::MeshPoint::operator<(), MeshCore::MeshPoint::operator==(), MeshPart::CurveProjectorShape::projectCurve(), ProjectFacetToPlane(), ProjectPointToPlane(), Roundness(), MeshCore::MeshOutput::SavePython(), MeshGui::ViewProviderMeshOrientation::showDefects(), MeshGui::ViewProviderMeshDuplicatedFaces::showDefects(), MeshGui::ViewProviderMeshDegenerations::showDefects(), MeshGui::ViewProviderMeshIndices::showDefects(), MeshGui::ViewProviderMeshFolds::showDefects(), Mesh::MeshObject::splitEdges(), SubSample(), MeshCore::MeshDistancePlanarSegment::TestFacet(), MeshCore::MeshDistanceGenericSurfaceFitSegment::TestFacet(), MeshCore::MeshDistanceGenericSurfaceFitSegment::TestInitialFacet(), Transform(), MeshCore::EarClippingTriangulator::Triangulate(), MeshCore::DelaunayTriangulator::Triangulate(), MeshCore::MeshTrimByPlane::TrimFacets(), VolumeOfPrism(), and Weights().
_ucFlag
unsigned char MeshCore::MeshGeomFacet::_ucFlag
Flag property
Definition at line 695 of file Elements.h.
Referenced by MeshCore::MeshBuilder::AddFacet(), and MeshCore::MeshKernel::GetFacet().
_ulProp
unsigned long MeshCore::MeshGeomFacet::_ulProp
Free usable property.
Definition at line 696 of file Elements.h.
Referenced by MeshCore::MeshBuilder::AddFacet(), and MeshCore::MeshKernel::GetFacet().
The documentation for this class was generated from the following files:
Elements.h
Elements.cpp