FreeCAD: App::DocumentObjectT Class Reference
App::DocumentObjectT Class Reference
#include <DocumentObserver.h>
Public Member Functions
DocumentObjectT ()
DocumentObjectT (const DocumentObjectT &)
DocumentObjectT (DocumentObjectT &&)
DocumentObjectT (const DocumentObject *)
DocumentObjectT (const Document *, const std::string &objName)
DocumentObjectT (const char *docName, const char *objName)
DocumentObjectT (const Property *)
~DocumentObjectT ()
DocumentObjectT & operator= (const DocumentObjectT &)
DocumentObjectT & operator= (DocumentObjectT &&)
void operator= (const DocumentObject *)
void operator= (const Property *)
bool operator== (const DocumentObjectT &) const
Document * getDocument () const
const std::string & getDocumentName () const
std::string getDocumentPython () const
DocumentObject * getObject () const
Property * getProperty () const
const std::string & getObjectName () const
const std::string & getObjectLabel () const
const std::string & getPropertyName () const
std::string getObjectPython () const
std::string getPropertyPython () const
template<typename T >
T * getObjectAs () const
template<typename T >
T * getPropertyAs () const
Detailed Description
The DocumentObjectT class is a helper class to store the names of a document object and its document. This can be useful when you cannot rely on that the document or the object still exists when you have to access it.
Author
Werner Mayer
Definition at line 116 of file App/DocumentObserver.h.
Constructor & Destructor Documentation
DocumentObjectT() [1/7]
DocumentObjectT::DocumentObjectT () default
Constructor
DocumentObjectT() [2/7]
DocumentObjectT::DocumentObjectT (const DocumentObjectT & other)
Constructor
Definition at line 97 of file App/DocumentObserver.cpp.
DocumentObjectT() [3/7]
DocumentObjectT::DocumentObjectT (DocumentObjectT && other)
Constructor
Definition at line 102 of file App/DocumentObserver.cpp.
References Path.Post.scripts.opensbp_post::move().
DocumentObjectT() [4/7]
DocumentObjectT::DocumentObjectT (const DocumentObject * obj) explicit
Constructor
Definition at line 107 of file App/DocumentObserver.cpp.
DocumentObjectT() [5/7]
DocumentObjectT::DocumentObjectT (const Document * doc, const std::string & objName)
Constructor
Definition at line 117 of file App/DocumentObserver.cpp.
References toolbit-attributes::doc.
DocumentObjectT() [6/7]
DocumentObjectT::DocumentObjectT (const char * docName, const char * objName)
Constructor
Definition at line 125 of file App/DocumentObserver.cpp.
DocumentObjectT() [7/7]
DocumentObjectT::DocumentObjectT (const Property * prop) explicit
Constructor
Definition at line 112 of file App/DocumentObserver.cpp.
~DocumentObjectT()
DocumentObjectT::~DocumentObjectT () default
Destructor
Member Function Documentation
getDocument()
Document * DocumentObjectT::getDocument () const
Get a pointer to the document or 0 if it doesn't exist any more.
Definition at line 201 of file App/DocumentObserver.cpp.
References App::GetApplication(), and App::Application::getDocument().
Referenced by getObject(), App::SubObjectT::getObjectFullName(), App::SubObjectT::getSubObjectFullName(), and Gui::PropertyEditor::PropertyLinkItem::toString().
getDocumentName()
const std::string & DocumentObjectT::getDocumentName () const
Get the name of the document.
Definition at line 206 of file App/DocumentObserver.cpp.
Referenced by App::SubObjectT::getObjectFullName(), App::SubObjectT::getSubObjectFullName(), App::SubObjectT::operator<(), and Gui::PropertyEditor::LinkSelection::select().
getDocumentPython()
std::string DocumentObjectT::getDocumentPython () const
Get the document as Python command.
Definition at line 211 of file App/DocumentObserver.cpp.
References Path.Post.scripts.refactored_centroid_post::str.
Referenced by ReenGui::FitBSplineSurfaceWidget::accept(), and ReenGui::PoissonWidget::accept().
getObject()
DocumentObject * DocumentObjectT::getObject () const
Get a pointer to the document object or 0 if it doesn't exist any more.
Definition at line 218 of file App/DocumentObserver.cpp.
References toolbit-attributes::doc, and getDocument().
Referenced by PartDesign::SubShapeBinder::collapseGeoChildren(), Gui::Dialog::DlgPropertyLink::formatObject(), getLocatedShape(), App::SubObjectT::getNewElementName(), App::SubObjectT::getOldElementName(), getProperty(), AssemblyGui::ViewProviderAssembly::getSelectedObjectsWithinAssembly(), getShapeFromStrings(), App::SubObjectT::getSubObject(), App::SubObjectT::getSubObjectList(), Measure::ResolveResult::getTarget(), Measure::ResolveResult::getTargetParent(), Gui::Dialog::DlgPropertyLink::init(), App::SubObjectT::normalize(), Gui::PropertyEditor::LinkLabel::updatePropertyLink(), and MeshPartGui::Mesh2ShapeGmsh::writeProject().
getObjectAs()
template<typename T > T* App::DocumentObjectT::getObjectAs () const inline
Get a pointer to the document or 0 if it doesn't exist any more or the type doesn't match.
Definition at line 169 of file App/DocumentObserver.h.
getObjectLabel()
const std::string & DocumentObjectT::getObjectLabel () const
Get the label of the document object.
Definition at line 233 of file App/DocumentObserver.cpp.
References NavigationIndicatorGui::label.
Referenced by App::SubObjectT::getObjectFullName().
getObjectName()
const std::string & DocumentObjectT::getObjectName () const
Get the name of the document object.
Definition at line 228 of file App/DocumentObserver.cpp.
Referenced by buildAdapter(), App::SubObjectT::getObjectFullName(), App::SubObjectT::getSubObjectFullName(), Gui::SelectionSingleton::hasPreselection(), MeasureAngleHandler(), MeasureAreaHandler(), MeasureDistanceHandler(), MeasureLengthHandler(), MeasurePositionHandler(), App::SubObjectT::operator<(), Gui::PropertyEditor::LinkSelection::select(), and Gui::SelectionSingleton::setPreselectCoord().
getObjectPython()
std::string DocumentObjectT::getObjectPython () const
Get the document object as Python command.
Definition at line 238 of file App/DocumentObserver.cpp.
References Path.Post.scripts.refactored_centroid_post::str.
Referenced by ReenGui::FitBSplineSurfaceWidget::accept(), ReenGui::PoissonWidget::accept(), getPropertyPython(), App::SubObjectT::getSubObjectPython(), and App::PropertyLinkT::PropertyLinkT().
getProperty()
Property * DocumentObjectT::getProperty () const
Get a pointer to the property or 0 if it doesn't exist any more.
Definition at line 260 of file App/DocumentObserver.cpp.
References getObject().
Referenced by Gui::Dialog::DlgPropertyLink::init(), and Gui::PropertyEditor::LinkLabel::updatePropertyLink().
getPropertyAs()
template<typename T > T* App::DocumentObjectT::getPropertyAs () const inline
Definition at line 174 of file App/DocumentObserver.h.
getPropertyName()
const std::string & DocumentObjectT::getPropertyName () const
Get the name of the property.
Definition at line 245 of file App/DocumentObserver.cpp.
Referenced by App::SubObjectT::operator<().
getPropertyPython()
std::string DocumentObjectT::getPropertyPython () const
Get the property as Python command.
Definition at line 250 of file App/DocumentObserver.cpp.
References getObjectPython(), and Path.Post.scripts.refactored_centroid_post::str.
operator=() [1/4]
void DocumentObjectT::operator= (const DocumentObject * obj)
Assignment operator
Definition at line 161 of file App/DocumentObserver.cpp.
References App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), App::PropertyString::getValue(), App::DocumentObject::isAttachedToDocument(), and App::DocumentObject::Label.
operator=() [2/4]
DocumentObjectT & DocumentObjectT::operator= (const DocumentObjectT & obj)
Assignment operator
Definition at line 137 of file App/DocumentObserver.cpp.
operator=() [3/4]
void DocumentObjectT::operator= (const Property * prop)
Assignment operator
Definition at line 177 of file App/DocumentObserver.cpp.
References Base::Persistence::getClassTypeId(), App::Property::getContainer(), App::Property::getName(), App::DocumentObject::getNameInDocument(), App::Property::hasName(), and Base::BaseClass::isDerivedFrom().
operator=() [4/4]
DocumentObjectT & DocumentObjectT::operator= (DocumentObjectT && obj)
Assignment operator
Definition at line 149 of file App/DocumentObserver.cpp.
References Path.Post.scripts.opensbp_post::move().
operator==()
bool DocumentObjectT::operator== (const DocumentObjectT & other) const
Equality operator
Definition at line 195 of file App/DocumentObserver.cpp.
The documentation for this class was generated from the following files:
App/DocumentObserver.h
App/DocumentObserver.cpp