FreeCAD: App::Extension Class Reference
App::Extension Class Reference
Base class for all extension that can be added to a DocumentObject.
#include <Extension.h>
Public Member Functions
virtual Base::Type getExtensionTypeId (void) const
Extension ()=default
virtual ~Extension ()
virtual void initExtension (App::ExtensionContainer *obj)
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual PyObject * getExtensionPyObject ()
Access properties
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
Persistence
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
Static Public Member Functions
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Protected Member Functions
virtual const App::PropertyData & extensionGetPropertyData (void) const
Static Protected Member Functions
static const App::PropertyData * extensionGetPropertyDataPtr (void)
TypeHandling
class App::ExtensionContainer
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
bool extensionIsDerivedFrom (const Base::Type type) const
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
virtual void extensionOnChanged (const Property *p)
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
returns true if the property name change was handled by the extension.
virtual bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
returns true if the property type change was handled by the extension.
void initExtensionType (Base::Type type)
Detailed Description
Base class for all extension that can be added to a DocumentObject.
For general documentation on why extension system exists and how to use it see the ExtensionContainer documentation. Following is a description howto create custom extensions.
Extensions are like every other FreeCAD object and based on properties. All information storage and persistence should be achieved by use of those. Additional any number of methods can be added to provide functionality around the properties. There are 3 small difference to normal objects:
They must be derived from Extension class
Properties must be handled with special extension macros
Extensions must be initialised This works as simple as
class MyExtension : public Extension {
  EXTENSION_PROPERTY_HEADER(MyExtension);
  PropertyInt MyProp;
  virtual bool overridableMethod(DocumentObject* obj) {};
};
EXTENSION_PROPERTY_SOURCE(App::MyExtension, App::Extension)
MyExtension::MyExtension() {
    EXTENSION_ADD_PROPERTY(MyProp, (0)) *
    initExtension(MyExtension::getExtensionClassTypeId());
}
using MyExtensionPython = ExtensionPythonT<MyExtension>;
The special python extension type created above is important, as only those python extensions can be added to an object from python. It does not work to add the c++ version directly there.
Note that every method of the extension becomes part of the extended object when added from c++. This means one should carefully design the API and make only necessary methods public or protected. Every internal method should be private.
The automatic availability of methods in the class does not hold for the python interface, only for c++ classes. This is like every where else in FreeCAD, there is no automatic creation of python API from c++ classes. Hence the extension creator must also create a custom python object of its extension, which works exactly like the normal FreeCAD python object workflow. There is nothing special at all for extension python objects, the normal xml + imp.cpp approach is used. It must only be taken care that the objects father is the correct extension base class. Of course also make sure your extension returns the correct python object in its "getPyObject" call. Every method you create in the extensions python will be later added to an extended object. This happens automatically for both, c++ and python extension, if "getPyObject" returns the correct python object. No extra work needs to be done.
A special case that needs to be handled for extensions is the possibility of overridden methods. Often it is desired to customise extension behaviour by allowing the user to override methods provided by the extension. On c++ side this is trivial, such methods are simply marked as "virtual" and can than be overridden in any derived class. This is more involved for the python interface and here special care needs to be taken.
As already seen above one needs to create a special ExtensionPythonT<> object for extension from python. This is done exactly for the purpose of allowing to have overridable methods. The ExtensionPythonT wrapper adds a proxy property which holds a PyObject which itself will contain the implementations for the overridden methods. This design is equal to the ObjectPythonT<> design of normal document objects. As this wrapper inherits the c++ extension class it can also override the virtual functions the user designed to be overridden. What it should do at a call of the virtual method is to check if this method is implemented in the proxy object and if so call it, and if not call the normal c++ version. It is the extensions creators responsibility to implement this check and call behaviour for every overridable method. This is done by creating a custom wrapper just like ExtensionPythonT<> and overriding all virtual methods.
template<typename ExtensionT> class MyExtensionPythonT : public ExtensionT {
public:
  MyExtensionPythonT() {}
  virtual ~MyExtensionPythonT() {}
  virtual bool overridableMethod(DocumentObject* obj)  override {
      Py::Object pyobj = Py::asObject(obj->getPyObject());
      EXTENSION_PROXY_ONEARG(allowObject, pyobj);
      if(result.isNone())
          ExtensionT::allowObject(obj);
      if(result.isBoolean())
          return result.isTrue();
      return false;
  };
};
@Note As seen in the code there are multiple helper macros to ease the repetitive work of querying and calling methods of the proxy object. See the macro documentation for how to use them.
To ensure that your wrapper is used when a extension is created from python the extension type must be exposed as follows:
using MyExtensionPython = ExtensionPythonT<MyExtensionPythonT<MyExtension>>;
This boilerplate is absolutely necessary to allow overridable methods in python and it is the extension creator's responsibility to ensure full implementation.
Definition at line 244 of file Extension.h.
Constructor & Destructor Documentation
Extension()
App::Extension::Extension () default
~Extension()
Extension::~Extension () virtual
Definition at line 66 of file Extension.cpp.
References ExtensionPythonObject, Py::SmartPtr::is(), Py::SmartPtr::ptr(), and Base::PyObjectBase::setInvalid().
Member Function Documentation
create()
void * App::Extension::create (void) static
Definition at line 41 of file Extension.cpp.
Referenced by draftguitools.gui_labels.Label::action(), and init().
extensionGetPropertyByName()
Property * Extension::extensionGetPropertyByName (const char * name) const virtual
find a property by its name
Reimplemented in App::LinkBaseExtension.
Definition at line 132 of file Extension.cpp.
References extensionGetPropertyData(), App::PropertyData::getPropertyByName(), and name().
Referenced by App::LinkBaseExtension::extensionGetPropertyByName().
extensionGetPropertyData()
const App::PropertyData & App::Extension::extensionGetPropertyData (void) const protected virtual
Reimplemented in App::LinkExtension, App::LinkBaseExtension, and App::DocumentObjectExtension.
Definition at line 48 of file Extension.cpp.
Referenced by extensionGetPropertyByName(), extensionGetPropertyDocumentation(), extensionGetPropertyGroup(), extensionGetPropertyList(), extensionGetPropertyMap(), extensionGetPropertyName(), extensionGetPropertyType(), and initExtension().
extensionGetPropertyDataPtr()
const App::PropertyData * App::Extension::extensionGetPropertyDataPtr (void) static protected
Definition at line 43 of file Extension.cpp.
extensionGetPropertyDocumentation() [1/2]
const char * Extension::extensionGetPropertyDocumentation (const char * name) const virtual
get the Group of a named Property
Definition at line 168 of file Extension.cpp.
References extensionGetPropertyData(), App::PropertyData::getDocumentation(), and name().
extensionGetPropertyDocumentation() [2/2]
const char * Extension::extensionGetPropertyDocumentation (const Property * prop) const virtual
get the Group of a Property
Definition at line 163 of file Extension.cpp.
References extensionGetPropertyData(), and App::PropertyData::getDocumentation().
extensionGetPropertyGroup() [1/2]
const char * Extension::extensionGetPropertyGroup (const char * name) const virtual
get the Group of a named Property
Definition at line 157 of file Extension.cpp.
References extensionGetPropertyData(), App::PropertyData::getGroup(), and name().
extensionGetPropertyGroup() [2/2]
const char * Extension::extensionGetPropertyGroup (const Property * prop) const virtual
get the Group of a Property
Definition at line 152 of file Extension.cpp.
References extensionGetPropertyData(), and App::PropertyData::getGroup().
extensionGetPropertyList()
void Extension::extensionGetPropertyList (std::vector< Property * > & List) const virtual
get all properties of the class (including properties of the parent)
Definition at line 173 of file Extension.cpp.
References extensionGetPropertyData(), and App::PropertyData::getPropertyList().
extensionGetPropertyMap()
void Extension::extensionGetPropertyMap (std::map< std::string, Property * > & Map) const virtual
get all properties of the class (including properties of the parent)
Definition at line 179 of file Extension.cpp.
References extensionGetPropertyData(), and App::PropertyData::getPropertyMap().
extensionGetPropertyName()
const char * Extension::extensionGetPropertyName (const Property * prop) const virtual
get the name of a property
Definition at line 147 of file Extension.cpp.
References extensionGetPropertyData(), and App::PropertyData::getName().
Referenced by App::LinkBaseExtension::setProperty().
extensionGetPropertyType() [1/2]
short int Extension::extensionGetPropertyType (const char * name) const virtual
get the Type of a named Property
Definition at line 142 of file Extension.cpp.
References extensionGetPropertyData(), App::PropertyData::getType(), and name().
extensionGetPropertyType() [2/2]
short int Extension::extensionGetPropertyType (const Property * prop) const virtual
get the Type of a Property
Definition at line 137 of file Extension.cpp.
References extensionGetPropertyData(), and App::PropertyData::getType().
extensionHandleChangedPropertyName()
bool Extension::extensionHandleChangedPropertyName (Base::XMLReader & reader, const char * TypeName, const char * PropName) protected virtual
returns true if the property name change was handled by the extension.
Reimplemented in Part::AttachExtension.
Definition at line 200 of file Extension.cpp.
References TechDrawTools.TaskFillTemplateFields::reader.
Referenced by Part::AttachExtension::extensionHandleChangedPropertyName().
extensionHandleChangedPropertyType()
bool Extension::extensionHandleChangedPropertyType (Base::XMLReader & reader, const char * TypeName, Property * prop) protected virtual
returns true if the property type change was handled by the extension.
Reimplemented in PartGui::ViewProviderGridExtension.
Definition at line 211 of file Extension.cpp.
References TechDrawTools.TaskFillTemplateFields::reader.
Referenced by PartGui::ViewProviderGridExtension::extensionHandleChangedPropertyType().
extensionIsDerivedFrom()
bool App::Extension::extensionIsDerivedFrom (const Base::Type type) const inline
Definition at line 302 of file Extension.h.
Referenced by App::LinkBaseExtension::getTrueLinkedObject().
extensionOnChanged()
virtual void App::Extension::extensionOnChanged (const Property * p) inline protected virtual
Reimplemented in App::LinkBaseExtension, App::GroupExtension, App::GeoFeatureGroupExtension, App::OriginGroupExtension, Fem::FemPostSmoothFilterExtension, PartGui::ViewProviderSplineExtension, Part::AttachExtension, Part::PrismExtension, PartGui::ViewProviderGridExtension, and Gui::ViewProviderLinkObserver.
Definition at line 308 of file Extension.h.
Referenced by PartGui::ViewProviderSplineExtension::extensionOnChanged(), Part::PrismExtension::extensionOnChanged(), App::GroupExtension::extensionOnChanged(), Part::AttachExtension::extensionOnChanged(), and App::LinkBaseExtension::extensionOnChanged().
extensionRestore()
virtual void App::Extension::extensionRestore (Base::XMLReader &) inline virtual
Definition at line 297 of file Extension.h.
extensionSave()
virtual void App::Extension::extensionSave (Base::Writer &) const inline virtual
Definition at line 296 of file Extension.h.
getExtendedContainer() [1/2]
App::ExtensionContainer* App::Extension::getExtendedContainer () inline
Definition at line 258 of file Extension.h.
Referenced by App::GroupExtension::extensionGetSubObject(), App::GeoFeatureGroupExtension::extensionGetSubObject(), Gui::ViewProviderLinkObserver::extensionModeSwitchChange(), Gui::ViewProviderLinkObserver::extensionReattach(), App::LinkBaseExtension::getContainer(), App::DocumentObjectExtension::getExtendedObject(), Gui::ViewProviderExtension::getExtendedViewProvider(), and App::GeoFeatureGroupExtension::placement().
getExtendedContainer() [2/2]
const App::ExtensionContainer* App::Extension::getExtendedContainer () const inline
Definition at line 259 of file Extension.h.
getExtensionClassTypeId()
Base::Type App::Extension::getExtensionClassTypeId (void) static
Definition at line 41 of file Extension.cpp.
Referenced by App::ExtensionContainer::restoreExtensions(), PartGui::ViewProviderAttachExtension::ViewProviderAttachExtension(), TechDrawGui::ViewProviderCosmeticExtension::ViewProviderCosmeticExtension(), TechDrawGui::ViewProviderDrawingViewExtension::ViewProviderDrawingViewExtension(), Gui::ViewProviderExtension::ViewProviderExtension(), Gui::ViewProviderFaceTexture::ViewProviderFaceTexture(), Gui::ViewProviderGeoFeatureGroupExtension::ViewProviderGeoFeatureGroupExtension(), PartGui::ViewProviderGridExtension::ViewProviderGridExtension(), Gui::ViewProviderGroupExtension::ViewProviderGroupExtension(), Gui::ViewProviderOriginGroupExtension::ViewProviderOriginGroupExtension(), TechDrawGui::ViewProviderPageExtension::ViewProviderPageExtension(), PartGui::ViewProviderSplineExtension::ViewProviderSplineExtension(), Gui::ViewProviderSuppressibleExtension::ViewProviderSuppressibleExtension(), TechDrawGui::ViewProviderTemplateExtension::ViewProviderTemplateExtension(), and Gui::ViewProviderTextureExtension::ViewProviderTextureExtension().
getExtensionPyObject()
PyObject * Extension::getExtensionPyObject () virtual
Reimplemented in App::LinkBaseExtension, Part::AttachExtension, App::GroupExtension, TechDraw::CosmeticExtension, Gui::ViewProviderExtension, App::DocumentObjectExtension, and App::SuppressibleExtension.
Definition at line 107 of file Extension.cpp.
References ExtensionPythonObject, toolbit-attributes::grp, Py::SmartPtr::is(), and Py::new_reference_to().
getExtensionTypeId()
Base::Type App::Extension::getExtensionTypeId (void) const virtual
Reimplemented in App::LinkExtension, App::LinkBaseExtension, and App::DocumentObjectExtension.
Definition at line 41 of file Extension.cpp.
init()
void App::Extension::init (void) static
Definition at line 55 of file Extension.cpp.
References Base::Type::badType(), create(), and Base::Type::createType().
Referenced by Gui::Application::initTypes(), App::Application::initTypes(), DocumentObject.DocumentObject::onChanged(), and PyMOD_INIT_FUNC().
initExtension()
void Extension::initExtension (App::ExtensionContainer * obj) virtual
Reimplemented in App::GeoFeatureGroupExtension.
Definition at line 88 of file Extension.cpp.
References extensionGetPropertyData(), App::PropertyData::getPropertyList(), Base::Type::isBad(), and App::ExtensionContainer::registerExtension().
Referenced by PartDesign::Cylinder::Cylinder(), Part::Cylinder::Cylinder(), Part::Datum::Datum(), Part::DatumLine::DatumLine(), Part::DatumPlane::DatumPlane(), Part::DatumPoint::DatumPoint(), App::DocumentObjectGroup::DocumentObjectGroup(), TechDraw::DrawViewPart::DrawViewPart(), PartDesign::FeaturePrimitive::FeaturePrimitive(), App::GeoFeatureGroupExtension::initExtension(), Part::LocalCoordinateSystem::LocalCoordinateSystem(), Part::Part2DObject::Part2DObject(), Part::Primitive::Primitive(), Part::Prism::Prism(), PartDesign::Prism::Prism(), PartDesignGui::ViewProvider::ViewProvider(), PartDesignGui::ViewProviderBody::ViewProviderBody(), PartDesignGui::ViewProviderBoolean::ViewProviderBoolean(), PartDesignGui::ViewProviderDatum::ViewProviderDatum(), Gui::ViewProviderDocumentObjectGroup::ViewProviderDocumentObjectGroup(), FemGui::ViewProviderFemConstraint::ViewProviderFemConstraint(), FemGui::ViewProviderFemMesh::ViewProviderFemMesh(), Gui::ViewProviderGeoFeatureGroup::ViewProviderGeoFeatureGroup(), PartGui::ViewProviderLCS::ViewProviderLCS(), PartGui::ViewProviderLine::ViewProviderLine(), PartGui::ViewProviderPartExt::ViewProviderPartExt(), PartGui::ViewProviderPlane::ViewProviderPlane(), PartGui::ViewProviderPoint::ViewProviderPoint(), and SketcherGui::ViewProviderSketch::ViewProviderSketch().
initExtensionSubclass()
void Extension::initExtensionSubclass (Base::Type & toInit, const char * ClassName, const char * ParentName, Base::Type::instantiationMethod method = nullptr) static protected
Definition at line 184 of file Extension.cpp.
References Base::Type::badType(), OverlayParams::ClassName, Base::Type::createType(), and Base::Type::fromName().
initExtensionType()
void Extension::initExtensionType (Base::Type type) protected
Definition at line 80 of file Extension.cpp.
References Base::Type::isBad(), and Path.Post.scripts.grbl_post::type.
Referenced by PartGui::ViewProviderGridExtension::ViewProviderGridExtension().
isPythonExtension()
bool App::Extension::isPythonExtension () inline
Definition at line 264 of file Extension.h.
name()
std::string Extension::name () const
Definition at line 117 of file Extension.cpp.
References Base::Type::getName(), Base::Type::isBad(), and RobotExample::pos.
Referenced by extensionGetPropertyByName(), App::LinkBaseExtension::extensionGetPropertyByName(), extensionGetPropertyDocumentation(), extensionGetPropertyGroup(), extensionGetPropertyType(), App::GroupExtension::extensionGetSubObject(), App::GeoFeatureGroupExtension::extensionGetSubObject(), App::LinkBaseExtension::extensionGetSubObjects(), PartDesignGui::ViewProviderDressUp::featureName(), PartDesignGui::ViewProviderLinearPattern::featureName(), PartDesignGui::ViewProviderMultiTransform::featureName(), PartDesignGui::ViewProviderMirrored::featureName(), PartDesignGui::ViewProviderScaled::featureName(), PartDesignGui::ViewProviderPolarPattern::featureName(), Assembly::AssemblyObject::fixGroundedPart(), SketcherGui::ViewProviderSketch::generateContextMenu(), App::LinkBaseExtension::getElementIndex(), Assembly::AssemblyObject::getJointOfPartConnectingToGround(), App::LinkBaseExtension::getProperty(), PartDesign::Loft::getSectionShape(), Assembly::AssemblyObject::getUpstreamMovingPart(), Assembly::AssemblyObject::getUpstreamParts(), PartDesign::ProfileBased::handleChangedPropertyName(), Assembly::AssemblyObject::makeMbdMarker(), Assembly::AssemblyObject::makeMbdPart(), src.Mod.AddonManager.addonmanager_licenses.SPDXLicenseManager::normalize(), App::LinkBaseExtension::setLink(), App::LinkBaseExtension::setProperty(), TechDraw::DrawViewPart::unsetupObject(), and App::LinkBaseExtension::update().
Friends And Related Function Documentation
App::ExtensionContainer
friend class App::ExtensionContainer friend
Definition at line 315 of file Extension.h.
Member Data Documentation
ExtensionPythonObject
Py::SmartPtr App::Extension::ExtensionPythonObject protected
Definition at line 320 of file Extension.h.
Referenced by App::DocumentObjectExtension::getExtensionPyObject(), Gui::ViewProviderExtension::getExtensionPyObject(), App::GroupExtension::getExtensionPyObject(), getExtensionPyObject(), App::LinkBaseExtension::getExtensionPyObject(), and ~Extension().
m_isPythonExtension
bool App::Extension::m_isPythonExtension = false protected
Definition at line 319 of file Extension.h.
The documentation for this class was generated from the following files:
Extension.h
Extension.cpp