FreeCAD: MeshGui::SegmentationBestFit Class Reference
MeshGui::SegmentationBestFit Class Reference
#include <SegmentationBestFit.h>
Public Member Functions
SegmentationBestFit (Mesh::Feature *mesh, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~SegmentationBestFit () override
void accept ()
Protected Member Functions
void changeEvent (QEvent *e) override
Detailed Description
Definition at line 97 of file SegmentationBestFit.h.
Constructor & Destructor Documentation
SegmentationBestFit()
SegmentationBestFit::SegmentationBestFit (Mesh::Feature * mesh, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Definition at line 330 of file SegmentationBestFit.cpp.
References MeshGui::MeshSelection::setObjects().
~SegmentationBestFit()
SegmentationBestFit::~SegmentationBestFit () override
Definition at line 351 of file SegmentationBestFit.cpp.
Member Function Documentation
accept()
void SegmentationBestFit::accept ()
Definition at line 445 of file SegmentationBestFit.cpp.
References App::Document::addObject(), App::Document::commitTransaction(), MeshCore::MeshSegmentAlgorithm::FindSegments(), Mesh::PropertyMeshKernel::finishEditing(), App::Application::getActiveDocument(), App::GetApplication(), App::DocumentObject::getNameInDocument(), App::PropertyString::getValue(), Mesh::PropertyMeshKernel::getValuePtr(), toolbit-attributes::group, App::DocumentObject::Label, NavigationIndicatorGui::label, Mesh2Shape::mesh, Mesh::Feature::Mesh, App::Document::openTransaction(), buildPsets::p, App::PropertyString::setValue(), Mesh::PropertyMeshKernel::startEditing(), and Mesh::MeshObject::swap().
Referenced by MeshGui::TaskSegmentationBestFit::accept().
changeEvent()
void SegmentationBestFit::changeEvent (QEvent * e) override protected
Definition at line 532 of file SegmentationBestFit.cpp.
References SCL.SimpleDataTypes::e.
The documentation for this class was generated from the following files:
SegmentationBestFit.h
SegmentationBestFit.cpp