FreeCAD: importAirfoilDAT Namespace Reference
importAirfoilDAT Namespace Reference
DRAFT
Airfoil (.dat) file importer.
Functions
def translate (context, txt)
def open (filename)
def insert (filename, docname)
def process (filename)
Variables
useDraftWire
Detailed Description
Airfoil (.dat) file importer.
This module provides support for importing airfoil .dat files
Function Documentation
insert()
def importAirfoilDAT.insert (filename, docname)
Get an active document and parse.
If no document exists, it is created.
Parameters
----------
filename : str
    The path to the filename to be opened.
docname : str
    The name of the active App::Document if one exists, or
    of the new one created.
Returns
-------
App::Document
    The active FreeCAD document, or the document created if none exists,
    with the parsed information.
Definition at line 81 of file importAirfoilDAT.py.
References process().
open()
def importAirfoilDAT.open (filename)
Open filename and parse.
Parameters
----------
filename : str
    The path to the filename to be opened.
Returns
-------
App::Document
    The new FreeCAD document object created, with the parsed information.
Definition at line 61 of file importAirfoilDAT.py.
References process().
process()
def importAirfoilDAT.process (filename)
Process the filename and create a Draft Wire from the data.
The common airfoil dat format has many flavors.
This code should work with almost every dialect.
Parameters
----------
filename : str
    The path to the filename to be opened.
Returns
-------
Part::Part2DObject or None.
    The created Draft Wire object or None if the file contains less
    than 3 points.
Definition at line 112 of file importAirfoilDAT.py.
References src.Mod.AddonManager.NetworkManager.count.
Referenced by importers.importSH3DHelper.SH3DImporter.add_wall(), insert(), open(), processElements(), TechDraw::XMLQuery.processItems(), and Gui::Application.runApplication().
translate()
def importAirfoilDAT.translate (context, txt)
Definition at line 53 of file importAirfoilDAT.py.
Variable Documentation
useDraftWire
importAirfoilDAT.useDraftWire
Definition at line 58 of file importAirfoilDAT.py.