FreeCAD: Path.Post.scripts.generic_post.Generic Class Reference
Path.Post.scripts.generic_post.Generic Class Reference
Public Member Functions
def __init__ (self, job)
def export (self)
def tooltip (self)
def tooltipArgs (self)
def units (self)
Public Member Functions inherited from Path.Post.Processor.PostProcessor
def __init__ (self, job, tooltip, tooltipargs, units, *args, **kwargs)
def exists (cls, processor)
Detailed Description
Definition at line 40 of file generic_post.py.
Constructor & Destructor Documentation
__init__()
def Path.Post.scripts.generic_post.Generic.__init__ (self, job)
Definition at line 41 of file generic_post.py.
References Path.Log.debug().
Referenced by draftguitools.gui_subelements.SubelementHighlight.finish().
Member Function Documentation
export()
def Path.Post.scripts.generic_post.Generic.export (self)
Reimplemented from Path.Post.Processor.PostProcessor.
Definition at line 50 of file generic_post.py.
References Path.Post.Processor.PostProcessor._buildPostList(), and Path.Log.debug().
tooltip()
def Path.Post.scripts.generic_post.Generic.tooltip (self)
Get the tooltip text for the post processor.
Reimplemented from Path.Post.Processor.PostProcessor.
Definition at line 66 of file generic_post.py.
tooltipArgs()
def Path.Post.scripts.generic_post.Generic.tooltipArgs (self)
Get the tooltip arguments for the post processor.
Reimplemented from Path.Post.Processor.PostProcessor.
Definition at line 77 of file generic_post.py.
units()
def Path.Post.scripts.generic_post.Generic.units (self)
Get the units used by the post processor.
Reimplemented from Path.Post.Processor.PostProcessor.
Definition at line 86 of file generic_post.py.
References Path.Post.Processor.PostProcessor._units.
The documentation for this class was generated from the following file:
generic_post.py