FreeCAD: ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.person_and_organization_address Class Reference
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.person_and_organization_address Class Reference
Public Member Functions
def __init__ (self, inherited0__internal_location, inherited1__street_number, inherited2__street, inherited3__postal_box, inherited4__town, inherited5__region, inherited6__postal_code, inherited7__country, inherited8__facsimile_number, inherited9__telephone_number, inherited10__electronic_mail_address, inherited11__telex_number, inherited12__organizations, inherited13__description, inherited14__internal_location, inherited15__street_number, inherited16__street, inherited17__postal_box, inherited18__town, inherited19__region, inherited20__postal_code, inherited21__country, inherited22__facsimile_number, inherited23__telephone_number, inherited24__electronic_mail_address, inherited25__telex_number, inherited26__people, inherited27__description, organizational_address_organizations, personal_address_people)
def organizational_address_organizations ()
def personal_address_people ()
def wr1 (self)
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.organizational_address
def __init__ (self, inherited0__internal_location, inherited1__street_number, inherited2__street, inherited3__postal_box, inherited4__town, inherited5__region, inherited6__postal_code, inherited7__country, inherited8__facsimile_number, inherited9__telephone_number, inherited10__electronic_mail_address, inherited11__telex_number, organizations, description)
def organizations ()
def description ()
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.address
def __init__ (self, internal_location, street_number, street, postal_box, town, region, postal_code, country, facsimile_number, telephone_number, electronic_mail_address, telex_number)
def internal_location ()
def street_number ()
def street ()
def postal_box ()
def town ()
def region ()
def postal_code ()
def country ()
def facsimile_number ()
def telephone_number ()
def electronic_mail_address ()
def telex_number ()
def name ()
def url ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.personal_address
def __init__ (self, inherited0__internal_location, inherited1__street_number, inherited2__street, inherited3__postal_box, inherited4__town, inherited5__region, inherited6__postal_code, inherited7__country, inherited8__facsimile_number, inherited9__telephone_number, inherited10__electronic_mail_address, inherited11__telex_number, people, description)
def people ()
def description ()
Public Attributes
organizational_address_organizations
personal_address_people
Public Attributes inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.organizational_address
organizations
description
Public Attributes inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.address
internal_location
street_number
street
postal_box
town
region
postal_code
country
facsimile_number
telephone_number
electronic_mail_address
telex_number
Public Attributes inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.personal_address
people
description
Detailed Description
Entity person_and_organization_address definition.
:param organizational_address_organizations
:type organizational_address_organizations:SET(1,1,'organization', scope = schema_scope)
:param personal_address_people
:type personal_address_people:SET(1,1,'person', scope = schema_scope)
Definition at line 31585 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Constructor & Destructor Documentation
__init__()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.person_and_organization_address.__init__ (self, inherited0__internal_location, inherited1__street_number, inherited2__street, inherited3__postal_box, inherited4__town, inherited5__region, inherited6__postal_code, inherited7__country, inherited8__facsimile_number, inherited9__telephone_number, inherited10__electronic_mail_address, inherited11__telex_number, inherited12__organizations, inherited13__description, inherited14__internal_location, inherited15__street_number, inherited16__street, inherited17__postal_box, inherited18__town, inherited19__region, inherited20__postal_code, inherited21__country, inherited22__facsimile_number, inherited23__telephone_number, inherited24__electronic_mail_address, inherited25__telex_number, inherited26__people, inherited27__description, organizational_address_organizations, personal_address_people)
Definition at line 31594 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Member Function Documentation
organizational_address_organizations()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.person_and_organization_address.organizational_address_organizations ()
Definition at line 31601 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.person_and_organization_address._organizational_address_organizations, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.person_and_organization_address.organizational_address_organizations.
personal_address_people()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.person_and_organization_address.personal_address_people ()
Definition at line 31615 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.person_and_organization_address._personal_address_people, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.person_and_organization_address.personal_address_people.
wr1()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.person_and_organization_address.wr1 (self)
Reimplemented from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.address.
Definition at line 31627 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
Referenced by config_control_design.week_in_year_number.__init__(), config_control_design.minute_in_hour.__init__(), config_control_design.dimension_count.__init__(), config_control_design.positive_length_measure.__init__(), config_control_design.hour_in_day.__init__(), config_control_design.positive_plane_angle_measure.__init__(), ifc2x3.ifctextalignment.__init__(), config_control_design.day_in_week_number.__init__(), ifc4.ifctextalignment.__init__(), ifc2x3.ifcspecularroughness.__init__(), config_control_design.month_in_year_number.__init__(), ifc2x3.ifcheatingvaluemeasure.__init__(), config_control_design.second_in_minute.__init__(), ifc4.ifcspecularroughness.__init__(), automotive_design.minute_in_hour.__init__(), ifc2x3.ifctexttransformation.__init__(), ifc4.ifcheatingvaluemeasure.__init__(), automotive_design.non_negative_length_measure.__init__(), ifc4.ifctexttransformation.__init__(), automotive_design.u_direction_count.__init__(), automotive_design.dimension_count.__init__(), automotive_design.positive_length_measure.__init__(), automotive_design.hour_in_day.__init__(), automotive_design.v_direction_count.__init__(), ifc2x3.ifcfontstyle.__init__(), ifc2x3.ifcboxalignment.__init__(), ifc2x3.ifcminuteinhour.__init__(), automotive_design.day_in_month_number.__init__(), ifc4.ifcfontstyle.__init__(), automotive_design.positive_plane_angle_measure.__init__(), ifc2x3.ifcpositiveplaneanglemeasure.__init__(), ifc4.ifcboxalignment.__init__(), ifc2x3.ifcdimensioncount.__init__(), automotive_design.presentable_text.__init__(), ifc4.ifcpositiveplaneanglemeasure.__init__(), ifc4.ifcdimensioncount.__init__(), ifc2x3.ifcdaylightsavinghour.__init__(), automotive_design.positive_ratio_measure.__init__(), ifc2x3.ifcmonthinyearnumber.__init__(), ifc2x3.ifcsecondinminute.__init__(), ifc2x3.ifcfontvariant.__init__(), automotive_design.month_in_year_number.__init__(), ifc2x3.ifcfontweight.__init__(), ifc2x3.ifchourinday.__init__(), ifc2x3.ifcnormalisedratiomeasure.__init__(), automotive_design.second_in_minute.__init__(), ifc2x3.ifcpositivelengthmeasure.__init__(), ifc2x3.ifcpositiveratiomeasure.__init__(), ifc4.ifcfontvariant.__init__(), ifc4.ifcfontweight.__init__(), ifc2x3.ifctextdecoration.__init__(), ifc4.ifcnormalisedratiomeasure.__init__(), ifc4.ifcpositivelengthmeasure.__init__(), ifc4.ifcpositiveratiomeasure.__init__(), and ifc4.ifctextdecoration.__init__().
Member Data Documentation
organizational_address_organizations
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.person_and_organization_address.organizational_address_organizations
Definition at line 31597 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.person_and_organization_address.organizational_address_organizations().
personal_address_people
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.person_and_organization_address.personal_address_people
Definition at line 31598 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.person_and_organization_address.personal_address_people().
The documentation for this class was generated from the following file:
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py