FreeCAD: Inspection::InspectNominalPoints Class Reference
Inspection::InspectNominalPoints Class Reference
#include <InspectionFeature.h>
Public Member Functions
InspectNominalPoints (const Points::PointKernel &, float offset)
~InspectNominalPoints () override
float getDistance (const Base::Vector3f &) const override
Public Member Functions inherited from Inspection::InspectNominalGeometry
InspectNominalGeometry ()=default
virtual ~InspectNominalGeometry ()=default
Detailed Description
Definition at line 150 of file InspectionFeature.h.
Constructor & Destructor Documentation
InspectNominalPoints()
InspectNominalPoints::InspectNominalPoints (const Points::PointKernel & Kernel, float offset)
Definition at line 439 of file InspectionFeature.cpp.
~InspectNominalPoints()
InspectNominalPoints::~InspectNominalPoints () override
Definition at line 446 of file InspectionFeature.cpp.
Member Function Documentation
getDistance()
float InspectNominalPoints::getDistance (const Base::Vector3f & point) const override virtual
Implements Inspection::InspectNominalGeometry.
Definition at line 451 of file InspectionFeature.cpp.
References Base::Distance(), Points::PointsGrid::GetElements(), Points::PointKernel::getPoint(), Points::PointsGrid::Position(), MovieTool::x, and MovieTool::y.
The documentation for this class was generated from the following files:
InspectionFeature.h
InspectionFeature.cpp