FreeCAD: offset.cpp File Reference
offset.cpp File Reference
#include "geometry.h"
Classes
struct iso
Namespaces
geoff_geometry
Functions
static Kurve geoff_geometry::eliminateLoops (const Kurve &k, const Kurve &originalk, double offset, int &ret)
static bool geoff_geometry::DoesIntersInterfere (const Point &pInt, const Kurve &k, double offset)
static void isoRadius (Span &before, Span &blend, Span &after, double radius)
Variables
static struct iso isodata
Function Documentation
isoRadius()
static void isoRadius (Span & before, Span & blend, Span & after, double radius) static
Definition at line 394 of file offset.cpp.
References a, SCL.SimpleDataTypes::b, geoff_geometry::Span::dir, LINEAR, geoff_geometry::Span::Near(), geoff_geometry::Span::Offset(), geoff_geometry::Span::p0, geoff_geometry::Span::p1, geoff_geometry::Span::pc, geoff_geometry::Span::ve, and geoff_geometry::Span::vs.
Referenced by geoff_geometry::Kurve::OffsetISOMethod().
Variable Documentation
isodata
struct iso isodata static
Referenced by geoff_geometry::Kurve::OffsetISOMethod().