FreeCAD: Gui::TaskView::ControlPy Class Reference
Gui::TaskView::ControlPy Class Reference
#include <TaskDialogPython.h>
Public Member Functions
ControlPy ()
~ControlPy () override
Py::Object repr () override
Py::Object showDialog (const Py::Tuple &)
Py::Object activeDialog (const Py::Tuple &)
Py::Object activeTaskDialog (const Py::Tuple &)
Py::Object closeDialog (const Py::Tuple &)
Py::Object addTaskWatcher (const Py::Tuple &)
Py::Object clearTaskWatcher (const Py::Tuple &)
Py::Object isAllowedAlterDocument (const Py::Tuple &)
Py::Object isAllowedAlterView (const Py::Tuple &)
Py::Object isAllowedAlterSelection (const Py::Tuple &)
Py::Object showTaskView (const Py::Tuple &)
Py::Object showModelView (const Py::Tuple &)
Static Public Member Functions
static void init_type ()
static ControlPy * getInstance ()
Detailed Description
Definition at line 74 of file TaskDialogPython.h.
Constructor & Destructor Documentation
ControlPy()
ControlPy::ControlPy () default
Referenced by getInstance().
~ControlPy()
ControlPy::~ControlPy () override default
Member Function Documentation
activeDialog()
Py::Object ControlPy::activeDialog (const Py::Tuple & args)
Definition at line 126 of file TaskDialogPython.cpp.
References Gui::ControlSingleton::activeDialog(), toolbit-attributes::args, and Gui::Control().
Referenced by init_type().
activeTaskDialog()
Py::Object ControlPy::activeTaskDialog (const Py::Tuple & args)
Definition at line 134 of file TaskDialogPython.cpp.
References Gui::ControlSingleton::activeDialog(), toolbit-attributes::args, and Gui::Control().
Referenced by init_type().
addTaskWatcher()
Py::Object ControlPy::addTaskWatcher (const Py::Tuple & args)
Definition at line 150 of file TaskDialogPython.cpp.
References Gui::TaskView::TaskView::addTaskWatcher(), toolbit-attributes::args, Gui::Control(), Gui::ControlSingleton::taskPanel(), and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by init_type().
clearTaskWatcher()
Py::Object ControlPy::clearTaskWatcher (const Py::Tuple & args)
Definition at line 169 of file TaskDialogPython.cpp.
References toolbit-attributes::args, Gui::TaskView::TaskView::clearTaskWatcher(), Gui::Control(), and Gui::ControlSingleton::taskPanel().
Referenced by init_type().
closeDialog()
Py::Object ControlPy::closeDialog (const Py::Tuple & args)
Definition at line 142 of file TaskDialogPython.cpp.
References toolbit-attributes::args, Gui::ControlSingleton::closeDialog(), and Gui::Control().
Referenced by init_type().
getInstance()
ControlPy * ControlPy::getInstance () static
Definition at line 49 of file TaskDialogPython.cpp.
References ControlPy().
Referenced by Gui::Application::Application().
init_type()
void ControlPy::init_type () static
Definition at line 56 of file TaskDialogPython.cpp.
References activeDialog(), activeTaskDialog(), addTaskWatcher(), clearTaskWatcher(), closeDialog(), isAllowedAlterDocument(), isAllowedAlterSelection(), isAllowedAlterView(), showDialog(), showModelView(), and showTaskView().
Referenced by Gui::Application::Application().
isAllowedAlterDocument()
Py::Object ControlPy::isAllowedAlterDocument (const Py::Tuple & args)
Definition at line 179 of file TaskDialogPython.cpp.
References toolbit-attributes::args, Gui::Control(), and Gui::ControlSingleton::isAllowedAlterDocument().
Referenced by init_type().
isAllowedAlterSelection()
Py::Object ControlPy::isAllowedAlterSelection (const Py::Tuple & args)
Definition at line 195 of file TaskDialogPython.cpp.
References toolbit-attributes::args, Gui::Control(), and Gui::ControlSingleton::isAllowedAlterSelection().
Referenced by init_type().
isAllowedAlterView()
Py::Object ControlPy::isAllowedAlterView (const Py::Tuple & args)
Definition at line 187 of file TaskDialogPython.cpp.
References toolbit-attributes::args, Gui::Control(), and Gui::ControlSingleton::isAllowedAlterView().
Referenced by init_type().
repr()
Py::Object ControlPy::repr () override
Definition at line 105 of file TaskDialogPython.cpp.
References toolbit-attributes::s, and src.Mod.Test.testmakeWireString::String.
showDialog()
Py::Object ControlPy::showDialog (const Py::Tuple & args)
Definition at line 113 of file TaskDialogPython.cpp.
References Gui::ControlSingleton::activeDialog(), toolbit-attributes::args, Gui::Control(), and Gui::ControlSingleton::showDialog().
Referenced by init_type().
showModelView()
Py::Object ControlPy::showModelView (const Py::Tuple & args)
Definition at line 211 of file TaskDialogPython.cpp.
References toolbit-attributes::args, Gui::Control(), and Gui::ControlSingleton::showModelView().
Referenced by init_type().
showTaskView()
Py::Object ControlPy::showTaskView (const Py::Tuple & args)
Definition at line 203 of file TaskDialogPython.cpp.
References toolbit-attributes::args, Gui::Control(), and Gui::ControlSingleton::showTaskView().
Referenced by init_type().
The documentation for this class was generated from the following files:
TaskDialogPython.h
TaskDialogPython.cpp