FreeCAD: AdaptivePath Namespace Reference
AdaptivePath Namespace Reference
Classes
class BoundBox
class ClearedArea
class EngagePoint
class Interpolation
class PerfCounter
Functions
double DistanceSqrd (const IntPoint &pt1, const IntPoint &pt2)
bool SetSegmentLength (const IntPoint &pt1, IntPoint &pt2, double new_length)
bool HasAnyPath (const Paths &paths)
double averageDV (const vector< double > &vec)
DoublePoint rotate (const DoublePoint &in, double rad)
double PathLength (const Path &path)
double PointSideOfLine (const IntPoint &p1, const IntPoint &p2, const IntPoint &pt)
double Angle3Points (const DoublePoint &p1, const DoublePoint &p2, const DoublePoint &p3)
DoublePoint DirectionV (const IntPoint &pt1, const IntPoint &pt2)
void NormalizeV (DoublePoint &pt)
DoublePoint GetPathDirectionV (const Path &pth, size_t pointIndex)
bool isClose (const IntPoint &a, const IntPoint &b)
void filterCloseValues (Paths &ppg)
std::ostream & operator<< (std::ostream &s, const BoundBox &p)
int getPathNestingLevel (const Path &path, const Paths &paths)
void appendDirectChildPaths (Paths &outPaths, const Path &path, const Paths &paths)
void AverageDirection (const vector< DoublePoint > &unityVectors, DoublePoint &output)
double DistancePointToLineSegSquared (const IntPoint &p1, const IntPoint &p2, const IntPoint &pt, IntPoint &closestPoint, double &ptParameter, bool clamp=true)
void ScaleUpPaths (Paths &paths, long scaleFactor)
void ScaleDownPaths (Paths &paths, long scaleFactor)
double DistancePointToPathsSqrd (const Paths &paths, const IntPoint &pt, IntPoint &closestPointOnPath, size_t &clpPathIndex, size_t &clpSegmentIndex, double &clpParameter)
void CleanPath (const Path &inp, Path &outpt, double tolerance)
bool Circle2CircleIntersect (const IntPoint &c1, const IntPoint &c2, double radius, pair< DoublePoint, DoublePoint > &intersections)
bool Line2CircleIntersect (const IntPoint &c, double radius, const IntPoint &p1, const IntPoint &p2, vector< DoublePoint > &result, bool clamp=true)
IntPoint Compute2DPolygonCentroid (const Path &vertices)
bool IsPointWithinCutRegion (const Paths &toolBoundPaths, const IntPoint &point)
bool IntersectionPoint (const IntPoint &s1p1, const IntPoint &s1p2, const IntPoint &s2p1, const IntPoint &s2p2, IntPoint &intersection)
bool IntersectionPoint (const Paths &paths, const IntPoint &p1, const IntPoint &p2, IntPoint &intersection)
void SmoothPaths (Paths &paths, double stepSize, long pointCount, long iterations)
bool PopPathWithClosestPoint (Paths &paths, IntPoint p1, Path &result)
void DeduplicatePaths (const Paths &inputs, Paths &outputs)
void ConnectPaths (Paths input, Paths &output)
Variables
PerfCounter Perf_ProcessPolyNode ("ProcessPolyNode")
PerfCounter Perf_CalcCutAreaCirc ("CalcCutArea")
PerfCounter Perf_CalcCutAreaClip ("CalcCutAreaClip")
PerfCounter Perf_NextEngagePoint ("NextEngagePoint")
PerfCounter Perf_PointIterations ("PointIterations")
PerfCounter Perf_ExpandCleared ("ExpandCleared")
PerfCounter Perf_DistanceToBoundary ("DistanceToBoundary")
PerfCounter Perf_AppendToolPath ("AppendToolPath")
PerfCounter Perf_IsAllowedToCutTrough ("IsAllowedToCutTrough")
PerfCounter Perf_IsClearPath ("IsClearPath")
Function Documentation
Angle3Points()
double AdaptivePath::Angle3Points (const DoublePoint & p1, const DoublePoint & p2, const DoublePoint & p3) inline
Definition at line 114 of file Adaptive.cpp.
References a, KDL::atan2(), M_PI, KDL::min(), src.Mod.PartDesign.Scripts.Gear::t1, and src.Mod.PartDesign.Scripts.Gear::t2.
appendDirectChildPaths()
void AdaptivePath::appendDirectChildPaths (Paths & outPaths, const Path & path, const Paths & paths)
Definition at line 283 of file Adaptive.cpp.
References getPathNestingLevel(), and ClipperLib::PointInPolygon().
AverageDirection()
void AdaptivePath::AverageDirection (const vector< DoublePoint > & unityVectors, DoublePoint & output)
Definition at line 295 of file Adaptive.cpp.
References SplineSurface::i, KDL::sqrt(), and TestSpreadsheet::v.
averageDV()
double AdaptivePath::averageDV (const vector< double > & vec) inline
Definition at line 76 of file Adaptive.cpp.
References SplineSurface::i, toolbit-attributes::s, and SurfaceTests.TestBlendCurve::vec.
Circle2CircleIntersect()
bool AdaptivePath::Circle2CircleIntersect (const IntPoint & c1, const IntPoint & c2, double radius, pair< DoublePoint, DoublePoint > & intersections)
Definition at line 460 of file Adaptive.cpp.
References src.Mod.PartDesign.Scripts.Gear::c1, and KDL::sqrt().
CleanPath()
void AdaptivePath::CleanPath (const Path & inp, Path & outpt, double tolerance)
Definition at line 404 of file Adaptive.cpp.
References ClipperLib::CleanPolygon(), DistancePointToPathsSqrd(), DistanceSqrd(), SplineSurface::i, OpenSCADFeatures::long, SAME_POINT_TOL_SQRD_SCALED, and draftutils.utils::tolerance().
Referenced by SmoothPaths().
Compute2DPolygonCentroid()
IntPoint AdaptivePath::Compute2DPolygonCentroid (const Path & vertices)
Definition at line 531 of file Adaptive.cpp.
References a, SplineSurface::i, DrawingExample::X, and DrawingExample::Y.
ConnectPaths()
void AdaptivePath::ConnectPaths (Paths input, Paths & output)
Definition at line 834 of file Adaptive.cpp.
References DistanceSqrd(), SplineSurface::i, ClipperLib::ReversePath(), and SAME_POINT_TOL_SQRD_SCALED.
DeduplicatePaths()
void AdaptivePath::DeduplicatePaths (const Paths & inputs, Paths & outputs)
Definition at line 801 of file Adaptive.cpp.
References DistanceSqrd(), and SAME_POINT_TOL_SQRD_SCALED.
DirectionV()
DoublePoint AdaptivePath::DirectionV (const IntPoint & pt1, const IntPoint & pt2) inline
Definition at line 122 of file Adaptive.cpp.
References RobotExample::l, and KDL::sqrt().
Referenced by GetPathDirectionV().
DistancePointToLineSegSquared()
double AdaptivePath::DistancePointToLineSegSquared (const IntPoint & p1, const IntPoint & p2, const IntPoint & pt, IntPoint & closestPoint, double & ptParameter, bool clamp = true)
Definition at line 312 of file Adaptive.cpp.
References Base::clamp(), and OpenSCADFeatures::long.
Referenced by DistancePointToPathsSqrd().
DistancePointToPathsSqrd()
double AdaptivePath::DistancePointToPathsSqrd (const Paths & paths, const IntPoint & pt, IntPoint & closestPointOnPath, size_t & clpPathIndex, size_t & clpSegmentIndex, double & clpParameter)
Definition at line 370 of file Adaptive.cpp.
References DistancePointToLineSegSquared(), and SplineSurface::i.
Referenced by CleanPath().
DistanceSqrd()
double AdaptivePath::DistanceSqrd (const IntPoint & pt1, const IntPoint & pt2) inline
Definition at line 46 of file Adaptive.cpp.
Referenced by CleanPath(), ConnectPaths(), DeduplicatePaths(), AdaptivePath::EngagePoint::getCurrentDir(), AdaptivePath::EngagePoint::getCurrentPoint(), AdaptivePath::EngagePoint::moveToClosestPoint(), PathLength(), PopPathWithClosestPoint(), and SmoothPaths().
filterCloseValues()
void AdaptivePath::filterCloseValues (Paths & ppg)
Definition at line 159 of file Adaptive.cpp.
References SplineSurface::i, and isClose().
GetPathDirectionV()
DoublePoint AdaptivePath::GetPathDirectionV (const Path & pth, size_t pointIndex) inline
Definition at line 142 of file Adaptive.cpp.
References DirectionV().
getPathNestingLevel()
int AdaptivePath::getPathNestingLevel (const Path & path, const Paths & paths)
Definition at line 272 of file Adaptive.cpp.
References ClipperLib::PointInPolygon().
Referenced by appendDirectChildPaths().
HasAnyPath()
bool AdaptivePath::HasAnyPath (const Paths & paths) inline
Definition at line 66 of file Adaptive.cpp.
References SplineSurface::i.
IntersectionPoint() [1/2]
bool AdaptivePath::IntersectionPoint (const IntPoint & s1p1, const IntPoint & s1p2, const IntPoint & s2p1, const IntPoint & s2p2, IntPoint & intersection)
Definition at line 577 of file Adaptive.cpp.
References intersection(), and InitGui::t.
IntersectionPoint() [2/2]
bool AdaptivePath::IntersectionPoint (const Paths & paths, const IntPoint & p1, const IntPoint & p2, IntPoint & intersection)
Definition at line 608 of file Adaptive.cpp.
References AdaptivePath::BoundBox::AddPoint(), AdaptivePath::BoundBox::CollidesWith(), SplineSurface::i, intersection(), and InitGui::t.
isClose()
bool AdaptivePath::isClose (const IntPoint & a, const IntPoint & b)
Definition at line 153 of file Adaptive.cpp.
References a, KDL::abs(), and SCL.SimpleDataTypes::b.
Referenced by filterCloseValues().
IsPointWithinCutRegion()
bool AdaptivePath::IsPointWithinCutRegion (const Paths & toolBoundPaths, const IntPoint & point)
Definition at line 562 of file Adaptive.cpp.
References SplineSurface::i, and ClipperLib::PointInPolygon().
Line2CircleIntersect()
bool AdaptivePath::Line2CircleIntersect (const IntPoint & c, double radius, const IntPoint & p1, const IntPoint & p2, vector< DoublePoint > & result, bool clamp = true)
Definition at line 482 of file Adaptive.cpp.
References a, SCL.SimpleDataTypes::b, RobotExample::C, SCL.SimpleDataTypes::c, Base::clamp(), AdaptivePath::BoundBox::CollidesWith(), result, KDL::sqrt(), src.Mod.PartDesign.Scripts.Gear::t1, and src.Mod.PartDesign.Scripts.Gear::t2.
NormalizeV()
void AdaptivePath::NormalizeV (DoublePoint & pt) inline
Definition at line 133 of file Adaptive.cpp.
References KDL::sqrt().
operator<<()
std::ostream& AdaptivePath::operator<< (std::ostream & s, const BoundBox & p)
Definition at line 266 of file Adaptive.cpp.
References buildPsets::p, and toolbit-attributes::s.
PathLength()
double AdaptivePath::PathLength (const Path & path) inline
Definition at line 97 of file Adaptive.cpp.
References DistanceSqrd(), SplineSurface::i, and KDL::sqrt().
PointSideOfLine()
double AdaptivePath::PointSideOfLine (const IntPoint & p1, const IntPoint & p2, const IntPoint & pt) inline
Definition at line 109 of file Adaptive.cpp.
PopPathWithClosestPoint()
bool AdaptivePath::PopPathWithClosestPoint (Paths & paths, IntPoint p1, Path & result)
Definition at line 760 of file Adaptive.cpp.
References DraftVecUtils::dist(), DistanceSqrd(), SplineSurface::i, OpenSCADFeatures::long, and result.
Referenced by AdaptivePath::EngagePoint::moveToClosestPoint().
rotate()
DoublePoint AdaptivePath::rotate (const DoublePoint & in, double rad) inline
Definition at line 89 of file Adaptive.cpp.
References SCL.SimpleDataTypes::c, KDL::cos(), toolbit-attributes::s, and KDL::sin().
ScaleDownPaths()
void AdaptivePath::ScaleDownPaths (Paths & paths, long scaleFactor)
Definition at line 359 of file Adaptive.cpp.
Referenced by SmoothPaths().
ScaleUpPaths()
void AdaptivePath::ScaleUpPaths (Paths & paths, long scaleFactor)
Definition at line 349 of file Adaptive.cpp.
Referenced by SmoothPaths().
SetSegmentLength()
bool AdaptivePath::SetSegmentLength (const IntPoint & pt1, IntPoint & pt2, double new_length) inline
Definition at line 53 of file Adaptive.cpp.
References RobotExample::l, OpenSCADFeatures::long, and KDL::sqrt().
SmoothPaths()
void AdaptivePath::SmoothPaths (Paths & paths, double stepSize, long pointCount, long iterations)
Definition at line 659 of file Adaptive.cpp.
References CleanPath(), DistanceSqrd(), SplineSurface::i, RobotExample::l, OpenSCADFeatures::long, KDL::max(), buildPsets::p, draftfunctions.scale::scale(), ScaleDownPaths(), ScaleUpPaths(), and KDL::sqrt().
Variable Documentation
Perf_AppendToolPath
PerfCounter AdaptivePath::Perf_AppendToolPath("AppendToolPath")
Perf_CalcCutAreaCirc
PerfCounter AdaptivePath::Perf_CalcCutAreaCirc("CalcCutArea")
Perf_CalcCutAreaClip
PerfCounter AdaptivePath::Perf_CalcCutAreaClip("CalcCutAreaClip")
Perf_DistanceToBoundary
PerfCounter AdaptivePath::Perf_DistanceToBoundary("DistanceToBoundary")
Perf_ExpandCleared
PerfCounter AdaptivePath::Perf_ExpandCleared("ExpandCleared")
Referenced by AdaptivePath::ClearedArea::ExpandCleared().
Perf_IsAllowedToCutTrough
PerfCounter AdaptivePath::Perf_IsAllowedToCutTrough("IsAllowedToCutTrough")
Perf_IsClearPath
PerfCounter AdaptivePath::Perf_IsClearPath("IsClearPath")
Perf_NextEngagePoint
PerfCounter AdaptivePath::Perf_NextEngagePoint("NextEngagePoint")
Referenced by AdaptivePath::EngagePoint::nextEngagePoint().
Perf_PointIterations
PerfCounter AdaptivePath::Perf_PointIterations("PointIterations")
Perf_ProcessPolyNode
PerfCounter AdaptivePath::Perf_ProcessPolyNode("ProcessPolyNode")