FreeCAD: SIM::Coin3D::Quarter::SignalThread Class Reference
SIM::Coin3D::Quarter::SignalThread Class Reference
#include <SignalThread.h>
Signals
void triggerSignal ()
Public Member Functions
SignalThread ()
~SignalThread () override
void run () override
void trigger ()
void stopThread ()
Detailed Description
Definition at line 45 of file SignalThread.h.
Constructor & Destructor Documentation
SignalThread()
SignalThread::SignalThread ()
Definition at line 39 of file SignalThread.cpp.
~SignalThread()
SignalThread::~SignalThread () override
Definition at line 44 of file SignalThread.cpp.
Member Function Documentation
run()
void SignalThread::run () override
Definition at line 66 of file SignalThread.cpp.
References triggerSignal().
Referenced by femexamples.examplesgui.FemExamples::clicked(), and femsolver.task.Task::protector().
stopThread()
void SignalThread::stopThread ()
Definition at line 57 of file SignalThread.cpp.
Referenced by SIM::Coin3D::Quarter::SensorManager::~SensorManager().
trigger()
void SignalThread::trigger ()
Definition at line 49 of file SignalThread.cpp.
triggerSignal
void SIM::Coin3D::Quarter::SignalThread::triggerSignal () signal
Referenced by run(), and SIM::Coin3D::Quarter::SensorManager::SensorManager().
The documentation for this class was generated from the following files:
SignalThread.h
SignalThread.cpp