FreeCAD: TechDrawGui::DlgPrefsTechDrawAnnotationImp Class Reference
TechDrawGui::DlgPrefsTechDrawAnnotationImp Class Reference
#include <DlgPrefsTechDrawAnnotationImp.h>
Public Slots
void onLineGroupChanged (int)
void onLineStandardChanged (int)
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Public Member Functions
DlgPrefsTechDrawAnnotationImp (QWidget *parent=nullptr)
~DlgPrefsTechDrawAnnotationImp () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void saveSettings () override
void loadSettings () override
void changeEvent (QEvent *e) override
int prefBalloonArrow () const
int prefBalloonShape () const
int prefMattingStyle () const
void loadLineStyleBoxes ()
fill the various line style comboboxes
Detailed Description
Definition at line 39 of file DlgPrefsTechDrawAnnotationImp.h.
Constructor & Destructor Documentation
DlgPrefsTechDrawAnnotationImp()
DlgPrefsTechDrawAnnotationImp::DlgPrefsTechDrawAnnotationImp (QWidget * parent = nullptr) explicit
Definition at line 44 of file DlgPrefsTechDrawAnnotationImp.cpp.
References draftgeoutils.intersections::connect(), Base::Unit::Length, onLineGroupChanged(), and onLineStandardChanged().
~DlgPrefsTechDrawAnnotationImp()
DlgPrefsTechDrawAnnotationImp::~DlgPrefsTechDrawAnnotationImp () override
Definition at line 79 of file DlgPrefsTechDrawAnnotationImp.cpp.
Member Function Documentation
changeEvent()
void DlgPrefsTechDrawAnnotationImp::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 196 of file DlgPrefsTechDrawAnnotationImp.cpp.
References SCL.SimpleDataTypes::e.
loadLineStyleBoxes()
void DlgPrefsTechDrawAnnotationImp::loadLineStyleBoxes () protected
fill the various line style comboboxes
Definition at line 264 of file DlgPrefsTechDrawAnnotationImp.cpp.
References TechDrawGui::DrawGuiUtil::loadLineStyleChoices().
Referenced by loadSettings(), and onLineStandardChanged().
loadSettings()
void DlgPrefsTechDrawAnnotationImp::loadSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 133 of file DlgPrefsTechDrawAnnotationImp.cpp.
References TechDrawGui::DrawGuiUtil::loadArrowBox(), TechDrawGui::DrawGuiUtil::loadBalloonShapeBox(), TechDrawGui::DrawGuiUtil::loadLineGroupChoices(), TechDrawGui::DrawGuiUtil::loadLineStandardsChoices(), loadLineStyleBoxes(), TechDrawGui::DrawGuiUtil::loadMattingStyleBox(), prefBalloonArrow(), prefBalloonShape(), and prefMattingStyle().
onLineGroupChanged
void DlgPrefsTechDrawAnnotationImp::onLineGroupChanged (int index) slot
Updates the tooltip of the LineGroup combobox
Definition at line 228 of file DlgPrefsTechDrawAnnotationImp.cpp.
References importOCA::getline().
Referenced by DlgPrefsTechDrawAnnotationImp().
onLineStandardChanged
void DlgPrefsTechDrawAnnotationImp::onLineStandardChanged (int index) slot
we must set the current line group preference when it changes so that the line style comboboxes are filled for the correct standard.
Definition at line 252 of file DlgPrefsTechDrawAnnotationImp.cpp.
References loadLineStyleBoxes(), and TechDraw::LineGenerator::reloadDescriptions().
Referenced by DlgPrefsTechDrawAnnotationImp().
prefBalloonArrow()
int DlgPrefsTechDrawAnnotationImp::prefBalloonArrow () const protected
Definition at line 210 of file DlgPrefsTechDrawAnnotationImp.cpp.
Referenced by loadSettings().
prefBalloonShape()
int DlgPrefsTechDrawAnnotationImp::prefBalloonShape () const protected
Definition at line 215 of file DlgPrefsTechDrawAnnotationImp.cpp.
Referenced by loadSettings().
prefMattingStyle()
int DlgPrefsTechDrawAnnotationImp::prefMattingStyle () const protected
Definition at line 220 of file DlgPrefsTechDrawAnnotationImp.cpp.
Referenced by loadSettings().
saveSettings()
void DlgPrefsTechDrawAnnotationImp::saveSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 85 of file DlgPrefsTechDrawAnnotationImp.cpp.
The documentation for this class was generated from the following files:
DlgPrefsTechDrawAnnotationImp.h
DlgPrefsTechDrawAnnotationImp.cpp