FreeCAD: GCS::Circle Class Reference
GCS::Circle Class Reference
#include <Geo.h>
Public Member Functions
Circle ()
~Circle () override
DeriVector2 CalculateNormal (const Point &p, const double *derivparam=nullptr) const override
DeriVector2 Value (double u, double du, const double *derivparam=nullptr) const override
Value: returns point (vector) given the value of parameter.
int PushOwnParams (VEC_pD &pvec) override
void ReconstructOnNewPvec (VEC_pD &pvec, int &cnt) override
Circle * Copy () override
Public Member Functions inherited from GCS::Curve
virtual ~Curve ()
virtual DeriVector2 CalculateNormal (const double *param, const double *derivparam=nullptr) const
Public Attributes
Point center
double * rad
Detailed Description
Definition at line 234 of file Geo.h.
Constructor & Destructor Documentation
Circle()
GCS::Circle::Circle () inline
Definition at line 237 of file Geo.h.
Referenced by Copy().
~Circle()
GCS::Circle::~Circle () inline override
Definition at line 241 of file Geo.h.
Member Function Documentation
CalculateNormal()
DeriVector2 Circle::CalculateNormal (const Point & p, const double * derivparam = nullptr) const override virtual
Implements GCS::Curve.
Definition at line 184 of file Geo.cpp.
References center, buildPsets::p, and GCS::DeriVector2::subtr().
Copy()
Circle * Circle::Copy () override virtual
Implements GCS::Curve.
Reimplemented in GCS::Arc.
Definition at line 228 of file Geo.cpp.
References Circle().
PushOwnParams()
int Circle::PushOwnParams (VEC_pD & pvec) override virtual
Implements GCS::Curve.
Reimplemented in GCS::Arc.
Definition at line 208 of file Geo.cpp.
References center, rad, GCS::Point::x, and GCS::Point::y.
Referenced by GCS::ConstraintC2CDistance::ConstraintC2CDistance(), and GCS::Arc::PushOwnParams().
ReconstructOnNewPvec()
void Circle::ReconstructOnNewPvec (VEC_pD & pvec, int & cnt) override virtual
Implements GCS::Curve.
Reimplemented in GCS::Arc.
Definition at line 219 of file Geo.cpp.
References center, rad, GCS::Point::x, and GCS::Point::y.
Referenced by GCS::Arc::ReconstructOnNewPvec().
Value()
DeriVector2 Circle::Value (double u, double du, const double * derivparam = nullptr) const override virtual
Value: returns point (vector) given the value of parameter.
Parameters
u value of parameter
du derivative of parameter by derivparam
derivparam pointer to sketch parameter to calculate the derivative for
Returns
Reimplemented from GCS::Curve.
Definition at line 192 of file Geo.cpp.
References center, KDL::cos(), GCS::DeriVector2::multD(), rad, GCS::DeriVector2::rotate90ccw(), KDL::sin(), GCS::DeriVector2::sum(), and buildPsets::u.
Member Data Documentation
center
Point GCS::Circle::center
Definition at line 243 of file Geo.h.
Referenced by GCS::System::addConstraintTangent(), CalculateNormal(), Path.Dressup.Gui.AxisMap.ObjectDressup::execute(), Path.Dressup.Gui.AxisMap.ObjectDressup::onChanged(), PushOwnParams(), ReconstructOnNewPvec(), and Value().
rad
double* GCS::Circle::rad
Definition at line 244 of file Geo.h.
Referenced by GCS::System::addConstraintEqualRadius(), GCS::System::addConstraintTangent(), PushOwnParams(), ReconstructOnNewPvec(), and Value().
The documentation for this class was generated from the following files:
Geo.h
Geo.cpp