FreeCAD: Points::PointsAlgos Class Reference
Points::PointsAlgos Class Reference
#include <PointsAlgos.h>
Static Public Member Functions
static void Load (PointKernel &, const char *FileName)
static void LoadAscii (PointKernel &, const char *FileName)
Detailed Description
The Points algorithms container class
Definition at line 57 of file PointsAlgos.h.
Member Function Documentation
Load()
void PointsAlgos::Load (PointKernel & points, const char * FileName) static
Load a point cloud
Definition at line 50 of file PointsAlgos.cpp.
References Base::FileInfo::hasExtension(), Base::FileInfo::isReadable(), and LoadAscii().
Referenced by Points::PointKernel::load().
LoadAscii()
void PointsAlgos::LoadAscii (PointKernel & points, const char * FileName) static
Load a point cloud
Definition at line 67 of file PointsAlgos.cpp.
References Points::PointKernel::clear(), Points::PointKernel::erase(), DrawingExample::file, importOCA::getline(), Base::SequencerLauncher::next(), Points::PointKernel::resize(), Points::PointKernel::setPoint(), Points::PointKernel::size(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by Load().
The documentation for this class was generated from the following files:
PointsAlgos.h
PointsAlgos.cpp