FreeCAD: feminout.importCcxFrdResults Namespace Reference
feminout.importCcxFrdResults Namespace Reference
Functions
def open (filename)
def insert (filename, docname)
def importFrd (filename, analysis=None, result_name_prefix="", result_analysis_type="")
def read_frd_result (frd_input)
Function Documentation
importFrd()
def feminout.importCcxFrdResults.importFrd (filename, analysis = None, result_name_prefix = "", result_analysis_type = "")
Definition at line 61 of file importCcxFrdResults.py.
References ObjectsFem.makeMeshResult(), ObjectsFem.makePostVtkResult(), ObjectsFem.makeResultMechanical(), feminout.importCcxFrdResults.read_frd_result(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by feminout.importCcxFrdResults.insert().
insert()
def feminout.importCcxFrdResults.insert (filename, docname)
Definition at line 50 of file importCcxFrdResults.py.
References feminout.importCcxFrdResults.importFrd().
Referenced by feminout.importCcxFrdResults.open().
open()
def feminout.importCcxFrdResults.open (filename)
Definition at line 44 of file importCcxFrdResults.py.
References feminout.importCcxFrdResults.insert().
read_frd_result()
def feminout.importCcxFrdResults.read_frd_result (frd_input)
Definition at line 252 of file importCcxFrdResults.py.
Referenced by feminout.importCcxFrdResults.importFrd().