FreeCAD: Tools.cpp File Reference
Mod/Part/App/Tools.cpp File Reference
#include "PreCompiled.h"
#include <cassert>
#include <BRep_Tool.hxx>
#include <BRepAdaptor_Curve.hxx>
#include <BRepAdaptor_Surface.hxx>
#include <BRepBuilderAPI_MakeEdge.hxx>
#include <BRepBuilderAPI_MakeFace.hxx>
#include <BRepIntCurveSurface_Inter.hxx>
#include <BRepLProp_SLProps.hxx>
#include <BRepMesh_IncrementalMesh.hxx>
#include <CSLib.hxx>
#include <Geom_BSplineSurface.hxx>
#include <Geom_Line.hxx>
#include <Geom_Plane.hxx>
#include <Geom_Point.hxx>
#include <GeomAPI_IntSS.hxx>
#include <GeomAPI_ProjectPointOnSurf.hxx>
#include <GeomAdaptor_Curve.hxx>
#include <GeomLib.hxx>
#include <GeomLProp_SLProps.hxx>
#include <GeomPlate_BuildPlateSurface.hxx>
#include <GeomPlate_CurveConstraint.hxx>
#include <GeomPlate_MakeApprox.hxx>
#include <GeomPlate_PlateG0Criterion.hxx>
#include <GeomPlate_PointConstraint.hxx>
#include <gp_Lin.hxx>
#include <gp_Pln.hxx>
#include <gp_Quaternion.hxx>
#include <Poly_Connect.hxx>
#include <Poly_Triangulation.hxx>
#include <Precision.hxx>
#include <Standard_Mutex.hxx>
#include <Standard_TypeMismatch.hxx>
#include <Standard_Version.hxx>
#include <TColStd_ListIteratorOfListOfTransient.hxx>
#include <TColStd_ListOfTransient.hxx>
#include <TColgp_SequenceOfXY.hxx>
#include <TColgp_SequenceOfXYZ.hxx>
#include <TopoDS.hxx>
#include <Adaptor3d_HCurveOnSurface.hxx>
#include <GeomAdaptor_HCurve.hxx>
#include <Base/Exception.h>
#include <Base/Vector3D.h>
#include "Tools.h"
Functions
Handle (Geom_Surface) Part
Handle (Poly_Triangulation) Part
Handle (Poly_Polygon3D) Part
template<typename T >
void getNormalBySLProp (T &prop, double u, double v, Standard_Real lastU, Standard_Real lastV, const Standard_Real tol, gp_Dir &dir, Standard_Boolean &done)
Function Documentation
getNormalBySLProp()
template<typename T > void getNormalBySLProp (T & prop, double u, double v, Standard_Real lastU, Standard_Real lastV, const Standard_Real tol, gp_Dir & dir, Standard_Boolean & done)
Definition at line 686 of file Mod/Part/App/Tools.cpp.
References ClipperLib::Abs(), geoff_geometry::Normal(), buildPsets::u, and TestSpreadsheet::v.
Handle() [1/3]
Handle (Geom_Surface)
The objects in theBoundaries must be of the type Adaptor3d_HCurveOnSurface or GeomAdaptor_HCurve or Geom_Point indicating type of a constraint. Otherwise an exception Standard_TypeMismatch is thrown.
If the theBoundaries list is empty then Standard_ConstructionError is thrown.
If the algorithm fails it returns a null surface.
See also
http://opencascade.blogspot.com/2010/03/surface-modeling-part6.html
Definition at line 133 of file Mod/Part/App/Tools.cpp.
References Part::Tools::Handle(), SplineSurface::i, Part::Tools::theMaxDeg, Part::Tools::theNbIter, Part::Tools::theNbPnts, and Part::Tools::theTol.
Referenced by Part::Tools::getPointNormals(), Part::Tools::getPolygon3D(), Part::Tools::getPolygonOnTriangulation(), Part::Tools::getTriangulation(), Handle(), Part::intersect(), and Part::Tools::isConcave().
Handle() [2/3]
Handle (Poly_Polygon3D)
Definition at line 656 of file Mod/Part/App/Tools.cpp.
References Handle(), src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::inv(), KDL::max(), KDL::min(), buildPsets::u, and TestSpreadsheet::v.
Handle() [3/3]
Handle (Poly_Triangulation)
Definition at line 607 of file Mod/Part/App/Tools.cpp.
References FC_THROWM, Handle(), Mesh2Shape::mesh, and draftgeoutils.general::v1().