FreeCAD: PartDesignGui::TaskChamferParameters Class Reference
PartDesignGui::TaskChamferParameters Class Reference
#include <TaskChamferParameters.h>
Public Member Functions
TaskChamferParameters (ViewProviderDressUp *DressUpView, QWidget *parent=nullptr)
~TaskChamferParameters () override
void apply () override
Apply the changes made to the object to it.
Public Member Functions inherited from PartDesignGui::TaskDressUpParameters
TaskDressUpParameters (ViewProviderDressUp *DressUpView, bool selectEdges, bool selectFaces, QWidget *parent=nullptr)
~TaskDressUpParameters () override
const std::vector< std::string > getReferences () const
Part::Feature * getBase () const
void hideObject ()
void showObject ()
void setupTransaction ()
int getTransactionID () const
bool event (QEvent *event) override
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Protected Member Functions
void setButtons (const selectionModes mode) override
void changeEvent (QEvent *e) override
void onSelectionChanged (const Gui::SelectionChanges &msg) override
int getType () const
double getSize () const
double getSize2 () const
double getAngle () const
bool getFlipDirection () const
Protected Member Functions inherited from PartDesignGui::TaskDressUpParameters
void referenceSelected (const Gui::SelectionChanges &msg, QListWidget *widget)
void keyPressEvent (QKeyEvent *ke) override
void hideOnError ()
void addAllEdges (QListWidget *listWidget)
void deleteRef (QListWidget *listWidget)
void updateFeature (PartDesign::DressUp *pcDressUp, const std::vector< std::string > &refs)
void setSelectionMode (selectionModes mode)
ViewProviderDressUp * getDressUpView () const
template<typename T = App::DocumentObject>
T * getObject () const
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Protected Types inherited from PartDesignGui::TaskDressUpParameters
enum selectionModes { none, refSel, plane, line }
Protected Slots inherited from PartDesignGui::TaskDressUpParameters
void onButtonRefSel (const bool checked)
void doubleClicked (QListWidgetItem *item)
void setSelection (QListWidgetItem *current)
void itemClickedTimeout ()
virtual void onRefDeleted ()=0
void createDeleteAction (QListWidget *parentList)
void createAddAllEdgesAction (QListWidget *parentList)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Static Protected Member Functions inherited from PartDesignGui::TaskDressUpParameters
static void removeItemFromListWidget (QListWidget *widget, const char *itemstr)
static const QString btnPreviewStr ()
static const QString btnSelectStr ()
Protected Attributes inherited from PartDesignGui::TaskDressUpParameters
bool wasDoubleClicked = false
QWidget * proxy
QAction * deleteAction
QAction * addAllEdgesAction
bool allowFaces
bool allowEdges
selectionModes selectionMode
int transactionID
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
Definition at line 37 of file TaskChamferParameters.h.
Constructor & Destructor Documentation
TaskChamferParameters()
TaskChamferParameters::TaskChamferParameters (ViewProviderDressUp * DressUpView, QWidget * parent = nullptr) explicit
Definition at line 50 of file TaskChamferParameters.cpp.
References PartDesignGui::TaskDressUpParameters::addAllEdgesAction, PartDesign::DressUp::Base, draftgeoutils.intersections::connect(), PartDesignGui::TaskDressUpParameters::createAddAllEdgesAction(), PartDesignGui::TaskDressUpParameters::createDeleteAction(), PartDesignGui::TaskDressUpParameters::deleteAction, PartDesignGui::TaskDressUpParameters::doubleClicked(), Gui::ViewProviderDocumentObject::getObject(), App::PropertyLinkSub::getSubValues(), App::PropertyBool::getValue(), QSint::ActionGroup::groupLayout(), PartDesignGui::TaskDressUpParameters::hideOnError(), PartDesignGui::TaskDressUpParameters::onButtonRefSel(), PartDesignGui::TaskDressUpParameters::proxy, PartDesignGui::TaskDressUpParameters::refSel, PartDesignGui::TaskDressUpParameters::setSelection(), PartDesignGui::TaskDressUpParameters::setSelectionMode(), PartDesign::Chamfer::UseAllEdges, and Gui::QuantitySpinBox::valueChanged().
~TaskChamferParameters()
TaskChamferParameters::~TaskChamferParameters () override
Definition at line 284 of file TaskChamferParameters.cpp.
References Gui::SelectionSingleton::clearSelection(), SCL.SimpleDataTypes::e, Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
apply()
void TaskChamferParameters::apply () override virtual
Apply the changes made to the object to it.
Reimplemented from PartDesignGui::TaskDressUpParameters.
Definition at line 304 of file TaskChamferParameters.cpp.
References Base::Console(), and Base::ConsoleSingleton::Warning().
changeEvent()
void TaskChamferParameters::changeEvent (QEvent * e) override protected
Definition at line 296 of file TaskChamferParameters.cpp.
References SCL.SimpleDataTypes::e, and PartDesignGui::TaskDressUpParameters::proxy.
getAngle()
double TaskChamferParameters::getAngle () const protected
Definition at line 274 of file TaskChamferParameters.cpp.
getFlipDirection()
bool TaskChamferParameters::getFlipDirection () const protected
Definition at line 279 of file TaskChamferParameters.cpp.
getSize()
double TaskChamferParameters::getSize () const protected
Definition at line 264 of file TaskChamferParameters.cpp.
getSize2()
double TaskChamferParameters::getSize2 () const protected
Definition at line 269 of file TaskChamferParameters.cpp.
getType()
int TaskChamferParameters::getType () const protected
Definition at line 259 of file TaskChamferParameters.cpp.
onSelectionChanged()
void TaskChamferParameters::onSelectionChanged (const Gui::SelectionChanges & msg) override protected virtual
Implements Gui::SelectionObserver.
Definition at line 156 of file TaskChamferParameters.cpp.
References Gui::SelectionChanges::AddSelection, Path.Op.Surface::msg, PartDesignGui::TaskDressUpParameters::referenceSelected(), PartDesignGui::TaskDressUpParameters::refSel, and PartDesignGui::TaskDressUpParameters::selectionMode.
setButtons()
void TaskChamferParameters::setButtons (const selectionModes mode) override protected virtual
Implements PartDesignGui::TaskDressUpParameters.
Definition at line 182 of file TaskChamferParameters.cpp.
References PartDesignGui::TaskDressUpParameters::btnPreviewStr(), PartDesignGui::TaskDressUpParameters::btnSelectStr(), and PartDesignGui::TaskDressUpParameters::refSel.
The documentation for this class was generated from the following files:
TaskChamferParameters.h
TaskChamferParameters.cpp