FreeCAD: MeshCore::MeshRefPointToFacets Class Reference
MeshCore::MeshRefPointToFacets Class Reference
#include <Algorithm.h>
Public Member Functions
MeshRefPointToFacets (const MeshKernel &rclM)
Construction.
void Rebuild ()
Rebuilds up data structure.
const std::set< FacetIndex > & operator[] (PointIndex) const
std::vector< FacetIndex > GetIndices (PointIndex, PointIndex) const
std::vector< FacetIndex > GetIndices (PointIndex, PointIndex, PointIndex) const
MeshFacetArray::_TConstIterator GetFacet (FacetIndex) const
std::set< PointIndex > NeighbourPoints (const std::vector< PointIndex > &, int level) const
std::set< PointIndex > NeighbourPoints (PointIndex) const
void Neighbours (FacetIndex ulFacetInd, float fMaxDist, MeshCollector &collect) const
Base::Vector3f GetNormal (PointIndex) const
void AddNeighbour (PointIndex, FacetIndex)
void RemoveNeighbour (PointIndex, FacetIndex)
void RemoveFacet (FacetIndex)
Protected Member Functions
void SearchNeighbours (const MeshFacetArray &rFacets, FacetIndex index, const Base::Vector3f &rclCenter, float fMaxDist, std::set< FacetIndex > &visit, MeshCollector &collect) const
Detailed Description
The MeshRefPointToFacets builds up a structure to have access to all facets indexing a point.
Note
If the underlying mesh kernel gets changed this structure becomes invalid and must be rebuilt.
Definition at line 474 of file Algorithm.h.
Constructor & Destructor Documentation
MeshRefPointToFacets()
MeshCore::MeshRefPointToFacets::MeshRefPointToFacets (const MeshKernel & rclM) inline explicit
Construction.
Definition at line 478 of file Algorithm.h.
Member Function Documentation
AddNeighbour()
void MeshRefPointToFacets::AddNeighbour (PointIndex pos, FacetIndex facet)
Definition at line 1981 of file Algorithm.cpp.
References RobotExample::pos.
Referenced by MeshCore::MeshRemoveNeedles::Fixup().
GetFacet()
MeshFacetArray::_TConstIterator MeshRefPointToFacets::GetFacet (FacetIndex index) const
Definition at line 1950 of file Algorithm.cpp.
References MeshCore::MeshKernel::GetFacets().
GetIndices() [1/2]
std::vector< FacetIndex > MeshRefPointToFacets::GetIndices (PointIndex pos1, PointIndex pos2) const
Definition at line 1960 of file Algorithm.cpp.
References intersection(), RobotExampleTrajectoryOutOfShapes::pos1, RobotExampleTrajectoryOutOfShapes::pos2, and result.
Referenced by GetIndices().
GetIndices() [2/2]
std::vector< FacetIndex > MeshRefPointToFacets::GetIndices (PointIndex pos1, PointIndex pos2, PointIndex pos3) const
Definition at line 1971 of file Algorithm.cpp.
References GetIndices(), intersection(), RobotExampleTrajectoryOutOfShapes::pos1, RobotExampleTrajectoryOutOfShapes::pos2, and result.
GetNormal()
Base::Vector3f MeshRefPointToFacets::GetNormal (PointIndex pos) const
Definition at line 1848 of file Algorithm.cpp.
References SCL.SimpleDataTypes::f, MeshCore::MeshKernel::GetFacet(), Base::Vector3< float_type >::Normalize(), and RobotExample::pos.
NeighbourPoints() [1/2]
std::set< PointIndex > MeshRefPointToFacets::NeighbourPoints (const std::vector< PointIndex > & pt, int level) const
Definition at line 1862 of file Algorithm.cpp.
References MeshCore::MeshKernel::GetFacets(), SplineSurface::i, and level().
Referenced by MeshCore::MeshEvalDentsOnSurface::Evaluate(), MeshCore::MeshAlgorithm::FillupHole(), and MeshCore::MeshRemoveNeedles::Fixup().
NeighbourPoints() [2/2]
std::set< PointIndex > MeshRefPointToFacets::NeighbourPoints (PointIndex pos) const
Definition at line 1891 of file Algorithm.cpp.
References MeshCore::MeshKernel::GetFacetPoints(), buildPsets::p, and RobotExample::pos.
Neighbours()
void MeshRefPointToFacets::Neighbours (FacetIndex ulFacetInd, float fMaxDist, MeshCollector & collect) const
Definition at line 1912 of file Algorithm.cpp.
References MeshCore::MeshKernel::GetFacet(), MeshCore::MeshKernel::GetFacets(), MeshCore::MeshGeomFacet::GetGravityPoint(), and SearchNeighbours().
Referenced by MeshCore::FacetCurvature::Compute().
operator[]()
const std::set< FacetIndex > & MeshRefPointToFacets::operator[] (PointIndex pos) const
Definition at line 1955 of file Algorithm.cpp.
References RobotExample::pos.
Rebuild()
void MeshRefPointToFacets::Rebuild ()
Rebuilds up data structure.
Definition at line 1832 of file Algorithm.cpp.
References MeshCore::MeshKernel::GetFacets(), and MeshCore::MeshKernel::GetPoints().
RemoveFacet()
void MeshRefPointToFacets::RemoveFacet (FacetIndex facetIndex)
Definition at line 1991 of file Algorithm.cpp.
References MeshCore::MeshKernel::GetFacetPoints().
Referenced by MeshCore::MeshRemoveNeedles::Fixup().
RemoveNeighbour()
void MeshRefPointToFacets::RemoveNeighbour (PointIndex pos, FacetIndex facet)
Definition at line 1986 of file Algorithm.cpp.
References RobotExample::pos.
Referenced by MeshCore::MeshRemoveNeedles::Fixup().
SearchNeighbours()
void MeshRefPointToFacets::SearchNeighbours (const MeshFacetArray & rFacets, FacetIndex index, const Base::Vector3f & rclCenter, float fMaxDist, std::set< FacetIndex > & visit, MeshCollector & collect) const protected
Definition at line 1923 of file Algorithm.cpp.
References MeshCore::MeshFacet::_aulPoints, MeshCore::MeshCollector::Append(), Base::DistanceP2(), SCL.SimpleDataTypes::f, MeshCore::MeshKernel::GetFacet(), and MeshCore::MeshGeomFacet::GetGravityPoint().
Referenced by Neighbours().
The documentation for this class was generated from the following files:
Algorithm.h
Algorithm.cpp