FreeCAD: App::UnitExpression Class Reference
App::UnitExpression Class Reference
#include <ExpressionParser.h>
Public Member Functions
UnitExpression (const App::DocumentObject *_owner=nullptr, const Base::Quantity &_quantity=Base::Quantity(), const std::string &_unitStr=std::string())
~UnitExpression () override
Expression * simplify () const override
void setUnit (const Base::Quantity &_quantity)
void setQuantity (const Base::Quantity &_quantity)
double getValue () const
const Base::Unit & getUnit () const
const Base::Quantity & getQuantity () const
const std::string getUnitString () const
double getScaler () const
Public Member Functions inherited from App::Expression
Expression (const App::DocumentObject *_owner)
~Expression () override
virtual bool isTouched () const
Expression * eval () const
std::string toString (bool persistent=false, bool checkPriority=false, int indent=0) const
void toString (std::ostream &os, bool persistent=false, bool checkPriority=false, int indent=0) const
Expression * copy () const
virtual int priority () const
void getIdentifiers (std::map< App::ObjectIdentifier, bool > &) const
std::map< App::ObjectIdentifier, bool > getIdentifiers () const
void getDeps (ExpressionDeps &deps, int option=DepNormal) const
ExpressionDeps getDeps (int option=DepNormal) const
std::map< App::DocumentObject *, bool > getDepObjects (std::vector< std::string > *labels=nullptr) const
void getDepObjects (std::map< App::DocumentObject *, bool > &, std::vector< std::string > *labels=nullptr) const
ExpressionPtr importSubNames (const std::map< std::string, std::string > &nameMap) const
ExpressionPtr updateLabelReference (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const
ExpressionPtr replaceObject (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const
bool adjustLinks (const std::set< App::DocumentObject * > &inList)
void visit (ExpressionVisitor &v)
App::DocumentObject * getOwner () const
virtual void addComponent (Component *component)
bool hasComponent () const
boost::any getValueAsAny () const
Py::Object getPyValue () const
bool isSame (const Expression &other, bool checkComment=true) const
Component (const std::string &n)
Component (Expression *e1, Expression *e2, Expression *e3, bool isRange=false)
Component (const ObjectIdentifier::Component &comp)
Component (const Component &other)
~Component ()
Component & operator= (const Component &)=delete
void visit (ExpressionVisitor &v)
bool isTouched () const
void toString (std::ostream &ss, bool persistent) const
Component * copy () const
Component * eval () const
Py::Object get (const Expression *owner, const Py::Object &pyobj) const
void set (const Expression *owner, Py::Object &pyobj, const Py::Object &value) const
void del (const Expression *owner, Py::Object &pyobj) const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
Expression * _copy () const override
void _toString (std::ostream &ss, bool persistent, int indent) const override
Py::Object _getPyValue () const override
Protected Member Functions inherited from App::Expression
virtual bool _isIndexable () const
virtual void _getIdentifiers (std::map< App::ObjectIdentifier, bool > &) const
virtual bool _adjustLinks (const std::set< App::DocumentObject * > &, ExpressionVisitor &)
virtual bool _updateElementReference (App::DocumentObject *, bool, ExpressionVisitor &)
virtual bool _relabeledDocument (const std::string &, const std::string &, ExpressionVisitor &)
virtual void _importSubNames (const ObjectIdentifier::SubNameMap &)
virtual void _updateLabelReference (App::DocumentObject *, const std::string &, const char *)
virtual bool _renameObjectIdentifier (const std::map< ObjectIdentifier, ObjectIdentifier > &, const ObjectIdentifier &, ExpressionVisitor &)
virtual void _collectReplacement (std::map< ObjectIdentifier, ObjectIdentifier > &, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const
virtual void _moveCells (const CellAddress &, int, int, ExpressionVisitor &)
virtual void _offsetCells (int, int, ExpressionVisitor &)
virtual void _visit (ExpressionVisitor &)
Protected Attributes
PyObject * cache = nullptr
Protected Attributes inherited from App::Expression
App::DocumentObject * owner
ComponentList components
Additional Inherited Members
Public Types inherited from App::Expression
enum DepOption { DepNormal, DepHidden, DepAll }
using ComponentList = std::vector< Component * >
Static Public Member Functions inherited from App::Expression
static Expression * parse (const App::DocumentObject *owner, const std::string &buffer)
static Component * createComponent (const std::string &n)
static Component * createComponent (Expression *e1, Expression *e2=nullptr, Expression *e3=nullptr, bool isRange=false)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::Expression
std::string comment
ObjectIdentifier::Component comp
Expression * e1
Expression * e2
Expression * e3
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Part of an expressions that contains a unit.
Definition at line 96 of file ExpressionParser.h.
Constructor & Destructor Documentation
UnitExpression()
UnitExpression::UnitExpression (const App::DocumentObject * _owner = nullptr, const Base::Quantity & _quantity = Base::Quantity(), const std::string & _unitStr = std::string()) explicit
Definition at line 1194 of file Expression.cpp.
Referenced by _copy().
~UnitExpression()
UnitExpression::~UnitExpression () override
Definition at line 1201 of file Expression.cpp.
References cache.
Member Function Documentation
_copy()
Expression * UnitExpression::_copy () const override protected virtual
Return a copy of the expression.
Implements App::Expression.
Reimplemented in App::VariableExpression, App::FunctionExpression, App::OperatorExpression, App::ConstantExpression, and App::NumberExpression.
Definition at line 1263 of file Expression.cpp.
References App::Expression::owner, and UnitExpression().
_getPyValue()
Py::Object UnitExpression::_getPyValue () const override protected virtual
Implements App::Expression.
Reimplemented in App::VariableExpression, App::FunctionExpression, App::OperatorExpression, and App::ConstantExpression.
Definition at line 1268 of file Expression.cpp.
References cache, Py::new_reference_to(), and App::pyFromQuantity().
Referenced by App::ConstantExpression::_getPyValue().
_toString()
void UnitExpression::_toString (std::ostream & ss, bool persistent, int indent) const override protected virtual
Return a string representation, in this case the unit string. Return a string representation of the expression.
Implements App::Expression.
Reimplemented in App::VariableExpression, App::FunctionExpression, App::OperatorExpression, App::ConstantExpression, and App::NumberExpression.
Definition at line 1254 of file Expression.cpp.
getQuantity()
const Base::Quantity& App::UnitExpression::getQuantity () const inline
Definition at line 123 of file ExpressionParser.h.
Referenced by App::NumberExpression::_copy(), App::ConstantExpression::_copy(), App::NumberExpression::negate(), Gui::QuantitySpinBoxPrivate::parseString(), App::ExpressionParser::parseUnit(), Gui::QuantitySpinBox::setNumberExpression(), materialtests.TestMaterials.MaterialTestCases::test2DArray(), materialtests.TestMaterials.MaterialTestCases::test3DArray(), materialtests.TestMaterials.MaterialTestCases::testCalculiXSteel(), and materialtests.TestMaterialCreation.MaterialCreationTestCases::testCreateMaterial().
getScaler()
double App::UnitExpression::getScaler () const inline
Definition at line 133 of file ExpressionParser.h.
getUnit()
const Base::Unit& App::UnitExpression::getUnit () const inline
Definition at line 118 of file ExpressionParser.h.
getUnitString()
const std::string App::UnitExpression::getUnitString () const inline
Definition at line 128 of file ExpressionParser.h.
getValue()
double App::UnitExpression::getValue () const inline
Definition at line 113 of file ExpressionParser.h.
References Base::Quantity::getValue().
Referenced by App::NumberExpression::_toString(), App::NumberExpression::isInteger(), App::ExpressionParser::parseUnit(), Gui::UIntSpinBox::setNumberExpression(), Gui::IntSpinBox::setNumberExpression(), and Gui::DoubleSpinBox::setNumberExpression().
setQuantity()
void UnitExpression::setQuantity (const Base::Quantity & _quantity)
Definition at line 1208 of file Expression.cpp.
References cache.
Referenced by App::NumberExpression::negate().
setUnit()
void UnitExpression::setUnit (const Base::Quantity & _quantity)
Set unit information.
Parameters
_unit A unit object
_unitstr The unit expressed as a string
_scaler Scale factor to convert unit into internal unit.
Definition at line 1226 of file Expression.cpp.
References cache.
simplify()
Expression * UnitExpression::simplify () const override virtual
Simplify the expression. In this case, a NumberExpression is returned, as it cannot be simplified any more.
Implements App::Expression.
Reimplemented in App::VariableExpression, App::FunctionExpression, App::OperatorExpression, and App::NumberExpression.
Definition at line 1241 of file Expression.cpp.
References App::Expression::owner.
Member Data Documentation
cache
PyObject* App::UnitExpression::cache = nullptr mutable protected
Definition at line 144 of file ExpressionParser.h.
Referenced by _getPyValue(), App::ConstantExpression::_getPyValue(), setQuantity(), setUnit(), and ~UnitExpression().
The documentation for this class was generated from the following files:
ExpressionParser.h
Expression.cpp