FreeCAD: Gui::DockWnd::SelectionView Class Reference
Gui::DockWnd::SelectionView Class Reference
#include <SelectionView.h>
Public Slots
void search (const QString &text)
get called when text is entered in the search box
void validateSearch ()
get called when enter is pressed in the search box
void onItemContextMenu (const QPoint &point)
get called when the list is right-clicked
void select (QListWidgetItem *item=nullptr)
different actions
void deselect ()
void zoom ()
void treeSelect ()
void toPython ()
void touch ()
void showPart ()
void onEnablePickList ()
void toggleSelect (QListWidgetItem *item=nullptr)
void preselect (QListWidgetItem *item=nullptr)
Public Member Functions
SelectionView (Gui::Document *pcDocument, QWidget *parent=nullptr)
~SelectionView () override
void onSelectionChanged (const SelectionChanges &msg) override
Observer message from the Selection.
void leaveEvent (QEvent *) override
bool onMsg (const char *pMsg, const char **ppReturn) override
Message handler.
const char * getName () const override
returns the name of the view (important for messages)
void onUpdate () override
get called when the document is changed or updated
Public Member Functions inherited from Gui::DockWindow
DockWindow (Gui::Document *pcDocument=nullptr, QWidget *parent=nullptr)
~DockWindow () override
bool onHasMsg (const char *) const override
Message handler test.
bool canClose () override
overwrite when checking on close state
Public Member Functions inherited from Gui::BaseView
BaseView (Gui::Document *pcDocument=nullptr)
~BaseView () override
void setDocument (Gui::Document *pcDocument)
sets the view to another document (called by Application)
void onClose ()
is sent from the document in order to close the document
Gui::Document * getGuiDocument () const
returns the document the view is attached to
App::Document * getAppDocument () const
returns the document the view is attached to
bool isPassive () const
indicates if the view is in passive mode
virtual void onRelabel (Gui::Document *)
get called when the document is relabeled (change of its user name)
virtual void onRename (Gui::Document *)
get called when the document is renamed (change of its internal name)
virtual void deleteSelf ()
delete itself
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Public Attributes
QListWidget * selectionView
QLabel * countLabel
QCheckBox * enablePickList
QListWidget * pickList
Protected Member Functions
void showEvent (QShowEvent *) override
void hideEvent (QHideEvent *) override
Additional Inherited Members
Signals inherited from Gui::DockWindow
void sendCloseView (Gui::MDIView *theView)
sends a message to the document
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Gui::BaseView
Gui::Document * _pcDocument
bool bIsDetached {false}
bool bIsPassive {false}
Detailed Description
A test class. A more elaborate class description.
Definition at line 44 of file SelectionView.h.
Constructor & Destructor Documentation
SelectionView()
SelectionView::SelectionView (Gui::Document * pcDocument, QWidget * parent = nullptr) explicit
A constructor. A more elaborate description of the constructor.
Definition at line 55 of file SelectionView.cpp.
References Gui::BitmapFactory(), Path.Op.Gui.Selection::clear(), and draftgeoutils.intersections::connect().
~SelectionView()
SelectionView::~SelectionView () override default
A destructor. A more elaborate description of the destructor.
Member Function Documentation
deselect
void Gui::DockWnd::SelectionView::deselect () slot
getName()
const char* Gui::DockWnd::SelectionView::getName () const inline override virtual
returns the name of the view (important for messages)
Reimplemented from Gui::DockWindow.
Definition at line 69 of file SelectionView.h.
hideEvent()
void Gui::DockWnd::SelectionView::hideEvent (QHideEvent *) override protected
leaveEvent()
void SelectionView::leaveEvent (QEvent *) override
Definition at line 120 of file SelectionView.cpp.
References Gui::SelectionSingleton::rmvPreselect(), and Gui::Selection().
onEnablePickList
void Gui::DockWnd::SelectionView::onEnablePickList () slot
onItemContextMenu
void Gui::DockWnd::SelectionView::onItemContextMenu (const QPoint & point) slot
get called when the list is right-clicked
onMsg()
bool Gui::DockWnd::SelectionView::onMsg (const char * , const char **) override virtual
Message handler.
Reimplemented from Gui::DockWindow.
onSelectionChanged()
void Gui::DockWnd::SelectionView::onSelectionChanged (const SelectionChanges & msg) override virtual
Observer message from the Selection.
Implements Gui::SelectionObserver.
onUpdate()
void Gui::DockWnd::SelectionView::onUpdate () override virtual
get called when the document is changed or updated
Reimplemented from Gui::DockWindow.
preselect
void Gui::DockWnd::SelectionView::preselect (QListWidgetItem * item = nullptr) slot
search
void Gui::DockWnd::SelectionView::search (const QString & text) slot
get called when text is entered in the search box
Referenced by importers.importIFClegacy.IfcDocument::find().
select
void Gui::DockWnd::SelectionView::select (QListWidgetItem * item = nullptr) slot
different actions
showEvent()
void Gui::DockWnd::SelectionView::showEvent (QShowEvent *) override protected
showPart
void Gui::DockWnd::SelectionView::showPart () slot
toggleSelect
void Gui::DockWnd::SelectionView::toggleSelect (QListWidgetItem * item = nullptr) slot
toPython
void Gui::DockWnd::SelectionView::toPython () slot
touch
void Gui::DockWnd::SelectionView::touch () slot
treeSelect
void Gui::DockWnd::SelectionView::treeSelect () slot
validateSearch
void Gui::DockWnd::SelectionView::validateSearch () slot
get called when enter is pressed in the search box
zoom
void Gui::DockWnd::SelectionView::zoom () slot
Member Data Documentation
countLabel
QLabel* Gui::DockWnd::SelectionView::countLabel
Definition at line 75 of file SelectionView.h.
enablePickList
QCheckBox* Gui::DockWnd::SelectionView::enablePickList
Definition at line 77 of file SelectionView.h.
pickList
QListWidget* Gui::DockWnd::SelectionView::pickList
Definition at line 78 of file SelectionView.h.
selectionView
QListWidget* Gui::DockWnd::SelectionView::selectionView
Definition at line 74 of file SelectionView.h.
The documentation for this class was generated from the following files:
SelectionView.h
SelectionView.cpp