FreeCAD: SnapSpaceAction Class Reference
SnapSpaceAction Class Reference
Public Member Functions
SnapSpaceAction (QObject *parent)
void updateWidget (bool snapenabled)
void languageChange ()
Protected Member Functions
QWidget * createWidget (QWidget *parent) override
Detailed Description
Definition at line 1343 of file Mod/Sketcher/Gui/Command.cpp.
Constructor & Destructor Documentation
SnapSpaceAction()
SnapSpaceAction::SnapSpaceAction (QObject * parent) inline
Definition at line 1347 of file Mod/Sketcher/Gui/Command.cpp.
Member Function Documentation
createWidget()
QWidget* SnapSpaceAction::createWidget (QWidget * parent) inline override protected
Definition at line 1408 of file Mod/Sketcher/Gui/Command.cpp.
References draftgeoutils.intersections::connect(), languageChange(), Init::parent, ParameterGrp::SetBool(), ParameterGrp::SetFloat(), Gui::QuantitySpinBox::setMaximum(), Gui::QuantitySpinBox::setMinimum(), toolbit-attributes::val, and Gui::QuantitySpinBox::valueChanged().
languageChange()
void SnapSpaceAction::languageChange () inline
Definition at line 1388 of file Mod/Sketcher/Gui/Command.cpp.
Referenced by createWidget(), and CmdSketcherSnap::languageChange().
updateWidget()
void SnapSpaceAction::updateWidget (bool snapenabled) inline
Definition at line 1353 of file Mod/Sketcher/Gui/Command.cpp.
References ParameterGrp::GetBool(), ParameterGrp::GetFloat(), Gui::QuantitySpinBox::rawValue, and Gui::QuantitySpinBox::setValue().
Referenced by CmdSketcherSnap::activated(), and CmdSketcherSnap::createAction().
The documentation for this class was generated from the following file:
Mod/Sketcher/Gui/Command.cpp