FreeCAD: TechDrawGui::TaskCustomizeFormat Class Reference
TechDrawGui::TaskCustomizeFormat Class Reference
#include <TaskCustomizeFormat.h>
Public Member Functions
TaskCustomizeFormat (App::DocumentObject *object)
~TaskCustomizeFormat () override
virtual bool accept ()
virtual bool reject ()
void updateTask ()
Protected Member Functions
void changeEvent (QEvent *e) override
void setUiEdit ()
Detailed Description
Definition at line 59 of file TaskCustomizeFormat.h.
Constructor & Destructor Documentation
TaskCustomizeFormat()
TaskCustomizeFormat::TaskCustomizeFormat (App::DocumentObject * object) explicit
Definition at line 46 of file TaskCustomizeFormat.cpp.
References setUiEdit().
~TaskCustomizeFormat()
TaskCustomizeFormat::~TaskCustomizeFormat () override
Definition at line 58 of file TaskCustomizeFormat.cpp.
Member Function Documentation
accept()
bool TaskCustomizeFormat::accept () virtual
Definition at line 185 of file TaskCustomizeFormat.cpp.
References Gui::Command::commitCommand(), TechDraw::DrawViewDimension::FormatSpec, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, App::PropertyString::setValue(), and TechDraw::DrawViewBalloon::Text.
Referenced by TechDrawGui::TaskDlgCustomizeFormat::accept().
changeEvent()
void TaskCustomizeFormat::changeEvent (QEvent * e) override protected
Definition at line 71 of file TaskCustomizeFormat.cpp.
References SCL.SimpleDataTypes::e.
reject()
bool TaskCustomizeFormat::reject () virtual
Definition at line 205 of file TaskCustomizeFormat.cpp.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and TechDrawGui::TaskDlgCustomizeFormat::reject().
setUiEdit()
void TaskCustomizeFormat::setUiEdit () protected
Definition at line 78 of file TaskCustomizeFormat.cpp.
References draftgeoutils.intersections::connect().
Referenced by TaskCustomizeFormat().
updateTask()
void TaskCustomizeFormat::updateTask ()
Definition at line 63 of file TaskCustomizeFormat.cpp.
The documentation for this class was generated from the following files:
TaskCustomizeFormat.h
TaskCustomizeFormat.cpp