FreeCAD: StringCache Class Reference
StringCache Class Reference
Static Public Member Functions
static const char * New (const char *str)
Detailed Description
Definition at line 138 of file Gui/Command.cpp.
Member Function Documentation
New()
static const char* StringCache::New (const char * str) inline static
Definition at line 140 of file Gui/Command.cpp.
References Path.Post.scripts.refactored_centroid_post::str.
Referenced by Gui::CommandBase::setAccel(), Gui::Command::setAppModuleName(), Gui::Command::setGroupName(), Gui::CommandBase::setMenuText(), Gui::CommandBase::setPixmap(), Gui::MacroCommand::setScriptName(), Gui::CommandBase::setStatusTip(), Gui::CommandBase::setToolTipText(), and Gui::CommandBase::setWhatsThis().
The documentation for this class was generated from the following file:
Gui/Command.cpp