FreeCAD: Gui::GuiNativeEvent Class Reference
Gui::GuiNativeEvent Class Reference
#include <GuiNativeEventLinux.h>
Public Member Functions
GuiNativeEvent (GUIApplicationNativeEventAware *app)
~GuiNativeEvent () override
void initSpaceball (QMainWindow *window) override final
GuiNativeEvent (GUIApplicationNativeEventAware *app)
~GuiNativeEvent () override
void initSpaceball (QMainWindow *window) override final
GuiNativeEvent (GUIApplicationNativeEventAware *app)
~GuiNativeEvent () override
void initSpaceball (QMainWindow *window) final
GuiNativeEvent (GUIApplicationNativeEventAware *app)
~GuiNativeEvent () override
void initSpaceball (QMainWindow *window) override final
I3dMouseParam & MouseParams ()
const I3dMouseParam & MouseParams () const
virtual void Move3d (HANDLE device, std::vector< float > &motionData)
virtual void On3dmouseKeyDown (HANDLE device, int virtualKeyCode)
virtual void On3dmouseKeyUp (HANDLE device, int virtualKeyCode)
Public Member Functions inherited from Gui::GuiAbstractNativeEvent
GuiAbstractNativeEvent (GUIApplicationNativeEventAware *app)
~GuiAbstractNativeEvent () override=0
Static Public Member Functions
static bool xcbEventFilter (void *message, long *result)
static bool Is3dmouseAttached ()
Additional Inherited Members
Static Protected Attributes inherited from Gui::GuiAbstractNativeEvent
static GUIApplicationNativeEventAware * mainApp
static std::vector< int > motionDataArray
Detailed Description
Definition at line 34 of file GuiNativeEventLinux.h.
Constructor & Destructor Documentation
GuiNativeEvent() [1/4]
Gui::GuiNativeEvent::GuiNativeEvent (Gui::GUIApplicationNativeEventAware * app)
Definition at line 35 of file GuiNativeEventLinux.cpp.
References GuiNativeEvent().
Referenced by GuiNativeEvent().
~GuiNativeEvent() [1/4]
Gui::GuiNativeEvent::~GuiNativeEvent () override
Definition at line 40 of file GuiNativeEventLinux.cpp.
References Base::Console(), and Base::ConsoleSingleton::Log().
GuiNativeEvent() [2/4]
Gui::GuiNativeEvent::GuiNativeEvent (GUIApplicationNativeEventAware * app)
~GuiNativeEvent() [2/4]
Gui::GuiNativeEvent::~GuiNativeEvent () override
GuiNativeEvent() [3/4]
Gui::GuiNativeEvent::GuiNativeEvent (GUIApplicationNativeEventAware * app) explicit
~GuiNativeEvent() [3/4]
Gui::GuiNativeEvent::~GuiNativeEvent () override
GuiNativeEvent() [4/4]
Gui::GuiNativeEvent::GuiNativeEvent (GUIApplicationNativeEventAware * app)
~GuiNativeEvent() [4/4]
Gui::GuiNativeEvent::~GuiNativeEvent () override
Member Function Documentation
initSpaceball() [1/4]
void Gui::GuiNativeEvent::initSpaceball (QMainWindow * window) final virtual
Implements Gui::GuiAbstractNativeEvent.
initSpaceball() [2/4]
void Gui::GuiNativeEvent::initSpaceball (QMainWindow * window) final override virtual
Implements Gui::GuiAbstractNativeEvent.
Definition at line 48 of file GuiNativeEventLinux.cpp.
References draftgeoutils.intersections::connect(), Base::Console(), and Base::ConsoleSingleton::Log().
initSpaceball() [3/4]
void Gui::GuiNativeEvent::initSpaceball (QMainWindow * window) final override virtual
Implements Gui::GuiAbstractNativeEvent.
initSpaceball() [4/4]
void Gui::GuiNativeEvent::initSpaceball (QMainWindow * window) final override virtual
Implements Gui::GuiAbstractNativeEvent.
Is3dmouseAttached()
bool Gui::GuiNativeEvent::Is3dmouseAttached () static
Detect the 3D mouse
Definition at line 428 of file GuiNativeEventWin32.cpp.
References CONNEXION_VENDOR_ID, GetDevicesToRegister(), SplineSurface::i, and LOGITECH_VENDOR_ID.
MouseParams() [1/2]
const I3dMouseParam & Gui::GuiNativeEvent::MouseParams ()
Access the mouse parameters structure
Definition at line 348 of file GuiNativeEventWin32.cpp.
MouseParams() [2/2]
const I3dMouseParam& Gui::GuiNativeEvent::MouseParams () const
Move3d()
void Gui::GuiNativeEvent::Move3d (HANDLE device, std::vector< float > & motionData) virtual
Called with the processed motion data when a 3D mouse event is received
The default implementation emits a Move3d signal with the motion data
Definition at line 366 of file GuiNativeEventWin32.cpp.
On3dmouseKeyDown()
void Gui::GuiNativeEvent::On3dmouseKeyDown (HANDLE device, int virtualKeyCode) virtual
Called when a 3D mouse key is pressed
The default implementation emits a On3dmouseKeyDown signal with the key code.
Definition at line 385 of file GuiNativeEventWin32.cpp.
On3dmouseKeyUp()
void Gui::GuiNativeEvent::On3dmouseKeyUp (HANDLE device, int virtualKeyCode) virtual
Called when a 3D mouse key is released
The default implementation emits a On3dmouseKeyUp signal with the key code.
Definition at line 397 of file GuiNativeEventWin32.cpp.
xcbEventFilter()
bool Gui::GuiNativeEvent::xcbEventFilter (void * message, long * result) static
Definition at line 81 of file GuiNativeEventLinuxX11.cpp.
References Spaceball::BUTTON_PRESSED, Spaceball::BUTTON_RELEASED, Base::Console(), Base::ConsoleSingleton::Log(), and result.
The documentation for this class was generated from the following files:
GuiNativeEventLinux.h
GuiNativeEventMac.h
GuiNativeEventWin32.h
GuiNativeEventLinuxX11.h
GuiNativeEventLinux.cpp
GuiNativeEventLinuxX11.cpp
GuiNativeEventMac.cpp
GuiNativeEventWin32.cpp