FreeCAD: Base::ConsoleObserverFile Class Reference
Base::ConsoleObserverFile Class Reference
#include <ConsoleObserver.h>
Public Member Functions
ConsoleObserverFile (const char *sFileName)
~ConsoleObserverFile () override
void SendLog (const std::string &notifiername, const std::string &msg, LogStyle level, IntendedRecipient recipient, ContentType content) override
const char * Name () override
ConsoleObserverFile (const ConsoleObserverFile &)=delete
ConsoleObserverFile (ConsoleObserverFile &&)=delete
ConsoleObserverFile & operator= (const ConsoleObserverFile &)=delete
ConsoleObserverFile & operator= (ConsoleObserverFile &&)=delete
Public Member Functions inherited from Base::ILogger
ILogger ()=default
ILogger (const ILogger &)=delete
ILogger (ILogger &&)=delete
ILogger & operator= (const ILogger &)=delete
ILogger & operator= (ILogger &&)=delete
virtual ~ILogger ()=0
bool isActive (Base::LogStyle category) const
Additional Inherited Members
Public Attributes inherited from Base::ILogger
bool bErr {true}
bool bMsg {true}
bool bLog {true}
bool bWrn {true}
bool bCritical {true}
bool bNotification {false}
Detailed Description
The LoggingConsoleObserver class This class is used by the main modules to write Console messages and logs to a file
Definition at line 61 of file ConsoleObserver.h.
Constructor & Destructor Documentation
ConsoleObserverFile() [1/3]
ConsoleObserverFile::ConsoleObserverFile (const char * sFileName) explicit
Definition at line 46 of file ConsoleObserver.cpp.
References Base::Console(), and Base::ConsoleSingleton::Warning().
~ConsoleObserverFile()
ConsoleObserverFile::~ConsoleObserverFile () override
Definition at line 57 of file ConsoleObserver.cpp.
ConsoleObserverFile() [2/3]
Base::ConsoleObserverFile::ConsoleObserverFile (const ConsoleObserverFile &) delete
ConsoleObserverFile() [3/3]
Base::ConsoleObserverFile::ConsoleObserverFile (ConsoleObserverFile &&) delete
Member Function Documentation
Name()
const char* Base::ConsoleObserverFile::Name () inline override virtual
Reimplemented from Base::ILogger.
Definition at line 93 of file ConsoleObserver.h.
References Base::Critical.
operator=() [1/2]
ConsoleObserverFile& Base::ConsoleObserverFile::operator= (ConsoleObserverFile &&) delete
operator=() [2/2]
ConsoleObserverFile& Base::ConsoleObserverFile::operator= (const ConsoleObserverFile &) delete
SendLog()
void ConsoleObserverFile::SendLog (const std::string & notifiername, const std::string & msg, LogStyle level, IntendedRecipient recipient, ContentType content) override virtual
Used to send a Log message at the given level.
Parameters
notifiername A string identifying the entity generating the notification. It may be the Label of the App::Document or the full label of the App::DocumentObject.
msg The message to be notified.
level A valid level (Log, Message, Error, Notification, CriticalNotification, ...)
recipient A valid intended recipient (All, Developer, User). Observers may decide to process only notifications when a certain recipient is intended.
content A valid content property (Untranslated, Translatable, Untranslatable). Observers may decide not to process notifications if they are not translated or cannot be translated (are untranslatable). Or conversely, may decide not to process already translated notifications. It is up to the intended behaviour of the observer.
Implements Base::ILogger.
Definition at line 62 of file ConsoleObserver.cpp.
References Base::Critical, Base::Error, level(), Base::Log, Base::Message, Path.Op.Surface::msg, Base::Translated, Base::User, and Base::Warning.
The documentation for this class was generated from the following files:
ConsoleObserver.h
ConsoleObserver.cpp