FreeCAD: Path.Tool.Bit Namespace Reference
Path.Tool.Bit Namespace Reference
Classes
class ToolBit
class ToolBitFactory
Functions
def findToolShape (name, path=None)
def findToolBit (name, path=None)
def findToolLibrary (name, path=None)
def findRelativePathLibrary (path)
def Declaration (path)
Variables
Part
PropertyGroupShape
Factory
Function Documentation
Declaration()
def Path.Tool.Bit.Declaration (path)
Definition at line 459 of file Bit.py.
References AssemblyImport.open(), and Path.Log.track().
Referenced by Path.Tool.Bit.ToolBitFactory.CreateFrom().
findRelativePathLibrary()
def Path.Tool.Bit.findRelativePathLibrary (path)
Definition at line 132 of file Bit.py.
findToolBit()
def Path.Tool.Bit.findToolBit (name, path = None)
findToolBit(name, path) ... search for name, if relative path look in path
Definition at line 91 of file Bit.py.
References Path.Log.track().
findToolLibrary()
def Path.Tool.Bit.findToolLibrary (name, path = None)
findToolLibrary(name, path) ... search for name, if relative path look in path
Definition at line 100 of file Bit.py.
References Path.Preferences.searchPathsTool(), and Path.Log.track().
findToolShape()
def Path.Tool.Bit.findToolShape (name, path = None)
findToolShape(name, path) ... search for name, if relative path look in path
Definition at line 85 of file Bit.py.
References Path.Log.track().
Referenced by Path.Tool.Bit.ToolBit.getBitThumbnail(), and Path.Tool.Bit.ToolBit.onDelete().
Variable Documentation
Factory
Path.Tool.Bit.Factory
Definition at line 500 of file Bit.py.
Part
Path.Tool.Bit.Part
Definition at line 35 of file Bit.py.
PropertyGroupShape
Path.Tool.Bit.PropertyGroupShape
Definition at line 42 of file Bit.py.