FreeCAD: nativeifc.ifc_status Namespace Reference
nativeifc.ifc_status Namespace Reference
Classes
class IFC_WBManipulator
Functions
def set_status_widget (statuswidget)
def set_properties_editor (statuswidget)
def on_add_property ()
def on_add_pset ()
def on_toggle_lock (checked=None, noconvert=False, setchecked=False)
def on_open ()
def on_activate ()
def on_new ()
def set_menu (locked=False)
def set_button (checked=False, setchecked=False)
def unlock_document ()
def lock_document ()
def find_toplevel (objs)
def filter_out (objs)
def get_lock_status ()
Variables
translate = FreeCAD.Qt.translate
params = FreeCAD.ParamGet("User parameter:BaseApp/Preferences/Mod/NativeIFC")
text_on = translate("BIM", "Strict IFC mode is ON (all objects are IFC)")
text_off = translate("BIM", "Strict IFC mode is OFF (IFC and non-IFC objects allowed)")
Function Documentation
filter_out()
def nativeifc.ifc_status.filter_out (objs)
Filter out objects that should not be converted to IFC
Definition at line 474 of file ifc_status.py.
Referenced by nativeifc.ifc_status.find_toplevel().
find_toplevel()
def nativeifc.ifc_status.find_toplevel (objs)
Finds the top-level objects from the list
Definition at line 452 of file ifc_status.py.
References nativeifc.ifc_status.filter_out().
Referenced by nativeifc.ifc_status.lock_document().
get_lock_status()
def nativeifc.ifc_status.get_lock_status ()
Returns the status of the IFC lock button
Definition at line 501 of file ifc_status.py.
Referenced by nativeifc.ifc_status.on_toggle_lock().
lock_document()
def nativeifc.ifc_status.lock_document ()
Locks the active document
Definition at line 356 of file ifc_status.py.
References nativeifc.ifc_status.find_toplevel().
Referenced by nativeifc.ifc_status.on_toggle_lock().
on_activate()
def nativeifc.ifc_status.on_activate ()
What happens when activating a document
Definition at line 246 of file ifc_status.py.
References nativeifc.ifc_status.on_toggle_lock(), and nativeifc.ifc_status.set_menu().
on_add_property()
def nativeifc.ifc_status.on_add_property ()
When the 'add property' button is clicked
Definition at line 97 of file ifc_status.py.
References exportCSG.center(), and Init.parent.
on_add_pset()
def nativeifc.ifc_status.on_add_pset ()
When the 'add pset' button is pressed
Definition at line 152 of file ifc_status.py.
References exportCSG.center(), and AssemblyImport.open().
on_new()
def nativeifc.ifc_status.on_new ()
What happens when creating a new document
Definition at line 267 of file ifc_status.py.
on_open()
def nativeifc.ifc_status.on_open ()
What happens when opening an existing document
Definition at line 240 of file ifc_status.py.
on_toggle_lock()
def nativeifc.ifc_status.on_toggle_lock (checked = None, noconvert = False, setchecked = False)
When the toolbar button is pressed
Definition at line 226 of file ifc_status.py.
References nativeifc.ifc_status.get_lock_status(), nativeifc.ifc_status.lock_document(), nativeifc.ifc_status.set_button(), nativeifc.ifc_status.set_menu(), and nativeifc.ifc_status.unlock_document().
Referenced by nativeifc.ifc_status.on_activate(), and nativeifc.ifc_status.set_status_widget().
set_button()
def nativeifc.ifc_status.set_button (checked = False, setchecked = False)
Sets the lock button
Definition at line 301 of file ifc_status.py.
Referenced by nativeifc.ifc_status.on_toggle_lock().
set_menu()
def nativeifc.ifc_status.set_menu (locked = False)
Sets the File menu items
Definition at line 273 of file ifc_status.py.
Referenced by nativeifc.ifc_status.on_activate(), and nativeifc.ifc_status.on_toggle_lock().
set_properties_editor()
def nativeifc.ifc_status.set_properties_editor (statuswidget)
Adds additional buttons to the properties editor
Definition at line 64 of file ifc_status.py.
Referenced by nativeifc.ifc_status.set_status_widget().
set_status_widget()
def nativeifc.ifc_status.set_status_widget (statuswidget)
Adds the needed controls to the status bar
Definition at line 39 of file ifc_status.py.
References nativeifc.ifc_status.on_toggle_lock(), and nativeifc.ifc_status.set_properties_editor().
unlock_document()
def nativeifc.ifc_status.unlock_document ()
Unlocks the active document
Definition at line 328 of file ifc_status.py.
Referenced by nativeifc.ifc_status.on_toggle_lock().
Variable Documentation
params
nativeifc.ifc_status.params = FreeCAD.ParamGet("User parameter:BaseApp/Preferences/Mod/NativeIFC")
Definition at line 34 of file ifc_status.py.
text_off
nativeifc.ifc_status.text_off = translate("BIM", "Strict IFC mode is OFF (IFC and non-IFC objects allowed)")
Definition at line 36 of file ifc_status.py.
text_on
nativeifc.ifc_status.text_on = translate("BIM", "Strict IFC mode is ON (all objects are IFC)")
Definition at line 35 of file ifc_status.py.
translate
nativeifc.ifc_status.translate = FreeCAD.Qt.translate
Definition at line 33 of file ifc_status.py.