FreeCAD: Gui::MenuManager Class Reference
Gui::MenuManager Class Reference
#include <MenuManager.h>
Public Member Functions
void setup (MenuItem *) const
void setupContextMenu (MenuItem *item, QMenu &menu) const
sets up a context menu out of item
void retranslate () const
Static Public Member Functions
static MenuManager * getInstance ()
The one and only instance.
static void destruct ()
Protected Member Functions
MenuManager ()
~MenuManager ()
Friends
class MainWindow
Detailed Description
The MenuManager class is responsible for the creation of menus and context menus and appending them to the main window.
See also
ToolBoxManager
ToolBarManager
Author
Werner Mayer
Definition at line 77 of file MenuManager.h.
Constructor & Destructor Documentation
MenuManager()
MenuManager::MenuManager () protected default
Referenced by getInstance().
~MenuManager()
MenuManager::~MenuManager () protected default
Member Function Documentation
destruct()
void MenuManager::destruct () static
Definition at line 190 of file MenuManager.cpp.
Referenced by Gui::WorkbenchManager::~WorkbenchManager().
getInstance()
MenuManager * MenuManager::getInstance () static
The one and only instance.
Definition at line 182 of file MenuManager.cpp.
References MenuManager().
Referenced by Gui::Workbench::activate(), Gui::DAG::Model::contextMenuEvent(), Gui::TreeWidget::contextMenuEvent(), SketcherGui::ViewProviderSketch::generateContextMenu(), Gui::NavigationStyle::openPopupMenu(), and Gui::Workbench::retranslate().
retranslate()
void MenuManager::retranslate () const
Definition at line 361 of file MenuManager.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and Gui::getMainWindow().
Referenced by Gui::Workbench::retranslate().
setup()
void MenuManager::setup (MenuItem * menuItems) const
Sets up the menus of a given workbench.
Definition at line 200 of file MenuManager.cpp.
References Path.Post.scripts.dynapath_4060_post::action, App::GetApplication(), Gui::MenuItem::getItems(), Gui::getMainWindow(), NavigationIndicatorGui::menu, and src.Mod.AddonManager.Addon::translate.
Referenced by Gui::Workbench::activate(), Path.Dressup.Tags.ObjectTagDressup::doExecute(), Path.Dressup.Gui.Dogbone.ObjectDressup::execute(), Path.Dressup.Tags.ObjectTagDressup::generateTags(), Path.Dressup.Tags.ObjectTagDressup::pointAtBottom(), Path.Dressup.Tags.ObjectTagDressup::pointIsOnPath(), setupContextMenu(), Path.Dressup.Tags.ObjectTagDressup::setXyEnabled(), and Path.Dressup.Tags.ObjectTagDressup::supportsTagGeneration().
setupContextMenu()
void MenuManager::setupContextMenu (MenuItem * item, QMenu & menu) const
sets up a context menu out of item
Definition at line 435 of file MenuManager.cpp.
References NavigationIndicatorGui::menu, and setup().
Referenced by Gui::DAG::Model::contextMenuEvent(), Gui::TreeWidget::contextMenuEvent(), SketcherGui::ViewProviderSketch::generateContextMenu(), and Gui::NavigationStyle::openPopupMenu().
Friends And Related Function Documentation
MainWindow
friend class MainWindow friend
Definition at line 103 of file MenuManager.h.
The documentation for this class was generated from the following files:
MenuManager.h
MenuManager.cpp