FreeCAD: Sketcher::ExternalGeometryFacade Class Reference
Sketcher::ExternalGeometryFacade Class Reference
#include <ExternalGeometryFacade.h>
Public Member Functions
void setGeometry (Part::Geometry *geometry)
bool testFlag (int flag) const override
void setFlag (int flag, bool v=true) override
unsigned long getFlags () const override
void setFlags (unsigned long flags) override
bool isClear () const override
size_t flagSize () const override
const std::string & getRef () const override
void setRef (const std::string &ref) override
int getRefIndex () const override
void setRefIndex (int index) override
long getId () const override
void setId (long id) override
InternalType::InternalType getInternalType () const override
void setInternalType (InternalType::InternalType type) override
bool testGeometryMode (int flag) const override
void setGeometryMode (int flag, bool v=true) override
int getGeometryLayerId () const override
void setGeometryLayerId (int geolayer) override
bool getBlocked () const
void setBlocked (bool status=true)
bool getConstruction () const
void setConstruction (bool construction)
const std::string & getSketchExtensionName () const
const std::string & getExternalExtensionName () const
template<typename GeometryT = Part::Geometry, typename = typename std::enable_if< std::is_base_of<Part::Geometry, typename std::decay<GeometryT>::type>::value>::type>
GeometryT * getGeometry ()
template<typename GeometryT = Part::Geometry, typename = typename std::enable_if< std::is_base_of<Part::Geometry, typename std::decay<GeometryT>::type>::value>::type>
GeometryT * getGeometry () const
PyObject * getPyObject () override
TopoDS_Shape toShape () const
const Handle (Geom_Geometry) &handle() const
Part::Geometry * copy () const
Part::Geometry * clone () const
boost::uuids::uuid getTag () const
std::vector< std::weak_ptr< const Part::GeometryExtension > > getExtensions () const
bool hasExtension (Base::Type type) const
bool hasExtension (const std::string &name) const
std::weak_ptr< const Part::GeometryExtension > getExtension (Base::Type type) const
std::weak_ptr< const Part::GeometryExtension > getExtension (const std::string &name) const
void setExtension (std::unique_ptr< Part::GeometryExtension > &&geo)
void deleteExtension (Base::Type type)
void deleteExtension (const std::string &name)
void mirror (const Base::Vector3d &point)
void mirror (const Base::Vector3d &point, Base::Vector3d dir)
void rotate (const Base::Placement &plm)
void scale (const Base::Vector3d &vec, double scale)
void transform (const Base::Matrix4D &mat)
void translate (const Base::Vector3d &vec)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static std::unique_ptr< ExternalGeometryFacade > getFacade (Part::Geometry *geometry)
static std::unique_ptr< const ExternalGeometryFacade > getFacade (const Part::Geometry *geometry)
static void ensureSketchGeometryExtensions (Part::Geometry *geometry)
static void copyId (const Part::Geometry *src, Part::Geometry *dst)
static void copyFlags (const Part::Geometry *src, Part::Geometry *dst)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Friends
class ExternalGeometryFacadePy
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 72 of file ExternalGeometryFacade.h.
Member Function Documentation
clone()
Part::Geometry* Sketcher::ExternalGeometryFacade::clone () const inline
Definition at line 245 of file ExternalGeometryFacade.h.
copy()
Part::Geometry* Sketcher::ExternalGeometryFacade::copy () const inline
Definition at line 241 of file ExternalGeometryFacade.h.
copyFlags()
void ExternalGeometryFacade::copyFlags (const Part::Geometry * src, Part::Geometry * dst) static
Definition at line 164 of file ExternalGeometryFacade.cpp.
References getFacade().
Referenced by Sketcher::SketchObject::rebuildExternalGeometry().
copyId()
void ExternalGeometryFacade::copyId (const Part::Geometry * src, Part::Geometry * dst) static
Definition at line 157 of file ExternalGeometryFacade.cpp.
References getFacade().
deleteExtension() [1/2]
void Sketcher::ExternalGeometryFacade::deleteExtension (Base::Type type) inline
Definition at line 278 of file ExternalGeometryFacade.h.
deleteExtension() [2/2]
void Sketcher::ExternalGeometryFacade::deleteExtension (const std::string & name) inline
Definition at line 282 of file ExternalGeometryFacade.h.
ensureSketchGeometryExtensions()
void ExternalGeometryFacade::ensureSketchGeometryExtensions (Part::Geometry * geometry) static
Definition at line 144 of file ExternalGeometryFacade.cpp.
References Base::BaseClass::getClassTypeId().
flagSize()
size_t Sketcher::ExternalGeometryFacade::flagSize () const inline override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
Definition at line 122 of file ExternalGeometryFacade.h.
getBlocked()
bool Sketcher::ExternalGeometryFacade::getBlocked () const inline
Definition at line 182 of file ExternalGeometryFacade.h.
getConstruction()
bool Sketcher::ExternalGeometryFacade::getConstruction () const inline
Definition at line 191 of file ExternalGeometryFacade.h.
getExtension() [1/2]
std::weak_ptr<const Part::GeometryExtension> Sketcher::ExternalGeometryFacade::getExtension (Base::Type type) const inline
Definition at line 266 of file ExternalGeometryFacade.h.
getExtension() [2/2]
std::weak_ptr<const Part::GeometryExtension> Sketcher::ExternalGeometryFacade::getExtension (const std::string & name) const inline
Definition at line 270 of file ExternalGeometryFacade.h.
getExtensions()
std::vector<std::weak_ptr<const Part::GeometryExtension> > Sketcher::ExternalGeometryFacade::getExtensions () const inline
Definition at line 254 of file ExternalGeometryFacade.h.
References Path.Post.scripts.opensbp_post::move().
getExternalExtensionName()
const std::string& Sketcher::ExternalGeometryFacade::getExternalExtensionName () const inline
Definition at line 205 of file ExternalGeometryFacade.h.
getFacade() [1/2]
std::unique_ptr< const ExternalGeometryFacade > ExternalGeometryFacade::getFacade (const Part::Geometry * geometry) static
Definition at line 67 of file ExternalGeometryFacade.cpp.
getFacade() [2/2]
std::unique_ptr< ExternalGeometryFacade > ExternalGeometryFacade::getFacade (Part::Geometry * geometry) static
Definition at line 56 of file ExternalGeometryFacade.cpp.
Referenced by Sketcher::SketchObject::attachExternal(), Sketcher::SketchObject::buildShape(), Sketcher::SketchObject::carbonCopy(), copyFlags(), copyId(), Sketcher::SketchObject::delAllExternal(), Sketcher::SketchObject::delExternal(), Sketcher::SketchObject::delExternalPrivate(), Sketcher::SketchObject::fixExternalGeometry(), Sketcher::SketchObject::getGeometryReference(), Sketcher::SketchObject::getRelatedGeometry(), SketcherGui::GeometryLayerParameters::getSubLayerIndex(), Sketcher::SketchObject::onChanged(), Sketcher::SketchObject::rebuildExternalGeometry(), Sketcher::SketchObject::Save(), Sketcher::SketchObject::setConstruction(), Sketcher::SketchObject::syncGeometry(), Sketcher::SketchObject::toggleConstruction(), Sketcher::SketchObject::toggleExternalGeometryFlag(), and Sketcher::SketchObject::updateGeometryRefs().
getFlags()
unsigned long Sketcher::ExternalGeometryFacade::getFlags () const inline override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
Definition at line 107 of file ExternalGeometryFacade.h.
getGeometry() [1/2]
template<typename GeometryT = Part::Geometry, typename = typename std::enable_if< std::is_base_of<Part::Geometry, typename std::decay<GeometryT>::type>::value>::type> GeometryT* Sketcher::ExternalGeometryFacade::getGeometry () inline
Definition at line 215 of file ExternalGeometryFacade.h.
getGeometry() [2/2]
template<typename GeometryT = Part::Geometry, typename = typename std::enable_if< std::is_base_of<Part::Geometry, typename std::decay<GeometryT>::type>::value>::type> GeometryT* Sketcher::ExternalGeometryFacade::getGeometry () const inline
Definition at line 225 of file ExternalGeometryFacade.h.
getGeometryLayerId()
int Sketcher::ExternalGeometryFacade::getGeometryLayerId () const inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 172 of file ExternalGeometryFacade.h.
References Sketcher::GeometryMode::Construction.
getId()
long Sketcher::ExternalGeometryFacade::getId () const inline override virtual
GeometryExtension Interface
Implements Sketcher::ISketchGeometryExtension.
Definition at line 145 of file ExternalGeometryFacade.h.
Referenced by setRef().
getInternalType()
InternalType::InternalType Sketcher::ExternalGeometryFacade::getInternalType () const inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 154 of file ExternalGeometryFacade.h.
getPyObject()
PyObject * ExternalGeometryFacade::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 181 of file ExternalGeometryFacade.cpp.
References ExternalGeometryFacadePy.
getRef()
const std::string& Sketcher::ExternalGeometryFacade::getRef () const inline override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
Definition at line 127 of file ExternalGeometryFacade.h.
getRefIndex()
int Sketcher::ExternalGeometryFacade::getRefIndex () const inline override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
Definition at line 134 of file ExternalGeometryFacade.h.
getSketchExtensionName()
const std::string& Sketcher::ExternalGeometryFacade::getSketchExtensionName () const inline
Definition at line 201 of file ExternalGeometryFacade.h.
getTag()
boost::uuids::uuid Sketcher::ExternalGeometryFacade::getTag () const inline
Definition at line 249 of file ExternalGeometryFacade.h.
Handle()
const Sketcher::ExternalGeometryFacade::Handle (Geom_Geometry) const & inline
Definition at line 237 of file ExternalGeometryFacade.h.
hasExtension() [1/2]
bool Sketcher::ExternalGeometryFacade::hasExtension (Base::Type type) const inline
Definition at line 258 of file ExternalGeometryFacade.h.
References Path.Post.scripts.grbl_post::type.
hasExtension() [2/2]
bool Sketcher::ExternalGeometryFacade::hasExtension (const std::string & name) const inline
Definition at line 262 of file ExternalGeometryFacade.h.
isClear()
bool Sketcher::ExternalGeometryFacade::isClear () const inline override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
Definition at line 117 of file ExternalGeometryFacade.h.
mirror() [1/2]
void Sketcher::ExternalGeometryFacade::mirror (const Base::Vector3d & point) inline
Definition at line 287 of file ExternalGeometryFacade.h.
References SurfaceTests.TestBlendCurve::vec.
mirror() [2/2]
void Sketcher::ExternalGeometryFacade::mirror (const Base::Vector3d & point, Base::Vector3d dir) inline
Definition at line 291 of file ExternalGeometryFacade.h.
rotate()
void Sketcher::ExternalGeometryFacade::rotate (const Base::Placement & plm) inline
Definition at line 295 of file ExternalGeometryFacade.h.
scale()
void Sketcher::ExternalGeometryFacade::scale (const Base::Vector3d & vec, double scale) inline
Definition at line 299 of file ExternalGeometryFacade.h.
setBlocked()
void Sketcher::ExternalGeometryFacade::setBlocked (bool status = true) inline
Definition at line 186 of file ExternalGeometryFacade.h.
setConstruction()
void Sketcher::ExternalGeometryFacade::setConstruction (bool construction) inline
Definition at line 195 of file ExternalGeometryFacade.h.
setExtension()
void Sketcher::ExternalGeometryFacade::setExtension (std::unique_ptr< Part::GeometryExtension > && geo) inline
Definition at line 274 of file ExternalGeometryFacade.h.
setFlag()
void Sketcher::ExternalGeometryFacade::setFlag (int flag, bool v = true) inline override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
Definition at line 102 of file ExternalGeometryFacade.h.
setFlags()
void Sketcher::ExternalGeometryFacade::setFlags (unsigned long flags) inline override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
Definition at line 112 of file ExternalGeometryFacade.h.
setGeometry()
void ExternalGeometryFacade::setGeometry (Part::Geometry * geometry)
Definition at line 77 of file ExternalGeometryFacade.cpp.
References THROWM.
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_readme_browser.WidgetReadmeBrowser::setMarkdown().
setGeometryLayerId()
void Sketcher::ExternalGeometryFacade::setGeometryLayerId (int geolayer) inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 176 of file ExternalGeometryFacade.h.
References Sketcher::GeometryMode::Construction.
setGeometryMode()
void Sketcher::ExternalGeometryFacade::setGeometryMode (int flag, bool v = true) inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 167 of file ExternalGeometryFacade.h.
References Sketcher::GeometryMode::Blocked.
setId()
void Sketcher::ExternalGeometryFacade::setId (long id) inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 149 of file ExternalGeometryFacade.h.
setInternalType()
void Sketcher::ExternalGeometryFacade::setInternalType (InternalType::InternalType type) inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 158 of file ExternalGeometryFacade.h.
setRef()
void ExternalGeometryFacade::setRef (const std::string & ref) override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
Definition at line 171 of file ExternalGeometryFacade.cpp.
References FC_ERR, and getId().
setRefIndex()
void Sketcher::ExternalGeometryFacade::setRefIndex (int index) inline override virtual
Implements Sketcher::ISketchExternalGeometryExtension.
Definition at line 139 of file ExternalGeometryFacade.h.
References Path.Post.scripts.grbl_post::type.
testFlag()
bool Sketcher::ExternalGeometryFacade::testFlag (int flag) const inline override virtual
External GeometryExtension Interface
Implements Sketcher::ISketchExternalGeometryExtension.
Definition at line 97 of file ExternalGeometryFacade.h.
testGeometryMode()
bool Sketcher::ExternalGeometryFacade::testGeometryMode (int flag) const inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 163 of file ExternalGeometryFacade.h.
References Sketcher::GeometryMode::Blocked.
toShape()
TopoDS_Shape Sketcher::ExternalGeometryFacade::toShape () const inline
Geometry Interface
Definition at line 233 of file ExternalGeometryFacade.h.
transform()
void Sketcher::ExternalGeometryFacade::transform (const Base::Matrix4D & mat) inline
Definition at line 303 of file ExternalGeometryFacade.h.
translate()
void Sketcher::ExternalGeometryFacade::translate (const Base::Vector3d & vec) inline
Definition at line 307 of file ExternalGeometryFacade.h.
Friends And Related Function Documentation
ExternalGeometryFacadePy
friend class ExternalGeometryFacadePy friend
Definition at line 82 of file ExternalGeometryFacade.h.
Referenced by getPyObject().
The documentation for this class was generated from the following files:
ExternalGeometryFacade.h
ExternalGeometryFacade.cpp