FreeCAD: Measure::Measurement Class Reference
Measure::Measurement Class Reference
#include <Measurement.h>
Public Member Functions
Measurement ()
~Measurement () override
void clear ()
bool has3DReferences ()
int addReference3D (App::DocumentObject *obj, const std::string &subName)
Add a reference.
int addReference3D (App::DocumentObject *obj, const char *subName)
add a 3D reference (obj+sub) to end of list
MeasureType getType ()
MeasureType findType ()
PyObject * getPyObject () override
virtual unsigned int getMemSize () const
double length () const
Base::Vector3d delta () const
double lineLineDistance () const
double planePlaneDistance () const
double radius () const
double angle (const Base::Vector3d &param=Base::Vector3d(0, 0, 0)) const
Base::Vector3d massCenter () const
double volume () const
double area () const
bool planesAreParallel () const
bool linesAreParallel () const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static Base::Vector3d toVector3d (const gp_Pnt gp)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes
App::PropertyLinkSubList References3D
Protected Member Functions
TopoDS_Shape getShape (App::DocumentObject *obj, const char *subName) const
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 62 of file Measurement.h.
Constructor & Destructor Documentation
Measurement()
Measurement::Measurement ()
Definition at line 60 of file Measurement.cpp.
References App::Global, and Measure::Invalid.
~Measurement()
Measurement::~Measurement () override default
Member Function Documentation
addReference3D() [1/2]
int Measurement::addReference3D (App::DocumentObject * obj, const char * subName)
add a 3D reference (obj+sub) to end of list
Definition at line 88 of file Measurement.cpp.
References importers.importIFCmulticore::objects.
addReference3D() [2/2]
int Measurement::addReference3D (App::DocumentObject * obj, const std::string & subName)
Add a reference.
Definition at line 82 of file Measurement.cpp.
angle()
double Measurement::angle (const Base::Vector3d & param = Base::Vector3d(0, 0, 0)) const
Definition at line 452 of file Measurement.cpp.
References importers.importIFClegacy::getShape(), Measure::Invalid, src.Mod.PartDesign.Scripts.Gear::l1, src.Mod.PartDesign.Scripts.Gear::l2, KDL::min(), importers.importIFCmulticore::objects, Measure::Points, and Measure::TwoLines.
Referenced by Path.Base.Generator.dogboneII.Generator::generate().
area()
double Measurement::area () const
Definition at line 677 of file Measurement.cpp.
References Measure::Cone, Base::Console(), Measure::Cylinder, Base::ConsoleSingleton::Error(), importers.importIFClegacy::getShape(), SplineSurface::i, importers.importIFCmulticore::objects, Measure::Plane, result, Measure::Sphere, Measure::Surfaces, Measure::Torus, and Measure::Volumes.
clear()
void Measurement::clear ()
Definition at line 68 of file Measurement.cpp.
References Measure::Invalid.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), and src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__().
delta()
Base::Vector3d Measurement::delta () const
Definition at line 562 of file Measurement.cpp.
References Base::Console(), KDL::diff(), Measure::Edges, Base::ConsoleSingleton::Error(), importers.importIFClegacy::getShape(), Measure::Invalid, importers.importIFCmulticore::objects, Measure::PointToEdge, Measure::PointToPoint, Measure::PointToSurface, and result.
findType()
MeasureType Measurement::findType ()
Definition at line 102 of file Measurement.cpp.
References Measure::Circle, Measure::Cone, Measure::Cylinder, SCL.SimpleDataTypes::e, Measure::Edges, TechDrawTools.TaskFillTemplateFields::errorMsg, Part::Feature::getShape(), Measure::Invalid, Measure::Line, importers.importIFCmulticore::objects, Measure::Plane, Measure::Points, Measure::PointToEdge, Measure::PointToPoint, Measure::PointToSurface, Measure::Sphere, Measure::Surfaces, Measure::Torus, Measure::TwoLines, Measure::TwoParallelLines, Measure::TwoPlanes, and Measure::Volumes.
getMemSize()
unsigned int Measurement::getMemSize () const virtual
Definition at line 823 of file Measurement.cpp.
getPyObject()
PyObject * Measurement::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 828 of file Measurement.cpp.
References Py::new_reference_to().
getShape()
TopoDS_Shape Measurement::getShape (App::DocumentObject * obj, const char * subName) const protected
Definition at line 282 of file Measurement.cpp.
References Measure::ShapeFinder::getLocatedShape().
getType()
MeasureType Measurement::getType ()
Definition at line 277 of file Measurement.cpp.
has3DReferences()
bool Measurement::has3DReferences ()
Definition at line 76 of file Measurement.cpp.
length()
double Measurement::length () const
Definition at line 290 of file Measurement.cpp.
References Measure::Circle, Base::Console(), KDL::diff(), Measure::Edges, Base::ConsoleSingleton::Error(), importers.importIFClegacy::getShape(), Measure::Invalid, FreeCADInit::Length, Measure::Line, importers.importIFCmulticore::objects, Measure::Points, Measure::PointToEdge, Measure::PointToPoint, Measure::PointToSurface, result, Measure::TwoLines, buildPsets::u, and TestSpreadsheet::v.
Referenced by src.Mod.PartDesign.Scripts.FilletArc.Vector::norm().
lineLineDistance()
double Measurement::lineLineDistance () const
Definition at line 363 of file Measurement.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), importers.importIFClegacy::getShape(), importers.importIFCmulticore::objects, and Measure::TwoParallelLines.
linesAreParallel()
bool Measurement::linesAreParallel () const
Definition at line 788 of file Measurement.cpp.
References importers.importIFClegacy::getShape(), and importers.importIFCmulticore::objects.
massCenter()
Base::Vector3d Measurement::massCenter () const
Definition at line 703 of file Measurement.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), importers.importIFClegacy::getShape(), Measure::Invalid, importers.importIFCmulticore::objects, result, and Measure::Volumes.
planePlaneDistance()
double Measurement::planePlaneDistance () const
Definition at line 414 of file Measurement.cpp.
References ClipperLib::Abs(), importers.importIFClegacy::getShape(), importers.importIFCmulticore::objects, and Measure::TwoPlanes.
planesAreParallel()
bool Measurement::planesAreParallel () const
Definition at line 744 of file Measurement.cpp.
References SCL.SimpleDataTypes::e, TechDrawTools.TaskFillTemplateFields::errorMsg, Part::Feature::getShape(), SplineSurface::i, importers.importIFCmulticore::objects, and WorkingPlane::plane.
radius()
double Measurement::radius () const
Definition at line 524 of file Measurement.cpp.
References Measure::Circle, Base::Console(), Measure::Cylinder, Base::ConsoleSingleton::Error(), importers.importIFClegacy::getShape(), importers.importIFCmulticore::objects, Measure::Sphere, and Measure::Torus.
Referenced by Path.Op.PocketBase.ObjectPocket::areaOpAreaParams(), Path.Op.Profile.ObjectProfile::areaOpAreaParams(), Path.Op.PocketBase.ObjectPocket::areaOpPathParams(), and Path.Op.Profile.ObjectProfile::areaOpPathParams().
toVector3d()
static Base::Vector3d Measure::Measurement::toVector3d (const gp_Pnt gp) inline static
Definition at line 109 of file Measurement.h.
volume()
double Measurement::volume () const
Definition at line 655 of file Measurement.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), importers.importIFClegacy::getShape(), SplineSurface::i, importers.importIFCmulticore::objects, result, and Measure::Volumes.
Member Data Documentation
References3D
App::PropertyLinkSubList Measure::Measurement::References3D
Definition at line 67 of file Measurement.h.
The documentation for this class was generated from the following files:
Measurement.h
Measurement.cpp