FreeCAD: DlgPreferencesImp.cpp File Reference
DlgPreferencesImp.cpp File Reference
#include "PreCompiled.h"
#include <algorithm>
#include <cstring>
#include <QAbstractButton>
#include <QApplication>
#include <QCursor>
#include <QDebug>
#include <QMenu>
#include <QMessageBox>
#include <QScreen>
#include <QScrollArea>
#include <QScrollBar>
#include <QTimer>
#include <QToolTip>
#include <QProcess>
#include <QPushButton>
#include <QWindow>
#include <App/Application.h>
#include <Base/Console.h>
#include <Base/Exception.h>
#include <Base/Tools.h>
#include "DlgPreferencesImp.h"
#include "ui_DlgPreferences.h"
#include "BitmapFactory.h"
#include "MainWindow.h"
#include "Tools.h"
#include "WidgetFactory.h"
#include "moc_DlgPreferencesImp.cpp"
Functions
bool isParentOf (const QModelIndex &parent, const QModelIndex &child)
QModelIndex findRootIndex (const QModelIndex &index)
Q_DECLARE_METATYPE (PreferencesPageItem *)
Function Documentation
findRootIndex()
QModelIndex findRootIndex (const QModelIndex & index)
Definition at line 70 of file DlgPreferencesImp.cpp.
Referenced by Gui::Dialog::DlgPreferencesImp::onGroupCollapsed(), Gui::Dialog::DlgPreferencesImp::onGroupExpanded(), and Gui::Dialog::DlgPreferencesImp::onPageSelected().
isParentOf()
bool isParentOf (const QModelIndex & parent, const QModelIndex & child)
Definition at line 59 of file DlgPreferencesImp.cpp.
References Init::parent.
Referenced by Gui::Dialog::DlgPreferencesImp::onStackWidgetChange().
Q_DECLARE_METATYPE()
Q_DECLARE_METATYPE (PreferencesPageItem *)