FreeCAD: FemGui::TaskFemConstraintTemperature Class Reference
FemGui::TaskFemConstraintTemperature Class Reference
#include <TaskFemConstraintTemperature.h>
Public Member Functions
TaskFemConstraintTemperature (ViewProviderFemConstraintTemperature *ConstraintView, QWidget *parent=nullptr)
~TaskFemConstraintTemperature () override
const std::string getReferences () const override
std::string get_temperature () const
std::string get_cflux () const
std::string get_constraint_type () const
Public Member Functions inherited from FemGui::TaskFemConstraintOnBoundary
TaskFemConstraintOnBoundary (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="")
~TaskFemConstraintOnBoundary () override
Public Member Functions inherited from FemGui::TaskFemConstraint
TaskFemConstraint (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="")
~TaskFemConstraint () override=default
const std::string getReferences (const std::vector< std::string > &items) const
const std::string getScale () const
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Protected Member Functions
void changeEvent (QEvent *e) override
void clearButtons (const SelectionChangeModes notThis) override
Protected Member Functions inherited from FemGui::TaskFemConstraintOnBoundary
void onSelectionChanged (const Gui::SelectionChanges &) override
Protected Member Functions inherited from FemGui::TaskFemConstraint
void changeEvent (QEvent *e) override
const QString makeRefText (const std::string &objName, const std::string &subName) const
const QString makeRefText (const App::DocumentObject *obj, const std::string &subName) const
void keyPressEvent (QKeyEvent *ke) override
void createDeleteAction (QListWidget *parentList)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Protected Types inherited from FemGui::TaskFemConstraintOnBoundary
enum SelectionChangeModes { SelectionChangeModes::none, SelectionChangeModes::refAdd, SelectionChangeModes::refRemove }
Protected Types inherited from FemGui::TaskFemConstraint
enum { seldir, selref, selloc, selnone }
Protected Slots inherited from FemGui::TaskFemConstraintOnBoundary
void onButtonToggled (QAbstractButton *button, bool checked)
virtual void addToSelection ()=0
virtual void removeFromSelection ()=0
Protected Slots inherited from FemGui::TaskFemConstraint
void onReferenceDeleted (const int row)
void onButtonReference (const bool pressed=true)
void setSelection (QListWidgetItem *item)
bool event (QEvent *event) override
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Attributes inherited from FemGui::TaskFemConstraintOnBoundary
enum SelectionChangeModes selChangeMode
Gui::ButtonGroup * buttonGroup
Protected Attributes inherited from FemGui::TaskFemConstraint
QWidget * proxy
QAction * deleteAction
Gui::WeakPtrT< ViewProviderFemConstraint > ConstraintView
enum FemGui::TaskFemConstraint:: { ... } selectionMode
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
Definition at line 43 of file TaskFemConstraintTemperature.h.
Constructor & Destructor Documentation
TaskFemConstraintTemperature()
TaskFemConstraintTemperature::TaskFemConstraintTemperature (ViewProviderFemConstraintTemperature * ConstraintView, QWidget * parent = nullptr) explicit
Definition at line 50 of file TaskFemConstraintTemperature.cpp.
References FemGui::TaskFemConstraintOnBoundary::buttonGroup, Fem::ConstraintTemperature::CFlux, draftgeoutils.intersections::connect(), Fem::ConstraintTemperature::ConstraintType, FemGui::TaskFemConstraint::ConstraintView, FemGui::TaskFemConstraint::createDeleteAction(), FemGui::TaskFemConstraint::deleteAction, FLOAT_MAX, App::PropertyEnumeration::getEnumVector(), App::PropertyQuantity::getQuantityValue(), App::PropertyLinkSubList::getSubValues(), App::PropertyQuantity::getUnit(), App::PropertyEnumeration::getValue(), App::PropertyLinkSubList::getValues(), QSint::ActionGroup::groupLayout(), SplineSurface::i, FemGui::TaskFemConstraint::makeRefText(), FemGui::TaskFemConstraint::proxy, FemGui::TaskFemConstraintOnBoundary::refAdd, Fem::Constraint::References, FemGui::TaskFemConstraintOnBoundary::refRemove, FemGui::TaskFemConstraint::setSelection(), Fem::ConstraintTemperature::Temperature, and Gui::QuantitySpinBox::valueChanged().
~TaskFemConstraintTemperature()
TaskFemConstraintTemperature::~TaskFemConstraintTemperature () override default
Member Function Documentation
changeEvent()
void TaskFemConstraintTemperature::changeEvent (QEvent * e) override protected
Definition at line 322 of file TaskFemConstraintTemperature.cpp.
clearButtons()
void TaskFemConstraintTemperature::clearButtons (const SelectionChangeModes notThis) override protected virtual
Implements FemGui::TaskFemConstraintOnBoundary.
Definition at line 332 of file TaskFemConstraintTemperature.cpp.
References FemGui::TaskFemConstraintOnBoundary::refAdd, and FemGui::TaskFemConstraintOnBoundary::refRemove.
get_cflux()
std::string TaskFemConstraintTemperature::get_cflux () const
Definition at line 312 of file TaskFemConstraintTemperature.cpp.
Referenced by FemGui::TaskDlgFemConstraintTemperature::accept().
get_constraint_type()
std::string TaskFemConstraintTemperature::get_constraint_type () const
Definition at line 317 of file TaskFemConstraintTemperature.cpp.
Referenced by FemGui::TaskDlgFemConstraintTemperature::accept().
get_temperature()
std::string TaskFemConstraintTemperature::get_temperature () const
Definition at line 307 of file TaskFemConstraintTemperature.cpp.
Referenced by FemGui::TaskDlgFemConstraintTemperature::accept().
getReferences()
const std::string TaskFemConstraintTemperature::getReferences () const override virtual
Reimplemented from FemGui::TaskFemConstraint.
Definition at line 297 of file TaskFemConstraintTemperature.cpp.
References FemGui::TaskFemConstraint::getReferences(), and src.Mod.Test.testPathArray::items.
The documentation for this class was generated from the following files:
TaskFemConstraintTemperature.h
TaskFemConstraintTemperature.cpp