FreeCAD: OverlayManager.cpp File Reference
OverlayManager.cpp File Reference
#include "PreCompiled.h"
#include <QAction>
#include <QApplication>
#include <QComboBox>
#include <QDockWidget>
#include <QFile>
#include <QGraphicsView>
#include <QHeaderView>
#include <QKeyEvent>
#include <QMdiArea>
#include <QMenu>
#include <QPainter>
#include <QPointer>
#include <QTextStream>
#include <QTimerEvent>
#include <QToolTip>
#include <QScrollBar>
#include <QPainterPath>
#include <QPropertyAnimation>
#include <array>
#include <unordered_map>
#include "OverlayManager.h"
#include <Base/Console.h>
#include <Base/Parameter.h>
#include <Base/Tools.h>
#include <App/Application.h>
#include "Application.h"
#include "BitmapFactory.h"
#include "Control.h"
#include "MainWindow.h"
#include "MDIView.h"
#include "NaviCube.h"
#include "OverlayParams.h"
#include "OverlayWidgets.h"
#include "TaskView/TaskView.h"
#include "Tree.h"
#include "TreeParams.h"
#include "View3DInventorViewer.h"
#include "moc_OverlayManager.cpp"
Classes
class OverlayStyleSheet
struct OverlayInfo
class Gui::OverlayManager::Private
Enumerations
enum ToggleMode {
ToggleMode::Unset, ToggleMode::Set, ToggleMode::Toggle, ToggleMode::Transparent,
ToggleMode::Check
}
Functions
FC_LOG_LEVEL_INIT ("Dock", true, true)
static OverlayTabWidget * findTabWidget (QWidget *widget=nullptr, bool filterDialog=false)
static bool isNear (const QPoint &a, const QPoint &b, int tol=16)
Variables
static std::array< OverlayTabWidget *, 4 > _Overlays
static OverlayManager * _instance
Enumeration Type Documentation
ToggleMode
enum ToggleMode strong
Enumerator
Unset
Set
Toggle
Transparent
Check
Definition at line 297 of file OverlayManager.cpp.
Function Documentation
FC_LOG_LEVEL_INIT()
FC_LOG_LEVEL_INIT ("Dock" , true , true)
findTabWidget()
static OverlayTabWidget* findTabWidget (QWidget * widget = nullptr, bool filterDialog = false) inline static
Definition at line 75 of file OverlayManager.cpp.
References src.Mod.PartDesign.fcgear.svggear::w.
Referenced by OverlayInfo::addWidget(), Gui::OverlayManager::eventFilter(), Gui::OverlayManager::isUnderOverlay(), Gui::OverlayManager::Private::onTimer(), and Gui::OverlayManager::Private::refresh().
isNear()
static bool isNear (const QPoint & a, const QPoint & b, int tol = 16) inline static
Definition at line 1611 of file OverlayManager.cpp.
References a, and SCL.SimpleDataTypes::b.
Referenced by Gui::OverlayManager::eventFilter().
Variable Documentation
_instance
OverlayManager* _instance static
Definition at line 1442 of file OverlayManager.cpp.
Referenced by PartDesignGui::WorkflowManager::destruct(), Gui::OverlayManager::destruct(), PartDesignGui::WorkflowManager::init(), PartDesignGui::WorkflowManager::instance(), and Gui::OverlayManager::instance().
_Overlays
std::array<OverlayTabWidget*, 4> _Overlays static
Definition at line 73 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::Private::dragDockWidget(), Gui::OverlayManager::eventFilter(), Gui::OverlayManager::Private::raiseAll(), Gui::OverlayManager::Private::refreshIcons(), and Gui::OverlayManager::Private::setMouseTransparent().