FreeCAD: SIM::Coin3D::Quarter::SensorManager Class Reference
SIM::Coin3D::Quarter::SensorManager Class Reference
#include <SensorManager.h>
Public Slots
void idleTimeout ()
void delayTimeout ()
void timerQueueTimeout ()
void sensorQueueChanged ()
void setTimerEpsilon (double sec)
Public Member Functions
SensorManager ()
~SensorManager () override
Detailed Description
Definition at line 44 of file SensorManager.h.
Constructor & Destructor Documentation
SensorManager()
SensorManager::SensorManager ()
Definition at line 47 of file SensorManager.cpp.
References draftgeoutils.intersections::connect(), delayTimeout(), idleTimeout(), sensorQueueChanged(), timerQueueTimeout(), and SIM::Coin3D::Quarter::SignalThread::triggerSignal().
~SensorManager()
SensorManager::~SensorManager () override
Definition at line 75 of file SensorManager.cpp.
References SIM::Coin3D::Quarter::SignalThread::stopThread().
Member Function Documentation
delayTimeout
void SensorManager::delayTimeout () slot
Definition at line 163 of file SensorManager.cpp.
References sensorQueueChanged().
Referenced by SensorManager().
idleTimeout
void SensorManager::idleTimeout () slot
Definition at line 148 of file SensorManager.cpp.
References sensorQueueChanged().
Referenced by SensorManager().
sensorQueueChanged
void SensorManager::sensorQueueChanged () slot
Definition at line 108 of file SensorManager.cpp.
Referenced by delayTimeout(), idleTimeout(), SensorManager(), and timerQueueTimeout().
setTimerEpsilon
void SensorManager::setTimerEpsilon (double sec) slot
Definition at line 171 of file SensorManager.cpp.
timerQueueTimeout
void SensorManager::timerQueueTimeout () slot
Definition at line 156 of file SensorManager.cpp.
References sensorQueueChanged().
Referenced by SensorManager().
The documentation for this class was generated from the following files:
SensorManager.h
SensorManager.cpp