FreeCAD: Gui::ModuleIO Class Reference
Gui::ModuleIO Class Reference
#include <ModuleIO.h>
Static Public Member Functions
static bool verifyFile (const QString &filename)
verifyFile Verifies the existence of the file. If it doesn't exist an error dialog pops up and false is returned, otherwise true is returned.
static void openFile (const QString &filename)
openFile Opens the file. The handling module is supposed to create a new document.
static void verifyAndOpenFile (const QString &filename)
verifyAndOpenFile Verifies the existence of the file and opens it. The handling module is supposed to create a new document.
static void importFiles (const QStringList &filenames, const char *document)
importFile Imports the files into the given document. The handling module is supposed to create a new document if the passed document doesn't exist.
Detailed Description
Definition at line 51 of file ModuleIO.h.
Member Function Documentation
importFiles()
void ModuleIO::importFiles (const QStringList & filenames, const char * document) static
importFile Imports the files into the given document. The handling module is supposed to create a new document if the passed document doesn't exist.
Parameters
filename
document
Definition at line 71 of file ModuleIO.cpp.
References Path.Base.SetupSheet::dict, Gui::Application::importFrom(), Gui::SelectModule::importHandler(), and Gui::Application::Instance.
Referenced by Gui::MainWindow::loadUrls().
openFile()
void ModuleIO::openFile (const QString & filename) static
openFile Opens the file. The handling module is supposed to create a new document.
Parameters
filename
Definition at line 54 of file ModuleIO.cpp.
References Path.Base.SetupSheet::dict, Gui::SelectModule::importHandler(), Gui::Application::Instance, and Gui::Application::open().
Referenced by Gui::RecentFilesAction::activateFile(), and verifyAndOpenFile().
verifyAndOpenFile()
void ModuleIO::verifyAndOpenFile (const QString & filename) static
verifyAndOpenFile Verifies the existence of the file and opens it. The handling module is supposed to create a new document.
Parameters
filename
Definition at line 64 of file ModuleIO.cpp.
References openFile(), and verifyFile().
Referenced by StartGui::StartView::fileCardSelected().
verifyFile()
bool ModuleIO::verifyFile (const QString & filename) static
verifyFile Verifies the existence of the file. If it doesn't exist an error dialog pops up and false is returned, otherwise true is returned.
Parameters
filename
Returns
Definition at line 41 of file ModuleIO.cpp.
References Gui::getMainWindow().
Referenced by Gui::RecentFilesAction::activateFile(), Gui::RecentMacrosAction::activateFile(), and verifyAndOpenFile().
The documentation for this class was generated from the following files:
ModuleIO.h
ModuleIO.cpp