FreeCAD: CAMTests.TestPathVoronoi.TestPathVoronoi Class Reference
CAMTests.TestPathVoronoi.TestPathVoronoi Class Reference
Public Member Functions
def setUp (self)
def test00 (self)
def test10 (self)
def test20 (self)
def test50 (self)
def test51 (self)
def test52 (self)
def test60 (self)
def test61 (self)
def test62 (self)
Public Member Functions inherited from CAMTests.PathTestUtils.PathTestBase
def assertRoughly (self, f1, f2, error=0.00001)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertPlacement (self, p1, p2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertArc (self, edge, pt1, pt2, direction="CW")
def assertCircle (self, edge, pt, r)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCommandEqual (self, c1, c2)
def assertEqualLocale (self, s1, s2)
def assertEdgeShapesMatch (self, e1, e2)
def assertPointsMatch (self, pts0, pts1)
def assertSuccessfulRecompute (self, doc, *objs, msg=None)
Detailed Description
Definition at line 65 of file TestPathVoronoi.py.
Member Function Documentation
setUp()
def CAMTests.TestPathVoronoi.TestPathVoronoi.setUp (self)
Definition at line 66 of file TestPathVoronoi.py.
References CAMTests.TestPathVoronoi.initVD().
test00()
def CAMTests.TestPathVoronoi.TestPathVoronoi.test00 (self)
Check vertex comparison
Definition at line 69 of file TestPathVoronoi.py.
test10()
def CAMTests.TestPathVoronoi.TestPathVoronoi.test10 (self)
Check edge comparison
Definition at line 80 of file TestPathVoronoi.py.
test20()
def CAMTests.TestPathVoronoi.TestPathVoronoi.test20 (self)
Check cell comparison
Definition at line 91 of file TestPathVoronoi.py.
test50()
def CAMTests.TestPathVoronoi.TestPathVoronoi.test50 (self)
Check toShape for linear edges
Definition at line 102 of file TestPathVoronoi.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly(), Path.Geom.pointsCoincide(), and Path.Post.scripts.grbl_post.type.
test51()
def CAMTests.TestPathVoronoi.TestPathVoronoi.test51 (self)
Check toShape for linear edges with set z
Definition at line 117 of file TestPathVoronoi.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly(), Path.Geom.pointsCoincide(), and Path.Post.scripts.grbl_post.type.
test52()
def CAMTests.TestPathVoronoi.TestPathVoronoi.test52 (self)
Check toShape for linear edges with varying z
Definition at line 132 of file TestPathVoronoi.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly(), Path.Geom.pointsCoincide(), and Path.Post.scripts.grbl_post.type.
test60()
def CAMTests.TestPathVoronoi.TestPathVoronoi.test60 (self)
Check toShape for curved edges
Definition at line 147 of file TestPathVoronoi.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly(), Path.Geom.pointsCoincide(), and Path.Post.scripts.grbl_post.type.
test61()
def CAMTests.TestPathVoronoi.TestPathVoronoi.test61 (self)
Check toShape for curved edges with set z
Definition at line 162 of file TestPathVoronoi.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly(), Path.Geom.pointsCoincide(), and Path.Post.scripts.grbl_post.type.
test62()
def CAMTests.TestPathVoronoi.TestPathVoronoi.test62 (self)
Check toShape for curved edges with varying z
Definition at line 177 of file TestPathVoronoi.py.
References CAMTests.PathTestUtils.PathTestBase.assertRoughly(), Path.Geom.pointsCoincide(), and Path.Post.scripts.grbl_post.type.
The documentation for this class was generated from the following file:
TestPathVoronoi.py