FreeCAD: src.Mod.AddonManager.AddonManagerTest.app.mocks.MockExists Class Reference
src.Mod.AddonManager.AddonManagerTest.app.mocks.MockExists Class Reference
Public Member Functions
def __init__ (self, List[str] files=None)
def exists (self, str check_file)
Public Attributes
files
files_checked
Detailed Description
Definition at line 450 of file mocks.py.
Constructor & Destructor Documentation
__init__()
def src.Mod.AddonManager.AddonManagerTest.app.mocks.MockExists.__init__ (self, List[str] files = None)
Returns True for all files in files, and False for all others
Definition at line 451 of file mocks.py.
Referenced by draftguitools.gui_subelements.SubelementHighlight.finish().
Member Function Documentation
exists()
def src.Mod.AddonManager.AddonManagerTest.app.mocks.MockExists.exists (self, str check_file)
Definition at line 456 of file mocks.py.
References Path.Post.scripts.uccnc_post.append(), src.Mod.AddonManager.AddonManagerTest.app.mocks.MockExists.files, and src.Mod.AddonManager.AddonManagerTest.app.mocks.MockExists.files_checked.
Referenced by ArchReference.ArchReference.getFile().
Member Data Documentation
files
src.Mod.AddonManager.AddonManagerTest.app.mocks.MockExists.files
Definition at line 453 of file mocks.py.
Referenced by src.Mod.AddonManager.AddonManagerTest.app.mocks.MockExists.exists().
files_checked
src.Mod.AddonManager.AddonManagerTest.app.mocks.MockExists.files_checked
Definition at line 454 of file mocks.py.
Referenced by src.Mod.AddonManager.AddonManagerTest.app.mocks.MockExists.exists().
The documentation for this class was generated from the following file:
mocks.py