FreeCAD: Path.Post.scripts.fanuc_post Namespace Reference
Path.Post.scripts.fanuc_post Namespace Reference
Functions
def processArguments (argstring)
def export (objectslist, filename, argstring)
def linenumber ()
def parse (pathobj)
Variables
TOOLTIP
now
parser
prog
add_help
action = "store_true",
help = "don't pop up editor before writing output",
default
TOOLTIP_ARGS
OUTPUT_COMMENTS
OUTPUT_HEADER
OUTPUT_LINE_NUMBERS
SHOW_EDITOR
MODAL
USE_TLO
OUTPUT_DOUBLES
COMMAND_SPACE
LINENR
UNITS
UNIT_SPEED_FORMAT
UNIT_FORMAT
MACHINE_NAME
CORNER_MIN
CORNER_MAX
PRECISION
tapSpeed
PREAMBLE
POSTAMBLE
PRE_OPERATION
POST_OPERATION
TOOL_CHANGE
Function Documentation
export()
def Path.Post.scripts.fanuc_post.export (objectslist, filename, argstring)
Definition at line 185 of file fanuc_post.py.
References Path.Post.scripts.fanuc_post.linenumber(), Path.Post.scripts.fanuc_post.parse(), Path.Post.scripts.fanuc_post.processArguments(), and Path.Post.scripts.refactored_centroid_post.str.
linenumber()
def Path.Post.scripts.fanuc_post.linenumber ()
Definition at line 304 of file fanuc_post.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.fanuc_post.export(), and Path.Post.scripts.fanuc_post.parse().
parse()
def Path.Post.scripts.fanuc_post.parse (pathobj)
Definition at line 312 of file fanuc_post.py.
References Path.Post.scripts.fanuc_post.linenumber(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.fanuc_post.export().
processArguments()
def Path.Post.scripts.fanuc_post.processArguments (argstring)
Definition at line 136 of file fanuc_post.py.
Referenced by Path.Post.scripts.fanuc_post.export().
Variable Documentation
action
string Path.Post.scripts.fanuc_post.action = "store_true",
Definition at line 52 of file fanuc_post.py.
add_help
Path.Post.scripts.fanuc_post.add_help
Definition at line 51 of file fanuc_post.py.
COMMAND_SPACE
Path.Post.scripts.fanuc_post.COMMAND_SPACE
Definition at line 98 of file fanuc_post.py.
CORNER_MAX
Path.Post.scripts.fanuc_post.CORNER_MAX
Definition at line 108 of file fanuc_post.py.
CORNER_MIN
Path.Post.scripts.fanuc_post.CORNER_MIN
Definition at line 107 of file fanuc_post.py.
default
Path.Post.scripts.fanuc_post.default
Definition at line 60 of file fanuc_post.py.
help
string Path.Post.scripts.fanuc_post.help = "don't pop up editor before writing output",
Definition at line 52 of file fanuc_post.py.
LINENR
Path.Post.scripts.fanuc_post.LINENR
Definition at line 99 of file fanuc_post.py.
MACHINE_NAME
Path.Post.scripts.fanuc_post.MACHINE_NAME
Definition at line 106 of file fanuc_post.py.
MODAL
Path.Post.scripts.fanuc_post.MODAL
Definition at line 93 of file fanuc_post.py.
now
Path.Post.scripts.fanuc_post.now
Definition at line 49 of file fanuc_post.py.
OUTPUT_COMMENTS
Path.Post.scripts.fanuc_post.OUTPUT_COMMENTS
Definition at line 89 of file fanuc_post.py.
OUTPUT_DOUBLES
Path.Post.scripts.fanuc_post.OUTPUT_DOUBLES
Definition at line 95 of file fanuc_post.py.
OUTPUT_HEADER
Path.Post.scripts.fanuc_post.OUTPUT_HEADER
Definition at line 90 of file fanuc_post.py.
OUTPUT_LINE_NUMBERS
Path.Post.scripts.fanuc_post.OUTPUT_LINE_NUMBERS
Definition at line 91 of file fanuc_post.py.
parser
Path.Post.scripts.fanuc_post.parser
Definition at line 51 of file fanuc_post.py.
POST_OPERATION
Path.Post.scripts.fanuc_post.POST_OPERATION
Definition at line 130 of file fanuc_post.py.
POSTAMBLE
Path.Post.scripts.fanuc_post.POSTAMBLE
Definition at line 120 of file fanuc_post.py.
PRE_OPERATION
Path.Post.scripts.fanuc_post.PRE_OPERATION
Definition at line 127 of file fanuc_post.py.
PREAMBLE
Path.Post.scripts.fanuc_post.PREAMBLE
Definition at line 116 of file fanuc_post.py.
PRECISION
Path.Post.scripts.fanuc_post.PRECISION
Definition at line 109 of file fanuc_post.py.
prog
Path.Post.scripts.fanuc_post.prog
Definition at line 51 of file fanuc_post.py.
SHOW_EDITOR
Path.Post.scripts.fanuc_post.SHOW_EDITOR
Definition at line 92 of file fanuc_post.py.
tapSpeed
Path.Post.scripts.fanuc_post.tapSpeed
Definition at line 113 of file fanuc_post.py.
TOOL_CHANGE
Path.Post.scripts.fanuc_post.TOOL_CHANGE
Definition at line 133 of file fanuc_post.py.
TOOLTIP
Path.Post.scripts.fanuc_post.TOOLTIP
Definition at line 36 of file fanuc_post.py.
TOOLTIP_ARGS
Path.Post.scripts.fanuc_post.TOOLTIP_ARGS
Definition at line 86 of file fanuc_post.py.
UNIT_FORMAT
Path.Post.scripts.fanuc_post.UNIT_FORMAT
Definition at line 104 of file fanuc_post.py.
UNIT_SPEED_FORMAT
Path.Post.scripts.fanuc_post.UNIT_SPEED_FORMAT
Definition at line 103 of file fanuc_post.py.
UNITS
Path.Post.scripts.fanuc_post.UNITS
Definition at line 102 of file fanuc_post.py.
USE_TLO
Path.Post.scripts.fanuc_post.USE_TLO
Definition at line 94 of file fanuc_post.py.