FreeCAD: FemGui::TaskCreateElementSet Class Reference
FemGui::TaskCreateElementSet Class Reference
#include <TaskCreateElementSet.h>
Public Member Functions
TaskCreateElementSet (Fem::FemSetElementNodesObject *pcObject, QWidget *parent=nullptr)
~TaskCreateElementSet () override
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Public Attributes
std::set< long > elementTempSet
ViewProviderFemMesh * MeshViewProvider
Static Public Attributes
static std::string currentProject = ""
Protected Types
enum selectionModes { none, PickElement }
Protected Member Functions
void DefineNodes (const Base::Polygon2d &polygon, const Gui::ViewVolumeProjection &proj, bool)
void onSelectionChanged (const Gui::SelectionChanges &msg) override
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Static Protected Member Functions
static void DefineElementsCallback (void *ud, SoEventCallback *n)
Protected Attributes
Fem::FemSetElementNodesObject * pcObject
enum FemGui::TaskCreateElementSet::selectionModes selectionMode
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
Definition at line 55 of file TaskCreateElementSet.h.
Member Enumeration Documentation
selectionModes
enum FemGui::TaskCreateElementSet::selectionModes protected
Enumerator
none
PickElement
Definition at line 80 of file TaskCreateElementSet.h.
Constructor & Destructor Documentation
TaskCreateElementSet()
TaskCreateElementSet::TaskCreateElementSet (Fem::FemSetElementNodesObject * pcObject, QWidget * parent = nullptr) explicit
Definition at line 439 of file TaskCreateElementSet.cpp.
References draftgeoutils.intersections::connect(), currentProject, toolbit-attributes::doc, Fem::FemSetElementNodesObject::Elements, elementTempSet, Fem::FemSetObject::FemMesh, App::Application::getActiveDocument(), App::GetApplication(), Gui::getMainWindow(), App::PropertyLink::getValue(), App::PropertyIntegerSet::getValues(), Gui::Application::getViewProvider(), QSint::ActionGroup::groupLayout(), Path.Log::info(), Gui::Application::Instance, MeshViewProvider, pcObject, and Path.Log::warning().
~TaskCreateElementSet()
TaskCreateElementSet::~TaskCreateElementSet () override
Definition at line 797 of file TaskCreateElementSet.cpp.
References Gui::Command::Doc, and doCommand.
Member Function Documentation
DefineElementsCallback()
void TaskCreateElementSet::DefineElementsCallback (void * ud, SoEventCallback * n) static protected
Definition at line 574 of file TaskCreateElementSet.cpp.
References DefineNodes(), Gui::View3DInventorViewer::getGLPolygon(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), Gui::Inner, Gui::View3DInventorViewer::removeEventCallback(), and Gui::View3DInventorViewer::setEditing().
DefineNodes()
void TaskCreateElementSet::DefineNodes (const Base::Polygon2d & polygon, const Gui::ViewVolumeProjection & proj, bool inner) protected
Definition at line 605 of file TaskCreateElementSet.cpp.
References Base::Console(), currentProject, Gui::Command::Doc, doCommand, elementTempSet, Fem::FemSetObject::FemMesh, Gui::getMainWindow(), Gui::SelectionSingleton::getSelection(), App::PropertyLink::getValue(), SplineSurface::i, pcObject, Path.Dressup.Utils::selection(), Gui::Selection(), SurfaceTests.TestBlendCurve::vec, Path.Log::warning(), Base::ConsoleSingleton::Warning(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by DefineElementsCallback().
onSelectionChanged()
void TaskCreateElementSet::onSelectionChanged (const Gui::SelectionChanges & msg) override protected virtual
Implements Gui::SelectionObserver.
Definition at line 767 of file TaskCreateElementSet.cpp.
References Gui::SelectionChanges::AddSelection, elementTempSet, Fem::FemSetObject::FemMesh, App::PropertyLink::getValue(), SplineSurface::i, Path.Op.Surface::msg, none, pcObject, Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), and selectionMode.
Member Data Documentation
currentProject
std::string TaskCreateElementSet::currentProject = "" static
Definition at line 66 of file TaskCreateElementSet.h.
Referenced by DefineNodes(), and TaskCreateElementSet().
elementTempSet
std::set<long> FemGui::TaskCreateElementSet::elementTempSet
Definition at line 64 of file TaskCreateElementSet.h.
Referenced by FemGui::TaskDlgCreateElementSet::accept(), DefineNodes(), onSelectionChanged(), and TaskCreateElementSet().
MeshViewProvider
ViewProviderFemMesh* FemGui::TaskCreateElementSet::MeshViewProvider
Definition at line 65 of file TaskCreateElementSet.h.
Referenced by FemGui::TaskDlgCreateElementSet::accept(), FemGui::TaskDlgCreateElementSet::reject(), and TaskCreateElementSet().
pcObject
Fem::FemSetElementNodesObject* FemGui::TaskCreateElementSet::pcObject protected
Definition at line 74 of file TaskCreateElementSet.h.
Referenced by DefineNodes(), onSelectionChanged(), and TaskCreateElementSet().
selectionMode
enum FemGui::TaskCreateElementSet::selectionModes FemGui::TaskCreateElementSet::selectionMode protected
Referenced by onSelectionChanged().
The documentation for this class was generated from the following files:
TaskCreateElementSet.h
TaskCreateElementSet.cpp