FreeCAD: src.Mod.Test.TestApp Namespace Reference
src.Mod.Test.TestApp Namespace Reference
Functions
def tryLoadingTest (testName)
def All ()
def PrintAll ()
def TestText (s)
def Test (s)
def testAll ()
def testUnit ()
def testDocument ()
Variables
testName
Function Documentation
All()
def src.Mod.Test.TestApp.All ()
Definition at line 58 of file TestApp.py.
References src.Mod.Test.TestApp.tryLoadingTest().
Referenced by src.Mod.Test.TestApp.testAll().
PrintAll()
def src.Mod.Test.TestApp.PrintAll ()
Definition at line 70 of file TestApp.py.
Test()
def src.Mod.Test.TestApp.Test (s)
Definition at line 96 of file TestApp.py.
References src.Mod.Test.TestApp.TestText().
Referenced by loadTestResource().
testAll()
def src.Mod.Test.TestApp.testAll ()
Definition at line 100 of file TestApp.py.
References src.Mod.Test.TestApp.All().
testDocument()
def src.Mod.Test.TestApp.testDocument ()
Definition at line 109 of file TestApp.py.
References src.Mod.Test.TestApp.TestText().
TestText()
def src.Mod.Test.TestApp.TestText (s)
Definition at line 84 of file TestApp.py.
Referenced by src.Mod.Test.TestApp.Test(), src.Mod.Test.TestApp.testDocument(), and src.Mod.Test.TestApp.testUnit().
testUnit()
def src.Mod.Test.TestApp.testUnit ()
Definition at line 105 of file TestApp.py.
References src.Mod.Test.TestApp.TestText().
tryLoadingTest()
def src.Mod.Test.TestApp.tryLoadingTest (testName)
Definition at line 34 of file TestApp.py.
Referenced by src.Mod.Test.TestApp.All().
Variable Documentation
testName
src.Mod.Test.TestApp.testName
Definition at line 47 of file TestApp.py.