FreeCAD: Gui::PropertyEditor::PropertyEditor Class Reference
Gui::PropertyEditor::PropertyEditor Class Reference
#include <PropertyEditor.h>
Public Member Functions
PropertyEditor (QWidget *parent=nullptr)
~PropertyEditor () override
void buildUp (PropertyModel::PropertyList &&props=PropertyModel::PropertyList(), bool checkDocument=false)
void updateProperty (const App::Property &)
void removeProperty (const App::Property &)
void setAutomaticExpand (bool)
bool isAutomaticExpand (bool) const
void setAutomaticDocumentUpdate (bool)
bool isAutomaticDocumentUpdate (bool) const
void reset () override
QBrush groupBackground () const
void setGroupBackground (const QBrush &c)
QColor groupTextColor () const
void setGroupTextColor (const QColor &c)
QBrush itemBackground () const
void setItemBackground (const QBrush &c)
bool isBinding () const
void openEditor (const QModelIndex &index)
void closeEditor ()
Protected Slots
void onItemActivated (const QModelIndex &index)
void onItemExpanded (const QModelIndex &index)
void onItemCollapsed (const QModelIndex &index)
void onRowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &dst, int row)
void onRowsRemoved (const QModelIndex &parent, int start, int end)
Protected Member Functions
bool eventFilter (QObject *object, QEvent *event) override
void closeEditor (QWidget *editor, QAbstractItemDelegate::EndEditHint hint) override
void commitData (QWidget *editor) override
void editorDestroyed (QObject *editor) override
void currentChanged (const QModelIndex &current, const QModelIndex &previous) override
void rowsInserted (const QModelIndex &parent, int start, int end) override
void rowsAboutToBeRemoved (const QModelIndex &parent, int start, int end) override
void drawBranches (QPainter *painter, const QRect &rect, const QModelIndex &index) const override
void drawRow (QPainter *painter, const QStyleOptionViewItem &options, const QModelIndex &index) const override
void initViewItemOption (QStyleOptionViewItem *option) const override
void contextMenuEvent (QContextMenuEvent *event) override
bool event (QEvent *) override
Properties
QBrush groupBackground
QColor groupTextColor
QBrush itemBackground
Friends
class Gui::PropertyView
class PropertyItemDelegate
Detailed Description
Put this into the .qss file after Gui–PropertyEditor–PropertyEditor
Gui–PropertyEditor–PropertyEditor { qproperty-groupBackground: gray; qproperty-groupTextColor: white; }
See also: https://man42.net/blog/2011/09/qt-4-7-modify-a-custom-q_property-with-a-qt-style-sheet/
Definition at line 63 of file PropertyEditor.h.
Constructor & Destructor Documentation
PropertyEditor()
PropertyEditor::PropertyEditor (QWidget * parent = nullptr)
Definition at line 54 of file PropertyEditor.cpp.
References draftgeoutils.intersections::connect(), App::GetApplication(), ParameterGrp::GetInt(), and App::Application::GetParameterGroupByPath().
~PropertyEditor()
PropertyEditor::~PropertyEditor () override
Definition at line 113 of file PropertyEditor.cpp.
References SCL.SimpleDataTypes::f.
Member Function Documentation
buildUp()
void PropertyEditor::buildUp (PropertyModel::PropertyList && props = PropertyModel::PropertyList(), bool checkDocument = false)
Builds up the list view with the properties.
Definition at line 610 of file PropertyEditor.cpp.
References Gui::PropertyEditor::PropertyModel::buildUp(), Base::Console(), Base::Persistence::getClassTypeId(), Path.Post.scripts.opensbp_post::move(), Gui::PropertyEditor::PropertyModel::propertyIndexFromPath(), Gui::PropertyEditor::PropertyModel::propertyPathFromIndex(), TestSpreadsheet::v, and Base::ConsoleSingleton::Warning().
Referenced by contextMenuEvent(), Gui::PropertyView::hideEvent(), Gui::PropertyView::onTimer(), and Gui::PropertyView::setShowAll().
closeEditor() [1/2]
void PropertyEditor::closeEditor ()
Definition at line 262 of file PropertyEditor.cpp.
References Gui::MainWindow::getInstance().
Referenced by closeEditor(), contextMenuEvent(), and openEditor().
closeEditor() [2/2]
void PropertyEditor::closeEditor (QWidget * editor, QAbstractItemDelegate::EndEditHint hint) override protected
Definition at line 406 of file PropertyEditor.cpp.
References Gui::PropertyEditor::PropertyModel::buddy(), closeEditor(), Path.Post.Utils::editor(), and openEditor().
commitData()
void PropertyEditor::commitData (QWidget * editor) override protected
Definition at line 224 of file PropertyEditor.cpp.
References Gui::PropertyEditor::PropertyModel::buildUp(), and Path.Post.Utils::editor().
contextMenuEvent()
void PropertyEditor::contextMenuEvent (QContextMenuEvent * event) override protected
Definition at line 714 of file PropertyEditor.cpp.
References _ACTION_SETUP, Path.Post.scripts.dynapath_4060_post::action, ACTION_CHECK, ACTION_SETUP, Gui::PropertyEditor::PropertyModel::buddy(), buildUp(), closeEditor(), SCL.SimpleDataTypes::e, Base::Persistence::getClassTypeId(), importDXF::getGroup(), Gui::getMainWindow(), Gui::SelectionSingleton::getSelection(), importers.exportIFC::getText(), toolbit-attributes::group, App::Property::Immutable, App::Property::LockDynamic, MA_AddProp, MA_AutoExpand, MA_EditPropGroup, MA_Expression, MA_RemoveProp, MA_ShowHidden, MA_Touched, NavigationIndicatorGui::menu, Path.Post.scripts.opensbp_post::move(), geoff_geometry::Normal(), openEditor(), Init::parent, RobotExample::pos, App::Prop_ReadOnly, App::Property::PropDynamic, Gui::Selection(), Gui::PropertyView::setShowAll(), and Gui::PropertyView::showAll().
currentChanged()
void PropertyEditor::currentChanged (const QModelIndex & current, const QModelIndex & previous) override protected
Definition at line 245 of file PropertyEditor.cpp.
References FC_LOG.
drawBranches()
void PropertyEditor::drawBranches (QPainter * painter, const QRect & rect, const QModelIndex & index) const override protected
Definition at line 587 of file PropertyEditor.cpp.
drawRow()
void Gui::PropertyEditor::PropertyEditor::drawRow (QPainter * painter, const QStyleOptionViewItem & options, const QModelIndex & index) const override protected
Definition at line 600 of file PropertyEditor.cpp.
editorDestroyed()
void PropertyEditor::editorDestroyed (QObject * editor) override protected
Definition at line 235 of file PropertyEditor.cpp.
References Path.Post.Utils::editor().
event()
bool PropertyEditor::event (QEvent * event) override protected
Definition at line 200 of file PropertyEditor.cpp.
Referenced by eventFilter().
eventFilter()
bool PropertyEditor::eventFilter (QObject * object, QEvent * event) override protected
Definition at line 933 of file PropertyEditor.cpp.
References event(), App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetInt().
groupBackground()
QBrush Gui::PropertyEditor::PropertyEditor::groupBackground () const
groupTextColor()
QColor Gui::PropertyEditor::PropertyEditor::groupTextColor () const
initViewItemOption()
void PropertyEditor::initViewItemOption (QStyleOptionViewItem * option) const override protected
Definition at line 193 of file PropertyEditor.cpp.
isAutomaticDocumentUpdate()
bool PropertyEditor::isAutomaticDocumentUpdate (bool) const
Definition at line 150 of file PropertyEditor.cpp.
isAutomaticExpand()
bool PropertyEditor::isAutomaticExpand (bool) const
Definition at line 125 of file PropertyEditor.cpp.
isBinding()
bool Gui::PropertyEditor::PropertyEditor::isBinding () const inline
Definition at line 95 of file PropertyEditor.h.
itemBackground()
QBrush Gui::PropertyEditor::PropertyEditor::itemBackground () const
onItemActivated
void PropertyEditor::onItemActivated (const QModelIndex & index) protected slot
Definition at line 359 of file PropertyEditor.cpp.
References openEditor().
onItemCollapsed
void PropertyEditor::onItemCollapsed (const QModelIndex & index) protected slot
Definition at line 139 of file PropertyEditor.cpp.
References Gui::PropertyEditor::PropertyItem::setExpanded().
onItemExpanded
void PropertyEditor::onItemExpanded (const QModelIndex & index) protected slot
Definition at line 130 of file PropertyEditor.cpp.
References SCL.SimpleDataTypes::c, SplineSurface::i, Gui::PropertyEditor::PropertyModel::index(), and Gui::PropertyEditor::PropertyItem::setExpanded().
onRowsMoved
void PropertyEditor::onRowsMoved (const QModelIndex & parent, int start, int end, const QModelIndex & dst, int row) protected slot
Definition at line 506 of file PropertyEditor.cpp.
References Init::parent, and Gui::PropertyEditor::PropertyModel::parent().
onRowsRemoved
void PropertyEditor::onRowsRemoved (const QModelIndex & parent, int start, int end) protected slot
Definition at line 579 of file PropertyEditor.cpp.
openEditor()
void PropertyEditor::openEditor (const QModelIndex & index)
Definition at line 292 of file PropertyEditor.cpp.
References src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui::app, closeEditor(), FC_LOG, App::GetApplication(), src.Mod.Test.testPathArray::items, Init::parent, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by closeEditor(), contextMenuEvent(), and onItemActivated().
removeProperty()
void PropertyEditor::removeProperty (const App::Property & prop)
Definition at line 678 of file PropertyEditor.cpp.
References DraftVecUtils::find(), RobotExample::pos, and Gui::PropertyEditor::PropertyModel::removeProperty().
reset()
void PropertyEditor::reset () override
Reset the internal state of the view.
Definition at line 481 of file PropertyEditor.cpp.
References SplineSurface::i, Gui::PropertyEditor::PropertyModel::index(), Init::parent, and Gui::PropertyEditor::PropertyModel::rowCount().
Referenced by ArchVRM.Renderer::__init__(), draftguitools.gui_trackers.gridTracker::set(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testAll(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
rowsAboutToBeRemoved()
void PropertyEditor::rowsAboutToBeRemoved (const QModelIndex & parent, int start, int end) override protected
Definition at line 554 of file PropertyEditor.cpp.
References Init::parent, Gui::PropertyEditor::PropertyModel::parent(), and src.Mod.PartDesign.fcgear.svggear::w.
rowsInserted()
void PropertyEditor::rowsInserted (const QModelIndex & parent, int start, int end) override protected
Definition at line 525 of file PropertyEditor.cpp.
References SplineSurface::i, Gui::PropertyEditor::PropertyModel::index(), Init::parent, and Gui::PropertyEditor::PropertyModel::parent().
setAutomaticDocumentUpdate()
void PropertyEditor::setAutomaticDocumentUpdate (bool v)
Definition at line 145 of file PropertyEditor.cpp.
References TestSpreadsheet::v.
Referenced by Gui::PropertyView::PropertyView().
setAutomaticExpand()
void PropertyEditor::setAutomaticExpand (bool v)
Definition at line 120 of file PropertyEditor.cpp.
References TestSpreadsheet::v.
Referenced by Gui::PropertyView::PropertyView().
setGroupBackground()
void PropertyEditor::setGroupBackground (const QBrush & c)
Definition at line 160 of file PropertyEditor.cpp.
References SCL.SimpleDataTypes::c.
setGroupTextColor()
void PropertyEditor::setGroupTextColor (const QColor & c)
Definition at line 170 of file PropertyEditor.cpp.
References SCL.SimpleDataTypes::c.
setItemBackground()
void PropertyEditor::setItemBackground (const QBrush & c)
Definition at line 180 of file PropertyEditor.cpp.
References SCL.SimpleDataTypes::c.
updateProperty()
void PropertyEditor::updateProperty (const App::Property & prop)
Definition at line 658 of file PropertyEditor.cpp.
References Gui::PropertyEditor::PropertyModel::updateProperty().
Friends And Related Function Documentation
Gui::PropertyView
friend class Gui::PropertyView friend
Definition at line 170 of file PropertyEditor.h.
PropertyItemDelegate
friend class PropertyItemDelegate friend
Definition at line 171 of file PropertyEditor.h.
Property Documentation
groupBackground
QBrush PropertyEditor::groupBackground read write
Definition at line 67 of file PropertyEditor.h.
groupTextColor
QColor PropertyEditor::groupTextColor read write
Definition at line 68 of file PropertyEditor.h.
itemBackground
QBrush PropertyEditor::itemBackground read write
Definition at line 69 of file PropertyEditor.h.
The documentation for this class was generated from the following files:
PropertyEditor.h
PropertyEditor.cpp