FreeCAD: Gui::TreeParams Class Reference
Gui::TreeParams Class Reference
#include <TreeParams.h>
Static Public Member Functions
static ParameterGrp::handle getHandle ()
static const bool & getSyncSelection ()
Accessor for parameter SyncSelection.
static const bool & defaultSyncSelection ()
static void removeSyncSelection ()
static void setSyncSelection (const bool &v)
static const char * docSyncSelection ()
static void onSyncSelectionChanged ()
static const bool & getCheckBoxesSelection ()
Accessor for parameter CheckBoxesSelection.
static const bool & defaultCheckBoxesSelection ()
static void removeCheckBoxesSelection ()
static void setCheckBoxesSelection (const bool &v)
static const char * docCheckBoxesSelection ()
static void onCheckBoxesSelectionChanged ()
static const bool & getSyncView ()
Accessor for parameter SyncView.
static const bool & defaultSyncView ()
static void removeSyncView ()
static void setSyncView (const bool &v)
static const char * docSyncView ()
static const bool & getPreSelection ()
Accessor for parameter PreSelection.
static const bool & defaultPreSelection ()
static void removePreSelection ()
static void setPreSelection (const bool &v)
static const char * docPreSelection ()
static const bool & getSyncPlacement ()
Accessor for parameter SyncPlacement.
static const bool & defaultSyncPlacement ()
static void removeSyncPlacement ()
static void setSyncPlacement (const bool &v)
static const char * docSyncPlacement ()
static const bool & getRecordSelection ()
Accessor for parameter RecordSelection.
static const bool & defaultRecordSelection ()
static void removeRecordSelection ()
static void setRecordSelection (const bool &v)
static const char * docRecordSelection ()
static const long & getDocumentMode ()
Accessor for parameter DocumentMode.
static const long & defaultDocumentMode ()
static void removeDocumentMode ()
static void setDocumentMode (const long &v)
static const char * docDocumentMode ()
static void onDocumentModeChanged ()
static const long & getStatusTimeout ()
Accessor for parameter StatusTimeout.
static const long & defaultStatusTimeout ()
static void removeStatusTimeout ()
static void setStatusTimeout (const long &v)
static const char * docStatusTimeout ()
static const long & getSelectionTimeout ()
Accessor for parameter SelectionTimeout.
static const long & defaultSelectionTimeout ()
static void removeSelectionTimeout ()
static void setSelectionTimeout (const long &v)
static const char * docSelectionTimeout ()
static const long & getPreSelectionTimeout ()
Accessor for parameter PreSelectionTimeout.
static const long & defaultPreSelectionTimeout ()
static void removePreSelectionTimeout ()
static void setPreSelectionTimeout (const long &v)
static const char * docPreSelectionTimeout ()
static const long & getPreSelectionDelay ()
Accessor for parameter PreSelectionDelay.
static const long & defaultPreSelectionDelay ()
static void removePreSelectionDelay ()
static void setPreSelectionDelay (const long &v)
static const char * docPreSelectionDelay ()
static const long & getPreSelectionMinDelay ()
Accessor for parameter PreSelectionMinDelay.
static const long & defaultPreSelectionMinDelay ()
static void removePreSelectionMinDelay ()
static void setPreSelectionMinDelay (const long &v)
static const char * docPreSelectionMinDelay ()
static const bool & getRecomputeOnDrop ()
Accessor for parameter RecomputeOnDrop.
static const bool & defaultRecomputeOnDrop ()
static void removeRecomputeOnDrop ()
static void setRecomputeOnDrop (const bool &v)
static const char * docRecomputeOnDrop ()
static const bool & getKeepRootOrder ()
Accessor for parameter KeepRootOrder.
static const bool & defaultKeepRootOrder ()
static void removeKeepRootOrder ()
static void setKeepRootOrder (const bool &v)
static const char * docKeepRootOrder ()
static const bool & getTreeActiveAutoExpand ()
Accessor for parameter TreeActiveAutoExpand.
static const bool & defaultTreeActiveAutoExpand ()
static void removeTreeActiveAutoExpand ()
static void setTreeActiveAutoExpand (const bool &v)
static const char * docTreeActiveAutoExpand ()
static const unsigned long & getTreeActiveColor ()
Accessor for parameter TreeActiveColor.
static const unsigned long & defaultTreeActiveColor ()
static void removeTreeActiveColor ()
static void setTreeActiveColor (const unsigned long &v)
static const char * docTreeActiveColor ()
static void onTreeActiveColorChanged ()
static const unsigned long & getTreeEditColor ()
Accessor for parameter TreeEditColor.
static const unsigned long & defaultTreeEditColor ()
static void removeTreeEditColor ()
static void setTreeEditColor (const unsigned long &v)
static const char * docTreeEditColor ()
static void onTreeEditColorChanged ()
static const unsigned long & getSelectingGroupColor ()
Accessor for parameter SelectingGroupColor.
static const unsigned long & defaultSelectingGroupColor ()
static void removeSelectingGroupColor ()
static void setSelectingGroupColor (const unsigned long &v)
static const char * docSelectingGroupColor ()
static void onSelectingGroupColorChanged ()
static const bool & getTreeActiveBold ()
Accessor for parameter TreeActiveBold.
static const bool & defaultTreeActiveBold ()
static void removeTreeActiveBold ()
static void setTreeActiveBold (const bool &v)
static const char * docTreeActiveBold ()
static void onTreeActiveBoldChanged ()
static const bool & getTreeActiveItalic ()
Accessor for parameter TreeActiveItalic.
static const bool & defaultTreeActiveItalic ()
static void removeTreeActiveItalic ()
static void setTreeActiveItalic (const bool &v)
static const char * docTreeActiveItalic ()
static void onTreeActiveItalicChanged ()
static const bool & getTreeActiveUnderlined ()
Accessor for parameter TreeActiveUnderlined.
static const bool & defaultTreeActiveUnderlined ()
static void removeTreeActiveUnderlined ()
static void setTreeActiveUnderlined (const bool &v)
static const char * docTreeActiveUnderlined ()
static void onTreeActiveUnderlinedChanged ()
static const bool & getTreeActiveOverlined ()
Accessor for parameter TreeActiveOverlined.
static const bool & defaultTreeActiveOverlined ()
static void removeTreeActiveOverlined ()
static void setTreeActiveOverlined (const bool &v)
static const char * docTreeActiveOverlined ()
static void onTreeActiveOverlinedChanged ()
static const long & getIndentation ()
Accessor for parameter Indentation.
static const long & defaultIndentation ()
static void removeIndentation ()
static void setIndentation (const long &v)
static const char * docIndentation ()
static void onIndentationChanged ()
static const bool & getLabelExpression ()
Accessor for parameter LabelExpression.
static const bool & defaultLabelExpression ()
static void removeLabelExpression ()
static void setLabelExpression (const bool &v)
static const char * docLabelExpression ()
static const long & getIconSize ()
Accessor for parameter IconSize.
static const long & defaultIconSize ()
static void removeIconSize ()
static void setIconSize (const long &v)
static const char * docIconSize ()
static void onIconSizeChanged ()
static const long & getFontSize ()
Accessor for parameter FontSize.
static const long & defaultFontSize ()
static void removeFontSize ()
static void setFontSize (const long &v)
static const char * docFontSize ()
static void onFontSizeChanged ()
static const long & getItemSpacing ()
Accessor for parameter ItemSpacing.
static const long & defaultItemSpacing ()
static void removeItemSpacing ()
static void setItemSpacing (const long &v)
static const char * docItemSpacing ()
static void onItemSpacingChanged ()
static const unsigned long & getItemBackground ()
static const unsigned long & defaultItemBackground ()
static void removeItemBackground ()
static void setItemBackground (const unsigned long &v)
static const char * docItemBackground ()
static void onItemBackgroundChanged ()
static const long & getItemBackgroundPadding ()
static const long & defaultItemBackgroundPadding ()
static void removeItemBackgroundPadding ()
static void setItemBackgroundPadding (const long &v)
static const char * docItemBackgroundPadding ()
static void onItemBackgroundPaddingChanged ()
static const bool & getHideColumn ()
static const bool & defaultHideColumn ()
static void removeHideColumn ()
static void setHideColumn (const bool &v)
static const char * docHideColumn ()
static void onHideColumnChanged ()
static const bool & getHideInternalNames ()
static const bool & defaultHideInternalNames ()
static void removeHideInternalNames ()
static void setHideInternalNames (const bool &v)
static const char * docHideInternalNames ()
static void onHideInternalNamesChanged ()
static const bool & getHideScrollBar ()
static const bool & defaultHideScrollBar ()
static void removeHideScrollBar ()
static void setHideScrollBar (const bool &v)
static const char * docHideScrollBar ()
static const bool & getHideHeaderView ()
static const bool & defaultHideHeaderView ()
static void removeHideHeaderView ()
static void setHideHeaderView (const bool &v)
static const char * docHideHeaderView ()
static const bool & getResizableColumn ()
static const bool & defaultResizableColumn ()
static void removeResizableColumn ()
static void setResizableColumn (const bool &v)
static const char * docResizableColumn ()
static void onResizableColumnChanged ()
static const long & getColumnSize1 ()
Accessor for parameter ColumnSize1.
static const long & defaultColumnSize1 ()
static void removeColumnSize1 ()
static void setColumnSize1 (const long &v)
static const char * docColumnSize1 ()
static const long & getColumnSize2 ()
Accessor for parameter ColumnSize2.
static const long & defaultColumnSize2 ()
static void removeColumnSize2 ()
static void setColumnSize2 (const long &v)
static const char * docColumnSize2 ()
static const long & getColumnSize3 ()
Accessor for parameter ColumnSize3.
static const long & defaultColumnSize3 ()
static void removeColumnSize3 ()
static void setColumnSize3 (const long &v)
static const char * docColumnSize3 ()
static const bool & getTreeToolTipIcon ()
Accessor for parameter TreeToolTipIcon.
static const bool & defaultTreeToolTipIcon ()
static void removeTreeToolTipIcon ()
static void setTreeToolTipIcon (const bool &v)
static const char * docTreeToolTipIcon ()
static const bool & getVisibilityIcon ()
static const bool & defaultVisibilityIcon ()
static void removeVisibilityIcon ()
static void setVisibilityIcon (const bool &v)
static const char * docVisibilityIcon ()
static void onVisibilityIconChanged ()
static void refreshTreeViews ()
Detailed Description
Convenient class to obtain tree view related parameters
The parameters are under group "User parameter:BaseApp/Preferences/TreeView"
This class is auto generated by Gui/TreeParams.py. Modify that file instead of this one, if you want to add any parameter. You need to install Cog Python package for code generation:
pip install cogapp
Once modified, you can regenerate the header and the source file,
python3 -m cogapp -r Gui/TreeParams.h Tree.cpp
You can add a new parameter by adding lines in Gui/TreeParams.py. Available parameter types are 'Int, UInt, String, Bool, Float'. For example, to add a new Int type parameter,
ParamInt(parameter_name, default_value, documentation, on_change=False)
If there is special handling on parameter change, pass in on_change=True. And you need to provide a function implementation in Tree.cpp with the following signature.
void TreeParams:on<parameter_name>Changed()
Definition at line 87 of file TreeParams.h.
Member Function Documentation
defaultCheckBoxesSelection()
static const bool& Gui::TreeParams::defaultCheckBoxesSelection () static
defaultColumnSize1()
static const long& Gui::TreeParams::defaultColumnSize1 () static
defaultColumnSize2()
static const long& Gui::TreeParams::defaultColumnSize2 () static
defaultColumnSize3()
static const long& Gui::TreeParams::defaultColumnSize3 () static
defaultDocumentMode()
static const long& Gui::TreeParams::defaultDocumentMode () static
defaultFontSize()
static const long& Gui::TreeParams::defaultFontSize () static
defaultHideColumn()
static const bool& Gui::TreeParams::defaultHideColumn () static
defaultHideHeaderView()
static const bool& Gui::TreeParams::defaultHideHeaderView () static
defaultHideInternalNames()
static const bool& Gui::TreeParams::defaultHideInternalNames () static
defaultHideScrollBar()
static const bool& Gui::TreeParams::defaultHideScrollBar () static
defaultIconSize()
static const long& Gui::TreeParams::defaultIconSize () static
defaultIndentation()
static const long& Gui::TreeParams::defaultIndentation () static
defaultItemBackground()
static const unsigned long& Gui::TreeParams::defaultItemBackground () static
defaultItemBackgroundPadding()
static const long& Gui::TreeParams::defaultItemBackgroundPadding () static
defaultItemSpacing()
static const long& Gui::TreeParams::defaultItemSpacing () static
defaultKeepRootOrder()
static const bool& Gui::TreeParams::defaultKeepRootOrder () static
defaultLabelExpression()
static const bool& Gui::TreeParams::defaultLabelExpression () static
defaultPreSelection()
static const bool& Gui::TreeParams::defaultPreSelection () static
defaultPreSelectionDelay()
static const long& Gui::TreeParams::defaultPreSelectionDelay () static
defaultPreSelectionMinDelay()
static const long& Gui::TreeParams::defaultPreSelectionMinDelay () static
defaultPreSelectionTimeout()
static const long& Gui::TreeParams::defaultPreSelectionTimeout () static
defaultRecomputeOnDrop()
static const bool& Gui::TreeParams::defaultRecomputeOnDrop () static
defaultRecordSelection()
static const bool& Gui::TreeParams::defaultRecordSelection () static
defaultResizableColumn()
static const bool& Gui::TreeParams::defaultResizableColumn () static
defaultSelectingGroupColor()
static const unsigned long& Gui::TreeParams::defaultSelectingGroupColor () static
defaultSelectionTimeout()
static const long& Gui::TreeParams::defaultSelectionTimeout () static
defaultStatusTimeout()
static const long& Gui::TreeParams::defaultStatusTimeout () static
defaultSyncPlacement()
static const bool& Gui::TreeParams::defaultSyncPlacement () static
defaultSyncSelection()
static const bool& Gui::TreeParams::defaultSyncSelection () static
defaultSyncView()
static const bool& Gui::TreeParams::defaultSyncView () static
defaultTreeActiveAutoExpand()
static const bool& Gui::TreeParams::defaultTreeActiveAutoExpand () static
defaultTreeActiveBold()
static const bool& Gui::TreeParams::defaultTreeActiveBold () static
defaultTreeActiveColor()
static const unsigned long& Gui::TreeParams::defaultTreeActiveColor () static
defaultTreeActiveItalic()
static const bool& Gui::TreeParams::defaultTreeActiveItalic () static
defaultTreeActiveOverlined()
static const bool& Gui::TreeParams::defaultTreeActiveOverlined () static
defaultTreeActiveUnderlined()
static const bool& Gui::TreeParams::defaultTreeActiveUnderlined () static
defaultTreeEditColor()
static const unsigned long& Gui::TreeParams::defaultTreeEditColor () static
defaultTreeToolTipIcon()
static const bool& Gui::TreeParams::defaultTreeToolTipIcon () static
defaultVisibilityIcon()
static const bool& Gui::TreeParams::defaultVisibilityIcon () static
docCheckBoxesSelection()
static const char* Gui::TreeParams::docCheckBoxesSelection () static
docColumnSize1()
static const char* Gui::TreeParams::docColumnSize1 () static
docColumnSize2()
static const char* Gui::TreeParams::docColumnSize2 () static
docColumnSize3()
static const char* Gui::TreeParams::docColumnSize3 () static
docDocumentMode()
static const char* Gui::TreeParams::docDocumentMode () static
docFontSize()
static const char* Gui::TreeParams::docFontSize () static
docHideColumn()
static const char* Gui::TreeParams::docHideColumn () static
docHideHeaderView()
static const char* Gui::TreeParams::docHideHeaderView () static
docHideInternalNames()
static const char* Gui::TreeParams::docHideInternalNames () static
docHideScrollBar()
static const char* Gui::TreeParams::docHideScrollBar () static
docIconSize()
static const char* Gui::TreeParams::docIconSize () static
docIndentation()
static const char* Gui::TreeParams::docIndentation () static
docItemBackground()
static const char* Gui::TreeParams::docItemBackground () static
docItemBackgroundPadding()
static const char* Gui::TreeParams::docItemBackgroundPadding () static
docItemSpacing()
static const char* Gui::TreeParams::docItemSpacing () static
docKeepRootOrder()
static const char* Gui::TreeParams::docKeepRootOrder () static
docLabelExpression()
static const char* Gui::TreeParams::docLabelExpression () static
docPreSelection()
static const char* Gui::TreeParams::docPreSelection () static
docPreSelectionDelay()
static const char* Gui::TreeParams::docPreSelectionDelay () static
docPreSelectionMinDelay()
static const char* Gui::TreeParams::docPreSelectionMinDelay () static
docPreSelectionTimeout()
static const char* Gui::TreeParams::docPreSelectionTimeout () static
docRecomputeOnDrop()
static const char* Gui::TreeParams::docRecomputeOnDrop () static
docRecordSelection()
static const char* Gui::TreeParams::docRecordSelection () static
docResizableColumn()
static const char* Gui::TreeParams::docResizableColumn () static
docSelectingGroupColor()
static const char* Gui::TreeParams::docSelectingGroupColor () static
docSelectionTimeout()
static const char* Gui::TreeParams::docSelectionTimeout () static
docStatusTimeout()
static const char* Gui::TreeParams::docStatusTimeout () static
docSyncPlacement()
static const char* Gui::TreeParams::docSyncPlacement () static
docSyncSelection()
static const char* Gui::TreeParams::docSyncSelection () static
docSyncView()
static const char* Gui::TreeParams::docSyncView () static
docTreeActiveAutoExpand()
static const char* Gui::TreeParams::docTreeActiveAutoExpand () static
docTreeActiveBold()
static const char* Gui::TreeParams::docTreeActiveBold () static
docTreeActiveColor()
static const char* Gui::TreeParams::docTreeActiveColor () static
docTreeActiveItalic()
static const char* Gui::TreeParams::docTreeActiveItalic () static
docTreeActiveOverlined()
static const char* Gui::TreeParams::docTreeActiveOverlined () static
docTreeActiveUnderlined()
static const char* Gui::TreeParams::docTreeActiveUnderlined () static
docTreeEditColor()
static const char* Gui::TreeParams::docTreeEditColor () static
docTreeToolTipIcon()
static const char* Gui::TreeParams::docTreeToolTipIcon () static
docVisibilityIcon()
static const char* Gui::TreeParams::docVisibilityIcon () static
getCheckBoxesSelection()
static const bool& Gui::TreeParams::getCheckBoxesSelection () static
Accessor for parameter CheckBoxesSelection.
Referenced by isSelectionCheckBoxesEnabled().
getColumnSize1()
static const long& Gui::TreeParams::getColumnSize1 () static
Accessor for parameter ColumnSize1.
Referenced by Gui::TreeWidget::setupResizableColumn().
getColumnSize2()
static const long& Gui::TreeParams::getColumnSize2 () static
Accessor for parameter ColumnSize2.
Referenced by Gui::TreeWidget::setupResizableColumn().
getColumnSize3()
static const long& Gui::TreeParams::getColumnSize3 () static
Accessor for parameter ColumnSize3.
Referenced by Gui::TreeWidget::setupResizableColumn().
getDocumentMode()
static const long& Gui::TreeParams::getDocumentMode () static
Accessor for parameter DocumentMode.
getFontSize()
static const long& Gui::TreeParams::getFontSize () static
Accessor for parameter FontSize.
getHandle()
static ParameterGrp::handle Gui::TreeParams::getHandle () static
getHideColumn()
static const bool& Gui::TreeParams::getHideColumn () static
Accessor for parameter HideColumn
Hide extra tree view column for item description.
Referenced by isOnlyNameColumnDisplayed(), and Gui::TreeWidget::TreeWidget().
getHideHeaderView()
static const bool& Gui::TreeParams::getHideHeaderView () static
Accessor for parameter HideHeaderView
Hide tree view header view in dock overlay.
Referenced by Gui::OverlayTabWidget::_setOverlayMode().
getHideInternalNames()
static const bool& Gui::TreeParams::getHideInternalNames () static
Accessor for parameter HideInternalNames
Hide extra tree view column - Internal Names.
Referenced by isOnlyNameColumnDisplayed(), and Gui::TreeWidget::TreeWidget().
getHideScrollBar()
static const bool& Gui::TreeParams::getHideScrollBar () static
Accessor for parameter HideScrollBar
Hide tree view scroll bar in dock overlay.
Referenced by Gui::OverlayTabWidget::_setOverlayMode().
getIconSize()
static const long& Gui::TreeParams::getIconSize () static
Accessor for parameter IconSize.
Referenced by treeIconSize().
getIndentation()
static const long& Gui::TreeParams::getIndentation () static
Accessor for parameter Indentation.
Referenced by Gui::TreePanel::TreePanel().
getItemBackground()
static const unsigned long& Gui::TreeParams::getItemBackground () static
Accessor for parameter ItemBackground
Tree view item background. Only effective in overlay.
getItemBackgroundPadding()
static const long& Gui::TreeParams::getItemBackgroundPadding () static
Accessor for parameter ItemBackgroundPadding
Tree view item background padding.
Referenced by DynamicQLineEdit::sizeHint().
getItemSpacing()
static const long& Gui::TreeParams::getItemSpacing () static
Accessor for parameter ItemSpacing.
Referenced by Gui::TreeWidgetItemDelegate::sizeHint().
getKeepRootOrder()
static const bool& Gui::TreeParams::getKeepRootOrder () static
Accessor for parameter KeepRootOrder.
Referenced by Gui::DocumentItem::findRootIndex().
getLabelExpression()
static const bool& Gui::TreeParams::getLabelExpression () static
Accessor for parameter LabelExpression.
Referenced by Gui::TreeWidgetItemDelegate::createEditor().
getPreSelection()
static const bool& Gui::TreeParams::getPreSelection () static
Accessor for parameter PreSelection.
Referenced by Gui::TreeWidget::leaveEvent(), and Gui::TreeWidget::onPreSelectTimer().
getPreSelectionDelay()
static const long& Gui::TreeParams::getPreSelectionDelay () static
Accessor for parameter PreSelectionDelay.
getPreSelectionMinDelay()
static const long& Gui::TreeParams::getPreSelectionMinDelay () static
Accessor for parameter PreSelectionMinDelay.
getPreSelectionTimeout()
static const long& Gui::TreeParams::getPreSelectionTimeout () static
Accessor for parameter PreSelectionTimeout.
getRecomputeOnDrop()
static const bool& Gui::TreeParams::getRecomputeOnDrop () static
Accessor for parameter RecomputeOnDrop.
Referenced by Gui::TreeWidget::dropEvent().
getRecordSelection()
static const bool& Gui::TreeParams::getRecordSelection () static
Accessor for parameter RecordSelection.
Referenced by Gui::TreeWidget::selectAll().
getResizableColumn()
static const bool& Gui::TreeParams::getResizableColumn () static
Accessor for parameter ResizableColumn
Allow tree view columns to be manually resized.
Referenced by Gui::TreeWidget::setupResizableColumn().
getSelectingGroupColor()
static const unsigned long& Gui::TreeParams::getSelectingGroupColor () static
Accessor for parameter SelectingGroupColor.
getSelectionTimeout()
static const long& Gui::TreeParams::getSelectionTimeout () static
Accessor for parameter SelectionTimeout.
Referenced by Gui::TreeWidget::onSelectionChanged().
getStatusTimeout()
static const long& Gui::TreeParams::getStatusTimeout () static
Accessor for parameter StatusTimeout.
getSyncPlacement()
static const bool& Gui::TreeParams::getSyncPlacement () static
Accessor for parameter SyncPlacement.
getSyncSelection()
static const bool& Gui::TreeParams::getSyncSelection () static
Accessor for parameter SyncSelection.
Referenced by Gui::TreeWidget::onSelectTimer().
getSyncView()
static const bool& Gui::TreeParams::getSyncView () static
Accessor for parameter SyncView.
Referenced by Gui::TreeWidget::dropEvent(), and Gui::TreeWidget::syncView().
getTreeActiveAutoExpand()
static const bool& Gui::TreeParams::getTreeActiveAutoExpand () static
Accessor for parameter TreeActiveAutoExpand.
getTreeActiveBold()
static const bool& Gui::TreeParams::getTreeActiveBold () static
Accessor for parameter TreeActiveBold.
getTreeActiveColor()
static const unsigned long& Gui::TreeParams::getTreeActiveColor () static
Accessor for parameter TreeActiveColor.
getTreeActiveItalic()
static const bool& Gui::TreeParams::getTreeActiveItalic () static
Accessor for parameter TreeActiveItalic.
getTreeActiveOverlined()
static const bool& Gui::TreeParams::getTreeActiveOverlined () static
Accessor for parameter TreeActiveOverlined.
getTreeActiveUnderlined()
static const bool& Gui::TreeParams::getTreeActiveUnderlined () static
Accessor for parameter TreeActiveUnderlined.
getTreeEditColor()
static const unsigned long& Gui::TreeParams::getTreeEditColor () static
Accessor for parameter TreeEditColor.
getTreeToolTipIcon()
static const bool& Gui::TreeParams::getTreeToolTipIcon () static
Accessor for parameter TreeToolTipIcon.
getVisibilityIcon()
static const bool& Gui::TreeParams::getVisibilityIcon () static
Accessor for parameter VisibilityIcon
If enabled, show an eye icon before the tree view items, showing the items visibility status. When clicked the visibility is toggled
Referenced by isVisibilityIconEnabled().
onCheckBoxesSelectionChanged()
static void Gui::TreeParams::onCheckBoxesSelectionChanged () static
onDocumentModeChanged()
static void Gui::TreeParams::onDocumentModeChanged () static
onFontSizeChanged()
static void Gui::TreeParams::onFontSizeChanged () static
Referenced by Gui::TreeWidget::TreeWidget().
onHideColumnChanged()
static void Gui::TreeParams::onHideColumnChanged () static
onHideInternalNamesChanged()
static void Gui::TreeParams::onHideInternalNamesChanged () static
onIconSizeChanged()
static void Gui::TreeParams::onIconSizeChanged () static
onIndentationChanged()
static void Gui::TreeParams::onIndentationChanged () static
onItemBackgroundChanged()
static void Gui::TreeParams::onItemBackgroundChanged () static
onItemBackgroundPaddingChanged()
static void Gui::TreeParams::onItemBackgroundPaddingChanged () static
onItemSpacingChanged()
static void Gui::TreeParams::onItemSpacingChanged () static
onResizableColumnChanged()
static void Gui::TreeParams::onResizableColumnChanged () static
onSelectingGroupColorChanged()
static void Gui::TreeParams::onSelectingGroupColorChanged () static
onSyncSelectionChanged()
static void Gui::TreeParams::onSyncSelectionChanged () static
onTreeActiveBoldChanged()
static void Gui::TreeParams::onTreeActiveBoldChanged () static
onTreeActiveColorChanged()
static void Gui::TreeParams::onTreeActiveColorChanged () static
onTreeActiveItalicChanged()
static void Gui::TreeParams::onTreeActiveItalicChanged () static
onTreeActiveOverlinedChanged()
static void Gui::TreeParams::onTreeActiveOverlinedChanged () static
onTreeActiveUnderlinedChanged()
static void Gui::TreeParams::onTreeActiveUnderlinedChanged () static
onTreeEditColorChanged()
static void Gui::TreeParams::onTreeEditColorChanged () static
onVisibilityIconChanged()
static void Gui::TreeParams::onVisibilityIconChanged () static
refreshTreeViews()
static void Gui::TreeParams::refreshTreeViews () static
removeCheckBoxesSelection()
static void Gui::TreeParams::removeCheckBoxesSelection () static
removeColumnSize1()
static void Gui::TreeParams::removeColumnSize1 () static
removeColumnSize2()
static void Gui::TreeParams::removeColumnSize2 () static
removeColumnSize3()
static void Gui::TreeParams::removeColumnSize3 () static
removeDocumentMode()
static void Gui::TreeParams::removeDocumentMode () static
removeFontSize()
static void Gui::TreeParams::removeFontSize () static
removeHideColumn()
static void Gui::TreeParams::removeHideColumn () static
removeHideHeaderView()
static void Gui::TreeParams::removeHideHeaderView () static
removeHideInternalNames()
static void Gui::TreeParams::removeHideInternalNames () static
removeHideScrollBar()
static void Gui::TreeParams::removeHideScrollBar () static
removeIconSize()
static void Gui::TreeParams::removeIconSize () static
removeIndentation()
static void Gui::TreeParams::removeIndentation () static
removeItemBackground()
static void Gui::TreeParams::removeItemBackground () static
removeItemBackgroundPadding()
static void Gui::TreeParams::removeItemBackgroundPadding () static
removeItemSpacing()
static void Gui::TreeParams::removeItemSpacing () static
removeKeepRootOrder()
static void Gui::TreeParams::removeKeepRootOrder () static
removeLabelExpression()
static void Gui::TreeParams::removeLabelExpression () static
removePreSelection()
static void Gui::TreeParams::removePreSelection () static
removePreSelectionDelay()
static void Gui::TreeParams::removePreSelectionDelay () static
removePreSelectionMinDelay()
static void Gui::TreeParams::removePreSelectionMinDelay () static
removePreSelectionTimeout()
static void Gui::TreeParams::removePreSelectionTimeout () static
removeRecomputeOnDrop()
static void Gui::TreeParams::removeRecomputeOnDrop () static
removeRecordSelection()
static void Gui::TreeParams::removeRecordSelection () static
removeResizableColumn()
static void Gui::TreeParams::removeResizableColumn () static
removeSelectingGroupColor()
static void Gui::TreeParams::removeSelectingGroupColor () static
removeSelectionTimeout()
static void Gui::TreeParams::removeSelectionTimeout () static
removeStatusTimeout()
static void Gui::TreeParams::removeStatusTimeout () static
removeSyncPlacement()
static void Gui::TreeParams::removeSyncPlacement () static
removeSyncSelection()
static void Gui::TreeParams::removeSyncSelection () static
removeSyncView()
static void Gui::TreeParams::removeSyncView () static
removeTreeActiveAutoExpand()
static void Gui::TreeParams::removeTreeActiveAutoExpand () static
removeTreeActiveBold()
static void Gui::TreeParams::removeTreeActiveBold () static
removeTreeActiveColor()
static void Gui::TreeParams::removeTreeActiveColor () static
removeTreeActiveItalic()
static void Gui::TreeParams::removeTreeActiveItalic () static
removeTreeActiveOverlined()
static void Gui::TreeParams::removeTreeActiveOverlined () static
removeTreeActiveUnderlined()
static void Gui::TreeParams::removeTreeActiveUnderlined () static
removeTreeEditColor()
static void Gui::TreeParams::removeTreeEditColor () static
removeTreeToolTipIcon()
static void Gui::TreeParams::removeTreeToolTipIcon () static
removeVisibilityIcon()
static void Gui::TreeParams::removeVisibilityIcon () static
setCheckBoxesSelection()
static void Gui::TreeParams::setCheckBoxesSelection (const bool & v) static
setColumnSize1()
static void Gui::TreeParams::setColumnSize1 (const long & v) static
Referenced by Gui::TreeWidget::TreeWidget().
setColumnSize2()
static void Gui::TreeParams::setColumnSize2 (const long & v) static
Referenced by Gui::TreeWidget::TreeWidget().
setColumnSize3()
static void Gui::TreeParams::setColumnSize3 (const long & v) static
Referenced by Gui::TreeWidget::TreeWidget().
setDocumentMode()
static void Gui::TreeParams::setDocumentMode (const long & v) static
setFontSize()
static void Gui::TreeParams::setFontSize (const long & v) static
setHideColumn()
static void Gui::TreeParams::setHideColumn (const bool & v) static
setHideHeaderView()
static void Gui::TreeParams::setHideHeaderView (const bool & v) static
setHideInternalNames()
static void Gui::TreeParams::setHideInternalNames (const bool & v) static
setHideScrollBar()
static void Gui::TreeParams::setHideScrollBar (const bool & v) static
setIconSize()
static void Gui::TreeParams::setIconSize (const long & v) static
setIndentation()
static void Gui::TreeParams::setIndentation (const long & v) static
setItemBackground()
static void Gui::TreeParams::setItemBackground (const unsigned long & v) static
setItemBackgroundPadding()
static void Gui::TreeParams::setItemBackgroundPadding (const long & v) static
setItemSpacing()
static void Gui::TreeParams::setItemSpacing (const long & v) static
setKeepRootOrder()
static void Gui::TreeParams::setKeepRootOrder (const bool & v) static
setLabelExpression()
static void Gui::TreeParams::setLabelExpression (const bool & v) static
setPreSelection()
static void Gui::TreeParams::setPreSelection (const bool & v) static
setPreSelectionDelay()
static void Gui::TreeParams::setPreSelectionDelay (const long & v) static
setPreSelectionMinDelay()
static void Gui::TreeParams::setPreSelectionMinDelay (const long & v) static
setPreSelectionTimeout()
static void Gui::TreeParams::setPreSelectionTimeout (const long & v) static
setRecomputeOnDrop()
static void Gui::TreeParams::setRecomputeOnDrop (const bool & v) static
setRecordSelection()
static void Gui::TreeParams::setRecordSelection (const bool & v) static
setResizableColumn()
static void Gui::TreeParams::setResizableColumn (const bool & v) static
setSelectingGroupColor()
static void Gui::TreeParams::setSelectingGroupColor (const unsigned long & v) static
setSelectionTimeout()
static void Gui::TreeParams::setSelectionTimeout (const long & v) static
setStatusTimeout()
static void Gui::TreeParams::setStatusTimeout (const long & v) static
setSyncPlacement()
static void Gui::TreeParams::setSyncPlacement (const bool & v) static
setSyncSelection()
static void Gui::TreeParams::setSyncSelection (const bool & v) static
setSyncView()
static void Gui::TreeParams::setSyncView (const bool & v) static
setTreeActiveAutoExpand()
static void Gui::TreeParams::setTreeActiveAutoExpand (const bool & v) static
setTreeActiveBold()
static void Gui::TreeParams::setTreeActiveBold (const bool & v) static
setTreeActiveColor()
static void Gui::TreeParams::setTreeActiveColor (const unsigned long & v) static
setTreeActiveItalic()
static void Gui::TreeParams::setTreeActiveItalic (const bool & v) static
setTreeActiveOverlined()
static void Gui::TreeParams::setTreeActiveOverlined (const bool & v) static
setTreeActiveUnderlined()
static void Gui::TreeParams::setTreeActiveUnderlined (const bool & v) static
setTreeEditColor()
static void Gui::TreeParams::setTreeEditColor (const unsigned long & v) static
setTreeToolTipIcon()
static void Gui::TreeParams::setTreeToolTipIcon (const bool & v) static
setVisibilityIcon()
static void Gui::TreeParams::setVisibilityIcon (const bool & v) static
The documentation for this class was generated from the following file:
TreeParams.h