FreeCAD: MeshCore::FunctionContainer Class Reference
MeshCore::FunctionContainer Class Reference
#include <Approximation.h>
Public Types
using Function = double(*)(double, double, double)
Public Member Functions
FunctionContainer (const double *pKoef)
FunctionContainer (const FunctionContainer &)=delete
FunctionContainer (FunctionContainer &&)=delete
FunctionContainer & operator= (const FunctionContainer &)=delete
FunctionContainer & operator= (FunctionContainer &&)=delete
void Assign (const double *pKoef)
~FunctionContainer ()
double & operator[] (int idx)
bool CurvatureInfo (double x, double y, double z, double &rfCurv0, double &rfCurv1, Wm4::Vector3< double > &rkDir0, Wm4::Vector3< double > &rkDir1, double &dDistance)
Base::Vector3f GetGradient (double x, double y, double z) const
Base::Matrix4D GetHessian (double x, double y, double z) const
bool CurvatureInfo (double x, double y, double z, double &rfCurv0, double &rfCurv1)
double F (double x, double y, double z)
double Fx (double x, double y, double z)
double Fy (double x, double y, double z)
double Fz (double x, double y, double z)
double Fxx (double x, double y, double z)
double Fxy (double x, double y, double z)
double Fxz (double x, double y, double z)
double Fyy (double x, double y, double z)
double Fyz (double x, double y, double z)
double Fzz (double x, double y, double z)
Detailed Description
Helper class for the quadric fit. Includes the partial derivates of the quadric and serves for calculation of the quadric properties.
Definition at line 494 of file Approximation.h.
Member Typedef Documentation
Function
using MeshCore::FunctionContainer::Function = double (*)(double, double, double)
WildMagic library uses function with this interface
Definition at line 500 of file Approximation.h.
Constructor & Destructor Documentation
FunctionContainer() [1/3]
MeshCore::FunctionContainer::FunctionContainer (const double * pKoef) inline explicit
The constructor expects an array of quadric coefficients.
Parameters
pKoef Pointer to the quadric coefficients (double [10])
Definition at line 507 of file Approximation.h.
References Assign().
FunctionContainer() [2/3]
MeshCore::FunctionContainer::FunctionContainer (const FunctionContainer &) delete
FunctionContainer() [3/3]
MeshCore::FunctionContainer::FunctionContainer (FunctionContainer &&) delete
~FunctionContainer()
MeshCore::FunctionContainer::~FunctionContainer () inline
Destructor. Deletes the ImpicitSurface instance of the WildMagic library
Definition at line 534 of file Approximation.h.
Member Function Documentation
Assign()
void MeshCore::FunctionContainer::Assign (const double * pKoef) inline
Apply quadric coefficients
Parameters
pKoef Pointer to the quadric coefficients (double [10])
Definition at line 524 of file Approximation.h.
Referenced by FunctionContainer().
CurvatureInfo() [1/2]
bool MeshCore::FunctionContainer::CurvatureInfo (double x, double y, double z, double & rfCurv0, double & rfCurv1) inline
Definition at line 602 of file Approximation.h.
References Fx(), Fy(), Fz(), KDL::sqrt(), MovieTool::x, and MovieTool::y.
CurvatureInfo() [2/2]
bool MeshCore::FunctionContainer::CurvatureInfo (double x, double y, double z, double & rfCurv0, double & rfCurv1, Wm4::Vector3< double > & rkDir0, Wm4::Vector3< double > & rkDir1, double & dDistance) inline
Redirector to a method of the WildMagic library. Determines the principal curvatures and their directions at the given point.
Parameters
x X-coordinate
y Y-coordinate
z Z-coordinate
rfCurv0 1. principal curvature
rfCurv1 2. principal curvature
rkDir0 direction of 1. principal curvature
rkDir1 direction of 2. principal curvature
dDistance Gives distances from the point to the quadric.
Returns
bool Success = true, otherwise false
Definition at line 560 of file Approximation.h.
References Wm4::ImplicitSurface< Real >::ComputePrincipalCurvatureInfo(), MovieTool::x, and MovieTool::y.
Referenced by MeshCore::QuadraticFit::GetCurvatureInfo(), and MeshCore::SurfaceFit::GetCurvatureInfo().
F()
double MeshCore::FunctionContainer::F (double x, double y, double z) inline
Definition at line 627 of file Approximation.h.
References MovieTool::x, and MovieTool::y.
Referenced by MeshCore::SurfaceFit::Value().
Fx()
double MeshCore::FunctionContainer::Fx (double x, double y, double z) inline
Definition at line 635 of file Approximation.h.
References MovieTool::x, and MovieTool::y.
Referenced by CurvatureInfo().
Fxx()
double MeshCore::FunctionContainer::Fxx (double x, double y, double z) inline
Definition at line 649 of file Approximation.h.
References MovieTool::x, and MovieTool::y.
Fxy()
double MeshCore::FunctionContainer::Fxy (double x, double y, double z) inline
Definition at line 656 of file Approximation.h.
References MovieTool::x, and MovieTool::y.
Fxz()
double MeshCore::FunctionContainer::Fxz (double x, double y, double z) inline
Definition at line 663 of file Approximation.h.
References MovieTool::x, and MovieTool::y.
Fy()
double MeshCore::FunctionContainer::Fy (double x, double y, double z) inline
Definition at line 639 of file Approximation.h.
References MovieTool::x, and MovieTool::y.
Referenced by CurvatureInfo().
Fyy()
double MeshCore::FunctionContainer::Fyy (double x, double y, double z) inline
Definition at line 670 of file Approximation.h.
References MovieTool::x, and MovieTool::y.
Fyz()
double MeshCore::FunctionContainer::Fyz (double x, double y, double z) inline
Definition at line 677 of file Approximation.h.
References MovieTool::x, and MovieTool::y.
Fz()
double MeshCore::FunctionContainer::Fz (double x, double y, double z) inline
Definition at line 643 of file Approximation.h.
References MovieTool::x, and MovieTool::y.
Referenced by CurvatureInfo().
Fzz()
double MeshCore::FunctionContainer::Fzz (double x, double y, double z) inline
Definition at line 684 of file Approximation.h.
References MovieTool::x, and MovieTool::y.
GetGradient()
Base::Vector3f MeshCore::FunctionContainer::GetGradient (double x, double y, double z) const inline
Definition at line 577 of file Approximation.h.
References Wm4::ImplicitSurface< Real >::GetGradient(), MovieTool::x, Wm4::Vector3< Real >::X(), MovieTool::y, Wm4::Vector3< Real >::Y(), and Wm4::Vector3< Real >::Z().
Referenced by MeshCore::QuadraticFit::GetCurvatureInfo(), and MeshCore::SurfaceFit::GetCurvatureInfo().
GetHessian()
Base::Matrix4D MeshCore::FunctionContainer::GetHessian (double x, double y, double z) const inline
Definition at line 585 of file Approximation.h.
References Wm4::ImplicitSurface< Real >::GetHessian(), Base::Matrix4D::setToUnity(), MovieTool::x, and MovieTool::y.
operator=() [1/2]
FunctionContainer& MeshCore::FunctionContainer::operator= (const FunctionContainer &) delete
operator=() [2/2]
FunctionContainer& MeshCore::FunctionContainer::operator= (FunctionContainer &&) delete
operator[]()
double& MeshCore::FunctionContainer::operator[] (int idx) inline
Access to the quadric coefficients
Parameters
idx Index to coefficient
Returns
double& coefficient
Definition at line 543 of file Approximation.h.
The documentation for this class was generated from the following file:
Approximation.h