FreeCAD: ifc2x3.ifcscheduletimecontrol Class Reference
ifc2x3.ifcscheduletimecontrol Class Reference
Public Member Functions
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__objecttype, actualstart, earlystart, latestart, schedulestart, actualfinish, earlyfinish, latefinish, schedulefinish, scheduleduration, actualduration, remainingtime, freefloat, totalfloat, iscritical, statustime, startfloat, finishfloat, completion)
def actualstart ()
def earlystart ()
def latestart ()
def schedulestart ()
def actualfinish ()
def earlyfinish ()
def latefinish ()
def schedulefinish ()
def scheduleduration ()
def actualduration ()
def remainingtime ()
def freefloat ()
def totalfloat ()
def iscritical ()
def statustime ()
def startfloat ()
def finishfloat ()
def completion ()
def scheduletimecontrolassigned ()
Public Member Functions inherited from ifc2x3.ifccontrol
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__objecttype)
def controls ()
Public Member Functions inherited from ifc2x3.ifcobject
def objecttype ()
def isdefinedby ()
def wr1 (self)
Public Member Functions inherited from ifc2x3.ifcobjectdefinition
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description)
def hasassignments ()
def isdecomposedby ()
def decomposes ()
def hasassociations ()
Public Member Functions inherited from ifc2x3.ifcroot
def globalid ()
def ownerhistory ()
def name ()
def description ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
actualstart
earlystart
latestart
schedulestart
actualfinish
earlyfinish
latefinish
schedulefinish
scheduleduration
actualduration
remainingtime
freefloat
totalfloat
iscritical
statustime
startfloat
finishfloat
completion
Public Attributes inherited from ifc2x3.ifcobject
objecttype
Public Attributes inherited from ifc2x3.ifcroot
globalid
ownerhistory
name
description
Detailed Description
Entity ifcscheduletimecontrol definition.
:param actualstart
:type actualstart:ifcdatetimeselect
:param earlystart
:type earlystart:ifcdatetimeselect
:param latestart
:type latestart:ifcdatetimeselect
:param schedulestart
:type schedulestart:ifcdatetimeselect
:param actualfinish
:type actualfinish:ifcdatetimeselect
:param earlyfinish
:type earlyfinish:ifcdatetimeselect
:param latefinish
:type latefinish:ifcdatetimeselect
:param schedulefinish
:type schedulefinish:ifcdatetimeselect
:param scheduleduration
:type scheduleduration:ifctimemeasure
:param actualduration
:type actualduration:ifctimemeasure
:param remainingtime
:type remainingtime:ifctimemeasure
:param freefloat
:type freefloat:ifctimemeasure
:param totalfloat
:type totalfloat:ifctimemeasure
:param iscritical
:type iscritical:BOOLEAN
:param statustime
:type statustime:ifcdatetimeselect
:param startfloat
:type startfloat:ifctimemeasure
:param finishfloat
:type finishfloat:ifctimemeasure
:param completion
:type completion:ifcpositiveratiomeasure
:param scheduletimecontrolassigned
:type scheduletimecontrolassigned:ifcrelassignstasks
Definition at line 35601 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcscheduletimecontrol.__init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__objecttype, actualstart, earlystart, latestart, schedulestart, actualfinish, earlyfinish, latefinish, schedulefinish, scheduleduration, actualduration, remainingtime, freefloat, totalfloat, iscritical, statustime, startfloat, finishfloat, completion)
Definition at line 35661 of file ifc2x3.py.
Member Function Documentation
actualduration()
def ifc2x3.ifcscheduletimecontrol.actualduration ()
Definition at line 35809 of file ifc2x3.py.
References ifc2x3.ifcscheduletimecontrol._actualduration, ifc2x3.ifcscheduletimecontrol.actualduration, and SCL.TypeChecker.check_type().
actualfinish()
def ifc2x3.ifcscheduletimecontrol.actualfinish ()
Definition at line 35739 of file ifc2x3.py.
References ifc2x3.ifcscheduletimecontrol._actualfinish, ifc2x3.ifcscheduletimecontrol.actualfinish, SCL.TypeChecker.check_type(), and ifc2x3.ifcdatetimeselect.
actualstart()
def ifc2x3.ifcscheduletimecontrol.actualstart ()
Definition at line 35683 of file ifc2x3.py.
References ifc2x3.ifcscheduletimecontrol._actualstart, ifc2x3.ifcscheduletimecontrol.actualstart, SCL.TypeChecker.check_type(), and ifc2x3.ifcdatetimeselect.
completion()
def ifc2x3.ifcscheduletimecontrol.completion ()
Definition at line 35921 of file ifc2x3.py.
References ifc2x3.ifcscheduletimecontrol._completion, SCL.TypeChecker.check_type(), and ifc2x3.ifcscheduletimecontrol.completion.
earlyfinish()
def ifc2x3.ifcscheduletimecontrol.earlyfinish ()
Definition at line 35753 of file ifc2x3.py.
References ifc2x3.ifcscheduletimecontrol._earlyfinish, SCL.TypeChecker.check_type(), ifc2x3.ifcscheduletimecontrol.earlyfinish, and ifc2x3.ifcdatetimeselect.
earlystart()
def ifc2x3.ifcscheduletimecontrol.earlystart ()
Definition at line 35697 of file ifc2x3.py.
References ifc2x3.ifcscheduletimecontrol._earlystart, SCL.TypeChecker.check_type(), ifc2x3.ifcscheduletimecontrol.earlystart, and ifc2x3.ifcdatetimeselect.
finishfloat()
def ifc2x3.ifcscheduletimecontrol.finishfloat ()
Definition at line 35907 of file ifc2x3.py.
References ifc2x3.ifcscheduletimecontrol._finishfloat, SCL.TypeChecker.check_type(), and ifc2x3.ifcscheduletimecontrol.finishfloat.
freefloat()
def ifc2x3.ifcscheduletimecontrol.freefloat ()
Definition at line 35837 of file ifc2x3.py.
References ifc2x3.ifcscheduletimecontrol._freefloat, SCL.TypeChecker.check_type(), and ifc2x3.ifcscheduletimecontrol.freefloat.
iscritical()
def ifc2x3.ifcscheduletimecontrol.iscritical ()
Definition at line 35865 of file ifc2x3.py.
References ifc2x3.ifcscheduletimecontrol._iscritical, SCL.SimpleDataTypes.BOOLEAN, SCL.TypeChecker.check_type(), and ifc2x3.ifcscheduletimecontrol.iscritical.
latefinish()
def ifc2x3.ifcscheduletimecontrol.latefinish ()
Definition at line 35767 of file ifc2x3.py.
References ifc2x3.ifcscheduletimecontrol._latefinish, SCL.TypeChecker.check_type(), ifc2x3.ifcdatetimeselect, and ifc2x3.ifcscheduletimecontrol.latefinish.
latestart()
def ifc2x3.ifcscheduletimecontrol.latestart ()
Definition at line 35711 of file ifc2x3.py.
References ifc2x3.ifcscheduletimecontrol._latestart, SCL.TypeChecker.check_type(), ifc2x3.ifcdatetimeselect, and ifc2x3.ifcscheduletimecontrol.latestart.
remainingtime()
def ifc2x3.ifcscheduletimecontrol.remainingtime ()
Definition at line 35823 of file ifc2x3.py.
References ifc2x3.ifcscheduletimecontrol._remainingtime, SCL.TypeChecker.check_type(), and ifc2x3.ifcscheduletimecontrol.remainingtime.
scheduleduration()
def ifc2x3.ifcscheduletimecontrol.scheduleduration ()
Definition at line 35795 of file ifc2x3.py.
References ifc2x3.ifcscheduletimecontrol._scheduleduration, SCL.TypeChecker.check_type(), and ifc2x3.ifcscheduletimecontrol.scheduleduration.
schedulefinish()
def ifc2x3.ifcscheduletimecontrol.schedulefinish ()
Definition at line 35781 of file ifc2x3.py.
References ifc2x3.ifcscheduletimecontrol._schedulefinish, SCL.TypeChecker.check_type(), ifc2x3.ifcdatetimeselect, and ifc2x3.ifcscheduletimecontrol.schedulefinish.
schedulestart()
def ifc2x3.ifcscheduletimecontrol.schedulestart ()
Definition at line 35725 of file ifc2x3.py.
References ifc2x3.ifcscheduletimecontrol._schedulestart, SCL.TypeChecker.check_type(), ifc2x3.ifcdatetimeselect, and ifc2x3.ifcscheduletimecontrol.schedulestart.
scheduletimecontrolassigned()
def ifc2x3.ifcscheduletimecontrol.scheduletimecontrolassigned ()
Definition at line 35935 of file ifc2x3.py.
startfloat()
def ifc2x3.ifcscheduletimecontrol.startfloat ()
Definition at line 35893 of file ifc2x3.py.
References ifc2x3.ifcscheduletimecontrol._startfloat, SCL.TypeChecker.check_type(), and ifc2x3.ifcscheduletimecontrol.startfloat.
statustime()
def ifc2x3.ifcscheduletimecontrol.statustime ()
Definition at line 35879 of file ifc2x3.py.
References ifc2x3.ifcscheduletimecontrol._statustime, SCL.TypeChecker.check_type(), ifc2x3.ifcdatetimeselect, and ifc2x3.ifcscheduletimecontrol.statustime.
totalfloat()
def ifc2x3.ifcscheduletimecontrol.totalfloat ()
Definition at line 35851 of file ifc2x3.py.
References ifc2x3.ifcworkcontrol._totalfloat, ifc2x3.ifcscheduletimecontrol._totalfloat, SCL.TypeChecker.check_type(), and ifc2x3.ifcscheduletimecontrol.totalfloat.
Member Data Documentation
actualduration
ifc2x3.ifcscheduletimecontrol.actualduration
Definition at line 35672 of file ifc2x3.py.
Referenced by ifc2x3.ifcscheduletimecontrol.actualduration().
actualfinish
ifc2x3.ifcscheduletimecontrol.actualfinish
Definition at line 35667 of file ifc2x3.py.
Referenced by ifc2x3.ifcscheduletimecontrol.actualfinish().
actualstart
ifc2x3.ifcscheduletimecontrol.actualstart
Definition at line 35663 of file ifc2x3.py.
Referenced by ifc2x3.ifcscheduletimecontrol.actualstart().
completion
ifc2x3.ifcscheduletimecontrol.completion
Definition at line 35680 of file ifc2x3.py.
Referenced by ifc2x3.ifcscheduletimecontrol.completion().
earlyfinish
ifc2x3.ifcscheduletimecontrol.earlyfinish
Definition at line 35668 of file ifc2x3.py.
Referenced by ifc2x3.ifcscheduletimecontrol.earlyfinish().
earlystart
ifc2x3.ifcscheduletimecontrol.earlystart
Definition at line 35664 of file ifc2x3.py.
Referenced by ifc2x3.ifcscheduletimecontrol.earlystart().
finishfloat
ifc2x3.ifcscheduletimecontrol.finishfloat
Definition at line 35679 of file ifc2x3.py.
Referenced by ifc2x3.ifcscheduletimecontrol.finishfloat().
freefloat
ifc2x3.ifcscheduletimecontrol.freefloat
Definition at line 35674 of file ifc2x3.py.
Referenced by ifc2x3.ifcscheduletimecontrol.freefloat().
iscritical
ifc2x3.ifcscheduletimecontrol.iscritical
Definition at line 35676 of file ifc2x3.py.
Referenced by ifc2x3.ifcscheduletimecontrol.iscritical().
latefinish
ifc2x3.ifcscheduletimecontrol.latefinish
Definition at line 35669 of file ifc2x3.py.
Referenced by ifc2x3.ifcscheduletimecontrol.latefinish().
latestart
ifc2x3.ifcscheduletimecontrol.latestart
Definition at line 35665 of file ifc2x3.py.
Referenced by ifc2x3.ifcscheduletimecontrol.latestart().
remainingtime
ifc2x3.ifcscheduletimecontrol.remainingtime
Definition at line 35673 of file ifc2x3.py.
Referenced by ifc2x3.ifcscheduletimecontrol.remainingtime().
scheduleduration
ifc2x3.ifcscheduletimecontrol.scheduleduration
Definition at line 35671 of file ifc2x3.py.
Referenced by ifc2x3.ifcscheduletimecontrol.scheduleduration().
schedulefinish
ifc2x3.ifcscheduletimecontrol.schedulefinish
Definition at line 35670 of file ifc2x3.py.
Referenced by ifc2x3.ifcscheduletimecontrol.schedulefinish().
schedulestart
ifc2x3.ifcscheduletimecontrol.schedulestart
Definition at line 35666 of file ifc2x3.py.
Referenced by ifc2x3.ifcscheduletimecontrol.schedulestart().
startfloat
ifc2x3.ifcscheduletimecontrol.startfloat
Definition at line 35678 of file ifc2x3.py.
Referenced by ifc2x3.ifcscheduletimecontrol.startfloat().
statustime
ifc2x3.ifcscheduletimecontrol.statustime
Definition at line 35677 of file ifc2x3.py.
Referenced by ifc2x3.ifcscheduletimecontrol.statustime().
totalfloat
ifc2x3.ifcscheduletimecontrol.totalfloat
Definition at line 35675 of file ifc2x3.py.
Referenced by ifc2x3.ifcscheduletimecontrol.totalfloat().
The documentation for this class was generated from the following file:
ifc2x3.py