FreeCAD: Gui::StatusWidget Class Reference
Gui::StatusWidget Class Reference
#include <Widgets.h>
Public Member Functions
StatusWidget (QWidget *parent)
~StatusWidget () override
void setStatusText (const QString &)
QSize sizeHint () const override
void showText (int ms)
Protected Member Functions
void showEvent (QShowEvent *) override
void hideEvent (QHideEvent *) override
Detailed Description
Definition at line 478 of file Widgets.h.
Constructor & Destructor Documentation
StatusWidget()
StatusWidget::StatusWidget (QWidget * parent)
Definition at line 1233 of file Widgets.cpp.
~StatusWidget()
StatusWidget::~StatusWidget () override default
Member Function Documentation
hideEvent()
void StatusWidget::hideEvent (QHideEvent *) override protected
Definition at line 1273 of file Widgets.cpp.
setStatusText()
void StatusWidget::setStatusText (const QString & s)
Definition at line 1247 of file Widgets.cpp.
References toolbit-attributes::s.
showEvent()
void StatusWidget::showEvent (QShowEvent * event) override protected
Definition at line 1268 of file Widgets.cpp.
showText()
void StatusWidget::showText (int ms)
Definition at line 1252 of file Widgets.cpp.
References draftgeoutils.intersections::connect(), ArchFence::hide(), bimcommands.BimViews::show(), and PersistentToolbarsGui::timer.
sizeHint()
QSize StatusWidget::sizeHint () const override
Definition at line 1263 of file Widgets.cpp.
The documentation for this class was generated from the following files:
Widgets.h
Widgets.cpp