FreeCAD: MeshCore::MeshPointGrid Class Reference
MeshCore::MeshPointGrid Class Reference
#include <Grid.h>
Construction
MeshPointGrid ()
Construction.
MeshPointGrid (const MeshKernel &rclM)
Construction.
MeshPointGrid (const MeshKernel &rclM, int iCtGridPerAxis)
Construction.
MeshPointGrid (const MeshKernel &rclM, float fGridLen)
Construction.
MeshPointGrid (const MeshKernel &rclM, unsigned long ulX, unsigned long ulY, unsigned long ulZ)
Construction.
MeshPointGrid (const MeshPointGrid &)=default
MeshPointGrid (MeshPointGrid &&)=default
~MeshPointGrid () override=default
Destruction.
MeshPointGrid & operator= (const MeshPointGrid &)=default
MeshPointGrid & operator= (MeshPointGrid &&)=default
unsigned long FindElements (const Base::Vector3f &rclPoint, std::set< ElementIndex > &aulElements) const
void Validate (const MeshKernel &rclM) override
virtual void Validate ()
bool Verify () const override
void AddPoint (const MeshPoint &rclPt, ElementIndex ulPtIndex, float fEpsilon=0.0F)
void Pos (const Base::Vector3f &rclPoint, unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
unsigned long HasElements () const override
void RebuildGrid () override
Additional Inherited Members
Public Member Functions inherited from MeshCore::MeshGrid
virtual unsigned long Inside (const Base::BoundBox3f &rclBB, std::vector< ElementIndex > &raulElements, bool bDelDoubles=true) const
virtual unsigned long Inside (const Base::BoundBox3f &rclBB, std::set< ElementIndex > &raulElementss) const
virtual unsigned long Inside (const Base::BoundBox3f &rclBB, std::vector< ElementIndex > &raulElements, const Base::Vector3f &rclOrg, float fMaxDist, bool bDelDoubles=true) const
void SearchNearestFromPoint (const Base::Vector3f &pnt, std::set< ElementIndex > &indices) const
unsigned long GetElements (unsigned long ulX, unsigned long ulY, unsigned long ulZ, std::set< ElementIndex > &raclInd) const
unsigned long GetElements (const Base::Vector3f &rclPoint, std::vector< ElementIndex > &aulFacets) const
virtual void GetGridLengths (float &rfLenX, float &rfLenY, float &rfLenZ) const
virtual void GetCtGrids (unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
virtual ~MeshGrid ()=default
Destruction.
virtual void Attach (const MeshKernel &rclM)
virtual void Rebuild (int iCtGridPerAxis=20)
virtual void Rebuild (unsigned long ulX, unsigned long ulY, unsigned long ulZ)
Base::BoundBox3f GetBoundBox (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
Base::BoundBox3f GetBoundBox () const
Base::BoundBox3f GetMeshBoundBox () const
unsigned long GetIndexToPosition (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
bool GetPositionToIndex (unsigned long id, unsigned long &ulX, unsigned long &ulY, unsigned long &ulZ) const
unsigned long GetCtElements (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
bool CheckPosition (const Base::Vector3f &rclPoint, unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
virtual void Position (const Base::Vector3f &rclPoint, unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
bool CheckPos (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
void GetHull (unsigned long ulX, unsigned long ulY, unsigned long ulZ, unsigned long ulDistance, std::set< ElementIndex > &raclInd) const
Protected Member Functions inherited from MeshCore::MeshGrid
MeshGrid (const MeshKernel &rclM)
Construction.
MeshGrid ()
Construction.
MeshGrid (const MeshGrid &)=default
MeshGrid (MeshGrid &&)=default
MeshGrid & operator= (const MeshGrid &)=default
MeshGrid & operator= (MeshGrid &&)=default
virtual void InitGrid ()
virtual void Clear ()
virtual void CalculateGridLength (int iCtGridPerAxis)
Protected Attributes inherited from MeshCore::MeshGrid
std::vector< std::vector< std::vector< std::set< ElementIndex > > > > _aulGrid
const MeshKernel * _pclMesh
unsigned long _ulCtElements
unsigned long _ulCtGridsX
unsigned long _ulCtGridsY
unsigned long _ulCtGridsZ
float _fGridLenX
float _fGridLenY
float _fGridLenZ
float _fMinX
float _fMinY
float _fMinZ
Detailed Description
Special grid class that stores point indices of the mesh object in its grids.
Definition at line 305 of file Grid.h.
Constructor & Destructor Documentation
MeshPointGrid() [1/7]
MeshPointGrid::MeshPointGrid () default
Construction.
MeshPointGrid() [2/7]
MeshPointGrid::MeshPointGrid (const MeshKernel & rclM) explicit
Construction.
Definition at line 1000 of file Grid.cpp.
References RebuildGrid().
MeshPointGrid() [3/7]
MeshPointGrid::MeshPointGrid (const MeshKernel & rclM, int iCtGridPerAxis)
Construction.
Definition at line 1017 of file Grid.cpp.
References MeshCore::MeshGrid::Rebuild().
MeshPointGrid() [4/7]
MeshPointGrid::MeshPointGrid (const MeshKernel & rclM, float fGridLen)
Construction.
Definition at line 1023 of file Grid.cpp.
References MeshCore::MeshGrid::_pclMesh, MeshCore::MeshKernel::GetBoundBox(), Base::BoundBox3< Precision >::LengthX(), Base::BoundBox3< Precision >::LengthY(), Base::BoundBox3< Precision >::LengthZ(), and MeshCore::MeshGrid::Rebuild().
MeshPointGrid() [5/7]
MeshPointGrid::MeshPointGrid (const MeshKernel & rclM, unsigned long ulX, unsigned long ulY, unsigned long ulZ)
Construction.
Definition at line 1008 of file Grid.cpp.
References MeshCore::MeshGrid::Rebuild().
MeshPointGrid() [6/7]
MeshCore::MeshPointGrid::MeshPointGrid (const MeshPointGrid &) default
MeshPointGrid() [7/7]
MeshCore::MeshPointGrid::MeshPointGrid (MeshPointGrid &&) default
~MeshPointGrid()
MeshCore::MeshPointGrid::~MeshPointGrid () override default
Destruction.
Member Function Documentation
AddPoint()
void MeshPointGrid::AddPoint (const MeshPoint & rclPt, ElementIndex ulPtIndex, float fEpsilon = 0.0F) protected
Adds a new point element to the grid structure. rclPt is the geometric point and ulPtIndex the corresponding index in the mesh kernel.
Definition at line 1032 of file Grid.cpp.
References MeshCore::MeshGrid::_aulGrid, MeshCore::MeshGrid::_ulCtGridsX, MeshCore::MeshGrid::_ulCtGridsY, MeshCore::MeshGrid::_ulCtGridsZ, Pos(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by RebuildGrid().
FindElements()
unsigned long MeshPointGrid::FindElements (const Base::Vector3f & rclPoint, std::set< ElementIndex > & aulElements) const
Finds all points that lie in the same grid as the point rclPoint.
Definition at line 1116 of file Grid.cpp.
References MeshCore::MeshGrid::_ulCtGridsX, MeshCore::MeshGrid::_ulCtGridsY, MeshCore::MeshGrid::_ulCtGridsZ, MeshCore::MeshGrid::GetElements(), and Pos().
HasElements()
unsigned long MeshCore::MeshPointGrid::HasElements () const inline override protected virtual
Returns the number of stored elements.
Implements MeshCore::MeshGrid.
Definition at line 348 of file Grid.h.
operator=() [1/2]
MeshPointGrid& MeshCore::MeshPointGrid::operator= (const MeshPointGrid &) default
operator=() [2/2]
MeshPointGrid& MeshCore::MeshPointGrid::operator= (MeshPointGrid &&) default
Pos()
void MeshPointGrid::Pos (const Base::Vector3f & rclPoint, unsigned long & rulX, unsigned long & rulY, unsigned long & rulZ) const protected
Returns the grid numbers to the given point rclPoint.
Definition at line 1106 of file Grid.cpp.
References MeshCore::MeshGrid::_fGridLenX, MeshCore::MeshGrid::_fGridLenY, MeshCore::MeshGrid::_fGridLenZ, MeshCore::MeshGrid::_fMinX, MeshCore::MeshGrid::_fMinY, MeshCore::MeshGrid::_fMinZ, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by AddPoint(), and FindElements().
RebuildGrid()
void MeshPointGrid::RebuildGrid () override protected virtual
Rebuilds the grid structure.
Implements MeshCore::MeshGrid.
Definition at line 1090 of file Grid.cpp.
References MeshCore::MeshGrid::_pclMesh, MeshCore::MeshGrid::_ulCtElements, AddPoint(), MeshCore::MeshKernel::CountPoints(), SplineSurface::i, MeshCore::MeshPointIterator::Init(), MeshCore::MeshGrid::InitGrid(), MeshCore::MeshPointIterator::More(), and MeshCore::MeshPointIterator::Next().
Referenced by MeshPointGrid(), and Validate().
Validate() [1/2]
void MeshPointGrid::Validate () virtual
Validates the grid structure and rebuilds it if needed.
Definition at line 1054 of file Grid.cpp.
References MeshCore::MeshGrid::_pclMesh, MeshCore::MeshGrid::_ulCtElements, MeshCore::MeshKernel::CountPoints(), and RebuildGrid().
Validate() [2/2]
void MeshPointGrid::Validate (const MeshKernel & rclM) override virtual
Validates the grid structure and rebuilds it if needed.
Implements MeshCore::MeshGrid.
Definition at line 1044 of file Grid.cpp.
References MeshCore::MeshGrid::_pclMesh, MeshCore::MeshGrid::_ulCtElements, MeshCore::MeshGrid::Attach(), MeshCore::MeshKernel::CountPoints(), and RebuildGrid().
Verify()
bool MeshPointGrid::Verify () const override virtual
Verifies the grid structure and returns false if inconsistencies are found.
Implements MeshCore::MeshGrid.
Definition at line 1065 of file Grid.cpp.
References MeshCore::MeshGrid::_pclMesh, MeshCore::MeshGrid::_ulCtElements, MeshCore::MeshKernel::CountFacets(), MeshCore::MeshGridIterator::GetBoundBox(), MeshCore::MeshGridIterator::GetElements(), MeshCore::MeshGridIterator::Init(), Base::BoundBox3< Precision >::IsInBox(), MeshCore::MeshGridIterator::More(), MeshCore::MeshGridIterator::Next(), and MeshCore::MeshPointIterator::Set().
The documentation for this class was generated from the following files:
Grid.h
Grid.cpp