FreeCAD: Gui::CommandActionPy Class Reference
Gui::CommandActionPy Class Reference
#include <CommandActionPy.h>
Public Member Functions
CommandActionPy (Py::PythonClassInstance *self, Py::Tuple &args, Py::Dict &kdws)
~CommandActionPy () override
Py::Object getCommand ()
Static Public Member Functions
static void init_type ()
Protected Member Functions
Py::Object repr () override
Py::Object getattro (const Py::String &attr) override
int setattro (const Py::String &attr_, const Py::Object &value) override
Py::Object getAction ()
Static Protected Member Functions
static PyObject * descriptorGetter (PyObject *self, PyObject *obj, PyObject *type)
static int descriptorSetter (PyObject *self, PyObject *obj, PyObject *value)
Detailed Description
Definition at line 52 of file CommandActionPy.h.
Constructor & Destructor Documentation
CommandActionPy()
CommandActionPy::CommandActionPy (Py::PythonClassInstance * self, Py::Tuple & args, Py::Dict & kdws)
Definition at line 37 of file CommandActionPy.cpp.
References toolbit-attributes::args, Gui::Application::commandManager(), Gui::CommandManager::getCommandByName(), and Gui::Application::Instance.
~CommandActionPy()
CommandActionPy::~CommandActionPy () override default
Member Function Documentation
descriptorGetter()
PyObject * CommandActionPy::descriptorGetter (PyObject * self, PyObject * obj, PyObject * type) static protected
Definition at line 100 of file CommandActionPy.cpp.
References Py::new_reference_to().
Referenced by init_type().
descriptorSetter()
int CommandActionPy::descriptorSetter (PyObject * self, PyObject * obj, PyObject * value) static protected
Definition at line 107 of file CommandActionPy.cpp.
Referenced by init_type().
getAction()
Py::Object CommandActionPy::getAction () protected
Definition at line 51 of file CommandActionPy.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::Application::commandManager(), Gui::PythonWrapper::fromQAction(), Gui::CommandBase::getAction(), Gui::CommandManager::getCommandByName(), Gui::Application::Instance, and Gui::PythonWrapper::loadWidgetsModule().
getattro()
Py::Object CommandActionPy::getattro (const Py::String & attr) override protected
Definition at line 127 of file CommandActionPy.cpp.
References src.Mod.Test.testmakeWireString::String.
getCommand()
Py::Object CommandActionPy::getCommand ()
Definition at line 69 of file CommandActionPy.cpp.
References Gui::Application::commandManager(), Gui::CommandManager::getCommandByName(), and Gui::Application::Instance.
init_type()
void CommandActionPy::init_type () static
Definition at line 84 of file CommandActionPy.cpp.
References descriptorGetter(), descriptorSetter(), and create_qrc::ext.
Referenced by Gui::Application::Application().
repr()
Py::Object CommandActionPy::repr () override protected
Definition at line 119 of file CommandActionPy.cpp.
References toolbit-attributes::s, and src.Mod.Test.testmakeWireString::String.
setattro()
int CommandActionPy::setattro (const Py::String & attr_, const Py::Object & value) override protected
Definition at line 143 of file CommandActionPy.cpp.
References Gui::Application::commandManager(), Gui::CommandManager::getCommandByName(), Gui::Application::Instance, and src.Mod.Test.testmakeWireString::String.
The documentation for this class was generated from the following files:
CommandActionPy.h
CommandActionPy.cpp