FreeCAD: PropertyLinks.cpp File Reference
PropertyLinks.cpp File Reference
#include "PreCompiled.h"
#include <QDir>
#include <QFileInfo>
#include <boost/algorithm/string/predicate.hpp>
#include <Base/Console.h>
#include <Base/Exception.h>
#include <Base/Reader.h>
#include <Base/Writer.h>
#include "PropertyLinks.h"
#include "Application.h"
#include "Document.h"
#include "DocumentObject.h"
#include "DocumentObjectPy.h"
#include "DocumentObserver.h"
#include "ObjectIdentifier.h"
#include "ElementNamingUtils.h"
#include "GeoFeature.h"
Classes
class StringGuard
class App::DocInfo
Macros
#define ATTR_SHADOWED "shadowed"
#define ATTR_SHADOW "shadow"
#define ATTR_MAPPED "mapped"
#define IGNORE_SHADOW false
#define CHECK_SUB_SIZE(_l, _r)
Typedefs
using DocInfoMap = std::map< QString, DocInfoPtr >
Functions
static std::string propertyName (const Property *prop)
static const std::string & getSubNameWithStyle (const std::string &subName, const PropertyLinkBase::ShadowSub &shadow, bool newStyle, std::string &tmp)
static bool updateLinkReference (App::PropertyLinkBase *prop, App::DocumentObject *feature, bool reverse, bool notify, App::DocumentObject *link, std::vector< std::string > &subs, std::vector< int > &mapped, std::vector< PropertyLinkBase::ShadowSub > &shadows)
template<class Func , class... Args>
std::vector< std::string > updateLinkSubs (const App::DocumentObject *obj, const std::vector< std::string > &subs, Func *f, Args &&... args)
static App::DocumentObject * adjustLinkSubs (App::PropertyLinkBase *prop, const std::set< App::DocumentObject * > &inList, App::DocumentObject *link, std::vector< std::string > &subs, std::map< App::DocumentObject *, std::vector< std::string >> *links=nullptr)
Variables
static std::unordered_map< std::string, std::set< PropertyLinkBase * > > _LabelMap
static std::unordered_map< App::DocumentObject *, std::unordered_set< PropertyLinkBase * > > _ElementRefMap
DocInfoMap _DocInfoMap
Macro Definition Documentation
ATTR_MAPPED
#define ATTR_MAPPED "mapped"
Definition at line 1838 of file PropertyLinks.cpp.
ATTR_SHADOW
#define ATTR_SHADOW "shadow"
Definition at line 1837 of file PropertyLinks.cpp.
ATTR_SHADOWED
#define ATTR_SHADOWED "shadowed"
Definition at line 1836 of file PropertyLinks.cpp.
CHECK_SUB_SIZE
#define CHECK_SUB_SIZE (_l, _r)
Value:
    do {                                                                                           \
        if (_l.size() != _r.size())                                                                \
            FC_THROWM(Base::ValueError, "object and subname size mismatch");                       \
    } while (0)
IGNORE_SHADOW
#define IGNORE_SHADOW false
Definition at line 1840 of file PropertyLinks.cpp.
Typedef Documentation
DocInfoMap
using DocInfoMap = std::map<QString, DocInfoPtr>
Definition at line 3287 of file PropertyLinks.cpp.
Function Documentation
adjustLinkSubs()
static App::DocumentObject* adjustLinkSubs (App::PropertyLinkBase * prop, const std::set< App::DocumentObject * > & inList, App::DocumentObject * link, std::vector< std::string > & subs, std::map< App::DocumentObject *, std::vector< std::string >> * links = nullptr) static
Definition at line 2099 of file PropertyLinks.cpp.
References App::DocumentObject::getDocument(), App::DocumentObject::getSubObject(), App::PropertyLinkBase::LinkAllowExternal, RobotExample::pos, importers.importIFCmulticore::subs, and App::PropertyLinkBase::testFlag().
Referenced by App::PropertyLinkSub::adjustLink(), App::PropertyXLink::adjustLink(), and App::PropertyXLinkSubList::adjustLink().
getSubNameWithStyle()
static const std::string& getSubNameWithStyle (const std::string & subName, const PropertyLinkBase::ShadowSub & shadow, bool newStyle, std::string & tmp) inline static
Definition at line 1379 of file PropertyLinks.cpp.
References Data::hasMissingElement(), App::ElementNamePair::newName, App::ElementNamePair::oldName, and RobotExample::pos.
Referenced by App::PropertyXLink::getSubName(), App::PropertyLinkSub::getSubValues(), App::PropertyLinkSubList::getSubValues(), App::PropertyXLink::getSubValues(), and App::PropertyLinkSub::getSubValuesStartsWith().
propertyName()
static std::string propertyName (const Property * prop) static
Definition at line 245 of file PropertyLinks.cpp.
References App::Property::getContainer(), App::Property::getFullName(), and App::Property::hasName().
Referenced by App::PropertyLinkBase::_updateElementReference(), Materials::Material::addAppearance(), Materials::Material::addPhysical(), Materials::MaterialYamlEntry::addToTree(), MatGui::Array2D::Array2D(), MatGui::Array3D::Array3D(), Gui::Dialog::Placement::bindObject(), MatGui::MaterialDelegate::editorEvent(), Gui::Dialog::find_placement::getProperty(), App::ObjectIdentifier::ResolveResults::getProperty(), MatGui::MaterialDelegate::getValue(), MatGui::ImageEdit::ImageEdit(), Materials::Material::isAppearanceModelComplete(), Materials::Material::isPhysicalModelComplete(), MatGui::ListEdit::ListEdit(), Materials::Material::modelAppearanceChanged(), Materials::Material::modelChanged(), MatGui::MaterialDelegate::notifyChanged(), MatGui::MaterialsEditor::onAppearanceRemove(), MatGui::MaterialsEditor::onPhysicalRemove(), App::ObjectIdentifier::ResolveResults::resolveErrorString(), App::ObjectIdentifier::resolveProperty(), App::PropertyXLinkContainer::Restore(), Materials::Material::saveAppearanceModels(), Materials::Material::saveModels(), Gui::Dialog::Placement::setPlacementAndBindObject(), Gui::Dialog::TaskPlacement::setPlacementAndBindObject(), MatGui::MaterialDelegate::setValue(), MatGui::TextEdit::TextEdit(), and App::PropertyLinkBase::updateElementReferences().
updateLinkReference()
static bool updateLinkReference (App::PropertyLinkBase * prop, App::DocumentObject * feature, bool reverse, bool notify, App::DocumentObject * link, std::vector< std::string > & subs, std::vector< int > & mapped, std::vector< PropertyLinkBase::ShadowSub > & shadows) static
Definition at line 1514 of file PropertyLinks.cpp.
References App::PropertyLinkBase::_updateElementReference(), App::Property::getContainer(), SplineSurface::i, App::DocumentObject::isAttachedToDocument(), femsolver.signal::notify(), importers.importIFCmulticore::subs, and App::PropertyLinkBase::unregisterElementReference().
Referenced by App::PropertyLinkSub::updateElementReference(), and App::PropertyXLink::updateElementReference().
updateLinkSubs()
template<class Func , class... Args> std::vector<std::string> updateLinkSubs (const App::DocumentObject * obj, const std::vector< std::string > & subs, Func * f, Args &&... args)
Definition at line 1953 of file PropertyLinks.cpp.
References toolbit-attributes::args, App::DocumentObject::isAttachedToDocument(), Path.Post.scripts.opensbp_post::move(), and importers.importIFCmulticore::subs.
Referenced by App::PropertyLinkSub::CopyOnImportExternal(), App::PropertyXLink::CopyOnImportExternal(), App::PropertyLinkSub::CopyOnLabelChange(), and App::PropertyXLink::CopyOnLabelChange().
Variable Documentation
_DocInfoMap
DocInfoMap _DocInfoMap
Definition at line 3288 of file PropertyLinks.cpp.
Referenced by App::DocInfo::breakLinks(), App::DocInfo::deinit(), App::DocInfo::get(), App::PropertyXLink::getDocumentInList(), App::PropertyXLink::getDocumentOutList(), App::PropertyXLink::hasXLink(), App::DocInfo::restoreDocument(), and App::DocInfo::slotSaveDocument().
_ElementRefMap
std::unordered_map<App::DocumentObject*, std::unordered_set<PropertyLinkBase*> > _ElementRefMap static
Definition at line 62 of file PropertyLinks.cpp.
Referenced by App::PropertyLinkBase::_registerElementReference(), App::PropertyLinkBase::_updateElementReference(), App::PropertyLinkBase::getElementReferences(), App::PropertyLinkBase::unregisterElementReference(), and App::PropertyLinkBase::updateElementReferences().
_LabelMap
std::unordered_map<std::string, std::set<PropertyLinkBase*> > _LabelMap static
Definition at line 61 of file PropertyLinks.cpp.
Referenced by App::PropertyLinkBase::registerLabelReferences(), App::PropertyLinkBase::unregisterLabelReferences(), and App::PropertyLinkBase::updateLabelReferences().