FreeCAD: App::ColorModelPack Struct Reference
App::ColorModelPack Struct Reference
#include <ColorModel.h>
Static Public Member Functions
static ColorModelPack createRedGreenBlue ()
static ColorModelPack createBlueGreenRed ()
static ColorModelPack createWhiteBlack ()
static ColorModelPack createBlackWhite ()
static ColorModelPack createRedWhiteBlue ()
Public Attributes
ColorModel totalModel = ColorModelBlueGreenRed()
ColorModel topModel = ColorModelGreenYellowRed()
ColorModel bottomModel = ColorModelBlueCyanGreen()
std::string description
Detailed Description
Definition at line 273 of file ColorModel.h.
Member Function Documentation
createBlackWhite()
ColorModelPack ColorModelPack::createBlackWhite () static
Definition at line 64 of file ColorModel.cpp.
Referenced by App::ColorGradient::createStandardPacks().
createBlueGreenRed()
ColorModelPack ColorModelPack::createBlueGreenRed () static
Definition at line 46 of file ColorModel.cpp.
Referenced by App::ColorGradient::createStandardPacks().
createRedGreenBlue()
ColorModelPack ColorModelPack::createRedGreenBlue () static
Definition at line 37 of file ColorModel.cpp.
Referenced by App::ColorGradient::createStandardPacks().
createRedWhiteBlue()
ColorModelPack ColorModelPack::createRedWhiteBlue () static
Definition at line 73 of file ColorModel.cpp.
Referenced by App::ColorGradient::createStandardPacks().
createWhiteBlack()
ColorModelPack ColorModelPack::createWhiteBlack () static
Definition at line 55 of file ColorModel.cpp.
Referenced by App::ColorGradient::createStandardPacks().
Member Data Documentation
bottomModel
ColorModel App::ColorModelPack::bottomModel = ColorModelBlueCyanGreen()
Definition at line 277 of file ColorModel.h.
Referenced by App::ColorGradient::getColorModel(), App::ColorGradient::rebuild(), and App::ColorGradient::setColorModel().
description
std::string App::ColorModelPack::description
Definition at line 278 of file ColorModel.h.
Referenced by src.Mod.AddonManager.Addon.Addon::to_cache().
topModel
ColorModel App::ColorModelPack::topModel = ColorModelGreenYellowRed()
Definition at line 276 of file ColorModel.h.
Referenced by App::ColorGradient::getColorModel(), App::ColorGradient::rebuild(), and App::ColorGradient::setColorModel().
totalModel
ColorModel App::ColorModelPack::totalModel = ColorModelBlueGreenRed()
Definition at line 275 of file ColorModel.h.
Referenced by App::ColorGradient::getColorModel(), App::ColorGradient::rebuild(), and App::ColorGradient::setColorModel().
The documentation for this struct was generated from the following files:
ColorModel.h
ColorModel.cpp