FreeCAD: Gui::CheckListDialog Class Reference
Gui::CheckListDialog Class Reference
#include <Widgets.h>
Public Member Functions
CheckListDialog (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~CheckListDialog () override
void setCheckableItems (const QStringList &items)
void setCheckableItems (const QList< CheckListItem > &items)
QStringList getCheckedItems () const
void accept () override
Detailed Description
The CheckListDialog class provides a dialog with a QListView with checkable items inside.
Author
Werner Mayer
Definition at line 199 of file Widgets.h.
Constructor & Destructor Documentation
CheckListDialog()
CheckListDialog::CheckListDialog (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
Constructs a CheckListDialog which is a child of 'parent', with the name 'name' and widget flags set to 'f'
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
Definition at line 554 of file Widgets.cpp.
~CheckListDialog()
CheckListDialog::~CheckListDialog () override default
Destroys the object and frees any allocated resources
Member Function Documentation
accept()
void CheckListDialog::accept () override
Collects all checked items to be able to return them by call getCheckedItems().
Definition at line 602 of file Widgets.cpp.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
getCheckedItems()
QStringList CheckListDialog::getCheckedItems () const
Returns a list of the check items.
Definition at line 594 of file Widgets.cpp.
setCheckableItems() [1/2]
void CheckListDialog::setCheckableItems (const QList< CheckListItem > & items)
Sets the items to the dialog's list view. If the boolean type of a CheckListItem is set to false the item is not checkable any more.
Definition at line 582 of file Widgets.cpp.
References src.Mod.Test.testPathArray::items.
setCheckableItems() [2/2]
void CheckListDialog::setCheckableItems (const QStringList & items)
Sets the items to the dialog's list view. By default all items are checkable..
Definition at line 569 of file Widgets.cpp.
References src.Mod.Test.testPathArray::items.
The documentation for this class was generated from the following files:
Widgets.h
Widgets.cpp