FreeCAD: Span Class Reference
Span Class Reference
#include <Curve.h>
Public Member Functions
Span ()
Span (const Point &p, const CVertex &v, bool start_span=false)
Point NearestPoint (const Point &p) const
Point NearestPoint (const Span &p, double *d=NULL) const
void GetBox (CBox2D &box)
double IncludedAngle () const
double GetArea () const
bool On (const Point &p, double *t=NULL) const
Point MidPerim (double d) const
Point MidParam (double param) const
double Length () const
Point GetVector (double fraction) const
void Intersect (const Span &s, std::list< Point > &pts) const
Public Attributes
bool m_start_span
Point m_p
CVertex m_v
Detailed Description
Definition at line 70 of file Curve.h.
Constructor & Destructor Documentation
Span() [1/2]
Span::Span ()
Definition at line 1035 of file Curve.cpp.
Span() [2/2]
Span::Span (const Point & p, const CVertex & v, bool start_span = false) inline
Definition at line 84 of file Curve.h.
Member Function Documentation
GetArea()
double Span::GetArea () const
Definition at line 1268 of file Curve.cpp.
References DraftVecUtils::angle(), Point::dist(), IncludedAngle(), CVertex::m_c, CVertex::m_p, m_p, CVertex::m_type, m_v, Point::x, and Point::y.
Referenced by BOOST_PYTHON_MODULE(), CCurve::GetArea(), and init_pyarea().
GetBox()
void Span::GetBox (CBox2D & box)
Definition at line 1197 of file Curve.cpp.
References MengerSponge::box, Point::dist(), GetQuadrant(), SplineSurface::i, CVertex::m_c, CVertex::m_p, m_p, CVertex::m_type, m_v, QuadrantEndPoint(), and InitGui::t.
Referenced by BOOST_PYTHON_MODULE(), CCurve::GetBox(), and init_pyarea().
GetVector()
Point Span::GetVector (double fraction) const
returns the direction vector at point which is 0-1 along span
Definition at line 1330 of file Curve.cpp.
References CVertex::m_c, CVertex::m_p, m_p, CVertex::m_type, m_v, MidParam(), buildPsets::p, and TestSpreadsheet::v.
Referenced by BOOST_PYTHON_MODULE(), init_pyarea(), MakeObround(), CCurve::Offset(), and CCurve::OffsetForward().
IncludedAngle()
double Span::IncludedAngle () const
Definition at line 1250 of file Curve.cpp.
References IncludedAngle(), CVertex::m_c, CVertex::m_p, m_p, CVertex::m_type, m_v, and Point::normalize().
Referenced by BOOST_PYTHON_MODULE(), GetArea(), init_pyarea(), Length(), and MidParam().
Intersect()
void Span::Intersect (const Span & s, std::list< Point > & pts) const
Definition at line 1350 of file Curve.cpp.
References geoff_geometry::Span::Intof(), MakeSpan(), toolbit-attributes::s, InitGui::t, geoff_geometry::Point::x, and geoff_geometry::Point::y.
Referenced by spanIntersect(), and CCurve::SpanIntersections().
Length()
double Span::Length () const
Definition at line 1320 of file Curve.cpp.
References Point::dist(), IncludedAngle(), CVertex::m_c, CVertex::m_p, m_p, CVertex::m_type, and m_v.
Referenced by BOOST_PYTHON_MODULE(), init_pyarea(), CCurve::Perim(), CCurve::PerimToPoint(), and CCurve::PointToPerim().
MidParam()
Point Span::MidParam (double param) const
returns a point which is 0-1 along span
Definition at line 1097 of file Curve.cpp.
References IncludedAngle(), CVertex::m_c, CVertex::m_p, m_p, CVertex::m_type, m_v, buildPsets::p, Init::param, and TestSpreadsheet::v.
Referenced by BOOST_PYTHON_MODULE(), GetVector(), and init_pyarea().
MidPerim()
Point Span::MidPerim (double d) const
returns a point which is 0-d along span
Definition at line 1079 of file Curve.cpp.
References CVertex::m_c, CVertex::m_p, m_p, CVertex::m_type, m_v, Point::normalize(), buildPsets::p, and TestSpreadsheet::v.
Referenced by BOOST_PYTHON_MODULE(), init_pyarea(), and CCurve::PerimToPoint().
NearestPoint() [1/2]
Point Span::NearestPoint (const Point & p) const
Definition at line 1060 of file Curve.cpp.
References CVertex::m_p, m_p, m_v, buildPsets::p, and InitGui::t.
Referenced by BOOST_PYTHON_MODULE(), init_pyarea(), NearestPoint(), CCurve::NearestPoint(), On(), and CCurve::PointToPerim().
NearestPoint() [2/2]
Point Span::NearestPoint (const Span & p, double * d = NULL) const
Definition at line 1146 of file Curve.cpp.
References NearestPoint(), and buildPsets::p.
On()
bool Span::On (const Point & p, double * t = NULL) const
Definition at line 1309 of file Curve.cpp.
References NearestPoint(), buildPsets::p, and InitGui::t.
Referenced by BOOST_PYTHON_MODULE(), CCurve::Break(), CCurve::ChangeEnd(), CCurve::ChangeStart(), CCurve::ExtractSeparateCurves(), GetCurveItem::GetCurve(), init_pyarea(), and CArea::SpanIntersections().
Member Data Documentation
m_p
Point Span::m_p
Definition at line 81 of file Curve.h.
Referenced by BOOST_PYTHON_MODULE(), GetArea(), GetBox(), GetVector(), IncludedAngle(), init_pyarea(), Length(), MakeSpan(), MidParam(), MidPerim(), NearestPoint(), CCurve::Offset(), and CCurve::OffsetForward().
m_start_span
bool Span::m_start_span
Definition at line 80 of file Curve.h.
m_v
CVertex Span::m_v
Definition at line 82 of file Curve.h.
Referenced by BOOST_PYTHON_MODULE(), GetArea(), GetBox(), GetVector(), IncludedAngle(), init_pyarea(), Length(), CArea::MakePocketToolpath(), MakeSpan(), MidParam(), MidPerim(), NearestPoint(), CCurve::OffsetForward(), and CCurve::PointToPerim().
The documentation for this class was generated from the following files:
Curve.h
Curve.cpp