FreeCAD: src.Mod.Show.ShowUtils Namespace Reference
src.Mod.Show.ShowUtils Namespace Reference
Functions
def is3DObject (obj)
Function Documentation
is3DObject()
def src.Mod.Show.ShowUtils.is3DObject (obj)
is3DObject(obj): tests if the object has some 3d geometry.
TempoVis is made only for objects in 3d view, so all objects that don't pass this check are ignored by TempoVis.
Definition at line 24 of file ShowUtils.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by src.Mod.Show.mTempoVis.TempoVis.allVisibleObjects(), src.Mod.Show.mTempoVis.TempoVis.clipPlane(), and src.Mod.Show.mTempoVis.TempoVis.setUnpickable().