FreeCAD: draftguitools.gui_edit_draft_objects.DraftWireGuiTools Class Reference
draftguitools.gui_edit_draft_objects.DraftWireGuiTools Class Reference
DRAFT » draftguitools
Public Member Functions
def __init__ (self)
def get_edit_points (self, obj)
def update_object_from_edit_points (self, obj, node_idx, v, alt_edit_mode=0)
def get_edit_point_context_menu (self, edit_command, obj, node_idx)
def get_edit_obj_context_menu (self, edit_command, obj, position)
def get_open_close_menu_text (self, obj)
def get_reverse_menu_text (self, obj)
def init_preview_object (self, obj)
def update_preview_object (self, edit_command, obj, node_idx, v)
def add_point (self, edit_command, obj, pos)
def delete_point (self, obj, node_idx)
def open_close_wire (self, obj)
def reverse_wire (self, obj)
Public Member Functions inherited from draftguitools.gui_edit_base_object.GuiTools
def get_object_style (self, obj)
def set_object_editing_style (self, obj)
def restore_object_style (self, obj, modes)
Detailed Description
Definition at line 62 of file gui_edit_draft_objects.py.
Constructor & Destructor Documentation
__init__()
def draftguitools.gui_edit_draft_objects.DraftWireGuiTools.__init__ (self)
Reimplemented from draftguitools.gui_edit_base_object.GuiTools.
Definition at line 64 of file gui_edit_draft_objects.py.
Member Function Documentation
add_point()
def draftguitools.gui_edit_draft_objects.DraftWireGuiTools.add_point (self, edit_command, obj, pos)
Add point to obj.
Reimplemented in draftguitools.gui_edit_draft_objects.DraftBSplineGuiTools.
Definition at line 144 of file gui_edit_draft_objects.py.
Referenced by draftguitools.gui_edit_draft_objects.DraftWireGuiTools.get_edit_obj_context_menu(), and draftguitools.gui_edit_draft_objects.DraftBezCurveGuiTools.get_edit_obj_context_menu().
delete_point()
def draftguitools.gui_edit_draft_objects.DraftWireGuiTools.delete_point (self, obj, node_idx)
Definition at line 175 of file gui_edit_draft_objects.py.
Referenced by draftguitools.gui_edit_draft_objects.DraftWireGuiTools.get_edit_point_context_menu(), and draftguitools.gui_edit_draft_objects.DraftBezCurveGuiTools.get_edit_point_context_menu().
get_edit_obj_context_menu()
def draftguitools.gui_edit_draft_objects.DraftWireGuiTools.get_edit_obj_context_menu (self, edit_command, obj, position)
Get the context menu associated to edited object (user is over the object)
Return a list of tuples containing menu labels and associated functions:
    return [
("action label", lambda: self.handle_action_label(edit_command, obj, position)),
    ]
Parameters:
edit_command: running Draft_Edit command
obj: the edited object
position: position of the cursor on the screen (x, y)
Reimplemented from draftguitools.gui_edit_base_object.GuiTools.
Definition at line 113 of file gui_edit_draft_objects.py.
References draftguitools.gui_edit_draft_objects.DraftWireGuiTools.add_point(), draftguitools.gui_edit_draft_objects.DraftWireGuiTools.get_open_close_menu_text(), draftguitools.gui_edit_draft_objects.DraftWireGuiTools.get_reverse_menu_text(), draftguitools.gui_edit_draft_objects.DraftWireGuiTools.open_close_wire(), and draftguitools.gui_edit_draft_objects.DraftWireGuiTools.reverse_wire().
get_edit_point_context_menu()
def draftguitools.gui_edit_draft_objects.DraftWireGuiTools.get_edit_point_context_menu (self, edit_command, obj, node_idx)
Get the context menu associated to edit points (user is over an editpoint)
Return a list of tuples containing menu labels and associated functions:
    return [
("action label", lambda: self.handle_action_label(edit_command, obj, node_idx)),
    ]
Parameters:
edit_command: running Draft_Edit command
obj: the edited object
node_idx: number of the edited node
Reimplemented from draftguitools.gui_edit_base_object.GuiTools.
Definition at line 108 of file gui_edit_draft_objects.py.
References draftguitools.gui_edit_draft_objects.DraftWireGuiTools.delete_point().
get_edit_points()
def draftguitools.gui_edit_draft_objects.DraftWireGuiTools.get_edit_points (self, obj)
Return to Draft_Edit a list of vectors for the given object.
Remember to use object local coordinates system.
Parameters:
obj: the object
Reimplemented from draftguitools.gui_edit_base_object.GuiTools.
Definition at line 67 of file gui_edit_draft_objects.py.
get_open_close_menu_text()
def draftguitools.gui_edit_draft_objects.DraftWireGuiTools.get_open_close_menu_text (self, obj)
This function is overridden in the DraftBSplineGuiTools class.
Reimplemented in draftguitools.gui_edit_draft_objects.DraftBSplineGuiTools.
Definition at line 120 of file gui_edit_draft_objects.py.
Referenced by draftguitools.gui_edit_draft_objects.DraftWireGuiTools.get_edit_obj_context_menu(), and draftguitools.gui_edit_draft_objects.DraftBezCurveGuiTools.get_edit_obj_context_menu().
get_reverse_menu_text()
def draftguitools.gui_edit_draft_objects.DraftWireGuiTools.get_reverse_menu_text (self, obj)
This function is overridden in the DraftBSplineGuiTools class.
Reimplemented in draftguitools.gui_edit_draft_objects.DraftBSplineGuiTools.
Definition at line 128 of file gui_edit_draft_objects.py.
Referenced by draftguitools.gui_edit_draft_objects.DraftWireGuiTools.get_edit_obj_context_menu().
init_preview_object()
def draftguitools.gui_edit_draft_objects.DraftWireGuiTools.init_preview_object (self, obj)
Reimplemented from draftguitools.gui_edit_base_object.GuiTools.
Reimplemented in draftguitools.gui_edit_draft_objects.DraftBSplineGuiTools.
Definition at line 133 of file gui_edit_draft_objects.py.
open_close_wire()
def draftguitools.gui_edit_draft_objects.DraftWireGuiTools.open_close_wire (self, obj)
Definition at line 186 of file gui_edit_draft_objects.py.
Referenced by draftguitools.gui_edit_draft_objects.DraftWireGuiTools.get_edit_obj_context_menu(), and draftguitools.gui_edit_draft_objects.DraftBezCurveGuiTools.get_edit_obj_context_menu().
reverse_wire()
def draftguitools.gui_edit_draft_objects.DraftWireGuiTools.reverse_wire (self, obj)
Definition at line 190 of file gui_edit_draft_objects.py.
Referenced by draftguitools.gui_edit_draft_objects.DraftWireGuiTools.get_edit_obj_context_menu(), and draftguitools.gui_edit_draft_objects.DraftBezCurveGuiTools.get_edit_obj_context_menu().
update_object_from_edit_points()
def draftguitools.gui_edit_draft_objects.DraftWireGuiTools.update_object_from_edit_points (self, obj, node_idx, v, alt_edit_mode = 0)
Update the object from modified Draft_Edit point.
No need to recompute at the end.
Parameters:
obj: the object
node_idx: number of the edited node
v: target vector of the node in object local coordinates system
alt_edit_mode: alternative edit mode to perform different operations
       (usually can be selected from the Draft_Edit context menu)
       default = 0
Reimplemented from draftguitools.gui_edit_base_object.GuiTools.
Definition at line 73 of file gui_edit_draft_objects.py.
update_preview_object()
def draftguitools.gui_edit_draft_objects.DraftWireGuiTools.update_preview_object (self, edit_command, obj, node_idx, v)
Reimplemented from draftguitools.gui_edit_base_object.GuiTools.
Reimplemented in draftguitools.gui_edit_draft_objects.DraftBSplineGuiTools.
Definition at line 136 of file gui_edit_draft_objects.py.
The documentation for this class was generated from the following file:
gui_edit_draft_objects.py