FreeCAD: femexamples.truss_3d_cs_circle_ele_seg2 Namespace Reference
femexamples.truss_3d_cs_circle_ele_seg2 Namespace Reference
Functions
def get_information ()
def setup (doc=None, solvertype="z88")
Function Documentation
get_information()
def femexamples.truss_3d_cs_circle_ele_seg2.get_information ()
Definition at line 33 of file truss_3d_cs_circle_ele_seg2.py.
setup()
def femexamples.truss_3d_cs_circle_ele_seg2.setup (doc = None, solvertype = "z88")
Definition at line 45 of file truss_3d_cs_circle_ele_seg2.py.
References femexamples.meshes.mesh_beamsimple_tetra10.create_elements(), femexamples.meshes.mesh_beamsimple_tetra10.create_nodes(), femexamples.manager.get_meshname(), and femexamples.manager.init_doc().