FreeCAD: Gui::Dialog::CameraDialog Class Reference
Gui::Dialog::CameraDialog Class Reference
#include <DlgSettingsNavigation.h>
Public Member Functions
CameraDialog (QWidget *parent=nullptr)
~CameraDialog () override
void setValues (double q0, double q1, double q2, double q3)
void getValues (double &q0, double &q1, double &q2, double &q3) const
Detailed Description
Definition at line 69 of file DlgSettingsNavigation.h.
Constructor & Destructor Documentation
CameraDialog()
CameraDialog::CameraDialog (QWidget * parent = nullptr) explicit
Definition at line 355 of file DlgSettingsNavigation.cpp.
References draftgeoutils.intersections::connect(), and Sketcher::Horizontal.
~CameraDialog()
CameraDialog::~CameraDialog () override default
Member Function Documentation
getValues()
void CameraDialog::getValues (double & q0, double & q1, double & q2, double & q3) const
Definition at line 438 of file DlgSettingsNavigation.cpp.
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::loadDefaults(), and draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle().
setValues()
void CameraDialog::setValues (double q0, double q1, double q2, double q3)
Definition at line 430 of file DlgSettingsNavigation.cpp.
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle().
The documentation for this class was generated from the following files:
DlgSettingsNavigation.h
DlgSettingsNavigation.cpp