FreeCAD: PartGui::FilletEdgesDialog Class Reference
PartGui::FilletEdgesDialog Class Reference
#include <DlgFilletEdges.h>
Public Member Functions
FilletEdgesDialog (DlgFilletEdges::FilletType type, Part::FilletBase *fillet, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~FilletEdgesDialog () override
void accept () override
Detailed Description
Definition at line 125 of file DlgFilletEdges.h.
Constructor & Destructor Documentation
FilletEdgesDialog()
FilletEdgesDialog::FilletEdgesDialog (DlgFilletEdges::FilletType type, Part::FilletBase * fillet, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags())
Definition at line 1044 of file DlgFilletEdges.cpp.
References accept(), draftgeoutils.intersections::connect(), and Path.Post.scripts.grbl_post::type.
~FilletEdgesDialog()
FilletEdgesDialog::~FilletEdgesDialog () override default
Member Function Documentation
accept()
void FilletEdgesDialog::accept () override
Definition at line 1063 of file DlgFilletEdges.cpp.
References PartGui::DlgFilletEdges::accept().
Referenced by FilletEdgesDialog().
The documentation for this class was generated from the following files:
DlgFilletEdges.h
DlgFilletEdges.cpp