FreeCAD: MeshGui::ThumbnailExtension3MF Class Reference
MeshGui::ThumbnailExtension3MF Class Reference
#include <ThumbnailExtension.h>
Public Member Functions
Mesh::Extension3MF::Resource addMesh (const Mesh::MeshObject &mesh) override
Public Member Functions inherited from Mesh::Extension3MF
Extension3MF ()=default
Public Member Functions inherited from Mesh::AbstractFormatExtension
virtual ~AbstractFormatExtension ()=default
AbstractFormatExtension (const AbstractFormatExtension &)=delete
AbstractFormatExtension (AbstractFormatExtension &&)=delete
AbstractFormatExtension & operator= (const AbstractFormatExtension &)=delete
AbstractFormatExtension & operator= (AbstractFormatExtension &&)=delete
Additional Inherited Members
Public Types inherited from Mesh::Extension3MF
using Resource = MeshCore::Resource3MF
Protected Member Functions inherited from Mesh::AbstractFormatExtension
AbstractFormatExtension ()=default
Detailed Description
Definition at line 52 of file ThumbnailExtension.h.
Member Function Documentation
addMesh()
Mesh::Extension3MF::Resource ThumbnailExtension3MF::addMesh (const Mesh::MeshObject & mesh) override virtual
Implements Mesh::Extension3MF.
Definition at line 45 of file ThumbnailExtension.cpp.
References MeshCore::Resource3MF::contentType, MeshGui::ViewProviderMeshBuilder::createMesh(), MeshCore::Resource3MF::extension, MeshCore::Resource3MF::fileContent, Mesh2Shape::mesh, MeshCore::Resource3MF::relationshipType, Gui::SoQtOffscreenRenderer::render(), Gui::SoQtOffscreenRenderer::setBackgroundColor(), and Gui::SoQtOffscreenRenderer::writeToImage().
The documentation for this class was generated from the following files:
ThumbnailExtension.h
ThumbnailExtension.cpp