FreeCAD: Gui::InputField Class Reference
Gui::InputField Class Reference
#include <InputField.h>
Public Member Functions
InputField (QWidget *parent=nullptr)
~InputField () override
void setValue (const Base::Quantity &)
set the field with a quantity
void setValue (const double &)
Base::Quantity getQuantity () const
get the current value
double rawValue () const
Get the current quantity without unit.
QString getQuantityString () const
get stored, valid quantity as a string (user string - avoid storing)
void setQuantityString (const QString &text)
set, validate and display quantity from a string. Must match existing units.
QString rawText () const
return the quantity in C locale, i.e. decimal separator is a dot.
void setRawText (const QString &text)
expects the string in C locale and internally converts it into the OS-specific locale
bool hasValidInput ()
void setUnit (const Base::Unit &)
const Base::Unit & getUnit () const
void setToLastUsedValue ()
set the input field to the last used value (works only if the setParamGrpPath() was called)
double singleStep () const
get the value of the singleStep property
void setSingleStep (double)
set the value of the singleStep property
double maximum () const
get the value of the maximum property
void setMaximum (double)
set the value of the maximum property
double minimum () const
get the value of the minimum property
void setMinimum (double)
set the value of the minimum property
int historySize () const
get the value of the minimum property
void setHistorySize (int)
set the value of the minimum property
void setUnitText (const QString &)
set the unit by a string (can be used in the *.ui file)
QString getUnitText ()
get the unit as a string (can be used in the *.ui file)
int getPrecision () const
get the value of the precision property
void setPrecision (const int)
set the value of the precision property (can be used in the *.ui file)
QString getFormat () const
get the value of the format property: "f" (fixed), "e" (scientific), "g" (general)
void setFormat (const QString &)
set the value of the format property (can be used in the *.ui file)
void selectNumber ()
set the number portion selected (use after setValue())
void fixup (QString &input) const
input validation
QValidator::State validate (QString &input, int &pos) const
input validation
Public Member Functions inherited from Gui::ExpressionLineEdit
ExpressionLineEdit (QWidget *parent=nullptr, bool noProperty=false, char checkPrefix=0, bool checkInList=true)
void setDocumentObject (const App::DocumentObject *currentDocObj, bool checkInList=true)
void setPrefix (char prefix)
bool completerActive () const
void hideCompleter ()
void setNoProperty (bool enabled=true)
void setExactMatch (bool enabled=true)
Public Member Functions inherited from Gui::ExpressionWidget
ExpressionWidget ()
QPixmap getIcon (const char *name, const QSize &size) const
Public Member Functions inherited from Gui::ExpressionBinding
ExpressionBinding ()
virtual ~ExpressionBinding ()
virtual void bind (const App::Property &prop)
bool isBound () const
void unbind ()
bool hasExpression () const
bool autoApply () const
void setAutoApply (bool value)
Properties
QByteArray prefPath
double singleStep
get the value of the singleStep property
double maximum
get the value of the maximum property
double minimum
get the value of the minimum property
double rawValue
int historySize
QString unit
int precision
QString format
Base::Quantity quantity
QString quantityString
QString rawText
return the quantity in C locale, i.e. decimal separator is a dot.
history and default management
QByteArray paramGrpPath () const
the param group path where the widget writes and reads the default values
void setParamGrpPath (const QByteArray &name)
set the param group path where the widget writes and reads the default values
void pushToHistory (const QString &valueq=QString())
push a new value to the history, if no string given the actual text of the input field is used.
std::vector< QString > getHistory ()
get the history of the field, newest first
void pushToSavedValues (const QString &valueq=QString())
push a new value to the history, if no string given the actual text of the input field is used.
std::vector< QString > getSavedValues ()
get the history of the field, newest first
void bind (const App::ObjectIdentifier &_path) override
bool apply (const std::string &propName) override
bool apply () override
void valueChanged (const Base::Quantity &)
void valueChanged (double)
void parseError (const QString &errorText)
signal for an invalid user input (signals a lot while typing!)
void newInput (const QString &text)
void updateIconLabel (const QString &text)
void showEvent (QShowEvent *event) override
void focusInEvent (QFocusEvent *event) override
void focusOutEvent (QFocusEvent *event) override
void keyPressEvent (QKeyEvent *event) override
void wheelEvent (QWheelEvent *event) override
void contextMenuEvent (QContextMenuEvent *event) override
void resizeEvent (QResizeEvent *) override
Additional Inherited Members
Public Slots inherited from Gui::ExpressionLineEdit
void slotTextChanged (const QString &text)
void slotCompleteText (const QString &completionPrefix, bool isActivated)
void slotCompleteTextHighlighted (const QString &completionPrefix)
void slotCompleteTextSelected (const QString &completionPrefix)
Signals inherited from Gui::ExpressionLineEdit
void textChanged2 (QString text, int pos)
Protected Member Functions inherited from Gui::ExpressionLineEdit
void keyPressEvent (QKeyEvent *event) override
void contextMenuEvent (QContextMenuEvent *event) override
Protected Member Functions inherited from Gui::ExpressionWidget
void makeLabel (QLineEdit *parent)
Protected Member Functions inherited from Gui::ExpressionBinding
const App::ObjectIdentifier & getPath () const
std::shared_ptr< App::Expression > getExpression () const
std::string getExpressionString (bool no_throw=true) const
std::string getEscapedExpressionString () const
bool assignToProperty (const std::string &propName, double)
virtual void setExpression (std::shared_ptr< App::Expression > expr)
virtual void onChange ()
void expressionChange (const App::ObjectIdentifier &id)
void objectDeleted (const App::DocumentObject &)
Protected Attributes inherited from Gui::ExpressionWidget
ExpressionLabel * iconLabel {nullptr}
QPalette defaultPalette
int iconHeight {-1}
Protected Attributes inherited from Gui::ExpressionBinding
boost::signals2::scoped_connection expressionchanged
boost::signals2::scoped_connection objectdeleted
bool m_autoApply {false}
Detailed Description
The InputField class The input field widget handles all around user input of Quantities. That includes parsing and checking input. Providing a context menu for common operations and managing default and history values. Although it's derived from a QLineEdit widget, it supports most of the properties and signals of a spin box.
Author
Jrgen Riegel
Definition at line 58 of file InputField.h.
Constructor & Destructor Documentation
InputField()
InputField::InputField (QWidget * parent = nullptr)
Definition at line 69 of file InputField.cpp.
References draftgeoutils.intersections::connect(), App::GetApplication(), Gui::ExpressionWidget::iconLabel, newInput(), and updateIconLabel().
~InputField()
InputField::~InputField () override default
Member Function Documentation
apply() [1/2]
bool InputField::apply () override virtual
Reimplemented from Gui::ExpressionBinding.
Definition at line 139 of file InputField.cpp.
References Gui::ExpressionBinding::apply().
apply() [2/2]
bool InputField::apply (const std::string & propName) override virtual
Reimplemented from Gui::ExpressionBinding.
Definition at line 129 of file InputField.cpp.
References Gui::ExpressionBinding::apply(), Gui::Command::Doc, doCommand, getQuantity(), and getValue().
bind()
void InputField::bind (const App::ObjectIdentifier & _path) override virtual
Reimplemented from Gui::ExpressionBinding.
Definition at line 107 of file InputField.cpp.
References Gui::ExpressionBinding::bind(), App::ObjectIdentifier::getDocumentObject(), App::DocumentObject::getExpression(), Gui::ExpressionBinding::getPath(), getProperty(), newInput(), src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::Quantity, and Gui::ExpressionLineEdit::setDocumentObject().
contextMenuEvent()
void InputField::contextMenuEvent (QContextMenuEvent * event) override protected
Definition at line 191 of file InputField.cpp.
References getHistory(), getSavedValues(), SplineSurface::i, NavigationIndicatorGui::menu, and pushToSavedValues().
fixup()
void InputField::fixup (QString & input) const
input validation
Definition at line 710 of file InputField.cpp.
Referenced by Gui::InputValidator::fixup(), newInput(), and validate().
focusInEvent()
void InputField::focusInEvent (QFocusEvent * event) override protected
Definition at line 620 of file InputField.cpp.
References selectNumber().
focusOutEvent()
void InputField::focusOutEvent (QFocusEvent * event) override protected
Definition at line 632 of file InputField.cpp.
References getUnit(), Base::Quantity::getUserString(), and App::ExpressionParser::parse().
getFormat()
QString InputField::getFormat () const
get the value of the format property: "f" (fixed), "e" (scientific), "g" (general)
Definition at line 565 of file InputField.cpp.
References Base::Quantity::getFormat(), and Base::QuantityFormat::toFormat().
getHistory()
std::vector< QString > InputField::getHistory ()
get the history of the field, newest first
Definition at line 336 of file InputField.cpp.
References ParameterGrp::GetASCII(), SplineSurface::i, and Base::Reference< T >::isValid().
Referenced by contextMenuEvent(), pushToHistory(), and setToLastUsedValue().
getPrecision()
int InputField::getPrecision () const
get the value of the precision property
Definition at line 552 of file InputField.cpp.
References Base::Quantity::getFormat(), and Base::QuantityFormat::precision.
getQuantity()
Base::Quantity Gui::InputField::getQuantity () const inline
get the current value
Definition at line 86 of file InputField.h.
Referenced by apply(), materialtests.TestMaterials.MaterialTestCases::test2DArray(), materialtests.TestMaterials.MaterialTestCases::test3DArray(), materialtests.TestMaterials.MaterialTestCases::testCalculiXSteel(), and materialtests.TestMaterialCreation.MaterialCreationTestCases::testCreateMaterial().
getQuantityString()
QString InputField::getQuantityString () const
get stored, valid quantity as a string (user string - avoid storing)
get stored, valid quantity as a string
Definition at line 457 of file InputField.cpp.
References Base::Quantity::getUserString().
getSavedValues()
std::vector< QString > InputField::getSavedValues ()
get the history of the field, newest first
Definition at line 384 of file InputField.cpp.
References ParameterGrp::GetASCII(), SplineSurface::i, and Base::Reference< T >::isValid().
Referenced by contextMenuEvent().
getUnit()
const Base::Unit & InputField::getUnit () const
Definition at line 451 of file InputField.cpp.
Referenced by focusOutEvent().
getUnitText()
QString InputField::getUnitText ()
get the unit as a string (can be used in the *.ui file)
Definition at line 544 of file InputField.cpp.
References Base::Quantity::getUserString().
hasValidInput()
bool Gui::InputField::hasValidInput () inline
gives the current state of the user input, gives true if it is a valid input with correct quantity (shown by the green pixmap), returns false if the input is a unparsable string or has a wrong unit (shown by the red pixmap in the gui)
Definition at line 105 of file InputField.h.
historySize()
int Gui::InputField::historySize () const
get the value of the minimum property
keyPressEvent()
void InputField::keyPressEvent (QKeyEvent * event) override protected
Definition at line 651 of file InputField.cpp.
References Base::Quantity::getUserString(), and toolbit-attributes::val.
maximum()
double Gui::InputField::maximum () const
get the value of the maximum property
minimum()
double Gui::InputField::minimum () const
get the value of the minimum property
newInput
void InputField::newInput (const QString & text) protected slot
Definition at line 238 of file InputField.cpp.
References SCL.SimpleDataTypes::e, fixup(), Gui::ExpressionBinding::getExpression(), Base::Quantity::getFormat(), Gui::ExpressionBinding::getPath(), Base::Quantity::getUnit(), Base::Quantity::getUserString(), Base::Quantity::getValue(), Gui::ExpressionWidget::iconLabel, Gui::ExpressionBinding::isBound(), Base::Unit::isEmpty(), App::ExpressionParser::parse(), parseError(), Gui::ExpressionBinding::setExpression(), Base::Quantity::setFormat(), Base::Quantity::setUnit(), Base::Quantity::setValue(), and valueChanged().
Referenced by bind(), InputField(), setQuantityString(), and setRawText().
paramGrpPath()
QByteArray InputField::paramGrpPath () const
the param group path where the widget writes and reads the default values
Returns the widget's preferences path.
Definition at line 412 of file InputField.cpp.
References Base::Reference< T >::isValid().
parseError
void Gui::InputField::parseError (const QString & errorText) signal
signal for an invalid user input (signals a lot while typing!)
Referenced by Gui::Dialog::DlgUnitsCalculator::DlgUnitsCalculator(), and newInput().
pushToHistory()
void InputField::pushToHistory (const QString & valueq = QString())
push a new value to the history, if no string given the actual text of the input field is used.
Definition at line 307 of file InputField.cpp.
References ParameterGrp::GetASCII(), getHistory(), SplineSurface::i, Base::Reference< T >::isValid(), ParameterGrp::SetASCII(), and toolbit-attributes::val.
pushToSavedValues()
void InputField::pushToSavedValues (const QString & valueq = QString())
push a new value to the history, if no string given the actual text of the input field is used.
Definition at line 362 of file InputField.cpp.
References ParameterGrp::GetASCII(), SplineSurface::i, Base::Reference< T >::isValid(), and ParameterGrp::SetASCII().
Referenced by contextMenuEvent().
rawText()
QString Gui::InputField::rawText () const
return the quantity in C locale, i.e. decimal separator is a dot.
rawValue()
double Gui::InputField::rawValue () const
Get the current quantity without unit.
resizeEvent()
void InputField::resizeEvent (QResizeEvent *) override protected
Definition at line 178 of file InputField.cpp.
References exportCSG::center(), Gui::ExpressionWidget::iconLabel, and MovieTool::y.
selectNumber()
void InputField::selectNumber ()
set the number portion selected (use after setValue())
Definition at line 596 of file InputField.cpp.
References src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression.
Referenced by focusInEvent(), showEvent(), and wheelEvent().
setFormat()
void InputField::setFormat (const QString & format)
set the value of the format property (can be used in the *.ui file)
Definition at line 570 of file InputField.cpp.
References SCL.SimpleDataTypes::c, SCL.SimpleDataTypes::f, format, Base::Quantity::getFormat(), Base::Quantity::setFormat(), and Base::QuantityFormat::toFormat().
Referenced by Path.Main.Gui.Inspect.GCodeHighlighter::highlightBlock(), and Path.Post.Utils.GCodeHighlighter::highlightBlock().
setHistorySize()
void InputField::setHistorySize (int i)
set the value of the minimum property
Definition at line 588 of file InputField.cpp.
References SplineSurface::i.
setMaximum()
void InputField::setMaximum (double m)
set the value of the maximum property
Definition at line 508 of file InputField.cpp.
References Base::Quantity::getValue(), test::m, and Base::Quantity::setValue().
setMinimum()
void InputField::setMinimum (double m)
set the value of the minimum property
Definition at line 524 of file InputField.cpp.
References Base::Quantity::getValue(), test::m, and Base::Quantity::setValue().
setParamGrpPath()
void InputField::setParamGrpPath (const QByteArray & path)
set the param group path where the widget writes and reads the default values
Sets the preference path to path.
Definition at line 404 of file InputField.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and Base::Reference< T >::isValid().
setPrecision()
void InputField::setPrecision (const int precision)
set the value of the precision property (can be used in the *.ui file)
Definition at line 557 of file InputField.cpp.
References format, Base::Quantity::getFormat(), precision, and Base::Quantity::setFormat().
setQuantityString()
void InputField::setQuantityString (const QString & text)
set, validate and display quantity from a string. Must match existing units.
Definition at line 463 of file InputField.cpp.
References newInput().
setRawText()
void InputField::setRawText (const QString & text)
expects the string in C locale and internally converts it into the OS-specific locale
Definition at line 481 of file InputField.cpp.
References Base::Quantity::getUserString(), newInput(), and Base::Quantity::parse().
setSingleStep()
void InputField::setSingleStep (double s)
set the value of the singleStep property
Definition at line 496 of file InputField.cpp.
References toolbit-attributes::s.
setToLastUsedValue()
void InputField::setToLastUsedValue ()
set the input field to the last used value (works only if the setParamGrpPath() was called)
Definition at line 355 of file InputField.cpp.
References getHistory().
setUnit()
void InputField::setUnit (const Base::Unit & unit)
sets the Unit this field is working with. After setting the Unit the field will only accept user input with this unit type. Or if the user input a value without unit, this one will be added to the resulting Quantity.
Definition at line 444 of file InputField.cpp.
References Base::Quantity::setUnit(), and unit.
Referenced by setUnitText().
setUnitText()
void InputField::setUnitText (const QString & str)
set the unit by a string (can be used in the *.ui file)
Definition at line 533 of file InputField.cpp.
References Base::Quantity::getUnit(), Base::Quantity::parse(), setUnit(), and Path.Post.scripts.refactored_centroid_post::str.
setValue() [1/2]
void InputField::setValue (const Base::Quantity & quant)
set the field with a quantity
sets the field with a quantity
Definition at line 420 of file InputField.cpp.
References Base::Quantity::getUnit(), Base::Quantity::getValue(), and Base::Quantity::setValue().
Referenced by setValue().
setValue() [2/2]
void InputField::setValue (const double & value)
Definition at line 434 of file InputField.cpp.
References setValue().
showEvent()
void InputField::showEvent (QShowEvent * event) override protected
Definition at line 610 of file InputField.cpp.
References selectNumber().
singleStep()
double Gui::InputField::singleStep () const
get the value of the singleStep property
updateIconLabel
void InputField::updateIconLabel (const QString & text) protected slot
Definition at line 186 of file InputField.cpp.
References Gui::ExpressionWidget::iconLabel.
Referenced by InputField().
validate()
QValidator::State InputField::validate (QString & input, int & pos) const
input validation
Definition at line 727 of file InputField.cpp.
References fixup(), Base::Quantity::getUserString(), Base::Quantity::getValue(), App::ExpressionParser::parse(), and RobotExample::pos.
Referenced by Gui::InputValidator::validate().
valueChanged [1/2]
void Gui::InputField::valueChanged (const Base::Quantity &) signal
gets emitted if the user has entered a VALID input Valid means the user inputted string obeys all restrictions like: minimum, maximum and/or the right Unit (if specified). If you want the unfiltered/non-validated input use textChanged(const QString&) instead:
Referenced by Gui::Dialog::DlgUnitsCalculator::DlgUnitsCalculator(), and newInput().
valueChanged [2/2]
void Gui::InputField::valueChanged (double) signal
gets emitted if the user has entered a VALID input Valid means the user inputted string obeys all restrictions like: minimum, maximum and/or the right Unit (if specified). If you want the unfiltered/non-validated input use textChanged(const QString&) instead:
wheelEvent()
void InputField::wheelEvent (QWheelEvent * event) override protected
Definition at line 683 of file InputField.cpp.
References Base::Quantity::getUserString(), selectNumber(), and toolbit-attributes::val.
Property Documentation
format
QString Gui::InputField::format read write
Definition at line 70 of file InputField.h.
Referenced by setFormat(), and setPrecision().
historySize
int InputField::historySize read write
Definition at line 67 of file InputField.h.
maximum
double InputField::maximum read write
get the value of the maximum property
Definition at line 64 of file InputField.h.
minimum
double InputField::minimum read write
get the value of the minimum property
Definition at line 65 of file InputField.h.
precision
int Gui::InputField::precision read write
Definition at line 69 of file InputField.h.
Referenced by ifc2x3.ifcgeometricrepresentationsubcontext::ifcgeometricrepresentationcontext_precision(), ifc4.ifcgeometricrepresentationsubcontext::ifcgeometricrepresentationcontext_precision(), and setPrecision().
prefPath
QByteArray Gui::InputField::prefPath read write
Definition at line 62 of file InputField.h.
quantity
Base::Quantity Gui::InputField::quantity read write
Definition at line 71 of file InputField.h.
Referenced by automotive_design.quantified_assembly_component_usage::wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.quantified_assembly_component_usage::wr1(), automotive_design.make_from_usage_option::wr1(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.make_from_usage_option::wr1().
quantityString
QString Gui::InputField::quantityString read write
Definition at line 72 of file InputField.h.
rawText
QString InputField::rawText read write
return the quantity in C locale, i.e. decimal separator is a dot.
Definition at line 73 of file InputField.h.
rawValue
double InputField::rawValue read write
Definition at line 66 of file InputField.h.
singleStep
double InputField::singleStep read write
get the value of the singleStep property
Definition at line 63 of file InputField.h.
unit
QString Gui::InputField::unit read write
Definition at line 68 of file InputField.h.
Referenced by setUnit().
The documentation for this class was generated from the following files:
InputField.h
InputField.cpp