FreeCAD: Gui::UiLoaderPy Class Reference
Gui::UiLoaderPy Class Reference
#include <UiLoader.h>
Public Member Functions
UiLoaderPy ()
~UiLoaderPy () override
Py::Object repr () override
Py::Object createWidget (const Py::Tuple &)
Py::Object load (const Py::Tuple &)
Py::Object addPluginPath (const Py::Tuple &)
Py::Object clearPluginPaths (const Py::Tuple &)
Py::Object pluginPaths (const Py::Tuple &)
Py::Object availableWidgets (const Py::Tuple &)
Py::Object errorString (const Py::Tuple &)
Py::Object isLanguageChangeEnabled (const Py::Tuple &)
Py::Object setLanguageChangeEnabled (const Py::Tuple &)
Py::Object setWorkingDirectory (const Py::Tuple &)
Py::Object workingDirectory (const Py::Tuple &)
Static Public Member Functions
static void init_type ()
Detailed Description
Definition at line 148 of file UiLoader.h.
Constructor & Destructor Documentation
UiLoaderPy()
UiLoaderPy::UiLoaderPy ()
Definition at line 555 of file UiLoader.cpp.
References Gui::UiLoader::newInstance().
~UiLoaderPy()
UiLoaderPy::~UiLoaderPy () override default
Member Function Documentation
addPluginPath()
Py::Object UiLoaderPy::addPluginPath (const Py::Tuple & args)
Definition at line 631 of file UiLoader.cpp.
References toolbit-attributes::args, Gui::PythonWrapper::loadCoreModule(), and Gui::PythonWrapper::toCString().
Referenced by init_type().
availableWidgets()
Py::Object UiLoaderPy::availableWidgets (const Py::Tuple &)
Definition at line 659 of file UiLoader.cpp.
References Base::Factory::CanProduce(), src.Mod.Test.testmakeWireString::String, and Gui::WidgetFactory().
Referenced by init_type().
clearPluginPaths()
Py::Object UiLoaderPy::clearPluginPaths (const Py::Tuple &)
Definition at line 643 of file UiLoader.cpp.
Referenced by init_type().
createWidget()
Py::Object UiLoaderPy::createWidget (const Py::Tuple & args)
Definition at line 621 of file UiLoader.cpp.
References toolbit-attributes::args, draftgeoutils.faces::bind(), and Gui::UiLoader::createWidget().
Referenced by init_type().
errorString()
Py::Object UiLoaderPy::errorString (const Py::Tuple &)
Definition at line 675 of file UiLoader.cpp.
References src.Mod.Test.testmakeWireString::String.
Referenced by init_type().
init_type()
void UiLoaderPy::init_type () static
Definition at line 528 of file UiLoader.cpp.
References addPluginPath(), availableWidgets(), clearPluginPaths(), createWidget(), errorString(), isLanguageChangeEnabled(), load(), pluginPaths(), setLanguageChangeEnabled(), setWorkingDirectory(), and workingDirectory().
Referenced by Gui::Application::Application().
isLanguageChangeEnabled()
Py::Object UiLoaderPy::isLanguageChangeEnabled (const Py::Tuple &)
Definition at line 680 of file UiLoader.cpp.
Referenced by init_type().
load()
Py::Object UiLoaderPy::load (const Py::Tuple & args)
Definition at line 570 of file UiLoader.cpp.
References toolbit-attributes::args, Gui::PythonWrapper::createChildrenNameAttributes(), DrawingExample::file, Gui::PythonWrapper::fromQWidget(), Gui::PythonWrapper::getWrapperName(), Gui::PythonWrapper::loadCoreModule(), Gui::PythonWrapper::loadGuiModule(), Gui::PythonWrapper::loadWidgetsModule(), Init::parent, src.Mod.AddonManager.addonmanager_pyside_interface::QObject, Gui::PythonWrapper::setParent(), src.Mod.Test.testmakeWireString::String, Gui::PythonWrapper::toCString(), and Gui::PythonWrapper::toQObject().
Referenced by init_type(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::loadDefaults(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onLoadStyle(), and draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle().
pluginPaths()
Py::Object UiLoaderPy::pluginPaths (const Py::Tuple &)
Definition at line 649 of file UiLoader.cpp.
References src.Mod.Test.testmakeWireString::String.
Referenced by init_type().
repr()
Py::Object UiLoaderPy::repr () override
Definition at line 562 of file UiLoader.cpp.
References toolbit-attributes::s, and src.Mod.Test.testmakeWireString::String.
setLanguageChangeEnabled()
Py::Object UiLoaderPy::setLanguageChangeEnabled (const Py::Tuple & args)
Definition at line 685 of file UiLoader.cpp.
References toolbit-attributes::args.
Referenced by init_type().
setWorkingDirectory()
Py::Object UiLoaderPy::setWorkingDirectory (const Py::Tuple & args)
Definition at line 691 of file UiLoader.cpp.
References toolbit-attributes::args, Gui::PythonWrapper::loadCoreModule(), and Gui::PythonWrapper::toCString().
Referenced by init_type().
workingDirectory()
Py::Object UiLoaderPy::workingDirectory (const Py::Tuple &)
Definition at line 703 of file UiLoader.cpp.
References src.Mod.Test.testmakeWireString::String.
Referenced by init_type().
The documentation for this class was generated from the following files:
UiLoader.h
UiLoader.cpp