FreeCAD: JointObject Namespace Reference
JointObject Namespace Reference
Classes
class GroundedJoint
class Joint
class MakeJointSelGate
class TaskAssemblyCreateJoint
class ViewProviderGroundedJoint
class ViewProviderJoint
Functions
def solveIfAllowed (assembly, storePrev=False)
def getContext (obj)
Variables
translate = App.Qt.translate
list TranslatedJointTypes
list JointTypes
list JointUsingDistance
list JointUsingDistance2
list JointNoNegativeDistance
list JointUsingOffset
list JointUsingRotation
list JointUsingReverse
list JointUsingLimitLength
list JointUsingLimitAngle
list JointUsingPreSolve
list JointParallelForbidden
activeTask = None
Function Documentation
getContext()
def JointObject.getContext (obj)
Fetch the context of an object.
Definition at line 152 of file JointObject.py.
solveIfAllowed()
def JointObject.solveIfAllowed (assembly, storePrev = False)
Definition at line 145 of file JointObject.py.
References Preferences.preferences().
Referenced by CommandInsertNewPart.TaskAssemblyNewPart.accept(), JointObject.TaskAssemblyCreateJoint.accept(), JointObject.Joint.flipOnePart(), and JointObject.Joint.onChanged().
Variable Documentation
activeTask
JointObject.activeTask = None
Definition at line 1180 of file JointObject.py.
JointNoNegativeDistance
list JointObject.JointNoNegativeDistance
Initial value:
 =  [
     "RackPinion",
     "Screw",
     "Gears",
     "Belt",
 ]
Definition at line 95 of file JointObject.py.
JointParallelForbidden
list JointObject.JointParallelForbidden
Initial value:
 =  [
     "Angle",
     "Perpendicular",
 ]
Definition at line 139 of file JointObject.py.
JointTypes
list JointObject.JointTypes
Initial value:
 =  [
     "Fixed",
     "Revolute",
     "Cylindrical",
     "Slider",
     "Ball",
     "Distance",
     "Parallel",
     "Perpendicular",
     "Angle",
     "RackPinion",
     "Screw",
     "Gears",
     "Belt",
 ]
Definition at line 65 of file JointObject.py.
JointUsingDistance
list JointObject.JointUsingDistance
Initial value:
 =  [
     "Distance",
     "Angle",
     "RackPinion",
     "Screw",
     "Gears",
     "Belt",
 ]
Definition at line 81 of file JointObject.py.
JointUsingDistance2
list JointObject.JointUsingDistance2
Initial value:
 =  [
     "Gears",
     "Belt",
 ]
Definition at line 90 of file JointObject.py.
JointUsingLimitAngle
list JointObject.JointUsingLimitAngle
Initial value:
 =  [
     "Revolute",
     "Cylindrical",
 ]
Definition at line 126 of file JointObject.py.
JointUsingLimitLength
list JointObject.JointUsingLimitLength
Initial value:
 =  [
     "Cylindrical",
     "Slider",
 ]
Definition at line 121 of file JointObject.py.
JointUsingOffset
list JointObject.JointUsingOffset
Initial value:
 =  [
     "Fixed",
     "Revolute",
 ]
Definition at line 102 of file JointObject.py.
JointUsingPreSolve
list JointObject.JointUsingPreSolve
Initial value:
 =  [
     "Fixed",
     "Revolute",
     "Cylindrical",
     "Slider",
     "Ball",
 ]
Definition at line 131 of file JointObject.py.
JointUsingReverse
list JointObject.JointUsingReverse
Initial value:
 =  [
     "Fixed",
     "Revolute",
     "Cylindrical",
     "Slider",
     "Distance",
     "Parallel",
 ]
Definition at line 112 of file JointObject.py.
JointUsingRotation
list JointObject.JointUsingRotation
Initial value:
 =  [
     "Fixed",
     "Slider",
 ]
Definition at line 107 of file JointObject.py.
translate
JointObject.translate = App.Qt.translate
Definition at line 47 of file JointObject.py.
TranslatedJointTypes
list JointObject.TranslatedJointTypes
Initial value:
 =  [
     translate("Assembly", "Fixed"),
     translate("Assembly", "Revolute"),
     translate("Assembly", "Cylindrical"),
     translate("Assembly", "Slider"),
     translate("Assembly", "Ball"),
     translate("Assembly", "Distance"),
     translate("Assembly", "Parallel"),
     translate("Assembly", "Perpendicular"),
     translate("Assembly", "Angle"),
     translate("Assembly", "RackPinion"),
     translate("Assembly", "Screw"),
     translate("Assembly", "Gears"),
     translate("Assembly", "Belt"),
 ]
Definition at line 49 of file JointObject.py.