FreeCAD: ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.drawing_revision Class Reference
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.drawing_revision Class Reference
Public Member Functions
def __init__ (self, revision_identifier, drawing_identifier, intended_scale)
def revision_identifier ()
def drawing_identifier ()
def intended_scale ()
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.presentation_set
def areas ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
revision_identifier
drawing_identifier
intended_scale
Detailed Description
Entity drawing_revision definition.
:param revision_identifier
:type revision_identifier:identifier
:param drawing_identifier
:type drawing_identifier:drawing_definition
:param intended_scale
:type intended_scale:text
Definition at line 30822 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Constructor & Destructor Documentation
__init__()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.drawing_revision.__init__ (self, revision_identifier, drawing_identifier, intended_scale)
Definition at line 30834 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Member Function Documentation
drawing_identifier()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.drawing_revision.drawing_identifier ()
Definition at line 30855 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.drawing_revision._drawing_identifier, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.drawing_revision.drawing_identifier.
intended_scale()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.drawing_revision.intended_scale ()
Definition at line 30869 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.drawing_revision._intended_scale, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.drawing_revision.intended_scale.
revision_identifier()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.drawing_revision.revision_identifier ()
Definition at line 30841 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.drawing_revision._revision_identifier, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.drawing_revision.revision_identifier.
Member Data Documentation
drawing_identifier
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.drawing_revision.drawing_identifier
Definition at line 30837 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.drawing_revision.drawing_identifier().
intended_scale
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.drawing_revision.intended_scale
Definition at line 30838 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.drawing_revision.intended_scale().
revision_identifier
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.drawing_revision.revision_identifier
Definition at line 30836 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.drawing_revision.revision_identifier().
The documentation for this class was generated from the following file:
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py