FreeCAD: CommandAlterGeometry.cpp File Reference
CommandAlterGeometry.cpp File Reference
#include "PreCompiled.h"
#include <Gui/Action.h>
#include <Gui/Application.h>
#include <Gui/BitmapFactory.h>
#include <Gui/CommandT.h>
#include <Gui/Document.h>
#include <Gui/MainWindow.h>
#include <Gui/Notifications.h>
#include <Gui/Selection.h>
#include <Gui/SelectionObject.h>
#include <Mod/Sketcher/App/SketchObject.h>
#include "GeometryCreationMode.h"
#include "Utils.h"
#include "ViewProviderSketch.h"
Namespaces
SketcherGui
Functions
bool isAlterGeoActive (Gui::Document *doc)
void CreateSketcherCommandsAlterGeo ()
Variables
GeometryCreationMode SketcherGui::geometryCreationMode = GeometryCreationMode::Normal
Function Documentation
CreateSketcherCommandsAlterGeo()
void CreateSketcherCommandsAlterGeo ()
Definition at line 251 of file CommandAlterGeometry.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
isAlterGeoActive()
bool isAlterGeoActive (Gui::Document * doc)
Definition at line 47 of file CommandAlterGeometry.cpp.
References toolbit-attributes::doc, and Base::Persistence::getClassTypeId().