FreeCAD: MeshCore::LMCylinderFunctor Struct Reference
MeshCore::LMCylinderFunctor Struct Reference
Public Member Functions
int operator() (const Eigen::VectorXd &xvec, Eigen::VectorXd &fvec) const
int df (const Eigen::VectorXd &x, Eigen::MatrixXd &fjac) const
int values () const
int inputs () const
Public Attributes
Eigen::MatrixXd measuredValues
int m
int n
Detailed Description
Definition at line 988 of file Approximation.cpp.
Member Function Documentation
df()
int MeshCore::LMCylinderFunctor::df (const Eigen::VectorXd & x, Eigen::MatrixXd & fjac) const inline
Definition at line 1031 of file Approximation.cpp.
References SCL.SimpleDataTypes::e, KDL::epsilon, SplineSurface::i, operator()(), values(), and MovieTool::x.
inputs()
int MeshCore::LMCylinderFunctor::inputs () const inline
Definition at line 1075 of file Approximation.cpp.
References n.
operator()()
int MeshCore::LMCylinderFunctor::operator() (const Eigen::VectorXd & xvec, Eigen::VectorXd & fvec) const inline
Definition at line 993 of file Approximation.cpp.
References a, SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::c, SplineSurface::i, measuredValues, KDL::sqrt(), buildPsets::u, TestSpreadsheet::v, values(), src.Mod.PartDesign.fcgear.svggear::w, MovieTool::x, and MovieTool::y.
Referenced by df().
values()
int MeshCore::LMCylinderFunctor::values () const inline
Definition at line 1066 of file Approximation.cpp.
References m.
Referenced by df(), and operator()().
Member Data Documentation
m
int MeshCore::LMCylinderFunctor::m
Definition at line 1063 of file Approximation.cpp.
Referenced by MeshCore::CylinderFit::Fit(), and values().
measuredValues
Eigen::MatrixXd MeshCore::LMCylinderFunctor::measuredValues
Definition at line 990 of file Approximation.cpp.
Referenced by MeshCore::CylinderFit::Fit(), and operator()().
n
int MeshCore::LMCylinderFunctor::n
Definition at line 1072 of file Approximation.cpp.
Referenced by MeshCore::CylinderFit::Fit(), and inputs().
The documentation for this struct was generated from the following file:
Approximation.cpp