FreeCAD: PartGui::DlgImportStep Class Reference
PartGui::DlgImportStep Class Reference
#include <DlgImportStep.h>
Public Member Functions
DlgImportStep (QWidget *parent=nullptr)
~DlgImportStep () override
void saveSettings () override
void loadSettings () override
StepImportSettings getSettings () const
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
Definition at line 50 of file DlgImportStep.h.
Constructor & Destructor Documentation
DlgImportStep()
DlgImportStep::DlgImportStep (QWidget * parent = nullptr) explicit
Definition at line 38 of file DlgImportStep.cpp.
References Part::OCAF::ImportExportSettings::getCodePageList(), Part::OCAF::ImportExportSettings::getExpandCompound(), Part::OCAF::ImportExportSettings::getImportHiddenObject(), Part::OCAF::ImportExportSettings::getReadShapeCompoundMode(), Part::OCAF::ImportExportSettings::getReduceObjects(), Part::OCAF::ImportExportSettings::getShowProgress(), Part::OCAF::ImportExportSettings::getUseBaseName(), and Part::OCAF::ImportExportSettings::getUseLinkGroup().
~DlgImportStep()
DlgImportStep::~DlgImportStep () override default
Destroys the object and frees any allocated resources
Member Function Documentation
changeEvent()
void DlgImportStep::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 123 of file DlgImportStep.cpp.
References SCL.SimpleDataTypes::e.
getSettings()
StepImportSettings DlgImportStep::getSettings () const
Definition at line 101 of file DlgImportStep.cpp.
References PartGui::StepImportSettings::codePage, PartGui::StepImportSettings::expandCompound, Part::OCAF::ImportExportSettings::getExpandCompound(), Part::OCAF::ImportExportSettings::getImportCodePage(), Part::OCAF::ImportExportSettings::getImportHiddenObject(), Part::OCAF::ImportExportSettings::getImportMode(), Part::OCAF::ImportExportSettings::getReadShapeCompoundMode(), Part::OCAF::ImportExportSettings::getReduceObjects(), Part::OCAF::ImportExportSettings::getShowProgress(), Part::OCAF::ImportExportSettings::getUseBaseName(), Part::OCAF::ImportExportSettings::getUseLinkGroup(), PartGui::StepImportSettings::importHidden, PartGui::StepImportSettings::merge, PartGui::StepImportSettings::mode, PartGui::StepImportSettings::reduceObjects, PartGui::StepImportSettings::showProgress, PartGui::StepImportSettings::useBaseName, and PartGui::StepImportSettings::useLinkGroup.
loadSettings()
void DlgImportStep::loadSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 85 of file DlgImportStep.cpp.
Referenced by PartGui::DlgImportExportStep::loadSettings().
saveSettings()
void DlgImportStep::saveSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 69 of file DlgImportStep.cpp.
Referenced by PartGui::DlgImportExportStep::saveSettings().
The documentation for this class was generated from the following files:
DlgImportStep.h
DlgImportStep.cpp