FreeCAD: Data::ElementMap Class Reference
Data::ElementMap Class Reference
#include <ElementMap.h>
Classes
struct MappedChildElements
Public Member Functions
ElementMap ()
void beforeSave (const ::App::StringHasherRef &hasherRef) const
void save (std::ostream &stream) const
ElementMapPtr restore (::App::StringHasherRef hasherRef, std::istream &stream)
MappedName setElementName (const IndexedName &element, const MappedName &name, long masterTag, const ElementIDRefs *sid=nullptr, bool overwrite=false)
void encodeElementName (char element_type, MappedName &name, std::ostringstream &ss, ElementIDRefs *sids, long masterTag, const char *postfix=nullptr, long tag=0, bool forceTag=false) const
void erase (const MappedName &name)
Remove name from the map.
void erase (const IndexedName &idx)
Remove idx and all the MappedNames associated with it.
unsigned long size () const
bool empty () const
IndexedName find (const MappedName &name, ElementIDRefs *sids=nullptr) const
MappedName find (const IndexedName &idx, ElementIDRefs *sids=nullptr) const
std::vector< std::pair< MappedName, ElementIDRefs > > findAll (const IndexedName &idx) const
bool hasChildElementMap () const
void hashChildMaps (long masterTag)
void addChildElements (long masterTag, const std::vector< MappedChildElements > &children)
std::vector< MappedChildElements > getChildElements () const
std::vector< MappedElement > getAll () const
long getElementHistory (const MappedName &name, long masterTag, MappedName *original=nullptr, std::vector< MappedName > *history=nullptr) const
void traceElement (const MappedName &name, long masterTag, TraceCallback cb) const
Public Attributes
App::StringHasherRef hasher
String hasher for element name shortening.
Detailed Description
Definition at line 92 of file ElementMap.h.
Constructor & Destructor Documentation
ElementMap()
Data::ElementMap::ElementMap ()
Default constructor: hooks internal functions to signalSaveDocument and signalStartRestoreDocument. This is related to the save and restore process of the map.
Definition at line 70 of file ElementMap.cpp.
Member Function Documentation
addChildElements()
void Data::ElementMap::addChildElements (long masterTag, const std::vector< MappedChildElements > & children)
Definition at line 1083 of file ElementMap.cpp.
References Data::MappedName::clear(), Data::ELEMENT_MAP_PREFIX, encodeElementName(), FC_ERR, FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, FC_WARN, Data::MappedName::find(), Data::IndexedName::getIndex(), Data::IndexedName::getType(), SplineSurface::i, setElementName(), and Data::MappedName::toBytes().
beforeSave()
void Data::ElementMap::beforeSave (const ::App::StringHasherRef & hasherRef) const
Ensures that naming is properly assigned. It then marks as "used" all the StringID that are used to make up this particular map and are stored in the hasherRef passed as a parameter. Finally do this recursively for all childEelementMaps as well.
Parameters
hasherRef where all the StringID needed to build the map are stored.
Definition at line 76 of file ElementMap.cpp.
References Data::_elementMapToId, SplineSurface::id, and Data::MappedNameRef::next.
empty()
bool Data::ElementMap::empty () const
Definition at line 814 of file ElementMap.cpp.
encodeElementName()
void Data::ElementMap::encodeElementName (char element_type, MappedName & name, std::ostringstream & ss, ElementIDRefs * sids, long masterTag, const char * postfix = nullptr, long tag = 0, bool forceTag = false) const
Definition at line 614 of file ElementMap.cpp.
References Data::ELEMENT_MAP_PREFIX, Data::MappedName::findTagInElementName(), hasher, RobotExample::pos, Data::POSTFIX_TAG, and Dice3DS.dom3ds::tag.
Referenced by addChildElements(), and hashChildMaps().
erase() [1/2]
void Data::ElementMap::erase (const IndexedName & idx)
Remove idx and all the MappedNames associated with it.
Definition at line 792 of file ElementMap.cpp.
References Data::IndexedName::getIndex(), and Data::IndexedName::getType().
erase() [2/2]
void Data::ElementMap::erase (const MappedName & name)
Remove name from the map.
Definition at line 778 of file ElementMap.cpp.
References Data::MappedNameRef::erase().
Referenced by setElementName().
find() [1/2]
MappedName Data::ElementMap::find (const IndexedName & idx, ElementIDRefs * sids = nullptr) const
Definition at line 875 of file ElementMap.cpp.
References Data::MappedName::find(), Data::IndexedName::getIndex(), Data::IndexedName::getType(), Data::MappedNameRef::name, and Data::MappedNameRef::sids.
find() [2/2]
IndexedName Data::ElementMap::find (const MappedName & name, ElementIDRefs * sids = nullptr) const
Definition at line 819 of file ElementMap.cpp.
References DraftVecUtils::equals(), Data::MappedName::findTagInElementName(), Data::MappedName::fromRawData(), Data::IndexedName::getIndex(), Data::IndexedName::getType(), Data::MappedNameRef::name, Data::MappedNameRef::next, Data::IndexedName::setIndex(), Data::MappedNameRef::sids, Data::MappedName::toIndexedName(), and Data::MappedName::toRawBytes().
findAll()
std::vector< std::pair< MappedName, ElementIDRefs > > Data::ElementMap::findAll (const IndexedName & idx) const
Definition at line 922 of file ElementMap.cpp.
References src.Mod.AddonManager.NetworkManager::count, Data::IndexedName::getIndex(), Data::IndexedName::getType(), Data::MappedNameRef::next, and TestSpreadsheet::v.
getAll()
std::vector< MappedElement > Data::ElementMap::getAll () const
Definition at line 1298 of file ElementMap.cpp.
References Data::MappedName::find(), Data::IndexedName::getIndex(), SplineSurface::i, Data::IndexedName::setIndex(), and size().
getChildElements()
std::vector< ElementMap::MappedChildElements > Data::ElementMap::getChildElements () const
Definition at line 1288 of file ElementMap.cpp.
getElementHistory()
long Data::ElementMap::getElementHistory (const MappedName & name, long masterTag, MappedName * original = nullptr, std::vector< MappedName > * history = nullptr) const
Definition at line 1327 of file ElementMap.cpp.
References Data::MappedName::copy(), Data::ELEMENT_MAP_PREFIX, Data::ELEMENT_MAP_PREFIX_SIZE, FC_WARN, Data::MappedName::findTagInElementName(), Data::MappedName::fromRawData(), Data::MAPPED_CHILD_ELEMENTS_PREFIX, RobotExample::pos, Data::POSTFIX_TAG_SIZE, Data::MappedName::startsWith(), and Dice3DS.dom3ds::tag.
hasChildElementMap()
bool Data::ElementMap::hasChildElementMap () const
Definition at line 1009 of file ElementMap.cpp.
hashChildMaps()
void Data::ElementMap::hashChildMaps (long masterTag)
Definition at line 1014 of file ElementMap.cpp.
References encodeElementName(), Data::MappedName::findTagInElementName(), Data::MappedName::fromRawData(), Data::MAPPED_CHILD_ELEMENTS_PREFIX, RobotExample::pos, Dice3DS.dom3ds::tag, and Data::MappedName::toBytes().
restore()
ElementMapPtr Data::ElementMap::restore (::App::StringHasherRef hasherRef, std::istream & stream)
Deserialize and restore this map. This function restores childMaps and postfixes from the stream, then calls the other (private) restore function with those parameters.
Parameters
hasherRef where all the StringIDs are stored
stream stream to deserialize
Definition at line 236 of file ElementMap.cpp.
References Data::_idToElementMap, src.Mod.AddonManager.NetworkManager::count, FC_THROWM, SplineSurface::i, SplineSurface::id, and Path.Op.Surface::msg.
Referenced by src.Mod.Show.mTempoVis.TempoVis::__del__().
save()
void Data::ElementMap::save (std::ostream & stream) const
Serialize this map. Calls collectChildMaps to get childMapSet and postfixMap, then calls the other (private) save function with those parameters.
Parameters
stream serialized stream
Definition at line 215 of file ElementMap.cpp.
Referenced by src.Mod.Show.mTempoVis.TempoVis::modify(), src.Mod.Show.mTempoVis.TempoVis::modifyVPProperty(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle(), src.Mod.Show.mTempoVis.TempoVis::saveCamera(), and nativeifc.ifc_viewproviders.ifc_vp_document::setupContextMenu().
setElementName()
MappedName Data::ElementMap::setElementName (const IndexedName & element, const MappedName & name, long masterTag, const ElementIDRefs * sid = nullptr, bool overwrite = false)
Add a sub-element name mapping.
Parameters
element the original Type + Index element name
name the mapped sub-element name. May or may not start with elementMapPrefix().
sid in case you use a hasher to hash the element name, pass in the string id reference using this parameter. You can have more than one string id associated with the same name.
overwrite if true, it will overwrite existing names
Returns
Returns the stored mapped element name.
An element can have multiple mapped names. However, a name can only be mapped to one element
Note: the original proc was in the context of ComplexGeoData, which provided Tag access, now you must pass in long masterTag explicitly.
Definition at line 548 of file ElementMap.cpp.
References ArchCommands::check(), src.Mod.AddonManager.NetworkManager::count, erase(), FC_ERR, FC_THROWM, Data::IndexedName::getType(), SplineSurface::i, and Data::MappedName::size().
Referenced by addChildElements().
size()
unsigned long Data::ElementMap::size () const
Definition at line 809 of file ElementMap.cpp.
Referenced by Path.Post.Utils.GCodeEditorDialog::done(), and getAll().
traceElement()
void Data::ElementMap::traceElement (const MappedName & name, long masterTag, TraceCallback cb) const
Iterate through the history of the give element name with a given callback
Parameters
name the input element name
cb trace callback with call signature.
See also
TraceCallback
Definition at line 1386 of file ElementMap.cpp.
References KDL::abs(), toolbit-attributes::doc, Data::ELEMENT_MAP_PREFIX, Data::ELEMENT_MAP_PREFIX_SIZE, FC_ERR, FC_LOG, FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, FC_LOGLEVEL_TRACE, FC_WARN, Data::MappedName::findTagInElementName(), App::Application::getActiveDocument(), App::GetApplication(), femtools.tokrules::names, RobotExample::pos, Data::POSTFIX_EXTERNAL_TAG, and Data::MappedName::startsWith().
Member Data Documentation
hasher
App::StringHasherRef Data::ElementMap::hasher
String hasher for element name shortening.
Definition at line 345 of file ElementMap.h.
Referenced by encodeElementName().
The documentation for this class was generated from the following files:
ElementMap.h
ElementMap.cpp