FreeCAD: Gui::Dialog::DemoMode Class Reference
Gui::Dialog::DemoMode Class Reference
#include <DemoMode.h>
Public Member Functions
DemoMode (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DemoMode () override
void accept () override
void reject () override
Protected Member Functions
void setupConnections ()
void onPlayButtonToggled (bool)
void onFullscreenToggled (bool)
void onTimerCheckToggled (bool)
void onSpeedSliderValueChanged (int)
void onAngleSliderValueChanged (int)
void onTimeoutValueChanged (int)
void onAutoPlay ()
Detailed Description
Definition at line 44 of file DemoMode.h.
Constructor & Destructor Documentation
DemoMode()
DemoMode::DemoMode (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Definition at line 45 of file DemoMode.cpp.
References draftgeoutils.intersections::connect(), ArchFence::hide(), onAutoPlay(), and setupConnections().
~DemoMode()
DemoMode::~DemoMode () override
Destroys the object and frees any allocated resources
Definition at line 67 of file DemoMode.cpp.
Member Function Documentation
accept()
void DemoMode::accept () override
Definition at line 102 of file DemoMode.cpp.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
onAngleSliderValueChanged()
void DemoMode::onAngleSliderValueChanged (int v) protected
Definition at line 180 of file DemoMode.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), Gui::View3DInventor::getViewer(), Gui::View3DInventorViewer::isSpinning(), and TestSpreadsheet::v.
Referenced by setupConnections().
onAutoPlay()
void DemoMode::onAutoPlay () protected
Definition at line 273 of file DemoMode.cpp.
References Gui::View3DInventor::getViewer(), and Gui::View3DInventorViewer::isSpinning().
Referenced by DemoMode().
onFullscreenToggled()
void DemoMode::onFullscreenToggled (bool on) protected
Definition at line 246 of file DemoMode.cpp.
References Gui::MDIView::Child, Gui::Application::commandManager(), Gui::MDIView::FullScreen, Gui::CommandManager::getCommandByName(), Gui::Application::Instance, and Gui::Command::invoke().
Referenced by setupConnections().
onPlayButtonToggled()
void DemoMode::onPlayButtonToggled (bool pressed) protected
Definition at line 222 of file DemoMode.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), Gui::View3DInventor::getViewer(), Gui::View3DInventorViewer::isSpinning(), Gui::View3DInventorViewer::stopAnimating(), and SurfaceTests.TestBlendCurve::vec.
Referenced by setupConnections().
onSpeedSliderValueChanged()
void DemoMode::onSpeedSliderValueChanged (int v) protected
Definition at line 213 of file DemoMode.cpp.
References Gui::View3DInventor::getViewer(), Gui::View3DInventorViewer::isSpinning(), and TestSpreadsheet::v.
Referenced by setupConnections().
onTimeoutValueChanged()
void DemoMode::onTimeoutValueChanged (int v) protected
Definition at line 268 of file DemoMode.cpp.
References TestSpreadsheet::v.
Referenced by setupConnections().
onTimerCheckToggled()
void DemoMode::onTimerCheckToggled (bool on) protected
Definition at line 288 of file DemoMode.cpp.
Referenced by setupConnections().
reject()
void DemoMode::reject () override
Definition at line 108 of file DemoMode.cpp.
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
setupConnections()
void DemoMode::setupConnections () protected
Definition at line 72 of file DemoMode.cpp.
References draftgeoutils.intersections::connect(), onAngleSliderValueChanged(), onFullscreenToggled(), onPlayButtonToggled(), onSpeedSliderValueChanged(), onTimeoutValueChanged(), and onTimerCheckToggled().
Referenced by DemoMode().
The documentation for this class was generated from the following files:
DemoMode.h
DemoMode.cpp