FreeCAD: Gui::Translator Class Reference
Gui::Translator Class Reference
#include <Translator.h>
singleton stuff
static Translator * instance ()
Creates an instance.
static void destruct ()
Destroys the instance.
void activateLanguage (const char *lang)
void refresh ()
std::string activeLanguage () const
std::string locale (const std::string &) const
void setLocale (const std::string &="") const
TStringList supportedLanguages () const
TStringMap supportedLocales () const
void addPath (const QString &path)
bool eventFilter (QObject *obj, QEvent *ev) override
void enableDecimalPointConversion (bool on)
bool isEnabledDecimalPointConversion () const
Detailed Description
Definition at line 50 of file Translator.h.
Member Function Documentation
activateLanguage()
void Translator::activateLanguage (const char * lang)
Activates the specified language lang if available.
Definition at line 238 of file Translator.cpp.
References Gui::TranslatorP::activatedLanguage, DraftVecUtils::find(), refresh(), and supportedLanguages().
Referenced by Std_TestQM::activated(), Std_TestReloadQM::activated(), Gui::Application::Application(), and Gui::ApplicationPy::sSetLocale().
activeLanguage()
std::string Translator::activeLanguage () const
Returns the currently installed language. If no language is installed an empty string is returned.
Definition at line 248 of file Translator.cpp.
References Gui::TranslatorP::activatedLanguage.
Referenced by Gui::Dialog::DlgSettingsGeneral::loadSettings(), and Gui::ApplicationPy::sGetLocale().
addPath()
void Translator::addPath (const QString & path)
Adds a path where localization files can be found
Definition at line 305 of file Translator.cpp.
References Gui::TranslatorP::paths.
Referenced by Gui::ApplicationPy::sAddLangPath(), and Gui::ApplicationPy::sAddResPath().
destruct()
void Translator::destruct () static
Destroys the instance.
Definition at line 125 of file Translator.cpp.
Referenced by Gui::Application::~Application().
enableDecimalPointConversion()
void Translator::enableDecimalPointConversion (bool on)
Enables/disables decimal separator conversion
Definition at line 398 of file Translator.cpp.
References Base::Console(), Base::ConsoleSingleton::Instance(), and Base::ConsoleSingleton::Warning().
eventFilter()
bool Translator::eventFilter (QObject * obj, QEvent * ev) override
eventFilter used to convert decimal separator
Definition at line 368 of file Translator.cpp.
References mod.
instance()
Translator * Translator::instance () static
Creates an instance.
Definition at line 118 of file Translator.cpp.
Referenced by Std_TestQM::activated(), Std_TestReloadQM::activated(), Gui::Application::Application(), loadDrawingResource(), loadFemResource(), loadMaterialResource(), loadMeshPartResource(), loadMeshResource(), loadPartDesignResource(), loadPartResource(), loadPathResource(), loadPointsResource(), loadReverseEngineeringResource(), loadRobotResource(), Gui::Dialog::DlgSettingsGeneral::loadSettings(), loadSketcherResource(), loadSpreadsheetResource(), loadStartResource(), loadTechDrawResource(), loadTestResource(), Gui::ApplicationPy::sAddLangPath(), Gui::ApplicationPy::sAddResPath(), Gui::ApplicationPy::sGetLocale(), Gui::ApplicationPy::sSetLocale(), Gui::ApplicationPy::sSupportedLocales(), and Gui::ApplicationPy::sUpdateLocale().
isEnabledDecimalPointConversion()
bool Translator::isEnabledDecimalPointConversion () const
Returns whether decimal separator conversion is enabled
Definition at line 423 of file Translator.cpp.
locale()
std::string Translator::locale (const std::string & lang) const
Returns the locale (e.g. "de") to the given language name.
Definition at line 253 of file Translator.cpp.
References Gui::TranslatorP::mapLanguageTopLevelDomain.
Referenced by setLocale().
refresh()
void Translator::refresh ()
This method checks for newly added (internal) .qm files which might be added at runtime. This e.g. happens if a plugin gets loaded at runtime. For each newly added files that supports the currently set language a new translator object is created to load the file.
Definition at line 344 of file Translator.cpp.
References Gui::TranslatorP::activatedLanguage, Gui::TranslatorP::mapLanguageTopLevelDomain, and Gui::TranslatorP::paths.
Referenced by Path.Tool.Gui.BitEdit.ToolBitEditor::accept(), activateLanguage(), loadDrawingResource(), loadFemResource(), loadMaterialResource(), loadMeshPartResource(), loadMeshResource(), loadPartDesignResource(), loadPartResource(), loadPathResource(), loadPointsResource(), loadReverseEngineeringResource(), loadRobotResource(), loadSketcherResource(), loadSpreadsheetResource(), loadStartResource(), loadTechDrawResource(), loadTestResource(), Path.Tool.Gui.Controller.ToolControllerEditor::setupUi(), Path.Tool.Gui.BitEdit.ToolBitEditor::setupUI(), and Gui::ApplicationPy::sUpdateLocale().
setLocale()
void Translator::setLocale (const std::string & language = "") const
Sets default Qt locale based on given language name
Definition at line 263 of file Translator.cpp.
References SCL.SimpleDataTypes::c, Base::Console(), locale(), and Base::ConsoleSingleton::Log().
supportedLanguages()
TStringList Translator::supportedLanguages () const
Returns a list of supported languages.
Definition at line 207 of file Translator.cpp.
References supportedLocales().
Referenced by activateLanguage().
supportedLocales()
TStringMap Translator::supportedLocales () const
Returns a map of supported languages/locales.
Definition at line 217 of file Translator.cpp.
References Gui::TranslatorP::mapLanguageTopLevelDomain, Gui::TranslatorP::mapSupportedLocales, and Gui::TranslatorP::paths.
Referenced by Gui::Dialog::DlgSettingsGeneral::loadSettings(), Gui::ApplicationPy::sSetLocale(), Gui::ApplicationPy::sSupportedLocales(), and supportedLanguages().
The documentation for this class was generated from the following files:
Translator.h
Translator.cpp