FreeCAD: Base::BoundBox2d Class Reference
Base::BoundBox2d Class Reference
#include <Tools2D.h>
Public Member Functions
BoundBox2d ()
BoundBox2d (const BoundBox2d &)=default
BoundBox2d (BoundBox2d &&)=default
BoundBox2d (double fX1, double fY1, double fX2, double fY2)
~BoundBox2d ()=default
bool IsValid () const
bool IsEqual (const BoundBox2d &bbox, double tolerance) const
BoundBox2d & operator= (const BoundBox2d &)=default
BoundBox2d & operator= (BoundBox2d &&)=default
bool operator== (const BoundBox2d &bbox) const
double Width () const
double Height () const
bool Contains (const Vector2d &v) const
bool Contains (const Vector2d &v, double tolerance) const
Vector2d GetCenter () const
void SetVoid ()
void Add (const Vector2d &v)
bool Intersect (const Line2d &rclLine) const
bool Intersect (const BoundBox2d &rclBB) const
bool Intersect (const Polygon2d &rclPoly) const
Public Attributes
double MinX
double MinY
double MaxX
double MaxY
Detailed Description
BoundBox2d Two dimensional bounding box.
Definition at line 125 of file Tools2D.h.
Constructor & Destructor Documentation
BoundBox2d() [1/4]
Base::BoundBox2d::BoundBox2d () inline
Definition at line 476 of file Tools2D.h.
BoundBox2d() [2/4]
Base::BoundBox2d::BoundBox2d (const BoundBox2d &) inline default
BoundBox2d() [3/4]
Base::BoundBox2d::BoundBox2d (BoundBox2d &&) inline default
BoundBox2d() [4/4]
Base::BoundBox2d::BoundBox2d (double fX1, double fY1, double fX2, double fY2) inline
Definition at line 482 of file Tools2D.h.
~BoundBox2d()
Base::BoundBox2d::~BoundBox2d () default
Member Function Documentation
Add()
void Base::BoundBox2d::Add (const Vector2d & v) inline
Definition at line 540 of file Tools2D.h.
Referenced by Reen::ParameterCorrection::GetUVParameters().
Contains() [1/2]
bool Base::BoundBox2d::Contains (const Vector2d & v) const inline
Definition at line 518 of file Tools2D.h.
Referenced by Base::Polygon2d::At(), MeshCore::MeshAlgorithm::CheckFacets(), Intersect(), and TechDraw::DrawUtil::mergeBoundedPoint().
Contains() [2/2]
bool Base::BoundBox2d::Contains (const Vector2d & v, double tolerance) const inline
Definition at line 523 of file Tools2D.h.
GetCenter()
Vector2d Base::BoundBox2d::GetCenter () const inline
Definition at line 529 of file Tools2D.h.
Referenced by TechDrawGui::QGIViewDimension::constructDimensionArc(), TechDrawGui::QGIViewDimension::constructDimensionLine(), TechDrawGui::QGIViewDimension::drawAngle(), TechDrawGui::QGIViewDimension::drawAreaExecutive(), TechDrawGui::QGIViewDimension::drawDiameter(), TechDrawGui::QGIViewDimension::drawDistanceExecutive(), TechDrawGui::QGIViewDimension::drawDistanceOverride(), TechDrawGui::QGIViewDimension::drawRadiusExecutive(), TechDrawGui::QGIViewDimension::getAsmeRefJointPoint(), TechDrawGui::QGIViewDimension::getAsmeRefOutsetPoint(), and getBoxSelection().
Height()
double Base::BoundBox2d::Height () const inline
Definition at line 513 of file Tools2D.h.
References DOUBLE_MAX, MaxX, MaxY, MinX, and MinY.
Referenced by TechDrawGui::QGIViewDimension::drawAngle(), TechDrawGui::QGIViewDimension::drawAreaExecutive(), TechDrawGui::QGIViewDimension::drawDiameter(), TechDrawGui::QGIViewDimension::drawDistanceExecutive(), TechDrawGui::QGIViewDimension::drawDistanceOverride(), and TechDrawGui::QGIViewDimension::drawRadiusExecutive().
Intersect() [1/3]
bool BoundBox2d::Intersect (const BoundBox2d & rclBB) const
Definition at line 109 of file Tools2D.cpp.
References MaxX, MaxY, MinX, and MinY.
Intersect() [2/3]
bool BoundBox2d::Intersect (const Line2d & rclLine) const
BOUNDBOX2d
Definition at line 72 of file Tools2D.cpp.
References Base::Line2d::clV1, Base::Line2d::clV2, Base::Line2d::IntersectAndContain(), MaxX, MaxY, MinX, MinY, Base::Vector2d::x, and Base::Vector2d::y.
Referenced by MeshCore::MeshTrimming::CheckFacets(), MeshCore::MeshAlgorithm::CheckFacets(), and Intersect().
Intersect() [3/3]
bool BoundBox2d::Intersect (const Polygon2d & rclPoly) const
Definition at line 114 of file Tools2D.cpp.
References Base::Line2d::clV1, Base::Line2d::clV2, Contains(), Base::Polygon2d::Contains(), Base::Polygon2d::GetCtVectors(), SplineSurface::i, Intersect(), MaxX, MaxY, MinX, and MinY.
IsEqual()
bool Base::BoundBox2d::IsEqual (const BoundBox2d & bbox, double tolerance) const inline
Definition at line 494 of file Tools2D.h.
References MaxY, and MinY.
IsValid()
bool Base::BoundBox2d::IsValid () const inline
Definition at line 489 of file Tools2D.h.
References MaxX, and MinX.
operator=() [1/2]
BoundBox2d& Base::BoundBox2d::operator= (BoundBox2d &&) inline default
operator=() [2/2]
BoundBox2d& Base::BoundBox2d::operator= (const BoundBox2d &) inline default
operator==()
bool Base::BoundBox2d::operator== (const BoundBox2d & bbox) const inline
Definition at line 500 of file Tools2D.h.
SetVoid()
void Base::BoundBox2d::SetVoid () inline
Definition at line 534 of file Tools2D.h.
Width()
double Base::BoundBox2d::Width () const inline
Definition at line 508 of file Tools2D.h.
References MaxX, MaxY, MinX, and MinY.
Referenced by TechDrawGui::QGIViewDimension::constructDimensionArc(), and TechDrawGui::QGIViewDimension::constructDimensionLine().
Member Data Documentation
MaxX
double Base::BoundBox2d::MaxX
Definition at line 128 of file Tools2D.h.
Referenced by Base::Line2d::CalcBoundBox(), Base::Polygon2d::CalcBoundBox(), TechDrawGui::QGIViewDimension::getAsmeRefJointPoint(), TechDrawGui::QGIViewDimension::getAsmeRefOutsetPoint(), TechDrawGui::QGIViewDimension::getIsoRefOutsetPoint(), Reen::ParameterCorrection::GetUVParameters(), Height(), Base::BoundBox3< double >::Intersect(), Intersect(), IsValid(), Base::Line2d::Line2d(), SketcherGui::EditModeCoinManager::updateAxesLength(), PartGui::ViewProvider2DObjectGrid::updateData(), and Width().
MaxY
double Base::BoundBox2d::MaxY
Definition at line 128 of file Tools2D.h.
Referenced by Base::Line2d::CalcBoundBox(), Base::Polygon2d::CalcBoundBox(), Reen::ParameterCorrection::GetUVParameters(), Height(), Base::BoundBox3< double >::Intersect(), Intersect(), IsEqual(), Base::Line2d::Line2d(), SketcherGui::EditModeCoinManager::updateAxesLength(), PartGui::ViewProvider2DObjectGrid::updateData(), and Width().
MinX
double Base::BoundBox2d::MinX
Definition at line 128 of file Tools2D.h.
Referenced by Base::Line2d::CalcBoundBox(), Base::Polygon2d::CalcBoundBox(), TechDrawGui::QGIViewDimension::getAsmeRefJointPoint(), TechDrawGui::QGIViewDimension::getAsmeRefOutsetPoint(), TechDrawGui::QGIViewDimension::getIsoRefOutsetPoint(), Reen::ParameterCorrection::GetUVParameters(), Height(), Base::BoundBox3< double >::Intersect(), Intersect(), IsValid(), Base::Line2d::Line2d(), SketcherGui::EditModeCoinManager::updateAxesLength(), PartGui::ViewProvider2DObjectGrid::updateData(), and Width().
MinY
double Base::BoundBox2d::MinY
Definition at line 128 of file Tools2D.h.
Referenced by Base::Line2d::CalcBoundBox(), Base::Polygon2d::CalcBoundBox(), TechDrawGui::QGIViewDimension::getIsoRefOutsetPoint(), Reen::ParameterCorrection::GetUVParameters(), Height(), Base::BoundBox3< double >::Intersect(), Intersect(), IsEqual(), Base::Line2d::Line2d(), SketcherGui::EditModeCoinManager::updateAxesLength(), PartGui::ViewProvider2DObjectGrid::updateData(), and Width().
The documentation for this class was generated from the following files:
Tools2D.h
Tools2D.cpp