FreeCAD: ifc2x3.ifcrelconnectspathelements Class Reference
ifc2x3.ifcrelconnectspathelements Class Reference
Public Member Functions
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__connectiongeometry, inherited5__relatingelement, inherited6__relatedelement, relatingpriorities, relatedpriorities, relatedconnectiontype, relatingconnectiontype)
def relatingpriorities ()
def relatedpriorities ()
def relatedconnectiontype ()
def relatingconnectiontype ()
Public Member Functions inherited from ifc2x3.ifcrelconnectselements
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, connectiongeometry, relatingelement, relatedelement)
def connectiongeometry ()
def relatingelement ()
def relatedelement ()
def wr31 (self)
Public Member Functions inherited from ifc2x3.ifcrelconnects
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description)
Public Member Functions inherited from ifc2x3.ifcroot
def globalid ()
def ownerhistory ()
def name ()
def description ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
relatingpriorities
relatedpriorities
relatedconnectiontype
relatingconnectiontype
Public Attributes inherited from ifc2x3.ifcrelconnectselements
connectiongeometry
relatingelement
relatedelement
Public Attributes inherited from ifc2x3.ifcroot
globalid
ownerhistory
name
description
Detailed Description
Entity ifcrelconnectspathelements definition.
:param relatingpriorities
:type relatingpriorities:LIST(0,None,'INTEGER', scope = schema_scope)
:param relatedpriorities
:type relatedpriorities:LIST(0,None,'INTEGER', scope = schema_scope)
:param relatedconnectiontype
:type relatedconnectiontype:ifcconnectiontypeenum
:param relatingconnectiontype
:type relatingconnectiontype:ifcconnectiontypeenum
Definition at line 29138 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcrelconnectspathelements.__init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__connectiongeometry, inherited5__relatingelement, inherited6__relatedelement, relatingpriorities, relatedpriorities, relatedconnectiontype, relatingconnectiontype)
Definition at line 29153 of file ifc2x3.py.
Member Function Documentation
relatedconnectiontype()
def ifc2x3.ifcrelconnectspathelements.relatedconnectiontype ()
Definition at line 29189 of file ifc2x3.py.
References ifc2x3.ifcrelconnectspathelements._relatedconnectiontype, SCL.TypeChecker.check_type(), and ifc2x3.ifcrelconnectspathelements.relatedconnectiontype.
relatedpriorities()
def ifc2x3.ifcrelconnectspathelements.relatedpriorities ()
Definition at line 29175 of file ifc2x3.py.
References ifc2x3.ifcrelconnectspathelements._relatedpriorities, SCL.TypeChecker.check_type(), and ifc2x3.ifcrelconnectspathelements.relatedpriorities.
relatingconnectiontype()
def ifc2x3.ifcrelconnectspathelements.relatingconnectiontype ()
Definition at line 29203 of file ifc2x3.py.
References ifc2x3.ifcrelconnectspathelements._relatingconnectiontype, SCL.TypeChecker.check_type(), and ifc2x3.ifcrelconnectspathelements.relatingconnectiontype.
relatingpriorities()
def ifc2x3.ifcrelconnectspathelements.relatingpriorities ()
Definition at line 29161 of file ifc2x3.py.
References ifc2x3.ifcrelconnectspathelements._relatingpriorities, SCL.TypeChecker.check_type(), and ifc2x3.ifcrelconnectspathelements.relatingpriorities.
Member Data Documentation
relatedconnectiontype
ifc2x3.ifcrelconnectspathelements.relatedconnectiontype
Definition at line 29157 of file ifc2x3.py.
Referenced by ifc2x3.ifcrelconnectspathelements.relatedconnectiontype().
relatedpriorities
ifc2x3.ifcrelconnectspathelements.relatedpriorities
Definition at line 29156 of file ifc2x3.py.
Referenced by ifc4.ifcrelconnectspathelements.normalizedrelatedpriorities(), and ifc2x3.ifcrelconnectspathelements.relatedpriorities().
relatingconnectiontype
ifc2x3.ifcrelconnectspathelements.relatingconnectiontype
Definition at line 29158 of file ifc2x3.py.
Referenced by ifc2x3.ifcrelconnectspathelements.relatingconnectiontype().
relatingpriorities
ifc2x3.ifcrelconnectspathelements.relatingpriorities
Definition at line 29155 of file ifc2x3.py.
Referenced by ifc4.ifcrelconnectspathelements.normalizedrelatingpriorities(), and ifc2x3.ifcrelconnectspathelements.relatingpriorities().
The documentation for this class was generated from the following file:
ifc2x3.py