FreeCAD: Cloud::CloudWriter Class Reference
Cloud::CloudWriter Class Reference
#include <AppCloud.h>
Public Member Functions
CloudWriter (const char *URL, const char *TokenAuth, const char *TokenSecret, const char *TCPPort, const char *Bucket, std::string ProtocolVersion, std::string Region)
virtual ~CloudWriter ()
void pushCloud (const char *FileName, const char *data, long size)
void putNextEntry (const char *file)
void createBucket ()
virtual void writeFiles (void)
process the requested file storing
virtual std::ostream & Stream (void)
virtual bool shouldWrite (const std::string &name, const Base::Persistence *Object) const
void checkText (XERCES_CPP_NAMESPACE_QUALIFIER DOMText *text)
void checkXML (XERCES_CPP_NAMESPACE_QUALIFIER DOMNode *node)
void checkElement (XERCES_CPP_NAMESPACE_QUALIFIER DOMElement *element)
Public Member Functions inherited from Base::Writer
Writer ()
virtual ~Writer ()
void setForceXML (bool on)
switch the writer in XML only mode (no files allowed)
bool isForceXML () const
check on state
void setFileVersion (int)
int getFileVersion () const
virtual void putNextEntry (const char *filename, const char *objName=nullptr)
put the next entry with a give name
void insertAsciiFile (const char *FileName)
insert a file as CDATA section in the XML file
void insertBinFile (const char *FileName)
insert a binary file BASE64 coded as CDATA section in the XML file
void insertText (const std::string &str)
insert text string as CDATA
std::string addFile (const char *Name, const Base::Persistence *Object)
add a write request of a persistent object
const std::vector< std::string > & getFilenames () const
get all registered file names
void setMode (const std::string &mode)
Set mode.
void setModes (const std::set< std::string > &modes)
Set modes.
bool getMode (const std::string &mode) const
Get mode.
std::set< std::string > getModes () const
Get modes.
void clearMode (const std::string &mode)
Clear mode.
void clearModes ()
Clear modes.
void addError (const std::string &)
bool hasErrors () const
void clearErrors ()
std::vector< std::string > getErrors () const
const char * ind () const
get the current indentation
void incInd ()
increase indentation by one tab
void decInd ()
decrease indentation by one tab
std::ostream & beginCharStream (CharStreamFormat format=CharStreamFormat::Raw)
std::ostream & endCharStream ()
std::ostream & charStream ()
Return the current character output stream.
Writer (const Writer &)=delete
Writer (Writer &&)=delete
Writer & operator= (const Writer &)=delete
Writer & operator= (Writer &&)=delete
Public Attributes
int print = 0
char errorCode [1024] = ""
Public Attributes inherited from Base::Writer
std::string ObjectName
name for underlying file saves
Protected Attributes
std::string FileName
const char * URL
const char * TCPPort
const char * TokenAuth
const char * TokenSecret
const char * Bucket
std::string ProtocolVersion
std::string Region
std::stringstream FileStream
Protected Attributes inherited from Base::Writer
std::vector< FileEntry > FileList
std::vector< std::string > FileNames
std::vector< std::string > Errors
std::set< std::string > Modes
short indent {0}
char indBuf [1024] {}
bool forceXML {false}
int fileVersion {1}
Additional Inherited Members
Protected Member Functions inherited from Base::Writer
std::string getUniqueFileName (const char *Name)
Detailed Description
Definition at line 207 of file AppCloud.h.
Constructor & Destructor Documentation
CloudWriter()
Cloud::CloudWriter::CloudWriter (const char * URL, const char * TokenAuth, const char * TokenSecret, const char * TCPPort, const char * Bucket, std::string ProtocolVersion, std::string Region)
Definition at line 728 of file AppCloud.cpp.
References Cloud::BuildHeaderAmzS3v2(), Cloud::BuildHeaderAmzS3v4(), Cloud::ComputeDigestAmzS3v2(), Cloud::ComputeDigestAmzS3v4(), Cloud::CurlWrite_CallbackFunc_StdString(), Cloud::eraseSubStr(), getIfcElements::parser, Cloud::AmzDatav4::Region, toolbit-attributes::s, and bimcommands.BimTutorial::URL.
~CloudWriter()
Cloud::CloudWriter::~CloudWriter () virtual
Definition at line 855 of file AppCloud.cpp.
Member Function Documentation
checkElement()
void Cloud::CloudWriter::checkElement (XERCES_CPP_NAMESPACE_QUALIFIER DOMElement * element)
Definition at line 239 of file AppCloud.cpp.
checkText()
void Cloud::CloudWriter::checkText (XERCES_CPP_NAMESPACE_QUALIFIER DOMText * text)
Definition at line 248 of file AppCloud.cpp.
References Materials::trim().
checkXML()
void Cloud::CloudWriter::checkXML (XERCES_CPP_NAMESPACE_QUALIFIER DOMNode * node)
Definition at line 217 of file AppCloud.cpp.
createBucket()
void Cloud::CloudWriter::createBucket ()
Definition at line 264 of file AppCloud.cpp.
References Cloud::BuildHeaderAmzS3v2(), Cloud::BuildHeaderAmzS3v4(), Cloud::ComputeDigestAmzS3v2(), Cloud::ComputeDigestAmzS3v4(), Cloud::eraseSubStr(), src.Mod.Test.testPathArray::path, data_buffer::ptr, read_callback(), data_buffer::remaining_size, and bimcommands.BimTutorial::URL.
pushCloud()
void Cloud::CloudWriter::pushCloud (const char * FileName, const char * data, long size)
Definition at line 1228 of file AppCloud.cpp.
References Cloud::BuildHeaderAmzS3v2(), Cloud::BuildHeaderAmzS3v4(), Cloud::ComputeDigestAmzS3v2(), Cloud::ComputeDigestAmzS3v4(), Cloud::eraseSubStr(), src.Mod.Test.testPathArray::path, data_buffer::ptr, read_callback(), data_buffer::remaining_size, and bimcommands.BimTutorial::URL.
putNextEntry()
void Cloud::CloudWriter::putNextEntry (const char * file)
Definition at line 1213 of file AppCloud.cpp.
References DrawingExample::file, Cloud::CloudReader::FileEntry::FileName, and Cloud::CloudReader::FileEntry::FileStream.
Referenced by Cloud::Module::cloudSave().
shouldWrite()
bool Cloud::CloudWriter::shouldWrite (const std::string & name, const Base::Persistence * Object) const virtual
Definition at line 1223 of file AppCloud.cpp.
Stream()
virtual std::ostream& Cloud::CloudWriter::Stream (void) inline virtual
Implements Base::Writer.
Definition at line 225 of file AppCloud.h.
Referenced by Cloud::Module::cloudSave().
writeFiles()
void Cloud::CloudWriter::writeFiles (void) virtual
process the requested file storing
Implements Base::Writer.
Definition at line 1315 of file AppCloud.cpp.
References Base::Writer::FileEntry::FileName, Base::Writer::FileEntry::Object, and Base::Persistence::SaveDocFile().
Referenced by Cloud::Module::cloudSave().
Member Data Documentation
Bucket
const char* Cloud::CloudWriter::Bucket protected
Definition at line 240 of file AppCloud.h.
errorCode
char Cloud::CloudWriter::errorCode[1024] = ""
Definition at line 211 of file AppCloud.h.
FileName
std::string Cloud::CloudWriter::FileName protected
Definition at line 235 of file AppCloud.h.
FileStream
std::stringstream Cloud::CloudWriter::FileStream protected
Definition at line 243 of file AppCloud.h.
print
int Cloud::CloudWriter::print = 0
Definition at line 210 of file AppCloud.h.
ProtocolVersion
std::string Cloud::CloudWriter::ProtocolVersion protected
Definition at line 241 of file AppCloud.h.
Region
std::string Cloud::CloudWriter::Region protected
Definition at line 242 of file AppCloud.h.
TCPPort
const char* Cloud::CloudWriter::TCPPort protected
Definition at line 237 of file AppCloud.h.
TokenAuth
const char* Cloud::CloudWriter::TokenAuth protected
Definition at line 238 of file AppCloud.h.
TokenSecret
const char* Cloud::CloudWriter::TokenSecret protected
Definition at line 239 of file AppCloud.h.
URL
const char* Cloud::CloudWriter::URL protected
Definition at line 236 of file AppCloud.h.
The documentation for this class was generated from the following files:
AppCloud.h
AppCloud.cpp