FreeCAD: femsolver.calculix.solver.Proxy Class Reference
femsolver.calculix.solver.Proxy Class Reference
Public Member Functions
def __init__ (self, obj)
def onDocumentRestored (self, obj)
def createMachine (self, obj, directory, testmode=False)
def editSupported (self)
def edit (self, directory)
def execute (self, obj)
Public Member Functions inherited from femsolver.solverbase.Proxy
def createEquation (self, obj, eqId)
def isSupported (self, equation)
def addEquation (self, obj, eqId)
Public Member Functions inherited from femsolver.calculix.solver._BaseSolverCalculix
def on_restore_of_document (self, obj)
def add_attributes (self, obj)
Static Public Attributes
Type
Static Public Attributes inherited from femsolver.solverbase.Proxy
BaseType
Detailed Description
The Fem::FemSolver's Proxy python type, add solver specific properties
Definition at line 329 of file calculix/solver.py.
Constructor & Destructor Documentation
__init__()
def femsolver.calculix.solver.Proxy.__init__ (self, obj)
Reimplemented from femsolver.solverbase.Proxy.
Definition at line 334 of file calculix/solver.py.
References femsolver.calculix.solver._BaseSolverCalculix.add_attributes().
Member Function Documentation
createMachine()
def femsolver.calculix.solver.Proxy.createMachine (self, obj, directory, testmode = False)
Reimplemented from femsolver.solverbase.Proxy.
Definition at line 342 of file calculix/solver.py.
edit()
def femsolver.calculix.solver.Proxy.edit (self, directory)
Reimplemented from femsolver.solverbase.Proxy.
Definition at line 356 of file calculix/solver.py.
editSupported()
def femsolver.calculix.solver.Proxy.editSupported (self)
Reimplemented from femsolver.solverbase.Proxy.
Definition at line 353 of file calculix/solver.py.
execute()
def femsolver.calculix.solver.Proxy.execute (self, obj)
Reimplemented from femsolver.solverbase.Proxy.
Definition at line 362 of file calculix/solver.py.
Referenced by src.Mod.PartDesign.Scripts.Spring.MySpring.onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped.onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder.onChanged(), MeasureCOM.MeasureCOM.onChanged(), and FeaturePython.DistanceBolt.onChanged().
onDocumentRestored()
def femsolver.calculix.solver.Proxy.onDocumentRestored (self, obj)
Definition at line 339 of file calculix/solver.py.
References femsolver.calculix.solver._BaseSolverCalculix.on_restore_of_document().
Member Data Documentation
Type
femsolver.calculix.solver.Proxy.Type static
Definition at line 332 of file calculix/solver.py.
The documentation for this class was generated from the following file:
calculix/solver.py