FreeCAD: App::VariableExpression Class Reference
App::VariableExpression Class Reference
#include <ExpressionParser.h>
Public Member Functions
VariableExpression (const App::DocumentObject *_owner=nullptr, const ObjectIdentifier &_var=ObjectIdentifier())
~VariableExpression () override
bool isTouched () const override
Expression * simplify () const override
std::string name () const
ObjectIdentifier getPath () const
void setPath (const ObjectIdentifier &path)
const App::Property * getProperty () const
void addComponent (Component *component) override
Public Member Functions inherited from App::UnitExpression
UnitExpression (const App::DocumentObject *_owner=nullptr, const Base::Quantity &_quantity=Base::Quantity(), const std::string &_unitStr=std::string())
~UnitExpression () override
void setUnit (const Base::Quantity &_quantity)
void setQuantity (const Base::Quantity &_quantity)
double getValue () const
const Base::Unit & getUnit () const
const Base::Quantity & getQuantity () const
const std::string getUnitString () const
double getScaler () const
Public Member Functions inherited from App::Expression
Expression (const App::DocumentObject *_owner)
~Expression () override
Expression * eval () const
std::string toString (bool persistent=false, bool checkPriority=false, int indent=0) const
void toString (std::ostream &os, bool persistent=false, bool checkPriority=false, int indent=0) const
Expression * copy () const
virtual int priority () const
void getIdentifiers (std::map< App::ObjectIdentifier, bool > &) const
std::map< App::ObjectIdentifier, bool > getIdentifiers () const
void getDeps (ExpressionDeps &deps, int option=DepNormal) const
ExpressionDeps getDeps (int option=DepNormal) const
std::map< App::DocumentObject *, bool > getDepObjects (std::vector< std::string > *labels=nullptr) const
void getDepObjects (std::map< App::DocumentObject *, bool > &, std::vector< std::string > *labels=nullptr) const
ExpressionPtr importSubNames (const std::map< std::string, std::string > &nameMap) const
ExpressionPtr updateLabelReference (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const
ExpressionPtr replaceObject (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const
bool adjustLinks (const std::set< App::DocumentObject * > &inList)
void visit (ExpressionVisitor &v)
App::DocumentObject * getOwner () const
bool hasComponent () const
boost::any getValueAsAny () const
Py::Object getPyValue () const
bool isSame (const Expression &other, bool checkComment=true) const
Component (const std::string &n)
Component (Expression *e1, Expression *e2, Expression *e3, bool isRange=false)
Component (const ObjectIdentifier::Component &comp)
Component (const Component &other)
~Component ()
Component & operator= (const Component &)=delete
void visit (ExpressionVisitor &v)
bool isTouched () const
void toString (std::ostream &ss, bool persistent) const
Component * copy () const
Component * eval () const
Py::Object get (const Expression *owner, const Py::Object &pyobj) const
void set (const Expression *owner, Py::Object &pyobj, const Py::Object &value) const
void del (const Expression *owner, Py::Object &pyobj) const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
Expression * _copy () const override
Py::Object _getPyValue () const override
void _toString (std::ostream &ss, bool persistent, int indent) const override
bool _isIndexable () const override
void _getIdentifiers (std::map< App::ObjectIdentifier, bool > &) const override
bool _adjustLinks (const std::set< App::DocumentObject * > &, ExpressionVisitor &) override
void _importSubNames (const ObjectIdentifier::SubNameMap &) override
void _updateLabelReference (App::DocumentObject *, const std::string &, const char *) override
bool _updateElementReference (App::DocumentObject *, bool, ExpressionVisitor &) override
bool _relabeledDocument (const std::string &, const std::string &, ExpressionVisitor &) override
bool _renameObjectIdentifier (const std::map< ObjectIdentifier, ObjectIdentifier > &, const ObjectIdentifier &, ExpressionVisitor &) override
void _collectReplacement (std::map< ObjectIdentifier, ObjectIdentifier > &, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const override
void _moveCells (const CellAddress &, int, int, ExpressionVisitor &) override
void _offsetCells (int, int, ExpressionVisitor &) override
Protected Member Functions inherited from App::Expression
virtual void _visit (ExpressionVisitor &)
Protected Attributes
ObjectIdentifier var
Protected Attributes inherited from App::UnitExpression
PyObject * cache = nullptr
Protected Attributes inherited from App::Expression
App::DocumentObject * owner
ComponentList components
Additional Inherited Members
Public Types inherited from App::Expression
enum DepOption { DepNormal, DepHidden, DepAll }
using ComponentList = std::vector< Component * >
Static Public Member Functions inherited from App::Expression
static Expression * parse (const App::DocumentObject *owner, const std::string &buffer)
static Component * createComponent (const std::string &n)
static Component * createComponent (Expression *e1, Expression *e2=nullptr, Expression *e3=nullptr, bool isRange=false)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::Expression
std::string comment
ObjectIdentifier::Component comp
Expression * e1
Expression * e2
Expression * e3
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Class implementing a reference to a property. If the name is unqualified, the owner of the expression is searched. If it is qualified, the document that contains the owning document object is searched for other document objects to search. Both labels and internal document names are searched.
Definition at line 462 of file ExpressionParser.h.
Constructor & Destructor Documentation
VariableExpression()
VariableExpression::VariableExpression (const App::DocumentObject * _owner = nullptr, const ObjectIdentifier & _var = ObjectIdentifier()) explicit
Definition at line 2832 of file Expression.cpp.
Referenced by _copy().
~VariableExpression()
VariableExpression::~VariableExpression () override default
Member Function Documentation
_adjustLinks()
bool VariableExpression::_adjustLinks (const std::set< App::DocumentObject * > & inList, ExpressionVisitor & v) override protected virtual
Reimplemented from App::Expression.
Definition at line 2970 of file Expression.cpp.
References App::ObjectIdentifier::adjustLinks(), TestSpreadsheet::v, and var.
_collectReplacement()
void VariableExpression::_collectReplacement (std::map< ObjectIdentifier, ObjectIdentifier > & paths, const App::DocumentObject * parent, App::DocumentObject * oldObj, App::DocumentObject * newObj) const override protected virtual
Reimplemented from App::Expression.
Definition at line 3021 of file Expression.cpp.
References App::ObjectIdentifier::canonicalPath(), Path.Post.scripts.opensbp_post::move(), Init::parent, App::ObjectIdentifier::replaceObject(), and var.
_copy()
Expression * VariableExpression::_copy () const override protected virtual
Return a copy of the expression.
Reimplemented from App::UnitExpression.
Definition at line 2951 of file Expression.cpp.
References App::Expression::owner, var, and VariableExpression().
_getIdentifiers()
void VariableExpression::_getIdentifiers (std::map< App::ObjectIdentifier, bool > & deps) const override protected virtual
Reimplemented from App::Expression.
Definition at line 2956 of file Expression.cpp.
References HiddenReference::isHidden(), and var.
_getPyValue()
Py::Object VariableExpression::_getPyValue () const override protected virtual
Reimplemented from App::UnitExpression.
Definition at line 2924 of file Expression.cpp.
References App::ObjectIdentifier::getPyValue(), and var.
_importSubNames()
void VariableExpression::_importSubNames (const ObjectIdentifier::SubNameMap & subNameMap) override protected virtual
Reimplemented from App::Expression.
Definition at line 2976 of file Expression.cpp.
References App::ObjectIdentifier::importSubNames(), and var.
_isIndexable()
bool VariableExpression::_isIndexable () const override protected virtual
Reimplemented from App::Expression.
Definition at line 2920 of file Expression.cpp.
_moveCells()
void VariableExpression::_moveCells (const CellAddress & address, int rowCount, int colCount, ExpressionVisitor & v) override protected virtual
Reimplemented from App::Expression.
Definition at line 3032 of file Expression.cpp.
References App::CellAddress::col(), App::Expression::comp, App::ObjectIdentifier::Component::getName(), App::ObjectIdentifier::getPropertyComponent(), App::ObjectIdentifier::hasDocumentObjectName(), App::CellAddress::isValid(), App::CellAddress::row(), App::CellAddress::setCol(), App::ObjectIdentifier::setComponent(), App::CellAddress::setRow(), App::ObjectIdentifier::SimpleComponent(), App::stringToAddress(), App::CellAddress::toString(), TestSpreadsheet::v, and var.
_offsetCells()
void VariableExpression::_offsetCells (int rowOffset, int colOffset, ExpressionVisitor & v) override protected virtual
Reimplemented from App::Expression.
Definition at line 3054 of file Expression.cpp.
References App::CellAddress::col(), App::Expression::comp, FC_WARN, App::ObjectIdentifier::Component::getName(), App::ObjectIdentifier::getPropertyComponent(), App::ObjectIdentifier::hasDocumentObjectName(), App::CellAddress::isAbsoluteCol(), App::CellAddress::isAbsoluteRow(), App::CellAddress::isValid(), App::CellAddress::row(), App::CellAddress::setCol(), App::ObjectIdentifier::setComponent(), App::CellAddress::setRow(), App::ObjectIdentifier::SimpleComponent(), App::stringToAddress(), App::CellAddress::toString(), TestSpreadsheet::v, and var.
_relabeledDocument()
bool VariableExpression::_relabeledDocument (const std::string & oldName, const std::string & newName, ExpressionVisitor & v) override protected virtual
Reimplemented from App::Expression.
Definition at line 2964 of file Expression.cpp.
References App::ObjectIdentifier::relabeledDocument(), TestSpreadsheet::v, and var.
_renameObjectIdentifier()
bool VariableExpression::_renameObjectIdentifier (const std::map< ObjectIdentifier, ObjectIdentifier > & paths, const ObjectIdentifier & path, ExpressionVisitor & visitor) override protected virtual
Reimplemented from App::Expression.
Definition at line 2993 of file Expression.cpp.
References App::ExpressionVisitor::aboutToChange(), App::ObjectIdentifier::canonicalPath(), App::ObjectIdentifier::getDocumentObjectName(), App::ObjectIdentifier::getSubObjectName(), App::ObjectIdentifier::hasDocumentObjectName(), Path.Post.scripts.opensbp_post::move(), App::ObjectIdentifier::relativeTo(), App::ObjectIdentifier::setDocumentObjectName(), and var.
_toString()
void VariableExpression::_toString (std::ostream & ss, bool persistent, int indent) const override protected virtual
Return a string representation, in this case the unit string. Return a string representation of the expression.
Reimplemented from App::UnitExpression.
Definition at line 2928 of file Expression.cpp.
References App::ObjectIdentifier::toPersistentString(), App::ObjectIdentifier::toString(), and var.
_updateElementReference()
bool VariableExpression::_updateElementReference (App::DocumentObject * feature, bool reverse, ExpressionVisitor & v) override protected virtual
Reimplemented from App::Expression.
Definition at line 2987 of file Expression.cpp.
References App::ObjectIdentifier::updateElementReference(), TestSpreadsheet::v, and var.
_updateLabelReference()
void VariableExpression::_updateLabelReference (App::DocumentObject * obj, const std::string & ref, const char * newLabel) override protected virtual
Reimplemented from App::Expression.
Definition at line 2981 of file Expression.cpp.
References App::ObjectIdentifier::updateLabelReference(), and var.
addComponent()
void VariableExpression::addComponent (Component * component) override virtual
Reimplemented from App::Expression.
Definition at line 2874 of file Expression.cpp.
References App::Expression::addComponent(), App::ObjectIdentifier::ArrayComponent(), SCL.SimpleDataTypes::c, App::Expression::components, essentiallyEqual(), essentiallyInteger(), src.Mod.PartDesign.Scripts.Gear::l1, src.Mod.PartDesign.Scripts.Gear::l2, src.Mod.PartDesign.Scripts.Gear::l3, App::ObjectIdentifier::MapComponent(), App::ObjectIdentifier::RangeComponent(), toolbit-attributes::s, and var.
getPath()
ObjectIdentifier App::VariableExpression::getPath () const inline
Definition at line 481 of file ExpressionParser.h.
getProperty()
const Property * VariableExpression::getProperty () const
Find the property this expression referse to.
Unqualified names (i.e the name only without any dots) are resolved in the owning DocumentObjects. Qualified names are looked up in the owning Document. It is first looked up by its internal name. If not found, the DocumentObjects' labels searched.
If something fails, an exception is thrown.
Returns
The Property object if it is derived from either PropertyInteger, PropertyFloat, or PropertyString.
Definition at line 2864 of file Expression.cpp.
References App::ObjectIdentifier::getProperty(), App::ObjectIdentifier::resolveErrorString(), and var.
isTouched()
bool VariableExpression::isTouched () const override virtual
Determine if the expression is touched or not, i.e whether the Property object it refers to is touched().
Returns
True if the Property object is touched, false if not.
Reimplemented from App::Expression.
Definition at line 2847 of file Expression.cpp.
References App::ObjectIdentifier::isTouched(), and var.
name()
std::string App::VariableExpression::name () const inline
Definition at line 476 of file ExpressionParser.h.
Referenced by src.Mod.AddonManager.addonmanager_licenses.SPDXLicenseManager::normalize().
setPath()
void VariableExpression::setPath (const ObjectIdentifier & path)
Definition at line 3078 of file Expression.cpp.
References var.
simplify()
Expression * VariableExpression::simplify () const override virtual
Simplify the expression. Simplification of VariableExpression objects is not possible (if it is instantiated it would be an evaluation instead).
Returns
A copy of the expression.
Reimplemented from App::UnitExpression.
Definition at line 2942 of file Expression.cpp.
References App::Expression::copy().
Member Data Documentation
var
ObjectIdentifier App::VariableExpression::var protected
Variable name
Definition at line 514 of file ExpressionParser.h.
Referenced by _adjustLinks(), _collectReplacement(), _copy(), _getIdentifiers(), _getPyValue(), _importSubNames(), _moveCells(), _offsetCells(), _relabeledDocument(), _renameObjectIdentifier(), _toString(), _updateElementReference(), _updateLabelReference(), addComponent(), getProperty(), isTouched(), and setPath().
The documentation for this class was generated from the following files:
ExpressionParser.h
Expression.cpp