FreeCAD: BimSelect.CyclicObjectSelector Class Reference
BimSelect.CyclicObjectSelector Class Reference
Public Member Functions
def __init__ (self)
def selectObject (self, event_callback)
def cycleSelectableObjects (self, event_callback)
Public Attributes
selectableObjects
objectIndex
Detailed Description
Definition at line 23 of file BimSelect.py.
Constructor & Destructor Documentation
__init__()
def BimSelect.CyclicObjectSelector.__init__ (self)
Definition at line 24 of file BimSelect.py.
Referenced by draftguitools.gui_subelements.SubelementHighlight.finish().
Member Function Documentation
cycleSelectableObjects()
def BimSelect.CyclicObjectSelector.cycleSelectableObjects (self, event_callback)
Definition at line 57 of file BimSelect.py.
References getValue(), BimSelect.CyclicObjectSelector.objectIndex, and BimSelect.CyclicObjectSelector.selectableObjects.
selectObject()
def BimSelect.CyclicObjectSelector.selectObject (self, event_callback)
Definition at line 28 of file BimSelect.py.
References getValue(), and BimSelect.CyclicObjectSelector.selectableObjects.
Member Data Documentation
objectIndex
BimSelect.CyclicObjectSelector.objectIndex
Definition at line 26 of file BimSelect.py.
Referenced by BimSelect.CyclicObjectSelector.cycleSelectableObjects().
selectableObjects
BimSelect.CyclicObjectSelector.selectableObjects
Definition at line 25 of file BimSelect.py.
Referenced by BimSelect.CyclicObjectSelector.cycleSelectableObjects(), and BimSelect.CyclicObjectSelector.selectObject().
The documentation for this class was generated from the following file:
BimSelect.py