FreeCAD: Gui::PropertyEditor::RotationHelper Class Reference
Gui::PropertyEditor::RotationHelper Class Reference
#include <PropertyItem.h>
Public Member Functions
RotationHelper ()
void setChanged (bool)
bool hasChangedAndReset ()
bool isAxisInitialized () const
void setValue (const Base::Vector3d &axis, double angle)
void getValue (Base::Vector3d &axis, double &angle) const
double getAngle (const Base::Rotation &val) const
Base::Rotation setAngle (double)
Base::Vector3d getAxis () const
Base::Rotation setAxis (const Base::Rotation &value, const Base::Vector3d &axis)
void assignProperty (const Base::Rotation &value, double eps)
Detailed Description
Definition at line 777 of file PropertyItem.h.
Constructor & Destructor Documentation
RotationHelper()
RotationHelper::RotationHelper ()
Definition at line 2295 of file PropertyItem.cpp.
Member Function Documentation
assignProperty()
void RotationHelper::assignProperty (const Base::Rotation & value, double eps)
Definition at line 2379 of file PropertyItem.cpp.
References Base::Vector3< float_type >::Cross(), Base::Vector3< float_type >::Dot(), Base::Rotation::getRawValue(), Base::Vector3< float_type >::Sqr(), and Base::toDegrees().
Referenced by Gui::PropertyEditor::PropertyRotationItem::assignProperty(), and Gui::PropertyEditor::PropertyPlacementItem::assignProperty().
getAngle()
double RotationHelper::getAngle (const Base::Rotation & val) const
Definition at line 2335 of file PropertyItem.cpp.
References toolbit-attributes::val.
Referenced by Gui::PropertyEditor::PropertyRotationItem::getAngle(), Gui::PropertyEditor::PropertyPlacementItem::getAngle(), Path.Dressup.Gui.Dogbone.Chord::getAngleXY(), draftguitools.gui_trackers.arcTracker::setEndPoint(), and draftguitools.gui_trackers.arcTracker::setStartPoint().
getAxis()
Base::Vector3d RotationHelper::getAxis () const
Definition at line 2355 of file PropertyItem.cpp.
Referenced by Gui::PropertyEditor::PropertyRotationItem::getAxis(), and Gui::PropertyEditor::PropertyPlacementItem::getAxis().
getValue()
void RotationHelper::getValue (Base::Vector3d & axis, double & angle) const
Definition at line 2329 of file PropertyItem.cpp.
Referenced by Gui::PropertyEditor::PropertyRotationItem::setValue(), and Gui::PropertyEditor::PropertyPlacementItem::setValue().
hasChangedAndReset()
bool RotationHelper::hasChangedAndReset ()
Definition at line 2307 of file PropertyItem.cpp.
Referenced by Gui::PropertyEditor::PropertyRotationItem::setValue(), and Gui::PropertyEditor::PropertyPlacementItem::setValue().
isAxisInitialized()
bool RotationHelper::isAxisInitialized () const
Definition at line 2317 of file PropertyItem.cpp.
Referenced by Gui::PropertyEditor::PropertyRotationItem::value(), and Gui::PropertyEditor::PropertyPlacementItem::value().
setAngle()
Base::Rotation RotationHelper::setAngle (double angle)
Definition at line 2346 of file PropertyItem.cpp.
References Base::Rotation::setValue().
Referenced by Gui::PropertyEditor::PropertyRotationItem::setAngle(), and Gui::PropertyEditor::PropertyPlacementItem::setAngle().
setAxis()
Base::Rotation RotationHelper::setAxis (const Base::Rotation & value, const Base::Vector3d & axis)
Definition at line 2364 of file PropertyItem.cpp.
References Base::Rotation::getValue(), and Base::Rotation::setValue().
Referenced by Gui::PropertyEditor::PropertyRotationItem::setAxis(), and Gui::PropertyEditor::PropertyPlacementItem::setAxis().
setChanged()
void RotationHelper::setChanged (bool value)
Definition at line 2302 of file PropertyItem.cpp.
Referenced by Gui::PropertyEditor::PropertyPlacementItem::setPosition().
setValue()
void RotationHelper::setValue (const Base::Vector3d & axis, double angle)
Definition at line 2322 of file PropertyItem.cpp.
Referenced by Gui::PropertyEditor::PropertyRotationItem::value(), and Gui::PropertyEditor::PropertyPlacementItem::value().
The documentation for this class was generated from the following files:
PropertyItem.h
PropertyItem.cpp