FreeCAD: ReportGenerator.ReportGenerator Class Reference
ReportGenerator.ReportGenerator Class Reference
Public Member Functions
def __init__ (self, data, embed_images=False)
def generate_html (self)
def encode_gcode_to_base64 (filepath)
def file_to_base64_with_tag (self, file_path)
Public Attributes
embed_images
squawks
tools
run_summary_ops
formatted_data
translated_labels
Detailed Description
Definition at line 48 of file ReportGenerator.py.
Constructor & Destructor Documentation
__init__()
def ReportGenerator.ReportGenerator.__init__ (self, data, embed_images = False)
Definition at line 49 of file ReportGenerator.py.
Referenced by draftguitools.gui_subelements.SubelementHighlight.finish().
Member Function Documentation
encode_gcode_to_base64()
def ReportGenerator.ReportGenerator.encode_gcode_to_base64 (filepath)
Definition at line 222 of file ReportGenerator.py.
References importFCMat.decode(), and AssemblyImport.open().
file_to_base64_with_tag()
def ReportGenerator.ReportGenerator.file_to_base64_with_tag (self, file_path)
Definition at line 227 of file ReportGenerator.py.
References importFCMat.decode(), Path.Log.error(), and AssemblyImport.open().
generate_html()
def ReportGenerator.ReportGenerator.generate_html (self)
Definition at line 217 of file ReportGenerator.py.
References ReportGenerator.ReportGenerator.formatted_data, and ReportGenerator.ReportGenerator.translated_labels.
Member Data Documentation
embed_images
ReportGenerator.ReportGenerator.embed_images
Definition at line 50 of file ReportGenerator.py.
formatted_data
ReportGenerator.ReportGenerator.formatted_data
Definition at line 54 of file ReportGenerator.py.
Referenced by ReportGenerator.ReportGenerator.generate_html().
run_summary_ops
ReportGenerator.ReportGenerator.run_summary_ops
Definition at line 53 of file ReportGenerator.py.
squawks
ReportGenerator.ReportGenerator.squawks
Definition at line 51 of file ReportGenerator.py.
tools
ReportGenerator.ReportGenerator.tools
Definition at line 52 of file ReportGenerator.py.
translated_labels
ReportGenerator.ReportGenerator.translated_labels
Definition at line 55 of file ReportGenerator.py.
Referenced by ReportGenerator.ReportGenerator.generate_html().
The documentation for this class was generated from the following file:
ReportGenerator.py