FreeCAD: ImageBuilder.NonGuiImageBuilder Class Reference
ImageBuilder.NonGuiImageBuilder Class Reference
Public Member Functions
def __init__ (self, file_path)
def build_image (self, obj, image_name)
Public Member Functions inherited from ImageBuilder.ImageBuilder
def save_image (self, image)
Additional Inherited Members
Public Attributes inherited from ImageBuilder.ImageBuilder
file_path
Detailed Description
Definition at line 158 of file ImageBuilder.py.
Constructor & Destructor Documentation
__init__()
def ImageBuilder.NonGuiImageBuilder.__init__ (self, file_path)
Reimplemented from ImageBuilder.ImageBuilder.
Definition at line 159 of file ImageBuilder.py.
References Path.Log.debug().
Referenced by draftguitools.gui_subelements.SubelementHighlight.finish().
Member Function Documentation
build_image()
def ImageBuilder.NonGuiImageBuilder.build_image (self, obj, image_name)
Generates a headless picture of a 3D object and saves it as a PNG and optionally a PostScript file.
Args:
- obj: The 3D object to generate an image for.
- image_name: Base name for the output image file without extension.
Returns:
- A boolean indicating the success of the operation.
Reimplemented from ImageBuilder.ImageBuilder.
Definition at line 163 of file ImageBuilder.py.
References Path.Log.debug().
The documentation for this class was generated from the following file:
ImageBuilder.py