FreeCAD: Wm4::GMatrix< Real > Class Template Reference
Wm4::GMatrix< Real > Class Template Reference
#include <Wm4GMatrix.h>
Public Member Functions
GMatrix (int iRows=0, int iCols=0)
GMatrix (int iRows, int iCols, const Real *afData)
GMatrix (int iRows, int iCols, const Real **aafEntry)
GMatrix (const GMatrix &rkM)
~GMatrix ()
void SetSize (int iRows, int iCols)
void GetSize (int &riRows, int &riCols) const
int GetRows () const
int GetColumns () const
int GetQuantity () const
operator const Real * () const
operator Real * ()
const Real * operator[] (int iRow) const
Real * operator[] (int iRow)
void SwapRows (int iRow0, int iRow1)
Real operator() (int iRow, int iCol) const
Real & operator() (int iRow, int iCol)
void SetRow (int iRow, const GVector< Real > &rkV)
GVector< Real > GetRow (int iRow) const
void SetColumn (int iCol, const GVector< Real > &rkV)
GVector< Real > GetColumn (int iCol) const
void SetMatrix (int iRows, int iCols, const Real *afEntry)
void SetMatrix (int iRows, int iCols, const Real **aafMatrix)
void GetColumnMajor (Real *afCMajor) const
GMatrix & operator= (const GMatrix &rkM)
bool operator== (const GMatrix &rkM) const
bool operator!= (const GMatrix &rkM) const
bool operator< (const GMatrix &rkM) const
bool operator<= (const GMatrix &rkM) const
bool operator> (const GMatrix &rkM) const
bool operator>= (const GMatrix &rkM) const
GMatrix operator+ (const GMatrix &rkM) const
GMatrix operator- (const GMatrix &rkM) const
GMatrix operator* (const GMatrix &rkM) const
GMatrix operator* (Real fScalar) const
GMatrix operator/ (Real fScalar) const
GMatrix operator- () const
GMatrix & operator+= (const GMatrix &rkM)
GMatrix & operator-= (const GMatrix &rkM)
GMatrix & operator*= (Real fScalar)
GMatrix & operator/= (Real fScalar)
GMatrix Transpose () const
GMatrix TransposeTimes (const GMatrix &rkM) const
GMatrix TimesTranspose (const GMatrix &rkM) const
GVector< Real > operator* (const GVector< Real > &rkV) const
Real QForm (const GVector< Real > &rkU, const GVector< Real > &rkV) const
bool GetInverse (GMatrix< Real > &rkInverse) const
Protected Member Functions
void Allocate (bool bSetToZero)
void Deallocate ()
int CompareArrays (const GMatrix &rkM) const
Protected Attributes
int m_iRows
int m_iCols
int m_iQuantity
Real * m_afData
Real ** m_aafEntry
Detailed Description
template<class Real>
class Wm4::GMatrix< Real >
Definition at line 40 of file Wm4GMatrix.h.
Constructor & Destructor Documentation
GMatrix() [1/4]
template<class Real > Wm4::GMatrix< Real >::GMatrix (int iRows = 0, int iCols = 0)
GMatrix() [2/4]
template<class Real > Wm4::GMatrix< Real >::GMatrix (int iRows, int iCols, const Real * afData)
GMatrix() [3/4]
template<class Real > Wm4::GMatrix< Real >::GMatrix (int iRows, int iCols, const Real ** aafEntry)
GMatrix() [4/4]
template<class Real > Wm4::GMatrix< Real >::GMatrix (const GMatrix< Real > & rkM)
~GMatrix()
template<class Real > Wm4::GMatrix< Real >::~GMatrix ()
Member Function Documentation
Allocate()
template<class Real > void Wm4::GMatrix< Real >::Allocate (bool bSetToZero) protected
CompareArrays()
template<class Real > int Wm4::GMatrix< Real >::CompareArrays (const GMatrix< Real > & rkM) const protected
Deallocate()
template<class Real > void Wm4::GMatrix< Real >::Deallocate () protected
GetColumn()
template<class Real > GVector<Real> Wm4::GMatrix< Real >::GetColumn (int iCol) const
GetColumnMajor()
template<class Real > void Wm4::GMatrix< Real >::GetColumnMajor (Real * afCMajor) const
GetColumns()
template<class Real > int Wm4::GMatrix< Real >::GetColumns () const
Referenced by Wm4::Eigen< Real >::Eigen(), Wm4::LinearSystem< Real >::Inverse(), Wm4::LinearSystem< Real >::Solve(), and Wm4::LinearSystem< Real >::SolveSymmetricCG().
GetInverse()
template<class Real > bool Wm4::GMatrix< Real >::GetInverse (GMatrix< Real > & rkInverse) const
GetQuantity()
template<class Real > int Wm4::GMatrix< Real >::GetQuantity () const
GetRow()
template<class Real > GVector<Real> Wm4::GMatrix< Real >::GetRow (int iRow) const
GetRows()
template<class Real > int Wm4::GMatrix< Real >::GetRows () const
Referenced by Wm4::Eigen< Real >::Eigen(), Wm4::LinearSystem< Real >::Inverse(), and Wm4::LinearSystem< Real >::SolveSymmetricCG().
GetSize()
template<class Real > void Wm4::GMatrix< Real >::GetSize (int & riRows, int & riCols) const
operator const Real *()
template<class Real > Wm4::GMatrix< Real >::operator const Real * () const
operator Real *()
template<class Real > Wm4::GMatrix< Real >::operator Real * ()
operator!=()
template<class Real > bool Wm4::GMatrix< Real >::operator!= (const GMatrix< Real > & rkM) const
operator()() [1/2]
template<class Real > Real& Wm4::GMatrix< Real >::operator() (int iRow, int iCol)
operator()() [2/2]
template<class Real > Real Wm4::GMatrix< Real >::operator() (int iRow, int iCol) const
operator*() [1/3]
template<class Real > GMatrix Wm4::GMatrix< Real >::operator* (const GMatrix< Real > & rkM) const
operator*() [2/3]
template<class Real > GVector<Real> Wm4::GMatrix< Real >::operator* (const GVector< Real > & rkV) const
operator*() [3/3]
template<class Real > GMatrix Wm4::GMatrix< Real >::operator* (Real fScalar) const
operator*=()
template<class Real > GMatrix& Wm4::GMatrix< Real >::operator*= (Real fScalar)
operator+()
template<class Real > GMatrix Wm4::GMatrix< Real >::operator+ (const GMatrix< Real > & rkM) const
operator+=()
template<class Real > GMatrix& Wm4::GMatrix< Real >::operator+= (const GMatrix< Real > & rkM)
operator-() [1/2]
template<class Real > GMatrix Wm4::GMatrix< Real >::operator- () const
operator-() [2/2]
template<class Real > GMatrix Wm4::GMatrix< Real >::operator- (const GMatrix< Real > & rkM) const
operator-=()
template<class Real > GMatrix& Wm4::GMatrix< Real >::operator-= (const GMatrix< Real > & rkM)
operator/()
template<class Real > GMatrix Wm4::GMatrix< Real >::operator/ (Real fScalar) const
operator/=()
template<class Real > GMatrix& Wm4::GMatrix< Real >::operator/= (Real fScalar)
operator<()
template<class Real > bool Wm4::GMatrix< Real >::operator< (const GMatrix< Real > & rkM) const
operator<=()
template<class Real > bool Wm4::GMatrix< Real >::operator<= (const GMatrix< Real > & rkM) const
operator=()
template<class Real > GMatrix& Wm4::GMatrix< Real >::operator= (const GMatrix< Real > & rkM)
operator==()
template<class Real > bool Wm4::GMatrix< Real >::operator== (const GMatrix< Real > & rkM) const
operator>()
template<class Real > bool Wm4::GMatrix< Real >::operator> (const GMatrix< Real > & rkM) const
operator>=()
template<class Real > bool Wm4::GMatrix< Real >::operator>= (const GMatrix< Real > & rkM) const
operator[]() [1/2]
template<class Real > Real* Wm4::GMatrix< Real >::operator[] (int iRow)
operator[]() [2/2]
template<class Real > const Real* Wm4::GMatrix< Real >::operator[] (int iRow) const
QForm()
template<class Real > Real Wm4::GMatrix< Real >::QForm (const GVector< Real > & rkU, const GVector< Real > & rkV) const
SetColumn()
template<class Real > void Wm4::GMatrix< Real >::SetColumn (int iCol, const GVector< Real > & rkV)
SetMatrix() [1/2]
template<class Real > void Wm4::GMatrix< Real >::SetMatrix (int iRows, int iCols, const Real ** aafMatrix)
SetMatrix() [2/2]
template<class Real > void Wm4::GMatrix< Real >::SetMatrix (int iRows, int iCols, const Real * afEntry)
SetRow()
template<class Real > void Wm4::GMatrix< Real >::SetRow (int iRow, const GVector< Real > & rkV)
SetSize()
template<class Real > void Wm4::GMatrix< Real >::SetSize (int iRows, int iCols)
SwapRows()
template<class Real > void Wm4::GMatrix< Real >::SwapRows (int iRow0, int iRow1)
Referenced by Wm4::LinearSystem< Real >::Inverse(), and Wm4::LinearSystem< Real >::Solve().
TimesTranspose()
template<class Real > GMatrix Wm4::GMatrix< Real >::TimesTranspose (const GMatrix< Real > & rkM) const
Transpose()
template<class Real > GMatrix Wm4::GMatrix< Real >::Transpose () const
TransposeTimes()
template<class Real > GMatrix Wm4::GMatrix< Real >::TransposeTimes (const GMatrix< Real > & rkM) const
Member Data Documentation
m_aafEntry
template<class Real > Real** Wm4::GMatrix< Real >::m_aafEntry protected
Definition at line 128 of file Wm4GMatrix.h.
m_afData
template<class Real > Real* Wm4::GMatrix< Real >::m_afData protected
Definition at line 123 of file Wm4GMatrix.h.
m_iCols
template<class Real > int Wm4::GMatrix< Real >::m_iCols protected
Definition at line 120 of file Wm4GMatrix.h.
m_iQuantity
template<class Real > int Wm4::GMatrix< Real >::m_iQuantity protected
Definition at line 120 of file Wm4GMatrix.h.
m_iRows
template<class Real > int Wm4::GMatrix< Real >::m_iRows protected
Definition at line 120 of file Wm4GMatrix.h.
The documentation for this class was generated from the following file:
Wm4GMatrix.h