FreeCAD: cStock Class Reference
cStock Class Reference
#include <VolSim.h>
Public Member Functions
cStock (float px, float py, float pz, float lx, float ly, float lz, float res)
~cStock ()
void Tessellate (Mesh::MeshObject &meshOuter, Mesh::MeshObject &meshInner)
void CreatePocket (float x, float y, float rad, float height)
void ApplyLinearTool (Point3D &p1, Point3D &p2, cSimTool &tool)
void ApplyCircularTool (Point3D &p1, Point3D &p2, Point3D &cent, cSimTool &tool, bool isCCW)
Point3D ToInner (Point3D &p)
Detailed Description
Definition at line 221 of file VolSim.h.
Constructor & Destructor Documentation
cStock()
cStock::cStock (float px, float py, float pz, float lx, float ly, float lz, float res)
Definition at line 39 of file VolSim.cpp.
References Array2D< T >::Init(), MovieTool::x, and MovieTool::y.
~cStock()
cStock::~cStock ()
Definition at line 61 of file VolSim.cpp.
Member Function Documentation
ApplyCircularTool()
void cStock::ApplyCircularTool (Point3D & p1, Point3D & p2, Point3D & cent, cSimTool & tool, bool isCCW)
Definition at line 578 of file VolSim.cpp.
References KDL::atan2(), SCL.SimpleDataTypes::f, cSimTool::GetToolProfileAt(), SplineSurface::i, KDL::max(), cSimTool::radius, Point3D::Rotate(), Point3D::SetRotationAngleRad(), SIM_WALK_RES, KDL::sqrt(), InitGui::t, ToInner(), unit(), MovieTool::x, Point3D::x, MovieTool::y, Point3D::y, and Point3D::z.
ApplyLinearTool()
void cStock::ApplyLinearTool (Point3D & p1, Point3D & p2, cSimTool & tool)
Definition at line 512 of file VolSim.cpp.
References a, SCL.SimpleDataTypes::f, cSimTool::GetToolProfileAt(), SplineSurface::i, buildPsets::p, src.Mod.Test.testPathArray::path, cSimTool::radius, Point3D::Rotate(), Point3D::SetRotationAngle(), SIM_EPSILON, SIM_WALK_RES, InitGui::t, ToInner(), MovieTool::x, Point3D::x, MovieTool::y, Point3D::y, and Point3D::z.
CreatePocket()
void cStock::CreatePocket (float x, float y, float rad, float height)
Definition at line 491 of file VolSim.cpp.
References KDL::max(), KDL::min(), MovieTool::x, and MovieTool::y.
Tessellate()
void cStock::Tessellate (Mesh::MeshObject & meshOuter, Mesh::MeshObject & meshInner)
Definition at line 448 of file VolSim.cpp.
References Mesh::MeshObject::addFacets(), SIM_TESSEL_BOT, SIM_TESSEL_TOP, MovieTool::x, and MovieTool::y.
ToInner()
Point3D cStock::ToInner (Point3D & p) inline
Definition at line 230 of file VolSim.h.
References buildPsets::p.
Referenced by ApplyCircularTool(), and ApplyLinearTool().
The documentation for this class was generated from the following files:
VolSim.h
VolSim.cpp