FreeCAD: OverlayStyleSheet Class Reference
OverlayStyleSheet Class Reference
Public Member Functions
OverlayStyleSheet ()
void OnChange (Base::Subject< const char * > &, const char *sReason)
void update ()
Static Public Member Functions
static OverlayStyleSheet * instance ()
Public Attributes
ParameterGrp::handle handle
QString activeStyleSheet
bool hideTab = false
Detailed Description
Definition at line 92 of file OverlayManager.cpp.
Constructor & Destructor Documentation
OverlayStyleSheet()
OverlayStyleSheet::OverlayStyleSheet () inline
Definition at line 95 of file OverlayManager.cpp.
References App::GetApplication(), and App::Application::GetParameterGroupByPath().
Member Function Documentation
instance()
static OverlayStyleSheet* OverlayStyleSheet::instance () inline static
Definition at line 104 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::getHideTab(), Gui::OverlayManager::getStyleSheet(), and Gui::OverlayManager::Private::refresh().
OnChange()
void OverlayStyleSheet::OnChange (Base::Subject< const char * > & , const char * sReason) inline
Definition at line 114 of file OverlayManager.cpp.
References Gui::OverlayManager::instance(), and Gui::OverlayManager::refresh().
update()
void OverlayStyleSheet::update () inline
Definition at line 125 of file OverlayManager.cpp.
Referenced by bimcommands.BimViews.BIM_Views::Activated(), ArchAxisSystem.AxisSystemTaskPanel::addElement(), ArchSectionPlane.SectionPlaneTaskPanel::addElement(), DraftGui.FacebinderTaskPanel::addElement(), ArchComponent.ComponentTaskPanel::addElement(), bimcommands.BimViews.BIM_Views::addLevel(), bimcommands.BimViews.BIM_Views::addProxy(), femtaskpanels.task_result_mechanical._TaskPanel::calculate(), bimcommands.BimIfcElements.BIM_IfcElements::checkMatChanged(), ArchWindow._ArchWindowTaskPanel::create(), bimcommands.BimViews.BIM_Views::delete(), draftguitools.gui_edit.Edit::endEditing(), bimcommands.BimWall.Arch_Wall::getPoint(), ArchStructure._CommandStructure::getPoint(), draftguitools.gui_trackers.boxTracker::height(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimTutorial.BIM_Tutorial::next(), bimcommands.BimIfcElements.BIM_IfcElements::onMaterialChanged(), bimcommands.BimIfcElements.BIM_IfcElements::onObjectTypeChanged(), bimcommands.BimIfcProperties.BIM_IfcProperties::onSelected(), bimcommands.BimIfcProperties.BIM_IfcProperties::onVisible(), draftguitools.gui_trackers.rectangleTracker::p3(), Plot.Plot::plot(), bimcommands.BimTutorial.BIM_Tutorial::previous(), Gui::OverlayManager::Private::refresh(), ArchAxisSystem.AxisSystemTaskPanel::removeElement(), ArchAxis._AxisTaskPanel::removeElement(), ArchWindow._ArchWindowTaskPanel::removeElement(), ArchSectionPlane.SectionPlaneTaskPanel::removeElement(), DraftGui.FacebinderTaskPanel::removeElement(), ArchComponent.ComponentTaskPanel::removeElement(), draftguitools.gui_trackers.gridTracker::reset(), ArchRoof._RoofTaskPanel::resetObject(), ArchNesting.Nester::run(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setDescription(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setHeight(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setLabel(), draftguitools.gui_trackers.gridTracker::setMainlines(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setMaterial(), draftguitools.gui_trackers.gridTracker::setSize(), draftguitools.gui_trackers.gridTracker::setSpacing(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setTag(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setWidth(), and bimcommands.BimViews.BIM_Views::update().
Member Data Documentation
activeStyleSheet
QString OverlayStyleSheet::activeStyleSheet
Definition at line 138 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::getStyleSheet().
handle
ParameterGrp::handle OverlayStyleSheet::handle
Definition at line 137 of file OverlayManager.cpp.
hideTab
bool OverlayStyleSheet::hideTab = false
Definition at line 139 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::getHideTab().
The documentation for this class was generated from the following file:
OverlayManager.cpp