FreeCAD: TechDrawGui::TaskCenterLine Class Reference
TechDrawGui::TaskCenterLine Class Reference
#include <TaskCenterLine.h>
Public Member Functions
TaskCenterLine (TechDraw::DrawViewPart *partFeat, TechDraw::DrawPage *page, std::vector< std::string > subNames, bool editMode)
TaskCenterLine (TechDraw::DrawViewPart *partFeat, TechDraw::DrawPage *page, std::string edgeName, bool editMode)
~TaskCenterLine () override
virtual bool accept ()
virtual bool reject ()
virtual void setCreateMode (bool mode)
virtual bool getCreateMode () const
void updateTask ()
void saveButtons (QPushButton *btnOK, QPushButton *btnCancel)
void enableTaskButtons (bool isEnabled)
Protected Member Functions
void changeEvent (QEvent *event) override
void setUiConnect ()
void setUiPrimary ()
void setUiEdit ()
void createCenterLine ()
void updateOrientation ()
double getCenterWidth ()
QColor getCenterColor ()
double getExtendBy ()
int checkPathologicalEdges (int inMode)
int checkPathologicalVertices (int inMode)
void setUiOrientation (int orientation)
Detailed Description
Definition at line 54 of file TaskCenterLine.h.
Constructor & Destructor Documentation
TaskCenterLine() [1/2]
TaskCenterLine::TaskCenterLine (TechDraw::DrawViewPart * partFeat, TechDraw::DrawPage * page, std::vector< std::string > subNames, bool editMode)
Definition at line 87 of file TaskCenterLine.cpp.
References ArchCommands::check(), Base::Console(), createCenterLine(), ZVALUE::EDGE, Base::ConsoleSingleton::Error(), ZVALUE::FACE, draftgeoutils.general::geomType(), TechDraw::DrawUtil::getGeomTypeFromName(), setUiConnect(), setUiPrimary(), and ZVALUE::VERTEX.
TaskCenterLine() [2/2]
TaskCenterLine::TaskCenterLine (TechDraw::DrawViewPart * partFeat, TechDraw::DrawPage * page, std::string edgeName, bool editMode)
Definition at line 53 of file TaskCenterLine.cpp.
References TechDraw::CosmeticExtension::getCenterLine(), TechDraw::DrawViewPart::getEdgeGeometry(), TechDraw::CenterLine::m_mode, TechDraw::CenterLine::m_type, setUiConnect(), setUiEdit(), and Dice3DS.dom3ds::tag.
~TaskCenterLine()
TaskCenterLine::~TaskCenterLine () override
Definition at line 128 of file TaskCenterLine.cpp.
Member Function Documentation
accept()
bool TaskCenterLine::accept () virtual
Definition at line 533 of file TaskCenterLine.cpp.
References Gui::Command::commitCommand(), toolbit-attributes::doc, App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::Application::Instance, and Gui::Command::updateActive().
Referenced by TechDrawGui::TaskDlgCenterLine::accept().
changeEvent()
void TaskCenterLine::changeEvent (QEvent * event) override protected
Definition at line 136 of file TaskCenterLine.cpp.
checkPathologicalEdges()
int TaskCenterLine::checkPathologicalEdges (int inMode) protected
Definition at line 346 of file TaskCenterLine.cpp.
References ZVALUE::EDGE, EWTOLERANCE, TechDraw::DrawUtil::fpCompare(), TechDraw::DrawViewPart::getEdge(), HORIZONTAL, and VERTICAL.
Referenced by createCenterLine(), setUiPrimary(), and updateOrientation().
checkPathologicalVertices()
int TaskCenterLine::checkPathologicalVertices (int inMode) protected
Definition at line 376 of file TaskCenterLine.cpp.
References EWTOLERANCE, TechDraw::DrawUtil::fpCompare(), TechDraw::DrawViewPart::getVertex(), HORIZONTAL, ZVALUE::VERTEX, VERTICAL, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by createCenterLine(), setUiPrimary(), and updateOrientation().
createCenterLine()
void TaskCenterLine::createCenterLine () protected
Definition at line 403 of file TaskCenterLine.cpp.
References Gui::Command::abortCommand(), TechDraw::CosmeticExtension::addCenterLine(), checkPathologicalEdges(), checkPathologicalVertices(), Gui::Command::commitCommand(), ZVALUE::EDGE, TechDraw::CenterLine::m_flip2Line, TechDraw::CenterLine::m_format, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, App::DocumentObject::recomputeFeature(), TechDraw::LineFormat::setColor(), TechDraw::CenterLine::setExtend(), TechDraw::LineFormat::setLineNumber(), TechDraw::CenterLine::setRotate(), TechDraw::CenterLine::setShifts(), App::Color::setValue(), TechDraw::LineFormat::setVisible(), TechDraw::LineFormat::setWidth(), Gui::Command::updateActive(), and ZVALUE::VERTEX.
Referenced by TaskCenterLine().
enableTaskButtons()
void TaskCenterLine::enableTaskButtons (bool isEnabled)
Definition at line 505 of file TaskCenterLine.cpp.
getCenterColor()
QColor TaskCenterLine::getCenterColor () protected
Definition at line 521 of file TaskCenterLine.cpp.
References TechDrawGui::PreferencesGui::centerQColor().
Referenced by setUiPrimary().
getCenterWidth()
double TaskCenterLine::getCenterWidth () protected
Definition at line 511 of file TaskCenterLine.cpp.
References TechDraw::LineGroup::getDefaultWidth(), and TechDrawGui::QGIView::getViewProvider().
Referenced by setUiPrimary().
getCreateMode()
virtual bool TechDrawGui::TaskCenterLine::getCreateMode () const inline virtual
Definition at line 72 of file TaskCenterLine.h.
Referenced by reject().
getExtendBy()
double TaskCenterLine::getExtendBy () protected
Definition at line 526 of file TaskCenterLine.cpp.
Referenced by setUiPrimary().
reject()
bool TaskCenterLine::reject () virtual
Definition at line 546 of file TaskCenterLine.cpp.
References toolbit-attributes::doc, doCommand, getCreateMode(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::Command::Gui, Gui::Application::Instance, TechDraw::CenterLine::m_extendBy, TechDraw::CenterLine::m_format, TechDraw::CenterLine::m_hShift, TechDraw::CenterLine::m_mode, TechDraw::CenterLine::m_rotate, TechDraw::CenterLine::m_type, TechDraw::CenterLine::m_vShift, App::DocumentObject::recomputeFeature(), TechDraw::LineFormat::setColor(), TechDraw::LineFormat::setLineNumber(), TechDraw::LineFormat::setVisible(), and TechDraw::LineFormat::setWidth().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and TechDrawGui::TaskDlgCenterLine::reject().
saveButtons()
void TaskCenterLine::saveButtons (QPushButton * btnOK, QPushButton * btnCancel)
Definition at line 498 of file TaskCenterLine.cpp.
Referenced by TechDrawGui::TaskDlgCenterLine::modifyStandardButtons().
setCreateMode()
virtual void TechDrawGui::TaskCenterLine::setCreateMode (bool mode) inline virtual
Definition at line 71 of file TaskCenterLine.h.
setUiConnect()
void TaskCenterLine::setUiConnect () protected
Definition at line 143 of file TaskCenterLine.cpp.
References draftgeoutils.intersections::connect(), and ZVALUE::FACE.
Referenced by TaskCenterLine().
setUiEdit()
void TaskCenterLine::setUiEdit () protected
Definition at line 209 of file TaskCenterLine.cpp.
References ALIGNED, Base::Unit::Angle, App::Color::asValue(), TechDraw::LineFormat::getColor(), Base::UnitsApi::getDecimals(), App::DocumentObject::getNameInDocument(), TechDraw::LineFormat::getStyle(), TechDraw::LineFormat::getWidth(), HORIZONTAL, Base::Unit::Length, TechDrawGui::DrawGuiUtil::loadLineStyleChoices(), TechDraw::CenterLine::m_extendBy, TechDraw::CenterLine::m_format, TechDraw::CenterLine::m_hShift, TechDraw::CenterLine::m_mode, TechDraw::CenterLine::m_rotate, TechDraw::CenterLine::m_vShift, draftgeoutils.general::precision(), Base::Quantity::setUnit(), Base::Quantity::setValue(), and VERTICAL.
Referenced by TaskCenterLine().
setUiOrientation()
void TaskCenterLine::setUiOrientation (int orientation) protected
Definition at line 480 of file TaskCenterLine.cpp.
References HORIZONTAL, and VERTICAL.
Referenced by setUiPrimary(), and updateOrientation().
setUiPrimary()
void TaskCenterLine::setUiPrimary () protected
Definition at line 166 of file TaskCenterLine.cpp.
References Base::Unit::Angle, checkPathologicalEdges(), checkPathologicalVertices(), ZVALUE::EDGE, getCenterColor(), getCenterWidth(), Base::UnitsApi::getDecimals(), getExtendBy(), App::DocumentObject::getNameInDocument(), Base::Unit::Length, TechDrawGui::DrawGuiUtil::loadLineStyleChoices(), draftgeoutils.general::precision(), toolbit-attributes::s, setUiOrientation(), Base::Quantity::setUnit(), Base::Quantity::setValue(), and ZVALUE::VERTEX.
Referenced by TaskCenterLine().
updateOrientation()
void TaskCenterLine::updateOrientation () protected
Definition at line 448 of file TaskCenterLine.cpp.
References checkPathologicalEdges(), checkPathologicalVertices(), ZVALUE::EDGE, TechDraw::CenterLine::m_edges, TechDraw::CenterLine::m_mode, TechDraw::CenterLine::m_verts, App::DocumentObject::recomputeFeature(), setUiOrientation(), and ZVALUE::VERTEX.
updateTask()
void TaskCenterLine::updateTask ()
Definition at line 132 of file TaskCenterLine.cpp.
The documentation for this class was generated from the following files:
TaskCenterLine.h
TaskCenterLine.cpp