FreeCAD: ifc2x3.ifcfailureconnectioncondition Class Reference
ifc2x3.ifcfailureconnectioncondition Class Reference
Public Member Functions
def __init__ (self, inherited0__name, tensionfailurex, tensionfailurey, tensionfailurez, compressionfailurex, compressionfailurey, compressionfailurez)
def tensionfailurex ()
def tensionfailurey ()
def tensionfailurez ()
def compressionfailurex ()
def compressionfailurey ()
def compressionfailurez ()
Public Member Functions inherited from ifc2x3.ifcstructuralconnectioncondition
def __init__ (self, name)
def name ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
tensionfailurex
tensionfailurey
tensionfailurez
compressionfailurex
compressionfailurey
compressionfailurez
Public Attributes inherited from ifc2x3.ifcstructuralconnectioncondition
name
Detailed Description
Entity ifcfailureconnectioncondition definition.
:param tensionfailurex
:type tensionfailurex:ifcforcemeasure
:param tensionfailurey
:type tensionfailurey:ifcforcemeasure
:param tensionfailurez
:type tensionfailurez:ifcforcemeasure
:param compressionfailurex
:type compressionfailurex:ifcforcemeasure
:param compressionfailurey
:type compressionfailurey:ifcforcemeasure
:param compressionfailurez
:type compressionfailurez:ifcforcemeasure
Definition at line 8100 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcfailureconnectioncondition.__init__ (self, inherited0__name, tensionfailurex, tensionfailurey, tensionfailurez, compressionfailurex, compressionfailurey, compressionfailurez)
Definition at line 8121 of file ifc2x3.py.
Member Function Documentation
compressionfailurex()
def ifc2x3.ifcfailureconnectioncondition.compressionfailurex ()
Definition at line 8173 of file ifc2x3.py.
References ifc2x3.ifcfailureconnectioncondition._compressionfailurex, SCL.TypeChecker.check_type(), and ifc2x3.ifcfailureconnectioncondition.compressionfailurex.
compressionfailurey()
def ifc2x3.ifcfailureconnectioncondition.compressionfailurey ()
Definition at line 8187 of file ifc2x3.py.
References ifc2x3.ifcfailureconnectioncondition._compressionfailurey, SCL.TypeChecker.check_type(), and ifc2x3.ifcfailureconnectioncondition.compressionfailurey.
compressionfailurez()
def ifc2x3.ifcfailureconnectioncondition.compressionfailurez ()
Definition at line 8201 of file ifc2x3.py.
References ifc2x3.ifcfailureconnectioncondition._compressionfailurez, SCL.TypeChecker.check_type(), and ifc2x3.ifcfailureconnectioncondition.compressionfailurez.
tensionfailurex()
def ifc2x3.ifcfailureconnectioncondition.tensionfailurex ()
Definition at line 8131 of file ifc2x3.py.
References ifc2x3.ifcfailureconnectioncondition._tensionfailurex, SCL.TypeChecker.check_type(), and ifc2x3.ifcfailureconnectioncondition.tensionfailurex.
tensionfailurey()
def ifc2x3.ifcfailureconnectioncondition.tensionfailurey ()
Definition at line 8145 of file ifc2x3.py.
References ifc2x3.ifcfailureconnectioncondition._tensionfailurey, SCL.TypeChecker.check_type(), and ifc2x3.ifcfailureconnectioncondition.tensionfailurey.
tensionfailurez()
def ifc2x3.ifcfailureconnectioncondition.tensionfailurez ()
Definition at line 8159 of file ifc2x3.py.
References ifc2x3.ifcfailureconnectioncondition._tensionfailurez, SCL.TypeChecker.check_type(), and ifc2x3.ifcfailureconnectioncondition.tensionfailurez.
Member Data Documentation
compressionfailurex
ifc2x3.ifcfailureconnectioncondition.compressionfailurex
Definition at line 8126 of file ifc2x3.py.
Referenced by ifc2x3.ifcfailureconnectioncondition.compressionfailurex().
compressionfailurey
ifc2x3.ifcfailureconnectioncondition.compressionfailurey
Definition at line 8127 of file ifc2x3.py.
Referenced by ifc2x3.ifcfailureconnectioncondition.compressionfailurey().
compressionfailurez
ifc2x3.ifcfailureconnectioncondition.compressionfailurez
Definition at line 8128 of file ifc2x3.py.
Referenced by ifc2x3.ifcfailureconnectioncondition.compressionfailurez().
tensionfailurex
ifc2x3.ifcfailureconnectioncondition.tensionfailurex
Definition at line 8123 of file ifc2x3.py.
Referenced by ifc2x3.ifcfailureconnectioncondition.tensionfailurex().
tensionfailurey
ifc2x3.ifcfailureconnectioncondition.tensionfailurey
Definition at line 8124 of file ifc2x3.py.
Referenced by ifc2x3.ifcfailureconnectioncondition.tensionfailurey().
tensionfailurez
ifc2x3.ifcfailureconnectioncondition.tensionfailurez
Definition at line 8125 of file ifc2x3.py.
Referenced by ifc2x3.ifcfailureconnectioncondition.tensionfailurez().
The documentation for this class was generated from the following file:
ifc2x3.py