FreeCAD: Mesh::MeshObject Class Reference
Mesh::MeshObject Class Reference
#include <Mesh.h>
Classes
class const_facet_iterator
class const_point_iterator
Public Types
enum GeometryType { PLANE, CYLINDER, SPHERE }
enum CutType { INNER, OUTER }
using TFacePair = std::pair< FacetIndex, FacetIndex >
using TFacePairs = std::vector< TFacePair >
using TPlane = std::pair< Base::Vector3f, Base::Vector3f >
using TPolylines = std::list< std::vector< Base::Vector3f > >
using TRay = std::pair< Base::Vector3d, Base::Vector3d >
using TFaceSection = std::pair< FacetIndex, Base::Vector3d >
Public Member Functions
MeshObject ()
MeshObject (const MeshCore::MeshKernel &Kernel)
MeshObject (const MeshCore::MeshKernel &Kernel, const Base::Matrix4D &Mtrx)
MeshObject (const MeshObject &)
MeshObject (MeshObject &&)
~MeshObject () override
MeshObject & operator= (const MeshObject &)
MeshObject & operator= (MeshObject &&)
Subelement management
std::vector< const char * > getElementTypes () const override
unsigned long countSubElements (const char *Type) const override
Data::Segment * getSubElement (const char *Type, unsigned long) const override
get the subelement by type and number
void getFacesFromSubElement (const Data::Segment *, std::vector< Base::Vector3d > &Points, std::vector< Base::Vector3d > &PointNormals, std::vector< Facet > &faces) const override
void setTransform (const Base::Matrix4D &rclTrf) override
Base::Matrix4D getTransform () const override
void transformGeometry (const Base::Matrix4D &rclMat) override
Applies a transformation on the real geometric data type.
void swap (MeshCore::MeshKernel &Kernel)
void swap (MeshObject &mesh)
Querying
std::string representation () const
std::string topologyInfo () const
unsigned long countPoints () const
unsigned long countFacets () const
unsigned long countEdges () const
unsigned long countSegments () const
bool isSolid () const
Base::Vector3d getPoint (PointIndex) const
MeshPoint getMeshPoint (PointIndex) const
Mesh::Facet getMeshFacet (FacetIndex) const
double getSurface () const
double getVolume () const
void getPoints (std::vector< Base::Vector3d > &Points, std::vector< Base::Vector3d > &Normals, double Accuracy, uint16_t flags=0) const override
void getFaces (std::vector< Base::Vector3d > &Points, std::vector< Facet > &Topo, double Accuracy, uint16_t flags=0) const override
std::vector< PointIndex > getPointsFromFacets (const std::vector< FacetIndex > &facets) const
bool nearestFacetOnRay (const TRay &ray, double maxAngle, TFaceSection &output) const
std::vector< TFaceSection > foraminate (const TRay &ray, double maxAngle) const
void setKernel (const MeshCore::MeshKernel &m)
MeshCore::MeshKernel & getKernel ()
const MeshCore::MeshKernel & getKernel () const
Base::BoundBox3d getBoundBox () const override
Get the bound box.
bool getCenterOfGravity (Base::Vector3d &center) const override
I/O
unsigned int getMemSize () const override
void Save (Base::Writer &writer) const override
void SaveDocFile (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void RestoreDocFile (Base::Reader &reader) override
void save (const char *file, MeshCore::MeshIO::Format f=MeshCore::MeshIO::Undefined, const MeshCore::Material *mat=nullptr, const char *objectname=nullptr) const
void save (std::ostream &, MeshCore::MeshIO::Format f, const MeshCore::Material *mat=nullptr, const char *objectname=nullptr) const
bool load (const char *file, MeshCore::Material *mat=nullptr)
bool load (std::istream &, MeshCore::MeshIO::Format f, MeshCore::Material *mat=nullptr)
void save (std::ostream &) const
void load (std::istream &)
void writeInventor (std::ostream &str, float creaseangle=0.0F) const
Manipulation
void addFacet (const MeshCore::MeshGeomFacet &facet)
void addFacets (const std::vector< MeshCore::MeshGeomFacet > &facets)
void addFacets (const std::vector< MeshCore::MeshFacet > &facets, bool checkManifolds)
void addFacets (const std::vector< MeshCore::MeshFacet > &facets, const std::vector< Base::Vector3f > &points, bool checkManifolds)
void addFacets (const std::vector< Data::ComplexGeoData::Facet > &facets, const std::vector< Base::Vector3d > &points, bool checkManifolds)
void setFacets (const std::vector< MeshCore::MeshGeomFacet > &facets)
void setFacets (const std::vector< Data::ComplexGeoData::Facet > &facets, const std::vector< Base::Vector3d > &points)
void addMesh (const MeshObject &)
void addMesh (const MeshCore::MeshKernel &)
void deleteFacets (const std::vector< FacetIndex > &removeIndices)
void deletePoints (const std::vector< PointIndex > &removeIndices)
std::vector< std::vector< FacetIndex > > getComponents () const
unsigned long countComponents () const
void removeComponents (unsigned long)
unsigned long getPointDegree (const std::vector< FacetIndex > &indices, std::vector< PointIndex > &point_degree) const
void fillupHoles (unsigned long, int, MeshCore::AbstractPolygonTriangulator &)
void offset (float fSize)
void offsetSpecial2 (float fSize)
void offsetSpecial (float fSize, float zmax, float zmin)
void clear ()
clears the Mesh
void transformToEigenSystem ()
Base::Matrix4D getEigenSystem (Base::Vector3d &v) const
void movePoint (PointIndex, const Base::Vector3d &v)
void setPoint (PointIndex index, const Base::Vector3d &p)
void smooth (int iterations, float d_max)
void decimate (float fTolerance, float fReduction)
void decimate (int targetSize)
Base::Vector3d getPointNormal (PointIndex) const
std::vector< Base::Vector3d > getPointNormals () const
void crossSections (const std::vector< TPlane > &, std::vector< TPolylines > &sections, float fMinEps=1.0e-2F, bool bConnectPolygons=false) const
void cut (const Base::Polygon2d &polygon, const Base::ViewProjMethod &proj, CutType)
void trim (const Base::Polygon2d &polygon, const Base::ViewProjMethod &proj, CutType)
void trimByPlane (const Base::Vector3f &base, const Base::Vector3f &normal)
Selection
void deleteSelectedFacets ()
void deleteSelectedPoints ()
void addFacetsToSelection (const std::vector< FacetIndex > &) const
void addPointsToSelection (const std::vector< PointIndex > &) const
void removeFacetsFromSelection (const std::vector< FacetIndex > &) const
void removePointsFromSelection (const std::vector< PointIndex > &) const
unsigned long countSelectedFacets () const
bool hasSelectedFacets () const
unsigned long countSelectedPoints () const
bool hasSelectedPoints () const
void getFacetsFromSelection (std::vector< FacetIndex > &) const
void getPointsFromSelection (std::vector< PointIndex > &) const
void clearFacetSelection () const
void clearPointSelection () const
Boolean operations
MeshObject * unite (const MeshObject &) const
MeshObject * intersect (const MeshObject &) const
MeshObject * subtract (const MeshObject &) const
MeshObject * inner (const MeshObject &) const
MeshObject * outer (const MeshObject &) const
std::vector< std::vector< Base::Vector3f > > section (const MeshObject &, bool connectLines, float fMinDist) const
Topological operations
void refine ()
void removeNeedles (float)
void optimizeTopology (float)
void optimizeEdges ()
void splitEdges ()
void splitEdge (FacetIndex, FacetIndex, const Base::Vector3f &)
void splitFacet (FacetIndex, const Base::Vector3f &, const Base::Vector3f &)
void swapEdge (FacetIndex, FacetIndex)
void collapseEdge (FacetIndex, FacetIndex)
void collapseFacet (FacetIndex)
void collapseFacets (const std::vector< FacetIndex > &)
void insertVertex (FacetIndex, const Base::Vector3f &v)
void snapVertex (FacetIndex, const Base::Vector3f &v)
Mesh validation
unsigned long countNonUniformOrientedFacets () const
void flipNormals ()
void harmonizeNormals ()
void validateIndices ()
void validateCaps (float fMaxAngle, float fSplitFactor)
void validateDeformations (float fMaxAngle, float fEps)
void validateDegenerations (float fEps)
void removeDuplicatedPoints ()
void removeDuplicatedFacets ()
bool hasNonManifolds () const
bool hasInvalidNeighbourhood () const
bool hasPointsOutOfRange () const
bool hasFacetsOutOfRange () const
bool hasCorruptedFacets () const
void removeNonManifolds ()
void removeNonManifoldPoints ()
bool hasSelfIntersections () const
TFacePairs getSelfIntersections () const
std::vector< Base::Line3d > getSelfIntersections (const TFacePairs &) const
void removeSelfIntersections ()
void removeSelfIntersections (const std::vector< FacetIndex > &)
void removeFoldsOnSurface ()
void removeFullBoundaryFacets ()
bool hasInvalidPoints () const
void removeInvalidPoints ()
void mergeFacets ()
bool hasPointsOnEdge () const
void removePointsOnEdge (bool fillBoundary)
Mesh segments
void addSegment (const Segment &)
void addSegment (const std::vector< FacetIndex > &)
const Segment & getSegment (unsigned long) const
Segment & getSegment (unsigned long)
MeshObject * meshFromSegment (const std::vector< FacetIndex > &) const
std::vector< Segment > getSegmentsOfType (GeometryType, float dev, unsigned long minFacets) const
Public Member Functions inherited from Data::ComplexGeoData
ComplexGeoData ()
Constructor.
~ComplexGeoData () override=default
Destructor.
void applyTransform (const Base::Matrix4D &rclTrf)
void applyTranslation (const Base::Vector3d &)
void applyRotation (const Base::Rotation &)
void setPlacement (const Base::Placement &rclPlacement)
Base::Placement getPlacement () const
virtual Segment * getSubElementByName (const char *Name) const
get sub-element by combined name
virtual void getLinesFromSubElement (const Segment *, std::vector< Base::Vector3d > &Points, std::vector< Line > &lines) const
virtual double getAccuracy () const
Get the standard accuracy to be used with getPoints, getLines or getFaces.
virtual Base::Vector3d getPointFromLineIntersection (const Base::Vector3f &base, const Base::Vector3f &dir) const
virtual void getLines (std::vector< Base::Vector3d > &Points, std::vector< Line > &lines, double Accuracy, uint16_t flags=0) const
virtual std::optional< Base::Vector3d > centerOfGravity () const
IndexedName getIndexedName (const MappedName &name, ElementIDRefs *sid=nullptr) const
MappedName getMappedName (const IndexedName &element, bool allowUnmapped=false, ElementIDRefs *sid=nullptr) const
MappedElement getElementName (const char *name, ElementIDRefs *sid=nullptr, bool copy=false) const
MappedName setElementName (const IndexedName &element, const MappedName &name, long masterTag, const ElementIDRefs *sid=nullptr, bool overwrite=false)
bool hasElementMap ()
std::vector< std::pair< MappedName, ElementIDRefs > > getElementMappedNames (const IndexedName &element, bool needUnmapped=false) const
void hashChildMaps ()
Hash the child element map postfixes to shorten element name from hierarchical maps.
bool hasChildElementMap () const
Check if there is child element map.
virtual void reTagElementMap (long tag, App::StringHasherRef hasher, const char *postfix=nullptr)
Append the Tag (if and only if it is non zero) into the element map.
long getElementHistory (const MappedName &name, MappedName *original=nullptr, std::vector< MappedName > *history=nullptr) const
void setMappedChildElements (const std::vector< Data::ElementMap::MappedChildElements > &children)
std::vector< Data::ElementMap::MappedChildElements > getMappedChildElements () const
char elementType (const Data::MappedName &) const
char elementType (const Data::IndexedName &) const
char elementType (const char *name) const
virtual ElementMapPtr resetElementMap (ElementMapPtr elementMap=ElementMapPtr())
std::vector< MappedElement > getElementMap () const
Get the entire element map.
void setElementMap (const std::vector< MappedElement > &elements)
Set the entire element map.
size_t getElementMapSize (bool flush=true) const
Get the current element map size.
virtual std::vector< IndexedName > getHigherElements (const char *name, bool silent=false) const
Return the higher level element names of the given element.
virtual std::string getElementMapVersion () const
Return the current element map version.
virtual bool checkElementMapVersion (const char *ver) const
Return true to signal element map version change.
void traceElement (const MappedName &name, TraceCallback cb) const
virtual void flushElementMap () const
void setPersistenceFileName (const char *name) const
virtual void beforeSave () const
bool isRestoreFailed () const
void resetRestoreFailure () const
void dumpElementMap (std::ostream &stream) const
const std::string dumpElementMap () const
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from Base::Handled
Handled ()
virtual ~Handled ()
void ref () const
void unref () const
int unrefNoDelete () const
int getRefCount () const
Handled & operator= (const Handled &)
Handled (const Handled &)=delete
Handled (Handled &&)=delete
Handled & operator= (Handled &&)=delete
Static Public Member Functions
Primitives
static MeshObject * createMeshFromList (Py::List &list)
static MeshObject * createSphere (float, int)
static MeshObject * createEllipsoid (float, float, int)
static MeshObject * createCylinder (float, float, int, float, int)
static MeshObject * createCone (float, float, float, int, float, int)
static MeshObject * createTorus (float, float, int)
static MeshObject * createCube (float, float, float)
static MeshObject * createCube (float, float, float, float)
static MeshObject * createCube (const Base::BoundBox3d &)
Static Public Member Functions inherited from Data::ComplexGeoData
static std::pair< std::string, unsigned long > getTypeAndIndex (const char *Name)
static const std::string & elementMapPrefix ()
static bool isElementName (const char *subName)
Check if the given sub-name only contains an element name.
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Iterator
using const_segment_iterator = std::vector< Segment >::const_iterator
class Segment
const_point_iterator points_begin () const
const_point_iterator points_end () const
const_facet_iterator facets_begin () const
const_facet_iterator facets_end () const
const_segment_iterator segments_begin () const
const_segment_iterator segments_end () const
Additional Inherited Members
Public Attributes inherited from Data::ComplexGeoData
long Tag {0}
App::StringHasherRef Hasher
String hasher for element name shortening.
Protected Member Functions inherited from Data::ComplexGeoData
Base::Vector3d transformPointToOutside (const Base::Vector3f &vec) const
from local to outside
template<typename Vec >
std::vector< Base::Vector3d > transformPointsToOutside (const std::vector< Vec > &input) const
from local to outside
Base::Vector3d transformVectorToOutside (const Base::Vector3f &vec) const
template<typename Vec >
std::vector< Base::Vector3d > transformVectorsToOutside (const std::vector< Vec > &input) const
Base::Vector3f transformPointToInside (const Base::Vector3d &vec) const
from local to inside
void restoreStream (std::istream &stream, std::size_t count)
void readElements (Base::XMLReader &reader, size_t count)
Base::Vector3d transformToOutside (const Base::Vector3f &vec) const
from local to outside
Base::Vector3f transformToInside (const Base::Vector3d &vec) const
from local to inside
ElementMapPtr elementMap (bool flush=true) const
ElementMapPtr ensureElementMap (bool flush=true)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Data::ComplexGeoData
std::string _persistenceName
bool _restoreFailed = false
Detailed Description
The MeshObject class provides an interface for the underlying MeshKernel class and most of its algorithm on it.
Note
Each instance of MeshObject has its own instance of a MeshKernel so it's not possible that several instances of MeshObject manage one instance of MeshKernel.
Definition at line 87 of file Mesh.h.
Member Typedef Documentation
const_segment_iterator
using Mesh::MeshObject::const_segment_iterator = std::vector<Segment>::const_iterator
Definition at line 448 of file Mesh.h.
TFacePair
using Mesh::MeshObject::TFacePair = std::pair<FacetIndex, FacetIndex>
Definition at line 104 of file Mesh.h.
TFacePairs
using Mesh::MeshObject::TFacePairs = std::vector<TFacePair>
Definition at line 105 of file Mesh.h.
TFaceSection
using Mesh::MeshObject::TFaceSection = std::pair<FacetIndex, Base::Vector3d>
Definition at line 111 of file Mesh.h.
TPlane
using Mesh::MeshObject::TPlane = std::pair<Base::Vector3f, Base::Vector3f>
Definition at line 108 of file Mesh.h.
TPolylines
using Mesh::MeshObject::TPolylines = std::list<std::vector<Base::Vector3f> >
Definition at line 109 of file Mesh.h.
TRay
using Mesh::MeshObject::TRay = std::pair<Base::Vector3d, Base::Vector3d>
Definition at line 110 of file Mesh.h.
Member Enumeration Documentation
CutType
enum Mesh::MeshObject::CutType
Enumerator
INNER
OUTER
Definition at line 98 of file Mesh.h.
GeometryType
enum Mesh::MeshObject::GeometryType
Enumerator
PLANE
CYLINDER
SPHERE
Definition at line 92 of file Mesh.h.
Constructor & Destructor Documentation
MeshObject() [1/5]
MeshObject::MeshObject () default
Referenced by getSubElement(), inner(), intersect(), meshFromSegment(), outer(), subtract(), and unite().
MeshObject() [2/5]
MeshObject::MeshObject (const MeshCore::MeshKernel & Kernel) explicit
Definition at line 66 of file Mesh.cpp.
MeshObject() [3/5]
MeshObject::MeshObject (const MeshCore::MeshKernel & Kernel, const Base::Matrix4D & Mtrx) explicit
Definition at line 72 of file Mesh.cpp.
MeshObject() [4/5]
MeshObject::MeshObject (const MeshObject & mesh)
Definition at line 79 of file Mesh.cpp.
References Mesh2Shape::mesh.
MeshObject() [5/5]
MeshObject::MeshObject (MeshObject && mesh)
Definition at line 87 of file Mesh.cpp.
References Mesh2Shape::mesh.
~MeshObject()
MeshObject::~MeshObject () override default
Member Function Documentation
addFacet()
void MeshObject::addFacet (const MeshCore::MeshGeomFacet & facet)
Definition at line 574 of file Mesh.cpp.
References MeshCore::MeshKernel::AddFacet().
addFacets() [1/4]
void MeshObject::addFacets (const std::vector< Data::ComplexGeoData::Facet > & facets, const std::vector< Base::Vector3d > & points, bool checkManifolds)
Definition at line 596 of file Mesh.cpp.
References MeshCore::MeshKernel::AddFacets(), SCL.SimpleDataTypes::f, and buildPsets::p.
addFacets() [2/4]
void MeshObject::addFacets (const std::vector< MeshCore::MeshFacet > & facets, bool checkManifolds)
Definition at line 584 of file Mesh.cpp.
References MeshCore::MeshKernel::AddFacets().
addFacets() [3/4]
void MeshObject::addFacets (const std::vector< MeshCore::MeshFacet > & facets, const std::vector< Base::Vector3f > & points, bool checkManifolds)
Definition at line 589 of file Mesh.cpp.
References MeshCore::MeshKernel::AddFacets().
addFacets() [4/4]
void MeshObject::addFacets (const std::vector< MeshCore::MeshGeomFacet > & facets)
Definition at line 579 of file Mesh.cpp.
References MeshCore::MeshKernel::AddFacets().
Referenced by MeshGui::ViewProviderMesh::fillHole(), and cStock::Tessellate().
addFacetsToSelection()
void MeshObject::addFacetsToSelection (const std::vector< FacetIndex > & inds) const
Definition at line 740 of file Mesh.cpp.
References MeshCore::MeshFacet::SELECTED, and MeshCore::MeshAlgorithm::SetFacetsFlag().
Referenced by MeshGui::ViewProviderMesh::addSelection(), MeshGui::ViewProviderMesh::selectArea(), MeshGui::ViewProviderMesh::selectComponent(), MeshGui::ViewProviderMesh::selectFacet(), and MeshGui::ViewProviderMesh::setSelection().
addMesh() [1/2]
void MeshObject::addMesh (const MeshCore::MeshKernel & kernel)
Combines two independent mesh objects.
Note
The mesh object we want to add must not overlap or intersect with this mesh object.
Definition at line 653 of file Mesh.cpp.
References MeshCore::MeshKernel::Merge().
addMesh() [2/2]
void MeshObject::addMesh (const MeshObject & mesh)
Combines two independent mesh objects.
Note
The mesh object we want to add must not overlap or intersect with this mesh object.
Definition at line 648 of file Mesh.cpp.
References MeshCore::MeshKernel::Merge(), and Mesh2Shape::mesh.
Referenced by Mesh::MergeExporter::addMesh().
addPointsToSelection()
void MeshObject::addPointsToSelection (const std::vector< PointIndex > & inds) const
Definition at line 745 of file Mesh.cpp.
References MeshCore::MeshPoint::SELECTED, and MeshCore::MeshAlgorithm::SetPointsFlag().
addSegment() [1/2]
void MeshObject::addSegment (const Segment & s)
Definition at line 2032 of file Mesh.cpp.
References toolbit-attributes::s.
Referenced by Mesh::MergeExporter::addMesh(), src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::addSegments(), MeshPart::BrepMesh::create(), and MeshGui::ViewProviderMesh::segmentMesh().
addSegment() [2/2]
void MeshObject::addSegment (const std::vector< FacetIndex > & inds)
Definition at line 2041 of file Mesh.cpp.
References MeshCore::MeshKernel::CountFacets().
Referenced by src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::addSegments().
clear()
void MeshObject::clear ()
clears the Mesh
Definition at line 1035 of file Mesh.cpp.
References MeshCore::MeshKernel::Clear(), and setTransform().
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), and src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__().
clearFacetSelection()
void MeshObject::clearFacetSelection () const
Definition at line 730 of file Mesh.cpp.
References MeshCore::MeshAlgorithm::ResetFacetFlag(), and MeshCore::MeshFacet::SELECTED.
Referenced by MeshGui::ViewProviderMesh::clearSelection(), ReverseEngineeringGui::SegmentationManual::createSegment(), MeshGui::ViewProviderMesh::deleteSelection(), and MeshGui::ViewProviderMesh::setSelection().
clearPointSelection()
void MeshObject::clearPointSelection () const
Definition at line 735 of file Mesh.cpp.
References MeshCore::MeshAlgorithm::ResetPointFlag(), and MeshCore::MeshPoint::SELECTED.
collapseEdge()
void MeshObject::collapseEdge (FacetIndex facet, FacetIndex neighbour)
Definition at line 1445 of file Mesh.cpp.
References MeshCore::MeshTopoAlgorithm::CollapseEdge().
collapseFacet()
void MeshObject::collapseFacet (FacetIndex facet)
Definition at line 1456 of file Mesh.cpp.
References MeshCore::MeshTopoAlgorithm::CollapseFacet().
collapseFacets()
void MeshObject::collapseFacets (const std::vector< FacetIndex > & facets)
Definition at line 1466 of file Mesh.cpp.
References MeshCore::MeshTopoAlgorithm::CollapseFacet().
countComponents()
unsigned long MeshObject::countComponents () const
Definition at line 885 of file Mesh.cpp.
References MeshCore::MeshComponents::OverEdge, MeshCore::MeshComponents::SearchForComponents(), and segments.
countEdges()
unsigned long MeshObject::countEdges () const
Definition at line 291 of file Mesh.cpp.
References MeshCore::MeshKernel::CountEdges().
countFacets()
unsigned long MeshObject::countFacets () const
Definition at line 286 of file Mesh.cpp.
References MeshCore::MeshKernel::CountFacets().
Referenced by MeshPartGui::Tessellation::addFaceColors(), Mesh::MergeExporter::addMesh(), MeshGui::ViewProviderMesh::canHighlightColors(), MeshGui::ViewProviderMesh::deselectFacet(), MeshGui::ViewProviderMesh::highlightColors(), MeshGui::ViewProviderMesh::highlightComponents(), MeshGui::ViewProviderMesh::highlightSegments(), MeshGui::ViewProviderMesh::highlightSelection(), MeshGui::ViewProviderMesh::removeFacets(), and MeshGui::ViewProviderMesh::selectFacet().
countNonUniformOrientedFacets()
unsigned long MeshObject::countNonUniformOrientedFacets () const
Definition at line 1488 of file Mesh.cpp.
References MeshCore::MeshEvalOrientation::GetIndices().
countPoints()
unsigned long MeshObject::countPoints () const
Definition at line 281 of file Mesh.cpp.
References MeshCore::MeshKernel::CountPoints().
Referenced by MeshGui::ViewProviderMesh::canHighlightColors(), MeshGui::ViewProviderMesh::highlightColors(), MeshInfoWatcher::onSelectionChanged(), MeshGui::ViewProviderMesh::removeFacets(), and MeshGui::ViewProviderMeshCurvature::updateData().
countSegments()
unsigned long MeshObject::countSegments () const
Definition at line 296 of file Mesh.cpp.
Referenced by MeshPartGui::Tessellation::addFaceColors(), countSubElements(), getSubElement(), and MeshGui::ViewProviderMesh::highlightSegments().
countSelectedFacets()
unsigned long MeshObject::countSelectedFacets () const
Definition at line 770 of file Mesh.cpp.
References MeshCore::MeshAlgorithm::CountFacetFlag(), and MeshCore::MeshFacet::SELECTED.
Referenced by hasSelectedFacets().
countSelectedPoints()
unsigned long MeshObject::countSelectedPoints () const
Definition at line 780 of file Mesh.cpp.
References MeshCore::MeshAlgorithm::CountPointFlag(), and MeshCore::MeshPoint::SELECTED.
Referenced by hasSelectedPoints().
countSubElements()
unsigned long MeshObject::countSubElements (const char * Type) const override virtual
Implements Data::ComplexGeoData.
Definition at line 106 of file Mesh.cpp.
References countSegments().
createCone()
MeshObject * MeshObject::createCone (float radius1, float radius2, float len, int closed, float edgelen, int sampling) static
Definition at line 1891 of file Mesh.cpp.
References toolbit-attributes::args, createMeshFromList(), Path.Base.SetupSheet::dict, SCL.SimpleDataTypes::e, and src.Mod.PartDesign.fcgear.svggear::module.
Referenced by Mesh::Cone::execute().
createCube() [1/3]
MeshObject * MeshObject::createCube (const Base::BoundBox3d & bbox) static
Definition at line 2000 of file Mesh.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::MeshGeomFacet::CalcNormal(), Base::BoundBox3< Precision >::CalcPoint(), and Mesh2Shape::mesh.
createCube() [2/3]
MeshObject * MeshObject::createCube (float length, float width, float height) static
Definition at line 1949 of file Mesh.cpp.
References toolbit-attributes::args, createMeshFromList(), Path.Base.SetupSheet::dict, SCL.SimpleDataTypes::e, and src.Mod.PartDesign.fcgear.svggear::module.
Referenced by Mesh::Cube::execute().
createCube() [3/3]
MeshObject * MeshObject::createCube (float length, float width, float height, float edgelen) static
Definition at line 1974 of file Mesh.cpp.
References toolbit-attributes::args, createMeshFromList(), Path.Base.SetupSheet::dict, SCL.SimpleDataTypes::e, and src.Mod.PartDesign.fcgear.svggear::module.
createCylinder()
MeshObject * MeshObject::createCylinder (float radius, float length, int closed, float edgelen, int sampling) static
Definition at line 1864 of file Mesh.cpp.
References toolbit-attributes::args, createMeshFromList(), Path.Base.SetupSheet::dict, SCL.SimpleDataTypes::e, and src.Mod.PartDesign.fcgear.svggear::module.
Referenced by Mesh::Cylinder::execute().
createEllipsoid()
MeshObject * MeshObject::createEllipsoid (float radius1, float radius2, int sampling) static
Definition at line 1838 of file Mesh.cpp.
References toolbit-attributes::args, createMeshFromList(), Path.Base.SetupSheet::dict, SCL.SimpleDataTypes::e, and src.Mod.PartDesign.fcgear.svggear::module.
Referenced by Mesh::Ellipsoid::execute().
createMeshFromList()
MeshObject * MeshObject::createMeshFromList (Py::List & list) static
Definition at line 1789 of file Mesh.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::MeshGeomFacet::CalcNormal(), SplineSurface::i, and Mesh2Shape::mesh.
Referenced by createCone(), createCube(), createCylinder(), createEllipsoid(), createSphere(), createTorus(), and Mesh::PropertyMeshKernel::setPyObject().
createSphere()
MeshObject * MeshObject::createSphere (float radius, int sampling) static
Definition at line 1814 of file Mesh.cpp.
References toolbit-attributes::args, createMeshFromList(), Path.Base.SetupSheet::dict, SCL.SimpleDataTypes::e, and src.Mod.PartDesign.fcgear.svggear::module.
Referenced by Mesh::Sphere::execute().
createTorus()
MeshObject * MeshObject::createTorus (float radius1, float radius2, int sampling) static
Definition at line 1924 of file Mesh.cpp.
References toolbit-attributes::args, createMeshFromList(), Path.Base.SetupSheet::dict, SCL.SimpleDataTypes::e, and src.Mod.PartDesign.fcgear.svggear::module.
Referenced by Mesh::Torus::execute().
crossSections()
void MeshObject::crossSections (const std::vector< TPlane > & planes, std::vector< TPolylines > & sections, float fMinEps = 1.0e-2F, bool bConnectPolygons = false) const
Definition at line 1110 of file Mesh.cpp.
References MeshCore::MeshAlgorithm::CutWithPlane(), Plot::grid(), WorkingPlane::plane, and MeshCore::MeshKernel::Transform().
cut()
void MeshObject::cut (const Base::Polygon2d & polygon, const Base::ViewProjMethod & proj, MeshObject::CutType type)
Definition at line 1127 of file Mesh.cpp.
References ArchCommands::check(), MeshCore::MeshAlgorithm::CheckFacets(), deleteFacets(), getTransform(), INNER, inner(), OUTER, MeshCore::MeshKernel::Transform(), and Path.Post.scripts.grbl_post::type.
decimate() [1/2]
void MeshObject::decimate (float fTolerance, float fReduction)
Definition at line 1079 of file Mesh.cpp.
References MeshCore::MeshSimplify::simplify().
decimate() [2/2]
void MeshObject::decimate (int targetSize)
Definition at line 1085 of file Mesh.cpp.
References MeshCore::MeshSimplify::simplify().
deleteFacets()
void MeshObject::deleteFacets (const std::vector< FacetIndex > & removeIndices)
Definition at line 658 of file Mesh.cpp.
References MeshCore::MeshKernel::DeleteFacets().
Referenced by ReverseEngineeringGui::SegmentationManual::createSegment(), cut(), deleteSelectedFacets(), MeshGui::ViewProviderMesh::removeFacets(), removeFoldsOnSurface(), removeFullBoundaryFacets(), removeNonManifoldPoints(), removeSelfIntersections(), trim(), and trimByPlane().
deletePoints()
void MeshObject::deletePoints (const std::vector< PointIndex > & removeIndices)
Definition at line 667 of file Mesh.cpp.
References MeshCore::MeshKernel::DeletePoints().
Referenced by deleteSelectedPoints(), and removeInvalidPoints().
deleteSelectedFacets()
void MeshObject::deleteSelectedFacets ()
Definition at line 716 of file Mesh.cpp.
References deleteFacets(), MeshCore::MeshAlgorithm::GetFacetsFlag(), and MeshCore::MeshFacet::SELECTED.
deleteSelectedPoints()
void MeshObject::deleteSelectedPoints ()
Definition at line 723 of file Mesh.cpp.
References deletePoints(), MeshCore::MeshAlgorithm::GetPointsFlag(), and MeshCore::MeshPoint::SELECTED.
facets_begin()
const_facet_iterator Mesh::MeshObject::facets_begin () const inline
Definition at line 439 of file Mesh.h.
facets_end()
const_facet_iterator Mesh::MeshObject::facets_end () const inline
Definition at line 443 of file Mesh.h.
fillupHoles()
void MeshObject::fillupHoles (unsigned long length, int level, MeshCore::AbstractPolygonTriangulator & cTria)
Definition at line 928 of file Mesh.cpp.
References MeshCore::MeshTopoAlgorithm::FillupHoles(), and level().
flipNormals()
void MeshObject::flipNormals ()
Definition at line 1495 of file Mesh.cpp.
References MeshCore::MeshTopoAlgorithm::FlipNormals().
foraminate()
std::vector< MeshObject::TFaceSection > MeshObject::foraminate (const TRay & ray, double maxAngle) const
Definition at line 823 of file Mesh.cpp.
References MeshCore::MeshFacetIterator::Begin(), MeshCore::MeshGeomFacet::Foraminate(), getKernel(), Data::ComplexGeoData::getPlacement(), src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::inv(), Base::Placement::inverse(), MeshCore::MeshFacetIterator::More(), Base::Placement::multVec(), MeshCore::MeshFacetIterator::Next(), and section().
getBoundBox()
Base::BoundBox3d MeshObject::getBoundBox () const override virtual
Get the bound box.
Implements Data::ComplexGeoData.
Definition at line 175 of file Mesh.cpp.
References Base::BoundBox3< Precision >::Add(), Base::BoundBox3< Precision >::CalcPoint(), MeshCore::MeshKernel::GetBoundBox(), SplineSurface::i, Base::BoundBox3< Precision >::IsValid(), MeshCore::MeshKernel::RecalcBoundBox(), and Data::ComplexGeoData::transformPointToOutside().
getCenterOfGravity()
bool MeshObject::getCenterOfGravity (Base::Vector3d & center) const override virtual
Get the center of gravity If this method is implemented then true is returned and the center of gravity. The default implementation only returns false.
Reimplemented from Data::ComplexGeoData.
Definition at line 190 of file Mesh.cpp.
References exportCSG::center(), MeshCore::MeshAlgorithm::GetGravityPoint(), and Data::ComplexGeoData::transformPointToOutside().
getComponents()
std::vector< std::vector< FacetIndex > > MeshObject::getComponents () const
Definition at line 877 of file Mesh.cpp.
References MeshCore::MeshComponents::OverEdge, MeshCore::MeshComponents::SearchForComponents(), and segments.
Referenced by MeshGui::ViewProviderMesh::highlightComponents().
getEigenSystem()
Base::Matrix4D MeshObject::getEigenSystem (Base::Vector3d & v) const
Definition at line 1049 of file Mesh.cpp.
References MeshCore::MeshEigensystem::Evaluate(), MeshCore::MeshEigensystem::GetBoundings(), MeshCore::MeshEigensystem::Transform(), TestSpreadsheet::v, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
getElementTypes()
std::vector< const char * > MeshObject::getElementTypes () const override virtual
Sub type list List of different subelement types its NOT a list of the subelements itself
Implements Data::ComplexGeoData.
Definition at line 97 of file Mesh.cpp.
getFaces()
void MeshObject::getFaces (std::vector< Base::Vector3d > & Points, std::vector< Facet > & faces, double Accuracy, uint16_t flags = 0) const override virtual
Get faces from object with given accuracy
Reimplemented from Data::ComplexGeoData.
Definition at line 347 of file Mesh.cpp.
References MeshCore::MeshKernel::CountFacets(), MeshCore::MeshKernel::CountPoints(), MeshCore::MeshKernel::GetFacets(), getPoint(), SplineSurface::i, and Data::ComplexGeoData::Facet::I1.
Referenced by getFacesFromSubElement().
getFacesFromSubElement()
void MeshObject::getFacesFromSubElement (const Data::Segment * element, std::vector< Base::Vector3d > & Points, std::vector< Base::Vector3d > & PointNormals, std::vector< Facet > & faces) const override virtual
Get faces from segment
Reimplemented from Data::ComplexGeoData.
Definition at line 139 of file Mesh.cpp.
References getFaces(), Base::BaseClass::is(), Mesh::MeshSegment::mesh, and Mesh::MeshSegment::segment.
getFacetsFromSelection()
void MeshObject::getFacetsFromSelection (std::vector< FacetIndex > & inds) const
Definition at line 760 of file Mesh.cpp.
References MeshCore::MeshAlgorithm::GetFacetsFlag(), and MeshCore::MeshFacet::SELECTED.
Referenced by MeshGui::ViewProviderMesh::deleteSelection(), and MeshGui::ViewProviderMesh::highlightSelection().
getKernel() [1/2]
MeshCore::MeshKernel& Mesh::MeshObject::getKernel () inline
Definition at line 179 of file Mesh.h.
Referenced by MeshGui::MeshSelection::deleteSelection(), MeshGui::MeshSelection::deleteSelectionBorder(), MeshGui::ViewProviderMesh::deselectComponent(), Mesh::Curvature::execute(), Mesh::SetOperations::execute(), Mesh::SegmentByMesh::execute(), MeshGui::ViewProviderMesh::faceInfo(), MeshGui::ViewProviderMesh::fillHole(), foraminate(), getSelfIntersections(), Inspection::InspectNominalFastMesh::InspectNominalFastMesh(), MeshGui::ViewProviderMesh::invertSelection(), MeshGui::ViewProviderMesh::isFacetSelected(), MeshPartGui::Mesh2ShapeGmsh::loadOutput(), MeshGui::RemeshGmsh::loadOutput(), nearestFacetOnRay(), MeshGui::SoFCMeshPickNode::notify(), MeshGui::SoFCMeshPickNode::pick(), MeshGui::ViewProviderMesh::segmentMesh(), MeshGui::ViewProviderMesh::selectComponent(), MeshGui::DlgEvaluateMeshImp::showInformation(), MeshGui::ViewProviderIndexedFaceSet::showOpenEdges(), MeshGui::ViewProviderMesh::splitMesh(), MeshGui::PropertyMeshKernelItem::value(), and writeInventor().
getKernel() [2/2]
const MeshCore::MeshKernel& Mesh::MeshObject::getKernel () const inline
Definition at line 183 of file Mesh.h.
getMemSize()
unsigned int MeshObject::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Reimplemented from Data::ComplexGeoData.
Definition at line 370 of file Mesh.cpp.
References MeshCore::MeshKernel::GetMemSize().
getMeshFacet()
Mesh::Facet MeshObject::getMeshFacet (FacetIndex index) const
Definition at line 341 of file Mesh.cpp.
References MeshCore::MeshKernel::GetFacets().
getMeshPoint()
MeshPoint MeshObject::getMeshPoint (PointIndex index) const
Definition at line 325 of file Mesh.cpp.
References getPoint(), and updateLeaderLines::point.
getPoint()
Base::Vector3d MeshObject::getPoint (PointIndex index) const
Definition at line 317 of file Mesh.cpp.
References MeshCore::MeshKernel::GetPoint(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by getFaces(), and getMeshPoint().
getPointDegree()
unsigned long MeshObject::getPointDegree (const std::vector< FacetIndex > & indices, std::vector< PointIndex > & point_degree) const
Checks for the given facet indices what will be the degree for each point when these facets are removed from the mesh kernel. The point degree information is stored in point_degree. The return value gives the number of points which will have a degree of zero.
Definition at line 901 of file Mesh.cpp.
References MeshCore::MeshFacet::_aulPoints, MeshCore::MeshKernel::CountPoints(), MeshCore::MeshKernel::GetFacets(), and TestSpreadsheet::v.
Referenced by MeshGui::ViewProviderMesh::removeFacets().
getPointNormal()
Base::Vector3d MeshObject::getPointNormal (PointIndex index) const
Definition at line 1091 of file Mesh.cpp.
References MeshCore::MeshKernel::CalcVertexNormals(), Base::Vector3< float_type >::Normalize(), and Data::ComplexGeoData::transformVectorToOutside().
getPointNormals()
std::vector< Base::Vector3d > MeshObject::getPointNormals () const
Definition at line 1099 of file Mesh.cpp.
References MeshCore::MeshKernel::CalcVertexNormals(), and Data::ComplexGeoData::transformVectorsToOutside().
getPoints()
void MeshObject::getPoints (std::vector< Base::Vector3d > & Points, std::vector< Base::Vector3d > & Normals, double Accuracy, uint16_t flags = 0) const override virtual
Get points from object with given accuracy
Reimplemented from Data::ComplexGeoData.
Definition at line 331 of file Mesh.cpp.
References MeshCore::MeshKernel::GetPoints(), MeshCore::MeshRefNormalToPoints::GetValues(), Data::ComplexGeoData::transformPointsToOutside(), and Data::ComplexGeoData::transformVectorsToOutside().
getPointsFromFacets()
std::vector< PointIndex > MeshObject::getPointsFromFacets (const std::vector< FacetIndex > & facets) const
Definition at line 790 of file Mesh.cpp.
References MeshCore::MeshKernel::GetFacetPoints().
getPointsFromSelection()
void MeshObject::getPointsFromSelection (std::vector< PointIndex > & inds) const
Definition at line 765 of file Mesh.cpp.
References MeshCore::MeshAlgorithm::GetPointsFlag(), and MeshCore::MeshPoint::SELECTED.
getSegment() [1/2]
Segment & MeshObject::getSegment (unsigned long index)
Definition at line 2058 of file Mesh.cpp.
getSegment() [2/2]
const Segment & MeshObject::getSegment (unsigned long index) const
Definition at line 2053 of file Mesh.cpp.
Referenced by MeshPartGui::Tessellation::addFaceColors(), getSubElement(), and MeshGui::ViewProviderMesh::highlightSegments().
getSegmentsOfType()
std::vector< Segment > MeshObject::getSegmentsOfType (MeshObject::GeometryType type, float dev, unsigned long minFacets) const
Definition at line 2079 of file Mesh.cpp.
References MeshCore::MeshKernel::CountFacets(), CYLINDER, MeshCore::MeshSegmentAlgorithm::FindSegments(), PLANE, SPHERE, and Path.Post.scripts.grbl_post::type.
getSelfIntersections() [1/2]
MeshObject::TFacePairs MeshObject::getSelfIntersections () const
Definition at line 1539 of file Mesh.cpp.
References MeshCore::MeshEvalSelfIntersection::GetIntersections(), and getKernel().
getSelfIntersections() [2/2]
std::vector< Base::Line3d > MeshObject::getSelfIntersections (const TFacePairs & facets) const
Definition at line 1548 of file Mesh.cpp.
References MeshCore::MeshEvalSelfIntersection::GetIntersections(), getKernel(), getTransform(), and RobotExample::l.
getSubElement()
Data::Segment * MeshObject::getSubElement (const char * Type, unsigned long n) const override virtual
get the subelement by type and number
Implements Data::ComplexGeoData.
Definition at line 118 of file Mesh.cpp.
References countSegments(), getSegment(), Mesh::MeshSegment::mesh, MeshObject(), and Mesh::MeshSegment::segment.
getSurface()
double MeshObject::getSurface () const
Definition at line 307 of file Mesh.cpp.
References MeshCore::MeshKernel::GetSurface().
getTransform()
Base::Matrix4D MeshObject::getTransform () const override virtual
Return the current matrix This method has to be handled by the child classes. the actual placement and matrix is not part of this class.
Implements Data::ComplexGeoData.
Definition at line 170 of file Mesh.cpp.
Referenced by cut(), getSelfIntersections(), Inspection::InspectActualMesh::InspectActualMesh(), Inspection::InspectNominalFastMesh::InspectNominalFastMesh(), Inspection::InspectNominalMesh::InspectNominalMesh(), trim(), and writeInventor().
getVolume()
double MeshObject::getVolume () const
Definition at line 312 of file Mesh.cpp.
References MeshCore::MeshKernel::GetVolume().
harmonizeNormals()
void MeshObject::harmonizeNormals ()
Definition at line 1501 of file Mesh.cpp.
References MeshCore::MeshTopoAlgorithm::HarmonizeNormals().
Referenced by MeshPartGui::Mesh2ShapeGmsh::loadOutput(), and MeshGui::RemeshGmsh::loadOutput().
hasCorruptedFacets()
bool MeshObject::hasCorruptedFacets () const
Definition at line 1739 of file Mesh.cpp.
References MeshCore::MeshEvalCorruptedFacets::Evaluate().
hasFacetsOutOfRange()
bool MeshObject::hasFacetsOutOfRange () const
Definition at line 1733 of file Mesh.cpp.
References MeshCore::MeshEvalRangeFacet::Evaluate().
hasInvalidNeighbourhood()
bool MeshObject::hasInvalidNeighbourhood () const
Definition at line 1721 of file Mesh.cpp.
References MeshCore::MeshEvalNeighbourhood::Evaluate().
hasInvalidPoints()
bool MeshObject::hasInvalidPoints () const
Definition at line 1655 of file Mesh.cpp.
References MeshCore::MeshEvalNaNPoints::GetIndices().
hasNonManifolds()
bool MeshObject::hasNonManifolds () const
Definition at line 1507 of file Mesh.cpp.
References MeshCore::MeshEvalTopology::Evaluate().
hasPointsOnEdge()
bool MeshObject::hasPointsOnEdge () const
Definition at line 1667 of file Mesh.cpp.
References MeshCore::MeshEvalPointOnEdge::Evaluate().
hasPointsOutOfRange()
bool MeshObject::hasPointsOutOfRange () const
Definition at line 1727 of file Mesh.cpp.
References MeshCore::MeshEvalRangePoint::Evaluate().
hasSelectedFacets()
bool MeshObject::hasSelectedFacets () const
Definition at line 775 of file Mesh.cpp.
References countSelectedFacets().
Referenced by MeshGui::ViewProviderMesh::deselectComponent(), MeshGui::ViewProviderMesh::deselectFacet(), MeshGui::ViewProviderMesh::hasSelection(), and MeshGui::ViewProviderMesh::removeSelection().
hasSelectedPoints()
bool MeshObject::hasSelectedPoints () const
Definition at line 785 of file Mesh.cpp.
References countSelectedPoints().
hasSelfIntersections()
bool MeshObject::hasSelfIntersections () const
Definition at line 1533 of file Mesh.cpp.
References MeshCore::MeshEvalSelfIntersection::Evaluate().
inner()
MeshObject * MeshObject::inner (const MeshObject & mesh) const
Definition at line 1268 of file Mesh.cpp.
References MeshCore::SetOperations::Do(), MeshCore::SetOperations::Inner, Mesh2Shape::mesh, MeshObject(), result, and MeshCore::MeshKernel::Transform().
Referenced by cut().
insertVertex()
void MeshObject::insertVertex (FacetIndex facet, const Base::Vector3f & v)
Definition at line 1476 of file Mesh.cpp.
References MeshCore::MeshTopoAlgorithm::InsertVertex(), and TestSpreadsheet::v.
intersect()
MeshObject * MeshObject::intersect (const MeshObject & mesh) const
Definition at line 1236 of file Mesh.cpp.
References MeshCore::SetOperations::Do(), MeshCore::SetOperations::Intersect, Mesh2Shape::mesh, MeshObject(), result, and MeshCore::MeshKernel::Transform().
isSolid()
bool MeshObject::isSolid () const
Definition at line 301 of file Mesh.cpp.
References MeshCore::MeshEvalSolid::Evaluate().
load() [1/3]
bool MeshObject::load (const char * file, MeshCore::Material * mat = nullptr)
Definition at line 453 of file Mesh.cpp.
References DrawingExample::file, MeshCore::MeshInput::GetGroupNames(), and MeshCore::MeshInput::LoadAny().
Referenced by RestoreDocFile(), and Sandbox::MeshLoaderThread::run().
load() [2/3]
void MeshObject::load (std::istream & in)
Definition at line 520 of file Mesh.cpp.
References Base::Console(), MeshCore::MeshEvalTopology::Evaluate(), MeshCore::MeshEvalNeighbourhood::Evaluate(), Base::ConsoleSingleton::Log(), MeshCore::MeshKernel::Read(), MeshCore::MeshKernel::RebuildNeighbours(), and Base::ConsoleSingleton::Warning().
load() [3/3]
bool MeshObject::load (std::istream & str, MeshCore::MeshIO::Format f, MeshCore::Material * mat = nullptr)
Definition at line 465 of file Mesh.cpp.
References SCL.SimpleDataTypes::f, MeshCore::MeshInput::GetGroupNames(), MeshCore::MeshInput::LoadFormat(), and Path.Post.scripts.refactored_centroid_post::str.
mergeFacets()
void MeshObject::mergeFacets ()
Definition at line 1679 of file Mesh.cpp.
References src.Mod.AddonManager.NetworkManager::count, MeshCore::MeshKernel::CountFacets(), and MeshCore::MeshFixMergeFacets::Fixup().
meshFromSegment()
MeshObject * MeshObject::meshFromSegment (const std::vector< FacetIndex > & indices) const
Definition at line 2063 of file Mesh.cpp.
References MeshCore::MeshKernel::GetFacets(), MeshCore::MeshKernel::GetPoints(), MeshCore::MeshKernel::Merge(), and MeshObject().
Referenced by MeshGui::ViewProviderMesh::splitMesh().
movePoint()
void MeshObject::movePoint (PointIndex index, const Base::Vector3d & v)
Definition at line 1058 of file Mesh.cpp.
References MeshCore::MeshKernel::MovePoint(), Data::ComplexGeoData::transformPointToInside(), TestSpreadsheet::v, and SurfaceTests.TestBlendCurve::vec.
nearestFacetOnRay()
bool MeshObject::nearestFacetOnRay (const TRay & ray, double maxAngle, MeshObject::TFaceSection & output) const
Definition at line 795 of file Mesh.cpp.
References getKernel(), Data::ComplexGeoData::getPlacement(), src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::inv(), Base::Placement::inverse(), Base::Placement::multVec(), and MeshCore::MeshAlgorithm::NearestFacetOnRay().
offset()
void MeshObject::offset (float fSize)
Definition at line 937 of file Mesh.cpp.
References MeshCore::MeshKernel::CalcVertexNormals(), SplineSurface::i, MeshCore::MeshKernel::MovePoint(), and MeshCore::MeshKernel::RecalcBoundBox().
offsetSpecial()
void MeshObject::offsetSpecial (float fSize, float zmax, float zmin)
Definition at line 1016 of file Mesh.cpp.
References MeshCore::MeshKernel::CalcVertexNormals(), MeshCore::MeshKernel::GetPoint(), SplineSurface::i, MeshCore::MeshKernel::MovePoint(), and Base::Vector3< float_type >::z.
offsetSpecial2()
void MeshObject::offsetSpecial2 (float fSize)
Definition at line 950 of file Mesh.cpp.
References KDL::acos(), Base::Builder3D::addNode(), MeshCore::MeshKernel::CalcVertexNormals(), MeshCore::MeshTopoAlgorithm::Cleanup(), MeshCore::MeshTopoAlgorithm::CollapseFacet(), Mesh2Shape::faces, MeshCore::MeshGeomFacet::GetGravityPoint(), MeshCore::MeshEvalSelfIntersection::GetIntersections(), MeshCore::MeshGeomFacet::GetNormal(), MeshCore::MeshKernel::GetPoint(), SplineSurface::i, MeshCore::MeshFacetIterator::Init(), MeshCore::MeshFacet::INVALID, MeshCore::MeshGeomFacet::IsFlag(), RobotExample::l, Base::Vector3< float_type >::Length(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshKernel::MovePoint(), MeshCore::MeshFacetIterator::Next(), Base::Vector3< float_type >::Normalize(), Base::DrawStyle::pointSize, MeshCore::MeshFacetIterator::Position(), MeshCore::MeshKernel::RecalcBoundBox(), and Base::Builder3D::saveToLog().
operator=() [1/2]
MeshObject & MeshObject::operator= (const MeshObject & mesh)
Definition at line 218 of file Mesh.cpp.
References Mesh2Shape::mesh, and setTransform().
operator=() [2/2]
MeshObject & MeshObject::operator= (MeshObject && mesh)
Definition at line 230 of file Mesh.cpp.
References Mesh2Shape::mesh, and setTransform().
optimizeEdges()
void MeshObject::optimizeEdges ()
Definition at line 1389 of file Mesh.cpp.
References MeshCore::MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection().
optimizeTopology()
void MeshObject::optimizeTopology (float fMaxAngle)
Definition at line 1374 of file Mesh.cpp.
References MeshCore::MeshTopoAlgorithm::OptimizeTopology().
outer()
MeshObject * MeshObject::outer (const MeshObject & mesh) const
Definition at line 1284 of file Mesh.cpp.
References MeshCore::SetOperations::Do(), Mesh2Shape::mesh, MeshObject(), MeshCore::SetOperations::Outer, result, and MeshCore::MeshKernel::Transform().
points_begin()
const_point_iterator Mesh::MeshObject::points_begin () const inline
Definition at line 430 of file Mesh.h.
points_end()
const_point_iterator Mesh::MeshObject::points_end () const inline
Definition at line 434 of file Mesh.h.
refine()
void MeshObject::refine ()
Definition at line 1339 of file Mesh.cpp.
References MeshCore::MeshKernel::CountFacets(), MeshCore::MeshGeomFacet::GetGravityPoint(), SplineSurface::i, MeshCore::MeshTopoAlgorithm::InsertVertexAndSwapEdge(), MeshCore::MeshGeomFacet::IsDeformed(), and MeshCore::MeshFacetIterator::Set().
removeComponents()
void MeshObject::removeComponents (unsigned long count)
Definition at line 893 of file Mesh.cpp.
References src.Mod.AddonManager.NetworkManager::count, MeshCore::MeshKernel::DeleteFacets(), and MeshCore::MeshTopoAlgorithm::FindComponents().
removeDuplicatedFacets()
void MeshObject::removeDuplicatedFacets ()
Definition at line 1779 of file Mesh.cpp.
References src.Mod.AddonManager.NetworkManager::count, MeshCore::MeshKernel::CountFacets(), and MeshCore::MeshFixDuplicateFacets::Fixup().
removeDuplicatedPoints()
void MeshObject::removeDuplicatedPoints ()
Definition at line 1769 of file Mesh.cpp.
References src.Mod.AddonManager.NetworkManager::count, MeshCore::MeshKernel::CountFacets(), and MeshCore::MeshFixDuplicatePoints::Fixup().
removeFacetsFromSelection()
void MeshObject::removeFacetsFromSelection (const std::vector< FacetIndex > & inds) const
Definition at line 750 of file Mesh.cpp.
References MeshCore::MeshAlgorithm::ResetFacetsFlag(), and MeshCore::MeshFacet::SELECTED.
Referenced by MeshGui::ViewProviderMesh::deselectComponent(), MeshGui::ViewProviderMesh::deselectFacet(), and MeshGui::ViewProviderMesh::removeSelection().
removeFoldsOnSurface()
void MeshObject::removeFoldsOnSurface ()
Definition at line 1613 of file Mesh.cpp.
References deleteFacets(), MeshCore::MeshEvalFoldsOnSurface::Evaluate(), MeshCore::MeshEvalFoldsOnBoundary::Evaluate(), MeshCore::MeshEvalFoldOversOnSurface::Evaluate(), MeshCore::MeshEvalFoldsOnSurface::GetIndices(), MeshCore::MeshEvalFoldsOnBoundary::GetIndices(), MeshCore::MeshEvalFoldOversOnSurface::GetIndices(), and SplineSurface::i.
removeFullBoundaryFacets()
void MeshObject::removeFullBoundaryFacets ()
Definition at line 1647 of file Mesh.cpp.
References deleteFacets().
removeInvalidPoints()
void MeshObject::removeInvalidPoints ()
Definition at line 1661 of file Mesh.cpp.
References deletePoints(), and MeshCore::MeshEvalNaNPoints::GetIndices().
removeNeedles()
void MeshObject::removeNeedles (float length)
Definition at line 1358 of file Mesh.cpp.
References src.Mod.AddonManager.NetworkManager::count, MeshCore::MeshKernel::CountFacets(), and MeshCore::MeshRemoveNeedles::Fixup().
removeNonManifoldPoints()
void MeshObject::removeNonManifoldPoints ()
Definition at line 1523 of file Mesh.cpp.
References deleteFacets(), MeshCore::MeshEvalPointManifolds::Evaluate(), Mesh2Shape::faces, and MeshCore::MeshEvalPointManifolds::GetFacetIndices().
removeNonManifolds()
void MeshObject::removeNonManifolds ()
Definition at line 1513 of file Mesh.cpp.
References MeshCore::MeshEvalTopology::Evaluate(), MeshCore::MeshFixTopology::Fixup(), MeshCore::MeshFixTopology::GetDeletedFaces(), and MeshCore::MeshEvalTopology::GetFacets().
removePointsFromSelection()
void MeshObject::removePointsFromSelection (const std::vector< PointIndex > & inds) const
Definition at line 755 of file Mesh.cpp.
References MeshCore::MeshAlgorithm::ResetPointsFlag(), and MeshCore::MeshPoint::SELECTED.
removePointsOnEdge()
void MeshObject::removePointsOnEdge (bool fillBoundary)
Definition at line 1673 of file Mesh.cpp.
References MeshCore::MeshFixPointOnEdge::Fixup().
removeSelfIntersections() [1/2]
void MeshObject::removeSelfIntersections ()
Definition at line 1569 of file Mesh.cpp.
References deleteFacets(), MeshCore::MeshFixSelfIntersection::GetFacets(), and MeshCore::MeshEvalSelfIntersection::GetIntersections().
removeSelfIntersections() [2/2]
void MeshObject::removeSelfIntersections (const std::vector< FacetIndex > & indices)
Definition at line 1581 of file Mesh.cpp.
References MeshCore::MeshKernel::CountFacets(), MeshCore::MeshFixSelfIntersection::Fixup(), and TestSpreadsheet::v.
representation()
std::string MeshObject::representation () const
Definition at line 265 of file Mesh.cpp.
References Path.Log::info(), and Path.Post.scripts.refactored_centroid_post::str.
Referenced by config_control_design.pcurve::wr1(), automotive_design.motion_link_relationship::wr1(), config_control_design.degenerate_pcurve::wr1(), automotive_design.pcurve::wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.pcurve::wr1(), automotive_design.degenerate_pcurve::wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.degenerate_pcurve::wr1(), config_control_design.pcurve::wr2(), config_control_design.degenerate_pcurve::wr2(), automotive_design.pcurve::wr2(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.pcurve::wr2(), automotive_design.degenerate_pcurve::wr2(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.degenerate_pcurve::wr2(), config_control_design.pcurve::wr3(), and config_control_design.degenerate_pcurve::wr3().
Restore()
void MeshObject::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from Data::ComplexGeoData.
Definition at line 385 of file Mesh.cpp.
RestoreDocFile()
void MeshObject::RestoreDocFile (Base::Reader &) override virtual
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data. Again you have to apply for the call of this method in the Restore() call:
void PropertyMeshKernel::Restore(Base::XMLReader &reader)
{
  reader.readElement("Mesh");
  std::string file (reader.getAttribute("file") );
  if(file == "")
  {
    // read XML
    MeshCore::MeshDocXML restorer(*_pcMesh);
    restorer.Restore(reader);
  }else{
    // initiate a file read
    reader.addFile(file.c_str(),this);
 }
}
After you issued the reader.addFile() your RestoreDocFile() is called:
void PropertyMeshKernel::RestoreDocFile(Base::Reader &reader)
{
    _pcMesh->Read( reader );
}
See also
Base::Reader,Base::XMLReader
Reimplemented from Data::ComplexGeoData.
Definition at line 390 of file Mesh.cpp.
References load(), and TechDrawTools.TaskFillTemplateFields::reader.
Save()
void MeshObject::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Reimplemented from Data::ComplexGeoData.
Definition at line 375 of file Mesh.cpp.
save() [1/3]
void MeshObject::save (const char * file, MeshCore::MeshIO::Format f = MeshCore::MeshIO::Undefined, const MeshCore::Material * mat = nullptr, const char * objectname = nullptr) const
Definition at line 395 of file Mesh.cpp.
References SCL.SimpleDataTypes::f, DrawingExample::file, Base::FileInfo::fileNamePure(), toolbit-attributes::g, MeshCore::Material::library, MeshCore::MeshOutput::SaveAny(), MeshCore::MeshOutput::SetGroups(), MeshCore::MeshOutput::SetObjectName(), and MeshCore::MeshOutput::Transform().
Referenced by Mesh::Export::execute(), src.Mod.Show.mTempoVis.TempoVis::modify(), src.Mod.Show.mTempoVis.TempoVis::modifyVPProperty(), and src.Mod.Show.mTempoVis.TempoVis::saveCamera().
save() [2/3]
void MeshObject::save (std::ostream & out) const
Definition at line 515 of file Mesh.cpp.
References MeshCore::MeshKernel::Write().
Referenced by src.Mod.Show.mTempoVis.TempoVis::modify(), src.Mod.Show.mTempoVis.TempoVis::modifyVPProperty(), and src.Mod.Show.mTempoVis.TempoVis::saveCamera().
save() [3/3]
void MeshObject::save (std::ostream & str, MeshCore::MeshIO::Format f, const MeshCore::Material * mat = nullptr, const char * objectname = nullptr) const
Definition at line 426 of file Mesh.cpp.
References SCL.SimpleDataTypes::f, toolbit-attributes::g, MeshCore::MeshOutput::SaveFormat(), MeshCore::MeshOutput::SetGroups(), MeshCore::MeshOutput::SetObjectName(), Path.Post.scripts.refactored_centroid_post::str, and MeshCore::MeshOutput::Transform().
Referenced by src.Mod.Show.mTempoVis.TempoVis::modify(), src.Mod.Show.mTempoVis.TempoVis::modifyVPProperty(), and src.Mod.Show.mTempoVis.TempoVis::saveCamera().
SaveDocFile()
void MeshObject::SaveDocFile (Base::Writer &) const override virtual
This method is used to save large amounts of data to a binary file. Sometimes it makes no sense to write property data as XML. In case the amount of data is too big or the data type has a more effective way to save itself. In this cases it is possible to write the data in a separate file inside the document archive. In case you want do so you have to re-implement SaveDocFile(). First, you have to inform the framework in Save() that you want do so. Here an example from the Mesh module which can save a (pontetionaly big) triangle mesh:
void PropertyMeshKernel::Save (Base::Writer &writer) const
{
  if (writer.isForceXML())
  {
    writer << writer.ind() << "<Mesh>" << std::endl;
    MeshCore::MeshDocXML saver(*_pcMesh);
    saver.Save(writer);
  }else{
   writer << writer.ind() << "<Mesh file=\"" << writer.addFile("MeshKernel.bms", this) <<
"\"/>" << std::endl;
}
The writer.isForceXML() is an indication to force you to write XML. Regardless of size and effectiveness. The second part informs the Base::writer through writer.addFile("MeshKernel.bms", this) that this object wants to write a file with the given name. The method addFile() returns a unique name that then is written in the XML stream. This allows your RestoreDocFile() method to identify and read the file again. Later your SaveDocFile() method is called as many times as you issued the addFile() call:
 void
PropertyMeshKernel::SaveDocFile (Base::Writer &writer) const
{
    _pcMesh->Write( writer );
}
In this method you can simply stream your content to the file (Base::Writer inheriting from ostream).
Reimplemented from Data::ComplexGeoData.
Definition at line 380 of file Mesh.cpp.
References Base::Writer::Stream(), and MeshCore::MeshKernel::Write().
section()
std::vector< std::vector< Base::Vector3f > > MeshObject::section (const MeshObject & mesh, bool connectLines, float fMinDist) const
Definition at line 1301 of file Mesh.cpp.
References MeshCore::MeshIntersection::connectLines(), MeshCore::MeshIntersection::getIntersection(), Mesh2Shape::mesh, and MeshCore::MeshKernel::Transform().
Referenced by foraminate().
segments_begin()
const_segment_iterator Mesh::MeshObject::segments_begin () const inline
Definition at line 449 of file Mesh.h.
segments_end()
const_segment_iterator Mesh::MeshObject::segments_end () const inline
Definition at line 453 of file Mesh.h.
setFacets() [1/2]
void MeshObject::setFacets (const std::vector< Data::ComplexGeoData::Facet > & facets, const std::vector< Base::Vector3d > & points)
Definition at line 625 of file Mesh.cpp.
References MeshCore::MeshKernel::Adopt(), SCL.SimpleDataTypes::f, and buildPsets::p.
setFacets() [2/2]
void MeshObject::setFacets (const std::vector< MeshCore::MeshGeomFacet > & facets)
Definition at line 620 of file Mesh.cpp.
setKernel()
void MeshObject::setKernel (const MeshCore::MeshKernel & m)
Definition at line 242 of file Mesh.cpp.
References test::m.
Referenced by Mesh::MergeExporter::addMesh().
setPoint()
void MeshObject::setPoint (PointIndex index, const Base::Vector3d & p)
Definition at line 1069 of file Mesh.cpp.
References buildPsets::p, MeshCore::MeshKernel::SetPoint(), and Data::ComplexGeoData::transformPointToInside().
setTransform()
void MeshObject::setTransform (const Base::Matrix4D & rclTrf) override virtual
Override the current transformation with the new one. This method has to be handled by the child classes. the actual placement and matrix is not part of this class.
Implements Data::ComplexGeoData.
Definition at line 165 of file Mesh.cpp.
Referenced by clear(), operator=(), and transformToEigenSystem().
smooth()
void MeshObject::smooth (int iterations, float d_max)
Definition at line 1074 of file Mesh.cpp.
References MeshCore::MeshKernel::Smooth().
snapVertex()
void MeshObject::snapVertex (FacetIndex facet, const Base::Vector3f & v)
Definition at line 1482 of file Mesh.cpp.
References MeshCore::MeshTopoAlgorithm::SnapVertex(), and TestSpreadsheet::v.
splitEdge()
void MeshObject::splitEdge (FacetIndex facet, FacetIndex neighbour, const Base::Vector3f & v)
Definition at line 1427 of file Mesh.cpp.
References MeshCore::MeshTopoAlgorithm::SplitEdge(), and TestSpreadsheet::v.
splitEdges()
void MeshObject::splitEdges ()
Definition at line 1395 of file Mesh.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::FACET_INDEX_MAX, MeshCore::MeshKernel::GetFacets(), SplineSurface::id, MeshCore::MeshFacet::IsFlag(), MeshCore::MeshAlgorithm::ResetFacetFlag(), MeshCore::MeshFacetIterator::Set(), MeshCore::MeshFacet::SetFlag(), MeshCore::MeshFacetArray::SetFlag(), MeshCore::MeshTopoAlgorithm::SplitEdge(), and MeshCore::MeshFacet::VISIT.
splitFacet()
void MeshObject::splitFacet (FacetIndex facet, const Base::Vector3f & v1, const Base::Vector3f & v2)
Definition at line 1433 of file Mesh.cpp.
References MeshCore::MeshTopoAlgorithm::SplitFacet(), and draftgeoutils.general::v1().
subtract()
MeshObject * MeshObject::subtract (const MeshObject & mesh) const
Definition at line 1252 of file Mesh.cpp.
References MeshCore::SetOperations::Difference, MeshCore::SetOperations::Do(), Mesh2Shape::mesh, MeshObject(), result, and MeshCore::MeshKernel::Transform().
swap() [1/2]
void MeshObject::swap (MeshCore::MeshKernel & Kernel)
Swaps the content of Kernel and the internal mesh kernel.
Definition at line 248 of file Mesh.cpp.
References MeshCore::MeshKernel::Swap().
Referenced by MeshGui::Segmentation::accept(), ReverseEngineeringGui::Segmentation::accept(), MeshGui::SegmentationBestFit::accept(), MeshPart::BrepMesh::create(), ReverseEngineeringGui::SegmentationManual::createSegment(), and transformGeometry().
swap() [2/2]
void MeshObject::swap (MeshObject & mesh)
Definition at line 256 of file Mesh.cpp.
References Mesh2Shape::mesh, and MeshCore::MeshKernel::Swap().
swapEdge()
void MeshObject::swapEdge (FacetIndex facet, FacetIndex neighbour)
Definition at line 1439 of file Mesh.cpp.
References MeshCore::MeshTopoAlgorithm::SwapEdge().
topologyInfo()
std::string MeshObject::topologyInfo () const
Definition at line 273 of file Mesh.cpp.
References Path.Log::info(), and Path.Post.scripts.refactored_centroid_post::str.
transformGeometry()
void MeshObject::transformGeometry (const Base::Matrix4D & rclMat) override virtual
Applies a transformation on the real geometric data type.
Implements Data::ComplexGeoData.
Definition at line 157 of file Mesh.cpp.
References swap(), and MeshCore::MeshKernel::Transform().
transformToEigenSystem()
void MeshObject::transformToEigenSystem ()
Definition at line 1042 of file Mesh.cpp.
References MeshCore::MeshEigensystem::Evaluate(), setTransform(), and MeshCore::MeshEigensystem::Transform().
trim()
void MeshObject::trim (const Base::Polygon2d & polygon, const Base::ViewProjMethod & proj, MeshObject::CutType type)
Definition at line 1157 of file Mesh.cpp.
References MeshCore::MeshKernel::AddFacets(), ArchCommands::check(), deleteFacets(), getTransform(), INNER, MeshCore::MeshTrimming::INNER, Base::Matrix4D::inverse(), OUTER, MeshCore::MeshTrimming::OUTER, MeshCore::MeshKernel::Transform(), and Path.Post.scripts.grbl_post::type.
Referenced by trimByPlane().
trimByPlane()
void MeshObject::trimByPlane (const Base::Vector3f & base, const Base::Vector3f & normal)
Definition at line 1195 of file Mesh.cpp.
References MeshCore::MeshKernel::AddFacets(), deleteFacets(), Data::ComplexGeoData::getPlacement(), Base::Placement::getRotation(), Base::Placement::invert(), Base::Placement::multVec(), Base::Rotation::multVec(), and trim().
unite()
MeshObject * MeshObject::unite (const MeshObject & mesh) const
Definition at line 1220 of file Mesh.cpp.
References MeshCore::SetOperations::Do(), Mesh2Shape::mesh, MeshObject(), result, MeshCore::MeshKernel::Transform(), and MeshCore::SetOperations::Union.
validateCaps()
void MeshObject::validateCaps (float fMaxAngle, float fSplitFactor)
Definition at line 1368 of file Mesh.cpp.
References MeshCore::MeshFixCaps::Fixup().
validateDeformations()
void MeshObject::validateDeformations (float fMaxAngle, float fEps)
Definition at line 1745 of file Mesh.cpp.
References src.Mod.AddonManager.NetworkManager::count, MeshCore::MeshKernel::CountFacets(), MeshCore::MeshFixDeformedFacets::Fixup(), and Base::toRadians().
validateDegenerations()
void MeshObject::validateDegenerations (float fEps)
Definition at line 1759 of file Mesh.cpp.
References src.Mod.AddonManager.NetworkManager::count, MeshCore::MeshKernel::CountFacets(), and MeshCore::MeshFixDegeneratedFacets::Fixup().
validateIndices()
void MeshObject::validateIndices ()
Definition at line 1689 of file Mesh.cpp.
References src.Mod.AddonManager.NetworkManager::count, MeshCore::MeshKernel::CountFacets(), MeshCore::MeshEvalRangeFacet::Evaluate(), MeshCore::MeshEvalRangePoint::Evaluate(), MeshCore::MeshEvalCorruptedFacets::Evaluate(), MeshCore::MeshFixNeighbourhood::Fixup(), MeshCore::MeshFixRangeFacet::Fixup(), MeshCore::MeshFixRangePoint::Fixup(), and MeshCore::MeshFixCorruptedFacets::Fixup().
writeInventor()
void MeshObject::writeInventor (std::ostream & str, float creaseangle = 0.0F) const
Definition at line 546 of file Mesh.cpp.
References Base::InventorBuilder::addNode(), Base::InventorBuilder::beginSeparator(), Base::InventorBuilder::endSeparator(), MeshCore::MeshKernel::GetFacets(), getKernel(), MeshCore::MeshKernel::GetPoints(), getTransform(), and Path.Post.scripts.refactored_centroid_post::str.
Friends And Related Function Documentation
Segment
friend class Segment friend
Definition at line 460 of file Mesh.h.
The documentation for this class was generated from the following files:
Mesh.h
Mesh.cpp