FreeCAD: BOPTools.SplitAPI Namespace Reference
BOPTools.SplitAPI Namespace Reference
Functions
def booleanFragments (list_of_shapes, mode, tolerance=0.0)
def slice (base_shape, tool_shapes, mode, tolerance=0.0)
def xor (list_of_shapes, tolerance=0.0)
Function Documentation
booleanFragments()
def BOPTools.SplitAPI.booleanFragments (list_of_shapes, mode, tolerance = 0.0)
booleanFragments(list_of_shapes, mode, tolerance = 0.0): functional part of
BooleanFragments feature. It's just result of generalFuse plus a bit of
post-processing.
mode is a string. It can be "Standard", "Split" or "CompSolid".
"Standard" - return generalFuse as is.
"Split" - wires and shells will be split at intersections.
"CompSolid" - solids will be extracted from result of generelFuse, and compsolids will
be made from them; all other stuff is discarded.
Definition at line 34 of file SplitAPI.py.
slice()
def BOPTools.SplitAPI.slice (base_shape, tool_shapes, mode, tolerance = 0.0)
slice(base_shape, tool_shapes, mode, tolerance = 0.0): functional part of
Slice feature. Splits base_shape into pieces based on intersections with tool_shapes.
mode is a string. It can be "Standard", "Split" or "CompSolid".
"Standard" - return like generalFuse: edges, faces and solids are split, but wires,
shells, compsolids get extra segments but remain in one piece.
"Split" - wires and shells will be split at intersections, too.
"CompSolid" - slice a solid and glue it back together to make a compsolid
Definition at line 62 of file SplitAPI.py.
Referenced by App::ObjectIdentifier::Component.del(), MillSim::Shape.GenerateSinTable(), App::ObjectIdentifier::Component.get(), and App::ObjectIdentifier::Component.set().
xor()
def BOPTools.SplitAPI.xor (list_of_shapes, tolerance = 0.0)
xor(list_of_shapes, tolerance = 0.0): boolean XOR operation.
Definition at line 91 of file SplitAPI.py.