FreeCAD: TechDrawGui::DlgPrefsTechDrawAdvancedImp Class Reference
TechDrawGui::DlgPrefsTechDrawAdvancedImp Class Reference
#include <DlgPrefsTechDrawAdvancedImp.h>
Public Member Functions
DlgPrefsTechDrawAdvancedImp (QWidget *parent=nullptr)
~DlgPrefsTechDrawAdvancedImp () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void saveSettings () override
void loadSettings () override
void changeEvent (QEvent *event) override
void loadBalloonOverride ()
void saveBalloonOverride ()
void clearBalloonOptions ()
void makeBalloonBoxConnections ()
void slotBalloonBoxChecked ()
void enableBalloonOptions (bool newState)
Static Protected Member Functions
static bool flagsContainValue (uint flags, uint value)
true if bit pattern of value is found in flags.
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
Definition at line 57 of file DlgPrefsTechDrawAdvancedImp.h.
Constructor & Destructor Documentation
DlgPrefsTechDrawAdvancedImp()
DlgPrefsTechDrawAdvancedImp::DlgPrefsTechDrawAdvancedImp (QWidget * parent = nullptr) explicit
Definition at line 35 of file DlgPrefsTechDrawAdvancedImp.cpp.
References makeBalloonBoxConnections().
~DlgPrefsTechDrawAdvancedImp()
DlgPrefsTechDrawAdvancedImp::~DlgPrefsTechDrawAdvancedImp () override
Definition at line 44 of file DlgPrefsTechDrawAdvancedImp.cpp.
Member Function Documentation
changeEvent()
void DlgPrefsTechDrawAdvancedImp::changeEvent (QEvent * event) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 228 of file DlgPrefsTechDrawAdvancedImp.cpp.
clearBalloonOptions()
void DlgPrefsTechDrawAdvancedImp::clearBalloonOptions () protected
Definition at line 170 of file DlgPrefsTechDrawAdvancedImp.cpp.
Referenced by loadBalloonOverride(), and slotBalloonBoxChecked().
enableBalloonOptions()
void DlgPrefsTechDrawAdvancedImp::enableBalloonOptions (bool newState) protected
Definition at line 179 of file DlgPrefsTechDrawAdvancedImp.cpp.
Referenced by loadBalloonOverride(), and slotBalloonBoxChecked().
flagsContainValue()
bool DlgPrefsTechDrawAdvancedImp::flagsContainValue (uint flags, uint value) static protected
true if bit pattern of value is found in flags.
Definition at line 160 of file DlgPrefsTechDrawAdvancedImp.cpp.
Referenced by loadBalloonOverride().
loadBalloonOverride()
void DlgPrefsTechDrawAdvancedImp::loadBalloonOverride () protected
Definition at line 129 of file DlgPrefsTechDrawAdvancedImp.cpp.
References clearBalloonOptions(), enableBalloonOptions(), and flagsContainValue().
Referenced by loadSettings().
loadSettings()
void DlgPrefsTechDrawAdvancedImp::loadSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 104 of file DlgPrefsTechDrawAdvancedImp.cpp.
References loadBalloonOverride().
makeBalloonBoxConnections()
void DlgPrefsTechDrawAdvancedImp::makeBalloonBoxConnections () protected
Definition at line 200 of file DlgPrefsTechDrawAdvancedImp.cpp.
References draftgeoutils.intersections::connect(), and slotBalloonBoxChecked().
Referenced by DlgPrefsTechDrawAdvancedImp().
saveBalloonOverride()
void DlgPrefsTechDrawAdvancedImp::saveBalloonOverride () protected
Definition at line 75 of file DlgPrefsTechDrawAdvancedImp.cpp.
References result.
Referenced by saveSettings().
saveSettings()
void DlgPrefsTechDrawAdvancedImp::saveSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 49 of file DlgPrefsTechDrawAdvancedImp.cpp.
References saveBalloonOverride().
slotBalloonBoxChecked()
void DlgPrefsTechDrawAdvancedImp::slotBalloonBoxChecked () protected
Definition at line 188 of file DlgPrefsTechDrawAdvancedImp.cpp.
References clearBalloonOptions(), and enableBalloonOptions().
Referenced by makeBalloonBoxConnections().
The documentation for this class was generated from the following files:
DlgPrefsTechDrawAdvancedImp.h
DlgPrefsTechDrawAdvancedImp.cpp