FreeCAD: ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_item_specific_usage Class Reference
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_item_specific_usage Class Reference
Public Member Functions
def __init__ (self, inherited0__name, inherited1__description, inherited2__definition, inherited3__used_representation, inherited4__identified_item, item_identified_representation_usage_definition, item_identified_representation_usage_identified_item, item_identified_representation_usage_used_representation)
def item_identified_representation_usage_definition ()
def item_identified_representation_usage_identified_item ()
def item_identified_representation_usage_used_representation ()
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.item_identified_representation_usage
def __init__ (self, name, description, definition, used_representation, identified_item)
def name ()
def description ()
def definition ()
def used_representation ()
def identified_item ()
def wr1 (self)
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
item_identified_representation_usage_definition
item_identified_representation_usage_identified_item
item_identified_representation_usage_used_representation
Public Attributes inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.item_identified_representation_usage
name
description
definition
used_representation
identified_item
Detailed Description
Entity geometric_item_specific_usage definition.
:param item_identified_representation_usage_definition
:type item_identified_representation_usage_definition:geometric_item_specific_usage_select
:param item_identified_representation_usage_identified_item
:type item_identified_representation_usage_identified_item:geometric_representation_item
:param item_identified_representation_usage_used_representation
:type item_identified_representation_usage_used_representation:shape_representation
Definition at line 24838 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Constructor & Destructor Documentation
__init__()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_item_specific_usage.__init__ (self, inherited0__name, inherited1__description, inherited2__definition, inherited3__used_representation, inherited4__identified_item, item_identified_representation_usage_definition, item_identified_representation_usage_identified_item, item_identified_representation_usage_used_representation)
Definition at line 24850 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Member Function Documentation
item_identified_representation_usage_definition()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_item_specific_usage.item_identified_representation_usage_definition ()
Definition at line 24857 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_item_specific_usage._item_identified_representation_usage_definition, SCL.TypeChecker.check_type(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_item_specific_usage_select, and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_item_specific_usage.item_identified_representation_usage_definition.
item_identified_representation_usage_identified_item()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_item_specific_usage.item_identified_representation_usage_identified_item ()
Definition at line 24871 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_item_specific_usage._item_identified_representation_usage_identified_item, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_item_specific_usage.item_identified_representation_usage_identified_item.
item_identified_representation_usage_used_representation()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_item_specific_usage.item_identified_representation_usage_used_representation ()
Definition at line 24885 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_item_specific_usage._item_identified_representation_usage_used_representation, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_item_specific_usage.item_identified_representation_usage_used_representation.
Member Data Documentation
item_identified_representation_usage_definition
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_item_specific_usage.item_identified_representation_usage_definition
Definition at line 24852 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_item_specific_usage.item_identified_representation_usage_definition().
item_identified_representation_usage_identified_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_item_specific_usage.item_identified_representation_usage_identified_item
Definition at line 24853 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_item_specific_usage.item_identified_representation_usage_identified_item().
item_identified_representation_usage_used_representation
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_item_specific_usage.item_identified_representation_usage_used_representation
Definition at line 24854 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_item_specific_usage.item_identified_representation_usage_used_representation().
The documentation for this class was generated from the following file:
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py