FreeCAD: geoff_geometry::Triangle3d Class Reference
geoff_geometry::Triangle3d Class Reference
#include <geometry.h>
Public Member Functions
Triangle3d ()
Triangle3d (const Point3d &vert1, const Point3d &vert2, const Point3d &vert3)
bool Intof (const Line &l, Point3d &intof) const
Detailed Description
Definition at line 1677 of file geometry.h.
Constructor & Destructor Documentation
Triangle3d() [1/2]
geoff_geometry::Triangle3d::Triangle3d () inline
Definition at line 1690 of file geometry.h.
Triangle3d() [2/2]
geoff_geometry::Triangle3d::Triangle3d (const Point3d & vert1, const Point3d & vert2, const Point3d & vert3)
Definition at line 524 of file Finite.cpp.
References __max, __min, geoff_geometry::Box3d::max, geoff_geometry::Box3d::min, geoff_geometry::Point3d::x, geoff_geometry::Point3d::y, and geoff_geometry::Point3d::z.
Member Function Documentation
Intof()
bool geoff_geometry::Triangle3d::Intof (const Line & l, Point3d & intof) const
Definition at line 544 of file Finite.cpp.
References geoff_geometry::FEQZ(), RobotExample::l, geoff_geometry::Vector3d::normalise(), geoff_geometry::Box3d::outside(), buildPsets::p, toolbit-attributes::s, InitGui::t, buildPsets::u, and TestSpreadsheet::v.
The documentation for this class was generated from the following files:
geometry.h
Finite.cpp