FreeCAD: PartGui::SoBrepFaceSet::VBO Class Reference
PartGui::SoBrepFaceSet::VBO Class Reference
Classes
struct Buffer
Public Member Functions
VBO ()
~VBO ()
void render (SoGLRenderAction *action, const SoGLCoordinateElement *const vertexlist, const int32_t *vertexindices, int num_vertexindices, const int32_t *partindices, int num_partindices, const SbVec3f *normals, const int32_t *normindices, SoMaterialBundle *const materials, const int32_t *matindices, SoTextureCoordinateBundle *const texcoords, const int32_t *texindices, const int nbind, const int mbind, SbBool texture)
Static Public Member Functions
static void context_destruction_cb (uint32_t context, void *userdata)
static void vbo_delete (void *closure, uint32_t contextid)
Public Attributes
uint32_t indice_array
std::map< uint32_t, Buffer > vbomap
Static Public Attributes
static SbBool vboAvailable = false
Detailed Description
Definition at line 84 of file SoBrepFaceSet.cpp.
Constructor & Destructor Documentation
VBO()
PartGui::SoBrepFaceSet::VBO::VBO () inline
Definition at line 98 of file SoBrepFaceSet.cpp.
References PartGui::SoBrepFaceSet::VBO::context_destruction_cb(), and PartGui::SoBrepFaceSet::VBO::indice_array.
~VBO()
PartGui::SoBrepFaceSet::VBO::~VBO () inline
Definition at line 103 of file SoBrepFaceSet.cpp.
References PartGui::SoBrepFaceSet::VBO::context_destruction_cb(), PartGui::SoBrepFaceSet::VBO::vbo_delete(), and PartGui::SoBrepFaceSet::VBO::vbomap.
Member Function Documentation
context_destruction_cb()
static void PartGui::SoBrepFaceSet::VBO::context_destruction_cb (uint32_t context, void * userdata) inline static
Definition at line 133 of file SoBrepFaceSet.cpp.
References PartGui::SoBrepFaceSet::VBO::vbomap.
Referenced by PartGui::SoBrepFaceSet::VBO::VBO(), and PartGui::SoBrepFaceSet::VBO::~VBO().
render()
void PartGui::SoBrepFaceSet::VBO::render (SoGLRenderAction * action, const SoGLCoordinateElement *const vertexlist, const int32_t * vertexindices, int num_vertexindices, const int32_t * partindices, int num_partindices, const SbVec3f * normals, const int32_t * normindices, SoMaterialBundle *const materials, const int32_t * matindices, SoTextureCoordinateBundle *const texcoords, const int32_t * texindices, const int nbind, const int mbind, SbBool texture)
Definition at line 1363 of file SoBrepFaceSet.cpp.
References RobotExample::A, Path.Post.scripts.dynapath_4060_post::action, RobotExample::B, GCS::free(), getValue(), glDrawElements, PartGui::SoBrepFaceSet::VBO::Buffer::index_array_size, PartGui::SoBrepFaceSet::VBO::indice_array, importers.importIFCmulticore::materials, PartGui::SoBrepFaceSet::VBO::Buffer::myvbo, MeshCore::MeshIO::PER_FACE, MeshCore::MeshIO::PER_VERTEX, ClipperLib::pi, CAMTests.TestPathStock::R, PartGui::SoBrepFaceSet::VBO::Buffer::updateVbo, draftgeoutils.general::v1(), PartGui::SoBrepFaceSet::VBO::Buffer::vboLoaded, PartGui::SoBrepFaceSet::VBO::vbomap, and PartGui::SoBrepFaceSet::VBO::Buffer::vertex_array_size.
vbo_delete()
static void PartGui::SoBrepFaceSet::VBO::vbo_delete (void * closure, uint32_t contextid) inline static
Definition at line 149 of file SoBrepFaceSet.cpp.
Referenced by PartGui::SoBrepFaceSet::VBO::~VBO().
Member Data Documentation
indice_array
uint32_t PartGui::SoBrepFaceSet::VBO::indice_array
Definition at line 95 of file SoBrepFaceSet.cpp.
Referenced by PartGui::SoBrepFaceSet::VBO::render(), and PartGui::SoBrepFaceSet::VBO::VBO().
vboAvailable
SbBool PartGui::SoBrepFaceSet::VBO::vboAvailable = false static
Definition at line 94 of file SoBrepFaceSet.cpp.
vbomap
std::map<uint32_t, Buffer> PartGui::SoBrepFaceSet::VBO::vbomap
Definition at line 96 of file SoBrepFaceSet.cpp.
Referenced by PartGui::SoBrepFaceSet::VBO::context_destruction_cb(), PartGui::SoBrepFaceSet::VBO::render(), and PartGui::SoBrepFaceSet::VBO::~VBO().
The documentation for this class was generated from the following file:
SoBrepFaceSet.cpp