FreeCAD: Gui::Dialog::DlgParameterFind Class Reference
Gui::Dialog::DlgParameterFind Class Reference
#include <DlgParameterFind.h>
Public Member Functions
DlgParameterFind (DlgParameterImp *parent)
~DlgParameterFind () override
void accept () override
void reject () override
Detailed Description
Definition at line 38 of file DlgParameterFind.h.
Constructor & Destructor Documentation
DlgParameterFind()
DlgParameterFind::DlgParameterFind (DlgParameterImp * parent) explicit
Definition at line 38 of file DlgParameterFind.cpp.
~DlgParameterFind()
DlgParameterFind::~DlgParameterFind () override
Destroys the object and frees any allocated resources
Definition at line 56 of file DlgParameterFind.cpp.
Member Function Documentation
accept()
void DlgParameterFind::accept () override
Definition at line 266 of file DlgParameterFind.cpp.
References SplineSurface::i, Init::parent, and Path.Log::warning().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
reject()
void DlgParameterFind::reject () override
Definition at line 316 of file DlgParameterFind.cpp.
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
DlgParameterFind.h
DlgParameterFind.cpp