FreeCAD: Gui::PropertyEditor::PropertyItemDelegate Class Reference
Gui::PropertyEditor::PropertyItemDelegate Class Reference
#include <PropertyItemDelegate.h>
Public Member Functions
PropertyItemDelegate (QObject *parent)
~PropertyItemDelegate () override
void paint (QPainter *painter, const QStyleOptionViewItem &opt, const QModelIndex &index) const override
QWidget * createEditor (QWidget *, const QStyleOptionViewItem &, const QModelIndex &) const override
void setEditorData (QWidget *editor, const QModelIndex &index) const override
void setModelData (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const override
QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const override
bool editorEvent (QEvent *event, QAbstractItemModel *model, const QStyleOptionViewItem &option, const QModelIndex &index) override
Protected Member Functions
bool eventFilter (QObject *, QEvent *) override
void valueChanged ()
Detailed Description
Definition at line 75 of file PropertyItemDelegate.h.
Constructor & Destructor Documentation
PropertyItemDelegate()
PropertyItemDelegate::PropertyItemDelegate (QObject * parent) explicit
Definition at line 46 of file PropertyItemDelegate.cpp.
~PropertyItemDelegate()
PropertyItemDelegate::~PropertyItemDelegate () override default
Member Function Documentation
createEditor()
QWidget * PropertyItemDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & , const QModelIndex & index) const override
Definition at line 143 of file PropertyItemDelegate.cpp.
References Path.Post.Utils::editor(), FC_LOG, Init::parent, App::Property::UserEdit, valueChanged(), and src.Mod.PartDesign.fcgear.svggear::w.
editorEvent()
bool PropertyItemDelegate::editorEvent (QEvent * event, QAbstractItemModel * model, const QStyleOptionViewItem & option, const QModelIndex & index) override
Definition at line 115 of file PropertyItemDelegate.cpp.
eventFilter()
bool PropertyItemDelegate::eventFilter (QObject * o, QEvent * ev) override protected
Definition at line 125 of file PropertyItemDelegate.cpp.
References src.Mod.Test.testPathArray::o, and Init::parent.
paint()
void PropertyItemDelegate::paint (QPainter * painter, const QStyleOptionViewItem & opt, const QModelIndex & index) const override
Definition at line 61 of file PropertyItemDelegate.cpp.
References Init::parent, and src.Mod.AddonManager.addonmanager_pyside_interface::QObject.
setEditorData()
void PropertyItemDelegate::setEditorData (QWidget * editor, const QModelIndex & index) const override
Definition at line 224 of file PropertyItemDelegate.cpp.
References Path.Post.Utils::editor(), Gui::PropertyEditor::PropertyEditorWidget::setValue(), and Gui::PropertyEditor::PropertyItemAttorney::toString().
setModelData()
void PropertyItemDelegate::setModelData (QWidget * editor, QAbstractItemModel * model, const QModelIndex & index) const override
Definition at line 241 of file PropertyItemDelegate.cpp.
References Path.Post.Utils::editor(), and Gui::PropertyEditor::PropertyItem::expressionEditorData().
sizeHint()
QSize PropertyItemDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex & index) const override
Definition at line 54 of file PropertyItemDelegate.cpp.
valueChanged()
void PropertyItemDelegate::valueChanged () protected
Definition at line 216 of file PropertyItemDelegate.cpp.
Referenced by createEditor().
The documentation for this class was generated from the following files:
PropertyItemDelegate.h
PropertyItemDelegate.cpp