FreeCAD: Gui::PrefPageProducer< CLASS > Class Template Reference
Gui::PrefPageProducer< CLASS > Class Template Reference
#include <WidgetFactory.h>
Public Member Functions
PrefPageProducer (const char *group)
~PrefPageProducer () override=default
void * Produce () const override
Public Member Functions inherited from Base::AbstractProducer
AbstractProducer ()=default
virtual ~AbstractProducer ()=default
Detailed Description
template<class CLASS>
class Gui::PrefPageProducer< CLASS >
The PrefPageProducer class is a value-based template class that provides the ability to create preference pages dynamically.
Author
Werner Mayer
Definition at line 112 of file WidgetFactory.h.
Constructor & Destructor Documentation
PrefPageProducer()
template<class CLASS > Gui::PrefPageProducer< CLASS >::PrefPageProducer (const char * group) inline
Register a special type of preference page to the WidgetFactoryInst.
Definition at line 118 of file WidgetFactory.h.
References Gui::Dialog::DlgPreferencesImp::addPage(), Base::Factory::AddProducer(), toolbit-attributes::group, and Gui::WidgetFactoryInst::instance().
~PrefPageProducer()
template<class CLASS > Gui::PrefPageProducer< CLASS >::~PrefPageProducer () override default
Member Function Documentation
Produce()
template<class CLASS > void* Gui::PrefPageProducer< CLASS >::Produce () const inline override virtual
Creates an instance of the specified widget.
Implements Base::AbstractProducer.
Definition at line 137 of file WidgetFactory.h.
The documentation for this class was generated from the following file:
WidgetFactory.h