FreeCAD: SIM::Coin3D::Quarter::ContextMenu Class Reference
SIM::Coin3D::Quarter::ContextMenu Class Reference
#include <ContextMenu.h>
Public Slots
void changeRenderMode (QAction *action)
void changeStereoMode (QAction *action)
void changeTransparencyType (QAction *action)
Public Member Functions
ContextMenu (QuarterWidget *quarterwidget)
~ContextMenu () override
QMenu * getMenu () const
Detailed Description
Definition at line 45 of file ContextMenu.h.
Constructor & Destructor Documentation
ContextMenu()
ContextMenu::ContextMenu (QuarterWidget * quarterwidget) explicit
Definition at line 43 of file ContextMenu.cpp.
References Path.Post.scripts.dynapath_4060_post::action, changeRenderMode(), changeStereoMode(), changeTransparencyType(), draftgeoutils.intersections::connect(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), SIM::Coin3D::Quarter::QuarterWidget::renderModeActions(), SIM::Coin3D::Quarter::QuarterWidget::seek(), SIM::Coin3D::Quarter::QuarterWidget::stereoModeActions(), SIM::Coin3D::Quarter::QuarterWidget::transparencyTypeActions(), and SIM::Coin3D::Quarter::QuarterWidget::viewAll().
~ContextMenu()
ContextMenu::~ContextMenu () override
Definition at line 129 of file ContextMenu.cpp.
Member Function Documentation
changeRenderMode
void ContextMenu::changeRenderMode (QAction * action) slot
Definition at line 145 of file ContextMenu.cpp.
References Path.Post.scripts.dynapath_4060_post::action, SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), and SIM::Coin3D::Quarter::QuarterWidget::setRenderMode().
Referenced by ContextMenu().
changeStereoMode
void ContextMenu::changeStereoMode (QAction * action) slot
Definition at line 155 of file ContextMenu.cpp.
References Path.Post.scripts.dynapath_4060_post::action, SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), and SIM::Coin3D::Quarter::QuarterWidget::setStereoMode().
Referenced by ContextMenu().
changeTransparencyType
void ContextMenu::changeTransparencyType (QAction * action) slot
Definition at line 165 of file ContextMenu.cpp.
References Path.Post.scripts.dynapath_4060_post::action, SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), SIM::Coin3D::Quarter::QuarterWidget::setTransparencyType(), and Path.Post.scripts.grbl_post::type.
Referenced by ContextMenu().
getMenu()
QMenu * ContextMenu::getMenu () const
Definition at line 139 of file ContextMenu.cpp.
Referenced by SIM::Coin3D::Quarter::QuarterWidgetP::contextMenu().
The documentation for this class was generated from the following files:
ContextMenu.h
ContextMenu.cpp