FreeCAD: Gui::Dialog::TextureMapping Class Reference
Gui::Dialog::TextureMapping Class Reference
#include <TextureMapping.h>
Public Member Functions
TextureMapping (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~TextureMapping () override
void accept () override
void reject () override
Protected Member Functions
void changeEvent (QEvent *e) override
void keyPressEvent (QKeyEvent *e) override
Detailed Description
Definition at line 38 of file TextureMapping.h.
Constructor & Destructor Documentation
TextureMapping()
TextureMapping::TextureMapping (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Definition at line 49 of file TextureMapping.cpp.
References App::Application::Config(), draftgeoutils.intersections::connect(), DrawingExample::file, Gui::FileChooser::fileNameSelected(), and App::GetApplication().
~TextureMapping()
TextureMapping::~TextureMapping () override
Definition at line 86 of file TextureMapping.cpp.
Member Function Documentation
accept()
void TextureMapping::accept () override
Definition at line 93 of file TextureMapping.cpp.
Referenced by Gui::Dialog::TaskTextureMapping::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
changeEvent()
void TextureMapping::changeEvent (QEvent * e) override protected
Definition at line 110 of file TextureMapping.cpp.
References SCL.SimpleDataTypes::e.
keyPressEvent()
void TextureMapping::keyPressEvent (QKeyEvent * e) override protected
Definition at line 120 of file TextureMapping.cpp.
References SCL.SimpleDataTypes::e.
reject()
void TextureMapping::reject () override
Definition at line 98 of file TextureMapping.cpp.
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), Gui::Dialog::TaskTextureMapping::reject(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
TextureMapping.h
TextureMapping.cpp