FreeCAD: Wm4::DistLine3Triangle3< Real > Class Template Reference
Wm4::DistLine3Triangle3< Real > Class Template Reference
#include <Wm4DistLine3Triangle3.h>
Public Member Functions
DistLine3Triangle3 (const Line3< Real > &rkLine, const Triangle3< Real > &rkTriangle)
const Line3< Real > & GetLine () const
const Triangle3< Real > & GetTriangle () const
virtual Real Get ()
virtual Real GetSquared ()
virtual Real Get (Real fT, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
virtual Real GetSquared (Real fT, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
Real GetLineParameter () const
Real GetTriangleBary (int i) const
Public Member Functions inherited from Wm4::Distance< Real, Vector3< Real > >
virtual ~Distance ()
virtual Real Get (Real fTMin, Real fTMax, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
virtual Real GetSquared (Real fTMin, Real fTMax, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
virtual Real GetDerivative (Real fT, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
virtual Real GetDerivativeSquared (Real fT, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
void SetDifferenceStep (Real fDifferenceStep)
Real GetDifferenceStep () const
Real GetContactTime () const
const Vector3< Real > & GetClosestPoint0 () const
const Vector3< Real > & GetClosestPoint1 () const
bool HasMultipleClosestPoints0 () const
bool HasMultipleClosestPoints1 () const
Additional Inherited Members
Public Attributes inherited from Wm4::Distance< Real, Vector3< Real > >
int MaximumIterations
Real ZeroThreshold
Protected Member Functions inherited from Wm4::Distance< Real, Vector3< Real > >
Distance ()
Protected Attributes inherited from Wm4::Distance< Real, Vector3< Real > >
Real m_fContactTime
Vector3< Real > m_kClosestPoint0
Vector3< Real > m_kClosestPoint1
bool m_bHasMultipleClosestPoints0
bool m_bHasMultipleClosestPoints1
Real m_fDifferenceStep
Real m_fInvTwoDifferenceStep
Detailed Description
template<class Real>
class Wm4::DistLine3Triangle3< Real >
Definition at line 29 of file Wm4DistLine3Triangle3.h.
Constructor & Destructor Documentation
DistLine3Triangle3()
template<class Real > Wm4::DistLine3Triangle3< Real >::DistLine3Triangle3 (const Line3< Real > & rkLine, const Triangle3< Real > & rkTriangle)
Definition at line 25 of file Wm4DistLine3Triangle3.cpp.
Member Function Documentation
Get() [1/2]
template<class Real > Real Wm4::DistLine3Triangle3< Real >::Get virtual
Implements Wm4::Distance< Real, Vector3< Real > >.
Definition at line 46 of file Wm4DistLine3Triangle3.cpp.
References Wm4::Math< Real >::Sqrt().
Referenced by Wm4::DistLine3Triangle3< Real >::Get().
Get() [2/2]
template<class Real > Real Wm4::DistLine3Triangle3< Real >::Get (Real fT, const Vector3< Real > & rkVelocity0, const Vector3< Real > & rkVelocity1) virtual
Implements Wm4::Distance< Real, Vector3< Real > >.
Definition at line 134 of file Wm4DistLine3Triangle3.cpp.
References Wm4::DistLine3Triangle3< Real >::Get().
GetLine()
template<class Real > const Line3< Real > & Wm4::DistLine3Triangle3< Real >::GetLine
Definition at line 34 of file Wm4DistLine3Triangle3.cpp.
GetLineParameter()
template<class Real > Real Wm4::DistLine3Triangle3< Real >::GetLineParameter
Definition at line 160 of file Wm4DistLine3Triangle3.cpp.
Referenced by Wm4::DistSegment3Triangle3< Real >::GetSquared().
GetSquared() [1/2]
template<class Real > Real Wm4::DistLine3Triangle3< Real >::GetSquared virtual
Implements Wm4::Distance< Real, Vector3< Real > >.
Definition at line 53 of file Wm4DistLine3Triangle3.cpp.
References Wm4::Segment3< Real >::Direction, Wm4::Vector3< Real >::Dot(), Wm4::Segment3< Real >::Extent, Wm4::Distance< Real, Vector3< Real > >::GetClosestPoint0(), Wm4::Distance< Real, Vector3< Real > >::GetClosestPoint1(), Wm4::DistLine3Segment3< Real >::GetLineParameter(), Wm4::DistLine3Segment3< Real >::GetSegmentParameter(), Wm4::DistLine3Segment3< Real >::GetSquared(), Wm4::Segment3< Real >::Origin, and Wm4::Vector3< Real >::UnitCross().
Referenced by Wm4::DistSegment3Triangle3< Real >::GetSquared(), and Wm4::DistLine3Triangle3< Real >::GetSquared().
GetSquared() [2/2]
template<class Real > Real Wm4::DistLine3Triangle3< Real >::GetSquared (Real fT, const Vector3< Real > & rkVelocity0, const Vector3< Real > & rkVelocity1) virtual
Implements Wm4::Distance< Real, Vector3< Real > >.
Definition at line 147 of file Wm4DistLine3Triangle3.cpp.
References Wm4::DistLine3Triangle3< Real >::GetSquared().
GetTriangle()
template<class Real > const Triangle3< Real > & Wm4::DistLine3Triangle3< Real >::GetTriangle
Definition at line 40 of file Wm4DistLine3Triangle3.cpp.
GetTriangleBary()
template<class Real > Real Wm4::DistLine3Triangle3< Real >::GetTriangleBary (int i) const
Definition at line 166 of file Wm4DistLine3Triangle3.cpp.
References SplineSurface::i.
Referenced by Wm4::DistSegment3Triangle3< Real >::GetSquared().
The documentation for this class was generated from the following files:
Wm4DistLine3Triangle3.h
Wm4DistLine3Triangle3.cpp