FreeCAD: Sandbox::DocumentSaverThread Class Reference
Sandbox::DocumentSaverThread Class Reference
#include <DocumentThread.h>
Public Member Functions
DocumentSaverThread (App::Document *doc, QObject *parent=0)
~DocumentSaverThread ()
Protected Member Functions
void run ()
Detailed Description
Definition at line 116 of file DocumentThread.h.
Constructor & Destructor Documentation
DocumentSaverThread()
DocumentSaverThread::DocumentSaverThread (App::Document * doc, QObject * parent = 0)
Definition at line 236 of file DocumentThread.cpp.
~DocumentSaverThread()
DocumentSaverThread::~DocumentSaverThread ()
Definition at line 241 of file DocumentThread.cpp.
Member Function Documentation
run()
void DocumentSaverThread::run () protected
Definition at line 245 of file DocumentThread.cpp.
References Base::Uuid::createUuid(), DrawingExample::file, App::PropertyString::getValue(), Base::ZipWriter::putNextEntry(), App::Document::Save(), Base::ZipWriter::setComment(), Base::ZipWriter::setLevel(), App::Document::signalSaveDocument, App::Document::TransientDir, and Base::ZipWriter::writeFiles().
The documentation for this class was generated from the following files:
DocumentThread.h
DocumentThread.cpp