FreeCAD: Command.cpp File Reference
Mod/Sketcher/Gui/Command.cpp File Reference
#include "PreCompiled.h"
#include <QApplication>
#include <QCheckBox>
#include <QGridLayout>
#include <QInputDialog>
#include <QLabel>
#include <QMenu>
#include <QMessageBox>
#include <QSignalBlocker>
#include <QWidgetAction>
#include <App/DocumentObjectGroup.h>
#include <App/Datums.h>
#include <Gui/Action.h>
#include <Gui/Application.h>
#include <Gui/BitmapFactory.h>
#include <Gui/CommandT.h>
#include <Gui/Control.h>
#include <Gui/Document.h>
#include <Gui/MainWindow.h>
#include <Gui/Notifications.h>
#include <Gui/PrefWidgets.h>
#include <Gui/QuantitySpinBox.h>
#include <Gui/SelectionFilter.h>
#include <Gui/SelectionObject.h>
#include <Mod/Part/App/Attacher.h>
#include <Mod/Part/App/Part2DObject.h>
#include <Mod/Part/Gui/AttacherTexts.h>
#include <Mod/Sketcher/App/Constraint.h>
#include <Mod/Sketcher/App/SketchObject.h>
#include "SketchMirrorDialog.h"
#include "SketchOrientationDialog.h"
#include "TaskSketcherValidation.h"
#include "Utils.h"
#include "ViewProviderSketch.h"
Classes
class SketcherGui::ExceptionWrongInput
class GridSpaceAction
class CmdSketcherGrid
class SnapSpaceAction
class CmdSketcherSnap
class RenderingOrderAction
class CmdRenderingOrder
Namespaces
SketcherGui
Functions
Attacher::eMapMode SketcherGui::SuggestAutoMapMode (Attacher::SuggestResult::eSuggestResult *pMsgId=nullptr, QString *message=nullptr, std::vector< Attacher::eMapMode > *allmodes=nullptr)
void CreateSketcherCommands ()
Function Documentation
CreateSketcherCommands()
void CreateSketcherCommands ()
Definition at line 1862 of file Mod/Sketcher/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().