FreeCAD: ifc2x3.ifcslippageconnectioncondition Class Reference
ifc2x3.ifcslippageconnectioncondition Class Reference
Public Member Functions
def __init__ (self, inherited0__name, slippagex, slippagey, slippagez)
def slippagex ()
def slippagey ()
def slippagez ()
Public Member Functions inherited from ifc2x3.ifcstructuralconnectioncondition
def __init__ (self, name)
def name ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
slippagex
slippagey
slippagez
Public Attributes inherited from ifc2x3.ifcstructuralconnectioncondition
name
Detailed Description
Entity ifcslippageconnectioncondition definition.
:param slippagex
:type slippagex:ifclengthmeasure
:param slippagey
:type slippagey:ifclengthmeasure
:param slippagez
:type slippagez:ifclengthmeasure
Definition at line 32483 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcslippageconnectioncondition.__init__ (self, inherited0__name, slippagex, slippagey, slippagez)
Definition at line 32495 of file ifc2x3.py.
Member Function Documentation
slippagex()
def ifc2x3.ifcslippageconnectioncondition.slippagex ()
Definition at line 32502 of file ifc2x3.py.
References ifc2x3.ifcslippageconnectioncondition._slippagex, SCL.TypeChecker.check_type(), and ifc2x3.ifcslippageconnectioncondition.slippagex.
slippagey()
def ifc2x3.ifcslippageconnectioncondition.slippagey ()
Definition at line 32516 of file ifc2x3.py.
References ifc2x3.ifcslippageconnectioncondition._slippagey, SCL.TypeChecker.check_type(), and ifc2x3.ifcslippageconnectioncondition.slippagey.
slippagez()
def ifc2x3.ifcslippageconnectioncondition.slippagez ()
Definition at line 32530 of file ifc2x3.py.
References ifc2x3.ifcslippageconnectioncondition._slippagez, SCL.TypeChecker.check_type(), and ifc2x3.ifcslippageconnectioncondition.slippagez.
Member Data Documentation
slippagex
ifc2x3.ifcslippageconnectioncondition.slippagex
Definition at line 32497 of file ifc2x3.py.
Referenced by ifc2x3.ifcslippageconnectioncondition.slippagex().
slippagey
ifc2x3.ifcslippageconnectioncondition.slippagey
Definition at line 32498 of file ifc2x3.py.
Referenced by ifc2x3.ifcslippageconnectioncondition.slippagey().
slippagez
ifc2x3.ifcslippageconnectioncondition.slippagez
Definition at line 32499 of file ifc2x3.py.
Referenced by ifc2x3.ifcslippageconnectioncondition.slippagez().
The documentation for this class was generated from the following file:
ifc2x3.py