FreeCAD: Base::InterpreterSingleton Class Reference
Base::InterpreterSingleton Class Reference
#include <Interpreter.h>
Public Member Functions
InterpreterSingleton ()
~InterpreterSingleton ()
InterpreterSingleton (const InterpreterSingleton &)=delete
InterpreterSingleton (InterpreterSingleton &&)=delete
InterpreterSingleton & operator= (const InterpreterSingleton &)=delete
InterpreterSingleton & operator= (InterpreterSingleton &&)=delete
execution methods
std::string runString (const char *psCmd)
std::string runStringWithKey (const char *psCmd, const char *key, const char *key_initial_value="")
Run a statement on the python interpreter with a key for exchanging strings.
Py::Object runStringObject (const char *sCmd)
Run a statement on the python interpreter and return back the result object.
void runInteractiveString (const char *psCmd)
void runFile (const char *pxFileName, bool local)
Run file (script) on the python interpreter.
void runStringArg (const char *psCom,...)
Run a statement with arguments on the python interpreter.
void runMethodVoid (PyObject *pobject, const char *method)
runs a python object method with no return value and no arguments
PyObject * runMethodObject (PyObject *pobject, const char *method)
runs a python object method which returns a arbitrary object
void runMethod (PyObject *pobject, const char *method, const char *resfmt=nullptr, void *cresult=nullptr, const char *argfmt="()",...)
runs a python method with arbitrary params
Cleanup
int cleanup (void(*func)())
void finalize ()
void systemExit ()
This shuts down the application.
external wrapper libs
here we can access external dynamically loaded wrapper libs done e.g. by SWIG or SIP
PyObject * createSWIGPointerObj (const char *Module, const char *TypeName, void *Pointer, int own)
generate a SWIG object
bool convertSWIGPointerObj (const char *Module, const char *TypeName, PyObject *obj, void **ptr, int flags)
void cleanupSWIG (const char *TypeName)
PyTypeObject * getSWIGPointerTypeObj (const char *Module, const char *TypeName)
methods for debugging facility
void dbgObserveFile (const char *sFileName="")
sets the file name which should be debugged
void dbgSetBreakPoint (unsigned int uiLineNumber)
sets a break point to a special line number in the current file
void dbgUnsetBreakPoint (unsigned int uiLineNumber)
unsets a break point to a special line number in the current file
void dbgStep ()
One step further.
Module handling
bool loadModule (const char *psModName)
void addPythonPath (const char *Path)
Add an additional python path.
PyObject * addModule (Py::ExtensionModuleBase *)
Add a module and return a PyObject to it.
void cleanupModules ()
Clean-up registered modules.
static void addType (PyTypeObject *Type, PyObject *Module, const char *Name)
startup and singletons
const char * init (int argc, char *argv[])
init the interpreter and returns the module search path
int runCommandLine (const char *prompt)
void replaceStdOutput ()
static InterpreterSingleton & Instance ()
static void Destruct ()
static helper functions
static InterpreterSingleton * _pcSingleton = nullptr
PyObject * getValue (const char *key, const char *result_var)
static std::string strToPython (const char *Str)
replaces all char with escapes for usage in python console
static std::string strToPython (const std::string &Str)
Detailed Description
The Interpreter class This class manage the python interpreter and hold a lot helper functions for handling python stuff
Definition at line 241 of file Interpreter.h.
Constructor & Destructor Documentation
InterpreterSingleton() [1/3]
InterpreterSingleton::InterpreterSingleton ()
Definition at line 224 of file Interpreter.cpp.
Referenced by Instance().
~InterpreterSingleton()
InterpreterSingleton::~InterpreterSingleton () default
InterpreterSingleton() [2/3]
Base::InterpreterSingleton::InterpreterSingleton (const InterpreterSingleton &) delete
InterpreterSingleton() [3/3]
Base::InterpreterSingleton::InterpreterSingleton (InterpreterSingleton &&) delete
Member Function Documentation
addModule()
PyObject * InterpreterSingleton::addModule (Py::ExtensionModuleBase * mod)
Add a module and return a PyObject to it.
Definition at line 506 of file Interpreter.cpp.
References mod.
Referenced by Gui::PythonDebugModule::init_module(), InspectionGui::initModule(), CloudGui::initModule(), SurfaceGui::initModule(), ReverseEngineeringGui::initModule(), PointsGui::initModule(), MeshPartGui::initModule(), MeasureGui::initModule(), RobotGui::initModule(), MatGui::initModule(), SketcherGui::initModule(), PartDesignGui::initModule(), StartGui::initModule(), PartGui::initModule(), MeshGui::initModule(), SpreadsheetGui::initModule(), JtReaderNS::initModule(), Cloud::initModule(), TestGui::initModule(), Drawing::initModule(), Mesh::initModule(), Reen::initModule(), TechDraw::initModule(), and Part::initModule().
addPythonPath()
void InterpreterSingleton::addPythonPath (const char * Path)
Add an additional python path.
Definition at line 536 of file Interpreter.cpp.
References src.Mod.Test.testmakeWireString::String.
Referenced by App::Application::processFiles().
addType()
void InterpreterSingleton::addType (PyTypeObject * Type, PyObject * Module, const char * Name) static
Definition at line 525 of file Interpreter.cpp.
References Base::getTypeAsObject().
Referenced by Gui::Application::Application(), Fem::SMESH_HypothesisPy< StdMeshers_TrianglePreferencePy >::init_type(), and PyMOD_INIT_FUNC().
cleanup()
int InterpreterSingleton::cleanup (void(*)() func)
Register a cleanup function to be called by finalize(). The cleanup function will be called with no arguments and should return no value. At most 32 cleanup functions can be registered. When the registration is successful 0 is returned; on failure -1 is returned. The cleanup function registered last is called first. Each cleanup function will be called at most once. Since Python's internal finalization will have completed before the cleanup function, no Python APIs should be called by func.
Definition at line 654 of file Interpreter.cpp.
Referenced by Path.Dressup.Gui.Boundary.TaskPanel::abort(), Path.Dressup.Gui.Tags.PathDressupTagTaskPanel::abort(), PathPythonGui.simple_edit_panel.SimpleEditPanel::abort(), Path.Dressup.Gui.Boundary.TaskPanel::accept(), Path.Dressup.Gui.Tags.PathDressupTagTaskPanel::accept(), Path.Dressup.Gui.DogboneII.TaskPanel::accept(), Path.Main.Gui.Job.TaskPanel::accept(), Path.Dressup.Gui.Dogbone.TaskPanel::accept(), Path.Op.Gui.Base.TaskPanel::accept(), Path.Dressup.Gui.Boundary.TaskPanel::reject(), Path.Dressup.Gui.Tags.PathDressupTagTaskPanel::reject(), Path.Dressup.Gui.DogboneII.TaskPanel::reject(), Path.Main.Gui.Job.TaskPanel::reject(), Path.Dressup.Gui.Dogbone.TaskPanel::reject(), and Path.Op.Gui.Base.TaskPanel::reject().
cleanupModules()
void InterpreterSingleton::cleanupModules ()
Clean-up registered modules.
Definition at line 512 of file Interpreter.cpp.
Referenced by finalize().
cleanupSWIG()
void InterpreterSingleton::cleanupSWIG (const char * TypeName)
Definition at line 976 of file Interpreter.cpp.
convertSWIGPointerObj()
bool InterpreterSingleton::convertSWIGPointerObj (const char * Module, const char * TypeName, PyObject * obj, void ** ptr, int flags)
Definition at line 949 of file Interpreter.cpp.
References result.
Referenced by Gui::View3DInventorPy::addDraggerCallback(), Gui::View3DInventorPy::addEventCallbackPivy(), Gui::View3DInventorPy::dumpNode(), Gui::FreeCADGui_exportSubgraph(), Gui::ViewProviderFeaturePythonImp::getDetail(), Gui::ViewProviderFeaturePythonImp::getDetailPath(), Gui::View3DInventorPy::removeDraggerCallback(), Gui::View3DInventorPy::removeEventCallbackPivy(), Gui::SoQtOffscreenRendererPy::render(), Gui::ApplicationPy::sCoinRemoveAllChildren(), Gui::View3DInventorViewerPy::setSceneGraph(), and Gui::View3DInventorViewerPy::setupEditingRoot().
createSWIGPointerObj()
PyObject * InterpreterSingleton::createSWIGPointerObj (const char * Module, const char * TypeName, void * Pointer, int own)
generate a SWIG object
Definition at line 923 of file Interpreter.cpp.
References result.
Referenced by Gui::FreeCADGui_subgraphFromObject(), Gui::View3DInventorPy::getCameraNode(), Gui::ViewProviderFeaturePythonImp::getDetailPath(), Gui::ViewProviderFeaturePythonImp::getElement(), Gui::ViewProviderFeaturePythonImp::getElementPicked(), Gui::View3DInventorViewerPy::getSceneGraph(), Gui::View3DInventorPy::getSceneGraph(), Gui::View3DInventorViewerPy::getSoEventManager(), and Gui::View3DInventorViewerPy::getSoRenderManager().
dbgObserveFile()
void InterpreterSingleton::dbgObserveFile (const char * sFileName = "")
sets the file name which should be debugged
Definition at line 820 of file Interpreter.cpp.
dbgSetBreakPoint()
void InterpreterSingleton::dbgSetBreakPoint (unsigned int uiLineNumber)
sets a break point to a special line number in the current file
Definition at line 830 of file Interpreter.cpp.
dbgStep()
void InterpreterSingleton::dbgStep ()
One step further.
Definition at line 836 of file Interpreter.cpp.
dbgUnsetBreakPoint()
void InterpreterSingleton::dbgUnsetBreakPoint (unsigned int uiLineNumber)
unsets a break point to a special line number in the current file
Definition at line 833 of file Interpreter.cpp.
Destruct()
void InterpreterSingleton::Destruct () static
Definition at line 699 of file Interpreter.cpp.
References _pcSingleton.
Referenced by App::Application::destruct().
finalize()
void InterpreterSingleton::finalize ()
This calls the registered cleanup functions.
See also
cleanup() for more details.
Definition at line 659 of file Interpreter.cpp.
References cleanupModules().
Referenced by App::Application::destruct(), and draftguitools.gui_trackers.ghostTracker::remove().
getSWIGPointerTypeObj()
PyTypeObject * InterpreterSingleton::getSWIGPointerTypeObj (const char * Module, const char * TypeName)
Definition at line 986 of file Interpreter.cpp.
References result.
getValue()
PyObject * InterpreterSingleton::getValue (const char * key, const char * result_var)
Definition at line 794 of file Interpreter.cpp.
References Path.Base.SetupSheet::dict, src.Mod.PartDesign.fcgear.svggear::module, and PP_Load_Module().
init()
const char * InterpreterSingleton::init (int argc, char * argv[])
init the interpreter and returns the module search path
Definition at line 544 of file Interpreter.cpp.
References SplineSurface::i, and PythonStdOutput::init_type().
Referenced by DocumentObject.DocumentObject::onChanged().
Instance()
InterpreterSingleton & InterpreterSingleton::Instance () static
Definition at line 690 of file Interpreter.cpp.
References _pcSingleton, and InterpreterSingleton().
Referenced by Base::Interpreter().
loadModule()
bool InterpreterSingleton::loadModule (const char * psModName)
Definition at line 486 of file Interpreter.cpp.
References src.Mod.PartDesign.fcgear.svggear::module, and PP_Load_Module().
Referenced by Base::Type::importModule(), App::Application::processCmdLineFiles(), App::Application::processFiles(), and PyMOD_INIT_FUNC().
operator=() [1/2]
InterpreterSingleton& Base::InterpreterSingleton::operator= (const InterpreterSingleton &) delete
operator=() [2/2]
InterpreterSingleton& Base::InterpreterSingleton::operator= (InterpreterSingleton &&) delete
replaceStdOutput()
void InterpreterSingleton::replaceStdOutput ()
Definition at line 646 of file Interpreter.cpp.
runCommandLine()
int InterpreterSingleton::runCommandLine (const char * prompt)
Definition at line 707 of file Interpreter.cpp.
References PP_Run_Command_Line().
Referenced by StdCmdCommandLine::activated(), and App::Application::runApplication().
runFile()
void InterpreterSingleton::runFile (const char * pxFileName, bool local)
Run file (script) on the python interpreter.
Definition at line 433 of file Interpreter.cpp.
References Path.Base.SetupSheet::dict, src.Mod.PartDesign.fcgear.svggear::module, result, and Base::FileInfo::toStdWString().
Referenced by Gui::PreferencePack::apply(), TechDraw::DrawParametricTemplate::execute(), App::Application::processFiles(), and Gui::MacroManager::run().
runInteractiveString()
void InterpreterSingleton::runInteractiveString (const char * psCmd)
Run a statement on the python interpreter and gives back a string with the representation of the result.
Definition at line 389 of file Interpreter.cpp.
References Path.Base.SetupSheet::dict, src.Mod.PartDesign.fcgear.svggear::module, PP_Load_Module(), and Base::Exception::setMessage().
runMethod()
void InterpreterSingleton::runMethod (PyObject * pobject, const char * method, const char * resfmt = nullptr, void * cresult = nullptr, const char * argfmt = "()", ...)
runs a python method with arbitrary params
Definition at line 747 of file Interpreter.cpp.
References PP_Convert_Result().
Referenced by Gui::PythonCommand::activated().
runMethodObject()
PyObject * InterpreterSingleton::runMethodObject (PyObject * pobject, const char * method)
runs a python object method which returns a arbitrary object
Definition at line 730 of file Interpreter.cpp.
References PP_Run_Method().
Referenced by Gui::PythonCommand::getHelpUrl(), Gui::PythonCommand::PythonCommand(), and Gui::PythonGroupCommand::PythonGroupCommand().
runMethodVoid()
void InterpreterSingleton::runMethodVoid (PyObject * pobject, const char * method)
runs a python object method with no return value and no arguments
Runs a member method of an object with no parameter and no return value void (void). There are other methods to run with returns
Definition at line 717 of file Interpreter.cpp.
References PP_Run_Method().
Referenced by Gui::PythonCommand::activated().
runString()
std::string InterpreterSingleton::runString (const char * psCmd)
Run a statement on the python interpreter and gives back a string with the representation of the result.
Definition at line 232 of file Interpreter.cpp.
References Path.Base.SetupSheet::dict, src.Mod.PartDesign.fcgear.svggear::module, PP_Load_Module(), and Base::PyException::ThrowException().
Referenced by Gui::Command::_runCommand(), Gui::Command::addModule(), TechDraw::DrawViewDraft::execute(), TechDraw::DrawViewArch::execute(), Measure::Module::Module(), Gui::GestureNavigationStyle::onRollGesture(), App::Application::processCmdLineFiles(), PyMOD_INIT_FUNC(), Sandbox::PythonThread::run(), App::Application::runApplication(), Gui::Application::runInitGuiScript(), runStringArg(), and Gui::Application::setActiveDocument().
runStringArg()
void InterpreterSingleton::runStringArg (const char * psCom, ...)
Run a statement with arguments on the python interpreter.
Definition at line 670 of file Interpreter.cpp.
References format2, format2_len, and runString().
Referenced by TechDraw::DrawViewDraft::execute(), TechDraw::DrawViewArch::execute(), TechDraw::DrawDimHelper::makeDistDim(), TechDraw::DrawDimHelper::makeExtentDim(), TechDraw::DrawDimHelper::makeExtentDim3d(), TechDraw::DrawLeaderLine::makeLeader(), App::Application::processCmdLineFiles(), App::Application::processFiles(), TechDraw::DrawViewCollection::unsetupObject(), TechDraw::DrawPage::unsetupObject(), and TechDraw::DrawViewPart::unsetupObject().
runStringObject()
Py::Object InterpreterSingleton::runStringObject (const char * sCmd)
Run a statement on the python interpreter and return back the result object.
Definition at line 314 of file Interpreter.cpp.
References Path.Base.SetupSheet::dict, src.Mod.PartDesign.fcgear.svggear::module, and PP_Load_Module().
Referenced by SketcherGui::ViewProviderSketch::onCameraChanged(), and PyMOD_INIT_FUNC().
runStringWithKey()
std::string InterpreterSingleton::runStringWithKey (const char * psCmd, const char * key, const char * key_initial_value = "")
Run a statement on the python interpreter with a key for exchanging strings.
runStringWithKey(psCmd, key, key_initial_value) psCmd is python script to run key is the name of a python string variable the script will have read/write access to during script execution. It will be our return value. key_initial_value is the initial value c++ will set before calling the script If the script runs successfully it will be able to change the value of key as the return value, but if there is a runtime error key will not be changed even if the error occurs after changing it inside the script.
Definition at line 281 of file Interpreter.cpp.
References src.Mod.PartDesign.fcgear.svggear::module, result, Path.Post.scripts.refactored_centroid_post::str, src.Mod.Test.testmakeWireString::String, and Base::PyException::ThrowException().
Referenced by PartGui::Workbench::Workbench().
strToPython() [1/2]
std::string InterpreterSingleton::strToPython (const char * Str) static
replaces all char with escapes for usage in python console
Definition at line 839 of file Interpreter.cpp.
References result.
Referenced by Gui::PropertyEditor::PropertyStringItem::setValue(), Gui::PropertyEditor::PropertyEnumItem::setValue(), Gui::PropertyEditor::PropertyStringListItem::setValue(), and Gui::Command::strToPython().
strToPython() [2/2]
static std::string Base::InterpreterSingleton::strToPython (const std::string & Str) inline static
Definition at line 362 of file Interpreter.h.
systemExit()
void InterpreterSingleton::systemExit ()
This shuts down the application.
Definition at line 343 of file Interpreter.cpp.
Member Data Documentation
_pcSingleton
InterpreterSingleton * InterpreterSingleton::_pcSingleton = nullptr static protected
Definition at line 372 of file Interpreter.h.
Referenced by Destruct(), and Instance().
The documentation for this class was generated from the following files:
Interpreter.h
Interpreter.cpp