FreeCAD: Gui::ViewProviderFeaturePythonImp Class Reference
Gui::ViewProviderFeaturePythonImp Class Reference
#include <ViewProviderFeaturePython.h>
Public Types
enum ValueT { NotImplemented = 0, Accepted = 1, Rejected = 2 }
Public Member Functions
ViewProviderFeaturePythonImp (ViewProviderDocumentObject *, App::PropertyPythonObject &)
constructor.
~ViewProviderFeaturePythonImp ()
destructor.
QIcon getIcon () const
bool claimChildren (std::vector< App::DocumentObject * > &) const
ValueT useNewSelectionModel () const
ValueT getElementPicked (const SoPickedPoint *pp, std::string &subname) const
bool getElement (const SoDetail *det, std::string &) const
bool getDetail (const char *, SoDetail *&det) const
ValueT getDetailPath (const char *name, SoFullPath *path, bool append, SoDetail *&det) const
std::vector< Base::Vector3d > getSelectionShape (const char *Element) const
ValueT setEdit (int ModNum)
ValueT unsetEdit (int ModNum)
ValueT setEditViewer (View3DInventorViewer *, int ModNum)
ValueT unsetEditViewer (View3DInventorViewer *)
ValueT doubleClicked ()
bool setupContextMenu (QMenu *menu)
Update data methods
void attach (App::DocumentObject *pcObject)
void updateData (const App::Property *)
void onChanged (const App::Property *prop)
void onBeforeChange (const App::Property *prop)
void startRestoring ()
void finishRestoring ()
ValueT onDelete (const std::vector< std::string > &sub)
ValueT canDelete (App::DocumentObject *obj) const
Display methods
ValueT isShow () const
Returns true if the icon must always appear enabled in the tree view.
bool getDefaultDisplayMode (std::string &mode) const
get the default display mode
std::vector< std::string > getDisplayModes () const
returns a list of all possible modes
std::string setDisplayMode (const char *ModeName)
set the display mode
ValueT canRemoveChildrenFromRoot () const
Drag and drop
ValueT canDragObjects () const
Returns true if the view provider generally supports dragging objects.
ValueT canDragObject (App::DocumentObject *) const
Check whether the object can be removed from the view provider by drag and drop.
ValueT dragObject (App::DocumentObject *)
Starts to drag the object.
ValueT canDropObjects () const
Returns true if the view provider generally accepts dropping of objects.
ValueT canDropObject (App::DocumentObject *) const
Check whether the object can be dropped to the view provider by drag and drop.
ValueT dropObject (App::DocumentObject *)
If the dropped object type is accepted the object will be added as child.
ValueT canDragAndDropObject (App::DocumentObject *) const
ValueT canDropObjectEx (App::DocumentObject *obj, App::DocumentObject *, const char *, const std::vector< std::string > &elements) const
bool dropObjectEx (App::DocumentObject *obj, App::DocumentObject *, const char *, const std::vector< std::string > &elements, std::string &ret)
ValueT replaceObject (App::DocumentObject *, App::DocumentObject *)
bool getLinkedViewProvider (ViewProviderDocumentObject *&res, std::string *subname, bool recursive) const
ValueT canAddToSceneGraph () const
bool getDropPrefix (std::string &prefix) const
bool editProperty (const char *propName)
void init (PyObject *pyobj)
Detailed Description
Definition at line 40 of file ViewProviderFeaturePython.h.
Member Enumeration Documentation
ValueT
enum Gui::ViewProviderFeaturePythonImp::ValueT
Enumerator
NotImplemented
Accepted
Rejected
Definition at line 43 of file ViewProviderFeaturePython.h.
Constructor & Destructor Documentation
ViewProviderFeaturePythonImp()
ViewProviderFeaturePythonImp::ViewProviderFeaturePythonImp (ViewProviderDocumentObject * vp, App::PropertyPythonObject & proxy)
constructor.
Definition at line 58 of file ViewProviderFeaturePython.cpp.
~ViewProviderFeaturePythonImp()
ViewProviderFeaturePythonImp::~ViewProviderFeaturePythonImp ()
destructor.
Definition at line 65 of file ViewProviderFeaturePython.cpp.
References SCL.SimpleDataTypes::e, and FC_PY_VIEW_OBJECT.
Member Function Documentation
attach()
void ViewProviderFeaturePythonImp::attach (App::DocumentObject * pcObject)
Definition at line 551 of file ViewProviderFeaturePython.cpp.
References _FC_PY_CALL_CHECK, toolbit-attributes::args, SCL.SimpleDataTypes::e, Gui::ViewProviderDocumentObject::getPyObject(), App::DocumentObject::Label, Base::pyCall(), and App::Property::touch().
Referenced by Path.Dressup.Gui.Boundary.DressupPathBoundaryViewProvider::__init__(), and Gui::ViewProviderFeaturePythonT< ViewProviderT >::onChanged().
canAddToSceneGraph()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::canAddToSceneGraph () const
Definition at line 756 of file ViewProviderFeaturePython.cpp.
References Accepted, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, NotImplemented, and Rejected.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::canAddToSceneGraph().
canDelete()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::canDelete (App::DocumentObject * obj) const
Definition at line 734 of file ViewProviderFeaturePython.cpp.
References Accepted, toolbit-attributes::args, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, App::DocumentObject::getPyObject(), NotImplemented, Base::pyCall(), and Rejected.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::canDelete().
canDragAndDropObject()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::canDragAndDropObject (App::DocumentObject * obj) const
Return false to force drop only operation for a give object
Definition at line 1014 of file ViewProviderFeaturePython.cpp.
References Accepted, toolbit-attributes::args, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, App::DocumentObject::getPyObject(), NotImplemented, Base::pyCall(), and Rejected.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::canDragAndDropObject().
canDragObject()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::canDragObject (App::DocumentObject * obj) const
Check whether the object can be removed from the view provider by drag and drop.
Definition at line 878 of file ViewProviderFeaturePython.cpp.
References Accepted, toolbit-attributes::args, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, App::DocumentObject::getPyObject(), NotImplemented, Base::pyCall(), and Rejected.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::canDragObject(), and draftviewproviders.view_layer.ViewProviderLayer::canDropObject().
canDragObjects()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::canDragObjects () const
Returns true if the view provider generally supports dragging objects.
Definition at line 856 of file ViewProviderFeaturePython.cpp.
References Accepted, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, NotImplemented, Base::pyCall(), and Rejected.
canDropObject()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::canDropObject (App::DocumentObject * obj) const
Check whether the object can be dropped to the view provider by drag and drop.
Definition at line 958 of file ViewProviderFeaturePython.cpp.
References Accepted, toolbit-attributes::args, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, App::DocumentObject::getPyObject(), NotImplemented, Base::pyCall(), and Rejected.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::canDropObject().
canDropObjectEx()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::canDropObjectEx (App::DocumentObject * obj, App::DocumentObject * owner, const char * subname, const std::vector< std::string > & elements) const
Query object dropping with full qualified name
Definition at line 1037 of file ViewProviderFeaturePython.cpp.
References Accepted, toolbit-attributes::args, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, App::DocumentObject::getPyObject(), SplineSurface::i, NotImplemented, Base::pyCall(), Rejected, and src.Mod.Test.testmakeWireString::String.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::canDropObjectEx().
canDropObjects()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::canDropObjects () const
Returns true if the view provider generally accepts dropping of objects.
Definition at line 936 of file ViewProviderFeaturePython.cpp.
References Accepted, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, NotImplemented, Base::pyCall(), and Rejected.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::canDropObjects().
canRemoveChildrenFromRoot()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::canRemoveChildrenFromRoot () const
Definition at line 1124 of file ViewProviderFeaturePython.cpp.
References Accepted, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, NotImplemented, Base::pyCall(), and Rejected.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::canRemoveChildrenFromRoot().
claimChildren()
bool ViewProviderFeaturePythonImp::claimChildren (std::vector< App::DocumentObject * > & children) const
Definition at line 155 of file ViewProviderFeaturePython.cpp.
References _FC_PY_CALL_CHECK, SCL.SimpleDataTypes::e, and Base::pyCall().
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::claimChildren(), femviewprovider.view_result_mechanical.VPResultMechanical::onDelete(), BOPTools.SplitFeatures.ViewProviderBooleanFragments::onDelete(), BOPTools.JoinFeatures.ViewProviderConnect::onDelete(), BOPTools.ToleranceFeatures.ViewProviderToleranceSet::onDelete(), femviewprovider.view_mesh_gmsh.VPMeshGmsh::onDelete(), CommandCreateView.ViewProviderExplodedView::onDelete(), CommandCreateSimulation.ViewProviderSimulation::onDelete(), BOPTools.SplitFeatures.ViewProviderSlice::onDelete(), and BOPTools.SplitFeatures.ViewProviderXOR::onDelete().
doubleClicked()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::doubleClicked ()
Definition at line 483 of file ViewProviderFeaturePython.cpp.
References Accepted, toolbit-attributes::args, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, Gui::ViewProviderDocumentObject::getPyObject(), NotImplemented, Base::pyCall(), and Rejected.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::doubleClicked().
dragObject()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::dragObject (App::DocumentObject * obj)
Starts to drag the object.
Definition at line 902 of file ViewProviderFeaturePython.cpp.
References Accepted, toolbit-attributes::args, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, Gui::ViewProviderDocumentObject::getPyObject(), App::DocumentObject::getPyObject(), NotImplemented, Base::pyCall(), and Rejected.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::dragObject().
dropObject()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::dropObject (App::DocumentObject * obj)
If the dropped object type is accepted the object will be added as child.
Definition at line 982 of file ViewProviderFeaturePython.cpp.
References Accepted, toolbit-attributes::args, FC_PY_CALL_CHECK, Gui::ViewProviderDocumentObject::getPyObject(), App::DocumentObject::getPyObject(), NotImplemented, Base::pyCall(), Rejected, and Base::PyException::ThrowException().
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::dropObject().
dropObjectEx()
bool ViewProviderFeaturePythonImp::dropObjectEx (App::DocumentObject * obj, App::DocumentObject * owner, const char * subname, const std::vector< std::string > & elements, std::string & ret)
Add an object with full qualified name to the view provider by drag and drop
Definition at line 1068 of file ViewProviderFeaturePython.cpp.
References _FC_PY_CALL_CHECK, toolbit-attributes::args, Gui::ViewProviderDocumentObject::getPyObject(), App::DocumentObject::getPyObject(), SplineSurface::i, Base::pyCall(), src.Mod.Test.testmakeWireString::String, and Base::PyException::ThrowException().
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::dropObjectEx().
editProperty()
bool ViewProviderFeaturePythonImp::editProperty (const char * propName)
Definition at line 1237 of file ViewProviderFeaturePython.cpp.
References _FC_PY_CALL_CHECK, toolbit-attributes::args, SCL.SimpleDataTypes::e, Base::pyCall(), and src.Mod.Test.testmakeWireString::String.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::editProperty().
finishRestoring()
void ViewProviderFeaturePythonImp::finishRestoring ()
Definition at line 677 of file ViewProviderFeaturePython.cpp.
References _FC_PY_CALL_CHECK, SCL.SimpleDataTypes::e, App::PropertyPythonObject::getValue(), Base::pyCall(), and App::PropertyPythonObject::setValue().
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::finishRestoring().
getDefaultDisplayMode()
bool ViewProviderFeaturePythonImp::getDefaultDisplayMode (std::string & mode) const
get the default display mode
Definition at line 775 of file ViewProviderFeaturePython.cpp.
References _FC_PY_CALL_CHECK, SCL.SimpleDataTypes::e, Base::pyCall(), Path.Post.scripts.refactored_centroid_post::str, and src.Mod.Test.testmakeWireString::String.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::getDefaultDisplayMode().
getDetail()
bool ViewProviderFeaturePythonImp::getDetail (const char * name, SoDetail *& det) const
Definition at line 270 of file ViewProviderFeaturePython.cpp.
References _FC_PY_CALL_CHECK, toolbit-attributes::args, Base::InterpreterSingleton::convertSWIGPointerObj(), SCL.SimpleDataTypes::e, Base::Interpreter(), Base::pyCall(), and src.Mod.Test.testmakeWireString::String.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::getDetail().
getDetailPath()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::getDetailPath (const char * name, SoFullPath * path, bool append, SoDetail *& det) const
Definition at line 301 of file ViewProviderFeaturePython.cpp.
References Accepted, Path.Post.scripts.uccnc_post::append(), toolbit-attributes::args, Base::InterpreterSingleton::convertSWIGPointerObj(), Base::InterpreterSingleton::createSWIGPointerObj(), SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, Base::Interpreter(), NotImplemented, Base::pyCall(), Rejected, and src.Mod.Test.testmakeWireString::String.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::getDetailPath().
getDisplayModes()
std::vector< std::string > ViewProviderFeaturePythonImp::getDisplayModes () const
returns a list of all possible modes
Definition at line 798 of file ViewProviderFeaturePython.cpp.
References _FC_PY_CALL_CHECK, toolbit-attributes::args, SCL.SimpleDataTypes::e, Gui::ViewProviderDocumentObject::getPyObject(), modes, Base::pyCall(), Path.Post.scripts.refactored_centroid_post::str, and src.Mod.Test.testmakeWireString::String.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::getDisplayModes().
getDropPrefix()
bool ViewProviderFeaturePythonImp::getDropPrefix (std::string & prefix) const
Definition at line 1144 of file ViewProviderFeaturePython.cpp.
References _FC_PY_CALL_CHECK, SCL.SimpleDataTypes::e, and Base::pyCall().
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::getDropPrefix().
getElement()
bool ViewProviderFeaturePythonImp::getElement (const SoDetail * det, std::string & res) const
Definition at line 205 of file ViewProviderFeaturePython.cpp.
References _FC_PY_CALL_CHECK, toolbit-attributes::args, Base::InterpreterSingleton::createSWIGPointerObj(), SCL.SimpleDataTypes::e, Base::Interpreter(), Base::pyCall(), and src.Mod.Test.testmakeWireString::String.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::getElement().
getElementPicked()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::getElementPicked (const SoPickedPoint * pp, std::string & subname) const
Definition at line 239 of file ViewProviderFeaturePython.cpp.
References Accepted, toolbit-attributes::args, Base::InterpreterSingleton::createSWIGPointerObj(), SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, Base::Interpreter(), NotImplemented, Base::pyCall(), and Rejected.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::getElementPicked().
getIcon()
QIcon ViewProviderFeaturePythonImp::getIcon () const
Definition at line 91 of file ViewProviderFeaturePython.cpp.
References _FC_PY_CALL_CHECK, Gui::BitmapFactory(), SCL.SimpleDataTypes::e, Gui::PythonWrapper::loadGuiModule(), Gui::PythonWrapper::loadWidgetsModule(), Base::pyCall(), src.Mod.Test.testmakeWireString::String, Gui::PythonWrapper::toQIcon(), and Materials::trim().
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::getIcon(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchWindow._ArchWindowTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), ArchComponent.ComponentTaskPanel::update(), bimcommands.BimClassification.BIM_Classification::updateByMaterial(), bimcommands.BimClassification.BIM_Classification::updateByTree(), bimcommands.BimClassification.BIM_Classification::updateByType(), and bimcommands.BimClassification.BIM_Classification::updateDefault().
getLinkedViewProvider()
bool ViewProviderFeaturePythonImp::getLinkedViewProvider (ViewProviderDocumentObject *& res, std::string * subname, bool recursive) const
Definition at line 1195 of file ViewProviderFeaturePython.cpp.
References _FC_PY_CALL_CHECK, toolbit-attributes::args, SCL.SimpleDataTypes::e, FC_ERR, Base::pyCall(), and src.Mod.Test.testmakeWireString::String.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::getLinkedViewProvider().
getSelectionShape()
std::vector< Base::Vector3d > ViewProviderFeaturePythonImp::getSelectionShape (const char * Element) const
Definition at line 345 of file ViewProviderFeaturePython.cpp.
init()
void ViewProviderFeaturePythonImp::init (PyObject * pyobj)
Definition at line 79 of file ViewProviderFeaturePython.cpp.
References FC_PY_VIEW_OBJECT.
Referenced by DocumentObject.DocumentObject::onChanged(), and Gui::ViewProviderFeaturePythonT< ViewProviderT >::onChanged().
isShow()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::isShow () const
Returns true if the icon must always appear enabled in the tree view.
Definition at line 1101 of file ViewProviderFeaturePython.cpp.
References Accepted, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, NotImplemented, Base::pyCall(), and Rejected.
onBeforeChange()
void ViewProviderFeaturePythonImp::onBeforeChange (const App::Property * prop)
Definition at line 641 of file ViewProviderFeaturePython.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, Gui::ViewProviderDocumentObject::getPyObject(), Base::pyCall(), and src.Mod.Test.testmakeWireString::String.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::onBeforeChange().
onChanged()
void ViewProviderFeaturePythonImp::onChanged (const App::Property * prop)
Definition at line 609 of file ViewProviderFeaturePython.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, Gui::ViewProviderDocumentObject::getPyObject(), Base::pyCall(), and src.Mod.Test.testmakeWireString::String.
Referenced by draftviewproviders.view_base.ViewProviderDraft::attach(), Gui::ViewProviderFeaturePythonT< ViewProviderT >::onChanged(), ArchSpace._ViewProviderSpace::onChanged(), ArchSchedule._ArchSchedule::setProperties(), draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), ArchAxis._ViewProviderAxis::updateData(), draftviewproviders.view_dimension.ViewProviderLinearDimension::updateData(), ArchSpace._ViewProviderSpace::updateData(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchSite._ViewProviderSite::updateData(), ArchSectionPlane._ViewProviderSectionPlane::updateData(), and ArchPanel.ViewProviderPanelSheet::updateData().
onDelete()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::onDelete (const std::vector< std::string > & sub)
Definition at line 696 of file ViewProviderFeaturePython.cpp.
References Accepted, toolbit-attributes::args, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, Gui::ViewProviderDocumentObject::getPyObject(), NotImplemented, Base::pyCall(), Rejected, and src.Mod.Test.testmakeWireString::String.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::onDelete().
replaceObject()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::replaceObject (App::DocumentObject * oldObj, App::DocumentObject * newObj)
Definition at line 1168 of file ViewProviderFeaturePython.cpp.
References Accepted, toolbit-attributes::args, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, App::DocumentObject::getPyObject(), App::DocumentObject::isAttachedToDocument(), NotImplemented, Base::pyCall(), and Rejected.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::replaceObject().
setDisplayMode()
std::string ViewProviderFeaturePythonImp::setDisplayMode (const char * ModeName)
set the display mode
Definition at line 835 of file ViewProviderFeaturePython.cpp.
References _FC_PY_CALL_CHECK, toolbit-attributes::args, SCL.SimpleDataTypes::e, Base::pyCall(), Path.Post.scripts.refactored_centroid_post::str, and src.Mod.Test.testmakeWireString::String.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::setDisplayMode().
setEdit()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::setEdit (int ModNum)
Definition at line 351 of file ViewProviderFeaturePython.cpp.
References Accepted, toolbit-attributes::args, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, Gui::ViewProviderDocumentObject::getPyObject(), NotImplemented, Base::pyCall(), and Rejected.
Referenced by Path.Base.Gui.PropertyBag.ViewProvider::doubleClicked(), Path.Base.Gui.SetupSheet.ViewProvider::doubleClicked(), Path.Tool.Gui.Bit.ViewProvider::doubleClicked(), Gui::ViewProviderFeaturePythonT< ViewProviderT >::setEdit(), Path.Base.Gui.IconViewProvider.ViewProvider::setupContextMenu(), Path.Tool.Gui.Controller.ViewProvider::setupContextMenu(), Path.Op.Gui.Base.ViewProvider::setupContextMenu(), and Path.Main.Gui.Job.ViewProvider::setupContextMenu().
setEditViewer()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::setEditViewer (View3DInventorViewer * viewer, int ModNum)
Definition at line 433 of file ViewProviderFeaturePython.cpp.
References Accepted, toolbit-attributes::args, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, Gui::ViewProviderDocumentObject::getPyObject(), NotImplemented, Base::pyCall(), Rejected, and OfflineRenderingUtils::viewer().
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::setEditViewer().
setupContextMenu()
bool ViewProviderFeaturePythonImp::setupContextMenu (QMenu * menu)
Definition at line 515 of file ViewProviderFeaturePython.cpp.
References _FC_PY_CALL_CHECK, toolbit-attributes::args, SCL.SimpleDataTypes::e, Gui::PythonWrapper::fromQWidget(), Gui::ViewProviderDocumentObject::getPyObject(), Gui::PythonWrapper::loadGuiModule(), Gui::PythonWrapper::loadWidgetsModule(), NavigationIndicatorGui::menu, and Base::pyCall().
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::setupContextMenu().
startRestoring()
void ViewProviderFeaturePythonImp::startRestoring ()
Definition at line 673 of file ViewProviderFeaturePython.cpp.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::startRestoring().
unsetEdit()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::unsetEdit (int ModNum)
Definition at line 392 of file ViewProviderFeaturePython.cpp.
References Accepted, toolbit-attributes::args, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, Gui::ViewProviderDocumentObject::getPyObject(), NotImplemented, Base::pyCall(), and Rejected.
Referenced by Path.Main.Gui.Job.ViewProvider::uneditObject(), and Gui::ViewProviderFeaturePythonT< ViewProviderT >::unsetEdit().
unsetEditViewer()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::unsetEditViewer (View3DInventorViewer * viewer)
Definition at line 458 of file ViewProviderFeaturePython.cpp.
References Accepted, toolbit-attributes::args, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, Gui::ViewProviderDocumentObject::getPyObject(), NotImplemented, Base::pyCall(), Rejected, and OfflineRenderingUtils::viewer().
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::unsetEditViewer().
updateData()
void ViewProviderFeaturePythonImp::updateData (const App::Property * prop)
Definition at line 577 of file ViewProviderFeaturePython.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, Gui::ViewProviderDocumentObject::getObject(), App::DocumentObject::getPyObject(), Base::pyCall(), and src.Mod.Test.testmakeWireString::String.
Referenced by Path.Main.Gui.JobDlg.JobCreate::exec_(), draftviewproviders.view_wire.ViewProviderWire::onChanged(), draftviewproviders.view_dimension.ViewProviderLinearDimension::onChanged(), draftviewproviders.view_dimension.ViewProviderAngularDimension::onChanged(), Path.Op.Gui.Base.TaskPanelPage::pageUpdateData(), Path.Base.Gui.SetupSheet.OpTaskPanel::setupUi(), Path.Base.Gui.PropertyBag.TaskPanel::setupUi(), and Gui::ViewProviderFeaturePythonT< ViewProviderT >::updateData().
useNewSelectionModel()
ViewProviderFeaturePythonImp::ValueT ViewProviderFeaturePythonImp::useNewSelectionModel () const
Definition at line 183 of file ViewProviderFeaturePython.cpp.
References Accepted, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, NotImplemented, and Rejected.
Referenced by Gui::ViewProviderFeaturePythonT< ViewProviderT >::useNewSelectionModel().
The documentation for this class was generated from the following files:
ViewProviderFeaturePython.h
ViewProviderFeaturePython.cpp