FreeCAD: Gui::GraphicsScene Class Reference
Gui::GraphicsScene Class Reference
#include <GLGraphicsView.h>
Public Member Functions
GraphicsScene ()
virtual ~GraphicsScene ()
void drawBackground (QPainter *painter, const QRectF &rect)
void setBackgroundColor (const QColor &)
void viewAll ()
void setSceneGraph (SoNode *node)
SoNode * getSceneGraph () const
SceneEventFilter * getEventFilter (void) const
void addStateMachine (SoScXMLStateMachine *statemachine)
void removeStateMachine (SoScXMLStateMachine *statemachine)
void setNavigationModeFile (const QUrl &)
bool processSoEvent (const SoEvent *event)
SoRenderManager * getSoRenderManager (void) const
SoEventManager * getSoEventManager (void) const
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void wheelEvent (QGraphicsSceneWheelEvent *wheelEvent)
Detailed Description
Definition at line 67 of file GLGraphicsView.h.
Constructor & Destructor Documentation
GraphicsScene()
GraphicsScene::GraphicsScene ()
Definition at line 308 of file GLGraphicsView.cpp.
References draftgeoutils.intersections::connect(), SCL.SimpleDataTypes::f, src.Mod.Test.testPathArray::items, and RobotExample::pos.
~GraphicsScene()
GraphicsScene::~GraphicsScene () virtual
Definition at line 370 of file GLGraphicsView.cpp.
Member Function Documentation
addStateMachine()
void GraphicsScene::addStateMachine (SoScXMLStateMachine * statemachine)
Definition at line 403 of file GLGraphicsView.cpp.
References OfflineRenderingUtils::getCamera(), getSceneGraph(), getSoEventManager(), and getSoRenderManager().
Referenced by setNavigationModeFile().
drawBackground()
void GraphicsScene::drawBackground (QPainter * painter, const QRectF & rect)
Definition at line 566 of file GLGraphicsView.cpp.
getEventFilter()
SceneEventFilter * GraphicsScene::getEventFilter (void) const
Definition at line 387 of file GLGraphicsView.cpp.
Referenced by Gui::GraphicsView3D::GraphicsView3D().
getSceneGraph()
SoNode * GraphicsScene::getSceneGraph () const
Definition at line 480 of file GLGraphicsView.cpp.
Referenced by addStateMachine().
getSoEventManager()
SoEventManager * GraphicsScene::getSoEventManager (void) const
Definition at line 554 of file GLGraphicsView.cpp.
Referenced by addStateMachine(), and removeStateMachine().
getSoRenderManager()
SoRenderManager * GraphicsScene::getSoRenderManager (void) const
Definition at line 548 of file GLGraphicsView.cpp.
Referenced by addStateMachine().
mouseMoveEvent()
void GraphicsScene::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected
Definition at line 604 of file GLGraphicsView.cpp.
mousePressEvent()
void GraphicsScene::mousePressEvent (QGraphicsSceneMouseEvent * event) protected
Definition at line 615 of file GLGraphicsView.cpp.
mouseReleaseEvent()
void GraphicsScene::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected
Definition at line 627 of file GLGraphicsView.cpp.
processSoEvent()
bool GraphicsScene::processSoEvent (const SoEvent * event)
Definition at line 393 of file GLGraphicsView.cpp.
removeStateMachine()
void GraphicsScene::removeStateMachine (SoScXMLStateMachine * statemachine)
Definition at line 412 of file GLGraphicsView.cpp.
References getSoEventManager().
setBackgroundColor()
void GraphicsScene::setBackgroundColor (const QColor & color)
Definition at line 589 of file GLGraphicsView.cpp.
Referenced by Gui::GraphicsView3D::OnChange().
setNavigationModeFile()
void GraphicsScene::setNavigationModeFile (const QUrl & url)
Definition at line 421 of file GLGraphicsView.cpp.
References addStateMachine(), DrawingExample::file, and readFile().
Referenced by Gui::GraphicsView3D::GraphicsView3D().
setSceneGraph()
void GraphicsScene::setSceneGraph (SoNode * node)
Definition at line 502 of file GLGraphicsView.cpp.
References viewAll().
Referenced by Gui::GraphicsView3D::GraphicsView3D().
viewAll()
void GraphicsScene::viewAll ()
Definition at line 379 of file GLGraphicsView.cpp.
Referenced by Gui::GraphicsView3D::GraphicsView3D(), and setSceneGraph().
wheelEvent()
void GraphicsScene::wheelEvent (QGraphicsSceneWheelEvent * wheelEvent) protected
Definition at line 637 of file GLGraphicsView.cpp.
The documentation for this class was generated from the following files:
GLGraphicsView.h
GLGraphicsView.cpp