FreeCAD: MeshCore::LaplaceSmoothing Class Reference
MeshCore::LaplaceSmoothing Class Reference
#include <Smoothing.h>
Public Member Functions
LaplaceSmoothing (MeshKernel &)
void Smooth (unsigned int) override
void SmoothPoints (unsigned int, const std::vector< PointIndex > &) override
void SetLambda (double l)
double GetLambda () const
Public Member Functions inherited from MeshCore::AbstractSmoothing
AbstractSmoothing (MeshKernel &)
virtual ~AbstractSmoothing ()
AbstractSmoothing (const AbstractSmoothing &)=delete
AbstractSmoothing (AbstractSmoothing &&)=delete
AbstractSmoothing & operator= (const AbstractSmoothing &)=delete
AbstractSmoothing & operator= (AbstractSmoothing &&)=delete
void initialize (Component comp, Continuity cont)
Protected Member Functions
void Umbrella (const MeshRefPointToPoints &, const MeshRefPointToFacets &, double)
void Umbrella (const MeshRefPointToPoints &, const MeshRefPointToFacets &, double, const std::vector< PointIndex > &)
Additional Inherited Members
Public Types inherited from MeshCore::AbstractSmoothing
enum Component { Tangential, Normal, TangentialNormal }
enum Continuity { C0, C1, C2 }
Protected Attributes inherited from MeshCore::AbstractSmoothing
MeshKernel & kernel
Component component {Normal}
Continuity continuity {C0}
Detailed Description
Definition at line 114 of file Smoothing.h.
Constructor & Destructor Documentation
LaplaceSmoothing()
LaplaceSmoothing::LaplaceSmoothing (MeshKernel & m) explicit
Definition at line 168 of file Smoothing.cpp.
Member Function Documentation
GetLambda()
double MeshCore::LaplaceSmoothing::GetLambda () const inline
Definition at line 124 of file Smoothing.h.
Referenced by MeshCore::TaubinSmoothing::Smooth(), and MeshCore::TaubinSmoothing::SmoothPoints().
SetLambda()
void MeshCore::LaplaceSmoothing::SetLambda (double l) inline
Definition at line 120 of file Smoothing.h.
Smooth()
void LaplaceSmoothing::Smooth (unsigned int) override virtual
Smooth the triangle mesh.
Implements MeshCore::AbstractSmoothing.
Reimplemented in MeshCore::TaubinSmoothing.
Definition at line 246 of file Smoothing.cpp.
References SplineSurface::i, MeshCore::AbstractSmoothing::kernel, and Umbrella().
Referenced by MeshGui::Segmentation::accept(), ReverseEngineeringGui::Segmentation::accept(), and MeshCore::MeshKernel::Smooth().
SmoothPoints()
void LaplaceSmoothing::SmoothPoints (unsigned int iterations, const std::vector< PointIndex > & point_indices) override virtual
Implements MeshCore::AbstractSmoothing.
Reimplemented in MeshCore::TaubinSmoothing.
Definition at line 256 of file Smoothing.cpp.
References SplineSurface::i, MeshCore::AbstractSmoothing::kernel, and Umbrella().
Umbrella() [1/2]
void LaplaceSmoothing::Umbrella (const MeshRefPointToPoints & vv_it, const MeshRefPointToFacets & vf_it, double stepsize) protected
Definition at line 172 of file Smoothing.cpp.
References MeshCore::MeshKernel::GetPoints(), MeshCore::AbstractSmoothing::kernel, RobotExample::pos, MeshCore::MeshKernel::SetPoint(), src.Mod.PartDesign.fcgear.svggear::w, MovieTool::x, and MovieTool::y.
Referenced by Smooth(), MeshCore::TaubinSmoothing::Smooth(), SmoothPoints(), and MeshCore::TaubinSmoothing::SmoothPoints().
Umbrella() [2/2]
void LaplaceSmoothing::Umbrella (const MeshRefPointToPoints & vv_it, const MeshRefPointToFacets & vf_it, double stepsize, const std::vector< PointIndex > & point_indices) protected
Definition at line 209 of file Smoothing.cpp.
References MeshCore::MeshKernel::GetPoints(), MeshCore::AbstractSmoothing::kernel, MeshCore::MeshKernel::SetPoint(), src.Mod.PartDesign.fcgear.svggear::w, MovieTool::x, and MovieTool::y.
The documentation for this class was generated from the following files:
Smoothing.h
Smoothing.cpp