FreeCAD: Wm4::IntrLine3Box3< Real > Class Template Reference
Wm4::IntrLine3Box3< Real > Class Template Reference
#include <Wm4IntrLine3Box3.h>
Public Member Functions
IntrLine3Box3 (const Line3< Real > &rkLine, const Box3< Real > &rkBox)
const Line3< Real > & GetLine () const
const Box3< Real > & GetBox () const
virtual bool Test ()
virtual bool Find ()
int GetQuantity () const
const Vector3< Real > & GetPoint (int i) const
Public Member Functions inherited from Wm4::Intersector< Real, Vector3< Real > >
virtual ~Intersector ()
virtual bool Test (Real fTMax, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
virtual bool Find (Real fTMax, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
Real GetContactTime () const
int GetIntersectionType () const
Static Public Member Functions
static bool DoClipping (Real fT0, Real fT1, const Vector3< Real > &rkOrigin, const Vector3< Real > &rkDirection, const Box3< Real > &rkBox, bool bSolid, int &riQuantity, Vector3< Real > akPoint[2], int &riIntrType)
Additional Inherited Members
Public Types inherited from Wm4::Intersector< Real, Vector3< Real > >
enum
Protected Member Functions inherited from Wm4::Intersector< Real, Vector3< Real > >
Intersector ()
Protected Attributes inherited from Wm4::Intersector< Real, Vector3< Real > >
Real m_fContactTime
int m_iIntersectionType
Detailed Description
template<class Real>
class Wm4::IntrLine3Box3< Real >
Definition at line 29 of file Wm4IntrLine3Box3.h.
Constructor & Destructor Documentation
IntrLine3Box3()
template<class Real > Wm4::IntrLine3Box3< Real >::IntrLine3Box3 (const Line3< Real > & rkLine, const Box3< Real > & rkBox)
Definition at line 24 of file Wm4IntrLine3Box3.cpp.
Member Function Documentation
DoClipping()
template<class Real > bool Wm4::IntrLine3Box3< Real >::DoClipping (Real fT0, Real fT1, const Vector3< Real > & rkOrigin, const Vector3< Real > & rkDirection, const Box3< Real > & rkBox, bool bSolid, int & riQuantity, Vector3< Real > akPoint[2], int & riIntrType) static
Definition at line 101 of file Wm4IntrLine3Box3.cpp.
References Wm4::Box3< Real >::Axis, Wm4::Box3< Real >::Center, Wm4::Vector3< Real >::Dot(), Wm4::Box3< Real >::Extent, Wm4::Vector3< Real >::X(), Wm4::Vector3< Real >::Y(), and Wm4::Vector3< Real >::Z().
Referenced by Wm4::IntrSegment3Box3< Real >::Find().
Find()
template<class Real > bool Wm4::IntrLine3Box3< Real >::Find virtual
Reimplemented from Wm4::Intersector< Real, Vector3< Real > >.
Definition at line 80 of file Wm4IntrLine3Box3.cpp.
GetBox()
template<class Real > const Box3< Real > & Wm4::IntrLine3Box3< Real >::GetBox
Definition at line 39 of file Wm4IntrLine3Box3.cpp.
GetLine()
template<class Real > const Line3< Real > & Wm4::IntrLine3Box3< Real >::GetLine
Definition at line 33 of file Wm4IntrLine3Box3.cpp.
GetPoint()
template<class Real > const Vector3< Real > & Wm4::IntrLine3Box3< Real >::GetPoint (int i) const
Definition at line 94 of file Wm4IntrLine3Box3.cpp.
References SplineSurface::i.
GetQuantity()
template<class Real > int Wm4::IntrLine3Box3< Real >::GetQuantity
Definition at line 88 of file Wm4IntrLine3Box3.cpp.
Test()
template<class Real > bool Wm4::IntrLine3Box3< Real >::Test virtual
Reimplemented from Wm4::Intersector< Real, Vector3< Real > >.
Definition at line 45 of file Wm4IntrLine3Box3.cpp.
References Wm4::Vector3< Real >::Cross(), Wm4::Vector3< Real >::Dot(), and Wm4::Math< Real >::FAbs().
The documentation for this class was generated from the following files:
Wm4IntrLine3Box3.h
Wm4IntrLine3Box3.cpp