FreeCAD: MeshCore::MeshSimplify Class Reference
MeshCore::MeshSimplify Class Reference
#include <Decimation.h>
Public Member Functions
MeshSimplify (MeshKernel &)
void simplify (float tolerance, float reduction)
void simplify (int targetSize)
Detailed Description
Definition at line 53 of file Decimation.h.
Constructor & Destructor Documentation
MeshSimplify()
MeshSimplify::MeshSimplify (MeshKernel & mesh) explicit
Definition at line 32 of file Decimation.cpp.
Member Function Documentation
simplify() [1/2]
void MeshSimplify::simplify (float tolerance, float reduction)
Definition at line 36 of file Decimation.cpp.
References MeshCore::MeshFacet::_aulPoints, MeshCore::MeshKernel::Adopt(), MeshCore::MeshKernel::GetFacets(), MeshCore::MeshKernel::GetPoints(), SplineSurface::i, Simplify::simplify_mesh(), InitGui::t, draftutils.utils::tolerance(), Simplify::triangles, TestSpreadsheet::v, and Simplify::vertices.
Referenced by Mesh::MeshObject::decimate().
simplify() [2/2]
void MeshSimplify::simplify (int targetSize)
Definition at line 97 of file Decimation.cpp.
References MeshCore::MeshFacet::_aulPoints, MeshCore::MeshKernel::Adopt(), MeshCore::MeshKernel::GetFacets(), MeshCore::MeshKernel::GetPoints(), SplineSurface::i, Simplify::simplify_mesh(), InitGui::t, Simplify::triangles, TestSpreadsheet::v, and Simplify::vertices.
The documentation for this class was generated from the following files:
Decimation.h
Decimation.cpp