FreeCAD: ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern Class Reference
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern Class Reference
Public Member Functions
def __init__ (self, inherited0__name, inherited1__rationale, inherited2__base_solid, inherited3__placing, inherited4__replicated_element, replicate_count, angular_spacing, radial_alignment, reference_point)
def replicate_count ()
def angular_spacing ()
def radial_alignment ()
def reference_point ()
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_shape_element_pattern
def __init__ (self, inherited0__name, inherited1__rationale, inherited2__base_solid, inherited3__placing, replicated_element)
def replicated_element ()
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.modified_solid_with_placed_configuration
def __init__ (self, inherited0__name, inherited1__rationale, inherited2__base_solid, placing)
def placing ()
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.modified_solid
def __init__ (self, inherited0__name, rationale, base_solid)
def rationale ()
def base_solid ()
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_model
def __init__ (self, inherited0__name)
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_representation_item
def dim ()
def wr1 (self)
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation_item
def name ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
replicate_count
angular_spacing
radial_alignment
reference_point
Public Attributes inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_shape_element_pattern
replicated_element
Public Attributes inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.modified_solid_with_placed_configuration
placing
Public Attributes inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.modified_solid
rationale
base_solid
Public Attributes inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation_item
name
Detailed Description
Entity solid_with_circular_pattern definition.
:param replicate_count
:type replicate_count:positive_integer
:param angular_spacing
:type angular_spacing:plane_angle_measure
:param radial_alignment
:type radial_alignment:BOOLEAN
:param reference_point
:type reference_point:point
Definition at line 3774 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Constructor & Destructor Documentation
__init__()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern.__init__ (self, inherited0__name, inherited1__rationale, inherited2__base_solid, inherited3__placing, inherited4__replicated_element, replicate_count, angular_spacing, radial_alignment, reference_point)
Definition at line 3789 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Member Function Documentation
angular_spacing()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern.angular_spacing ()
Definition at line 3811 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern._angular_spacing, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern.angular_spacing, and SCL.TypeChecker.check_type().
radial_alignment()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern.radial_alignment ()
Definition at line 3825 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern._radial_alignment, SCL.SimpleDataTypes.BOOLEAN, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern.radial_alignment.
reference_point()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern.reference_point ()
Definition at line 3839 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern._reference_point, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern.reference_point.
replicate_count()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern.replicate_count ()
Definition at line 3797 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern._replicate_count, SCL.TypeChecker.check_type(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern.replicate_count.
Member Data Documentation
angular_spacing
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern.angular_spacing
Definition at line 3792 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern.angular_spacing().
radial_alignment
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern.radial_alignment
Definition at line 3793 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern.radial_alignment().
reference_point
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern.reference_point
Definition at line 3794 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern.reference_point(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_general_pocket.wr2(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_general_protrusion.wr2().
replicate_count
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern.replicate_count
Definition at line 3791 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pattern.replicate_count().
The documentation for this class was generated from the following file:
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py