FreeCAD: Gui::Dialog::DocumentRecoveryCleaner Class Reference
Gui::Dialog::DocumentRecoveryCleaner Class Reference
#include <DocumentRecovery.h>
Public Member Functions
void clearDirectory (const QFileInfo &dir)
void setIgnoreFiles (const QStringList &)
void setIgnoreDirectories (const QFileInfoList &)
Detailed Description
Definition at line 126 of file DocumentRecovery.h.
Member Function Documentation
clearDirectory()
void DocumentRecoveryCleaner::clearDirectory (const QFileInfo & dir)
Definition at line 688 of file DocumentRecovery.cpp.
References DrawingExample::file.
Referenced by Gui::Dialog::DocumentRecovery::accept(), Gui::Dialog::DocumentRecovery::cleanup(), and Gui::Dialog::DocumentRecovery::onDeleteSection().
setIgnoreDirectories()
void DocumentRecoveryCleaner::setIgnoreDirectories (const QFileInfoList & list)
Definition at line 744 of file DocumentRecovery.cpp.
setIgnoreFiles()
void DocumentRecoveryCleaner::setIgnoreFiles (const QStringList & list)
Definition at line 739 of file DocumentRecovery.cpp.
The documentation for this class was generated from the following files:
DocumentRecovery.h
DocumentRecovery.cpp