FreeCAD: MatGui::ListDelegate Class Reference
MatGui::ListDelegate Class Reference
#include <ListDelegate.h>
Public Member Functions
ListDelegate (Materials::MaterialValue::ValueType type=Materials::MaterialValue::None, const QString &units=QString(), QObject *parent=nullptr)
virtual ~ListDelegate ()=default
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const override
Public Member Functions inherited from MatGui::BaseDelegate
BaseDelegate (QObject *parent=nullptr)
virtual ~BaseDelegate ()=default
QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const override
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const override
QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &styleOption, const QModelIndex &index) const override
void setEditorData (QWidget *editor, const QModelIndex &index) const override
void setModelData (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const override
Protected Member Functions
Materials::MaterialValue::ValueType getType (const QModelIndex &index) const override
QString getUnits (const QModelIndex &index) const override
QVariant getValue (const QModelIndex &index) const override
void setValue (QAbstractItemModel *model, const QModelIndex &index, const QVariant &value) const override
void notifyChanged (const QAbstractItemModel *model, const QModelIndex &index) const override
Protected Member Functions inherited from MatGui::BaseDelegate
QString getStringValue (const QModelIndex &index) const
QRgb parseColor (const QString &color) const
void paintQuantity (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
void paintImage (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
void paintSVG (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
void paintColor (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
void paintList (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
void paintMultiLineString (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
void paintArray (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
virtual bool newRow (const QAbstractItemModel *model, const QModelIndex &index) const
QWidget * createWidget (QWidget *parent, const QVariant &item, const QModelIndex &index) const
Detailed Description
Definition at line 60 of file ListDelegate.h.
Constructor & Destructor Documentation
ListDelegate()
ListDelegate::ListDelegate (Materials::MaterialValue::ValueType type = Materials::MaterialValue::None, const QString & units = QString(), QObject * parent = nullptr)
Definition at line 57 of file ListDelegate.cpp.
~ListDelegate()
virtual MatGui::ListDelegate::~ListDelegate () virtual default
Member Function Documentation
getType()
Materials::MaterialValue::ValueType MatGui::ListDelegate::getType (const QModelIndex & index) const inline override protected virtual
Emits this signal when a property has changed
Implements MatGui::BaseDelegate.
Definition at line 93 of file ListDelegate.h.
Referenced by paint().
getUnits()
QString MatGui::ListDelegate::getUnits (const QModelIndex & index) const inline override protected virtual
Implements MatGui::BaseDelegate.
Definition at line 98 of file ListDelegate.h.
getValue()
QVariant ListDelegate::getValue (const QModelIndex & index) const override protected virtual
Implements MatGui::BaseDelegate.
Definition at line 65 of file ListDelegate.cpp.
notifyChanged()
void ListDelegate::notifyChanged (const QAbstractItemModel * model, const QModelIndex & index) const override protected virtual
Implements MatGui::BaseDelegate.
Definition at line 85 of file ListDelegate.cpp.
Referenced by setValue().
paint()
void ListDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const override
Definition at line 91 of file ListDelegate.cpp.
References getType(), Materials::MaterialValue::Image, Materials::MaterialValue::ImageList, MatGui::BaseDelegate::paintImage(), MatGui::BaseDelegate::paintQuantity(), Materials::MaterialValue::Quantity, and Path.Post.scripts.grbl_post::type.
setValue()
void ListDelegate::setValue (QAbstractItemModel * model, const QModelIndex & index, const QVariant & value) const override protected virtual
Implements MatGui::BaseDelegate.
Definition at line 73 of file ListDelegate.cpp.
References notifyChanged(), and MatGui::ListModel::setData().
The documentation for this class was generated from the following files:
ListDelegate.h
ListDelegate.cpp