FreeCAD: TopoShape.cpp File Reference
TopoShape.cpp File Reference
#include "PreCompiled.h"
#include <array>
#include <cmath>
#include <cstdlib>
#include <sstream>
#include <boost/regex.hpp>
#include <APIHeaderSection_MakeHeader.hxx>
#include <BinTools.hxx>
#include <BinTools_ShapeSet.hxx>
#include <Bnd_Box.hxx>
#include <BRep_Builder.hxx>
#include <BRep_Tool.hxx>
#include <BRepAdaptor_Surface.hxx>
#include <Mod/Part/App/FCBRepAlgoAPI_Common.h>
#include <BRepAdaptor_CompCurve.hxx>
#include <BRepAdaptor_Curve.hxx>
#include <Mod/Part/App/FCBRepAlgoAPI_Cut.h>
#include <Mod/Part/App/FCBRepAlgoAPI_Fuse.h>
#include <Mod/Part/App/FCBRepAlgoAPI_Section.h>
#include <BRepBndLib.hxx>
#include <BRepBuilderAPI_Copy.hxx>
#include <BRepBuilderAPI_FaceError.hxx>
#include <BRepBuilderAPI_GTransform.hxx>
#include <BRepBuilderAPI_MakeEdge.hxx>
#include <BRepBuilderAPI_MakeFace.hxx>
#include <BRepBuilderAPI_MakeSolid.hxx>
#include <BRepBuilderAPI_MakeVertex.hxx>
#include <BRepBuilderAPI_MakeWire.hxx>
#include <BRepBuilderAPI_NurbsConvert.hxx>
#include <BRepBuilderAPI_Sewing.hxx>
#include <BRepBuilderAPI_Transform.hxx>
#include <BRepCheck_Analyzer.hxx>
#include <BRepClass_FaceClassifier.hxx>
#include <BRepCheck_ListIteratorOfListOfStatus.hxx>
#include <BRepCheck_Result.hxx>
#include <BRepFill_CompatibleWires.hxx>
#include <BRepGProp.hxx>
#include <BRepGProp_Face.hxx>
#include <BRepLib.hxx>
#include <BRepLib_FindSurface.hxx>
#include <BRepLProp_SLProps.hxx>
#include <BRepMesh_IncrementalMesh.hxx>
#include <BRepOffsetAPI_MakeOffset.hxx>
#include <BRepOffsetAPI_MakeOffsetShape.hxx>
#include <BRepOffsetAPI_MakePipe.hxx>
#include <BRepOffsetAPI_MakePipeShell.hxx>
#include <BRepOffsetAPI_ThruSections.hxx>
#include <BRepOffsetAPI_MakeThickSolid.hxx>
#include <BRepPrimAPI_MakePrism.hxx>
#include <BRepPrimAPI_MakeRevol.hxx>
#include <BRepPrimAPI_MakeTorus.hxx>
#include <BRepTools.hxx>
#include <BRepTools_ReShape.hxx>
#include <BRepTools_ShapeSet.hxx>
#include <BRepTools_WireExplorer.hxx>
#include <BSplCLib.hxx>
#include <GCE2d_MakeSegment.hxx>
#include <GCPnts_UniformAbscissa.hxx>
#include <Geom_BezierCurve.hxx>
#include <Geom_BezierSurface.hxx>
#include <Geom_BSplineCurve.hxx>
#include <Geom_BSplineSurface.hxx>
#include <Geom_CartesianPoint.hxx>
#include <Geom_Circle.hxx>
#include <Geom_ConicalSurface.hxx>
#include <Geom_CylindricalSurface.hxx>
#include <Geom_Ellipse.hxx>
#include <Geom_Hyperbola.hxx>
#include <Geom_Line.hxx>
#include <Geom_Parabola.hxx>
#include <Geom_Plane.hxx>
#include <Geom_SphericalSurface.hxx>
#include <Geom_SurfaceOfLinearExtrusion.hxx>
#include <Geom_SurfaceOfRevolution.hxx>
#include <Geom_ToroidalSurface.hxx>
#include <Geom2d_Ellipse.hxx>
#include <Geom2d_Line.hxx>
#include <Geom2d_TrimmedCurve.hxx>
#include <GeomFill_CorrectedFrenet.hxx>
#include <GeomFill_CurveAndTrihedron.hxx>
#include <GeomFill_EvolvedSection.hxx>
#include <GeomFill_Pipe.hxx>
#include <GeomFill_SectionLaw.hxx>
#include <GeomFill_Sweep.hxx>
#include <GeomLib.hxx>
#include <GeomLib_IsPlanarSurface.hxx>
#include <gp_Circ.hxx>
#include <gp_Pln.hxx>
#include <GProp_GProps.hxx>
#include <IGESControl_Controller.hxx>
#include <IGESControl_Reader.hxx>
#include <IGESControl_Writer.hxx>
#include <IGESData_GlobalSection.hxx>
#include <IGESData_IGESModel.hxx>
#include <Interface_Static.hxx>
#include <Law_BSpline.hxx>
#include <Law_BSpFunc.hxx>
#include <Law_Constant.hxx>
#include <ShapeAnalysis_FreeBoundsProperties.hxx>
#include <ShapeExtend_Explorer.hxx>
#include <ShapeFix_Shape.hxx>
#include <ShapeUpgrade_RemoveInternalWires.hxx>
#include <ShapeUpgrade_ShellSewing.hxx>
#include <Standard_Failure.hxx>
#include <Standard_Version.hxx>
#include <STEPControl_Reader.hxx>
#include <STEPControl_Writer.hxx>
#include <StlAPI_Writer.hxx>
#include <TopoDS.hxx>
#include <TopoDS_Compound.hxx>
#include <TopoDS_Iterator.hxx>
#include <TopoDS_Solid.hxx>
#include <TopoDS_Vertex.hxx>
#include <TopExp.hxx>
#include <TopExp_Explorer.hxx>
#include <TopTools_ListIteratorOfListOfShape.hxx>
#include <TopTools_HSequenceOfShape.hxx>
#include <Transfer_FinderProcess.hxx>
#include <Transfer_TransientProcess.hxx>
#include <XSControl_TransferWriter.hxx>
#include <XSControl_WorkSession.hxx>
#include <BOPAlgo_ArgumentAnalyzer.hxx>
#include <BOPAlgo_ListOfCheckResult.hxx>
#include <BRepAlgoAPI_Defeaturing.hxx>
#include <BRepAdaptor_HCurve.hxx>
#include <BRepAdaptor_HCompCurve.hxx>
#include <boost/algorithm/string/predicate.hpp>
#include <boost/core/ignore_unused.hpp>
#include <App/Material.h>
#include <App/ElementNamingUtils.h>
#include <Base/BoundBox.h>
#include <Base/Builder3D.h>
#include <Base/Console.h>
#include <Base/Exception.h>
#include <Base/Placement.h>
#include <Base/Tools.h>
#include <Base/Reader.h>
#include <Base/Writer.h>
#include "TopoShape.h"
#include "BRepMesh.h"
#include "BRepOffsetAPI_MakeOffsetFix.h"
#include "CrossSection.h"
#include "encodeFilename.h"
#include "FaceMakerBullseye.h"
#include "Interface.h"
#include "modelRefine.h"
#include "PartPyCXX.h"
#include "ProgressIndicator.h"
#include "Tools.h"
#include "TopoShapeCompoundPy.h"
#include "TopoShapeCompSolidPy.h"
#include "TopoShapeEdgePy.h"
#include "TopoShapeFacePy.h"
#include "TopoShapeShellPy.h"
#include "TopoShapeSolidPy.h"
#include "TopoShapeVertexPy.h"
#include "TopoShapeWirePy.h"
Namespaces
Part
Macros
#define _HANDLE_NULL_SHAPE(_msg, _throw)
#define HANDLE_NULL_SHAPE _HANDLE_NULL_SHAPE("Null shape",true)
#define HANDLE_NULL_INPUT _HANDLE_NULL_SHAPE("Null input shape",true)
#define WARN_NULL_INPUT _HANDLE_NULL_SHAPE("Null input shape",false)
Functions
const char * BRepBuilderAPI_FaceErrorText (BRepBuilderAPI_FaceError et)
double defaultAngularDeflection (double linearTolerance)
template<class T >
static std::vector< T > _getSubShapes (const TopoDS_Shape &s, TopAbs_ShapeEnum type)
static void initShapeNameMap ()
unsigned int TopoShape_RefCountShapes (const TopoDS_Shape &aShape)
std::vector< std::string > Part::buildShapeEnumVector ()
std::vector< std::string > Part::buildBOPCheckResultVector ()
static Handle (Law_Function) CreateBsFunction(const Standard_Real theFirst
Handle (Law_Constant) aFunc
aFunc Set (1, theFirst, theLast)
Variables
static std::array< std::string, TopAbs_SHAPE > _ShapeNames
static const Standard_Real theLast
static const Standard_Real const Standard_Real theRadius
return aFunc
Macro Definition Documentation
_HANDLE_NULL_SHAPE
#define _HANDLE_NULL_SHAPE (_msg, _throw)
Value:
    do {\
    if(_throw) {\
        FC_THROWM(NullShapeException,_msg);\
    }\
    FC_WARN(_msg);\
}while(0)
Definition at line 3760 of file TopoShape.cpp.
HANDLE_NULL_INPUT
#define HANDLE_NULL_INPUT _HANDLE_NULL_SHAPE("Null input shape",true)
Definition at line 3768 of file TopoShape.cpp.
HANDLE_NULL_SHAPE
#define HANDLE_NULL_SHAPE _HANDLE_NULL_SHAPE("Null shape",true)
Definition at line 3767 of file TopoShape.cpp.
WARN_NULL_INPUT
#define WARN_NULL_INPUT _HANDLE_NULL_SHAPE("Null input shape",false)
Definition at line 3769 of file TopoShape.cpp.
Function Documentation
_getSubShapes()
template<class T > static std::vector<T> _getSubShapes (const TopoDS_Shape & s, TopAbs_ShapeEnum type) inline static
Definition at line 393 of file TopoShape.cpp.
References src.Mod.AddonManager.NetworkManager::count, SplineSurface::i, toolbit-attributes::s, and Path.Post.scripts.grbl_post::type.
BRepBuilderAPI_FaceErrorText()
const char* BRepBuilderAPI_FaceErrorText (BRepBuilderAPI_FaceError et)
Definition at line 199 of file TopoShape.cpp.
defaultAngularDeflection()
double defaultAngularDeflection (double linearTolerance) inline
Derive a roughly proportional default angular deflection from a linear tolerance. This is a work-around for unreliable linear tolerance enforcement in OCC, especially on nurbs surfaces. The intention is to provide sane baseline (default) behavior with linear tolerances only, until OCC is fixed. If needed for specific use cases, explicit angular deflection parameters can still be exposed separately.
Definition at line 226 of file TopoShape.cpp.
References KDL::min().
Referenced by Part::TopoShape::exportFaceSet(), Part::TopoShape::exportStl(), and Part::TopoShape::getFaces().
Handle() [1/2]
Handle (Law_Constant)
Handle() [2/2]
static Handle (Law_Function) const static
Referenced by Part::TopoShape::analyze(), Part::TopoShape::exportStep(), Part::TopoShape::findPlane(), Part::TopoShape::getMemSize(), Part::TopoShape::getPoints(), Part::TopoShape::importBrep(), Part::TopoShape::importIges(), Part::TopoShape::importStep(), Part::TopoShape::isPlanar(), Part::TopoShape::makeHelix(), Part::TopoShape::makeLongHelix(), Part::TopoShape::makeOffset2D(), Part::TopoShape::makeSpiralHelix(), Part::TopoShape::makeSweep(), Part::TopoShape::makeThread(), Part::TopoShape::makeTube(), and Part::TopoShape::setFaces().
initShapeNameMap()
static void initShapeNameMap () static
Definition at line 415 of file TopoShape.cpp.
References _ShapeNames.
Referenced by Part::TopoShape::shapeName(), and Part::TopoShape::shapeType().
Set()
aFunc Set (1 , theFirst , theLast)
Referenced by Import::ExportOCAF::createNode(), MeshCore::MeshPointIterator::EndReached(), and Import::ExportOCAF::saveShape().
TopoShape_RefCountShapes()
unsigned int TopoShape_RefCountShapes (const TopoDS_Shape & aShape)
Definition at line 1224 of file TopoShape.cpp.
Referenced by Part::TopoShape::getMemSize().
Variable Documentation
_ShapeNames
std::array<std::string,TopAbs_SHAPE> _ShapeNames static
Definition at line 413 of file TopoShape.cpp.
Referenced by initShapeNameMap(), Part::TopoShape::shapeName(), and Part::TopoShape::shapeType().
aFunc
return aFunc
Definition at line 1995 of file TopoShape.cpp.
theLast
const Standard_Real theLast
Definition at line 1988 of file TopoShape.cpp.
theRadius
const Standard_Real const Standard_Real theRadius
Initial value:
{
    (void)theRadius
Definition at line 1989 of file TopoShape.cpp.
Referenced by Part::TopoShape::makeTube().