FreeCAD: Base::ScriptFactorySingleton Class Reference
Base::ScriptFactorySingleton Class Reference
#include <Factory.h>
Public Member Functions
const char * ProduceScript (const char *sScriptName) const
Public Member Functions inherited from Base::Factory
void AddProducer (const char *sClassName, AbstractProducer *pcProducer)
Adds a new prducer instance.
bool CanProduce (const char *sClassName) const
returns true if there is a producer for this class registered
std::list< std::string > CanProduce () const
returns a list of all registered producer
virtual ~Factory ()
destruction
Static Public Member Functions
static ScriptFactorySingleton & Instance ()
static void Destruct ()
Protected Member Functions
ScriptFactorySingleton ()=default
~ScriptFactorySingleton () override=default
Protected Member Functions inherited from Base::Factory
void * Produce (const char *sClassName) const
produce a class with the given name
Factory ()=default
construction
Additional Inherited Members
Protected Attributes inherited from Base::Factory
std::map< const std::string, AbstractProducer * > _mpcProducers
Detailed Description
The ScriptFactorySingleton singleton
Definition at line 106 of file Factory.h.
Constructor & Destructor Documentation
ScriptFactorySingleton()
Base::ScriptFactorySingleton::ScriptFactorySingleton () protected default
Referenced by Instance().
~ScriptFactorySingleton()
Base::ScriptFactorySingleton::~ScriptFactorySingleton () override protected default
Member Function Documentation
Destruct()
void ScriptFactorySingleton::Destruct () static
Definition at line 91 of file Factory.cpp.
Referenced by App::Application::destruct().
Instance()
ScriptFactorySingleton & ScriptFactorySingleton::Instance () static
Definition at line 83 of file Factory.cpp.
References ScriptFactorySingleton().
ProduceScript()
const char * ScriptFactorySingleton::ProduceScript (const char * sScriptName) const
Definition at line 97 of file Factory.cpp.
References Base::Console(), Base::Factory::Produce(), and Base::ConsoleSingleton::Warning().
The documentation for this class was generated from the following files:
Factory.h
Factory.cpp