FreeCAD: Path.Post.scripts.smoothie_post Namespace Reference
Path.Post.scripts.smoothie_post Namespace Reference
Functions
def processArguments (argstring)
def export (objectslist, filename, argstring)
def sendToSmoothie (ip, GCODE, fname)
def linenumber ()
def parse (pathobj)
Variables
TOOLTIP
now
parser
prog
add_help
action = "store_true",
help = "don't prefix with line numbers (default)",
default
TOOLTIP_ARGS
OUTPUT_COMMENTS
OUTPUT_HEADER
OUTPUT_LINE_NUMBERS
IP_ADDR
VERBOSE
SPINDLE_SPEED
SHOW_EDITOR
MODAL
COMMAND_SPACE
LINENR
UNITS
UNIT_SPEED_FORMAT
UNIT_FORMAT
MACHINE_NAME
CORNER_MIN
CORNER_MAX
PREAMBLE
POSTAMBLE
PRE_OPERATION
POST_OPERATION
TOOL_CHANGE
PRECISION
Function Documentation
export()
def Path.Post.scripts.smoothie_post.export (objectslist, filename, argstring)
Definition at line 192 of file smoothie_post.py.
References Path.Post.scripts.smoothie_post.linenumber(), Path.Post.scripts.smoothie_post.parse(), Path.Post.scripts.smoothie_post.processArguments(), Path.Post.scripts.smoothie_post.sendToSmoothie(), and Path.Post.scripts.refactored_centroid_post.str.
linenumber()
def Path.Post.scripts.smoothie_post.linenumber ()
Definition at line 358 of file smoothie_post.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.smoothie_post.export(), and Path.Post.scripts.smoothie_post.parse().
parse()
def Path.Post.scripts.smoothie_post.parse (pathobj)
Definition at line 366 of file smoothie_post.py.
References Path.Post.scripts.smoothie_post.linenumber(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.smoothie_post.export().
processArguments()
def Path.Post.scripts.smoothie_post.processArguments (argstring)
Definition at line 139 of file smoothie_post.py.
Referenced by Path.Post.scripts.smoothie_post.export().
sendToSmoothie()
def Path.Post.scripts.smoothie_post.sendToSmoothie (ip, GCODE, fname)
Definition at line 282 of file smoothie_post.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.smoothie_post.export().
Variable Documentation
action
string Path.Post.scripts.smoothie_post.action = "store_true",
Definition at line 48 of file smoothie_post.py.
add_help
Path.Post.scripts.smoothie_post.add_help
Definition at line 47 of file smoothie_post.py.
COMMAND_SPACE
Path.Post.scripts.smoothie_post.COMMAND_SPACE
Definition at line 103 of file smoothie_post.py.
CORNER_MAX
Path.Post.scripts.smoothie_post.CORNER_MAX
Definition at line 113 of file smoothie_post.py.
CORNER_MIN
Path.Post.scripts.smoothie_post.CORNER_MIN
Definition at line 112 of file smoothie_post.py.
default
Path.Post.scripts.smoothie_post.default
Definition at line 68 of file smoothie_post.py.
help
string Path.Post.scripts.smoothie_post.help = "don't prefix with line numbers (default)",
Definition at line 48 of file smoothie_post.py.
IP_ADDR
Path.Post.scripts.smoothie_post.IP_ADDR
Definition at line 93 of file smoothie_post.py.
LINENR
Path.Post.scripts.smoothie_post.LINENR
Definition at line 104 of file smoothie_post.py.
MACHINE_NAME
Path.Post.scripts.smoothie_post.MACHINE_NAME
Definition at line 111 of file smoothie_post.py.
MODAL
Path.Post.scripts.smoothie_post.MODAL
Definition at line 102 of file smoothie_post.py.
now
Path.Post.scripts.smoothie_post.now
Definition at line 45 of file smoothie_post.py.
OUTPUT_COMMENTS
Path.Post.scripts.smoothie_post.OUTPUT_COMMENTS
Definition at line 90 of file smoothie_post.py.
OUTPUT_HEADER
Path.Post.scripts.smoothie_post.OUTPUT_HEADER
Definition at line 91 of file smoothie_post.py.
OUTPUT_LINE_NUMBERS
Path.Post.scripts.smoothie_post.OUTPUT_LINE_NUMBERS
Definition at line 92 of file smoothie_post.py.
parser
Path.Post.scripts.smoothie_post.parser
Definition at line 47 of file smoothie_post.py.
POST_OPERATION
Path.Post.scripts.smoothie_post.POST_OPERATION
Definition at line 130 of file smoothie_post.py.
POSTAMBLE
Path.Post.scripts.smoothie_post.POSTAMBLE
Definition at line 120 of file smoothie_post.py.
PRE_OPERATION
Path.Post.scripts.smoothie_post.PRE_OPERATION
Definition at line 127 of file smoothie_post.py.
PREAMBLE
Path.Post.scripts.smoothie_post.PREAMBLE
Definition at line 116 of file smoothie_post.py.
PRECISION
Path.Post.scripts.smoothie_post.PRECISION
Definition at line 136 of file smoothie_post.py.
prog
Path.Post.scripts.smoothie_post.prog
Definition at line 47 of file smoothie_post.py.
SHOW_EDITOR
Path.Post.scripts.smoothie_post.SHOW_EDITOR
Definition at line 99 of file smoothie_post.py.
SPINDLE_SPEED
Path.Post.scripts.smoothie_post.SPINDLE_SPEED
Definition at line 96 of file smoothie_post.py.
TOOL_CHANGE
Path.Post.scripts.smoothie_post.TOOL_CHANGE
Definition at line 133 of file smoothie_post.py.
TOOLTIP
Path.Post.scripts.smoothie_post.TOOLTIP
Definition at line 34 of file smoothie_post.py.
TOOLTIP_ARGS
Path.Post.scripts.smoothie_post.TOOLTIP_ARGS
Definition at line 87 of file smoothie_post.py.
UNIT_FORMAT
Path.Post.scripts.smoothie_post.UNIT_FORMAT
Definition at line 109 of file smoothie_post.py.
UNIT_SPEED_FORMAT
Path.Post.scripts.smoothie_post.UNIT_SPEED_FORMAT
Definition at line 108 of file smoothie_post.py.
UNITS
Path.Post.scripts.smoothie_post.UNITS
Definition at line 107 of file smoothie_post.py.
VERBOSE
Path.Post.scripts.smoothie_post.VERBOSE
Definition at line 94 of file smoothie_post.py.