FreeCAD: FCBRepAlgoAPI_Section Class Reference
FCBRepAlgoAPI_Section Class Reference
#include <FCBRepAlgoAPI_Section.h>
Public Member Functions
DEFINE_STANDARD_ALLOC Standard_EXPORT FCBRepAlgoAPI_Section ()
Empty constructor.
Standard_EXPORT FCBRepAlgoAPI_Section (const TopoDS_Shape &S1, const TopoDS_Shape &S2, const Standard_Boolean PerformNow=Standard_True)
Standard_EXPORT FCBRepAlgoAPI_Section (const TopoDS_Shape &S1, const gp_Pln &Pl, const Standard_Boolean PerformNow=Standard_True)
void setAutoFuzzy ()
Detailed Description
FCBRepAlgoAPI provides a wrapper for various OCCT functions.
Definition at line 36 of file FCBRepAlgoAPI_Section.h.
Constructor & Destructor Documentation
FCBRepAlgoAPI_Section() [1/3]
FCBRepAlgoAPI_Section::FCBRepAlgoAPI_Section ()
Empty constructor.
FCBRepAlgoAPI provides a wrapper for various OCCT functions.
Definition at line 37 of file FCBRepAlgoAPI_Section.cpp.
FCBRepAlgoAPI_Section() [2/3]
FCBRepAlgoAPI_Section::FCBRepAlgoAPI_Section (const TopoDS_Shape & S1, const TopoDS_Shape & S2, const Standard_Boolean PerformNow = Standard_True)
Constructor with two shapes <S1> -argument <S2> -tool <PerformNow> - the flag: if <PerformNow>=True - the algorithm is performed immediately Obsolete
Definition at line 43 of file FCBRepAlgoAPI_Section.cpp.
References setAutoFuzzy().
FCBRepAlgoAPI_Section() [3/3]
FCBRepAlgoAPI_Section::FCBRepAlgoAPI_Section (const TopoDS_Shape & S1, const gp_Pln & Pl, const Standard_Boolean PerformNow = Standard_True)
Constructor with two shapes <S1> - argument <Pl> - tool <PerformNow> - the flag: if <PerformNow>=True - the algorithm is performed immediately Obsolete
Definition at line 59 of file FCBRepAlgoAPI_Section.cpp.
Member Function Documentation
setAutoFuzzy()
void FCBRepAlgoAPI_Section::setAutoFuzzy ()
Definition at line 74 of file FCBRepAlgoAPI_Section.cpp.
References FCBRepAlgoAPIHelper::setAutoFuzzy().
Referenced by FCBRepAlgoAPI_Section(), and Part::TopoShape::section().
The documentation for this class was generated from the following files:
FCBRepAlgoAPI_Section.h
FCBRepAlgoAPI_Section.cpp