FreeCAD: App::PropertyContainer Class Reference
App::PropertyContainer Class Reference
#include <PropertyContainer.h>
Public Member Functions
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual std::string getFullName () const
virtual Property * getPropertyByName (const char *name) const
find a property by its name
virtual const char * getPropertyName (const Property *prop) const
get the name of a property
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void getPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
virtual short getPropertyType (const Property *prop) const
get the Type of a Property
virtual short getPropertyType (const char *name) const
get the Type of a named Property
virtual const char * getPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * getPropertyDocumentation (const char *name) const
get the Group of a named Property
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
virtual App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false)
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual bool removeDynamicProperty (const char *name)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
virtual void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus)
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
virtual void onEarlyChange (const Property *)
virtual void onChanged (const Property *)
get called by the container when a property has changed
virtual void onBeforeChange (const Property *)
get called before the value is changed
virtual const PropertyData & getPropertyData () const
virtual void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container. This method is typically called if the property on file has changed its name in more recent versions.
virtual void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container. This method is typically called if the property on file has changed its type in more recent versions.
Static Protected Member Functions
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes
DynamicProperty dynamicProps
Friends
class Property
class DynamicProperty
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Detailed Description
Base class of all classes with properties
Definition at line 145 of file PropertyContainer.h.
Constructor & Destructor Documentation
PropertyContainer() [1/2]
PropertyContainer::PropertyContainer ()
A constructor. A more elaborate description of the constructor.
Definition at line 48 of file PropertyContainer.cpp.
~PropertyContainer()
PropertyContainer::~PropertyContainer () override default
A destructor. A more elaborate description of the destructor.
PropertyContainer() [2/2]
App::PropertyContainer::PropertyContainer (const PropertyContainer &) delete
Member Function Documentation
addDynamicProperty()
App::Property * PropertyContainer::addDynamicProperty (const char * type, const char * name = nullptr, const char * group = nullptr, const char * doc = nullptr, short attr = 0, bool ro = false, bool hidden = false) virtual
Reimplemented in App::DocumentObject, and Gui::ViewProviderDocumentObject.
Definition at line 67 of file PropertyContainer.cpp.
References App::DynamicProperty::addDynamicProperty(), toolbit-attributes::doc, dynamicProps, toolbit-attributes::group, and Path.Post.scripts.grbl_post::type.
Referenced by Gui::ViewProviderDocumentObject::addDynamicProperty(), App::TransactionObject::applyChn(), and getProp().
beforeSave()
void PropertyContainer::beforeSave () const virtual
Definition at line 223 of file PropertyContainer.cpp.
References getPropertyMap(), getPropertyType(), App::Prop_Transient, App::Property::PropDynamic, and App::Property::Transient.
Referenced by App::Document::Save().
changeDynamicProperty()
bool App::PropertyContainer::changeDynamicProperty (const Property * prop, const char * group, const char * doc) inline
Definition at line 209 of file PropertyContainer.h.
References toolbit-attributes::doc, and toolbit-attributes::group.
editProperty()
virtual void App::PropertyContainer::editProperty (const char *) inline virtual
Definition at line 229 of file PropertyContainer.h.
getDynamicPropertyByName()
virtual App::Property* App::PropertyContainer::getDynamicPropertyByName (const char * name) const inline virtual
Reimplemented in Spreadsheet::Sheet.
Definition at line 219 of file PropertyContainer.h.
Referenced by App::TransactionObject::applyChn(), Part::PropertyShapeCache::get(), getProp(), Gui::ViewProviderDocumentObject::removeDynamicProperty(), and PartDesign::SubShapeBinder::update().
getDynamicPropertyData()
DynamicProperty::PropData App::PropertyContainer::getDynamicPropertyData (const Property * prop) const inline
Definition at line 205 of file PropertyContainer.h.
Referenced by App::TransactionObject::addOrRemoveProperty(), and App::TransactionObject::setProperty().
getDynamicPropertyNames()
virtual std::vector<std::string> App::PropertyContainer::getDynamicPropertyNames () const inline virtual
Definition at line 216 of file PropertyContainer.h.
Referenced by PartDesign::SubShapeBinder::update().
getFullName()
virtual std::string App::PropertyContainer::getFullName () const inline virtual
Reimplemented in App::Document, Gui::ViewProviderDocumentObject, and App::DocumentObject.
Definition at line 165 of file PropertyContainer.h.
Referenced by App::DynamicProperty::addDynamicProperty(), App::Property::getFullName(), and getProp().
getMemSize()
unsigned int PropertyContainer::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
Reimplemented in Sketcher::SketchObject, and TechDraw::DrawParametricTemplate.
Definition at line 55 of file PropertyContainer.cpp.
References getPropertyMap().
Referenced by App::Document::getMemSize().
getPropertyByName()
Property * PropertyContainer::getPropertyByName (const char * name) const virtual
find a property by its name
Reimplemented in Gui::ViewProviderLink, Spreadsheet::Sheet, App::ExtensionContainer, and App::ExtensionContainer.
Definition at line 74 of file PropertyContainer.cpp.
References dynamicProps, App::DynamicProperty::getDynamicPropertyByName(), App::PropertyData::getPropertyByName(), and getPropertyData().
Referenced by App::DynamicProperty::addDynamicProperty(), App::ExtensionContainer::getPropertyByName(), getPropertyType(), and Restore().
getPropertyData()
const PropertyData & PropertyContainer::getPropertyData () const protected virtual
Reimplemented in App::Document.
Definition at line 180 of file PropertyContainer.cpp.
Referenced by getPropertyByName(), getPropertyDocumentation(), getPropertyGroup(), getPropertyList(), getPropertyMap(), getPropertyName(), and getPropertyNamedList().
getPropertyDataPtr()
const PropertyData * PropertyContainer::getPropertyDataPtr () static protected
Definition at line 179 of file PropertyContainer.cpp.
getPropertyDocumentation() [1/2]
const char * PropertyContainer::getPropertyDocumentation (const char * name) const virtual
get the Group of a named Property
Reimplemented in App::ExtensionContainer.
Definition at line 143 of file PropertyContainer.cpp.
References toolbit-attributes::doc, dynamicProps, App::PropertyData::getDocumentation(), getPropertyData(), and App::DynamicProperty::getPropertyDocumentation().
getPropertyDocumentation() [2/2]
const char * PropertyContainer::getPropertyDocumentation (const Property * prop) const virtual
get the Group of a Property
Reimplemented in App::ExtensionContainer.
Definition at line 135 of file PropertyContainer.cpp.
References toolbit-attributes::doc, dynamicProps, App::PropertyData::getDocumentation(), getPropertyData(), and App::DynamicProperty::getPropertyDocumentation().
Referenced by App::Property::getDocumentation(), and App::ExtensionContainer::getPropertyDocumentation().
getPropertyGroup() [1/2]
const char * PropertyContainer::getPropertyGroup (const char * name) const virtual
get the Group of a named Property
Reimplemented in App::ExtensionContainer.
Definition at line 127 of file PropertyContainer.cpp.
References dynamicProps, App::PropertyData::getGroup(), getPropertyData(), App::DynamicProperty::getPropertyGroup(), and toolbit-attributes::group.
getPropertyGroup() [2/2]
const char * PropertyContainer::getPropertyGroup (const Property * prop) const virtual
get the Group of a Property
Reimplemented in App::ExtensionContainer.
Definition at line 119 of file PropertyContainer.cpp.
References dynamicProps, App::PropertyData::getGroup(), getPropertyData(), App::DynamicProperty::getPropertyGroup(), and toolbit-attributes::group.
Referenced by App::Property::getGroup(), and App::ExtensionContainer::getPropertyGroup().
getPropertyList()
void PropertyContainer::getPropertyList (std::vector< Property * > & List) const virtual
get all properties of the class (including properties of the parent)
Reimplemented in App::ExtensionContainer, and Gui::ViewProviderLink.
Definition at line 89 of file PropertyContainer.cpp.
References dynamicProps, getPropertyData(), App::DynamicProperty::getPropertyList(), and App::PropertyData::getPropertyList().
Referenced by App::ExtensionContainer::getPropertyList(), PartDesignGui::isAnyNonPartDesignLinksTo(), Gui::Application::reopen(), and setPropertyStatus().
getPropertyMap()
void PropertyContainer::getPropertyMap (std::map< std::string, Property * > & Map) const virtual
get all properties of the class (including properties of the parent)
Reimplemented in App::ExtensionContainer, and Gui::ViewProviderLink.
Definition at line 83 of file PropertyContainer.cpp.
References dynamicProps, getPropertyData(), App::DynamicProperty::getPropertyMap(), and App::PropertyData::getPropertyMap().
Referenced by beforeSave(), getMemSize(), App::ExtensionContainer::getPropertyMap(), and Save().
getPropertyName()
const char * PropertyContainer::getPropertyName (const Property * prop) const virtual
get the name of a property
Reimplemented in App::ExtensionContainer.
Definition at line 171 of file PropertyContainer.cpp.
References dynamicProps, App::PropertyData::getName(), getPropertyData(), and App::DynamicProperty::getPropertyName().
Referenced by App::ExtensionContainer::getPropertyName().
getPropertyNamedList()
void PropertyContainer::getPropertyNamedList (std::vector< std::pair< const char *, Property * > > & List) const virtual
get all properties with their names, may contain duplicates and aliases
Definition at line 95 of file PropertyContainer.cpp.
References dynamicProps, getPropertyData(), App::DynamicProperty::getPropertyNamedList(), and App::PropertyData::getPropertyNamedList().
Referenced by ExpressionCompleterModel::_data().
getPropertyPrefix()
const char* App::PropertyContainer::getPropertyPrefix () const inline
Definition at line 231 of file PropertyContainer.h.
getPropertyType() [1/2]
short PropertyContainer::getPropertyType (const char * name) const virtual
get the Type of a named Property
Reimplemented in App::ExtensionContainer.
Definition at line 114 of file PropertyContainer.cpp.
References getPropertyByName(), and getPropertyType().
getPropertyType() [2/2]
short PropertyContainer::getPropertyType (const Property * prop) const virtual
get the Type of a Property
Reimplemented in App::ExtensionContainer.
Definition at line 109 of file PropertyContainer.cpp.
References App::Property::getType().
Referenced by beforeSave(), getPropertyType(), App::ExtensionContainer::getPropertyType(), isHidden(), isReadOnly(), and Save().
handleChangedPropertyName()
void PropertyContainer::handleChangedPropertyName (Base::XMLReader & reader, const char * TypeName, const char * PropName) protected virtual
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container. This method is typically called if the property on file has changed its name in more recent versions.
The default implementation does nothing.
Parameters
reader The XML stream to read from.
TypeName Name of property type on file.
PropName Name of property on file that does not exist in the container anymore.
Reimplemented in App::LinkElement, App::Link, Part::Ellipse, App::ExtensionContainer, PartGui::ViewProviderPartExt, Measure::MeasureDistanceDetached, PartDesign::ProfileBased, Fem::FemAnalysis, Part::BodyBase, Gui::ViewProviderGeometryObject, PartDesign::Boolean, Surface::Extend, Fem::ConstraintTransform, Part::Circle, FemGui::ViewProviderFemConstraint, and TechDraw::DrawViewBalloon.
Definition at line 195 of file PropertyContainer.cpp.
References TechDrawTools.TaskFillTemplateFields::reader.
Referenced by App::ExtensionContainer::handleChangedPropertyName(), and Restore().
handleChangedPropertyType()
void PropertyContainer::handleChangedPropertyType (Base::XMLReader & reader, const char * TypeName, Property * prop) protected virtual
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container. This method is typically called if the property on file has changed its type in more recent versions.
The default implementation does nothing.
Parameters
reader The XML stream to read from.
TypeName Name of property type on file.
prop Pointer to property to restore. Its type differs from TypeName.
Reimplemented in App::ExtensionContainer, Sketcher::SketchObject, Fem::Constraint, Mesh::Cube, TechDraw::DrawProjGroup, Part::Thickness, Mesh::Torus, Fem::FemPostDataAlongLineFilter, Mesh::Cone, PartDesign::SubShapeBinder, PartDesign::Transformed, TechDrawGui::ViewProviderDimension, App::Part, Mesh::Cylinder, TechDraw::DrawViewAnnotation, Fem::ConstraintDisplacement, PartDesign::Pipe, TechDrawGui::ViewProviderViewPart, PartDesign::Helix, TechDrawGui::ViewProviderBalloon, Fem::ConstraintContact, PartDesign::Chamfer, PartDesign::PolarPattern, PartDesign::ShapeBinder, Fem::ConstraintHeatflux, Fem::ConstraintTemperature, Fem::ConstraintInitialTemperature, Part::Mirroring, PartDesign::LinearPattern, PartDesign::Loft, TechDraw::DrawPage, TechDraw::DrawTile, Fem::ConstraintForce, PartDesign::Fillet, Mesh::Ellipsoid, TechDraw::DrawView, Fem::ConstraintPressure, Mesh::Sphere, Part::Primitive, TechDraw::DrawViewBalloon, PartGui::ViewProvider2DObjectGrid, TechDrawGui::ViewProviderLeader, TechDrawGui::ViewProviderRichAnno, and TechDraw::DrawViewDimension.
Definition at line 214 of file PropertyContainer.cpp.
References TechDrawTools.TaskFillTemplateFields::reader.
Referenced by App::ExtensionContainer::handleChangedPropertyType(), and Restore().
isHidden() [1/2]
bool PropertyContainer::isHidden (const char * name) const
check if the named property is hidden
Definition at line 166 of file PropertyContainer.cpp.
References getPropertyType(), and App::Prop_Hidden.
isHidden() [2/2]
bool PropertyContainer::isHidden (const Property * prop) const
check if the property is hidden
Definition at line 161 of file PropertyContainer.cpp.
References getPropertyType(), and App::Prop_Hidden.
isReadOnly() [1/2]
bool PropertyContainer::isReadOnly (const char * name) const
check if the named property is read-only
Definition at line 156 of file PropertyContainer.cpp.
References getPropertyType(), and App::Prop_ReadOnly.
isReadOnly() [2/2]
bool PropertyContainer::isReadOnly (const Property * prop) const
check if the property is read-only
Definition at line 151 of file PropertyContainer.cpp.
References getPropertyType(), and App::Prop_ReadOnly.
onBeforeChange()
virtual void App::PropertyContainer::onBeforeChange (const Property *) inline protected virtual
get called before the value is changed
Reimplemented in App::DocumentObject, App::Document, Gui::ViewProvider, Gui::ViewProviderDocumentObject, Part::Feature, TechDraw::DrawPage, TechDraw::DrawView, Part::BodyBase, Drawing::FeaturePage, and Gui::ViewProviderLink.
Definition at line 252 of file PropertyContainer.h.
Referenced by App::Property::aboutToSetValue(), and Gui::ViewProvider::onBeforeChange().
onChanged()
virtual void App::PropertyContainer::onChanged (const Property *) inline protected virtual
get called by the container when a property has changed
Reimplemented in App::DocumentObject, App::Document, App::GeoFeature, App::TextDocument, App::ExtensionContainer, SketcherGui::ViewProviderSketch, Gui::ViewProvider, Part::Wedge, Part::Spiral, Fem::FemPostWarpVectorFilter, Part::Helix, Fem::FemPostScalarClipFilter, Fem::FemPostCutFilter, Fem::FemPostContoursFilter, Spreadsheet::Sheet, Fem::FemPostClipFilter, TechDraw::DrawViewPart, TechDraw::DrawViewDimension, MeshGui::ViewProviderMesh, Gui::ViewProviderLink, Fem::FemPostSphereFunction, Gui::ViewProviderDocumentObject, Fem::FemPostDataAtPointFilter, PartDesign::ProfileBased, Fem::Constraint, Fem::FemPostPlaneFunction, MeasureGui::ViewProviderMeasure, Part::Feature, Fem::FemPostDataAlongLineFilter, Fem::FemPostCylinderFunction, PartGui::ViewProviderPartExt, TechDraw::DrawPage, FemGui::ViewProviderFemMesh, TechDraw::DrawProjGroup, Part::Extrusion, TechDraw::DrawView, FemGui::ViewProviderFemPostFunction, PartDesign::SubShapeBinder, Part::Sweep, PartDesign::Body, Fem::FemPostBoxFunction, MeasureGui::ViewProviderMeasureBase, Part::BodyBase, Fem::ConstraintDisplacement, Robot::RobotObject, TechDraw::DrawViewClip, TechDraw::DrawProjGroupItem, TechDraw::DrawViewAnnotation, FemGui::ViewProviderFemPostFunctionProvider, PartDesign::Helix, TechDrawGui::ViewProviderViewPart, TechDraw::DrawViewSection, Part::Loft, TechDraw::DrawViewCollection, Fem::FemPostFunctionProvider, Fem::FemPostPipeline, PartDesign::Hole, Gui::ViewProviderAnnotationLabel, Fem::ConstraintFluidBoundary, TechDraw::DrawViewImage, MeshGui::ViewProviderMeshCurvature, PartDesign::DressUp, Assembly::AssemblyLink, Surface::FeatureBlendCurve, Fem::ConstraintBearing, PartDesign::ShapeBinder, Fem::ConstraintContact, Fem::ConstraintRigidBody, Fem::ConstraintPulley, Fem::FemMeshObject, PartDesign::PolarPattern, TechDraw::DrawViewSpreadsheet, Fem::ConstraintHeatflux, Fem::ConstraintTemperature, Robot::TrajectoryDressUpObject, Gui::ViewProviderDragger, TechDraw::DrawTileWeld, Fem::ConstraintInitialTemperature, PointsGui::ViewProviderPoints, TechDraw::DrawRichAnno, Gui::ViewProviderGeometryObject, Path::Feature, MeasureGui::ViewProviderMeasureDistance, Robot::TrajectoryObject, Surface::Extend, Fem::ConstraintForce, Fem::ConstraintGear, Fem::ConstraintTransform, PartDesign::Boolean, PartDesign::LinearPattern, TechDrawGui::ViewProviderBalloon, Robot::Edge2TracObject, TechDraw::DrawTile, Gui::ViewProviderPart, Part::Mirroring, Part::RuledSurface, Part::Revolution, PartDesignGui::ViewProviderSubShapeBinder, TechDrawGui::ViewProviderViewSection, Part::Box, PartDesign::FeaturePrimitive, FemGui::ViewProviderFemPostObject, PartDesignGui::ViewProviderBoolean, TechDrawGui::ViewProviderPage, Fem::ConstraintFixed, Fem::ConstraintSpring, PartDesign::Point, TechDraw::DrawViewSymbol, PathGui::ViewProviderPath, Part::Primitive, PartDesign::Feature, TechDraw::DrawSVGTemplate, TechDrawGui::ViewProviderImage, Fem::ConstraintPlaneRotation, PartDesign::Plane, PartDesign::FeatureBase, PartDesignGui::ViewProviderDatumPoint, TechDraw::DrawWeldSymbol, FemGui::ViewProviderFemConstraint, PartDesign::Line, FemGui::ViewProviderFemPostDataAtPoint, TechDraw::DrawViewBalloon, InspectionGui::ViewProviderInspection, SketcherGui::ViewProviderCustom, PartGui::ViewProviderCustom, PartGui::ViewProviderPartReference, PartGui::ViewProvider2DObjectGrid, TechDraw::DrawParametricTemplate, Points::Feature, TechDraw::DrawHatch, PartDesignGui::ViewProvider, Mesh::Feature, PartDesignGui::ViewProviderBody, TechDraw::DrawViewDetail, TechDrawGui::ViewProviderDrawingView, Gui::ViewProviderAnnotation, TechDraw::DrawGeomHatch, TechDraw::DrawViewMulti, Gui::ViewProviderDatum, Gui::ViewProviderPlacement, TechDraw::LandmarkDimension, MeshGui::ViewProviderMeshDefects, RobotGui::ViewProviderRobotObject, TechDrawGui::ViewProviderGeomHatch, TechDrawGui::ViewProviderRichAnno, TechDrawGui::ViewProviderHatch, Gui::ViewProviderImagePlane, TechDrawGui::ViewProviderTemplate, Gui::ViewProviderTextDocument, Drawing::FeatureClip, Drawing::FeaturePage, Drawing::FeatureViewSymbol, Sandbox::SandboxObject, TechDrawGui::ViewProviderDimension, TechDrawGui::ViewProviderWeld, TechDrawGui::ViewProviderLeader, Sketcher::SketchObject, Part::Ellipse, FemGui::ViewProviderFemPostPlaneFunction, Part::FilletBase, Part::Line, App::VRMLObject, PartDesign::Chamfer, Surface::GeomFillSurface, Part::Vertex, Part::Circle, and PartDesignGui::ViewProviderDatumCoordinateSystem.
Definition at line 250 of file PropertyContainer.h.
Referenced by draftviewproviders.view_base.ViewProviderDraft::attach(), App::Property::hasSetValue(), App::ExtensionContainer::onChanged(), ArchSpace._ViewProviderSpace::onChanged(), ArchSchedule._ArchSchedule::setProperties(), App::Property::touch(), draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), ArchAxis._ViewProviderAxis::updateData(), draftviewproviders.view_dimension.ViewProviderLinearDimension::updateData(), ArchSpace._ViewProviderSpace::updateData(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchSite._ViewProviderSite::updateData(), ArchSectionPlane._ViewProviderSectionPlane::updateData(), and ArchPanel.ViewProviderPanelSheet::updateData().
onEarlyChange()
virtual void App::PropertyContainer::onEarlyChange (const Property *) inline protected virtual
get called by the container when a property has changed
This function is called before onChanged()
Reimplemented in App::DocumentObject.
Definition at line 248 of file PropertyContainer.h.
Referenced by App::Property::touch().
onPropertyStatusChanged()
void PropertyContainer::onPropertyStatusChanged (const Property & prop, unsigned long oldStatus) virtual
Reimplemented in App::DocumentObject, and Gui::ViewProviderDocumentObject.
Definition at line 425 of file PropertyContainer.cpp.
Referenced by App::Property::setStatusValue().
operator=()
PropertyContainer& App::PropertyContainer::operator= (const PropertyContainer &) delete
removeDynamicProperty()
virtual bool App::PropertyContainer::removeDynamicProperty (const char * name) inline virtual
Reimplemented in App::DocumentObject, and Gui::ViewProviderDocumentObject.
Definition at line 213 of file PropertyContainer.h.
Referenced by App::TransactionObject::applyChn(), and Gui::ViewProviderDocumentObject::removeDynamicProperty().
Restore()
void PropertyContainer::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Reimplemented in Part::Ellipse, TechDraw::DrawViewDimension, PartDesign::Transformed, PartDesign::ProfileBased, PartDesign::Hole, PartDesign::Chamfer, Part::Circle, PartDesign::Plane, Part::Part2DObject, PartDesign::Fillet, App::VRMLObject, Part::Box, Part::Primitive, PartGui::ViewProvider2DObjectGrid, Points::Feature, Sketcher::SketchObject, and Robot::RobotObject.
Definition at line 332 of file PropertyContainer.cpp.
References Base::Console(), dynamicProps, SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), FC_TRACE, App::Property::getName(), getPropertyByName(), handleChangedPropertyName(), handleChangedPropertyType(), SplineSurface::i, App::Property::PropTransient, TechDrawTools.TaskFillTemplateFields::reader, App::DynamicProperty::restore(), App::Property::setStatusValue(), App::Property::StatusBits, and App::Property::Transient.
Referenced by App::ExtensionContainer::Restore(), App::Document::Restore(), and App::ProjectFile::restoreObject().
Save()
void PropertyContainer::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Reimplemented in App::VRMLObject, Sketcher::SketchObject, and Robot::RobotObject.
Definition at line 240 of file PropertyContainer.cpp.
References Base::Console(), Base::Writer::decInd(), dynamicProps, SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), getPropertyMap(), getPropertyType(), Base::Writer::incInd(), Base::Writer::ind(), App::Prop_Transient, App::Property::PropDynamic, App::Property::PropNoPersist, App::DynamicProperty::save(), Base::Writer::Stream(), and App::Property::Transient.
Referenced by App::ExtensionContainer::Save(), and App::Document::Save().
setPropertyPrefix()
void App::PropertyContainer::setPropertyPrefix (const char * prefix) inline
Definition at line 235 of file PropertyContainer.h.
Referenced by Gui::ViewProviderLink::onChanged().
setPropertyStatus()
void PropertyContainer::setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
Definition at line 101 of file PropertyContainer.cpp.
References getPropertyList().
Friends And Related Function Documentation
DynamicProperty
friend class DynamicProperty friend
Definition at line 240 of file PropertyContainer.h.
Property
friend class Property friend
Definition at line 239 of file PropertyContainer.h.
Member Data Documentation
dynamicProps
DynamicProperty App::PropertyContainer::dynamicProps protected
Definition at line 267 of file PropertyContainer.h.
Referenced by addDynamicProperty(), getPropertyByName(), getPropertyDocumentation(), getPropertyGroup(), getPropertyList(), getPropertyMap(), getPropertyName(), getPropertyNamedList(), Part::Box::Restore(), Restore(), and Save().
The documentation for this class was generated from the following files:
PropertyContainer.h
PropertyContainer.cpp