FreeCAD: Base::QuantityFormat Struct Reference
Base::QuantityFormat Struct Reference
#include <Quantity.h>
Public Types
enum NumberOption { None = 0x00, OmitGroupSeparator = 0x01, RejectGroupSeparator = 0x02 }
enum NumberFormat { Default = 0, Fixed = 1, Scientific = 2 }
using NumberOptions = int
Public Member Functions
int getDenominator () const
void setDenominator (int denom)
QuantityFormat ()
QuantityFormat (NumberFormat format, int decimals=-1)
char toFormat () const
Static Public Member Functions
static int getDefaultDenominator ()
static void setDefaultDenominator (int denom)
static NumberFormat toFormat (char ch, bool *ok=nullptr)
Public Attributes
NumberOptions option
NumberFormat format
int precision
int denominator
Static Public Attributes
static int defaultDenominator = 8
Detailed Description
Definition at line 43 of file Quantity.h.
Member Typedef Documentation
NumberOptions
using Base::QuantityFormat::NumberOptions = int
Definition at line 58 of file Quantity.h.
Member Enumeration Documentation
NumberFormat
enum Base::QuantityFormat::NumberFormat
Enumerator
Default
Fixed
Scientific
Definition at line 51 of file Quantity.h.
NumberOption
enum Base::QuantityFormat::NumberOption
Enumerator
None
OmitGroupSeparator
RejectGroupSeparator
Definition at line 45 of file Quantity.h.
Constructor & Destructor Documentation
QuantityFormat() [1/2]
QuantityFormat::QuantityFormat ()
Definition at line 59 of file Quantity.cpp.
QuantityFormat() [2/2]
QuantityFormat::QuantityFormat (QuantityFormat::NumberFormat format, int decimals = -1) explicit
Definition at line 66 of file Quantity.cpp.
Member Function Documentation
getDefaultDenominator()
static int Base::QuantityFormat::getDefaultDenominator () inline static
Definition at line 69 of file Quantity.h.
Referenced by Gui::Dialog::DlgSettingsGeneral::loadSettings().
getDenominator()
int Base::QuantityFormat::getDenominator () const inline
Definition at line 79 of file Quantity.h.
Referenced by Base::UnitsSchemaImperialBuilding::schemaTranslate().
setDefaultDenominator()
static void Base::QuantityFormat::setDefaultDenominator (int denom) inline static
Definition at line 74 of file Quantity.h.
setDenominator()
void Base::QuantityFormat::setDenominator (int denom) inline
Definition at line 84 of file Quantity.h.
toFormat() [1/2]
char Base::QuantityFormat::toFormat () const inline
Definition at line 90 of file Quantity.h.
Referenced by Gui::InputField::getFormat(), Gui::InputField::setFormat(), Base::UnitsApi::sToNumber(), and Base::UnitsSchema::toLocale().
toFormat() [2/2]
static NumberFormat Base::QuantityFormat::toFormat (char ch, bool * ok = nullptr) inline static
Definition at line 101 of file Quantity.h.
Member Data Documentation
defaultDenominator
int QuantityFormat::defaultDenominator = 8 static
Definition at line 67 of file Quantity.h.
denominator
int Base::QuantityFormat::denominator
Definition at line 62 of file Quantity.h.
format
NumberFormat Base::QuantityFormat::format
Definition at line 60 of file Quantity.h.
Referenced by Sketcher::Constraint::getPresentationValue(), Base::UnitsApi::sToNumber(), and Base::UnitsApi::toNumber().
option
NumberOptions Base::QuantityFormat::option
Definition at line 59 of file Quantity.h.
Referenced by Sketcher::Constraint::getPresentationValue(), and Base::UnitsSchema::toLocale().
precision
int Base::QuantityFormat::precision
Definition at line 61 of file Quantity.h.
Referenced by Gui::InputField::getPrecision(), Sketcher::Constraint::getPresentationValue(), ifc2x3.ifcgeometricrepresentationsubcontext::ifcgeometricrepresentationcontext_precision(), ifc4.ifcgeometricrepresentationsubcontext::ifcgeometricrepresentationcontext_precision(), Base::UnitsApi::sToNumber(), Base::UnitsSchema::toLocale(), and Base::UnitsApi::toNumber().
The documentation for this struct was generated from the following files:
Quantity.h
Quantity.cpp