FreeCAD: Gui::DockWnd::ReportOutputObserver Class Reference
Gui::DockWnd::ReportOutputObserver Class Reference
#include <ReportView.h>
Public Member Functions
ReportOutputObserver (ReportOutput *view)
bool eventFilter (QObject *obj, QEvent *event) override
Protected Member Functions
void showReportView ()
Protected Attributes
QPointer< ReportOutput > reportView
Detailed Description
Observer to enable report view on warnings / errors if not already enabled.
Definition at line 219 of file ReportView.h.
Constructor & Destructor Documentation
ReportOutputObserver()
ReportOutputObserver::ReportOutputObserver (ReportOutput * report) explicit
The ReportOutputObserver class is used to check if messages sent to the report view are warnings or errors, and if so and if the user has not disabled this in preferences, the report view is toggled on so the user always gets the warnings/errors
Definition at line 305 of file ReportView.cpp.
References reportView.
Member Function Documentation
eventFilter()
bool ReportOutputObserver::eventFilter (QObject * obj, QEvent * event) override
Definition at line 317 of file ReportView.cpp.
References Gui::DockWnd::ReportHighlighter::Critical, Gui::DockWnd::ReportHighlighter::Error, Gui::DockWnd::ReportHighlighter::LogText, Gui::DockWnd::ReportHighlighter::Message, CustomReportEvent::messageType(), reportView, Gui::ReportOutputParameter::showOnCritical(), Gui::ReportOutputParameter::showOnError(), Gui::ReportOutputParameter::showOnLogMessage(), Gui::ReportOutputParameter::showOnMessage(), Gui::ReportOutputParameter::showOnWarning(), showReportView(), and Gui::DockWnd::ReportHighlighter::Warning.
showReportView()
void ReportOutputObserver::showReportView () protected
Definition at line 311 of file ReportView.cpp.
References Gui::DockWindowManager::activate(), Gui::DockWindowManager::instance(), and reportView.
Referenced by eventFilter().
Member Data Documentation
reportView
QPointer<ReportOutput> Gui::DockWnd::ReportOutputObserver::reportView protected
Definition at line 228 of file ReportView.h.
Referenced by eventFilter(), ReportOutputObserver(), and showReportView().
The documentation for this class was generated from the following files:
ReportView.h
ReportView.cpp