FreeCAD: FemGui::TaskFemConstraintOnBoundary Class Reference
FemGui::TaskFemConstraintOnBoundary Class Reference abstract
Taskbox for FEM constraints that apply on subsets of the domain boundary.
#include <TaskFemConstraintOnBoundary.h>
Public Member Functions
TaskFemConstraintOnBoundary (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="")
~TaskFemConstraintOnBoundary () override
Public Member Functions inherited from FemGui::TaskFemConstraint
TaskFemConstraint (ViewProviderFemConstraint *ConstraintView, QWidget *parent=nullptr, const char *pixmapname="")
~TaskFemConstraint () override=default
virtual const std::string getReferences () const
const std::string getReferences (const std::vector< std::string > &items) const
const std::string getScale () const
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Protected Types
enum SelectionChangeModes { SelectionChangeModes::none, SelectionChangeModes::refAdd, SelectionChangeModes::refRemove }
Protected Types inherited from FemGui::TaskFemConstraint
enum { seldir, selref, selloc, selnone }
Protected Slots
void onButtonToggled (QAbstractButton *button, bool checked)
virtual void addToSelection ()=0
virtual void removeFromSelection ()=0
Protected Slots inherited from FemGui::TaskFemConstraint
void onReferenceDeleted (const int row)
void onButtonReference (const bool pressed=true)
void setSelection (QListWidgetItem *item)
bool event (QEvent *event) override
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Member Functions
void onSelectionChanged (const Gui::SelectionChanges &) override
virtual void clearButtons (const SelectionChangeModes notThis)=0
Protected Member Functions inherited from FemGui::TaskFemConstraint
void changeEvent (QEvent *e) override
const QString makeRefText (const std::string &objName, const std::string &subName) const
const QString makeRefText (const App::DocumentObject *obj, const std::string &subName) const
void keyPressEvent (QKeyEvent *ke) override
void createDeleteAction (QListWidget *parentList)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Protected Attributes
enum SelectionChangeModes selChangeMode
Gui::ButtonGroup * buttonGroup
Protected Attributes inherited from FemGui::TaskFemConstraint
QWidget * proxy
QAction * deleteAction
Gui::WeakPtrT< ViewProviderFemConstraint > ConstraintView
enum FemGui::TaskFemConstraint:: { ... } selectionMode
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
Taskbox for FEM constraints that apply on subsets of the domain boundary.
@detail Convenience superclass for taskboxes setting certain constraints that apply on subsets of the boundary (faces/edges/vertices), where one or more boundary entities need to be selected.
Definition at line 67 of file TaskFemConstraintOnBoundary.h.
Member Enumeration Documentation
SelectionChangeModes
enum FemGui::TaskFemConstraintOnBoundary::SelectionChangeModes strong protected
Enumerator
none
refAdd
refRemove
Definition at line 104 of file TaskFemConstraintOnBoundary.h.
Constructor & Destructor Documentation
TaskFemConstraintOnBoundary()
TaskFemConstraintOnBoundary::TaskFemConstraintOnBoundary (ViewProviderFemConstraint * ConstraintView, QWidget * parent = nullptr, const char * pixmapname = "") explicit
Definition at line 33 of file TaskFemConstraintOnBoundary.cpp.
References buttonGroup, draftgeoutils.intersections::connect(), FemGui::TaskFemConstraint::ConstraintView, onButtonToggled(), and Gui::ButtonGroup::setExclusive().
~TaskFemConstraintOnBoundary()
TaskFemConstraintOnBoundary::~TaskFemConstraintOnBoundary () override
Definition at line 50 of file TaskFemConstraintOnBoundary.cpp.
References FemGui::TaskFemConstraint::ConstraintView.
Member Function Documentation
addToSelection
virtual void FemGui::TaskFemConstraintOnBoundary::addToSelection () protected pure virtual slot
Referenced by onSelectionChanged().
clearButtons()
virtual void FemGui::TaskFemConstraintOnBoundary::clearButtons (const SelectionChangeModes notThis) protected pure virtual
Implemented in FemGui::TaskFemConstraintFluidBoundary, FemGui::TaskFemConstraintDisplacement, FemGui::TaskFemConstraintForce, FemGui::TaskFemConstraintHeatflux, FemGui::TaskFemConstraintRigidBody, FemGui::TaskFemConstraintTemperature, FemGui::TaskFemConstraintPressure, FemGui::TaskFemConstraintSpring, and FemGui::TaskFemConstraintFixed.
onButtonToggled
void TaskFemConstraintOnBoundary::onButtonToggled (QAbstractButton * button, bool checked) protected slot
Definition at line 56 of file TaskFemConstraintOnBoundary.cpp.
References buttonGroup, Gui::SelectionSingleton::clearSelection(), FemGui::TaskFemConstraint::ConstraintView, none, selChangeMode, and Gui::Selection().
Referenced by TaskFemConstraintOnBoundary().
onSelectionChanged()
void TaskFemConstraintOnBoundary::onSelectionChanged (const Gui::SelectionChanges & msg) override protected virtual
Reimplemented from FemGui::TaskFemConstraint.
Definition at line 73 of file TaskFemConstraintOnBoundary.cpp.
References Gui::SelectionChanges::AddSelection, addToSelection(), FemGui::TaskFemConstraint::ConstraintView, Path.Op.Surface::msg, none, refAdd, refRemove, removeFromSelection(), and selChangeMode.
removeFromSelection
virtual void FemGui::TaskFemConstraintOnBoundary::removeFromSelection () protected pure virtual slot
Referenced by onSelectionChanged().
Member Data Documentation
buttonGroup
Gui::ButtonGroup* FemGui::TaskFemConstraintOnBoundary::buttonGroup protected
Definition at line 115 of file TaskFemConstraintOnBoundary.h.
Referenced by onButtonToggled(), FemGui::TaskFemConstraintDisplacement::TaskFemConstraintDisplacement(), FemGui::TaskFemConstraintFixed::TaskFemConstraintFixed(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), FemGui::TaskFemConstraintForce::TaskFemConstraintForce(), FemGui::TaskFemConstraintHeatflux::TaskFemConstraintHeatflux(), TaskFemConstraintOnBoundary(), FemGui::TaskFemConstraintPressure::TaskFemConstraintPressure(), FemGui::TaskFemConstraintRigidBody::TaskFemConstraintRigidBody(), FemGui::TaskFemConstraintSpring::TaskFemConstraintSpring(), and FemGui::TaskFemConstraintTemperature::TaskFemConstraintTemperature().
selChangeMode
enum SelectionChangeModes FemGui::TaskFemConstraintOnBoundary::selChangeMode protected
Definition at line 114 of file TaskFemConstraintOnBoundary.h.
Referenced by onButtonToggled(), and onSelectionChanged().
The documentation for this class was generated from the following files:
TaskFemConstraintOnBoundary.h
TaskFemConstraintOnBoundary.cpp