FreeCAD: Gui::WorkbenchManipulator Class Reference
Gui::WorkbenchManipulator Class Reference
#include <WorkbenchManipulator.h>
Public Types
using Ptr = std::shared_ptr< WorkbenchManipulator >
Public Member Functions
WorkbenchManipulator ()=default
virtual ~WorkbenchManipulator ()=default
WorkbenchManipulator (const WorkbenchManipulator &)=delete
WorkbenchManipulator (WorkbenchManipulator &&)=delete
WorkbenchManipulator & operator= (const WorkbenchManipulator &)=delete
WorkbenchManipulator & operator= (WorkbenchManipulator &&)=delete
Static Public Member Functions
static void installManipulator (const WorkbenchManipulator::Ptr &)
installManipulator Installs a new instance of WorkbenchManipulator
static void removeManipulator (const WorkbenchManipulator::Ptr &)
removeManipulator Removes an installed instance of WorkbenchManipulator
static void removeAll ()
clear Removes all instances of WorkbenchManipulator
static void changeMenuBar (MenuItem *menuBar)
changeMenuBar Calls modifyMenuBar for every installed WorkbenchManipulator
static void changeContextMenu (const char *recipient, MenuItem *menuBar)
changeContextMenu Calls modifyContextMenu for every installed WorkbenchManipulator
static void changeToolBars (ToolBarItem *toolBar)
changeToolBars Calls modifyToolBars for every installed WorkbenchManipulator
static void changeDockWindows (DockWindowItems *dockWindow)
changeDockWindows Calls modifyDockWindows for every installed WorkbenchManipulator
Protected Member Functions
virtual void modifyMenuBar ([[maybe_unused]] MenuItem *menuBar)
modifyMenuBar Method to manipulate the menu structure of a workbench. The default implementation doesn't change anything.
virtual void modifyContextMenu ([[maybe_unused]] const char *recipient, [[maybe_unused]] MenuItem *menuBar)
modifyContextMenu Method to manipulate the contextmenu structure of a workbench. The default implementation doesn't change anything.
virtual void modifyToolBars ([[maybe_unused]] ToolBarItem *toolBar)
modifyToolBars Method to manipulate the toolbar structure of a workbench The default implementation doesn't change anything.
virtual void modifyDockWindows ([[maybe_unused]] DockWindowItems *dockWindow)
modifyDockWindows Method to manipulate the dock window structure of a workbench The default implementation doesn't change anything.
Static Protected Member Functions
static std::set< WorkbenchManipulator::Ptr > getManipulators ()
Detailed Description
The WorkbenchManipulator is a class that allows one to modify the workbench by adding or removing commands. WorkbenchManipulator provides methods to manipulate the MenuItem, ToolBarItem or DockWindowItems structure before setting up the workbench.
Author
Werner Mayer
Definition at line 66 of file Gui/WorkbenchManipulator.h.
Member Typedef Documentation
Ptr
using Gui::WorkbenchManipulator::Ptr = std::shared_ptr<WorkbenchManipulator>
Definition at line 69 of file Gui/WorkbenchManipulator.h.
Constructor & Destructor Documentation
WorkbenchManipulator() [1/3]
Gui::WorkbenchManipulator::WorkbenchManipulator () default
~WorkbenchManipulator()
virtual Gui::WorkbenchManipulator::~WorkbenchManipulator () virtual default
WorkbenchManipulator() [2/3]
Gui::WorkbenchManipulator::WorkbenchManipulator (const WorkbenchManipulator &) delete
WorkbenchManipulator() [3/3]
Gui::WorkbenchManipulator::WorkbenchManipulator (WorkbenchManipulator &&) delete
Member Function Documentation
changeContextMenu()
void WorkbenchManipulator::changeContextMenu (const char * recipient, MenuItem * menuBar) static
changeContextMenu Calls modifyContextMenu for every installed WorkbenchManipulator
Definition at line 62 of file Gui/WorkbenchManipulator.cpp.
Referenced by Gui::Workbench::createContextMenu().
changeDockWindows()
void WorkbenchManipulator::changeDockWindows (DockWindowItems * dockWindow) static
changeDockWindows Calls modifyDockWindows for every installed WorkbenchManipulator
Definition at line 76 of file Gui/WorkbenchManipulator.cpp.
Referenced by Gui::Workbench::activate().
changeMenuBar()
void WorkbenchManipulator::changeMenuBar (MenuItem * menuBar) static
changeMenuBar Calls modifyMenuBar for every installed WorkbenchManipulator
Definition at line 55 of file Gui/WorkbenchManipulator.cpp.
Referenced by Gui::Workbench::activate().
changeToolBars()
void WorkbenchManipulator::changeToolBars (ToolBarItem * toolBar) static
changeToolBars Calls modifyToolBars for every installed WorkbenchManipulator
Definition at line 69 of file Gui/WorkbenchManipulator.cpp.
Referenced by Gui::Workbench::activate().
getManipulators()
std::set< WorkbenchManipulator::Ptr > WorkbenchManipulator::getManipulators () static protected
Definition at line 50 of file Gui/WorkbenchManipulator.cpp.
Referenced by Gui::WorkbenchManipulatorPython::removeManipulator().
installManipulator()
void WorkbenchManipulator::installManipulator (const WorkbenchManipulator::Ptr & ptr) static
installManipulator Installs a new instance of WorkbenchManipulator
Definition at line 32 of file Gui/WorkbenchManipulator.cpp.
Referenced by Gui::WorkbenchManipulatorPython::installManipulator(), and PyMOD_INIT_FUNC().
modifyContextMenu()
void WorkbenchManipulator::modifyContextMenu ([[maybe_unused] ] const char * recipient, [[maybe_unused] ] MenuItem * menuBar) protected virtual
modifyContextMenu Method to manipulate the contextmenu structure of a workbench. The default implementation doesn't change anything.
Definition at line 87 of file Gui/WorkbenchManipulator.cpp.
modifyDockWindows()
void WorkbenchManipulator::modifyDockWindows ([[maybe_unused] ] DockWindowItems * dockWindow) protected virtual
modifyDockWindows Method to manipulate the dock window structure of a workbench The default implementation doesn't change anything.
Reimplemented in PartGui::WorkbenchManipulator.
Definition at line 96 of file Gui/WorkbenchManipulator.cpp.
modifyMenuBar()
void WorkbenchManipulator::modifyMenuBar ([[maybe_unused] ] MenuItem * menuBar) protected virtual
modifyMenuBar Method to manipulate the menu structure of a workbench. The default implementation doesn't change anything.
Definition at line 83 of file Gui/WorkbenchManipulator.cpp.
modifyToolBars()
void WorkbenchManipulator::modifyToolBars ([[maybe_unused] ] ToolBarItem * toolBar) protected virtual
modifyToolBars Method to manipulate the toolbar structure of a workbench The default implementation doesn't change anything.
Reimplemented in PartGui::WorkbenchManipulator.
Definition at line 92 of file Gui/WorkbenchManipulator.cpp.
operator=() [1/2]
WorkbenchManipulator& Gui::WorkbenchManipulator::operator= (const WorkbenchManipulator &) delete
operator=() [2/2]
WorkbenchManipulator& Gui::WorkbenchManipulator::operator= (WorkbenchManipulator &&) delete
removeAll()
void WorkbenchManipulator::removeAll () static
clear Removes all instances of WorkbenchManipulator
Definition at line 45 of file Gui/WorkbenchManipulator.cpp.
Referenced by Gui::Application::~Application().
removeManipulator()
void WorkbenchManipulator::removeManipulator (const WorkbenchManipulator::Ptr & ptr) static
removeManipulator Removes an installed instance of WorkbenchManipulator
Definition at line 37 of file Gui/WorkbenchManipulator.cpp.
Referenced by Gui::WorkbenchManipulatorPython::removeManipulator().
The documentation for this class was generated from the following files:
Gui/WorkbenchManipulator.h
Gui/WorkbenchManipulator.cpp