FreeCAD: MeshPartGui::CurveOnMeshHandler Class Reference
MeshPartGui::CurveOnMeshHandler Class Reference
#include <CurveOnMesh.h>
Classes
class Private
Public Member Functions
CurveOnMeshHandler (QObject *parent=nullptr)
~CurveOnMeshHandler () override
void enableApproximation (bool)
void setParameters (int maxDegree, GeomAbs_Shape cont, double tol3d, double angle)
void enableCallback (Gui::View3DInventor *viewer)
void disableCallback ()
void recomputeDocument ()
Detailed Description
Definition at line 69 of file CurveOnMesh.h.
Constructor & Destructor Documentation
CurveOnMeshHandler()
CurveOnMeshHandler::CurveOnMeshHandler (QObject * parent = nullptr) explicit
Definition at line 333 of file CurveOnMesh.cpp.
~CurveOnMeshHandler()
CurveOnMeshHandler::~CurveOnMeshHandler () override
Definition at line 338 of file CurveOnMesh.cpp.
References disableCallback().
Member Function Documentation
disableCallback()
void CurveOnMeshHandler::disableCallback ()
Definition at line 445 of file CurveOnMesh.cpp.
References Gui::View3DInventorViewer::removeEventCallback(), Gui::View3DInventorViewer::removeViewProvider(), Gui::View3DInventorViewer::setEditing(), and MeshPartGui::CurveOnMeshHandler::Private::vertexCallback().
Referenced by ~CurveOnMeshHandler().
enableApproximation()
void CurveOnMeshHandler::enableApproximation (bool on)
Definition at line 343 of file CurveOnMesh.cpp.
enableCallback()
void CurveOnMeshHandler::enableCallback (Gui::View3DInventor * viewer)
Definition at line 430 of file CurveOnMesh.cpp.
References Gui::View3DInventorViewer::addEventCallback(), Gui::View3DInventorViewer::addViewProvider(), Gui::View3DInventorViewer::setEditing(), Gui::View3DInventorViewer::setEditingCursor(), TestSpreadsheet::v, and MeshPartGui::CurveOnMeshHandler::Private::vertexCallback().
recomputeDocument()
void CurveOnMeshHandler::recomputeDocument ()
Definition at line 674 of file CurveOnMesh.cpp.
References toolbit-attributes::doc, Gui::Document::getDocument(), and Gui::View3DInventorViewer::getDocument().
Referenced by MeshPartGui::CurveOnMeshWidget::reject().
setParameters()
void CurveOnMeshHandler::setParameters (int maxDegree, GeomAbs_Shape cont, double tol3d, double angle)
Definition at line 348 of file CurveOnMesh.cpp.
References KDL::cos().
The documentation for this class was generated from the following files:
CurveOnMesh.h
CurveOnMesh.cpp