FreeCAD: SurfaceGui::GeomFillSurface Class Reference
SurfaceGui::GeomFillSurface Class Reference
#include <TaskGeomFillSurface.h>
Classes
class EdgeSelection
Public Member Functions
GeomFillSurface (ViewProviderGeomFillSurface *vp, Surface::GeomFillSurface *obj)
~GeomFillSurface () override
void open ()
void checkOpenCommand ()
bool accept ()
bool reject ()
void setEditedObject (Surface::GeomFillSurface *obj)
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Public Member Functions inherited from Gui::DocumentObserver
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
void attachDocument (Document *)
void detachDocument ()
Protected Types
enum SelectionMode { None, Append, Remove }
Protected Member Functions
void changeEvent (QEvent *e) override
void onSelectionChanged (const Gui::SelectionChanges &msg) override
void slotUndoDocument (const Gui::Document &Doc) override
void slotRedoDocument (const Gui::Document &Doc) override
void slotDeletedObject (const Gui::ViewProviderDocumentObject &Obj) override
void changeFillType (GeomFill_FillingStyle)
void flipOrientation (QListWidgetItem *)
Protected Attributes
SelectionMode selectionMode
Surface::GeomFillSurface * editedObject
bool checkCommand
Detailed Description
Definition at line 59 of file TaskGeomFillSurface.h.
Member Enumeration Documentation
SelectionMode
enum SurfaceGui::GeomFillSurface::SelectionMode protected
Enumerator
None
Append
Remove
Definition at line 65 of file TaskGeomFillSurface.h.
Constructor & Destructor Documentation
GeomFillSurface()
SurfaceGui::GeomFillSurface::GeomFillSurface (ViewProviderGeomFillSurface * vp, Surface::GeomFillSurface * obj)
Definition at line 200 of file TaskGeomFillSurface.cpp.
References checkCommand, draftgeoutils.intersections::connect(), None, App::Remove, selectionMode, setEditedObject(), and Gui::ButtonGroup::setExclusive().
Referenced by SurfaceGui::TaskGeomFillSurface::TaskGeomFillSurface().
~GeomFillSurface()
SurfaceGui::GeomFillSurface::~GeomFillSurface () override
Definition at line 233 of file TaskGeomFillSurface.cpp.
Member Function Documentation
accept()
bool SurfaceGui::GeomFillSurface::accept ()
Definition at line 375 of file TaskGeomFillSurface.cpp.
References Gui::Command::commitCommand(), src.Mod.AddonManager.NetworkManager::count, doCommand, editedObject, App::DocumentObject::getStatusString(), Gui::Command::Gui, SurfaceGui::ViewProviderGeomFillSurface::highlightReferences(), App::DocumentObject::isValid(), Surface::GeomFillSurface::mustExecute(), None, App::DocumentObject::recomputeFeature(), Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), selectionMode, Gui::Command::updateActive(), and Path.Log::warning().
changeEvent()
void SurfaceGui::GeomFillSurface::changeEvent (QEvent * e) override protected
Definition at line 324 of file TaskGeomFillSurface.cpp.
References SCL.SimpleDataTypes::e.
changeFillType()
void SurfaceGui::GeomFillSurface::changeFillType (GeomFill_FillingStyle fillType) protected
Definition at line 439 of file TaskGeomFillSurface.cpp.
References checkOpenCommand(), Base::Console(), editedObject, Base::ConsoleSingleton::Error(), Surface::GeomFillSurface::FillType, App::DocumentObject::getStatusString(), App::PropertyEnumeration::getValue(), App::DocumentObject::isValid(), App::DocumentObject::recomputeFeature(), and App::PropertyEnumeration::setValue().
checkOpenCommand()
void SurfaceGui::GeomFillSurface::checkOpenCommand ()
Definition at line 346 of file TaskGeomFillSurface.cpp.
References checkCommand, editedObject, App::PropertyString::getValue(), Gui::Command::hasPendingCommand(), App::DocumentObject::Label, FreeCADInit::Msg, and Gui::Command::openCommand().
Referenced by changeFillType(), onSelectionChanged(), and open().
flipOrientation()
void SurfaceGui::GeomFillSurface::flipOrientation (QListWidgetItem * item) protected
Definition at line 608 of file TaskGeomFillSurface.cpp.
References Gui::BitmapFactory(), editedObject, App::PropertyListsT< T, ListT, ParentT >::getValues(), Gui::BitmapFactoryInst::pixmap(), App::DocumentObject::recomputeFeature(), Surface::GeomFillSurface::ReversedList, and App::PropertyListsT< T, ListT, ParentT >::setValues().
onSelectionChanged()
void SurfaceGui::GeomFillSurface::onSelectionChanged (const Gui::SelectionChanges & msg) override protected virtual
Implements Gui::SelectionObserver.
Definition at line 475 of file TaskGeomFillSurface.cpp.
References Gui::SelectionChanges::AddSelection, Append, Gui::BitmapFactory(), Surface::GeomFillSurface::BoundaryList, checkOpenCommand(), editedObject, Gui::SelectionObject::getObject(), App::PropertyLinkSubList::getSubValues(), App::PropertyString::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyLinkSubList::getValues(), SurfaceGui::ViewProviderGeomFillSurface::highlightReferences(), SplineSurface::i, App::DocumentObject::Label, Path.Op.Surface::msg, None, importers.importIFCmulticore::objects, App::DocumentObject::recomputeFeature(), Surface::GeomFillSurface::ReversedList, selectionMode, App::PropertyListsT< T, ListT, ParentT >::setValues(), and App::PropertyLinkSubList::setValues().
open()
void SurfaceGui::GeomFillSurface::open ()
Definition at line 334 of file TaskGeomFillSurface.cpp.
References checkOpenCommand(), Gui::SelectionSingleton::clearSelection(), SurfaceGui::ViewProviderGeomFillSurface::highlightReferences(), and Gui::Selection().
reject()
bool SurfaceGui::GeomFillSurface::reject ()
Definition at line 412 of file TaskGeomFillSurface.cpp.
References Gui::Command::abortCommand(), doCommand, Gui::Command::Gui, SurfaceGui::ViewProviderGeomFillSurface::highlightReferences(), None, Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), selectionMode, and Gui::Command::updateActive().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action().
setEditedObject()
void SurfaceGui::GeomFillSurface::setEditedObject (Surface::GeomFillSurface * obj)
Definition at line 268 of file TaskGeomFillSurface.cpp.
References Gui::DocumentObserver::attachDocument(), Gui::BitmapFactory(), Surface::GeomFillSurface::BoundaryList, toolbit-attributes::doc, editedObject, Surface::GeomFillSurface::FillType, App::DocumentObject::getDocument(), App::PropertyLinkSubList::getSubValues(), App::PropertyEnumeration::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyLinkSubList::getValues(), Gui::Application::Instance, importers.importIFCmulticore::objects, Gui::BitmapFactoryInst::pixmap(), and Surface::GeomFillSurface::ReversedList.
Referenced by GeomFillSurface().
slotDeletedObject()
void SurfaceGui::GeomFillSurface::slotDeletedObject (const Gui::ViewProviderDocumentObject & Obj) override protected virtual
Notifies when the object is about to be removed.
Reimplemented from Gui::DocumentObserver.
Definition at line 366 of file TaskGeomFillSurface.cpp.
References SurfaceGui::ViewProviderGeomFillSurface::highlightReferences().
slotRedoDocument()
void SurfaceGui::GeomFillSurface::slotRedoDocument (const Gui::Document & Doc) override protected virtual
Notifies on redo
Reimplemented from Gui::DocumentObserver.
Definition at line 361 of file TaskGeomFillSurface.cpp.
References checkCommand.
slotUndoDocument()
void SurfaceGui::GeomFillSurface::slotUndoDocument (const Gui::Document & Doc) override protected virtual
Notifies on undo
Reimplemented from Gui::DocumentObserver.
Definition at line 356 of file TaskGeomFillSurface.cpp.
References checkCommand.
Member Data Documentation
checkCommand
bool SurfaceGui::GeomFillSurface::checkCommand protected
Definition at line 73 of file TaskGeomFillSurface.h.
Referenced by checkOpenCommand(), GeomFillSurface(), slotRedoDocument(), and slotUndoDocument().
editedObject
Surface::GeomFillSurface* SurfaceGui::GeomFillSurface::editedObject protected
Definition at line 72 of file TaskGeomFillSurface.h.
Referenced by accept(), changeFillType(), checkOpenCommand(), flipOrientation(), onSelectionChanged(), and setEditedObject().
selectionMode
SelectionMode SurfaceGui::GeomFillSurface::selectionMode protected
Definition at line 71 of file TaskGeomFillSurface.h.
Referenced by accept(), GeomFillSurface(), onSelectionChanged(), and reject().
The documentation for this class was generated from the following files:
TaskGeomFillSurface.h
TaskGeomFillSurface.cpp