FreeCAD: SurfaceGui::FillingEdgePanel Class Reference
SurfaceGui::FillingEdgePanel Class Reference
#include <TaskFillingEdge.h>
Classes
class ShapeSelection
Public Member Functions
FillingEdgePanel (ViewProviderFilling *vp, Surface::Filling *obj)
~FillingEdgePanel () override
void open ()
void checkOpenCommand ()
bool accept ()
bool reject ()
void setEditedObject (Surface::Filling *obj)
void appendButtons (Gui::ButtonGroup *)
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Public Member Functions inherited from Gui::DocumentObserver
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
void attachDocument (Document *)
void detachDocument ()
Protected Types
enum SelectionMode { None = SurfaceGui::SelectionMode::None, AppendEdge = SurfaceGui::SelectionMode::AppendEdgeConstraint, RemoveEdge = SurfaceGui::SelectionMode::RemoveEdgeConstraint }
Protected Member Functions
void changeEvent (QEvent *e) override
void onSelectionChanged (const Gui::SelectionChanges &msg) override
void slotUndoDocument (const Gui::Document &Doc) override
void slotRedoDocument (const Gui::Document &Doc) override
void slotDeletedObject (const Gui::ViewProviderDocumentObject &Obj) override
void modifyBoundary (bool)
Protected Attributes
SelectionMode selectionMode
Surface::Filling * editedObject
bool checkCommand
Detailed Description
Definition at line 47 of file TaskFillingEdge.h.
Member Enumeration Documentation
SelectionMode
enum SurfaceGui::FillingEdgePanel::SelectionMode protected
Enumerator
None
AppendEdge
RemoveEdge
Definition at line 53 of file TaskFillingEdge.h.
Constructor & Destructor Documentation
FillingEdgePanel()
SurfaceGui::FillingEdgePanel::FillingEdgePanel (ViewProviderFilling * vp, Surface::Filling * obj)
Definition at line 123 of file TaskFillingEdge.cpp.
References Path.Post.scripts.dynapath_4060_post::action, checkCommand, draftgeoutils.intersections::connect(), None, selectionMode, and setEditedObject().
~FillingEdgePanel()
SurfaceGui::FillingEdgePanel::~FillingEdgePanel () override
Definition at line 146 of file TaskFillingEdge.cpp.
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
accept()
bool SurfaceGui::FillingEdgePanel::accept ()
Definition at line 298 of file TaskFillingEdge.cpp.
References SurfaceGui::ViewProviderFilling::Edge, editedObject, App::DocumentObject::getStatusString(), App::PropertyLinkSubList::getSubListValues(), SurfaceGui::ViewProviderFilling::highlightReferences(), App::DocumentObject::isValid(), Surface::Filling::mustExecute(), None, App::DocumentObject::recomputeFeature(), Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), selectionMode, Surface::Filling::UnboundEdges, and Path.Log::warning().
appendButtons()
void SurfaceGui::FillingEdgePanel::appendButtons (Gui::ButtonGroup * buttonGroup)
Definition at line 177 of file TaskFillingEdge.cpp.
References SurfaceGui::AppendEdge, and SurfaceGui::RemoveEdge.
Referenced by SurfaceGui::TaskFilling::TaskFilling().
changeEvent()
void SurfaceGui::FillingEdgePanel::changeEvent (QEvent * e) override protected
Definition at line 240 of file TaskFillingEdge.cpp.
References SCL.SimpleDataTypes::e.
checkOpenCommand()
void SurfaceGui::FillingEdgePanel::checkOpenCommand ()
Definition at line 267 of file TaskFillingEdge.cpp.
References checkCommand, editedObject, App::PropertyString::getValue(), Gui::Command::hasPendingCommand(), App::DocumentObject::Label, FreeCADInit::Msg, and Gui::Command::openCommand().
Referenced by onSelectionChanged(), and open().
modifyBoundary()
void SurfaceGui::FillingEdgePanel::modifyBoundary (bool on) protected
Definition at line 645 of file TaskFillingEdge.cpp.
onSelectionChanged()
void SurfaceGui::FillingEdgePanel::onSelectionChanged (const Gui::SelectionChanges & msg) override protected virtual
Implements Gui::SelectionObserver.
Definition at line 427 of file TaskFillingEdge.cpp.
References Gui::SelectionChanges::AddSelection, AppendEdge, checkOpenCommand(), src.Mod.AddonManager.NetworkManager::count, SurfaceGui::ViewProviderFilling::Edge, editedObject, Gui::SelectionObject::getObject(), App::PropertyLinkSubList::getSubListValues(), App::PropertyLinkSubList::getSubValues(), App::PropertyString::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyLinkSubList::getValues(), SurfaceGui::ViewProviderFilling::highlightReferences(), SplineSurface::i, App::DocumentObject::Label, Path.Op.Surface::msg, None, importers.importIFCmulticore::objects, App::DocumentObject::recomputeFeature(), RemoveEdge, selectionMode, App::PropertyListsT< T, ListT, ParentT >::setValues(), App::PropertyStringList::setValues(), App::PropertyLinkSubList::setValues(), Surface::Filling::UnboundEdges, Surface::Filling::UnboundFaces, and Surface::Filling::UnboundOrder.
open()
void SurfaceGui::FillingEdgePanel::open ()
Definition at line 250 of file TaskFillingEdge.cpp.
References checkOpenCommand(), Gui::SelectionSingleton::clearSelection(), SurfaceGui::ViewProviderFilling::Edge, editedObject, App::PropertyLinkSubList::getSubListValues(), SurfaceGui::ViewProviderFilling::highlightReferences(), Gui::Selection(), and Surface::Filling::UnboundEdges.
Referenced by SurfaceGui::TaskFilling::open().
reject()
bool SurfaceGui::FillingEdgePanel::reject ()
Definition at line 319 of file TaskFillingEdge.cpp.
References SurfaceGui::ViewProviderFilling::Edge, editedObject, App::PropertyLinkSubList::getSubListValues(), SurfaceGui::ViewProviderFilling::highlightReferences(), None, Gui::SelectionSingleton::rmvSelectionGate(), Gui::Selection(), selectionMode, and Surface::Filling::UnboundEdges.
Referenced by SurfaceGui::TaskFilling::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and SurfaceGui::TaskFilling::reject().
setEditedObject()
void SurfaceGui::FillingEdgePanel::setEditedObject (Surface::Filling * obj)
Definition at line 184 of file TaskFillingEdge.cpp.
References Gui::DocumentObserver::attachDocument(), src.Mod.AddonManager.NetworkManager::count, toolbit-attributes::doc, editedObject, App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::PropertyLinkSubList::getSubValues(), App::PropertyString::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyLinkSubList::getValues(), SplineSurface::i, Gui::Application::Instance, App::DocumentObject::Label, importers.importIFCmulticore::objects, Surface::Filling::UnboundEdges, Surface::Filling::UnboundFaces, and Surface::Filling::UnboundOrder.
Referenced by FillingEdgePanel().
slotDeletedObject()
void SurfaceGui::FillingEdgePanel::slotDeletedObject (const Gui::ViewProviderDocumentObject & Obj) override protected virtual
Notifies when the object is about to be removed.
Reimplemented from Gui::DocumentObserver.
Definition at line 287 of file TaskFillingEdge.cpp.
References SurfaceGui::ViewProviderFilling::Edge, editedObject, App::PropertyLinkSubList::getSubListValues(), SurfaceGui::ViewProviderFilling::highlightReferences(), and Surface::Filling::UnboundEdges.
slotRedoDocument()
void SurfaceGui::FillingEdgePanel::slotRedoDocument (const Gui::Document & Doc) override protected virtual
Notifies on redo
Reimplemented from Gui::DocumentObserver.
Definition at line 282 of file TaskFillingEdge.cpp.
References checkCommand.
slotUndoDocument()
void SurfaceGui::FillingEdgePanel::slotUndoDocument (const Gui::Document & Doc) override protected virtual
Notifies on undo
Reimplemented from Gui::DocumentObserver.
Definition at line 277 of file TaskFillingEdge.cpp.
References checkCommand.
Member Data Documentation
checkCommand
bool SurfaceGui::FillingEdgePanel::checkCommand protected
Definition at line 61 of file TaskFillingEdge.h.
Referenced by checkOpenCommand(), FillingEdgePanel(), slotRedoDocument(), and slotUndoDocument().
editedObject
Surface::Filling* SurfaceGui::FillingEdgePanel::editedObject protected
Definition at line 60 of file TaskFillingEdge.h.
Referenced by accept(), checkOpenCommand(), onSelectionChanged(), open(), reject(), setEditedObject(), and slotDeletedObject().
selectionMode
SelectionMode SurfaceGui::FillingEdgePanel::selectionMode protected
Definition at line 59 of file TaskFillingEdge.h.
Referenced by accept(), FillingEdgePanel(), onSelectionChanged(), and reject().
The documentation for this class was generated from the following files:
TaskFillingEdge.h
TaskFillingEdge.cpp