FreeCAD: feminout.importInpMesh Namespace Reference
feminout.importInpMesh Namespace Reference
Functions
def open (filename)
def insert (filename, docname)
def read (filename)
def import_inp (filename)
def read_inp (file_name)
Function Documentation
import_inp()
def feminout.importInpMesh.import_inp (filename)
read a FEM mesh from a Z88 mesh file and insert a FreeCAD FEM Mesh object in the ActiveDocument
Definition at line 70 of file importInpMesh.py.
References feminout.importInpMesh.read().
Referenced by feminout.importInpMesh.insert().
insert()
def feminout.importInpMesh.insert (filename, docname)
Definition at line 50 of file importInpMesh.py.
References feminout.importInpMesh.import_inp().
Referenced by feminout.importInpMesh.open().
open()
def feminout.importInpMesh.open (filename)
Definition at line 44 of file importInpMesh.py.
References feminout.importInpMesh.insert().
read()
def feminout.importInpMesh.read (filename)
read a FemMesh from a inp mesh file and return the FemMesh
Definition at line 61 of file importInpMesh.py.
References feminout.importInpMesh.read_inp().
Referenced by feminout.importInpMesh.import_inp().
read_inp()
def feminout.importInpMesh.read_inp (file_name)
read .inp file
Definition at line 79 of file importInpMesh.py.
References Path.Post.scripts.uccnc_post.append().
Referenced by feminout.importInpMesh.read().