FreeCAD: importers.importSH3DHelper Namespace Reference
importers.importSH3DHelper Namespace Reference
Classes
class BaseFurnitureHandler
class BaseHandler
class CameraHandler
class DoorOrWindowHandler
class FurnitureHandler
class LevelHandler
class LightHandler
class RoomHandler
class SH3DImporter
class WallHandler
Functions
def dim_sh2fc (dimension)
def dim_fc2sh (dimension)
def coord_sh2fc (vector)
def ang_sh2fc (angle)
def set_color_and_transparency (obj, color)
def color_fc2sh (hexcode)
def hex2rgb (hexcode)
Variables
list DEBUG_EDGES_COLORS = ["5bc0eb", "fde74c", "9bc53d", "e55934", "fa7921"]
list DEBUG_POINT_COLORS = ["011627", "ff0022", "41ead4", "fdfffc", "b91372"]
bool RENDER_IS_AVAILABLE = True
bool FIX_INVALID_SWEEP = False
int FACTOR = 10
int DEFAULT_WALL_WIDTH = 100
TOLERANCE = float(.1)
ORIGIN = App.Vector(0, 0, 0)
X_NORM = App.Vector(1, 0, 0)
Y_NORM = App.Vector(0, 1, 0)
Z_NORM = App.Vector(0, 0, 1)
dictionary DOOR_MODELS
Function Documentation
ang_sh2fc()
def importers.importSH3DHelper.ang_sh2fc (angle)
Convert SweetHome angle (ยบ) to FreeCAD angle (ยบ)
SweetHome angles are clockwise positive while FreeCAD are anti-clockwise
positive
Args:
    angle (float): The angle in SweetHome
Returns:
    float: the FreeCAD angle
Definition at line 1676 of file importSH3DHelper.py.
Referenced by importers.importSH3DHelper.WallHandler.process().
color_fc2sh()
def importers.importSH3DHelper.color_fc2sh (hexcode)
Definition at line 1700 of file importSH3DHelper.py.
Referenced by importers.importSH3DHelper.SH3DImporter.import_sh3d_from_filename().
coord_sh2fc()
def importers.importSH3DHelper.coord_sh2fc (vector)
Converts SweetHome to FreeCAD coordinate
Args:
    FreeCAD.Vector (FreeCAD.Vector): The coordinate in SweetHome
Returns:
    FreeCAD.Vector: the FreeCAD coordinate
Definition at line 1664 of file importSH3DHelper.py.
Referenced by importers.importSH3DHelper.RoomHandler.process(), importers.importSH3DHelper.WallHandler.process(), importers.importSH3DHelper.DoorOrWindowHandler.process(), importers.importSH3DHelper.FurnitureHandler.process(), importers.importSH3DHelper.LightHandler.process(), and importers.importSH3DHelper.CameraHandler.process().
dim_fc2sh()
def importers.importSH3DHelper.dim_fc2sh (dimension)
Convert FreeCAD dimension (mm) to SweetHome dimension (cm)
Args:
    dimension (float): The dimension in FreeCAD
Returns:
    float: the SweetHome dimension
Definition at line 1652 of file importSH3DHelper.py.
Referenced by importers.importSH3DHelper.SH3DImporter.add_wall(), importers.importSH3DHelper.RoomHandler.process(), importers.importSH3DHelper.WallHandler.process(), importers.importSH3DHelper.DoorOrWindowHandler.process(), and importers.importSH3DHelper.FurnitureHandler.process().
dim_sh2fc()
def importers.importSH3DHelper.dim_sh2fc (dimension)
Convert SweetHome dimension (cm) to FreeCAD dimension (mm)
Args:
    dimension (float): The dimension in SweetHome
Returns:
    float: the FreeCAD dimension
Definition at line 1640 of file importSH3DHelper.py.
Referenced by importers.importSH3DHelper.LevelHandler.process(), importers.importSH3DHelper.WallHandler.process(), importers.importSH3DHelper.DoorOrWindowHandler.process(), importers.importSH3DHelper.FurnitureHandler.process(), and importers.importSH3DHelper.LightHandler.process().
hex2rgb()
def importers.importSH3DHelper.hex2rgb (hexcode)
Definition at line 1706 of file importSH3DHelper.py.
Referenced by importers.importSH3DHelper.WallHandler.process(), importers.importSH3DHelper.LightHandler.process(), and importers.importSH3DHelper.set_color_and_transparency().
set_color_and_transparency()
def importers.importSH3DHelper.set_color_and_transparency (obj, color)
Definition at line 1691 of file importSH3DHelper.py.
References importers.importSH3DHelper.hex2rgb().
Referenced by importers.importSH3DHelper.RoomHandler.process(), and importers.importSH3DHelper.WallHandler.process().
Variable Documentation
DEBUG_EDGES_COLORS
list importers.importSH3DHelper.DEBUG_EDGES_COLORS = ["5bc0eb", "fde74c", "9bc53d", "e55934", "fa7921"]
Definition at line 51 of file importSH3DHelper.py.
DEBUG_POINT_COLORS
list importers.importSH3DHelper.DEBUG_POINT_COLORS = ["011627", "ff0022", "41ead4", "fdfffc", "b91372"]
Definition at line 52 of file importSH3DHelper.py.
DEFAULT_WALL_WIDTH
int importers.importSH3DHelper.DEFAULT_WALL_WIDTH = 100
Definition at line 67 of file importSH3DHelper.py.
DOOR_MODELS
dictionary importers.importSH3DHelper.DOOR_MODELS
Definition at line 85 of file importSH3DHelper.py.
FACTOR
int importers.importSH3DHelper.FACTOR = 10
Definition at line 66 of file importSH3DHelper.py.
FIX_INVALID_SWEEP
bool importers.importSH3DHelper.FIX_INVALID_SWEEP = False
Definition at line 63 of file importSH3DHelper.py.
ORIGIN
importers.importSH3DHelper.ORIGIN = App.Vector(0, 0, 0)
Definition at line 70 of file importSH3DHelper.py.
RENDER_IS_AVAILABLE
bool importers.importSH3DHelper.RENDER_IS_AVAILABLE = True
Definition at line 57 of file importSH3DHelper.py.
TOLERANCE
importers.importSH3DHelper.TOLERANCE = float(.1)
Definition at line 68 of file importSH3DHelper.py.
X_NORM
importers.importSH3DHelper.X_NORM = App.Vector(1, 0, 0)
Definition at line 71 of file importSH3DHelper.py.
Y_NORM
importers.importSH3DHelper.Y_NORM = App.Vector(0, 1, 0)
Definition at line 72 of file importSH3DHelper.py.
Z_NORM
importers.importSH3DHelper.Z_NORM = App.Vector(0, 0, 1)
Definition at line 73 of file importSH3DHelper.py.