FreeCAD: Gui::PropertyEditor::PropertyEditorWidget Class Reference
Gui::PropertyEditor::PropertyEditorWidget Class Reference
#include <PropertyItem.h>
Public Slots
void setValue (const QVariant &)
Signals
void buttonClick ()
void valueChanged (const QVariant &)
Public Member Functions
PropertyEditorWidget (QWidget *parent=nullptr)
~PropertyEditorWidget () override
QVariant value () const
Protected Member Functions
virtual void showValue (const QVariant &data)
void resizeEvent (QResizeEvent *) override
Protected Attributes
QVariant variant
QLineEdit * lineEdit
QPushButton * button
Detailed Description
Definition at line 570 of file PropertyItem.h.
Constructor & Destructor Documentation
PropertyEditorWidget()
PropertyEditorWidget::PropertyEditorWidget (QWidget * parent = nullptr) explicit
Definition at line 1575 of file PropertyItem.cpp.
References button, buttonClick(), draftgeoutils.intersections::connect(), and lineEdit.
~PropertyEditorWidget()
PropertyEditorWidget::~PropertyEditorWidget () override default
Member Function Documentation
buttonClick
void Gui::PropertyEditor::PropertyEditorWidget::buttonClick () signal
Referenced by Gui::PropertyEditor::PropertyItem::createPropertyEditorWidget(), and PropertyEditorWidget().
resizeEvent()
void PropertyEditorWidget::resizeEvent (QResizeEvent * e) override protected
Definition at line 1606 of file PropertyItem.cpp.
References button, and SCL.SimpleDataTypes::e.
setValue
void PropertyEditorWidget::setValue (const QVariant & val) slot
Definition at line 1622 of file PropertyItem.cpp.
References showValue(), toolbit-attributes::val, valueChanged(), and variant.
Referenced by Gui::PropertyEditor::PropertyItemDelegate::setEditorData().
showValue()
void PropertyEditorWidget::showValue (const QVariant & data) protected virtual
Reimplemented in Gui::PropertyEditor::VectorListWidget.
Definition at line 1612 of file PropertyItem.cpp.
References lineEdit.
Referenced by setValue().
value()
QVariant PropertyEditorWidget::value () const
Definition at line 1617 of file PropertyItem.cpp.
References variant.
Referenced by src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), and Gui::PropertyEditor::VectorListWidget::showValue().
valueChanged
void Gui::PropertyEditor::PropertyEditorWidget::valueChanged (const QVariant &) signal
Referenced by Gui::PropertyEditor::PropertyVectorListItem::createEditor(), and setValue().
Member Data Documentation
button
QPushButton* Gui::PropertyEditor::PropertyEditorWidget::button protected
Definition at line 594 of file PropertyItem.h.
Referenced by TechDrawTools.TaskFillTemplateFields.TaskFillTemplateFields::chkEachChkBox(), src.Mod.AddonManager.AddonManagerTest.gui.gui_mocks.DialogWatcher::click_button(), TechDrawTools.TaskFillTemplateFields.TaskFillTemplateFields::on_cb1_clicked(), TechDrawTools.TaskFillTemplateFields.TaskFillTemplateFields::on_cb2_clicked(), TechDrawTools.TaskFillTemplateFields.TaskFillTemplateFields::on_cb3_clicked(), TechDrawTools.TaskFillTemplateFields.TaskFillTemplateFields::on_cb4_clicked(), TechDrawTools.TaskFillTemplateFields.TaskFillTemplateFields::on_cb5_clicked(), TechDrawTools.TaskFillTemplateFields.TaskFillTemplateFields::on_cb6_clicked(), TechDrawTools.TaskFillTemplateFields.TaskFillTemplateFields::on_cb7_clicked(), TechDrawTools.TaskFillTemplateFields.TaskFillTemplateFields::on_cb8_clicked(), TechDrawTools.TaskFillTemplateFields.TaskFillTemplateFields::on_cbAll_clicked(), PropertyEditorWidget(), resizeEvent(), and Gui::PropertyEditor::VectorListWidget::VectorListWidget().
lineEdit
QLineEdit* Gui::PropertyEditor::PropertyEditorWidget::lineEdit protected
Definition at line 593 of file PropertyItem.h.
Referenced by PropertyEditorWidget(), showValue(), and Gui::PropertyEditor::VectorListWidget::showValue().
variant
QVariant Gui::PropertyEditor::PropertyEditorWidget::variant protected
Definition at line 592 of file PropertyItem.h.
Referenced by setValue(), and value().
The documentation for this class was generated from the following files:
PropertyItem.h
PropertyItem.cpp