FreeCAD: App::FeaturePythonImp Class Reference
App::FeaturePythonImp Class Reference
#include <FeaturePython.h>
Public Types
enum ValueT { NotImplemented = 0, Accepted = 1, Rejected = 2 }
Public Member Functions
FeaturePythonImp (App::DocumentObject *)
~FeaturePythonImp ()
bool execute ()
bool mustExecute () const
void onBeforeChange (const Property *prop)
bool onBeforeChangeLabel (std::string &newLabel)
void onChanged (const Property *prop)
void onDocumentRestored ()
void unsetupObject ()
std::string getViewProviderName ()
PyObject * getPyObject ()
bool getSubObject (App::DocumentObject *&ret, const char *subname, PyObject **pyObj, Base::Matrix4D *mat, bool transform, int depth) const
bool getSubObjects (std::vector< std::string > &ret, int reason) const
bool getLinkedObject (App::DocumentObject *&ret, bool recurse, Base::Matrix4D *mat, bool transform, int depth) const
ValueT canLinkProperties () const
ValueT allowDuplicateLabel () const
ValueT redirectSubName (std::ostringstream &ss, App::DocumentObject *topParent, App::DocumentObject *child) const
int canLoadPartial () const
ValueT hasChildElement () const
return true to activate tree view group object handling
int isElementVisible (const char *) const
Get sub-element visibility.
int setElementVisible (const char *, bool)
Set sub-element visibility.
bool editProperty (const char *propName)
void init (PyObject *pyobj)
Detailed Description
Definition at line 57 of file FeaturePython.h.
Member Enumeration Documentation
ValueT
enum App::FeaturePythonImp::ValueT
Enumerator
NotImplemented
Accepted
Rejected
Definition at line 60 of file FeaturePython.h.
Constructor & Destructor Documentation
FeaturePythonImp()
FeaturePythonImp::FeaturePythonImp (App::DocumentObject * o) explicit
Definition at line 40 of file FeaturePython.cpp.
~FeaturePythonImp()
FeaturePythonImp::~FeaturePythonImp ()
Definition at line 44 of file FeaturePython.cpp.
References SCL.SimpleDataTypes::e, and FC_PY_FEATURE_PYTHON.
Member Function Documentation
allowDuplicateLabel()
FeaturePythonImp::ValueT FeaturePythonImp::allowDuplicateLabel () const
Definition at line 542 of file FeaturePython.cpp.
References _FC_PY_CALL_CHECK, Accepted, toolbit-attributes::args, SCL.SimpleDataTypes::e, App::DocumentObject::getPyObject(), NotImplemented, Base::pyCall(), and Rejected.
Referenced by App::FeaturePythonT< FeatureT >::setElementVisible().
canLinkProperties()
FeaturePythonImp::ValueT FeaturePythonImp::canLinkProperties () const
Definition at line 521 of file FeaturePython.cpp.
References _FC_PY_CALL_CHECK, Accepted, toolbit-attributes::args, SCL.SimpleDataTypes::e, App::DocumentObject::getPyObject(), NotImplemented, Base::pyCall(), and Rejected.
canLoadPartial()
int FeaturePythonImp::canLoadPartial () const
Definition at line 564 of file FeaturePython.cpp.
References _FC_PY_CALL_CHECK, toolbit-attributes::args, SCL.SimpleDataTypes::e, App::DocumentObject::getPyObject(), and Base::pyCall().
editProperty()
bool FeaturePythonImp::editProperty (const char * propName)
Definition at line 617 of file FeaturePython.cpp.
References _FC_PY_CALL_CHECK, toolbit-attributes::args, SCL.SimpleDataTypes::e, Base::pyCall(), and src.Mod.Test.testmakeWireString::String.
execute()
bool FeaturePythonImp::execute ()
Calls the execute() method of the Python feature class. If the Python feature class doesn't have an execute() method or if it returns False this method also return false and true otherwise.
Definition at line 75 of file FeaturePython.cpp.
References toolbit-attributes::args, FC_PY_CALL_CHECK, App::DocumentObject::getPyObject(), Base::pyCall(), and Base::PyException::ThrowException().
Referenced by draftobjects.facebinder.Facebinder::addSubobjects(), Path.Dressup.Gui.Dogbone.ObjectDressup::boneStateList(), Path.Dressup.Tags.ObjectTagDressup::generateTags(), ArchRoof._Roof::getSubVolume(), ArchPanel.PanelCut::getWires(), src.Mod.PartDesign.Scripts.Spring.MySpring::onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid::onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped::onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt::onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder::onChanged(), MeasureCOM.MeasureCOM::onChanged(), Path.Main.Stock.StockFromBase::onChanged(), Path.Main.Stock.StockCreateBox::onChanged(), Path.Main.Stock.StockCreateCylinder::onChanged(), FeaturePython.DistanceBolt::onChanged(), draftobjects.draftlink.DraftLink::onDocumentRestored(), ArchSchedule._ArchSchedule::setSpreadsheetData(), draftobjects.array.Array::update_properties_0v21(), and App::FeaturePythonT< FeatureT >::~FeaturePythonT().
getLinkedObject()
bool FeaturePythonImp::getLinkedObject (App::DocumentObject *& ret, bool recurse, Base::Matrix4D * mat, bool transform, int depth) const
Definition at line 375 of file FeaturePython.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, App::DocumentObject::getPyObject(), and Base::pyCall().
getPyObject()
PyObject * FeaturePythonImp::getPyObject ()
Definition at line 433 of file FeaturePython.cpp.
getSubObject()
bool FeaturePythonImp::getSubObject (App::DocumentObject *& ret, const char * subname, PyObject ** pyObj, Base::Matrix4D * mat, bool transform, int depth) const
Definition at line 265 of file FeaturePython.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, App::DocumentObject::getPyObject(), Py::new_reference_to(), Base::pyCall(), and src.Mod.Test.testmakeWireString::String.
getSubObjects()
bool FeaturePythonImp::getSubObjects (std::vector< std::string > & ret, int reason) const
Definition at line 339 of file FeaturePython.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, App::DocumentObject::getPyObject(), SplineSurface::i, and Base::pyCall().
getViewProviderName()
std::string FeaturePythonImp::getViewProviderName ()
Definition at line 504 of file FeaturePython.cpp.
References _FC_PY_CALL_CHECK, toolbit-attributes::args, SCL.SimpleDataTypes::e, App::DocumentObject::getPyObject(), Base::pyCall(), and src.Mod.Test.testmakeWireString::String.
hasChildElement()
FeaturePythonImp::ValueT FeaturePythonImp::hasChildElement () const
return true to activate tree view group object handling
Definition at line 439 of file FeaturePython.cpp.
References _FC_PY_CALL_CHECK, Accepted, toolbit-attributes::args, SCL.SimpleDataTypes::e, App::DocumentObject::getPyObject(), NotImplemented, Base::pyCall(), and Rejected.
Referenced by App::FeaturePythonT< FeatureT >::getSubObjects().
init()
void FeaturePythonImp::init (PyObject * pyobj)
Definition at line 58 of file FeaturePython.cpp.
References FC_PY_FEATURE_PYTHON.
Referenced by DocumentObject.DocumentObject::onChanged().
isElementVisible()
int FeaturePythonImp::isElementVisible (const char * element) const
Get sub-element visibility.
Definition at line 461 of file FeaturePython.cpp.
References _FC_PY_CALL_CHECK, toolbit-attributes::args, SCL.SimpleDataTypes::e, App::DocumentObject::getPyObject(), Base::pyCall(), and src.Mod.Test.testmakeWireString::String.
mustExecute()
bool FeaturePythonImp::mustExecute () const
Definition at line 108 of file FeaturePython.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, FC_PY_CALL_CHECK, App::DocumentObject::getPyObject(), and Base::pyCall().
onBeforeChange()
void FeaturePythonImp::onBeforeChange (const Property * prop)
Definition at line 132 of file FeaturePython.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, App::DocumentObject::getPyObject(), Base::pyCall(), and src.Mod.Test.testmakeWireString::String.
Referenced by App::FeaturePythonT< FeatureT >::getPyObject().
onBeforeChangeLabel()
bool FeaturePythonImp::onBeforeChangeLabel (std::string & newLabel)
Definition at line 163 of file FeaturePython.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, App::DocumentObject::getPyObject(), Base::pyCall(), and src.Mod.Test.testmakeWireString::String.
onChanged()
void FeaturePythonImp::onChanged (const Property * prop)
Definition at line 191 of file FeaturePython.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, App::DocumentObject::getPyObject(), Base::pyCall(), and src.Mod.Test.testmakeWireString::String.
Referenced by draftviewproviders.view_base.ViewProviderDraft::attach(), ArchSpace._ViewProviderSpace::onChanged(), ArchSchedule._ArchSchedule::setProperties(), draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), ArchAxis._ViewProviderAxis::updateData(), draftviewproviders.view_dimension.ViewProviderLinearDimension::updateData(), ArchSpace._ViewProviderSpace::updateData(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchSite._ViewProviderSite::updateData(), ArchSectionPlane._ViewProviderSectionPlane::updateData(), and ArchPanel.ViewProviderPanelSheet::updateData().
onDocumentRestored()
void FeaturePythonImp::onDocumentRestored ()
Definition at line 221 of file FeaturePython.cpp.
References _FC_PY_CALL_CHECK, toolbit-attributes::args, SCL.SimpleDataTypes::e, App::DocumentObject::getPyObject(), and Base::pyCall().
Referenced by Path.Base.PropertyBag.PropertyBag::__init__(), Path.Dressup.DogboneII.Proxy::__init__(), and App::FeaturePythonT< FeatureT >::onBeforeChange().
redirectSubName()
FeaturePythonImp::ValueT FeaturePythonImp::redirectSubName (std::ostringstream & ss, App::DocumentObject * topParent, App::DocumentObject * child) const
Definition at line 585 of file FeaturePython.cpp.
References _FC_PY_CALL_CHECK, Accepted, toolbit-attributes::args, SCL.SimpleDataTypes::e, App::DocumentObject::getPyObject(), NotImplemented, Base::pyCall(), Rejected, and src.Mod.Test.testmakeWireString::String.
setElementVisible()
int FeaturePythonImp::setElementVisible (const char * element, bool visible)
Set sub-element visibility.
Definition at line 482 of file FeaturePython.cpp.
References _FC_PY_CALL_CHECK, toolbit-attributes::args, SCL.SimpleDataTypes::e, App::DocumentObject::getPyObject(), Base::pyCall(), and src.Mod.Test.testmakeWireString::String.
unsetupObject()
void FeaturePythonImp::unsetupObject ()
Definition at line 243 of file FeaturePython.cpp.
References _FC_PY_CALL_CHECK, toolbit-attributes::args, SCL.SimpleDataTypes::e, App::DocumentObject::getPyObject(), and Base::pyCall().
Referenced by App::FeaturePythonT< FeatureT >::onBeforeChangeLabel().
The documentation for this class was generated from the following files:
FeaturePython.h
FeaturePython.cpp