FreeCAD: Gui::ActionGroup Class Reference
Gui::ActionGroup Class Reference
#include <Action.h>
Public Slots
void onActivated () override
void onToggled (bool) override
void onActivated (QAction *)
void onHovered (QAction *)
Public Slots inherited from Gui::Action
virtual void onActivated ()
virtual void onToggled (bool)
Signals
void aboutToHide (QMenu *)
When drop down menu is enabled, the signal is triggered just before hiding the menu.
void aboutToShow (QMenu *)
When drop down menu is enabled, the signal is triggered just before showing the menu.
Public Member Functions
ActionGroup (Command *pcCmd, QObject *parent=nullptr)
~ActionGroup () override
void addTo (QWidget *widget) override
void setEnabled (bool) override
void setDisabled (bool)
void setExclusive (bool)
bool isExclusive () const
void setVisible (bool) override
void setIsMode (bool check)
void setRememberLast (bool)
bool doesRememberLast () const
void setDropDownMenu (bool check)
QAction * addAction (QAction *)
QAction * addAction (const QString &)
QList< QAction * > actions () const
int checkedAction () const
void setCheckedAction (int)
QActionGroup * groupAction () const
Public Member Functions inherited from Gui::Action
Action (Command *pcCmd, QObject *parent=nullptr)
Action (Command *pcCmd, QAction *action, QObject *parent)
Action takes ownership of the 'action' object.
~Action () override
void setCheckable (bool)
void setChecked (bool, bool no_signal=false)
bool isChecked () const
bool isEnabled () const
void setShortcut (const QString &)
QKeySequence shortcut () const
void setIcon (const QIcon &)
QIcon icon () const
void setStatusTip (const QString &)
QString statusTip () const
void setText (const QString &)
QString text () const
void setToolTip (const QString &, const QString &title=QString())
QString toolTip () const
void setWhatsThis (const QString &)
QString whatsThis () const
void setMenuRole (QAction::MenuRole menuRole)
QAction * action () const
Command * command () const
Additional Inherited Members
Static Public Member Functions inherited from Gui::Action
static QString createToolTip (QString helpText, const QString &title, const QFont &font, const QString &shortCut, const Command *command=nullptr)
static QString commandToolTip (const Command *cmd, bool richFormat=true)
static QString commandMenuText (const Command *cmd)
static QString cleanTitle (const QString &title)
Clean the title by stripping the mnemonic symbol '&' and ending punctuation.
Detailed Description
The ActionGroup class is the link between Qt's QActionGroup class and FreeCAD's command classes (Command). Compared to Action with an ActionGroup it is possible to implement a single command with a group of toggable actions where e.g. one is set exclusive.
Author
Werner Mayer
Definition at line 151 of file Action.h.
Constructor & Destructor Documentation
ActionGroup()
ActionGroup::ActionGroup (Command * pcCmd, QObject * parent = nullptr) explicit
Constructs an action called name with parent parent. It also stores a pointer to the command object.
Definition at line 432 of file Action.cpp.
References draftgeoutils.intersections::connect(), onActivated(), and onHovered().
~ActionGroup()
ActionGroup::~ActionGroup () override
Definition at line 444 of file Action.cpp.
Member Function Documentation
aboutToHide
void Gui::ActionGroup::aboutToHide (QMenu *) signal
When drop down menu is enabled, the signal is triggered just before hiding the menu.
Referenced by addTo().
aboutToShow
void Gui::ActionGroup::aboutToShow (QMenu *) signal
When drop down menu is enabled, the signal is triggered just before showing the menu.
Referenced by addTo(), CmdSketcherGrid::createAction(), CmdSketcherSnap::createAction(), and CmdRenderingOrder::createAction().
actions()
QList< QAction * > ActionGroup::actions () const
Definition at line 549 of file Action.cpp.
References groupAction().
Referenced by CmdSketcherSnap::activated(), addTo(), Gui::WorkbenchGroup::addTo(), Gui::WindowAction::addTo(), checkedAction(), CmdSketcherGrid::languageChange(), CmdSketcherSnap::languageChange(), CmdRenderingOrder::languageChange(), Gui::WorkbenchGroup::onWorkbenchActivated(), Gui::WorkbenchGroup::refreshWorkbenchList(), CmdSketcherCompLine::updateAction(), CmdSketcherCompCreateArc::updateAction(), CmdSketcherCompCreateConic::updateAction(), CmdSketcherCompDimensionTools::updateAction(), CmdSketcherCompExternal::updateAction(), CmdSketcherCompSlot::updateAction(), and Gui::WorkbenchComboBox::WorkbenchComboBox().
addAction() [1/2]
QAction * ActionGroup::addAction (const QString & text)
Definition at line 544 of file Action.cpp.
References groupAction().
addAction() [2/2]
QAction * ActionGroup::addAction (QAction * action)
Definition at line 539 of file Action.cpp.
References Gui::Action::action(), and groupAction().
Referenced by StdCmdWindowsMenu::createAction().
addTo()
void ActionGroup::addTo (QWidget * widget) override virtual
Adds this action to widget w.
Reimplemented from Gui::Action.
Reimplemented in Gui::WindowAction, and Gui::WorkbenchGroup.
Definition at line 452 of file Action.cpp.
References aboutToHide(), aboutToShow(), Gui::Action::action(), actions(), draftgeoutils.intersections::connect(), groupAction(), NavigationIndicatorGui::menu, and Gui::Action::text().
Referenced by src.Mod.PartDesign.WizardShaft.Shaft.Shaft::equilibrium().
checkedAction()
int ActionGroup::checkedAction () const
Definition at line 554 of file Action.cpp.
References actions(), and groupAction().
doesRememberLast()
bool ActionGroup::doesRememberLast () const
Definition at line 534 of file Action.cpp.
groupAction()
QActionGroup* Gui::ActionGroup::groupAction () const inline
Definition at line 177 of file Action.h.
Referenced by actions(), addAction(), addTo(), Gui::WindowAction::addTo(), checkedAction(), isExclusive(), onActivated(), Gui::WorkbenchGroup::refreshWorkbenchList(), Gui::RecentFilesAction::resizeList(), Gui::RecentMacrosAction::resizeList(), setCheckedAction(), setDisabled(), setEnabled(), setExclusive(), setVisible(), Gui::WorkbenchComboBox::WorkbenchComboBox(), and Gui::WorkbenchTabWidget::WorkbenchTabWidget().
isExclusive()
bool ActionGroup::isExclusive () const
Definition at line 518 of file Action.cpp.
References groupAction().
onActivated [1/2]
void ActionGroup::onActivated () override slot
Activates the command.
Definition at line 577 of file Action.cpp.
References Gui::Action::command(), Gui::Command::invoke(), and Gui::Command::TriggerAction.
Referenced by ActionGroup(), and onToggled().
onActivated [2/2]
void ActionGroup::onActivated (QAction * act) slot
Activates the command.
Definition at line 591 of file Action.cpp.
References Gui::Action::command(), groupAction(), Gui::Command::invoke(), Gui::Action::setIcon(), Path.Base.Util::setProperty(), Gui::Action::setToolTip(), and Gui::Command::TriggerChildAction.
onHovered
void ActionGroup::onHovered (QAction * act) slot
Definition at line 605 of file Action.cpp.
References RobotExample::pos.
Referenced by ActionGroup().
onToggled
void ActionGroup::onToggled (bool check) override slot
Definition at line 582 of file Action.cpp.
References ArchCommands::check(), and onActivated().
setCheckedAction()
void ActionGroup::setCheckedAction (int index)
Definition at line 561 of file Action.cpp.
References groupAction(), Gui::Action::setIcon(), Path.Base.Util::setProperty(), and Gui::Action::setToolTip().
Referenced by StdCmdDrawStyle::updateIcon(), and StdCmdUserEditMode::updateIcon().
setDisabled()
void ActionGroup::setDisabled (bool check)
Definition at line 507 of file Action.cpp.
References ArchCommands::check(), groupAction(), and Gui::Action::setEnabled().
setDropDownMenu()
void Gui::ActionGroup::setDropDownMenu (bool check) inline
Definition at line 170 of file Action.h.
setEnabled()
void ActionGroup::setEnabled (bool enable) override virtual
Sets whether the action is enabled.
Reimplemented from Gui::Action.
Definition at line 501 of file Action.cpp.
References ArchCommands::check(), groupAction(), and Gui::Action::setEnabled().
Referenced by Path.Dressup.Gui.Tags.HoldingTagMarker::setSelected().
setExclusive()
void ActionGroup::setExclusive (bool check)
Definition at line 513 of file Action.cpp.
References ArchCommands::check(), and groupAction().
setIsMode()
void Gui::ActionGroup::setIsMode (bool check) inline
Definition at line 165 of file Action.h.
setRememberLast()
void ActionGroup::setRememberLast (bool remember)
Definition at line 529 of file Action.cpp.
setVisible()
void ActionGroup::setVisible (bool check) override virtual
Reimplemented from Gui::Action.
Definition at line 523 of file Action.cpp.
References ArchCommands::check(), groupAction(), and Gui::Action::setVisible().
The documentation for this class was generated from the following files:
Action.h
Action.cpp