FreeCAD: Gui::LabelButton Class Reference
Gui::LabelButton Class Reference
#include <Widgets.h>
Public Slots
void setValue (const QVariant &)
Signals
void valueChanged (const QVariant &)
void buttonClicked ()
Public Member Functions
LabelButton (QWidget *parent=nullptr)
~LabelButton () override
QVariant value () const
QLabel * getLabel () const
QPushButton * getButton () const
Protected Slots
virtual void browse ()
Protected Member Functions
virtual void showValue (const QVariant &data)
void resizeEvent (QResizeEvent *) override
Properties
QVariant value
Detailed Description
The LabelButton class provides a label with a button on the right side.
Author
Werner Mayer
Definition at line 404 of file Widgets.h.
Constructor & Destructor Documentation
LabelButton()
LabelButton::LabelButton (QWidget * parent = nullptr)
Constructs a file chooser called name with the parent parent.
Definition at line 1059 of file Widgets.cpp.
References browse(), buttonClicked(), and draftgeoutils.intersections::connect().
~LabelButton()
LabelButton::~LabelButton () override default
Member Function Documentation
browse
void LabelButton::browse () protected virtual slot
Definition at line 1115 of file Widgets.cpp.
Referenced by LabelButton().
buttonClicked
void Gui::LabelButton::buttonClicked () signal
Referenced by PartGui::PropertyEnumAttacherItem::createEditor(), and LabelButton().
getButton()
QPushButton * LabelButton::getButton () const
Definition at line 1093 of file Widgets.cpp.
getLabel()
QLabel * LabelButton::getLabel () const
Definition at line 1088 of file Widgets.cpp.
resizeEvent()
void LabelButton::resizeEvent (QResizeEvent * e) override protected
Definition at line 1082 of file Widgets.cpp.
References SCL.SimpleDataTypes::e.
setValue
void LabelButton::setValue (const QVariant & val) slot
Definition at line 1103 of file Widgets.cpp.
References showValue(), toolbit-attributes::val, and valueChanged().
Referenced by PartGui::PropertyEnumAttacherItem::setEditorData().
showValue()
void LabelButton::showValue (const QVariant & data) protected virtual
Definition at line 1110 of file Widgets.cpp.
Referenced by setValue().
value()
QVariant Gui::LabelButton::value () const
Referenced by src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), and src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue().
valueChanged
void Gui::LabelButton::valueChanged (const QVariant &) signal
Referenced by PartGui::PropertyEnumAttacherItem::createEditor(), Gui::PropertyEditor::PropertyPlacementItem::createEditor(), and setValue().
Property Documentation
value
QVariant LabelButton::value read write
Definition at line 408 of file Widgets.h.
Referenced by src.Mod.AddonManager.Addon.Addon.Status::__lt__(), OpenSCADUtils.OpenSCADError::__str__(), femobjects.base_fempythonobject._PropHelper::add_to_object(), Path.Base.Property.Property::displayString(), Path.Base.SetupSheetOpPrototype.Property::displayString(), Path.Base.Property.PropertyQuantity::displayString(), Path.Base.SetupSheetOpPrototype.PropertyQuantity::displayString(), PartGui::PropertyEnumAttacherItem::editorData(), src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), Path.Base.Property.Property::getValue(), Path.Base.SetupSheetOpPrototype.Property::getValue(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), Path.Base.SetupSheetOpPrototype.Property::setValue(), and Path.Base.Property.Property::setValue().
The documentation for this class was generated from the following files:
Widgets.h
Widgets.cpp