FreeCAD: Area.h File Reference
libarea/Area.h File Reference
#include "Curve.h"
#include "clipper.hpp"
Classes
struct CAreaPocketParams
class CArea
Macros
#define CAREA_PARAM_DECLARE(_type, _name)
Enumerations
enum PocketMode { SpiralPocketMode, ZigZagPocketMode, SingleOffsetPocketMode, ZigZagThenSingleOffsetPocketMode }
enum eOverlapType { eOutside, eInside, eSiblings, eCrossing }
Functions
eOverlapType GetOverlapType (const CCurve &c1, const CCurve &c2)
eOverlapType GetOverlapType (const CArea &a1, const CArea &a2)
bool IsInside (const Point &p, const CCurve &c)
bool IsInside (const Point &p, const CArea &a)
Macro Definition Documentation
CAREA_PARAM_DECLARE
#define CAREA_PARAM_DECLARE (_type, _name)
Value:
    static _type get_##_name();                                                                    \
    static void set_##_name(_type _name);
Definition at line 104 of file libarea/Area.h.
Enumeration Type Documentation
eOverlapType
enum eOverlapType
Enumerator
eOutside
eInside
eSiblings
eCrossing
Definition at line 126 of file libarea/Area.h.
PocketMode
enum PocketMode
Enumerator
SpiralPocketMode
ZigZagPocketMode
SingleOffsetPocketMode
ZigZagThenSingleOffsetPocketMode
Definition at line 12 of file libarea/Area.h.
Function Documentation
GetOverlapType() [1/2]
eOverlapType GetOverlapType (const CArea & a1, const CArea & a2)
Definition at line 852 of file libarea/Area.cpp.
References NavigationIndicatorGui::a1, NavigationIndicatorGui::a2, eCrossing, eInside, eOutside, eSiblings, CArea::Intersect(), CArea::m_curves, and CArea::Subtract().
GetOverlapType() [2/2]
eOverlapType GetOverlapType (const CCurve & c1, const CCurve & c2)
Definition at line 842 of file libarea/Area.cpp.
References NavigationIndicatorGui::a1, NavigationIndicatorGui::a2, src.Mod.PartDesign.Scripts.Gear::c1, and GetOverlapType().
Referenced by GetOverlapType(), CInnerCurves::Insert(), and MarkOverlappingOffsetIslands().
IsInside() [1/2]
bool IsInside (const Point & p, const CArea & a)
Definition at line 883 of file libarea/Area.cpp.
References a, NavigationIndicatorGui::a2, SCL.SimpleDataTypes::c, and buildPsets::p.
IsInside() [2/2]
bool IsInside (const Point & p, const CCurve & c)
Definition at line 876 of file libarea/Area.cpp.
References a, SCL.SimpleDataTypes::c, IsInside(), and buildPsets::p.
Referenced by CArea::InsideCurves(), and IsInside().