FreeCAD: OpenSCAD2Dgeom Namespace Reference
OpenSCAD2Dgeom Namespace Reference
Classes
class Overlappingfaces
Functions
def findConnectedEdges (edgelist, eps=1e-6, debug=False)
def endpointdistance (edges)
def endpointdistancedebuglist (debuglist)
def edgestowires (edgelist, eps=0.001)
def subtractfaces (faces)
def fusefaces (faces)
def subtractfaces2 (faces)
def edgestofaces (edges, algo=3, eps=0.001)
def superWireReverse (debuglist, closed=False)
def importDXFface (filename, layer=None, doc=None)
Function Documentation
edgestofaces()
def OpenSCAD2Dgeom.edgestofaces (edges, algo = 3, eps = 0.001)
Definition at line 342 of file OpenSCAD2Dgeom.py.
References edgestowires(), subtractfaces(), and subtractfaces2().
Referenced by OpenSCADCommands.Edgestofaces.Activated(), prototype.Node.addtofreecad(), and importDXFface().
edgestowires()
def OpenSCAD2Dgeom.edgestowires (edgelist, eps = 0.001)
takes list of edges and returns a list of wires
Definition at line 284 of file OpenSCAD2Dgeom.py.
References endpointdistancedebuglist(), findConnectedEdges(), and superWireReverse().
Referenced by edgestofaces().
endpointdistance()
def OpenSCAD2Dgeom.endpointdistance (edges)
return the distance of vertices in path (list of edges) as
maximum, minimum and distance between start and endpoint
it expects the edges to be traversed forward starting from Vertex 0
Definition at line 250 of file OpenSCAD2Dgeom.py.
References KDL.max(), and KDL.min().
endpointdistancedebuglist()
def OpenSCAD2Dgeom.endpointdistancedebuglist (debuglist)
return the distance of vertices in path (list of edges) as
maximum, minimum and distance between start and endpoint
it expects a 'not reversed' flag for every edge
Definition at line 266 of file OpenSCAD2Dgeom.py.
References KDL.max(), and KDL.min().
Referenced by edgestowires().
findConnectedEdges()
def OpenSCAD2Dgeom.findConnectedEdges (edgelist, eps = 1e-6, debug = False)
returns a list of list of connected edges
Definition at line 203 of file OpenSCAD2Dgeom.py.
Referenced by edgestowires().
fusefaces()
def OpenSCAD2Dgeom.fusefaces (faces)
Definition at line 331 of file OpenSCAD2Dgeom.py.
Referenced by OpenSCAD2Dgeom.Overlappingfaces.makeshape(), and subtractfaces2().
importDXFface()
def OpenSCAD2Dgeom.importDXFface (filename, layer = None, doc = None)
Definition at line 436 of file OpenSCAD2Dgeom.py.
References edgestofaces(), importDXF.getDXFlibs(), importDXF.processdxf(), and importDXF.readPreferences().
Referenced by OpenSCADUtils.process2D_ObjectsViaOpenSCADShape(), importCSG.processDXF(), and importCSG.processTextCmd().
subtractfaces()
def OpenSCAD2Dgeom.subtractfaces (faces)
searches for the biggest face and subtracts all smaller ones from the
first. Only makes sense if all faces overlap.
Definition at line 320 of file OpenSCAD2Dgeom.py.
Referenced by prototype.Node.addtofreecad(), edgestofaces(), and subtractfaces2().
subtractfaces2()
def OpenSCAD2Dgeom.subtractfaces2 (faces)
Sort faces, check if they overlap. Subtract overlapping face and fuse
nonoverlapping groups.
Definition at line 337 of file OpenSCAD2Dgeom.py.
References fusefaces(), and subtractfaces().
Referenced by edgestofaces().
superWireReverse()
def OpenSCAD2Dgeom.superWireReverse (debuglist, closed = False)
superWireReverse(debuglist,[closed]): forces a wire between edges
that don't necessarily have coincident endpoints. If closed=True, wire
will always be closed. debuglist has a tuple for every edge.The first
entry is the edge, the second is the flag 'does not need to be inverted'
Definition at line 370 of file OpenSCAD2Dgeom.py.
References draftgeoutils.edges.findMidpoint().
Referenced by edgestowires().