FreeCAD: Gui::MDIViewPy Class Reference
Gui::MDIViewPy Class Reference
#include <MDIViewPy.h>
Public Member Functions
MDIViewPy (MDIView *mdi)
~MDIViewPy () override
Py::Object repr () override
Printing
Py::Object printView (const Py::Tuple &)
Py::Object printPdf (const Py::Tuple &)
Py::Object printPreview (const Py::Tuple &)
Static Public Member Functions
static void init_type ()
static PyObject * extension_object_new (PyTypeObject *subtype, PyObject *, PyObject *)
static Py::Object type ()
static Py::ExtensionObject< MDIViewPy > create (MDIView *mdi)
Undo/Redo actions
Py::Object undoActions (const Py::Tuple &)
Py::Object redoActions (const Py::Tuple &)
Py::Object sendMessage (const Py::Tuple &)
Py::Object supportMessage (const Py::Tuple &)
Py::Object fitAll (const Py::Tuple &)
Py::Object setActiveObject (const Py::Tuple &)
Py::Object getActiveObject (const Py::Tuple &)
Py::Object cast_to_base (const Py::Tuple &)
MDIView * getMDIViewPtr ()
Detailed Description
Definition at line 55 of file MDIViewPy.h.
Constructor & Destructor Documentation
MDIViewPy()
MDIViewPy::MDIViewPy (MDIView * mdi) explicit
Definition at line 81 of file MDIViewPy.cpp.
Referenced by extension_object_new().
~MDIViewPy()
MDIViewPy::~MDIViewPy () override
Definition at line 86 of file MDIViewPy.cpp.
Member Function Documentation
cast_to_base()
Py::Object MDIViewPy::cast_to_base (const Py::Tuple &)
Definition at line 292 of file MDIViewPy.cpp.
Referenced by init_type().
create()
Py::ExtensionObject< MDIViewPy > MDIViewPy::create (MDIView * mdi) static
Definition at line 72 of file MDIViewPy.cpp.
References type().
Referenced by draftguitools.gui_labels.Label::action(), Gui::View3DInventorPy::cast_to_base(), Gui::AbstractSplitViewPy::cast_to_base(), SpreadsheetGui::SheetViewPy::cast_to_base(), and TechDrawGui::MDIViewPagePy::cast_to_base().
extension_object_new()
PyObject * MDIViewPy::extension_object_new (PyTypeObject * subtype, PyObject * , PyObject *) static
Definition at line 62 of file MDIViewPy.cpp.
References MDIViewPy().
Referenced by init_type().
fitAll()
Py::Object MDIViewPy::fitAll (const Py::Tuple & args)
Definition at line 212 of file MDIViewPy.cpp.
References toolbit-attributes::args, and SCL.SimpleDataTypes::e.
Referenced by init_type().
getActiveObject()
Py::Object MDIViewPy::getActiveObject (const Py::Tuple & args)
Definition at line 257 of file MDIViewPy.cpp.
References toolbit-attributes::args, Base::asBoolean(), App::DocumentObject::getPyObject(), Init::parent, and src.Mod.Test.testmakeWireString::String.
Referenced by init_type().
getMDIViewPtr()
MDIView* Gui::MDIViewPy::getMDIViewPtr () inline
Definition at line 89 of file MDIViewPy.h.
init_type()
void MDIViewPy::init_type () static
Definition at line 36 of file MDIViewPy.cpp.
References cast_to_base(), extension_object_new(), fitAll(), getActiveObject(), printPdf(), printPreview(), printView(), redoActions(), sendMessage(), setActiveObject(), supportMessage(), and undoActions().
Referenced by Gui::Application::Application().
printPdf()
Py::Object MDIViewPy::printPdf (const Py::Tuple & args)
Definition at line 113 of file MDIViewPy.cpp.
References toolbit-attributes::args.
Referenced by init_type().
printPreview()
Py::Object MDIViewPy::printPreview (const Py::Tuple & args)
Definition at line 124 of file MDIViewPy.cpp.
References toolbit-attributes::args.
Referenced by init_type().
printView()
Py::Object MDIViewPy::printView (const Py::Tuple & args)
Definition at line 102 of file MDIViewPy.cpp.
References toolbit-attributes::args.
Referenced by init_type().
redoActions()
Py::Object MDIViewPy::redoActions (const Py::Tuple & args)
Definition at line 150 of file MDIViewPy.cpp.
References toolbit-attributes::args, and src.Mod.Test.testmakeWireString::String.
Referenced by init_type().
repr()
Py::Object MDIViewPy::repr () override
Definition at line 92 of file MDIViewPy.cpp.
References toolbit-attributes::s, and src.Mod.Test.testmakeWireString::String.
sendMessage()
Py::Object MDIViewPy::sendMessage (const Py::Tuple & args)
Definition at line 165 of file MDIViewPy.cpp.
References toolbit-attributes::args, and SCL.SimpleDataTypes::e.
Referenced by init_type().
setActiveObject()
Py::Object MDIViewPy::setActiveObject (const Py::Tuple & args)
Definition at line 233 of file MDIViewPy.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, and Base::PyTypeCheck().
Referenced by init_type().
supportMessage()
Py::Object MDIViewPy::supportMessage (const Py::Tuple & args)
Definition at line 189 of file MDIViewPy.cpp.
References toolbit-attributes::args, and SCL.SimpleDataTypes::e.
Referenced by init_type().
type()
Py::Object MDIViewPy::type () static
Definition at line 67 of file MDIViewPy.cpp.
Referenced by create().
undoActions()
Py::Object MDIViewPy::undoActions (const Py::Tuple & args)
Definition at line 135 of file MDIViewPy.cpp.
References toolbit-attributes::args, and src.Mod.Test.testmakeWireString::String.
Referenced by init_type().
The documentation for this class was generated from the following files:
MDIViewPy.h
MDIViewPy.cpp