FreeCAD: Measure::MeasureDistanceType Class Reference
Measure::MeasureDistanceType Class Reference
#include <MeasureDistance.h>
Public Member Functions
Base::Type getTypeId () const override
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static Base::Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 45 of file MeasureDistance.h.
Member Function Documentation
create()
void * MeasureDistanceType::create () static
Definition at line 434 of file MeasureDistance.cpp.
Referenced by init().
getClassTypeId()
Base::Type MeasureDistanceType::getClassTypeId () static
Definition at line 416 of file MeasureDistance.cpp.
References Base::Type::badType().
getTypeId()
Base::Type MeasureDistanceType::getTypeId () const override virtual
Reimplemented from Base::BaseClass.
Definition at line 421 of file MeasureDistance.cpp.
References Base::Type::badType().
init()
void MeasureDistanceType::init () static
Definition at line 426 of file MeasureDistance.cpp.
References create(), and Base::BaseClass::initSubclass().
Referenced by DocumentObject.DocumentObject::onChanged().
The documentation for this class was generated from the following files:
MeasureDistance.h
MeasureDistance.cpp