FreeCAD: TechDraw::BSpline Class Reference
TechDraw::BSpline Class Reference
#include <Geometry.h>
Public Member Functions
BSpline (const TopoDS_Edge &e)
~BSpline () override=default
double getStartAngle () override
double getEndAngle () override
bool isLine ()
Can this B-spline be represented by a straight line?
bool isCircle ()
TopoDS_Edge asCircle (bool &isArc)
bool intersectsArc (Base::Vector3d p1, Base::Vector3d p2)
Public Member Functions inherited from TechDraw::BaseGeom
BaseGeom ()
virtual ~BaseGeom ()=default
virtual void Save (Base::Writer &w) const
virtual void Restore (Base::XMLReader &r)
std::vector< Base::Vector3d > findEndPoints ()
Base::Vector3d getStartPoint ()
Base::Vector3d getEndPoint ()
Base::Vector3d getMidPoint ()
std::vector< Base::Vector3d > getQuads ()
double minDist (Base::Vector3d p)
Base::Vector3d nearPoint (Base::Vector3d p)
Base::Vector3d nearPoint (const BaseGeomPtr p)
find point on me nearest to p
bool closed ()
virtual BaseGeomPtr copy ()
std::string dump ()
virtual std::string toString () const
std::vector< Base::Vector3d > intersection (TechDraw::BaseGeomPtr geom2)
boost::uuids::uuid getTag () const
virtual std::string getTagAsString () const
std::string geomTypeName ()
BaseGeomPtr inverted ()
GeomType getGeomType ()
void setGeomType (GeomType type)
edgeClass getClassOfEdge ()
void setClassOfEdge (edgeClass newClass)
bool getHlrVisible ()
void setHlrVisible (bool state)
bool getReversed ()
void setReversed (bool state)
int getRef3d ()
void setRef3d (int ref)
TopoDS_Edge getOCCEdge ()
void setOCCEdge (TopoDS_Edge newEdge)
bool getCosmetic ()
void setCosmetic (bool state)
int source ()
void source (int s)
int sourceIndex ()
void sourceIndex (int si)
std::string getCosmeticTag ()
void setCosmeticTag (std::string t)
Part::TopoShape asTopoShape (double scale=1.0)
virtual bool clockwiseAngle ()
virtual void clockwiseAngle (bool direction)
Public Attributes
Base::Vector3d startPnt
Base::Vector3d endPnt
Base::Vector3d midPnt
double startAngle
double endAngle
bool cw
Arc is drawn clockwise from startAngle to endAngle if true, counterclockwise if false.
bool isArc
std::vector< BezierSegment > segments
Additional Inherited Members
Static Public Member Functions inherited from TechDraw::BaseGeom
static BaseGeomPtr baseFactory (TopoDS_Edge edge, bool isCosmetic=false)
Convert 1 OCC edge into 1 BaseGeom (static factory method)
static bool validateEdge (TopoDS_Edge edge)
static TopoDS_Edge completeEdge (const TopoDS_Edge &edge)
Protected Member Functions inherited from TechDraw::BaseGeom
void createNewTag ()
Protected Attributes inherited from TechDraw::BaseGeom
GeomType geomType
ExtractionType extractType
edgeClass classOfEdge
bool hlrVisible
bool reversed
int ref3D
TopoDS_Edge occEdge
bool cosmetic
int m_source
int m_sourceIndex
std::string cosmeticTag
boost::uuids::uuid tag
Detailed Description
Definition at line 289 of file TechDraw/App/Geometry.h.
Constructor & Destructor Documentation
BSpline()
BSpline::BSpline (const TopoDS_Edge & e) explicit
Definition at line 1146 of file TechDraw/App/Geometry.cpp.
References a, KDL::atan2(), TechDraw::BSPLINE, SCL.SimpleDataTypes::c, cw, TechDraw::BezierSegment::degree, SCL.SimpleDataTypes::e, endAngle, endPnt, SCL.SimpleDataTypes::f, TechDraw::BaseGeom::geomType, Handle(), SplineSurface::i, isArc, RobotExample::l, test::m, M_PI, midPnt, TechDraw::BaseGeom::occEdge, TechDraw::BezierSegment::pnts, TechDraw::BezierSegment::poles, TechDraw::BaseGeom::reversed, toolbit-attributes::s, segments, startAngle, startPnt, draftgeoutils.general::v1(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
~BSpline()
TechDraw::BSpline::~BSpline () override default
Member Function Documentation
asCircle()
TopoDS_Edge BSpline::asCircle (bool & isArc)
Definition at line 1236 of file TechDraw/App/Geometry.cpp.
References TechDraw::GeometryUtils::asCircle(), and TechDraw::BaseGeom::occEdge.
getEndAngle()
double TechDraw::BSpline::getEndAngle () inline override virtual
Reimplemented from TechDraw::BaseGeom.
Definition at line 297 of file TechDraw/App/Geometry.h.
getStartAngle()
double TechDraw::BSpline::getStartAngle () inline override virtual
Reimplemented from TechDraw::BaseGeom.
Definition at line 296 of file TechDraw/App/Geometry.h.
intersectsArc()
bool BSpline::intersectsArc (Base::Vector3d p1, Base::Vector3d p2)
Definition at line 1241 of file TechDraw/App/Geometry.cpp.
References TechDraw::BaseGeom::minDist(), TechDraw::BaseGeom::occEdge, draftgeoutils.general::v1(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
isCircle()
bool BSpline::isCircle ()
Definition at line 1230 of file TechDraw/App/Geometry.cpp.
References TechDraw::GeometryUtils::isCircle(), and TechDraw::BaseGeom::occEdge.
isLine()
bool BSpline::isLine ()
Can this B-spline be represented by a straight line?
Definition at line 1224 of file TechDraw/App/Geometry.cpp.
References TechDraw::GeometryUtils::isLine(), and TechDraw::BaseGeom::occEdge.
Member Data Documentation
cw
bool TechDraw::BSpline::cw
Arc is drawn clockwise from startAngle to endAngle if true, counterclockwise if false.
Definition at line 305 of file TechDraw/App/Geometry.h.
Referenced by BSpline().
endAngle
double TechDraw::BSpline::endAngle
Definition at line 303 of file TechDraw/App/Geometry.h.
Referenced by BSpline().
endPnt
Base::Vector3d TechDraw::BSpline::endPnt
Definition at line 300 of file TechDraw/App/Geometry.h.
Referenced by BSpline().
isArc
bool TechDraw::BSpline::isArc
Definition at line 306 of file TechDraw/App/Geometry.h.
Referenced by BSpline().
midPnt
Base::Vector3d TechDraw::BSpline::midPnt
Definition at line 301 of file TechDraw/App/Geometry.h.
Referenced by BSpline().
segments
std::vector<BezierSegment> TechDraw::BSpline::segments
Definition at line 313 of file TechDraw/App/Geometry.h.
Referenced by BSpline().
startAngle
double TechDraw::BSpline::startAngle
Definition at line 302 of file TechDraw/App/Geometry.h.
Referenced by BSpline().
startPnt
Base::Vector3d TechDraw::BSpline::startPnt
Definition at line 299 of file TechDraw/App/Geometry.h.
Referenced by BSpline().
The documentation for this class was generated from the following files:
TechDraw/App/Geometry.h
TechDraw/App/Geometry.cpp