FreeCAD: Gui::ViewProviderGroupExtension Class Reference
Gui::ViewProviderGroupExtension Class Reference
#include <ViewProviderGroupExtension.h>
Public Member Functions
ViewProviderGroupExtension ()
Constructor.
~ViewProviderGroupExtension () override
std::vector< App::DocumentObject * > extensionClaimChildren () const override
bool extensionCanDragObjects () const override
bool extensionCanDragObject (App::DocumentObject *) const override
void extensionDragObject (App::DocumentObject *) override
bool extensionCanDropObjects () const override
bool extensionCanDropObject (App::DocumentObject *) const override
void extensionDropObject (App::DocumentObject *) override
void extensionHide () override
Hides the view provider.
void extensionShow () override
Shows the view provider.
bool extensionOnDelete (const std::vector< std::string > &) override
Public Member Functions inherited from Gui::ViewProviderExtension
ViewProviderExtension ()
~ViewProviderExtension () override
Gui::ViewProviderDocumentObject * getExtendedViewProvider ()
const Gui::ViewProviderDocumentObject * getExtendedViewProvider () const
virtual std::vector< App::DocumentObject * > extensionClaimChildren3D () const
virtual void extensionBeforeDelete ()
virtual bool extensionCanDragAndDropObject (App::DocumentObject *) const
virtual bool extensionCanDropObjectEx (App::DocumentObject *, App::DocumentObject *, const char *, const std::vector< std::string > &) const
virtual std::string extensionDropObjectEx (App::DocumentObject *obj, App::DocumentObject *, const char *, const std::vector< std::string > &)
virtual int extensionReplaceObject (App::DocumentObject *, App::DocumentObject *)
virtual void extensionModeSwitchChange ()
virtual SoSeparator * extensionGetFrontRoot () const
virtual SoGroup * extensionGetChildRoot () const
virtual SoSeparator * extensionGetBackRoot () const
virtual void extensionAttach (App::DocumentObject *)
virtual void extensionReattach (App::DocumentObject *)
virtual void extensionSetDisplayMode (const char *)
virtual std::vector< std::string > extensionGetDisplayModes () const
virtual void extensionSetupContextMenu (QMenu *, QObject *, const char *)
virtual void extensionUpdateData (const App::Property *)
PyObject * getExtensionPyObject () override
void setIgnoreOverlayIcon (bool on)
bool ignoreOverlayIcon () const
virtual QIcon extensionMergeGreyableOverlayIcons (const QIcon &orig) const
virtual QIcon extensionMergeColorfullOverlayIcons (const QIcon &orig) const
virtual void extensionStartRestoring ()
virtual void extensionFinishRestoring ()
virtual bool extensionGetElementPicked (const SoPickedPoint *, std::string &) const
virtual bool extensionGetDetailPath (const char *, SoFullPath *, SoDetail *&) const
Public Member Functions inherited from App::Extension
virtual Base::Type getExtensionTypeId (void) const
Extension ()=default
virtual ~Extension ()
virtual void initExtension (App::ExtensionContainer *obj)
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Additional Inherited Members
Static Public Member Functions inherited from App::Extension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Protected Member Functions inherited from App::Extension
virtual const App::PropertyData & extensionGetPropertyData (void) const
virtual void extensionOnChanged (const Property *p)
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
returns true if the property name change was handled by the extension.
virtual bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
returns true if the property type change was handled by the extension.
void initExtensionType (Base::Type type)
Static Protected Member Functions inherited from App::Extension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Detailed Description
Definition at line 52 of file ViewProviderGroupExtension.h.
Constructor & Destructor Documentation
ViewProviderGroupExtension()
ViewProviderGroupExtension::ViewProviderGroupExtension ()
Constructor.
Definition at line 46 of file ViewProviderGroupExtension.cpp.
References App::Extension::getExtensionClassTypeId().
~ViewProviderGroupExtension()
ViewProviderGroupExtension::~ViewProviderGroupExtension () override default
Member Function Documentation
extensionCanDragObject()
bool ViewProviderGroupExtension::extensionCanDragObject (App::DocumentObject *) const override virtual
Reimplemented from Gui::ViewProviderExtension.
Definition at line 57 of file ViewProviderGroupExtension.cpp.
extensionCanDragObjects()
bool ViewProviderGroupExtension::extensionCanDragObjects () const override virtual
Reimplemented from Gui::ViewProviderExtension.
Definition at line 53 of file ViewProviderGroupExtension.cpp.
extensionCanDropObject()
bool ViewProviderGroupExtension::extensionCanDropObject (App::DocumentObject * obj) const override virtual
Reimplemented from Gui::ViewProviderExtension.
Definition at line 75 of file ViewProviderGroupExtension.cpp.
References Gui::ViewProvider::acceptReorderingObjects(), Base::Console(), DraftVecUtils::find(), Gui::ViewProviderExtension::getExtendedViewProvider(), Gui::ViewProviderDocumentObject::getObject(), App::DocumentObject::getOutList(), toolbit-attributes::group, Base::ConsoleSingleton::Log(), and Base::ConsoleSingleton::Warning().
extensionCanDropObjects()
bool ViewProviderGroupExtension::extensionCanDropObjects () const override virtual
Reimplemented from Gui::ViewProviderExtension.
Definition at line 71 of file ViewProviderGroupExtension.cpp.
extensionClaimChildren()
std::vector< App::DocumentObject * > ViewProviderGroupExtension::extensionClaimChildren () const override virtual
Reimplemented from Gui::ViewProviderExtension.
Reimplemented in Gui::ViewProviderOriginGroupExtension.
Definition at line 115 of file ViewProviderGroupExtension.cpp.
References Gui::ViewProviderExtension::getExtendedViewProvider(), Gui::ViewProviderDocumentObject::getObject(), and toolbit-attributes::group.
extensionDragObject()
void ViewProviderGroupExtension::extensionDragObject (App::DocumentObject * obj) override virtual
Reimplemented from Gui::ViewProviderExtension.
Definition at line 63 of file ViewProviderGroupExtension.cpp.
References Gui::Command::Doc, doCommand, App::DocumentObject::getDocument(), Gui::ViewProviderExtension::getExtendedViewProvider(), App::Document::getName(), App::DocumentObject::getNameInDocument(), and UtilsAssembly::getObject().
extensionDropObject()
void ViewProviderGroupExtension::extensionDropObject (App::DocumentObject * obj) override virtual
Reimplemented from Gui::ViewProviderExtension.
Definition at line 99 of file ViewProviderGroupExtension.cpp.
References Gui::Command::App, toolbit-attributes::doc, doCommand, Gui::ViewProviderExtension::getExtendedViewProvider(), App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), and toolbit-attributes::grp.
extensionHide()
void ViewProviderGroupExtension::extensionHide () override virtual
Hides the view provider.
Reimplemented from Gui::ViewProviderExtension.
Definition at line 150 of file ViewProviderGroupExtension.cpp.
References Gui::ViewProviderExtension::extensionHide(), Gui::ViewProviderExtension::getExtendedViewProvider(), App::ExtensionContainer::getExtensionByType(), Gui::ViewProviderDocumentObject::getObject(), toolbit-attributes::group, Gui::isRestoring, and App::Property::User1.
extensionOnDelete()
bool ViewProviderGroupExtension::extensionOnDelete (const std::vector< std::string > &) override virtual
Reimplemented from Gui::ViewProviderExtension.
Definition at line 174 of file ViewProviderGroupExtension.cpp.
References Gui::Command::Doc, doCommand, Gui::ViewProviderExtension::getExtendedViewProvider(), App::ExtensionContainer::getExtensionByType(), Gui::getMainWindow(), Gui::ViewProviderDocumentObject::getObject(), UtilsAssembly::getObject(), and toolbit-attributes::group.
extensionShow()
void ViewProviderGroupExtension::extensionShow () override virtual
Shows the view provider.
Reimplemented from Gui::ViewProviderExtension.
Definition at line 126 of file ViewProviderGroupExtension.cpp.
References Gui::ViewProviderExtension::extensionShow(), Gui::ViewProviderExtension::getExtendedViewProvider(), App::ExtensionContainer::getExtensionByType(), Gui::ViewProviderDocumentObject::getObject(), toolbit-attributes::group, Gui::isRestoring, and App::Property::User1.
The documentation for this class was generated from the following files:
ViewProviderGroupExtension.h
ViewProviderGroupExtension.cpp