FreeCAD: PersistentToolbarsGui Namespace Reference
PersistentToolbarsGui Namespace Reference
Functions
def pythonToolbars ()
def isConnected (i)
def onRestore (active)
def onSave ()
def onWorkbenchActivated ()
def onStart ()
def onClose ()
Variables
list conectedToolbars = []
timer = QtCore.QTimer()
mw = Gui.getMainWindow()
Function Documentation
isConnected()
def PersistentToolbarsGui.isConnected (i)
Connect toolbar to onSave function.
Definition at line 47 of file PersistentToolbarsGui.py.
Referenced by onRestore().
onClose()
def PersistentToolbarsGui.onClose ()
Remove system provided presets on FreeCAD close.
Definition at line 254 of file PersistentToolbarsGui.py.
onRestore()
def PersistentToolbarsGui.onRestore (active)
Restore current workbench toolbars position.
Definition at line 57 of file PersistentToolbarsGui.py.
References isConnected().
Referenced by onWorkbenchActivated().
onSave()
def PersistentToolbarsGui.onSave ()
Save current workbench toolbars position.
Definition at line 144 of file PersistentToolbarsGui.py.
References MovieTool.x, and MovieTool.y.
Referenced by MRichTextEdit.keyPressEvent().
onStart()
def PersistentToolbarsGui.onStart ()
Start persistent toolbars.
Definition at line 237 of file PersistentToolbarsGui.py.
References onWorkbenchActivated().
onWorkbenchActivated()
def PersistentToolbarsGui.onWorkbenchActivated ()
When workbench gets activated restore toolbar position.
Definition at line 225 of file PersistentToolbarsGui.py.
References onRestore(), and pythonToolbars().
Referenced by onStart().
pythonToolbars()
def PersistentToolbarsGui.pythonToolbars ()
Manage Python based toolbar in BIM workbench.
Definition at line 32 of file PersistentToolbarsGui.py.
Referenced by onWorkbenchActivated().
Variable Documentation
conectedToolbars
list PersistentToolbarsGui.conectedToolbars = []
Definition at line 27 of file PersistentToolbarsGui.py.
mw
PersistentToolbarsGui.mw = Gui.getMainWindow()
Definition at line 29 of file PersistentToolbarsGui.py.
timer
PersistentToolbarsGui.timer = QtCore.QTimer()
Definition at line 28 of file PersistentToolbarsGui.py.
Referenced by CmdSandboxEventLoop.activated(), CmdTestProgress5.activated(), Gui::View3DInventorViewer.animatedViewAll(), Gui::Dialog::DlgCustomKeyboardImp.DlgCustomKeyboardImp(), Gui::OverlaySplitterHandle.enterEvent(), Gui::OverlayProxyWidget.enterEvent(), Gui::PropertyView.hideEvent(), Gui::Dialog::DlgCustomKeyboardImp.initCommandList(), Gui::Dialog::DlgCustomKeyboardImp.initCommandWidgets(), Gui::PropertyView.PropertyView(), Gui::PropertyView.showEvent(), and Gui::StatusWidget.showText().