FreeCAD: Base::ProgressIndicatorPy Class Reference
Base::ProgressIndicatorPy Class Reference
#include <ProgressIndicatorPy.h>
Public Member Functions
ProgressIndicatorPy ()
~ProgressIndicatorPy () override
Py::Object repr () override
Py::Object start (const Py::Tuple &)
Py::Object next (const Py::Tuple &)
Py::Object stop (const Py::Tuple &)
Static Public Member Functions
static void init_type ()
static Py::PythonType & behaviors ()
static PyTypeObject * type_object ()
static bool check (PyObject *py)
Detailed Description
Definition at line 54 of file ProgressIndicatorPy.h.
Constructor & Destructor Documentation
ProgressIndicatorPy()
ProgressIndicatorPy::ProgressIndicatorPy () default
~ProgressIndicatorPy()
ProgressIndicatorPy::~ProgressIndicatorPy () override default
Member Function Documentation
behaviors()
Py::PythonType & ProgressIndicatorPy::behaviors () static
Definition at line 46 of file ProgressIndicatorPy.cpp.
Referenced by init_type().
check()
bool ProgressIndicatorPy::check (PyObject * py) static
Definition at line 56 of file ProgressIndicatorPy.cpp.
References ArchCommands::check().
init_type()
void ProgressIndicatorPy::init_type () static
Definition at line 31 of file ProgressIndicatorPy.cpp.
References behaviors(), next(), start(), and stop().
next()
Py::Object ProgressIndicatorPy::next (const Py::Tuple & args)
Definition at line 90 of file ProgressIndicatorPy.cpp.
References toolbit-attributes::args, and SCL.SimpleDataTypes::b.
Referenced by init_type().
repr()
Py::Object ProgressIndicatorPy::repr () override
Definition at line 71 of file ProgressIndicatorPy.cpp.
References toolbit-attributes::s, and src.Mod.Test.testmakeWireString::String.
start()
Py::Object ProgressIndicatorPy::start (const Py::Tuple & args)
Definition at line 77 of file ProgressIndicatorPy.cpp.
References toolbit-attributes::args.
Referenced by init_type().
stop()
Py::Object ProgressIndicatorPy::stop (const Py::Tuple & args)
Definition at line 108 of file ProgressIndicatorPy.cpp.
References toolbit-attributes::args.
Referenced by bimcommands.BimPanel.NestTaskPanel::accept(), init_type(), and bimcommands.BimPanel.NestTaskPanel::reject().
type_object()
PyTypeObject * ProgressIndicatorPy::type_object () static
Definition at line 51 of file ProgressIndicatorPy.cpp.
The documentation for this class was generated from the following files:
ProgressIndicatorPy.h
ProgressIndicatorPy.cpp