FreeCAD: TechDrawGui::TaskComplexSection Class Reference
TechDrawGui::TaskComplexSection Class Reference
#include <TaskComplexSection.h>
Public Member Functions
TaskComplexSection (TechDraw::DrawPage *page, TechDraw::DrawViewPart *baseView, std::vector< App::DocumentObject * > shapes, std::vector< App::DocumentObject * > xShapes, App::DocumentObject *profileObject, std::vector< std::string > profileSubs)
TaskComplexSection (TechDraw::DrawComplexSection *complexSection)
~TaskComplexSection () override=default
virtual bool accept ()
virtual bool reject ()
Protected Slots
void onSectionObjectsUseSelectionClicked ()
void onProfileObjectsUseSelectionClicked ()
void onUpClicked ()
void onDownClicked ()
void onLeftClicked ()
void onRightClicked ()
void onIdentifierChanged ()
void onScaleChanged ()
void scaleTypeChanged (int index)
void liveUpdateClicked ()
void updateNowClicked ()
void slotChangeAngle (double newAngle)
void slotViewDirectionChanged (Base::Vector3d newDirection)
Protected Member Functions
void changeEvent (QEvent *event) override
void saveSectionState ()
void restoreSectionState ()
bool apply (bool forceUpdate=false)
void applyQuick (std::string dir)
void applyAligned ()
void setUiPrimary ()
void setUiEdit ()
void setUiCommon ()
void checkAll (bool check)
void enableAll (bool enable)
void failNoObject ()
bool isBaseValid ()
bool isSectionValid ()
void updateUi ()
Detailed Description
Definition at line 54 of file TaskComplexSection.h.
Constructor & Destructor Documentation
TaskComplexSection() [1/2]
TaskComplexSection::TaskComplexSection (TechDraw::DrawPage * page, TechDraw::DrawViewPart * baseView, std::vector< App::DocumentObject * > shapes, std::vector< App::DocumentObject * > xShapes, App::DocumentObject * profileObject, std::vector< std::string > profileSubs)
Definition at line 58 of file TaskComplexSection.cpp.
References App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), saveSectionState(), and setUiPrimary().
TaskComplexSection() [2/2]
TaskComplexSection::TaskComplexSection (TechDraw::DrawComplexSection * complexSection)
Definition at line 97 of file TaskComplexSection.cpp.
References TechDraw::DrawViewSection::BaseView, TechDraw::DrawComplexSection::CuttingToolWireObject, TechDraw::DrawView::findParentPage(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::PropertyLink::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyXLinkSubList::getValues(), saveSectionState(), setUiEdit(), TechDraw::DrawViewPart::Source, and TechDraw::DrawViewPart::XSource.
~TaskComplexSection()
TechDrawGui::TaskComplexSection::~TaskComplexSection () override default
Member Function Documentation
accept()
bool TaskComplexSection::accept () virtual
Definition at line 757 of file TaskComplexSection.cpp.
References apply(), doCommand, and Gui::Command::Gui.
Referenced by TechDrawGui::TaskDlgComplexSection::accept().
apply()
bool TaskComplexSection::apply (bool forceUpdate = false) protected
Definition at line 479 of file TaskComplexSection.cpp.
References checkAll(), Base::Console(), enableAll(), Base::ConsoleSingleton::Error(), failNoObject(), isBaseValid(), isSectionValid(), TechDraw::DrawViewPart::localVectorToCS(), Arch::QT_TRANSLATE_NOOP, App::DocumentObject::recomputeFeature(), TechDraw::DrawView::requestPaint(), Gui::WaitCursor::restoreCursor(), and TechDrawGui::VectorEditWidget::value().
Referenced by accept(), applyAligned(), liveUpdateClicked(), onIdentifierChanged(), onScaleChanged(), and updateNowClicked().
applyAligned()
void TaskComplexSection::applyAligned () protected
Definition at line 541 of file TaskComplexSection.cpp.
References apply(), and enableAll().
Referenced by onDownClicked(), onLeftClicked(), onRightClicked(), onUpClicked(), slotChangeAngle(), and slotViewDirectionChanged().
applyQuick()
void TechDrawGui::TaskComplexSection::applyQuick (std::string dir) protected
changeEvent()
void TaskComplexSection::changeEvent (QEvent * event) override protected
Definition at line 804 of file TaskComplexSection.cpp.
checkAll()
void TaskComplexSection::checkAll (bool check) protected
Definition at line 420 of file TaskComplexSection.cpp.
References ArchCommands::check().
Referenced by apply(), onDownClicked(), onIdentifierChanged(), onLeftClicked(), onRightClicked(), onScaleChanged(), onUpClicked(), slotChangeAngle(), and slotViewDirectionChanged().
enableAll()
void TaskComplexSection::enableAll (bool enable) protected
Definition at line 428 of file TaskComplexSection.cpp.
Referenced by apply(), and applyAligned().
failNoObject()
void TaskComplexSection::failNoObject () protected
Definition at line 710 of file TaskComplexSection.cpp.
References Gui::ControlSingleton::closeDialog(), Gui::Control(), Gui::getMainWindow(), and Path.Op.Surface::msg.
Referenced by apply().
isBaseValid()
bool TaskComplexSection::isBaseValid () protected
Definition at line 719 of file TaskComplexSection.cpp.
References App::Document::getObject().
Referenced by apply(), and reject().
isSectionValid()
bool TaskComplexSection::isSectionValid () protected
Definition at line 731 of file TaskComplexSection.cpp.
References App::Document::getObject().
Referenced by apply(), and reject().
liveUpdateClicked
void TaskComplexSection::liveUpdateClicked () protected slot
Definition at line 443 of file TaskComplexSection.cpp.
References apply().
Referenced by setUiCommon().
onDownClicked
void TaskComplexSection::onDownClicked () protected slot
Definition at line 338 of file TaskComplexSection.cpp.
References applyAligned(), checkAll(), TechDrawGui::CompassWidget::setToSouth(), and TechDrawGui::VectorEditWidget::setValueNoNotify().
Referenced by setUiCommon().
onIdentifierChanged
void TaskComplexSection::onIdentifierChanged () protected slot
Definition at line 365 of file TaskComplexSection.cpp.
References apply(), and checkAll().
onLeftClicked
void TaskComplexSection::onLeftClicked () protected slot
Definition at line 347 of file TaskComplexSection.cpp.
References applyAligned(), checkAll(), TechDrawGui::CompassWidget::setToWest(), and TechDrawGui::VectorEditWidget::setValueNoNotify().
Referenced by setUiCommon().
onProfileObjectsUseSelectionClicked
void TaskComplexSection::onProfileObjectsUseSelectionClicked () protected slot
Definition at line 378 of file TaskComplexSection.cpp.
References App::DocumentObject::getNameInDocument(), Gui::SelectionSingleton::getSelectionEx(), App::PropertyString::getValue(), App::DocumentObject::Label, Path.Dressup.Utils::selection(), and Gui::Selection().
Referenced by setUiCommon().
onRightClicked
void TaskComplexSection::onRightClicked () protected slot
Definition at line 356 of file TaskComplexSection.cpp.
References applyAligned(), checkAll(), TechDrawGui::CompassWidget::setToEast(), and TechDrawGui::VectorEditWidget::setValueNoNotify().
Referenced by setUiCommon().
onScaleChanged
void TaskComplexSection::onScaleChanged () protected slot
Definition at line 371 of file TaskComplexSection.cpp.
References apply(), and checkAll().
onSectionObjectsUseSelectionClicked
void TaskComplexSection::onSectionObjectsUseSelectionClicked () protected slot
Definition at line 279 of file TaskComplexSection.cpp.
References Base::Persistence::getClassTypeId(), Gui::SelectionSingleton::getSelectionEx(), Path.Dressup.Utils::selection(), and Gui::Selection().
Referenced by setUiCommon().
onUpClicked
void TaskComplexSection::onUpClicked () protected slot
Definition at line 329 of file TaskComplexSection.cpp.
References applyAligned(), checkAll(), TechDrawGui::CompassWidget::setToNorth(), and TechDrawGui::VectorEditWidget::setValueNoNotify().
Referenced by setUiCommon().
reject()
bool TaskComplexSection::reject () virtual
Definition at line 765 of file TaskComplexSection.cpp.
References doCommand, App::DocumentObject::getNameInDocument(), Gui::Command::Gui, isBaseValid(), isSectionValid(), App::DocumentObject::recomputeFeature(), TechDraw::DrawView::requestPaint(), restoreSectionState(), and Gui::Command::updateActive().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and TechDrawGui::TaskDlgComplexSection::reject().
restoreSectionState()
void TaskComplexSection::restoreSectionState () protected
Definition at line 263 of file TaskComplexSection.cpp.
References TechDraw::DrawViewPart::Direction, TechDraw::DrawView::Scale, TechDraw::DrawView::ScaleType, TechDraw::DrawViewSection::SectionDirection, TechDraw::DrawViewSection::SectionNormal, TechDraw::DrawViewSection::SectionOrigin, TechDraw::DrawViewSection::SectionSymbol, App::PropertyVector::setValue(), App::PropertyEnumeration::setValue(), App::PropertyFloat::setValue(), App::PropertyString::setValue(), and TechDraw::DrawViewPart::XDirection.
Referenced by reject().
saveSectionState()
void TaskComplexSection::saveSectionState () protected
Definition at line 242 of file TaskComplexSection.cpp.
References TechDraw::DrawViewPart::Direction, TechDraw::DrawView::getScale(), TechDraw::DrawView::getScaleType(), App::PropertyVector::getValue(), App::PropertyString::getValue(), App::PropertyEnumeration::getValueAsString(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyXLinkSubList::getValues(), TechDraw::DrawViewSection::SectionDirection, TechDraw::DrawViewSection::SectionNormal, TechDraw::DrawViewSection::SectionOrigin, TechDraw::DrawViewSection::SectionSymbol, TechDraw::DrawViewPart::Source, TechDraw::DrawViewPart::XDirection, and TechDraw::DrawViewPart::XSource.
Referenced by TaskComplexSection().
scaleTypeChanged
void TaskComplexSection::scaleTypeChanged (int index) protected slot
Definition at line 390 of file TaskComplexSection.cpp.
References TechDraw::DrawView::autoScale(), TechDraw::DrawView::findParentPage(), App::PropertyFloat::getValue(), TechDraw::DrawView::Scale, and TechDraw::DrawPage::Scale.
setUiCommon()
void TaskComplexSection::setUiCommon () protected
Definition at line 204 of file TaskComplexSection.cpp.
References TechDrawGui::CompassWidget::angleChanged(), draftgeoutils.intersections::connect(), App::DocumentObject::getNameInDocument(), App::PropertyString::getValue(), App::DocumentObject::Label, liveUpdateClicked(), onDownClicked(), onLeftClicked(), onProfileObjectsUseSelectionClicked(), onRightClicked(), onSectionObjectsUseSelectionClicked(), onUpClicked(), TechDrawGui::VectorEditWidget::setLabel(), slotChangeAngle(), slotViewDirectionChanged(), updateNowClicked(), and TechDrawGui::VectorEditWidget::valueChanged().
Referenced by setUiEdit(), and setUiPrimary().
setUiEdit()
void TaskComplexSection::setUiEdit () protected
Definition at line 176 of file TaskComplexSection.cpp.
References KDL::atan2(), App::DocumentObject::getNameInDocument(), TechDraw::DrawView::getScaleType(), App::PropertyVector::getValue(), App::PropertyEnumeration::getValue(), App::PropertyFloat::getValue(), App::PropertyString::getValue(), M_PI, TechDraw::DrawComplexSection::ProjectionStrategy, TechDraw::DrawViewPart::projectPoint(), TechDraw::DrawView::Scale, TechDraw::DrawViewSection::SectionNormal, TechDraw::DrawViewSection::SectionSymbol, TechDrawGui::CompassWidget::setDialAngle(), setUiCommon(), TechDrawGui::VectorEditWidget::setValue(), TechDrawGui::VectorEditWidget::setValueNoNotify(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by TaskComplexSection().
setUiPrimary()
void TaskComplexSection::setUiPrimary () protected
Definition at line 135 of file TaskComplexSection.cpp.
References TechDrawGui::DrawGuiUtil::get3DDirAndRot(), App::DocumentObject::getNameInDocument(), TechDraw::DrawView::getScale(), TechDraw::DrawView::getScaleType(), draftfunctions.scale::scale(), TechDrawGui::CompassWidget::setDialAngle(), setUiCommon(), TechDrawGui::VectorEditWidget::setValue(), and TechDrawGui::VectorEditWidget::setValueNoNotify().
Referenced by TaskComplexSection().
slotChangeAngle
void TaskComplexSection::slotChangeAngle (double newAngle) protected slot
Definition at line 317 of file TaskComplexSection.cpp.
References applyAligned(), checkAll(), KDL::cos(), M_PI, TechDrawGui::VectorEditWidget::setValueNoNotify(), and KDL::sin().
Referenced by setUiCommon().
slotViewDirectionChanged
void TaskComplexSection::slotViewDirectionChanged (Base::Vector3d newDirection) protected slot
Definition at line 300 of file TaskComplexSection.cpp.
References applyAligned(), KDL::atan2(), checkAll(), M_PI, Base::Vector3< float_type >::Normalize(), TechDraw::DrawViewPart::projectPoint(), TechDrawGui::CompassWidget::setDialAngle(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by setUiCommon().
updateNowClicked
void TaskComplexSection::updateNowClicked () protected slot
Definition at line 445 of file TaskComplexSection.cpp.
References apply().
Referenced by setUiCommon().
updateUi()
void TechDrawGui::TaskComplexSection::updateUi () protected
The documentation for this class was generated from the following files:
TaskComplexSection.h
TaskComplexSection.cpp