FreeCAD: Path.Post.scripts.opensbp_pre Namespace Reference
Path.Post.scripts.opensbp_pre Namespace Reference
Functions
def open (filename)
def insert (filename, docname)
def parse (inputstring)
Variables
AXIS
SPEEDS
Function Documentation
insert()
def Path.Post.scripts.opensbp_pre.insert (filename, docname)
called when freecad imports a file
This insert expects parse to return a list of strings
each string will become a separate path
Definition at line 74 of file opensbp_pre.py.
References Path.Post.scripts.opensbp_pre.parse().
Referenced by Path.Post.scripts.opensbp_pre.open().
open()
def Path.Post.scripts.opensbp_pre.open (filename)
Definition at line 67 of file opensbp_pre.py.
References Path.Post.scripts.opensbp_pre.insert().
parse()
def Path.Post.scripts.opensbp_pre.parse (inputstring)
Definition at line 89 of file opensbp_pre.py.
References KDL.abs(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.opensbp_pre.insert().
Variable Documentation
AXIS
Path.Post.scripts.opensbp_pre.AXIS
Definition at line 57 of file opensbp_pre.py.
SPEEDS
Path.Post.scripts.opensbp_pre.SPEEDS
Definition at line 64 of file opensbp_pre.py.