FreeCAD: FemGui::TaskPostContours Class Reference
FemGui::TaskPostContours Class Reference
#include <TaskPostBoxes.h>
Public Member Functions
TaskPostContours (ViewProviderFemPostContours *view, QWidget *parent=nullptr)
~TaskPostContours () override
void applyPythonCode () override
Public Member Functions inherited from FemGui::TaskPostBox
TaskPostBox (Gui::ViewProviderDocumentObject *view, const QPixmap &icon, const QString &title, QWidget *parent=nullptr)
~TaskPostBox () override
virtual bool isGuiTaskOnly ()
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Member Functions inherited from FemGui::TaskPostBox
App::DocumentObject * getObject () const
template<class T >
T * getObject () const
template<typename T >
T * getTypedObject () const
Gui::ViewProviderDocumentObject * getView () const
template<typename T >
T * getTypedView () const
App::Document * getDocument () const
bool autoApply ()
void recompute ()
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Static Protected Member Functions inherited from FemGui::TaskPostBox
static void updateEnumerationList (App::PropertyEnumeration &, QComboBox *box)
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
Definition at line 400 of file TaskPostBoxes.h.
Constructor & Destructor Documentation
TaskPostContours()
TaskPostContours::TaskPostContours (ViewProviderFemPostContours * view, QWidget * parent = nullptr) explicit
Definition at line 1427 of file TaskPostBoxes.cpp.
References draftgeoutils.intersections::connect(), create_qrc::ext, QSint::ActionGroup::groupLayout(), and FemGui::TaskPostBox::updateEnumerationList().
~TaskPostContours()
TaskPostContours::~TaskPostContours () override default
Member Function Documentation
applyPythonCode()
void TaskPostContours::applyPythonCode () override virtual
Implements FemGui::TaskPostBox.
Definition at line 1482 of file TaskPostBoxes.cpp.
The documentation for this class was generated from the following files:
TaskPostBoxes.h
TaskPostBoxes.cpp