FreeCAD: SketcherTests.TestSketchFillet Namespace Reference
SketcherTests.TestSketchFillet Namespace Reference
Classes
class TestSketchFillet
Functions
def VShape (SketchFeature)
def BoxCircle (SketchFeature)
def PointOnObject (SketchFeature)
Variables
App = FreeCAD
Function Documentation
BoxCircle()
def SketcherTests.TestSketchFillet.BoxCircle (SketchFeature)
Definition at line 43 of file TestSketchFillet.py.
References SketcherTests.TestSketcherSolver.CreateRectangleSketch().
Referenced by SketcherTests.TestSketchFillet.TestSketchFillet.testCoincident().
PointOnObject()
def SketcherTests.TestSketchFillet.PointOnObject (SketchFeature)
Definition at line 60 of file TestSketchFillet.py.
References SketcherTests.TestSketcherSolver.CreateRectangleSketch().
Referenced by SketcherTests.TestSketchFillet.TestSketchFillet.testPointOnObject().
VShape()
def SketcherTests.TestSketchFillet.VShape (SketchFeature)
Definition at line 30 of file TestSketchFillet.py.
Referenced by SketcherTests.TestSketchFillet.TestSketchFillet.testOriginalCorner().
Variable Documentation
App
SketcherTests.TestSketchFillet.App = FreeCAD
Definition at line 27 of file TestSketchFillet.py.