FreeCAD: Gui::DocumentModelIndex Class Reference
Gui::DocumentModelIndex Class Reference
Public Member Functions
~DocumentModelIndex () override
void setParent (DocumentModelIndex *parent)
DocumentModelIndex * parent () const
void appendChild (DocumentModelIndex *child)
void removeChild (int row)
QList< DocumentModelIndex * > removeAll ()
DocumentModelIndex * child (int row)
int row () const
int childCount () const
virtual QVariant data (int role) const
virtual bool setData (const QVariant &value, int role)
virtual Qt::ItemFlags flags () const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
void reset ()
DocumentModelIndex ()=default
Protected Attributes
DocumentModelIndex * parentItem {nullptr}
QList< DocumentModelIndex * > childItems
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 49 of file DocumentModel.cpp.
Constructor & Destructor Documentation
~DocumentModelIndex()
Gui::DocumentModelIndex::~DocumentModelIndex () inline override
Definition at line 54 of file DocumentModel.cpp.
References childItems.
DocumentModelIndex()
Gui::DocumentModelIndex::DocumentModelIndex () protected default
Member Function Documentation
appendChild()
void Gui::DocumentModelIndex::appendChild (DocumentModelIndex * child) inline
Definition at line 61 of file DocumentModel.cpp.
References child(), childItems, and setParent().
child()
DocumentModelIndex* Gui::DocumentModelIndex::child (int row) inline
Definition at line 71 of file DocumentModel.cpp.
References childItems, and row().
Referenced by appendChild(), and Gui::ApplicationIndex::findChild().
childCount()
int Gui::DocumentModelIndex::childCount () const inline
Definition at line 80 of file DocumentModel.cpp.
References childItems.
Referenced by Gui::DocumentModel::rowCount().
data()
virtual QVariant Gui::DocumentModelIndex::data (int role) const inline virtual
Reimplemented in Gui::ViewProviderIndex, Gui::DocumentIndex, and Gui::ApplicationIndex.
Definition at line 82 of file DocumentModel.cpp.
flags()
virtual Qt::ItemFlags Gui::DocumentModelIndex::flags () const inline virtual
Reimplemented in Gui::ApplicationIndex.
Definition at line 96 of file DocumentModel.cpp.
parent()
DocumentModelIndex* Gui::DocumentModelIndex::parent () const inline
Definition at line 59 of file DocumentModel.cpp.
References parentItem.
Referenced by Gui::DocumentModel::parent(), and setParent().
removeAll()
QList<DocumentModelIndex*> Gui::DocumentModelIndex::removeAll () inline
Definition at line 65 of file DocumentModel.cpp.
References childItems.
removeChild()
void Gui::DocumentModelIndex::removeChild (int row) inline
Definition at line 63 of file DocumentModel.cpp.
References childItems, and row().
reset()
void Gui::DocumentModelIndex::reset () inline protected
Definition at line 102 of file DocumentModel.cpp.
References childItems.
Referenced by ArchVRM.Renderer::__init__(), draftguitools.gui_trackers.gridTracker::set(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testAll(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
row()
int Gui::DocumentModelIndex::row () const inline
Definition at line 73 of file DocumentModel.cpp.
References childItems, and parentItem.
Referenced by child(), and removeChild().
setData()
virtual bool Gui::DocumentModelIndex::setData (const QVariant & value, int role) inline virtual
Definition at line 87 of file DocumentModel.cpp.
setParent()
void Gui::DocumentModelIndex::setParent (DocumentModelIndex * parent) inline
Definition at line 57 of file DocumentModel.cpp.
References parent(), and parentItem.
Referenced by appendChild().
Member Data Documentation
childItems
QList<DocumentModelIndex*> Gui::DocumentModelIndex::childItems protected
Definition at line 108 of file DocumentModel.cpp.
Referenced by appendChild(), child(), childCount(), Gui::ViewProviderIndex::clone(), Gui::ApplicationIndex::findChild(), Gui::DocumentIndex::findViewProviders(), Gui::ViewProviderIndex::findViewProviders(), removeAll(), removeChild(), reset(), row(), Gui::DocumentIndex::rowOfViewProvider(), Gui::DocumentIndex::~DocumentIndex(), and ~DocumentModelIndex().
parentItem
DocumentModelIndex* Gui::DocumentModelIndex::parentItem {nullptr} protected
Definition at line 107 of file DocumentModel.cpp.
Referenced by parent(), row(), and setParent().
The documentation for this class was generated from the following file:
DocumentModel.cpp