FreeCAD: Base::InventorBuilder Class Reference
Base::InventorBuilder Class Reference
#include <Builder3D.h>
Public Member Functions
InventorBuilder (std::ostream &str)
Construction of an InventorBuilder instance.
void addHeader ()
Adds the OpenInventor header.
virtual ~InventorBuilder ()
Destruction of an InventorBuilder instance.
void addNode (const NodeItem &)
addNode Writes the content of the added node to the output stream.
void beginSeparator ()
Sets a separator node.
void endSeparator ()
Closes the last added separator node.
InventorBuilder (const InventorBuilder &)=delete
InventorBuilder (InventorBuilder &&)=delete
void operator= (const InventorBuilder &)=delete
void operator= (InventorBuilder &&)=delete
Detailed Description
This class does basically the same as Builder3D except that it writes the data directly into a given stream without buffering the output data in a string stream. Compared to file streams, string streams are quite slow when writing data with more than a few hundred lines. Due to performance reasons the user should use a file stream in this case.
Author
Werner Mayer
Definition at line 676 of file Builder3D.h.
Constructor & Destructor Documentation
InventorBuilder() [1/3]
InventorBuilder::InventorBuilder (std::ostream & str) explicit
Construction of an InventorBuilder instance.
Parameters
str - stream to write the content into
Definition at line 942 of file Builder3D.cpp.
References addHeader().
~InventorBuilder()
InventorBuilder::~InventorBuilder () virtual default
Destruction of an InventorBuilder instance.
InventorBuilder() [2/3]
Base::InventorBuilder::InventorBuilder (const InventorBuilder &) delete
InventorBuilder() [3/3]
Base::InventorBuilder::InventorBuilder (InventorBuilder &&) delete
Member Function Documentation
addHeader()
void InventorBuilder::addHeader ()
Adds the OpenInventor header.
Definition at line 950 of file Builder3D.cpp.
Referenced by InventorBuilder().
addNode()
void InventorBuilder::addNode (const NodeItem & node)
addNode Writes the content of the added node to the output stream.
Definition at line 965 of file Builder3D.cpp.
References Base::NodeItem::write().
Referenced by WriterInventorImp::addCoordinateNode(), WriterInventorImp::addIndexedFaceSetNode(), WriterInventorImp::addInfoNode(), WriterInventorImp::addLabel(), WriterInventorImp::addMaterialBindingNode(), Base::Builder3D::addNode(), WriterInventorImp::addNormalNode(), WriterInventorImp::addTransformNode(), Part::TopoShape::exportFaceSet(), Part::TopoShape::exportLineSet(), and Mesh::MeshObject::writeInventor().
beginSeparator()
void InventorBuilder::beginSeparator ()
Sets a separator node.
Definition at line 971 of file Builder3D.cpp.
Referenced by Base::Builder3D::beginSeparator(), Part::TopoShape::exportFaceSet(), Part::TopoShape::exportLineSet(), MeshCore::WriterInventor::Save(), and Mesh::MeshObject::writeInventor().
endSeparator()
void InventorBuilder::endSeparator ()
Closes the last added separator node.
Definition at line 977 of file Builder3D.cpp.
Referenced by Base::Builder3D::endSeparator(), Part::TopoShape::exportFaceSet(), Part::TopoShape::exportLineSet(), MeshCore::WriterInventor::Save(), and Mesh::MeshObject::writeInventor().
operator=() [1/2]
void Base::InventorBuilder::operator= (const InventorBuilder &) delete
operator=() [2/2]
void Base::InventorBuilder::operator= (InventorBuilder &&) delete
The documentation for this class was generated from the following files:
Builder3D.h
Builder3D.cpp