FreeCAD: ReenGui::FitBSplineSurfaceWidget Class Reference
ReenGui::FitBSplineSurfaceWidget Class Reference
#include <FitBSplineSurface.h>
Classes
class Private
Public Member Functions
FitBSplineSurfaceWidget (const App::DocumentObjectT &, QWidget *parent=nullptr)
~FitBSplineSurfaceWidget () override
bool accept ()
Detailed Description
Definition at line 53 of file FitBSplineSurface.h.
Constructor & Destructor Documentation
FitBSplineSurfaceWidget()
FitBSplineSurfaceWidget::FitBSplineSurfaceWidget (const App::DocumentObjectT & obj, QWidget * parent = nullptr) explicit
Definition at line 57 of file FitBSplineSurface.cpp.
References draftgeoutils.intersections::connect(), ReenGui::FitBSplineSurfaceWidget::Private::obj, Init::parent, and ReenGui::FitBSplineSurfaceWidget::Private::ui.
~FitBSplineSurfaceWidget()
FitBSplineSurfaceWidget::~FitBSplineSurfaceWidget () override
Definition at line 70 of file FitBSplineSurface.cpp.
Member Function Documentation
accept()
bool FitBSplineSurfaceWidget::accept ()
Definition at line 169 of file FitBSplineSurface.cpp.
References Gui::Command::abortCommand(), Gui::Command::addModule(), Gui::Command::App, Gui::Command::commitCommand(), Gui::Command::Doc, SCL.SimpleDataTypes::e, App::DocumentObjectT::getDocumentPython(), App::DocumentObjectT::getObjectPython(), Gui::SelectionSingleton::getObjectsOfType(), Base::Rotation::multVec(), ReenGui::FitBSplineSurfaceWidget::Private::obj, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, runCommand, Path.Dressup.Utils::selection(), Gui::Selection(), buildPsets::u, ReenGui::FitBSplineSurfaceWidget::Private::ui, Gui::Command::updateActive(), TestSpreadsheet::v, and Path.Log::warning().
Referenced by ReenGui::TaskFitBSplineSurface::accept().
The documentation for this class was generated from the following files:
FitBSplineSurface.h
FitBSplineSurface.cpp