FreeCAD: MeshPartGui::CurveOnMeshHandler::Private Class Reference
MeshPartGui::CurveOnMeshHandler::Private Class Reference
Classes
struct ApproxPar
struct PickedPoint
Public Member Functions
Private ()
~Private ()
std::vector< SbVec3f > convert (const std::vector< Base::Vector3f > &points) const
void createGrid ()
bool projectLineOnMesh (const PickedPoint &pick)
Static Public Member Functions
static void vertexCallback (void *ud, SoEventCallback *n)
Public Attributes
std::vector< PickedPoint > pickedPoints
std::list< std::vector< Base::Vector3f > > cutLines
bool wireClosed {false}
double distance {1}
double cosAngle {0.7071}
bool approximate {true}
ViewProviderCurveOnMesh * curve
Gui::ViewProviderDocumentObject * mesh {0}
MeshCore::MeshFacetGrid * grid {nullptr}
MeshCore::MeshKernel kernel
QPointer< Gui::View3DInventor > viewer
QCursor editcursor
ApproxPar par
Detailed Description
Definition at line 216 of file CurveOnMesh.cpp.
Constructor & Destructor Documentation
Private()
MeshPartGui::CurveOnMeshHandler::Private::Private () inline
Definition at line 245 of file CurveOnMesh.cpp.
~Private()
MeshPartGui::CurveOnMeshHandler::Private::~Private () inline
Definition at line 249 of file CurveOnMesh.cpp.
References MeshPartGui::CurveOnMeshHandler::Private::curve, and MeshPartGui::CurveOnMeshHandler::Private::grid.
Member Function Documentation
convert()
std::vector<SbVec3f> MeshPartGui::CurveOnMeshHandler::Private::convert (const std::vector< Base::Vector3f > & points) const inline
Definition at line 255 of file CurveOnMesh.cpp.
createGrid()
void MeshPartGui::CurveOnMeshHandler::Private::createGrid () inline
Definition at line 264 of file CurveOnMesh.cpp.
References SCL.SimpleDataTypes::f, MeshCore::MeshAlgorithm::GetAverageEdgeLength(), Gui::ViewProviderDocumentObject::getObject(), Mesh::PropertyMeshKernel::getValue(), MeshPartGui::CurveOnMeshHandler::Private::grid, MeshPartGui::CurveOnMeshHandler::Private::kernel, Mesh::Feature::Mesh, MeshPartGui::CurveOnMeshHandler::Private::mesh, and MeshCore::MeshKernel::Transform().
projectLineOnMesh()
bool MeshPartGui::CurveOnMeshHandler::Private::projectLineOnMesh (const PickedPoint & pick) inline
Definition at line 275 of file CurveOnMesh.cpp.
References MeshPartGui::CurveOnMeshHandler::Private::cosAngle, MeshPartGui::CurveOnMeshHandler::Private::cutLines, SCL.SimpleDataTypes::f, MeshPartGui::CurveOnMeshHandler::Private::PickedPoint::facet, MeshPartGui::CurveOnMeshHandler::Private::grid, MeshPartGui::CurveOnMeshHandler::Private::kernel, MeshPartGui::CurveOnMeshHandler::Private::pickedPoints, MeshPartGui::CurveOnMeshHandler::Private::PickedPoint::point, MeshCore::MeshProjection::projectLineOnMesh(), draftgeoutils.general::v1(), CAMTests.TestPathVoronoi::vd, and MeshPartGui::CurveOnMeshHandler::Private::viewer.
vertexCallback()
void MeshPartGui::CurveOnMeshHandler::Private::vertexCallback (void * ud, SoEventCallback * n) static
Definition at line 596 of file CurveOnMesh.cpp.
References MeshPartGui::CurveOnMeshHandler::Private::PickedPoint::facet, Gui::ViewProvider::getDetail(), Gui::getMainWindow(), Gui::View3DInventorViewer::getPickedPoint(), Gui::View3DInventorViewer::getViewProviderByPathFromTail(), Base::BaseClass::isDerivedFrom(), MeshPartGui::CurveOnMeshHandler::Private::mesh, MeshPartGui::CurveOnMeshHandler::Private::PickedPoint::normal, buildPsets::p, MeshPartGui::CurveOnMeshHandler::Private::PickedPoint::point, and Gui::MainWindow::showMessage().
Referenced by MeshPartGui::CurveOnMeshHandler::disableCallback(), and MeshPartGui::CurveOnMeshHandler::enableCallback().
Member Data Documentation
approximate
bool MeshPartGui::CurveOnMeshHandler::Private::approximate {true}
Definition at line 323 of file CurveOnMesh.cpp.
cosAngle
double MeshPartGui::CurveOnMeshHandler::Private::cosAngle {0.7071}
Definition at line 322 of file CurveOnMesh.cpp.
Referenced by MeshPartGui::CurveOnMeshHandler::Private::projectLineOnMesh().
curve
ViewProviderCurveOnMesh* MeshPartGui::CurveOnMeshHandler::Private::curve
Definition at line 324 of file CurveOnMesh.cpp.
Referenced by MeshPartGui::CurveOnMeshHandler::Private::~Private().
cutLines
std::list<std::vector<Base::Vector3f> > MeshPartGui::CurveOnMeshHandler::Private::cutLines
Definition at line 319 of file CurveOnMesh.cpp.
Referenced by MeshPartGui::CurveOnMeshHandler::Private::projectLineOnMesh().
distance
double MeshPartGui::CurveOnMeshHandler::Private::distance {1}
Definition at line 321 of file CurveOnMesh.cpp.
Referenced by Path.Dressup.Gui.Dogbone.Bone::adaptiveLength(), and Path.Dressup.Gui.Dogbone.Bone::corner().
editcursor
QCursor MeshPartGui::CurveOnMeshHandler::Private::editcursor
Definition at line 329 of file CurveOnMesh.cpp.
grid
MeshCore::MeshFacetGrid* MeshPartGui::CurveOnMeshHandler::Private::grid {nullptr}
Definition at line 326 of file CurveOnMesh.cpp.
Referenced by MeshPartGui::CurveOnMeshHandler::Private::createGrid(), Plot.Plot::isGrid(), MeshPartGui::CurveOnMeshHandler::Private::projectLineOnMesh(), and MeshPartGui::CurveOnMeshHandler::Private::~Private().
kernel
MeshCore::MeshKernel MeshPartGui::CurveOnMeshHandler::Private::kernel
Definition at line 327 of file CurveOnMesh.cpp.
Referenced by MeshPartGui::CurveOnMeshHandler::Private::createGrid(), and MeshPartGui::CurveOnMeshHandler::Private::projectLineOnMesh().
mesh
Gui::ViewProviderDocumentObject* MeshPartGui::CurveOnMeshHandler::Private::mesh {0}
Definition at line 325 of file CurveOnMesh.cpp.
Referenced by MeshPartGui::CurveOnMeshHandler::Private::createGrid(), MengerSponge.MengerThread::run(), and MeshPartGui::CurveOnMeshHandler::Private::vertexCallback().
par
ApproxPar MeshPartGui::CurveOnMeshHandler::Private::par
Definition at line 330 of file CurveOnMesh.cpp.
pickedPoints
std::vector<PickedPoint> MeshPartGui::CurveOnMeshHandler::Private::pickedPoints
Definition at line 318 of file CurveOnMesh.cpp.
Referenced by MeshPartGui::CurveOnMeshHandler::Private::projectLineOnMesh().
viewer
QPointer<Gui::View3DInventor> MeshPartGui::CurveOnMeshHandler::Private::viewer
Definition at line 328 of file CurveOnMesh.cpp.
Referenced by MeshPartGui::CurveOnMeshHandler::Private::projectLineOnMesh().
wireClosed
bool MeshPartGui::CurveOnMeshHandler::Private::wireClosed {false}
Definition at line 320 of file CurveOnMesh.cpp.
The documentation for this class was generated from the following file:
CurveOnMesh.cpp