FreeCAD: Gui::ExpressionSpinBox Class Reference
Gui::ExpressionSpinBox Class Reference abstract
#include <SpinBox.h>
Public Member Functions
ExpressionSpinBox (QAbstractSpinBox *)
~ExpressionSpinBox () override
void bind (const App::ObjectIdentifier &_path) override
void setExpression (std::shared_ptr< App::Expression > expr) override
Public Member Functions inherited from Gui::ExpressionWidget
ExpressionWidget ()
QPixmap getIcon (const char *name, const QSize &size) const
Public Member Functions inherited from Gui::ExpressionBinding
ExpressionBinding ()
virtual ~ExpressionBinding ()
virtual void bind (const App::Property &prop)
bool isBound () const
void unbind ()
virtual bool apply (const std::string &propName)
virtual bool apply ()
bool hasExpression () const
bool autoApply () const
void setAutoApply (bool value)
Protected Types
enum Number { Number::KeepCurrent = 0, Number::SetIfNumber = 1 }
Protected Member Functions
void showInvalidExpression (const QString &)
void showValidExpression (Number number)
void clearExpression ()
void updateExpression ()
void onChange () override
virtual void setNumberExpression (App::NumberExpression *)=0
virtual void showIcon ()
virtual void validateInput ()
void resizeWidget ()
bool handleKeyEvent (const QString &)
virtual void openFormulaDialog ()
void drawControl (QStyleOptionSpinBox &)
Protected Member Functions inherited from Gui::ExpressionWidget
void makeLabel (QLineEdit *parent)
Protected Member Functions inherited from Gui::ExpressionBinding
const App::ObjectIdentifier & getPath () const
std::shared_ptr< App::Expression > getExpression () const
std::string getExpressionString (bool no_throw=true) const
std::string getEscapedExpressionString () const
bool assignToProperty (const std::string &propName, double)
void expressionChange (const App::ObjectIdentifier &id)
void objectDeleted (const App::DocumentObject &)
Protected Attributes
QLineEdit * lineedit
QAbstractSpinBox * spinbox
Protected Attributes inherited from Gui::ExpressionWidget
ExpressionLabel * iconLabel {nullptr}
QPalette defaultPalette
int iconHeight {-1}
Protected Attributes inherited from Gui::ExpressionBinding
boost::signals2::scoped_connection expressionchanged
boost::signals2::scoped_connection objectdeleted
bool m_autoApply {false}
Detailed Description
Definition at line 39 of file SpinBox.h.
Member Enumeration Documentation
Number
enum Gui::ExpressionSpinBox::Number strong protected
Expression handling
Enumerator
KeepCurrent
SetIfNumber
Definition at line 51 of file SpinBox.h.
Constructor & Destructor Documentation
ExpressionSpinBox()
ExpressionSpinBox::ExpressionSpinBox (QAbstractSpinBox * sb) explicit
Definition at line 49 of file SpinBox.cpp.
References ExpressionLabel::clicked(), draftgeoutils.intersections::connect(), Gui::ExpressionWidget::iconLabel, lineedit, Gui::ExpressionWidget::makeLabel(), openFormulaDialog(), and spinbox.
~ExpressionSpinBox()
ExpressionSpinBox::~ExpressionSpinBox () override default
Member Function Documentation
bind()
void ExpressionSpinBox::bind (const App::ObjectIdentifier & _path) override virtual
Reimplemented from Gui::ExpressionBinding.
Definition at line 61 of file SpinBox.cpp.
References Gui::ExpressionBinding::bind(), and showIcon().
Referenced by Gui::QuantitySpinBox::bind().
clearExpression()
void ExpressionSpinBox::clearExpression () protected
Definition at line 113 of file SpinBox.cpp.
References Gui::ExpressionWidget::defaultPalette, Gui::ExpressionWidget::getIcon(), Gui::ExpressionWidget::iconHeight, Gui::ExpressionWidget::iconLabel, lineedit, buildPsets::p, ExpressionLabel::setExpressionText(), and spinbox.
Referenced by onChange(), and updateExpression().
drawControl()
void ExpressionSpinBox::drawControl (QStyleOptionSpinBox & opt) protected
Definition at line 210 of file SpinBox.cpp.
References Gui::ExpressionBinding::hasExpression(), buildPsets::p, and spinbox.
Referenced by Gui::UIntSpinBox::paintEvent(), Gui::IntSpinBox::paintEvent(), and Gui::DoubleSpinBox::paintEvent().
handleKeyEvent()
bool ExpressionSpinBox::handleKeyEvent (const QString & text) protected
Definition at line 200 of file SpinBox.cpp.
References Gui::ExpressionBinding::isBound(), and openFormulaDialog().
Referenced by Gui::UIntSpinBox::keyPressEvent(), Gui::IntSpinBox::keyPressEvent(), and Gui::DoubleSpinBox::keyPressEvent().
onChange()
void ExpressionSpinBox::onChange () override protected virtual
Reimplemented from Gui::ExpressionBinding.
Definition at line 153 of file SpinBox.cpp.
References clearExpression(), Gui::ExpressionBinding::getExpression(), Gui::ExpressionBinding::isBound(), SetIfNumber, and showValidExpression().
openFormulaDialog()
void ExpressionSpinBox::openFormulaDialog () protected virtual
Reimplemented in Gui::QuantitySpinBox.
Definition at line 174 of file SpinBox.cpp.
References MengerSponge::box, draftgeoutils.intersections::connect(), Gui::ExpressionBinding::getExpression(), Gui::ExpressionBinding::getPath(), getProperty(), Gui::ExpressionBinding::isBound(), RobotExample::pos, setExpression(), spinbox, and unit().
Referenced by ExpressionSpinBox(), and handleKeyEvent().
resizeWidget()
void ExpressionSpinBox::resizeWidget () protected
Definition at line 165 of file SpinBox.cpp.
References Gui::ExpressionWidget::iconLabel, lineedit, spinbox, and updateExpression().
Referenced by Gui::UIntSpinBox::resizeEvent(), Gui::IntSpinBox::resizeEvent(), Gui::QuantitySpinBox::resizeEvent(), and Gui::DoubleSpinBox::resizeEvent().
setExpression()
void ExpressionSpinBox::setExpression (std::shared_ptr< App::Expression > expr) override virtual
Reimplemented from Gui::ExpressionBinding.
Definition at line 140 of file SpinBox.cpp.
References SCL.SimpleDataTypes::e, Gui::ExpressionBinding::isBound(), Gui::ExpressionBinding::setExpression(), showInvalidExpression(), and validateInput().
Referenced by openFormulaDialog(), and Gui::QuantitySpinBox::setExpression().
setNumberExpression()
virtual void Gui::ExpressionSpinBox::setNumberExpression (App::NumberExpression *) protected pure virtual
Implemented in Gui::DoubleSpinBox, Gui::IntSpinBox, Gui::QuantitySpinBox, and Gui::UIntSpinBox.
Referenced by showValidExpression().
showIcon()
void ExpressionSpinBox::showIcon () protected virtual
Reimplemented in Gui::QuantitySpinBox.
Definition at line 68 of file SpinBox.cpp.
References Gui::ExpressionWidget::iconLabel, lineedit, and spinbox.
Referenced by bind().
showInvalidExpression()
void ExpressionSpinBox::showInvalidExpression (const QString & tip) protected
Definition at line 80 of file SpinBox.cpp.
References Gui::ExpressionWidget::iconLabel, lineedit, buildPsets::p, and spinbox.
Referenced by setExpression(), and updateExpression().
showValidExpression()
void ExpressionSpinBox::showValidExpression (ExpressionSpinBox::Number number) protected
Definition at line 89 of file SpinBox.cpp.
References Gui::ExpressionBinding::getExpression(), Gui::ExpressionWidget::getIcon(), Gui::ExpressionWidget::iconHeight, Gui::ExpressionWidget::iconLabel, KeepCurrent, lineedit, buildPsets::p, result, ExpressionLabel::setExpressionText(), SetIfNumber, setNumberExpression(), spinbox, and DraftVecUtils::toString().
Referenced by Gui::QuantitySpinBox::evaluateExpression(), onChange(), and updateExpression().
updateExpression()
void ExpressionSpinBox::updateExpression () protected
Definition at line 125 of file SpinBox.cpp.
References clearExpression(), SCL.SimpleDataTypes::e, Gui::ExpressionBinding::getExpression(), Gui::ExpressionBinding::isBound(), KeepCurrent, showInvalidExpression(), and showValidExpression().
Referenced by resizeWidget().
validateInput()
void ExpressionSpinBox::validateInput () protected virtual
Definition at line 76 of file SpinBox.cpp.
Referenced by setExpression().
Member Data Documentation
lineedit
QLineEdit* Gui::ExpressionSpinBox::lineedit protected
Definition at line 73 of file SpinBox.h.
Referenced by clearExpression(), ExpressionSpinBox(), resizeWidget(), showIcon(), showInvalidExpression(), and showValidExpression().
spinbox
QAbstractSpinBox* Gui::ExpressionSpinBox::spinbox protected
Definition at line 74 of file SpinBox.h.
Referenced by draftguitools.gui_lineslope.LineSlope::accept(), clearExpression(), drawControl(), ExpressionSpinBox(), openFormulaDialog(), resizeWidget(), showIcon(), showInvalidExpression(), and showValidExpression().
The documentation for this class was generated from the following files:
SpinBox.h
SpinBox.cpp