FreeCAD: TechDrawGui::QGISVGTemplate Class Reference
TechDrawGui::QGISVGTemplate Class Reference
#include <QGISVGTemplate.h>
Public Types
enum { Type = QGraphicsItem::UserType + 153 }
Public Types inherited from TechDrawGui::QGITemplate
enum { Type = QGraphicsItem::UserType + 150 }
Public Member Functions
QGISVGTemplate (QGSPage *scene)
~QGISVGTemplate () override
int type () const override
void draw () override
void updateView (bool update=false) override
TechDraw::DrawSVGTemplate * getSVGTemplate ()
Public Member Functions inherited from TechDrawGui::QGITemplate
QGITemplate (QGSPage *)
~QGITemplate () override
int type () const override
void clearContents ()
void setTemplate (TechDraw::DrawTemplate *obj)
TechDraw::DrawTemplate * getTemplate ()
qreal getY ()
std::vector< TemplateTextField * > getTextFields ()
Protected Member Functions
void openFile (const QFile &file)
void load (const QByteArray &svgCode)
void createClickHandles (void)
Static Protected Member Functions
static double getFontSizeFromStyle (QString style)
find the font-size hidden in a style element
static double getFontSizeFromElement (QString element)
find the font-size hidden in a style element
Protected Attributes
bool firstTime
QGraphicsSvgItem * m_svgItem
QSvgRenderer * m_svgRender
Protected Attributes inherited from TechDrawGui::QGITemplate
TechDraw::DrawTemplate * pageTemplate
std::vector< TemplateTextField * > textFields
Detailed Description
Definition at line 46 of file QGISVGTemplate.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 54 of file QGISVGTemplate.h.
Constructor & Destructor Documentation
QGISVGTemplate()
QGISVGTemplate::QGISVGTemplate (QGSPage * scene) explicit
Definition at line 55 of file QGISVGTemplate.cpp.
References m_svgItem, m_svgRender, and ZVALUE::SVGTEMPLATE.
~QGISVGTemplate()
QGISVGTemplate::~QGISVGTemplate () override
Definition at line 72 of file QGISVGTemplate.cpp.
References m_svgRender.
Member Function Documentation
createClickHandles()
void QGISVGTemplate::createClickHandles (void) protected
Definition at line 139 of file QGISVGTemplate.cpp.
References Base::Console(), TechDraw::DrawTemplate::EditableTexts, Base::ConsoleSingleton::Error(), DrawingExample::file, FREECAD_ATTR_EDITABLE, FREECAD_SVG_NS_URI, TechDraw::DrawSVGTemplate::getAutofillByEditableName(), getFontSizeFromElement(), getFontSizeFromStyle(), TechDraw::DrawSVGTemplate::getHeight(), getSVGTemplate(), App::PropertyFileIncluded::getValue(), App::PropertyMap::getValues(), TechDrawGui::Rez::guiX(), App::DocumentObject::isRestoring(), KDL::max(), Base::ConsoleSingleton::Message(), TechDraw::DrawSVGTemplate::PageResult, TechDraw::XMLQuery::processItems(), SVG_NS_URI, ZVALUE::SVGTEMPLATE, TechDrawGui::PreferencesGui::templateClickBoxColor(), TechDrawGui::QGITemplate::textFields, Base::ConsoleSingleton::Warning(), MovieTool::x, and MovieTool::y.
Referenced by load().
draw()
void QGISVGTemplate::draw () override virtual
Implements TechDrawGui::QGITemplate.
Definition at line 123 of file QGISVGTemplate.cpp.
References getSVGTemplate(), load(), and TechDraw::DrawSVGTemplate::processTemplate().
Referenced by updateView().
getFontSizeFromElement()
double QGISVGTemplate::getFontSizeFromElement (QString element) static protected
find the font-size hidden in a style element
Definition at line 274 of file QGISVGTemplate.cpp.
References TechDrawGui::Rez::guiX(), RobotExample::pos, and src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression.
Referenced by createClickHandles().
getFontSizeFromStyle()
double QGISVGTemplate::getFontSizeFromStyle (QString style) static protected
find the font-size hidden in a style element
Definition at line 254 of file QGISVGTemplate.cpp.
References TechDrawGui::Rez::guiX(), RobotExample::pos, and src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression.
Referenced by createClickHandles().
getSVGTemplate()
TechDraw::DrawSVGTemplate * QGISVGTemplate::getSVGTemplate ()
Definition at line 113 of file QGISVGTemplate.cpp.
References Base::Persistence::getClassTypeId(), Base::BaseClass::isDerivedFrom(), and TechDrawGui::QGITemplate::pageTemplate.
Referenced by createClickHandles(), draw(), load(), and TechDrawGui::QGSPage::postProcessXml().
load()
void QGISVGTemplate::load (const QByteArray & svgCode) protected
Definition at line 76 of file QGISVGTemplate.cpp.
References createClickHandles(), firstTime, TechDrawGui::PreferencesGui::getAccessibleQColor(), TechDraw::DrawSVGTemplate::getHeight(), getSVGTemplate(), TechDraw::DrawSVGTemplate::getWidth(), TechDrawGui::Rez::guiX(), m_svgItem, and m_svgRender.
Referenced by draw().
openFile()
void QGISVGTemplate::openFile (const QFile & file) protected
Definition at line 74 of file QGISVGTemplate.cpp.
References DrawingExample::file.
type()
int TechDrawGui::QGISVGTemplate::type () const inline override
Definition at line 58 of file QGISVGTemplate.h.
updateView()
void QGISVGTemplate::updateView (bool update = false) override virtual
Reimplemented from TechDrawGui::QGITemplate.
Definition at line 133 of file QGISVGTemplate.cpp.
References draw().
Referenced by TechDrawGui::ViewProviderTemplate::setMarkers().
Member Data Documentation
firstTime
bool TechDrawGui::QGISVGTemplate::firstTime protected
Definition at line 73 of file QGISVGTemplate.h.
Referenced by load().
m_svgItem
QGraphicsSvgItem* TechDrawGui::QGISVGTemplate::m_svgItem protected
Definition at line 74 of file QGISVGTemplate.h.
Referenced by load(), and QGISVGTemplate().
m_svgRender
QSvgRenderer* TechDrawGui::QGISVGTemplate::m_svgRender protected
Definition at line 75 of file QGISVGTemplate.h.
Referenced by load(), QGISVGTemplate(), and ~QGISVGTemplate().
The documentation for this class was generated from the following files:
QGISVGTemplate.h
QGISVGTemplate.cpp