FreeCAD: lscmrelax::LscmRelax Class Reference
lscmrelax::LscmRelax Class Reference
#include <MeshFlatteningLscmRelax.h>
Public Member Functions
LscmRelax ()=default
LscmRelax (RowMat< double, 3 > vertices, RowMat< long, 3 > triangles, std::vector< long > fixed_pins)
void lscm ()
void relax (double)
void area_relax (double)
void edge_relax (double)
ColMat< double, 3 > get_flat_vertices_3D ()
void rotate_by_min_bound_area ()
void transform (bool scale=false)
double get_area ()
double get_flat_area ()
Public Attributes
std::vector< long > fixed_pins
RowMat< double, 3 > vertices
RowMat< long, 3 > triangles
RowMat< double, 2 > flat_vertices
ColMat< double, 1 > rhs
Eigen::MatrixXd MATRIX
double nue =0.9
double elasticity =1.
Detailed Description
Definition at line 72 of file MeshFlatteningLscmRelax.h.
Constructor & Destructor Documentation
LscmRelax() [1/2]
lscmrelax::LscmRelax::LscmRelax () default
LscmRelax() [2/2]
lscmrelax::LscmRelax::LscmRelax (RowMat< double, 3 > vertices, RowMat< long, 3 > triangles, std::vector< long > fixed_pins)
Definition at line 96 of file MeshFlatteningLscmRelax.cpp.
References elasticity, fixed_pins, flat_vertices, SplineSurface::i, nue, triangles, and vertices.
Member Function Documentation
area_relax()
void lscmrelax::LscmRelax::area_relax (double weight)
Definition at line 297 of file MeshFlatteningLscmRelax.cpp.
References RobotExample::B, flat_vertices, SplineSurface::i, rhs, triangles, draftgeoutils.general::v1(), and vertices.
edge_relax()
void lscmrelax::LscmRelax::edge_relax (double weight)
Definition at line 352 of file MeshFlatteningLscmRelax.cpp.
References RobotExample::B, flat_vertices, SplineSurface::i, rhs, InitGui::t, triangles, and vertices.
get_area()
double lscmrelax::LscmRelax::get_area ()
Definition at line 598 of file MeshFlatteningLscmRelax.cpp.
References SplineSurface::i, and triangles.
Referenced by BOOST_PYTHON_MODULE(), and PYBIND11_MODULE().
get_flat_area()
double lscmrelax::LscmRelax::get_flat_area ()
Definition at line 608 of file MeshFlatteningLscmRelax.cpp.
References SplineSurface::i, and triangles.
Referenced by BOOST_PYTHON_MODULE(), and PYBIND11_MODULE().
get_flat_vertices_3D()
ColMat< double, 3 > lscmrelax::LscmRelax::get_flat_vertices_3D ()
Definition at line 572 of file MeshFlatteningLscmRelax.cpp.
References flat_vertices.
Referenced by BOOST_PYTHON_MODULE(), and PYBIND11_MODULE().
lscm()
void lscmrelax::LscmRelax::lscm ()
Definition at line 425 of file MeshFlatteningLscmRelax.cpp.
References RobotExample::A, RobotExample::B, fixed_pins, flat_vertices, SplineSurface::i, rhs, transform(), triangles, and vertices.
Referenced by BOOST_PYTHON_MODULE(), FaceUnwrapper::findFlatNodes(), and PYBIND11_MODULE().
relax()
void lscmrelax::LscmRelax::relax (double weight)
Definition at line 148 of file MeshFlatteningLscmRelax.cpp.
References RobotExample::A, KDL::abs(), RobotExample::B, flat_vertices, SplineSurface::i, rhs, triangles, draftgeoutils.general::v1(), and vertices.
Referenced by BOOST_PYTHON_MODULE(), FaceUnwrapper::findFlatNodes(), and PYBIND11_MODULE().
rotate_by_min_bound_area()
void lscmrelax::LscmRelax::rotate_by_min_bound_area ()
Definition at line 642 of file MeshFlatteningLscmRelax.cpp.
References KDL::cos(), flat_vertices, SplineSurface::i, M_PI, and KDL::sin().
Referenced by BOOST_PYTHON_MODULE(), and PYBIND11_MODULE().
transform()
void lscmrelax::LscmRelax::transform (bool scale = false)
Definition at line 618 of file MeshFlatteningLscmRelax.cpp.
References exportCSG::center(), flat_vertices, SplineSurface::i, Base::pow(), and triangles.
Referenced by BOOST_PYTHON_MODULE(), lscm(), and PYBIND11_MODULE().
Member Data Documentation
elasticity
double lscmrelax::LscmRelax::elasticity =1.
Definition at line 107 of file MeshFlatteningLscmRelax.h.
Referenced by LscmRelax().
fixed_pins
std::vector<long> lscmrelax::LscmRelax::fixed_pins
Definition at line 99 of file MeshFlatteningLscmRelax.h.
Referenced by lscm(), and LscmRelax().
flat_vertices
RowMat<double, 2> lscmrelax::LscmRelax::flat_vertices
Definition at line 102 of file MeshFlatteningLscmRelax.h.
Referenced by area_relax(), edge_relax(), FaceUnwrapper::findFlatNodes(), get_flat_vertices_3D(), lscm(), LscmRelax(), PYBIND11_MODULE(), relax(), rotate_by_min_bound_area(), and transform().
MATRIX
Eigen::MatrixXd lscmrelax::LscmRelax::MATRIX
Definition at line 104 of file MeshFlatteningLscmRelax.h.
Referenced by BOOST_PYTHON_MODULE(), and PYBIND11_MODULE().
nue
double lscmrelax::LscmRelax::nue =0.9
Definition at line 106 of file MeshFlatteningLscmRelax.h.
Referenced by LscmRelax().
rhs
ColMat<double, 1> lscmrelax::LscmRelax::rhs
Definition at line 103 of file MeshFlatteningLscmRelax.h.
Referenced by area_relax(), BOOST_PYTHON_MODULE(), edge_relax(), lscm(), PYBIND11_MODULE(), and relax().
triangles
RowMat<long, 3> lscmrelax::LscmRelax::triangles
Definition at line 101 of file MeshFlatteningLscmRelax.h.
Referenced by area_relax(), edge_relax(), get_area(), get_flat_area(), lscm(), LscmRelax(), relax(), and transform().
vertices
RowMat<double, 3> lscmrelax::LscmRelax::vertices
Definition at line 100 of file MeshFlatteningLscmRelax.h.
Referenced by area_relax(), edge_relax(), lscm(), LscmRelax(), and relax().
The documentation for this class was generated from the following files:
MeshFlatteningLscmRelax.h
MeshFlatteningLscmRelax.cpp