FreeCAD: PartDesignGui::TaskHoleParameters Class Reference
PartDesignGui::TaskHoleParameters Class Reference
#include <TaskHoleParameters.h>
Public Member Functions
TaskHoleParameters (ViewProviderHole *HoleView, QWidget *parent=nullptr)
~TaskHoleParameters () override
void apply () override
apply changes made in the parameters input to the model via commands
bool getThreaded () const
long getThreadType () const
long getThreadSize () const
long getThreadClass () const
long getThreadFit () const
Base::Quantity getDiameter () const
long getThreadDirection () const
long getHoleCutType () const
bool getHoleCutCustomValues () const
Base::Quantity getHoleCutDiameter () const
Base::Quantity getHoleCutDepth () const
Base::Quantity getHoleCutCountersinkAngle () const
long getDepthType () const
Base::Quantity getDepth () const
long getDrillPoint () const
Base::Quantity getDrillPointAngle () const
bool getDrillForDepth () const
bool getTapered () const
Base::Quantity getTaperedAngle () const
bool getUseCustomThreadClearance () const
double getCustomThreadClearance () const
bool getModelThread () const
long getThreadDepthType () const
double getThreadDepth () const
Public Member Functions inherited from PartDesignGui::TaskSketchBasedParameters
TaskSketchBasedParameters (PartDesignGui::ViewProvider *vp, QWidget *parent, const std::string &pixmapname, const QString &parname)
~TaskSketchBasedParameters () override
Public Member Functions inherited from PartDesignGui::TaskFeatureParameters
TaskFeatureParameters (PartDesignGui::ViewProvider *vp, QWidget *parent, const std::string &pixmapname, const QString &parname)
~TaskFeatureParameters () override=default
virtual void saveHistory ()
save field history
void recomputeFeature ()
bool isUpdateBlocked () const
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Public Member Functions inherited from Gui::DocumentObserver
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
void attachDocument (Document *)
void detachDocument ()
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Protected Member Functions
void changeEvent (QEvent *e) override
void changedObject (const App::Document &, const App::Property &Prop)
Protected Member Functions inherited from PartDesignGui::TaskSketchBasedParameters
const QString onAddSelection (const Gui::SelectionChanges &msg)
virtual void startReferenceSelection (App::DocumentObject *profile, App::DocumentObject *base)
virtual void finishReferenceSelection (App::DocumentObject *profile, App::DocumentObject *base)
void onSelectReference (AllowSelectionFlags)
onSelectReference Start reference selection mode to allow one to select objects of the type defined with AllowSelectionFlags. If AllowSelection::NONE is passed the selection mode is finished.
void exitSelectionMode ()
QVariant setUpToFace (const QString &text)
QVariant objectNameByLabel (const QString &label, const QVariant &suggest) const
QString getFaceReference (const QString &obj, const QString &sub) const
QString make2DLabel (const App::DocumentObject *section, const std::vector< std::string > &subValues)
Protected Member Functions inherited from PartDesignGui::TaskFeatureParameters
template<typename T = PartDesignGui::ViewProvider>
T * getViewObject () const
template<typename T = App::DocumentObject>
T * getObject () const
Gui::Document * getGuiDocument () const
App::Document * getAppDocument () const
bool & getUpdateBlockRef ()
void setUpdateBlocked (bool value)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Protected Slots inherited from PartDesignGui::TaskFeatureParameters
void onUpdateView (bool on)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
Definition at line 48 of file TaskHoleParameters.h.
Constructor & Destructor Documentation
TaskHoleParameters()
TaskHoleParameters::TaskHoleParameters (ViewProviderHole * HoleView, QWidget * parent = nullptr) explicit
Definition at line 52 of file TaskHoleParameters.cpp.
References draftgeoutils.faces::bind(), changedObject(), draftgeoutils.intersections::connect(), App::GetApplication(), PartDesignGui::TaskFeatureParameters::getViewObject(), QSint::ActionGroup::groupLayout(), App::Application::signalChangePropertyEditor, and Gui::QuantitySpinBox::valueChanged().
~TaskHoleParameters()
TaskHoleParameters::~TaskHoleParameters () override default
Member Function Documentation
apply()
void TaskHoleParameters::apply () override virtual
apply changes made in the parameters input to the model via commands
Reimplemented from PartDesignGui::TaskFeatureParameters.
Definition at line 1200 of file TaskHoleParameters.cpp.
References FCMD_OBJ_CMD, getCustomThreadClearance(), getDepthType(), getDrillForDepth(), getDrillPoint(), getHoleCutCustomValues(), getHoleCutType(), getModelThread(), getTapered(), getThreadClass(), getThreadDepth(), getThreadDepthType(), getThreadDirection(), getThreaded(), getThreadFit(), getThreadSize(), getThreadType(), and getUseCustomThreadClearance().
changedObject()
void TaskHoleParameters::changedObject (const App::Document & , const App::Property & Prop) protected
Definition at line 779 of file TaskHoleParameters.cpp.
References Base::Console(), App::Property::getName(), App::Property::isReadOnly(), and Base::ConsoleSingleton::Log().
Referenced by TaskHoleParameters().
changeEvent()
void TaskHoleParameters::changeEvent (QEvent * e) override protected
Definition at line 771 of file TaskHoleParameters.cpp.
References SCL.SimpleDataTypes::e.
getCustomThreadClearance()
double TaskHoleParameters::getCustomThreadClearance () const
Definition at line 1180 of file TaskHoleParameters.cpp.
Referenced by apply().
getDepth()
Base::Quantity TaskHoleParameters::getDepth () const
Definition at line 1138 of file TaskHoleParameters.cpp.
getDepthType()
long TaskHoleParameters::getDepthType () const
Definition at line 1133 of file TaskHoleParameters.cpp.
Referenced by apply().
getDiameter()
Base::Quantity TaskHoleParameters::getDiameter () const
Definition at line 1088 of file TaskHoleParameters.cpp.
getDrillForDepth()
bool TaskHoleParameters::getDrillForDepth () const
Definition at line 1165 of file TaskHoleParameters.cpp.
Referenced by apply().
getDrillPoint()
long TaskHoleParameters::getDrillPoint () const
Definition at line 1143 of file TaskHoleParameters.cpp.
Referenced by apply().
getDrillPointAngle()
Base::Quantity TaskHoleParameters::getDrillPointAngle () const
Definition at line 1155 of file TaskHoleParameters.cpp.
getHoleCutCountersinkAngle()
Base::Quantity TaskHoleParameters::getHoleCutCountersinkAngle () const
Definition at line 1128 of file TaskHoleParameters.cpp.
getHoleCutCustomValues()
bool TaskHoleParameters::getHoleCutCustomValues () const
Definition at line 1113 of file TaskHoleParameters.cpp.
Referenced by apply().
getHoleCutDepth()
Base::Quantity TaskHoleParameters::getHoleCutDepth () const
Definition at line 1123 of file TaskHoleParameters.cpp.
getHoleCutDiameter()
Base::Quantity TaskHoleParameters::getHoleCutDiameter () const
Definition at line 1118 of file TaskHoleParameters.cpp.
getHoleCutType()
long TaskHoleParameters::getHoleCutType () const
Definition at line 1103 of file TaskHoleParameters.cpp.
Referenced by apply().
getModelThread()
bool TaskHoleParameters::getModelThread () const
Definition at line 1185 of file TaskHoleParameters.cpp.
Referenced by apply().
getTapered()
bool TaskHoleParameters::getTapered () const
Definition at line 1160 of file TaskHoleParameters.cpp.
Referenced by apply().
getTaperedAngle()
Base::Quantity TaskHoleParameters::getTaperedAngle () const
Definition at line 1170 of file TaskHoleParameters.cpp.
getThreadClass()
long TaskHoleParameters::getThreadClass () const
Definition at line 1071 of file TaskHoleParameters.cpp.
Referenced by apply().
getThreadDepth()
double TaskHoleParameters::getThreadDepth () const
Definition at line 1195 of file TaskHoleParameters.cpp.
Referenced by apply().
getThreadDepthType()
long TaskHoleParameters::getThreadDepthType () const
Definition at line 1190 of file TaskHoleParameters.cpp.
Referenced by apply().
getThreadDirection()
long TaskHoleParameters::getThreadDirection () const
Definition at line 1093 of file TaskHoleParameters.cpp.
Referenced by apply().
getThreaded()
bool TaskHoleParameters::getThreaded () const
Definition at line 1051 of file TaskHoleParameters.cpp.
Referenced by apply().
getThreadFit()
long TaskHoleParameters::getThreadFit () const
Definition at line 1081 of file TaskHoleParameters.cpp.
Referenced by apply().
getThreadSize()
long TaskHoleParameters::getThreadSize () const
Definition at line 1061 of file TaskHoleParameters.cpp.
Referenced by apply().
getThreadType()
long TaskHoleParameters::getThreadType () const
Definition at line 1056 of file TaskHoleParameters.cpp.
Referenced by apply().
getUseCustomThreadClearance()
bool TaskHoleParameters::getUseCustomThreadClearance () const
Definition at line 1175 of file TaskHoleParameters.cpp.
Referenced by apply().
The documentation for this class was generated from the following files:
TaskHoleParameters.h
TaskHoleParameters.cpp