FreeCAD: AppSandbox.cpp File Reference
AppSandbox.cpp File Reference
#include "PreCompiled.h"
#include <Python.h>
#include <Base/Console.h>
#include <App/DocumentPy.h>
#include <App/DocumentObjectPy.h>
#include <CXX/Extensions.hxx>
#include <CXX/Objects.hxx>
#include "DocumentThread.h"
#include "DocumentProtector.h"
#include "DocumentProtectorPy.h"
Classes
class Sandbox::PythonBaseClass
class Sandbox::Module
Namespaces
Sandbox
Functions
PyObject * Sandbox::initModule ()
PyMOD_INIT_FUNC (Sandbox)
Function Documentation
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (Sandbox)
Definition at line 248 of file AppSandbox.cpp.
References Base::Console(), Sandbox::DocumentProtector::init(), Base::Persistence::init(), Sandbox::initModule(), Base::ConsoleSingleton::Log(), mod, and PyMOD_Return.