FreeCAD: Gui::SoFCCSysDragger Class Reference
Gui::SoFCCSysDragger Class Reference
Coordinate System Dragger.
#include <SoFCCSysDragger.h>
Public Member Functions
SoFCCSysDragger ()
~SoFCCSysDragger () override
void clearIncrementCounts ()
used to reset after drag update.
void setUpAutoScale (SoCamera *cameraIn)
used to setup the auto scaling of dragger.
void setAxisColors (unsigned long x, unsigned long y, unsigned long z)
set the axis colors.
Static Public Member Functions
static void initClass ()
Public Attributes
SoSFVec3f translation
initial translation and reflects single precision movement.
SoSFDouble translationIncrement
set from outside used for rounding.
SoSFInt32 translationIncrementCountX
used from outside for translation x steps.
SoSFInt32 translationIncrementCountY
used from outside for translation y steps.
SoSFInt32 translationIncrementCountZ
used from outside for translation z steps.
SoSFRotation rotation
initial rotation and reflects single precision movement.
SoSFDouble rotationIncrement
radians set from outside and used for rounding.
SoSFInt32 rotationIncrementCountX
used from outside for rotation x steps.
SoSFInt32 rotationIncrementCountY
used from outside for rotation y steps.
SoSFInt32 rotationIncrementCountZ
used from outside for rotation z steps.
SoSFString xAxisLabel
label for X axis
SoSFString yAxisLabel
label for Y axis
SoSFString zAxisLabel
label for Z axis
SoSFFloat draggerSize
Overall scale of dragger node.
SoSFFloat autoScaleResult
result of autoscale calculation and used by childdraggers. Don't use.
SoIdleSensor idleSensor
might be overkill, but want to make sure of performance.
Visibility Functions
SoFieldSensor translationSensor
SoFieldSensor rotationSensor
SoFieldSensor cameraSensor
void showTranslationX ()
show the x translation dragger.
void showTranslationY ()
show the y translation dragger.
void showTranslationZ ()
show the z translation dragger.
void hideTranslationX ()
hide the x translation dragger.
void hideTranslationY ()
hide the y translation dragger.
void hideTranslationZ ()
hide the z translation dragger.
bool isShownTranslationX ()
is x translation dragger shown.
bool isShownTranslationY ()
is y translation dragger shown.
bool isShownTranslationZ ()
is z translation dragger shown.
bool isHiddenTranslationX ()
is x translation dragger hidden.
bool isHiddenTranslationY ()
is y translation dragger hidden.
bool isHiddenTranslationZ ()
is z translation dragger hidden.
void showPlanarTranslationXY ()
show the xy planar translation dragger.
void showPlanarTranslationYZ ()
show the yz planar translation dragger.
void showPlanarTranslationZX ()
show the zx planar translation dragger.
void hidePlanarTranslationXY ()
hide the xy planar translation dragger.
void hidePlanarTranslationYZ ()
hide the yz planar translation dragger.
void hidePlanarTranslationZX ()
hide the zx planar translation dragger.
bool isShownPlanarTranslationXY ()
is xy planar translation dragger shown.
bool isShownPlanarTranslationYZ ()
is yz planar translation dragger shown.
bool isShownPlanarTranslationZX ()
is zx planar translation dragger shown.
bool isHiddenPlanarTranslationXY ()
is xy planar translation dragger hidden.
bool isHiddenPlanarTranslationYZ ()
is yz planar translation dragger hidden.
bool isHiddenPlanarTranslationZX ()
is zx planar translation dragger hidden.
void showRotationX ()
show the x rotation dragger.
void showRotationY ()
show the y rotation dragger.
void showRotationZ ()
show the z rotation dragger.
void hideRotationX ()
hide the x rotation dragger.
void hideRotationY ()
hide the y rotation dragger.
void hideRotationZ ()
hide the z rotation dragger.
bool isShownRotationX ()
is x rotation dragger shown.
bool isShownRotationY ()
is x rotation dragger shown.
bool isShownRotationZ ()
is x rotation dragger shown.
bool isHiddenRotationX ()
is x rotation dragger hidden.
bool isHiddenRotationY ()
is x rotation dragger hidden.
bool isHiddenRotationZ ()
is x rotation dragger hidden.
void GLRender (SoGLRenderAction *action) override
SbBool setUpConnections (SbBool onoff, SbBool doitalways=FALSE) override
void handleEvent (SoHandleEventAction *action) override
static void translationSensorCB (void *f, SoSensor *)
static void rotationSensorCB (void *f, SoSensor *)
static void valueChangedCB (void *, SoDragger *d)
static void cameraCB (void *data, SoSensor *)
static void idleCB (void *data, SoSensor *)
scheduled from cameraCB to auto scale dragger.
static void finishDragCB (void *data, SoDragger *)
Detailed Description
Coordinate System Dragger.
used to transform objects in 3d space. Set initial: translation, rotation, translationIncrement and rotationIncrement. Use IncrementCount multiplied with *Increment for full double precision output.
Dragger can be displayed in 2 modes: static scale and auto scale. For static you can set the field scale and you are done. For autoscale you set the field scale & call setupAutoScale with the viewer camera.
See also
setUpAutoScale
scale.
Definition at line 215 of file SoFCCSysDragger.h.
Constructor & Destructor Documentation
SoFCCSysDragger()
SoFCCSysDragger::SoFCCSysDragger ()
Definition at line 1036 of file SoFCCSysDragger.cpp.
References Gui::TDragger::autoScaleResult, Gui::TPlanarDragger::autoScaleResult, autoScaleResult, cameraCB(), cameraSensor, draggerSize, SCL.SimpleDataTypes::f, finishDragCB(), idleCB(), idleSensor, Gui::TDragger::label, M_PI, rotation, Gui::RDragger::rotationIncrement, rotationIncrement, Gui::RDragger::rotationIncrementCount, rotationIncrementCountX, rotationIncrementCountY, rotationIncrementCountZ, rotationSensor, rotationSensorCB(), setAxisColors(), setUpConnections(), translation, Gui::TDragger::translationIncrement, Gui::TPlanarDragger::translationIncrement, translationIncrement, Gui::TDragger::translationIncrementCount, translationIncrementCountX, translationIncrementCountY, translationIncrementCountZ, Gui::TPlanarDragger::translationIncrementXCount, Gui::TPlanarDragger::translationIncrementYCount, translationSensor, translationSensorCB(), SCL.Builtin::TRUE, valueChangedCB(), xAxisLabel, yAxisLabel, and zAxisLabel.
~SoFCCSysDragger()
SoFCCSysDragger::~SoFCCSysDragger () override
Definition at line 1336 of file SoFCCSysDragger.cpp.
References cameraSensor, finishDragCB(), idleSensor, rotationSensor, translationSensor, and valueChangedCB().
Member Function Documentation
cameraCB()
void SoFCCSysDragger::cameraCB (void * data, SoSensor *) static protected
Definition at line 1491 of file SoFCCSysDragger.cpp.
References idleSensor.
Referenced by finishDragCB(), setUpAutoScale(), and SoFCCSysDragger().
clearIncrementCounts()
void SoFCCSysDragger::clearIncrementCounts ()
used to reset after drag update.
Definition at line 1583 of file SoFCCSysDragger.cpp.
References rotationIncrementCountX, rotationIncrementCountY, rotationIncrementCountZ, translationIncrementCountX, translationIncrementCountY, and translationIncrementCountZ.
finishDragCB()
void SoFCCSysDragger::finishDragCB (void * data, SoDragger *) static protected
Definition at line 1566 of file SoFCCSysDragger.cpp.
References cameraCB().
Referenced by SoFCCSysDragger(), and ~SoFCCSysDragger().
GLRender()
void SoFCCSysDragger::GLRender (SoGLRenderAction * action) override
Definition at line 1502 of file SoFCCSysDragger.cpp.
References Path.Post.scripts.dynapath_4060_post::action.
handleEvent()
void SoFCCSysDragger::handleEvent (SoHandleEventAction * action) override protected
Definition at line 1531 of file SoFCCSysDragger.cpp.
References Path.Post.scripts.dynapath_4060_post::action.
hidePlanarTranslationXY()
void SoFCCSysDragger::hidePlanarTranslationXY ()
hide the xy planar translation dragger.
Definition at line 1713 of file SoFCCSysDragger.cpp.
hidePlanarTranslationYZ()
void SoFCCSysDragger::hidePlanarTranslationYZ ()
hide the yz planar translation dragger.
Definition at line 1718 of file SoFCCSysDragger.cpp.
hidePlanarTranslationZX()
void SoFCCSysDragger::hidePlanarTranslationZX ()
hide the zx planar translation dragger.
Definition at line 1723 of file SoFCCSysDragger.cpp.
hideRotationX()
void SoFCCSysDragger::hideRotationX ()
hide the x rotation dragger.
Definition at line 1778 of file SoFCCSysDragger.cpp.
hideRotationY()
void SoFCCSysDragger::hideRotationY ()
hide the y rotation dragger.
Definition at line 1783 of file SoFCCSysDragger.cpp.
hideRotationZ()
void SoFCCSysDragger::hideRotationZ ()
hide the z rotation dragger.
Definition at line 1788 of file SoFCCSysDragger.cpp.
hideTranslationX()
void SoFCCSysDragger::hideTranslationX ()
hide the x translation dragger.
Definition at line 1648 of file SoFCCSysDragger.cpp.
hideTranslationY()
void SoFCCSysDragger::hideTranslationY ()
hide the y translation dragger.
Definition at line 1653 of file SoFCCSysDragger.cpp.
hideTranslationZ()
void SoFCCSysDragger::hideTranslationZ ()
hide the z translation dragger.
Definition at line 1658 of file SoFCCSysDragger.cpp.
idleCB()
void SoFCCSysDragger::idleCB (void * data, SoSensor *) static protected
scheduled from cameraCB to auto scale dragger.
Definition at line 1541 of file SoFCCSysDragger.cpp.
References cameraSensor.
Referenced by SoFCCSysDragger().
initClass()
void SoFCCSysDragger::initClass () static
Definition at line 1028 of file SoFCCSysDragger.cpp.
References Gui::TDragger::initClass(), Gui::TPlanarDragger::initClass(), and Gui::RDragger::initClass().
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
isHiddenPlanarTranslationXY()
bool SoFCCSysDragger::isHiddenPlanarTranslationXY ()
is xy planar translation dragger hidden.
Definition at line 1745 of file SoFCCSysDragger.cpp.
isHiddenPlanarTranslationYZ()
bool SoFCCSysDragger::isHiddenPlanarTranslationYZ ()
is yz planar translation dragger hidden.
Definition at line 1750 of file SoFCCSysDragger.cpp.
isHiddenPlanarTranslationZX()
bool SoFCCSysDragger::isHiddenPlanarTranslationZX ()
is zx planar translation dragger hidden.
Definition at line 1755 of file SoFCCSysDragger.cpp.
isHiddenRotationX()
bool SoFCCSysDragger::isHiddenRotationX ()
is x rotation dragger hidden.
Definition at line 1810 of file SoFCCSysDragger.cpp.
isHiddenRotationY()
bool SoFCCSysDragger::isHiddenRotationY ()
is x rotation dragger hidden.
Definition at line 1815 of file SoFCCSysDragger.cpp.
isHiddenRotationZ()
bool SoFCCSysDragger::isHiddenRotationZ ()
is x rotation dragger hidden.
Definition at line 1820 of file SoFCCSysDragger.cpp.
isHiddenTranslationX()
bool SoFCCSysDragger::isHiddenTranslationX ()
is x translation dragger hidden.
Definition at line 1680 of file SoFCCSysDragger.cpp.
isHiddenTranslationY()
bool SoFCCSysDragger::isHiddenTranslationY ()
is y translation dragger hidden.
Definition at line 1685 of file SoFCCSysDragger.cpp.
isHiddenTranslationZ()
bool SoFCCSysDragger::isHiddenTranslationZ ()
is z translation dragger hidden.
Definition at line 1690 of file SoFCCSysDragger.cpp.
isShownPlanarTranslationXY()
bool SoFCCSysDragger::isShownPlanarTranslationXY ()
is xy planar translation dragger shown.
Definition at line 1729 of file SoFCCSysDragger.cpp.
isShownPlanarTranslationYZ()
bool SoFCCSysDragger::isShownPlanarTranslationYZ ()
is yz planar translation dragger shown.
Definition at line 1734 of file SoFCCSysDragger.cpp.
isShownPlanarTranslationZX()
bool SoFCCSysDragger::isShownPlanarTranslationZX ()
is zx planar translation dragger shown.
Definition at line 1739 of file SoFCCSysDragger.cpp.
isShownRotationX()
bool SoFCCSysDragger::isShownRotationX ()
is x rotation dragger shown.
Definition at line 1794 of file SoFCCSysDragger.cpp.
isShownRotationY()
bool SoFCCSysDragger::isShownRotationY ()
is x rotation dragger shown.
Definition at line 1799 of file SoFCCSysDragger.cpp.
isShownRotationZ()
bool SoFCCSysDragger::isShownRotationZ ()
is x rotation dragger shown.
Definition at line 1804 of file SoFCCSysDragger.cpp.
isShownTranslationX()
bool SoFCCSysDragger::isShownTranslationX ()
is x translation dragger shown.
Definition at line 1664 of file SoFCCSysDragger.cpp.
isShownTranslationY()
bool SoFCCSysDragger::isShownTranslationY ()
is y translation dragger shown.
Definition at line 1669 of file SoFCCSysDragger.cpp.
isShownTranslationZ()
bool SoFCCSysDragger::isShownTranslationZ ()
is z translation dragger shown.
Definition at line 1674 of file SoFCCSysDragger.cpp.
rotationSensorCB()
void SoFCCSysDragger::rotationSensorCB (void * f, SoSensor *) static protected
Definition at line 1430 of file SoFCCSysDragger.cpp.
References SCL.SimpleDataTypes::f.
Referenced by setUpConnections(), and SoFCCSysDragger().
setAxisColors()
void SoFCCSysDragger::setAxisColors (unsigned long x, unsigned long y, unsigned long z)
set the axis colors.
Definition at line 1593 of file SoFCCSysDragger.cpp.
References InitGui::t, MovieTool::x, and MovieTool::y.
Referenced by SoFCCSysDragger().
setUpAutoScale()
void SoFCCSysDragger::setUpAutoScale (SoCamera * cameraIn)
used to setup the auto scaling of dragger.
Definition at line 1466 of file SoFCCSysDragger.cpp.
References autoScaleResult, cameraCB(), cameraSensor, and draggerSize.
setUpConnections()
SbBool SoFCCSysDragger::setUpConnections (SbBool onoff, SbBool doitalways = FALSE) override protected
Definition at line 1352 of file SoFCCSysDragger.cpp.
References rotation, rotationSensor, rotationSensorCB(), translation, translationSensor, and translationSensorCB().
Referenced by SoFCCSysDragger().
showPlanarTranslationXY()
void SoFCCSysDragger::showPlanarTranslationXY ()
show the xy planar translation dragger.
Definition at line 1697 of file SoFCCSysDragger.cpp.
showPlanarTranslationYZ()
void SoFCCSysDragger::showPlanarTranslationYZ ()
show the yz planar translation dragger.
Definition at line 1702 of file SoFCCSysDragger.cpp.
showPlanarTranslationZX()
void SoFCCSysDragger::showPlanarTranslationZX ()
show the zx planar translation dragger.
Definition at line 1707 of file SoFCCSysDragger.cpp.
showRotationX()
void SoFCCSysDragger::showRotationX ()
show the x rotation dragger.
Definition at line 1762 of file SoFCCSysDragger.cpp.
showRotationY()
void SoFCCSysDragger::showRotationY ()
show the y rotation dragger.
Definition at line 1767 of file SoFCCSysDragger.cpp.
showRotationZ()
void SoFCCSysDragger::showRotationZ ()
show the z rotation dragger.
Definition at line 1772 of file SoFCCSysDragger.cpp.
showTranslationX()
void SoFCCSysDragger::showTranslationX ()
show the x translation dragger.
Definition at line 1632 of file SoFCCSysDragger.cpp.
showTranslationY()
void SoFCCSysDragger::showTranslationY ()
show the y translation dragger.
Definition at line 1637 of file SoFCCSysDragger.cpp.
showTranslationZ()
void SoFCCSysDragger::showTranslationZ ()
show the z translation dragger.
Definition at line 1642 of file SoFCCSysDragger.cpp.
translationSensorCB()
void SoFCCSysDragger::translationSensorCB (void * f, SoSensor *) static protected
Definition at line 1418 of file SoFCCSysDragger.cpp.
References SCL.SimpleDataTypes::f.
Referenced by setUpConnections(), and SoFCCSysDragger().
valueChangedCB()
void SoFCCSysDragger::valueChangedCB (void * , SoDragger * d) static protected
Definition at line 1442 of file SoFCCSysDragger.cpp.
Referenced by SoFCCSysDragger(), and ~SoFCCSysDragger().
Member Data Documentation
autoScaleResult
SoSFFloat Gui::SoFCCSysDragger::autoScaleResult
result of autoscale calculation and used by childdraggers. Don't use.
Definition at line 299 of file SoFCCSysDragger.h.
Referenced by setUpAutoScale(), and SoFCCSysDragger().
cameraSensor
SoFieldSensor Gui::SoFCCSysDragger::cameraSensor protected
Definition at line 364 of file SoFCCSysDragger.h.
Referenced by idleCB(), setUpAutoScale(), SoFCCSysDragger(), and ~SoFCCSysDragger().
draggerSize
SoSFFloat Gui::SoFCCSysDragger::draggerSize
Overall scale of dragger node.
When using autoscale mode, this represents normalized device coordinates (0.0 to 1.0). A value of 0.05 is a good place to start. When NOT using autoscale mode, scale represents a traditional scale and a value of 1.0 is a good place to start.
Definition at line 298 of file SoFCCSysDragger.h.
Referenced by setUpAutoScale(), and SoFCCSysDragger().
idleSensor
SoIdleSensor Gui::SoFCCSysDragger::idleSensor
might be overkill, but want to make sure of performance.
Definition at line 301 of file SoFCCSysDragger.h.
Referenced by cameraCB(), SoFCCSysDragger(), and ~SoFCCSysDragger().
rotation
SoSFRotation Gui::SoFCCSysDragger::rotation
initial rotation and reflects single precision movement.
Definition at line 280 of file SoFCCSysDragger.h.
Referenced by femtaskpanels.task_element_rotation1D._TaskPanel::accept(), femtaskpanels.task_element_rotation1D._TaskPanel::rotation_changed(), setUpConnections(), and SoFCCSysDragger().
rotationIncrement
SoSFDouble Gui::SoFCCSysDragger::rotationIncrement
radians set from outside and used for rounding.
Definition at line 281 of file SoFCCSysDragger.h.
Referenced by SoFCCSysDragger().
rotationIncrementCountX
SoSFInt32 Gui::SoFCCSysDragger::rotationIncrementCountX
used from outside for rotation x steps.
Definition at line 282 of file SoFCCSysDragger.h.
Referenced by clearIncrementCounts(), and SoFCCSysDragger().
rotationIncrementCountY
SoSFInt32 Gui::SoFCCSysDragger::rotationIncrementCountY
used from outside for rotation y steps.
Definition at line 283 of file SoFCCSysDragger.h.
Referenced by clearIncrementCounts(), and SoFCCSysDragger().
rotationIncrementCountZ
SoSFInt32 Gui::SoFCCSysDragger::rotationIncrementCountZ
used from outside for rotation z steps.
Definition at line 284 of file SoFCCSysDragger.h.
Referenced by clearIncrementCounts(), and SoFCCSysDragger().
rotationSensor
SoFieldSensor Gui::SoFCCSysDragger::rotationSensor protected
Definition at line 363 of file SoFCCSysDragger.h.
Referenced by setUpConnections(), SoFCCSysDragger(), and ~SoFCCSysDragger().
translation
SoSFVec3f Gui::SoFCCSysDragger::translation
initial translation and reflects single precision movement.
Definition at line 274 of file SoFCCSysDragger.h.
Referenced by setUpConnections(), and SoFCCSysDragger().
translationIncrement
SoSFDouble Gui::SoFCCSysDragger::translationIncrement
set from outside used for rounding.
Definition at line 275 of file SoFCCSysDragger.h.
Referenced by SoFCCSysDragger().
translationIncrementCountX
SoSFInt32 Gui::SoFCCSysDragger::translationIncrementCountX
used from outside for translation x steps.
Definition at line 276 of file SoFCCSysDragger.h.
Referenced by clearIncrementCounts(), and SoFCCSysDragger().
translationIncrementCountY
SoSFInt32 Gui::SoFCCSysDragger::translationIncrementCountY
used from outside for translation y steps.
Definition at line 277 of file SoFCCSysDragger.h.
Referenced by clearIncrementCounts(), and SoFCCSysDragger().
translationIncrementCountZ
SoSFInt32 Gui::SoFCCSysDragger::translationIncrementCountZ
used from outside for translation z steps.
Definition at line 278 of file SoFCCSysDragger.h.
Referenced by clearIncrementCounts(), and SoFCCSysDragger().
translationSensor
SoFieldSensor Gui::SoFCCSysDragger::translationSensor protected
Definition at line 362 of file SoFCCSysDragger.h.
Referenced by setUpConnections(), SoFCCSysDragger(), and ~SoFCCSysDragger().
xAxisLabel
SoSFString Gui::SoFCCSysDragger::xAxisLabel
label for X axis
Definition at line 286 of file SoFCCSysDragger.h.
Referenced by SoFCCSysDragger().
yAxisLabel
SoSFString Gui::SoFCCSysDragger::yAxisLabel
label for Y axis
Definition at line 287 of file SoFCCSysDragger.h.
Referenced by SoFCCSysDragger().
zAxisLabel
SoSFString Gui::SoFCCSysDragger::zAxisLabel
label for Z axis
Definition at line 288 of file SoFCCSysDragger.h.
Referenced by SoFCCSysDragger().
The documentation for this class was generated from the following files:
SoFCCSysDragger.h
SoFCCSysDragger.cpp