FreeCAD: Gui::LocationDialogUi< Ui > Class Template Reference
Gui::LocationDialogUi< Ui > Class Template Reference
#include <InputVector.h>
Public Member Functions
LocationDialogUi (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~LocationDialogUi () override=default
void retranslate ()
void setPosition (const Base::Vector3d &v)
Base::Vector3d getPosition () const
Base::Vector3d getDirection () const override
Public Member Functions inherited from Gui::LocationDialog
Base::Vector3d getUserDirection (bool *ok=nullptr) const
Protected Member Functions
void changeEvent (QEvent *e) override
Protected Member Functions inherited from Gui::LocationDialog
LocationDialog (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~LocationDialog () override
Detailed Description
template<class Ui>
class Gui::LocationDialogUi< Ui >
This is the template class that implements the interface of LocationDialog. The template argument can be the Ui interface class built by uic out of a .ui file. This class might be very useful for dialogs where a combo box is used to define a direction vector by the user. For such classes the programmer doesn't have to write a subclass to implement the appropriate signals/slots. Instead it's possible to omit this further class and use LocationDialogUi parametrized with the generated Ui class.
Author
Werner Mayer
Definition at line 113 of file InputVector.h.
Constructor & Destructor Documentation
LocationDialogUi()
template<class Ui > Gui::LocationDialogUi< Ui >::LocationDialogUi (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) inline
Definition at line 116 of file InputVector.h.
References Gui::LocationDialogUi< Ui >::retranslate().
~LocationDialogUi()
template<class Ui > Gui::LocationDialogUi< Ui >::~LocationDialogUi () override default
Member Function Documentation
changeEvent()
template<class Ui > void Gui::LocationDialogUi< Ui >::changeEvent (QEvent * e) inline override protected virtual
Implements Gui::LocationDialog.
Definition at line 177 of file InputVector.h.
References SCL.SimpleDataTypes::e, and Gui::LocationDialogUi< Ui >::retranslate().
getDirection()
template<class Ui > Base::Vector3d Gui::LocationDialogUi< Ui >::getDirection () const inline override virtual
Implements Gui::LocationDialog.
Definition at line 165 of file InputVector.h.
getPosition()
template<class Ui > Base::Vector3d Gui::LocationDialogUi< Ui >::getPosition () const inline
Definition at line 158 of file InputVector.h.
retranslate()
template<class Ui > void Gui::LocationDialogUi< Ui >::retranslate () inline
Definition at line 123 of file InputVector.h.
References NavigationIndicatorGui::retranslateUi(), and src.Mod.AddonManager.Addon::translate.
Referenced by Gui::LocationDialogUi< Ui >::changeEvent(), and Gui::LocationDialogUi< Ui >::LocationDialogUi().
setPosition()
template<class Ui > void Gui::LocationDialogUi< Ui >::setPosition (const Base::Vector3d & v) inline
Definition at line 151 of file InputVector.h.
References TestSpreadsheet::v.
The documentation for this class was generated from the following file:
InputVector.h