FreeCAD: PartFeature.cpp File Reference
PartFeature.cpp File Reference
#include "PreCompiled.h"
#include <sstream>
#include <Bnd_Box.hxx>
#include <BRepAdaptor_Curve.hxx>
#include <Mod/Part/App/FCBRepAlgoAPI_Fuse.h>
#include <Mod/Part/App/FCBRepAlgoAPI_Common.h>
#include <BRepBndLib.hxx>
#include <BRepBuilderAPI_MakeEdge.hxx>
#include <BRepBuilderAPI_MakeFace.hxx>
#include <BRepBuilderAPI_MakeVertex.hxx>
#include <BRepBuilderAPI_MakeShape.hxx>
#include <BRepExtrema_DistShapeShape.hxx>
#include <BRepGProp.hxx>
#include <BRepGProp_Face.hxx>
#include <BRepIntCurveSurface_Inter.hxx>
#include <gce_MakeDir.hxx>
#include <gce_MakeLin.hxx>
#include <gp_Ax1.hxx>
#include <gp_Dir.hxx>
#include <gp_Pln.hxx>
#include <gp_Trsf.hxx>
#include <GProp_GProps.hxx>
#include <IntCurveSurface_IntersectionPoint.hxx>
#include <Precision.hxx>
#include <Standard_Failure.hxx>
#include <Standard_Version.hxx>
#include <TopExp.hxx>
#include <TopExp_Explorer.hxx>
#include <TopoDS.hxx>
#include <TopTools_IndexedMapOfShape.hxx>
#include <TopTools_ListIteratorOfListOfShape.hxx>
#include <App/Application.h>
#include <App/Document.h>
#include <App/FeaturePythonPyImp.h>
#include <App/GeoFeature.h>
#include <App/Link.h>
#include <App/GeoFeatureGroupExtension.h>
#include <App/ElementNamingUtils.h>
#include <App/Placement.h>
#include <App/Datums.h>
#include <Base/Exception.h>
#include <Base/Placement.h>
#include <Base/Rotation.h>
#include <Base/Stream.h>
#include <Base/Tools.h>
#include <Mod/Material/App/MaterialManager.h>
#include "Geometry.h"
#include "PartFeature.h"
#include "PartFeaturePy.h"
#include "PartPyCXX.h"
#include "TopoShapePy.h"
#include "Tools.h"
Classes
struct Mesh::Feature::ElementCache
Namespaces
App
a class to assist with exporting sketches to dxf
Functions
static std::vector< std::pair< long, Data::MappedName > > getElementSource (App::DocumentObject *owner, TopoShape shape, const Data::MappedName &name, char type)
static TopoShape _getTopoShape (const App::DocumentObject *obj, const char *subname, bool needSubElement, Base::Matrix4D *pmat, App::DocumentObject **powner, bool resolveLink, bool noElementMap, const std::set< std::string > hiddens, const App::DocumentObject *lastLink)
Function Documentation
_getTopoShape()
static TopoShape _getTopoShape (const App::DocumentObject * obj, const char * subname, bool needSubElement, Base::Matrix4D * pmat, App::DocumentObject ** powner, bool resolveLink, bool noElementMap, const std::set< std::string > hiddens, const App::DocumentObject * lastLink) static
Definition at line 890 of file PartFeature.cpp.
References Data::findElementName(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), App::ExtensionContainer::getExtensionByType(), App::DocumentObject::getID(), App::DocumentObject::getLinkedObject(), Part::PropertyShapeCache::getShape(), App::Document::getStringHasher(), App::DocumentObject::getSubObject(), App::DocumentObject::getSubObjects(), Part::Feature::getTopoShape(), Data::ComplexGeoData::Hasher, Base::Matrix4D::hasScale(), Base::BaseClass::isDerivedFrom(), App::DocumentObject::isElementVisible(), App::GeoFeatureGroupExtension::isNonGeoGroup(), Part::TopoShape::isNull(), Part::TopoShape::makeElementCompound(), Part::TopoShape::makeElementTransform(), Base::NoScaling, src.Mod.Test.testPathArray::o, Init::parent, WorkingPlane::plane, Data::POSTFIX_INDEX, Part::TopoShape::resetElementMap(), App::DocumentObject::resolve(), Part::TopoShape::reTagElementMap(), Part::PropertyShapeCache::setShape(), Data::ComplexGeoData::Tag, Dice3DS.dom3ds::tag, Part::TopoShape::transformShape(), Path.Post.scripts.grbl_post::type, and Base::Uniform.
Referenced by Part::TopoShapeCache::Ancestry::getTopoShape(), Part::Feature::getTopoShape(), and Part::TopoShapeCache::Ancestry::getTopoShapes().
getElementSource()
static std::vector<std::pair<long, Data::MappedName> > getElementSource (App::DocumentObject * owner, TopoShape shape, const Data::MappedName & name, char type) static
Definition at line 487 of file PartFeature.cpp.
References KDL::abs(), toolbit-attributes::doc, Data::ComplexGeoData::elementType(), FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, FC_WARN, Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), Data::ComplexGeoData::getElementHistory(), App::DocumentObject::getLinkedObject(), App::Document::getStringHasher(), Part::Feature::getTopoShape(), Data::ComplexGeoData::Hasher, Base::BaseClass::isDerivedFrom(), Part::TopoShape::setShape(), Dice3DS.dom3ds::tag, and Path.Post.scripts.grbl_post::type.
Referenced by Part::Feature::getRelatedElements().