FreeCAD: MeshCore::MeshPointArray Class Reference
MeshCore::MeshPointArray Class Reference
#include <Elements.h>
Public Types
using _TIterator = std::vector< MeshPoint >::iterator
using _TConstIterator = std::vector< MeshPoint >::const_iterator
Public Member Functions
Construction
MeshPointArray ()=default
MeshPointArray (PointIndex ulSize)
MeshPointArray (const MeshPointArray &)
copy-constructor
MeshPointArray (MeshPointArray &&)
~MeshPointArray ()=default
Flag state
Note
All flag methods are const as they do NOT change the actual properties of the object
void SetFlag (MeshPoint::TFlagType tF) const
Sets the flag for all points.
void ResetFlag (MeshPoint::TFlagType tF) const
Resets the flag for all points.
void ResetInvalid () const
Sets all points invalid.
void SetProperty (unsigned long ulVal) const
Sets the property for all points.
MeshPointArray & operator= (const MeshPointArray &rclPAry)
MeshPointArray & operator= (MeshPointArray &&rclPAry)
void Transform (const Base::Matrix4D &)
PointIndex Get (const MeshPoint &rclPoint)
PointIndex GetOrAddIndex (const MeshPoint &rclPoint)
Detailed Description
Stores all data points of the mesh structure.
Definition at line 704 of file Elements.h.
Member Typedef Documentation
_TConstIterator
using MeshCore::MeshPointArray::_TConstIterator = std::vector<MeshPoint>::const_iterator
Definition at line 709 of file Elements.h.
_TIterator
using MeshCore::MeshPointArray::_TIterator = std::vector<MeshPoint>::iterator
Definition at line 708 of file Elements.h.
Constructor & Destructor Documentation
MeshPointArray() [1/4]
MeshCore::MeshPointArray::MeshPointArray () default
MeshPointArray() [2/4]
MeshCore::MeshPointArray::MeshPointArray (PointIndex ulSize) inline explicit
Definition at line 716 of file Elements.h.
MeshPointArray() [3/4]
MeshPointArray::MeshPointArray (const MeshPointArray &) default
copy-constructor
MeshPointArray() [4/4]
MeshPointArray::MeshPointArray (MeshPointArray &&) default
~MeshPointArray()
MeshCore::MeshPointArray::~MeshPointArray () default
Member Function Documentation
Get()
PointIndex MeshPointArray::Get (const MeshPoint & rclPoint)
Searches for the first point index Two points are equal if the distance is less than EPSILON. If no such points is found POINT_INDEX_MAX is returned.
Definition at line 43 of file Elements.cpp.
References DraftVecUtils::find(), and MeshCore::POINT_INDEX_MAX.
GetOrAddIndex()
PointIndex MeshPointArray::GetOrAddIndex (const MeshPoint & rclPoint)
Searches for the first point index Two points are equal if the distance is less than EPSILON. If no such points is found the point is added to the array at end and its index is returned.
Definition at line 55 of file Elements.cpp.
References MeshCore::POINT_INDEX_MAX.
Referenced by MeshCore::MeshKernel::AddFacet().
operator=() [1/2]
MeshPointArray & MeshPointArray::operator= (const MeshPointArray & rclPAry) default
operator=() [2/2]
MeshPointArray & MeshPointArray::operator= (MeshPointArray && rclPAry) default
ResetFlag()
void MeshPointArray::ResetFlag (MeshPoint::TFlagType tF) const
Resets the flag for all points.
Definition at line 74 of file Elements.cpp.
References SplineSurface::i.
Referenced by MeshCore::MeshRemoveNeedles::Fixup(), MeshCore::MeshKernel::GetPointFacets(), MeshCore::MeshSearchNeighbours::NeighboursFacetFromFacet(), MeshCore::MeshSearchNeighbours::NeighboursFromFacet(), MeshCore::MeshAlgorithm::ResetPointFlag(), and MeshCore::MeshAlgorithm::ResetPointsFlag().
ResetInvalid()
void MeshPointArray::ResetInvalid () const
Sets all points invalid.
Definition at line 88 of file Elements.cpp.
Referenced by MeshCore::MeshKernel::AddFacets(), MeshCore::MeshKernel::DeleteFacets(), MeshCore::MeshKernel::DeletePoints(), MeshCore::MeshRemoveNeedles::Fixup(), and MeshCore::MeshCleanup::RemoveInvalids().
SetFlag()
void MeshPointArray::SetFlag (MeshPoint::TFlagType tF) const
Sets the flag for all points.
Definition at line 67 of file Elements.cpp.
References SplineSurface::i.
Referenced by MeshCore::MeshKernel::AddFacets(), MeshCore::MeshSearchNeighbours::ExpandRadius(), MeshCore::MeshAlgorithm::GetFacetsBorders(), MeshCore::MeshKernel::GetPointFacets(), MeshCore::MeshCleanup::RemoveInvalids(), MeshCore::MeshAlgorithm::SetPointFlag(), and MeshCore::MeshAlgorithm::SetPointsFlag().
SetProperty()
void MeshPointArray::SetProperty (unsigned long ulVal) const
Sets the property for all points.
Definition at line 81 of file Elements.cpp.
Referenced by MeshCore::MeshKernel::DeleteFacets(), MeshCore::MeshKernel::DeletePoints(), and MeshCore::ReaderOBJ::Load().
Transform()
void MeshPointArray::Transform (const Base::Matrix4D & mat)
Definition at line 99 of file Elements.cpp.
References Base::Matrix4D::multVec().
The documentation for this class was generated from the following files:
Elements.h
Elements.cpp