FreeCAD: Base::Axis Class Reference
Base::Axis Class Reference
#include <Axis.h>
Public Member Functions
Axis ()=default
default constructor
Axis (const Axis &)=default
Axis (Axis &&)=default
Axis (const Vector3d &Orig, const Vector3d &Dir)
~Axis ()=default
Destruction.
const Vector3d & getBase () const
const Vector3d & getDirection () const
void setBase (const Vector3d &Orig)
void setDirection (const Vector3d &Dir)
void reverse ()
Axis reversed () const
void move (const Vector3d &MovVec)
Axis & operator*= (const Placement &plm)
Axis operator* (const Placement &plm) const
bool operator== (const Axis &) const
bool operator!= (const Axis &) const
Axis & operator= (const Axis &)=default
Axis & operator= (Axis &&)=default
Detailed Description
The Axis class.
Definition at line 56 of file Axis.h.
Constructor & Destructor Documentation
Axis() [1/4]
Base::Axis::Axis () default
default constructor
Axis() [2/4]
Base::Axis::Axis (const Axis &) default
Axis() [3/4]
Base::Axis::Axis (Axis &&) default
Axis() [4/4]
Axis::Axis (const Vector3d & Orig, const Vector3d & Dir)
Definition at line 29 of file Axis.cpp.
~Axis()
Base::Axis::~Axis () default
Destruction.
Member Function Documentation
getBase()
const Vector3d& Base::Axis::getBase () const inline
Definition at line 87 of file Axis.h.
Referenced by Base::CoordinateSystem::displacement(), PartDesign::ProfileBased::getAxis(), PartDesign::Mirrored::getTransformations(), PartDesign::PolarPattern::getTransformations(), and Base::CoordinateSystem::transformTo().
getDirection()
const Vector3d& Base::Axis::getDirection () const inline
Definition at line 91 of file Axis.h.
Referenced by Base::CoordinateSystem::displacement(), PartDesign::ProfileBased::getAxis(), PartDesign::LinearPattern::getTransformations(), PartDesign::Mirrored::getTransformations(), PartDesign::PolarPattern::getTransformations(), Base::CoordinateSystem::setXDirection(), Base::CoordinateSystem::setYDirection(), and Base::CoordinateSystem::transform().
move()
void Axis::move (const Vector3d & MovVec)
Definition at line 46 of file Axis.cpp.
Referenced by draftguitools.gui_circulararray.CircularArray::Activated(), and draftguitools.gui_polararray.PolarArray::Activated().
operator!=()
bool Axis::operator!= (const Axis & that) const
Definition at line 56 of file Axis.cpp.
operator*()
Axis Axis::operator* (const Placement & plm) const
Definition at line 68 of file Axis.cpp.
operator*=()
Axis & Axis::operator*= (const Placement & plm)
Operators.
Definition at line 61 of file Axis.cpp.
References Base::Placement::getRotation(), Base::Placement::multVec(), and Base::Rotation::multVec().
operator=() [1/2]
Axis& Base::Axis::operator= (Axis &&) default
operator=() [2/2]
Axis& Base::Axis::operator= (const Axis &) default
operator==()
bool Axis::operator== (const Axis & that) const
Definition at line 51 of file Axis.cpp.
reverse()
void Axis::reverse ()
Definition at line 34 of file Axis.cpp.
Referenced by reversed().
reversed()
Axis Axis::reversed () const
Definition at line 39 of file Axis.cpp.
References reverse().
setBase()
void Base::Axis::setBase (const Vector3d & Orig) inline
Definition at line 95 of file Axis.h.
Referenced by PartDesign::LinearPattern::getTransformations(), PartDesign::Mirrored::getTransformations(), Base::CoordinateSystem::setAxes(), and Base::CoordinateSystem::setPlacement().
setDirection()
void Base::Axis::setDirection (const Vector3d & Dir) inline
Definition at line 99 of file Axis.h.
Referenced by PartDesign::LinearPattern::getTransformations(), PartDesign::Mirrored::getTransformations(), Base::CoordinateSystem::setAxes(), Base::CoordinateSystem::setPlacement(), and Base::CoordinateSystem::transform().
The documentation for this class was generated from the following files:
Axis.h
Axis.cpp