FreeCAD: TechDrawGui::QGIRichAnno Class Reference
TechDrawGui::QGIRichAnno Class Reference
#include <QGIRichAnno.h>
Public Types
enum { Type = QGraphicsItem::UserType + 233 }
Public Types inherited from TechDrawGui::QGIView
enum { Type = QGraphicsItem::UserType + 101 }
Public Member Functions
QGIRichAnno ()
~QGIRichAnno () override=default
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QRectF boundingRect () const override
QRectF frameRect () const
void drawBorder () override
void updateView (bool update=false) override
void setTextItem ()
virtual TechDraw::DrawRichAnno * getFeature ()
QPen rectPen () const
void setExportingPdf (bool b)
bool getExportingPdf () const
void setExportingSvg (bool b)
bool getExportingSvg () const
Public Member Functions inherited from TechDrawGui::QGIView
QGIView ()
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
const char * getViewName () const
const std::string getViewNameAsString () const
void setViewFeature (TechDraw::DrawView *obj)
TechDraw::DrawView * getViewObject () const
MDIViewPage * getMDIViewPage () const
double getScale ()
void hideFrame ()
virtual bool getFrameState ()
virtual void toggleCache (bool state)
virtual void isVisible (bool state)
virtual bool isVisible ()
virtual bool getGroupSelection ()
virtual void setGroupSelection (bool isSelected)
virtual void setGroupSelection (bool isSelected, const std::vector< std::string > &subNames)
virtual void drawCaption ()
virtual void rotateView ()
void makeMark (double xPos, double yPos, QColor color=Qt::red)
void makeMark (Base::Vector3d pos, QColor color=Qt::red)
void makeMark (QPointF pos, QColor color=Qt::red)
void setPosition (qreal xPos, qreal yPos)
qreal getY ()
bool isInnerView () const
void isInnerView (bool state)
QGIViewClip * getClipGroup ()
bool isSnapping ()
void snapPosition (QPointF &position)
void snapSectionView (const TechDraw::DrawViewSection *sectionView, QPointF &newPosition)
Base::Vector3d projItemPagePos (TechDraw::DrawViewPart *item)
void alignTo (QGraphicsItem *, const QString &alignment)
QColor prefNormalColor ()
QColor getNormalColor ()
void setNormalColor (QColor color)
QColor getPreColor ()
QColor getSelectColor ()
QColor getCurrentColor ()
void setCurrentColor (QColor color)
QColor getSettingColor ()
void setSettingColor (QColor color)
virtual void setStack (int z)
virtual void setStackFromVP ()
QFont getFont ()
void setFont (QFont font)
virtual void removeChild (QGIView *child)
virtual void addArbitraryItem (QGraphicsItem *qgi)
virtual void switchParentItem (QGIView *targetParent)
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
Protected Member Functions
void draw () override
void setLineSpacing (int lineSpacing)
QFont prefFont (void)
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
QString convertTextSizes (const QString &inHtml) const
Protected Member Functions inherited from TechDrawGui::QGIView
QGIView * getQGIVByName (std::string name)
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QRectF customChildrenBoundingRect () const
void dumpRect (const char *text, QRectF rect)
Base::Reference< ParameterGrp > getParmGroupCol ()
Protected Attributes
bool m_isExportingPdf
bool m_isExportingSvg
QGCustomText * m_text
bool m_hasHover
QGCustomRect * m_rect
Additional Inherited Members
Static Public Member Functions inherited from TechDrawGui::QGIView
static Gui::ViewProvider * getViewProvider (App::DocumentObject *obj)
static ViewProviderPage * getViewProviderPage (TechDraw::DrawView *dView)
static int calculateFontPixelSize (double sizeInMillimetres)
static int calculateFontPixelWidth (const QFont &font)
static QString getPrefFont ()
static double getPrefFontSize ()
static double getDimFontSize ()
static int exactFontSize (std::string fontFamily, double nominalSize)
Static Public Attributes inherited from TechDrawGui::QGIView
static const double DefaultFontSizeInMM = 5.0
Detailed Description
Definition at line 53 of file QGIRichAnno.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 58 of file QGIRichAnno.h.
Constructor & Destructor Documentation
QGIRichAnno()
QGIRichAnno::QGIRichAnno () explicit
Definition at line 59 of file QGIRichAnno.cpp.
References TechDrawGui::QGCustomRect::centerAt(), TechDrawGui::QGCustomText::centerAt(), ZVALUE::DIMENSION, m_rect, and m_text.
~QGIRichAnno()
TechDrawGui::QGIRichAnno::~QGIRichAnno () override default
Member Function Documentation
boundingRect()
QRectF QGIRichAnno::boundingRect () const override
Definition at line 287 of file QGIRichAnno.cpp.
References m_rect, and m_text.
convertTextSizes()
QString QGIRichAnno::convertTextSizes (const QString & inHtml) const protected
convert the word processing font size spec (in typographic points) to scene units for the screen or pdf rendering or to CSS pixels for Svg rendering
Definition at line 235 of file QGIRichAnno.cpp.
References getExportingSvg(), TechDrawGui::Rez::getRezFactor(), RobotExample::pos, and src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression.
Referenced by setTextItem().
draw()
void QGIRichAnno::draw () override protected virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 123 of file QGIRichAnno.cpp.
References TechDrawGui::QGIView::draw(), getFeature(), TechDrawGui::QGIView::getViewProvider(), TechDrawGui::QGIView::isVisible(), and setTextItem().
Referenced by updateView().
drawBorder()
void QGIRichAnno::drawBorder () override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 116 of file QGIRichAnno.cpp.
frameRect()
QRectF TechDrawGui::QGIRichAnno::frameRect () const
getExportingPdf()
bool TechDrawGui::QGIRichAnno::getExportingPdf () const inline
Definition at line 79 of file QGIRichAnno.h.
getExportingSvg()
bool TechDrawGui::QGIRichAnno::getExportingSvg () const inline
Definition at line 81 of file QGIRichAnno.h.
Referenced by convertTextSizes(), and setTextItem().
getFeature()
TechDraw::DrawRichAnno * QGIRichAnno::getFeature () virtual
Definition at line 280 of file QGIRichAnno.cpp.
References TechDrawGui::QGIView::getViewObject().
Referenced by draw(), and setTextItem().
mouseDoubleClickEvent()
void QGIRichAnno::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 332 of file QGIRichAnno.cpp.
References TechDraw::DrawRichAnno::AnnoText, App::Application::closeActiveTransaction(), draftgeoutils.intersections::connect(), src.Mod.PartDesign.Scripts.Gear::dialog, MRichTextEdit::editorFinished(), App::GetApplication(), App::PropertyString::getValue(), TechDrawGui::QGIView::getViewObject(), MRichTextEdit::saveText(), App::Application::setActiveTransaction(), and App::PropertyString::setValue().
paint()
void QGIRichAnno::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 295 of file QGIRichAnno.cpp.
References TechDrawGui::QGIView::paint().
prefFont()
QFont QGIRichAnno::prefFont (void) protected
Definition at line 327 of file QGIRichAnno.cpp.
References TechDrawGui::PreferencesGui::labelFontQFont().
rectPen()
QPen QGIRichAnno::rectPen () const
Definition at line 305 of file QGIRichAnno.cpp.
References App::Color::asValue(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), and TechDrawGui::Rez::guiX().
Referenced by setTextItem().
setExportingPdf()
void TechDrawGui::QGIRichAnno::setExportingPdf (bool b) inline
Definition at line 78 of file QGIRichAnno.h.
References SCL.SimpleDataTypes::b.
setExportingSvg()
void TechDrawGui::QGIRichAnno::setExportingSvg (bool b) inline
Definition at line 80 of file QGIRichAnno.h.
References SCL.SimpleDataTypes::b.
Referenced by TechDrawGui::QGSPage::setExportingSvg().
setLineSpacing()
void QGIRichAnno::setLineSpacing (int lineSpacing) protected
Definition at line 195 of file QGIRichAnno.cpp.
References Path.Post.scripts.comparams_post::fmt(), TechDrawGui::Rez::guiX(), and m_text.
Referenced by setTextItem().
setTextItem()
void QGIRichAnno::setTextItem ()
Definition at line 146 of file QGIRichAnno.cpp.
References TechDraw::DrawRichAnno::AnnoText, TechDrawGui::QGCustomText::centerAt(), convertTextSizes(), getExportingSvg(), getFeature(), App::PropertyFloat::getValue(), App::PropertyString::getValue(), App::PropertyBool::getValue(), TechDrawGui::Rez::guiX(), m_rect, m_text, TechDraw::DrawRichAnno::MaxWidth, rectPen(), setLineSpacing(), and TechDraw::DrawRichAnno::ShowFrame.
Referenced by draw().
type()
int TechDrawGui::QGIRichAnno::type () const inline override
Definition at line 63 of file QGIRichAnno.h.
updateView()
void QGIRichAnno::updateView (bool update = false) override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 84 of file QGIRichAnno.cpp.
References TechDrawGui::QGCustomRect::centerAt(), TechDrawGui::QGCustomText::centerAt(), draw(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), TechDrawGui::Rez::guiX(), TechDraw::DrawView::isLocked(), m_rect, m_text, MovieTool::x, and MovieTool::y.
Member Data Documentation
m_hasHover
bool TechDrawGui::QGIRichAnno::m_hasHover protected
Definition at line 95 of file QGIRichAnno.h.
m_isExportingPdf
bool TechDrawGui::QGIRichAnno::m_isExportingPdf protected
Definition at line 92 of file QGIRichAnno.h.
m_isExportingSvg
bool TechDrawGui::QGIRichAnno::m_isExportingSvg protected
Definition at line 93 of file QGIRichAnno.h.
m_rect
QGCustomRect* TechDrawGui::QGIRichAnno::m_rect protected
Definition at line 96 of file QGIRichAnno.h.
Referenced by boundingRect(), QGIRichAnno(), setTextItem(), and updateView().
m_text
QGCustomText* TechDrawGui::QGIRichAnno::m_text protected
Definition at line 94 of file QGIRichAnno.h.
Referenced by boundingRect(), QGIRichAnno(), setLineSpacing(), setTextItem(), and updateView().
The documentation for this class was generated from the following files:
QGIRichAnno.h
QGIRichAnno.cpp