FreeCAD: importers.importIFC Namespace Reference
importers.importIFC Namespace Reference
Functions
def export (exportList, filename, colors=None, preferences=None)
def open (filename, skip=[], only=[], root=None)
def insert (srcfile, docname, skip=[], only=[], root=None, preferences=None)
Variables
bool DEBUG = False
bool ZOOMOUT = True
dictionary typesmap
tuple structuralifcobjects
getPreferences = importIFCHelper.getPreferences
Function Documentation
export()
def importers.importIFC.export (exportList, filename, colors = None, preferences = None)
Export the selected objects to IFC format.
The export code is now in a separate module; this call is retained
in this module for compatibility purposes with older scripts.
Definition at line 145 of file importIFC.py.
insert()
def importers.importIFC.insert (srcfile, docname, skip = [], only = [], root = None, preferences = None)
Import the contents of an IFC file in the current active document.
TODO: change the default argument to `None`, instead of `[]`.
This is better because lists are mutable.
Parameters
----------
skip: list
    By default empty list `[]`.
    Can contain a list of ids of objects to be skipped.
only: list
    By default, empty list `[]`.
    Restrict the import to certain object ids; it will also
    get their children.
root: object
    It is used to import only the derivates of a certain element type,
    for example, `'ifcProduct'
Definition at line 170 of file importIFC.py.
References importDXF.addObject(), Path.Post.scripts.uccnc_post.append(), SplineSurface.id, Arch.makeMaterial(), Path.Post.scripts.refactored_centroid_post.str, DraftVecUtils.tup(), and Path.Post.scripts.grbl_post.type.
Referenced by importers.importIFC.open().
open()
def importers.importIFC.open (filename, skip = [], only = [], root = None)
Open an IFC file inside a new document.
TODO: change the default argument to `None`, instead of `[]`.
This is better because lists are mutable.
Most of the work is done in the `insert` function.
Definition at line 155 of file importIFC.py.
References importers.importIFC.insert().
Variable Documentation
DEBUG
bool importers.importIFC.DEBUG = False
Definition at line 55 of file importIFC.py.
getPreferences
importers.importIFC.getPreferences = importIFCHelper.getPreferences
Definition at line 142 of file importIFC.py.
structuralifcobjects
tuple importers.importIFC.structuralifcobjects
Initial value:
 =  (
     "IfcStructuralCurveMember",
     "IfcStructuralSurfaceMember",
     "IfcStructuralPointConnection",
     "IfcStructuralCurveConnection",
     "IfcStructuralSurfaceConnection",
     "IfcStructuralAction",
     "IfcStructuralPointAction",
     "IfcStructuralLinearAction",
     "IfcStructuralLinearActionVarying",
     "IfcStructuralPlanarAction"
 )
Definition at line 128 of file importIFC.py.
typesmap
dictionary importers.importIFC.typesmap
Definition at line 61 of file importIFC.py.
ZOOMOUT
bool importers.importIFC.ZOOMOUT = True
Definition at line 56 of file importIFC.py.