FreeCAD: SketcherGui::SnapManager Class Reference
SketcherGui::SnapManager Class Reference
#include <SnapManager.h>
Public Member Functions
SnapManager (ViewProviderSketch &vp)
~SnapManager ()
bool snap (double &x, double &y)
bool snapAtAngle (double &x, double &y)
bool snapToObject (double &x, double &y)
bool snapToGrid (double &x, double &y)
bool snapToLineMiddle (Base::Vector3d &pointToOverride, const Part::GeomLineSegment *line)
bool snapToArcMiddle (Base::Vector3d &pointToOverride, const Part::GeomArcOfCircle *arc)
void setAngleSnapping (bool enable, Base::Vector2d referencepoint)
Detailed Description
Definition at line 61 of file SnapManager.h.
Constructor & Destructor Documentation
SnapManager()
SnapManager::SnapManager (ViewProviderSketch & vp) explicit
Definition at line 175 of file SnapManager.cpp.
~SnapManager()
SnapManager::~SnapManager ()
Definition at line 185 of file SnapManager.cpp.
Member Function Documentation
setAngleSnapping()
void SnapManager::setAngleSnapping (bool enable, Base::Vector2d referencepoint)
Definition at line 388 of file SnapManager.cpp.
snap()
bool SnapManager::snap (double & x, double & y)
Definition at line 188 of file SnapManager.cpp.
References snapAtAngle(), snapToGrid(), snapToObject(), MovieTool::x, and MovieTool::y.
snapAtAngle()
bool SnapManager::snapAtAngle (double & x, double & y)
Definition at line 219 of file SnapManager.cpp.
References KDL::abs(), KDL::cos(), FreeCADInit::Length, M_PI, KDL::sin(), MovieTool::x, Base::Vector2d::x, MovieTool::y, and Base::Vector2d::y.
Referenced by snap().
snapToArcMiddle()
bool SnapManager::snapToArcMiddle (Base::Vector3d & pointToOverride, const Part::GeomArcOfCircle * arc)
Definition at line 349 of file SnapManager.cpp.
References Base::Vector2d::Angle(), Base::Vector3< float_type >::Length(), M_PI, buildPsets::u, TestSpreadsheet::v, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by snapToObject().
snapToGrid()
bool SnapManager::snapToGrid (double & x, double & y)
Definition at line 307 of file SnapManager.cpp.
References PartGui::ViewProviderGridExtension::getClosestGridPoint(), PartGui::ViewProviderGridExtension::getGridSize(), MovieTool::x, and MovieTool::y.
Referenced by snap().
snapToLineMiddle()
bool SnapManager::snapToLineMiddle (Base::Vector3d & pointToOverride, const Part::GeomLineSegment * line)
Definition at line 333 of file SnapManager.cpp.
References Part::GeomLineSegment::getEndPoint(), Part::GeomLineSegment::getStartPoint(), and FreeCADInit::Length.
Referenced by snapToObject().
snapToObject()
bool SnapManager::snapToObject (double & x, double & y)
Definition at line 236 of file SnapManager.cpp.
References Part::GeomCurve::closestParameter(), SCL.SimpleDataTypes::e, Sketcher::GeoUndef, Sketcher::SketchObject::getGeometry(), Sketcher::SketchObject::getGeoVertexIndex(), Sketcher::SketchObject::getPoint(), SketcherGui::ViewProviderSketch::getSketchObject(), Base::BaseClass::is(), Sketcher::none, Sketcher::RefExt, Sketcher::RtPnt, snapToArcMiddle(), snapToLineMiddle(), Sketcher::start, MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, and Base::Vector3< float_type >::y.
Referenced by snap().
The documentation for this class was generated from the following files:
SnapManager.h
SnapManager.cpp