FreeCAD: PartDesign::SubShapeBinder Class Reference
PartDesign::SubShapeBinder Class Reference
#include <ShapeBinder.h>
Public Types
enum UpdateOption { UpdateNone = 0, UpdateInit = 1, UpdateForced = 2 }
using inherited = Part::Feature
Public Types inherited from App::GeoFeature
enum ElementNameType { Normal = 0, Import = 1, Export = 2 }
Specify the type of element name to return when calling getElementName()
Public Types inherited from App::DocumentObject
enum OutListOption { OutListNoExpression = 1, OutListNoHidden = 2, OutListNoXLinked = 4 }
OutList options.
enum GSReason { GS_DEFAULT, GS_SELECT }
reason of calling getSubObjects()
Public Types inherited from App::ExtensionContainer
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Public Member Functions
SubShapeBinder ()
~SubShapeBinder () override
const char * getViewProviderName () const override
returns the type name of the ViewProvider
void setLinks (std::map< App::DocumentObject *, std::vector< std::string > > &&values, bool reset=false)
void update (UpdateOption options=UpdateNone)
int canLoadPartial () const override
bool canLinkProperties () const override
App::DocumentObject * getSubObject (const char *subname, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const override
Public Member Functions inherited from Part::Feature
Feature ()
Constructor.
~Feature () override
short mustExecute () const override
const App::PropertyComplexGeoData * getPropertyOfGeometry () const override
PyObject * getPyObject () override
getPyObject returns the Python binding object
App::ElementNamePair getElementName (const char *name, ElementNameType type=Normal) const override
TopLoc_Location getLocation () const
App::Material getMaterialAppearance () const override
Virtual function to get an App::Material object describing the appearance.
void setMaterialAppearance (const App::Material &material) override
Virtual function to set the appearance with an App::Material object.
bool getCameraAlignmentDirection (Base::Vector3d &direction, const char *subname) const override
Virtual function to get the camera alignment direction.
const std::vector< std::string > & searchElementCache (const std::string &element, Data::SearchOptions options=Data::SearchOption::CheckGeometry, double tol=1e-7, double atol=1e-10) const override
Public Member Functions inherited from App::GeoFeature
GeoFeature ()
Constructor.
~GeoFeature () override
virtual void transformPlacement (const Base::Placement &transform)
transformPlacement applies transform to placement of this shape. Override this function to propagate the change of placement to base features, for example. By the time of writing this comment, the function was only called by alignment task (Edit->Alignment)
Base::Placement globalPlacement () const
Deprecated. Calculates the placement in the global reference coordinate system.
virtual DocumentObject * getElementOwner (const Data::MappedName &) const
Return the object that owns the shape that contains the give element name.
virtual std::vector< const char * > getElementTypes (bool all=true) const
virtual std::vector< Data::IndexedName > getHigherElements (const char *name, bool silent=false) const
Return the higher level element names of the given element.
Public Member Functions inherited from App::DocumentObject
virtual const char * getViewProviderNameOverride () const
DocumentObject ()
Constructor.
~DocumentObject () override
const char * getDagKey () const
returns a value that uniquely identifies this DocumentObject.
const char * getNameInDocument () const
returns the name which is set in the document for this object (not the name property!)
long getID () const
Return the object ID that is unique within its owner document.
std::string getExportName (bool forced=false) const
returns the name that is safe to be exported to other document
std::string getFullName () const override
Return the object full name of the form DocName::ObjName.
std::string getFullLabel () const
Return the object full label in the form DocName::ObjName.
bool isAttachedToDocument () const override
const char * detachFromDocument () override
App::Document * getDocument () const
gets the document in which this Object is handled
void touch (bool noRecompute=false)
set this document object touched (cause recomputation on dependent features)
bool isTouched () const
test if this document object is touched
void enforceRecompute ()
Enforce this document object to be recomputed.
bool mustRecompute () const
Test if this document object must be recomputed.
void purgeTouched ()
reset this document object touched
bool isError () const
set this feature to error
bool isValid () const
void purgeError ()
remove the error from the object
bool isRecomputing () const
returns true if this objects is currently recomputing
bool isRestoring () const
returns true if this objects is currently restoring from file
bool isRemoving () const
returns true if this objects is currently removed from the document
void freeze ()
set this document object freezed (prevent recomputation)
void unfreeze (bool noRecompute=false)
set this document object unfreezed (and touch it)
bool isFreezed () const
returns true if this objects is currently freezed
unsigned long getStatus () const
return the status bits
bool testStatus (ObjectStatus pos) const
void setStatus (ObjectStatus pos, bool on)
int isExporting () const
virtual int setElementVisible (const char *element, bool visible)
virtual int isElementVisible (const char *element) const
virtual bool hasChildElement () const
return true to activate tree view group object handling and element visibility
const std::vector< App::DocumentObject * > & getOutList () const
returns a list of objects this object is pointing to by Links
std::vector< App::DocumentObject * > getOutList (int option) const
void getOutList (int option, std::vector< App::DocumentObject * > &res) const
std::vector< App::DocumentObject * > getOutListOfProperty (App::Property *) const
returns a list of objects linked by the property
std::vector< App::DocumentObject * > getOutListRecursive () const
returns a list of objects this object is pointing to by Links and all further descended
void clearOutListCache () const
clear internal out list cache
std::vector< std::list< App::DocumentObject * > > getPathsByOutList (App::DocumentObject *to) const
get all possible paths from this to another object following the OutList
const std::vector< App::DocumentObject * > & getInList () const
std::vector< App::DocumentObject * > getInListRecursive () const
get all objects link directly or indirectly to this object
void getInListEx (std::set< App::DocumentObject * > &inSet, bool recursive, std::vector< App::DocumentObject * > *inList=nullptr) const
std::set< App::DocumentObject * > getInListEx (bool recursive) const
DocumentObjectGroup * getGroup () const
get group if object is part of a group, otherwise 0 is returned
bool isInInListRecursive (DocumentObject *objToTest) const
test if this object is in the InList and recursive further down
bool isInInList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the InList
bool isInOutListRecursive (DocumentObject *objToTest) const
test if the given object is in the OutList and recursive further down
bool isInOutList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the OutList
void _removeBackLink (DocumentObject *)
internal, used by PropertyLink to maintain DAG back links
void _addBackLink (DocumentObject *)
internal, used by PropertyLink to maintain DAG back links
bool testIfLinkDAGCompatible (DocumentObject *linkTo) const
testIfLinkIsDAG tests a link that is about to be created for circular references.
bool testIfLinkDAGCompatible (const std::vector< DocumentObject * > &linksTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSubList &linksTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSub &linkTo) const
virtual std::string getElementMapVersion (const App::Property *prop, bool restored=false) const
virtual bool checkElementMapVersion (const App::Property *prop, const char *ver) const
Return true to signal re-generation of geometry element names.
bool recomputeFeature (bool recursive=false)
const char * getStatusString () const
get the status Message
virtual void onLostLinkToObject (DocumentObject *)
std::vector< DocumentObject * > getSubObjectList (const char *subname, std::vector< int > *subsizes=nullptr, bool flatten=false) const
virtual std::vector< std::string > getSubObjects (int reason=0) const
std::vector< std::pair< App::DocumentObject *, std::string > > getParents (int depth=0) const
Obtain top parents and subnames of this object using its InList.
App::DocumentObject * getFirstParent () const
Obtain the first parent group of this object.
virtual DocumentObject * getLinkedObject (bool recurse=true, Base::Matrix4D *mat=nullptr, bool transform=false, int depth=0) const
virtual bool isLink () const
virtual bool isLinkGroup () const
virtual bool allowDuplicateLabel () const
virtual void onBeforeChangeLabel (std::string &newLabel)
void Save (Base::Writer &writer) const override
virtual void setExpression (const ObjectIdentifier &path, std::shared_ptr< App::Expression > expr)
void clearExpression (const ObjectIdentifier &path)
virtual const PropertyExpressionEngine::ExpressionInfo getExpression (const ObjectIdentifier &path) const
virtual void renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &paths)
const std::string & getOldLabel () const
const char * getViewProviderNameStored () const
bool removeDynamicProperty (const char *prop) override
App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
App::DocumentObject * resolve (const char *subname, App::DocumentObject **parent=nullptr, std::string *childName=nullptr, const char **subElement=nullptr, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
App::DocumentObject * resolveRelativeLink (std::string &subname, App::DocumentObject *&link, std::string &linkSub) const
virtual bool adjustRelativeLinks (const std::set< App::DocumentObject * > &inList, std::set< App::DocumentObject * > *visited=nullptr)
virtual void onUpdateElementReference (const Property *)
virtual bool redirectSubName (std::ostringstream &ss, DocumentObject *topParent, DocumentObject *child) const
Public Member Functions inherited from App::TransactionalObject
TransactionalObject ()
Constructor.
~TransactionalObject () override
Public Member Functions inherited from App::ExtensionContainer
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
Property * getPropertyByName (const char *name) const override
find a property by its name
template<typename T >
T * getPropertyByName (const char *name) const
find a property by its name, dynamic cased to specified type
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Attributes
App::PropertyXLinkSubList Support
App::PropertyBool ClaimChildren
App::PropertyBool Relative
App::PropertyBool Fuse
App::PropertyBool MakeFace
App::PropertyEnumeration BindMode
App::PropertyBool PartialLoad
App::PropertyXLink Context
App::PropertyInteger _Version
App::PropertyEnumeration BindCopyOnChange
App::PropertyBool Refine
App::PropertyFloat Offset
App::PropertyEnumeration OffsetJoinType
App::PropertyBool OffsetFill
App::PropertyBool OffsetOpenResult
App::PropertyBool OffsetIntersection
Public Attributes inherited from Part::Feature
PropertyPartShape Shape
Materials::PropertyMaterial ShapeMaterial
Public Attributes inherited from App::GeoFeature
PropertyPlacement Placement
Public Attributes inherited from App::DocumentObject
PropertyString Label
PropertyString Label2
PropertyExpressionEngine ExpressionEngine
PropertyBool Visibility
Allow control visibility status in App name space.
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalBeforeChange
signal before changing a property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalChanged
signal on changed property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalEarlyChanged
signal on changed property of this object before document scoped signalChangedObject
Protected Types
using Connection = boost::signals2::scoped_connection
Protected Member Functions
App::DocumentObjectExecReturn * execute () override
recalculate the feature
void onChanged (const App::Property *prop) override
get called by the container when a property was changed
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, App::Property *prop) override
void onDocumentRestored () override
get called after a document has been fully restored
void setupObject () override
get called after a brand new object was created
void setupCopyOnChange ()
void checkCopyOnChange (const App::Property &prop)
void clearCopiedObjects ()
void checkPropertyStatus ()
void collapseGeoChildren ()
void slotRecomputedObject (const App::DocumentObject &Obj)
Protected Member Functions inherited from Part::Feature
App::DocumentObjectExecReturn * recompute () override
recompute only this object
void onBeforeChange (const App::Property *prop) override
get called before the value is changed
void copyMaterial (Feature *feature)
void copyMaterial (App::DocumentObject *link)
void registerElementCache (const std::string &prefix, PropertyPartShape *prop)
App::ElementNamePair getExportElementName (TopoShape shape, const char *name) const
ShapeHistory buildHistory (BRepBuilderAPI_MakeShape &, TopAbs_ShapeEnum type, const TopoDS_Shape &newS, const TopoDS_Shape &oldS)
ShapeHistory joinHistory (const ShapeHistory &, const ShapeHistory &)
Protected Member Functions inherited from App::GeoFeature
void updateElementReference ()
ElementNamePair _getElementName (const char *name, const Data::MappedElement &mapped) const
Protected Member Functions inherited from App::DocumentObject
App::DocumentObjectExecReturn * executeExtensions ()
void setError ()
void resetError ()
void setDocument (App::Document *doc)
void onEarlyChange (const Property *prop) override
get called by the container when a property was changed
virtual void onUndoRedoFinished ()
get called after an undo/redo transaction is finished
virtual void onSettingDocument ()
get called after setting the document
virtual void unsetupObject ()
get called when object is going to be removed from the document
void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus) override
get called when a property status has changed
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData () const
Protected Attributes
Connection connRecomputedObj
App::Document * contextDoc = nullptr
std::vector< Connection > copyOnChangeConns
bool hasCopyOnChange = true
App::PropertyXLinkSub _CopiedLink
std::vector< App::DocumentObjectT > _CopiedObjs
Protected Attributes inherited from App::DocumentObject
std::bitset< 32 > StatusBits
Py::SmartPtr PythonObject
python object of this class and all descendent
App::Document * _pDoc {nullptr}
pointer to the document this object belongs to
std::string oldLabel
Old label; used for renaming expressions.
const std::string * pcNameInDocument {nullptr}
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Additional Inherited Members
Static Public Member Functions inherited from Part::Feature
static std::list< Data::HistoryItem > getElementHistory (App::DocumentObject *obj, const char *name, bool recursive=true, bool sameType=false)
static QVector< Data::MappedElement > getRelatedElements (App::DocumentObject *obj, const char *name, HistoryTraceType sameType=HistoryTraceType::followTypeChange, bool withCache=true)
static QVector< Data::MappedElement > getElementFromSource (App::DocumentObject *obj, const char *subname, App::DocumentObject *src, const char *srcSub, bool single=false)
static TopoDS_Shape getShape (const App::DocumentObject *obj, const char *subname=nullptr, bool needSubElement=false, Base::Matrix4D *pmat=nullptr, App::DocumentObject **owner=nullptr, bool resolveLink=true, bool transform=true)
static TopoShape getTopoShape (const App::DocumentObject *obj, const char *subname=nullptr, bool needSubElement=false, Base::Matrix4D *pmat=nullptr, App::DocumentObject **owner=nullptr, bool resolveLink=true, bool transform=true, bool noElementMap=false)
static void clearShapeCache ()
static App::DocumentObject * getShapeOwner (const App::DocumentObject *obj, const char *subname=nullptr)
static bool hasShapeOwner (const App::DocumentObject *obj, const char *subname=nullptr)
static Feature * create (const TopoShape &shape, const char *name=nullptr, App::Document *document=nullptr)
static bool isElementMappingDisabled (App::PropertyContainer *container)
static void guessNewLink (std::string &replacementName, DocumentObject *base, const char *oldLink)
Static Public Member Functions inherited from App::GeoFeature
static DocumentObject * resolveElement (const App::DocumentObject *obj, const char *subname, ElementNamePair &elementName, bool append=false, ElementNameType type=Normal, const DocumentObject *filter=nullptr, const char **element=nullptr, GeoFeature **geo=nullptr)
static bool hasMissingElement (const char *subname)
static Base::Placement getPlacementFromProp (DocumentObject *obj, const char *propName)
static Base::Placement getGlobalPlacement (DocumentObject *targetObj, DocumentObject *rootObj, const std::string &sub)
static Base::Placement getGlobalPlacement (DocumentObject *targetObj, PropertyXLinkSub *prop)
static Base::Placement getGlobalPlacement (const DocumentObject *obj)
Static Public Member Functions inherited from App::DocumentObject
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
Check if the subname reference ends with hidden marker.
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Attributes inherited from App::DocumentObject
static DocumentObjectExecReturn * StdReturn
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 98 of file ShapeBinder.h.
Member Typedef Documentation
Connection
using PartDesign::SubShapeBinder::Connection = boost::signals2::scoped_connection protected
Definition at line 165 of file ShapeBinder.h.
inherited
using PartDesign::SubShapeBinder::inherited = Part::Feature
Definition at line 101 of file ShapeBinder.h.
Member Enumeration Documentation
UpdateOption
enum PartDesign::SubShapeBinder::UpdateOption
Enumerator
UpdateNone
UpdateInit
UpdateForced
Definition at line 129 of file ShapeBinder.h.
Constructor & Destructor Documentation
SubShapeBinder()
SubShapeBinder::SubShapeBinder ()
Definition at line 334 of file ShapeBinder.cpp.
References ADD_PROPERTY_TYPE, App::Hidden, App::Property::PartialTrigger, App::Prop_Hidden, App::Prop_None, App::Prop_NoPersist, App::Prop_Output, App::Prop_ReadOnly, and App::Property::ReadOnly.
~SubShapeBinder()
SubShapeBinder::~SubShapeBinder () override
Definition at line 388 of file ShapeBinder.cpp.
References clearCopiedObjects(), and SCL.SimpleDataTypes::e.
Member Function Documentation
canLinkProperties()
bool PartDesign::SubShapeBinder::canLinkProperties () const inline override virtual
Reimplemented from App::DocumentObject.
Definition at line 140 of file ShapeBinder.h.
canLoadPartial()
int PartDesign::SubShapeBinder::canLoadPartial () const inline override virtual
allow partial loading of dependent objects
Returns
Returns 0 means do not support partial loading. 1 means allow dependent objects to be partially loaded, i.e. only create, but not restored. 2 means this object itself can be partially loaded.
Reimplemented from App::DocumentObject.
Definition at line 136 of file ShapeBinder.h.
checkCopyOnChange()
void SubShapeBinder::checkCopyOnChange (const App::Property & prop) protected
Definition at line 995 of file ShapeBinder.cpp.
References BindCopyOnChange, App::DocumentObject::getDocument(), App::Property::getName(), App::PropertyXLinkSubList::getSubListValues(), Base::Persistence::getTypeId(), App::PropertyEnumeration::getValue(), App::LinkBaseExtension::isCopyOnChangeProperty(), App::PropertyEnumeration::setValue(), and Support.
Referenced by onChanged().
checkPropertyStatus()
void SubShapeBinder::checkPropertyStatus () protected
Definition at line 1010 of file ShapeBinder.cpp.
References App::PropertyBool::getValue(), PartialLoad, App::PropertyXLinkSubList::setAllowPartial(), and Support.
Referenced by onChanged(), and setupObject().
clearCopiedObjects()
void SubShapeBinder::clearCopiedObjects () protected
Definition at line 488 of file ShapeBinder.cpp.
References _CopiedLink, _CopiedObjs, App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), src.Mod.Test.testPathArray::o, replaceobj::objs, App::Document::removeObject(), and App::PropertyXLink::setValue().
Referenced by onChanged(), update(), and ~SubShapeBinder().
collapseGeoChildren()
void SubShapeBinder::collapseGeoChildren () protected
Definition at line 888 of file ShapeBinder.cpp.
References App::DocumentObject::getNameInDocument(), App::DocumentObjectT::getObject(), App::PropertyXLinkSubList::getSubListValues(), App::SubObjectT::getSubName(), App::SubObjectT::KeepSubName, RobotExample::l, Path.Post.scripts.opensbp_post::move(), App::SubObjectT::normalize(), App::PropertyXLinkSubList::removeValue(), setLinks(), Support, App::Property::testStatus(), and App::Property::User3.
Referenced by onChanged().
execute()
App::DocumentObjectExecReturn * SubShapeBinder::execute () override protected virtual
recalculate the feature
Reimplemented from Part::Feature.
Definition at line 872 of file ShapeBinder.cpp.
References BindMode, Part::Feature::execute(), App::PropertyEnumeration::getValue(), setupCopyOnChange(), update(), and UpdateForced.
Referenced by src.Mod.PartDesign.Scripts.Spring.MySpring::onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid::onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped::onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt::onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder::onChanged(), and FeaturePython.DistanceBolt::onChanged().
getSubObject()
App::DocumentObject * SubShapeBinder::getSubObject (const char * subname, PyObject ** pyObj = nullptr, Base::Matrix4D * mat = nullptr, bool transform = true, int depth = 0) const override virtual
Get the sub element/object by name
Parameters
subname a string which is dot separated name to refer to a sub element or object. An empty string can be used to refer to the object itself
pyObj if non zero, returns the python object corresponding to this sub object. The actual type of this python object is implementation dependent. For example, The current implementation of Part::Feature will return the TopoShapePy, event if there is no sub-element reference, in which case it returns the whole shape.
mat If non zero, it is used as the current transformation matrix on input. And output as the accumulated transformation up until and include the transformation applied by the final object reference in subname. For Part::Feature, the transformation is applied to the TopoShape inside pyObj before returning.
transform if false, then it will not apply the object's own transformation to mat, which lets you override the object's placement (and possibly scale).
depth depth limitation as hint for cyclic link detection
Returns
The last document object referred in subname. If subname is empty, then it shall return itself. If subname is invalid, then it shall return zero.
Reimplemented from Part::Feature.
Definition at line 404 of file ShapeBinder.cpp.
References App::Application::checkLinkDepth(), dot(), DraftVecUtils::equals(), Data::findElementName(), App::GetApplication(), App::PropertyXLinkSubList::getSubListValues(), Part::Feature::getSubObject(), App::DocumentObject::getSubObject(), App::PropertyPlacement::getValue(), App::DocumentObject::isAttachedToDocument(), RobotExample::l, Data::noElementName(), App::GeoFeature::Placement, Support, and Base::Placement::toMatrix().
getViewProviderName()
const char* PartDesign::SubShapeBinder::getViewProviderName () const inline override virtual
returns the type name of the ViewProvider
Reimplemented from Part::Feature.
Definition at line 106 of file ShapeBinder.h.
handleChangedPropertyType()
void SubShapeBinder::handleChangedPropertyType (Base::XMLReader & reader, const char * TypeName, App::Property * prop) override protected virtual
Extends the rules for handling property type changed, so that extensions are given an opportunity to handle it. If an extension handles a change, neither the rest of the extensions, nor the container itself get to handle it.
Extensions get their extensionHandleChangedPropertyType() called.
If no extension handles the request, then the containers handleChangedPropertyType() is called.
Reimplemented from App::ExtensionContainer.
Definition at line 1105 of file ShapeBinder.cpp.
References App::ExtensionContainer::handleChangedPropertyType(), TechDrawTools.TaskFillTemplateFields::reader, Support, and App::PropertyXLinkSubList::upgrade().
onChanged()
void SubShapeBinder::onChanged (const App::Property * prop) override protected virtual
get called by the container when a property was changed
Reimplemented from Part::Feature.
Definition at line 950 of file ShapeBinder.cpp.
References draftgeoutils.faces::bind(), BindCopyOnChange, BindMode, checkCopyOnChange(), checkPropertyStatus(), clearCopiedObjects(), collapseGeoChildren(), connRecomputedObj, contextDoc, App::PropertyXLinkSubList::getSubListValues(), App::PropertyEnumeration::getValue(), App::PropertyBool::getValue(), App::DocumentObject::isRestoring(), Part::Feature::onChanged(), PartialLoad, Relative, setupCopyOnChange(), App::PropertyXLinkSubList::setValue(), App::Document::signalRecomputedObject, slotRecomputedObject(), Support, App::Property::testStatus(), update(), and App::Property::User3.
onDocumentRestored()
void SubShapeBinder::onDocumentRestored () override protected virtual
get called after a document has been fully restored
Reimplemented from App::DocumentObject.
Definition at line 882 of file ShapeBinder.cpp.
References _Version, App::PropertyInteger::getValue(), App::DocumentObject::onDocumentRestored(), update(), and UpdateInit.
setLinks()
void SubShapeBinder::setLinks (std::map< App::DocumentObject *, std::vector< std::string > > && values, bool reset = false)
Definition at line 1020 of file ShapeBinder.cpp.
References FC_LOG, FC_THROWM, App::DocumentObject::getInListEx(), App::PropertyXLinkSubList::getSubListValues(), Path.Post.scripts.opensbp_post::move(), toolbit-attributes::s, Part::PropertyPartShape::setValue(), App::PropertyXLinkSubList::setValue(), App::PropertyXLinkSubList::setValues(), Part::Feature::Shape, importers.importIFCmulticore::subs, Support, and TestSpreadsheet::v.
Referenced by collapseGeoChildren().
setupCopyOnChange()
void SubShapeBinder::setupCopyOnChange () protected
Definition at line 443 of file ShapeBinder.cpp.
References BindCopyOnChange, copyOnChangeConns, SCL.SimpleDataTypes::e, App::ExtensionContainer::getPropertyList(), App::PropertyXLinkSubList::getSubListValues(), App::PropertyEnumeration::getValue(), hasCopyOnChange, App::LinkBaseExtension::isCopyOnChangeProperty(), App::DocumentObject::removeDynamicProperty(), App::LinkBaseExtension::setupCopyOnChange(), and Support.
Referenced by execute(), and onChanged().
setupObject()
void SubShapeBinder::setupObject () override protected virtual
get called after a brand new object was created
Reimplemented from App::DocumentObject.
Definition at line 397 of file ShapeBinder.cpp.
References _Version, checkPropertyStatus(), PartDesign::getPDRefineModelParameter(), Refine, App::PropertyInteger::setValue(), and App::PropertyBool::setValue().
slotRecomputedObject()
void SubShapeBinder::slotRecomputedObject (const App::DocumentObject & Obj) protected
Definition at line 859 of file ShapeBinder.cpp.
References SCL.SimpleDataTypes::e, App::Recompute2, App::DocumentObject::testStatus(), and update().
Referenced by onChanged().
update()
void SubShapeBinder::update (SubShapeBinder::UpdateOption options = UpdateNone)
Definition at line 499 of file ShapeBinder.cpp.
References _CopiedLink, _CopiedObjs, _Version, App::DocumentObject::addDynamicProperty(), Part::allowOpenResult, BindCopyOnChange, clearCopiedObjects(), Base::Console(), SCL.SimpleDataTypes::e, Data::ComplexGeoData::elementMapPrefix(), Base::ConsoleSingleton::Error(), FC_ERR, FC_LOG, FC_THROWM, FC_WARN, Part::fill, Fuse, App::GetApplication(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), App::PropertyContainer::getDynamicPropertyByName(), App::PropertyContainer::getDynamicPropertyNames(), App::DocumentObject::getFullName(), App::DocumentObject::getID(), App::Document::getName(), App::DocumentObject::getNameInDocument(), App::DocumentObject::getParents(), App::ExtensionContainer::getPropertyByName(), App::ExtensionContainer::getPropertyList(), App::PropertyXLinkSubList::getSubListValues(), App::PropertyXLink::getSubValues(), Part::Feature::getTopoShape(), App::PropertyInteger::getValue(), Part::PropertyPartShape::getValue(), App::PropertyEnumeration::getValue(), App::PropertyPlacement::getValue(), App::PropertyFloat::getValue(), App::PropertyString::getValue(), App::PropertyBool::getValue(), SplineSurface::i, Base::Persistence::init(), Base::Matrix4D::inverseGauss(), App::DocumentObject::isAttachedToDocument(), App::LinkBaseExtension::isCopyOnChangeProperty(), App::DocumentObject::isValid(), RobotExample::l, App::DocumentObject::Label, MakeFace, Path.Op.Surface::msg, App::Application::newDocument(), Part::noFill, Part::noOpenResult, replaceobj::objs, Offset, OffsetFill, OffsetIntersection, OffsetJoinType, OffsetOpenResult, Data::oldElementName(), App::Property::Output, buildPsets::p, Init::parent, App::GeoFeature::Placement, Data::POSTFIX_EXTERNAL_TAG, App::Property::ReadOnly, App::DocumentObject::recomputeFeature(), Refine, Relative, App::DocumentObject::removeDynamicProperty(), result, toolbit-attributes::s, App::Document::setUndoMode(), Part::PropertyPartShape::setValue(), App::PropertyPlacement::setValue(), App::PropertyXLink::setValue(), Part::Feature::Shape, Part::OpCodes::Shapebinder, importers.importIFCmulticore::subs, Support, Base::Placement::toMatrix(), UpdateForced, UpdateInit, and TestSpreadsheet::v.
Referenced by execute(), onChanged(), onDocumentRestored(), Plot.Plot::plot(), and slotRecomputedObject().
Member Data Documentation
_CopiedLink
App::PropertyXLinkSub PartDesign::SubShapeBinder::_CopiedLink protected
Definition at line 172 of file ShapeBinder.h.
Referenced by clearCopiedObjects(), and update().
_CopiedObjs
std::vector<App::DocumentObjectT> PartDesign::SubShapeBinder::_CopiedObjs protected
Definition at line 173 of file ShapeBinder.h.
Referenced by clearCopiedObjects(), and update().
_Version
App::PropertyInteger PartDesign::SubShapeBinder::_Version
Definition at line 120 of file ShapeBinder.h.
Referenced by onDocumentRestored(), setupObject(), and update().
BindCopyOnChange
App::PropertyEnumeration PartDesign::SubShapeBinder::BindCopyOnChange
Definition at line 121 of file ShapeBinder.h.
Referenced by checkCopyOnChange(), onChanged(), setupCopyOnChange(), and update().
BindMode
App::PropertyEnumeration PartDesign::SubShapeBinder::BindMode
Definition at line 117 of file ShapeBinder.h.
Referenced by execute(), and onChanged().
ClaimChildren
App::PropertyBool PartDesign::SubShapeBinder::ClaimChildren
Definition at line 113 of file ShapeBinder.h.
connRecomputedObj
Connection PartDesign::SubShapeBinder::connRecomputedObj protected
Definition at line 166 of file ShapeBinder.h.
Referenced by onChanged().
Context
App::PropertyXLink PartDesign::SubShapeBinder::Context
Definition at line 119 of file ShapeBinder.h.
contextDoc
App::Document* PartDesign::SubShapeBinder::contextDoc = nullptr protected
Definition at line 167 of file ShapeBinder.h.
Referenced by onChanged().
copyOnChangeConns
std::vector<Connection> PartDesign::SubShapeBinder::copyOnChangeConns protected
Definition at line 169 of file ShapeBinder.h.
Referenced by setupCopyOnChange().
Fuse
App::PropertyBool PartDesign::SubShapeBinder::Fuse
Definition at line 115 of file ShapeBinder.h.
Referenced by update().
hasCopyOnChange
bool PartDesign::SubShapeBinder::hasCopyOnChange = true protected
Definition at line 170 of file ShapeBinder.h.
Referenced by setupCopyOnChange().
MakeFace
App::PropertyBool PartDesign::SubShapeBinder::MakeFace
Definition at line 116 of file ShapeBinder.h.
Referenced by update().
Offset
App::PropertyFloat PartDesign::SubShapeBinder::Offset
Definition at line 123 of file ShapeBinder.h.
Referenced by update().
OffsetFill
App::PropertyBool PartDesign::SubShapeBinder::OffsetFill
Definition at line 125 of file ShapeBinder.h.
Referenced by update().
OffsetIntersection
App::PropertyBool PartDesign::SubShapeBinder::OffsetIntersection
Definition at line 127 of file ShapeBinder.h.
Referenced by update().
OffsetJoinType
App::PropertyEnumeration PartDesign::SubShapeBinder::OffsetJoinType
Definition at line 124 of file ShapeBinder.h.
Referenced by update().
OffsetOpenResult
App::PropertyBool PartDesign::SubShapeBinder::OffsetOpenResult
Definition at line 126 of file ShapeBinder.h.
Referenced by update().
PartialLoad
App::PropertyBool PartDesign::SubShapeBinder::PartialLoad
Definition at line 118 of file ShapeBinder.h.
Referenced by checkPropertyStatus(), and onChanged().
Refine
App::PropertyBool PartDesign::SubShapeBinder::Refine
Definition at line 122 of file ShapeBinder.h.
Referenced by setupObject(), and update().
Relative
App::PropertyBool PartDesign::SubShapeBinder::Relative
Definition at line 114 of file ShapeBinder.h.
Referenced by onChanged(), and update().
Support
App::PropertyXLinkSubList PartDesign::SubShapeBinder::Support
Definition at line 112 of file ShapeBinder.h.
Referenced by checkCopyOnChange(), checkPropertyStatus(), collapseGeoChildren(), getSubObject(), handleChangedPropertyType(), onChanged(), setLinks(), setupCopyOnChange(), and update().
The documentation for this class was generated from the following files:
ShapeBinder.h
ShapeBinder.cpp