FreeCAD: Gui::Dialog::DlgExpressionInput Class Reference
Gui::Dialog::DlgExpressionInput Class Reference
#include <DlgExpressionInput.h>
Public Slots
void show ()
void accept () override
Public Member Functions
DlgExpressionInput (const App::ObjectIdentifier &_path, std::shared_ptr< const App::Expression > _expression, const Base::Unit &_impliedUnit, QWidget *parent=nullptr)
~DlgExpressionInput () override
void setRange (double minimum, double maximum)
void clearRange ()
std::shared_ptr< App::Expression > getExpression () const
bool discardedFormula () const
QPoint expressionPosition () const
void setExpressionInputSize (int width, int height)
Protected Member Functions
void mouseReleaseEvent (QMouseEvent *) override
void mousePressEvent (QMouseEvent *) override
Detailed Description
Definition at line 64 of file DlgExpressionInput.h.
Constructor & Destructor Documentation
DlgExpressionInput()
DlgExpressionInput::DlgExpressionInput (const App::ObjectIdentifier & _path, std::shared_ptr< const App::Expression > _expression, const Base::Unit & _impliedUnit, QWidget * parent = nullptr) explicit
Definition at line 54 of file DlgExpressionInput.cpp.
References draftgeoutils.intersections::connect(), App::GetApplication(), ParameterGrp::GetBool(), App::ObjectIdentifier::getDocumentObject(), App::Application::GetParameterGroupByPath(), and Init::parent.
~DlgExpressionInput()
DlgExpressionInput::~DlgExpressionInput () override
Definition at line 121 of file DlgExpressionInput.cpp.
Member Function Documentation
accept
void DlgExpressionInput::accept () override slot
Definition at line 522 of file DlgExpressionInput.cpp.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
clearRange()
void DlgExpressionInput::clearRange ()
Definition at line 259 of file DlgExpressionInput.cpp.
References Gui::Dialog::NumberRange::clearRange().
discardedFormula()
bool Gui::Dialog::DlgExpressionInput::discardedFormula () const inline
Definition at line 76 of file DlgExpressionInput.h.
expressionPosition()
QPoint DlgExpressionInput::expressionPosition () const
Definition at line 264 of file DlgExpressionInput.cpp.
getExpression()
std::shared_ptr<App::Expression> Gui::Dialog::DlgExpressionInput::getExpression () const inline
Definition at line 74 of file DlgExpressionInput.h.
mousePressEvent()
void DlgExpressionInput::mousePressEvent (QMouseEvent * ev) override protected
Definition at line 386 of file DlgExpressionInput.cpp.
mouseReleaseEvent()
void DlgExpressionInput::mouseReleaseEvent (QMouseEvent * ev) override protected
Definition at line 381 of file DlgExpressionInput.cpp.
setExpressionInputSize()
void DlgExpressionInput::setExpressionInputSize (int width, int height)
Definition at line 370 of file DlgExpressionInput.cpp.
setRange()
void DlgExpressionInput::setRange (double minimum, double maximum)
Definition at line 254 of file DlgExpressionInput.cpp.
References Gui::Dialog::NumberRange::setRange().
show
void DlgExpressionInput::show () slot
Definition at line 400 of file DlgExpressionInput.cpp.
References bimcommands.BimViews::show().
Referenced by src.Mod.Show.mTempoVis.TempoVis::show_all_dependencies(), src.Mod.Show.mTempoVis.TempoVis::show_all_dependent(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
The documentation for this class was generated from the following files:
DlgExpressionInput.h
DlgExpressionInput.cpp