FreeCAD: Path.Base.Language.MoveArcCCW Class Reference
Path.Base.Language.MoveArcCCW Class Reference
Public Member Functions
def arcDirection (self)
Public Member Functions inherited from Path.Base.Language.MoveArc
def anglesOfTangents (self)
def isMove (self)
def isArc (self)
def isCW (self)
def isCCW (self)
def arcAngle (self)
def arcRadius (self)
def pathLength (self)
def xyCenter (self)
Public Member Functions inherited from Path.Base.Language.Instruction
def __init__ (self, begin, cmd, param=None)
def setPositionBegin (self, begin)
def positionBegin (self)
def positionEnd (self)
def isRapid (self)
def isPlunge (self)
def leadsInto (self, instr)
def x (self, default=0)
def y (self, default=0)
def z (self, default=0)
def i (self, default=0)
def j (self, default=0)
def k (self, default=0)
def xyBegin (self)
def xyEnd (self)
def __repr__ (self)
def str (self, digits=2)
Additional Inherited Members
Public Attributes inherited from Path.Base.Language.Instruction
begin
cmd
param
Detailed Description
Definition at line 202 of file Language.py.
Member Function Documentation
arcDirection()
def Path.Base.Language.MoveArcCCW.arcDirection (self)
Definition at line 203 of file Language.py.
Referenced by Path.Base.Language.MoveArc.anglesOfTangents(), Path.Base.Language.MoveArc.isCCW(), and Path.Base.Language.MoveArc.isCW().
The documentation for this class was generated from the following file:
Language.py