FreeCAD: SIM::Coin3D::Quarter::SpaceNavigatorDevice Class Reference
SIM::Coin3D::Quarter::SpaceNavigatorDevice Class Reference
#include <SpaceNavigatorDevice.h>
Public Member Functions
SpaceNavigatorDevice (QuarterWidget *quarter)
~SpaceNavigatorDevice () override
const SoEvent * translateEvent (QEvent *event) override
Public Member Functions inherited from SIM::Coin3D::Quarter::InputDevice
InputDevice (QuarterWidget *quarter)
virtual ~InputDevice ()
void setMousePosition (const SbVec2s &pos)
void setWindowSize (const SbVec2s &size)
void setModifiers (SoEvent *soevent, const QInputEvent *qevent)
Friends
class SpaceNavigatorDeviceP
Additional Inherited Members
Protected Attributes inherited from SIM::Coin3D::Quarter::InputDevice
SbVec2s mousepos
SbVec2s windowsize
QuarterWidget * quarter
Detailed Description
Definition at line 43 of file SpaceNavigatorDevice.h.
Constructor & Destructor Documentation
SpaceNavigatorDevice()
SpaceNavigatorDevice::SpaceNavigatorDevice (QuarterWidget * quarter) explicit
Definition at line 84 of file SpaceNavigatorDevice.cpp.
References femsolver.report::display(), PRIVATE, and SpaceNavigatorDeviceP.
~SpaceNavigatorDevice()
SpaceNavigatorDevice::~SpaceNavigatorDevice () override
Definition at line 101 of file SpaceNavigatorDevice.cpp.
References PRIVATE.
Member Function Documentation
translateEvent()
const SoEvent * SpaceNavigatorDevice::translateEvent (QEvent * event) override virtual
Subclasses must override this method to provide custom event handling
Implements SIM::Coin3D::Quarter::InputDevice.
Definition at line 108 of file SpaceNavigatorDevice.cpp.
References KDL::cos(), RobotExample::pos, PRIVATE, KDL::sin(), and KDL::sqrt().
Friends And Related Function Documentation
SpaceNavigatorDeviceP
friend class SpaceNavigatorDeviceP friend
Definition at line 51 of file SpaceNavigatorDevice.h.
Referenced by SpaceNavigatorDevice().
The documentation for this class was generated from the following files:
SpaceNavigatorDevice.h
SpaceNavigatorDevice.cpp