FreeCAD: Gui::Inventor::MarkerBitmaps Class Reference
Gui::Inventor::MarkerBitmaps Class Reference
#include <MarkerBitmaps.h>
Static Public Member Functions
static void initClass ()
static int getMarkerIndex (const std::string &, int px)
static std::list< int > getSupportedSizes (const std::string &)
Detailed Description
Definition at line 74 of file MarkerBitmaps.h.
Member Function Documentation
getMarkerIndex()
int MarkerBitmaps::getMarkerIndex (const std::string & name, int px) static
Definition at line 1384 of file MarkerBitmaps.cpp.
Referenced by RobotGui::ViewProviderTrajectory::attach(), PartDesignGui::ViewProviderDatumPoint::attach(), SketcherGui::EditModeCoinManager::drawEditMarkers(), MeshGui::ViewProviderMeshDefects::makeMarkerSet(), Gui::ApplicationPy::sGetMarkerIndex(), MeasureGui::ViewProviderMeasureDistance::ViewProviderMeasureDistance(), and FemGui::ViewProviderPointMarker::ViewProviderPointMarker().
getSupportedSizes()
std::list< int > MarkerBitmaps::getSupportedSizes (const std::string & name) static
Definition at line 1394 of file MarkerBitmaps.cpp.
Referenced by SketcherGui::EditModeCoinManager::drawEditMarkers(), and Gui::ApplicationPy::sGetMarkerIndex().
initClass()
void MarkerBitmaps::initClass () static
Definition at line 1258 of file MarkerBitmaps.cpp.
References circleFilled11_marker, circleFilled13_marker, circleFilled15_marker, circleFilled20_marker, circleFilled25_marker, circleFilled30_marker, circleLine11_marker, circleLine13_marker, circleLine15_marker, circleLine20_marker, circleLine25_marker, circleLine30_marker, cross11_marker, cross13_marker, cross15_marker, cross20_marker, cross25_marker, cross30_marker, diamondFilled11_marker, diamondFilled13_marker, diamondFilled15_marker, diamondFilled20_marker, diamondFilled25_marker, diamondFilled30_marker, hourglassFilled11_marker, hourglassFilled13_marker, hourglassFilled15_marker, hourglassFilled20_marker, hourglassFilled25_marker, hourglassFilled30_marker, plus11_marker, plus13_marker, plus15_marker, plus20_marker, plus25_marker, plus30_marker, squareFilled11_marker, squareFilled13_marker, squareFilled15_marker, squareFilled20_marker, squareFilled25_marker, squareFilled30_marker, squareLine11_marker, squareLine13_marker, squareLine15_marker, squareLine20_marker, squareLine25_marker, and squareLine30_marker.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
The documentation for this class was generated from the following files:
MarkerBitmaps.h
MarkerBitmaps.cpp