FreeCAD: Command.cpp File Reference
Mod/Fem/Gui/Command.cpp File Reference
#include "PreCompiled.h"
#include <Inventor/events/SoMouseButtonEvent.h>
#include <Inventor/nodes/SoCamera.h>
#include <Inventor/nodes/SoEventCallback.h>
#include <QAction>
#include <QApplication>
#include <QMessageBox>
#include <SMESHDS_Mesh.hxx>
#include <SMESH_Mesh.hxx>
#include <App/Document.h>
#include <App/DocumentObserver.h>
#include <Gui/Action.h>
#include <Gui/Application.h>
#include <Gui/BitmapFactory.h>
#include <Gui/CommandT.h>
#include <Gui/Document.h>
#include <Gui/FileDialog.h>
#include <Gui/MainWindow.h>
#include <Gui/SelectionFilter.h>
#include <Gui/SelectionObject.h>
#include <Gui/Utilities.h>
#include <Gui/View3DInventor.h>
#include <Gui/View3DInventorViewer.h>
#include <Gui/WaitCursor.h>
#include <Mod/Fem/App/FemAnalysis.h>
#include <Mod/Fem/App/FemConstraint.h>
#include <Mod/Fem/App/FemMeshObject.h>
#include <Mod/Fem/App/FemSetElementNodesObject.h>
#include <Mod/Fem/App/FemSetNodesObject.h>
#include "ActiveAnalysisObserver.h"
#include "FemSettings.h"
Functions
static bool getConstraintPrerequisits (Fem::FemAnalysis **Analysis)
static std::string gethideMeshShowPartStr (std::string showConstr="")
static std::string getSelectedNodes (Gui::View3DInventorViewer *view)
static void DefineNodesCallback (void *ud, SoEventCallback *n)
DEF_STD_CMD_A (CmdFemDefineElementsSet)
static void DefineElementsCallback (void *ud, SoEventCallback *n)
DEF_STD_CMD_A (CmdFemCreateElementsSet)
void CreateFemCommands ()
Function Documentation
CreateFemCommands()
void CreateFemCommands ()
Definition at line 2802 of file Mod/Fem/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
DEF_STD_CMD_A() [1/2]
DEF_STD_CMD_A (CmdFemCreateElementsSet)
DEF_STD_CMD_A() [2/2]
DEF_STD_CMD_A (CmdFemDefineElementsSet)
DefineElementsCallback()
static void DefineElementsCallback (void * ud, SoEventCallback * n) static
Definition at line 1242 of file Mod/Fem/Gui/Command.cpp.
References Gui::Command::commitCommand(), Gui::Command::Doc, doCommand, getConstraintPrerequisits(), App::DocumentObject::getNameInDocument(), getSelectedNodes(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, Gui::View3DInventorViewer::removeEventCallback(), Gui::View3DInventorViewer::setEditing(), and Path.Post.scripts.refactored_centroid_post::str.
DefineNodesCallback()
static void DefineNodesCallback (void * ud, SoEventCallback * n) static
Definition at line 1091 of file Mod/Fem/Gui/Command.cpp.
References Gui::Command::commitCommand(), Gui::Command::Doc, doCommand, getConstraintPrerequisits(), App::DocumentObject::getNameInDocument(), getSelectedNodes(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, Gui::View3DInventorViewer::removeEventCallback(), Gui::View3DInventorViewer::setEditing(), and Path.Post.scripts.refactored_centroid_post::str.
getConstraintPrerequisits()
static bool getConstraintPrerequisits (Fem::FemAnalysis ** Analysis) static
Definition at line 73 of file Mod/Fem/Gui/Command.cpp.
References FemGui::ActiveAnalysisObserver::getActiveObject(), Gui::getMainWindow(), FemGui::ActiveAnalysisObserver::instance(), and Path.Log::warning().
Referenced by DefineElementsCallback(), and DefineNodesCallback().
gethideMeshShowPartStr()
static std::string gethideMeshShowPartStr (std::string showConstr = "") static
Definition at line 89 of file Mod/Fem/Gui/Command.cpp.
getSelectedNodes()
static std::string getSelectedNodes (Gui::View3DInventorViewer * view) static
Definition at line 103 of file Mod/Fem/Gui/Command.cpp.
References Base::Persistence::getClassTypeId(), Gui::View3DInventorViewer::getGLPolygon(), Gui::SelectionSingleton::getObjectsOfType(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), Gui::Selection(), SurfaceTests.TestBlendCurve::vec, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by DefineElementsCallback(), and DefineNodesCallback().