FreeCAD: Gui::ReportOutputParameter Class Reference
Gui::ReportOutputParameter Class Reference
Static Public Member Functions
static bool showOnLogMessage ()
static void toggleShowOnLogMessage ()
static bool showOnMessage ()
static void toggleShowOnMessage ()
static bool showOnWarning ()
static void toggleShowOnWarning ()
static bool showOnError ()
static void toggleShowOnError ()
static bool showOnCritical ()
static void toggleShowOnCritical ()
Detailed Description
Definition at line 212 of file ReportView.cpp.
Member Function Documentation
showOnCritical()
static bool Gui::ReportOutputParameter::showOnCritical () inline static
Definition at line 251 of file ReportView.cpp.
References importDXF::getGroup().
Referenced by Gui::DockWnd::ReportOutput::contextMenuEvent(), and Gui::DockWnd::ReportOutputObserver::eventFilter().
showOnError()
static bool Gui::ReportOutputParameter::showOnError () inline static
Definition at line 242 of file ReportView.cpp.
References importDXF::getGroup().
Referenced by Gui::DockWnd::ReportOutput::contextMenuEvent(), and Gui::DockWnd::ReportOutputObserver::eventFilter().
showOnLogMessage()
static bool Gui::ReportOutputParameter::showOnLogMessage () inline static
Definition at line 215 of file ReportView.cpp.
References importDXF::getGroup().
Referenced by Gui::DockWnd::ReportOutput::contextMenuEvent(), and Gui::DockWnd::ReportOutputObserver::eventFilter().
showOnMessage()
static bool Gui::ReportOutputParameter::showOnMessage () inline static
Definition at line 224 of file ReportView.cpp.
References importDXF::getGroup().
Referenced by Gui::DockWnd::ReportOutput::contextMenuEvent(), and Gui::DockWnd::ReportOutputObserver::eventFilter().
showOnWarning()
static bool Gui::ReportOutputParameter::showOnWarning () inline static
Definition at line 233 of file ReportView.cpp.
References importDXF::getGroup().
Referenced by Gui::DockWnd::ReportOutput::contextMenuEvent(), and Gui::DockWnd::ReportOutputObserver::eventFilter().
toggleShowOnCritical()
static void Gui::ReportOutputParameter::toggleShowOnCritical () inline static
Definition at line 255 of file ReportView.cpp.
References importDXF::getGroup(), and bimcommands.BimViews::show().
Referenced by Gui::DockWnd::ReportOutput::onToggleShowReportViewOnCritical().
toggleShowOnError()
static void Gui::ReportOutputParameter::toggleShowOnError () inline static
Definition at line 246 of file ReportView.cpp.
References importDXF::getGroup(), and bimcommands.BimViews::show().
Referenced by Gui::DockWnd::ReportOutput::onToggleShowReportViewOnError().
toggleShowOnLogMessage()
static void Gui::ReportOutputParameter::toggleShowOnLogMessage () inline static
Definition at line 219 of file ReportView.cpp.
References importDXF::getGroup(), and bimcommands.BimViews::show().
Referenced by Gui::DockWnd::ReportOutput::onToggleShowReportViewOnLogMessage().
toggleShowOnMessage()
static void Gui::ReportOutputParameter::toggleShowOnMessage () inline static
Definition at line 228 of file ReportView.cpp.
References importDXF::getGroup(), and bimcommands.BimViews::show().
Referenced by Gui::DockWnd::ReportOutput::onToggleShowReportViewOnNormalMessage().
toggleShowOnWarning()
static void Gui::ReportOutputParameter::toggleShowOnWarning () inline static
Definition at line 237 of file ReportView.cpp.
References importDXF::getGroup(), and bimcommands.BimViews::show().
Referenced by Gui::DockWnd::ReportOutput::onToggleShowReportViewOnWarning().
The documentation for this class was generated from the following file:
ReportView.cpp