FreeCAD: Gui::PropertyEditor::LinkLabel Class Reference
Gui::PropertyEditor::LinkLabel Class Reference
#include <PropertyItem.h>
Signals
void linkChanged (const QVariant &)
Public Member Functions
LinkLabel (QWidget *parent, const App::Property *prop)
~LinkLabel () override
void updatePropertyLink ()
QVariant propertyLink () const
Protected Slots
void onLinkActivated (const QString &)
void onEditClicked ()
void onLinkChanged ()
Protected Member Functions
void resizeEvent (QResizeEvent *) override
Detailed Description
Definition at line 1226 of file PropertyItem.h.
Constructor & Destructor Documentation
LinkLabel()
LinkLabel::LinkLabel (QWidget * parent, const App::Property * prop)
Definition at line 4566 of file PropertyItem.cpp.
References draftgeoutils.intersections::connect(), onEditClicked(), and onLinkActivated().
~LinkLabel()
LinkLabel::~LinkLabel () override default
Member Function Documentation
linkChanged
void Gui::PropertyEditor::LinkLabel::linkChanged (const QVariant &) signal
Referenced by Gui::PropertyEditor::PropertyLinkItem::createEditor(), and onLinkChanged().
onEditClicked
void LinkLabel::onEditClicked () protected slot
Definition at line 4649 of file PropertyItem.cpp.
References draftgeoutils.intersections::connect(), and onLinkChanged().
Referenced by LinkLabel().
onLinkActivated
void LinkLabel::onLinkActivated (const QString & s) protected slot
Definition at line 4642 of file PropertyItem.cpp.
References toolbit-attributes::s, Path.Op.Gui.Selection::select(), and Gui::PropertyEditor::LinkSelection::select().
Referenced by LinkLabel().
onLinkChanged
void LinkLabel::onLinkChanged () protected slot
Definition at line 4663 of file PropertyItem.cpp.
References linkChanged(), and updatePropertyLink().
Referenced by onEditClicked().
propertyLink()
QVariant LinkLabel::propertyLink () const
Definition at line 4637 of file PropertyItem.cpp.
Referenced by Gui::PropertyEditor::PropertyLinkItem::editorData().
resizeEvent()
void LinkLabel::resizeEvent (QResizeEvent * e) override protected
Definition at line 4675 of file PropertyItem.cpp.
References SCL.SimpleDataTypes::e.
updatePropertyLink()
void LinkLabel::updatePropertyLink ()
Definition at line 4601 of file PropertyItem.cpp.
References draftutils.gui_utils::formatObject, App::DocumentObjectT::getObject(), and App::DocumentObjectT::getProperty().
Referenced by onLinkChanged(), and Gui::PropertyEditor::PropertyLinkItem::setEditorData().
The documentation for this class was generated from the following files:
PropertyItem.h
PropertyItem.cpp