FreeCAD: ifc2x3.ifcmechanicalmaterialproperties Class Reference
ifc2x3.ifcmechanicalmaterialproperties Class Reference
Public Member Functions
def __init__ (self, inherited0__material, dynamicviscosity, youngmodulus, shearmodulus, poissonratio, thermalexpansioncoefficient)
def dynamicviscosity ()
def youngmodulus ()
def shearmodulus ()
def poissonratio ()
def thermalexpansioncoefficient ()
def wr21 (self)
def wr22 (self)
Public Member Functions inherited from ifc2x3.ifcmaterialproperties
def __init__ (self, material)
def material ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
dynamicviscosity
youngmodulus
shearmodulus
poissonratio
thermalexpansioncoefficient
Public Attributes inherited from ifc2x3.ifcmaterialproperties
material
Detailed Description
Entity ifcmechanicalmaterialproperties definition.
:param dynamicviscosity
:type dynamicviscosity:ifcdynamicviscositymeasure
:param youngmodulus
:type youngmodulus:ifcmodulusofelasticitymeasure
:param shearmodulus
:type shearmodulus:ifcmodulusofelasticitymeasure
:param poissonratio
:type poissonratio:ifcpositiveratiomeasure
:param thermalexpansioncoefficient
:type thermalexpansioncoefficient:ifcthermalexpansioncoefficientmeasure
Definition at line 9801 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcmechanicalmaterialproperties.__init__ (self, inherited0__material, dynamicviscosity, youngmodulus, shearmodulus, poissonratio, thermalexpansioncoefficient)
Definition at line 9819 of file ifc2x3.py.
Member Function Documentation
dynamicviscosity()
def ifc2x3.ifcmechanicalmaterialproperties.dynamicviscosity ()
Definition at line 9828 of file ifc2x3.py.
References ifc2x3.ifcmechanicalmaterialproperties._dynamicviscosity, SCL.TypeChecker.check_type(), and ifc2x3.ifcmechanicalmaterialproperties.dynamicviscosity.
poissonratio()
def ifc2x3.ifcmechanicalmaterialproperties.poissonratio ()
Definition at line 9870 of file ifc2x3.py.
References ifc2x3.ifcmechanicalmaterialproperties._poissonratio, SCL.TypeChecker.check_type(), and ifc2x3.ifcmechanicalmaterialproperties.poissonratio.
shearmodulus()
def ifc2x3.ifcmechanicalmaterialproperties.shearmodulus ()
Definition at line 9856 of file ifc2x3.py.
References ifc2x3.ifcmechanicalmaterialproperties._shearmodulus, SCL.TypeChecker.check_type(), and ifc2x3.ifcmechanicalmaterialproperties.shearmodulus.
thermalexpansioncoefficient()
def ifc2x3.ifcmechanicalmaterialproperties.thermalexpansioncoefficient ()
Definition at line 9884 of file ifc2x3.py.
References ifc2x3.ifcmechanicalmaterialproperties._thermalexpansioncoefficient, SCL.TypeChecker.check_type(), and ifc2x3.ifcmechanicalmaterialproperties.thermalexpansioncoefficient.
wr21()
def ifc2x3.ifcmechanicalmaterialproperties.wr21 (self)
Definition at line 9896 of file ifc2x3.py.
References SCL.Builtin.EXISTS(), and ifc2x3.ifcmechanicalmaterialproperties.youngmodulus.
Referenced by ifc4.ifcphmeasure.__init__().
wr22()
def ifc2x3.ifcmechanicalmaterialproperties.wr22 (self)
Definition at line 9903 of file ifc2x3.py.
References SCL.Builtin.EXISTS(), and ifc2x3.ifcmechanicalmaterialproperties.shearmodulus.
youngmodulus()
def ifc2x3.ifcmechanicalmaterialproperties.youngmodulus ()
Definition at line 9842 of file ifc2x3.py.
References ifc2x3.ifcmechanicalmaterialproperties._youngmodulus, SCL.TypeChecker.check_type(), and ifc2x3.ifcmechanicalmaterialproperties.youngmodulus.
Member Data Documentation
dynamicviscosity
ifc2x3.ifcmechanicalmaterialproperties.dynamicviscosity
Definition at line 9821 of file ifc2x3.py.
Referenced by ifc2x3.ifcmechanicalmaterialproperties.dynamicviscosity().
poissonratio
ifc2x3.ifcmechanicalmaterialproperties.poissonratio
Definition at line 9824 of file ifc2x3.py.
Referenced by ifc2x3.ifcmechanicalmaterialproperties.poissonratio().
shearmodulus
ifc2x3.ifcmechanicalmaterialproperties.shearmodulus
Definition at line 9823 of file ifc2x3.py.
Referenced by ifc2x3.ifcmechanicalmaterialproperties.shearmodulus(), and ifc2x3.ifcmechanicalmaterialproperties.wr22().
thermalexpansioncoefficient
ifc2x3.ifcmechanicalmaterialproperties.thermalexpansioncoefficient
Definition at line 9825 of file ifc2x3.py.
Referenced by ifc2x3.ifcmechanicalmaterialproperties.thermalexpansioncoefficient().
youngmodulus
ifc2x3.ifcmechanicalmaterialproperties.youngmodulus
Definition at line 9822 of file ifc2x3.py.
Referenced by ifc2x3.ifcmechanicalmaterialproperties.wr21(), and ifc2x3.ifcmechanicalmaterialproperties.youngmodulus().
The documentation for this class was generated from the following file:
ifc2x3.py