FreeCAD: Path::Command Class Reference
Path::Command Class Reference
#include <Command.h>
Public Member Functions
Command ()
Command (const char *name, const std::map< std::string, double > &parameters)
~Command () override
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
Base::Placement getPlacement (const Base::Vector3d pos=Base::Vector3d()) const
Base::Vector3d getCenter () const
void setCenter (const Base::Vector3d &, bool clockwise=true)
std::string toGCode (int precision=6, bool padzero=true) const
void setFromGCode (const std::string &)
void setFromPlacement (const Base::Placement &)
bool has (const std::string &) const
Command transform (const Base::Placement &)
double getValue (const std::string &name) const
void scaleBy (double factor)
double getParam (const std::string &name, double fallback=0.0) const
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Attributes
std::string Name
std::map< std::string, double > Parameters
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
The representation of a cnc command in a path
Definition at line 57 of file Mod/CAM/App/Command.h.
Constructor & Destructor Documentation
Command() [1/2]
Command::Command ()
Definition at line 51 of file Mod/CAM/App/Command.cpp.
Command() [2/2]
Command::Command (const char * name, const std::map< std::string, double > & parameters)
Definition at line 46 of file Mod/CAM/App/Command.cpp.
~Command()
Command::~Command () override
Definition at line 54 of file Mod/CAM/App/Command.cpp.
Member Function Documentation
getCenter()
Vector3d Command::getCenter () const
Definition at line 74 of file Mod/CAM/App/Command.cpp.
References draftutils.utils::getParam, SplineSurface::i, and SurfaceTests.TestBlendCurve::vec.
Referenced by PathSimulator::PathSim::ApplyCommand(), and Path::PathSegmentWalker::walk().
getMemSize()
unsigned int Command::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
Definition at line 338 of file Mod/CAM/App/Command.cpp.
getParam()
double Path::Command::getParam (const std::string & name, double fallback = 0.0) const inline
Definition at line 111 of file Mod/CAM/App/Command.h.
getPlacement()
Placement Command::getPlacement (const Base::Vector3d pos = Base::Vector3d()) const
Definition at line 59 of file Mod/CAM/App/Command.cpp.
References a, SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::c, draftutils.utils::getParam, RobotExample::pos, Base::Rotation::setYawPitchRoll(), SurfaceTests.TestBlendCurve::vec, MovieTool::x, and MovieTool::y.
Referenced by Point3D::UpdateCmd(), and Path::PathSegmentWalker::walk().
getValue()
double Command::getValue (const std::string & name) const
Definition at line 83 of file Mod/CAM/App/Command.cpp.
References a, and draftutils.utils::getParam.
Referenced by Path::PathSegmentWalker::walk().
has()
bool Command::has (const std::string & attr) const
Definition at line 90 of file Mod/CAM/App/Command.cpp.
References a.
Referenced by src.Mod.Show.mTempoVis.TempoVis::restoreDetail(), Point3D::UpdateCmd(), and Path::PathSegmentWalker::walk().
Restore()
void Command::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 351 of file Mod/CAM/App/Command.cpp.
References TechDrawTools.TaskFillTemplateFields::reader.
Save()
void Command::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 343 of file Mod/CAM/App/Command.cpp.
References Base::Writer::ind(), and Base::Writer::Stream().
scaleBy()
void Command::scaleBy (double factor)
Definition at line 316 of file Mod/CAM/App/Command.cpp.
References SplineSurface::i.
Referenced by bulkAddCommand().
setCenter()
void Command::setCenter (const Base::Vector3d & pos, bool clockwise = true)
Definition at line 257 of file Mod/CAM/App/Command.cpp.
References SplineSurface::i, and RobotExample::pos.
Referenced by draftguitools.gui_trackers.arcTracker::setBy3Points().
setFromGCode()
void Command::setFromGCode (const std::string & str)
Definition at line 144 of file Mod/CAM/App/Command.cpp.
References SplineSurface::i, Path.Post.scripts.refactored_centroid_post::str, and toolbit-attributes::val.
Referenced by bulkAddCommand().
setFromPlacement()
void Command::setFromPlacement (const Base::Placement & plac)
Definition at line 222 of file Mod/CAM/App/Command.cpp.
References a, SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::c, Base::Placement::getPosition(), Base::Placement::getRotation(), Base::Rotation::getYawPitchRoll(), MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
toGCode()
std::string Command::toGCode (int precision = 6, bool padzero = true) const
Definition at line 97 of file Mod/CAM/App/Command.cpp.
References SplineSurface::i, Base::pow(), draftgeoutils.general::precision(), draftfunctions.scale::scale(), Path.Post.scripts.refactored_centroid_post::str, and TestSpreadsheet::v.
Referenced by CAMSimulator::CAMSim::AddCommand(), and PathGui::ViewProviderPath::getElement().
transform()
Command Command::transform (const Base::Placement & other)
Definition at line 277 of file Mod/CAM/App/Command.cpp.
References SCL.SimpleDataTypes::c, Path.Op.Gui.Adaptive::Command, importers.importIFCHelper::getPlacement(), Base::Placement::getPosition(), Base::Placement::getRotation(), Base::Rotation::getYawPitchRoll(), SplineSurface::i, TestSpreadsheet::v, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by draftviewproviders.view_hatch.ViewProviderDraftHatch::setupContextMenu(), and draftviewproviders.view_base.ViewProviderDraft::setupContextMenu().
Member Data Documentation
Name
std::string Path::Command::Name
Definition at line 118 of file Mod/CAM/App/Command.h.
Referenced by PathSimulator::PathSim::ApplyCommand(), bulkAddCommand(), and Path::PathSegmentWalker::walk().
Parameters
std::map<std::string, double> Path::Command::Parameters
Definition at line 119 of file Mod/CAM/App/Command.h.
The documentation for this class was generated from the following files:
Mod/CAM/App/Command.h
Mod/CAM/App/Command.cpp