FreeCAD: SketcherGui::ElementFilterList Class Reference
SketcherGui::ElementFilterList Class Reference
Public Member Functions
ElementFilterList (QWidget *parent=nullptr)
~ElementFilterList () override
Protected Member Functions
void changeEvent (QEvent *e) override
void languageChange ()
Detailed Description
Definition at line 295 of file TaskSketcherElements.cpp.
Constructor & Destructor Documentation
ElementFilterList()
ElementFilterList::ElementFilterList (QWidget * parent = nullptr) explicit
Definition at line 1122 of file TaskSketcherElements.cpp.
References AllGeosTypes, src.Mod.AddonManager.NetworkManager::count, App::GetApplication(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), SplineSurface::i, and languageChange().
~ElementFilterList()
ElementFilterList::~ElementFilterList () override
Definition at line 1158 of file TaskSketcherElements.cpp.
Member Function Documentation
changeEvent()
void ElementFilterList::changeEvent (QEvent * e) override protected
Definition at line 1161 of file TaskSketcherElements.cpp.
References SCL.SimpleDataTypes::e, and languageChange().
languageChange()
void ElementFilterList::languageChange () protected
Definition at line 1169 of file TaskSketcherElements.cpp.
References src.Mod.AddonManager.NetworkManager::count, and SplineSurface::i.
Referenced by changeEvent(), and ElementFilterList().
The documentation for this class was generated from the following file:
TaskSketcherElements.cpp