FreeCAD: App::CellAddress Struct Reference
App::CellAddress Struct Reference
#include <Range.h>
Public Types
enum Cell {
Cell::Absolute = 1, Cell::ShowRow = 2, Cell::ShowColumn = 4, Cell::ShowRowColumn = ShowRow | ShowColumn,
Cell::ShowFull = Absolute | ShowRow | ShowColumn
}
Public Member Functions
CellAddress (int row=-1, int col=-1, bool absRow=false, bool absCol=false)
CellAddress (const char *address)
CellAddress (const std::string &address)
bool parseAbsoluteAddress (const char *txt)
App::CellAddress::parseAbsoluteAddress.
int row () const
int col () const
void setRow (int r, bool clip=false)
void setCol (int c, bool clip=false)
bool operator< (const CellAddress &other) const
bool operator> (const CellAddress &other) const
bool operator== (const CellAddress &other) const
bool operator!= (const CellAddress &other) const
bool isValid ()
bool isAbsoluteRow () const
bool isAbsoluteCol () const
std::string toString (Cell=Cell::ShowFull) const
Convert given cell address into its string representation.
Static Public Attributes
static const int MAX_ROWS = 16384
static const int MAX_COLUMNS = 26 * 26 + 26
Protected Member Functions
unsigned int asInt () const
Protected Attributes
short _row
short _col
bool _absRow
bool _absCol
Detailed Description
Definition at line 63 of file Range.h.
Member Enumeration Documentation
Cell
enum App::CellAddress::Cell strong
Enumerator
Absolute
ShowRow
ShowColumn
ShowRowColumn
ShowFull
Definition at line 66 of file Range.h.
Constructor & Destructor Documentation
CellAddress() [1/3]
App::CellAddress::CellAddress (int row = -1, int col = -1, bool absRow = false, bool absCol = false) inline explicit
Definition at line 75 of file Range.h.
CellAddress() [2/3]
App::CellAddress::CellAddress (const char * address) inline explicit
Definition at line 82 of file Range.h.
CellAddress() [3/3]
App::CellAddress::CellAddress (const std::string & address) inline explicit
Definition at line 87 of file Range.h.
Member Function Documentation
asInt()
unsigned int App::CellAddress::asInt () const inline protected
Definition at line 158 of file Range.h.
Referenced by col(), row(), setCol(), and setRow().
col()
int App::CellAddress::col () const inline
Definition at line 99 of file Range.h.
References asInt().
Referenced by _getBorder(), App::VariableExpression::_moveCells(), App::RangeExpression::_moveCells(), App::VariableExpression::_offsetCells(), App::RangeExpression::_offsetCells(), SpreadsheetGui::DlgSheetConf::accept(), CurrentAddressLock::CurrentAddressLock(), SpreadsheetGui::DlgBindSheet::DlgBindSheet(), Drawing::FeatureViewSpreadsheet::execute(), Spreadsheet::Sheet::getCellBinding(), Spreadsheet::PropertySheet::getRange(), TechDraw::DrawViewSpreadsheet::getSheetImage(), Spreadsheet::PropertySheet::mergeCells(), Spreadsheet::PropertySheet::pasteCells(), SpreadsheetGui::SheetTableView::pasteClipboard(), SpreadsheetGui::DlgSheetConf::prepare(), App::Range::Range(), Spreadsheet::PropertySheet::Restore(), SpreadsheetGui::SheetView::select(), SpreadsheetGui::SheetView::setCurrentIndex(), Spreadsheet::PropertySheet::setPathValue(), SpreadsheetGui::SheetTableView::setSheet(), Spreadsheet::PropertySheet::splitCell(), and SpreadsheetGui::SheetView::updateCell().
isAbsoluteCol()
bool App::CellAddress::isAbsoluteCol () const inline
Definition at line 144 of file Range.h.
Referenced by App::VariableExpression::_offsetCells(), and App::RangeExpression::_offsetCells().
isAbsoluteRow()
bool App::CellAddress::isAbsoluteRow () const inline
Definition at line 139 of file Range.h.
Referenced by App::VariableExpression::_offsetCells(), and App::RangeExpression::_offsetCells().
isValid()
bool App::CellAddress::isValid () inline
Definition at line 134 of file Range.h.
Referenced by App::VariableExpression::_moveCells(), App::RangeExpression::_moveCells(), App::VariableExpression::_offsetCells(), App::RangeExpression::_offsetCells(), SpreadsheetGui::DlgBindSheet::accept(), Spreadsheet::Cell::Cell(), Spreadsheet::Sheet::getDynamicPropertyByName(), Spreadsheet::Sheet::getPropertyByName(), Spreadsheet::PropertySheet::getPyValue(), Spreadsheet::PropertySheet::getRange(), parseAbsoluteAddress(), and Spreadsheet::PropertySheet::pasteCells().
operator!=()
bool App::CellAddress::operator!= (const CellAddress & other) const inline
Definition at line 129 of file Range.h.
operator<()
bool App::CellAddress::operator< (const CellAddress & other) const inline
Definition at line 114 of file Range.h.
operator==()
bool App::CellAddress::operator== (const CellAddress & other) const inline
Definition at line 124 of file Range.h.
operator>()
bool App::CellAddress::operator> (const CellAddress & other) const inline
Definition at line 119 of file Range.h.
parseAbsoluteAddress()
bool App::CellAddress::parseAbsoluteAddress (const char * address)
App::CellAddress::parseAbsoluteAddress.
Parameters
address If the passed string is a valid and absolute cell address it will be assigned to this instance.
Returns
True if it's an absolute cell address and false otherwise
Definition at line 317 of file Range.cpp.
References isValid(), App::maybeAbsolute(), and App::stringToAddress().
Referenced by App::FeatureTestAbsAddress::execute(), and App::ObjectIdentifier::verify().
row()
int App::CellAddress::row () const inline
Definition at line 94 of file Range.h.
References asInt().
Referenced by _getBorder(), App::VariableExpression::_moveCells(), App::RangeExpression::_moveCells(), App::VariableExpression::_offsetCells(), App::RangeExpression::_offsetCells(), SpreadsheetGui::DlgSheetConf::accept(), CurrentAddressLock::CurrentAddressLock(), SpreadsheetGui::DlgBindSheet::DlgBindSheet(), Drawing::FeatureViewSpreadsheet::execute(), SpreadsheetGui::SheetTableView::finishEditWithMove(), Spreadsheet::Sheet::getCellBinding(), Spreadsheet::PropertySheet::getRange(), TechDraw::DrawViewSpreadsheet::getSheetImage(), Spreadsheet::PropertySheet::mergeCells(), Spreadsheet::PropertySheet::pasteCells(), SpreadsheetGui::SheetTableView::pasteClipboard(), SpreadsheetGui::DlgSheetConf::prepare(), App::Range::Range(), Spreadsheet::PropertySheet::Restore(), SpreadsheetGui::SheetView::select(), SpreadsheetGui::SheetView::setCurrentIndex(), Spreadsheet::PropertySheet::setPathValue(), SpreadsheetGui::SheetTableView::setSheet(), Spreadsheet::PropertySheet::splitCell(), and SpreadsheetGui::SheetView::updateCell().
setCol()
void App::CellAddress::setCol (int c, bool clip = false) inline
Definition at line 109 of file Range.h.
References asInt().
Referenced by App::VariableExpression::_moveCells(), App::RangeExpression::_moveCells(), App::VariableExpression::_offsetCells(), App::RangeExpression::_offsetCells(), SpreadsheetGui::DlgBindSheet::DlgBindSheet(), SpreadsheetGui::DlgSheetConf::DlgSheetConf(), Spreadsheet::PropertySheet::getRange(), and Spreadsheet::PropertySheet::setPathValue().
setRow()
void App::CellAddress::setRow (int r, bool clip = false) inline
Definition at line 104 of file Range.h.
References asInt().
Referenced by App::VariableExpression::_moveCells(), App::RangeExpression::_moveCells(), App::VariableExpression::_offsetCells(), App::RangeExpression::_offsetCells(), SpreadsheetGui::DlgBindSheet::DlgBindSheet(), Spreadsheet::PropertySheet::getRange(), SpreadsheetGui::DlgSheetConf::prepare(), and Spreadsheet::PropertySheet::setPathValue().
toString()
std::string App::CellAddress::toString (Cell cell = Cell::ShowFull) const
Convert given cell address into its string representation.
Returns
Address given as a string.
Definition at line 281 of file Range.cpp.
References toolbit-attributes::s, and Base::Flags< Enum >::testFlag().
Referenced by App::VariableExpression::_moveCells(), App::RangeExpression::_moveCells(), App::VariableExpression::_offsetCells(), App::RangeExpression::_offsetCells(), SpreadsheetGui::DlgSheetConf::accept(), Spreadsheet::Sheet::clear(), SpreadsheetGui::SheetView::confirmAliasChanged(), SpreadsheetGui::SpreadsheetDelegate::createEditor(), SpreadsheetGui::SheetViewPy::currentIndex(), SpreadsheetGui::SheetModel::data(), SpreadsheetGui::DlgBindSheet::DlgBindSheet(), SpreadsheetGui::DlgSheetConf::DlgSheetConf(), Drawing::FeatureViewSpreadsheet::execute(), Spreadsheet::Sheet::getAddressFromAlias(), Spreadsheet::PropertySheet::getBinding(), Spreadsheet::Cell::getFormattedQuantity(), Spreadsheet::Sheet::getProperty(), Spreadsheet::PropertySheet::getPyValue(), TechDraw::DrawViewSpreadsheet::getSheetImage(), SpreadsheetGui::DlgSheetConf::onDiscard(), Spreadsheet::PropertySheet::pasteCells(), SpreadsheetGui::DlgSheetConf::prepare(), Spreadsheet::Sheet::providesTo(), Spreadsheet::Cell::save(), SpreadsheetGui::SheetViewPy::selectedCells(), Spreadsheet::PropertySheet::setAlias(), Spreadsheet::Sheet::setAlias(), Spreadsheet::Cell::setException(), Spreadsheet::Sheet::setFloatProperty(), Spreadsheet::Sheet::setIntegerProperty(), Spreadsheet::Sheet::setObjectProperty(), Spreadsheet::Sheet::setQuantityProperty(), Spreadsheet::Cell::setResolveException(), Spreadsheet::Sheet::setStringProperty(), Spreadsheet::Sheet::updateProperty(), and App::ObjectIdentifier::verify().
Member Data Documentation
_absCol
bool App::CellAddress::_absCol protected
Definition at line 166 of file Range.h.
_absRow
bool App::CellAddress::_absRow protected
Definition at line 165 of file Range.h.
_col
short App::CellAddress::_col protected
Definition at line 164 of file Range.h.
_row
short App::CellAddress::_row protected
Definition at line 163 of file Range.h.
MAX_COLUMNS
const int App::CellAddress::MAX_COLUMNS = 26 * 26 + 26 static
Definition at line 155 of file Range.h.
MAX_ROWS
const int App::CellAddress::MAX_ROWS = 16384 static
Definition at line 153 of file Range.h.
Referenced by App::validRow().
The documentation for this struct was generated from the following files:
Range.h
Range.cpp