FreeCAD: App::TransactionFactory Class Reference
App::TransactionFactory Class Reference
#include <Transactions.h>
Public Member Functions
TransactionObject * createTransaction (const Base::Type &type) const
void addProducer (const Base::Type &type, Base::AbstractProducer *producer)
Static Public Member Functions
static TransactionFactory & instance ()
static void destruct ()
Detailed Description
Definition at line 182 of file Transactions.h.
Member Function Documentation
addProducer()
void TransactionFactory::addProducer (const Base::Type & type, Base::AbstractProducer * producer)
Definition at line 519 of file Transactions.cpp.
References Path.Post.scripts.grbl_post::type.
createTransaction()
TransactionObject * TransactionFactory::createTransaction (const Base::Type & type) const
Creates a transaction object for the given type id.
Definition at line 527 of file Transactions.cpp.
References Path.Post.scripts.grbl_post::type.
Referenced by App::Transaction::addObjectChange(), App::Transaction::addObjectDel(), App::Transaction::addObjectNew(), and App::Transaction::addOrRemoveProperty().
destruct()
void TransactionFactory::destruct () static
Definition at line 513 of file Transactions.cpp.
instance()
TransactionFactory & TransactionFactory::instance () static
Definition at line 505 of file Transactions.cpp.
Referenced by App::Transaction::addObjectChange(), App::Transaction::addObjectDel(), App::Transaction::addObjectNew(), and App::Transaction::addOrRemoveProperty().
The documentation for this class was generated from the following files:
Transactions.h
Transactions.cpp