FreeCAD: MeshPart::CurveProjectorShape Class Reference
MeshPart::CurveProjectorShape Class Reference
#include <CurveProjector.h>
Public Member Functions
CurveProjectorShape (const TopoDS_Shape &aShape, const MeshKernel &pMesh)
~CurveProjectorShape () override=default
void projectCurve (const TopoDS_Edge &aEdge, std::vector< FaceSplitEdge > &vSplitEdges)
bool findStartPoint (const MeshKernel &MeshK, const Base::Vector3f &Pnt, Base::Vector3f &Rslt, MeshCore::FacetIndex &FaceIndex)
Public Member Functions inherited from MeshPart::CurveProjector
CurveProjector (const TopoDS_Shape &aShape, const MeshKernel &pMesh)
virtual ~CurveProjector ()=default
result_type & result ()
void writeIntersectionPointsToFile (const char *name="export_pts.asc")
Protected Member Functions
void Do () override
Additional Inherited Members
Public Types inherited from MeshPart::CurveProjector
using result_type = std::map< TopoDS_Edge, std::vector< FaceSplitEdge >, TopoDSLess< TopoDS_Edge > >
Protected Attributes inherited from MeshPart::CurveProjector
const TopoDS_Shape & _Shape
const MeshKernel & _Mesh
result_type mvEdgeSplitPoints
Detailed Description
Project by intersection face planes with the curve
Definition at line 94 of file CurveProjector.h.
Constructor & Destructor Documentation
CurveProjectorShape()
CurveProjectorShape::CurveProjectorShape (const TopoDS_Shape & aShape, const MeshKernel & pMesh)
Definition at line 95 of file CurveProjector.cpp.
References Do().
~CurveProjectorShape()
MeshPart::CurveProjectorShape::~CurveProjectorShape () override default
Member Function Documentation
Do()
void CurveProjectorShape::Do () override protected virtual
Implements MeshPart::CurveProjector.
Definition at line 101 of file CurveProjector.cpp.
References MeshPart::CurveProjector::_Shape, MeshPart::CurveProjector::mvEdgeSplitPoints, and projectCurve().
Referenced by CurveProjectorShape().
findStartPoint()
bool CurveProjectorShape::findStartPoint (const MeshKernel & MeshK, const Base::Vector3f & Pnt, Base::Vector3f & Rslt, MeshCore::FacetIndex & FaceIndex)
Definition at line 231 of file CurveProjector.cpp.
References geoff_geometry::Dist(), FLOAT_MAX, MeshCore::MeshGeomFacet::Foraminate(), MeshCore::MeshGeomFacet::GetNormal(), MeshCore::MeshFacetIterator::Init(), FreeCADInit::Length, MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), and MeshCore::MeshFacetIterator::Position().
Referenced by projectCurve().
projectCurve()
void CurveProjectorShape::projectCurve (const TopoDS_Edge & aEdge, std::vector< FaceSplitEdge > & vSplitEdges)
Definition at line 111 of file CurveProjector.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshPart::CurveProjector::_Mesh, Base::Console(), MeshCore::FACET_INDEX_MAX, findStartPoint(), FLOAT_MAX, MeshCore::MeshKernel::GetFacet(), MeshCore::MeshKernel::GetFacetNeighbours(), MeshCore::MeshGeomFacet::GetNormal(), Handle(), SplineSurface::i, RobotExample::l, Base::ConsoleSingleton::Log(), MeshPart::CurveProjector::FaceSplitEdge::p1, MeshPart::CurveProjector::FaceSplitEdge::p2, MeshPart::CurveProjector::FaceSplitEdge::ulFaceIndex, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by Do().
The documentation for this class was generated from the following files:
CurveProjector.h
CurveProjector.cpp