FreeCAD: Gui::MacroFile Class Reference
Gui::MacroFile Class Reference
#include <Macro.h>
Public Member Functions
MacroFile ()
void open (const char *sName)
bool isOpen () const
indicates if a macro recording is in progress
void append (const QString &)
void append (const QStringList &)
QString fileName () const
bool commit ()
void cancel ()
Detailed Description
Definition at line 59 of file Macro.h.
Constructor & Destructor Documentation
MacroFile()
MacroFile::MacroFile () default
Member Function Documentation
append() [1/2]
void MacroFile::append (const QString & line)
Definition at line 64 of file Macro.cpp.
Referenced by Gui::MacroManager::setModule().
append() [2/2]
void MacroFile::append (const QStringList & lines)
Definition at line 69 of file Macro.cpp.
cancel()
void MacroFile::cancel ()
Definition at line 129 of file Macro.cpp.
Referenced by Gui::MacroManager::cancel().
commit()
bool MacroFile::commit ()
Definition at line 74 of file Macro.cpp.
References DrawingExample::file, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by draftguitools.gui_offset.Offset::action(), draftguitools.gui_styles.ApplyStyle::Activated(), draftguitools.gui_points.Point::click(), Gui::MacroManager::commit(), draftguitools.gui_labels.Label::create(), draftguitools.gui_dimensions.Dimension::create_angle_dimension(), draftguitools.gui_dimensions.Dimension::create_linear_dimension(), draftguitools.gui_dimensions.Dimension::create_linear_dimension_obj(), draftguitools.gui_dimensions.Dimension::create_radial_dimension_obj(), draftguitools.gui_rectangles.Rectangle::createObject(), draftguitools.gui_ellipses.Ellipse::createObject(), draftguitools.gui_texts.Text::createObject(), draftguitools.gui_stretch.Stretch::doStretch(), draftguitools.gui_fillets.Fillet::draw_arc(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), draftguitools.gui_lines.Line::finish(), draftguitools.gui_splines.BSpline::finish(), draftguitools.gui_beziers.BezCurve::finish(), draftguitools.gui_beziers.CubicBezCurve::finish(), draftguitools.gui_arcs.Arc_3Points::getPoint(), draftguitools.gui_mirror.Mirror::mirror(), draftguitools.gui_move.Move::move_object(), draftguitools.gui_move.Move::move_subelements(), draftguitools.gui_offset.Offset::numericRadius(), bimcommands.BimShape2DView.BIM_Shape2DView::proceed(), draftguitools.gui_join.Join::proceed(), draftguitools.gui_draft2sketch.Draft2Sketch::proceed(), draftguitools.gui_downgrade.Downgrade::proceed(), draftguitools.gui_upgrade.Upgrade::proceed(), draftguitools.gui_pathtwistedarray.PathTwistedArray::proceed(), draftguitools.gui_shape2dview.Shape2DView::proceed(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_pointarray.PointArray::proceed(), draftguitools.gui_patharray.PathArray::proceed(), draftguitools.gui_rotate.Rotate::rotate_object(), draftguitools.gui_rotate.Rotate::rotate_subelements(), draftguitools.gui_scale.Scale::scale_object(), draftguitools.gui_scale.Scale::scale_subelements(), and draftguitools.gui_scale.Scale::scale_with_clone().
fileName()
QString Gui::MacroFile::fileName () const inline
Definition at line 70 of file Macro.h.
Referenced by Gui::MacroManager::cancel(), and Gui::MacroManager::commit().
isOpen()
bool Gui::MacroFile::isOpen () const inline
indicates if a macro recording is in progress
Definition at line 65 of file Macro.h.
Referenced by Gui::MacroManager::setModule().
open()
void MacroFile::open (const char * sName)
Definition at line 48 of file Macro.cpp.
Referenced by Gui::MacroManager::open().
The documentation for this class was generated from the following files:
Macro.h
Macro.cpp