FreeCAD: MeshCore::MeshTrimByPlane Class Reference
MeshCore::MeshTrimByPlane Class Reference
#include <TrimByPlane.h>
Public Member Functions
MeshTrimByPlane (MeshKernel &mesh)
void CheckFacets (const MeshFacetGrid &rclGrid, const Base::Vector3f &base, const Base::Vector3f &normal, std::vector< FacetIndex > &trimFacets, std::vector< FacetIndex > &removeFacets) const
void TrimFacets (const std::vector< FacetIndex > &trimFacets, const Base::Vector3f &base, const Base::Vector3f &normal, std::vector< MeshGeomFacet > &trimmedFacets)
Detailed Description
Trim the facets in 3D with a plane
Author
Werner Mayer
Definition at line 56 of file TrimByPlane.h.
Constructor & Destructor Documentation
MeshTrimByPlane()
MeshTrimByPlane::MeshTrimByPlane (MeshKernel & mesh) explicit
Definition at line 35 of file TrimByPlane.cpp.
Member Function Documentation
CheckFacets()
void MeshTrimByPlane::CheckFacets (const MeshFacetGrid & rclGrid, const Base::Vector3f & base, const Base::Vector3f & normal, std::vector< FacetIndex > & trimFacets, std::vector< FacetIndex > & removeFacets) const
Checks all facets for intersection with the plane and writes all touched facets into the vector
Definition at line 39 of file TrimByPlane.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, Base::BoundBox3< Precision >::CalcPoint(), Base::Vector3< float_type >::DistanceToPlane(), MeshCore::MeshGridIterator::GetBoundBox(), MeshCore::MeshGridIterator::GetElements(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshGridIterator::Init(), MeshCore::MeshGeomFacet::IntersectWithPlane(), Base::BoundBox3< Precision >::IsCutPlane(), MeshCore::MeshGridIterator::More(), MeshCore::MeshGridIterator::Next(), and Base::BoundBox3< Precision >::TLB.
TrimFacets()
void MeshTrimByPlane::TrimFacets (const std::vector< FacetIndex > & trimFacets, const Base::Vector3f & base, const Base::Vector3f & normal, std::vector< MeshGeomFacet > & trimmedFacets)
The facets from trimFacets will be trimmed or deleted and trimmedFacets holds the newly generated facets
Definition at line 145 of file TrimByPlane.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, Base::Vector3< float_type >::DistanceToPlane(), and MeshCore::MeshKernel::GetFacet().
The documentation for this class was generated from the following files:
TrimByPlane.h
TrimByPlane.cpp