FreeCAD: PartGui::EllipsoidPrimitive Class Reference
PartGui::EllipsoidPrimitive Class Reference
#include <DlgPrimitives.h>
Public Member Functions
EllipsoidPrimitive (std::shared_ptr< Ui_DlgPrimitives > ui, Part::Ellipsoid *feature=nullptr)
const char * getDefaultName () const override
QString create (const QString &objectName, const QString &placement) const override
QString change (const QString &objectName, const QString &placement) const override
void changeValue (QObject *) override
Public Member Functions inherited from PartGui::AbstractPrimitive
AbstractPrimitive (Part::Primitive *feature=nullptr)
~AbstractPrimitive () override=default
bool hasValidPrimitive () const
Additional Inherited Members
Protected Member Functions inherited from PartGui::AbstractPrimitive
void connectSignalMapper (QSignalMapper *mapper)
Protected Attributes inherited from PartGui::AbstractPrimitive
App::DocumentObjectWeakPtrT featurePtr
Detailed Description
Definition at line 190 of file DlgPrimitives.h.
Constructor & Destructor Documentation
EllipsoidPrimitive()
EllipsoidPrimitive::EllipsoidPrimitive (std::shared_ptr< Ui_DlgPrimitives > ui, Part::Ellipsoid * feature = nullptr)
Definition at line 673 of file DlgPrimitives.cpp.
References Part::Ellipsoid::Angle1, Part::Ellipsoid::Angle2, Part::Ellipsoid::Angle3, PartGui::connectMapSignalMapper(), PartGui::AbstractPrimitive::connectSignalMapper(), App::PropertyQuantity::getQuantityValue(), Part::Ellipsoid::Radius1, Part::Ellipsoid::Radius2, Part::Ellipsoid::Radius3, and Gui::QuantitySpinBox::valueChanged().
Member Function Documentation
change()
QString EllipsoidPrimitive::change (const QString & objectName, const QString & placement) const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 738 of file DlgPrimitives.cpp.
References PartGui::safeQuantityQString().
changeValue()
void EllipsoidPrimitive::changeValue (QObject * widget) override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 758 of file DlgPrimitives.cpp.
References Part::Ellipsoid::Angle1, Part::Ellipsoid::Angle2, Part::Ellipsoid::Angle3, App::DocumentObjectWeakPtrT::expired(), PartGui::AbstractPrimitive::featurePtr, App::DocumentObjectWeakPtrT::get(), Part::Ellipsoid::Radius1, Part::Ellipsoid::Radius2, Part::Ellipsoid::Radius3, App::DocumentObject::recomputeFeature(), and App::PropertyQuantity::setValue().
create()
QString EllipsoidPrimitive::create (const QString & objectName, const QString & placement) const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 715 of file DlgPrimitives.cpp.
References PartGui::safeQuantityQString().
getDefaultName()
const char * EllipsoidPrimitive::getDefaultName () const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 710 of file DlgPrimitives.cpp.
The documentation for this class was generated from the following files:
DlgPrimitives.h
DlgPrimitives.cpp