FreeCAD: ifc2x3.ifcconnectionportgeometry Class Reference
ifc2x3.ifcconnectionportgeometry Class Reference
Public Member Functions
def __init__ (self, locationatrelatingelement, locationatrelatedelement, profileofport)
def locationatrelatingelement ()
def locationatrelatedelement ()
def profileofport ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
locationatrelatingelement
locationatrelatedelement
profileofport
Detailed Description
Entity ifcconnectionportgeometry definition.
:param locationatrelatingelement
:type locationatrelatingelement:ifcaxis2placement
:param locationatrelatedelement
:type locationatrelatedelement:ifcaxis2placement
:param profileofport
:type profileofport:ifcprofiledef
Definition at line 32099 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcconnectionportgeometry.__init__ (self, locationatrelatingelement, locationatrelatedelement, profileofport)
Definition at line 32111 of file ifc2x3.py.
Member Function Documentation
locationatrelatedelement()
def ifc2x3.ifcconnectionportgeometry.locationatrelatedelement ()
Definition at line 32132 of file ifc2x3.py.
References ifc2x3.ifcconnectionportgeometry._locationatrelatedelement, SCL.TypeChecker.check_type(), ifc2x3.ifcaxis2placement, and ifc2x3.ifcconnectionportgeometry.locationatrelatedelement.
locationatrelatingelement()
def ifc2x3.ifcconnectionportgeometry.locationatrelatingelement ()
Definition at line 32118 of file ifc2x3.py.
References ifc2x3.ifcconnectionportgeometry._locationatrelatingelement, SCL.TypeChecker.check_type(), ifc2x3.ifcaxis2placement, and ifc2x3.ifcconnectionportgeometry.locationatrelatingelement.
profileofport()
def ifc2x3.ifcconnectionportgeometry.profileofport ()
Definition at line 32146 of file ifc2x3.py.
References ifc2x3.ifcconnectionportgeometry._profileofport, SCL.TypeChecker.check_type(), and ifc2x3.ifcconnectionportgeometry.profileofport.
Member Data Documentation
locationatrelatedelement
ifc2x3.ifcconnectionportgeometry.locationatrelatedelement
Definition at line 32114 of file ifc2x3.py.
Referenced by ifc2x3.ifcconnectionportgeometry.locationatrelatedelement().
locationatrelatingelement
ifc2x3.ifcconnectionportgeometry.locationatrelatingelement
Definition at line 32113 of file ifc2x3.py.
Referenced by ifc2x3.ifcconnectionportgeometry.locationatrelatingelement().
profileofport
ifc2x3.ifcconnectionportgeometry.profileofport
Definition at line 32115 of file ifc2x3.py.
Referenced by ifc2x3.ifcconnectionportgeometry.profileofport().
The documentation for this class was generated from the following file:
ifc2x3.py