FreeCAD: Path.Op.FeatureExtension Namespace Reference
Path.Op.FeatureExtension Namespace Reference
Classes
class Extension
Functions
def endPoints (edgeOrWire)
def includesPoint (p, pts)
def selectOffsetWire (feature, wires)
def extendWire (feature, wire, length)
def createExtension (obj, extObj, extFeature, extSub)
def readObjExtensionFeature (obj)
def getExtensions (obj)
def setExtensions (obj, extensions)
def getStandardAngle (x, y)
def arcAdjustmentAngle (arc1, arc2)
def initialize_properties (obj)
def set_default_property_values (obj, job)
def SetupProperties ()
def getExtendOutlineFace (base_shape, face, extension, remHoles=False, offset_tolerance=1e-4)
def getWaterlineFace (base_shape, face)
Variables
PathUtils
translate
Function Documentation
arcAdjustmentAngle()
def Path.Op.FeatureExtension.arcAdjustmentAngle (arc1, arc2)
arcAdjustmentAngle(arc1, arc2)...
Return adjustment angle to apply to arc2 in order to align it with arc1.
Arcs must have same center point.
Definition at line 186 of file FeatureExtension.py.
References Path.Op.FeatureExtension.getStandardAngle().
Referenced by Path.Op.FeatureExtension.Extension.getWire().
createExtension()
def Path.Op.FeatureExtension.createExtension (obj, extObj, extFeature, extSub)
Definition at line 135 of file FeatureExtension.py.
Referenced by Path.Op.FeatureExtension.getExtensions().
endPoints()
def Path.Op.FeatureExtension.endPoints (edgeOrWire)
endPoints(edgeOrWire) ... return the first and last point of the wire or the edge, assuming the argument is not a closed wire.
Definition at line 50 of file FeatureExtension.py.
References Path.Geom.pointsCoincide(), and Path.Post.scripts.grbl_post.type.
Referenced by Path.Op.FeatureExtension.extendWire(), TechDraw::DrawViewDimExtent.getPointsExtent(), and Path.Op.FeatureExtension.Extension.getWire().
extendWire()
def Path.Op.FeatureExtension.extendWire (feature, wire, length)
extendWire(wire, length) ... return a closed Wire which extends wire by length
Definition at line 95 of file FeatureExtension.py.
References Path.Log.debug(), Path.Op.FeatureExtension.endPoints(), Path.Op.FeatureExtension.includesPoint(), Path.Op.FeatureExtension.selectOffsetWire(), Path.Log.track(), and Path.Post.scripts.grbl_post.type.
Referenced by Path.Op.FeatureExtension.Extension.getSubLink(), and Path.Op.FeatureExtension.Extension.getWire().
getExtendOutlineFace()
def Path.Op.FeatureExtension.getExtendOutlineFace (base_shape, face, extension, remHoles = False, offset_tolerance = 1e-4)
getExtendOutlineFace(obj, base_shape, face, extension, remHoles) ...
Creates an extended face for the pocket, taking into consideration lateral
collision with the greater base shape.
Arguments are:
    parent base shape of face,
    target face,
    extension magnitude,
    remove holes boolean,
    offset tolerance = 1e-4 default
The default value of 1e-4 for offset tolerance is the same default value
at getOffsetArea() function definition.
Return is an all access face extending the specified extension value from the source face.
Definition at line 514 of file FeatureExtension.py.
References KDL.abs(), Path.Log.error(), and Path.Geom.isRoughly().
getExtensions()
def Path.Op.FeatureExtension.getExtensions (obj)
Definition at line 159 of file FeatureExtension.py.
References Path.Op.FeatureExtension.createExtension(), and Path.Log.debug().
Referenced by Part::PropertyGeometryList.Save().
getStandardAngle()
def Path.Op.FeatureExtension.getStandardAngle (x, y)
getStandardAngle(x, y)...
Return standard degree angle given x and y values of vector.
Definition at line 177 of file FeatureExtension.py.
Referenced by Path.Op.FeatureExtension.arcAdjustmentAngle().
getWaterlineFace()
def Path.Op.FeatureExtension.getWaterlineFace (base_shape, face)
getWaterlineFace(base_shape, face) ...
Creates a waterline extension face for the target face,
taking into consideration the greater base shape.
Arguments are: parent base shape and target face.
Return is a waterline face at height of the target face.
Definition at line 580 of file FeatureExtension.py.
References Path.Geom.isRoughly().
includesPoint()
def Path.Op.FeatureExtension.includesPoint (p, pts)
includesPoint(p, pts) ... answer True if the collection of pts includes the point p
Definition at line 72 of file FeatureExtension.py.
References Path.Geom.pointsCoincide().
Referenced by Path.Op.FeatureExtension.extendWire().
initialize_properties()
def Path.Op.FeatureExtension.initialize_properties (obj)
initialize_properties(obj)... Adds feature properties to object argument
Definition at line 470 of file FeatureExtension.py.
References Arch.QT_TRANSLATE_NOOP.
readObjExtensionFeature()
def Path.Op.FeatureExtension.readObjExtensionFeature (obj)
readObjExtensionFeature(obj)...
Return three item string tuples (base name, feature, subfeature) extracted from obj.ExtensionFeature
Definition at line 146 of file FeatureExtension.py.
selectOffsetWire()
def Path.Op.FeatureExtension.selectOffsetWire (feature, wires)
selectOffsetWire(feature, wires) ... returns the Wire in wires which is does not intersect with feature
Definition at line 81 of file FeatureExtension.py.
Referenced by Path.Op.FeatureExtension.extendWire().
set_default_property_values()
def Path.Op.FeatureExtension.set_default_property_values (obj, job)
set_default_property_values(obj, job) ... set default values for feature properties
Definition at line 501 of file FeatureExtension.py.
setExtensions()
def Path.Op.FeatureExtension.setExtensions (obj, extensions)
Definition at line 172 of file FeatureExtension.py.
References Path.Log.track().
SetupProperties()
def Path.Op.FeatureExtension.SetupProperties ()
SetupProperties()... Returns list of feature property names
Definition at line 507 of file FeatureExtension.py.
Variable Documentation
PathUtils
Path.Op.FeatureExtension.PathUtils
Definition at line 32 of file FeatureExtension.py.
translate
Path.Op.FeatureExtension.translate
Definition at line 47 of file FeatureExtension.py.