FreeCAD: FemGui::DlgSettingsFemGeneralImp Class Reference
FemGui::DlgSettingsFemGeneralImp Class Reference
#include <DlgSettingsFemGeneralImp.h>
Public Member Functions
DlgSettingsFemGeneralImp (QWidget *parent=nullptr)
~DlgSettingsFemGeneralImp () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void saveSettings () override
void loadSettings () override
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
Definition at line 57 of file DlgSettingsFemGeneralImp.h.
Constructor & Destructor Documentation
DlgSettingsFemGeneralImp()
DlgSettingsFemGeneralImp::DlgSettingsFemGeneralImp (QWidget * parent = nullptr) explicit
Definition at line 36 of file DlgSettingsFemGeneralImp.cpp.
References Fem::Tools::checkIfBinaryExists(), App::GetApplication(), ParameterGrp::GetInt(), and App::Application::GetParameterGroupByPath().
~DlgSettingsFemGeneralImp()
DlgSettingsFemGeneralImp::~DlgSettingsFemGeneralImp () override default
Member Function Documentation
changeEvent()
void DlgSettingsFemGeneralImp::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 116 of file DlgSettingsFemGeneralImp.cpp.
References SCL.SimpleDataTypes::e.
loadSettings()
void DlgSettingsFemGeneralImp::loadSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 97 of file DlgSettingsFemGeneralImp.cpp.
saveSettings()
void DlgSettingsFemGeneralImp::saveSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 81 of file DlgSettingsFemGeneralImp.cpp.
The documentation for this class was generated from the following files:
DlgSettingsFemGeneralImp.h
DlgSettingsFemGeneralImp.cpp