FreeCAD: TechDraw::DimensionAutoCorrect Class Reference
TechDraw::DimensionAutoCorrect Class Reference
#include <DimensionAutoCorrect.h>
Public Member Functions
DimensionAutoCorrect ()=default
DimensionAutoCorrect (DrawViewDimension *dim)
~DimensionAutoCorrect ()=default
bool referencesHaveValidGeometry (std::vector< bool > &referenceState) const
bool autocorrectReferences (std::vector< bool > &referenceState, ReferenceVector &repairedRefs) const
void set3dObjectCache (std::set< std::string > cache)
bool fixBrokenReferences (ReferenceVector &fixedReferences) const
Detailed Description
Definition at line 42 of file DimensionAutoCorrect.h.
Constructor & Destructor Documentation
DimensionAutoCorrect() [1/2]
TechDraw::DimensionAutoCorrect::DimensionAutoCorrect () default
DimensionAutoCorrect() [2/2]
TechDraw::DimensionAutoCorrect::DimensionAutoCorrect (DrawViewDimension * dim) inline explicit
Definition at line 46 of file DimensionAutoCorrect.h.
~DimensionAutoCorrect()
TechDraw::DimensionAutoCorrect::~DimensionAutoCorrect () default
Member Function Documentation
autocorrectReferences()
bool DimensionAutoCorrect::autocorrectReferences (std::vector< bool > & referenceState, ReferenceVector & repairedRefs) const
try to correct references that point to non-existent geometry or when the saved geometry does not match the current geometry the reference points to. referenceState is the output of a previous use of referencesHaveValidGeometry.
Definition at line 126 of file DimensionAutoCorrect.cpp.
References TechDraw::Preferences::autoCorrectDimRefs(), Part::TopoShape::isNull(), and result.
fixBrokenReferences()
bool DimensionAutoCorrect::fixBrokenReferences (ReferenceVector & fixedReferences) const
rebuild 3d references from saved geometry. returns true is all references have been repaired
Definition at line 554 of file DimensionAutoCorrect.cpp.
References TechDraw::ReferenceEntry::getObject(), and Part::TopoShape::getShape().
referencesHaveValidGeometry()
bool DimensionAutoCorrect::referencesHaveValidGeometry (std::vector< bool > & referenceState) const
true if references point to valid geometry and the valid geometry matches the corresponding saved geometry. this method does not correct anything, it just verifies if the references point to the same geometry as when the reference was created.
Definition at line 88 of file DimensionAutoCorrect.cpp.
References result.
set3dObjectCache()
void TechDraw::DimensionAutoCorrect::set3dObjectCache (std::set< std::string > cache) inline
Definition at line 54 of file DimensionAutoCorrect.h.
The documentation for this class was generated from the following files:
DimensionAutoCorrect.h
DimensionAutoCorrect.cpp