FreeCAD: TDHandlerDimension Class Reference
TDHandlerDimension Class Reference
Public Types
enum AvailableDimension {
AvailableDimension::FIRST, AvailableDimension::SECOND, AvailableDimension::THIRD, AvailableDimension::FOURTH,
AvailableDimension::FIFTH, AvailableDimension::RESET
}
enum SpecialDimension {
SpecialDimension::LineOr2PointsDistance, SpecialDimension::LineOr2PointsChamfer, SpecialDimension::ExtendDistance, SpecialDimension::ChainDistance,
SpecialDimension::CoordDistance, SpecialDimension::None
}
Public Member Functions
TDHandlerDimension (ReferenceVector refs, TechDraw::DrawViewPart *pFeat)
~TDHandlerDimension ()
void activated () override
void deactivated () override
void keyPressEvent (QKeyEvent *event) override
void keyReleaseEvent (QKeyEvent *event) override
void mouseMoveEvent (QMouseEvent *event) override
QGIDatumLabel * getDimLabel (DrawViewDimension *d)
void moveDimension (QPoint pos, DrawViewDimension *dim, bool textToMiddle=false, Base::Vector3d dir=Base::Vector3d(), Base::Vector3d delta=Base::Vector3d(), DimensionType type=DimensionType::Distance, int i=0)
QPointF getDimPositionToBe (QPoint pos, QPointF curPos=QPointF(), bool textToMiddle=false, Base::Vector3d dir=Base::Vector3d(), Base::Vector3d delta=Base::Vector3d(), DimensionType type=DimensionType::Distance, int i=0)
void finishDimensionMove ()
void setDimsSelectability (bool val)
void setDimSelectability (DrawViewDimension *d, bool val)
void mouseReleaseEvent (QMouseEvent *event) override
void onSelectionChanged (const Gui::SelectionChanges &msg) override
Public Member Functions inherited from TechDrawGui::TechDrawHandler
TechDrawHandler ()
virtual ~TechDrawHandler ()
void activate (QGVPage *vPage)
void deactivate () override
void quit () override
virtual void mousePressEvent (QMouseEvent *event)
TechDraw::DrawPage * getPage ()
Public Member Functions inherited from Gui::ToolHandler
ToolHandler ()=default
virtual ~ToolHandler ()=default
bool activate ()
void updateCursor ()
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Protected Member Functions
void handleInitialSelection ()
void finalizeCommand ()
ReferenceVector & getSelectionVector (ReferenceEntry &ref)
bool selectionEmpty ()
ReferenceVector allRefs ()
bool makeAppropriateDimension ()
void makeCts_Faces (bool &selAllowed)
void makeCts_2Point (bool &selAllowed)
void makeCts_3Point (bool &selAllowed)
void makeCts_4MorePoints (bool &selAllowed)
void makeCts_1Point1Line (bool &selAllowed)
void makeCts_1Point1Circle (bool &selAllowed)
void makeCts_1Point1Ellipse (bool &selAllowed)
void makeCts_1Line (bool &selAllowed)
void makeCts_2Line (bool &selAllowed)
void makeCts_1Line1Circle (bool &selAllowed)
void makeCts_1Line1Ellipse (bool &selAllowed)
void makeCts_1Circle (bool &selAllowed)
void makeCts_2Circle (bool &selAllowed)
void makeCts_1Ellipse (bool &selAllowed)
void makeCts_2Ellipses (bool &selAllowed)
void makeCts_1Spline (bool &selAllowed)
void makeCts_1SplineAndMore (bool &selAllowed)
void createAreaDimension (ReferenceEntry ref)
void createRadiusDiameterDimension (ReferenceEntry ref, bool firstCstr)
void createAngleDimension (ReferenceEntry ref1, ReferenceEntry ref2)
void create3pAngleDimension (ReferenceVector refs)
void createArcLengthDimension (ReferenceEntry ref)
void createDistanceDimension (std::string type, ReferenceVector refs, bool chamfer=false)
void createExtentDistanceDimension (std::string type)
void updateDistanceType ()
void updateExtentDistanceType ()
void updateChainDistanceType ()
void createChainDimension (std::string type)
void createCoordDimension (std::string type)
bool isVerticalDistance (ReferenceVector refs)
QPixmap icon (std::string name)
void restartCommand (const char *cstrName)
void clearAndRestartCommand ()
void clearRefVectors ()
Protected Member Functions inherited from TechDrawGui::TechDrawHandler
QWidget * getCursorWidget () override
void setWidgetCursor (QCursor cursor) override
Protected Member Functions inherited from Gui::ToolHandler
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
void unsetCursor ()
void applyCursor ()
restitutes the DSH cached cursor (without any tail due to autoconstraints, ...)
void addCursorTail (std::vector< QPixmap > &pixmaps)
unsigned long getCrosshairColor ()
returns the color to be used for the crosshair (configurable as a parameter)
qreal devicePixelRatio ()
functions to set the cursor to a given svgName (to be migrated to NVI style)
View3DInventorViewer * getViewer ()
Protected Attributes
SpecialDimension specialDimension
AvailableDimension availableDimension
QPoint mousePos
ReferenceVector selPoints
ReferenceVector selLine
ReferenceVector selCircleArc
ReferenceVector selEllipseArc
ReferenceVector selSplineAndCo
ReferenceVector selFaces
ReferenceVector emptyVector
ReferenceEntry addedRef
ReferenceEntry removedRef
ReferenceVector initialSelection
TechDraw::DrawViewPart * partFeat
std::vector< DrawViewDimension * > dims
bool blockRemoveSel
Protected Attributes inherited from TechDrawGui::TechDrawHandler
QGVPage * viewPage
Protected Attributes inherited from Gui::ToolHandler
QCursor oldCursor
QCursor actCursor
QPixmap actCursorPixmap
Detailed Description
Definition at line 187 of file CommandCreateDims.cpp.
Member Enumeration Documentation
AvailableDimension
enum TDHandlerDimension::AvailableDimension strong
Enumerator
FIRST
SECOND
THIRD
FOURTH
FIFTH
RESET
Definition at line 215 of file CommandCreateDims.cpp.
SpecialDimension
enum TDHandlerDimension::SpecialDimension strong
Enumerator
LineOr2PointsDistance
LineOr2PointsChamfer
ExtendDistance
ChainDistance
CoordDistance
None
Definition at line 224 of file CommandCreateDims.cpp.
Constructor & Destructor Documentation
TDHandlerDimension()
TDHandlerDimension::TDHandlerDimension (ReferenceVector refs, TechDraw::DrawViewPart * pFeat) inline explicit
Definition at line 191 of file CommandCreateDims.cpp.
~TDHandlerDimension()
TDHandlerDimension::~TDHandlerDimension () inline
Definition at line 211 of file CommandCreateDims.cpp.
Member Function Documentation
activated()
void TDHandlerDimension::activated () inline override virtual
Reimplemented from Gui::ToolHandler.
Definition at line 234 of file CommandCreateDims.cpp.
References Gui::MainWindow::activeWindow(), Gui::getMainWindow(), Gui::SelectionSingleton::GreedySelection, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, Gui::Selection(), TechDrawGui::MDIViewPage::setDimensionsSelectability(), and Gui::SelectionSingleton::setSelectionStyle().
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::set_status_filter().
allRefs()
ReferenceVector TDHandlerDimension::allRefs () inline protected
Definition at line 732 of file CommandCreateDims.cpp.
References result.
clearAndRestartCommand()
void TDHandlerDimension::clearAndRestartCommand () inline protected
Definition at line 1381 of file CommandCreateDims.cpp.
References Gui::Command::abortCommand(), Gui::None, Gui::Command::openCommand(), and Arch::QT_TRANSLATE_NOOP.
clearRefVectors()
void TDHandlerDimension::clearRefVectors () inline protected
Definition at line 1391 of file CommandCreateDims.cpp.
create3pAngleDimension()
void TDHandlerDimension::create3pAngleDimension (ReferenceVector refs) inline protected
Definition at line 1115 of file CommandCreateDims.cpp.
References dimMaker().
createAngleDimension()
void TDHandlerDimension::createAngleDimension (ReferenceEntry ref1, ReferenceEntry ref2) inline protected
Definition at line 1101 of file CommandCreateDims.cpp.
References dimMaker(), TechDraw::isAngle, TechDraw::isValidMultiEdge(), and Arch::QT_TRANSLATE_NOOP.
createArcLengthDimension()
void TDHandlerDimension::createArcLengthDimension (ReferenceEntry ref) inline protected
Definition at line 1123 of file CommandCreateDims.cpp.
References TechDrawGui::makeArcLengthDimension().
createAreaDimension()
void TDHandlerDimension::createAreaDimension (ReferenceEntry ref) inline protected
Definition at line 1066 of file CommandCreateDims.cpp.
References dimMaker().
createChainDimension()
void TDHandlerDimension::createChainDimension (std::string type) inline protected
Definition at line 1322 of file CommandCreateDims.cpp.
References dimMaker(), SplineSurface::i, TechDrawGui::makeObliqueChainDimension(), positionDimText(), and Path.Post.scripts.grbl_post::type.
createCoordDimension()
void TDHandlerDimension::createCoordDimension (std::string type) inline protected
Definition at line 1338 of file CommandCreateDims.cpp.
References dimMaker(), SplineSurface::i, TechDrawGui::makeObliqueCoordDimension(), positionDimText(), and Path.Post.scripts.grbl_post::type.
createDistanceDimension()
void TDHandlerDimension::createDistanceDimension (std::string type, ReferenceVector refs, bool chamfer = false) inline protected
Definition at line 1131 of file CommandCreateDims.cpp.
References KDL::abs(), KDL::atan(), dimMaker(), TechDraw::pointPair::first(), TechDraw::DrawViewDimension::FormatSpec, TechDraw::DrawViewDimension::getLinearPoints(), App::PropertyString::getStrValue(), TechDraw::pointPair::second(), App::PropertyString::setValue(), Base::toDegrees(), Path.Post.scripts.grbl_post::type, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
createExtentDistanceDimension()
void TDHandlerDimension::createExtentDistanceDimension (std::string type) inline protected
Definition at line 1151 of file CommandCreateDims.cpp.
References Path.Post.scripts.grbl_post::type.
createRadiusDiameterDimension()
void TDHandlerDimension::createRadiusDiameterDimension (ReferenceEntry ref, bool firstCstr) inline protected
Definition at line 1074 of file CommandCreateDims.cpp.
References TechDraw::CIRCLE, dimMaker(), TechDraw::ELLIPSE, App::GetApplication(), ParameterGrp::GetBool(), TechDraw::DrawViewPart::getGeomByIndex(), TechDraw::DrawUtil::getIndexFromName(), App::Application::GetParameterGroupByPath(), TechDraw::ReferenceEntry::getSubName(), and Arch::QT_TRANSLATE_NOOP.
deactivated()
void TDHandlerDimension::deactivated () inline override virtual
Reimplemented from Gui::ToolHandler.
Definition at line 245 of file CommandCreateDims.cpp.
References Gui::Command::abortCommand(), Gui::MainWindow::activeWindow(), Gui::getMainWindow(), Gui::SelectionSingleton::NormalSelection, Gui::Selection(), TechDrawGui::MDIViewPage::setDimensionsSelectability(), and Gui::SelectionSingleton::setSelectionStyle().
finalizeCommand()
void TDHandlerDimension::finalizeCommand () inline protected
Definition at line 630 of file CommandCreateDims.cpp.
References Gui::SelectionSingleton::clearSelection(), Gui::Command::commitCommand(), App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), Gui::Selection(), and App::DocumentObject::touch().
finishDimensionMove()
void TDHandlerDimension::finishDimensionMove () inline
Definition at line 398 of file CommandCreateDims.cpp.
References TechDrawGui::Rez::appX(), Gui::Command::Doc, doCommand, App::DocumentObject::getNameInDocument(), MovieTool::x, and MovieTool::y.
getDimLabel()
QGIDatumLabel* TDHandlerDimension::getDimLabel (DrawViewDimension * d) inline
Definition at line 336 of file CommandCreateDims.cpp.
References Gui::Application::getViewProvider(), and Gui::Application::Instance.
getDimPositionToBe()
QPointF TDHandlerDimension::getDimPositionToBe (QPoint pos, QPointF curPos = QPointF(), bool textToMiddle = false, Base::Vector3d dir = Base::Vector3d(), Base::Vector3d delta = Base::Vector3d(), DimensionType type = DimensionType::Distance, int i = 0) inline
Definition at line 357 of file CommandCreateDims.cpp.
References activeDimAttributes, Sketcher::Distance, Sketcher::DistanceX, Sketcher::DistanceY, TechDraw::pointPair::first(), dimAttributes::getCascadeSpacing(), Gui::Application::getViewProvider(), TechDrawGui::Rez::guiX(), SplineSurface::i, Gui::Application::Instance, RobotExample::pos, Path.Post.scripts.grbl_post::type, MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, and Base::Vector3< float_type >::y.
getSelectionVector()
ReferenceVector& TDHandlerDimension::getSelectionVector (ReferenceEntry & ref) inline protected
Definition at line 655 of file CommandCreateDims.cpp.
References TechDraw::ARCOFCIRCLE, TechDraw::ARCOFELLIPSE, TechDraw::BSPLINE, TechDraw::CIRCLE, TechDraw::ELLIPSE, TechDraw::GENERIC, TechDraw::DrawUtil::getIndexFromName(), TechDraw::ReferenceEntry::getObject(), and TechDraw::ReferenceEntry::getSubName().
handleInitialSelection()
void TDHandlerDimension::handleInitialSelection () inline protected
Definition at line 605 of file CommandCreateDims.cpp.
icon()
QPixmap TDHandlerDimension::icon (std::string name) inline protected
Definition at line 1362 of file CommandCreateDims.cpp.
References Gui::BitmapFactory(), Gui::BitmapFactoryInst::pixmapFromSvg(), and OfflineRenderingUtils::viewer().
isVerticalDistance()
bool TDHandlerDimension::isVerticalDistance (ReferenceVector refs) inline protected
Definition at line 1354 of file CommandCreateDims.cpp.
References TechDraw::isDiagonal, and TechDraw::validateDimSelection().
keyPressEvent()
void TDHandlerDimension::keyPressEvent (QKeyEvent * event) inline override virtual
Implements TechDrawGui::TechDrawHandler.
Definition at line 255 of file CommandCreateDims.cpp.
keyReleaseEvent()
void TDHandlerDimension::keyReleaseEvent (QKeyEvent * event) inline override virtual
Reimplemented from TechDrawGui::TechDrawHandler.
Definition at line 282 of file CommandCreateDims.cpp.
References TechDrawGui::TechDrawHandler::keyReleaseEvent().
makeAppropriateDimension()
bool TDHandlerDimension::makeAppropriateDimension () inline protected
Definition at line 749 of file CommandCreateDims.cpp.
References Path.Dressup.Utils::selection().
makeCts_1Circle()
void TDHandlerDimension::makeCts_1Circle (bool & selAllowed) inline protected
Definition at line 976 of file CommandCreateDims.cpp.
References TechDraw::ARCOFCIRCLE, and Arch::QT_TRANSLATE_NOOP.
makeCts_1Ellipse()
void TDHandlerDimension::makeCts_1Ellipse (bool & selAllowed) inline protected
Definition at line 1010 of file CommandCreateDims.cpp.
References TechDraw::ARCOFELLIPSE, and Arch::QT_TRANSLATE_NOOP.
makeCts_1Line()
void TDHandlerDimension::makeCts_1Line (bool & selAllowed) inline protected
Definition at line 908 of file CommandCreateDims.cpp.
References Arch::QT_TRANSLATE_NOOP.
makeCts_1Line1Circle()
void TDHandlerDimension::makeCts_1Line1Circle (bool & selAllowed) inline protected
Definition at line 946 of file CommandCreateDims.cpp.
References Arch::QT_TRANSLATE_NOOP.
makeCts_1Line1Ellipse()
void TDHandlerDimension::makeCts_1Line1Ellipse (bool & selAllowed) inline protected
Definition at line 961 of file CommandCreateDims.cpp.
References Arch::QT_TRANSLATE_NOOP.
makeCts_1Point1Circle()
void TDHandlerDimension::makeCts_1Point1Circle (bool & selAllowed) inline protected
Definition at line 878 of file CommandCreateDims.cpp.
References Arch::QT_TRANSLATE_NOOP.
makeCts_1Point1Ellipse()
void TDHandlerDimension::makeCts_1Point1Ellipse (bool & selAllowed) inline protected
Definition at line 893 of file CommandCreateDims.cpp.
References Arch::QT_TRANSLATE_NOOP.
makeCts_1Point1Line()
void TDHandlerDimension::makeCts_1Point1Line (bool & selAllowed) inline protected
Definition at line 867 of file CommandCreateDims.cpp.
References Arch::QT_TRANSLATE_NOOP.
makeCts_1Spline()
void TDHandlerDimension::makeCts_1Spline (bool & selAllowed) inline protected
Definition at line 1044 of file CommandCreateDims.cpp.
References Arch::QT_TRANSLATE_NOOP.
makeCts_1SplineAndMore()
void TDHandlerDimension::makeCts_1SplineAndMore (bool & selAllowed) inline protected
Definition at line 1055 of file CommandCreateDims.cpp.
References Arch::QT_TRANSLATE_NOOP.
makeCts_2Circle()
void TDHandlerDimension::makeCts_2Circle (bool & selAllowed) inline protected
Definition at line 995 of file CommandCreateDims.cpp.
References Arch::QT_TRANSLATE_NOOP.
makeCts_2Ellipses()
void TDHandlerDimension::makeCts_2Ellipses (bool & selAllowed) inline protected
Definition at line 1029 of file CommandCreateDims.cpp.
References Arch::QT_TRANSLATE_NOOP.
makeCts_2Line()
void TDHandlerDimension::makeCts_2Line (bool & selAllowed) inline protected
Definition at line 931 of file CommandCreateDims.cpp.
References Arch::QT_TRANSLATE_NOOP.
makeCts_2Point()
void TDHandlerDimension::makeCts_2Point (bool & selAllowed) inline protected
Definition at line 805 of file CommandCreateDims.cpp.
References Arch::QT_TRANSLATE_NOOP.
makeCts_3Point()
void TDHandlerDimension::makeCts_3Point (bool & selAllowed) inline protected
Definition at line 825 of file CommandCreateDims.cpp.
References Arch::QT_TRANSLATE_NOOP.
makeCts_4MorePoints()
void TDHandlerDimension::makeCts_4MorePoints (bool & selAllowed) inline protected
Definition at line 852 of file CommandCreateDims.cpp.
References Arch::QT_TRANSLATE_NOOP.
makeCts_Faces()
void TDHandlerDimension::makeCts_Faces (bool & selAllowed) inline protected
Definition at line 794 of file CommandCreateDims.cpp.
References Arch::QT_TRANSLATE_NOOP.
mouseMoveEvent()
void TDHandlerDimension::mouseMoveEvent (QMouseEvent * event) inline override virtual
Implements TechDrawGui::TechDrawHandler.
Definition at line 294 of file CommandCreateDims.cpp.
References activeDimAttributes, TechDraw::pointPair::first(), dimAttributes::getCascadeSpacing(), TechDrawGui::Rez::guiX(), SplineSurface::i, Base::Vector3< float_type >::Normalize(), and TechDraw::pointPair::second().
mouseReleaseEvent()
void TDHandlerDimension::mouseReleaseEvent (QMouseEvent * event) inline override virtual
Reimplemented from TechDrawGui::TechDrawHandler.
Definition at line 424 of file CommandCreateDims.cpp.
References Gui::SelectionSingleton::clearSelection(), TechDrawGui::TechDrawHandler::mouseReleaseEvent(), Arch::QT_TRANSLATE_NOOP, Gui::SelectionSingleton::rmvSelection(), and Gui::Selection().
moveDimension()
void TDHandlerDimension::moveDimension (QPoint pos, DrawViewDimension * dim, bool textToMiddle = false, Base::Vector3d dir = Base::Vector3d(), Base::Vector3d delta = Base::Vector3d(), DimensionType type = DimensionType::Distance, int i = 0) inline
Definition at line 348 of file CommandCreateDims.cpp.
References SplineSurface::i, RobotExample::pos, and Path.Post.scripts.grbl_post::type.
onSelectionChanged()
void TDHandlerDimension::onSelectionChanged (const Gui::SelectionChanges & msg) inline override virtual
Implements Gui::SelectionObserver.
Definition at line 507 of file CommandCreateDims.cpp.
References Gui::SelectionChanges::AddSelection, Gui::SelectionChanges::ClrSelection, Path.Op.Surface::msg, Gui::SelectionChanges::RmvSelection, Gui::SelectionSingleton::rmvSelection(), and Gui::Selection().
restartCommand()
void TDHandlerDimension::restartCommand (const char * cstrName) inline protected
Definition at line 1373 of file CommandCreateDims.cpp.
References Gui::Command::abortCommand(), Gui::None, and Gui::Command::openCommand().
selectionEmpty()
bool TDHandlerDimension::selectionEmpty () inline protected
Definition at line 727 of file CommandCreateDims.cpp.
setDimSelectability()
void TDHandlerDimension::setDimSelectability (DrawViewDimension * d, bool val) inline
Definition at line 416 of file CommandCreateDims.cpp.
References toolbit-attributes::val.
setDimsSelectability()
void TDHandlerDimension::setDimsSelectability (bool val) inline
Definition at line 410 of file CommandCreateDims.cpp.
References toolbit-attributes::val.
updateChainDistanceType()
void TDHandlerDimension::updateChainDistanceType () inline protected
Definition at line 1258 of file CommandCreateDims.cpp.
References Sketcher::Distance, Sketcher::DistanceX, Sketcher::DistanceY, TechDraw::pointPair::first(), TechDraw::DrawViewDimension::getLinearPoints(), TechDrawGui::Rez::guiX(), KDL::max(), KDL::min(), Arch::QT_TRANSLATE_NOOP, TechDraw::pointPair::second(), Path.Post.scripts.grbl_post::type, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
updateDistanceType()
void TDHandlerDimension::updateDistanceType () inline protected
Definition at line 1160 of file CommandCreateDims.cpp.
References Sketcher::Distance, Sketcher::DistanceX, Sketcher::DistanceY, TechDraw::pointPair::first(), TechDrawGui::Rez::guiX(), KDL::max(), KDL::min(), Arch::QT_TRANSLATE_NOOP, TechDraw::pointPair::second(), Path.Post.scripts.grbl_post::type, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
updateExtentDistanceType()
void TDHandlerDimension::updateExtentDistanceType () inline protected
Definition at line 1221 of file CommandCreateDims.cpp.
References Sketcher::DistanceX, Sketcher::DistanceY, TechDraw::pointPair::first(), TechDrawGui::Rez::guiX(), KDL::max(), KDL::min(), Arch::QT_TRANSLATE_NOOP, TechDraw::pointPair::second(), Path.Post.scripts.grbl_post::type, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Member Data Documentation
addedRef
ReferenceEntry TDHandlerDimension::addedRef protected
Definition at line 594 of file CommandCreateDims.cpp.
availableDimension
AvailableDimension TDHandlerDimension::availableDimension protected
Definition at line 582 of file CommandCreateDims.cpp.
blockRemoveSel
bool TDHandlerDimension::blockRemoveSel protected
Definition at line 603 of file CommandCreateDims.cpp.
dims
std::vector<DrawViewDimension*> TDHandlerDimension::dims protected
Definition at line 601 of file CommandCreateDims.cpp.
emptyVector
ReferenceVector TDHandlerDimension::emptyVector protected
Definition at line 592 of file CommandCreateDims.cpp.
initialSelection
ReferenceVector TDHandlerDimension::initialSelection protected
Definition at line 597 of file CommandCreateDims.cpp.
mousePos
QPoint TDHandlerDimension::mousePos protected
Definition at line 584 of file CommandCreateDims.cpp.
partFeat
TechDraw::DrawViewPart* TDHandlerDimension::partFeat protected
Definition at line 599 of file CommandCreateDims.cpp.
removedRef
ReferenceEntry TDHandlerDimension::removedRef protected
Definition at line 595 of file CommandCreateDims.cpp.
selCircleArc
ReferenceVector TDHandlerDimension::selCircleArc protected
Definition at line 588 of file CommandCreateDims.cpp.
selEllipseArc
ReferenceVector TDHandlerDimension::selEllipseArc protected
Definition at line 589 of file CommandCreateDims.cpp.
selFaces
ReferenceVector TDHandlerDimension::selFaces protected
Definition at line 591 of file CommandCreateDims.cpp.
selLine
ReferenceVector TDHandlerDimension::selLine protected
Definition at line 587 of file CommandCreateDims.cpp.
selPoints
ReferenceVector TDHandlerDimension::selPoints protected
Definition at line 586 of file CommandCreateDims.cpp.
selSplineAndCo
ReferenceVector TDHandlerDimension::selSplineAndCo protected
Definition at line 590 of file CommandCreateDims.cpp.
specialDimension
SpecialDimension TDHandlerDimension::specialDimension protected
Definition at line 581 of file CommandCreateDims.cpp.
The documentation for this class was generated from the following file:
CommandCreateDims.cpp