FreeCAD: TechDrawGui::QGMText Class Reference
TechDrawGui::QGMText Class Reference
#include <QGMText.h>
Public Types
enum { Type = QGraphicsItem::UserType + 300 }
Public Types inherited from TechDrawGui::QGCustomText
enum { Type = QGraphicsItem::UserType + 130 }
Signals
void dragging ()
void hover (bool state)
void selected (bool state)
void dragFinished ()
Public Member Functions
QGMText (void)
~QGMText () override=default
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual void showBox (bool b)
virtual bool showBox ()
void setPrettyNormal () override
void setPrettyPre () override
void setPrettySel () override
Public Member Functions inherited from TechDrawGui::QGCustomText
QGCustomText (QGraphicsItem *parent=nullptr)
~QGCustomText () override
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QRectF tightBoundingRect () const
QRectF alignmentRect () const
a boundingRect for text alignment, that does not adversely affect rendering.
QPointF tightBoundingAdjust () const
void setHighlighted (bool state)
virtual void centerAt (QPointF centerPos)
virtual void centerAt (double cX, double cY)
virtual void justifyLeftAt (QPointF centerPos, bool vCenter=true)
virtual void justifyLeftAt (double cX, double cY, bool vCenter=true)
virtual void justifyRightAt (QPointF centerPos, bool vCenter=true)
virtual void justifyRightAt (double cX, double cY, bool vCenter=true)
virtual double getHeight ()
virtual double getWidth ()
virtual QColor getNormalColor ()
virtual QColor getPreColor ()
virtual QColor getSelectColor ()
virtual void setColor (QColor c)
virtual void setTightBounding (bool tight)
void makeMark (double x, double y)
void makeMark (Base::Vector3d v)
Protected Member Functions
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
Protected Member Functions inherited from TechDrawGui::QGCustomText
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
Base::Reference< ParameterGrp > getParmGroup ()
Additional Inherited Members
Protected Attributes inherited from TechDrawGui::QGCustomText
bool isHighlighted
bool tightBounding
QColor m_colCurrent
QColor m_colNormal
Detailed Description
Definition at line 43 of file QGMText.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 51 of file QGMText.h.
Constructor & Destructor Documentation
QGMText()
QGMText::QGMText (void) explicit
Definition at line 35 of file QGMText.cpp.
~QGMText()
TechDrawGui::QGMText::~QGMText () override default
Member Function Documentation
dragFinished
void TechDrawGui::QGMText::dragFinished () signal
Referenced by mouseReleaseEvent().
dragging
void TechDrawGui::QGMText::dragging () signal
Referenced by itemChange().
hover
void TechDrawGui::QGMText::hover (bool state) signal
Referenced by hoverEnterEvent(), and hoverLeaveEvent().
hoverEnterEvent()
void QGMText::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override protected
Definition at line 65 of file QGMText.cpp.
References hover(), and TechDrawGui::QGCustomText::hoverEnterEvent().
hoverLeaveEvent()
void QGMText::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override protected
Definition at line 71 of file QGMText.cpp.
References hover(), and TechDrawGui::QGCustomText::hoverLeaveEvent().
itemChange()
QVariant QGMText::itemChange (GraphicsItemChange change, const QVariant & value) override protected
Definition at line 47 of file QGMText.cpp.
References dragging(), and TechDrawGui::QGCustomText::itemChange().
mouseReleaseEvent()
void QGMText::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override
Definition at line 57 of file QGMText.cpp.
References dragFinished().
paint()
void QGMText::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 95 of file QGMText.cpp.
References TechDrawGui::QGCustomText::paint(), and showBox().
selected
void TechDrawGui::QGMText::selected (bool state) signal
setPrettyNormal()
void QGMText::setPrettyNormal () override virtual
Reimplemented from TechDrawGui::QGCustomText.
Definition at line 89 of file QGMText.cpp.
References TechDrawGui::QGCustomText::setPrettyNormal().
setPrettyPre()
void QGMText::setPrettyPre () override virtual
Reimplemented from TechDrawGui::QGCustomText.
Definition at line 83 of file QGMText.cpp.
References TechDrawGui::QGCustomText::setPrettyPre().
setPrettySel()
void QGMText::setPrettySel () override virtual
Reimplemented from TechDrawGui::QGCustomText.
Definition at line 77 of file QGMText.cpp.
References TechDrawGui::QGCustomText::setPrettySel().
showBox() [1/2]
virtual bool TechDrawGui::QGMText::showBox () inline virtual
Definition at line 59 of file QGMText.h.
Referenced by paint().
showBox() [2/2]
virtual void TechDrawGui::QGMText::showBox (bool b) inline virtual
Definition at line 58 of file QGMText.h.
References SCL.SimpleDataTypes::b.
type()
int TechDrawGui::QGMText::type () const inline override
Definition at line 52 of file QGMText.h.
The documentation for this class was generated from the following files:
QGMText.h
QGMText.cpp