FreeCAD: Path.Post.scripts.example_pre Namespace Reference
Path.Post.scripts.example_pre Namespace Reference
Functions
def open (filename)
def insert (filename, docname)
def parse (inputstring)
Variables
LEVEL
Function Documentation
insert()
def Path.Post.scripts.example_pre.insert (filename, docname)
Definition at line 56 of file example_pre.py.
References Path.Post.scripts.example_pre.parse(), and Path.Log.track().
Referenced by Path.Post.scripts.example_pre.open().
open()
def Path.Post.scripts.example_pre.open (filename)
Definition at line 48 of file example_pre.py.
References Path.Post.scripts.example_pre.insert(), and Path.Log.track().
parse()
def Path.Post.scripts.example_pre.parse (inputstring)
Definition at line 69 of file example_pre.py.
References Path.Post.scripts.refactored_centroid_post.str, and Path.Log.track().
Referenced by Path.Post.scripts.example_pre.insert().
Variable Documentation
LEVEL
Path.Post.scripts.example_pre.LEVEL
Definition at line 41 of file example_pre.py.