FreeCAD: Part::ExtrusionHelper Class Reference
Part::ExtrusionHelper Class Reference
#include <ExtrusionHelper.h>
Public Member Functions
ExtrusionHelper ()
Static Public Member Functions
static void makeDraft (const TopoDS_Shape &shape, const gp_Dir &direction, const double LengthFwd, const double LengthRev, const double AngleFwd, const double AngleRev, bool isSolid, std::list< TopoDS_Shape > &drafts, bool isPartDesign)
makeDraft: creates a drafted extrusion shape out of the input 2D shape
static void checkInnerWires (std::vector< bool > &isInnerWire, const gp_Dir direction, std::vector< bool > &checklist, bool forInner, std::vector< TopoDS_Shape > prisms)
checkInnerWires: Checks what wires are inner ones by taking a set of prisms created with every wire. The prisms are cut from each other. If the moment of inertia thereby changes, the prism wire is an inner wire. Inner wires can have nested inner wires that are then in fact outer wires. Therefore checkInnerWires is called recursively until all wires are checked.
static void createTaperedPrismOffset (TopoDS_Wire sourceWire, const gp_Vec &translation, double offset, bool isSecond, TopoDS_Wire &result)
createTaperedPrismOffset: creates an offset wire from the sourceWire in the specified translation. isSecond determines if the wire is used for the 2nd extrusion direction.
static void makeElementDraft (const ExtrusionParameters &params, const TopoShape &, std::vector< TopoShape > &, App::StringHasherRef hasher)
Detailed Description
Definition at line 76 of file ExtrusionHelper.h.
Constructor & Destructor Documentation
ExtrusionHelper()
ExtrusionHelper::ExtrusionHelper () default
Member Function Documentation
checkInnerWires()
void ExtrusionHelper::checkInnerWires (std::vector< bool > & isInnerWire, const gp_Dir direction, std::vector< bool > & checklist, bool forInner, std::vector< TopoDS_Shape > prisms) static
checkInnerWires: Checks what wires are inner ones by taking a set of prisms created with every wire. The prisms are cut from each other. If the moment of inertia thereby changes, the prism wire is an inner wire. Inner wires can have nested inner wires that are then in fact outer wires. Therefore checkInnerWires is called recursively until all wires are checked.
Definition at line 312 of file ExtrusionHelper.cpp.
References Base::Console(), SplineSurface::i, and Base::ConsoleSingleton::Warning().
Referenced by makeDraft().
createTaperedPrismOffset()
void ExtrusionHelper::createTaperedPrismOffset (TopoDS_Wire sourceWire, const gp_Vec & translation, double offset, bool isSecond, TopoDS_Wire & result) static
createTaperedPrismOffset: creates an offset wire from the sourceWire in the specified translation. isSecond determines if the wire is used for the 2nd extrusion direction.
Definition at line 413 of file ExtrusionHelper.cpp.
References Part::BRepOffsetAPI_MakeOffsetFix::AddWire(), Base::Console(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), Part::BRepOffsetAPI_MakeOffsetFix::Init(), Part::BRepOffsetAPI_MakeOffsetFix::IsDone(), Part::BRepOffsetAPI_MakeOffsetFix::Perform(), result, Part::BRepOffsetAPI_MakeOffsetFix::Shape(), and Path.Post.scripts.grbl_post::type.
Referenced by makeDraft(), and makeElementDraft().
makeDraft()
void ExtrusionHelper::makeDraft (const TopoDS_Shape & shape, const gp_Dir & direction, const double LengthFwd, const double LengthRev, const double AngleFwd, const double AngleRev, bool isSolid, std::list< TopoDS_Shape > & drafts, bool isPartDesign) static
makeDraft: creates a drafted extrusion shape out of the input 2D shape
Definition at line 57 of file ExtrusionHelper.cpp.
References checkInnerWires(), createTaperedPrismOffset(), SCL.SimpleDataTypes::e, SplineSurface::i, Path.Base.Util::isSolid(), Path.Op.Util::offsetWire(), toolbit-attributes::s, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf::shell, and KDL::tan().
Referenced by PartDesign::FeatureExtrude::generateTaperedPrism().
makeElementDraft()
void ExtrusionHelper::makeElementDraft (const ExtrusionParameters & params, const TopoShape & _shape, std::vector< TopoShape > & drafts, App::StringHasherRef hasher) static
Same as makeDraft() with support of element mapping
Definition at line 485 of file ExtrusionHelper.cpp.
References createTaperedPrismOffset(), Part::TopoShape::getShape(), Part::TopoShape::getSubTopoShapes(), Part::TopoShape::hasSubShape(), Part::TopoShape::isNull(), Part::TopoShape::makeElementCompound(), Part::TopoShape::makeElementFace(), Part::TopoShape::mapSubElement(), Path.Op.Util::offsetWire(), nativeifc.ifc_observer::params, RobotExample::pos, Part::TopoShape::ReorientForward, Part::TopoShape::returnShape, toolbit-attributes::s, Part::TopoShape::setShape(), Part::TopoShape::shapeType(), Part::TopoShape::splitWires(), Data::ComplexGeoData::Tag, KDL::tan(), and Mesh2Shape::wires.
Referenced by PartDesign::FeatureExtrude::buildExtrusion(), and Part::Extrusion::extrudeShape().
The documentation for this class was generated from the following files:
ExtrusionHelper.h
ExtrusionHelper.cpp