FreeCAD: MeshGui::SoFCMeshGridNode Class Reference
MeshGui::SoFCMeshGridNode Class Reference
#include <SoFCMeshObject.h>
Public Member Functions
SoFCMeshGridNode ()
void GLRender (SoGLRenderAction *action) override
Static Public Member Functions
static void initClass ()
Public Attributes
SoSFVec3f minGrid
SoSFVec3f maxGrid
SoSFVec3s lenGrid
Protected Member Functions
~SoFCMeshGridNode () override
Detailed Description
Definition at line 113 of file SoFCMeshObject.h.
Constructor & Destructor Documentation
SoFCMeshGridNode()
SoFCMeshGridNode::SoFCMeshGridNode ()
Constructor.
Definition at line 422 of file SoFCMeshObject.cpp.
~SoFCMeshGridNode()
SoFCMeshGridNode::~SoFCMeshGridNode () override protected default
Destructor.
Member Function Documentation
GLRender()
void SoFCMeshGridNode::GLRender (SoGLRenderAction * action) override
Definition at line 442 of file SoFCMeshObject.cpp.
References SplineSurface::i, lenGrid, KDL::max(), maxGrid, KDL::min(), minGrid, buildPsets::p, buildPsets::u, TestSpreadsheet::v, and src.Mod.PartDesign.fcgear.svggear::w.
initClass()
void SoFCMeshGridNode::initClass () static
Definition at line 437 of file SoFCMeshObject.cpp.
Referenced by PyMOD_INIT_FUNC().
Member Data Documentation
lenGrid
SoSFVec3s MeshGui::SoFCMeshGridNode::lenGrid
Definition at line 126 of file SoFCMeshObject.h.
Referenced by GLRender().
maxGrid
SoSFVec3f MeshGui::SoFCMeshGridNode::maxGrid
Definition at line 125 of file SoFCMeshObject.h.
Referenced by GLRender().
minGrid
SoSFVec3f MeshGui::SoFCMeshGridNode::minGrid
Definition at line 124 of file SoFCMeshObject.h.
Referenced by GLRender().
The documentation for this class was generated from the following files:
SoFCMeshObject.h
SoFCMeshObject.cpp