FreeCAD: Tree.cpp File Reference
Tree.cpp File Reference
#include "PreCompiled.h"
#include <QAction>
#include <QActionGroup>
#include <QApplication>
#include <QContextMenuEvent>
#include <QCursor>
#include <QHeaderView>
#include <QMenu>
#include <QMessageBox>
#include <QPainter>
#include <QPixmap>
#include <QThread>
#include <QTimer>
#include <QToolTip>
#include <QVBoxLayout>
#include <Base/Console.h>
#include <Base/Reader.h>
#include <Base/Sequencer.h>
#include <Base/Tools.h>
#include <Base/Writer.h>
#include <App/Color.h>
#include <App/Document.h>
#include <App/DocumentObjectGroup.h>
#include <App/AutoTransaction.h>
#include <App/GeoFeatureGroupExtension.h>
#include <App/Link.h>
#include "Tree.h"
#include "BitmapFactory.h"
#include "Command.h"
#include "Document.h"
#include "ExpressionCompleter.h"
#include "Macro.h"
#include "MainWindow.h"
#include "MenuManager.h"
#include "TreeParams.h"
#include "View3DInventor.h"
#include "ViewProviderDocumentObject.h"
#include "Widgets.h"
#include "Workbench.h"
#include "moc_Tree.cpp"
Classes
struct Stats
struct TimingInfo
class Gui::DocumentObjectData
class Gui::DocumentItem::ExpandInfo
class Gui::TreeWidgetItemDelegate
class DynamicQLineEdit
struct ItemInfo
struct ItemInfo2
struct UpdateDisabler
Namespaces
Gui
Macros
#define _TREE_PRINT(_level, _func, _msg) _FC_PRINT(FC_LOG_INSTANCE,_level,_func, '['<<getTreeName()<<"] " << _msg)
#define TREE_MSG(_msg) _TREE_PRINT(FC_LOGLEVEL_MSG,Notify<Base::LogStyle::Message>,_msg)
#define TREE_WARN(_msg) _TREE_PRINT(FC_LOGLEVEL_WARN,Notify<Base::LogStyle::Warning>,_msg)
#define TREE_ERR(_msg) _TREE_PRINT(FC_LOGLEVEL_ERR,Notify<Base::LogStyle::Error>,_msg)
#define TREE_LOG(_msg) _TREE_PRINT(FC_LOGLEVEL_LOG,Notify<Base::LogStyle::Log>,_msg)
#define TREE_TRACE(_msg) _TREE_PRINT(FC_LOGLEVEL_TRACE,Notify<Base::LogStyle::Log>,_msg)
#define DEFINE_STATS
#define DEFINE_STAT(_name)
#define DEFINE_STAT(_name)
#define DEFINE_STAT(_name) FC_DURATION_MSG(_name, #_name " count: " << _name##_count);
#define DEFINE_STAT(_name)
#define _Timing(...) do{}while(0)
#define Timing(...) do{}while(0)
#define TimingInit() do{}while(0)
#define TimingPrint() do{}while(0)
#define _TimingStop(...) do{}while(0);
#define TimingStop(...) do{}while(0);
#define FOREACH_ITEM(_item, _obj)
#define FOREACH_ITEM_ALL(_item)
#define END_FOREACH_ITEM }}
Typedefs
using DocumentObjectItems = std::set< DocumentObjectItem * >
Enumerations
enum GroupType { NotGroup = 0, LinkGroup = 1, PartGroup = 2, SuperGroup = 3 }
Functions
static bool isVisibilityIconEnabled ()
static bool isOnlyNameColumnDisplayed ()
static bool isSelectionCheckBoxesEnabled ()
static int & treeIconSize ()
bool Gui::isTreeViewDragging ()
static unsigned int countExpandedItem (const QTreeWidgetItem *item)
static void saveExpandedItem (Base::Writer &writer, const QTreeWidgetItem *item)
Variables
static QBrush _TreeItemBackground
static TreeWidget * _LastSelectedTreeWidget
static bool _DraggingActive
static bool _DragEventFilter
static bool _DisableCheckTopParent
static int countItems
Macro Definition Documentation
_Timing
#define _Timing (...) do{}while(0)
Definition at line 200 of file Tree.cpp.
_TimingStop
#define _TimingStop (...) do{}while(0);
Definition at line 204 of file Tree.cpp.
_TREE_PRINT
#define _TREE_PRINT (_level, _func, _msg) _FC_PRINT(FC_LOG_INSTANCE,_level,_func, '['<<getTreeName()<<"] " << _msg)
Definition at line 73 of file Tree.cpp.
DEFINE_STAT [1/4]
#define DEFINE_STAT (_name)
Value:
    FC_DURATION_DECLARE(_name);\
    int _name##_count;
Definition at line 156 of file Tree.cpp.
DEFINE_STAT [2/4]
#define DEFINE_STAT (_name)
Value:
        FC_DURATION_INIT(_name);\
        _name##_count = 0;
Definition at line 156 of file Tree.cpp.
DEFINE_STAT [3/4]
#define DEFINE_STAT (_name) FC_DURATION_MSG(_name, #_name " count: " << _name##_count);
Definition at line 156 of file Tree.cpp.
DEFINE_STAT [4/4]
#define DEFINE_STAT (_name)
Value:
    void time_##_name(FC_TIME_POINT &t) {\
        ++_name##_count;\
        FC_DURATION_PLUS(_name,t);\
    }
Definition at line 156 of file Tree.cpp.
DEFINE_STATS
#define DEFINE_STATS
Value:
    DEFINE_STAT(testStatus1) \
    DEFINE_STAT(testStatus2) \
    DEFINE_STAT(testStatus3) \
    DEFINE_STAT(getIcon) \
    DEFINE_STAT(setIcon) \
Definition at line 127 of file Tree.cpp.
END_FOREACH_ITEM
#define END_FOREACH_ITEM }}
Definition at line 3816 of file Tree.cpp.
FOREACH_ITEM
#define FOREACH_ITEM (_item, _obj)
Value:
    auto _it = ObjectMap.end();\
    if(_obj.getObject() && _obj.getObject()->isAttachedToDocument())\
        _it = ObjectMap.find(_obj.getObject());\
    if(_it != ObjectMap.end()) {\
        for(auto _item : _it->second->items) {
Definition at line 3805 of file Tree.cpp.
FOREACH_ITEM_ALL
#define FOREACH_ITEM_ALL (_item)
Value:
    for(const auto& _v : ObjectMap) {\
        for(auto _item : _v.second->items) {
Definition at line 3812 of file Tree.cpp.
Timing
#define Timing (...) do{}while(0)
Definition at line 201 of file Tree.cpp.
TimingInit
#define TimingInit () do{}while(0)
Definition at line 202 of file Tree.cpp.
TimingPrint
#define TimingPrint () do{}while(0)
Definition at line 203 of file Tree.cpp.
TimingStop
#define TimingStop (...) do{}while(0);
Definition at line 205 of file Tree.cpp.
TREE_ERR
#define TREE_ERR (_msg) _TREE_PRINT(FC_LOGLEVEL_ERR,Notify<Base::LogStyle::Error>,_msg)
Definition at line 77 of file Tree.cpp.
TREE_LOG
#define TREE_LOG (_msg) _TREE_PRINT(FC_LOGLEVEL_LOG,Notify<Base::LogStyle::Log>,_msg)
Definition at line 78 of file Tree.cpp.
TREE_MSG
#define TREE_MSG (_msg) _TREE_PRINT(FC_LOGLEVEL_MSG,Notify<Base::LogStyle::Message>,_msg)
Definition at line 75 of file Tree.cpp.
TREE_TRACE
#define TREE_TRACE (_msg) _TREE_PRINT(FC_LOGLEVEL_TRACE,Notify<Base::LogStyle::Log>,_msg)
Definition at line 79 of file Tree.cpp.
TREE_WARN
#define TREE_WARN (_msg) _TREE_PRINT(FC_LOGLEVEL_WARN,Notify<Base::LogStyle::Warning>,_msg)
Definition at line 76 of file Tree.cpp.
Typedef Documentation
DocumentObjectItems
using DocumentObjectItems = std::set<DocumentObjectItem*>
Definition at line 210 of file Tree.cpp.
Enumeration Type Documentation
GroupType
enum GroupType
Enumerator
NotGroup
LinkGroup
PartGroup
SuperGroup
Definition at line 5623 of file Tree.cpp.
Function Documentation
countExpandedItem()
static unsigned int countExpandedItem (const QTreeWidgetItem * item) static
Definition at line 4474 of file Tree.cpp.
References src.Mod.AddonManager.NetworkManager::count, App::DocumentObject::getNameInDocument(), SplineSurface::i, App::DocumentObject::isAttachedToDocument(), and Gui::TreeWidget::ObjectType.
Referenced by Gui::DocumentItem::getMemSize().
isOnlyNameColumnDisplayed()
static bool isOnlyNameColumnDisplayed () static
Definition at line 100 of file Tree.cpp.
References Gui::TreeParams::getHideColumn(), and Gui::TreeParams::getHideInternalNames().
Referenced by Gui::TreeWidgetItemDelegate::initStyleOption(), and Gui::TreeWidgetItemDelegate::paint().
isSelectionCheckBoxesEnabled()
static bool isSelectionCheckBoxesEnabled () static
Definition at line 105 of file Tree.cpp.
References Gui::TreeParams::getCheckBoxesSelection().
Referenced by Gui::TreeWidget::mousePressEvent(), and Gui::TreeWidget::synchronizeSelectionCheckBoxes().
isVisibilityIconEnabled()
static bool isVisibilityIconEnabled () static
Definition at line 96 of file Tree.cpp.
References Gui::TreeParams::getVisibilityIcon().
Referenced by Gui::TreeWidget::mousePressEvent(), and Gui::DocumentObjectItem::testStatus().
saveExpandedItem()
static void saveExpandedItem (Base::Writer & writer, const QTreeWidgetItem * item) static
Definition at line 4491 of file Tree.cpp.
References src.Mod.AddonManager.NetworkManager::count, Base::Writer::decInd(), App::DocumentObject::getNameInDocument(), SplineSurface::i, Base::Writer::incInd(), Base::Writer::ind(), App::DocumentObject::isAttachedToDocument(), Gui::TreeWidget::ObjectType, and Base::Writer::Stream().
Referenced by Gui::DocumentItem::Save().
treeIconSize()
static int& treeIconSize () static
Definition at line 1415 of file Tree.cpp.
References Gui::TreeParams::getIconSize().
Referenced by Gui::TreeWidget::iconHeight(), Gui::TreeWidget::iconSize(), and Gui::TreeWidget::setIconHeight().
Variable Documentation
_DisableCheckTopParent
bool _DisableCheckTopParent static
Definition at line 801 of file Tree.cpp.
Referenced by Gui::TreeWidget::checkTopParent().
_DragEventFilter
bool _DragEventFilter static
Definition at line 94 of file Tree.cpp.
Referenced by Gui::TreeWidget::dragMoveEvent(), and Gui::TreeWidget::startDrag().
_DraggingActive
bool _DraggingActive static
Definition at line 93 of file Tree.cpp.
Referenced by Gui::isTreeViewDragging(), and Gui::TreeWidget::startDrag().
_LastSelectedTreeWidget
TreeWidget* _LastSelectedTreeWidget static
Definition at line 90 of file Tree.cpp.
Referenced by Gui::TreeWidget::instance(), Gui::TreeWidget::TreeWidget(), and Gui::TreeWidget::~TreeWidget().
_TreeItemBackground
QBrush _TreeItemBackground static
Definition at line 88 of file Tree.cpp.
Referenced by Gui::TreeWidgetItemDelegate::paint().
countItems
int countItems static
Definition at line 5186 of file Tree.cpp.
Referenced by Gui::DocumentObjectItem::DocumentObjectItem(), SketcherGui::TaskSketcherElements::onSelectionChanged(), SketcherGui::TaskSketcherConstraints::onSelectionChanged(), and Gui::DocumentObjectItem::~DocumentObjectItem().