FreeCAD: CommandDecorate.cpp File Reference
CommandDecorate.cpp File Reference
#include "PreCompiled.h"
#include <QMessageBox>
#include <sstream>
#include <App/Document.h>
#include <App/DocumentObject.h>
#include <Base/Tools.h>
#include <Gui/Action.h>
#include <Gui/Application.h>
#include <Gui/Command.h>
#include <Gui/Control.h>
#include <Gui/Document.h>
#include <Gui/FileDialog.h>
#include <Gui/MainWindow.h>
#include <Gui/Selection.h>
#include <Gui/SelectionObject.h>
#include <Gui/ViewProvider.h>
#include <Mod/TechDraw/App/DrawHatch.h>
#include <Mod/TechDraw/App/DrawGeomHatch.h>
#include <Mod/TechDraw/App/DrawPage.h>
#include <Mod/TechDraw/App/DrawUtil.h>
#include <Mod/TechDraw/App/DrawView.h>
#include <Mod/TechDraw/App/DrawViewPart.h>
#include <Mod/TechDraw/App/Preferences.h>
#include "DrawGuiUtil.h"
#include "TaskGeomHatch.h"
#include "TaskHatch.h"
#include "ViewProviderGeomHatch.h"
#include "ViewProviderPage.h"
#include "MDIViewPage.h"
#include "CommandHelpers.h"
Typedefs
using DU = DrawUtil
Functions
bool _checkSelectionHatch (Gui::Command *cmd)
void CreateTechDrawCommandsDecorate ()
Typedef Documentation
DU
using DU = DrawUtil
Definition at line 61 of file CommandDecorate.cpp.
Function Documentation
_checkSelectionHatch()
bool _checkSelectionHatch (Gui::Command * cmd)
Definition at line 384 of file CommandDecorate.cpp.
References Base::Persistence::getClassTypeId(), Gui::Command::getDocument(), TechDraw::DrawUtil::getGeomTypeFromName(), Gui::getMainWindow(), App::Document::getObjectsOfType(), Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), Path.Dressup.Utils::selection(), and Path.Log::warning().
CreateTechDrawCommandsDecorate()
void CreateTechDrawCommandsDecorate ()
Definition at line 368 of file CommandDecorate.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().