FreeCAD: SketcherGui::TaskDlgEditSketch Class Reference
SketcherGui::TaskDlgEditSketch Class Reference
simulation dialog for the TaskView
#include <TaskDlgEditSketch.h>
Public Member Functions
TaskDlgEditSketch (ViewProviderSketch *sketchView)
~TaskDlgEditSketch () override
ViewProviderSketch * getSketchView () const
void open () override
is called the TaskView when the dialog is opened
void clicked (int) override
is called by the framework if an button is clicked which has no accept or reject role
bool accept () override
is called by the framework if the dialog is accepted (Ok)
bool reject () override
is called by the framework if the dialog is rejected (Cancel)
bool isAllowedAlterDocument () const override
void autoClosedOnClosedView () override
QDialogButtonBox::StandardButtons getStandardButtons () const override
returns for Close and Help button
template<typename F >
boost::signals2::connection registerToolWidgetChanged (F &&f)
Function used to register a slot to be triggered when the tool widget is changed.
Public Member Functions inherited from Gui::TaskView::TaskDialog
TaskDialog ()
~TaskDialog () override
QWidget * addTaskBox (QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBox (const QPixmap &icon, QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBoxWithoutHeader (QWidget *widget)
void setButtonPosition (ButtonPosition p)
ButtonPosition buttonPosition () const
const std::vector< QWidget * > & getDialogContent () const
bool canClose () const
virtual void modifyStandardButtons (QDialogButtonBox *)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
bool isEscapeButtonEnabled () const
void setAutoCloseOnTransactionChange (bool on)
bool isAutoCloseOnTransactionChange () const
void setAutoCloseOnDeletedDocument (bool on)
bool isAutoCloseOnDeletedDocument () const
const std::string & getDocumentName () const
void setDocumentName (const std::string &doc)
void setAutoCloseOnClosedView (bool on)
bool isAutoCloseOnClosedView () const
void associateToObject3dView (App::DocumentObject *obj)
const Gui::MDIView * getAssociatedView () const
void setAssociatedView (const Gui::MDIView *view)
virtual bool isAllowedAlterView () const
virtual bool isAllowedAlterSelection () const
virtual bool needsFullSpace () const
virtual void closed ()
is called by the framework when the dialog is closed
virtual void autoClosedOnTransactionChange ()
virtual void autoClosedOnDeletedDocument ()
virtual void helpRequested ()
is called by the framework if the user press the help button
void emitDestructionSignal ()
Protected Member Functions
void slotUndoDocument (const App::Document &)
void slotRedoDocument (const App::Document &)
Protected Attributes
ViewProviderSketch * sketchView
TaskSketcherConstraints * Constraints
TaskSketcherElements * Elements
TaskSketcherMessages * Messages
TaskSketcherSolverAdvanced * SolverAdvanced
TaskSketcherTool * ToolSettings
Protected Attributes inherited from Gui::TaskView::TaskDialog
QPointer< QDialogButtonBox > buttonBox
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Detailed Description
simulation dialog for the TaskView
Definition at line 45 of file TaskDlgEditSketch.h.
Constructor & Destructor Documentation
TaskDlgEditSketch()
TaskDlgEditSketch::TaskDlgEditSketch (ViewProviderSketch * sketchView) explicit
Definition at line 40 of file TaskDlgEditSketch.cpp.
References Gui::TaskView::TaskDialog::associateToObject3dView(), draftgeoutils.faces::bind(), Constraints, Gui::TaskView::TaskDialog::Content, Elements, App::GetApplication(), ParameterGrp::GetBool(), Gui::ViewProviderDocumentObject::getObject(), App::Application::GetParameterGroupByPath(), Gui::TaskView::TaskBox::hideGroupBox(), Messages, SketcherGui::ViewProviderSketch::registerToolChanged(), Gui::TaskView::TaskDialog::setEscapeButtonEnabled(), sketchView, SolverAdvanced, and ToolSettings.
~TaskDlgEditSketch()
TaskDlgEditSketch::~TaskDlgEditSketch () override
Definition at line 86 of file TaskDlgEditSketch.cpp.
References Gui::TaskView::TaskDialog::Content, DraftVecUtils::find(), and SolverAdvanced.
Member Function Documentation
accept()
bool TaskDlgEditSketch::accept () override virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 120 of file TaskDlgEditSketch.cpp.
autoClosedOnClosedView()
void TaskDlgEditSketch::autoClosedOnClosedView () override virtual
is called by the framework when the dialog is automatically closed due to closing of associated view
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 150 of file TaskDlgEditSketch.cpp.
References reject().
clicked()
void TaskDlgEditSketch::clicked (int) override virtual
is called by the framework if an button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 117 of file TaskDlgEditSketch.cpp.
getSketchView()
ViewProviderSketch* SketcherGui::TaskDlgEditSketch::getSketchView () const inline
Definition at line 52 of file TaskDlgEditSketch.h.
Referenced by SketcherGui::ViewProviderSketch::setEdit().
getStandardButtons()
QDialogButtonBox::StandardButtons SketcherGui::TaskDlgEditSketch::getStandardButtons () const inline override virtual
returns for Close and Help button
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 73 of file TaskDlgEditSketch.h.
isAllowedAlterDocument()
bool SketcherGui::TaskDlgEditSketch::isAllowedAlterDocument () const inline override virtual
Indicates whether this task dialog allows other commands to modify the document while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 66 of file TaskDlgEditSketch.h.
open()
void TaskDlgEditSketch::open () override virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 114 of file TaskDlgEditSketch.cpp.
registerToolWidgetChanged()
template<typename F > boost::signals2::connection SketcherGui::TaskDlgEditSketch::registerToolWidgetChanged (F && f) inline
Function used to register a slot to be triggered when the tool widget is changed.
Definition at line 80 of file TaskDlgEditSketch.h.
References SCL.SimpleDataTypes::f.
Referenced by SketcherGui::ViewProviderSketch::setEdit().
reject()
bool TaskDlgEditSketch::reject () override virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 125 of file TaskDlgEditSketch.cpp.
References Constraints, Gui::Command::Doc, doCommand, Elements, App::GetApplication(), Gui::TaskView::TaskDialog::getDocumentName(), App::Application::GetParameterGroupByPath(), SketcherGui::ViewProviderSketch::getSketchMode(), Gui::Command::Gui, Gui::TaskView::TaskBox::isGroupVisible(), Messages, SketcherGui::ViewProviderSketch::purgeHandler(), ParameterGrp::SetBool(), sketchView, SolverAdvanced, and SketcherGui::ViewProviderSketch::STATUS_NONE.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and autoClosedOnClosedView().
slotRedoDocument()
void SketcherGui::TaskDlgEditSketch::slotRedoDocument (const App::Document &) protected
slotUndoDocument()
void SketcherGui::TaskDlgEditSketch::slotUndoDocument (const App::Document &) protected
Member Data Documentation
Constraints
TaskSketcherConstraints* SketcherGui::TaskDlgEditSketch::Constraints protected
Definition at line 94 of file TaskDlgEditSketch.h.
Referenced by reject(), and TaskDlgEditSketch().
Elements
TaskSketcherElements* SketcherGui::TaskDlgEditSketch::Elements protected
Definition at line 95 of file TaskDlgEditSketch.h.
Referenced by reject(), and TaskDlgEditSketch().
Messages
TaskSketcherMessages* SketcherGui::TaskDlgEditSketch::Messages protected
Definition at line 96 of file TaskDlgEditSketch.h.
Referenced by reject(), and TaskDlgEditSketch().
sketchView
ViewProviderSketch* SketcherGui::TaskDlgEditSketch::sketchView protected
Definition at line 93 of file TaskDlgEditSketch.h.
Referenced by reject(), and TaskDlgEditSketch().
SolverAdvanced
TaskSketcherSolverAdvanced* SketcherGui::TaskDlgEditSketch::SolverAdvanced protected
Definition at line 97 of file TaskDlgEditSketch.h.
Referenced by reject(), TaskDlgEditSketch(), and ~TaskDlgEditSketch().
ToolSettings
TaskSketcherTool* SketcherGui::TaskDlgEditSketch::ToolSettings protected
Definition at line 98 of file TaskDlgEditSketch.h.
Referenced by TaskDlgEditSketch().
The documentation for this class was generated from the following files:
TaskDlgEditSketch.h
TaskDlgEditSketch.cpp