FreeCAD: Gui::Dialog::DlgOnlineHelpImp Class Reference
Gui::Dialog::DlgOnlineHelpImp Class Reference
#include <DlgOnlineHelpImp.h>
Public Member Functions
DlgOnlineHelpImp (QWidget *parent=nullptr)
~DlgOnlineHelpImp () override
void saveSettings () override
void loadSettings () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Static Public Member Functions
static QString getStartpage ()
Protected Member Functions
void changeEvent (QEvent *e) override
void onLineEditDownloadFileNameSelected (const QString &)
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
This class implements the dialog for downloading the online documentation. Moreover it allows one to specify location of the start page an an external browser. Here you can specify to use a proxy if necessary and some more stuff.
Author
Werner Mayer
Definition at line 79 of file DlgOnlineHelpImp.h.
Constructor & Destructor Documentation
DlgOnlineHelpImp()
DlgOnlineHelpImp::DlgOnlineHelpImp (QWidget * parent = nullptr)
Constructs a DlgOnlineHelpImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
Definition at line 46 of file DlgOnlineHelpImp.cpp.
References getStartpage().
~DlgOnlineHelpImp()
DlgOnlineHelpImp::~DlgOnlineHelpImp () override default
Destroys the object and frees any allocated resources
Member Function Documentation
changeEvent()
void DlgOnlineHelpImp::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 88 of file DlgOnlineHelpImp.cpp.
References SCL.SimpleDataTypes::e.
getStartpage()
QString DlgOnlineHelpImp::getStartpage () static
Returns the start page for the HelpView. If none is defined the default start page "<FreeCADHome>/doc/free-cad.sourceforge.net/wiki/index.php.html" is returned.
Remarks
It is not checked if the returned page really exists.
Definition at line 69 of file DlgOnlineHelpImp.cpp.
References App::Application::getHelpDir().
Referenced by DlgOnlineHelpImp().
loadSettings()
void DlgOnlineHelpImp::loadSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 80 of file DlgOnlineHelpImp.cpp.
onLineEditDownloadFileNameSelected()
void DlgOnlineHelpImp::onLineEditDownloadFileNameSelected (const QString & url) protected
Definition at line 98 of file DlgOnlineHelpImp.cpp.
saveSettings()
void DlgOnlineHelpImp::saveSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 75 of file DlgOnlineHelpImp.cpp.
The documentation for this class was generated from the following files:
DlgOnlineHelpImp.h
DlgOnlineHelpImp.cpp