FreeCAD: geoff_geometry::Matrix Class Reference
geoff_geometry::Matrix Class Reference
#include <geometry.h>
Public Member Functions
Matrix ()
Matrix (double m[16])
~Matrix ()
bool operator== (const Matrix &m) const
bool operator!= (const Matrix &m) const
void Unit ()
void Get (double *p) const
void Put (double *p)
void Translate (double x, double y, double z=0)
void Rotate (double sinang, double cosang, Vector3d *rotAxis)
void Rotate (double angle, Vector3d *rotAxis)
void Rotate (double sinang, double cosang, int Axis)
void Rotate (double angle, int Axis)
void Scale (double scale)
void Scale (double scalex, double scaley, double scalez)
void Multiply (Matrix &m)
void Transform (double p0[3]) const
void Transform (double p0[3], double p1[3]) const
void Transform2d (double p0[2], double p1[2]) const
int IsMirrored ()
int IsUnit ()
void GetTranslate (double &x, double &y, double &z) const
void GetScale (double &sx, double &sy, double &sz) const
bool GetScale (double &sx) const
void GetRotation (double &ax, double &ay, double &az) const
Matrix Inverse ()
Public Attributes
double e [16]
bool m_unit
int m_mirrored
Detailed Description
Definition at line 169 of file geometry.h.
Constructor & Destructor Documentation
Matrix() [1/2]
geoff_geometry::Matrix::Matrix ()
Definition at line 24 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References Unit().
Referenced by geoff_geometry::Kurve::OffsetMethod1(), and geoff_geometry::Kurve::Reduce().
Matrix() [2/2]
geoff_geometry::Matrix::Matrix (double m[16])
Definition at line 28 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References e, IsMirrored(), IsUnit(), and test::m.
~Matrix()
geoff_geometry::Matrix::~Matrix () inline
Definition at line 183 of file geometry.h.
Member Function Documentation
Get()
void geoff_geometry::Matrix::Get (double * p) const
Definition at line 71 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References e, and buildPsets::p.
GetRotation()
void geoff_geometry::Matrix::GetRotation (double & ax, double & ay, double & az) const
Definition at line 287 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References a, KDL::atan2(), SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::c, e, SCL.SimpleDataTypes::f, geoff_geometry::FAILURE(), GetScale(), m_mirrored, m_unit, buildPsets::p, and KDL::sqrt().
GetScale() [1/2]
bool geoff_geometry::Matrix::GetScale (double & sx) const
Definition at line 276 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References GetScale(), and m_unit.
GetScale() [2/2]
void geoff_geometry::Matrix::GetScale (double & sx, double & sy, double & sz) const
Definition at line 264 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References e, m_unit, and KDL::sqrt().
Referenced by geoff_geometry::Kurve::Area(), GetRotation(), GetScale(), geoff_geometry::Kurve::minmax(), geoff_geometry::Kurve::OffsetMethod1(), geoff_geometry::Kurve::Perim(), and geoff_geometry::Circle::Transform().
GetTranslate()
void geoff_geometry::Matrix::GetTranslate (double & x, double & y, double & z) const
Definition at line 257 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References e, MovieTool::x, and MovieTool::y.
Inverse()
Matrix geoff_geometry::Matrix::Inverse ()
Definition at line 349 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References a, e, geoff_geometry::FAILURE(), geoff_geometry::getMessage(), SplineSurface::i, RobotExample::l, and test::m.
Referenced by geoff_geometry::Kurve::Add(), and geoff_geometry::Kurve::NearToVertex().
IsMirrored()
int geoff_geometry::Matrix::IsMirrored ()
Definition at line 224 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References e, m_mirrored, and m_unit.
Referenced by Matrix().
IsUnit()
int geoff_geometry::Matrix::IsUnit ()
Definition at line 238 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References e, SplineSurface::i, m_mirrored, and m_unit.
Referenced by Matrix(), and Multiply().
Multiply()
void geoff_geometry::Matrix::Multiply (Matrix & m)
Definition at line 175 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References e, SplineSurface::i, IsUnit(), RobotExample::l, and test::m.
Referenced by geoff_geometry::Kurve::Add(), BOOST_PYTHON_MODULE(), init_pyarea(), Rotate(), and Scale().
operator!=()
bool geoff_geometry::Matrix::operator!= (const Matrix & m) const inline
Definition at line 187 of file geometry.h.
References test::m.
operator==()
bool geoff_geometry::Matrix::operator== (const Matrix & m) const
Definition at line 40 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References e, geoff_geometry::FEQ(), SplineSurface::i, test::m, m_unit, and geoff_geometry::TIGHT_TOLERANCE.
Put()
void geoff_geometry::Matrix::Put (double * p)
Definition at line 76 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References e, m_mirrored, m_unit, and buildPsets::p.
Rotate() [1/4]
void geoff_geometry::Matrix::Rotate (double angle, int Axis)
Definition at line 121 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References Axis, KDL::cos(), Rotate(), and KDL::sin().
Rotate() [2/4]
void geoff_geometry::Matrix::Rotate (double angle, Vector3d * rotAxis)
Rotation about rotAxis with angle
Definition at line 92 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References KDL::cos(), Rotate(), and KDL::sin().
Rotate() [3/4]
void geoff_geometry::Matrix::Rotate (double sinang, double cosang, int Axis)
Definition at line 126 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References Axis, m_mirrored, m_unit, Multiply(), and src.Mod.PartDesign.fcgear.fcgear::rotate.
Rotate() [4/4]
void geoff_geometry::Matrix::Rotate (double sinang, double cosang, Vector3d * rotAxis)
Rotation about rotAxis with cp & dp
Definition at line 98 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References geoff_geometry::Vector3d::getx(), geoff_geometry::Vector3d::gety(), geoff_geometry::Vector3d::getz(), m_mirrored, m_unit, Multiply(), and src.Mod.PartDesign.fcgear.fcgear::rotate.
Referenced by Rotate(), and geoff_geometry::Span::SplitMatrix().
Scale() [1/2]
void geoff_geometry::Matrix::Scale (double scale)
Definition at line 156 of file Mod/CAM/libarea/kurve/Matrix.cpp.
Scale() [2/2]
void geoff_geometry::Matrix::Scale (double scalex, double scaley, double scalez)
Definition at line 162 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References e, m_mirrored, m_unit, Multiply(), and Unit().
Transform() [1/2]
void geoff_geometry::Matrix::Transform (double p0[3]) const
Definition at line 215 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References m_unit.
Transform() [2/2]
void geoff_geometry::Matrix::Transform (double p0[3], double p1[3]) const
Definition at line 191 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References e, and m_unit.
Transform2d()
void geoff_geometry::Matrix::Transform2d (double p0[2], double p1[2]) const
Definition at line 203 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References e, and m_unit.
Translate()
void geoff_geometry::Matrix::Translate (double x, double y, double z = 0)
Definition at line 83 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References e, m_unit, MovieTool::x, and MovieTool::y.
Referenced by geoff_geometry::Span::SplitMatrix().
Unit()
void geoff_geometry::Matrix::Unit ()
Definition at line 62 of file Mod/CAM/libarea/kurve/Matrix.cpp.
References e, m_mirrored, and m_unit.
Referenced by Matrix(), geoff_geometry::Plane::Mirrored(), Scale(), and geoff_geometry::Span::SplitMatrix().
Member Data Documentation
e
double geoff_geometry::Matrix::e[16]
Definition at line 173 of file geometry.h.
Referenced by Get(), GetRotation(), GetScale(), GetTranslate(), Inverse(), IsMirrored(), IsUnit(), geoff_geometry::Kurve::Kurve(), Matrix(), geoff_geometry::Plane::Mirrored(), Multiply(), geoff_geometry::Kurve::OffsetISOMethod(), geoff_geometry::Kurve::operator=(), operator==(), Put(), Scale(), Transform(), Transform2d(), Translate(), and Unit().
m_mirrored
int geoff_geometry::Matrix::m_mirrored
Definition at line 175 of file geometry.h.
Referenced by GetRotation(), IsMirrored(), IsUnit(), geoff_geometry::Kurve::Kurve(), geoff_geometry::Plane::Mirrored(), geoff_geometry::Kurve::OffsetMethod1(), geoff_geometry::Kurve::operator=(), Put(), Rotate(), Scale(), and Unit().
m_unit
bool geoff_geometry::Matrix::m_unit
Definition at line 174 of file geometry.h.
Referenced by geoff_geometry::Kurve::Add(), geoff_geometry::Kurve::Get(), GetRotation(), GetScale(), IsMirrored(), IsUnit(), geoff_geometry::Kurve::Kurve(), geoff_geometry::Plane::Mirrored(), geoff_geometry::Kurve::NearToVertex(), geoff_geometry::Kurve::operator=(), operator==(), Put(), Rotate(), Scale(), Transform(), Transform2d(), Translate(), and Unit().
The documentation for this class was generated from the following files:
geometry.h
Mod/CAM/libarea/kurve/Matrix.cpp