FreeCAD: TechDraw::LineGenerator Class Reference
TechDraw::LineGenerator Class Reference
#include <LineGenerator.h>
Public Types
enum LINESTANDARD { ANSI, ISO, ASME }
Public Member Functions
LineGenerator ()
~LineGenerator ()=default
QPen getBestPen (size_t lineNumber, Qt::PenStyle qtStyle, double width)
QPen getLinePen (size_t lineNumber, double nominalLineWidth)
void reloadDescriptions ()
std::vector< std::string > getLoadedDescriptions ()
get line descriptions from memory
bool isCurrentProportional ()
Static Public Member Functions
static int fromQtStyle (Qt::PenStyle style)
convert Qt line style to closest ISO line number
static std::vector< std::string > getAvailableLineStandards ()
retrieve a sorted list of available line definition files.
static std::string getLineStandardsBody ()
static std::vector< std::string > getLineDescriptions ()
get line descriptions from file
static bool isProportional (size_t standardIndex)
static std::string getBodyFromString (std::string inString)
Detailed Description
Definition at line 67 of file LineGenerator.h.
Member Enumeration Documentation
LINESTANDARD
enum TechDraw::LineGenerator::LINESTANDARD
Enumerator
ANSI
ISO
ASME
Definition at line 92 of file LineGenerator.h.
Constructor & Destructor Documentation
LineGenerator()
LineGenerator::LineGenerator ()
Definition at line 57 of file LineGenerator.cpp.
References reloadDescriptions().
~LineGenerator()
TechDraw::LineGenerator::~LineGenerator () default
Member Function Documentation
fromQtStyle()
int LineGenerator::fromQtStyle (Qt::PenStyle style) static
convert Qt line style to closest ISO line number
Definition at line 176 of file LineGenerator.cpp.
References ANSI, ASME, and TechDraw::Preferences::lineStandard().
Referenced by getBestPen(), TechDraw::LineFormat::initCurrentLineFormat(), and TechDraw::LineFormat::LineFormat().
getAvailableLineStandards()
std::vector< std::string > LineGenerator::getAvailableLineStandards () static
retrieve a sorted list of available line definition files.
Definition at line 289 of file LineGenerator.cpp.
References Base::FileInfo::getDirectoryContent(), TechDraw::Preferences::lineDefinitionLocation(), and result.
Referenced by getLineStandardsBody(), and isProportional().
getBestPen()
QPen LineGenerator::getBestPen (size_t isoNumber, Qt::PenStyle qtStyle, double width)
figure out an appropriate QPen from an iso line number and a Qt PenStyle we prefer to use the ISO Line Number if available.
Definition at line 74 of file LineGenerator.cpp.
References fromQtStyle(), and getLinePen().
getBodyFromString()
std::string LineGenerator::getBodyFromString (std::string inString) static
returns the standards body name from a standard name in the form body.standard.section.revision
Definition at line 401 of file LineGenerator.cpp.
Referenced by getLineStandardsBody(), and isProportional().
getLineDescriptions()
std::vector< std::string > LineGenerator::getLineDescriptions () static
get line descriptions from file
extract the line description fields from the current definition file
Definition at line 318 of file LineGenerator.cpp.
References Base::Console(), TechDraw::Preferences::currentLineDefFile(), Base::FileInfo::filePath(), importOCA::getline(), Base::ConsoleSingleton::Message(), and TechDraw::DrawUtil::tokenize().
Referenced by reloadDescriptions().
getLinePen()
QPen LineGenerator::getLinePen (size_t lineNumber, double nominalLineWidth)
create a QPen for a given line number and line width. ISO lines are numbered 1-15 and ANSI lines are 1-4(?) The line width is the nominal width in mm.
Definition at line 96 of file LineGenerator.cpp.
References isCurrentProportional(), and TechDraw::Preferences::LineCapStyle().
Referenced by getBestPen(), and TechDrawGui::DrawGuiUtil::iconForLine().
getLineStandardsBody()
std::string LineGenerator::getLineStandardsBody () static
returns a string identifying the standards body which issued the active line standard
Definition at line 353 of file LineGenerator.cpp.
References getAvailableLineStandards(), getBodyFromString(), and TechDraw::Preferences::lineStandard().
getLoadedDescriptions()
std::vector< std::string > LineGenerator::getLoadedDescriptions ()
get line descriptions from memory
get the descriptions of the lines already loaded into this LineGenerator object
Definition at line 311 of file LineGenerator.cpp.
Referenced by TechDrawGui::DrawGuiUtil::loadLineStyleChoices().
isCurrentProportional()
bool LineGenerator::isCurrentProportional ()
returns true if line elements of the current standard are proportional to line width (as in ISO), or false if the elements have a constant length (as in ANSI)
Definition at line 375 of file LineGenerator.cpp.
References isProportional(), and TechDraw::Preferences::lineStandard().
Referenced by getLinePen().
isProportional()
bool LineGenerator::isProportional (size_t standardIndex) static
returns true if line elements of the specified standard are proportional to line width (as in ISO), or false if the elements have a constant length (as in ANSI)
Definition at line 384 of file LineGenerator.cpp.
References getAvailableLineStandards(), and getBodyFromString().
Referenced by isCurrentProportional().
reloadDescriptions()
void LineGenerator::reloadDescriptions ()
if the line standard changes during a lineGenerator's life time then the elements and line descriptions need to be reloaded using the new standard.
Definition at line 65 of file LineGenerator.cpp.
References getLineDescriptions().
Referenced by LineGenerator(), and TechDrawGui::DlgPrefsTechDrawAnnotationImp::onLineStandardChanged().
The documentation for this class was generated from the following files:
LineGenerator.h
LineGenerator.cpp