FreeCAD: Gui::PythonCommand Class Reference
Gui::PythonCommand Class Reference
#include <Command.h>
Public Member Functions
PythonCommand (const char *name, PyObject *pcPyCommand, const char *pActivationString)
~PythonCommand () override
Public Member Functions inherited from Gui::Command
const char * beginCmdHelp ()
returns the begin of a online help page
const char * endCmdHelp ()
returns the end of a online help page
bool hasActiveDocument () const
true when there is a document
bool hasObject (const char *Name)
true when there is a document and a Feature with Name
const char * getAppModuleName () const
returns the name to which the command belongs
void setAppModuleName (const char *)
const char * getName () const
Get the command name.
const char * getGroupName () const
Get the name of the grouping of the command.
void setGroupName (const char *)
QString translatedGroupName () const
virtual void setShortcut (const QString &)
Override shortcut of this command.
virtual QString getShortcut () const
Obtain the current shortcut of this command.
void testActive ()
Get somtile called to check the state of the command.
void setEnabled (bool)
Enables or disables the command.
TriggerSource triggerSource () const
Return the current command trigger source.
void invoke (int index, TriggerSource trigger=TriggerNone)
void addTo (QWidget *)
adds this command to arbitrary widgets
void addToGroup (ActionGroup *, bool checkable)
void addToGroup (ActionGroup *)
void initAction ()
Create the action if not exist.
Gui::Document * getActiveGuiDocument () const
Get pointer to the active gui document.
App::Document * getDocument (const char *Name=nullptr) const
bool isViewOfType (Base::Type t) const
checks if the active view is of a special type or derived
App::DocumentObject * getObject (const char *Name) const
returns the named feature or the active one from the active document or NULL
std::string getUniqueObjectName (const char *BaseName, const App::DocumentObject *obj=nullptr) const
void updateAction (int mode) override
Updates the QAction with respect to the passed mode.
void setupCheckable (int iMsg)
Setup checkable actions based on current TriggerSource.
const std::string strToPython (const char *Str)
translate a string to a python string literal (needed e.g. in file names for windows...)
const std::string strToPython (const std::string &Str)
void adjustCameraPosition ()
Public Member Functions inherited from Gui::CommandBase
Action * getAction () const
void setWhatsThis (const char *)
void setMenuText (const char *)
void setToolTipText (const char *)
void setStatusTip (const char *)
void setPixmap (const char *)
void setAccel (const char *)
Protected Member Functions
Methods reimplemented for Command Framework
void activated (int iMsg) override
Method which gets called when activated.
bool isActive () override
if the command is not always active
const char * getHelpUrl () const override
Get the help URL.
Protected Member Functions inherited from Gui::Command
Command (const char *name)
~Command () override
void applyCommandData (const char *context, Action *)
Applies the menu text, tool and status tip to the passed action object.
const char * keySequenceToAccel (int) const
void printConflictingAccelerators () const
Protected Member Functions inherited from Gui::CommandBase
CommandBase (const char *sMenu, const char *sToolTip=nullptr, const char *sWhat=nullptr, const char *sStatus=nullptr, const char *sPixmap=nullptr, const char *sAccel=nullptr)
virtual ~CommandBase ()
Methods to get the properties of the command
PyObject * _pcPyCommand
a pointer to the Python command object
PyObject * _pcPyResourceDict
the command object resource dictionary
std::string Activation
the activation sequence
boost::signals2::connection connPyCmdInitialized
void languageChange () override
Reassigns QAction stuff after the language has changed.
const char * className () const override
The C++ class name is needed as context for the translation framework.
const char * getWhatsThis () const override
const char * getMenuText () const override
const char * getToolTipText () const override
const char * getStatusTip () const override
const char * getPixmap () const override
const char * getAccel () const override
bool isCheckable () const
bool isChecked () const
const char * getResource (const char *sName) const
Returns the resource values.
Action * createAction () override
Creates the used Action.
void onActionInit () const
Additional Inherited Members
Public Types inherited from Gui::Command
enum TriggerSource { TriggerNone, TriggerAction, TriggerChildAction }
Command trigger source.
enum DoCmd_Type { Doc, App, Gui }
types of application level actions for DoCommand()
Static Public Member Functions inherited from Gui::Command
static Application * getGuiApplication ()
Get pointer to the Application Window.
static Gui::SelectionSingleton & getSelection ()
Get a reference to the selection.
static std::string getObjectCmd (const char *Name, const App::Document *doc=nullptr, const char *prefix=nullptr, const char *postfix=nullptr, bool gui=false)
returns a python command string to retrieve an object from a document
static std::string getObjectCmd (const App::DocumentObject *obj, const char *prefix=nullptr, const char *postfix=nullptr, bool gui=false)
returns a python command string to retrieve the given object
static void openCommand (const char *sName=nullptr)
Open a new Undo transaction on the active document.
static void commitCommand ()
Commit the Undo transaction on the active document.
static void abortCommand ()
Abort the Undo transaction on the active document.
static bool hasPendingCommand ()
Check if an Undo transaction is open on the active document.
static void updateActive ()
Updates the (active) document (propagate changes)
static void updateAll (std::list< Gui::Document * > cList)
Updates the (all or listed) documents (propagate changes)
static bool isActiveObjectValid ()
Checks if the active object of the active document is valid.
static void blockCommand (bool)
Blocks all command objects.
static void printPyCaller ()
Print to Python console the current Python calling source file and line number.
static void printCaller (const char *file, int line)
Print to Python console the current calling source file and line number.
static void _doCommand (const char *file, int line, DoCmd_Type eType, const char *sCmd,...)
Run a App level Action.
static void _runCommand (const char *file, int line, DoCmd_Type eType, const char *sCmd)
Run a App level Action.
static void _runCommand (const char *file, int line, DoCmd_Type eType, const QByteArray &sCmd)
Run a App level Action.
static void addModule (DoCmd_Type eType, const char *sModuleName)
import an external (or own) module only once
static std::string _assureWorkbench (const char *file, int line, const char *sName)
static void _copyVisual (const char *file, int line, const char *to, const char *attr, const char *from)
static void _copyVisual (const char *file, int line, const char *to, const char *attr_to, const char *from, const char *attr_from)
static void _copyVisual (const char *file, int line, const App::DocumentObject *to, const char *attr, const App::DocumentObject *from)
static void _copyVisual (const char *file, int line, const App::DocumentObject *to, const char *attr_to, const App::DocumentObject *from, const char *attr_from)
static std::string getPythonTuple (const std::string &name, const std::vector< std::string > &subnames)
Get Python tuple from object and sub-elements.
Protected Types inherited from Gui::Command
enum CmdType {
AlterDoc = 1, Alter3DView = 2, AlterSelection = 4, ForEdit = 8,
NoTransaction = 16
}
Protected Attributes inherited from Gui::Command
const char * sAppModule
const char * sGroup
const char * sName
const char * sHelpUrl
int eType
bool bCanLog
Indicate if the command shall log to MacroManager.
Protected Attributes inherited from Gui::CommandBase
const char * sMenuText
const char * sToolTipText
const char * sWhatsThis
const char * sStatusTip
const char * sPixmap
const char * sAccel
Action * _pcAction
std::string displayText
Detailed Description
The Python command class This is a special type of command class. It's used to bind a Python command class into the FreeCAD command framework. An object of this class gets a reference to the Python command object and manages all the passing between the C++ and the Python world. This includes everything like setting resources such as bitmaps, activation or bindings to the user interface.
See also
CommandManager
Author
Jrgen Riegel
Definition at line 686 of file Gui/Command.h.
Constructor & Destructor Documentation
PythonCommand()
PythonCommand::PythonCommand (const char * name, PyObject * pcPyCommand, const char * pActivationString)
Definition at line 1266 of file Gui/Command.cpp.
References _pcPyCommand, _pcPyResourceDict, Activation, Gui::Command::Alter3DView, Gui::Command::AlterDoc, Gui::Command::AlterSelection, Gui::Application::commandManager(), connPyCmdInitialized, Gui::Command::eType, Gui::Command::ForEdit, getResource(), Gui::Application::Instance, Base::Interpreter(), Gui::Command::NoTransaction, onActionInit(), Base::InterpreterSingleton::runMethodObject(), Gui::Command::sGroup, and Path.Post.scripts.grbl_post::type.
~PythonCommand()
PythonCommand::~PythonCommand () override
Definition at line 1309 of file Gui/Command.cpp.
References _pcPyCommand.
Member Function Documentation
activated()
void PythonCommand::activated (int iMsg) override protected virtual
Method which gets called when activated.
Implements Gui::Command.
Definition at line 1331 of file Gui/Command.cpp.
References _pcPyCommand, Activation, Base::Console(), Gui::Command::Doc, SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), Base::Interpreter(), isCheckable(), runCommand, Base::InterpreterSingleton::runMethod(), Base::InterpreterSingleton::runMethodVoid(), and Gui::Command::sName.
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::set_status_filter().
className()
const char* Gui::PythonCommand::className () const inline override virtual
The C++ class name is needed as context for the translation framework.
Implements Gui::CommandBase.
Definition at line 708 of file Gui/Command.h.
createAction()
Action * PythonCommand::createAction () override protected virtual
Creates the used Action.
Reimplemented from Gui::Command.
Definition at line 1396 of file Gui/Command.cpp.
References Gui::Command::applyCommandData(), Gui::BitmapFactory(), Base::Console(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), Gui::getMainWindow(), Gui::Command::getName(), getResource(), isCheckable(), isChecked(), Gui::Action::setCheckable(), Gui::Action::setChecked(), and Gui::Action::setIcon().
getAccel()
const char * PythonCommand::getAccel () const override virtual
Reimplemented from Gui::CommandBase.
Definition at line 1451 of file Gui/Command.cpp.
References getResource().
getHelpUrl()
const char * PythonCommand::getHelpUrl () const override protected virtual
Get the help URL.
Reimplemented from Gui::Command.
Definition at line 1385 of file Gui/Command.cpp.
References _pcPyCommand, Base::Interpreter(), and Base::InterpreterSingleton::runMethodObject().
getMenuText()
const char * PythonCommand::getMenuText () const override virtual
Reimplemented from Gui::CommandBase.
Definition at line 1430 of file Gui/Command.cpp.
References getResource().
getPixmap()
const char * PythonCommand::getPixmap () const override virtual
Reimplemented from Gui::CommandBase.
Definition at line 1445 of file Gui/Command.cpp.
References getResource().
getResource()
const char * PythonCommand::getResource (const char * sName) const protected
Returns the resource values.
Definition at line 1315 of file Gui/Command.cpp.
References _pcPyResourceDict, and Gui::Command::sName.
Referenced by createAction(), getAccel(), getMenuText(), getPixmap(), getStatusTip(), getToolTipText(), getWhatsThis(), and PythonCommand().
getStatusTip()
const char * PythonCommand::getStatusTip () const override virtual
Reimplemented from Gui::CommandBase.
Definition at line 1440 of file Gui/Command.cpp.
References getResource().
getToolTipText()
const char * PythonCommand::getToolTipText () const override virtual
Reimplemented from Gui::CommandBase.
Definition at line 1435 of file Gui/Command.cpp.
References getResource().
getWhatsThis()
const char * PythonCommand::getWhatsThis () const override virtual
Reimplemented from Gui::CommandBase.
Definition at line 1422 of file Gui/Command.cpp.
References Gui::Command::getName(), and getResource().
isActive()
bool PythonCommand::isActive () override protected virtual
if the command is not always active
Reimplemented from Gui::Command.
Definition at line 1355 of file Gui/Command.cpp.
References _pcPyCommand, toolbit-attributes::args, and SCL.SimpleDataTypes::e.
isCheckable()
bool PythonCommand::isCheckable () const
Definition at line 1456 of file Gui/Command.cpp.
References _pcPyResourceDict.
Referenced by activated(), createAction(), and Gui::PythonGroupCommand::createAction().
isChecked()
bool PythonCommand::isChecked () const
Definition at line 1463 of file Gui/Command.cpp.
References _pcPyResourceDict, and Base::asBoolean().
Referenced by createAction(), Gui::PythonGroupCommand::createAction(), draftguitools.gui_snaps.Draft_Snap_Lock::GetResources(), draftguitools.gui_snaps.Draft_Snap_Midpoint::GetResources(), draftguitools.gui_snaps.Draft_Snap_Perpendicular::GetResources(), draftguitools.gui_snaps.Draft_Snap_Grid::GetResources(), draftguitools.gui_snaps.Draft_Snap_Intersection::GetResources(), draftguitools.gui_snaps.Draft_Snap_Parallel::GetResources(), draftguitools.gui_snaps.Draft_Snap_Endpoint::GetResources(), draftguitools.gui_snaps.Draft_Snap_Angle::GetResources(), draftguitools.gui_snaps.Draft_Snap_Center::GetResources(), draftguitools.gui_snaps.Draft_Snap_Extension::GetResources(), draftguitools.gui_snaps.Draft_Snap_Near::GetResources(), draftguitools.gui_snaps.Draft_Snap_Ortho::GetResources(), draftguitools.gui_snaps.Draft_Snap_Special::GetResources(), draftguitools.gui_snaps.Draft_Snap_Dimensions::GetResources(), and draftguitools.gui_snaps.Draft_Snap_WorkingPlane::GetResources().
languageChange()
void PythonCommand::languageChange () override virtual
Reassigns QAction stuff after the language has changed.
Reimplemented from Gui::Command.
Definition at line 1378 of file Gui/Command.cpp.
References Gui::CommandBase::_pcAction, Gui::Command::applyCommandData(), and Gui::Command::getName().
onActionInit()
void PythonCommand::onActionInit () const protected
Definition at line 1481 of file Gui/Command.cpp.
References _pcPyCommand, toolbit-attributes::args, connPyCmdInitialized, and SCL.SimpleDataTypes::e.
Referenced by PythonCommand().
Member Data Documentation
_pcPyCommand
PyObject* Gui::PythonCommand::_pcPyCommand protected
a pointer to the Python command object
Definition at line 726 of file Gui/Command.h.
Referenced by activated(), getHelpUrl(), isActive(), onActionInit(), PythonCommand(), and ~PythonCommand().
_pcPyResourceDict
PyObject* Gui::PythonCommand::_pcPyResourceDict protected
the command object resource dictionary
Definition at line 728 of file Gui/Command.h.
Referenced by getResource(), isCheckable(), isChecked(), and PythonCommand().
Activation
std::string Gui::PythonCommand::Activation protected
the activation sequence
Definition at line 730 of file Gui/Command.h.
Referenced by activated(), and PythonCommand().
connPyCmdInitialized
boost::signals2::connection Gui::PythonCommand::connPyCmdInitialized protected
Definition at line 734 of file Gui/Command.h.
Referenced by onActionInit(), and PythonCommand().
The documentation for this class was generated from the following files:
Gui/Command.h
Gui/Command.cpp