FreeCAD: Gui::Dialog::DlgCustomizeImp Class Reference
Gui::Dialog::DlgCustomizeImp Class Reference
#include <DlgCustomizeImp.h>
Signals
void addMacroAction (const QByteArray &)
void removeMacroAction (const QByteArray &)
void modifyMacroAction (const QByteArray &)
Public Member Functions
DlgCustomizeImp (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgCustomizeImp () override
void addPage (QWidget *w)
Static Public Member Functions
static void addPage (const char *className)
Protected Member Functions
void changeEvent (QEvent *e) override
Detailed Description
Dialog which contains several tab pages to customize the changeable toolbars and commandbars or to define own macro actions.
You can extend the existing toolbars or commandbars with several commands just by drag and drop.
See also
DlgCustomCommandsImp
DlgCustomToolbarsImp
DlgCustomCmdbarsImp
DlgCustomActionsImp
Author
Werner Mayer
Definition at line 49 of file DlgCustomizeImp.h.
Constructor & Destructor Documentation
DlgCustomizeImp()
DlgCustomizeImp::DlgCustomizeImp (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Constructs a DlgCustomizeImp which is a child of 'parent', with the name 'name' and widget flags set to 'f'
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
Definition at line 50 of file DlgCustomizeImp.cpp.
References addPage(), draftgeoutils.intersections::connect(), Gui::getMainWindow(), Gui::GetWidgetFactorySupplier(), Gui::MainWindow::whatsThis(), and Gui::WidgetFactory().
~DlgCustomizeImp()
DlgCustomizeImp::~DlgCustomizeImp () override default
Destroys the object and frees any allocated resources
Member Function Documentation
addMacroAction
void Gui::Dialog::DlgCustomizeImp::addMacroAction (const QByteArray &) signal
addPage() [1/2]
void DlgCustomizeImp::addPage (const char * className) static
Adds a customize page with its class name className. To create this page it must be registered in the WidgetFactory.
See also
WidgetFactory
CustomPageProducer
Definition at line 115 of file DlgCustomizeImp.cpp.
Referenced by Gui::CustomPageProducer< CLASS >::CustomPageProducer(), and DlgCustomizeImp().
addPage() [2/2]
void DlgCustomizeImp::addPage (QWidget * w)
Inserts a new tab page with its caption
Definition at line 121 of file DlgCustomizeImp.cpp.
References src.Mod.PartDesign.fcgear.svggear::w.
changeEvent()
void DlgCustomizeImp::changeEvent (QEvent * e) override protected
Definition at line 126 of file DlgCustomizeImp.cpp.
References src.Mod.AddonManager.NetworkManager::count, SCL.SimpleDataTypes::e, SplineSurface::i, and src.Mod.PartDesign.fcgear.svggear::w.
modifyMacroAction
void Gui::Dialog::DlgCustomizeImp::modifyMacroAction (const QByteArray &) signal
removeMacroAction
void Gui::Dialog::DlgCustomizeImp::removeMacroAction (const QByteArray &) signal
The documentation for this class was generated from the following files:
DlgCustomizeImp.h
DlgCustomizeImp.cpp