FreeCAD: App::Color Class Reference
App::Color Class Reference
#include <Color.h>
Public Member Functions
Color (float R=0.0, float G=0.0, float B=0.0, float A=1.0)
Color (uint32_t rgba)
Color (const Color &c)=default
Color (Color &&)=default
bool operator== (const Color &c) const
bool operator!= (const Color &c) const
void set (float R, float G, float B, float A=1.0)
float transparency () const
void setTransparency (float value)
Color & operator= (const Color &c)=default
Color & operator= (Color &&c)=default
Color & setPackedValue (uint32_t rgba)
uint32_t getPackedValue () const
uint32_t getPackedRGB () const
void setPackedRGB (uint32_t)
uint32_t getPackedARGB () const
void setPackedARGB (uint32_t)
template<typename T >
void setValue (const T &q)
template<typename T >
T asValue () const
std::string asHexString () const
bool fromHexString (const std::string &hex)
Static Public Member Functions
template<typename T >
static uint32_t asPackedRGBA (const T &color)
template<typename T >
static T fromPackedRGBA (uint32_t color)
template<typename T >
static uint32_t asPackedRGB (const T &color)
template<typename T >
static T fromPackedRGB (uint32_t color)
template<typename T >
static Color fromValue (const T &q)
Public Attributes
float r {}
color values, public accessible
float g {}
float b {}
float a {}
Detailed Description
Color class
Definition at line 109 of file Color.h.
Constructor & Destructor Documentation
Color() [1/4]
Color::Color (float R = 0.0, float G = 0.0, float B = 0.0, float A = 1.0) explicit
Defines the color as (R,G,B,A) whereas all values are in the range [0,1]. A defines the alpha value.
Definition at line 37 of file Color.cpp.
References blue, green, and red.
Color() [2/4]
Color::Color (uint32_t rgba) explicit
Does basically the same as the constructor above unless that (R,G,B,A) is encoded as an unsigned int.
Definition at line 44 of file Color.cpp.
Color() [3/4]
App::Color::Color (const Color & c) default
Copy constructor.
Color() [4/4]
App::Color::Color (Color &&) default
Member Function Documentation
asHexString()
std::string Color::asHexString () const
returns color as hex color "#RRGGBB"
Definition at line 139 of file Color.cpp.
References b, g, and r.
Referenced by MeshPart::BrepMesh::create(), TechDraw::DrawViewDraft::execute(), TechDraw::CosmeticVertex::Save(), TechDraw::CosmeticEdge::Save(), TechDraw::CenterLine::Save(), TechDraw::GeomFormat::Save(), TechDrawGui::QGIFace::setHatchColor(), TechDraw::CosmeticVertex::toString(), and TechDraw::LineFormat::toString().
asPackedRGB()
template<typename T > static uint32_t App::Color::asPackedRGB (const T & color) inline static
Definition at line 188 of file Color.h.
asPackedRGBA()
template<typename T > static uint32_t App::Color::asPackedRGBA (const T & color) inline static
Definition at line 172 of file Color.h.
asValue()
template<typename T > T App::Color::asValue () const inline
returns a template type e.g. Qt color equivalent to FC color
Definition at line 215 of file Color.h.
Referenced by TechDrawGui::PreferencesGui::breaklineQColor(), TechDrawGui::PreferencesGui::centerQColor(), MatGui::ColorWidget::ColorWidget(), TechDrawGui::PreferencesGui::dimQColor(), TechDrawGui::QGIViewPart::drawAllEdges(), TechDrawGui::QGIViewPart::drawAllFaces(), TechDrawGui::QGIViewPart::drawBreakLines(), TechDrawGui::QGIViewPart::drawComplexSectionLine(), TechDrawGui::QGIViewPart::drawHighlight(), TechDrawGui::QGIViewPart::drawSectionLine(), TechDrawGui::QGIViewPart::formatGeomFromCenterLine(), TechDrawGui::QGIViewPart::formatGeomFromCosmetic(), TechDrawGui::QGVPage::getBackgroundColor(), TechDrawGui::QGSPage::getBackgroundColor(), TechDrawGui::QGIEdge::getHiddenColor(), TechDrawGui::QGITile::getTileColor(), TechDrawGui::QGTracker::getTrackerColor(), TechDrawGui::PreferencesGui::gridQColor(), TechDrawGui::TaskGeomHatch::initUi(), TechDrawGui::TaskLineDecor::initUi(), TechDrawGui::PreferencesGui::leaderQColor(), TechDrawGui::PreferencesGui::normalQColor(), TechDrawGui::PreferencesGui::pageQColor(), TechDrawGui::QGILeaderLine::prefNormalColor(), TechDrawGui::QGIViewDimension::prefNormalColor(), TechDrawGui::QGIViewBalloon::prefNormalColor(), TechDrawGui::PreferencesGui::preselectQColor(), TechDrawGui::QGIFace::QGIFace(), TechDrawGui::QGIRichAnno::rectPen(), TechDrawGui::PreferencesGui::sectionLineQColor(), TechDrawGui::PreferencesGui::selectQColor(), MatGui::DlgDisplayPropertiesImp::Private::setElementAppearance(), MatGui::DlgDisplayPropertiesImp::Private::setElementColor(), TechDrawGui::QGIFace::setHatchColor(), TechDrawGui::TaskHatch::setUiEdit(), TechDrawGui::TaskCenterLine::setUiEdit(), TechDrawGui::TaskRichAnno::setUiEdit(), TechDrawGui::TaskLeaderLine::setUiEdit(), TechDrawGui::TaskBalloon::TaskBalloon(), TechDrawGui::TaskDimension::TaskDimension(), and TechDrawGui::PreferencesGui::templateClickBoxColor().
fromHexString()
bool Color::fromHexString (const std::string & hex)
gets color from hex color "#RRGGBB"
Definition at line 151 of file Color.cpp.
References a, b, g, and r.
Referenced by MeshGui::ViewProviderMesh::highlightSegments(), TechDraw::CosmeticVertex::Restore(), TechDraw::CosmeticEdge::Restore(), TechDraw::CenterLine::Restore(), and TechDraw::GeomFormat::Restore().
fromPackedRGB()
template<typename T > static T App::Color::fromPackedRGB (uint32_t color) inline static
Definition at line 195 of file Color.h.
References a, SCL.SimpleDataTypes::b, toolbit-attributes::g, and App::color_traits< color_type >::makeColor().
fromPackedRGBA()
template<typename T > static T App::Color::fromPackedRGBA (uint32_t color) inline static
Definition at line 179 of file Color.h.
fromValue()
template<typename T > static Color App::Color::fromValue (const T & q) inline static
creates FC Color from template type, e.g. Qt QColor
Definition at line 228 of file Color.h.
getPackedARGB()
uint32_t Color::getPackedARGB () const
Returns color as a 32 bit packed unsigned int in the form 0xAARRGGBB.
Definition at line 119 of file Color.cpp.
References a, b, g, and r.
getPackedRGB()
uint32_t Color::getPackedRGB () const
Returns color as a 32 bit packed unsigned int in the form 0xRRGGBB.
Definition at line 110 of file Color.cpp.
References b, g, and r.
getPackedValue()
uint32_t Color::getPackedValue () const
Returns color as a 32 bit packed unsigned int in the form 0xRRGGBBAA.
See also
setPackedValue().
Definition at line 91 of file Color.cpp.
References a, b, g, and r.
Referenced by Import::ExportOCAF2::customExportOptions(), Import::ImportOCAF2::customImportOptions(), App::ColorLegend::getPackedColor(), operator==(), PartGui::ViewProviderGridExtension::setGridDivLineColor(), and PartGui::ViewProviderGridExtension::setGridLineColor().
operator!=()
bool Color::operator!= (const Color & c) const
Definition at line 55 of file Color.cpp.
References operator==().
operator=() [1/2]
Color& App::Color::operator= (Color && c) default
operator=() [2/2]
Color& App::Color::operator= (const Color & c) default
operator==()
bool Color::operator== (const Color & c) const
Returns true if both colors are equal. Therefore all components must be equal.
Definition at line 50 of file Color.cpp.
References getPackedValue().
Referenced by operator!=().
set()
void Color::set (float R, float G, float B, float A = 1.0)
Defines the color as (R,G,B,A) whereas all values are in the range [0,1]. A defines the alpha value, 1 means fully opaque and 0 transparent.
Definition at line 61 of file Color.cpp.
References a, b, blue, g, green, r, and red.
Referenced by TechDrawGui::TaskSelectLineAttributes::accept(), draftguitools.gui_trackers.editTracker::move(), setPackedARGB(), setPackedRGB(), setPackedValue(), App::Material::setType(), PartGui::ViewProviderPartExt::ViewProviderPartExt(), and PartGui::ViewProviderPartReference::ViewProviderPartReference().
setPackedARGB()
void Color::setPackedARGB (uint32_t argb)
Sets color as a 32 bit packed unsigned int in the form 0xAARRGGBB.
Definition at line 129 of file Color.cpp.
References set().
Referenced by Points::PcdReader::read().
setPackedRGB()
void Color::setPackedRGB (uint32_t rgb)
Sets color as a 32 bit packed unsigned int in the form 0xRRGGBB.
Definition at line 101 of file Color.cpp.
References set().
setPackedValue()
Color & Color::setPackedValue (uint32_t rgba)
Sets the color value as a 32 bit combined red/green/blue/alpha value. Each component is 8 bit wide (i.e. from 0x00 to 0xff), and the red value should be stored leftmost, like this: 0xRRGGBBAA.
See also
getPackedValue().
Definition at line 80 of file Color.cpp.
References set().
Referenced by TechDrawGui::PreferencesGui::breaklineColor(), TechDrawGui::PreferencesGui::breaklineQColor(), MeshPart::BrepMesh::create(), Import::ExportOCAF2::customExportOptions(), Import::ImportOCAF2::customImportOptions(), TechDrawGui::PreferencesGui::dimColor(), TechDrawGui::PreferencesGui::dimQColor(), TechDrawGui::QGVPage::getBackgroundColor(), TechDrawGui::QGSPage::getBackgroundColor(), TechDrawGui::PreferencesGui::gridColor(), TechDrawGui::PreferencesGui::gridQColor(), TechDrawGui::PreferencesGui::leaderColor(), TechDrawGui::PreferencesGui::leaderQColor(), PartDesignGui::ViewProviderSubShapeBinder::onChanged(), TechDraw::DrawGeomHatch::prefGeomHatchColor(), TechDrawGui::ViewProviderViewPart::prefHighlightColor(), TechDraw::DrawHatch::prefSvgHatchColor(), TechDrawGui::PreferencesGui::sectionLineColor(), TechDrawGui::PreferencesGui::sectionLineQColor(), App::PropertyColor::setPyObject(), TechDrawGui::PreferencesGui::templateClickBoxColor(), Gui::ViewProviderLink::ViewProviderLink(), and MeshGui::ViewProviderMeshCurvature::ViewProviderMeshCurvature().
setTransparency()
void Color::setTransparency (float value)
Definition at line 74 of file Color.cpp.
References a.
Referenced by PartGui::ViewProviderPartExt::getElementColors(), and Gui::ViewProviderLink::getElementColors().
setValue()
template<typename T > void App::Color::setValue (const T & q) inline
creates FC Color from template type, e.g. Qt QColor
Definition at line 205 of file Color.h.
Referenced by MeshGui::ViewProviderFace::attach(), TechDrawGui::TaskRichAnno::createAnnoFeature(), TechDrawGui::TaskCenterLine::createCenterLine(), TechDrawGui::TaskHatch::createHatch(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), MeshGui::ViewProviderMeshCurvature::onChanged(), MeasureGui::ViewProviderMeasureBase::onChanged(), TechDrawGui::TaskHatch::onColorChanged(), TechDrawGui::TaskLineDecor::onColorChanged(), Gui::PropertyEditor::PropertyMaterialItem::setValue(), Gui::PropertyEditor::PropertyMaterialListItem::setValue(), TechDrawGui::TaskRichAnno::updateAnnoFeature(), TechDrawGui::TaskHatch::updateHatch(), TechDrawGui::TaskLeaderLine::updateLeaderFeature(), and TechDrawGui::TaskGeomHatch::updateValues().
transparency()
float Color::transparency () const
Definition at line 69 of file Color.cpp.
References a.
Referenced by Gui::ViewProviderLink::setElementColors().
Member Data Documentation
a
float App::Color::a {}
Definition at line 246 of file Color.h.
Referenced by SpreadsheetGui::PropertiesDialog::apply(), TechDraw::DrawUtil::colorToPyTuple(), Import::Tools::convertColor(), Import::ExportOCAF2::customExportOptions(), Import::ImportOCAF2::customImportOptions(), SpreadsheetGui::SheetModel::data(), Spreadsheet::Cell::encodeColor(), fromHexString(), App::ColorGradient::getColor(), getPackedARGB(), getPackedValue(), PartGui::FaceAppearances::onSelectionChanged(), operator<<(), SpreadsheetGui::PropertiesDialog::PropertiesDialog(), set(), Materials::MaterialProperty::setColor(), App::PropertyColor::setPyObject(), setTransparency(), transparency(), and PartDesignGui::ViewProviderDatum::ViewProviderDatum().
b
float App::Color::b {}
Definition at line 246 of file Color.h.
Referenced by App::ColorLegend::addMax(), App::ColorLegend::addMin(), SpreadsheetGui::PropertiesDialog::apply(), asHexString(), MeshGui::ViewProviderFace::attach(), TechDraw::DrawUtil::colorToPyTuple(), Import::Tools::convertColor(), SpreadsheetGui::SheetModel::data(), Spreadsheet::Cell::encodeColor(), fromHexString(), App::ColorField::getColor(), getPackedARGB(), getPackedRGB(), getPackedValue(), App::ColorField::interpolate(), Import::ImpExpDxfRead::MakeLayer(), MeshGui::ViewProviderMeshCurvature::onChanged(), MeasureGui::ViewProviderMeasureBase::onChanged(), PartGui::ViewProviderPartExt::onChanged(), PartGui::FaceAppearances::onSelectionChanged(), operator<<(), SpreadsheetGui::PropertiesDialog::PropertiesDialog(), MeshCore::MeshOutput::SaveAsymptote(), MeshCore::MeshOutput::SaveX3DContent(), set(), Gui::ViewProviderTextureExtension::setCoinAppearance(), Gui::ViewProviderGeometryObject::setCoinAppearance(), Materials::MaterialProperty::setColor(), Gui::SoFCColorLegend::setColorLegend(), InspectionGui::ViewProviderInspection::setDistances(), FemGui::ViewProviderFemMesh::setMaterialByColorArray(), FemGui::ViewProviderFemMesh::setMaterialOverall(), App::PropertyColor::setPyObject(), src.Mod.Test.Menu.MenuCreateCases::tearDown(), and src.Mod.Test.Menu.MenuDeleteCases::tearDown().
g
float App::Color::g {}
Definition at line 246 of file Color.h.
Referenced by App::ColorLegend::addMax(), App::ColorLegend::addMin(), SpreadsheetGui::PropertiesDialog::apply(), asHexString(), MeshGui::ViewProviderFace::attach(), TechDraw::DrawUtil::colorToPyTuple(), Import::Tools::convertColor(), SpreadsheetGui::SheetModel::data(), Spreadsheet::Cell::encodeColor(), fromHexString(), App::ColorField::getColor(), getPackedARGB(), getPackedRGB(), getPackedValue(), App::ColorField::interpolate(), Import::ImpExpDxfRead::MakeLayer(), MeshGui::ViewProviderMeshCurvature::onChanged(), MeasureGui::ViewProviderMeasureBase::onChanged(), PartGui::ViewProviderPartExt::onChanged(), PartGui::FaceAppearances::onSelectionChanged(), operator<<(), SpreadsheetGui::PropertiesDialog::PropertiesDialog(), MeshCore::MeshOutput::SaveAsymptote(), MeshCore::MeshOutput::SaveX3DContent(), set(), Gui::ViewProviderTextureExtension::setCoinAppearance(), Gui::ViewProviderGeometryObject::setCoinAppearance(), Materials::MaterialProperty::setColor(), Gui::SoFCColorLegend::setColorLegend(), InspectionGui::ViewProviderInspection::setDistances(), FemGui::ViewProviderFemMesh::setMaterialByColorArray(), FemGui::ViewProviderFemMesh::setMaterialOverall(), and App::PropertyColor::setPyObject().
r
float App::Color::r {}
color values, public accessible
Definition at line 246 of file Color.h.
Referenced by App::ColorLegend::addMax(), App::ColorLegend::addMin(), SpreadsheetGui::PropertiesDialog::apply(), asHexString(), MeshGui::ViewProviderFace::attach(), TechDraw::DrawUtil::colorToPyTuple(), Import::Tools::convertColor(), SpreadsheetGui::SheetModel::data(), Spreadsheet::Cell::encodeColor(), fromHexString(), App::ColorField::getColor(), getPackedARGB(), getPackedRGB(), getPackedValue(), App::ColorField::interpolate(), Import::ImpExpDxfRead::MakeLayer(), MeshGui::ViewProviderMeshCurvature::onChanged(), MeasureGui::ViewProviderMeasureBase::onChanged(), PartGui::ViewProviderPartExt::onChanged(), PartGui::FaceAppearances::onSelectionChanged(), operator<<(), SpreadsheetGui::PropertiesDialog::PropertiesDialog(), MeshCore::MeshOutput::SaveAsymptote(), MeshCore::MeshOutput::SaveX3DContent(), set(), Gui::ViewProviderTextureExtension::setCoinAppearance(), Gui::ViewProviderGeometryObject::setCoinAppearance(), Materials::MaterialProperty::setColor(), Gui::SoFCColorLegend::setColorLegend(), InspectionGui::ViewProviderInspection::setDistances(), FemGui::ViewProviderFemMesh::setMaterialByColorArray(), FemGui::ViewProviderFemMesh::setMaterialOverall(), and App::PropertyColor::setPyObject().
The documentation for this class was generated from the following files:
Color.h
Color.cpp