FreeCAD: AppDrawingGui.cpp File Reference
AppDrawingGui.cpp File Reference
#include "PreCompiled.h"
#include <Base/Console.h>
#include <Base/PyObjectBase.h>
#include <Gui/Application.h>
#include <Gui/Language/Translator.h>
#include "ViewProviderPage.h"
#include "ViewProviderView.h"
#include "Workbench.h"
Namespaces
DrawingGui
Functions
void CreateDrawingCommands (void)
void loadDrawingResource ()
PyObject * DrawingGui::initModule ()
PyMOD_INIT_FUNC (DrawingGui)
Function Documentation
CreateDrawingCommands()
void CreateDrawingCommands (void)
Definition at line 859 of file Mod/Drawing/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
loadDrawingResource()
void loadDrawingResource ()
Definition at line 38 of file AppDrawingGui.cpp.
References Gui::Translator::instance(), and Gui::Translator::refresh().
Referenced by PyMOD_INIT_FUNC().
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (DrawingGui)
Definition at line 53 of file AppDrawingGui.cpp.
References Base::Console(), CreateDrawingCommands(), SIM::Coin3D::Quarter::Quarter::init(), Base::Persistence::init(), Base::BaseClass::init(), App::Extension::init(), DrawingGui::initModule(), Gui::Application::Instance, loadDrawingResource(), Base::ConsoleSingleton::Log(), mod, and PyMOD_Return.