FreeCAD: App::ExpressionVisitor Class Reference
App::ExpressionVisitor Class Reference abstract
#include <Expression.h>
Public Member Functions
virtual ~ExpressionVisitor ()=default
virtual void visit (Expression &e)=0
virtual void aboutToChange ()
virtual int changed () const
virtual void reset ()
virtual App::PropertyLinkBase * getPropertyLink ()
Protected Member Functions
void getIdentifiers (Expression &e, std::map< App::ObjectIdentifier, bool > &)
bool adjustLinks (Expression &e, const std::set< App::DocumentObject * > &inList)
bool relabeledDocument (Expression &e, const std::string &oldName, const std::string &newName)
bool renameObjectIdentifier (Expression &e, const std::map< ObjectIdentifier, ObjectIdentifier > &, const ObjectIdentifier &)
void collectReplacement (Expression &e, std::map< ObjectIdentifier, ObjectIdentifier > &, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const
bool updateElementReference (Expression &e, App::DocumentObject *feature, bool reverse)
void importSubNames (Expression &e, const ObjectIdentifier::SubNameMap &subNameMap)
void updateLabelReference (Expression &e, App::DocumentObject *obj, const std::string &ref, const char *newLabel)
void moveCells (Expression &e, const CellAddress &address, int rowCount, int colCount)
void offsetCells (Expression &e, int rowOffset, int colOffset)
Detailed Description
Definition at line 58 of file Expression.h.
Constructor & Destructor Documentation
~ExpressionVisitor()
virtual App::ExpressionVisitor::~ExpressionVisitor () virtual default
Member Function Documentation
aboutToChange()
virtual void App::ExpressionVisitor::aboutToChange () inline virtual
Reimplemented in App::ExpressionModifier< P >.
Definition at line 62 of file Expression.h.
Referenced by App::VariableExpression::_renameObjectIdentifier().
adjustLinks()
bool ExpressionVisitor::adjustLinks (Expression & e, const std::set< App::DocumentObject * > & inList) protected
Definition at line 240 of file Expression.cpp.
References SCL.SimpleDataTypes::e.
changed()
virtual int App::ExpressionVisitor::changed () const inline virtual
Reimplemented in App::ExpressionModifier< P >.
Definition at line 63 of file Expression.h.
collectReplacement()
void ExpressionVisitor::collectReplacement (Expression & e, std::map< ObjectIdentifier, ObjectIdentifier > & paths, const App::DocumentObject * parent, App::DocumentObject * oldObj, App::DocumentObject * newObj) const protected
Definition at line 270 of file Expression.cpp.
References SCL.SimpleDataTypes::e, and Init::parent.
getIdentifiers()
void ExpressionVisitor::getIdentifiers (Expression & e, std::map< App::ObjectIdentifier, bool > & ids) protected
Definition at line 236 of file Expression.cpp.
References SCL.SimpleDataTypes::e.
getPropertyLink()
virtual App::PropertyLinkBase* App::ExpressionVisitor::getPropertyLink () inline virtual
Reimplemented in App::ExpressionModifier< P >.
Definition at line 65 of file Expression.h.
importSubNames()
void ExpressionVisitor::importSubNames (Expression & e, const ObjectIdentifier::SubNameMap & subNameMap) protected
Definition at line 244 of file Expression.cpp.
References SCL.SimpleDataTypes::e.
moveCells()
void ExpressionVisitor::moveCells (Expression & e, const CellAddress & address, int rowCount, int colCount) protected
Definition at line 277 of file Expression.cpp.
References SCL.SimpleDataTypes::e.
Referenced by App::RelabelDocumentExpressionVisitor::visit().
offsetCells()
void ExpressionVisitor::offsetCells (Expression & e, int rowOffset, int colOffset) protected
Definition at line 281 of file Expression.cpp.
References SCL.SimpleDataTypes::e.
Referenced by App::MoveCellsExpressionVisitor< P >::visit().
relabeledDocument()
bool ExpressionVisitor::relabeledDocument (Expression & e, const std::string & oldName, const std::string & newName) protected
Definition at line 258 of file Expression.cpp.
References SCL.SimpleDataTypes::e.
Referenced by App::UpdateElementReferenceExpressionVisitor< P >::visit().
renameObjectIdentifier()
bool ExpressionVisitor::renameObjectIdentifier (Expression & e, const std::map< ObjectIdentifier, ObjectIdentifier > & paths, const ObjectIdentifier & path) protected
Definition at line 264 of file Expression.cpp.
References SCL.SimpleDataTypes::e.
reset()
virtual void App::ExpressionVisitor::reset () inline virtual
Reimplemented in App::ExpressionModifier< P >.
Definition at line 64 of file Expression.h.
Referenced by ArchVRM.Renderer::__init__(), draftguitools.gui_trackers.gridTracker::set(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testAll(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
updateElementReference()
bool ExpressionVisitor::updateElementReference (Expression & e, App::DocumentObject * feature, bool reverse) protected
Definition at line 254 of file Expression.cpp.
References SCL.SimpleDataTypes::e.
updateLabelReference()
void ExpressionVisitor::updateLabelReference (Expression & e, App::DocumentObject * obj, const std::string & ref, const char * newLabel) protected
Definition at line 248 of file Expression.cpp.
References SCL.SimpleDataTypes::e.
visit()
virtual void App::ExpressionVisitor::visit (Expression & e) pure virtual
Implemented in App::OffsetCellsExpressionVisitor< P >, App::MoveCellsExpressionVisitor< P >, App::RelabelDocumentExpressionVisitor, App::UpdateElementReferenceExpressionVisitor< P >, App::RenameObjectIdentifierExpressionVisitor< P >, ReplaceObjectExpressionVisitor, UpdateLabelExpressionVisitor, ImportSubNamesExpressionVisitor, AdjustLinksExpressionVisitor, and GetIdentifiersExpressionVisitor.
The documentation for this class was generated from the following files:
Expression.h
Expression.cpp