FreeCAD: PartGui::DlgExportStep Class Reference
PartGui::DlgExportStep Class Reference
#include <DlgExportStep.h>
Public Member Functions
DlgExportStep (QWidget *parent=nullptr)
~DlgExportStep () override
void saveSettings () override
void loadSettings () override
StepSettings getSettings () const
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
Definition at line 46 of file DlgExportStep.h.
Constructor & Destructor Documentation
DlgExportStep()
DlgExportStep::DlgExportStep (QWidget * parent = nullptr) explicit
Definition at line 46 of file DlgExportStep.cpp.
References Part::OCAF::ImportExportSettings::getExportHiddenObject(), Part::OCAF::ImportExportSettings::getExportKeepPlacement(), and Part::OCAF::ImportExportSettings::getExportLegacy().
~DlgExportStep()
DlgExportStep::~DlgExportStep () override default
Destroys the object and frees any allocated resources
Member Function Documentation
changeEvent()
void DlgExportStep::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 128 of file DlgExportStep.cpp.
References SCL.SimpleDataTypes::e.
getSettings()
StepSettings DlgExportStep::getSettings () const
Definition at line 116 of file DlgExportStep.cpp.
References PartGui::StepSettings::exportHidden, PartGui::StepSettings::exportLegacy, and PartGui::StepSettings::keepPlacement.
loadSettings()
void DlgExportStep::loadSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 95 of file DlgExportStep.cpp.
References Part::STEP::ImportExportSettings::getScheme(), Part::STEP::ImportExportSettings::getUnit(), and Part::STEP::ImportExportSettings::getWriteSurfaceCurveMode().
Referenced by PartGui::DlgImportExportStep::loadSettings().
saveSettings()
void DlgExportStep::saveSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 74 of file DlgExportStep.cpp.
References Part::STEP::ImportExportSettings::setScheme(), Part::STEP::ImportExportSettings::setUnit(), Part::STEP::ImportExportSettings::setWriteSurfaceCurveMode(), and unit().
Referenced by PartGui::DlgImportExportStep::saveSettings().
The documentation for this class was generated from the following files:
DlgExportStep.h
DlgExportStep.cpp