FreeCAD: SurfaceGui::FillingVertexPanel Class Reference
SurfaceGui::FillingVertexPanel Class Reference
#include <TaskFillingVertex.h>
Classes
class VertexSelection
Public Member Functions
FillingVertexPanel (ViewProviderFilling *vp, Surface::Filling *obj)
~FillingVertexPanel () override
void open ()
void reject ()
void checkOpenCommand ()
void setEditedObject (Surface::Filling *obj)
void appendButtons (Gui::ButtonGroup *)
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Public Member Functions inherited from Gui::DocumentObserver
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
void attachDocument (Document *)
void detachDocument ()
Protected Types
enum SelectionMode { None = SurfaceGui::SelectionMode::None, AppendVertex = SurfaceGui::SelectionMode::AppendVertexConstraint, RemoveVertex = SurfaceGui::SelectionMode::RemoveVertexConstraint }
Protected Member Functions
void changeEvent (QEvent *e) override
void onSelectionChanged (const Gui::SelectionChanges &msg) override
void slotUndoDocument (const Gui::Document &Doc) override
void slotRedoDocument (const Gui::Document &Doc) override
void slotDeletedObject (const Gui::ViewProviderDocumentObject &Obj) override
Protected Attributes
SelectionMode selectionMode
Surface::Filling * editedObject
bool checkCommand
Detailed Description
Definition at line 46 of file TaskFillingVertex.h.
Member Enumeration Documentation
SelectionMode
enum SurfaceGui::FillingVertexPanel::SelectionMode protected
Enumerator
None
AppendVertex
RemoveVertex
Definition at line 54 of file TaskFillingVertex.h.
Constructor & Destructor Documentation
FillingVertexPanel()
SurfaceGui::FillingVertexPanel::FillingVertexPanel (ViewProviderFilling * vp, Surface::Filling * obj)
Definition at line 115 of file TaskFillingVertex.cpp.
References Path.Post.scripts.dynapath_4060_post::action, checkCommand, draftgeoutils.intersections::connect(), None, selectionMode, and setEditedObject().
~FillingVertexPanel()
SurfaceGui::FillingVertexPanel::~FillingVertexPanel () override
Definition at line 138 of file TaskFillingVertex.cpp.
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
appendButtons()
void SurfaceGui::FillingVertexPanel::appendButtons (Gui::ButtonGroup * buttonGroup)
Definition at line 157 of file TaskFillingVertex.cpp.
Referenced by SurfaceGui::TaskFilling::TaskFilling().
changeEvent()
void SurfaceGui::FillingVertexPanel::changeEvent (QEvent * e) override protected
Definition at line 191 of file TaskFillingVertex.cpp.
References SCL.SimpleDataTypes::e.
checkOpenCommand()
void SurfaceGui::FillingVertexPanel::checkOpenCommand ()
Definition at line 222 of file TaskFillingVertex.cpp.
References checkCommand, editedObject, App::PropertyString::getValue(), Gui::Command::hasPendingCommand(), App::DocumentObject::Label, FreeCADInit::Msg, and Gui::Command::openCommand().
Referenced by onSelectionChanged(), and open().
onSelectionChanged()
void SurfaceGui::FillingVertexPanel::onSelectionChanged (const Gui::SelectionChanges & msg) override protected virtual
Implements Gui::SelectionObserver.
Definition at line 277 of file TaskFillingVertex.cpp.
References Gui::SelectionChanges::AddSelection, AppendVertex, checkOpenCommand(), editedObject, Gui::SelectionObject::getObject(), App::PropertyLinkSubList::getSubListValues(), App::PropertyLinkSubList::getSubValues(), App::PropertyString::getValue(), App::PropertyLinkSubList::getValues(), SurfaceGui::ViewProviderFilling::highlightReferences(), SplineSurface::i, App::DocumentObject::Label, Path.Op.Surface::msg, None, importers.importIFCmulticore::objects, Surface::Filling::Points, App::DocumentObject::recomputeFeature(), RemoveVertex, selectionMode, App::PropertyLinkSubList::setValues(), and SurfaceGui::ViewProviderFilling::Vertex.
open()
void SurfaceGui::FillingVertexPanel::open ()
Definition at line 201 of file TaskFillingVertex.cpp.
References checkOpenCommand(), Gui::SelectionSingleton::clearSelection(), editedObject, App::PropertyLinkSubList::getSubListValues(), SurfaceGui::ViewProviderFilling::highlightReferences(), Surface::Filling::Points, Gui::Selection(), and SurfaceGui::ViewProviderFilling::Vertex.
Referenced by SurfaceGui::TaskFilling::open().
reject()
void SurfaceGui::FillingVertexPanel::reject ()
Definition at line 210 of file TaskFillingVertex.cpp.
References editedObject, App::PropertyLinkSubList::getSubListValues(), SurfaceGui::ViewProviderFilling::highlightReferences(), Surface::Filling::Points, and SurfaceGui::ViewProviderFilling::Vertex.
Referenced by SurfaceGui::TaskFilling::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and SurfaceGui::TaskFilling::reject().
setEditedObject()
void SurfaceGui::FillingVertexPanel::setEditedObject (Surface::Filling * obj)
Definition at line 164 of file TaskFillingVertex.cpp.
References Gui::DocumentObserver::attachDocument(), toolbit-attributes::doc, editedObject, App::DocumentObject::getDocument(), App::PropertyLinkSubList::getSubValues(), App::PropertyLinkSubList::getValues(), Gui::Application::Instance, importers.importIFCmulticore::objects, and Surface::Filling::Points.
Referenced by FillingVertexPanel().
slotDeletedObject()
void SurfaceGui::FillingVertexPanel::slotDeletedObject (const Gui::ViewProviderDocumentObject & Obj) override protected virtual
Notifies when the object is about to be removed.
Reimplemented from Gui::DocumentObserver.
Definition at line 242 of file TaskFillingVertex.cpp.
References editedObject, App::PropertyLinkSubList::getSubListValues(), SurfaceGui::ViewProviderFilling::highlightReferences(), Surface::Filling::Points, and SurfaceGui::ViewProviderFilling::Vertex.
slotRedoDocument()
void SurfaceGui::FillingVertexPanel::slotRedoDocument (const Gui::Document & Doc) override protected virtual
Notifies on redo
Reimplemented from Gui::DocumentObserver.
Definition at line 237 of file TaskFillingVertex.cpp.
References checkCommand.
slotUndoDocument()
void SurfaceGui::FillingVertexPanel::slotUndoDocument (const Gui::Document & Doc) override protected virtual
Notifies on undo
Reimplemented from Gui::DocumentObserver.
Definition at line 232 of file TaskFillingVertex.cpp.
References checkCommand.
Member Data Documentation
checkCommand
bool SurfaceGui::FillingVertexPanel::checkCommand protected
Definition at line 62 of file TaskFillingVertex.h.
Referenced by checkOpenCommand(), FillingVertexPanel(), slotRedoDocument(), and slotUndoDocument().
editedObject
Surface::Filling* SurfaceGui::FillingVertexPanel::editedObject protected
Definition at line 61 of file TaskFillingVertex.h.
Referenced by checkOpenCommand(), onSelectionChanged(), open(), reject(), setEditedObject(), and slotDeletedObject().
selectionMode
SelectionMode SurfaceGui::FillingVertexPanel::selectionMode protected
Definition at line 60 of file TaskFillingVertex.h.
Referenced by FillingVertexPanel(), and onSelectionChanged().
The documentation for this class was generated from the following files:
TaskFillingVertex.h
TaskFillingVertex.cpp