FreeCAD: Gui::FileDialog Class Reference
Gui::FileDialog Class Reference
#include <FileDialog.h>
Public Member Functions
FileDialog (QWidget *parent=nullptr)
~FileDialog () override
void accept () override
Static Public Member Functions
static QString getOpenFileName (QWidget *parent=nullptr, const QString &caption=QString(), const QString &dir=QString(), const QString &filter=QString(), QString *selectedFilter=nullptr, Options options=Options())
static QString getSaveFileName (QWidget *parent=nullptr, const QString &caption=QString(), const QString &dir=QString(), const QString &filter=QString(), QString *selectedFilter=nullptr, Options options=Options())
static QString getExistingDirectory (QWidget *parent=nullptr, const QString &caption=QString(), const QString &dir=QString(), Options options=ShowDirsOnly)
static QStringList getOpenFileNames (QWidget *parent=nullptr, const QString &caption=QString(), const QString &dir=QString(), const QString &filter=QString(), QString *selectedFilter=nullptr, Options options=Options())
static QString getWorkingDirectory ()
static void setWorkingDirectory (const QString &)
static QString restoreLocation ()
Return the last location where a file save or load dialog was used.
static void saveLocation (const QString &)
Save the last location where a file save or load dialog was used.
Detailed Description
The FileDialog class provides dialogs that allow users to select files or directories.
Author
Werner Mayer
Definition at line 59 of file FileDialog.h.
Constructor & Destructor Documentation
FileDialog()
FileDialog::FileDialog (QWidget * parent = nullptr) explicit
Definition at line 78 of file FileDialog.cpp.
References draftgeoutils.intersections::connect().
~FileDialog()
FileDialog::~FileDialog () override default
Member Function Documentation
accept()
void FileDialog::accept () override
Definition at line 132 of file FileDialog.cpp.
References create_qrc::ext, and DrawingExample::file.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
getExistingDirectory()
QString FileDialog::getExistingDirectory (QWidget * parent = nullptr, const QString & caption = QString(), const QString & dir = QString(), Options options = ShowDirsOnly) static
This is a convenience static function that will return an existing directory selected by the user.
Definition at line 265 of file FileDialog.cpp.
References Init::parent.
Referenced by Gui::StdCmdDownloadOnlineHelp::activated().
getOpenFileName()
QString FileDialog::getOpenFileName (QWidget * parent = nullptr, const QString & caption = QString(), const QString & dir = QString(), const QString & filter = QString(), QString * selectedFilter = nullptr, Options options = Options()) static
This is a convenience static function that returns an existing file selected by the user. If the user pressed Cancel, it returns a null string.
Definition at line 281 of file FileDialog.cpp.
References Gui::DialogOptions::dontUseNativeFileDialog(), DrawingExample::file, getWorkingDirectory(), Init::parent, setWorkingDirectory(), and src.Mod.AddonManager.NetworkManager::urls.
Referenced by CmdSandboxMeshLoader::activated(), PartGui::DlgPartImportIgesImp::onChooseFileName(), PartGui::DlgPartImportStepImp::onChooseFileName(), Gui::Dialog::ParameterGroup::onImportFromFile(), and Gui::PythonConsole::onInsertFileName().
getOpenFileNames()
QStringList FileDialog::getOpenFileNames (QWidget * parent = nullptr, const QString & caption = QString(), const QString & dir = QString(), const QString & filter = QString(), QString * selectedFilter = nullptr, Options options = Options()) static
This is a convenience static function that will return one or more existing files selected by the user.
Definition at line 334 of file FileDialog.cpp.
References Gui::DialogOptions::dontUseNativeFileDialog(), DrawingExample::file, getWorkingDirectory(), Init::parent, setWorkingDirectory(), and src.Mod.AddonManager.NetworkManager::urls.
getSaveFileName()
QString FileDialog::getSaveFileName (QWidget * parent = nullptr, const QString & caption = QString(), const QString & dir = QString(), const QString & filter = QString(), QString * selectedFilter = nullptr, Options options = Options()) static
This is a convenience static function that will return a file name selected by the user. The file does not have to exist.
Definition at line 175 of file FileDialog.cpp.
References Gui::DialogOptions::dontUseNativeFileDialog(), DrawingExample::file, getWorkingDirectory(), Init::parent, setWorkingDirectory(), and src.Mod.AddonManager.NetworkManager::urls.
Referenced by StdCmdExportDependencyGraph::activated(), SpreadsheetGui::ViewProviderSheet::exportAsFile(), Gui::Dialog::ParameterGroup::onExportToFile(), Gui::GraphvizView::onMsg(), Gui::PythonConsole::onSaveHistoryAs(), Gui::GraphvizView::printPdf(), TechDrawGui::MDIViewPage::printPdf(), Gui::EditorView::printPdf(), Gui::MDIView::printPdf(), Gui::View3DInventor::printPdf(), Gui::EditorView::saveAs(), Gui::Document::saveAs(), Gui::Document::saveCopy(), TechDrawGui::MDIViewPage::saveDXF(), TechDrawGui::MDIViewPage::savePDF(), and TechDrawGui::MDIViewPage::saveSVG().
getWorkingDirectory()
QString FileDialog::getWorkingDirectory () static
Return the last directory a file was read from or saved to.
Returns the working directory for the file dialog. This path can be used in combination with getSaveFileName(), getOpenFileName(), getOpenFileNames() or getExistingDirectory() to open the dialog in this path.
Definition at line 392 of file FileDialog.cpp.
Referenced by StdCmdExport::activated(), getOpenFileName(), getOpenFileNames(), and getSaveFileName().
restoreLocation()
QString FileDialog::restoreLocation () static
Return the last location where a file save or load dialog was used.
Returns
QString
Definition at line 421 of file FileDialog.cpp.
References App::Application::Config(), App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
saveLocation()
void FileDialog::saveLocation (const QString & dirName) static
Save the last location where a file save or load dialog was used.
Parameters
dirName
Definition at line 437 of file FileDialog.cpp.
References App::GetApplication(), ParameterGrp::GetGroup(), App::Application::GetUserParameter(), and ParameterGrp::SetASCII().
Referenced by setWorkingDirectory().
setWorkingDirectory()
void FileDialog::setWorkingDirectory (const QString & dir) static
Set the directory a file was read from or saved to.
Sets the working directory to dir for the file dialog. If dir is a file then the path only is taken. getWorkingDirectory() returns the working directory.
Definition at line 402 of file FileDialog.cpp.
References Path.Log::info(), and saveLocation().
Referenced by getOpenFileName(), getOpenFileNames(), getSaveFileName(), Gui::Application::importFrom(), and Gui::Application::open().
The documentation for this class was generated from the following files:
FileDialog.h
FileDialog.cpp