FreeCAD: StdCmdLinkSelectLinked Class Reference
StdCmdLinkSelectLinked Class Reference
Public Member Functions
StdCmdLinkSelectLinked ()
virtual ~ StdCmdLinkSelectLinked ()
virtual const char * className () const
The C++ class name is needed as context for the translation framework.
Public Member Functions inherited from Gui::Command
const char * beginCmdHelp ()
returns the begin of a online help page
const char * endCmdHelp ()
returns the end of a online help page
virtual const char * getHelpUrl () const
Get the help URL.
bool hasActiveDocument () const
true when there is a document
bool hasObject (const char *Name)
true when there is a document and a Feature with Name
const char * getAppModuleName () const
returns the name to which the command belongs
void setAppModuleName (const char *)
const char * getName () const
Get the command name.
const char * getGroupName () const
Get the name of the grouping of the command.
void setGroupName (const char *)
QString translatedGroupName () const
virtual void setShortcut (const QString &)
Override shortcut of this command.
virtual QString getShortcut () const
Obtain the current shortcut of this command.
void testActive ()
Get somtile called to check the state of the command.
void setEnabled (bool)
Enables or disables the command.
TriggerSource triggerSource () const
Return the current command trigger source.
void invoke (int index, TriggerSource trigger=TriggerNone)
void addTo (QWidget *)
adds this command to arbitrary widgets
void addToGroup (ActionGroup *, bool checkable)
void addToGroup (ActionGroup *)
void initAction ()
Create the action if not exist.
void adjustCameraPosition ()
Gui::Document * getActiveGuiDocument () const
Get pointer to the active gui document.
App::Document * getDocument (const char *Name=nullptr) const
bool isViewOfType (Base::Type t) const
checks if the active view is of a special type or derived
App::DocumentObject * getObject (const char *Name) const
returns the named feature or the active one from the active document or NULL
std::string getUniqueObjectName (const char *BaseName, const App::DocumentObject *obj=nullptr) const
void languageChange () override
Translate command.
void updateAction (int mode) override
Updates the QAction with respect to the passed mode.
void setupCheckable (int iMsg)
Setup checkable actions based on current TriggerSource.
const std::string strToPython (const char *Str)
translate a string to a python string literal (needed e.g. in file names for windows...)
const std::string strToPython (const std::string &Str)
Public Member Functions inherited from Gui::CommandBase
Action * getAction () const
virtual const char * getMenuText () const
virtual const char * getToolTipText () const
virtual const char * getStatusTip () const
virtual const char * getWhatsThis () const
virtual const char * getPixmap () const
virtual const char * getAccel () const
void setWhatsThis (const char *)
void setMenuText (const char *)
void setToolTipText (const char *)
void setStatusTip (const char *)
void setPixmap (const char *)
void setAccel (const char *)
Protected Member Functions
virtual void activated (int iMsg)
Methods which gets called when activated, needs to be reimplemented!
virtual bool isActive (void)
Override this method if your Cmd is not always active.
Protected Member Functions inherited from Gui::Command
Command (const char *name)
~Command () override
Action * createAction () override
Creates the used Action.
void applyCommandData (const char *context, Action *)
Applies the menu text, tool and status tip to the passed action object.
const char * keySequenceToAccel (int) const
void printConflictingAccelerators () const
Protected Member Functions inherited from Gui::CommandBase
CommandBase (const char *sMenu, const char *sToolTip=nullptr, const char *sWhat=nullptr, const char *sStatus=nullptr, const char *sPixmap=nullptr, const char *sAccel=nullptr)
virtual ~CommandBase ()
Additional Inherited Members
Public Types inherited from Gui::Command
enum TriggerSource { TriggerNone, TriggerAction, TriggerChildAction }
Command trigger source.
enum DoCmd_Type { Doc, App, Gui }
types of application level actions for DoCommand()
Static Public Member Functions inherited from Gui::Command
static void blockCommand (bool)
Blocks all command objects.
static void printPyCaller ()
Print to Python console the current Python calling source file and line number.
static void printCaller (const char *file, int line)
Print to Python console the current calling source file and line number.
static void _doCommand (const char *file, int line, DoCmd_Type eType, const char *sCmd,...)
Run a App level Action.
static void _runCommand (const char *file, int line, DoCmd_Type eType, const char *sCmd)
Run a App level Action.
static void _runCommand (const char *file, int line, DoCmd_Type eType, const QByteArray &sCmd)
Run a App level Action.
static void addModule (DoCmd_Type eType, const char *sModuleName)
import an external (or own) module only once
static std::string _assureWorkbench (const char *file, int line, const char *sName)
static Application * getGuiApplication ()
Get pointer to the Application Window.
static Gui::SelectionSingleton & getSelection ()
Get a reference to the selection.
static std::string getObjectCmd (const char *Name, const App::Document *doc=nullptr, const char *prefix=nullptr, const char *postfix=nullptr, bool gui=false)
returns a python command string to retrieve an object from a document
static std::string getObjectCmd (const App::DocumentObject *obj, const char *prefix=nullptr, const char *postfix=nullptr, bool gui=false)
returns a python command string to retrieve the given object
static void openCommand (const char *sName=nullptr)
Open a new Undo transaction on the active document.
static void commitCommand ()
Commit the Undo transaction on the active document.
static void abortCommand ()
Abort the Undo transaction on the active document.
static bool hasPendingCommand ()
Check if an Undo transaction is open on the active document.
static void updateActive ()
Updates the (active) document (propagate changes)
static void updateAll (std::list< Gui::Document * > cList)
Updates the (all or listed) documents (propagate changes)
static bool isActiveObjectValid ()
Checks if the active object of the active document is valid.
static void _copyVisual (const char *file, int line, const char *to, const char *attr, const char *from)
static void _copyVisual (const char *file, int line, const char *to, const char *attr_to, const char *from, const char *attr_from)
static void _copyVisual (const char *file, int line, const App::DocumentObject *to, const char *attr, const App::DocumentObject *from)
static void _copyVisual (const char *file, int line, const App::DocumentObject *to, const char *attr_to, const App::DocumentObject *from, const char *attr_from)
static std::string getPythonTuple (const std::string &name, const std::vector< std::string > &subnames)
Get Python tuple from object and sub-elements.
Protected Types inherited from Gui::Command
enum CmdType {
AlterDoc = 1, Alter3DView = 2, AlterSelection = 4, ForEdit = 8,
NoTransaction = 16
}
Protected Attributes inherited from Gui::Command
const char * sAppModule
const char * sGroup
const char * sName
const char * sHelpUrl
int eType
bool bCanLog
Indicate if the command shall log to MacroManager.
Protected Attributes inherited from Gui::CommandBase
const char * sMenuText
const char * sToolTipText
const char * sWhatsThis
const char * sStatusTip
const char * sPixmap
const char * sAccel
Action * _pcAction
std::string displayText
Detailed Description
Definition at line 643 of file CommandLink.cpp.
Constructor & Destructor Documentation
StdCmdLinkSelectLinked()
StdCmdLinkSelectLinked::StdCmdLinkSelectLinked ()
Definition at line 645 of file CommandLink.cpp.
~ StdCmdLinkSelectLinked()
virtual StdCmdLinkSelectLinked::~ StdCmdLinkSelectLinked () inline virtual
Definition at line 643 of file CommandLink.cpp.
Member Function Documentation
activated()
void StdCmdLinkSelectLinked::activated (int iMsg) protected virtual
Methods which gets called when activated, needs to be reimplemented!
Implements Gui::Command.
Definition at line 744 of file CommandLink.cpp.
References Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::clearCompleteSelection(), toolbit-attributes::doc, FC_WARN, Gui::getMainWindow(), getSelectedLink(), Instance, Gui::Selection(), Gui::TreeWidget::selectLinkedObject(), and Gui::SelectionSingleton::selStackPush().
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::set_status_filter().
className()
virtual const char* StdCmdLinkSelectLinked::className () const inline virtual
The C++ class name is needed as context for the translation framework.
Implements Gui::CommandBase.
Definition at line 643 of file CommandLink.cpp.
isActive()
bool StdCmdLinkSelectLinked::isActive (void) protected virtual
Override this method if your Cmd is not always active.
Reimplemented from Gui::Command.
Definition at line 740 of file CommandLink.cpp.
References getSelectedLink().
The documentation for this class was generated from the following file:
CommandLink.cpp