FreeCAD: SketchObject.cpp File Reference
SketchObject.cpp File Reference
#include "PreCompiled.h"
#include <cmath>
#include <vector>
#include <BRepAdaptor_Curve.hxx>
#include <BRepAdaptor_Surface.hxx>
#include <Mod/Part/App/FCBRepAlgoAPI_Section.h>
#include <BRepBuilderAPI_MakeEdge.hxx>
#include <BRepBuilderAPI_MakeFace.hxx>
#include <BRepBuilderAPI_MakeVertex.hxx>
#include <BRepMesh_IncrementalMesh.hxx>
#include <BRepOffsetAPI_NormalProjection.hxx>
#include <BRepTools_WireExplorer.hxx>
#include <BRep_Tool.hxx>
#include <ElCLib.hxx>
#include <GCPnts_AbscissaPoint.hxx>
#include <GC_MakeArcOfCircle.hxx>
#include <GC_MakeCircle.hxx>
#include <GeomAPI_ProjectPointOnCurve.hxx>
#include <GeomAPI_ProjectPointOnSurf.hxx>
#include <GeomConvert_BSplineCurveKnotSplitting.hxx>
#include <GeomLProp_CLProps.hxx>
#include <Geom_BSplineCurve.hxx>
#include <Geom_Circle.hxx>
#include <Geom_Ellipse.hxx>
#include <Geom_Hyperbola.hxx>
#include <Geom_Line.hxx>
#include <Geom_Parabola.hxx>
#include <Geom_Plane.hxx>
#include <Geom_TrimmedCurve.hxx>
#include <Standard_Version.hxx>
#include <TColStd_Array1OfInteger.hxx>
#include <TopExp.hxx>
#include <TopExp_Explorer.hxx>
#include <TopTools_IndexedMapOfShape.hxx>
#include <TopoDS.hxx>
#include <TopoDS_Edge.hxx>
#include <TopoDS_Face.hxx>
#include <TopoDS_Shape.hxx>
#include <gp_Ax3.hxx>
#include <gp_Circ.hxx>
#include <gp_Elips.hxx>
#include <gp_Hypr.hxx>
#include <gp_Parab.hxx>
#include <gp_Pln.hxx>
#include <boost/algorithm/string.hpp>
#include <boost/algorithm/string/predicate.hpp>
#include <boost/geometry/geometries/register/point.hpp>
#include <boost/iostreams/device/array.hpp>
#include <boost/iostreams/stream.hpp>
#include <boost/range/adaptor/map.hpp>
#include <boost_geometry.hpp>
#include <HLRAlgo_Projector.hxx>
#include <HLRBRep_Algo.hxx>
#include <HLRBRep_HLRToShape.hxx>
#include <App/Application.h>
#include <App/Document.h>
#include <App/ElementNamingUtils.h>
#include <App/Expression.h>
#include <App/ExpressionParser.h>
#include <App/FeaturePythonPyImp.h>
#include <App/IndexedName.h>
#include <App/MappedName.h>
#include <App/ObjectIdentifier.h>
#include <App/Datums.h>
#include <App/Part.h>
#include <Base/Console.h>
#include <Base/Reader.h>
#include <Base/Tools.h>
#include <Base/Vector3D.h>
#include <Base/Writer.h>
#include <Mod/Part/App/BodyBase.h>
#include <Mod/Part/App/PartPyCXX.h>
#include <Mod/Part/App/DatumFeature.h>
#include <Mod/Part/App/GeometryMigrationExtension.h>
#include <Mod/Part/App/TopoShapeOpCode.h>
#include <Mod/Part/App/WireJoiner.h>
#include <memory>
#include "SketchObject.h"
#include "SketchObjectPy.h"
#include "SolverGeometryExtension.h"
#include "ExternalGeometryFacade.h"
Classes
class Sketcher::SketchObject::GeoHistory
Namespaces
App
a class to assist with exporting sketches to dxf
Functions
static bool checkSmallEdge (const Part::TopoShape &s)
static const char * hasSketchMarker (const char *name)
static Part::Geometry * fitArcs (std::vector< std::unique_ptr< Part::Geometry > > &arcs, const gp_Pnt &P1, const gp_Pnt &P2, double tol)
static bool checkMigration (Part::PropertyGeometryList &prop)
Function Documentation
checkMigration()
static bool checkMigration (Part::PropertyGeometryList & prop) inline static
Definition at line 10143 of file SketchObject.cpp.
References toolbit-attributes::g, Base::BaseClass::getClassTypeId(), and Part::PropertyGeometryList::getValues().
Referenced by Sketcher::SketchObject::onChanged().
checkSmallEdge()
static bool checkSmallEdge (const Part::TopoShape & s) inline static
Definition at line 317 of file SketchObject.cpp.
References FreeCADInit::Length, and toolbit-attributes::s.
Referenced by Sketcher::SketchObject::buildShape().
fitArcs()
static Part::Geometry* fitArcs (std::vector< std::unique_ptr< Part::Geometry > > & arcs, const gp_Pnt & P1, const gp_Pnt & P2, double tol) static
Definition at line 8207 of file SketchObject.cpp.
References KDL::abs(), exportCSG::center(), SCL.SimpleDataTypes::f, Handle(), RobotExample::l, and test::m.
Referenced by Sketcher::SketchObject::rebuildExternalGeometry().
hasSketchMarker()
static const char* hasSketchMarker (const char * name) static
Definition at line 473 of file SketchObject.cpp.
References Data::ComplexGeoData::elementMapPrefix(), and Part::OpCodes::Sketch.
Referenced by Sketcher::SketchObject::getElementName().