FreeCAD: Gui::SoGLRenderActionElement Class Reference
Gui::SoGLRenderActionElement Class Reference
#include <SoFCInteractiveElement.h>
Public Member Functions
void init (SoState *state) override
void push (SoState *state) override
void pop (SoState *state, const SoElement *prevTopElement) override
SbBool matches (const SoElement *element) const override
SoElement * copyMatchInfo () const override
Static Public Member Functions
static void initClass ()
static void set (SoState *state, SoGLRenderAction *action)
static void get (SoState *state, SoGLRenderAction *&action)
Protected Member Functions
~SoGLRenderActionElement () override
Protected Attributes
SoGLRenderAction * glRenderAction
Detailed Description
Definition at line 106 of file SoFCInteractiveElement.h.
Constructor & Destructor Documentation
~SoGLRenderActionElement()
SoGLRenderActionElement::~SoGLRenderActionElement () override protected default
Member Function Documentation
copyMatchInfo()
SoElement * SoGLRenderActionElement::copyMatchInfo () const override
Definition at line 171 of file SoFCInteractiveElement.cpp.
get()
void SoGLRenderActionElement::get (SoState * state, SoGLRenderAction *& action) static
Definition at line 149 of file SoFCInteractiveElement.cpp.
References Path.Post.scripts.dynapath_4060_post::action.
Referenced by draftguitools.gui_trackers.editTracker::move(), and Gui::SoFCSelection::redrawHighlighted().
init()
void SoGLRenderActionElement::init (SoState * state) override
Definition at line 134 of file SoFCInteractiveElement.cpp.
References glRenderAction, and SIM::Coin3D::Quarter::Quarter::init().
Referenced by DocumentObject.DocumentObject::onChanged().
initClass()
void SoGLRenderActionElement::initClass () static
Definition at line 127 of file SoFCInteractiveElement.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
matches()
SbBool SoGLRenderActionElement::matches (const SoElement * element) const override
Definition at line 166 of file SoFCInteractiveElement.cpp.
pop()
void SoGLRenderActionElement::pop (SoState * state, const SoElement * prevTopElement) override
Definition at line 161 of file SoFCInteractiveElement.cpp.
push()
void SoGLRenderActionElement::push (SoState * state) override
Definition at line 156 of file SoFCInteractiveElement.cpp.
set()
void SoGLRenderActionElement::set (SoState * state, SoGLRenderAction * action) static
Definition at line 142 of file SoFCInteractiveElement.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and glRenderAction.
Referenced by draftguitools.gui_trackers.editTracker::move(), and Gui::View3DInventorViewer::renderScene().
Member Data Documentation
glRenderAction
SoGLRenderAction* Gui::SoGLRenderActionElement::glRenderAction protected
Definition at line 128 of file SoFCInteractiveElement.h.
Referenced by init(), and set().
The documentation for this class was generated from the following files:
SoFCInteractiveElement.h
SoFCInteractiveElement.cpp