FreeCAD: SIM::Coin3D::Quarter::QuarterWidget Class Reference
SIM::Coin3D::Quarter::QuarterWidget Class Reference
The QuarterWidget class is the main class in Quarter. It provides a widget for Coin rendering. It provides scenegraph management and event handling.
#include <Quarter/QuarterWidget.h>
Public Types
enum TransparencyType {
SCREEN_DOOR = SoGLRenderAction::SCREEN_DOOR, ADD = SoGLRenderAction::ADD, DELAYED_ADD = SoGLRenderAction::DELAYED_ADD, SORTED_OBJECT_ADD = SoGLRenderAction::SORTED_OBJECT_ADD,
BLEND = SoGLRenderAction::BLEND, DELAYED_BLEND = SoGLRenderAction::DELAYED_BLEND, SORTED_OBJECT_BLEND = SoGLRenderAction::SORTED_OBJECT_BLEND, SORTED_OBJECT_SORTED_TRIANGLE_ADD = SoGLRenderAction::SORTED_OBJECT_SORTED_TRIANGLE_ADD,
SORTED_OBJECT_SORTED_TRIANGLE_BLEND = SoGLRenderAction::SORTED_OBJECT_SORTED_TRIANGLE_BLEND, NONE = SoGLRenderAction::NONE, SORTED_LAYERS_BLEND = SoGLRenderAction::SORTED_LAYERS_BLEND
}
enum RenderMode {
AS_IS = SoRenderManager::AS_IS, WIREFRAME = SoRenderManager::WIREFRAME, WIREFRAME_OVERLAY = SoRenderManager::WIREFRAME_OVERLAY, POINTS = SoRenderManager::POINTS,
HIDDEN_LINE = SoRenderManager::HIDDEN_LINE, BOUNDING_BOX = SoRenderManager::BOUNDING_BOX
}
enum StereoMode {
MONO = SoRenderManager::MONO, ANAGLYPH = SoRenderManager::ANAGLYPH, QUAD_BUFFER = SoRenderManager::QUAD_BUFFER, INTERLEAVED_ROWS = SoRenderManager::INTERLEAVED_ROWS,
INTERLEAVED_COLUMNS = SoRenderManager::INTERLEAVED_COLUMNS
}
Public Slots
virtual void viewAll ()
virtual void seek ()
void redraw ()
void setRenderMode (SIM::Coin3D::Quarter::QuarterWidget::RenderMode mode)
void setStereoMode (SIM::Coin3D::Quarter::QuarterWidget::StereoMode mode)
void setTransparencyType (SIM::Coin3D::Quarter::QuarterWidget::TransparencyType type)
Signals
void devicePixelRatioChanged (qreal dev_pixel_ratio)
Public Member Functions
QuarterWidget (QWidget *parent=nullptr, const QtGLWidget *sharewidget=nullptr, Qt::WindowFlags f=Qt::WindowFlags())
QuarterWidget (QtGLContext *context, QWidget *parent=nullptr, const QtGLWidget *sharewidget=nullptr, Qt::WindowFlags f=Qt::WindowFlags())
QuarterWidget (const QtGLFormat &format, QWidget *parent=nullptr, const QtGLWidget *shareWidget=nullptr, Qt::WindowFlags f=Qt::WindowFlags())
~QuarterWidget () override
TransparencyType transparencyType () const
RenderMode renderMode () const
StereoMode stereoMode () const
void setBackgroundColor (const QColor &color)
QColor backgroundColor () const
qreal devicePixelRatio () const
void resetNavigationModeFile ()
void setNavigationModeFile (const QUrl &url=QUrl(QString::fromLatin1(DEFAULT_NAVIGATIONFILE)))
const QUrl & navigationModeFile () const
void setupDefaultCursors ()
void setContextMenuEnabled (bool yes)
bool contextMenuEnabled () const
QMenu * getContextMenu () const
bool headlightEnabled () const
void setHeadlightEnabled (bool onoff)
SoDirectionalLight * getHeadlight () const
bool clearZBuffer () const
void setClearZBuffer (bool onoff)
bool clearWindow () const
void setClearWindow (bool onoff)
bool interactionModeEnabled () const
void setInteractionModeEnabled (bool onoff)
bool interactionModeOn () const
void setInteractionModeOn (bool onoff)
void setStateCursor (const SbName &state, const QCursor &cursor)
QCursor stateCursor (const SbName &state)
uint32_t getCacheContextId () const
virtual void setSceneGraph (SoNode *root)
virtual SoNode * getSceneGraph () const
void setSoEventManager (SoEventManager *manager)
SoEventManager * getSoEventManager () const
void setSoRenderManager (SoRenderManager *manager)
SoRenderManager * getSoRenderManager () const
EventFilter * getEventFilter () const
void addStateMachine (SoScXMLStateMachine *statemachine)
void removeStateMachine (SoScXMLStateMachine *statemachine)
virtual bool processSoEvent (const SoEvent *event)
QSize minimumSizeHint () const override
QList< QAction * > transparencyTypeActions () const
QList< QAction * > stereoModeActions () const
QList< QAction * > renderModeActions () const
Protected Member Functions
void paintEvent (QPaintEvent *) override
void resizeEvent (QResizeEvent *) override
bool viewportEvent (QEvent *event) override
virtual void actualRedraw ()
virtual bool updateDevicePixelRatio ()
Properties
QUrl navigationModeFile
QColor backgroundColor
bool contextMenuEnabled
bool headlightEnabled
bool clearZBuffer
bool clearWindow
bool interactionModeEnabled
bool interactionModeOn
TransparencyType transparencyType
RenderMode renderMode
StereoMode stereoMode
qreal devicePixelRatio
Friends
class QuarterWidgetP
Detailed Description
The QuarterWidget class is the main class in Quarter. It provides a widget for Coin rendering. It provides scenegraph management and event handling.
If you want to modify the GL format for an existing QuarterWidget, you can set up a new GL context for the widget, e.g.:
QGLContext * context = new QGLContext(QGLFormat(QGL::SampleBuffers), viewer);
if (context->create()) {
  viewer->setContext(context);
}
Definition at line 61 of file QuarterWidget.h.
Member Enumeration Documentation
RenderMode
enum SIM::Coin3D::Quarter::QuarterWidget::RenderMode
Sets how rendering of primitives is done.
See SoRenderManager::RenderMode for a full description of the modes
Enumerator
AS_IS
WIREFRAME
WIREFRAME_OVERLAY
POINTS
HIDDEN_LINE
BOUNDING_BOX
Definition at line 80 of file QuarterWidget.h.
StereoMode
enum SIM::Coin3D::Quarter::QuarterWidget::StereoMode
Sets how stereo rendering is performed.
See SoRenderManager::StereoMode for a full description of the modes
Enumerator
MONO
ANAGLYPH
QUAD_BUFFER
INTERLEAVED_ROWS
INTERLEAVED_COLUMNS
Definition at line 89 of file QuarterWidget.h.
TransparencyType
enum SIM::Coin3D::Quarter::QuarterWidget::TransparencyType
Various settings for how to do rendering of transparent objects in the scene. Some of the settings will provide faster rendering, while others gives you better quality rendering.
See SoGLRenderAction::TransparencyType for a full description of the modes
Enumerator
SCREEN_DOOR
ADD
DELAYED_ADD
SORTED_OBJECT_ADD
BLEND
DELAYED_BLEND
SORTED_OBJECT_BLEND
SORTED_OBJECT_SORTED_TRIANGLE_ADD
SORTED_OBJECT_SORTED_TRIANGLE_BLEND
NONE
SORTED_LAYERS_BLEND
Definition at line 66 of file QuarterWidget.h.
Constructor & Destructor Documentation
QuarterWidget() [1/3]
QuarterWidget::QuarterWidget (QWidget * parent = nullptr, const QtGLWidget * sharewidget = nullptr, Qt::WindowFlags f = Qt::WindowFlags()) explicit
constructor
Definition at line 241 of file QuarterWidget.cpp.
References SCL.SimpleDataTypes::f.
QuarterWidget() [2/3]
QuarterWidget::QuarterWidget (QtGLContext * context, QWidget * parent = nullptr, const QtGLWidget * sharewidget = nullptr, Qt::WindowFlags f = Qt::WindowFlags()) explicit
constructor
Definition at line 249 of file QuarterWidget.cpp.
References SCL.SimpleDataTypes::f.
QuarterWidget() [3/3]
QuarterWidget::QuarterWidget (const QtGLFormat & format, QWidget * parent = nullptr, const QtGLWidget * sharewidget = nullptr, Qt::WindowFlags f = Qt::WindowFlags()) explicit
constructor
Definition at line 233 of file QuarterWidget.cpp.
References SCL.SimpleDataTypes::f.
~QuarterWidget()
QuarterWidget::~QuarterWidget () override
destructor
Definition at line 324 of file QuarterWidget.cpp.
References PRIVATE, removeStateMachine(), setSceneGraph(), setSoEventManager(), and setSoRenderManager().
Member Function Documentation
actualRedraw()
void QuarterWidget::actualRedraw () protected virtual
Overridden from QGLWidget to render the scenegraph
Reimplemented in Gui::View3DInventorViewer.
Definition at line 990 of file QuarterWidget.cpp.
References PRIVATE.
Referenced by paintEvent(), and Gui::View3DInventorViewer::renderScene().
addStateMachine()
void QuarterWidget::addStateMachine (SoScXMLStateMachine * statemachine)
Convenience method that adds a state machine to the current SoEventManager. It also initializes the scene graph root and active camera for the state machine, and finally it sets up the default Quarter cursor handling.
See also
removeStateMachine
Definition at line 1096 of file QuarterWidget.cpp.
References OfflineRenderingUtils::getCamera(), getSceneGraph(), getSoEventManager(), getSoRenderManager(), PRIVATE, and SIM::Coin3D::Quarter::QuarterWidgetP::statechangecb().
Referenced by setNavigationModeFile().
backgroundColor()
QColor SIM::Coin3D::Quarter::QuarterWidget::backgroundColor () const
clearWindow()
bool SIM::Coin3D::Quarter::QuarterWidget::clearWindow () const
clearZBuffer()
bool SIM::Coin3D::Quarter::QuarterWidget::clearZBuffer () const
contextMenuEnabled()
bool SIM::Coin3D::Quarter::QuarterWidget::contextMenuEnabled () const
devicePixelRatio()
qreal SIM::Coin3D::Quarter::QuarterWidget::devicePixelRatio () const
devicePixelRatioChanged
void SIM::Coin3D::Quarter::QuarterWidget::devicePixelRatioChanged (qreal dev_pixel_ratio) signal
Referenced by Gui::View3DInventorViewer::init(), MeshGui::MeshSelection::prepareFreehandSelection(), and updateDevicePixelRatio().
getCacheContextId()
uint32_t QuarterWidget::getCacheContextId () const
Returns the Coin cache context id for this widget.
Definition at line 503 of file QuarterWidget.cpp.
References PRIVATE.
getContextMenu()
QMenu * QuarterWidget::getContextMenu () const
Returns the context menu used by the widget.
Definition at line 1056 of file QuarterWidget.cpp.
References PRIVATE.
getEventFilter()
EventFilter * QuarterWidget::getEventFilter () const
Returns a pointer to the event filter
Definition at line 756 of file QuarterWidget.cpp.
References PRIVATE.
Referenced by Gui::View3DInventorViewer::init().
getHeadlight()
SoDirectionalLight * QuarterWidget::getHeadlight () const
Returns the light used for the headlight.
Definition at line 394 of file QuarterWidget.cpp.
References PRIVATE.
Referenced by Gui::View3DInventorViewer::init(), and Gui::View3DInventorViewer::savePicture().
getSceneGraph()
SoNode * QuarterWidget::getSceneGraph () const virtual
Returns pointer to root of scene graph
Definition at line 657 of file QuarterWidget.cpp.
References PRIVATE.
Referenced by addStateMachine(), MatGui::AppearancePreview::AppearancePreview(), Gui::View3DInventorViewer::containsViewProvider(), Gui::View3DInventor::dump(), Gui::NavigationStyle::findBoundingSphere(), Gui::View3DInventorViewer::getBoundingBox(), Gui::View3DInventorViewer::getPointOnRay(), Gui::View3DInventorViewerPy::getSceneGraph(), Gui::View3DInventorPy::getSceneGraph(), Gui::View3DInventorViewer::isSelectionEnabled(), Gui::View3DInventor::onRename(), Gui::View3DInventorViewer::pickPoint(), Gui::View3DInventorViewer::renderToFramebuffer(), Gui::View3DInventorViewer::searchNode(), Gui::View3DInventorViewer::setAxisCross(), Gui::NavigationStyle::setCameraOrientation(), Gui::View3DInventorViewer::setSelectionEnabled(), Gui::View3DInventorViewer::showRotationCenter(), Gui::NavigationStyle::viewAll(), and Gui::View3DInventorViewer::viewAll().
getSoEventManager()
SoEventManager * QuarterWidget::getSoEventManager () const
Returns a pointer to the event manager
Definition at line 747 of file QuarterWidget.cpp.
References PRIVATE.
Referenced by addStateMachine(), Gui::View3DInventorViewerPy::getSoEventManager(), SIM::Coin3D::Quarter::InteractionMode::InteractionMode(), removeStateMachine(), Gui::View3DInventorViewer::resetEditingViewProvider(), and SIM::Coin3D::Quarter::InteractionMode::setOn().
getSoRenderManager()
SoRenderManager * QuarterWidget::getSoRenderManager () const
Returns a pointer to the render manager.
Definition at line 702 of file QuarterWidget.cpp.
References PRIVATE.
Referenced by Gui::GLFlagWindow::addFlag(), addStateMachine(), Gui::AlignmentView::AlignmentView(), Gui::View3DInventorViewer::animatedViewAll(), Gui::NavigationStyle::boxZoom(), SIM::Coin3D::Quarter::ContextMenu::changeRenderMode(), SIM::Coin3D::Quarter::ContextMenu::changeStereoMode(), SIM::Coin3D::Quarter::ContextMenu::changeTransparencyType(), Gui::View3DInventorViewer::containsViewProvider(), SIM::Coin3D::Quarter::ContextMenu::ContextMenu(), PointsGui::ViewProviderScattered::cut(), PointsGui::ViewProviderStructured::cut(), FemGui::TaskCreateElementSet::DefineElementsCallback(), FemGui::TaskCreateNodeSet::DefineNodesCallback(), Gui::GLFlagWindow::deleteFlags(), Gui::NavigationStyle::doRotate(), Gui::NavigationStyle::doSpin(), Gui::NavigationStyle::doZoom(), SandboxGui::DrawingPlane::draw(), Gui::NavigationStyle::findBoundingSphere(), Gui::View3DInventorViewer::fromQPoint(), Gui::View3DInventorViewer::getBoundingBox(), Gui::View3DInventorPy::getCamera(), Gui::View3DInventorPy::getCameraNode(), Gui::View3DInventorViewer::getCameraOrientation(), Gui::View3DInventorPy::getCameraType(), Gui::View3DInventorViewer::getCenterPointOnFocalPlane(), Gui::View3DInventorViewer::getDimensions(), Gui::View3DInventorViewer::getFarPlane(), Gui::View3DInventorViewerPy::getFocalDistance(), Gui::NavigationStyle::getFocalPoint(), Gui::View3DInventorViewer::getGLPolygon(), Gui::View3DInventorViewer::getNearPlane(), Gui::View3DInventorViewer::getNormalizedPosition(), Gui::View3DInventorViewer::getPointOnFocalPlane(), Gui::View3DInventorViewer::getPointOnLine(), Gui::View3DInventorViewer::getPointOnRay(), Gui::View3DInventorViewer::getPointOnViewport(), Gui::View3DInventorViewer::getPointOnXYPlaneOfPlacement(), getSelectedNodes(), Gui::View3DInventorPy::getSize(), Gui::View3DInventorViewerPy::getSoRenderManager(), Gui::View3DInventorViewer::getUpDirection(), Gui::View3DInventorViewer::getViewDirection(), Gui::View3DInventorViewer::getViewportOnXYPlaneOfPlacement(), Gui::View3DInventorViewer::grabFramebuffer(), Gui::NavigationStyle::handleEventInForeground(), Gui::View3DInventorViewer::init(), InspectionGui::ViewProviderInspection::inspectCallback(), Gui::GestureNavigationStyle::isDraggerUnderCursor(), Gui::NavigationStyle::lookAtPoint(), MyPaintable::MyPaintable(), Gui::NavigationStyle::normalizePixelPos(), Gui::Dialog::DemoMode::onAngleSliderValueChanged(), Gui::View3DInventor::onMsg(), Gui::Dialog::DemoMode::onPlayButtonToggled(), paintEvent(), MyPaintable::paintGL(), Gui::Rubberband::paintGL(), Gui::Polyline::paintGL(), Gui::GLFlagWindow::paintGL(), Teapots::paintGL(), Rubberband::paintGL(), Gui::View3DInventorViewer::pickPoint(), Gui::NavigationStyle::processEvent(), Gui::NavigationStyle::processKeyboardEvent(), Gui::NavigationStyle::processMotionEvent(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), Gui::TinkerCADNavigationStyle::processSoEvent(), Gui::NavigationStyle::processWheelEvent(), Gui::View3DInventorViewer::projectOnFarPlane(), Gui::View3DInventorViewer::projectOnNearPlane(), Gui::View3DInventorViewer::projectPointToLine(), Gui::GLFlagWindow::removeFlag(), Gui::View3DInventorViewer::renderFramebuffer(), Gui::View3DInventorViewer::renderGLImage(), Gui::View3DInventorViewer::renderScene(), Gui::View3DInventorViewer::renderToFramebuffer(), Teapots::resizeGL(), Gui::NavigationStyle::saveCursorPosition(), Gui::View3DInventorViewer::saveGraphic(), Gui::View3DInventorPy::saveImage(), Gui::View3DInventorViewer::savePicture(), Gui::View3DInventorViewer::screenCoordsOfPath(), Gui::View3DInventor::setCamera(), Gui::NavigationStyle::setCameraOrientation(), Gui::View3DInventorViewer::setCameraType(), Gui::View3DInventorViewer::setFeedbackSize(), Gui::View3DInventorViewer::setFeedbackVisibility(), Gui::View3DInventorViewerPy::setFocalDistance(), Gui::View3DInventorViewer::setOverrideMode(), Gui::View3DInventorViewer::setRenderType(), Gui::View3DInventorViewer::setSceneGraph(), Gui::View3DInventorViewer::setViewDirection(), Gui::NavigationStyle::setViewingMode(), Gui::NavigationStyle::spin(), Gui::NavigationStyle::spin_simplified(), Teapots::Teapots(), SandboxGui::DrawingPlane::terminate(), Gui::View3DInventorViewer::toQPoint(), Gui::View3DInventorViewer::updateOverrideMode(), Gui::NavigationStyle::viewAll(), Gui::View3DInventorViewer::viewAll(), Gui::View3DInventorPy::viewPosition(), Gui::View3DInventorPy::viewRotateLeft(), Gui::View3DInventorPy::viewRotateRight(), Gui::View3DInventorViewer::viewSelection(), Gui::NavigationStyle::zoomByCursor(), Gui::NavigationStyle::zoomIn(), Gui::NavigationStyle::zoomOut(), Gui::View3DInventor::~View3DInventor(), and Gui::View3DInventorViewer::~View3DInventorViewer().
headlightEnabled()
bool SIM::Coin3D::Quarter::QuarterWidget::headlightEnabled () const
interactionModeEnabled()
bool SIM::Coin3D::Quarter::QuarterWidget::interactionModeEnabled () const
interactionModeOn()
bool SIM::Coin3D::Quarter::QuarterWidget::interactionModeOn () const
minimumSizeHint()
QSize QuarterWidget::minimumSizeHint () const override
See QWidget::minimumSizeHint
Definition at line 1124 of file QuarterWidget.cpp.
navigationModeFile()
const QUrl& SIM::Coin3D::Quarter::QuarterWidget::navigationModeFile () const
paintEvent()
void QuarterWidget::paintEvent (QPaintEvent * event) override protected
Overridden from QGLWidget to render the scenegraph
Definition at line 839 of file QuarterWidget.cpp.
References actualRedraw(), devicePixelRatio, getSoRenderManager(), GL_MULTISAMPLE_BIT_EXT, glMatrixMode, PRIVATE, updateDevicePixelRatio(), and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by SIM::Coin3D::Quarter::SoQTQuarterAdaptor::paintEvent().
processSoEvent()
bool QuarterWidget::processSoEvent (const SoEvent * event) virtual
Passes an event to the event manager.
Parameters
[in] event to pass
Return values
Returns true if the event was successfully processed
Reimplemented in SIM::Coin3D::Quarter::SoQTQuarterAdaptor, and Gui::View3DInventorViewer.
Definition at line 1004 of file QuarterWidget.cpp.
References PRIVATE.
Referenced by SIM::Coin3D::Quarter::SoQTQuarterAdaptor::processSoEvent().
redraw
void QuarterWidget::redraw () slot
Used for rendering the scene. Usually Coin/Quarter will automatically redraw the scene graph at regular intervals, after the scene is modified.
However, if you want to disable this functionality and gain full control over when the scene is rendered yourself, you can turn off autoredraw in the render manager and render the scene by calling this method.
Definition at line 963 of file QuarterWidget.cpp.
References PRIVATE.
Referenced by PointsGui::ViewProviderPoints::clipPointsCallback(), Gui::PolyPickerSelection::draw(), Gui::RubberbandSelection::draw(), Gui::PolyPickerSelection::initialize(), Gui::RubberbandSelection::initialize(), Gui::View3DInventor::onUpdate(), CustomGLWidget::paintGL(), Gui::View3DInventorPy::redraw(), SIM::Coin3D::Quarter::QuarterWidgetP::rendercb(), Gui::View3DInventorViewerPy::setBackgroundColor(), Gui::View3DInventorPy::setCornerCrossSize(), Gui::View3DInventorPy::setCornerCrossVisible(), Gui::View3DInventorViewerPy::setGradientBackground(), Gui::View3DInventorViewerPy::setGradientBackgroundColor(), Gui::PolyPickerSelection::terminate(), Gui::RubberbandSelection::terminate(), and draftguitools.gui_trimex.Trimex::trimObject().
removeStateMachine()
void QuarterWidget::removeStateMachine (SoScXMLStateMachine * statemachine)
Convenience method that removes a state machine from the current SoEventManager.
See also
addStateMachine
Definition at line 1112 of file QuarterWidget.cpp.
References getSoEventManager().
Referenced by setNavigationModeFile(), and ~QuarterWidget().
renderMode()
RenderMode SIM::Coin3D::Quarter::QuarterWidget::renderMode () const
renderModeActions()
QList< QAction * > QuarterWidget::renderModeActions () const
Returns a list of grouped actions that corresponds to the RenderMode enum. If you want to create a menu in your application that controls the render mode type used in QuarterWidget, add these actions to the menu.
Definition at line 1157 of file QuarterWidget.cpp.
References PRIVATE.
Referenced by SIM::Coin3D::Quarter::ContextMenu::ContextMenu().
resetNavigationModeFile()
void QuarterWidget::resetNavigationModeFile ()
Removes any navigationModeFile set.
Definition at line 1179 of file QuarterWidget.cpp.
References setNavigationModeFile().
resizeEvent()
void QuarterWidget::resizeEvent (QResizeEvent * event) override protected
Overridden from QGLWidget to resize the Coin scenegraph
Definition at line 821 of file QuarterWidget.cpp.
References devicePixelRatio, PRIVATE, and updateDevicePixelRatio().
seek
void QuarterWidget::seek () virtual slot
Sets the current camera in seek mode, if supported by the underlying navigation system. Camera typically seeks towards what the mouse is pointing at.
Definition at line 783 of file QuarterWidget.cpp.
References SCL.SimpleDataTypes::c, and PRIVATE.
Referenced by SIM::Coin3D::Quarter::ContextMenu::ContextMenu().
setBackgroundColor()
void QuarterWidget::setBackgroundColor (const QColor & color)
Set background color to a given QColor
Remember that QColors are given in integers between 0 and 255, as opposed to SbColor4f which is in [0, 1]. The default alpha value for a QColor is 255, but you'll probably want to set it to zero before using it as an OpenGL clear color.
Definition at line 1026 of file QuarterWidget.cpp.
References PRIVATE.
Referenced by Gui::View3DInventorViewer::imageFromFramebuffer(), Gui::View3DInventorViewer::init(), and Gui::View3DInventorViewerPy::setBackgroundColor().
setClearWindow()
void QuarterWidget::setClearWindow (bool onoff)
Specify if you want the rendering buffer to be cleared before rendering. This is on by default.
Definition at line 435 of file QuarterWidget.cpp.
References PRIVATE.
Referenced by Gui::View3DInventorViewer::init().
setClearZBuffer()
void QuarterWidget::setClearZBuffer (bool onoff)
Specify if you want the z buffer to be cleared before redraw. This is on by default.
Definition at line 410 of file QuarterWidget.cpp.
References PRIVATE.
setContextMenuEnabled()
void QuarterWidget::setContextMenuEnabled (bool yes)
Controls the display of the context menu
Parameters
[in] yes Context menu on?
Definition at line 1082 of file QuarterWidget.cpp.
References PRIVATE.
setHeadlightEnabled()
void QuarterWidget::setHeadlightEnabled (bool onoff)
Enable/disable the headlight. This will toggle the SoDirectionalLight::on field (returned from getHeadlight()).
Definition at line 376 of file QuarterWidget.cpp.
References PRIVATE.
setInteractionModeEnabled()
void QuarterWidget::setInteractionModeEnabled (bool onoff)
Enable/disable interaction mode.
Specifies whether you may use the alt-key to enter interaction mode.
Definition at line 461 of file QuarterWidget.cpp.
References PRIVATE.
setInteractionModeOn()
void QuarterWidget::setInteractionModeOn (bool onoff)
Turn interaction mode on or off.
Definition at line 485 of file QuarterWidget.cpp.
References PRIVATE.
setNavigationModeFile()
void QuarterWidget::setNavigationModeFile (const QUrl & url = QUrl(QString::fromLatin1(DEFAULT_NAVIGATIONFILE)))
Sets a navigation mode file. Supports the schemes "coin" and "file"
Parameters
[in] url URL to the resource
Definition at line 1204 of file QuarterWidget.cpp.
References addStateMachine(), SIM::Coin3D::Quarter::DEFAULT_NAVIGATIONFILE, DrawingExample::file, navigationModeFile, PRIVATE, readFile(), removeStateMachine(), and setupDefaultCursors().
Referenced by resetNavigationModeFile().
setRenderMode
void QuarterWidget::setRenderMode (SIM::Coin3D::Quarter::QuarterWidget::RenderMode mode) slot
Sets how rendering of primitives is done.
See SoRenderManager::RenderMode for a full description of the modes
Definition at line 546 of file QuarterWidget.cpp.
References PRIVATE.
Referenced by SIM::Coin3D::Quarter::ContextMenu::changeRenderMode().
setSceneGraph()
void QuarterWidget::setSceneGraph (SoNode * node) virtual
Sets the Inventor scenegraph to be rendered
Reimplemented in Gui::View3DInventorViewer, and SIM::Coin3D::Quarter::SoQTQuarterAdaptor.
Definition at line 612 of file QuarterWidget.cpp.
References PRIVATE, and viewAll().
Referenced by SIM::Coin3D::Quarter::DragDropHandlerP::dropEvent(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::setSceneGraph(), and ~QuarterWidget().
setSoEventManager()
void QuarterWidget::setSoEventManager (SoEventManager * manager)
Set the Coin event manager for the widget.
Definition at line 711 of file QuarterWidget.cpp.
References PRIVATE.
Referenced by ~QuarterWidget().
setSoRenderManager()
void QuarterWidget::setSoRenderManager (SoRenderManager * manager)
Set the render manager for the widget.
Definition at line 666 of file QuarterWidget.cpp.
References PRIVATE.
Referenced by ~QuarterWidget().
setStateCursor()
void QuarterWidget::setStateCursor (const SbName & state, const QCursor & cursor)
You can set the cursor you want to use for a given navigation state. See the Coin documentation on navigation for information about available states
Definition at line 345 of file QuarterWidget.cpp.
References SIM::Coin3D::Quarter::QuarterP::statecursormap.
Referenced by setupDefaultCursors().
setStereoMode
void QuarterWidget::setStereoMode (SIM::Coin3D::Quarter::QuarterWidget::StereoMode mode) slot
Sets how stereo rendering is performed.
See SoRenderManager::StereoMode for a full description of the modes
Definition at line 573 of file QuarterWidget.cpp.
References PRIVATE.
Referenced by SIM::Coin3D::Quarter::ContextMenu::changeStereoMode(), Gui::View3DInventor::onMsg(), and Gui::View3DInventorPy::setStereoType().
setTransparencyType
void QuarterWidget::setTransparencyType (SIM::Coin3D::Quarter::QuarterWidget::TransparencyType type) slot
Sets the transparency type to be used for the scene.
Definition at line 518 of file QuarterWidget.cpp.
References PRIVATE, and Path.Post.scripts.grbl_post::type.
Referenced by SIM::Coin3D::Quarter::ContextMenu::changeTransparencyType().
setupDefaultCursors()
void QuarterWidget::setupDefaultCursors ()
Sets up the default cursors for the widget.
Definition at line 1186 of file QuarterWidget.cpp.
References setStateCursor().
Referenced by setNavigationModeFile().
stateCursor()
QCursor QuarterWidget::stateCursor (const SbName & state)
Maps a state to a cursor
Parameters
[in] state Named state in the statemachine
Return values
Cursor corresponding to the given state
Definition at line 359 of file QuarterWidget.cpp.
References SIM::Coin3D::Quarter::QuarterP::statecursormap.
Referenced by SIM::Coin3D::Quarter::InteractionMode::setOn().
stereoMode()
StereoMode SIM::Coin3D::Quarter::QuarterWidget::stereoMode () const
stereoModeActions()
QList< QAction * > QuarterWidget::stereoModeActions () const
Returns a list of grouped actions that corresponds to the StereoMode enum. If you want to create a menu in your application that controls the stereo mode used in QuarterWidget, add these actions to the menu.
Definition at line 1146 of file QuarterWidget.cpp.
References PRIVATE.
Referenced by SIM::Coin3D::Quarter::ContextMenu::ContextMenu().
transparencyType()
TransparencyType SIM::Coin3D::Quarter::QuarterWidget::transparencyType () const
transparencyTypeActions()
QList< QAction * > QuarterWidget::transparencyTypeActions () const
Returns a list of grouped actions that corresponds to the TransparencyType enum. If you want to create a menu in your application that controls the transparency type used in QuarterWidget, add these actions to the menu.
Definition at line 1135 of file QuarterWidget.cpp.
References PRIVATE.
Referenced by SIM::Coin3D::Quarter::ContextMenu::ContextMenu().
updateDevicePixelRatio()
bool QuarterWidget::updateDevicePixelRatio () protected virtual
Definition at line 797 of file QuarterWidget.cpp.
References devicePixelRatio, devicePixelRatioChanged(), and PRIVATE.
Referenced by paintEvent(), and resizeEvent().
viewAll
void QuarterWidget::viewAll () virtual slot
Reposition the current camera to display the entire scene
Reimplemented in Gui::View3DInventorViewer.
Definition at line 765 of file QuarterWidget.cpp.
References SCL.SimpleDataTypes::c, and PRIVATE.
Referenced by SIM::Coin3D::Quarter::ContextMenu::ContextMenu(), and setSceneGraph().
viewportEvent()
bool QuarterWidget::viewportEvent (QEvent * event) override protected
Definition at line 913 of file QuarterWidget.cpp.
References RobotExample::pos, and wheel().
Friends And Related Function Documentation
QuarterWidgetP
friend class QuarterWidgetP friend
Definition at line 207 of file QuarterWidget.h.
Property Documentation
backgroundColor
QColor QuarterWidget::backgroundColor read write
Set background color to a given QColor
Remember that QColors are given in integers between 0 and 255, as opposed to SbColor4f which is in [0, 1]. The default alpha value for a QColor is 255, but you'll probably want to set it to zero before using it as an OpenGL clear color.
Returns color used for clearing the rendering area before rendering the scene.
Definition at line 98 of file QuarterWidget.h.
Referenced by Gui::View3DInventorViewer::imageFromFramebuffer(), Gui::View3DInventorViewer::renderScene(), Gui::View3DInventorViewer::renderToFramebuffer(), Gui::View3DInventorViewer::savePicture(), and Gui::View3DInventorPy::saveVectorGraphic().
clearWindow
bool QuarterWidget::clearWindow read write
Specify if you want the rendering buffer to be cleared before rendering. This is on by default.
Returns true if the rendering buffer is cleared before rendering.
Definition at line 102 of file QuarterWidget.h.
clearZBuffer
bool QuarterWidget::clearZBuffer read write
Specify if you want the z buffer to be cleared before redraw. This is on by default.
Returns true if the z buffer is cleared before rendering.
Definition at line 101 of file QuarterWidget.h.
contextMenuEnabled
QuarterWidget::contextMenuEnabled read write
Return values
Is context menu enabled?
Controls the display of the context menu
Parameters
[in] yes Context menu on?
Definition at line 99 of file QuarterWidget.h.
devicePixelRatio
qreal QuarterWidget::devicePixelRatio read
The ratio between logical and physical pixel sizes – obtained from the window that the widget is located within, and updated whenever any change occurs, emitting a devicePixelRatioChanged signal. Only available for version Qt 5.6 and above (will be 1.0 for all previous versions)
The ratio between logical and physical pixel sizes – obtained from the window that the widget is located within, and updated whenever any change occurs, emitting a devicePixelRatioChanged signal. Only available for version Qt 5.6 and above (will be 1.0 for all previous versions)
Definition at line 109 of file QuarterWidget.h.
Referenced by Gui::View3DInventorViewer::fromQPoint(), Gui::View3DInventorViewer::init(), SIM::Coin3D::Quarter::MouseP::mouseButtonEvent(), SIM::Coin3D::Quarter::MouseP::mouseMoveEvent(), SIM::Coin3D::Quarter::MouseP::mouseWheelEvent(), paintEvent(), Gui::View3DInventorViewer::renderScene(), resizeEvent(), Gui::View3DInventorViewer::toQPoint(), SIM::Coin3D::Quarter::EventFilterP::trackPointerPosition(), and updateDevicePixelRatio().
headlightEnabled
bool QuarterWidget::headlightEnabled read write
Enable/disable the headlight. This will toggle the SoDirectionalLight::on field (returned from getHeadlight()).
Returns true if the headlight is on, false if it is off
Definition at line 100 of file QuarterWidget.h.
interactionModeEnabled
bool QuarterWidget::interactionModeEnabled read write
Enable/disable interaction mode.
Specifies whether you may use the alt-key to enter interaction mode.
Returns true if interaction mode is enabled, false otherwise.
Definition at line 103 of file QuarterWidget.h.
interactionModeOn
bool QuarterWidget::interactionModeOn read write
Turn interaction mode on or off.
Returns true if interaction mode is on.
Definition at line 104 of file QuarterWidget.h.
navigationModeFile
const QUrl & QuarterWidget::navigationModeFile read write
A url pointing to a navigation mode file which is a scxml file that defines the possible states for the Coin navigation system
Supports:
coin for internal Coin resources
file for file system path to resources
See also
scxml
Return values
The current navigation mode file
Definition at line 97 of file QuarterWidget.h.
Referenced by setNavigationModeFile().
renderMode
QuarterWidget::RenderMode QuarterWidget::renderMode read write
Sets how rendering of primitives is done.
See SoRenderManager::RenderMode for a full description of the modes
Return values
The current RenderMode
Definition at line 107 of file QuarterWidget.h.
stereoMode
QuarterWidget::StereoMode QuarterWidget::stereoMode read write
Sets how stereo rendering is performed.
See SoRenderManager::StereoMode for a full description of the modes
Return values
The current StereoMode
Definition at line 108 of file QuarterWidget.h.
transparencyType
QuarterWidget::TransparencyType QuarterWidget::transparencyType read write
Sets the transparency type to be used for the scene.
Return values
The current TransparencyType
Definition at line 106 of file QuarterWidget.h.
The documentation for this class was generated from the following files:
QuarterWidget.h
QuarterWidget.cpp