FreeCAD: AdaptivePath::ClearedArea Class Reference
AdaptivePath::ClearedArea Class Reference
Public Member Functions
ClearedArea (ClipperLib::cInt p_toolRadiusScaled)
void SetClearedPaths (const Paths &paths)
void ExpandCleared (const Path toClearToolPath)
Paths & GetBoundedClearedPaths (const IntPoint &toolPos)
Paths & GetBoundedClearedAreaClipped (const IntPoint &toolPos)
Paths & GetCleared ()
Detailed Description
Definition at line 964 of file Adaptive.cpp.
Constructor & Destructor Documentation
ClearedArea()
AdaptivePath::ClearedArea::ClearedArea (ClipperLib::cInt p_toolRadiusScaled) inline
Definition at line 967 of file Adaptive.cpp.
Member Function Documentation
ExpandCleared()
void AdaptivePath::ClearedArea::ExpandCleared (const Path toClearToolPath) inline
Definition at line 978 of file Adaptive.cpp.
References ClipperLib::CleanPolygons(), AdaptivePath::Perf_ExpandCleared, AdaptivePath::PerfCounter::Start(), and AdaptivePath::PerfCounter::Stop().
GetBoundedClearedAreaClipped()
Paths& AdaptivePath::ClearedArea::GetBoundedClearedAreaClipped (const IntPoint & toolPos) inline
Definition at line 1044 of file Adaptive.cpp.
GetBoundedClearedPaths()
Paths& AdaptivePath::ClearedArea::GetBoundedClearedPaths (const IntPoint & toolPos) inline
Definition at line 999 of file Adaptive.cpp.
References AdaptivePath::BoundBox::CollidesWith(), and SplineSurface::i.
GetCleared()
Paths& AdaptivePath::ClearedArea::GetCleared () inline
Definition at line 1070 of file Adaptive.cpp.
SetClearedPaths()
void AdaptivePath::ClearedArea::SetClearedPaths (const Paths & paths) inline
Definition at line 972 of file Adaptive.cpp.
The documentation for this class was generated from the following file:
Adaptive.cpp