FreeCAD: App::DocumentObserver Class Reference
App::DocumentObserver Class Reference
#include <DocumentObserver.h>
Public Member Functions
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
void attachDocument (Document *)
void detachDocument ()
Protected Member Functions
Document * getDocument () const
Detailed Description
The DocumentObserver class simplifies the step to write classes that listen to what happens inside a document. This is very useful for classes that needs to be notified when an observed object has changed.
Author
Werner Mayer
Definition at line 539 of file App/DocumentObserver.h.
Constructor & Destructor Documentation
DocumentObserver() [1/2]
DocumentObserver::DocumentObserver ()
Constructor.
Definition at line 860 of file App/DocumentObserver.cpp.
References draftgeoutils.faces::bind(), App::GetApplication(), App::Application::signalActiveDocument, App::Application::signalDeleteDocument, and App::Application::signalNewDocument.
DocumentObserver() [2/2]
DocumentObserver::DocumentObserver (Document * doc) explicit
Definition at line 873 of file App/DocumentObserver.cpp.
References attachDocument(), and toolbit-attributes::doc.
~DocumentObserver()
DocumentObserver::~DocumentObserver () virtual
Definition at line 880 of file App/DocumentObserver.cpp.
References detachDocument().
Member Function Documentation
attachDocument()
void DocumentObserver::attachDocument (Document * doc)
Attaches to another document, the old document is not longer observed then.
Definition at line 894 of file App/DocumentObserver.cpp.
References draftgeoutils.faces::bind(), detachDocument(), toolbit-attributes::doc, App::Document::signalChangedObject, App::Document::signalDeletedObject, App::Document::signalNewObject, App::Document::signalRecomputed, and App::Document::signalRecomputedObject.
Referenced by PartGui::DlgProjectionOnSurface::DlgProjectionOnSurface(), DocumentObserver(), TechDraw::DrawSVGTemplate::onSettingDocument(), FemGui::ActiveAnalysisObserver::setActiveObject(), and MeshGui::DlgEvaluateMeshImp::setMesh().
detachDocument()
void DocumentObserver::detachDocument ()
Detaches from the current document, the document is not longer observed then.
Definition at line 915 of file App/DocumentObserver.cpp.
Referenced by attachDocument(), and ~DocumentObserver().
getDocument()
Document * DocumentObserver::getDocument () const protected
Definition at line 889 of file App/DocumentObserver.cpp.
Referenced by Sandbox::DocumentProtector::addObject(), Sandbox::DocumentProtector::recompute(), MeshGui::DlgEvaluateMeshImp::refreshList(), Sandbox::DocumentProtector::removeObject(), and MeshGui::DlgEvaluateMeshImp::setMesh().
The documentation for this class was generated from the following files:
App/DocumentObserver.h
App/DocumentObserver.cpp