FreeCAD: Gui::InteractiveScale Class Reference
Gui::InteractiveScale Class Reference
#include <TaskImage.h>
Signals
void scaleRequired ()
void scaleCanceled ()
void enableApplyBtn ()
Public Member Functions
InteractiveScale (View3DInventorViewer *view, ViewProvider *vp, const Base::Placement &plc)
~InteractiveScale () override
bool eventFilter (QObject *object, QEvent *event) override
void activate ()
void deactivate ()
bool isActive () const
double getScaleFactor () const
double getDistance (const SbVec3f &) const
void setPlacement (const Base::Placement &plc)
Detailed Description
Definition at line 43 of file TaskImage.h.
Constructor & Destructor Documentation
InteractiveScale()
InteractiveScale::InteractiveScale (View3DInventorViewer * view, ViewProvider * vp, const Base::Placement & plc) explicit
Definition at line 459 of file TaskImage.cpp.
~InteractiveScale()
InteractiveScale::~InteractiveScale () override
Definition at line 472 of file TaskImage.cpp.
Member Function Documentation
activate()
void InteractiveScale::activate ()
Definition at line 477 of file TaskImage.cpp.
Referenced by ArchBuildingPart.ViewProviderBuildingPart::setEdit(), nativeifc.ifc_viewproviders.ifc_vp_object::setupContextMenu(), and ArchBuildingPart.ViewProviderBuildingPart::setupContextMenu().
deactivate()
void InteractiveScale::deactivate ()
Definition at line 493 of file TaskImage.cpp.
References Gui::EditableDatumLabel::deactivate().
Referenced by CommandCreateBom.TaskAssemblyCreateBom::accept(), CommandInsertNewPart.TaskAssemblyNewPart::accept(), CommandCreateView.TaskAssemblyCreateView::accept(), CommandCreateSimulation.TaskAssemblyCreateSimulation::accept(), JointObject.TaskAssemblyCreateJoint::accept(), CommandCreateBom.TaskAssemblyCreateBom::reject(), CommandCreateView.TaskAssemblyCreateView::reject(), CommandCreateSimulation.TaskAssemblyCreateSimulation::reject(), and JointObject.TaskAssemblyCreateJoint::reject().
enableApplyBtn
void Gui::InteractiveScale::enableApplyBtn () signal
eventFilter()
bool InteractiveScale::eventFilter (QObject * object, QEvent * event) override
Definition at line 629 of file TaskImage.cpp.
References scaleCanceled(), and scaleRequired().
getDistance()
double InteractiveScale::getDistance (const SbVec3f & pt) const
Definition at line 520 of file TaskImage.cpp.
getScaleFactor()
double InteractiveScale::getScaleFactor () const
Definition at line 511 of file TaskImage.cpp.
References Gui::EditableDatumLabel::getValue().
isActive()
bool Gui::InteractiveScale::isActive () const inline
Definition at line 55 of file TaskImage.h.
scaleCanceled
void Gui::InteractiveScale::scaleCanceled () signal
Referenced by eventFilter().
scaleRequired
void Gui::InteractiveScale::scaleRequired () signal
Referenced by eventFilter().
setPlacement()
void InteractiveScale::setPlacement (const Base::Placement & plc)
Definition at line 649 of file TaskImage.cpp.
References Gui::EditableDatumLabel::setPlacement().
The documentation for this class was generated from the following files:
TaskImage.h
TaskImage.cpp