FreeCAD: Gui::Dialog::PrintModel Class Reference
Gui::Dialog::PrintModel Class Reference
#include <DlgCustomizeSpaceball.h>
Public Member Functions
PrintModel (QObject *parent, ButtonModel *buttonModelIn, CommandModel *commandModelIn)
int rowCount (const QModelIndex &parent) const override
int columnCount (const QModelIndex &parent) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
Detailed Description
Definition at line 127 of file DlgCustomizeSpaceball.h.
Constructor & Destructor Documentation
PrintModel()
PrintModel::PrintModel (QObject * parent, ButtonModel * buttonModelIn, CommandModel * commandModelIn)
Definition at line 603 of file DlgCustomizeSpaceball.cpp.
Member Function Documentation
columnCount()
int PrintModel::columnCount (const QModelIndex & parent) const override
Definition at line 617 of file DlgCustomizeSpaceball.cpp.
References Init::parent.
data()
QVariant PrintModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 623 of file DlgCustomizeSpaceball.cpp.
References Gui::Dialog::ButtonModel::data(), Gui::Dialog::CommandModel::data(), and Gui::Dialog::CommandModel::index().
headerData()
QVariant PrintModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const override
Definition at line 648 of file DlgCustomizeSpaceball.cpp.
References Sketcher::Horizontal.
rowCount()
int PrintModel::rowCount (const QModelIndex & parent) const override
Definition at line 611 of file DlgCustomizeSpaceball.cpp.
References Init::parent, and Gui::Dialog::ButtonModel::rowCount().
Referenced by src.Mod.AddonManager.package_list.PackageListItemModel::append_item(), src.Mod.AddonManager.AddonManagerOptions.CustomRepoDataModel::appendData(), and src.Mod.AddonManager.package_list.PackageListItemModel::clear().
The documentation for this class was generated from the following files:
DlgCustomizeSpaceball.h
DlgCustomizeSpaceball.cpp