FreeCAD: TechDrawGui::QGSPage Class Reference
TechDrawGui::QGSPage Class Reference
#include <QGSPage.h>
Public Member Functions
QGSPage (ViewProviderPage *vpPage, QWidget *parent=nullptr)
~QGSPage () override=default
bool addView (const App::DocumentObject *obj)
bool attachView (App::DocumentObject *obj)
QGIView * addViewDimension (TechDraw::DrawViewDimension *dimFeat)
QGIView * addViewBalloon (TechDraw::DrawViewBalloon *balloonFeat)
QGIView * addProjectionGroup (TechDraw::DrawProjGroup *projGroupFeat)
QGIView * addViewPart (TechDraw::DrawViewPart *partFeat)
QGIView * addViewSection (TechDraw::DrawViewSection *sectionFeat)
QGIView * addDrawView (TechDraw::DrawView *viewFeat)
QGIView * addDrawViewCollection (TechDraw::DrawViewCollection *collectionFeat)
QGIView * addAnnotation (TechDraw::DrawViewAnnotation *annoFeat)
QGIView * addDrawViewSymbol (TechDraw::DrawViewSymbol *symbolFeat)
QGIView * addDrawViewClip (TechDraw::DrawViewClip *clipFeat)
QGIView * addDrawViewSpreadsheet (TechDraw::DrawViewSpreadsheet *sheetFeat)
QGIView * addDrawViewImage (TechDraw::DrawViewImage *imageFeat)
QGIView * addViewLeader (TechDraw::DrawLeaderLine *leaderFeat)
QGIView * addRichAnno (TechDraw::DrawRichAnno *richFeat)
QGIView * addWeldSymbol (TechDraw::DrawWeldSymbol *weldFeat)
void addChildrenToPage ()
void fixOrphans (bool force=false)
void redrawAllViews ()
void redraw1View (TechDraw::DrawView *dView)
QGIView * findQViewForDocObj (App::DocumentObject *obj) const
find the graphic for a DocumentObject
QGIView * getQGIVByName (std::string name) const
find the graphic for DocumentObject with name
QGIView * findParent (QGIView *) const
void findMissingViews (const std::vector< App::DocumentObject * > &list, std::vector< App::DocumentObject * > &missing)
bool hasQView (App::DocumentObject *obj)
void addBalloonToParent (QGIViewBalloon *balloon, QGIView *parent)
void createBalloon (QPointF origin, TechDraw::DrawView *parent)
void addDimToParent (QGIViewDimension *dim, QGIView *parent)
void addLeaderToParent (QGILeaderLine *leader, QGIView *parent)
void addRichAnnoToParent (QGIRichAnno *anno, QGIView *parent)
void addItemToScene (QGIView *item)
void addItemToParent (QGIView *item, QGIView *parent)
adds item to parent's group with position adjustments if required.
std::vector< QGIView * > getViews () const
retrieve the QGIView objects currently in the scene
int addQView (QGIView *view)
int removeQView (QGIView *view)
int removeQViewByName (const char *name)
void removeQViewFromScene (QGIView *view)
void setPageTemplate (TechDraw::DrawTemplate *templateFeat)
QGITemplate * getTemplate () const
void removeTemplate ()
void matchSceneRectToTemplate ()
void attachTemplate (TechDraw::DrawTemplate *obj)
void updateTemplate (bool force=false)
QPointF getTemplateCenter ()
TechDraw::DrawPage * getDrawPage ()
void setExportingSvg (bool enable)
bool getExportingSvg ()
void setExportingPdf (bool enable)
bool getExportingPdf () const
virtual void refreshViews ()
void saveSvg (QString filename)
Renders the page to SVG with filename.
void postProcessXml (QTemporaryFile &temporaryFile, QString filename, QString pagename)
void setViewParents ()
ensure that all QGIViews are parented correctly in the scene
Static Public Member Functions
static bool itemClearsSelection (int itemTypeIn)
returns true if clicking on the item should clear the selection
static Qt::KeyboardModifiers cleanModifierList (Qt::KeyboardModifiers mods)
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
QColor getBackgroundColor ()
bool orphanExists (const char *viewName, const std::vector< App::DocumentObject * > &list)
Detailed Description
Definition at line 72 of file QGSPage.h.
Constructor & Destructor Documentation
QGSPage()
QGSPage::QGSPage (ViewProviderPage * vpPage, QWidget * parent = nullptr) explicit
Definition at line 102 of file QGSPage.cpp.
~QGSPage()
TechDrawGui::QGSPage::~QGSPage () override default
Member Function Documentation
addAnnotation()
QGIView * QGSPage::addAnnotation (TechDraw::DrawViewAnnotation * annoFeat)
Definition at line 552 of file QGSPage.cpp.
References addItemToScene(), ZVALUE::ANNOTATION, and TechDrawGui::QGIView::setViewFeature().
Referenced by attachView().
addBalloonToParent()
void QGSPage::addBalloonToParent (QGIViewBalloon * balloon, QGIView * parent)
Definition at line 608 of file QGSPage.cpp.
References ZVALUE::DIMENSION, and Init::parent.
addChildrenToPage()
void QGSPage::addChildrenToPage ()
Definition at line 176 of file QGSPage.cpp.
References attachTemplate(), attachView(), TechDrawGui::ViewProviderPage::getDrawPage(), App::PropertyLink::getValue(), TechDraw::DrawPage::getViews(), matchSceneRectToTemplate(), setViewParents(), and TechDraw::DrawPage::Template.
addDimToParent()
void QGSPage::addDimToParent (QGIViewDimension * dim, QGIView * parent)
Definition at line 676 of file QGSPage.cpp.
References ZVALUE::DIMENSION, and Init::parent.
addDrawView()
QGIView * QGSPage::addDrawView (TechDraw::DrawView * viewFeat)
Definition at line 535 of file QGSPage.cpp.
Referenced by attachView().
addDrawViewClip()
QGIView * QGSPage::addDrawViewClip (TechDraw::DrawViewClip * clipFeat)
Definition at line 571 of file QGSPage.cpp.
References addItemToScene(), App::PropertyQuantity::getValue(), TechDrawGui::Rez::guiX(), TechDraw::DrawView::X, and TechDraw::DrawView::Y.
Referenced by attachView().
addDrawViewCollection()
QGIView * QGSPage::addDrawViewCollection (TechDraw::DrawViewCollection * collectionFeat)
Definition at line 543 of file QGSPage.cpp.
addDrawViewImage()
QGIView * QGSPage::addDrawViewImage (TechDraw::DrawViewImage * imageFeat)
Definition at line 590 of file QGSPage.cpp.
References addItemToScene().
Referenced by attachView().
addDrawViewSpreadsheet()
QGIView * QGSPage::addDrawViewSpreadsheet (TechDraw::DrawViewSpreadsheet * sheetFeat)
Definition at line 581 of file QGSPage.cpp.
References addItemToScene().
Referenced by attachView().
addDrawViewSymbol()
QGIView * QGSPage::addDrawViewSymbol (TechDraw::DrawViewSymbol * symbolFeat)
Definition at line 562 of file QGSPage.cpp.
References addItemToScene(), and TechDrawGui::QGIView::setViewFeature().
Referenced by attachView().
addItemToParent()
void QGSPage::addItemToParent (QGIView * item, QGIView * parent)
adds item to parent's group with position adjustments if required.
Definition at line 466 of file QGSPage.cpp.
References ZVALUE::DIMENSION, App::PropertyQuantity::getValue(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::Rez::guiX(), Init::parent, TechDrawGui::QGIView::type(), TechDraw::DrawView::X, and TechDraw::DrawView::Y.
Referenced by addItemToScene(), and setViewParents().
addItemToScene()
void QGSPage::addItemToScene (QGIView * item)
Definition at line 452 of file QGSPage.cpp.
References addItemToParent(), findParent(), and Init::parent.
Referenced by addAnnotation(), addDrawViewClip(), addDrawViewImage(), addDrawViewSpreadsheet(), addDrawViewSymbol(), addRichAnno(), addViewBalloon(), addViewDimension(), and addViewLeader().
addLeaderToParent()
void QGSPage::addLeaderToParent (QGILeaderLine * leader, QGIView * parent)
Definition at line 698 of file QGSPage.cpp.
References ZVALUE::DIMENSION, App::PropertyQuantity::getValue(), TechDrawGui::QGIView::getViewObject(), Init::parent, TechDraw::DrawView::X, and TechDraw::DrawView::Y.
addProjectionGroup()
QGIView * QGSPage::addProjectionGroup (TechDraw::DrawProjGroup * projGroupFeat)
Definition at line 525 of file QGSPage.cpp.
Referenced by attachView().
addQView()
int QGSPage::addQView (QGIView * view)
Definition at line 309 of file QGSPage.cpp.
References Base::Console(), findParent(), getQGIVByName(), App::PropertyQuantity::getValue(), TechDrawGui::QGIView::getViewName(), TechDrawGui::QGIView::getViewObject(), TechDrawGui::QGIView::getViewProvider(), TechDrawGui::Rez::guiX(), Base::ConsoleSingleton::Message(), Init::parent, TechDrawGui::QGIView::updateView(), TechDraw::DrawView::X, and TechDraw::DrawView::Y.
addRichAnno()
QGIView * QGSPage::addRichAnno (TechDraw::DrawRichAnno * richFeat)
Definition at line 713 of file QGSPage.cpp.
References addItemToScene(), addRichAnnoToParent(), findParent(), Init::parent, and TechDrawGui::QGIView::setViewFeature().
Referenced by attachView().
addRichAnnoToParent()
void QGSPage::addRichAnnoToParent (QGIRichAnno * anno, QGIView * parent)
Definition at line 731 of file QGSPage.cpp.
References ZVALUE::DIMENSION, App::PropertyQuantity::getValue(), TechDrawGui::QGIView::getViewObject(), Init::parent, TechDraw::DrawView::X, and TechDraw::DrawView::Y.
Referenced by addRichAnno().
addView()
bool QGSPage::addView (const App::DocumentObject * obj)
Definition at line 385 of file QGSPage.cpp.
References attachView().
addViewBalloon()
QGIView * QGSPage::addViewBalloon (TechDraw::DrawViewBalloon * balloonFeat)
Definition at line 599 of file QGSPage.cpp.
References addItemToScene().
Referenced by attachView().
addViewDimension()
QGIView * QGSPage::addViewDimension (TechDraw::DrawViewDimension * dimFeat)
Definition at line 667 of file QGSPage.cpp.
References addItemToScene().
Referenced by attachView().
addViewLeader()
QGIView * QGSPage::addViewLeader (TechDraw::DrawLeaderLine * leaderFeat)
Definition at line 688 of file QGSPage.cpp.
References addItemToScene(), and TechDrawGui::QGIView::setViewFeature().
Referenced by attachView().
addViewPart()
QGIView * QGSPage::addViewPart (TechDraw::DrawViewPart * partFeat)
Definition at line 504 of file QGSPage.cpp.
Referenced by attachView().
addViewSection()
QGIView * QGSPage::addViewSection (TechDraw::DrawViewSection * sectionFeat)
Definition at line 515 of file QGSPage.cpp.
Referenced by attachView().
addWeldSymbol()
QGIView * QGSPage::addWeldSymbol (TechDraw::DrawWeldSymbol * weldFeat)
Definition at line 750 of file QGSPage.cpp.
References TechDrawGui::QGIView::setViewFeature().
Referenced by attachView().
attachTemplate()
void QGSPage::attachTemplate (TechDraw::DrawTemplate * obj)
Definition at line 208 of file QGSPage.cpp.
References setPageTemplate().
Referenced by addChildrenToPage(), and TechDrawGui::ViewProviderTemplate::updateData().
attachView()
bool QGSPage::attachView (App::DocumentObject * obj)
Definition at line 390 of file QGSPage.cpp.
References addAnnotation(), addDrawView(), addDrawViewClip(), addDrawViewImage(), addDrawViewSpreadsheet(), addDrawViewSymbol(), addProjectionGroup(), addRichAnno(), addViewBalloon(), addViewDimension(), addViewLeader(), addViewPart(), addViewSection(), addWeldSymbol(), findQViewForDocObj(), Base::Persistence::getClassTypeId(), and Base::Persistence::getTypeId().
Referenced by addChildrenToPage(), addView(), and fixOrphans().
cleanModifierList()
Qt::KeyboardModifiers QGSPage::cleanModifierList (Qt::KeyboardModifiers mods) static
return only the modifiers that are relevant to snapping/balloon drag. this is a substitute for !modifiers (ie no modifiers in use) since keypad or group modifiers (which don't apply to snapping/dragging) would give a misleading result.
Definition at line 157 of file QGSPage.cpp.
Referenced by mousePressEvent().
createBalloon()
void QGSPage::createBalloon (QPointF origin, TechDraw::DrawView * parent)
Definition at line 620 of file QGSPage.cpp.
References TechDrawGui::Rez::appX(), Gui::Command::commitCommand(), doCommand, App::DocumentObject::getDocument(), getDrawPage(), App::DocumentObject::getNameInDocument(), TechDraw::DrawPage::getNextBalloonIndex(), App::Document::getObject(), getQGIVByName(), App::Document::getUniqueObjectName(), Gui::Command::openCommand(), Init::parent, Arch::QT_TRANSLATE_NOOP, TechDraw::DrawViewBalloon::setOrigin(), TechDraw::DrawView::setPosition(), App::PropertyString::setValue(), TechDraw::DrawViewBalloon::Text, Base::toRadians(), and TechDraw::DrawUtil::toVector3d().
Referenced by TechDrawGui::QGVNavStyle::placeBalloon().
findMissingViews()
void QGSPage::findMissingViews (const std::vector< App::DocumentObject * > & list, std::vector< App::DocumentObject * > & missing)
Definition at line 895 of file QGSPage.cpp.
References hasQView().
findParent()
QGIView * QGSPage::findParent (QGIView * view) const
Definition at line 812 of file QGSPage.cpp.
References TechDraw::DrawView::claimParent(), App::DocumentObject::getNameInDocument(), getQGIVByName(), TechDrawGui::QGIView::getViewObject(), getViews(), and replaceobj::objs.
Referenced by addItemToScene(), addQView(), addRichAnno(), and setViewParents().
findQViewForDocObj()
QGIView * QGSPage::findQViewForDocObj (App::DocumentObject * obj) const
find the graphic for a DocumentObject
Definition at line 781 of file QGSPage.cpp.
References App::DocumentObject::getNameInDocument(), and getViews().
Referenced by attachView(), fixOrphans(), TechDrawGui::ViewProviderDrawingView::getQView(), TechDrawGui::TaskLeaderLine::onTrackerClicked(), TechDrawGui::TaskCosVertex::setEditCursor(), TechDrawGui::TaskLeaderLine::setEditCursor(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), and TechDrawGui::TaskRichAnno::TaskRichAnno().
fixOrphans()
void QGSPage::fixOrphans (bool force = false)
Definition at line 922 of file QGSPage.cpp.
References attachView(), TechDraw::DrawView::claimParent(), TechDraw::DrawView::countParentPages(), toolbit-attributes::doc, TechDraw::DrawView::findParentPage(), findQViewForDocObj(), TechDraw::DrawPage::getAllViews(), App::DocumentObject::getDocument(), TechDrawGui::ViewProviderPage::getDrawPage(), getViews(), TechDraw::DrawPage::getViews(), App::DocumentObject::isAttachedToDocument(), buildPsets::p, removeQView(), and TestSpreadsheet::v.
getBackgroundColor()
QColor QGSPage::getBackgroundColor () protected
Definition at line 1257 of file QGSPage.cpp.
References App::Color::asValue(), and App::Color::setPackedValue().
getDrawPage()
TechDraw::DrawPage * QGSPage::getDrawPage ()
Definition at line 1255 of file QGSPage.cpp.
References TechDrawGui::ViewProviderPage::getDrawPage().
Referenced by TechDrawGui::_createBalloon(), createBalloon(), and TechDrawGui::DrawGuiUtil::findPage().
getExportingPdf()
bool TechDrawGui::QGSPage::getExportingPdf () const inline
Definition at line 142 of file QGSPage.h.
getExportingSvg()
bool TechDrawGui::QGSPage::getExportingSvg () inline
Definition at line 139 of file QGSPage.h.
Referenced by TechDrawGui::QGIFace::exporting().
getQGIVByName()
QGIView * QGSPage::getQGIVByName (std::string name) const
find the graphic for DocumentObject with name
Definition at line 795 of file QGSPage.cpp.
References TechDrawGui::QGIView::getViewName(), and src.Mod.Test.testPathArray::items.
Referenced by addQView(), createBalloon(), and findParent().
getTemplate()
QGITemplate * QGSPage::getTemplate () const
Definition at line 282 of file QGSPage.cpp.
Referenced by TechDrawGui::ViewProviderTemplate::getQTemplate(), and updateTemplate().
getTemplateCenter()
QPointF QGSPage::getTemplateCenter ()
Definition at line 242 of file QGSPage.cpp.
References TechDrawGui::ViewProviderPage::getDrawPage(), App::PropertyLink::getValue(), TechDrawGui::Rez::guiX(), and TechDraw::DrawPage::Template.
Referenced by TechDrawGui::QGVPage::centerOnPage().
getViews()
std::vector< QGIView * > QGSPage::getViews () const
retrieve the QGIView objects currently in the scene
Definition at line 296 of file QGSPage.cpp.
References src.Mod.Test.testPathArray::items, result, and TestSpreadsheet::v.
Referenced by findParent(), findQViewForDocObj(), fixOrphans(), hasQView(), redraw1View(), redrawAllViews(), removeQViewByName(), setViewParents(), and TechDrawGui::QGIView::snapPosition().
hasQView()
bool QGSPage::hasQView (App::DocumentObject * obj)
Definition at line 859 of file QGSPage.cpp.
References App::DocumentObject::getNameInDocument(), and getViews().
Referenced by findMissingViews().
itemClearsSelection()
bool QGSPage::itemClearsSelection (int itemTypeIn) static
returns true if clicking on the item should clear the selection
Definition at line 135 of file QGSPage.cpp.
References Path.Post.scripts.grbl_post::type.
Referenced by mousePressEvent().
matchSceneRectToTemplate()
void QGSPage::matchSceneRectToTemplate ()
Definition at line 254 of file QGSPage.cpp.
References TechDrawGui::ViewProviderPage::getDrawPage(), App::PropertyLink::getValue(), TechDrawGui::Rez::guiX(), and TechDraw::DrawPage::Template.
Referenced by addChildrenToPage(), and TechDrawGui::ViewProviderTemplate::updateData().
mousePressEvent()
void QGSPage::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 112 of file QGSPage.cpp.
References cleanModifierList(), Gui::SelectionSingleton::clearSelection(), itemClearsSelection(), TechDrawGui::PreferencesGui::multiSelection(), and Gui::Selection().
orphanExists()
bool QGSPage::orphanExists (const char * viewName, const std::vector< App::DocumentObject * > & list) protected
Definition at line 1006 of file QGSPage.cpp.
postProcessXml()
void QGSPage::postProcessXml (QTemporaryFile & temporaryFile, QString filename, QString pagename)
Definition at line 1151 of file QGSPage.cpp.
References CC_NS_URI, Base::Console(), DC_NS_URI, Base::ConsoleSingleton::Error(), DrawingExample::file, Base::FileInfo::fileName(), FREECAD_SVG_NS_URI, TechDrawGui::QGISVGTemplate::getSVGTemplate(), App::PropertyFileIncluded::getValue(), TechDrawGui::Rez::guiX(), INKSCAPE_NS_URI, TechDraw::DrawSVGTemplate::PageResult, TechDraw::DrawSVGTemplate::processTemplate(), RDF_NS_URI, removeEmptyGroups(), SODIPODI_NS_URI, and SVG_NS_URI.
Referenced by saveSvg().
redraw1View()
void QGSPage::redraw1View (TechDraw::DrawView * dView)
Definition at line 1036 of file QGSPage.cpp.
References App::DocumentObject::getNameInDocument(), and getViews().
redrawAllViews()
void QGSPage::redrawAllViews ()
Definition at line 1026 of file QGSPage.cpp.
References getViews().
Referenced by TechDrawGui::PagePrinter::renderPage().
refreshViews()
void QGSPage::refreshViews () virtual
Definition at line 875 of file QGSPage.cpp.
References src.Mod.Test.testPathArray::items, and TechDrawGui::QGIView::updateView().
Referenced by TechDrawGui::PagePrinter::renderPage(), and saveSvg().
removeQView()
int QGSPage::removeQView (QGIView * view)
Definition at line 337 of file QGSPage.cpp.
References removeQViewFromScene().
Referenced by fixOrphans().
removeQViewByName()
int QGSPage::removeQViewByName (const char * name)
Definition at line 346 of file QGSPage.cpp.
References getViews(), SplineSurface::i, src.Mod.Test.testPathArray::items, removeQViewFromScene(), and TechDrawGui::QGIView::type().
removeQViewFromScene()
void QGSPage::removeQViewFromScene (QGIView * view)
Definition at line 374 of file QGSPage.cpp.
References TechDrawGui::QGIView::removeChild().
Referenced by removeQView(), and removeQViewByName().
removeTemplate()
void QGSPage::removeTemplate ()
Definition at line 284 of file QGSPage.cpp.
Referenced by setPageTemplate().
saveSvg()
void QGSPage::saveSvg (QString filename)
Renders the page to SVG with filename.
Definition at line 1063 of file QGSPage.cpp.
References Gui::SelectionSingleton::clearSelection(), App::DocumentObject::getDocument(), TechDrawGui::ViewProviderPage::getDrawPage(), TechDrawGui::ViewProviderPage::getFrameState(), App::Document::getName(), App::DocumentObject::getNameInDocument(), TechDraw::DrawPage::getPageHeight(), TechDraw::DrawPage::getPageWidth(), TechDrawGui::Rez::guiX(), buildPsets::p, postProcessXml(), refreshViews(), OfflineRenderingUtils::render(), Gui::Selection(), setExportingSvg(), TechDrawGui::ViewProviderPage::setFrameState(), and TechDrawGui::ViewProviderPage::setTemplateMarkers().
setExportingPdf()
void TechDrawGui::QGSPage::setExportingPdf (bool enable) inline
Definition at line 141 of file QGSPage.h.
Referenced by TechDrawGui::PagePrinter::print(), TechDrawGui::PagePrinter::printAllPdf(), and TechDrawGui::PagePrinter::printPdf().
setExportingSvg()
void QGSPage::setExportingSvg (bool enable)
Definition at line 1051 of file QGSPage.cpp.
References src.Mod.Test.testPathArray::items, and TechDrawGui::QGIRichAnno::setExportingSvg().
Referenced by TechDrawGui::PagePrinter::saveSVG(), and saveSvg().
setPageTemplate()
void QGSPage::setPageTemplate (TechDraw::DrawTemplate * templateFeat)
Definition at line 267 of file QGSPage.cpp.
References Base::Persistence::getClassTypeId(), Base::BaseClass::isDerivedFrom(), removeTemplate(), TechDrawGui::QGITemplate::setTemplate(), and TechDrawGui::QGITemplate::updateView().
Referenced by attachTemplate().
setViewParents()
void QGSPage::setViewParents ()
ensure that all QGIViews are parented correctly in the scene
Definition at line 761 of file QGSPage.cpp.
References addItemToParent(), findParent(), getViews(), and Init::parent.
Referenced by addChildrenToPage().
updateTemplate()
void QGSPage::updateTemplate (bool force = false)
Definition at line 214 of file QGSPage.cpp.
References Base::Persistence::getClassTypeId(), TechDrawGui::ViewProviderPage::getDrawPage(), getTemplate(), App::PropertyLink::getValue(), Base::BaseClass::isDerivedFrom(), App::DocumentObject::isTouched(), App::Property::isTouched(), TechDrawGui::QGITemplate::setTemplate(), TechDraw::DrawPage::Template, and TechDrawGui::QGITemplate::updateView().
The documentation for this class was generated from the following files:
QGSPage.h
QGSPage.cpp