FreeCAD: importCSG Namespace Reference
importCSG Namespace Reference
Functions
def shallHide (subject)
def setColorRecursively (obj, color, transp)
def fixVisibility ()
def open (filename)
def insert (filename, docname)
def processcsg (filename)
def p_block_list_ (p)
def p_render_action (p)
def p_group_action1 (p)
def p_group_action2 (p)
def p_boolean (p)
def p_stripped_string (p)
def p_statement (p)
def p_anymodifier (p)
def p_statementwithmod (p)
def p_part (p)
def p_2d_point (p)
def p_points_list_2d (p)
def p_3d_point (p)
def p_points_list_3d (p)
def p_path_points (p)
def p_path_list (p)
def p_path_set (p)
def p_operation (p)
def placeholder (name, children, arguments)
def CGALFeatureObj (name, children, arguments=[])
def p_offset_action (p)
def checkObjShape (obj)
def p_hull_action (p)
def p_minkowski_action (p)
def p_resize_action (p)
def p_not_supported (p)
def p_size_vector (p)
def p_keywordargument (p)
def p_keywordargument_list (p)
def p_color_action (p)
def p_error (p)
def fuse (lst, name)
def p_empty_union_action (p)
def p_union_action (p)
def p_difference_action (p)
def p_intersection_action (p)
def process_rotate_extrude (obj, angle)
def process_rotate_extrude_prism (obj, angle, n)
def p_rotate_extrude_action (p)
def p_rotate_extrude_file (p)
def process_linear_extrude (obj, h)
def process_linear_extrude_with_transform (base, height, twist, scale)
def p_linear_extrude_with_transform (p)
def p_import_file1 (p)
def p_surface_action (p)
def process_import_file (fname, ext, layer)
def processSVG (fname, ext)
def process_mesh_file (fname, ext)
def processTextCmd (t)
def processDXF (fname, layer)
def processSTL (fname)
def p_multmatrix_action (p)
def p_matrix (p)
def p_vector (p)
def center (obj, x, y, z)
def p_sphere_action (p)
def myPolygon (n, r1)
def p_cylinder_action (p)
def p_cube_action (p)
def p_circle_action (p)
def p_square_action (p)
def addString (t, s, p)
def addValue (t, v, p)
def p_text_action (p)
def convert_points_list_to_vector (l)
def p_polygon_action_nopath (p)
def p_polygon_action_plus_path (p)
def make_face (v1, v2, v3)
def p_polyhedron_action (p)
def p_projection_action (p)
Variables
bool printverbose = False
params = FreeCAD.ParamGet("User parameter:BaseApp/Preferences/Mod/OpenSCAD")
bool gui = True
list hassetcolor = []
list alreadyhidden = []
list original_root_objects = []
translate = FreeCAD.Qt.translate
Function Documentation
addString()
def importCSG.addString (t, s, p)
Definition at line 1283 of file importCSG.py.
Referenced by p_text_action().
addValue()
def importCSG.addValue (t, v, p)
Definition at line 1286 of file importCSG.py.
Referenced by p_text_action().
center()
def importCSG.center (obj, x, y, z)
Definition at line 1092 of file importCSG.py.
Referenced by p_cube_action(), p_cylinder_action(), p_linear_extrude_with_transform(), p_square_action(), and p_surface_action().
CGALFeatureObj()
def importCSG.CGALFeatureObj (name, children, arguments = [])
Definition at line 429 of file importCSG.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by p_hull_action(), and p_minkowski_action().
checkObjShape()
def importCSG.checkObjShape (obj)
Definition at line 479 of file importCSG.py.
Referenced by fuse(), p_difference_action(), p_group_action1(), p_intersection_action(), p_linear_extrude_with_transform(), and p_offset_action().
convert_points_list_to_vector()
def importCSG.convert_points_list_to_vector (l)
Definition at line 1315 of file importCSG.py.
Referenced by p_polygon_action_nopath(), and p_polygon_action_plus_path().
fixVisibility()
def importCSG.fixVisibility ()
Definition at line 99 of file importCSG.py.
Referenced by processcsg().
fuse()
def importCSG.fuse (lst, name)
Definition at line 602 of file importCSG.py.
References checkObjShape(), and placeholder().
insert()
def importCSG.insert (filename, docname)
Definition at line 131 of file importCSG.py.
References OpenSCADUtils.callopenscad(), and processcsg().
Referenced by OpenSCADCommands.AddSCADTask.addelement().
make_face()
def importCSG.make_face (v1, v2, v3)
Definition at line 1362 of file importCSG.py.
myPolygon()
def importCSG.myPolygon (n, r1)
Definition at line 1107 of file importCSG.py.
Referenced by p_cylinder_action().
open()
def importCSG.open (filename)
Definition at line 111 of file importCSG.py.
References OpenSCADUtils.callopenscad(), and processcsg().
Referenced by OpenSCADTest.app.test_importCSG.TestImportCSG.test_open_csg(), OpenSCADTest.app.test_importCSG.TestImportCSG.test_open_scad(), and OpenSCADTest.app.test_importCSG.TestImportCSG.utility_create_scad().
p_2d_point()
def importCSG.p_2d_point (p)
Definition at line 305 of file importCSG.py.
p_3d_point()
def importCSG.p_3d_point (p)
Definition at line 332 of file importCSG.py.
p_anymodifier()
def importCSG.p_anymodifier (p)
anymodifier : MODIFIERBACK
               | MODIFIERDEBUG
               | MODIFIERROOT
               | MODIFIERDISABLE
Definition at line 268 of file importCSG.py.
p_block_list_()
def importCSG.p_block_list_ (p)
block_list : statement
           | block_list statement
           | statementwithmod
           | block_list statementwithmod
Definition at line 191 of file importCSG.py.
p_boolean()
def importCSG.p_boolean (p)
boolean : true
        | false
Definition at line 238 of file importCSG.py.
p_circle_action()
def importCSG.p_circle_action (p)
Definition at line 1235 of file importCSG.py.
References Path.Post.scripts.refactored_centroid_post.str.
p_color_action()
def importCSG.p_color_action (p)
Definition at line 581 of file importCSG.py.
References setColorRecursively(), and shallHide().
p_cube_action()
def importCSG.p_cube_action (p)
Definition at line 1216 of file importCSG.py.
References center().
p_cylinder_action()
def importCSG.p_cylinder_action (p)
Definition at line 1123 of file importCSG.py.
References center(), and myPolygon().
p_difference_action()
def importCSG.p_difference_action (p)
Definition at line 648 of file importCSG.py.
References checkObjShape(), and placeholder().
p_empty_union_action()
def importCSG.p_empty_union_action (p)
Definition at line 632 of file importCSG.py.
p_error()
def importCSG.p_error (p)
Definition at line 598 of file importCSG.py.
p_group_action1()
def importCSG.p_group_action1 (p)
Definition at line 214 of file importCSG.py.
References checkObjShape().
p_group_action2()
def importCSG.p_group_action2 (p)
Definition at line 232 of file importCSG.py.
p_hull_action()
def importCSG.p_hull_action (p)
Definition at line 493 of file importCSG.py.
References CGALFeatureObj().
p_import_file1()
def importCSG.p_import_file1 (p)
Definition at line 855 of file importCSG.py.
References process_import_file().
p_intersection_action()
def importCSG.p_intersection_action (p)
Definition at line 676 of file importCSG.py.
References checkObjShape(), and placeholder().
p_keywordargument()
def importCSG.p_keywordargument (p)
keywordargument : ID EQ boolean
| ID EQ NUMBER
| ID EQ size_vector
| ID EQ vector
| ID EQ 2d_point
| text EQ stripped_string
| ID EQ stripped_string
Definition at line 558 of file importCSG.py.
p_keywordargument_list()
def importCSG.p_keywordargument_list (p)
keywordargument_list : keywordargument
           | keywordargument_list COMMA keywordargument
Definition at line 570 of file importCSG.py.
p_linear_extrude_with_transform()
def importCSG.p_linear_extrude_with_transform (p)
Definition at line 819 of file importCSG.py.
References center(), checkObjShape(), process_linear_extrude(), process_linear_extrude_with_transform(), and Path.Post.scripts.refactored_centroid_post.str.
p_matrix()
def importCSG.p_matrix (p)
Definition at line 1082 of file importCSG.py.
p_minkowski_action()
def importCSG.p_minkowski_action (p)
minkowski_action : minkowski LPAREN keywordargument_list RPAREN OBRACE block_list EBRACE
Definition at line 497 of file importCSG.py.
References CGALFeatureObj().
p_multmatrix_action()
def importCSG.p_multmatrix_action (p)
Definition at line 988 of file importCSG.py.
References KDL.abs(), OpenSCADUtils.decomposerotoinversion(), OpenSCADUtils.fcsubmatrix(), OpenSCADUtils.isrotoinversionpython(), OpenSCADUtils.isspecialorthogonalpython(), KDL.max(), placeholder(), and OpenSCADUtils.roundrotation().
p_not_supported()
def importCSG.p_not_supported (p)
not_supported : glide LPAREN keywordargument_list RPAREN OBRACE block_list EBRACE
              | subdiv LPAREN keywordargument_list RPAREN OBRACE block_list EBRACE
Definition at line 541 of file importCSG.py.
References placeholder().
p_offset_action()
def importCSG.p_offset_action (p)
Definition at line 443 of file importCSG.py.
References checkObjShape(), and placeholder().
p_operation()
def importCSG.p_operation (p)
operation : difference_action
          | intersection_action
          | union_action
          | rotate_extrude_action
          | linear_extrude_with_transform
          | rotate_extrude_file
          | import_file1
          | resize_action
          | surface_action
          | projection_action
          | hull_action
          | minkowski_action
          | offset_action
Definition at line 397 of file importCSG.py.
p_part()
def importCSG.p_part (p)
part : sphere_action
     | cylinder_action
     | cube_action
     | circle_action
     | square_action
     | text_action
     | polygon_action_nopath
     | polygon_action_plus_path
     | polyhedron_action
Definition at line 290 of file importCSG.py.
p_path_list()
def importCSG.p_path_list (p)
Definition at line 376 of file importCSG.py.
p_path_points()
def importCSG.p_path_points (p)
path_points : NUMBER COMMA
            | path_points NUMBER COMMA
            | path_points NUMBER
Definition at line 356 of file importCSG.py.
References Path.Post.scripts.uccnc_post.append().
p_path_set()
def importCSG.p_path_set (p)
path_set : path_list
         | path_set COMMA path_list
Definition at line 383 of file importCSG.py.
References Path.Post.scripts.uccnc_post.append().
p_points_list_2d()
def importCSG.p_points_list_2d (p)
points_list_2d : 2d_point COMMA
               | points_list_2d 2d_point COMMA
               | points_list_2d 2d_point
Definition at line 312 of file importCSG.py.
References Path.Post.scripts.uccnc_post.append().
p_points_list_3d()
def importCSG.p_points_list_3d (p)
points_list_3d : 3d_point COMMA
           | points_list_3d 3d_point COMMA
           | points_list_3d 3d_point
Definition at line 339 of file importCSG.py.
References Path.Post.scripts.uccnc_post.append().
p_polygon_action_nopath()
def importCSG.p_polygon_action_nopath (p)
Definition at line 1324 of file importCSG.py.
References convert_points_list_to_vector().
p_polygon_action_plus_path()
def importCSG.p_polygon_action_plus_path (p)
Definition at line 1338 of file importCSG.py.
References convert_points_list_to_vector().
p_polyhedron_action()
def importCSG.p_polyhedron_action (p)
polyhedron_action : polyhedron LPAREN points EQ OSQUARE points_list_3d ESQUARE COMMA faces EQ OSQUARE path_set ESQUARE COMMA keywordargument_list RPAREN SEMICOL
                  | polyhedron LPAREN points EQ OSQUARE points_list_3d ESQUARE COMMA triangles EQ OSQUARE points_list_3d ESQUARE COMMA keywordargument_list RPAREN SEMICOL
Definition at line 1367 of file importCSG.py.
References draftgeoutils.faces.removeSplitter().
p_projection_action()
def importCSG.p_projection_action (p)
Definition at line 1402 of file importCSG.py.
References placeholder().
p_render_action()
def importCSG.p_render_action (p)
Definition at line 208 of file importCSG.py.
p_resize_action()
def importCSG.p_resize_action (p)
resize_action : resize LPAREN keywordargument_list RPAREN OBRACE block_list EBRACE
Definition at line 502 of file importCSG.py.
References nativeifc.ifc_tools.recompute(), and Path.Post.scripts.refactored_centroid_post.str.
p_rotate_extrude_action()
def importCSG.p_rotate_extrude_action (p)
Definition at line 741 of file importCSG.py.
References process_rotate_extrude(), and process_rotate_extrude_prism().
p_rotate_extrude_file()
def importCSG.p_rotate_extrude_file (p)
Definition at line 762 of file importCSG.py.
References process_import_file(), process_rotate_extrude(), and process_rotate_extrude_prism().
p_size_vector()
def importCSG.p_size_vector (p)
Definition at line 553 of file importCSG.py.
p_sphere_action()
def importCSG.p_sphere_action (p)
Definition at line 1097 of file importCSG.py.
p_square_action()
def importCSG.p_square_action (p)
Definition at line 1270 of file importCSG.py.
References center().
p_statement()
def importCSG.p_statement (p)
statement : part
             | operation
             | multmatrix_action
             | group_action1
             | group_action2
             | color_action
             | render_action
             | not_supported
Definition at line 255 of file importCSG.py.
p_statementwithmod()
def importCSG.p_statementwithmod (p)
statementwithmod : anymodifier statement
Definition at line 280 of file importCSG.py.
p_stripped_string()
def importCSG.p_stripped_string (p)
Definition at line 250 of file importCSG.py.
p_surface_action()
def importCSG.p_surface_action (p)
Definition at line 862 of file importCSG.py.
References center(), and OpenSCADFeatures.makeSurfaceVolume().
p_text_action()
def importCSG.p_text_action (p)
Definition at line 1289 of file importCSG.py.
References addString(), addValue(), and processTextCmd().
p_union_action()
def importCSG.p_union_action (p)
Definition at line 640 of file importCSG.py.
p_vector()
def importCSG.p_vector (p)
Definition at line 1087 of file importCSG.py.
placeholder()
def importCSG.placeholder (name, children, arguments)
Definition at line 415 of file importCSG.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by fuse(), p_difference_action(), p_intersection_action(), p_multmatrix_action(), p_not_supported(), p_offset_action(), p_projection_action(), and Gui::Dialog::AboutDialog.showLicenseInformation().
process_import_file()
def importCSG.process_import_file (fname, ext, layer)
Definition at line 872 of file importCSG.py.
References process_mesh_file(), processDXF(), processSVG(), and OpenSCADUtils.reverseimporttypes().
Referenced by p_import_file1(), and p_rotate_extrude_file().
process_linear_extrude()
def importCSG.process_linear_extrude (obj, h)
Definition at line 781 of file importCSG.py.
Referenced by p_linear_extrude_with_transform().
process_linear_extrude_with_transform()
def importCSG.process_linear_extrude_with_transform (base, height, twist, scale)
Definition at line 804 of file importCSG.py.
Referenced by p_linear_extrude_with_transform().
process_mesh_file()
def importCSG.process_mesh_file (fname, ext)
Definition at line 916 of file importCSG.py.
Referenced by process_import_file().
process_rotate_extrude()
def importCSG.process_rotate_extrude (obj, angle)
Definition at line 706 of file importCSG.py.
Referenced by p_rotate_extrude_action(), and p_rotate_extrude_file().
process_rotate_extrude_prism()
def importCSG.process_rotate_extrude_prism (obj, angle, n)
Definition at line 727 of file importCSG.py.
Referenced by p_rotate_extrude_action(), and p_rotate_extrude_file().
processcsg()
def importCSG.processcsg (filename)
Definition at line 155 of file importCSG.py.
References fixVisibility().
Referenced by insert(), and open().
processDXF()
def importCSG.processDXF (fname, layer)
Definition at line 963 of file importCSG.py.
References OpenSCAD2Dgeom.importDXFface(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by process_import_file().
processSTL()
def importCSG.processSTL (fname)
Definition at line 985 of file importCSG.py.
processSVG()
def importCSG.processSVG (fname, ext)
Definition at line 884 of file importCSG.py.
Referenced by process_import_file().
processTextCmd()
def importCSG.processTextCmd (t)
Definition at line 950 of file importCSG.py.
References OpenSCADUtils.callopenscadstring(), and OpenSCAD2Dgeom.importDXFface().
Referenced by p_text_action().
setColorRecursively()
def importCSG.setColorRecursively (obj, color, transp)
For some reason a part made by cutting or fusing other parts do not have a color
unless its constituents are also colored. This code sets colors for those
constituents unless already set elsewhere.
Definition at line 81 of file importCSG.py.
Referenced by p_color_action().
shallHide()
def importCSG.shallHide (subject)
Definition at line 72 of file importCSG.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by p_color_action().
Variable Documentation
alreadyhidden
list importCSG.alreadyhidden = []
Definition at line 61 of file importCSG.py.
gui
bool importCSG.gui = True
Definition at line 55 of file importCSG.py.
hassetcolor
list importCSG.hassetcolor = []
Definition at line 60 of file importCSG.py.
original_root_objects
list importCSG.original_root_objects = []
Definition at line 62 of file importCSG.py.
params
importCSG.params = FreeCAD.ParamGet("User parameter:BaseApp/Preferences/Mod/OpenSCAD")
Definition at line 51 of file importCSG.py.
printverbose
importCSG.printverbose = False
Definition at line 33 of file importCSG.py.
translate
importCSG.translate = FreeCAD.Qt.translate
Definition at line 69 of file importCSG.py.