FreeCAD: TechDrawGui::QGCustomText Class Reference
TechDrawGui::QGCustomText Class Reference
#include <QGCustomText.h>
Public Types
enum { Type = QGraphicsItem::UserType + 130 }
Public Member Functions
QGCustomText (QGraphicsItem *parent=nullptr)
~QGCustomText () override
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QRectF tightBoundingRect () const
QRectF alignmentRect () const
a boundingRect for text alignment, that does not adversely affect rendering.
QPointF tightBoundingAdjust () const
void setHighlighted (bool state)
virtual void setPrettyNormal ()
virtual void setPrettyPre ()
virtual void setPrettySel ()
virtual void centerAt (QPointF centerPos)
virtual void centerAt (double cX, double cY)
virtual void justifyLeftAt (QPointF centerPos, bool vCenter=true)
virtual void justifyLeftAt (double cX, double cY, bool vCenter=true)
virtual void justifyRightAt (QPointF centerPos, bool vCenter=true)
virtual void justifyRightAt (double cX, double cY, bool vCenter=true)
virtual double getHeight ()
virtual double getWidth ()
virtual QColor getNormalColor ()
virtual QColor getPreColor ()
virtual QColor getSelectColor ()
virtual void setColor (QColor c)
virtual void setTightBounding (bool tight)
void makeMark (double x, double y)
void makeMark (Base::Vector3d v)
Protected Member Functions
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
Base::Reference< ParameterGrp > getParmGroup ()
Protected Attributes
bool isHighlighted
bool tightBounding
QColor m_colCurrent
QColor m_colNormal
Detailed Description
Definition at line 43 of file QGCustomText.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 49 of file QGCustomText.h.
Constructor & Destructor Documentation
QGCustomText()
QGCustomText::QGCustomText (QGraphicsItem * parent = nullptr) explicit
Definition at line 45 of file QGCustomText.cpp.
References getNormalColor(), m_colCurrent, m_colNormal, and tightBounding.
~QGCustomText()
TechDrawGui::QGCustomText::~QGCustomText () inline override
Definition at line 47 of file QGCustomText.h.
Member Function Documentation
alignmentRect()
QRectF QGCustomText::alignmentRect () const
a boundingRect for text alignment, that does not adversely affect rendering.
Definition at line 205 of file QGCustomText.cpp.
References tightBounding, and tightBoundingRect().
Referenced by TechDrawGui::QGIDatumLabel::setPosFromCenter().
centerAt() [1/2]
void QGCustomText::centerAt (double cX, double cY) virtual
Definition at line 63 of file QGCustomText.cpp.
References MengerSponge::box.
centerAt() [2/2]
void QGCustomText::centerAt (QPointF centerPos) virtual
Definition at line 58 of file QGCustomText.cpp.
Referenced by TechDrawGui::QGIViewAnnotation::drawAnnotation(), TechDrawGui::QGISectionLine::makeSymbolsISO(), TechDrawGui::QGISectionLine::makeSymbolsTrad(), TechDrawGui::QGITile::makeText(), TechDrawGui::QGIRichAnno::QGIRichAnno(), TechDrawGui::QGIRichAnno::setTextItem(), and TechDrawGui::QGIRichAnno::updateView().
getHeight()
double QGCustomText::getHeight () virtual
Definition at line 107 of file QGCustomText.cpp.
getNormalColor()
QColor QGCustomText::getNormalColor () virtual
Definition at line 245 of file QGCustomText.cpp.
References TechDrawGui::PreferencesGui::normalQColor().
Referenced by QGCustomText().
getParmGroup()
Base::Reference< ParameterGrp > QGCustomText::getParmGroup () protected
Definition at line 260 of file QGCustomText.cpp.
getPreColor()
QColor QGCustomText::getPreColor () virtual
Definition at line 250 of file QGCustomText.cpp.
References TechDrawGui::PreferencesGui::preselectQColor().
Referenced by setPrettyPre().
getSelectColor()
QColor QGCustomText::getSelectColor () virtual
Definition at line 255 of file QGCustomText.cpp.
References TechDrawGui::PreferencesGui::selectQColor().
Referenced by setPrettySel().
getWidth()
double QGCustomText::getWidth () virtual
Definition at line 112 of file QGCustomText.cpp.
hoverEnterEvent()
void QGCustomText::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override protected
Definition at line 130 of file QGCustomText.cpp.
References setPrettyPre().
Referenced by TechDrawGui::QGMText::hoverEnterEvent().
hoverLeaveEvent()
void QGCustomText::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override protected
Definition at line 138 of file QGCustomText.cpp.
References setPrettyNormal().
Referenced by TechDrawGui::QGMText::hoverLeaveEvent().
itemChange()
QVariant QGCustomText::itemChange (GraphicsItemChange change, const QVariant & value) override protected
Definition at line 116 of file QGCustomText.cpp.
References setPrettyNormal(), and setPrettySel().
Referenced by TechDrawGui::QGMText::itemChange().
justifyLeftAt() [1/2]
void QGCustomText::justifyLeftAt (double cX, double cY, bool vCenter = true) virtual
Definition at line 78 of file QGCustomText.cpp.
References MengerSponge::box.
justifyLeftAt() [2/2]
void QGCustomText::justifyLeftAt (QPointF centerPos, bool vCenter = true) virtual
Definition at line 73 of file QGCustomText.cpp.
Referenced by TechDrawGui::QGITile::makeText(), and TechDrawGui::QGIDatumLabel::setPosFromCenter().
justifyRightAt() [1/2]
void QGCustomText::justifyRightAt (double cX, double cY, bool vCenter = true) virtual
Definition at line 94 of file QGCustomText.cpp.
References MengerSponge::box.
justifyRightAt() [2/2]
void QGCustomText::justifyRightAt (QPointF centerPos, bool vCenter = true) virtual
Definition at line 89 of file QGCustomText.cpp.
Referenced by TechDrawGui::QGITile::makeText().
makeMark() [1/2]
void QGCustomText::makeMark (Base::Vector3d v)
Definition at line 275 of file QGCustomText.cpp.
References makeMark(), and TestSpreadsheet::v.
makeMark() [2/2]
void QGCustomText::makeMark (double x, double y)
Definition at line 265 of file QGCustomText.cpp.
References TechDrawGui::QGICMark::setSize(), TechDrawGui::QGICMark::setThick(), ZVALUE::VERTEX, MovieTool::x, and MovieTool::y.
Referenced by makeMark().
paint()
void QGCustomText::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 176 of file QGCustomText.cpp.
Referenced by TechDrawGui::QGMText::paint().
setColor()
void QGCustomText::setColor (QColor c) virtual
Definition at line 164 of file QGCustomText.cpp.
References SCL.SimpleDataTypes::c, m_colCurrent, and m_colNormal.
Referenced by TechDrawGui::QGIWeldSymbol::drawTailText(), TechDrawGui::QGITile::makeText(), TechDrawGui::QGIDatumLabel::setColor(), TechDrawGui::QGITile::setPrettyNormal(), TechDrawGui::QGIWeldSymbol::setPrettyNormal(), TechDrawGui::QGITile::setPrettyPre(), TechDrawGui::QGIWeldSymbol::setPrettyPre(), TechDrawGui::QGITile::setPrettySel(), and TechDrawGui::QGIWeldSymbol::setPrettySel().
setHighlighted()
void TechDrawGui::QGCustomText::setHighlighted (bool state)
setPrettyNormal()
void QGCustomText::setPrettyNormal () virtual
Reimplemented in TechDrawGui::QGMText.
Definition at line 146 of file QGCustomText.cpp.
References m_colCurrent, and m_colNormal.
Referenced by hoverLeaveEvent(), itemChange(), TechDrawGui::QGMText::setPrettyNormal(), TechDrawGui::QGIWeldSymbol::setPrettyNormal(), and TechDrawGui::QGIDatumLabel::setPrettyNormal().
setPrettyPre()
void QGCustomText::setPrettyPre () virtual
Reimplemented in TechDrawGui::QGMText.
Definition at line 152 of file QGCustomText.cpp.
References getPreColor(), and m_colCurrent.
Referenced by hoverEnterEvent(), TechDrawGui::QGMText::setPrettyPre(), TechDrawGui::QGIWeldSymbol::setPrettyPre(), and TechDrawGui::QGIDatumLabel::setPrettyPre().
setPrettySel()
void QGCustomText::setPrettySel () virtual
Reimplemented in TechDrawGui::QGMText.
Definition at line 158 of file QGCustomText.cpp.
References getSelectColor(), and m_colCurrent.
Referenced by itemChange(), TechDrawGui::QGMText::setPrettySel(), TechDrawGui::QGIWeldSymbol::setPrettySel(), and TechDrawGui::QGIDatumLabel::setPrettySel().
setTightBounding()
void QGCustomText::setTightBounding (bool tight) virtual
Definition at line 171 of file QGCustomText.cpp.
References tightBounding.
Referenced by TechDrawGui::QGIDatumLabel::QGIDatumLabel(), and TechDrawGui::QGIBalloonLabel::setDimText().
tightBoundingAdjust()
QPointF QGCustomText::tightBoundingAdjust () const
Definition at line 215 of file QGCustomText.cpp.
References tightBoundingRect().
Referenced by TechDrawGui::QGIHighlight::makeReference(), and TechDrawGui::QGIDatumLabel::setPosFromCenter().
tightBoundingRect()
QRectF QGCustomText::tightBoundingRect () const
Definition at line 186 of file QGCustomText.cpp.
References result.
Referenced by alignmentRect(), and tightBoundingAdjust().
type()
int TechDrawGui::QGCustomText::type () const inline override
Definition at line 50 of file QGCustomText.h.
Member Data Documentation
isHighlighted
bool TechDrawGui::QGCustomText::isHighlighted protected
Definition at line 90 of file QGCustomText.h.
m_colCurrent
QColor TechDrawGui::QGCustomText::m_colCurrent protected
Definition at line 92 of file QGCustomText.h.
Referenced by QGCustomText(), setColor(), setPrettyNormal(), setPrettyPre(), and setPrettySel().
m_colNormal
QColor TechDrawGui::QGCustomText::m_colNormal protected
Definition at line 93 of file QGCustomText.h.
Referenced by QGCustomText(), setColor(), and setPrettyNormal().
tightBounding
bool TechDrawGui::QGCustomText::tightBounding protected
Definition at line 91 of file QGCustomText.h.
Referenced by alignmentRect(), QGCustomText(), and setTightBounding().
The documentation for this class was generated from the following files:
QGCustomText.h
QGCustomText.cpp