FreeCAD: GCS::Parabola Class Reference
GCS::Parabola Class Reference
#include <Geo.h>
Public Member Functions
Parabola ()
~Parabola () override
DeriVector2 CalculateNormal (const Point &p, const double *derivparam=nullptr) const override
DeriVector2 Value (double u, double du, const double *derivparam=nullptr) const override
Value: returns point (vector) given the value of parameter.
int PushOwnParams (VEC_pD &pvec) override
void ReconstructOnNewPvec (VEC_pD &pvec, int &cnt) override
Parabola * Copy () override
Public Member Functions inherited from GCS::Curve
virtual ~Curve ()
virtual DeriVector2 CalculateNormal (const double *param, const double *derivparam=nullptr) const
Public Attributes
Point vertex
Point focus1
Detailed Description
Definition at line 388 of file Geo.h.
Constructor & Destructor Documentation
Parabola()
GCS::Parabola::Parabola () inline
Definition at line 391 of file Geo.h.
Referenced by Copy().
~Parabola()
GCS::Parabola::~Parabola () inline override
Definition at line 393 of file Geo.h.
Member Function Documentation
CalculateNormal()
DeriVector2 GCS::Parabola::CalculateNormal (const Point & p, const double * derivparam = nullptr) const override virtual
Implements GCS::Curve.
Definition at line 609 of file Geo.cpp.
References focus1, GCS::DeriVector2::getNormalized(), buildPsets::p, GCS::DeriVector2::subtr(), and vertex.
Copy()
Parabola * GCS::Parabola::Copy () override virtual
Implements GCS::Curve.
Reimplemented in GCS::ArcOfParabola.
Definition at line 682 of file Geo.cpp.
References Parabola().
PushOwnParams()
int GCS::Parabola::PushOwnParams (VEC_pD & pvec) override virtual
Implements GCS::Curve.
Reimplemented in GCS::ArcOfParabola.
Definition at line 656 of file Geo.cpp.
References focus1, vertex, GCS::Point::x, and GCS::Point::y.
Referenced by GCS::ArcOfParabola::PushOwnParams().
ReconstructOnNewPvec()
void GCS::Parabola::ReconstructOnNewPvec (VEC_pD & pvec, int & cnt) override virtual
Implements GCS::Curve.
Reimplemented in GCS::ArcOfParabola.
Definition at line 670 of file Geo.cpp.
References focus1, vertex, GCS::Point::x, and GCS::Point::y.
Referenced by GCS::ArcOfParabola::ReconstructOnNewPvec().
Value()
DeriVector2 GCS::Parabola::Value (double u, double du, const double * derivparam = nullptr) const override virtual
Value: returns point (vector) given the value of parameter.
Parameters
u value of parameter
du derivative of parameter by derivparam
derivparam pointer to sketch parameter to calculate the derivative for
Returns
Reimplemented from GCS::Curve.
Definition at line 626 of file Geo.cpp.
References SCL.SimpleDataTypes::c, GCS::DeriVector2::divD(), SCL.SimpleDataTypes::f, focus1, GCS::DeriVector2::getNormalized(), GCS::DeriVector2::length(), GCS::DeriVector2::multD(), GCS::DeriVector2::rotate90ccw(), GCS::DeriVector2::subtr(), GCS::DeriVector2::sum(), buildPsets::u, and vertex.
Member Data Documentation
focus1
Point GCS::Parabola::focus1
Definition at line 396 of file Geo.h.
Referenced by CalculateNormal(), PushOwnParams(), ReconstructOnNewPvec(), and Value().
vertex
Point GCS::Parabola::vertex
Definition at line 395 of file Geo.h.
Referenced by TechDrawTools.TaskAddOffsetVertex.TaskAddOffsetVertex::accept(), CalculateNormal(), PushOwnParams(), ReconstructOnNewPvec(), and Value().
The documentation for this class was generated from the following files:
Geo.h
Geo.cpp