FreeCAD: Sketcher Namespace Reference
Sketcher Namespace Reference
a class for establishing our connection with the unified measurement facility
Namespaces
GeometryMode
InternalType
Classes
class Constraint
struct Constraint_Equal
struct ConstraintIds
class ExternalGeometryExtension
class ExternalGeometryFacade
struct ExternalToAdd
class GeoElementId
Struct for storing a {GeoId, PointPos} pair.
class GeoListModel
Class for managing internal and external geometry as a single object.
class GeometryFacade
This class is a Facade to handle geometry and sketcher geometry extensions with a single sketcher specific interface.
class GeometryTypedFacade
It provides all the functionality of GeometryFacade (derives from it), but in addition allows one to indicate the type of a Part::Geometry derived class.
class ISketchExternalGeometryExtension
class ISketchGeometryExtension
class Measure
class Module
class PropertyConstraintList
class PythonConverter
Class for generating python code.
class Sketch
class SketchAnalysis
class SketchGeometryExtension
class SketchObject
class SketchObjectSF
class SolverGeometryExtension
Typedefs
using GeometryPtr = Part::Geometry *
using GeometryFacadeUniquePtr = std::unique_ptr< const Sketcher::GeometryFacade >
using GeoList = GeoListModel< GeometryPtr >
using GeoListFacade = GeoListModel< GeometryFacadeUniquePtr >
using SketchObjectPython = App::FeaturePythonT< SketchObject >
Enumerations
enum ConstraintType : int {
None = 0, Coincident = 1, Horizontal = 2, Vertical = 3,
Parallel = 4, Tangent = 5, Distance = 6, DistanceX = 7,
DistanceY = 8, Angle = 9, Perpendicular = 10, Radius = 11,
Equal = 12, PointOnObject = 13, Symmetric = 14, InternalAlignment = 15,
SnellsLaw = 16, Block = 17, Diameter = 18, Weight = 19,
NumConstraintTypes
}
enum InternalAlignmentType {
Undef = 0, EllipseMajorDiameter = 1, EllipseMinorDiameter = 2, EllipseFocus1 = 3,
EllipseFocus2 = 4, HyperbolaMajor = 5, HyperbolaMinor = 6, HyperbolaFocus = 7,
ParabolaFocus = 8, BSplineControlPoint = 9, BSplineKnotPoint = 10, ParabolaFocalAxis = 11,
NumInternalAlignmentType
}
enum GeoEnum {
RtPnt = -1, HAxis = -1, VAxis = -2, RefExt = -3,
GeoUndef = -2000
}
Sketcher Geometry is identified with an index called GeoId.
enum PointPos : int { PointPos::none = 0, PointPos::start = 1, PointPos::end = 2, PointPos::mid = 3 }
PointPos lets us refer to different aspects of a piece of geometry.
enum Solver { Solver::RedundantConstraints = -2, Solver::ConflictingConstraints = -3, Solver::OverConstrained = -4 }
enum ExtType { ExtType::Projection, ExtType::Intersection, ExtType::Both }
Functions
PyObject * initModule ()
GeoListFacade getGeoListFacade (const GeoList &geolist)
bool isCircle (const Part::Geometry &)
bool isArcOfCircle (const Part::Geometry &)
bool isEllipse (const Part::Geometry &)
bool isArcOfEllipse (const Part::Geometry &)
bool isLineSegment (const Part::Geometry &)
bool isArcOfHyperbola (const Part::Geometry &)
bool isArcOfParabola (const Part::Geometry &)
bool isBSplineCurve (const Part::Geometry &)
bool isPeriodicBSplineCurve (const Part::Geometry &)
bool isPoint (const Part::Geometry &)
bool isCircleOrArc (const Part::Geometry &geo)
std::tuple< double, Base::Vector3d > getRadiusCenterCircleArc (const Part::Geometry *geo)
Detailed Description
a class for establishing our connection with the unified measurement facility
Typedef Documentation
GeoList
using Sketcher::GeoList = typedef GeoListModel<GeometryPtr>
Definition at line 265 of file GeoList.h.
GeoListFacade
using Sketcher::GeoListFacade = typedef GeoListModel<GeometryFacadeUniquePtr>
Definition at line 266 of file GeoList.h.
GeometryFacadeUniquePtr
using Sketcher::GeometryFacadeUniquePtr = typedef std::unique_ptr<const Sketcher::GeometryFacade>
Definition at line 263 of file GeoList.h.
GeometryPtr
using Sketcher::GeometryPtr = typedef Part::Geometry*
Definition at line 262 of file GeoList.h.
SketchObjectPython
using Sketcher::SketchObjectPython = typedef App::FeaturePythonT<SketchObject>
Definition at line 1142 of file SketchObject.h.
Enumeration Type Documentation
ConstraintType
enum Sketcher::ConstraintType : int
Important note: New constraint types must be always added at the end but before 'NumConstraintTypes'. This is mandatory in order to keep the handling of constraint types upward compatible which means that this program version ignores later introduced constraint types when reading them from a project file.
Enumerator
None
Coincident
Horizontal
Vertical
Parallel
Tangent
Distance
DistanceX
DistanceY
Angle
Perpendicular
Radius
Equal
PointOnObject
Symmetric
InternalAlignment
SnellsLaw
Block
Diameter
Weight
NumConstraintTypes
Definition at line 64 of file Constraint.h.
ExtType
enum Sketcher::ExtType strong
Enumerator
Projection
Intersection
Both
Definition at line 76 of file SketchObject.h.
GeoEnum
enum Sketcher::GeoEnum
Sketcher Geometry is identified with an index called GeoId.
GeoId >= 0 are normal geometry elements GeoId = -1 and -2 are the Horizontal and Vertical axes and the root point GeoId <= -2 are external geometry elements GeoId = -2000 is an undefined or unused geometry id
GeoEnum struct provides convenience labels for these GeoIds.
However, GeoEnum is not enough to define an element of a Geometry. The most straightforward example is the RootPoint and the Horizontal Axis. Both have the same GeoId (= -1).
The same happens for elements of a given geometry. For example, a line has a starting point, an endpoint and an edge. All these share the same GeoId, as the GeoId identifies a geometry and not an element of a geometry.
The elements of a given geometry are identified by the PointPos enum. In the case of the root point, it is considered to be the start point of the Horizontal Axis, this is a convention.
Therefore, a geometry element (GeoElementId) is univocally defined by the combination of a GeoId and a PointPos.
Geometry shapes having more or different elements than those supported by the PointPos struct, such as conics, in particular an arc of ellipse, are called complex geometries. The extra elements of complex geometries are actual separate geometries (focus of an ellipse, line defining the major axis of an ellipse, circle representing the weight of a BSpline), and they are call InternalAlignment geometries.
For Geometry lists, refer to GeoListModel template.
Enumerator
RtPnt
HAxis
VAxis
RefExt
GeoUndef
Definition at line 85 of file GeoEnum.h.
InternalAlignmentType
enum Sketcher::InternalAlignmentType
Enumerator
Undef
EllipseMajorDiameter
EllipseMinorDiameter
EllipseFocus1
EllipseFocus2
HyperbolaMajor
HyperbolaMinor
HyperbolaFocus
ParabolaFocus
BSplineControlPoint
BSplineKnotPoint
ParabolaFocalAxis
NumInternalAlignmentType
Definition at line 89 of file Constraint.h.
PointPos
enum Sketcher::PointPos : int strong
PointPos lets us refer to different aspects of a piece of geometry.
sketcher::none refers to an edge itself (eg., for a Perpendicular constraint on two lines). sketcher::start and sketcher::end denote the endpoints of lines or bounded curves. Sketcher::mid denotes geometries with geometrical centers (eg., circle, ellipse). Bare points use 'start'. More complex geometries like parabola focus or b-spline knots use InternalAlignment constraints in addition to PointPos.
Enumerator
none
start
end
mid
Definition at line 102 of file GeoEnum.h.
Solver
enum Sketcher::Solver strong
Enumerator
RedundantConstraints
ConflictingConstraints
OverConstrained
Definition at line 64 of file SketchAnalysis.h.
Function Documentation
getGeoListFacade()
GeoListFacade Sketcher::getGeoListFacade (const GeoList & geolist)
Definition at line 436 of file GeoList.cpp.
References Sketcher::GeoListModel< T >::geomlist, Sketcher::GeoListModel< T >::getInternalCount(), and Path.Post.scripts.opensbp_post::move().
getRadiusCenterCircleArc()
std::tuple< double, Base::Vector3d > Sketcher::getRadiusCenterCircleArc (const Part::Geometry * geo)
Definition at line 109 of file Sketcher/Gui/Utils.cpp.
References isArcOfCircle(), TechDraw::isCircle, and THROWM.
Referenced by CmdSketcherConstrainDistance::activated(), SketcherGui::GetCirclesMinimalDistance(), and SketcherGui::EditModeConstraintCoinManager::processConstraints().
initModule()
PyObject* Sketcher::initModule ()
Definition at line 62 of file AppAssemblyPy.cpp.
References Base::InterpreterSingleton::addModule(), and Base::Interpreter().
Referenced by PyMOD_INIT_FUNC().
isArcOfCircle()
bool Sketcher::isArcOfCircle (const Part::Geometry & geom)
Definition at line 55 of file Sketcher/Gui/Utils.cpp.
References Base::BaseClass::is().
Referenced by CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadiam::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainRadiam::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), DrawSketchHandlerDimension::createArcAngleConstrain(), DrawSketchHandlerDimension::createArcLengthConstrain(), DrawSketchHandlerDimension::createDistanceConstrain(), DrawSketchHandlerDimension::createEqualityConstrain(), DrawSketchHandlerDimension::createRadiusDiameterConstrain(), getRadiusCenterCircleArc(), isCircleOrArc(), isGeoConcentricCompatible(), DrawSketchHandlerDimension::isRadiusDoF(), DrawSketchHandlerDimension::makeCts_1Circle(), SketcherGui::makeTangentToArcOfEllipseviaNewPoint(), SketcherGui::makeTangentToArcOfHyperbolaviaNewPoint(), SketcherGui::makeTangentToArcOfParabolaviaNewPoint(), SketcherGui::makeTangentToEllipseviaNewPoint(), and SketcherGui::EditModeConstraintCoinManager::processConstraints().
isArcOfEllipse()
bool Sketcher::isArcOfEllipse (const Part::Geometry & geom)
Definition at line 65 of file Sketcher/Gui/Utils.cpp.
References Base::BaseClass::is().
Referenced by CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), DrawSketchHandlerDimension::createEqualityConstrain(), getListOfSelectedGeoIds(), isGeoConcentricCompatible(), SketcherGui::makeTangentToArcOfEllipseviaNewPoint(), SketcherGui::makeTangentToArcOfHyperbolaviaNewPoint(), SketcherGui::makeTangentToArcOfParabolaviaNewPoint(), and SketcherGui::makeTangentToEllipseviaNewPoint().
isArcOfHyperbola()
bool Sketcher::isArcOfHyperbola (const Part::Geometry & geom)
Definition at line 75 of file Sketcher/Gui/Utils.cpp.
References Base::BaseClass::is().
Referenced by CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), DrawSketchHandlerDimension::createEqualityConstrain(), getListOfSelectedGeoIds(), SketcherGui::makeTangentToArcOfHyperbolaviaNewPoint(), and SketcherGui::makeTangentToArcOfParabolaviaNewPoint().
isArcOfParabola()
bool Sketcher::isArcOfParabola (const Part::Geometry & geom)
Definition at line 80 of file Sketcher/Gui/Utils.cpp.
References Base::BaseClass::is().
Referenced by CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), DrawSketchHandlerDimension::createEqualityConstrain(), getListOfSelectedGeoIds(), and SketcherGui::makeTangentToArcOfParabolaviaNewPoint().
isBSplineCurve()
bool Sketcher::isBSplineCurve (const Part::Geometry & geom)
Definition at line 85 of file Sketcher/Gui/Utils.cpp.
References Base::BaseClass::is().
Referenced by CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), SketcherGui::doEndpointTangency(), getListOfSelectedGeoIds(), and removeRedundantPointOnObject().
isCircle()
bool Sketcher::isCircle (const Part::Geometry & geom)
Definition at line 50 of file Sketcher/Gui/Utils.cpp.
References Base::BaseClass::is().
isCircleOrArc()
bool Sketcher::isCircleOrArc (const Part::Geometry & geo)
Definition at line 104 of file Sketcher/Gui/Utils.cpp.
References isArcOfCircle(), and TechDraw::isCircle.
Referenced by CmdSketcherConstrainDistance::activated(), and SketcherGui::EditModeConstraintCoinManager::processConstraints().
isEllipse()
bool Sketcher::isEllipse (const Part::Geometry & geom)
Definition at line 60 of file Sketcher/Gui/Utils.cpp.
References Base::BaseClass::is().
isLineSegment()
bool Sketcher::isLineSegment (const Part::Geometry & geom)
Definition at line 70 of file Sketcher/Gui/Utils.cpp.
References Base::BaseClass::is().
Referenced by CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), CmdSketcherConstrainDistance::applyConstraint(), CmdSketcherConstrainDistanceX::applyConstraint(), CmdSketcherConstrainDistanceY::applyConstraint(), CmdSketcherConstrainParallel::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), DrawSketchHandlerDimension::createDistanceConstrain(), DrawSketchHandlerDimension::createEqualityConstrain(), DrawSketchHandlerDimension::createSymmetryConstrain(), SketcherGui::ViewProviderSketch::generateContextMenu(), horVerActivated(), horVerApplyConstraint(), SketcherGui::makeTangentToArcOfHyperbolaviaNewPoint(), SketcherGui::makeTangentToArcOfParabolaviaNewPoint(), and SketcherGui::EditModeConstraintCoinManager::processConstraints().
isPeriodicBSplineCurve()
bool Sketcher::isPeriodicBSplineCurve (const Part::Geometry & geom)
Definition at line 90 of file Sketcher/Gui/Utils.cpp.
References Base::BaseClass::is(), and Part::GeomBSplineCurve::isPeriodic().
Referenced by SketcherGui::ViewProviderSketch::toggleWireSelelection().
isPoint()
bool Sketcher::isPoint (const Part::Geometry & geom)
Definition at line 99 of file Sketcher/Gui/Utils.cpp.
References Base::BaseClass::is().
Referenced by getListOfSelectedGeoIds(), and SketcherGui::ViewProviderSketch::toggleWireSelelection().