FreeCAD: TechDrawGui::QGCustomRect Class Reference
TechDrawGui::QGCustomRect Class Reference
#include <QGCustomRect.h>
Public Types
enum { Type = QGraphicsItem::UserType + 133 }
Public Member Functions
QGCustomRect ()
~QGCustomRect () override=default
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
virtual void centerAt (QPointF centerPos)
virtual void centerAt (double cX, double cY)
Detailed Description
Definition at line 40 of file QGCustomRect.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 46 of file QGCustomRect.h.
Constructor & Destructor Documentation
QGCustomRect()
QGCustomRect::QGCustomRect () explicit
Definition at line 37 of file QGCustomRect.cpp.
~QGCustomRect()
TechDrawGui::QGCustomRect::~QGCustomRect () override default
Member Function Documentation
centerAt() [1/2]
void QGCustomRect::centerAt (double cX, double cY) virtual
Definition at line 50 of file QGCustomRect.cpp.
References MengerSponge::box.
centerAt() [2/2]
void QGCustomRect::centerAt (QPointF centerPos) virtual
Definition at line 45 of file QGCustomRect.cpp.
Referenced by TechDrawGui::QGIFace::buildSvgHatch(), TechDrawGui::QGIRichAnno::QGIRichAnno(), and TechDrawGui::QGIRichAnno::updateView().
paint()
void QGCustomRect::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 61 of file QGCustomRect.cpp.
type()
int TechDrawGui::QGCustomRect::type () const inline override
Definition at line 47 of file QGCustomRect.h.
The documentation for this class was generated from the following files:
QGCustomRect.h
QGCustomRect.cpp