FreeCAD: CAMTests.TestPathDressupDogbone.TestDressupDogbone Class Reference
CAMTests.TestPathDressupDogbone.TestDressupDogbone Class Reference
Public Member Functions
def formatBone (self, bone)
def test00 (self)
def test01 (self)
def test02 (self)
def test03 (self)
def test04 (self)
def test05 (self)
Public Member Functions inherited from CAMTests.PathTestUtils.PathTestBase
def assertRoughly (self, f1, f2, error=0.00001)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertPlacement (self, p1, p2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertArc (self, edge, pt1, pt2, direction="CW")
def assertCircle (self, edge, pt, r)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCommandEqual (self, c1, c2)
def assertEqualLocale (self, s1, s2)
def assertEdgeShapesMatch (self, e1, e2)
def assertPointsMatch (self, pts0, pts1)
def assertSuccessfulRecompute (self, doc, *objs, msg=None)
Detailed Description
Unit tests for the Dogbone dressup.
Definition at line 52 of file TestPathDressupDogbone.py.
Member Function Documentation
formatBone()
def CAMTests.TestPathDressupDogbone.TestDressupDogbone.formatBone (self, bone)
Definition at line 55 of file TestPathDressupDogbone.py.
Referenced by CAMTests.TestPathDressupDogbone.TestDressupDogbone.test00(), CAMTests.TestPathDressupDogbone.TestDressupDogbone.test01(), CAMTests.TestPathDressupDogbone.TestDressupDogbone.test04(), and CAMTests.TestPathDressupDogbone.TestDressupDogbone.test05().
test00()
def CAMTests.TestPathDressupDogbone.TestDressupDogbone.test00 (self)
Verify bones are inserted for simple moves.
Definition at line 58 of file TestPathDressupDogbone.py.
References CAMTests.TestPathDressupDogbone.TestDressupDogbone.formatBone().
Referenced by CAMTests.TestPathToolController.TestPathToolController.test01().
test01()
def CAMTests.TestPathDressupDogbone.TestDressupDogbone.test01 (self)
Verify bones are inserted if hole ends with rapid move out.
Definition at line 83 of file TestPathDressupDogbone.py.
References CAMTests.TestPathDressupDogbone.TestDressupDogbone.formatBone().
test02()
def CAMTests.TestPathDressupDogbone.TestDressupDogbone.test02 (self)
Verify bones are correctly generated for a Profile.
Definition at line 108 of file TestPathDressupDogbone.py.
test03()
def CAMTests.TestPathDressupDogbone.TestDressupDogbone.test03 (self)
Verify no bone is inserted for straight move interrupted by plunge.
Definition at line 174 of file TestPathDressupDogbone.py.
test04()
def CAMTests.TestPathDressupDogbone.TestDressupDogbone.test04 (self)
Verify can handle comments between moves
Definition at line 196 of file TestPathDressupDogbone.py.
References CAMTests.TestPathDressupDogbone.TestDressupDogbone.formatBone().
test05()
def CAMTests.TestPathDressupDogbone.TestDressupDogbone.test05 (self)
Verify can handle noops between moves
Definition at line 245 of file TestPathDressupDogbone.py.
References CAMTests.TestPathDressupDogbone.TestDressupDogbone.formatBone().
The documentation for this class was generated from the following file:
TestPathDressupDogbone.py