FreeCAD: Gui::ControlSingleton Class Reference
Gui::ControlSingleton Class Reference
#include <Control.h>
Public Member Functions
dialog handling
These methods are used to control the TaskDialog stuff.
void showDialog (Gui::TaskView::TaskDialog *dlg)
This method starts a task dialog in the task view.
Gui::TaskView::TaskDialog * activeDialog () const
Static Public Member Functions
static ControlSingleton & instance ()
static void destruct ()
task view handling
Gui::TaskView::TaskView * taskPanel () const
void showModelView ()
raising the model view
bool isAllowedAlterDocument () const
bool isAllowedAlterView () const
bool isAllowedAlterSelection () const
void accept ()
void reject ()
void closeDialog ()
void showTaskView ()
raises the task view panel
Detailed Description
The control class
Definition at line 55 of file Control.h.
Member Function Documentation
accept
void ControlSingleton::accept () slot
Definition at line 201 of file Control.cpp.
References Gui::TaskView::TaskView::accept().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
activeDialog()
Gui::TaskView::TaskDialog * ControlSingleton::activeDialog () const
Definition at line 196 of file Control.cpp.
Referenced by Gui::TaskView::ControlPy::activeDialog(), Gui::TaskView::ControlPy::activeTaskDialog(), Gui::Document::canClose(), PartGui::ViewProviderPartExt::changeFaceAppearances(), StdCmdEdit::isActive(), StdCmdTextureMapping::isActive(), TechDrawGui::ViewProviderDimension::onDelete(), PartGui::PropertyEnumAttacherItem::openTask(), prepareProfileBased(), Gui::DocumentP::setDocumentNameOfTaskDialog(), SurfaceGui::ViewProviderGeomFillSurface::setEdit(), TechDrawGui::ViewProviderGeomHatch::setEdit(), SurfaceGui::ViewProviderSections::setEdit(), SurfaceGui::ViewProviderFilling::setEdit(), PartDesignGui::ViewProviderShapeBinder::setEdit(), PartDesignGui::ViewProviderHole::setEdit(), PartDesignGui::ViewProviderPrimitive::setEdit(), TechDrawGui::ViewProviderProjGroup::setEdit(), PartDesignGui::ViewProviderBoolean::setEdit(), FemGui::ViewProviderFemPostObject::setEdit(), PartDesignGui::ViewProvider::setEdit(), PartDesignGui::ViewProviderDatum::setEdit(), FemGui::ViewProviderFemPostFunction::setEdit(), PartGui::ViewProviderOffset::setEdit(), PartGui::ViewProviderThickness::setEdit(), Gui::ViewProviderLink::setEdit(), SketcherGui::ViewProviderSketch::setEdit(), PartGui::ViewProviderAttachExtension::showAttachmentEditor(), and Gui::TaskView::ControlPy::showDialog().
closeDialog
void ControlSingleton::closeDialog () slot
Definition at line 221 of file Control.cpp.
References Gui::TaskView::TaskView::removeDialog().
Referenced by Gui::TaskMeasure::close(), Gui::TaskView::ControlPy::closeDialog(), TechDrawGui::TaskSectionView::failNoObject(), TechDrawGui::TaskComplexSection::failNoObject(), prepareProfileBased(), FemGui::ViewProviderFemConstraintPressure::setEdit(), FemGui::ViewProviderFemConstraintRigidBody::setEdit(), FemGui::ViewProviderFemConstraintSpring::setEdit(), FemGui::ViewProviderFemConstraintPulley::setEdit(), FemGui::ViewProviderFemConstraintBearing::setEdit(), PartDesignGui::ViewProviderHole::setEdit(), PartDesignGui::ViewProviderPrimitive::setEdit(), FemGui::ViewProviderFemConstraintGear::setEdit(), FemGui::ViewProviderFemConstraintFixed::setEdit(), FemGui::ViewProviderFemConstraintFluidBoundary::setEdit(), FemGui::ViewProviderFemConstraintForce::setEdit(), FemGui::ViewProviderFemConstraintPlaneRotation::setEdit(), FemGui::ViewProviderFemConstraintContact::setEdit(), FemGui::ViewProviderFemConstraintTemperature::setEdit(), FemGui::ViewProviderFemConstraintDisplacement::setEdit(), FemGui::ViewProviderFemConstraintHeatflux::setEdit(), FemGui::ViewProviderFemConstraintInitialTemperature::setEdit(), FemGui::ViewProviderFemConstraintTransform::setEdit(), PartDesignGui::ViewProviderBoolean::setEdit(), PartDesignGui::ViewProviderDatum::setEdit(), PartGui::ViewProviderOffset::setEdit(), PartGui::ViewProviderThickness::setEdit(), SketcherGui::ViewProviderSketch::setEdit(), PartGui::ViewProviderAttachExtension::showAttachmentEditor(), PartGui::FaceAppearances::slotDeleteDocument(), Gui::ElementColors::slotDeleteDocument(), PartDesignGui::TaskFeaturePick::slotDeleteDocument(), PartGui::FaceAppearances::slotDeleteObject(), Gui::ElementColors::slotDeleteObject(), PartGui::FaceAppearances::slotUndoDocument(), PartDesignGui::TaskFeaturePick::slotUndoDocument(), SurfaceGui::ViewProviderGeomFillSurface::unsetEdit(), SurfaceGui::ViewProviderSections::unsetEdit(), RobotGui::ViewProviderTrajectoryCompound::unsetEdit(), RobotGui::ViewProviderTrajectoryDressUp::unsetEdit(), PathGui::ViewProviderPathCompound::unsetEdit(), PartGui::ViewProviderProjectOnSurface::unsetEdit(), PartGui::ViewProviderPrimitive::unsetEdit(), FemGui::ViewProviderFemConstraint::unsetEdit(), TechDrawGui::ViewProviderProjGroupItem::unsetEdit(), PartGui::ViewProviderFillet::unsetEdit(), Gui::ViewProviderDragger::unsetEdit(), FemGui::ViewProviderFemPostObject::unsetEdit(), PartDesignGui::ViewProvider::unsetEdit(), PartGui::ViewProviderChamfer::unsetEdit(), PartDesignGui::ViewProviderDatum::unsetEdit(), FemGui::ViewProviderFemAnalysis::unsetEdit(), FemGui::ViewProviderFemPostFunction::unsetEdit(), PartGui::ViewProviderOffset::unsetEdit(), PartGui::ViewProviderThickness::unsetEdit(), and SketcherGui::ViewProviderSketch::unsetEdit().
destruct()
void ControlSingleton::destruct () static
Definition at line 275 of file Control.cpp.
instance()
ControlSingleton & ControlSingleton::instance () static
Definition at line 268 of file Control.cpp.
Referenced by Gui::Control().
isAllowedAlterDocument()
bool ControlSingleton::isAllowedAlterDocument () const
If a task dialog is open then it indicates whether this task dialog allows other commands to modify the document while it is open. If no task dialog is open true is returned.
Definition at line 244 of file Control.cpp.
Referenced by Gui::TaskView::ControlPy::isAllowedAlterDocument().
isAllowedAlterSelection()
bool ControlSingleton::isAllowedAlterSelection () const
If a task dialog is open then it indicates whether this task dialog allows other commands to modify the selection while it is open. If no task dialog is open true is returned.
Definition at line 259 of file Control.cpp.
Referenced by Gui::TaskView::ControlPy::isAllowedAlterSelection().
isAllowedAlterView()
bool ControlSingleton::isAllowedAlterView () const
If a task dialog is open then it indicates whether this task dialog allows other commands to modify the 3d view while it is open. If no task dialog is open true is returned.
Definition at line 252 of file Control.cpp.
Referenced by Gui::TaskView::ControlPy::isAllowedAlterView().
reject
void ControlSingleton::reject () slot
Definition at line 211 of file Control.cpp.
References Gui::TaskView::TaskView::reject().
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), PartDesignGui::ViewProviderShapeBinder::setEdit(), FemGui::ViewProviderFemPostObject::setEdit(), PartDesignGui::ViewProvider::setEdit(), FemGui::ViewProviderFemPostFunction::setEdit(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
showDialog()
void ControlSingleton::showDialog (Gui::TaskView::TaskDialog * dlg)
This method starts a task dialog in the task view.
Definition at line 152 of file Control.cpp.
References draftgeoutils.intersections::connect(), App::AutoTransaction::setEnable(), and Gui::TaskView::TaskView::showDialog().
Referenced by StdCmdTransform::activated(), StdCmdPlacement::activated(), StdCmdTextureMapping::activated(), PartGui::ViewProviderPartExt::changeFaceAppearances(), FemGui::ViewProviderSetNodes::doubleClicked(), RobotGui::ViewProviderEdge2TracObject::doubleClicked(), FemGui::ViewProviderSetElementNodes::doubleClicked(), exec2LineCenterLine(), exec2PointCenterLine(), execCenterLine(), execComplexSection(), execCosmeticCircle(), execCosmeticVertex(), execLine2Points(), execSimpleSection(), TechDrawGui::QGIEdge::mouseDoubleClickEvent(), PartGui::PropertyEnumAttacherItem::openTask(), prepareProfileBased(), SurfaceGui::ViewProviderGeomFillSurface::setEdit(), TechDrawGui::ViewProviderGeomHatch::setEdit(), TechDrawGui::ViewProviderHatch::setEdit(), SurfaceGui::ViewProviderSections::setEdit(), TechDrawGui::ViewProviderLeader::setEdit(), SurfaceGui::ViewProviderFilling::setEdit(), FemGui::ViewProviderSetNodes::setEdit(), RobotGui::ViewProviderEdge2TracObject::setEdit(), RobotGui::ViewProviderTrajectoryCompound::setEdit(), RobotGui::ViewProviderTrajectoryDressUp::setEdit(), PartDesignGui::ViewProviderShapeBinder::setEdit(), FemGui::ViewProviderFemConstraintPressure::setEdit(), FemGui::ViewProviderFemConstraintRigidBody::setEdit(), FemGui::ViewProviderFemConstraintSpring::setEdit(), PathGui::ViewProviderPathCompound::setEdit(), FemGui::ViewProviderFemMeshShapeNetgen::setEdit(), PartGui::ViewProviderPrimitive::setEdit(), PartGui::ViewProviderProjectOnSurface::setEdit(), FemGui::ViewProviderFemConstraintGear::setEdit(), FemGui::ViewProviderFemConstraintPulley::setEdit(), PartDesignGui::ViewProviderHole::setEdit(), FemGui::ViewProviderFemConstraintBearing::setEdit(), PartDesignGui::ViewProviderPrimitive::setEdit(), FemGui::ViewProviderFemConstraintFluidBoundary::setEdit(), FemGui::ViewProviderFemConstraintFixed::setEdit(), FemGui::ViewProviderFemConstraintForce::setEdit(), FemGui::ViewProviderFemConstraintContact::setEdit(), FemGui::ViewProviderFemConstraintPlaneRotation::setEdit(), FemGui::ViewProviderFemConstraintHeatflux::setEdit(), FemGui::ViewProviderFemConstraintInitialTemperature::setEdit(), FemGui::ViewProviderFemConstraintTemperature::setEdit(), FemGui::ViewProviderFemConstraintDisplacement::setEdit(), FemGui::ViewProviderFemConstraintTransform::setEdit(), TechDrawGui::ViewProviderWeld::setEdit(), PartGui::ViewProviderFillet::setEdit(), Gui::ViewProviderDragger::setEdit(), TechDrawGui::ViewProviderProjGroup::setEdit(), PartDesignGui::ViewProviderBoolean::setEdit(), TechDrawGui::ViewProviderViewSection::setEdit(), FemGui::ViewProviderFemPostObject::setEdit(), PartDesignGui::ViewProvider::setEdit(), TechDrawGui::ViewProviderBalloon::setEdit(), TechDrawGui::ViewProviderViewPart::setEdit(), PartGui::ViewProviderChamfer::setEdit(), PartDesignGui::ViewProviderDatum::setEdit(), TechDrawGui::ViewProviderDimension::setEdit(), FemGui::ViewProviderFemPostFunction::setEdit(), PartGui::ViewProviderOffset::setEdit(), PartGui::ViewProviderThickness::setEdit(), Gui::ViewProviderLink::setEdit(), SketcherGui::ViewProviderSketch::setEdit(), Gui::ViewProviderLink::setEditViewer(), PartGui::ViewProviderAttachExtension::showAttachmentEditor(), and Gui::TaskView::ControlPy::showDialog().
showModelView()
void ControlSingleton::showModelView ()
raising the model view
Definition at line 136 of file Control.cpp.
References Gui::DockWindowManager::instance().
Referenced by Gui::TaskView::ControlPy::showModelView().
showTaskView
void ControlSingleton::showTaskView () slot
raises the task view panel
Definition at line 128 of file Control.cpp.
Referenced by PartDesignGui::Workbench::activated(), RobotGui::Workbench::activated(), and Gui::TaskView::ControlPy::showTaskView().
taskPanel()
Gui::TaskView::TaskView * ControlSingleton::taskPanel () const
Definition at line 61 of file Control.cpp.
References Gui::DockWindowManager::instance().
Referenced by Gui::Workbench::addTaskWatcher(), Gui::TaskView::ControlPy::addTaskWatcher(), Gui::OverlayTabWidget::checkAutoHide(), Gui::TaskView::ControlPy::clearTaskWatcher(), Gui::Workbench::removeTaskWatcher(), and Gui::TaskView::TaskView::updateWatcher().
The documentation for this class was generated from the following files:
Control.h
Control.cpp