FreeCAD: Base::Stream Class Reference
Base::Stream Class Reference
#include <Stream.h>
Public Types
enum ByteOrder { BigEndian, LittleEndian }
Public Member Functions
ByteOrder byteOrder () const
void setByteOrder (ByteOrder)
virtual ~Stream ()
Protected Member Functions
Stream ()
Stream (const Stream &)=default
Stream (Stream &&)=default
Stream & operator= (const Stream &)=default
Stream & operator= (Stream &&)=default
bool isSwapped () const
Detailed Description
Definition at line 47 of file Stream.h.
Member Enumeration Documentation
ByteOrder
enum Base::Stream::ByteOrder
Enumerator
BigEndian
LittleEndian
Definition at line 50 of file Stream.h.
Constructor & Destructor Documentation
~Stream()
Stream::~Stream () virtual default
Stream() [1/3]
Stream::Stream () protected default
Stream() [2/3]
Base::Stream::Stream (const Stream &) protected default
Stream() [3/3]
Base::Stream::Stream (Stream &&) protected default
Member Function Documentation
byteOrder()
Stream::ByteOrder Stream::byteOrder () const
Definition at line 47 of file Stream.cpp.
References BigEndian, and LittleEndian.
isSwapped()
bool Base::Stream::isSwapped () const inline protected
Definition at line 67 of file Stream.h.
Referenced by Base::OutputStream::operator<<(), and Base::InputStream::operator>>().
operator=() [1/2]
Stream& Base::Stream::operator= (const Stream &) protected default
operator=() [2/2]
Stream& Base::Stream::operator= (Stream &&) protected default
setByteOrder()
void Stream::setByteOrder (ByteOrder bo)
Definition at line 52 of file Stream.cpp.
References BigEndian.
Referenced by MeshCore::MeshOutput::SaveBinaryPLY().
The documentation for this class was generated from the following files:
Stream.h
Stream.cpp