FreeCAD: CAMTests.TestPathToolBit.TestPathToolBit Class Reference
CAMTests.TestPathToolBit.TestPathToolBit Class Reference
Public Member Functions
def test (self)
def test00 (self)
def test01 (self)
def test02 (self)
def test03 (self)
def test04 (self)
def test10 (self)
def test11 (self)
def test12 (self)
def test13 (self)
def test14 (self)
def test20 (self)
def test21 (self)
def test22 (self)
def test23 (self)
def test24 (self)
Public Member Functions inherited from CAMTests.PathTestUtils.PathTestBase
def assertRoughly (self, f1, f2, error=0.00001)
def assertCoincide (self, pt1, pt2, error=0.0001)
def assertPlacement (self, p1, p2)
def assertLine (self, edge, pt1, pt2)
def assertLines (self, edgs, tail, points)
def assertArc (self, edge, pt1, pt2, direction="CW")
def assertCircle (self, edge, pt, r)
def assertCurve (self, edge, p1, p2, p3)
def assertCylinderAt (self, solid, pt, r, h)
def assertConeAt (self, solid, pt, r1, r2, h)
def assertCommandEqual (self, c1, c2)
def assertEqualLocale (self, s1, s2)
def assertEdgeShapesMatch (self, e1, e2)
def assertPointsMatch (self, pts0, pts1)
def assertSuccessfulRecompute (self, doc, *objs, msg=None)
Detailed Description
Definition at line 60 of file TestPathToolBit.py.
Member Function Documentation
test()
def CAMTests.TestPathToolBit.TestPathToolBit.test (self)
Log test setup directory structure
Definition at line 61 of file TestPathToolBit.py.
References CAMTests.TestPathToolBit.printTree().
test00()
def CAMTests.TestPathToolBit.TestPathToolBit.test00 (self)
Find a tool shape from file name
Definition at line 72 of file TestPathToolBit.py.
Referenced by CAMTests.TestPathToolController.TestPathToolController.test01().
test01()
def CAMTests.TestPathToolBit.TestPathToolBit.test01 (self)
Not find a relative path shape if not stored in default location
Definition at line 78 of file TestPathToolBit.py.
test02()
def CAMTests.TestPathToolBit.TestPathToolBit.test02 (self)
Find a relative path shape if it's local to a bit path
Definition at line 83 of file TestPathToolBit.py.
References CAMTests.TestPathToolBit.testToolBit(), and CAMTests.TestPathToolBit.testToolShape().
test03()
def CAMTests.TestPathToolBit.TestPathToolBit.test03 (self)
Not find a tool shape from an invalid absolute path.
Definition at line 89 of file TestPathToolBit.py.
References CAMTests.TestPathToolBit.testToolShape().
test04()
def CAMTests.TestPathToolBit.TestPathToolBit.test04 (self)
Find a tool shape from a valid absolute path.
Definition at line 94 of file TestPathToolBit.py.
References CAMTests.TestPathToolBit.testToolShape().
test10()
def CAMTests.TestPathToolBit.TestPathToolBit.test10 (self)
Find a tool bit from file name
Definition at line 100 of file TestPathToolBit.py.
test11()
def CAMTests.TestPathToolBit.TestPathToolBit.test11 (self)
Not find a relative path bit if not stored in default location
Definition at line 106 of file TestPathToolBit.py.
test12()
def CAMTests.TestPathToolBit.TestPathToolBit.test12 (self)
Find a relative path bit if it's local to a library path
Definition at line 111 of file TestPathToolBit.py.
References CAMTests.TestPathToolBit.testToolBit(), and CAMTests.TestPathToolBit.testToolLibrary().
test13()
def CAMTests.TestPathToolBit.TestPathToolBit.test13 (self)
Not find a tool bit from an invalid absolute path.
Definition at line 117 of file TestPathToolBit.py.
References CAMTests.TestPathToolBit.testToolBit().
test14()
def CAMTests.TestPathToolBit.TestPathToolBit.test14 (self)
Find a tool bit from a valid absolute path.
Definition at line 122 of file TestPathToolBit.py.
References CAMTests.TestPathToolBit.testToolBit().
test20()
def CAMTests.TestPathToolBit.TestPathToolBit.test20 (self)
Find a tool library from file name
Definition at line 128 of file TestPathToolBit.py.
test21()
def CAMTests.TestPathToolBit.TestPathToolBit.test21 (self)
Not find a relative path library if not stored in default location
Definition at line 134 of file TestPathToolBit.py.
test22()
def CAMTests.TestPathToolBit.TestPathToolBit.test22 (self)
[skipped] Find a relative path library if it's local to <what?>
Definition at line 139 of file TestPathToolBit.py.
test23()
def CAMTests.TestPathToolBit.TestPathToolBit.test23 (self)
Not find a tool library from an invalid absolute path.
Definition at line 144 of file TestPathToolBit.py.
References CAMTests.TestPathToolBit.testToolLibrary().
test24()
def CAMTests.TestPathToolBit.TestPathToolBit.test24 (self)
Find a tool library from a valid absolute path.
Definition at line 149 of file TestPathToolBit.py.
References CAMTests.TestPathToolBit.testToolBit().
The documentation for this class was generated from the following file:
TestPathToolBit.py