FreeCAD: TechDraw::CosmeticEdge Class Reference
TechDraw::CosmeticEdge Class Reference
#include <Cosmetic.h>
Public Member Functions
CosmeticEdge ()
CosmeticEdge (const TechDraw::BaseGeomPtr *geometry)
CosmeticEdge (const CosmeticEdge *ce)
CosmeticEdge (const Base::Vector3d &p1, const Base::Vector3d &p2)
CosmeticEdge (const TopoDS_Edge &e)
CosmeticEdge (const TechDraw::BaseGeomPtr g)
~CosmeticEdge () override
void initialize ()
TopoDS_Edge TopoDS_EdgeFromVectors (const Base::Vector3d &pt1, const Base::Vector3d &pt2)
TechDraw::BaseGeomPtr scaledGeometry (const double scale)
TechDraw::BaseGeomPtr scaledAndRotatedGeometry (const double scale, const double rotDegrees)
LineFormat format () const
void setFormat (LineFormat newFormat)
std::string toString () const override
void dump (const char *title) const
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
PyObject * getPyObject () override
CosmeticEdge * clone () const
boost::uuids::uuid getTag () const
std::string getTagAsString () const override
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from TechDraw::BaseGeom
BaseGeom ()
virtual ~BaseGeom ()=default
std::vector< Base::Vector3d > findEndPoints ()
Base::Vector3d getStartPoint ()
Base::Vector3d getEndPoint ()
Base::Vector3d getMidPoint ()
std::vector< Base::Vector3d > getQuads ()
double minDist (Base::Vector3d p)
Base::Vector3d nearPoint (Base::Vector3d p)
Base::Vector3d nearPoint (const BaseGeomPtr p)
find point on me nearest to p
bool closed ()
virtual BaseGeomPtr copy ()
std::string dump ()
std::vector< Base::Vector3d > intersection (TechDraw::BaseGeomPtr geom2)
boost::uuids::uuid getTag () const
std::string geomTypeName ()
BaseGeomPtr inverted ()
GeomType getGeomType ()
void setGeomType (GeomType type)
edgeClass getClassOfEdge ()
void setClassOfEdge (edgeClass newClass)
bool getHlrVisible ()
void setHlrVisible (bool state)
bool getReversed ()
void setReversed (bool state)
int getRef3d ()
void setRef3d (int ref)
TopoDS_Edge getOCCEdge ()
void setOCCEdge (TopoDS_Edge newEdge)
bool getCosmetic ()
void setCosmetic (bool state)
int source ()
void source (int s)
int sourceIndex ()
void sourceIndex (int si)
std::string getCosmeticTag ()
void setCosmeticTag (std::string t)
Part::TopoShape asTopoShape (double scale=1.0)
virtual double getStartAngle ()
virtual double getEndAngle ()
virtual bool clockwiseAngle ()
virtual void clockwiseAngle (bool direction)
Static Public Member Functions
static TechDraw::BaseGeomPtr makeCanonicalLine (DrawViewPart *dvp, Base::Vector3d start, Base::Vector3d end)
static TechDraw::BaseGeomPtr makeLineFromCanonicalPoints (Base::Vector3d start, Base::Vector3d end)
makes an unscaled, unrotated line from two canonical points.
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Member Functions inherited from TechDraw::BaseGeom
static BaseGeomPtr baseFactory (TopoDS_Edge edge, bool isCosmetic=false)
Convert 1 OCC edge into 1 BaseGeom (static factory method)
static bool validateEdge (TopoDS_Edge edge)
static TopoDS_Edge completeEdge (const TopoDS_Edge &edge)
Public Attributes
Base::Vector3d permaStart
Base::Vector3d permaEnd
double permaRadius
TechDraw::BaseGeomPtr m_geometry
LineFormat m_format
Protected Member Functions
void createNewTag ()
void assignTag (const TechDraw::CosmeticEdge *ce)
Protected Member Functions inherited from TechDraw::BaseGeom
void createNewTag ()
Protected Attributes
boost::uuids::uuid tag
Py::Object PythonObject
Protected Attributes inherited from TechDraw::BaseGeom
GeomType geomType
ExtractionType extractType
edgeClass classOfEdge
bool hlrVisible
bool reversed
int ref3D
TopoDS_Edge occEdge
bool cosmetic
int m_source
int m_sourceIndex
std::string cosmeticTag
boost::uuids::uuid tag
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 43 of file Cosmetic.h.
Constructor & Destructor Documentation
CosmeticEdge() [1/6]
CosmeticEdge::CosmeticEdge ()
Definition at line 56 of file Cosmetic.cpp.
Referenced by clone().
CosmeticEdge() [2/6]
TechDraw::CosmeticEdge::CosmeticEdge (const TechDraw::BaseGeomPtr * geometry)
CosmeticEdge() [3/6]
CosmeticEdge::CosmeticEdge (const CosmeticEdge * ce)
Definition at line 63 of file Cosmetic.cpp.
References m_format, m_geometry, permaEnd, permaRadius, and permaStart.
CosmeticEdge() [4/6]
CosmeticEdge::CosmeticEdge (const Base::Vector3d & p1, const Base::Vector3d & p2)
Definition at line 75 of file Cosmetic.cpp.
CosmeticEdge() [5/6]
CosmeticEdge::CosmeticEdge (const TopoDS_Edge & e)
Definition at line 80 of file Cosmetic.cpp.
CosmeticEdge() [6/6]
CosmeticEdge::CosmeticEdge (const TechDraw::BaseGeomPtr g)
Definition at line 85 of file Cosmetic.cpp.
References TechDraw::ARCOFCIRCLE, TechDraw::CIRCLE, toolbit-attributes::g, initialize(), m_geometry, permaEnd, permaRadius, and permaStart.
~CosmeticEdge()
CosmeticEdge::~CosmeticEdge () override
Definition at line 111 of file Cosmetic.cpp.
Member Function Documentation
assignTag()
void CosmeticEdge::assignTag (const TechDraw::CosmeticEdge * ce) protected
Definition at line 335 of file Cosmetic.cpp.
References Base::Persistence::getTypeId(), and tag.
clone()
CosmeticEdge * CosmeticEdge::clone () const
Definition at line 343 of file Cosmetic.cpp.
References Base::Console(), CosmeticEdge(), m_format, m_geometry, Base::ConsoleSingleton::Message(), and tag.
createNewTag()
void CosmeticEdge::createNewTag () protected
Definition at line 315 of file Cosmetic.cpp.
References tag.
Referenced by initialize().
dump()
void CosmeticEdge::dump (const char * title) const
Definition at line 203 of file Cosmetic.cpp.
References Base::Console(), Base::ConsoleSingleton::Message(), Plot::title(), and toString().
format()
LineFormat TechDraw::CosmeticEdge::format () const inline
Definition at line 63 of file Cosmetic.h.
getMemSize()
unsigned int CosmeticEdge::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
Definition at line 210 of file Cosmetic.cpp.
getPyObject()
PyObject * CosmeticEdge::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 353 of file Cosmetic.cpp.
References Py::new_reference_to(), and PythonObject.
getTag()
boost::uuids::uuid CosmeticEdge::getTag () const
Definition at line 305 of file Cosmetic.cpp.
References tag.
Referenced by getTagAsString().
getTagAsString()
std::string CosmeticEdge::getTagAsString () const override virtual
Reimplemented from TechDraw::BaseGeom.
Definition at line 310 of file Cosmetic.cpp.
References getTag().
Referenced by TechDraw::CosmeticExtension::addCosmeticEdge(), TechDraw::GeometryObject::addCosmeticEdge(), initialize(), scaledAndRotatedGeometry(), scaledGeometry(), and toString().
initialize()
void CosmeticEdge::initialize ()
Definition at line 116 of file Cosmetic.cpp.
References COSMETICEDGE, createNewTag(), TechDraw::ecHARD, getTagAsString(), and m_geometry.
Referenced by CosmeticEdge().
makeCanonicalLine()
TechDraw::BaseGeomPtr CosmeticEdge::makeCanonicalLine (DrawViewPart * dvp, Base::Vector3d start, Base::Vector3d end) static
makes an unscaled, unrotated line from two scaled & rotated end points. the result of this method should be used in addCosmeticEdge().
Definition at line 170 of file Cosmetic.cpp.
References TechDraw::BaseGeom::baseFactory(), TechDraw::CosmeticVertex::makeCanonicalPoint(), and TechDraw::DrawUtil::togp_Pnt().
makeLineFromCanonicalPoints()
TechDraw::BaseGeomPtr CosmeticEdge::makeLineFromCanonicalPoints (Base::Vector3d start, Base::Vector3d end) static
makes an unscaled, unrotated line from two canonical points.
Definition at line 181 of file Cosmetic.cpp.
References TechDraw::BaseGeom::baseFactory(), and TechDraw::DrawUtil::togp_Pnt().
Restore()
void CosmeticEdge::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 243 of file Cosmetic.cpp.
References TechDraw::ARCOFCIRCLE, TechDraw::CIRCLE, Base::Console(), TechDraw::GeometryUtils::edgeFromCircle(), TechDraw::GeometryUtils::edgeFromCircleArc(), TechDraw::GeometryUtils::edgeFromGeneric(), App::Color::fromHexString(), TechDraw::GENERIC, TechDraw::LineFormat::InvalidLine, m_format, m_geometry, permaEnd, permaRadius, permaStart, TechDrawTools.TaskFillTemplateFields::reader, TechDraw::CosmeticVertex::restoreCosmetic(), TechDraw::LineFormat::setColor(), TechDraw::LineFormat::setLineNumber(), TechDraw::LineFormat::setStyle(), TechDraw::LineFormat::setVisible(), TechDraw::LineFormat::setWidth(), and Base::ConsoleSingleton::Warning().
Referenced by TechDraw::PropertyCosmeticEdgeList::Restore().
Save()
void CosmeticEdge::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 215 of file Cosmetic.cpp.
References TechDraw::ARCOFCIRCLE, App::Color::asHexString(), TechDraw::CIRCLE, Base::Console(), TechDraw::GENERIC, TechDraw::LineFormat::getColor(), TechDraw::LineFormat::getLineNumber(), TechDraw::LineFormat::getStyle(), TechDraw::LineFormat::getVisible(), TechDraw::LineFormat::getWidth(), Base::Writer::ind(), m_format, m_geometry, Base::Writer::Stream(), TestSpreadsheet::v, and Base::ConsoleSingleton::Warning().
scaledAndRotatedGeometry()
TechDraw::BaseGeomPtr CosmeticEdge::scaledAndRotatedGeometry (const double scale, const double rotDegrees)
Definition at line 148 of file Cosmetic.cpp.
References TechDraw::BaseGeom::baseFactory(), COSMETICEDGE, SCL.SimpleDataTypes::e, TechDraw::ecHARD, getTagAsString(), m_geometry, TechDraw::ShapeUtils::mirrorShape(), TechDraw::ShapeUtils::rotateShape(), and toolbit-attributes::s.
Referenced by TechDraw::CosmeticExtension::add1CEToGE().
scaledGeometry()
TechDraw::BaseGeomPtr CosmeticEdge::scaledGeometry (const double scale)
Definition at line 134 of file Cosmetic.cpp.
References TechDraw::BaseGeom::baseFactory(), COSMETICEDGE, SCL.SimpleDataTypes::e, TechDraw::ecHARD, getTagAsString(), m_geometry, toolbit-attributes::s, and TechDraw::ShapeUtils::scaleShape().
Referenced by TechDraw::GeometryObject::addCosmeticEdge().
setFormat()
void TechDraw::CosmeticEdge::setFormat (LineFormat newFormat) inline
Definition at line 64 of file Cosmetic.h.
Referenced by TechDrawGui::TaskCosmeticCircle::createCosmeticCircle(), TechDrawGui::TaskCosmeticLine::createCosmeticLine(), Path.Main.Gui.Inspect.GCodeHighlighter::highlightBlock(), and Path.Post.Utils.GCodeHighlighter::highlightBlock().
TopoDS_EdgeFromVectors()
TopoDS_Edge CosmeticEdge::TopoDS_EdgeFromVectors (const Base::Vector3d & pt1, const Base::Vector3d & pt2)
Definition at line 127 of file Cosmetic.cpp.
References Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
toString()
std::string CosmeticEdge::toString () const override virtual
Reimplemented from TechDraw::BaseGeom.
Definition at line 189 of file Cosmetic.cpp.
References getTagAsString(), m_format, m_geometry, and TechDraw::LineFormat::toString().
Referenced by dump().
Member Data Documentation
m_format
LineFormat TechDraw::CosmeticEdge::m_format
Definition at line 82 of file Cosmetic.h.
Referenced by TechDrawGui::_setLineAttributes(), clone(), CosmeticEdge(), TechDrawGui::QGIViewPart::formatGeomFromCosmetic(), TechDrawGui::TaskLineDecor::getFormatAccessPtr(), Restore(), Save(), and toString().
m_geometry
TechDraw::BaseGeomPtr TechDraw::CosmeticEdge::m_geometry
Definition at line 81 of file Cosmetic.h.
Referenced by clone(), CosmeticEdge(), execCosmeticCircle(), execLine2Points(), initialize(), Restore(), Save(), scaledAndRotatedGeometry(), scaledGeometry(), TechDrawGui::TaskCosmeticCircle::setUiEdit(), toString(), TechDrawGui::TaskCosmeticCircle::updateCosmeticCircle(), and TechDrawGui::TaskCosmeticLine::updateCosmeticLine().
permaEnd
Base::Vector3d TechDraw::CosmeticEdge::permaEnd
Definition at line 78 of file Cosmetic.h.
Referenced by CosmeticEdge(), Restore(), TechDrawGui::TaskCosmeticLine::setUiEdit(), TechDrawGui::TaskCosmeticCircle::updateCosmeticCircle(), and TechDrawGui::TaskCosmeticLine::updateCosmeticLine().
permaRadius
double TechDraw::CosmeticEdge::permaRadius
Definition at line 79 of file Cosmetic.h.
Referenced by CosmeticEdge(), Restore(), TechDrawGui::TaskCosmeticCircle::setUiEdit(), and TechDrawGui::TaskCosmeticCircle::updateCosmeticCircle().
permaStart
Base::Vector3d TechDraw::CosmeticEdge::permaStart
Definition at line 77 of file Cosmetic.h.
Referenced by CosmeticEdge(), Restore(), TechDrawGui::TaskCosmeticLine::setUiEdit(), TechDrawGui::TaskCosmeticCircle::setUiEdit(), TechDrawGui::TaskCosmeticCircle::updateCosmeticCircle(), and TechDrawGui::TaskCosmeticLine::updateCosmeticLine().
PythonObject
Py::Object TechDraw::CosmeticEdge::PythonObject protected
Definition at line 93 of file Cosmetic.h.
Referenced by getPyObject().
tag
boost::uuids::uuid TechDraw::CosmeticEdge::tag protected
Definition at line 91 of file Cosmetic.h.
Referenced by assignTag(), clone(), createNewTag(), Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.ChunkBase::dump_header(), and getTag().
The documentation for this class was generated from the following files:
Cosmetic.h
Cosmetic.cpp