FreeCAD: nativeifc.ifc_materials Namespace Reference
nativeifc.ifc_materials Namespace Reference
Functions
def create_material (element, parent, recursive=False)
def show_material (obj)
def load_materials (obj)
def get_material (obj)
def set_material (material, obj)
Function Documentation
create_material()
def nativeifc.ifc_materials.create_material (element, parent, recursive = False)
Creates a material object in the given project or parent material
Definition at line 33 of file ifc_materials.py.
References importDXF.addObject(), and nativeifc.ifc_materials.get_material().
Referenced by nativeifc.ifc_materials.show_material().
get_material()
def nativeifc.ifc_materials.get_material (obj)
Returns a material attached to this object
Definition at line 91 of file ifc_materials.py.
Referenced by nativeifc.ifc_materials.create_material(), and nativeifc.ifc_materials.show_material().
load_materials()
def nativeifc.ifc_materials.load_materials (obj)
Recursively loads materials of child objects
Definition at line 79 of file ifc_materials.py.
References nativeifc.ifc_materials.show_material().
set_material()
def nativeifc.ifc_materials.set_material (material, obj)
Attributes a material to an object
Definition at line 116 of file ifc_materials.py.
References nativeifc.ifc_materials.show_material().
show_material()
def nativeifc.ifc_materials.show_material (obj)
Creates and links materials for the given object, if available
Definition at line 66 of file ifc_materials.py.
References nativeifc.ifc_materials.create_material(), and nativeifc.ifc_materials.get_material().
Referenced by nativeifc.ifc_materials.load_materials(), and nativeifc.ifc_materials.set_material().