FreeCAD: PartGui::SweepWidget Class Reference
PartGui::SweepWidget Class Reference
#include <TaskSweep.h>
Classes
class Private
Public Member Functions
SweepWidget (QWidget *parent=nullptr)
~SweepWidget () override
bool accept ()
bool reject ()
Detailed Description
Definition at line 38 of file TaskSweep.h.
Constructor & Destructor Documentation
SweepWidget()
SweepWidget::SweepWidget (QWidget * parent = nullptr) explicit
Definition at line 123 of file TaskSweep.cpp.
References Gui::Command::App, draftgeoutils.intersections::connect(), Init::parent, runCommand, and PartGui::SweepWidget::Private::ui.
~SweepWidget()
SweepWidget::~SweepWidget () override
Definition at line 147 of file TaskSweep.cpp.
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
accept()
bool SweepWidget::accept ()
Definition at line 279 of file TaskSweep.cpp.
References Gui::Command::App, src.Mod.AddonManager.NetworkManager::count, toolbit-attributes::doc, PartGui::SweepWidget::Private::document, SCL.SimpleDataTypes::e, Gui::Application::getDocument(), Gui::SelectionSingleton::getSelectionEx(), App::DocumentObject::getStatusString(), Part::Feature::getTopoShape(), App::PropertyString::getValue(), SplineSurface::i, Gui::Application::Instance, Part::TopoShape::isNull(), App::DocumentObject::isValid(), App::DocumentObject::Label, Path.Op.Surface::msg, Arch::QT_TRANSLATE_NOOP, runCommand, Path.Dressup.Utils::selection(), Gui::Selection(), Path.Post.scripts.refactored_centroid_post::str, src.Mod.AddonManager.Addon::translate, PartGui::SweepWidget::Private::ui, and Path.Log::warning().
Referenced by PartGui::TaskSweep::accept().
reject()
bool SweepWidget::reject ()
Definition at line 387 of file TaskSweep.cpp.
References PartGui::SweepWidget::Private::ui.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and PartGui::TaskSweep::reject().
The documentation for this class was generated from the following files:
TaskSweep.h
TaskSweep.cpp