FreeCAD: PartGui::Picker Class Reference
PartGui::Picker Class Reference abstract
#include <DlgPrimitives.h>
Public Member Functions
virtual ~Picker ()=default
virtual bool pickedPoint (const SoPickedPoint *point)=0
virtual QString command (App::Document *) const =0
void createPrimitive (QWidget *widget, const QString &, Gui::Document *)
QString toPlacement (const gp_Ax2 &) const
Public Attributes
int exitCode {-1}
QEventLoop loop
Detailed Description
Definition at line 61 of file DlgPrimitives.h.
Constructor & Destructor Documentation
~Picker()
virtual PartGui::Picker::~Picker () virtual default
Member Function Documentation
command()
virtual QString PartGui::Picker::command (App::Document *) const pure virtual
Implemented in PartGui::CircleFromThreePoints.
Referenced by createPrimitive().
createPrimitive()
void PartGui::Picker::createPrimitive (QWidget * widget, const QString & descr, Gui::Document * doc)
Definition at line 119 of file DlgPrimitives.cpp.
References src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui::app, command(), toolbit-attributes::doc, Gui::Command::Doc, SCL.SimpleDataTypes::e, Gui::Command::Gui, runCommand, src.Mod.AddonManager.Addon::translate, and Path.Log::warning().
pickedPoint()
virtual bool PartGui::Picker::pickedPoint (const SoPickedPoint * point) pure virtual
Implemented in PartGui::CircleFromThreePoints.
toPlacement()
QString PartGui::Picker::toPlacement (const gp_Ax2 & axis) const
Definition at line 137 of file DlgPrimitives.cpp.
References Base::UnitsApi::getDecimals().
Referenced by PartGui::CircleFromThreePoints::command().
Member Data Documentation
exitCode
int PartGui::Picker::exitCode {-1}
Definition at line 71 of file DlgPrimitives.h.
loop
QEventLoop PartGui::Picker::loop
Definition at line 72 of file DlgPrimitives.h.
The documentation for this class was generated from the following files:
DlgPrimitives.h
DlgPrimitives.cpp