FreeCAD: SketcherGui::ConstructionMethodMachine< ConstructionMethodT > Class Template Reference
SketcherGui::ConstructionMethodMachine< ConstructionMethodT > Class Template Reference
An encapsulation of a construction method.
#include <DrawSketchDefaultHandler.h>
Public Member Functions
ConstructionMethodMachine (ConstructionMethodT constructionmethod=static_cast< ConstructionMethodT >(0))
virtual ~ConstructionMethodMachine ()
Protected Member Functions
void setConstructionMethod (ConstructionMethodT mode)
ConstructionMethodT constructionMethod () const
bool isConstructionMethod (ConstructionMethodT state) const
void resetConstructionMode ()
void initConstructionMethod (ConstructionMethodT mode)
ConstructionMethodT getNextMethod () const
void iterateToNextConstructionMethod ()
virtual void onConstructionMethodChanged ()
Static Protected Member Functions
static constexpr int ConstructionMethodsCount ()
Detailed Description
template<typename ConstructionMethodT>
class SketcherGui::ConstructionMethodMachine< ConstructionMethodT >
An encapsulation of a construction method.
A template class for a construction method defined by template type ConstructionMethodT.
A construction method is an alternative UI sequence of steps or input parameters to achieve a goal.For example, for creation of a circle, point center + radius is a possible construction method. Three points on the rim is another possible construction method.
The construction method is automatically initialised to the first or default construction method. It senses construction method change, triggering onModeChanged() after every change.
the getNextMethod() returns the next construction method, in a round-robin fashion.
NOTE: A construction method enum defining the different construction methods must be provided and the last item shall be ConstructionMethodT::End.
Definition at line 280 of file DrawSketchDefaultHandler.h.
Constructor & Destructor Documentation
ConstructionMethodMachine()
template<typename ConstructionMethodT > SketcherGui::ConstructionMethodMachine< ConstructionMethodT >::ConstructionMethodMachine (ConstructionMethodT constructionmethod = static_cast<ConstructionMethodT>(0)) inline
Definition at line 283 of file DrawSketchDefaultHandler.h.
Referenced by SketcherGui::StateMachine< ControllerT::SelectModeType >::onModeChanged().
~ConstructionMethodMachine()
template<typename ConstructionMethodT > virtual SketcherGui::ConstructionMethodMachine< ConstructionMethodT >::~ConstructionMethodMachine () inline virtual
Definition at line 287 of file DrawSketchDefaultHandler.h.
Referenced by SketcherGui::StateMachine< ControllerT::SelectModeType >::onModeChanged().
Member Function Documentation
constructionMethod()
template<typename ConstructionMethodT > ConstructionMethodT SketcherGui::ConstructionMethodMachine< ConstructionMethodT >::constructionMethod () const inline protected
Definition at line 297 of file DrawSketchDefaultHandler.h.
Referenced by SketcherGui::StateMachine< ControllerT::SelectModeType >::onModeChanged().
ConstructionMethodsCount()
template<typename ConstructionMethodT > static constexpr int SketcherGui::ConstructionMethodMachine< ConstructionMethodT >::ConstructionMethodsCount () inline static constexpr protected
Definition at line 341 of file DrawSketchDefaultHandler.h.
Referenced by SketcherGui::ConstructionMethodMachine< ConstructionMethods::DefaultConstructionMethod >::initConstructionMethod().
getNextMethod()
template<typename ConstructionMethodT > ConstructionMethodT SketcherGui::ConstructionMethodMachine< ConstructionMethodT >::getNextMethod () const inline protected
Definition at line 318 of file DrawSketchDefaultHandler.h.
Referenced by SketcherGui::ConstructionMethodMachine< ConstructionMethods::DefaultConstructionMethod >::initConstructionMethod().
initConstructionMethod()
template<typename ConstructionMethodT > void SketcherGui::ConstructionMethodMachine< ConstructionMethodT >::initConstructionMethod (ConstructionMethodT mode) inline protected
Definition at line 312 of file DrawSketchDefaultHandler.h.
isConstructionMethod()
template<typename ConstructionMethodT > bool SketcherGui::ConstructionMethodMachine< ConstructionMethodT >::isConstructionMethod (ConstructionMethodT state) const inline protected
Definition at line 302 of file DrawSketchDefaultHandler.h.
iterateToNextConstructionMethod()
template<typename ConstructionMethodT > void SketcherGui::ConstructionMethodMachine< ConstructionMethodT >::iterateToNextConstructionMethod () inline protected
Definition at line 332 of file DrawSketchDefaultHandler.h.
onConstructionMethodChanged()
template<typename ConstructionMethodT > virtual void SketcherGui::ConstructionMethodMachine< ConstructionMethodT >::onConstructionMethodChanged () inline protected virtual
Definition at line 339 of file DrawSketchDefaultHandler.h.
Referenced by SketcherGui::StateMachine< ControllerT::SelectModeType >::onModeChanged().
resetConstructionMode()
template<typename ConstructionMethodT > void SketcherGui::ConstructionMethodMachine< ConstructionMethodT >::resetConstructionMode () inline protected
Definition at line 307 of file DrawSketchDefaultHandler.h.
setConstructionMethod()
template<typename ConstructionMethodT > void SketcherGui::ConstructionMethodMachine< ConstructionMethodT >::setConstructionMethod (ConstructionMethodT mode) inline protected
Definition at line 291 of file DrawSketchDefaultHandler.h.
Referenced by SketcherGui::ConstructionMethodMachine< ConstructionMethods::DefaultConstructionMethod >::initConstructionMethod(), and SketcherGui::StateMachine< ControllerT::SelectModeType >::onModeChanged().
The documentation for this class was generated from the following file:
DrawSketchDefaultHandler.h