FreeCAD: Gui::Dialog::Placement Class Reference
Gui::Dialog::Placement Class Reference
#include <Placement.h>
Public Slots
void onApplyButtonClicked ()
Signals
void placementChanged (const QVariant &, bool, bool)
Public Member Functions
Placement (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~Placement () override
void open () override
void accept () override
void reject () override
void setPropertyName (const std::string &)
void setSelection (const std::vector< SelectionObject > &)
Placement::setSelection Sets the array of selection objects.
void bindObject ()
Placement::bindObject Binds the spin boxes to the placement components of the first object of the selection. This requires the call of setSelection() beforehand.
void setPlacementAndBindObject (const App::DocumentObject *obj, const std::string &propertyName)
Placement::setPlacementAndBindObject Sets the placement, binds the spin boxes to the placement components of the passed object and sets the name of the placement property.
void setIgnoreTransactions (bool value)
Base::Vector3d getDirection () const
void setPlacement (const Base::Placement &)
Base::Placement getPlacement () const
void showDefaultButtons (bool)
Protected Member Functions
void changeEvent (QEvent *e) override
void keyPressEvent (QKeyEvent *) override
Detailed Description
Definition at line 112 of file Gui/Placement.h.
Constructor & Destructor Documentation
Placement()
Placement::Placement (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Definition at line 456 of file Gui/Placement.cpp.
~Placement()
Placement::~Placement () override
Definition at line 467 of file Gui/Placement.cpp.
Member Function Documentation
accept()
void Placement::accept () override
Definition at line 793 of file Gui/Placement.cpp.
References Gui::Dialog::PlacementHandler::revertTransformation().
Referenced by Gui::Dialog::DockablePlacement::accept(), Gui::Dialog::TaskPlacement::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
bindObject()
void Placement::bindObject ()
Placement::bindObject Binds the spin boxes to the placement components of the first object of the selection. This requires the call of setSelection() beforehand.
Definition at line 888 of file Gui/Placement.cpp.
References Gui::Dialog::PlacementHandler::getFirstOfSelection(), Gui::Dialog::PlacementHandler::getPropertyName(), and propertyName().
Referenced by Gui::Dialog::TaskPlacement::bindObject().
changeEvent()
void Placement::changeEvent (QEvent * e) override protected
Definition at line 1087 of file Gui/Placement.cpp.
References SCL.SimpleDataTypes::e.
getDirection()
Base::Vector3d Placement::getDirection () const
Definition at line 941 of file Gui/Placement.cpp.
References MovieTool::x, and MovieTool::y.
getPlacement()
Base::Placement Placement::getPlacement () const
Definition at line 976 of file Gui/Placement.cpp.
References buildPsets::p.
Referenced by RobotGui::TaskRobot6Axis::createPlacementDlg().
keyPressEvent()
void Placement::keyPressEvent (QKeyEvent * ke) override protected
Definition at line 767 of file Gui/Placement.cpp.
onApplyButtonClicked
void Placement::onApplyButtonClicked () slot
Definition at line 801 of file Gui/Placement.cpp.
Referenced by Gui::Dialog::TaskPlacement::clicked().
open()
void Placement::open () override
Definition at line 562 of file Gui/Placement.cpp.
References Gui::Dialog::PlacementHandler::openTransactionIfNeeded().
Referenced by Gui::Dialog::TaskPlacement::open().
placementChanged
void Gui::Dialog::Placement::placementChanged (const QVariant & , bool , bool) signal
Referenced by reject(), and Gui::Dialog::TaskPlacement::TaskPlacement().
reject()
void Placement::reject () override
Definition at line 774 of file Gui/Placement.cpp.
References Gui::Dialog::PlacementHandler::applyPlacement(), placementChanged(), and Gui::Dialog::PlacementHandler::revertTransformation().
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), Gui::Dialog::DockablePlacement::reject(), Gui::Dialog::TaskPlacement::reject(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
setIgnoreTransactions()
void Placement::setIgnoreTransactions (bool value)
Definition at line 878 of file Gui/Placement.cpp.
References Gui::Dialog::PlacementHandler::setIgnoreTransactions().
setPlacement()
void Placement::setPlacement (const Base::Placement & p)
Definition at line 949 of file Gui/Placement.cpp.
References buildPsets::p.
Referenced by RobotGui::TaskRobot6Axis::createPlacementDlg(), Gui::Dialog::TaskPlacement::setPlacement(), and setPlacementAndBindObject().
setPlacementAndBindObject()
void Placement::setPlacementAndBindObject (const App::DocumentObject * obj, const std::string & propertyName)
Placement::setPlacementAndBindObject Sets the placement, binds the spin boxes to the placement components of the passed object and sets the name of the placement property.
Definition at line 901 of file Gui/Placement.cpp.
References Gui::Dialog::find_placement::getProperty(), App::PropertyPlacement::getValue(), propertyName(), setPlacement(), Gui::Dialog::PlacementHandler::setPropertyName(), and Gui::Dialog::PlacementHandler::setSelection().
Referenced by Gui::Dialog::TaskPlacement::setPlacementAndBindObject().
setPropertyName()
void Placement::setPropertyName (const std::string & name)
Definition at line 873 of file Gui/Placement.cpp.
References Gui::Dialog::PlacementHandler::setPropertyName().
Referenced by Gui::Dialog::TaskPlacement::setPropertyName().
setSelection()
void Placement::setSelection (const std::vector< SelectionObject > & selection)
Placement::setSelection Sets the array of selection objects.
Parameters
selection
Definition at line 868 of file Gui/Placement.cpp.
References Path.Dressup.Utils::selection(), and Gui::Dialog::PlacementHandler::setSelection().
Referenced by Gui::Dialog::TaskPlacement::clearSelection(), RobotGui::TaskRobot6Axis::createPlacementDlg(), and Gui::Dialog::TaskPlacement::setSelection().
showDefaultButtons()
void Placement::showDefaultButtons (bool ok)
Definition at line 550 of file Gui/Placement.cpp.
Referenced by Gui::Dialog::TaskPlacement::TaskPlacement().
The documentation for this class was generated from the following files:
Gui/Placement.h
Gui/Placement.cpp