FreeCAD: FemGui::DlgSettingsFemZ88Imp Class Reference
FemGui::DlgSettingsFemZ88Imp Class Reference
#include <DlgSettingsFemZ88Imp.h>
Public Member Functions
DlgSettingsFemZ88Imp (QWidget *parent=nullptr)
~DlgSettingsFemZ88Imp () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Slots
void onfileNameChanged (QString FileName)
Protected Member Functions
void saveSettings () override
void loadSettings () override
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
Definition at line 58 of file DlgSettingsFemZ88Imp.h.
Constructor & Destructor Documentation
DlgSettingsFemZ88Imp()
DlgSettingsFemZ88Imp::DlgSettingsFemZ88Imp (QWidget * parent = nullptr) explicit
Definition at line 38 of file DlgSettingsFemZ88Imp.cpp.
References draftgeoutils.intersections::connect(), Gui::FileChooser::fileNameChanged(), and onfileNameChanged().
~DlgSettingsFemZ88Imp()
DlgSettingsFemZ88Imp::~DlgSettingsFemZ88Imp () override default
Member Function Documentation
changeEvent()
void DlgSettingsFemZ88Imp::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 93 of file DlgSettingsFemZ88Imp.cpp.
References SCL.SimpleDataTypes::e.
loadSettings()
void DlgSettingsFemZ88Imp::loadSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 67 of file DlgSettingsFemZ88Imp.cpp.
References App::GetApplication(), ParameterGrp::GetInt(), and App::Application::GetParameterGroupByPath().
onfileNameChanged
void DlgSettingsFemZ88Imp::onfileNameChanged (QString FileName) protected slot
Definition at line 103 of file DlgSettingsFemZ88Imp.cpp.
Referenced by DlgSettingsFemZ88Imp().
saveSettings()
void DlgSettingsFemZ88Imp::saveSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 52 of file DlgSettingsFemZ88Imp.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetInt().
The documentation for this class was generated from the following files:
DlgSettingsFemZ88Imp.h
DlgSettingsFemZ88Imp.cpp