FreeCAD: Points::PointKernel Class Reference
Points::PointKernel Class Reference
#include <Points.h>
Classes
class const_point_iterator
Public Types
using float_type = float
using value_type = Base::Vector3< float_type >
using difference_type = std::vector< value_type >::difference_type
using size_type = std::vector< value_type >::size_type
Public Member Functions
PointKernel ()=default
PointKernel (size_type size)
PointKernel (const PointKernel &)
PointKernel (PointKernel &&) noexcept
~PointKernel () override=default
PointKernel & operator= (const PointKernel &)
PointKernel & operator= (PointKernel &&) noexcept
Subelement management
std::vector< const char * > getElementTypes () const override
unsigned long countSubElements (const char *Type) const override
Data::Segment * getSubElement (const char *Type, unsigned long) const override
get the subelement by type and number
void setTransform (const Base::Matrix4D &rclTrf) override
Base::Matrix4D getTransform () const override
std::vector< value_type > & getBasicPoints ()
const std::vector< value_type > & getBasicPoints () const
void setBasicPoints (const std::vector< value_type > &pts)
void swap (std::vector< value_type > &pts)
void getPoints (std::vector< Base::Vector3d > &Points, std::vector< Base::Vector3d > &Normals, double Accuracy, uint16_t flags=0) const override
void transformGeometry (const Base::Matrix4D &rclMat) override
Applies a transformation on the real geometric data type.
Base::BoundBox3d getBoundBox () const override
Get the bound box.
Iterator
const_point_iterator begin () const
const_point_iterator end () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
Public Member Functions inherited from Data::ComplexGeoData
ComplexGeoData ()
Constructor.
~ComplexGeoData () override=default
Destructor.
void applyTransform (const Base::Matrix4D &rclTrf)
void applyTranslation (const Base::Vector3d &)
void applyRotation (const Base::Rotation &)
void setPlacement (const Base::Placement &rclPlacement)
Base::Placement getPlacement () const
virtual Segment * getSubElementByName (const char *Name) const
get sub-element by combined name
virtual void getLinesFromSubElement (const Segment *, std::vector< Base::Vector3d > &Points, std::vector< Line > &lines) const
virtual void getFacesFromSubElement (const Segment *, std::vector< Base::Vector3d > &Points, std::vector< Base::Vector3d > &PointNormals, std::vector< Facet > &faces) const
virtual double getAccuracy () const
Get the standard accuracy to be used with getPoints, getLines or getFaces.
virtual Base::Vector3d getPointFromLineIntersection (const Base::Vector3f &base, const Base::Vector3f &dir) const
virtual void getLines (std::vector< Base::Vector3d > &Points, std::vector< Line > &lines, double Accuracy, uint16_t flags=0) const
virtual void getFaces (std::vector< Base::Vector3d > &Points, std::vector< Facet > &faces, double Accuracy, uint16_t flags=0) const
virtual bool getCenterOfGravity (Base::Vector3d &center) const
virtual std::optional< Base::Vector3d > centerOfGravity () const
IndexedName getIndexedName (const MappedName &name, ElementIDRefs *sid=nullptr) const
MappedName getMappedName (const IndexedName &element, bool allowUnmapped=false, ElementIDRefs *sid=nullptr) const
MappedElement getElementName (const char *name, ElementIDRefs *sid=nullptr, bool copy=false) const
MappedName setElementName (const IndexedName &element, const MappedName &name, long masterTag, const ElementIDRefs *sid=nullptr, bool overwrite=false)
bool hasElementMap ()
std::vector< std::pair< MappedName, ElementIDRefs > > getElementMappedNames (const IndexedName &element, bool needUnmapped=false) const
void hashChildMaps ()
Hash the child element map postfixes to shorten element name from hierarchical maps.
bool hasChildElementMap () const
Check if there is child element map.
virtual void reTagElementMap (long tag, App::StringHasherRef hasher, const char *postfix=nullptr)
Append the Tag (if and only if it is non zero) into the element map.
long getElementHistory (const MappedName &name, MappedName *original=nullptr, std::vector< MappedName > *history=nullptr) const
void setMappedChildElements (const std::vector< Data::ElementMap::MappedChildElements > &children)
std::vector< Data::ElementMap::MappedChildElements > getMappedChildElements () const
char elementType (const Data::MappedName &) const
char elementType (const Data::IndexedName &) const
char elementType (const char *name) const
virtual ElementMapPtr resetElementMap (ElementMapPtr elementMap=ElementMapPtr())
std::vector< MappedElement > getElementMap () const
Get the entire element map.
void setElementMap (const std::vector< MappedElement > &elements)
Set the entire element map.
size_t getElementMapSize (bool flush=true) const
Get the current element map size.
virtual std::vector< IndexedName > getHigherElements (const char *name, bool silent=false) const
Return the higher level element names of the given element.
virtual std::string getElementMapVersion () const
Return the current element map version.
virtual bool checkElementMapVersion (const char *ver) const
Return true to signal element map version change.
void traceElement (const MappedName &name, TraceCallback cb) const
virtual void flushElementMap () const
void setPersistenceFileName (const char *name) const
virtual void beforeSave () const
bool isRestoreFailed () const
void resetRestoreFailure () const
void dumpElementMap (std::ostream &stream) const
const std::string dumpElementMap () const
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from Base::Handled
Handled ()
virtual ~Handled ()
void ref () const
void unref () const
int unrefNoDelete () const
int getRefCount () const
Handled & operator= (const Handled &)
Handled (const Handled &)=delete
Handled (Handled &&)=delete
Handled & operator= (Handled &&)=delete
I/O
using const_iterator = const_point_iterator
using const_reverse_iterator = std::reverse_iterator< const_iterator >
unsigned int getMemSize () const override
void Save (Base::Writer &writer) const override
void SaveDocFile (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void RestoreDocFile (Base::Reader &reader) override
void save (const char *file) const
void save (std::ostream &) const
void load (const char *file)
void load (std::istream &)
size_type size () const
number of points stored
size_type countValid () const
std::vector< value_type > getValidPoints () const
void resize (size_type n)
void reserve (size_type n)
void erase (size_type first, size_type last)
void clear ()
const Base::Vector3d getPoint (const int idx) const
get the points
void setPoint (const int idx, const Base::Vector3d &point)
set the points
void push_back (const Base::Vector3d &point)
insert the points
Additional Inherited Members
Static Public Member Functions inherited from Data::ComplexGeoData
static std::pair< std::string, unsigned long > getTypeAndIndex (const char *Name)
static const std::string & elementMapPrefix ()
static bool isElementName (const char *subName)
Check if the given sub-name only contains an element name.
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from Data::ComplexGeoData
long Tag {0}
App::StringHasherRef Hasher
String hasher for element name shortening.
Protected Member Functions inherited from Data::ComplexGeoData
Base::Vector3d transformPointToOutside (const Base::Vector3f &vec) const
from local to outside
template<typename Vec >
std::vector< Base::Vector3d > transformPointsToOutside (const std::vector< Vec > &input) const
from local to outside
Base::Vector3d transformVectorToOutside (const Base::Vector3f &vec) const
template<typename Vec >
std::vector< Base::Vector3d > transformVectorsToOutside (const std::vector< Vec > &input) const
Base::Vector3f transformPointToInside (const Base::Vector3d &vec) const
from local to inside
void restoreStream (std::istream &stream, std::size_t count)
void readElements (Base::XMLReader &reader, size_t count)
Base::Vector3d transformToOutside (const Base::Vector3f &vec) const
from local to outside
Base::Vector3f transformToInside (const Base::Vector3d &vec) const
from local to inside
ElementMapPtr elementMap (bool flush=true) const
ElementMapPtr ensureElementMap (bool flush=true)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Data::ComplexGeoData
std::string _persistenceName
bool _restoreFailed = false
Detailed Description
Point kernel
Definition at line 65 of file Points.h.
Member Typedef Documentation
const_iterator
using Points::PointKernel::const_iterator = const_point_iterator
Definition at line 251 of file Points.h.
const_reverse_iterator
using Points::PointKernel::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 252 of file Points.h.
difference_type
using Points::PointKernel::difference_type = std::vector<value_type>::difference_type
Definition at line 92 of file Points.h.
float_type
using Points::PointKernel::float_type = float
Definition at line 90 of file Points.h.
size_type
using Points::PointKernel::size_type = std::vector<value_type>::size_type
Definition at line 93 of file Points.h.
value_type
using Points::PointKernel::value_type = Base::Vector3<float_type>
Definition at line 91 of file Points.h.
Constructor & Destructor Documentation
PointKernel() [1/4]
Points::PointKernel::PointKernel () default
PointKernel() [2/4]
Points::PointKernel::PointKernel (size_type size) inline explicit
Definition at line 96 of file Points.h.
PointKernel() [3/4]
PointKernel::PointKernel (const PointKernel & pts)
Definition at line 48 of file Points.cpp.
PointKernel() [4/4]
PointKernel::PointKernel (PointKernel && pts) noexcept
Definition at line 53 of file Points.cpp.
~PointKernel()
Points::PointKernel::~PointKernel () override default
Member Function Documentation
begin()
const_point_iterator Points::PointKernel::begin () const inline
Definition at line 256 of file Points.h.
Referenced by PointsGui::ViewProviderScattered::cut().
clear()
void Points::PointKernel::clear () inline
Definition at line 190 of file Points.h.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__(), and Points::PointsAlgos::LoadAscii().
countSubElements()
unsigned long PointKernel::countSubElements (const char * Type) const override virtual
Implements Data::ComplexGeoData.
Definition at line 66 of file Points.cpp.
countValid()
PointKernel::size_type PointKernel::countValid () const
Definition at line 156 of file Points.cpp.
end()
const_point_iterator Points::PointKernel::end () const inline
Definition at line 260 of file Points.h.
Referenced by PointsGui::ViewProviderScattered::cut().
erase()
void Points::PointKernel::erase (size_type first, size_type last) inline
Definition at line 185 of file Points.h.
Referenced by Points::PointsAlgos::LoadAscii().
getBasicPoints() [1/2]
std::vector<value_type>& Points::PointKernel::getBasicPoints () inline
Definition at line 127 of file Points.h.
Referenced by PointsGui::ViewProviderPointsBuilder::createPoints(), Points::PlyWriter::write(), and Points::PcdWriter::write().
getBasicPoints() [2/2]
const std::vector<value_type>& Points::PointKernel::getBasicPoints () const inline
Definition at line 131 of file Points.h.
getBoundBox()
Base::BoundBox3d PointKernel::getBoundBox () const override virtual
Get the bound box.
Implements Data::ComplexGeoData.
Definition at line 102 of file Points.cpp.
References Base::BoundBox3< Precision >::Add().
getElementTypes()
std::vector< const char * > PointKernel::getElementTypes () const override virtual
Sub type list List of different subelement types its NOT a list of the subelements itself
Implements Data::ComplexGeoData.
Definition at line 58 of file Points.cpp.
getMemSize()
unsigned int PointKernel::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Reimplemented from Data::ComplexGeoData.
Definition at line 151 of file Points.cpp.
getPoint()
const Base::Vector3d Points::PointKernel::getPoint (const int idx) const inline
get the points
Definition at line 197 of file Points.h.
Referenced by Inspection::InspectNominalPoints::getDistance(), Inspection::InspectActualPoints::getPoint(), and Points::PointsGrid::Verify().
getPoints()
void PointKernel::getPoints (std::vector< Base::Vector3d > & Points, std::vector< Base::Vector3d > & Normals, double Accuracy, uint16_t flags = 0) const override virtual
Get points from object with given accuracy
Reimplemented from Data::ComplexGeoData.
Definition at line 252 of file Points.cpp.
References draftguitools.gui_tool_utils::getPoint, and SplineSurface::i.
getSubElement()
Data::Segment * PointKernel::getSubElement (const char * Type, unsigned long) const override virtual
get the subelement by type and number
Implements Data::ComplexGeoData.
Definition at line 71 of file Points.cpp.
getTransform()
Base::Matrix4D Points::PointKernel::getTransform () const inline override virtual
Return the current matrix This method has to be handled by the child classes. the actual placement and matrix is not part of this class.
Implements Data::ComplexGeoData.
Definition at line 123 of file Points.h.
getValidPoints()
std::vector< PointKernel::value_type > PointKernel::getValidPoints () const
Definition at line 167 of file Points.cpp.
load() [1/2]
void PointKernel::load (const char * file)
Definition at line 239 of file Points.cpp.
References DrawingExample::file, and Points::PointsAlgos::Load().
Referenced by Points::AscReader::read().
load() [2/2]
void Points::PointKernel::load (std::istream &)
operator=() [1/2]
PointKernel & PointKernel::operator= (const PointKernel & Kernel)
Definition at line 129 of file Points.cpp.
operator=() [2/2]
PointKernel & PointKernel::operator= (PointKernel && Kernel) noexcept
Definition at line 140 of file Points.cpp.
References Path.Post.scripts.opensbp_post::move().
push_back()
void Points::PointKernel::push_back (const Base::Vector3d & point) inline
insert the points
Definition at line 207 of file Points.h.
Referenced by PointsGui::ViewProviderStructured::cut(), Points::PlyReader::read(), Points::PcdReader::read(), and Points::PropertyPointKernel::removeIndices().
rbegin()
const_reverse_iterator Points::PointKernel::rbegin () const inline
Definition at line 264 of file Points.h.
rend()
const_reverse_iterator Points::PointKernel::rend () const inline
Definition at line 268 of file Points.h.
reserve()
void Points::PointKernel::reserve (size_type n) inline
Definition at line 181 of file Points.h.
Referenced by PointsGui::ViewProviderStructured::cut(), Points::PlyReader::read(), Points::PcdReader::read(), and Points::PropertyPointKernel::removeIndices().
resize()
void Points::PointKernel::resize (size_type n) inline
Definition at line 177 of file Points.h.
Referenced by femsolver.reportdialog.ReportDialog::__init__(), and Points::PointsAlgos::LoadAscii().
Restore()
void PointKernel::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from Data::ComplexGeoData.
Definition at line 201 of file Points.cpp.
References Path.Op.Gui.Selection::clear(), DrawingExample::file, and TechDrawTools.TaskFillTemplateFields::reader.
RestoreDocFile()
void PointKernel::RestoreDocFile (Base::Reader &) override virtual
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data. Again you have to apply for the call of this method in the Restore() call:
void PropertyMeshKernel::Restore(Base::XMLReader &reader)
{
  reader.readElement("Mesh");
  std::string file (reader.getAttribute("file") );
  if(file == "")
  {
    // read XML
    MeshCore::MeshDocXML restorer(*_pcMesh);
    restorer.Restore(reader);
  }else{
    // initiate a file read
    reader.addFile(file.c_str(),this);
 }
}
After you issued the reader.addFile() your RestoreDocFile() is called:
void PropertyMeshKernel::RestoreDocFile(Base::Reader &reader)
{
    _pcMesh->Read( reader );
}
See also
Base::Reader,Base::XMLReader
Reimplemented from Data::ComplexGeoData.
Definition at line 218 of file Points.cpp.
References SplineSurface::i, TechDrawTools.TaskFillTemplateFields::reader, Path.Post.scripts.refactored_centroid_post::str, MovieTool::x, and MovieTool::y.
Save()
void PointKernel::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Reimplemented from Data::ComplexGeoData.
Definition at line 181 of file Points.cpp.
References Base::Writer::addFile(), Base::Writer::ind(), Base::Writer::isForceXML(), Base::Writer::ObjectName, and Base::Writer::Stream().
save() [1/2]
void PointKernel::save (const char * file) const
Definition at line 233 of file Points.cpp.
References DrawingExample::file, and nativeifc.ifc_tools::save().
Referenced by src.Mod.Show.mTempoVis.TempoVis::modify(), src.Mod.Show.mTempoVis.TempoVis::modifyVPProperty(), src.Mod.Show.mTempoVis.TempoVis::saveCamera(), and Points::AscWriter::write().
save() [2/2]
void PointKernel::save (std::ostream & out) const
Definition at line 244 of file Points.cpp.
Referenced by src.Mod.Show.mTempoVis.TempoVis::modify(), src.Mod.Show.mTempoVis.TempoVis::modifyVPProperty(), and src.Mod.Show.mTempoVis.TempoVis::saveCamera().
SaveDocFile()
void PointKernel::SaveDocFile (Base::Writer &) const override virtual
This method is used to save large amounts of data to a binary file. Sometimes it makes no sense to write property data as XML. In case the amount of data is too big or the data type has a more effective way to save itself. In this cases it is possible to write the data in a separate file inside the document archive. In case you want do so you have to re-implement SaveDocFile(). First, you have to inform the framework in Save() that you want do so. Here an example from the Mesh module which can save a (pontetionaly big) triangle mesh:
void PropertyMeshKernel::Save (Base::Writer &writer) const
{
  if (writer.isForceXML())
  {
    writer << writer.ind() << "<Mesh>" << std::endl;
    MeshCore::MeshDocXML saver(*_pcMesh);
    saver.Save(writer);
  }else{
   writer << writer.ind() << "<Mesh file=\"" << writer.addFile("MeshKernel.bms", this) <<
"\"/>" << std::endl;
}
The writer.isForceXML() is an indication to force you to write XML. Regardless of size and effectiveness. The second part informs the Base::writer through writer.addFile("MeshKernel.bms", this) that this object wants to write a file with the given name. The method addFile() returns a unique name that then is written in the XML stream. This allows your RestoreDocFile() method to identify and read the file again. Later your SaveDocFile() method is called as many times as you issued the addFile() call:
 void
PropertyMeshKernel::SaveDocFile (Base::Writer &writer) const
{
    _pcMesh->Write( writer );
}
In this method you can simply stream your content to the file (Base::Writer inheriting from ostream).
Reimplemented from Data::ComplexGeoData.
Definition at line 190 of file Points.cpp.
References Path.Post.scripts.refactored_centroid_post::str, and Base::Writer::Stream().
setBasicPoints()
void Points::PointKernel::setBasicPoints (const std::vector< value_type > & pts) inline
Definition at line 135 of file Points.h.
setPoint()
void Points::PointKernel::setPoint (const int idx, const Base::Vector3d & point) inline
set the points
Definition at line 202 of file Points.h.
Referenced by Points::PointsAlgos::LoadAscii().
setTransform()
void Points::PointKernel::setTransform (const Base::Matrix4D & rclTrf) inline override virtual
Override the current transformation with the new one. This method has to be handled by the child classes. the actual placement and matrix is not part of this class.
Implements Data::ComplexGeoData.
Definition at line 119 of file Points.h.
Referenced by Points::PropertyPointKernel::removeIndices().
size()
size_type Points::PointKernel::size () const inline
number of points stored
Definition at line 171 of file Points.h.
Referenced by Inspection::InspectActualPoints::countPoints(), PointsGui::ViewProviderPointsBuilder::createPoints(), PointsGui::ViewProviderScattered::cut(), PointsGui::ViewProviderStructured::cut(), Path.Post.Utils.GCodeEditorDialog::done(), Points::PointsAlgos::LoadAscii(), Points::AscReader::read(), Points::E57Reader::read(), Points::PointsGrid::RebuildGrid(), Points::PointsGrid::Validate(), Points::PointsGrid::Verify(), Points::PlyWriter::write(), and Points::PcdWriter::write().
swap()
void Points::PointKernel::swap (std::vector< value_type > & pts) inline
Definition at line 139 of file Points.h.
transformGeometry()
void PointKernel::transformGeometry (const Base::Matrix4D & rclMat) override virtual
Applies a transformation on the real geometric data type.
Implements Data::ComplexGeoData.
Definition at line 84 of file Points.cpp.
References Base::Matrix4D::multVec().
The documentation for this class was generated from the following files:
Points.h
Points.cpp