FreeCAD: MeshCore::QuadraticFit Class Reference
MeshCore::QuadraticFit Class Reference
#include <Approximation.h>
Public Member Functions
QuadraticFit ()=default
double GetCoeff (std::size_t ulIndex) const
const double & GetCoeffArray () const
float Fit () override
void CalcZValues (double x, double y, double &dZ1, double &dZ2) const
bool GetCurvatureInfo (double x, double y, double z, double &rfCurv0, double &rfCurv1, Base::Vector3f &rkDir0, Base::Vector3f &rkDir1, double &dDistance)
bool GetCurvatureInfo (double x, double y, double z, double &rfCurv0, double &rfcurv1)
void CalcEigenValues (double &dLambda1, double &dLambda2, double &dLambda3, Base::Vector3f &clEV1, Base::Vector3f &clEV2, Base::Vector3f &clEV3) const
Public Member Functions inherited from MeshCore::Approximation
Approximation ()
virtual ~Approximation ()
void AddPoint (const Base::Vector3f &point)
void AddPoints (const std::vector< Base::Vector3f > &points)
void AddPoints (const std::set< Base::Vector3f > &points)
void AddPoints (const std::list< Base::Vector3f > &points)
void AddPoints (const MeshPointArray &points)
const std::list< Base::Vector3f > & GetPoints () const
Base::Vector3f GetGravity () const
std::size_t CountPoints () const
void Clear ()
float GetLastResult () const
bool Done () const
Additional Inherited Members
Protected Member Functions inherited from MeshCore::Approximation
void GetMgcVectorArray (std::vector< Wm4::Vector3< double >> &rcPts) const
Approximation (const Approximation &)=default
Approximation (Approximation &&)=default
Approximation & operator= (const Approximation &)=default
Approximation & operator= (Approximation &&)=default
Protected Attributes inherited from MeshCore::Approximation
std::list< Base::Vector3f > _vPoints
bool _bIsFitted {false}
float _fLastResult {FLOAT_MAX}
Detailed Description
Approximation of a quadratic surface into a given set of points. The implicit form of the surface is defined by F(x,y,z) = a * x^2 + b * y^2 + c * z^2 + 2d * x * y + 2e * x * z + 2f * y * z + g * x + h * y + * i * z + k = 0 Depending on the parameters (a,..,k) this surface defines a sphere, ellipsoid, cylinder, cone and so on.
Definition at line 286 of file Approximation.h.
Constructor & Destructor Documentation
QuadraticFit()
MeshCore::QuadraticFit::QuadraticFit () default
Member Function Documentation
CalcEigenValues()
void QuadraticFit::CalcEigenValues (double & dLambda1, double & dLambda2, double & dLambda3, Base::Vector3f & clEV1, Base::Vector3f & clEV2, Base::Vector3f & clEV3) const
Compute form matrix A and calculate Eigenvalues.
Parameters
dLambda1 Eigenvalue 1
dLambda2 Eigenvalue 2
dLambda3 Eigenvalue 3
clEV1 Eigenvector 1
clEV2 Eigenvector 2
clEV3 Eigenvector 3
Definition at line 529 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, Wm4::Matrix3< Real >::EigenDecomposition(), and Wm4::Matrix3< Real >::GetColumn().
CalcZValues()
void QuadraticFit::CalcZValues (double x, double y, double & dZ1, double & dZ2) const
Definition at line 586 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, FLOAT_MAX, KDL::sqrt(), MovieTool::x, and MovieTool::y.
Fit()
float QuadraticFit::Fit () override virtual
Invocation of fitting algorithm
Returns
float Quality of fit.
Implements MeshCore::Approximation.
Definition at line 513 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, MeshCore::Approximation::_fLastResult, MeshCore::Approximation::CountPoints(), FLOAT_MAX, MeshCore::Approximation::GetMgcVectorArray(), Wm4::QuadraticFit3< double >(), and Base::Vector3< double >.
GetCoeff()
double QuadraticFit::GetCoeff (std::size_t ulIndex) const
Get the quadric coefficients
Parameters
ulIndex Number of coefficient (0..9)
Returns
double value of coefficient
Definition at line 502 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, and FLOAT_MAX.
GetCoeffArray()
const double & QuadraticFit::GetCoeffArray () const
Get the quadric coefficients as reference to the internal array
Returns
const double& Reference to the double array
Definition at line 497 of file Approximation.cpp.
GetCurvatureInfo() [1/2]
bool QuadraticFit::GetCurvatureInfo (double x, double y, double z, double & rfCurv0, double & rfcurv1)
Definition at line 485 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, MeshCore::FunctionContainer::CurvatureInfo(), MovieTool::x, and MovieTool::y.
GetCurvatureInfo() [2/2]
bool QuadraticFit::GetCurvatureInfo (double x, double y, double z, double & rfCurv0, double & rfCurv1, Base::Vector3f & rkDir0, Base::Vector3f & rkDir1, double & dDistance)
Calculate the curvatures of the quadric at a given point.
Parameters
x X-coordinate
y Y-coordinate
z Z-coordinate
rfCurv0 1. principal curvature
rfCurv1 2. principal curvature
rkDir0 Direction of 1. principal curvature
rkDir1 Direction of 2. principal curvature
dDistance
Returns
bool Success = true, otherwise false
Definition at line 460 of file Approximation.cpp.
References MeshCore::Approximation::_bIsFitted, MeshCore::FunctionContainer::CurvatureInfo(), MeshCore::FunctionContainer::GetGradient(), Base::Vector3< float_type >::Length(), MovieTool::x, and MovieTool::y.
The documentation for this class was generated from the following files:
Approximation.h
Approximation.cpp