FreeCAD: ArchCurtainWall.ViewProviderCurtainWall Class Reference
ArchCurtainWall.ViewProviderCurtainWall Class Reference
Public Member Functions
def __init__ (self, vobj)
def getIcon (self)
def updateData (self, obj, prop)
def onChanged (self, vobj, prop)
def colorize (self, obj, force=False)
Public Member Functions inherited from ArchComponent.ViewProviderComponent
def setProperties (self, vobj)
def attach (self, vobj)
def getDisplayModes (self, vobj)
def setDisplayMode (self, mode)
def dumps (self)
def loads (self, state)
def claimChildren (self)
def setEdit (self, vobj, mode)
def unsetEdit (self, vobj, mode)
def setupContextMenu (self, vobj, menu)
def contextMenuAddEdit (self, menu)
def contextMenuAddToggleSubcomponents (self, menu)
def edit (self)
def toggleSubcomponents (self)
def areDifferentColors (self, a, b)
Additional Inherited Members
Public Attributes inherited from ArchComponent.ViewProviderComponent
Object
hiresgroup
meshcolor
meshnode
Detailed Description
Definition at line 497 of file ArchCurtainWall.py.
Constructor & Destructor Documentation
__init__()
def ArchCurtainWall.ViewProviderCurtainWall.__init__ (self, vobj)
Reimplemented from ArchComponent.ViewProviderComponent.
Definition at line 502 of file ArchCurtainWall.py.
References ArchComponent.ViewProviderComponent.__init__().
Referenced by draftguitools.gui_subelements.SubelementHighlight.finish().
Member Function Documentation
colorize()
def ArchCurtainWall.ViewProviderCurtainWall.colorize (self, obj, force = False)
If an object is a clone, set it to copy the color of its parent.
Only change the color of the clone if the clone and its parent have
colors that are distinguishably different from each other.
Parameters
----------
obj: <Part::Feature>
    The object to change the color of.
force: bool
    If true, forces the colourisation even if the two objects have very
    similar colors.
Reimplemented from ArchComponent.ViewProviderComponent.
Definition at line 524 of file ArchCurtainWall.py.
References ArchComponent.ViewProviderComponent.areDifferentColors(), and ArchCommands.getDefaultColor().
getIcon()
def ArchCurtainWall.ViewProviderCurtainWall.getIcon (self)
Return the path to the appropriate icon.
If a clone, return the cloned component icon path. Otherwise return the
Arch Component icon.
Returns
-------
str
    Path to the appropriate icon .svg file.
Reimplemented from ArchComponent.ViewProviderComponent.
Definition at line 506 of file ArchCurtainWall.py.
Referenced by ArchWindow._ArchWindowTaskPanel.update(), ArchSectionPlane.SectionPlaneTaskPanel.update(), bimcommands.BimClassification.BIM_Classification.updateByMaterial(), bimcommands.BimClassification.BIM_Classification.updateByTree(), bimcommands.BimClassification.BIM_Classification.updateByType(), and bimcommands.BimClassification.BIM_Classification.updateDefault().
onChanged()
def ArchCurtainWall.ViewProviderCurtainWall.onChanged (self, vobj, prop)
Method called when the view provider has a property changed.
If DiffuseColor changes, change DiffuseColor to copy the host object's
clone, if it exists.
If ShapeColor changes, overwrite it with DiffuseColor.
If Visibility changes, propagate the change to all view objects that
are also hosted by this view object's host.
Parameters
----------
vobj: <Gui.ViewProviderDocumentObject>
    The component's view provider object.
prop: string
    The name of the property that has changed.
Reimplemented from ArchComponent.ViewProviderComponent.
Definition at line 516 of file ArchCurtainWall.py.
References ArchComponent.ViewProviderComponent.colorize(), and ArchComponent.ViewProviderComponent.onChanged().
Referenced by draftviewproviders.view_base.ViewProviderDraft.attach(), ArchSchedule._ArchSchedule.setProperties(), draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy.updateData(), draftviewproviders.view_layer.ViewProviderLayer.updateData(), draftviewproviders.view_label.ViewProviderLabel.updateData(), draftviewproviders.view_dimension.ViewProviderLinearDimension.updateData(), ArchPanel.ViewProviderPanelCut.updateData(), ArchSite._ViewProviderSite.updateData(), ArchSectionPlane._ViewProviderSectionPlane.updateData(), and ArchPanel.ViewProviderPanelSheet.updateData().
updateData()
def ArchCurtainWall.ViewProviderCurtainWall.updateData (self, obj, prop)
Method called when the host object has a property changed.
If the object has a Material associated with it, match the view
object's ShapeColor and Transparency to match the Material.
If the object is now cloned, or is part of a compound, have the view
object inherit the DiffuseColor.
Parameters
----------
obj: <App::FeaturePython>
    The host object that has changed.
prop: string
    The name of the property that has changed.
Reimplemented from ArchComponent.ViewProviderComponent.
Definition at line 511 of file ArchCurtainWall.py.
References ArchComponent.ViewProviderComponent.colorize().
Referenced by Path.Main.Gui.JobDlg.JobCreate.exec_(), draftviewproviders.view_wire.ViewProviderWire.onChanged(), draftviewproviders.view_dimension.ViewProviderLinearDimension.onChanged(), draftviewproviders.view_dimension.ViewProviderAngularDimension.onChanged(), Path.Op.Gui.Base.TaskPanelPage.pageUpdateData(), Path.Base.Gui.SetupSheet.OpTaskPanel.setupUi(), and Path.Base.Gui.PropertyBag.TaskPanel.setupUi().
The documentation for this class was generated from the following file:
ArchCurtainWall.py