FreeCAD: AppSurfaceGui.cpp File Reference
AppSurfaceGui.cpp File Reference
#include "PreCompiled.h"
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/PyObjectBase.h>
#include <Gui/Application.h>
#include "Blending/ViewProviderBlendCurve.h"
#include "TaskFilling.h"
#include "TaskGeomFillSurface.h"
#include "TaskSections.h"
#include "ViewProviderExtend.h"
#include "Workbench.h"
Classes
class SurfaceGui::Module
Namespaces
SurfaceGui
Functions
void CreateSurfaceCommands ()
PyObject * SurfaceGui::initModule ()
PyMOD_INIT_FUNC (SurfaceGui)
Function Documentation
CreateSurfaceCommands()
void CreateSurfaceCommands ()
Definition at line 348 of file Mod/Surface/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (SurfaceGui)
Definition at line 66 of file AppSurfaceGui.cpp.
References Base::Console(), CreateSurfaceCommands(), Base::Persistence::init(), Base::BaseClass::init(), SurfaceGui::initModule(), Gui::Application::Instance, Base::Interpreter(), Base::ConsoleSingleton::Log(), mod, PyMOD_Return, and Base::InterpreterSingleton::runString().