FreeCAD: ifc2x3.ifcstructuralprofileproperties Class Reference
ifc2x3.ifcstructuralprofileproperties Class Reference
Public Member Functions
def __init__ (self, inherited0__profilename, inherited1__profiledefinition, inherited2__physicalweight, inherited3__perimeter, inherited4__minimumplatethickness, inherited5__maximumplatethickness, inherited6__crosssectionarea, torsionalconstantx, momentofinertiayz, momentofinertiay, momentofinertiaz, warpingconstant, shearcentrez, shearcentrey, sheardeformationareaz, sheardeformationareay, maximumsectionmodulusy, minimumsectionmodulusy, maximumsectionmodulusz, minimumsectionmodulusz, torsionalsectionmodulus, centreofgravityinx, centreofgravityiny)
def torsionalconstantx ()
def momentofinertiayz ()
def momentofinertiay ()
def momentofinertiaz ()
def warpingconstant ()
def shearcentrez ()
def shearcentrey ()
def sheardeformationareaz ()
def sheardeformationareay ()
def maximumsectionmodulusy ()
def minimumsectionmodulusy ()
def maximumsectionmodulusz ()
def minimumsectionmodulusz ()
def torsionalsectionmodulus ()
def centreofgravityinx ()
def centreofgravityiny ()
def wr21 (self)
def wr22 (self)
Public Member Functions inherited from ifc2x3.ifcgeneralprofileproperties
def __init__ (self, inherited0__profilename, inherited1__profiledefinition, physicalweight, perimeter, minimumplatethickness, maximumplatethickness, crosssectionarea)
def physicalweight ()
def perimeter ()
def minimumplatethickness ()
def maximumplatethickness ()
def crosssectionarea ()
def wr1 (self)
Public Member Functions inherited from ifc2x3.ifcprofileproperties
def __init__ (self, profilename, profiledefinition)
def profilename ()
def profiledefinition ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
torsionalconstantx
momentofinertiayz
momentofinertiay
momentofinertiaz
warpingconstant
shearcentrez
shearcentrey
sheardeformationareaz
sheardeformationareay
maximumsectionmodulusy
minimumsectionmodulusy
maximumsectionmodulusz
minimumsectionmodulusz
torsionalsectionmodulus
centreofgravityinx
centreofgravityiny
Public Attributes inherited from ifc2x3.ifcgeneralprofileproperties
physicalweight
perimeter
minimumplatethickness
maximumplatethickness
crosssectionarea
Public Attributes inherited from ifc2x3.ifcprofileproperties
profilename
profiledefinition
Detailed Description
Entity ifcstructuralprofileproperties definition.
:param torsionalconstantx
:type torsionalconstantx:ifcmomentofinertiameasure
:param momentofinertiayz
:type momentofinertiayz:ifcmomentofinertiameasure
:param momentofinertiay
:type momentofinertiay:ifcmomentofinertiameasure
:param momentofinertiaz
:type momentofinertiaz:ifcmomentofinertiameasure
:param warpingconstant
:type warpingconstant:ifcwarpingconstantmeasure
:param shearcentrez
:type shearcentrez:ifclengthmeasure
:param shearcentrey
:type shearcentrey:ifclengthmeasure
:param sheardeformationareaz
:type sheardeformationareaz:ifcareameasure
:param sheardeformationareay
:type sheardeformationareay:ifcareameasure
:param maximumsectionmodulusy
:type maximumsectionmodulusy:ifcsectionmodulusmeasure
:param minimumsectionmodulusy
:type minimumsectionmodulusy:ifcsectionmodulusmeasure
:param maximumsectionmodulusz
:type maximumsectionmodulusz:ifcsectionmodulusmeasure
:param minimumsectionmodulusz
:type minimumsectionmodulusz:ifcsectionmodulusmeasure
:param torsionalsectionmodulus
:type torsionalsectionmodulus:ifcsectionmodulusmeasure
:param centreofgravityinx
:type centreofgravityinx:ifclengthmeasure
:param centreofgravityiny
:type centreofgravityiny:ifclengthmeasure
Definition at line 5087 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcstructuralprofileproperties.__init__ (self, inherited0__profilename, inherited1__profiledefinition, inherited2__physicalweight, inherited3__perimeter, inherited4__minimumplatethickness, inherited5__maximumplatethickness, inherited6__crosssectionarea, torsionalconstantx, momentofinertiayz, momentofinertiay, momentofinertiaz, warpingconstant, shearcentrez, shearcentrey, sheardeformationareaz, sheardeformationareay, maximumsectionmodulusy, minimumsectionmodulusy, maximumsectionmodulusz, minimumsectionmodulusz, torsionalsectionmodulus, centreofgravityinx, centreofgravityiny)
Definition at line 5138 of file ifc2x3.py.
Member Function Documentation
centreofgravityinx()
def ifc2x3.ifcstructuralprofileproperties.centreofgravityinx ()
Definition at line 5354 of file ifc2x3.py.
References ifc2x3.ifcstructuralprofileproperties._centreofgravityinx, ifc2x3.ifcstructuralprofileproperties.centreofgravityinx, and SCL.TypeChecker.check_type().
centreofgravityiny()
def ifc2x3.ifcstructuralprofileproperties.centreofgravityiny ()
Definition at line 5368 of file ifc2x3.py.
References ifc2x3.ifccranerailashapeprofiledef._centreofgravityiny, ifc2x3.ifcstructuralprofileproperties._centreofgravityiny, ifc2x3.ifcstructuralprofileproperties.centreofgravityiny, and SCL.TypeChecker.check_type().
maximumsectionmodulusy()
def ifc2x3.ifcstructuralprofileproperties.maximumsectionmodulusy ()
Definition at line 5284 of file ifc2x3.py.
References ifc2x3.ifcstructuralprofileproperties._maximumsectionmodulusy, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralprofileproperties.maximumsectionmodulusy.
maximumsectionmodulusz()
def ifc2x3.ifcstructuralprofileproperties.maximumsectionmodulusz ()
Definition at line 5312 of file ifc2x3.py.
References ifc2x3.ifcstructuralprofileproperties._maximumsectionmodulusz, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralprofileproperties.maximumsectionmodulusz.
minimumsectionmodulusy()
def ifc2x3.ifcstructuralprofileproperties.minimumsectionmodulusy ()
Definition at line 5298 of file ifc2x3.py.
References ifc2x3.ifcstructuralprofileproperties._minimumsectionmodulusy, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralprofileproperties.minimumsectionmodulusy.
minimumsectionmodulusz()
def ifc2x3.ifcstructuralprofileproperties.minimumsectionmodulusz ()
Definition at line 5326 of file ifc2x3.py.
References ifc2x3.ifcstructuralprofileproperties._minimumsectionmodulusz, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralprofileproperties.minimumsectionmodulusz.
momentofinertiay()
def ifc2x3.ifcstructuralprofileproperties.momentofinertiay ()
Definition at line 5186 of file ifc2x3.py.
References ifc2x3.ifcstructuralprofileproperties._momentofinertiay, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralprofileproperties.momentofinertiay.
momentofinertiayz()
def ifc2x3.ifcstructuralprofileproperties.momentofinertiayz ()
Definition at line 5172 of file ifc2x3.py.
References ifc2x3.ifcstructuralprofileproperties._momentofinertiayz, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralprofileproperties.momentofinertiayz.
momentofinertiaz()
def ifc2x3.ifcstructuralprofileproperties.momentofinertiaz ()
Definition at line 5200 of file ifc2x3.py.
References ifc2x3.ifcstructuralprofileproperties._momentofinertiaz, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralprofileproperties.momentofinertiaz.
shearcentrey()
def ifc2x3.ifcstructuralprofileproperties.shearcentrey ()
Definition at line 5242 of file ifc2x3.py.
References ifc2x3.ifcstructuralprofileproperties._shearcentrey, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralprofileproperties.shearcentrey.
shearcentrez()
def ifc2x3.ifcstructuralprofileproperties.shearcentrez ()
Definition at line 5228 of file ifc2x3.py.
References ifc2x3.ifcstructuralprofileproperties._shearcentrez, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralprofileproperties.shearcentrez.
sheardeformationareay()
def ifc2x3.ifcstructuralprofileproperties.sheardeformationareay ()
Definition at line 5270 of file ifc2x3.py.
References ifc2x3.ifcstructuralprofileproperties._sheardeformationareay, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralprofileproperties.sheardeformationareay.
sheardeformationareaz()
def ifc2x3.ifcstructuralprofileproperties.sheardeformationareaz ()
Definition at line 5256 of file ifc2x3.py.
References ifc2x3.ifcstructuralprofileproperties._sheardeformationareaz, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralprofileproperties.sheardeformationareaz.
torsionalconstantx()
def ifc2x3.ifcstructuralprofileproperties.torsionalconstantx ()
Definition at line 5158 of file ifc2x3.py.
References ifc2x3.ifcstructuralprofileproperties._torsionalconstantx, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralprofileproperties.torsionalconstantx.
torsionalsectionmodulus()
def ifc2x3.ifcstructuralprofileproperties.torsionalsectionmodulus ()
Definition at line 5340 of file ifc2x3.py.
References ifc2x3.ifcstructuralprofileproperties._torsionalsectionmodulus, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralprofileproperties.torsionalsectionmodulus.
warpingconstant()
def ifc2x3.ifcstructuralprofileproperties.warpingconstant ()
Definition at line 5214 of file ifc2x3.py.
References ifc2x3.ifcstructuralprofileproperties._warpingconstant, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralprofileproperties.warpingconstant.
wr21()
def ifc2x3.ifcstructuralprofileproperties.wr21 (self)
Definition at line 5380 of file ifc2x3.py.
References SCL.Builtin.EXISTS(), and ifc2x3.ifcstructuralprofileproperties.sheardeformationareay.
Referenced by ifc4.ifcphmeasure.__init__().
wr22()
def ifc2x3.ifcstructuralprofileproperties.wr22 (self)
Definition at line 5387 of file ifc2x3.py.
References SCL.Builtin.EXISTS(), and ifc2x3.ifcstructuralprofileproperties.sheardeformationareaz.
Member Data Documentation
centreofgravityinx
ifc2x3.ifcstructuralprofileproperties.centreofgravityinx
Definition at line 5154 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralprofileproperties.centreofgravityinx().
centreofgravityiny
ifc2x3.ifcstructuralprofileproperties.centreofgravityiny
Definition at line 5155 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralprofileproperties.centreofgravityiny().
maximumsectionmodulusy
ifc2x3.ifcstructuralprofileproperties.maximumsectionmodulusy
Definition at line 5149 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralprofileproperties.maximumsectionmodulusy().
maximumsectionmodulusz
ifc2x3.ifcstructuralprofileproperties.maximumsectionmodulusz
Definition at line 5151 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralprofileproperties.maximumsectionmodulusz().
minimumsectionmodulusy
ifc2x3.ifcstructuralprofileproperties.minimumsectionmodulusy
Definition at line 5150 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralprofileproperties.minimumsectionmodulusy().
minimumsectionmodulusz
ifc2x3.ifcstructuralprofileproperties.minimumsectionmodulusz
Definition at line 5152 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralprofileproperties.minimumsectionmodulusz().
momentofinertiay
ifc2x3.ifcstructuralprofileproperties.momentofinertiay
Definition at line 5142 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralprofileproperties.momentofinertiay().
momentofinertiayz
ifc2x3.ifcstructuralprofileproperties.momentofinertiayz
Definition at line 5141 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralprofileproperties.momentofinertiayz().
momentofinertiaz
ifc2x3.ifcstructuralprofileproperties.momentofinertiaz
Definition at line 5143 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralprofileproperties.momentofinertiaz().
shearcentrey
ifc2x3.ifcstructuralprofileproperties.shearcentrey
Definition at line 5146 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralprofileproperties.shearcentrey().
shearcentrez
ifc2x3.ifcstructuralprofileproperties.shearcentrez
Definition at line 5145 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralprofileproperties.shearcentrez().
sheardeformationareay
ifc2x3.ifcstructuralprofileproperties.sheardeformationareay
Definition at line 5148 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralprofileproperties.sheardeformationareay(), and ifc2x3.ifcstructuralprofileproperties.wr21().
sheardeformationareaz
ifc2x3.ifcstructuralprofileproperties.sheardeformationareaz
Definition at line 5147 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralprofileproperties.sheardeformationareaz(), and ifc2x3.ifcstructuralprofileproperties.wr22().
torsionalconstantx
ifc2x3.ifcstructuralprofileproperties.torsionalconstantx
Definition at line 5140 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralprofileproperties.torsionalconstantx().
torsionalsectionmodulus
ifc2x3.ifcstructuralprofileproperties.torsionalsectionmodulus
Definition at line 5153 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralprofileproperties.torsionalsectionmodulus().
warpingconstant
ifc2x3.ifcstructuralprofileproperties.warpingconstant
Definition at line 5144 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralprofileproperties.warpingconstant().
The documentation for this class was generated from the following file:
ifc2x3.py