FreeCAD: Wm4::Vector3< Real > Class Template Reference
Wm4::Vector3< Real > Class Template Reference
#include <Wm4Vector3.h>
Public Member Functions
Vector3 ()
Vector3 (Real fX, Real fY, Real fZ)
Vector3 (const Real *afTuple)
Vector3 (const Vector3 &rkV)
operator const Real * () const
operator Real * ()
Real operator[] (int i) const
Real & operator[] (int i)
Real X () const
Real & X ()
Real Y () const
Real & Y ()
Real Z () const
Real & Z ()
Vector3 & operator= (const Vector3 &rkV)
bool operator== (const Vector3 &rkV) const
bool operator!= (const Vector3 &rkV) const
bool operator< (const Vector3 &rkV) const
bool operator<= (const Vector3 &rkV) const
bool operator> (const Vector3 &rkV) const
bool operator>= (const Vector3 &rkV) const
Vector3 operator+ (const Vector3 &rkV) const
Vector3 operator- (const Vector3 &rkV) const
Vector3 operator* (Real fScalar) const
Vector3 operator/ (Real fScalar) const
Vector3 operator- () const
Vector3 & operator+= (const Vector3 &rkV)
Vector3 & operator-= (const Vector3 &rkV)
Vector3 & operator*= (Real fScalar)
Vector3 & operator/= (Real fScalar)
Real Length () const
Real SquaredLength () const
Real Dot (const Vector3 &rkV) const
Real Normalize ()
Vector3 Cross (const Vector3 &rkV) const
Vector3 UnitCross (const Vector3 &rkV) const
void GetBarycentrics (const Vector3 &rkV0, const Vector3 &rkV1, const Vector3 &rkV2, const Vector3 &rkV3, Real afBary[4]) const
const Vector3< float > ZERO (0.0f, 0.0f, 0.0f)
const Vector3< float > UNIT_X (1.0f, 0.0f, 0.0f)
const Vector3< float > UNIT_Y (0.0f, 1.0f, 0.0f)
const Vector3< float > UNIT_Z (0.0f, 0.0f, 1.0f)
const Vector3< float > ONE (1.0f, 1.0f, 1.0f)
Static Public Member Functions
static void Orthonormalize (Vector3 &rkU, Vector3 &rkV, Vector3 &rkW)
static void Orthonormalize (Vector3 *akV)
static void GenerateOrthonormalBasis (Vector3 &rkU, Vector3 &rkV, Vector3 &rkW)
static void GenerateComplementBasis (Vector3 &rkU, Vector3 &rkV, const Vector3 &rkW)
static void ComputeExtremes (int iVQuantity, const Vector3 *akPoint, Vector3 &rkMin, Vector3 &rkMax)
Static Public Attributes
static const Vector3 ZERO
static const Vector3 UNIT_X
static const Vector3 UNIT_Y
static const Vector3 UNIT_Z
static const Vector3 ONE
Detailed Description
template<class Real>
class Wm4::Vector3< Real >
Definition at line 27 of file Wm4Vector3.h.
Constructor & Destructor Documentation
Vector3() [1/4]
template<class Real > Wm4::Vector3< Real >::Vector3 ()
Vector3() [2/4]
template<class Real > Wm4::Vector3< Real >::Vector3 (Real fX, Real fY, Real fZ)
Vector3() [3/4]
template<class Real > Wm4::Vector3< Real >::Vector3 (const Real * afTuple)
Vector3() [4/4]
template<class Real > Wm4::Vector3< Real >::Vector3 (const Vector3< Real > & rkV)
Member Function Documentation
ComputeExtremes()
template<class Real > static void Wm4::Vector3< Real >::ComputeExtremes (int iVQuantity, const Vector3< Real > * akPoint, Vector3< Real > & rkMin, Vector3< Real > & rkMax) static
Referenced by Wm4::ContAlignedBox().
Cross()
template<class Real > Vector3 Wm4::Vector3< Real >::Cross (const Vector3< Real > & rkV) const
Referenced by Wm4::ParametricSurface< Real >::ComputePrincipalCurvatureInfo(), Wm4::ParametricSurface< Real >::GetFrame(), Wm4::MeshCurvature< Real >::MeshCurvature(), Wm4::IntrLine3Box3< Real >::Test(), Wm4::IntrSegment3Box3< Real >::Test(), and Wm4::MeshSmoother< Real >::Update().
Dot()
template<class Real > Real Wm4::Vector3< Real >::Dot (const Vector3< Real > & rkV) const
Referenced by Wm4::ParametricSurface< Real >::ComputePrincipalCurvatureInfo(), Wm4::ContMinBox(), Wm4::ContOrientedBox(), Wm4::CylinderFit3< Real >::CylinderFit3(), Wm4::IntrLine3Box3< Real >::DoClipping(), Wm4::QuadricSurface< Real >::F(), Wm4::IntrTriangle3Triangle3< Real >::Find(), MeshCore::PlaneFit::Fit(), Wm4::DistVector3Plane3< Real >::Get(), Wm4::ConvexHull3< Real >::GetConvexHull1(), Wm4::Delaunay3< Real >::GetDelaunay1(), Wm4::DistSegment3Segment3< Real >::GetSquared(), Wm4::DistVector3Segment3< Real >::GetSquared(), Wm4::DistVector3Triangle3< Real >::GetSquared(), Wm4::DistLine3Segment3< Real >::GetSquared(), Wm4::DistLine3Triangle3< Real >::GetSquared(), Wm4::DistVector3Plane3< Real >::GetSquared(), Wm4::InBox(), Wm4::MergeBoxes(), Wm4::MeshCurvature< Real >::MeshCurvature(), Wm4::IntrLine3Box3< Real >::Test(), Wm4::IntrSegment3Box3< Real >::Test(), Wm4::IntrTriangle3Triangle3< Real >::Test(), and Wm4::MeshSmoother< Real >::Update().
GenerateComplementBasis()
template<class Real > static void Wm4::Vector3< Real >::GenerateComplementBasis (Vector3< Real > & rkU, Vector3< Real > & rkV, const Vector3< Real > & rkW) static
Referenced by Wm4::ContMinBox(), and Wm4::MeshCurvature< Real >::MeshCurvature().
GenerateOrthonormalBasis()
template<class Real > static void Wm4::Vector3< Real >::GenerateOrthonormalBasis (Vector3< Real > & rkU, Vector3< Real > & rkV, Vector3< Real > & rkW) static
Referenced by MeshCore::PlaneFit::Fit(), and Wm4::ImplicitSurface< double >::GetFrame().
GetBarycentrics()
template<class Real > void Wm4::Vector3< Real >::GetBarycentrics (const Vector3< Real > & rkV0, const Vector3< Real > & rkV1, const Vector3< Real > & rkV2, const Vector3< Real > & rkV3, Real afBary[4]) const
Referenced by Wm4::Delaunay3< Real >::GetBarycentricSet().
Length()
template<class Real > Real Wm4::Vector3< Real >::Length () const
Referenced by Wm4::ImplicitSurface< double >::ComputePrincipalCurvatureInfo(), MeshCore::MeshGeomFacet::DistanceToLineSegment(), MeshCore::MeshGeomEdge::IntersectBoundingBox(), and Wm4::SphereFit3().
Normalize()
template<class Real > Real Wm4::Vector3< Real >::Normalize ()
Referenced by Wm4::ParametricSurface< Real >::ComputePrincipalCurvatureInfo(), Wm4::ContMinBox(), MeshCore::MeshGeomFacet::DistanceToLineSegment(), Wm4::ParametricSurface< Real >::GetFrame(), MeshCore::MeshGeomEdge::IntersectBoundingBox(), MeshCore::MeshGeomFacet::IntersectBoundingBox(), MeshCore::MeshGeomFacet::IntersectWithPlane(), Wm4::MeshCurvature< Real >::MeshCurvature(), and Wm4::MeshSmoother< Real >::Update().
ONE()
const Vector3< float > Wm4::Vector3< float >::ONE (1. 0f, 1. 0f, 1. 0f)
operator const Real *()
template<class Real > Wm4::Vector3< Real >::operator const Real * () const
operator Real *()
template<class Real > Wm4::Vector3< Real >::operator Real * ()
operator!=()
template<class Real > bool Wm4::Vector3< Real >::operator!= (const Vector3< Real > & rkV) const
operator*()
template<class Real > Vector3 Wm4::Vector3< Real >::operator* (Real fScalar) const
operator*=()
template<class Real > Vector3& Wm4::Vector3< Real >::operator*= (Real fScalar)
operator+()
template<class Real > Vector3 Wm4::Vector3< Real >::operator+ (const Vector3< Real > & rkV) const
operator+=()
template<class Real > Vector3& Wm4::Vector3< Real >::operator+= (const Vector3< Real > & rkV)
operator-() [1/2]
template<class Real > Vector3 Wm4::Vector3< Real >::operator- () const
operator-() [2/2]
template<class Real > Vector3 Wm4::Vector3< Real >::operator- (const Vector3< Real > & rkV) const
operator-=()
template<class Real > Vector3& Wm4::Vector3< Real >::operator-= (const Vector3< Real > & rkV)
operator/()
template<class Real > Vector3 Wm4::Vector3< Real >::operator/ (Real fScalar) const
operator/=()
template<class Real > Vector3& Wm4::Vector3< Real >::operator/= (Real fScalar)
operator<()
template<class Real > bool Wm4::Vector3< Real >::operator< (const Vector3< Real > & rkV) const
operator<=()
template<class Real > bool Wm4::Vector3< Real >::operator<= (const Vector3< Real > & rkV) const
operator=()
template<class Real > Vector3& Wm4::Vector3< Real >::operator= (const Vector3< Real > & rkV)
operator==()
template<class Real > bool Wm4::Vector3< Real >::operator== (const Vector3< Real > & rkV) const
operator>()
template<class Real > bool Wm4::Vector3< Real >::operator> (const Vector3< Real > & rkV) const
operator>=()
template<class Real > bool Wm4::Vector3< Real >::operator>= (const Vector3< Real > & rkV) const
operator[]() [1/2]
template<class Real > Real& Wm4::Vector3< Real >::operator[] (int i)
operator[]() [2/2]
template<class Real > Real Wm4::Vector3< Real >::operator[] (int i) const
Orthonormalize() [1/2]
template<class Real > static void Wm4::Vector3< Real >::Orthonormalize (Vector3< Real > & rkU, Vector3< Real > & rkV, Vector3< Real > & rkW) static
Orthonormalize() [2/2]
template<class Real > static void Wm4::Vector3< Real >::Orthonormalize (Vector3< Real > * akV) static
SquaredLength()
template<class Real > Real Wm4::Vector3< Real >::SquaredLength () const
Referenced by Wm4::DistSegment3Segment3< Real >::GetSquared(), Wm4::DistVector3Triangle3< Real >::GetSquared(), Wm4::DistVector3Segment3< Real >::GetSquared(), and Wm4::DistLine3Segment3< Real >::GetSquared().
UNIT_X()
const Vector3< float > Wm4::Vector3< float >::UNIT_X (1. 0f, 0. 0f, 0. 0f)
UNIT_Y()
const Vector3< float > Wm4::Vector3< float >::UNIT_Y (0. 0f, 1. 0f, 0. 0f)
UNIT_Z()
const Vector3< float > Wm4::Vector3< float >::UNIT_Z (0. 0f, 0. 0f, 1. 0f)
UnitCross()
template<class Real > Vector3 Wm4::Vector3< Real >::UnitCross (const Vector3< Real > & rkV) const
Referenced by Wm4::ParametricSurface< Real >::ComputePrincipalCurvatureInfo(), Wm4::ImplicitSurface< double >::ComputePrincipalCurvatureInfo(), Wm4::ContMinBox(), Wm4::IntrTriangle3Triangle3< Real >::Find(), Wm4::ParametricSurface< Real >::GetFrame(), Wm4::DistLine3Triangle3< Real >::GetSquared(), and Wm4::IntrTriangle3Triangle3< Real >::Test().
X() [1/2]
template<class Real > Real& Wm4::Vector3< Real >::X ()
X() [2/2]
template<class Real > Real Wm4::Vector3< Real >::X () const
Referenced by MeshCore::MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection(), Wm4::ImplicitSurface< double >::ComputePrincipalCurvatureInfo(), MeshCore::MeshGeomFacet::DistanceToPoint(), Wm4::IntrLine3Box3< Real >::DoClipping(), MeshCore::PlaneFit::Fit(), Wm4::GaussPointsFit3(), MeshCore::FunctionContainer::GetGradient(), Wm4::HeightPlaneFit3(), Wm4::OrthogonalLineFit3(), Wm4::OrthogonalPlaneFit3(), Wm4::QuadraticFit3(), Wm4::QuadraticSphereFit3(), and Wm4::SphereFit3().
Y() [1/2]
template<class Real > Real& Wm4::Vector3< Real >::Y ()
Y() [2/2]
template<class Real > Real Wm4::Vector3< Real >::Y () const
Referenced by MeshCore::MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection(), Wm4::ImplicitSurface< double >::ComputePrincipalCurvatureInfo(), MeshCore::MeshGeomFacet::DistanceToPoint(), Wm4::IntrLine3Box3< Real >::DoClipping(), MeshCore::PlaneFit::Fit(), Wm4::GaussPointsFit3(), MeshCore::FunctionContainer::GetGradient(), Wm4::HeightPlaneFit3(), Wm4::OrthogonalLineFit3(), Wm4::OrthogonalPlaneFit3(), Wm4::QuadraticFit3(), Wm4::QuadraticSphereFit3(), and Wm4::SphereFit3().
Z() [1/2]
template<class Real > Real& Wm4::Vector3< Real >::Z ()
Z() [2/2]
template<class Real > Real Wm4::Vector3< Real >::Z () const
Referenced by MeshCore::MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection(), Wm4::ImplicitSurface< double >::ComputePrincipalCurvatureInfo(), MeshCore::MeshGeomFacet::DistanceToPoint(), Wm4::IntrLine3Box3< Real >::DoClipping(), MeshCore::PlaneFit::Fit(), Wm4::GaussPointsFit3(), MeshCore::FunctionContainer::GetGradient(), Wm4::HeightPlaneFit3(), Wm4::OrthogonalLineFit3(), Wm4::OrthogonalPlaneFit3(), Wm4::QuadraticFit3(), Wm4::QuadraticSphereFit3(), and Wm4::SphereFit3().
ZERO()
const Vector3< float > Wm4::Vector3< float >::ZERO (0. 0f, 0. 0f, 0. 0f)
Member Data Documentation
ONE
template<class Real > const Vector3 Wm4::Vector3< Real >::ONE static
Definition at line 120 of file Wm4Vector3.h.
UNIT_X
template<class Real > const Vector3 Wm4::Vector3< Real >::UNIT_X static
Definition at line 117 of file Wm4Vector3.h.
UNIT_Y
template<class Real > const Vector3 Wm4::Vector3< Real >::UNIT_Y static
Definition at line 118 of file Wm4Vector3.h.
UNIT_Z
template<class Real > const Vector3 Wm4::Vector3< Real >::UNIT_Z static
Definition at line 119 of file Wm4Vector3.h.
ZERO
template<class Real > const Vector3 Wm4::Vector3< Real >::ZERO static
Definition at line 116 of file Wm4Vector3.h.
The documentation for this class was generated from the following file:
Wm4Vector3.h