FreeCAD: ifc2x3.ifcrelnests Class Reference
ifc2x3.ifcrelnests Class Reference
Public Member Functions
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__relatingobject, inherited5__relatedobjects)
def wr1 (self)
Public Member Functions inherited from ifc2x3.ifcreldecomposes
def relatingobject ()
def relatedobjects ()
def wr31 (self)
Public Member Functions inherited from ifc2x3.ifcrelationship
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description)
Public Member Functions inherited from ifc2x3.ifcroot
def globalid ()
def ownerhistory ()
def name ()
def description ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Additional Inherited Members
Public Attributes inherited from ifc2x3.ifcreldecomposes
relatingobject
relatedobjects
Public Attributes inherited from ifc2x3.ifcroot
globalid
ownerhistory
name
description
Detailed Description
Entity ifcrelnests definition.
Definition at line 6809 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcrelnests.__init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__relatingobject, inherited5__relatedobjects)
Reimplemented from ifc2x3.ifcreldecomposes.
Definition at line 6812 of file ifc2x3.py.
Member Function Documentation
wr1()
def ifc2x3.ifcrelnests.wr1 (self)
Definition at line 6814 of file ifc2x3.py.
References SCL.Builtin.SIZEOF().
Referenced by ifc4.ifctextalignment.__init__(), ifc4.ifcspecularroughness.__init__(), ifc4.ifcheatingvaluemeasure.__init__(), ifc4.ifctexttransformation.__init__(), ifc4.ifcfontstyle.__init__(), ifc4.ifcboxalignment.__init__(), ifc4.ifcpositiveplaneanglemeasure.__init__(), ifc4.ifcdimensioncount.__init__(), ifc4.ifcfontvariant.__init__(), ifc4.ifcfontweight.__init__(), ifc4.ifcnormalisedratiomeasure.__init__(), ifc4.ifcpositivelengthmeasure.__init__(), ifc4.ifcpositiveratiomeasure.__init__(), and ifc4.ifctextdecoration.__init__().
The documentation for this class was generated from the following file:
ifc2x3.py