FreeCAD: Materials::MaterialEntry Class Reference
Materials::MaterialEntry Class Reference abstract
#include <MaterialLoader.h>
Public Member Functions
MaterialEntry ()=default
MaterialEntry (const std::shared_ptr< MaterialLibrary > &library, const QString &modelName, const QString &dir, const QString &modelUuid)
virtual ~MaterialEntry ()=default
virtual void addToTree (std::shared_ptr< std::map< QString, std::shared_ptr< Material >>> materialMap)=0
std::shared_ptr< MaterialLibrary > getLibrary () const
QString getName () const
QString getDirectory () const
QString getUUID () const
Protected Attributes
std::shared_ptr< MaterialLibrary > _library
QString _name
QString _directory
QString _uuid
Detailed Description
Definition at line 56 of file MaterialLoader.h.
Constructor & Destructor Documentation
MaterialEntry() [1/2]
Materials::MaterialEntry::MaterialEntry () default
MaterialEntry() [2/2]
MaterialEntry::MaterialEntry (const std::shared_ptr< MaterialLibrary > & library, const QString & modelName, const QString & dir, const QString & modelUuid)
Definition at line 48 of file MaterialLoader.cpp.
~MaterialEntry()
virtual Materials::MaterialEntry::~MaterialEntry () virtual default
Member Function Documentation
addToTree()
virtual void Materials::MaterialEntry::addToTree (std::shared_ptr< std::map< QString, std::shared_ptr< Material >>> materialMap) pure virtual
Implemented in Materials::MaterialYamlEntry.
getDirectory()
QString Materials::MaterialEntry::getDirectory () const inline
Definition at line 96 of file MaterialLoader.h.
Referenced by Materials::MaterialYamlEntry::addToTree().
getLibrary()
std::shared_ptr<MaterialLibrary> Materials::MaterialEntry::getLibrary () const inline
Definition at line 88 of file MaterialLoader.h.
Referenced by Materials::MaterialYamlEntry::addToTree().
getName()
QString Materials::MaterialEntry::getName () const inline
Definition at line 92 of file MaterialLoader.h.
Referenced by Materials::MaterialYamlEntry::addToTree().
getUUID()
QString Materials::MaterialEntry::getUUID () const inline
Definition at line 100 of file MaterialLoader.h.
Referenced by Materials::MaterialYamlEntry::addToTree().
Member Data Documentation
_directory
QString Materials::MaterialEntry::_directory protected
Definition at line 108 of file MaterialLoader.h.
_library
std::shared_ptr<MaterialLibrary> Materials::MaterialEntry::_library protected
Definition at line 106 of file MaterialLoader.h.
_name
QString Materials::MaterialEntry::_name protected
Definition at line 107 of file MaterialLoader.h.
_uuid
QString Materials::MaterialEntry::_uuid protected
Definition at line 109 of file MaterialLoader.h.
The documentation for this class was generated from the following files:
MaterialLoader.h
MaterialLoader.cpp