FreeCAD: App::ColorField Class Reference
App::ColorField Class Reference
#include <ColorModel.h>
Public Member Functions
ColorField ()
ColorField (const ColorField &rclCF)=default
ColorField (const ColorModel &rclModel, float fMin, float fMax, std::size_t usCt)
virtual ~ColorField ()=default
ColorField & operator= (const ColorField &rclCF)
std::size_t getCountColors () const
void set (const ColorModel &rclModel, float fMin, float fMax, std::size_t usCt)
void setCountColors (std::size_t usCt)
void setRange (float fMin, float fMax)
void getRange (float &rfMin, float &rfMax)
std::size_t getMinColors () const
void setColorModel (const ColorModel &rclModel)
const ColorModel & getColorModel () const
void setDirect (std::size_t usInd, Color clCol)
float getMinValue () const
float getMaxValue () const
Color getColor (std::size_t usIndex) const
Color getColor (float fVal) const
std::size_t getColorIndex (float fVal) const
Protected Member Functions
void rebuild ()
void interpolate (Color clCol1, std::size_t usPos1, Color clCol2, std::size_t usPos2)
Protected Attributes
ColorModel colorModel
float fMin
float fMax
float fAscent
float fConstant
std::size_t ctColors
std::vector< Color > colorField
Detailed Description
Definition at line 286 of file ColorModel.h.
Constructor & Destructor Documentation
ColorField() [1/3]
ColorField::ColorField ()
Definition at line 82 of file ColorModel.cpp.
References SCL.SimpleDataTypes::f, and set().
ColorField() [2/3]
App::ColorField::ColorField (const ColorField & rclCF) default
ColorField() [3/3]
ColorField::ColorField (const ColorModel & rclModel, float fMin, float fMax, std::size_t usCt)
Definition at line 87 of file ColorModel.cpp.
References fMax, fMin, and set().
~ColorField()
virtual App::ColorField::~ColorField () virtual default
Member Function Documentation
getColor() [1/2]
Color App::ColorField::getColor (float fVal) const inline
Definition at line 354 of file ColorModel.h.
References App::Color::b, src.Mod.PartDesign.Scripts.Gear::c1, colorModel, App::ColorModel::colors, SCL.SimpleDataTypes::f, fMax, fMin, App::Color::g, App::ColorModel::getCountColors(), SplineSurface::i, App::Color::r, toolbit-attributes::s, and InitGui::t.
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::setValues().
getColor() [2/2]
Color App::ColorField::getColor (std::size_t usIndex) const inline
Definition at line 336 of file ColorModel.h.
Referenced by draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::setValues().
getColorIndex()
std::size_t App::ColorField::getColorIndex (float fVal) const inline
Definition at line 385 of file ColorModel.h.
References ctColors, fAscent, and fConstant.
Referenced by App::ColorGradient::getColorIndex().
getColorModel()
const ColorModel& App::ColorField::getColorModel () const inline
Definition at line 319 of file ColorModel.h.
getCountColors()
std::size_t App::ColorField::getCountColors () const inline
Definition at line 296 of file ColorModel.h.
Referenced by App::ColorGradient::getColorIndex().
getMaxValue()
float App::ColorField::getMaxValue () const inline
Definition at line 331 of file ColorModel.h.
getMinColors()
std::size_t App::ColorField::getMinColors () const inline
Definition at line 314 of file ColorModel.h.
Referenced by App::ColorGradient::getMinColors().
getMinValue()
float App::ColorField::getMinValue () const inline
Definition at line 327 of file ColorModel.h.
getRange()
void App::ColorField::getRange (float & rfMin, float & rfMax) inline
Definition at line 309 of file ColorModel.h.
interpolate()
void ColorField::interpolate (Color clCol1, std::size_t usPos1, Color clCol2, std::size_t usPos2) protected
Definition at line 142 of file ColorModel.cpp.
References App::Color::b, colorField, App::Color::g, SplineSurface::i, and App::Color::r.
Referenced by rebuild().
operator=()
ColorField & ColorField::operator= (const ColorField & rclCF)
Definition at line 92 of file ColorModel.cpp.
References colorField.
rebuild()
void ColorField::rebuild () protected
Definition at line 118 of file ColorModel.cpp.
References colorField, colorModel, App::ColorModel::colors, ctColors, fAscent, fConstant, fMax, fMin, App::ColorModel::getCountColors(), SplineSurface::i, and interpolate().
Referenced by set(), and setColorModel().
set()
void ColorField::set (const ColorModel & rclModel, float fMin, float fMax, std::size_t usCt)
Definition at line 98 of file ColorModel.cpp.
References colorModel, ctColors, fMax, fMin, App::ColorModel::getCountColors(), and rebuild().
Referenced by ColorField(), draftguitools.gui_trackers.editTracker::move(), and App::ColorGradient::rebuild().
setColorModel()
void ColorField::setColorModel (const ColorModel & rclModel)
Definition at line 112 of file ColorModel.cpp.
References colorModel, and rebuild().
Referenced by App::ColorGradient::setColorModel().
setCountColors()
void App::ColorField::setCountColors (std::size_t usCt) inline
Definition at line 301 of file ColorModel.h.
setDirect()
void App::ColorField::setDirect (std::size_t usInd, Color clCol) inline
Definition at line 323 of file ColorModel.h.
setRange()
void App::ColorField::setRange (float fMin, float fMax) inline
Definition at line 305 of file ColorModel.h.
Member Data Documentation
colorField
std::vector<Color> App::ColorField::colorField protected
Definition at line 348 of file ColorModel.h.
Referenced by interpolate(), operator=(), and rebuild().
colorModel
ColorModel App::ColorField::colorModel protected
Definition at line 344 of file ColorModel.h.
Referenced by getColor(), rebuild(), set(), and setColorModel().
ctColors
std::size_t App::ColorField::ctColors protected
Definition at line 347 of file ColorModel.h.
Referenced by getColorIndex(), rebuild(), and set().
fAscent
float App::ColorField::fAscent protected
Definition at line 346 of file ColorModel.h.
Referenced by getColorIndex(), and rebuild().
fConstant
float App::ColorField::fConstant protected
Definition at line 346 of file ColorModel.h.
Referenced by getColorIndex(), and rebuild().
fMax
float App::ColorField::fMax protected
Definition at line 345 of file ColorModel.h.
Referenced by ColorField(), getColor(), rebuild(), and set().
fMin
float App::ColorField::fMin protected
Definition at line 345 of file ColorModel.h.
Referenced by ColorField(), getColor(), rebuild(), and set().
The documentation for this class was generated from the following files:
ColorModel.h
ColorModel.cpp