FreeCAD: Reen::BSplineParameterCorrection Class Reference
Reen::BSplineParameterCorrection Class Reference
#include <ApproxSurface.h>
Public Member Functions
BSplineParameterCorrection (unsigned usUOrder=4, unsigned usVOrder=4, unsigned usUCtrlpoints=6, unsigned usVCtrlpoints=6)
~BSplineParameterCorrection () override=default
void SetUKnots (const std::vector< double > &afKnots)
void SetVKnots (const std::vector< double > &afKnots)
virtual const math_Matrix & GetFirstSmoothMatrix () const
virtual const math_Matrix & GetSecondSmoothMatrix () const
virtual const math_Matrix & GetThirdSmoothMatrix () const
virtual void SetFirstSmoothMatrix (const math_Matrix &rclMat)
virtual void SetSecondSmoothMatrix (const math_Matrix &rclMat)
virtual void SetThirdSmoothMatrix (const math_Matrix &rclMat)
void EnableSmoothing (bool bSmooth=true, double fSmoothInfl=1.0f) override
virtual void EnableSmoothing (bool bSmooth, double fSmoothInfl, double fFirst, double fSec, double fThird)
Public Member Functions inherited from Reen::ParameterCorrection
ParameterCorrection (unsigned usUOrder=4, unsigned usVOrder=4, unsigned usUCtrlpoints=6, unsigned usVCtrlpoints=6)
virtual ~ParameterCorrection ()
virtual Handle (Geom_BSplineSurface) CreateSurface(const TColgp_Array1OfPnt &points
virtual void SetUV (const Base::Vector3d &clU, const Base::Vector3d &clV, bool bUseDir=true)
virtual void GetUVW (Base::Vector3d &clU, Base::Vector3d &clV, Base::Vector3d &clW) const
virtual Base::Vector3d GetGravityPoint () const
Protected Member Functions
virtual void Init ()
void DoParameterCorrection (int iIter) override
bool SolveWithoutSmoothing () override
bool SolveWithSmoothing (double fWeight) override
virtual void CalcSmoothingTerms (bool bRecalc, double fFirst, double fSecond, double fThird)
virtual void CalcFirstSmoothMatrix (Base::SequencerLauncher &)
virtual void CalcSecondSmoothMatrix (Base::SequencerLauncher &)
virtual void CalcThirdSmoothMatrix (Base::SequencerLauncher &)
Protected Member Functions inherited from Reen::ParameterCorrection
virtual void CalcEigenvectors ()
void ProjectControlPointsOnPlane ()
virtual bool DoInitialParameterCorrection (double fSizeFactor=0.0f)
virtual bool GetUVParameters (double fSizeFactor)
Protected Attributes
BSplineBasis _clUSpline
BSplineBasis _clVSpline
B-spline basic function in the u-direction.
math_Matrix _clSmoothMatrix
B-spline basic function in the v-direction.
math_Matrix _clFirstMatrix
Matrix of smoothing functionals.
math_Matrix _clSecondMatrix
Matrix of the 1st smoothing functionals.
math_Matrix _clThirdMatrix
Matrix of the 2nd smoothing functionals.
Protected Attributes inherited from Reen::ParameterCorrection
bool _bGetUVDir
bool _bSmoothing
Determines whether u/v direction is given.
double _fSmoothInfluence
Use smoothing.
unsigned _usUOrder
Influence of smoothing.
unsigned _usVOrder
Order in u-direction.
unsigned _usUCtrlpoints
Order in v-direction.
unsigned _usVCtrlpoints
Number of control points in the u-direction.
Base::Vector3d _clU
Number of control points in the v-direction.
Base::Vector3d _clV
u-direction
Base::Vector3d _clW
v-direction
TColgp_Array1OfPnt * _pvcPoints {nullptr}
w-direction (perpendicular to u & v directions)
TColgp_Array1OfPnt2d * _pvcUVParam {nullptr}
Raw data point list.
TColgp_Array2OfPnt _vCtrlPntsOfSurf
Parameter value for the points in the list.
TColStd_Array1OfReal _vUKnots
Array of control points.
TColStd_Array1OfReal _vVKnots
Knot vector of the B-spline surface in the u-direction.
TColStd_Array1OfInteger _vUMults
Knot vector of the B-spline surface in the v-direction.
TColStd_Array1OfInteger _vVMults
Multiplicity of the knots in the knot vector.
Additional Inherited Members
Public Attributes inherited from Reen::ParameterCorrection
virtual int iIter
virtual int bool bParaCor
virtual int bool double fSizeFactor = 0.0f)
Detailed Description
This class calculates a B-spline area on any point cloud (AKA scattered data). The surface is generated iteratively with the help of a parameter correction. See Hoschek/Lasser 2nd ed. (1992). The approximation is expanded to include smoothing terms so that smooth surfaces can be generated.
Definition at line 383 of file ApproxSurface.h.
Constructor & Destructor Documentation
BSplineParameterCorrection()
BSplineParameterCorrection::BSplineParameterCorrection (unsigned usUOrder = 4, unsigned usVOrder = 4, unsigned usUCtrlpoints = 6, unsigned usVCtrlpoints = 6) explicit
Definition at line 866 of file ApproxSurface.cpp.
References Init().
~BSplineParameterCorrection()
Reen::BSplineParameterCorrection::~BSplineParameterCorrection () override default
Member Function Documentation
CalcFirstSmoothMatrix()
void BSplineParameterCorrection::CalcFirstSmoothMatrix (Base::SequencerLauncher & seq) protected virtual
Calculates the matrix for the first smoothing term (see U.Dietz dissertation)
Definition at line 1286 of file ApproxSurface.cpp.
References _clFirstMatrix, _clUSpline, _clVSpline, Reen::ParameterCorrection::_usUCtrlpoints, Reen::ParameterCorrection::_usVCtrlpoints, Reen::BSplineBasis::GetIntegralOfProductOfBSplines(), SplineSurface::i, RobotExample::l, test::m, and Base::SequencerLauncher::next().
Referenced by CalcSmoothingTerms().
CalcSecondSmoothMatrix()
void BSplineParameterCorrection::CalcSecondSmoothMatrix (Base::SequencerLauncher & seq) protected virtual
Calculates the matrix for the second smoothing term (see U.Dietz dissertation)
Definition at line 1308 of file ApproxSurface.cpp.
References _clSecondMatrix, _clUSpline, _clVSpline, Reen::ParameterCorrection::_usUCtrlpoints, Reen::ParameterCorrection::_usVCtrlpoints, Reen::BSplineBasis::GetIntegralOfProductOfBSplines(), SplineSurface::i, RobotExample::l, test::m, and Base::SequencerLauncher::next().
Referenced by CalcSmoothingTerms().
CalcSmoothingTerms()
void BSplineParameterCorrection::CalcSmoothingTerms (bool bRecalc, double fFirst, double fSecond, double fThird) protected virtual
Calculates the matrix for the smoothing terms (see U.Dietz dissertation)
Definition at line 1269 of file ApproxSurface.cpp.
References _clFirstMatrix, _clSecondMatrix, _clSmoothMatrix, _clThirdMatrix, Reen::ParameterCorrection::_usUCtrlpoints, Reen::ParameterCorrection::_usVCtrlpoints, CalcFirstSmoothMatrix(), CalcSecondSmoothMatrix(), and CalcThirdSmoothMatrix().
Referenced by EnableSmoothing().
CalcThirdSmoothMatrix()
void BSplineParameterCorrection::CalcThirdSmoothMatrix (Base::SequencerLauncher & seq) protected virtual
Calculates the matrix for the third smoothing term
Definition at line 1332 of file ApproxSurface.cpp.
References _clThirdMatrix, _clUSpline, _clVSpline, Reen::ParameterCorrection::_usUCtrlpoints, Reen::ParameterCorrection::_usVCtrlpoints, Reen::BSplineBasis::GetIntegralOfProductOfBSplines(), SplineSurface::i, RobotExample::l, test::m, and Base::SequencerLauncher::next().
Referenced by CalcSmoothingTerms().
DoParameterCorrection()
void BSplineParameterCorrection::DoParameterCorrection (int iIter) override protected virtual
Carries out a parameter correction.
Implements Reen::ParameterCorrection.
Definition at line 961 of file ApproxSurface.cpp.
References Reen::ParameterCorrection::_bSmoothing, Reen::ParameterCorrection::_fSmoothInfluence, Reen::ParameterCorrection::_pvcPoints, Reen::ParameterCorrection::_usUOrder, Reen::ParameterCorrection::_usVOrder, Reen::ParameterCorrection::_vCtrlPntsOfSurf, Reen::ParameterCorrection::_vUKnots, Reen::ParameterCorrection::_vUMults, Reen::ParameterCorrection::_vVKnots, Reen::ParameterCorrection::_vVMults, Reen::ParameterCorrection::Handle(), SplineSurface::i, Reen::ParameterCorrection::iIter, Base::SequencerLauncher::next(), SolveWithoutSmoothing(), SolveWithSmoothing(), and DrawingExample::X.
EnableSmoothing() [1/2]
void BSplineParameterCorrection::EnableSmoothing (bool bSmooth, double fSmoothInfl, double fFirst, double fSec, double fThird) virtual
Use smoothing-terms
Definition at line 1371 of file ApproxSurface.cpp.
References Reen::ParameterCorrection::_bSmoothing, CalcSmoothingTerms(), and Reen::ParameterCorrection::EnableSmoothing().
EnableSmoothing() [2/2]
void BSplineParameterCorrection::EnableSmoothing (bool bSmooth = true, double fSmoothInfl = 1.0f) override virtual
Use smoothing-terms
Reimplemented from Reen::ParameterCorrection.
Definition at line 1366 of file ApproxSurface.cpp.
GetFirstSmoothMatrix()
const math_Matrix & BSplineParameterCorrection::GetFirstSmoothMatrix () const virtual
Returns the first matrix of smoothing terms, if calculated
Definition at line 1387 of file ApproxSurface.cpp.
References _clFirstMatrix.
GetSecondSmoothMatrix()
const math_Matrix & BSplineParameterCorrection::GetSecondSmoothMatrix () const virtual
Returns the second matrix of smoothing terms, if calculated
Definition at line 1392 of file ApproxSurface.cpp.
References _clSecondMatrix.
GetThirdSmoothMatrix()
const math_Matrix & BSplineParameterCorrection::GetThirdSmoothMatrix () const virtual
Returns the third matrix of smoothing terms, if calculated
Definition at line 1397 of file ApproxSurface.cpp.
References _clThirdMatrix.
Init()
void BSplineParameterCorrection::Init () protected virtual
Initialization
Definition at line 881 of file ApproxSurface.cpp.
References _clFirstMatrix, _clSecondMatrix, _clSmoothMatrix, _clThirdMatrix, _clUSpline, _clVSpline, Reen::ParameterCorrection::_pvcPoints, Reen::ParameterCorrection::_pvcUVParam, Reen::ParameterCorrection::_usUCtrlpoints, Reen::ParameterCorrection::_usUOrder, Reen::ParameterCorrection::_usVCtrlpoints, Reen::ParameterCorrection::_usVOrder, Reen::ParameterCorrection::_vUKnots, Reen::ParameterCorrection::_vUMults, Reen::ParameterCorrection::_vVKnots, Reen::ParameterCorrection::_vVMults, SplineSurface::i, and Reen::SplineBasisfunction::SetKnots().
Referenced by BSplineParameterCorrection().
SetFirstSmoothMatrix()
void BSplineParameterCorrection::SetFirstSmoothMatrix (const math_Matrix & rclMat) virtual
Sets the first matrix of the smoothing terms
Definition at line 1402 of file ApproxSurface.cpp.
References _clFirstMatrix.
SetSecondSmoothMatrix()
void BSplineParameterCorrection::SetSecondSmoothMatrix (const math_Matrix & rclMat) virtual
Sets the second matrix of smoothing terms
Definition at line 1407 of file ApproxSurface.cpp.
References _clSecondMatrix.
SetThirdSmoothMatrix()
void BSplineParameterCorrection::SetThirdSmoothMatrix (const math_Matrix & rclMat) virtual
Sets the third matrix of smoothing terms
Definition at line 1412 of file ApproxSurface.cpp.
References _clThirdMatrix.
SetUKnots()
void BSplineParameterCorrection::SetUKnots (const std::vector< double > & afKnots)
Setting the knot vector
Definition at line 919 of file ApproxSurface.cpp.
References _clUSpline, Reen::ParameterCorrection::_usUCtrlpoints, Reen::ParameterCorrection::_usUOrder, Reen::ParameterCorrection::_vUKnots, Reen::ParameterCorrection::_vUMults, SplineSurface::i, and Reen::SplineBasisfunction::SetKnots().
SetVKnots()
void BSplineParameterCorrection::SetVKnots (const std::vector< double > & afKnots)
Setting the knot vector
Definition at line 940 of file ApproxSurface.cpp.
References _clVSpline, Reen::ParameterCorrection::_usVCtrlpoints, Reen::ParameterCorrection::_usVOrder, Reen::ParameterCorrection::_vVKnots, Reen::ParameterCorrection::_vVMults, SplineSurface::i, and Reen::SplineBasisfunction::SetKnots().
SolveWithoutSmoothing()
bool BSplineParameterCorrection::SolveWithoutSmoothing () override protected virtual
Solve an overdetermined LGS with the help of the Householder-Tansformation
Implements Reen::ParameterCorrection.
Definition at line 1038 of file ApproxSurface.cpp.
References _clUSpline, _clVSpline, Reen::ParameterCorrection::_pvcPoints, Reen::ParameterCorrection::_usUCtrlpoints, Reen::ParameterCorrection::_usVCtrlpoints, Reen::ParameterCorrection::_vCtrlPntsOfSurf, Reen::BSplineBasis::BasisFunction(), and SplineSurface::i.
Referenced by DoParameterCorrection().
SolveWithSmoothing()
bool BSplineParameterCorrection::SolveWithSmoothing (double fWeight) override protected virtual
Solve a regular system of equations by LU decomposition. Depending on the weighting, smoothing terms are included
Implements Reen::ParameterCorrection.
Definition at line 1139 of file ApproxSurface.cpp.
References _clSmoothMatrix, _clUSpline, _clVSpline, Reen::ParameterCorrection::_pvcPoints, Reen::ParameterCorrection::_usUCtrlpoints, Reen::ParameterCorrection::_usVCtrlpoints, Reen::ParameterCorrection::_vCtrlPntsOfSurf, Reen::BSplineBasis::BasisFunction(), draftgeoutils.faces::bind(), Path.Base.Generator.dogboneII::generate(), SplineSurface::i, test::m, and Reen::ScalarProduct::multiply().
Referenced by DoParameterCorrection().
Member Data Documentation
_clFirstMatrix
math_Matrix Reen::BSplineParameterCorrection::_clFirstMatrix protected
Matrix of smoothing functionals.
Definition at line 497 of file ApproxSurface.h.
Referenced by CalcFirstSmoothMatrix(), CalcSmoothingTerms(), GetFirstSmoothMatrix(), Init(), and SetFirstSmoothMatrix().
_clSecondMatrix
math_Matrix Reen::BSplineParameterCorrection::_clSecondMatrix protected
Matrix of the 1st smoothing functionals.
Definition at line 498 of file ApproxSurface.h.
Referenced by CalcSecondSmoothMatrix(), CalcSmoothingTerms(), GetSecondSmoothMatrix(), Init(), and SetSecondSmoothMatrix().
_clSmoothMatrix
math_Matrix Reen::BSplineParameterCorrection::_clSmoothMatrix protected
B-spline basic function in the v-direction.
Definition at line 496 of file ApproxSurface.h.
Referenced by CalcSmoothingTerms(), Init(), and SolveWithSmoothing().
_clThirdMatrix
math_Matrix Reen::BSplineParameterCorrection::_clThirdMatrix protected
Matrix of the 2nd smoothing functionals.
Definition at line 499 of file ApproxSurface.h.
Referenced by CalcSmoothingTerms(), CalcThirdSmoothMatrix(), GetThirdSmoothMatrix(), Init(), and SetThirdSmoothMatrix().
_clUSpline
BSplineBasis Reen::BSplineParameterCorrection::_clUSpline protected
Definition at line 494 of file ApproxSurface.h.
Referenced by CalcFirstSmoothMatrix(), CalcSecondSmoothMatrix(), CalcThirdSmoothMatrix(), Init(), SetUKnots(), SolveWithoutSmoothing(), and SolveWithSmoothing().
_clVSpline
BSplineBasis Reen::BSplineParameterCorrection::_clVSpline protected
B-spline basic function in the u-direction.
Definition at line 495 of file ApproxSurface.h.
Referenced by CalcFirstSmoothMatrix(), CalcSecondSmoothMatrix(), CalcThirdSmoothMatrix(), Init(), SetVKnots(), SolveWithoutSmoothing(), and SolveWithSmoothing().
The documentation for this class was generated from the following files:
ApproxSurface.h
ApproxSurface.cpp