FreeCAD: Gui::View3DInventorViewer Class Reference
Gui::View3DInventorViewer Class Reference
#include <View3DInventorViewer.h>
Public Types
enum SelectionMode {
Lasso = 0, Rectangle = 1, Rubberband = 2, BoxZoom = 3,
Clip = 4
}
Pick modes for picking points in the scene.
Modus handling of the viewer
Here you can switch several features on/off and modes of the Viewer
enum ViewerMod {
ShowCoord =1, ShowFPS =2, SimpleBackground =4, DisallowRotation =8,
DisallowPanning =16, DisallowZooming =32
}
Render mode
enum RenderType { Native, Framebuffer, Image }
Public Types inherited from SIM::Coin3D::Quarter::QuarterWidget
enum TransparencyType {
SCREEN_DOOR = SoGLRenderAction::SCREEN_DOOR, ADD = SoGLRenderAction::ADD, DELAYED_ADD = SoGLRenderAction::DELAYED_ADD, SORTED_OBJECT_ADD = SoGLRenderAction::SORTED_OBJECT_ADD,
BLEND = SoGLRenderAction::BLEND, DELAYED_BLEND = SoGLRenderAction::DELAYED_BLEND, SORTED_OBJECT_BLEND = SoGLRenderAction::SORTED_OBJECT_BLEND, SORTED_OBJECT_SORTED_TRIANGLE_ADD = SoGLRenderAction::SORTED_OBJECT_SORTED_TRIANGLE_ADD,
SORTED_OBJECT_SORTED_TRIANGLE_BLEND = SoGLRenderAction::SORTED_OBJECT_SORTED_TRIANGLE_BLEND, NONE = SoGLRenderAction::NONE, SORTED_LAYERS_BLEND = SoGLRenderAction::SORTED_LAYERS_BLEND
}
enum RenderMode {
AS_IS = SoRenderManager::AS_IS, WIREFRAME = SoRenderManager::WIREFRAME, WIREFRAME_OVERLAY = SoRenderManager::WIREFRAME_OVERLAY, POINTS = SoRenderManager::POINTS,
HIDDEN_LINE = SoRenderManager::HIDDEN_LINE, BOUNDING_BOX = SoRenderManager::BOUNDING_BOX
}
enum StereoMode {
MONO = SoRenderManager::MONO, ANAGLYPH = SoRenderManager::ANAGLYPH, QUAD_BUFFER = SoRenderManager::QUAD_BUFFER, INTERLEAVED_ROWS = SoRenderManager::INTERLEAVED_ROWS,
INTERLEAVED_COLUMNS = SoRenderManager::INTERLEAVED_COLUMNS
}
Public Member Functions
Handling of view providers
bool hasViewProvider (ViewProvider *) const
Checks if the view provider is a top-level object of the scene.
bool containsViewProvider (const ViewProvider *) const
void addViewProvider (ViewProvider *)
adds an ViewProvider to the view, e.g. from a feature
void removeViewProvider (ViewProvider *)
remove a ViewProvider
ViewProvider * getViewProviderByPath (SoPath *) const
get view provider by path
ViewProvider * getViewProviderByPathFromTail (SoPath *) const
std::vector< ViewProvider * > getViewProvidersOfType (const Base::Type &typeId) const
get all view providers of given type
void setEditingViewProvider (Gui::ViewProvider *vp, int ModNum)
set the ViewProvider in special edit mode
bool isEditingViewProvider () const
return whether a view provider is edited
ViewProvider * getEditingViewProvider () const
return currently editing view provider
void resetEditingViewProvider ()
reset from edit mode
void setupEditingRoot (SoNode *node=nullptr, const Base::Matrix4D *mat=nullptr)
void resetEditingRoot (bool updateLinks=true)
void setEditingTransform (const Base::Matrix4D &mat)
SoPickedPoint * getPointOnRay (const SbVec2s &pos, const ViewProvider *vp) const
SoPickedPoint * getPointOnRay (const SbVec3f &pos, const SbVec3f &dir, const ViewProvider *vp) const
void setOverrideMode (const std::string &mode)
display override mode
void updateOverrideMode (const std::string &mode)
update override mode. doesn't affect providers
std::string getOverrideMode () const
Making pictures
void savePicture (int width, int height, int sample, const QColor &bg, QImage &img) const
void saveGraphic (int pagesize, const QColor &, SoVectorizeAction *va) const
bool dumpToFile (SoNode *node, const char *filename, bool binary) const
Selection methods
void startSelection (SelectionMode=Lasso)
void abortSelection ()
void stopSelection ()
bool isSelecting () const
std::vector< SbVec2f > getGLPolygon (SelectionRole *role=nullptr) const
std::vector< SbVec2f > getGLPolygon (const std::vector< SbVec2s > &) const
const std::vector< SbVec2s > & getPolygon (SelectionRole *role=nullptr) const
void setSelectionEnabled (bool enable)
bool isSelectionEnabled () const
SbVec2f screenCoordsOfPath (SoPath *path) const
Returns the screen coordinates of the origin of the path's tail object.
Edit methods
void setEditing (bool edit)
bool isEditing () const
void setEditingCursor (const QCursor &cursor)
void setComponentCursor (const QCursor &cursor)
void setRedirectToSceneGraph (bool redirect)
bool isRedirectedToSceneGraph () const
void setRedirectToSceneGraphEnabled (bool enable)
bool isRedirectToSceneGraphEnabled () const
Pick actions
bool pickPoint (const SbVec2s &pos, SbVec3f &point, SbVec3f &norm) const
SoPickedPoint * pickPoint (const SbVec2s &pos) const
const SoPickedPoint * getPickedPoint (SoEventCallback *n) const
bool pubSeekToPoint (const SbVec2s &pos)
void pubSeekToPoint (const SbVec3f &pos)
void addEventCallback (SoType eventtype, SoEventCallbackCB *cb, void *userdata=nullptr)
void removeEventCallback (SoType eventtype, SoEventCallbackCB *cb, void *userdata=nullptr)
Clipping plane, near and far plane
SbVec3f getViewDirection () const
void setViewDirection (SbVec3f)
SbVec3f getUpDirection () const
SbRotation getCameraOrientation () const
SbVec3f getPointOnFocalPlane (const SbVec2s &) const
SbVec3f getPointOnLine (const SbVec2s &, const SbVec3f &axisCenter, const SbVec3f &axis) const
SbVec3f getPointOnXYPlaneOfPlacement (const SbVec2s &, const Base::Placement &) const
Base::BoundBox2d getViewportOnXYPlaneOfPlacement (Base::Placement plc) const
SbVec2s getPointOnViewport (const SbVec3f &) const
QPoint toQPoint (const SbVec2s &) const
SbVec2s fromQPoint (const QPoint &) const
void getNearPlane (SbVec3f &rcPt, SbVec3f &rcNormal) const
void getFarPlane (SbVec3f &rcPt, SbVec3f &rcNormal) const
void toggleClippingPlane (int toggle=-1, bool beforeEditing=false, bool noManip=false, const Base::Placement &pla=Base::Placement())
bool hasClippingPlane () const
SbVec3f projectOnNearPlane (const SbVec2f &) const
SbVec3f projectOnFarPlane (const SbVec2f &) const
void projectPointToLine (const SbVec2s &, SbVec3f &pt1, SbVec3f &pt2) const
SbVec2f getNormalizedPosition (const SbVec2s &) const
Public Member Functions inherited from SIM::Coin3D::Quarter::SoQTQuarterAdaptor
SoQTQuarterAdaptor (QWidget *parent=nullptr, const QtGLWidget *sharewidget=nullptr, Qt::WindowFlags flags=Qt::WindowFlags())
SoQTQuarterAdaptor (const QtGLFormat &format, QWidget *parent=nullptr, const QtGLWidget *shareWidget=nullptr, Qt::WindowFlags flags=Qt::WindowFlags())
SoQTQuarterAdaptor (QtGLContext *context, QWidget *parent=nullptr, const QtGLWidget *sharewidget=nullptr, Qt::WindowFlags flags=Qt::WindowFlags())
~SoQTQuarterAdaptor () override
QWidget * getWidget ()
QWidget * getGLWidget ()
QWidget * getWidget () const
QWidget * getGLWidget () const
SoCamera * getCamera () const
const SbViewportRegion & getViewportRegion () const
bool isViewing () const
void interactiveCountInc ()
void interactiveCountDec ()
int getInteractiveCount () const
void addStartCallback (SoQTQuarterAdaptorCB *func, void *data=nullptr)
void addFinishCallback (SoQTQuarterAdaptorCB *func, void *data=nullptr)
void removeStartCallback (SoQTQuarterAdaptorCB *func, void *data=nullptr)
void removeFinishCallback (SoQTQuarterAdaptorCB *func, void *data=nullptr)
bool isSeekMode () const
bool seekToPoint (const SbVec2s &screenpos)
void seekToPoint (const SbVec3f &scenepos)
void setSeekTime (float seconds)
float getSeekTime () const
void setSeekDistance (float distance)
float getSeekDistance () const
void setSeekValueAsPercentage (bool on)
bool isSeekValuePercentage () const
virtual float getPickRadius () const
virtual void setPickRadius (float pickRadius)
virtual void saveHomePosition ()
virtual void resetToHomePosition ()
virtual bool hasHomePosition () const
void paintEvent (QPaintEvent *event) override
Public Member Functions inherited from SIM::Coin3D::Quarter::QuarterWidget
QuarterWidget (QWidget *parent=nullptr, const QtGLWidget *sharewidget=nullptr, Qt::WindowFlags f=Qt::WindowFlags())
QuarterWidget (QtGLContext *context, QWidget *parent=nullptr, const QtGLWidget *sharewidget=nullptr, Qt::WindowFlags f=Qt::WindowFlags())
QuarterWidget (const QtGLFormat &format, QWidget *parent=nullptr, const QtGLWidget *shareWidget=nullptr, Qt::WindowFlags f=Qt::WindowFlags())
~QuarterWidget () override
TransparencyType transparencyType () const
RenderMode renderMode () const
StereoMode stereoMode () const
void setBackgroundColor (const QColor &color)
QColor backgroundColor () const
qreal devicePixelRatio () const
void resetNavigationModeFile ()
void setNavigationModeFile (const QUrl &url=QUrl(QString::fromLatin1(DEFAULT_NAVIGATIONFILE)))
const QUrl & navigationModeFile () const
void setupDefaultCursors ()
void setContextMenuEnabled (bool yes)
bool contextMenuEnabled () const
QMenu * getContextMenu () const
bool headlightEnabled () const
void setHeadlightEnabled (bool onoff)
SoDirectionalLight * getHeadlight () const
bool clearZBuffer () const
void setClearZBuffer (bool onoff)
bool clearWindow () const
void setClearWindow (bool onoff)
bool interactionModeEnabled () const
void setInteractionModeEnabled (bool onoff)
bool interactionModeOn () const
void setInteractionModeOn (bool onoff)
void setStateCursor (const SbName &state, const QCursor &cursor)
QCursor stateCursor (const SbName &state)
uint32_t getCacheContextId () const
virtual SoNode * getSceneGraph () const
void setSoEventManager (SoEventManager *manager)
SoEventManager * getSoEventManager () const
void setSoRenderManager (SoRenderManager *manager)
SoRenderManager * getSoRenderManager () const
EventFilter * getEventFilter () const
void addStateMachine (SoScXMLStateMachine *statemachine)
void removeStateMachine (SoScXMLStateMachine *statemachine)
QSize minimumSizeHint () const override
QList< QAction * > transparencyTypeActions () const
QList< QAction * > stereoModeActions () const
QList< QAction * > renderModeActions () const
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Background
enum Background { NoGradient, LinearGradient, RadialGradient }
View3DInventorViewer (QWidget *parent, const QtGLWidget *sharewidget=nullptr)
View3DInventorViewer (const QtGLFormat &format, QWidget *parent, const QtGLWidget *sharewidget=nullptr)
~View3DInventorViewer () override
void init ()
void onSelectionChanged (const SelectionChanges &Reason) override
Observer message from the Selection.
SoDirectionalLight * getBacklight () const
void setBacklightEnabled (bool on)
bool isBacklightEnabled () const
void setSceneGraph (SoNode *root) override
bool searchNode (SoNode *) const
void setAnimationEnabled (bool enable)
Decide if it should be possible to start any animation.
void setSpinningAnimationEnabled (bool enable)
Decide if it should be possible to start a spin animation of the model in the viewer by releasing the mouse button while dragging.
bool isAnimationEnabled () const
bool isSpinningAnimationEnabled () const
bool isAnimating () const
bool isSpinning () const
void startAnimation (const SbRotation &orientation, const SbVec3f &rotationCenter, const SbVec3f &translation, int duration=-1, bool wait=false)
Change the camera pose with an animation.
void startSpinningAnimation (const SbVec3f &axis, float velocity)
Start an infinite spin animation.
void stopAnimating ()
void setPopupMenuEnabled (bool on)
bool isPopupMenuEnabled () const
void setFeedbackVisibility (bool enable)
bool isFeedbackVisible () const
void setFeedbackSize (int size)
int getFeedbackSize () const
void setRenderType (RenderType type)
RenderType getRenderType () const
void renderToFramebuffer (QtGLFramebufferObject *)
QImage grabFramebuffer ()
void imageFromFramebuffer (int width, int height, int samples, const QColor &bgcolor, QImage &img)
void setViewing (bool enable) override
virtual void setCursorEnabled (bool enable)
void addGraphicsItem (GLGraphicsItem *)
void removeGraphicsItem (GLGraphicsItem *)
std::list< GLGraphicsItem * > getGraphicsItems () const
std::list< GLGraphicsItem * > getGraphicsItemsOfType (const Base::Type &) const
void clearGraphicsItems ()
static int getNumSamples ()
Get the preferred samples from the user settings.
Dimension controls
the "turn*" functions are wired up to parameter groups through view3dinventor. don't call them directly. instead set the parameter groups.
See also
TaskDimension
class NavigationStyle
class GLPainter
class ViewerEventFilter
void turnAllDimensionsOn ()
void turnAllDimensionsOff ()
void turn3dDimensionsOn ()
void turn3dDimensionsOff ()
void turnDeltaDimensionsOn ()
void turnDeltaDimensionsOff ()
void eraseAllDimensions ()
void addDimension3d (SoNode *node)
void addDimensionDelta (SoNode *node)
void setCameraOrientation (const SbRotation &orientation, bool moveToCenter=false)
void setCameraType (SoType type) override
void moveCameraTo (const SbRotation &orientation, const SbVec3f &position, int duration=-1)
void boxZoom (const SbBox2s &)
void viewAll () override
void viewAll (float factor)
void viewVR ()
Breaks out a VR window for a Rift.
SbBox3f getBoundingBox () const
void viewSelection ()
void alignToSelection ()
void setGradientBackground (Background)
Background getGradientBackground () const
void setGradientBackgroundColor (const SbColor &fromColor, const SbColor &toColor)
void setGradientBackgroundColor (const SbColor &fromColor, const SbColor &toColor, const SbColor &midColor)
void setNavigationType (Base::Type)
void setAxisLetterColor (const SbColor &color)
void setAxisCross (bool on)
bool hasAxisCross ()
void showRotationCenter (bool show)
void changeRotationCenterPosition (const SbVec3f &newCenter)
void setEnabledFPSCounter (bool on)
void setEnabledNaviCube (bool on)
bool isEnabledNaviCube () const
void setNaviCubeCorner (int)
NaviCube * getNaviCube () const
void setEnabledVBO (bool on)
bool isEnabledVBO () const
void setRenderCache (int)
void getDimensions (float &fHeight, float &fWidth) const
float getMaxDimension () const
SbVec3f getCenterPointOnFocalPlane () const
NavigationStyle * navigationStyle () const
void setDocument (Gui::Document *pcDocument)
Gui::Document * getDocument ()
virtual PyObject * getPyObject ()
static GLenum getInternalTextureFormat ()
void renderScene ()
void renderFramebuffer ()
void renderGLImage ()
void animatedViewAll (int steps, int ms)
void actualRedraw () override
void setSeekMode (bool on) override
void afterRealizeHook () override
bool processSoEvent (const SoEvent *ev) override
void dropEvent (QDropEvent *ev) override
void dragEnterEvent (QDragEnterEvent *ev) override
void dragMoveEvent (QDragMoveEvent *ev) override
void dragLeaveEvent (QDragLeaveEvent *ev) override
bool processSoEventBase (const SoEvent *const ev)
void printDimension () const
void selectAll ()
Additional Inherited Members
Public Slots inherited from SIM::Coin3D::Quarter::QuarterWidget
virtual void seek ()
void redraw ()
void setRenderMode (SIM::Coin3D::Quarter::QuarterWidget::RenderMode mode)
void setStereoMode (SIM::Coin3D::Quarter::QuarterWidget::StereoMode mode)
void setTransparencyType (SIM::Coin3D::Quarter::QuarterWidget::TransparencyType type)
Signals inherited from SIM::Coin3D::Quarter::QuarterWidget
void devicePixelRatioChanged (qreal dev_pixel_ratio)
Protected Member Functions inherited from SIM::Coin3D::Quarter::QuarterWidget
void paintEvent (QPaintEvent *) override
void resizeEvent (QResizeEvent *) override
bool viewportEvent (QEvent *event) override
virtual bool updateDevicePixelRatio ()
Static Protected Member Functions inherited from SIM::Coin3D::Quarter::SoQTQuarterAdaptor
static void draw2DString (const char *str, SbVec2s glsize, SbVec2f position)
static void printString (const char *str)
Protected Attributes inherited from SIM::Coin3D::Quarter::SoQTQuarterAdaptor
SbVec2f framesPerSecond
Properties inherited from SIM::Coin3D::Quarter::QuarterWidget
QUrl navigationModeFile
QColor backgroundColor
bool contextMenuEnabled
bool headlightEnabled
bool clearZBuffer
bool clearWindow
bool interactionModeEnabled
bool interactionModeOn
TransparencyType transparencyType
RenderMode renderMode
StereoMode stereoMode
qreal devicePixelRatio
Detailed Description
GUI view into a 3D scene provided by View3DInventor
Definition at line 88 of file View3DInventorViewer.h.
Member Enumeration Documentation
Background
enum Gui::View3DInventorViewer::Background
Enumerator
NoGradient
LinearGradient
RadialGradient
Definition at line 130 of file View3DInventorViewer.h.
RenderType
enum Gui::View3DInventorViewer::RenderType
Enumerator
Native
Framebuffer
Image
Definition at line 120 of file View3DInventorViewer.h.
SelectionMode
enum Gui::View3DInventorViewer::SelectionMode
Pick modes for picking points in the scene.
Enumerator
Lasso
Select objects using a lasso.
Rectangle
Select objects using a rectangle.
Rubberband
Select objects using a rubberband.
BoxZoom
Perform a box zoom.
Clip
Clip objects using a lasso.
Definition at line 95 of file View3DInventorViewer.h.
ViewerMod
enum Gui::View3DInventorViewer::ViewerMod
Enumerator
ShowCoord
Enables the Coordinate system in the corner.
ShowFPS
Enables the Frames Per Second counter.
SimpleBackground
switch to a simple background.
DisallowRotation
switch off the rotation.
DisallowPanning
switch off the panning.
DisallowZooming
switch off the zooming.
Definition at line 107 of file View3DInventorViewer.h.
Constructor & Destructor Documentation
View3DInventorViewer() [1/2]
View3DInventorViewer::View3DInventorViewer (QWidget * parent, const QtGLWidget * sharewidget = nullptr) explicit
Definition at line 364 of file View3DInventorViewer.cpp.
References init(), and Gui::NoResolve.
View3DInventorViewer() [2/2]
View3DInventorViewer::View3DInventorViewer (const QtGLFormat & format, QWidget * parent, const QtGLWidget * sharewidget = nullptr)
Definition at line 384 of file View3DInventorViewer.cpp.
References init(), and Gui::NoResolve.
~View3DInventorViewer()
View3DInventorViewer::~View3DInventorViewer () override
Definition at line 591 of file View3DInventorViewer.cpp.
References Gui::coinRemoveAllChildren(), Gui::SelectionObserver::detachSelection(), Gui::getMainWindow(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), resetEditingRoot(), Gui::MainWindow::setPaneText(), and setSceneGraph().
Member Function Documentation
abortSelection()
void View3DInventorViewer::abortSelection ()
Definition at line 1769 of file View3DInventorViewer.cpp.
References Gui::NavigationStyle::abortSelection(), and setCursorEnabled().
actualRedraw()
void View3DInventorViewer::actualRedraw () override protected virtual
Overridden from QGLWidget to render the scenegraph
Reimplemented from SIM::Coin3D::Quarter::QuarterWidget.
Definition at line 2252 of file View3DInventorViewer.cpp.
References Framebuffer, Image, Native, renderFramebuffer(), renderGLImage(), and renderScene().
addDimension3d()
void View3DInventorViewer::addDimension3d (SoNode * node)
Definition at line 4145 of file View3DInventorViewer.cpp.
addDimensionDelta()
void View3DInventorViewer::addDimensionDelta (SoNode * node)
Definition at line 4150 of file View3DInventorViewer.cpp.
addEventCallback()
void View3DInventorViewer::addEventCallback (SoType eventtype, SoEventCallbackCB * cb, void * userdata = nullptr)
Set up a callback function cb which will be invoked for the given eventtype. userdata will be given as the first argument to the callback function.
Definition at line 4082 of file View3DInventorViewer.cpp.
Referenced by Gui::View3DInventorPy::addEventCallback(), Gui::View3DInventorPy::addEventCallbackPivy(), MeshPartGui::CurveOnMeshHandler::enableCallback(), and setEditingViewProvider().
addGraphicsItem()
void View3DInventorViewer::addGraphicsItem (GLGraphicsItem * item)
Definition at line 1962 of file View3DInventorViewer.cpp.
Referenced by InspectionGui::ViewProviderProxyObject::addFlag(), Gui::PolyPickerSelection::initialize(), and Gui::RubberbandSelection::initialize().
addViewProvider()
void View3DInventorViewer::addViewProvider (ViewProvider * pcProvider)
adds an ViewProvider to the view, e.g. from a feature
Definition at line 823 of file View3DInventorViewer.cpp.
References Gui::ViewProvider::canAddToSceneGraph(), Gui::ViewProvider::getBackRoot(), Gui::ViewProvider::getFrontRoot(), getOverrideMode(), Gui::ViewProvider::getRoot(), Gui::ViewProvider::isPartOfPhysicalObject(), and Gui::ViewProvider::setOverrideMode().
Referenced by MeshPartGui::CurveOnMeshHandler::enableCallback(), FemGui::PointMarker::PointMarker(), Gui::Document::setAnnotationViewProvider(), and Gui::Document::slotNewObject().
afterRealizeHook()
void View3DInventorViewer::afterRealizeHook () override protected virtual
Reimplemented from SIM::Coin3D::Quarter::SoQTQuarterAdaptor.
Definition at line 3650 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::afterRealizeHook(), and Gui::NavigationStyle::getViewingMode().
alignToSelection()
void View3DInventorViewer::alignToSelection ()
Definition at line 3431 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getCamera(), App::GeoFeature::getCameraAlignmentDirection(), App::GeoFeature::getGlobalPlacement(), Base::Placement::getRotation(), Gui::SelectionSingleton::getSelection(), App::PropertyPlacement::getValue(), Base::Rotation::inverse(), Gui::NoResolve, geoff_geometry::Normal(), App::ElementNamePair::oldName, App::GeoFeature::Placement, App::GeoFeature::resolveElement(), Path.Dressup.Utils::selection(), Gui::Selection(), setCameraOrientation(), and Base::Tools::splitSubName().
Referenced by Gui::View3DInventor::onMsg().
animatedViewAll()
void View3DInventorViewer::animatedViewAll (int steps, int ms) protected
Definition at line 3160 of file View3DInventorViewer.cpp.
References MengerSponge::box, draftgeoutils.intersections::connect(), KDL::diff(), getBoundingBox(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), SplineSurface::i, RobotExample::pos, KDL::tan(), and PersistentToolbarsGui::timer.
Referenced by viewAll().
boxZoom()
void View3DInventorViewer::boxZoom (const SbBox2s & box)
Zooms the viewport to the size of the bounding box.
Definition at line 3251 of file View3DInventorViewer.cpp.
References MengerSponge::box, and Gui::NavigationStyle::boxZoom().
Referenced by Gui::View3DInventorPy::boxZoom(), and Gui::BoxZoomSelection::terminate().
changeRotationCenterPosition()
void View3DInventorViewer::changeRotationCenterPosition (const SbVec3f & newCenter)
Definition at line 1475 of file View3DInventorViewer.cpp.
Referenced by Gui::NavigationStyle::doZoom(), and Gui::NavigationStyle::setViewingMode().
clearGraphicsItems()
void View3DInventorViewer::clearGraphicsItems ()
Definition at line 1989 of file View3DInventorViewer.cpp.
containsViewProvider()
bool View3DInventorViewer::containsViewProvider (const ViewProvider * vp) const
Checks if the view provider is part of the scene. In contrast to hasViewProvider() this method also checks if the view provider is a child of another view provider
Definition at line 813 of file View3DInventorViewer.cpp.
References Gui::ViewProvider::getRoot(), SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph(), and SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager().
Referenced by Gui::View3DInventor::containsViewProvider().
dragEnterEvent()
void View3DInventorViewer::dragEnterEvent (QDragEnterEvent * ev) override protected
Definition at line 4189 of file View3DInventorViewer.cpp.
dragLeaveEvent()
void View3DInventorViewer::dragLeaveEvent (QDragLeaveEvent * ev) override protected
Definition at line 4212 of file View3DInventorViewer.cpp.
dragMoveEvent()
void View3DInventorViewer::dragMoveEvent (QDragMoveEvent * ev) override protected
Definition at line 4201 of file View3DInventorViewer.cpp.
dropEvent()
void View3DInventorViewer::dropEvent (QDropEvent * ev) override protected
Drops the event e and loads the files into the given document.
Definition at line 4178 of file View3DInventorViewer.cpp.
References Gui::Document::getDocument(), Gui::getMainWindow(), and Gui::MainWindow::loadUrls().
dumpToFile()
bool View3DInventorViewer::dumpToFile (SoNode * node, const char * filename, bool binary) const
Writes the current scenegraph to an Inventor file, either in ascii or binary.
Definition at line 1891 of file View3DInventorViewer.cpp.
References Base::FileInfo::hasExtension(), saveGraphic(), and Gui::SoFCDB::writeToFile().
Referenced by Gui::View3DInventor::dump().
eraseAllDimensions()
void View3DInventorViewer::eraseAllDimensions ()
Definition at line 4129 of file View3DInventorViewer.cpp.
References Gui::coinRemoveAllChildren().
fromQPoint()
SbVec2s View3DInventorViewer::fromQPoint (const QPoint & pnt) const
Converts Qt coordinates into Inventor coordinates. The conversion takes the device pixel ratio into account.
Definition at line 2905 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::devicePixelRatio, and SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager().
getBacklight()
SoDirectionalLight * View3DInventorViewer::getBacklight () const
Definition at line 1518 of file View3DInventorViewer.cpp.
getBoundingBox()
SbBox3f View3DInventorViewer::getBoundingBox () const
Returns the bounding box of the scene graph.
Definition at line 3256 of file View3DInventorViewer.cpp.
References Path.Post.scripts.dynapath_4060_post::action, SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph(), and SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager().
Referenced by animatedViewAll(), toggleClippingPlane(), and viewAll().
getCameraOrientation()
SbRotation View3DInventorViewer::getCameraOrientation () const
Returns the orientation of the camera.
Definition at line 2631 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager().
Referenced by Gui::View3DInventorPy::getCameraOrientation().
getCenterPointOnFocalPlane()
SbVec3f View3DInventorViewer::getCenterPointOnFocalPlane () const
Definition at line 2466 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager().
getDimensions()
void View3DInventorViewer::getDimensions (float & fHeight, float & fWidth) const
Definition at line 2484 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getViewportRegion(), KDL::tan(), and Path.Post.scripts.grbl_post::type.
Referenced by getMaxDimension(), and printDimension().
getDocument()
Document * View3DInventorViewer::getDocument ()
Definition at line 727 of file View3DInventorViewer.cpp.
Referenced by MeshPartGui::CurveOnMeshHandler::recomputeDocument(), setOverrideMode(), and setupEditingRoot().
getEditingViewProvider()
ViewProvider * View3DInventorViewer::getEditingViewProvider () const
return currently editing view provider
Definition at line 1123 of file View3DInventorViewer.cpp.
Referenced by Gui::ViewerEventFilter::eventFilter().
getFarPlane()
void View3DInventorViewer::getFarPlane (SbVec3f & rcPt, SbVec3f & rcNormal) const
Returns the far plane represented by its normal and base point.
Definition at line 2941 of file View3DInventorViewer.cpp.
References DraftVecUtils::dist(), and SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager().
getFeedbackSize()
int View3DInventorViewer::getFeedbackSize () const
Return the size of the feedback axis cross. Default is 10.
Definition at line 3636 of file View3DInventorViewer.cpp.
Referenced by Gui::View3DInventorPy::getCornerCrossSize().
getGLPolygon() [1/2]
std::vector< SbVec2f > View3DInventorViewer::getGLPolygon (const std::vector< SbVec2s > & pnts) const
Definition at line 1849 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), and RobotExample::pos.
getGLPolygon() [2/2]
std::vector< SbVec2f > View3DInventorViewer::getGLPolygon (SelectionRole * role = nullptr) const
Definition at line 1885 of file View3DInventorViewer.cpp.
References Gui::NavigationStyle::getPolygon().
Referenced by PointsGui::ViewProviderPoints::clipPointsCallback(), FemGui::TaskCreateElementSet::DefineElementsCallback(), FemGui::TaskCreateNodeSet::DefineNodesCallback(), and getSelectedNodes().
getGradientBackground()
View3DInventorViewer::Background View3DInventorViewer::getGradientBackground () const
Definition at line 1250 of file View3DInventorViewer.cpp.
References Gui::SoFCBackgroundGradient::getGradient(), and Gui::SoFCBackgroundGradient::LINEAR.
Referenced by imageFromFramebuffer().
getGraphicsItems()
std::list< GLGraphicsItem * > View3DInventorViewer::getGraphicsItems () const
Definition at line 1972 of file View3DInventorViewer.cpp.
getGraphicsItemsOfType()
std::list< GLGraphicsItem * > View3DInventorViewer::getGraphicsItemsOfType (const Base::Type & type) const
Definition at line 1977 of file View3DInventorViewer.cpp.
References src.Mod.Test.testPathArray::items, and Path.Post.scripts.grbl_post::type.
Referenced by InspectionGui::ViewProviderProxyObject::addFlag().
getInternalTextureFormat()
GLenum View3DInventorViewer::getInternalTextureFormat () static protected
Definition at line 2000 of file View3DInventorViewer.cpp.
References App::GetApplication(), ParameterGrp::GetASCII(), and App::Application::GetParameterGroupByPath().
Referenced by grabFramebuffer(), imageFromFramebuffer(), and savePicture().
getMaxDimension()
float View3DInventorViewer::getMaxDimension () const
Definition at line 2477 of file View3DInventorViewer.cpp.
References getDimensions(), and KDL::max().
getNaviCube()
NaviCube * View3DInventorViewer::getNaviCube () const
Definition at line 1355 of file View3DInventorViewer.cpp.
getNearPlane()
void View3DInventorViewer::getNearPlane (SbVec3f & rcPt, SbVec3f & rcNormal) const
Returns the near plane represented by its normal and base point.
Definition at line 2919 of file View3DInventorViewer.cpp.
References DraftVecUtils::dist(), and SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager().
getNormalizedPosition()
SbVec2f View3DInventorViewer::getNormalizedPosition (const SbVec2s & pnt) const
Get the normalized position of the 2d point.
Definition at line 2643 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager().
Referenced by getPointOnFocalPlane(), getPointOnLine(), getPointOnXYPlaneOfPlacement(), and projectPointToLine().
getNumSamples()
int View3DInventorViewer::getNumSamples () static
Get the preferred samples from the user settings.
Definition at line 1994 of file View3DInventorViewer.cpp.
References Gui::Multisample::readMSAAFromSettings(), and Gui::Multisample::toSamples().
Referenced by Gui::AlignmentView::AlignmentView(), CAMSimulator::DlgCAMSimulator::GetInstance(), grabFramebuffer(), Gui::View3DInventorPy::saveImage(), setRenderType(), Gui::SplitView3DInventor::SplitView3DInventor(), and Gui::View3DInventor::View3DInventor().
getOverrideMode()
std::string Gui::View3DInventorViewer::getOverrideMode () const inline
Definition at line 229 of file View3DInventorViewer.h.
Referenced by addViewProvider(), Gui::Document::cloneView(), and Gui::Document::createView().
getPickedPoint()
const SoPickedPoint * View3DInventorViewer::getPickedPoint (SoEventCallback * n) const
Definition at line 3099 of file View3DInventorViewer.cpp.
Referenced by MeshPartGui::CurveOnMeshHandler::Private::vertexCallback().
getPointOnFocalPlane()
SbVec3f View3DInventorViewer::getPointOnFocalPlane (const SbVec2s & pnt) const
Returns the 3d point on the focal plane to the given 2d point.
Definition at line 2846 of file View3DInventorViewer.cpp.
References getNormalizedPosition(), and SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager().
Referenced by Gui::View3DInventorViewerPy::getPointOnFocalPlane(), and Gui::View3DInventorPy::getPointOnFocalPlane().
getPointOnLine()
SbVec3f View3DInventorViewer::getPointOnLine (const SbVec2s & pnt, const SbVec3f & axisCenter, const SbVec3f & axis) const
Returns the 3d point on a line to the given 2d point.
Definition at line 2797 of file View3DInventorViewer.cpp.
References SCL.SimpleDataTypes::e, getNormalizedPosition(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), intersection(), and projectLineOntoPlane().
getPointOnRay() [1/2]
SoPickedPoint * View3DInventorViewer::getPointOnRay (const SbVec2s & pos, const ViewProvider * vp) const
Helper method to get picked entities while editing. It's in the responsibility of the caller to delete the returned instance.
Definition at line 982 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getCamera(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getPickRadius(), Gui::ViewProvider::getRoot(), SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getViewportRegion(), and RobotExample::pos.
getPointOnRay() [2/2]
SoPickedPoint * View3DInventorViewer::getPointOnRay (const SbVec3f & pos, const SbVec3f & dir, const ViewProvider * vp) const
Helper method to get picked entities while editing. It's in the responsibility of the caller to delete the returned instance.
Definition at line 1030 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getCamera(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getPickRadius(), Gui::ViewProvider::getRoot(), SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getViewportRegion(), and RobotExample::pos.
getPointOnViewport()
SbVec2s View3DInventorViewer::getPointOnViewport (const SbVec3f & pnt) const
Returns the 2d coordinates on the viewport to the given 3d point.
Definition at line 2875 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager().
Referenced by Gui::View3DInventorPy::getPointOnViewport(), and Gui::NavigationStyle::spin().
getPointOnXYPlaneOfPlacement()
SbVec3f View3DInventorViewer::getPointOnXYPlaneOfPlacement (const SbVec2s & pnt, const Base::Placement & plc) const
Returns the 3d point on the XY plane of a placement to the given 2d point.
Definition at line 2742 of file View3DInventorViewer.cpp.
References getNormalizedPosition(), Base::Placement::getPosition(), Base::Placement::getRotation(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), Base::Rotation::multVec(), and RobotExample::pos.
getPolygon()
const std::vector< SbVec2s > & View3DInventorViewer::getPolygon (SelectionRole * role = nullptr) const
Definition at line 1786 of file View3DInventorViewer.cpp.
References Gui::NavigationStyle::getPolygon().
getPyObject()
PyObject * View3DInventorViewer::getPyObject () virtual
Definition at line 4165 of file View3DInventorViewer.cpp.
Referenced by Gui::AbstractSplitViewPy::getViewer(), and Gui::AbstractSplitViewPy::sequence_item().
getRenderType()
View3DInventorViewer::RenderType View3DInventorViewer::getRenderType () const
Definition at line 2091 of file View3DInventorViewer.cpp.
getUpDirection()
SbVec3f View3DInventorViewer::getUpDirection () const
Returns the up direction
Definition at line 2617 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager().
Referenced by Gui::View3DInventorPy::getUpDirection().
getViewDirection()
SbVec3f View3DInventorViewer::getViewDirection () const
Returns the view direction from the user's eye point in direction to the viewport which is actually the negative normal of the near plane. The vector is normalized to length of 1.
Definition at line 2597 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager().
Referenced by Gui::View3DInventorPy::getViewDirection(), and Gui::Dialog::Clipping::onFromViewClicked().
getViewportOnXYPlaneOfPlacement()
Base::BoundBox2d View3DInventorViewer::getViewportOnXYPlaneOfPlacement (Base::Placement plc) const
Returns the bounding box on the XY plane of a placement to the given 2d point.
Definition at line 2673 of file View3DInventorViewer.cpp.
References SCL.SimpleDataTypes::f, Base::Placement::getPosition(), Base::Placement::getRotation(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), Base::Placement::invert(), Base::Rotation::multVec(), RobotExample::pos, Base::Placement::toMatrix(), MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by SketcherGui::ViewProviderSketch::onCameraChanged().
getViewProviderByPath()
ViewProvider * View3DInventorViewer::getViewProviderByPath (SoPath * path) const
get view provider by path
Definition at line 4092 of file View3DInventorViewer.cpp.
References Base::Console(), Gui::Document::getViewProviderByPathFromHead(), and Base::ConsoleSingleton::Warning().
Referenced by Gui::View3DInventorPy::getObjectInfo(), Gui::View3DInventorPy::getObjectsInfo(), and Gui::View3DInventor::getObjInfoRay().
getViewProviderByPathFromTail()
ViewProvider * View3DInventorViewer::getViewProviderByPathFromTail (SoPath * path) const
Definition at line 4101 of file View3DInventorViewer.cpp.
References Base::Console(), Gui::Document::getViewProviderByPathFromTail(), and Base::ConsoleSingleton::Warning().
Referenced by InspectionGui::ViewProviderInspection::inspectCallback(), and MeshPartGui::CurveOnMeshHandler::Private::vertexCallback().
getViewProvidersOfType()
std::vector< ViewProvider * > View3DInventorViewer::getViewProvidersOfType (const Base::Type & typeId) const
get all view providers of given type
Definition at line 4110 of file View3DInventorViewer.cpp.
References Base::Console(), Gui::Document::getViewProvidersOfType(), and Base::ConsoleSingleton::Warning().
Referenced by PointsGui::ViewProviderPoints::clipPointsCallback(), and Gui::View3DInventorPy::getViewProvidersOfType().
grabFramebuffer()
QImage View3DInventorViewer::grabFramebuffer ()
Definition at line 2096 of file View3DInventorViewer.cpp.
References getInternalTextureFormat(), getNumSamples(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), and renderToFramebuffer().
Referenced by Gui::View3DInventorViewerPy::grabFramebuffer(), savePicture(), and setRenderType().
hasAxisCross()
bool View3DInventorViewer::hasAxisCross ()
Definition at line 1388 of file View3DInventorViewer.cpp.
Referenced by Gui::View3DInventorPy::hasAxisCross().
hasClippingPlane()
bool View3DInventorViewer::hasClippingPlane () const
Checks whether a clipping plane is set or not.
Definition at line 3054 of file View3DInventorViewer.cpp.
Referenced by Gui::View3DInventor::hasClippingPlane().
hasViewProvider()
bool View3DInventorViewer::hasViewProvider (ViewProvider * pcProvider) const
Checks if the view provider is a top-level object of the scene.
Definition at line 808 of file View3DInventorViewer.cpp.
imageFromFramebuffer()
void View3DInventorViewer::imageFromFramebuffer (int width, int height, int samples, const QColor & bgcolor, QImage & img)
Definition at line 2137 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::backgroundColor, Base::Console(), getGradientBackground(), getInternalTextureFormat(), renderToFramebuffer(), SIM::Coin3D::Quarter::QuarterWidget::setBackgroundColor(), setGradientBackground(), and Base::ConsoleSingleton::Warning().
Referenced by Gui::View3DInventor::print(), Gui::Thumbnail::SaveDocFile(), and savePicture().
init()
void View3DInventorViewer::init ()
Definition at line 404 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::addFinishCallback(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::addStartCallback(), Gui::SoFCUnifiedSelection::applySettings(), Gui::SelectionObserver::attachSelection(), draftgeoutils.intersections::connect(), Base::Console(), SIM::Coin3D::Quarter::QuarterWidget::devicePixelRatio, SIM::Coin3D::Quarter::QuarterWidget::devicePixelRatioChanged(), SCL.SimpleDataTypes::e, SIM::Coin3D::Quarter::QuarterWidget::getEventFilter(), SIM::Coin3D::Quarter::QuarterWidget::getHeadlight(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::isSeekValuePercentage(), SIM::Coin3D::Quarter::EventFilter::registerInputDevice(), SIM::Coin3D::Quarter::QuarterWidget::setBackgroundColor(), SIM::Coin3D::Quarter::QuarterWidget::setClearWindow(), setGradientBackground(), setRenderCache(), setSceneGraph(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::setSeekDistance(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::setSeekTime(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::setSeekValueAsPercentage(), setViewing(), ViewerEventFilter, and Base::ConsoleSingleton::Warning().
Referenced by DocumentObject.DocumentObject::onChanged(), and View3DInventorViewer().
isAnimating()
bool View3DInventorViewer::isAnimating () const
Returns
Whether or not any animation is currently active
Definition at line 3509 of file View3DInventorViewer.cpp.
References Gui::NavigationStyle::isAnimating().
Referenced by renderScene(), and setSeekMode().
isAnimationEnabled()
bool View3DInventorViewer::isAnimationEnabled () const
Returns
Whether or not it is possible to start any animation
Definition at line 3493 of file View3DInventorViewer.cpp.
References Gui::NavigationStyle::isAnimationEnabled().
Referenced by Gui::View3DInventorPy::isAnimationEnabled(), moveCameraTo(), and viewAll().
isBacklightEnabled()
bool View3DInventorViewer::isBacklightEnabled () const
Definition at line 1528 of file View3DInventorViewer.cpp.
isEditing()
bool Gui::View3DInventorViewer::isEditing () const inline
Definition at line 266 of file View3DInventorViewer.h.
Referenced by Gui::GestureNavigationStyle::is2DViewing(), Gui::GestureNavigationStyle::processSoEvent(), Gui::InventorNavigationStyle::processSoEvent(), Gui::CADNavigationStyle::processSoEvent(), Gui::RevitNavigationStyle::processSoEvent(), Gui::BlenderNavigationStyle::processSoEvent(), Gui::MayaGestureNavigationStyle::processSoEvent(), Gui::TouchpadNavigationStyle::processSoEvent(), Gui::OpenCascadeNavigationStyle::processSoEvent(), Gui::OpenSCADNavigationStyle::processSoEvent(), and Gui::TinkerCADNavigationStyle::processSoEvent().
isEditingViewProvider()
bool View3DInventorViewer::isEditingViewProvider () const
return whether a view provider is edited
reset from edit mode
Definition at line 1117 of file View3DInventorViewer.cpp.
isEnabledNaviCube()
bool View3DInventorViewer::isEnabledNaviCube () const
Definition at line 1343 of file View3DInventorViewer.cpp.
Referenced by Gui::View3DInventorViewerPy::isEnabledNaviCube().
isEnabledVBO()
bool View3DInventorViewer::isEnabledVBO () const
Definition at line 1286 of file View3DInventorViewer.cpp.
isFeedbackVisible()
bool View3DInventorViewer::isFeedbackVisible () const
Check if the feedback axis cross is visible.
Definition at line 3607 of file View3DInventorViewer.cpp.
Referenced by Gui::View3DInventorPy::isCornerCrossVisible(), and setFeedbackSize().
isPopupMenuEnabled()
bool View3DInventorViewer::isPopupMenuEnabled () const
Definition at line 3579 of file View3DInventorViewer.cpp.
References Gui::NavigationStyle::isPopupMenuEnabled().
Referenced by Gui::View3DInventorPy::isPopupMenuEnabled().
isRedirectedToSceneGraph()
bool Gui::View3DInventorViewer::isRedirectedToSceneGraph () const inline
Definition at line 270 of file View3DInventorViewer.h.
Referenced by InspectionGui::ViewProviderInspection::inspectCallback(), Gui::View3DInventorViewerPy::isRedirectedToSceneGraph(), and processSoEvent().
isRedirectToSceneGraphEnabled()
bool Gui::View3DInventorViewer::isRedirectToSceneGraphEnabled () const inline
Definition at line 272 of file View3DInventorViewer.h.
isSelecting()
bool View3DInventorViewer::isSelecting () const
Definition at line 1781 of file View3DInventorViewer.cpp.
References Gui::NavigationStyle::isSelecting().
isSelectionEnabled()
bool View3DInventorViewer::isSelectionEnabled () const
Definition at line 1797 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph().
isSpinning()
bool View3DInventorViewer::isSpinning () const
Returns
Whether or not a spinning animation is currently active e.g. after a user drag
Definition at line 3517 of file View3DInventorViewer.cpp.
References Gui::NavigationStyle::isSpinning().
Referenced by Gui::Dialog::DemoMode::onAngleSliderValueChanged(), Gui::Dialog::DemoMode::onAutoPlay(), Gui::Dialog::DemoMode::onPlayButtonToggled(), and Gui::Dialog::DemoMode::onSpeedSliderValueChanged().
isSpinningAnimationEnabled()
bool View3DInventorViewer::isSpinningAnimationEnabled () const
Returns
Whether or not it is possible to start a spinning animation e.g. after dragging
Definition at line 3501 of file View3DInventorViewer.cpp.
References Gui::NavigationStyle::isSpinningAnimationEnabled().
moveCameraTo()
void View3DInventorViewer::moveCameraTo (const SbRotation & orientation, const SbVec3f & position, int duration = -1)
Definition at line 3144 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getCamera(), isAnimationEnabled(), and startAnimation().
Referenced by Gui::View3DInventorPy::viewPosition().
navigationStyle()
NavigationStyle * View3DInventorViewer::navigationStyle () const
Definition at line 1513 of file View3DInventorViewer.cpp.
Referenced by Gui::View3DInventorViewerPy::getNavigationStyle(), Gui::View3DInventorPy::getNavigationType(), Gui::View3DInventorPy::zoomIn(), and Gui::View3DInventorPy::zoomOut().
onSelectionChanged()
void Gui::View3DInventorViewer::onSelectionChanged (const SelectionChanges & Reason) override virtual
Observer message from the Selection.
Implements Gui::SelectionObserver.
Referenced by setDocument().
pickPoint() [1/2]
SoPickedPoint * View3DInventorViewer::pickPoint (const SbVec2s & pos) const
This method is provided for convenience and does basically the same as method above unless that it returns an SoPickedPoint object with additional information.
Note
It is in the response of the client programmer to delete the returned SoPickedPoint object.
Definition at line 3087 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getViewportRegion(), and RobotExample::pos.
pickPoint() [2/2]
bool View3DInventorViewer::pickPoint (const SbVec2s & pos, SbVec3f & point, SbVec3f & norm) const
This method picks the closest point to the camera in the underlying scenegraph and returns its location and normal. If no point was picked false is returned.
Definition at line 3064 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getViewportRegion(), and RobotExample::pos.
Referenced by PartGui::ViewProviderCurveNet::handleEvent().
printDimension()
void View3DInventorViewer::printDimension () const protected
Definition at line 2517 of file View3DInventorViewer.cpp.
References getDimensions(), Gui::getMainWindow(), Base::Quantity::MilliMetre, Base::UnitsApi::schemaTranslate(), Gui::MainWindow::setPaneText(), and Base::Quantity::setValue().
Referenced by renderFramebuffer(), renderGLImage(), and renderScene().
processSoEvent()
bool View3DInventorViewer::processSoEvent (const SoEvent * event) override protected virtual
Passes an event to the event manager.
Parameters
[in] event to pass
Return values
Returns true if the event was successfully processed
Reimplemented from SIM::Coin3D::Quarter::SoQTQuarterAdaptor.
Definition at line 2561 of file View3DInventorViewer.cpp.
References isRedirectedToSceneGraph(), Gui::NavigationStyle::processEvent(), NaviCube::processSoEvent(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::processSoEvent(), and AttachmentEditor.TaskAttachmentEditor::Q.
processSoEventBase()
bool View3DInventorViewer::processSoEventBase (const SoEvent *const ev) protected
Definition at line 2592 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::processSoEvent().
Referenced by Gui::NavigationStyle::processSoEvent().
projectOnFarPlane()
SbVec3f View3DInventorViewer::projectOnFarPlane (const SbVec2f & pt) const
Project the given normalized 2d point onto the far plane
Definition at line 2979 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager().
projectOnNearPlane()
SbVec3f View3DInventorViewer::projectOnNearPlane (const SbVec2f & pt) const
Project the given normalized 2d point onto the near plane
Definition at line 2963 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager().
projectPointToLine()
void View3DInventorViewer::projectPointToLine (const SbVec2s & pt, SbVec3f & pt1, SbVec3f & pt2) const
Project the given 2d point to a line
Definition at line 2995 of file View3DInventorViewer.cpp.
References getNormalizedPosition(), and SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager().
Referenced by Gui::View3DInventorPy::projectPointToLine().
pubSeekToPoint() [1/2]
bool View3DInventorViewer::pubSeekToPoint (const SbVec2s & pos)
Definition at line 3111 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::seekToPoint().
pubSeekToPoint() [2/2]
void View3DInventorViewer::pubSeekToPoint (const SbVec3f & pos)
Definition at line 3116 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::seekToPoint().
removeEventCallback()
void View3DInventorViewer::removeEventCallback (SoType eventtype, SoEventCallbackCB * cb, void * userdata = nullptr)
Unregister the given callback function cb.
Definition at line 4087 of file View3DInventorViewer.cpp.
Referenced by PointsGui::ViewProviderPoints::clipPointsCallback(), FemGui::TaskCreateElementSet::DefineElementsCallback(), DefineElementsCallback(), FemGui::TaskCreateNodeSet::DefineNodesCallback(), DefineNodesCallback(), MeshPartGui::CurveOnMeshHandler::disableCallback(), InspectionGui::ViewProviderInspection::inspectCallback(), FemGui::TaskPostDataAlongLine::pointCallback(), FemGui::TaskPostDataAtPoint::pointCallback(), Gui::View3DInventorPy::removeEventCallback(), Gui::View3DInventorPy::removeEventCallbackPivy(), resetEditingViewProvider(), FemGui::TaskPostDataAlongLine::~TaskPostDataAlongLine(), and FemGui::TaskPostDataAtPoint::~TaskPostDataAtPoint().
removeGraphicsItem()
void View3DInventorViewer::removeGraphicsItem (GLGraphicsItem * item)
Definition at line 1967 of file View3DInventorViewer.cpp.
Referenced by Gui::PolyPickerSelection::terminate(), and Gui::RubberbandSelection::terminate().
removeViewProvider()
void View3DInventorViewer::removeViewProvider (ViewProvider * pcProvider)
remove a ViewProvider
Definition at line 852 of file View3DInventorViewer.cpp.
References Gui::ViewProvider::getBackRoot(), Gui::ViewProvider::getFrontRoot(), Gui::ViewProvider::getRoot(), and resetEditingViewProvider().
Referenced by MeshPartGui::CurveOnMeshHandler::disableCallback(), Gui::Document::slotDeletedObject(), and FemGui::PointMarker::~PointMarker().
renderFramebuffer()
void View3DInventorViewer::renderFramebuffer () protected
Definition at line 2267 of file View3DInventorViewer.cpp.
References NaviCube::drawNaviCube(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), glBindTexture, glClear, glDisable, glEnable, glMatrixMode, and printDimension().
Referenced by actualRedraw().
renderGLImage()
void View3DInventorViewer::renderGLImage () protected
Definition at line 2310 of file View3DInventorViewer.cpp.
References NaviCube::drawNaviCube(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), glClear, glDisable, glMatrixMode, and printDimension().
Referenced by actualRedraw().
renderScene()
void View3DInventorViewer::renderScene () protected
Definition at line 2350 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::actualRedraw(), SIM::Coin3D::Quarter::QuarterWidget::backgroundColor, SIM::Coin3D::Quarter::QuarterWidget::devicePixelRatio, SIM::Coin3D::Quarter::SoQTQuarterAdaptor::draw2DString(), NaviCube::drawNaviCube(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::framesPerSecond, SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getGLWidget(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), glClear, glClearColor, glEnable, isAnimating(), printDimension(), SoDevicePixelRatioElement::set(), Gui::SoGLWidgetElement::set(), Gui::SoGLRenderActionElement::set(), Gui::SoGLVBOActivatedElement::set(), and Path.Log::warning().
Referenced by actualRedraw().
renderToFramebuffer()
void View3DInventorViewer::renderToFramebuffer (QtGLFramebufferObject * fbo)
Definition at line 2208 of file View3DInventorViewer.cpp.
References Gui::SoBoxSelectionRenderAction::apply(), SIM::Coin3D::Quarter::QuarterWidget::backgroundColor, SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), glClear, glClearColor, glDepthFunc, glDisable, and glEnable.
Referenced by grabFramebuffer(), imageFromFramebuffer(), and setRenderType().
resetEditingRoot()
void View3DInventorViewer::resetEditingRoot (bool updateLinks = true)
Definition at line 928 of file View3DInventorViewer.cpp.
References Base::Console(), src.Mod.AddonManager.NetworkManager::count, SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), FC_ERR, Gui::ViewProvider::getRoot(), Gui::ViewProvider::getTransformNode(), SplineSurface::i, Path.Post.scripts.refactored_centroid_post::str, src.Mod.Test.testmakeWireString::String, Path.Post.scripts.grbl_post::type, Gui::ViewProviderLink::updateLinks(), and Base::ConsoleSingleton::Warning().
Referenced by Gui::View3DInventorViewerPy::resetEditingRoot(), resetEditingViewProvider(), setupEditingRoot(), and ~View3DInventorViewer().
resetEditingViewProvider()
void View3DInventorViewer::resetEditingViewProvider ()
reset from edit mode
Definition at line 1096 of file View3DInventorViewer.cpp.
References Gui::ViewProvider::eventCallback(), SIM::Coin3D::Quarter::QuarterWidget::getSoEventManager(), removeEventCallback(), resetEditingRoot(), and Gui::ViewProvider::unsetEditViewer().
Referenced by Gui::Document::_resetEdit(), and removeViewProvider().
saveGraphic()
void View3DInventorViewer::saveGraphic (int pagesize, const QColor & bgcolor, SoVectorizeAction * va) const
Definition at line 1714 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), and pagesize().
Referenced by dumpToFile(), and Gui::View3DInventorPy::saveVectorGraphic().
savePicture()
void View3DInventorViewer::savePicture (int width, int height, int sample, const QColor & bg, QImage & img) const
Creates an image with width width and height height of the current scene graph using a multi-sampling of sample and exports the rendered scenegraph to an image.
Definition at line 1559 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::backgroundColor, App::GetApplication(), ParameterGrp::GetASCII(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getGLWidget(), SIM::Coin3D::Quarter::QuarterWidget::getHeadlight(), getInternalTextureFormat(), App::Application::GetParameterGroupByPath(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getViewportRegion(), grabFramebuffer(), imageFromFramebuffer(), Gui::SoFCOffscreenRenderer::instance(), Gui::SoQtOffscreenRenderer::render(), Gui::SoQtOffscreenRenderer::setBackgroundColor(), Gui::SoQtOffscreenRenderer::setInternalTextureFormat(), Gui::SoQtOffscreenRenderer::setNumPasses(), Gui::SoFCOffscreenRenderer::writeToImage(), and Gui::SoQtOffscreenRenderer::writeToImage().
Referenced by Gui::View3DInventorPy::saveImage().
screenCoordsOfPath()
SbVec2f View3DInventorViewer::screenCoordsOfPath (SoPath * path) const
Returns the screen coordinates of the origin of the path's tail object.
Return value is in floating-point pixels, origin at bottom-left.
Definition at line 1803 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getGLWidget(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), and SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getViewportRegion().
searchNode()
bool View3DInventorViewer::searchNode (SoNode * node) const
Definition at line 798 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph().
selectAll()
void View3DInventorViewer::selectAll () protected
Definition at line 2541 of file View3DInventorViewer.cpp.
References replaceobj::objs, Gui::Selection(), and Gui::SelectionSingleton::setSelection().
setAnimationEnabled()
void View3DInventorViewer::setAnimationEnabled (bool enable)
Decide if it should be possible to start any animation.
If the enable flag is false and we're currently animating, the animation will be stopped
Definition at line 3475 of file View3DInventorViewer.cpp.
References Gui::NavigationStyle::setAnimationEnabled().
Referenced by Gui::View3DInventorPy::setAnimationEnabled().
setAxisCross()
void View3DInventorViewer::setAxisCross (bool on)
Definition at line 1360 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph(), and Gui::SoShapeScale::scaleFactor.
Referenced by Gui::View3DInventorPy::setAxisCross().
setAxisLetterColor()
void View3DInventorViewer::setAxisLetterColor (const SbColor & color)
Definition at line 3672 of file View3DInventorViewer.cpp.
References MovieTool::x, XPM_BYTES_PER_PIXEL, XPM_HEIGHT, XPM_PIXEL_MASK, XPM_WIDTH, MovieTool::y, YPM_BYTES_PER_PIXEL, YPM_HEIGHT, YPM_PIXEL_MASK, YPM_WIDTH, ZPM_BYTES_PER_PIXEL, ZPM_HEIGHT, ZPM_PIXEL_MASK, and ZPM_WIDTH.
setBacklightEnabled()
void View3DInventorViewer::setBacklightEnabled (bool on)
Definition at line 1523 of file View3DInventorViewer.cpp.
setCameraOrientation()
void View3DInventorViewer::setCameraOrientation (const SbRotation & orientation, bool moveToCenter = false)
Set the camera's orientation. If isAnimationEnabled() returns true the reorientation is animated, otherwise its directly set.
Definition at line 3121 of file View3DInventorViewer.cpp.
References Gui::NavigationStyle::setCameraOrientation().
Referenced by alignToSelection(), Gui::View3DInventor::onMsg(), Gui::View3DInventorPy::setCameraOrientation(), Gui::View3DInventorPy::viewBottom(), Gui::View3DInventorPy::viewDimetric(), Gui::View3DInventorPy::viewFront(), Gui::View3DInventorPy::viewIsometric(), Gui::View3DInventorPy::viewLeft(), Gui::View3DInventorPy::viewRear(), Gui::View3DInventorPy::viewRight(), Gui::View3DInventorPy::viewTop(), and Gui::View3DInventorPy::viewTrimetric().
setCameraType()
void View3DInventorViewer::setCameraType (SoType type) override virtual
Reimplemented from SIM::Coin3D::Quarter::SoQTQuarterAdaptor.
Definition at line 3126 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), M_PI, SIM::Coin3D::Quarter::SoQTQuarterAdaptor::setCameraType(), and Path.Post.scripts.grbl_post::type.
Referenced by MatGui::AppearancePreview::AppearancePreview(), Gui::View3DInventor::onMsg(), Gui::View3DInventor::setCamera(), and Gui::View3DInventorPy::setCameraType().
setComponentCursor()
void View3DInventorViewer::setComponentCursor (const QCursor & cursor)
Definition at line 4034 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getWidget().
setCursorEnabled()
void View3DInventorViewer::setCursorEnabled (bool enable) virtual
Decide whether or not the mouse pointer cursor should be visible in the rendering canvas.
Definition at line 3645 of file View3DInventorViewer.cpp.
References Gui::NavigationStyle::getViewingMode().
Referenced by abortSelection(), and stopSelection().
setDocument()
void View3DInventorViewer::setDocument (Gui::Document * pcDocument)
Definition at line 710 of file View3DInventorViewer.cpp.
References Gui::Document::getDocument(), App::Document::getName(), Gui::SelectionSingleton::getSelection(), Gui::NoResolve, onSelectionChanged(), Gui::Selection(), and Gui::SelectionChanges::ShowSelection.
Referenced by Gui::View3DInventor::deleteSelf().
setEditing()
void View3DInventorViewer::setEditing (bool edit)
Definition at line 4027 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getWidget().
Referenced by MeshGui::ViewProviderMesh::clipMeshCallback(), PointsGui::ViewProviderPoints::clipPointsCallback(), FemGui::TaskCreateElementSet::DefineElementsCallback(), DefineElementsCallback(), FemGui::TaskCreateNodeSet::DefineNodesCallback(), DefineNodesCallback(), MeshPartGui::CurveOnMeshHandler::disableCallback(), MeshPartGui::CurveOnMeshHandler::enableCallback(), InspectionGui::ViewProviderInspection::inspectCallback(), MeshGui::ViewProviderMesh::partMeshCallback(), FemGui::TaskPostDataAlongLine::pointCallback(), FemGui::TaskPostDataAtPoint::pointCallback(), MeshGui::ViewProviderMesh::segmMeshCallback(), MeshGui::ViewProviderMesh::selectGLCallback(), MeshGui::ViewProviderMesh::trimMeshCallback(), FemGui::TaskPostDataAlongLine::~TaskPostDataAlongLine(), and FemGui::TaskPostDataAtPoint::~TaskPostDataAtPoint().
setEditingCursor()
void View3DInventorViewer::setEditingCursor (const QCursor & cursor)
Definition at line 4039 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getWidget().
Referenced by MeshPartGui::CurveOnMeshHandler::enableCallback().
setEditingTransform()
void View3DInventorViewer::setEditingTransform (const Base::Matrix4D & mat)
Definition at line 884 of file View3DInventorViewer.cpp.
References Base::Matrix4D::getGLMatrix().
Referenced by Gui::Document::setEditingTransform(), setupEditingRoot(), and Gui::Document::slotChangedObject().
setEditingViewProvider()
void View3DInventorViewer::setEditingViewProvider (Gui::ViewProvider * vp, int ModNum)
set the ViewProvider in special edit mode
Definition at line 1083 of file View3DInventorViewer.cpp.
References addEventCallback(), Gui::ViewProvider::eventCallback(), Gui::NavigationStyle::findBoundingSphere(), and Gui::ViewProvider::setEditViewer().
Referenced by Gui::DocumentP::setEditingViewerIfPossible().
setEnabledFPSCounter()
void View3DInventorViewer::setEnabledFPSCounter (bool on)
Definition at line 1276 of file View3DInventorViewer.cpp.
setEnabledNaviCube()
void View3DInventorViewer::setEnabledNaviCube (bool on)
Definition at line 1338 of file View3DInventorViewer.cpp.
Referenced by MatGui::AppearancePreview::AppearancePreview(), and Gui::View3DInventorViewerPy::setEnabledNaviCube().
setEnabledVBO()
void View3DInventorViewer::setEnabledVBO (bool on)
Definition at line 1281 of file View3DInventorViewer.cpp.
setFeedbackSize()
void View3DInventorViewer::setFeedbackSize (int size)
Set the size of the feedback axiscross. The value is interpreted as an approximate percentage chunk of the dimensions of the total canvas.
Definition at line 3618 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), isFeedbackVisible(), and SIM::Coin3D::Quarter::SoQTQuarterAdaptor::isViewing().
Referenced by Gui::View3DInventorPy::setCornerCrossSize().
setFeedbackVisibility()
void View3DInventorViewer::setFeedbackVisibility (bool enable)
Set the flag deciding whether or not to show the axis cross.
Definition at line 3589 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), and SIM::Coin3D::Quarter::SoQTQuarterAdaptor::isViewing().
Referenced by Gui::View3DInventorPy::setCornerCrossVisible().
setGradientBackground()
void View3DInventorViewer::setGradientBackground (View3DInventorViewer::Background grad)
Definition at line 1227 of file View3DInventorViewer.cpp.
References Gui::SoFCBackgroundGradient::LINEAR, Gui::SoFCBackgroundGradient::RADIAL, and Gui::SoFCBackgroundGradient::setGradient().
Referenced by imageFromFramebuffer(), init(), and Gui::View3DInventorViewerPy::setGradientBackground().
setGradientBackgroundColor() [1/2]
void View3DInventorViewer::setGradientBackgroundColor (const SbColor & fromColor, const SbColor & toColor)
Definition at line 1263 of file View3DInventorViewer.cpp.
References Gui::SoFCBackgroundGradient::setColorGradient().
Referenced by Gui::View3DInventorViewerPy::setBackgroundColor(), and Gui::View3DInventorViewerPy::setGradientBackgroundColor().
setGradientBackgroundColor() [2/2]
void View3DInventorViewer::setGradientBackgroundColor (const SbColor & fromColor, const SbColor & toColor, const SbColor & midColor)
Definition at line 1269 of file View3DInventorViewer.cpp.
References Gui::SoFCBackgroundGradient::setColorGradient().
setNaviCubeCorner()
void View3DInventorViewer::setNaviCubeCorner (int cc)
Definition at line 1348 of file View3DInventorViewer.cpp.
References NaviCube::setCorner().
Referenced by Gui::View3DInventorViewerPy::setNaviCubeCorner().
setNavigationType()
void View3DInventorViewer::setNavigationType (Base::Type type)
Definition at line 1488 of file View3DInventorViewer.cpp.
References Base::Type::createInstance(), Base::BaseClass::getClassTypeId(), Base::BaseClass::getTypeId(), Base::Type::getTypeIfDerivedFrom(), Gui::NavigationStyle::setViewer(), and Path.Post.scripts.grbl_post::type.
Referenced by Gui::View3DInventor::customEvent(), and Gui::View3DInventorPy::setNavigationType().
setOverrideMode()
void View3DInventorViewer::setOverrideMode (const std::string & mode)
display override mode
Definition at line 1129 of file View3DInventorViewer.cpp.
References Base::Persistence::getClassTypeId(), getDocument(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), and Gui::Document::getViewProvidersOfType().
setPopupMenuEnabled()
void View3DInventorViewer::setPopupMenuEnabled (bool on)
Definition at line 3574 of file View3DInventorViewer.cpp.
References Gui::NavigationStyle::setPopupMenuEnabled().
Referenced by MatGui::AppearancePreview::AppearancePreview(), and Gui::View3DInventorPy::setPopupMenuEnabled().
setRedirectToSceneGraph()
void Gui::View3DInventorViewer::setRedirectToSceneGraph (bool redirect) inline
Definition at line 269 of file View3DInventorViewer.h.
Referenced by MatGui::AppearancePreview::AppearancePreview(), InspectionGui::ViewProviderInspection::inspectCallback(), and Gui::View3DInventorViewerPy::setRedirectToSceneGraph().
setRedirectToSceneGraphEnabled()
void Gui::View3DInventorViewer::setRedirectToSceneGraphEnabled (bool enable) inline
Definition at line 271 of file View3DInventorViewer.h.
Referenced by InspectionGui::ViewProviderInspection::inspectCallback().
setRenderCache()
void View3DInventorViewer::setRenderCache (int mode)
Definition at line 1291 of file View3DInventorViewer.cpp.
References Gui::ViewParams::getRenderCache(), Gui::ViewParams::instance(), MeshCore::MeshIO::OFF, Gui::SoFCSeparator::setCacheMode(), and SCL.Builtin::TRUE.
Referenced by init().
setRenderType()
void View3DInventorViewer::setRenderType (RenderType type)
Definition at line 2044 of file View3DInventorViewer.cpp.
References Framebuffer, getNumSamples(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), grabFramebuffer(), Image, Native, renderToFramebuffer(), and Path.Post.scripts.grbl_post::type.
Referenced by Gui::PolyPickerSelection::initialize(), Gui::RubberbandSelection::initialize(), Gui::PolyPickerSelection::terminate(), and Gui::RubberbandSelection::terminate().
setSceneGraph()
void View3DInventorViewer::setSceneGraph (SoNode * node) override virtual
Sets the Inventor scenegraph to be rendered
Reimplemented from SIM::Coin3D::Quarter::SoQTQuarterAdaptor.
Definition at line 1533 of file View3DInventorViewer.cpp.
References Gui::NavigationStyle::findBoundingSphere(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), and SIM::Coin3D::Quarter::SoQTQuarterAdaptor::setSceneGraph().
Referenced by Gui::View3DInventor::deleteSelf(), init(), Gui::View3DInventorViewerPy::setSceneGraph(), and ~View3DInventorViewer().
setSeekMode()
void View3DInventorViewer::setSeekMode (bool on) override protected virtual
Reimplemented from SIM::Coin3D::Quarter::SoQTQuarterAdaptor.
Definition at line 2448 of file View3DInventorViewer.cpp.
References Gui::NavigationStyle::IDLE, Gui::NavigationStyle::INTERACT, isAnimating(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::isViewing(), Gui::NavigationStyle::SEEK_WAIT_MODE, SIM::Coin3D::Quarter::SoQTQuarterAdaptor::setSeekMode(), Gui::NavigationStyle::setViewingMode(), and stopAnimating().
Referenced by Gui::NavigationStyle::setSeekMode().
setSelectionEnabled()
void View3DInventorViewer::setSelectionEnabled (bool enable)
Definition at line 1791 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph().
Referenced by AssemblyGui::ViewProviderAssembly::endMove(), and InspectionGui::ViewProviderInspection::inspectCallback().
setSpinningAnimationEnabled()
void View3DInventorViewer::setSpinningAnimationEnabled (bool enable)
Decide if it should be possible to start a spin animation of the model in the viewer by releasing the mouse button while dragging.
If the enable flag is false and we're currently animating, the spin animation will be stopped
Definition at line 3485 of file View3DInventorViewer.cpp.
References Gui::NavigationStyle::setSpinningAnimationEnabled().
setupEditingRoot()
void View3DInventorViewer::setupEditingRoot (SoNode * node = nullptr, const Base::Matrix4D * mat = nullptr)
Definition at line 899 of file View3DInventorViewer.cpp.
References Gui::coinRemoveAllChildren(), src.Mod.AddonManager.NetworkManager::count, getDocument(), Gui::ViewProvider::getRoot(), Gui::ViewProvider::getTransformNode(), SplineSurface::i, resetEditingRoot(), setEditingTransform(), and Gui::ViewProviderLink::updateLinks().
Referenced by Gui::View3DInventorViewerPy::setupEditingRoot().
setViewDirection()
void View3DInventorViewer::setViewDirection (SbVec3f dir)
Definition at line 2610 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getCamera(), and SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager().
Referenced by MatGui::AppearancePreview::AppearancePreview(), and Gui::View3DInventorPy::setViewDirection().
setViewing()
void View3DInventorViewer::setViewing (bool enable) override virtual
Reimplemented from SIM::Coin3D::Quarter::SoQTQuarterAdaptor.
Definition at line 3658 of file View3DInventorViewer.cpp.
References Gui::NavigationStyle::IDLE, Gui::NavigationStyle::INTERACT, SIM::Coin3D::Quarter::SoQTQuarterAdaptor::isViewing(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::setViewing(), and Gui::NavigationStyle::setViewingMode().
Referenced by MatGui::AppearancePreview::AppearancePreview(), init(), and Gui::NavigationStyle::setViewing().
showRotationCenter()
void View3DInventorViewer::showRotationCenter (bool show)
Definition at line 1393 of file View3DInventorViewer.cpp.
References exportCSG::center(), App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetFloat(), App::Application::GetParameterGroupByPath(), Gui::NavigationStyle::getRotationCenter(), SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph(), ParameterGrp::GetUnsigned(), and bimcommands.BimViews::show().
Referenced by Gui::NavigationStyle::setViewingMode().
startAnimation()
void View3DInventorViewer::startAnimation (const SbRotation & orientation, const SbVec3f & rotationCenter, const SbVec3f & translation, int duration = -1, bool wait = false)
Change the camera pose with an animation.
Parameters
orientation The new orientation
rotationCenter The rotation center
translation An additional translation on top of the translation caused by the rotation around the rotation center
duration The duration in milliseconds
wait When false, start the animation and continue (asynchronous). When true, start the animation and wait for the animation to finish (synchronous)
Definition at line 3531 of file View3DInventorViewer.cpp.
References App::GetApplication(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), and Gui::NavigationStyle::startAnimating().
Referenced by moveCameraTo(), Gui::NavigationStyle::setCameraOrientation(), and Gui::NavigationStyle::translateCamera().
startSelection()
void View3DInventorViewer::startSelection (View3DInventorViewer::SelectionMode mode = Lasso)
Definition at line 1764 of file View3DInventorViewer.cpp.
References Gui::NavigationStyle::startSelection().
startSpinningAnimation()
void View3DInventorViewer::startSpinningAnimation (const SbVec3f & axis, float velocity)
Start an infinite spin animation.
Parameters
axis The rotation axis in screen coordinates
velocity The angular velocity in radians per second
Definition at line 3563 of file View3DInventorViewer.cpp.
References Gui::NavigationStyle::startAnimating().
Referenced by Gui::NavigationStyle::doSpin(), and Gui::View3DInventorPy::startAnimating().
stopAnimating()
void View3DInventorViewer::stopAnimating ()
Definition at line 3569 of file View3DInventorViewer.cpp.
References Gui::NavigationStyle::stopAnimating().
Referenced by Gui::Dialog::DemoMode::onPlayButtonToggled(), setSeekMode(), Gui::View3DInventorPy::stopAnimating(), and Gui::View3DInventor::stopAnimating().
stopSelection()
void View3DInventorViewer::stopSelection ()
Definition at line 1775 of file View3DInventorViewer.cpp.
References setCursorEnabled(), and Gui::NavigationStyle::stopSelection().
toggleClippingPlane()
void View3DInventorViewer::toggleClippingPlane (int toggle = -1, bool beforeEditing = false, bool noManip = false, const Base::Placement & pla = Base::Placement())
Adds or remove a manipulator to/from the scenegraph.
Definition at line 3008 of file View3DInventorViewer.cpp.
References MengerSponge::box, getBoundingBox(), Base::Placement::getPosition(), Base::Placement::getRotation(), and Base::Rotation::multVec().
Referenced by Gui::View3DInventor::toggleClippingPlane(), and Gui::View3DInventorPy::toggleClippingPlane().
toQPoint()
QPoint View3DInventorViewer::toQPoint (const SbVec2s & pnt) const
Converts Inventor coordinates into Qt coordinates. The conversion takes the device pixel ratio into account.
Definition at line 2891 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::devicePixelRatio, and SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager().
turn3dDimensionsOff()
void View3DInventorViewer::turn3dDimensionsOff ()
Definition at line 4140 of file View3DInventorViewer.cpp.
turn3dDimensionsOn()
void View3DInventorViewer::turn3dDimensionsOn ()
Definition at line 4135 of file View3DInventorViewer.cpp.
turnAllDimensionsOff()
void View3DInventorViewer::turnAllDimensionsOff ()
Definition at line 4124 of file View3DInventorViewer.cpp.
turnAllDimensionsOn()
void View3DInventorViewer::turnAllDimensionsOn ()
Definition at line 4119 of file View3DInventorViewer.cpp.
turnDeltaDimensionsOff()
void View3DInventorViewer::turnDeltaDimensionsOff ()
Definition at line 4160 of file View3DInventorViewer.cpp.
turnDeltaDimensionsOn()
void View3DInventorViewer::turnDeltaDimensionsOn ()
Definition at line 4155 of file View3DInventorViewer.cpp.
updateOverrideMode()
void View3DInventorViewer::updateOverrideMode (const std::string & mode)
update override mode. doesn't affect providers
Definition at line 1164 of file View3DInventorViewer.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager().
viewAll() [1/2]
void View3DInventorViewer::viewAll () override virtual
Reposition the current camera so we can see the complete scene.
Reimplemented from SIM::Coin3D::Quarter::QuarterWidget.
Definition at line 3264 of file View3DInventorViewer.cpp.
References animatedViewAll(), MengerSponge::box, Gui::SoSkipBoundingGroup::EXCLUDE_BBOX, getBoundingBox(), SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getViewportRegion(), toolbit-attributes::group, SplineSurface::i, Gui::SoSkipBoundingGroup::INCLUDE_BBOX, isAnimationEnabled(), and M_PI.
Referenced by MatGui::AppearancePreview::AppearancePreview(), Gui::View3DInventorPy::fitAll(), Gui::View3DInventor::onMsg(), Gui::View3DInventor::viewAll(), and viewAll().
viewAll() [2/2]
void View3DInventorViewer::viewAll (float factor)
Definition at line 3316 of file View3DInventorViewer.cpp.
References MengerSponge::box, cube, Gui::SoSkipBoundingGroup::EXCLUDE_BBOX, getBoundingBox(), SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph(), SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getViewportRegion(), toolbit-attributes::group, SplineSurface::i, Gui::SoSkipBoundingGroup::INCLUDE_BBOX, and viewAll().
viewSelection()
void View3DInventorViewer::viewSelection ()
Reposition the current camera so we can see all selected objects of the scene. Therefore we search for all SOFCSelection nodes, if none of them is selected nothing happens.
Definition at line 3376 of file View3DInventorViewer.cpp.
References Base::BoundBox3< Precision >::Add(), MengerSponge::box, draftutils.gui_utils::getSelection, SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::getViewportRegion(), Gui::Application::getViewProvider(), Gui::Application::Instance, Base::BoundBox3< Precision >::IsValid(), Base::BoundBox3< Precision >::MaxX, Base::BoundBox3< Precision >::MaxY, Base::BoundBox3< Precision >::MaxZ, Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, Base::BoundBox3< Precision >::MinZ, Gui::NoResolve, and Gui::Selection().
Referenced by Gui::View3DInventor::onMsg().
viewVR()
void View3DInventorViewer::viewVR ()
Breaks out a VR window for a Rift.
Definition at line 3238 of file View3DInventorViewer.cpp.
Referenced by Gui::View3DInventor::onMsg().
Friends And Related Function Documentation
GLPainter
friend class GLPainter friend
Definition at line 552 of file View3DInventorViewer.h.
NavigationStyle
friend class NavigationStyle friend
Definition at line 551 of file View3DInventorViewer.h.
ViewerEventFilter
friend class ViewerEventFilter friend
Definition at line 553 of file View3DInventorViewer.h.
Referenced by init().
The documentation for this class was generated from the following files:
View3DInventorViewer.h
View3DInventorViewer.cpp