FreeCAD: ModelRefine Namespace Reference
ModelRefine Namespace Reference
Classes
class FaceAdjacencySplitter
class FaceEqualitySplitter
class FaceTypedBase
class FaceTypedBSpline
class FaceTypedCylinder
class FaceTypedPlane
class FaceTypeSplitter
class FaceUniter
class WireSort
Typedefs
using FaceVectorType = std::vector< TopoDS_Face >
using EdgeVectorType = std::vector< TopoDS_Edge >
using ShapeVectorType = std::vector< TopoDS_Shape >
using ShapePairType = std::pair< TopoDS_Shape, TopoDS_Shape >
Functions
void getFaceEdges (const TopoDS_Face &face, EdgeVectorType &edges)
void boundaryEdges (const FaceVectorType &faces, EdgeVectorType &edgesOut)
TopoDS_Shell removeFaces (const TopoDS_Shell &shell, const FaceVectorType &faces)
FaceTypedPlane & getPlaneObject ()
FaceTypedCylinder & getCylinderObject ()
FaceTypedBSpline & getBSplineObject ()
Typedef Documentation
EdgeVectorType
using ModelRefine::EdgeVectorType = typedef std::vector<TopoDS_Edge>
Definition at line 68 of file modelRefine.h.
FaceVectorType
using ModelRefine::FaceVectorType = typedef std::vector<TopoDS_Face>
Definition at line 67 of file modelRefine.h.
ShapePairType
using ModelRefine::ShapePairType = typedef std::pair<TopoDS_Shape, TopoDS_Shape>
Definition at line 70 of file modelRefine.h.
ShapeVectorType
using ModelRefine::ShapeVectorType = typedef std::vector<TopoDS_Shape>
Definition at line 69 of file modelRefine.h.
Function Documentation
boundaryEdges()
void ModelRefine::boundaryEdges (const FaceVectorType & faces, EdgeVectorType & edgesOut)
Definition at line 85 of file modelRefine.cpp.
References getFaceEdges().
Referenced by ModelRefine::FaceTypedBase::boundarySplit(), ModelRefine::FaceTypedCylinder::boundarySplit(), and MeshPart::MeshProjection::projectOnMesh().
getBSplineObject()
FaceTypedBSpline & ModelRefine::getBSplineObject ()
Definition at line 1016 of file modelRefine.cpp.
Referenced by ModelRefine::FaceUniter::process().
getCylinderObject()
FaceTypedCylinder & ModelRefine::getCylinderObject ()
Definition at line 779 of file modelRefine.cpp.
Referenced by ModelRefine::FaceUniter::process().
getFaceEdges()
void ModelRefine::getFaceEdges (const TopoDS_Face & face, EdgeVectorType & edges)
Definition at line 78 of file modelRefine.cpp.
Referenced by boundaryEdges().
getPlaneObject()
FaceTypedPlane & ModelRefine::getPlaneObject ()
Definition at line 433 of file modelRefine.cpp.
Referenced by ModelRefine::FaceUniter::process().
removeFaces()
TopoDS_Shell ModelRefine::removeFaces (const TopoDS_Shell & shell, const FaceVectorType & faces)
Definition at line 117 of file modelRefine.cpp.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf::shell.
Referenced by ModelRefine::FaceUniter::process().