FreeCAD: FemGui::FemSettings Class Reference
FemGui::FemSettings Class Reference
#include <FemSettings.h>
Public Member Functions
FemSettings ()
void setPostAutoRecompute (bool)
bool getPostAutoRecompute () const
Detailed Description
Definition at line 52 of file FemSettings.h.
Constructor & Destructor Documentation
FemSettings()
FemSettings::FemSettings ()
Definition at line 33 of file FemSettings.cpp.
References App::GetApplication(), and App::Application::GetParameterGroupByPath().
Member Function Documentation
getPostAutoRecompute()
bool FemSettings::getPostAutoRecompute () const
Definition at line 44 of file FemSettings.cpp.
References ParameterGrp::GetBool().
Referenced by FemGui::TaskPostBox::autoApply().
setPostAutoRecompute()
void FemSettings::setPostAutoRecompute (bool on)
Definition at line 39 of file FemSettings.cpp.
References ParameterGrp::SetBool().
The documentation for this class was generated from the following files:
FemSettings.h
FemSettings.cpp