FreeCAD: Sketcher::SketchObject Class Reference
Sketcher::SketchObject Class Reference
#include <SketchObject.h>
Classes
class GeoHistory
Public Member Functions
SketchObject ()
~SketchObject () override
template<>
Base::Vector3d getPointForGeometry (const Part::GeomPoint *geomPoint, PointPos PosId)
template<>
Base::Vector3d getPointForGeometry (const Part::GeomLineSegment *lineSeg, PointPos PosId)
template<>
Base::Vector3d getPointForGeometry (const Part::GeomCircle *circle, PointPos PosId)
template<>
Base::Vector3d getPointForGeometry (const Part::GeomEllipse *ellipse, PointPos PosId)
template<>
Base::Vector3d getPointForGeometry (const Part::GeomArcOfCircle *aoc, PointPos PosId)
template<>
Base::Vector3d getPointForGeometry (const Part::GeomArcOfEllipse *aoe, PointPos PosId)
template<>
Base::Vector3d getPointForGeometry (const Part::GeomArcOfHyperbola *aoh, PointPos PosId)
template<>
Base::Vector3d getPointForGeometry (const Part::GeomArcOfParabola *aop, PointPos PosId)
template<>
Base::Vector3d getPointForGeometry (const Part::GeomBSplineCurve *bsp, PointPos PosId)
Public Member Functions inherited from Part::Part2DObject
Part2DObject ()
void transformPlacement (const Base::Placement &transform) override
transformPlacement applies transform to placement of this shape. Override this function to propagate the change of placement to base features, for example. By the time of writing this comment, the function was only called by alignment task (Edit->Alignment)
Public Member Functions inherited from Part::Feature
Feature ()
Constructor.
~Feature () override
const App::PropertyComplexGeoData * getPropertyOfGeometry () const override
TopLoc_Location getLocation () const
App::Material getMaterialAppearance () const override
Virtual function to get an App::Material object describing the appearance.
void setMaterialAppearance (const App::Material &material) override
Virtual function to set the appearance with an App::Material object.
bool getCameraAlignmentDirection (Base::Vector3d &direction, const char *subname) const override
Virtual function to get the camera alignment direction.
const std::vector< std::string > & searchElementCache (const std::string &element, Data::SearchOptions options=Data::SearchOption::CheckGeometry, double tol=1e-7, double atol=1e-10) const override
Public Member Functions inherited from App::GeoFeature
GeoFeature ()
Constructor.
~GeoFeature () override
Base::Placement globalPlacement () const
Deprecated. Calculates the placement in the global reference coordinate system.
virtual DocumentObject * getElementOwner (const Data::MappedName &) const
Return the object that owns the shape that contains the give element name.
Public Member Functions inherited from App::DocumentObject
virtual const char * getViewProviderNameOverride () const
DocumentObject ()
Constructor.
~DocumentObject () override
const char * getDagKey () const
returns a value that uniquely identifies this DocumentObject.
const char * getNameInDocument () const
returns the name which is set in the document for this object (not the name property!)
long getID () const
Return the object ID that is unique within its owner document.
std::string getExportName (bool forced=false) const
returns the name that is safe to be exported to other document
std::string getFullName () const override
Return the object full name of the form DocName::ObjName.
std::string getFullLabel () const
Return the object full label in the form DocName::ObjName.
bool isAttachedToDocument () const override
const char * detachFromDocument () override
App::Document * getDocument () const
gets the document in which this Object is handled
void touch (bool noRecompute=false)
set this document object touched (cause recomputation on dependent features)
bool isTouched () const
test if this document object is touched
void enforceRecompute ()
Enforce this document object to be recomputed.
bool mustRecompute () const
Test if this document object must be recomputed.
void purgeTouched ()
reset this document object touched
bool isError () const
set this feature to error
bool isValid () const
void purgeError ()
remove the error from the object
bool isRecomputing () const
returns true if this objects is currently recomputing
bool isRestoring () const
returns true if this objects is currently restoring from file
bool isRemoving () const
returns true if this objects is currently removed from the document
void freeze ()
set this document object freezed (prevent recomputation)
void unfreeze (bool noRecompute=false)
set this document object unfreezed (and touch it)
bool isFreezed () const
returns true if this objects is currently freezed
unsigned long getStatus () const
return the status bits
bool testStatus (ObjectStatus pos) const
void setStatus (ObjectStatus pos, bool on)
int isExporting () const
virtual int setElementVisible (const char *element, bool visible)
virtual int isElementVisible (const char *element) const
virtual bool hasChildElement () const
return true to activate tree view group object handling and element visibility
const std::vector< App::DocumentObject * > & getOutList () const
returns a list of objects this object is pointing to by Links
std::vector< App::DocumentObject * > getOutList (int option) const
void getOutList (int option, std::vector< App::DocumentObject * > &res) const
std::vector< App::DocumentObject * > getOutListOfProperty (App::Property *) const
returns a list of objects linked by the property
std::vector< App::DocumentObject * > getOutListRecursive () const
returns a list of objects this object is pointing to by Links and all further descended
void clearOutListCache () const
clear internal out list cache
std::vector< std::list< App::DocumentObject * > > getPathsByOutList (App::DocumentObject *to) const
get all possible paths from this to another object following the OutList
const std::vector< App::DocumentObject * > & getInList () const
std::vector< App::DocumentObject * > getInListRecursive () const
get all objects link directly or indirectly to this object
void getInListEx (std::set< App::DocumentObject * > &inSet, bool recursive, std::vector< App::DocumentObject * > *inList=nullptr) const
std::set< App::DocumentObject * > getInListEx (bool recursive) const
DocumentObjectGroup * getGroup () const
get group if object is part of a group, otherwise 0 is returned
bool isInInListRecursive (DocumentObject *objToTest) const
test if this object is in the InList and recursive further down
bool isInInList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the InList
bool isInOutListRecursive (DocumentObject *objToTest) const
test if the given object is in the OutList and recursive further down
bool isInOutList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the OutList
void _removeBackLink (DocumentObject *)
internal, used by PropertyLink to maintain DAG back links
void _addBackLink (DocumentObject *)
internal, used by PropertyLink to maintain DAG back links
bool testIfLinkDAGCompatible (DocumentObject *linkTo) const
testIfLinkIsDAG tests a link that is about to be created for circular references.
bool testIfLinkDAGCompatible (const std::vector< DocumentObject * > &linksTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSubList &linksTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSub &linkTo) const
virtual std::string getElementMapVersion (const App::Property *prop, bool restored=false) const
virtual bool checkElementMapVersion (const App::Property *prop, const char *ver) const
Return true to signal re-generation of geometry element names.
bool recomputeFeature (bool recursive=false)
const char * getStatusString () const
get the status Message
virtual void onLostLinkToObject (DocumentObject *)
std::vector< DocumentObject * > getSubObjectList (const char *subname, std::vector< int > *subsizes=nullptr, bool flatten=false) const
virtual std::vector< std::string > getSubObjects (int reason=0) const
std::vector< std::pair< App::DocumentObject *, std::string > > getParents (int depth=0) const
Obtain top parents and subnames of this object using its InList.
App::DocumentObject * getFirstParent () const
Obtain the first parent group of this object.
virtual DocumentObject * getLinkedObject (bool recurse=true, Base::Matrix4D *mat=nullptr, bool transform=false, int depth=0) const
virtual bool canLinkProperties () const
virtual bool isLink () const
virtual bool isLinkGroup () const
virtual bool allowDuplicateLabel () const
virtual void onBeforeChangeLabel (std::string &newLabel)
virtual void setExpression (const ObjectIdentifier &path, std::shared_ptr< App::Expression > expr)
void clearExpression (const ObjectIdentifier &path)
virtual const PropertyExpressionEngine::ExpressionInfo getExpression (const ObjectIdentifier &path) const
virtual void renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &paths)
const std::string & getOldLabel () const
const char * getViewProviderNameStored () const
bool removeDynamicProperty (const char *prop) override
App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
App::DocumentObject * resolve (const char *subname, App::DocumentObject **parent=nullptr, std::string *childName=nullptr, const char **subElement=nullptr, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
App::DocumentObject * resolveRelativeLink (std::string &subname, App::DocumentObject *&link, std::string &linkSub) const
virtual bool adjustRelativeLinks (const std::set< App::DocumentObject * > &inList, std::set< App::DocumentObject * > *visited=nullptr)
virtual int canLoadPartial () const
virtual bool redirectSubName (std::ostringstream &ss, DocumentObject *topParent, DocumentObject *child) const
Public Member Functions inherited from App::TransactionalObject
TransactionalObject ()
Constructor.
~TransactionalObject () override
Public Member Functions inherited from App::ExtensionContainer
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
Property * getPropertyByName (const char *name) const override
find a property by its name
template<typename T >
T * getPropertyByName (const char *name) const
find a property by its name, dynamic cased to specified type
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from Part::AttachExtension
AttachExtension ()
~AttachExtension () override
virtual void setAttacher (Attacher::AttachEngine *attacher, bool base=false)
setAttacher sets the AttachEngine object. The class takes the ownership of the pointer, it will be deleted when the class is destroyed, or when a new attacher is set. The default attacher is AttachEngine3D.
bool changeAttacherType (const char *typeName, bool base=false)
changeAttacherType
Attacher::AttachEngine & attacher (bool base=false) const
virtual bool positionBySupport ()
bool isAttacherActive () const
virtual bool isTouched_Mapping ()
short int extensionMustExecute () override
App::DocumentObjectExecReturn * extensionExecute () override
PyObject * getExtensionPyObject () override
void onExtendedDocumentRestored () override
get called after a document has been fully restored
Properties getProperties (bool base) const
Properties getInitedProperties (bool base)
void updateAttacherVals (bool base=false) const
void updatePropertyStatus (bool attached, bool base=false)
void updateSinglePropertyStatus (bool attached, bool base=false)
Public Member Functions inherited from App::DocumentObjectExtension
virtual Base::Type getExtensionTypeId (void) const override
DocumentObjectExtension ()
~DocumentObjectExtension () override
App::DocumentObject * getExtendedObject ()
const App::DocumentObject * getExtendedObject () const
virtual void onExtendedSettingDocument ()
get called after setting the document
virtual void onExtendedSetupObject ()
get called after a brand new object was created
virtual void onExtendedUnsetupObject ()
get called when object is going to be removed from the document
virtual const char * getViewProviderExtensionName () const
virtual bool extensionGetSubObject (DocumentObject *&ret, const char *subname, PyObject **pyObj, Base::Matrix4D *mat, bool transform, int depth) const
virtual bool extensionGetSubObjects (std::vector< std::string > &ret, int reason) const
virtual bool extensionGetLinkedObject (DocumentObject *&ret, bool recursive, Base::Matrix4D *mat, bool transform, int depth) const
virtual int extensionSetElementVisible (const char *, bool)
virtual int extensionIsElementVisible (const char *)
virtual bool extensionHasChildElement () const
Public Member Functions inherited from App::Extension
Extension ()=default
virtual ~Extension ()
virtual void initExtension (App::ExtensionContainer *obj)
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Public Attributes
Part ::PropertyGeometryList Geometry
Property.
Sketcher::PropertyConstraintList Constraints
App ::PropertyLinkSubList ExternalGeometry
App::PropertyIntegerList ExternalTypes
App ::PropertyLinkListHidden Exports
Part ::PropertyGeometryList ExternalGeo
App ::PropertyBool FullyConstrained
App ::PropertyPrecision ArcFitTolerance
Part ::PropertyPartShape InternalShape
App ::PropertyPrecision InternalTolerance
App ::PropertyBool MakeInternals
Public Attributes inherited from Part::Feature
PropertyPartShape Shape
Materials::PropertyMaterial ShapeMaterial
Public Attributes inherited from App::GeoFeature
PropertyPlacement Placement
Public Attributes inherited from App::DocumentObject
PropertyString Label
PropertyString Label2
PropertyExpressionEngine ExpressionEngine
PropertyBool Visibility
Allow control visibility status in App name space.
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalBeforeChange
signal before changing a property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalChanged
signal on changed property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalEarlyChanged
signal on changed property of this object before document scoped signalChangedObject
Public Attributes inherited from Part::AttachExtension
App::PropertyString AttacherType
App::PropertyEnumeration AttacherEngine
App::PropertyLinkSubList AttachmentSupport
App::PropertyEnumeration MapMode
App::PropertyBool MapReversed
App::PropertyPlacement AttachmentOffset
App::PropertyFloat MapPathParameter
MapPathParameter is a parameter value for mmNormalToPath (the sketch will be mapped normal to a curve at point specified by parameter (from 0.0 to 1.0, from start to end))
methods override Feature
enum eReasonList {
rlAllowed, rlOtherDoc, rlCircularReference, rlOtherPart,
rlOtherBody, rlOtherBodyWithLinks, rlNotASketch, rlNonParallel,
rlAxesMisaligned, rlOriginsMisaligned
}
bool noRecomputes
boost::signals2::signal< void()> signalSolverUpdate
boost::signals2::signal< void()> signalElementsChanged
short mustExecute () const override
App::DocumentObjectExecReturn * execute () override
const char * getViewProviderName () const override
returns the type name of the ViewProvider
void setupObject () override
get called after a brand new object was created
bool isSupportedGeometry (const Part::Geometry *geo) const
Returns true if the sketcher supports the given geometry.
int addGeometry (const Part::Geometry *geo, bool construction=false)
Add geometry to a sketch - It adds a copy with a different uuid (internally uses copy() instead of clone())
int addGeometry (std::unique_ptr< Part::Geometry > newgeo, bool construction=false)
Add geometry to a sketch using up the provided newgeo. Caveat: It will use the provided newgeo with the uuid it has. This is different from the addGeometry method with a naked pointer, where a different uuid is ensured. The caller is responsible for provided a new or existing uuid, as necessary.
int addGeometry (const std::vector< Part::Geometry * > &geoList, bool construction=false)
Add multiple geometry elements to a sketch.
int delGeometry (int GeoId, bool deleteinternalgeo=true)
Deletes indicated geometry (by geoid).
int delGeometriesExclusiveList (const std::vector< int > &GeoIds)
Deletes just the GeoIds indicated, it does not look for internal geometry.
int delGeometries (const std::vector< int > &GeoIds)
Does the same as delGeometry but allows one to delete several geometries in one step.
int deleteAllGeometry ()
deletes all the elements/constraints of the sketch except for external geometry
int deleteAllConstraints ()
deletes all the constraints of the sketch
int addConstraints (const std::vector< Constraint * > &ConstraintList)
add all constraints in the list
int addCopyOfConstraints (const SketchObject &orig)
Copy the constraints instead of cloning them and copying the expressions if any.
int addConstraint (const Constraint *constraint)
add constraint
int addConstraint (std::unique_ptr< Constraint > constraint)
add constraint
int delConstraint (int ConstrId)
delete constraint
int delConstraints (std::vector< int > ConstrIds, bool updategeometry=true)
int delConstraintOnPoint (int GeoId, PointPos PosId, bool onlyCoincident=true)
int delConstraintOnPoint (int VertexId, bool onlyCoincident=true)
int delConstraintsToExternal ()
Deletes all constraints referencing an external geometry.
int transferConstraints (int fromGeoId, PointPos fromPosId, int toGeoId, PointPos toPosId, bool doNotTransformTangencies=false)
transfers all constraints of a point to a new point
int carbonCopy (App::DocumentObject *pObj, bool construction=true)
Carbon copy another sketch geometry and constraints.
int addExternal (App::DocumentObject *Obj, const char *SubName, bool defining=false, bool intersection=false)
add an external geometry reference
int delExternal (int ExtGeoId)
int delExternal (const std::vector< int > &ExtGeoIds)
int attachExternal (const std::vector< int > &geoIds, App::DocumentObject *Obj, const char *SubName)
attach a link reference to an external geometry
int detachExternal (const std::vector< int > &geoIds)
int delAllExternal ()
const Part::Geometry * _getGeometry (int GeoId) const
int setGeometry (int GeoId, const Part::Geometry *)
std::vector< int > getRelatedGeometry (int GeoId) const
returns GeoId of all geometries projected from the same external geometry reference
int syncGeometry (const std::vector< int > &geoIds)
Sync frozen external geometries.
template<typename returnType >
returnType performActionByGeomType (const Part::Geometry *geo)
template<typename GeometryT = Part::Geometry, typename = typename std::enable_if< std::is_base_of<Part::Geometry, typename std::decay<GeometryT>::type>::value>::type>
const GeometryT * getGeometry (int GeoId) const
std::unique_ptr< const GeometryFacade > getGeometryFacade (int GeoId) const
const std::vector< Part::Geometry * > & getInternalGeometry () const
returns a list of all internal geometries
const std::vector< Part::Geometry * > & getExternalGeometry () const
returns a list of projected external geometries
void rebuildExternalGeometry (std::optional< ExternalToAdd > extToAdd=std::nullopt)
rebuilds external geometry (projection onto the sketch plane)
int getExternalGeometryCount () const
returns the number of external Geometry entities
void fixExternalGeometry (const std::vector< int > &geoIds={})
auto fix external geometry references
std::vector< Part::Geometry * > getCompleteGeometry () const
retrieves a vector containing both normal and external Geometry (including the sketch axes)
GeoListFacade getGeoListFacade () const
int getCompleteGeometryIndex (int GeoId) const
converts a GeoId index into an index of the CompleteGeometry vector
int getGeoIdFromCompleteGeometryIndex (int completeGeometryIndex) const
int hasConflicts () const
returns non zero if the sketch contains conflicting constraints
int setUpSketch ()
int diagnoseAdditionalConstraints (std::vector< Sketcher::Constraint * > additionalconstraints)
int solve (bool updateGeoAfterSolving=true)
int setDatum (int ConstrId, double Datum)
set the datum of a Distance or Angle constraint and solve
int setDriving (int ConstrId, bool isdriving)
set the driving status of this constraint and solve
int getDriving (int ConstrId, bool &isdriving)
get the driving status of this constraint
int toggleDriving (int ConstrId)
toggle the driving status of this constraint
int setActive (int ConstrId, bool isactive)
set the driving status of this constraint and solve
int getActive (int ConstrId, bool &isactive)
get the driving status of this constraint
int toggleActive (int ConstrId)
toggle the driving status of this constraint
int setLabelPosition (int ConstrId, float value)
set the label position of the constraint
int getLabelPosition (int ConstrId, float &value)
get the label position of the constraint
int setLabelDistance (int ConstrId, float value)
set the label distance of the constraint
int getLabelDistance (int ConstrId, float &value)
get the label distance of the constraint
int setDatumsDriving (bool isdriving)
Make all dimensionals Driving/non-Driving.
int moveDatumsToEnd ()
Move Dimensional constraints at the end of the properties array.
void reverseAngleConstraintToSupplementary (Constraint *constr, int constNum)
Change an angle constraint to its supplementary angle.
void inverseAngleConstraint (Constraint *constr)
bool constraintHasExpression (int constNum) const
std::string getConstraintExpression (int constNum) const
void setConstraintExpression (int constNum, const std::string &newExpression)
void setExpression (const App::ObjectIdentifier &path, std::shared_ptr< App::Expression > expr) override
int setVirtualSpace (int ConstrId, bool isinvirtualspace)
set the driving status of this constraint and solve
int setVirtualSpace (std::vector< int > constrIds, bool isinvirtualspace)
set the driving status of a group of constraints at once
int getVirtualSpace (int ConstrId, bool &isinvirtualspace) const
get the driving status of this constraint
int toggleVirtualSpace (int ConstrId)
toggle the driving status of this constraint
int moveGeometries (std::vector< GeoElementId > geoEltIds, const Base::Vector3d &toPoint, bool relative=false, bool updateGeoBeforeMoving=false)
move this point to a new location and solve
int moveGeometry (int GeoId, PointPos PosId, const Base::Vector3d &toPoint, bool relative=false, bool updateGeoBeforeMoving=false)
Base::Vector3d getPoint (int GeoId, PointPos PosId) const
int toggleConstruction (int GeoId)
toggle geometry to draft line
int setConstruction (int GeoId, bool on)
int fillet (int geoId, PointPos pos, double radius, bool trim=true, bool preserveCorner=false, bool chamfer=false)
Create a sketch fillet from the point at the intersection of two lines.
int fillet (int geoId1, int geoId2, const Base::Vector3d &refPnt1, const Base::Vector3d &refPnt2, double radius, bool trim=true, bool createCorner=false, bool chamfer=false)
More general form of fillet.
int trim (int geoId, const Base::Vector3d &point)
trim a curve
int extend (int geoId, double increment, PointPos endPoint)
extend a curve
bool deriveConstraintsForPieces (const int oldId, const std::vector< int > &newIds, const Constraint *con, std::vector< Constraint * > &newConstraints)
bool deriveConstraintsForPieces (const int oldId, const std::vector< int > &newIds, const std::vector< const Part::Geometry * > &newGeo, const Constraint *con, std::vector< Constraint * > &newConstraints)
int split (int geoId, const Base::Vector3d &point)
split a curve
int join (int geoId1, Sketcher::PointPos posId1, int geoId2, Sketcher::PointPos posId2, int continuity=0)
Join one or two curves at the given end points.
int addSymmetric (const std::vector< int > &geoIdList, int refGeoId, Sketcher::PointPos refPosId=Sketcher::PointPos::none, bool addSymmetryConstraints=false)
adds symmetric geometric elements with respect to the refGeoId (line or point)
std::vector< Part::Geometry * > getSymmetric (const std::vector< int > &geoIdList, std::map< int, int > &geoIdMap, std::map< int, bool > &isStartEndInverted, int refGeoId, Sketcher::PointPos refPosId=Sketcher::PointPos::none)
int addCopy (const std::vector< int > &geoIdList, const Base::Vector3d &displacement, bool moveonly=false, bool clone=false, int csize=2, int rsize=1, bool constraindisplacement=false, double perpscale=1.0)
int removeAxesAlignment (const std::vector< int > &geoIdList)
int exposeInternalGeometry (int GeoId)
Exposes all internal geometry of an object supporting internal geometry.
int deleteUnusedInternalGeometry (int GeoId, bool delgeoid=false)
Deletes all unused (not further constrained) internal geometry.
int deleteUnusedInternalGeometryAndUpdateGeoId (int &GeoId, bool delgeoid=false)
Same as deleteUnusedInternalGeometry, but changes GeoId to the new Id of the geometry, or to GeoEnum::GeoUndef if the geometry is deleted as well.
bool convertToNURBS (int GeoId)
Approximates the given geometry with a B-spline.
bool increaseBSplineDegree (int GeoId, int degreeincrement=1)
Increases the degree of a BSpline by degreeincrement, which defaults to 1.
bool decreaseBSplineDegree (int GeoId, int degreedecrement=1)
Decreases the degree of a BSpline by degreedecrement, which defaults to 1.
bool modifyBSplineKnotMultiplicity (int GeoId, int knotIndex, int multiplicityincr=1)
Increases or Decreases the multiplicity of a BSpline knot by the multiplicityincr param, which defaults to 1, if the result is multiplicity zero, the knot is removed.
bool insertBSplineKnot (int GeoId, double param, int multiplicity=1)
Inserts a knot in the BSpline at param with given multiplicity. If the knot already exists, its multiplicity is increased by multiplicity.
void getGeoVertexIndex (int VertexId, int &GeoId, PointPos &PosId) const
retrieves for a Vertex number the corresponding GeoId and PosId
int getHighestVertexIndex () const
int getHighestCurveIndex () const
void rebuildVertexIndex ()
int getVertexIndexGeoPos (int GeoId, PointPos PosId) const
retrieves for a GeoId and PosId the Vertex number
const std::vector< std::map< int, Sketcher::PointPos > > getCoincidenceGroups ()
void isCoincidentWithExternalGeometry (int GeoId, bool &start_external, bool &mid_external, bool &end_external)
const std::map< int, Sketcher::PointPos > getAllCoincidentPoints (int GeoId, PointPos PosId)
void getDirectlyCoincidentPoints (int GeoId, PointPos PosId, std::vector< int > &GeoIdList, std::vector< PointPos > &PosIdList)
void getDirectlyCoincidentPoints (int VertexId, std::vector< int > &GeoIdList, std::vector< PointPos > &PosIdList)
bool arePointsCoincident (int GeoId1, PointPos PosId1, int GeoId2, PointPos PosId2)
void getConstraintIndices (int GeoId, std::vector< int > &constraintList)
returns a list of indices of all constraints involving given GeoId
double calculateAngleViaPoint (int geoId1, int geoId2, double px, double py)
bool isPointOnCurve (int geoIdCurve, double px, double py)
double calculateConstraintError (int ConstrId)
int changeConstraintsLocking (bool bLock)
int port_reversedExternalArcs (bool justAnalyze)
porting functions
PyObject * getPyObject () override
getPyObject returns the Python binding object
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, App::Property *prop) override
int getAxisCount () const override
returns the number of construction lines (to be used as axes)
Base::Axis getAxis (int axId) const override
void acceptGeometry () override
verify and accept the assigned geometry
bool evaluateConstraint (const Constraint *constraint) const
Check if constraint has invalid indexes.
bool evaluateConstraints () const
Check for constraints with invalid indexes.
void validateConstraints ()
Remove constraints with invalid indexes.
bool evaluateSupport ()
Checks if support is valid.
void validateExternalLinks ()
validate External Links (remove invalid external links)
int getLastDoF () const
gets DoF of last solver execution
bool getLastHasConflicts () const
gets HasConflicts status of last solver execution
bool getLastHasRedundancies () const
gets HasRedundancies status of last solver execution
bool getLastHasPartialRedundancies () const
gets HasRedundancies status of last solver execution
bool getLastHasMalformedConstraints () const
gets HasMalformedConstraints status of last solver execution
int getLastSolverStatus () const
gets solver status of last solver execution
float getLastSolveTime () const
gets solver SolveTime of last solver execution
const std::vector< int > & getLastConflicting () const
gets the conflicting constraints of the last solver execution
const std::vector< int > & getLastRedundant () const
gets the redundant constraints of last solver execution
const std::vector< int > & getLastPartiallyRedundant () const
gets the redundant constraints of last solver execution
const std::vector< int > & getLastMalformedConstraints () const
gets the redundant constraints of last solver execution
const Sketch & getSolvedSketch () const
gets the solved sketch as a reference
void setRecalculateInitialSolutionWhileMovingPoint (bool recalculateInitialSolutionWhileMovingPoint)
int initTemporaryMove (std::vector< GeoElementId > moved, bool fine=true)
int initTemporaryMove (int geoId, PointPos pos, bool fine=true)
int initTemporaryBSplinePieceMove (int geoId, PointPos pos, const Base::Vector3d &firstPoint, bool fine=true)
int moveGeometriesTemporary (std::vector< GeoElementId > moved, Base::Vector3d toPoint, bool relative=false)
int moveGeometryTemporary (int geoId, PointPos pos, Base::Vector3d toPoint, bool relative=false)
void updateSolverExtension (int geoId, std::unique_ptr< Part::GeometryExtension > &&ext)
forwards a request to update an extension of a geometry of the solver to the solver.
void getGeometryWithDependentParameters (std::vector< std::pair< int, PointPos >> &geometrymap)
bool isAllowedOtherBody () const
Flag to allow external geometry from other bodies than the one this sketch belongs to.
void setAllowOtherBody (bool on)
bool isAllowedUnaligned () const
Flag to allow carbon copy from misaligned geometry.
void setAllowUnaligned (bool on)
bool isExternalAllowed (App::Document *pDoc, App::DocumentObject *pObj, eReasonList *rsn=nullptr) const
bool isCarbonCopyAllowed (App::Document *pDoc, App::DocumentObject *pObj, bool &xinv, bool &yinv, eReasonList *rsn=nullptr) const
DocumentObject * getSubObject (const char *subname, PyObject **pyObj=0, Base::Matrix4D *mat=0, bool transform=true, int depth=0) const override
Part::TopoShape getEdge (const Part::Geometry *geo, const char *name) const
std::vector< const char * > getElementTypes (bool all=true) const override
std::vector< Data::IndexedName > getHigherElements (const char *element, bool silent=false) const override
Return the higher level element names of the given element.
Data::IndexedName checkSubName (const char *subname) const
bool geoIdFromShapeType (const Data::IndexedName &, int &geoId, PointPos &posId) const
bool geoIdFromShapeType (const char *shapetype, int &geoId, PointPos &posId) const
bool geoIdFromShapeType (const char *shapetype, int &geoId) const
std::string getGeometryReference (int GeoId) const
Return a human friendly element reference of an external geometry.
std::string convertSubName (const char *subname, bool postfix=true) const
std::string convertSubName (const std::string &subname, bool postfix=true) const
std::string convertSubName (const Data::IndexedName &, bool postfix=true) const
Data::IndexedName shapeTypeFromGeoId (int GeoId, PointPos pos=Sketcher::PointPos::none) const
App::ElementNamePair getElementName (const char *name, ElementNameType type) const override
bool isPerformingInternalTransaction () const
bool seekTrimPoints (int GeoId, const Base::Vector3d &point, int &GeoId1, Base::Vector3d &intersect1, int &GeoId2, Base::Vector3d &intersect2)
int autoConstraint (double precision=Precision::Confusion() *1000, double angleprecision=M_PI/20, bool includeconstruction=true)
int detectMissingPointOnPointConstraints (double precision=Precision::Confusion() *1000, bool includeconstruction=true)
void analyseMissingPointOnPointCoincident (double angleprecision=M_PI/8)
int detectMissingVerticalHorizontalConstraints (double angleprecision=M_PI/8)
int detectMissingEqualityConstraints (double precision)
std::vector< ConstraintIds > & getMissingPointOnPointConstraints ()
std::vector< ConstraintIds > & getMissingVerticalHorizontalConstraints ()
std::vector< ConstraintIds > & getMissingLineEqualityConstraints ()
std::vector< ConstraintIds > & getMissingRadiusConstraints ()
void setMissingRadiusConstraints (std::vector< ConstraintIds > &cl)
void setMissingLineEqualityConstraints (std::vector< ConstraintIds > &cl)
void setMissingVerticalHorizontalConstraints (std::vector< ConstraintIds > &cl)
void setMissingPointOnPointConstraints (std::vector< ConstraintIds > &cl)
void makeMissingPointOnPointCoincident (bool onebyone=false)
void makeMissingVerticalHorizontal (bool onebyone=false)
void makeMissingEquality (bool onebyone=true)
int detectDegeneratedGeometries (double tolerance)
Detect degenerated geometries.
int removeDegeneratedGeometries (double tolerance)
Remove degenerated geometries.
int autoRemoveRedundants (bool updategeo=true)
returns the number of redundant constraints detected
int renameConstraint (int GeoId, std::string name)
std::vector< Base::Vector3d > getOpenVertices () const
Part::TopoShape buildInternals (const Part::TopoShape &edges) const
const std::map< std::string, std::string > getInternalElementMap () const
Get a map from internal element to the same geometry in normal shape.
int setGeometryId (int GeoId, long id)
int getGeometryId (int GeoId, long &id) const
static std::string reverseAngleConstraintExpression (std::string expression)
Modify an angle constraint expression string to its supplementary angle.
static Base::Vector3d getPoint (const Part::Geometry *geo, PointPos PosId)
retrieves the coordinates of a point
template<class geomType >
static Base::Vector3d getPointForGeometry (const geomType *geo, PointPos PosId)
static bool isClosedCurve (const Part::Geometry *geo)
static bool hasInternalGeometry (const Part::Geometry *geo)
static void appendConflictMsg (const std::vector< int > &conflicting, std::string &msg)
generates a warning message about constraint conflicts and appends it to the given message
static void appendRedundantMsg (const std::vector< int > &redundant, std::string &msg)
generates a warning message about redundant constraints and appends it to the given message
static void appendMalformedConstraintsMsg (const std::vector< int > &malformed, std::string &msg)
generates a warning message about malformed constraints and appends it to the given message
static const std::string & internalPrefix ()
static const char * convertInternalName (const char *name)
int toggleExternalGeometryFlag (const std::vector< int > &geoIds, const std::vector< ExternalGeometryExtension::Flag > &flags)
void buildShape ()
void onChanged (const App::Property *) override
get called by the container when a property has changed
void onDocumentRestored () override
get called after a document has been fully restored
void restoreFinished () override
std::string validateExpression (const App::ObjectIdentifier &path, std::shared_ptr< const App::Expression > expr)
void constraintsRenamed (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &renamed)
void constraintsRemoved (const std::set< App::ObjectIdentifier > &removed)
std::vector< Part::Geometry * > supportedGeometry (const std::vector< Part::Geometry * > &geoList) const
Returns a list of supported geometries from the input list.
void updateGeoHistory ()
void generateId (const Part::Geometry *geo)
void transferFilletConstraints (int geoId1, PointPos posId1, int geoId2, PointPos posId2)
Transfer constraints on lines being filleted.
int testDrivingChange (int ConstrId, bool isdriving)
void initExternalGeo ()
void onUpdateElementReference (const App::Property *) override
void delExternalPrivate (const std::set< long > &ids, bool removeReference)
void updateGeometryRefs ()
void onUndoRedoFinished () override
get called after an undo/redo transaction is finished
void migrateSketch ()
void retrieveSolverDiagnostics ()
bool getBlockedState (const Constraint *cstr, bool &blockedstate) const
bool getInternalTypeState (const Constraint *cstr, Sketcher::InternalType::InternalType &internaltypestate) const
void synchroniseGeometryState ()
void addConstraint (Sketcher::ConstraintType constrType, int firstGeoId, Sketcher::PointPos firstPos, int secondGeoId=GeoEnum::GeoUndef, Sketcher::PointPos secondPos=Sketcher::PointPos::none, int thirdGeoId=GeoEnum::GeoUndef, Sketcher::PointPos thirdPos=Sketcher::PointPos::none)
std::unique_ptr< Constraint > createConstraint (Sketcher::ConstraintType constrType, int firstGeoId, Sketcher::PointPos firstPos, int secondGeoId=GeoEnum::GeoUndef, Sketcher::PointPos secondPos=Sketcher::PointPos::none, int thirdGeoId=GeoEnum::GeoUndef, Sketcher::PointPos thirdPos=Sketcher::PointPos::none)
std::unique_ptr< Constraint > getConstraintAfterDeletingGeo (const Constraint *constr, const int deletedGeoId) const
void changeConstraintAfterDeletingGeo (Constraint *constr, const int deletedGeoId) const
static void appendConstraintsMsg (const std::vector< int > &vector, const std::string &singularmsg, const std::string &pluralmsg, std::string &msg)
Additional Inherited Members
Public Types inherited from App::GeoFeature
enum ElementNameType { Normal = 0, Import = 1, Export = 2 }
Specify the type of element name to return when calling getElementName()
Public Types inherited from App::DocumentObject
enum OutListOption { OutListNoExpression = 1, OutListNoHidden = 2, OutListNoXLinked = 4 }
OutList options.
enum GSReason { GS_DEFAULT, GS_SELECT }
reason of calling getSubObjects()
Public Types inherited from App::ExtensionContainer
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Static Public Member Functions inherited from Part::Part2DObject
static bool seekTrimPoints (const std::vector< Geometry * > &geomlist, int geometryIndex, const Base::Vector3d &point, int &geometryIndex1, Base::Vector3d &intersect1, int &geometryIndex2, Base::Vector3d &intersect2)
Static Public Member Functions inherited from Part::Feature
static std::list< Data::HistoryItem > getElementHistory (App::DocumentObject *obj, const char *name, bool recursive=true, bool sameType=false)
static QVector< Data::MappedElement > getRelatedElements (App::DocumentObject *obj, const char *name, HistoryTraceType sameType=HistoryTraceType::followTypeChange, bool withCache=true)
static QVector< Data::MappedElement > getElementFromSource (App::DocumentObject *obj, const char *subname, App::DocumentObject *src, const char *srcSub, bool single=false)
static TopoDS_Shape getShape (const App::DocumentObject *obj, const char *subname=nullptr, bool needSubElement=false, Base::Matrix4D *pmat=nullptr, App::DocumentObject **owner=nullptr, bool resolveLink=true, bool transform=true)
static TopoShape getTopoShape (const App::DocumentObject *obj, const char *subname=nullptr, bool needSubElement=false, Base::Matrix4D *pmat=nullptr, App::DocumentObject **owner=nullptr, bool resolveLink=true, bool transform=true, bool noElementMap=false)
static void clearShapeCache ()
static App::DocumentObject * getShapeOwner (const App::DocumentObject *obj, const char *subname=nullptr)
static bool hasShapeOwner (const App::DocumentObject *obj, const char *subname=nullptr)
static Feature * create (const TopoShape &shape, const char *name=nullptr, App::Document *document=nullptr)
static bool isElementMappingDisabled (App::PropertyContainer *container)
static void guessNewLink (std::string &replacementName, DocumentObject *base, const char *oldLink)
Static Public Member Functions inherited from App::GeoFeature
static DocumentObject * resolveElement (const App::DocumentObject *obj, const char *subname, ElementNamePair &elementName, bool append=false, ElementNameType type=Normal, const DocumentObject *filter=nullptr, const char **element=nullptr, GeoFeature **geo=nullptr)
static bool hasMissingElement (const char *subname)
static Base::Placement getPlacementFromProp (DocumentObject *obj, const char *propName)
static Base::Placement getGlobalPlacement (DocumentObject *targetObj, DocumentObject *rootObj, const std::string &sub)
static Base::Placement getGlobalPlacement (DocumentObject *targetObj, PropertyXLinkSub *prop)
static Base::Placement getGlobalPlacement (const DocumentObject *obj)
Static Public Member Functions inherited from App::DocumentObject
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
Check if the subname reference ends with hidden marker.
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Member Functions inherited from App::DocumentObjectExtension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Static Public Member Functions inherited from App::Extension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Static Public Attributes inherited from Part::Part2DObject
static const int H_Axis = -1
static const int V_Axis = -2
static const int N_Axis = -3
Static Public Attributes inherited from App::DocumentObject
static DocumentObjectExecReturn * StdReturn
Protected Member Functions inherited from Part::Feature
App::DocumentObjectExecReturn * recompute () override
recompute only this object
void onBeforeChange (const App::Property *prop) override
get called before the value is changed
void copyMaterial (Feature *feature)
void copyMaterial (App::DocumentObject *link)
void registerElementCache (const std::string &prefix, PropertyPartShape *prop)
App::ElementNamePair getExportElementName (TopoShape shape, const char *name) const
ShapeHistory buildHistory (BRepBuilderAPI_MakeShape &, TopAbs_ShapeEnum type, const TopoDS_Shape &newS, const TopoDS_Shape &oldS)
ShapeHistory joinHistory (const ShapeHistory &, const ShapeHistory &)
Protected Member Functions inherited from App::GeoFeature
void updateElementReference ()
ElementNamePair _getElementName (const char *name, const Data::MappedElement &mapped) const
Protected Member Functions inherited from App::DocumentObject
App::DocumentObjectExecReturn * executeExtensions ()
void setError ()
void resetError ()
void setDocument (App::Document *doc)
void onEarlyChange (const Property *prop) override
get called by the container when a property was changed
virtual void onSettingDocument ()
get called after setting the document
virtual void unsetupObject ()
get called when object is going to be removed from the document
void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus) override
get called when a property status has changed
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData () const
Protected Member Functions inherited from Part::AttachExtension
void extensionOnChanged (const App::Property *) override
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
returns true if the property name change was handled by the extension.
App::PropertyPlacement & getPlacement () const
void initBase (bool force)
Protected Member Functions inherited from App::DocumentObjectExtension
virtual const App::PropertyData & extensionGetPropertyData (void) const override
Protected Member Functions inherited from App::Extension
virtual bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
returns true if the property type change was handled by the extension.
void initExtensionType (Base::Type type)
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Static Protected Member Functions inherited from App::DocumentObjectExtension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
Static Protected Member Functions inherited from App::Extension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::DocumentObject
std::bitset< 32 > StatusBits
Py::SmartPtr PythonObject
python object of this class and all descendent
App::Document * _pDoc {nullptr}
pointer to the document this object belongs to
std::string oldLabel
Old label; used for renaming expressions.
const std::string * pcNameInDocument {nullptr}
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Detailed Description
Definition at line 83 of file SketchObject.h.
Member Enumeration Documentation
eReasonList
enum Sketcher::SketchObject::eReasonList
Enumerator
rlAllowed
rlOtherDoc
rlCircularReference
rlOtherPart
rlOtherBody
rlOtherBodyWithLinks
rlNotASketch
rlNonParallel
rlAxesMisaligned
rlOriginsMisaligned
Definition at line 765 of file SketchObject.h.
Constructor & Destructor Documentation
SketchObject()
SketchObject::SketchObject ()
Definition at line 130 of file SketchObject.cpp.
References ADD_PROPERTY, ADD_PROPERTY_TYPE, draftgeoutils.faces::bind(), SketcherExample::Constraints, constraintsRemoved(), constraintsRenamed(), SketcherExample::Geometry, App::Prop_Hidden, App::Prop_None, App::Prop_Output, App::Prop_ReadOnly, and validateExpression().
~SketchObject()
SketchObject::~SketchObject () override
Definition at line 214 of file SketchObject.cpp.
Member Function Documentation
_getGeometry()
const Part::Geometry * SketchObject::_getGeometry (int GeoId) const
Definition at line 8050 of file SketchObject.cpp.
acceptGeometry()
void SketchObject::acceptGeometry () override virtual
verify and accept the assigned geometry
Reimplemented from Part::Part2DObject.
Definition at line 1611 of file SketchObject.cpp.
References SketcherExample::Constraints.
addConstraint() [1/3]
int SketchObject::addConstraint (const Constraint * constraint)
add constraint
Definition at line 2215 of file SketchObject.cpp.
References Sketcher::Constraint::clone(), and Path.Post.scripts.opensbp_post::move().
addConstraint() [2/3]
void SketchObject::addConstraint (Sketcher::ConstraintType constrType, int firstGeoId, Sketcher::PointPos firstPos, int secondGeoId = GeoEnum::GeoUndef, Sketcher::PointPos secondPos = Sketcher::PointPos::none, int thirdGeoId = GeoEnum::GeoUndef, Sketcher::PointPos thirdPos = Sketcher::PointPos::none) protected
Definition at line 3431 of file SketchObject.cpp.
References Path.Post.scripts.opensbp_post::move().
addConstraint() [3/3]
int SketchObject::addConstraint (std::unique_ptr< Constraint > constraint)
add constraint
Definition at line 2222 of file SketchObject.cpp.
References SketcherExample::Constraints, Path.Post.scripts.opensbp_post::move(), Sketcher::Perpendicular, Sketcher::Tangent, and Sketcher::Constraint::Type.
addConstraints()
int SketchObject::addConstraints (const std::vector< Constraint * > & ConstraintList)
add all constraints in the list
Definition at line 2147 of file SketchObject.cpp.
References Sketcher::Constraint::clone(), SketcherExample::Constraints, SplineSurface::i, Path.Post.scripts.opensbp_post::move(), Sketcher::Perpendicular, Sketcher::Tangent, and Sketcher::Constraint::Type.
addCopy()
int SketchObject::addCopy (const std::vector< int > & geoIdList, const Base::Vector3d & displacement, bool moveonly = false, bool clone = false, int csize = 2, int rsize = 1, bool constraindisplacement = false, double perpscale = 1.0)
with default parameters adds a copy of the geometric elements displaced by the displacement vector. It creates an array of csize elements in the direction of the displacement vector by rsize elements in the direction perpendicular to the displacement vector, wherein the modulus of this perpendicular vector is scaled by perpscale.
Definition at line 5298 of file SketchObject.cpp.
References Sketcher::Angle, KDL::atan2(), SCL.SimpleDataTypes::c, Sketcher::Coincident, Base::Console(), SketcherExample::Constraints, Part::Geometry::copy(), Sketcher::Constraint::copy(), Sketcher::Diameter, Sketcher::Distance, Sketcher::DistanceX, Sketcher::DistanceY, Sketcher::end, Sketcher::Equal, Base::ConsoleSingleton::Error(), DraftVecUtils::find(), Sketcher::Constraint::First, Sketcher::Constraint::FirstPos, SketcherExample::Geometry, Sketcher::GeoUndef, Part::GeomConic::getCenter(), Part::GeomArcOfConic::getCenter(), Part::GeomLineSegment::getEndPoint(), Sketcher::GeometryFacade::getFacade(), Part::GeomPoint::getPoint(), draftguitools.gui_tool_utils::getPoint, Part::GeomBSplineCurve::getPoles(), Part::GeomBoundedCurve::getStartPoint(), Part::GeomArcOfConic::getStartPoint(), Part::GeomLineSegment::getStartPoint(), SplineSurface::i, Sketcher::InternalAlignment, Base::BaseClass::is(), Sketcher::Constraint::isDriving, Base::Vector3< float_type >::Length(), Sketcher::mid, Path.Post.scripts.opensbp_post::move(), Sketcher::none, Sketcher::Parallel, Sketcher::Perpendicular, Sketcher::Radius, SCL.BaseType::scp, Sketcher::Constraint::Second, Sketcher::Constraint::SecondPos, Part::GeomConic::setCenter(), Part::GeomArcOfConic::setCenter(), Sketcher::GeometryFacade::setConstruction(), Part::GeomPoint::setPoint(), Part::GeomLineSegment::setPoints(), Part::GeomBSplineCurve::setPoles(), Sketcher::Constraint::setValue(), Sketcher::start, Sketcher::Constraint::Third, THROWM, Sketcher::Constraint::Type, Sketcher::Weight, MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, and Base::Vector3< float_type >::y.
addCopyOfConstraints()
int SketchObject::addCopyOfConstraints (const SketchObject & orig)
Copy the constraints instead of cloning them and copying the expressions if any.
Definition at line 2172 of file SketchObject.cpp.
References SketcherExample::Constraints, Constraints, Sketcher::PropertyConstraintList::createPath(), App::PropertyExpressionEngine::ExpressionInfo::expression, App::DocumentObject::getExpression(), Sketcher::PropertyConstraintList::getValues(), SplineSurface::i, Path.Post.scripts.opensbp_post::move(), and TestSpreadsheet::v.
addExternal()
int SketchObject::addExternal (App::DocumentObject * Obj, const char * SubName, bool defining = false, bool intersection = false)
add an external geometry reference
Definition at line 7594 of file SketchObject.cpp.
References Sketcher::Both, Base::Console(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), create_qrc::ext, App::DocumentObject::getDocument(), Base::Placement::getPosition(), Base::Placement::getRotation(), Part::Feature::getTopoShape(), SplineSurface::i, Sketcher::Intersection, intersection(), Base::Rotation::multVec(), Sketcher::Projection, Part::TopoShape::shapeName(), Path.Base.Gui.PropertyEditor::Types(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
addGeometry() [1/3]
int SketchObject::addGeometry (const Part::Geometry * geo, bool construction = false)
Add geometry to a sketch - It adds a copy with a different uuid (internally uses copy() instead of clone())
Parameters
geo - geometry to add
construction - true for construction lines
Return values
int - GeoId of added element
Definition at line 1685 of file SketchObject.cpp.
References Part::Geometry::copy(), and Path.Post.scripts.opensbp_post::move().
addGeometry() [2/3]
int SketchObject::addGeometry (const std::vector< Part::Geometry * > & geoList, bool construction = false)
Add multiple geometry elements to a sketch.
Parameters
geoList - geometry to add
construction - true for construction lines
Return values
int - GeoId of last added element
Definition at line 1657 of file SketchObject.cpp.
References Drawing::copy(), SketcherExample::Geometry, Path.Post.scripts.opensbp_post::move(), Sketcher::GeometryFacade::setConstruction(), and TestSpreadsheet::v.
addGeometry() [3/3]
int SketchObject::addGeometry (std::unique_ptr< Part::Geometry > newgeo, bool construction = false)
Add geometry to a sketch using up the provided newgeo. Caveat: It will use the provided newgeo with the uuid it has. This is different from the addGeometry method with a naked pointer, where a different uuid is ensured. The caller is responsible for provided a new or existing uuid, as necessary.
Parameters
geo - geometry to add
construction - true for construction lines
Return values
int - GeoId of added element
Definition at line 1693 of file SketchObject.cpp.
References SketcherExample::Geometry, Path.Post.scripts.opensbp_post::move(), and Sketcher::GeometryFacade::setConstruction().
addSymmetric()
int SketchObject::addSymmetric (const std::vector< int > & geoIdList, int refGeoId, Sketcher::PointPos refPosId = Sketcher::PointPos::none, bool addSymmetryConstraints = false)
adds symmetric geometric elements with respect to the refGeoId (line or point)
Definition at line 4691 of file SketchObject.cpp.
References Sketcher::Angle, Sketcher::Coincident, SketcherExample::Constraints, Sketcher::Constraint::copy(), Sketcher::Distance, Sketcher::DistanceX, Sketcher::DistanceY, Sketcher::end, Sketcher::Equal, Sketcher::Constraint::First, Sketcher::Constraint::FirstPos, SketcherExample::Geometry, Sketcher::GeoUndef, Sketcher::GeometryFacade::getFacade(), Sketcher::HAxis, Sketcher::Horizontal, Sketcher::InternalAlignment, Base::BaseClass::is(), Sketcher::mid, Path.Post.scripts.opensbp_post::move(), Sketcher::Constraint::Name, Sketcher::none, Sketcher::Parallel, Sketcher::Perpendicular, Sketcher::PointOnObject, Sketcher::Constraint::Second, Sketcher::Constraint::SecondPos, Sketcher::Constraint::setValue(), Sketcher::start, Sketcher::Symmetric, Sketcher::Tangent, Sketcher::Constraint::Third, Sketcher::Constraint::ThirdPos, Sketcher::Constraint::Type, Sketcher::VAxis, and Sketcher::Vertical.
analyseMissingPointOnPointCoincident()
void SketchObject::analyseMissingPointOnPointCoincident (double angleprecision = M_PI / 8)
Definition at line 11746 of file SketchObject.cpp.
appendConflictMsg()
void SketchObject::appendConflictMsg (const std::vector< int > & conflicting, std::string & msg) static
generates a warning message about constraint conflicts and appends it to the given message
Definition at line 9703 of file SketchObject.cpp.
References Path.Op.Surface::msg.
appendConstraintsMsg()
void SketchObject::appendConstraintsMsg (const std::vector< int > & vector, const std::string & singularmsg, const std::string & pluralmsg, std::string & msg) static protected
Definition at line 9728 of file SketchObject.cpp.
References SplineSurface::i, and Path.Op.Surface::msg.
appendMalformedConstraintsMsg()
void SketchObject::appendMalformedConstraintsMsg (const std::vector< int > & malformed, std::string & msg) static
generates a warning message about malformed constraints and appends it to the given message
Definition at line 9719 of file SketchObject.cpp.
References Path.Op.Surface::msg.
appendRedundantMsg()
void SketchObject::appendRedundantMsg (const std::vector< int > & redundant, std::string & msg) static
generates a warning message about redundant constraints and appends it to the given message
Definition at line 9711 of file SketchObject.cpp.
References Path.Op.Surface::msg.
arePointsCoincident()
bool SketchObject::arePointsCoincident (int GeoId1, PointPos PosId1, int GeoId2, PointPos PosId2)
Definition at line 9665 of file SketchObject.cpp.
Referenced by CmdSketcherConstrainCoincidentUnified::activatedCoincident(), CmdSketcherConstrainCoincidentUnified::applyConstraintCoincident(), DrawSketchHandlerDimension::createCoincidenceConstrain(), and CmdSketcherConstrainCoincidentUnified::substituteConstraintCombinationsCoincident().
attachExternal()
int SketchObject::attachExternal (const std::vector< int > & geoIds, App::DocumentObject * Obj, const char * SubName)
attach a link reference to an external geometry
Definition at line 7939 of file SketchObject.cpp.
References FC_ERR, App::DocumentObject::getDocument(), Sketcher::ExternalGeometryFacade::getFacade(), Path.Post.scripts.opensbp_post::move(), and Sketcher::RefExt.
autoConstraint()
int SketchObject::autoConstraint (double precision = Precision::Confusion() * 1000, double angleprecision = M_PI / 20, bool includeconstruction = true)
Definition at line 11736 of file SketchObject.cpp.
References draftgeoutils.general::precision().
autoRemoveRedundants()
int SketchObject::autoRemoveRedundants (bool updategeo = true)
returns the number of redundant constraints detected
Definition at line 11839 of file SketchObject.cpp.
References SplineSurface::i.
Referenced by SketcherGui::tryAutoRecompute(), and SketcherGui::tryAutoRecomputeIfNotSolve().
buildInternals()
Part::TopoShape SketchObject::buildInternals (const Part::TopoShape & edges) const
Definition at line 440 of file SketchObject.cpp.
References Part::WireJoiner::addShape(), SCL.SimpleDataTypes::e, FC_WARN, Part::WireJoiner::getOpenWires(), Part::WireJoiner::getResultWires(), Part::TopoShape::isNull(), result, Part::WireJoiner::setMergeEdges(), and Part::WireJoiner::setTightBound().
buildShape()
void SketchObject::buildShape () protected
Definition at line 324 of file SketchObject.cpp.
References checkSmallEdge(), Sketcher::ExternalGeometryExtension::Defining, FC_WARN, Data::IndexedName::fromConst(), Data::MappedName::fromRawData(), Sketcher::GeometryFacade::getConstruction(), Sketcher::ExternalGeometryFacade::getFacade(), Data::ComplexGeoData::hasElementMap(), SplineSurface::i, Part::TopoShape::resetElementMap(), result, Data::ComplexGeoData::setElementName(), DrawingExample::Shape, Part::OpCodes::Sketch, and Sketcher::start.
calculateAngleViaPoint()
double SketchObject::calculateAngleViaPoint (int geoId1, int geoId2, double px, double py)
Definition at line 9970 of file SketchObject.cpp.
References Sketcher::Sketch::addGeometry(), Sketcher::Sketch::calculateAngleViaParams(), Sketcher::Sketch::calculateAngleViaPoint(), Part::GeomCurve::closestParameter(), and Base::BaseClass::is().
Referenced by CmdSketcherConstrainAngle::applyConstraint().
calculateConstraintError()
double SketchObject::calculateConstraintError (int ConstrId)
Definition at line 10038 of file SketchObject.cpp.
References Sketcher::Sketch::addConstraint(), Sketcher::Sketch::addGeometry(), Sketcher::Sketch::calculateConstraintError(), Sketcher::Constraint::clone(), SketcherExample::Constraints, Sketcher::Constraint::First, toolbit-attributes::g, Sketcher::GeoUndef, SplineSurface::i, result, Sketcher::Constraint::Second, and Sketcher::Constraint::Third.
carbonCopy()
int SketchObject::carbonCopy (App::DocumentObject * pObj, bool construction = true)
Carbon copy another sketch geometry and constraints.
Definition at line 7380 of file SketchObject.cpp.
References Base::Console(), SketcherExample::Constraints, Constraints, Drawing::copy(), Part::Geometry::copy(), Sketcher::Constraint::copy(), Sketcher::PropertyConstraintList::createPath(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), ExternalGeo, ExternalGeometry, Sketcher::Constraint::First, SketcherExample::Geometry, Sketcher::GeoUndef, Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), App::ObjectIdentifier::getDocumentObjectName(), Sketcher::ExternalGeometryFacade::getFacade(), getInternalGeometry(), App::ObjectIdentifier::String::getString(), Base::Persistence::getTypeId(), Sketcher::PropertyConstraintList::getValues(), SplineSurface::i, App::ExpressionParser::isTokenAnIndentifier(), Path.Post.scripts.opensbp_post::move(), App::Expression::parse(), Sketcher::Constraint::Second, Sketcher::GeometryFacade::setConstruction(), App::ObjectIdentifier::SimpleComponent(), Sketcher::Constraint::Third, App::ObjectIdentifier::toString(), and App::Property::User3.
changeConstraintAfterDeletingGeo()
void SketchObject::changeConstraintAfterDeletingGeo (Constraint * constr, const int deletedGeoId) const protected
Definition at line 3889 of file SketchObject.cpp.
References Sketcher::Constraint::First, Sketcher::GeoUndef, Sketcher::Constraint::Second, and Sketcher::Constraint::Third.
changeConstraintsLocking()
int SketchObject::changeConstraintsLocking (bool bLock)
changeConstraintsLocking locks or unlocks all tangent and perpendicular constraints. (Constraint locking prevents it from flipping to another valid configuration, when e.g. external geometry is updated from outside.) The sketch solve is not triggered by the function, but the SketchObject is touched (a recompute will be necessary). The geometry should not be affected by the function. The bLock argument specifies, what to do. If true, all constraints are unlocked and locked again. If false, all tangent and perp. constraints are unlocked.
Definition at line 10930 of file SketchObject.cpp.
References Sketcher::Constraint::clone(), Base::Console(), SketcherExample::Constraints, SplineSurface::i, Base::ConsoleSingleton::Log(), Path.Post.scripts.opensbp_post::move(), Sketcher::Perpendicular, and Sketcher::Tangent.
checkSubName()
Data::IndexedName SketchObject::checkSubName (const char * subname) const
Definition at line 11476 of file SketchObject.cpp.
References dot(), DraftVecUtils::equals(), FC_ERR, Data::IndexedName::fromConst(), Sketcher::GeometryFacade::getId(), Data::isMappedElement(), Sketcher::none, and result.
constraintHasExpression()
bool SketchObject::constraintHasExpression (int constNum) const
Definition at line 1143 of file SketchObject.cpp.
References SketcherExample::Constraints, Path.Log::info(), and src.Mod.Test.testPathArray::path.
constraintsRemoved()
void SketchObject::constraintsRemoved (const std::set< App::ObjectIdentifier > & removed) protected
Definition at line 10008 of file SketchObject.cpp.
References SplineSurface::i.
Referenced by SketchObject().
constraintsRenamed()
void SketchObject::constraintsRenamed (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > & renamed) protected
Definition at line 9999 of file SketchObject.cpp.
References toolbit-attributes::doc, and App::GetApplication().
Referenced by SketchObject().
convertInternalName()
const char * SketchObject::convertInternalName (const char * name) static
Definition at line 11375 of file SketchObject.cpp.
convertSubName() [1/3]
std::string SketchObject::convertSubName (const char * subname, bool postfix = true) const
Definition at line 11642 of file SketchObject.cpp.
Referenced by SketcherGui::TaskSketcherElements::onListWidgetElementsItemPressed().
convertSubName() [2/3]
std::string SketchObject::convertSubName (const Data::IndexedName & indexedName, bool postfix = true) const
Definition at line 11646 of file SketchObject.cpp.
References Data::ELEMENT_MAP_PREFIX, Data::ComplexGeoData::elementMapPrefix(), Data::IndexedName::fromConst(), Sketcher::GeometryFacade::getFacade(), Data::IndexedName::getIndex(), Data::IndexedName::getType(), Sketcher::HAxis, Sketcher::none, Sketcher::RtPnt, Data::IndexedName::toString(), and Sketcher::VAxis.
convertSubName() [3/3]
std::string Sketcher::SketchObject::convertSubName (const std::string & subname, bool postfix = true) const inline
Definition at line 823 of file SketchObject.h.
convertToNURBS()
bool SketchObject::convertToNURBS (int GeoId)
Approximates the given geometry with a B-spline.
Parameters
GeoId - the geometry to approximate
delgeoid - if true in addition to the unused internal geometry also deletes the GeoId geometry
Return values
bool - returns true if the approximation succeeded, or false if it did not succeed.
Definition at line 6839 of file SketchObject.cpp.
References Sketcher::Coincident, Base::Console(), SketcherExample::Constraints, Sketcher::GeometryFacade::copyId(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), SketcherExample::Geometry, Base::Persistence::getClassTypeId(), Part::GeomCurve::getFirstParameter(), Part::GeomCurve::getLastParameter(), Base::BaseClass::is(), Base::BaseClass::isDerivedFrom(), Part::GeomArcOfConic::isReversed(), Sketcher::mid, Path.Post.scripts.opensbp_post::move(), FreeCADInit::Second, and Part::GeomCurve::toNurbs().
createConstraint()
std::unique_ptr< Constraint > SketchObject::createConstraint (Sketcher::ConstraintType constrType, int firstGeoId, Sketcher::PointPos firstPos, int secondGeoId = GeoEnum::GeoUndef, Sketcher::PointPos secondPos = Sketcher::PointPos::none, int thirdGeoId = GeoEnum::GeoUndef, Sketcher::PointPos thirdPos = Sketcher::PointPos::none) protected
Definition at line 3415 of file SketchObject.cpp.
decreaseBSplineDegree()
bool SketchObject::decreaseBSplineDegree (int GeoId, int degreedecrement = 1)
Decreases the degree of a BSpline by degreedecrement, which defaults to 1.
Parameters
GeoId - the geometry of type bspline to increase the degree
degreedecrement - the decrement in number of degrees to effect
Return values
bool - returns true if the decrease in degree succeeded, or false if it did not succeed.
Definition at line 6970 of file SketchObject.cpp.
References Base::Console(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), SketcherExample::Geometry, Base::Persistence::getClassTypeId(), Base::Persistence::getTypeId(), and Handle().
delAllExternal()
int SketchObject::delAllExternal ()
deletes all external geometry
Definition at line 7852 of file SketchObject.cpp.
References Sketcher::Constraint::clone(), Base::Console(), SketcherExample::Constraints, src.Mod.AddonManager.NetworkManager::count, SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), Sketcher::GeoUndef, Sketcher::ExternalGeometryFacade::getFacade(), SplineSurface::i, Path.Post.scripts.opensbp_post::move(), and Sketcher::RefExt.
delConstraint()
int SketchObject::delConstraint (int ConstrId)
delete constraint
Definition at line 2245 of file SketchObject.cpp.
References SketcherExample::Constraints, and Path.Post.scripts.opensbp_post::move().
delConstraintOnPoint() [1/2]
int SketchObject::delConstraintOnPoint (int GeoId, PointPos PosId, bool onlyCoincident = true)
Definition at line 2312 of file SketchObject.cpp.
References Sketcher::Coincident, SketcherExample::Constraints, Sketcher::Distance, Sketcher::DistanceX, Sketcher::DistanceY, Sketcher::end, Sketcher::GeoUndef, Sketcher::Horizontal, Path.Post.scripts.opensbp_post::move(), Sketcher::none, Sketcher::Perpendicular, Sketcher::PointOnObject, Sketcher::start, Sketcher::Symmetric, Sketcher::Tangent, and Sketcher::Vertical.
delConstraintOnPoint() [2/2]
int SketchObject::delConstraintOnPoint (int VertexId, bool onlyCoincident = true)
Definition at line 2298 of file SketchObject.cpp.
References Sketcher::RtPnt, and Sketcher::start.
delConstraints()
int SketchObject::delConstraints (std::vector< int > ConstrIds, bool updategeometry = true)
deletes a group of constraints at once, if norecomputes is active, the default behaviour is that it will solve the sketch.
If updating the Geometry property as a consequence of a (successful) solve() is not wanted, updategeometry=false, prevents the update. This allows one to update the solve status (e.g. dof), without updating the geometry (i.e. make it move to fulfil the constraints).
Definition at line 2267 of file SketchObject.cpp.
References SketcherExample::Constraints, and Path.Post.scripts.opensbp_post::move().
delConstraintsToExternal()
int SketchObject::delConstraintsToExternal ()
Deletes all constraints referencing an external geometry.
Definition at line 7913 of file SketchObject.cpp.
References SketcherExample::Constraints, Sketcher::GeoUndef, Path.Post.scripts.opensbp_post::move(), and Sketcher::RefExt.
deleteAllConstraints()
int SketchObject::deleteAllConstraints ()
deletes all the constraints of the sketch
Definition at line 1960 of file SketchObject.cpp.
References SketcherExample::Constraints.
deleteAllGeometry()
int SketchObject::deleteAllGeometry ()
deletes all the elements/constraints of the sketch except for external geometry
Definition at line 1935 of file SketchObject.cpp.
References SketcherExample::Constraints, and SketcherExample::Geometry.
deleteUnusedInternalGeometry()
int SketchObject::deleteUnusedInternalGeometry (int GeoId, bool delgeoid = false)
Deletes all unused (not further constrained) internal geometry.
Parameters
GeoId - the geometry having the internal geometry to delete
delgeoid - if true in addition to the unused internal geometry also deletes the GeoId geometry
Return values
int - returns -1 on error, otherwise the number of deleted elements
Definition at line 6511 of file SketchObject.cpp.
References Sketcher::BSplineControlPoint, Sketcher::BSplineKnotPoint, SketcherExample::Constraints, Part::GeomBSplineCurve::countKnots(), Part::GeomBSplineCurve::countPoles(), Sketcher::EllipseFocus1, Sketcher::EllipseFocus2, Sketcher::EllipseMajorDiameter, Sketcher::EllipseMinorDiameter, Sketcher::Equal, SCL.SimpleDataTypes::f, Sketcher::HyperbolaFocus, Sketcher::HyperbolaMajor, Sketcher::HyperbolaMinor, Sketcher::InternalAlignment, Base::BaseClass::is(), Sketcher::ParabolaFocalAxis, Sketcher::ParabolaFocus, and toolbit-attributes::s.
deleteUnusedInternalGeometryAndUpdateGeoId()
int SketchObject::deleteUnusedInternalGeometryAndUpdateGeoId (int & GeoId, bool delgeoid = false)
Same as deleteUnusedInternalGeometry, but changes GeoId to the new Id of the geometry, or to GeoEnum::GeoUndef if the geometry is deleted as well.
Parameters
GeoId - the geometry having the internal geometry to delete
delgeoid - if true in addition to the unused internal geometry also deletes the GeoId geometry
Return values
int - returns -1 on error, otherwise the number of deleted elements
Definition at line 6806 of file SketchObject.cpp.
References Sketcher::GeoUndef, Part::Geometry::getTag(), and SplineSurface::i.
delExternal() [1/2]
int SketchObject::delExternal (const std::vector< int > & ExtGeoIds)
Definition at line 7721 of file SketchObject.cpp.
References Sketcher::ExternalGeometryFacade::getFacade(), and Sketcher::RefExt.
delExternal() [2/2]
int SketchObject::delExternal (int ExtGeoId)
delete external ExtGeoId >= 0 with 0 corresponding to the first user defined external geometry
Definition at line 7716 of file SketchObject.cpp.
delExternalPrivate()
void SketchObject::delExternalPrivate (const std::set< long > & ids, bool removeReference) protected
Definition at line 7745 of file SketchObject.cpp.
References Sketcher::Constraint::clone(), SketcherExample::Constraints, Sketcher::Constraint::First, Sketcher::GeoUndef, Sketcher::ExternalGeometryFacade::getFacade(), Path.Post.scripts.opensbp_post::move(), replaceobj::objs, draftfunctions.offset::offset(), Sketcher::Constraint::Second, importers.importIFCmulticore::subs, and Sketcher::Constraint::Third.
delGeometries()
int SketchObject::delGeometries (const std::vector< int > & GeoIds)
Does the same as delGeometry but allows one to delete several geometries in one step.
Definition at line 1806 of file SketchObject.cpp.
References SCL.SimpleDataTypes::c, SketcherExample::Constraints, DraftVecUtils::find(), Sketcher::InternalAlignment, RobotExample::pos, Sketcher::RefExt, and result.
delGeometriesExclusiveList()
int SketchObject::delGeometriesExclusiveList (const std::vector< int > & GeoIds)
Deletes just the GeoIds indicated, it does not look for internal geometry.
Definition at line 1853 of file SketchObject.cpp.
References SketcherExample::Constraints, Sketcher::end, Sketcher::Constraint::First, SketcherExample::Geometry, Sketcher::mid, Path.Post.scripts.opensbp_post::move(), Sketcher::Constraint::Second, Sketcher::start, and Sketcher::Constraint::Third.
delGeometry()
int SketchObject::delGeometry (int GeoId, bool deleteinternalgeo = true)
Deletes indicated geometry (by geoid).
Parameters
GeoId - the geometry to delete
deleteinternalgeo - if true deletes the associated and unconstraint internal geometry, otherwise deletes only the GeoId
Return values
int - 0 if successful
Definition at line 1735 of file SketchObject.cpp.
References SketcherExample::Constraints, Sketcher::end, SketcherExample::Geometry, Sketcher::mid, Path.Post.scripts.opensbp_post::move(), Sketcher::RefExt, and Sketcher::start.
Referenced by Sketcher::SketchAnalysis::removeDegeneratedGeometries().
deriveConstraintsForPieces() [1/2]
bool SketchObject::deriveConstraintsForPieces (const int oldId, const std::vector< int > & newIds, const Constraint * con, std::vector< Constraint * > & newConstraints)
Once smaller pieces have been created from a larger curve (by split or trim, say), derive the constraint that will replace the given one (which is to be deleted). NOTE: Currently assuming all constraints on the end points of the old curve have been transferred or destroyed Returns whether or not new constraint(s) was/were added.
Definition at line 3914 of file SketchObject.cpp.
deriveConstraintsForPieces() [2/2]
bool SketchObject::deriveConstraintsForPieces (const int oldId, const std::vector< int > & newIds, const std::vector< const Part::Geometry * > & newGeo, const Constraint * con, std::vector< Constraint * > & newConstraints)
Definition at line 3927 of file SketchObject.cpp.
References Part::GeomCurve::closestParameter(), Sketcher::Constraint::copy(), Sketcher::Diameter, DraftVecUtils::dist(), Sketcher::Distance, Sketcher::DistanceX, Sketcher::DistanceY, Sketcher::end, Sketcher::Equal, Sketcher::Constraint::First, Sketcher::Constraint::FirstPos, draftguitools.gui_tool_utils::getPoint, Sketcher::Horizontal, SplineSurface::i, Part::intersect(), Base::BaseClass::is(), Base::BaseClass::isDerivedFrom(), Sketcher::none, Sketcher::Parallel, Sketcher::Perpendicular, Sketcher::PointOnObject, Sketcher::Radius, Sketcher::Constraint::Second, Sketcher::Constraint::SecondPos, Sketcher::start, Sketcher::Constraint::substituteIndex(), Sketcher::Tangent, Sketcher::Constraint::Type, and Sketcher::Vertical.
detachExternal()
int Sketcher::SketchObject::detachExternal (const std::vector< int > & geoIds)
detectDegeneratedGeometries()
int SketchObject::detectDegeneratedGeometries (double tolerance)
Detect degenerated geometries.
Definition at line 11829 of file SketchObject.cpp.
References draftutils.utils::tolerance().
detectMissingEqualityConstraints()
int SketchObject::detectMissingEqualityConstraints (double precision)
Definition at line 11756 of file SketchObject.cpp.
References draftgeoutils.general::precision().
detectMissingPointOnPointConstraints()
int SketchObject::detectMissingPointOnPointConstraints (double precision = Precision::Confusion() * 1000, bool includeconstruction = true)
Definition at line 11741 of file SketchObject.cpp.
References draftgeoutils.general::precision().
detectMissingVerticalHorizontalConstraints()
int SketchObject::detectMissingVerticalHorizontalConstraints (double angleprecision = M_PI / 8)
Definition at line 11751 of file SketchObject.cpp.
diagnoseAdditionalConstraints()
int SketchObject::diagnoseAdditionalConstraints (std::vector< Sketcher::Constraint * > additionalconstraints)
Performs a full analysis of the addition of additional constraints without adding them to the sketch object
Definition at line 1320 of file SketchObject.cpp.
References SketcherExample::Constraints.
evaluateConstraint()
bool SketchObject::evaluateConstraint (const Constraint * constraint) const
Check if constraint has invalid indexes.
Definition at line 9801 of file SketchObject.cpp.
References Sketcher::Angle, Sketcher::Coincident, Sketcher::Diameter, Sketcher::Distance, Sketcher::DistanceX, Sketcher::DistanceY, Sketcher::Equal, Sketcher::Constraint::First, Sketcher::GeoUndef, Sketcher::Horizontal, Sketcher::Parallel, Sketcher::Perpendicular, Sketcher::PointOnObject, Sketcher::Radius, Sketcher::Constraint::Second, Sketcher::SnellsLaw, Sketcher::Symmetric, Sketcher::Tangent, Sketcher::Constraint::Third, Sketcher::Constraint::Type, Sketcher::Vertical, and Sketcher::Weight.
evaluateConstraints()
bool SketchObject::evaluateConstraints () const
Check for constraints with invalid indexes.
Definition at line 9862 of file SketchObject.cpp.
References SketcherExample::Constraints.
Referenced by SketcherGui::ViewProviderSketch::setEdit().
evaluateSupport()
bool SketchObject::evaluateSupport ()
Checks if support is valid.
Definition at line 8198 of file SketchObject.cpp.
References Base::BaseClass::isDerivedFrom().
execute()
App::DocumentObjectExecReturn * SketchObject::execute () override virtual
recalculate the Feature (if no recompute is needed see also solve() and solverNeedsUpdate boolean)
Reimplemented from Part::Part2DObject.
Definition at line 257 of file SketchObject.cpp.
References SketcherExample::Constraints, SCL.SimpleDataTypes::e, Path.Op.Surface::msg, and App::DocumentObject::StdReturn.
Referenced by FeaturePython.DistanceBolt::onChanged().
exposeInternalGeometry()
int SketchObject::exposeInternalGeometry (int GeoId)
Exposes all internal geometry of an object supporting internal geometry.
Returns
-1 on error
Definition at line 5972 of file SketchObject.cpp.
References Sketcher::Constraint::AlignmentType, Sketcher::BSplineControlPoint, Sketcher::BSplineKnotPoint, exportCSG::center(), SketcherExample::Constraints, Part::GeomBSplineCurve::countKnots(), Part::GeomBSplineCurve::countPoles(), Sketcher::EllipseFocus1, Sketcher::EllipseFocus2, Sketcher::EllipseMajorDiameter, Sketcher::EllipseMinorDiameter, Sketcher::Equal, Sketcher::Constraint::First, Sketcher::Constraint::FirstPos, Part::GeomArcOfConic::getCenter(), Part::GeomArcOfParabola::getFocus(), Part::GeomBSplineCurve::getKnots(), Part::GeomArcOfEllipse::getMajorAxisDir(), Part::GeomArcOfHyperbola::getMajorAxisDir(), Part::GeomArcOfEllipse::getMajorRadius(), Part::GeomArcOfHyperbola::getMajorRadius(), Part::GeomArcOfEllipse::getMinorRadius(), Part::GeomArcOfHyperbola::getMinorRadius(), Part::GeomBSplineCurve::getPoles(), Part::GeomBSplineCurve::getWeights(), Sketcher::HyperbolaFocus, Sketcher::HyperbolaMajor, Sketcher::HyperbolaMinor, Sketcher::InternalAlignment, Sketcher::Constraint::InternalAlignmentIndex, Base::BaseClass::is(), FreeCADInit::Length, Sketcher::mid, Sketcher::none, Sketcher::ParabolaFocalAxis, Sketcher::ParabolaFocus, Part::GeomCurve::pointAtParameter(), Sketcher::Constraint::Second, Sketcher::Constraint::SecondPos, Part::GeomConic::setCenter(), Part::GeomPoint::setPoint(), Part::GeomLineSegment::setPoints(), Part::GeomCircle::setRadius(), Sketcher::Constraint::setValue(), KDL::sqrt(), Sketcher::start, Sketcher::Constraint::Type, Sketcher::Weight, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
extend()
int SketchObject::extend (int geoId, double increment, PointPos endPoint)
extend a curve
Definition at line 3367 of file SketchObject.cpp.
References Path.Post.scripts.opensbp_post::arc(), Sketcher::end, Part::GeomLineSegment::getEndPoint(), Part::GeomLineSegment::getStartPoint(), Base::BaseClass::is(), Base::Vector3< float_type >::Length(), Base::Vector3< float_type >::Normalize(), Base::Vector3< float_type >::Scale(), and Sketcher::start.
fillet() [1/2]
int SketchObject::fillet (int geoId, PointPos pos, double radius, bool trim = true, bool preserveCorner = false, bool chamfer = false)
Create a sketch fillet from the point at the intersection of two lines.
Parameters
geoId,pos - one of the (exactly) two coincident endpoints
radius - fillet radius
trim - if false, leaves the original lines untouched
createCorner - keep geoId/pos as a Point and keep as many constraints as possible
Return values
- 0 on success, -1 on failure
Definition at line 2687 of file SketchObject.cpp.
References draftgeoutils.fillets::fillet(), Base::BaseClass::is(), and Materials::trim().
fillet() [2/2]
int SketchObject::fillet (int geoId1, int geoId2, const Base::Vector3d & refPnt1, const Base::Vector3d & refPnt2, double radius, bool trim = true, bool createCorner = false, bool chamfer = false)
More general form of fillet.
Parameters
geoId1,geoId2 - geoId for two lines (which don't necessarily have to coincide)
refPnt1,refPnt2 - reference points on the input geometry, used to influence the free fillet variables
radius - fillet radius
trim - if false, leaves the original lines untouched
preserveCorner - if the lines are coincident, place a Point where they meet and keep as many of the existing constraints as possible
Return values
- 0 on success, -1 on failure
Definition at line 2715 of file SketchObject.cpp.
References KDL::abs(), Path.Post.scripts.opensbp_post::arc(), KDL::atan2(), Part::GeomCurve::closestParameter(), Sketcher::Coincident, Base::Console(), SketcherExample::Constraints, Part::createFilletGeometry(), Base::Vector3< float_type >::Cross(), DraftVecUtils::dist(), Base::Vector3< float_type >::Dot(), SCL.SimpleDataTypes::e, Sketcher::end, SCL.SimpleDataTypes::f, Part::find2DLinesIntersection(), Part::findFilletCenter(), Part::GeomCurve::firstDerivativeAtParameter(), Sketcher::GeometryFacade::getBlocked(), Part::GeomCurve::getFirstParameter(), draftguitools.gui_tool_utils::getPoint, Handle(), SplineSurface::i, Part::GeomCurve::intersect(), intersection(), Base::BaseClass::is(), Base::BaseClass::isDerivedFrom(), Base::Vector3< float_type >::Length(), FreeCADInit::Length, Base::ConsoleSingleton::Log(), M_PI, Path.Post.scripts.opensbp_post::move(), Sketcher::none, Sketcher::Perpendicular, Part::GeomCurve::pointAtParameter(), Base::Vector3< float_type >::ProjectToLine(), Arch::QT_TRANSLATE_NOOP, Sketcher::start, Sketcher::Tangent, Part::GeomCurve::tangent(), THROWM, THROWMT, Materials::trim(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
fixExternalGeometry()
void SketchObject::fixExternalGeometry (const std::vector< int > & geoIds = {})
auto fix external geometry references
Definition at line 9341 of file SketchObject.cpp.
References Data::ComplexGeoData::elementMapPrefix(), FC_ERR, Sketcher::ExternalGeometryFacade::getFacade(), Part::Feature::getRelatedElements(), SplineSurface::i, Sketcher::ExternalGeometryExtension::Missing, replaceobj::objs, RobotExample::pos, and importers.importIFCmulticore::subs.
generateId()
void SketchObject::generateId (const Part::Geometry * geo) protected
Definition at line 737 of file SketchObject.cpp.
References Sketcher::end, FC_TRACE, SketcherExample::Geometry, Sketcher::GeometryFacade::getId(), draftguitools.gui_tool_utils::getPoint, SplineSurface::id, OpenSCADFeatures::long, Sketcher::GeometryFacade::setId(), and Sketcher::start.
geoIdFromShapeType() [1/3]
bool Sketcher::SketchObject::geoIdFromShapeType (const char * shapetype, int & geoId) const inline
Definition at line 812 of file SketchObject.h.
geoIdFromShapeType() [2/3]
bool Sketcher::SketchObject::geoIdFromShapeType (const char * shapetype, int & geoId, PointPos & posId) const inline
Definition at line 807 of file SketchObject.h.
geoIdFromShapeType() [3/3]
bool SketchObject::geoIdFromShapeType (const Data::IndexedName & indexedName, int & geoId, PointPos & posId) const
Definition at line 11610 of file SketchObject.cpp.
References DraftVecUtils::equals(), Sketcher::GeoUndef, Data::IndexedName::getIndex(), Data::IndexedName::getType(), Sketcher::HAxis, Sketcher::none, Sketcher::RefExt, Sketcher::RtPnt, Sketcher::start, and Sketcher::VAxis.
getActive()
int SketchObject::getActive (int ConstrId, bool & isactive)
get the driving status of this constraint
Definition at line 939 of file SketchObject.cpp.
References SketcherExample::Constraints.
getAllCoincidentPoints()
const std::map< int, Sketcher::PointPos > SketchObject::getAllCoincidentPoints (int GeoId, PointPos PosId)
Definition at line 9589 of file SketchObject.cpp.
Referenced by SketcherGui::removeRedundantHorizontalVertical().
getAxis()
Base::Axis SketchObject::getAxis (int axId) const override virtual
retrieves an axis iterating through the construction lines of the sketch (indices start at 0)
Reimplemented from Part::Part2DObject.
Definition at line 1588 of file SketchObject.cpp.
References Axis, src.Mod.AddonManager.NetworkManager::count, Sketcher::end, Part::Part2DObject::getAxis(), Sketcher::GeometryFacade::getConstruction(), Part::GeomLineSegment::getEndPoint(), Part::GeomLineSegment::getStartPoint(), and Sketcher::start.
getAxisCount()
int SketchObject::getAxisCount () const override virtual
returns the number of construction lines (to be used as axes)
Reimplemented from Part::Part2DObject.
Definition at line 1573 of file SketchObject.cpp.
References src.Mod.AddonManager.NetworkManager::count, and Sketcher::GeometryFacade::getConstruction().
getBlockedState()
bool SketchObject::getBlockedState (const Constraint * cstr, bool & blockedstate) const protected
Definition at line 10631 of file SketchObject.cpp.
References Sketcher::Block, and Sketcher::Constraint::Type.
getCoincidenceGroups()
const std::vector< std::map< int, Sketcher::PointPos > > SketchObject::getCoincidenceGroups ()
Definition at line 9489 of file SketchObject.cpp.
References Sketcher::Coincident, SketcherExample::Constraints, Sketcher::end, and SplineSurface::i.
getCompleteGeometry()
std::vector< Part::Geometry * > SketchObject::getCompleteGeometry () const
retrieves a vector containing both normal and external Geometry (including the sketch axes)
Definition at line 9393 of file SketchObject.cpp.
Referenced by SketcherGui::DrawSketchHandler::seekAutoConstraint().
getCompleteGeometryIndex()
int SketchObject::getCompleteGeometryIndex (int GeoId) const
converts a GeoId index into an index of the CompleteGeometry vector
Definition at line 8063 of file SketchObject.cpp.
References SketcherExample::Geometry, and Sketcher::GeoUndef.
getConstraintAfterDeletingGeo()
std::unique_ptr< Constraint > SketchObject::getConstraintAfterDeletingGeo (const Constraint * constr, const int deletedGeoId) const protected
Definition at line 3872 of file SketchObject.cpp.
References Sketcher::Constraint::clone(), Sketcher::Constraint::First, Sketcher::Constraint::Second, and Sketcher::Constraint::Third.
getConstraintExpression()
std::string SketchObject::getConstraintExpression (int constNum) const
Definition at line 1153 of file SketchObject.cpp.
References SketcherExample::Constraints, Path.Log::info(), and src.Mod.Test.testPathArray::path.
getConstraintIndices()
void SketchObject::getConstraintIndices (int GeoId, std::vector< int > & constraintList)
returns a list of indices of all constraints involving given GeoId
Definition at line 9690 of file SketchObject.cpp.
References SketcherExample::Constraints, and SplineSurface::i.
getDirectlyCoincidentPoints() [1/2]
void SketchObject::getDirectlyCoincidentPoints (int GeoId, PointPos PosId, std::vector< int > & GeoIdList, std::vector< PointPos > & PosIdList)
retrieves for a Vertex number a list with all coincident points (sharing a single coincidence constraint)
Definition at line 9613 of file SketchObject.cpp.
References Sketcher::Coincident, SketcherExample::Constraints, Sketcher::end, Sketcher::start, and Sketcher::Tangent.
getDirectlyCoincidentPoints() [2/2]
void SketchObject::getDirectlyCoincidentPoints (int VertexId, std::vector< int > & GeoIdList, std::vector< PointPos > & PosIdList)
Definition at line 9656 of file SketchObject.cpp.
getDriving()
int SketchObject::getDriving (int ConstrId, bool & isdriving)
get the driving status of this constraint
Definition at line 880 of file SketchObject.cpp.
References SketcherExample::Constraints.
getEdge()
Part::TopoShape SketchObject::getEdge (const Part::Geometry * geo, const char * name) const
Definition at line 11445 of file SketchObject.cpp.
References Sketcher::end, Data::IndexedName::fromConst(), Data::MappedName::fromRawData(), draftguitools.gui_tool_utils::getPoint, Part::TopoShape::getShape(), Data::ComplexGeoData::hasElementMap(), SplineSurface::i, RobotExample::pos, Part::TopoShape::resetElementMap(), Data::ComplexGeoData::setElementName(), Sketcher::start, and Part::Geometry::toShape().
getElementName()
App::ElementNamePair SketchObject::getElementName (const char * name, ElementNameType type) const override virtual
Override getElementName to support the Export type. Other calls are passed to the original method
Parameters
name The name to search for, or if non existent, name of current Feature is returned
type An element type name.
Returns
a struct with the newName and oldName. New element name may be empty.
Reimplemented from Part::Feature.
Definition at line 11382 of file SketchObject.cpp.
References Data::MappedName::appendToBuffer(), Data::IndexedName::appendToStringBuffer(), dot(), Data::ComplexGeoData::elementMapPrefix(), UtilsAssembly::getElementName(), hasSketchMarker(), Data::MappedElement::index, Data::isMappedElement(), Data::MISSING_PREFIX, Data::MappedElement::name, App::ElementNamePair::newName, App::ElementNamePair::oldName, Part::TopoShape::shapeTypeAndIndex(), and Path.Post.scripts.grbl_post::type.
getElementTypes()
std::vector< const char * > SketchObject::getElementTypes (bool all = true) const override virtual
Reimplemented from App::GeoFeature.
Definition at line 11330 of file SketchObject.cpp.
References App::GeoFeature::getElementTypes(), and Part::TopoShape::shapeName().
getExternalGeometry()
const std::vector<Part::Geometry*>& Sketcher::SketchObject::getExternalGeometry () const inline
returns a list of projected external geometries
Definition at line 267 of file SketchObject.h.
getExternalGeometryCount()
int Sketcher::SketchObject::getExternalGeometryCount () const inline
returns the number of external Geometry entities
Definition at line 276 of file SketchObject.h.
Referenced by isCarbonCopyAllowed().
getGeoIdFromCompleteGeometryIndex()
int SketchObject::getGeoIdFromCompleteGeometryIndex (int completeGeometryIndex) const
Definition at line 8075 of file SketchObject.cpp.
References SketcherExample::Geometry, and Sketcher::GeoUndef.
getGeoListFacade()
GeoListFacade SketchObject::getGeoListFacade () const
Definition at line 9401 of file SketchObject.cpp.
References SketcherExample::Geometry, Sketcher::GeometryFacade::getFacade(), Sketcher::GeoListModel< T >::getGeoListModel(), and Path.Post.scripts.opensbp_post::move().
Referenced by SketcherGui::ViewProviderSketch::draw().
getGeometry()
template<typename GeometryT = Part::Geometry, typename = typename std::enable_if< std::is_base_of<Part::Geometry, typename std::decay<GeometryT>::type>::value>::type> const GeometryT* Sketcher::SketchObject::getGeometry (int GeoId) const inline
returns a pointer to a given Geometry index, possible indexes are: id>=0 for user defined geometries, id==-1 for the horizontal sketch axis, id==-2 for the vertical sketch axis id<=-3 for user defined projected external geometries,
Definition at line 254 of file SketchObject.h.
Referenced by SketcherCopy::activate(), CmdSketcherConstrainCoincidentUnified::activatedCoincident(), CmdSketcherConstrainCoincidentUnified::activatedPointOnObject(), Sketcher::SketchAnalysis::analyseMissingPointOnPointCoincident(), CmdSketcherConstrainDistance::applyConstraint(), CmdSketcherConstrainDistanceX::applyConstraint(), CmdSketcherConstrainDistanceY::applyConstraint(), CmdSketcherConstrainParallel::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainRadiam::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), CmdSketcherConstrainCoincidentUnified::applyConstraintCoincident(), CmdSketcherConstrainCoincidentUnified::applyConstraintPointOnObject(), SketcherGui::calculateAngle(), copySelectionToClipboard(), DrawSketchHandlerDimension::createArcAngleConstrain(), DrawSketchHandlerDimension::createArcLengthConstrain(), SketcherGui::DrawSketchHandler::createAutoConstraints(), DrawSketchHandlerDimension::createDistanceConstrain(), DrawSketchHandlerDimension::createEqualityConstrain(), DrawSketchHandlerDimension::createHorizontalConstrain(), DrawSketchHandlerDimension::createRadiusDiameterConstrain(), DrawSketchHandlerDimension::createSymmetryConstrain(), DrawSketchHandlerDimension::createVerticalConstrain(), SketcherGui::doEndpointTangency(), DrawSketchHandlerBSplineInsertKnot::DrawSketchHandlerBSplineInsertKnot(), SketcherGui::DrawSketchHandlerExtend::DrawSketchHandlerExtend(), findBSplineAndKnotIndex(), finishDatumConstraint(), SketcherGui::ViewProviderSketch::generateContextMenu(), SketcherGui::getGeoIdsOfEdgesFromNames(), DrawSketchHandlerDimension::handleInitialSelection(), horVerApplyConstraint(), SketcherGui::isBsplineKnotOrEndPoint(), SketcherGui::isBsplinePole(), SketcherGui::IsPointAlreadyOnCurve(), DrawSketchHandlerDimension::isRadiusDoF(), SketcherGui::isSimpleVertex(), DrawSketchHandlerDimension::makeCts_1Circle(), DrawSketchHandlerDimension::makeCts_2MoreEllipse(), DrawSketchHandlerBSplineInsertKnot::mouseMove(), SketcherGui::DrawSketchHandlerTrimming::pressButton(), DrawSketchHandlerBSplineInsertKnot::releaseButton(), removeRedundantPointOnObject(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), SketcherGui::SnapManager::snapToObject(), and SketcherGui::ViewProviderSketch::toggleWireSelelection().
getGeometryFacade()
std::unique_ptr< const GeometryFacade > SketchObject::getGeometryFacade (int GeoId) const
Definition at line 8088 of file SketchObject.cpp.
References Sketcher::GeometryFacade::getFacade().
Referenced by SketcherGui::isBsplineKnot().
getGeometryId()
int SketchObject::getGeometryId (int GeoId, long & id) const
Definition at line 11925 of file SketchObject.cpp.
References SketcherExample::Geometry, and Sketcher::GeometryFacade::getFacade().
getGeometryReference()
std::string SketchObject::getGeometryReference (int GeoId) const
Return a human friendly element reference of an external geometry.
Definition at line 11702 of file SketchObject.cpp.
References Sketcher::ExternalGeometryFacade::getFacade(), Sketcher::ExternalGeometryExtension::Missing, App::ElementNamePair::oldName, RobotExample::pos, and App::GeoFeature::resolveElement().
getGeometryWithDependentParameters()
void SketchObject::getGeometryWithDependentParameters (std::vector< std::pair< int, PointPos >> & geometrymap)
returns the geometric elements/vertex which the solver detects as having dependent parameters. these parameters relate to not fully constraint edges/vertices.
Definition at line 9749 of file SketchObject.cpp.
References Sketcher::SolverGeometryExtension::Dependent, Base::BaseClass::getClassTypeId(), Sketcher::none, Sketcher::SolverGeometryExtension::NotFullyConstraint, and Sketcher::start.
getGeoVertexIndex()
void SketchObject::getGeoVertexIndex (int VertexId, int & GeoId, PointPos & PosId) const
retrieves for a Vertex number the corresponding GeoId and PosId
Definition at line 10900 of file SketchObject.cpp.
References Sketcher::GeoUndef, and Sketcher::none.
Referenced by SketcherCopy::activate(), SketcherGui::SplittingSelection::allow(), SketcherGui::getGeoIdsOfEdgesFromNames(), SketcherGui::getIdsFromName(), SketcherGui::ViewProviderSketch::mouseMove(), SketcherGui::ViewProviderSketch::onDelete(), SketcherGui::TaskSketcherElements::onSelectionChanged(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), and SketcherGui::SnapManager::snapToObject().
getHigherElements()
std::vector< Data::IndexedName > SketchObject::getHigherElements (const char * name, bool silent = false) const override virtual
Return the higher level element names of the given element.
Reimplemented from App::GeoFeature.
Definition at line 11288 of file SketchObject.cpp.
References Sketcher::Coincident, SketcherExample::Constraints, DraftVecUtils::equals(), Sketcher::Constraint::First, Sketcher::Constraint::FirstPos, Data::IndexedName::fromConst(), Sketcher::Constraint::Second, Sketcher::Constraint::SecondPos, DrawingExample::Shape, Base::silent, and Sketcher::Constraint::Type.
getHighestCurveIndex()
int Sketcher::SketchObject::getHighestCurveIndex () const inline
Definition at line 566 of file SketchObject.h.
Referenced by CmdSketcherConstrainPerpendicular::applyConstraint(), SketcherGui::DrawSketchHandler::getHighestCurveIndex(), SketcherGui::makeTangentToArcOfEllipseviaNewPoint(), SketcherGui::makeTangentToArcOfHyperbolaviaNewPoint(), SketcherGui::makeTangentToArcOfParabolaviaNewPoint(), SketcherGui::makeTangentToEllipseviaNewPoint(), and SketcherGui::ViewProviderSketch::toggleWireSelelection().
getHighestVertexIndex()
int Sketcher::SketchObject::getHighestVertexIndex () const inline
Definition at line 562 of file SketchObject.h.
Referenced by SketcherGui::DrawSketchHandler::getHighestVertexIndex().
getInternalElementMap()
const std::map< std::string, std::string > SketchObject::getInternalElementMap () const
Get a map from internal element to the same geometry in normal shape.
Definition at line 408 of file SketchObject.cpp.
References Data::CheckGeometry, SplineSurface::i, femtools.tokrules::names, DrawingExample::Shape, Part::TopoShape::shapeName(), Data::SingleResult, Path.Post.scripts.grbl_post::type, and TestSpreadsheet::v.
getInternalGeometry()
const std::vector<Part::Geometry*>& Sketcher::SketchObject::getInternalGeometry () const inline
returns a list of all internal geometries
Definition at line 262 of file SketchObject.h.
Referenced by carbonCopy(), Sketcher::SketchAnalysis::detectMissingEqualityConstraints(), Sketcher::SketchAnalysis::detectMissingPointOnPointConstraints(), Sketcher::SketchAnalysis::detectMissingVerticalHorizontalConstraints(), and DrawSketchHandlerBSplineInsertKnot::releaseButton().
getInternalTypeState()
bool SketchObject::getInternalTypeState (const Constraint * cstr, Sketcher::InternalType::InternalType & internaltypestate) const protected
Definition at line 10580 of file SketchObject.cpp.
References Sketcher::Constraint::AlignmentType, Sketcher::BSplineControlPoint, Sketcher::InternalType::BSplineControlPoint, Sketcher::BSplineKnotPoint, Sketcher::InternalType::BSplineKnotPoint, Sketcher::EllipseFocus1, Sketcher::InternalType::EllipseFocus1, Sketcher::EllipseFocus2, Sketcher::InternalType::EllipseFocus2, Sketcher::EllipseMajorDiameter, Sketcher::InternalType::EllipseMajorDiameter, Sketcher::EllipseMinorDiameter, Sketcher::InternalType::EllipseMinorDiameter, Sketcher::HyperbolaFocus, Sketcher::InternalType::HyperbolaFocus, Sketcher::HyperbolaMajor, Sketcher::InternalType::HyperbolaMajor, Sketcher::HyperbolaMinor, Sketcher::InternalType::HyperbolaMinor, Sketcher::InternalAlignment, Sketcher::InternalType::None, Sketcher::NumInternalAlignmentType, Sketcher::ParabolaFocalAxis, Sketcher::InternalType::ParabolaFocalAxis, Sketcher::ParabolaFocus, Sketcher::InternalType::ParabolaFocus, Sketcher::Constraint::Type, and Sketcher::Undef.
getLabelDistance()
int SketchObject::getLabelDistance (int ConstrId, float & value)
get the label distance of the constraint
Definition at line 1031 of file SketchObject.cpp.
References SketcherExample::Constraints.
getLabelPosition()
int SketchObject::getLabelPosition (int ConstrId, float & value)
get the label position of the constraint
Definition at line 997 of file SketchObject.cpp.
References SketcherExample::Constraints.
getLastConflicting()
const std::vector<int>& Sketcher::SketchObject::getLastConflicting () const inline
gets the conflicting constraints of the last solver execution
Definition at line 680 of file SketchObject.h.
getLastDoF()
int Sketcher::SketchObject::getLastDoF () const inline
gets DoF of last solver execution
Definition at line 645 of file SketchObject.h.
Referenced by Sketcher::SketchAnalysis::solvesketch(), and SketcherGui::ViewProviderSketch::UpdateSolverInformation().
getLastHasConflicts()
bool Sketcher::SketchObject::getLastHasConflicts () const inline
gets HasConflicts status of last solver execution
Definition at line 650 of file SketchObject.h.
Referenced by Sketcher::SketchAnalysis::solvesketch(), and SketcherGui::ViewProviderSketch::UpdateSolverInformation().
getLastHasMalformedConstraints()
bool Sketcher::SketchObject::getLastHasMalformedConstraints () const inline
gets HasMalformedConstraints status of last solver execution
Definition at line 665 of file SketchObject.h.
Referenced by SketcherGui::ViewProviderSketch::UpdateSolverInformation().
getLastHasPartialRedundancies()
bool Sketcher::SketchObject::getLastHasPartialRedundancies () const inline
gets HasRedundancies status of last solver execution
Definition at line 660 of file SketchObject.h.
Referenced by SketcherGui::ViewProviderSketch::UpdateSolverInformation().
getLastHasRedundancies()
bool Sketcher::SketchObject::getLastHasRedundancies () const inline
gets HasRedundancies status of last solver execution
Definition at line 655 of file SketchObject.h.
Referenced by Sketcher::SketchAnalysis::solvesketch(), and SketcherGui::ViewProviderSketch::UpdateSolverInformation().
getLastMalformedConstraints()
const std::vector<int>& Sketcher::SketchObject::getLastMalformedConstraints () const inline
gets the redundant constraints of last solver execution
Definition at line 695 of file SketchObject.h.
getLastPartiallyRedundant()
const std::vector<int>& Sketcher::SketchObject::getLastPartiallyRedundant () const inline
gets the redundant constraints of last solver execution
Definition at line 690 of file SketchObject.h.
References Sketcher::Sketch::setRecalculateInitialSolutionWhileMovingPoint().
getLastRedundant()
const std::vector<int>& Sketcher::SketchObject::getLastRedundant () const inline
gets the redundant constraints of last solver execution
Definition at line 685 of file SketchObject.h.
getLastSolverStatus()
int Sketcher::SketchObject::getLastSolverStatus () const inline
gets solver status of last solver execution
Definition at line 670 of file SketchObject.h.
getLastSolveTime()
float Sketcher::SketchObject::getLastSolveTime () const inline
gets solver SolveTime of last solver execution
Definition at line 675 of file SketchObject.h.
getMemSize()
unsigned int SketchObject::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Reimplemented from App::PropertyContainer.
Definition at line 10085 of file SketchObject.cpp.
getMissingLineEqualityConstraints()
std::vector< ConstraintIds > & SketchObject::getMissingLineEqualityConstraints ()
Definition at line 11771 of file SketchObject.cpp.
getMissingPointOnPointConstraints()
std::vector< ConstraintIds > & SketchObject::getMissingPointOnPointConstraints ()
Definition at line 11761 of file SketchObject.cpp.
getMissingRadiusConstraints()
std::vector< ConstraintIds > & SketchObject::getMissingRadiusConstraints ()
Definition at line 11776 of file SketchObject.cpp.
getMissingVerticalHorizontalConstraints()
std::vector< ConstraintIds > & SketchObject::getMissingVerticalHorizontalConstraints ()
Definition at line 11766 of file SketchObject.cpp.
getOpenVertices()
std::vector< Base::Vector3d > SketchObject::getOpenVertices () const
Definition at line 11879 of file SketchObject.cpp.
getPoint() [1/2]
Base::Vector3d SketchObject::getPoint (const Part::Geometry * geo, PointPos PosId) static
retrieves the coordinates of a point
Definition at line 1532 of file SketchObject.cpp.
References Base::BaseClass::is().
Referenced by CmdSketcherConstrainLock::applyConstraint(), CmdSketcherConstrainDistance::applyConstraint(), CmdSketcherConstrainDistanceX::applyConstraint(), CmdSketcherConstrainDistanceY::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), DrawSketchHandlerDimension::createDistanceConstrain(), DrawSketchHandlerDimension::createDistanceXYConstrain(), horVerApplyConstraint(), SketcherGui::IsPointAlreadyOnCurve(), SketcherGui::SnapManager::snapToObject(), SketcherGui::ViewProviderSketch::toggleWireSelelection(), and DrawSketchHandlerDimension::updateDistanceType().
getPoint() [2/2]
Base::Vector3d SketchObject::getPoint (int GeoId, PointPos PosId) const
Definition at line 1564 of file SketchObject.cpp.
References draftguitools.gui_tool_utils::getPoint.
getPointForGeometry() [1/10]
template<class geomType > static Base::Vector3d Sketcher::SketchObject::getPointForGeometry (const geomType * geo, PointPos PosId) inline static
Definition at line 388 of file SketchObject.h.
getPointForGeometry() [2/10]
template<> Base::Vector3d Sketcher::SketchObject::getPointForGeometry (const Part::GeomArcOfCircle * aoc, PointPos PosId)
Definition at line 1441 of file SketchObject.cpp.
References Sketcher::end, Part::GeomArcOfConic::getCenter(), Part::GeomArcOfConic::getEndPoint(), Part::GeomArcOfConic::getStartPoint(), Sketcher::mid, and Sketcher::start.
getPointForGeometry() [3/10]
template<> Base::Vector3d Sketcher::SketchObject::getPointForGeometry (const Part::GeomArcOfEllipse * aoe, PointPos PosId)
Definition at line 1460 of file SketchObject.cpp.
References Sketcher::end, Part::GeomArcOfConic::getCenter(), Part::GeomArcOfConic::getEndPoint(), Part::GeomArcOfConic::getStartPoint(), Sketcher::mid, and Sketcher::start.
getPointForGeometry() [4/10]
template<> Base::Vector3d Sketcher::SketchObject::getPointForGeometry (const Part::GeomArcOfHyperbola * aoh, PointPos PosId)
Definition at line 1479 of file SketchObject.cpp.
References Sketcher::end, Part::GeomArcOfConic::getCenter(), Part::GeomArcOfConic::getEndPoint(), Part::GeomArcOfConic::getStartPoint(), Sketcher::mid, and Sketcher::start.
getPointForGeometry() [5/10]
template<> Base::Vector3d Sketcher::SketchObject::getPointForGeometry (const Part::GeomArcOfParabola * aop, PointPos PosId)
Definition at line 1498 of file SketchObject.cpp.
References Sketcher::end, Part::GeomArcOfConic::getCenter(), Part::GeomArcOfConic::getEndPoint(), Part::GeomArcOfConic::getStartPoint(), Sketcher::mid, and Sketcher::start.
getPointForGeometry() [6/10]
template<> Base::Vector3d Sketcher::SketchObject::getPointForGeometry (const Part::GeomBSplineCurve * bsp, PointPos PosId)
Definition at line 1517 of file SketchObject.cpp.
References Sketcher::end, Part::GeomBoundedCurve::getEndPoint(), Part::GeomBoundedCurve::getStartPoint(), and Sketcher::start.
getPointForGeometry() [7/10]
template<> Base::Vector3d Sketcher::SketchObject::getPointForGeometry (const Part::GeomCircle * circle, PointPos PosId)
Definition at line 1423 of file SketchObject.cpp.
References Sketcher::mid.
getPointForGeometry() [8/10]
template<> Base::Vector3d Sketcher::SketchObject::getPointForGeometry (const Part::GeomEllipse * ellipse, PointPos PosId)
Definition at line 1432 of file SketchObject.cpp.
References Sketcher::mid.
getPointForGeometry() [9/10]
template<> Base::Vector3d Sketcher::SketchObject::getPointForGeometry (const Part::GeomLineSegment * lineSeg, PointPos PosId)
Definition at line 1407 of file SketchObject.cpp.
References Sketcher::end, Part::GeomLineSegment::getEndPoint(), Part::GeomLineSegment::getStartPoint(), and Sketcher::start.
getPointForGeometry() [10/10]
template<> Base::Vector3d Sketcher::SketchObject::getPointForGeometry (const Part::GeomPoint * geomPoint, PointPos PosId)
Definition at line 1399 of file SketchObject.cpp.
References Sketcher::end, Part::GeomPoint::getPoint(), Sketcher::mid, and Sketcher::start.
getPyObject()
PyObject * SketchObject::getPyObject () override virtual
getPyObject returns the Python binding object
Returns
the Python binding object
Reimplemented from Part::Feature.
Definition at line 10076 of file SketchObject.cpp.
References Py::new_reference_to().
getRelatedGeometry()
std::vector< int > SketchObject::getRelatedGeometry (int GeoId) const
returns GeoId of all geometries projected from the same external geometry reference
Definition at line 8005 of file SketchObject.cpp.
References Sketcher::ExternalGeometryFacade::getFacade(), and Sketcher::RefExt.
getSolvedSketch()
const Sketch& Sketcher::SketchObject::getSolvedSketch () const inline
gets the solved sketch as a reference
Definition at line 702 of file SketchObject.h.
Referenced by DrawSketchHandlerDimension::isRadiusDoF(), SketcherGui::TaskSketcherSolverAdvanced::updateDefaultMethodParameters(), SketcherGui::TaskSketcherSolverAdvanced::updateRedundantMethodParameters(), and SketcherGui::TaskSketcherSolverAdvanced::updateSketchObject().
getSubObject()
App::DocumentObject * SketchObject::getSubObject (const char * subname, PyObject ** pyObj = 0, Base::Matrix4D * mat = 0, bool transform = true, int depth = 0) const override virtual
Get the sub element/object by name
Parameters
subname a string which is dot separated name to refer to a sub element or object. An empty string can be used to refer to the object itself
pyObj if non zero, returns the python object corresponding to this sub object. The actual type of this python object is implementation dependent. For example, The current implementation of Part::Feature will return the TopoShapePy, event if there is no sub-element reference, in which case it returns the whole shape.
mat If non zero, it is used as the current transformation matrix on input. And output as the accumulated transformation up until and include the transformation applied by the final object reference in subname. For Part::Feature, the transformation is applied to the TopoShape inside pyObj before returning.
transform if false, then it will not apply the object's own transformation to mat, which lets you override the object's placement (and possibly scale).
depth depth limitation as hint for cyclic link detection
Returns
The last document object referred in subname. If subname is empty, then it shall return itself. If subname is invalid, then it shall return zero.
Reimplemented from Part::Feature.
Definition at line 11162 of file SketchObject.cpp.
References SketcherExample::Constraints, dot(), DraftVecUtils::equals(), Data::findElementName(), Data::IndexedName::fromConst(), Data::MappedName::fromRawData(), Data::IndexedName::getIndex(), Sketcher::PropertyConstraintList::getIndexFromConstraintName(), draftguitools.gui_tool_utils::getPoint, Part::TopoShape::getShape(), Data::IndexedName::getType(), Data::ComplexGeoData::hasElementMap(), Sketcher::HAxis, Data::isMappedElement(), Part::TopoShape::isNull(), Py::new_reference_to(), Sketcher::none, updateLeaderLines::point, Part::TopoShape::resetElementMap(), Sketcher::RtPnt, Data::ComplexGeoData::setElementName(), DrawingExample::Shape, Part::shape2pyshape(), Part::TopoShape::shapeType(), Sketcher::start, Data::ComplexGeoData::Tag, Base::Placement::toMatrix(), Part::TopoShape::transformShape(), and Sketcher::VAxis.
getSymmetric()
std::vector< Part::Geometry * > SketchObject::getSymmetric (const std::vector< int > & geoIdList, std::map< int, int > & geoIdMap, std::map< int, bool > & isStartEndInverted, int refGeoId, Sketcher::PointPos refPosId = Sketcher::PointPos::none)
Definition at line 4911 of file SketchObject.cpp.
References KDL::atan2(), SCL.SimpleDataTypes::c, Base::Console(), SketcherExample::Constraints, Part::Geometry::copy(), Base::ConsoleSingleton::Error(), DraftVecUtils::find(), Base::fmod(), Sketcher::GeoUndef, Sketcher::GeometryFacade::getFacade(), draftguitools.gui_tool_utils::getPoint, Part::GeomBSplineCurve::getPoles(), Sketcher::InternalAlignment, Base::BaseClass::is(), M_PI, Sketcher::none, Base::Vector3< float_type >::Perpendicular(), SCL.BaseType::scp, KDL::sqrt(), Sketcher::start, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
getVertexIndexGeoPos()
int SketchObject::getVertexIndexGeoPos (int GeoId, PointPos PosId) const
retrieves for a GeoId and PosId the Vertex number
Definition at line 10911 of file SketchObject.cpp.
References SplineSurface::i.
Referenced by SketcherGui::TaskSketcherElements::onListWidgetElementsMouseMoveOnItem().
getViewProviderName()
const char* Sketcher::SketchObject::getViewProviderName () const inline override virtual
returns the type name of the ViewProvider
Reimplemented from Part::Part2DObject.
Definition at line 121 of file SketchObject.h.
getVirtualSpace()
int SketchObject::getVirtualSpace (int ConstrId, bool & isinvirtualspace) const
get the driving status of this constraint
Definition at line 1267 of file SketchObject.cpp.
References SketcherExample::Constraints.
handleChangedPropertyType()
void SketchObject::handleChangedPropertyType (Base::XMLReader & reader, const char * TypeName, App::Property * prop) override virtual
Extends the rules for handling property type changed, so that extensions are given an opportunity to handle it. If an extension handles a change, neither the rest of the extensions, nor the container itself get to handle it.
Extensions get their extensionHandleChangedPropertyType() called.
If no extension handles the request, then the containers handleChangedPropertyType() is called.
Reimplemented from App::ExtensionContainer.
Definition at line 10134 of file SketchObject.cpp.
References TechDrawTools.TaskFillTemplateFields::reader.
hasConflicts()
int SketchObject::hasConflicts () const
returns non zero if the sketch contains conflicting constraints
Definition at line 480 of file SketchObject.cpp.
Referenced by SketcherGui::EditDatumDialog::exec().
hasInternalGeometry()
bool SketchObject::hasInternalGeometry (const Part::Geometry * geo) static
Definition at line 1726 of file SketchObject.cpp.
References Base::BaseClass::is().
increaseBSplineDegree()
bool SketchObject::increaseBSplineDegree (int GeoId, int degreeincrement = 1)
Increases the degree of a BSpline by degreeincrement, which defaults to 1.
Parameters
GeoId - the geometry of type bspline to increase the degree
degreeincrement - the increment in number of degrees to effect
Return values
bool - returns true if the increase in degree succeeded, or false if it did not succeed.
Definition at line 6928 of file SketchObject.cpp.
References Base::Console(), Sketcher::GeometryFacade::copyId(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), SketcherExample::Geometry, Base::Persistence::getClassTypeId(), Base::Persistence::getTypeId(), Handle(), and Path.Post.scripts.opensbp_post::move().
initExternalGeo()
void SketchObject::initExternalGeo () protected
Definition at line 227 of file SketchObject.cpp.
References Sketcher::GeometryTypedFacade< GeometryT >::getTypedFacade(), and Path.Post.scripts.opensbp_post::move().
initTemporaryBSplinePieceMove()
int Sketcher::SketchObject::initTemporaryBSplinePieceMove (int geoId, PointPos pos, const Base::Vector3d & firstPoint, bool fine = true) inline
Forwards a request for a temporary initBSplinePieceMove to the solver using the current sketch state as a reference (enables dragging)
Definition at line 1111 of file SketchObject.h.
initTemporaryMove() [1/2]
int Sketcher::SketchObject::initTemporaryMove (int geoId, PointPos pos, bool fine = true) inline
Definition at line 1105 of file SketchObject.h.
References Sketcher::Sketch::moveGeometries().
initTemporaryMove() [2/2]
int Sketcher::SketchObject::initTemporaryMove (std::vector< GeoElementId > moved, bool fine = true) inline
Forwards a request for a temporary initMove to the solver using the current sketch state as a reference (enables dragging)
Definition at line 1096 of file SketchObject.h.
References solve().
insertBSplineKnot()
bool SketchObject::insertBSplineKnot (int GeoId, double param, int multiplicity = 1)
Inserts a knot in the BSpline at param with given multiplicity. If the knot already exists, its multiplicity is increased by multiplicity.
Parameters
GeoId - the geometry of type bspline to increase the degree
param - the parameter value where the knot is to be placed
multiplicity - multiplicity of the inserted knot
Return values
bool - returns true if the operation succeeded, or false if it did not succeed.
Definition at line 7207 of file SketchObject.cpp.
References Sketcher::BSplineControlPoint, Sketcher::BSplineKnotPoint, Sketcher::Constraint::clone(), Part::Geometry::clone(), Base::Console(), SketcherExample::Constraints, Part::GeomBSplineCurve::countKnots(), Part::GeomBSplineCurve::countPoles(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), SketcherExample::Geometry, Base::Persistence::getClassTypeId(), Part::GeomBSplineCurve::getDegree(), Part::GeomCurve::getFirstParameter(), Part::GeomBSplineCurve::getKnots(), Part::GeomCurve::getLastParameter(), Part::GeomBSplineCurve::getPoles(), Base::Persistence::getTypeId(), SplineSurface::i, Sketcher::InternalAlignment, Sketcher::Constraint::InternalAlignmentIndex, Path.Post.scripts.opensbp_post::move(), Init::param, Arch::QT_TRANSLATE_NOOP, and THROWMT.
internalPrefix()
const std::string & SketchObject::internalPrefix () static
Definition at line 11369 of file SketchObject.cpp.
inverseAngleConstraint()
void SketchObject::inverseAngleConstraint (Constraint * constr)
Definition at line 1137 of file SketchObject.cpp.
References Sketcher::end, Sketcher::Constraint::FirstPos, Sketcher::Constraint::SecondPos, and Sketcher::start.
isAllowedOtherBody()
bool Sketcher::SketchObject::isAllowedOtherBody () const inline
Flag to allow external geometry from other bodies than the one this sketch belongs to.
Definition at line 746 of file SketchObject.h.
isAllowedUnaligned()
bool Sketcher::SketchObject::isAllowedUnaligned () const inline
Flag to allow carbon copy from misaligned geometry.
Definition at line 756 of file SketchObject.h.
isCarbonCopyAllowed()
bool SketchObject::isCarbonCopyAllowed (App::Document * pDoc, App::DocumentObject * pObj, bool & xinv, bool & yinv, eReasonList * rsn = nullptr) const
Definition at line 4554 of file SketchObject.cpp.
References Base::Console(), dot(), SCL.SimpleDataTypes::e, Part::BodyBase::findBodyOf(), Base::Persistence::getClassTypeId(), getExternalGeometryCount(), Base::Type::getName(), App::Part::getPartOfObject(), Base::Placement::getPosition(), Base::Placement::getRotation(), Base::Persistence::getTypeId(), App::PropertyPlacement::getValue(), Base::Rotation::multVec(), App::GeoFeature::Placement, and Base::ConsoleSingleton::Warning().
isClosedCurve()
bool SketchObject::isClosedCurve (const Part::Geometry * geo) static
Definition at line 1718 of file SketchObject.cpp.
References Base::BaseClass::is(), and Part::GeomBSplineCurve::isPeriodic().
isCoincidentWithExternalGeometry()
void SketchObject::isCoincidentWithExternalGeometry (int GeoId, bool & start_external, bool & mid_external, bool & end_external)
Definition at line 9559 of file SketchObject.cpp.
References Sketcher::end, Sketcher::mid, and Sketcher::start.
isExternalAllowed()
bool SketchObject::isExternalAllowed (App::Document * pDoc, App::DocumentObject * pObj, eReasonList * rsn = nullptr) const
Return true if this object is allowed as external geometry for the sketch. rsn argument receives the reason for disallowing.
Definition at line 4498 of file SketchObject.cpp.
References Base::Console(), SCL.SimpleDataTypes::e, Part::BodyBase::findBodyOf(), App::Part::getPartOfObject(), and Base::ConsoleSingleton::Warning().
isPerformingInternalTransaction()
bool Sketcher::SketchObject::isPerformingInternalTransaction () const inline
Definition at line 837 of file SketchObject.h.
isPointOnCurve()
bool SketchObject::isPointOnCurve (int geoIdCurve, double px, double py)
Definition at line 10022 of file SketchObject.cpp.
References Sketcher::Sketch::addGeometry(), Sketcher::Sketch::addPoint(), Sketcher::Sketch::addPointOnObjectConstraint(), Sketcher::Sketch::calculateConstraintError(), Sketcher::Sketch::getSolverPrecision(), buildPsets::p, Sketcher::start, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by SketcherGui::IsPointAlreadyOnCurve().
isSupportedGeometry()
bool SketchObject::isSupportedGeometry (const Part::Geometry * geo) const
Returns true if the sketcher supports the given geometry.
Parameters
geo - the geometry
Return values
bool - true if the geometry is supported
Definition at line 1618 of file SketchObject.cpp.
References Handle(), Base::BaseClass::is(), and Materials::trim().
join()
int SketchObject::join (int geoId1, Sketcher::PointPos posId1, int geoId2, Sketcher::PointPos posId2, int continuity = 0)
Join one or two curves at the given end points.
The combined curve will be a b-spline
Parameters
geoId1,posId1,geoId2,posId2 the end points to join
Return values
- 0 on success, -1 on failure
Definition at line 4335 of file SketchObject.cpp.
References Sketcher::end, Sketcher::GeometryFacade::getConstruction(), Base::Vector3< float_type >::Length(), Path.Post.scripts.opensbp_post::move(), draftfunctions.offset::offset(), Sketcher::start, and THROWM.
makeMissingEquality()
void SketchObject::makeMissingEquality (bool onebyone = true)
Definition at line 11821 of file SketchObject.cpp.
makeMissingPointOnPointCoincident()
void SketchObject::makeMissingPointOnPointCoincident (bool onebyone = false)
Definition at line 11805 of file SketchObject.cpp.
makeMissingVerticalHorizontal()
void SketchObject::makeMissingVerticalHorizontal (bool onebyone = false)
Definition at line 11813 of file SketchObject.cpp.
migrateSketch()
void SketchObject::migrateSketch () protected
Definition at line 10708 of file SketchObject.cpp.
References Sketcher::Constraint::AlignmentType, Sketcher::BSplineControlPoint, SCL.SimpleDataTypes::c, Sketcher::Coincident, Base::Console(), SketcherExample::Constraints, Part::GeometryMigrationExtension::Construction, Base::ConsoleSingleton::Critical(), Sketcher::Diameter, create_qrc::ext, Sketcher::Constraint::First, Sketcher::Constraint::FirstPos, toolbit-attributes::g, SketcherExample::Geometry, Base::BaseClass::getClassTypeId(), Sketcher::GeometryFacade::getFacade(), Part::GeomBSplineCurve::getWeights(), SplineSurface::i, Sketcher::InternalAlignment, Sketcher::mid, Path.Post.scripts.opensbp_post::move(), Sketcher::none, Sketcher::ParabolaFocalAxis, Sketcher::ParabolaFocus, Arch::QT_TRANSLATE_NOOP, Sketcher::Radius, Sketcher::Constraint::Second, Sketcher::Constraint::SecondPos, Sketcher::GeometryFacade::setConstruction(), Sketcher::start, Sketcher::Constraint::Type, and Sketcher::Weight.
modifyBSplineKnotMultiplicity()
bool SketchObject::modifyBSplineKnotMultiplicity (int GeoId, int knotIndex, int multiplicityincr = 1)
Increases or Decreases the multiplicity of a BSpline knot by the multiplicityincr param, which defaults to 1, if the result is multiplicity zero, the knot is removed.
Parameters
GeoId - the geometry of type bspline to increase the degree
knotIndex - the index of the knot to modify (note that index is OCC consistent, so 1<=knotindex<=knots)
multiplicityincr - the increment (positive value) or decrement (negative value) of multiplicity of the knot
Return values
bool - returns true if the operation succeeded, or false if it did not succeed.
Definition at line 7023 of file SketchObject.cpp.
References Sketcher::BSplineControlPoint, Sketcher::BSplineKnotPoint, Sketcher::Constraint::clone(), Part::Geometry::clone(), Base::Console(), SketcherExample::Constraints, Sketcher::GeometryFacade::copyId(), Part::GeomBSplineCurve::countKnots(), Part::GeomBSplineCurve::countPoles(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), SketcherExample::Geometry, Base::Persistence::getClassTypeId(), Part::GeomBSplineCurve::getDegree(), Part::GeomBSplineCurve::getKnots(), Part::GeomBSplineCurve::getMultiplicity(), Part::GeomBSplineCurve::getPoles(), Base::Persistence::getTypeId(), SplineSurface::i, Sketcher::InternalAlignment, Sketcher::Constraint::InternalAlignmentIndex, Path.Post.scripts.opensbp_post::move(), Arch::QT_TRANSLATE_NOOP, result, and THROWMT.
moveDatumsToEnd()
int SketchObject::moveDatumsToEnd ()
Move Dimensional constraints at the end of the properties array.
Definition at line 1078 of file SketchObject.cpp.
References SketcherExample::Constraints, Drawing::copy(), SplineSurface::i, and Path.Post.scripts.opensbp_post::move().
moveGeometries()
int SketchObject::moveGeometries (std::vector< GeoElementId > geoEltIds, const Base::Vector3d & toPoint, bool relative = false, bool updateGeoBeforeMoving = false)
move this point to a new location and solve
Definition at line 1340 of file SketchObject.cpp.
References SketcherExample::Constraints, and SketcherExample::Geometry.
moveGeometriesTemporary()
int Sketcher::SketchObject::moveGeometriesTemporary (std::vector< GeoElementId > moved, Base::Vector3d toPoint, bool relative = false) inline
Forwards a request for point or curve temporary movement to the solver using the current state as a reference (enables dragging). NOTE: A temporary move operation must always be preceded by a initTemporaryMove() operation.
Definition at line 1126 of file SketchObject.h.
moveGeometry()
int SketchObject::moveGeometry (int GeoId, PointPos PosId, const Base::Vector3d & toPoint, bool relative = false, bool updateGeoBeforeMoving = false)
Definition at line 1391 of file SketchObject.cpp.
References RobotExample::pos.
moveGeometryTemporary()
int Sketcher::SketchObject::moveGeometryTemporary (int geoId, PointPos pos, Base::Vector3d toPoint, bool relative = false) inline
Definition at line 1132 of file SketchObject.h.
mustExecute()
short SketchObject::mustExecute () const override virtual
mustExecute We call this method to check if the object was modified to be invoked. If the object label or an argument is modified. If we must recompute the object - to call the method execute(). 0: no recomputation is needed 1: recomputation needed
Remarks
If an object is marked as 'touched' then this does not necessarily mean that it will be recomputed. It only means that all objects that link it (i.e. its InList) will be recomputed.
Reimplemented from Part::Feature.
Definition at line 244 of file SketchObject.cpp.
References SketcherExample::Constraints, and SketcherExample::Geometry.
onChanged()
void SketchObject::onChanged (const App::Property * prop) override protected virtual
get called by the container when a property has changed
Reimplemented from Part::Feature.
Definition at line 10153 of file SketchObject.cpp.
References checkMigration(), Base::Console(), SketcherExample::Constraints, Part::GeometryMigrationExtension::Construction, Sketcher::ExternalGeometryExtension::Detached, toolbit-attributes::doc, SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), create_qrc::ext, Part::GeometryMigrationExtension::ExternalReference, FC_ERR, FC_WARN, SketcherExample::Geometry, Part::GeometryMigrationExtension::GeometryId, Base::Persistence::getClassTypeId(), Base::BaseClass::getClassTypeId(), Sketcher::ExternalGeometryFacade::getFacade(), Sketcher::GeometryFacade::getFacade(), SplineSurface::i, Gui::isRestoring, OpenSCADFeatures::long, Sketcher::ExternalGeometryExtension::Missing, replaceobj::objs, Part::Feature::onChanged(), App::PendingTransactionUpdate, Arch::QT_TRANSLATE_NOOP, importers.importIFCmulticore::subs, App::Property::testStatus(), and App::Property::User3.
onDocumentRestored()
void SketchObject::onDocumentRestored () override protected virtual
get called after a document has been fully restored
Reimplemented from App::DocumentObject.
Definition at line 10641 of file SketchObject.cpp.
References App::DocumentObject::onDocumentRestored().
onUndoRedoFinished()
void SketchObject::onUndoRedoFinished () override protected virtual
get called after an undo/redo transaction is finished
Reimplemented from App::DocumentObject.
Definition at line 10536 of file SketchObject.cpp.
References SketcherExample::Constraints.
onUpdateElementReference()
void SketchObject::onUpdateElementReference (const App::Property * prop) override protected virtual
Reimplemented from App::DocumentObject.
Definition at line 10417 of file SketchObject.cpp.
performActionByGeomType()
template<typename returnType > returnType Sketcher::SketchObject::performActionByGeomType (const Part::Geometry * geo)
port_reversedExternalArcs()
int SketchObject::port_reversedExternalArcs (bool justAnalyze)
porting functions
SketchObject::port_reversedExternalArcs finds constraints that link to endpoints of external-geometry arcs, and swaps the endpoints in the constraints. This is needed after CCW emulation was introduced, to port old sketches.
Parameters
justAnalyze if true, nothing is actually done - only the number of constraints to be affected is returned.
Returns
the number of constraints changed/to be changed.
Definition at line 10972 of file SketchObject.cpp.
References Sketcher::Constraint::clone(), Base::Console(), SketcherExample::Constraints, Sketcher::end, Sketcher::Constraint::First, Sketcher::Constraint::FirstPos, toolbit-attributes::g, Part::GeomArcOfConic::isReversed(), Base::ConsoleSingleton::Log(), Path.Post.scripts.opensbp_post::move(), Sketcher::none, Sketcher::RefExt, Sketcher::Constraint::Second, Sketcher::Constraint::SecondPos, Sketcher::start, Sketcher::Constraint::Third, and Sketcher::Constraint::ThirdPos.
rebuildExternalGeometry()
void SketchObject::rebuildExternalGeometry (std::optional< ExternalToAdd > extToAdd = std::nullopt)
rebuilds external geometry (projection onto the sketch plane)
Definition at line 8907 of file SketchObject.cpp.
References Sketcher::Both, SketcherExample::Constraints, Sketcher::ExternalGeometryFacade::copyFlags(), Sketcher::ExternalGeometryExtension::Defining, SCL.SimpleDataTypes::e, Sketcher::end, KDL::exp(), importers.importIFClegacy::explorer(), SCL.SimpleDataTypes::f, FC_ERR, FC_THROWM, FC_WARN, fitArcs(), Sketcher::ExternalGeometryExtension::Frozen, Sketcher::ExternalGeometryFacade::getFacade(), Sketcher::GeometryFacade::getId(), App::DocumentObject::getNameInDocument(), Base::Placement::getPosition(), Base::Placement::getRotation(), Part::Datum::getShape(), Part::TopoShape::getShape(), Part::TopoShape::getSubShape(), Part::TopoShape::getSubShapes(), Part::TopoShape::getSubTopoShapes(), Handle(), App::GeoFeature::hasMissingElement(), SplineSurface::i, Sketcher::Intersection, intersection(), Base::Placement::inverse(), Base::Rotation::inverse(), Base::BaseClass::isDerivedFrom(), FreeCADInit::Length, M_PI_2, Sketcher::ExternalGeometryExtension::Missing, Path.Post.scripts.opensbp_post::move(), Base::Placement::multVec(), Base::Rotation::multVec(), App::ElementNamePair::oldName, buildPsets::p, Base::Placement::Placement(), WorkingPlane::plane, updateLeaderLines::point, RobotExample::pos, Sketcher::Projection, importDXF::projectShape(), App::GeoFeature::resolveElement(), toolbit-attributes::s, Sketcher::GeometryFacade::setConstruction(), Sketcher::GeometryFacade::setId(), Sketcher::start, Sketcher::ExternalGeometryExtension::Sync, Base::Placement::toMatrix(), Path.Base.Gui.PropertyEditor::Types(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
rebuildVertexIndex()
void SketchObject::rebuildVertexIndex ()
Definition at line 9416 of file SketchObject.cpp.
References Sketcher::end, SplineSurface::i, Sketcher::mid, and Sketcher::start.
removeAxesAlignment()
int SketchObject::removeAxesAlignment (const std::vector< int > & geoIdList)
Definition at line 5838 of file SketchObject.cpp.
References draftmake.make_clone::clone, SketcherExample::Constraints, Sketcher::Distance, Sketcher::DistanceX, Sketcher::DistanceY, Sketcher::GeoUndef, Sketcher::HAxis, Sketcher::Horizontal, SplineSurface::i, Path.Post.scripts.opensbp_post::move(), Sketcher::none, Sketcher::Parallel, Sketcher::Perpendicular, Sketcher::PointOnObject, FreeCADInit::Second, Sketcher::Symmetric, Sketcher::VAxis, and Sketcher::Vertical.
removeDegeneratedGeometries()
int SketchObject::removeDegeneratedGeometries (double tolerance)
Remove degenerated geometries.
Definition at line 11834 of file SketchObject.cpp.
References draftutils.utils::tolerance().
renameConstraint()
int SketchObject::renameConstraint (int GeoId, std::string name)
Definition at line 11855 of file SketchObject.cpp.
References Sketcher::Constraint::clone(), SketcherExample::Constraints, and Sketcher::Constraint::Name.
Restore()
void SketchObject::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from Part::Part2DObject.
Definition at line 10128 of file SketchObject.cpp.
References TechDrawTools.TaskFillTemplateFields::reader, and Part::Part2DObject::Restore().
restoreFinished()
void SketchObject::restoreFinished () override protected virtual
This method is used at the end of restoreFromStream() after all data files have been read in. A subclass can set up some internals. The default implementation does nothing.
Reimplemented from Base::Persistence.
Definition at line 10651 of file SketchObject.cpp.
References SketcherExample::Constraints, SCL.SimpleDataTypes::e, FC_ERR, FC_WARN, SplineSurface::id, Sketcher::Constraint::isDimensional(), DrawingExample::Shape, and TestSpreadsheet::v.
retrieveSolverDiagnostics()
void SketchObject::retrieveSolverDiagnostics () protected
Definition at line 490 of file SketchObject.cpp.
reverseAngleConstraintExpression()
std::string SketchObject::reverseAngleConstraintExpression (std::string expression) static
Modify an angle constraint expression string to its supplementary angle.
Definition at line 1180 of file SketchObject.cpp.
reverseAngleConstraintToSupplementary()
void SketchObject::reverseAngleConstraintToSupplementary (Constraint * constr, int constNum)
Change an angle constraint to its supplementary angle.
Definition at line 1115 of file SketchObject.cpp.
References Sketcher::end, Sketcher::Constraint::First, Sketcher::Constraint::FirstPos, Sketcher::Constraint::getValue(), M_PI, Sketcher::Constraint::Second, Sketcher::Constraint::SecondPos, Sketcher::Constraint::setValue(), and Sketcher::start.
Save()
void SketchObject::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Reimplemented from App::DocumentObject.
Definition at line 10090 of file SketchObject.cpp.
References Sketcher::ExternalGeometryFacade::getFacade(), and App::DocumentObject::Save().
seekTrimPoints()
bool SketchObject::seekTrimPoints (int GeoId, const Base::Vector3d & point, int & GeoId1, Base::Vector3d & intersect1, int & GeoId2, Base::Vector3d & intersect2)
retrieves intersection points of this curve with the closest two curves around a point of this curve.
it includes internal and external intersecting geometry.
it returns GeoEnum::GeoUndef if no intersection is found.
Definition at line 3442 of file SketchObject.cpp.
Referenced by trim().
setActive()
int SketchObject::setActive (int ConstrId, bool isactive)
set the driving status of this constraint and solve
Definition at line 914 of file SketchObject.cpp.
References Sketcher::Constraint::clone(), SketcherExample::Constraints, Sketcher::Constraint::isActive, and Path.Post.scripts.opensbp_post::move().
setAllowOtherBody()
void Sketcher::SketchObject::setAllowOtherBody (bool on) inline
Definition at line 750 of file SketchObject.h.
setAllowUnaligned()
void Sketcher::SketchObject::setAllowUnaligned (bool on) inline
Definition at line 760 of file SketchObject.h.
setConstraintExpression()
void SketchObject::setConstraintExpression (int constNum, const std::string & newExpression)
Definition at line 1165 of file SketchObject.cpp.
References Base::Console(), SketcherExample::Constraints, Base::ConsoleSingleton::Error(), Path.Log::info(), App::Expression::parse(), and src.Mod.Test.testPathArray::path.
setConstruction()
int SketchObject::setConstruction (int GeoId, bool on)
Definition at line 2018 of file SketchObject.cpp.
References Sketcher::ExternalGeometryExtension::Defining, SketcherExample::Geometry, Sketcher::ExternalGeometryFacade::getFacade(), Part::PropertyGeometryList::getValues(), Path.Post.scripts.opensbp_post::move(), Sketcher::RefExt, Part::PropertyGeometryList::set1Value(), and Sketcher::GeometryFacade::setConstruction().
setDatum()
int SketchObject::setDatum (int ConstrId, double Datum)
set the datum of a Distance or Angle constraint and solve
Definition at line 813 of file SketchObject.cpp.
References SketcherExample::Constraints, Sketcher::Diameter, Sketcher::Distance, Path.Post.scripts.opensbp_post::move(), Sketcher::Perpendicular, Sketcher::Radius, Sketcher::Tangent, Path.Post.scripts.grbl_post::type, and Sketcher::Weight.
setDatumsDriving()
int SketchObject::setDatumsDriving (bool isdriving)
Make all dimensionals Driving/non-Driving.
Definition at line 1046 of file SketchObject.cpp.
References SketcherExample::Constraints, SplineSurface::i, and Path.Post.scripts.opensbp_post::move().
setDriving()
int SketchObject::setDriving (int ConstrId, bool isdriving)
set the driving status of this constraint and solve
Definition at line 851 of file SketchObject.cpp.
References SketcherExample::Constraints, and Path.Post.scripts.opensbp_post::move().
setExpression()
void SketchObject::setExpression (const App::ObjectIdentifier & path, std::shared_ptr< App::Expression > expr) override
Definition at line 11345 of file SketchObject.cpp.
References SCL.SimpleDataTypes::e, and FC_ERR.
setGeometry()
int SketchObject::setGeometry (int GeoId, const Part::Geometry * geo)
Definition at line 8093 of file SketchObject.cpp.
References Part::Geometry::clone(), toolbit-attributes::g, SketcherExample::Geometry, Path.Post.scripts.opensbp_post::move(), and Sketcher::RefExt.
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_readme_browser.WidgetReadmeBrowser::setMarkdown().
setGeometryId()
int SketchObject::setGeometryId (int GeoId, long id)
Definition at line 11891 of file SketchObject.cpp.
References SketcherExample::Geometry, Sketcher::GeometryFacade::getFacade(), SplineSurface::i, and Path.Post.scripts.opensbp_post::move().
setLabelDistance()
int SketchObject::setLabelDistance (int ConstrId, float value)
set the label distance of the constraint
Definition at line 1010 of file SketchObject.cpp.
References Sketcher::Constraint::clone(), SketcherExample::Constraints, Sketcher::Constraint::LabelDistance, and Path.Post.scripts.opensbp_post::move().
setLabelPosition()
int SketchObject::setLabelPosition (int ConstrId, float value)
set the label position of the constraint
Definition at line 976 of file SketchObject.cpp.
References Sketcher::Constraint::clone(), SketcherExample::Constraints, Sketcher::Constraint::LabelPosition, and Path.Post.scripts.opensbp_post::move().
setMissingLineEqualityConstraints()
void SketchObject::setMissingLineEqualityConstraints (std::vector< ConstraintIds > & cl)
Definition at line 11787 of file SketchObject.cpp.
setMissingPointOnPointConstraints()
void SketchObject::setMissingPointOnPointConstraints (std::vector< ConstraintIds > & cl)
Definition at line 11799 of file SketchObject.cpp.
setMissingRadiusConstraints()
void SketchObject::setMissingRadiusConstraints (std::vector< ConstraintIds > & cl)
Definition at line 11781 of file SketchObject.cpp.
setMissingVerticalHorizontalConstraints()
void SketchObject::setMissingVerticalHorizontalConstraints (std::vector< ConstraintIds > & cl)
Definition at line 11793 of file SketchObject.cpp.
setRecalculateInitialSolutionWhileMovingPoint()
void Sketcher::SketchObject::setRecalculateInitialSolutionWhileMovingPoint (bool recalculateInitialSolutionWhileMovingPoint) inline
enables/disables solver initial solution recalculation when moving point mode (useful for dragging)
Definition at line 709 of file SketchObject.h.
Referenced by SketcherGui::ViewProviderSketch::setEdit().
setupObject()
void SketchObject::setupObject () override virtual
get called after a brand new object was created
Reimplemented from App::DocumentObject.
Definition at line 218 of file SketchObject.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetFloat(), and App::Application::GetParameterGroupByPath().
setUpSketch()
int SketchObject::setUpSketch ()
sets the geometry of sketchObject as the solvedsketch geometry returns the DoF of such a geometry.
Definition at line 1306 of file SketchObject.cpp.
References SketcherExample::Constraints.
Referenced by Sketcher::SketchAnalysis::solvesketch().
setVirtualSpace() [1/2]
int SketchObject::setVirtualSpace (int ConstrId, bool isinvirtualspace)
set the driving status of this constraint and solve
Definition at line 1204 of file SketchObject.cpp.
References Sketcher::Constraint::clone(), SketcherExample::Constraints, Sketcher::Constraint::isInVirtualSpace, and Path.Post.scripts.opensbp_post::move().
setVirtualSpace() [2/2]
int SketchObject::setVirtualSpace (std::vector< int > constrIds, bool isinvirtualspace)
set the driving status of a group of constraints at once
Definition at line 1231 of file SketchObject.cpp.
References Sketcher::Constraint::clone(), SketcherExample::Constraints, Sketcher::Constraint::isInVirtualSpace, and Path.Post.scripts.opensbp_post::move().
shapeTypeFromGeoId()
Data::IndexedName SketchObject::shapeTypeFromGeoId (int GeoId, PointPos pos = Sketcher::PointPos::none) const
Definition at line 11579 of file SketchObject.cpp.
References Data::IndexedName::fromConst(), Base::Persistence::getClassTypeId(), Sketcher::HAxis, Sketcher::none, Sketcher::start, and Sketcher::VAxis.
solve()
int SketchObject::solve (bool updateGeoAfterSolving = true)
solves the sketch and updates the geometry, but not all the dependent features (does not recompute) When a recompute is necessary, recompute triggers execute() which solves the sketch and updates all dependent features When a solve only is necessary (e.g. DoF changed), solve() solves the sketch and updates the geometry (if updateGeoAfterSolving==true), but does not trigger any recompute.
Returns
0 if no error, if error, the following codes in this order of priority: -4 if overconstrained, -3 if conflicting constraints, -5 if malformed constraints, -1 if solver error, -2 if redundant constraints
Definition at line 502 of file SketchObject.cpp.
References Base::Console(), SketcherExample::Constraints, Base::ConsoleSingleton::Error(), GCS::Failed, SketcherExample::Geometry, Path.Post.scripts.opensbp_post::move(), Arch::QT_TRANSLATE_NOOP, Part::PropertyGeometryList::setValues(), and Base::ConsoleSingleton::Warning().
Referenced by initTemporaryMove(), DrawSketchHandlerDimension::isRadiusDoF(), SketcherGui::ViewProviderSketch::onDelete(), DrawSketchHandlerDimension::restartCommand(), SketcherGui::ViewProviderSketch::setEdit(), Sketcher::SketchAnalysis::solvesketch(), CmdSketcherConstrainTangent::substituteConstraintCombinations(), SketcherGui::tryAutoRecompute(), and SketcherGui::tryAutoRecomputeIfNotSolve().
split()
int SketchObject::split (int geoId, const Base::Vector3d & point)
split a curve
Definition at line 4047 of file SketchObject.cpp.
References Part::GeomCurve::closestParameter(), Sketcher::Coincident, SketcherExample::Constraints, Part::Geometry::copy(), Sketcher::end, Sketcher::Constraint::First, Sketcher::Constraint::FirstPos, Sketcher::GeoUndef, Base::Persistence::getClassTypeId(), Sketcher::GeometryFacade::getConstruction(), Part::GeomBoundedCurve::getEndPoint(), Part::GeomCurve::getFirstParameter(), Part::GeomCurve::getLastParameter(), Part::GeomBoundedCurve::getStartPoint(), Handle(), SplineSurface::i, Base::BaseClass::is(), Base::BaseClass::isDerivedFrom(), Part::GeomBSplineCurve::isPeriodic(), Sketcher::mid, Path.Post.scripts.opensbp_post::move(), Sketcher::Constraint::Second, Sketcher::Constraint::SecondPos, Sketcher::start, THROWM, and Sketcher::Constraint::Type.
supportedGeometry()
std::vector< Part::Geometry * > SketchObject::supportedGeometry (const std::vector< Part::Geometry * > & geoList) const protected
Returns a list of supported geometries from the input list.
Parameters
geoList - the geometry list
Return values
list - the supported geometry list
Definition at line 1643 of file SketchObject.cpp.
syncGeometry()
int SketchObject::syncGeometry (const std::vector< int > & geoIds)
Sync frozen external geometries.
Definition at line 8026 of file SketchObject.cpp.
References Sketcher::ExternalGeometryExtension::Frozen, Sketcher::ExternalGeometryFacade::getFacade(), Path.Post.scripts.opensbp_post::move(), Sketcher::RefExt, and Sketcher::ExternalGeometryExtension::Sync.
synchroniseGeometryState()
void SketchObject::synchroniseGeometryState () protected
Definition at line 10552 of file SketchObject.cpp.
References SketcherExample::Constraints, Sketcher::Constraint::First, Sketcher::GeometryFacade::getFacade(), SplineSurface::i, and Sketcher::InternalType::None.
testDrivingChange()
int SketchObject::testDrivingChange (int ConstrId, bool isdriving) protected
Definition at line 894 of file SketchObject.cpp.
References SketcherExample::Constraints, and FreeCADInit::Second.
toggleActive()
int SketchObject::toggleActive (int ConstrId)
toggle the driving status of this constraint
Definition at line 951 of file SketchObject.cpp.
References Sketcher::Constraint::clone(), SketcherExample::Constraints, Sketcher::Constraint::isActive, and Path.Post.scripts.opensbp_post::move().
toggleConstruction()
int SketchObject::toggleConstruction (int GeoId)
toggle geometry to draft line
Definition at line 1976 of file SketchObject.cpp.
References Sketcher::ExternalGeometryExtension::Defining, SketcherExample::Geometry, Sketcher::ExternalGeometryFacade::getFacade(), Sketcher::GeometryFacade::getFacade(), and Sketcher::RefExt.
toggleDriving()
int Sketcher::SketchObject::toggleDriving (int ConstrId) inline
toggle the driving status of this constraint
Definition at line 325 of file SketchObject.h.
toggleExternalGeometryFlag()
int SketchObject::toggleExternalGeometryFlag (const std::vector< int > & geoIds, const std::vector< ExternalGeometryExtension::Flag > & flags) protected
Definition at line 2055 of file SketchObject.cpp.
References Sketcher::ExternalGeometryExtension::Frozen, Sketcher::ExternalGeometryFacade::getFacade(), SplineSurface::i, and Sketcher::RefExt.
toggleVirtualSpace()
int SketchObject::toggleVirtualSpace (int ConstrId)
toggle the driving status of this constraint
Definition at line 1278 of file SketchObject.cpp.
References Sketcher::Constraint::clone(), SketcherExample::Constraints, Sketcher::Constraint::isInVirtualSpace, and Path.Post.scripts.opensbp_post::move().
transferConstraints()
int SketchObject::transferConstraints (int fromGeoId, PointPos fromPosId, int toGeoId, PointPos toPosId, bool doNotTransformTangencies = false)
transfers all constraints of a point to a new point
Definition at line 2612 of file SketchObject.cpp.
References Sketcher::Angle, draftmake.make_clone::clone, Sketcher::Coincident, SketcherExample::Constraints, SplineSurface::i, Path.Post.scripts.opensbp_post::move(), Sketcher::Perpendicular, FreeCADInit::Second, and Sketcher::Tangent.
transferFilletConstraints()
void SketchObject::transferFilletConstraints (int geoId1, PointPos posId1, int geoId2, PointPos posId2) protected
Transfer constraints on lines being filleted.
Since filleting moves the endpoints of the input geometry, existing constraints may no longer be sensible. If fillet() was called with preserveCorner=false, the constraints are simply deleted. But if the lines are coincident and preserveCorner=true, we can preserve most constraints on the old end points by moving them to the preserved corner, or transforming distance constraints on straight lines into point-to-point distance constraints.
Parameters
geoId1,podId1,geoId2,posId2 - The two lines that have just been filleted
Definition at line 2432 of file SketchObject.cpp.
References SCL.SimpleDataTypes::c, Sketcher::Coincident, SketcherExample::Constraints, Sketcher::Distance, Sketcher::DistanceX, Sketcher::DistanceY, Sketcher::end, Sketcher::Equal, Sketcher::Constraint::First, Sketcher::Constraint::FirstPos, Base::Persistence::getClassTypeId(), draftguitools.gui_tool_utils::getPoint, Base::Persistence::getTypeId(), Sketcher::Horizontal, SplineSurface::i, Path.Post.scripts.opensbp_post::move(), Sketcher::none, Sketcher::PointOnObject, Sketcher::Constraint::Second, Sketcher::Constraint::SecondPos, Sketcher::SnellsLaw, Sketcher::start, Sketcher::Symmetric, Sketcher::Constraint::Type, and Sketcher::Vertical.
trim()
int SketchObject::trim (int geoId, const Base::Vector3d & point)
trim a curve
Definition at line 3468 of file SketchObject.cpp.
References Part::GeomCurve::closestParameter(), Sketcher::Coincident, SketcherExample::Constraints, Sketcher::Constraint::copy(), SCL.SimpleDataTypes::e, Sketcher::end, Sketcher::Equal, Sketcher::Constraint::First, Sketcher::Constraint::FirstPos, SketcherExample::Geometry, Sketcher::GeoUndef, Part::GeomCurve::getFirstParameter(), draftguitools.gui_tool_utils::getPoint, Sketcher::InternalAlignment, Sketcher::Constraint::involvesGeoId(), Sketcher::Constraint::involvesGeoIdAndPosId(), Base::BaseClass::isDerivedFrom(), Sketcher::GeometryFacade::isInternalType(), Sketcher::mid, Path.Post.scripts.opensbp_post::move(), Sketcher::InternalType::None, Sketcher::none, Sketcher::Perpendicular, updateLeaderLines::point, Sketcher::PointOnObject, RobotExampleTrajectoryOutOfShapes::pos1, Sketcher::Constraint::Second, Sketcher::Constraint::SecondPos, seekTrimPoints(), Sketcher::start, Sketcher::Constraint::substituteIndexAndPos(), Sketcher::Tangent, and Sketcher::Constraint::Type.
updateGeoHistory()
void SketchObject::updateGeoHistory () protected
Definition at line 715 of file SketchObject.cpp.
References Sketcher::end, FC_TIME_INIT, FC_TIME_LOG, Sketcher::GeometryFacade::getId(), draftguitools.gui_tool_utils::getPoint, Sketcher::start, and InitGui::t.
updateGeometryRefs()
void SketchObject::updateGeometryRefs () protected
Definition at line 10429 of file SketchObject.cpp.
References FC_ERR, FC_LOG, FC_WARN, Base::Persistence::getClassTypeId(), Sketcher::ExternalGeometryFacade::getFacade(), SplineSurface::i, Path.Post.scripts.opensbp_post::move(), Data::newElementName(), replaceobj::objs, Data::oldElementName(), importers.importIFCmulticore::subs, and TestSpreadsheet::v.
updateSolverExtension()
void Sketcher::SketchObject::updateSolverExtension (int geoId, std::unique_ptr< Part::GeometryExtension > && ext) inline
forwards a request to update an extension of a geometry of the solver to the solver.
Definition at line 735 of file SketchObject.h.
validateConstraints()
void SketchObject::validateConstraints ()
Remove constraints with invalid indexes.
Definition at line 9891 of file SketchObject.cpp.
References SketcherExample::Constraints, and Path.Post.scripts.opensbp_post::move().
validateExpression()
std::string SketchObject::validateExpression (const App::ObjectIdentifier & path, std::shared_ptr< const App::Expression > expr) protected
Definition at line 9918 of file SketchObject.cpp.
References SketcherExample::Constraints, FC_WARN, Sketcher::GeometryFacade::getFacade(), SplineSurface::i, Sketcher::Constraint::isDriving, and OpenSCADFeatures::long.
Referenced by SketchObject().
validateExternalLinks()
void SketchObject::validateExternalLinks ()
validate External Links (remove invalid external links)
Definition at line 8251 of file SketchObject.cpp.
References Sketcher::Constraint::clone(), Base::Console(), SketcherExample::Constraints, Sketcher::Constraint::First, Sketcher::GeoUndef, Base::Exception::getMessage(), Part::PropertyPartShape::getShape(), Part::Datum::getShape(), Part::TopoShape::getSubShape(), SplineSurface::i, Base::BaseClass::isDerivedFrom(), Path.Post.scripts.opensbp_post::move(), Sketcher::RefExt, Sketcher::Constraint::Second, Part::Feature::Shape, Sketcher::Constraint::Third, and Base::ConsoleSingleton::Warning().
Referenced by SketcherGui::ViewProviderSketch::setEdit().
Member Data Documentation
ArcFitTolerance
App ::PropertyPrecision Sketcher::SketchObject::ArcFitTolerance
Definition at line 109 of file SketchObject.h.
Constraints
Sketcher::PropertyConstraintList Sketcher::SketchObject::Constraints
Definition at line 103 of file SketchObject.h.
Referenced by DrawSketchHandlerDimension::addConstraintIndex(), addCopyOfConstraints(), CmdSketcherConstrainLock::applyConstraint(), CmdSketcherConstrainBlock::applyConstraint(), CmdSketcherConstrainDistance::applyConstraint(), CmdSketcherConstrainDistanceX::applyConstraint(), CmdSketcherConstrainDistanceY::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainRadiam::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), SketcherGui::areAllPointsOrSegmentsFixed(), SketcherGui::areBothPointsOrSegmentsFixed(), canHorVerBlock(), carbonCopy(), copySelectionToClipboard(), Sketcher::SketchAnalysis::detectMissingEqualityConstraints(), Sketcher::SketchAnalysis::detectMissingPointOnPointConstraints(), SketcherGui::EditDatumDialog::EditDatumDialog(), SketcherGui::ViewProviderSketch::editDoubleClicked(), SketcherGui::EditDatumDialog::exec(), DrawSketchHandlerDimension::finalizeCommand(), findBSplineAndKnotIndex(), finishDatumConstraint(), DrawSketchHandlerDimension::finishDimensionCreation(), DrawSketchHandlerDimension::hasBeenAborted(), DrawSketchHandlerDimension::isHorizontalVerticalBlock(), SketcherGui::IsPointAlreadyOnCurve(), SketcherGui::isPointOrSegmentFixed(), SketcherGui::makeAngleBetweenTwoLines(), SketcherGui::ViewProviderSketch::mouseButtonPressed(), SketcherGui::ViewProviderSketch::onDelete(), SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsItemChanged(), ExpressionDelegate::paint(), removeRedundantPointOnObject(), CmdSketcherConstrainTangent::substituteConstraintCombinations(), CmdSketcherConstrainCoincidentUnified::substituteConstraintCombinationsCoincident(), CmdSketcherConstrainCoincidentUnified::substituteConstraintCombinationsPointOnObject(), SketcherGui::ConstraintView::swapNamedOfSelectedItems(), and DrawSketchHandlerDimension::updateDistanceType().
Exports
App ::PropertyLinkListHidden Sketcher::SketchObject::Exports
Definition at line 106 of file SketchObject.h.
ExternalGeo
Part ::PropertyGeometryList Sketcher::SketchObject::ExternalGeo
Definition at line 107 of file SketchObject.h.
Referenced by carbonCopy().
ExternalGeometry
App ::PropertyLinkSubList Sketcher::SketchObject::ExternalGeometry
Definition at line 104 of file SketchObject.h.
Referenced by carbonCopy().
ExternalTypes
App::PropertyIntegerList Sketcher::SketchObject::ExternalTypes
Definition at line 105 of file SketchObject.h.
FullyConstrained
App ::PropertyBool Sketcher::SketchObject::FullyConstrained
Definition at line 108 of file SketchObject.h.
Geometry
Part ::PropertyGeometryList Sketcher::SketchObject::Geometry
Property.
The Geometry list contains the non-external Part::Geometry objects in the sketch. The list may be accessed directly, or indirectly via getInternalGeometry().
Many of the methods in this class take geoId and posId parameters. A GeoId is a unique identifier for geometry in the Sketch. geoId >= 0 means an index in the Geometry list. geoId < 0 refers to sketch axes and external geometry. posId is a PointPos enum, documented in Constraint.h.
Definition at line 102 of file SketchObject.h.
InternalShape
Part ::PropertyPartShape Sketcher::SketchObject::InternalShape
Definition at line 110 of file SketchObject.h.
InternalTolerance
App ::PropertyPrecision Sketcher::SketchObject::InternalTolerance
Definition at line 111 of file SketchObject.h.
MakeInternals
App ::PropertyBool Sketcher::SketchObject::MakeInternals
Definition at line 112 of file SketchObject.h.
noRecomputes
bool Sketcher::SketchObject::noRecomputes
SketchObject can work in two modes: Recompute Mode and noRecomputes Mode
In Recompute Mode, a recompute is necessary after each geometry addition to update the solver DoF (default)
In NoRecomputes Mode, no recompute is necessary after a geometry addition. If a recompute is triggered it is just less efficient.
This flag does not regulate whether this object will recompute or not if execute() or a recompute() is actually executed, it just regulates whether the solver is called or not (i.e. whether it relies on the solve of execute for the calculation)
Definition at line 138 of file SketchObject.h.
Referenced by SketcherGui::TaskSketcherMessages::TaskSketcherMessages().
signalElementsChanged
boost::signals2::signal<void()> Sketcher::SketchObject::signalElementsChanged
Definition at line 896 of file SketchObject.h.
signalSolverUpdate
boost::signals2::signal<void()> Sketcher::SketchObject::signalSolverUpdate
Definition at line 895 of file SketchObject.h.
Referenced by SketcherGui::ViewProviderSketch::setEdit().
The documentation for this class was generated from the following files:
SketchObject.h
SketchObject.cpp