FreeCAD: Gui Namespace Reference
Gui Namespace Reference
Namespaces
DAG
Dialog
DockWnd
Gui
Inventor
PropertyEditor
TaskView
Classes
class AbstractMouseSelection
class AbstractSplitView
class AbstractSplitViewPy
class AbstractUi
The AbstractUi class Abstract base class the defines the class interface.
class AccelLineEdit
class Action
class ActionFunction
class ActionFunctionPrivate
class ActionGroup
class ActionSelector
class ActionStyleEvent
class ActiveObjectList
class AlignmentGroup
class AlignmentView
class Application
class ApplicationIndex
struct ApplicationP
class ApplicationPy
class ArcEngine
class Assistant
class AutoSaveProperty
class AutoSaver
class AxisOrigin
A class to create a Coin3D node representation of an coordinate system.
class BaseMouseSelection
class BaseView
class BitmapFactoryInst
class BitmapFactoryInstP
class BlankWorkbench
class BlenderNavigationStyle
class BoxZoomSelection
class Breakpoint
class ButtonGroup
The ButtonGroup class Unlike Qt's QButtonGroup this class allows it that in exclusive mode all buttons can be unchecked.
class CADNavigationStyle
class CallTip
class CallTipsList
class Camera
class CheckListDialog
class ClearLineEdit
class CoinPtr
class ColorButton
struct ColorButtonP
class Command
class CommandActionPy
class CommandBase
class CommandCompleter
class CommandIconView
class CommandManager
class CompletionList
class ConsoleCriticalTask
class ConsoleErrorTask
class ConsoleHistory
class ConsoleLogTask
class ConsoleMessageTask
class ConsoleWarningTask
class ContainerDialog
class ControlSingleton
class CustomMessageEvent
class CustomPageProducer
class DialogOptions
The DialogOptions class Helper class to control whether to use native or Qt dialogs.
class DimensionWidget
class DlgObjectSelection
class DockWidgetAction
class DockWidgetEventFilter
class DockWindow
struct DockWindowItem
class DockWindowItems
class DockWindowManager
struct DockWindowManagerP
class Document
class DocumentIndex
class DocumentItem
class DocumentModel
class DocumentModelIndex
struct DocumentModelP
class DocumentObjectData
class DocumentObjectItem
class DocumentObserver
class DocumentObserverPython
struct DocumentP
class DocumentT
class DocumentWeakPtrT
The DocumentWeakPtrT class.
class DoubleSpinBox
class EditableDatumLabel
class EditorView
class EditorViewP
class ElementColors
class ExpLineEdit
class ExpressionBinding
class ExpressionBindingPy
class ExpressionCompleter
The ExpressionCompleter class extends the QCompleter class to provide a completer model of documentobject names and properties.
class ExpressionLineEdit
class ExpressionParameter
class ExpressionSpinBox
class ExpressionTextEdit
class ExpressionWidget
class FileChooser
class FileDialog
class FileHandler
class FileIconProvider
class FileOptionsDialog
class FixedGroup
class FixedTimeAnimation
class Flag
class FlagLayout
class FormatString
class FreehandSelection
class GestureNavigationStyle
class GLFlagWindow
class GLGraphicsItem
class GLOverlayWidget
class GLPainter
class GraphicsScene
class GraphicsView
class GraphicsView3D
class GraphvizGraphicsView
class GraphvizView
class GraphvizWorker
The GraphvizWorker class.
class GroupCommand
class GuiAbstractNativeEvent
class GUIApplication
class GUIApplicationNativeEventAware
class GUIConsole
class GuiNativeEvent
class GUISingleApplication
class HistoryList
class HttpServer
class ImageView
class InputField
class InputValidator
class InteractiveInterpreter
struct InteractiveInterpreterP
class InteractiveScale
class IntSpinBox
class InventorNavigationStyle
class ItemViewSelection
class LabelButton
class LabelEditor
class LineMarker
class LinkInfo
class LinkOwner
class LinkView
class LocationDialog
class LocationDialogImp
class LocationDialogUi
class LocationDialogUiImp
class LocationImpUi
class LocationUi
class LocationWidget
class MacroCommand
class MacroFile
class MacroManager
class MacroOutputBuffer
class MacroOutputOption
class MainWindow
struct MainWindowP
class MainWindowPy
class ManualAlignment
class MayaGestureNavigationStyle
class MDIView
class MDIViewPy
class MDIViewPyWrap
class MDIViewPyWrapImp
class MenuItem
class MenuManager
class MergeDocuments
class ModifierLineEdit
class ModuleIO
class MovableGroup
class MovableGroupModel
class Multisample
class NaviCubeSettings
class NavigationAnimation
class NavigationAnimator
class NavigationStyle
class NavigationStyleEvent
class NetworkRetriever
struct NetworkRetrieverP
struct Node_Block
struct Node_Object
struct Node_Slice
class NoneWorkbench
class NotificationArea
struct NotificationAreaP
class NotificationBox
class NotificationLabel
class OpenCascadeNavigationStyle
class OpenGLBuffer
class OpenGLMultiBuffer
class OpenSCADNavigationStyle
class OutputStderr
class OutputStdout
class OverlayDragFrame
A translucent frame as a visual indicator when dragging a dock widget.
class OverlayGraphicsEffect
class OverlayManager
Class that manages overlay dockable widgets.
class OverlayParams
class OverlayProxyWidget
class OverlaySizeGrip
Size grip for title bar and split handler of OverlayTabWidget.
class OverlaySplitter
Splitter for OverlayTabWidget.
class OverlaySplitterHandle
Splitter handle for dragging the splitter.
class OverlayTabWidget
Tab widget to contain dock widgets in overlay mode.
class OverlayTitleBar
Title bar for OverlayTabWidget.
class OverlayToolButton
Tool button for the title bar of the OverlayTabWidget.
class ParamDelayedHandlerT
Template class for a delayed parameter handler.
class ParamHandler
Helper class to handle parameter change.
class ParamHandlers
class ParamHandlerT
Template class for a non-delayed parameter handler.
struct ParamKey
Structure for storing a parameter key and its path to be used in std::map.
class ParentFinder
class PickedPoint
class PolyClipSelection
class Polyline
class PolyPickerSelection
class PrefCheckBox
class PrefColorButton
class PrefComboBox
class PrefDoubleSpinBox
class PreferencePack
class PreferencePackManager
class PrefFileChooser
class PrefFontBox
class PrefLineEdit
class PrefPageProducer
class PrefPagePyProducer
class PrefPageUiProducer
class PrefQuantitySpinBox
class PrefQuantitySpinBoxPrivate
class PrefRadioButton
class PrefSlider
class PrefSpinBox
class PrefTextEdit
class PrefUnitSpinBox
class PrefWidget
class ProgressBar
struct ProgressBarPrivate
class ProgressDialog
class PropertyListEditor
class PropertyView
class PyResource
class PySideUicModule
class PythonBaseWorkbench
class PythonBlankWorkbench
class PythonCommand
class PythonConsole
class PythonConsoleHighlighter
struct PythonConsoleP
class PythonDebugExcept
class PythonDebugger
struct PythonDebuggerP
class PythonDebuggerPy
class PythonDebugModule
class PythonDebugStderr
class PythonDebugStdout
class PythonEditor
struct PythonEditorP
class PythonEditorView
class PythonGroupCommand
class PythonOnlineHelp
class PythonRedirector
class PythonStderr
class PythonStdin
class PythonStdout
class PythonSyntaxHighlighter
class PythonSyntaxHighlighterP
class PythonTextEditor
class PythonTracing
class PythonTracingLocker
class PythonTracingWatcher
class PythonWorkbench
class PythonWrapper
struct QObjectDeleteLater
class QtTools
The QtTools class Helper class to reduce adding a lot of extra QT_VERSION checks to client code.
class QuantitySpinBox
class QuantitySpinBoxPrivate
class RawInputEventFilter
struct RayPickInfo
class RDragger
Rotation Dragger.
class RecentFilesAction
class RecentMacrosAction
class RecoveryRunnable
class RecoveryWriter
class RectangleSelection
class RedoAction
class ReportOutputParameter
class RevitNavigationStyle
class Rubberband
class RubberbandSelection
class RunningState
class SceneEventFilter
class SearchBar
class SelectionChanges
class SelectionFilter
class SelectionFilterGate
class SelectionFilterGatePython
class SelectionFilterPy
class SelectionGate
class SelectionGateFilterExternal
class SelectionGatePython
class SelectionLogDisabler
class SelectionObject
class SelectionObserver
class SelectionObserverPython
class SelectionSingleton
class SelectModule
class SequencerBar
struct SequencerBarPrivate
class SequencerDialog
struct SequencerDialogPrivate
class ShortcutManager
class SignalConnect
class So3DAnnotation
3D Annotation Node - Annotation with depth buffer
class SoAutoZoomTranslation
class SoAxisCrossKit
class SoBoxSelectionRenderAction
class SoBoxSelectionRenderActionP
class SoColorBarLabel
class SoDatumLabel
class SoFCBackgroundGradient
class SoFCBoundingBox
class SoFCColorBar
class SoFCColorBarBase
class SoFCColorBarNotifier
class SoFCColorBarProxyObject
class SoFCColorGradient
class SoFCColorLegend
class SoFCCSysDragger
Coordinate System Dragger.
class SoFCDB
class SoFCDocumentAction
class SoFCDocumentObjectAction
class SoFCEnableHighlightAction
class SoFCEnableSelectionAction
class SoFCHighlightAction
class SoFCHighlightColorAction
class SoFCInteractiveElement
class SoFCOffscreenRenderer
class SoFCPathAnnotation
class SoFCSelection
class SoFCSelectionAction
class SoFCSelectionColorAction
struct SoFCSelectionContext
struct SoFCSelectionContextBase
struct SoFCSelectionContextEx
class SoFCSelectionCounter
class SoFCSelectionRoot
class SoFCSeparator
class SoFCTransform
A temporary workaround for coin3d/coin#534.
class SoFCUnifiedSelection
class SoFCVectorizeSVGAction
class SoFCVectorizeSVGActionP
class SoFCVectorizeU3DAction
class SoFCVectorizeU3DActionP
class SoFrameLabel
class SoGLRenderActionElement
class SoGLSelectAction
class SoGLVBOActivatedElement
class SoGLWidgetElement
class SoGLWidgetNode
class SoHighlightElementAction
struct SoLabelTextFormat
class SoQtOffscreenRenderer
class SoQtOffscreenRendererPy
class SoRegPoint
class SoSelectionElementAction
class SoShapeScale
class SoSkipBoundingGroup
class SoStringLabel
class SoSVGVectorOutput
class SoTextLabel
class SoU3DVectorOutput
class SoUpdateVBOAction
class SoVisibleFaceAction
class SoVRMLAction
class SpinningAnimation
class SplashObserver
class SplashScreen
class SplitView3DInventor
class StartupPostProcess
class StartupProcess
class StatefulLabel
class StatusBarObserver
class StatusWidget
class StdCmdDescription
class StdCmdDownloadOnlineHelp
class StdCmdPythonHelp
class StdWorkbench
class SyntaxHighlighter
class SyntaxHighlighterP
class TaskBoxAngle
class TaskBoxPosition
class TaskCSysDragger
class TaskDlgRelocation
class TaskElementColors
class TaskImage
class TaskImageDialog
class TaskMeasure
class TaskOrientation
class TaskOrientationDialog
class TaskTransform
class TDragger
Translation Dragger.
class Tessellator
class TestConsoleObserver
class TestWorkbench
struct TextBlockData
class TextDocumentEditorView
class TextEdit
class TextEditor
struct TextEditorP
class Thumbnail
class TimerFunction
class TimerFunctionPrivate
class TinkerCADNavigationStyle
class ToolBar
class ToolBarAction
class ToolBarAreaWidget
class ToolBarGrip
class ToolBarItem
class ToolBarManager
class ToolBoxManager
class ToolHandler
class ToolTip
class TouchpadNavigationStyle
class TPlanarDragger
Planar Translation Dragger.
class TransactionViewProvider
class TranslateManip
class Translator
class TranslatorP
class TreeDockWidget
class TreePanel
class TreeParams
class TreeView
class TreeWidget
class TreeWidgetItemDelegate
class UiLoader
class UiLoaderPy
class UIntSpinBox
class UIntSpinBoxPrivate
class UndoAction
class UnsignedValidator
class UrlHandler
class UrlLabel
class UserNavigationStyle
class VectorListEditor
class VectorTableDelegate
class VectorTableModel
class View3DInventor
class View3DInventorPy
class View3DInventorSelection
class View3DInventorViewer
class View3DInventorViewerPy
Python interface for View3DInventorViewer.
class View3DSettings
class ViewerEventFilter
class ViewParams
class ViewProvider
class ViewProviderAnnotation
class ViewProviderAnnotationLabel
class ViewProviderBuilder
class ViewProviderColorBuilder
class ViewProviderCoordinateSystem
class ViewProviderDatum
class ViewProviderDocumentObject
class ViewProviderDocumentObjectGroup
class ViewProviderDragger
class ViewProviderExtension
Extension with special viewprovider calls.
class ViewProviderExtensionPythonT
class ViewProviderExtern
class ViewProviderFaceTexture
class ViewProviderFeature
class ViewProviderFeaturePythonImp
class ViewProviderFeaturePythonT
class ViewProviderGeoFeatureGroup
class ViewProviderGeoFeatureGroupExtension
class ViewProviderGeometryObject
class ViewProviderGroupExtension
class ViewProviderImagePlane
class ViewProviderIndex
class ViewProviderInventorObject
class ViewProviderLine
class ViewProviderLink
class ViewProviderLinkObserver
class ViewProviderMap
class ViewProviderMaterialObject
class ViewProviderOriginGroup
class ViewProviderOriginGroupExtension
class ViewProviderPart
class ViewProviderPlacement
class ViewProviderPlane
class ViewProviderPoint
class ViewProviderSuppressibleExtension
class ViewProviderT
class ViewProviderTextDocument
class ViewProviderTextureExtension
class ViewProviderVarSet
class ViewProviderVRMLObject
class ViewProviderWeakPtrT
The ViewProviderWeakPtrT class.
class ViewVolumeProjection
class WaitCursor
class WaitCursorP
class WeakPtrT
The WeakPtrT class.
class WheelEventFilter
class WidgetFactoryInst
class WidgetFactorySupplier
class WidgetProducer
class WindowAction
class WindowParameter
class Workbench
class WorkbenchComboBox
class WorkbenchFactoryInst
class WorkbenchGroup
class WorkbenchManager
class WorkbenchManipulator
class WorkbenchManipulatorPython
class WorkbenchProducer
class WorkbenchTabWidget
class XMLMergeReader
Typedefs
using ColorMap = std::map< unsigned long, unsigned long >
using TStringList = std::list< std::string >
using TStringMap = std::map< std::string, std::string >
template<typename T >
using qobject_delete_later_unique_ptr = std::unique_ptr< T, QObjectDeleteLater >
using Node_ObjectPtr = std::shared_ptr< Node_Object >
using SoFCSelectionContextBasePtr = std::shared_ptr< SoFCSelectionContextBase >
using SoFCSelectionContextPtr = std::shared_ptr< SoFCSelectionContext >
using SoFCSelectionContextExPtr = std::shared_ptr< SoFCSelectionContextEx >
using DocumentObjectDataPtr = std::shared_ptr< DocumentObjectData >
using Graph = boost::adjacency_list< boost::vecS, boost::vecS, boost::directedS, boost::no_property, boost::no_property, boost::no_property, boost::listS >
using Vertex = boost::graph_traits< Graph >::vertex_descriptor
using Edge = boost::graph_traits< Graph >::edge_descriptor
using ViewProviderDocumentObjectGroupPython = ViewProviderFeaturePythonT< ViewProviderDocumentObjectGroup >
using ViewProviderExtensionPython = ViewProviderExtensionPythonT< Gui::ViewProviderExtension >
using ViewProviderFeaturePython = ViewProviderFeaturePythonT< ViewProviderDocumentObject >
using ViewProviderGeometryPython = ViewProviderFeaturePythonT< ViewProviderGeometryObject >
using ViewProviderGeoFeatureGroupPython = ViewProviderFeaturePythonT< ViewProviderGeoFeatureGroup >
using ViewProviderGeoFeatureGroupExtensionPython = ViewProviderExtensionPythonT< Gui::ViewProviderGeoFeatureGroupExtension >
using ViewProviderGroupExtensionPython = ViewProviderExtensionPythonT< Gui::ViewProviderGroupExtension >
using LinkInfoPtr = boost::intrusive_ptr< LinkInfo >
using ViewProviderLinkPython = ViewProviderFeaturePythonT< ViewProviderLink >
using ViewProviderMaterialObjectPython = ViewProviderFeaturePythonT< ViewProviderMaterialObject >
using ViewProviderOriginGroupExtensionPython = ViewProviderExtensionPythonT< Gui::ViewProviderOriginGroupExtension >
using ViewProviderPartPython = ViewProviderFeaturePythonT< ViewProviderPart >
using ViewProviderPlacementPython = ViewProviderFeaturePythonT< ViewProviderPlacement >
using ViewProviderSuppressibleExtensionPython = ViewProviderExtensionPythonT< Gui::ViewProviderSuppressibleExtension >
using CheckListItem = QPair< QString, bool >
Enumerations
enum SelectionRole {
None = 0, None = 0, Inner = 1, Outer = 2,
Split = 3, Custom0 = 4, Custom1 = 5, Custom2 = 6
}
enum ResolveMode { ResolveMode::NoResolve, ResolveMode::OldStyleElement, ResolveMode::NewStyleElement, ResolveMode::FollowLink }
enum ToolBarArea {
ToolBarArea::NoToolBarArea, ToolBarArea::LeftToolBarArea, ToolBarArea::RightToolBarArea, ToolBarArea::TopToolBarArea,
ToolBarArea::BottomToolBarArea, ToolBarArea::LeftMenuToolBarArea, ToolBarArea::RightMenuToolBarArea, ToolBarArea::StatusBarToolBarArea
}
enum HighlightMode {
HighlightMode::Underlined, HighlightMode::Italic, HighlightMode::Overlined, HighlightMode::StrikeOut,
HighlightMode::Bold, HighlightMode::Blue, HighlightMode::LightBlue, HighlightMode::UserDefined
}
highlight modes for the tree items
enum TreeItemMode { TreeItemMode::ExpandItem, TreeItemMode::ExpandPath, TreeItemMode::CollapseItem, TreeItemMode::ToggleItem }
highlight modes for the tree items
enum ViewStatus {
UpdateData = 0, Detach = 1, isRestoring = 2, UpdatingView = 3,
TouchDocument = 4
}
enum WorkbenchItemStyle { WorkbenchItemStyle::IconAndText = 0, WorkbenchItemStyle::IconOnly = 1, WorkbenchItemStyle::TextOnly = 2 }
Functions
static PyObject * FreeCADGui_subgraphFromObject (PyObject *, PyObject *args)
static PyObject * FreeCADGui_exportSubgraph (PyObject *, PyObject *args)
static PyObject * FreeCADGui_getSoDBVersion (PyObject *, PyObject *args)
BitmapFactoryInst & BitmapFactory ()
Get the global instance.
void CreateStdCommands ()
void CreateDocCommands ()
void CreateFeatCommands ()
void CreateMacroCommands ()
void CreateViewStdCommands ()
void CreateWindowStdCommands ()
void CreateStructureCommands ()
void CreateTestCommands ()
void CreateLinkCommands ()
template<typename T >
void _cmdDocument (Gui::Command::DoCmd_Type cmdType, const App::Document *doc, const std::string &mod, T &&cmd)
template<typename T >
void _cmdDocument (Gui::Command::DoCmd_Type cmdType, const std::string &doc, const std::string &mod, T &&cmd)
template<typename T >
void cmdAppDocument (const App::Document *doc, T &&cmd)
template<typename T >
void cmdAppDocument (const std::string &doc, T &&cmd)
template<typename T >
void cmdGuiDocument (const App::Document *doc, T &&cmd)
template<typename T >
void cmdGuiDocument (const std::string &doc, T &&cmd)
template<typename T >
void _cmdDocument (Gui::Command::DoCmd_Type cmdType, const App::DocumentObject *obj, const std::string &mod, T &&cmd)
template<typename T >
void cmdAppDocument (const App::DocumentObject *obj, T &&cmd)
template<typename... Args>
void cmdAppDocumentArgs (const App::Document *doc, const std::string &cmd, Args &&... args)
template<typename T >
void cmdGuiDocument (const App::DocumentObject *obj, T &&cmd)
template<typename T >
void _cmdObject (Gui::Command::DoCmd_Type cmdType, const App::DocumentObject *obj, const std::string &mod, T &&cmd)
template<typename T >
void cmdAppObject (const App::DocumentObject *obj, T &&cmd)
template<typename T >
void cmdGuiObject (const App::DocumentObject *obj, T &&cmd)
void cmdAppObjectHide (const App::DocumentObject *obj)
Hides an object.
void cmdAppObjectShow (const App::DocumentObject *obj)
Shows an object.
void cmdSetEdit (const App::DocumentObject *obj, int mod=0)
template<typename... Args>
void cmdAppObjectArgs (const App::DocumentObject *obj, const std::string &cmd, Args &&... args)
template<typename... Args>
void cmdGuiObjectArgs (const App::DocumentObject *obj, const std::string &cmd, Args &&... args)
template<typename... Args>
void doCommandT (Gui::Command::DoCmd_Type cmdType, const std::string &cmd, Args &&... args)
template<typename... Args>
void copyVisualT (Args &&... args)
ControlSingleton & Control ()
Get the global instance.
bool validateInput (QWidget *parent, const QString &input)
MainWindow * getMainWindow ()
NotificationBox::Options operator| (NotificationBox::Options lhs, NotificationBox::Options rhs)
bool operator& (NotificationBox::Options lhs, NotificationBox::Options rhs)
template<Base::LogStyle , Base::IntendedRecipient = Base::IntendedRecipient::User, Base::ContentType = Base::ContentType::Translated, typename TNotifier , typename TCaption , typename TMessage >
void Notify (TNotifier &&notifier, TCaption &&caption, TMessage &&message)
generic function to send any message provided by Base::LogStyle
template<typename TNotifier , typename TCaption , typename TMessage >
void NotifyWarning (TNotifier &&notifier, TCaption &&caption, TMessage &&message)
template<typename TNotifier , typename TCaption , typename TMessage >
void NotifyUserWarning (TNotifier &&notifier, TCaption &&caption, TMessage &&message)
template<typename TNotifier , typename TCaption , typename TMessage >
void TranslatedUserWarning (TNotifier &&notifier, TCaption &&caption, TMessage &&message)
template<typename TNotifier , typename TCaption , typename TMessage >
void NotifyError (TNotifier &&notifier, TCaption &&caption, TMessage &&message)
template<typename TNotifier , typename TCaption , typename TMessage >
void NotifyUserError (TNotifier &&notifier, TCaption &&caption, TMessage &&message)
template<typename TNotifier , typename TCaption , typename TMessage >
void TranslatedUserError (TNotifier &&notifier, TCaption &&caption, TMessage &&message)
template<typename TNotifier , typename TCaption , typename TMessage >
void TranslatedNotification (TNotifier &&notifier, TCaption &&caption, TMessage &&message)
template<typename TNotifier , typename TCaption , typename TMessage >
void Notification (TNotifier &&notifier, TCaption &&caption, TMessage &&message)
bool GuiExport OpenURLInBrowser (const char *URL)
opens a URL in the system Browser
static const QChar promptEnd (QLatin1Char(' '))
int promptLength (const QString &lineStr)
QString stripPromptFrom (const QString &lineStr)
bool cursorBeyond (const QTextCursor &cursor, const QTextCursor &limit, int shift=0)
static std::string getPySideModuleName (const std::string &moduleName)
static bool loadPySideModule (const std::string &moduleName, PyTypeObject **&types)
static std::string formatModuleError (const std::string &name)
static PyObject * importShiboken ()
static PyObject * importPySide (const std::string &moduleName)
template<typename qttype >
qttype * qt_getCppType (PyObject *pyobj)
template<typename qttype >
Py::Object qt_wrapInstance (qttype object, const std::string &className, const std::string &moduleName)
const char * qt_identifyType (QObject *ptr, const std::string &moduleName)
std::array< std::pair< double, std::string >, 3 > schemaTranslatePoint (double x, double y, double z, double precision)
QString getPreselectionInfo (const char *documentName, const char *objectName, const char *subElementName, float x, float y, float z, double precision)
void printPreselectionInfo (const char *documentName, const char *objectName, const char *subElementName, float x, float y, float z, double precision)
SelectionSingleton & Selection ()
Get the global instance.
static void renderDevBuildWarning (QPainter &painter, const QPoint startPosition, const QSize maxSize, QColor color)
bool isTreeViewDragging ()
void coinRemoveAllChildren (SoGroup *group)
void addNodes (Graph &graph, std::map< SoNode *, Vertex > &vertexNodeMap, SoNode *node)
WidgetFactoryInst & WidgetFactory ()
WidgetFactorySupplier & GetWidgetFactorySupplier ()
GuiExport WorkbenchFactoryInst & WorkbenchFactory ()
PROPERTY_SOURCE_TEMPLATE (FemGui::ViewProviderFemMeshShapeBasePython, FemGui::ViewProviderFemMeshShapeBase) template class FemGuiExport ViewProviderFeaturePythonT< ViewProviderFemMeshShapeBase >
PROPERTY_SOURCE_TEMPLATE (PartDesignGui::ViewProviderSubShapeBinderPython, PartDesignGui::ViewProviderSubShapeBinder) template class PartDesignGuiExport ViewProviderFeaturePythonT< ViewProviderSubShapeBinder >
Variables
struct PyMethodDef FreeCADGui_methods []
static const unsigned char XPM_pixel_mask [21 *27 *4+1]
static const unsigned char YPM_pixel_mask [21 *27 *4+1]
static const unsigned char ZPM_pixel_mask [21 *27 *4+1]
template class GuiExport ViewProviderFeaturePythonT< ViewProviderDocumentObjectGroup >
template class GuiExport ViewProviderExtensionPythonT< ViewProviderExtension >
template class GuiExport ViewProviderFeaturePythonT< ViewProviderDocumentObject >
template class GuiExport ViewProviderFeaturePythonT< ViewProviderGeometryObject >
template class GuiExport ViewProviderFeaturePythonT< ViewProviderGeoFeatureGroup >
template class GuiExport ViewProviderExtensionPythonT< ViewProviderGeoFeatureGroupExtension >
template class GuiExport ViewProviderExtensionPythonT< ViewProviderGroupExtension >
template class GuiExport ViewProviderFeaturePythonT< ViewProviderLink >
template class GuiExport ViewProviderFeaturePythonT< ViewProviderMaterialObject >
template class GuiExport ViewProviderExtensionPythonT< ViewProviderOriginGroupExtension >
template class GuiExport ViewProviderFeaturePythonT< ViewProviderPart >
template class GuiExport ViewProviderFeaturePythonT< ViewProviderPlacement >
template class GuiExport ViewProviderExtensionPythonT< ViewProviderSuppressibleExtension >
template class FemGuiExport ViewProviderFeaturePythonT< ViewProviderFemAnalysis >
template class FemGuiExport ViewProviderFeaturePythonT< ViewProviderFemConstraint >
template class FemGuiExport ViewProviderFeaturePythonT< ViewProviderFemMesh >
template class FemGuiExport ViewProviderFeaturePythonT< ViewProviderResult >
template class FemGuiExport ViewProviderFeaturePythonT< ViewProviderSolver >
template class SpreadsheetGuiExport ViewProviderFeaturePythonT< ViewProviderSheet >
Typedef Documentation
CheckListItem
using Gui::CheckListItem = typedef QPair<QString, bool>
Definition at line 191 of file Widgets.h.
ColorMap
using Gui::ColorMap = typedef std::map<unsigned long, unsigned long>
Definition at line 37 of file BitmapFactory.h.
DocumentObjectDataPtr
using Gui::DocumentObjectDataPtr = typedef std::shared_ptr<DocumentObjectData>
Definition at line 48 of file Tree.h.
Edge
using Gui::Edge = typedef boost::graph_traits<Graph>::edge_descriptor
Definition at line 569 of file Gui/ViewProvider.cpp.
Graph
using Gui::Graph = typedef boost::adjacency_list < boost::vecS, boost::vecS, boost::directedS, boost::no_property, boost::no_property, boost::no_property, boost::listS >
Definition at line 567 of file Gui/ViewProvider.cpp.
LinkInfoPtr
using Gui::LinkInfoPtr = typedef boost::intrusive_ptr<LinkInfo>
Definition at line 41 of file ViewProviderLink.h.
Node_ObjectPtr
using Gui::Node_ObjectPtr = typedef std::shared_ptr<Node_Object>
Definition at line 198 of file SelectionFilter.h.
qobject_delete_later_unique_ptr
template<typename T > using Gui::qobject_delete_later_unique_ptr = typedef std::unique_ptr<T, QObjectDeleteLater>
Definition at line 55 of file NotificationBox.cpp.
SoFCSelectionContextBasePtr
using Gui::SoFCSelectionContextBasePtr = typedef std::shared_ptr<SoFCSelectionContextBase>
Definition at line 41 of file SoFCSelectionContext.h.
SoFCSelectionContextExPtr
using Gui::SoFCSelectionContextExPtr = typedef std::shared_ptr<SoFCSelectionContextEx>
Definition at line 104 of file SoFCSelectionContext.h.
SoFCSelectionContextPtr
using Gui::SoFCSelectionContextPtr = typedef std::shared_ptr<SoFCSelectionContext>
Definition at line 52 of file SoFCSelectionContext.h.
TStringList
using Gui::TStringList = typedef std::list<std::string>
Definition at line 38 of file Translator.h.
TStringMap
using Gui::TStringMap = typedef std::map<std::string, std::string>
Definition at line 39 of file Translator.h.
Vertex
using Gui::Vertex = typedef boost::graph_traits<Graph>::vertex_descriptor
Definition at line 568 of file Gui/ViewProvider.cpp.
ViewProviderDocumentObjectGroupPython
using Gui::ViewProviderDocumentObjectGroupPython = typedef ViewProviderFeaturePythonT<ViewProviderDocumentObjectGroup>
Definition at line 81 of file ViewProviderDocumentObjectGroup.h.
ViewProviderExtensionPython
using Gui::ViewProviderExtensionPython = typedef ViewProviderExtensionPythonT<Gui::ViewProviderExtension>
Definition at line 76 of file ViewProviderExtensionPython.h.
ViewProviderFeaturePython
using Gui::ViewProviderFeaturePython = typedef ViewProviderFeaturePythonT<ViewProviderDocumentObject>
Definition at line 633 of file ViewProviderFeaturePython.h.
ViewProviderGeoFeatureGroupExtensionPython
using Gui::ViewProviderGeoFeatureGroupExtensionPython = typedef ViewProviderExtensionPythonT<Gui::ViewProviderGeoFeatureGroupExtension>
Definition at line 92 of file ViewProviderGeoFeatureGroupExtension.h.
ViewProviderGeoFeatureGroupPython
using Gui::ViewProviderGeoFeatureGroupPython = typedef ViewProviderFeaturePythonT<ViewProviderGeoFeatureGroup>
Definition at line 68 of file ViewProviderGeoFeatureGroup.h.
ViewProviderGeometryPython
using Gui::ViewProviderGeometryPython = typedef ViewProviderFeaturePythonT<ViewProviderGeometryObject>
Definition at line 634 of file ViewProviderFeaturePython.h.
ViewProviderGroupExtensionPython
using Gui::ViewProviderGroupExtensionPython = typedef ViewProviderExtensionPythonT<Gui::ViewProviderGroupExtension>
Definition at line 79 of file ViewProviderGroupExtension.h.
ViewProviderLinkPython
using Gui::ViewProviderLinkPython = typedef ViewProviderFeaturePythonT<ViewProviderLink>
Definition at line 335 of file ViewProviderLink.h.
ViewProviderMaterialObjectPython
using Gui::ViewProviderMaterialObjectPython = typedef ViewProviderFeaturePythonT<ViewProviderMaterialObject>
Definition at line 72 of file ViewProviderMaterialObject.h.
ViewProviderOriginGroupExtensionPython
using Gui::ViewProviderOriginGroupExtensionPython = typedef ViewProviderExtensionPythonT<Gui::ViewProviderOriginGroupExtension>
Definition at line 71 of file ViewProviderOriginGroupExtension.h.
ViewProviderPartPython
using Gui::ViewProviderPartPython = typedef ViewProviderFeaturePythonT<ViewProviderPart>
Definition at line 84 of file ViewProviderPart.h.
ViewProviderPlacementPython
using Gui::ViewProviderPlacementPython = typedef ViewProviderFeaturePythonT<ViewProviderPlacement>
Definition at line 70 of file ViewProviderPlacement.h.
ViewProviderSuppressibleExtensionPython
using Gui::ViewProviderSuppressibleExtensionPython = typedef ViewProviderExtensionPythonT<Gui::ViewProviderSuppressibleExtension>
Definition at line 70 of file ViewProviderSuppressibleExtension.h.
Enumeration Type Documentation
AntiAliasing
enum Gui::AntiAliasing strong
Enumerator
None
MSAA1x
MSAA2x
MSAA4x
MSAA6x
MSAA8x
Definition at line 62 of file Multisample.h.
HighlightMode
enum Gui::HighlightMode strong
highlight modes for the tree items
Enumerator
Underlined
Italic
Overlined
StrikeOut
Bold
Blue
LightBlue
UserDefined
Definition at line 50 of file TreeItemMode.h.
ResolveMode
enum Gui::ResolveMode strong
Enumerator
NoResolve
OldStyleElement
NewStyleElement
FollowLink
Definition at line 51 of file Gui/Selection.h.
SelectionRole
enum Gui::SelectionRole
Enumerator
None
None
Inner
Outer
Split
Custom0
Custom1
Custom2
Definition at line 50 of file Namespace.h.
ToolBarArea
enum Gui::ToolBarArea strong
Enumerator
NoToolBarArea
LeftToolBarArea
RightToolBarArea
TopToolBarArea
BottomToolBarArea
LeftMenuToolBarArea
RightMenuToolBarArea
StatusBarToolBarArea
Definition at line 56 of file ToolBarAreaWidget.h.
TreeItemMode
enum Gui::TreeItemMode strong
highlight modes for the tree items
Enumerator
ExpandItem
ExpandPath
CollapseItem
ToggleItem
Definition at line 62 of file TreeItemMode.h.
ViewStatus
enum Gui::ViewStatus
Enumerator
UpdateData
Detach
isRestoring
UpdatingView
TouchDocument
Definition at line 78 of file Gui/ViewProvider.h.
WorkbenchItemStyle
enum Gui::WorkbenchItemStyle strong
Enumerator
IconAndText
IconOnly
TextOnly
Definition at line 60 of file WorkbenchSelector.h.
Function Documentation
_cmdDocument() [1/3]
template<typename T > void Gui::_cmdDocument (Gui::Command::DoCmd_Type cmdType, const App::Document * doc, const std::string & mod, T && cmd)
Runs a command for accessing document attribute or method This function is an alternative to _FCMD_DOC_CMD
Parameters
doc pointer to a document
mod module name, "Gui" or "App"
cmd command string, streamable
Example:
_cmdDocument(Gui::Command::Gui, doc, "Gui", std::stringstream() << "getObject('" << objName << "')");
Translates to command (assuming doc's name is 'DocName', and and objName contains value 'ObjName'):
Gui.getDocument('DocName').getObject('ObjName')
Definition at line 114 of file CommandT.h.
Referenced by cmdGuiDocument().
_cmdDocument() [2/3]
template<typename T > void Gui::_cmdDocument (Gui::Command::DoCmd_Type cmdType, const App::DocumentObject * obj, const std::string & mod, T && cmd) inline
Runs a command for accessing an object's document attribute or method This function is an alternative to _FCMD_OBJ_DOC_CMD
Parameters
obj pointer to a DocumentObject
mod module name, "Gui" or "App"
cmd command string, streamable
Definition at line 247 of file CommandT.h.
_cmdDocument() [3/3]
template<typename T > void Gui::_cmdDocument (Gui::Command::DoCmd_Type cmdType, const std::string & doc, const std::string & mod, T && cmd)
Runs a command for accessing document attribute or method This function is an alternative to _FCMD_DOC_CMD
Parameters
doc document name
mod module name, "Gui" or "App"
cmd command string, streamable
Example:
_cmdDocument(Gui::Command::Gui, doc, "Gui", std::stringstream() << "getObject('" << objName << "')");
Translates to command (assuming doc's name is 'DocName', and and objName contains value 'ObjName'):
Gui.getDocument('DocName').getObject('ObjName')
Definition at line 141 of file CommandT.h.
_cmdObject()
template<typename T > void Gui::_cmdObject (Gui::Command::DoCmd_Type cmdType, const App::DocumentObject * obj, const std::string & mod, T && cmd)
Runs a command for accessing a document/view object's attribute or method This function is an alternative to _FCMD_OBJ_CMD
Parameters
cmdType Command type
obj pointer to a DocumentObject
mod module name, "Gui" or "App"
cmd command string, streamable
Example:
_cmdObject(Command::Gui,obj,"Gui", "Visibility = " << (visible?"True":"False"));
Translates to command (assuming obj's document name is 'DocName', obj's name is 'ObjName', and visible is true):
Gui.getDocument('DocName').getObject('ObjName').Visibility = True
Definition at line 323 of file CommandT.h.
References Gui::Command::Gui.
addNodes()
void Gui::addNodes (Graph & graph, std::map< SoNode *, Vertex > & vertexNodeMap, SoNode * node)
Definition at line 571 of file Gui/ViewProvider.cpp.
References toolbit-attributes::group, and SplineSurface::i.
Referenced by Gui::ViewProvider::checkRecursion().
BitmapFactory()
BitmapFactoryInst& Gui::BitmapFactory () inline
Get the global instance.
Definition at line 165 of file BitmapFactory.h.
References Gui::BitmapFactoryInst::instance().
Referenced by Gui::ViewProviderLink::_setupContextMenu(), Gui::Dialog::AboutDialog::aboutImage(), Gui::ActionSelector::ActionSelector(), StdCmdDlgMacroRecord::activated(), DrawSketchHandlerDimension::activated(), StdViewScreenShot::activated(), Gui::RecentMacrosAction::activateFile(), Gui::ElementColors::Private::addItem(), StdCmdWorkbench::createAction(), Gui::StdCmdDownloadOnlineHelp::createAction(), Gui::Command::createAction(), StdCmdDrawStyle::createAction(), Gui::PythonCommand::createAction(), Gui::PythonGroupCommand::createAction(), Gui::MacroCommand::createAction(), StdCmdUserEditMode::createAction(), StdCmdUndo::createAction(), StdCmdRedo::createAction(), TechDrawGui::ViewProviderPage::createMDIViewPage(), createVarSetTreeWidget(), Gui::Dialog::ButtonModel::data(), Gui::Dialog::CommandModel::data(), ConstraintItem::data(), Gui::Dialog::DlgCustomToolbars::DlgCustomToolbars(), Gui::DocumentIndex::DocumentIndex(), Gui::ViewProviderAnnotationLabel::drawImage(), PartGui::ViewProviderAttachExtension::extensionMergeColorfullOverlayIcons(), Gui::ViewProviderSuppressibleExtension::extensionMergeColorfullOverlayIcons(), SurfaceGui::GeomFillSurface::flipOrientation(), Gui::ViewProviderFeaturePythonImp::getIcon(), SurfaceGui::ViewProviderGeomFillSurface::getIcon(), SurfaceGui::ViewProviderSections::getIcon(), SurfaceGui::ViewProviderFilling::getIcon(), MeasureGui::ViewProviderMeasureGroup::getIcon(), PathGui::ViewProviderPath::getIcon(), SurfaceGui::ViewProviderExtend::getIcon(), PartGui::ViewProviderMultiFuse::getIcon(), PathGui::ViewProviderPathCompound::getIcon(), AssemblyGui::ViewProviderBom::getIcon(), AssemblyGui::ViewProviderBomGroup::getIcon(), PartGui::ViewProviderBoolean::getIcon(), AssemblyGui::ViewProviderJointGroup::getIcon(), AssemblyGui::ViewProviderSimulationGroup::getIcon(), AssemblyGui::ViewProviderViewGroup::getIcon(), PartDesignGui::ViewProviderPrimitive::getIcon(), PartGui::ViewProviderSpline::getIcon(), AssemblyGui::ViewProviderAssemblyLink::getIcon(), Gui::ExpressionWidget::getIcon(), Gui::ViewProviderDocumentObjectGroup::getIcon(), PartDesignGui::ViewProviderHelix::getIcon(), PathGui::ViewProviderPathShape::getIcon(), Gui::ViewProviderPart::getIcon(), MeshGui::ViewProviderMeshCurvature::getIcon(), PartDesignGui::ViewProviderPipe::getIcon(), PartDesignGui::ViewProviderLoft::getIcon(), AssemblyGui::ViewProviderAssembly::getIcon(), PartGui::ViewProviderMultiCommon::getIcon(), MeshGui::ViewProviderExport::getIcon(), MeshGui::ViewProviderMesh::getIcon(), Gui::ViewProviderLink::getIcon(), Gui::ViewProvider::getIcon(), ExpressionDelegate::getIcon(), Gui::LinkInfo::getIcon(), Gui::ViewProviderLink::getOverlayPixmap(), TDHandlerDimension::icon(), Gui::Dialog::IconDialog::IconDialog(), Gui::Dialog::IconFolders::IconFolders(), Gui::Dialog::DlgPropertyLink::init(), Gui::PythonGroupCommand::languageChange(), PartDesignGui::ViewProvider::mergeColorfulOverlayIcons(), SketcherGui::ViewProviderSketch::mergeColorfulOverlayIcons(), Gui::BitmapFactoryInst::mergePixmap(), Gui::DAG::Model::Model(), Gui::Dialog::DlgCustomActionsImp::onActionListWidgetItemActivated(), Gui::Dialog::DlgCustomActionsImp::onButtonReplaceActionClicked(), Gui::Dialog::DlgCustomToolbars::onModifyMacroAction(), SketcherGui::SketchOrientationDialog::onPreview(), SurfaceGui::GeomFillSurface::onSelectionChanged(), Gui::Dialog::ParameterBool::ParameterBool(), Gui::Dialog::ParameterFloat::ParameterFloat(), Gui::Dialog::ParameterInt::ParameterInt(), Gui::Dialog::ParameterText::ParameterText(), Gui::Dialog::ParameterUInt::ParameterUInt(), Gui::BitmapFactoryInst::pixmap(), Gui::Dialog::DlgCustomKeyboardImp::populateCommandList(), TechDrawGui::QGVPage::prepareCursorPixmap(), PyMOD_INIT_FUNC(), Gui::OverlayTabWidget::refreshIcons(), Gui::OverlayManager::Private::refreshIcons(), Gui::OverlaySplitterHandle::refreshIcons(), Gui::DockWnd::ReportView::ReportView(), Gui::ApplicationPy::sAddIcon(), Gui::ApplicationPy::sAddIconPath(), Gui::ApplicationPy::sAddResPath(), Gui::Thumbnail::SaveDocFile(), Gui::DockWnd::SelectionView::SelectionView(), Gui::ViewProviderTextureExtension::setCoinAppearance(), SurfaceGui::GeomFillSurface::setEditedObject(), MatGui::AppearancePreview::setTexture(), Gui::GroupCommand::setup(), Gui::ViewProviderDragger::setupContextMenu(), PartDesignGui::ViewProvider::setupContextMenu(), PartGui::ViewProviderPartExt::setupContextMenu(), Gui::AlignmentView::setupHeadUpDisplay(), Gui::ApplicationPy::sGetIcon(), Gui::PythonDebugger::showDebugMarker(), DrawingGui::ViewProviderDrawingPage::showDrawingView(), SpreadsheetGui::ViewProviderSheet::showSpreadsheetView(), Gui::CallTipsList::showTips(), Gui::ApplicationPy::sIsIconCached(), Gui::SplashScreen::splashImage(), SketcherGui::DrawSketchHandler::suggestedConstraintsPixmaps(), Gui::OverlayTabWidget::syncAutoMode(), PartGui::TaskBooleanOperation::TaskBooleanOperation(), PartGui::TaskChamferEdges::TaskChamferEdges(), PartGui::TaskCheckGeometryDialog::TaskCheckGeometryDialog(), PartGui::TaskCrossSections::TaskCrossSections(), MeshPartGui::TaskCrossSections::TaskCrossSections(), TechDrawGui::TaskDlgActiveView::TaskDlgActiveView(), TechDrawGui::TaskDlgBalloon::TaskDlgBalloon(), TechDrawGui::TaskDlgCenterLine::TaskDlgCenterLine(), TechDrawGui::TaskDlgComplexSection::TaskDlgComplexSection(), TechDrawGui::TaskDlgCosmeticCircle::TaskDlgCosmeticCircle(), TechDrawGui::TaskDlgCosmeticLine::TaskDlgCosmeticLine(), TechDrawGui::TaskDlgCosVertex::TaskDlgCosVertex(), TechDrawGui::TaskDlgCustomizeFormat::TaskDlgCustomizeFormat(), TechDrawGui::TaskDlgDetail::TaskDlgDetail(), TechDrawGui::TaskDlgDimension::TaskDlgDimension(), TechDrawGui::TaskDlgDimReference::TaskDlgDimReference(), TechDrawGui::TaskDlgGeomHatch::TaskDlgGeomHatch(), TechDrawGui::TaskDlgHatch::TaskDlgHatch(), TechDrawGui::TaskDlgLeaderLine::TaskDlgLeaderLine(), TechDrawGui::TaskDlgLineDecor::TaskDlgLineDecor(), TechDrawGui::TaskDlgLinkDim::TaskDlgLinkDim(), DrawingGui::TaskDlgOrthoViews::TaskDlgOrthoViews(), TechDrawGui::TaskDlgProjection::TaskDlgProjection(), TechDrawGui::TaskDlgProjGroup::TaskDlgProjGroup(), TechDrawGui::TaskDlgRichAnno::TaskDlgRichAnno(), TechDrawGui::TaskDlgSectionView::TaskDlgSectionView(), TechDrawGui::TaskDlgSelectLineAttributes::TaskDlgSelectLineAttributes(), TechDrawGui::TaskDlgSurfaceFinishSymbols::TaskDlgSurfaceFinishSymbols(), TechDrawGui::TaskDlgWeldingSymbol::TaskDlgWeldingSymbol(), PartGui::TaskExtrusion::TaskExtrusion(), PartGui::TaskFilletEdges::TaskFilletEdges(), SurfaceGui::TaskFilling::TaskFilling(), ReenGui::TaskFitBSplineSurface::TaskFitBSplineSurface(), SurfaceGui::TaskGeomFillSurface::TaskGeomFillSurface(), MatGui::TaskInspectAppearance::TaskInspectAppearance(), MatGui::TaskInspectMaterial::TaskInspectMaterial(), PartGui::TaskLoft::TaskLoft(), Gui::TaskMeasure::TaskMeasure(), PartGui::TaskMirroring::TaskMirroring(), PartGui::TaskOffset::TaskOffset(), ReenGui::TaskPoisson::TaskPoisson(), PartGui::TaskProjectOnSurface::TaskProjectOnSurface(), PartGui::TaskRevolution::TaskRevolution(), PartGui::TaskScale::TaskScale(), SurfaceGui::TaskSections::TaskSections(), Gui::TaskView::TaskSelectLinkProperty::TaskSelectLinkProperty(), PartGui::TaskShapeBuilder::TaskShapeBuilder(), PartGui::TaskSweep::TaskSweep(), PartGui::TaskThickness::TaskThickness(), Gui::TaskView::TaskWatcherCommands::TaskWatcherCommands(), Gui::TaskView::TaskWatcherPython::TaskWatcherPython(), Gui::DocumentObjectItem::testStatus(), Gui::TreeWidget::TreeWidget(), CmdSketcherCompLine::updateAction(), CmdSketcherCompCreateArc::updateAction(), CmdSketcherCompCreateConic::updateAction(), CmdSketcherCompDimensionTools::updateAction(), CmdSketcherCompExternal::updateAction(), CmdSketcherCompSlot::updateAction(), CmdSketcherConstrainLock::updateAction(), CmdSketcherConstrainDistance::updateAction(), CmdSketcherConstrainDistanceX::updateAction(), CmdSketcherConstrainDistanceY::updateAction(), CmdSketcherConstrainRadius::updateAction(), CmdSketcherConstrainDiameter::updateAction(), CmdSketcherConstrainRadiam::updateAction(), CmdSketcherConstrainAngle::updateAction(), MeasureGui::ViewProviderMeasureBase::updateIcon(), Gui::View3DInventor::View3DInventor(), Gui::Application::workbenchIcon(), Gui::WorkbenchTabWidget::WorkbenchTabWidget(), and Gui::SoFCOffscreenRenderer::writeToImage().
cmdAppDocument() [1/3]
template<typename T > void Gui::cmdAppDocument (const App::Document * doc, T && cmd) inline
Runs a command for accessing App.Document attribute or method This function is an alternative to FCMD_DOC_CMD
Parameters
doc pointer to a document
cmd command string, streamable
See also
_cmdDocument()
Example:
cmdAppDocument(doc, std::stringstream() << "getObject('" << objName << "')");
Translates to command (assuming doc's name is 'DocName', and and objName contains value 'ObjName'):
App.getDocument('DocName').getObject('ObjName')
Definition at line 169 of file CommandT.h.
Referenced by FemGui::TaskDlgMeshShapeNetgen::accept(), PartDesignGui::TaskPipeParameters::accept(), PartDesignGui::TaskDlgShapeBinder::accept(), PartDesignGui::TaskDlgFeatureParameters::accept(), CmdTestCmdFuncs::activated(), SpreadsheetGui::SheetView::confirmAliasChanged(), FemGui::TaskDlgMeshShapeNetgen::reject(), PartDesignGui::TaskDlgShapeBinder::reject(), and PartDesignGui::TaskDlgFeatureParameters::reject().
cmdAppDocument() [2/3]
template<typename T > void Gui::cmdAppDocument (const App::DocumentObject * obj, T && cmd) inline
Runs a command for accessing an object's App::Document attribute or method This function is an alternative to FCMD_OBJ_DOC_CMD
Parameters
obj pointer to a DocumentObject
cmd command string, streamable
Definition at line 257 of file CommandT.h.
References toolbit-attributes::args, toolbit-attributes::doc, Gui::Command::Doc, doCommand, Path.Post.scripts.comparams_post::fmt(), and Gui::FormatString::toStr().
cmdAppDocument() [3/3]
template<typename T > void Gui::cmdAppDocument (const std::string & doc, T && cmd) inline
Runs a command for accessing App.Document attribute or method This function is an alternative to FCMD_DOC_CMD
Parameters
doc document name
cmd command string, streamable
See also
_cmdDocument()
Example:
cmdAppDocument(doc, std::stringstream() << "getObject('" << objName << "')");
Translates to command (assuming doc's name is 'DocName', and and objName contains value 'ObjName'):
App.getDocument('DocName').getObject('ObjName')
Definition at line 192 of file CommandT.h.
cmdAppDocumentArgs()
template<typename... Args> void Gui::cmdAppDocumentArgs (const App::Document * doc, const std::string & cmd, Args &&... args)
Runs a command for accessing a document's attribute or method
Parameters
doc pointer to a Document
cmd command string, supporting printf like formatter
Example:
cmdAppDocumentArgs(obj, "addObject('%s')", "Part::Feature");
Translates to command (assuming obj's document name is 'DocName':
App.getDocument('DocName').addObject('Part::Feature')
Definition at line 276 of file CommandT.h.
cmdAppObject()
template<typename T > void Gui::cmdAppObject (const App::DocumentObject * obj, T && cmd) inline
Runs a command for accessing an document object's attribute or method This function is an alternative to FCMD_OBJ_CMD
Parameters
obj pointer to a DocumentObject
cmd command string, streamable
See also
_cmdObject()
Definition at line 340 of file CommandT.h.
Referenced by PartGui::TaskDlgAttacher::accept(), CmdTestCmdFuncs::activated(), and prepareProfileBased().
cmdAppObjectArgs()
template<typename... Args> void Gui::cmdAppObjectArgs (const App::DocumentObject * obj, const std::string & cmd, Args &&... args)
Runs a command for accessing a document object's attribute or method This function is an alternative to FCMD_OBJ_CMD2
Parameters
cmd command string, supporting printf like formatter
obj pointer to a DocumentObject
Example:
cmdAppObjectArgs(obj, "Visibility = %s", visible ? "True" : "False");
Translates to command (assuming obj's document name is 'DocName', obj's name is 'ObjName', and visible is true):
App.getDocument('DocName').getObject('ObjName').Visibility = True
Definition at line 399 of file CommandT.h.
Referenced by PartGui::OffsetWidget::accept(), PartGui::ThicknessWidget::accept(), SpreadsheetGui::DlgSheetConf::accept(), SpreadsheetGui::DlgBindSheet::accept(), PartDesignGui::TaskPipeParameters::accept(), MeshGui::TaskDecimating::accept(), PartGui::TaskDlgAttacher::accept(), CmdTestCmdFuncs::activated(), CmdSketcherConstrainLock::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadiam::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), CmdSketcherConstrainCoincidentUnified::activatedCoincident(), CmdSketcherConstrainCoincidentUnified::activatedPointOnObject(), SpreadsheetGui::PropertiesDialog::apply(), CmdSketcherConstrainLock::applyConstraint(), CmdSketcherConstrainBlock::applyConstraint(), CmdSketcherConstrainDistance::applyConstraint(), CmdSketcherConstrainDistanceX::applyConstraint(), CmdSketcherConstrainDistanceY::applyConstraint(), CmdSketcherConstrainParallel::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainRadiam::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), CmdSketcherConstrainCoincidentUnified::applyConstraintCoincident(), CmdSketcherConstrainCoincidentUnified::applyConstraintPointOnObject(), SpreadsheetGui::SheetView::confirmAliasChanged(), SketcherGui::ConstraintToAttachment(), DrawSketchHandlerDimension::createAngleConstrain(), DrawSketchHandlerDimension::createArcAngleConstrain(), DrawSketchHandlerDimension::createArcLengthConstrain(), SketcherGui::DrawSketchHandler::createAutoConstraints(), DrawSketchHandlerDimension::createBlockConstrain(), DrawSketchHandlerDimension::createCoincidenceConstrain(), DrawSketchHandlerDimension::createDistanceConstrain(), DrawSketchHandlerDimension::createDistanceXYConstrain(), DrawSketchHandlerDimension::createEqualityConstrain(), DrawSketchHandlerDimension::createHorizontalConstrain(), DrawSketchHandlerDimension::createRadiusDiameterConstrain(), DrawSketchHandlerDimension::createSymmetryConstrain(), DrawSketchHandlerDimension::createVerticalConstrain(), SketcherGui::doEndpointTangency(), SketcherGui::doEndpointToEdgeTangency(), DrawSketchHandlerDimension::finishDimensionCreation(), horVerActivated(), horVerApplyConstraint(), SpreadsheetGui::SheetTableView::insertColumns(), SpreadsheetGui::SheetTableView::insertColumnsAfter(), SpreadsheetGui::SheetTableView::insertRows(), SpreadsheetGui::SheetTableView::insertRowsAfter(), SketcherGui::makeAngleBetweenTwoLines(), SketcherGui::makeTangentToArcOfEllipseviaNewPoint(), SketcherGui::makeTangentToArcOfHyperbolaviaNewPoint(), SketcherGui::makeTangentToArcOfParabolaviaNewPoint(), SketcherGui::makeTangentToEllipseviaNewPoint(), SketcherGui::ViewProviderSketch::onDelete(), SpreadsheetGui::DlgBindSheet::onDiscard(), SpreadsheetGui::DlgSheetConf::onDiscard(), SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsItemChanged(), SpreadsheetGui::SheetTableView::onRecompute(), SketcherGui::DrawSketchHandlerExternal::releaseButton(), SketcherGui::DrawSketchHandlerCarbonCopy::releaseButton(), DrawSketchHandlerBSplineInsertKnot::releaseButton(), DrawSketchHandlerCopy::releaseButton(), DrawSketchHandlerRectangularArray::releaseButton(), SpreadsheetGui::SheetTableView::removeColumns(), removeRedundantPointOnObject(), SpreadsheetGui::SheetTableView::removeRows(), AssemblyGui::ViewProviderAssemblyLink::setupContextMenu(), CmdSketcherConstrainTangent::substituteConstraintCombinations(), CmdSketcherConstrainCoincidentUnified::substituteConstraintCombinationsCoincident(), CmdSketcherConstrainCoincidentUnified::substituteConstraintCombinationsPointOnObject(), and SketcherGui::ConstraintView::swapNamedOfSelectedItems().
cmdAppObjectHide()
void Gui::cmdAppObjectHide (const App::DocumentObject * obj) inline
Hides an object.
Definition at line 356 of file CommandT.h.
Referenced by PartDesignGui::TaskDlgSketchBasedParameters::accept(), PartDesignGui::TaskDlgLoftParameters::accept(), PartDesignGui::TaskDlgFeatureParameters::accept(), and CmdTestCmdFuncs::activated().
cmdAppObjectShow()
void Gui::cmdAppObjectShow (const App::DocumentObject * obj) inline
Shows an object.
Definition at line 361 of file CommandT.h.
References toolbit-attributes::args, Base::Console(), Base::ConsoleSingleton::DeveloperError(), Gui::Command::Doc, doCommand, SCL.SimpleDataTypes::e, Path.Post.scripts.comparams_post::fmt(), App::DocumentObject::getDocument(), App::DocumentObject::getFullLabel(), App::Document::getName(), App::DocumentObject::getNameInDocument(), and Gui::FormatString::toStr().
Referenced by CmdTestCmdFuncs::activated().
cmdGuiDocument() [1/3]
template<typename T > void Gui::cmdGuiDocument (const App::Document * doc, T && cmd) inline
Runs a command for accessing App.Document attribute or method
Parameters
doc pointer to a document
cmd command string, streamable
See also
_cmdDocument()
Example:
cmdGuiDocument(doc, std::stringstream() << "getObject('" << objName << "')");
Translates to command (assuming doc's name is 'DocName', and and objName contains value 'ObjName'):
Gui.getDocument('DocName').getObject('ObjName')
Definition at line 214 of file CommandT.h.
Referenced by FemGui::TaskDlgMeshShapeNetgen::accept(), PartDesignGui::TaskPipeParameters::accept(), PartDesignGui::TaskDlgShapeBinder::accept(), PartDesignGui::TaskDlgFeatureParameters::accept(), PartGui::TaskDlgAttacher::accept(), FemGui::TaskDlgPost::accept(), CmdTestCmdFuncs::activated(), PartDesignGui::makeBodyActive(), FemGui::TaskDlgMeshShapeNetgen::reject(), PartDesignGui::TaskDlgShapeBinder::reject(), PartDesignGui::TaskDlgFeatureParameters::reject(), FemGui::TaskDlgPost::reject(), and PartDesignGui::setEdit().
cmdGuiDocument() [2/3]
template<typename T > void Gui::cmdGuiDocument (const App::DocumentObject * obj, T && cmd) inline
Runs a command for accessing an object's Gui::Document attribute or method This function is an alternative to FCMD_VOBJ_DOC_CMD
Parameters
obj pointer to a DocumentObject
cmd command string, streamable
Definition at line 300 of file CommandT.h.
cmdGuiDocument() [3/3]
template<typename T > void Gui::cmdGuiDocument (const std::string & doc, T && cmd) inline
Runs a command for accessing App.Document attribute or method
Parameters
doc document name
cmd command string, streamable
See also
_cmdDocument()
Example:
cmdGuiDocument(doc, std::stringstream() << "getObject('" << objName << "')");
Translates to command (assuming doc's name is 'DocName', and and objName contains value 'ObjName'):
Gui.getDocument('DocName').getObject('ObjName')
Definition at line 236 of file CommandT.h.
References _cmdDocument(), and Gui::Command::Doc.
cmdGuiObject()
template<typename T > void Gui::cmdGuiObject (const App::DocumentObject * obj, T && cmd) inline
Runs a command for accessing an view object's attribute or method This function is an alternative to FCMD_VOBJ_CMD
Parameters
obj pointer to a DocumentObject
cmd command string, streamable
See also
_cmdObject()
Definition at line 351 of file CommandT.h.
Referenced by CmdTestCmdFuncs::activated(), and PartDesignGui::TaskPipeParameters::~TaskPipeParameters().
cmdGuiObjectArgs()
template<typename... Args> void Gui::cmdGuiObjectArgs (const App::DocumentObject * obj, const std::string & cmd, Args &&... args)
Runs a command for accessing a view object's attribute or method This function is an alternative to FCMD_VOBJ_CMD2
Parameters
cmd command string, supporting printf like formatter
obj pointer to a DocumentObject
See also
cmdAppObjectArgs()
Definition at line 424 of file CommandT.h.
Referenced by CmdTestCmdFuncs::activated().
cmdSetEdit()
void Gui::cmdSetEdit (const App::DocumentObject * obj, int mod = 0) inline
Runs a command to start editing a give object This function is an alternative to FCMD_SET_EDIT
Parameters
obj pointer to a DocumentObject
Unlike other helper functions, this one editing the object using the current active document, instead of the object's owner document. This allows in-place editing an object, which may be brought in through linking to an external group.
Definition at line 374 of file CommandT.h.
Referenced by CmdTestCmdFuncs::activated().
coinRemoveAllChildren()
void Gui::coinRemoveAllChildren (SoGroup * node)
Helper function to deal with bug in SoNode::removeAllChildren()
See also
https://bitbucket.org/Coin3D/coin/pull-requests/119/fix-sochildlist-auditing/diff
Definition at line 70 of file Gui/ViewProvider.cpp.
References src.Mod.AddonManager.NetworkManager::count, SCL.Builtin::FALSE, FC_TRACE, and toolbit-attributes::group.
Referenced by Gui::View3DInventorSelection::checkGroupOnTop(), Gui::View3DInventorSelection::clearGroupOnTop(), Gui::ManualAlignment::continueAlignment(), PartGui::ViewProvider2DObjectGrid::createGrid(), Gui::LinkInfo::detach(), PartGui::GridExtensionP::drawGrid(), Gui::View3DInventorViewer::eraseAllDimensions(), PartGui::ViewProviderSplineExtension::extensionUpdateData(), Gui::LinkInfo::getSnapshot(), PartGui::ViewProvider2DObjectGrid::onChanged(), Gui::ManualAlignment::onClear(), Gui::SoFCColorGradient::rebuildGradient(), PartDesignGui::ViewProviderTransformed::recomputeFeature(), Gui::ManualAlignment::reset(), RobotGui::ViewProviderRobotObject::resetDragger(), Gui::LinkView::resetRoot(), Gui::ApplicationPy::sCoinRemoveAllChildren(), Gui::LinkView::setChildren(), Gui::SoFCColorLegend::setColorLegend(), Gui::SoFCPathAnnotation::setPath(), Gui::View3DInventorViewer::setupEditingRoot(), MeshGui::MeshFillHole::startEditing(), Gui::LinkView::SubInfo::unlink(), Gui::LinkView::Element::unlink(), PartDesignGui::ViewProviderTransformed::unsetEdit(), PartGui::ViewProvider2DObjectGrid::unsetEdit(), PartGui::ViewProviderMirror::unsetEdit(), Gui::LinkInfo::updateChildren(), Gui::ViewProviderVRMLObject::updateData(), RobotGui::ViewProviderRobotObject::updateData(), PartGui::ViewProviderCurveNet::updateData(), InspectionGui::ViewProviderInspection::updateData(), PartGui::ViewProvider2DObjectGrid::updateData(), MeshGui::ViewProviderMeshFaceSet::updateData(), FemGui::ViewProviderFemConstraintBearing::updateData(), FemGui::ViewProviderFemConstraintGear::updateData(), FemGui::ViewProviderFemConstraintPulley::updateData(), FemGui::ViewProviderFemConstraintFluidBoundary::updateData(), Gui::ViewProviderInventorObject::updateData(), MeshGui::ViewProviderMeshCurvature::updateData(), Gui::LinkView::updateLink(), SketcherGui::EditModeCoinManager::~EditModeCoinManager(), PartGui::GridExtensionP::~GridExtensionP(), and Gui::View3DInventorViewer::~View3DInventorViewer().
Control()
ControlSingleton& Gui::Control () inline
Get the global instance.
Definition at line 132 of file Control.h.
References Gui::ControlSingleton::instance().
Referenced by PartDesignGui::Workbench::activated(), RobotGui::Workbench::activated(), StdCmdTransform::activated(), StdCmdPlacement::activated(), StdCmdTextureMapping::activated(), Gui::TaskView::ControlPy::activeDialog(), Gui::TaskView::ControlPy::activeTaskDialog(), Gui::Workbench::addTaskWatcher(), Gui::TaskView::ControlPy::addTaskWatcher(), Gui::Document::canClose(), PartGui::ViewProviderPartExt::changeFaceAppearances(), Gui::OverlayTabWidget::checkAutoHide(), Gui::TaskView::ControlPy::clearTaskWatcher(), Gui::TaskMeasure::close(), Gui::TaskView::ControlPy::closeDialog(), RobotGui::ViewProviderEdge2TracObject::doubleClicked(), FemGui::ViewProviderSetNodes::doubleClicked(), FemGui::ViewProviderSetElementNodes::doubleClicked(), exec2LineCenterLine(), exec2PointCenterLine(), execCenterLine(), execComplexSection(), execCosmeticCircle(), execCosmeticVertex(), execLine2Points(), execSimpleSection(), PartGui::ViewProviderAttachExtension::extensionSetupContextMenu(), TechDrawGui::TaskSectionView::failNoObject(), TechDrawGui::TaskComplexSection::failNoObject(), StdCmdTransform::isActive(), StdCmdEdit::isActive(), StdCmdToggleNavigation::isActive(), CmdPartDesignCompDatums::isActive(), CmdPartDesignCompSketches::isActive(), StdCmdTextureMapping::isActive(), Gui::TaskView::ControlPy::isAllowedAlterDocument(), Gui::TaskView::ControlPy::isAllowedAlterSelection(), Gui::TaskView::ControlPy::isAllowedAlterView(), AssemblyGui::ViewProviderAssembly::keyPressed(), TechDrawGui::QGIEdge::mouseDoubleClickEvent(), TechDrawGui::ViewProviderBalloon::onDelete(), TechDrawGui::ViewProviderDimension::onDelete(), PartDesignGui::TaskFeaturePick::onDoubleClick(), PartDesignGui::TaskFeaturePick::onSelectionChanged(), PartGui::PropertyEnumAttacherItem::openTask(), prepareProfileBased(), Gui::Workbench::removeTaskWatcher(), Gui::OverlayManager::restore(), Gui::DocumentP::setDocumentNameOfTaskDialog(), SurfaceGui::ViewProviderGeomFillSurface::setEdit(), TechDrawGui::ViewProviderGeomHatch::setEdit(), TechDrawGui::ViewProviderHatch::setEdit(), TechDrawGui::ViewProviderLeader::setEdit(), SurfaceGui::ViewProviderSections::setEdit(), SurfaceGui::ViewProviderFilling::setEdit(), RobotGui::ViewProviderEdge2TracObject::setEdit(), FemGui::ViewProviderSetNodes::setEdit(), RobotGui::ViewProviderTrajectoryCompound::setEdit(), RobotGui::ViewProviderTrajectoryDressUp::setEdit(), FemGui::ViewProviderFemConstraintPressure::setEdit(), FemGui::ViewProviderFemConstraintRigidBody::setEdit(), FemGui::ViewProviderFemConstraintSpring::setEdit(), PathGui::ViewProviderPathCompound::setEdit(), PartDesignGui::ViewProviderShapeBinder::setEdit(), FemGui::ViewProviderFemMeshShapeNetgen::setEdit(), PartGui::ViewProviderPrimitive::setEdit(), PartGui::ViewProviderProjectOnSurface::setEdit(), FemGui::ViewProviderFemConstraintBearing::setEdit(), FemGui::ViewProviderFemConstraintGear::setEdit(), FemGui::ViewProviderFemConstraintPulley::setEdit(), PartDesignGui::ViewProviderPrimitive::setEdit(), PartDesignGui::ViewProviderHole::setEdit(), FemGui::ViewProviderFemConstraintFixed::setEdit(), FemGui::ViewProviderFemConstraintFluidBoundary::setEdit(), FemGui::ViewProviderFemConstraintForce::setEdit(), FemGui::ViewProviderFemConstraintContact::setEdit(), FemGui::ViewProviderFemConstraintPlaneRotation::setEdit(), FemGui::ViewProviderFemConstraintDisplacement::setEdit(), FemGui::ViewProviderFemConstraintHeatflux::setEdit(), FemGui::ViewProviderFemConstraintTemperature::setEdit(), FemGui::ViewProviderFemConstraintInitialTemperature::setEdit(), FemGui::ViewProviderFemConstraintTransform::setEdit(), TechDrawGui::ViewProviderWeld::setEdit(), PartGui::ViewProviderFillet::setEdit(), TechDrawGui::ViewProviderViewSection::setEdit(), Gui::ViewProviderDragger::setEdit(), PartDesignGui::ViewProviderBoolean::setEdit(), TechDrawGui::ViewProviderProjGroup::setEdit(), FemGui::ViewProviderFemPostObject::setEdit(), PartDesignGui::ViewProvider::setEdit(), TechDrawGui::ViewProviderBalloon::setEdit(), TechDrawGui::ViewProviderViewPart::setEdit(), PartGui::ViewProviderChamfer::setEdit(), PartDesignGui::ViewProviderDatum::setEdit(), TechDrawGui::ViewProviderDimension::setEdit(), FemGui::ViewProviderFemPostFunction::setEdit(), PartGui::ViewProviderOffset::setEdit(), PartGui::ViewProviderThickness::setEdit(), Gui::ViewProviderLink::setEdit(), SketcherGui::ViewProviderSketch::setEdit(), Gui::ViewProviderLink::setEditViewer(), PartGui::ViewProviderAttachExtension::showAttachmentEditor(), Gui::TaskView::ControlPy::showDialog(), Gui::TaskView::ControlPy::showModelView(), Gui::TaskView::ControlPy::showTaskView(), PartGui::FaceAppearances::slotDeleteDocument(), Gui::ElementColors::slotDeleteDocument(), PartDesignGui::TaskFeaturePick::slotDeleteDocument(), PartGui::FaceAppearances::slotDeleteObject(), Gui::ElementColors::slotDeleteObject(), PartGui::FaceAppearances::slotUndoDocument(), PartDesignGui::TaskFeaturePick::slotUndoDocument(), Gui::Command::testActive(), SurfaceGui::ViewProviderGeomFillSurface::unsetEdit(), SurfaceGui::ViewProviderSections::unsetEdit(), RobotGui::ViewProviderTrajectoryCompound::unsetEdit(), RobotGui::ViewProviderTrajectoryDressUp::unsetEdit(), PathGui::ViewProviderPathCompound::unsetEdit(), PartGui::ViewProviderPrimitive::unsetEdit(), PartGui::ViewProviderProjectOnSurface::unsetEdit(), FemGui::ViewProviderFemConstraint::unsetEdit(), TechDrawGui::ViewProviderProjGroupItem::unsetEdit(), PartGui::ViewProviderFillet::unsetEdit(), Gui::ViewProviderDragger::unsetEdit(), FemGui::ViewProviderFemPostObject::unsetEdit(), PartDesignGui::ViewProvider::unsetEdit(), PartDesignGui::ViewProviderDatum::unsetEdit(), PartGui::ViewProviderChamfer::unsetEdit(), FemGui::ViewProviderFemAnalysis::unsetEdit(), FemGui::ViewProviderFemPostFunction::unsetEdit(), PartGui::ViewProviderOffset::unsetEdit(), PartGui::ViewProviderThickness::unsetEdit(), SketcherGui::ViewProviderSketch::unsetEdit(), and Gui::TaskView::TaskView::updateWatcher().
copyVisualT()
template<typename... Args> void Gui::copyVisualT (Args &&... args)
Copy visual attributes from a source to a target object
Definition at line 477 of file CommandT.h.
Referenced by CmdTestCmdFuncs::activated().
CreateDocCommands()
void Gui::CreateDocCommands ()
Definition at line 2001 of file CommandDoc.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by Gui::Application::createStandardOperations().
CreateFeatCommands()
void Gui::CreateFeatCommands ()
Definition at line 301 of file CommandFeat.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by Gui::Application::createStandardOperations().
CreateLinkCommands()
void Gui::CreateLinkCommands ()
Definition at line 913 of file CommandLink.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by Gui::Application::createStandardOperations().
CreateMacroCommands()
void Gui::CreateMacroCommands ()
Definition at line 307 of file CommandMacro.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by Gui::Application::createStandardOperations().
CreateStdCommands()
void Gui::CreateStdCommands ()
Definition at line 977 of file CommandStd.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by Gui::Application::createStandardOperations().
CreateStructureCommands()
void Gui::CreateStructureCommands ()
Definition at line 181 of file CommandStructure.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by Gui::Application::createStandardOperations().
CreateTestCommands()
void Gui::CreateTestCommands ()
Definition at line 835 of file CommandTest.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by Gui::Application::createStandardOperations().
CreateViewStdCommands()
void Gui::CreateViewStdCommands ()
Definition at line 3971 of file CommandView.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), App::GetApplication(), App::Application::GetParameterGroupByPath(), Gui::Application::Instance, and ParameterGrp::SetASCII().
Referenced by Gui::Application::createStandardOperations().
CreateWindowStdCommands()
void Gui::CreateWindowStdCommands ()
Definition at line 506 of file CommandWindow.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by Gui::Application::createStandardOperations().
cursorBeyond()
bool Gui::cursorBeyond (const QTextCursor & cursor, const QTextCursor & limit, int shift = 0) inline
cursorBeyond checks if cursor is at a valid position to accept keyEvents.
Parameters
cursor - cursor to check
limit - cursor that marks the begin of the input region
shift - offset for shifting the limit for non-selection cursors [default: 0]
Returns
true if a keyEvent is ok at cursor's position, false otherwise
Definition at line 76 of file PythonConsole.cpp.
References RobotExample::pos.
Referenced by Gui::PythonConsole::contextMenuEvent(), Gui::PythonConsole::dropEvent(), and Gui::PythonConsole::keyPressEvent().
doCommandT()
template<typename... Args> void Gui::doCommandT (Gui::Command::DoCmd_Type cmdType, const std::string & cmd, Args &&... args)
Runs a command
Parameters
cmdType command type
cmd command string, supporting printf like formatter
Example:
doCommandT(Gui::Command::Gui, "Gui.getDocument(%s).getObject(%s).Visibility = %s", "DocName", "ObjName", visible?"True":"False");
Translates to command (assuming obj's document name is 'DocName', obj's name is 'ObjName', and visible is true):
Gui.getDocument('DocName').getObject('ObjName').Visibility = True
Definition at line 458 of file CommandT.h.
Referenced by CmdTestCmdFuncs::activated().
formatModuleError()
static std::string Gui::formatModuleError (const std::string & name) static
Definition at line 459 of file PythonWrapper.cpp.
References Path.Log::error().
Referenced by importPySide(), and importShiboken().
FreeCADGui_exportSubgraph()
static PyObject* Gui::FreeCADGui_exportSubgraph (PyObject * , PyObject * args) static
Definition at line 293 of file Gui/Application.cpp.
References toolbit-attributes::args, Base::InterpreterSingleton::convertSWIGPointerObj(), SCL.SimpleDataTypes::e, Base::Interpreter(), Path.Post.scripts.refactored_centroid_post::str, Gui::SoFCDB::writeNodesToString(), and Gui::SoFCDB::writeToVRML().
FreeCADGui_getSoDBVersion()
static PyObject* Gui::FreeCADGui_getSoDBVersion (PyObject * , PyObject * args) static
Definition at line 335 of file Gui/Application.cpp.
References toolbit-attributes::args.
FreeCADGui_subgraphFromObject()
static PyObject* Gui::FreeCADGui_subgraphFromObject (PyObject * , PyObject * args) static
Definition at line 227 of file Gui/Application.cpp.
References toolbit-attributes::args, Base::Type::createInstanceByName(), Base::InterpreterSingleton::createSWIGPointerObj(), SCL.SimpleDataTypes::e, App::ExtensionContainer::getPropertyMap(), App::DocumentObject::getViewProviderName(), Base::Interpreter(), Base::BaseClass::is(), modes, Py::new_reference_to(), src.Mod.Test.testPathArray::o, and Path.Post.scripts.grbl_post::type.
getMainWindow()
MainWindow* Gui::getMainWindow () inline
Definition at line 367 of file MainWindow.h.
References Gui::MainWindow::getInstance().
Referenced by _checkDrawViewPartBalloon(), TechDrawGui::_checkSel(), TechDrawGui::_checkSelAndObj(), TechDrawGui::_checkSelection(), _checkSelection(), _checkSelectionBalloon(), _checkSelectionHatch(), TechDrawGui::_checkSelObjAndSubs(), TechDrawGui::_createThreadLines(), TechDrawGui::TaskCosVertex::abandonEditSession(), TechDrawGui::TaskLeaderLine::abandonEditSession(), Gui::Dialog::DlgProjectInformationImp::accept(), Gui::Dialog::DlgAddProperty::accept(), Gui::Dialog::DlgMacroExecuteImp::accept(), TechDrawGui::TaskProjection::accept(), FemGui::TaskDlgMeshShapeNetgen::accept(), PartDesignGui::TaskDlgDatumParameters::accept(), TechDrawGui::TaskDimension::accept(), PartDesignGui::TaskPipeParameters::accept(), Gui::Dialog::DlgActivateWindowImp::accept(), PartDesignGui::TaskDlgFeatureParameters::accept(), TechDrawGui::TechDrawHandler::activate(), StdCmdDlgMacroRecord::activated(), StdCmdTileWindows::activated(), Std_TestQM::activated(), SpreadsheetGui::Workbench::activated(), StdCmdLinkMakeGroup::activated(), StdCmdWorkbench::activated(), StdCmdCascadeWindows::activated(), StdCmdOpen::activated(), draftguitools.gui_annotationstyleeditor.AnnotationStyleEditor::Activated(), RobotGui::Workbench::activated(), StdCmdDlgMacroExecute::activated(), StdCmdCloseActiveWindow::activated(), Gui::StdCmdDownloadOnlineHelp::activated(), Gui::StdCmdPythonHelp::activated(), StdOrthographicCamera::activated(), StdCmdCloseAllWindows::activated(), StdCmdActivateNextWindow::activated(), StdPerspectiveCamera::activated(), Gui::BlankWorkbench::activated(), StdCmdActivatePrevWindow::activated(), StdCmdImport::activated(), StdCmdLinkMake::activated(), StdCmdAbout::activated(), StdCmdWindows::activated(), TDHandlerDimension::activated(), StdCmdViewSaveCamera::activated(), StdCmdUserInterface::activated(), StdCmdViewRestoreCamera::activated(), StdCmdLinkMakeRelative::activated(), StdCmdExport::activated(), StdCmdRestartInSafeMode::activated(), StdCmdDlgParameter::activated(), StdCmdDlgPreferences::activated(), StdCmdStatusBar::activated(), StdCmdDlgCustomize::activated(), StdCmdCommandLine::activated(), StdCmdOnlineHelp::activated(), StdCmdMergeProjects::activated(), StdCmdLinkImport::activated(), CmdSandboxMeshLoader::activated(), StdCmdToggleClipPlane::activated(), StdCmdDependencyGraph::activated(), StdCmdLinkImportAll::activated(), StdCmdExportDependencyGraph::activated(), CmdTestMDI1::activated(), StdCmdLinkSelectLinked::activated(), CmdTestMDI2::activated(), CmdTestMDI3::activated(), StdCmdLinkSelectLinkedFinal::activated(), StdCmdLinkSelectAllLinks::activated(), StdCmdRevert::activated(), Gui::MacroCommand::activated(), StdCmdUnitsCalculator::activated(), StdCmdProjectInfo::activated(), StdCmdProjectUtil::activated(), StdCmdPrint::activated(), StdCmdPrintPreview::activated(), StdCmdReloadStyleSheet::activated(), StdCmdPrintPdf::activated(), StdCmdQuit::activated(), StdCmdCopy::activated(), StdCmdPaste::activated(), NaviCubeDraggableCmd::activated(), StdCmdDuplicateSelection::activated(), StdCmdDelete::activated(), StdCmdRefresh::activated(), StdCmdEdit::activated(), StdMainFullscreen::activated(), StdViewDockUndockFullscreen::activated(), StdViewScreenShot::activated(), StdViewLoadImage::activated(), StdCmdToggleNavigation::activated(), StdCmdAxisCross::activated(), StdViewBoxZoom::activated(), StdBoxSelection::activated(), StdBoxElementSelection::activated(), StdCmdTreeCollapse::activated(), StdCmdTreeExpand::activated(), StdCmdTreeSelectAllInstances::activated(), StdCmdSceneInspector::activated(), StdCmdDemoMode::activated(), StdTreeDrag::activated(), StdStoreWorkingView::activated(), StdRecallWorkingView::activated(), Gui::RecentMacrosAction::activateFile(), activateHandler(), Gui::Application::activateWorkbench(), Gui::Dialog::DlgCustomToolbarsImp::addCustomCommand(), Gui::Dialog::DlgCustomToolbarsImp::addCustomToolbar(), Gui::DockWindowManager::addDockWindow(), Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::addSelections(), Gui::DockWidgetAction::addTo(), Gui::ToolBarAction::addTo(), Gui::WindowAction::addTo(), Gui::ToolBarManager::addToolBarToArea(), Gui::OverlayTabWidget::addWidget(), OverlayInfo::addWidget(), Gui::ManualAlignment::align(), RemoteDebugger::attachToRemoteDebugger(), SpreadsheetGui::ViewProviderSheet::beforeDelete(), Gui::WorkbenchTabWidget::buildPrefMenu(), Gui::ProgressDialog::canAbort(), Gui::ProgressBar::canAbort(), Gui::ManualAlignment::cancel(), Gui::Document::canClose(), Gui::MDIView::changeEvent(), Gui::MainWindow::changeEvent(), Gui::OverlayTabWidget::checkAutoHide(), checkCanonicalPath(), Gui::Application::checkForRecomputes(), FemGui::ViewProviderFemAnalysis::checkSelectedChildren(), Gui::SelectionSingleton::clearCompleteSelection(), Gui::SelectionSingleton::clearSelection(), Gui::Document::cloneView(), Gui::MainWindow::closeAllDocuments(), Gui::EditorView::closeEvent(), Gui::TextDocumentEditorView::closeEvent(), Gui::GUIApplication::commitData(), Gui::PropertyEditor::PropertyEditor::contextMenuEvent(), Gui::ManualAlignment::continueAlignment(), StdCmdWorkbench::createAction(), StdCmdLinkMakeGroup::createAction(), Gui::StdCmdDownloadOnlineHelp::createAction(), StdCmdRecentFiles::createAction(), StdCmdRecentMacros::createAction(), StdCmdAbout::createAction(), StdCmdDockViewMenu::createAction(), StdCmdFreezeViews::createAction(), StdCmdToolBarMenu::createAction(), Gui::Command::createAction(), StdCmdStatusBar::createAction(), StdCmdWindowsMenu::createAction(), StdCmdDrawStyle::createAction(), Gui::GroupCommand::createAction(), Gui::PythonCommand::createAction(), Gui::PythonGroupCommand::createAction(), Gui::MacroCommand::createAction(), StdCmdUserEditMode::createAction(), StdCmdUndo::createAction(), StdCmdRedo::createAction(), CmdSketcherGrid::createAction(), CmdSketcherSnap::createAction(), CmdRenderingOrder::createAction(), StdViewDockUndockFullscreen::createAction(), StdCmdExpression::createAction(), TechDrawGui::TaskActiveView::createActiveView(), TechDrawGui::ViewProviderPage::createMDIViewPage(), Gui::MainWindow::createMimeDataFromSelection(), PartDesignGui::SketchWorkflow::createSketch(), Gui::Document::createView(), MeshGui::ViewProviderMeshCurvature::curvatureInfoCallback(), InspectionGui::ViewProviderProxyObject::customEvent(), Gui::SoFCColorGradient::customize(), TechDrawGui::TechDrawHandler::deactivate(), Gui::BlankWorkbench::deactivated(), TDHandlerDimension::deactivated(), FemGui::TaskCreateElementSet::DefineNodes(), PartDesignGui::WorkflowManager::determineWorkflow(), draftguitools.gui_snapper.Snapper::device_pixel_ratio(), Gui::DimensionWidget::DimensionWidget(), femsolver.report::displayGui(), Gui::DocumentObjectItem::displayStatusInfo(), Gui::Dialog::DlgActivateWindowImp::DlgActivateWindowImp(), Gui::Dialog::DlgCustomizeImp::DlgCustomizeImp(), Gui::ViewProviderTextDocument::doubleClicked(), DrawingGui::ViewProviderDrawingPage::doubleClicked(), Gui::ViewProviderVarSet::doubleClicked(), Gui::TDragger::drag(), Gui::TPlanarDragger::drag(), Gui::RDragger::drag(), Gui::OverlayManager::Private::dragDockWidget(), Gui::OverlayGraphicsEffect::draw(), dressupGetSelected(), Gui::View3DInventor::dropEvent(), Gui::View3DInventorViewer::dropEvent(), Gui::EditorView::EditorView(), StartGui::StartLauncher::EnsureLaunched(), Gui::GUIApplication::event(), Gui::OverlayManager::eventFilter(), Gui::ProgressBar::eventFilter(), FilterStatusBar::eventFilter(), SketcherGui::EditDatumDialog::exec(), exec2LineCenterLine(), exec2PointCenterLine(), execCascadeHorizDimension(), execCascadeObliqueDimension(), execCascadeVertDimension(), execCenterLine(), execComplexSection(), execCosmeticCircle(), execCosmeticVertex(), execDim(), execExtent(), TechDrawGui::execHoleCircle(), execLine2Points(), execPosHorizChainDimension(), execPosObliqueChainDimension(), execPosVertChainDimension(), execSimpleSection(), Gui::PythonEditorView::executeScript(), CommandInsertNewPart.TaskAssemblyNewPart::expandLinkManually(), SpreadsheetGui::ViewProviderSheet::exportAsFile(), Gui::SelectModule::exportHandler(), Gui::Application::exportTo(), Gui::ViewProviderGroupExtension::extensionOnDelete(), TechDrawGui::TaskSectionView::failNoObject(), TechDrawGui::TaskComplexSection::failNoObject(), draftutils.utils::filter_objects_for_modifiers(), TechDrawGui::DrawGuiUtil::findPage(), Gui::ManualAlignment::finish(), draftutils.gui_utils::get_3d_view(), draftguitools.gui_snapper.Snapper::get_snap_toolbar(), Gui::Document::getActiveView(), Gui::OverlayTabWidget::getAutoHideRect(), PartDesignGui::getBody(), PartDesignGui::getBodyFor(), getConstraintPrerequisits(), Gui::Dialog::DownloadManager::getInstance(), getListOfSelectedGeoIds(), Gui::ViewProviderLink::getOverlayPixmap(), PartDesignGui::getPartFor(), Gui::MacroManager::getPythonConsole(), PartDesignGui::getReferencedSelection(), TechDraw::CommandHelpers::getSelectedSubElements(), Gui::ToolHandler::getViewer(), PartGui::TaskCheckGeometryResults::goCheck(), Gui::SoFCSelection::handleEvent(), draftutils.init_draft_statusbar::hide_draft_statusbar(), Gui::PythonDebugger::hideDebugMarker(), Gui::OverlayProxyWidget::hitTest(), Gui::Application::importFrom(), Gui::SelectModule::importHandler(), draftutils.init_draft_statusbar::init_draft_statusbar_scale(), draftutils.init_draft_statusbar::init_draft_statusbar_snap(), Gui::MainWindow::insertFromMimeData(), InspectionGui::ViewProviderInspection::inspectCallback(), TestGui::UnitTestDialog::instance(), MeshGui::DockEvaluateMeshImp::instance(), StdCmdTileWindows::isActive(), StdCmdCascadeWindows::isActive(), StdCmdCloseActiveWindow::isActive(), StdOrthographicCamera::isActive(), StdCmdCloseAllWindows::isActive(), StdCmdActivateNextWindow::isActive(), StdPerspectiveCamera::isActive(), StdCmdActivatePrevWindow::isActive(), StdCmdFreezeViews::isActive(), StdCmdStatusBar::isActive(), StdCmdToggleClipPlane::isActive(), CmdTestMDI1::isActive(), CmdTestMDI2::isActive(), CmdTestMDI3::isActive(), StdCmdPaste::isActive(), NaviCubeDraggableCmd::isActive(), StdViewDock::isActive(), StdViewUndock::isActive(), StdViewFullscreen::isActive(), StdViewDockUndockFullscreen::isActive(), StdCmdToggleNavigation::isActive(), StdCmdAxisCross::isActive(), StdCmdTextureMapping::isActive(), StdStoreWorkingView::isActive(), StdRecallWorkingView::isActive(), Gui::OverlayTabWidget::isTransparent(), draftutils.init_draft_statusbar::label_to_scale(), Gui::Dialog::AboutDialog::linkActivated(), linkConvert(), Gui::MainWindow::MainWindow(), Automation::makeSnapshotWithGui(), ImportGui::Module::Module(), TechDrawGui::QGIViewAnnotation::mouseDoubleClickEvent(), Gui::DAG::Model::mouseDoubleClickEvent(), Gui::TreeView::mouseDoubleClickEvent(), Gui::OverlayTitleBar::mousePressEvent(), Gui::OverlaySplitterHandle::mousePressEvent(), Gui::Dialog::DlgCustomToolbarsImp::moveDownCustomCommand(), Gui::Dialog::DlgCustomToolbarsImp::moveUpCustomCommand(), PartDesignGui::needActiveBodyError(), Notify(), Gui::OverlayManager::Private::onAction(), Gui::Dialog::DlgMacroRecordImp::onButtonStartClicked(), PartGui::DlgPartImportIgesImp::onChooseFileName(), PartGui::DlgPartImportStepImp::onChooseFileName(), TechDrawGui::ViewProviderLeader::onDelete(), TechDrawGui::ViewProviderTemplate::onDelete(), TechDrawGui::ViewProviderPage::onDelete(), TechDrawGui::ViewProviderProjGroup::onDelete(), TechDrawGui::ViewProviderProjGroupItem::onDelete(), TechDrawGui::ViewProviderWeld::onDelete(), TechDrawGui::ViewProviderBalloon::onDelete(), TechDrawGui::ViewProviderViewPart::onDelete(), TechDrawGui::ViewProviderDimension::onDelete(), Gui::Dialog::RedoDialog::onFetchInfo(), Gui::Dialog::UndoDialog::onFetchInfo(), Gui::PythonConsole::onInsertFileName(), Gui::Application::onLastWindowClosed(), Gui::OverlayTabWidget::onSizeGripMove(), Gui::TreeWidget::onStartEditing(), Gui::OverlayManager::Private::onTimer(), TechDrawGui::TaskCosVertex::onTrackerClicked(), TechDrawGui::TaskLeaderLine::onTrackerClicked(), TechDrawGui::TaskLeaderLine::onTrackerFinished(), Gui::Application::open(), Gui::Document::openEditingView3D(), OpenURLInBrowser(), Gui::OverlayManager::OverlayManager(), SpreadsheetGui::SheetTableView::pasteClipboard(), StdCmdExpression::pasteExpressions(), Gui::Dialog::ApplicationCache::performAction(), prepareProfileBased(), prepareTransformed(), TechDrawGui::MDIViewPage::printAllPages(), Gui::View3DInventorViewer::printDimension(), TechDrawGui::MDIViewPage::printPdf(), printPreselectionInfo(), Gui::ManualAlignment::probePickedCallback(), TechDrawGui::Grabber3d::quickView(), TechDrawGui::TaskCosmeticCircle::radiusChanged(), TechDrawGui::TaskDimension::reject(), Gui::Dialog::DlgCustomToolbarsImp::removeCustomCommand(), Gui::Dialog::DlgCustomToolbarsImp::removeCustomToolbar(), Gui::TaskView::TaskView::removeDialog(), Gui::DockWindowManager::removeDockWindow(), TechDrawGui::ViewProviderPage::removeMDIView(), Gui::OverlayTabWidget::removeWidget(), Gui::Dialog::DlgCustomToolbarsImp::renameCustomToolbar(), Gui::SequencerBar::resetData(), Gui::OverlayTabWidget::restore(), Gui::ToolBarAreaWidget::restoreState(), Gui::ToolBarManager::restoreState(), Gui::MainWindowP::restoreWindowState(), Gui::MenuManager::retranslate(), Gui::SelectionSingleton::rmvPreselect(), Gui::SelectionSingleton::rmvSelection(), Gui::Application::runApplication(), Gui::Document::save(), Gui::Document::saveAll(), Gui::Document::saveAs(), Gui::Document::saveCopy(), Gui::AutoSaver::saveDocument(), TechDrawGui::MDIViewPage::saveDXF(), TechDrawGui::MDIViewPage::savePDF(), Gui::Dialog::DlgSettingsGeneral::saveSettings(), TechDrawGui::MDIViewPage::saveSVG(), Gui::ApplicationPy::sCreateViewer(), Gui::PropertyEditor::LinkSelection::select(), SpreadsheetGui::SheetTableView::selectionChanged(), Gui::SelectionSingleton::selStackGoBack(), Gui::SelectionSingleton::selStackGoForward(), Gui::Application::sendHasMsgToActiveView(), Gui::Application::sendHasMsgToFocusView(), Gui::StatusBarObserver::SendLog(), Gui::Application::sendMsgToActiveView(), Gui::Application::sendMsgToFocusView(), Gui::SequencerDialog::SequencerDialog(), Gui::Document::setActiveView(), Gui::Document::setActiveWindow(), SpreadsheetGui::WorkbenchHelper::setBackgroundColor(), Gui::View3DInventor::setCurrentViewMode(), Gui::MDIView::setCurrentViewMode(), draftguitools.gui_snapper.Snapper::setCursor(), femsolver.solverbase.ViewProxy::setEdit(), FemGui::ViewProviderFemMeshShapeNetgen::setEdit(), SketcherGui::ViewProviderSketch::setEdit(), Gui::OverlayManager::setFocusView(), SpreadsheetGui::WorkbenchHelper::setForegroundColor(), Gui::OverlayManager::Private::setOverlayMode(), Gui::SelectionSingleton::setPreselect(), PartDesignGui::TaskBoxPrimitives::setPrimitive(), Gui::OverlayTabWidget::setRect(), Gui::SelectionSingleton::setSelection(), Gui::PropertyView::setShowAll(), Gui::StdCmdDescription::setSource(), Gui::Application::setStyleSheet(), Gui::SequencerBar::setText(), Gui::MenuManager::setup(), Gui::ToolBarManager::setup(), Gui::ViewProviderLink::setupContextMenu(), Gui::ToolBarManager::setupToolBarIconSize(), Gui::ApplicationPy::sGetMainWindow(), SpreadsheetGui::SheetView::SheetView(), draftutils.init_draft_statusbar::show_draft_statusbar(), draftguitools.gui_snapper.Snapper::show_hide_grids(), Gui::ToolBarManager::showContextMenu(), Gui::PythonDebugger::showDebugMarker(), ImportGui::OCAFBrowser::showDialog(), Gui::TaskView::TaskView::showDialog(), DrawingGui::ViewProviderDrawingPage::showDrawingView(), Gui::EditorView::showEvent(), Gui::TextDocumentEditorView::showEvent(), Gui::ManualAlignment::showInstructions(), TechDrawGui::ViewProviderDrawingView::showProgressMessage(), Gui::SequencerBar::showRemainingTime(), MatGui::MaterialSave::showSelectedTree(), SpreadsheetGui::ViewProviderSheet::showSheetMdi(), SpreadsheetGui::ViewProviderSheet::showSpreadsheetView(), TechDrawGui::MDIViewPage::showStatusMsg(), Gui::Application::slotActiveDocument(), Gui::Document::slotChangedObject(), Gui::Document::slotChangePropertyEditor(), Gui::SelectionSingleton::slotDeletedObject(), draftutils.params.ParamObserverView::slotParamChanged(), Gui::Document::slotRecomputed(), Gui::Document::slotRedoDocument(), Gui::Document::slotTouchedObject(), Gui::Document::slotUndoDocument(), TechDrawGui::TaskDimRepair::slotUseSelection(), Gui::ApplicationPy::sSetActiveDocument(), Gui::ApplicationPy::sShowPreferences(), Gui::ApplicationPy::sShowPreferencesByName(), PartGui::BoxSelection::start(), Gui::ManualAlignment::startAlignment(), TechDrawGui::TaskCosVertex::startTracker(), TechDrawGui::TaskLeaderLine::startTracker(), Gui::MainWindow::switchToTopLevelMode(), FemGui::TaskCreateElementSet::TaskCreateElementSet(), Gui::DocumentObjectItem::testStatus(), Gui::OverlayManager::Private::toggleOverlay(), Gui::ToolBarManager::toolBarArea(), Gui::ToolBarManager::toolBars(), Gui::Application::tryClose(), Gui::ToolBar::undock(), UnifiedDatumCommand(), SketcherGui::ViewProviderSketch::unsetEdit(), Gui::Application::updateActions(), Gui::ModuleIO::verifyFile(), MeshPartGui::CurveOnMeshHandler::Private::vertexCallback(), Gui::Application::viewActivated(), InspectionGui::VisualInspection::VisualInspection(), SandboxGui::Workbench::Workbench(), Gui::WorkbenchGroup::WorkbenchGroup(), Gui::CommandBase::~CommandBase(), Gui::MDIView::~MDIView(), Gui::View3DInventorViewer::~View3DInventorViewer(), and SpreadsheetGui::ViewProviderSheet::~ViewProviderSheet().
getPreselectionInfo()
QString Gui::getPreselectionInfo (const char * documentName, const char * objectName, const char * subElementName, float x, float y, float z, double precision)
Definition at line 717 of file Gui/Selection.cpp.
References Base::UnitsApi::getDecimals(), KDL::min(), draftgeoutils.general::precision(), schemaTranslatePoint(), MovieTool::x, and MovieTool::y.
Referenced by printPreselectionInfo().
getPySideModuleName()
static std::string Gui::getPySideModuleName (const std::string & moduleName) static
Definition at line 304 of file PythonWrapper.cpp.
References ModulePySide.
Referenced by importPySide(), and loadPySideModule().
GetWidgetFactorySupplier()
WidgetFactorySupplier& Gui::GetWidgetFactorySupplier () inline
Definition at line 246 of file WidgetFactory.h.
References Gui::WidgetFactorySupplier::instance().
Referenced by Gui::Application::Application(), and Gui::Dialog::DlgCustomizeImp::DlgCustomizeImp().
importPySide()
static PyObject* Gui::importPySide (const std::string & moduleName) static
Definition at line 475 of file PythonWrapper.cpp.
References formatModuleError(), and getPySideModuleName().
Referenced by qt_identifyType(), and qt_wrapInstance().
importShiboken()
static PyObject* Gui::importShiboken () static
Definition at line 465 of file PythonWrapper.cpp.
References formatModuleError(), and ModuleShiboken.
Referenced by qt_getCppType(), and qt_wrapInstance().
isTreeViewDragging()
GuiExport bool Gui::isTreeViewDragging ()
Definition at line 1635 of file Tree.cpp.
References _DraggingActive.
Referenced by Gui::OverlayManager::eventFilter().
loadPySideModule()
static bool Gui::loadPySideModule (const std::string & moduleName, PyTypeObject **& types) static
Definition at line 316 of file PythonWrapper.cpp.
References getPySideModuleName().
Referenced by Gui::PythonWrapper::loadCoreModule(), Gui::PythonWrapper::loadGuiModule(), Gui::PythonWrapper::loadPrintSupportModule(), Gui::PythonWrapper::loadUiToolsModule(), and Gui::PythonWrapper::loadWidgetsModule().
Notification()
template<typename TNotifier , typename TCaption , typename TMessage > void Gui::Notification (TNotifier && notifier, TCaption && caption, TMessage && message) inline
Convenience function to send untranslated user notifications. The NotificationArea will attempt to find a translation in the "Notifications" context. This may be marked using QT_TRANSLATE_NOOP("Notifications","My message")
Definition at line 346 of file Notifications.h.
References Base::Notification, Notify(), Base::Untranslated, and Base::User.
Notify()
template<Base::LogStyle , Base::IntendedRecipient = Base::IntendedRecipient::User, Base::ContentType = Base::ContentType::Translated, typename TNotifier , typename TCaption , typename TMessage > void Gui::Notify (TNotifier && notifier, TCaption && caption, TMessage && message) inline
generic function to send any message provided by Base::LogStyle
Methods to seamlessly provide intrusive or non-intrusive notifications of error, warning, messages, translated notifications, or untranslated notifications originating in a given document object.
They are intended for easy substitution of currently blocking modal dialogs in which the user may only click 'ok'.
It produces a blocking modal notification or a non-intrusive non-modal notification depending on the preference parameter NotificationArea/NonIntrusiveNotificationsEnabled.
The notifier field can be a string or an App::DocumentObject * object, then the notifier is taken from the getFullLabel() method of the DocumentObject.
Translations:
An attempt is made by NotificationArea to translate the message using the "Notifications" context, except for messages which are already translated. Those that are untranslatable can only be send as messages intended for a developer directly using Console..
For the former, this may be marked using QT_TRANSLATE_NOOP("Notifications","My message")
For translated Notification, many modules using blocking notifications have their translations stored in other contexts, and the translations available at the callee function. This kind of notification provides a very low entry point to move existing blocking notifications into non-intrusive respecting the user choice (given by NotificationArea/NonIntrusiveNotificationsEnabled).
Example 1:
QMessageBox::warning(Gui::getMainWindow(), QObject::tr("Wrong selection"), QObject::tr("Cannot add a constraint between two external geometries."));
Can be rewritten as:
Gui::TranslatedNotification(obj, QObject::tr("Wrong selection"), QObject::tr("Cannot add a constraint between two external geometries."));
or
Gui::TranslatedUserWarning(obj, QObject::tr("Wrong selection"), QObject::tr("Cannot add a constraint between two external geometries."));
or
Gui::TranslatedUserError(obj, QObject::tr("Wrong selection"), QObject::tr("Cannot add a constraint between two external geometries.")); *
depending on the severity.
Here obj is a DocumentObject and serves to set the Notifier field for the notification. If the user preference is to see non-intrusive notifications, no pop-up will be shown and the notification will be shown in the notifications area. If the user preference is to see intrusive notifications, the pop-up will be shown (and it won't appear on the notification area as as a non- intrusive notification).
Definition at line 144 of file Notifications.h.
References Base::All, Base::Console(), Base::Developer, Base::Error, App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), getMainWindow(), App::Application::GetUserParameter(), Path.Op.Surface::msg, Base::ConsoleSingleton::Send(), src.Mod.AddonManager.Addon::translate, Base::Translated, Path.Post.scripts.grbl_post::type, Base::Untranslatable, Base::Untranslated, Path.Log::warning(), and Base::Warning.
Referenced by Notification(), NotifyError(), NotifyUserError(), NotifyUserWarning(), Base::PyObjectBase::setShouldNotify(), Base::PyObjectBase::shouldNotify(), TranslatedNotification(), TranslatedUserError(), and TranslatedUserWarning().
NotifyError()
template<typename TNotifier , typename TCaption , typename TMessage > void Gui::NotifyError (TNotifier && notifier, TCaption && caption, TMessage && message) inline
Convenience function to notify errors The NotificationArea will attempt to find a translation in the "Notifications" context. This may be marked using QT_TRANSLATE_NOOP("Notifications","My message")
Definition at line 305 of file Notifications.h.
References Base::All, Base::Error, Notify(), and Base::Untranslated.
Referenced by SketcherGui::DrawSketchHandlerTrimming::executeCommands().
NotifyUserError()
template<typename TNotifier , typename TCaption , typename TMessage > void Gui::NotifyUserError (TNotifier && notifier, TCaption && caption, TMessage && message) inline
Definition at line 315 of file Notifications.h.
References Base::Error, Notify(), Base::Untranslated, and Base::User.
Referenced by CmdSketcherConstrainPerpendicular::activated(), addConstraintSafely(), CmdSketcherConstrainPerpendicular::applyConstraint(), getListOfSelectedGeoIds(), SketcherGui::makeTangentToArcOfEllipseviaNewPoint(), SketcherGui::makeTangentToArcOfHyperbolaviaNewPoint(), SketcherGui::makeTangentToArcOfParabolaviaNewPoint(), SketcherGui::makeTangentToEllipseviaNewPoint(), SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsItemChanged(), DrawSketchHandlerBSplineInsertKnot::releaseButton(), DrawSketchHandlerCopy::releaseButton(), and DrawSketchHandlerRectangularArray::releaseButton().
NotifyUserWarning()
template<typename TNotifier , typename TCaption , typename TMessage > void Gui::NotifyUserWarning (TNotifier && notifier, TCaption && caption, TMessage && message) inline
Definition at line 284 of file Notifications.h.
References Notify(), Base::Untranslated, Base::User, and Base::Warning.
NotifyWarning()
template<typename TNotifier , typename TCaption , typename TMessage > void Gui::NotifyWarning (TNotifier && notifier, TCaption && caption, TMessage && message) inline
Convenience function to notify warnings The NotificationArea will attempt to find a translation in the "Notifications" context. This may be marked using QT_TRANSLATE_NOOP("Notifications","My message")
Definition at line 276 of file Notifications.h.
OpenURLInBrowser()
bool Gui::Gui::OpenURLInBrowser (const char * URL)
opens a URL in the system Browser
Definition at line 365 of file OnlineDocumentation.cpp.
References SCL.SimpleDataTypes::e, getMainWindow(), mod, src.Mod.PartDesign.fcgear.svggear::module, src.Mod.Test.testmakeWireString::String, and bimcommands.BimTutorial::URL.
Referenced by Gui::StdCmdPythonHelp::activated(), StdCmdOnlineHelpWebsite::activated(), StdCmdFreeCADDonation::activated(), StdCmdFreeCADWebsite::activated(), StdCmdFreeCADUserHub::activated(), StdCmdFreeCADPowerUserHub::activated(), StdCmdFreeCADForum::activated(), StdCmdFreeCADFAQ::activated(), StdCmdPythonWebsite::activated(), and StdCmdReportBug::activated().
operator&()
bool Gui::operator& (NotificationBox::Options lhs, NotificationBox::Options rhs) inline
Definition at line 133 of file NotificationBox.h.
operator|()
NotificationBox::Options Gui::operator| (NotificationBox::Options lhs, NotificationBox::Options rhs) inline
Definition at line 125 of file NotificationBox.h.
printPreselectionInfo()
void Gui::printPreselectionInfo (const char * documentName, const char * objectName, const char * subElementName, float x, float y, float z, double precision)
Definition at line 740 of file Gui/Selection.cpp.
References getMainWindow(), getPreselectionInfo(), draftgeoutils.general::precision(), Gui::MainWindow::showMessage(), MovieTool::x, and MovieTool::y.
Referenced by Gui::SoFCSelection::handleEvent(), and Gui::SelectionSingleton::setPreselectCoord().
promptEnd()
static const QChar Gui::promptEnd (QLatin1Char(' ')) static
Referenced by promptLength().
promptLength()
int Gui::promptLength (const QString & lineStr) inline
Definition at line 59 of file PythonConsole.cpp.
References promptEnd().
Referenced by Gui::PythonConsole::inputBegin(), and stripPromptFrom().
PROPERTY_SOURCE_TEMPLATE() [1/2]
Gui::PROPERTY_SOURCE_TEMPLATE (FemGui::ViewProviderFemMeshShapeBasePython , FemGui::ViewProviderFemMeshShapeBase)
PROPERTY_SOURCE_TEMPLATE() [2/2]
Gui::PROPERTY_SOURCE_TEMPLATE (PartDesignGui::ViewProviderSubShapeBinderPython , PartDesignGui::ViewProviderSubShapeBinder)
qt_getCppType()
template<typename qttype > qttype* Gui::qt_getCppType (PyObject * pyobj)
Definition at line 487 of file PythonWrapper.cpp.
References importShiboken(), and result.
qt_identifyType()
const char* Gui::qt_identifyType (QObject * ptr, const std::string & moduleName)
Definition at line 528 of file PythonWrapper.cpp.
References importPySide().
Referenced by Gui::PythonWrapper::createChildrenNameAttributes().
qt_wrapInstance()
template<typename qttype > Py::Object Gui::qt_wrapInstance (qttype object, const std::string & className, const std::string & moduleName)
Definition at line 503 of file PythonWrapper.cpp.
References importPySide(), and importShiboken().
renderDevBuildWarning()
static void Gui::renderDevBuildWarning (QPainter & painter, const QPoint startPosition, const QSize maxSize, QColor color) static
Displays a warning about this being a developer build. Designed for display in the Splashscreen.
Parameters
painter The painter to draw the warning into
startPosition The painter-space coordinates to start the warning box at.
maxSize The maximum extents for the box that is drawn. If the text exceeds this size it will be scaled down to fit.
Note
The text string is translatable, so its length is somewhat unpredictable. It is always displayed as two lines, regardless of the length of the text (e.g. no wrapping is done). Only the width is considered, the height simply follows from the font size.
Definition at line 176 of file SplashScreen.cpp.
References Gui::QtTools::horizontalAdvance(), and KDL::max().
Referenced by Gui::SplashScreen::splashImage().
schemaTranslatePoint()
std::array<std::pair<double, std::string>, 3> Gui::schemaTranslatePoint (double x, double y, double z, double precision)
Definition at line 691 of file Gui/Selection.cpp.
References Base::Quantity::MilliMetre, draftgeoutils.general::precision(), Base::UnitsApi::schemaTranslate(), Base::Quantity::setValue(), MovieTool::x, and MovieTool::y.
Referenced by getPreselectionInfo().
Selection()
SelectionSingleton& Gui::Selection () inline
Get the global instance.
Definition at line 756 of file Gui/Selection.h.
Referenced by _copyShape(), PartGui::Mirroring::accept(), PartGui::SweepWidget::accept(), DrawingGui::TaskProjection::accept(), TechDrawGui::TaskProjection::accept(), TechDrawGui::TaskDimRepair::accept(), SurfaceGui::FillingEdgePanel::accept(), ReenGui::FitBSplineSurfaceWidget::accept(), SurfaceGui::GeomFillSurface::accept(), MeshGui::TaskDecimating::accept(), MeshPartGui::Tessellation::accept(), SurfaceGui::SectionsPanel::accept(), SurfaceGui::FillingPanel::accept(), StdCmdLinkMakeGroup::activated(), StdCmdVarSet::activated(), StdCmdLinkMake::activated(), TDHandlerDimension::activated(), StdCmdLinkMakeRelative::activated(), StdCmdExport::activated(), StdCmdLinkSelectLinked::activated(), StdCmdLinkSelectLinkedFinal::activated(), StdCmdLinkSelectAllLinks::activated(), StdCmdToggleVisibility::activated(), StdCmdToggleTransparency::activated(), StdCmdToggleSelectability::activated(), StdCmdShowSelection::activated(), StdCmdHideSelection::activated(), StdCmdSelectVisibleObjects::activated(), StdCmdDuplicateSelection::activated(), StdCmdSelectAll::activated(), StdCmdDelete::activated(), StdCmdPlacement::activated(), StdCmdTransformManip::activated(), StdCmdAlignment::activated(), StdCmdEdit::activated(), StdCmdExpression::activated(), StdCmdTreeSelectAllInstances::activated(), StdCmdSelBack::activated(), StdCmdSelForward::activated(), StdTreeDrag::activated(), PartGui::FaceAppearances::Private::addFacesToSelection(), PartDesignGui::TaskTransformedParameters::addReferenceSelectionGate(), TechDrawGui::MDIViewPage::addSceneItemToTreeSel(), Gui::View3DInventorViewer::alignToSelection(), PartGui::CrossSections::apply(), MeshPartGui::CrossSections::apply(), Gui::ElementColors::Private::apply(), Gui::Dialog::DlgPropertyLink::attachObserver(), Gui::SelectionObserver::attachSelection(), PartGui::ViewProviderPartExt::changeFaceAppearances(), Gui::View3DInventorSelection::checkGroupOnTop(), Gui::SoFCSelectionCounter::checkRenderCache(), FemGui::ViewProviderFemAnalysis::checkSelectedChildren(), Gui::TaskMeasure::clearSelection(), Gui::Dialog::PlacementHandler::computeCenterOfMass(), SketcherGui::ConstraintView::contextMenuEvent(), Gui::DAG::Model::contextMenuEvent(), Gui::PropertyEditor::PropertyEditor::contextMenuEvent(), Gui::TreeWidget::contextMenuEvent(), createDefaultExportBasename(), Gui::MainWindow::createMimeDataFromSelection(), RobotGui::TaskRobot6Axis::createPlacementDlg(), TDHandlerDimension::deactivated(), FemGui::TaskCreateElementSet::DefineNodes(), PartDesignGui::TaskDressUpParameters::deleteRef(), SketcherGui::ViewProviderSketch::deleteSelected(), SketcherGui::ConstraintView::deleteSelectedItems(), SketcherGui::ElementView::deleteSelectedItems(), Gui::Dialog::DlgPropertyLink::detachObserver(), Gui::SelectionObserver::detachSelection(), dimensionMaker(), PartDesignGui::DlgActiveBody::DlgActiveBody(), MatGui::DlgDisplayPropertiesImp::DlgDisplayPropertiesImp(), PartGui::DlgExtrusion::DlgExtrusion(), PartGui::DlgFilletEdges::DlgFilletEdges(), MatGui::DlgInspectAppearance::DlgInspectAppearance(), MatGui::DlgInspectMaterial::DlgInspectMaterial(), MatGui::DlgMaterialImp::DlgMaterialImp(), PartGui::DlgRevolution::DlgRevolution(), PartGui::DlgScale::DlgScale(), Gui::SoFCUnifiedSelection::doAction(), Gui::SoFCSelection::doAction(), doSelect(), FemGui::ViewProviderFemAnalysis::doubleClicked(), AssemblyGui::ViewProviderAssembly::doubleClicked(), dressupGetSelected(), Gui::ElementColors::ElementColors(), Gui::OverlayManager::eventFilter(), PartDesignGui::TaskTransformedParameters::exitSelectionMode(), Gui::Application::exportTo(), PartGui::FaceAppearances::FaceAppearances(), TechDraw::CommandHelpers::faceFromSelection(), faceFromSelection(), TDHandlerDimension::finalizeCommand(), PartGui::DlgFilletEdges::findShapes(), SketcherGui::ViewProviderSketch::generateContextMenu(), getLinkImportSelections(), getListOfSelectedGeoIds(), TechDraw::getReferencesFromSelection(), AssemblyGui::ViewProviderAssembly::getSelectedJoint(), getSelectedLink(), getSelectedNodes(), AssemblyGui::ViewProviderAssembly::getSelectedObjectsWithinAssembly(), Gui::Dialog::PlacementHandler::getSelectedPoints(), Gui::Command::getSelection(), PartGui::getShapesFromSelection(), PartGui::TaskCheckGeometryResults::goCheck(), Gui::SoFCUnifiedSelection::handleEvent(), Gui::SoFCSelection::handleEvent(), Gui::TaskMeasure::hasSelection(), PartGui::hasShapesInSelection(), Gui::MainWindow::insertFromMimeData(), StdCmdLinkMakeRelative::isActive(), StdCmdLinkSelectAllLinks::isActive(), StdCmdToggleVisibility::isActive(), StdCmdToggleTransparency::isActive(), StdCmdToggleSelectability::isActive(), StdCmdShowSelection::isActive(), StdCmdHideSelection::isActive(), StdCmdCopy::isActive(), StdCmdDuplicateSelection::isActive(), StdCmdDelete::isActive(), StdCmdPlacement::isActive(), StdCmdTransformManip::isActive(), StdCmdAlignment::isActive(), StdCmdEdit::isActive(), StdCmdProperties::isActive(), StdCmdExpression::isActive(), StdCmdTreeSelectAllInstances::isActive(), StdCmdSelBack::isActive(), StdCmdSelForward::isActive(), SketcherGui::isCommandActive(), isCreateConstraintActive(), SketcherGui::isSketcherBSplineActive(), isSketcherVirtualSpaceActive(), Gui::TreeWidget::itemSearch(), Gui::DockWnd::SelectionView::leaveEvent(), Gui::Dialog::DlgPropertyLink::leaveEvent(), Gui::ElementColors::leaveEvent(), SketcherGui::TaskSketcherElements::leaveEvent(), Gui::TreeWidget::leaveEvent(), linkConvert(), Gui::SelectionFilter::match(), PartGui::Mirroring::Mirroring(), AssemblyGui::ViewProviderAssembly::mouseButtonPressed(), SketcherGui::ViewProviderSketch::mouseButtonPressed(), Gui::DAG::Model::mousePressEvent(), TechDrawGui::QGIPrimPath::mousePressEvent(), TechDrawGui::QGSPage::mousePressEvent(), TechDrawGui::QGIView::mousePressEvent(), TDHandlerDimension::mouseReleaseEvent(), TechDrawGui::PreferencesGui::multiSelection(), FemGui::TaskFemConstraint::onButtonReference(), FemGui::TaskFemConstraintOnBoundary::onButtonToggled(), PartDesignGui::TaskDlgPipeParameters::onButtonToggled(), SketcherGui::ViewProviderSketch::onDelete(), PartDesignGui::TaskFeaturePick::onDoubleClick(), PartDesignGui::TaskFeaturePick::onItemSelectionChanged(), SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsItemSelectionChanged(), SketcherGui::TaskSketcherElements::onListWidgetElementsItemPressed(), SketcherGui::TaskSketcherElements::onListWidgetElementsMouseMoveOnItem(), Gui::TreeWidget::onPreSelectTimer(), TechDrawGui::TaskComplexSection::onProfileObjectsUseSelectionClicked(), TechDrawGui::TaskComplexSection::onSectionObjectsUseSelectionClicked(), Gui::TreeWidget::onSelectDependents(), TechDrawGui::MDIViewPage::onSelectionChanged(), FemGui::TaskFemConstraintBearing::onSelectionChanged(), FemGui::TaskCreateNodeSet::onSelectionChanged(), FemGui::TaskCreateElementSet::onSelectionChanged(), PartDesignGui::TaskFeaturePick::onSelectionChanged(), FemGui::TaskFemConstraintGear::onSelectionChanged(), SurfaceGui::FillingPanel::onSelectionChanged(), MeshInfoWatcher::onSelectionChanged(), Gui::ElementColors::Private::onSelectionChanged(), TDHandlerDimension::onSelectionChanged(), PartDesignGui::TaskSketchBasedParameters::onSelectReference(), Gui::TreeWidget::onSelectTimer(), Gui::PropertyView::onTimer(), SurfaceGui::FillingEdgePanel::open(), SurfaceGui::FillingVertexPanel::open(), SurfaceGui::GeomFillSurface::open(), SurfaceGui::SectionsPanel::open(), SurfaceGui::FillingPanel::open(), MeshGui::ParametersDialog::ParametersDialog(), prepareProfileBased(), TechDrawGui::MDIViewPage::preSelectionChanged(), Gui::NavigationStyle::processEvent(), SketcherGui::ViewProviderSketch::purgeHandler(), SketcherGui::DrawSketchHandler::quit(), PartDesignGui::TaskDressUpParameters::referenceSelected(), PartGui::Mirroring::reject(), TechDrawGui::TaskDimRepair::reject(), SurfaceGui::FillingEdgePanel::reject(), SurfaceGui::GeomFillSurface::reject(), SurfaceGui::SectionsPanel::reject(), SurfaceGui::FillingPanel::reject(), DrawSketchHandlerGenConstraint::releaseButton(), DrawSketchHandlerDimension::releaseButton(), MeshGui::RemoveComponents::RemoveComponents(), TechDrawGui::QGIViewPart::removeSelectedCosmetic(), TechDrawGui::MDIViewPage::removeUnselectedTreeSelection(), Gui::Dialog::PlacementHandler::reselectObjects(), Gui::ElementColors::Private::reset(), DrawSketchHandlerGenConstraint::resetOngoingSequences(), DrawSketchHandlerDimension::resetTool(), Gui::SelectionSingleton::sAddSelection(), Gui::SelectionSingleton::sAddSelectionGate(), TechDrawGui::QGSPage::saveSvg(), TechDrawGui::MDIViewPage::sceneSelectionChanged(), Gui::SelectionSingleton::sClearSelection(), Gui::SelectionSingleton::sCountObjectsOfType(), Gui::TreeWidget::scrollItemToTop(), ReverseEngineeringGui::SegmentationManual::SegmentationManual(), Gui::PropertyEditor::LinkSelection::select(), Gui::TreeWidget::selectAll(), Gui::View3DInventorViewer::selectAll(), Gui::DAG::Model::selectionChanged(), Gui::SelectionLogDisabler::SelectionLogDisabler(), Gui::DocumentItem::selectItems(), Gui::SelectionSingleton::sEnablePickedList(), Gui::View3DInventorViewer::setDocument(), TechDrawGui::ViewProviderGeomHatch::setEdit(), TechDrawGui::ViewProviderHatch::setEdit(), TechDrawGui::ViewProviderLeader::setEdit(), FemGui::ViewProviderFemConstraintPressure::setEdit(), FemGui::ViewProviderFemConstraintRigidBody::setEdit(), FemGui::ViewProviderFemConstraintSpring::setEdit(), PartDesignGui::ViewProviderShapeBinder::setEdit(), FemGui::ViewProviderFemMeshShapeNetgen::setEdit(), FemGui::ViewProviderFemConstraintBearing::setEdit(), FemGui::ViewProviderFemConstraintGear::setEdit(), PartDesignGui::ViewProviderPrimitive::setEdit(), FemGui::ViewProviderFemConstraintPulley::setEdit(), PartDesignGui::ViewProviderHole::setEdit(), FemGui::ViewProviderFemConstraintForce::setEdit(), FemGui::ViewProviderFemConstraintFixed::setEdit(), FemGui::ViewProviderFemConstraintFluidBoundary::setEdit(), FemGui::ViewProviderFemConstraintContact::setEdit(), FemGui::ViewProviderFemConstraintPlaneRotation::setEdit(), FemGui::ViewProviderFemConstraintInitialTemperature::setEdit(), FemGui::ViewProviderFemConstraintTemperature::setEdit(), FemGui::ViewProviderFemConstraintHeatflux::setEdit(), FemGui::ViewProviderFemConstraintDisplacement::setEdit(), FemGui::ViewProviderFemConstraintTransform::setEdit(), TechDrawGui::ViewProviderWeld::setEdit(), PartDesignGui::ViewProviderSubShapeBinder::setEdit(), PartDesignGui::ViewProviderBoolean::setEdit(), TechDrawGui::ViewProviderViewSection::setEdit(), TechDrawGui::ViewProviderProjGroup::setEdit(), PartDesignGui::ViewProvider::setEdit(), TechDrawGui::ViewProviderBalloon::setEdit(), TechDrawGui::ViewProviderViewPart::setEdit(), PartDesignGui::ViewProviderDatum::setEdit(), TechDrawGui::ViewProviderDimension::setEdit(), PartGui::ViewProviderOffset::setEdit(), PartGui::ViewProviderThickness::setEdit(), Gui::ViewProviderLink::setEdit(), SketcherGui::ViewProviderSketch::setEdit(), FemGui::TaskFemConstraint::setSelection(), PartDesignGui::TaskDressUpParameters::setSelection(), PartDesignGui::TaskDressUpParameters::setSelectionMode(), PartDesignGui::TaskExtrudeParameters::setSelectionMode(), TechDrawGui::MDIViewPage::setTreeToSceneSelect(), SketcherGui::SketchSelection::setUp(), PartDesignGui::Workbench::setupContextMenu(), MeshGui::Workbench::setupContextMenu(), AssemblyGui::ViewProviderAssemblyLink::setupContextMenu(), Gui::StdWorkbench::setupContextMenu(), PartGui::DlgFilletEdges::setupFillet(), Gui::SelectionSingleton::sGetCompleteSelection(), Gui::SelectionSingleton::sGetPickedList(), Gui::SelectionSingleton::sGetPreselection(), Gui::SelectionSingleton::sGetSelection(), Gui::SelectionSingleton::sGetSelectionEx(), Gui::SelectionSingleton::sGetSelectionFromStack(), PartGui::ShapeBuilderWidget::ShapeBuilderWidget(), Gui::SelectionSingleton::sHasSelection(), Gui::SelectionSingleton::sHasSubSelection(), Gui::TaskView::TaskWatcherCommandsEmptySelection::shouldShow(), Gui::SelectionSingleton::sIsSelected(), Gui::Application::slotDeleteDocument(), TechDrawGui::TaskDimRepair::slotUseSelection(), Gui::SelectionSingleton::sPushSelStack(), Gui::SelectionSingleton::sRemoveSelection(), Gui::SelectionSingleton::sRemoveSelectionGate(), Gui::SelectionSingleton::sRemPreselection(), Gui::SelectionSingleton::sSetPreselection(), Gui::SelectionSingleton::sSetSelectionStyle(), Gui::SelectionSingleton::sSetVisible(), SketcherGui::SuggestAutoMapMode(), Gui::SelectionSingleton::sUpdateSelection(), Gui::TaskView::TaskAppearance::TaskAppearance(), PartDesignGui::TaskDatumParameters::TaskDatumParameters(), MeshGui::TaskDecimating::TaskDecimating(), Gui::TaskMeasure::TaskMeasure(), DrawingGui::TaskOrthoViews::TaskOrthoViews(), Gui::TaskView::TaskSelectLinkProperty::TaskSelectLinkProperty(), Gui::TaskView::TaskSketcherCreateCommands::TaskSketcherCreateCommands(), MeshGui::TaskSmoothing::TaskSmoothing(), Gui::TaskView::TaskView::TaskView(), FemGui::ViewProviderFemConstraint::unsetEdit(), PartDesignGui::ViewProvider::unsetEdit(), SketcherGui::ViewProviderSketch::unsetEdit(), Gui::TaskMeasure::update(), Gui::DocumentItem::updateItemSelection(), Gui::View3DInventorViewer::viewSelection(), MatGui::DlgDisplayPropertiesImp::~DlgDisplayPropertiesImp(), PartGui::DlgExtrusion::~DlgExtrusion(), PartGui::DlgFilletEdges::~DlgFilletEdges(), MatGui::DlgInspectAppearance::~DlgInspectAppearance(), MatGui::DlgInspectMaterial::~DlgInspectMaterial(), MatGui::DlgMaterialImp::~DlgMaterialImp(), PartGui::DlgProjectionOnSurface::~DlgProjectionOnSurface(), PartGui::DlgProjectOnSurface::~DlgProjectOnSurface(), PartGui::DlgRevolution::~DlgRevolution(), SketcherGui::DrawSketchHandlerFillet::~DrawSketchHandlerFillet(), DrawSketchHandlerGenConstraint::~DrawSketchHandlerGenConstraint(), Gui::ElementColors::~ElementColors(), PartGui::FaceAppearances::~FaceAppearances(), SurfaceGui::FillingEdgePanel::~FillingEdgePanel(), SurfaceGui::FillingVertexPanel::~FillingVertexPanel(), Gui::SelectionLogDisabler::~SelectionLogDisabler(), PartGui::ShapeBuilderWidget::~ShapeBuilderWidget(), PartGui::SweepWidget::~SweepWidget(), Gui::TaskView::TaskAppearance::~TaskAppearance(), PartDesignGui::TaskChamferParameters::~TaskChamferParameters(), PartGui::TaskCheckGeometryResults::~TaskCheckGeometryResults(), FemGui::TaskCreateNodeSet::~TaskCreateNodeSet(), PartDesignGui::TaskDatumParameters::~TaskDatumParameters(), PartDesignGui::TaskDraftParameters::~TaskDraftParameters(), PartDesignGui::TaskDressUpParameters::~TaskDressUpParameters(), PartDesignGui::TaskFilletParameters::~TaskFilletParameters(), Gui::TaskMeasure::~TaskMeasure(), Gui::TaskView::TaskSelectLinkProperty::~TaskSelectLinkProperty(), PartDesignGui::TaskSketchBasedParameters::~TaskSketchBasedParameters(), Gui::TaskView::TaskSketcherCreateCommands::~TaskSketcherCreateCommands(), PartDesignGui::TaskThicknessParameters::~TaskThicknessParameters(), PartDesignGui::TaskTransformedParameters::~TaskTransformedParameters(), Gui::TaskView::TaskView::~TaskView(), and PartGui::ThicknessWidget::~ThicknessWidget().
stripPromptFrom()
QString Gui::stripPromptFrom (const QString & lineStr) inline
Definition at line 64 of file PythonConsole.cpp.
References promptLength().
Referenced by Gui::PythonConsole::createMimeDataFromSelection(), and Gui::PythonConsole::keyPressEvent().
TranslatedNotification()
template<typename TNotifier , typename TCaption , typename TMessage > void Gui::TranslatedNotification (TNotifier && notifier, TCaption && caption, TMessage && message) inline
Convenience function to send already translated user notifications. No attempt will be made by the NotificationArea to translate them.
Definition at line 336 of file Notifications.h.
References Base::Notification, Notify(), Base::Translated, and Base::User.
Referenced by CmdSketcherConstrainDistance::activated().
TranslatedUserError()
template<typename TNotifier , typename TCaption , typename TMessage > void Gui::TranslatedUserError (TNotifier && notifier, TCaption && caption, TMessage && message) inline
Definition at line 325 of file Notifications.h.
References Base::Error, Notify(), Base::Translated, and Base::User.
Referenced by addConstraintSafely(), and DrawSketchHandlerBSplineInsertKnot::releaseButton().
TranslatedUserWarning()
template<typename TNotifier , typename TCaption , typename TMessage > void Gui::TranslatedUserWarning (TNotifier && notifier, TCaption && caption, TMessage && message) inline
Definition at line 294 of file Notifications.h.
References Notify(), Base::Translated, Base::User, and Base::Warning.
Referenced by SketcherCopy::activate(), CmdSketcherConstrainLock::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadiam::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), CmdSketcherConstrainCoincidentUnified::activatedCoincident(), CmdSketcherConstrainCoincidentUnified::activatedPointOnObject(), CmdSketcherConstrainBlock::applyConstraint(), CmdSketcherConstrainDistance::applyConstraint(), CmdSketcherConstrainDistanceX::applyConstraint(), CmdSketcherConstrainDistanceY::applyConstraint(), CmdSketcherConstrainParallel::applyConstraint(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainRadiam::applyConstraint(), CmdSketcherConstrainAngle::applyConstraint(), CmdSketcherConstrainEqual::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), CmdSketcherConstrainCoincidentUnified::applyConstraintCoincident(), CmdSketcherConstrainCoincidentUnified::applyConstraintPointOnObject(), canHorVerBlock(), DrawSketchHandlerDimension::createEqualityConstrain(), DrawSketchHandlerDimension::createSymmetryConstrain(), SketcherGui::EditDatumDialog::exec(), horVerActivated(), horVerApplyConstraint(), SketcherGui::makeAngleBetweenTwoLines(), CmdSketcherConstrainCoincidentUnified::onActivated(), showNoConstraintBetweenExternal(), showNoConstraintBetweenFixedGeometry(), and SketcherGui::ConstraintView::swapNamedOfSelectedItems().
validateInput()
bool Gui::validateInput (QWidget * parent, const QString & input)
Definition at line 466 of file DlgParameterImp.cpp.
References SCL.SimpleDataTypes::c, SplineSurface::i, Init::parent, and Path.Log::warning().
Referenced by Gui::Dialog::ParameterValue::onCreateBoolItem(), Gui::Dialog::ParameterValue::onCreateFloatItem(), Gui::Dialog::ParameterValue::onCreateIntItem(), Gui::Dialog::ParameterGroup::onCreateSubgroup(), Gui::Dialog::ParameterValue::onCreateTextItem(), Gui::Dialog::ParameterValue::onCreateUIntItem(), Gui::Dialog::ParameterGroupItem::setData(), Gui::Dialog::ParameterValueItem::setData(), and Gui::QuantitySpinBoxPrivate::validate().
WidgetFactory()
WidgetFactoryInst& Gui::WidgetFactory () inline
Definition at line 68 of file WidgetFactory.h.
References Gui::WidgetFactoryInst::instance().
Referenced by Gui::UiLoaderPy::availableWidgets(), Gui::Dialog::DlgPreferencesImp::createPreferencePage(), and Gui::Dialog::DlgCustomizeImp::DlgCustomizeImp().
WorkbenchFactory()
GuiExport WorkbenchFactoryInst& Gui::WorkbenchFactory () inline
Definition at line 83 of file WorkbenchFactory.h.
Variable Documentation
FreeCADGui_methods
struct PyMethodDef Gui::FreeCADGui_methods[]
Initial value:
= {
    {"subgraphFromObject",
     FreeCADGui_subgraphFromObject,
     METH_VARARGS,
     "subgraphFromObject(object) -> Node\n\n"
     "Return the Inventor subgraph to an object"},
    {"exportSubgraph",
     FreeCADGui_exportSubgraph,
     METH_VARARGS,
     "exportSubgraph(Node, File or Buffer, [Format='VRML']) -> None\n\n"
     "Exports the sub-graph in the requested format"
     "The format string can be VRML or IV"},
    {"getSoDBVersion",
     FreeCADGui_getSoDBVersion,
     METH_VARARGS,
     "getSoDBVersion() -> String\n\n"
     "Return a text string containing the name\n"
     "of the Coin library and version information"},
    {nullptr, nullptr, 0, nullptr}
}
Definition at line 343 of file Gui/Application.cpp.
Referenced by Gui::Application::Application().
ViewProviderExtensionPythonT< ViewProviderExtension >
template class GuiExport Gui::ViewProviderExtensionPythonT< ViewProviderExtension >
Definition at line 77 of file ViewProviderExtension.cpp.
ViewProviderExtensionPythonT< ViewProviderGeoFeatureGroupExtension >
template class GuiExport Gui::ViewProviderExtensionPythonT< ViewProviderGeoFeatureGroupExtension >
Definition at line 165 of file ViewProviderGeoFeatureGroupExtension.cpp.
ViewProviderExtensionPythonT< ViewProviderGroupExtension >
template class GuiExport Gui::ViewProviderExtensionPythonT< ViewProviderGroupExtension >
Definition at line 200 of file ViewProviderGroupExtension.cpp.
ViewProviderExtensionPythonT< ViewProviderOriginGroupExtension >
template class GuiExport Gui::ViewProviderExtensionPythonT< ViewProviderOriginGroupExtension >
Definition at line 95 of file ViewProviderOriginGroupExtension.cpp.
ViewProviderExtensionPythonT< ViewProviderSuppressibleExtension >
template class GuiExport Gui::ViewProviderExtensionPythonT< ViewProviderSuppressibleExtension >
Definition at line 109 of file ViewProviderSuppressibleExtension.cpp.
ViewProviderFeaturePythonT< ViewProviderDocumentObject >
template class GuiExport Gui::ViewProviderFeaturePythonT< ViewProviderDocumentObject >
Definition at line 1264 of file ViewProviderFeaturePython.cpp.
ViewProviderFeaturePythonT< ViewProviderDocumentObjectGroup >
template class GuiExport Gui::ViewProviderFeaturePythonT< ViewProviderDocumentObjectGroup >
Definition at line 94 of file ViewProviderDocumentObjectGroup.cpp.
ViewProviderFeaturePythonT< ViewProviderFemAnalysis >
template class FemGuiExport Gui::ViewProviderFeaturePythonT< ViewProviderFemAnalysis >
Definition at line 370 of file ViewProviderAnalysis.cpp.
ViewProviderFeaturePythonT< ViewProviderFemConstraint >
template class FemGuiExport Gui::ViewProviderFeaturePythonT< ViewProviderFemConstraint >
Definition at line 308 of file ViewProviderFemConstraint.cpp.
ViewProviderFeaturePythonT< ViewProviderFemMesh >
template class FemGuiExport Gui::ViewProviderFeaturePythonT< ViewProviderFemMesh >
Definition at line 3172 of file ViewProviderFemMesh.cpp.
ViewProviderFeaturePythonT< ViewProviderGeoFeatureGroup >
template class GuiExport Gui::ViewProviderFeaturePythonT< ViewProviderGeoFeatureGroup >
Definition at line 50 of file ViewProviderGeoFeatureGroup.cpp.
ViewProviderFeaturePythonT< ViewProviderGeometryObject >
template class GuiExport Gui::ViewProviderFeaturePythonT< ViewProviderGeometryObject >
Definition at line 1272 of file ViewProviderFeaturePython.cpp.
ViewProviderFeaturePythonT< ViewProviderLink >
template class GuiExport Gui::ViewProviderFeaturePythonT< ViewProviderLink >
Definition at line 3353 of file ViewProviderLink.cpp.
ViewProviderFeaturePythonT< ViewProviderMaterialObject >
template class GuiExport Gui::ViewProviderFeaturePythonT< ViewProviderMaterialObject >
Definition at line 76 of file ViewProviderMaterialObject.cpp.
ViewProviderFeaturePythonT< ViewProviderPart >
template class GuiExport Gui::ViewProviderFeaturePythonT< ViewProviderPart >
Definition at line 147 of file ViewProviderPart.cpp.
ViewProviderFeaturePythonT< ViewProviderPlacement >
template class GuiExport Gui::ViewProviderFeaturePythonT< ViewProviderPlacement >
Definition at line 141 of file ViewProviderPlacement.cpp.
ViewProviderFeaturePythonT< ViewProviderResult >
template class FemGuiExport Gui::ViewProviderFeaturePythonT< ViewProviderResult >
Definition at line 49 of file ViewProviderResult.cpp.
ViewProviderFeaturePythonT< ViewProviderSheet >
template class SpreadsheetGuiExport Gui::ViewProviderFeaturePythonT< ViewProviderSheet >
Definition at line 209 of file Spreadsheet/Gui/ViewProviderSpreadsheet.cpp.
ViewProviderFeaturePythonT< ViewProviderSolver >
template class FemGuiExport Gui::ViewProviderFeaturePythonT< ViewProviderSolver >
Definition at line 80 of file ViewProviderSolver.cpp.
XPM_pixel_mask
const unsigned char Gui::XPM_pixel_mask[21 *27 *4+1] static
Definition at line 20 of file CornerCrossLetters.h.
YPM_pixel_mask
const unsigned char Gui::YPM_pixel_mask[21 *27 *4+1] static
Definition at line 93 of file CornerCrossLetters.h.
ZPM_pixel_mask
const unsigned char Gui::ZPM_pixel_mask[21 *27 *4+1] static
Definition at line 165 of file CornerCrossLetters.h.