FreeCAD: OpenSCADUtils Namespace Reference
OpenSCADUtils Namespace Reference
Classes
class OpenSCADError
Functions
def getopenscadexe (osfilename=None)
def searchforopenscadexe ()
def getopenscadversion (osfilename=None)
def newtempfilename ()
def callopenscad (inputfilename, outputfilename=None, outputext='csg', keepname=False)
def call_openscad_with_pipes (input_filename, output_filename, output_extension, keep_name)
def callopenscadstring (scadstr, outputext='csg')
def reverseimporttypes ()
def fcsubmatrix (m)
def multiplymat (l, r)
def isorthogonal (submatrix, precision=4)
def detsubmatrix (s)
def isspecialorthogonalpython (submat, precision=4)
def isrotoinversionpython (submat, precision=4)
def isspecialorthogonal (mat, precision=4)
def decomposerotoinversion (m, precision=4)
def mirror2mat (nv, bv)
def vec2householder (nv)
def mirrormesh (msh, vec)
def scalemesh (msh, vec)
def resizemesh (msh, vec)
def angneg (d)
def shorthexfloat (f)
def comparerotations (r1, r2)
def findbestmatchingrotation (r1)
def roundrotation (rot, maxangulardistance=1e-5)
def callopenscadmeshstring (scadstr)
def meshopinline (opname, iterable1)
def meshoptempfile (opname, iterable1)
def meshoponobjs (opname, inobjs)
def process2D_ObjectsViaOpenSCADShape (ObjList, Operation, doc)
def process2D_ObjectsViaOpenSCAD (ObjList, Operation, doc=None)
def process3D_ObjectsViaOpenSCADShape (ObjList, Operation, maxmeshpoints=None)
def process3D_ObjectsViaOpenSCAD (doc, ObjList, Operation)
def process_ObjectsViaOpenSCADShape (doc, children, name, maxmeshpoints=None)
def process_ObjectsViaOpenSCAD (doc, children, name)
def removesubtree (objs)
def applyPlacement (shape)
Variables
translate = FreeCAD.Qt.translate
BaseError = FreeCAD.Base.FreeCADError
def tempfilenamegen = newtempfilename()
Function Documentation
angneg()
def OpenSCADUtils.angneg (d)
Definition at line 375 of file OpenSCADUtils.py.
applyPlacement()
def OpenSCADUtils.applyPlacement (shape)
Definition at line 689 of file OpenSCADUtils.py.
call_openscad_with_pipes()
def OpenSCADUtils.call_openscad_with_pipes (input_filename, output_filename, output_extension, keep_name)
Call OpenSCAD by sending input data to stdin, and read the output from stdout.
    Returns the tempfile the output is stored in on success, or None on failure.
    NOTE: This feature was added to OpenSCAD in 2021.01
Definition at line 189 of file OpenSCADUtils.py.
References AssemblyImport.open().
Referenced by callopenscad().
callopenscad()
def OpenSCADUtils.callopenscad (inputfilename, outputfilename = None, outputext = 'csg', keepname = False)
call the open scad binary
returns the filename of the result (or None),
please delete the file afterwards
Definition at line 141 of file OpenSCADUtils.py.
References call_openscad_with_pipes().
Referenced by callopenscadstring(), importCSG.insert(), importCSG.open(), and prototype.readfile().
callopenscadmeshstring()
def OpenSCADUtils.callopenscadmeshstring (scadstr)
Call OpenSCAD and return the result as a Mesh
Definition at line 491 of file OpenSCADUtils.py.
References callopenscadstring().
Referenced by meshopinline(), meshoptempfile(), mirrormesh(), resizemesh(), and scalemesh().
callopenscadstring()
def OpenSCADUtils.callopenscadstring (scadstr, outputext = 'csg')
create a tempfile and call the open scad binary
returns the filename of the result (or None),
please delete the file afterwards
Definition at line 229 of file OpenSCADUtils.py.
References callopenscad().
Referenced by OpenSCADCommands.AddSCADTask.addelement(), callopenscadmeshstring(), prototype.openscadmesh(), process2D_ObjectsViaOpenSCADShape(), and importCSG.processTextCmd().
comparerotations()
def OpenSCADUtils.comparerotations (r1, r2)
compares two rotations
a value of zero means that they are identical
Definition at line 384 of file OpenSCADUtils.py.
Referenced by findbestmatchingrotation(), and roundrotation().
decomposerotoinversion()
def OpenSCADUtils.decomposerotoinversion (m, precision = 4)
Definition at line 309 of file OpenSCADUtils.py.
References fcsubmatrix().
Referenced by importCSG.p_multmatrix_action().
detsubmatrix()
def OpenSCADUtils.detsubmatrix (s)
get the determinant of a 3x3 Matrix given as list of row vectors
Definition at line 291 of file OpenSCADUtils.py.
Referenced by isrotoinversionpython(), and isspecialorthogonalpython().
fcsubmatrix()
def OpenSCADUtils.fcsubmatrix (m)
Extracts the 3x3 Submatrix from a freecad Matrix Object
as a list of row vectors
Definition at line 265 of file OpenSCADUtils.py.
Referenced by prototype.Node.addtofreecad(), decomposerotoinversion(), and importCSG.p_multmatrix_action().
findbestmatchingrotation()
def OpenSCADUtils.findbestmatchingrotation (r1)
Definition at line 391 of file OpenSCADUtils.py.
References comparerotations().
Referenced by roundrotation().
getopenscadexe()
def OpenSCADUtils.getopenscadexe (osfilename = None)
Definition at line 62 of file OpenSCADUtils.py.
References searchforopenscadexe().
getopenscadversion()
def OpenSCADUtils.getopenscadversion (osfilename = None)
Definition at line 117 of file OpenSCADUtils.py.
isorthogonal()
def OpenSCADUtils.isorthogonal (submatrix, precision = 4)
checking if 3x3 Matrix is orthogonal (M*Transp(M)==I)
Definition at line 284 of file OpenSCADUtils.py.
References multiplymat().
Referenced by isrotoinversionpython(), and isspecialorthogonalpython().
isrotoinversionpython()
def OpenSCADUtils.isrotoinversionpython (submat, precision = 4)
Definition at line 300 of file OpenSCADUtils.py.
References detsubmatrix(), and isorthogonal().
Referenced by importCSG.p_multmatrix_action().
isspecialorthogonal()
def OpenSCADUtils.isspecialorthogonal (mat, precision = 4)
Definition at line 303 of file OpenSCADUtils.py.
References KDL.abs(), and draftgeoutils.linear_algebra.determinant().
Referenced by expandplacements.expandplacementsmatrix().
isspecialorthogonalpython()
def OpenSCADUtils.isspecialorthogonalpython (submat, precision = 4)
Definition at line 297 of file OpenSCADUtils.py.
References detsubmatrix(), and isorthogonal().
Referenced by prototype.Node.addtofreecad(), and importCSG.p_multmatrix_action().
meshopinline()
def OpenSCADUtils.meshopinline (opname, iterable1)
uses OpenSCAD to combine meshes
takes the name of the CGAL operation and an iterable (tuple,list) of
FreeCAD Mesh objects
includes all the mesh data in the SCAD file
Definition at line 503 of file OpenSCADUtils.py.
References callopenscadmeshstring(), and exportCSG.mesh2polyhedron().
meshoponobjs()
def OpenSCADUtils.meshoponobjs (opname, inobjs)
takes a string (operation name) and a list of Feature Objects
returns a mesh and a list of objects that were used
Part Objects will be meshed
Definition at line 538 of file OpenSCADUtils.py.
References meshoptempfile().
Referenced by OpenSCADCommands.OpenSCADMeshBooleanTask.doboolean().
meshoptempfile()
def OpenSCADUtils.meshoptempfile (opname, iterable1)
uses OpenSCAD to combine meshes
takes the name of the CGAL operation and an iterable (tuple,list) of
FreeCAD Mesh objects
uses stl files to supply the mesh data
Definition at line 513 of file OpenSCADUtils.py.
References callopenscadmeshstring().
Referenced by meshoponobjs(), and process3D_ObjectsViaOpenSCADShape().
mirror2mat()
def OpenSCADUtils.mirror2mat (nv, bv)
calculate the transformation matrix of a mirror feature
Definition at line 326 of file OpenSCADUtils.py.
References vec2householder().
Referenced by expandplacements.expandplacements().
mirrormesh()
def OpenSCADUtils.mirrormesh (msh, vec)
mirrormesh(mesh,vector) where mesh is a mesh object and vector is a Base.Vector
Definition at line 345 of file OpenSCADUtils.py.
References callopenscadmeshstring(), exportCSG.mesh2polyhedron(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by OpenSCADCommands.MirrorMeshFeature.Activated().
multiplymat()
def OpenSCADUtils.multiplymat (l, r)
multiply matrices given as lists of row vectors
Definition at line 271 of file OpenSCADUtils.py.
Referenced by isorthogonal().
newtempfilename()
def OpenSCADUtils.newtempfilename ()
Definition at line 131 of file OpenSCADUtils.py.
process2D_ObjectsViaOpenSCAD()
def OpenSCADUtils.process2D_ObjectsViaOpenSCAD (ObjList, Operation, doc = None)
Definition at line 600 of file OpenSCADUtils.py.
References process2D_ObjectsViaOpenSCADShape().
Referenced by process_ObjectsViaOpenSCAD().
process2D_ObjectsViaOpenSCADShape()
def OpenSCADUtils.process2D_ObjectsViaOpenSCADShape (ObjList, Operation, doc)
Definition at line 570 of file OpenSCADUtils.py.
References callopenscadstring(), importDXF.export(), OpenSCAD2Dgeom.importDXFface(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by process2D_ObjectsViaOpenSCAD(), and process_ObjectsViaOpenSCADShape().
process3D_ObjectsViaOpenSCAD()
def OpenSCADUtils.process3D_ObjectsViaOpenSCAD (doc, ObjList, Operation)
Definition at line 634 of file OpenSCADUtils.py.
References process3D_ObjectsViaOpenSCADShape().
Referenced by process_ObjectsViaOpenSCAD().
process3D_ObjectsViaOpenSCADShape()
def OpenSCADUtils.process3D_ObjectsViaOpenSCADShape (ObjList, Operation, maxmeshpoints = None)
Definition at line 612 of file OpenSCADUtils.py.
References KDL.max(), and meshoptempfile().
Referenced by process3D_ObjectsViaOpenSCAD(), and process_ObjectsViaOpenSCADShape().
process_ObjectsViaOpenSCAD()
def OpenSCADUtils.process_ObjectsViaOpenSCAD (doc, children, name)
Definition at line 656 of file OpenSCADUtils.py.
References process2D_ObjectsViaOpenSCAD(), and process3D_ObjectsViaOpenSCAD().
process_ObjectsViaOpenSCADShape()
def OpenSCADUtils.process_ObjectsViaOpenSCADShape (doc, children, name, maxmeshpoints = None)
Definition at line 645 of file OpenSCADUtils.py.
References process2D_ObjectsViaOpenSCADShape(), and process3D_ObjectsViaOpenSCADShape().
removesubtree()
def OpenSCADUtils.removesubtree (objs)
Definition at line 668 of file OpenSCADUtils.py.
Referenced by OpenSCADCommands.RemoveSubtree.Activated().
resizemesh()
def OpenSCADUtils.resizemesh (msh, vec)
resizemesh(mesh,vector) where mesh is a mesh object and vector is a Base.Vector
Definition at line 365 of file OpenSCADUtils.py.
References callopenscadmeshstring(), exportCSG.mesh2polyhedron(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by OpenSCADCommands.ResizeMeshFeature.Activated().
reverseimporttypes()
def OpenSCADUtils.reverseimporttypes ()
allows one to search for supported filetypes by module
Definition at line 244 of file OpenSCADUtils.py.
References src.Mod.Test.testPathArray.items, and Path.Post.scripts.grbl_post.type.
Referenced by prototype.Node.addtofreecad(), and importCSG.process_import_file().
roundrotation()
def OpenSCADUtils.roundrotation (rot, maxangulardistance = 1e-5)
guess the rotation axis and angle for a rotation
recreated from rounded floating point values
(from a quaterion or transformation matrix)
Definition at line 461 of file OpenSCADUtils.py.
References comparerotations(), and findbestmatchingrotation().
Referenced by importCSG.p_multmatrix_action().
scalemesh()
def OpenSCADUtils.scalemesh (msh, vec)
scalemesh(mesh,vector) where mesh is a mesh object and vector is a Base.Vector
Definition at line 355 of file OpenSCADUtils.py.
References callopenscadmeshstring(), exportCSG.mesh2polyhedron(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by OpenSCADCommands.ScaleMeshFeature.Activated().
searchforopenscadexe()
def OpenSCADUtils.searchforopenscadexe ()
Try to use Python's built-in executable-finder. If that fails, fall back to the
old code.
Definition at line 72 of file OpenSCADUtils.py.
Referenced by getopenscadexe(), and InitGui.OpenSCADWorkbench.Initialize().
shorthexfloat()
def OpenSCADUtils.shorthexfloat (f)
Definition at line 379 of file OpenSCADUtils.py.
Referenced by exportDRAWEXE.quaternionToString().
vec2householder()
def OpenSCADUtils.vec2householder (nv)
calculated the householder matrix for a given normal vector
Definition at line 335 of file OpenSCADUtils.py.
Referenced by mirror2mat().
Variable Documentation
BaseError
OpenSCADUtils.BaseError = FreeCAD.Base.FreeCADError
Definition at line 48 of file OpenSCADUtils.py.
tempfilenamegen
def OpenSCADUtils.tempfilenamegen = newtempfilename()
Definition at line 138 of file OpenSCADUtils.py.
translate
OpenSCADUtils.translate = FreeCAD.Qt.translate
Definition at line 45 of file OpenSCADUtils.py.