FreeCAD: Gui::Dialog::DlgPreferencesImp Class Reference
Gui::Dialog::DlgPreferencesImp Class Reference
#include <DlgPreferencesImp.h>
Public Member Functions
DlgPreferencesImp (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgPreferencesImp () override
void accept () override
void reject () override
void reload ()
void activateGroupPage (const QString &group, int index)
void activateGroupPageByPageName (const QString &group, const QString &pageName)
void activeGroupPage (QString &group, int &index) const
Static Public Member Functions
static void addPage (const std::string &className, const std::string &group)
static void removePage (const std::string &className, const std::string &group)
static void setGroupData (const std::string &group, const std::string &icon, const QString &tip)
static void getGroupData (const std::string &group, std::string &icon, QString &tip)
static void reloadSettings ()
static PreferencePage * createPreferencePage (const std::string &pageName, const std::string &groupName)
Protected Slots
void onButtonBoxClicked (QAbstractButton *)
void onPageSelected (const QModelIndex &index)
void onStackWidgetChange (int index)
void onGroupExpanded (const QModelIndex &index)
void onGroupCollapsed (const QModelIndex &index)
Protected Member Functions
void changeEvent (QEvent *e) override
void showEvent (QShowEvent *) override
Detailed Description
This class implements a dialog containing several preference pages.
To append your own page you just have to take note of these points:
Each preference page can be created by the Qt Designer selecting the "Widget" item in the project dialog.
To save or load the widgets' settings automatically (e.g. combo boxes, line edits, check boxes, ...) you can make use of the classes inherited from PrefWidget such as: PrefSpinBox, PrefLineEdit, PrefComboBox, PrefListBox, PrefCheckBox, PrefRadioButton and PrefSlider. If you have compiled and installed the library under src/Tools/plugins/widgets to QTDIR/plugins/designer you should see the new category "Preferences". Moreover you have to make sure to have specified the "prefEntry" and "prefPath" properties for each preference widget you have used inside your form in Qt Designer.
For each widget inside your page - you want to save or load - you have to call <objectname>->onSave() or <objectname>->onRestore(). The best way to this is either to define the protected slots saveSettings() and loadSettings() in your form and overwrite them in a subclass or define these slots in this subclass directly.
See the example below for more details:
 // This class was created by Qt's uic tool
 class MyPrefPage : public QWidget
 {
 public:
   MyPrefPage( QWidget* parent = 0, const char* name = 0, WFlags fl = 0 )
   {
     myLineEdit->setProperty( "prefEntry", "lineedit" );
     myLineEdit->setProperty( "prefPath", "GroupName" );
     myCheckBox->setProperty( "prefEntry", "checkbox" );
     myCheckBox->setProperty( "prefPath", "GroupName" );
     ...
   }
   PrefLineEdit* myLineEdit;
   PrefCheckBox* myCheckBox;
};
In the derived class you just have to implement the methods saveSettings() and loadSettings() in the following way:.
 class MyPrefPageImp : public MyPrefPage
 {
 public:
   MyPrefPageImp( QWidget* parent = 0, const char* name = 0, WFlags fl = 0 )
   {
   }
 protected Q_SLOTS:
   void saveSettings()
   {
     myLineEdit->onSave();
     myCheckBox->onSave();
   }
   void loadSettings();
   {
     myLineEdit->onRestore();
     myCheckBox->onRestore();
   }
};
Now you have to make the widget factory to know your class by adding the line new PrefPageProducer<MyPrefPageImp> (QT_TR_NOOP("My category"));
See also
PrefWidget
Author
Werner Mayer, Jürgen Riegel
Definition at line 129 of file DlgPreferencesImp.h.
Constructor & Destructor Documentation
DlgPreferencesImp()
DlgPreferencesImp::DlgPreferencesImp (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Constructs a DlgPreferencesImp which is a child of 'parent', with widget flags set to 'fl'
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
Definition at line 127 of file DlgPreferencesImp.cpp.
~DlgPreferencesImp()
DlgPreferencesImp::~DlgPreferencesImp () override
Destroys the object and frees any allocated resources.
Definition at line 151 of file DlgPreferencesImp.cpp.
Member Function Documentation
accept()
void DlgPreferencesImp::accept () override
Definition at line 553 of file DlgPreferencesImp.cpp.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
activateGroupPage()
void DlgPreferencesImp::activateGroupPage (const QString & group, int index)
Activates the page at position index of the group with name group.
Definition at line 488 of file DlgPreferencesImp.cpp.
References toolbit-attributes::group, and SplineSurface::i.
Referenced by StdCmdDlgPreferences::activated(), Gui::WorkbenchTabWidget::buildPrefMenu(), and Gui::ApplicationPy::sShowPreferences().
activateGroupPageByPageName()
void DlgPreferencesImp::activateGroupPageByPageName (const QString & group, const QString & pageName)
Activates the page with name pageName of the group with name group.
Definition at line 511 of file DlgPreferencesImp.cpp.
References toolbit-attributes::group, and SplineSurface::i.
Referenced by Gui::ApplicationPy::sShowPreferencesByName().
activeGroupPage()
void DlgPreferencesImp::activeGroupPage (QString & group, int & index) const
Returns the group name group and position index of the active page.
Definition at line 543 of file DlgPreferencesImp.cpp.
References toolbit-attributes::group.
Referenced by StdCmdDlgPreferences::activated().
addPage()
void DlgPreferencesImp::addPage (const std::string & className, const std::string & group) static
Adds a preference page with its class name className and the group group it belongs to. To create this page it must be registered in the WidgetFactory.
See also
WidgetFactory
PrefPageProducer
Definition at line 402 of file DlgPreferencesImp.cpp.
References toolbit-attributes::group.
Referenced by Gui::PrefPageProducer< CLASS >::PrefPageProducer(), Gui::PrefPagePyProducer::PrefPagePyProducer(), and Gui::PrefPageUiProducer::PrefPageUiProducer().
changeEvent()
void DlgPreferencesImp::changeEvent (QEvent * e) override protected
Definition at line 916 of file DlgPreferencesImp.cpp.
References SCL.SimpleDataTypes::e, and SplineSurface::i.
createPreferencePage()
PreferencePage * DlgPreferencesImp::createPreferencePage (const std::string & pageName, const std::string & groupName) static
Definition at line 282 of file DlgPreferencesImp.cpp.
References Gui::WidgetFactoryInst::createPreferencePage(), and Gui::WidgetFactory().
getGroupData()
void DlgPreferencesImp::getGroupData (const std::string & group, std::string & icon, QString & tip) static
Gets the icon name or tool tip for a given group. If no custom name or tool tip is given they are determined from the group name.
Definition at line 467 of file DlgPreferencesImp.cpp.
References toolbit-attributes::group.
onButtonBoxClicked
void DlgPreferencesImp::onButtonBoxClicked (QAbstractButton * btn) protected slot
Definition at line 571 of file DlgPreferencesImp.cpp.
onGroupCollapsed
void DlgPreferencesImp::onGroupCollapsed (const QModelIndex & index) protected slot
Definition at line 861 of file DlgPreferencesImp.cpp.
References findRootIndex(), and Gui::Dialog::PreferencesPageItem::setExpanded().
onGroupExpanded
void DlgPreferencesImp::onGroupExpanded (const QModelIndex & index) protected slot
Definition at line 852 of file DlgPreferencesImp.cpp.
References findRootIndex(), and Gui::Dialog::PreferencesPageItem::setExpanded().
onPageSelected
void DlgPreferencesImp::onPageSelected (const QModelIndex & index) protected slot
Definition at line 824 of file DlgPreferencesImp.cpp.
References findRootIndex(), and Gui::Dialog::PreferencesPageItem::getWidget().
onStackWidgetChange
void DlgPreferencesImp::onStackWidgetChange (int index) protected slot
Definition at line 870 of file DlgPreferencesImp.cpp.
References SplineSurface::i, and isParentOf().
reject()
void DlgPreferencesImp::reject () override
Definition at line 565 of file DlgPreferencesImp.cpp.
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
reload()
void DlgPreferencesImp::reload ()
Definition at line 944 of file DlgPreferencesImp.cpp.
References SplineSurface::i.
reloadSettings()
static void Gui::Dialog::DlgPreferencesImp::reloadSettings () static
removePage()
void DlgPreferencesImp::removePage (const std::string & className, const std::string & group) static
Definition at line 429 of file DlgPreferencesImp.cpp.
References toolbit-attributes::group, and buildPsets::p.
setGroupData()
void DlgPreferencesImp::setGroupData (const std::string & name, const std::string & icon, const QString & tip) static
Sets a custom icon name or tool tip for a given group.
Definition at line 455 of file DlgPreferencesImp.cpp.
References toolbit-attributes::group.
Referenced by PyMOD_INIT_FUNC().
showEvent()
void DlgPreferencesImp::showEvent (QShowEvent * ev) override protected
Definition at line 791 of file DlgPreferencesImp.cpp.
References Path.Post.scripts.opensbp_post::move(), and MovieTool::x.
The documentation for this class was generated from the following files:
DlgPreferencesImp.h
DlgPreferencesImp.cpp