FreeCAD: Gui::Dialog::DlgRunExternal Class Reference
Gui::Dialog::DlgRunExternal Class Reference
#include <DlgRunExternal.h>
Public Member Functions
DlgRunExternal (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgRunExternal () override
void addArgument (const QString &)
int runProcess ()
Protected Slots
void reject () override
void accept () override
virtual void abort ()
virtual void advanced ()
void finished (int exitCode, QProcess::ExitStatus exitStatus)
void onChooseProgramClicked ()
Detailed Description
The DlgRunExternal class implements a dialog to start and control external programs to edit FreeCAD controlled content.
Author
Jürgen Riegel
Definition at line 80 of file DlgRunExternal.h.
Constructor & Destructor Documentation
DlgRunExternal()
DlgRunExternal::DlgRunExternal (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Constructs a DlgRunExternal which is a child of 'parent', with the name 'name' and widget flags set to 'f'
The dialog will by default be modeless, unless you set 'modal' to true to construct a modal dialog.
Definition at line 44 of file DlgRunExternal.cpp.
References abort(), accept(), advanced(), draftgeoutils.intersections::connect(), finished(), onChooseProgramClicked(), and reject().
~DlgRunExternal()
DlgRunExternal::~DlgRunExternal () override default
Destroys the object and frees any allocated resources
Member Function Documentation
abort
void DlgRunExternal::abort () protected virtual slot
Definition at line 98 of file DlgRunExternal.cpp.
References reject().
Referenced by PathPythonGui.simple_edit_panel.SimpleEditPanel::clicked(), DlgRunExternal(), and femsolver.run.Machine::run().
accept
void DlgRunExternal::accept () override protected slot
Definition at line 93 of file DlgRunExternal.cpp.
Referenced by femexamples.examplesgui.FemExamples::clicked(), DlgRunExternal(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
addArgument()
void DlgRunExternal::addArgument (const QString & arg)
Definition at line 70 of file DlgRunExternal.cpp.
Referenced by Gui::Dialog::DlgEditFileIncludePropertyExternal::processFile().
advanced
void DlgRunExternal::advanced () protected virtual slot
Definition at line 104 of file DlgRunExternal.cpp.
Referenced by DlgRunExternal().
finished
void DlgRunExternal::finished (int exitCode, QProcess::ExitStatus exitStatus) protected slot
Definition at line 116 of file DlgRunExternal.cpp.
Referenced by DlgRunExternal().
onChooseProgramClicked
void DlgRunExternal::onChooseProgramClicked () protected slot
Definition at line 125 of file DlgRunExternal.cpp.
Referenced by DlgRunExternal().
reject
void DlgRunExternal::reject () override protected slot
Definition at line 88 of file DlgRunExternal.cpp.
Referenced by abort(), bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), DlgRunExternal(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
runProcess()
int DlgRunExternal::runProcess ()
Definition at line 75 of file DlgRunExternal.cpp.
Referenced by Gui::Dialog::DlgEditFileIncludePropertyExternal::processFile().
The documentation for this class was generated from the following files:
DlgRunExternal.h
DlgRunExternal.cpp