FreeCAD: Gui::Dialog::TransformStrategy Class Reference
Gui::Dialog::TransformStrategy Class Reference abstract
#include <Transform.h>
Public Member Functions
TransformStrategy ()
virtual ~TransformStrategy ()
Base::Vector3d getRotationCenter () const
void acceptDataTransform (const Base::Matrix4D &mat, App::DocumentObject *obj)
void commitTransform (const Base::Matrix4D &plm)
void applyTransform (const Base::Placement &plm)
void resetTransform ()
void applyViewTransform (const Base::Placement &plm, App::DocumentObject *obj)
void resetViewTransform (App::DocumentObject *obj)
virtual std::set< App::DocumentObject * > transformObjects () const =0
Detailed Description
Definition at line 78 of file Transform.h.
Constructor & Destructor Documentation
TransformStrategy()
TransformStrategy::TransformStrategy () default
~TransformStrategy()
TransformStrategy::~TransformStrategy () virtual default
Member Function Documentation
acceptDataTransform()
void TransformStrategy::acceptDataTransform (const Base::Matrix4D & mat, App::DocumentObject * obj)
Definition at line 109 of file Transform.cpp.
References toolbit-attributes::doc, App::DocumentObject::getDocument(), Gui::Application::getDocument(), App::ExtensionContainer::getPropertyMap(), getValue(), Gui::Application::Instance, Base::BaseClass::isDerivedFrom(), Gui::ViewProvider::setTransformation(), and Base::Placement::toMatrix().
Referenced by commitTransform().
applyTransform()
void TransformStrategy::applyTransform (const Base::Placement & plm)
Definition at line 138 of file Transform.cpp.
References applyViewTransform(), importers.importIFCmulticore::objects, and transformObjects().
applyViewTransform()
void TransformStrategy::applyViewTransform (const Base::Placement & plm, App::DocumentObject * obj)
Definition at line 154 of file Transform.cpp.
References toolbit-attributes::doc, App::DocumentObject::getDocument(), Gui::Application::getDocument(), App::ExtensionContainer::getPropertyMap(), getValue(), Gui::Application::Instance, Gui::ViewProvider::setTransformation(), and Base::Placement::toMatrix().
Referenced by applyTransform().
commitTransform()
void TransformStrategy::commitTransform (const Base::Matrix4D & plm)
Definition at line 96 of file Transform.cpp.
References acceptDataTransform(), Gui::Application::activeDocument(), toolbit-attributes::doc, Gui::Application::Instance, importers.importIFCmulticore::objects, Arch::QT_TRANSLATE_NOOP, and transformObjects().
Referenced by Gui::Dialog::Transform::onApplyButtonClicked().
getRotationCenter()
Base::Vector3d TransformStrategy::getRotationCenter () const
Definition at line 66 of file Transform.cpp.
References Base::BoundBox3< Precision >::Add(), App::PropertyGeometry::getBoundingBox(), Base::BoundBox3< Precision >::MaxX, Base::BoundBox3< Precision >::MaxY, Base::BoundBox3< Precision >::MaxZ, Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, Base::BoundBox3< Precision >::MinZ, importers.importIFCmulticore::objects, and transformObjects().
Referenced by Gui::Dialog::Transform::onApplyButtonClicked(), and Gui::Dialog::Transform::setTransformStrategy().
resetTransform()
void TransformStrategy::resetTransform ()
Definition at line 146 of file Transform.cpp.
References importers.importIFCmulticore::objects, resetViewTransform(), and transformObjects().
Referenced by Gui::Dialog::Transform::reject().
resetViewTransform()
void TransformStrategy::resetViewTransform (App::DocumentObject * obj)
Definition at line 175 of file Transform.cpp.
References toolbit-attributes::doc, App::DocumentObject::getDocument(), Gui::Application::getDocument(), App::ExtensionContainer::getPropertyMap(), getValue(), Gui::Application::Instance, Gui::ViewProvider::setTransformation(), and Base::Placement::toMatrix().
Referenced by resetTransform().
transformObjects()
virtual std::set<App::DocumentObject*> Gui::Dialog::TransformStrategy::transformObjects () const pure virtual
Implemented in Gui::Dialog::DefaultTransformStrategy.
Referenced by applyTransform(), commitTransform(), getRotationCenter(), resetTransform(), and Gui::Dialog::Transform::setTransformStrategy().
The documentation for this class was generated from the following files:
Transform.h
Transform.cpp