FreeCAD: CAMSimulator::CAMSim Class Reference
CAMSimulator::CAMSim Class Reference
#include <CAMSim.h>
Public Member Functions
Base::Type getTypeId () const override
CAMSim ()=default
void BeginSimulation (const Part::TopoShape &stock, float resolution)
void resetSimulation ()
void addTool (const std::vector< float > &toolProfilePoints, int toolNumber, float diameter, float resolution)
void SetBaseShape (const Part::TopoShape &baseShape, float resolution)
void AddCommand (Command *cmd)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static Base::Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes
std::unique_ptr< SimStock > m_stock
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
The representation of a CNC Toolpath Simulator
Definition at line 43 of file CAMSim.h.
Constructor & Destructor Documentation
CAMSim()
CAMSimulator::CAMSim::CAMSim () default
Member Function Documentation
AddCommand()
void CAMSim::AddCommand (Command * cmd)
Definition at line 66 of file CAMSim.cpp.
References Path::Command::toGCode().
addTool()
void CAMSim::addTool (const std::vector< float > & toolProfilePoints, int toolNumber, float diameter, float resolution)
Definition at line 49 of file CAMSim.cpp.
BeginSimulation()
void CAMSim::BeginSimulation (const Part::TopoShape & stock, float resolution)
Definition at line 39 of file CAMSim.cpp.
create()
static void* CAMSimulator::CAMSim::create () static
Referenced by draftguitools.gui_labels.Label::action().
getClassTypeId()
static Base::Type CAMSimulator::CAMSim::getClassTypeId () static
getTypeId()
Base::Type CAMSimulator::CAMSim::getTypeId () const override virtual
Reimplemented from Base::BaseClass.
init()
static void CAMSimulator::CAMSim::init () static
Referenced by DocumentObject.DocumentObject::onChanged().
resetSimulation()
void CAMSimulator::CAMSim::resetSimulation ()
Definition at line 44 of file CAMSim.cpp.
SetBaseShape()
void CAMSimulator::CAMSim::SetBaseShape (const Part::TopoShape & baseShape, float resolution)
Definition at line 57 of file CAMSim.cpp.
References Part::TopoShape::isNull().
Member Data Documentation
m_stock
std::unique_ptr<SimStock> CAMSimulator::CAMSim::m_stock
Definition at line 70 of file CAMSim.h.
The documentation for this class was generated from the following files:
CAMSim.h
CAMSim.cpp