FreeCAD: Gui::PrefDoubleSpinBox Class Reference
Gui::PrefDoubleSpinBox Class Reference
#include <PrefWidgets.h>
Public Member Functions
PrefDoubleSpinBox (QWidget *parent=nullptr)
~PrefDoubleSpinBox () override
Public Member Functions inherited from Gui::PrefWidget
void setEntryName (const QByteArray &name)
QByteArray entryName () const
void setPrefEntry (const QByteArray &name)
void setParamGrpPath (const QByteArray &path)
QByteArray paramGrpPath () const
void setPrefPath (const QByteArray &name)
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
void onSave ()
void onRestore ()
Public Member Functions inherited from Gui::WindowParameter
WindowParameter (const char *name)
~WindowParameter () override
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
ParameterGrp::handle getWindowParameter ()
return the parameter group of this window
Protected Member Functions
void restorePreferences () override
void savePreferences () override
Protected Member Functions inherited from Gui::PrefWidget
void failedToSave (const QString &) const
void failedToRestore (const QString &) const
PrefWidget ()
~PrefWidget () override
Protected Member Functions inherited from Gui::WindowParameter
bool setGroupName (const char *name)
template<typename S , typename T >
void setSlotParamChanged (S slot, T *obsPtr)
connect slot to ParameterManager signal
Properties
QByteArray prefEntry
QByteArray prefPath
Additional Inherited Members
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter ()
get the parameters
Protected Attributes inherited from Gui::PrefWidget
bool m_Restored = false
Detailed Description
The PrefDoubleSpinBox class.
Author
Werner Mayer
Definition at line 154 of file PrefWidgets.h.
Constructor & Destructor Documentation
PrefDoubleSpinBox()
PrefDoubleSpinBox::PrefDoubleSpinBox (QWidget * parent = nullptr) explicit
Definition at line 201 of file PrefWidgets.cpp.
~PrefDoubleSpinBox()
PrefDoubleSpinBox::~PrefDoubleSpinBox () override default
Member Function Documentation
restorePreferences()
void PrefDoubleSpinBox::restorePreferences () override protected virtual
Restores the preferences Must be reimplemented in any subclasses.
Implements Gui::PrefWidget.
Definition at line 208 of file PrefWidgets.cpp.
References Gui::PrefWidget::entryName(), Gui::PrefWidget::failedToRestore(), ParameterGrp::GetFloat(), Gui::WindowParameter::getWindowParameter(), and draftgeoutils.general::isNull().
savePreferences()
void PrefDoubleSpinBox::savePreferences () override protected virtual
Save the preferences Must be reimplemented in any subclasses.
Implements Gui::PrefWidget.
Definition at line 220 of file PrefWidgets.cpp.
References Gui::PrefWidget::entryName(), Gui::PrefWidget::failedToSave(), Gui::WindowParameter::getWindowParameter(), draftgeoutils.general::isNull(), and ParameterGrp::SetFloat().
Property Documentation
prefEntry
QByteArray Gui::PrefDoubleSpinBox::prefEntry read write
Definition at line 158 of file PrefWidgets.h.
prefPath
QByteArray Gui::PrefDoubleSpinBox::prefPath read write
Definition at line 159 of file PrefWidgets.h.
The documentation for this class was generated from the following files:
PrefWidgets.h
PrefWidgets.cpp