FreeCAD: Part::ShapeMapper Struct Reference
Part::ShapeMapper Struct Reference
#include <TopoShapeMapper.h>
Classes
struct ShapeValue
Public Types
typedef std::unordered_map< TopoDS_Shape, ShapeValue, ShapeHasher, ShapeHasher > ShapeMap
Public Member Functions
virtual ~ShapeMapper () noexcept=default
void populate (MappingStatus status, const TopoShape &src, const TopTools_ListOfShape &dst)
void populate (MappingStatus status, const TopTools_ListOfShape &src, const TopTools_ListOfShape &dst)
void populate (MappingStatus status, const std::vector< TopoShape > &src, const std::vector< TopoShape > &dst)
void populate (MappingStatus status, const TopoShape &src, const std::vector< TopoShape > &dst)
void expand (const TopoDS_Shape &d, std::vector< TopoDS_Shape > &shapes)
void insert (MappingStatus status, const TopoDS_Shape &s, const std::vector< TopoDS_Shape > &d)
void insert (MappingStatus status, const TopoDS_Shape &s, const TopoDS_Shape &d)
const std::vector< TopoDS_Shape > & generated (const TopoDS_Shape &s) const override
Return a list of shape generated from the given input shape.
const std::vector< TopoDS_Shape > & modified (const TopoDS_Shape &s) const override
Return a list of shape modified from the given input shape.
Public Member Functions inherited from Part::TopoShape::Mapper
virtual ~Mapper ()
Public Attributes
std::vector< TopoShape > shapes
std::unordered_set< TopoDS_Shape, ShapeHasher, ShapeHasher > shapeSet
ShapeMap _generated
std::unordered_set< TopoDS_Shape, ShapeHasher, ShapeHasher > _generatedShapes
ShapeMap _modified
std::unordered_set< TopoDS_Shape, ShapeHasher, ShapeHasher > _modifiedShapes
Public Attributes inherited from Part::TopoShape::Mapper
std::vector< TopoDS_Shape > _res
Helper vector for temporary storage of both generated and modified shapes.
Detailed Description
Shape mapper for user defined shape mapping
Definition at line 118 of file TopoShapeMapper.h.
Member Typedef Documentation
ShapeMap
typedef std::unordered_map<TopoDS_Shape, ShapeValue, ShapeHasher, ShapeHasher> Part::ShapeMapper::ShapeMap
Definition at line 232 of file TopoShapeMapper.h.
Constructor & Destructor Documentation
~ShapeMapper()
virtual Part::ShapeMapper::~ShapeMapper () virtual default noexcept
Member Function Documentation
expand()
void Part::ShapeMapper::expand (const TopoDS_Shape & d, std::vector< TopoDS_Shape > & shapes)
Expand a shape into faces, edges and vertices @params d: shape to expand
Parameters
shapes output sub shapes of faces, edges and vertices
Definition at line 57 of file TopoShapeMapper.cpp.
References populate().
generated()
const std::vector<TopoDS_Shape>& Part::ShapeMapper::generated (const TopoDS_Shape &) const inline override virtual
Return a list of shape generated from the given input shape.
Reimplemented from Part::TopoShape::Mapper.
Definition at line 206 of file TopoShapeMapper.h.
References toolbit-attributes::s.
insert() [1/2]
void Part::ShapeMapper::insert (MappingStatus status, const TopoDS_Shape & s, const std::vector< TopoDS_Shape > & d)
Insert a map entry from a sub shape in the source to a list of sub shapes in the new shape
@params status: whether the sub shapes are generated or modified
Parameters
s a sub shape in the source
d a list of sub shapes in the new shape
Definition at line 123 of file TopoShapeMapper.cpp.
Referenced by Part::GenericShapeMapper::init().
insert() [2/2]
void Part::ShapeMapper::insert (MappingStatus status, const TopoDS_Shape & s, const TopoDS_Shape & d)
Insert a map entry from a sub shape in the source to a sub shape in the new shape
@params status: whether the sub shapes are generated or modified
Parameters
s a sub shape in the source
d a list of sub shapes in the new shape
Definition at line 99 of file TopoShapeMapper.cpp.
modified()
const std::vector<TopoDS_Shape>& Part::ShapeMapper::modified (const TopoDS_Shape &) const inline override virtual
Return a list of shape modified from the given input shape.
Reimplemented from Part::TopoShape::Mapper.
Definition at line 215 of file TopoShapeMapper.h.
References toolbit-attributes::s.
populate() [1/4]
void Part::ShapeMapper::populate (MappingStatus status, const std::vector< TopoShape > & src, const std::vector< TopoShape > & dst) inline
Populate mapping from a source sub shape to a list of shape
Parameters
status whether the shape is generated
src a list of sub shapes in the source shape
dst a list of sub shapes in the new shape
The source will be expanded into sub shapes of faces, edges and vertices before being inserted into the map.
Definition at line 154 of file TopoShapeMapper.h.
References toolbit-attributes::s.
populate() [2/4]
void Part::ShapeMapper::populate (MappingStatus status, const TopoShape & src, const std::vector< TopoShape > & dst) inline
Populate mapping from a source sub shape to a list of shape
Parameters
status whether the shape is generated
src a sub shape of the source shape
dst a list of sub shapes in the new shape
The source will be expanded into sub shapes of faces, edges and vertices before being inserted into the map.
Definition at line 172 of file TopoShapeMapper.h.
References AssemblyImport::insert().
populate() [3/4]
void Part::ShapeMapper::populate (MappingStatus status, const TopoShape & src, const TopTools_ListOfShape & dst)
Populate mapping from a source shape to a list of shape
Parameters
status whether the shape is generated
src source shape
dst a list of sub shapes in the new shape
The source will be expanded into sub shapes of faces, edges and vertices before being inserted into the map.
Definition at line 82 of file TopoShapeMapper.cpp.
Referenced by expand(), and PyShapeMapper::populate().
populate() [4/4]
void Part::ShapeMapper::populate (MappingStatus status, const TopTools_ListOfShape & src, const TopTools_ListOfShape & dst)
Populate mapping from a source sub shape to a list of shape
Parameters
status whether the shape is generated
src a list of sub shapes in the source shape
dst a list of sub shapes in the new shape
The source will be expanded into sub shapes of faces, edges and vertices before being inserted into the map.
Definition at line 73 of file TopoShapeMapper.cpp.
Member Data Documentation
_generated
ShapeMap Part::ShapeMapper::_generated
Definition at line 233 of file TopoShapeMapper.h.
_generatedShapes
std::unordered_set<TopoDS_Shape, ShapeHasher, ShapeHasher> Part::ShapeMapper::_generatedShapes
Definition at line 234 of file TopoShapeMapper.h.
_modified
ShapeMap Part::ShapeMapper::_modified
Definition at line 235 of file TopoShapeMapper.h.
_modifiedShapes
std::unordered_set<TopoDS_Shape, ShapeHasher, ShapeHasher> Part::ShapeMapper::_modifiedShapes
Definition at line 236 of file TopoShapeMapper.h.
shapes
std::vector<TopoShape> Part::ShapeMapper::shapes
Definition at line 224 of file TopoShapeMapper.h.
shapeSet
std::unordered_set<TopoDS_Shape, ShapeHasher, ShapeHasher> Part::ShapeMapper::shapeSet
Definition at line 225 of file TopoShapeMapper.h.
The documentation for this struct was generated from the following files:
TopoShapeMapper.h
TopoShapeMapper.cpp