FreeCAD: TechDrawGui::QGEPath Class Reference
TechDrawGui::QGEPath Class Reference
#include <QGEPath.h>
Public Types
enum { Type = QGraphicsItem::UserType + 301 }
Public Types inherited from TechDrawGui::QGIPrimPath
enum { Type = QGraphicsItem::UserType + 170 }
Public Slots
void onDragFinished (QPointF pos, int index)
void onDragging (QPointF pos, int index)
void onDoubleClick (QPointF pos, int markerIndex)
void onEndEdit ()
Signals
void pointsUpdated (QPointF attach, std::vector< QPointF > deltas)
void hover (bool state)
void selected (bool state)
Public Member Functions
QGEPath ()
~QGEPath () override=default
int type () const override
QRectF boundingRect () const override
QPainterPath shape () const override
void inEdit (bool isInEdit)
bool inEdit () const
void startPathEdit (const std::vector< QPointF > &pathPoints)
this begins an edit session for a path described by pathPoints.
void showMarkers (const std::vector< QPointF > &points)
void clearMarkers ()
void setScale (double scale)
double getScale () const
void updateParent ()
void drawGhost ()
the ghost is the red line drawn when creating or editing the points
void dumpGhostPoints (const char *text)
void dumpMarkerPos (const char *text)
void setStartAdjust (double adjust)
void setEndAdjust (double adjust)
Public Member Functions inherited from TechDrawGui::QGIPrimPath
QGIPrimPath ()
~QGIPrimPath () override=default
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QPainterPath shape () const override
virtual void setPrettyNormal ()
virtual void setPrettyPre ()
virtual void setPrettySel ()
virtual void setWidth (double w)
virtual double getWidth ()
Qt::PenStyle getStyle ()
void setStyle (Qt::PenStyle s)
void setStyle (int s)
virtual void setNormalColor (QColor c)
virtual void setCapStyle (Qt::PenCapStyle c)
void setFillStyle (Qt::BrushStyle f)
Qt::BrushStyle getFillStyle ()
void setFill (QColor c, Qt::BrushStyle s)
void setFill (QBrush b)
void resetFill ()
void setFillColor (QColor c)
QColor getFillColor ()
void setFillOverride (bool b)
virtual void setCurrentPen ()
Protected Member Functions
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
double getEdgeFuzz () const
Protected Member Functions inherited from TechDrawGui::QGIPrimPath
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
virtual bool multiselectEligible ()
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual QColor getNormalColor ()
virtual QColor getPreColor ()
virtual QColor getSelectColor ()
Base::Reference< ParameterGrp > getParmGroup ()
virtual Qt::PenCapStyle prefCapStyle ()
Additional Inherited Members
Protected Attributes inherited from TechDrawGui::QGIPrimPath
bool isHighlighted
bool multiselectActivated
QPen m_pen
QColor m_colCurrent
QColor m_colNormal
bool m_colOverride
Qt::PenStyle m_styleCurrent
Qt::PenStyle m_styleNormal
double m_width
Qt::PenCapStyle m_capStyle
QBrush m_brush
Qt::BrushStyle m_fillStyleCurrent
QColor m_fillColorCurrent
QColor m_colDefFill
QColor m_colNormalFill
Qt::BrushStyle m_fillDef
Qt::BrushStyle m_fillNormal
Qt::BrushStyle m_fillSelect
bool m_fillOverride
Detailed Description
Definition at line 99 of file QGEPath.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 107 of file QGEPath.h.
Constructor & Destructor Documentation
QGEPath()
QGEPath::QGEPath () explicit
QGEPath is an editable version of QGIPrimPath. Points along the path can be dragged to new positions that are returned to the caller on completion of the edit session. The points are in scene coordinates and are relative to the scene position of the caller.
Definition at line 139 of file QGEPath.cpp.
References TechDrawGui::QGIPrimPath::QGIPrimPath(), TechDrawGui::QGIPrimPath::setNormalColor(), TechDrawGui::QGIPrimPath::setPrettyNormal(), and TechDrawGui::QGIPrimPath::setStyle().
~QGEPath()
TechDrawGui::QGEPath::~QGEPath () override default
Member Function Documentation
boundingRect()
QRectF QGEPath::boundingRect () const override
Definition at line 361 of file QGEPath.cpp.
References shape().
clearMarkers()
void QGEPath::clearMarkers ()
Definition at line 263 of file QGEPath.cpp.
References test::m, and toolbit-attributes::s.
Referenced by TechDrawGui::QGILeaderLine::abandonEdit(), onEndEdit(), and showMarkers().
drawGhost()
void QGEPath::drawGhost ()
the ghost is the red line drawn when creating or editing the points
Definition at line 336 of file QGEPath.cpp.
References SplineSurface::i.
Referenced by onDragFinished().
dumpGhostPoints()
void QGEPath::dumpGhostPoints (const char * text)
Definition at line 380 of file QGEPath.cpp.
References Base::Console(), TechDraw::DrawUtil::formatVector(), and Base::ConsoleSingleton::Message().
dumpMarkerPos()
void QGEPath::dumpMarkerPos (const char * text)
Definition at line 390 of file QGEPath.cpp.
References Base::Console(), TechDraw::DrawUtil::formatVector(), test::m, and Base::ConsoleSingleton::Message().
getEdgeFuzz()
double QGEPath::getEdgeFuzz () const protected
Definition at line 375 of file QGEPath.cpp.
References TechDrawGui::PreferencesGui::edgeFuzz().
Referenced by shape().
getScale()
double TechDrawGui::QGEPath::getScale () const inline
Definition at line 120 of file QGEPath.h.
hover
void TechDrawGui::QGEPath::hover (bool state) signal
Referenced by hoverEnterEvent(), and hoverLeaveEvent().
hoverEnterEvent()
void QGEPath::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override protected
Definition at line 176 of file QGEPath.cpp.
References hover(), TechDrawGui::QGIPrimPath::hoverEnterEvent(), and TechDrawGui::QGIPrimPath::setPrettyPre().
hoverLeaveEvent()
void QGEPath::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override protected
Definition at line 185 of file QGEPath.cpp.
References hover(), Init::parent, and TechDrawGui::QGIPrimPath::setPrettyNormal().
inEdit() [1/2]
bool TechDrawGui::QGEPath::inEdit () const inline
Definition at line 113 of file QGEPath.h.
Referenced by onEndEdit(), showMarkers(), startPathEdit(), and updateParent().
inEdit() [2/2]
void TechDrawGui::QGEPath::inEdit (bool isInEdit) inline
Definition at line 112 of file QGEPath.h.
Referenced by TechDrawGui::QGILeaderLine::draw(), and TechDrawGui::QGILeaderLine::startPathEdit().
itemChange()
QVariant QGEPath::itemChange (GraphicsItemChange change, const QVariant & value) override protected
Definition at line 161 of file QGEPath.cpp.
References TechDrawGui::QGIPrimPath::itemChange(), selected(), TechDrawGui::QGIPrimPath::setPrettyNormal(), and TechDrawGui::QGIPrimPath::setPrettySel().
onDoubleClick
void QGEPath::onDoubleClick (QPointF pos, int markerIndex) slot
Definition at line 303 of file QGEPath.cpp.
References onEndEdit(), and RobotExample::pos.
Referenced by showMarkers().
onDragFinished
void QGEPath::onDragFinished (QPointF pos, int index) slot
Definition at line 283 of file QGEPath.cpp.
References drawGhost().
Referenced by showMarkers().
onDragging
void QGEPath::onDragging (QPointF pos, int index) slot
Definition at line 294 of file QGEPath.cpp.
References RobotExample::pos.
Referenced by showMarkers().
onEndEdit
void QGEPath::onEndEdit () slot
Definition at line 311 of file QGEPath.cpp.
References clearMarkers(), inEdit(), and updateParent().
Referenced by TechDrawGui::QGILeaderLine::closeEdit(), onDoubleClick(), and showMarkers().
pointsUpdated
void TechDrawGui::QGEPath::pointsUpdated (QPointF attach, std::vector< QPointF > deltas) signal
Referenced by TechDrawGui::QGILeaderLine::QGILeaderLine(), and updateParent().
selected
void TechDrawGui::QGEPath::selected (bool state) signal
Referenced by itemChange().
setEndAdjust()
void QGEPath::setEndAdjust (double adjust)
Definition at line 356 of file QGEPath.cpp.
References TechDrawGui::Rez::guiX().
setScale()
void TechDrawGui::QGEPath::setScale (double scale) inline
Definition at line 119 of file QGEPath.h.
Referenced by TechDrawGui::QGILeaderLine::startPathEdit().
setStartAdjust()
void QGEPath::setStartAdjust (double adjust)
Definition at line 351 of file QGEPath.cpp.
References TechDrawGui::Rez::guiX().
shape()
QPainterPath QGEPath::shape () const override
Definition at line 366 of file QGEPath.cpp.
References getEdgeFuzz().
Referenced by boundingRect().
showMarkers()
void QGEPath::showMarkers (const std::vector< QPointF > & points)
Definition at line 214 of file QGEPath.cpp.
References clearMarkers(), draftgeoutils.intersections::connect(), Base::Console(), TechDrawGui::QGMarker::doubleClick(), TechDrawGui::QGMarker::dragFinished(), TechDrawGui::QGMarker::dragging(), TechDrawGui::QGMarker::endEdit(), TechDrawGui::PreferencesGui::get3dMarkerSize(), TechDrawGui::PreferencesGui::getAccessibleQColor(), inEdit(), Base::ConsoleSingleton::Message(), onDoubleClick(), onDragFinished(), onDragging(), onEndEdit(), buildPsets::p, TestSpreadsheet::v, and ZVALUE::VERTEX.
Referenced by startPathEdit().
startPathEdit()
void QGEPath::startPathEdit (const std::vector< QPointF > & pathPoints)
this begins an edit session for a path described by pathPoints.
Definition at line 206 of file QGEPath.cpp.
References inEdit(), and showMarkers().
Referenced by TechDrawGui::QGILeaderLine::startPathEdit().
type()
int TechDrawGui::QGEPath::type () const inline override
Definition at line 108 of file QGEPath.h.
updateParent()
void QGEPath::updateParent ()
Definition at line 325 of file QGEPath.cpp.
References inEdit(), and pointsUpdated().
Referenced by onEndEdit().
The documentation for this class was generated from the following files:
QGEPath.h
QGEPath.cpp