FreeCAD: Wm4::Delaunay2< Real > Class Template Reference
Wm4::Delaunay2< Real > Class Template Reference
#include <Wm4Delaunay2.h>
Public Member Functions
Delaunay2 (int iVertexQuantity, Vector2< Real > *akVertex, Real fEpsilon, bool bOwner, Query::Type eQueryType)
virtual ~Delaunay2 ()
const Vector2< Real > * GetVertices () const
int GetUniqueVertexQuantity () const
const Vector2< Real > & GetLineOrigin () const
const Vector2< Real > & GetLineDirection () const
Delaunay1< Real > * GetDelaunay1 () const
bool GetHull (int &riEQuantity, int *&raiIndex)
int GetContainingTriangle (const Vector2< Real > &rkP) const
int GetPathLast () const
const int * GetPath () const
int GetLastEdge (int &riV0, int &riV1, int &riV2) const
bool GetVertexSet (int i, Vector2< Real > akV[3]) const
bool GetIndexSet (int i, int aiIndex[3]) const
bool GetAdjacentSet (int i, int aiAdjacent[3]) const
bool GetBarycentricSet (int i, const Vector2< Real > &rkP, Real afBary[3]) const
Delaunay2 (const char *acFilename)
bool Load (const char *acFilename)
bool Save (const char *acFilename) const
Public Member Functions inherited from Wm4::Delaunay< Real >
virtual ~Delaunay ()
int GetQueryType () const
int GetVertexQuantity () const
Real GetEpsilon () const
bool GetOwner () const
int GetDimension () const
int GetSimplexQuantity () const
const int * GetIndices () const
const int * GetAdjacencies () const
Additional Inherited Members
Protected Member Functions inherited from Wm4::Delaunay< Real >
Delaunay (int iVertexQuantity, Real fEpsilon, bool bOwner, Query::Type eQueryType)
bool Load (FILE *pkIFile)
bool Save (FILE *pkOFile) const
Protected Attributes inherited from Wm4::Delaunay< Real >
Query::Type m_eQueryType
int m_iVertexQuantity
int m_iDimension
int m_iSimplexQuantity
int * m_aiIndex
int * m_aiAdjacent
Real m_fEpsilon
bool m_bOwner
Detailed Description
template<class Real>
class Wm4::Delaunay2< Real >
Definition at line 29 of file Wm4Delaunay2.h.
Constructor & Destructor Documentation
Delaunay2() [1/2]
template<class Real > Wm4::Delaunay2< Real >::Delaunay2 (int iVertexQuantity, Vector2< Real > * akVertex, Real fEpsilon, bool bOwner, Query::Type eQueryType)
Definition at line 31 of file Wm4Delaunay2.cpp.
References Wm4::DelTriangle< Real >::A, Wm4::Mapper2< Real >::GetDimension(), Wm4::Mapper2< Real >::GetDirection(), Wm4::Mapper2< Real >::GetMax(), Wm4::Mapper2< Real >::GetMaxRange(), Wm4::Mapper2< Real >::GetMin(), Wm4::Mapper2< Real >::GetOrigin(), SplineSurface::i, Wm4::Delaunay< Real >::m_aiAdjacent, Wm4::Delaunay< Real >::m_aiIndex, Wm4::Delaunay< Real >::m_fEpsilon, Wm4::Delaunay< Real >::m_iDimension, Wm4::Delaunay< Real >::m_iSimplexQuantity, Wm4::Delaunay< Real >::m_iVertexQuantity, Wm4::System::Memcpy(), Wm4::Query::QT_FILTERED, Wm4::Query::QT_INT64, Wm4::Query::QT_INTEGER, Wm4::Query::QT_RATIONAL, Wm4::DelTriangle< Real >::V, WM4_DELETE, and WM4_NEW.
~Delaunay2()
template<class Real > Wm4::Delaunay2< Real >::~Delaunay2 virtual
Definition at line 225 of file Wm4Delaunay2.cpp.
References WM4_DELETE.
Delaunay2() [2/2]
template<class Real > Wm4::Delaunay2< Real >::Delaunay2 (const char * acFilename)
Definition at line 728 of file Wm4Delaunay2.cpp.
References Wm4::Delaunay2< Real >::Load().
Member Function Documentation
GetAdjacentSet()
template<class Real > bool Wm4::Delaunay2< Real >::GetAdjacentSet (int i, int aiAdjacent[3]) const
Definition at line 464 of file Wm4Delaunay2.cpp.
References SplineSurface::i.
GetBarycentricSet()
template<class Real > bool Wm4::Delaunay2< Real >::GetBarycentricSet (int i, const Vector2< Real > & rkP, Real afBary[3]) const
Definition at line 484 of file Wm4Delaunay2.cpp.
References Wm4::Vector2< Real >::GetBarycentrics(), and SplineSurface::i.
GetContainingTriangle()
template<class Real > int Wm4::Delaunay2< Real >::GetContainingTriangle (const Vector2< Real > & rkP) const
Definition at line 324 of file Wm4Delaunay2.cpp.
References SplineSurface::i.
GetDelaunay1()
template<class Real > Delaunay1< Real > * Wm4::Delaunay2< Real >::GetDelaunay1
Definition at line 261 of file Wm4Delaunay2.cpp.
References Wm4::Vector2< Real >::Dot(), SplineSurface::i, and WM4_NEW.
GetHull()
template<class Real > bool Wm4::Delaunay2< Real >::GetHull (int & riEQuantity, int *& raiIndex)
Definition at line 281 of file Wm4Delaunay2.cpp.
References SplineSurface::i, and WM4_NEW.
Referenced by MeshCore::DelaunayTriangulator::Triangulate().
GetIndexSet()
template<class Real > bool Wm4::Delaunay2< Real >::GetIndexSet (int i, int aiIndex[3]) const
Definition at line 444 of file Wm4Delaunay2.cpp.
References SplineSurface::i.
GetLastEdge()
template<class Real > int Wm4::Delaunay2< Real >::GetLastEdge (int & riV0, int & riV1, int & riV2) const
Definition at line 415 of file Wm4Delaunay2.cpp.
GetLineDirection()
template<class Real > const Vector2< Real > & Wm4::Delaunay2< Real >::GetLineDirection
Definition at line 255 of file Wm4Delaunay2.cpp.
GetLineOrigin()
template<class Real > const Vector2< Real > & Wm4::Delaunay2< Real >::GetLineOrigin
Definition at line 249 of file Wm4Delaunay2.cpp.
GetPath()
template<class Real > const int * Wm4::Delaunay2< Real >::GetPath
Definition at line 409 of file Wm4Delaunay2.cpp.
GetPathLast()
template<class Real > int Wm4::Delaunay2< Real >::GetPathLast
Definition at line 403 of file Wm4Delaunay2.cpp.
GetUniqueVertexQuantity()
template<class Real > int Wm4::Delaunay2< Real >::GetUniqueVertexQuantity
Definition at line 243 of file Wm4Delaunay2.cpp.
Referenced by MeshCore::DelaunayTriangulator::Triangulate().
GetVertexSet()
template<class Real > bool Wm4::Delaunay2< Real >::GetVertexSet (int i, Vector2< Real > akV[3]) const
Definition at line 424 of file Wm4Delaunay2.cpp.
References SplineSurface::i.
GetVertices()
template<class Real > const Vector2< Real > * Wm4::Delaunay2< Real >::GetVertices
Definition at line 237 of file Wm4Delaunay2.cpp.
Load()
template<class Real > bool Wm4::Delaunay2< Real >::Load (const char * acFilename)
Definition at line 742 of file Wm4Delaunay2.cpp.
References Wm4::System::Fclose(), Wm4::System::Fopen(), Wm4::Delaunay< Real >::Load(), Wm4::Query::QT_FILTERED, Wm4::Query::QT_INT64, Wm4::Query::QT_INTEGER, Wm4::Query::QT_RATIONAL, Wm4::Query::QT_REAL, Wm4::System::Read4le(), Wm4::System::Read8le(), WM4_DELETE, and WM4_NEW.
Referenced by Wm4::Delaunay2< Real >::Delaunay2().
Save()
template<class Real > bool Wm4::Delaunay2< Real >::Save (const char * acFilename) const
Definition at line 823 of file Wm4Delaunay2.cpp.
References Wm4::System::Fclose(), Wm4::System::Fopen(), Wm4::Delaunay< Real >::Save(), Wm4::System::Write4le(), and Wm4::System::Write8le().
The documentation for this class was generated from the following files:
Wm4Delaunay2.h
Wm4Delaunay2.cpp