FreeCAD: MeshCore::MeshFacetIterator Class Reference
MeshCore::MeshFacetIterator Class Reference
#include <Iterator.h>
Public Member Functions
Construction
MeshFacetIterator (const MeshKernel &rclM)
construction
MeshFacetIterator (const MeshKernel &rclM, FacetIndex ulPos)
construction
MeshFacetIterator (const MeshFacetIterator &rclI)
construction
MeshFacetIterator (MeshFacetIterator &&rclI)
~MeshFacetIterator ()=default
Transformation
void Transform (const Base::Matrix4D &rclTrf)
Transforms the returned facet points with the current transformation.
Access methods
const MeshGeomFacet & operator* ()
Access to the element the iterator points to.
const MeshGeomFacet * operator-> ()
Access to the element the iterator points to.
const MeshFacetIterator & operator++ ()
const MeshFacetIterator & operator-- ()
const MeshFacetIterator & operator+= (int k)
Increments the iterator by k positions.
const MeshFacetIterator & operator-= (int k)
Decrements the iterator by k positions.
MeshFacetIterator & operator= (const MeshFacetIterator &rpI)
Assignment.
MeshFacetIterator & operator= (MeshFacetIterator &&rpI)
bool operator< (const MeshFacetIterator &rclI) const
Compares if this iterator points to a lower element than the other one.
bool operator> (const MeshFacetIterator &rclI) const
Compares if this iterator points to a higher element than the other one.
bool operator== (const MeshFacetIterator &rclI) const
Checks if the iterators points to the same element.
void Begin ()
Sets the iterator to the beginning of the array.
void End ()
Sets the iterator to the end of the array.
FacetIndex Position () const
Returns the current position of the iterator in the array.
bool EndReached () const
Checks if the end is already reached.
void Init ()
Sets the iterator to the beginning of the array.
bool More () const
Checks if the end is not yet reached.
void Next ()
Increments the iterator.
bool Set (FacetIndex ulIndex)
Sets the iterator to a given position.
MeshFacet GetIndices () const
Returns the topologic facet.
const MeshFacet & GetReference () const
Returns the topologic facet.
void GetNeighbours (MeshFacetIterator &rclN0, MeshFacetIterator &rclN1, MeshFacetIterator &rclN2) const
Returns iterators pointing to the current facet's neighbours.
void SetToNeighbour (unsigned short usN)
Sets the iterator to the current facet's neighbour of the side usN.
unsigned long GetProperty () const
Returns the property information to the current facet.
bool IsValid () const
Checks if the iterator points to a valid element inside the array.
Flag state
class MeshKernel
void SetFlag (MeshFacet::TFlagType tF) const
void ResetFlag (MeshFacet::TFlagType tF) const
bool IsFlag (MeshFacet::TFlagType tF) const
void SetProperty (unsigned long uP) const
const MeshGeomFacet & Dereference ()
Detailed Description
The MeshFacetIterator allows one to iterate over the facets that hold the topology of the mesh and provides access to their geometric information.
Note
This class is not thread-safe.
Definition at line 69 of file Iterator.h.
Constructor & Destructor Documentation
MeshFacetIterator() [1/4]
MeshCore::MeshFacetIterator::MeshFacetIterator (const MeshKernel & rclM) inline explicit
construction
Definition at line 434 of file Iterator.h.
MeshFacetIterator() [2/4]
MeshCore::MeshFacetIterator::MeshFacetIterator (const MeshKernel & rclM, FacetIndex ulPos) inline
construction
Definition at line 442 of file Iterator.h.
MeshFacetIterator() [3/4]
MeshCore::MeshFacetIterator::MeshFacetIterator (const MeshFacetIterator & rclI) inline
construction
Definition at line 450 of file Iterator.h.
MeshFacetIterator() [4/4]
MeshCore::MeshFacetIterator::MeshFacetIterator (MeshFacetIterator && rclI) inline
Definition at line 459 of file Iterator.h.
~MeshFacetIterator()
MeshCore::MeshFacetIterator::~MeshFacetIterator () default
Member Function Documentation
Begin()
void MeshCore::MeshFacetIterator::Begin () inline
Sets the iterator to the beginning of the array.
Definition at line 147 of file Iterator.h.
Referenced by MeshCore::MeshEvalSelfIntersection::Evaluate(), MeshCore::MeshKernel::FacetIterator(), Mesh::MeshObject::foraminate(), MeshCore::MeshIntersection::getIntersection(), and MeshCore::MeshEvalSelfIntersection::GetIntersections().
Dereference()
const MeshGeomFacet & MeshCore::MeshFacetIterator::Dereference () inline protected
Definition at line 476 of file Iterator.h.
End()
void MeshCore::MeshFacetIterator::End () inline
Sets the iterator to the end of the array.
Definition at line 152 of file Iterator.h.
References EndReached().
Referenced by Mesh::ExporterAMF::addMesh(), WriterInventorImp::addNormalNode(), MeshCore::MeshKernel::DeletePoint(), MeshCore::MeshInfo::DetailedFacetInfo(), MeshCore::WriterOBJ::Save(), MeshCore::MeshOutput::SaveAsciiSTL(), MeshCore::MeshOutput::SaveAsymptote(), and MeshCore::MeshOutput::SaveBinarySTL().
EndReached()
bool MeshCore::MeshFacetIterator::EndReached () const inline
Checks if the end is already reached.
Definition at line 162 of file Iterator.h.
Referenced by MeshCore::MeshEvalDegeneratedFacets::CountEdgeTooSmall(), and End().
GetIndices()
MeshFacet MeshCore::MeshFacetIterator::GetIndices () const inline
Returns the topologic facet.
Definition at line 184 of file Iterator.h.
Referenced by MeshCore::MeshOutput::SaveNastran(), and MeshCore::MeshOutput::SaveVRML().
GetNeighbours()
void MeshCore::MeshFacetIterator::GetNeighbours (MeshFacetIterator & rclN0, MeshFacetIterator & rclN1, MeshFacetIterator & rclN2) const inline
Returns iterators pointing to the current facet's neighbours.
Definition at line 527 of file Iterator.h.
GetProperty()
unsigned long MeshCore::MeshFacetIterator::GetProperty () const inline
Returns the property information to the current facet.
Definition at line 522 of file Iterator.h.
GetReference()
const MeshFacet& MeshCore::MeshFacetIterator::GetReference () const inline
Returns the topologic facet.
Definition at line 189 of file Iterator.h.
Referenced by MeshCore::MeshFixDeformedFacets::Fixup(), and MeshCore::MeshFixCorruptedFacets::Fixup().
Init()
void MeshCore::MeshFacetIterator::Init () inline
Sets the iterator to the beginning of the array.
Definition at line 167 of file Iterator.h.
Referenced by MeshGui::ViewProviderMeshTransformDemolding::calcNormalVector(), MeshCore::MeshTrimming::CheckFacets(), MeshCore::MeshAlgorithm::CheckFacets(), MeshCore::MeshEvalDegeneratedFacets::Evaluate(), MeshCore::MeshEvalDeformedFacets::Evaluate(), MeshPart::CurveProjectorShape::findStartPoint(), MeshPart::CurveProjectorSimple::findStartPoint(), MeshCore::MeshFixDegeneratedFacets::Fixup(), MeshCore::MeshFixDeformedFacets::Fixup(), MeshCore::MeshFixCorruptedFacets::Fixup(), MeshCore::MeshAlgorithm::GetAverageEdgeLength(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), MeshCore::MeshEvalDegeneratedFacets::GetIndices(), MeshCore::MeshEvalDeformedFacets::GetIndices(), MeshCore::MeshAlgorithm::GetMaximumEdgeLength(), MeshCore::MeshAlgorithm::GetMinimumEdgeLength(), MeshCore::MeshKernel::GetSurface(), MeshCore::MeshKernel::GetVolume(), MeshPart::CurveProjectorWithToolMesh::makeToolMesh(), MeshCore::MeshAlgorithm::NearestFacetOnRay(), MeshCore::MeshAlgorithm::NearestPointFromPoint(), MeshPart::MeshAlgos::offsetSpecial2(), Mesh::MeshObject::offsetSpecial2(), MeshPart::CurveProjectorSimple::projectCurve(), Inspection::MeshInspectGrid::RebuildGrid(), MeshCore::MeshFacetGrid::RebuildGrid(), MeshCore::MeshSearchNeighbours::SampleAllFacets(), MeshCore::MeshOutput::SaveNastran(), MeshCore::MeshOutput::SavePython(), MeshCore::MeshOutput::SaveVRML(), MeshCore::MeshAlgorithm::SubSampleByDist(), MeshCore::MeshAlgorithm::Surface(), and MeshCore::MeshAlgorithm::Surround().
IsFlag()
bool MeshCore::MeshFacetIterator::IsFlag (MeshFacet::TFlagType tF) const inline
Definition at line 218 of file Iterator.h.
IsValid()
bool MeshCore::MeshFacetIterator::IsValid () const inline
Checks if the iterator points to a valid element inside the array.
Definition at line 202 of file Iterator.h.
More()
bool MeshCore::MeshFacetIterator::More () const inline
Checks if the end is not yet reached.
Definition at line 172 of file Iterator.h.
Referenced by MeshGui::ViewProviderMeshTransformDemolding::calcNormalVector(), MeshCore::MeshTrimming::CheckFacets(), MeshCore::MeshAlgorithm::CheckFacets(), MeshCore::MeshEvalDegeneratedFacets::Evaluate(), MeshCore::MeshEvalSelfIntersection::Evaluate(), MeshCore::MeshEvalDeformedFacets::Evaluate(), MeshPart::CurveProjectorShape::findStartPoint(), MeshPart::CurveProjectorSimple::findStartPoint(), MeshCore::MeshFixDegeneratedFacets::Fixup(), MeshCore::MeshFixDeformedFacets::Fixup(), MeshCore::MeshFixCorruptedFacets::Fixup(), Mesh::MeshObject::foraminate(), MeshCore::MeshAlgorithm::GetAverageEdgeLength(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), MeshCore::MeshEvalDegeneratedFacets::GetIndices(), MeshCore::MeshEvalDeformedFacets::GetIndices(), MeshCore::MeshIntersection::getIntersection(), MeshCore::MeshEvalSelfIntersection::GetIntersections(), MeshCore::MeshAlgorithm::GetMaximumEdgeLength(), MeshCore::MeshAlgorithm::GetMinimumEdgeLength(), MeshCore::MeshKernel::GetSurface(), MeshCore::MeshKernel::GetVolume(), MeshPart::CurveProjectorWithToolMesh::makeToolMesh(), MeshCore::MeshAlgorithm::NearestFacetOnRay(), MeshCore::MeshAlgorithm::NearestPointFromPoint(), MeshPart::MeshAlgos::offsetSpecial2(), Mesh::MeshObject::offsetSpecial2(), MeshPart::CurveProjectorSimple::projectCurve(), Inspection::MeshInspectGrid::RebuildGrid(), MeshCore::MeshFacetGrid::RebuildGrid(), MeshCore::MeshSearchNeighbours::SampleAllFacets(), MeshCore::MeshOutput::SaveNastran(), MeshCore::MeshOutput::SavePython(), MeshCore::MeshOutput::SaveVRML(), MeshCore::MeshAlgorithm::SubSampleByDist(), MeshCore::MeshAlgorithm::Surface(), and MeshCore::MeshAlgorithm::Surround().
Next()
void MeshCore::MeshFacetIterator::Next () inline
Increments the iterator.
Definition at line 177 of file Iterator.h.
Referenced by MeshGui::ViewProviderMeshTransformDemolding::calcNormalVector(), MeshCore::MeshTrimming::CheckFacets(), MeshCore::MeshAlgorithm::CheckFacets(), MeshCore::MeshEvalDegeneratedFacets::Evaluate(), MeshCore::MeshEvalSelfIntersection::Evaluate(), MeshCore::MeshEvalDeformedFacets::Evaluate(), MeshPart::CurveProjectorShape::findStartPoint(), MeshPart::CurveProjectorSimple::findStartPoint(), MeshCore::MeshFixDegeneratedFacets::Fixup(), MeshCore::MeshFixDeformedFacets::Fixup(), MeshCore::MeshFixCorruptedFacets::Fixup(), Mesh::MeshObject::foraminate(), MeshCore::MeshAlgorithm::GetAverageEdgeLength(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), MeshCore::MeshEvalDegeneratedFacets::GetIndices(), MeshCore::MeshEvalDeformedFacets::GetIndices(), MeshCore::MeshIntersection::getIntersection(), MeshCore::MeshEvalSelfIntersection::GetIntersections(), MeshCore::MeshAlgorithm::GetMaximumEdgeLength(), MeshCore::MeshAlgorithm::GetMinimumEdgeLength(), MeshCore::MeshKernel::GetSurface(), MeshCore::MeshKernel::GetVolume(), MeshPart::CurveProjectorWithToolMesh::makeToolMesh(), MeshCore::MeshAlgorithm::NearestFacetOnRay(), MeshCore::MeshAlgorithm::NearestPointFromPoint(), MeshPart::MeshAlgos::offsetSpecial2(), Mesh::MeshObject::offsetSpecial2(), MeshPart::CurveProjectorSimple::projectCurve(), Inspection::MeshInspectGrid::RebuildGrid(), MeshCore::MeshFacetGrid::RebuildGrid(), MeshCore::MeshSearchNeighbours::SampleAllFacets(), MeshCore::MeshOutput::SaveNastran(), MeshCore::MeshOutput::SavePython(), MeshCore::MeshOutput::SaveVRML(), MeshCore::MeshAlgorithm::SubSampleByDist(), MeshCore::MeshAlgorithm::Surface(), and MeshCore::MeshAlgorithm::Surround().
operator*()
const MeshGeomFacet& MeshCore::MeshFacetIterator::operator* () inline
Access to the element the iterator points to.
Definition at line 93 of file Iterator.h.
operator++()
const MeshFacetIterator& MeshCore::MeshFacetIterator::operator++ () inline
Increments the iterator. It points then to the next element if the end is not reached.
Definition at line 104 of file Iterator.h.
Referenced by Position().
operator+=()
const MeshFacetIterator& MeshCore::MeshFacetIterator::operator+= (int k) inline
Increments the iterator by k positions.
Definition at line 117 of file Iterator.h.
operator--()
const MeshFacetIterator& MeshCore::MeshFacetIterator::operator-- () inline
Decrements the iterator. It points then to the previous element if the beginning is not reached.
Definition at line 111 of file Iterator.h.
operator-=()
const MeshFacetIterator& MeshCore::MeshFacetIterator::operator-= (int k) inline
Decrements the iterator by k positions.
Definition at line 123 of file Iterator.h.
operator->()
const MeshGeomFacet* MeshCore::MeshFacetIterator::operator-> () inline
Access to the element the iterator points to.
Definition at line 98 of file Iterator.h.
operator<()
bool MeshCore::MeshFacetIterator::operator< (const MeshFacetIterator & rclI) const inline
Compares if this iterator points to a lower element than the other one.
Definition at line 132 of file Iterator.h.
operator=() [1/2]
MeshFacetIterator & MeshCore::MeshFacetIterator::operator= (const MeshFacetIterator & rpI) inline
Assignment.
Definition at line 506 of file Iterator.h.
References MeshCore::FACET_INDEX_MAX.
operator=() [2/2]
MeshFacetIterator & MeshCore::MeshFacetIterator::operator= (MeshFacetIterator && rpI) inline
Definition at line 514 of file Iterator.h.
operator==()
bool MeshCore::MeshFacetIterator::operator== (const MeshFacetIterator & rclI) const inline
Checks if the iterators points to the same element.
Definition at line 142 of file Iterator.h.
operator>()
bool MeshCore::MeshFacetIterator::operator> (const MeshFacetIterator & rclI) const inline
Compares if this iterator points to a higher element than the other one.
Definition at line 137 of file Iterator.h.
Position()
FacetIndex MeshCore::MeshFacetIterator::Position () const inline
Returns the current position of the iterator in the array.
Definition at line 157 of file Iterator.h.
References operator++().
Referenced by MeshCore::MeshTrimming::CheckFacets(), MeshCore::MeshAlgorithm::CheckFacets(), MeshCore::MeshKernel::DeleteFacet(), MeshPart::CurveProjectorShape::findStartPoint(), MeshPart::CurveProjectorSimple::findStartPoint(), MeshCore::MeshFixDegeneratedFacets::Fixup(), MeshCore::MeshFixDeformedFacets::Fixup(), MeshCore::MeshFixCorruptedFacets::Fixup(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), MeshCore::MeshEvalDegeneratedFacets::GetIndices(), MeshCore::MeshEvalDeformedFacets::GetIndices(), MeshCore::MeshAlgorithm::NearestFacetOnRay(), MeshCore::MeshAlgorithm::NearestPointFromPoint(), MeshPart::MeshAlgos::offsetSpecial2(), Mesh::MeshObject::offsetSpecial2(), and MeshPart::CurveProjectorSimple::projectCurve().
ResetFlag()
void MeshCore::MeshFacetIterator::ResetFlag (MeshFacet::TFlagType tF) const inline
Definition at line 214 of file Iterator.h.
Set()
bool MeshCore::MeshFacetIterator::Set (FacetIndex ulIndex) inline
Sets the iterator to a given position.
Definition at line 495 of file Iterator.h.
Referenced by Mesh::MeshObject::const_facet_iterator::const_facet_iterator(), MeshCore::MeshKernel::DeleteFacet(), MeshCore::MeshEvalSelfIntersection::Evaluate(), Mesh::SegmentByMesh::execute(), MeshCore::MeshFixDegeneratedFacets::Fixup(), MeshCore::MeshFixCorruptedFacets::Fixup(), MeshCore::MeshAlgorithm::GetFacetsFromToolMesh(), MeshCore::MeshIntersection::getIntersection(), MeshCore::MeshEvalSelfIntersection::GetIntersections(), MeshCore::MeshKernel::GetSurface(), MeshPart::MeshProjection::projectEdgeToEdge(), Mesh::MeshObject::refine(), MeshGui::ViewProviderMeshOrientation::showDefects(), MeshGui::ViewProviderMeshDuplicatedFaces::showDefects(), MeshGui::ViewProviderMeshDegenerations::showDefects(), MeshGui::ViewProviderMeshIndices::showDefects(), MeshGui::ViewProviderMeshFolds::showDefects(), Mesh::MeshObject::splitEdges(), and MeshCore::MeshFacetGrid::Verify().
SetFlag()
void MeshCore::MeshFacetIterator::SetFlag (MeshFacet::TFlagType tF) const inline
Definition at line 210 of file Iterator.h.
SetProperty()
void MeshCore::MeshFacetIterator::SetProperty (unsigned long uP) const inline
Definition at line 222 of file Iterator.h.
SetToNeighbour()
void MeshCore::MeshFacetIterator::SetToNeighbour (unsigned short usN) inline
Sets the iterator to the current facet's neighbour of the side usN.
Definition at line 553 of file Iterator.h.
Transform()
void MeshCore::MeshFacetIterator::Transform (const Base::Matrix4D & rclTrf) inline
Transforms the returned facet points with the current transformation.
Definition at line 468 of file Iterator.h.
Referenced by Mesh::MeshObject::const_facet_iterator::const_facet_iterator(), Inspection::MeshInspectGrid::RebuildGrid(), MeshCore::MeshOutput::SavePython(), and MeshCore::MeshOutput::SaveVRML().
Friends And Related Function Documentation
MeshKernel
friend class MeshKernel friend
Definition at line 241 of file Iterator.h.
The documentation for this class was generated from the following file:
Iterator.h