FreeCAD: ifc2x3.ifcelectricalbaseproperties Class Reference
ifc2x3.ifcelectricalbaseproperties Class Reference
Public Member Functions
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__energysequence, inherited5__userdefinedenergysequence, electriccurrenttype, inputvoltage, inputfrequency, fullloadcurrent, minimumcircuitcurrent, maximumpowerinput, ratedpowerinput, inputphase)
def electriccurrenttype ()
def inputvoltage ()
def inputfrequency ()
def fullloadcurrent ()
def minimumcircuitcurrent ()
def maximumpowerinput ()
def ratedpowerinput ()
def inputphase ()
Public Member Functions inherited from ifc2x3.ifcenergyproperties
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, energysequence, userdefinedenergysequence)
def energysequence ()
def userdefinedenergysequence ()
Public Member Functions inherited from ifc2x3.ifcpropertysetdefinition
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description)
def propertydefinitionof ()
def definestype ()
Public Member Functions inherited from ifc2x3.ifcpropertydefinition
def hasassociations ()
Public Member Functions inherited from ifc2x3.ifcroot
def globalid ()
def ownerhistory ()
def name ()
def description ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
electriccurrenttype
inputvoltage
inputfrequency
fullloadcurrent
minimumcircuitcurrent
maximumpowerinput
ratedpowerinput
inputphase
Public Attributes inherited from ifc2x3.ifcenergyproperties
energysequence
userdefinedenergysequence
Public Attributes inherited from ifc2x3.ifcroot
globalid
ownerhistory
name
description
Detailed Description
Entity ifcelectricalbaseproperties definition.
:param electriccurrenttype
:type electriccurrenttype:ifcelectriccurrentenum
:param inputvoltage
:type inputvoltage:ifcelectricvoltagemeasure
:param inputfrequency
:type inputfrequency:ifcfrequencymeasure
:param fullloadcurrent
:type fullloadcurrent:ifcelectriccurrentmeasure
:param minimumcircuitcurrent
:type minimumcircuitcurrent:ifcelectriccurrentmeasure
:param maximumpowerinput
:type maximumpowerinput:ifcpowermeasure
:param ratedpowerinput
:type ratedpowerinput:ifcpowermeasure
:param inputphase
:type inputphase:INTEGER
Definition at line 31347 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcelectricalbaseproperties.__init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__energysequence, inherited5__userdefinedenergysequence, electriccurrenttype, inputvoltage, inputfrequency, fullloadcurrent, minimumcircuitcurrent, maximumpowerinput, ratedpowerinput, inputphase)
Definition at line 31374 of file ifc2x3.py.
Member Function Documentation
electriccurrenttype()
def ifc2x3.ifcelectricalbaseproperties.electriccurrenttype ()
Definition at line 31386 of file ifc2x3.py.
References ifc2x3.ifcelectricalbaseproperties._electriccurrenttype, SCL.TypeChecker.check_type(), and ifc2x3.ifcelectricalbaseproperties.electriccurrenttype.
fullloadcurrent()
def ifc2x3.ifcelectricalbaseproperties.fullloadcurrent ()
Definition at line 31428 of file ifc2x3.py.
References ifc2x3.ifcelectricalbaseproperties._fullloadcurrent, SCL.TypeChecker.check_type(), and ifc2x3.ifcelectricalbaseproperties.fullloadcurrent.
inputfrequency()
def ifc2x3.ifcelectricalbaseproperties.inputfrequency ()
Definition at line 31414 of file ifc2x3.py.
References ifc2x3.ifcelectricalbaseproperties._inputfrequency, SCL.TypeChecker.check_type(), and ifc2x3.ifcelectricalbaseproperties.inputfrequency.
inputphase()
def ifc2x3.ifcelectricalbaseproperties.inputphase ()
Definition at line 31484 of file ifc2x3.py.
References ifc2x3.ifcelectricalbaseproperties._inputphase, SCL.TypeChecker.check_type(), and ifc2x3.ifcelectricalbaseproperties.inputphase.
inputvoltage()
def ifc2x3.ifcelectricalbaseproperties.inputvoltage ()
Definition at line 31400 of file ifc2x3.py.
References ifc2x3.ifcelectricalbaseproperties._inputvoltage, SCL.TypeChecker.check_type(), and ifc2x3.ifcelectricalbaseproperties.inputvoltage.
maximumpowerinput()
def ifc2x3.ifcelectricalbaseproperties.maximumpowerinput ()
Definition at line 31456 of file ifc2x3.py.
References ifc2x3.ifcelectricalbaseproperties._maximumpowerinput, SCL.TypeChecker.check_type(), and ifc2x3.ifcelectricalbaseproperties.maximumpowerinput.
minimumcircuitcurrent()
def ifc2x3.ifcelectricalbaseproperties.minimumcircuitcurrent ()
Definition at line 31442 of file ifc2x3.py.
References ifc2x3.ifcelectricalbaseproperties._minimumcircuitcurrent, SCL.TypeChecker.check_type(), and ifc2x3.ifcelectricalbaseproperties.minimumcircuitcurrent.
ratedpowerinput()
def ifc2x3.ifcelectricalbaseproperties.ratedpowerinput ()
Definition at line 31470 of file ifc2x3.py.
References ifc2x3.ifcelectricalbaseproperties._ratedpowerinput, SCL.TypeChecker.check_type(), and ifc2x3.ifcelectricalbaseproperties.ratedpowerinput.
Member Data Documentation
electriccurrenttype
ifc2x3.ifcelectricalbaseproperties.electriccurrenttype
Definition at line 31376 of file ifc2x3.py.
Referenced by ifc2x3.ifcelectricalbaseproperties.electriccurrenttype().
fullloadcurrent
ifc2x3.ifcelectricalbaseproperties.fullloadcurrent
Definition at line 31379 of file ifc2x3.py.
Referenced by ifc2x3.ifcelectricalbaseproperties.fullloadcurrent().
inputfrequency
ifc2x3.ifcelectricalbaseproperties.inputfrequency
Definition at line 31378 of file ifc2x3.py.
Referenced by ifc2x3.ifcelectricalbaseproperties.inputfrequency().
inputphase
ifc2x3.ifcelectricalbaseproperties.inputphase
Definition at line 31383 of file ifc2x3.py.
Referenced by ifc2x3.ifcelectricalbaseproperties.inputphase().
inputvoltage
ifc2x3.ifcelectricalbaseproperties.inputvoltage
Definition at line 31377 of file ifc2x3.py.
Referenced by ifc2x3.ifcelectricalbaseproperties.inputvoltage().
maximumpowerinput
ifc2x3.ifcelectricalbaseproperties.maximumpowerinput
Definition at line 31381 of file ifc2x3.py.
Referenced by ifc2x3.ifcelectricalbaseproperties.maximumpowerinput().
minimumcircuitcurrent
ifc2x3.ifcelectricalbaseproperties.minimumcircuitcurrent
Definition at line 31380 of file ifc2x3.py.
Referenced by ifc2x3.ifcelectricalbaseproperties.minimumcircuitcurrent().
ratedpowerinput
ifc2x3.ifcelectricalbaseproperties.ratedpowerinput
Definition at line 31382 of file ifc2x3.py.
Referenced by ifc2x3.ifcelectricalbaseproperties.ratedpowerinput().
The documentation for this class was generated from the following file:
ifc2x3.py