FreeCAD: AppMatGui.cpp File Reference
AppMatGui.cpp File Reference
#include "PreCompiled.h"
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/PyObjectBase.h>
#include <Gui/Application.h>
#include <Gui/Language/Translator.h>
#include <Gui/WidgetFactory.h>
#include "DlgSettingsDefaultMaterial.h"
#include "DlgSettingsMaterial.h"
#include "Workbench.h"
#include "WorkbenchManipulator.h"
#include "MaterialTreeWidget.h"
#include "MaterialTreeWidgetPy.h"
Classes
class MatGui::Module
Namespaces
MatGui
Functions
void CreateMaterialCommands ()
void loadMaterialResource ()
PyObject * MatGui::initModule ()
PyMOD_INIT_FUNC (MatGui)
Function Documentation
CreateMaterialCommands()
void CreateMaterialCommands ()
Definition at line 194 of file Mod/Material/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
loadMaterialResource()
void loadMaterialResource ()
Definition at line 44 of file AppMatGui.cpp.
References Gui::Translator::instance(), and Gui::Translator::refresh().
Referenced by PyMOD_INIT_FUNC().
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (MatGui)
Definition at line 75 of file AppMatGui.cpp.
References Base::InterpreterSingleton::addType(), Base::Console(), CreateMaterialCommands(), SCL.SimpleDataTypes::e, Base::BaseClass::init(), MatGui::initModule(), Gui::WorkbenchManipulator::installManipulator(), Gui::Application::Instance, Base::Interpreter(), loadMaterialResource(), Base::ConsoleSingleton::Log(), PyMOD_Return, Arch::QT_TRANSLATE_NOOP, Base::InterpreterSingleton::runString(), and Gui::Dialog::DlgPreferencesImp::setGroupData().