FreeCAD: BOPTools.ToleranceFeatures.FeatureToleranceSet Class Reference
BOPTools.ToleranceFeatures.FeatureToleranceSet Class Reference
Public Member Functions
def __init__ (self, obj)
def onDocumentRestored (self, obj)
def execute (self, selfobj)
Public Attributes
Type
Detailed Description
The PartToleranceSetFeature object.
Definition at line 105 of file ToleranceFeatures.py.
Constructor & Destructor Documentation
__init__()
def BOPTools.ToleranceFeatures.FeatureToleranceSet.__init__ (self, obj)
Definition at line 108 of file ToleranceFeatures.py.
References BOPTools.ToleranceFeatures.getParamRefine().
Member Function Documentation
execute()
def BOPTools.ToleranceFeatures.FeatureToleranceSet.execute (self, selfobj)
Definition at line 123 of file ToleranceFeatures.py.
Referenced by src.Mod.PartDesign.Scripts.Spring.MySpring.onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped.onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder.onChanged(), and FeaturePython.DistanceBolt.onChanged().
onDocumentRestored()
def BOPTools.ToleranceFeatures.FeatureToleranceSet.onDocumentRestored (self, obj)
Definition at line 119 of file ToleranceFeatures.py.
Member Data Documentation
Type
BOPTools.ToleranceFeatures.FeatureToleranceSet.Type
Definition at line 117 of file ToleranceFeatures.py.
The documentation for this class was generated from the following file:
ToleranceFeatures.py