FreeCAD: CommandSketcherVirtualSpace.cpp File Reference
CommandSketcherVirtualSpace.cpp File Reference
#include "PreCompiled.h"
#include <cfloat>
#include <App/Application.h>
#include <Base/Console.h>
#include <Gui/Action.h>
#include <Gui/Application.h>
#include <Gui/BitmapFactory.h>
#include <Gui/CommandT.h>
#include <Gui/Document.h>
#include <Gui/MainWindow.h>
#include <Gui/Notifications.h>
#include <Gui/Selection.h>
#include <Gui/SelectionObject.h>
#include "DrawSketchHandler.h"
#include "ViewProviderSketch.h"
#include <Mod/Part/App/Geometry.h>
#include <Mod/Sketcher/App/SketchObject.h>
#include "Utils.h"
Functions
bool isSketcherVirtualSpaceActive (Gui::Document *doc, bool actsOnSelection)
void ActivateVirtualSpaceHandler (Gui::Document *doc, DrawSketchHandler *handler)
void CreateSketcherCommandsVirtualSpace ()
Function Documentation
ActivateVirtualSpaceHandler()
void ActivateVirtualSpaceHandler (Gui::Document * doc, DrawSketchHandler * handler)
Definition at line 73 of file CommandSketcherVirtualSpace.cpp.
References SketcherGui::ViewProviderSketch::activateHandler(), toolbit-attributes::doc, Base::Persistence::getClassTypeId(), buildPsets::handler, Path.Post.scripts.opensbp_post::move(), and SketcherGui::ViewProviderSketch::purgeHandler().
CreateSketcherCommandsVirtualSpace()
void CreateSketcherCommandsVirtualSpace ()
Definition at line 205 of file CommandSketcherVirtualSpace.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
isSketcherVirtualSpaceActive()
bool isSketcherVirtualSpaceActive (Gui::Document * doc, bool actsOnSelection)
Definition at line 53 of file CommandSketcherVirtualSpace.cpp.
References toolbit-attributes::doc, Base::Persistence::getClassTypeId(), SketcherGui::ViewProviderSketch::getSketchMode(), and Gui::Selection().