FreeCAD: PythonStdOutput Class Reference
PythonStdOutput Class Reference
Public Member Functions
PythonStdOutput ()=default
~PythonStdOutput () override=default
Py::Object write (const Py::Tuple &)
Py::Object flush (const Py::Tuple &)
Static Public Member Functions
static void init_type ()
Detailed Description
Definition at line 198 of file Interpreter.cpp.
Constructor & Destructor Documentation
PythonStdOutput()
PythonStdOutput::PythonStdOutput () default
~PythonStdOutput()
PythonStdOutput::~PythonStdOutput () override default
Member Function Documentation
flush()
Py::Object PythonStdOutput::flush (const Py::Tuple &) inline
Definition at line 216 of file Interpreter.cpp.
Referenced by init_type().
init_type()
static void PythonStdOutput::init_type () inline static
Definition at line 201 of file Interpreter.cpp.
References flush(), and write().
Referenced by Base::InterpreterSingleton::init().
write()
Py::Object PythonStdOutput::write (const Py::Tuple &) inline
Definition at line 212 of file Interpreter.cpp.
Referenced by init_type().
The documentation for this class was generated from the following file:
Interpreter.cpp