FreeCAD: SurfaceGui::TaskSections Class Reference
SurfaceGui::TaskSections Class Reference
#include <TaskSections.h>
Public Member Functions
TaskSections (ViewProviderSections *vp, Surface::Sections *obj)
void setEditedObject (Surface::Sections *obj)
void open () override
is called by the framework when the dialog is opened
bool accept () override
is called by the framework if the dialog is accepted (Ok)
bool reject () override
is called by the framework if the dialog is rejected (Cancel)
QDialogButtonBox::StandardButtons getStandardButtons () const override
tells the framework which buttons are wished for the dialog
Public Member Functions inherited from Gui::TaskView::TaskDialog
TaskDialog ()
~TaskDialog () override
QWidget * addTaskBox (QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBox (const QPixmap &icon, QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBoxWithoutHeader (QWidget *widget)
void setButtonPosition (ButtonPosition p)
ButtonPosition buttonPosition () const
const std::vector< QWidget * > & getDialogContent () const
bool canClose () const
virtual void modifyStandardButtons (QDialogButtonBox *)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
bool isEscapeButtonEnabled () const
void setAutoCloseOnTransactionChange (bool on)
bool isAutoCloseOnTransactionChange () const
void setAutoCloseOnDeletedDocument (bool on)
bool isAutoCloseOnDeletedDocument () const
const std::string & getDocumentName () const
void setDocumentName (const std::string &doc)
void setAutoCloseOnClosedView (bool on)
bool isAutoCloseOnClosedView () const
void associateToObject3dView (App::DocumentObject *obj)
const Gui::MDIView * getAssociatedView () const
void setAssociatedView (const Gui::MDIView *view)
virtual bool isAllowedAlterDocument () const
virtual bool isAllowedAlterView () const
virtual bool isAllowedAlterSelection () const
virtual bool needsFullSpace () const
virtual void closed ()
is called by the framework when the dialog is closed
virtual void autoClosedOnTransactionChange ()
virtual void autoClosedOnDeletedDocument ()
virtual void autoClosedOnClosedView ()
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
virtual void helpRequested ()
is called by the framework if the user press the help button
void emitDestructionSignal ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from Gui::TaskView::TaskDialog
QPointer< QDialogButtonBox > buttonBox
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Detailed Description
Definition at line 121 of file TaskSections.h.
Constructor & Destructor Documentation
TaskSections()
SurfaceGui::TaskSections::TaskSections (ViewProviderSections * vp, Surface::Sections * obj)
Definition at line 610 of file TaskSections.cpp.
References Gui::TaskView::TaskDialog::addTaskBox(), and Gui::BitmapFactory().
Member Function Documentation
accept()
bool SurfaceGui::TaskSections::accept () override virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 627 of file TaskSections.cpp.
References SurfaceGui::SectionsPanel::accept(), Gui::Command::commitCommand(), doCommand, Gui::Command::Gui, and Gui::Command::updateActive().
getStandardButtons()
QDialogButtonBox::StandardButtons SurfaceGui::TaskSections::getStandardButtons () const inline override virtual
tells the framework which buttons are wished for the dialog
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 134 of file TaskSections.h.
open()
void SurfaceGui::TaskSections::open () override virtual
is called by the framework when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 622 of file TaskSections.cpp.
References SurfaceGui::SectionsPanel::open().
reject()
bool SurfaceGui::TaskSections::reject () override virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 639 of file TaskSections.cpp.
References Gui::Command::abortCommand(), doCommand, Gui::Command::Gui, SurfaceGui::SectionsPanel::reject(), and Gui::Command::updateActive().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action().
setEditedObject()
void SurfaceGui::TaskSections::setEditedObject (Surface::Sections * obj)
Definition at line 617 of file TaskSections.cpp.
References SurfaceGui::SectionsPanel::setEditedObject().
Referenced by SurfaceGui::ViewProviderSections::setEdit().
The documentation for this class was generated from the following files:
TaskSections.h
TaskSections.cpp