FreeCAD: Wm4::MeshSmoother< Real > Class Template Reference
Wm4::MeshSmoother< Real > Class Template Reference
#include <Wm4MeshSmoother.h>
Public Member Functions
MeshSmoother (int iVQuantity, Vector3< Real > *akVertex, int iTQuantity, const int *aiIndex)
virtual ~MeshSmoother ()
MeshSmoother ()
void Create (int iVQuantity, Vector3< Real > *akVertex, int iTQuantity, const int *aiIndex)
void Destroy ()
int GetVQuantity () const
const Vector3< Real > * GetVertices () const
int GetTQuantity () const
const int * GetIndices () const
const Vector3< Real > * GetNormals () const
const Vector3< Real > * GetMeans () const
void Update (Real fTime=(Real) 0.0)
Protected Member Functions
virtual bool VertexInfluenced (int i, Real fTime)
virtual Real GetTangentWeight (int i, Real fTime)
virtual Real GetNormalWeight (int i, Real fTime)
Protected Attributes
int m_iVQuantity
Vector3< Real > * m_akVertex
int m_iTQuantity
const int * m_aiIndex
Vector3< Real > * m_akNormal
Vector3< Real > * m_akMean
int * m_aiNeighborCount
Detailed Description
template<class Real>
class Wm4::MeshSmoother< Real >
Definition at line 27 of file Wm4MeshSmoother.h.
Constructor & Destructor Documentation
MeshSmoother() [1/2]
template<class Real > Wm4::MeshSmoother< Real >::MeshSmoother (int iVQuantity, Vector3< Real > * akVertex, int iTQuantity, const int * aiIndex)
Definition at line 36 of file Wm4MeshSmoother.cpp.
References Path.Base.Gui.PropertyBag::Create().
~MeshSmoother()
template<class Real > Wm4::MeshSmoother< Real >::~MeshSmoother virtual
Definition at line 49 of file Wm4MeshSmoother.cpp.
References App::Destroy.
MeshSmoother() [2/2]
template<class Real > Wm4::MeshSmoother< Real >::MeshSmoother
Definition at line 24 of file Wm4MeshSmoother.cpp.
Member Function Documentation
Create()
template<class Real > void Wm4::MeshSmoother< Real >::Create (int iVQuantity, Vector3< Real > * akVertex, int iTQuantity, const int * aiIndex)
Definition at line 55 of file Wm4MeshSmoother.cpp.
References App::Destroy, SplineSurface::i, and WM4_NEW.
Destroy()
template<class Real > void Wm4::MeshSmoother< Real >::Destroy
Definition at line 82 of file Wm4MeshSmoother.cpp.
References WM4_DELETE.
GetIndices()
template<class Real > const int * Wm4::MeshSmoother< Real >::GetIndices
Definition at line 179 of file Wm4MeshSmoother.cpp.
GetMeans()
template<class Real > const Vector3< Real > * Wm4::MeshSmoother< Real >::GetMeans
Definition at line 191 of file Wm4MeshSmoother.cpp.
GetNormals()
template<class Real > const Vector3< Real > * Wm4::MeshSmoother< Real >::GetNormals
Definition at line 185 of file Wm4MeshSmoother.cpp.
GetNormalWeight()
template<class Real > Real Wm4::MeshSmoother< Real >::GetNormalWeight (int i, Real fTime) protected virtual
Definition at line 155 of file Wm4MeshSmoother.cpp.
GetTangentWeight()
template<class Real > Real Wm4::MeshSmoother< Real >::GetTangentWeight (int i, Real fTime) protected virtual
Definition at line 149 of file Wm4MeshSmoother.cpp.
GetTQuantity()
template<class Real > int Wm4::MeshSmoother< Real >::GetTQuantity
Definition at line 173 of file Wm4MeshSmoother.cpp.
GetVertices()
template<class Real > const Vector3< Real > * Wm4::MeshSmoother< Real >::GetVertices
Definition at line 167 of file Wm4MeshSmoother.cpp.
GetVQuantity()
template<class Real > int Wm4::MeshSmoother< Real >::GetVQuantity
Definition at line 161 of file Wm4MeshSmoother.cpp.
Update()
template<class Real > void Wm4::MeshSmoother< Real >::Update (Real fTime = (Real)0.0)
Definition at line 90 of file Wm4MeshSmoother.cpp.
References Wm4::Vector3< Real >::Cross(), Wm4::Vector3< Real >::Dot(), SplineSurface::i, and Wm4::Vector3< Real >::Normalize().
VertexInfluenced()
template<class Real > bool Wm4::MeshSmoother< Real >::VertexInfluenced (int i, Real fTime) protected virtual
Definition at line 143 of file Wm4MeshSmoother.cpp.
Member Data Documentation
m_aiIndex
template<class Real > const int* Wm4::MeshSmoother< Real >::m_aiIndex protected
Definition at line 65 of file Wm4MeshSmoother.h.
m_aiNeighborCount
template<class Real > int* Wm4::MeshSmoother< Real >::m_aiNeighborCount protected
Definition at line 69 of file Wm4MeshSmoother.h.
m_akMean
template<class Real > Vector3<Real>* Wm4::MeshSmoother< Real >::m_akMean protected
Definition at line 68 of file Wm4MeshSmoother.h.
m_akNormal
template<class Real > Vector3<Real>* Wm4::MeshSmoother< Real >::m_akNormal protected
Definition at line 67 of file Wm4MeshSmoother.h.
m_akVertex
template<class Real > Vector3<Real>* Wm4::MeshSmoother< Real >::m_akVertex protected
Definition at line 63 of file Wm4MeshSmoother.h.
m_iTQuantity
template<class Real > int Wm4::MeshSmoother< Real >::m_iTQuantity protected
Definition at line 64 of file Wm4MeshSmoother.h.
m_iVQuantity
template<class Real > int Wm4::MeshSmoother< Real >::m_iVQuantity protected
Definition at line 62 of file Wm4MeshSmoother.h.
The documentation for this class was generated from the following files:
Wm4MeshSmoother.h
Wm4MeshSmoother.cpp