FreeCAD: Gui::TranslateManip Class Reference
Gui::TranslateManip Class Reference
#include <SoTextLabel.h>
Public Member Functions
TranslateManip ()
Static Public Member Functions
static void initClass ()
Detailed Description
Definition at line 155 of file SoTextLabel.h.
Constructor & Destructor Documentation
TranslateManip()
TranslateManip::TranslateManip ()
Definition at line 525 of file SoTextLabel.cpp.
Member Function Documentation
initClass()
void TranslateManip::initClass () static
Definition at line 519 of file SoTextLabel.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
The documentation for this class was generated from the following files:
SoTextLabel.h
SoTextLabel.cpp