FreeCAD: Path.Op.Area.ObjectOp Class Reference
Path.Op.Area.ObjectOp Class Reference
Public Member Functions
def opFeatures (self, obj)
def areaOpFeatures (self, obj)
def initOperation (self, obj)
def initAreaOp (self, obj)
def areaOpShapeForDepths (self, obj, job)
def areaOpOnChanged (self, obj, prop)
def opOnChanged (self, obj, prop)
def opOnDocumentRestored (self, obj)
def areaOpOnDocumentRestored (self, obj)
def opSetDefaultValues (self, obj, job)
def areaOpSetDefaultValues (self, obj, job)
def opExecute (self, obj, getsim=False)
def areaOpRetractTool (self, obj)
def areaOpAreaParams (self, obj, isHole)
def areaOpPathParams (self, obj, isHole)
def areaOpShapes (self, obj)
def areaOpUseProjection (self, obj)
Public Attributes
sectionShapes
endVector
leadIn
depthparams
Detailed Description
Base class for all Path.Area based operations.
Provides standard features including debugging properties AreaParams,
PathParams and removalshape, all hidden.
The main reason for existence is to implement the standard interface
to Path.Area so subclasses only have to provide the shapes for the
operations.
Definition at line 53 of file Area.py.
Member Function Documentation
areaOpAreaParams()
def Path.Op.Area.ObjectOp.areaOpAreaParams (self, obj, isHole)
areaOpAreaParams(obj, isHole) ... return operation specific area parameters in a dictionary.
Note that the resulting parameters are stored in the property AreaParams.
Must be overwritten by subclasses.
Definition at line 469 of file Area.py.
areaOpFeatures()
def Path.Op.Area.ObjectOp.areaOpFeatures (self, obj)
areaOpFeatures(obj) ... overwrite to add operation specific features.
Can safely be overwritten by subclasses.
Definition at line 75 of file Area.py.
Referenced by Path.Op.Area.ObjectOp.opFeatures().
areaOpOnChanged()
def Path.Op.Area.ObjectOp.areaOpOnChanged (self, obj, prop)
areaOpOnChanged(obj, porp) ... overwrite to process operation specific changes to properties.
Can safely be overwritten by subclasses.
Definition at line 120 of file Area.py.
areaOpOnDocumentRestored()
def Path.Op.Area.ObjectOp.areaOpOnDocumentRestored (self, obj)
areaOpOnDocumentRestored(obj) ... overwrite to fully restore receiver
Definition at line 163 of file Area.py.
Referenced by Path.Op.Area.ObjectOp.opOnDocumentRestored().
areaOpPathParams()
def Path.Op.Area.ObjectOp.areaOpPathParams (self, obj, isHole)
areaOpPathParams(obj, isHole) ... return operation specific path parameters in a dictionary.
Note that the resulting parameters are stored in the property PathParams.
Must be overwritten by subclasses.
Definition at line 475 of file Area.py.
areaOpRetractTool()
def Path.Op.Area.ObjectOp.areaOpRetractTool (self, obj)
areaOpRetractTool(obj) ... return False to keep the tool at current level between shapes. Default is True.
Definition at line 465 of file Area.py.
areaOpSetDefaultValues()
def Path.Op.Area.ObjectOp.areaOpSetDefaultValues (self, obj, job)
areaOpSetDefaultValues(obj, job) ... overwrite to set initial values of operation specific properties.
Can safely be overwritten by subclasses.
Definition at line 205 of file Area.py.
Referenced by Path.Op.Profile.ObjectProfile.areaOpOnDocumentRestored().
areaOpShapeForDepths()
def Path.Op.Area.ObjectOp.areaOpShapeForDepths (self, obj, job)
areaOpShapeForDepths(obj) ... returns the shape used to make an initial calculation for the depths being used.
The default implementation returns the job's Base.Shape
Definition at line 107 of file Area.py.
areaOpShapes()
def Path.Op.Area.ObjectOp.areaOpShapes (self, obj)
areaOpShapes(obj) ... return all shapes to be processed by Path.Area for this op.
Must be overwritten by subclasses.
Definition at line 481 of file Area.py.
areaOpUseProjection()
def Path.Op.Area.ObjectOp.areaOpUseProjection (self, obj)
areaOpUseProcjection(obj) ... return True if the operation can use procjection, defaults to False.
Can safely be overwritten by subclasses.
Definition at line 486 of file Area.py.
initAreaOp()
def Path.Op.Area.ObjectOp.initAreaOp (self, obj)
initAreaOp(obj) ... overwrite if the receiver class needs initialisation.
Can safely be overwritten by subclasses.
Definition at line 102 of file Area.py.
Referenced by Path.Op.Area.ObjectOp.initOperation().
initOperation()
def Path.Op.Area.ObjectOp.initOperation (self, obj)
initOperation(obj) ... sets up standard Path.Area properties and calls initAreaOp().
Do not overwrite, overwrite initAreaOp(obj) instead.
Definition at line 80 of file Area.py.
References Path.Op.Area.ObjectOp.initAreaOp(), Arch.QT_TRANSLATE_NOOP, and Path.Log.track().
opExecute()
def Path.Op.Area.ObjectOp.opExecute (self, obj, getsim = False)
opExecute(obj, getsim=False) ... implementation of Path.Area ops.
determines the parameters for _buildPathArea().
Do not overwrite, implement
    areaOpAreaParams(obj, isHole) ... op specific area param dictionary
    areaOpPathParams(obj, isHole) ... op specific path param dictionary
    areaOpShapes(obj)             ... the shape for path area to process
    areaOpUseProjection(obj)      ... return true if operation can use projection
instead.
Definition at line 374 of file Area.py.
References Path.Op.Area.ObjectOp.endVector, and Path.Log.track().
Referenced by Path.Op.Base.ObjectOp.execute().
opFeatures()
def Path.Op.Area.ObjectOp.opFeatures (self, obj)
opFeatures(obj) ... returns the base features supported by all Path.Area based operations.
The standard feature list is OR'ed with the return value of areaOpFeatures().
Do not overwrite, implement areaOpFeatures(obj) instead.
Definition at line 61 of file Area.py.
References Path.Op.Area.ObjectOp.areaOpFeatures().
Referenced by Path.Op.Base.ObjectOp.__init__(), Path.Op.Base.ObjectOp.execute(), Path.Op.Base.ObjectOp.onDocumentRestored(), Path.Op.CircularHoleBase.ObjectOp.opExecute(), Path.Op.EngraveBase.ObjectOp.opSetDefaultValues(), Path.Op.Vcarve.ObjectVcarve.opSetDefaultValues(), Path.Op.Base.ObjectOp.setDefaultValues(), and Path.Op.Base.ObjectOp.updateDepths().
opOnChanged()
def Path.Op.Area.ObjectOp.opOnChanged (self, obj, prop)
opOnChanged(obj, prop) ... base implementation of the notification framework - do not overwrite.
The base implementation takes a stab at determining Heights and Depths if the operations's Base
changes.
Do not overwrite, overwrite areaOpOnChanged(obj, prop) instead.
Definition at line 125 of file Area.py.
Referenced by Path.Op.Base.ObjectOp.onChanged().
opOnDocumentRestored()
def Path.Op.Area.ObjectOp.opOnDocumentRestored (self, obj)
Definition at line 148 of file Area.py.
References Path.Op.Area.ObjectOp.areaOpOnDocumentRestored(), Arch.QT_TRANSLATE_NOOP, and Path.Log.track().
Referenced by Path.Op.Base.ObjectOp.onDocumentRestored().
opSetDefaultValues()
def Path.Op.Area.ObjectOp.opSetDefaultValues (self, obj, job)
opSetDefaultValues(obj) ... base implementation, do not overwrite.
The base implementation sets the depths and heights based on the
areaOpShapeForDepths() return value.
Do not overwrite, overwrite areaOpSetDefaultValues(obj, job) instead.
Definition at line 167 of file Area.py.
Referenced by Path.Op.Engrave.ObjectEngrave.opUpdateDepths(), Path.Op.Vcarve.ObjectVcarve.opUpdateDepths(), and Path.Op.Base.ObjectOp.setDefaultValues().
Member Data Documentation
depthparams
Path.Op.Area.ObjectOp.depthparams
Definition at line 390 of file Area.py.
Referenced by Path.Op.Pocket.ObjectPocket.areaOpShapes().
endVector
Path.Op.Area.ObjectOp.endVector
Definition at line 305 of file Area.py.
Referenced by Path.Op.Area.ObjectOp.opExecute().
leadIn
Path.Op.Area.ObjectOp.leadIn
Definition at line 387 of file Area.py.
sectionShapes
Path.Op.Area.ObjectOp.sectionShapes
Definition at line 231 of file Area.py.
The documentation for this class was generated from the following file:
Area.py