FreeCAD: Gui::SoGLWidgetNode Class Reference
Gui::SoGLWidgetNode Class Reference
#include <SoFCInteractiveElement.h>
Public Member Functions
SoGLWidgetNode ()
void doAction (SoAction *action) override
void GLRender (SoGLRenderAction *action) override
Static Public Member Functions
static void initClass ()
Public Attributes
QtGLWidget * window {nullptr}
Protected Member Functions
~SoGLWidgetNode () override
Detailed Description
Definition at line 131 of file SoFCInteractiveElement.h.
Constructor & Destructor Documentation
SoGLWidgetNode()
SoGLWidgetNode::SoGLWidgetNode ()
Constructor.
Definition at line 183 of file SoFCInteractiveElement.cpp.
~SoGLWidgetNode()
SoGLWidgetNode::~SoGLWidgetNode () override protected default
Destructor.
Member Function Documentation
doAction()
void SoGLWidgetNode::doAction (SoAction * action) override
Definition at line 202 of file SoFCInteractiveElement.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and Gui::SoGLWidgetElement::set().
Referenced by GLRender().
GLRender()
void SoGLWidgetNode::GLRender (SoGLRenderAction * action) override
Definition at line 208 of file SoFCInteractiveElement.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
initClass()
void SoGLWidgetNode::initClass () static
Definition at line 194 of file SoFCInteractiveElement.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
Member Data Documentation
window
QtGLWidget* Gui::SoGLWidgetNode::window {nullptr}
Definition at line 140 of file SoFCInteractiveElement.h.
The documentation for this class was generated from the following files:
SoFCInteractiveElement.h
SoFCInteractiveElement.cpp