FreeCAD: Gui::CommandIconView Class Reference
Gui::CommandIconView Class Reference
#include <Widgets.h>
Signals
void emitSelectionChanged (const QString &)
Public Member Functions
CommandIconView (QWidget *parent=nullptr)
~CommandIconView () override
Protected Slots
void onSelectionChanged (QListWidgetItem *item, QListWidgetItem *)
Protected Member Functions
void startDrag (Qt::DropActions supportedActions) override
Detailed Description
This class allows one to drag one or more items which correspond to a Command object. The dragged items can be dropped onto the Gui::PythonConsole.
See also
CommandViewItem, Command
Author
Werner Mayer
Definition at line 61 of file Widgets.h.
Constructor & Destructor Documentation
CommandIconView()
CommandIconView::CommandIconView (QWidget * parent = nullptr)
Constructs an empty command view with parent parent.
Definition at line 66 of file Widgets.cpp.
References draftgeoutils.intersections::connect(), and onSelectionChanged().
~CommandIconView()
CommandIconView::~CommandIconView () override default
Destroys the icon view and deletes all items.
Member Function Documentation
emitSelectionChanged
void Gui::CommandIconView::emitSelectionChanged (const QString &) signal
Emits this signal if selection has changed.
Referenced by onSelectionChanged().
onSelectionChanged
void CommandIconView::onSelectionChanged (QListWidgetItem * item, QListWidgetItem *) protected slot
This slot is called when a new item becomes current. item is the new current item (or 0 if no item is now current). This slot emits the emitSelectionChanged() signal for its part.
Definition at line 111 of file Widgets.cpp.
References emitSelectionChanged().
Referenced by CommandIconView().
startDrag()
void CommandIconView::startDrag (Qt::DropActions supportedActions) override protected
Stores the name of the selected commands for drag and drop.
Definition at line 81 of file Widgets.cpp.
References src.Mod.Test.testPathArray::items.
The documentation for this class was generated from the following files:
Widgets.h
Widgets.cpp