FreeCAD: CommandStack.cpp File Reference
CommandStack.cpp File Reference
#include "PreCompiled.h"
#include <QApplication>
#include <QMessageBox>
#include <App/DocumentObject.h>
#include <Base/Console.h>
#include <Gui/Action.h>
#include <Gui/Application.h>
#include <Gui/BitmapFactory.h>
#include <Gui/Command.h>
#include <Gui/Control.h>
#include <Gui/Document.h>
#include <Gui/MainWindow.h>
#include <Gui/Selection.h>
#include <Gui/ViewProvider.h>
#include <Mod/TechDraw/App/DrawPage.h>
#include <Mod/TechDraw/App/DrawView.h>
#include "DrawGuiUtil.h"
#include "ViewProviderDrawingView.h"
Functions
void execStackTop (Gui::Command *cmd)
void execStackBottom (Gui::Command *cmd)
void execStackUp (Gui::Command *cmd)
void execStackDown (Gui::Command *cmd)
void CreateTechDrawCommandsStack (void)
Function Documentation
CreateTechDrawCommandsStack()
void CreateTechDrawCommandsStack (void)
Definition at line 407 of file CommandStack.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
execStackBottom()
void execStackBottom (Gui::Command * cmd)
Definition at line 266 of file CommandStack.cpp.
References Base::Persistence::getClassTypeId(), Gui::Application::getDocument(), Gui::Command::getDocument(), Gui::SelectionSingleton::getObjectsOfType(), Gui::Command::getSelection(), Gui::Application::Instance, TechDrawGui::ViewProviderDrawingView::stackBottom(), and TestSpreadsheet::v.
execStackDown()
void execStackDown (Gui::Command * cmd)
Definition at line 386 of file CommandStack.cpp.
References Base::Persistence::getClassTypeId(), Gui::Application::getDocument(), Gui::Command::getDocument(), Gui::SelectionSingleton::getObjectsOfType(), Gui::Command::getSelection(), Gui::Application::Instance, TechDrawGui::ViewProviderDrawingView::stackDown(), and TestSpreadsheet::v.
execStackTop()
void execStackTop (Gui::Command * cmd)
Definition at line 206 of file CommandStack.cpp.
References Base::Persistence::getClassTypeId(), Gui::Application::getDocument(), Gui::Command::getDocument(), Gui::SelectionSingleton::getObjectsOfType(), Gui::Command::getSelection(), Gui::Application::Instance, TechDrawGui::ViewProviderDrawingView::stackTop(), and TestSpreadsheet::v.
execStackUp()
void execStackUp (Gui::Command * cmd)
Definition at line 326 of file CommandStack.cpp.
References Base::Persistence::getClassTypeId(), Gui::Application::getDocument(), Gui::Command::getDocument(), Gui::SelectionSingleton::getObjectsOfType(), Gui::Command::getSelection(), Gui::Application::Instance, TechDrawGui::ViewProviderDrawingView::stackUp(), and TestSpreadsheet::v.