FreeCAD: ImpExpDxf.cpp File Reference
ImpExpDxf.cpp File Reference
#include "PreCompiled.h"
#include <Standard_Version.hxx>
#include <BRepAdaptor_HCurve.hxx>
#include <Approx_Curve3d.hxx>
#include <BRepAdaptor_Curve.hxx>
#include <BRepBuilderAPI_MakeEdge.hxx>
#include <BRepBuilderAPI_MakeVertex.hxx>
#include <BRepBuilderAPI_Transform.hxx>
#include <BRep_Builder.hxx>
#include <GCPnts_UniformAbscissa.hxx>
#include <GeomAPI_Interpolate.hxx>
#include <GeomAPI_PointsToBSpline.hxx>
#include <Geom_BSplineCurve.hxx>
#include <TColgp_Array1OfPnt.hxx>
#include <TopExp_Explorer.hxx>
#include <TopoDS.hxx>
#include <TopoDS_Compound.hxx>
#include <TopoDS_Edge.hxx>
#include <TopoDS_Shape.hxx>
#include <TopoDS_Vertex.hxx>
#include <gp_Ax1.hxx>
#include <gp_Ax2.hxx>
#include <gp_Circ.hxx>
#include <gp_Dir.hxx>
#include <gp_Elips.hxx>
#include <gp_Pnt.hxx>
#include <gp_Vec.hxx>
#include <App/Annotation.h>
#include <App/Application.h>
#include <App/Document.h>
#include <App/DocumentObjectPy.h>
#include <App/FeaturePythonPyImp.h>
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/Matrix.h>
#include <Base/Parameter.h>
#include <Base/Vector3D.h>
#include <Base/PlacementPy.h>
#include <Base/VectorPy.h>
#include <Mod/Part/App/PartFeature.h>
#include "ImpExpDxf.h"
Functions
Handle (Geom_BSplineCurve) getSplineFromPolesAndKnots(struct SplineData &sd)
void gPntToTuple (double result[3], gp_Pnt &p)
point3D gPntTopoint3D (gp_Pnt &p)
Function Documentation
gPntTopoint3D()
point3D gPntTopoint3D (gp_Pnt & p)
Definition at line 764 of file ImpExpDxf.cpp.
References buildPsets::p, and result.
Referenced by Import::ImpExpDxfWrite::exportBSpline(), Import::ImpExpDxfWrite::exportLWPoly(), and Import::ImpExpDxfWrite::exportPolyline().
gPntToTuple()
void gPntToTuple (double result[3], gp_Pnt & p)
Definition at line 757 of file ImpExpDxf.cpp.
References buildPsets::p, and result.
Referenced by Import::ImpExpDxfWrite::exportArc(), Import::ImpExpDxfWrite::exportCircle(), Import::ImpExpDxfWrite::exportEllipse(), Import::ImpExpDxfWrite::exportEllipseArc(), Import::ImpExpDxfWrite::exportLine(), and Import::ImpExpDxfWrite::exportShape().
Handle()
Handle (Geom_BSplineCurve) &
Definition at line 270 of file ImpExpDxf.cpp.
References SplineData::control_points, SplineData::controlx, SplineData::controly, SplineData::controlz, src.Mod.AddonManager.NetworkManager::count, SplineData::degree, SplineData::flag, SplineSurface::i, SplineData::knot, and SplineData::weight.
Referenced by Attacher::AttachEngine3D::_calculateAttachedPlacement(), Attacher::AttachEngineLine::_calculateAttachedPlacement(), ReverseEngineeringGui::Segmentation::accept(), TechDraw::DrawUtil::angleWithX(), TechDraw::AOC::AOC(), Drawing::DrawingOutput::asBSpline(), TechDraw::TechDrawOutput::asBSpline(), Drawing::DrawingOutput::asCircle(), TechDraw::TechDrawOutput::asCircle(), TechDraw::GeometryUtils::asCircle(), TechDraw::GeometryUtils::asLine(), TechDraw::BaseGeom::baseFactory(), TechDraw::BezierSegment::BezierSegment(), TechDraw::BSpline::BSpline(), Part::FaceMakerCheese::Build_Essence(), PartDesign::Pipe::buildPipePath(), Surface::ShapeValidator::checkEdge(), PartGui::CircleFromThreePoints::command(), PartGui::ViewProviderCurveNet::computeEdges(), Part::create3dCurve(), Surface::GeomFillSurface::createBezierSurface(), Surface::GeomFillSurface::createBSplineSurface(), Import::ExportOCAF::createNode(), Sketcher::SketchObject::decreaseBSplineDegree(), TechDraw::GeometryUtils::edgeFromCircle(), TechDraw::GeometryUtils::edgeFromCircleArc(), TechDraw::GeometryUtils::edgeLength(), TechDraw::Ellipse::Ellipse(), Drawing::ProjectionAlgos::execute(), TechDraw::ProjectionAlgos::execute(), Surface::Sections::execute(), PartDesign::Pipe::execute(), Surface::Extend::execute(), Surface::FeatureBlendCurve::execute(), Part::Plane::execute(), Import::ImpExpDxfWrite::exportBSpline(), FaceUnwrapper::FaceUnwrapper(), FC_LOG_LEVEL_INIT(), Surface::FeatureBlendCurve::FeatureBlendCurve(), Sketcher::SketchObject::fillet(), FindSHUO(), fitArcs(), TechDraw::Generic::Generic(), Fem::Constraint::getBasePoint(), TechDraw::GeometryUtils::getCircleParms(), Fem::Tools::getCylinderParams(), Fem::Tools::getDirection(), Fem::Constraint::getPoints(), TechDraw::DrawViewDimension::getPointsEdgeVert(), MeshPart::CurveProjectorSimple::GetSampledCurves(), Surface::GeomFillSurface::getWire(), PartGui::TaskCheckGeometryResults::goCheck(), Part::ImportIgesParts(), Part::ImportStepParts(), Sketcher::SketchObject::increaseBSplineDegree(), FaceUnwrapper::interpolateFlatFace(), Part::FaceMakerCheese::isInside(), TechDraw::GeometryUtils::isLine(), Fem::Tools::isLinear(), TechDraw::DrawProjectSplit::isOnEdge(), Fem::Tools::isPlanar(), Sketcher::SketchObject::isSupportedGeometry(), Import::Tools::labelName(), TechDraw::EdgeWalker::makeCleanWire(), TechDraw::DrawViewSection::makeFaceFromWires(), MeshPart::CurveProjectorWithToolMesh::makeToolMesh(), TechDraw::DrawDimHelper::minMax(), TechDraw::DrawDimHelper::minMax3d(), Import::ImpExpDxfRead::OnReadSpline(), MeshPart::CurveProjectorShape::projectCurve(), MeshPart::CurveProjectorSimple::projectCurve(), MeshPart::MeshProjection::projectEdgeToEdge(), Import::SketchExportHelper::projectShape(), TechDraw::GeometryObject::projectShape(), TechDraw::GeometryObject::projectShapeWithPolygonAlgo(), Import::ReaderIges::read(), Import::StepShape::read(), Import::ReaderStep::read(), Sketcher::SketchObject::rebuildExternalGeometry(), Import::ExportOCAF::saveShape(), Part::Part2DObject::seekTrimPoints(), Part::ProgressIndicator::Show(), PartGui::BOPProgressIndicator::Show(), PartGui::ViewProviderSplineExtension::showControlPointsOfEdge(), PartGui::ViewProviderSplineExtension::showControlPointsOfFace(), Part::sort_Edges(), TechDraw::DrawUtil::sort_Edges(), Sketcher::SketchObject::split(), TechDraw::DrawProjectSplit::split1Edge(), PartDesignGui::ViewProviderAddSub::updateAddSubShapeIndicator(), and PartGui::ViewProviderPartExt::updateVisual().