FreeCAD: nativeifc.ifc_layers Namespace Reference
nativeifc.ifc_layers Namespace Reference
Functions
def load_layers (obj)
def has_layers (obj)
def get_layer (layer, project)
def populate_layer (obj)
def add_layers (obj, element=None, ifcfile=None, proj=None)
def add_to_layer (obj, layer)
def create_layer (name, project)
def transfer_layer (layer, project)
Function Documentation
add_layers()
def nativeifc.ifc_layers.add_layers (obj, element = None, ifcfile = None, proj = None)
Creates necessary layers for the given object
Definition at line 87 of file ifc_layers.py.
References nativeifc.ifc_layers.get_layer().
add_to_layer()
def nativeifc.ifc_layers.add_to_layer (obj, layer)
Adds the given object to the given layer
Definition at line 103 of file ifc_layers.py.
create_layer()
def nativeifc.ifc_layers.create_layer (name, project)
Adds a new layer to the given project
Definition at line 134 of file ifc_layers.py.
References nativeifc.ifc_layers.get_layer().
Referenced by nativeifc.ifc_layers.transfer_layer().
get_layer()
def nativeifc.ifc_layers.get_layer (layer, project)
Returns (creates if necessary) a layer object in the given project
Definition at line 53 of file ifc_layers.py.
Referenced by nativeifc.ifc_layers.add_layers(), nativeifc.ifc_layers.create_layer(), and nativeifc.ifc_layers.load_layers().
has_layers()
def nativeifc.ifc_layers.has_layers (obj)
Returns true if the given project has layers
Definition at line 43 of file ifc_layers.py.
load_layers()
def nativeifc.ifc_layers.load_layers (obj)
Loads all the layers of an IFC file
Definition at line 32 of file ifc_layers.py.
References nativeifc.ifc_layers.get_layer(), and nativeifc.ifc_layers.populate_layer().
populate_layer()
def nativeifc.ifc_layers.populate_layer (obj)
Attaches all the possible objects to this layer
Definition at line 73 of file ifc_layers.py.
Referenced by nativeifc.ifc_layers.load_layers().
transfer_layer()
def nativeifc.ifc_layers.transfer_layer (layer, project)
Transfer a non-NativeIFC layer to a project
Definition at line 148 of file ifc_layers.py.
References nativeifc.ifc_layers.create_layer().