FreeCAD: src.Mod.AddonManager.AddonManagerTest.gui.gui_mocks.FakeWorker Class Reference
src.Mod.AddonManager.AddonManagerTest.gui.gui_mocks.FakeWorker Class Reference
Public Member Functions
def __init__ (self)
def work (self)
def stop (self)
Public Attributes
called
should_continue
Detailed Description
Definition at line 117 of file gui_mocks.py.
Constructor & Destructor Documentation
__init__()
def src.Mod.AddonManager.AddonManagerTest.gui.gui_mocks.FakeWorker.__init__ (self)
Definition at line 118 of file gui_mocks.py.
Referenced by draftguitools.gui_subelements.SubelementHighlight.finish().
Member Function Documentation
stop()
def src.Mod.AddonManager.AddonManagerTest.gui.gui_mocks.FakeWorker.stop (self)
Definition at line 126 of file gui_mocks.py.
References src.Mod.AddonManager.AddonManagerTest.gui.gui_mocks.FakeWorker.should_continue.
Referenced by bimcommands.BimPanel.NestTaskPanel.accept(), and bimcommands.BimPanel.NestTaskPanel.reject().
work()
def src.Mod.AddonManager.AddonManagerTest.gui.gui_mocks.FakeWorker.work (self)
Definition at line 122 of file gui_mocks.py.
References src.Mod.AddonManager.AddonManagerTest.gui.gui_mocks.FakeWorker.should_continue.
Member Data Documentation
called
src.Mod.AddonManager.AddonManagerTest.gui.gui_mocks.FakeWorker.called
Definition at line 119 of file gui_mocks.py.
Referenced by src.Mod.AddonManager.AddonManagerTest.gui.test_update_all_gui.CallInterceptor.intercept().
should_continue
src.Mod.AddonManager.AddonManagerTest.gui.gui_mocks.FakeWorker.should_continue
Definition at line 120 of file gui_mocks.py.
Referenced by src.Mod.AddonManager.AddonManagerTest.gui.gui_mocks.FakeWorker.stop(), and src.Mod.AddonManager.AddonManagerTest.gui.gui_mocks.FakeWorker.work().
The documentation for this class was generated from the following file:
gui_mocks.py