FreeCAD: MeshCore::SetOperations Class Reference
MeshCore::SetOperations Class Reference
#include <SetOperations.h>
Public Types
enum OperationType {
Union, Intersect, Difference, Inner,
Outer
}
Public Member Functions
SetOperations (const MeshKernel &cutMesh1, const MeshKernel &cutMesh2, MeshKernel &result, OperationType opType, float minDistanceToPoint=1e-5F)
Construction.
void Do ()
Detailed Description
The MeshAlgorithm class provides algorithms base on meshes.
Definition at line 73 of file SetOperations.h.
Member Enumeration Documentation
OperationType
enum MeshCore::SetOperations::OperationType
Enumerator
Union
Intersect
Difference
Inner
Outer
Definition at line 76 of file SetOperations.h.
Constructor & Destructor Documentation
SetOperations()
SetOperations::SetOperations (const MeshKernel & cutMesh1, const MeshKernel & cutMesh2, MeshKernel & result, OperationType opType, float minDistanceToPoint = 1e-5F)
Construction.
Definition at line 48 of file SetOperations.cpp.
Member Function Documentation
Do()
void SetOperations::Do ()
Cut this mesh with another one. The result is a list of polylines If the distance of the polyline to one of the points is less than minDistanceToPoint the polyline goes direct to the point
Definition at line 60 of file SetOperations.cpp.
References MeshCore::MeshDefinitions::_fMinPointDistance, MeshCore::MeshKernel::Clear(), MeshCore::MeshKernel::CountFacets(), Difference, MeshCore::MeshKernel::GetFacet(), SplineSurface::i, Inner, Intersect, MeshCore::MeshKernel::Merge(), Outer, MeshCore::MeshDefinitions::SetMinPointDistance(), and Union.
Referenced by Mesh::SetOperations::execute(), Mesh::MeshObject::inner(), Mesh::MeshObject::intersect(), Mesh::MeshObject::outer(), Mesh::MeshObject::subtract(), and Mesh::MeshObject::unite().
The documentation for this class was generated from the following files:
SetOperations.h
SetOperations.cpp