FreeCAD: DrawingGui::OrthoViews Class Reference
DrawingGui::OrthoViews Class Reference
#include <TaskOrthoViews.h>
Public Member Functions
OrthoViews (App::Document *, const char *pagename, const char *partname)
~OrthoViews ()
void set_primary (gp_Dir facing, gp_Dir right)
void add_view (int rel_x, int rel_y)
void del_view (int rel_x, int rel_y)
void del_all ()
void set_projection (int proj)
void set_hidden (bool state)
void set_smooth (bool state)
void set_Axo (int rel_x, int rel_y, gp_Dir up, gp_Dir right, bool away=false, int axo=0, bool tri=false)
void set_Axo (int rel_x, int rel_y)
void set_Axo_scale (int rel_x, int rel_y, float axo_scale)
void set_Ortho (int rel_x, int rel_y)
int is_Ortho (int rel_x, int rel_y)
bool get_Axo (int rel_x, int rel_y, int &axo, gp_Dir &up, gp_Dir &right, bool &away, bool &tri, float &axo_scale)
void auto_dims (bool setting)
void set_configs (float configs[5])
void get_configs (float configs[5])
Detailed Description
Definition at line 113 of file TaskOrthoViews.h.
Constructor & Destructor Documentation
OrthoViews()
OrthoViews::OrthoViews (App::Document * doc, const char * pagename, const char * partname)
Definition at line 277 of file TaskOrthoViews.cpp.
References draftgeoutils.faces::bind(), toolbit-attributes::doc, App::GetApplication(), Gui::Application::Instance, DrawingExample::Shape, Gui::Application::showViewProvider(), and App::Application::signalDeleteDocument.
~OrthoViews()
OrthoViews::~OrthoViews ()
Definition at line 315 of file TaskOrthoViews.cpp.
References SplineSurface::i.
Member Function Documentation
add_view()
void OrthoViews::add_view (int rel_x, int rel_y)
Definition at line 651 of file TaskOrthoViews.cpp.
References SplineSurface::i, KDL::max(), KDL::min(), and DrawingGui::orthoview::set_data().
Referenced by DrawingGui::TaskOrthoViews::cb_toggled().
auto_dims()
void OrthoViews::auto_dims (bool setting)
Definition at line 893 of file TaskOrthoViews.cpp.
Referenced by DrawingGui::TaskOrthoViews::toggle_auto().
del_all()
void OrthoViews::del_all ()
Definition at line 711 of file TaskOrthoViews.cpp.
References SplineSurface::i.
Referenced by DrawingGui::TaskOrthoViews::clean_up().
del_view()
void OrthoViews::del_view (int rel_x, int rel_y)
Definition at line 681 of file TaskOrthoViews.cpp.
References SplineSurface::i, KDL::max(), and KDL::min().
Referenced by DrawingGui::TaskOrthoViews::cb_toggled().
get_Axo()
bool OrthoViews::get_Axo (int rel_x, int rel_y, int & axo, gp_Dir & up, gp_Dir & right, bool & away, bool & tri, float & axo_scale)
Definition at line 868 of file TaskOrthoViews.cpp.
get_configs()
void OrthoViews::get_configs (float configs[5])
Definition at line 913 of file TaskOrthoViews.cpp.
References draftfunctions.scale::scale().
is_Ortho()
int OrthoViews::is_Ortho (int rel_x, int rel_y)
Definition at line 722 of file TaskOrthoViews.cpp.
References result.
Referenced by DrawingGui::TaskOrthoViews::cb_toggled(), and DrawingGui::TaskOrthoViews::ShowContextMenu().
set_Axo() [1/2]
void OrthoViews::set_Axo (int rel_x, int rel_y)
Definition at line 815 of file TaskOrthoViews.cpp.
set_Axo() [2/2]
void OrthoViews::set_Axo (int rel_x, int rel_y, gp_Dir up, gp_Dir right, bool away = false, int axo = 0, bool tri = false)
Definition at line 761 of file TaskOrthoViews.cpp.
References M_PI.
Referenced by DrawingGui::TaskOrthoViews::change_axo(), and DrawingGui::TaskOrthoViews::ShowContextMenu().
set_Axo_scale()
void OrthoViews::set_Axo_scale (int rel_x, int rel_y, float axo_scale)
Definition at line 747 of file TaskOrthoViews.cpp.
Referenced by DrawingGui::TaskOrthoViews::axo_scale().
set_configs()
void OrthoViews::set_configs (float configs[5])
Definition at line 901 of file TaskOrthoViews.cpp.
Referenced by DrawingGui::TaskOrthoViews::data_entered().
set_hidden()
void OrthoViews::set_hidden (bool state)
Definition at line 555 of file TaskOrthoViews.cpp.
References SplineSurface::i.
Referenced by DrawingGui::TaskOrthoViews::hidden().
set_Ortho()
void OrthoViews::set_Ortho (int rel_x, int rel_y)
Definition at line 853 of file TaskOrthoViews.cpp.
Referenced by DrawingGui::TaskOrthoViews::ShowContextMenu().
set_primary()
void OrthoViews::set_primary (gp_Dir facing, gp_Dir right)
Definition at line 577 of file TaskOrthoViews.cpp.
References KDL::abs().
Referenced by DrawingGui::TaskOrthoViews::setPrimary(), and DrawingGui::TaskOrthoViews::TaskOrthoViews().
set_projection()
void OrthoViews::set_projection (int proj)
Definition at line 638 of file TaskOrthoViews.cpp.
Referenced by DrawingGui::TaskOrthoViews::projectionChanged().
set_smooth()
void OrthoViews::set_smooth (bool state)
Definition at line 566 of file TaskOrthoViews.cpp.
References SplineSurface::i.
Referenced by DrawingGui::TaskOrthoViews::smooth().
The documentation for this class was generated from the following files:
TaskOrthoViews.h
TaskOrthoViews.cpp