FreeCAD: CommandFilter.cpp File Reference
CommandFilter.cpp File Reference
#include "PreCompiled.h"
#include <QAction>
#include <QApplication>
#include <Gui/Action.h>
#include <Gui/BitmapFactory.h>
#include <Gui/Command.h>
#include <Gui/MainWindow.h>
#include <Gui/View3DInventor.h>
Functions
void CreatePartSelectCommands ()
Function Documentation
CreatePartSelectCommands()
void CreatePartSelectCommands ()
Definition at line 263 of file CommandFilter.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().