FreeCAD: Path.Main.Gui.SimulatorGL Namespace Reference
Path.Main.Gui.SimulatorGL Namespace Reference
Classes
class CAMSimTaskUi
class CAMSimulation
class CommandCAMSimulate
Functions
def IsSame (x, y)
def RadiusAt (edge, p)
def TSError (msg)
Variables
Mesh
Part
Function Documentation
IsSame()
def Path.Main.Gui.SimulatorGL.IsSame (x, y)
Check if two floats are the same within an epsilon
Definition at line 53 of file SimulatorGL.py.
References KDL.abs().
Referenced by Path.Main.Gui.SimulatorGL.CAMSimulation.FindClosestEdge(), and Path.Main.Gui.SimulatorGL.CAMSimulation.GetToolProfile().
RadiusAt()
def Path.Main.Gui.SimulatorGL.RadiusAt (edge, p)
Find the tool radius within a point on its circumference
Definition at line 58 of file SimulatorGL.py.
Referenced by Path.Main.Gui.SimulatorGL.CAMSimulation.FindClosestEdge(), and Path.Main.Gui.SimulatorGL.CAMSimulation.GetToolProfile().
TSError()
def Path.Main.Gui.SimulatorGL.TSError (msg)
Display error message
Definition at line 83 of file SimulatorGL.py.
Variable Documentation
Mesh
Path.Main.Gui.SimulatorGL.Mesh
Definition at line 42 of file SimulatorGL.py.
Part
Path.Main.Gui.SimulatorGL.Part
Definition at line 43 of file SimulatorGL.py.