FreeCAD: ReverseEngineeringGui::Segmentation Class Reference
ReverseEngineeringGui::Segmentation Class Reference
#include <Segmentation.h>
Public Member Functions
Segmentation (Mesh::Feature *mesh, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~Segmentation () override
void accept ()
Protected Member Functions
void changeEvent (QEvent *e) override
Detailed Description
Definition at line 44 of file ReverseEngineering/Gui/Segmentation.h.
Constructor & Destructor Documentation
Segmentation()
Segmentation::Segmentation (Mesh::Feature * mesh, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Definition at line 56 of file ReverseEngineering/Gui/Segmentation.cpp.
~Segmentation()
Segmentation::~Segmentation () override default
Member Function Documentation
accept()
void Segmentation::accept ()
Definition at line 70 of file ReverseEngineering/Gui/Segmentation.cpp.
References App::Document::addObject(), MeshCore::Approximation::AddPoints(), App::Document::commitTransaction(), MeshCore::MeshCurvature::ComputePerVertex(), Base::Console(), Base::ConsoleSingleton::Error(), App::DocumentObjectWeakPtrT::expired(), MeshCore::MeshSegmentAlgorithm::FindSegments(), Mesh::PropertyMeshKernel::finishEditing(), MeshCore::PlaneFit::Fit(), FLOAT_MAX, App::DocumentObjectWeakPtrT::get(), App::Application::getActiveDocument(), App::GetApplication(), MeshCore::PlaneFit::GetBase(), MeshCore::MeshCurvature::GetCurvature(), MeshCore::MeshAlgorithm::GetFacetBorders(), MeshCore::MeshKernel::GetFacetPoints(), MeshCore::MeshAlgorithm::GetFacetsFlag(), App::DocumentObject::getNameInDocument(), MeshCore::PlaneFit::GetNormal(), MeshCore::MeshKernel::GetPoints(), App::PropertyString::getValue(), toolbit-attributes::group, App::GroupExtension::Group, Handle(), draftgeoutils.geometry::isPlanar, App::DocumentObject::Label, NavigationIndicatorGui::label, Part::FaceMakerCheese::makeFace(), Mesh2Shape::mesh, Mesh::Feature::Mesh, App::Document::openTransaction(), MeshCore::MeshAlgorithm::ResetFacetsFlag(), MeshCore::MeshAlgorithm::SetFacetFlag(), Part::PropertyPartShape::setValue(), App::PropertyString::setValue(), App::PropertyLinkList::setValues(), Part::Feature::Shape, MeshCore::LaplaceSmoothing::Smooth(), Mesh::PropertyMeshKernel::startEditing(), Mesh::MeshObject::swap(), MeshCore::MeshFacet::TMP0, TestSpreadsheet::v, Base::ConsoleSingleton::Warning(), and Mesh2Shape::wires.
Referenced by ReverseEngineeringGui::TaskSegmentation::accept().
changeEvent()
void Segmentation::changeEvent (QEvent * e) override protected
Definition at line 260 of file ReverseEngineering/Gui/Segmentation.cpp.
References SCL.SimpleDataTypes::e.
The documentation for this class was generated from the following files:
ReverseEngineering/Gui/Segmentation.h
ReverseEngineering/Gui/Segmentation.cpp