FreeCAD: SCL.SimpleReader.SimpleParser Class Reference
SCL.SimpleReader.SimpleParser Class Reference
Public Member Functions
def __init__ (self, filename)
def writeGraphViz (self, fileName)
def instantiate (self)
Public Attributes
schemaModule
schemaClasses
instanceMape
Detailed Description
read the file
Part21.Part21Parser Loads all instances definition of a Part21 file into memory.
Two dicts are created:
Part21.Part21Parser._instance_definition : stores attributes, key is the instance integer id
Part21.Part21Parser._number_of_ancestors : stores the number of ancestors of entity id. This enables
to define the order of instances creation.
Definition at line 47 of file SimpleReader.py.
Constructor & Destructor Documentation
__init__()
def SCL.SimpleReader.SimpleParser.__init__ (self, filename)
Definition at line 57 of file SimpleReader.py.
References SCL.SimpleReader.SimpleParser._p21loader.
Member Function Documentation
instantiate()
def SCL.SimpleReader.SimpleParser.instantiate (self)
Instantiate the python class from the entities
Definition at line 102 of file SimpleReader.py.
References SCL.SimpleReader.SimpleParser._create_entity_instance(), SCL.SimpleReader.SimpleParser._p21loader, SCL.SimpleReader.SimpleParser._transformAttributes(), Path.Base.SetupSheet.dict, SCL.SimpleReader.SimpleParser.instanceMape, SCL.SimpleReader.SimpleParser.schemaClasses, SCL.SimpleReader.SimpleParser.schemaModule, and Path.Post.scripts.refactored_centroid_post.str.
writeGraphViz()
def SCL.SimpleReader.SimpleParser.writeGraphViz (self, fileName)
Definition at line 78 of file SimpleReader.py.
References SCL.SimpleReader.SimpleParser._p21loader, SCL.SimpleReader.SimpleParser._writeGraphVizEdge(), and AssemblyImport.open().
Member Data Documentation
instanceMape
SCL.SimpleReader.SimpleParser.instanceMape
Definition at line 65 of file SimpleReader.py.
Referenced by SCL.SimpleReader.SimpleParser.instantiate().
schemaClasses
SCL.SimpleReader.SimpleParser.schemaClasses
Definition at line 64 of file SimpleReader.py.
Referenced by SCL.SimpleReader.SimpleParser.instantiate().
schemaModule
SCL.SimpleReader.SimpleParser.schemaModule
Definition at line 63 of file SimpleReader.py.
Referenced by SCL.SimpleReader.SimpleParser.instantiate().
The documentation for this class was generated from the following file:
SimpleReader.py