FreeCAD: Part::Geom2dLine Class Reference
Part::Geom2dLine Class Reference
#include <Geometry2d.h>
Public Member Functions
Geom2dLine ()
Geom2dLine (const Handle(Geom2d_Line)&)
Geom2dLine (const Base::Vector2d &Pos, const Base::Vector2d &Dir)
~Geom2dLine () override
Geometry2d * clone () const override
returns a cloned object
void setLine (const Base::Vector2d &Pos, const Base::Vector2d &Dir)
Base::Vector2d getPos () const
Base::Vector2d getDir () const
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
PyObject * getPyObject () override
const Handle (Geom2d_Geometry) &handle() const override
Public Member Functions inherited from Part::Geom2dCurve
Geom2dCurve ()
~Geom2dCurve () override
TopoDS_Shape toShape () const override
bool tangent (double u, gp_Dir2d &) const
Base::Vector2d pointAtParameter (double u) const
Base::Vector2d firstDerivativeAtParameter (double u) const
Base::Vector2d secondDerivativeAtParameter (double u) const
bool normal (double u, gp_Dir2d &dir) const
bool closestParameter (const Base::Vector2d &point, double &u) const
bool closestParameterToBasicCurve (const Base::Vector2d &point, double &u) const
Public Member Functions inherited from Part::Geometry2d
~Geometry2d () override
Geometry2d (const Geometry2d &)=delete
Geometry2d & operator= (const Geometry2d &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions inherited from Part::Geometry2d
Geometry2d ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 490 of file Geometry2d.h.
Constructor & Destructor Documentation
Geom2dLine() [1/3]
Geom2dLine::Geom2dLine ()
Definition at line 1869 of file Geometry2d.cpp.
References SCL.SimpleDataTypes::c, and Handle().
Geom2dLine() [2/3]
Geom2dLine::Geom2dLine (const Handle(Geom2d_Line)& l)
Definition at line 1875 of file Geometry2d.cpp.
References Handle(), and RobotExample::l.
Geom2dLine() [3/3]
Geom2dLine::Geom2dLine (const Base::Vector2d & Pos, const Base::Vector2d & Dir)
Definition at line 1880 of file Geometry2d.cpp.
References Base::Vector2d::x, and Base::Vector2d::y.
~Geom2dLine()
Geom2dLine::~Geom2dLine () override default
Member Function Documentation
clone()
Geometry2d* Part::Geom2dLine::clone () const override virtual
returns a cloned object
Implements Part::Geometry2d.
Referenced by src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated().
getDir()
Base::Vector2d Geom2dLine::getDir () const
Definition at line 1899 of file Geometry2d.cpp.
getMemSize()
unsigned int Part::Geom2dLine::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Reimplemented from Part::Geometry2d.
getPos()
Base::Vector2d Geom2dLine::getPos () const
Definition at line 1893 of file Geometry2d.cpp.
getPyObject()
PyObject * Geom2dLine::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 1967 of file Geometry2d.cpp.
References draftmake.make_clone::clone.
Handle()
const Part::Geom2dLine::Handle (Geom2d_Geometry) const & override virtual
Implements Part::Geometry2d.
Restore()
void Part::Geom2dLine::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from Part::Geometry2d.
Save()
void Part::Geom2dLine::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Reimplemented from Part::Geometry2d.
setLine()
void Geom2dLine::setLine (const Base::Vector2d & Pos, const Base::Vector2d & Dir)
Definition at line 1887 of file Geometry2d.cpp.
References Base::Vector2d::x, and Base::Vector2d::y.
The documentation for this class was generated from the following files:
Geometry2d.h
Geometry2d.cpp