FreeCAD: PartGui::DlgRevolution Class Reference
PartGui::DlgRevolution Class Reference
#include <DlgRevolution.h>
Classes
class EdgeSelection
Public Member Functions
DlgRevolution (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgRevolution () override
void accept () override
Base::Vector3d getDirection () const
Base::Vector3d getPosition () const
void getAxisLink (App::PropertyLinkSub &lnk) const
double getAngle () const
void setDirection (Base::Vector3d dir)
void setPosition (Base::Vector3d dir)
void setAxisLink (const App::PropertyLinkSub &lnk)
void setAxisLink (const char *objname, const char *subname)
std::vector< App::DocumentObject * > getShapesToRevolve () const
bool validate ()
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Protected Member Functions
void changeEvent (QEvent *e) override
void keyPressEvent (QKeyEvent *) override
Detailed Description
Definition at line 55 of file DlgRevolution.h.
Constructor & Destructor Documentation
DlgRevolution()
DlgRevolution::DlgRevolution (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Definition at line 97 of file DlgRevolution.cpp.
References Base::Unit::Angle, Gui::ItemViewSelection::applyFrom(), draftgeoutils.intersections::connect(), Base::Persistence::getClassTypeId(), draftutils.utils::getObjectsOfType, Base::Unit::Length, and Gui::Selection().
~DlgRevolution()
DlgRevolution::~DlgRevolution () override
Definition at line 137 of file DlgRevolution.cpp.
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Member Function Documentation
accept()
void DlgRevolution::accept () override
Definition at line 368 of file DlgRevolution.cpp.
References Gui::Command::App, App::Document::commitTransaction(), copyVisual, App::Application::getActiveDocument(), getAngle(), App::GetApplication(), getAxisLink(), getDirection(), App::DocumentObject::getNameInDocument(), getPosition(), App::PropertyLinkSub::getSubValues(), App::Document::getUniqueObjectName(), App::PropertyLinkSub::getValue(), src.Mod.Test.testPathArray::items, App::Document::openTransaction(), RobotExample::pos, App::Document::recompute(), runCommand, src.Mod.AddonManager.Addon::translate, Path.Post.scripts.grbl_post::type, validate(), Base::Exception::what(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by PartGui::TaskRevolution::accept().
changeEvent()
void DlgRevolution::changeEvent (QEvent * e) override protected
Definition at line 320 of file DlgRevolution.cpp.
References SCL.SimpleDataTypes::e.
getAngle()
double DlgRevolution::getAngle () const
Definition at line 199 of file DlgRevolution.cpp.
References Base::Quantity::Degree.
Referenced by accept(), and validate().
getAxisLink()
void DlgRevolution::getAxisLink (App::PropertyLinkSub & lnk) const
Definition at line 175 of file DlgRevolution.cpp.
References App::Application::getActiveDocument(), App::GetApplication(), App::Document::getObject(), App::PropertyLinkSub::setValue(), and importers.importIFCmulticore::subs.
Referenced by accept(), and validate().
getDirection()
Base::Vector3d DlgRevolution::getDirection () const
Definition at line 159 of file DlgRevolution.cpp.
Referenced by accept(), and validate().
getPosition()
Base::Vector3d DlgRevolution::getPosition () const
Definition at line 167 of file DlgRevolution.cpp.
References Base::Quantity::MilliMetre.
Referenced by accept().
getShapesToRevolve()
std::vector< App::DocumentObject * > DlgRevolution::getShapesToRevolve () const
Definition at line 244 of file DlgRevolution.cpp.
References toolbit-attributes::doc, App::Application::getActiveDocument(), App::GetApplication(), src.Mod.Test.testPathArray::items, and importers.importIFCmulticore::objects.
keyPressEvent()
void DlgRevolution::keyPressEvent (QKeyEvent * ke) override protected
Definition at line 330 of file DlgRevolution.cpp.
setAxisLink() [1/2]
void DlgRevolution::setAxisLink (const App::PropertyLinkSub & lnk)
Definition at line 218 of file DlgRevolution.cpp.
References App::DocumentObject::getNameInDocument(), App::PropertyLinkSub::getSubValues(), and App::PropertyLinkSub::getValue().
setAxisLink() [2/2]
void DlgRevolution::setAxisLink (const char * objname, const char * subname)
Definition at line 231 of file DlgRevolution.cpp.
References create_qrc::txt.
setDirection()
void DlgRevolution::setDirection (Base::Vector3d dir)
Definition at line 204 of file DlgRevolution.cpp.
References Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
setPosition()
void DlgRevolution::setPosition (Base::Vector3d dir)
Definition at line 211 of file DlgRevolution.cpp.
References RobotExample::pos.
validate()
bool DlgRevolution::validate ()
Definition at line 261 of file DlgRevolution.cpp.
References exportCSG::center(), Part::Revolution::fetchAxisLink(), getAngle(), getAxisLink(), getDirection(), FreeCADInit::Length, M_PI, src.Mod.AddonManager.Addon::translate, and Base::Exception::what().
Referenced by accept().
The documentation for this class was generated from the following files:
DlgRevolution.h
DlgRevolution.cpp