FreeCAD: NaviCube Class Reference
NaviCube Class Reference
#include <NaviCube.h>
Public Types
enum Corner { TopLeftCorner, TopRightCorner, BottomLeftCorner, BottomRightCorner }
Public Member Functions
NaviCube (Gui::View3DInventorViewer *viewer)
virtual ~NaviCube ()
void drawNaviCube ()
void createContextMenu (const std::vector< std::string > &cmd)
bool processSoEvent (const SoEvent *ev)
void setCorner (Corner)
void setOffset (int x, int y)
bool isDraggable ()
void setDraggable (bool draggable)
void setSize (int size)
void setChamfer (float size)
void setNaviRotateToNearest (bool toNearest)
void setNaviStepByTurn (int steps)
void setFont (std::string font)
void setFontWeight (int weight)
void setFontStretch (int stretch)
void setFontZoom (float zoom)
void setBaseColor (QColor TextColor)
void setEmphaseColor (QColor ButtonColor)
void setHiliteColor (QColor HiliteColor)
void setBorderWidth (double BorderWidth)
void setShowCS (bool showCS)
void setInactiveOpacity (float opacity)
void setNaviCubeLabels (const std::vector< std::string > &labels)
Static Public Member Functions
static void setNaviCubeCommands (const std::vector< std::string > &cmd)
static int getNaviCubeSize ()
Detailed Description
Definition at line 38 of file NaviCube.h.
Member Enumeration Documentation
Corner
enum NaviCube::Corner
Enumerator
TopLeftCorner
TopRightCorner
BottomLeftCorner
BottomRightCorner
Definition at line 40 of file NaviCube.h.
Constructor & Destructor Documentation
NaviCube()
NaviCube::NaviCube (Gui::View3DInventorViewer * viewer)
Definition at line 213 of file NaviCube.cpp.
References OfflineRenderingUtils::viewer().
~NaviCube()
NaviCube::~NaviCube () virtual
Definition at line 217 of file NaviCube.cpp.
Member Function Documentation
createContextMenu()
void NaviCube::createContextMenu (const std::vector< std::string > & cmd)
Definition at line 225 of file NaviCube.cpp.
drawNaviCube()
void NaviCube::drawNaviCube ()
Definition at line 221 of file NaviCube.cpp.
Referenced by Gui::View3DInventorViewer::renderFramebuffer(), Gui::View3DInventorViewer::renderGLImage(), and Gui::View3DInventorViewer::renderScene().
getNaviCubeSize()
int NaviCube::getNaviCubeSize () static
Definition at line 208 of file NaviCube.cpp.
References NaviCubeImplementation::m_CubeWidgetSize.
Referenced by Gui::OverlayManager::Private::onTimer().
isDraggable()
bool NaviCube::isDraggable ()
Definition at line 244 of file NaviCube.cpp.
processSoEvent()
bool NaviCube::processSoEvent (const SoEvent * ev)
Definition at line 229 of file NaviCube.cpp.
Referenced by Gui::View3DInventorViewer::processSoEvent().
setBaseColor()
void NaviCube::setBaseColor (QColor TextColor)
Definition at line 297 of file NaviCube.cpp.
setBorderWidth()
void NaviCube::setBorderWidth (double BorderWidth)
Definition at line 313 of file NaviCube.cpp.
setChamfer()
void NaviCube::setChamfer (float size)
Definition at line 257 of file NaviCube.cpp.
References SCL.SimpleDataTypes::f, KDL::max(), and KDL::min().
setCorner()
void NaviCube::setCorner (Corner c)
Definition at line 235 of file NaviCube.cpp.
References SCL.SimpleDataTypes::c.
Referenced by Gui::View3DInventorViewer::setNaviCubeCorner().
setDraggable()
void NaviCube::setDraggable (bool draggable)
Definition at line 248 of file NaviCube.cpp.
setEmphaseColor()
void NaviCube::setEmphaseColor (QColor ButtonColor)
Definition at line 302 of file NaviCube.cpp.
References eColor.
setFont()
void NaviCube::setFont (std::string font)
Definition at line 273 of file NaviCube.cpp.
setFontStretch()
void NaviCube::setFontStretch (int stretch)
Definition at line 285 of file NaviCube.cpp.
References Part::stretch.
setFontWeight()
void NaviCube::setFontWeight (int weight)
Definition at line 279 of file NaviCube.cpp.
setFontZoom()
void NaviCube::setFontZoom (float zoom)
Definition at line 291 of file NaviCube.cpp.
setHiliteColor()
void NaviCube::setHiliteColor (QColor HiliteColor)
Definition at line 308 of file NaviCube.cpp.
setInactiveOpacity()
void NaviCube::setInactiveOpacity (float opacity)
Definition at line 328 of file NaviCube.cpp.
setNaviCubeCommands()
void NaviCube::setNaviCubeCommands (const std::vector< std::string > & cmd) static
Definition at line 1170 of file NaviCube.cpp.
References NaviCubeImplementation::m_commands.
setNaviCubeLabels()
void NaviCube::setNaviCubeLabels (const std::vector< std::string > & labels)
Definition at line 323 of file NaviCube.cpp.
References App::ExpressionParser::labels.
setNaviRotateToNearest()
void NaviCube::setNaviRotateToNearest (bool toNearest)
Definition at line 263 of file NaviCube.cpp.
setNaviStepByTurn()
void NaviCube::setNaviStepByTurn (int steps)
Definition at line 268 of file NaviCube.cpp.
setOffset()
void NaviCube::setOffset (int x, int y)
Definition at line 239 of file NaviCube.cpp.
References MovieTool::x, and MovieTool::y.
Referenced by ArchPipe._ArchPipeConnector::execute().
setShowCS()
void NaviCube::setShowCS (bool showCS)
Definition at line 318 of file NaviCube.cpp.
setSize()
void NaviCube::setSize (int size)
Definition at line 252 of file NaviCube.cpp.
The documentation for this class was generated from the following files:
NaviCube.h
NaviCube.cpp