FreeCAD: MeshCore::MeshDistancePlanarSegment Class Reference
MeshCore::MeshDistancePlanarSegment Class Reference
#include <Segmentation.h>
Public Member Functions
MeshDistancePlanarSegment (const MeshKernel &mesh, unsigned long minFacets, float tol)
~MeshDistancePlanarSegment () override
MeshDistancePlanarSegment (const MeshDistancePlanarSegment &)=delete
MeshDistancePlanarSegment (MeshDistancePlanarSegment &&)=delete
MeshDistancePlanarSegment & operator= (const MeshDistancePlanarSegment &)=delete
MeshDistancePlanarSegment & operator= (MeshDistancePlanarSegment &&)=delete
bool TestFacet (const MeshFacet &face) const override
const char * GetType () const override
void Initialize (FacetIndex) override
void AddFacet (const MeshFacet &face) override
Public Member Functions inherited from MeshCore::MeshDistanceSurfaceSegment
MeshDistanceSurfaceSegment (const MeshKernel &mesh, unsigned long minFacets, float tol)
Public Member Functions inherited from MeshCore::MeshSurfaceSegment
MeshSurfaceSegment (unsigned long minFacets)
virtual ~MeshSurfaceSegment ()=default
MeshSurfaceSegment (const MeshSurfaceSegment &)=delete
MeshSurfaceSegment (MeshSurfaceSegment &&)=delete
MeshSurfaceSegment & operator= (const MeshSurfaceSegment &)=delete
MeshSurfaceSegment & operator= (MeshSurfaceSegment &&)=delete
virtual bool TestInitialFacet (FacetIndex) const
void AddSegment (const std::vector< FacetIndex > &)
const std::vector< MeshSegment > & GetSegments () const
MeshSegment FindSegment (FacetIndex) const
Additional Inherited Members
Protected Attributes inherited from MeshCore::MeshDistanceSurfaceSegment
const MeshKernel & kernel
float tolerance
Detailed Description
Definition at line 112 of file Mesh/App/Core/Segmentation.h.
Constructor & Destructor Documentation
MeshDistancePlanarSegment() [1/3]
MeshDistancePlanarSegment::MeshDistancePlanarSegment (const MeshKernel & mesh, unsigned long minFacets, float tol)
Definition at line 66 of file Mesh/App/Core/Segmentation.cpp.
~MeshDistancePlanarSegment()
MeshDistancePlanarSegment::~MeshDistancePlanarSegment () override
Definition at line 73 of file Mesh/App/Core/Segmentation.cpp.
MeshDistancePlanarSegment() [2/3]
MeshCore::MeshDistancePlanarSegment::MeshDistancePlanarSegment (const MeshDistancePlanarSegment &) delete
MeshDistancePlanarSegment() [3/3]
MeshCore::MeshDistancePlanarSegment::MeshDistancePlanarSegment (MeshDistancePlanarSegment &&) delete
Member Function Documentation
AddFacet()
void MeshDistancePlanarSegment::AddFacet (const MeshFacet & face) override virtual
Reimplemented from MeshCore::MeshSurfaceSegment.
Definition at line 105 of file Mesh/App/Core/Segmentation.cpp.
References MeshCore::Approximation::AddPoint(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshGeomFacet::GetGravityPoint(), and MeshCore::MeshDistanceSurfaceSegment::kernel.
GetType()
const char* MeshCore::MeshDistancePlanarSegment::GetType () const inline override virtual
Implements MeshCore::MeshSurfaceSegment.
Definition at line 124 of file Mesh/App/Core/Segmentation.h.
Initialize()
void MeshDistancePlanarSegment::Initialize (FacetIndex index) override virtual
Reimplemented from MeshCore::MeshSurfaceSegment.
Definition at line 78 of file Mesh/App/Core/Segmentation.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::Approximation::AddPoint(), MeshCore::Approximation::Clear(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshGeomFacet::GetGravityPoint(), MeshCore::MeshGeomFacet::GetNormal(), and MeshCore::MeshDistanceSurfaceSegment::kernel.
operator=() [1/2]
MeshDistancePlanarSegment& MeshCore::MeshDistancePlanarSegment::operator= (const MeshDistancePlanarSegment &) delete
operator=() [2/2]
MeshDistancePlanarSegment& MeshCore::MeshDistancePlanarSegment::operator= (MeshDistancePlanarSegment &&) delete
TestFacet()
bool MeshDistancePlanarSegment::TestFacet (const MeshFacet & face) const override virtual
Implements MeshCore::MeshSurfaceSegment.
Definition at line 90 of file Mesh/App/Core/Segmentation.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::Approximation::Done(), MeshCore::PlaneFit::Fit(), MeshCore::PlaneFit::GetDistanceToPlane(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshDistanceSurfaceSegment::kernel, and MeshCore::MeshDistanceSurfaceSegment::tolerance.
The documentation for this class was generated from the following files:
Mesh/App/Core/Segmentation.h
Mesh/App/Core/Segmentation.cpp