FreeCAD: Path::Area Class Reference
Path::Area Class Reference
#include <Area.h>
Classes
struct Shape
Public Member Functions
BOOST_PP_SEQ_FOR_EACH (PARAM_TYPED_FOREACH_, PARAM_ENUM_DECLARE_, AREA_PARAMS_ALL) explicit Area(const AreaParams *params
Area (const Area &other, bool deep_copy=true)
~Area () override
bool isBuilt () const
void setPlane (const TopoDS_Shape &shape)
TopoDS_Shape getPlane (gp_Trsf *trsf=nullptr)
void add (const TopoDS_Shape &shape, BOOST_PP_SEQ_FOR_EACH_I(PARAM_ARGS_DEF_, PARAM_FARG, AREA_PARAMS_OPCODE)))
TopoDS_Shape makeOffset (int index=-1, BOOST_PP_SEQ_FOR_EACH_I(PARAM_ARGS_DEF_, PARAM_FARG, AREA_PARAMS_OFFSET),, int reoirent=0, bool from_center=false)
TopoDS_Shape makePocket (int index=-1, BOOST_PP_SEQ_FOR_EACH_I(PARAM_ARGS_DEF_, PARAM_FARG, AREA_PARAMS_POCKET)))
std::vector< std::shared_ptr< Area > > makeSections (BOOST_PP_SEQ_FOR_EACH_I(PARAM_ARGS_DEF_, PARAM_FARG, AREA_PARAMS_SECTION_EXTRA),, const std::vector< double > &heights=std::vector< double >(), const TopoDS_Shape &plane=TopoDS_Shape())
std::shared_ptr< Area > getClearedArea (const Toolpath *path, double diameter, double zmax, Base::BoundBox3d bbox)
std::shared_ptr< Area > getRestArea (std::vector< std::shared_ptr< Area >> clearedAreas, double diameter)
TopoDS_Shape toTopoShape ()
void setParams (const AreaParams &params)
const std::list< Shape > getChildren () const
const AreaParams & getParams () const
void clean (bool deleteShapes=false)
TopoDS_Shape getShape (int index=-1)
std::size_t getSectionCount ()
BOOST_PP_SEQ_FOR_EACH (PARAM_TYPED_FOREACH_, PARAM_ENUM_DECLARE_, AREA_PARAMS_PATH) static void abort(bool aborting)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static void addWire (CArea &area, const TopoDS_Wire &wire, const gp_Trsf *trsf=nullptr, double deflection=0.01, bool to_edges=false)
static int addShape (CArea &area, const TopoDS_Shape &shape, const gp_Trsf *trsf=nullptr, double deflection=0.01, const TopoDS_Shape *plane=nullptr, bool force_coplanar=true, CArea *areaOpen=nullptr, bool to_edges=false, bool reorient=true)
static TopoDS_Shape toShape (const CArea &area, bool fill, const gp_Trsf *trsf=nullptr, int reoirent=0)
static TopoDS_Shape toShape (const CCurve &curve, const gp_Trsf *trsf=nullptr, int reorient=0)
static bool isCoplanar (const TopoDS_Shape &s1, const TopoDS_Shape &s2)
static std::list< TopoDS_Shape > sortWires (const std::list< TopoDS_Shape > &shapes, bool has_start=false, gp_Pnt *pstart=nullptr, gp_Pnt *pend=nullptr, double *stepdown_hint=nullptr, short *arc_plane=nullptr, BOOST_PP_SEQ_FOR_EACH_I(PARAM_ARGS_DEF_, PARAM_FARG, AREA_PARAMS_SORT)))
static void toPath (Toolpath &path, const std::list< TopoDS_Shape > &shapes, const gp_Pnt *pstart=nullptr, gp_Pnt *pend=nullptr, BOOST_PP_SEQ_FOR_EACH_I(PARAM_ARGS_DEF_, PARAM_FARG, AREA_PARAMS_PATH)))
static int project (TopoDS_Shape &out, const TopoDS_Shape &in, const AreaParams *params=nullptr, const TopoDS_Shape *work_plane=nullptr)
static void setWireOrientation (TopoDS_Wire &wire, const gp_Dir &dir, bool ccw)
static bool aborting ()
static void setDefaultParams (const AreaStaticParams &params)
static const AreaStaticParams & getDefaultParams ()
static void showShape (const TopoDS_Shape &shape, const char *name, const char *fmt=nullptr,...)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions
void build ()
void addToBuild (CArea &area, const TopoDS_Shape &shape)
TopoDS_Shape toShape (CArea &area, short fill, int reorient=0)
void makeOffset (std::list< std::shared_ptr< CArea >> &areas, BOOST_PP_SEQ_FOR_EACH_I(PARAM_ARGS_DEF_, PARAM_FARG, AREA_PARAMS_OFFSET),, bool from_center=false)
TopoDS_Shape makePocket ()
void explode (const TopoDS_Shape &shape)
TopoDS_Shape findPlane (const TopoDS_Shape &shape, gp_Trsf &trsf)
std::list< Shape > getProjectedShapes (const gp_Trsf &trsf, bool inverse=true) const
Protected Attributes
std::list< Shape > myShapes
std::unique_ptr< CArea > myArea
std::unique_ptr< CArea > myAreaOpen
gp_Trsf myTrsf
AreaParams myParams
TopoDS_Shape myShapePlane
TopoDS_Shape myWorkPlane
TopoDS_Shape myShape
std::vector< std::shared_ptr< Area > > mySections
bool myHaveFace
bool myHaveSolid
bool myShapeDone
bool myProjecting
int mySkippedShapes
Static Protected Attributes
static bool s_aborting
static AreaStaticParams s_params
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Base class for FreeCAD wrapping of libarea
Definition at line 106 of file App/Area.h.
Constructor & Destructor Documentation
Area()
Path::Area::Area (const Area & other, bool deep_copy = true)
~Area()
Path::Area::~Area () override
Member Function Documentation
aborting()
static bool Path::Area::aborting () static
add()
void Path::Area::add (const TopoDS_Shape & shape, BOOST_PP_SEQ_FOR_EACH_I(PARAM_ARGS_DEF_, PARAM_FARG, AREA_PARAMS_OPCODE))
Add a child shape with given operation code
No validation is done at this point. Exception will be thrown when asking for output shape, if any of the children shapes is not valid or not coplanar
shape: the child shape
op: operation code, see AREA_PARAMS_OPCODE
Referenced by Path::FeatureArea::execute().
addShape()
static int Path::Area::addShape (CArea & area, const TopoDS_Shape & shape, const gp_Trsf * trsf = nullptr, double deflection = 0.01, const TopoDS_Shape * plane = nullptr, bool force_coplanar = true, CArea * areaOpen = nullptr, bool to_edges = false, bool reorient = true) static
Add a OCC generic shape to CArea
area: output converted curved object to here
shape: input shape object
trsf: optional transform matrix to transform the wire shape into XY0 plane.
deflection: for defecting non circular curves
plane: a shape for testing coplanar
force_coplaner: if true, discard non-coplanar shapes.
areaOpen: for collecting open curves. If not supplied, open curves are added to area
to_edges: separate open wires to individual edges
reorient: reorient closed wires for wire only shape
Returns
Returns the number of non coplaner. Planar testing only happens if plane is supplied
addToBuild()
void Path::Area::addToBuild (CArea & area, const TopoDS_Shape & shape) protected
Called by build() to add children shape
Mainly for checking if there is any faces for auto fill
addWire()
static void Path::Area::addWire (CArea & area, const TopoDS_Wire & wire, const gp_Trsf * trsf = nullptr, double deflection = 0.01, bool to_edges = false) static
Add a OCC wire shape to CArea
area: output converted curved object to here
wire: input wire object
trsf: optional transform matrix to transform the wire shape into XY0 plane.
deflection: for discretizing non circular curves
to_edges: if true, discretize all curves, and insert as open line segments
BOOST_PP_SEQ_FOR_EACH() [1/2]
Path::Area::BOOST_PP_SEQ_FOR_EACH (PARAM_TYPED_FOREACH_ , PARAM_ENUM_DECLARE_ , AREA_PARAMS_ALL) const
Declare all parameters defined in AREA_PARAMS_ALL as member variable
BOOST_PP_SEQ_FOR_EACH() [2/2]
Path::Area::BOOST_PP_SEQ_FOR_EACH (PARAM_TYPED_FOREACH_ , PARAM_ENUM_DECLARE_ , AREA_PARAMS_PATH)
build()
void Path::Area::build () protected
Called internally to combine children shapes for further processing
clean()
void Path::Area::clean (bool deleteShapes = false)
Clean internal caches
The combined shapes is cached internally to make other operation more efficient, such as makeOffset() and makePocket()
deleteShapes: if true, delete all children shapes.
Referenced by Path::FeatureArea::execute().
explode()
void Path::Area::explode (const TopoDS_Shape & shape) protected
findPlane()
TopoDS_Shape Path::Area::findPlane (const TopoDS_Shape & shape, gp_Trsf & trsf) protected
getChildren()
const std::list<Shape> Path::Area::getChildren () const inline
Definition at line 262 of file App/Area.h.
getClearedArea()
std::shared_ptr<Area> Path::Area::getClearedArea (const Toolpath * path, double diameter, double zmax, Base::BoundBox3d bbox)
getDefaultParams()
static const AreaStaticParams& Path::Area::getDefaultParams () static
getParams()
const AreaParams& Path::Area::getParams () const inline
Get the current configuration
Definition at line 268 of file App/Area.h.
getPlane()
TopoDS_Shape Path::Area::getPlane (gp_Trsf * trsf = nullptr)
Return the current active workplane
trsf: optional return of a transformation matrix that will bring the found plane to XY0 plane.
If no workplane is set using setPlane(), the active workplane is derived from the added children shapes using the same algorithm empolyed by setPlane().
getProjectedShapes()
std::list<Shape> Path::Area::getProjectedShapes (const gp_Trsf & trsf, bool inverse = true) const protected
getRestArea()
std::shared_ptr<Area> Path::Area::getRestArea (std::vector< std::shared_ptr< Area >> clearedAreas, double diameter)
getSectionCount()
std::size_t Path::Area::getSectionCount () inline
Return the number of sections
Definition at line 289 of file App/Area.h.
Referenced by Path::FeatureArea::execute().
getShape()
TopoDS_Shape Path::Area::getShape (int index = -1)
Get the combined shape
index: index of the section, -1 for all sections. No effect on non-sectioned area.
Referenced by Path::FeatureArea::execute().
isBuilt()
bool Path::Area::isBuilt () const
isCoplanar()
static bool Path::Area::isCoplanar (const TopoDS_Shape & s1, const TopoDS_Shape & s2) static
Check if two OCC shape is coplanar
makeOffset() [1/2]
TopoDS_Shape Path::Area::makeOffset (int index = -1, BOOST_PP_SEQ_FOR_EACH_I(PARAM_ARGS_DEF_, PARAM_FARG, AREA_PARAMS_OFFSET) , int reoirent = 0, bool from_center = false)
Generate an offset of the combined shape
See AREA_PARAMS_OFFSET for description of the arguments. If more than one offset is requested, a compound shape is return containing all offset shapes as wires regardless of Fill setting.
makeOffset() [2/2]
void Path::Area::makeOffset (std::list< std::shared_ptr< CArea >> & areas, BOOST_PP_SEQ_FOR_EACH_I(PARAM_ARGS_DEF_, PARAM_FARG, AREA_PARAMS_OFFSET) , bool from_center = false) protected
Obtain a list of offset areas
See AREA_PARAMS_OFFSET for description of the arguments.
makePocket() [1/2]
TopoDS_Shape Path::Area::makePocket () protected
Make a pocket of the combined shape
User AREA_PARAMS_POCKET setting in myParams.
makePocket() [2/2]
TopoDS_Shape Path::Area::makePocket (int index = -1, BOOST_PP_SEQ_FOR_EACH_I(PARAM_ARGS_DEF_, PARAM_FARG, AREA_PARAMS_POCKET))
Make a pocket of the combined shape
See AREA_PARAMS_POCKET for description of the arguments.
makeSections()
std::vector<std::shared_ptr<Area> > Path::Area::makeSections (BOOST_PP_SEQ_FOR_EACH_I(PARAM_ARGS_DEF_, PARAM_FARG, AREA_PARAMS_SECTION_EXTRA) , const std::vector< double > & heights = std::vector< double >(), const TopoDS_Shape & plane = TopoDS_Shape())
Make a pocket of the combined shape
heights: optional customized heights of each section. The meaning of each height depends on section mode. If none is given, the section heights is determined by the section settings in this Area object (configured through setParams()).
plane: the section plane if the section mode is SectionModeWorkplane, otherwise ignored
See #AREA_PARAMS_EXTRA for description of the arguments. Currently, there is only one argument, namely mode for section mode.
project()
static int Path::Area::project (TopoDS_Shape & out, const TopoDS_Shape & in, const AreaParams * params = nullptr, const TopoDS_Shape * work_plane = nullptr) static
setDefaultParams()
static void Path::Area::setDefaultParams (const AreaStaticParams & params) static
Referenced by Path.Main.Gui.PreferencesJob.JobPreferencesPage::saveSettings().
setParams()
void Path::Area::setParams (const AreaParams & params)
Config this Area object
Referenced by Path::FeatureArea::execute().
setPlane()
void Path::Area::setPlane (const TopoDS_Shape & shape)
Set a working plane
shape: a shape defining a working plane.
The supplied shape does not need to be planar. Area will try to find planar sub-shape (face, wire or edge). If more than one planar sub-shape is found, it will prefer the top plane parallel to XY0 plane.
If no working plane are set, Area will try to find a working plane from the added children shape using the same algorithm
Referenced by Path::FeatureArea::execute().
setWireOrientation()
static void Path::Area::setWireOrientation (TopoDS_Wire & wire, const gp_Dir & dir, bool ccw) static
showShape()
static void Path::Area::showShape (const TopoDS_Shape & shape, const char * name, const char * fmt = nullptr, ...) static
sortWires()
static std::list<TopoDS_Shape> Path::Area::sortWires (const std::list< TopoDS_Shape > & shapes, bool has_start = false, gp_Pnt * pstart = nullptr, gp_Pnt * pend = nullptr, double * stepdown_hint = nullptr, short * arc_plane = nullptr, BOOST_PP_SEQ_FOR_EACH_I(PARAM_ARGS_DEF_, PARAM_FARG, AREA_PARAMS_SORT)) static
Group shapes by their plane, and return a list of sorted wires
The output wires is ordered by its occupied plane, and sorted to minimize traval distance
shapes: input list of shapes.
has_start: if false or pstart is 0, then a start point will be auto selected.
pstart: optional start point. If has_start is false, then the auto selected start point will be returned with this point if not NULL.
pend: optional output containing the ending point of the returned
stepdown_hint: optional output of a hint of step down as the max distance between two sections.
arc_plane: optional arc plane selection, if given the found plane will be returned. See AREA_PARAMS_ARC_PLANE for more details.
See AREA_PARAMS_SORT for other arguments
Returns
sorted wires
toPath()
static void Path::Area::toPath (Toolpath & path, const std::list< TopoDS_Shape > & shapes, const gp_Pnt * pstart = nullptr, gp_Pnt * pend = nullptr, BOOST_PP_SEQ_FOR_EACH_I(PARAM_ARGS_DEF_, PARAM_FARG, AREA_PARAMS_PATH)) static
Convert a list of wires to gcode
path: output toolpath
shapes: input list of shapes
pstart: output start point,
pend: optional output containing the ending point of the returned
See AREA_PARAMS_PATH for other arguments
toShape() [1/3]
TopoDS_Shape Path::Area::toShape (CArea & area, short fill, int reorient = 0) protected
Called internally to obtain the combined children shapes
toShape() [2/3]
static TopoDS_Shape Path::Area::toShape (const CArea & area, bool fill, const gp_Trsf * trsf = nullptr, int reoirent = 0) static
Convert curves in CArea into an OCC shape
area: input area object
fill: if true, create a face object from the wires
trsf: optional transform matrix to transform the shape back into its original position.
toShape() [3/3]
static TopoDS_Shape Path::Area::toShape (const CCurve & curve, const gp_Trsf * trsf = nullptr, int reorient = 0) static
Convert a single curve into an OCC wire
curve: input curve object
trsf: optional transform matrix to transform the shape back into its original position.
toTopoShape()
TopoDS_Shape Path::Area::toTopoShape ()
Member Data Documentation
myArea
std::unique_ptr<CArea> Path::Area::myArea protected
Definition at line 125 of file App/Area.h.
myAreaOpen
std::unique_ptr<CArea> Path::Area::myAreaOpen protected
Definition at line 126 of file App/Area.h.
myHaveFace
bool Path::Area::myHaveFace protected
Definition at line 133 of file App/Area.h.
myHaveSolid
bool Path::Area::myHaveSolid protected
Definition at line 134 of file App/Area.h.
myParams
AreaParams Path::Area::myParams protected
Definition at line 128 of file App/Area.h.
myProjecting
bool Path::Area::myProjecting protected
Definition at line 136 of file App/Area.h.
mySections
std::vector<std::shared_ptr<Area> > Path::Area::mySections protected
Definition at line 132 of file App/Area.h.
myShape
TopoDS_Shape Path::Area::myShape protected
Definition at line 131 of file App/Area.h.
myShapeDone
bool Path::Area::myShapeDone protected
Definition at line 135 of file App/Area.h.
myShapePlane
TopoDS_Shape Path::Area::myShapePlane protected
Definition at line 129 of file App/Area.h.
myShapes
std::list<Shape> Path::Area::myShapes protected
Definition at line 124 of file App/Area.h.
mySkippedShapes
int Path::Area::mySkippedShapes mutable protected
Definition at line 137 of file App/Area.h.
myTrsf
gp_Trsf Path::Area::myTrsf protected
Definition at line 127 of file App/Area.h.
myWorkPlane
TopoDS_Shape Path::Area::myWorkPlane protected
Definition at line 130 of file App/Area.h.
s_aborting
bool Path::Area::s_aborting static protected
Definition at line 139 of file App/Area.h.
s_params
AreaStaticParams Path::Area::s_params static protected
Definition at line 140 of file App/Area.h.
The documentation for this class was generated from the following file:
App/Area.h