FreeCAD: App::BackupPolicy Class Reference
App::BackupPolicy Class Reference
Public Types
enum Policy { Standard, TimeStamp }
Public Member Functions
BackupPolicy ()
~BackupPolicy ()=default
void setPolicy (Policy p)
void setNumberOfFiles (int count)
void useBackupExtension (bool on)
void setDateFormat (const std::string &fmt)
void apply (const std::string &sourcename, const std::string &targetname)
Detailed Description
Definition at line 1804 of file App/Document.cpp.
Member Enumeration Documentation
Policy
enum App::BackupPolicy::Policy
Enumerator
Standard
TimeStamp
Definition at line 1807 of file App/Document.cpp.
Constructor & Destructor Documentation
BackupPolicy()
App::BackupPolicy::BackupPolicy () inline
Definition at line 1812 of file App/Document.cpp.
References Standard.
~BackupPolicy()
App::BackupPolicy::~BackupPolicy () default
Member Function Documentation
apply()
void App::BackupPolicy::apply (const std::string & sourcename, const std::string & targetname) inline
Definition at line 1836 of file App/Document.cpp.
References Standard, and TimeStamp.
Referenced by App::Document::saveToFile().
setDateFormat()
void App::BackupPolicy::setDateFormat (const std::string & fmt) inline
Definition at line 1832 of file App/Document.cpp.
References Path.Post.scripts.comparams_post::fmt().
Referenced by App::Document::saveToFile().
setNumberOfFiles()
void App::BackupPolicy::setNumberOfFiles (int count) inline
Definition at line 1824 of file App/Document.cpp.
References src.Mod.AddonManager.NetworkManager::count.
Referenced by App::Document::saveToFile().
setPolicy()
void App::BackupPolicy::setPolicy (Policy p) inline
Definition at line 1820 of file App/Document.cpp.
References buildPsets::p.
Referenced by App::Document::saveToFile().
useBackupExtension()
void App::BackupPolicy::useBackupExtension (bool on) inline
Definition at line 1828 of file App/Document.cpp.
Referenced by App::Document::saveToFile().
The documentation for this class was generated from the following file:
App/Document.cpp