FreeCAD: DynamicQLineEdit Class Reference
DynamicQLineEdit Class Reference
Public Member Functions
DynamicQLineEdit (QWidget *parent=nullptr)
QSize sizeHint () const override
void keyPressEvent (QKeyEvent *event) override
Public Member Functions inherited from Gui::ExpLineEdit
ExpLineEdit (QWidget *parent=nullptr, bool expressionOnly=false)
void setExpression (std::shared_ptr< App::Expression > expr) override
void bind (const App::ObjectIdentifier &_path) override
bool apply (const std::string &propName) override
void keyPressEvent (QKeyEvent *event) override
void resizeEvent (QResizeEvent *event) override
Public Member Functions inherited from Gui::ExpressionWidget
ExpressionWidget ()
QPixmap getIcon (const char *name, const QSize &size) const
Public Member Functions inherited from Gui::ExpressionBinding
ExpressionBinding ()
virtual ~ExpressionBinding ()
virtual void bind (const App::Property &prop)
bool isBound () const
void unbind ()
virtual bool apply ()
bool hasExpression () const
bool autoApply () const
void setAutoApply (bool value)
Additional Inherited Members
Protected Member Functions inherited from Gui::ExpressionWidget
void makeLabel (QLineEdit *parent)
Protected Member Functions inherited from Gui::ExpressionBinding
const App::ObjectIdentifier & getPath () const
std::shared_ptr< App::Expression > getExpression () const
std::string getExpressionString (bool no_throw=true) const
std::string getEscapedExpressionString () const
bool assignToProperty (const std::string &propName, double)
virtual void onChange ()
void expressionChange (const App::ObjectIdentifier &id)
void objectDeleted (const App::DocumentObject &)
Protected Attributes inherited from Gui::ExpressionWidget
ExpressionLabel * iconLabel {nullptr}
QPalette defaultPalette
int iconHeight {-1}
Protected Attributes inherited from Gui::ExpressionBinding
boost::signals2::scoped_connection expressionchanged
boost::signals2::scoped_connection objectdeleted
bool m_autoApply {false}
Detailed Description
Definition at line 543 of file Tree.cpp.
Constructor & Destructor Documentation
DynamicQLineEdit()
DynamicQLineEdit::DynamicQLineEdit (QWidget * parent = nullptr) inline
Definition at line 546 of file Tree.cpp.
Member Function Documentation
keyPressEvent()
void DynamicQLineEdit::keyPressEvent (QKeyEvent * event) inline override
Definition at line 561 of file Tree.cpp.
References Gui::ExpLineEdit::keyPressEvent().
sizeHint()
QSize DynamicQLineEdit::sizeHint () const inline override
Definition at line 548 of file Tree.cpp.
References Gui::TreeParams::getItemBackgroundPadding(), and KDL::min().
The documentation for this class was generated from the following file:
Tree.cpp