FreeCAD: App::Document Class Reference
App::Document Class Reference
The document class.
#include <Document.h>
Public Types
enum Status {
SkipRecompute = 0, KeepTrailingDigits = 1, Closable = 2, Restoring = 3,
Recomputing = 4, PartialRestore = 5, Importing = 6, PartialDoc = 7,
AllowPartialRecompute = 8, TempDoc = 9, RestoreError = 10, LinkStampChanged = 11,
IgnoreErrorOnRecompute = 12, RecomputeOnRestore = 13, MigrateLCS = 14
}
Public Member Functions
Object handling
DocumentObject * addObject (const char *sType, const char *pObjectName=nullptr, bool isNew=true, const char *viewType=nullptr, bool isPartial=false)
std::vector< DocumentObject * > addObjects (const char *sType, const std::vector< std::string > &objectNames, bool isNew=true)
void removeObject (const char *sName)
Remove a feature out of the document.
void addObject (DocumentObject *, const char *pObjectName=nullptr)
std::vector< DocumentObject * > copyObject (const std::vector< DocumentObject * > &objs, bool recursive=false, bool returnAll=false)
DocumentObject * moveObject (DocumentObject *obj, bool recursive=false)
DocumentObject * getActiveObject () const
Returns the active Object of this document.
DocumentObject * getObject (const char *Name) const
Returns a Object of this document.
DocumentObject * getObjectByID (long id) const
Returns a Object of this document by its id.
bool isIn (const DocumentObject *pFeat) const
Returns true if the DocumentObject is contained in this document.
const char * getObjectName (DocumentObject *pFeat) const
Returns a Name of an Object or 0.
std::string getUniqueObjectName (const char *Name) const
Returns a Name of an Object or 0.
std::string getStandardObjectName (const char *Name, int d) const
Returns a name of the form prefix_number. d specifies the number of digits.
std::vector< DocumentObject * > getDependingObjects () const
Returns a list of document's objects including the dependencies.
const std::vector< DocumentObject * > & getObjects () const
Returns a list of all Objects.
std::vector< DocumentObject * > getObjectsOfType (const Base::Type &typeId) const
std::vector< DocumentObject * > getObjectsWithExtension (const Base::Type &typeId, bool derived=true) const
std::vector< DocumentObject * > findObjects (const Base::Type &typeId, const char *objname, const char *label) const
template<typename T >
std::vector< T * > getObjectsOfType () const
Returns an array with the correct types already.
template<typename T >
int countObjectsOfType () const
int countObjectsOfType (const char *typeName) const
int countObjects () const
get the number of objects in the document
methods for modification and state handling
void purgeTouched ()
Remove all modifications. After this call The document becomes Valid again.
bool isTouched () const
check if there is any touched object in this document
bool mustExecute () const
check if there is any object must execute in this document
std::vector< App::DocumentObject * > getTouched () const
returns all touched objects
void setClosable (bool)
set the document to be closable, this is on by default.
bool isClosable () const
check whether the document can be closed
int recompute (const std::vector< App::DocumentObject * > &objs={}, bool force=false, bool *hasError=nullptr, int options=0)
bool recomputeFeature (DocumentObject *Feat, bool recursive=false)
Recompute only one feature.
const char * getErrorDescription (const App::DocumentObject *) const
get the text of the error of a specified object
bool testStatus (Status pos) const
return the status bits
void setStatus (Status pos, bool on)
set the status bits
methods for the UNDO REDO and Transaction handling
Introduce a new concept of transaction ID. Each transaction must be unique inside the document. Multiple transactions from different documents can be grouped together with the same transaction ID.
When undo, Gui component can query getAvailableUndo(id) to see if it is possible to undo with a given ID. If there more than one undo transactions, meaning that there are other transactions before the given ID. The Gui component shall ask user if they want to undo multiple steps. And if the user agrees, call undo(id) to unroll all transaction before and including the one with the given ID. Same applies for redo.
The new transaction ID describe here is fully backward compatible. Calling the APIs with a default id=0 gives the original behavior.
void setUndoMode (int iMode)
switch the level of Undo/Redo
int getUndoMode () const
switch the level of Undo/Redo
void setTransactionMode (int iMode)
switch the transaction mode
void openTransaction (const char *name=nullptr)
void renameTransaction (const char *name, int id)
Rename the current transaction if the id matches.
void commitTransaction ()
Commit the Command transaction. Do nothing If there is no Command transaction open.
void abortTransaction ()
Abort the actually running transaction.
bool hasPendingTransaction () const
Check if a transaction is open.
int getTransactionID (bool undo, unsigned pos=0) const
Return the undo/redo transaction ID starting from the back.
bool isTransactionEmpty () const
void setUndoLimit (unsigned int UndoMemSize=0)
Set the Undo limit in Byte!
unsigned int getUndoMemSize () const
Returns the actual memory consumption of the Undo redo stuff.
void setMaxUndoStackSize (unsigned int UndoMaxStackSize=20)
Set the Undo limit as stack size.
unsigned int getMaxUndoStackSize () const
Set the Undo limit as stack size.
void clearUndos ()
Remove all stored Undos and Redos.
int getAvailableUndos (int id=0) const
Returns the number of stored Undos. If greater than 0 Undo will be effective.
std::vector< std::string > getAvailableUndoNames () const
Returns a list of the Undo names.
bool undo (int id=0)
Will UNDO one step, returns False if no undo was done (Undos == 0).
int getAvailableRedos (int id=0) const
Returns the number of stored Redos. If greater than 0 Redo will be effective.
std::vector< std::string > getAvailableRedoNames () const
Returns a list of the Redo names.
bool redo (int id=0)
Will REDO one step, returns False if no redo was done (Redos == 0).
bool isPerformingTransaction () const
void addOrRemovePropertyOfObject (TransactionalObject *, Property *prop, bool add)
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual Property * getPropertyByName (const char *name) const
find a property by its name
virtual const char * getPropertyName (const Property *prop) const
get the name of a property
virtual void getPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void getPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
virtual short getPropertyType (const Property *prop) const
get the Type of a Property
virtual short getPropertyType (const char *name) const
get the Type of a named Property
virtual const char * getPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * getPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * getPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * getPropertyDocumentation (const char *name) const
get the Group of a named Property
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
virtual App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false)
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual bool removeDynamicProperty (const char *name)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
virtual void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus)
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Attributes
Properties
PropertyString Label
holds the long name of the document (utf-8 coded)
PropertyString FileName
full qualified (with path) file name (utf-8 coded)
PropertyString CreatedBy
creators name (utf-8)
PropertyString CreationDate
PropertyString LastModifiedBy
user last modified the document
PropertyString LastModifiedDate
PropertyString Company
company name UTF8(optional)
PropertyEnumeration UnitSystem
Unit System.
PropertyString Comment
long comment or description (UTF8 with line breaks)
PropertyString Id
Id e.g. Part number.
PropertyUUID Uid
unique identifier of the document
App::PropertyString License
Full name of the licence e.g. "Creative Commons Attribution". See https://spdx.org/licenses/.
App::PropertyString LicenseURL
License description/contract URL.
App::PropertyMap Meta
Meta descriptions.
App::PropertyMap Material
Material descriptions, used and defined in the Material module.
PropertyString TransientDir
read-only name of the temp dir created when the document is opened
PropertyLink Tip
Tip object of the document (if any)
PropertyString TipName
Tip object of the document (if any)
PropertyBool ShowHidden
Whether to show hidden items in TreeView.
PropertyBool UseHasher
Whether to use hasher on topological naming.
Protected Member Functions
const App::PropertyData & getPropertyData (void) const override
Protected Member Functions inherited from App::PropertyContainer
virtual void onEarlyChange (const Property *)
virtual void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
PropertyContainer::handleChangedPropertyName is called during restore to possibly fix reading of older versions of this property container. This method is typically called if the property on file has changed its name in more recent versions.
virtual void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
PropertyContainer::handleChangedPropertyType is called during restore to possibly fix reading of older versions of the property container. This method is typically called if the property on file has changed its type in more recent versions.
Static Protected Member Functions
static const App::PropertyData * getPropertyDataPtr (void)
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Signals of the document
boost::signals2::signal< void(const App::Document &, const App::Property &)> signalBeforeChange
signal before changing an doc property
boost::signals2::signal< void(const App::Document &, const App::Property &)> signalChanged
signal on changed doc property
boost::signals2::signal< void(const App::DocumentObject &)> signalNewObject
signal on new Object
boost::signals2::signal< void(const App::DocumentObject &)> signalDeletedObject
signal on deleted Object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalBeforeChangeObject
signal before changing an Object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalChangedObject
signal on changed Object
boost::signals2::signal< void(const App::DocumentObject &)> signalTouchedObject
signal on manually called DocumentObject::touch()
boost::signals2::signal< void(const App::DocumentObject &)> signalRelabelObject
signal on relabeled Object
boost::signals2::signal< void(const App::DocumentObject &)> signalActivatedObject
signal on activated Object
boost::signals2::signal< void(const App::DocumentObject &, Transaction *)> signalTransactionAppend
signal on created object
boost::signals2::signal< void(const App::DocumentObject &, Transaction *)> signalTransactionRemove
signal on removed object
boost::signals2::signal< void(const App::Document &)> signalUndo
signal on undo
boost::signals2::signal< void(const App::Document &)> signalRedo
signal on redo
boost::signals2::signal< void(Base::Writer &)> signalSaveDocument
boost::signals2::signal< void(Base::XMLReader &)> signalRestoreDocument
boost::signals2::signal< void(const std::vector< App::DocumentObject * > &, Base::Writer &)> signalExportObjects
boost::signals2::signal< void(const std::vector< App::DocumentObject * > &, Base::Writer &)> signalExportViewObjects
boost::signals2::signal< void(const std::vector< App::DocumentObject * > &, Base::XMLReader &)> signalImportObjects
boost::signals2::signal< void(const std::vector< App::DocumentObject * > &, Base::Reader &, const std::map< std::string, std::string > &)> signalImportViewObjects
boost::signals2::signal< void(const std::vector< App::DocumentObject * > &)> signalFinishImportObjects
boost::signals2::signal< void(const App::Document &, const std::string &)> signalStartSave
boost::signals2::signal< void(const App::Document &, const std::string &)> signalFinishSave
boost::signals2::signal< void(const App::Document &)> signalBeforeRecompute
boost::signals2::signal< void(const App::Document &, const std::vector< App::DocumentObject * > &)> signalRecomputed
boost::signals2::signal< void(const App::DocumentObject &)> signalRecomputedObject
boost::signals2::signal< void(const App::Document &, std::string)> signalOpenTransaction
boost::signals2::signal< void(const App::Document &)> signalCommitTransaction
boost::signals2::signal< void(const App::Document &)> signalAbortTransaction
boost::signals2::signal< void(const App::Document &, const std::vector< App::DocumentObject * > &)> signalSkipRecompute
boost::signals2::signal< void(const App::DocumentObject &)> signalFinishRestoreObject
boost::signals2::signal< void(const App::Document &, const App::Property &)> signalChangePropertyEditor
boost::signals2::signal< void(std::string)> signalLinkXsetValue
void clearDocument ()
File handling of the document
enum ExportStatus { NotExporting, Exporting }
bool save ()
Save the Document under a new Name.
bool saveAs (const char *file)
bool saveCopy (const char *file) const
void restore (const char *filename=nullptr, bool delaySignal=false, const std::vector< std::string > &objNames={})
Restore the document from the file in Property Path.
bool afterRestore (bool checkPartial=false)
bool afterRestore (const std::vector< App::DocumentObject * > &, bool checkPartial=false)
ExportStatus isExporting (const App::DocumentObject *obj) const
void exportObjects (const std::vector< App::DocumentObject * > &, std::ostream &)
void exportGraphviz (std::ostream &) const
std::vector< App::DocumentObject * > importObjects (Base::XMLReader &reader)
std::vector< App::DocumentObject * > importLinks (const std::vector< App::DocumentObject * > &objs={})
bool isSaved () const
Opens the document from its file name.
const char * getName () const
Get the document name.
const char * getProgramVersion () const
Get program version the project file was created with.
const char * getFileName () const
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
unsigned int getMemSize () const override
dependency stuff
enum DependencyOption { DepSort = 1, DepNoXLinked = 2, DepNoCycle = 4 }
Option bit flags used by getDepenencyList()
class Application
class TransactionalObject
because of transaction handling
class DocumentObject
class Transaction
class TransactionDocumentObject
Document (const char *documentName="")
Construction.
void _removeObject (DocumentObject *pcObject)
Remove an object out of the document (internal)
void _addObject (DocumentObject *pcObject, const char *pObjectName)
void _checkTransaction (DocumentObject *pcDelObj, const Property *What, int line)
checks if a valid transaction is open
void breakDependency (DocumentObject *pcObject, bool clear)
std::vector< App::DocumentObject * > readObjects (Base::XMLReader &reader)
void writeObjects (const std::vector< App::DocumentObject * > &, Base::Writer &writer) const
bool saveToFile (const char *filename) const
int countObjectsOfType (const Base::Type &typeId) const
void onBeforeChange (const Property *prop) override
get called before the value is changed
void onChanged (const Property *prop) override
get called by the container when a property has changed
void onBeforeChangeProperty (const TransactionalObject *Who, const Property *What)
callback from the Document objects before property will be changed
void onChangedProperty (const DocumentObject *Who, const Property *What)
callback from the Document objects after property was changed
int _recomputeFeature (DocumentObject *Feat)
void _clearRedos ()
void _rebuildDependencyList (const std::vector< App::DocumentObject * > &objs=std::vector< App::DocumentObject * >())
refresh the internal dependency graph
std::string getTransientDirectoryName (const std::string &uuid, const std::string &filename) const
int _openTransaction (const char *name=nullptr, int id=0)
void _commitTransaction (bool notify=false)
Internally called by App::Application to commit the Command transaction.
void _abortTransaction ()
Internally called by App::Application to abort the running transaction.
void writeDependencyGraphViz (std::ostream &out)
write GraphViz file
bool checkOnCycle ()
checks if the graph is directed and has no cycles
std::vector< App::DocumentObject * > getInList (const DocumentObject *me) const
get a list of all objects linking to the given object
std::vector< App::Document * > getDependentDocuments (bool sort=true)
std::vector< App::DocumentObject * > topologicalSort () const
get a list of topological sorted objects (https://en.wikipedia.org/wiki/Topological_sorting)
std::vector< App::DocumentObject * > getRootObjects () const
get all root objects (objects no other one reference too)
std::vector< App::DocumentObject * > getRootObjectsIgnoreLinks () const
get all tree root objects (objects that are at the root of the object tree)
std::vector< std::list< App::DocumentObject * > > getPathsByOutList (const App::DocumentObject *from, const App::DocumentObject *to) const
get all possible paths from one object to another following the OutList
std::pair< bool, int > addStringHasher (const StringHasherRef &hasher) const
StringHasherRef getStringHasher (int index=-1) const
void getLinksTo (std::set< DocumentObject * > &links, const DocumentObject *obj, int options, int maxCount=0, const std::vector< DocumentObject * > &objs={}) const
bool hasLinksTo (const DocumentObject *obj) const
Check if there is any link to the given object.
void addRecomputeObject (DocumentObject *obj)
Called by objects during restore to ask for recompute.
const std::string & getOldLabel () const
void renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &paths, const std::function< bool(const App::DocumentObject *)> &selector=[](const App::DocumentObject *) { return true;})
Function called to signal that an object identifier has been renamed.
PyObject * getPyObject () override
std::string getFullName () const override
~Document () override
Destruction.
static std::vector< App::DocumentObject * > getDependencyList (const std::vector< App::DocumentObject * > &objs, int options=0)
static std::vector< App::Document * > getDependentDocuments (std::vector< App::Document * > docs, bool sort)
static bool isAnyRestoring ()
Indicate if there is any document restoring/importing.
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Detailed Description
The document class.
This is besides the Application class the most important class in FreeCAD It contains all the data of the opened, saved or newly created FreeCAD Document. The Document manage the Undo and Redo mechanism and the linking of documents.
Note: the documents are not free objects. They are completely handled by the App::Application. Only the Application can Open or destroy a document.
Exception handling
As the document is the main data structure of FreeCAD we have to take a close look at how Exceptions affect the integrity of the App::Document.
Undo Redo an Transactions
Undo Redo handling is one of the major mechanism of a document in terms of user friendliness and speed (no one will wait for Undo too long).
Graph and dependency handling
The FreeCAD document handles the dependencies of its DocumentObjects with an adjacence list. This gives the opportunity to calculate the shortest recompute path. Also, it enables more complicated dependencies beyond trees.
See also
App::Application
App::DocumentObject
Definition at line 58 of file App/Document.h.
Member Enumeration Documentation
DependencyOption
enum App::Document::DependencyOption
Option bit flags used by getDepenencyList()
Enumerator
DepSort
Return topological sorted list.
DepNoXLinked
Do no include object linked by PropertyXLink, as it can handle external link.
DepNoCycle
Raise exception on cycles.
Definition at line 467 of file App/Document.h.
ExportStatus
enum App::Document::ExportStatus
Enumerator
NotExporting
Exporting
Definition at line 207 of file App/Document.h.
Status
enum App::Document::Status
Enumerator
SkipRecompute
KeepTrailingDigits
Closable
Restoring
Recomputing
PartialRestore
Importing
PartialDoc
AllowPartialRecompute
TempDoc
RestoreError
LinkStampChanged
IgnoreErrorOnRecompute
RecomputeOnRestore
MigrateLCS
Definition at line 64 of file App/Document.h.
Constructor & Destructor Documentation
~Document()
Document::~Document () override
Destruction.
Definition at line 974 of file App/Document.cpp.
References App::DocumentP::clearDocument(), clearUndos(), src.Mod.AddonManager.addonmanager_freecad_interface::Console, Base::FileInfo::deleteDirectoryRecursive(), toolbit-attributes::doc, App::DocumentP::DocumentPythonObject, SCL.SimpleDataTypes::e, getName(), App::PropertyString::getValue(), and TransientDir.
Document()
Document::Document (const char * documentName = "") explicit protected
Construction.
Definition at line 862 of file App/Document.cpp.
References ADD_PROPERTY_TYPE, Comment, Company, src.Mod.AddonManager.addonmanager_freecad_interface::Console, App::countOfLicenses, CreatedBy, CreationDate, Base::Tools::currentDateTimeString(), App::DocumentP::DocumentPythonObject, FileName, App::GetApplication(), ParameterGrp::GetASCII(), Base::UnitsApi::getDescription(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), SplineSurface::i, SplineSurface::id, Id, Label, LastModifiedBy, LastModifiedDate, License, App::licenseItems, LicenseURL, Meta, Base::NumUnitSystemTypes, App::posnOfFullName, App::posnOfUrl, App::Prop_Hidden, App::Prop_None, App::Prop_ReadOnly, App::Prop_Transient, App::PropertyEnumeration::setEnums(), App::PropertyEnumeration::setValue(), ShowHidden, Tip, TipName, App::Property::touch(), TransientDir, Uid, UnitSystem, and UseHasher.
Member Function Documentation
_abortTransaction()
void Document::_abortTransaction () protected
Internally called by App::Application to abort the running transaction.
Definition at line 558 of file App/Document.cpp.
References App::DocumentP::activeUndoTransaction, App::Transaction::apply(), App::DocumentP::committing, FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, FC_WARN, App::Transaction::getID(), isPerformingTransaction(), App::DocumentP::rollback, and signalAbortTransaction.
_addObject()
void Document::_addObject (DocumentObject * pcObject, const char * pObjectName) protected
Definition at line 3797 of file App/Document.cpp.
References _checkTransaction(), App::DocumentP::activeObject, App::DocumentP::activeUndoTransaction, App::Transaction::addObjectDel(), getUniqueObjectName(), App::DocumentObject::getViewProviderNameOverride(), App::DocumentP::lastObjectId, App::DocumentP::objectArray, App::DocumentP::objectIdMap, App::DocumentP::objectMap, App::DocumentObject::pcNameInDocument, App::DocumentP::rollback, signalActivatedObject, signalNewObject, and signalTransactionAppend.
Referenced by App::TransactionDocumentObject::applyNew(), and moveObject().
_checkTransaction()
void Document::_checkTransaction (DocumentObject * pcDelObj, const Property * What, int line) protected
checks if a valid transaction is open
Definition at line 438 of file App/Document.cpp.
References _openTransaction(), App::DocumentP::activeUndoTransaction, FC_LOG, FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, App::Application::getActiveTransaction(), App::GetApplication(), App::Property::getFullName(), getName(), Importing, isPerformingTransaction(), App::DocumentP::iUndoMode, App::Property::NoModify, Restoring, App::Property::testStatus(), and testStatus().
Referenced by _addObject(), _removeObject(), addObject(), addObjects(), onBeforeChangeProperty(), and removeObject().
_clearRedos()
void Document::_clearRedos () protected
Definition at line 483 of file App/Document.cpp.
References App::DocumentP::committing, FC_ERR, and isPerformingTransaction().
Referenced by _openTransaction(), and clearUndos().
_commitTransaction()
void Document::_commitTransaction (bool notify = false) protected
Internally called by App::Application to commit the Command transaction.
Definition at line 511 of file App/Document.cpp.
References App::DocumentP::activeUndoTransaction, App::Application::closeActiveTransaction(), App::DocumentP::committing, FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, FC_WARN, App::GetApplication(), App::Transaction::getID(), isPerformingTransaction(), femsolver.signal::notify(), signalCommitTransaction, and App::DocumentP::UndoMaxStackSize.
Referenced by _openTransaction(), clearUndos(), redo(), and undo().
_openTransaction()
int Document::_openTransaction (const char * name = nullptr, int id = 0) protected
Open a new command Undo/Redo, an UTF-8 name can be specified
Parameters
name transaction name
id transaction ID, if 0 then the ID is auto generated.
Returns
: Return the ID of the new transaction.
This function creates an actual transaction regardless of Application AutoTransaction setting.
Definition at line 375 of file App/Document.cpp.
References _clearRedos(), _commitTransaction(), App::DocumentP::activeUndoTransaction, src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui::app, App::DocumentP::committing, FC_LOG, FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, FC_WARN, App::GetApplication(), App::Transaction::getID(), getName(), SplineSurface::id, isPerformingTransaction(), App::DocumentP::iUndoMode, App::Transaction::Name, App::DocumentP::opentransaction, signalOpenTransaction, and Transaction.
Referenced by _checkTransaction(), and addOrRemovePropertyOfObject().
_rebuildDependencyList()
void Document::_rebuildDependencyList (const std::vector< App::DocumentObject * > & objs = std::vector<App::DocumentObject*>()) protected
refresh the internal dependency graph
Definition at line 2892 of file App/Document.cpp.
References _buildDependencyList(), App::DocumentP::objectArray, and replaceobj::objs.
_recomputeFeature()
int Document::_recomputeFeature (DocumentObject * Feat) protected
helper which Recompute only this feature
Returns
0 if succeeded, 1 if failed, -1 if aborted by user.
Definition at line 3461 of file App/Document.cpp.
References App::DocumentP::addRecomputeLog(), SCL.SimpleDataTypes::e, App::PropertyExpressionEngine::execute(), App::PropertyExpressionEngine::ExecuteNonOutput, App::PropertyExpressionEngine::ExecuteOutput, App::DocumentObject::ExpressionEngine, FC_ERR, FC_LOG, App::DocumentObject::getFullName(), App::DocumentObject::recompute(), App::DocumentObject::resetError(), App::DocumentObject::StdReturn, App::DocumentObjectExecReturn::Which, and App::DocumentObjectExecReturn::Why.
Referenced by recompute(), and recomputeFeature().
_removeObject()
void Document::_removeObject (DocumentObject * pcObject) protected
Remove an object out of the document (internal)
Definition at line 3939 of file App/Document.cpp.
References _checkTransaction(), App::DocumentP::activeObject, App::DocumentP::activeUndoTransaction, App::Transaction::addObjectChange(), App::Transaction::addObjectNew(), breakDependency(), App::Destroy, FC_ERR, App::DocumentObject::getFullName(), App::DocumentObject::getNameInDocument(), App::PropertyLink::getValue(), App::DocumentP::objectArray, App::DocumentP::objectIdMap, App::DocumentP::objectMap, RobotExample::pos, Recomputing, App::Remove, App::DocumentP::rollback, App::DocumentObject::setStatus(), App::PropertyLink::setValue(), App::PropertyString::setValue(), signalDeletedObject, signalTransactionRemove, testStatus(), Tip, TipName, App::DocumentP::undoing, and App::DocumentObject::unsetupObject().
Referenced by App::TransactionDocumentObject::applyDel(), and moveObject().
abortTransaction()
void Document::abortTransaction ()
Abort the actually running transaction.
Definition at line 545 of file App/Document.cpp.
References App::DocumentP::activeUndoTransaction, App::Application::closeActiveTransaction(), App::DocumentP::committing, FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, FC_WARN, App::GetApplication(), App::Transaction::getID(), and isPerformingTransaction().
Referenced by Gui::Document::abortCommand(), and PartGui::DlgProjectOnSurface::reject().
addObject() [1/2]
DocumentObject * Document::addObject (const char * sType, const char * pObjectName = nullptr, bool isNew = true, const char * viewType = nullptr, bool isPartial = false)
Add a feature of sType with sName (ASCII) to this document and set it active. Unicode names are set through the Label property.
Parameters
sType the type of created object
pObjectName if nonNULL use that name otherwise generate a new unique name based on the sType
isNew if false don't call the DocumentObject::setupObject() callback (default is true)
viewType override object's view provider name
isPartial indicate if this object is meant to be partially loaded
Definition at line 3541 of file App/Document.cpp.
References _checkTransaction(), App::DocumentP::activeObject, App::DocumentP::activeUndoTransaction, App::Transaction::addObjectDel(), Base::Persistence::getClassTypeId(), Base::Type::getTypeIfDerivedFrom(), getUniqueObjectName(), App::DocumentObject::getViewProviderNameOverride(), App::DocumentObject::Label, App::DocumentP::lastObjectId, App::New, App::DocumentP::objectArray, App::DocumentP::objectIdMap, App::DocumentP::objectMap, App::PartialObject, App::DocumentObject::pcNameInDocument, Restoring, App::DocumentP::rollback, App::DocumentObject::setDocument(), App::DocumentObject::setStatus(), App::DocumentObject::setupObject(), App::PropertyString::setValue(), signalActivatedObject, signalNewObject, signalTransactionAppend, App::DocumentP::StatusBits, Path.Post.scripts.refactored_centroid_post::str, Path.Post.scripts.grbl_post::type, and App::DocumentP::undoing.
Referenced by MeshGui::Segmentation::accept(), ReverseEngineeringGui::Segmentation::accept(), MeshGui::SegmentationBestFit::accept(), App::GroupExtension::addObject(), ArchBuildingPart.BuildingPart::autogroup(), Part::Feature::create(), ReverseEngineeringGui::SegmentationManual::createSegment(), PartGui::DlgProjectionOnSurface::DlgProjectionOnSurface(), Assembly::AssemblyLink::ensureJointGroup(), Sandbox::CustomAddObjectEvent::execute(), bimcommands.BimPanel.NestTaskPanel::getContainer(), bimcommands.BimPanel.NestTaskPanel::getShapes(), Part::ImportIgesParts(), Part::ImportStepParts(), Import::ImportOCAF2::loadShapes(), PartDesignGui::TaskFeaturePick::makeCopy(), App::LinkBaseExtension::makeCopyOnChange(), PartDesign::Body::onChanged(), readObjects(), and Restore().
addObject() [2/2]
void Document::addObject (DocumentObject * pcObject, const char * pObjectName = nullptr)
Add an existing feature with sName (ASCII) to this document and set it active. Unicode names are set through the Label property. This is an overloaded function of the function above and can be used to create a feature outside and add it to the document afterwards.
Note
The passed feature must not yet be added to a document, otherwise an exception is raised.
Definition at line 3738 of file App/Document.cpp.
References _checkTransaction(), App::DocumentP::activeObject, App::DocumentP::activeUndoTransaction, App::Transaction::addObjectDel(), App::DocumentObject::getDocument(), Base::Type::getName(), Base::Persistence::getTypeId(), getUniqueObjectName(), App::DocumentObject::getViewProviderNameOverride(), App::DocumentObject::Label, App::DocumentP::lastObjectId, App::New, App::DocumentP::objectArray, App::DocumentP::objectIdMap, App::DocumentP::objectMap, App::DocumentObject::pcNameInDocument, App::DocumentP::rollback, App::DocumentObject::setDocument(), App::DocumentObject::setStatus(), App::PropertyString::setValue(), signalActivatedObject, signalNewObject, and signalTransactionAppend.
Referenced by ArchBuildingPart.BuildingPart::autogroup(), bimcommands.BimPanel.NestTaskPanel::getContainer(), and bimcommands.BimPanel.NestTaskPanel::getShapes().
addObjects()
std::vector< DocumentObject * > Document::addObjects (const char * sType, const std::vector< std::string > & objectNames, bool isNew = true)
Add an array of features of the given types and names. Unicode names are set through the Label property.
Parameters
sType The type of created object
objectNames A list of object names
isNew If false don't call the DocumentObject::setupObject() callback (default is true)
Definition at line 3635 of file App/Document.cpp.
References _checkTransaction(), App::DocumentP::activeObject, App::DocumentP::activeUndoTransaction, App::Transaction::addObjectDel(), Path.Base.Generator.dogboneII::generate(), Base::Persistence::getClassTypeId(), Base::Tools::getIdentifier(), Base::Type::getTypeIfDerivedFrom(), Base::Tools::getUniqueName(), App::DocumentObject::getViewProviderNameOverride(), KeepTrailingDigits, App::DocumentObject::Label, App::DocumentP::lastObjectId, App::New, App::DocumentP::objectArray, App::DocumentP::objectIdMap, App::DocumentP::objectMap, importers.importIFCmulticore::objects, App::DocumentObject::pcNameInDocument, RobotExample::pos, App::DocumentP::rollback, App::DocumentObject::setDocument(), App::DocumentObject::setStatus(), App::DocumentObject::setupObject(), App::PropertyString::setValue(), signalActivatedObject, signalNewObject, signalTransactionAppend, Path.Post.scripts.refactored_centroid_post::str, testStatus(), Path.Post.scripts.grbl_post::type, and App::DocumentP::undoing.
addOrRemovePropertyOfObject()
void Document::addOrRemovePropertyOfObject (TransactionalObject * obj, Property * prop, bool add)
Definition at line 314 of file App/Document.cpp.
References _openTransaction(), App::DocumentP::activeUndoTransaction, App::Transaction::addOrRemoveProperty(), App::Application::getActiveTransaction(), App::GetApplication(), Importing, App::TransactionalObject::isAttachedToDocument(), isPerformingTransaction(), App::DocumentP::iUndoMode, Restoring, App::DocumentP::rollback, and testStatus().
Referenced by Gui::ViewProviderDocumentObject::addDynamicProperty(), and Gui::ViewProviderDocumentObject::removeDynamicProperty().
addRecomputeObject()
void Document::addRecomputeObject (DocumentObject * obj)
Called by objects during restore to ask for recompute.
Definition at line 1623 of file App/Document.cpp.
References setStatus(), testStatus(), App::DocumentObject::touch(), and App::DocumentP::touchedObjs.
addStringHasher()
std::pair< bool, int > Document::addStringHasher (const StringHasherRef & hasher) const
Called by a property during save to store its StringHasher
Parameters
hasher the input hasher
Returns
Returns a pair<bool,int>. The boolean indicates if the StringHasher has been added before. The integer is the hasher index.
The StringHasher object is designed to be shared among multiple objects. We must not save duplicate copies of the same hasher, and must be able to restore with the same sharing relationship. This function returns whether the hasher has been added before by other objects, and the index of the hasher. If the hasher has not been added before, the object must save the hasher by calling StringHasher::Save
Definition at line 1171 of file App/Document.cpp.
References App::StringHasher::clearMarks(), and App::DocumentP::hashers.
Referenced by Restore(), and Save().
afterRestore() [1/2]
bool Document::afterRestore (bool checkPartial = false)
Definition at line 2349 of file App/Document.cpp.
References FC_WARN, App::GetApplication(), getName(), App::globalIsRestoring, App::DocumentP::objectArray, Restoring, setStatus(), App::Application::signalFinishRestoreDocument, and App::Application::signalPendingReloadDocument.
Referenced by importObjects(), and restore().
afterRestore() [2/2]
bool Document::afterRestore (const std::vector< App::DocumentObject * > & objArray, bool checkPartial = false)
Definition at line 2362 of file App/Document.cpp.
References App::DocumentP::addRecomputeLog(), DepSort, SCL.SimpleDataTypes::e, App::PropertyExpressionEngine::ExecuteOnRestore, FC_ERR, FC_WARN, getDependencyList(), LinkStampChanged, App::DocumentP::objectArray, replaceobj::objs, PartialDoc, PartialRestore, setStatus(), signalFinishRestoreObject, App::DocumentObject::StdReturn, testStatus(), and App::DocumentP::touchedObjs.
breakDependency()
void Document::breakDependency (DocumentObject * pcObject, bool clear) protected
Definition at line 4022 of file App/Document.cpp.
References App::PropertyLinkBase::breakLinks(), Path.Op.Gui.Selection::clear(), and App::DocumentP::objectArray.
Referenced by _removeObject(), moveObject(), and removeObject().
checkOnCycle()
bool Document::checkOnCycle ()
checks if the graph is directed and has no cycles
Definition at line 195 of file App/Document.cpp.
References num_vertices().
clearDocument()
void Document::clearDocument ()
Definition at line 633 of file App/Document.cpp.
References App::DocumentP::activeObject, App::DocumentP::clearDocument(), App::DocumentP::clearRecomputeLog(), App::GetApplication(), App::globalIsRestoring, App::DocumentP::lastObjectId, App::DocumentP::objectArray, App::DocumentP::objectIdMap, App::DocumentP::objectMap, PartialDoc, setStatus(), App::Application::signalDeleteDocument, and App::Application::signalNewDocument.
clearUndos()
void Document::clearUndos ()
Remove all stored Undos and Redos.
Definition at line 655 of file App/Document.cpp.
References _clearRedos(), _commitTransaction(), App::DocumentP::activeUndoTransaction, App::DocumentP::committing, FC_ERR, and isPerformingTransaction().
Referenced by restore(), setUndoMode(), and ~Document().
commitTransaction()
void Document::commitTransaction ()
Commit the Command transaction. Do nothing If there is no Command transaction open.
Definition at line 497 of file App/Document.cpp.
References App::DocumentP::activeUndoTransaction, App::Application::closeActiveTransaction(), App::DocumentP::committing, FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, FC_WARN, App::GetApplication(), App::Transaction::getID(), and isPerformingTransaction().
Referenced by PartGui::Mirroring::accept(), PartGui::DlgBooleanOperation::accept(), MeshGui::Segmentation::accept(), ReverseEngineeringGui::Segmentation::accept(), PartGui::DlgRevolution::accept(), PartGui::DlgFilletEdges::accept(), MeshGui::SegmentationBestFit::accept(), PartGui::DlgProjectOnSurface::accept(), PartGui::DlgScale::apply(), PartGui::DlgExtrusion::apply(), and Gui::Document::commitCommand().
copyObject()
std::vector< DocumentObject * > Document::copyObject (const std::vector< DocumentObject * > & objs, bool recursive = false, bool returnAll = false)
Copy objects from another document to this document
Parameters
recursive if true, then all objects this object depends on are copied as well. By default recursive is false.
returnAll if true, return all copied objects including those auto included by recursive searching. If false, then only return the copied object corresponding to the input objects.
Returns
Returns the list of objects copied.
Definition at line 4029 of file App/Document.cpp.
References DepNoXLinked, DepSort, exportObjects(), getDependencyList(), App::Application::getTempFileName(), App::PropertyXLink::hasXLink(), SplineSurface::i, App::MergeDocuments::importObjects(), isSaved(), src.Mod.Test.testPathArray::o, replaceobj::objs, result, App::MergeDocuments::setVerbose(), TempDoc, and testStatus().
Referenced by moveObject().
countObjects()
int Document::countObjects () const
get the number of objects in the document
Definition at line 2553 of file App/Document.cpp.
References App::DocumentP::objectArray.
Referenced by StdCmdImport::activated(), and Gui::Application::open().
countObjectsOfType() [1/3]
template<typename T > int Document::countObjectsOfType inline
Definition at line 658 of file App/Document.h.
Referenced by PartGui::Mirroring::accept(), countObjectsOfType(), and PartDesignGui::Workbench::setupContextMenu().
countObjectsOfType() [2/3]
int Document::countObjectsOfType (const Base::Type & typeId) const protected
Definition at line 4398 of file App/Document.cpp.
References App::DocumentP::objectMap.
countObjectsOfType() [3/3]
int Document::countObjectsOfType (const char * typeName) const
Definition at line 4405 of file App/Document.cpp.
References countObjectsOfType(), Base::Type::fromName(), and Path.Post.scripts.grbl_post::type.
exportGraphviz()
void Document::exportGraphviz (std::ostream & out) const
The GraphCreator class
This class creates the dependency graph for a document.
getId returns a canonical string for a DocumentObject.
Parameters
docObj Document object to get an ID from
Returns
A string
getId returns a canonical string for an ObjectIdentifier;
Parameters
path
Returns
A string
setGraphAttributes Set graph attributes on a subgraph for a DocumentObject node.
Parameters
obj DocumentObject
setPropertyVertexAttributes Set vertex attributes for a Property node in a graph.
Parameters
g Graph
vertex Property node
name Name of node
addExpressionSubgraphIfNeeded Add a subgraph to the main graph if it is needed, i.e. there are defined at least one expression in the document object, or other objects are referencing properties in it.
Parameters
obj DocumentObject to assess.
CSSubgraphs Boolean if the GeoFeatureGroups are created as subgraphs
add Add @docObj to the graph, including all expressions (and dependencies) it includes.
Parameters
docObj The document object to add.
name Name of node.
Definition at line 75 of file Graphviz.cpp.
References toolbit-attributes::doc, SCL.SimpleDataTypes::e, App::DocumentObject::ExpressionEngine, DraftVecUtils::find(), toolbit-attributes::g, App::GetApplication(), ParameterGrp::GetBool(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), App::PropertyExpressionEngine::getExpressions(), App::ExtensionContainer::getExtensionByType(), App::DocumentObjectExtension::getExtensionClassTypeId(), App::GeoFeatureGroupExtension::getGroupOfObject(), App::GeoFeatureGroupExtension::getInvalidLinkObjects(), getName(), App::DocumentObject::getNameInDocument(), App::DocumentObject::getOutList(), App::Application::GetParameterGroupByPath(), App::PropertyString::getValue(), toolbit-attributes::group, App::ExtensionContainer::hasExtension(), SplineSurface::i, SplineSurface::id, App::DocumentObject::isAttachedToDocument(), Base::BaseClass::isDerivedFrom(), App::DocumentObject::Label, NavigationIndicatorGui::label, src.Mod.Test.testPathArray::o, importers.importIFCmulticore::objects, Init::parent, result, toolbit-attributes::s, and Path.Post.scripts.grbl_post::type.
exportObjects()
void Document::exportObjects (const std::vector< App::DocumentObject * > & obj, std::ostream & out)
Definition at line 1243 of file App/Document.cpp.
References App::Application::Config(), Base::Uuid::createUuid(), FC_LOG, FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, App::DocumentP::hashers, src.Mod.Test.testPathArray::o, App::Prop_Hidden, App::Prop_Output, Base::ZipWriter::putNextEntry(), App::PropertyUUID::setValue(), signalExportObjects, Base::ZipWriter::Stream(), Base::ZipWriter::writeFiles(), and writeObjects().
Referenced by copyObject(), and importLinks().
findObjects()
std::vector< DocumentObject * > Document::findObjects (const Base::Type & typeId, const char * objname, const char * label) const
Definition at line 4363 of file App/Document.cpp.
References App::DocumentP::objectArray.
getActiveObject()
DocumentObject * Document::getActiveObject () const
Returns the active Object of this document.
Definition at line 4230 of file App/Document.cpp.
References App::DocumentP::activeObject.
Referenced by _copyShape(), Gui::ViewProviderIndex::data(), and Gui::Command::isActiveObjectValid().
getAvailableRedoNames()
std::vector< std::string > Document::getAvailableRedoNames () const
Returns a list of the Redo names.
Definition at line 352 of file App/Document.cpp.
Referenced by Gui::Document::getRedoVector().
getAvailableRedos()
int Document::getAvailableRedos (int id = 0) const
Returns the number of stored Redos. If greater than 0 Redo will be effective.
Definition at line 715 of file App/Document.cpp.
References SplineSurface::i.
getAvailableUndoNames()
std::vector< std::string > Document::getAvailableUndoNames () const
Returns a list of the Undo names.
Definition at line 338 of file App/Document.cpp.
References App::DocumentP::activeUndoTransaction, and App::Transaction::Name.
Referenced by Gui::Document::getUndoVector().
getAvailableUndos()
int Document::getAvailableUndos (int id = 0) const
Returns the number of stored Undos. If greater than 0 Undo will be effective.
Definition at line 686 of file App/Document.cpp.
References App::DocumentP::activeUndoTransaction, App::Transaction::getID(), and SplineSurface::i.
getDependencyList()
std::vector< App::DocumentObject * > Document::getDependencyList (const std::vector< App::DocumentObject * > & objs, int options = 0) static
Get a complete list of all objects the given objects depend on.
This function is defined as static because it accepts objects from different documents, and the returned list will contain dependent objects from all relevant documents
Parameters
objs input objects to query for dependency.
options See DependencyOption
Definition at line 2736 of file App/Document.cpp.
References _buildDependencyList(), SCL.SimpleDataTypes::c, DepNoCycle, DepSort, SCL.SimpleDataTypes::e, FC_ERR, FC_THROWM, SplineSurface::i, App::DocumentP::partialTopologicalSort(), and TestSpreadsheet::v.
Referenced by StdCmdDuplicateSelection::activated(), afterRestore(), copyObject(), Gui::MainWindow::createMimeDataFromSelection(), getDependingObjects(), App::LinkBaseExtension::getOnChangeCopyObjects(), importLinks(), Import::ImportOCAF2::loadShapes(), moveObject(), recompute(), and Gui::ViewProviderLink::setupContextMenu().
getDependentDocuments() [1/2]
std::vector< App::Document * > Document::getDependentDocuments (bool sort = true)
Definition at line 2822 of file App/Document.cpp.
Referenced by Gui::Application::checkForRecomputes(), Gui::MainWindow::closeAllDocuments(), App::Application::openDocuments(), Gui::Document::save(), and Gui::Document::saveAll().
getDependentDocuments() [2/2]
std::vector< App::Document * > Document::getDependentDocuments (std::vector< App::Document * > docs, bool sort) static
Definition at line 2827 of file App/Document.cpp.
References toolbit-attributes::doc, SCL.SimpleDataTypes::e, App::PropertyXLink::getDocumentOutList(), Path.Op.Surface::msg, and TestSpreadsheet::v.
getDependingObjects()
std::vector< DocumentObject * > Document::getDependingObjects () const
Returns a list of document's objects including the dependencies.
Definition at line 4326 of file App/Document.cpp.
References getDependencyList(), and App::DocumentP::objectArray.
getErrorDescription()
const char * Document::getErrorDescription (const App::DocumentObject * Obj) const
get the text of the error of a specified object
Definition at line 3455 of file App/Document.cpp.
References App::DocumentP::findRecomputeLog().
Referenced by recompute(), PartDesignGui::ViewProviderTransformed::recomputeFeature(), and writeObjects().
getFileName()
const char * Document::getFileName () const
Returned filename
For saved document, this will be the content stored in property 'Filename'. For unsaved temporary file, this will be the content of property 'TransientDir'.
Definition at line 2507 of file App/Document.cpp.
References FileName, App::PropertyString::getValue(), TempDoc, testStatus(), and TransientDir.
Referenced by Assembly::BomObject::addObjectToBom(), and App::DocInfo::getDocPath().
getFullName()
std::string Document::getFullName () const override virtual
Reimplemented from App::PropertyContainer.
Definition at line 2497 of file App/Document.cpp.
getInList()
std::vector< App::DocumentObject * > Document::getInList (const DocumentObject * me) const
get a list of all objects linking to the given object
Definition at line 2641 of file App/Document.cpp.
References App::DocumentP::objectMap, and result.
getLinksTo()
void Document::getLinksTo (std::set< DocumentObject * > & links, const DocumentObject * obj, int options, int maxCount = 0, const std::vector< DocumentObject * > & objs = {}) const
Return the links to a given object
Parameters
links holds the links found
obj the linked object. If NULL, then all links are returned.
option
See also
App::GetLinkOption
Parameters
maxCount limit the number of links returned, 0 means no limit
objs optional objects to search for, if empty, then all objects of this document are searched.
Definition at line 2558 of file App/Document.cpp.
References App::Error, create_qrc::ext, App::GetApplication(), App::GetLinkArrayElement, App::GetLinkedObject, App::GetLinkExternal, App::GetLinkRecursive, Path.Post.scripts.opensbp_post::move(), src.Mod.Test.testPathArray::o, App::DocumentP::objectArray, and replaceobj::objs.
Referenced by hasLinksTo(), and importLinks().
getMaxUndoStackSize()
unsigned int Document::getMaxUndoStackSize () const
Set the Undo limit as stack size.
Definition at line 761 of file App/Document.cpp.
References App::DocumentP::UndoMaxStackSize.
getMemSize()
unsigned int Document::getMemSize () const override virtual
returns the complete document memory consumption, including all managed DocObjects and Undo Redo.
Implements Base::Persistence.
Definition at line 1697 of file App/Document.cpp.
References App::PropertyContainer::getMemSize(), App::StringHasher::getMemSize(), getUndoMemSize(), App::DocumentP::Hasher, and App::DocumentP::objectArray.
getName()
const char * Document::getName () const
Get the document name.
Label is the visible name of a document shown e.g. in the windows title or in the tree view. The label almost (but not always e.g. if you manually change it) matches with the file name where the document is stored to. In contrast to Label the method getName() returns the internal name of the document that only matches with Label when loading or creating a document because then both are set to the same value. Since the internal name cannot be changed during runtime it must differ from the Label after saving the document the first time or saving it under a new file name. @ note More than one document can have the same label name. @ note The internal is always guaranteed to be unique because Application::newDocument() checks for a document with the same name and makes it unique if needed. Hence you cannot rely on that the internal name matches with the name you passed to Application::newDoument(). You should use the method getName() instead.
Definition at line 2491 of file App/Document.cpp.
Referenced by _checkTransaction(), _openTransaction(), PartDesignGui::TaskShapeBinder::accept(), MeshPartGui::Tessellation::accept(), PartGui::FaceAppearances::Private::addFacesToSelection(), TechDrawGui::MDIViewPage::addSceneItemToTreeSel(), afterRestore(), App::PropertyXLinkContainer::afterRestore(), Gui::ExpressionBinding::apply(), Gui::ViewProviderVRMLObject::attach(), Gui::ViewProviderDatum::attach(), RobotGui::ViewProviderTrajectory::attach(), RobotGui::ViewProviderRobotObject::attach(), Gui::ViewProviderAnnotation::attach(), PointsGui::ViewProviderScattered::attach(), MeshGui::ViewProviderMesh::attach(), PointsGui::ViewProviderStructured::attach(), FemGui::ViewProviderFemAnalysis::checkSelectedChildren(), Gui::SelectionSingleton::checkSelection(), Gui::cmdAppObjectShow(), Gui::DAG::Model::contextMenuEvent(), App::PropertyXLink::copyTo(), TechDrawGui::TaskActiveView::createActiveView(), App::DocInfo::deinit(), dimensionMaker(), FemGui::ViewProviderFemAnalysis::doubleClicked(), AssemblyGui::ViewProviderBom::doubleClicked(), exportGraphviz(), Gui::ViewProviderGroupExtension::extensionDragObject(), PartGui::DlgScale::findShapes(), PartGui::DlgExtrusion::findShapes(), Gui::LinkInfo::getDocName(), App::PropertyLinkSubList::getPyReprString(), App::PropertyXLinkSubList::getPyReprString(), PartDesignGui::getReferencedSelection(), PartDesign::Loft::getSectionShape(), MeshPartGui::Tessellation::getStandardParameters(), Gui::SelectionSingleton::isSelected(), Gui::DAG::Model::mousePressEvent(), Spreadsheet::Sheet::observeDocument(), AssemblyGui::ViewProviderAssembly::onDelete(), Gui::Application::onLastWindowClosed(), SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsItemSelectionChanged(), SketcherGui::TaskSketcherElements::onListWidgetElementsItemPressed(), SketcherGui::TaskSketcherElements::onListWidgetElementsMouseMoveOnItem(), Gui::View3DInventor::onRename(), PartDesignGui::TaskBooleanParameters::onSelectionChanged(), SketcherGui::TaskSketcherElements::onSelectionChanged(), SketcherGui::TaskSketcherConstraints::onSelectionChanged(), Gui::Application::open(), App::Application::openDocumentPrivate(), Gui::ViewProviderT::operator=(), App::DocumentObjectT::operator=(), TechDrawGui::MDIViewPage::preSelectionChanged(), Gui::ElementColors::Private::Private(), recompute(), removeObject(), TechDrawGui::MDIViewPage::removeUnselectedTreeSelection(), App::ObjectIdentifier::resolve(), App::PropertyLinkList::Restore(), Gui::SelectionSingleton::sAddSelection(), TechDrawGui::QGSPage::saveSvg(), Gui::SelectionObject::SelectionObject(), Gui::SelectionObserver::SelectionObserver(), Gui::DocumentItem::selectItems(), Gui::Application::setActiveDocument(), Gui::View3DInventorViewer::setDocument(), ExpressionCompleterModel::setDocumentObject(), App::ObjectIdentifier::setDocumentObjectName(), TechDrawGui::ViewProviderViewPart::setEdit(), SketcherGui::ViewProviderSketch::setEditViewer(), TechDrawGui::MDIViewPage::setTreeToSceneSelect(), Gui::AutoSaver::slotCreateDocument(), Gui::SelectionSingleton::slotDeletedObject(), Gui::ElementColors::slotDeleteDocument(), Gui::AutoSaver::slotDeleteDocument(), Gui::Application::slotDeleteDocument(), Gui::DocumentItem::slotNewObject(), TechDrawGui::TaskDimRepair::slotUseSelection(), Gui::SelectionSingleton::sRemoveSelection(), Gui::SelectionSingleton::sSetPreselection(), Gui::SelectionSingleton::sUpdateSelection(), PartDesignGui::TaskFeaturePick::TaskFeaturePick(), PartDesignGui::ViewProvider::unsetEdit(), TechDraw::DrawViewCollection::unsetupObject(), PartDesign::SubShapeBinder::update(), Gui::ViewProviderInventorObject::updateData(), Gui::DocumentItem::updateItemSelection(), PartGui::DlgScale::writeParametersToFeature(), PartGui::DlgExtrusion::writeParametersToFeature(), and ~Document().
getObject()
DocumentObject * Document::getObject (const char * Name) const
Returns a Object of this document.
Definition at line 4235 of file App/Document.cpp.
References App::DocumentP::objectMap, and RobotExample::pos.
Referenced by TechDrawGui::_createLinDimension(), SpreadsheetGui::DlgBindSheet::accept(), PartGui::DlgBooleanOperation::accept(), TechDrawGui::TaskBalloon::accept(), PartDesignGui::TaskFeaturePick::buildFeatures(), Gui::View3DInventorSelection::checkGroupOnTop(), App::ObjectIdentifier::String::checkImport(), Gui::SelectionSingleton::checkSelection(), TechDrawGui::TaskActiveView::createActiveView(), TechDrawGui::TaskRichAnno::createAnnoFeature(), TechDrawGui::QGSPage::createBalloon(), TechDrawGui::TaskDetail::createDetail(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), TechDrawGui::TaskSectionView::createSectionView(), dimMaker(), PartGui::DlgExtrusion::getAxisLink(), PartGui::DlgRevolution::getAxisLink(), TechDrawGui::TaskDetail::getBaseFeat(), TechDrawGui::TaskDetail::getDetailFeat(), App::GroupExtension::getObject(), Gui::Command::getObject(), PartDesignGui::getReferencedSelection(), Gui::Document::getViewProviderByName(), PartDesign::ProfileBased::handleChangedPropertyName(), Gui::Command::hasObject(), App::ObjectIdentifier::importSubNames(), TechDrawGui::TaskSectionView::isBaseValid(), TechDrawGui::TaskComplexSection::isBaseValid(), TechDrawGui::TaskSectionView::isSectionValid(), TechDrawGui::TaskComplexSection::isSectionValid(), PartDesignGui::TaskSketchBasedParameters::onAddSelection(), PartDesignGui::TaskBooleanParameters::onSelectionChanged(), PartDesignGui::TaskTransformedParameters::originalSelected(), prepareProfileBased(), prepareTransformed(), readObjects(), PartDesignGui::TaskPipeParameters::referenceSelected(), PartDesignGui::TaskPipeScaling::referenceSelected(), PartGui::ThicknessWidget::reject(), TechDrawGui::TaskBalloon::reject(), App::ObjectIdentifier::resolve(), Restore(), App::PropertyLink::Restore(), App::PropertyLinkList::Restore(), App::PropertyLinkSub::Restore(), App::PropertyLinkSubList::Restore(), App::PropertyXLink::Restore(), Gui::SelectionSingleton::setPreselect(), UnifiedDatumCommand(), and TechDrawGui::TaskLinkDim::updateDims().
getObjectByID()
DocumentObject * Document::getObjectByID (long id) const
Returns a Object of this document by its id.
Definition at line 4247 of file App/Document.cpp.
References App::DocumentP::objectIdMap.
Referenced by App::LinkBaseExtension::extensionExecute(), and moveObject().
getObjectName()
const char * Document::getObjectName (DocumentObject * pFeat) const
Returns a Name of an Object or 0.
Definition at line 4269 of file App/Document.cpp.
References App::DocumentP::objectMap, and RobotExample::pos.
getObjects()
const std::vector< DocumentObject * > & Document::getObjects () const
Returns a list of all Objects.
Definition at line 4331 of file App/Document.cpp.
References App::DocumentP::objectArray.
Referenced by Gui::ViewProviderDocumentObject::findFrontRootOfType(), PartDesignGui::ViewProviderDatum::getRelevantBoundBox(), getStandardObjectName(), Gui::Document::getTreeRootObjects(), Gui::DAG::Model::Model(), PartGui::SectionCut::SectionCut(), Gui::TreeWidget::startItemSearch(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
getObjectsOfType() [1/2]
template<typename T > std::vector< T * > Document::getObjectsOfType inline
Returns an array with the correct types already.
Definition at line 646 of file App/Document.h.
References Path.Post.scripts.grbl_post::type.
getObjectsOfType() [2/2]
std::vector< DocumentObject * > Document::getObjectsOfType (const Base::Type & typeId) const
Definition at line 4337 of file App/Document.cpp.
References App::DocumentP::objectArray.
Referenced by _checkSelection(), _checkSelectionBalloon(), _checkSelectionHatch(), ReverseEngineeringGui::SegmentationManual::createSegment(), PartDesignGui::DlgActiveBody::DlgActiveBody(), SpreadsheetGui::DlgBindSheet::DlgBindSheet(), ReverseEngineeringGui::SegmentationManual::Private::findGeometry(), TechDrawGui::DrawGuiUtil::findPage(), PartGui::DlgScale::findShapes(), PartGui::DlgExtrusion::findShapes(), PartGui::DlgFilletEdges::findShapes(), TechDraw::DrawTemplate::getPageNumbers(), PartDesignGui::getPartFor(), TechDrawGui::DrawGuiUtil::needPage(), TechDrawGui::DrawGuiUtil::needView(), prepareProfileBased(), MeshGui::DlgEvaluateMeshImp::refreshList(), and FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary().
getObjectsWithExtension()
std::vector< DocumentObject * > Document::getObjectsWithExtension (const Base::Type & typeId, bool derived = true) const
Returns all object with given extensions. If derived=true also all objects with extensions derived from the given one
Definition at line 4348 of file App/Document.cpp.
References App::DocumentP::objectArray.
getOldLabel()
const std::string& App::Document::getOldLabel () const inline
Definition at line 553 of file App/Document.h.
Referenced by App::UpdateElementReferenceExpressionVisitor< P >::visit().
getPathsByOutList()
std::vector< std::list< App::DocumentObject * > > Document::getPathsByOutList (const App::DocumentObject * from, const App::DocumentObject * to) const
get all possible paths from one object to another following the OutList
Definition at line 4480 of file App/Document.cpp.
References draftfunctions.array::array(), DraftVecUtils::find(), App::DocumentP::findAllPathsAt(), App::DocumentObject::getOutList(), SplineSurface::i, App::DocumentP::objectArray, and src.Mod.Test.testPathArray::path.
getProgramVersion()
const char * Document::getProgramVersion () const
Get program version the project file was created with.
Definition at line 2502 of file App/Document.cpp.
References App::DocumentP::programVersion.
getPropertyData()
const App::PropertyData & Document::getPropertyData (void) const override protected virtual
Reimplemented from App::PropertyContainer.
Definition at line 169 of file App/Document.cpp.
getPropertyDataPtr()
static const App::PropertyData* App::Document::getPropertyDataPtr (void) static protected
getPyObject()
PyObject * Document::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 4411 of file App/Document.cpp.
References App::DocumentP::DocumentPythonObject, and Py::new_reference_to().
Referenced by App::Application::newDocument(), and App::Application::setActiveDocument().
getRootObjects()
std::vector< App::DocumentObject * > Document::getRootObjects () const
get all root objects (objects no other one reference too)
Definition at line 4416 of file App/Document.cpp.
References App::DocumentP::objectArray.
getRootObjectsIgnoreLinks()
std::vector< App::DocumentObject * > Document::getRootObjectsIgnoreLinks () const
get all tree root objects (objects that are at the root of the object tree)
Definition at line 4429 of file App/Document.cpp.
References App::DocumentP::objectArray.
getStandardObjectName()
std::string Document::getStandardObjectName (const char * Name, int d) const
Returns a name of the form prefix_number. d specifies the number of digits.
Definition at line 4313 of file App/Document.cpp.
References getObjects(), Base::Tools::getUniqueName(), App::ExpressionParser::labels, and AttachmentEditor.TaskAttachmentEditor::mm.
getStringHasher()
StringHasherRef Document::getStringHasher (int index = -1) const
Called by property to restore its StringHasher
Parameters
index the index previously returned by calling addStringHasher() during save. Or if is negative, then return document's own string hasher.
Returns
Return the resulting string hasher.
The caller is responsible for restoring the hasher if the caller is the first owner of the hasher, i.e. if addStringHasher() returns true during save.
Definition at line 1184 of file App/Document.cpp.
References App::PropertyBool::getValue(), App::DocumentP::Hasher, App::DocumentP::hashers, and UseHasher.
Referenced by _getTopoShape(), App::LinkBaseExtension::checkGeoElementMap(), PartDesign::Loft::execute(), Part::Thickness::execute(), getElementSource(), and PartDesign::ProfileBased::getTopoShapeVerifiedFace().
getTouched()
vector< DocumentObject * > Document::getTouched () const
returns all touched objects
Definition at line 2530 of file App/Document.cpp.
References App::DocumentP::objectArray, and result.
getTransactionID()
int Document::getTransactionID (bool undo, unsigned pos = 0) const
Return the undo/redo transaction ID starting from the back.
Definition at line 591 of file App/Document.cpp.
References App::DocumentP::activeUndoTransaction, App::Transaction::getID(), RobotExample::pos, and undo().
getTransientDirectoryName()
std::string Document::getTransientDirectoryName (const std::string & uuid, const std::string & filename) const protected
Definition at line 1013 of file App/Document.cpp.
References App::Application::applicationPid(), App::Application::getExecutableName(), and App::Application::getUserCachePath().
Referenced by onChanged().
getUndoMemSize()
unsigned int Document::getUndoMemSize () const
Returns the actual memory consumption of the Undo redo stuff.
Definition at line 746 of file App/Document.cpp.
References App::DocumentP::UndoMemSize.
Referenced by getMemSize().
getUndoMode()
int Document::getUndoMode () const
switch the level of Undo/Redo
Definition at line 741 of file App/Document.cpp.
References App::DocumentP::iUndoMode.
getUniqueObjectName()
std::string Document::getUniqueObjectName (const char * Name) const
Returns a Name of an Object or 0.
Definition at line 4280 of file App/Document.cpp.
References Base::Tools::getIdentifier(), Base::Tools::getUniqueName(), KeepTrailingDigits, femtools.tokrules::names, App::DocumentP::objectMap, RobotExample::pos, and testStatus().
Referenced by _addObject(), TechDrawGui::_createBalloon(), TechDrawGui::_createLinDimension(), PartGui::DlgRevolution::accept(), PartGui::DlgFilletEdges::accept(), addObject(), TechDraw::DrawProjGroup::addProjection(), TechDrawGui::TaskActiveView::createActiveView(), TechDrawGui::TaskRichAnno::createAnnoFeature(), TechDrawGui::QGSPage::createBalloon(), TechDrawGui::TaskDetail::createDetail(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), TechDrawGui::TaskSectionView::createSectionView(), dimMaker(), and moveObject().
hasLinksTo()
bool Document::hasLinksTo (const DocumentObject * obj) const
Check if there is any link to the given object.
Definition at line 2634 of file App/Document.cpp.
References getLinksTo().
hasPendingTransaction()
bool Document::hasPendingTransaction () const
Check if a transaction is open.
Definition at line 581 of file App/Document.cpp.
References App::DocumentP::activeUndoTransaction.
Referenced by Gui::Document::hasPendingCommand().
importLinks()
std::vector< App::DocumentObject * > Document::importLinks (const std::vector< App::DocumentObject * > & objs = {})
Import any externally linked objects
Parameters
objs input list of objects. Only objects belonging to this document will be checked for external links. And all found external linked object will be imported to this document. Link type properties of those input objects will be automatically reassigned to the imported objects. Note that the link properties of other objects in the document but not included in the input list, will not be affected even if they point to some object beining imported. To import all objects, simply pass in all objects of this document.
Returns
the list of imported objects
Definition at line 4102 of file App/Document.cpp.
References Drawing::copy(), Base::FileInfo::deleteFile(), exportObjects(), FC_ERR, getDependencyList(), App::GetLinkExternal, getLinksTo(), App::MergeDocuments::getNameMap(), App::Application::getTempFileName(), App::Property::Immutable, App::MergeDocuments::importObjects(), replaceobj::objs, App::PartialObject, Path.Post.scripts.refactored_centroid_post::str, and TestSpreadsheet::v.
importObjects()
std::vector< App::DocumentObject * > Document::importObjects (Base::XMLReader & reader)
Definition at line 1632 of file App/Document.cpp.
References afterRestore(), Base::Uuid::createUuid(), FC_LOG, App::globalIsRestoring, App::DocumentP::hashers, src.Mod.Test.testPathArray::o, App::ObjImporting, replaceobj::objs, App::Prop_Hidden, App::Prop_Output, TechDrawTools.TaskFillTemplateFields::reader, readObjects(), App::PropertyUUID::setValue(), signalFinishImportObjects, and signalImportObjects.
Referenced by Gui::MergeDocuments::importObjects(), and App::MergeDocuments::importObjects().
isAnyRestoring()
bool Document::isAnyRestoring () static
Indicate if there is any document restoring/importing.
Definition at line 2253 of file App/Document.cpp.
References App::globalIsRestoring.
Referenced by App::Application::isRestoring(), Gui::ViewProviderDocumentObject::onPropertyStatusChanged(), App::LinkBaseExtension::setLink(), and App::LinkBaseExtension::update().
isClosable()
bool Document::isClosable () const
check whether the document can be closed
Definition at line 2548 of file App/Document.cpp.
References Closable, and testStatus().
isExporting()
Document::ExportStatus Document::isExporting (const App::DocumentObject * obj) const
Definition at line 1234 of file App/Document.cpp.
References _ExportStatus, NotExporting, DocExportStatus::objs, and DocExportStatus::status.
Referenced by writeObjects().
isIn()
bool Document::isIn (const DocumentObject * pFeat) const
Returns true if the DocumentObject is contained in this document.
Definition at line 4258 of file App/Document.cpp.
References App::DocumentP::objectMap, and RobotExample::pos.
Referenced by PartDesignGui::ComboLinks::getLink().
isPerformingTransaction()
bool Document::isPerformingTransaction () const
returns true if the document is in an Transaction phase, e.g. currently performing a redo/undo or rollback
Definition at line 333 of file App/Document.cpp.
References App::DocumentP::rollback, and App::DocumentP::undoing.
Referenced by _abortTransaction(), _checkTransaction(), _clearRedos(), _commitTransaction(), _openTransaction(), abortTransaction(), addOrRemovePropertyOfObject(), clearUndos(), commitTransaction(), and openTransaction().
isSaved()
bool Document::isSaved () const
Opens the document from its file name.
Is the document already saved to a file?
Definition at line 2472 of file App/Document.cpp.
References FileName, and App::PropertyString::getValue().
Referenced by copyObject(), Import::ImportOCAF2::ImportOCAF2(), Gui::Document::save(), and Import::ImportOCAF2::setMode().
isTouched()
bool Document::isTouched () const
check if there is any touched object in this document
Definition at line 2520 of file App/Document.cpp.
References App::DocumentP::objectArray.
isTransactionEmpty()
bool Document::isTransactionEmpty () const
Check if a transaction is open and its list is empty. If no transaction is open true is returned.
Definition at line 617 of file App/Document.cpp.
References App::DocumentP::activeUndoTransaction.
moveObject()
DocumentObject * Document::moveObject (DocumentObject * obj, bool recursive = false)
Move an object from another document to this document If recursive is true then all objects this object depends on are moved as well. By default recursive is false. Returns the moved object itself or 0 if the object is already part of this document..
Definition at line 4173 of file App/Document.cpp.
References _addObject(), _removeObject(), breakDependency(), copyObject(), DepNoXLinked, DepSort, getDependencyList(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), getObjectByID(), getUniqueObjectName(), App::DocumentP::iUndoMode, src.Mod.Test.testPathArray::o, replaceobj::objs, removeObject(), App::DocumentP::rollback, and App::DocumentObject::setDocument().
mustExecute()
bool Document::mustExecute () const
check if there is any object must execute in this document
Definition at line 4527 of file App/Document.cpp.
References _buildDependencyList(), App::PropertyXLink::hasXLink(), and App::DocumentP::objectArray.
Referenced by StdCmdRefresh::isActive(), recompute(), and Gui::Document::save().
onBeforeChange()
void Document::onBeforeChange (const Property *) override protected virtual
get called before the value is changed
Reimplemented from App::PropertyContainer.
Definition at line 766 of file App/Document.cpp.
References App::PropertyString::getValue(), Label, and signalBeforeChange.
onBeforeChangeProperty()
void Document::onBeforeChangeProperty (const TransactionalObject * Who, const Property * What) protected
callback from the Document objects before property will be changed
Definition at line 836 of file App/Document.cpp.
References _checkTransaction(), App::DocumentP::activeUndoTransaction, App::Transaction::addObjectChange(), Base::Persistence::getClassTypeId(), App::globalIsRelabeling, Base::BaseClass::isDerivedFrom(), App::DocumentP::rollback, and signalBeforeChangeObject.
onChanged()
void Document::onChanged (const Property *) override protected virtual
get called by the container when a property has changed
Reimplemented from App::PropertyContainer.
Definition at line 774 of file App/Document.cpp.
References Base::Console(), Base::FileInfo::createDirectories(), App::DocumentObject::enforceRecompute(), Base::FileInfo::exists(), Base::FileInfo::filePath(), App::GetApplication(), App::PropertyString::getStrValue(), getTransientDirectoryName(), App::PropertyUUID::getValueStr(), App::globalIsRelabeling, SplineSurface::id, Label, App::DocumentP::objectArray, Base::FileInfo::renameFile(), App::PropertyString::setValue(), App::PropertyUUID::setValue(), ShowHidden, signalChanged, App::Application::signalRelabelDocument, App::Application::signalShowHidden, TransientDir, Uid, UseHasher, and Base::ConsoleSingleton::Warning().
Referenced by draftviewproviders.view_base.ViewProviderDraft::attach(), ArchSpace._ViewProviderSpace::onChanged(), ArchSchedule._ArchSchedule::setProperties(), draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy::updateData(), draftviewproviders.view_layer.ViewProviderLayer::updateData(), draftviewproviders.view_label.ViewProviderLabel::updateData(), ArchAxis._ViewProviderAxis::updateData(), draftviewproviders.view_dimension.ViewProviderLinearDimension::updateData(), ArchSpace._ViewProviderSpace::updateData(), ArchBuildingPart.ViewProviderBuildingPart::updateData(), ArchPanel.ViewProviderPanelCut::updateData(), ArchSite._ViewProviderSite::updateData(), ArchSectionPlane._ViewProviderSectionPlane::updateData(), and ArchPanel.ViewProviderPanelSheet::updateData().
onChangedProperty()
void Document::onChangedProperty (const DocumentObject * Who, const Property * What) protected
callback from the Document objects after property was changed
Definition at line 849 of file App/Document.cpp.
References signalChangedObject.
openTransaction()
void Document::openTransaction (const char * name = nullptr)
Open a new command Undo/Redo, an UTF-8 name can be specified
Parameters
name transaction name
This function calls App::Application::setActiveTransaction(name) instead to setup a potential transaction which will only be created if there is actual changes.
Definition at line 363 of file App/Document.cpp.
References App::DocumentP::committing, FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, FC_WARN, App::GetApplication(), isPerformingTransaction(), and App::Application::setActiveTransaction().
Referenced by PartGui::Mirroring::accept(), PartGui::DlgBooleanOperation::accept(), MeshGui::Segmentation::accept(), ReverseEngineeringGui::Segmentation::accept(), PartGui::DlgRevolution::accept(), PartGui::DlgFilletEdges::accept(), MeshGui::SegmentationBestFit::accept(), PartGui::DlgScale::apply(), PartGui::DlgExtrusion::apply(), PartGui::DlgProjectionOnSurface::DlgProjectionOnSurface(), PartDesignGui::getReferencedSelection(), and Gui::Document::openCommand().
purgeTouched()
void Document::purgeTouched ()
Remove all modifications. After this call The document becomes Valid again.
Remove all modifications. After this call The document becomes valid again.
Definition at line 2513 of file App/Document.cpp.
References App::DocumentP::objectArray.
readObjects()
std::vector< App::DocumentObject * > Document::readObjects (Base::XMLReader & reader) protected
Definition at line 1430 of file App/Document.cpp.
References _loadDeps(), addObject(), App::DocumentP::addRecomputeLog(), Base::Console(), SCL.SimpleDataTypes::e, App::Error, Base::ConsoleSingleton::Error(), FC_ATTR_DEP_ALLOW_PARTIAL, FC_ATTR_DEP_COUNT, FC_ATTR_DEP_OBJ_NAME, FC_ATTR_DEPENDENCIES, FC_ELEMENT_OBJECT_DEP, FC_ELEMENT_OBJECT_DEPS, FC_TRACE, App::DocumentObject::getFullName(), App::DocumentObject::getNameInDocument(), getObject(), SplineSurface::i, Path.Log::info(), App::DocumentObject::isError(), KeepTrailingDigits, App::DocumentP::lastObjectId, replaceobj::objs, PartialDoc, App::DocumentP::partialLoadObjects, App::PartialObject, RobotExample::pos, TechDrawTools.TaskFillTemplateFields::reader, App::Restore, App::ExtensionContainer::Restore(), App::DocumentObject::setStatus(), setStatus(), App::DocumentObject::testStatus(), testStatus(), App::DocumentP::touchedObjs, Path.Post.scripts.grbl_post::type, and TestSpreadsheet::v.
Referenced by importObjects(), and Restore().
recompute()
int Document::recompute (const std::vector< App::DocumentObject * > & objs = {}, bool force = false, bool * hasError = nullptr, int options = 0)
Recompute touched features and return the number of recalculated features
Parameters
objs specify a sub set of objects to recompute. If empty, then all object in this document is checked for recompute
Definition at line 3083 of file App/Document.cpp.
References _recomputeFeature(), App::DocumentP::_RecomputeLog, App::DocumentP::clearRecomputeLog(), Base::Console(), DepSort, toolbit-attributes::doc, SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), FC_ERR, FC_LOG, FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, FC_TIME_INIT, FC_TIME_LOG, FC_WARN, App::GetApplication(), ParameterGrp::GetBool(), getDependencyList(), getErrorDescription(), getName(), App::Application::GetParameterGroupByPath(), App::PropertyString::getValue(), SplineSurface::i, Label, mustExecute(), src.Mod.Test.testPathArray::o, App::DocumentP::objectArray, replaceobj::objs, PartialDoc, App::DocumentP::partialTopologicalSort(), App::PendingRecompute, App::Recompute2, Recomputing, App::DocumentP::rollback, signalBeforeRecompute, signalRecomputed, signalRecomputedObject, signalSkipRecompute, SkipRecompute, InitGui::t, src.Mod.PartDesign.Scripts.Gear::t2, testStatus(), topologicalSort(), and App::DocumentP::undoing.
Referenced by PartGui::Mirroring::accept(), PartGui::DlgBooleanOperation::accept(), Gui::Dialog::DlgMacroExecuteImp::accept(), PartGui::DlgRevolution::accept(), PartGui::DlgFilletEdges::accept(), Gui::TaskCSysDragger::accept(), Gui::MacroCommand::activated(), Gui::RecentMacrosAction::activateFile(), Sandbox::CustomRecomputeEvent::execute(), Gui::ManualAlignment::finish(), SpreadsheetGui::SheetTableView::pasteClipboard(), FemGui::TaskDlgPost::recompute(), recomputeFeature(), TechDrawGui::TaskGeomHatch::reject(), Gui::TaskCSysDragger::reject(), draftguitools.gui_trackers.arcTracker::setApertureAngle(), draftguitools.gui_trackers.arcTracker::setEndAngle(), draftguitools.gui_trackers.arcTracker::setStartAngle(), draftguitools.gui_trackers.bsplineTracker::update(), and draftguitools.gui_trackers.bezcurveTracker::update().
recomputeFeature()
bool Document::recomputeFeature (DocumentObject * Feat, bool recursive = false)
Recompute only one feature.
Definition at line 3518 of file App/Document.cpp.
References _recomputeFeature(), App::DocumentP::clearRecomputeLog(), App::DocumentObject::isAttachedToDocument(), App::DocumentObject::isValid(), recompute(), and signalRecomputedObject.
Referenced by PartDesignGui::TaskBooleanParameters::onSelectionChanged(), TechDrawGui::TaskBalloon::recomputeFeature(), TechDrawGui::TaskDimension::recomputeFeature(), TechDrawGui::TaskLeaderLine::recomputeFeature(), and PartDesignGui::TaskFeatureParameters::recomputeFeature().
redo()
bool Document::redo (int id = 0)
Will REDO one step, returns False if no redo was done (Redos == 0).
Definition at line 263 of file App/Document.cpp.
References _commitTransaction(), App::DocumentP::activeUndoTransaction, App::Transaction::getID(), App::DocumentP::iUndoMode, App::Transaction::Name, App::DocumentP::objectArray, App::PendingTransactionUpdate, signalRedo, Transaction, and App::DocumentP::undoing.
Referenced by Gui::Document::redo().
removeObject()
void Document::removeObject (const char * sName)
Remove a feature out of the document.
Remove an object out of the document.
Definition at line 3836 of file App/Document.cpp.
References _checkTransaction(), App::DocumentP::activeObject, App::DocumentP::activeUndoTransaction, App::Transaction::addObjectNew(), breakDependency(), App::Destroy, FC_MSG, getName(), App::DocumentObject::getNameInDocument(), App::PropertyLink::getValue(), App::DocumentP::objectArray, App::DocumentP::objectIdMap, App::DocumentP::objectMap, App::PendingRecompute, App::DocumentP::pendingRemove, RobotExample::pos, App::Remove, App::DocumentP::rollback, App::PropertyLink::setValue(), App::PropertyString::setValue(), signalDeletedObject, signalTransactionRemove, Tip, TipName, and App::DocumentP::undoing.
Referenced by App::GroupExtension::addObject(), PartDesign::SubShapeBinder::clearCopiedObjects(), App::LinkBaseExtension::detachElement(), Assembly::AssemblyLink::ensureNoJointGroup(), Sandbox::CustomRemoveObjectEvent::execute(), Assembly::AssemblyObject::getJoints(), moveObject(), App::OriginGroupExtension::onExtendedUnsetupObject(), and TechDraw::DrawProjGroup::removeProjection().
renameObjectIdentifiers()
void Document::renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > & paths, const std::function< bool(const App::DocumentObject *)> & selector = [](const App::DocumentObject*) { return true; })
Function called to signal that an object identifier has been renamed.
Signal that object identifiers, typically a property or document object has been renamed.
This function iterates through all document object in the document, and calls its renameObjectIdentifiers functions.
Parameters
paths Map with current and new names
Definition at line 2914 of file App/Document.cpp.
References App::DocumentP::objectArray.
Referenced by Spreadsheet::PropertySheet::insertColumns(), Spreadsheet::PropertySheet::insertRows(), Spreadsheet::PropertySheet::removeColumns(), Spreadsheet::PropertySheet::removeRows(), and Spreadsheet::PropertySheet::setAlias().
renameTransaction()
void Document::renameTransaction (const char * name, int id)
Rename the current transaction if the id matches.
Definition at line 425 of file App/Document.cpp.
References App::DocumentP::activeUndoTransaction, App::Transaction::getID(), and App::Transaction::Name.
Restore()
void Document::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 1064 of file App/Document.cpp.
References addObject(), addStringHasher(), App::StringHasher::clear(), Base::Console(), FileName, getObject(), App::PropertyString::getValue(), App::DocumentP::Hasher, App::DocumentP::hashers, SplineSurface::i, Label, Base::ConsoleSingleton::Message(), PartialDoc, TechDrawTools.TaskFillTemplateFields::reader, readObjects(), App::Restore, App::ExtensionContainer::Restore(), App::PropertyContainer::Restore(), App::StringHasher::Restore(), App::DocumentObject::setStatus(), setStatus(), App::PropertyLink::setValue(), App::PropertyString::setValue(), Tip, TipName, App::DocumentP::touchedObjs, and Path.Post.scripts.grbl_post::type.
Referenced by restore().
restore()
void Document::restore (const char * filename = nullptr, bool delaySignal = false, const std::vector< std::string > & objNames = {})
Restore the document from the file in Property Path.
Definition at line 2259 of file App/Document.cpp.
References App::DocumentP::activeObject, afterRestore(), App::DocumentP::checkStringHasher(), App::DocumentP::clearDocument(), App::DocumentP::clearRecomputeLog(), clearUndos(), Base::Console(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), DrawingExample::file, FileName, App::Application::getActiveDocument(), App::GetApplication(), App::PropertyString::getValue(), App::globalIsRestoring, App::DocumentP::lastObjectId, App::DocumentP::objectArray, App::DocumentP::objectIdMap, App::DocumentP::objectMap, PartialDoc, App::DocumentP::partialLoadObjects, PartialRestore, App::DocumentP::programVersion, TechDrawTools.TaskFillTemplateFields::reader, Restore(), RestoreError, Restoring, App::Application::setActiveDocument(), setStatus(), App::Application::signalDeleteDocument, App::Application::signalNewDocument, signalRestoreDocument, and App::Application::signalStartRestoreDocument.
Referenced by src.Mod.Show.mTempoVis.TempoVis::__del__(), and App::Application::openDocumentPrivate().
save()
bool Document::save ()
Save the Document under a new Name.
Save the document to the file in Property Path
Definition at line 1764 of file App/Document.cpp.
References Base::Tools::currentDateTimeString(), FC_ERR, FileName, App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetBool(), App::DocumentObject::getNameInDocument(), App::Application::GetParameterGroupByPath(), App::PropertyLink::getValue(), App::PropertyString::getValue(), Label, LastModifiedBy, LastModifiedDate, PartialDoc, saveToFile(), App::PropertyString::setValue(), testStatus(), Tip, and TipName.
Referenced by src.Mod.Show.mTempoVis.TempoVis::modify(), src.Mod.Show.mTempoVis.TempoVis::modifyVPProperty(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle(), saveAs(), src.Mod.Show.mTempoVis.TempoVis::saveCamera(), and nativeifc.ifc_viewproviders.ifc_vp_document::setupContextMenu().
Save()
void Document::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 1034 of file App/Document.cpp.
References addStringHasher(), App::PropertyContainer::beforeSave(), App::Application::Config(), Base::Writer::decInd(), Base::Writer::getFileVersion(), App::DocumentP::Hasher, App::DocumentP::hashers, Base::Writer::incInd(), src.Mod.Test.testPathArray::o, App::DocumentP::objectArray, App::PropertyContainer::Save(), App::StringHasher::Save(), App::StringHasher::setPersistenceFileName(), Base::Writer::Stream(), and writeObjects().
Referenced by Sandbox::DocumentSaverThread::run(), and saveToFile().
saveAs()
bool Document::saveAs (const char * file)
Definition at line 1740 of file App/Document.cpp.
References checkFileName(), DrawingExample::file, FileName, Base::FileInfo::fileNamePure(), App::PropertyString::getStrValue(), Label, save(), App::PropertyString::setValue(), App::Property::touch(), and Uid.
saveCopy()
bool Document::saveCopy (const char * file) const
Definition at line 1753 of file App/Document.cpp.
References checkFileName(), DrawingExample::file, FileName, App::PropertyString::getStrValue(), result, and saveToFile().
saveToFile()
bool Document::saveToFile (const char * filename) const protected
Definition at line 2122 of file App/Document.cpp.
References App::BackupPolicy::apply(), Base::Uuid::createUuid(), DrawingExample::file, App::GetApplication(), ParameterGrp::GetASCII(), ParameterGrp::GetBool(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), Base::Writer::hasErrors(), src.Mod.Test.testPathArray::path, Base::ZipWriter::putNextEntry(), Save(), Base::ZipWriter::setComment(), App::BackupPolicy::setDateFormat(), Base::ZipWriter::setLevel(), Base::Writer::setMode(), App::BackupPolicy::setNumberOfFiles(), App::BackupPolicy::setPolicy(), signalFinishSave, signalSaveDocument, App::Application::signalSaveDocument, signalStartSave, App::BackupPolicy::Standard, Base::ZipWriter::Stream(), App::BackupPolicy::TimeStamp, App::BackupPolicy::useBackupExtension(), and Base::ZipWriter::writeFiles().
Referenced by save(), and saveCopy().
setClosable()
void Document::setClosable (bool c)
set the document to be closable, this is on by default.
Definition at line 2543 of file App/Document.cpp.
References SCL.SimpleDataTypes::c, Closable, and setStatus().
setMaxUndoStackSize()
void Document::setMaxUndoStackSize (unsigned int UndoMaxStackSize = 20)
Set the Undo limit as stack size.
Definition at line 756 of file App/Document.cpp.
References App::DocumentP::UndoMaxStackSize.
Referenced by Gui::Document::Document().
setStatus()
void Document::setStatus (Status pos, bool on)
set the status bits
Definition at line 176 of file App/Document.cpp.
References RobotExample::pos, and App::DocumentP::StatusBits.
Referenced by addRecomputeObject(), afterRestore(), clearDocument(), readObjects(), restore(), Restore(), and setClosable().
setTransactionMode()
void Document::setTransactionMode (int iMode)
switch the transaction mode
Definition at line 854 of file App/Document.cpp.
References App::DocumentP::iTransactionMode.
setUndoLimit()
void Document::setUndoLimit (unsigned int UndoMemSize = 0)
Set the Undo limit in Byte!
Definition at line 751 of file App/Document.cpp.
References App::DocumentP::UndoMemSize.
setUndoMode()
void Document::setUndoMode (int iMode)
switch the level of Undo/Redo
Definition at line 732 of file App/Document.cpp.
References clearUndos(), and App::DocumentP::iUndoMode.
Referenced by Gui::Document::Document(), and PartDesign::SubShapeBinder::update().
testStatus()
bool Document::testStatus (Status pos) const
return the status bits
Definition at line 171 of file App/Document.cpp.
References RobotExample::pos.
Referenced by _checkTransaction(), _removeObject(), addObjects(), addOrRemovePropertyOfObject(), addRecomputeObject(), afterRestore(), copyObject(), App::OriginGroupExtension::extensionOnChanged(), getFileName(), getUniqueObjectName(), isClosable(), readObjects(), recompute(), save(), and Gui::DocumentItem::slotExpandObject().
topologicalSort()
std::vector< App::DocumentObject * > Document::topologicalSort () const
get a list of topological sorted objects (https://en.wikipedia.org/wiki/Topological_sorting)
Definition at line 3450 of file App/Document.cpp.
References App::DocumentP::objectArray, and App::DocumentP::topologicalSort().
Referenced by recompute().
undo()
bool Document::undo (int id = 0)
Will UNDO one step, returns False if no undo was done (Undos == 0).
Definition at line 208 of file App/Document.cpp.
References _commitTransaction(), App::DocumentP::activeUndoTransaction, App::Transaction::getID(), App::DocumentP::iUndoMode, App::Transaction::Name, App::DocumentP::objectArray, App::PendingTransactionUpdate, signalUndo, Transaction, and App::DocumentP::undoing.
Referenced by getTransactionID(), and Gui::Document::undo().
writeDependencyGraphViz()
void Document::writeDependencyGraphViz (std::ostream & out)
write GraphViz file
Definition at line 41 of file Graphviz.cpp.
writeObjects()
void Document::writeObjects (const std::vector< App::DocumentObject * > & obj, Base::Writer & writer) const protected
Definition at line 1297 of file App/Document.cpp.
References Base::Writer::decInd(), Base::Persistence::encodeAttribute(), App::Error, FC_ATTR_DEP_ALLOW_PARTIAL, FC_ATTR_DEP_COUNT, FC_ATTR_DEP_OBJ_NAME, FC_ATTR_DEPENDENCIES, FC_ELEMENT_OBJECT_DEP, FC_ELEMENT_OBJECT_DEPS, getErrorDescription(), Base::Writer::incInd(), Base::Writer::ind(), isExporting(), src.Mod.Test.testPathArray::o, App::DocumentObject::OutListNoHidden, App::DocumentObject::OutListNoXLinked, Base::Writer::Stream(), and App::Touch.
Referenced by exportObjects(), and Save().
Friends And Related Function Documentation
Application
friend class Application friend
Definition at line 573 of file App/Document.h.
DocumentObject
friend class DocumentObject friend
The DocumentObject that will own the expression
Definition at line 576 of file App/Document.h.
Transaction
friend class Transaction friend
Definition at line 577 of file App/Document.h.
Referenced by _openTransaction(), redo(), and undo().
TransactionalObject
friend class TransactionalObject friend
because of transaction handling
Definition at line 575 of file App/Document.h.
TransactionDocumentObject
friend class TransactionDocumentObject friend
Definition at line 578 of file App/Document.h.
Member Data Documentation
Comment
PropertyString App::Document::Comment
long comment or description (UTF8 with line breaks)
Definition at line 102 of file App/Document.h.
Referenced by Gui::Dialog::DlgProjectInformationImp::accept(), and Document().
Company
PropertyString App::Document::Company
company name UTF8(optional)
Definition at line 98 of file App/Document.h.
Referenced by Gui::Dialog::DlgProjectInformationImp::accept(), and Document().
CreatedBy
PropertyString App::Document::CreatedBy
creators name (utf-8)
Definition at line 92 of file App/Document.h.
Referenced by Gui::Dialog::DlgProjectInformationImp::accept(), and Document().
CreationDate
PropertyString App::Document::CreationDate
Definition at line 93 of file App/Document.h.
Referenced by Document().
FileName
PropertyString App::Document::FileName
full qualified (with path) file name (utf-8 coded)
Definition at line 90 of file App/Document.h.
Referenced by Document(), getFileName(), Import::ImportOCAF2::ImportOCAF2(), isSaved(), App::Application::openDocumentPrivate(), restore(), Restore(), Gui::Document::Save(), save(), Gui::Document::saveAs(), saveAs(), saveCopy(), and Import::ImportOCAF2::setMode().
Id
PropertyString App::Document::Id
Id e.g. Part number.
Definition at line 104 of file App/Document.h.
Referenced by Document().
Label
PropertyString App::Document::Label
holds the long name of the document (utf-8 coded)
Definition at line 88 of file App/Document.h.
Referenced by App::PropertyXLinkContainer::afterRestore(), Gui::Document::canClose(), Gui::Document::createView(), Document(), PartGui::DlgScale::findShapes(), PartGui::DlgExtrusion::findShapes(), App::Application::newDocument(), onBeforeChange(), onChanged(), Gui::MDIView::onRelabel(), DrawingGui::DrawingView::onRelabel(), recompute(), Restore(), save(), saveAs(), Gui::DocumentItem::setData(), App::ObjectIdentifier::setDocumentObjectName(), and App::UpdateElementReferenceExpressionVisitor< P >::visit().
LastModifiedBy
PropertyString App::Document::LastModifiedBy
user last modified the document
Definition at line 95 of file App/Document.h.
Referenced by Gui::Dialog::DlgProjectInformationImp::accept(), Document(), and save().
LastModifiedDate
PropertyString App::Document::LastModifiedDate
Definition at line 96 of file App/Document.h.
Referenced by Document(), and save().
License
App::PropertyString App::Document::License
Full name of the licence e.g. "Creative Commons Attribution". See https://spdx.org/licenses/.
Definition at line 108 of file App/Document.h.
Referenced by Gui::Dialog::DlgProjectInformationImp::accept(), and Document().
LicenseURL
App::PropertyString App::Document::LicenseURL
License description/contract URL.
Definition at line 110 of file App/Document.h.
Referenced by Gui::Dialog::DlgProjectInformationImp::accept(), and Document().
Material
App::PropertyMap App::Document::Material
Material descriptions, used and defined in the Material module.
Definition at line 114 of file App/Document.h.
Meta
App::PropertyMap App::Document::Meta
Meta descriptions.
Definition at line 112 of file App/Document.h.
Referenced by Document().
ShowHidden
PropertyBool App::Document::ShowHidden
Whether to show hidden items in TreeView.
Definition at line 122 of file App/Document.h.
Referenced by Document(), onChanged(), Gui::DocumentItem::setShowHidden(), and Gui::DocumentItem::showHidden().
signalAbortTransaction
boost::signals2::signal<void(const App::Document&)> App::Document::signalAbortTransaction
Definition at line 181 of file App/Document.h.
Referenced by _abortTransaction(), and App::Application::newDocument().
signalActivatedObject
boost::signals2::signal<void(const App::DocumentObject&)> App::Document::signalActivatedObject
signal on activated Object
Definition at line 147 of file App/Document.h.
Referenced by _addObject(), addObject(), addObjects(), Gui::Document::Document(), and App::Application::newDocument().
signalBeforeChange
boost::signals2::signal<void(const App::Document&, const App::Property&)> App::Document::signalBeforeChange
signal before changing an doc property
Definition at line 131 of file App/Document.h.
Referenced by App::Application::newDocument(), and onBeforeChange().
signalBeforeChangeObject
boost::signals2::signal<void(const App::DocumentObject&, const App::Property&)> App::Document::signalBeforeChangeObject
signal before changing an Object
Definition at line 139 of file App/Document.h.
Referenced by App::Application::newDocument(), and onBeforeChangeProperty().
signalBeforeRecompute
boost::signals2::signal<void(const App::Document&)> App::Document::signalBeforeRecompute
Definition at line 173 of file App/Document.h.
Referenced by App::Application::newDocument(), and recompute().
signalChanged
boost::signals2::signal<void(const App::Document&, const App::Property&)> App::Document::signalChanged
signal on changed doc property
Definition at line 133 of file App/Document.h.
Referenced by Gui::Document::Document(), App::Application::newDocument(), and onChanged().
signalChangedObject
boost::signals2::signal<void(const App::DocumentObject&, const App::Property&)> App::Document::signalChangedObject
signal on changed Object
Definition at line 141 of file App/Document.h.
Referenced by App::DocumentObserver::attachDocument(), Gui::Document::Document(), App::Application::newDocument(), onChangedProperty(), and FemGui::FunctionWidget::setViewProvider().
signalChangePropertyEditor
boost::signals2::signal<void(const App::Document&, const App::Property&)> App::Document::signalChangePropertyEditor
Definition at line 184 of file App/Document.h.
Referenced by Gui::Document::Document(), App::Application::newDocument(), and Gui::ViewProviderDocumentObject::onPropertyStatusChanged().
signalCommitTransaction
boost::signals2::signal<void(const App::Document&)> App::Document::signalCommitTransaction
Definition at line 179 of file App/Document.h.
Referenced by _commitTransaction(), and App::Application::newDocument().
signalDeletedObject
boost::signals2::signal<void(const App::DocumentObject&)> App::Document::signalDeletedObject
signal on deleted Object
Definition at line 137 of file App/Document.h.
Referenced by _removeObject(), App::DocumentObserver::attachDocument(), Gui::Document::Document(), TechDrawGui::MDIViewPage::MDIViewPage(), App::Application::newDocument(), and removeObject().
signalExportObjects
boost::signals2::signal<void(const std::vector<App::DocumentObject*>&, Base::Writer&)> App::Document::signalExportObjects
Definition at line 163 of file App/Document.h.
Referenced by exportObjects().
signalExportViewObjects
boost::signals2::signal<void(const std::vector<App::DocumentObject*>&, Base::Writer&)> App::Document::signalExportViewObjects
Definition at line 164 of file App/Document.h.
Referenced by Gui::Document::Document(), and App::MergeDocuments::SaveDocFile().
signalFinishImportObjects
boost::signals2::signal<void(const std::vector<App::DocumentObject*>&)> App::Document::signalFinishImportObjects
Definition at line 168 of file App/Document.h.
Referenced by Gui::Document::Document(), and importObjects().
signalFinishRestoreObject
boost::signals2::signal<void(const App::DocumentObject&)> App::Document::signalFinishRestoreObject
Definition at line 183 of file App/Document.h.
Referenced by afterRestore(), and Gui::Document::Document().
signalFinishSave
boost::signals2::signal<void(const App::Document&, const std::string&)> App::Document::signalFinishSave
Definition at line 172 of file App/Document.h.
Referenced by App::Application::newDocument(), and saveToFile().
signalImportObjects
boost::signals2::signal<void(const std::vector<App::DocumentObject*>&, Base::XMLReader&)> App::Document::signalImportObjects
Definition at line 165 of file App/Document.h.
Referenced by importObjects().
signalImportViewObjects
boost::signals2::signal<void(const std::vector<App::DocumentObject*>&, Base::Reader&, const std::map<std::string, std::string>&)> App::Document::signalImportViewObjects
Definition at line 167 of file App/Document.h.
Referenced by Gui::Document::Document(), and App::MergeDocuments::RestoreDocFile().
signalLinkXsetValue
boost::signals2::signal<void(std::string)> App::Document::signalLinkXsetValue
Definition at line 185 of file App/Document.h.
signalNewObject
boost::signals2::signal<void(const App::DocumentObject&)> App::Document::signalNewObject
signal on new Object
Definition at line 135 of file App/Document.h.
Referenced by _addObject(), addObject(), addObjects(), App::DocumentObserver::attachDocument(), Gui::Document::Document(), and App::Application::newDocument().
signalOpenTransaction
boost::signals2::signal<void(const App::Document&, std::string)> App::Document::signalOpenTransaction
Definition at line 177 of file App/Document.h.
Referenced by _openTransaction(), and App::Application::newDocument().
signalRecomputed
boost::signals2::signal<void(const App::Document&, const std::vector<App::DocumentObject*>&)> App::Document::signalRecomputed
Definition at line 174 of file App/Document.h.
Referenced by App::DocumentObserver::attachDocument(), Gui::Document::Document(), Gui::GraphvizView::GraphvizView(), App::Application::newDocument(), and recompute().
signalRecomputedObject
boost::signals2::signal<void(const App::DocumentObject&)> App::Document::signalRecomputedObject
Definition at line 175 of file App/Document.h.
Referenced by App::DocumentObserver::attachDocument(), App::Application::newDocument(), PartDesign::SubShapeBinder::onChanged(), recompute(), and recomputeFeature().
signalRedo
boost::signals2::signal<void(const App::Document&)> App::Document::signalRedo
signal on redo
Definition at line 155 of file App/Document.h.
Referenced by Gui::Document::Document(), Gui::GraphvizView::GraphvizView(), App::Application::newDocument(), and redo().
signalRelabelObject
boost::signals2::signal<void(const App::DocumentObject&)> App::Document::signalRelabelObject
signal on relabeled Object
Definition at line 145 of file App/Document.h.
Referenced by Gui::Document::Document(), and App::Application::newDocument().
signalRestoreDocument
boost::signals2::signal<void(Base::XMLReader&)> App::Document::signalRestoreDocument
Definition at line 162 of file App/Document.h.
Referenced by Gui::Document::Document(), and restore().
signalSaveDocument
boost::signals2::signal<void(Base::Writer&)> App::Document::signalSaveDocument
signal on load/save document this signal is given when the document gets streamed. you can use this hook to write additional information in the file (like the Gui::Document does).
Definition at line 161 of file App/Document.h.
Referenced by Gui::Document::Document(), Sandbox::DocumentSaverThread::run(), and saveToFile().
signalSkipRecompute
boost::signals2::signal<void(const App::Document&, const std::vector<App::DocumentObject*>&)> App::Document::signalSkipRecompute
Definition at line 182 of file App/Document.h.
Referenced by Gui::Document::Document(), and recompute().
signalStartSave
boost::signals2::signal<void(const App::Document&, const std::string&)> App::Document::signalStartSave
Definition at line 170 of file App/Document.h.
Referenced by App::Application::newDocument(), and saveToFile().
signalTouchedObject
boost::signals2::signal<void(const App::DocumentObject&)> App::Document::signalTouchedObject
signal on manually called DocumentObject::touch()
Definition at line 143 of file App/Document.h.
Referenced by Gui::Document::Document().
signalTransactionAppend
boost::signals2::signal<void(const App::DocumentObject&, Transaction*)> App::Document::signalTransactionAppend
signal on created object
Definition at line 149 of file App/Document.h.
Referenced by _addObject(), addObject(), addObjects(), and Gui::Document::Document().
signalTransactionRemove
boost::signals2::signal<void(const App::DocumentObject&, Transaction*)> App::Document::signalTransactionRemove
signal on removed object
Definition at line 151 of file App/Document.h.
Referenced by _removeObject(), Gui::Document::Document(), and removeObject().
signalUndo
boost::signals2::signal<void(const App::Document&)> App::Document::signalUndo
signal on undo
Definition at line 153 of file App/Document.h.
Referenced by Gui::Document::Document(), Gui::GraphvizView::GraphvizView(), App::Application::newDocument(), and undo().
Tip
PropertyLink App::Document::Tip
Tip object of the document (if any)
Definition at line 118 of file App/Document.h.
Referenced by _removeObject(), Document(), removeObject(), Restore(), and save().
TipName
PropertyString App::Document::TipName
Tip object of the document (if any)
Definition at line 120 of file App/Document.h.
Referenced by _removeObject(), Document(), removeObject(), Restore(), and save().
TransientDir
PropertyString App::Document::TransientDir
read-only name of the temp dir created when the document is opened
Definition at line 116 of file App/Document.h.
Referenced by Document(), getFileName(), onChanged(), Sandbox::DocumentSaverThread::run(), App::VRMLObject::SaveDocFile(), Gui::AutoSaver::slotCreateDocument(), and ~Document().
Uid
PropertyUUID App::Document::Uid
unique identifier of the document
Definition at line 106 of file App/Document.h.
Referenced by Document(), onChanged(), and saveAs().
UnitSystem
PropertyEnumeration App::Document::UnitSystem
Unit System.
Definition at line 100 of file App/Document.h.
Referenced by Document(), and Gui::Application::slotActiveDocument().
UseHasher
PropertyBool App::Document::UseHasher
Whether to use hasher on topological naming.
Definition at line 124 of file App/Document.h.
Referenced by Document(), getStringHasher(), and onChanged().
The documentation for this class was generated from the following files:
App/Document.h
App/Document.cpp
Graphviz.cpp