FreeCAD: Gui::Dialog::SceneModel Class Reference
Gui::Dialog::SceneModel Class Reference
Stores data representing scenegraph nodes.
#include <SceneInspector.h>
Public Member Functions
SceneModel (QObject *parent)
~SceneModel () override
int columnCount (const QModelIndex &parent=QModelIndex()) const override
Tree structure: column count is 1.
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole) override
header data not used: returns false
void setNode (SoNode *node)
insert the first node in tree
void setNodeNames (const QHash< SoNode *, QString > &names)
set names per node
Qt::ItemFlags flags (const QModelIndex &index) const override
returns standard parent's flags
Detailed Description
Stores data representing scenegraph nodes.
Definition at line 39 of file SceneInspector.h.
Constructor & Destructor Documentation
SceneModel()
SceneModel::SceneModel (QObject * parent)
Definition at line 46 of file SceneInspector.cpp.
~SceneModel()
SceneModel::~SceneModel () override default
Member Function Documentation
columnCount()
int SceneModel::columnCount (const QModelIndex & parent = QModelIndex()) const override
Tree structure: column count is 1.
Definition at line 61 of file SceneInspector.cpp.
References COUNT, and Init::parent.
flags()
Qt::ItemFlags SceneModel::flags (const QModelIndex & index) const override
returns standard parent's flags
Definition at line 67 of file SceneInspector.cpp.
headerData()
QVariant SceneModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const override
returns empty QVariant, unless orientation == Qt::Horizontal, role == Qt::DisplayRole and section == 0 where it returns "Inventor Tree"
Definition at line 72 of file SceneInspector.cpp.
References DATA, Sketcher::Horizontal, INVENTOR_TREE, MEMORY_ADDRESS, and NAME.
setHeaderData()
bool SceneModel::setHeaderData (int section, Qt::Orientation orientation, const QVariant & value, int role = Qt::EditRole) override
header data not used: returns false
Definition at line 95 of file SceneInspector.cpp.
Referenced by setNode().
setNode()
void SceneModel::setNode (SoNode * node)
insert the first node in tree
Definition at line 100 of file SceneInspector.cpp.
References Path.Op.Gui.Selection::clear(), COUNT, Sketcher::Horizontal, and setHeaderData().
Referenced by Gui::Dialog::DlgInspector::setNode().
setNodeNames()
void SceneModel::setNodeNames (const QHash< SoNode *, QString > & names)
set names per node
Definition at line 236 of file SceneInspector.cpp.
References femtools.tokrules::names.
Referenced by Gui::Dialog::DlgInspector::setNodeNames().
The documentation for this class was generated from the following files:
SceneInspector.h
SceneInspector.cpp