FreeCAD: MeshGui::SoFCMeshObjectNode Class Reference
MeshGui::SoFCMeshObjectNode Class Reference
#include <SoFCMeshObject.h>
Public Member Functions
SoFCMeshObjectNode ()
void doAction (SoAction *action) override
void GLRender (SoGLRenderAction *action) override
void callback (SoCallbackAction *action) override
void getBoundingBox (SoGetBoundingBoxAction *action) override
void pick (SoPickAction *action) override
void getPrimitiveCount (SoGetPrimitiveCountAction *action) override
Static Public Member Functions
static void initClass ()
Public Attributes
SoSFMeshObject mesh
Protected Member Functions
~SoFCMeshObjectNode () override
Detailed Description
Definition at line 134 of file SoFCMeshObject.h.
Constructor & Destructor Documentation
SoFCMeshObjectNode()
SoFCMeshObjectNode::SoFCMeshObjectNode ()
Constructor.
Definition at line 510 of file SoFCMeshObject.cpp.
References Mesh2Shape::mesh.
~SoFCMeshObjectNode()
SoFCMeshObjectNode::~SoFCMeshObjectNode () override protected default
Destructor.
Member Function Documentation
callback()
void SoFCMeshObjectNode::callback (SoCallbackAction * action) override
Definition at line 547 of file SoFCMeshObject.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
doAction()
void SoFCMeshObjectNode::doAction (SoAction * action) override
Definition at line 535 of file SoFCMeshObject.cpp.
References Path.Post.scripts.dynapath_4060_post::action, mesh, and MeshGui::SoFCMeshObjectElement::set().
Referenced by callback(), getBoundingBox(), getPrimitiveCount(), GLRender(), and pick().
getBoundingBox()
void SoFCMeshObjectNode::getBoundingBox (SoGetBoundingBoxAction * action) override
Definition at line 559 of file SoFCMeshObject.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
getPrimitiveCount()
void SoFCMeshObjectNode::getPrimitiveCount (SoGetPrimitiveCountAction * action) override
Definition at line 565 of file SoFCMeshObject.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
GLRender()
void SoFCMeshObjectNode::GLRender (SoGLRenderAction * action) override
Definition at line 541 of file SoFCMeshObject.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
initClass()
void SoFCMeshObjectNode::initClass () static
Definition at line 523 of file SoFCMeshObject.cpp.
Referenced by PyMOD_INIT_FUNC().
pick()
void SoFCMeshObjectNode::pick (SoPickAction * action) override
Definition at line 553 of file SoFCMeshObject.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and doAction().
Member Data Documentation
mesh
SoSFMeshObject MeshGui::SoFCMeshObjectNode::mesh
Definition at line 144 of file SoFCMeshObject.h.
Referenced by doAction(), MengerSponge.MengerThread::run(), MeshGui::ViewProviderMeshFaceSet::updateData(), and MeshGui::ViewProviderMeshObject::updateData().
The documentation for this class was generated from the following files:
SoFCMeshObject.h
SoFCMeshObject.cpp