FreeCAD: MillSim::GuiDisplay Class Reference
MillSim::GuiDisplay Class Reference
#include <GuiDisplay.h>
Public Member Functions
bool InitGui ()
void ResetGui ()
void Render (float progress)
void MouseCursorPos (int x, int y)
void HandleActionItem (GuiItem *guiItem)
void MousePressed (int button, bool isPressed, bool isRunning)
void MouseDrag (int buttons, int dx, int dy)
void SetMillSimulator (MillSimulation *millSim)
void UpdatePlayState (bool isRunning)
void UpdateSimSpeed (int speed)
void HandleKeyPress (int key)
bool IsChecked (eGuiItems item)
void UpdateWindowScale ()
Public Attributes
bool guiInitiated = false
Detailed Description
Definition at line 113 of file GuiDisplay.h.
Member Function Documentation
HandleActionItem()
void MillSim::GuiDisplay::HandleActionItem (GuiItem * guiItem)
Definition at line 211 of file GuiDisplay.cpp.
References MillSim::GuiItem::actionKey, MillSim::GuiItem::flags, GUIITEM_CHECKABLE, GUIITEM_CHECKED, and MillSim::GuiItem::name.
Referenced by MousePressed().
HandleKeyPress()
void MillSim::GuiDisplay::HandleKeyPress (int key)
Definition at line 275 of file GuiDisplay.cpp.
References toolbit-attributes::g, guiItems, SplineSurface::i, and NUM_GUI_ITEMS.
Referenced by MillSim::MillSimulation::HandleKeyPress().
InitGui()
bool GuiDisplay::InitGui ()
Definition at line 117 of file GuiDisplay.cpp.
References MillSim::Shader::CompileShader(), MillSim::eGuiItemSlider, MillSim::eGuiItemThumb, MillSim::FragShader2dTex, MillSim::TextureLoader::GetRawData(), MillSim::TextureLoader::GetTextureItem(), glBindBuffer, glBufferData, glGenBuffers, guiFileNames, guiInitiated, guiItems, SplineSurface::i, MillSim::Texture::LoadImage(), NUM_GUI_ITEMS, MillSim::GuiItem::posx(), TEX_SIZE, MillSim::GuiItem::texItem, UpdateSimSpeed(), MillSim::Shader::UpdateTextureSlot(), MillSim::VertShader2DTex, and MillSim::TextureItem::w.
Referenced by MillSim::MillSimulation::InitDisplay().
IsChecked()
bool MillSim::GuiDisplay::IsChecked (eGuiItems item)
Definition at line 285 of file GuiDisplay.cpp.
References GUIITEM_CHECKED, and guiItems.
Referenced by MillSim::MillSimulation::InitSimulation(), MillSim::MillSimulation::ProcessSim(), and MillSim::MillSimulation::RenderPath().
MouseCursorPos()
void GuiDisplay::MouseCursorPos (int x, int y)
Definition at line 192 of file GuiDisplay.cpp.
References toolbit-attributes::g, guiItems, SplineSurface::i, NUM_GUI_ITEMS, MovieTool::x, and MovieTool::y.
Referenced by MillSim::MillSimulation::MouseHover(), and MousePressed().
MouseDrag()
void GuiDisplay::MouseDrag (int buttons, int dx, int dy)
Definition at line 242 of file GuiDisplay.cpp.
References MillSim::eGuiItemThumb, MillSim::GuiItem::name, MillSim::GuiItem::posx(), MillSim::GuiItem::setPosx(), and MillSim::MillSimulation::SetSimulationStage().
Referenced by MillSim::MillSimulation::MouseDrag().
MousePressed()
void GuiDisplay::MousePressed (int button, bool isPressed, bool isRunning)
Definition at line 222 of file GuiDisplay.cpp.
References HandleActionItem(), MouseCursorPos(), MS_MOUSE_LEFT, MillSim::GuiItem::posx(), MillSim::GuiItem::posy(), and UpdatePlayState().
Referenced by MillSim::MillSimulation::MousePress().
Render()
void GuiDisplay::Render (float progress)
Definition at line 295 of file GuiDisplay.cpp.
References MillSim::Texture::Activate(), MillSim::Shader::Activate(), MillSim::eGuiItemThumb, glBlendFunc, glDisable, glEnable, guiItems, SplineSurface::i, MillSim::GuiItem::name, NUM_GUI_ITEMS, MillSim::GuiItem::setPosx(), and MillSim::Shader::UpdateTextureSlot().
Referenced by MillSim::MillSimulation::Render().
ResetGui()
void GuiDisplay::ResetGui ()
Definition at line 151 of file GuiDisplay.cpp.
References MillSim::Shader::Destroy(), MillSim::Texture::DestroyTexture(), GLDELETE_BUFFER, guiInitiated, guiItems, SplineSurface::i, and NUM_GUI_ITEMS.
Referenced by MillSim::MillSimulation::Clear().
SetMillSimulator()
void MillSim::GuiDisplay::SetMillSimulator (MillSimulation * millSim) inline
Definition at line 124 of file GuiDisplay.h.
Referenced by MillSim::MillSimulation::MillSimulation().
UpdatePlayState()
void GuiDisplay::UpdatePlayState (bool isRunning)
Definition at line 262 of file GuiDisplay.cpp.
References MillSim::eGuiItemPause, MillSim::eGuiItemPlay, guiItems, and MillSim::GuiItem::hidden.
Referenced by MillSim::MillSimulation::HandleGuiAction(), and MousePressed().
UpdateSimSpeed()
void MillSim::GuiDisplay::UpdateSimSpeed (int speed)
Definition at line 268 of file GuiDisplay.cpp.
References MillSim::eGuiItemChar0Img, MillSim::eGuiItemChar1Img, MillSim::eGuiItemChar4Img, guiItems, MillSim::GuiItem::hidden, and Path.Post.scripts.rml_post::speed().
Referenced by MillSim::MillSimulation::HandleGuiAction(), and InitGui().
UpdateWindowScale()
void MillSim::GuiDisplay::UpdateWindowScale ()
Definition at line 290 of file GuiDisplay.cpp.
Referenced by MillSim::MillSimulation::UpdateWindowScale().
Member Data Documentation
guiInitiated
bool MillSim::GuiDisplay::guiInitiated = false
Definition at line 135 of file GuiDisplay.h.
Referenced by InitGui(), and ResetGui().
The documentation for this class was generated from the following files:
GuiDisplay.h
GuiDisplay.cpp