FreeCAD: PlmXmlParser Namespace Reference
PlmXmlParser Namespace Reference
Functions
def ParseUserData (element)
def addPart (partElement)
def addAssembly (asmElement)
def addReference (refElement)
def resolveRefs ()
def open (fileName)
def insert (filename, docname)
def main ()
def parse (fileName)
Variables
FreeCAD_On
FreeCAD_Doc
FreeCAD_ObjList
Function Documentation
addAssembly()
def PlmXmlParser.addAssembly (asmElement)
Definition at line 66 of file PlmXmlParser.py.
References ParseUserData().
Referenced by parse().
addPart()
def PlmXmlParser.addPart (partElement)
Definition at line 41 of file PlmXmlParser.py.
References ParseUserData().
Referenced by parse().
addReference()
def PlmXmlParser.addReference (refElement)
Definition at line 86 of file PlmXmlParser.py.
References ParseUserData().
Referenced by parse().
insert()
def PlmXmlParser.insert (filename, docname)
called when freecad imports an PlmXml file
Definition at line 138 of file PlmXmlParser.py.
References parse(), and resolveRefs().
main()
def PlmXmlParser.main ()
Definition at line 152 of file PlmXmlParser.py.
References parse().
Referenced by parse().
open()
def PlmXmlParser.open (fileName)
called when freecad opens an PlmXml file
Definition at line 123 of file PlmXmlParser.py.
References parse(), and resolveRefs().
parse()
def PlmXmlParser.parse (fileName)
Definition at line 156 of file PlmXmlParser.py.
References addAssembly(), addPart(), addReference(), main(), and ParseUserData().
Referenced by insert(), main(), and open().
ParseUserData()
def PlmXmlParser.ParseUserData (element)
Definition at line 33 of file PlmXmlParser.py.
Referenced by addAssembly(), addPart(), addReference(), and parse().
resolveRefs()
def PlmXmlParser.resolveRefs ()
Definition at line 109 of file PlmXmlParser.py.
Referenced by insert(), and open().
Variable Documentation
FreeCAD_Doc
PlmXmlParser.FreeCAD_Doc
Definition at line 29 of file PlmXmlParser.py.
FreeCAD_ObjList
PlmXmlParser.FreeCAD_ObjList
Definition at line 30 of file PlmXmlParser.py.
FreeCAD_On
PlmXmlParser.FreeCAD_On
Definition at line 28 of file PlmXmlParser.py.