FreeCAD: App::Application Class Reference
App::Application Class Reference
#include <Application.h>
Classes
class TransactionSignaller
Helper class for App::Document to signal on close/abort transaction.
Public Member Functions
Application-wide trandaction setting
int setActiveTransaction (const char *name, bool persist=false)
const char * getActiveTransaction (int *tid=nullptr) const
Return the current active transaction name and ID.
void closeActiveTransaction (bool abort=false, int id=0)
methods for parameter handling
ParameterManager & GetSystemParameter ()
returns the system parameter
ParameterManager & GetUserParameter ()
returns the user parameter
Base::Reference< ParameterGrp > GetParameterGroupByPath (const char *sName)
ParameterManager * GetParameterSet (const char *sName) const
const std::map< std::string, Base::Reference< ParameterManager > > & GetParameterSetList () const
void AddParameterSet (const char *sName)
void RemoveParameterSet (const char *sName)
methods for the open handler
With this facility an Application module can register an ending (filetype) which it can handle to open. The ending and the module name are stored and if the file type is opened the module gets loaded and needs to register an OpenHandler class in the OpenHandlerFactorySingleton. After the module is loaded, an OpenHandler of this type is created and the file gets loaded.
See also
OpenHandler
OpenHandlerFactorySingleton
void addImportType (const char *Type, const char *ModuleName)
Register an import filetype and a module name.
void changeImportModule (const char *Type, const char *OldModuleName, const char *NewModuleName)
Change the module name of a registered filetype.
std::vector< std::string > getImportModules (const char *Type) const
Return a list of modules that support the given filetype.
std::vector< std::string > getImportModules () const
Return a list of all modules.
std::vector< std::string > getImportTypes (const char *Module) const
Return a list of filetypes that are supported by a module.
std::vector< std::string > getImportTypes () const
Return a list of all filetypes.
std::map< std::string, std::string > getImportFilters (const char *Type) const
Return the import filters with modules of a given filetype.
std::map< std::string, std::string > getImportFilters () const
Return a list of all import filters.
void addExportType (const char *Type, const char *ModuleName)
Register an export filetype and a module name.
void changeExportModule (const char *Type, const char *OldModuleName, const char *NewModuleName)
Change the module name of a registered filetype.
std::vector< std::string > getExportModules (const char *Type) const
Return a list of modules that support the given filetype.
std::vector< std::string > getExportModules () const
Return a list of all modules.
std::vector< std::string > getExportTypes (const char *Module) const
Return a list of filetypes that are supported by a module.
std::vector< std::string > getExportTypes () const
Return a list of all filetypes.
std::map< std::string, std::string > getExportFilters (const char *Type) const
Return the export filters with modules of a given filetype.
std::map< std::string, std::string > getExportFilters () const
Return a list of all export filters.
Static Public Member Functions
Application directories
static std::string getHomePath ()
static std::string getExecutableName ()
static std::string getTempPath ()
static std::string getTempFileName (const char *FileName=nullptr)
static std::string getUserCachePath ()
static std::string getUserConfigPath ()
static std::string getUserAppDataDir ()
static std::string getUserMacroDir ()
static std::string getResourceDir ()
static std::string getLibraryDir ()
static std::string getHelpDir ()
Public Attributes
Signals of the Application
boost::signals2::signal< void(const Document &, bool)> signalNewDocument
signal on new Document
boost::signals2::signal< void(const Document &)> signalDeleteDocument
signal on document getting deleted
boost::signals2::signal< void()> signalDeletedDocument
signal on already deleted Document
boost::signals2::signal< void(const Document &)> signalRelabelDocument
signal on relabeling Document (user name)
boost::signals2::signal< void(const Document &)> signalRenameDocument
signal on renaming Document (internal name)
boost::signals2::signal< void(const Document &)> signalActiveDocument
signal on activating Document
boost::signals2::signal< void(const Document &)> signalSaveDocument
signal on saving Document
boost::signals2::signal< void(const Document &)> signalStartRestoreDocument
signal on starting to restore Document
boost::signals2::signal< void(const Document &)> signalFinishRestoreDocument
signal on restoring Document
boost::signals2::signal< void(const Document &)> signalPendingReloadDocument
signal on pending reloading of a partial Document
boost::signals2::signal< void(const Document &, const std::string &)> signalStartSaveDocument
signal on starting to save Document
boost::signals2::signal< void(const Document &, const std::string &)> signalFinishSaveDocument
signal on saved Document
boost::signals2::signal< void(const Document &)> signalUndoDocument
signal on undo in document
boost::signals2::signal< void()> signalUndo
signal on application wide undo
boost::signals2::signal< void(const Document &)> signalRedoDocument
signal on redo in document
boost::signals2::signal< void()> signalRedo
signal on application wide redo
boost::signals2::signal< void(bool)> signalBeforeCloseTransaction
signal before close/abort active transaction
boost::signals2::signal< void(bool)> signalCloseTransaction
signal after close/abort active transaction
boost::signals2::signal< void(const Document &)> signalShowHidden
signal on show hidden items
boost::signals2::signal< void()> signalStartOpenDocument
signal on start opening document(s)
boost::signals2::signal< void()> signalFinishOpenDocument
signal on finished opening document(s)
Signals of the document
This signals are an aggregation of all document. If you only the signal of a special document connect to the document itself
boost::signals2::signal< void(const App::Document &, const App::Property &)> signalBeforeChangeDocument
signal before change of doc property
boost::signals2::signal< void(const App::Document &, const App::Property &)> signalChangedDocument
signal on changed doc property
boost::signals2::signal< void(const App::DocumentObject &)> signalNewObject
signal on new Object
boost::signals2::signal< void(const App::DocumentObject &)> signalDeletedObject
signal on deleted Object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalBeforeChangeObject
signal on changed Object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalChangedObject
signal on changed Object
boost::signals2::signal< void(const App::DocumentObject &)> signalRelabelObject
signal on relabeled Object
boost::signals2::signal< void(const App::DocumentObject &)> signalActivatedObject
signal on activated Object
boost::signals2::signal< void(const App::Document &)> signalBeforeRecomputeDocument
signal before recomputed document
boost::signals2::signal< void(const App::Document &)> signalRecomputed
signal on recomputed document
boost::signals2::signal< void(const App::DocumentObject &)> signalObjectRecomputed
signal on recomputed document object
boost::signals2::signal< void(const App::Document &, std::string)> signalOpenTransaction
boost::signals2::signal< void(const App::Document &)> signalCommitTransaction
boost::signals2::signal< void(const App::Document &)> signalAbortTransaction
Signals of property changes
These signals are emitted on property additions or removal. The changed object can be any sub-class of PropertyContainer.
boost::signals2::signal< void(const App::Property &)> signalAppendDynamicProperty
signal on adding a dynamic property
boost::signals2::signal< void(const App::Property &)> signalRemoveDynamicProperty
signal on about removing a dynamic property
boost::signals2::signal< void(const App::Document &, const App::Property &)> signalChangePropertyEditor
signal on about changing the editor mode of a property
Signals of extension changes
These signals are emitted on dynamic extension addition. Dynamic extensions are the ones added by python (c++ ones are part of the class definition, hence not dynamic) The extension in question is provided as parameter.
boost::signals2::signal< void(const App::ExtensionContainer &, std::string extension)> signalBeforeAddingDynamicExtension
signal before adding the extension
boost::signals2::signal< void(const App::ExtensionContainer &, std::string extension)> signalAddedDynamicExtension
signal after the extension was added
methods for document handling
enum PathMatchMode { PathMatchMode::MatchAbsolute = 0, PathMatchMode::MatchCanonical = 1, PathMatchMode::MatchCanonicalWarning = 2 }
Path matching mode for getDocumentByPath()
App::Document * newDocument (const char *Name=nullptr, const char *UserName=nullptr, bool createView=true, bool tempDoc=false)
bool closeDocument (const char *name)
Closes the document name and removes it from the application.
std::string getUniqueDocumentName (const char *Name, bool tempDoc=false) const
find a unique document name
App::Document * openDocument (const char *FileName=nullptr, bool createView=true)
Open an existing document from a file.
std::vector< Document * > openDocuments (const std::vector< std::string > &filenames, const std::vector< std::string > *paths=nullptr, const std::vector< std::string > *labels=nullptr, std::vector< std::string > *errs=nullptr, bool createView=true)
App::Document * getActiveDocument () const
Retrieve the active document.
App::Document * getDocument (const char *Name) const
Retrieve a named document.
App::Document * getDocumentByPath (const char *path, PathMatchMode checkCanonical=PathMatchMode::MatchAbsolute) const
const char * getDocumentName (const App::Document *) const
gets the (internal) name of the document
std::vector< App::Document * > getDocuments () const
get a list of all documents in the application
void setActiveDocument (App::Document *pDoc)
Set the active document.
void setActiveDocument (const char *Name)
void closeAllDocuments ()
close all documents (without saving)
int addPendingDocument (const char *FileName, const char *objName, bool allowPartial)
Add pending document to open together with the current opening document.
bool isRestoring () const
Indicate whether the application is opening (restoring) some document.
bool isClosingAll () const
Indicate the application is closing all document.
Init, Destruct an Access methods
Application & GetApplication ()
Singleton getter of the Application.
static void init (int argc, char **argv)
static void initTypes ()
static void destruct ()
static void destructObserver ()
static void processCmdLineFiles ()
static std::list< std::string > getCmdLineFiles ()
static std::list< std::string > processFiles (const std::list< std::string > &)
static void runApplication ()
static std::map< std::string, std::string > & Config ()
static int GetARGC ()
static char ** GetARGV ()
static int64_t applicationPid ()
Link handling
class App::Document
int checkLinkDepth (int depth, MessageOption option=MessageOption::Error)
std::set< DocumentObject * > getLinksTo (const DocumentObject *, int options, int maxCount=0) const
bool hasLinksTo (const DocumentObject *obj) const
Check if there is any link to the given object.
void renameDocument (const char *OldName, const char *NewName)
get called by the document when the name is changing
I/O of the document
This slot gets connected to all App::Documents created
void slotBeforeChangeDocument (const App::Document &, const App::Property &)
void slotChangedDocument (const App::Document &, const App::Property &)
void slotNewObject (const App::DocumentObject &)
void slotDeletedObject (const App::DocumentObject &)
void slotBeforeChangeObject (const App::DocumentObject &, const App::Property &Prop)
void slotChangedObject (const App::DocumentObject &, const App::Property &Prop)
void slotRelabelObject (const App::DocumentObject &)
void slotActivatedObject (const App::DocumentObject &)
void slotUndoDocument (const App::Document &)
void slotRedoDocument (const App::Document &)
void slotRecomputedObject (const App::DocumentObject &)
void slotRecomputed (const App::Document &)
void slotBeforeRecompute (const App::Document &)
void slotOpenTransaction (const App::Document &, std::string)
void slotCommitTransaction (const App::Document &)
void slotAbortTransaction (const App::Document &)
void slotStartSaveDocument (const App::Document &, const std::string &)
void slotFinishSaveDocument (const App::Document &, const std::string &)
void slotChangePropertyEditor (const App::Document &, const App::Property &)
App::Document * openDocumentPrivate (const char *FileName, const char *propFileName, const char *label, bool isMainDoc, bool createView, std::vector< std::string > &&objNames)
open single document only
member for parameter
class ApplicationObserver
Private Init, Destruct an Access methods
class AutoTransaction
Detailed Description
The Application The root of the whole application
See also
App::Document
Definition at line 77 of file App/Application.h.
Member Enumeration Documentation
PathMatchMode
enum App::Application::PathMatchMode strong
Path matching mode for getDocumentByPath()
Enumerator
MatchAbsolute
Match by resolving to absolute file path.
MatchCanonical
Match by absolute path first. If not found then match by resolving to canonical file path where any intermediate '.' '..' and symlinks are resolved.
MatchCanonicalWarning
Same as MatchCanonical, but if a document is found by canonical path match, which means the document can be resolved using two different absolute path, a warning is printed and the found document is not returned. This is to allow the caller to intentionally load the same physical file as separate documents.
Definition at line 132 of file App/Application.h.
Member Function Documentation
addExportType()
void Application::addExportType (const char * Type, const char * ModuleName)
Register an export filetype and a module name.
Definition at line 1461 of file App/Application.cpp.
References Config(), RobotExample::pos, and Path.Post.scripts.grbl_post::type.
addImportType()
void Application::addImportType (const char * Type, const char * ModuleName)
Register an import filetype and a module name.
Definition at line 1338 of file App/Application.cpp.
References Config(), RobotExample::pos, and Path.Post.scripts.grbl_post::type.
AddParameterSet()
void Application::AddParameterSet (const char * sName)
Definition at line 1299 of file App/Application.cpp.
References ParameterManager::Create().
addPendingDocument()
int Application::addPendingDocument (const char * FileName, const char * objName, bool allowPartial)
Add pending document to open together with the current opening document.
Definition at line 644 of file App/Application.cpp.
Referenced by App::DocInfo::attach(), and App::DocInfo::get().
applicationPid()
int64_t Application::applicationPid () static
Definition at line 1122 of file App/Application.cpp.
References Path.Post.scripts.dumper_post::now.
Referenced by Gui::Dialog::DocumentRecoveryHandler::checkForPreviousCrashes(), and App::Document::getTransientDirectoryName().
changeExportModule()
void Application::changeExportModule (const char * Type, const char * OldModuleName, const char * NewModuleName)
Change the module name of a registered filetype.
Definition at line 1490 of file App/Application.cpp.
changeImportModule()
void Application::changeImportModule (const char * Type, const char * OldModuleName, const char * NewModuleName)
Change the module name of a registered filetype.
Definition at line 1367 of file App/Application.cpp.
checkLinkDepth()
int Application::checkLinkDepth (int depth, MessageOption option = MessageOption::Error)
Check for link recursion depth
Parameters
depth current depth
option whether to throw exception, print an error message or quieten any output. In the latter case the caller must check the returned value.
Returns
Return the maximum remaining depth.
The function uses an internal count of all objects in all documents as the limit of recursion depth.
Definition at line 1221 of file App/Application.cpp.
References App::Error, FC_ERR, Path.Op.Surface::msg, App::Quiet, App::Throw, and TestSpreadsheet::v.
Referenced by PartDesign::SubShapeBinder::getSubObject().
closeActiveTransaction()
void Application::closeActiveTransaction (bool abort = false, int id = 0)
Commit/abort current active transactions
Parameters
abort whether to abort or commit the transactions
Bsides calling this function directly, it will be called by automatically if 1) any new transaction is created with a different ID, or 2) any transaction with the current active transaction ID is either committed or aborted
Definition at line 187 of file AutoTransaction.cpp.
References _TransactionClosed, _TransactionLock, FC_LOG, and TestSpreadsheet::v.
Referenced by App::Document::_commitTransaction(), Gui::Document::_resetEdit(), Gui::Command::abortCommand(), App::Document::abortTransaction(), PartDesignGui::DlgActiveBody::accept(), Gui::ElementColors::Private::accept(), App::TransactionLocker::activate(), Gui::ExpressionBinding::apply(), Gui::TaskMeasure::apply(), App::AutoTransaction::close(), Gui::Command::commitCommand(), App::Document::commitTransaction(), TechDrawGui::QGIViewAnnotation::mouseDoubleClickEvent(), TechDrawGui::QGIRichAnno::mouseDoubleClickEvent(), Gui::TaskMeasure::reject(), Gui::ElementColors::Private::reset(), Gui::ExpressionBinding::setExpression(), and App::PropertyString::setValue().
closeAllDocuments()
void Application::closeAllDocuments ()
close all documents (without saving)
Definition at line 580 of file App/Application.cpp.
References closeDocument(), and RobotExample::pos.
Referenced by Gui::MainWindow::closeAllDocuments(), Gui::GUIApplication::commitData(), and Gui::Application::tryClose().
closeDocument()
bool Application::closeDocument (const char * name)
Closes the document name and removes it from the application.
Definition at line 553 of file App/Application.cpp.
References Base::FileInfo::filePath(), RobotExample::pos, setActiveDocument(), signalDeletedDocument, and signalDeleteDocument.
Referenced by Gui::Dialog::DocumentRecovery::accept(), closeAllDocuments(), openDocumentPrivate(), and openDocuments().
Config()
static std::map<std::string, std::string>& App::Application::Config () inline static
Definition at line 402 of file App/Application.h.
Referenced by _replaceDirs(), Gui::Dialog::AboutDialog::aboutImage(), StdViewScreenShot::activated(), addExportType(), addImportType(), Gui::RecentMacrosAction::appendFile(), Gui::Application::Application(), Gui::Application::checkForRecomputes(), Gui::Dialog::AboutDialog::copyToClipboard(), Gui::SoFCOffscreenRenderer::createMIBA(), App::Document::exportObjects(), Gui::Dialog::DlgMacroExecuteImp::fillUpList(), Gui::Application::hiddenMainWindow(), Gui::BitmapFactoryInst::instance(), Gui::Dialog::DlgSettingsWorkbenchesImp::loadSettings(), Gui::MainWindow::loadWindowSettings(), Gui::PreferencePackManager::modPaths(), Gui::Dialog::ApplicationCache::periodicCheckOfSize(), processCmdLineFiles(), Gui::PythonConsole::PythonConsole(), Gui::FileDialog::restoreLocation(), App::Metadata::satisfies(), App::Document::Save(), Materials::Material::save(), Gui::Thumbnail::SaveDocFile(), Gui::RecentFilesAction::Private::saveUserParameter(), Gui::MainWindow::saveWindowSettings(), Gui::Dialog::AboutDialog::setupLabels(), Gui::MainWindow::setWindowTitle(), Gui::SplashScreen::splashImage(), Gui::SplashObserver::SplashObserver(), Gui::MainWindow::startSplasher(), App::Metadata::supportsCurrentFreeCAD(), Gui::Dialog::TextureMapping::TextureMapping(), Gui::Application::workbenches(), and CDxfWrite::writeHeaderSection().
destruct()
void Application::destruct () static
Definition at line 1710 of file App/Application.cpp.
References App::CleanupProcess::callCleanup(), Base::Console(), SafeMode::Destruct(), Base::ScriptFactorySingleton::Destruct(), Base::Type::destruct(), Base::InterpreterSingleton::Destruct(), destructObserver(), Base::InterpreterSingleton::finalize(), ParameterManager::IgnoreSave(), Base::Interpreter(), Base::ConsoleSingleton::Log(), ParameterManager::SaveDocument(), ParameterManager::Terminate(), and Base::ConsoleSingleton::Warning().
destructObserver()
void Application::destructObserver () static
Definition at line 1770 of file App/Application.cpp.
References Base::Console(), and Base::ConsoleSingleton::DetachObserver().
Referenced by destruct(), init(), and Gui::Application::initApplication().
getActiveDocument()
Document * Application::getActiveDocument () const
Retrieve the active document.
Definition at line 1052 of file App/Application.cpp.
Referenced by _copyShape(), Gui::Command::_copyVisual(), PartGui::DlgBooleanOperation::accept(), MeshGui::Segmentation::accept(), ReverseEngineeringGui::Segmentation::accept(), PartGui::DlgRevolution::accept(), PartGui::DlgFilletEdges::accept(), MeshPartGui::Tessellation::accept(), MeshGui::SegmentationBestFit::accept(), StdCmdLinkMakeGroup::activated(), StdCmdOpen::activated(), StdCmdLinkMake::activated(), StdCmdLinkMakeRelative::activated(), StdCmdMergeProjects::activated(), CmdSandboxMeshLoader::activated(), StdCmdDependencyGraph::activated(), StdCmdLinkImportAll::activated(), StdCmdExportDependencyGraph::activated(), StdCmdDuplicateSelection::activated(), StdCmdSelectAll::activated(), StdCmdExpression::activated(), Cloud::Module::cloudRestore(), Cloud::Module::cloudSave(), Gui::TreeWidget::contextMenuEvent(), Part::Feature::create(), Fem::createObjectByType(), SketcherGui::ConstraintView::deleteSelectedItems(), SketcherGui::ElementView::deleteSelectedItems(), PartGui::DlgProjectionOnSurface::DlgProjectionOnSurface(), doSelect(), PartGui::DlgScale::findShapes(), PartGui::DlgExtrusion::findShapes(), PartGui::DlgFilletEdges::findShapes(), PartGui::DlgExtrusion::getAxisLink(), PartGui::DlgRevolution::getAxisLink(), Gui::SelectionSingleton::getDocument(), Gui::Command::getObjectCmd(), MeshGui::MeshSelection::getObjects(), PartGui::DlgRevolution::getShapesToRevolve(), Gui::Command::getUniqueObjectName(), Gui::MainWindow::insertFromMimeData(), StdCmdLinkMakeGroup::isActive(), StdCmdLinkMake::isActive(), StdCmdLinkImportAll::isActive(), StdCmdSelectVisibleObjects::isActive(), StdCmdToggleObjects::isActive(), StdCmdShowObjects::isActive(), StdCmdHideObjects::isActive(), StdCmdSelectAll::isActive(), Cloud::Module::LinkXSetValue(), PartDesignGui::TaskFeaturePick::makeCopy(), Gui::Application::open(), SpreadsheetGui::SheetTableView::pasteClipboard(), TechDrawGui::MDIViewPage::printAllPages(), App::Document::restore(), Sandbox::DocumentThread::run(), Sandbox::DocumentTestThread::run(), Gui::TreeWidget::selectLinkedObject(), Gui::QuantitySpinBox::setBoundToByName(), PartDesignGui::TaskBoxPrimitives::setPrimitive(), Gui::DimensionWidget::setUserSchema(), Gui::TaskView::TaskWatcherCommandsEmptyDoc::shouldShow(), Gui::Document::slotSkipRecompute(), MeshGui::ViewProviderMesh::splitMesh(), FemGui::TaskCreateElementSet::TaskCreateElementSet(), DrawingGui::TaskOrthoViews::TaskOrthoViews(), TechDrawGui::TaskSurfaceFinishSymbols::TaskSurfaceFinishSymbols(), Data::ElementMap::traceElement(), Gui::TaskMeasure::update(), and InspectionGui::VisualInspection::VisualInspection().
getActiveTransaction()
const char * Application::getActiveTransaction (int * tid = nullptr) const
Return the current active transaction name and ID.
Definition at line 175 of file AutoTransaction.cpp.
References App::Transaction::getLastID().
Referenced by App::Document::_checkTransaction(), App::Document::addOrRemovePropertyOfObject(), Gui::ExpressionBinding::apply(), Gui::Command::hasPendingCommand(), setActiveTransaction(), Gui::ExpressionBinding::setExpression(), PartDesignGui::TaskDressUpParameters::setupTransaction(), PartDesignGui::TaskTransformedParameters::setupTransaction(), PartDesignGui::TaskDressUpParameters::TaskDressUpParameters(), and PartDesignGui::TaskTransformedParameters::TaskTransformedParameters().
GetARGC()
static int App::Application::GetARGC () inline static
Definition at line 403 of file App/Application.h.
Referenced by Gui::Application::runApplication().
GetARGV()
static char** App::Application::GetARGV () inline static
Definition at line 404 of file App/Application.h.
Referenced by Gui::Application::runApplication().
getCmdLineFiles()
std::list< std::string > Application::getCmdLineFiles () static
Definition at line 2842 of file App/Application.cpp.
References src.Mod.AddonManager.NetworkManager::count, DrawingExample::file, and SplineSurface::i.
Referenced by processCmdLineFiles().
getDocument()
App::Document * Application::getDocument (const char * Name) const
Retrieve a named document.
Definition at line 588 of file App/Application.cpp.
References RobotExample::pos.
Referenced by ExpressionCompleterModel::_data(), PartGui::Mirroring::accept(), SpreadsheetGui::DlgBindSheet::accept(), DrawingGui::TaskDlgOrthoViews::accept(), PartGui::DlgScale::apply(), PartGui::DlgExtrusion::apply(), PartDesignGui::TaskFeaturePick::buildFeatures(), Gui::SoFCUnifiedSelection::doAction(), App::PropertyLinkBase::exportSubName(), Gui::Application::exportTo(), App::DocumentT::getDocument(), App::DocumentObjectT::getDocument(), Gui::Application::getDocument(), Gui::Command::getDocument(), App::ObjectIdentifier::getDocument(), Gui::SelectionSingleton::getDocument(), Gui::SelectionObject::getObject(), Attacher::AttachEngine::getRefObjects(), PartGui::DlgExtrusion::getShapesToExtrude(), PartGui::DlgScale::getShapesToScale(), ExpressionCompleterModel::modelIndexToParentInfo(), App::PropertyXLink::Paste(), StdCmdExpression::pasteExpressions(), DrawingGui::TaskDlgOrthoViews::reject(), Gui::AutoSaver::saveDocument(), Gui::QuantitySpinBox::setBoundToByName(), Gui::SelectionSingleton::setVisible(), and PartGui::DlgScale::validate().
getDocumentByPath()
Document * Application::getDocumentByPath (const char * path, PathMatchMode checkCanonical = PathMatchMode::MatchAbsolute) const
Retrieve a document based on file path
Parameters
path file path
checkCanonical file path matching mode,
See also
PathMatchMode.
Returns
Return the document found by matching with the given path
Definition at line 711 of file App/Application.cpp.
References FC_WARN, DrawingExample::file, Base::FileInfo::filePath(), ifctree::filepath, Path.Preferences::filePath(), MatchAbsolute, MatchCanonical, and TestSpreadsheet::v.
Referenced by openDocumentPrivate(), and openDocuments().
getDocumentName()
const char * Application::getDocumentName (const App::Document * doc) const
gets the (internal) name of the document
Definition at line 600 of file App/Application.cpp.
References toolbit-attributes::doc.
Referenced by dressupGetSelected(), Gui::Document::saveAs(), and Gui::Document::saveCopy().
getDocuments()
std::vector< App::Document * > Application::getDocuments () const
get a list of all documents in the application
Definition at line 611 of file App/Application.cpp.
Referenced by ExpressionCompleterModel::_data(), StdCmdToggleSelectability::activated(), Gui::MainWindow::closeAllDocuments(), Gui::TreeWidget::contextMenuEvent(), createVarSetTreeWidget(), TechDrawGui::DrawGuiUtil::findPage(), getAllVarSets(), App::ObjectIdentifier::getDocument(), Gui::Dialog::DlgPropertyLink::init(), StdCmdCloseAllWindows::isActive(), Cloud::Module::LinkXSetValue(), ExpressionCompleterModel::modelIndexToParentInfo(), TechDrawGui::DrawGuiUtil::needPage(), Gui::Document::saveAll(), PartGui::DlgSettings3DViewPart::saveSettings(), and Attacher::AttachEngine::verifyReferencesAreSafe().
getExecutableName()
std::string Application::getExecutableName () static
Definition at line 1142 of file App/Application.cpp.
Referenced by Gui::Dialog::DocumentRecoveryHandler::checkForPreviousCrashes(), Gui::Dialog::AboutDialog::copyToClipboard(), Gui::StdCmdDownloadOnlineHelp::createAction(), Gui::SoFCOffscreenRenderer::createMIBA(), App::Document::getTransientDirectoryName(), Gui::StdCmdDownloadOnlineHelp::languageChange(), Gui::Dialog::ApplicationCache::periodicCheckOfSize(), Gui::GUISingleApplication::Private::Private(), Import::WriterStep::write(), and Gui::SoFCOffscreenRenderer::writeToImageFile().
getExportFilters() [1/2]
std::map< std::string, std::string > Application::getExportFilters () const
Return a list of all export filters.
Definition at line 1574 of file App/Application.cpp.
getExportFilters() [2/2]
std::map< std::string, std::string > Application::getExportFilters (const char * Type) const
Return the export filters with modules of a given filetype.
Definition at line 1556 of file App/Application.cpp.
Referenced by StdCmdExport::activated(), and Gui::SelectModule::exportHandler().
getExportModules() [1/2]
std::vector< std::string > Application::getExportModules () const
Return a list of all modules.
Definition at line 1518 of file App/Application.cpp.
References bimcommands::modules.
getExportModules() [2/2]
std::vector< std::string > Application::getExportModules (const char * Type) const
Return a list of modules that support the given filetype.
Definition at line 1500 of file App/Application.cpp.
References bimcommands::modules.
Referenced by processCmdLineFiles().
getExportTypes() [1/2]
std::vector< std::string > Application::getExportTypes () const
Return a list of all filetypes.
Definition at line 1543 of file App/Application.cpp.
getExportTypes() [2/2]
std::vector< std::string > Application::getExportTypes (const char * Module) const
Return a list of filetypes that are supported by a module.
Definition at line 1528 of file App/Application.cpp.
getHelpDir()
std::string Application::getHelpDir () static
Definition at line 1206 of file App/Application.cpp.
Referenced by Gui::Dialog::DlgOnlineHelpImp::getStartpage(), Gui::Dialog::AboutDialog::showCollectionInformation(), Gui::Dialog::AboutDialog::showLibraryInformation(), and Gui::Dialog::AboutDialog::showLicenseInformation().
getHomePath()
std::string Application::getHomePath () static
Definition at line 1137 of file App/Application.cpp.
Referenced by Gui::Dialog::AboutDialog::aboutImage(), Gui::StdCmdDownloadOnlineHelp::activated(), Gui::MacroCommand::activated(), Fem::Tools::checkIfBinaryExists(), Gui::Dialog::DlgCustomActionsImp::DlgCustomActionsImp(), Gui::Dialog::DlgMacroExecuteImp::fillUpList(), Gui::BitmapFactoryInst::instance(), Gui::PyResource::load(), Gui::ApplicationPy::sAddIconPath(), Gui::ApplicationPy::sAddLangPath(), Gui::ApplicationPy::sAddResPath(), and Gui::SplashScreen::splashImage().
getImportFilters() [1/2]
std::map< std::string, std::string > Application::getImportFilters () const
Return a list of all import filters.
Definition at line 1451 of file App/Application.cpp.
getImportFilters() [2/2]
std::map< std::string, std::string > Application::getImportFilters (const char * Type) const
Return the import filters with modules of a given filetype.
Definition at line 1433 of file App/Application.cpp.
Referenced by StdCmdOpen::activated(), StdCmdImport::activated(), Gui::Application::exportTo(), and Gui::SelectModule::importHandler().
getImportModules() [1/2]
std::vector< std::string > Application::getImportModules () const
Return a list of all modules.
Definition at line 1395 of file App/Application.cpp.
References bimcommands::modules.
getImportModules() [2/2]
std::vector< std::string > Application::getImportModules (const char * Type) const
Return a list of modules that support the given filetype.
Definition at line 1377 of file App/Application.cpp.
References bimcommands::modules.
Referenced by Gui::MainWindow::loadUrls(), processFiles(), and Gui::ApplicationPy::sLoadFile().
getImportTypes() [1/2]
std::vector< std::string > Application::getImportTypes () const
Return a list of all filetypes.
Definition at line 1420 of file App/Application.cpp.
getImportTypes() [2/2]
std::vector< std::string > Application::getImportTypes (const char * Module) const
Return a list of filetypes that are supported by a module.
Definition at line 1405 of file App/Application.cpp.
Referenced by StdCmdOpen::activated(), and StdCmdImport::activated().
getLibraryDir()
std::string Application::getLibraryDir () static
Definition at line 1192 of file App/Application.cpp.
getLinksTo()
std::set< DocumentObject * > Application::getLinksTo (const DocumentObject * obj, int options, int maxCount = 0) const
Return the links to a given object
Parameters
obj the linked object. If NULL, then all links are returned.
option
See also
App::GetLinkOption
Parameters
maxCount limit the number of links returned, 0 means no limit
Definition at line 1247 of file App/Application.cpp.
References App::DocumentObject::getInList(), src.Mod.Test.testPathArray::o, and TestSpreadsheet::v.
Referenced by hasLinksTo().
GetParameterGroupByPath()
Base::Reference< ParameterGrp > Application::GetParameterGroupByPath (const char * sName)
Gets a parameter group by a full qualified path It's an easy method to get a group:
// getting standard parameter
ParameterGrp::handle hGrp = App::GetApplication().GetParameterGroupByPath("User parameter:BaseApp/Preferences/Mod/Raytracing");
std::string cDir             = hGrp->GetASCII("ProjectPath", "");
std::string cCameraName      = hGrp->GetASCII("CameraName", "TempCamera.inc");
Definition at line 1316 of file App/Application.cpp.
References RobotExample::pos.
Referenced by _GetParam(), Gui::Dialog::DlgAddProperty::accept(), Gui::Dialog::DlgAddPropertyVarSet::accept(), Gui::StdCmdDownloadOnlineHelp::activated(), StdCmdDlgPreferences::activated(), StdCmdOnlineHelpWebsite::activated(), StdCmdFreeCADDonation::activated(), StdCmdFreeCADWebsite::activated(), StdCmdFreeCADUserHub::activated(), StdCmdFreeCADPowerUserHub::activated(), StdCmdNew::activated(), StdCmdFreeCADForum::activated(), StdCmdFreeCADFAQ::activated(), StdCmdReportBug::activated(), Gui::MacroCommand::activated(), StdCmdUserEditMode::activated(), StdCmdViewHome::activated(), StdViewScreenShot::activated(), CmdSketcherConstrainLock::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadiam::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), Gui::Application::activateWorkbench(), Gui::MainWindow::activateWorkbench(), App::DynamicProperty::addDynamicProperty(), Gui::Dialog::DlgSettingsNavigation::addOrientations(), Gui::WorkbenchGroup::addTo(), Gui::RecentMacrosAction::appendFile(), Gui::Application::Application(), CmdSketcherConstrainLock::applyConstraint(), Gui::ViewProviderLine::attach(), Gui::ViewProviderPlane::attach(), Gui::ViewProviderDatum::attach(), Gui::ViewProviderPoint::attach(), PartDesignGui::ViewProviderDatumPoint::attach(), Gui::Gui::GestureNavigationStyle ::AwaitingMoveState::AwaitingMoveState(), Gui::Application::checkForDeprecatedSettings(), Fem::Tools::checkIfBinaryExists(), Cloud::Module::cloudSave(), CmdSketcherConstrainCoincident::CmdSketcherConstrainCoincident(), CmdSketcherConstrainCoincidentUnified::CmdSketcherConstrainCoincidentUnified(), StartGui::StartView::configureRecentFilesListWidget(), SketcherGui::ConstraintFilterList::ConstraintFilterList(), Gui::TreeWidget::contextMenuEvent(), copyTemplateParameters(), Gui::Dialog::AboutDialog::copyToClipboard(), StdCmdUserEditMode::createAction(), PartGui::ViewProvider2DObjectGrid::createGrid(), MatGui::MaterialTreeWidget::createLayout(), DrawSketchHandlerDimension::createRadiusDiameterConstrain(), TDHandlerDimension::createRadiusDiameterDimension(), Gui::CreateViewStdCommands(), SketcherGui::CurveConverter::CurveConverter(), Gui::View3DInventor::customEvent(), Import::ExportOCAF2::customExportOptions(), Import::ImportOCAF2::customImportOptions(), ConstraintItem::data(), Materials::MaterialManager::defaultAppearance(), Materials::MaterialManager::defaultMaterialUUID(), Gui::ViewProviderCoordinateSystem::defaultSize(), TechDrawGui::QGVPage::Private::detach(), Gui::Dialog::DlgAddProperty::DlgAddProperty(), Gui::Dialog::DlgCustomActionsImp::DlgCustomActionsImp(), MeshGui::DlgEvaluateMeshImp::DlgEvaluateMeshImp(), Gui::Dialog::DlgExpressionInput::DlgExpressionInput(), PartGui::DlgSettings3DViewPart::DlgSettings3DViewPart(), FemGui::DlgSettingsFemGeneralImp::DlgSettingsFemGeneralImp(), Gui::Document::Document(), App::Document::Document(), DrawingGui::DrawingView::DrawingView(), Gui::ElementColors::ElementColors(), SketcherGui::ElementFilterList::ElementFilterList(), AssemblyGui::ViewProviderAssembly::endMove(), Gui::PropertyEditor::PropertyEditor::eventFilter(), Assembly::AssemblyObject::execute(), Gui::GraphvizView::exportGraph(), App::Document::exportGraphviz(), Gui::Application::exportTo(), MeshGui::ViewProviderMesh::faceInfoCallback(), FemGui::FemSettings::FemSettings(), Gui::PythonTracing::fetchFromSettings(), FileCardDelegate::FileCardDelegate(), MatGui::MaterialTreeWidget::fillMaterialTree(), TDHandlerDimension::finalizeCommand(), DrawSketchHandlerDimension::finalizeCommand(), finishDatumConstraint(), StartGui::StartView::firstStartWidgetDismissed(), Gui::GestureNavigationStyle::GestureNavigationStyle(), Gui::Gui::GestureNavigationStyle ::GestureState::GestureState(), TechDrawGui::PreferencesGui::get3dMarkerSize(), PathGui::ViewProviderPath::getBoundColor(), Gui::ViewProviderGeometryObject::getBoundColor(), Spreadsheet::Sheet::getCharsFromPrefs(), Gui::ToolHandler::getCrosshairColor(), Path::Toolpath::getCycleTime(), App::Material::getDefaultAppearance(), Gui::Dialog::DlgSettingsWorkbenchesImp::getDisabledWorkbenches(), Gui::Dialog::DlgSettingsWorkbenchesImp::getEnabledWorkbenches(), MatGui::MaterialTreeWidget::getFavorites(), Gui::View3DInventorViewer::getInternalTextureFormat(), Materials::MaterialLoader::getMaterialLibraries(), TechDrawGui::QGVPage::getNavStyleParameter(), getPreferencesViewParameter(), MatGui::MaterialTreeWidget::getRecents(), getSketcherGeneralParameter(), Part::Feature::getSubObject(), Gui::GraphicsView3D::GraphicsView3D(), Gui::GraphvizView::GraphvizView(), StartGui::FileCardView::heightForWidth(), horVerActivated(), TechDrawGui::DrawGuiUtil::iconForLine(), Gui::Application::importFrom(), TechDrawGui::QGVNavStyle::initialize(), Gui::NavigationStyle::initialize(), Gui::ExpressionParameter::isCaseSensitive(), Gui::ExpressionParameter::isExactMatch(), Gui::PreferencePackManager::isVisible(), Gui::WorkbenchTabWidget::itemStyle(), AssemblyGui::ViewProviderAssembly::keyPressed(), StartGui::StartLauncher::Launch(), Gui::MacroCommand::load(), TechDrawGui::DrawGuiUtil::loadArrowBox(), TechDrawGui::DrawGuiUtil::loadBalloonShapeBox(), TechDrawGui::DrawGuiUtil::loadMattingStyleBox(), PartGui::ViewProviderPartExt::loadParameter(), InspectionGui::VisualInspection::loadSettings(), Gui::Dialog::DlgSettingsNavigation::loadSettings(), Gui::Dialog::DlgSettingsGeneral::loadSettings(), TechDrawGui::DlgPrefsTechDrawDimensionsImp::loadSettings(), FemGui::DlgSettingsFemExportAbaqusImp::loadSettings(), FemGui::DlgSettingsFemInOutVtkImp::loadSettings(), SpreadsheetGui::DlgSettingsImp::loadSettings(), FemGui::DlgSettingsFemGmshImp::loadSettings(), SketcherGui::SketcherSettings::loadSettings(), MeshGui::DlgSettingsImportExport::loadSettings(), FemGui::DlgSettingsFemZ88Imp::loadSettings(), FemGui::DlgSettingsFemCcxImp::loadSettings(), Gui::Dialog::DlgSettingsNotificationArea::loadSettings(), Gui::Dialog::DlgSettingsWorkbenchesImp::loadSettings(), SketcherGui::SketcherSettingsGrid::loadSettings(), SketcherGui::SketcherSettingsAppearance::loadSettings(), Gui::Dialog::DlgSettingsGeneral::loadThemes(), Gui::MacroManager::MacroManager(), Gui::MainWindow::MainWindow(), Assembly::AssemblyObject::makeMbdAssembly(), Materials::MaterialFilterOptions::MaterialFilterOptions(), Materials::MaterialFilterTreeWidgetOptions::MaterialFilterTreeWidgetOptions(), CmdSketcherConstrainCoincidentUnified::onActivated(), SketcherGui::TaskSketcherConstraints::OnChange(), PathGui::ViewProviderPath::onChanged(), PartDesignGui::ViewProviderSubShapeBinder::onChanged(), SketcherGui::TaskSketcherElements::onFilterBoxStateChanged(), SketcherGui::TaskSketcherConstraints::onFilterBoxStateChanged(), SketcherGui::TaskSketcherConstraints::onFilterListItemChanged(), Gui::Dialog::DlgSettingsGeneral::onLinkActivated(), SketcherGui::TaskSketcherElements::onListMultiFilterItemChanged(), Gui::GestureNavigationStyle::onRollGesture(), SketcherGui::TaskSketcherConstraints::onSettingsAutoConstraintsChanged(), SketcherGui::TaskSketcherConstraints::onSettingsAutoRemoveRedundantChanged(), SketcherGui::TaskSketcherElements::onSettingsExtendedInformationChanged(), SketcherGui::TaskSketcherConstraints::onSettingsExtendedInformationChanged(), SketcherGui::TaskSketcherConstraints::onSettingsHideInternalAligmentChanged(), SketcherGui::TaskSketcherConstraints::onSettingsRestrictVisibilityChanged(), Gui::OverlayManager::Private::onTimer(), Gui::Application::open(), openDocuments(), OverlayStyleSheet::OverlayStyleSheet(), Gui::NotificationArea::ParameterObserver::ParameterObserver(), FemGui::DlgSettingsFemGmshImp::populateLogVerbosity(), Gui::Dialog::DlgSettingsUI::populateStylesheets(), StartGui::StartView::postStart(), TechDrawGui::QGVPage::Private::Private(), Gui::RecentFilesAction::Private::Private(), Gui::PropertyEditor::PropertyEditor::PropertyEditor(), PyMOD_INIT_FUNC(), Gui::Multisample::readMSAAFromSettings(), Start::RecentFilesModel::RecentFilesModel(), App::Document::recompute(), Gui::OverlayTabWidget::refreshIcons(), Gui::WorkbenchComboBox::refreshList(), SketcherGui::TaskDlgEditSketch::reject(), DrawSketchHandlerBSplineInsertKnot::releaseButton(), Gui::Application::replaceVariablesInQss(), Gui::Dialog::DlgSettings3DViewImp::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsNavigation::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsGeneral::resetSettingsToDefaults(), TechDrawGui::DlgPrefsTechDrawDimensionsImp::resetSettingsToDefaults(), SketcherGui::SketcherSettings::resetSettingsToDefaults(), Gui::Dialog::DlgSettingsWorkbenchesImp::resetSettingsToDefaults(), Gui::Dialog::PreferencePage::resetSettingsToDefaults(), Gui::ViewProviderDatum::resetTemporarySize(), ZoomableView::resetZoom(), Part::PropertyPartShape::RestoreDocFile(), Gui::MDIView::restorePrinterSettings(), Gui::GraphvizWorker::run(), Gui::Document::Save(), App::Document::save(), Gui::MacroCommand::save(), Part::PropertyPartShape::SaveDocFile(), Gui::AutoSaver::saveDocument(), MatGui::MaterialTreeWidget::saveMaterialTree(), MeshPartGui::Tessellation::saveParameters(), Gui::View3DInventorViewer::savePicture(), Gui::MDIView::savePrinterSettings(), MatGui::MaterialTreeWidget::saveRecents(), InspectionGui::VisualInspection::saveSettings(), Gui::Dialog::DlgSettingsNavigation::saveSettings(), Gui::Dialog::DlgSettingsGeneral::saveSettings(), TechDrawGui::DlgPrefsTechDrawDimensionsImp::saveSettings(), SpreadsheetGui::DlgSettingsImp::saveSettings(), FemGui::DlgSettingsFemInOutVtkImp::saveSettings(), FemGui::DlgSettingsFemExportAbaqusImp::saveSettings(), SketcherGui::SketcherSettings::saveSettings(), MeshGui::DlgSettingsImportExport::saveSettings(), FemGui::DlgSettingsFemZ88Imp::saveSettings(), FemGui::DlgSettingsFemCcxImp::saveSettings(), Gui::Dialog::DlgSettingsNotificationArea::saveSettings(), Gui::Dialog::DlgSettingsWorkbenchesImp::saveSettings(), SketcherGui::SketcherSettingsGrid::saveSettings(), SketcherGui::SketcherSettingsAppearance::saveSettings(), Gui::Dialog::DlgSettingsGeneral::saveThemes(), App::Document::saveToFile(), MatGui::MaterialTreeWidget::saveWidgetSettings(), Gui::SelectionSingleton::selStackPush(), SketcherGui::ViewProviderSketch::setEditViewer(), Gui::WindowParameter::setGroupName(), Gui::DocumentObjectItem::setHighlight(), Gui::Dialog::DlgCheckableMessageBox::setIconPixmap(), Import::ImpExpDxfRead::setOptions(), Import::ImpExpDxfWrite::setOptions(), Gui::StatefulLabel::setParameterGroup(), Gui::InputField::setParamGrpPath(), Gui::StartupProcess::setupApplication(), Sketcher::SketchObject::setupObject(), FemGui::ViewProviderFemPostObject::setupPipeline(), TechDrawGui::Workbench::setupToolBars(), Gui::MainWindow::setWindowTitle(), Gui::ApplicationPy::sGetMarkerIndex(), SpreadsheetGui::SheetModel::SheetModel(), Gui::Dialog::DlgPreferencePackManagementImp::showAddonManager(), StartGui::StartView::showOnStartupChanged(), PartDesignGui::TaskHelixParameters::showPreview(), ShowRestoreInformationLayer(), Gui::View3DInventorViewer::showRotationCenter(), SketcherGui::SketcherAddWorkbenchConstraints< Gui::MenuItem >(), SketcherGui::SketcherAddWorkbenchConstraints< Gui::ToolBarItem >(), Gui::Application::slotActiveDocument(), Gui::DocumentItem::slotInEdit(), Gui::View3DInventorViewer::startAnimation(), Gui::StatefulLabel::StatefulLabel(), StdCmdRefresh::StdCmdRefresh(), Gui::OverlayTabWidget::syncAutoMode(), SketcherGui::TaskDlgEditSketch::TaskDlgEditSketch(), SketcherGui::TaskSketcherElements::TaskSketcherElements(), SketcherGui::TaskSketcherMessages::TaskSketcherMessages(), MeshPartGui::Tessellation::Tessellation(), StartGui::ThemeSelectorWidget::themeChanged(), Gui::PreferencePackManager::toggleVisibility(), SketcherGui::tryAutoRecompute(), Gui::RecentFilesAction::Private::trySaveUserParameter(), TYPESYSTEM_SOURCE_ABSTRACT(), SketcherGui::ViewProviderSketch::unsetEdit(), SketcherGui::TaskSketcherSolverAdvanced::updateDefaultMethodParameters(), SketcherGui::TaskSketcherSolverAdvanced::updateRedundantMethodParameters(), Gui::View3DInventorPy::viewDefaultOrientation(), Gui::ViewParams::ViewParams(), Gui::ViewProviderAnnotation::ViewProviderAnnotation(), PartDesignGui::ViewProviderDatum::ViewProviderDatum(), PartDesignGui::ViewProviderDatumCoordinateSystem::ViewProviderDatumCoordinateSystem(), PartGui::ViewProviderPartExt::ViewProviderPartExt(), PathGui::ViewProviderPath::ViewProviderPath(), PartDesignGui::ViewProviderShapeBinder::ViewProviderShapeBinder(), Path::PathSegmentWalker::walk(), SandboxGui::Workbench::Workbench(), Gui::Multisample::writeMSAAToSettings(), MeshGui::DlgEvaluateMeshImp::~DlgEvaluateMeshImp(), and SketcherGui::TaskSketcherConstraints::~TaskSketcherConstraints().
GetParameterSet()
ParameterManager * Application::GetParameterSet (const char * sName) const
Definition at line 1284 of file App/Application.cpp.
Referenced by Gui::RecentMacrosAction::appendFile(), Gui::Dialog::DlgParameterImp::DlgParameterImp(), Gui::Dialog::DlgParameterImp::onButtonSaveToDiskClicked(), Gui::Dialog::DlgParameterImp::onChangeParameterSet(), and Gui::RecentFilesAction::Private::saveUserParameter().
GetParameterSetList()
const std::map< std::string, Base::Reference< ParameterManager > > & Application::GetParameterSetList () const
Definition at line 1294 of file App/Application.cpp.
Referenced by Gui::Dialog::DlgParameterImp::DlgParameterImp(), and Gui::WindowParameter::setGroupName().
getResourceDir()
std::string Application::getResourceDir () static
Definition at line 1177 of file App/Application.cpp.
Referenced by RobotGui::Workbench::activated(), Start::ExamplesModel::ExamplesModel(), Drawing::FeaturePage::execute(), Drawing::FeaturePage::getEditableTextsFromTemplate(), Materials::MaterialLoader::getMaterialLibraries(), getResourcePrefPacksPath(), loadTechDrawResource(), Drawing::FeaturePage::onDocumentRestored(), pagesize(), TechDraw::DrawTileWeld::prefSymbol(), Import::ImpExpDxfWrite::setOptions(), TechDrawGui::SymbolChooser::setUiPrimary(), Gui::PreferencePackManager::templateFiles(), and TechDrawGui::PreferencesGui::weldingDirectory().
GetSystemParameter()
ParameterManager & Application::GetSystemParameter ()
returns the system parameter
Definition at line 1274 of file App/Application.cpp.
getTempFileName()
std::string Application::getTempFileName (const char * FileName = nullptr) static
Definition at line 1152 of file App/Application.cpp.
References Base::FileInfo::getTempFileName(), and getTempPath().
Referenced by StdCmdDuplicateSelection::activated(), App::Document::copyObject(), Gui::MainWindow::createMimeDataFromSelection(), App::Document::importLinks(), MeshPartGui::Mesh2ShapeGmsh::Mesh2ShapeGmsh(), MeshGui::RemeshGmsh::RemeshGmsh(), Fem::FemMesh::RestoreDocFile(), Fem::PropertyPostDataObject::RestoreDocFile(), Fem::FemMesh::SaveDocFile(), and Fem::PropertyPostDataObject::SaveDocFile().
getTempPath()
std::string Application::getTempPath () static
Returns the temporary directory. By default, this is set to the system's temporary directory but can be customized by the user.
Definition at line 1147 of file App/Application.cpp.
Referenced by getTempFileName().
getUniqueDocumentName()
std::string Application::getUniqueDocumentName (const char * Name, bool tempDoc = false) const
find a unique document name
Definition at line 619 of file App/Application.cpp.
References Base::Tools::getIdentifier(), Base::Tools::getUniqueName(), femtools.tokrules::names, RobotExample::pos, and App::Document::TempDoc.
Referenced by Cloud::Module::LinkXSetValue(), and newDocument().
getUserAppDataDir()
std::string Application::getUserAppDataDir () static
Definition at line 1167 of file App/Application.cpp.
Referenced by Gui::Dialog::AboutDialog::copyToClipboard(), Materials::MaterialLoader::getMaterialLibraries(), getSavedPrefPacksPath(), Gui::BitmapFactoryInst::instance(), Gui::PreferencePackManager::modPaths(), Drawing::FeaturePage::onDocumentRestored(), and Gui::PythonConsoleP::PythonConsoleP().
getUserCachePath()
std::string Application::getUserCachePath () static
Definition at line 1157 of file App/Application.cpp.
Referenced by Gui::Dialog::DocumentRecoveryHandler::checkForPreviousCrashes(), Gui::Dialog::DlgSettingsCacheDirectory::DlgSettingsCacheDirectory(), App::Document::getTransientDirectoryName(), Gui::Dialog::DocumentRecovery::onDeleteSection(), Gui::Dialog::ApplicationCache::performAction(), Gui::Dialog::DlgEditFileIncludePropertyExternal::processFile(), and Gui::Dialog::ApplicationCache::size().
getUserConfigPath()
std::string Application::getUserConfigPath () static
Definition at line 1162 of file App/Application.cpp.
getUserMacroDir()
std::string Application::getUserMacroDir () static
Definition at line 1172 of file App/Application.cpp.
Referenced by Gui::MacroCommand::activated(), Gui::Dialog::DlgCustomActionsImp::DlgCustomActionsImp(), Gui::Dialog::DlgMacroExecuteImp::DlgMacroExecuteImp(), Gui::Dialog::DlgMacroRecordImp::DlgMacroRecordImp(), and Gui::PythonConsole::onSaveHistoryAs().
GetUserParameter()
ParameterManager & Application::GetUserParameter ()
returns the user parameter
Definition at line 1279 of file App/Application.cpp.
Referenced by Gui::Dialog::DlgRevertToBackupConfigImp::accept(), Gui::StdCmdDownloadOnlineHelp::activated(), StdCmdImport::activated(), StdCmdExport::activated(), StdViewScreenShot::activated(), Gui::ParamHandlers::addDelayedHandler(), Gui::ParamHandlers::addHandler(), Gui::Application::Application(), PartGui::DlgScale::apply(), PartGui::DlgExtrusion::apply(), Gui::PreferencePack::apply(), Gui::Dialog::DlgSettingsGeneral::attachObserver(), PartDesign::Body::Body(), Gui::Dialog::DlgParameterImp::closeEvent(), Gui::MainWindow::confirmSave(), Gui::DialogOptions::dontUseNativeColorDialog(), Gui::DialogOptions::dontUseNativeFileDialog(), Gui::MainWindow::event(), Gui::WindowParameter::getDefaultParameter(), TechDrawGui::QGIView::getParmGroupCol(), Part::getRefineModelParameter(), PartGui::TaskCheckGeometryResults::goCheck(), SketcherGui::hideUnits(), PartDesignGui::TaskFeaturePick::isSingleSelectionEnabled(), Gui::DockWindowManager::loadState(), Gui::MainWindow::MainWindow(), Gui::DAG::Model::Model(), Gui::Notify(), Gui::Dialog::DlgParameterImp::onChangeParameterSet(), OverlayInfo::OverlayInfo(), PyMOD_INIT_FUNC(), Import::ReaderIges::read(), Gui::FileDialog::restoreLocation(), Gui::MacroManager::run(), Gui::FileDialog::saveLocation(), Gui::ToolBarManager::setup(), Gui::StdWorkbench::setupDockWindows(), App::PropertyString::setValue(), SketcherGui::showCursorCoords(), Gui::Dialog::DlgParameterImp::showEvent(), Gui::MainWindow::startSplasher(), PartGui::TaskCheckGeometryDialog::TaskCheckGeometryDialog(), Part::throwIfInvalidIfCheckModel(), SketcherGui::useSystemDecimals(), and Import::WriterStep::write().
hasLinksTo()
bool Application::hasLinksTo (const DocumentObject * obj) const
Check if there is any link to the given object.
Definition at line 1270 of file App/Application.cpp.
References getLinksTo().
Referenced by StdCmdLinkSelectAllLinks::isActive().
init()
void Application::init (int argc, char ** argv) static
Definition at line 1926 of file App/Application.cpp.
References destructObserver(), freecadNewHandler(), initTypes(), segmentation_fault_handler(), unexpection_error_handler(), and unhandled_exception_handler().
Referenced by DocumentObject.DocumentObject::onChanged().
initTypes()
void Application::initTypes () static
Definition at line 1962 of file App/Application.cpp.
References Base::Persistence::getClassTypeId(), SIM::Coin3D::Quarter::Quarter::init(), App::DocumentObjectExtension::init(), App::LinkBaseExtension::init(), Base::Persistence::init(), App::ExtensionPythonT< ExtensionT >::init(), Base::BaseClass::init(), Base::Type::init(), Base::Exception::init(), App::Extension::init(), Base::AbortException::init(), and App::LinkExtension::init().
Referenced by init().
isClosingAll()
bool Application::isClosingAll () const
Indicate the application is closing all document.
Definition at line 667 of file App/Application.cpp.
isRestoring()
bool Application::isRestoring () const
Indicate whether the application is opening (restoring) some document.
Definition at line 663 of file App/Application.cpp.
References App::Document::isAnyRestoring().
Referenced by App::PropertyXLink::setAllowPartial().
newDocument()
Document * Application::newDocument (const char * Name = nullptr, const char * UserName = nullptr, bool createView = true, bool tempDoc = false)
Creates a new document The first name is a the identifier and some kind of an internal (english) name. It has to be like an identifier in a programming language, with no spaces and not starting with a number. This name gets also forced to be unique in this Application. You can avoid the renaming by using getUniqueDocumentName() to get a unique name before calling newDoucument(). The second name is a UTF8 name of any kind. It's that name normally shown to the user and stored in the App::Document::Name property.
Definition at line 455 of file App/Application.cpp.
References draftgeoutils.faces::bind(), toolbit-attributes::doc, App::Document::getPyObject(), getUniqueDocumentName(), Base::Tools::getUniqueName(), App::Document::Label, femtools.tokrules::names, RobotExample::pos, setActiveDocument(), App::PropertyString::setValue(), App::Document::signalAbortTransaction, App::Document::signalActivatedObject, App::Document::signalBeforeChange, App::Document::signalBeforeChangeObject, App::Document::signalBeforeRecompute, App::Document::signalChanged, App::Document::signalChangedObject, App::Document::signalChangePropertyEditor, App::Document::signalCommitTransaction, App::Document::signalDeletedObject, App::Document::signalFinishSave, signalNewDocument, App::Document::signalNewObject, App::Document::signalOpenTransaction, App::Document::signalRecomputed, App::Document::signalRecomputedObject, App::Document::signalRedo, App::Document::signalRelabelObject, App::Document::signalStartSave, App::Document::signalUndo, slotAbortTransaction(), slotActivatedObject(), slotBeforeChangeDocument(), slotBeforeChangeObject(), slotBeforeRecompute(), slotChangedDocument(), slotChangedObject(), slotChangePropertyEditor(), slotCommitTransaction(), slotDeletedObject(), slotFinishSaveDocument(), slotNewObject(), slotOpenTransaction(), slotRecomputed(), slotRecomputedObject(), slotRedoDocument(), slotRelabelObject(), slotStartSaveDocument(), slotUndoDocument(), and App::Document::TempDoc.
Referenced by Part::Feature::create(), Gui::MainWindow::insertFromMimeData(), Cloud::Module::LinkXSetValue(), openDocumentPrivate(), and PartDesign::SubShapeBinder::update().
openDocument()
Document * Application::openDocument (const char * FileName = nullptr, bool createView = true)
Open an existing document from a file.
Definition at line 703 of file App/Application.cpp.
References openDocuments().
Referenced by processFiles(), Gui::Application::reopen(), and App::PropertyXLink::setAllowPartial().
openDocumentPrivate()
Document * Application::openDocumentPrivate (const char * FileName, const char * propFileName, const char * label, bool isMainDoc, bool createView, std::vector< std::string > && objNames) protected
open single document only
Definition at line 951 of file App/Application.cpp.
References closeDocument(), toolbit-attributes::doc, Base::FileInfo::exists(), App::Document::FileName, Base::FileInfo::fileNamePure(), Base::FileInfo::filePath(), getDocumentByPath(), App::Document::getName(), App::PropertyString::getValue(), MatchCanonicalWarning, Path.Post.scripts.opensbp_post::move(), newDocument(), App::Document::PartialDoc, App::PartialObject, App::Document::PartialRestore, App::Document::restore(), App::PropertyString::setValue(), and Path.Post.scripts.refactored_centroid_post::str.
Referenced by openDocuments().
openDocuments()
std::vector< Document * > Application::openDocuments (const std::vector< std::string > & filenames, const std::vector< std::string > * paths = nullptr, const std::vector< std::string > * labels = nullptr, std::vector< std::string > * errs = nullptr, bool createView = true)
Open multiple documents
Parameters
filenames input file names
paths optional input file path in case it is different from filenames (mainly used during recovery).
labels optional label assign to document (mainly used during recovery).
errs optional output error message corresponding to each input file name. If errs is given, this function will catch all Base::Exception and save the error message inside. Otherwise, it will throw on exception when opening the input files.
createView whether to signal Gui module to create view on restore.
Returns
Return opened document object corresponding to each input file name, which maybe NULL if failed.
This function will also open any external referenced files.
Definition at line 746 of file App/Application.cpp.
References closeDocument(), Base::Console(), src.Mod.AddonManager.NetworkManager::count, toolbit-attributes::doc, SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), FC_DURATION_LOG, FC_DURATION_PLUS, FC_TIME_INIT, FC_TIME_LOG, DrawingExample::file, ParameterGrp::GetBool(), App::Document::getDependentDocuments(), getDocumentByPath(), GetParameterGroupByPath(), App::ExpressionParser::labels, Path.Post.scripts.opensbp_post::move(), Base::SequencerLauncher::next(), openDocumentPrivate(), App::PropertyXLink::restoreDocument(), setActiveDocument(), signalFinishOpenDocument, signalStartOpenDocument, InitGui::t, and src.Mod.PartDesign.Scripts.Gear::t1.
Referenced by Gui::Dialog::DocumentRecovery::accept(), and openDocument().
processCmdLineFiles()
void Application::processCmdLineFiles () static
Definition at line 2927 of file App/Application.cpp.
References Config(), Base::Console(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), Base::Tools::escapeEncodeFilename(), create_qrc::ext, Base::FileInfo::extension(), DrawingExample::file, App::GetApplication(), getCmdLineFiles(), getExportModules(), Base::Interpreter(), Base::InterpreterSingleton::loadModule(), processFiles(), Base::InterpreterSingleton::runString(), Base::InterpreterSingleton::runStringArg(), and Base::ConsoleSingleton::Warning().
Referenced by runApplication().
processFiles()
std::list< std::string > Application::processFiles (const std::list< std::string > & files) static
Definition at line 2863 of file App/Application.cpp.
References Base::InterpreterSingleton::addPythonPath(), Base::Console(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), Base::Tools::escapedUnicodeFromUtf8(), Base::Tools::escapeEncodeFilename(), create_qrc::ext, DrawingExample::file, App::GetApplication(), getImportModules(), Base::Interpreter(), Base::InterpreterSingleton::loadModule(), Base::ConsoleSingleton::Log(), openDocument(), Base::InterpreterSingleton::runFile(), Base::InterpreterSingleton::runStringArg(), and Base::ConsoleSingleton::Warning().
Referenced by processCmdLineFiles().
RemoveParameterSet()
void Application::RemoveParameterSet (const char * sName)
Definition at line 1307 of file App/Application.cpp.
renameDocument()
void Application::renameDocument (const char * OldName, const char * NewName) protected
get called by the document when the name is changing
Definition at line 448 of file App/Application.cpp.
runApplication()
void Application::runApplication () static
Definition at line 2976 of file App/Application.cpp.
References Base::Console(), Base::Interpreter(), Base::ConsoleSingleton::Log(), processCmdLineFiles(), Base::InterpreterSingleton::runCommandLine(), Base::InterpreterSingleton::runString(), and Base::ScriptFactory().
setActiveDocument() [1/2]
void Application::setActiveDocument (App::Document * pDoc)
Set the active document.
Definition at line 1057 of file App/Application.cpp.
References App::Document::getPyObject(), and signalActiveDocument.
Referenced by closeDocument(), Cloud::Module::LinkXSetValue(), newDocument(), Gui::TreeWidget::onReloadDoc(), openDocuments(), App::Document::restore(), and setActiveDocument().
setActiveDocument() [2/2]
void Application::setActiveDocument (const char * Name)
Definition at line 1076 of file App/Application.cpp.
References RobotExample::pos, toolbit-attributes::s, and setActiveDocument().
setActiveTransaction()
int Application::setActiveTransaction (const char * name, bool persist = false)
Setup a pending application-wide active transaction
Parameters
name new transaction name
persist by default, if the calling code is inside any invocation of a command, it will be auto closed once all command within the current stack exists. To disable auto closing, set persist=true
Returns
The new transaction ID.
Call this function to setup an application-wide transaction. All current pending transactions of opening documents will be committed first. However, no new transaction is created by this call. Any subsequent changes in any current opening document will auto create a transaction with the given name and ID. If more than one document is changed, the transactions will share the same ID, and will be undo/redo together.
Definition at line 133 of file AutoTransaction.cpp.
References _TransactionLock, FC_LOG, FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, FC_WARN, getActiveTransaction(), App::Transaction::getNewID(), App::AutoTransaction::setEnable(), and TestSpreadsheet::v.
Referenced by PartDesignGui::DlgActiveBody::accept(), Gui::ExpressionBinding::apply(), Gui::TaskMeasure::apply(), Gui::ElementColors::Private::apply(), Gui::TreeWidgetItemDelegate::createEditor(), TechDrawGui::QGIViewAnnotation::mouseDoubleClickEvent(), TechDrawGui::QGIRichAnno::mouseDoubleClickEvent(), TechDrawGui::TaskDlgProjGroup::open(), Gui::Command::openCommand(), App::Document::openTransaction(), Gui::ExpressionBinding::setExpression(), PartDesignGui::TaskDressUpParameters::setupTransaction(), PartDesignGui::TaskTransformedParameters::setupTransaction(), App::PropertyString::setValue(), and Gui::TaskMeasure::TaskMeasure().
slotAbortTransaction()
void Application::slotAbortTransaction (const App::Document & d) protected
Definition at line 1663 of file App/Application.cpp.
References signalAbortTransaction.
Referenced by newDocument().
slotActivatedObject()
void Application::slotActivatedObject (const App::DocumentObject & O) protected
Definition at line 1623 of file App/Application.cpp.
References signalActivatedObject.
Referenced by newDocument().
slotBeforeChangeDocument()
void Application::slotBeforeChangeDocument (const App::Document & doc, const App::Property & prop) protected
Definition at line 1586 of file App/Application.cpp.
References signalBeforeChangeDocument.
Referenced by newDocument().
slotBeforeChangeObject()
void Application::slotBeforeChangeObject (const App::DocumentObject & O, const App::Property & Prop) protected
Definition at line 1608 of file App/Application.cpp.
References signalBeforeChangeObject.
Referenced by newDocument().
slotBeforeRecompute()
void Application::slotBeforeRecompute (const App::Document & doc) protected
Definition at line 1648 of file App/Application.cpp.
References signalBeforeRecomputeDocument.
Referenced by newDocument().
slotChangedDocument()
void Application::slotChangedDocument (const App::Document & doc, const App::Property & prop) protected
Definition at line 1591 of file App/Application.cpp.
References signalChangedDocument.
Referenced by newDocument().
slotChangedObject()
void Application::slotChangedObject (const App::DocumentObject & O, const App::Property & Prop) protected
Definition at line 1613 of file App/Application.cpp.
References signalChangedObject.
Referenced by newDocument().
slotChangePropertyEditor()
void Application::slotChangePropertyEditor (const App::Document & doc, const App::Property & prop) protected
Definition at line 1679 of file App/Application.cpp.
References signalChangePropertyEditor.
Referenced by newDocument().
slotCommitTransaction()
void Application::slotCommitTransaction (const App::Document & d) protected
Definition at line 1658 of file App/Application.cpp.
References signalCommitTransaction.
Referenced by newDocument().
slotDeletedObject()
void Application::slotDeletedObject (const App::DocumentObject & O) protected
Definition at line 1602 of file App/Application.cpp.
References signalDeletedObject.
Referenced by newDocument().
slotFinishSaveDocument()
void Application::slotFinishSaveDocument (const App::Document & doc, const std::string & filename) protected
Definition at line 1673 of file App/Application.cpp.
References signalFinishSaveDocument.
Referenced by newDocument().
slotNewObject()
void Application::slotNewObject (const App::DocumentObject & O) protected
Definition at line 1596 of file App/Application.cpp.
References signalNewObject.
Referenced by newDocument().
slotOpenTransaction()
void Application::slotOpenTransaction (const App::Document & , std::string) protected
Definition at line 1653 of file App/Application.cpp.
References toolbit-attributes::s, and signalOpenTransaction.
Referenced by newDocument().
slotRecomputed()
void Application::slotRecomputed (const App::Document & doc) protected
Definition at line 1643 of file App/Application.cpp.
References signalRecomputed.
Referenced by newDocument().
slotRecomputedObject()
void Application::slotRecomputedObject (const App::DocumentObject & obj) protected
Definition at line 1638 of file App/Application.cpp.
References signalObjectRecomputed.
Referenced by newDocument().
slotRedoDocument()
void Application::slotRedoDocument (const App::Document & d) protected
Definition at line 1633 of file App/Application.cpp.
References signalRedoDocument.
Referenced by newDocument().
slotRelabelObject()
void Application::slotRelabelObject (const App::DocumentObject & O) protected
Definition at line 1618 of file App/Application.cpp.
References signalRelabelObject.
Referenced by newDocument().
slotStartSaveDocument()
void Application::slotStartSaveDocument (const App::Document & doc, const std::string & filename) protected
Definition at line 1668 of file App/Application.cpp.
References signalStartSaveDocument.
Referenced by newDocument().
slotUndoDocument()
void Application::slotUndoDocument (const App::Document & d) protected
Definition at line 1628 of file App/Application.cpp.
References signalUndoDocument.
Referenced by newDocument().
Friends And Related Function Documentation
App::Document
friend class App::Document friend
Definition at line 456 of file App/Application.h.
ApplicationObserver
friend class ApplicationObserver friend
Definition at line 573 of file App/Application.h.
AutoTransaction
friend class AutoTransaction friend
Definition at line 633 of file App/Application.h.
GetApplication
Application& GetApplication () friend
Singleton getter of the Application.
Definition at line 645 of file App/Application.h.
Referenced by App::Application::TransactionSignaller::TransactionSignaller(), and App::Application::TransactionSignaller::~TransactionSignaller().
Member Data Documentation
signalAbortTransaction
boost::signals2::signal<void (const App::Document&)> App::Application::signalAbortTransaction
Definition at line 289 of file App/Application.h.
Referenced by slotAbortTransaction().
signalActivatedObject
boost::signals2::signal<void (const App::DocumentObject&)> App::Application::signalActivatedObject
signal on activated Object
Definition at line 277 of file App/Application.h.
Referenced by slotActivatedObject().
signalActiveDocument
boost::signals2::signal<void (const Document&)> App::Application::signalActiveDocument
signal on activating Document
Definition at line 222 of file App/Application.h.
Referenced by Gui::Application::Application(), App::DocumentObserver::DocumentObserver(), setActiveDocument(), and Gui::TaskView::TaskView::TaskView().
signalAddedDynamicExtension
boost::signals2::signal<void (const App::ExtensionContainer&, std::string extension)> App::Application::signalAddedDynamicExtension
signal after the extension was added
Definition at line 314 of file App/Application.h.
signalAppendDynamicProperty
boost::signals2::signal<void (const App::Property&)> App::Application::signalAppendDynamicProperty
signal on adding a dynamic property
Definition at line 298 of file App/Application.h.
Referenced by App::DynamicProperty::addDynamicProperty(), and Gui::PropertyView::PropertyView().
signalBeforeAddingDynamicExtension
boost::signals2::signal<void (const App::ExtensionContainer&, std::string extension)> App::Application::signalBeforeAddingDynamicExtension
signal before adding the extension
Definition at line 312 of file App/Application.h.
signalBeforeChangeDocument
boost::signals2::signal<void (const App::Document&, const App::Property&)> App::Application::signalBeforeChangeDocument
signal before change of doc property
Definition at line 262 of file App/Application.h.
Referenced by slotBeforeChangeDocument().
signalBeforeChangeObject
boost::signals2::signal<void (const App::DocumentObject&, const App::Property&)> App::Application::signalBeforeChangeObject
signal on changed Object
Definition at line 271 of file App/Application.h.
Referenced by slotBeforeChangeObject().
signalBeforeCloseTransaction
boost::signals2::signal<void (bool)> App::Application::signalBeforeCloseTransaction
signal before close/abort active transaction
Definition at line 244 of file App/Application.h.
Referenced by App::Application::TransactionSignaller::TransactionSignaller().
signalBeforeRecomputeDocument
boost::signals2::signal<void (const App::Document&)> App::Application::signalBeforeRecomputeDocument
signal before recomputed document
Definition at line 279 of file App/Application.h.
Referenced by slotBeforeRecompute().
signalChangedDocument
boost::signals2::signal<void (const App::Document&, const App::Property&)> App::Application::signalChangedDocument
signal on changed doc property
Definition at line 264 of file App/Application.h.
Referenced by Gui::PropertyView::PropertyView(), and slotChangedDocument().
signalChangedObject
boost::signals2::signal<void (const App::DocumentObject&, const App::Property&)> App::Application::signalChangedObject
signal on changed Object
Definition at line 273 of file App/Application.h.
Referenced by PartGui::DlgBooleanOperation::DlgBooleanOperation(), Gui::PropertyView::PropertyView(), slotChangedObject(), and MeshGui::MeshFillHole::startEditing().
signalChangePropertyEditor
boost::signals2::signal<void (const App::Document&, const App::Property&)> App::Application::signalChangePropertyEditor
signal on about changing the editor mode of a property
Definition at line 302 of file App/Application.h.
Referenced by Gui::PropertyView::PropertyView(), slotChangePropertyEditor(), and PartDesignGui::TaskHoleParameters::TaskHoleParameters().
signalCloseTransaction
boost::signals2::signal<void (bool)> App::Application::signalCloseTransaction
signal after close/abort active transaction
Definition at line 246 of file App/Application.h.
Referenced by App::Application::TransactionSignaller::~TransactionSignaller().
signalCommitTransaction
boost::signals2::signal<void (const App::Document&)> App::Application::signalCommitTransaction
Definition at line 287 of file App/Application.h.
Referenced by slotCommitTransaction().
signalDeletedDocument
boost::signals2::signal<void ()> App::Application::signalDeletedDocument
signal on already deleted Document
Definition at line 216 of file App/Application.h.
Referenced by closeDocument().
signalDeletedObject
boost::signals2::signal<void (const App::DocumentObject&)> App::Application::signalDeletedObject
signal on deleted Object
Definition at line 269 of file App/Application.h.
Referenced by PartGui::DlgFilletEdges::DlgFilletEdges(), Gui::PropertyView::PropertyView(), Gui::SelectionSingleton::SelectionSingleton(), and slotDeletedObject().
signalDeleteDocument
boost::signals2::signal<void (const Document&)> App::Application::signalDeleteDocument
signal on document getting deleted
Definition at line 214 of file App/Application.h.
Referenced by Gui::Application::Application(), App::Document::clearDocument(), closeDocument(), PartGui::DlgFilletEdges::DlgFilletEdges(), App::DocumentObserver::DocumentObserver(), DrawingGui::OrthoViews::OrthoViews(), App::DocumentWeakPtrT::Private::Private(), App::Document::restore(), App::DocumentObjectWeakPtrT::Private::set(), and Gui::TaskView::TaskView::TaskView().
signalFinishOpenDocument
boost::signals2::signal<void ()> App::Application::signalFinishOpenDocument
signal on finished opening document(s)
Definition at line 252 of file App/Application.h.
Referenced by openDocuments().
signalFinishRestoreDocument
boost::signals2::signal<void (const Document&)> App::Application::signalFinishRestoreDocument
signal on restoring Document
Definition at line 228 of file App/Application.h.
Referenced by App::Document::afterRestore(), Cloud::Module::cloudRestore(), and Gui::Document::Document().
signalFinishSaveDocument
boost::signals2::signal<void (const Document&, const std::string&)> App::Application::signalFinishSaveDocument
signal on saved Document
Definition at line 234 of file App/Application.h.
Referenced by slotFinishSaveDocument().
signalNewDocument
boost::signals2::signal<void (const Document&, bool)> App::Application::signalNewDocument
signal on new Document
Definition at line 212 of file App/Application.h.
Referenced by Gui::Application::Application(), App::Document::clearDocument(), App::DocumentObserver::DocumentObserver(), newDocument(), and App::Document::restore().
signalNewObject
boost::signals2::signal<void (const App::DocumentObject&)> App::Application::signalNewObject
signal on new Object
Definition at line 266 of file App/Application.h.
Referenced by PartGui::DlgBooleanOperation::DlgBooleanOperation(), and slotNewObject().
signalObjectRecomputed
boost::signals2::signal<void (const App::DocumentObject&)> App::Application::signalObjectRecomputed
signal on recomputed document object
Definition at line 283 of file App/Application.h.
Referenced by slotRecomputedObject().
signalOpenTransaction
boost::signals2::signal<void (const App::Document&, std::string)> App::Application::signalOpenTransaction
Definition at line 285 of file App/Application.h.
Referenced by slotOpenTransaction().
signalPendingReloadDocument
boost::signals2::signal<void (const Document&)> App::Application::signalPendingReloadDocument
signal on pending reloading of a partial Document
Definition at line 230 of file App/Application.h.
Referenced by App::Document::afterRestore().
signalRecomputed
boost::signals2::signal<void (const App::Document&)> App::Application::signalRecomputed
signal on recomputed document
Definition at line 281 of file App/Application.h.
Referenced by slotRecomputed().
signalRedo
boost::signals2::signal<void ()> App::Application::signalRedo
signal on application wide redo
Definition at line 242 of file App/Application.h.
Referenced by Gui::Document::redo().
signalRedoDocument
boost::signals2::signal<void (const Document&)> App::Application::signalRedoDocument
signal on redo in document
Definition at line 240 of file App/Application.h.
Referenced by Gui::PropertyView::PropertyView(), slotRedoDocument(), and Gui::TaskView::TaskView::TaskView().
signalRelabelDocument
boost::signals2::signal<void (const Document&)> App::Application::signalRelabelDocument
signal on relabeling Document (user name)
Definition at line 218 of file App/Application.h.
Referenced by Gui::Application::Application(), App::Document::onChanged(), and App::PropertyExpressionContainer::PropertyExpressionContainer().
signalRelabelObject
boost::signals2::signal<void (const App::DocumentObject&)> App::Application::signalRelabelObject
signal on relabeled Object
Definition at line 275 of file App/Application.h.
Referenced by slotRelabelObject().
signalRemoveDynamicProperty
boost::signals2::signal<void (const App::Property&)> App::Application::signalRemoveDynamicProperty
signal on about removing a dynamic property
Definition at line 300 of file App/Application.h.
Referenced by Gui::PropertyView::PropertyView(), and App::DynamicProperty::removeDynamicProperty().
signalRenameDocument
boost::signals2::signal<void (const Document&)> App::Application::signalRenameDocument
signal on renaming Document (internal name)
Definition at line 220 of file App/Application.h.
Referenced by Gui::Application::Application().
signalSaveDocument
boost::signals2::signal<void (const Document&)> App::Application::signalSaveDocument
signal on saving Document
Definition at line 224 of file App/Application.h.
Referenced by App::Document::saveToFile().
signalShowHidden
boost::signals2::signal<void (const Document&)> App::Application::signalShowHidden
signal on show hidden items
Definition at line 248 of file App/Application.h.
Referenced by Gui::Application::Application(), Gui::Document::Document(), and App::Document::onChanged().
signalStartOpenDocument
boost::signals2::signal<void ()> App::Application::signalStartOpenDocument
signal on start opening document(s)
Definition at line 250 of file App/Application.h.
Referenced by openDocuments().
signalStartRestoreDocument
boost::signals2::signal<void (const Document&)> App::Application::signalStartRestoreDocument
signal on starting to restore Document
Definition at line 226 of file App/Application.h.
Referenced by Cloud::Module::cloudRestore(), Gui::Document::Document(), and App::Document::restore().
signalStartSaveDocument
boost::signals2::signal<void (const Document&, const std::string&)> App::Application::signalStartSaveDocument
signal on starting to save Document
Definition at line 232 of file App/Application.h.
Referenced by slotStartSaveDocument().
signalUndo
boost::signals2::signal<void ()> App::Application::signalUndo
signal on application wide undo
Definition at line 238 of file App/Application.h.
Referenced by Gui::Document::undo().
signalUndoDocument
boost::signals2::signal<void (const Document&)> App::Application::signalUndoDocument
signal on undo in document
Definition at line 236 of file App/Application.h.
Referenced by Gui::PropertyView::PropertyView(), slotUndoDocument(), and Gui::TaskView::TaskView::TaskView().
The documentation for this class was generated from the following files:
App/Application.h
App/Application.cpp
App/ApplicationPy.cpp
AutoTransaction.cpp