FreeCAD: ifc2x3.ifcconstructionresource Class Reference
ifc2x3.ifcconstructionresource Class Reference
Public Member Functions
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__objecttype, resourceidentifier, resourcegroup, resourceconsumption, basequantity)
def resourceidentifier ()
def resourcegroup ()
def resourceconsumption ()
def basequantity ()
Public Member Functions inherited from ifc2x3.ifcresource
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__objecttype)
def resourceof ()
Public Member Functions inherited from ifc2x3.ifcobject
def objecttype ()
def isdefinedby ()
def wr1 (self)
Public Member Functions inherited from ifc2x3.ifcobjectdefinition
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description)
def hasassignments ()
def isdecomposedby ()
def decomposes ()
def hasassociations ()
Public Member Functions inherited from ifc2x3.ifcroot
def globalid ()
def ownerhistory ()
def name ()
def description ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
resourceidentifier
resourcegroup
resourceconsumption
basequantity
Public Attributes inherited from ifc2x3.ifcobject
objecttype
Public Attributes inherited from ifc2x3.ifcroot
globalid
ownerhistory
name
description
Detailed Description
Entity ifcconstructionresource definition.
:param resourceidentifier
:type resourceidentifier:ifcidentifier
:param resourcegroup
:type resourcegroup:ifclabel
:param resourceconsumption
:type resourceconsumption:ifcresourceconsumptionenum
:param basequantity
:type basequantity:ifcmeasurewithunit
Definition at line 19409 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcconstructionresource.__init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__objecttype, resourceidentifier, resourcegroup, resourceconsumption, basequantity)
Reimplemented in ifc2x3.ifcconstructionproductresource, ifc2x3.ifcconstructionequipmentresource, and ifc2x3.ifccrewresource.
Definition at line 19424 of file ifc2x3.py.
Member Function Documentation
basequantity()
def ifc2x3.ifcconstructionresource.basequantity ()
Definition at line 19474 of file ifc2x3.py.
References ifc2x3.ifcconstructionresource._basequantity, ifc2x3.ifcconstructionresource.basequantity, and SCL.TypeChecker.check_type().
resourceconsumption()
def ifc2x3.ifcconstructionresource.resourceconsumption ()
Definition at line 19460 of file ifc2x3.py.
References ifc2x3.ifcconstructionresource._resourceconsumption, SCL.TypeChecker.check_type(), and ifc2x3.ifcconstructionresource.resourceconsumption.
resourcegroup()
def ifc2x3.ifcconstructionresource.resourcegroup ()
Definition at line 19446 of file ifc2x3.py.
References ifc2x3.ifcconstructionresource._resourcegroup, SCL.TypeChecker.check_type(), and ifc2x3.ifcconstructionresource.resourcegroup.
resourceidentifier()
def ifc2x3.ifcconstructionresource.resourceidentifier ()
Definition at line 19432 of file ifc2x3.py.
References ifc2x3.ifcconstructionresource._resourceidentifier, SCL.TypeChecker.check_type(), and ifc2x3.ifcconstructionresource.resourceidentifier.
Member Data Documentation
basequantity
ifc2x3.ifcconstructionresource.basequantity
Definition at line 19429 of file ifc2x3.py.
Referenced by ifc2x3.ifcconstructionresource.basequantity().
resourceconsumption
ifc2x3.ifcconstructionresource.resourceconsumption
Definition at line 19428 of file ifc2x3.py.
Referenced by ifc2x3.ifcconstructionresource.resourceconsumption().
resourcegroup
ifc2x3.ifcconstructionresource.resourcegroup
Definition at line 19427 of file ifc2x3.py.
Referenced by ifc2x3.ifcconstructionresource.resourcegroup().
resourceidentifier
ifc2x3.ifcconstructionresource.resourceidentifier
Definition at line 19426 of file ifc2x3.py.
Referenced by ifc2x3.ifcconstructionresource.resourceidentifier().
The documentation for this class was generated from the following file:
ifc2x3.py