FreeCAD: Wm4::IntrSegment3Plane3< Real > Class Template Reference
Wm4::IntrSegment3Plane3< Real > Class Template Reference
#include <Wm4IntrSegment3Plane3.h>
Public Member Functions
IntrSegment3Plane3 (const Segment3< Real > &rkSegment, const Plane3< Real > &rkPlane)
const Segment3< Real > & GetSegment () const
const Plane3< Real > & GetPlane () const
virtual bool Test ()
virtual bool Find ()
Real GetSegmentT () const
Public Member Functions inherited from Wm4::Intersector< Real, Vector3< Real > >
virtual ~Intersector ()
virtual bool Test (Real fTMax, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
virtual bool Find (Real fTMax, const Vector3< Real > &rkVelocity0, const Vector3< Real > &rkVelocity1)
Real GetContactTime () const
int GetIntersectionType () const
Additional Inherited Members
Public Types inherited from Wm4::Intersector< Real, Vector3< Real > >
enum
Protected Member Functions inherited from Wm4::Intersector< Real, Vector3< Real > >
Intersector ()
Protected Attributes inherited from Wm4::Intersector< Real, Vector3< Real > >
Real m_fContactTime
int m_iIntersectionType
Detailed Description
template<class Real>
class Wm4::IntrSegment3Plane3< Real >
Definition at line 29 of file Wm4IntrSegment3Plane3.h.
Constructor & Destructor Documentation
IntrSegment3Plane3()
template<class Real > Wm4::IntrSegment3Plane3< Real >::IntrSegment3Plane3 (const Segment3< Real > & rkSegment, const Plane3< Real > & rkPlane)
Definition at line 25 of file Wm4IntrSegment3Plane3.cpp.
Member Function Documentation
Find()
template<class Real > bool Wm4::IntrSegment3Plane3< Real >::Find virtual
Reimplemented from Wm4::Intersector< Real, Vector3< Real > >.
Definition at line 90 of file Wm4IntrSegment3Plane3.cpp.
References Wm4::Math< Real >::FAbs(), Wm4::IntrLine3Plane3< Real >::Find(), Wm4::Intersector< Real, Vector3< Real > >::GetIntersectionType(), and Wm4::IntrLine3Plane3< Real >::GetLineT().
Referenced by MeshCore::MeshGeomFacet::IntersectWithPlane().
GetPlane()
template<class Real > const Plane3< Real > & Wm4::IntrSegment3Plane3< Real >::GetPlane
Definition at line 40 of file Wm4IntrSegment3Plane3.cpp.
GetSegment()
template<class Real > const Segment3< Real > & Wm4::IntrSegment3Plane3< Real >::GetSegment
Definition at line 34 of file Wm4IntrSegment3Plane3.cpp.
GetSegmentT()
template<class Real > Real Wm4::IntrSegment3Plane3< Real >::GetSegmentT
Definition at line 108 of file Wm4IntrSegment3Plane3.cpp.
Referenced by MeshCore::MeshGeomFacet::IntersectWithPlane().
Test()
template<class Real > bool Wm4::IntrSegment3Plane3< Real >::Test virtual
Reimplemented from Wm4::Intersector< Real, Vector3< Real > >.
Definition at line 46 of file Wm4IntrSegment3Plane3.cpp.
The documentation for this class was generated from the following files:
Wm4IntrSegment3Plane3.h
Wm4IntrSegment3Plane3.cpp