FreeCAD: ModelRefine::FaceTypedBSpline Class Reference
ModelRefine::FaceTypedBSpline Class Reference
#include <modelRefine.h>
Public Member Functions
bool isEqual (const TopoDS_Face &faceOne, const TopoDS_Face &faceTwo) const override
GeomAbs_SurfaceType getType () const override
TopoDS_Face buildFace (const FaceVectorType &faces) const override
Friends
FaceTypedBSpline & getBSplineObject ()
Additional Inherited Members
Static Public Member Functions inherited from ModelRefine::FaceTypedBase
static GeomAbs_SurfaceType getFaceType (const TopoDS_Face &faceIn)
Protected Member Functions inherited from ModelRefine::FaceTypedBase
FaceTypedBase (const GeomAbs_SurfaceType &typeIn)
virtual void boundarySplit (const FaceVectorType &facesIn, std::vector< EdgeVectorType > &boundariesOut) const
Protected Attributes inherited from ModelRefine::FaceTypedBase
GeomAbs_SurfaceType surfaceType
Detailed Description
Definition at line 121 of file modelRefine.h.
Member Function Documentation
buildFace()
TopoDS_Face FaceTypedBSpline::buildFace (const FaceVectorType & faces) const override virtual
Implements ModelRefine::FaceTypedBase.
Definition at line 963 of file modelRefine.cpp.
References ModelRefine::FaceTypedBase::boundarySplit(), Handle(), and Mesh2Shape::wires.
getType()
GeomAbs_SurfaceType FaceTypedBSpline::getType () const override virtual
Implements ModelRefine::FaceTypedBase.
Definition at line 958 of file modelRefine.cpp.
isEqual()
bool FaceTypedBSpline::isEqual (const TopoDS_Face & faceOne, const TopoDS_Face & faceTwo) const override virtual
Implements ModelRefine::FaceTypedBase.
Definition at line 814 of file modelRefine.cpp.
References Base::Console(), SCL.SimpleDataTypes::e, Handle(), and Base::ConsoleSingleton::Message().
Friends And Related Function Documentation
getBSplineObject
FaceTypedBSpline& getBSplineObject () friend
The documentation for this class was generated from the following files:
modelRefine.h
modelRefine.cpp