FreeCAD: Gui::Rubberband Class Reference
Gui::Rubberband Class Reference
#include <GLPainter.h>
Public Member Functions
Rubberband (View3DInventorViewer *v)
Rubberband ()
~Rubberband () override
void setWorking (bool on)
void setLineStipple (bool on)
bool isWorking ()
void setViewer (View3DInventorViewer *v)
void setCoords (int x1, int y1, int x2, int y2)
void setColor (float r, float g, float b, float a)
void paintGL () override
Public Member Functions inherited from Gui::GLGraphicsItem
GLGraphicsItem ()=default
~GLGraphicsItem () override=default
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 96 of file GLPainter.h.
Constructor & Destructor Documentation
Rubberband() [1/2]
Rubberband::Rubberband (View3DInventorViewer * v) explicit
Definition at line 208 of file GLPainter.cpp.
Rubberband() [2/2]
Rubberband::Rubberband ()
Definition at line 220 of file GLPainter.cpp.
~Rubberband()
Rubberband::~Rubberband () override default
Member Function Documentation
isWorking()
bool Gui::Rubberband::isWorking ()
paintGL()
void Rubberband::paintGL () override virtual
Implements Gui::GLGraphicsItem.
Definition at line 265 of file GLPainter.cpp.
References SCL.SimpleDataTypes::f, SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), glBlendFunc, glDisable, glEnable, glLineWidth, and glMatrixMode.
setColor()
void Rubberband::setColor (float r, float g, float b, float a)
Definition at line 257 of file GLPainter.cpp.
References a, SCL.SimpleDataTypes::b, and toolbit-attributes::g.
Referenced by Gui::RectangleSelection::RectangleSelection(), Gui::RubberbandSelection::RubberbandSelection(), and Gui::RubberbandSelection::setColor().
setCoords()
void Rubberband::setCoords (int x1, int y1, int x2, int y2)
Definition at line 244 of file GLPainter.cpp.
Referenced by Gui::RubberbandSelection::locationEvent().
setLineStipple()
void Rubberband::setLineStipple (bool on)
Definition at line 252 of file GLPainter.cpp.
setViewer()
void Rubberband::setViewer (View3DInventorViewer * v)
Definition at line 239 of file GLPainter.cpp.
References TestSpreadsheet::v.
Referenced by Gui::RubberbandSelection::initialize().
setWorking()
void Rubberband::setWorking (bool on)
Definition at line 234 of file GLPainter.cpp.
Referenced by Gui::RubberbandSelection::initialize(), and Gui::RubberbandSelection::mouseButtonEvent().
The documentation for this class was generated from the following files:
GLPainter.h
GLPainter.cpp