FreeCAD: Gui::SoFCInteractiveElement Class Reference
Gui::SoFCInteractiveElement Class Reference
#include <SoFCInteractiveElement.h>
Public Member Functions
void init (SoState *state) override
Static Public Member Functions
static void initClass ()
static void set (SoState *const state, SoNode *const node, SbBool mode)
static SbBool get (SoState *const state)
static const SoFCInteractiveElement * getInstance (SoState *state)
Protected Member Functions
~SoFCInteractiveElement () override
virtual void setElt (SbBool mode)
Detailed Description
Author
Werner Mayer
Definition at line 60 of file SoFCInteractiveElement.h.
Constructor & Destructor Documentation
~SoFCInteractiveElement()
SoFCInteractiveElement::~SoFCInteractiveElement () override protected default
Member Function Documentation
get()
SbBool SoFCInteractiveElement::get (SoState *const state) static
Definition at line 55 of file SoFCInteractiveElement.cpp.
References getInstance().
Referenced by MeshGui::SoFCIndexedFaceSet::drawFaces(), MeshGui::SoFCMeshObjectShape::GLRender(), MeshGui::SoFCMeshSegmentShape::GLRender(), and draftguitools.gui_trackers.editTracker::move().
getInstance()
const SoFCInteractiveElement * SoFCInteractiveElement::getInstance (SoState * state) static
Definition at line 65 of file SoFCInteractiveElement.cpp.
Referenced by get().
init()
void SoFCInteractiveElement::init (SoState * state) override
Definition at line 41 of file SoFCInteractiveElement.cpp.
Referenced by DocumentObject.DocumentObject::onChanged().
initClass()
void SoFCInteractiveElement::initClass () static
Definition at line 35 of file SoFCInteractiveElement.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
set()
void SoFCInteractiveElement::set (SoState *const state, SoNode *const node, SbBool mode) static
Definition at line 48 of file SoFCInteractiveElement.cpp.
Referenced by draftguitools.gui_trackers.editTracker::move().
setElt()
void SoFCInteractiveElement::setElt (SbBool mode) protected virtual
Definition at line 60 of file SoFCInteractiveElement.cpp.
The documentation for this class was generated from the following files:
SoFCInteractiveElement.h
SoFCInteractiveElement.cpp