FreeCAD: SketcherGui::SketcherSettings Class Reference
SketcherGui::SketcherSettings Class Reference
#include <SketcherSettings.h>
Public Member Functions
SketcherSettings (QWidget *parent=nullptr)
~SketcherSettings () override
void saveSettings () override
void loadSettings () override
void resetSettingsToDefaults () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void changeEvent (QEvent *e) override
void dimensioningModeChanged (int index)
void checkForRestart ()
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
Detailed Description
The SketcherSettings class implements a preference page to change sketcher settings.
Author
Werner Mayer
Definition at line 61 of file SketcherSettings.h.
Constructor & Destructor Documentation
SketcherSettings()
SketcherSettings::SketcherSettings (QWidget * parent = nullptr) explicit
Definition at line 89 of file SketcherSettings.cpp.
~SketcherSettings()
SketcherSettings::~SketcherSettings () override
Destroys the object and frees any allocated resources
Definition at line 99 of file SketcherSettings.cpp.
Member Function Documentation
changeEvent()
void SketcherSettings::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 256 of file SketcherSettings.cpp.
References SCL.SimpleDataTypes::e.
checkForRestart()
void SketcherSettings::checkForRestart () protected
Definition at line 239 of file SketcherSettings.cpp.
References Gui::Dialog::PreferencePage::requireRestart().
Referenced by saveSettings().
dimensioningModeChanged()
void SketcherSettings::dimensioningModeChanged (int index) protected
Definition at line 234 of file SketcherSettings.cpp.
Referenced by loadSettings().
loadSettings()
void SketcherSettings::loadSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 177 of file SketcherSettings.cpp.
References draftgeoutils.intersections::connect(), dimensioningModeChanged(), App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), and Path.Base.Util::setProperty().
resetSettingsToDefaults()
void SketcherSettings::resetSettingsToDefaults () override virtual
Reimplemented from Gui::Dialog::PreferencePage.
Definition at line 266 of file SketcherSettings.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), ParameterGrp::RemoveBool(), and ParameterGrp::RemoveInt().
saveSettings()
void SketcherSettings::saveSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 104 of file SketcherSettings.cpp.
References checkForRestart(), App::GetApplication(), App::Application::GetParameterGroupByPath(), ParameterGrp::SetBool(), and ParameterGrp::SetInt().
The documentation for this class was generated from the following files:
SketcherSettings.h
SketcherSettings.cpp