FreeCAD: tritritest.h File Reference
tritritest.h File Reference
#include <cmath>
Macros
#define FABS(x) ((float)fabs(x)) /* implement as is fastest on your machine */
#define USE_EPSILON_TEST 1
#define EPSILON 0.000001
#define CROSS(dest, v1, v2)
#define DOT(v1, v2) (v1[0]*v2[0]+v1[1]*v2[1]+v1[2]*v2[2])
#define SUB(dest, v1, v2) dest[0]=v1[0]-v2[0]; dest[1]=v1[1]-v2[1]; dest[2]=v1[2]-v2[2];
#define ADD(dest, v1, v2) dest[0]=v1[0]+v2[0]; dest[1]=v1[1]+v2[1]; dest[2]=v1[2]+v2[2];
#define MULT(dest, v, factor) dest[0]=factor*v[0]; dest[1]=factor*v[1]; dest[2]=factor*v[2];
#define SET(dest, src) dest[0]=src[0]; dest[1]=src[1]; dest[2]=src[2];
#define SORT(a, b)
#define ISECT(VV0, VV1, VV2, D0, D1, D2, isect0, isect1)
#define COMPUTE_INTERVALS(VV0, VV1, VV2, D0, D1, D2, D0D1, D0D2, isect0, isect1)
#define EDGE_EDGE_TEST(V0, U0, U1)
#define EDGE_AGAINST_TRI_EDGES(V0, V1, U0, U1, U2)
#define POINT_IN_TRI(V0, U0, U1, U2)
#define NEWCOMPUTE_INTERVALS(VV0, VV1, VV2, D0, D1, D2, D0D1, D0D2, A, B, C, X0, X1)
#define SORT2(a, b, smallest)
#define COMPUTE_INTERVALS_ISECTLINE(VERT0, VERT1, VERT2, VV0, VV1, VV2, D0, D1, D2, D0D1, D0D2, isect0, isect1, isectpoint0, isectpoint1)
Functions
int coplanar_tri_tri (float N[3], float V0[3], float V1[3], float V2[3], float U0[3], float U1[3], float U2[3])
int tri_tri_intersect (float V0[3], float V1[3], float V2[3], float U0[3], float U1[3], float U2[3])
int NoDivTriTriIsect (float V0[3], float V1[3], float V2[3], float U0[3], float U1[3], float U2[3])
void isect2 (float VTX0[3], float VTX1[3], float VTX2[3], float VV0, float VV1, float VV2, float D0, float D1, float D2, float *isect0, float *isect1, float isectpoint0[3], float isectpoint1[3])
int compute_intervals_isectline (float VERT0[3], float VERT1[3], float VERT2[3], float VV0, float VV1, float VV2, float D0, float D1, float D2, float D0D1, float D0D2, float *isect0, float *isect1, float isectpoint0[3], float isectpoint1[3])
int tri_tri_intersect_with_isectline (float V0[3], float V1[3], float V2[3], float U0[3], float U1[3], float U2[3], int *coplanar, float isectpt1[3], float isectpt2[3])
Macro Definition Documentation
ADD
#define ADD (dest, v1, v2) dest[0]=v1[0]+v2[0]; dest[1]=v1[1]+v2[1]; dest[2]=v1[2]+v2[2];
Definition at line 67 of file tritritest.h.
COMPUTE_INTERVALS
#define COMPUTE_INTERVALS (VV0, VV1, VV2, D0, D1, D2, D0D1, D0D2, isect0, isect1)
Value:
  if(D0D1>0.0f)                                         \
  {                                                     \
    /* here we know that D0D2<=0.0 */                   \
    /* that is D0, D1 are on the same side, D2 on the other or on the plane */ \
    ISECT(VV2,VV0,VV1,D2,D0,D1,isect0,isect1);          \
  }                                                     \
  else if(D0D2>0.0f)                                    \
  {                                                     \
    /* here we know that d0d1<=0.0 */                   \
    ISECT(VV1,VV0,VV2,D1,D0,D2,isect0,isect1);          \
  }                                                     \
  else if(D1*D2>0.0f || D0!=0.0f)                       \
  {                                                     \
    /* here we know that d0d1<=0.0 or that D0!=0.0 */   \
    ISECT(VV0,VV1,VV2,D0,D1,D2,isect0,isect1);          \
  }                                                     \
  else if(D1!=0.0f)                                     \
  {                                                     \
    ISECT(VV1,VV0,VV2,D1,D0,D2,isect0,isect1);          \
  }                                                     \
  else if(D2!=0.0f)                                     \
  {                                                     \
    ISECT(VV2,VV0,VV1,D2,D0,D1,isect0,isect1);          \
  }                                                     \
  else                                                  \
  {                                                     \
    /* triangles are coplanar */                        \
    return coplanar_tri_tri(N1,V0,V1,V2,U0,U1,U2);      \
  }
Definition at line 88 of file tritritest.h.
COMPUTE_INTERVALS_ISECTLINE
#define COMPUTE_INTERVALS_ISECTLINE (VERT0, VERT1, VERT2, VV0, VV1, VV2, D0, D1, D2, D0D1, D0D2, isect0, isect1, isectpoint0, isectpoint1)
Value:
  if(D0D1>0.0f)                                         \
  {                                                     \
    /* here we know that D0D2<=0.0 */                   \
    /* that is D0, D1 are on the same side, D2 on the other or on the plane */ \
    isect2(VERT2,VERT0,VERT1,VV2,VV0,VV1,D2,D0,D1,&isect0,&isect1,isectpoint0,isectpoint1);          \
  }
Definition at line 554 of file tritritest.h.
CROSS
#define CROSS (dest, v1, v2)
Value:
              dest[0]=v1[1]*v2[2]-v1[2]*v2[1]; \
              dest[1]=v1[2]*v2[0]-v1[0]*v2[2]; \
              dest[2]=v1[0]*v2[1]-v1[1]*v2[0];
Definition at line 58 of file tritritest.h.
DOT
#define DOT (v1, v2) (v1[0]*v2[0]+v1[1]*v2[1]+v1[2]*v2[2])
Definition at line 63 of file tritritest.h.
EDGE_AGAINST_TRI_EDGES
#define EDGE_AGAINST_TRI_EDGES (V0, V1, U0, U1, U2)
Value:
{                                              \
  float Ax,Ay,Bx,By,Cx,Cy,e,d,f;               \
  Ax=V1[i0]-V0[i0];                            \
  Ay=V1[i1]-V0[i1];                            \
  /* test edge U0,U1 against V0,V1 */          \
  EDGE_EDGE_TEST(V0,U0,U1);                    \
  /* test edge U1,U2 against V0,V1 */          \
  EDGE_EDGE_TEST(V0,U1,U2);                    \
  /* test edge U2,U1 against V0,V1 */          \
  EDGE_EDGE_TEST(V0,U2,U0);                    \
}
Definition at line 144 of file tritritest.h.
EDGE_EDGE_TEST
#define EDGE_EDGE_TEST (V0, U0, U1)
Value:
  Bx=U0[i0]-U1[i0];                                   \
  By=U0[i1]-U1[i1];                                   \
  Cx=V0[i0]-U0[i0];                                   \
  Cy=V0[i1]-U0[i1];                                   \
  f=Ay*Bx-Ax*By;                                      \
  d=By*Cx-Bx*Cy;                                      \
  if((f>0 && d>=0 && d<=f) || (f<0 && d<=0 && d>=f))  \
  {                                                   \
    e=Ax*Cy-Ay*Cx;                                    \
    if(f>0)                                           \
    {                                                 \
      if(e>=0 && e<=f) return 1;                      \
    }                                                 \
    else                                              \
    {                                                 \
      if(e<=0 && e>=f) return 1;                      \
    }                                                 \
  }
Definition at line 124 of file tritritest.h.
EPSILON
#define EPSILON 0.000001
Definition at line 54 of file tritritest.h.
FABS
#define FABS (x) ((float)fabs(x)) /* implement as is fastest on your machine */
Definition at line 47 of file tritritest.h.
ISECT
#define ISECT (VV0, VV1, VV2, D0, D1, D2, isect0, isect1)
Value:
              isect0=VV0+(VV1-VV0)*D0/(D0-D1);    \
              isect1=VV0+(VV2-VV0)*D0/(D0-D2);
Definition at line 83 of file tritritest.h.
MULT
#define MULT (dest, v, factor) dest[0]=factor*v[0]; dest[1]=factor*v[1]; dest[2]=factor*v[2];
Definition at line 69 of file tritritest.h.
NEWCOMPUTE_INTERVALS
#define NEWCOMPUTE_INTERVALS (VV0, VV1, VV2, D0, D1, D2, D0D1, D0D2, A, B, C, X0, X1)
Definition at line 328 of file tritritest.h.
POINT_IN_TRI
#define POINT_IN_TRI (V0, U0, U1, U2)
Value:
{                                           \
  float a,b,c,d0,d1,d2;                     \
  /* is T1 completely inside T2? */         \
  /* check if V0 is inside tri(U0,U1,U2) */ \
  a=U1[i1]-U0[i1];                          \
  b=-(U1[i0]-U0[i0]);                       \
  c=-a*U0[i0]-b*U0[i1];                     \
  d0=a*V0[i0]+b*V0[i1]+c;                   \
                                            \
  a=U2[i1]-U1[i1];                          \
  b=-(U2[i0]-U1[i0]);                       \
  c=-a*U1[i0]-b*U1[i1];                     \
  d1=a*V0[i0]+b*V0[i1]+c;                   \
                                            \
  a=U0[i1]-U2[i1];                          \
  b=-(U0[i0]-U2[i0]);                       \
  c=-a*U2[i0]-b*U2[i1];                     \
  d2=a*V0[i0]+b*V0[i1]+c;                   \
  if(d0*d1>0.0)                             \
  {                                         \
    if(d0*d2>0.0) return 1;                 \
  }                                         \
}
Definition at line 157 of file tritritest.h.
SET
#define SET (dest, src) dest[0]=src[0]; dest[1]=src[1]; dest[2]=src[2];
Definition at line 71 of file tritritest.h.
SORT
#define SORT (a, b)
Value:
             if(a>b)    \
             {          \
               float c; \
               c=a;     \
               a=b;     \
               b=c;     \
             }
Definition at line 74 of file tritritest.h.
SORT2
#define SORT2 (a, b, smallest)
Value:
             if(a>b)       \
             {             \
               float c;    \
               c=a;        \
               a=b;        \
               b=c;        \
               smallest=1; \
             }             \
             else smallest=0;
Definition at line 474 of file tritritest.h.
SUB
#define SUB (dest, v1, v2) dest[0]=v1[0]-v2[0]; dest[1]=v1[1]-v2[1]; dest[2]=v1[2]-v2[2];
Definition at line 65 of file tritritest.h.
USE_EPSILON_TEST
#define USE_EPSILON_TEST 1
Definition at line 53 of file tritritest.h.
Function Documentation
compute_intervals_isectline()
int compute_intervals_isectline (float VERT0[3], float VERT1[3], float VERT2[3], float VV0, float VV1, float VV2, float D0, float D1, float D2, float D0D1, float D0D2, float * isect0, float * isect1, float isectpoint0[3], float isectpoint1[3]) inline
Definition at line 517 of file tritritest.h.
References SCL.SimpleDataTypes::f, and isect2().
Referenced by tri_tri_intersect_with_isectline().
coplanar_tri_tri()
int coplanar_tri_tri (float N[3], float V0[3], float V1[3], float V2[3], float U0[3], float U1[3], float U2[3])
Definition at line 182 of file tritritest.h.
References RobotExample::A, EDGE_AGAINST_TRI_EDGES, and POINT_IN_TRI.
Referenced by tri_tri_intersect_with_isectline().
isect2()
void isect2 (float VTX0[3], float VTX1[3], float VTX2[3], float VV0, float VV1, float VV2, float D0, float D1, float D2, float * isect0, float * isect1, float isectpoint0[3], float isectpoint1[3]) inline
Definition at line 486 of file tritritest.h.
References ADD, KDL::diff(), MULT, and SUB.
Referenced by compute_intervals_isectline(), NoDivTriTriIsect(), tri_tri_intersect(), and tri_tri_intersect_with_isectline().
NoDivTriTriIsect()
int NoDivTriTriIsect (float V0[3], float V1[3], float V2[3], float U0[3], float U1[3], float U2[3])
Definition at line 363 of file tritritest.h.
References a, SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::c, CROSS, Path.Dressup.Gui.Dragknife::D, DOT, SCL.SimpleDataTypes::e, EPSILON, SCL.SimpleDataTypes::f, FABS, isect2(), KDL::max(), NEWCOMPUTE_INTERVALS, SORT, and SUB.
tri_tri_intersect()
int tri_tri_intersect (float V0[3], float V1[3], float V2[3], float U0[3], float U1[3], float U2[3])
Definition at line 232 of file tritritest.h.
References SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::c, COMPUTE_INTERVALS, CROSS, Path.Dressup.Gui.Dragknife::D, DOT, EPSILON, SCL.SimpleDataTypes::f, isect2(), KDL::max(), SORT, and SUB.
Referenced by MeshCore::MeshGeomFacet::IntersectWithFacet().
tri_tri_intersect_with_isectline()
int tri_tri_intersect_with_isectline (float V0[3], float V1[3], float V2[3], float U0[3], float U1[3], float U2[3], int * coplanar, float isectpt1[3], float isectpt2[3])
Definition at line 588 of file tritritest.h.
References SCL.SimpleDataTypes::b, SCL.SimpleDataTypes::c, compute_intervals_isectline(), coplanar_tri_tri(), CROSS, Path.Dressup.Gui.Dragknife::D, DOT, EPSILON, SCL.SimpleDataTypes::f, isect2(), KDL::max(), SET, SORT2, and SUB.
Referenced by MeshCore::MeshGeomFacet::IntersectWithFacet().