FreeCAD: CommandSketcherTools.cpp File Reference
CommandSketcherTools.cpp File Reference
#include "PreCompiled.h"
#include <cfloat>
#include <memory>
#include <QApplication>
#include <QClipboard>
#include <QMessageBox>
#include <Inventor/SbString.h>
#include <App/Application.h>
#include <Base/Console.h>
#include <Base/Reader.h>
#include <Base/Writer.h>
#include <Gui/Action.h>
#include <Gui/Application.h>
#include <Gui/BitmapFactory.h>
#include <Gui/CommandT.h>
#include <Gui/Document.h>
#include <Gui/MainWindow.h>
#include <Gui/Notifications.h>
#include <Gui/Selection.h>
#include <Gui/SelectionObject.h>
#include <Mod/Sketcher/App/PythonConverter.h>
#include <Mod/Sketcher/App/SketchObject.h>
#include <Mod/Sketcher/App/SolverGeometryExtension.h>
#include "DrawSketchHandler.h"
#include "SketchRectangularArrayDialog.h"
#include "Utils.h"
#include "ViewProviderSketch.h"
#include "DrawSketchHandlerTranslate.h"
#include "DrawSketchHandlerOffset.h"
#include "DrawSketchHandlerRotate.h"
#include "DrawSketchHandlerScale.h"
#include "DrawSketchHandlerSymmetry.h"
Classes
class SketcherCopy
class DrawSketchHandlerCopy
class CmdSketcherCopy
class CmdSketcherClone
class CmdSketcherMove
class DrawSketchHandlerRectangularArray
Functions
std::vector< int > getListOfSelectedGeoIds (bool forceInternalSelection)
Sketcher::SketchObject * getSketchObject ()
bool copySelectionToClipboard (Sketcher::SketchObject *obj)
void CreateSketcherCommandsConstraintAccel ()
Variables
static const char * cursor_createcopy []
static const char * cursor_createrectangulararray []
Function Documentation
copySelectionToClipboard()
bool copySelectionToClipboard (Sketcher::SketchObject * obj)
Definition at line 153 of file CommandSketcherTools.cpp.
References Sketcher::PythonConverter::AddLastGeoIdToGeoIds, Sketcher::SketchObject::Constraints, Sketcher::PythonConverter::convert(), Sketcher::Constraint::copy(), DraftVecUtils::find(), Sketcher::Constraint::First, Sketcher::GeoUndef, Sketcher::SketchObject::getGeometry(), getListOfSelectedGeoIds(), Gui::Command::getObjectCmd(), Sketcher::PropertyConstraintList::getValues(), Sketcher::HAxis, Sketcher::PythonConverter::OmitInternalGeometry, Sketcher::RtPnt, Sketcher::Constraint::Second, Sketcher::Constraint::Third, Sketcher::VAxis, and SurfaceTests.TestBlendCurve::vec.
CreateSketcherCommandsConstraintAccel()
void CreateSketcherCommandsConstraintAccel ()
Definition at line 2489 of file CommandSketcherTools.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
getListOfSelectedGeoIds()
std::vector<int> getListOfSelectedGeoIds (bool forceInternalSelection)
Definition at line 69 of file CommandSketcherTools.cpp.
References DraftVecUtils::find(), Base::Persistence::getClassTypeId(), Gui::getMainWindow(), Gui::SelectionSingleton::getSelectionEx(), SplineSurface::i, Sketcher::InternalAlignment, Sketcher::isArcOfEllipse(), Sketcher::isArcOfHyperbola(), Sketcher::isArcOfParabola(), Sketcher::isBSplineCurve(), TechDraw::isEllipse, Sketcher::isPoint(), Gui::NotifyUserError(), Arch::QT_TRANSLATE_NOOP, Path.Dressup.Utils::selection(), Gui::Selection(), and Path.Log::warning().
Referenced by copySelectionToClipboard().
getSketchObject()
Sketcher::SketchObject* getSketchObject ()
Definition at line 141 of file CommandSketcherTools.cpp.
References Gui::Application::activeDocument(), toolbit-attributes::doc, SketcherGui::ViewProviderSketch::getSketchObject(), Gui::Application::Instance, and SketcherGui::ReleaseHandler().
Variable Documentation
cursor_createcopy
const char* cursor_createcopy[] static
Definition at line 1138 of file CommandSketcherTools.cpp.
cursor_createrectangulararray
const char* cursor_createrectangulararray[] static
Definition at line 1709 of file CommandSketcherTools.cpp.