FreeCAD: Geometry.cpp File Reference
Part/App/Geometry.cpp File Reference
#include "PreCompiled.h"
#include <Approx_Curve3d.hxx>
#include <BRepAdaptor_Curve.hxx>
#include <BRepAdaptor_Surface.hxx>
#include <BRepBuilderAPI_MakeEdge.hxx>
#include <BRepBuilderAPI_MakeFace.hxx>
#include <BRepBuilderAPI_MakeVertex.hxx>
#include <BSplCLib.hxx>
#include <GC_MakeArcOfCircle.hxx>
#include <GC_MakeArcOfEllipse.hxx>
#include <GC_MakeArcOfHyperbola.hxx>
#include <GC_MakeArcOfParabola.hxx>
#include <GC_MakeCircle.hxx>
#include <GC_MakeEllipse.hxx>
#include <GC_MakeHyperbola.hxx>
#include <GC_MakeSegment.hxx>
#include <GCPnts_AbscissaPoint.hxx>
#include <gce_ErrorType.hxx>
#include <gce_MakeParab.hxx>
#include <Geom_BezierCurve.hxx>
#include <Geom_BezierSurface.hxx>
#include <Geom_BSplineCurve.hxx>
#include <Geom_BSplineSurface.hxx>
#include <Geom_CartesianPoint.hxx>
#include <Geom_Circle.hxx>
#include <Geom_ConicalSurface.hxx>
#include <Geom_Curve.hxx>
#include <Geom_CylindricalSurface.hxx>
#include <Geom_Ellipse.hxx>
#include <Geom_Hyperbola.hxx>
#include <Geom_Line.hxx>
#include <Geom_OffsetCurve.hxx>
#include <Geom_OffsetSurface.hxx>
#include <Geom_Parabola.hxx>
#include <Geom_Plane.hxx>
#include <Geom_RectangularTrimmedSurface.hxx>
#include <Geom_SphericalSurface.hxx>
#include <Geom_Surface.hxx>
#include <Geom_SurfaceOfLinearExtrusion.hxx>
#include <Geom_SurfaceOfRevolution.hxx>
#include <Geom_ToroidalSurface.hxx>
#include <Geom_TrimmedCurve.hxx>
#include <GeomAPI_ExtremaCurveCurve.hxx>
#include <GeomAPI_Interpolate.hxx>
#include <GeomAPI_PointsToBSpline.hxx>
#include <GeomAPI_ProjectPointOnCurve.hxx>
#include <GeomConvert.hxx>
#include <GeomConvert_CompCurveToBSplineCurve.hxx>
#include <GeomLProp_CLProps.hxx>
#include <GeomLProp_SLProps.hxx>
#include <GeomLib_IsPlanarSurface.hxx>
#include <GeomPlate_Surface.hxx>
#include <gp.hxx>
#include <gp_Ax2.hxx>
#include <gp_Circ.hxx>
#include <gp_Cone.hxx>
#include <gp_Cylinder.hxx>
#include <gp_Elips.hxx>
#include <gp_Hypr.hxx>
#include <gp_Lin.hxx>
#include <gp_Parab.hxx>
#include <gp_Pln.hxx>
#include <gp_Pnt.hxx>
#include <gp_Sphere.hxx>
#include <gp_Torus.hxx>
#include <LProp_NotDefined.hxx>
#include <Precision.hxx>
#include <ShapeConstruct_Curve.hxx>
#include <Standard_ConstructionError.hxx>
#include <Standard_Real.hxx>
#include <Standard_Version.hxx>
#include <TColgp_Array2OfPnt.hxx>
#include <TColgp_HArray1OfPnt.hxx>
#include <TColStd_Array1OfReal.hxx>
#include <TColStd_HArray1OfBoolean.hxx>
#include <GeomAdaptor_HSurface.hxx>
#include <GeomAdaptor_HCurve.hxx>
#include <boost/random.hpp>
#include <cmath>
#include <ctime>
#include <Base/Console.h>
#include <Base/Exception.h>
#include <Base/Reader.h>
#include <Base/Writer.h>
#include <BRep_Tool.hxx>
#include <TopoDS.hxx>
#include <memory>
#include <boost/thread/mutex.hpp>
#include <boost/thread/thread.hpp>
#include "Geometry.h"
#include "ArcOfCirclePy.h"
#include "ArcOfEllipsePy.h"
#include "ArcOfHyperbolaPy.h"
#include "ArcOfParabolaPy.h"
#include "BezierCurvePy.h"
#include "BezierSurfacePy.h"
#include "BSplineCurveBiArcs.h"
#include "BSplineCurvePy.h"
#include "BSplineSurfacePy.h"
#include "CirclePy.h"
#include "ConePy.h"
#include "CylinderPy.h"
#include "EllipsePy.h"
#include "GeometryMigrationExtension.h"
#include "HyperbolaPy.h"
#include "LinePy.h"
#include "LineSegmentPy.h"
#include "OffsetCurvePy.h"
#include "OffsetSurfacePy.h"
#include "ParabolaPy.h"
#include "PlanePy.h"
#include "PlateSurfacePy.h"
#include "PointPy.h"
#include "RectangularTrimmedSurfacePy.h"
#include "SpherePy.h"
#include "SurfaceOfExtrusionPy.h"
#include "SurfaceOfRevolutionPy.h"
#include "Tools.h"
#include "ToroidPy.h"
#include "TopoShape.h"
#include <gp_Quaternion.hxx>
Namespaces
Part
Functions
const char * gce_ErrorStatusText (gce_ErrorType et)
TYPESYSTEM_SOURCE_ABSTRACT (Part::Geometry, Base::Persistence) Geometry
const Handle (Geom_Geometry) &GeomPoint
static Standard_Boolean IsLinear (const Adaptor3d_Curve &theC)
bool Part::find2DLinesIntersection (const Base::Vector3d &orig1, const Base::Vector3d &dir1, const Base::Vector3d &orig2, const Base::Vector3d &dir2, Base::Vector3d &point)
bool Part::find2DLinesIntersection (const GeomLineSegment *lineSeg1, const GeomLineSegment *lineSeg2, Base::Vector3d &point)
bool Part::findFilletCenter (const GeomLineSegment *lineSeg1, const GeomLineSegment *lineSeg2, double radius, Base::Vector3d &center)
bool Part::findFilletCenter (const GeomLineSegment *lineSeg1, const GeomLineSegment *lineSeg2, double radius, const Base::Vector3d &refPnt1, const Base::Vector3d &refPnt2, Base::Vector3d &center)
double Part::suggestFilletRadius (const GeomLineSegment *lineSeg1, const GeomLineSegment *lineSeg2, const Base::Vector3d &refPnt1, const Base::Vector3d &refPnt2)
GeomArcOfCircle * Part::createFilletGeometry (const GeomLineSegment *lineSeg1, const GeomLineSegment *lineSeg2, const Base::Vector3d &center, double radius)
std::unique_ptr< GeomSurface > Part::makeFromSurface (const Handle(Geom_Surface)&s, bool silent)
std::unique_ptr< GeomSurface > Part::makeFromSurfaceAdaptor (const BRepAdaptor_Surface &adapt, bool silent)
std::unique_ptr< GeomCurve > Part::makeFromCurve (const Handle(Geom_Curve)&c, bool silent)
std::unique_ptr< GeomCurve > Part::makeFromTrimmedCurve (const Handle(Geom_Curve)&c, double f, double l, bool silent)
std::unique_ptr< GeomCurve > Part::makeFromCurveAdaptor (const Adaptor3d_Curve &adapt, bool silent)
Function Documentation
gce_ErrorStatusText()
const char* gce_ErrorStatusText (gce_ErrorType et)
Definition at line 162 of file Part/App/Geometry.cpp.
Referenced by Part::GeomCircle::Restore(), Part::GeomArcOfCircle::Restore(), Part::GeomEllipse::Restore(), Part::GeomArcOfEllipse::Restore(), Part::GeomHyperbola::Restore(), Part::GeomArcOfHyperbola::Restore(), Part::GeomParabola::Restore(), and Part::GeomArcOfParabola::Restore().
Handle()
const Handle (Geom_Geometry) &
Definition at line 575 of file Part/App/Geometry.cpp.
Referenced by Part::GeomArcOfCircle::GeomArcOfCircle(), Part::GeomArcOfEllipse::GeomArcOfEllipse(), Part::GeomArcOfHyperbola::GeomArcOfHyperbola(), Part::GeomArcOfParabola::GeomArcOfParabola(), Part::GeomBezierCurve::GeomBezierCurve(), Part::GeomCircle::GeomCircle(), Part::GeomCone::GeomCone(), Part::GeomCylinder::GeomCylinder(), Part::GeomEllipse::GeomEllipse(), Part::GeomHyperbola::GeomHyperbola(), Part::GeomLine::GeomLine(), Part::GeomLineSegment::GeomLineSegment(), Part::GeomParabola::GeomParabola(), Part::GeomPlane::GeomPlane(), Part::GeomSphere::GeomSphere(), Part::GeomToroid::GeomToroid(), Part::makeFromCurve(), Part::makeFromCurveAdaptor(), Part::makeFromSurface(), Part::makeFromSurfaceAdaptor(), and Part::makeFromTrimmedCurve().
IsLinear()
static Standard_Boolean IsLinear (const Adaptor3d_Curve & theC) static
Definition at line 677 of file Part/App/Geometry.cpp.
Referenced by Part::GeomCurve::isLinear().
TYPESYSTEM_SOURCE_ABSTRACT()
TYPESYSTEM_SOURCE_ABSTRACT (Part::Geometry , Base::Persistence)
Definition at line 201 of file Part/App/Geometry.cpp.
References Part::Geometry::createNewTag().