FreeCAD: Mesh::Segment Class Reference
Mesh::Segment Class Reference
#include <Segment.h>
Classes
class const_facet_iterator
Public Member Functions
Segment (const MeshObject *, bool mod)
Segment (const MeshObject *, const std::vector< FacetIndex > &inds, bool mod)
~Segment ()=default
void addIndices (const std::vector< FacetIndex > &inds)
void removeIndices (const std::vector< FacetIndex > &inds)
const std::vector< FacetIndex > & getIndices () const
bool isEmpty () const
Segment (const Segment &)
Segment (Segment &&)
Segment & operator= (const Segment &)
Segment & operator= (Segment &&)
bool operator== (const Segment &) const
void setName (const std::string &n)
const std::string & getName () const
void setColor (const std::string &c)
const std::string & getColor () const
void save (bool on)
bool isSaved () const
const_facet_iterator facets_begin () const
const_facet_iterator facets_end () const
Friends
class MeshObject
Detailed Description
Definition at line 60 of file Segment.h.
Constructor & Destructor Documentation
Segment() [1/4]
Segment::Segment (const MeshObject * mesh, bool mod)
Definition at line 36 of file Segment.cpp.
Segment() [2/4]
Segment::Segment (const MeshObject * mesh, const std::vector< FacetIndex > & inds, bool mod)
Definition at line 42 of file Segment.cpp.
~Segment()
Mesh::Segment::~Segment () default
Segment() [3/4]
Segment::Segment (const Segment &) default
Segment() [4/4]
Segment::Segment (Segment &&) default
Member Function Documentation
addIndices()
void Segment::addIndices (const std::vector< FacetIndex > & inds)
Definition at line 53 of file Segment.cpp.
Referenced by MeshPart::BrepMesh::create().
facets_begin()
const_facet_iterator Mesh::Segment::facets_begin () const inline
Definition at line 144 of file Segment.h.
facets_end()
const_facet_iterator Mesh::Segment::facets_end () const inline
Definition at line 148 of file Segment.h.
getColor()
const std::string& Mesh::Segment::getColor () const inline
Definition at line 93 of file Segment.h.
Referenced by MeshGui::ViewProviderMesh::highlightSegments().
getIndices()
const std::vector< FacetIndex > & Segment::getIndices () const
Definition at line 81 of file Segment.cpp.
Referenced by MeshPartGui::Tessellation::addFaceColors(), Mesh::MergeExporter::addMesh(), MeshGui::SoFCMeshSegmentShape::computeBBox(), MeshGui::SoFCMeshSegmentShape::getPrimitiveCount(), and MeshGui::ViewProviderMesh::highlightSegments().
getName()
const std::string& Mesh::Segment::getName () const inline
Definition at line 84 of file Segment.h.
Referenced by Mesh::MergeExporter::addMesh().
isEmpty()
bool Mesh::Segment::isEmpty () const inline
Definition at line 69 of file Segment.h.
References SCL.SimpleDataTypes::c.
isSaved()
bool Mesh::Segment::isSaved () const inline
Definition at line 102 of file Segment.h.
Referenced by Mesh::MergeExporter::addMesh().
operator=() [1/2]
Segment & Segment::operator= (const Segment & s)
Definition at line 90 of file Segment.cpp.
References toolbit-attributes::s.
operator=() [2/2]
Segment & Segment::operator= (Segment && s)
Definition at line 102 of file Segment.cpp.
References toolbit-attributes::s.
operator==()
bool Segment::operator== (const Segment & s) const
Definition at line 114 of file Segment.cpp.
References toolbit-attributes::s.
Referenced by Mesh::Segment::const_facet_iterator::operator!=().
removeIndices()
void Segment::removeIndices (const std::vector< FacetIndex > & inds)
Definition at line 63 of file Segment.cpp.
References result.
save()
void Mesh::Segment::save (bool on) inline
Definition at line 98 of file Segment.h.
Referenced by MeshPart::BrepMesh::create(), src.Mod.Show.mTempoVis.TempoVis::modify(), src.Mod.Show.mTempoVis.TempoVis::modifyVPProperty(), and src.Mod.Show.mTempoVis.TempoVis::saveCamera().
setColor()
void Mesh::Segment::setColor (const std::string & c) inline
Definition at line 89 of file Segment.h.
Referenced by MeshPart::BrepMesh::create().
setName()
void Mesh::Segment::setName (const std::string & n) inline
Definition at line 80 of file Segment.h.
Referenced by Mesh::MergeExporter::addMesh(), and MeshPart::BrepMesh::create().
Friends And Related Function Documentation
MeshObject
friend class MeshObject friend
Definition at line 108 of file Segment.h.
The documentation for this class was generated from the following files:
Segment.h
Segment.cpp