FreeCAD: Materials::MaterialYamlEntry Class Reference
Materials::MaterialYamlEntry Class Reference
#include <MaterialLoader.h>
Public Member Functions
MaterialYamlEntry (const std::shared_ptr< MaterialLibrary > &library, const QString &modelName, const QString &dir, const QString &modelUuid, const YAML::Node &modelData)
~MaterialYamlEntry () override=default
void addToTree (std::shared_ptr< std::map< QString, std::shared_ptr< Material >>> materialMap) override
const YAML::Node & getModel () const
YAML::Node * getModelPtr ()
Public Member Functions inherited from Materials::MaterialEntry
MaterialEntry ()=default
MaterialEntry (const std::shared_ptr< MaterialLibrary > &library, const QString &modelName, const QString &dir, const QString &modelUuid)
virtual ~MaterialEntry ()=default
std::shared_ptr< MaterialLibrary > getLibrary () const
QString getName () const
QString getDirectory () const
QString getUUID () const
Additional Inherited Members
Protected Attributes inherited from Materials::MaterialEntry
std::shared_ptr< MaterialLibrary > _library
QString _name
QString _directory
QString _uuid
Detailed Description
Definition at line 93 of file MaterialLoader.h.
Constructor & Destructor Documentation
MaterialYamlEntry()
MaterialYamlEntry::MaterialYamlEntry (const std::shared_ptr< MaterialLibrary > & library, const QString & modelName, const QString & dir, const QString & modelUuid, const YAML::Node & modelData)
Definition at line 58 of file MaterialLoader.cpp.
~MaterialYamlEntry()
Materials::MaterialYamlEntry::~MaterialYamlEntry () override default
Member Function Documentation
addToTree()
void MaterialYamlEntry::addToTree (std::shared_ptr< std::map< QString, std::shared_ptr< Material >>> materialMap) override virtual
Implements Materials::MaterialEntry.
Definition at line 167 of file MaterialLoader.cpp.
References Materials::MaterialValue::Array2D, Materials::MaterialValue::Array3D, Base::Console(), SCL.SimpleDataTypes::e, Materials::MaterialValue::FileList, Materials::MaterialEntry::getDirectory(), Materials::MaterialEntry::getLibrary(), getModel(), Materials::MaterialEntry::getName(), Materials::MaterialEntry::getUUID(), Materials::MaterialValue::Image, Materials::MaterialValue::ImageList, Materials::MaterialValue::List, Base::ConsoleSingleton::Log(), propertyName(), src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression, and Path.Post.scripts.grbl_post::type.
getModel()
const YAML::Node& Materials::MaterialYamlEntry::getModel () const inline
Definition at line 106 of file MaterialLoader.h.
Referenced by addToTree().
getModelPtr()
YAML::Node* Materials::MaterialYamlEntry::getModelPtr () inline
Definition at line 110 of file MaterialLoader.h.
References Materials::MaterialLoader::dereference(), Materials::MaterialLoader::getMaterialFolders(), Materials::MaterialLoader::getMaterialFromYAML(), Materials::MaterialLoader::getMaterialLibraries(), Materials::MaterialLoader::showYaml(), and Materials::MaterialLoader::~MaterialLoader().
The documentation for this class was generated from the following files:
MaterialLoader.h
MaterialLoader.cpp