FreeCAD: PartGui::TaskAttacher Class Reference
PartGui::TaskAttacher Class Reference
#include <TaskAttacher.h>
Public Types
using VisibilityFunction = std::function< void(bool, const std::string &, Gui::ViewProviderDocumentObject *, App::DocumentObject *, const std::string &)>
Public Member Functions
TaskAttacher (Gui::ViewProviderDocumentObject *ViewProvider, QWidget *parent, QString picture, QString text, VisibilityFunction func=0)
~TaskAttacher () override
bool getFlip () const
Attacher::eMapMode getActiveMapMode ()
getActiveMapMode returns either the default mode for selected references, or the mode that was selected by the user in the list. If no modes fit current set of references, mmDeactivated is returned.
bool isCompleted () const
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Protected Member Functions
void changeEvent (QEvent *e) override
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Protected Attributes
Gui::ViewProviderDocumentObject * ViewProvider
std::string ObjectName
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
Definition at line 51 of file TaskAttacher.h.
Member Typedef Documentation
VisibilityFunction
using PartGui::TaskAttacher::VisibilityFunction = std::function<void (bool, const std::string &, Gui::ViewProviderDocumentObject*, App::DocumentObject *, const std::string&)>
Definition at line 57 of file TaskAttacher.h.
Constructor & Destructor Documentation
TaskAttacher()
TaskAttacher::TaskAttacher (Gui::ViewProviderDocumentObject * ViewProvider, QWidget * parent, QString picture, QString text, TaskAttacher::VisibilityFunction visFunc = 0) explicit
Definition at line 104 of file TaskAttacher.cpp.
References Part::AttachExtension::AttachmentSupport, draftgeoutils.faces::bind(), draftgeoutils.intersections::connect(), Gui::Application::getDocument(), App::ExtensionContainer::getExtensionByType(), App::DocumentObjectExtension::getExtensionClassTypeId(), App::PropertyLinkSubList::getSize(), App::PropertyLinkSubList::getSubValues(), App::PropertyEnumeration::getValue(), App::PropertyBool::getValue(), QSint::ActionGroup::groupLayout(), App::ExtensionContainer::hasExtension(), Gui::Application::Instance, Part::AttachExtension::MapMode, Part::AttachExtension::MapReversed, Gui::NoResolve, App::ObjectIdentifier::parse(), Gui::Document::signalDeletedObject, Gui::Document::signalDeleteDocument, and Gui::QuantitySpinBox::valueChanged().
~TaskAttacher()
TaskAttacher::~TaskAttacher () override
Definition at line 238 of file TaskAttacher.cpp.
Member Function Documentation
changeEvent()
void TaskAttacher::changeEvent (QEvent * e) override protected
Definition at line 1092 of file TaskAttacher.cpp.
References SCL.SimpleDataTypes::e.
getActiveMapMode()
Attacher::eMapMode TaskAttacher::getActiveMapMode ()
getActiveMapMode returns either the default mode for selected references, or the mode that was selected by the user in the list. If no modes fit current set of references, mmDeactivated is returned.
Definition at line 1054 of file TaskAttacher.cpp.
References Attacher::SuggestResult::bestFitMode, Attacher::SuggestResult::message, and Attacher::mmDeactivated.
Referenced by PartDesignGui::TaskDlgDatumParameters::accept().
getFlip()
bool TaskAttacher::getFlip () const
Definition at line 1087 of file TaskAttacher.cpp.
isCompleted()
bool PartGui::TaskAttacher::isCompleted () const inline
Definition at line 73 of file TaskAttacher.h.
Member Data Documentation
ObjectName
std::string PartGui::TaskAttacher::ObjectName protected
Definition at line 138 of file TaskAttacher.h.
ViewProvider
Gui::ViewProviderDocumentObject* PartGui::TaskAttacher::ViewProvider protected
Definition at line 137 of file TaskAttacher.h.
Referenced by PartDesignGui::TaskDatumParameters::~TaskDatumParameters().
The documentation for this class was generated from the following files:
TaskAttacher.h
TaskAttacher.cpp