FreeCAD: Base::Vector2dPy Class Reference
Base::Vector2dPy Class Reference
#include <GeometryPyCXX.h>
Public Member Functions
Vector2dPy (Py::PythonClassInstance *self, Py::Tuple &args, Py::Dict &kwds)
~Vector2dPy () override
Py::Object getattro (const Py::String &name_) override
int setattro (const Py::String &name_, const Py::Object &value) override
Py::Object repr () override
const Vector2d & value () const
void setValue (const Vector2d &n)
void setValue (double vx, double vy)
Static Public Member Functions
static Py::PythonType & behaviors ()
static PyTypeObject * type_object ()
static bool check (PyObject *py)
static Py::PythonClassObject< Vector2dPy > create (const Vector2d &)
static Py::PythonClassObject< Vector2dPy > create (double vx, double vy)
static void init_type ()
methods for group handling
Py::Object number_negative () override
Py::Object number_positive () override
Py::Object number_absolute () override
Py::Object number_invert () override
Py::Object number_int () override
Py::Object number_float () override
Py::Object number_add (const Py::Object &) override
Py::Object number_subtract (const Py::Object &) override
Py::Object number_multiply (const Py::Object &) override
Py::Object number_remainder (const Py::Object &) override
Py::Object number_divmod (const Py::Object &) override
Py::Object number_lshift (const Py::Object &) override
Py::Object number_rshift (const Py::Object &) override
Py::Object number_and (const Py::Object &) override
Py::Object number_xor (const Py::Object &) override
Py::Object number_or (const Py::Object &) override
Py::Object number_power (const Py::Object &, const Py::Object &) override
Py::Object isNull (const Py::Tuple &)
Py::Object length (const Py::Tuple &)
Py::Object atan2 (const Py::Tuple &)
Py::Object square (const Py::Tuple &)
Py::Object scale (const Py::Tuple &)
Py::Object rotate (const Py::Tuple &)
Py::Object normalize (const Py::Tuple &)
Py::Object perpendicular (const Py::Tuple &)
Py::Object distance (const Py::Tuple &)
Py::Object isEqual (const Py::Tuple &)
Py::Object getAngle (const Py::Tuple &)
Py::Object projectToLine (const Py::Tuple &)
Detailed Description
Definition at line 77 of file GeometryPyCXX.h.
Constructor & Destructor Documentation
Vector2dPy()
Base::Vector2dPy::Vector2dPy (Py::PythonClassInstance * self, Py::Tuple & args, Py::Dict & kwds)
Definition at line 127 of file GeometryPyCXX.cpp.
References toolbit-attributes::args, Base::Vector2d::x, and Base::Vector2d::y.
~Vector2dPy()
Base::Vector2dPy::~Vector2dPy () override default
Member Function Documentation
atan2()
Py::Object Base::Vector2dPy::atan2 (const Py::Tuple &)
Definition at line 308 of file GeometryPyCXX.cpp.
References TestSpreadsheet::v.
behaviors()
Py::PythonType & Base::Vector2dPy::behaviors () static
Definition at line 96 of file GeometryPyCXX.cpp.
check()
bool Base::Vector2dPy::check (PyObject * py) static
Definition at line 106 of file GeometryPyCXX.cpp.
References ArchCommands::check().
create() [1/2]
Py::PythonClassObject< Vector2dPy > Base::Vector2dPy::create (const Vector2d & vec) static
Definition at line 111 of file GeometryPyCXX.cpp.
References importers.importIFClegacy::create(), and SurfaceTests.TestBlendCurve::vec.
Referenced by draftguitools.gui_labels.Label::action(), number_absolute(), number_add(), number_multiply(), number_negative(), number_positive(), and number_subtract().
create() [2/2]
Py::PythonClassObject< Vector2dPy > Base::Vector2dPy::create (double vx, double vy) static
Definition at line 116 of file GeometryPyCXX.cpp.
References Path.Post.scripts.grbl_post::type.
Referenced by draftguitools.gui_labels.Label::action().
distance()
Py::Object Base::Vector2dPy::distance (const Py::Tuple & args)
Definition at line 351 of file GeometryPyCXX.cpp.
References toolbit-attributes::args, Base::Vector2d::Distance(), Py::toVector2d(), and TestSpreadsheet::v.
Referenced by Path.Dressup.Gui.Dogbone.Bone::adaptiveLength(), and Path.Dressup.Gui.Dogbone.Bone::corner().
getAngle()
Py::Object Base::Vector2dPy::getAngle (const Py::Tuple & args)
Definition at line 366 of file GeometryPyCXX.cpp.
References toolbit-attributes::args, Py::toVector2d(), TestSpreadsheet::v, and SurfaceTests.TestBlendCurve::vec.
Referenced by Path.Dressup.Gui.Dogbone.Chord::getAngleXY(), draftguitools.gui_trackers.arcTracker::setEndPoint(), and draftguitools.gui_trackers.arcTracker::setStartPoint().
getattro()
Py::Object Base::Vector2dPy::getattro (const Py::String & name_) override
Definition at line 154 of file GeometryPyCXX.cpp.
References src.Mod.Test.testmakeWireString::String, Base::Vector2d::x, and Base::Vector2d::y.
init_type()
void Base::Vector2dPy::init_type () static
Definition at line 383 of file GeometryPyCXX.cpp.
References KDL::atan2(), Path.Dressup.Gui.Dogbone::getAngle(), and draftgeoutils.general::isNull().
isEqual()
Py::Object Base::Vector2dPy::isEqual (const Py::Tuple & args)
Definition at line 358 of file GeometryPyCXX.cpp.
References toolbit-attributes::args, Py::toVector2d(), and TestSpreadsheet::v.
isNull()
Py::Object Base::Vector2dPy::isNull (const Py::Tuple & args)
Definition at line 292 of file GeometryPyCXX.cpp.
References toolbit-attributes::args, and Base::Vector2d::IsNull().
length()
Py::Object Base::Vector2dPy::length (const Py::Tuple &)
Definition at line 302 of file GeometryPyCXX.cpp.
References TestSpreadsheet::v.
Referenced by Path.Base.Generator.dogboneII.Generator::generate(), and src.Mod.PartDesign.Scripts.FilletArc.Vector::norm().
normalize()
Py::Object Base::Vector2dPy::normalize (const Py::Tuple &)
Definition at line 336 of file GeometryPyCXX.cpp.
References TestSpreadsheet::v.
number_absolute()
Py::Object Base::Vector2dPy::number_absolute () override
Definition at line 203 of file GeometryPyCXX.cpp.
References create(), Base::Vector2d::x, and Base::Vector2d::y.
number_add()
Py::Object Base::Vector2dPy::number_add (const Py::Object & py) override
Definition at line 223 of file GeometryPyCXX.cpp.
References create(), Py::toVector2d(), and SurfaceTests.TestBlendCurve::vec.
number_and()
Py::Object Base::Vector2dPy::number_and (const Py::Object &) override
Definition at line 272 of file GeometryPyCXX.cpp.
number_divmod()
Py::Object Base::Vector2dPy::number_divmod (const Py::Object &) override
Definition at line 257 of file GeometryPyCXX.cpp.
number_float()
Py::Object Base::Vector2dPy::number_float () override
Definition at line 218 of file GeometryPyCXX.cpp.
number_int()
Py::Object Base::Vector2dPy::number_int () override
Definition at line 213 of file GeometryPyCXX.cpp.
number_invert()
Py::Object Base::Vector2dPy::number_invert () override
Definition at line 208 of file GeometryPyCXX.cpp.
number_lshift()
Py::Object Base::Vector2dPy::number_lshift (const Py::Object &) override
Definition at line 262 of file GeometryPyCXX.cpp.
number_multiply()
Py::Object Base::Vector2dPy::number_multiply (const Py::Object & py) override
Definition at line 237 of file GeometryPyCXX.cpp.
References create(), Py::toVector2d(), type_object(), and SurfaceTests.TestBlendCurve::vec.
number_negative()
Py::Object Base::Vector2dPy::number_negative () override
Definition at line 193 of file GeometryPyCXX.cpp.
References create(), Base::Vector2d::x, and Base::Vector2d::y.
number_or()
Py::Object Base::Vector2dPy::number_or (const Py::Object &) override
Definition at line 282 of file GeometryPyCXX.cpp.
number_positive()
Py::Object Base::Vector2dPy::number_positive () override
Definition at line 198 of file GeometryPyCXX.cpp.
References create(), Base::Vector2d::x, and Base::Vector2d::y.
number_power()
Py::Object Base::Vector2dPy::number_power (const Py::Object & , const Py::Object &) override
Definition at line 287 of file GeometryPyCXX.cpp.
number_remainder()
Py::Object Base::Vector2dPy::number_remainder (const Py::Object &) override
Definition at line 252 of file GeometryPyCXX.cpp.
number_rshift()
Py::Object Base::Vector2dPy::number_rshift (const Py::Object &) override
Definition at line 267 of file GeometryPyCXX.cpp.
number_subtract()
Py::Object Base::Vector2dPy::number_subtract (const Py::Object & py) override
Definition at line 230 of file GeometryPyCXX.cpp.
References create(), Py::toVector2d(), and SurfaceTests.TestBlendCurve::vec.
number_xor()
Py::Object Base::Vector2dPy::number_xor (const Py::Object &) override
Definition at line 277 of file GeometryPyCXX.cpp.
perpendicular()
Py::Object Base::Vector2dPy::perpendicular (const Py::Tuple & args)
Definition at line 343 of file GeometryPyCXX.cpp.
References toolbit-attributes::args, importers.importIFClegacy::create(), and TestSpreadsheet::v.
projectToLine()
Py::Object Base::Vector2dPy::projectToLine (const Py::Tuple & args)
Definition at line 373 of file GeometryPyCXX.cpp.
References toolbit-attributes::args, Py::toVector2d(), and TestSpreadsheet::v.
repr()
Py::Object Base::Vector2dPy::repr () override
Definition at line 142 of file GeometryPyCXX.cpp.
References Path.Post.scripts.refactored_centroid_post::str, src.Mod.Test.testmakeWireString::String, Base::Vector2d::x, and Base::Vector2d::y.
rotate()
Py::Object Base::Vector2dPy::rotate (const Py::Tuple & args)
Definition at line 328 of file GeometryPyCXX.cpp.
References toolbit-attributes::args, and TestSpreadsheet::v.
Referenced by draftguitools.gui_rotate.Rotate::numericRadius(), ArchSectionPlane.SectionPlaneTaskPanel::rotateX(), ArchSectionPlane.SectionPlaneTaskPanel::rotateY(), and ArchSectionPlane.SectionPlaneTaskPanel::rotateZ().
scale()
Py::Object Base::Vector2dPy::scale (const Py::Tuple & args)
Definition at line 320 of file GeometryPyCXX.cpp.
References toolbit-attributes::args, and TestSpreadsheet::v.
setattro()
int Base::Vector2dPy::setattro (const Py::String & name_, const Py::Object & value) override
Definition at line 177 of file GeometryPyCXX.cpp.
References value(), Base::Vector2d::x, and Base::Vector2d::y.
setValue() [1/2]
void Base::Vector2dPy::setValue (const Vector2d & n) inline
Definition at line 97 of file GeometryPyCXX.h.
setValue() [2/2]
void Base::Vector2dPy::setValue (double vx, double vy) inline
Definition at line 101 of file GeometryPyCXX.h.
square()
Py::Object Base::Vector2dPy::square (const Py::Tuple &)
Definition at line 314 of file GeometryPyCXX.cpp.
References TestSpreadsheet::v.
type_object()
PyTypeObject * Base::Vector2dPy::type_object () static
Definition at line 101 of file GeometryPyCXX.cpp.
Referenced by getPointFromPy(), and number_multiply().
value()
const Vector2d& Base::Vector2dPy::value () const inline
Definition at line 93 of file GeometryPyCXX.h.
Referenced by src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), setattro(), and Py::toVector2d().
The documentation for this class was generated from the following files:
GeometryPyCXX.h
GeometryPyCXX.cpp