FreeCAD: Gui::PropertyEditor::PropertyMaterialItem Class Reference
Gui::PropertyEditor::PropertyMaterialItem Class Reference
#include <PropertyItem.h>
Public Member Functions
QWidget * createEditor (QWidget *parent, const std::function< void()> &method) const override
void setEditorData (QWidget *editor, const QVariant &data) const override
QVariant editorData (QWidget *editor) const override
void propertyBound () override
QColor getAmbientColor () const
void setAmbientColor (const QColor &)
QColor getDiffuseColor () const
void setDiffuseColor (const QColor &)
QColor getSpecularColor () const
void setSpecularColor (const QColor &)
QColor getEmissiveColor () const
void setEmissiveColor (const QColor &)
int getShininess () const
void setShininess (int)
int getTransparency () const
void setTransparency (int)
Public Member Functions inherited from Gui::PropertyEditor::PropertyItem
~PropertyItem () override
void setPropertyData (const std::vector< App::Property * > &)
void updateData ()
const std::vector< App::Property * > & getPropertyData () const
bool hasProperty (const App::Property *) const
virtual void assignProperty (const App::Property *)
bool removeProperty (const App::Property *)
App::Property * getFirstProperty ()
const App::Property * getFirstProperty () const
virtual bool isSeparator () const
QWidget * createExpressionEditor (QWidget *parent, const std::function< void()> &method) const
void setExpressionEditorData (QWidget *editor, const QVariant &data) const
QVariant expressionEditorData (QWidget *editor) const
PropertyEditorWidget * createPropertyEditorWidget (QWidget *parent) const
void bind (const App::Property &prop) override
void bind (const App::ObjectIdentifier &_path) override
QString expressionAsString () const
void setParent (PropertyItem *parent)
PropertyItem * parent () const
void appendChild (PropertyItem *child)
void insertChild (int, PropertyItem *child)
void moveChild (int from, int to)
void removeChildren (int from, int to)
PropertyItem::removeChildren Deletes the children in the range of [from, to].
PropertyItem * takeChild (int)
PropertyItem::takeChild Removes the child at index row but doesn't delete it.
void setReadOnly (bool)
bool isReadOnly () const
bool testStatus (App::Property::Status pos) const
void setDecimals (int)
int decimals () const
void setLinked (bool)
bool isLinked () const
bool isExpanded () const
void setExpanded (bool e)
PropertyItem * child (int row)
int childCount () const
int columnCount () const
QString propertyName () const
void setPropertyName (const QString &name, const QString &realName=QString())
void setPropertyValue (const QString &)
virtual QVariant data (int column, int role) const
bool setData (const QVariant &value)
Qt::ItemFlags flags (int column) const
virtual int row () const
void reset ()
bool hasAnyExpression () const
Public Member Functions inherited from Gui::ExpressionBinding
ExpressionBinding ()
virtual ~ExpressionBinding ()
bool isBound () const
void unbind ()
virtual bool apply (const std::string &propName)
virtual bool apply ()
bool hasExpression () const
bool autoApply () const
void setAutoApply (bool value)
Static Public Member Functions
static void * create (void)
static void init (void)
Static Public Member Functions inherited from Gui::PropertyEditor::PropertyItem
static void * create (void)
static void init (void)
Protected Member Functions
PropertyMaterialItem ()
~PropertyMaterialItem () override
QVariant decoration (const QVariant &) const override
QVariant toolTip (const App::Property *) const override
QVariant toString (const QVariant &) const override
QVariant value (const App::Property *) const override
void setValue (const QVariant &) override
Protected Member Functions inherited from Gui::PropertyEditor::PropertyItem
PropertyItem ()
void setPropertyValue (const std::string &value)
virtual QVariant displayName () const
virtual void initialize ()
void onChange () override
Protected Member Functions inherited from Gui::ExpressionBinding
const App::ObjectIdentifier & getPath () const
std::shared_ptr< App::Expression > getExpression () const
std::string getExpressionString (bool no_throw=true) const
std::string getEscapedExpressionString () const
bool assignToProperty (const std::string &propName, double)
virtual void setExpression (std::shared_ptr< App::Expression > expr)
void expressionChange (const App::ObjectIdentifier &id)
void objectDeleted (const App::DocumentObject &)
Properties
QColor AmbientColor
QColor DiffuseColor
QColor SpecularColor
QColor EmissiveColor
float Shininess
float Transparency
Additional Inherited Members
Protected Attributes inherited from Gui::PropertyEditor::PropertyItem
QString propName
QString displayText
std::vector< App::Property * > propertyItems
PropertyItem * parentItem
QList< PropertyItem * > childItems
bool readonly
int precision
bool linked
bool expanded
Protected Attributes inherited from Gui::ExpressionBinding
boost::signals2::scoped_connection expressionchanged
boost::signals2::scoped_connection objectdeleted
bool m_autoApply {false}
Detailed Description
Change a material property.
Author
Werner Mayer
Definition at line 1042 of file PropertyItem.h.
Constructor & Destructor Documentation
PropertyMaterialItem()
PropertyMaterialItem::PropertyMaterialItem () protected
Definition at line 3514 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyIntegerConstraintItem::create(), Gui::PropertyEditor::PropertyColorItem::create(), KDL::max(), KDL::min(), Gui::PropertyEditor::PropertyItem::setParent(), and Gui::PropertyEditor::PropertyIntegerConstraintItem::setRange().
~PropertyMaterialItem()
PropertyMaterialItem::~PropertyMaterialItem () override protected default
Member Function Documentation
create()
static void* Gui::PropertyEditor::PropertyMaterialItem::create (void) static
Referenced by draftguitools.gui_labels.Label::action().
createEditor()
QWidget * PropertyMaterialItem::createEditor (QWidget * parent, const std::function< void()> & method) const override virtual
Creates the appropriate editor for this item and sets the editor to the value of overrideValue().
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 3817 of file PropertyItem.cpp.
References Gui::ColorButton::changed(), draftgeoutils.intersections::connect(), Gui::PropertyEditor::PropertyItem::isReadOnly(), and Gui::PropertyEditor::PropertyItem::parent().
decoration()
QVariant PropertyMaterialItem::decoration (const QVariant & value) const override protected virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 3699 of file PropertyItem.cpp.
References buildPsets::p, toolbit-attributes::val, and value().
editorData()
QVariant PropertyMaterialItem::editorData (QWidget * editor) const override virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 3837 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), Path.Post.Utils::editor(), toolbit-attributes::val, and value().
getAmbientColor()
QColor PropertyMaterialItem::getAmbientColor () const
Definition at line 3584 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), toolbit-attributes::val, and value().
getDiffuseColor()
QColor PropertyMaterialItem::getDiffuseColor () const
Definition at line 3561 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), toolbit-attributes::val, and value().
getEmissiveColor()
QColor PropertyMaterialItem::getEmissiveColor () const
Definition at line 3630 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), toolbit-attributes::val, and value().
getShininess()
int PropertyMaterialItem::getShininess () const
Definition at line 3653 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), toolbit-attributes::val, and value().
getSpecularColor()
QColor PropertyMaterialItem::getSpecularColor () const
Definition at line 3607 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), toolbit-attributes::val, and value().
getTransparency()
int PropertyMaterialItem::getTransparency () const
Definition at line 3676 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), toolbit-attributes::val, and value().
init()
void Gui::PropertyEditor::PropertyMaterialItem::init (void) static
Definition at line 3512 of file PropertyItem.cpp.
Referenced by DocumentObject.DocumentObject::onChanged().
propertyBound()
void PropertyMaterialItem::propertyBound () override virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 3558 of file PropertyItem.cpp.
setAmbientColor()
void PropertyMaterialItem::setAmbientColor (const QColor & color)
Definition at line 3595 of file PropertyItem.cpp.
References Gui::PropertyEditor::Material::ambientColor, Gui::PropertyEditor::PropertyItem::data(), setValue(), and value().
setDiffuseColor()
void PropertyMaterialItem::setDiffuseColor (const QColor & color)
Definition at line 3572 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), Gui::PropertyEditor::Material::diffuseColor, setValue(), and value().
setEditorData()
void PropertyMaterialItem::setEditorData (QWidget * editor, const QVariant & data) const override virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 3826 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), Path.Post.Utils::editor(), and toolbit-attributes::val.
setEmissiveColor()
void PropertyMaterialItem::setEmissiveColor (const QColor & color)
Definition at line 3641 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), Gui::PropertyEditor::Material::emissiveColor, setValue(), and value().
setShininess()
void PropertyMaterialItem::setShininess (int s)
Definition at line 3664 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), toolbit-attributes::s, setValue(), Gui::PropertyEditor::Material::shininess, and value().
setSpecularColor()
void PropertyMaterialItem::setSpecularColor (const QColor & color)
Definition at line 3618 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), setValue(), Gui::PropertyEditor::Material::specularColor, and value().
setTransparency()
void PropertyMaterialItem::setTransparency (int t)
Definition at line 3687 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), setValue(), InitGui::t, Gui::PropertyEditor::Material::transparency, and value().
setValue()
void PropertyMaterialItem::setValue (const QVariant & value) override protected virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 3773 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), Gui::PropertyEditor::PropertyItem::decimals(), Gui::ExpressionBinding::hasExpression(), toolbit-attributes::s, Gui::PropertyEditor::PropertyItem::setPropertyValue(), App::Color::setValue(), InitGui::t, and value().
Referenced by setAmbientColor(), setDiffuseColor(), setEmissiveColor(), setShininess(), setSpecularColor(), and setTransparency().
toolTip()
QVariant PropertyMaterialItem::toolTip (const App::Property * prop) const override protected virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 3722 of file PropertyItem.cpp.
References Gui::PropertyEditor::PropertyItem::data(), getValue(), Base::BaseClass::isDerivedFrom(), and value().
toString()
QVariant PropertyMaterialItem::toString (const QVariant & prop) const override protected virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 3712 of file PropertyItem.cpp.
References toolbit-attributes::val, and value().
value()
QVariant PropertyMaterialItem::value (const App::Property * prop) const override protected virtual
Reimplemented from Gui::PropertyEditor::PropertyItem.
Definition at line 3756 of file PropertyItem.cpp.
References Gui::PropertyEditor::Material::ambientColor, Gui::PropertyEditor::Material::diffuseColor, Gui::PropertyEditor::Material::emissiveColor, getValue(), Base::BaseClass::isDerivedFrom(), Gui::PropertyEditor::Material::shininess, Gui::PropertyEditor::Material::specularColor, and Gui::PropertyEditor::Material::transparency.
Referenced by decoration(), editorData(), src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), getAmbientColor(), getDiffuseColor(), getEmissiveColor(), getShininess(), getSpecularColor(), getTransparency(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), setAmbientColor(), setDiffuseColor(), setEmissiveColor(), setShininess(), setSpecularColor(), setTransparency(), setValue(), toolTip(), and toString().
Property Documentation
AmbientColor
QColor Gui::PropertyEditor::PropertyMaterialItem::AmbientColor read write
Definition at line 1046 of file PropertyItem.h.
DiffuseColor
QColor Gui::PropertyEditor::PropertyMaterialItem::DiffuseColor read write
Definition at line 1047 of file PropertyItem.h.
EmissiveColor
QColor Gui::PropertyEditor::PropertyMaterialItem::EmissiveColor read write
Definition at line 1049 of file PropertyItem.h.
Shininess
float Gui::PropertyEditor::PropertyMaterialItem::Shininess read write
Definition at line 1050 of file PropertyItem.h.
SpecularColor
QColor Gui::PropertyEditor::PropertyMaterialItem::SpecularColor read write
Definition at line 1048 of file PropertyItem.h.
Transparency
float Gui::PropertyEditor::PropertyMaterialItem::Transparency read write
Definition at line 1051 of file PropertyItem.h.
The documentation for this class was generated from the following files:
PropertyItem.h
PropertyItem.cpp