FreeCAD: CBox2D Class Reference
CBox2D Class Reference
#include <Box2D.h>
Public Member Functions
CBox2D ()
CBox2D (const Point &minxy, const Point &maxxy)
bool operator== (const CBox2D &rhs) const
bool operator!= (const CBox2D &rhs) const
void Insert (const Point &p)
void Insert (const CBox2D &b)
Point Centre () const
double Width () const
double Height () const
double Radius () const
double MinX () const
double MaxX () const
double MinY () const
double MaxY () const
Public Attributes
Point m_minxy
Point m_maxxy
bool m_valid
Detailed Description
Definition at line 34 of file Box2D.h.
Constructor & Destructor Documentation
CBox2D() [1/2]
CBox2D::CBox2D () inline
Definition at line 41 of file Box2D.h.
CBox2D() [2/2]
CBox2D::CBox2D (const Point & minxy, const Point & maxxy) inline
Definition at line 44 of file Box2D.h.
Member Function Documentation
Centre()
Point CBox2D::Centre () const inline
Definition at line 118 of file Box2D.h.
References m_maxxy, and m_minxy.
Height()
double CBox2D::Height () const inline
Definition at line 131 of file Box2D.h.
References m_maxxy, m_minxy, m_valid, and Point::y.
Referenced by Radius().
Insert() [1/2]
void CBox2D::Insert (const CBox2D & b) inline
Definition at line 94 of file Box2D.h.
References SCL.SimpleDataTypes::b, m_maxxy, m_minxy, m_valid, Point::x, and Point::y.
Insert() [2/2]
void CBox2D::Insert (const Point & p) inline
Definition at line 71 of file Box2D.h.
References m_maxxy, m_minxy, m_valid, buildPsets::p, Point::x, and Point::y.
MaxX()
double CBox2D::MaxX () const inline
Definition at line 148 of file Box2D.h.
References m_maxxy, and Point::x.
Referenced by BOOST_PYTHON_MODULE(), and init_pyarea().
MaxY()
double CBox2D::MaxY () const inline
Definition at line 156 of file Box2D.h.
References m_maxxy, and Point::y.
Referenced by BOOST_PYTHON_MODULE(), and init_pyarea().
MinX()
double CBox2D::MinX () const inline
Definition at line 144 of file Box2D.h.
References m_minxy, and Point::x.
Referenced by BOOST_PYTHON_MODULE(), and init_pyarea().
MinY()
double CBox2D::MinY () const inline
Definition at line 152 of file Box2D.h.
References m_minxy, and Point::y.
Referenced by BOOST_PYTHON_MODULE(), and init_pyarea().
operator!=()
bool CBox2D::operator!= (const CBox2D & rhs) const inline
Definition at line 65 of file Box2D.h.
operator==()
bool CBox2D::operator== (const CBox2D & rhs) const inline
Definition at line 50 of file Box2D.h.
References m_maxxy, m_minxy, and m_valid.
Radius()
double CBox2D::Radius () const inline
Definition at line 140 of file Box2D.h.
References Height(), KDL::sqrt(), and Width().
Width()
double CBox2D::Width () const inline
Definition at line 122 of file Box2D.h.
References m_maxxy, m_minxy, m_valid, and Point::x.
Referenced by Radius().
Member Data Documentation
m_maxxy
Point CBox2D::m_maxxy
Definition at line 38 of file Box2D.h.
Referenced by Centre(), Height(), Insert(), MaxX(), MaxY(), operator==(), and Width().
m_minxy
Point CBox2D::m_minxy
Definition at line 37 of file Box2D.h.
Referenced by Centre(), Height(), Insert(), MinX(), MinY(), operator==(), and Width().
m_valid
bool CBox2D::m_valid
Definition at line 39 of file Box2D.h.
Referenced by Height(), Insert(), operator==(), and Width().
The documentation for this class was generated from the following file:
Box2D.h