FreeCAD: Gui::Dialog::RedoDialog Class Reference
Gui::Dialog::RedoDialog Class Reference
#include <DlgUndoRedo.h>
Public Member Functions
RedoDialog (QWidget *parent=nullptr)
~RedoDialog () override
Protected Slots
void onSelected ()
void onFetchInfo ()
Detailed Description
This class implements the redo dialog.
Author
Werner Mayer
Definition at line 91 of file DlgUndoRedo.h.
Constructor & Destructor Documentation
RedoDialog()
RedoDialog::RedoDialog (QWidget * parent = nullptr) explicit
Constructs a UndoRedoDialog which is a child of 'parent', with the name 'name'.'
Definition at line 90 of file DlgUndoRedo.cpp.
References draftgeoutils.intersections::connect(), and onFetchInfo().
~RedoDialog()
RedoDialog::~RedoDialog () override default
Destroys the object and frees any allocated resources.
Member Function Documentation
onFetchInfo
void RedoDialog::onFetchInfo () protected slot
This method fetches the undo / redo information from the active document and shows it in the undo / redo dialog.
Definition at line 105 of file DlgUndoRedo.cpp.
References Gui::MainWindow::activeWindow(), Path.Op.Gui.Selection::clear(), Gui::getMainWindow(), SplineSurface::i, onSelected(), and Gui::MDIView::redoActions().
Referenced by RedoDialog().
onSelected
void RedoDialog::onSelected () protected slot
Closes the dialog and sends the message 'Redo' to the currently active MDI view.
Definition at line 119 of file DlgUndoRedo.cpp.
References a, Gui::Application::Instance, and Gui::Application::sendMsgToActiveView().
Referenced by onFetchInfo().
The documentation for this class was generated from the following files:
DlgUndoRedo.h
DlgUndoRedo.cpp