FreeCAD: Command.cpp File Reference
Mod/PartDesign/Gui/Command.cpp File Reference
#include "PreCompiled.h"
#include <BRep_Tool.hxx>
#include <BRepAdaptor_Surface.hxx>
#include <GeomLib_IsPlanarSurface.hxx>
#include <QMessageBox>
#include <TopExp_Explorer.hxx>
#include <TopLoc_Location.hxx>
#include <TopoDS.hxx>
#include <TopoDS_Face.hxx>
#include <App/Origin.h>
#include <App/Part.h>
#include <Base/Tools.h>
#include <Gui/Application.h>
#include <Gui/Command.h>
#include <Gui/CommandT.h>
#include <Gui/Control.h>
#include <Gui/Document.h>
#include <Gui/MainWindow.h>
#include <Gui/Selection.h>
#include <Gui/SelectionObject.h>
#include <Mod/Sketcher/App/SketchObject.h>
#include <Mod/PartDesign/App/Body.h>
#include <Mod/PartDesign/App/FeatureBoolean.h>
#include <Mod/PartDesign/App/FeatureGroove.h>
#include <Mod/PartDesign/App/FeatureMultiTransform.h>
#include <Mod/PartDesign/App/FeatureRevolution.h>
#include <Mod/PartDesign/App/FeatureTransformed.h>
#include <Mod/PartDesign/App/DatumLine.h>
#include <Mod/PartDesign/App/DatumPlane.h>
#include <Mod/PartDesign/App/DatumPoint.h>
#include <Mod/PartDesign/App/FeatureDressUp.h>
#include <Mod/PartDesign/App/ShapeBinder.h>
#include "DlgActiveBody.h"
#include "ReferenceSelection.h"
#include "SketchWorkflow.h"
#include "TaskFeaturePick.h"
#include "Utils.h"
#include "WorkflowManager.h"
#include "ViewProvider.h"
#include "ViewProviderBody.h"
#include "ui_DlgReference.h"
Classes
class CmdPartDesignCompDatums
class CmdPartDesignCompSketches
Functions
void UnifiedDatumCommand (Gui::Command &cmd, Base::Type type, std::string name)
UnifiedDatumCommand is a common routine called by datum plane, line and point commands.
void finishFeature (const Gui::Command *cmd, App::DocumentObject *Feat, App::DocumentObject *prevSolidFeature=nullptr, const bool hidePrevSolid=true, const bool updateDocument=true)
unsigned validateSketches (std::vector< App::DocumentObject * > &sketches, std::vector< PartDesignGui::TaskFeaturePick::featureStatus > &status, std::vector< App::DocumentObject * >::iterator &firstFreeSketch)
bool importExternalElements (App::PropertyLinkSub &prop, std::vector< App::SubObjectT > _sobjs)
void prepareProfileBased (PartDesign::Body *pcActiveBody, Gui::Command *cmd, const std::string &which, std::function< void(Part::Feature *, App::DocumentObject *)> func)
void finishProfileBased (const Gui::Command *cmd, const Part::Feature *sketch, App::DocumentObject *Feat)
void prepareProfileBased (Gui::Command *cmd, const std::string &which, double length)
bool dressupGetSelected (Gui::Command *cmd, const std::string &which, Gui::SelectionObject &selected, bool &useAllEdges, bool &noSelection)
void finishDressupFeature (const Gui::Command *cmd, const std::string &which, Part::Feature *base, const std::vector< std::string > &SubNames, const bool useAllEdges)
void makeChamferOrFillet (Gui::Command *cmd, const std::string &which)
void prepareTransformed (PartDesign::Body *pcActiveBody, Gui::Command *cmd, const std::string &which, std::function< void(App::DocumentObject *, std::vector< App::DocumentObject * >)> func)
void finishTransformed (Gui::Command *cmd, App::DocumentObject *Feat)
void CreatePartDesignCommands ()
Function Documentation
CreatePartDesignCommands()
void CreatePartDesignCommands ()
Definition at line 2448 of file Mod/PartDesign/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
dressupGetSelected()
bool dressupGetSelected (Gui::Command * cmd, const std::string & which, Gui::SelectionObject & selected, bool & useAllEdges, bool & noSelection)
Definition at line 1631 of file Mod/PartDesign/Gui/Command.cpp.
References Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::clearSelection(), src.Mod.AddonManager.NetworkManager::count, Part::TopoShape::countSubElements(), App::GetApplication(), PartDesignGui::getBody(), PartDesignGui::getBodyFor(), Base::Persistence::getClassTypeId(), App::Application::getDocumentName(), Gui::getMainWindow(), Gui::SelectionObject::getObject(), UtilsAssembly::getObject(), Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), Part::TopoShape::getShape(), Gui::SelectionObject::isObjectTypeOf(), Path.Dressup.Utils::selection(), Gui::Selection(), Part::TopoShape::shapeName(), and Path.Log::warning().
Referenced by makeChamferOrFillet().
finishDressupFeature()
void finishDressupFeature (const Gui::Command * cmd, const std::string & which, Part::Feature * base, const std::vector< std::string > & SubNames, const bool useAllEdges)
Definition at line 1698 of file Mod/PartDesign/Gui/Command.cpp.
References FCMD_OBJ_CMD, finishFeature(), PartDesignGui::getBodyFor(), Gui::Command::getObjectCmd(), Gui::Command::getUniqueObjectName(), Gui::Application::getViewProvider(), Gui::Command::Gui, Gui::Application::Instance, Gui::Command::openCommand(), App::PropertyBool::setValue(), Path.Post.scripts.refactored_centroid_post::str, and Gui::ViewProviderDocumentObject::Visibility.
Referenced by makeChamferOrFillet().
finishFeature()
void finishFeature (const Gui::Command * cmd, App::DocumentObject * Feat, App::DocumentObject * prevSolidFeature = nullptr, const bool hidePrevSolid = true, const bool updateDocument = true)
Definition at line 531 of file Mod/PartDesign/Gui/Command.cpp.
References importers.importWebGL::base, FCMD_OBJ_HIDE, PartDesignGui::getBody(), PartDesignGui::getBodyFor(), Gui::Command::Gui, PartDesignGui::setEdit(), and Gui::Command::updateActive().
Referenced by finishDressupFeature(), finishProfileBased(), and finishTransformed().
finishProfileBased()
void finishProfileBased (const Gui::Command * cmd, const Part::Feature * sketch, App::DocumentObject * Feat)
Definition at line 1049 of file Mod/PartDesign/Gui/Command.cpp.
References FCMD_OBJ_HIDE, finishFeature(), Base::Persistence::getClassTypeId(), and Base::BaseClass::isDerivedFrom().
Referenced by prepareProfileBased().
finishTransformed()
void finishTransformed (Gui::Command * cmd, App::DocumentObject * Feat)
Definition at line 1991 of file Mod/PartDesign/Gui/Command.cpp.
References finishFeature().
importExternalElements()
bool importExternalElements (App::PropertyLinkSub & prop, std::vector< App::SubObjectT > _sobjs)
Partially pulled from Linkstage3 importExternalObjects for toponaming element map compatibility with sketches that contain point objects. By adding an empty subobject when appropriate, we allow those sketches to be used as profiles without error.
Parameters
prop The property (generally a Profile link)
_sobjs Subobjects to use
report True if we should raise a dialog, otherwise raise and exception
Returns
True if elements were found
Definition at line 677 of file Mod/PartDesign/Gui/Command.cpp.
References FC_THROWM, PartDesign::Body::findBodyOf(), App::Property::getContainer(), App::Property::getName(), App::PropertyLinkSub::getSubValues(), App::PropertyLinkSub::getValue(), Path.Post.scripts.opensbp_post::move(), App::PropertyLinkSub::setValue(), and importers.importIFCmulticore::subs.
Referenced by prepareProfileBased().
makeChamferOrFillet()
void makeChamferOrFillet (Gui::Command * cmd, const std::string & which)
Definition at line 1733 of file Mod/PartDesign/Gui/Command.cpp.
References importers.importWebGL::base, dressupGetSelected(), finishDressupFeature(), PartDesignGui::getBody(), Gui::SelectionObject::getObject(), Gui::SelectionObject::getSubNames(), App::PropertyLink::getValue(), and Part::BodyBase::Tip.
prepareProfileBased() [1/2]
void prepareProfileBased (Gui::Command * cmd, const std::string & which, double length)
Definition at line 1056 of file Mod/PartDesign/Gui/Command.cpp.
References Gui::Command::adjustCameraPosition(), Gui::cmdAppObject(), FCMD_OBJ_CMD, finishProfileBased(), PartDesignGui::getBody(), Gui::Command::getObjectCmd(), length(), prepareProfileBased(), Path.Post.scripts.refactored_centroid_post::str, and Gui::Command::updateActive().
prepareProfileBased() [2/2]
void prepareProfileBased (PartDesign::Body * pcActiveBody, Gui::Command * cmd, const std::string & which, std::function< void(Part::Feature *, App::DocumentObject *)> func)
Definition at line 764 of file Mod/PartDesign/Gui/Command.cpp.
References Gui::ControlSingleton::activeDialog(), PartDesign::Body::addObject(), Gui::SelectionSingleton::clearSelection(), Gui::ControlSingleton::closeDialog(), Gui::Control(), Drawing::copy(), FCMD_OBJ_CMD, PartDesign::Body::findBodyOf(), PartDesignGui::getBodyFor(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), Gui::Command::getDocument(), Gui::getMainWindow(), UtilsAssembly::getObject(), App::Document::getObject(), Gui::Command::getObjectCmd(), App::Document::getObjectsOfType(), Gui::SelectionSingleton::getObjectsOfType(), PartDesignGui::getPartFor(), Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), Gui::Command::getUniqueObjectName(), importExternalElements(), Base::BaseClass::isDerivedFrom(), PartDesign::Body::isSolid(), App::DocumentObject::isTouched(), PartDesignGui::TaskFeaturePick::makeCopy(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, App::DocumentObject::recomputeFeature(), result, toolbit-attributes::s, Path.Dressup.Utils::selection(), Gui::Selection(), Gui::ControlSingleton::showDialog(), importers.importIFCmulticore::subs, validateSketches(), and Path.Log::warning().
Referenced by prepareProfileBased().
prepareTransformed()
void prepareTransformed (PartDesign::Body * pcActiveBody, Gui::Command * cmd, const std::string & which, std::function< void(App::DocumentObject *, std::vector< App::DocumentObject * >)> func)
Definition at line 1941 of file Mod/PartDesign/Gui/Command.cpp.
References FCMD_OBJ_CMD, PartDesignGui::getBody(), PartDesignGui::getBodyFor(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), Gui::getMainWindow(), App::Document::getObject(), Gui::Command::getObjectCmd(), Gui::SelectionSingleton::getObjectsOfType(), Gui::Command::getSelection(), Gui::Command::getUniqueObjectName(), Path.Op.Surface::msg, Gui::Command::openCommand(), Path.Post.scripts.refactored_centroid_post::str, Gui::Command::updateActive(), and Path.Log::warning().
UnifiedDatumCommand()
void UnifiedDatumCommand (Gui::Command & cmd, Base::Type type, std::string name)
UnifiedDatumCommand is a common routine called by datum plane, line and point commands.
Parameters
cmd (i/o) command, to have shortcuts to doCommand, etc.
type (input)
name (input). Is used to generate new name for an object, and to fill undo messages.
Definition at line 91 of file Mod/PartDesign/Gui/Command.cpp.
References Part::AttachExtension::attacher(), Attacher::SuggestResult::bestFitMode, Gui::Command::Doc, SCL.SimpleDataTypes::e, FCMD_OBJ_CMD, PartDesignGui::getBody(), App::DocumentObject::getDocument(), Gui::getMainWindow(), App::Document::getObject(), App::PropertyLinkSubList::getPyReprString(), App::PropertyLinkSubList::getSize(), App::PropertyLinkSubList::getValue(), Base::BaseClass::isDerivedFrom(), Attacher::SuggestResult::message, App::PropertyLinkSubList::removeValue(), PartDesignGui::setEdit(), Attacher::AttachEngine::setReferences(), Attacher::SuggestResult::srOK, Attacher::AttachEngine::suggestMapModes(), src.Mod.AddonManager.Addon::translate, Path.Post.scripts.grbl_post::type, and Path.Log::warning().
validateSketches()
unsigned validateSketches (std::vector< App::DocumentObject * > & sketches, std::vector< PartDesignGui::TaskFeaturePick::featureStatus > & status, std::vector< App::DocumentObject * >::iterator & firstFreeSketch)
Definition at line 580 of file Mod/PartDesign/Gui/Command.cpp.
References PartDesignGui::TaskFeaturePick::afterTip, SCL.SimpleDataTypes::b, PartDesign::Body::findBodyOf(), PartDesignGui::getBody(), PartDesignGui::getPartFor(), Part::PropertyPartShape::getValue(), App::OriginGroupExtension::hasObject(), PartDesignGui::TaskFeaturePick::invalidShape, PartDesign::Body::isAfterInsertPoint(), PartDesignGui::TaskFeaturePick::isUsed, PartDesignGui::TaskFeaturePick::notInBody, PartDesignGui::TaskFeaturePick::noWire, src.Mod.Test.testPathArray::o, PartDesignGui::TaskFeaturePick::otherBody, PartDesignGui::TaskFeaturePick::otherPart, toolbit-attributes::s, Part::Feature::Shape, and PartDesignGui::TaskFeaturePick::validFeature.
Referenced by prepareProfileBased().