FreeCAD: MeshCore::MeshAlgorithm Class Reference
MeshCore::MeshAlgorithm Class Reference
#include <Algorithm.h>
Public Member Functions
MeshAlgorithm (const MeshKernel &rclM)
bool NearestFacetOnRay (const Base::Vector3f &rclPt, const Base::Vector3f &rclDir, Base::Vector3f &rclRes, FacetIndex &rulFacet) const
bool NearestFacetOnRay (const Base::Vector3f &rclPt, const Base::Vector3f &rclDir, float fMaxAngle, Base::Vector3f &rclRes, FacetIndex &rulFacet) const
bool NearestFacetOnRay (const Base::Vector3f &rclPt, const Base::Vector3f &rclDir, const MeshFacetGrid &rclGrid, Base::Vector3f &rclRes, FacetIndex &rulFacet) const
bool NearestFacetOnRay (const Base::Vector3f &rclPt, const Base::Vector3f &rclDir, const std::vector< FacetIndex > &raulFacets, Base::Vector3f &rclRes, FacetIndex &rulFacet) const
bool NearestFacetOnRay (const Base::Vector3f &rclPt, const Base::Vector3f &rclDir, float fMaxSearchArea, const MeshFacetGrid &rclGrid, Base::Vector3f &rclRes, FacetIndex &rulFacet) const
bool FirstFacetToVertex (const Base::Vector3f &rPt, float fMaxDistance, const MeshFacetGrid &rGrid, FacetIndex &uIndex) const
bool IsVertexVisible (const Base::Vector3f &rcVertex, const Base::Vector3f &rcView, const MeshFacetGrid &rclGrid) const
float GetAverageEdgeLength () const
float GetMinimumEdgeLength () const
float GetMaximumEdgeLength () const
Base::Vector3f GetGravityPoint () const
void GetMeshBorders (std::list< std::vector< Base::Vector3f >> &rclBorders) const
void GetMeshBorders (std::list< std::vector< PointIndex >> &rclBorders) const
void GetFacetBorders (const std::vector< FacetIndex > &raulInd, std::list< std::vector< Base::Vector3f >> &rclBorders) const
void GetFacetBorders (const std::vector< FacetIndex > &raulInd, std::list< std::vector< PointIndex >> &rclBorders, bool ignoreOrientation=false) const
void GetFacetBorder (FacetIndex uFacet, std::list< PointIndex > &rBorder) const
void GetFacetsBorders (const std::vector< FacetIndex > &uFacets, std::list< std::vector< PointIndex >> &rBorders) const
void SplitBoundaryLoops (std::list< std::vector< PointIndex >> &aBorders)
bool FillupHole (const std::vector< PointIndex > &boundary, AbstractPolygonTriangulator &cTria, MeshFacetArray &rFaces, MeshPointArray &rPoints, int level, const MeshRefPointToFacets *pP2FStructure=nullptr) const
void SetFacetsProperty (const std::vector< FacetIndex > &raulInds, const std::vector< unsigned long > &raulProps) const
void SetFacetFlag (MeshFacet::TFlagType tF) const
void SetPointFlag (MeshPoint::TFlagType tF) const
void ResetFacetFlag (MeshFacet::TFlagType tF) const
void ResetPointFlag (MeshPoint::TFlagType tF) const
void SetFacetsFlag (const std::vector< FacetIndex > &raulInds, MeshFacet::TFlagType tF) const
void SetPointsFlag (const std::vector< PointIndex > &raulInds, MeshPoint::TFlagType tF) const
void GetFacetsFlag (std::vector< FacetIndex > &raulInds, MeshFacet::TFlagType tF) const
void GetPointsFlag (std::vector< PointIndex > &raulInds, MeshPoint::TFlagType tF) const
void ResetFacetsFlag (const std::vector< FacetIndex > &raulInds, MeshFacet::TFlagType tF) const
void ResetPointsFlag (const std::vector< PointIndex > &raulInds, MeshPoint::TFlagType tF) const
unsigned long CountFacetFlag (MeshFacet::TFlagType tF) const
unsigned long CountPointFlag (MeshPoint::TFlagType tF) const
void PointsFromFacetsIndices (const std::vector< FacetIndex > &rvecIndices, std::vector< Base::Vector3f > &rvecPoints) const
void GetFacetsFromToolMesh (const MeshKernel &rToolMesh, const Base::Vector3f &rcDir, std::vector< FacetIndex > &raclCutted) const
void GetFacetsFromToolMesh (const MeshKernel &rToolMesh, const Base::Vector3f &rcDir, const MeshFacetGrid &rGrid, std::vector< FacetIndex > &raclCutted) const
int Surround (const Base::BoundBox3f &rBox, const Base::Vector3f &rcDir)
void CheckFacets (const MeshFacetGrid &rclGrid, const Base::ViewProjMethod *pclProj, const Base::Polygon2d &rclPoly, bool bInner, std::vector< FacetIndex > &facets) const
void CheckFacets (const Base::ViewProjMethod *pclProj, const Base::Polygon2d &rclPoly, bool bInner, std::vector< FacetIndex > &facets) const
void CheckBorderFacets (const std::vector< FacetIndex > &raclFacetIndices, std::vector< FacetIndex > &raclResultIndices, unsigned short usLevel=1) const
void CutBorderFacets (std::vector< FacetIndex > &raclFacetIndices, unsigned short usLevel=1) const
unsigned long CountBorderEdges () const
void GetBorderPoints (const std::vector< FacetIndex > &raclFacetIndices, std::set< PointIndex > &raclResultPointsIndices) const
float Surface () const
void SubSampleByDist (float fDist, std::vector< Base::Vector3f > &rclPoints) const
void SubSampleByCount (unsigned long ulCtPoints, std::vector< Base::Vector3f > &rclPoints) const
void SubSampleAllPoints (std::vector< Base::Vector3f > &rclPoints) const
void SearchFacetsFromPolyline (const std::vector< Base::Vector3f > &rclPolyline, float fRadius, const MeshFacetGrid &rclGrid, std::vector< FacetIndex > &rclResultFacetsIndices) const
bool NearestPointFromPoint (const Base::Vector3f &rclPt, FacetIndex &rclResFacetIndex, Base::Vector3f &rclResPoint) const
bool NearestPointFromPoint (const Base::Vector3f &rclPt, const MeshFacetGrid &rclGrid, FacetIndex &rclResFacetIndex, Base::Vector3f &rclResPoint) const
bool NearestPointFromPoint (const Base::Vector3f &rclPt, const MeshFacetGrid &rclGrid, float fMaxSearchArea, FacetIndex &rclResFacetIndex, Base::Vector3f &rclResPoint) const
bool CutWithPlane (const Base::Vector3f &clBase, const Base::Vector3f &clNormal, const MeshFacetGrid &rclGrid, std::list< std::vector< Base::Vector3f >> &rclResult, float fMinEps=1.0e-2F, bool bConnectPolygons=false) const
void GetFacetsFromPlane (const MeshFacetGrid &rclGrid, const Base::Vector3f &clNormal, float dist, const Base::Vector3f &rclLeft, const Base::Vector3f &rclRight, std::vector< FacetIndex > &rclRes) const
bool Distance (const Base::Vector3f &rclPt, FacetIndex ulFacetIdx, float fMaxDistance, float &rfDistance) const
float CalculateMinimumGridLength (float fLength, const Base::BoundBox3f &rBBox, unsigned long maxElements) const
Protected Member Functions
bool ConnectLines (std::list< std::pair< Base::Vector3f, Base::Vector3f >> &rclLines, std::list< std::vector< Base::Vector3f >> &rclPolylines, float fMinEps) const
bool ConnectPolygons (std::list< std::vector< Base::Vector3f >> &clPolyList, std::list< std::pair< Base::Vector3f, Base::Vector3f >> &rclLines) const
bool RayNearestField (const Base::Vector3f &rclPt, const Base::Vector3f &rclDir, const std::vector< FacetIndex > &raulFacets, Base::Vector3f &rclRes, FacetIndex &rulFacet, float fMaxAngle=Mathf::PI) const
void SplitBoundaryLoops (const std::vector< PointIndex > &rBound, std::list< std::vector< PointIndex >> &aBorders)
void SplitBoundaryFromOpenEdges (std::list< std::pair< PointIndex, PointIndex >> &openEdges, std::list< PointIndex > &boundary) const
Detailed Description
The MeshAlgorithm class provides algorithms base on meshes.
Definition at line 56 of file Algorithm.h.
Constructor & Destructor Documentation
MeshAlgorithm()
MeshCore::MeshAlgorithm::MeshAlgorithm (const MeshKernel & rclM) inline explicit
Definition at line 59 of file Algorithm.h.
Member Function Documentation
CalculateMinimumGridLength()
float MeshAlgorithm::CalculateMinimumGridLength (float fLength, const Base::BoundBox3f & rBBox, unsigned long maxElements) const
Calculates the minimum grid length so that not more elements than maxElements will be created when the grid gets built up. The minimum grid length must be at least fLength.
Definition at line 1816 of file Algorithm.cpp.
References Base::BoundBox3< Precision >::LengthX(), Base::BoundBox3< Precision >::LengthY(), Base::BoundBox3< Precision >::LengthZ(), and Base::pow().
CheckBorderFacets()
void MeshAlgorithm::CheckBorderFacets (const std::vector< FacetIndex > & raclFacetIndices, std::vector< FacetIndex > & raclResultIndices, unsigned short usLevel = 1) const
Determines all facets of the given array raclFacetIndices that lie at the edge or that have at least neighbour facet that is not inside the array. The resulting array raclResultIndices is not be deleted before the algorithm starts. usLevel indicates how often the algorithm is repeated.
Definition at line 1402 of file Algorithm.cpp.
References MeshCore::FACET_INDEX_MAX, ResetFacetFlag(), MeshCore::MeshFacetArray::ResetFlag(), SetFacetsFlag(), and MeshCore::MeshFacet::TMP0.
Referenced by CutBorderFacets().
CheckFacets() [1/2]
void MeshAlgorithm::CheckFacets (const Base::ViewProjMethod * pclProj, const Base::Polygon2d & rclPoly, bool bInner, std::vector< FacetIndex > & facets) const
Does the same as the above method unless that it doesn't use a grid.
Definition at line 1260 of file Algorithm.cpp.
References Base::Polygon2d::CalcBoundBox(), Base::BoundBox2d::Contains(), Base::Polygon2d::Contains(), SCL.SimpleDataTypes::f, Base::ViewProjMethod::getComposedProjectionMatrix(), MeshCore::MeshKernel::GetFacets(), MeshCore::MeshKernel::GetPoints(), buildPsets::p, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
CheckFacets() [2/2]
void MeshAlgorithm::CheckFacets (const MeshFacetGrid & rclGrid, const Base::ViewProjMethod * pclProj, const Base::Polygon2d & rclPoly, bool bInner, std::vector< FacetIndex > & facets) const
Projects the determined facets through projection with pclProj into the 2D plane and checks for intersection with the polygon. If bInner is true than all facets with at least one corner inside the polygon get deleted. If bInner is false then all facets with at least one corner outside the polygon get deleted. This algorithm is optimized by using a grid.
Definition at line 1176 of file Algorithm.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, Base::Polygon2d::CalcBoundBox(), Base::BoundBox2d::Contains(), Base::Polygon2d::Contains(), MeshCore::MeshKernel::CountFacets(), MeshCore::MeshGridIterator::GetBoundBox(), Base::ViewProjMethod::getComposedProjectionMatrix(), MeshCore::MeshGridIterator::GetElements(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshFacetIterator::Init(), MeshCore::MeshGridIterator::Init(), Base::BoundBox2d::Intersect(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshGridIterator::More(), MeshCore::MeshFacetIterator::Next(), Base::SequencerLauncher::next(), MeshCore::MeshGridIterator::Next(), MeshCore::MeshFacetIterator::Position(), Base::Vector3< float_type >::Set(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by Mesh::MeshObject::cut(), and MeshGui::ViewProviderMesh::getFacetsFromPolygon().
ConnectLines()
bool MeshAlgorithm::ConnectLines (std::list< std::pair< Base::Vector3f, Base::Vector3f >> & rclLines, std::list< std::vector< Base::Vector3f >> & rclPolylines, float fMinEps) const protected
Helper method to connect the intersection points to polylines.
Definition at line 1573 of file Algorithm.cpp.
References Base::DistanceP2().
Referenced by CutWithPlane().
ConnectPolygons()
bool MeshAlgorithm::ConnectPolygons (std::list< std::vector< Base::Vector3f >> & clPolyList, std::list< std::pair< Base::Vector3f, Base::Vector3f >> & rclLines) const protected
Definition at line 1693 of file Algorithm.cpp.
References Base::Distance().
Referenced by CutWithPlane().
CountBorderEdges()
unsigned long MeshAlgorithm::CountBorderEdges () const
Returns the number of border edges
Definition at line 1386 of file Algorithm.cpp.
References MeshCore::FACET_INDEX_MAX.
CountFacetFlag()
unsigned long MeshAlgorithm::CountFacetFlag (MeshFacet::TFlagType tF) const
Count all facets with the flag tF.
Definition at line 948 of file Algorithm.cpp.
References SCL.SimpleDataTypes::f.
Referenced by Mesh::MeshObject::countSelectedFacets(), ReverseEngineeringGui::SegmentationManual::createSegment(), MeshGui::MeshSelection::deleteSelection(), MeshCore::MeshSegmentAlgorithm::FindSegments(), GetFacetsFlag(), and MeshCore::MeshComponents::SearchForComponents().
CountPointFlag()
unsigned long MeshAlgorithm::CountPointFlag (MeshPoint::TFlagType tF) const
Count all points with the flag tF.
Definition at line 958 of file Algorithm.cpp.
References SCL.SimpleDataTypes::f.
Referenced by Mesh::MeshObject::countSelectedPoints(), and GetPointsFlag().
CutBorderFacets()
void MeshAlgorithm::CutBorderFacets (std::vector< FacetIndex > & raclFacetIndices, unsigned short usLevel = 1) const
Invokes CheckBorderFacets() to get all border facets of raclFacetIndices. Then the content of raclFacetIndices is replaced by all facets that can be deleted.
Note
The mesh structure is not modified by this method. This is in the responsibility of the user.
Definition at line 1366 of file Algorithm.cpp.
References CheckBorderFacets().
CutWithPlane()
bool MeshAlgorithm::CutWithPlane (const Base::Vector3f & clBase, const Base::Vector3f & clNormal, const MeshFacetGrid & rclGrid, std::list< std::vector< Base::Vector3f >> & rclResult, float fMinEps = 1.0e-2F, bool bConnectPolygons = false) const
Cuts the mesh with a plane. The result is a list of polylines.
Definition at line 1519 of file Algorithm.cpp.
References ConnectLines(), ConnectPolygons(), MeshCore::MeshGridIterator::GetBoundBox(), MeshCore::MeshGridIterator::GetElements(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshGridIterator::Init(), MeshCore::MeshGeomFacet::IntersectWithPlane(), Base::BoundBox3< Precision >::IsCutPlane(), MeshCore::MeshGridIterator::More(), and MeshCore::MeshGridIterator::Next().
Referenced by Mesh::MeshObject::crossSections(), and MeshPartGui::MeshCrossSection::section().
Distance()
bool MeshAlgorithm::Distance (const Base::Vector3f & rclPt, FacetIndex ulFacetIdx, float fMaxDistance, float & rfDistance) const
Returns true if the distance from the rclPt to the facet ulFacetIdx is less than fMaxDistance. If this restriction is met rfDistance is set to the actual distance, otherwise false is returned.
Definition at line 1792 of file Algorithm.cpp.
References MeshCore::MeshGeomFacet::DistanceToPoint(), and MeshCore::MeshKernel::GetFacet().
Referenced by MeshCore::MeshFacetGrid::SearchNearestFromPoint().
FillupHole()
bool MeshAlgorithm::FillupHole (const std::vector< PointIndex > & boundary, AbstractPolygonTriangulator & cTria, MeshFacetArray & rFaces, MeshPointArray & rPoints, int level, const MeshRefPointToFacets * pP2FStructure = nullptr) const
Fills up the single boundary if it is a hole with high quality triangles and a maximum area of fMaxArea. The triangulation information is stored in rFaces and rPoints. To speed up the calculations the optional parameter pStructure can be specified that holds a facet-to-points structure of the underlying mesh. If the boundary is not a hole or the algorithm failed false is returned, otherwise true.
Note
boundary contains the point indices of the mesh data structure. The first and last index must therefore be equal.
rPoints contains the geometric points of the triangulation. The number of points can be the same as or exceed the number of boundary indices but it cannot be lower.
If the number of geometric points exceeds the number of boundary indices then the triangulation algorithm has introduced new points which are added to the end of rPoints.
Definition at line 666 of file Algorithm.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::MeshFacet::_aulPoints, MeshCore::TriangulationVerifier::Accept(), MeshCore::AbstractPolygonTriangulator::AddedPoints(), Base::Console(), MeshCore::AbstractPolygonTriangulator::Discard(), MeshCore::MeshFacet::FlipNormal(), MeshCore::MeshKernel::GetFacet(), MeshCore::AbstractPolygonTriangulator::GetFacets(), MeshCore::MeshGeomFacet::GetNormal(), MeshCore::AbstractPolygonTriangulator::GetPolygon(), MeshCore::AbstractPolygonTriangulator::GetTriangle(), MeshCore::AbstractPolygonTriangulator::GetVerifier(), SplineSurface::i, MeshCore::MeshFacet::IsEqual(), level(), Base::ConsoleSingleton::Log(), MeshCore::TriangulationVerifier::MustFlip(), MeshCore::AbstractPolygonTriangulator::NeedsReindexing(), MeshCore::MeshRefPointToFacets::NeighbourPoints(), MeshCore::AbstractPolygonTriangulator::PostProcessing(), MeshCore::AbstractPolygonTriangulator::SetIndices(), MeshCore::AbstractPolygonTriangulator::SetPolygon(), MeshCore::MeshFacet::Side(), and MeshCore::AbstractPolygonTriangulator::TriangulatePolygon().
Referenced by MeshGui::ViewProviderMesh::fillHole(), and MeshCore::MeshTopoAlgorithm::FillupHoles().
FirstFacetToVertex()
bool MeshAlgorithm::FirstFacetToVertex (const Base::Vector3f & rPt, float fMaxDistance, const MeshFacetGrid & rGrid, FacetIndex & uIndex) const
Searches for the first facet of the grid element (rGrid) in that the point rPt lies into which is a distance not higher than fMaxDistance. Of no such facet is found uIndex is undefined and false is returned, otherwise true.
Note
If the point rPt is outside of the grid rclGrid nothing is done.
Definition at line 244 of file Algorithm.cpp.
References MeshCore::MeshGrid::GetElements(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshGeomFacet::IsPointOfFace(), MeshCore::MeshGeomFacet::NearestEdgeToPoint(), and MeshCore::MeshGeomFacet::ProjectPointToPlane().
GetAverageEdgeLength()
float MeshAlgorithm::GetAverageEdgeLength () const
Calculates the average length of edges.
Definition at line 282 of file Algorithm.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::MeshKernel::CountFacets(), Base::Distance(), SplineSurface::i, MeshCore::MeshFacetIterator::Init(), MeshCore::MeshFacetIterator::More(), and MeshCore::MeshFacetIterator::Next().
Referenced by MeshPartGui::CurveOnMeshHandler::Private::createGrid(), MeshPart::MeshProjection::findSectionParameters(), Inspection::InspectNominalFastMesh::InspectNominalFastMesh(), Inspection::InspectNominalMesh::InspectNominalMesh(), MeshGui::SoFCMeshPickNode::notify(), MeshPart::MeshProjection::projectOnMesh(), MeshPart::MeshProjection::projectParallelToMesh(), and MeshPart::MeshProjection::projectToMesh().
GetBorderPoints()
void MeshAlgorithm::GetBorderPoints (const std::vector< FacetIndex > & raclFacetIndices, std::set< PointIndex > & raclResultPointsIndices) const
Determines all border points as indices of the facets in raclFacetIndices. The points are unsorted.
Definition at line 1429 of file Algorithm.cpp.
References MeshCore::MeshFacet::_aulNeighbours, MeshCore::MeshFacet::_aulPoints, MeshCore::FACET_INDEX_MAX, SplineSurface::i, ResetFacetFlag(), SetFacetsFlag(), and MeshCore::MeshFacet::TMP0.
Referenced by MeshGui::MeshSelection::deleteSelectionBorder().
GetFacetBorder()
void MeshAlgorithm::GetFacetBorder (FacetIndex uFacet, std::list< PointIndex > & rBorder) const
Returns the boundary of the mesh to the facet uFacet. If this facet does not have an open edge the returned boundary is empty.
Definition at line 472 of file Algorithm.cpp.
References MeshCore::FACET_INDEX_MAX, SplineSurface::i, and SplitBoundaryFromOpenEdges().
Referenced by MeshGui::ViewProviderMesh::fillHole().
GetFacetBorders() [1/2]
void MeshAlgorithm::GetFacetBorders (const std::vector< FacetIndex > & raulInd, std::list< std::vector< Base::Vector3f >> & rclBorders) const
Returns all boundaries of a subset the mesh defined by raulInd.
Definition at line 355 of file Algorithm.cpp.
Referenced by ReverseEngineeringGui::Segmentation::accept(), and GetMeshBorders().
GetFacetBorders() [2/2]
void MeshAlgorithm::GetFacetBorders (const std::vector< FacetIndex > & raulInd, std::list< std::vector< PointIndex >> & rclBorders, bool ignoreOrientation = false) const
Returns all boundaries of a subset the mesh defined by raulInd. This method does basically the same as above unless that it returns the point indices of the boundaries. If ignoreOrientation is false (the default) we may get a broken boundary curve if the mesh has facets with wrong orientation. However, if ignoreOrientation is true we may get a boundary curve with wrong orientation even if the mesh is topologically correct. You should let the default value unless you exactly know what you do.
Definition at line 374 of file Algorithm.cpp.
References MeshCore::MeshFacet::_aulNeighbours, MeshCore::FACET_INDEX_MAX, MeshCore::MeshFacet::GetEdge(), SplineSurface::i, ResetFacetFlag(), MeshCore::MeshFacetArray::SetFlag(), and MeshCore::MeshFacet::VISIT.
GetFacetsBorders()
void MeshAlgorithm::GetFacetsBorders (const std::vector< FacetIndex > & uFacets, std::list< std::vector< PointIndex >> & rBorders) const
Returns the boundary of the mesh to the facets uFacest. If none of the facets have an open edge the returned boundary is empty.
Definition at line 505 of file Algorithm.cpp.
References MeshCore::MeshFacet::_aulNeighbours, MeshCore::FACET_INDEX_MAX, MeshCore::MeshFacet::GetEdge(), SplineSurface::i, ResetFacetFlag(), ResetPointFlag(), SetFacetsFlag(), MeshCore::MeshPointArray::SetFlag(), SplitBoundaryFromOpenEdges(), MeshCore::MeshPoint::TMP0, and MeshCore::MeshFacet::TMP0.
GetFacetsFlag()
void MeshAlgorithm::GetFacetsFlag (std::vector< FacetIndex > & raulInds, MeshFacet::TFlagType tF) const
Gets all facets in raulInds with the flag tF.
Definition at line 888 of file Algorithm.cpp.
References CountFacetFlag().
Referenced by ReverseEngineeringGui::Segmentation::accept(), ReverseEngineeringGui::SegmentationManual::createSegment(), Mesh::MeshObject::deleteSelectedFacets(), MeshGui::MeshSelection::deleteSelectionBorder(), and Mesh::MeshObject::getFacetsFromSelection().
GetFacetsFromPlane()
void MeshAlgorithm::GetFacetsFromPlane (const MeshFacetGrid & rclGrid, const Base::Vector3f & clNormal, float dist, const Base::Vector3f & rclLeft, const Base::Vector3f & rclRight, std::vector< FacetIndex > & rclRes) const
Gets all facets that cut the plane (N,d) and that lie between the two points left and right. The plane is defined by it normalized normal and the signed distance to the origin.
Definition at line 1729 of file Algorithm.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, Base::Vector3< float_type >::DistanceToPlane(), MeshCore::MeshGridIterator::GetBoundBox(), MeshCore::MeshGridIterator::GetElements(), MeshCore::MeshKernel::GetFacet(), SplineSurface::i, MeshCore::MeshGridIterator::Init(), MeshCore::MeshGeomFacet::IntersectWithPlane(), Base::BoundBox3< Precision >::IsCutPlane(), MeshCore::MeshGridIterator::More(), MeshCore::MeshGridIterator::Next(), and Base::Vector3< float_type >::Normalize().
GetFacetsFromToolMesh() [1/2]
void MeshAlgorithm::GetFacetsFromToolMesh (const MeshKernel & rToolMesh, const Base::Vector3f & rcDir, const MeshFacetGrid & rGrid, std::vector< FacetIndex > & raclCutted) const
Does basically the same as method above except it uses a mesh grid to speed up the computation.
Definition at line 1015 of file Algorithm.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, Base::Vector3< float_type >::epsilon(), MeshCore::MeshGeomFacet::Foraminate(), MeshCore::MeshKernel::GetBoundBox(), MeshCore::MeshGridIterator::GetBoundBox(), MeshCore::MeshGridIterator::GetElements(), MeshCore::MeshFacetIterator::Init(), MeshCore::MeshGridIterator::Init(), MeshCore::MeshGeomFacet::IsPointOfFace(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshGridIterator::More(), MeshCore::MeshFacetIterator::Next(), MeshCore::MeshGridIterator::Next(), Base::SequencerLauncher::next(), MeshCore::MeshFacetIterator::Position(), MeshCore::MeshFacetIterator::Set(), and Surround().
GetFacetsFromToolMesh() [2/2]
void MeshAlgorithm::GetFacetsFromToolMesh (const MeshKernel & rToolMesh, const Base::Vector3f & rcDir, std::vector< FacetIndex > & raclCutted) const
Returns the indices of all facets that have at least one point that lies inside the tool mesh. The direction dir is used to try to foraminate the facets of the tool mesh and counts the number of foraminated facets. If this number is odd the considered point lies inside otherwise outside.
Note
The tool mesh must be a valid solid.
It's not tested if rToolMesh is a valid solid. In case it is not the result is undefined.
Definition at line 968 of file Algorithm.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::MeshKernel::CountFacets(), Base::Vector3< float_type >::epsilon(), MeshCore::MeshGeomFacet::Foraminate(), MeshCore::MeshKernel::GetBoundBox(), MeshCore::MeshFacetIterator::Init(), MeshCore::MeshGeomFacet::IsPointOfFace(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), Base::SequencerLauncher::next(), and MeshCore::MeshFacetIterator::Position().
Referenced by Mesh::SegmentByMesh::execute(), MeshGui::ViewProviderMesh::segmentMesh(), and MeshGui::ViewProviderMesh::splitMesh().
GetGravityPoint()
Base::Vector3f MeshAlgorithm::GetGravityPoint () const
Calculates the gravity point of the mesh.
Definition at line 322 of file Algorithm.cpp.
References exportCSG::center(), MeshCore::MeshKernel::CountPoints(), MeshCore::MeshPointIterator::Init(), MeshCore::MeshPointIterator::More(), and MeshCore::MeshPointIterator::Next().
Referenced by Mesh::MeshObject::getCenterOfGravity().
GetMaximumEdgeLength()
float MeshAlgorithm::GetMaximumEdgeLength () const
Calculates the maximum length of edges.
Definition at line 309 of file Algorithm.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, Base::Distance(), SplineSurface::i, MeshCore::MeshFacetIterator::Init(), KDL::max(), MeshCore::MeshFacetIterator::More(), and MeshCore::MeshFacetIterator::Next().
GetMeshBorders() [1/2]
void MeshAlgorithm::GetMeshBorders (std::list< std::vector< Base::Vector3f >> & rclBorders) const
Returns all boundaries of the mesh.
Definition at line 333 of file Algorithm.cpp.
References MeshCore::MeshKernel::CountFacets(), and GetFacetBorders().
Referenced by MeshCore::MeshTopoAlgorithm::FillupHoles(), and MeshCore::MeshTopoAlgorithm::FindHoles().
GetMeshBorders() [2/2]
void MeshAlgorithm::GetMeshBorders (std::list< std::vector< PointIndex >> & rclBorders) const
Returns all boundaries of the mesh. This method does basically the same as above unless that it returns the point indices of the boundaries.
Definition at line 344 of file Algorithm.cpp.
References MeshCore::MeshKernel::CountFacets(), and GetFacetBorders().
GetMinimumEdgeLength()
float MeshAlgorithm::GetMinimumEdgeLength () const
Calculates the minimum length of edges.
Definition at line 296 of file Algorithm.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, Base::Distance(), FLOAT_MAX, SplineSurface::i, MeshCore::MeshFacetIterator::Init(), KDL::min(), MeshCore::MeshFacetIterator::More(), and MeshCore::MeshFacetIterator::Next().
GetPointsFlag()
void MeshAlgorithm::GetPointsFlag (std::vector< PointIndex > & raulInds, MeshPoint::TFlagType tF) const
Gets all points in raulInds with the flag tF.
Definition at line 900 of file Algorithm.cpp.
References CountPointFlag().
Referenced by Mesh::MeshObject::deleteSelectedPoints(), and Mesh::MeshObject::getPointsFromSelection().
IsVertexVisible()
bool MeshAlgorithm::IsVertexVisible (const Base::Vector3f & rcVertex, const Base::Vector3f & rcView, const MeshFacetGrid & rclGrid) const
Checks from the viewpoint rcView if the vertex rcVertex is visible or it is hidden by a facet. If the vertex is visible true is returned, false otherwise.
Definition at line 46 of file Algorithm.cpp.
References Base::Distance(), Base::Vector3< float_type >::Length(), and NearestFacetOnRay().
Referenced by MeshGui::Vertex::visible().
NearestFacetOnRay() [1/5]
bool MeshAlgorithm::NearestFacetOnRay (const Base::Vector3f & rclPt, const Base::Vector3f & rclDir, Base::Vector3f & rclRes, FacetIndex & rulFacet) const
Searches for the nearest facet to the ray defined by (rclPt, rclDir). The point rclRes holds the intersection point with the ray and the nearest facet with index rulFacet.
Note
This method tests all facets so it should only be used occasionally.
Definition at line 72 of file Algorithm.cpp.
References MeshCore::Math< Prec >::PI.
Referenced by IsVertexVisible(), Mesh::MeshObject::nearestFacetOnRay(), MeshGui::SoFCMeshPickNode::pick(), MeshPart::MeshProjection::projectOnMesh(), and MeshPart::MeshProjection::projectParallelToMesh().
NearestFacetOnRay() [2/5]
bool MeshAlgorithm::NearestFacetOnRay (const Base::Vector3f & rclPt, const Base::Vector3f & rclDir, const MeshFacetGrid & rclGrid, Base::Vector3f & rclRes, FacetIndex & rulFacet) const
Searches for the nearest facet to the ray defined by (rclPt, rclDir). The point rclRes holds the intersection point with the ray and the nearest facet with index rulFacet.
Note
This method is optimized by using a grid. So this method can be used for a lot of tests.
Definition at line 119 of file Algorithm.cpp.
References MeshCore::MeshGridIterator::InitOnRay(), MeshCore::MeshGridIterator::NextOnRay(), and RayNearestField().
NearestFacetOnRay() [3/5]
bool MeshAlgorithm::NearestFacetOnRay (const Base::Vector3f & rclPt, const Base::Vector3f & rclDir, const std::vector< FacetIndex > & raulFacets, Base::Vector3f & rclRes, FacetIndex & rulFacet) const
Searches for the nearest facet to the ray defined by (rclPt, rclDir). The point rclRes holds the intersection point with the ray and the nearest facet with index rulFacet.
Note
This method tests all facets taken from raulFacets instead of the attached mesh. So the caller must ensure that the indices are valid facets.
Definition at line 173 of file Algorithm.cpp.
References MeshCore::MeshGeomFacet::Foraminate(), MeshCore::MeshKernel::GetFacet(), and FreeCADInit::Length.
NearestFacetOnRay() [4/5]
bool MeshAlgorithm::NearestFacetOnRay (const Base::Vector3f & rclPt, const Base::Vector3f & rclDir, float fMaxAngle, Base::Vector3f & rclRes, FacetIndex & rulFacet) const
Searches for the nearest facet to the ray defined by (rclPt, rclDir). The point rclRes holds the intersection point with the ray and the nearest facet with index rulFacet. The angle between the ray and the normal of the triangle must be less than or equal to fMaxAngle.
Note
This method tests all facets so it should only be used occasionally.
Definition at line 80 of file Algorithm.cpp.
References MeshCore::MeshGeomFacet::Foraminate(), MeshCore::MeshFacetIterator::Init(), FreeCADInit::Length, MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), and MeshCore::MeshFacetIterator::Position().
NearestFacetOnRay() [5/5]
bool MeshAlgorithm::NearestFacetOnRay (const Base::Vector3f & rclPt, const Base::Vector3f & rclDir, float fMaxSearchArea, const MeshFacetGrid & rclGrid, Base::Vector3f & rclRes, FacetIndex & rulFacet) const
Searches for the nearest facet to the ray defined by (rclPt, rclDir). The point rclRes holds the intersection point with the ray and the nearest facet with index rulFacet. More a search radius around the ray of fMaxSearchArea is defined.
Note
This method is optimized by using a grid. So this method can be used for a lot of tests.
Definition at line 145 of file Algorithm.cpp.
References MeshCore::MeshGridIterator::InitOnRay(), MeshCore::MeshGridIterator::NextOnRay(), and RayNearestField().
NearestPointFromPoint() [1/3]
bool MeshAlgorithm::NearestPointFromPoint (const Base::Vector3f & rclPt, const MeshFacetGrid & rclGrid, FacetIndex & rclResFacetIndex, Base::Vector3f & rclResPoint) const
Definition at line 1482 of file Algorithm.cpp.
References MeshCore::MeshGeomFacet::DistanceToPoint(), MeshCore::FACET_INDEX_MAX, MeshCore::MeshKernel::GetFacet(), and MeshCore::MeshFacetGrid::SearchNearestFromPoint().
NearestPointFromPoint() [2/3]
bool MeshAlgorithm::NearestPointFromPoint (const Base::Vector3f & rclPt, const MeshFacetGrid & rclGrid, float fMaxSearchArea, FacetIndex & rclResFacetIndex, Base::Vector3f & rclResPoint) const
Definition at line 1500 of file Algorithm.cpp.
References MeshCore::MeshGeomFacet::DistanceToPoint(), MeshCore::FACET_INDEX_MAX, MeshCore::MeshKernel::GetFacet(), and MeshCore::MeshFacetGrid::SearchNearestFromPoint().
NearestPointFromPoint() [3/3]
bool MeshAlgorithm::NearestPointFromPoint (const Base::Vector3f & rclPt, FacetIndex & rclResFacetIndex, Base::Vector3f & rclResPoint) const
Projects a point directly to the mesh (means nearest facet), the result is the facet index and the foraminate point, use second version with grid for more performance.
Definition at line 1455 of file Algorithm.cpp.
References MeshCore::MeshKernel::CountFacets(), MeshCore::MeshGeomFacet::DistanceToPoint(), MeshCore::FACET_INDEX_MAX, FLOAT_MAX, MeshCore::MeshKernel::GetFacet(), MeshCore::MeshFacetIterator::Init(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), and MeshCore::MeshFacetIterator::Position().
PointsFromFacetsIndices()
void MeshAlgorithm::PointsFromFacetsIndices (const std::vector< FacetIndex > & rvecIndices, std::vector< Base::Vector3f > & rvecPoints) const
Returns all geometric points from the facets in rvecIndices.
Definition at line 1772 of file Algorithm.cpp.
RayNearestField()
bool MeshAlgorithm::RayNearestField (const Base::Vector3f & rclPt, const Base::Vector3f & rclDir, const std::vector< FacetIndex > & raulFacets, Base::Vector3f & rclRes, FacetIndex & rulFacet, float fMaxAngle = Mathf::PI) const protected
Searches the nearest facet in raulFacets to the ray (rclPt, rclDir).
Definition at line 209 of file Algorithm.cpp.
References MeshCore::MeshGeomFacet::Foraminate(), MeshCore::MeshKernel::GetFacet(), and FreeCADInit::Length.
Referenced by NearestFacetOnRay().
ResetFacetFlag()
void MeshAlgorithm::ResetFacetFlag (MeshFacet::TFlagType tF) const
Resets of all facets the flag tF.
Definition at line 938 of file Algorithm.cpp.
References MeshCore::MeshFacetArray::ResetFlag().
Referenced by CheckBorderFacets(), Mesh::MeshObject::clearFacetSelection(), MeshGui::MeshSelection::deleteSelectionBorder(), MeshGui::ViewProviderMesh::deselectComponent(), MeshCore::MeshSegmentAlgorithm::FindSegments(), GetBorderPoints(), GetFacetBorders(), GetFacetsBorders(), MeshCore::MeshEvalOrientation::GetIndices(), MeshCore::MeshSearchNeighbours::MeshSearchNeighbours(), MeshCore::MeshSearchNeighbours::Reinit(), MeshGui::ViewProviderMesh::selectComponent(), and Mesh::MeshObject::splitEdges().
ResetFacetsFlag()
void MeshAlgorithm::ResetFacetsFlag (const std::vector< FacetIndex > & raulInds, MeshFacet::TFlagType tF) const
Resets from all facets in raulInds the flag tF.
Definition at line 912 of file Algorithm.cpp.
References MeshCore::MeshFacetArray::ResetFlag().
Referenced by ReverseEngineeringGui::Segmentation::accept(), Mesh::SegmentByMesh::execute(), MeshCore::MeshSegmentAlgorithm::FindSegments(), MeshCore::MeshSearchNeighbourFacetsVisitor::GetAndReset(), MeshCore::MeshEvalOrientation::GetIndices(), Mesh::MeshObject::removeFacetsFromSelection(), and MeshCore::MeshComponents::SearchForComponents().
ResetPointFlag()
void MeshAlgorithm::ResetPointFlag (MeshPoint::TFlagType tF) const
Resets of all points the flag tF.
Definition at line 943 of file Algorithm.cpp.
References MeshCore::MeshPointArray::ResetFlag().
Referenced by Mesh::MeshObject::clearPointSelection(), MeshGui::MeshSelection::deleteSelectionBorder(), GetFacetsBorders(), MeshCore::MeshSearchNeighbours::MeshSearchNeighbours(), and MeshCore::MeshSearchNeighbours::Reinit().
ResetPointsFlag()
void MeshAlgorithm::ResetPointsFlag (const std::vector< PointIndex > & raulInds, MeshPoint::TFlagType tF) const
Resets from all points in raulInds the flag tF.
Definition at line 920 of file Algorithm.cpp.
References MeshCore::MeshPointArray::ResetFlag().
Referenced by Mesh::MeshObject::removePointsFromSelection().
SearchFacetsFromPolyline()
void MeshAlgorithm::SearchFacetsFromPolyline (const std::vector< Base::Vector3f > & rclPolyline, float fRadius, const MeshFacetGrid & rclGrid, std::vector< FacetIndex > & rclResultFacetsIndices) const
Searches for all facets that intersect the "search tube" with radius r around the polyline.
Definition at line 1333 of file Algorithm.cpp.
References MeshCore::MeshGeomFacet::DistanceToLineSegment(), MeshCore::MeshKernel::GetFacet(), SplineSurface::i, MeshCore::MeshGrid::Inside(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by MeshPart::MeshProjection::projectEdgeToEdge().
SetFacetFlag()
void MeshAlgorithm::SetFacetFlag (MeshFacet::TFlagType tF) const
Sets to all facets the flag tF.
Definition at line 928 of file Algorithm.cpp.
References MeshCore::MeshFacetArray::SetFlag().
Referenced by ReverseEngineeringGui::Segmentation::accept(), Mesh::SegmentByMesh::execute(), and MeshCore::MeshComponents::SearchForComponents().
SetFacetsFlag()
void MeshAlgorithm::SetFacetsFlag (const std::vector< FacetIndex > & raulInds, MeshFacet::TFlagType tF) const
Sets to all facets in raulInds the flag tF.
Definition at line 872 of file Algorithm.cpp.
References MeshCore::MeshFacetArray::SetFlag().
Referenced by Mesh::MeshObject::addFacetsToSelection(), CheckBorderFacets(), MeshGui::MeshSelection::deleteSelectionBorder(), GetBorderPoints(), GetFacetsBorders(), and MeshCore::MeshEvalOrientation::GetIndices().
SetFacetsProperty()
void MeshAlgorithm::SetFacetsProperty (const std::vector< FacetIndex > & raulInds, const std::vector< unsigned long > & raulProps) const
Sets to all facets in raulInds the properties in raulProps.
Note
Both arrays must have the same size.
Definition at line 859 of file Algorithm.cpp.
References SplineSurface::i, and MeshCore::MeshFacetArray::SetProperty().
SetPointFlag()
void MeshAlgorithm::SetPointFlag (MeshPoint::TFlagType tF) const
Sets to all points the flag tF.
Definition at line 933 of file Algorithm.cpp.
References MeshCore::MeshPointArray::SetFlag().
SetPointsFlag()
void MeshAlgorithm::SetPointsFlag (const std::vector< PointIndex > & raulInds, MeshPoint::TFlagType tF) const
Sets to all points in raulInds the flag tF.
Definition at line 880 of file Algorithm.cpp.
References MeshCore::MeshPointArray::SetFlag().
Referenced by Mesh::MeshObject::addPointsToSelection(), and MeshGui::MeshSelection::deleteSelectionBorder().
SplitBoundaryFromOpenEdges()
void MeshAlgorithm::SplitBoundaryFromOpenEdges (std::list< std::pair< PointIndex, PointIndex >> & openEdges, std::list< PointIndex > & boundary) const protected
From the given openEdges a boundary is split and added to boundary.
Definition at line 562 of file Algorithm.cpp.
Referenced by GetFacetBorder(), and GetFacetsBorders().
SplitBoundaryLoops() [1/2]
void MeshAlgorithm::SplitBoundaryLoops (const std::vector< PointIndex > & rBound, std::list< std::vector< PointIndex >> & aBorders) protected
Splits the boundary rBound in several loops and append this loops to the list of borders.
Definition at line 641 of file Algorithm.cpp.
References AttachmentEditor.TaskAttachmentEditor::deg.
SplitBoundaryLoops() [2/2]
void MeshAlgorithm::SplitBoundaryLoops (std::list< std::vector< PointIndex >> & aBorders)
Boundaries that consist of several loops must be split in several independent boundaries to perform e.g. a polygon triangulation algorithm on them.
Definition at line 605 of file Algorithm.cpp.
References MeshCore::FACET_INDEX_MAX, and SplineSurface::i.
Referenced by MeshGui::ViewProviderMesh::fillHole(), and MeshCore::MeshTopoAlgorithm::FillupHoles().
SubSampleAllPoints()
void MeshAlgorithm::SubSampleAllPoints (std::vector< Base::Vector3f > & rclPoints) const
Returns only the points of the mesh without actually sampling the data.
Definition at line 1314 of file Algorithm.cpp.
References MeshCore::MeshPointIterator::Init(), MeshCore::MeshPointIterator::More(), and MeshCore::MeshPointIterator::Next().
SubSampleByCount()
void MeshAlgorithm::SubSampleByCount (unsigned long ulCtPoints, std::vector< Base::Vector3f > & rclPoints) const
Subsamples the mesh to produce around ulCtPoints. ulCtPoints should be greater than 5 * number of facets.
Definition at line 1326 of file Algorithm.cpp.
References KDL::sqrt(), SubSampleByDist(), and Surface().
SubSampleByDist()
void MeshAlgorithm::SubSampleByDist (float fDist, std::vector< Base::Vector3f > & rclPoints) const
Subsamples the mesh with point distance fDist and stores the points in rclPoints.
Definition at line 1301 of file Algorithm.cpp.
References MeshCore::MeshGeomFacet::GetGravityPoint(), MeshCore::MeshFacetIterator::Init(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), and MeshCore::MeshGeomFacet::SubSample().
Referenced by SubSampleByCount().
Surface()
float MeshAlgorithm::Surface () const
Computes the surface of the mesh.
Definition at line 1289 of file Algorithm.cpp.
References MeshCore::MeshGeomFacet::Area(), MeshCore::MeshFacetIterator::Init(), MeshCore::MeshFacetIterator::More(), and MeshCore::MeshFacetIterator::Next().
Referenced by SubSampleByCount().
Surround()
int MeshAlgorithm::Surround (const Base::BoundBox3f & rBox, const Base::Vector3f & rcDir)
Checks whether the bounding box rBox is surrounded by the attached mesh which must be a solid. The direction rcDir is used to try to foraminate the facets of the tool mesh and counts the number of foraminated facets. 1 is returned if the box is completely inside the mesh 0 is returned if the box is partially inside (i.e. intersects) the mesh -1 is returned if the box is completely outside the mesh. This could also mean that the mesh is surrounded by rBox.
Definition at line 1107 of file Algorithm.cpp.
References Base::Vector3< float_type >::epsilon(), MeshCore::MeshGeomFacet::Foraminate(), MeshCore::MeshKernel::GetBoundBox(), MeshCore::MeshFacetIterator::Init(), MeshCore::MeshGeomFacet::IntersectWithFacet(), MeshCore::MeshGeomFacet::IsPointOfFace(), Base::BoundBox3< Precision >::MaxX, Base::BoundBox3< Precision >::MaxY, Base::BoundBox3< Precision >::MaxZ, Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, Base::BoundBox3< Precision >::MinZ, MeshCore::MeshFacetIterator::More(), and MeshCore::MeshFacetIterator::Next().
Referenced by GetFacetsFromToolMesh().
The documentation for this class was generated from the following files:
Algorithm.h
Algorithm.cpp