FreeCAD: CArea Class Reference
CArea Class Reference
#include <Area.h>
Public Member Functions
void append (const CCurve &curve)
void move (CCurve &&curve)
void Subtract (const CArea &a2)
void Intersect (const CArea &a2)
void Union (const CArea &a2)
void Xor (const CArea &a2)
void Offset (double inwards_value)
void OffsetWithClipper (double offset, ClipperLib::JoinType joinType=ClipperLib::jtRound, ClipperLib::EndType endType=ClipperLib::etOpenRound, double miterLimit=5.0, double roundPrecision=0.0)
void Thicken (double value)
void FitArcs ()
unsigned int num_curves ()
Point NearestPoint (const Point &p) const
void GetBox (CBox2D &box)
void Reorder ()
void MakePocketToolpath (std::list< CCurve > &toolpath, const CAreaPocketParams &params) const
void SplitAndMakePocketToolpath (std::list< CCurve > &toolpath, const CAreaPocketParams &params) const
void MakeOnePocketCurve (std::list< CCurve > &curve_list, const CAreaPocketParams &params) const
void Split (std::list< CArea > &m_areas) const
double GetArea (bool always_add=false) const
void SpanIntersections (const Span &span, std::list< Point > &pts) const
void CurveIntersections (const CCurve &curve, std::list< Point > &pts) const
void InsideCurves (const CCurve &curve, std::list< CCurve > &curves_inside) const
void ChangeStartToNearest (const Point *pstart=NULL, double min_dist=1.0)
void PopulateClipper (ClipperLib::Clipper &c, ClipperLib::PolyType type) const
void Clip (ClipperLib::ClipType op, const CArea *a, ClipperLib::PolyFillType subjFillType=ClipperLib::pftEvenOdd, ClipperLib::PolyFillType clipFillType=ClipperLib::pftEvenOdd)
Static Public Member Functions
static CArea UniteCurves (std::list< CCurve > &curves)
static bool HolesLinked ()
static double get_tolerance ()
static void set_tolerance (double tolerance)
static bool get_fit_arcs ()
static void set_fit_arcs (bool fit_arcs)
static bool get_clipper_simple ()
static void set_clipper_simple (bool clipper_simple)
static double get_clipper_clean_distance ()
static void set_clipper_clean_distance (double clipper_clean_distance)
static double get_accuracy ()
static void set_accuracy (double accuracy)
static double get_units ()
static void set_units (double units)
static short get_min_arc_points ()
static void set_min_arc_points (short min_arc_points)
static short get_max_arc_points ()
static void set_max_arc_points (short max_arc_points)
static double get_clipper_scale ()
static void set_clipper_scale (double clipper_scale)
Public Attributes
std::list< CCurve > m_curves
Static Public Attributes
static double m_accuracy = 0.01
static double m_units = 1.0
static bool m_clipper_simple = false
static double m_clipper_clean_distance = 0.0
static bool m_fit_arcs = true
static int m_min_arc_points = 4
static int m_max_arc_points = 100
static double m_processing_done = 0.0
static double m_single_area_processing_length = 0.0
static double m_after_MakeOffsets_length = 0.0
static double m_MakeOffsets_increment = 0.0
static double m_split_processing_length = 0.0
static bool m_set_processing_length_in_split = false
static bool m_please_abort = false
static double m_clipper_scale = 10000.0
Detailed Description
Definition at line 46 of file libarea/Area.h.
Member Function Documentation
append()
void CArea::append (const CCurve & curve)
Definition at line 57 of file libarea/Area.cpp.
Referenced by BOOST_PYTHON_MODULE(), init_pyarea(), and ThickLine::ThickLine().
ChangeStartToNearest()
void CArea::ChangeStartToNearest (const Point * pstart = NULL, double min_dist = 1.0)
Definition at line 91 of file libarea/Area.cpp.
References Point::dist(), DraftVecUtils::dist(), CCurve::IsClosed(), m_curves, CCurve::m_vertices, CCurve::NearestPoint(), buildPsets::p, updateLeaderLines::point, and Point::tolerance.
Clip()
void CArea::Clip (ClipperLib::ClipType op, const CArea * a, ClipperLib::PolyFillType subjFillType = ClipperLib::pftEvenOdd, ClipperLib::PolyFillType clipFillType = ClipperLib::pftEvenOdd)
Definition at line 539 of file AreaClipper.cpp.
References a, SCL.SimpleDataTypes::c, ClipperLib::ClosedPathsFromPolyTree(), m_clipper_simple, ClipperLib::OpenPathsFromPolyTree(), SetFromResult(), and TPolyPolygon.
CurveIntersections()
void CArea::CurveIntersections (const CCurve & curve, std::list< Point > & pts) const
Definition at line 930 of file libarea/Area.cpp.
References CCurve::GetSpans(), and SpanIntersections().
Referenced by InsideCurves().
FitArcs()
void CArea::FitArcs ()
Definition at line 67 of file libarea/Area.cpp.
References CCurve::FitArcs(), and m_curves.
Referenced by BOOST_PYTHON_MODULE(), and init_pyarea().
get_accuracy()
double CArea::get_accuracy () static
Definition at line 51 of file libarea/Area.cpp.
get_clipper_clean_distance()
double CArea::get_clipper_clean_distance () static
Definition at line 50 of file libarea/Area.cpp.
get_clipper_scale()
double CArea::get_clipper_scale () static
Definition at line 55 of file libarea/Area.cpp.
get_clipper_simple()
bool CArea::get_clipper_simple () static
Definition at line 49 of file libarea/Area.cpp.
get_fit_arcs()
bool CArea::get_fit_arcs () static
Definition at line 48 of file libarea/Area.cpp.
get_max_arc_points()
short CArea::get_max_arc_points () static
Definition at line 54 of file libarea/Area.cpp.
get_min_arc_points()
short CArea::get_min_arc_points () static
Definition at line 53 of file libarea/Area.cpp.
get_tolerance()
double CArea::get_tolerance () static
Definition at line 47 of file libarea/Area.cpp.
get_units()
double CArea::get_units () static
Definition at line 52 of file libarea/Area.cpp.
Referenced by get_units(), and print_curve().
GetArea()
double CArea::GetArea (bool always_add = false) const
Definition at line 825 of file libarea/Area.cpp.
References a, CCurve::GetArea(), and m_curves.
Referenced by MakeOnePocketCurve().
GetBox()
void CArea::GetBox (CBox2D & box)
Definition at line 168 of file libarea/Area.cpp.
References MengerSponge::box, CCurve::GetBox(), and m_curves.
Referenced by BOOST_PYTHON_MODULE(), and init_pyarea().
HolesLinked()
bool CArea::HolesLinked () static
Definition at line 12 of file AreaClipper.cpp.
Referenced by holes_linked(), recur(), and Split().
InsideCurves()
void CArea::InsideCurves (const CCurve & curve, std::list< CCurve > & curves_inside) const
Definition at line 967 of file libarea/Area.cpp.
References CurveIntersections(), CCurve::ExtractSeparateCurves(), IsInside(), length(), Idf::mid_point(), CCurve::Perim(), and CCurve::PerimToPoint().
Intersect()
void CArea::Intersect (const CArea & a2)
Definition at line 444 of file AreaClipper.cpp.
References NavigationIndicatorGui::a2, SCL.SimpleDataTypes::c, m_clipper_simple, MakePolyPoly(), SetFromResult(), and TPolyPolygon.
Referenced by BOOST_PYTHON_MODULE(), GetOverlapType(), and init_pyarea().
MakeOnePocketCurve()
void CArea::MakeOnePocketCurve (std::list< CCurve > & curve_list, const CAreaPocketParams & params) const
Definition at line 520 of file AreaPocket.cpp.
References SCL.SimpleDataTypes::c, GetArea(), GetCurveItem::GetCurve(), CurveTree::inners, m_after_MakeOffsets_length, m_curves, m_MakeOffsets_increment, m_please_abort, m_processing_done, m_single_area_processing_length, CCurve::m_vertices, CurveTree::MakeOffsets(), MarkOverlappingOffsetIslands(), Offset(), CurveTree::offset_islands, nativeifc.ifc_observer::params, pocket_params, recur(), KDL::sqrt(), and GetCurveItem::to_do_list.
MakePocketToolpath()
void CArea::MakePocketToolpath (std::list< CCurve > & toolpath, const CAreaPocketParams & params) const
Definition at line 634 of file libarea/Area.cpp.
References NavigationIndicatorGui::a2, CCurve::append(), KDL::cos(), cos_angle_for_zigs, cos_minus_angle_for_zigs, curve_list_for_zigs, Point::dist(), DraftVecUtils::dist(), CCurve::GetSpans(), SplineSurface::i, CVertex::m_c, m_curves, m_please_abort, m_processing_done, m_single_area_processing_length, CVertex::m_type, CVertex::m_user_data, Span::m_v, CCurve::m_vertices, KDL::max(), Offset(), nativeifc.ifc_observer::params, PI, KDL::sin(), sin_angle_for_zigs, sin_minus_angle_for_zigs, SingleOffsetPocketMode, SpiralPocketMode, Split(), stepover_for_pocket, Point::tolerance, zigzag(), ZigZagPocketMode, and ZigZagThenSingleOffsetPocketMode.
Referenced by SplitAndMakePocketToolpath().
move()
void CArea::move (CCurve && curve)
Definition at line 62 of file libarea/Area.cpp.
References m_curves, and Path.Post.scripts.opensbp_post::move().
Referenced by draftguitools.gui_circulararray.CircularArray::Activated(), and draftguitools.gui_polararray.PolarArray::Activated().
NearestPoint()
Point CArea::NearestPoint (const Point & p) const
Definition at line 75 of file libarea/Area.cpp.
References Point::dist(), DraftVecUtils::dist(), m_curves, CCurve::NearestPoint(), and buildPsets::p.
Referenced by BOOST_PYTHON_MODULE(), and init_pyarea().
num_curves()
unsigned int CArea::num_curves () inline
Definition at line 83 of file libarea/Area.h.
References m_curves.
Referenced by BOOST_PYTHON_MODULE(), and init_pyarea().
Offset()
void CArea::Offset (double inwards_value)
Definition at line 509 of file AreaClipper.cpp.
References MakePolyPoly(), OffsetWithLoops(), SetFromResult(), and TPolyPolygon.
Referenced by BOOST_PYTHON_MODULE(), init_pyarea(), MakeOnePocketCurve(), MakePocketToolpath(), and recur().
OffsetWithClipper()
void CArea::OffsetWithClipper (double offset, ClipperLib::JoinType joinType = ClipperLib::jtRound, ClipperLib::EndType endType = ClipperLib::etOpenRound, double miterLimit = 5.0, double roundPrecision = 0.0)
Definition at line 557 of file AreaClipper.cpp.
References KDL::acos(), SCL.SimpleDataTypes::c, KDL::cos(), SplineSurface::i, m_min_arc_points, MakePolyPoly(), PI, SetFromResult(), and TPolyPolygon.
PopulateClipper()
void CArea::PopulateClipper (ClipperLib::Clipper & c, ClipperLib::PolyType type) const
Definition at line 518 of file AreaClipper.cpp.
References SCL.SimpleDataTypes::c, CCurve::IsClosed(), MakePoly(), buildPsets::p, TPolygon, and Path.Post.scripts.grbl_post::type.
Reorder()
void CArea::Reorder ()
Definition at line 176 of file libarea/Area.cpp.
References CAreaOrderer::Insert(), m_curves, m_processing_done, m_set_processing_length_in_split, m_split_processing_length, and CAreaOrderer::m_top_level.
Referenced by BOOST_PYTHON_MODULE(), init_pyarea(), and recur().
set_accuracy()
void CArea::set_accuracy (double accuracy) static
Definition at line 51 of file libarea/Area.cpp.
set_clipper_clean_distance()
void CArea::set_clipper_clean_distance (double clipper_clean_distance) static
Definition at line 50 of file libarea/Area.cpp.
set_clipper_scale()
void CArea::set_clipper_scale (double clipper_scale) static
Definition at line 55 of file libarea/Area.cpp.
set_clipper_simple()
void CArea::set_clipper_simple (bool clipper_simple) static
Definition at line 49 of file libarea/Area.cpp.
set_fit_arcs()
void CArea::set_fit_arcs (bool fit_arcs) static
Definition at line 48 of file libarea/Area.cpp.
set_max_arc_points()
void CArea::set_max_arc_points (short max_arc_points) static
Definition at line 54 of file libarea/Area.cpp.
set_min_arc_points()
void CArea::set_min_arc_points (short min_arc_points) static
Definition at line 53 of file libarea/Area.cpp.
set_tolerance()
void CArea::set_tolerance (double tolerance) static
Definition at line 47 of file libarea/Area.cpp.
set_units()
void CArea::set_units (double units) static
Definition at line 52 of file libarea/Area.cpp.
Referenced by set_units().
SpanIntersections()
void CArea::SpanIntersections (const Span & span, std::list< Point > & pts) const
Definition at line 900 of file libarea/Area.cpp.
References SCL.SimpleDataTypes::c, m_curves, Span::On(), buildPsets::p, and InitGui::t.
Referenced by CurveIntersections().
Split()
void CArea::Split (std::list< CArea > & m_areas) const
Definition at line 792 of file libarea/Area.cpp.
References a, HolesLinked(), CCurve::IsClockwise(), m_curves, and m_please_abort.
Referenced by MakePocketToolpath(), and SplitAndMakePocketToolpath().
SplitAndMakePocketToolpath()
void CArea::SplitAndMakePocketToolpath (std::list< CCurve > & toolpath, const CAreaPocketParams & params) const
Definition at line 606 of file libarea/Area.cpp.
References m_processing_done, m_set_processing_length_in_split, m_single_area_processing_length, m_split_processing_length, m_units, MakePocketToolpath(), nativeifc.ifc_observer::params, and Split().
Subtract()
void CArea::Subtract (const CArea & a2)
Definition at line 430 of file AreaClipper.cpp.
References NavigationIndicatorGui::a2, SCL.SimpleDataTypes::c, m_clipper_simple, MakePolyPoly(), SetFromResult(), and TPolyPolygon.
Referenced by BOOST_PYTHON_MODULE(), GetOverlapType(), and init_pyarea().
Thicken()
void CArea::Thicken (double value)
Definition at line 592 of file AreaClipper.cpp.
References OffsetSpansWithObrounds(), SetFromResult(), and TPolyPolygon.
Referenced by BOOST_PYTHON_MODULE(), init_pyarea(), and ThickLine::ThickLine().
Union()
void CArea::Union (const CArea & a2)
Definition at line 458 of file AreaClipper.cpp.
References NavigationIndicatorGui::a2, SCL.SimpleDataTypes::c, m_clipper_simple, MakePolyPoly(), SetFromResult(), and TPolyPolygon.
Referenced by BOOST_PYTHON_MODULE(), and init_pyarea().
UniteCurves()
CArea CArea::UniteCurves (std::list< CCurve > & curves) static
Definition at line 473 of file AreaClipper.cpp.
References SCL.SimpleDataTypes::c, m_clipper_simple, MakePoly(), buildPsets::p, SetFromResult(), TPolygon, and TPolyPolygon.
Xor()
void CArea::Xor (const CArea & a2)
Definition at line 495 of file AreaClipper.cpp.
References NavigationIndicatorGui::a2, SCL.SimpleDataTypes::c, m_clipper_simple, MakePolyPoly(), SetFromResult(), and TPolyPolygon.
Member Data Documentation
m_accuracy
double CArea::m_accuracy = 0.01 static
Definition at line 50 of file libarea/Area.h.
Referenced by AddVertex(), CCurve::CheckForArc(), and CCurve::UnFitArcs().
m_after_MakeOffsets_length
double CArea::m_after_MakeOffsets_length = 0.0 static
Definition at line 60 of file libarea/Area.h.
Referenced by MakeOnePocketCurve().
m_clipper_clean_distance
double CArea::m_clipper_clean_distance = 0.0 static
Definition at line 54 of file libarea/Area.h.
Referenced by SetFromResult().
m_clipper_scale
double CArea::m_clipper_scale = 10000.0 static
Definition at line 66 of file libarea/Area.h.
Referenced by DoubleAreaPoint::DoubleAreaPoint(), and DoubleAreaPoint::int_point().
m_clipper_simple
bool CArea::m_clipper_simple = false static
Definition at line 53 of file libarea/Area.h.
Referenced by Clip(), Intersect(), OffsetSpansWithObrounds(), OffsetWithLoops(), Subtract(), Union(), UniteCurves(), and Xor().
m_curves
std::list<CCurve> CArea::m_curves
Definition at line 49 of file libarea/Area.h.
Referenced by ChangeStartToNearest(), FitArcs(), CInnerCurves::GetArea(), GetArea(), GetBox(), getCurves(), GetOverlapType(), MakeOnePocketCurve(), MakePocketToolpath(), MakePolyPoly(), move(), NearestPoint(), num_curves(), OffsetSpansWithObrounds(), AreaDxfRead::OnReadArc(), AreaDxfRead::OnReadLine(), recur(), Reorder(), SetFromResult(), SpanIntersections(), Split(), and zigzag().
m_fit_arcs
bool CArea::m_fit_arcs = true static
Definition at line 55 of file libarea/Area.h.
Referenced by SetFromResult().
m_MakeOffsets_increment
double CArea::m_MakeOffsets_increment = 0.0 static
Definition at line 61 of file libarea/Area.h.
Referenced by MakeOnePocketCurve().
m_max_arc_points
int CArea::m_max_arc_points = 100 static
Definition at line 57 of file libarea/Area.h.
m_min_arc_points
int CArea::m_min_arc_points = 4 static
Definition at line 56 of file libarea/Area.h.
Referenced by AddVertex(), and OffsetWithClipper().
m_please_abort
bool CArea::m_please_abort = false static
Definition at line 64 of file libarea/Area.h.
Referenced by GetCurveItem::GetCurve(), MakeOnePocketCurve(), MakePocketToolpath(), Split(), and zigzag().
m_processing_done
double CArea::m_processing_done = 0.0 static
Definition at line 58 of file libarea/Area.h.
Referenced by MakeOnePocketCurve(), MakePocketToolpath(), Reorder(), SplitAndMakePocketToolpath(), and zigzag().
m_set_processing_length_in_split
bool CArea::m_set_processing_length_in_split = false static
Definition at line 63 of file libarea/Area.h.
Referenced by Reorder(), and SplitAndMakePocketToolpath().
m_single_area_processing_length
double CArea::m_single_area_processing_length = 0.0 static
Definition at line 59 of file libarea/Area.h.
Referenced by MakeOnePocketCurve(), MakePocketToolpath(), SplitAndMakePocketToolpath(), and zigzag().
m_split_processing_length
double CArea::m_split_processing_length = 0.0 static
Definition at line 62 of file libarea/Area.h.
Referenced by Reorder(), and SplitAndMakePocketToolpath().
m_units
double CArea::m_units = 1.0 static
Definition at line 51 of file libarea/Area.h.
Referenced by AddVertex(), CCurve::CheckForArc(), GetCurveItem::GetCurve(), MakeLoop(), MakeObround(), SetFromResult(), SplitAndMakePocketToolpath(), CCurve::UnFitArcs(), UnFitArcs(), and zigzag().
The documentation for this class was generated from the following files:
libarea/Area.h
libarea/Area.cpp
AreaClipper.cpp
AreaPocket.cpp