FreeCAD: TechDraw::DrawProjGroup Class Reference
TechDraw::DrawProjGroup Class Reference
#include <DrawProjGroup.h>
Public Member Functions
DrawProjGroup ()
Constructor.
~DrawProjGroup () override=default
double autoScale () const override
Anchor Element to align views to.
double autoScale (double w, double h) const override
QRectF getRect () const override
QRectF getRect (bool scaled) const
bool hasProjection (const char *viewProjType) const
Check if container has a view of a specific type.
bool canDelete (const char *viewProjType) const
check if it is safe to delete item
App::DocumentObject * getProjObj (const char *viewProjType) const
DrawProjGroupItem * getProjItem (const char *viewProjType) const
App::DocumentObject * addProjection (const char *viewProjType)
Adds a projection to the group.
int removeProjection (const char *viewProjType)
Removes a projection from the group.
int purgeProjections ()
Base::Vector3d getXYPosition (const char *viewTypeCStr)
short mustExecute () const override
Public Member Functions inherited from TechDraw::DrawViewCollection
DrawViewCollection ()
Constructor.
~DrawViewCollection () override
short mustExecute () const override
int addView (App::DocumentObject *obj)
int removeView (App::DocumentObject *obj)
std::vector< App::DocumentObject * > getViews () const
void rebuildViewList ()
bool isUnsetting ()
int countChildren ()
void lockChildren ()
void onDocumentRestored () override
get called after a document has been fully restored
App::DocumentObjectExecReturn * execute () override
recalculate the Feature
void unsetupObject () override
get called when object is going to be removed from the document
const char * getViewProviderName () const override
returns the type name of the ViewProvider
QRectF getRect () const override
Public Member Functions inherited from TechDraw::DrawView
DrawView ()
Constructor.
~DrawView () override
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, App::Property *prop) override
bool isInClip ()
DrawViewClip * getClipGroup ()
DrawViewCollection * getCollection () const
PyObject * getPyObject () override
virtual DrawPage * findParentPage () const
virtual std::vector< DrawPage * > findAllParentPages () const
virtual DrawView * claimParent () const
virtual int countParentPages () const
DrawView::countParentPages Fixes a crash in TechDraw when user creates duplicate page without dependencies In fixOrphans() we check how many parent pages an object has before deleting in case it is also a child of another duplicate page.
QRectF getRectAligned () const
virtual void setPosition (double x, double y, bool force=false)
virtual Base::Vector3d getPosition () const
virtual bool keepUpdated (void)
void requestPaint (void)
void showProgressMessage (std::string featureName, std::string text)
virtual double getScale (void) const
virtual int getScaleType () const
void checkScale (void)
virtual void handleXYLock (void)
virtual bool isLocked (void) const
virtual bool showLock (void) const
std::vector< TechDraw::DrawLeaderLine * > getLeaders (void) const
void setScaleAttribute ()
void overrideKeepUpdated (bool s)
bool overrideKeepUpdated (void)
void translateLabel (std::string context, std::string baseName, std::string uniqueName)
virtual App::PropertyLink * getOwnerProperty ()
Public Member Functions inherited from App::DocumentObject
virtual const char * getViewProviderNameOverride () const
DocumentObject ()
Constructor.
~DocumentObject () override
const char * getDagKey () const
returns a value that uniquely identifies this DocumentObject.
const char * getNameInDocument () const
returns the name which is set in the document for this object (not the name property!)
long getID () const
Return the object ID that is unique within its owner document.
std::string getExportName (bool forced=false) const
returns the name that is safe to be exported to other document
std::string getFullName () const override
Return the object full name of the form DocName::ObjName.
std::string getFullLabel () const
Return the object full label in the form DocName::ObjName.
bool isAttachedToDocument () const override
const char * detachFromDocument () override
App::Document * getDocument () const
gets the document in which this Object is handled
void touch (bool noRecompute=false)
set this document object touched (cause recomputation on dependent features)
bool isTouched () const
test if this document object is touched
void enforceRecompute ()
Enforce this document object to be recomputed.
bool mustRecompute () const
Test if this document object must be recomputed.
void purgeTouched ()
reset this document object touched
bool isError () const
set this feature to error
bool isValid () const
void purgeError ()
remove the error from the object
bool isRecomputing () const
returns true if this objects is currently recomputing
bool isRestoring () const
returns true if this objects is currently restoring from file
bool isRemoving () const
returns true if this objects is currently removed from the document
void freeze ()
set this document object freezed (prevent recomputation)
void unfreeze (bool noRecompute=false)
set this document object unfreezed (and touch it)
bool isFreezed () const
returns true if this objects is currently freezed
unsigned long getStatus () const
return the status bits
bool testStatus (ObjectStatus pos) const
void setStatus (ObjectStatus pos, bool on)
int isExporting () const
virtual int setElementVisible (const char *element, bool visible)
virtual int isElementVisible (const char *element) const
virtual bool hasChildElement () const
return true to activate tree view group object handling and element visibility
const std::vector< App::DocumentObject * > & getOutList () const
returns a list of objects this object is pointing to by Links
std::vector< App::DocumentObject * > getOutList (int option) const
void getOutList (int option, std::vector< App::DocumentObject * > &res) const
std::vector< App::DocumentObject * > getOutListOfProperty (App::Property *) const
returns a list of objects linked by the property
std::vector< App::DocumentObject * > getOutListRecursive () const
returns a list of objects this object is pointing to by Links and all further descended
void clearOutListCache () const
clear internal out list cache
std::vector< std::list< App::DocumentObject * > > getPathsByOutList (App::DocumentObject *to) const
get all possible paths from this to another object following the OutList
const std::vector< App::DocumentObject * > & getInList () const
std::vector< App::DocumentObject * > getInListRecursive () const
get all objects link directly or indirectly to this object
void getInListEx (std::set< App::DocumentObject * > &inSet, bool recursive, std::vector< App::DocumentObject * > *inList=nullptr) const
std::set< App::DocumentObject * > getInListEx (bool recursive) const
DocumentObjectGroup * getGroup () const
get group if object is part of a group, otherwise 0 is returned
bool isInInListRecursive (DocumentObject *objToTest) const
test if this object is in the InList and recursive further down
bool isInInList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the InList
bool isInOutListRecursive (DocumentObject *objToTest) const
test if the given object is in the OutList and recursive further down
bool isInOutList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the OutList
void _removeBackLink (DocumentObject *)
internal, used by PropertyLink to maintain DAG back links
void _addBackLink (DocumentObject *)
internal, used by PropertyLink to maintain DAG back links
bool testIfLinkDAGCompatible (DocumentObject *linkTo) const
testIfLinkIsDAG tests a link that is about to be created for circular references.
bool testIfLinkDAGCompatible (const std::vector< DocumentObject * > &linksTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSubList &linksTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSub &linkTo) const
virtual std::string getElementMapVersion (const App::Property *prop, bool restored=false) const
virtual bool checkElementMapVersion (const App::Property *prop, const char *ver) const
Return true to signal re-generation of geometry element names.
bool recomputeFeature (bool recursive=false)
const char * getStatusString () const
get the status Message
virtual void onLostLinkToObject (DocumentObject *)
virtual DocumentObject * getSubObject (const char *subname, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
std::vector< DocumentObject * > getSubObjectList (const char *subname, std::vector< int > *subsizes=nullptr, bool flatten=false) const
virtual std::vector< std::string > getSubObjects (int reason=0) const
std::vector< std::pair< App::DocumentObject *, std::string > > getParents (int depth=0) const
Obtain top parents and subnames of this object using its InList.
App::DocumentObject * getFirstParent () const
Obtain the first parent group of this object.
virtual DocumentObject * getLinkedObject (bool recurse=true, Base::Matrix4D *mat=nullptr, bool transform=false, int depth=0) const
virtual bool canLinkProperties () const
virtual bool isLink () const
virtual bool isLinkGroup () const
virtual bool allowDuplicateLabel () const
virtual void onBeforeChangeLabel (std::string &newLabel)
void Save (Base::Writer &writer) const override
virtual void setExpression (const ObjectIdentifier &path, std::shared_ptr< App::Expression > expr)
void clearExpression (const ObjectIdentifier &path)
virtual const PropertyExpressionEngine::ExpressionInfo getExpression (const ObjectIdentifier &path) const
virtual void renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &paths)
const std::string & getOldLabel () const
const char * getViewProviderNameStored () const
bool removeDynamicProperty (const char *prop) override
App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
App::DocumentObject * resolve (const char *subname, App::DocumentObject **parent=nullptr, std::string *childName=nullptr, const char **subElement=nullptr, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
App::DocumentObject * resolveRelativeLink (std::string &subname, App::DocumentObject *&link, std::string &linkSub) const
virtual bool adjustRelativeLinks (const std::set< App::DocumentObject * > &inList, std::set< App::DocumentObject * > *visited=nullptr)
virtual int canLoadPartial () const
virtual void onUpdateElementReference (const Property *)
virtual bool redirectSubName (std::ostringstream &ss, DocumentObject *topParent, DocumentObject *child) const
Public Member Functions inherited from App::TransactionalObject
TransactionalObject ()
Constructor.
~TransactionalObject () override
Public Member Functions inherited from App::ExtensionContainer
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
Property * getPropertyByName (const char *name) const override
find a property by its name
template<typename T >
T * getPropertyByName (const char *name) const
find a property by its name, dynamic cased to specified type
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Attributes
App::PropertyLinkList Source
App::PropertyXLinkList XSource
App::PropertyEnumeration ProjectionType
App::PropertyBool AutoDistribute
Whether projcetion group view are automatically distributed or not.
App::PropertyLength spacingX
Default horizontal spacing between adjacent views on Drawing, in mm.
App::PropertyLength spacingY
Default vertical spacing between adjacent views on Drawing, in mm.
App::PropertyLink Anchor
Public Attributes inherited from TechDraw::DrawViewCollection
App::PropertyLinkList Views
Public Attributes inherited from TechDraw::DrawView
App::PropertyDistance X
App::PropertyDistance Y
App::PropertyBool LockPosition
App::PropertyFloatConstraint Scale
App::PropertyEnumeration ScaleType
App::PropertyAngle Rotation
App::PropertyString Caption
boost::signals2::signal< void(const DrawView *)> signalGuiPaint
boost::signals2::signal< void(const DrawView *, std::string, std::string)> signalProgressMessage
Public Attributes inherited from App::DocumentObject
PropertyString Label
PropertyString Label2
PropertyExpressionEngine ExpressionEngine
PropertyBool Visibility
Allow control visibility status in App name space.
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalBeforeChange
signal before changing a property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalChanged
signal on changed property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalEarlyChanged
signal on changed property of this object before document scoped signalChangedObject
methods override Feature
static const char * ProjectionTypeEnums []
Allowed projection types - either Document, First Angle or Third Angle.
App::DocumentObjectExecReturn * execute () override
recalculate the Feature
const char * getViewProviderName () const override
returns the type name of the ViewProvider
PyObject * getPyObject () override
App::Enumeration usedProjectionType ()
Determines either "First Angle" or "Third Angle".
bool hasAnchor ()
void setAnchorDirection (Base::Vector3d dir)
Base::Vector3d getAnchorDirection ()
TechDraw::DrawProjGroupItem * getAnchor ()
std::pair< Base::Vector3d, Base::Vector3d > getDirsFromFront (DrawProjGroupItem *view)
std::pair< Base::Vector3d, Base::Vector3d > getDirsFromFront (std::string viewType)
void updateSecondaryDirs ()
void rotate (const std::string &rotationdirection)
void spin (const std::string &spindirection)
void spin (double angle)
void dumpISO (const char *title)
std::vector< DrawProjGroupItem * > getViewsAsDPGI ()
void recomputeChildren ()
void updateChildrenScale ()
void autoPositionChildren ()
void updateChildrenEnforce ()
std::vector< App::DocumentObject * > getAllSources () const
bool checkFit () const override
bool checkFit (DrawPage *p) const override
check if View is too big for page
bool waitingForChildren () const
void reportReady ()
void dumpTouchedProps ()
void onChanged (const App::Property *prop) override
get called by the container when a property was changed
bool checkViewProjType (const char *in)
Annoying helper - keep in sync with DrawProjGroupItem::TypeEnums.
void arrangeViewPointers (std::array< DrawProjGroupItem *, MAXPROJECTIONCOUNT > &viewPtrs) const
void makeViewBbs (std::array< DrawProjGroupItem *, MAXPROJECTIONCOUNT > &viewPtrs, std::array< Base::BoundBox3d, MAXPROJECTIONCOUNT > &bboxes, bool scaled=true) const
Populates array of 10 BoundBox3d's given DrawProjGroupItem *s.
void getViewArea (std::array< TechDraw::DrawProjGroupItem *, MAXPROJECTIONCOUNT > &viewPtrs, double &width, double &height, bool scaled=true) const
Helper for calculateAutomaticScale.
TechDraw::DrawPage * getPage () const
Returns pointer to our page, or NULL if it couldn't be located.
void updateChildrenSource ()
void updateChildrenLock ()
int getViewIndex (const char *viewTypeCStr) const
int getDefProjConv () const
Base::Vector3d dir2vec (gp_Dir d)
gp_Dir vec2dir (Base::Vector3d v)
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, App::Property *prop) override
double getMaxRowHeight (std::array< int, 3 > list, std::array< Base::BoundBox3d, MAXPROJECTIONCOUNT > bboxes)
double getMaxColWidth (std::array< int, 3 > list, std::array< Base::BoundBox3d, MAXPROJECTIONCOUNT > bboxes)
Additional Inherited Members
Public Types inherited from App::DocumentObject
enum OutListOption { OutListNoExpression = 1, OutListNoHidden = 2, OutListNoXLinked = 4 }
OutList options.
enum GSReason { GS_DEFAULT, GS_SELECT }
reason of calling getSubObjects()
Public Types inherited from App::ExtensionContainer
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Static Public Member Functions inherited from TechDraw::DrawView
static bool isProjGroupItem (DrawViewPart *item)
Static Public Member Functions inherited from App::DocumentObject
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
Check if the subname reference ends with hidden marker.
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Attributes inherited from App::DocumentObject
static DocumentObjectExecReturn * StdReturn
Protected Member Functions inherited from TechDraw::DrawViewCollection
void onChanged (const App::Property *prop) override
get called by the container when a property was changed
Protected Member Functions inherited from TechDraw::DrawView
void onBeforeChange (const App::Property *prop) override
get called before the value is changed
virtual void validateScale ()
int prefScaleType ()
double prefScale ()
void touchTreeOwner (App::DocumentObject *owner) const
Protected Member Functions inherited from App::DocumentObject
virtual App::DocumentObjectExecReturn * recompute ()
recompute only this object
App::DocumentObjectExecReturn * executeExtensions ()
void setError ()
void resetError ()
void setDocument (App::Document *doc)
void onEarlyChange (const Property *prop) override
get called by the container when a property was changed
virtual void onUndoRedoFinished ()
get called after an undo/redo transaction is finished
virtual void onSettingDocument ()
get called after setting the document
virtual void setupObject ()
get called after a brand new object was created
void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus) override
get called when a property status has changed
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData () const
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from TechDraw::DrawViewCollection
bool nowUnsetting
Protected Attributes inherited from TechDraw::DrawView
std::string pageFeatName
bool autoPos
bool mouseMove
Protected Attributes inherited from App::DocumentObject
std::bitset< 32 > StatusBits
Py::SmartPtr PythonObject
python object of this class and all descendent
App::Document * _pDoc {nullptr}
pointer to the document this object belongs to
std::string oldLabel
Old label; used for renaming expressions.
const std::string * pcNameInDocument {nullptr}
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Detailed Description
Class super-container for managing a collection of DrawProjGroupItem Page Features
Definition at line 51 of file DrawProjGroup.h.
Constructor & Destructor Documentation
DrawProjGroup()
DrawProjGroup::DrawProjGroup ()
Constructor.
Definition at line 59 of file DrawProjGroup.cpp.
References ADD_PROPERTY_TYPE, ParameterGrp::GetBool(), TechDraw::Preferences::getPreferenceGroup(), App::Global, toolbit-attributes::group, App::Property::Hidden, App::Prop_None, and DrawingExample::Source.
~DrawProjGroup()
TechDraw::DrawProjGroup::~DrawProjGroup () override default
Member Function Documentation
addProjection()
App::DocumentObject * DrawProjGroup::addProjection (const char * viewProjType)
Adds a projection to the group.
Returns
pointer to the new view
Definition at line 453 of file DrawProjGroup.cpp.
References importDXF::addObject(), TechDraw::DrawViewCollection::addView(), Anchor, checkViewProjType(), Base::Console(), TechDraw::DrawViewPart::Direction, Base::ConsoleSingleton::Error(), TechDraw::DrawView::findParentPage(), getDirsFromFront(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::Document::getUniqueObjectName(), App::PropertyString::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyXLinkSubList::getValues(), hasProjection(), App::DocumentObject::Label, TechDraw::DrawView::LockPosition, App::Property::purgeTouched(), App::Property::ReadOnly, App::DocumentObject::recomputeFeature(), TechDraw::DrawView::requestPaint(), App::Property::setStatus(), App::PropertyVector::setValue(), App::PropertyEnumeration::setValue(), App::PropertyLink::setValue(), App::PropertyString::setValue(), App::PropertyBool::setValue(), App::PropertyLinkList::setValues(), App::PropertyXLinkSubList::setValues(), Source, TechDraw::DrawViewPart::Source, TechDraw::DrawView::translateLabel(), TechDraw::DrawProjGroupItem::Type, TechDraw::DrawViewPart::XDirection, XSource, and TechDraw::DrawViewPart::XSource.
Referenced by TechDrawGui::TaskProjGroup::restoreGroupState().
arrangeViewPointers()
void DrawProjGroup::arrangeViewPointers (std::array< DrawProjGroupItem *, MAXPROJECTIONCOUNT > & viewPtrs) const protected
Definition at line 827 of file DrawProjGroup.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), TechDraw::DrawView::findParentPage(), getDefProjConv(), App::DocumentObject::getNameInDocument(), App::PropertyEnumeration::getValueAsString(), App::PropertyListsT< T, ListT, ParentT >::getValues(), SplineSurface::i, App::PropertyEnumeration::isValue(), TechDraw::MAXPROJECTIONCOUNT, ProjectionType, TechDraw::DrawPage::ProjectionType, ProjectionTypeEnums, TechDraw::DrawViewCollection::Views, and Base::ConsoleSingleton::Warning().
Referenced by getRect(), and getXYPosition().
autoPositionChildren()
void DrawProjGroup::autoPositionChildren ()
Definition at line 961 of file DrawProjGroup.cpp.
References App::PropertyListsT< T, ListT, ParentT >::getValues(), and TechDraw::DrawViewCollection::Views.
Referenced by execute().
autoScale() [1/2]
double DrawProjGroup::autoScale () const override virtual
Anchor Element to align views to.
Reimplemented from TechDraw::DrawView.
Definition at line 283 of file DrawProjGroup.cpp.
References TechDraw::DrawView::findParentPage().
Referenced by execute().
autoScale() [2/2]
double DrawProjGroup::autoScale (double w, double h) const override virtual
Reimplemented from TechDraw::DrawView.
Definition at line 293 of file DrawProjGroup.cpp.
References getRect(), KDL::min(), TechDraw::DrawUtil::sensibleScale(), and src.Mod.PartDesign.fcgear.svggear::w.
canDelete()
bool DrawProjGroup::canDelete (const char * viewProjType) const
check if it is safe to delete item
Definition at line 423 of file DrawProjGroup.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), Base::Persistence::getClassTypeId(), App::DocumentObject::getNameInDocument(), App::PropertyListsT< T, ListT, ParentT >::getValues(), and TechDraw::DrawViewCollection::Views.
Referenced by TechDrawGui::TaskProjGroup::setupViewCheckboxes(), and TechDrawGui::TaskProjGroup::viewToggled().
checkFit() [1/2]
bool DrawProjGroup::checkFit () const override virtual
Reimplemented from TechDraw::DrawView.
Definition at line 255 of file DrawProjGroup.cpp.
References TechDraw::DrawView::findParentPage(), and waitingForChildren().
Referenced by execute().
checkFit() [2/2]
bool DrawProjGroup::checkFit (DrawPage * p) const override virtual
check if View is too big for page
Reimplemented from TechDraw::DrawView.
Definition at line 268 of file DrawProjGroup.cpp.
References TechDraw::DrawPage::getPageHeight(), TechDraw::DrawPage::getPageWidth(), getRect(), and waitingForChildren().
checkViewProjType()
bool DrawProjGroup::checkViewProjType (const char * in) protected
Annoying helper - keep in sync with DrawProjGroupItem::TypeEnums.
Todo:
{See note regarding App::PropertyEnumeration on my wiki page https://freecad.org/wiki/User:Ian.rees}
Returns
true iff 'in' is a valid name for an orthographic/isometric view
Definition at line 386 of file DrawProjGroup.cpp.
Referenced by addProjection(), and removeProjection().
dir2vec()
Base::Vector3d DrawProjGroup::dir2vec (gp_Dir d) protected
Definition at line 588 of file DrawProjGroup.cpp.
dumpISO()
void DrawProjGroup::dumpISO (const char * title)
dumps the current iso DPGI's
Definition at line 1250 of file DrawProjGroup.cpp.
References Base::Console(), TechDraw::DrawUtil::formatVector(), App::PropertyListsT< T, ListT, ParentT >::getValues(), Base::ConsoleSingleton::Message(), InitGui::t, Plot::title(), TestSpreadsheet::v, and TechDraw::DrawViewCollection::Views.
dumpTouchedProps()
void TechDraw::DrawProjGroup::dumpTouchedProps ()
execute()
App::DocumentObjectExecReturn * DrawProjGroup::execute () override virtual
recalculate the Feature
Reimplemented from App::DocumentObject.
Definition at line 169 of file DrawProjGroup.cpp.
References Anchor, AutoDistribute, autoPositionChildren(), autoScale(), checkFit(), TechDraw::DrawViewCollection::execute(), TechDraw::DrawUtil::fpCompare(), getPage(), TechDraw::DrawView::getScale(), App::PropertyLink::getValue(), App::PropertyBool::getValue(), App::PropertyEnumeration::isValue(), TechDraw::DrawView::keepUpdated(), TechDraw::DrawView::overrideKeepUpdated(), TechDraw::DrawView::Scale, TechDraw::DrawView::ScaleType, App::PropertyFloat::setValue(), App::DocumentObject::StdReturn, and waitingForChildren().
Referenced by FeaturePython.DistanceBolt::onChanged().
getAllSources()
std::vector< App::DocumentObject * > DrawProjGroup::getAllSources () const
Definition at line 92 of file DrawProjGroup.cpp.
References App::PropertyXLinkSubList::getLinks(), App::PropertyListsT< T, ListT, ParentT >::getValues(), result, Source, and XSource.
getAnchor()
TechDraw::DrawProjGroupItem * DrawProjGroup::getAnchor ()
Definition at line 1075 of file DrawProjGroup.cpp.
References Anchor, and App::PropertyLink::getValue().
Referenced by TechDrawGui::TaskProjGroup::customDirectionClicked(), getDirsFromFront(), TechDraw::DrawProjGroupItem::isAnchor(), TechDrawGui::ViewProviderProjGroupItem::onDelete(), rotate(), TechDrawGui::TaskProjGroup::rotateButtonClicked(), TechDrawGui::TaskProjGroup::saveGroupState(), spin(), TechDrawGui::TaskProjGroup::turnProjGroupToView(), and updateSecondaryDirs().
getAnchorDirection()
Base::Vector3d DrawProjGroup::getAnchorDirection ()
Definition at line 1091 of file DrawProjGroup.cpp.
References Anchor, TechDraw::DrawViewPart::Direction, App::PropertyVector::getValue(), and App::PropertyLink::getValue().
Referenced by TechDrawGui::TaskProjGroup::setUiPrimary().
getDefProjConv()
int DrawProjGroup::getDefProjConv () const protected
Definition at line 1245 of file DrawProjGroup.cpp.
References TechDraw::Preferences::projectionAngle().
Referenced by arrangeViewPointers(), and getViewIndex().
getDirsFromFront() [1/2]
std::pair< Base::Vector3d, Base::Vector3d > DrawProjGroup::getDirsFromFront (DrawProjGroupItem * view)
Definition at line 566 of file DrawProjGroup.cpp.
References App::PropertyEnumeration::getValueAsString(), result, and TechDraw::DrawProjGroupItem::Type.
Referenced by addProjection(), rotate(), and updateSecondaryDirs().
getDirsFromFront() [2/2]
std::pair< Base::Vector3d, Base::Vector3d > DrawProjGroup::getDirsFromFront (std::string viewType)
Definition at line 573 of file DrawProjGroup.cpp.
References Base::Console(), getAnchor(), TechDraw::DrawViewPart::getDirsFromFront(), App::PropertyString::getValue(), App::DocumentObject::Label, result, and Base::ConsoleSingleton::Warning().
getMaxColWidth()
double DrawProjGroup::getMaxColWidth (std::array< int, 3 > list, std::array< Base::BoundBox3d, MAXPROJECTIONCOUNT > bboxes) protected
Definition at line 745 of file DrawProjGroup.cpp.
References KDL::max().
Referenced by getXYPosition().
getMaxRowHeight()
double DrawProjGroup::getMaxRowHeight (std::array< int, 3 > list, std::array< Base::BoundBox3d, MAXPROJECTIONCOUNT > bboxes) protected
Definition at line 732 of file DrawProjGroup.cpp.
References KDL::max().
Referenced by getXYPosition().
getPage()
TechDraw::DrawPage * DrawProjGroup::getPage () const protected
Returns pointer to our page, or NULL if it couldn't be located.
Definition at line 252 of file DrawProjGroup.cpp.
References TechDraw::DrawView::findParentPage().
Referenced by execute(), onChanged(), and usedProjectionType().
getProjItem()
DrawProjGroupItem * DrawProjGroup::getProjItem (const char * viewProjType) const
Definition at line 373 of file DrawProjGroup.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), App::DocumentObject::getNameInDocument(), getProjObj(), and result.
getProjObj()
App::DocumentObject * DrawProjGroup::getProjObj (const char * viewProjType) const
Definition at line 355 of file DrawProjGroup.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), App::DocumentObject::getNameInDocument(), App::PropertyListsT< T, ListT, ParentT >::getValues(), and TechDraw::DrawViewCollection::Views.
Referenced by getProjItem().
getPyObject()
PyObject * DrawProjGroup::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from App::DocumentObject.
Definition at line 1266 of file DrawProjGroup.cpp.
References Py::SmartPtr::is(), Py::new_reference_to(), and App::DocumentObject::PythonObject.
getRect() [1/2]
QRectF DrawProjGroup::getRect () const override virtual
Reimplemented from TechDraw::DrawView.
Definition at line 307 of file DrawProjGroup.cpp.
Referenced by autoScale(), and checkFit().
getRect() [2/2]
QRectF DrawProjGroup::getRect (bool scaled) const
Definition at line 309 of file DrawProjGroup.cpp.
References arrangeViewPointers(), App::PropertyQuantity::getValue(), getViewArea(), spacingX, and spacingY.
getViewArea()
void DrawProjGroup::getViewArea (std::array< TechDraw::DrawProjGroupItem *, MAXPROJECTIONCOUNT > & viewPtrs, double & width, double & height, bool scaled = true) const protected
Helper for calculateAutomaticScale.
Returns a width and height in object-space scale, for the enabled views without accounting for their actual X and Y positions or borders.
Definition at line 328 of file DrawProjGroup.cpp.
References makeViewBbs(), and KDL::max().
Referenced by getRect().
getViewIndex()
int DrawProjGroup::getViewIndex (const char * viewTypeCStr) const protected
Definition at line 758 of file DrawProjGroup.cpp.
References Base::Console(), TechDraw::DrawView::findParentPage(), getDefProjConv(), App::DocumentObject::getNameInDocument(), App::PropertyEnumeration::getValueAsString(), App::PropertyEnumeration::isValue(), ProjectionType, TechDraw::DrawPage::ProjectionType, ProjectionTypeEnums, and Base::ConsoleSingleton::Warning().
Referenced by getXYPosition().
getViewProviderName()
const char* TechDraw::DrawProjGroup::getViewProviderName () const inline override virtual
returns the type name of the ViewProvider
Reimplemented from App::DocumentObject.
Definition at line 109 of file DrawProjGroup.h.
getViewsAsDPGI()
std::vector< DrawProjGroupItem * > DrawProjGroup::getViewsAsDPGI ()
Definition at line 1235 of file DrawProjGroup.cpp.
References App::PropertyListsT< T, ListT, ParentT >::getValues(), result, TestSpreadsheet::v, and TechDraw::DrawViewCollection::Views.
getXYPosition()
Base::Vector3d DrawProjGroup::getXYPosition (const char * viewTypeCStr)
Definition at line 599 of file DrawProjGroup.cpp.
References arrangeViewPointers(), AutoDistribute, getMaxColWidth(), getMaxRowHeight(), App::PropertyQuantity::getValue(), App::PropertyBool::getValue(), getViewIndex(), TechDraw::DrawView::LockPosition, makeViewBbs(), TechDraw::MAXPROJECTIONCOUNT, spacingX, spacingY, MovieTool::x, TechDraw::DrawView::X, and MovieTool::y.
Referenced by TechDraw::DrawProjGroupItem::autoPosition().
handleChangedPropertyType()
void DrawProjGroup::handleChangedPropertyType (Base::XMLReader & reader, const char * TypeName, App::Property * prop) override protected virtual
Extends the rules for handling property type changed, so that extensions are given an opportunity to handle it. If an extension handles a change, neither the rest of the extensions, nor the container itself get to handle it.
Extensions get their extensionHandleChangedPropertyType() called.
If no extension handles the request, then the containers handleChangedPropertyType() is called.
Reimplemented from App::ExtensionContainer.
Definition at line 1275 of file DrawProjGroup.cpp.
References App::PropertyFloat::getValue(), TechDraw::DrawView::handleChangedPropertyType(), TechDrawTools.TaskFillTemplateFields::reader, App::PropertyFloat::Restore(), App::PropertyQuantity::setValue(), spacingX, and spacingY.
hasAnchor()
bool DrawProjGroup::hasAnchor ()
Definition at line 1066 of file DrawProjGroup.cpp.
References Anchor, and App::PropertyLink::getValue().
hasProjection()
bool DrawProjGroup::hasProjection (const char * viewProjType) const
Check if container has a view of a specific type.
Definition at line 405 of file DrawProjGroup.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), App::DocumentObject::getNameInDocument(), App::PropertyListsT< T, ListT, ParentT >::getValues(), and TechDraw::DrawViewCollection::Views.
Referenced by addProjection(), removeProjection(), TechDrawGui::TaskProjGroup::setupViewCheckboxes(), and TechDrawGui::TaskProjGroup::viewToggled().
makeViewBbs()
void DrawProjGroup::makeViewBbs (std::array< DrawProjGroupItem *, MAXPROJECTIONCOUNT > & viewPtrs, std::array< Base::BoundBox3d, MAXPROJECTIONCOUNT > & bboxes, bool scaled = true) const protected
Populates array of 10 BoundBox3d's given DrawProjGroupItem *s.
If documentScale is set, then returned bounding boxes are scaled as in the Drawing. Otherwise, the dimensions are as in object space.
Definition at line 924 of file DrawProjGroup.cpp.
References SplineSurface::i, and TechDraw::MAXPROJECTIONCOUNT.
Referenced by getViewArea(), and getXYPosition().
mustExecute()
short DrawProjGroup::mustExecute () const override virtual
mustExecute We call this method to check if the object was modified to be invoked. If the object label or an argument is modified. If we must recompute the object - to call the method execute(). 0: no recomputation is needed 1: recomputation needed
Remarks
If an object is marked as 'touched' then this does not necessarily mean that it will be recomputed. It only means that all objects that link it (i.e. its InList) will be recomputed.
Reimplemented from App::DocumentObject.
Definition at line 205 of file DrawProjGroup.cpp.
References Anchor, AutoDistribute, App::DocumentObject::isRestoring(), App::Property::isTouched(), TechDraw::DrawView::LockPosition, TechDraw::DrawViewCollection::mustExecute(), ProjectionType, TechDraw::DrawView::Scale, TechDraw::DrawView::ScaleType, Source, spacingX, spacingY, TechDraw::DrawViewCollection::Views, and XSource.
onChanged()
void DrawProjGroup::onChanged (const App::Property * prop) override protected virtual
get called by the container when a property was changed
Reimplemented from App::DocumentObject.
Definition at line 106 of file DrawProjGroup.cpp.
References KDL::abs(), TechDraw::DrawUtil::fpCompare(), getPage(), TechDraw::DrawView::getScale(), App::PropertyQuantity::getValue(), App::PropertyFloat::getValue(), App::DocumentObject::isRestoring(), App::PropertyEnumeration::isValue(), TechDraw::DrawView::LockPosition, TechDraw::DrawViewCollection::onChanged(), ProjectionType, App::DocumentObject::purgeTouched(), recomputeChildren(), TechDraw::DrawView::Rotation, TechDraw::DrawView::Scale, TechDraw::DrawPage::Scale, TechDraw::DrawView::ScaleType, App::PropertyQuantity::setValue(), App::PropertyFloat::setValue(), Source, spacingX, spacingY, updateChildrenEnforce(), updateChildrenLock(), updateChildrenScale(), updateChildrenSource(), and XSource.
purgeProjections()
int DrawProjGroup::purgeProjections ()
Definition at line 541 of file DrawProjGroup.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), TechDraw::DrawView::findParentPage(), App::DocumentObject::getNameInDocument(), App::PropertyEnumeration::getValueAsString(), App::PropertyListsT< T, ListT, ParentT >::getValues(), removeProjection(), TechDraw::DrawProjGroupItem::Type, and TechDraw::DrawViewCollection::Views.
Referenced by TechDrawGui::TaskProjGroup::restoreGroupState().
recomputeChildren()
void DrawProjGroup::recomputeChildren ()
Definition at line 947 of file DrawProjGroup.cpp.
References App::PropertyListsT< T, ListT, ParentT >::getValues(), and TechDraw::DrawViewCollection::Views.
Referenced by TechDrawGui::TaskProjGroup::accept(), TechDrawGui::TaskProjGroup::apply(), onChanged(), TechDrawGui::TaskProjGroup::projectionTypeChanged(), and updateSecondaryDirs().
removeProjection()
int DrawProjGroup::removeProjection (const char * viewProjType)
Removes a projection from the group.
Returns
number of projections remaining
Definition at line 509 of file DrawProjGroup.cpp.
References checkViewProjType(), Base::Console(), Base::ConsoleSingleton::Error(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::PropertyListsT< T, ListT, ParentT >::getValues(), hasProjection(), App::Document::removeObject(), TechDraw::DrawViewCollection::removeView(), and TechDraw::DrawViewCollection::Views.
Referenced by purgeProjections(), and TechDrawGui::TaskProjGroup::viewToggled().
reportReady()
void DrawProjGroup::reportReady ()
Definition at line 227 of file DrawProjGroup.cpp.
References AutoDistribute, App::PropertyBool::getValue(), App::DocumentObject::recomputeFeature(), and waitingForChildren().
Referenced by TechDraw::DrawProjGroupItem::postHlrTasks().
rotate()
void DrawProjGroup::rotate (const std::string & rotationdirection)
Definition at line 1193 of file DrawProjGroup.cpp.
References TechDraw::DrawViewPart::Direction, getAnchor(), getDirsFromFront(), App::PropertyVector::setValue(), updateSecondaryDirs(), and TechDraw::DrawViewPart::XDirection.
Referenced by TechDrawGui::TaskProjGroup::rotateButtonClicked().
setAnchorDirection()
void DrawProjGroup::setAnchorDirection (Base::Vector3d dir)
Definition at line 1084 of file DrawProjGroup.cpp.
References Anchor, TechDraw::DrawViewPart::Direction, App::PropertyLink::getValue(), and App::PropertyVector::setValue().
spin() [1/2]
void DrawProjGroup::spin (const std::string & spindirection)
Definition at line 1212 of file DrawProjGroup.cpp.
References M_PI.
Referenced by TechDrawGui::TaskProjGroup::customDirectionClicked(), and TechDrawGui::TaskProjGroup::rotateButtonClicked().
spin() [2/2]
void DrawProjGroup::spin (double angle)
Definition at line 1223 of file DrawProjGroup.cpp.
References TechDraw::DrawViewPart::Direction, getAnchor(), App::PropertyVector::getValue(), TechDraw::DrawProjGroupItem::getXDirection(), App::PropertyVector::setValue(), updateSecondaryDirs(), TechDraw::DrawUtil::vecRotate(), and TechDraw::DrawViewPart::XDirection.
updateChildrenEnforce()
void DrawProjGroup::updateChildrenEnforce ()
Definition at line 1038 of file DrawProjGroup.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), App::DocumentObject::getNameInDocument(), App::PropertyListsT< T, ListT, ParentT >::getValues(), and TechDraw::DrawViewCollection::Views.
Referenced by onChanged().
updateChildrenLock()
void DrawProjGroup::updateChildrenLock () protected
tell children DPGIs that parent DPG has changed LockPosition (really for benefit of QGIV on Gui side)
Definition at line 1023 of file DrawProjGroup.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), App::DocumentObject::getNameInDocument(), App::PropertyListsT< T, ListT, ParentT >::getValues(), and TechDraw::DrawViewCollection::Views.
Referenced by onChanged().
updateChildrenScale()
void DrawProjGroup::updateChildrenScale ()
tell children DPGIs that parent DPG has changed Scale
Definition at line 980 of file DrawProjGroup.cpp.
References TechDraw::DrawView::getScale(), App::PropertyListsT< T, ListT, ParentT >::getValues(), and TechDraw::DrawViewCollection::Views.
Referenced by onChanged().
updateChildrenSource()
void DrawProjGroup::updateChildrenSource () protected
tell children DPGIs that parent DPG has changed Source
Definition at line 999 of file DrawProjGroup.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), App::DocumentObject::getNameInDocument(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::PropertyXLinkSubList::getValues(), Source, TechDraw::DrawViewCollection::Views, and XSource.
Referenced by onChanged().
updateSecondaryDirs()
void DrawProjGroup::updateSecondaryDirs ()
Definition at line 1107 of file DrawProjGroup.cpp.
References TechDraw::Bottom, Base::Console(), TechDraw::DrawViewPart::Direction, TechDraw::Front, TechDraw::FrontBottomLeft, TechDraw::FrontBottomRight, TechDraw::FrontTopLeft, TechDraw::FrontTopRight, getAnchor(), getDirsFromFront(), App::PropertyVector::getValue(), App::PropertyListsT< T, ListT, ParentT >::getValues(), TechDraw::DrawProjGroupItem::getXDirection(), TechDraw::Left, Base::ConsoleSingleton::Message(), TechDraw::Rear, recomputeChildren(), TechDraw::Right, InitGui::t, TechDraw::Top, Path.Post.scripts.grbl_post::type, TestSpreadsheet::v, and TechDraw::DrawViewCollection::Views.
Referenced by rotate(), TechDrawGui::TaskProjGroup::rotateButtonClicked(), and spin().
usedProjectionType()
App::Enumeration DrawProjGroup::usedProjectionType ()
Determines either "First Angle" or "Third Angle".
Definition at line 1053 of file DrawProjGroup.cpp.
References getPage(), App::PropertyEnumeration::getValueAsString(), App::Enumeration::isValue(), ProjectionType, TechDraw::DrawPage::ProjectionType, ProjectionTypeEnums, and App::Enumeration::setValue().
Referenced by TechDrawGui::TaskProjGroup::useThirdAngle().
vec2dir()
gp_Dir DrawProjGroup::vec2dir (Base::Vector3d v) protected
Definition at line 593 of file DrawProjGroup.cpp.
References TestSpreadsheet::v.
waitingForChildren()
bool DrawProjGroup::waitingForChildren () const
Definition at line 240 of file DrawProjGroup.cpp.
References App::PropertyListsT< T, ListT, ParentT >::getValues(), App::DocumentObject::isTouched(), TestSpreadsheet::v, TechDraw::DrawViewCollection::Views, and TechDraw::DrawViewPart::waitingForHlr().
Referenced by checkFit(), execute(), and reportReady().
Member Data Documentation
Anchor
App::PropertyLink TechDraw::DrawProjGroup::Anchor
Definition at line 72 of file DrawProjGroup.h.
Referenced by addProjection(), execute(), getAnchor(), getAnchorDirection(), TechDrawGui::QGIProjGroup::getAnchorQItem(), hasAnchor(), mustExecute(), setAnchorDirection(), TechDrawGui::TaskProjGroup::turnViewToProjGroup(), and TechDraw::DrawProjGroupItem::unsetupObject().
AutoDistribute
App::PropertyBool TechDraw::DrawProjGroup::AutoDistribute
Whether projcetion group view are automatically distributed or not.
Definition at line 66 of file DrawProjGroup.h.
Referenced by TechDrawGui::TaskProjGroup::AutoDistributeClicked(), TechDraw::DrawProjGroupItem::autoPosition(), execute(), getXYPosition(), TechDrawGui::TaskProjGroup::initializeUi(), mustExecute(), reportReady(), TechDrawGui::TaskProjGroup::restoreGroupState(), and TechDrawGui::TaskProjGroup::saveGroupState().
ProjectionType
App::PropertyEnumeration TechDraw::DrawProjGroup::ProjectionType
Definition at line 63 of file DrawProjGroup.h.
Referenced by arrangeViewPointers(), getViewIndex(), TechDrawGui::TaskProjGroup::initializeUi(), mustExecute(), onChanged(), TechDraw::DrawPage::onChanged(), TechDrawGui::TaskProjGroup::projectionTypeChanged(), TechDrawGui::TaskProjGroup::restoreGroupState(), TechDrawGui::TaskProjGroup::saveGroupState(), TechDrawGui::TaskProjGroup::turnViewToProjGroup(), and usedProjectionType().
ProjectionTypeEnums
const char * DrawProjGroup::ProjectionTypeEnums static
Initial value:
= {"First Angle", "Third Angle",
                                                    "Default",
                                                    nullptr}
Allowed projection types - either Document, First Angle or Third Angle.
Definition at line 119 of file DrawProjGroup.h.
Referenced by arrangeViewPointers(), getViewIndex(), and usedProjectionType().
Source
App::PropertyLinkList TechDraw::DrawProjGroup::Source
Definition at line 60 of file DrawProjGroup.h.
Referenced by addProjection(), getAllSources(), mustExecute(), onChanged(), TechDrawGui::TaskProjGroup::saveGroupState(), TechDrawGui::TaskProjGroup::turnViewToProjGroup(), and updateChildrenSource().
spacingX
App::PropertyLength TechDraw::DrawProjGroup::spacingX
Default horizontal spacing between adjacent views on Drawing, in mm.
Definition at line 68 of file DrawProjGroup.h.
Referenced by getRect(), getXYPosition(), handleChangedPropertyType(), TechDrawGui::TaskProjGroup::initializeUi(), mustExecute(), onChanged(), TechDrawGui::TaskProjGroup::restoreGroupState(), TechDrawGui::TaskProjGroup::saveGroupState(), and TechDrawGui::TaskProjGroup::spacingChanged().
spacingY
App::PropertyLength TechDraw::DrawProjGroup::spacingY
Default vertical spacing between adjacent views on Drawing, in mm.
Definition at line 70 of file DrawProjGroup.h.
Referenced by getRect(), getXYPosition(), handleChangedPropertyType(), TechDrawGui::TaskProjGroup::initializeUi(), mustExecute(), onChanged(), TechDrawGui::TaskProjGroup::restoreGroupState(), TechDrawGui::TaskProjGroup::saveGroupState(), and TechDrawGui::TaskProjGroup::spacingChanged().
XSource
App::PropertyXLinkList TechDraw::DrawProjGroup::XSource
Definition at line 61 of file DrawProjGroup.h.
Referenced by addProjection(), getAllSources(), mustExecute(), onChanged(), TechDrawGui::TaskProjGroup::turnViewToProjGroup(), and updateChildrenSource().
The documentation for this class was generated from the following files:
DrawProjGroup.h
DrawProjGroup.cpp