FreeCAD: MeshGui::SoFCMeshPickNode Class Reference
MeshGui::SoFCMeshPickNode Class Reference
#include <SoFCMeshObject.h>
Public Member Functions
SoFCMeshPickNode ()
void notify (SoNotList *) override
void rayPick (SoRayPickAction *action) override
void pick (SoPickAction *action) override
Static Public Member Functions
static void initClass ()
Public Attributes
SoSFMeshObject mesh
Protected Member Functions
~SoFCMeshPickNode () override
Detailed Description
Definition at line 88 of file SoFCMeshObject.h.
Constructor & Destructor Documentation
SoFCMeshPickNode()
SoFCMeshPickNode::SoFCMeshPickNode ()
Constructor.
Definition at line 351 of file SoFCMeshObject.cpp.
References Mesh2Shape::mesh.
~SoFCMeshPickNode()
SoFCMeshPickNode::~SoFCMeshPickNode () override protected
Destructor.
Definition at line 361 of file SoFCMeshObject.cpp.
Member Function Documentation
initClass()
void SoFCMeshPickNode::initClass () static
Definition at line 367 of file SoFCMeshObject.cpp.
Referenced by PyMOD_INIT_FUNC().
notify()
void SoFCMeshPickNode::notify (SoNotList * list) override
Definition at line 372 of file SoFCMeshObject.cpp.
References SCL.SimpleDataTypes::f, MeshCore::MeshAlgorithm::GetAverageEdgeLength(), Mesh::MeshObject::getKernel(), and mesh.
pick()
void SoFCMeshPickNode::pick (SoPickAction * action) override
Definition at line 391 of file SoFCMeshObject.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Mesh::MeshObject::getKernel(), mesh, MeshCore::MeshAlgorithm::NearestFacetOnRay(), RobotExample::pos, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
rayPick()
void SoFCMeshPickNode::rayPick (SoRayPickAction * action) override
Definition at line 387 of file SoFCMeshObject.cpp.
Member Data Documentation
mesh
SoSFMeshObject MeshGui::SoFCMeshPickNode::mesh
Definition at line 99 of file SoFCMeshObject.h.
Referenced by MeshGui::ViewProviderFace::attach(), notify(), pick(), and MengerSponge.MengerThread::run().
The documentation for this class was generated from the following files:
SoFCMeshObject.h
SoFCMeshObject.cpp