FreeCAD: Part::AttachExtension Class Reference
Part::AttachExtension Class Reference
The AttachableObject class is the thing to extend an object with that should be attachable. It includes the required properties, and shortcuts for accessing the attachment math class.
#include <AttachExtension.h>
Classes
struct Properties
Public Member Functions
AttachExtension ()
~AttachExtension () override
virtual void setAttacher (Attacher::AttachEngine *attacher, bool base=false)
setAttacher sets the AttachEngine object. The class takes the ownership of the pointer, it will be deleted when the class is destroyed, or when a new attacher is set. The default attacher is AttachEngine3D.
bool changeAttacherType (const char *typeName, bool base=false)
changeAttacherType
Attacher::AttachEngine & attacher (bool base=false) const
virtual bool positionBySupport ()
bool isAttacherActive () const
virtual bool isTouched_Mapping ()
short int extensionMustExecute () override
App::DocumentObjectExecReturn * extensionExecute () override
PyObject * getExtensionPyObject () override
void onExtendedDocumentRestored () override
get called after a document has been fully restored
Properties getProperties (bool base) const
Properties getInitedProperties (bool base)
void updateAttacherVals (bool base=false) const
void updatePropertyStatus (bool attached, bool base=false)
void updateSinglePropertyStatus (bool attached, bool base=false)
Public Member Functions inherited from App::DocumentObjectExtension
virtual Base::Type getExtensionTypeId (void) const override
DocumentObjectExtension ()
~DocumentObjectExtension () override
App::DocumentObject * getExtendedObject ()
const App::DocumentObject * getExtendedObject () const
virtual void onExtendedSettingDocument ()
get called after setting the document
virtual void onExtendedSetupObject ()
get called after a brand new object was created
virtual void onExtendedUnsetupObject ()
get called when object is going to be removed from the document
virtual const char * getViewProviderExtensionName () const
virtual bool extensionGetSubObject (DocumentObject *&ret, const char *subname, PyObject **pyObj, Base::Matrix4D *mat, bool transform, int depth) const
virtual bool extensionGetSubObjects (std::vector< std::string > &ret, int reason) const
virtual bool extensionGetLinkedObject (DocumentObject *&ret, bool recursive, Base::Matrix4D *mat, bool transform, int depth) const
virtual int extensionSetElementVisible (const char *, bool)
virtual int extensionIsElementVisible (const char *)
virtual bool extensionHasChildElement () const
Public Member Functions inherited from App::Extension
Extension ()=default
virtual ~Extension ()
virtual void initExtension (App::ExtensionContainer *obj)
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Public Attributes
App::PropertyString AttacherType
App::PropertyEnumeration AttacherEngine
App::PropertyLinkSubList AttachmentSupport
App::PropertyEnumeration MapMode
App::PropertyBool MapReversed
App::PropertyPlacement AttachmentOffset
App::PropertyFloat MapPathParameter
MapPathParameter is a parameter value for mmNormalToPath (the sketch will be mapped normal to a curve at point specified by parameter (from 0.0 to 1.0, from start to end))
Protected Member Functions
void extensionOnChanged (const App::Property *) override
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
returns true if the property name change was handled by the extension.
App::PropertyPlacement & getPlacement () const
void initBase (bool force)
Protected Member Functions inherited from App::DocumentObjectExtension
virtual const App::PropertyData & extensionGetPropertyData (void) const override
Protected Member Functions inherited from App::Extension
virtual bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
returns true if the property type change was handled by the extension.
void initExtensionType (Base::Type type)
Additional Inherited Members
Static Public Member Functions inherited from App::DocumentObjectExtension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Static Public Member Functions inherited from App::Extension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Static Protected Member Functions inherited from App::DocumentObjectExtension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
Static Protected Member Functions inherited from App::Extension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Detailed Description
The AttachableObject class is the thing to extend an object with that should be attachable. It includes the required properties, and shortcuts for accessing the attachment math class.
Definition at line 80 of file AttachExtension.h.
Constructor & Destructor Documentation
AttachExtension()
AttachExtension::AttachExtension ()
Definition at line 90 of file AttachExtension.cpp.
References EXTENSION_ADD_PROPERTY_TYPE, App::DocumentObjectExtension::getExtensionClassTypeId(), App::Global, Attacher::mmDeactivated, Attacher::mmDummy_NumberOfModes, App::Prop_Hidden, App::Prop_None, and App::Prop_ReadOnly.
~AttachExtension()
AttachExtension::~AttachExtension () override
Definition at line 160 of file AttachExtension.cpp.
Member Function Documentation
attacher()
Attacher::AttachEngine & AttachExtension::attacher (bool base = false) const
Definition at line 595 of file AttachExtension.cpp.
Referenced by UnifiedDatumCommand().
changeAttacherType()
bool AttachExtension::changeAttacherType (const char * typeName, bool base = false)
changeAttacherType
Parameters
typeName is the typename of new attacher class. Must be derived from Attacher::AttachEngine.
Returns
true if attacher was changed. false if attacher is already of the type requested. Throws if invalid type is supplied.
Definition at line 274 of file AttachExtension.cpp.
References Base::Type::createInstanceByName(), Base::Type::fromName(), and InitGui::t.
extensionExecute()
App::DocumentObjectExecReturn * AttachExtension::extensionExecute () override virtual
Reimplemented from App::DocumentObjectExtension.
Definition at line 382 of file AttachExtension.cpp.
References SCL.SimpleDataTypes::e, and App::DocumentObjectExtension::extensionExecute().
extensionHandleChangedPropertyName()
bool AttachExtension::extensionHandleChangedPropertyName (Base::XMLReader & reader, const char * TypeName, const char * PropName) override protected virtual
returns true if the property name change was handled by the extension.
Reimplemented from App::Extension.
Definition at line 451 of file AttachExtension.cpp.
References App::Extension::extensionHandleChangedPropertyName(), Base::Type::fromName(), Base::Type::getName(), App::PropertyLinkSub::getSubValues(), Base::Persistence::getTypeId(), App::PropertyLinkSub::getValue(), Attacher::mmFlatFace, TechDrawTools.TaskFillTemplateFields::reader, App::PropertyLinkSub::Restore(), App::Property::setContainer(), and Path.Post.scripts.grbl_post::type.
extensionMustExecute()
short int AttachExtension::extensionMustExecute () override virtual
Reimplemented from App::DocumentObjectExtension.
Definition at line 376 of file AttachExtension.cpp.
extensionOnChanged()
void AttachExtension::extensionOnChanged (const App::Property * prop) override protected virtual
Reimplemented from App::Extension.
Definition at line 401 of file AttachExtension.cpp.
References Base::Console(), SCL.SimpleDataTypes::e, App::Error, Base::ConsoleSingleton::Error(), App::Extension::extensionOnChanged(), and Gui::isRestoring.
getExtensionPyObject()
PyObject * AttachExtension::getExtensionPyObject () override virtual
Reimplemented from App::DocumentObjectExtension.
Definition at line 584 of file AttachExtension.cpp.
References Py::new_reference_to().
getInitedProperties()
AttachExtension::Properties AttachExtension::getInitedProperties (bool base)
Definition at line 565 of file AttachExtension.cpp.
getPlacement()
App::PropertyPlacement & AttachExtension::getPlacement () const protected
Definition at line 574 of file AttachExtension.cpp.
getProperties()
AttachExtension::Properties AttachExtension::getProperties (bool base) const
Definition at line 560 of file AttachExtension.cpp.
initBase()
void AttachExtension::initBase (bool force) protected
Definition at line 191 of file AttachExtension.cpp.
References Part::AttachExtension::Properties::attacherType, Part::AttachExtension::Properties::attachment, Base::Persistence::getClassTypeId(), Part::AttachExtension::Properties::mapMode, Part::AttachExtension::Properties::mapPathParameter, Part::AttachExtension::Properties::mapReversed, App::PropertyEnumeration::setEditorName(), App::PropertyEnumeration::setEnums(), App::Property::setStatus(), and App::PropertyString::setValue().
isAttacherActive()
bool AttachExtension::isAttacherActive () const
Return whether this attacher is active
Definition at line 360 of file AttachExtension.cpp.
References importers.importIFCHelper::getPlacement(), and getValue().
isTouched_Mapping()
virtual bool Part::AttachExtension::isTouched_Mapping () inline virtual
Definition at line 131 of file AttachExtension.h.
onExtendedDocumentRestored()
void AttachExtension::onExtendedDocumentRestored () override virtual
get called after a document has been fully restored
Reimplemented from App::DocumentObjectExtension.
Definition at line 481 of file AttachExtension.cpp.
References App::Hidden.
positionBySupport()
bool AttachExtension::positionBySupport () virtual
calculate and update the Placement property based on the Support, and mode. Can throw FreeCAD and OCC exceptions. Returns true if attached, false if not, throws if attachment failed.
Definition at line 304 of file AttachExtension.cpp.
References importers.importIFCHelper::getPlacement(), Base::Placement::inverse(), Attacher::mmDeactivated, and App::Property::User3.
Referenced by Part::Part2DObject::transformPlacement().
setAttacher()
void AttachExtension::setAttacher (Attacher::AttachEngine * attacher, bool base = false) virtual
setAttacher sets the AttachEngine object. The class takes the ownership of the pointer, it will be deleted when the class is destroyed, or when a new attacher is set. The default attacher is AttachEngine3D.
Parameters
attacher. AttachableObject takes ownership and will delete it eventually.
Definition at line 248 of file AttachExtension.cpp.
updateAttacherVals()
void AttachExtension::updateAttacherVals (bool base = false) const
Definition at line 546 of file AttachExtension.cpp.
updatePropertyStatus()
void AttachExtension::updatePropertyStatus (bool attached, bool base = false)
Definition at line 537 of file AttachExtension.cpp.
updateSinglePropertyStatus()
void AttachExtension::updateSinglePropertyStatus (bool attached, bool base = false)
Definition at line 506 of file AttachExtension.cpp.
References importers.importIFCHelper::getPlacement(), Attacher::mmConcentric, Attacher::mmFrenetNB, Attacher::mmFrenetTB, Attacher::mmFrenetTN, Attacher::mmNormalToPath, Attacher::mmRevolutionSection, and Attacher::mmTranslate.
Member Data Documentation
AttacherEngine
App::PropertyEnumeration Part::AttachExtension::AttacherEngine
Definition at line 108 of file AttachExtension.h.
AttacherType
App::PropertyString Part::AttachExtension::AttacherType
Definition at line 107 of file AttachExtension.h.
AttachmentOffset
App::PropertyPlacement Part::AttachExtension::AttachmentOffset
Definition at line 112 of file AttachExtension.h.
Referenced by PartGui::TaskDlgAttacher::accept(), and PartDesign::FeaturePrimitive::onChanged().
AttachmentSupport
App::PropertyLinkSubList Part::AttachExtension::AttachmentSupport
Definition at line 109 of file AttachExtension.h.
Referenced by PartDesignGui::TaskDlgDatumParameters::accept(), PartGui::TaskDlgAttacher::accept(), PartDesignGui::fixSketchSupport(), PartDesign::ProfileBased::getBaseObject(), PartDesign::ProfileBased::getSupportFace(), PartDesign::ProfileBased::getTopoShapeSupportFace(), PartDesignGui::TaskFeaturePick::makeCopy(), PartDesign::ProfileBased::positionByPrevious(), SketcherGui::SketchSelection::setUp(), PartGui::TaskAttacher::TaskAttacher(), and Part::Part2DObject::transformPlacement().
MapMode
App::PropertyEnumeration Part::AttachExtension::MapMode
Definition at line 110 of file AttachExtension.h.
Referenced by PartGui::TaskDlgAttacher::accept(), Assembly::AssemblyObject::getGroundedParts(), PartDesign::ProfileBased::getSupportFace(), PartDesign::ProfileBased::getTopoShapeSupportFace(), PartDesignGui::TaskFeaturePick::makeCopy(), and PartGui::TaskAttacher::TaskAttacher().
MapPathParameter
App::PropertyFloat Part::AttachExtension::MapPathParameter
MapPathParameter is a parameter value for mmNormalToPath (the sketch will be mapped normal to a curve at point specified by parameter (from 0.0 to 1.0, from start to end))
Definition at line 119 of file AttachExtension.h.
Referenced by PartGui::TaskDlgAttacher::accept().
MapReversed
App::PropertyBool Part::AttachExtension::MapReversed
Definition at line 111 of file AttachExtension.h.
Referenced by PartGui::TaskDlgAttacher::accept(), and PartGui::TaskAttacher::TaskAttacher().
The documentation for this class was generated from the following files:
AttachExtension.h
AttachExtension.cpp