FreeCAD: Base::PyObjectBase Class Reference
Base::PyObjectBase Class Reference
#include <PyObjectBase.h>
Public Types
enum Status { Valid = 0, Immutable = 1, Notify = 2, NoTrack = 3 }
using PointerType = void *
Public Member Functions
virtual PyTypeObject * GetType (void)
PyObjectBase (void *, PyTypeObject *T)
PyObjectBase * IncRef ()
incref method wrapper (see python extending manual)
PyObjectBase * DecRef ()
decref method wrapper (see python extending manual)
void * getTwinPointer () const
Get the pointer of the twin object.
virtual PyObject * _getattr (const char *attr)
virtual int _setattr (const char *attro, PyObject *value)
virtual PyObject * _repr ()
virtual int PyInit (PyObject *, PyObject *)
void setInvalid ()
bool isValid ()
void setConst ()
bool isConst ()
void setShouldNotify (bool on)
bool shouldNotify () const
void startNotify ()
void setNotTracking (bool on=true)
bool isNotTracking () const
Static Public Member Functions
static void PyDestructor (PyObject *P)
Wrapper for the Python destructor.
static PyObject * __getattro (PyObject *PyObj, PyObject *attro)
static wrapper for pythons _getattro()
static int __setattro (PyObject *PyObj, PyObject *attro, PyObject *value)
static wrapper for pythons _setattro(). // This should be the entry in Type.
static PyObject * __repr (PyObject *PyObj)
python wrapper for the _repr() function
static int __PyInit (PyObject *self, PyObject *args, PyObject *kwd)
python wrapper for the _repr() function
Public Attributes
PyObject * baseProxy {nullptr}
Static Public Attributes
static PyTypeObject Type
static PyMethodDef Methods []
Protected Member Functions
virtual ~PyObjectBase ()
destructor
void setTwinPointer (void *ptr)
Overrides the pointer to the twin object.
Protected Attributes
std::bitset< 32 > StatusBits
void * _pcTwinPointer
pointer to the handled class
Detailed Description
The PyObjectBase class, exports the class as a python type PyObjectBase is the base class for all C++ classes which need to get exported into the python namespace. This class is very important because nearly all important classes in FreeCAD are visible in python for macro recording and automation purpose. The class App::Document is a good expample for an exported class. There are some convenience macros to make it easier to inherit from this class and defining new methods exported to python. PYFUNCDEF_D defines a new exported method. PYFUNCIMP_D defines the implementation of the new exported method. In the implementation you can use Py_Return, Py_Error, Py_Try and Py_Assert. PYMETHODEDEF makes the entry in the python method table.
See also
Document
PYFUNCDEF_D
PYFUNCIMP_D
PYMETHODEDEF
Py_Return
Py_Error
Py_Try
Py_Assert
Definition at line 187 of file PyObjectBase.h.
Member Typedef Documentation
PointerType
using Base::PyObjectBase::PointerType = void*
Definition at line 329 of file PyObjectBase.h.
Member Enumeration Documentation
Status
enum Base::PyObjectBase::Status
Enumerator
Valid
Immutable
Notify
NoTrack
Definition at line 195 of file PyObjectBase.h.
Constructor & Destructor Documentation
~PyObjectBase()
PyObjectBase::~PyObjectBase () protected virtual
destructor
Definition at line 78 of file PyObjectBase.cpp.
References baseProxy, Base::Console(), and Base::ConsoleSingleton::Log().
PyObjectBase()
PyObjectBase::PyObjectBase (void * voidp, PyTypeObject * T)
Constructor Sets the Type of the object (for inheritance) and decrease the the reference count of the PyObject.
Definition at line 61 of file PyObjectBase.cpp.
References Base::Console(), Base::ConsoleSingleton::Log(), Notify, StatusBits, and Valid.
Member Function Documentation
__getattro()
PyObject * PyObjectBase::__getattro (PyObject * PyObj, PyObject * attro) static
static wrapper for pythons _getattro()
Definition at line 299 of file PyObjectBase.cpp.
References _getattr(), isConst(), isNotTracking(), isValid(), Base::streq(), and Type.
__PyInit()
static int Base::PyObjectBase::__PyInit (PyObject * self, PyObject * args, PyObject * kwd) inline static
python wrapper for the _repr() function
Definition at line 286 of file PyObjectBase.h.
References toolbit-attributes::args.
__repr()
static PyObject* Base::PyObjectBase::__repr (PyObject * PyObj) inline static
python wrapper for the _repr() function
Definition at line 269 of file PyObjectBase.h.
References femsolver.elmer.sifio::isValid().
__setattro()
int PyObjectBase::__setattro (PyObject * PyObj, PyObject * attro, PyObject * value) static
static wrapper for pythons _setattro(). // This should be the entry in Type.
Definition at line 365 of file PyObjectBase.cpp.
References _setattr(), isValid(), startNotify(), and Type.
Referenced by startNotify().
_getattr()
PyObject * PyObjectBase::_getattr (const char * attr) virtual
GetAttribute implementation This method implements the retrieval of object attributes. If you want to implement attributes in your class, reimplement this method. You have to call the method of the base class. Note: if you reimplement _gettattr() in a inheriting class you need to call the method of the base class! Otherwise even the methods of the object will disappear!
Definition at line 406 of file PyObjectBase.cpp.
References Base::streq(), and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by __getattro().
_repr()
PyObject * PyObjectBase::_repr () virtual
_repr method Override this method to return a string object with some information about the object.
PyObject *MeshFeaturePy::_repr(void)
{
  std::stringstream a;
  a << "MeshFeature: [ ";
  a << "some really important info about the object!";
  a << "]" << std::endl;
  return Py_BuildValue("s", a.str().c_str());
}
Definition at line 466 of file PyObjectBase.cpp.
References _pcTwinPointer, a, Base::Console(), and Base::ConsoleSingleton::Log().
_setattr()
int PyObjectBase::_setattr (const char * attro, PyObject * value) virtual
SetAttribute implementation This method implements the setting of object attributes. If you want to implement attributes in your class, reimplement this method. You have to call the method of the base class.
Definition at line 443 of file PyObjectBase.cpp.
References Base::streq(), and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by __setattro().
DecRef()
PyObjectBase* Base::PyObjectBase::DecRef () inline
decref method wrapper (see python extending manual)
Definition at line 223 of file PyObjectBase.h.
Referenced by Gui::PythonBaseWorkbench::~PythonBaseWorkbench().
getTwinPointer()
void* Base::PyObjectBase::getTwinPointer () const inline
Get the pointer of the twin object.
Definition at line 226 of file PyObjectBase.h.
GetType()
virtual PyTypeObject* Base::PyObjectBase::GetType (void) inline virtual
Definition at line 193 of file PyObjectBase.h.
IncRef()
PyObjectBase* Base::PyObjectBase::IncRef () inline
incref method wrapper (see python extending manual)
Definition at line 221 of file PyObjectBase.h.
Referenced by Gui::PythonBaseWorkbench::getPyObject().
isConst()
bool Base::PyObjectBase::isConst () inline
Definition at line 307 of file PyObjectBase.h.
Referenced by __getattro().
isNotTracking()
bool Base::PyObjectBase::isNotTracking () const inline
Definition at line 325 of file PyObjectBase.h.
Referenced by __getattro().
isValid()
bool Base::PyObjectBase::isValid () inline
Definition at line 298 of file PyObjectBase.h.
Referenced by __getattro(), and __setattro().
PyDestructor()
static void Base::PyObjectBase::PyDestructor (PyObject * P) inline static
Wrapper for the Python destructor.
Definition at line 218 of file PyObjectBase.h.
PyInit()
virtual int Base::PyObjectBase::PyInit (PyObject * , PyObject *) inline virtual
PyInit method Override this method to initialize a newly created instance of the class (Constructor)
Definition at line 281 of file PyObjectBase.h.
setConst()
void Base::PyObjectBase::setConst () inline
Definition at line 302 of file PyObjectBase.h.
Referenced by Part::PropertyPartShape::getPyObject().
setInvalid()
void Base::PyObjectBase::setInvalid () inline
Definition at line 291 of file PyObjectBase.h.
Referenced by Gui::LinkView::setInvalid(), App::Extension::~Extension(), and Gui::PythonBaseWorkbench::~PythonBaseWorkbench().
setNotTracking()
void Base::PyObjectBase::setNotTracking (bool on = true) inline
Definition at line 321 of file PyObjectBase.h.
Referenced by Part::TopoShape::getPyObject().
setShouldNotify()
void Base::PyObjectBase::setShouldNotify (bool on) inline
Definition at line 311 of file PyObjectBase.h.
References Gui::Notify().
setTwinPointer()
void Base::PyObjectBase::setTwinPointer (void * ptr) inline protected
Overrides the pointer to the twin object.
Definition at line 207 of file PyObjectBase.h.
shouldNotify()
bool Base::PyObjectBase::shouldNotify () const inline
Definition at line 315 of file PyObjectBase.h.
References Gui::Notify().
Referenced by startNotify().
startNotify()
void PyObjectBase::startNotify ()
Definition at line 514 of file PyObjectBase.cpp.
References __setattro(), Init::parent, and shouldNotify().
Referenced by __setattro().
Member Data Documentation
_pcTwinPointer
void* Base::PyObjectBase::_pcTwinPointer protected
pointer to the handled class
Definition at line 342 of file PyObjectBase.h.
Referenced by _repr().
baseProxy
PyObject* Base::PyObjectBase::baseProxy {nullptr}
Definition at line 345 of file PyObjectBase.h.
Referenced by createWeakRef(), and ~PyObjectBase().
Methods
PyMethodDef PyObjectBase::Methods static
Initial value:
= {
    {nullptr, nullptr, 0, nullptr}
}
Definition at line 193 of file PyObjectBase.h.
StatusBits
std::bitset<32> Base::PyObjectBase::StatusBits protected
Definition at line 340 of file PyObjectBase.h.
Referenced by PyObjectBase().
Type
PyTypeObject PyObjectBase::Type static
Py_Header struct from python.h. Every PyObjectBase object is also a python object. So you can use every Python C-Library function also on a PyObjectBase object
Definition at line 193 of file PyObjectBase.h.
Referenced by __getattro(), femobjects.result_mechanical.ResultMechanical::__init__(), __setattro(), draftobjects.wpproxy.WorkingPlaneProxy::dumps(), draftobjects.base.DraftObject::dumps(), draftobjects.layer.Layer::dumps(), draftobjects.layer.LayerContainer::dumps(), ArchComponent.Component::dumps(), ArchMaterial._ArchMaterial::dumps(), ArchSchedule._ArchSchedule::dumps(), ArchMaterial._ArchMultiMaterial::dumps(), ArchMaterial._ArchMaterialContainer::loads(), draftobjects.wpproxy.WorkingPlaneProxy::loads(), draftobjects.text.Text::loads(), draftobjects.base.DraftObject::loads(), draftobjects.layer.Layer::loads(), nativeifc.ifc_objects.ifc_object::loads(), draftobjects.layer.LayerContainer::loads(), ArchMaterial._ArchMaterial::loads(), ArchSchedule._ArchSchedule::loads(), ArchMaterial._ArchMultiMaterial::loads(), draftobjects.layer.Layer::onDocumentRestored(), draftobjects.text.Text::onDocumentRestored(), draftobjects.label.Label::onDocumentRestored(), draftobjects.dimension.LinearDimension::onDocumentRestored(), draftobjects.dimension.AngularDimension::onDocumentRestored(), and ArchReference.ArchReference::setProperties().
The documentation for this class was generated from the following files:
PyObjectBase.h
PyObjectBase.cpp