FreeCAD: draftobjects.wire.Wire Class Reference
draftobjects.wire.Wire Class Reference
DRAFT » draftobjects
Public Member Functions
def __init__ (self, obj)
def onDocumentRestored (self, obj)
def execute (self, obj)
def onChanged (self, obj, prop)
def update_start_end (self, obj)
Public Member Functions inherited from draftobjects.base.DraftObject
def __init__ (self, obj, tp="Unknown")
def dumps (self)
def loads (self, state)
def props_changed_store (self, prop)
def props_changed_clear (self)
def props_changed_placement_only (self, obj=None)
Additional Inherited Members
Public Attributes inherited from draftobjects.base.DraftObject
Type
props_changed
Detailed Description
The Wire object
Definition at line 41 of file wire.py.
Constructor & Destructor Documentation
__init__()
def draftobjects.wire.Wire.__init__ (self, obj)
Definition at line 44 of file wire.py.
References Arch.QT_TRANSLATE_NOOP.
Member Function Documentation
execute()
def draftobjects.wire.Wire.execute (self, obj)
Run this method when the object is created or recomputed.
Override this method to produce effects when the object
is newly created, and whenever the document is recomputed.
By default it does nothing.
Parameters
----------
obj : the scripted object.
    This commonly may be of types `Part::Part2DObjectPython`,
    `Part::FeaturePython`, or `App::FeaturePython`.
Reimplemented from draftobjects.base.DraftObject.
Definition at line 102 of file wire.py.
References DraftVecUtils.equals(), draftobjects.base.DraftObject.props_changed_clear(), draftobjects.base.DraftObject.props_changed_placement_only(), DraftVecUtils.scaleTo(), and draftobjects.wire.Wire.update_start_end().
Referenced by src.Mod.PartDesign.Scripts.Spring.MySpring.onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped.onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder.onChanged(), MeasureCOM.MeasureCOM.onChanged(), and FeaturePython.DistanceBolt.onChanged().
onChanged()
def draftobjects.wire.Wire.onChanged (self, obj, prop)
Run this method when a property is changed.
Override this method to handle the behavior
of the object depending on changes that occur to its properties.
By default it does nothing.
Parameters
----------
obj : the scripted object.
    This commonly may be of types `Part::Part2DObjectPython`,
    `Part::FeaturePython`, or `App::FeaturePython`.
prop : str
    Name of the property that was modified.
Reimplemented from draftobjects.base.DraftObject.
Definition at line 211 of file wire.py.
References KDL.abs(), draftobjects.base.DraftObject.props_changed_store(), and DraftVecUtils.scaleTo().
Referenced by draftviewproviders.view_base.ViewProviderDraft.attach(), draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy.updateData(), draftviewproviders.view_layer.ViewProviderLayer.updateData(), draftviewproviders.view_label.ViewProviderLabel.updateData(), and draftviewproviders.view_dimension.ViewProviderLinearDimension.updateData().
onDocumentRestored()
def draftobjects.wire.Wire.onDocumentRestored (self, obj)
Reimplemented from draftobjects.base.DraftObject.
Definition at line 98 of file wire.py.
update_start_end()
def draftobjects.wire.Wire.update_start_end (self, obj)
Definition at line 243 of file wire.py.
Referenced by draftobjects.wire.Wire.execute().
The documentation for this class was generated from the following file:
wire.py