FreeCAD: Gui::AccelLineEdit Class Reference
Gui::AccelLineEdit Class Reference
#include <Widgets.h>
Public Member Functions
AccelLineEdit (QWidget *parent=nullptr)
bool isNone () const
Protected Member Functions
void keyPressEvent (QKeyEvent *e) override
Detailed Description
The AccelLineEdit class provides a lineedit to specify shortcuts.
Author
Werner Mayer
Definition at line 135 of file Widgets.h.
Constructor & Destructor Documentation
AccelLineEdit()
AccelLineEdit::AccelLineEdit (QWidget * parent = nullptr)
Constructs a line edit with no text. The parent argument is sent to the QLineEdit constructor.
Definition at line 363 of file Widgets.cpp.
Member Function Documentation
isNone()
bool AccelLineEdit::isNone () const
Definition at line 371 of file Widgets.cpp.
Referenced by keyPressEvent(), and Gui::Dialog::DlgCustomKeyboardImp::populatePriorityList().
keyPressEvent()
void AccelLineEdit::keyPressEvent (QKeyEvent * e) override protected
Checks which keys are pressed and show it as text.
Definition at line 379 of file Widgets.cpp.
References Path.Op.Gui.Selection::clear(), SCL.SimpleDataTypes::e, and isNone().
The documentation for this class was generated from the following files:
Widgets.h
Widgets.cpp