FreeCAD: ApproxSurface.cpp File Reference
ApproxSurface.cpp File Reference
#include "PreCompiled.h"
#include <QFuture>
#include <QFutureWatcher>
#include <QtConcurrentMap>
#include <Geom_BSplineSurface.hxx>
#include <Precision.hxx>
#include <math_Gauss.hxx>
#include <math_Householder.hxx>
#include <Base/Sequencer.h>
#include <Base/Tools.h>
#include <Mod/Mesh/App/Core/Approximation.h>
#include "ApproxSurface.h"
Classes
class Reen::ScalarProduct
Namespaces
Reen
Functions
Handle (Geom_BSplineSurface) ParameterCorrection
Function Documentation
Handle()
Handle (Geom_BSplineSurface)
Definition at line 811 of file ApproxSurface.cpp.
References Reen::ParameterCorrection::_pvcPoints, Reen::ParameterCorrection::_pvcUVParam, Reen::ParameterCorrection::_usUCtrlpoints, Reen::ParameterCorrection::_usUOrder, Reen::ParameterCorrection::_usVCtrlpoints, Reen::ParameterCorrection::_usVOrder, Reen::ParameterCorrection::_vCtrlPntsOfSurf, Reen::ParameterCorrection::_vUKnots, Reen::ParameterCorrection::_vUMults, Reen::ParameterCorrection::_vVKnots, Reen::ParameterCorrection::_vVMults, Reen::ParameterCorrection::bParaCor, Reen::ParameterCorrection::DoInitialParameterCorrection(), Reen::ParameterCorrection::DoParameterCorrection(), Reen::ParameterCorrection::fSizeFactor, Reen::ParameterCorrection::iIter, and Reen::ParameterCorrection::ProjectControlPointsOnPlane().