FreeCAD: Gui::SelectionObserver Class Reference
Gui::SelectionObserver Class Reference abstract
#include <Selection.h>
Public Member Functions
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Detailed Description
The SelectionObserver class simplifies the step to write classes that listen to what happens to the selection.
Author
Werner Mayer
Definition at line 222 of file Gui/Selection.h.
Constructor & Destructor Documentation
SelectionObserver() [1/2]
SelectionObserver::SelectionObserver (bool attach = true, ResolveMode resolve = ResolveMode::OldStyleElement) explicit
Constructor
Parameters
attach whether to attach this observer on construction
resolve sub-object resolving mode. 0 no resolve, 1 resolve sub-object with old style element name 2 resolve sub-object with new style element name
Definition at line 86 of file Gui/Selection.cpp.
References attachSelection().
SelectionObserver() [2/2]
SelectionObserver::SelectionObserver (const Gui::ViewProviderDocumentObject * vp, bool attach = true, ResolveMode resolve = ResolveMode::OldStyleElement) explicit
Constructor
Parameters
vp filtering view object.
attach whether to attach this observer on construction
resolve sub-object resolving mode. 0 no resolve, 1 resolve sub-object with old style element name 2 resolve sub-object with new style element name
Constructs an selection observer that receives only selection event of objects within the same document as the input view object.
Definition at line 94 of file Gui/Selection.cpp.
References attachSelection(), App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), and Gui::ViewProviderDocumentObject::getObject().
~SelectionObserver()
SelectionObserver::~SelectionObserver () virtual
Definition at line 107 of file Gui/Selection.cpp.
References detachSelection().
Member Function Documentation
attachSelection()
void SelectionObserver::attachSelection ()
Attaches to the selection.
Definition at line 129 of file Gui/Selection.cpp.
References Gui::SelectionSingleton::addSelectionGate(), draftgeoutils.faces::bind(), Gui::NewStyleElement, Gui::OldStyleElement, Gui::Selection(), Gui::SelectionSingleton::signalSelectionChanged, Gui::SelectionSingleton::signalSelectionChanged2, and Gui::SelectionSingleton::signalSelectionChanged3.
Referenced by Gui::Dialog::DlgPropertyLink::attachObserver(), Gui::View3DInventorViewer::init(), SelectionObserver(), SketcherGui::ViewProviderSketch::setEdit(), Gui::PropertyView::showEvent(), and Gui::TaskMeasure::TaskMeasure().
blockSelection()
bool SelectionObserver::blockSelection (bool block)
Definition at line 112 of file Gui/Selection.cpp.
Referenced by SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsItemSelectionChanged(), SketcherGui::TaskSketcherElements::onListWidgetElementsItemPressed(), SketcherGui::TaskSketcherConstraints::onSelectionChanged(), PartDesignGui::TaskSketchBasedParameters::onSelectReference(), Gui::TreeWidget::onSelectTimer(), Gui::DocumentItem::populateItem(), Gui::DocumentItem::selectAllInstances(), PartDesignGui::TaskDressUpParameters::setSelection(), PartDesignGui::TaskPipeOrientation::TaskPipeOrientation(), PartDesignGui::TaskPipeParameters::TaskPipeParameters(), PartDesignGui::TaskPipeScaling::TaskPipeScaling(), PartDesignGui::TaskSketchBasedParameters::TaskSketchBasedParameters(), Gui::TaskTransform::TaskTransform(), and Gui::DocumentItem::updateSelection().
detachSelection()
void SelectionObserver::detachSelection ()
Detaches from the selection.
Definition at line 164 of file Gui/Selection.cpp.
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Referenced by Gui::Dialog::DlgPropertyLink::detachObserver(), Gui::PropertyView::hideEvent(), SketcherGui::ViewProviderSketch::unsetEdit(), ~SelectionObserver(), Gui::TaskMeasure::~TaskMeasure(), and Gui::View3DInventorViewer::~View3DInventorViewer().
isSelectionAttached()
bool SelectionObserver::isSelectionAttached () const
Definition at line 124 of file Gui/Selection.cpp.
Referenced by Gui::Dialog::DlgPropertyLink::attachObserver(), Gui::Dialog::DlgPropertyLink::detachObserver(), Gui::TreeWidget::expandSelectedItems(), Gui::TreeWidget::getSelection(), Gui::PropertyView::onTimer(), Gui::TreeWidget::selectAllInstances(), Gui::TreeWidget::selectAllLinks(), and Gui::TreeWidget::selectLinkedObject().
isSelectionBlocked()
bool SelectionObserver::isSelectionBlocked () const
Definition at line 119 of file Gui/Selection.cpp.
Referenced by Gui::TreeWidget::selectLinkedObject().
The documentation for this class was generated from the following files:
Gui/Selection.h
Gui/Selection.cpp