FreeCAD: ifc2x3.ifcstructuralresultgroup Class Reference
ifc2x3.ifcstructuralresultgroup Class Reference
Public Member Functions
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__objecttype, theorytype, resultforloadgroup, islinear)
def theorytype ()
def resultforloadgroup ()
def islinear ()
def resultgroupfor ()
Public Member Functions inherited from ifc2x3.ifcgroup
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__objecttype)
def isgroupedby ()
Public Member Functions inherited from ifc2x3.ifcobject
def objecttype ()
def isdefinedby ()
def wr1 (self)
Public Member Functions inherited from ifc2x3.ifcobjectdefinition
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description)
def hasassignments ()
def isdecomposedby ()
def decomposes ()
def hasassociations ()
Public Member Functions inherited from ifc2x3.ifcroot
def globalid ()
def ownerhistory ()
def name ()
def description ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
theorytype
resultforloadgroup
islinear
Public Attributes inherited from ifc2x3.ifcobject
objecttype
Public Attributes inherited from ifc2x3.ifcroot
globalid
ownerhistory
name
description
Detailed Description
Entity ifcstructuralresultgroup definition.
:param theorytype
:type theorytype:ifcanalysistheorytypeenum
:param resultforloadgroup
:type resultforloadgroup:ifcstructuralloadgroup
:param islinear
:type islinear:BOOLEAN
:param resultgroupfor
:type resultgroupfor:SET(0,1,'ifcstructuralanalysismodel', scope = schema_scope)
Definition at line 32546 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcstructuralresultgroup.__init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__objecttype, theorytype, resultforloadgroup, islinear)
Definition at line 32561 of file ifc2x3.py.
Member Function Documentation
islinear()
def ifc2x3.ifcstructuralresultgroup.islinear ()
Definition at line 32596 of file ifc2x3.py.
References ifc2x3.ifcstructuralresultgroup._islinear, SCL.SimpleDataTypes.BOOLEAN, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralresultgroup.islinear.
resultforloadgroup()
def ifc2x3.ifcstructuralresultgroup.resultforloadgroup ()
Definition at line 32582 of file ifc2x3.py.
References ifc2x3.ifcstructuralresultgroup._resultforloadgroup, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralresultgroup.resultforloadgroup.
resultgroupfor()
def ifc2x3.ifcstructuralresultgroup.resultgroupfor ()
Definition at line 32610 of file ifc2x3.py.
theorytype()
def ifc2x3.ifcstructuralresultgroup.theorytype ()
Definition at line 32568 of file ifc2x3.py.
References ifc2x3.ifcstructuralresultgroup._theorytype, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralresultgroup.theorytype.
Member Data Documentation
islinear
ifc2x3.ifcstructuralresultgroup.islinear
Definition at line 32565 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralresultgroup.islinear().
resultforloadgroup
ifc2x3.ifcstructuralresultgroup.resultforloadgroup
Definition at line 32564 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralresultgroup.resultforloadgroup().
theorytype
ifc2x3.ifcstructuralresultgroup.theorytype
Definition at line 32563 of file ifc2x3.py.
Referenced by ifc4.ifcstructuralresultgroup.hasobjecttype(), and ifc2x3.ifcstructuralresultgroup.theorytype().
The documentation for this class was generated from the following file:
ifc2x3.py