FreeCAD: Gui::FlagLayout Class Reference
Gui::FlagLayout Class Reference
#include <Flag.h>
Public Types
enum Position { TopLeft, TopRight, BottomLeft, BottomRight }
Public Member Functions
FlagLayout (QWidget *parent, int margin=0, int spacing=-1)
FlagLayout (int spacing=-1)
~FlagLayout () override
void addItem (QLayoutItem *item) override
void addWidget (QWidget *widget, Position position)
Qt::Orientations expandingDirections () const override
bool hasHeightForWidth () const override
int count () const override
QLayoutItem * itemAt (int index) const override
QSize minimumSize () const override
void setGeometry (const QRect &rect) override
QSize sizeHint () const override
QLayoutItem * takeAt (int index) override
void add (QLayoutItem *item, Position position)
Detailed Description
Definition at line 91 of file Flag.h.
Member Enumeration Documentation
Position
enum Gui::FlagLayout::Position
Enumerator
TopLeft
TopRight
BottomLeft
BottomRight
Definition at line 96 of file Flag.h.
Constructor & Destructor Documentation
FlagLayout() [1/2]
FlagLayout::FlagLayout (QWidget * parent, int margin = 0, int spacing = -1)
Definition at line 189 of file Flag.cpp.
FlagLayout() [2/2]
FlagLayout::FlagLayout (int spacing = -1)
Definition at line 196 of file Flag.cpp.
~FlagLayout()
FlagLayout::~FlagLayout () override
Definition at line 201 of file Flag.cpp.
References RobotExample::l, and takeAt().
Member Function Documentation
add()
void FlagLayout::add (QLayoutItem * item, Position position)
Definition at line 308 of file Flag.cpp.
Referenced by addItem(), and addWidget().
addItem()
void FlagLayout::addItem (QLayoutItem * item) override
Definition at line 208 of file Flag.cpp.
References add(), and TopLeft.
Referenced by draftguitools.gui_layers.LayerManager::update(), and bimcommands.BimLayers.BIM_Layers::update().
addWidget()
void FlagLayout::addWidget (QWidget * widget, Position position)
Definition at line 213 of file Flag.cpp.
References add().
Referenced by Gui::GLFlagWindow::addFlag().
count()
int FlagLayout::count () const override
Definition at line 228 of file Flag.cpp.
Referenced by Gui::GLFlagWindow::countFlags(), Gui::GLFlagWindow::deleteFlags(), Gui::GLFlagWindow::paintGL(), and src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::set_status_filter().
expandingDirections()
Qt::Orientations FlagLayout::expandingDirections () const override
Definition at line 218 of file Flag.cpp.
References Sketcher::Horizontal, and Sketcher::Vertical.
hasHeightForWidth()
bool FlagLayout::hasHeightForWidth () const override
Definition at line 223 of file Flag.cpp.
itemAt()
QLayoutItem * FlagLayout::itemAt (int index) const override
Definition at line 233 of file Flag.cpp.
Referenced by Gui::GLFlagWindow::deleteFlags(), Gui::GLFlagWindow::getFlag(), and Gui::GLFlagWindow::paintGL().
minimumSize()
QSize FlagLayout::minimumSize () const override
Definition at line 242 of file Flag.cpp.
setGeometry()
void FlagLayout::setGeometry (const QRect & rect) override
Definition at line 247 of file Flag.cpp.
References BottomLeft, BottomRight, TopLeft, and TopRight.
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_readme_browser.WidgetReadmeBrowser::setMarkdown().
sizeHint()
QSize FlagLayout::sizeHint () const override
Definition at line 294 of file Flag.cpp.
takeAt()
QLayoutItem * FlagLayout::takeAt (int index) override
Definition at line 299 of file Flag.cpp.
Referenced by ~FlagLayout().
The documentation for this class was generated from the following files:
Flag.h
Flag.cpp