FreeCAD: AttacherGui::AttacherGuiPy Class Reference
AttacherGui::AttacherGuiPy Class Reference
#include <AttacherTexts.h>
Static Public Member Functions
static PyObject * sGetModeStrings (PyObject *, PyObject *args)
static PyObject * sGetRefTypeUserFriendlyName (PyObject *, PyObject *args)
Static Public Attributes
static PyMethodDef Methods []
Detailed Description
Definition at line 78 of file AttacherTexts.h.
Member Function Documentation
sGetModeStrings()
PyObject * AttacherGui::AttacherGuiPy::sGetModeStrings (PyObject * , PyObject * args) static
Definition at line 380 of file AttacherTexts.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, Base::Type::fromName(), Base::BaseClass::getClassTypeId(), AttacherGui::getUIStrings(), Py::new_reference_to(), result, toolbit-attributes::s, src.Mod.Test.testmakeWireString::String, and InitGui::t.
sGetRefTypeUserFriendlyName()
PyObject * AttacherGui::AttacherGuiPy::sGetRefTypeUserFriendlyName (PyObject * , PyObject * args) static
Definition at line 411 of file AttacherTexts.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, AttacherGui::getShapeTypeText(), Py::new_reference_to(), and src.Mod.Test.testmakeWireString::String.
Member Data Documentation
Methods
PyMethodDef AttacherGui::AttacherGuiPy::Methods static
Initial value:
= {
    {"getModeStrings",             (PyCFunction) AttacherGuiPy::sGetModeStrings, METH_VARARGS,
     "getModeStrings(attacher_type, mode_index) - gets mode user-friendly name and brief description."},
    {"getRefTypeUserFriendlyName", (PyCFunction) AttacherGuiPy::sGetRefTypeUserFriendlyName, METH_VARARGS,
     "getRefTypeUserFriendlyName(type_index) - gets user-friendly name of AttachEngine's shape type."},
    {nullptr, nullptr, 0, nullptr}
}
Definition at line 80 of file AttacherTexts.h.
Referenced by PyMOD_INIT_FUNC().
The documentation for this class was generated from the following files:
AttacherTexts.h
AttacherTexts.cpp