FreeCAD: Path.Base.Generator.dogboneII Namespace Reference
Path.Base.Generator.dogboneII Namespace Reference
Classes
class Bone
class Generator
class GeneratorDogbone
class GeneratorTBoneHorizontal
class GeneratorTBoneOnLong
class GeneratorTBoneOnShort
class GeneratorTBoneVertical
class Kink
Functions
def kink_to_path (kink, g0=False)
def bone_to_path (bone, g0=False)
def generate_bone (kink, length, angle)
def generate (kink, generator, calc_length, nominal_length, custom_length=None)
Variables
PI
the value of pi
Function Documentation
bone_to_path()
def Path.Base.Generator.dogboneII.bone_to_path (bone, g0 = False)
Definition at line 115 of file dogboneII.py.
References Path.Geom.isRoughly(), and Path.Geom.pointsCoincide().
generate()
def Path.Base.Generator.dogboneII.generate (kink, generator, calc_length, nominal_length, custom_length = None)
Definition at line 209 of file dogboneII.py.
Referenced by Mesh::MergeExporter.addMesh(), App::Document.addObjects(), Part::BRepMesh.createSegments(), Inspection::Feature.execute(), MeshGui::MeshSelection.fullSelection(), MeshGui::ViewProviderMesh.getFacetsFromPolygon(), MeshCore::MeshCurvature.MeshCurvature(), MeshGui::ViewProviderMesh.segmentMesh(), MeshCore::MedianFilterSmoothing.Smooth(), Reen::BSplineParameterCorrection.SolveWithSmoothing(), and MeshGui::ViewProviderMesh.splitMesh().
generate_bone()
def Path.Base.Generator.dogboneII.generate_bone (kink, length, angle)
Definition at line 131 of file dogboneII.py.
References Path.Geom.isRoughly().
kink_to_path()
def Path.Base.Generator.dogboneII.kink_to_path (kink, g0 = False)
Definition at line 111 of file dogboneII.py.
Variable Documentation
PI
Path.Base.Generator.dogboneII.PI
the value of pi
Definition at line 30 of file dogboneII.py.