FreeCAD: Gui::Dialog::DlgCreateNewPreferencePackImp Class Reference
Gui::Dialog::DlgCreateNewPreferencePackImp Class Reference
#include <DlgCreateNewPreferencePackImp.h>
Public Member Functions
DlgCreateNewPreferencePackImp (QWidget *parent=nullptr)
~DlgCreateNewPreferencePackImp () override
void setPreferencePackTemplates (const std::vector< PreferencePackManager::TemplateFile > &availableTemplates)
void setPreferencePackNames (const std::vector< std::string > &usedNames)
std::vector< PreferencePackManager::TemplateFile > selectedTemplates () const
std::string preferencePackName () const
std::string preferencePackDirectory () const
Protected Slots
void onItemChanged (QTreeWidgetItem *item, int column)
void onLineEditTextEdited (const QString &text)
void onBrowseButtonClicked ()
void accept () override
Detailed Description
A dialog to request a preferencePack name and a set of preferencePack templates.
Author
Chris Hennes
Definition at line 48 of file DlgCreateNewPreferencePackImp.h.
Constructor & Destructor Documentation
DlgCreateNewPreferencePackImp()
DlgCreateNewPreferencePackImp::DlgCreateNewPreferencePackImp (QWidget * parent = nullptr) explicit
Constructs a Gui::Dialog::DlgCreateNewPreferencePackImp as a child of 'parent'
Definition at line 46 of file DlgCreateNewPreferencePackImp.cpp.
References draftgeoutils.intersections::connect(), onBrowseButtonClicked(), onItemChanged(), onLineEditTextEdited(), and src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression.
~DlgCreateNewPreferencePackImp()
Gui::Dialog::DlgCreateNewPreferencePackImp::~DlgCreateNewPreferencePackImp () override
Member Function Documentation
accept
void Gui::Dialog::DlgCreateNewPreferencePackImp::accept () override protected slot
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
onBrowseButtonClicked
void Gui::Dialog::DlgCreateNewPreferencePackImp::onBrowseButtonClicked () protected slot
Referenced by DlgCreateNewPreferencePackImp().
onItemChanged
void Gui::Dialog::DlgCreateNewPreferencePackImp::onItemChanged (QTreeWidgetItem * item, int column) protected slot
Referenced by DlgCreateNewPreferencePackImp().
onLineEditTextEdited
void Gui::Dialog::DlgCreateNewPreferencePackImp::onLineEditTextEdited (const QString & text) protected slot
Referenced by DlgCreateNewPreferencePackImp().
preferencePackDirectory()
std::string Gui::Dialog::DlgCreateNewPreferencePackImp::preferencePackDirectory () const
preferencePackName()
std::string Gui::Dialog::DlgCreateNewPreferencePackImp::preferencePackName () const
selectedTemplates()
std::vector<PreferencePackManager::TemplateFile> Gui::Dialog::DlgCreateNewPreferencePackImp::selectedTemplates () const
setPreferencePackNames()
void Gui::Dialog::DlgCreateNewPreferencePackImp::setPreferencePackNames (const std::vector< std::string > & usedNames)
setPreferencePackTemplates()
void Gui::Dialog::DlgCreateNewPreferencePackImp::setPreferencePackTemplates (const std::vector< PreferencePackManager::TemplateFile > & availableTemplates)
The documentation for this class was generated from the following files:
DlgCreateNewPreferencePackImp.h
DlgCreateNewPreferencePackImp.cpp