FreeCAD: PartGui::CirclePrimitive Class Reference
PartGui::CirclePrimitive Class Reference
#include <DlgPrimitives.h>
Public Member Functions
CirclePrimitive (std::shared_ptr< Ui_DlgPrimitives > ui, Part::Circle *feature=nullptr)
const char * getDefaultName () const override
QString create (const QString &objectName, const QString &placement) const override
QString change (const QString &objectName, const QString &placement) const override
void changeValue (QObject *) override
Public Member Functions inherited from PartGui::AbstractPrimitive
AbstractPrimitive (Part::Primitive *feature=nullptr)
~AbstractPrimitive () override=default
bool hasValidPrimitive () const
Additional Inherited Members
Protected Member Functions inherited from PartGui::AbstractPrimitive
void connectSignalMapper (QSignalMapper *mapper)
Protected Attributes inherited from PartGui::AbstractPrimitive
App::DocumentObjectWeakPtrT featurePtr
Detailed Description
Definition at line 298 of file DlgPrimitives.h.
Constructor & Destructor Documentation
CirclePrimitive()
CirclePrimitive::CirclePrimitive (std::shared_ptr< Ui_DlgPrimitives > ui, Part::Circle * feature = nullptr)
Definition at line 1334 of file DlgPrimitives.cpp.
References Part::Circle::Angle1, Part::Circle::Angle2, PartGui::connectMapSignalMapper(), PartGui::AbstractPrimitive::connectSignalMapper(), App::PropertyQuantity::getQuantityValue(), Part::Circle::Radius, and Gui::QuantitySpinBox::valueChanged().
Member Function Documentation
change()
QString CirclePrimitive::change (const QString & objectName, const QString & placement) const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 1380 of file DlgPrimitives.cpp.
References PartGui::safeQuantityQString().
changeValue()
void CirclePrimitive::changeValue (QObject * widget) override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 1394 of file DlgPrimitives.cpp.
References App::DocumentObjectWeakPtrT::expired(), PartGui::AbstractPrimitive::featurePtr, and App::DocumentObjectWeakPtrT::get().
create()
QString CirclePrimitive::create (const QString & objectName, const QString & placement) const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 1363 of file DlgPrimitives.cpp.
References PartGui::safeQuantityQString().
getDefaultName()
const char * CirclePrimitive::getDefaultName () const override virtual
Implements PartGui::AbstractPrimitive.
Definition at line 1358 of file DlgPrimitives.cpp.
The documentation for this class was generated from the following files:
DlgPrimitives.h
DlgPrimitives.cpp