FreeCAD: Assembly::AssemblyObject Class Reference
Assembly::AssemblyObject Class Reference
#include <AssemblyObject.h>
Classes
struct MbDPartData
Public Member Functions
AssemblyObject ()
~AssemblyObject () override
PyObject * getPyObject () override
getPyObject returns the Python binding object
const char * getViewProviderName () const override
returns the type name of the ViewProvider
App::DocumentObjectExecReturn * execute () override
int solve (bool enableRedo=false, bool updateJCS=true)
int generateSimulation (App::DocumentObject *sim)
int updateForFrame (size_t index, bool updateJCS=true)
size_t numberOfFrames ()
void preDrag (std::vector< App::DocumentObject * > dragParts)
void doDragStep ()
void postDrag ()
void savePlacementsForUndo ()
void undoSolve ()
void clearUndo ()
void exportAsASMT (std::string fileName)
Base::Placement getMbdPlacement (std::shared_ptr< MbD::ASMTPart > mbdPart)
bool validateNewPlacements ()
void setNewPlacements ()
void ensureIdentityPlacements ()
std::shared_ptr< MbD::ASMTAssembly > makeMbdAssembly ()
void create_mbdSimulationParameters (App::DocumentObject *sim)
std::shared_ptr< MbD::ASMTPart > makeMbdPart (std::string &name, Base::Placement plc=Base::Placement(), double mass=1.0)
std::shared_ptr< MbD::ASMTPart > getMbDPart (App::DocumentObject *obj)
MbDPartData getMbDData (App::DocumentObject *obj)
std::shared_ptr< MbD::ASMTMarker > makeMbdMarker (std::string &name, Base::Placement &plc)
std::vector< std::shared_ptr< MbD::ASMTJoint > > makeMbdJoint (App::DocumentObject *joint)
std::shared_ptr< MbD::ASMTJoint > makeMbdJointOfType (App::DocumentObject *joint, JointType jointType)
std::shared_ptr< MbD::ASMTJoint > makeMbdJointDistance (App::DocumentObject *joint)
std::string handleOneSideOfJoint (App::DocumentObject *joint, const char *propRefName, const char *propPlcName)
void getRackPinionMarkers (App::DocumentObject *joint, std::string &markerNameI, std::string &markerNameJ)
int slidingPartIndex (App::DocumentObject *joint)
void jointParts (std::vector< App::DocumentObject * > joints)
JointGroup * getJointGroup () const
ViewGroup * getExplodedViewGroup () const
template<typename T >
T * getGroup ()
std::vector< App::DocumentObject * > getJoints (bool updateJCS=true, bool delBadJoints=false, bool subJoints=true)
std::vector< App::DocumentObject * > getGroundedJoints ()
std::vector< App::DocumentObject * > getJointsOfObj (App::DocumentObject *obj)
std::vector< App::DocumentObject * > getJointsOfPart (App::DocumentObject *part)
App::DocumentObject * getJointOfPartConnectingToGround (App::DocumentObject *part, std::string &name)
std::unordered_set< App::DocumentObject * > getGroundedParts ()
std::unordered_set< App::DocumentObject * > fixGroundedParts ()
void fixGroundedPart (App::DocumentObject *obj, Base::Placement &plc, std::string &jointName)
bool isJointConnectingPartToGround (App::DocumentObject *joint, const char *partPropName)
bool isJointTypeConnecting (App::DocumentObject *joint)
bool isObjInSetOfObjRefs (App::DocumentObject *obj, const std::vector< ObjRef > &pairs)
void removeUnconnectedJoints (std::vector< App::DocumentObject * > &joints, std::unordered_set< App::DocumentObject * > groundedObjs)
void traverseAndMarkConnectedParts (App::DocumentObject *currentPart, std::vector< ObjRef > &connectedParts, const std::vector< App::DocumentObject * > &joints)
std::vector< ObjRef > getConnectedParts (App::DocumentObject *part, const std::vector< App::DocumentObject * > &joints)
bool isPartGrounded (App::DocumentObject *part)
bool isPartConnected (App::DocumentObject *part)
std::vector< ObjRef > getDownstreamParts (App::DocumentObject *part, App::DocumentObject *joint=nullptr)
std::vector< App::DocumentObject * > getUpstreamParts (App::DocumentObject *part, int limit=0)
App::DocumentObject * getUpstreamMovingPart (App::DocumentObject *part, App::DocumentObject *&joint, std::string &name)
double getObjMass (App::DocumentObject *obj)
void setObjMasses (std::vector< std::pair< App::DocumentObject *, double >> objectMasses)
std::vector< AssemblyLink * > getSubAssemblies ()
std::vector< App::DocumentObject * > getMotionsFromSimulation (App::DocumentObject *sim)
Public Member Functions inherited from App::Part
Part ()
Constructor.
~Part () override
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, App::Property *prop) override
Public Member Functions inherited from App::GeoFeature
GeoFeature ()
Constructor.
~GeoFeature () override
virtual void transformPlacement (const Base::Placement &transform)
transformPlacement applies transform to placement of this shape. Override this function to propagate the change of placement to base features, for example. By the time of writing this comment, the function was only called by alignment task (Edit->Alignment)
virtual const PropertyComplexGeoData * getPropertyOfGeometry () const
virtual ElementNamePair getElementName (const char *name, ElementNameType type=Normal) const
Base::Placement globalPlacement () const
Deprecated. Calculates the placement in the global reference coordinate system.
virtual App::Material getMaterialAppearance () const
Virtual function to get an App::Material object describing the appearance.
virtual void setMaterialAppearance (const App::Material &material)
Virtual function to set the appearance with an App::Material object.
virtual bool getCameraAlignmentDirection (Base::Vector3d &direction, const char *subname=nullptr) const
Virtual function to get the camera alignment direction.
virtual const std::vector< std::string > & searchElementCache (const std::string &element, Data::SearchOptions options=Data::SearchOption::CheckGeometry, double tol=1e-7, double atol=1e-10) const
virtual DocumentObject * getElementOwner (const Data::MappedName &) const
Return the object that owns the shape that contains the give element name.
virtual std::vector< const char * > getElementTypes (bool all=true) const
virtual std::vector< Data::IndexedName > getHigherElements (const char *name, bool silent=false) const
Return the higher level element names of the given element.
Public Member Functions inherited from App::DocumentObject
virtual const char * getViewProviderNameOverride () const
DocumentObject ()
Constructor.
~DocumentObject () override
const char * getDagKey () const
returns a value that uniquely identifies this DocumentObject.
const char * getNameInDocument () const
returns the name which is set in the document for this object (not the name property!)
long getID () const
Return the object ID that is unique within its owner document.
std::string getExportName (bool forced=false) const
returns the name that is safe to be exported to other document
std::string getFullName () const override
Return the object full name of the form DocName::ObjName.
std::string getFullLabel () const
Return the object full label in the form DocName::ObjName.
bool isAttachedToDocument () const override
const char * detachFromDocument () override
App::Document * getDocument () const
gets the document in which this Object is handled
void touch (bool noRecompute=false)
set this document object touched (cause recomputation on dependent features)
bool isTouched () const
test if this document object is touched
void enforceRecompute ()
Enforce this document object to be recomputed.
bool mustRecompute () const
Test if this document object must be recomputed.
void purgeTouched ()
reset this document object touched
bool isError () const
set this feature to error
bool isValid () const
void purgeError ()
remove the error from the object
bool isRecomputing () const
returns true if this objects is currently recomputing
bool isRestoring () const
returns true if this objects is currently restoring from file
bool isRemoving () const
returns true if this objects is currently removed from the document
void freeze ()
set this document object freezed (prevent recomputation)
void unfreeze (bool noRecompute=false)
set this document object unfreezed (and touch it)
bool isFreezed () const
returns true if this objects is currently freezed
unsigned long getStatus () const
return the status bits
bool testStatus (ObjectStatus pos) const
void setStatus (ObjectStatus pos, bool on)
int isExporting () const
virtual int setElementVisible (const char *element, bool visible)
virtual int isElementVisible (const char *element) const
virtual bool hasChildElement () const
return true to activate tree view group object handling and element visibility
const std::vector< App::DocumentObject * > & getOutList () const
returns a list of objects this object is pointing to by Links
std::vector< App::DocumentObject * > getOutList (int option) const
void getOutList (int option, std::vector< App::DocumentObject * > &res) const
std::vector< App::DocumentObject * > getOutListOfProperty (App::Property *) const
returns a list of objects linked by the property
std::vector< App::DocumentObject * > getOutListRecursive () const
returns a list of objects this object is pointing to by Links and all further descended
void clearOutListCache () const
clear internal out list cache
std::vector< std::list< App::DocumentObject * > > getPathsByOutList (App::DocumentObject *to) const
get all possible paths from this to another object following the OutList
const std::vector< App::DocumentObject * > & getInList () const
std::vector< App::DocumentObject * > getInListRecursive () const
get all objects link directly or indirectly to this object
void getInListEx (std::set< App::DocumentObject * > &inSet, bool recursive, std::vector< App::DocumentObject * > *inList=nullptr) const
std::set< App::DocumentObject * > getInListEx (bool recursive) const
DocumentObjectGroup * getGroup () const
get group if object is part of a group, otherwise 0 is returned
bool isInInListRecursive (DocumentObject *objToTest) const
test if this object is in the InList and recursive further down
bool isInInList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the InList
bool isInOutListRecursive (DocumentObject *objToTest) const
test if the given object is in the OutList and recursive further down
bool isInOutList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the OutList
void _removeBackLink (DocumentObject *)
internal, used by PropertyLink to maintain DAG back links
void _addBackLink (DocumentObject *)
internal, used by PropertyLink to maintain DAG back links
bool testIfLinkDAGCompatible (DocumentObject *linkTo) const
testIfLinkIsDAG tests a link that is about to be created for circular references.
bool testIfLinkDAGCompatible (const std::vector< DocumentObject * > &linksTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSubList &linksTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSub &linkTo) const
virtual std::string getElementMapVersion (const App::Property *prop, bool restored=false) const
virtual bool checkElementMapVersion (const App::Property *prop, const char *ver) const
Return true to signal re-generation of geometry element names.
virtual short mustExecute () const
bool recomputeFeature (bool recursive=false)
const char * getStatusString () const
get the status Message
virtual void onLostLinkToObject (DocumentObject *)
virtual DocumentObject * getSubObject (const char *subname, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
std::vector< DocumentObject * > getSubObjectList (const char *subname, std::vector< int > *subsizes=nullptr, bool flatten=false) const
virtual std::vector< std::string > getSubObjects (int reason=0) const
std::vector< std::pair< App::DocumentObject *, std::string > > getParents (int depth=0) const
Obtain top parents and subnames of this object using its InList.
App::DocumentObject * getFirstParent () const
Obtain the first parent group of this object.
virtual DocumentObject * getLinkedObject (bool recurse=true, Base::Matrix4D *mat=nullptr, bool transform=false, int depth=0) const
virtual bool canLinkProperties () const
virtual bool isLink () const
virtual bool isLinkGroup () const
virtual bool allowDuplicateLabel () const
virtual void onBeforeChangeLabel (std::string &newLabel)
void Save (Base::Writer &writer) const override
virtual void setExpression (const ObjectIdentifier &path, std::shared_ptr< App::Expression > expr)
void clearExpression (const ObjectIdentifier &path)
virtual const PropertyExpressionEngine::ExpressionInfo getExpression (const ObjectIdentifier &path) const
virtual void renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &paths)
const std::string & getOldLabel () const
const char * getViewProviderNameStored () const
bool removeDynamicProperty (const char *prop) override
App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
App::DocumentObject * resolve (const char *subname, App::DocumentObject **parent=nullptr, std::string *childName=nullptr, const char **subElement=nullptr, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
App::DocumentObject * resolveRelativeLink (std::string &subname, App::DocumentObject *&link, std::string &linkSub) const
virtual bool adjustRelativeLinks (const std::set< App::DocumentObject * > &inList, std::set< App::DocumentObject * > *visited=nullptr)
virtual int canLoadPartial () const
virtual void onUpdateElementReference (const Property *)
virtual bool redirectSubName (std::ostringstream &ss, DocumentObject *topParent, DocumentObject *child) const
Public Member Functions inherited from App::TransactionalObject
TransactionalObject ()
Constructor.
~TransactionalObject () override
Public Member Functions inherited from App::ExtensionContainer
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
Property * getPropertyByName (const char *name) const override
find a property by its name
template<typename T >
T * getPropertyByName (const char *name) const
find a property by its name, dynamic cased to specified type
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::OriginGroupExtension
OriginGroupExtension ()
~OriginGroupExtension () override
App::Origin * getOrigin () const
Returns the origin link or throws an exception.
short extensionMustExecute () override
Returns true on changing OriginFeature set.
void relinkToOrigin (App::DocumentObject *obj)
std::vector< DocumentObject * > addObjects (std::vector< DocumentObject * > obj) override
bool hasObject (const DocumentObject *obj, bool recursive=false) const override
bool extensionGetSubObject (DocumentObject *&ret, const char *subname, PyObject **pyObj, Base::Matrix4D *mat, bool transform, int depth) const override
void extensionOnChanged (const Property *p) override
Public Member Functions inherited from App::GeoFeatureGroupExtension
PropertyPlacement & placement ()
void initExtension (ExtensionContainer *obj) override
virtual void transformPlacement (const Base::Placement &transform)
transformPlacement applies transform to placement of this shape. Override this function to propagate the change of placement to base features.
GeoFeatureGroupExtension ()
Constructor.
~GeoFeatureGroupExtension () override
Base::Placement globalGroupPlacement ()
Calculates the global placement of this group.
bool extensionGetSubObjects (std::vector< std::string > &ret, int reason) const override
std::vector< DocumentObject * > removeObjects (std::vector< DocumentObject * > obj) override
Public Member Functions inherited from App::GroupExtension
GroupExtension ()
Constructor.
~GroupExtension () override
virtual DocumentObject * addObject (const char *sType, const char *pObjectName)
virtual std::vector< DocumentObject * > addObject (DocumentObject *obj)
virtual std::vector< DocumentObject * > setObjects (std::vector< DocumentObject * > obj)
virtual bool allowObject (DocumentObject *)
virtual std::vector< DocumentObject * > removeObject (DocumentObject *obj)
virtual void removeObjectsFromDocument ()
DocumentObject * getObject (const char *Name) const
bool isChildOf (const GroupExtension *group, bool recursive=true) const
const std::vector< DocumentObject * > & getObjects () const
std::vector< DocumentObject * > getObjectsOfType (const Base::Type &typeId) const
int countObjectsOfType (const Base::Type &typeId) const
PyObject * getExtensionPyObject () override
bool extensionGetSubObjects (std::vector< std::string > &ret, int reason) const override
std::vector< DocumentObject * > getAllChildren () const
void getAllChildren (std::vector< DocumentObject * > &, std::set< DocumentObject * > &) const
Public Member Functions inherited from App::DocumentObjectExtension
virtual Base::Type getExtensionTypeId (void) const override
DocumentObjectExtension ()
~DocumentObjectExtension () override
App::DocumentObject * getExtendedObject ()
const App::DocumentObject * getExtendedObject () const
virtual void onExtendedSettingDocument ()
get called after setting the document
virtual void onExtendedDocumentRestored ()
get called after a document has been fully restored
virtual const char * getViewProviderExtensionName () const
virtual bool extensionGetLinkedObject (DocumentObject *&ret, bool recursive, Base::Matrix4D *mat, bool transform, int depth) const
virtual int extensionSetElementVisible (const char *, bool)
virtual int extensionIsElementVisible (const char *)
virtual bool extensionHasChildElement () const
Public Member Functions inherited from App::Extension
Extension ()=default
virtual ~Extension ()
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual Property * extensionGetPropertyByName (const char *name) const
find a property by its name
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Static Public Member Functions
static void recomputeJointPlacements (std::vector< App::DocumentObject * > joints)
static void redrawJointPlacements (std::vector< App::DocumentObject * > joints)
static void redrawJointPlacement (App::DocumentObject *joint)
Static Public Member Functions inherited from App::Part
static App::Part * getPartOfObject (const DocumentObject *obj, bool recursive=true)
Static Public Member Functions inherited from App::GeoFeature
static DocumentObject * resolveElement (const App::DocumentObject *obj, const char *subname, ElementNamePair &elementName, bool append=false, ElementNameType type=Normal, const DocumentObject *filter=nullptr, const char **element=nullptr, GeoFeature **geo=nullptr)
static bool hasMissingElement (const char *subname)
static Base::Placement getPlacementFromProp (DocumentObject *obj, const char *propName)
static Base::Placement getGlobalPlacement (DocumentObject *targetObj, DocumentObject *rootObj, const std::string &sub)
static Base::Placement getGlobalPlacement (DocumentObject *targetObj, PropertyXLinkSub *prop)
static Base::Placement getGlobalPlacement (const DocumentObject *obj)
Static Public Member Functions inherited from App::DocumentObject
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
Check if the subname reference ends with hidden marker.
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Member Functions inherited from App::OriginGroupExtension
static DocumentObject * getGroupOfObject (const DocumentObject *obj)
Static Public Member Functions inherited from App::GeoFeatureGroupExtension
static DocumentObject * getGroupOfObject (const DocumentObject *obj)
static bool isNonGeoGroup (const DocumentObject *obj)
Returns true if the given DocumentObject is DocumentObjectGroup but not GeoFeatureGroup.
static std::vector< App::DocumentObject * > getCSRelevantLinks (const App::DocumentObject *obj)
static bool areLinksValid (const App::DocumentObject *obj)
static bool isLinkValid (App::Property *link)
static void getInvalidLinkObjects (const App::DocumentObject *obj, std::vector< App::DocumentObject * > &vec)
Static Public Member Functions inherited from App::GroupExtension
static DocumentObject * getGroupOfObject (const DocumentObject *obj)
Static Public Member Functions inherited from App::DocumentObjectExtension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Static Public Member Functions inherited from App::Extension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Additional Inherited Members
Public Types inherited from App::GeoFeature
enum ElementNameType { Normal = 0, Import = 1, Export = 2 }
Specify the type of element name to return when calling getElementName()
Public Types inherited from App::DocumentObject
enum OutListOption { OutListNoExpression = 1, OutListNoHidden = 2, OutListNoXLinked = 4 }
OutList options.
enum GSReason { GS_DEFAULT, GS_SELECT }
reason of calling getSubObjects()
Public Types inherited from App::ExtensionContainer
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Public Attributes inherited from App::Part
PropertyString Type
type of the part
App::PropertyString Id
Id e.g. Part number.
App::PropertyUUID Uid
unique identifier of the Item
App::PropertyLink Material
material descriptions
App::PropertyMap Meta
Meta descriptions.
App::PropertyString License
App::PropertyString LicenseURL
License description/contract URL.
App::PropertyColor Color
Public Attributes inherited from App::GeoFeature
PropertyPlacement Placement
Public Attributes inherited from App::DocumentObject
PropertyString Label
PropertyString Label2
PropertyExpressionEngine ExpressionEngine
PropertyBool Visibility
Allow control visibility status in App name space.
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalBeforeChange
signal before changing a property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalChanged
signal on changed property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalEarlyChanged
signal on changed property of this object before document scoped signalChangedObject
Public Attributes inherited from App::OriginGroupExtension
PropertyLink Origin
Origin linked to the group.
Public Attributes inherited from App::GroupExtension
PropertyLinkList Group
Properties.
PropertyBool _GroupTouched
Static Public Attributes inherited from App::DocumentObject
static DocumentObjectExecReturn * StdReturn
Protected Member Functions inherited from App::GeoFeature
void onChanged (const Property *prop) override
get called by the container when a property was changed
void updateElementReference ()
ElementNamePair _getElementName (const char *name, const Data::MappedElement &mapped) const
Protected Member Functions inherited from App::DocumentObject
virtual App::DocumentObjectExecReturn * recompute ()
recompute only this object
App::DocumentObjectExecReturn * executeExtensions ()
void setError ()
void resetError ()
void setDocument (App::Document *doc)
void onBeforeChange (const Property *prop) override
get called before the value is changed
void onEarlyChange (const Property *prop) override
get called by the container when a property was changed
virtual void onDocumentRestored ()
get called after a document has been fully restored
virtual void onUndoRedoFinished ()
get called after an undo/redo transaction is finished
virtual void onSettingDocument ()
get called after setting the document
virtual void setupObject ()
get called after a brand new object was created
virtual void unsetupObject ()
get called when object is going to be removed from the document
void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus) override
get called when a property status has changed
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData () const
Protected Member Functions inherited from App::OriginGroupExtension
App::DocumentObjectExecReturn * extensionExecute () override
Checks integrity of the Origin.
void onExtendedSetupObject () override
Creates the corresponding Origin object.
void onExtendedUnsetupObject () override
Removes all planes and axis if they are still linked to the document.
Protected Member Functions inherited from App::DocumentObjectExtension
virtual const App::PropertyData & extensionGetPropertyData (void) const override
Protected Member Functions inherited from App::Extension
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
returns true if the property name change was handled by the extension.
virtual bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
returns true if the property type change was handled by the extension.
void initExtensionType (Base::Type type)
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Static Protected Member Functions inherited from App::DocumentObjectExtension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
Static Protected Member Functions inherited from App::Extension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::DocumentObject
std::bitset< 32 > StatusBits
Py::SmartPtr PythonObject
python object of this class and all descendent
App::Document * _pDoc {nullptr}
pointer to the document this object belongs to
std::string oldLabel
Old label; used for renaming expressions.
const std::string * pcNameInDocument {nullptr}
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Detailed Description
Definition at line 74 of file AssemblyObject.h.
Constructor & Destructor Documentation
AssemblyObject()
AssemblyObject::AssemblyObject ()
Definition at line 106 of file AssemblyObject.cpp.
~AssemblyObject()
AssemblyObject::~AssemblyObject () override default
Member Function Documentation
clearUndo()
void AssemblyObject::clearUndo ()
Definition at line 447 of file AssemblyObject.cpp.
create_mbdSimulationParameters()
void Assembly::AssemblyObject::create_mbdSimulationParameters (App::DocumentObject * sim)
Definition at line 1075 of file AssemblyObject.cpp.
References SCL.SimpleDataTypes::e, and App::PropertyFloat::getValue().
Referenced by generateSimulation().
doDragStep()
void AssemblyObject::doDragStep ()
Definition at line 288 of file AssemblyObject.cpp.
References getJoints(), getMbDPart(), App::GeoFeature::getPlacementFromProp(), Base::Placement::getPosition(), Base::Placement::getRotation(), Base::Matrix4D::getRow(), Base::Rotation::getValue(), RobotExample::pos, redrawJointPlacement(), setNewPlacements(), validateNewPlacements(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
ensureIdentityPlacements()
void AssemblyObject::ensureIdentityPlacements ()
Definition at line 1984 of file AssemblyObject.cpp.
References App::PropertyListsT< T, ListT, ParentT >::getValues(), toolbit-attributes::group, App::GroupExtension::Group, Base::Placement::isIdentity(), and App::PropertyPlacement::setValue().
Referenced by solve().
execute()
App::DocumentObjectExecReturn * AssemblyObject::execute () override virtual
get called by the document to recompute this feature Normally this method get called in the processing of Document::recompute(). In execute() the output properties get recomputed with the data from linked objects and objects own properties.
Reimplemented from App::DocumentObject.
Definition at line 124 of file AssemblyObject.cpp.
References App::DocumentObject::execute(), App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), and solve().
Referenced by draftobjects.facebinder.Facebinder::addSubobjects(), Path.Dressup.Gui.Dogbone.ObjectDressup::boneStateList(), Path.Dressup.Tags.ObjectTagDressup::generateTags(), ArchRoof._Roof::getSubVolume(), ArchPanel.PanelCut::getWires(), src.Mod.PartDesign.Scripts.Spring.MySpring::onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid::onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped::onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt::onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder::onChanged(), MeasureCOM.MeasureCOM::onChanged(), Path.Main.Stock.StockFromBase::onChanged(), Path.Main.Stock.StockCreateBox::onChanged(), Path.Main.Stock.StockCreateCylinder::onChanged(), FeaturePython.DistanceBolt::onChanged(), draftobjects.draftlink.DraftLink::onDocumentRestored(), ArchSchedule._ArchSchedule::setSpreadsheetData(), and draftobjects.array.Array::update_properties_0v21().
exportAsASMT()
void AssemblyObject::exportAsASMT (std::string fileName)
Definition at line 452 of file AssemblyObject.cpp.
References fixGroundedParts(), getJoints(), jointParts(), and makeMbdAssembly().
fixGroundedPart()
void AssemblyObject::fixGroundedPart (App::DocumentObject * obj, Base::Placement & plc, std::string & jointName)
Definition at line 820 of file AssemblyObject.cpp.
References App::DocumentObject::getFullName(), getMbDPart(), makeMbdMarker(), and App::Extension::name().
Referenced by fixGroundedParts().
fixGroundedParts()
std::unordered_set< App::DocumentObject * > AssemblyObject::fixGroundedParts ()
Definition at line 804 of file AssemblyObject.cpp.
References fixGroundedPart(), getGroundedParts(), App::GeoFeature::getPlacementFromProp(), and Path.Post.scripts.refactored_centroid_post::str.
Referenced by exportAsASMT(), generateSimulation(), and solve().
generateSimulation()
int AssemblyObject::generateSimulation (App::DocumentObject * sim)
Definition at line 180 of file AssemblyObject.cpp.
References Base::Console(), create_mbdSimulationParameters(), Base::ConsoleSingleton::Error(), fixGroundedParts(), getJoints(), getMotionsFromSimulation(), jointParts(), makeMbdAssembly(), and removeUnconnectedJoints().
getConnectedParts()
std::vector< ObjRef > AssemblyObject::getConnectedParts (App::DocumentObject * part, const std::vector< App::DocumentObject * > & joints)
Definition at line 978 of file AssemblyObject.cpp.
References Assembly::getMovingPartFromRef(), and isJointTypeConnecting().
Referenced by traverseAndMarkConnectedParts().
getDownstreamParts()
std::vector< ObjRef > AssemblyObject::getDownstreamParts (App::DocumentObject * part, App::DocumentObject * joint = nullptr)
Definition at line 1868 of file AssemblyObject.cpp.
References Assembly::getJointActivated(), getJoints(), isPartConnected(), Assembly::setJointActivated(), and traverseAndMarkConnectedParts().
getExplodedViewGroup()
ViewGroup * AssemblyObject::getExplodedViewGroup () const
Definition at line 622 of file AssemblyObject.cpp.
References toolbit-attributes::doc, Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), and App::OriginGroupExtension::hasObject().
getGroundedJoints()
std::vector< App::DocumentObject * > AssemblyObject::getGroundedJoints ()
Definition at line 695 of file AssemblyObject.cpp.
References getJointGroup(), and App::GroupExtension::getObjects().
Referenced by getGroundedParts().
getGroundedParts()
std::unordered_set< App::DocumentObject * > AssemblyObject::getGroundedParts ()
Definition at line 760 of file AssemblyObject.cpp.
References getGroundedJoints(), App::PropertyLink::getValue(), App::PropertyEnumeration::getValueAsString(), App::PropertyListsT< T, ListT, ParentT >::getValues(), App::GroupExtension::Group, Base::BaseClass::isDerivedFrom(), Part::AttachExtension::MapMode, replaceobj::objs, and App::OriginGroupExtension::Origin.
Referenced by fixGroundedParts(), isPartConnected(), isPartGrounded(), and validateNewPlacements().
getGroup()
template<typename T > T * AssemblyObject::getGroup
Definition at line 601 of file AssemblyObject.cpp.
References toolbit-attributes::doc, App::DocumentObject::getDocument(), toolbit-attributes::group, and App::OriginGroupExtension::hasObject().
getJointGroup()
JointGroup * AssemblyObject::getJointGroup () const
Definition at line 617 of file AssemblyObject.cpp.
References Assembly::getJointGroup().
Referenced by getGroundedJoints(), and getJoints().
getJointOfPartConnectingToGround()
App::DocumentObject * AssemblyObject::getJointOfPartConnectingToGround (App::DocumentObject * part, std::string & name)
Definition at line 568 of file AssemblyObject.cpp.
References getJointsOfPart(), Assembly::getMovingPartFromRef(), isJointConnectingPartToGround(), and App::Extension::name().
Referenced by getUpstreamMovingPart(), and getUpstreamParts().
getJoints()
std::vector< App::DocumentObject * > AssemblyObject::getJoints (bool updateJCS = true, bool delBadJoints = false, bool subJoints = true)
Definition at line 639 of file AssemblyObject.cpp.
References App::DocumentObject::getDocument(), getJointGroup(), Assembly::getMovingPartFromRef(), App::GroupExtension::getObjects(), getSubAssemblies(), recomputeJointPlacements(), and App::Document::removeObject().
Referenced by doDragStep(), exportAsASMT(), generateSimulation(), getDownstreamParts(), getJointsOfObj(), getJointsOfPart(), isPartConnected(), slidingPartIndex(), solve(), Assembly::AssemblyLink::synchronizeJoints(), and undoSolve().
getJointsOfObj()
std::vector< App::DocumentObject * > AssemblyObject::getJointsOfObj (App::DocumentObject * obj)
Definition at line 720 of file AssemblyObject.cpp.
References getJoints(), and Assembly::getObjFromRef().
getJointsOfPart()
std::vector< App::DocumentObject * > AssemblyObject::getJointsOfPart (App::DocumentObject * part)
Definition at line 740 of file AssemblyObject.cpp.
References getJoints(), and Assembly::getMovingPartFromRef().
Referenced by getJointOfPartConnectingToGround(), getMbDData(), and isJointConnectingPartToGround().
getMbDData()
AssemblyObject::MbDPartData AssemblyObject::getMbDData (App::DocumentObject * obj)
Definition at line 1763 of file AssemblyObject.cpp.
References Assembly::Fixed, App::DocumentObject::getFullName(), getJointsOfPart(), Assembly::getJointType(), Assembly::getMovingPartFromRef(), App::GeoFeature::getPlacementFromProp(), Base::Placement::inverse(), makeMbdPart(), and Path.Post.scripts.refactored_centroid_post::str.
Referenced by getMbDPart(), getRackPinionMarkers(), and handleOneSideOfJoint().
getMbDPart()
std::shared_ptr< ASMTPart > AssemblyObject::getMbDPart (App::DocumentObject * obj)
Definition at line 1811 of file AssemblyObject.cpp.
References getMbDData(), and Assembly::AssemblyObject::MbDPartData::part.
Referenced by doDragStep(), and fixGroundedPart().
getMbdPlacement()
Base::Placement AssemblyObject::getMbdPlacement (std::shared_ptr< MbD::ASMTPart > mbdPart)
Definition at line 340 of file AssemblyObject.cpp.
References RobotExample::pos, MovieTool::x, and MovieTool::y.
Referenced by setNewPlacements(), and validateNewPlacements().
getMotionsFromSimulation()
std::vector< App::DocumentObject * > AssemblyObject::getMotionsFromSimulation (App::DocumentObject * sim)
Definition at line 216 of file AssemblyObject.cpp.
References App::ExtensionContainer::getPropertyByName(), and App::PropertyListsT< T, ListT, ParentT >::getValue().
Referenced by generateSimulation().
getObjMass()
double AssemblyObject::getObjMass (App::DocumentObject * obj)
Definition at line 1948 of file AssemblyObject.cpp.
getPyObject()
PyObject * AssemblyObject::getPyObject () override virtual
getPyObject returns the Python binding object
Returns
the Python binding object
Reimplemented from App::Part.
Definition at line 115 of file AssemblyObject.cpp.
References Py::SmartPtr::is(), Py::new_reference_to(), and App::DocumentObject::PythonObject.
getRackPinionMarkers()
void AssemblyObject::getRackPinionMarkers (App::DocumentObject * joint, std::string & markerNameI, std::string & markerNameJ)
Definition at line 1626 of file AssemblyObject.cpp.
References Base::Console(), Base::Vector3< float_type >::Cross(), Base::Vector3< float_type >::GetAngle(), App::DocumentObject::getFullName(), App::GeoFeature::getGlobalPlacement(), getMbDData(), Assembly::getMovingPartFromRef(), App::DocumentObject::getNameInDocument(), Assembly::getObjFromRef(), App::GeoFeature::getPlacementFromProp(), App::ExtensionContainer::getPropertyByName(), Base::Placement::getRotation(), handleOneSideOfJoint(), Base::Placement::inverse(), Base::Placement::isIdentity(), makeMbdMarker(), Base::Rotation::multVec(), Assembly::AssemblyObject::MbDPartData::offsetPlc, Assembly::AssemblyObject::MbDPartData::part, Base::Placement::setRotation(), slidingPartIndex(), Assembly::swapJCS(), and Base::ConsoleSingleton::Warning().
Referenced by makeMbdJoint().
getSubAssemblies()
std::vector< AssemblyLink * > AssemblyObject::getSubAssemblies ()
Definition at line 1967 of file AssemblyObject.cpp.
References toolbit-attributes::doc, Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), and App::OriginGroupExtension::hasObject().
Referenced by getJoints().
getUpstreamMovingPart()
App::DocumentObject * AssemblyObject::getUpstreamMovingPart (App::DocumentObject * part, App::DocumentObject *& joint, std::string & name)
Definition at line 1929 of file AssemblyObject.cpp.
References Assembly::Fixed, getJointOfPartConnectingToGround(), Assembly::getJointType(), Assembly::getMovingPartFromRef(), isPartGrounded(), and App::Extension::name().
getUpstreamParts()
std::vector< App::DocumentObject * > AssemblyObject::getUpstreamParts (App::DocumentObject * part, int limit = 0)
Definition at line 1901 of file AssemblyObject.cpp.
References getJointOfPartConnectingToGround(), Assembly::getMovingPartFromRef(), isPartGrounded(), and App::Extension::name().
getViewProviderName()
const char* Assembly::AssemblyObject::getViewProviderName () const inline override virtual
returns the type name of the ViewProvider
Reimplemented from App::Part.
Definition at line 85 of file AssemblyObject.h.
handleOneSideOfJoint()
std::string AssemblyObject::handleOneSideOfJoint (App::DocumentObject * joint, const char * propRefName, const char * propPlcName)
Definition at line 1581 of file AssemblyObject.cpp.
References Base::Console(), App::DocumentObject::getFullName(), App::GeoFeature::getGlobalPlacement(), getMbDData(), Assembly::getMovingPartFromRef(), App::DocumentObject::getNameInDocument(), Assembly::getObjFromRef(), App::GeoFeature::getPlacementFromProp(), App::ExtensionContainer::getPropertyByName(), Base::Placement::inverse(), Base::Placement::isIdentity(), makeMbdMarker(), Assembly::AssemblyObject::MbDPartData::offsetPlc, Assembly::AssemblyObject::MbDPartData::part, and Base::ConsoleSingleton::Warning().
Referenced by getRackPinionMarkers(), and makeMbdJoint().
isJointConnectingPartToGround()
bool AssemblyObject::isJointConnectingPartToGround (App::DocumentObject * joint, const char * partPropName)
Definition at line 850 of file AssemblyObject.cpp.
References App::DocumentObject::getFullName(), Assembly::getJointActivated(), getJointsOfPart(), Assembly::getMovingPartFromRef(), BOPTools.ShapeMerge::isConnected(), isJointTypeConnecting(), isPartConnected(), isPartGrounded(), and Assembly::setJointActivated().
Referenced by getJointOfPartConnectingToGround().
isJointTypeConnecting()
bool AssemblyObject::isJointTypeConnecting (App::DocumentObject * joint)
Definition at line 901 of file AssemblyObject.cpp.
References Assembly::Belt, Assembly::Gears, Assembly::getJointType(), Assembly::RackPinion, and Assembly::Screw.
Referenced by getConnectedParts(), and isJointConnectingPartToGround().
isObjInSetOfObjRefs()
bool AssemblyObject::isObjInSetOfObjRefs (App::DocumentObject * obj, const std::vector< ObjRef > & pairs)
Definition at line 913 of file AssemblyObject.cpp.
Referenced by traverseAndMarkConnectedParts().
isPartConnected()
bool AssemblyObject::isPartConnected (App::DocumentObject * part)
Definition at line 1031 of file AssemblyObject.cpp.
References getGroundedParts(), getJoints(), and traverseAndMarkConnectedParts().
Referenced by getDownstreamParts(), and isJointConnectingPartToGround().
isPartGrounded()
bool AssemblyObject::isPartGrounded (App::DocumentObject * part)
Definition at line 1014 of file AssemblyObject.cpp.
References App::DocumentObject::getFullName(), and getGroundedParts().
Referenced by getUpstreamMovingPart(), getUpstreamParts(), and isJointConnectingPartToGround().
jointParts()
void AssemblyObject::jointParts (std::vector< App::DocumentObject * > joints)
Definition at line 1061 of file AssemblyObject.cpp.
References makeMbdJoint().
Referenced by exportAsASMT(), generateSimulation(), and solve().
makeMbdAssembly()
std::shared_ptr< ASMTAssembly > AssemblyObject::makeMbdAssembly ()
Definition at line 555 of file AssemblyObject.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), and App::Application::GetParameterGroupByPath().
Referenced by exportAsASMT(), generateSimulation(), and solve().
makeMbdJoint()
std::vector< std::shared_ptr< MbD::ASMTJoint > > AssemblyObject::makeMbdJoint (App::DocumentObject * joint)
Definition at line 1364 of file AssemblyObject.cpp.
References Assembly::Cylindrical, DraftVecUtils::find(), App::DocumentObject::getFullName(), Assembly::getJointType(), App::ExtensionContainer::getPropertyByName(), getRackPinionMarkers(), App::PropertyString::getValue(), App::PropertyBool::getValue(), handleOneSideOfJoint(), makeMbdJointOfType(), Assembly::RackPinion, Assembly::Revolute, and Assembly::Slider.
Referenced by jointParts().
makeMbdJointDistance()
std::shared_ptr< ASMTJoint > AssemblyObject::makeMbdJointDistance (App::DocumentObject * joint)
Definition at line 1172 of file AssemblyObject.cpp.
References Assembly::CircleCircle, Assembly::ConeCone, Assembly::ConeSphere, Assembly::ConeTorus, Assembly::CurveCone, Assembly::CurveCylinder, Assembly::CurvePlane, Assembly::CurveSphere, Assembly::CurveTorus, Assembly::CylinderCone, Assembly::CylinderCylinder, Assembly::CylinderSphere, Assembly::CylinderTorus, Assembly::getDistanceType(), Assembly::getEdgeRadius(), Assembly::getElementFromProp(), Assembly::getFaceRadius(), Assembly::getJointDistance(), Assembly::getLinkedObjFromRef(), Assembly::LineCircle, Assembly::LineCone, Assembly::LineCylinder, Assembly::LineLine, Assembly::LinePlane, Assembly::LineSphere, Assembly::LineTorus, Assembly::PlaneCone, Assembly::PlaneCylinder, Assembly::PlanePlane, Assembly::PlaneSphere, Assembly::PlaneTorus, Assembly::PointCone, Assembly::PointCurve, Assembly::PointCylinder, Assembly::PointLine, Assembly::PointPlane, Assembly::PointPoint, Assembly::PointSphere, Assembly::PointTorus, Assembly::SphereSphere, Assembly::TorusSphere, Assembly::TorusTorus, and Path.Post.scripts.grbl_post::type.
Referenced by makeMbdJointOfType().
makeMbdJointOfType()
std::shared_ptr< ASMTJoint > AssemblyObject::makeMbdJointOfType (App::DocumentObject * joint, JointType jointType)
Definition at line 1096 of file AssemblyObject.cpp.
References Assembly::Angle, Assembly::Ball, Assembly::Belt, Assembly::Cylindrical, Assembly::Distance, Assembly::Fixed, Base::fmod(), Assembly::Gears, Assembly::getJointDistance(), Assembly::getJointDistance2(), M_PI, makeMbdJointDistance(), Assembly::Parallel, Assembly::Perpendicular, Assembly::RackPinion, Assembly::Revolute, Assembly::Screw, Assembly::Slider, slidingPartIndex(), Assembly::swapJCS(), Base::toRadians(), and Path.Post.scripts.grbl_post::type.
Referenced by makeMbdJoint().
makeMbdMarker()
std::shared_ptr< ASMTMarker > AssemblyObject::makeMbdMarker (std::string & name, Base::Placement & plc)
Definition at line 1848 of file AssemblyObject.cpp.
References Base::Placement::getPosition(), Base::Placement::getRotation(), Base::Matrix4D::getRow(), Base::Rotation::getValue(), App::Extension::name(), RobotExample::pos, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by fixGroundedPart(), getRackPinionMarkers(), and handleOneSideOfJoint().
makeMbdPart()
std::shared_ptr< ASMTPart > AssemblyObject::makeMbdPart (std::string & name, Base::Placement plc = Base::Placement(), double mass = 1.0)
Definition at line 1821 of file AssemblyObject.cpp.
References Base::Placement::getPosition(), Base::Placement::getRotation(), Base::Matrix4D::getRow(), Base::Rotation::getValue(), App::Extension::name(), RobotExample::pos, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by getMbDData().
numberOfFrames()
size_t Assembly::AssemblyObject::numberOfFrames ()
Definition at line 248 of file AssemblyObject.cpp.
postDrag()
void AssemblyObject::postDrag ()
Definition at line 391 of file AssemblyObject.cpp.
preDrag()
void AssemblyObject::preDrag (std::vector< App::DocumentObject * > dragParts)
Definition at line 253 of file AssemblyObject.cpp.
References DraftVecUtils::find(), Base::Placement::isIdentity(), and solve().
recomputeJointPlacements()
void AssemblyObject::recomputeJointPlacements (std::vector< App::DocumentObject * > joints) static
Definition at line 523 of file AssemblyObject.cpp.
References toolbit-attributes::args, and App::PropertyPythonObject::getValue().
Referenced by getJoints(), and Assembly::AssemblyLink::synchronizeJoints().
redrawJointPlacement()
void AssemblyObject::redrawJointPlacement (App::DocumentObject * joint) static
Definition at line 505 of file AssemblyObject.cpp.
References App::ExtensionContainer::getPropertyByName(), App::DocumentObject::purgeTouched(), and App::PropertyPlacement::setValue().
Referenced by doDragStep(), and redrawJointPlacements().
redrawJointPlacements()
void AssemblyObject::redrawJointPlacements (std::vector< App::DocumentObject * > joints) static
Definition at line 494 of file AssemblyObject.cpp.
References redrawJointPlacement().
Referenced by Assembly::AssemblyLink::onChanged(), and solve().
removeUnconnectedJoints()
void AssemblyObject::removeUnconnectedJoints (std::vector< App::DocumentObject * > & joints, std::unordered_set< App::DocumentObject * > groundedObjs)
Definition at line 927 of file AssemblyObject.cpp.
References traverseAndMarkConnectedParts().
Referenced by generateSimulation(), and solve().
savePlacementsForUndo()
void AssemblyObject::savePlacementsForUndo ()
Definition at line 396 of file AssemblyObject.cpp.
References App::ExtensionContainer::getPropertyByName(), and App::PropertyPlacement::getValue().
Referenced by solve().
setNewPlacements()
void AssemblyObject::setNewPlacements ()
Definition at line 465 of file AssemblyObject.cpp.
References getMbdPlacement(), App::ExtensionContainer::getPropertyByName(), and App::DocumentObject::purgeTouched().
Referenced by doDragStep(), and solve().
setObjMasses()
void AssemblyObject::setObjMasses (std::vector< std::pair< App::DocumentObject *, double >> objectMasses)
Definition at line 1962 of file AssemblyObject.cpp.
slidingPartIndex()
int AssemblyObject::slidingPartIndex (App::DocumentObject * joint)
Definition at line 1717 of file AssemblyObject.cpp.
References getJoints(), Assembly::getJointType(), Assembly::getMovingPartFromRef(), Assembly::getObjFromRef(), App::GeoFeature::getPlacementFromProp(), Base::Placement::getRotation(), Base::Rotation::getYawPitchRoll(), and Assembly::Slider.
Referenced by getRackPinionMarkers(), and makeMbdJointOfType().
solve()
int AssemblyObject::solve (bool enableRedo = false, bool updateJCS = true)
Definition at line 136 of file AssemblyObject.cpp.
References SCL.SimpleDataTypes::e, ensureIdentityPlacements(), FC_ERR, fixGroundedParts(), getJoints(), jointParts(), makeMbdAssembly(), redrawJointPlacements(), removeUnconnectedJoints(), savePlacementsForUndo(), and setNewPlacements().
Referenced by execute(), and preDrag().
traverseAndMarkConnectedParts()
void AssemblyObject::traverseAndMarkConnectedParts (App::DocumentObject * currentPart, std::vector< ObjRef > & connectedParts, const std::vector< App::DocumentObject * > & joints)
Definition at line 962 of file AssemblyObject.cpp.
References getConnectedParts(), and isObjInSetOfObjRefs().
Referenced by getDownstreamParts(), isPartConnected(), and removeUnconnectedJoints().
undoSolve()
void AssemblyObject::undoSolve ()
Definition at line 420 of file AssemblyObject.cpp.
References getJoints(), App::ExtensionContainer::getPropertyByName(), and App::PropertyPlacement::setValue().
updateForFrame()
int Assembly::AssemblyObject::updateForFrame (size_t index, bool updateJCS = true)
Definition at line 230 of file AssemblyObject.cpp.
validateNewPlacements()
bool AssemblyObject::validateNewPlacements ()
Definition at line 357 of file AssemblyObject.cpp.
References Base::Console(), getGroundedParts(), getMbdPlacement(), Base::Placement::isSame(), and Base::ConsoleSingleton::Warning().
Referenced by doDragStep().
The documentation for this class was generated from the following files:
AssemblyObject.h
AssemblyObject.cpp