FreeCAD: TestJtReader Class Reference
TestJtReader Class Reference
#include <TestJtReader.h>
Public Member Functions
TestJtReader ()
~TestJtReader ()
void read (void)
Public Member Functions inherited from JtReader
JtReader ()
~JtReader ()
void setFile (const std::string fileName)
const std::vector< TOC_Entry > & readToc ()
void readSegment (int tocIndex)
void readLodSegment (const TOC_Entry &, LodHandler &)
Additional Inherited Members
Static Public Attributes inherited from JtReader
static const GUID TriStripSetShapeLODElement_ID
Protected Attributes inherited from JtReader
std::string _fileName
vector< TOC_Entry > TocEntries
Detailed Description
Definition at line 9 of file TestJtReader.h.
Constructor & Destructor Documentation
TestJtReader()
TestJtReader::TestJtReader ()
Definition at line 35 of file TestJtReader.cpp.
~TestJtReader()
TestJtReader::~TestJtReader ()
Definition at line 39 of file TestJtReader.cpp.
Member Function Documentation
read()
void TestJtReader::read (void)
Definition at line 42 of file TestJtReader.cpp.
References Base::Console(), buildPsets::handler, SplineSurface::i, Base::ConsoleSingleton::Log(), JtReader::readLodSegment(), and JtReader::TocEntries.
The documentation for this class was generated from the following files:
TestJtReader.h
TestJtReader.cpp