FreeCAD: Gui::Dialog::DlgSettingsColorGradientImp Class Reference
Gui::Dialog::DlgSettingsColorGradientImp Class Reference
#include <DlgSettingsColorGradientImp.h>
Public Member Functions
DlgSettingsColorGradientImp (const App::ColorGradient &cg, QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgSettingsColorGradientImp () override
void accept () override
Color profile
App::ColorGradientProfile getProfile () const
void setProfile (const App::ColorGradientProfile &pro)
Parameter range and scale
void setNumberOfDecimals (int, float fMin, float fMax)
int numberOfDecimals () const
void colorModelChanged ()
Detailed Description
The DlgSettingsColorGradientImp class implements a preference page to change settings for the color gradient bar.
Author
Werner Mayer
Definition at line 42 of file DlgSettingsColorGradientImp.h.
Constructor & Destructor Documentation
DlgSettingsColorGradientImp()
DlgSettingsColorGradientImp::DlgSettingsColorGradientImp (const App::ColorGradient & cg, QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Constructs a DlgSettingsColorGradientImp as a child of 'parent', with the name 'name' and widget flags set to 'f'.
Definition at line 48 of file DlgSettingsColorGradientImp.cpp.
References App::ColorGradient::getColorModelNames(), App::ColorGradient::getProfile(), Gui::QtTools::horizontalAdvance(), and setProfile().
~DlgSettingsColorGradientImp()
DlgSettingsColorGradientImp::~DlgSettingsColorGradientImp () override default
Destroys the object and frees any allocated resources
Member Function Documentation
accept()
void DlgSettingsColorGradientImp::accept () override
Definition at line 249 of file DlgSettingsColorGradientImp.cpp.
References Path.Log::warning().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
colorModelChanged
void Gui::Dialog::DlgSettingsColorGradientImp::colorModelChanged () signal
Referenced by Gui::SoFCColorGradient::customize().
getProfile()
App::ColorGradientProfile DlgSettingsColorGradientImp::getProfile () const
Definition at line 121 of file DlgSettingsColorGradientImp.cpp.
References App::ColorGradientProfile::ctColors, App::ColorGradientProfile::fMax, App::ColorGradientProfile::fMin, App::Grayed, App::Invisible, Base::Flags< Enum >::setFlag(), App::ColorGradientProfile::tColorModel, App::ColorGradientProfile::tStyle, and App::ColorGradientProfile::visibility.
Referenced by Gui::SoFCColorGradient::customize(), and ArchPipe._ArchPipe::execute().
numberOfDecimals()
int DlgSettingsColorGradientImp::numberOfDecimals () const
Definition at line 244 of file DlgSettingsColorGradientImp.cpp.
Referenced by Gui::SoFCColorGradient::customize().
setNumberOfDecimals()
void DlgSettingsColorGradientImp::setNumberOfDecimals (int val, float fMin, float fMax)
Definition at line 238 of file DlgSettingsColorGradientImp.cpp.
References toolbit-attributes::val.
Referenced by Gui::SoFCColorGradient::customize().
setProfile()
void DlgSettingsColorGradientImp::setProfile (const App::ColorGradientProfile & pro)
Definition at line 133 of file DlgSettingsColorGradientImp.cpp.
References App::ColorGradientProfile::ctColors, App::ColorGradientProfile::fMax, App::ColorGradientProfile::fMin, App::Grayed, App::Invisible, App::ColorGradientProfile::tColorModel, Base::Flags< Enum >::testFlag(), App::ColorGradientProfile::tStyle, and App::ColorGradientProfile::visibility.
Referenced by DlgSettingsColorGradientImp().
The documentation for this class was generated from the following files:
DlgSettingsColorGradientImp.h
DlgSettingsColorGradientImp.cpp