FreeCAD: Part::Feature Class Reference
Part::Feature Class Reference
#include <PartFeature.h>
Public Member Functions
Feature ()
Constructor.
~Feature () override
Public Member Functions inherited from App::GeoFeature
GeoFeature ()
Constructor.
~GeoFeature () override
virtual void transformPlacement (const Base::Placement &transform)
transformPlacement applies transform to placement of this shape. Override this function to propagate the change of placement to base features, for example. By the time of writing this comment, the function was only called by alignment task (Edit->Alignment)
Base::Placement globalPlacement () const
Deprecated. Calculates the placement in the global reference coordinate system.
virtual DocumentObject * getElementOwner (const Data::MappedName &) const
Return the object that owns the shape that contains the give element name.
virtual std::vector< const char * > getElementTypes (bool all=true) const
virtual std::vector< Data::IndexedName > getHigherElements (const char *name, bool silent=false) const
Return the higher level element names of the given element.
Public Member Functions inherited from App::DocumentObject
virtual const char * getViewProviderNameOverride () const
DocumentObject ()
Constructor.
~DocumentObject () override
const char * getDagKey () const
returns a value that uniquely identifies this DocumentObject.
const char * getNameInDocument () const
returns the name which is set in the document for this object (not the name property!)
long getID () const
Return the object ID that is unique within its owner document.
std::string getExportName (bool forced=false) const
returns the name that is safe to be exported to other document
std::string getFullName () const override
Return the object full name of the form DocName::ObjName.
std::string getFullLabel () const
Return the object full label in the form DocName::ObjName.
bool isAttachedToDocument () const override
const char * detachFromDocument () override
App::Document * getDocument () const
gets the document in which this Object is handled
void touch (bool noRecompute=false)
set this document object touched (cause recomputation on dependent features)
bool isTouched () const
test if this document object is touched
void enforceRecompute ()
Enforce this document object to be recomputed.
bool mustRecompute () const
Test if this document object must be recomputed.
void purgeTouched ()
reset this document object touched
bool isError () const
set this feature to error
bool isValid () const
void purgeError ()
remove the error from the object
bool isRecomputing () const
returns true if this objects is currently recomputing
bool isRestoring () const
returns true if this objects is currently restoring from file
bool isRemoving () const
returns true if this objects is currently removed from the document
void freeze ()
set this document object freezed (prevent recomputation)
void unfreeze (bool noRecompute=false)
set this document object unfreezed (and touch it)
bool isFreezed () const
returns true if this objects is currently freezed
unsigned long getStatus () const
return the status bits
bool testStatus (ObjectStatus pos) const
void setStatus (ObjectStatus pos, bool on)
int isExporting () const
virtual int setElementVisible (const char *element, bool visible)
virtual int isElementVisible (const char *element) const
virtual bool hasChildElement () const
return true to activate tree view group object handling and element visibility
const std::vector< App::DocumentObject * > & getOutList () const
returns a list of objects this object is pointing to by Links
std::vector< App::DocumentObject * > getOutList (int option) const
void getOutList (int option, std::vector< App::DocumentObject * > &res) const
std::vector< App::DocumentObject * > getOutListOfProperty (App::Property *) const
returns a list of objects linked by the property
std::vector< App::DocumentObject * > getOutListRecursive () const
returns a list of objects this object is pointing to by Links and all further descended
void clearOutListCache () const
clear internal out list cache
std::vector< std::list< App::DocumentObject * > > getPathsByOutList (App::DocumentObject *to) const
get all possible paths from this to another object following the OutList
const std::vector< App::DocumentObject * > & getInList () const
std::vector< App::DocumentObject * > getInListRecursive () const
get all objects link directly or indirectly to this object
void getInListEx (std::set< App::DocumentObject * > &inSet, bool recursive, std::vector< App::DocumentObject * > *inList=nullptr) const
std::set< App::DocumentObject * > getInListEx (bool recursive) const
DocumentObjectGroup * getGroup () const
get group if object is part of a group, otherwise 0 is returned
bool isInInListRecursive (DocumentObject *objToTest) const
test if this object is in the InList and recursive further down
bool isInInList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the InList
bool isInOutListRecursive (DocumentObject *objToTest) const
test if the given object is in the OutList and recursive further down
bool isInOutList (DocumentObject *objToTest) const
test if this object is directly (non recursive) in the OutList
void _removeBackLink (DocumentObject *)
internal, used by PropertyLink to maintain DAG back links
void _addBackLink (DocumentObject *)
internal, used by PropertyLink to maintain DAG back links
bool testIfLinkDAGCompatible (DocumentObject *linkTo) const
testIfLinkIsDAG tests a link that is about to be created for circular references.
bool testIfLinkDAGCompatible (const std::vector< DocumentObject * > &linksTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSubList &linksTo) const
bool testIfLinkDAGCompatible (App::PropertyLinkSub &linkTo) const
virtual std::string getElementMapVersion (const App::Property *prop, bool restored=false) const
virtual bool checkElementMapVersion (const App::Property *prop, const char *ver) const
Return true to signal re-generation of geometry element names.
bool recomputeFeature (bool recursive=false)
const char * getStatusString () const
get the status Message
virtual void onLostLinkToObject (DocumentObject *)
std::vector< DocumentObject * > getSubObjectList (const char *subname, std::vector< int > *subsizes=nullptr, bool flatten=false) const
virtual std::vector< std::string > getSubObjects (int reason=0) const
std::vector< std::pair< App::DocumentObject *, std::string > > getParents (int depth=0) const
Obtain top parents and subnames of this object using its InList.
App::DocumentObject * getFirstParent () const
Obtain the first parent group of this object.
virtual DocumentObject * getLinkedObject (bool recurse=true, Base::Matrix4D *mat=nullptr, bool transform=false, int depth=0) const
virtual bool canLinkProperties () const
virtual bool isLink () const
virtual bool isLinkGroup () const
virtual bool allowDuplicateLabel () const
virtual void onBeforeChangeLabel (std::string &newLabel)
void Save (Base::Writer &writer) const override
virtual void setExpression (const ObjectIdentifier &path, std::shared_ptr< App::Expression > expr)
void clearExpression (const ObjectIdentifier &path)
virtual const PropertyExpressionEngine::ExpressionInfo getExpression (const ObjectIdentifier &path) const
virtual void renameObjectIdentifiers (const std::map< App::ObjectIdentifier, App::ObjectIdentifier > &paths)
const std::string & getOldLabel () const
const char * getViewProviderNameStored () const
bool removeDynamicProperty (const char *prop) override
App::Property * addDynamicProperty (const char *type, const char *name=nullptr, const char *group=nullptr, const char *doc=nullptr, short attr=0, bool ro=false, bool hidden=false) override
App::DocumentObject * resolve (const char *subname, App::DocumentObject **parent=nullptr, std::string *childName=nullptr, const char **subElement=nullptr, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=true, int depth=0) const
App::DocumentObject * resolveRelativeLink (std::string &subname, App::DocumentObject *&link, std::string &linkSub) const
virtual bool adjustRelativeLinks (const std::set< App::DocumentObject * > &inList, std::set< App::DocumentObject * > *visited=nullptr)
virtual int canLoadPartial () const
virtual void onUpdateElementReference (const Property *)
virtual bool redirectSubName (std::ostringstream &ss, DocumentObject *topParent, DocumentObject *child) const
Public Member Functions inherited from App::TransactionalObject
TransactionalObject ()
Constructor.
~TransactionalObject () override
Public Member Functions inherited from App::ExtensionContainer
ExtensionContainer ()
~ExtensionContainer () override
void registerExtension (Base::Type extension, App::Extension *ext)
bool hasExtension (Base::Type, bool derived=true) const
bool hasExtension (const std::string &name) const
bool hasExtensions () const
App::Extension * getExtension (Base::Type, bool derived=true, bool no_except=false) const
App::Extension * getExtension (const std::string &name) const
template<typename ExtensionT >
ExtensionT * getExtension () const
template<typename ExtensionT >
ExtensionT * getExtensionByType (bool no_except=false, bool derived=true) const
std::vector< Extension * > getExtensionsDerivedFrom (Base::Type type) const
template<typename ExtensionT >
std::vector< ExtensionT * > getExtensionsDerivedFromType () const
ExtensionIterator extensionBegin ()
ExtensionIterator extensionEnd ()
Property * getPropertyByName (const char *name) const override
find a property by its name
template<typename T >
T * getPropertyByName (const char *name) const
find a property by its name, dynamic cased to specified type
const char * getPropertyName (const Property *prop) const override
get the name of a property
void getPropertyMap (std::map< std::string, Property * > &Map) const override
get all properties of the class (including properties of the parent)
void getPropertyList (std::vector< Property * > &List) const override
get all properties of the class (including properties of the parent)
short getPropertyType (const Property *prop) const override
get the Type of a Property
short getPropertyType (const char *name) const override
get the Type of a named Property
const char * getPropertyGroup (const Property *prop) const override
get the Group of a Property
const char * getPropertyGroup (const char *name) const override
get the Group of a named Property
const char * getPropertyDocumentation (const Property *prop) const override
get the Group of a Property
const char * getPropertyDocumentation (const char *name) const override
get the Group of a named Property
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void saveExtensions (Base::Writer &writer) const
void restoreExtensions (Base::XMLReader &reader)
void handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName) override
void handleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop) override
Public Member Functions inherited from App::PropertyContainer
PropertyContainer ()
~PropertyContainer () override
unsigned int getMemSize () const override
virtual void getPropertyNamedList (std::vector< std::pair< const char *, Property * > > &List) const
get all properties with their names, may contain duplicates and aliases
void setPropertyStatus (unsigned char bit, bool value)
set the Status bit of all properties at once
bool isReadOnly (const Property *prop) const
check if the property is read-only
bool isReadOnly (const char *name) const
check if the named property is read-only
bool isHidden (const Property *prop) const
check if the property is hidden
bool isHidden (const char *name) const
check if the named property is hidden
DynamicProperty::PropData getDynamicPropertyData (const Property *prop) const
bool changeDynamicProperty (const Property *prop, const char *group, const char *doc)
virtual std::vector< std::string > getDynamicPropertyNames () const
virtual App::Property * getDynamicPropertyByName (const char *name) const
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
virtual void beforeSave () const
virtual void editProperty (const char *)
const char * getPropertyPrefix () const
void setPropertyPrefix (const char *prefix)
PropertyContainer (const PropertyContainer &)=delete
PropertyContainer & operator= (const PropertyContainer &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Attributes
PropertyPartShape Shape
Materials::PropertyMaterial ShapeMaterial
Public Attributes inherited from App::GeoFeature
PropertyPlacement Placement
Public Attributes inherited from App::DocumentObject
PropertyString Label
PropertyString Label2
PropertyExpressionEngine ExpressionEngine
PropertyBool Visibility
Allow control visibility status in App name space.
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalBeforeChange
signal before changing a property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalChanged
signal on changed property of this object
boost::signals2::signal< void(const App::DocumentObject &, const App::Property &)> signalEarlyChanged
signal on changed property of this object before document scoped signalChangedObject
methods override feature
short mustExecute () const override
const char * getViewProviderName () const override
returns the type name of the ViewProvider
const App::PropertyComplexGeoData * getPropertyOfGeometry () const override
PyObject * getPyObject () override
getPyObject returns the Python binding object
App::ElementNamePair getElementName (const char *name, ElementNameType type=Normal) const override
TopLoc_Location getLocation () const
DocumentObject * getSubObject (const char *subname, PyObject **pyObj, Base::Matrix4D *mat, bool transform, int depth) const override
App::Material getMaterialAppearance () const override
Virtual function to get an App::Material object describing the appearance.
void setMaterialAppearance (const App::Material &material) override
Virtual function to set the appearance with an App::Material object.
bool getCameraAlignmentDirection (Base::Vector3d &direction, const char *subname) const override
Virtual function to get the camera alignment direction.
const std::vector< std::string > & searchElementCache (const std::string &element, Data::SearchOptions options=Data::SearchOption::CheckGeometry, double tol=1e-7, double atol=1e-10) const override
static std::list< Data::HistoryItem > getElementHistory (App::DocumentObject *obj, const char *name, bool recursive=true, bool sameType=false)
static QVector< Data::MappedElement > getRelatedElements (App::DocumentObject *obj, const char *name, HistoryTraceType sameType=HistoryTraceType::followTypeChange, bool withCache=true)
static QVector< Data::MappedElement > getElementFromSource (App::DocumentObject *obj, const char *subname, App::DocumentObject *src, const char *srcSub, bool single=false)
static TopoDS_Shape getShape (const App::DocumentObject *obj, const char *subname=nullptr, bool needSubElement=false, Base::Matrix4D *pmat=nullptr, App::DocumentObject **owner=nullptr, bool resolveLink=true, bool transform=true)
static TopoShape getTopoShape (const App::DocumentObject *obj, const char *subname=nullptr, bool needSubElement=false, Base::Matrix4D *pmat=nullptr, App::DocumentObject **owner=nullptr, bool resolveLink=true, bool transform=true, bool noElementMap=false)
static void clearShapeCache ()
static App::DocumentObject * getShapeOwner (const App::DocumentObject *obj, const char *subname=nullptr)
static bool hasShapeOwner (const App::DocumentObject *obj, const char *subname=nullptr)
static Feature * create (const TopoShape &shape, const char *name=nullptr, App::Document *document=nullptr)
static bool isElementMappingDisabled (App::PropertyContainer *container)
static void guessNewLink (std::string &replacementName, DocumentObject *base, const char *oldLink)
App::DocumentObjectExecReturn * recompute () override
recompute only this object
App::DocumentObjectExecReturn * execute () override
recalculate the feature
void onBeforeChange (const App::Property *prop) override
get called before the value is changed
void onChanged (const App::Property *prop) override
get called by the container when a property was changed
void copyMaterial (Feature *feature)
void copyMaterial (App::DocumentObject *link)
void registerElementCache (const std::string &prefix, PropertyPartShape *prop)
App::ElementNamePair getExportElementName (TopoShape shape, const char *name) const
ShapeHistory buildHistory (BRepBuilderAPI_MakeShape &, TopAbs_ShapeEnum type, const TopoDS_Shape &newS, const TopoDS_Shape &oldS)
ShapeHistory joinHistory (const ShapeHistory &, const ShapeHistory &)
Additional Inherited Members
Public Types inherited from App::GeoFeature
enum ElementNameType { Normal = 0, Import = 1, Export = 2 }
Specify the type of element name to return when calling getElementName()
Public Types inherited from App::DocumentObject
enum OutListOption { OutListNoExpression = 1, OutListNoHidden = 2, OutListNoXLinked = 4 }
OutList options.
enum GSReason { GS_DEFAULT, GS_SELECT }
reason of calling getSubObjects()
Public Types inherited from App::ExtensionContainer
using ExtensionIterator = std::map< Base::Type, App::Extension * >::iterator
Static Public Member Functions inherited from App::GeoFeature
static DocumentObject * resolveElement (const App::DocumentObject *obj, const char *subname, ElementNamePair &elementName, bool append=false, ElementNameType type=Normal, const DocumentObject *filter=nullptr, const char **element=nullptr, GeoFeature **geo=nullptr)
static bool hasMissingElement (const char *subname)
static Base::Placement getPlacementFromProp (DocumentObject *obj, const char *propName)
static Base::Placement getGlobalPlacement (DocumentObject *targetObj, DocumentObject *rootObj, const std::string &sub)
static Base::Placement getGlobalPlacement (DocumentObject *targetObj, PropertyXLinkSub *prop)
static Base::Placement getGlobalPlacement (const DocumentObject *obj)
Static Public Member Functions inherited from App::DocumentObject
static const std::string & hiddenMarker ()
static const char * hasHiddenMarker (const char *subname)
Check if the subname reference ends with hidden marker.
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Attributes inherited from App::DocumentObject
static DocumentObjectExecReturn * StdReturn
Protected Member Functions inherited from App::GeoFeature
void updateElementReference ()
ElementNamePair _getElementName (const char *name, const Data::MappedElement &mapped) const
Protected Member Functions inherited from App::DocumentObject
App::DocumentObjectExecReturn * executeExtensions ()
void setError ()
void resetError ()
void setDocument (App::Document *doc)
void onEarlyChange (const Property *prop) override
get called by the container when a property was changed
virtual void onDocumentRestored ()
get called after a document has been fully restored
virtual void onUndoRedoFinished ()
get called after an undo/redo transaction is finished
virtual void onSettingDocument ()
get called after setting the document
virtual void setupObject ()
get called after a brand new object was created
virtual void unsetupObject ()
get called when object is going to be removed from the document
void onPropertyStatusChanged (const Property &prop, unsigned long oldStatus) override
get called when a property status has changed
Protected Member Functions inherited from App::TransactionalObject
void onBeforeChangeProperty (Document *doc, const Property *prop)
Protected Member Functions inherited from App::PropertyContainer
virtual const PropertyData & getPropertyData () const
Static Protected Member Functions inherited from App::PropertyContainer
static const PropertyData * getPropertyDataPtr ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::DocumentObject
std::bitset< 32 > StatusBits
Py::SmartPtr PythonObject
python object of this class and all descendent
App::Document * _pDoc {nullptr}
pointer to the document this object belongs to
std::string oldLabel
Old label; used for renaming expressions.
const std::string * pcNameInDocument {nullptr}
Protected Attributes inherited from App::PropertyContainer
DynamicProperty dynamicProps
Detailed Description
Base class of all shape feature classes in FreeCAD
Definition at line 51 of file PartFeature.h.
Constructor & Destructor Documentation
Feature()
Feature::Feature ()
Constructor.
Definition at line 90 of file PartFeature.cpp.
References ADD_PROPERTY, Materials::MaterialManager::defaultMaterial(), and DrawingExample::Shape.
~Feature()
Feature::~Feature () override default
Member Function Documentation
buildHistory()
ShapeHistory Feature::buildHistory (BRepBuilderAPI_MakeShape & mkShape, TopAbs_ShapeEnum type, const TopoDS_Shape & newS, const TopoDS_Shape & oldS) protected
Build a history of changes MakeShape: The operation that created the changes, e.g. FCBRepAlgoAPI_Common type: The type of object we are interested in, e.g. TopAbs_FACE newS: The new shape that was created by the operation oldS: The original shape prior to the operation
Definition at line 1584 of file PartFeature.cpp.
References SplineSurface::i, Part::ShapeHistory::shapeMap, Path.Post.scripts.grbl_post::type, and Part::ShapeHistory::type.
Referenced by Part::MultiFuse::execute().
clearShapeCache()
void Feature::clearShapeCache () static
Definition at line 886 of file PartFeature.cpp.
copyMaterial() [1/2]
void Feature::copyMaterial (App::DocumentObject * link) protected
Definition at line 144 of file PartFeature.cpp.
References copyMaterial().
copyMaterial() [2/2]
void Feature::copyMaterial (Feature * feature) protected
Definition at line 132 of file PartFeature.cpp.
References Materials::MaterialManager::defaultMaterial(), Materials::Material::getUUID(), Materials::PropertyMaterial::getValue(), Materials::PropertyMaterial::setValue(), and ShapeMaterial.
Referenced by copyMaterial(), Part::Boolean::execute(), Part::MultiCommon::execute(), Part::MultiFuse::execute(), Part::Compound::execute(), Part::Mirroring::execute(), and Part::FilletBase::execute().
create()
Feature * Feature::create (const TopoShape & shape, const char * name = nullptr, App::Document * document = nullptr) static
Definition at line 1567 of file PartFeature.cpp.
References App::Document::addObject(), App::Application::getActiveDocument(), App::GetApplication(), App::Application::newDocument(), Part::PropertyPartShape::setValue(), and Shape.
execute()
App::DocumentObjectExecReturn * Feature::execute () override protected virtual
recalculate the feature
Reimplemented from App::DocumentObject.
Reimplemented in Part::Ellipse, Part::Wedge, PartDesign::Wedge, Part::Spiral, Part::Helix, PartDesign::Prism, Part::Torus, PartDesign::Torus, Part::Cone, Part::RegularPolygon, PartDesign::Ellipsoid, Part::Prism, PartDesign::Cone, Part::FilletBase, Part::Reverse, Part::Cylinder, Part::Refine, Part::Ellipsoid, PartDesign::Sphere, Part::Thickness, Part::Sphere, PartDesign::SubShapeBinder, Part::Plane, PartDesign::Cylinder, Part::Sweep, PartDesign::Transformed, Part::Line, Sketcher::SketchObject, PartDesign::ShapeBinder, Part::Loft, TechDraw::FeatureProjection, PartDesign::Box, PartDesign::Groove, PartDesign::FeaturePrimitive, PartDesign::Revolution, Surface::GeomFillSurface, PartDesign::Boolean, Surface::FeatureBlendCurve, PartDesign::Pad, PartDesign::Draft, Surface::Extend, PartDesign::Chamfer, PartDesign::Pipe, PartDesign::Pocket, Part::Vertex, PartDesign::Thickness, Surface::Sewing, Part::RuledSurface, PartDesign::FeatureBase, PartDesign::Helix, PartDesign::Fillet, Sketcher::SketchObjectSF, PartDesign::Loft, Part::Primitive, Surface::Cut, Surface::Sections, PartDesign::Hole, Surface::Filling, and PartDesign::Body.
Definition at line 117 of file PartFeature.cpp.
References Shape, and App::Property::touch().
Referenced by Part::Boolean::execute(), PartDesign::Body::execute(), Part::MultiFuse::execute(), Part::MultiCommon::execute(), Part::Primitive::execute(), Part::Compound::execute(), Part::Part2DObject::execute(), Part::RuledSurface::execute(), Part::Mirroring::execute(), Part::Revolution::execute(), Part::Loft::execute(), PartDesign::FeaturePrimitive::execute(), PartDesign::ShapeBinder::execute(), PartDesign::SubShapeBinder::execute(), Part::Thickness::execute(), Part::FilletBase::execute(), src.Mod.PartDesign.Scripts.Spring.MySpring::onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid::onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped::onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt::onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder::onChanged(), and FeaturePython.DistanceBolt::onChanged().
getCameraAlignmentDirection()
bool Feature::getCameraAlignmentDirection (Base::Vector3d & direction, const char * subname) const override virtual
Virtual function to get the camera alignment direction.
Finds a direction to align the camera with.
Returns
bool whether or not a direction is found.
Reimplemented from App::GeoFeature.
Definition at line 1694 of file PartFeature.cpp.
References Part::Geometry::fromShape(), getTopoShape(), Base::Vector3< float_type >::Normalize(), updateLeaderLines::point, and Part::GeomCurve::toLine().
getElementFromSource()
QVector< Data::MappedElement > Feature::getElementFromSource (App::DocumentObject * obj, const char * subname, App::DocumentObject * src, const char * srcSub, bool single = false) static
Obtain the element name from a feature based of the element name of its source feature
Parameters
obj current feature
subname sub-object/element reference
src source feature
srcSub sub-object/element reference of the source
single if true, then return upon first match is found, or else return all matches. Multiple matches are possible for compound of multiple instances of the same source shape.
Returns
Return a vector of pair of new style and old style element names.
Definition at line 661 of file PartFeature.cpp.
References KDL::abs(), Data::IndexedName::appendToStringBuffer(), src.Mod.AddonManager.NetworkManager::count, SCL.SimpleDataTypes::e, Data::findElementName(), Data::IndexedName::fromConst(), App::DocumentObject::getID(), getTopoShape(), SplineSurface::i, Data::MappedElement::index, Data::isMappedElement(), OpenSCADFeatures::long, Data::MappedElement::name, femtools.tokrules::names, Data::newElementName(), App::ElementNamePair::newName, Data::noElementName(), App::ElementNamePair::oldName, Part::TopoShape::shapeName(), Part::TopoShape::shapeType(), Dice3DS.dom3ds::tag, and Path.Post.scripts.grbl_post::type.
getElementHistory()
std::list< Data::HistoryItem > Feature::getElementHistory (App::DocumentObject * obj, const char * name, bool recursive = true, bool sameType = false) static
Definition at line 569 of file PartFeature.cpp.
References KDL::abs(), toolbit-attributes::doc, Data::ComplexGeoData::elementType(), Base::Persistence::getClassTypeId(), App::DocumentObject::getDocument(), Data::ComplexGeoData::getElementHistory(), App::GeoFeature::getElementOwner(), Data::ComplexGeoData::getIndexedName(), App::DocumentObject::getLinkedObject(), Data::ComplexGeoData::getMappedName(), getTopoShape(), Base::BaseClass::isDerivedFrom(), Data::isMappedElement(), Data::newElementName(), and Dice3DS.dom3ds::tag.
getElementName()
App::ElementNamePair Feature::getElementName (const char * name, ElementNameType type = Normal) const override virtual
Override getElementName to support the Export type. Other calls are passed to the original method
Parameters
name The name to search for, or if non existent, name of current Feature is returned
type An element type name.
Returns
a struct with the newName and oldName. New element name may be empty.
Reimplemented from App::GeoFeature.
Reimplemented in Sketcher::SketchObject.
Definition at line 159 of file PartFeature.cpp.
References App::GeoFeature::getElementName(), getExportElementName(), getPropertyOfGeometry(), and Path.Post.scripts.grbl_post::type.
getExportElementName()
App::ElementNamePair Feature::getExportElementName (TopoShape shape, const char * name) const protected
Helper function to obtain mapped and indexed element name from a shape @params shape: source shape
Parameters
name the input name, can be either mapped or indexed name
Returns
Returns both the indexed and mapped name
If the 'name' referencing a non-primary shape type, i.e. not Vertex/Edge/Face, this function will auto generate a name from primary sub-shapes.
Definition at line 176 of file PartFeature.cpp.
References App::GeoFeature::_getElementName(), a, SCL.SimpleDataTypes::b, Part::TopoShape::chooseMatchingSubShapeByPlaneOrLine(), src.Mod.AddonManager.NetworkManager::count, Part::TopoShape::decodeElementComboName(), dot(), DraftVecUtils::find(), Part::TopoShape::findAncestors(), Data::IndexedName::fromConst(), Data::ComplexGeoData::getElementName(), Data::ComplexGeoData::getIndexedName(), Part::PropertyPartShape::getShape(), Part::TopoShape::getSubShape(), Part::TopoShape::getSubTopoShape(), Part::TopoShape::getSubTopoShapes(), Data::IndexedName::getType(), Data::hasMissingElement(), Data::MappedElement::index, KDL::min(), Data::MISSING_PREFIX, Path.Post.scripts.opensbp_post::move(), Data::MappedElement::name, femtools.tokrules::names, RobotExample::pos, Data::POSTFIX_INDEX, Part::TopoShape::setElementComboName(), Shape, Part::TopoShape::shapeName(), Part::TopoShape::shapeTypeAndIndex(), and TestSpreadsheet::v.
Referenced by getElementName().
getLocation()
TopLoc_Location Feature::getLocation () const
Definition at line 1554 of file PartFeature.cpp.
References Base::Placement::getPosition(), Base::Placement::getRotation(), Base::Rotation::getValue(), App::PropertyPlacement::getValue(), App::GeoFeature::Placement, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by PartDesign::FeatureExtrude::buildExtrusion(), PartDesign::Hole::execute(), PartDesign::Loft::execute(), PartDesign::Helix::execute(), PartDesign::Pipe::execute(), PartDesign::Revolution::execute(), PartDesign::Groove::execute(), PartDesign::FeaturePrimitive::execute(), PartDesign::Helix::generateHelixPath(), PartDesign::DressUp::getAddSubShape(), PartDesign::LinearPattern::getTransformations(), and PartDesign::PolarPattern::getTransformations().
getMaterialAppearance()
App::Material Feature::getMaterialAppearance () const override virtual
Virtual function to get an App::Material object describing the appearance.
The appearance properties are described by the underlying features material. This can not be accessed directly from within the Gui module. This virtual function will return a App::Material object describing the appearance properties of the material.
Returns
App::Material the appearance properties of the object material
Reimplemented from App::GeoFeature.
Definition at line 870 of file PartFeature.cpp.
References Materials::Material::getMaterialAppearance(), Materials::PropertyMaterial::getValue(), and ShapeMaterial.
getPropertyOfGeometry()
const App::PropertyComplexGeoData * Feature::getPropertyOfGeometry () const override virtual
This method returns the main property of a geometric object that holds the actual geometry. For a part object this is the Shape property, for a mesh object the Mesh property and so on. The default implementation returns null.
Reimplemented from App::GeoFeature.
Definition at line 1666 of file PartFeature.cpp.
References Shape.
Referenced by getElementName().
getPyObject()
PyObject * Feature::getPyObject () override virtual
getPyObject returns the Python binding object
Returns
the Python binding object
Reimplemented from App::GeoFeature.
Reimplemented in Sketcher::SketchObject, PartDesign::Body, PartDesign::FeaturePrimitive, Part::Primitive, and PartDesign::Feature.
Definition at line 123 of file PartFeature.cpp.
References Py::SmartPtr::is(), Py::new_reference_to(), and App::DocumentObject::PythonObject.
Referenced by Part::ImportStepParts().
getRelatedElements()
QVector< Data::MappedElement > Feature::getRelatedElements (App::DocumentObject * obj, const char * name, HistoryTraceType sameType = HistoryTraceType::followTypeChange, bool withCache = true) static
Definition at line 790 of file PartFeature.cpp.
References Part::followTypeChange, Data::IndexedName::fromConst(), getElementSource(), getTopoShape(), SplineSurface::i, Data::MappedElement::index, Data::MappedElement::name, Part::TopoShape::shapeName(), Part::TopoShape::shapeType(), and Path.Post.scripts.grbl_post::type.
Referenced by Attacher::AttachEngine::calculateAttachedPlacement(), Sketcher::SketchObject::fixExternalGeometry(), guessNewLink(), and PartGui::DlgFilletEdges::setupFillet().
getShape()
TopoDS_Shape Feature::getShape (const App::DocumentObject * obj, const char * subname = nullptr, bool needSubElement = false, Base::Matrix4D * pmat = nullptr, App::DocumentObject ** owner = nullptr, bool resolveLink = true, bool transform = true) static
Convenience function to extract shape from fully qualified subname
Parameters
obj the parent object
subname dot separated full qualified subname
needSubElement whether to ignore the non-object subelement reference inside subname
pmat used as current transformation on input, and return the accumulated transformation on output
owner return the owner of the shape returned
resolveLink if true, resolve link(s) of the returned 'owner' by calling its getLinkedObject(true) function
transform if true, apply obj's transformation. Set to false if pmat already include obj's transformation matrix.
Definition at line 863 of file PartFeature.cpp.
References Part::TopoShape::getShape(), and getTopoShape().
Referenced by PartGui::MirrorPlaneSelection::allow(), Part::Extrusion::calculateShapeNormal(), TechDraw::DrawComplexSection::canBuild(), Part::Chamfer::execute(), Part::Fillet::execute(), Part::MultiFuse::execute(), Part::Face::execute(), Part::Mirroring::execute(), Part::Revolution::fetchAxisLink(), Part::Extrusion::fetchAxisLink(), Measure::Measurement::findType(), Measure::ShapeFinder::getLocatedShape(), TechDrawGui::DrawGuiUtil::getProjDirFromFace(), getShapeFromStrings(), TechDraw::ShapeExtractor::getShapeFromXLink(), TechDraw::ShapeExtractor::getShapes(), TechDraw::ShapeExtractor::getXShapes(), PartGui::TaskCheckGeometryResults::goCheck(), TechDraw::DrawComplexSection::isLinearProfile(), TechDraw::DrawComplexSection::isMultiSegmentProfile(), TechDraw::DrawComplexSection::isProfileObject(), TechDraw::DrawComplexSection::makeProfileWire(), TechDraw::DrawComplexSection::makeSectionLineWire(), PartMeasureTypeCb(), Measure::Measurement::planesAreParallel(), and PartGui::ViewProviderPartExt::updateVisual().
getShapeOwner()
App::DocumentObject * Feature::getShapeOwner (const App::DocumentObject * obj, const char * subname = nullptr) static
Definition at line 1350 of file PartFeature.cpp.
References App::DocumentObject::getLinkedObject(), and App::DocumentObject::getSubObject().
Referenced by PartDesignGui::ReferenceSelection::allow(), PartGui::ViewProviderMultiFuse::updateData(), PartGui::ViewProviderBoolean::updateData(), PartGui::ViewProviderCompound::updateData(), PartGui::ViewProviderFillet::updateData(), PartGui::ViewProviderMultiCommon::updateData(), and PartGui::ViewProviderChamfer::updateData().
getSubObject()
App::DocumentObject * Feature::getSubObject (const char * subname, PyObject ** pyObj, Base::Matrix4D * mat, bool transform, int depth) const override virtual
Get the sub element/object by name
Parameters
subname a string which is dot separated name to refer to a sub element or object. An empty string can be used to refer to the object itself
pyObj if non zero, returns the python object corresponding to this sub object. The actual type of this python object is implementation dependent. For example, The current implementation of Part::Feature will return the TopoShapePy, event if there is no sub-element reference, in which case it returns the whole shape.
mat If non zero, it is used as the current transformation matrix on input. And output as the accumulated transformation up until and include the transformation applied by the final object reference in subname. For Part::Feature, the transformation is applied to the TopoShape inside pyObj before returning.
transform if false, then it will not apply the object's own transformation to mat, which lets you override the object's placement (and possibly scale).
depth depth limitation as hint for cyclic link detection
Returns
The last document object referred in subname. If subname is empty, then it shall return itself. If subname is invalid, then it shall return zero.
Reimplemented from App::DocumentObject.
Reimplemented in PartDesign::SubShapeBinder, Sketcher::SketchObject, PartDesign::Body, PartDesign::Feature, and PartDesign::CoordinateSystem.
Definition at line 399 of file PartFeature.cpp.
References Drawing::copy(), SCL.SimpleDataTypes::e, KDL::exp(), FC_LOG, App::GetApplication(), ParameterGrp::GetBool(), App::DocumentObject::getFullName(), App::Application::GetParameterGroupByPath(), Part::PropertyPartShape::getShape(), App::DocumentObject::getSubObject(), App::PropertyPlacement::getValue(), Data::isMappedElement(), Path.Op.Surface::msg, Py::new_reference_to(), App::GeoFeature::Placement, Shape, Part::shape2pyshape(), Path.Post.scripts.refactored_centroid_post::str, Base::Placement::toMatrix(), and src.Mod.Test.UnitTests::ts().
Referenced by PartDesign::Body::getSubObject(), and PartDesign::SubShapeBinder::getSubObject().
getTopoShape()
TopoShape Feature::getTopoShape (const App::DocumentObject * obj, const char * subname = nullptr, bool needSubElement = false, Base::Matrix4D * pmat = nullptr, App::DocumentObject ** owner = nullptr, bool resolveLink = true, bool transform = true, bool noElementMap = false) static
Definition at line 1247 of file PartFeature.cpp.
References _getTopoShape(), Data::findElementName(), Base::Persistence::getClassTypeId(), App::LinkBaseExtension::getExtensionClassTypeId(), App::DocumentObject::getNameInDocument(), Part::PropertyPartShape::getShape(), App::DocumentObject::getSubObject(), App::PropertyPlacement::getValue(), App::ExtensionContainer::hasExtension(), Base::BaseClass::isDerivedFrom(), App::GeoFeature::Placement, Shape, Base::Placement::toMatrix(), and src.Mod.Test.UnitTests::ts().
Referenced by _getTopoShape(), PartGui::SweepWidget::accept(), MeshPartGui::Tessellation::accept(), PartDesignGui::TaskDressUpParameters::addAllEdges(), Sketcher::SketchObject::addExternal(), PartGui::DlgRevolution::EdgeSelection::allow(), PartGui::DlgExtrusion::EdgeSelection::allow(), PartGui::SweepWidget::Private::EdgeSelection::allow(), PartGui::MirrorPlaneSelection::allow(), PartGui::DlgScale::apply(), PartGui::DlgExtrusion::apply(), PartGui::CrossSections::apply(), PartDesign::FeatureExtrude::buildExtrusion(), Part::Boolean::execute(), Part::Fillet::execute(), Part::MultiCommon::execute(), Part::MultiFuse::execute(), Part::Chamfer::execute(), Part::Compound::execute(), Part::Mirroring::execute(), Part::RuledSurface::execute(), Part::Offset::execute(), Part::Revolution::execute(), Part::Offset2D::execute(), PartDesign::Boolean::execute(), Part::Extrusion::execute(), Part::Loft::execute(), Part::Scale::execute(), Part::Sweep::execute(), Part::Thickness::execute(), Part::Reverse::execute(), Attacher::AttachEngine::extractSubShape(), Part::Revolution::fetchAxisLink(), Part::Extrusion::fetchAxisLink(), PartGui::DlgScale::findShapes(), PartGui::DlgExtrusion::findShapes(), getCameraAlignmentDirection(), getElementFromSource(), getElementHistory(), getElementSource(), getLocatedShape(), TechDraw::ShapeExtractor::getLocatedShape(), PartGui::ViewProviderPartExt::getModelPoints(), PartDesign::ProfileBased::getProfileNormal(), PartDesign::ProfileBased::getProfileShape(), getRelatedElements(), PartDesign::Loft::getSectionShape(), getShape(), PartGui::getShapesFromSelection(), PartDesign::ProfileBased::getTopoShapeSupportFace(), PartDesign::ProfileBased::getTopoShapeVerifiedFace(), PartDesign::ProfileBased::getUpToFaceFromLinkSub(), PartDesign::ProfileBased::getUpToShapeFromLinkSubList(), TechDraw::ReferenceEntry::hasGeometry(), PartGui::hasShapesInSelection(), Import::ImportOCAF2::loadShapes(), PartGui::DlgFilletEdges::setupFillet(), PartDesign::SubShapeBinder::update(), and MeshPartGui::Mesh2ShapeGmsh::writeProject().
getViewProviderName()
const char * Feature::getViewProviderName () const override virtual
returns the type name of the ViewProvider
Reimplemented from App::DocumentObject.
Reimplemented in Part::Ellipse, Part::Wedge, Part::Spiral, Part::Helix, Part::Torus, Part::Cone, Part::RegularPolygon, Part::Prism, Part::FeatureExt, Part::Cylinder, Part::Reverse, Part::Refine, Part::Ellipsoid, Part::Thickness, Part::Sphere, Part::Plane, Part::Sweep, Part::Line, Sketcher::SketchObject, Part::Loft, PartDesign::SubShapeBinder, PartDesign::Groove, PartDesign::Revolution, Surface::GeomFillSurface, PartDesign::Boolean, PartDesign::ShapeBinder, Surface::FeatureBlendCurve, PartDesign::Draft, PartDesign::Pad, Surface::Extend, Part::Vertex, PartDesign::Chamfer, PartDesign::Pipe, PartDesign::Pocket, PartDesign::Thickness, PartDesign::FeaturePrimitive, Part::RuledSurface, PartDesign::Helix, PartDesign::Plane, PartDesign::Fillet, PartDesign::Line, PartDesign::Scaled, PartDesign::Loft, PartDesign::Feature, PartDesign::Mirrored, PartDesign::MultiTransform, Surface::Sections, PartDesign::Point, PartDesign::FeatureBase, PartDesign::Hole, PartDesign::CoordinateSystem, PartDesign::PolarPattern, PartDesign::LinearPattern, Surface::Filling, PartDesign::FeatureExtrude, and PartDesign::Body.
Definition at line 1662 of file PartFeature.cpp.
guessNewLink()
void Feature::guessNewLink (std::string & replacementName, DocumentObject * base, const char * oldLink) static
Definition at line 1732 of file PartFeature.cpp.
References FC_WARN, and getRelatedElements().
Referenced by PartDesignGui::TaskDlgDressUpParameters::TaskDlgDressUpParameters().
hasShapeOwner()
static bool Part::Feature::hasShapeOwner (const App::DocumentObject * obj, const char * subname = nullptr) inline static
Definition at line 146 of file PartFeature.h.
isElementMappingDisabled()
bool Feature::isElementMappingDisabled (App::PropertyContainer * container) static
Definition at line 1671 of file PartFeature.cpp.
joinHistory()
ShapeHistory Feature::joinHistory (const ShapeHistory & oldH, const ShapeHistory & newH) protected
Definition at line 1640 of file PartFeature.cpp.
References Part::ShapeHistory::shapeMap, and Part::ShapeHistory::type.
Referenced by Part::MultiFuse::execute().
mustExecute()
short Feature::mustExecute () const override virtual
mustExecute We call this method to check if the object was modified to be invoked. If the object label or an argument is modified. If we must recompute the object - to call the method execute(). 0: no recomputation is needed 1: recomputation needed
Remarks
If an object is marked as 'touched' then this does not necessarily mean that it will be recomputed. It only means that all objects that link it (i.e. its InList) will be recomputed.
Reimplemented from App::DocumentObject.
Reimplemented in Part::Ellipse, Part::Wedge, PartDesign::Wedge, Part::Spiral, Part::Helix, PartDesign::Prism, Part::Torus, PartDesign::Torus, Part::Cone, Part::RegularPolygon, PartDesign::Ellipsoid, Part::Prism, PartDesign::Cone, Part::FilletBase, Part::Cylinder, Part::Ellipsoid, PartDesign::Sphere, Part::Thickness, Part::Sphere, Part::Plane, PartDesign::Cylinder, Part::Sweep, PartDesign::Transformed, Part::Line, Sketcher::SketchObject, PartDesign::ShapeBinder, Part::Loft, PartDesign::Box, PartDesign::Groove, PartDesign::Revolution, PartDesign::Boolean, Surface::FeatureBlendCurve, Surface::GeomFillSurface, PartDesign::Draft, Surface::Extend, PartDesign::FeatureAddSub, PartDesign::Chamfer, PartDesign::Pipe, Part::Vertex, PartDesign::Thickness, Surface::Sewing, Part::RuledSurface, PartDesign::Helix, PartDesign::Fillet, Sketcher::SketchObjectSF, PartDesign::DressUp, PartDesign::Hole, PartDesign::Loft, PartDesign::Scaled, Part::Primitive, Surface::Cut, PartDesign::Mirrored, PartDesign::MultiTransform, PartDesign::FeatureBase, PartDesign::PolarPattern, PartDesign::LinearPattern, Surface::Filling, PartDesign::Feature, PartDesign::ProfileBased, PartDesign::FeatureExtrude, and PartDesign::Body.
Definition at line 99 of file PartFeature.cpp.
Referenced by SurfaceGui::SectionsPanel::accept(), PartDesign::Body::mustExecute(), Part::Face::mustExecute(), Part::CustomFeature::mustExecute(), and PartDesign::ShapeBinder::mustExecute().
onBeforeChange()
void Feature::onBeforeChange (const App::Property * prop) override protected virtual
get called before the value is changed
Reimplemented from App::DocumentObject.
Definition at line 1384 of file PartFeature.cpp.
References Data::findElementName(), App::Property::getContainer(), App::DocumentObject::getDocument(), App::PropertyLinkBase::getElementReferences(), Part::PropertyPartShape::getShape(), Part::TopoShape::getSubTopoShape(), Data::hasMissingElement(), replaceobj::objs, App::Document::Restoring, Shape, importers.importIFCmulticore::subs, App::DocumentObject::testStatus(), and TestSpreadsheet::v.
onChanged()
void Feature::onChanged (const App::Property * prop) override protected virtual
get called by the container when a property was changed
Reimplemented from App::GeoFeature.
Reimplemented in Part::Wedge, Part::Spiral, Part::Helix, PartDesign::ProfileBased, PartDesign::SubShapeBinder, Part::Sweep, PartDesign::Body, PartDesign::Helix, Part::Loft, PartDesign::Hole, PartDesign::DressUp, Surface::FeatureBlendCurve, PartDesign::ShapeBinder, PartDesign::PolarPattern, Surface::Extend, PartDesign::Boolean, PartDesign::LinearPattern, Part::RuledSurface, PartDesign::FeaturePrimitive, PartDesign::Point, Part::Primitive, PartDesign::Feature, PartDesign::Plane, PartDesign::FeatureBase, PartDesign::Line, Sketcher::SketchObject, Part::Ellipse, Part::FilletBase, Part::Line, PartDesign::Chamfer, Surface::GeomFillSurface, and Part::Vertex.
Definition at line 1474 of file PartFeature.cpp.
References Base::Placement::fromMatrix(), Part::PropertyPartShape::getShape(), Part::TopoShape::getTransform(), Part::PropertyPartShape::getValue(), App::PropertyPlacement::getValue(), App::DocumentObject::isRecomputing(), App::Property::NoRecompute, buildPsets::p, App::GeoFeature::Placement, Part::TopoShape::setTransform(), Part::PropertyPartShape::setValue(), App::PropertyPlacement::setValueIfChanged(), Shape, and Base::Placement::toMatrix().
Referenced by Part::Circle::onChanged(), Part::Primitive::onChanged(), Surface::GeomFillSurface::onChanged(), Part::Revolution::onChanged(), Part::Mirroring::onChanged(), Part::RuledSurface::onChanged(), Surface::Extend::onChanged(), Surface::FeatureBlendCurve::onChanged(), Part::Loft::onChanged(), Part::Sweep::onChanged(), PartDesign::SubShapeBinder::onChanged(), Part::Extrusion::onChanged(), Part::FilletBase::onChanged(), and Sketcher::SketchObject::onChanged().
recompute()
App::DocumentObjectExecReturn * Feature::recompute () override protected virtual
recompute only this object
Reimplemented from App::DocumentObject.
Reimplemented in PartDesign::Feature.
Definition at line 104 of file PartFeature.cpp.
References SCL.SimpleDataTypes::e, App::DocumentObject::recompute(), and App::DocumentObjectExecReturn::Why.
Referenced by Part::Circle::onChanged(), Part::Primitive::onChanged(), Part::Vertex::onChanged(), Part::Box::onChanged(), Part::Mirroring::onChanged(), Surface::FeatureBlendCurve::onChanged(), Part::Line::onChanged(), Part::Helix::onChanged(), Part::Spiral::onChanged(), Part::Wedge::onChanged(), and Part::Ellipse::onChanged().
registerElementCache()
void Feature::registerElementCache (const std::string & prefix, PropertyPartShape * prop) protected
Definition at line 1370 of file PartFeature.cpp.
searchElementCache()
const std::vector< std::string > & Feature::searchElementCache (const std::string & element, Data::SearchOptions options = Data::SearchOption::CheckGeometry, double tol = 1e-7, double atol = 1e-10) const override virtual
Search sub element using internal cached geometry
Parameters
element element name
options search options
tol coordinate tolerance
atol angle tolerance
Returns
Returns a list of found element reference to the new geometry. The returned value will be invalidated when the geometry is changed.
Before changing the property of geometry, GeoFeature will internally make a snapshot of all referenced element geometry. After change, user code may call this function to search for the new element name that reference to the same geometry of the old element.
Reimplemented from App::GeoFeature.
Definition at line 1511 of file PartFeature.cpp.
References dot(), Part::none, Shape, and TestSpreadsheet::v.
setMaterialAppearance()
void Feature::setMaterialAppearance (const App::Material & material) override virtual
Virtual function to set the appearance with an App::Material object.
The appearance properties are described by the underlying features material. This cannot be accessed directly from within the Gui module. This virtual function will set the appearance from an App::Material object.
Reimplemented from App::GeoFeature.
Definition at line 875 of file PartFeature.cpp.
References SCL.SimpleDataTypes::e, Materials::PropertyMaterial::setValue(), and ShapeMaterial.
Member Data Documentation
Shape
PropertyPartShape Part::Feature::Shape
Definition at line 60 of file PartFeature.h.
Referenced by BOPTools.Utils.HashableShape::__eq__(), BOPTools.Utils.HashableShape_Deep::__eq__(), ReverseEngineeringGui::Segmentation::accept(), Import::ImpExpDxfRead::DrawingEntityCollector::AddObject(), PartGui::CrossSections::apply(), MeshPartGui::CrossSections::apply(), PartDesign::FeatureExtrude::buildExtrusion(), PartDesign::ShapeBinder::buildShapeFromReferences(), create(), Surface::GeomFillSurface::createFace(), Part::Boolean::execute(), PartDesign::Body::execute(), Surface::Filling::execute(), PartDesign::Hole::execute(), Part::MultiCommon::execute(), Part::Fillet::execute(), Part::MultiFuse::execute(), Part::Chamfer::execute(), Part::CurveNet::execute(), Part::ImportBrep::execute(), Part::ImportIges::execute(), Surface::Cut::execute(), Surface::Sections::execute(), Fem::FemMeshShapeObject::execute(), Part::Face::execute(), Part::FeatureGeometrySet::execute(), PartDesign::Loft::execute(), Part::ImportStep::execute(), Part::Box::execute(), PartDesign::Fillet::execute(), Part::Compound::execute(), Part::Circle::execute(), PartDesign::Helix::execute(), Part::RuledSurface::execute(), Part::Mirroring::execute(), Part::Vertex::execute(), Surface::Sewing::execute(), PartDesign::Thickness::execute(), PartDesign::Chamfer::execute(), PartDesign::Pipe::execute(), Part::Offset::execute(), Surface::Extend::execute(), Part::Revolution::execute(), Path::FeatureArea::execute(), Fem::FemMeshShapeNetgenObject::execute(), Part::Offset2D::execute(), Surface::FeatureBlendCurve::execute(), PartDesign::Boolean::execute(), Part::Extrusion::execute(), PartDesign::Revolution::execute(), PartDesign::Groove::execute(), Drawing::FeatureProjection::execute(), Part::Loft::execute(), TechDraw::FeatureProjection::execute(), PartDesign::FeaturePrimitive::execute(), Part::Scale::execute(), PartDesign::ShapeBinder::execute(), Part::Line::execute(), PartDesign::Transformed::execute(), Part::Sweep::execute(), Part::Plane::execute(), Part::Sphere::execute(), execute(), Part::Thickness::execute(), Part::Ellipsoid::execute(), Part::Refine::execute(), Part::Reverse::execute(), Part::Cylinder::execute(), Part::Prism::execute(), Part::RegularPolygon::execute(), Inspection::Feature::execute(), Part::Cone::execute(), Part::Torus::execute(), Part::Helix::execute(), Part::Spiral::execute(), Part::Wedge::execute(), Part::Ellipse::execute(), PartDesign::DressUp::getAddSubShape(), PartDesign::ProfileBased::getAxis(), Fem::Constraint::getBasePoint(), Fem::Constraint::getDirection(), getExportElementName(), PartDesign::ProfileBased::getFaceFromLinkSub(), Fem::Tools::getFeatureSubShape(), TechDraw::ShapeExtractor::getLocation3dFromFeat(), Sketcher::SketchAnalysis::getOpenVertices(), Fem::Constraint::getPoints(), PartDesign::ProfileBased::getProfileWires(), getPropertyOfGeometry(), getSubObject(), PartDesign::ProfileBased::getSupportFace(), getTopoShape(), PartDesign::LinearPattern::getTransformations(), PartDesign::PolarPattern::getTransformations(), Surface::GeomFillSurface::getWire(), Part::ImportIgesParts(), Part::ImportStepParts(), Import::ImportOCAF2::loadShapes(), PartDesignGui::TaskFeaturePick::makeCopy(), onBeforeChange(), Part::Box::onChanged(), Fem::ConstraintBearing::onChanged(), PartDesign::DressUp::onChanged(), onChanged(), FemGui::TaskFemConstraintBearing::onSelectionChanged(), FemGui::TaskFemConstraintGear::onSelectionChanged(), SurfaceGui::FillingPanel::open(), Import::ExportOCAF::reallocateFreeShape(), Part::Box::Restore(), Import::ExportOCAF::saveShape(), searchElementCache(), PartGui::ViewProviderMirror::setEdit(), PartDesign::SubShapeBinder::setLinks(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), PartDesign::SubShapeBinder::update(), PartGui::ViewProviderMultiFuse::updateData(), PartGui::ViewProviderBoolean::updateData(), PartGui::ViewProviderFillet::updateData(), PartGui::ViewProviderCompound::updateData(), PartGui::ViewProviderMultiCommon::updateData(), PartGui::ViewProviderChamfer::updateData(), Sketcher::SketchObject::validateExternalLinks(), and validateSketches().
ShapeMaterial
Materials::PropertyMaterial Part::Feature::ShapeMaterial
Definition at line 61 of file PartFeature.h.
Referenced by copyMaterial(), getMaterialAppearance(), PartDesign::Body::onChanged(), and setMaterialAppearance().
The documentation for this class was generated from the following files:
PartFeature.h
PartFeature.cpp