FreeCAD: Gui::PythonEditor Class Reference
Gui::PythonEditor Class Reference
#include <PythonEditor.h>
Public Slots
void onComment ()
void onUncomment ()
void setFileName (const QString &)
void startDebug ()
Public Member Functions
PythonEditor (QWidget *parent=nullptr)
~PythonEditor () override
void OnChange (Base::Subject< const char * > &rCaller, const char *rcReason) override
void toggleBreakpoint ()
void showDebugMarker (int line)
void hideDebugMarker ()
Public Member Functions inherited from Gui::PythonTextEditor
PythonTextEditor (QWidget *parent=nullptr)
~PythonTextEditor () override
Public Member Functions inherited from Gui::TextEditor
TextEditor (QWidget *parent=nullptr)
~TextEditor () override
void setSyntaxHighlighter (SyntaxHighlighter *)
void OnChange (Base::Subject< const char * > &rCaller, const char *rcReason) override
void lineNumberAreaPaintEvent (QPaintEvent *)
int lineNumberAreaWidth ()
void setVisibleLineNumbers (bool value)
bool isVisibleLineNumbers () const
void setEnabledHighlightCurrentLine (bool value)
bool isEnabledHighlightCurrentLine () const
Public Member Functions inherited from Gui::TextEdit
TextEdit (QWidget *parent=nullptr)
~TextEdit () override
Public Member Functions inherited from Gui::WindowParameter
WindowParameter (const char *name)
~WindowParameter () override
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
ParameterGrp::handle getWindowParameter ()
return the parameter group of this window
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *e) override
void drawMarker (int line, int x, int y, QPainter *) override
void keyPressEvent (QKeyEvent *) override
Protected Member Functions inherited from Gui::PythonTextEditor
void keyPressEvent (QKeyEvent *) override
Protected Member Functions inherited from Gui::TextEditor
void resizeEvent (QResizeEvent *e) override
QWidget * getMarker () const
Protected Member Functions inherited from Gui::TextEdit
void keyPressEvent (QKeyEvent *) override
void wheelEvent (QWheelEvent *e) override
Protected Member Functions inherited from Gui::WindowParameter
bool setGroupName (const char *name)
template<typename S , typename T >
void setSlotParamChanged (S slot, T *obsPtr)
connect slot to ParameterManager signal
Additional Inherited Members
Signals inherited from Gui::TextEdit
void showSearchBar ()
void findNext ()
void findPrevious ()
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter ()
get the parameters
Detailed Description
Python text editor with syntax highlighting.
Author
Werner Mayer
Definition at line 59 of file PythonEditor.h.
Constructor & Destructor Documentation
PythonEditor()
PythonEditor::PythonEditor (QWidget * parent = nullptr) explicit
Constructs a PythonEditor which is a child of 'parent' and does the syntax highlighting for the Python language.
Definition at line 67 of file PythonEditor.cpp.
References AttacherGui::comment, draftgeoutils.intersections::connect(), onComment(), onUncomment(), and Gui::TextEditor::setSyntaxHighlighter().
~PythonEditor()
PythonEditor::~PythonEditor () override
Destroys the object and frees any allocated resources
Definition at line 85 of file PythonEditor.cpp.
Member Function Documentation
contextMenuEvent()
void PythonEditor::contextMenuEvent (QContextMenuEvent * e) override protected
Pops up the context menu with some extensions
Definition at line 166 of file PythonEditor.cpp.
References AttacherGui::comment, SCL.SimpleDataTypes::e, NavigationIndicatorGui::menu, onComment(), and onUncomment().
drawMarker()
void PythonEditor::drawMarker (int line, int x, int y, QPainter * p) override protected virtual
Reimplemented from Gui::TextEditor.
Definition at line 154 of file PythonEditor.cpp.
References Gui::PythonEditorP::breakpoint, Gui::Breakpoint::checkLine(), Gui::PythonEditorP::debugger, Gui::PythonEditorP::debugLine, Gui::PythonEditorP::debugMarker, Gui::PythonEditorP::debugRect, Gui::PythonEditorP::filename, Gui::PythonDebugger::getBreakpoint(), buildPsets::p, MovieTool::x, and MovieTool::y.
hideDebugMarker()
void PythonEditor::hideDebugMarker ()
Definition at line 148 of file PythonEditor.cpp.
References Gui::PythonEditorP::debugLine, and Gui::TextEditor::getMarker().
Referenced by Gui::PythonEditorView::hideDebugMarker().
keyPressEvent()
void PythonEditor::keyPressEvent (QKeyEvent * e) override protected
When the user presses enter the next line should match the current indentation unless the line ends in a colon, where the next line should have an additional indentation. Shift+Enter should dedent the next block 1 indentation from what it would have been, if possible.
Definition at line 181 of file PythonEditor.cpp.
References SCL.SimpleDataTypes::c, SCL.SimpleDataTypes::e, ParameterGrp::GetBool(), ParameterGrp::GetInt(), Gui::WindowParameter::getWindowParameter(), indent, and Gui::PythonTextEditor::keyPressEvent().
OnChange()
void PythonEditor::OnChange (Base::Subject< const char * > & rCaller, const char * rcReason) override
Definition at line 90 of file PythonEditor.cpp.
References Gui::TextEditor::OnChange().
onComment
void PythonEditor::onComment () slot
Inserts a '#' at the beginning of each selected line or the current line if nothing is selected
Definition at line 230 of file PythonEditor.cpp.
References RobotExample::pos.
Referenced by contextMenuEvent(), and PythonEditor().
onUncomment
void PythonEditor::onUncomment () slot
Removes the leading '#' from each selected line or the current line if nothing is selected. In case a line hasn't a leading '#' then this line is skipped.
Definition at line 253 of file PythonEditor.cpp.
References RobotExample::pos.
Referenced by contextMenuEvent(), and PythonEditor().
setFileName
void PythonEditor::setFileName (const QString & fn) slot
Definition at line 109 of file PythonEditor.cpp.
References Gui::PythonEditorP::filename.
Referenced by Gui::PythonEditorView::PythonEditorView().
showDebugMarker()
void PythonEditor::showDebugMarker (int line)
Definition at line 130 of file PythonEditor.cpp.
References Gui::PythonEditorP::debugLine, Gui::TextEditor::getMarker(), and SplineSurface::i.
Referenced by Gui::PythonEditorView::showDebugMarker().
startDebug
void PythonEditor::startDebug () slot
Definition at line 114 of file PythonEditor.cpp.
References Gui::PythonEditorP::debugger, Gui::PythonEditorP::filename, Gui::PythonDebugger::runFile(), Gui::PythonDebugger::start(), and Gui::PythonDebugger::stop().
Referenced by Gui::PythonEditorView::startDebug().
toggleBreakpoint()
void PythonEditor::toggleBreakpoint ()
Definition at line 122 of file PythonEditor.cpp.
References Gui::PythonEditorP::debugger, Gui::PythonEditorP::filename, Gui::TextEditor::getMarker(), and Gui::PythonDebugger::toggleBreakpoint().
Referenced by Gui::PythonEditorView::toggleBreakpoint().
The documentation for this class was generated from the following files:
PythonEditor.h
PythonEditor.cpp