FreeCAD: App::StringID Class Reference
App::StringID Class Reference
#include <StringHasher.h>
Classes
struct IndexID
Light weight structure of holding a string ID and associated index.
Public Types
enum Flag {
Flag::None = 0, Flag::Binary = 1 << 0, Flag::Hashed = 1 << 1, Flag::PostfixEncoded = 1 << 2,
Flag::Postfixed = 1 << 3, Flag::Indexed = 1 << 4, Flag::PrefixID = 1 << 5, Flag::PrefixIDIndex = 1 << 6,
Flag::Persistent = 1 << 7, Flag::Marked = 1 << 8
}
Flag of the stored string data.
using Flags = Base::Flags< Flag >
Public Member Functions
StringID (long id, QByteArray data, const Flags &flags=Flag::None)
StringID ()
Constructs an empty StringID.
StringID (const StringID &other)=delete
StringID (StringID &&other) noexcept=delete
StringID & operator= (const StringID &rhs)=delete
StringID & operator= (StringID &&rhs) noexcept=delete
~StringID () override
long value () const
Returns the ID of this StringID.
const QVector< StringIDRef > & relatedIDs () const
Returns all related StringIDs that used to encode this StringID.
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from Base::Handled
Handled ()
virtual ~Handled ()
void ref () const
void unref () const
int unrefNoDelete () const
int getRefCount () const
Handled & operator= (const Handled &)
Handled (const Handled &)=delete
Handled (Handled &&)=delete
Handled & operator= (Handled &&)=delete
Flag accessors
class StringHasher
bool isBinary () const
bool isHashed () const
bool isPostfixed () const
bool isPostfixEncoded () const
bool isIndexed () const
bool isPrefixID () const
bool isPrefixIDIndex () const
bool isMarked () const
bool isPersistent () const
bool isFromSameHasher (const StringHasherRef &hasher) const
Checks if this StringID is from the input hasher.
StringHasherRef getHasher () const
Returns the owner hasher.
const QByteArray & data () const
Returns the data (prefix)
QByteArray postfix () const
Returns the postfix.
void setPostfix (QByteArray postfix)
Sets the postfix.
PyObject * getPyObject () override
PyObject * getPyObjectWithIndex (int index)
Returns a Python tuple containing both the text and index.
std::string toString (int index=0) const
std::string dataToText (int index=0) const
QByteArray dataToBytes (int index=0) const
void mark () const
Mark this StringID as used.
void setPersistent (bool enable)
Mark the StringID as persistent regardless of usage mark.
bool operator< (const StringID &other) const
int compare (const StringID &other) const
static IndexID fromString (const char *name, bool eof=true, int size=-1)
static IndexID fromString (const QByteArray &bytes, bool eof=true)
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Class to store a string
The main purpose of this class is to provide an efficient storage of the mapped geometry element name (i.e. the new Topological Naming), but it can also be used as a general purpose string table.
The StringID is to be stored in a string table (StringHasher), and be referred to by an integer ID. The stored data can be optionally divided into two parts, prefix and postfix. This is because a new mapped name is often created by adding some common postfix to an existing name, so data sharing can be improved using the following techniques:
 a) reference count (through QByteArray) the main data part,
 b) (recursively) encode prefix and/or postfix as an integer (in the
    format of #<hex>, e.g. #1b) that references another StringID,
 c) Check index based name in prefix, e.g. Edge1, Vertex2, and encode
    only the text part as StringID. The index is stored separately in
    reference class StringIDRef to maximize data sharing.
Definition at line 77 of file StringHasher.h.
Member Typedef Documentation
Flags
using App::StringID::Flags = Base::Flags<Flag>
Definition at line 112 of file StringHasher.h.
Member Enumeration Documentation
Flag
enum App::StringID::Flag strong
Flag of the stored string data.
Enumerator
None
No flag.
Binary
The stored data is binary.
Hashed
The stored data is the sha1 hash of the original content.
PostfixEncoded
Postfix is encoded as #<hex>, e.g. #1b, where the hex integer part refers to another StringID.
Postfixed
The data is split as prefix and postfix.
Indexed
The prefix data is split as text + index.
PrefixID
The prefix data is encoded as #<hex>, e.g. #1b, where the hex integer part refers to another StringID.
PrefixIDIndex
The prefix split as text + index, where the text is encoded using another StringID.
Persistent
The string ID is persistent regardless of internal mark.
Marked
Internal marked used to check if the string ID is used.
Definition at line 83 of file StringHasher.h.
Constructor & Destructor Documentation
StringID() [1/4]
App::StringID::StringID (long id, QByteArray data, const Flags & flags = Flag::None) inline
Constructor
Parameters
id integer ID of this StringID
data input data
flags flags describes the data
User code is not supposed to create StringID directly, but through StringHasher::getID()
Definition at line 121 of file StringHasher.h.
StringID() [2/4]
App::StringID::StringID () inline
Constructs an empty StringID.
Definition at line 128 of file StringHasher.h.
StringID() [3/4]
App::StringID::StringID (const StringID & other) delete
StringID() [4/4]
App::StringID::StringID (StringID && other) delete noexcept
~StringID()
StringID::~StringID () override
Definition at line 91 of file StringHasher.cpp.
Member Function Documentation
compare()
int App::StringID::compare (const StringID & other) const inline
Compare StringID
Parameters
other the other StringID for comparison
Returns
Returns -1 if less than the other StringID, 1 if greater, or 0 if equal
Definition at line 292 of file StringHasher.h.
Referenced by ArchVRM.Renderer::findPosition(), App::StringIDRef::operator<(), App::StringIDRef::operator==(), and ArchVRM.Renderer::sort().
data()
const QByteArray& App::StringID::data () const inline
Returns the data (prefix)
Definition at line 178 of file StringHasher.h.
Referenced by App::StringIDRef::constData(), and StringIDHasher::operator()().
dataToBytes()
QByteArray App::StringID::dataToBytes (int index = 0) const inline
Get the content of this StringID as QByteArray
Parameters
index optional index.
Definition at line 265 of file StringHasher.h.
Referenced by App::StringIDRef::toBytes().
dataToText()
std::string StringID::dataToText (int index = 0) const
Get the text content of this StringID
Parameters
index optional index
Returns
Return the text content of this StringID. If the data is binary, then output in base64 encoded string.
Definition at line 143 of file StringHasher.cpp.
References isBinary(), and isHashed().
Referenced by App::StringIDRef::dataToText().
fromString() [1/2]
StringID::IndexID StringID::fromString (const char * name, bool eof = true, int size = -1) static
Parse string to get ID and index
Parameters
name input string
eof Whether to check the end of string. If true, then the input string must contain only the string representation of this StringID
size input string size, or -1 if the input string is zero terminated.
Returns
Return the integer ID and index.
The input string is expected to be in the format of #<id> or with index #<id>:<index>, where both id and index are in hex digits.
Definition at line 120 of file StringHasher.cpp.
References App::StringID::IndexID::id.
Referenced by FC_LOG_LEVEL_INIT(), App::StringHasher::getID(), and App::StringHasher::saveStream().
fromString() [2/2]
static IndexID App::StringID::fromString (const QByteArray & bytes, bool eof = true) inline static
Parse string to get ID and index
Parameters
bytes input data
eof Whether to check the end of string. If true, then the input string must contain only the string representation of this StringID
The input string is expected to be in the format of #<id> or with index #<id>:<index>, where both id and index are in hex digits.
Definition at line 250 of file StringHasher.h.
getHasher()
StringHasherRef App::StringID::getHasher () const inline
Returns the owner hasher.
Definition at line 172 of file StringHasher.h.
Referenced by App::StringIDRef::getHasher().
getPyObject()
PyObject * StringID::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 98 of file StringHasher.cpp.
getPyObjectWithIndex()
PyObject * StringID::getPyObjectWithIndex (int index)
Returns a Python tuple containing both the text and index.
Definition at line 103 of file StringHasher.cpp.
Referenced by App::StringIDRef::getPyObject().
isBinary()
bool App::StringID::isBinary () const inline
Definition at line 792 of file StringHasher.h.
References Binary, and Base::Flags< Enum >::testFlag().
Referenced by dataToText(), App::StringIDRef::isBinary(), and App::StringHasher::restoreStreamNew().
isFromSameHasher()
bool App::StringID::isFromSameHasher (const StringHasherRef & hasher) const inline
Checks if this StringID is from the input hasher.
Definition at line 166 of file StringHasher.h.
Referenced by App::StringIDRef::isFromSameHasher().
isHashed()
bool App::StringID::isHashed () const inline
Definition at line 796 of file StringHasher.h.
References Hashed, and Base::Flags< Enum >::testFlag().
Referenced by dataToText(), App::StringIDRef::isHashed(), and App::StringHasher::restoreStreamNew().
isIndexed()
bool App::StringID::isIndexed () const inline
Definition at line 808 of file StringHasher.h.
References Indexed, and Base::Flags< Enum >::testFlag().
Referenced by App::StringHasher::restoreStreamNew().
isMarked()
bool App::StringID::isMarked () const inline
Definition at line 820 of file StringHasher.h.
References Marked, and Base::Flags< Enum >::testFlag().
Referenced by App::StringIDRef::isMarked(), and mark().
isPersistent()
bool App::StringID::isPersistent () const inline
Definition at line 824 of file StringHasher.h.
References Persistent, and Base::Flags< Enum >::testFlag().
isPostfixed()
bool App::StringID::isPostfixed () const inline
Definition at line 800 of file StringHasher.h.
References Postfixed, and Base::Flags< Enum >::testFlag().
Referenced by App::StringHasher::restoreStreamNew().
isPostfixEncoded()
bool App::StringID::isPostfixEncoded () const inline
Definition at line 804 of file StringHasher.h.
References PostfixEncoded, and Base::Flags< Enum >::testFlag().
Referenced by App::StringHasher::getID(), and App::StringHasher::restoreStreamNew().
isPrefixID()
bool App::StringID::isPrefixID () const inline
Definition at line 812 of file StringHasher.h.
References PrefixID, and Base::Flags< Enum >::testFlag().
Referenced by App::StringHasher::restoreStreamNew().
isPrefixIDIndex()
bool App::StringID::isPrefixIDIndex () const inline
Definition at line 816 of file StringHasher.h.
References PrefixIDIndex, and Base::Flags< Enum >::testFlag().
Referenced by App::StringHasher::restoreStreamNew().
mark()
void StringID::mark () const
Mark this StringID as used.
Definition at line 159 of file StringHasher.cpp.
References isMarked(), Marked, and Base::Flags< Enum >::setFlag().
Referenced by App::StringIDRef::mark().
operator<()
bool App::StringID::operator< (const StringID & other) const inline
Definition at line 283 of file StringHasher.h.
References nativeifc.ifc_selftest::compare().
operator=() [1/2]
StringID& App::StringID::operator= (const StringID & rhs) delete
operator=() [2/2]
StringID& App::StringID::operator= (StringID && rhs) delete noexcept
postfix()
QByteArray App::StringID::postfix () const inline
Returns the postfix.
Definition at line 184 of file StringHasher.h.
Referenced by App::StringIDRef::constData(), and StringIDHasher::operator()().
relatedIDs()
const QVector<StringIDRef>& App::StringID::relatedIDs () const inline
Returns all related StringIDs that used to encode this StringID.
Definition at line 147 of file StringHasher.h.
Referenced by App::StringIDRef::relatedIDs().
setPersistent()
void App::StringID::setPersistent (bool enable) inline
Mark the StringID as persistent regardless of usage mark.
Definition at line 828 of file StringHasher.h.
References Persistent, and Base::Flags< Enum >::setFlag().
Referenced by App::StringIDRef::setPersistent().
setPostfix()
void App::StringID::setPostfix (QByteArray postfix) inline
Sets the postfix.
Definition at line 190 of file StringHasher.h.
References Path.Post.scripts.opensbp_post::move().
toString()
std::string StringID::toString (int index = 0) const
Convert to string representation of this StringID
Parameters
index optional index
The format is #<id>. And if index is non zero, then #<id>:<index>. Both <id> and <index> are in hex format.
Definition at line 110 of file StringHasher.cpp.
References value().
Referenced by App::StringIDRef::toString().
value()
long App::StringID::value () const inline
Returns the ID of this StringID.
Definition at line 141 of file StringHasher.h.
Referenced by src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::evaluate(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::lowervalue(), toString(), and App::StringIDRef::value().
Friends And Related Function Documentation
StringHasher
friend class StringHasher friend
Definition at line 309 of file StringHasher.h.
The documentation for this class was generated from the following files:
StringHasher.h
StringHasher.cpp