FreeCAD: SketcherGui::DrawSketchKeyboardManager Class Reference
SketcherGui::DrawSketchKeyboardManager Class Reference
#include <DrawSketchKeyboardManager.h>
Public Types
enum KeyboardEventHandlingMode { KeyboardEventHandlingMode::DSHControl, KeyboardEventHandlingMode::ViewProvider }
Public Member Functions
DrawSketchKeyboardManager ()
bool isMode (KeyboardEventHandlingMode mode)
returns whether the provided entity will currently receive the event.
KeyboardEventHandlingMode getMode ()
returns which entity will currently receive the event.
bool eventFilter (QObject *object, QEvent *event)
void setTimeOut (int milliseconds)
sets the timeout to the amount of milliseconds.
int timeOut ()
Detailed Description
Class implementing an event filter for DrawSketchHandler tools, enabling seamless introduction of values to parameters, including units, while still allowing operation of shortcuts.
The basic mechanism to decide which control should respond is based on using timers, type of entered event.
Definition at line 55 of file DrawSketchKeyboardManager.h.
Member Enumeration Documentation
KeyboardEventHandlingMode
enum SketcherGui::DrawSketchKeyboardManager::KeyboardEventHandlingMode strong
Indicates whether the DSH control (e.g. on-view parameter or widget) should handle keyboard input or should signal it via boost
Enumerator
DSHControl
ViewProvider
Definition at line 65 of file DrawSketchKeyboardManager.h.
Constructor & Destructor Documentation
DrawSketchKeyboardManager()
DrawSketchKeyboardManager::DrawSketchKeyboardManager ()
Definition at line 41 of file DrawSketchKeyboardManager.cpp.
References Gui::Application::activeDocument(), draftgeoutils.intersections::connect(), toolbit-attributes::doc, Gui::Application::Instance, and ViewProvider.
Member Function Documentation
eventFilter()
bool DrawSketchKeyboardManager::eventFilter (QObject * object, QEvent * event)
Definition at line 73 of file DrawSketchKeyboardManager.cpp.
References isMode(), and ViewProvider.
getMode()
DrawSketchKeyboardManager::KeyboardEventHandlingMode DrawSketchKeyboardManager::getMode ()
returns which entity will currently receive the event.
Definition at line 68 of file DrawSketchKeyboardManager.cpp.
isMode()
bool DrawSketchKeyboardManager::isMode (KeyboardEventHandlingMode mode)
returns whether the provided entity will currently receive the event.
Definition at line 63 of file DrawSketchKeyboardManager.cpp.
Referenced by eventFilter().
setTimeOut()
void DrawSketchKeyboardManager::setTimeOut (int milliseconds)
sets the timeout to the amount of milliseconds.
Definition at line 117 of file DrawSketchKeyboardManager.cpp.
timeOut()
int DrawSketchKeyboardManager::timeOut ()
Definition at line 123 of file DrawSketchKeyboardManager.cpp.
The documentation for this class was generated from the following files:
DrawSketchKeyboardManager.h
DrawSketchKeyboardManager.cpp