FreeCAD: Path.Op.Gui.Comment._ViewProviderComment Class Reference
Path.Op.Gui.Comment._ViewProviderComment Class Reference
Public Member Functions
def __init__ (self, vobj)
def dumps (self)
def loads (self, state)
def getIcon (self)
def onChanged (self, vobj, prop)
Detailed Description
Definition at line 63 of file Comment.py.
Constructor & Destructor Documentation
__init__()
def Path.Op.Gui.Comment._ViewProviderComment.__init__ (self, vobj)
Definition at line 64 of file Comment.py.
Referenced by draftguitools.gui_subelements.SubelementHighlight.finish().
Member Function Documentation
dumps()
def Path.Op.Gui.Comment._ViewProviderComment.dumps (self)
Definition at line 77 of file Comment.py.
getIcon()
def Path.Op.Gui.Comment._ViewProviderComment.getIcon (self)
Definition at line 83 of file Comment.py.
loads()
def Path.Op.Gui.Comment._ViewProviderComment.loads (self, state)
Definition at line 80 of file Comment.py.
onChanged()
def Path.Op.Gui.Comment._ViewProviderComment.onChanged (self, vobj, prop)
Definition at line 86 of file Comment.py.
Referenced by draftviewproviders.view_base.ViewProviderDraft.attach(), draftviewproviders.view_wpproxy.ViewProviderWorkingPlaneProxy.updateData(), draftviewproviders.view_layer.ViewProviderLayer.updateData(), draftviewproviders.view_label.ViewProviderLabel.updateData(), and draftviewproviders.view_dimension.ViewProviderLinearDimension.updateData().
The documentation for this class was generated from the following file:
Comment.py