FreeCAD: ifc2x3.ifcfacebasedsurfacemodel Class Reference
ifc2x3.ifcfacebasedsurfacemodel Class Reference
Public Member Functions
def __init__ (self, fbsmfaces)
def fbsmfaces ()
def dim ()
Public Member Functions inherited from ifc2x3.ifcgeometricrepresentationitem
def __init__ (self)
Public Member Functions inherited from ifc2x3.ifcrepresentationitem
def layerassignments ()
def styledbyitem ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
fbsmfaces
Detailed Description
Entity ifcfacebasedsurfacemodel definition.
:param fbsmfaces
:type fbsmfaces:SET(1,None,'ifcconnectedfaceset', scope = schema_scope)
:param dim
:type dim:ifcdimensioncount
Definition at line 13732 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcfacebasedsurfacemodel.__init__ (self, fbsmfaces)
Definition at line 13741 of file ifc2x3.py.
Member Function Documentation
dim()
def ifc2x3.ifcfacebasedsurfacemodel.dim ()
Definition at line 13760 of file ifc2x3.py.
Referenced by ifc4.ifccompositecurvesegment.dim(), ifc4.ifcplacement.dim(), ifc4.ifccartesiantransformationoperator.dim(), ifc4.ifcgeometricset.dim(), ifc2x3.ifcrectangulartrimmedsurface.dim(), ifc2x3.ifcelementarysurface.dim(), ifc2x3.ifcpointoncurve.dim(), ifc4.ifcpointoncurve.dim(), ifc2x3.ifcpointonsurface.dim(), ifc2x3.ifcvector.dim(), ifc4.ifcpointonsurface.dim(), and ifc4.ifcvector.dim().
fbsmfaces()
def ifc2x3.ifcfacebasedsurfacemodel.fbsmfaces ()
Definition at line 13746 of file ifc2x3.py.
References ifc2x3.ifcfacebasedsurfacemodel._fbsmfaces, SCL.TypeChecker.check_type(), and ifc2x3.ifcfacebasedsurfacemodel.fbsmfaces.
Member Data Documentation
fbsmfaces
ifc2x3.ifcfacebasedsurfacemodel.fbsmfaces
Definition at line 13743 of file ifc2x3.py.
Referenced by ifc2x3.ifcfacebasedsurfacemodel.fbsmfaces().
The documentation for this class was generated from the following file:
ifc2x3.py