FreeCAD: Gui::Dialog::DlgSettingsAdvanced Class Reference
Gui::Dialog::DlgSettingsAdvanced Class Reference
#include <DlgSettingsAdvanced.h>
Public Member Functions
DlgSettingsAdvanced (QWidget *parent=0)
~DlgSettingsAdvanced ()
void saveSettings ()
void loadSettings ()
void retranslateUi ()
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void changeEvent (QEvent *e)
Properties
qreal offset1
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
Preference dialog for various advanced UI settings
This class is auto generated by Gui/PreferencePages/DlgSettingsAdvanced.py. Modify that file instead of this one, if you want to make any change. You need to install Cog Python package for code generation:
pip install cogapp
Once modified, you can regenerate the header and the source file,
python3 -m cogapp -r Gui/PreferencePages/DlgSettingsAdvanced.h Gui/PreferencePages/DlgSettingsAdvanced.cpp
Definition at line 57 of file DlgSettingsAdvanced.h.
Constructor & Destructor Documentation
DlgSettingsAdvanced()
Gui::Dialog::DlgSettingsAdvanced::DlgSettingsAdvanced (QWidget * parent = 0)
~DlgSettingsAdvanced()
Gui::Dialog::DlgSettingsAdvanced::~DlgSettingsAdvanced ()
Member Function Documentation
changeEvent()
void Gui::Dialog::DlgSettingsAdvanced::changeEvent (QEvent * e) protected virtual
Implements Gui::Dialog::PreferencePage.
loadSettings()
void Gui::Dialog::DlgSettingsAdvanced::loadSettings () virtual
Implements Gui::Dialog::PreferencePage.
retranslateUi()
void Gui::Dialog::DlgSettingsAdvanced::retranslateUi ()
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_search.WidgetSearch::__init__(), ArchGrid.ArchGridTaskPanel::addColumn(), ArchGrid.ArchGridTaskPanel::addRow(), ArchGrid.ArchGridTaskPanel::delColumn(), ArchGrid.ArchGridTaskPanel::delRow(), src.Mod.AddonManager.Widgets.addonmanager_widget_view_selector.WidgetViewSelector::set_current_view(), src.Mod.AddonManager.Widgets.addonmanager_widget_addon_buttons.WidgetAddonButtons::set_display_mode(), src.Mod.AddonManager.Widgets.addonmanager_widget_view_control_bar.WidgetViewControlBar::set_rankings_available(), ArchAxisSystem.AxisSystemTaskPanel::update(), ArchAxis._AxisTaskPanel::update(), ArchRoof._RoofTaskPanel::update(), ArchWindow._ArchWindowTaskPanel::update(), ArchSectionPlane.SectionPlaneTaskPanel::update(), DraftGui.FacebinderTaskPanel::update(), and ArchComponent.ComponentTaskPanel::update().
saveSettings()
void Gui::Dialog::DlgSettingsAdvanced::saveSettings () virtual
Implements Gui::Dialog::PreferencePage.
Property Documentation
offset1
qreal Gui::Dialog::DlgSettingsAdvanced::offset1 read write
Definition at line 124 of file DlgSettingsAdvanced.h.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.thickened_face_solid::wr2().
The documentation for this class was generated from the following file:
DlgSettingsAdvanced.h