FreeCAD: Part::MeasureClient Class Reference
Part::MeasureClient Class Reference
#include <MeasureClient.h>
Static Public Member Functions
static void initialize ()
static CallbackRegistrationList reportLengthCB ()
static CallbackRegistrationList reportPositionCB ()
static CallbackRegistrationList reportAreaCB ()
static CallbackRegistrationList reportAngleCB ()
static CallbackRegistrationList reportDistanceCB ()
static CallbackRegistrationList reportRadiusCB ()
Detailed Description
Definition at line 54 of file MeasureClient.h.
Member Function Documentation
initialize()
void Part::MeasureClient::initialize () static
Definition at line 405 of file MeasureClient.cpp.
References App::MeasureManager::addMeasureHandler(), and PartMeasureTypeCb().
Referenced by PyMOD_INIT_FUNC().
reportAngleCB()
Part::CallbackRegistrationList Part::MeasureClient::reportAngleCB () static
Definition at line 438 of file MeasureClient.cpp.
References MeasureAngleHandler().
reportAreaCB()
Part::CallbackRegistrationList Part::MeasureClient::reportAreaCB () static
Definition at line 428 of file MeasureClient.cpp.
References MeasureAreaHandler().
reportDistanceCB()
Part::CallbackRegistrationList Part::MeasureClient::reportDistanceCB () static
Definition at line 448 of file MeasureClient.cpp.
References MeasureDistanceHandler().
reportLengthCB()
Part::CallbackRegistrationList Part::MeasureClient::reportLengthCB () static
Definition at line 410 of file MeasureClient.cpp.
References MeasureLengthHandler().
reportPositionCB()
Part::CallbackRegistrationList Part::MeasureClient::reportPositionCB () static
Definition at line 419 of file MeasureClient.cpp.
References MeasurePositionHandler().
reportRadiusCB()
Part::CallbackRegistrationList Part::MeasureClient::reportRadiusCB () static
Definition at line 458 of file MeasureClient.cpp.
References MeasureRadiusHandler().
The documentation for this class was generated from the following files:
MeasureClient.h
MeasureClient.cpp