FreeCAD: TechDrawGui::TaskProjGroup Class Reference
TechDrawGui::TaskProjGroup Class Reference
#include <TaskProjGroup.h>
Public Member Functions
TaskProjGroup (TechDraw::DrawView *featView, bool mode)
~TaskProjGroup () override=default
virtual bool accept ()
virtual bool reject ()
virtual bool apply ()
void modifyStandardButtons (QDialogButtonBox *box)
void saveButtons (QPushButton *btnOK, QPushButton *btnCancel, QPushButton *btnApply)
void updateTask ()
void setFractionalScale (double newScale)
void setCreateMode (bool mode)
bool getCreateMode () const
Protected Slots
void viewToggled (bool toggle)
void rotateButtonClicked ()
Requests appropriate rotation of our DrawProjGroup.
void customDirectionClicked ()
void projectionTypeChanged (QString qText)
void scaleTypeChanged (int index)
void AutoDistributeClicked (bool clicked)
void spacingChanged ()
Updates item spacing.
void scaleManuallyChanged (int unused)
Protected Member Functions
void changeEvent (QEvent *event) override
void setupViewCheckboxes (bool addConnections=false)
Connects and updates state of view checkboxes to match the state of multiView.
void setUiPrimary ()
sets the main direction of the view
bool useThirdAngle ()
void saveGroupState ()
void restoreGroupState ()
void updateUi ()
enable/disable the appropriate widgets
void connectWidgets ()
void initializeUi ()
void turnViewToProjGroup ()
void turnProjGroupToView ()
QString formatVector (Base::Vector3d vec)
Detailed Description
Definition at line 51 of file TaskProjGroup.h.
Constructor & Destructor Documentation
TaskProjGroup()
TaskProjGroup::TaskProjGroup (TechDraw::DrawView * featView, bool mode)
Definition at line 68 of file TaskProjGroup.cpp.
References connectWidgets(), TechDraw::DrawView::findParentPage(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::Document::getViewProvider(), initializeUi(), Gui::Application::Instance, saveGroupState(), setUiPrimary(), and updateUi().
~TaskProjGroup()
TechDrawGui::TaskProjGroup::~TaskProjGroup () override default
Member Function Documentation
accept()
bool TaskProjGroup::accept () virtual
Definition at line 792 of file TaskProjGroup.cpp.
References toolbit-attributes::doc, doCommand, App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::Command::Gui, Gui::Application::Instance, TechDraw::DrawProjGroup::recomputeChildren(), and App::DocumentObject::recomputeFeature().
Referenced by TechDrawGui::TaskDlgProjGroup::accept().
apply()
bool TaskProjGroup::apply () virtual
Definition at line 782 of file TaskProjGroup.cpp.
References TechDraw::DrawProjGroup::recomputeChildren(), and App::DocumentObject::recomputeFeature().
Referenced by TechDrawGui::TaskDlgProjGroup::clicked().
AutoDistributeClicked
void TaskProjGroup::AutoDistributeClicked (bool clicked) protected slot
Definition at line 560 of file TaskProjGroup.cpp.
References TechDraw::DrawProjGroup::AutoDistribute, App::DocumentObject::recomputeFeature(), and App::PropertyBool::setValue().
Referenced by connectWidgets().
changeEvent()
void TaskProjGroup::changeEvent (QEvent * event) override protected
Definition at line 623 of file TaskProjGroup.cpp.
connectWidgets()
void TaskProjGroup::connectWidgets () protected
Definition at line 93 of file TaskProjGroup.cpp.
References AutoDistributeClicked(), draftgeoutils.intersections::connect(), customDirectionClicked(), projectionTypeChanged(), rotateButtonClicked(), scaleManuallyChanged(), scaleTypeChanged(), and spacingChanged().
Referenced by TaskProjGroup().
customDirectionClicked
void TaskProjGroup::customDirectionClicked () protected slot
Definition at line 378 of file TaskProjGroup.cpp.
References TechDraw::DrawViewPart::Direction, TechDraw::DrawProjGroup::getAnchor(), App::PropertyVector::getValue(), setUiPrimary(), App::PropertyVector::setValue(), TechDraw::DrawProjGroup::spin(), and Base::toRadians().
Referenced by connectWidgets().
formatVector()
QString TaskProjGroup::formatVector (Base::Vector3d vec) protected
Definition at line 763 of file TaskProjGroup.cpp.
References DraftVecUtils::toString(), and SurfaceTests.TestBlendCurve::vec.
Referenced by setUiPrimary().
getCreateMode()
bool TechDrawGui::TaskProjGroup::getCreateMode () const inline
Definition at line 71 of file TaskProjGroup.h.
Referenced by TechDrawGui::TaskDlgProjGroup::open(), and reject().
initializeUi()
void TaskProjGroup::initializeUi () protected
Definition at line 127 of file TaskProjGroup.cpp.
References TechDraw::DrawProjGroup::AutoDistribute, TechDraw::DrawView::getScale(), App::PropertyQuantity::getValue(), App::PropertyEnumeration::getValue(), App::PropertyBool::getValue(), App::PropertyEnumeration::isValue(), Base::Unit::Length, TechDraw::DrawProjGroup::ProjectionType, TechDraw::DrawView::ScaleType, setFractionalScale(), setupViewCheckboxes(), TechDraw::DrawProjGroup::spacingX, and TechDraw::DrawProjGroup::spacingY.
Referenced by TaskProjGroup().
modifyStandardButtons()
void TechDrawGui::TaskProjGroup::modifyStandardButtons (QDialogButtonBox * box)
projectionTypeChanged
void TaskProjGroup::projectionTypeChanged (QString qText) protected slot
Definition at line 487 of file TaskProjGroup.cpp.
References TechDraw::DrawProjGroup::ProjectionType, TechDraw::DrawProjGroup::recomputeChildren(), setupViewCheckboxes(), and App::PropertyEnumeration::setValue().
Referenced by connectWidgets().
reject()
bool TaskProjGroup::reject () virtual
Definition at line 809 of file TaskProjGroup.cpp.
References Gui::Command::abortCommand(), toolbit-attributes::doc, doCommand, TechDraw::DrawView::findParentPage(), getCreateMode(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), App::DocumentObject::getNameInDocument(), Gui::Command::Gui, Gui::Command::hasPendingCommand(), Gui::Application::Instance, and runCommand.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and TechDrawGui::TaskDlgProjGroup::reject().
restoreGroupState()
void TaskProjGroup::restoreGroupState () protected
Definition at line 236 of file TaskProjGroup.cpp.
References TechDraw::DrawProjGroup::addProjection(), TechDraw::DrawProjGroup::AutoDistribute, TechDraw::DrawProjGroup::ProjectionType, TechDraw::DrawProjGroup::purgeProjections(), TechDraw::DrawView::Scale, TechDraw::DrawView::ScaleType, App::PropertyQuantity::setValue(), App::PropertyEnumeration::setValue(), App::PropertyFloat::setValue(), App::PropertyBool::setValue(), TechDraw::DrawProjGroup::spacingX, and TechDraw::DrawProjGroup::spacingY.
rotateButtonClicked
void TaskProjGroup::rotateButtonClicked () protected slot
Requests appropriate rotation of our DrawProjGroup.
Definition at line 410 of file TaskProjGroup.cpp.
References TechDraw::DrawViewPart::Direction, TechDrawGui::DrawGuiUtil::get3DDirAndRot(), TechDraw::DrawProjGroup::getAnchor(), TechDraw::DrawUtil::getGeomTypeFromName(), TechDrawGui::DrawGuiUtil::getProjDirFromFace(), Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), src.Mod.AddonManager.addonmanager_pyside_interface::QObject, TechDraw::DrawProjGroup::rotate(), TechDraw::DrawViewPart::rotate(), TechDraw::DrawProjGroupItem::RotationVector, Path.Dressup.Utils::selection(), setUiPrimary(), App::PropertyVector::setValue(), TechDraw::DrawProjGroup::spin(), TechDraw::DrawProjGroup::updateSecondaryDirs(), and TechDraw::DrawViewPart::XDirection.
Referenced by connectWidgets().
saveButtons()
void TaskProjGroup::saveButtons (QPushButton * btnOK, QPushButton * btnCancel, QPushButton * btnApply)
Definition at line 772 of file TaskProjGroup.cpp.
Referenced by TechDrawGui::TaskDlgProjGroup::modifyStandardButtons().
saveGroupState()
void TaskProjGroup::saveGroupState () protected
Definition at line 208 of file TaskProjGroup.cpp.
References TechDraw::DrawProjGroup::AutoDistribute, TechDraw::DrawViewPart::Direction, TechDraw::DrawProjGroup::getAnchor(), App::PropertyQuantity::getValue(), App::PropertyVector::getValue(), App::PropertyFloat::getValue(), App::PropertyBool::getValue(), App::PropertyEnumeration::getValueAsString(), App::PropertyListsT< T, ListT, ParentT >::getValues(), TechDraw::DrawProjGroup::ProjectionType, TechDraw::DrawView::Scale, TechDraw::DrawView::ScaleType, TechDraw::DrawProjGroup::Source, TechDraw::DrawProjGroup::spacingX, TechDraw::DrawProjGroup::spacingY, and TechDraw::DrawViewCollection::Views.
Referenced by TaskProjGroup().
scaleManuallyChanged
void TaskProjGroup::scaleManuallyChanged (int unused) protected slot
Definition at line 603 of file TaskProjGroup.cpp.
References Gui::Command::Doc, doCommand, App::DocumentObject::getNameInDocument(), App::PropertyEnumeration::isValue(), App::DocumentObject::recomputeFeature(), and TechDraw::DrawView::ScaleType.
Referenced by connectWidgets().
scaleTypeChanged
void TaskProjGroup::scaleTypeChanged (int index) protected slot
Definition at line 522 of file TaskProjGroup.cpp.
References TechDraw::DrawView::autoScale(), TechDraw::DrawView::Scale, TechDraw::DrawView::ScaleType, App::PropertyEnumeration::setValue(), and App::PropertyFloat::setValue().
Referenced by connectWidgets().
setCreateMode()
void TechDrawGui::TaskProjGroup::setCreateMode (bool mode) inline
Definition at line 70 of file TaskProjGroup.h.
Referenced by TechDrawGui::TaskDlgProjGroup::setCreateMode().
setFractionalScale()
void TaskProjGroup::setFractionalScale (double newScale)
Definition at line 592 of file TaskProjGroup.cpp.
Referenced by initializeUi(), updateTask(), and viewToggled().
setUiPrimary()
void TaskProjGroup::setUiPrimary () protected
sets the main direction of the view
Definition at line 748 of file TaskProjGroup.cpp.
References formatVector(), and TechDraw::DrawProjGroup::getAnchorDirection().
Referenced by customDirectionClicked(), rotateButtonClicked(), and TaskProjGroup().
setupViewCheckboxes()
void TaskProjGroup::setupViewCheckboxes (bool addConnections = false) protected
Connects and updates state of view checkboxes to match the state of multiView.
If addConnections is true, then also sets up Qt connections between checkboxes and viewToggled()
Definition at line 700 of file TaskProjGroup.cpp.
References MengerSponge::box, TechDraw::DrawProjGroup::canDelete(), draftgeoutils.intersections::connect(), TechDraw::DrawProjGroup::hasProjection(), SplineSurface::i, and viewToggled().
Referenced by initializeUi(), and projectionTypeChanged().
spacingChanged
void TaskProjGroup::spacingChanged () protected slot
Updates item spacing.
Definition at line 569 of file TaskProjGroup.cpp.
References App::DocumentObject::recomputeFeature(), App::PropertyQuantity::setValue(), TechDraw::DrawProjGroup::spacingX, and TechDraw::DrawProjGroup::spacingY.
Referenced by connectWidgets().
turnProjGroupToView()
void TaskProjGroup::turnProjGroupToView () protected
Definition at line 346 of file TaskProjGroup.cpp.
References TechDraw::DrawPage::addView(), doCommand, TechDraw::DrawProjGroup::getAnchor(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), App::DocumentObject::getNameInDocument(), App::PropertyQuantity::getValue(), App::PropertyEnumeration::getValue(), App::PropertyFloat::getValue(), Gui::Document::getViewProvider(), Gui::Command::Gui, App::Property::Hidden, Gui::Application::Instance, App::DocumentObject::Label, TechDraw::DrawView::LockPosition, App::Property::ReadOnly, App::DocumentObject::recomputeFeature(), TechDraw::DrawViewCollection::removeView(), TechDraw::DrawView::Scale, TechDraw::DrawView::ScaleType, App::Property::setStatus(), App::PropertyQuantity::setValue(), App::PropertyEnumeration::setValue(), App::PropertyFloat::setValue(), App::PropertyString::setValue(), App::PropertyBool::setValue(), TechDrawGui::ViewProviderProjGroupItem::updateIcon(), updateUi(), TechDraw::DrawView::X, and TechDraw::DrawView::Y.
Referenced by viewToggled().
turnViewToProjGroup()
void TaskProjGroup::turnViewToProjGroup () protected
Definition at line 306 of file TaskProjGroup.cpp.
References TechDraw::DrawViewCollection::addView(), TechDraw::DrawProjGroup::Anchor, toolbit-attributes::doc, doCommand, TechDraw::DrawView::findParentPage(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), Gui::Command::Gui, App::Property::Hidden, TechDraw::DrawProjGroup::ProjectionType, App::Property::purgeTouched(), App::Property::ReadOnly, TechDraw::DrawPage::removeView(), TechDraw::DrawPage::requestPaint(), TechDraw::DrawView::Scale, TechDraw::DrawView::ScaleType, App::PropertyQuantity::setValue(), App::PropertyEnumeration::setValue(), App::PropertyFloat::setValue(), App::PropertyLink::setValue(), App::PropertyLinkList::setValues(), App::PropertyXLinkSubList::setValues(), TechDraw::DrawProjGroup::Source, updateUi(), TechDraw::DrawView::X, TechDraw::DrawProjGroup::XSource, and TechDraw::DrawView::Y.
Referenced by viewToggled().
updateTask()
void TaskProjGroup::updateTask ()
Definition at line 579 of file TaskProjGroup.cpp.
References TechDraw::DrawView::getScale(), App::PropertyEnumeration::getValue(), TechDraw::DrawView::ScaleType, and setFractionalScale().
Referenced by TechDrawGui::TaskDlgProjGroup::update().
updateUi()
void TaskProjGroup::updateUi () protected
enable/disable the appropriate widgets
Definition at line 178 of file TaskProjGroup.cpp.
Referenced by TaskProjGroup(), turnProjGroupToView(), and turnViewToProjGroup().
useThirdAngle()
bool TaskProjGroup::useThirdAngle () protected
Definition at line 674 of file TaskProjGroup.cpp.
References TechDraw::DrawView::findParentPage(), App::Enumeration::isValue(), and TechDraw::DrawProjGroup::usedProjectionType().
viewToggled
void TaskProjGroup::viewToggled (bool toggle) protected slot
Definition at line 259 of file TaskProjGroup.cpp.
References TechDraw::DrawProjGroup::canDelete(), Gui::Command::Doc, doCommand, App::DocumentObject::getNameInDocument(), TechDraw::DrawView::getScale(), App::PropertyListsT< T, ListT, ParentT >::getValues(), TechDraw::DrawProjGroup::hasProjection(), App::PropertyEnumeration::isValue(), App::DocumentObject::recomputeFeature(), TechDraw::DrawProjGroup::removeProjection(), Gui::WaitCursor::restoreCursor(), TechDraw::DrawView::ScaleType, setFractionalScale(), turnProjGroupToView(), turnViewToProjGroup(), and TechDraw::DrawViewCollection::Views.
Referenced by setupViewCheckboxes().
The documentation for this class was generated from the following files:
TaskProjGroup.h
TaskProjGroup.cpp