FreeCAD: Gui::Dialog::DockablePlacement Class Reference
Gui::Dialog::DockablePlacement Class Reference
#include <Placement.h>
Public Member Functions
DockablePlacement (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DockablePlacement () override
void accept () override
void reject () override
Public Member Functions inherited from Gui::Dialog::Placement
Placement (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~Placement () override
void open () override
void accept () override
void reject () override
void setPropertyName (const std::string &)
void setSelection (const std::vector< SelectionObject > &)
Placement::setSelection Sets the array of selection objects.
void bindObject ()
Placement::bindObject Binds the spin boxes to the placement components of the first object of the selection. This requires the call of setSelection() beforehand.
void setPlacementAndBindObject (const App::DocumentObject *obj, const std::string &propertyName)
Placement::setPlacementAndBindObject Sets the placement, binds the spin boxes to the placement components of the passed object and sets the name of the placement property.
void setIgnoreTransactions (bool value)
Base::Vector3d getDirection () const
void setPlacement (const Base::Placement &)
Base::Placement getPlacement () const
void showDefaultButtons (bool)
Additional Inherited Members
Public Slots inherited from Gui::Dialog::Placement
void onApplyButtonClicked ()
Signals inherited from Gui::Dialog::Placement
void placementChanged (const QVariant &, bool, bool)
Protected Member Functions inherited from Gui::Dialog::Placement
void changeEvent (QEvent *e) override
void keyPressEvent (QKeyEvent *) override
Detailed Description
Definition at line 179 of file Gui/Placement.h.
Constructor & Destructor Documentation
DockablePlacement()
DockablePlacement::DockablePlacement (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Definition at line 1101 of file Gui/Placement.cpp.
References Gui::DockWindowManager::addDockWindow(), and Gui::DockWindowManager::instance().
~DockablePlacement()
DockablePlacement::~DockablePlacement () override default
Member Function Documentation
accept()
void DockablePlacement::accept () override
Definition at line 1112 of file Gui/Placement.cpp.
References Gui::Dialog::Placement::accept(), Gui::DockWindowManager::instance(), and Gui::DockWindowManager::removeDockWindow().
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
reject()
void DockablePlacement::reject () override
Definition at line 1120 of file Gui/Placement.cpp.
References Gui::DockWindowManager::instance(), Gui::Dialog::Placement::reject(), and Gui::DockWindowManager::removeDockWindow().
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
Gui/Placement.h
Gui/Placement.cpp