FreeCAD: MeshCore::MeshEvalPointManifolds Class Reference
MeshCore::MeshEvalPointManifolds Class Reference
#include <Evaluation.h>
Public Member Functions
MeshEvalPointManifolds (const MeshKernel &rclB)
bool Evaluate () override
void GetFacetIndices (std::vector< FacetIndex > &facets) const
const std::list< std::vector< FacetIndex > > & GetFacetIndices () const
const std::vector< FacetIndex > & GetIndices () const
unsigned long CountManifolds () const
Public Member Functions inherited from MeshCore::MeshEvaluation
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()=default
MeshEvaluation (const MeshEvaluation &)=delete
MeshEvaluation (MeshEvaluation &&)=delete
MeshEvaluation & operator= (const MeshEvaluation &)=delete
MeshEvaluation & operator= (MeshEvaluation &&)=delete
Additional Inherited Members
Protected Attributes inherited from MeshCore::MeshEvaluation
const MeshKernel & _rclMesh
Detailed Description
The MeshEvalPointManifolds class checks for non-manifold points. A point is considered non-manifold if two sets of triangles share the point but are not topologically connected over a common edge. Such mesh defects can lead to some very ugly folds on the surface.
Definition at line 279 of file Evaluation.h.
Constructor & Destructor Documentation
MeshEvalPointManifolds()
MeshCore::MeshEvalPointManifolds::MeshEvalPointManifolds (const MeshKernel & rclB) inline explicit
Definition at line 282 of file Evaluation.h.
Member Function Documentation
CountManifolds()
unsigned long MeshCore::MeshEvalPointManifolds::CountManifolds () const inline
Definition at line 296 of file Evaluation.h.
Evaluate()
bool MeshEvalPointManifolds::Evaluate () override virtual
Evaluates the mesh kernel with respect to certain criteria. Must be reimplemented by every subclass. This pure virtual function returns false if the mesh kernel is invalid according to this criterion and true if the mesh kernel is correct.
Implements MeshCore::MeshEvaluation.
Definition at line 474 of file Evaluation.cpp.
References MeshCore::MeshEvaluation::_rclMesh, MeshCore::MeshKernel::CountPoints(), and Mesh2Shape::faces.
Referenced by Mesh::MeshObject::removeNonManifoldPoints().
GetFacetIndices() [1/2]
const std::list<std::vector<FacetIndex> >& MeshCore::MeshEvalPointManifolds::GetFacetIndices () const inline
Definition at line 288 of file Evaluation.h.
GetFacetIndices() [2/2]
void MeshEvalPointManifolds::GetFacetIndices (std::vector< FacetIndex > & facets) const
Definition at line 506 of file Evaluation.cpp.
Referenced by Mesh::MeshObject::removeNonManifoldPoints().
GetIndices()
const std::vector<FacetIndex>& MeshCore::MeshEvalPointManifolds::GetIndices () const inline
Definition at line 292 of file Evaluation.h.
The documentation for this class was generated from the following files:
Evaluation.h
Evaluation.cpp