FreeCAD: App::ColorModel Class Reference
App::ColorModel Class Reference
#include <ColorModel.h>
Public Member Functions
ColorModel ()=default
ColorModel (std::size_t usCt)
ColorModel (const ColorModel &)=default
virtual ~ColorModel ()=default
ColorModel & operator= (const ColorModel &)=default
std::size_t getCountColors () const
Public Attributes
std::vector< Color > colors
Detailed Description
Definition at line 75 of file ColorModel.h.
Constructor & Destructor Documentation
ColorModel() [1/3]
App::ColorModel::ColorModel () default
ColorModel() [2/3]
App::ColorModel::ColorModel (std::size_t usCt) inline explicit
Definition at line 79 of file ColorModel.h.
References importers.importIFCmulticore::colors.
ColorModel() [3/3]
App::ColorModel::ColorModel (const ColorModel &) default
~ColorModel()
virtual App::ColorModel::~ColorModel () virtual default
Member Function Documentation
getCountColors()
std::size_t App::ColorModel::getCountColors () const inline
Definition at line 86 of file ColorModel.h.
References importers.importIFCmulticore::colors.
Referenced by App::ColorField::getColor(), App::ColorField::rebuild(), and App::ColorField::set().
operator=()
ColorModel& App::ColorModel::operator= (const ColorModel &) default
Member Data Documentation
colors
std::vector<Color> App::ColorModel::colors
Definition at line 90 of file ColorModel.h.
Referenced by App::ColorField::getColor(), App::ColorField::rebuild(), Path.Dressup.Gui.Tags.PathDressupTagViewProvider::setupColors(), and Path.Dressup.Gui.Tags.PathDressupTagViewProvider::updatePositions().
The documentation for this class was generated from the following file:
ColorModel.h