FreeCAD: MeshGui::SoFCMeshObjectElement Class Reference
MeshGui::SoFCMeshObjectElement Class Reference
#include <SoFCMeshObject.h>
Public Member Functions
void init (SoState *state) override
void print (FILE *file) const override
Static Public Member Functions
static void initClass ()
static void set (SoState *const state, SoNode *const node, const Mesh::MeshObject *const mesh)
static const Mesh::MeshObject * get (SoState *const state)
static const SoFCMeshObjectElement * getInstance (SoState *state)
Protected Member Functions
~SoFCMeshObjectElement () override
Detailed Description
Definition at line 64 of file SoFCMeshObject.h.
Constructor & Destructor Documentation
~SoFCMeshObjectElement()
SoFCMeshObjectElement::~SoFCMeshObjectElement () override protected default
Member Function Documentation
get()
const Mesh::MeshObject * SoFCMeshObjectElement::get (SoState *const state) static
Definition at line 330 of file SoFCMeshObject.cpp.
References getInstance().
Referenced by MeshGui::SoFCMeshObjectShape::computeBBox(), MeshGui::SoFCMeshSegmentShape::computeBBox(), MeshGui::SoFCMeshObjectBoundary::computeBBox(), MeshGui::SoFCMeshObjectShape::generatePrimitives(), MeshGui::SoFCMeshSegmentShape::generatePrimitives(), MeshGui::SoFCMeshObjectBoundary::generatePrimitives(), MeshGui::SoFCMeshObjectShape::getPrimitiveCount(), MeshGui::SoFCMeshSegmentShape::getPrimitiveCount(), MeshGui::SoFCMeshObjectBoundary::getPrimitiveCount(), MeshGui::SoFCMeshObjectShape::GLRender(), MeshGui::SoFCMeshSegmentShape::GLRender(), and MeshGui::SoFCMeshObjectBoundary::GLRender().
getInstance()
const SoFCMeshObjectElement * SoFCMeshObjectElement::getInstance (SoState * state) static
Definition at line 335 of file SoFCMeshObject.cpp.
Referenced by get().
init()
void SoFCMeshObjectElement::init (SoState * state) override
Definition at line 310 of file SoFCMeshObject.cpp.
References SIM::Coin3D::Quarter::Quarter::init().
Referenced by DocumentObject.DocumentObject::onChanged().
initClass()
void SoFCMeshObjectElement::initClass () static
Definition at line 305 of file SoFCMeshObject.cpp.
Referenced by PyMOD_INIT_FUNC().
print()
void SoFCMeshObjectElement::print (FILE * file) const override
Definition at line 341 of file SoFCMeshObject.cpp.
set()
void SoFCMeshObjectElement::set (SoState *const state, SoNode *const node, const Mesh::MeshObject *const mesh) static
Definition at line 318 of file SoFCMeshObject.cpp.
Referenced by MeshGui::SoFCMeshObjectNode::doAction().
The documentation for this class was generated from the following files:
SoFCMeshObject.h
SoFCMeshObject.cpp