FreeCAD: CommandSketcherBSpline.cpp File Reference
CommandSketcherBSpline.cpp File Reference
#include "PreCompiled.h"
#include <Inventor/SbString.h>
#include <QApplication>
#include <cfloat>
#include <App/Application.h>
#include <Base/Console.h>
#include <Gui/Action.h>
#include <Gui/Application.h>
#include <Gui/BitmapFactory.h>
#include <Gui/CommandT.h>
#include <Gui/Document.h>
#include <Gui/MainWindow.h>
#include <Gui/Notifications.h>
#include <Gui/Selection.h>
#include <Gui/SelectionObject.h>
#include <Mod/Sketcher/App/SketchObject.h>
#include "DrawSketchHandler.h"
#include "Utils.h"
#include "ViewProviderSketch.h"
Classes
class DrawSketchHandlerBSplineInsertKnot
Functions
void ActivateBSplineHandler (Gui::Document *doc, DrawSketchHandler *handler)
bool findBSplineAndKnotIndex (Sketcher::SketchObject *Obj, int knotGeoId, Sketcher::PointPos knotPosId, int &splineGeoId, int &knotIndexOCC)
void CreateSketcherCommandsBSpline ()
Function Documentation
ActivateBSplineHandler()
void ActivateBSplineHandler (Gui::Document * doc, DrawSketchHandler * handler)
Definition at line 52 of file CommandSketcherBSpline.cpp.
References SketcherGui::ViewProviderSketch::activateHandler(), toolbit-attributes::doc, Base::Persistence::getClassTypeId(), buildPsets::handler, Path.Post.scripts.opensbp_post::move(), and SketcherGui::ViewProviderSketch::purgeHandler().
CreateSketcherCommandsBSpline()
void CreateSketcherCommandsBSpline ()
Definition at line 1107 of file CommandSketcherBSpline.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
findBSplineAndKnotIndex()
bool findBSplineAndKnotIndex (Sketcher::SketchObject * Obj, int knotGeoId, Sketcher::PointPos knotPosId, int & splineGeoId, int & knotIndexOCC)
For a knot given by (GeoId, PosId) finds the B-Spline and the knot's index within it (by OCC numbering). Returns true if the entities are found, false otherwise. If returns false, splineGeoId and knotIndexOCC have garbage values.
Definition at line 70 of file CommandSketcherBSpline.cpp.
References Sketcher::BSplineKnotPoint, Sketcher::SketchObject::Constraints, Sketcher::end, Sketcher::SketchObject::getGeometry(), Sketcher::PropertyConstraintList::getValues(), Sketcher::InternalAlignment, Base::BaseClass::is(), and Sketcher::start.