FreeCAD: ifc2x3.ifclightdistributiondata Class Reference
ifc2x3.ifclightdistributiondata Class Reference
Public Member Functions
def __init__ (self, mainplaneangle, secondaryplaneangle, luminousintensity)
def mainplaneangle ()
def secondaryplaneangle ()
def luminousintensity ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
mainplaneangle
secondaryplaneangle
luminousintensity
Detailed Description
Entity ifclightdistributiondata definition.
:param mainplaneangle
:type mainplaneangle:ifcplaneanglemeasure
:param secondaryplaneangle
:type secondaryplaneangle:LIST(1,None,'REAL', scope = schema_scope)
:param luminousintensity
:type luminousintensity:LIST(1,None,'REAL', scope = schema_scope)
Definition at line 34362 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifclightdistributiondata.__init__ (self, mainplaneangle, secondaryplaneangle, luminousintensity)
Definition at line 34374 of file ifc2x3.py.
Member Function Documentation
luminousintensity()
def ifc2x3.ifclightdistributiondata.luminousintensity ()
Definition at line 34408 of file ifc2x3.py.
References ifc2x3.ifclightdistributiondata._luminousintensity, SCL.TypeChecker.check_type(), and ifc2x3.ifclightdistributiondata.luminousintensity.
mainplaneangle()
def ifc2x3.ifclightdistributiondata.mainplaneangle ()
Definition at line 34380 of file ifc2x3.py.
References ifc2x3.ifclightdistributiondata._mainplaneangle, SCL.TypeChecker.check_type(), and ifc2x3.ifclightdistributiondata.mainplaneangle.
secondaryplaneangle()
def ifc2x3.ifclightdistributiondata.secondaryplaneangle ()
Definition at line 34394 of file ifc2x3.py.
References ifc2x3.ifclightdistributiondata._secondaryplaneangle, SCL.TypeChecker.check_type(), and ifc2x3.ifclightdistributiondata.secondaryplaneangle.
Member Data Documentation
luminousintensity
ifc2x3.ifclightdistributiondata.luminousintensity
Definition at line 34377 of file ifc2x3.py.
Referenced by ifc2x3.ifclightdistributiondata.luminousintensity().
mainplaneangle
ifc2x3.ifclightdistributiondata.mainplaneangle
Definition at line 34375 of file ifc2x3.py.
Referenced by ifc2x3.ifclightdistributiondata.mainplaneangle().
secondaryplaneangle
ifc2x3.ifclightdistributiondata.secondaryplaneangle
Definition at line 34376 of file ifc2x3.py.
Referenced by ifc2x3.ifclightdistributiondata.secondaryplaneangle().
The documentation for this class was generated from the following file:
ifc2x3.py