FreeCAD: OpenSCADFeatures.CGALFeature Class Reference
OpenSCADFeatures.CGALFeature Class Reference
Public Member Functions
def __init__ (self, obj, opname=None, children=None, arguments=None)
def execute (self, fp)
Detailed Description
Definition at line 531 of file OpenSCADFeatures.py.
Constructor & Destructor Documentation
__init__()
def OpenSCADFeatures.CGALFeature.__init__ (self, obj, opname = None, children = None, arguments = None)
Definition at line 532 of file OpenSCADFeatures.py.
Member Function Documentation
execute()
def OpenSCADFeatures.CGALFeature.execute (self, fp)
Definition at line 544 of file OpenSCADFeatures.py.
Referenced by src.Mod.PartDesign.Scripts.Spring.MySpring.onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped.onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder.onChanged(), and FeaturePython.DistanceBolt.onChanged().
The documentation for this class was generated from the following file:
OpenSCADFeatures.py