FreeCAD: Inspection::MeshInspectGrid Class Reference
Inspection::MeshInspectGrid Class Reference
Public Member Functions
MeshInspectGrid (const MeshCore::MeshKernel &mesh, float fGridLen, const Base::Matrix4D &mat)
void Validate (const MeshCore::MeshKernel &kernel) override
void Validate ()
bool Verify () const override
Public Member Functions inherited from MeshCore::MeshGrid
virtual unsigned long Inside (const Base::BoundBox3f &rclBB, std::vector< ElementIndex > &raulElements, bool bDelDoubles=true) const
virtual unsigned long Inside (const Base::BoundBox3f &rclBB, std::set< ElementIndex > &raulElementss) const
virtual unsigned long Inside (const Base::BoundBox3f &rclBB, std::vector< ElementIndex > &raulElements, const Base::Vector3f &rclOrg, float fMaxDist, bool bDelDoubles=true) const
void SearchNearestFromPoint (const Base::Vector3f &pnt, std::set< ElementIndex > &indices) const
unsigned long GetElements (unsigned long ulX, unsigned long ulY, unsigned long ulZ, std::set< ElementIndex > &raclInd) const
unsigned long GetElements (const Base::Vector3f &rclPoint, std::vector< ElementIndex > &aulFacets) const
virtual void GetGridLengths (float &rfLenX, float &rfLenY, float &rfLenZ) const
virtual void GetCtGrids (unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
Base::BoundBox3f GetBoundBox (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
Base::BoundBox3f GetBoundBox () const
Base::BoundBox3f GetMeshBoundBox () const
unsigned long GetIndexToPosition (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
bool GetPositionToIndex (unsigned long id, unsigned long &ulX, unsigned long &ulY, unsigned long &ulZ) const
unsigned long GetCtElements (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
bool CheckPosition (const Base::Vector3f &rclPoint, unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
virtual void Position (const Base::Vector3f &rclPoint, unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
bool CheckPos (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
void GetHull (unsigned long ulX, unsigned long ulY, unsigned long ulZ, unsigned long ulDistance, std::set< ElementIndex > &raclInd) const
virtual ~MeshGrid ()=default
Destruction.
virtual void Attach (const MeshKernel &rclM)
virtual void Rebuild (int iCtGridPerAxis=20)
virtual void Rebuild (unsigned long ulX, unsigned long ulY, unsigned long ulZ)
Protected Member Functions
void CalculateGridLength (int) override
unsigned long HasElements () const override
void Pos (const Base::Vector3f &rclPoint, unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
void AddFacet (const MeshCore::MeshGeomFacet &rclFacet, unsigned long ulFacetIndex)
void InitGrid () override
void RebuildGrid () override
Protected Member Functions inherited from MeshCore::MeshGrid
virtual void Clear ()
MeshGrid (const MeshKernel &rclM)
Construction.
MeshGrid ()
Construction.
MeshGrid (const MeshGrid &)=default
MeshGrid (MeshGrid &&)=default
MeshGrid & operator= (const MeshGrid &)=default
MeshGrid & operator= (MeshGrid &&)=default
Additional Inherited Members
Protected Attributes inherited from MeshCore::MeshGrid
std::vector< std::vector< std::vector< std::set< ElementIndex > > > > _aulGrid
const MeshKernel * _pclMesh
unsigned long _ulCtElements
unsigned long _ulCtGridsX
unsigned long _ulCtGridsY
unsigned long _ulCtGridsZ
float _fGridLenX
float _fGridLenY
float _fGridLenZ
float _fMinX
float _fMinY
float _fMinZ
Detailed Description
Definition at line 149 of file InspectionFeature.cpp.
Constructor & Destructor Documentation
MeshInspectGrid()
Inspection::MeshInspectGrid::MeshInspectGrid (const MeshCore::MeshKernel & mesh, float fGridLen, const Base::Matrix4D & mat) inline
Definition at line 152 of file InspectionFeature.cpp.
References MeshCore::MeshGrid::_pclMesh, MeshCore::MeshKernel::GetBoundBox(), Base::BoundBox3< Precision >::LengthX(), Base::BoundBox3< Precision >::LengthY(), Base::BoundBox3< Precision >::LengthZ(), MeshCore::MeshGrid::Rebuild(), and Base::BoundBox3< Precision >::Transformed().
Member Function Documentation
AddFacet()
void Inspection::MeshInspectGrid::AddFacet (const MeshCore::MeshGeomFacet & rclFacet, unsigned long ulFacetIndex) inline protected
Definition at line 202 of file InspectionFeature.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::MeshGrid::_aulGrid, Base::BoundBox3< Precision >::Add(), MeshCore::MeshGrid::GetBoundBox(), MeshCore::MeshGeomFacet::IntersectBoundingBox(), Base::BoundBox3< Precision >::MaxX, Base::BoundBox3< Precision >::MaxY, Base::BoundBox3< Precision >::MaxZ, Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, Base::BoundBox3< Precision >::MinZ, and Pos().
Referenced by RebuildGrid().
CalculateGridLength()
void Inspection::MeshInspectGrid::CalculateGridLength (int iCtGridPerAxis) inline override protected virtual
Calculates the grid length dependent on the number of grids per axis.
Reimplemented from MeshCore::MeshGrid.
Definition at line 180 of file InspectionFeature.cpp.
HasElements()
unsigned long Inspection::MeshInspectGrid::HasElements () const inline override protected virtual
Returns the number of stored elements. Must be implemented in sub-classes.
Implements MeshCore::MeshGrid.
Definition at line 185 of file InspectionFeature.cpp.
References MeshCore::MeshGrid::_pclMesh, and MeshCore::MeshKernel::CountFacets().
InitGrid()
void Inspection::MeshInspectGrid::InitGrid () inline override protected virtual
Initializes the size of the internal structure.
Reimplemented from MeshCore::MeshGrid.
Definition at line 236 of file InspectionFeature.cpp.
References MeshCore::MeshGrid::_aulGrid, MeshCore::MeshGrid::_fGridLenX, MeshCore::MeshGrid::_fGridLenY, MeshCore::MeshGrid::_fGridLenZ, MeshCore::MeshGrid::_fMinX, MeshCore::MeshGrid::_fMinY, MeshCore::MeshGrid::_fMinZ, MeshCore::MeshGrid::_pclMesh, MeshCore::MeshGrid::_ulCtGridsX, MeshCore::MeshGrid::_ulCtGridsY, MeshCore::MeshGrid::_ulCtGridsZ, MeshCore::MeshKernel::GetBoundBox(), SplineSurface::i, Base::BoundBox3< Precision >::LengthX(), Base::BoundBox3< Precision >::LengthY(), Base::BoundBox3< Precision >::LengthZ(), Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, Base::BoundBox3< Precision >::MinZ, and Base::BoundBox3< Precision >::Transformed().
Referenced by RebuildGrid().
Pos()
void Inspection::MeshInspectGrid::Pos (const Base::Vector3f & rclPoint, unsigned long & rulX, unsigned long & rulY, unsigned long & rulZ) const inline protected
Definition at line 190 of file InspectionFeature.cpp.
References MeshCore::MeshGrid::_fGridLenX, MeshCore::MeshGrid::_fGridLenY, MeshCore::MeshGrid::_fGridLenZ, MeshCore::MeshGrid::_fMinX, MeshCore::MeshGrid::_fMinY, MeshCore::MeshGrid::_fMinZ, MeshCore::MeshGrid::_ulCtGridsX, MeshCore::MeshGrid::_ulCtGridsY, MeshCore::MeshGrid::_ulCtGridsZ, OpenSCADFeatures::long, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by AddFacet().
RebuildGrid()
void Inspection::MeshInspectGrid::RebuildGrid () inline override protected virtual
Rebuilds the grid structure. Must be implemented in sub-classes.
Implements MeshCore::MeshGrid.
Definition at line 265 of file InspectionFeature.cpp.
References MeshCore::MeshGrid::_pclMesh, MeshCore::MeshGrid::_ulCtElements, AddFacet(), MeshCore::MeshKernel::CountFacets(), SplineSurface::i, MeshCore::MeshFacetIterator::Init(), InitGrid(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), and MeshCore::MeshFacetIterator::Transform().
Validate() [1/2]
void Inspection::MeshInspectGrid::Validate () inline
Definition at line 168 of file InspectionFeature.cpp.
Validate() [2/2]
void Inspection::MeshInspectGrid::Validate (const MeshCore::MeshKernel & rclM) inline override virtual
Validates the grid structure and rebuilds it if needed. Must be implemented in sub-classes.
Implements MeshCore::MeshGrid.
Definition at line 162 of file InspectionFeature.cpp.
Verify()
bool Inspection::MeshInspectGrid::Verify () const inline override virtual
Verifies the grid structure and returns false if inconsistencies are found.
Implements MeshCore::MeshGrid.
Definition at line 173 of file InspectionFeature.cpp.
The documentation for this class was generated from the following file:
InspectionFeature.cpp