FreeCAD: Gui::Dialog::DlgSettings3DViewImp Class Reference
Gui::Dialog::DlgSettings3DViewImp Class Reference
#include <DlgSettings3DViewImp.h>
Public Member Functions
DlgSettings3DViewImp (QWidget *parent=nullptr)
~DlgSettings3DViewImp () override
void saveSettings () override
void loadSettings () override
void resetSettingsToDefaults () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
Detailed Description
The DlgSettings3DViewImp class implements a preference page to change settings for the Inventor viewer.
Author
Jürgen Riegel
Definition at line 41 of file DlgSettings3DViewImp.h.
Constructor & Destructor Documentation
DlgSettings3DViewImp()
DlgSettings3DViewImp::DlgSettings3DViewImp (QWidget * parent = nullptr) explicit
Definition at line 47 of file DlgSettings3DViewImp.cpp.
~DlgSettings3DViewImp()
DlgSettings3DViewImp::~DlgSettings3DViewImp () override default
Member Function Documentation
changeEvent()
void DlgSettings3DViewImp::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 209 of file DlgSettings3DViewImp.cpp.
References Gui::Dialog::PreferencePage::changeEvent(), and SCL.SimpleDataTypes::e.
loadSettings()
void DlgSettings3DViewImp::loadSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 79 of file DlgSettings3DViewImp.cpp.
resetSettingsToDefaults()
void DlgSettings3DViewImp::resetSettingsToDefaults () override virtual
Reimplemented from Gui::Dialog::PreferencePage.
Definition at line 191 of file DlgSettings3DViewImp.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), ParameterGrp::RemoveInt(), and Gui::Dialog::PreferencePage::resetSettingsToDefaults().
saveSettings()
void DlgSettings3DViewImp::saveSettings () override virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 57 of file DlgSettings3DViewImp.cpp.
The documentation for this class was generated from the following files:
DlgSettings3DViewImp.h
DlgSettings3DViewImp.cpp