FreeCAD: Start::DisplayedFilesModel Class Reference
Start::DisplayedFilesModel Class Reference
#include <DisplayedFilesModel.h>
Public Member Functions
DisplayedFilesModel (QObject *parent=nullptr)
int rowCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
void addFile (const QString &filePath)
void clear ()
Protected Member Functions
QHash< int, QByteArray > roleNames () const override
void reCacheFileInfo ()
Detailed Description
A model for displaying a list of files including a thumbnail or icon, plus various file statistics.
Definition at line 73 of file DisplayedFilesModel.h.
Constructor & Destructor Documentation
DisplayedFilesModel()
DisplayedFilesModel::DisplayedFilesModel (QObject * parent = nullptr) explicit
Definition at line 219 of file DisplayedFilesModel.cpp.
Member Function Documentation
addFile()
void DisplayedFilesModel::addFile (const QString & filePath)
Definition at line 279 of file DisplayedFilesModel.cpp.
References Path.Preferences::filePath().
Referenced by Start::ExamplesModel::loadExamples(), and Start::RecentFilesModel::loadRecentFiles().
clear()
void DisplayedFilesModel::clear ()
Definition at line 297 of file DisplayedFilesModel.cpp.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__(), Start::ExamplesModel::loadExamples(), and Start::RecentFilesModel::loadRecentFiles().
data()
QVariant DisplayedFilesModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 230 of file DisplayedFilesModel.cpp.
References Start::author, Start::baseName, Start::company, Start::creationTime, Start::description, Start::image, Start::license, Start::modifiedTime, src.Mod.Test.testPathArray::path, Start::path, and Start::size.
reCacheFileInfo()
void Start::DisplayedFilesModel::reCacheFileInfo () protected
Destroy and recreate the cache of info about the files. Should be connected to a signal indicating when some piece of information about the files has changed. Does NOT generate a new list of files, only re-caches the existing ones.
roleNames()
QHash< int, QByteArray > DisplayedFilesModel::roleNames () const override protected
For communication with QML, define the text version of each role name defined in the DisplayedFilesModelRoles enumeration
Definition at line 302 of file DisplayedFilesModel.cpp.
References Start::author, Start::baseName, Start::company, Start::creationTime, Start::description, Start::image, Start::license, Start::modifiedTime, Start::path, and Start::size.
rowCount()
int DisplayedFilesModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 224 of file DisplayedFilesModel.cpp.
References Init::parent.
The documentation for this class was generated from the following files:
DisplayedFilesModel.h
DisplayedFilesModel.cpp