FreeCAD: ifc2x3.ifctextstyle Class Reference
ifc2x3.ifctextstyle Class Reference
Public Member Functions
def __init__ (self, inherited0__name, textcharacterappearance, textstyle, textfontstyle)
def textcharacterappearance ()
def textstyle ()
def textfontstyle ()
Public Member Functions inherited from ifc2x3.ifcpresentationstyle
def __init__ (self, name)
def name ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
textcharacterappearance
textstyle
textfontstyle
Public Attributes inherited from ifc2x3.ifcpresentationstyle
name
Detailed Description
Entity ifctextstyle definition.
:param textcharacterappearance
:type textcharacterappearance:ifccharacterstyleselect
:param textstyle
:type textstyle:ifctextstyleselect
:param textfontstyle
:type textfontstyle:ifctextfontselect
Definition at line 7985 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifctextstyle.__init__ (self, inherited0__name, textcharacterappearance, textstyle, textfontstyle)
Definition at line 7997 of file ifc2x3.py.
Member Function Documentation
textcharacterappearance()
def ifc2x3.ifctextstyle.textcharacterappearance ()
Definition at line 8004 of file ifc2x3.py.
References ifc2x3.ifctextstyle._textcharacterappearance, SCL.TypeChecker.check_type(), ifc2x3.ifccharacterstyleselect, and ifc2x3.ifctextstyle.textcharacterappearance.
textfontstyle()
def ifc2x3.ifctextstyle.textfontstyle ()
Definition at line 8032 of file ifc2x3.py.
References ifc2x3.ifctextstyle._textfontstyle, SCL.TypeChecker.check_type(), ifc2x3.ifctextfontselect, and ifc2x3.ifctextstyle.textfontstyle.
textstyle()
def ifc2x3.ifctextstyle.textstyle ()
Definition at line 8018 of file ifc2x3.py.
References ifc2x3.ifctextstyle._textstyle, SCL.TypeChecker.check_type(), ifc2x3.ifctextstyleselect, and ifc2x3.ifctextstyle.textstyle.
Member Data Documentation
textcharacterappearance
ifc2x3.ifctextstyle.textcharacterappearance
Definition at line 7999 of file ifc2x3.py.
Referenced by ifc2x3.ifctextstyle.textcharacterappearance().
textfontstyle
ifc2x3.ifctextstyle.textfontstyle
Definition at line 8001 of file ifc2x3.py.
Referenced by ifc2x3.ifctextstyle.textfontstyle().
textstyle
ifc2x3.ifctextstyle.textstyle
Definition at line 8000 of file ifc2x3.py.
Referenced by ifc2x3.ifctextstyle.textstyle().
The documentation for this class was generated from the following file:
ifc2x3.py