FreeCAD: Command.cpp File Reference
Mod/TechDraw/Gui/Command.cpp File Reference
#include "PreCompiled.h"
#include <QApplication>
#include <QFileInfo>
#include <QMessageBox>
#include <QCheckBox>
#include <QPushButton>
#include <vector>
#include <App/Document.h>
#include <App/DocumentObject.h>
#include <App/Link.h>
#include <Base/Console.h>
#include <Base/Tools.h>
#include <Gui/Action.h>
#include <Gui/Application.h>
#include <Gui/BitmapFactory.h>
#include <Gui/Command.h>
#include <Gui/Control.h>
#include <Gui/Document.h>
#include <Gui/FileDialog.h>
#include <Gui/MainWindow.h>
#include <Gui/Selection.h>
#include <Gui/SelectionObject.h>
#include <Gui/ViewProvider.h>
#include <Gui/WaitCursor.h>
#include <Mod/Spreadsheet/App/Sheet.h>
#include <Mod/TechDraw/App/DrawComplexSection.h>
#include <Mod/TechDraw/App/DrawPage.h>
#include <Mod/TechDraw/App/DrawProjGroup.h>
#include <Mod/TechDraw/App/DrawUtil.h>
#include <Mod/TechDraw/App/DrawSVGTemplate.h>
#include <Mod/TechDraw/App/DrawViewArch.h>
#include <Mod/TechDraw/App/DrawViewClip.h>
#include <Mod/TechDraw/App/DrawViewDetail.h>
#include <Mod/TechDraw/App/DrawViewDraft.h>
#include <Mod/TechDraw/App/DrawViewPart.h>
#include <Mod/TechDraw/App/DrawViewSymbol.h>
#include <Mod/TechDraw/App/Preferences.h>
#include <Mod/TechDraw/App/DrawBrokenView.h>
#include "DrawGuiUtil.h"
#include "MDIViewPage.h"
#include "QGIViewPart.h"
#include "QGSPage.h"
#include "QGVPage.h"
#include "Rez.h"
#include "TaskActiveView.h"
#include "TaskComplexSection.h"
#include "TaskDetail.h"
#include "TaskProjGroup.h"
#include "TaskProjection.h"
#include "TaskSectionView.h"
#include "ViewProviderPage.h"
#include "ViewProviderDrawingView.h"
#include "CommandHelpers.h"
Typedefs
using DU = DrawUtil
Functions
void execSimpleSection (Gui::Command *cmd)
void execComplexSection (Gui::Command *cmd)
void getSelectedShapes (Gui::Command *cmd, std::vector< App::DocumentObject * > &shapes, std::vector< App::DocumentObject * > &xShapes, App::DocumentObject *faceObj, std::string &faceName)
std::pair< App::DocumentObject *, std::string > faceFromSelection ()
std::pair< Base::Vector3d, Base::Vector3d > viewDirection ()
bool _checkSelectionBalloon (Gui::Command *cmd, unsigned maxObjs)
common checks of Selection for Dimension commands
bool _checkDrawViewPartBalloon (Gui::Command *cmd)
bool _checkDirectPlacement (const QGIView *view, const std::vector< std::string > &subNames, QPointF &placement)
void CreateTechDrawCommands ()
Typedef Documentation
DU
using DU = DrawUtil
Definition at line 98 of file Mod/TechDraw/Gui/Command.cpp.
Function Documentation
_checkDirectPlacement()
bool _checkDirectPlacement (const QGIView * view, const std::vector< std::string > & subNames, QPointF & placement)
Definition at line 1226 of file Mod/TechDraw/Gui/Command.cpp.
References TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::DrawUtil::getIndexFromName(), TechDrawGui::QGIView::getViewObject(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
_checkDrawViewPartBalloon()
bool _checkDrawViewPartBalloon (Gui::Command * cmd)
Definition at line 1214 of file Mod/TechDraw/Gui/Command.cpp.
References Gui::getMainWindow(), UtilsAssembly::getObject(), Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), Path.Dressup.Utils::selection(), and Path.Log::warning().
_checkSelectionBalloon()
bool _checkSelectionBalloon (Gui::Command * cmd, unsigned maxObjs)
common checks of Selection for Dimension commands
Definition at line 1188 of file Mod/TechDraw/Gui/Command.cpp.
References Base::Persistence::getClassTypeId(), Gui::Command::getDocument(), Gui::getMainWindow(), App::Document::getObjectsOfType(), Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), Path.Dressup.Utils::selection(), and Path.Log::warning().
CreateTechDrawCommands()
void CreateTechDrawCommands ()
Definition at line 1932 of file Mod/TechDraw/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
execComplexSection()
void execComplexSection (Gui::Command * cmd)
Definition at line 909 of file Mod/TechDraw/Gui/Command.cpp.
References Gui::Control(), Base::Persistence::getClassTypeId(), Gui::Command::getDocument(), App::DocumentObject::getInListEx(), Gui::getMainWindow(), Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), TechDraw::DrawComplexSection::isProfileObject(), Gui::OldStyleElement, Init::parent, Path.Dressup.Utils::selection(), Gui::ControlSingleton::showDialog(), and Path.Log::warning().
execSimpleSection()
void execSimpleSection (Gui::Command * cmd)
Definition at line 853 of file Mod/TechDraw/Gui/Command.cpp.
References Gui::Command::commitCommand(), Gui::Control(), Base::Persistence::getClassTypeId(), Gui::getMainWindow(), Gui::SelectionSingleton::getObjectsOfType(), Gui::Command::getSelection(), Gui::ControlSingleton::showDialog(), Gui::Command::updateActive(), and Path.Log::warning().
faceFromSelection()
std::pair< App::DocumentObject *, std::string > faceFromSelection ()
Definition at line 2042 of file Mod/TechDraw/Gui/Command.cpp.
References Base::Persistence::getClassTypeId(), TechDraw::DrawUtil::getGeomTypeFromName(), Gui::SelectionSingleton::getSelectionEx(), Gui::NoResolve, Path.Dressup.Utils::selection(), and Gui::Selection().
Referenced by TechDraw::CommandHelpers::viewDirection(), and viewDirection().
getSelectedShapes()
void getSelectedShapes (Gui::Command * cmd, std::vector< App::DocumentObject * > & shapes, std::vector< App::DocumentObject * > & xShapes, App::DocumentObject * faceObj, std::string & faceName)
extract the selected shapes and xShapes and determine if a face has been selected to define the projection direction
Definition at line 1967 of file Mod/TechDraw/Gui/Command.cpp.
References Base::Persistence::getClassTypeId(), Gui::Command::getDocument(), TechDraw::DrawUtil::getGeomTypeFromName(), Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), Gui::OldStyleElement, Init::parent, and Path.Dressup.Utils::selection().
viewDirection()
std::pair< Base::Vector3d, Base::Vector3d > viewDirection ()
Definition at line 2028 of file Mod/TechDraw/Gui/Command.cpp.
References faceFromSelection(), and TechDraw::Preferences::useCameraDirection().
Referenced by MeasureGui::ViewProviderMeasureBase::getTextDirection().