FreeCAD: ifc4.ifcprojectedcrs Class Reference
ifc4.ifcprojectedcrs Class Reference
Public Member Functions
def __init__ (self, inherited0__name, inherited1__description, inherited2__geodeticdatum, inherited3__verticaldatum, mapprojection, mapzone, mapunit)
def mapprojection ()
def mapzone ()
def mapunit ()
def wr11 (self)
Public Member Functions inherited from ifc4.ifccoordinatereferencesystem
def __init__ (self, name, description, geodeticdatum, verticaldatum)
def name ()
def description ()
def geodeticdatum ()
def verticaldatum ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
mapprojection
mapzone
mapunit
unittype
Public Attributes inherited from ifc4.ifccoordinatereferencesystem
name
description
geodeticdatum
verticaldatum
Detailed Description
Entity ifcprojectedcrs definition.
:param mapprojection
:type mapprojection:ifcidentifier
:param mapzone
:type mapzone:ifcidentifier
:param mapunit
:type mapunit:ifcnamedunit
Definition at line 30133 of file ifc4.py.
Constructor & Destructor Documentation
__init__()
def ifc4.ifcprojectedcrs.__init__ (self, inherited0__name, inherited1__description, inherited2__geodeticdatum, inherited3__verticaldatum, mapprojection, mapzone, mapunit)
Definition at line 30145 of file ifc4.py.
Member Function Documentation
mapprojection()
def ifc4.ifcprojectedcrs.mapprojection ()
Definition at line 30152 of file ifc4.py.
References ifc4.ifcprojectedcrs._mapprojection, SCL.TypeChecker.check_type(), and ifc4.ifcprojectedcrs.mapprojection.
mapunit()
def ifc4.ifcprojectedcrs.mapunit ()
Definition at line 30180 of file ifc4.py.
References ifc4.ifcprojectedcrs._mapunit, SCL.TypeChecker.check_type(), and ifc4.ifcprojectedcrs.mapunit.
mapzone()
def ifc4.ifcprojectedcrs.mapzone ()
Definition at line 30166 of file ifc4.py.
References ifc4.ifcprojectedcrs._mapzone, SCL.TypeChecker.check_type(), and ifc4.ifcprojectedcrs.mapzone.
wr11()
def ifc4.ifcprojectedcrs.wr11 (self)
Definition at line 30192 of file ifc4.py.
Member Data Documentation
mapprojection
ifc4.ifcprojectedcrs.mapprojection
Definition at line 30147 of file ifc4.py.
Referenced by ifc4.ifcprojectedcrs.mapprojection().
mapunit
ifc4.ifcprojectedcrs.mapunit
Definition at line 30149 of file ifc4.py.
Referenced by ifc4.ifcprojectedcrs.mapunit().
mapzone
ifc4.ifcprojectedcrs.mapzone
Definition at line 30148 of file ifc4.py.
Referenced by ifc4.ifcprojectedcrs.mapzone().
unittype
ifc4.ifcprojectedcrs.unittype
Definition at line 30193 of file ifc4.py.
The documentation for this class was generated from the following file:
ifc4.py