FreeCAD: App::OperatorExpression Class Reference
App::OperatorExpression Class Reference
#include <ExpressionParser.h>
Public Types
enum Operator {
NONE, ADD, SUB, MUL,
DIV, MOD, POW, EQ,
NEQ, LT, GT, LTE,
GTE, UNIT, NEG, POS
}
Public Types inherited from App::Expression
enum DepOption { DepNormal, DepHidden, DepAll }
using ComponentList = std::vector< Component * >
Public Member Functions
OperatorExpression (const App::DocumentObject *_owner=nullptr, Expression *_left=nullptr, Operator _op=NONE, Expression *_right=nullptr)
~OperatorExpression () override
bool isTouched () const override
Expression * simplify () const override
int priority () const override
Operator getOperator () const
Expression * getLeft () const
Expression * getRight () const
Public Member Functions inherited from App::UnitExpression
UnitExpression (const App::DocumentObject *_owner=nullptr, const Base::Quantity &_quantity=Base::Quantity(), const std::string &_unitStr=std::string())
~UnitExpression () override
void setUnit (const Base::Quantity &_quantity)
void setQuantity (const Base::Quantity &_quantity)
double getValue () const
const Base::Unit & getUnit () const
const Base::Quantity & getQuantity () const
const std::string getUnitString () const
double getScaler () const
Public Member Functions inherited from App::Expression
Expression (const App::DocumentObject *_owner)
~Expression () override
Expression * eval () const
std::string toString (bool persistent=false, bool checkPriority=false, int indent=0) const
void toString (std::ostream &os, bool persistent=false, bool checkPriority=false, int indent=0) const
Expression * copy () const
void getIdentifiers (std::map< App::ObjectIdentifier, bool > &) const
std::map< App::ObjectIdentifier, bool > getIdentifiers () const
void getDeps (ExpressionDeps &deps, int option=DepNormal) const
ExpressionDeps getDeps (int option=DepNormal) const
std::map< App::DocumentObject *, bool > getDepObjects (std::vector< std::string > *labels=nullptr) const
void getDepObjects (std::map< App::DocumentObject *, bool > &, std::vector< std::string > *labels=nullptr) const
ExpressionPtr importSubNames (const std::map< std::string, std::string > &nameMap) const
ExpressionPtr updateLabelReference (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const
ExpressionPtr replaceObject (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const
bool adjustLinks (const std::set< App::DocumentObject * > &inList)
void visit (ExpressionVisitor &v)
App::DocumentObject * getOwner () const
virtual void addComponent (Component *component)
bool hasComponent () const
boost::any getValueAsAny () const
Py::Object getPyValue () const
bool isSame (const Expression &other, bool checkComment=true) const
Component (const std::string &n)
Component (Expression *e1, Expression *e2, Expression *e3, bool isRange=false)
Component (const ObjectIdentifier::Component &comp)
Component (const Component &other)
~Component ()
Component & operator= (const Component &)=delete
void visit (ExpressionVisitor &v)
bool isTouched () const
void toString (std::ostream &ss, bool persistent) const
Component * copy () const
Component * eval () const
Py::Object get (const Expression *owner, const Py::Object &pyobj) const
void set (const Expression *owner, Py::Object &pyobj, const Py::Object &value) const
void del (const Expression *owner, Py::Object &pyobj) const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
Expression * _copy () const override
Py::Object _getPyValue () const override
void _toString (std::ostream &ss, bool persistent, int indent) const override
void _visit (ExpressionVisitor &v) override
virtual bool isCommutative () const
virtual bool isLeftAssociative () const
virtual bool isRightAssociative () const
Protected Member Functions inherited from App::Expression
virtual bool _isIndexable () const
virtual void _getIdentifiers (std::map< App::ObjectIdentifier, bool > &) const
virtual bool _adjustLinks (const std::set< App::DocumentObject * > &, ExpressionVisitor &)
virtual bool _updateElementReference (App::DocumentObject *, bool, ExpressionVisitor &)
virtual bool _relabeledDocument (const std::string &, const std::string &, ExpressionVisitor &)
virtual void _importSubNames (const ObjectIdentifier::SubNameMap &)
virtual void _updateLabelReference (App::DocumentObject *, const std::string &, const char *)
virtual bool _renameObjectIdentifier (const std::map< ObjectIdentifier, ObjectIdentifier > &, const ObjectIdentifier &, ExpressionVisitor &)
virtual void _collectReplacement (std::map< ObjectIdentifier, ObjectIdentifier > &, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const
virtual void _moveCells (const CellAddress &, int, int, ExpressionVisitor &)
virtual void _offsetCells (int, int, ExpressionVisitor &)
Protected Attributes
Operator op
Expression * left
Expression * right
Protected Attributes inherited from App::UnitExpression
PyObject * cache = nullptr
Protected Attributes inherited from App::Expression
App::DocumentObject * owner
ComponentList components
Additional Inherited Members
Static Public Member Functions inherited from App::Expression
static Expression * parse (const App::DocumentObject *owner, const std::string &buffer)
static Component * createComponent (const std::string &n)
static Component * createComponent (Expression *e1, Expression *e2=nullptr, Expression *e3=nullptr, bool isRange=false)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::Expression
std::string comment
ObjectIdentifier::Component comp
Expression * e1
Expression * e2
Expression * e3
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Class implementing an infix expression.
Definition at line 204 of file ExpressionParser.h.
Member Enumeration Documentation
Operator
enum App::OperatorExpression::Operator
Enumerator
NONE
ADD
SUB
MUL
DIV
MOD
POW
EQ
NEQ
LT
GT
LTE
GTE
UNIT
NEG
POS
Definition at line 209 of file ExpressionParser.h.
Constructor & Destructor Documentation
OperatorExpression()
OperatorExpression::OperatorExpression (const App::DocumentObject * _owner = nullptr, Expression * _left = nullptr, Operator _op = NONE, Expression * _right = nullptr) explicit
Definition at line 1343 of file Expression.cpp.
Referenced by _copy(), and simplify().
~OperatorExpression()
OperatorExpression::~OperatorExpression () override
Definition at line 1352 of file Expression.cpp.
References left, and right.
Member Function Documentation
_copy()
Expression * OperatorExpression::_copy () const override protected virtual
A deep copy of the expression.
Reimplemented from App::UnitExpression.
Definition at line 1617 of file Expression.cpp.
References App::Expression::copy(), left, op, OperatorExpression(), App::Expression::owner, and right.
_getPyValue()
Py::Object OperatorExpression::_getPyValue () const override protected virtual
Reimplemented from App::UnitExpression.
Definition at line 1479 of file Expression.cpp.
References calc(), left, op, and right.
_toString()
void OperatorExpression::_toString (std::ostream & s, bool persistent, int indent) const override protected virtual
Create a string representation of the expression.
Returns
A string representing the expression.
Reimplemented from App::UnitExpression.
Definition at line 1512 of file Expression.cpp.
References ADD, DIV, EQ, GT, GTE, isCommutative(), isLeftAssociative(), isRightAssociative(), left, LT, LTE, MOD, MUL, NEG, NEQ, NONE, op, POS, POW, App::Expression::priority(), priority(), right, toolbit-attributes::s, SUB, App::Expression::toString(), and UNIT.
_visit()
void OperatorExpression::_visit (ExpressionVisitor & v) override protected virtual
Reimplemented from App::Expression.
Definition at line 1658 of file Expression.cpp.
References left, right, TestSpreadsheet::v, and App::Expression::visit().
getLeft()
Expression* App::OperatorExpression::getLeft () const inline
Definition at line 246 of file ExpressionParser.h.
Referenced by App::ExpressionParser::parseUnit().
getOperator()
Operator App::OperatorExpression::getOperator () const inline
Definition at line 241 of file ExpressionParser.h.
Referenced by App::ExpressionParser::parseUnit().
getRight()
Expression* App::OperatorExpression::getRight () const inline
Definition at line 251 of file ExpressionParser.h.
Referenced by App::ExpressionParser::parseUnit().
isCommutative()
bool OperatorExpression::isCommutative () const protected virtual
Definition at line 1666 of file Expression.cpp.
References ADD, EQ, MUL, NEQ, and op.
Referenced by _toString().
isLeftAssociative()
bool OperatorExpression::isLeftAssociative () const protected virtual
Definition at line 1679 of file Expression.cpp.
Referenced by _toString().
isRightAssociative()
bool OperatorExpression::isRightAssociative () const protected virtual
Definition at line 1684 of file Expression.cpp.
References ADD, MUL, and op.
Referenced by _toString().
isTouched()
bool OperatorExpression::isTouched () const override virtual
Determine whether the expression is touched or not, i.e relies on properties that are touched.
Reimplemented from App::Expression.
Definition at line 1362 of file Expression.cpp.
References App::Expression::isTouched(), left, and right.
priority()
int OperatorExpression::priority () const override virtual
Return the operators priority. This is used to add parentheses where needed when creating a string representation of the expression.
Returns
The operator's priority.
Reimplemented from App::Expression.
Definition at line 1629 of file Expression.cpp.
References ADD, DIV, EQ, GT, GTE, LT, LTE, MOD, MUL, NEG, NEQ, op, POS, POW, SUB, and UNIT.
Referenced by _toString().
simplify()
Expression * OperatorExpression::simplify () const override virtual
Simplify the expression. For OperatorExpressions, we return a NumberExpression if both the left and right side can be simplified to NumberExpressions. In this case we can calculate the final value of the expression.
Returns
Simplified expression.
Reimplemented from App::UnitExpression.
Definition at line 1491 of file Expression.cpp.
References App::Expression::eval(), left, op, OperatorExpression(), App::Expression::owner, right, App::Expression::simplify(), and draftgeoutils.general::v1().
Member Data Documentation
left
Expression* App::OperatorExpression::left protected
Left operand
Definition at line 272 of file ExpressionParser.h.
Referenced by _copy(), _getPyValue(), _toString(), _visit(), isTouched(), simplify(), and ~OperatorExpression().
op
Operator App::OperatorExpression::op protected
Operator working on left and right
Definition at line 271 of file ExpressionParser.h.
Referenced by _copy(), _getPyValue(), _toString(), isCommutative(), isRightAssociative(), priority(), and simplify().
right
Expression* App::OperatorExpression::right protected
Right operand
Definition at line 273 of file ExpressionParser.h.
Referenced by _copy(), _getPyValue(), _toString(), _visit(), isTouched(), simplify(), and ~OperatorExpression().
The documentation for this class was generated from the following files:
ExpressionParser.h
Expression.cpp