FreeCAD: Gui::OverlaySizeGrip Class Reference
Gui::OverlaySizeGrip Class Reference
Size grip for title bar and split handler of OverlayTabWidget.
#include <OverlayWidgets.h>
Signals
void dragMove (const QPoint &globalPos)
Public Member Functions
OverlaySizeGrip (QWidget *parent, bool vertical)
Protected Member Functions
void paintEvent (QPaintEvent *ev) override
void mouseMoveEvent (QMouseEvent *ev) override
void mousePressEvent (QMouseEvent *ev) override
void mouseReleaseEvent (QMouseEvent *ev) override
const QPixmap & pixmap () const
Detailed Description
Size grip for title bar and split handler of OverlayTabWidget.
Definition at line 448 of file OverlayWidgets.h.
Constructor & Destructor Documentation
OverlaySizeGrip()
OverlaySizeGrip::OverlaySizeGrip (QWidget * parent, bool vertical)
Definition at line 2213 of file OverlayWidgets.cpp.
References widgetMinSize().
Member Function Documentation
dragMove
void Gui::OverlaySizeGrip::dragMove (const QPoint & globalPos) signal
Referenced by mouseMoveEvent(), and Gui::OverlayTabWidget::prepareTitleWidget().
mouseMoveEvent()
void OverlaySizeGrip::mouseMoveEvent (QMouseEvent * ev) override protected
Definition at line 2239 of file OverlayWidgets.cpp.
References dragMove().
mousePressEvent()
void OverlaySizeGrip::mousePressEvent (QMouseEvent * ev) override protected
Definition at line 2252 of file OverlayWidgets.cpp.
mouseReleaseEvent()
void OverlaySizeGrip::mouseReleaseEvent (QMouseEvent * ev) override protected
Definition at line 2256 of file OverlayWidgets.cpp.
paintEvent()
void OverlaySizeGrip::paintEvent (QPaintEvent * ev) override protected
Definition at line 2229 of file OverlayWidgets.cpp.
pixmap()
const QPixmap& Gui::OverlaySizeGrip::pixmap () const protected
The documentation for this class was generated from the following files:
OverlayWidgets.h
OverlayWidgets.cpp