FreeCAD: FemGui::BoxWidget Class Reference
FemGui::BoxWidget Class Reference
#include <ViewProviderFemPostFunction.h>
Public Member Functions
BoxWidget ()
~BoxWidget () override
void applyPythonCode () override
void onChange (const App::Property &p) override
void setViewProvider (ViewProviderFemPostFunction *view) override
Public Member Functions inherited from FemGui::FunctionWidget
FunctionWidget ()=default
~FunctionWidget () override=default
void onObjectsChanged (const App::DocumentObject &obj, const App::Property &)
Additional Inherited Members
Protected Member Functions inherited from FemGui::FunctionWidget
ViewProviderFemPostFunction * getView ()
Fem::FemPostFunction * getObject () const
template<class T >
T * getObject () const
bool blockObjectUpdates ()
void setBlockObjectUpdates (bool val)
Detailed Description
Definition at line 195 of file ViewProviderFemPostFunction.h.
Constructor & Destructor Documentation
BoxWidget()
BoxWidget::BoxWidget ()
Definition at line 449 of file ViewProviderFemPostFunction.cpp.
References draftgeoutils.intersections::connect(), Base::UnitsApi::getDecimals(), and Gui::QuantitySpinBox::valueChanged().
~BoxWidget()
BoxWidget::~BoxWidget () override default
Member Function Documentation
applyPythonCode()
void BoxWidget::applyPythonCode () override virtual
Implements FemGui::FunctionWidget.
Definition at line 498 of file ViewProviderFemPostFunction.cpp.
onChange()
void BoxWidget::onChange (const App::Property & p) override virtual
Implements FemGui::FunctionWidget.
Definition at line 523 of file ViewProviderFemPostFunction.cpp.
References Fem::FemPostBoxFunction::Center, getValue(), Fem::FemPostBoxFunction::Height, RobotExample::l, Fem::FemPostBoxFunction::Length, buildPsets::p, FemGui::FunctionWidget::setBlockObjectUpdates(), SurfaceTests.TestBlendCurve::vec, src.Mod.PartDesign.fcgear.svggear::w, and Fem::FemPostBoxFunction::Width.
Referenced by setViewProvider().
setViewProvider()
void BoxWidget::setViewProvider (ViewProviderFemPostFunction * view) override virtual
Reimplemented from FemGui::FunctionWidget.
Definition at line 501 of file ViewProviderFemPostFunction.cpp.
References Fem::FemPostBoxFunction::Center, App::PropertyQuantity::getUnit(), App::PropertyVectorDistance::getUnit(), Fem::FemPostBoxFunction::Height, Fem::FemPostBoxFunction::Length, onChange(), FemGui::FunctionWidget::setBlockObjectUpdates(), FemGui::FunctionWidget::setViewProvider(), unit(), and Fem::FemPostBoxFunction::Width.
The documentation for this class was generated from the following files:
ViewProviderFemPostFunction.h
ViewProviderFemPostFunction.cpp