FreeCAD: SketcherGui::StateMachine< SelectModeT > Class Template Reference
SketcherGui::StateMachine< SelectModeT > Class Template Reference
A state machine to encapsulate a state.
#include <DrawSketchDefaultHandler.h>
Public Member Functions
StateMachine ()
virtual ~StateMachine ()
Protected Member Functions
void setState (SelectModeT mode)
void ensureState (SelectModeT mode)
void ensureStateIfEarlier (SelectModeT mode)
SelectModeT state () const
bool isState (SelectModeT state) const
bool isFirstState () const
bool isLastState () const
constexpr SelectModeT getFirstState () const
SelectModeT getNextMode () const
void moveToNextMode ()
void reset ()
virtual bool onModeChanged ()
Detailed Description
template<typename SelectModeT>
class SketcherGui::StateMachine< SelectModeT >
A state machine to encapsulate a state.
A template class for a state machine defined by template type SelectModeT, automatically initialised to the first state, encapsulating the actual state, and enabling to change the state, while generating a call to onModeChanged() after every change.
the getNextMode() returns the next mode in the state machine, unless it is in End mode, in which End mode is returned.
The goal of this class to sense navigation through the states of the time machine (for example as triggered by one input method) and notifying of changes (for example to another input method to update it appropriately).
NOTE: Some basic state machines are provided. However, it is possible for the user to provide its own customised time machine instead. The state machine provided MUST include a last state named End.
Definition at line 148 of file DrawSketchDefaultHandler.h.
Constructor & Destructor Documentation
StateMachine()
template<typename SelectModeT > SketcherGui::StateMachine< SelectModeT >::StateMachine () inline
Definition at line 151 of file DrawSketchDefaultHandler.h.
~StateMachine()
template<typename SelectModeT > virtual SketcherGui::StateMachine< SelectModeT >::~StateMachine () inline virtual
Definition at line 154 of file DrawSketchDefaultHandler.h.
Member Function Documentation
ensureState()
template<typename SelectModeT > void SketcherGui::StateMachine< SelectModeT >::ensureState (SelectModeT mode) inline protected
Definition at line 164 of file DrawSketchDefaultHandler.h.
ensureStateIfEarlier()
template<typename SelectModeT > void SketcherGui::StateMachine< SelectModeT >::ensureStateIfEarlier (SelectModeT mode) inline protected
Ensure the state machine is the provided mode but only if the mode is an earlier state.
This allows one to return to previous states (e.g. for modification), only if that state has previously been completed.
Definition at line 179 of file DrawSketchDefaultHandler.h.
getFirstState()
template<typename SelectModeT > constexpr SelectModeT SketcherGui::StateMachine< SelectModeT >::getFirstState () const inline constexpr protected
Definition at line 209 of file DrawSketchDefaultHandler.h.
getNextMode()
template<typename SelectModeT > SelectModeT SketcherGui::StateMachine< SelectModeT >::getNextMode () const inline protected
Definition at line 214 of file DrawSketchDefaultHandler.h.
Referenced by SketcherGui::StateMachine< ControllerT::SelectModeType >::getFirstState().
isFirstState()
template<typename SelectModeT > bool SketcherGui::StateMachine< SelectModeT >::isFirstState () const inline protected
Definition at line 199 of file DrawSketchDefaultHandler.h.
isLastState()
template<typename SelectModeT > bool SketcherGui::StateMachine< SelectModeT >::isLastState () const inline protected
Definition at line 204 of file DrawSketchDefaultHandler.h.
Referenced by SketcherGui::DrawSketchDefaultHandler< ControllerT::HandlerType, ControllerT::SelectModeType, ControllerT::AutoConstraintInitialSize, ControllerT::ContructionMethodType >::mouseMove().
isState()
template<typename SelectModeT > bool SketcherGui::StateMachine< SelectModeT >::isState (SelectModeT state) const inline protected
Definition at line 194 of file DrawSketchDefaultHandler.h.
Referenced by SketcherGui::DrawSketchDefaultHandler< ControllerT::HandlerType, ControllerT::SelectModeType, ControllerT::AutoConstraintInitialSize, ControllerT::ContructionMethodType >::pressRightButton().
moveToNextMode()
template<typename SelectModeT > void SketcherGui::StateMachine< SelectModeT >::moveToNextMode () inline protected
Definition at line 228 of file DrawSketchDefaultHandler.h.
onModeChanged()
template<typename SelectModeT > virtual bool SketcherGui::StateMachine< SelectModeT >::onModeChanged () inline protected virtual
Reimplemented in SketcherGui::DrawSketchDefaultHandler< HandlerT, SelectModeT, PInitAutoConstraintSize, ConstructionMethodT >, and SketcherGui::DrawSketchDefaultHandler< ControllerT::HandlerType, ControllerT::SelectModeType, ControllerT::AutoConstraintInitialSize, ControllerT::ContructionMethodType >.
Definition at line 240 of file DrawSketchDefaultHandler.h.
reset()
template<typename SelectModeT > void SketcherGui::StateMachine< SelectModeT >::reset () inline protected
Definition at line 233 of file DrawSketchDefaultHandler.h.
setState()
template<typename SelectModeT > void SketcherGui::StateMachine< SelectModeT >::setState (SelectModeT mode) inline protected
Definition at line 158 of file DrawSketchDefaultHandler.h.
Referenced by SketcherGui::StateMachine< ControllerT::SelectModeType >::getFirstState(), and SketcherGui::StateMachine< ControllerT::SelectModeType >::getNextMode().
state()
template<typename SelectModeT > SelectModeT SketcherGui::StateMachine< SelectModeT >::state () const inline protected
Definition at line 189 of file DrawSketchDefaultHandler.h.
Referenced by SketcherGui::StateMachine< ControllerT::SelectModeType >::isState().
The documentation for this class was generated from the following file:
DrawSketchDefaultHandler.h