FreeCAD: Gui::DAG::Model Class Reference
Gui::DAG::Model Class Reference
#include <DAGModel.h>
Public Member Functions
Model (QObject *parentIn, const Gui::Document &documentIn)
~Model () override
void awake ()
hooked up to event dispatcher for update when idle.
void selectionChanged (const SelectionChanges &msg)
Protected Member Functions
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event) override
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event) override
Detailed Description
Definition at line 63 of file DAGModel.h.
Constructor & Destructor Documentation
Model()
Model::Model (QObject * parentIn, const Gui::Document & documentIn)
Definition at line 96 of file DAGModel.cpp.
References draftgeoutils.faces::bind(), Gui::BitmapFactory(), draftgeoutils.intersections::connect(), App::GetApplication(), Gui::Document::getDocument(), ParameterGrp::GetGroup(), App::Document::getObjects(), App::Application::GetUserParameter(), Gui::Document::getViewProvider(), toolbit-attributes::group, geoff_geometry::Normal(), geoff_geometry::On(), Gui::Document::signalChangedObject, Gui::Document::signalDeletedObject, Gui::Document::signalInEdit, Gui::Document::signalNewObject, and Gui::Document::signalResetEdit.
~Model()
Model::~Model () override
Definition at line 155 of file DAGModel.cpp.
Member Function Documentation
awake()
void Model::awake ()
hooked up to event dispatcher for update when idle.
Definition at line 450 of file DAGModel.cpp.
Referenced by Gui::DAG::View::awakeSlot().
contextMenuEvent()
void Model::contextMenuEvent (QGraphicsSceneContextMenuEvent * event) override protected
Definition at line 1057 of file DAGModel.cpp.
References Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::clearSelection(), Gui::DAG::GraphLinkRecord::DObject, Gui::DAG::findRecord(), App::DocumentObject::getDocument(), Gui::MenuManager::getInstance(), App::Document::getName(), App::DocumentObject::getNameInDocument(), Gui::Application::Instance, Gui::DAG::RectItem::isEditing(), Gui::DAG::RectItem::isSelected(), Gui::Selection(), Gui::MenuManager::setupContextMenu(), Gui::Application::setupContextMenu(), Gui::DAG::GraphLinkRecord::vertex, and Gui::DAG::GraphLinkRecord::VPDObject.
mouseDoubleClickEvent()
void Model::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 1025 of file DAGModel.cpp.
References Gui::DAG::GraphLinkRecord::DObject, toolbit-attributes::doc, Gui::DAG::findRecord(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::getMainWindow(), Gui::Application::Instance, Gui::MainWindow::setActiveWindow(), and Gui::DAG::GraphLinkRecord::VPDObject.
mouseMoveEvent()
void Model::mouseMoveEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 906 of file DAGModel.cpp.
References Gui::DAG::RectItem::preHighlightOff(), and Gui::DAG::RectItem::preHighlightOn().
mousePressEvent()
void Model::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 935 of file DAGModel.cpp.
References Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::clearSelection(), Gui::DAG::GraphLinkRecord::DObject, Gui::DAG::findRecord(), App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), ArchFence::hide(), Gui::DAG::Off, Gui::SelectionSingleton::rmvSelection(), Path.Dressup.Utils::selection(), Gui::Selection(), Gui::ViewProviderDocumentObject::show(), Gui::DAG::GraphLinkRecord::vertex, and Gui::DAG::GraphLinkRecord::VPDObject.
selectionChanged()
void Model::selectionChanged (const SelectionChanges & msg)
Definition at line 343 of file DAGModel.cpp.
References Gui::SelectionChanges::AddSelection, Gui::SelectionChanges::ClrSelection, Gui::DAG::findRecord(), Gui::SelectionSingleton::getSelection(), Path.Op.Surface::msg, Gui::SelectionChanges::RmvSelection, Path.Dressup.Utils::selection(), Gui::Selection(), Gui::DAG::RectItem::selectionOff(), Gui::DAG::RectItem::selectionOn(), Gui::SelectionChanges::SetSelection, and Gui::DAG::GraphLinkRecord::vertex.
Referenced by Path.Op.Gui.FeatureExtension.TaskPanelExtensionPage::toggleExtensionCorners().
The documentation for this class was generated from the following files:
DAGModel.h
DAGModel.cpp