FreeCAD: App::PropertyData::OffsetBase Struct Reference
App::PropertyData::OffsetBase Struct Reference
#include <PropertyContainer.h>
Public Member Functions
OffsetBase (const App::PropertyContainer *container)
OffsetBase (const App::Extension *container)
short int getOffsetTo (const App::Property *prop) const
char * getOffset () const
Detailed Description
Definition at line 76 of file PropertyContainer.h.
Constructor & Destructor Documentation
OffsetBase() [1/2]
App::PropertyData::OffsetBase::OffsetBase (const App::PropertyContainer * container) inline
Definition at line 78 of file PropertyContainer.h.
OffsetBase() [2/2]
App::PropertyData::OffsetBase::OffsetBase (const App::Extension * container) inline
Definition at line 79 of file PropertyContainer.h.
Member Function Documentation
getOffset()
char* App::PropertyData::OffsetBase::getOffset () const inline
Definition at line 88 of file PropertyContainer.h.
Referenced by App::PropertyData::getPropertyByName(), App::PropertyData::getPropertyList(), App::PropertyData::getPropertyMap(), and App::PropertyData::getPropertyNamedList().
getOffsetTo()
short int App::PropertyData::OffsetBase::getOffsetTo (const App::Property * prop) const inline
Definition at line 81 of file PropertyContainer.h.
References importers.importWebGL::base.
Referenced by App::PropertyData::addProperty(), and App::PropertyData::findProperty().
The documentation for this struct was generated from the following file:
PropertyContainer.h