FreeCAD: Gui::ExpressionBindingPy Class Reference
Gui::ExpressionBindingPy Class Reference
#include <ExpressionBindingPy.h>
Public Member Functions
ExpressionBindingPy (Py::PythonClassInstance *self, Py::Tuple &args, Py::Dict &kwds)
~ExpressionBindingPy () override
Py::Object repr () override
Py::Object bind (const Py::Tuple &)
Py::Object isBound ()
Py::Object apply (const Py::Tuple &)
Py::Object hasExpression ()
Py::Object autoApply ()
Py::Object setAutoApply (const Py::Tuple &)
Static Public Member Functions
static void init_type ()
Detailed Description
Definition at line 32 of file ExpressionBindingPy.h.
Constructor & Destructor Documentation
ExpressionBindingPy()
ExpressionBindingPy::ExpressionBindingPy (Py::PythonClassInstance * self, Py::Tuple & args, Py::Dict & kwds)
Definition at line 35 of file ExpressionBindingPy.cpp.
References toolbit-attributes::args, Gui::PythonWrapper::loadWidgetsModule(), and Gui::PythonWrapper::toQObject().
~ExpressionBindingPy()
ExpressionBindingPy::~ExpressionBindingPy () override default
Member Function Documentation
apply()
Py::Object ExpressionBindingPy::apply (const Py::Tuple & args)
Definition at line 139 of file ExpressionBindingPy.cpp.
References Gui::ExpressionBinding::apply(), toolbit-attributes::args, and Path.Post.scripts.refactored_centroid_post::str.
autoApply()
Py::Object ExpressionBindingPy::autoApply ()
Definition at line 156 of file ExpressionBindingPy.cpp.
References Gui::ExpressionBinding::autoApply().
bind()
Py::Object ExpressionBindingPy::bind (const Py::Tuple & args)
Definition at line 105 of file ExpressionBindingPy.cpp.
References toolbit-attributes::args, Gui::ExpressionBinding::bind(), SCL.SimpleDataTypes::e, getProperty(), SplineSurface::id, App::ObjectIdentifier::parse(), and Path.Post.scripts.refactored_centroid_post::str.
hasExpression()
Py::Object ExpressionBindingPy::hasExpression ()
Definition at line 150 of file ExpressionBindingPy.cpp.
References Gui::ExpressionBinding::hasExpression().
init_type()
void ExpressionBindingPy::init_type () static
Definition at line 175 of file ExpressionBindingPy.cpp.
References draftgeoutils.faces::bind().
Referenced by Gui::Application::Application().
isBound()
Py::Object ExpressionBindingPy::isBound ()
Definition at line 133 of file ExpressionBindingPy.cpp.
References Gui::ExpressionBinding::isBound().
repr()
Py::Object ExpressionBindingPy::repr () override
Definition at line 98 of file ExpressionBindingPy.cpp.
References toolbit-attributes::s, and src.Mod.Test.testmakeWireString::String.
setAutoApply()
Py::Object ExpressionBindingPy::setAutoApply (const Py::Tuple & args)
Definition at line 162 of file ExpressionBindingPy.cpp.
References toolbit-attributes::args, Base::asBoolean(), SCL.SimpleDataTypes::b, and Gui::ExpressionBinding::setAutoApply().
The documentation for this class was generated from the following files:
ExpressionBindingPy.h
ExpressionBindingPy.cpp