FreeCAD: Gui::ToolBarManager Class Reference
Gui::ToolBarManager Class Reference
#include <ToolBarManager.h>
Public Types
enum State { State::ForceHidden, State::ForceAvailable, State::RestoreDefault, State::SaveState }
Public Member Functions
void setup (ToolBarItem *)
void saveState () const
void restoreState () const
void retranslate () const
bool areToolBarsLocked () const
void setToolBarsLocked (bool locked) const
void setState (const QList< QString > &names, State state)
void setState (const QString &name, State state)
int toolBarIconSize (QWidget *widget=nullptr) const
void setupToolBarIconSize ()
ToolBarArea toolBarArea (QWidget *toolBar) const
ToolBarAreaWidget * toolBarAreaWidget (QWidget *toolBar) const
Static Public Member Functions
static ToolBarManager * getInstance ()
The one and only instance.
static void destruct ()
Protected Member Functions
void setup (ToolBarItem *, QToolBar *) const
void setMovable (bool movable) const
ToolBarItem::DefaultVisibility getToolbarPolicy (const QToolBar *) const
bool addToolBarToArea (QObject *source, QMouseEvent *ev)
bool showContextMenu (QObject *source)
void onToggleStatusBarWidget (QWidget *widget, bool visible)
void setToolBarIconSize (QToolBar *toolbar)
void onTimer ()
bool eventFilter (QObject *source, QEvent *ev) override
QList< ToolBar * > toolBars () const
ToolBar * findToolBar (const QList< ToolBar * > &, const QString &) const
QAction * findAction (const QList< QAction * > &, const QString &) const
ToolBarManager ()
~ToolBarManager () override
Detailed Description
The ToolBarManager class is responsible for the creation of toolbars and appending them to the main window.
See also
ToolBoxManager
MenuManager
Author
Werner Mayer
Definition at line 146 of file ToolBarManager.h.
Member Enumeration Documentation
State
enum Gui::ToolBarManager::State strong
Enumerator
ForceHidden
ForceAvailable
RestoreDefault
SaveState
Definition at line 151 of file ToolBarManager.h.
Constructor & Destructor Documentation
ToolBarManager()
ToolBarManager::ToolBarManager () protected
Definition at line 403 of file ToolBarManager.cpp.
Referenced by getInstance().
~ToolBarManager()
ToolBarManager::~ToolBarManager () override protected default
Member Function Documentation
addToolBarToArea()
bool ToolBarManager::addToolBarToArea (QObject * source, QMouseEvent * ev) protected
Definition at line 900 of file ToolBarManager.cpp.
References SCL.SimpleDataTypes::c, Gui::ToolBarAreaWidget::count(), Gui::getMainWindow(), Sketcher::Horizontal, Gui::ToolBarAreaWidget::insertWidget(), buildPsets::p, RobotExample::pos, Gui::ToolBarAreaWidget::removeWidget(), NavigationIndicatorGui::statusBar, and Gui::ToolBarAreaWidget::widgetAt().
Referenced by eventFilter().
areToolBarsLocked()
bool Gui::ToolBarManager::areToolBarsLocked () const
Definition at line 1183 of file ToolBarManager.cpp.
Referenced by restoreState(), and setup().
destruct()
void ToolBarManager::destruct () static
Definition at line 397 of file ToolBarManager.cpp.
Referenced by Gui::WorkbenchManager::~WorkbenchManager().
eventFilter()
bool ToolBarManager::eventFilter (QObject * source, QEvent * ev) override protected
Definition at line 1137 of file ToolBarManager.cpp.
References addToolBarToArea(), Init::parent, and showContextMenu().
findAction()
QAction * ToolBarManager::findAction (const QList< QAction * > & acts, const QString & item) const protected
Definition at line 1214 of file ToolBarManager.cpp.
Referenced by setup().
findToolBar()
ToolBar * ToolBarManager::findToolBar (const QList< ToolBar * > & toolbars, const QString & item) const protected
Definition at line 1203 of file ToolBarManager.cpp.
Referenced by restoreState(), saveState(), setState(), and setup().
getInstance()
ToolBarManager * ToolBarManager::getInstance () static
The one and only instance.
Definition at line 389 of file ToolBarManager.cpp.
References ToolBarManager().
Referenced by Gui::Workbench::activate(), SketcherGui::Workbench::activated(), StdCmdToggleToolBarLock::activated(), Gui::PreferencePackManager::apply(), copyTemplateParameters(), StdCmdToggleToolBarLock::createAction(), SketcherGui::Workbench::enterEditMode(), SketcherGui::Workbench::leaveEditMode(), Gui::MainWindow::loadWindowSettings(), Gui::ToolBarGrip::mouseMoveEvent(), Gui::Workbench::retranslate(), Gui::MainWindow::saveWindowSettings(), Gui::ToolBar::undock(), Gui::ToolBar::updateCustomGripVisibility(), and Gui::WorkbenchTabWidget::updateLayout().
getToolbarPolicy()
ToolBarItem::DefaultVisibility ToolBarManager::getToolbarPolicy (const QToolBar * toolbar) const protected
Definition at line 1247 of file ToolBarManager.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and Gui::ToolBarItem::Visible.
Referenced by restoreState(), and setState().
onTimer()
void ToolBarManager::onTimer () protected
Definition at line 818 of file ToolBarManager.cpp.
References restoreState().
onToggleStatusBarWidget()
void ToolBarManager::onToggleStatusBarWidget (QWidget * widget, bool visible) protected
Definition at line 1130 of file ToolBarManager.cpp.
References ParameterGrp::SetBool().
restoreState()
void ToolBarManager::restoreState () const
Definition at line 858 of file ToolBarManager.cpp.
References areToolBarsLocked(), findToolBar(), ParameterGrp::GetBool(), ParameterGrp::GetInt(), Gui::getMainWindow(), getToolbarPolicy(), Gui::ToolBarAreaWidget::restoreState(), setMovable(), toolBars(), and Gui::ToolBarItem::Unavailable.
Referenced by Gui::PreferencePackManager::apply(), Gui::MainWindow::loadWindowSettings(), and onTimer().
retranslate()
void ToolBarManager::retranslate () const
Definition at line 1174 of file ToolBarManager.cpp.
References toolBars(), and src.Mod.AddonManager.Addon::translate.
Referenced by Gui::Workbench::retranslate().
saveState()
void ToolBarManager::saveState () const
Definition at line 823 of file ToolBarManager.cpp.
References Path.Post.scripts.dynapath_4060_post::action, findToolBar(), ParameterGrp::SetBool(), toolBars(), and Gui::ToolBarItem::Unavailable.
Referenced by copyTemplateParameters(), Gui::MainWindow::saveWindowSettings(), and setup().
setMovable()
void Gui::ToolBarManager::setMovable (bool movable) const protected
Definition at line 1195 of file ToolBarManager.cpp.
Referenced by restoreState(), and setup().
setState() [1/2]
void ToolBarManager::setState (const QList< QString > & names, State state)
Definition at line 1259 of file ToolBarManager.cpp.
References femtools.tokrules::names.
Referenced by SketcherGui::Workbench::activated(), SketcherGui::Workbench::enterEditMode(), and SketcherGui::Workbench::leaveEditMode().
setState() [2/2]
void ToolBarManager::setState (const QString & name, State state)
Definition at line 1266 of file ToolBarManager.cpp.
References findToolBar(), ForceAvailable, ForceHidden, ParameterGrp::GetBool(), getToolbarPolicy(), RestoreDefault, SaveState, ParameterGrp::SetBool(), bimcommands.BimViews::show(), toolBars(), Gui::ToolBarItem::Unavailable, and Gui::ToolBarItem::Visible.
setToolBarIconSize()
void ToolBarManager::setToolBarIconSize (QToolBar * toolbar) protected
Definition at line 641 of file ToolBarManager.cpp.
References Gui::ToolBarAreaWidget::adjustParent(), toolbit-attributes::s, and toolBarIconSize().
Referenced by setupToolBarIconSize().
setToolBarsLocked()
void Gui::ToolBarManager::setToolBarsLocked (bool locked) const
Definition at line 1188 of file ToolBarManager.cpp.
setup() [1/2]
void ToolBarManager::setup (ToolBarItem * toolBarItems)
Sets up the toolbars of a given workbench.
Definition at line 653 of file ToolBarManager.cpp.
References Path.Post.scripts.dynapath_4060_post::action, areToolBarsLocked(), findToolBar(), App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), Gui::ToolBarItem::getItems(), Gui::getMainWindow(), App::Application::GetUserParameter(), src.Mod.Test.testPathArray::items, saveState(), setMovable(), toolBars(), CommandInsertLink::tooltip, src.Mod.AddonManager.Addon::translate, Gui::ToolBarItem::Unavailable, and Gui::ToolBarItem::Visible.
Referenced by Gui::Workbench::activate(), Path.Dressup.Tags.ObjectTagDressup::doExecute(), Path.Dressup.Gui.Dogbone.ObjectDressup::execute(), Path.Dressup.Tags.ObjectTagDressup::generateTags(), Path.Dressup.Tags.ObjectTagDressup::pointAtBottom(), Path.Dressup.Tags.ObjectTagDressup::pointIsOnPath(), Path.Dressup.Tags.ObjectTagDressup::setXyEnabled(), and Path.Dressup.Tags.ObjectTagDressup::supportsTagGeneration().
setup() [2/2]
void ToolBarManager::setup (ToolBarItem * item, QToolBar * toolbar) const protected
Definition at line 779 of file ToolBarManager.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::CommandManager::addTo(), Gui::Application::commandManager(), findAction(), Gui::ToolBarItem::getItems(), Gui::Application::Instance, and src.Mod.Test.testPathArray::items.
Referenced by Path.Dressup.Tags.ObjectTagDressup::doExecute(), Path.Dressup.Gui.Dogbone.ObjectDressup::execute(), Path.Dressup.Tags.ObjectTagDressup::generateTags(), Path.Dressup.Tags.ObjectTagDressup::pointAtBottom(), Path.Dressup.Tags.ObjectTagDressup::pointIsOnPath(), Path.Dressup.Tags.ObjectTagDressup::setXyEnabled(), and Path.Dressup.Tags.ObjectTagDressup::supportsTagGeneration().
setupToolBarIconSize()
void ToolBarManager::setupToolBarIconSize ()
Definition at line 628 of file ToolBarManager.cpp.
References Gui::getMainWindow(), toolbit-attributes::s, setToolBarIconSize(), and toolBarIconSize().
showContextMenu()
bool ToolBarManager::showContextMenu (QObject * source) protected
Definition at line 1031 of file ToolBarManager.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::ToolBarAreaWidget::foreachToolBar(), Gui::getMainWindow(), NavigationIndicatorGui::menu, RobotExample::pos, and NavigationIndicatorGui::statusBar.
Referenced by eventFilter().
toolBarArea()
ToolBarArea ToolBarManager::toolBarArea (QWidget * toolBar) const
Definition at line 536 of file ToolBarManager.cpp.
References Gui::BottomToolBarArea, Gui::getMainWindow(), Gui::LeftToolBarArea, Gui::NoToolBarArea, Gui::RightToolBarArea, toolBarAreaWidget(), and Gui::TopToolBarArea.
Referenced by Gui::WorkbenchTabWidget::updateLayout().
toolBarAreaWidget()
ToolBarAreaWidget * ToolBarManager::toolBarAreaWidget (QWidget * toolBar) const
Definition at line 566 of file ToolBarManager.cpp.
Referenced by Gui::ToolBarGrip::mouseMoveEvent(), toolBarArea(), and Gui::ToolBar::updateCustomGripVisibility().
toolBarIconSize()
int ToolBarManager::toolBarIconSize (QWidget * widget = nullptr) const
Definition at line 603 of file ToolBarManager.cpp.
References KDL::max(), and toolbit-attributes::s.
Referenced by setToolBarIconSize(), and setupToolBarIconSize().
toolBars()
QList< ToolBar * > ToolBarManager::toolBars () const protected
Returns a list of all currently existing toolbars.
Definition at line 1225 of file ToolBarManager.cpp.
References Gui::getMainWindow(), NavigationIndicatorGui::mw, and Init::parent.
Referenced by restoreState(), retranslate(), saveState(), setState(), and setup().
The documentation for this class was generated from the following files:
ToolBarManager.h
ToolBarManager.cpp