FreeCAD: MeshCore::MeshFacet Class Reference
MeshCore::MeshFacet Class Reference
#include <Elements.h>
Public Types
enum TFlagType {
INVALID = 1, VISIT = 2, SEGMENT = 4, MARKED = 8,
SELECTED = 16, REV = 32, TMP0 = 64, TMP1 = 128
}
Public Member Functions
Construction
MeshFacet ()
MeshFacet (const MeshFacet &rclF)=default
MeshFacet (MeshFacet &&rclF)=default
MeshFacet (PointIndex p1, PointIndex p2, PointIndex p3, FacetIndex n1=FACET_INDEX_MAX, FacetIndex n2=FACET_INDEX_MAX, FacetIndex n3=FACET_INDEX_MAX)
~MeshFacet ()=default
Flag state
Note
All flag methods are const as they do NOT change the actual behaviour of the object
unsigned char _ucFlag
unsigned long _ulProp
PointIndex _aulPoints [3]
FacetIndex _aulNeighbours [3]
void SetFlag (TFlagType tF) const
void ResetFlag (TFlagType tF) const
bool IsFlag (TFlagType tF) const
void ResetInvalid () const
void SetProperty (unsigned long uP) const
void SetInvalid () const
bool IsValid () const
MeshFacet & operator= (const MeshFacet &rclF)=default
MeshFacet & operator= (MeshFacet &&rclF)=default
void SetVertices (PointIndex, PointIndex, PointIndex)
void SetNeighbours (FacetIndex, FacetIndex, FacetIndex)
void GetEdge (unsigned short usSide, MeshHelpEdge &rclEdge) const
std::pair< PointIndex, PointIndex > GetEdge (unsigned short usSide) const
unsigned short Side (FacetIndex ulNIndex) const
unsigned short Side (PointIndex ulP0, PointIndex P1) const
unsigned short Side (const MeshFacet &rFace) const
bool IsEqual (const MeshFacet &rcFace) const
void Transpose (PointIndex ulOrig, PointIndex ulNew)
void Decrement (PointIndex ulIndex)
bool HasPoint (PointIndex) const
void ReplaceNeighbour (FacetIndex ulOrig, FacetIndex ulNew)
bool HasNeighbour (unsigned short usSide) const
bool IsNeighbour (FacetIndex index) const
unsigned short CountOpenEdges () const
bool HasOpenEdge () const
bool HasSameOrientation (const MeshFacet &) const
bool IsDegenerated () const
void FlipNormal ()
Detailed Description
The MeshFacet class represent a triangle facet in the mesh data.structure. A facet indexes three neighbour facets and also three corner points. This class only keeps topologic information but no geometric information at all.
Here are the most important conventions concerning the facet's orientation:
neighbour or edge number of 0 is defined by corner 0 and 1
neighbour or edge number of 1 is defined by corner 1 and 2
neighbour or edge number of 2 is defined by corner 2 and 0
neighbour index is set to FACET_INDEX_MAX if there is no neighbour facet
Note: The status flag SEGMENT mark a facet to be part of certain subset, a segment. This flag must not be set by any algorithm unless it adds or removes facets to a segment.
Note: The status flag SELECTED mark a facet to be selected which is e.g. used in the GUI. This flag must not be set by any algorithm unless it adds or removes facets to the selection.
Definition at line 291 of file Elements.h.
Member Enumeration Documentation
TFlagType
enum MeshCore::MeshFacet::TFlagType
Enumerator
INVALID
VISIT
SEGMENT
MARKED
SELECTED
REV
TMP0
TMP1
Definition at line 294 of file Elements.h.
Constructor & Destructor Documentation
MeshFacet() [1/4]
MeshCore::MeshFacet::MeshFacet () inline
Definition at line 1014 of file Elements.h.
References _aulPoints.
MeshFacet() [2/4]
MeshCore::MeshFacet::MeshFacet (const MeshFacet & rclF) inline default
MeshFacet() [3/4]
MeshCore::MeshFacet::MeshFacet (MeshFacet && rclF) inline default
MeshFacet() [4/4]
MeshCore::MeshFacet::MeshFacet (PointIndex p1, PointIndex p2, PointIndex p3, FacetIndex n1 = FACET_INDEX_MAX, FacetIndex n2 = FACET_INDEX_MAX, FacetIndex n3 = FACET_INDEX_MAX) inline
Definition at line 1022 of file Elements.h.
References _aulNeighbours.
~MeshFacet()
MeshCore::MeshFacet::~MeshFacet () default
Member Function Documentation
CountOpenEdges()
unsigned short MeshCore::MeshFacet::CountOpenEdges () const inline
Counts the number of edges without neighbour.
Definition at line 1112 of file Elements.h.
References _aulPoints, SCL.SimpleDataTypes::f, and SplineSurface::i.
Decrement()
void MeshCore::MeshFacet::Decrement (PointIndex ulIndex) inline
Decrement the index for each corner point that is higher than ulIndex.
Definition at line 1072 of file Elements.h.
FlipNormal()
void MeshCore::MeshFacet::FlipNormal () inline
Flips the orientation of the facet.
Definition at line 439 of file Elements.h.
Referenced by MeshCore::MeshKernel::AdjustNormal(), and MeshCore::MeshAlgorithm::FillupHole().
GetEdge() [1/2]
std::pair< PointIndex, PointIndex > MeshCore::MeshFacet::GetEdge (unsigned short usSide) const inline
Returns the indices of the corner points of the given edge number.
Definition at line 1054 of file Elements.h.
References _aulPoints.
GetEdge() [2/2]
void MeshCore::MeshFacet::GetEdge (unsigned short usSide, MeshHelpEdge & rclEdge) const inline
Returns the indices of the corner points of the given edge number.
Definition at line 1048 of file Elements.h.
Referenced by MeshCore::MeshAlgorithm::GetFacetBorders(), and MeshCore::MeshAlgorithm::GetFacetsBorders().
HasNeighbour()
bool MeshCore::MeshFacet::HasNeighbour (unsigned short usSide) const inline
Checks if the neighbour exists at the given edge-number.
Definition at line 417 of file Elements.h.
HasOpenEdge()
bool MeshCore::MeshFacet::HasOpenEdge () const inline
Returns true if there is an edge without neighbour, otherwise false.
Definition at line 1123 of file Elements.h.
References _aulPoints.
Referenced by MeshCore::MeshEvalPointOnEdge::Evaluate(), and MeshCore::MeshTopoAlgorithm::SnapVertex().
HasPoint()
bool MeshCore::MeshFacet::HasPoint (PointIndex ulIndex) const inline
Checks if the facets references the given point index.
Definition at line 1085 of file Elements.h.
Referenced by MeshCore::MeshTopoAlgorithm::CollapseVertex(), and MeshCore::MeshPointFacetAdjacency::SetFacetNeighbourhood().
HasSameOrientation()
bool MeshCore::MeshFacet::HasSameOrientation (const MeshFacet & f) const inline
Returns true if the two facets have the same orientation, false otherwise Therefore the two facets must be adjacent.
Definition at line 1128 of file Elements.h.
Referenced by MeshCore::MeshOrientationVisitor::Visit(), MeshCore::MeshOrientationCollector::Visit(), and MeshCore::MeshSameOrientationCollector::Visit().
IsDegenerated()
bool MeshCore::MeshFacet::IsDegenerated () const inline
Checks whether the facet is degenerated to a line of point.
Definition at line 1144 of file Elements.h.
Referenced by MeshCore::MeshFixCorruptedFacets::Fixup().
IsEqual()
bool MeshCore::MeshFacet::IsEqual (const MeshFacet & rcFace) const inline
Returns true if this facet shares the same three points as rcFace. The orientation is not of interest in this case.
Definition at line 1216 of file Elements.h.
Referenced by MeshCore::MeshAlgorithm::FillupHole().
IsFlag()
bool MeshCore::MeshFacet::IsFlag (TFlagType tF) const inline
Definition at line 333 of file Elements.h.
Referenced by MeshCore::MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection(), MeshCore::MeshTopoAlgorithm::DelaunayFlip(), MeshGui::MeshSelection::deleteSelectionBorder(), MeshCore::MeshSearchNeighbours::NeighboursFacetFromFacet(), MeshCore::MeshSearchNeighbours::NeighboursFromFacet(), MeshCore::MeshSearchNeighbours::NeighboursFromSampledFacets(), Mesh::MeshObject::splitEdges(), and MeshCore::MeshOrientationCollector::Visit().
IsNeighbour()
bool MeshCore::MeshFacet::IsNeighbour (FacetIndex index) const inline
Checks if the given index is a neighbour facet.
Definition at line 424 of file Elements.h.
IsValid()
bool MeshCore::MeshFacet::IsValid () const inline
Definition at line 354 of file Elements.h.
Referenced by MeshCore::MeshTopoAlgorithm::CollapseEdge(), and MeshCore::MeshTopoAlgorithm::CollapseFacet().
operator=() [1/2]
MeshFacet& MeshCore::MeshFacet::operator= (const MeshFacet & rclF) inline default
operator=() [2/2]
MeshFacet& MeshCore::MeshFacet::operator= (MeshFacet && rclF) inline default
ReplaceNeighbour()
void MeshCore::MeshFacet::ReplaceNeighbour (FacetIndex ulOrig, FacetIndex ulNew) inline
Replaces the index of the neighbour facet that is equal to ulOrig by ulNew. If the facet does not have a neighbourt with this index nothing happens.
Definition at line 1099 of file Elements.h.
Referenced by MeshCore::MeshTopoAlgorithm::CollapseEdge(), and MeshCore::MeshTopoAlgorithm::CollapseVertex().
ResetFlag()
void MeshCore::MeshFacet::ResetFlag (TFlagType tF) const inline
Definition at line 329 of file Elements.h.
ResetInvalid()
void MeshCore::MeshFacet::ResetInvalid () const inline
Definition at line 337 of file Elements.h.
SetFlag()
void MeshCore::MeshFacet::SetFlag (TFlagType tF) const inline
Definition at line 325 of file Elements.h.
Referenced by MeshCore::MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection(), MeshCore::MeshTopoAlgorithm::DelaunayFlip(), MeshCore::MeshSearchNeighbours::NeighboursFacetFromFacet(), MeshCore::MeshSearchNeighbours::NeighboursFromFacet(), MeshCore::MeshSearchNeighbours::NeighboursFromSampledFacets(), Mesh::MeshObject::splitEdges(), and MeshCore::MeshOrientationCollector::Visit().
SetInvalid()
void MeshCore::MeshFacet::SetInvalid () const inline
Marks a facet as invalid. Should be used only temporary from within an algorithm (e.g. deletion of several facets) but must not be set permanently. From outside the data-structure must not have invalid facets.
Definition at line 350 of file Elements.h.
Referenced by MeshCore::MeshTopoAlgorithm::CollapseEdge(), MeshCore::MeshTopoAlgorithm::CollapseFacet(), MeshCore::MeshTopoAlgorithm::CollapseVertex(), and MeshCore::MeshKernel::DeleteFacets().
SetNeighbours()
void MeshCore::MeshFacet::SetNeighbours (FacetIndex n1, FacetIndex n2, FacetIndex n3) inline
Definition at line 1041 of file Elements.h.
References _aulPoints.
SetProperty()
void MeshCore::MeshFacet::SetProperty (unsigned long uP) const inline
Definition at line 341 of file Elements.h.
Referenced by MeshCore::ReaderOBJ::Load(), and MeshCore::MeshInput::LoadSMF().
SetVertices()
void MeshCore::MeshFacet::SetVertices (PointIndex p1, PointIndex p2, PointIndex p3) inline
Definition at line 1034 of file Elements.h.
References _aulPoints.
Referenced by MeshCore::ReaderOBJ::Load(), MeshCore::MeshInput::LoadOFF(), and MeshCore::MeshInput::LoadSMF().
Side() [1/3]
unsigned short MeshCore::MeshFacet::Side (const MeshFacet & rFace) const inline
Returns the edge-number defined by the shared edge of both facets. If the facets don't share a common edge USHRT_MAX is returned.
Definition at line 1203 of file Elements.h.
Side() [2/3]
unsigned short MeshCore::MeshFacet::Side (FacetIndex ulNIndex) const inline
Returns the edge-number to the given index of neighbour facet. If ulNIndex is not a neighbour USHRT_MAX is returned.
Definition at line 1158 of file Elements.h.
Referenced by MeshCore::MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection(), MeshCore::MeshTopoAlgorithm::CollapseEdge(), MeshCore::MeshTopoAlgorithm::CollapseFacet(), MeshCore::MeshTopoAlgorithm::DelaunayFlip(), MeshCore::MeshEvalNeighbourhood::Evaluate(), MeshCore::MeshAlgorithm::FillupHole(), MeshCore::MeshEvalNeighbourhood::GetIndices(), MeshCore::MeshTopoAlgorithm::IsSwapEdgeLegal(), MeshCore::MeshTopoAlgorithm::OptimizeTopology(), MeshCore::MeshKernel::RebuildNeighbours(), MeshCore::MeshTopoAlgorithm::RemoveDegeneratedFacet(), MeshCore::MeshTopoAlgorithm::ShouldSwapEdge(), MeshCore::MeshTopoAlgorithm::SplitEdge(), MeshCore::MeshTopoAlgorithm::SwapEdge(), and MeshCore::QuasiDelaunayTriangulator::Triangulate().
Side() [3/3]
unsigned short MeshCore::MeshFacet::Side (PointIndex ulP0, PointIndex P1) const inline
Returns the edge-number defined by two points. If one point is not a corner point USHRT_MAX is returned.
Definition at line 1173 of file Elements.h.
Transpose()
void MeshCore::MeshFacet::Transpose (PointIndex ulOrig, PointIndex ulNew) inline
Replaces the index of the corner point that is equal to ulOrig by ulNew. If the facet does not have a corner point with this index nothing happens.
Definition at line 1059 of file Elements.h.
Referenced by MeshCore::MeshTopoAlgorithm::CollapseEdge(), MeshCore::MeshTopoAlgorithm::CollapseFacet(), and MeshCore::MeshTopoAlgorithm::CollapseVertex().
Member Data Documentation
_aulNeighbours
FacetIndex MeshCore::MeshFacet::_aulNeighbours[3]
Indices of neighbour facets.
Definition at line 449 of file Elements.h.
Referenced by MeshCore::MeshKernel::AddFacet(), MeshCore::MeshTopoAlgorithm::CollapseEdge(), MeshCore::MeshTopoAlgorithm::CollapseFacet(), MeshCore::MeshTopoAlgorithm::CollapseVertex(), MeshCore::MeshTopoAlgorithm::DelaunayFlip(), MeshCore::MeshEvalNeighbourhood::Evaluate(), MeshGui::ViewProviderMesh::faceInfo(), Mesh::Facet::Facet(), MeshCore::MeshFixDeformedFacets::Fixup(), MeshCore::MeshAlgorithm::GetBorderPoints(), MeshCore::MeshAlgorithm::GetFacetBorders(), MeshCore::MeshAlgorithm::GetFacetsBorders(), MeshCore::MeshEvalNeighbourhood::GetIndices(), MeshCore::MeshTopoAlgorithm::InsertVertex(), MeshCore::MeshTopoAlgorithm::InsertVertexAndSwapEdge(), MeshFacet(), MeshCore::MeshKernel::RebuildNeighbours(), MeshCore::MeshTopoAlgorithm::RemoveCorruptedFacet(), MeshCore::MeshTopoAlgorithm::RemoveDegeneratedFacet(), MeshCore::MeshPointFacetAdjacency::SetFacetNeighbourhood(), MeshCore::MeshTopoAlgorithm::SnapVertex(), MeshCore::MeshTopoAlgorithm::SplitEdge(), MeshCore::MeshTopoAlgorithm::SplitOpenEdge(), and MeshCore::MeshTopoAlgorithm::SwapEdge().
_aulPoints
PointIndex MeshCore::MeshFacet::_aulPoints[3]
Indices of corner points.
Definition at line 448 of file Elements.h.
Referenced by MeshCore::MeshSearchNeighbours::AccumulateNeighbours(), MeshCore::MeshBuilder::AddFacet(), MeshCore::MeshKernel::AddFacet(), MeshCore::MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection(), MeshCore::MeshKernel::AdjustNormal(), MeshCore::MeshTopoAlgorithm::CollapseEdge(), MeshCore::MeshTopoAlgorithm::CollapseFacet(), MeshGui::SoFCMeshSegmentShape::computeBBox(), CountOpenEdges(), MeshCore::MeshTopoAlgorithm::DelaunayFlip(), MeshCore::MeshKernel::DeleteFacets(), MeshGui::MeshSelection::deleteSelectionBorder(), MeshCore::MeshInfo::DetailedEdgeInfo(), MeshCore::MeshEvalOrientation::Evaluate(), MeshCore::MeshEvalSelfIntersection::Evaluate(), MeshGui::ViewProviderMesh::faceInfo(), Mesh::Facet::Facet(), MeshCore::MeshAlgorithm::FillupHole(), MeshCore::MeshRemoveNeedles::Fixup(), MeshCore::MeshFixCaps::Fixup(), MeshCore::MeshAlgorithm::GetBorderPoints(), GetEdge(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshKernel::GetFacetNormals(), MeshCore::MeshKernel::GetFacetPoints(), MeshCore::MeshKernel::GetGravityPoint(), MeshCore::MeshEvalSelfIntersection::GetIntersections(), MeshCore::MeshKernel::GetNormal(), Mesh::MeshObject::getPointDegree(), MeshCore::AbstractPolygonTriangulator::GetTriangle(), HasOpenEdge(), MeshCore::MeshTopoAlgorithm::InsertVertex(), MeshCore::MeshTopoAlgorithm::IsSwapEdgeLegal(), MeshCore::MeshInput::LoadNastran(), MeshFacet(), MeshCore::MeshSearchNeighbours::NeighboursFacetFromFacet(), MeshCore::MeshTopoAlgorithm::OptimizeTopology(), MeshPart::MeshProjection::projectEdgeToEdge(), MeshCore::MeshTopoAlgorithm::RemoveCorruptedFacet(), MeshCore::MeshTopoAlgorithm::RemoveDegeneratedFacet(), MeshCore::MeshOutput::SaveAsymptote(), MeshCore::MeshOutput::SaveNastran(), MeshCore::MeshOutput::SaveVRML(), MeshCore::MeshRefPointToFacets::SearchNeighbours(), MeshCore::MeshPointFacetAdjacency::SetFacetNeighbourhood(), MeshCore::MeshKernel::SetFacetPoints(), SetNeighbours(), SetVertices(), MeshCore::MeshTopoAlgorithm::ShouldSwapEdge(), MeshCore::MeshSimplify::simplify(), MeshCore::MeshTopoAlgorithm::SnapVertex(), MeshCore::MeshTopoAlgorithm::SplitEdge(), MeshCore::MeshTopoAlgorithm::SplitFacet(), MeshCore::MeshTopoAlgorithm::SplitOpenEdge(), MeshCore::MeshTopoAlgorithm::SwapEdge(), MeshCore::MeshCurvaturePlanarSegment::TestFacet(), MeshCore::MeshCurvatureCylindricalSegment::TestFacet(), MeshCore::MeshCurvatureSphericalSegment::TestFacet(), MeshCore::MeshCurvatureFreeformSegment::TestFacet(), MeshCore::EarClippingTriangulator::Triangulate(), MeshCore::QuasiDelaunayTriangulator::Triangulate(), MeshCore::DelaunayTriangulator::Triangulate(), and MeshCore::MeshKernel::VisitNeighbourFacetsOverCorners().
_ucFlag
unsigned char MeshCore::MeshFacet::_ucFlag mutable
Flag member.
Definition at line 446 of file Elements.h.
Referenced by MeshCore::MeshBuilder::AddFacet(), and MeshCore::MeshKernel::GetFacet().
_ulProp
unsigned long MeshCore::MeshFacet::_ulProp mutable
Free usable property.
Definition at line 447 of file Elements.h.
Referenced by MeshCore::MeshBuilder::AddFacet(), and MeshCore::MeshKernel::GetFacet().
The documentation for this class was generated from the following file:
Elements.h