FreeCAD: MeshCore::MeshFastFacetIterator Class Reference
MeshCore::MeshFastFacetIterator Class Reference
#include <Iterator.h>
Public Member Functions
MeshFastFacetIterator (const MeshKernel &rclM)
virtual ~MeshFastFacetIterator ()=default
void Init ()
void Next ()
bool More ()
MeshFastFacetIterator (const MeshFastFacetIterator &)=delete
MeshFastFacetIterator (MeshFastFacetIterator &&)=delete
void operator= (const MeshFastFacetIterator &)=delete
void operator= (MeshFastFacetIterator &&)=delete
Public Attributes
Base::Vector3f _afPoints [3]
Detailed Description
Definition at line 389 of file Iterator.h.
Constructor & Destructor Documentation
MeshFastFacetIterator() [1/3]
MeshCore::MeshFastFacetIterator::MeshFastFacetIterator (const MeshKernel & rclM) inline explicit
Definition at line 419 of file Iterator.h.
Referenced by MeshCore::MeshPointIterator::SetProperty().
~MeshFastFacetIterator()
virtual MeshCore::MeshFastFacetIterator::~MeshFastFacetIterator () virtual default
Referenced by MeshCore::MeshPointIterator::SetProperty().
MeshFastFacetIterator() [2/3]
MeshCore::MeshFastFacetIterator::MeshFastFacetIterator (const MeshFastFacetIterator &) delete
MeshFastFacetIterator() [3/3]
MeshCore::MeshFastFacetIterator::MeshFastFacetIterator (MeshFastFacetIterator &&) delete
Member Function Documentation
Init()
void MeshCore::MeshFastFacetIterator::Init () inline
Definition at line 395 of file Iterator.h.
Referenced by MeshCore::MeshPointIterator::SetProperty().
More()
bool MeshCore::MeshFastFacetIterator::More () inline
Definition at line 400 of file Iterator.h.
Referenced by MeshCore::MeshPointIterator::SetProperty().
Next()
void MeshCore::MeshFastFacetIterator::Next () inline
Definition at line 425 of file Iterator.h.
Referenced by MeshCore::MeshPointIterator::SetProperty().
operator=() [1/2]
void MeshCore::MeshFastFacetIterator::operator= (const MeshFastFacetIterator &) delete
operator=() [2/2]
void MeshCore::MeshFastFacetIterator::operator= (MeshFastFacetIterator &&) delete
Member Data Documentation
_afPoints
Base::Vector3f MeshCore::MeshFastFacetIterator::_afPoints[3]
Definition at line 405 of file Iterator.h.
Referenced by MeshCore::MeshPointIterator::SetProperty().
The documentation for this class was generated from the following file:
Iterator.h