FreeCAD: Gui::SoQtOffscreenRendererPy Class Reference
Gui::SoQtOffscreenRendererPy Class Reference
#include <SoQtOffscreenRendererPy.h>
Public Member Functions
SoQtOffscreenRendererPy (Py::PythonClassInstance *self, Py::Tuple &args, Py::Dict &kwds)
~SoQtOffscreenRendererPy () override
Py::Object repr () override
Py::Object setViewportRegion (const Py::Tuple &)
Py::Object getViewportRegion ()
Py::Object setBackgroundColor (const Py::Tuple &)
Py::Object getBackgroundColor ()
Py::Object setNumPasses (const Py::Tuple &)
Py::Object getNumPasses ()
Py::Object setInternalTextureFormat (const Py::Tuple &)
Py::Object getInternalTextureFormat ()
Py::Object render (const Py::Tuple &)
Py::Object writeToImage (const Py::Tuple &)
Py::Object getWriteImageFiletypeInfo ()
Static Public Member Functions
static void init_type ()
Detailed Description
Definition at line 53 of file SoQtOffscreenRendererPy.h.
Constructor & Destructor Documentation
SoQtOffscreenRendererPy()
SoQtOffscreenRendererPy::SoQtOffscreenRendererPy (Py::PythonClassInstance * self, Py::Tuple & args, Py::Dict & kwds)
Definition at line 31 of file SoQtOffscreenRendererPy.cpp.
References setViewportRegion().
~SoQtOffscreenRendererPy()
SoQtOffscreenRendererPy::~SoQtOffscreenRendererPy () override default
Member Function Documentation
getBackgroundColor()
Py::Object SoQtOffscreenRendererPy::getBackgroundColor ()
Definition at line 80 of file SoQtOffscreenRendererPy.cpp.
References getBackgroundColor().
Referenced by getBackgroundColor().
getInternalTextureFormat()
Py::Object SoQtOffscreenRendererPy::getInternalTextureFormat ()
Definition at line 119 of file SoQtOffscreenRendererPy.cpp.
getNumPasses()
Py::Object SoQtOffscreenRendererPy::getNumPasses ()
Definition at line 100 of file SoQtOffscreenRendererPy.cpp.
getViewportRegion()
Py::Object SoQtOffscreenRendererPy::getViewportRegion ()
Definition at line 58 of file SoQtOffscreenRendererPy.cpp.
References getViewportRegion().
Referenced by getViewportRegion().
getWriteImageFiletypeInfo()
Py::Object SoQtOffscreenRendererPy::getWriteImageFiletypeInfo ()
Definition at line 164 of file SoQtOffscreenRendererPy.cpp.
References getWriteImageFiletypeInfo(), and src.Mod.Test.testmakeWireString::String.
Referenced by getWriteImageFiletypeInfo().
init_type()
void SoQtOffscreenRendererPy::init_type () static
Definition at line 177 of file SoQtOffscreenRendererPy.cpp.
References OfflineRenderingUtils::render().
Referenced by Gui::Application::Application().
render()
Py::Object SoQtOffscreenRendererPy::render (const Py::Tuple & args)
Definition at line 125 of file SoQtOffscreenRendererPy.cpp.
References toolbit-attributes::args, Base::InterpreterSingleton::convertSWIGPointerObj(), SCL.SimpleDataTypes::e, and Base::Interpreter().
repr()
Py::Object SoQtOffscreenRendererPy::repr () override
Definition at line 39 of file SoQtOffscreenRendererPy.cpp.
References toolbit-attributes::s, and src.Mod.Test.testmakeWireString::String.
setBackgroundColor()
Py::Object SoQtOffscreenRendererPy::setBackgroundColor (const Py::Tuple & args)
Definition at line 67 of file SoQtOffscreenRendererPy.cpp.
References a, toolbit-attributes::args, SCL.SimpleDataTypes::b, and toolbit-attributes::g.
setInternalTextureFormat()
Py::Object SoQtOffscreenRendererPy::setInternalTextureFormat (const Py::Tuple & args)
Definition at line 106 of file SoQtOffscreenRendererPy.cpp.
References toolbit-attributes::args.
setNumPasses()
Py::Object SoQtOffscreenRendererPy::setNumPasses (const Py::Tuple & args)
Definition at line 87 of file SoQtOffscreenRendererPy.cpp.
References toolbit-attributes::args.
setViewportRegion()
Py::Object SoQtOffscreenRendererPy::setViewportRegion (const Py::Tuple & args)
Definition at line 46 of file SoQtOffscreenRendererPy.cpp.
References toolbit-attributes::args, Gui::SoQtOffscreenRenderer::setViewportRegion(), and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by SoQtOffscreenRendererPy().
writeToImage()
Py::Object SoQtOffscreenRendererPy::writeToImage (const Py::Tuple & args)
Definition at line 149 of file SoQtOffscreenRendererPy.cpp.
References toolbit-attributes::args.
The documentation for this class was generated from the following files:
SoQtOffscreenRendererPy.h
SoQtOffscreenRendererPy.cpp