FreeCAD: Materials::ModelProperty Class Reference
Materials::ModelProperty Class Reference
#include <Model.h>
Public Member Functions
ModelProperty ()
ModelProperty (const QString &name, const QString &header, const QString &type, const QString &units, const QString &url, const QString &description)
ModelProperty (const ModelProperty &other)
~ModelProperty () override=default
const QString getName () const
const QString getDisplayName () const
const QString getPropertyType () const
const QString getUnits () const
const QString getURL () const
const QString getDescription () const
const QString getInheritance () const
bool isInherited () const
void setName (const QString &name)
void setColumnHeader (const QString &header)
virtual void setPropertyType (const QString &type)
void setUnits (const QString &units)
void setURL (const QString &url)
void setDescription (const QString &description)
void setInheritance (const QString &uuid)
void addColumn (ModelProperty &column)
const std::vector< ModelProperty > & getColumns () const
int columns () const
ModelProperty & operator= (const ModelProperty &other)
bool operator== (const ModelProperty &other) const
bool operator!= (const ModelProperty &other) const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 71 of file Model.h.
Constructor & Destructor Documentation
ModelProperty() [1/3]
ModelProperty::ModelProperty ()
Definition at line 38 of file Model.cpp.
ModelProperty() [2/3]
ModelProperty::ModelProperty (const QString & name, const QString & header, const QString & type, const QString & units, const QString & url, const QString & description)
Definition at line 41 of file Model.cpp.
ModelProperty() [3/3]
ModelProperty::ModelProperty (const ModelProperty & other)
Definition at line 55 of file Model.cpp.
~ModelProperty()
Materials::ModelProperty::~ModelProperty () override default
Member Function Documentation
addColumn()
void Materials::ModelProperty::addColumn (ModelProperty & column) inline
Definition at line 145 of file Model.h.
Referenced by src.Mod.PartDesign.WizardShaft.WizardShaftTable.WizardShaftTable::slotInsertColumn().
columns()
int Materials::ModelProperty::columns () const inline
Definition at line 153 of file Model.h.
Referenced by Materials::MaterialProperty::MaterialProperty(), and Materials::MaterialProperty::setType().
getColumns()
const std::vector<ModelProperty>& Materials::ModelProperty::getColumns () const inline
Definition at line 149 of file Model.h.
Referenced by Materials::MaterialProperty::MaterialProperty().
getDescription()
const QString Materials::ModelProperty::getDescription () const inline
Definition at line 103 of file Model.h.
Referenced by MatGui::MaterialsEditor::updateMaterialProperties().
getDisplayName()
const QString ModelProperty::getDisplayName () const
Definition at line 69 of file Model.cpp.
References getName().
Referenced by MatGui::MaterialsEditor::updateMaterialProperties().
getInheritance()
const QString Materials::ModelProperty::getInheritance () const inline
Definition at line 107 of file Model.h.
getName()
const QString Materials::ModelProperty::getName () const inline
Definition at line 86 of file Model.h.
Referenced by getDisplayName().
getPropertyType()
const QString Materials::ModelProperty::getPropertyType () const inline
Definition at line 91 of file Model.h.
Referenced by Materials::MaterialProperty::MaterialProperty(), and MatGui::MaterialsEditor::updateMaterialProperties().
getUnits()
const QString Materials::ModelProperty::getUnits () const inline
Definition at line 95 of file Model.h.
Referenced by MatGui::MaterialsEditor::updateMaterialProperties().
getURL()
const QString Materials::ModelProperty::getURL () const inline
Definition at line 99 of file Model.h.
isInherited()
bool Materials::ModelProperty::isInherited () const inline
Definition at line 111 of file Model.h.
operator!=()
bool Materials::ModelProperty::operator!= (const ModelProperty & other) const inline
Definition at line 160 of file Model.h.
operator=()
ModelProperty & ModelProperty::operator= (const ModelProperty & other)
Definition at line 77 of file Model.cpp.
Referenced by Materials::MaterialProperty::operator=().
operator==()
bool ModelProperty::operator== (const ModelProperty & other) const
Definition at line 98 of file Model.cpp.
setColumnHeader()
void Materials::ModelProperty::setColumnHeader (const QString & header) inline
Definition at line 120 of file Model.h.
setDescription()
void Materials::ModelProperty::setDescription (const QString & description) inline
Definition at line 136 of file Model.h.
setInheritance()
void Materials::ModelProperty::setInheritance (const QString & uuid) inline
Definition at line 140 of file Model.h.
setName()
void Materials::ModelProperty::setName (const QString & name) inline
Definition at line 116 of file Model.h.
setPropertyType()
virtual void Materials::ModelProperty::setPropertyType (const QString & type) inline virtual
Reimplemented in Materials::MaterialProperty.
Definition at line 124 of file Model.h.
Referenced by Materials::MaterialProperty::setPropertyType().
setUnits()
void Materials::ModelProperty::setUnits (const QString & units) inline
Definition at line 128 of file Model.h.
setURL()
void Materials::ModelProperty::setURL (const QString & url) inline
Definition at line 132 of file Model.h.
The documentation for this class was generated from the following files:
Model.h
Model.cpp