FreeCAD: CAMTests.TestPathDressupDogbone.TestFeature Class Reference
CAMTests.TestPathDressupDogbone.TestFeature Class Reference
Public Member Functions
def __init__ (self)
def addProperty (self, typ, name, category, tip)
def setEditorMode (self, prop, mode)
Public Attributes
Path
Detailed Description
Definition at line 41 of file TestPathDressupDogbone.py.
Constructor & Destructor Documentation
__init__()
def CAMTests.TestPathDressupDogbone.TestFeature.__init__ (self)
Definition at line 42 of file TestPathDressupDogbone.py.
Referenced by draftguitools.gui_subelements.SubelementHighlight.finish().
Member Function Documentation
addProperty()
def CAMTests.TestPathDressupDogbone.TestFeature.addProperty (self, typ, name, category, tip)
Definition at line 45 of file TestPathDressupDogbone.py.
Referenced by femobjects.constraint_selfweight.ConstraintSelfWeight.__init__(), DocumentObject.Box.init(), DocumentObject.DocumentObject.onChanged(), and femobjects.constraint_selfweight.ConstraintSelfWeight.onDocumentRestored().
setEditorMode()
def CAMTests.TestPathDressupDogbone.TestFeature.setEditorMode (self, prop, mode)
Definition at line 48 of file TestPathDressupDogbone.py.
Member Data Documentation
Path
CAMTests.TestPathDressupDogbone.TestFeature.Path
Definition at line 43 of file TestPathDressupDogbone.py.
The documentation for this class was generated from the following file:
TestPathDressupDogbone.py