FreeCAD: nativeifc.ifc_export Namespace Reference
nativeifc.ifc_export Namespace Reference
Functions
def get_export_preferences (ifcfile, preferred_context=None, create=None)
def create_product (obj, parent, ifcfile, ifcclass=None)
def create_representation (obj, ifcfile)
def get_object_type (ifcentity, objecttype=None)
def is_annotation (obj)
def get_text (annotation)
def get_dimension (annotation)
def get_sectionplane (annotation)
def get_axis (obj)
def create_annotation (obj, ifcfile)
def get_history (ifcfile)
def get_placement (ifcelement, ifcfile=None, scale=None)
def get_scaled_point (point, ifcfile=None, is2d=False)
def get_scaled_value (value, ifcfile)
def export_and_convert (objs, doc)
def direct_conversion (objs, doc)
Variables
PARAMS = FreeCAD.ParamGet("User parameter:BaseApp/Preferences/Mod/NativeIFC")
Function Documentation
create_annotation()
def nativeifc.ifc_export.create_annotation (obj, ifcfile)
Adds an IfcAnnotation from the given object to the given IFC file
Definition at line 307 of file ifc_export.py.
References nativeifc.ifc_export.get_export_preferences(), nativeifc.ifc_export.get_history(), and nativeifc.ifc_export.is_annotation().
create_product()
def nativeifc.ifc_export.create_product (obj, parent, ifcfile, ifcclass = None)
Creates an IFC product out of a FreeCAD object
Definition at line 133 of file ifc_export.py.
References nativeifc.ifc_export.create_representation().
create_representation()
def nativeifc.ifc_export.create_representation (obj, ifcfile)
Creates a geometry representation for the given object
Definition at line 152 of file ifc_export.py.
References nativeifc.ifc_export.get_export_preferences().
Referenced by nativeifc.ifc_export.create_product().
direct_conversion()
def nativeifc.ifc_export.direct_conversion (objs, doc)
Exports the given objects to the given ifcfile and recreates the contents
Definition at line 383 of file ifc_export.py.
export_and_convert()
def nativeifc.ifc_export.export_and_convert (objs, doc)
Exports the given objects and their descendents to the given IFC file
and re-imports it into the given document. This is slower than direct_conversion()
but gives an intermediate file which can be useful for debugging
Definition at line 373 of file ifc_export.py.
get_axis()
def nativeifc.ifc_export.get_axis (obj)
Determines if a given IFC entity is an IfcGridAxis. Returns a tuple
containing a Placement, a length value in millimeters, and a tag
Definition at line 283 of file ifc_export.py.
get_dimension()
def nativeifc.ifc_export.get_dimension (annotation)
Determines if an IfcAnnotation is representing a dimension.
Returns a list containing the representation, two points indicating
the measured points, and optionally a third point indicating where
the dimension line is located, if available
Definition at line 236 of file ifc_export.py.
References nativeifc.ifc_export.get_placement().
Referenced by nativeifc.ifc_export.get_object_type().
get_export_preferences()
def nativeifc.ifc_export.get_export_preferences (ifcfile, preferred_context = None, create = None)
returns a preferences dict for exportIFC.
Preferred context can either indicate a ContextType like 'Model' or 'Plan',
or a [ContextIdentifier,ContextType,TargetView] list or tuple, for ex.
('Annotation','Plan') or ('Body','Model','MODEL_VIEW'). This function
will do its best to find the most appropriate context. If create is True,
if the exact context is not found, a new one is created
Definition at line 40 of file ifc_export.py.
Referenced by nativeifc.ifc_export.create_annotation(), and nativeifc.ifc_export.create_representation().
get_history()
def nativeifc.ifc_export.get_history (ifcfile)
Returns the owner history or None
Definition at line 330 of file ifc_export.py.
Referenced by nativeifc.ifc_export.create_annotation().
get_object_type()
def nativeifc.ifc_export.get_object_type (ifcentity, objecttype = None)
Determines a creation type for this object
Definition at line 177 of file ifc_export.py.
References nativeifc.ifc_export.get_dimension(), nativeifc.ifc_export.get_sectionplane(), and nativeifc.ifc_export.get_text().
get_placement()
def nativeifc.ifc_export.get_placement (ifcelement, ifcfile = None, scale = None)
Returns a FreeCAD placement from an IFC placement
Definition at line 342 of file ifc_export.py.
Referenced by draftguitools.gui_labels.Label.create(), nativeifc.ifc_export.get_dimension(), nativeifc.ifc_export.get_sectionplane(), draftguitools.gui_base_original.DraftTool.getStrings(), Arch.makeSectionPlane(), and draftguitools.gui_trackers.PlaneTracker.set().
get_scaled_point()
def nativeifc.ifc_export.get_scaled_point (point, ifcfile = None, is2d = False)
Returns a scaled 2d or 3d point tuple form a FreeCAD point
Definition at line 352 of file ifc_export.py.
get_scaled_value()
def nativeifc.ifc_export.get_scaled_value (value, ifcfile)
Returns a scaled dimension value
Definition at line 366 of file ifc_export.py.
get_sectionplane()
def nativeifc.ifc_export.get_sectionplane (annotation)
Determines if an IfcAnnotation is representing a section plane.
Returns a list containing a placement, and optionally an X dimension,
an Y dimension and a  depth dimension
Definition at line 263 of file ifc_export.py.
References nativeifc.ifc_export.get_placement().
Referenced by nativeifc.ifc_export.get_object_type().
get_text()
def nativeifc.ifc_export.get_text (annotation)
Determines if an IfcAnnotation contains an IfcTextLiteral.
Returns the IfcTextLiteral or None
Definition at line 224 of file ifc_export.py.
Referenced by nativeifc.ifc_export.get_object_type().
is_annotation()
def nativeifc.ifc_export.is_annotation (obj)
Determines if the given FreeCAD object should be saved as an IfcAnnotation
Definition at line 195 of file ifc_export.py.
Referenced by nativeifc.ifc_export.create_annotation().
Variable Documentation
PARAMS
nativeifc.ifc_export.PARAMS = FreeCAD.ParamGet("User parameter:BaseApp/Preferences/Mod/NativeIFC")
Definition at line 37 of file ifc_export.py.