FreeCAD: Part::Geom2dConic Class Reference
Part::Geom2dConic Class Reference abstract
#include <Geometry2d.h>
Public Member Functions
~Geom2dConic () override
Geometry2d * clone () const override=0
returns a cloned object
Base::Vector2d getLocation () const
void setLocation (const Base::Vector2d &Center)
bool isReversed () const
unsigned int getMemSize () const override=0
PyObject * getPyObject () override=0
const Handle (Geom2d_Geometry) &handle() const override=0
Public Member Functions inherited from Part::Geom2dCurve
Geom2dCurve ()
~Geom2dCurve () override
TopoDS_Shape toShape () const override
bool tangent (double u, gp_Dir2d &) const
Base::Vector2d pointAtParameter (double u) const
Base::Vector2d firstDerivativeAtParameter (double u) const
Base::Vector2d secondDerivativeAtParameter (double u) const
bool normal (double u, gp_Dir2d &dir) const
bool closestParameter (const Base::Vector2d &point, double &u) const
bool closestParameterToBasicCurve (const Base::Vector2d &point, double &u) const
Public Member Functions inherited from Part::Geometry2d
~Geometry2d () override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
Geometry2d (const Geometry2d &)=delete
Geometry2d & operator= (const Geometry2d &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
Geom2dConic ()
void SaveAxis (Base::Writer &writer, const gp_Ax22d &) const
void RestoreAxis (Base::XMLReader &reader, gp_Ax22d &)
Protected Member Functions inherited from Part::Geometry2d
Geometry2d ()
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 217 of file Geometry2d.h.
Constructor & Destructor Documentation
Geom2dConic()
Geom2dConic::Geom2dConic () protected default
~Geom2dConic()
Geom2dConic::~Geom2dConic () override default
Member Function Documentation
clone()
Geometry2d* Part::Geom2dConic::clone () const override pure virtual
returns a cloned object
Implements Part::Geometry2d.
Implemented in Part::Geom2dParabola, Part::Geom2dHyperbola, Part::Geom2dEllipse, and Part::Geom2dCircle.
Referenced by src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated().
getLocation()
Base::Vector2d Geom2dConic::getLocation () const
Definition at line 588 of file Geometry2d.cpp.
References Handle().
getMemSize()
unsigned int Part::Geom2dConic::getMemSize () const override pure virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Reimplemented from Part::Geometry2d.
Implemented in Part::Geom2dParabola, Part::Geom2dHyperbola, Part::Geom2dEllipse, and Part::Geom2dCircle.
getPyObject()
PyObject* Part::Geom2dConic::getPyObject () override pure virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Implemented in Part::Geom2dParabola, Part::Geom2dHyperbola, Part::Geom2dEllipse, and Part::Geom2dCircle.
Handle()
const Part::Geom2dConic::Handle (Geom2d_Geometry) const & override pure virtual
Implements Part::Geometry2d.
Implemented in Part::Geom2dParabola, Part::Geom2dHyperbola, Part::Geom2dEllipse, and Part::Geom2dCircle.
isReversed()
bool Geom2dConic::isReversed () const
Definition at line 608 of file Geometry2d.cpp.
References Base::Vector3< float_type >::Cross(), Handle(), and Base::Vector3< float_type >::z.
RestoreAxis()
void Geom2dConic::RestoreAxis (Base::XMLReader & reader, gp_Ax22d & axis) protected
Definition at line 634 of file Geometry2d.cpp.
References TechDrawTools.TaskFillTemplateFields::reader.
SaveAxis()
void Geom2dConic::SaveAxis (Base::Writer & writer, const gp_Ax22d & axis) const protected
Definition at line 620 of file Geometry2d.cpp.
References exportCSG::center(), and Base::Writer::Stream().
setLocation()
void Geom2dConic::setLocation (const Base::Vector2d & Center)
Definition at line 595 of file Geometry2d.cpp.
References SCL.SimpleDataTypes::e, and Handle().
The documentation for this class was generated from the following files:
Geometry2d.h
Geometry2d.cpp