FreeCAD: Fem::StdMeshers_NumberOfSegmentsPy Class Reference
Fem::StdMeshers_NumberOfSegmentsPy Class Reference
#include <HypothesisPy.h>
Public Member Functions
StdMeshers_NumberOfSegmentsPy (int hypId, int studyId, SMESH_Gen *gen)
~StdMeshers_NumberOfSegmentsPy () override
Py::Object setNumSegm (const Py::Tuple &args)
Py::Object getNumSegm (const Py::Tuple &args)
Public Member Functions inherited from Fem::SMESH_HypothesisPy< StdMeshers_NumberOfSegmentsPy >
SMESH_HypothesisPy (SMESH_Hypothesis *)
~SMESH_HypothesisPy () override
Py::Object getattr (const char *name) override
Py::Object repr () override
Py::Object getLibName (const Py::Tuple &args)
Py::Object setLibName (const Py::Tuple &args)
Py::Object isAuxiliary (const Py::Tuple &args)
Py::Object setParametersByMesh (const Py::Tuple &args)
std::shared_ptr< SMESH_Hypothesis > getHypothesis () const
Static Public Member Functions
static void init_type (PyObject *)
Static Public Member Functions inherited from Fem::SMESH_HypothesisPy< StdMeshers_NumberOfSegmentsPy >
static void init_type (PyObject *)
Additional Inherited Members
Public Types inherited from Fem::SMESH_HypothesisPy< StdMeshers_NumberOfSegmentsPy >
using SMESH_HypothesisPyBase = SMESH_HypothesisPy< StdMeshers_NumberOfSegmentsPy >
Protected Member Functions inherited from Fem::SMESH_HypothesisPy< StdMeshers_NumberOfSegmentsPy >
type * hypothesis () const
Detailed Description
Definition at line 671 of file HypothesisPy.h.
Constructor & Destructor Documentation
StdMeshers_NumberOfSegmentsPy()
StdMeshers_NumberOfSegmentsPy::StdMeshers_NumberOfSegmentsPy (int hypId, int studyId, SMESH_Gen * gen)
Definition at line 1034 of file HypothesisPy.cpp.
~StdMeshers_NumberOfSegmentsPy()
StdMeshers_NumberOfSegmentsPy::~StdMeshers_NumberOfSegmentsPy () override default
Member Function Documentation
getNumSegm()
Py::Object StdMeshers_NumberOfSegmentsPy::getNumSegm (const Py::Tuple & args)
Definition at line 1047 of file HypothesisPy.cpp.
References toolbit-attributes::args.
Referenced by init_type().
init_type()
void StdMeshers_NumberOfSegmentsPy::init_type (PyObject * module) static
Definition at line 1016 of file HypothesisPy.cpp.
References getNumSegm(), Fem::SMESH_HypothesisPy< StdMeshers_NumberOfSegmentsPy >::init_type(), src.Mod.PartDesign.fcgear.svggear::module, and setNumSegm().
Referenced by PyMOD_INIT_FUNC().
setNumSegm()
Py::Object StdMeshers_NumberOfSegmentsPy::setNumSegm (const Py::Tuple & args)
Definition at line 1041 of file HypothesisPy.cpp.
References toolbit-attributes::args.
Referenced by init_type().
The documentation for this class was generated from the following files:
HypothesisPy.h
HypothesisPy.cpp