FreeCAD: Gui::SelectionFilterPy Class Reference
Gui::SelectionFilterPy Class Reference
#include <SelectionFilterPy.h>
Public Member Functions
SelectionFilterPy (Py::PythonClassInstance *self, Py::Tuple &args, Py::Dict &kdws)
~SelectionFilterPy () override
Py::Object repr () override
Py::Object match ()
Py::Object result ()
Py::Object test (const Py::Tuple &)
Py::Object setFilter (const Py::Tuple &)
Py::Object getFilter ()
Static Public Member Functions
static void init_type ()
static SelectionFilterPy * cast (PyObject *py)
Public Attributes
SelectionFilter filter
Detailed Description
Python binding for SelectionFilter class.
filter=Gui.Selection.Filter("SELECT Part::Feature SUBELEMENT Edge")
Gui.Selection.addSelectionGate(filter)
See also
SelectionFilter
Author
Werner Mayer
Definition at line 61 of file SelectionFilterPy.h.
Constructor & Destructor Documentation
SelectionFilterPy()
SelectionFilterPy::SelectionFilterPy (Py::PythonClassInstance * self, Py::Tuple & args, Py::Dict & kdws)
Definition at line 31 of file SelectionFilterPy.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, filter, and Path.Post.scripts.refactored_centroid_post::str.
~SelectionFilterPy()
SelectionFilterPy::~SelectionFilterPy () override default
Member Function Documentation
cast()
static SelectionFilterPy* Gui::SelectionFilterPy::cast (PyObject * py) inline static
Definition at line 88 of file SelectionFilterPy.h.
Referenced by Gui::SelectionSingleton::sAddSelectionGate().
getFilter()
Py::Object SelectionFilterPy::getFilter ()
Definition at line 110 of file SelectionFilterPy.cpp.
References src.Mod.Test.testmakeWireString::String.
init_type()
void SelectionFilterPy::init_type () static
Definition at line 116 of file SelectionFilterPy.cpp.
References result.
Referenced by Gui::Application::Application().
match()
Py::Object SelectionFilterPy::match ()
Definition at line 56 of file SelectionFilterPy.cpp.
References filter, and Gui::SelectionFilter::match().
Referenced by WorkingPlane.PlaneBase::copy(), WorkingPlane.Plane::copy(), and WorkingPlane.PlaneGui::copy().
repr()
Py::Object SelectionFilterPy::repr () override
Definition at line 48 of file SelectionFilterPy.cpp.
References toolbit-attributes::s, and src.Mod.Test.testmakeWireString::String.
result()
Py::Object SelectionFilterPy::result ()
Definition at line 77 of file SelectionFilterPy.cpp.
References SurfaceTests.TestBlendCurve::vec.
setFilter()
Py::Object SelectionFilterPy::setFilter (const Py::Tuple & args)
Definition at line 93 of file SelectionFilterPy.cpp.
References toolbit-attributes::args, and SCL.SimpleDataTypes::e.
test()
Py::Object SelectionFilterPy::test (const Py::Tuple & args)
Definition at line 62 of file SelectionFilterPy.cpp.
References toolbit-attributes::args.
Member Data Documentation
filter
SelectionFilter Gui::SelectionFilterPy::filter
Definition at line 84 of file SelectionFilterPy.h.
Referenced by Gui::SelectionFilterGatePython::allow(), match(), and SelectionFilterPy().
The documentation for this class was generated from the following files:
SelectionFilterPy.h
SelectionFilterPy.cpp