FreeCAD: StartGui::FlowLayout Class Reference
StartGui::FlowLayout Class Reference
The FlowLayout class Based on https://forum.qt.io/topic/109408/is-there-a-qt-layout-grid-that-can-dynamically- change-row-and-column-counts-to-best-fit-the-space.
#include <FlowLayout.h>
Public Member Functions
FlowLayout (QWidget *parent=nullptr, int margin=-1, int hSpacing=-1, int vSpacing=-1)
~FlowLayout () override
void addItem (QLayoutItem *item) override
int count () const override
QLayoutItem * itemAt (int index) const override
QLayoutItem * takeAt (int index) override
Qt::Orientations expandingDirections () const override
bool hasHeightForWidth () const override
int heightForWidth (int width) const override
void setGeometry (const QRect &rect) override
QSize sizeHint () const override
QSize minimumSize () const override
Detailed Description
The FlowLayout class Based on https://forum.qt.io/topic/109408/is-there-a-qt-layout-grid-that-can-dynamically- change-row-and-column-counts-to-best-fit-the-space.
Definition at line 58 of file FlowLayout.h.
Constructor & Destructor Documentation
FlowLayout()
FlowLayout::FlowLayout (QWidget * parent = nullptr, int margin = -1, int hSpacing = -1, int vSpacing = -1) explicit
Definition at line 30 of file FlowLayout.cpp.
~FlowLayout()
FlowLayout::~FlowLayout () override
Definition at line 38 of file FlowLayout.cpp.
References takeAt().
Member Function Documentation
addItem()
void FlowLayout::addItem (QLayoutItem * item) override
Definition at line 46 of file FlowLayout.cpp.
count()
int FlowLayout::count () const override
Definition at line 69 of file FlowLayout.cpp.
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::set_status_filter().
expandingDirections()
Qt::Orientations FlowLayout::expandingDirections () const override
Definition at line 92 of file FlowLayout.cpp.
hasHeightForWidth()
bool FlowLayout::hasHeightForWidth () const override
Definition at line 97 of file FlowLayout.cpp.
heightForWidth()
int FlowLayout::heightForWidth (int width) const override
Definition at line 102 of file FlowLayout.cpp.
itemAt()
QLayoutItem * FlowLayout::itemAt (int index) const override
Definition at line 74 of file FlowLayout.cpp.
minimumSize()
QSize FlowLayout::minimumSize () const override
Definition at line 119 of file FlowLayout.cpp.
Referenced by sizeHint().
setGeometry()
void FlowLayout::setGeometry (const QRect & rect) override
Definition at line 108 of file FlowLayout.cpp.
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_readme_browser.WidgetReadmeBrowser::setMarkdown().
sizeHint()
QSize FlowLayout::sizeHint () const override
Definition at line 114 of file FlowLayout.cpp.
References minimumSize().
takeAt()
QLayoutItem * FlowLayout::takeAt (int index) override
Definition at line 83 of file FlowLayout.cpp.
Referenced by ~FlowLayout().
The documentation for this class was generated from the following files:
FlowLayout.h
FlowLayout.cpp