FreeCAD: Part::GeomBSplineCurve Class Reference
Part::GeomBSplineCurve Class Reference
#include <Geometry.h>
Public Member Functions
GeomBSplineCurve ()
GeomBSplineCurve (const Handle(Geom_BSplineCurve)&)
GeomBSplineCurve (const std::vector< Base::Vector3d > &poles, const std::vector< double > &weights, const std::vector< double > &knots, const std::vector< int > &multiplicities, int degree, bool periodic=false, bool checkrational=true)
~GeomBSplineCurve () override
Geometry * copy () const override
GeomCurve * createArc (double first, double last) const override
createArc Generates a curve that is an arc of this curve between given parameters
void interpolate (const std::vector< gp_Pnt > &, Standard_Boolean=Standard_False)
void interpolate (const std::vector< gp_Pnt > &, const std::vector< gp_Vec > &)
void getCardinalSplineTangents (const std::vector< gp_Pnt > &, const std::vector< double > &, std::vector< gp_Vec > &) const
void getCardinalSplineTangents (const std::vector< gp_Pnt > &, double, std::vector< gp_Vec > &) const
int countPoles () const
int countKnots () const
void setPole (int index, const Base::Vector3d &, double weight=-1)
void setPoles (const std::vector< Base::Vector3d > &poles, const std::vector< double > &weights)
void setPoles (const std::vector< Base::Vector3d > &poles)
void setWeights (const std::vector< double > &weights)
void setKnot (int index, const double val, int mult=-1)
void setKnots (const std::vector< double > &knots)
void setKnots (const std::vector< double > &knots, const std::vector< int > &multiplicities)
std::vector< Base::Vector3d > getPoles () const
std::vector< double > getWeights () const
std::vector< double > getKnots () const
std::vector< int > getMultiplicities () const
int getMultiplicity (int index) const
int getDegree () const
bool isPeriodic () const
void setPeriodic () const
bool isRational () const
bool join (const Handle(Geom_BoundedCurve)&)
void makeC1Continuous (double, double)
std::list< Geometry * > toBiArcs (double tolerance) const
void increaseDegree (int degree)
void approximate (double tol3d, int maxSegments, int maxDegree, GeomAbs_Shape continuity)
GeomBSplineCurve::approximate.
void approximate (const std::vector< Base::Vector3d > &pnts, int minDegree=3, int maxDegree=8, GeomAbs_Shape continuity=GeomAbs_C2, double tol3d=1.0e-3)
void approximate (const std::vector< Base::Vector3d > &pnts, Approx_ParametrizationType parType, int minDegree=3, int maxDegree=8, GeomAbs_Shape continuity=GeomAbs_C2, double tol3d=1.0e-3)
void approximate (const std::vector< Base::Vector3d > &pnts, double weight1, double weight2, double weight3, int maxDegree=8, GeomAbs_Shape continuity=GeomAbs_C2, double tol3d=1.0e-3)
GeomBSplineCurve::approximate.
void increaseMultiplicity (int index, int multiplicity)
void insertKnot (double param, int multiplicity)
bool removeKnot (int index, int multiplicity, double tolerance=Precision::PConfusion())
void Trim (double u, double v)
void scaleKnotsToBounds (double u0, double u1)
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
PyObject * getPyObject () override
bool isSame (const Geometry &other, double tol, double atol) const override
void setHandle (const Handle(Geom_BSplineCurve)&)
const Handle (Geom_Geometry) &handle() const override
Public Member Functions inherited from Part::GeomBoundedCurve
GeomBoundedCurve ()
~GeomBoundedCurve () override
virtual Base::Vector3d getStartPoint () const
virtual Base::Vector3d getEndPoint () const
Public Member Functions inherited from Part::GeomCurve
GeomCurve ()
~GeomCurve () override
bool isLinear (Base::Vector3d *dir=nullptr, Base::Vector3d *base=nullptr) const
TopoDS_Shape toShape () const override
GeomBSplineCurve * toBSpline (double first, double last) const
toBSpline Converts the curve to a B-spline
virtual GeomBSplineCurve * toNurbs (double first, double last) const
bool tangent (double u, gp_Dir &) const
bool tangent (double u, Base::Vector3d &dir) const
Base::Vector3d pointAtParameter (double u) const
Base::Vector3d firstDerivativeAtParameter (double u) const
Base::Vector3d secondDerivativeAtParameter (double u) const
bool closestParameter (const Base::Vector3d &point, double &u) const
bool closestParameterToBasisCurve (const Base::Vector3d &point, double &u) const
double getFirstParameter () const
double getLastParameter () const
double curvatureAt (double u) const
double length (double u, double v) const
bool normalAt (double u, Base::Vector3d &dir) const
bool normalAt (const Base::Vector3d &curvepoint, Base::Vector3d &dir) const
bool intersect (const GeomCurve *c, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> &points, double tol=Precision::Confusion()) const
void reverse ()
Base::Vector3d value (double u) const
GeomLine * toLine (KeepTag clone=CopyTag) const
GeomLineSegment * toLineSegment (KeepTag clone=CopyTag) const
Public Member Functions inherited from Part::Geometry
~Geometry () override
Geometry * clone () const
boost::uuids::uuid getTag () const
returns the tag of the geometry object
bool hasSameExtensions (const Geometry &other) const
std::vector< std::weak_ptr< const GeometryExtension > > getExtensions () const
bool hasExtension (const Base::Type &type) const
bool hasExtension (const std::string &name) const
std::weak_ptr< const GeometryExtension > getExtension (const Base::Type &type) const
std::weak_ptr< const GeometryExtension > getExtension (const std::string &name) const
std::weak_ptr< GeometryExtension > getExtension (const Base::Type &type)
std::weak_ptr< GeometryExtension > getExtension (const std::string &name)
void setExtension (std::unique_ptr< GeometryExtension > &&geo)
void deleteExtension (const Base::Type &type)
void deleteExtension (const std::string &name)
void mirror (const Base::Vector3d &point) const
void mirror (const Base::Vector3d &point, const Base::Vector3d &dir) const
void rotate (const Base::Placement &plm) const
void scale (const Base::Vector3d &vec, double scale) const
void transform (const Base::Matrix4D &mat) const
void translate (const Base::Vector3d &vec) const
Geometry (const Geometry &)=delete
Geometry & operator= (const Geometry &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Part::GeomCurve
static bool isLinear (const Handle(Geom_Curve) &c, Base::Vector3d *dir=nullptr, Base::Vector3d *base=nullptr)
Static Public Member Functions inherited from Part::Geometry
static std::unique_ptr< Geometry > fromShape (const TopoDS_Shape &s, bool silent=false)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions inherited from Part::Geometry
void createNewTag ()
create a new tag for the geometry object
void assignTag (const Part::Geometry *)
copies the tag from the geometry passed as a parameter to this object
void copyNonTag (const Part::Geometry *)
Geometry ()
Static Protected Member Functions inherited from Part::GeomCurve
static bool intersect (const Handle(Geom_Curve)&c, const Handle(Geom_Curve)&c2, std::vector< std::pair< Base::Vector3d, Base::Vector3d >> &points, double tol=Precision::Confusion())
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Part::Geometry
boost::uuids::uuid tag
std::vector< std::shared_ptr< GeometryExtension > > extensions
Detailed Description
Definition at line 311 of file Part/App/Geometry.h.
Constructor & Destructor Documentation
GeomBSplineCurve() [1/3]
GeomBSplineCurve::GeomBSplineCurve ()
Definition at line 1314 of file Part/App/Geometry.cpp.
GeomBSplineCurve() [2/3]
GeomBSplineCurve::GeomBSplineCurve (const Handle(Geom_BSplineCurve)& b) explicit
Definition at line 1331 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::b, and setHandle().
GeomBSplineCurve() [3/3]
GeomBSplineCurve::GeomBSplineCurve (const std::vector< Base::Vector3d > & poles, const std::vector< double > & weights, const std::vector< double > & knots, const std::vector< int > & multiplicities, int degree, bool periodic = false, bool checkrational = true)
Definition at line 1336 of file Part/App/Geometry.cpp.
References test::m, buildPsets::p, src.Mod.PartDesign.fcgear.svggear::w, MovieTool::x, and MovieTool::y.
~GeomBSplineCurve()
GeomBSplineCurve::~GeomBSplineCurve () override default
Member Function Documentation
approximate() [1/4]
void GeomBSplineCurve::approximate (const std::vector< Base::Vector3d > & pnts, Approx_ParametrizationType parType, int minDegree = 3, int maxDegree = 8, GeomAbs_Shape continuity = GeomAbs_C2, double tol3d = 1.0e-3)
Definition at line 1788 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::e, Handle(), setHandle(), and THROWM.
approximate() [2/4]
void GeomBSplineCurve::approximate (const std::vector< Base::Vector3d > & pnts, double weight1, double weight2, double weight3, int maxDegree = 8, GeomAbs_Shape continuity = GeomAbs_C2, double tol3d = 1.0e-3)
GeomBSplineCurve::approximate.
Parameters
pnts Points to fit
weight1 Weight of curve length as smoothing criterion
weight2 Weight of curvature as smoothing criterion
weight3 Weight of torsion as smoothing criterion
minDegree Minimum degree
maxDegree Maximum degree
continuity Continuity of the spline
tol3d Tolerance to the data points
Definition at line 1825 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::e, Handle(), setHandle(), and THROWM.
approximate() [3/4]
void GeomBSplineCurve::approximate (const std::vector< Base::Vector3d > & pnts, int minDegree = 3, int maxDegree = 8, GeomAbs_Shape continuity = GeomAbs_C2, double tol3d = 1.0e-3)
Definition at line 1763 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::e, Handle(), setHandle(), and THROWM.
approximate() [4/4]
void GeomBSplineCurve::approximate (double tol3d, int maxSegments, int maxDegree, GeomAbs_Shape continuity)
GeomBSplineCurve::approximate.
Parameters
tol3d
maxSegments
maxDegree
continuity
Definition at line 1741 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::e, Handle(), setHandle(), and THROWM.
copy()
Geometry* Part::GeomBSplineCurve::copy () const override virtual
returns a copy of this object having a new randomly generated tag. If you also want to copy the tag, you may use clone() instead. For creation of geometry with other handles, with or without the same tag, you may use the constructors and the sethandle functions. The tag of a geometry can be copied to another geometry using the assignTag function.
Implements Part::Geometry.
countKnots()
int Part::GeomBSplineCurve::countKnots () const
Referenced by Sketcher::SketchObject::deleteUnusedInternalGeometry(), Sketcher::SketchObject::exposeInternalGeometry(), Sketcher::SketchObject::insertBSplineKnot(), isSame(), and Sketcher::SketchObject::modifyBSplineKnotMultiplicity().
countPoles()
int Part::GeomBSplineCurve::countPoles () const
Referenced by Sketcher::SketchObject::deleteUnusedInternalGeometry(), Sketcher::SketchObject::exposeInternalGeometry(), Sketcher::SketchObject::insertBSplineKnot(), isSame(), and Sketcher::SketchObject::modifyBSplineKnotMultiplicity().
createArc()
GeomCurve* Part::GeomBSplineCurve::createArc (double first, double last) const override virtual
createArc Generates a curve that is an arc of this curve between given parameters
Parameters
first Parameter at start of arc
last Parameter at end of arc. This may be < first for periodic curves.
Returns
the new curve
Reimplemented from Part::GeomCurve.
getCardinalSplineTangents() [1/2]
void GeomBSplineCurve::getCardinalSplineTangents (const std::vector< gp_Pnt > & p, const std::vector< double > & c, std::vector< gp_Vec > & t) const
Compute the tangents for a Cardinal spline using the the cubic Hermite spline. It uses the method for Cardinal splines.
Definition at line 1661 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, SCL.SimpleDataTypes::e, SCL.SimpleDataTypes::f, SplineSurface::i, buildPsets::p, InitGui::t, and TestSpreadsheet::v.
getCardinalSplineTangents() [2/2]
void GeomBSplineCurve::getCardinalSplineTangents (const std::vector< gp_Pnt > & p, double c, std::vector< gp_Vec > & t) const
Compute the tangents for a Cardinal spline using the the cubic Hermite spline. It uses the method for Cardinal splines. It uses the same parameter for each tangent.
Definition at line 1691 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, SCL.SimpleDataTypes::e, SCL.SimpleDataTypes::f, SplineSurface::i, buildPsets::p, InitGui::t, and TestSpreadsheet::v.
getDegree()
int GeomBSplineCurve::getDegree () const
Definition at line 1589 of file Part/App/Geometry.cpp.
Referenced by Sketcher::Sketch::addBSpline(), Sketcher::SketchObject::insertBSplineKnot(), isSame(), Sketcher::SketchObject::modifyBSplineKnotMultiplicity(), and Save().
getKnots()
std::vector< double > GeomBSplineCurve::getKnots () const
Definition at line 1550 of file Part/App/Geometry.cpp.
References SplineSurface::i.
Referenced by Sketcher::Sketch::addBSpline(), Sketcher::SketchObject::exposeInternalGeometry(), Sketcher::SketchObject::insertBSplineKnot(), Sketcher::SketchObject::modifyBSplineKnotMultiplicity(), and Save().
getMemSize()
unsigned int GeomBSplineCurve::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Reimplemented from Part::Geometry.
Definition at line 1943 of file Part/App/Geometry.cpp.
getMultiplicities()
std::vector< int > GeomBSplineCurve::getMultiplicities () const
Definition at line 1564 of file Part/App/Geometry.cpp.
References SplineSurface::i, and test::m.
Referenced by Sketcher::Sketch::addBSpline(), and Save().
getMultiplicity()
int GeomBSplineCurve::getMultiplicity (int index) const
Definition at line 1578 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::e, and THROWM.
Referenced by Sketcher::SketchObject::modifyBSplineKnotMultiplicity().
getPoles()
std::vector< Base::Vector3d > GeomBSplineCurve::getPoles () const
Definition at line 1470 of file Part/App/Geometry.cpp.
References SplineSurface::i, and buildPsets::p.
Referenced by Sketcher::Sketch::addBSpline(), Sketcher::SketchObject::addCopy(), Sketcher::SketchObject::exposeInternalGeometry(), Sketcher::SketchObject::getSymmetric(), Sketcher::SketchObject::insertBSplineKnot(), Sketcher::SketchObject::modifyBSplineKnotMultiplicity(), SketcherGui::EditModeConstraintCoinManager::processConstraints(), and Save().
getPyObject()
PyObject * GeomBSplineCurve::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 2059 of file Part/App/Geometry.cpp.
References Part::Geometry::clone().
getWeights()
std::vector< double > GeomBSplineCurve::getWeights () const
Definition at line 1484 of file Part/App/Geometry.cpp.
References SplineSurface::i, and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by Sketcher::Sketch::addBSpline(), Sketcher::SketchObject::exposeInternalGeometry(), Sketcher::SketchObject::migrateSketch(), and Save().
Handle()
const Part::GeomBSplineCurve::Handle (Geom_Geometry) const & override virtual
Implements Part::Geometry.
Referenced by approximate(), increaseDegree(), increaseMultiplicity(), insertKnot(), interpolate(), removeKnot(), Restore(), scaleKnotsToBounds(), and setHandle().
increaseDegree()
void GeomBSplineCurve::increaseDegree (int degree)
Definition at line 1723 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::e, Handle(), and THROWM.
increaseMultiplicity()
void GeomBSplineCurve::increaseMultiplicity (int index, int multiplicity)
Definition at line 1851 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::e, Handle(), and THROWM.
insertKnot()
void GeomBSplineCurve::insertKnot (double param, int multiplicity)
Definition at line 1862 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::e, Handle(), Init::param, and THROWM.
interpolate() [1/2]
void GeomBSplineCurve::interpolate (const std::vector< gp_Pnt > & p, const std::vector< gp_Vec > & t)
Set the poles and tangents for the cubic Hermite spline
Definition at line 1634 of file Part/App/Geometry.cpp.
References Handle(), SplineSurface::i, interpolate(), buildPsets::p, and InitGui::t.
interpolate() [2/2]
void GeomBSplineCurve::interpolate (const std::vector< gp_Pnt > & p, Standard_Boolean periodic = Standard_False)
Interpolate a spline passing through the given points without tangency.
Definition at line 1618 of file Part/App/Geometry.cpp.
References Handle(), SplineSurface::i, and buildPsets::p.
Referenced by interpolate().
isPeriodic()
bool GeomBSplineCurve::isPeriodic () const
Definition at line 1594 of file Part/App/Geometry.cpp.
Referenced by Sketcher::Sketch::addBSpline(), Sketcher::SketchObject::isClosedCurve(), Sketcher::isPeriodicBSplineCurve(), isSame(), Save(), Sketcher::SketchObject::split(), and Trim().
isRational()
bool GeomBSplineCurve::isRational () const
Definition at line 1604 of file Part/App/Geometry.cpp.
isSame()
bool GeomBSplineCurve::isSame (const Geometry & other, double tol, double atol) const override virtual
Implements Part::Geometry.
Definition at line 2064 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::c, countKnots(), countPoles(), Base::Persistence::getClassTypeId(), getDegree(), Base::Persistence::getTypeId(), SplineSurface::i, Base::BaseClass::isDerivedFrom(), Part::GeomCurve::isLinear(), isPeriodic(), and Part::GeomCurve::toLineSegment().
join()
bool GeomBSplineCurve::join (const Handle(Geom_BoundedCurve)& other)
Definition at line 1609 of file Part/App/Geometry.cpp.
makeC1Continuous()
void GeomBSplineCurve::makeC1Continuous (double tol, double ang_tol)
Definition at line 1718 of file Part/App/Geometry.cpp.
removeKnot()
bool GeomBSplineCurve::removeKnot (int index, int multiplicity, double tolerance = Precision::PConfusion())
Definition at line 1874 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::e, Handle(), SplineSurface::i, THROWM, draftutils.utils::tolerance(), and TestSpreadsheet::v.
Restore()
void GeomBSplineCurve::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Reimplemented from Part::Geometry.
Definition at line 2001 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::e, Handle(), SplineSurface::i, test::m, buildPsets::p, TechDrawTools.TaskFillTemplateFields::reader, Part::Geometry::Restore(), THROWM, toolbit-attributes::val, src.Mod.PartDesign.fcgear.svggear::w, DrawingExample::X, and DrawingExample::Y.
Save()
void GeomBSplineCurve::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Reimplemented from Part::Geometry.
Definition at line 1948 of file Part/App/Geometry.cpp.
References Base::Writer::decInd(), getDegree(), getKnots(), getMultiplicities(), getPoles(), getWeights(), Base::Writer::incInd(), Base::Writer::ind(), isPeriodic(), Part::Geometry::Save(), and Base::Writer::Stream().
scaleKnotsToBounds()
void GeomBSplineCurve::scaleKnotsToBounds (double u0, double u1)
Definition at line 1923 of file Part/App/Geometry.cpp.
References KDL::abs(), SCL.SimpleDataTypes::e, Handle(), and THROWM.
setHandle()
void GeomBSplineCurve::setHandle (const Handle(Geom_BSplineCurve)& curve)
Definition at line 1368 of file Part/App/Geometry.cpp.
References Handle().
Referenced by approximate(), GeomBSplineCurve(), and Trim().
setKnot()
void GeomBSplineCurve::setKnot (int index, const double val, int mult = -1)
Definition at line 1515 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::e, THROWM, and toolbit-attributes::val.
Referenced by setKnots().
setKnots() [1/2]
void GeomBSplineCurve::setKnots (const std::vector< double > & knots)
Definition at line 1529 of file Part/App/Geometry.cpp.
References setKnot().
setKnots() [2/2]
void GeomBSplineCurve::setKnots (const std::vector< double > & knots, const std::vector< int > & multiplicities)
Definition at line 1538 of file Part/App/Geometry.cpp.
References setKnot().
setPeriodic()
void GeomBSplineCurve::setPeriodic () const
Definition at line 1599 of file Part/App/Geometry.cpp.
setPole()
void Part::GeomBSplineCurve::setPole (int index, const Base::Vector3d & , double weight = -1)
Referenced by setPoles().
setPoles() [1/2]
void GeomBSplineCurve::setPoles (const std::vector< Base::Vector3d > & poles)
Definition at line 1461 of file Part/App/Geometry.cpp.
References setPole().
setPoles() [2/2]
void GeomBSplineCurve::setPoles (const std::vector< Base::Vector3d > & poles, const std::vector< double > & weights)
Definition at line 1447 of file Part/App/Geometry.cpp.
References SplineSurface::i, and setPole().
Referenced by Sketcher::SketchObject::addCopy().
setWeights()
void GeomBSplineCurve::setWeights (const std::vector< double > & weights)
Definition at line 1498 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::e, and THROWM.
toBiArcs()
std::list< Geometry * > GeomBSplineCurve::toBiArcs (double tolerance) const
Definition at line 1422 of file Part/App/Geometry.cpp.
References draftutils.utils::tolerance().
Trim()
void GeomBSplineCurve::Trim (double u, double v)
Definition at line 1900 of file Part/App/Geometry.cpp.
References SCL.SimpleDataTypes::e, Part::GeomCurve::getFirstParameter(), Part::GeomCurve::getLastParameter(), isPeriodic(), setHandle(), THROWM, buildPsets::u, and TestSpreadsheet::v.
The documentation for this class was generated from the following files:
Part/App/Geometry.h
Part/App/Geometry.cpp