FreeCAD: ifc2x3.ifcrelinteractionrequirements Class Reference
ifc2x3.ifcrelinteractionrequirements Class Reference
Public Member Functions
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, dailyinteraction, importancerating, locationofinteraction, relatedspaceprogram, relatingspaceprogram)
def dailyinteraction ()
def importancerating ()
def locationofinteraction ()
def relatedspaceprogram ()
def relatingspaceprogram ()
Public Member Functions inherited from ifc2x3.ifcrelconnects
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description)
Public Member Functions inherited from ifc2x3.ifcroot
def globalid ()
def ownerhistory ()
def name ()
def description ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
dailyinteraction
importancerating
locationofinteraction
relatedspaceprogram
relatingspaceprogram
Public Attributes inherited from ifc2x3.ifcroot
globalid
ownerhistory
name
description
Detailed Description
Entity ifcrelinteractionrequirements definition.
:param dailyinteraction
:type dailyinteraction:ifccountmeasure
:param importancerating
:type importancerating:ifcnormalisedratiomeasure
:param locationofinteraction
:type locationofinteraction:ifcspatialstructureelement
:param relatedspaceprogram
:type relatedspaceprogram:ifcspaceprogram
:param relatingspaceprogram
:type relatingspaceprogram:ifcspaceprogram
Definition at line 2036 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcrelinteractionrequirements.__init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, dailyinteraction, importancerating, locationofinteraction, relatedspaceprogram, relatingspaceprogram)
Definition at line 2054 of file ifc2x3.py.
Member Function Documentation
dailyinteraction()
def ifc2x3.ifcrelinteractionrequirements.dailyinteraction ()
Definition at line 2063 of file ifc2x3.py.
References ifc2x3.ifcrelinteractionrequirements._dailyinteraction, SCL.TypeChecker.check_type(), and ifc2x3.ifcrelinteractionrequirements.dailyinteraction.
importancerating()
def ifc2x3.ifcrelinteractionrequirements.importancerating ()
Definition at line 2077 of file ifc2x3.py.
References ifc2x3.ifcrelinteractionrequirements._importancerating, SCL.TypeChecker.check_type(), and ifc2x3.ifcrelinteractionrequirements.importancerating.
locationofinteraction()
def ifc2x3.ifcrelinteractionrequirements.locationofinteraction ()
Definition at line 2091 of file ifc2x3.py.
References ifc2x3.ifcrelinteractionrequirements._locationofinteraction, SCL.TypeChecker.check_type(), and ifc2x3.ifcrelinteractionrequirements.locationofinteraction.
relatedspaceprogram()
def ifc2x3.ifcrelinteractionrequirements.relatedspaceprogram ()
Definition at line 2105 of file ifc2x3.py.
References ifc2x3.ifcrelinteractionrequirements._relatedspaceprogram, SCL.TypeChecker.check_type(), and ifc2x3.ifcrelinteractionrequirements.relatedspaceprogram.
relatingspaceprogram()
def ifc2x3.ifcrelinteractionrequirements.relatingspaceprogram ()
Definition at line 2119 of file ifc2x3.py.
References ifc2x3.ifcrelinteractionrequirements._relatingspaceprogram, SCL.TypeChecker.check_type(), and ifc2x3.ifcrelinteractionrequirements.relatingspaceprogram.
Member Data Documentation
dailyinteraction
ifc2x3.ifcrelinteractionrequirements.dailyinteraction
Definition at line 2056 of file ifc2x3.py.
Referenced by ifc2x3.ifcrelinteractionrequirements.dailyinteraction().
importancerating
ifc2x3.ifcrelinteractionrequirements.importancerating
Definition at line 2057 of file ifc2x3.py.
Referenced by ifc2x3.ifcrelinteractionrequirements.importancerating().
locationofinteraction
ifc2x3.ifcrelinteractionrequirements.locationofinteraction
Definition at line 2058 of file ifc2x3.py.
Referenced by ifc2x3.ifcrelinteractionrequirements.locationofinteraction().
relatedspaceprogram
ifc2x3.ifcrelinteractionrequirements.relatedspaceprogram
Definition at line 2059 of file ifc2x3.py.
Referenced by ifc2x3.ifcrelinteractionrequirements.relatedspaceprogram().
relatingspaceprogram
ifc2x3.ifcrelinteractionrequirements.relatingspaceprogram
Definition at line 2060 of file ifc2x3.py.
Referenced by ifc2x3.ifcrelinteractionrequirements.relatingspaceprogram().
The documentation for this class was generated from the following file:
ifc2x3.py