FreeCAD: App::PropertyFileIncluded Class Reference
App::PropertyFileIncluded Class Reference
#include <PropertyFile.h>
Public Member Functions
PropertyFileIncluded ()
~PropertyFileIncluded () override
void setValue (const char *sFile, const char *sName=nullptr)
const char * getValue () const
const char * getEditorName () const override
Get the class name of the associated property editor item.
PyObject * getPyObject () override
void setPyObject (PyObject *) override
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void SaveDocFile (Base::Writer &writer) const override
void RestoreDocFile (Base::Reader &reader) override
Property * Copy () const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
unsigned int getMemSize () const override
bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
std::string getExchangeTempFile () const
std::string getOriginalFileName () const
bool isEmpty () const
void setFilter (std::string filter)
std::string getFilter () const
Public Member Functions inherited from App::Property
Property ()
~Property () override
const char * getName () const
bool hasName () const
std::string getFullName () const
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual void afterRestore ()
virtual void onContainerRestored ()
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
int64_t getID () const
virtual void beforeSave () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
std::string getDocTransientPath () const
std::string getUniqueFileName (const std::string &, const std::string &) const
void aboutToSetValue () override
Gets called by all setValue() methods before the value has changed.
Protected Member Functions inherited from App::Property
virtual void hasSetValue ()
Gets called by all setValue() methods after the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Protected Attributes
std::string _cValue
std::string _BaseFileName
std::string _OriginalName
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
File include properties This property doesn't only save the file name like PropertyFile it also includes the file itself into the document. The file doesn't get loaded into memory, it gets copied from the document archive into the document transient directory. There it is accessible for the algorithms. You get the transient path through getDocTransientPath() It's allowed to read the file, it's not allowed to write the file directly in the transient path! That would undermine the Undo/Redo framework. It's only allowed to use setValue() to change the file. If you give a file name outside the transient dir to setValue() it will copy the file. If you give a file name in the transient path it will just rename and use the same file. You can use getExchangeTempFile() to get a file name in the transient dir to write a new file version.
Definition at line 78 of file PropertyFile.h.
Constructor & Destructor Documentation
PropertyFileIncluded()
PropertyFileIncluded::PropertyFileIncluded () default
~PropertyFileIncluded()
PropertyFileIncluded::~PropertyFileIncluded () override
Definition at line 53 of file PropertyFile.cpp.
References DrawingExample::file, and Base::FileInfo::ReadWrite.
Member Function Documentation
aboutToSetValue()
void PropertyFileIncluded::aboutToSetValue () override protected virtual
Gets called by all setValue() methods before the value has changed.
Reimplemented from App::Property.
Definition at line 63 of file PropertyFile.cpp.
References App::Property::aboutToSetValue().
Copy()
Property * PropertyFileIncluded::Copy () const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 476 of file PropertyFile.cpp.
References Base::Console(), DrawingExample::file, Base::FileInfo::filePath(), Base::ConsoleSingleton::Log(), Base::FileInfo::ReadWrite, Base::FileInfo::setPermissions(), and Path.Post.scripts.refactored_centroid_post::str.
getDocTransientPath()
std::string PropertyFileIncluded::getDocTransientPath () const protected
Definition at line 77 of file PropertyFile.cpp.
References Base::Persistence::getClassTypeId(), and Base::BaseClass::isDerivedFrom().
getEditorName()
const char* App::PropertyFileIncluded::getEditorName () const inline override virtual
Get the class name of the associated property editor item.
Reimplemented from App::Property.
Definition at line 89 of file PropertyFile.h.
getExchangeTempFile()
std::string PropertyFileIncluded::getExchangeTempFile () const
get a temp file name in the transient path of the document. Using this file for new Version of the file and set this file with setValue() is the fastest way to change the File.
Definition at line 100 of file PropertyFile.cpp.
References Base::FileInfo::getTempFileName(), and getValue().
getFilter()
std::string PropertyFileIncluded::getFilter () const
Definition at line 589 of file PropertyFile.cpp.
Referenced by Gui::PropertyEditor::PropertyTransientFileItem::setEditorData().
getMemSize()
unsigned int PropertyFileIncluded::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence
See also
Base::Persistence
Reimplemented from App::Property.
Definition at line 576 of file PropertyFile.cpp.
References App::Property::getMemSize().
getOriginalFileName()
std::string PropertyFileIncluded::getOriginalFileName () const
Definition at line 106 of file PropertyFile.cpp.
Referenced by App::VRMLObject::onChanged().
getPyObject()
PyObject * PropertyFileIncluded::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 238 of file PropertyFile.cpp.
References buildPsets::p.
getUniqueFileName()
std::string PropertyFileIncluded::getUniqueFileName (const std::string & path, const std::string & filename) const protected
Definition at line 88 of file PropertyFile.cpp.
References Base::FileInfo::exists(), Base::FileInfo::filePath(), Base::Uuid::getValue(), and Base::FileInfo::setFile().
getValue()
const char * PropertyFileIncluded::getValue () const
Definition at line 233 of file PropertyFile.cpp.
Referenced by TechDrawGui::QGISVGTemplate::createClickHandles(), TechDrawGui::QGIViewPart::drawAllFaces(), TechDraw::DrawSVGTemplate::getAutofillByEditableName(), TechDraw::DrawGeomHatch::getDecodedSpecsFromFile(), TechDraw::DrawSVGTemplate::getEditableTextsFromTemplate(), TechDraw::DrawSVGTemplate::getTemplateDocument(), TechDraw::DrawGeomHatch::makeLineSets(), TechDraw::DrawViewSection::makeLineSets(), TechDraw::DrawSVGTemplate::onChanged(), TechDrawGui::QGSPage::postProcessXml(), Gui::Dialog::DlgEditFileIncludePropertyExternal::processFile(), TechDraw::DrawSVGTemplate::processTemplate(), Gui::ViewProviderVRMLObject::updateData(), and RobotGui::ViewProviderRobotObject::updateData().
isEmpty()
bool App::PropertyFileIncluded::isEmpty () const inline
Definition at line 125 of file PropertyFile.h.
Referenced by TechDrawGui::QGIViewPart::drawAllFaces(), TechDraw::DrawGeomHatch::makeLineSets(), and TechDraw::DrawViewSection::makeLineSets().
isSame()
bool App::PropertyFileIncluded::isSame (const Property & other) const inline override virtual
Compare if this property has the same content as the given one.
Reimplemented from App::Property.
Definition at line 106 of file PropertyFile.h.
References Base::Persistence::getTypeId().
Paste()
void PropertyFileIncluded::Paste (const Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 521 of file PropertyFile.cpp.
References _BaseFileName, _cValue, Base::FileInfo::copyTo(), Base::FileInfo::deleteFile(), Base::FileInfo::dirPath(), Base::FileInfo::exists(), Base::FileInfo::fileName(), Base::FileInfo::filePath(), Base::FileInfo::ReadOnly, Base::FileInfo::ReadWrite, Base::FileInfo::renameFile(), Base::FileInfo::setFile(), Base::FileInfo::setPermissions(), and Path.Post.scripts.refactored_centroid_post::str.
Restore()
void PropertyFileIncluded::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 396 of file PropertyFile.cpp.
References DrawingExample::file, TechDrawTools.TaskFillTemplateFields::reader, Base::FileInfo::ReadOnly, and Base::FileInfo::setPermissions().
RestoreDocFile()
void PropertyFileIncluded::RestoreDocFile (Base::Reader &) override virtual
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data. Again you have to apply for the call of this method in the Restore() call:
void PropertyMeshKernel::Restore(Base::XMLReader &reader)
{
  reader.readElement("Mesh");
  std::string file (reader.getAttribute("file") );
  if(file == "")
  {
    // read XML
    MeshCore::MeshDocXML restorer(*_pcMesh);
    restorer.Restore(reader);
  }else{
    // initiate a file read
    reader.addFile(file.c_str(),this);
 }
}
After you issued the reader.addFile() your RestoreDocFile() is called:
void PropertyMeshKernel::RestoreDocFile(Base::Reader &reader)
{
    _pcMesh->Read( reader );
}
See also
Base::Reader,Base::XMLReader
Reimplemented from Base::Persistence.
Definition at line 447 of file PropertyFile.cpp.
References SCL.SimpleDataTypes::c, Base::FileInfo::exists(), Base::FileInfo::isWritable(), TechDrawTools.TaskFillTemplateFields::reader, Base::FileInfo::ReadOnly, Base::FileInfo::setPermissions(), and Path.Post.scripts.refactored_centroid_post::str.
Save()
void PropertyFileIncluded::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 355 of file PropertyFile.cpp.
References Base::Writer::addFile(), Base::Writer::decInd(), Base::FileInfo::exists(), DrawingExample::file, Base::FileInfo::filePath(), Base::Writer::incInd(), Base::Writer::ind(), Base::Writer::insertBinFile(), Base::Writer::isForceXML(), and Base::Writer::Stream().
SaveDocFile()
void PropertyFileIncluded::SaveDocFile (Base::Writer &) const override virtual
This method is used to save large amounts of data to a binary file. Sometimes it makes no sense to write property data as XML. In case the amount of data is too big or the data type has a more effective way to save itself. In this cases it is possible to write the data in a separate file inside the document archive. In case you want do so you have to re-implement SaveDocFile(). First, you have to inform the framework in Save() that you want do so. Here an example from the Mesh module which can save a (pontetionaly big) triangle mesh:
void PropertyMeshKernel::Save (Base::Writer &writer) const
{
  if (writer.isForceXML())
  {
    writer << writer.ind() << "<Mesh>" << std::endl;
    MeshCore::MeshDocXML saver(*_pcMesh);
    saver.Save(writer);
  }else{
   writer << writer.ind() << "<Mesh file=\"" << writer.addFile("MeshKernel.bms", this) <<
"\"/>" << std::endl;
}
The writer.isForceXML() is an indication to force you to write XML. Regardless of size and effectiveness. The second part informs the Base::writer through writer.addFile("MeshKernel.bms", this) that this object wants to write a file with the given name. The method addFile() returns a unique name that then is written in the XML stream. This allows your RestoreDocFile() method to identify and read the file again. Later your SaveDocFile() method is called as many times as you issued the addFile() call:
 void
PropertyMeshKernel::SaveDocFile (Base::Writer &writer) const
{
    _pcMesh->Write( writer );
}
In this method you can simply stream your content to the file (Base::Writer inheriting from ostream).
Reimplemented from Base::Persistence.
Definition at line 429 of file PropertyFile.cpp.
References SCL.SimpleDataTypes::c, Path.Post.scripts.refactored_centroid_post::str, and Base::Writer::Stream().
setFilter()
void PropertyFileIncluded::setFilter (std::string filter)
Definition at line 584 of file PropertyFile.cpp.
References Path.Post.scripts.opensbp_post::move().
setPyObject()
void PropertyFileIncluded::setPyObject (PyObject * value) override virtual
Reimplemented from Base::BaseClass.
Definition at line 281 of file PropertyFile.cpp.
References Path.Base.SetupSheet::dict, Path.Log::error(), DrawingExample::file, App::getNameFromFile(), App::isIOFile(), and src.Mod.Test.testmakeWireString::String.
setValue()
void PropertyFileIncluded::setValue (const char * sFile, const char * sName = nullptr)
Definition at line 111 of file PropertyFile.cpp.
References Base::FileInfo::deleteFile(), Base::FileInfo::dirPath(), Base::FileInfo::exists(), create_qrc::ext, Base::FileInfo::extension(), DrawingExample::file, Base::FileInfo::fileName(), Base::FileInfo::fileNamePure(), Base::FileInfo::filePath(), SplineSurface::i, Base::FileInfo::ReadOnly, Base::FileInfo::ReadWrite, Base::FileInfo::setFile(), Base::FileInfo::setPermissions(), and Path.Post.scripts.refactored_centroid_post::str.
Referenced by Gui::Dialog::DlgEditFileIncludePropertyExternal::processFile(), TechDraw::DrawHatch::replaceFileIncluded(), TechDraw::DrawTileWeld::replaceFileIncluded(), TechDraw::DrawSVGTemplate::replaceFileIncluded(), TechDraw::DrawViewImage::replaceImageIncluded(), TechDraw::DrawGeomHatch::replacePatIncluded(), TechDraw::DrawViewSection::replacePatIncluded(), and TechDraw::DrawViewSection::replaceSvgIncluded().
Member Data Documentation
_BaseFileName
std::string App::PropertyFileIncluded::_BaseFileName mutable protected
Definition at line 141 of file PropertyFile.h.
Referenced by Paste().
_cValue
std::string App::PropertyFileIncluded::_cValue mutable protected
Definition at line 140 of file PropertyFile.h.
Referenced by Paste().
_OriginalName
std::string App::PropertyFileIncluded::_OriginalName mutable protected
Definition at line 142 of file PropertyFile.h.
The documentation for this class was generated from the following files:
PropertyFile.h
PropertyFile.cpp