FreeCAD: Gui::Polyline Class Reference
Gui::Polyline Class Reference
#include <GLPainter.h>
Public Member Functions
Polyline (View3DInventorViewer *v)
Polyline ()
~Polyline () override
void setWorking (bool on)
bool isWorking () const
void setViewer (View3DInventorViewer *v)
void setCoords (int x, int y)
void setColor (int r, int g, int b, int a=0)
void setLineWidth (float l)
void setClosed (bool c)
void setCloseStippled (bool c)
void addNode (const QPoint &p)
void popNode ()
void clear ()
void paintGL () override
Public Member Functions inherited from Gui::GLGraphicsItem
GLGraphicsItem ()=default
~GLGraphicsItem () override=default
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 116 of file GLPainter.h.
Constructor & Destructor Documentation
Polyline() [1/2]
Polyline::Polyline (View3DInventorViewer * v) explicit
Definition at line 308 of file GLPainter.cpp.
Polyline() [2/2]
Polyline::Polyline ()
Definition at line 322 of file GLPainter.cpp.
~Polyline()
Polyline::~Polyline () override default
Member Function Documentation
addNode()
void Polyline::addNode (const QPoint & p)
Definition at line 382 of file GLPainter.cpp.
Referenced by Gui::PolyPickerSelection::locationEvent(), Gui::FreehandSelection::locationEvent(), Gui::PolyPickerSelection::mouseButtonEvent(), and Gui::FreehandSelection::mouseButtonEvent().
clear()
void Polyline::clear ()
Definition at line 393 of file GLPainter.cpp.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__(), Gui::PolyPickerSelection::mouseButtonEvent(), and Gui::FreehandSelection::mouseButtonEvent().
isWorking()
bool Polyline::isWorking () const
Definition at line 343 of file GLPainter.cpp.
Referenced by Gui::PolyPickerSelection::locationEvent(), Gui::FreehandSelection::locationEvent(), Gui::PolyPickerSelection::mouseButtonEvent(), and Gui::FreehandSelection::mouseButtonEvent().
paintGL()
void Polyline::paintGL () override virtual
Implements Gui::GLGraphicsItem.
Definition at line 398 of file GLPainter.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoRenderManager(), glBlendFunc, glDisable, glEnable, glLineWidth, and glMatrixMode.
popNode()
void Polyline::popNode ()
Definition at line 387 of file GLPainter.cpp.
Referenced by Gui::PolyPickerSelection::locationEvent().
setClosed()
void Polyline::setClosed (bool c)
Definition at line 367 of file GLPainter.cpp.
References SCL.SimpleDataTypes::c.
Referenced by Gui::FreehandSelection::setClosed().
setCloseStippled()
void Polyline::setCloseStippled (bool c)
Definition at line 372 of file GLPainter.cpp.
References SCL.SimpleDataTypes::c.
Referenced by Gui::FreehandSelection::setClosed().
setColor()
void Polyline::setColor (int r, int g, int b, int a = 0)
Definition at line 359 of file GLPainter.cpp.
References a, SCL.SimpleDataTypes::b, and toolbit-attributes::g.
Referenced by Gui::PolyPickerSelection::setColor().
setCoords()
void Polyline::setCoords (int x, int y)
Definition at line 353 of file GLPainter.cpp.
References MovieTool::x, and MovieTool::y.
Referenced by Gui::FreehandSelection::locationEvent(), and Gui::FreehandSelection::mouseButtonEvent().
setLineWidth()
void Polyline::setLineWidth (float l)
Definition at line 377 of file GLPainter.cpp.
References RobotExample::l.
Referenced by Gui::PolyPickerSelection::setLineWidth().
setViewer()
void Polyline::setViewer (View3DInventorViewer * v)
Definition at line 348 of file GLPainter.cpp.
References TestSpreadsheet::v.
Referenced by Gui::PolyPickerSelection::initialize().
setWorking()
void Polyline::setWorking (bool on)
Definition at line 338 of file GLPainter.cpp.
Referenced by Gui::PolyPickerSelection::mouseButtonEvent(), and Gui::FreehandSelection::mouseButtonEvent().
The documentation for this class was generated from the following files:
GLPainter.h
GLPainter.cpp