FreeCAD: DlgSettingsLightSources.cpp File Reference
DlgSettingsLightSources.cpp File Reference
#include "PreCompiled.h"
#include <Inventor/draggers/SoDirectionalLightDragger.h>
#include <Inventor/events/SoEvent.h>
#include <Inventor/nodes/SoDirectionalLight.h>
#include <Inventor/nodes/SoEventCallback.h>
#include <Inventor/nodes/SoOrthographicCamera.h>
#include <Inventor/nodes/SoPickStyle.h>
#include <Inventor/nodes/SoSeparator.h>
#include <Inventor/nodes/SoMaterial.h>
#include <Inventor/nodes/SoSphere.h>
#include "DlgSettingsLightSources.h"
#include "ui_DlgSettingsLightSources.h"
#include <App/Application.h>
#include <Gui/View3DInventorViewer.h>
#include <Gui/View3DSettings.h>
#include "moc_DlgSettingsLightSources.cpp"
Functions
static SbVec3f getDirectionVector (const SbRotation &rotation)
static void setLightDirection (const SbRotation &rotation, Gui::View3DInventorViewer *viewer)
static void setLightDraggerDirection (const SbRotation &rotation, SoDirectionalLightDragger *light_dragger)
static void setValueSilently (QDoubleSpinBox *spn, const float val)
static SoMaterial * createMaterial (void)
static SoSphere * createSphere (void)
Function Documentation
createMaterial()
static SoMaterial* createMaterial (void) inline static
Definition at line 111 of file DlgSettingsLightSources.cpp.
createSphere()
static SoSphere* createSphere (void) inline static
Definition at line 130 of file DlgSettingsLightSources.cpp.
getDirectionVector()
static SbVec3f getDirectionVector (const SbRotation & rotation) inline static
Definition at line 60 of file DlgSettingsLightSources.cpp.
Referenced by setLightDirection(), and Gui::Dialog::DlgSettingsLightSources::updateDraggerQS().
setLightDirection()
static void setLightDirection (const SbRotation & rotation, Gui::View3DInventorViewer * viewer) inline static
Definition at line 68 of file DlgSettingsLightSources.cpp.
References getDirectionVector(), and OfflineRenderingUtils::viewer().
Referenced by Gui::Dialog::DlgSettingsLightSources::updateDraggerQS(), and Gui::Dialog::DlgSettingsLightSources::updateDraggerXYZ().
setLightDraggerDirection()
static void setLightDraggerDirection (const SbRotation & rotation, SoDirectionalLightDragger * light_dragger) inline static
Definition at line 74 of file DlgSettingsLightSources.cpp.
Referenced by Gui::Dialog::DlgSettingsLightSources::updateDraggerQS(), and Gui::Dialog::DlgSettingsLightSources::updateDraggerXYZ().
setValueSilently()
static void setValueSilently (QDoubleSpinBox * spn, const float val) inline static
Definition at line 80 of file DlgSettingsLightSources.cpp.
References toolbit-attributes::val.
Referenced by Gui::Dialog::DlgSettingsLightSources::updateDraggerQS(), and Gui::Dialog::DlgSettingsLightSources::updateDraggerXYZ().