FreeCAD: App::Transaction Class Reference
App::Transaction Class Reference
#include <Transactions.h>
Public Member Functions
Transaction (int id=0)
~Transaction () override
Construction.
void apply (Document &Doc, bool forward)
apply the content to the document
unsigned int getMemSize () const override
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
This method is used to restore properties from an XML document.
int getID () const
Return the transaction ID.
bool isEmpty () const
Returns true if the transaction list is empty; otherwise returns false.
bool hasObject (const TransactionalObject *Obj) const
check if this object is used in a transaction
void addOrRemoveProperty (TransactionalObject *Obj, const Property *pcProp, bool add)
void addObjectNew (TransactionalObject *Obj)
void addObjectDel (const TransactionalObject *Obj)
void addObjectChange (const TransactionalObject *Obj, const Property *Prop)
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static int getNewID ()
Generate a new unique transaction ID.
static int getLastID ()
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes
std::string Name
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Represents a atomic transaction of the document
Definition at line 66 of file Transactions.h.
Constructor & Destructor Documentation
Transaction()
Transaction::Transaction (int id = 0) explicit
Construction
Parameters
id transaction id. If zero, then it will be generated automatically as a monotonically increasing index across the entire application. User can pass in a transaction id to group multiple transactions from different document, so that they can be undo/redo together.
Definition at line 52 of file Transactions.cpp.
References SplineSurface::id.
~Transaction()
Transaction::~Transaction () override
Construction.
A destructor. A more elaborate description of the destructor.
Definition at line 64 of file Transactions.cpp.
References App::Destroy, and App::TransactionObject::New.
Member Function Documentation
addObjectChange()
void Transaction::addObjectChange (const TransactionalObject * Obj, const Property * Prop)
Definition at line 250 of file Transactions.cpp.
References App::TransactionObject::Chn, App::TransactionFactory::createTransaction(), Base::Persistence::getTypeId(), App::TransactionFactory::instance(), RobotExample::pos, and App::TransactionObject::setProperty().
Referenced by App::Document::_removeObject(), and App::Document::onBeforeChangeProperty().
addObjectDel()
void Transaction::addObjectDel (const TransactionalObject * Obj)
Definition at line 229 of file Transactions.cpp.
References App::TransactionObject::Chn, App::TransactionFactory::createTransaction(), App::TransactionObject::Del, Base::Persistence::getTypeId(), App::TransactionFactory::instance(), App::TransactionObject::New, and RobotExample::pos.
Referenced by App::Document::_addObject(), App::Document::addObject(), App::Document::addObjects(), and Gui::Document::slotTransactionAppend().
addObjectNew()
void Transaction::addObjectNew (TransactionalObject * Obj)
Definition at line 200 of file Transactions.cpp.
References App::TransactionObject::_NameInDocument, App::TransactionFactory::createTransaction(), App::TransactionObject::Del, App::TransactionalObject::detachFromDocument(), Base::Persistence::getTypeId(), App::TransactionFactory::instance(), App::TransactionObject::New, and RobotExample::pos.
Referenced by App::Document::_removeObject(), App::Document::removeObject(), and Gui::Document::slotTransactionRemove().
addOrRemoveProperty()
void Transaction::addOrRemoveProperty (TransactionalObject * Obj, const Property * pcProp, bool add)
Definition at line 147 of file Transactions.cpp.
References App::TransactionObject::addOrRemoveProperty(), App::TransactionObject::Chn, App::TransactionFactory::createTransaction(), Base::Persistence::getTypeId(), App::TransactionFactory::instance(), and RobotExample::pos.
Referenced by App::Document::addOrRemovePropertyOfObject().
apply()
void Transaction::apply (Document & Doc, bool forward)
apply the content to the document
Definition at line 170 of file Transactions.cpp.
References SCL.SimpleDataTypes::e, FC_ERR, Path.Log::info(), and Name.
Referenced by App::Document::_abortTransaction().
getID()
int Transaction::getID () const
Return the transaction ID.
Definition at line 132 of file Transactions.cpp.
Referenced by App::Document::_abortTransaction(), App::Document::_commitTransaction(), App::Document::_openTransaction(), App::Document::abortTransaction(), App::Document::commitTransaction(), App::Document::getAvailableUndos(), App::Document::getTransactionID(), App::Document::redo(), App::Document::renameTransaction(), and App::Document::undo().
getLastID()
int Transaction::getLastID () static
Definition at line 112 of file Transactions.cpp.
References _TransactionID.
Referenced by App::Application::getActiveTransaction().
getMemSize()
unsigned int Transaction::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
Definition at line 117 of file Transactions.cpp.
getNewID()
int Transaction::getNewID () static
Generate a new unique transaction ID.
Definition at line 102 of file Transactions.cpp.
References _TransactionID, and SplineSurface::id.
Referenced by App::Application::setActiveTransaction().
hasObject()
bool Transaction::hasObject (const TransactionalObject * Obj) const
check if this object is used in a transaction
Definition at line 142 of file Transactions.cpp.
References src.Mod.AddonManager.NetworkManager::count.
isEmpty()
bool Transaction::isEmpty () const
Returns true if the transaction list is empty; otherwise returns false.
Definition at line 137 of file Transactions.cpp.
Restore()
void Transaction::Restore (Base::XMLReader & reader) override virtual
This method is used to restore properties from an XML document.
Implements Base::Persistence.
Definition at line 127 of file Transactions.cpp.
Save()
void Transaction::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 122 of file Transactions.cpp.
Member Data Documentation
Name
std::string App::Transaction::Name
Definition at line 87 of file Transactions.h.
Referenced by importers.importIFClegacy.IfcWriter::__repr__(), App::Document::_openTransaction(), apply(), bimcommands.BimClassification.BIM_Classification::build_xml(), App::Document::getAvailableUndoNames(), App::Document::redo(), App::Document::renameTransaction(), and App::Document::undo().
The documentation for this class was generated from the following files:
Transactions.h
Transactions.cpp