FreeCAD: Metadata.cpp File Reference
Metadata.cpp File Reference
#include "PreCompiled.h"
#include <boost/core/ignore_unused.hpp>
#include <memory>
#include <sstream>
#include <xercesc/framework/LocalFileFormatTarget.hpp>
#include <xercesc/framework/LocalFileInputSource.hpp>
#include <xercesc/framework/MemBufInputSource.hpp>
#include <xercesc/sax/HandlerBase.hpp>
#include "App/Application.h"
#include "App/Expression.h"
#include "Base/XMLTools.h"
#include "Metadata.h"
Classes
class MetadataInternal::XMLErrorHandler
Namespaces
MetadataInternal
Macros
#define XERCES_CPP_NAMESPACE_QUALIFIER
Functions
DOMElement * appendSimpleXMLNode (DOMElement *baseNode, const std::string &nodeName, const std::string &nodeContents)
void addAttribute (DOMElement *node, const std::string &key, const std::string &value)
void addAttribute (DOMElement *node, const std::string &key, bool value)
void addAttribute (DOMElement *node, const std::string &key, Meta::DependencyType value)
void addDependencyNode (DOMElement *root, const std::string &name, const Meta::Dependency &depend)
Macro Definition Documentation
XERCES_CPP_NAMESPACE_QUALIFIER
#define XERCES_CPP_NAMESPACE_QUALIFIER
Definition at line 62 of file Metadata.cpp.
Function Documentation
addAttribute() [1/3]
void addAttribute (DOMElement * node, const std::string & key, bool value)
Definition at line 560 of file Metadata.cpp.
References XUTF8Str::unicodeForm().
addAttribute() [2/3]
void addAttribute (DOMElement * node, const std::string & key, const std::string & value)
Definition at line 552 of file Metadata.cpp.
References XUTF8Str::unicodeForm().
Referenced by addDependencyNode().
addAttribute() [3/3]
void addAttribute (DOMElement * node, const std::string & key, Meta::DependencyType value)
Definition at line 570 of file Metadata.cpp.
References App::Meta::addon, App::Meta::automatic, App::Meta::internal, App::Meta::python, and XUTF8Str::unicodeForm().
addDependencyNode()
void addDependencyNode (DOMElement * root, const std::string & name, const Meta::Dependency & depend)
Definition at line 593 of file Metadata.cpp.
References addAttribute(), appendSimpleXMLNode(), App::Meta::Dependency::condition, App::Meta::Dependency::dependencyType, App::Meta::Dependency::optional, App::Meta::Dependency::package, App::Meta::Dependency::version_eq, App::Meta::Dependency::version_gt, App::Meta::Dependency::version_gte, App::Meta::Dependency::version_lt, and App::Meta::Dependency::version_lte.
appendSimpleXMLNode()
DOMElement* appendSimpleXMLNode (DOMElement * baseNode, const std::string & nodeName, const std::string & nodeContents)
Definition at line 536 of file Metadata.cpp.
References toolbit-attributes::doc, and XUTF8Str::unicodeForm().
Referenced by addDependencyNode().