FreeCAD: Curve.cpp File Reference
Curve.cpp File Reference
#include "Curve.h"
#include "Circle.h"
#include "Arc.h"
#include "Area.h"
#include "kurve/geometry.h"
Functions
const Point operator* (const double &d, const Point &p)
static geoff_geometry::Kurve MakeKurve (const CCurve &curve)
static CCurve MakeCCurve (const geoff_geometry::Kurve &k)
static geoff_geometry::Span MakeSpan (const Span &span)
static int GetQuadrant (const Point &v)
static Point QuadrantEndPoint (int i)
double IncludedAngle (const Point &v0, const Point &v1, int dir)
void tangential_arc (const Point &p0, const Point &p1, const Point &v0, Point &c, int &dir)
Function Documentation
GetQuadrant()
static int GetQuadrant (const Point & v) static
Definition at line 1165 of file Curve.cpp.
References TestSpreadsheet::v.
Referenced by Span::GetBox().
IncludedAngle()
double IncludedAngle (const Point & v0, const Point & v1, int dir)
Definition at line 1227 of file Curve.cpp.
References KDL::acos(), SCL.SimpleDataTypes::e, PI, and draftgeoutils.general::v1().
Referenced by Span::IncludedAngle(), and geoff_geometry::IncludedAngle().
MakeCCurve()
static CCurve MakeCCurve (const geoff_geometry::Kurve & k) static
Definition at line 762 of file Curve.cpp.
References SCL.SimpleDataTypes::c, geoff_geometry::Kurve::Get(), SplineSurface::i, geoff_geometry::Kurve::nSpans(), geoff_geometry::spVertex::p, geoff_geometry::spVertex::pc, geoff_geometry::spVertex::type, geoff_geometry::Point::x, and geoff_geometry::Point::y.
Referenced by CCurve::Offset().
MakeKurve()
static geoff_geometry::Kurve MakeKurve (const CCurve & curve) static
Definition at line 748 of file Curve.cpp.
References geoff_geometry::Kurve::Add(), CCurve::m_vertices, and TestSpreadsheet::v.
Referenced by CCurve::Offset().
MakeSpan()
static geoff_geometry::Span MakeSpan (const Span & span) static
Definition at line 774 of file Curve.cpp.
References CVertex::m_c, CVertex::m_p, Span::m_p, CVertex::m_type, Span::m_v, Point::x, and Point::y.
Referenced by Span::Intersect().
operator*()
const Point operator* (const double & d, const Point & p)
Definition at line 11 of file Curve.cpp.
References buildPsets::p.
QuadrantEndPoint()
static Point QuadrantEndPoint (int i) static
Definition at line 1180 of file Curve.cpp.
References SplineSurface::i.
Referenced by Span::GetBox().
tangential_arc()
void tangential_arc (const Point & p0, const Point & p1, const Point & v0, Point & c, int & dir)
Definition at line 1364 of file Curve.cpp.
References SCL.SimpleDataTypes::c, geoff_geometry::tangential_arc(), Point::x, geoff_geometry::Point::x, Point::y, and geoff_geometry::Point::y.
Referenced by TangentialArc().