FreeCAD: ifc2x3.ifcrelreferencedinspatialstructure Class Reference
ifc2x3.ifcrelreferencedinspatialstructure Class Reference
Public Member Functions
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, relatedelements, relatingstructure)
def relatedelements ()
def relatingstructure ()
def wr31 (self)
Public Member Functions inherited from ifc2x3.ifcrelconnects
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description)
Public Member Functions inherited from ifc2x3.ifcroot
def globalid ()
def ownerhistory ()
def name ()
def description ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
relatedelements
relatingstructure
Public Attributes inherited from ifc2x3.ifcroot
globalid
ownerhistory
name
description
Detailed Description
Entity ifcrelreferencedinspatialstructure definition.
:param relatedelements
:type relatedelements:SET(1,None,'ifcproduct', scope = schema_scope)
:param relatingstructure
:type relatingstructure:ifcspatialstructureelement
Definition at line 23608 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcrelreferencedinspatialstructure.__init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, relatedelements, relatingstructure)
Definition at line 23617 of file ifc2x3.py.
Member Function Documentation
relatedelements()
def ifc2x3.ifcrelreferencedinspatialstructure.relatedelements ()
Definition at line 23623 of file ifc2x3.py.
References ifc2x3.ifcrelreferencedinspatialstructure._relatedelements, SCL.TypeChecker.check_type(), and ifc2x3.ifcrelreferencedinspatialstructure.relatedelements.
relatingstructure()
def ifc2x3.ifcrelreferencedinspatialstructure.relatingstructure ()
Definition at line 23637 of file ifc2x3.py.
References ifc2x3.ifcrelreferencedinspatialstructure._relatingstructure, SCL.TypeChecker.check_type(), and ifc2x3.ifcrelreferencedinspatialstructure.relatingstructure.
wr31()
def ifc2x3.ifcrelreferencedinspatialstructure.wr31 (self)
Definition at line 23649 of file ifc2x3.py.
References SCL.Builtin.SIZEOF().
Member Data Documentation
relatedelements
ifc2x3.ifcrelreferencedinspatialstructure.relatedelements
Definition at line 23619 of file ifc2x3.py.
Referenced by ifc2x3.ifcrelreferencedinspatialstructure.relatedelements().
relatingstructure
ifc2x3.ifcrelreferencedinspatialstructure.relatingstructure
Definition at line 23620 of file ifc2x3.py.
Referenced by ifc2x3.ifcrelreferencedinspatialstructure.relatingstructure().
The documentation for this class was generated from the following file:
ifc2x3.py