FreeCAD: Gui::Dialog::ParameterGroupItem Class Reference
Gui::Dialog::ParameterGroupItem Class Reference
#include <DlgParameterImp.h>
Public Member Functions
ParameterGroupItem (ParameterGroupItem *parent, const Base::Reference< ParameterGrp > &hcGrp)
Constructor.
ParameterGroupItem (QTreeWidget *parent, const Base::Reference< ParameterGrp > &hcGrp)
~ParameterGroupItem () override
void setData (int column, int role, const QVariant &value) override
QVariant data (int column, int role) const override
void fillUp ()
Public Attributes
Base::Reference< ParameterGrp > _hcGrp
Detailed Description
The link between the Tree and the shown Label. Every (shown) Label in the FCDocument class get it associated FCTreeLabel which controls the visibility and the functions of the Label.
Author
Jürgen Riegel
Definition at line 253 of file DlgParameterImp.h.
Constructor & Destructor Documentation
ParameterGroupItem() [1/2]
ParameterGroupItem::ParameterGroupItem (ParameterGroupItem * parent, const Base::Reference< ParameterGrp > & hcGrp)
Constructor.
Definition at line 1010 of file DlgParameterImp.cpp.
References fillUp().
Referenced by fillUp().
ParameterGroupItem() [2/2]
ParameterGroupItem::ParameterGroupItem (QTreeWidget * parent, const Base::Reference< ParameterGrp > & hcGrp)
Definition at line 1019 of file DlgParameterImp.cpp.
References fillUp().
~ParameterGroupItem()
ParameterGroupItem::~ParameterGroupItem () override
Definition at line 1028 of file DlgParameterImp.cpp.
References _hcGrp, Base::Subject< MsgType >::ClearObserver(), and Base::Reference< T >::getRefCount().
Member Function Documentation
data()
QVariant ParameterGroupItem::data (int column, int role) const override
Definition at line 1086 of file DlgParameterImp.cpp.
References App::ExpressionParser::column, and Init::parent.
fillUp()
void ParameterGroupItem::fillUp ()
Definition at line 1037 of file DlgParameterImp.cpp.
References _hcGrp, ParameterGrp::GetGroupName(), ParameterGrp::GetGroups(), and ParameterGroupItem().
Referenced by ParameterGroupItem().
setData()
void ParameterGroupItem::setData (int column, int role, const QVariant & value) override
Definition at line 1048 of file DlgParameterImp.cpp.
References App::ExpressionParser::column, Init::parent, and Gui::validateInput().
Member Data Documentation
_hcGrp
Base::Reference<ParameterGrp> Gui::Dialog::ParameterGroupItem::_hcGrp
Definition at line 265 of file DlgParameterImp.h.
Referenced by fillUp(), Gui::Dialog::ParameterGroup::onDeleteSelectedItem(), and ~ParameterGroupItem().
The documentation for this class was generated from the following files:
DlgParameterImp.h
DlgParameterImp.cpp