FreeCAD: Wm4::CylinderFit3< Real > Class Template Reference
Wm4::CylinderFit3< Real > Class Template Reference
#include <Wm4ApprCylinderFit3.h>
Public Member Functions
CylinderFit3 (int iQuantity, const Vector3< Real > *akPoint, Vector3< Real > &rkC, Vector3< Real > &rkU, Real &rfR, Real &rfH, bool bInputsAreInitialGuess)
operator Real ()
Detailed Description
template<class Real>
class Wm4::CylinderFit3< Real >
Definition at line 54 of file Wm4ApprCylinderFit3.h.
Constructor & Destructor Documentation
CylinderFit3()
template<class Real > Wm4::CylinderFit3< Real >::CylinderFit3 (int iQuantity, const Vector3< Real > * akPoint, Vector3< Real > & rkC, Vector3< Real > & rkU, Real & rfR, Real & rfH, bool bInputsAreInitialGuess)
Definition at line 26 of file Wm4ApprCylinderFit3.cpp.
References Wm4::Line3< Real >::Direction, Wm4::Vector3< Real >::Dot(), SplineSurface::i, Wm4::Math< Real >::InvSqrt(), Wm4::Line3< Real >::Origin, and Wm4::OrthogonalLineFit3().
Member Function Documentation
operator Real()
template<class Real > Wm4::CylinderFit3< Real >::operator Real
Definition at line 76 of file Wm4ApprCylinderFit3.cpp.
The documentation for this class was generated from the following files:
Wm4ApprCylinderFit3.h
Wm4ApprCylinderFit3.cpp