FreeCAD: src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonDepsStandaloneFunctions Class Reference
src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonDepsStandaloneFunctions Class Reference
Public Member Functions
def test_call_pip (self, MagicMock mock_run_subprocess)
def test_call_pip_no_python (self, MagicMock mock_get_python_exe)
def test_call_pip_exception_raised (self, MagicMock mock_run_subprocess)
def test_call_pip_splits_results (self, MagicMock mock_run_subprocess)
def test_python_package_updates_are_available (self, MagicMock mock_call_pip)
def test_python_package_updates_are_available_no_results (self, MagicMock mock_call_pip)
def test_python_package_updates_are_available_pip_failure (self, MagicMock mock_call_pip)
def test_parse_pip_list_output_no_input (self)
def test_parse_pip_list_output_all_packages_no_updates (self)
def test_parse_pip_list_output_all_packages_with_updates (self)
Detailed Description
Definition at line 47 of file test_python_deps_gui.py.
Member Function Documentation
test_call_pip()
def src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonDepsStandaloneFunctions.test_call_pip (self, MagicMock mock_run_subprocess)
Definition at line 50 of file test_python_deps_gui.py.
References src.Mod.AddonManager.addonmanager_python_deps_gui.call_pip().
test_call_pip_exception_raised()
def src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonDepsStandaloneFunctions.test_call_pip_exception_raised (self, MagicMock mock_run_subprocess)
Definition at line 63 of file test_python_deps_gui.py.
References src.Mod.AddonManager.addonmanager_python_deps_gui.call_pip().
test_call_pip_no_python()
def src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonDepsStandaloneFunctions.test_call_pip_no_python (self, MagicMock mock_get_python_exe)
Definition at line 57 of file test_python_deps_gui.py.
References src.Mod.AddonManager.addonmanager_python_deps_gui.call_pip().
test_call_pip_splits_results()
def src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonDepsStandaloneFunctions.test_call_pip_splits_results (self, MagicMock mock_run_subprocess)
Definition at line 71 of file test_python_deps_gui.py.
References src.Mod.AddonManager.addonmanager_python_deps_gui.call_pip().
test_parse_pip_list_output_all_packages_no_updates()
def src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonDepsStandaloneFunctions.test_parse_pip_list_output_all_packages_no_updates (self)
Definition at line 104 of file test_python_deps_gui.py.
References src.Mod.AddonManager.addonmanager_python_deps_gui.parse_pip_list_output().
test_parse_pip_list_output_all_packages_with_updates()
def src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonDepsStandaloneFunctions.test_parse_pip_list_output_all_packages_with_updates (self)
Definition at line 117 of file test_python_deps_gui.py.
References src.Mod.AddonManager.addonmanager_python_deps_gui.parse_pip_list_output().
test_parse_pip_list_output_no_input()
def src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonDepsStandaloneFunctions.test_parse_pip_list_output_no_input (self)
Definition at line 100 of file test_python_deps_gui.py.
References src.Mod.AddonManager.addonmanager_python_deps_gui.parse_pip_list_output().
test_python_package_updates_are_available()
def src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonDepsStandaloneFunctions.test_python_package_updates_are_available (self, MagicMock mock_call_pip)
Definition at line 79 of file test_python_deps_gui.py.
References src.Mod.AddonManager.addonmanager_python_deps_gui.python_package_updates_are_available().
test_python_package_updates_are_available_no_results()
def src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonDepsStandaloneFunctions.test_python_package_updates_are_available_no_results (self, MagicMock mock_call_pip)
An empty string is an indication that no updates are available
Definition at line 85 of file test_python_deps_gui.py.
References src.Mod.AddonManager.addonmanager_python_deps_gui.python_package_updates_are_available().
test_python_package_updates_are_available_pip_failure()
def src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui.TestPythonDepsStandaloneFunctions.test_python_package_updates_are_available_pip_failure (self, MagicMock mock_call_pip)
Definition at line 92 of file test_python_deps_gui.py.
References src.Mod.AddonManager.addonmanager_python_deps_gui.python_package_updates_are_available().
The documentation for this class was generated from the following file:
test_python_deps_gui.py