FreeCAD: App::FunctionExpression Class Reference
App::FunctionExpression Class Reference
#include <ExpressionParser.h>
Public Types
enum Function {
NONE, ABS, ACOS, ASIN,
ATAN, ATAN2, CATH, CBRT,
CEIL, COS, COSH, EXP,
FLOOR, HYPOT, LOG, LOG10,
MOD, POW, ROUND, SIN,
SINH, SQRT, TAN, TANH,
TRUNC, VANGLE, VCROSS, VDOT,
VLINEDIST, VLINESEGDIST, VLINEPROJ, VNORMALIZE,
VPLANEDIST, VPLANEPROJ, VSCALE, VSCALEX,
VSCALEY, VSCALEZ, MINVERT, MROTATE,
MROTATEX, MROTATEY, MROTATEZ, MSCALE,
MTRANSLATE, CREATE, LIST, MATRIX,
PLACEMENT, ROTATION, ROTATIONX, ROTATIONY,
ROTATIONZ, STR, PARSEQUANT, TRANSLATIONM,
TUPLE, VECTOR, HIDDENREF, HREF,
AGGREGATES, AVERAGE, COUNT, MAX,
MIN, STDDEV, SUM, LAST
}
Public Types inherited from App::Expression
enum DepOption { DepNormal, DepHidden, DepAll }
using ComponentList = std::vector< Component * >
Public Member Functions
FunctionExpression (const App::DocumentObject *_owner=nullptr, Function _f=NONE, std::string &&name=std::string(), std::vector< Expression * > _args=std::vector< Expression * >())
~FunctionExpression () override
bool isTouched () const override
Expression * simplify () const override
Function getFunction () const
const std::vector< Expression * > & getArgs () const
Public Member Functions inherited from App::UnitExpression
UnitExpression (const App::DocumentObject *_owner=nullptr, const Base::Quantity &_quantity=Base::Quantity(), const std::string &_unitStr=std::string())
~UnitExpression () override
void setUnit (const Base::Quantity &_quantity)
void setQuantity (const Base::Quantity &_quantity)
double getValue () const
const Base::Unit & getUnit () const
const Base::Quantity & getQuantity () const
const std::string getUnitString () const
double getScaler () const
Public Member Functions inherited from App::Expression
Expression (const App::DocumentObject *_owner)
~Expression () override
Expression * eval () const
std::string toString (bool persistent=false, bool checkPriority=false, int indent=0) const
void toString (std::ostream &os, bool persistent=false, bool checkPriority=false, int indent=0) const
Expression * copy () const
virtual int priority () const
void getIdentifiers (std::map< App::ObjectIdentifier, bool > &) const
std::map< App::ObjectIdentifier, bool > getIdentifiers () const
void getDeps (ExpressionDeps &deps, int option=DepNormal) const
ExpressionDeps getDeps (int option=DepNormal) const
std::map< App::DocumentObject *, bool > getDepObjects (std::vector< std::string > *labels=nullptr) const
void getDepObjects (std::map< App::DocumentObject *, bool > &, std::vector< std::string > *labels=nullptr) const
ExpressionPtr importSubNames (const std::map< std::string, std::string > &nameMap) const
ExpressionPtr updateLabelReference (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const
ExpressionPtr replaceObject (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const
bool adjustLinks (const std::set< App::DocumentObject * > &inList)
void visit (ExpressionVisitor &v)
App::DocumentObject * getOwner () const
virtual void addComponent (Component *component)
bool hasComponent () const
boost::any getValueAsAny () const
Py::Object getPyValue () const
bool isSame (const Expression &other, bool checkComment=true) const
Component (const std::string &n)
Component (Expression *e1, Expression *e2, Expression *e3, bool isRange=false)
Component (const ObjectIdentifier::Component &comp)
Component (const Component &other)
~Component ()
Component & operator= (const Component &)=delete
void visit (ExpressionVisitor &v)
bool isTouched () const
void toString (std::ostream &ss, bool persistent) const
Component * copy () const
Component * eval () const
Py::Object get (const Expression *owner, const Py::Object &pyobj) const
void set (const Expression *owner, Py::Object &pyobj, const Py::Object &value) const
void del (const Expression *owner, Py::Object &pyobj) const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static Py::Object evaluate (const Expression *owner, int type, const std::vector< Expression * > &args)
Static Public Member Functions inherited from App::Expression
static Expression * parse (const App::DocumentObject *owner, const std::string &buffer)
static Component * createComponent (const std::string &n)
static Component * createComponent (Expression *e1, Expression *e2=nullptr, Expression *e3=nullptr, bool isRange=false)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions
Py::Object _getPyValue () const override
Expression * _copy () const override
void _visit (ExpressionVisitor &v) override
void _toString (std::ostream &ss, bool persistent, int indent) const override
Protected Member Functions inherited from App::Expression
virtual bool _isIndexable () const
virtual void _getIdentifiers (std::map< App::ObjectIdentifier, bool > &) const
virtual bool _adjustLinks (const std::set< App::DocumentObject * > &, ExpressionVisitor &)
virtual bool _updateElementReference (App::DocumentObject *, bool, ExpressionVisitor &)
virtual bool _relabeledDocument (const std::string &, const std::string &, ExpressionVisitor &)
virtual void _importSubNames (const ObjectIdentifier::SubNameMap &)
virtual void _updateLabelReference (App::DocumentObject *, const std::string &, const char *)
virtual bool _renameObjectIdentifier (const std::map< ObjectIdentifier, ObjectIdentifier > &, const ObjectIdentifier &, ExpressionVisitor &)
virtual void _collectReplacement (std::map< ObjectIdentifier, ObjectIdentifier > &, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const
virtual void _moveCells (const CellAddress &, int, int, ExpressionVisitor &)
virtual void _offsetCells (int, int, ExpressionVisitor &)
Static Protected Member Functions
static Py::Object evalAggregate (const Expression *owner, int type, const std::vector< Expression * > &args)
static Base::Vector3d evaluateSecondVectorArgument (const Expression *expression, const std::vector< Expression * > &arguments)
static double extractLengthValueArgument (const Expression *expression, const std::vector< Expression * > &arguments, int argumentIndex)
static Base::Vector3d extractVectorArgument (const Expression *expression, const std::vector< Expression * > &arguments, int argumentIndex)
static void initialiseObject (const Py::Object *object, const std::vector< Expression * > &arguments, const unsigned long offset=0)
static Py::Object transformFirstArgument (const Expression *expression, const std::vector< Expression * > &arguments, const Base::Matrix4D *transformationMatrix)
static Py::Object translationMatrix (double x, double y, double z)
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes
Function f
std::string fname
std::vector< Expression * > args
Protected Attributes inherited from App::UnitExpression
PyObject * cache = nullptr
Protected Attributes inherited from App::Expression
App::DocumentObject * owner
ComponentList components
Additional Inherited Members
Public Attributes inherited from App::Expression
std::string comment
ObjectIdentifier::Component comp
Expression * e1
Expression * e2
Expression * e3
Detailed Description
Class implementing various functions, e.g sin, cos, etc.
Definition at line 311 of file ExpressionParser.h.
Member Enumeration Documentation
Function
enum App::FunctionExpression::Function
Enumerator
NONE
ABS
ACOS
ASIN
ATAN
ATAN2
CATH
CBRT
CEIL
COS
COSH
EXP
FLOOR
HYPOT
LOG
LOG10
MOD
POW
ROUND
SIN
SINH
SQRT
TAN
TANH
TRUNC
VANGLE
VCROSS
VDOT
VLINEDIST
VLINESEGDIST
VLINEPROJ
VNORMALIZE
VPLANEDIST
VPLANEPROJ
VSCALE
VSCALEX
VSCALEY
VSCALEZ
MINVERT
MROTATE
MROTATEX
MROTATEY
MROTATEZ
MSCALE
MTRANSLATE
CREATE
LIST
MATRIX
PLACEMENT
ROTATION
ROTATIONX
ROTATIONY
ROTATIONZ
STR
PARSEQUANT
TRANSLATIONM
TUPLE
VECTOR
HIDDENREF
HREF
AGGREGATES
AVERAGE
COUNT
MAX
MIN
STDDEV
SUM
LAST
Definition at line 316 of file ExpressionParser.h.
Constructor & Destructor Documentation
FunctionExpression()
FunctionExpression::FunctionExpression (const App::DocumentObject * _owner = nullptr, Function _f = NONE, std::string && name = std::string(), std::vector< Expression * > _args = std::vector<Expression*>()) explicit
Definition at line 1727 of file Expression.cpp.
References ABS, ACOS, AGGREGATES, args, ARGUMENT_THROW, ASIN, ATAN, ATAN2, AVERAGE, CATH, CBRT, CEIL, COS, COSH, COUNT, CREATE, EXP, f, FLOOR, HIDDENREF, HREF, HYPOT, LAST, LIST, LOG, LOG10, MATRIX, MAX, MIN, MINVERT, MOD, MROTATE, MROTATEX, MROTATEY, MROTATEZ, MSCALE, MTRANSLATE, NONE, PARSEQUANT, PARSER_THROW, PLACEMENT, POW, ROTATION, ROTATIONX, ROTATIONY, ROTATIONZ, ROUND, SIN, SINH, SQRT, STDDEV, STR, SUM, TAN, TANH, TRANSLATIONM, TRUNC, TUPLE, VANGLE, VCROSS, VDOT, VECTOR, VLINEDIST, VLINEPROJ, VLINESEGDIST, VNORMALIZE, VPLANEDIST, VPLANEPROJ, VSCALE, VSCALEX, VSCALEY, and VSCALEZ.
Referenced by _copy(), and simplify().
~FunctionExpression()
FunctionExpression::~FunctionExpression () override
Definition at line 1842 of file Expression.cpp.
References args, and SplineSurface::i.
Member Function Documentation
_copy()
Expression * FunctionExpression::_copy () const override protected virtual
Create a copy of the expression.
Returns
A deep copy of the expression.
Reimplemented from App::UnitExpression.
Definition at line 2803 of file Expression.cpp.
References a, args, f, fname, FunctionExpression(), SplineSurface::i, and App::Expression::owner.
_getPyValue()
Py::Object FunctionExpression::_getPyValue () const override protected virtual
Reimplemented from App::UnitExpression.
Definition at line 2610 of file Expression.cpp.
References args, evaluate(), and f.
_toString()
void FunctionExpression::_toString (std::ostream & ss, bool persistent, int indent) const override protected virtual
Create a string representation of the expression.
Returns
A string representing the expression.
Reimplemented from App::UnitExpression.
Definition at line 2653 of file Expression.cpp.
References ABS, ACOS, args, ASIN, ATAN, ATAN2, AVERAGE, CATH, CBRT, CEIL, COS, COSH, COUNT, CREATE, EXP, f, FLOOR, fname, HIDDENREF, HREF, HYPOT, SplineSurface::i, LIST, LOG, LOG10, MATRIX, MAX, MIN, MINVERT, MOD, MROTATE, MROTATEX, MROTATEY, MROTATEZ, MSCALE, MTRANSLATE, PARSEQUANT, PLACEMENT, POW, ROTATION, ROTATIONX, ROTATIONY, ROTATIONZ, ROUND, SIN, SINH, SQRT, STDDEV, STR, SUM, TAN, TANH, TRANSLATIONM, TRUNC, TUPLE, VANGLE, VCROSS, VDOT, VECTOR, VLINEDIST, VLINEPROJ, VLINESEGDIST, VNORMALIZE, VPLANEDIST, VPLANEPROJ, VSCALE, VSCALEX, VSCALEY, and VSCALEZ.
_visit()
void FunctionExpression::_visit (ExpressionVisitor & v) override protected virtual
Reimplemented from App::Expression.
Definition at line 2815 of file Expression.cpp.
References args, f, HIDDENREF, HREF, SplineSurface::i, and TestSpreadsheet::v.
evalAggregate()
Py::Object FunctionExpression::evalAggregate (const Expression * owner, int type, const std::vector< Expression * > & args) static protected
Definition at line 1990 of file Expression.cpp.
References _EXPR_THROW, App::Range::address(), args, AVERAGE, SCL.SimpleDataTypes::c, COUNT, f, Base::BaseClass::getClassTypeId(), App::ExtensionContainer::getPropertyByName(), App::PropertyQuantity::getQuantityValue(), App::RangeExpression::getRange(), App::PropertyInteger::getValue(), App::PropertyFloat::getValue(), MAX, MIN, App::Range::next(), App::Expression::owner, buildPsets::p, App::pyFromQuantity(), App::pyToQuantity(), src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::Quantity, STDDEV, and SUM.
Referenced by evaluate().
evaluate()
Py::Object FunctionExpression::evaluate (const Expression * owner, int type, const std::vector< Expression * > & args) static
Definition at line 2151 of file Expression.cpp.
References _EXPR_THROW, ABS, ACOS, KDL::acos(), AGGREGATES, FreeCADInit::Angle, args, ASIN, KDL::asin(), ATAN, KDL::atan(), ATAN2, KDL::atan2(), CATH, CBRT, CEIL, COS, KDL::cos(), COSH, KDL::cosh(), CREATE, Base::Vector3< float_type >::Cross(), Base::Vector3< float_type >::DistanceToLine(), Base::Vector3< float_type >::DistanceToLineSegment(), Base::Vector3< float_type >::DistanceToPlane(), Base::Vector3< float_type >::Dot(), SCL.SimpleDataTypes::e, App::Expression::e1, App::Expression::e2, App::Expression::e3, evalAggregate(), evaluateSecondVectorArgument(), KDL::exp(), EXP, extractLengthValueArgument(), extractVectorArgument(), f, FLOOR, Base::fmod(), Base::Vector3< float_type >::GetAngle(), Base::BaseClass::getClassTypeId(), App::Expression::getOwner(), App::Expression::getPyValue(), Base::Quantity::getUnit(), Base::Rotation::getValue(), Base::Quantity::getValue(), HIDDENREF, HREF, HYPOT, SplineSurface::i, initialiseObject(), Base::Quantity::isDimensionless(), Base::Quantity::isDimensionlessOrUnit(), FreeCADInit::Length, LIST, KDL::log(), LOG, LOG10, test::m, M_PI, MATRIX, MINVERT, MOD, Base::Matrix4D::move(), MROTATE, MROTATEX, MROTATEY, MROTATEZ, MSCALE, MTRANSLATE, Base::Vector3< float_type >::Normalize(), App::ExpressionParser::parse(), PARSEQUANT, PLACEMENT, Base::pow(), POW, Base::Vector3< float_type >::ProjectToLine(), Base::Vector3< float_type >::ProjectToPlane(), App::pyToQuantity(), src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::Quantity, ROTATION, ROTATIONX, ROTATIONY, ROTATIONZ, ROUND, Base::Vector3< float_type >::Scale(), Base::Matrix4D::scale(), Base::Vector3< float_type >::ScaleX(), Base::Vector3< float_type >::ScaleY(), Base::Vector3< float_type >::ScaleZ(), KDL::sin(), SIN, SINH, KDL::sinh(), SQRT, KDL::sqrt(), STR, src.Mod.Test.testmakeWireString::String, TAN, KDL::tan(), TANH, KDL::tanh(), transformFirstArgument(), TRANSLATIONM, translationMatrix(), TRUNC, TUPLE, Path.Post.scripts.grbl_post::type, unit(), draftgeoutils.general::v1(), VANGLE, VCROSS, VDOT, VECTOR, VLINEDIST, VLINEPROJ, VLINESEGDIST, VNORMALIZE, VPLANEDIST, VPLANEPROJ, VSCALE, VSCALEX, VSCALEY, VSCALEZ, MovieTool::x, and MovieTool::y.
Referenced by _getPyValue().
evaluateSecondVectorArgument()
Base::Vector3d FunctionExpression::evaluateSecondVectorArgument (const Expression * expression, const std::vector< Expression * > & arguments) static protected
Definition at line 2051 of file Expression.cpp.
References _EXPR_THROW, App::Expression::getPyValue(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by evaluate().
extractLengthValueArgument()
double FunctionExpression::extractLengthValueArgument (const Expression * expression, const std::vector< Expression * > & arguments, int argumentIndex) static protected
Definition at line 2121 of file Expression.cpp.
References _EXPR_THROW, App::Expression::getPyValue(), Base::Quantity::getValue(), Base::Quantity::isDimensionlessOrUnit(), FreeCADInit::Length, and App::pyToQuantity().
Referenced by evaluate().
extractVectorArgument()
Base::Vector3d FunctionExpression::extractVectorArgument (const Expression * expression, const std::vector< Expression * > & arguments, int argumentIndex) static protected
Definition at line 2136 of file Expression.cpp.
References _EXPR_THROW.
Referenced by evaluate().
getArgs()
const std::vector<Expression*>& App::FunctionExpression::getArgs () const inline
Definition at line 421 of file ExpressionParser.h.
getFunction()
Function App::FunctionExpression::getFunction () const inline
Definition at line 417 of file ExpressionParser.h.
initialiseObject()
void FunctionExpression::initialiseObject (const Py::Object * object, const std::vector< Expression * > & arguments, const unsigned long offset = 0) static protected
Definition at line 2079 of file Expression.cpp.
References SplineSurface::i.
Referenced by evaluate().
isTouched()
bool FunctionExpression::isTouched () const override virtual
Determine whether the expressions is considered touched, i.e one or both of its arguments are touched.
Returns
True if touched, false if not.
Reimplemented from App::Expression.
Definition at line 1859 of file Expression.cpp.
References args, and SplineSurface::i.
simplify()
Expression * FunctionExpression::simplify () const override virtual
Try to simplify the expression, i.e calculate all constant expressions.
Returns
A simplified expression.
Reimplemented from App::UnitExpression.
Definition at line 2620 of file Expression.cpp.
References a, args, App::Expression::eval(), f, fname, FunctionExpression(), App::Expression::owner, and TestSpreadsheet::v.
transformFirstArgument()
Py::Object FunctionExpression::transformFirstArgument (const Expression * expression, const std::vector< Expression * > & arguments, const Base::Matrix4D * transformationMatrix) static protected
Definition at line 2090 of file Expression.cpp.
References _EXPR_THROW.
Referenced by evaluate().
translationMatrix()
Py::Object FunctionExpression::translationMatrix (double x, double y, double z) static protected
Definition at line 2114 of file Expression.cpp.
References Base::Matrix4D::move(), MovieTool::x, and MovieTool::y.
Referenced by evaluate().
Member Data Documentation
args
std::vector<Expression*> App::FunctionExpression::args protected
Definition at line 451 of file ExpressionParser.h.
Referenced by _copy(), _getPyValue(), _toString(), _visit(), src.Mod.AddonManager.AddonManagerTest.app.mocks.CallCatcher::catch_call(), src.Mod.AddonManager.AddonManagerTest.app.mocks.SignalCatcher::catch_signal(), evalAggregate(), evaluate(), FunctionExpression(), src.Mod.AddonManager.AddonManagerTest.gui.test_update_all_gui.CallInterceptor::intercept(), isTouched(), MengerSponge.MengerThread::run(), simplify(), and ~FunctionExpression().
f
Function App::FunctionExpression::f protected
Function to execute
Definition at line 449 of file ExpressionParser.h.
Referenced by _copy(), _getPyValue(), _toString(), _visit(), evalAggregate(), evaluate(), FunctionExpression(), and simplify().
fname
std::string App::FunctionExpression::fname protected
Definition at line 450 of file ExpressionParser.h.
Referenced by _copy(), _toString(), and simplify().
The documentation for this class was generated from the following files:
ExpressionParser.h
Expression.cpp