FreeCAD: Path.Post.scripts.estlcam_post Namespace Reference
Path.Post.scripts.estlcam_post Namespace Reference
Functions
def processArguments (argstring)
def dump (obj)
def export (objectslist, filename, argstring)
def linenumber ()
def format_outstring (strTable)
def parse (pathobj)
def drill_translate (outstring, cmd, params)
Variables
TOOLTIP
OUTPUT_COMMENTS
OUTPUT_HEADER
OUTPUT_LINE_NUMBERS
OUTPUT_TOOL_CHANGE
TOOL_CHANGE_USE_ALTCMD
SHOW_EDITOR
PRECISION
TRANSLATE_DRILL_CYCLES
PREAMBLE
PRE_OPERATION
POST_OPERATION
POSTAMBLE
LINENR
LINEINCR
DRILL_RETRACT_MODE
MOTION_MODE
UNITS
UNIT_FORMAT
UNIT_SPEED_FORMAT
TOOL_CHANGE_ALTERNATIVE_CMD
TOOL_CHANGE
parser
prog
add_help
action = "store_true",
help = "don't pop up editor before writing output",
default
TOOLTIP_ARGS
MOTION_COMMANDS
RAPID_MOVES
SUPPRESS_COMMANDS
COMMAND_SPACE
CURRENT_X
CURRENT_Y
CURRENT_Z
Function Documentation
drill_translate()
def Path.Post.scripts.estlcam_post.drill_translate (outstring, cmd, params)
Definition at line 496 of file estlcam_post.py.
References Path.Post.scripts.estlcam_post.format_outstring(), Path.Post.scripts.estlcam_post.linenumber(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.estlcam_post.parse().
dump()
def Path.Post.scripts.estlcam_post.dump (obj)
Definition at line 203 of file estlcam_post.py.
Referenced by Gui::GUIApplication.notify(), and App::PropertyPythonObject.toString().
export()
def Path.Post.scripts.estlcam_post.export (objectslist, filename, argstring)
Definition at line 208 of file estlcam_post.py.
References Path.Post.scripts.estlcam_post.linenumber(), Path.Post.scripts.estlcam_post.parse(), Path.Post.scripts.estlcam_post.processArguments(), and Path.Post.scripts.refactored_centroid_post.str.
format_outstring()
def Path.Post.scripts.estlcam_post.format_outstring (strTable)
Definition at line 346 of file estlcam_post.py.
Referenced by Path.Post.scripts.estlcam_post.drill_translate(), and Path.Post.scripts.estlcam_post.parse().
linenumber()
def Path.Post.scripts.estlcam_post.linenumber ()
Definition at line 336 of file estlcam_post.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.estlcam_post.drill_translate(), Path.Post.scripts.estlcam_post.export(), and Path.Post.scripts.estlcam_post.parse().
parse()
def Path.Post.scripts.estlcam_post.parse (pathobj)
Definition at line 356 of file estlcam_post.py.
References Path.Post.scripts.estlcam_post.drill_translate(), Path.Post.scripts.estlcam_post.format_outstring(), Path.Post.scripts.estlcam_post.linenumber(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by Path.Post.scripts.estlcam_post.export().
processArguments()
def Path.Post.scripts.estlcam_post.processArguments (argstring)
Definition at line 155 of file estlcam_post.py.
Referenced by Path.Post.scripts.estlcam_post.export().
Variable Documentation
action
string Path.Post.scripts.estlcam_post.action = "store_true",
Definition at line 107 of file estlcam_post.py.
add_help
Path.Post.scripts.estlcam_post.add_help
Definition at line 106 of file estlcam_post.py.
COMMAND_SPACE
Path.Post.scripts.estlcam_post.COMMAND_SPACE
Definition at line 148 of file estlcam_post.py.
CURRENT_X
Path.Post.scripts.estlcam_post.CURRENT_X
Definition at line 150 of file estlcam_post.py.
CURRENT_Y
Path.Post.scripts.estlcam_post.CURRENT_Y
Definition at line 151 of file estlcam_post.py.
CURRENT_Z
Path.Post.scripts.estlcam_post.CURRENT_Z
Definition at line 152 of file estlcam_post.py.
default
Path.Post.scripts.estlcam_post.default
Definition at line 123 of file estlcam_post.py.
DRILL_RETRACT_MODE
Path.Post.scripts.estlcam_post.DRILL_RETRACT_MODE
Definition at line 86 of file estlcam_post.py.
help
string Path.Post.scripts.estlcam_post.help = "don't pop up editor before writing output",
Definition at line 107 of file estlcam_post.py.
LINEINCR
Path.Post.scripts.estlcam_post.LINEINCR
Definition at line 84 of file estlcam_post.py.
LINENR
Path.Post.scripts.estlcam_post.LINENR
Definition at line 83 of file estlcam_post.py.
MOTION_COMMANDS
Path.Post.scripts.estlcam_post.MOTION_COMMANDS
Definition at line 136 of file estlcam_post.py.
MOTION_MODE
Path.Post.scripts.estlcam_post.MOTION_MODE
Definition at line 90 of file estlcam_post.py.
OUTPUT_COMMENTS
Path.Post.scripts.estlcam_post.OUTPUT_COMMENTS
Definition at line 59 of file estlcam_post.py.
OUTPUT_HEADER
Path.Post.scripts.estlcam_post.OUTPUT_HEADER
Definition at line 60 of file estlcam_post.py.
OUTPUT_LINE_NUMBERS
Path.Post.scripts.estlcam_post.OUTPUT_LINE_NUMBERS
Definition at line 61 of file estlcam_post.py.
OUTPUT_TOOL_CHANGE
Path.Post.scripts.estlcam_post.OUTPUT_TOOL_CHANGE
Definition at line 63 of file estlcam_post.py.
parser
Path.Post.scripts.estlcam_post.parser
Definition at line 106 of file estlcam_post.py.
POST_OPERATION
Path.Post.scripts.estlcam_post.POST_OPERATION
Definition at line 76 of file estlcam_post.py.
POSTAMBLE
Path.Post.scripts.estlcam_post.POSTAMBLE
Definition at line 79 of file estlcam_post.py.
PRE_OPERATION
Path.Post.scripts.estlcam_post.PRE_OPERATION
Definition at line 73 of file estlcam_post.py.
PREAMBLE
Path.Post.scripts.estlcam_post.PREAMBLE
Definition at line 70 of file estlcam_post.py.
PRECISION
Path.Post.scripts.estlcam_post.PRECISION
Definition at line 67 of file estlcam_post.py.
prog
Path.Post.scripts.estlcam_post.prog
Definition at line 106 of file estlcam_post.py.
RAPID_MOVES
Path.Post.scripts.estlcam_post.RAPID_MOVES
Definition at line 146 of file estlcam_post.py.
SHOW_EDITOR
Path.Post.scripts.estlcam_post.SHOW_EDITOR
Definition at line 66 of file estlcam_post.py.
SUPPRESS_COMMANDS
Path.Post.scripts.estlcam_post.SUPPRESS_COMMANDS
Definition at line 147 of file estlcam_post.py.
TOOL_CHANGE
Path.Post.scripts.estlcam_post.TOOL_CHANGE
Definition at line 98 of file estlcam_post.py.
TOOL_CHANGE_ALTERNATIVE_CMD
Path.Post.scripts.estlcam_post.TOOL_CHANGE_ALTERNATIVE_CMD
Definition at line 95 of file estlcam_post.py.
TOOL_CHANGE_USE_ALTCMD
Path.Post.scripts.estlcam_post.TOOL_CHANGE_USE_ALTCMD
Definition at line 64 of file estlcam_post.py.
TOOLTIP
Path.Post.scripts.estlcam_post.TOOLTIP
Definition at line 41 of file estlcam_post.py.
TOOLTIP_ARGS
Path.Post.scripts.estlcam_post.TOOLTIP_ARGS
Definition at line 130 of file estlcam_post.py.
TRANSLATE_DRILL_CYCLES
Path.Post.scripts.estlcam_post.TRANSLATE_DRILL_CYCLES
Definition at line 68 of file estlcam_post.py.
UNIT_FORMAT
Path.Post.scripts.estlcam_post.UNIT_FORMAT
Definition at line 92 of file estlcam_post.py.
UNIT_SPEED_FORMAT
Path.Post.scripts.estlcam_post.UNIT_SPEED_FORMAT
Definition at line 93 of file estlcam_post.py.
UNITS
Path.Post.scripts.estlcam_post.UNITS
Definition at line 91 of file estlcam_post.py.