FreeCAD: BOPTools.SplitFeatures Namespace Reference
BOPTools.SplitFeatures Namespace Reference
Classes
class CommandBooleanFragments
class CommandSlice
class CommandSliceApart
class CommandXOR
class FeatureBooleanFragments
class FeatureSlice
class FeatureXOR
class ViewProviderBooleanFragments
class ViewProviderSlice
class ViewProviderXOR
Functions
def getIconPath (icon_dot_svg)
def makeBooleanFragments (name)
def cmdCreateBooleanFragmentsFeature (name, mode)
def makeSlice (name)
def cmdCreateSliceFeature (name, mode, transaction=True)
def cmdSliceApart ()
def makeXOR (name)
def cmdCreateXORFeature (name)
def addCommands ()
Variables
translate = FreeCAD.Qt.translate
Function Documentation
addCommands()
def BOPTools.SplitFeatures.addCommands ()
Definition at line 546 of file SplitFeatures.py.
cmdCreateBooleanFragmentsFeature()
def BOPTools.SplitFeatures.cmdCreateBooleanFragmentsFeature (name, mode)
cmdCreateBooleanFragmentsFeature(name, mode): implementation of GUI command to create
BooleanFragments feature (GFA). Mode can be "Standard", "Split", or "CompSolid".
Definition at line 136 of file SplitFeatures.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by BOPTools.SplitFeatures.CommandBooleanFragments.Activated().
cmdCreateSliceFeature()
def BOPTools.SplitFeatures.cmdCreateSliceFeature (name, mode, transaction = True)
cmdCreateSliceFeature(name, mode): implementation of GUI command to create
Slice feature. Mode can be "Standard", "Split", or "CompSolid".
Definition at line 278 of file SplitFeatures.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by BOPTools.SplitFeatures.CommandSlice.Activated(), and BOPTools.SplitFeatures.cmdSliceApart().
cmdCreateXORFeature()
def BOPTools.SplitFeatures.cmdCreateXORFeature (name)
cmdCreateXORFeature(name): implementation of GUI command to create
XOR feature (GFA). Mode can be "Standard", "Split", or "CompSolid".
Definition at line 474 of file SplitFeatures.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by BOPTools.SplitFeatures.CommandXOR.Activated().
cmdSliceApart()
def BOPTools.SplitFeatures.cmdSliceApart ()
Definition at line 318 of file SplitFeatures.py.
References BOPTools.SplitFeatures.cmdCreateSliceFeature().
Referenced by BOPTools.SplitFeatures.CommandSliceApart.Activated().
getIconPath()
def BOPTools.SplitFeatures.getIconPath (icon_dot_svg)
Definition at line 48 of file SplitFeatures.py.
Referenced by BOPTools.SplitFeatures.CommandBooleanFragments.GetResources(), BOPTools.SplitFeatures.CommandSlice.GetResources(), BOPTools.SplitFeatures.CommandSliceApart.GetResources(), and BOPTools.SplitFeatures.CommandXOR.GetResources().
makeBooleanFragments()
def BOPTools.SplitFeatures.makeBooleanFragments (name)
makeBooleanFragments(name): makes an BooleanFragments object.
Definition at line 55 of file SplitFeatures.py.
Referenced by femexamples.material_multiple_bendingbeam_fiveboxes.setup(), and femexamples.constraint_section_print.setup().
makeSlice()
def BOPTools.SplitFeatures.makeSlice (name)
makeSlice(name): makes an Slice object.
Definition at line 212 of file SplitFeatures.py.
Referenced by femexamples.constraint_section_print.setup().
makeXOR()
def BOPTools.SplitFeatures.makeXOR (name)
makeXOR(name): makes an XOR object.
Definition at line 398 of file SplitFeatures.py.
Variable Documentation
translate
BOPTools.SplitFeatures.translate = FreeCAD.Qt.translate
Definition at line 44 of file SplitFeatures.py.