FreeCAD: TechDraw::CenterLine Class Reference
TechDraw::CenterLine Class Reference
#include <CenterLine.h>
Public Types
enum CLMODE { VERTICAL, HORIZONTAL, ALIGNED }
enum CLTYPE { FACE, EDGE, VERTEX }
Public Member Functions
CenterLine ()
CenterLine (const CenterLine *cl)
CenterLine (const TechDraw::BaseGeomPtr &bg, const int m=CLMODE::VERTICAL, const double h=0.0, const double v=0.0, const double r=0.0, const double x=0.0)
CenterLine (const Base::Vector3d &p1, const Base::Vector3d &p2, const int m=CLMODE::VERTICAL, const double h=0.0, const double v=0.0, const double r=0.0, const double x=0.0)
~CenterLine () override
TechDraw::BaseGeomPtr BaseGeomPtrFromVectors (Base::Vector3d pt1, Base::Vector3d pt2)
unsigned int getMemSize () const override
void Save (Base::Writer &) const override
void Restore (Base::XMLReader &) override
PyObject * getPyObject () override
CenterLine * copy () const
CenterLine * clone () const
std::string toString () const
TechDraw::BaseGeomPtr scaledGeometry (const TechDraw::DrawViewPart *partFeat)
TechDraw::BaseGeomPtr scaledAndRotatedGeometry (TechDraw::DrawViewPart *partFeat)
void dump (const char *title)
void setShifts (const double h, const double v)
double getHShift () const
double getVShift () const
void setRotate (const double r)
double getRotate () const
void setExtend (const double e)
double getExtend () const
void setFlip (const bool f)
bool getFlip () const
void setType (const int type)
int getType () const
boost::uuids::uuid getTag () const
virtual std::string getTagAsString () const
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static CenterLine * CenterLineBuilder (const TechDraw::DrawViewPart *partFeat, const std::vector< std::string > &subs, const int mode=0, const bool flip=false)
static std::pair< Base::Vector3d, Base::Vector3d > rotatePointsAroundMid (const Base::Vector3d &p1, const Base::Vector3d &p2, const Base::Vector3d &mid, const double rotate)
rotate a notional 2d vector from p1 to p2 around its midpoint by angleDeg
static std::pair< Base::Vector3d, Base::Vector3d > calcEndPointsNoRef (const Base::Vector3d &start, const Base::Vector3d &end, const double scale, const double ext, const double hShift, const double vShift, const double rotate, const double viewAngleDeg)
static std::pair< Base::Vector3d, Base::Vector3d > calcEndPoints (const TechDraw::DrawViewPart *partFeat, const std::vector< std::string > &faceNames, const int mode, const double ext, const double m_hShift, const double m_vShift, const double rotate)
static std::pair< Base::Vector3d, Base::Vector3d > calcEndPoints2Lines (const TechDraw::DrawViewPart *partFeat, const std::vector< std::string > &faceNames, const int vert, const double ext, const double m_hShift, const double m_vShift, const double rotate, const bool flip)
static std::pair< Base::Vector3d, Base::Vector3d > calcEndPoints2Points (const TechDraw::DrawViewPart *partFeat, const std::vector< std::string > &faceNames, const int vert, const double ext, const double m_hShift, const double m_vShift, const double rotate, const bool flip)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes
Base::Vector3d m_start
Base::Vector3d m_end
std::vector< std::string > m_faces
std::vector< std::string > m_edges
std::vector< std::string > m_verts
int m_type
int m_mode
double m_hShift
double m_vShift
double m_rotate
double m_extendBy
LineFormat m_format
bool m_flip2Line
TechDraw::BaseGeomPtr m_geometry
Protected Member Functions
void initialize ()
void createNewTag ()
void assignTag (const TechDraw::CenterLine *cl)
Protected Attributes
boost::uuids::uuid tag
Py::Object PythonObject
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 58 of file CenterLine.h.
Member Enumeration Documentation
CLMODE
enum TechDraw::CenterLine::CLMODE
Enumerator
VERTICAL
HORIZONTAL
ALIGNED
Definition at line 63 of file CenterLine.h.
CLTYPE
enum TechDraw::CenterLine::CLTYPE
Enumerator
FACE
EDGE
VERTEX
Definition at line 69 of file CenterLine.h.
Constructor & Destructor Documentation
CenterLine() [1/4]
CenterLine::CenterLine ()
Definition at line 53 of file CenterLine.cpp.
References ZVALUE::FACE, and VERTICAL.
Referenced by copy().
CenterLine() [2/4]
CenterLine::CenterLine (const CenterLine * cl)
Definition at line 70 of file CenterLine.cpp.
References initialize(), m_end, m_extendBy, m_flip2Line, m_geometry, m_hShift, m_mode, m_rotate, m_start, m_type, and m_vShift.
CenterLine() [3/4]
CenterLine::CenterLine (const TechDraw::BaseGeomPtr & bg, const int m = CLMODE::VERTICAL, const double h = 0.0, const double v = 0.0, const double r = 0.0, const double x = 0.0)
Definition at line 87 of file CenterLine.cpp.
References ZVALUE::FACE, initialize(), test::m, m_end, m_extendBy, m_flip2Line, m_geometry, m_hShift, m_mode, m_rotate, m_start, m_type, m_vShift, TestSpreadsheet::v, and MovieTool::x.
CenterLine() [4/4]
CenterLine::CenterLine (const Base::Vector3d & p1, const Base::Vector3d & p2, const int m = CLMODE::VERTICAL, const double h = 0.0, const double v = 0.0, const double r = 0.0, const double x = 0.0)
Definition at line 109 of file CenterLine.cpp.
References BaseGeomPtrFromVectors(), ZVALUE::FACE, initialize(), test::m, m_end, m_extendBy, m_flip2Line, m_geometry, m_hShift, m_mode, m_rotate, m_start, m_type, m_vShift, TestSpreadsheet::v, and MovieTool::x.
~CenterLine()
CenterLine::~CenterLine () override
Definition at line 133 of file CenterLine.cpp.
Member Function Documentation
assignTag()
void CenterLine::assignTag (const TechDraw::CenterLine * cl) protected
Definition at line 1096 of file CenterLine.cpp.
References Base::Persistence::getTypeId(), and tag.
BaseGeomPtrFromVectors()
TechDraw::BaseGeomPtr CenterLine::BaseGeomPtrFromVectors (Base::Vector3d pt1, Base::Vector3d pt2)
Definition at line 148 of file CenterLine.cpp.
References TechDraw::BaseGeom::baseFactory(), SCL.SimpleDataTypes::e, TechDraw::DrawUtil::invertY(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by CenterLine().
calcEndPoints()
std::pair< Base::Vector3d, Base::Vector3d > CenterLine::calcEndPoints (const TechDraw::DrawViewPart * partFeat, const std::vector< std::string > & faceNames, const int mode, const double ext, const double m_hShift, const double m_vShift, const double rotate) static
Definition at line 465 of file CenterLine.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), create_qrc::ext, TechDraw::ShapeUtils::findCentroidVec(), TechDraw::DrawUtil::fpCompare(), TechDraw::DrawViewPart::getFaceEdgesByIndex(), TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::DrawUtil::getIndexFromName(), TechDraw::DrawViewPart::getProjectionCS(), TechDraw::DrawView::getScale(), App::PropertyQuantity::getValue(), HORIZONTAL, Base::ConsoleSingleton::Message(), TechDraw::ShapeUtils::moveShape(), Base::Vector3< float_type >::Normalize(), result, rotatePointsAroundMid(), TechDraw::ShapeUtils::rotateShape(), TechDraw::DrawView::Rotation, draftfunctions.scale::scale(), TechDraw::DrawUtil::vectorToCompound(), VERTICAL, and Base::ConsoleSingleton::Warning().
Referenced by CenterLineBuilder(), scaledAndRotatedGeometry(), and scaledGeometry().
calcEndPoints2Lines()
std::pair< Base::Vector3d, Base::Vector3d > CenterLine::calcEndPoints2Lines (const TechDraw::DrawViewPart * partFeat, const std::vector< std::string > & faceNames, const int vert, const double ext, const double m_hShift, const double m_vShift, const double rotate, const bool flip) static
Definition at line 587 of file CenterLine.cpp.
References TechDraw::DrawUtil::circulation(), Base::Console(), EWTOLERANCE, create_qrc::ext, TechDraw::DrawUtil::fpCompare(), TechDraw::DrawViewPart::getGeomByIndex(), TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::DrawUtil::getIndexFromName(), TechDraw::DrawView::getScale(), App::PropertyQuantity::getValue(), TechDraw::DrawUtil::invertY(), Base::ConsoleSingleton::Message(), Base::Vector3< float_type >::Normalize(), result, rotatePointsAroundMid(), TechDraw::DrawView::Rotation, draftfunctions.scale::scale(), Base::ConsoleSingleton::Warning(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by CenterLineBuilder(), scaledAndRotatedGeometry(), and scaledGeometry().
calcEndPoints2Points()
std::pair< Base::Vector3d, Base::Vector3d > CenterLine::calcEndPoints2Points (const TechDraw::DrawViewPart * partFeat, const std::vector< std::string > & faceNames, const int vert, const double ext, const double m_hShift, const double m_vShift, const double rotate, const bool flip) static
Definition at line 707 of file CenterLine.cpp.
References ALIGNED, Base::Console(), EWTOLERANCE, create_qrc::ext, TechDraw::DrawUtil::fpCompare(), TechDraw::DrawUtil::getGeomTypeFromName(), TechDraw::DrawUtil::getIndexFromName(), TechDraw::DrawViewPart::getProjVertexByIndex(), TechDraw::DrawView::getScale(), App::PropertyQuantity::getValue(), HORIZONTAL, TechDraw::DrawUtil::invertY(), length(), Base::Vector3< float_type >::Length(), Base::Vector3< float_type >::Normalize(), result, rotatePointsAroundMid(), TechDraw::DrawView::Rotation, draftfunctions.scale::scale(), TestSpreadsheet::v, draftgeoutils.general::v1(), VERTICAL, Base::ConsoleSingleton::Warning(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by CenterLineBuilder(), scaledAndRotatedGeometry(), and scaledGeometry().
calcEndPointsNoRef()
std::pair< Base::Vector3d, Base::Vector3d > CenterLine::calcEndPointsNoRef (const Base::Vector3d & start, const Base::Vector3d & end, const double scale, const double ext, const double hShift, const double vShift, const double rotate, const double viewAngleDeg) static
Definition at line 416 of file CenterLine.cpp.
References create_qrc::ext, TechDraw::DrawUtil::fpCompare(), Base::Vector3< float_type >::Normalize(), result, rotatePointsAroundMid(), and draftfunctions.scale::scale().
Referenced by scaledAndRotatedGeometry(), and scaledGeometry().
CenterLineBuilder()
CenterLine * CenterLine::CenterLineBuilder (const TechDraw::DrawViewPart * partFeat, const std::vector< std::string > & subs, const int mode = 0, const bool flip = false) static
Definition at line 160 of file CenterLine.cpp.
References calcEndPoints(), calcEndPoints2Lines(), calcEndPoints2Points(), Base::Console(), ZVALUE::EDGE, ZVALUE::FACE, Mesh2Shape::faces, TechDraw::DrawUtil::formatVector(), draftgeoutils.general::geomType(), TechDraw::DrawUtil::getGeomTypeFromName(), m_edges, m_faces, m_flip2Line, m_mode, m_type, m_verts, Path.Post.scripts.grbl_post::type, ZVALUE::VERTEX, and Base::ConsoleSingleton::Warning().
clone()
CenterLine * CenterLine::clone () const
Definition at line 1104 of file CenterLine.cpp.
References copy(), and tag.
copy()
CenterLine * CenterLine::copy () const
Definition at line 1040 of file CenterLine.cpp.
References CenterLine(), m_edges, m_end, m_extendBy, m_faces, m_flip2Line, m_format, m_geometry, m_hShift, m_mode, m_rotate, m_start, m_type, m_verts, and m_vShift.
Referenced by clone().
createNewTag()
void CenterLine::createNewTag () protected
Definition at line 1075 of file CenterLine.cpp.
References tag.
Referenced by initialize().
dump()
void CenterLine::dump (const char * title)
Definition at line 388 of file CenterLine.cpp.
References Base::Console(), Base::ConsoleSingleton::Message(), Plot::title(), and toString().
getExtend()
double CenterLine::getExtend () const
Definition at line 1154 of file CenterLine.cpp.
References m_extendBy.
getFlip()
bool CenterLine::getFlip () const
Definition at line 1164 of file CenterLine.cpp.
References m_flip2Line.
getHShift()
double CenterLine::getHShift () const
Definition at line 1129 of file CenterLine.cpp.
References m_hShift.
getMemSize()
unsigned int CenterLine::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
Definition at line 819 of file CenterLine.cpp.
getPyObject()
PyObject * CenterLine::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Definition at line 1113 of file CenterLine.cpp.
References Py::new_reference_to(), and PythonObject.
getRotate()
double CenterLine::getRotate () const
Definition at line 1144 of file CenterLine.cpp.
References m_rotate.
getTag()
boost::uuids::uuid CenterLine::getTag () const
Definition at line 1065 of file CenterLine.cpp.
References tag.
Referenced by getTagAsString().
getTagAsString()
std::string CenterLine::getTagAsString () const virtual
Definition at line 1070 of file CenterLine.cpp.
References getTag().
Referenced by TechDraw::CosmeticExtension::addCenterLine(), TechDraw::CosmeticExtension::deleteCosmeticElements(), TechDraw::CosmeticExtension::getCenterLine(), initialize(), scaledAndRotatedGeometry(), and scaledGeometry().
getType()
int TechDraw::CenterLine::getType () const inline
Definition at line 164 of file CenterLine.h.
Referenced by scaledAndRotatedGeometry().
getVShift()
double CenterLine::getVShift () const
Definition at line 1134 of file CenterLine.cpp.
References m_vShift.
initialize()
void CenterLine::initialize () protected
Definition at line 137 of file CenterLine.cpp.
References TechDraw::CENTERLINE, createNewTag(), TechDraw::ecHARD, getTagAsString(), and m_geometry.
Referenced by CenterLine().
Restore()
void CenterLine::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 920 of file CenterLine.cpp.
References TechDraw::ARCOFCIRCLE, TechDraw::CIRCLE, Base::Console(), src.Mod.AddonManager.NetworkManager::count, SCL.SimpleDataTypes::e, TechDraw::GeometryUtils::edgeFromCircle(), TechDraw::GeometryUtils::edgeFromCircleArc(), TechDraw::GeometryUtils::edgeFromGeneric(), SCL.SimpleDataTypes::f, App::Color::fromHexString(), TechDraw::GENERIC, SplineSurface::i, TechDraw::LineFormat::InvalidLine, m_edges, m_end, m_extendBy, m_faces, m_flip2Line, m_format, m_geometry, m_hShift, m_mode, m_rotate, m_start, m_type, m_verts, m_vShift, buildPsets::p, TechDrawTools.TaskFillTemplateFields::reader, TechDraw::CosmeticVertex::restoreCosmetic(), TechDraw::LineFormat::setColor(), TechDraw::LineFormat::setLineNumber(), TechDraw::LineFormat::setStyle(), TechDraw::LineFormat::setVisible(), TechDraw::LineFormat::setWidth(), Base::ConsoleSingleton::Warning(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by TechDraw::PropertyCenterLineList::Restore().
rotatePointsAroundMid()
std::pair< Base::Vector3d, Base::Vector3d > CenterLine::rotatePointsAroundMid (const Base::Vector3d & p1, const Base::Vector3d & p2, const Base::Vector3d & mid, const double rotate) static
rotate a notional 2d vector from p1 to p2 around its midpoint by angleDeg
Definition at line 395 of file CenterLine.cpp.
References KDL::cos(), M_PI, result, KDL::sin(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by calcEndPoints(), calcEndPoints2Lines(), calcEndPoints2Points(), and calcEndPointsNoRef().
Save()
void CenterLine::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 824 of file CenterLine.cpp.
References TechDraw::ARCOFCIRCLE, App::Color::asHexString(), TechDraw::CIRCLE, Base::Console(), Base::Writer::decInd(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), SCL.SimpleDataTypes::f, TechDraw::GENERIC, TechDraw::LineFormat::getColor(), TechDraw::LineFormat::getLineNumber(), TechDraw::LineFormat::getStyle(), TechDraw::LineFormat::getVisible(), TechDraw::LineFormat::getWidth(), Base::Writer::incInd(), Base::Writer::ind(), m_edges, m_end, m_extendBy, m_faces, m_flip2Line, m_format, m_geometry, m_hShift, m_mode, m_rotate, m_start, m_type, m_verts, m_vShift, Base::ConsoleSingleton::Message(), buildPsets::p, Base::Writer::Stream(), TestSpreadsheet::v, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
scaledAndRotatedGeometry()
TechDraw::BaseGeomPtr CenterLine::scaledAndRotatedGeometry (TechDraw::DrawViewPart * partFeat)
Definition at line 280 of file CenterLine.cpp.
References TechDraw::BaseGeom::baseFactory(), calcEndPoints(), calcEndPoints2Lines(), calcEndPoints2Points(), calcEndPointsNoRef(), TechDraw::CENTERLINE, Base::Console(), SCL.SimpleDataTypes::e, TechDraw::ecHARD, ZVALUE::EDGE, Base::ConsoleSingleton::Error(), ZVALUE::FACE, TechDraw::DrawView::getScale(), getTagAsString(), getType(), App::PropertyQuantity::getValue(), TechDraw::DrawUtil::invertY(), Base::Vector3< float_type >::IsEqual(), m_edges, m_end, m_extendBy, m_faces, m_flip2Line, m_geometry, m_hShift, m_mode, m_rotate, m_start, m_type, m_verts, m_vShift, TechDraw::ShapeUtils::mirrorShape(), TechDraw::ShapeUtils::rotateShape(), TechDraw::DrawView::Rotation, toolbit-attributes::s, TechDraw::DrawUtil::togp_Pnt(), ZVALUE::VERTEX, and Base::ConsoleSingleton::Warning().
Referenced by TechDraw::CosmeticExtension::add1CLToGE().
scaledGeometry()
TechDraw::BaseGeomPtr CenterLine::scaledGeometry (const TechDraw::DrawViewPart * partFeat)
Definition at line 218 of file CenterLine.cpp.
References TechDraw::BaseGeom::baseFactory(), calcEndPoints(), calcEndPoints2Lines(), calcEndPoints2Points(), calcEndPointsNoRef(), TechDraw::CENTERLINE, Base::Console(), SCL.SimpleDataTypes::e, TechDraw::ecHARD, ZVALUE::EDGE, Base::ConsoleSingleton::Error(), ZVALUE::FACE, TechDraw::DrawView::getScale(), getTagAsString(), App::PropertyQuantity::getValue(), Base::Vector3< float_type >::IsEqual(), m_edges, m_end, m_extendBy, m_faces, m_flip2Line, m_geometry, m_hShift, m_mode, m_rotate, m_start, m_type, m_verts, m_vShift, TechDraw::DrawView::Rotation, toolbit-attributes::s, TechDraw::ShapeUtils::scaleShape(), ZVALUE::VERTEX, Base::ConsoleSingleton::Warning(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
setExtend()
void CenterLine::setExtend (const double e)
Definition at line 1149 of file CenterLine.cpp.
References SCL.SimpleDataTypes::e, and m_extendBy.
Referenced by TechDrawGui::TaskCenterLine::createCenterLine().
setFlip()
void CenterLine::setFlip (const bool f)
Definition at line 1159 of file CenterLine.cpp.
References SCL.SimpleDataTypes::f, and m_flip2Line.
setRotate()
void CenterLine::setRotate (const double r)
Definition at line 1139 of file CenterLine.cpp.
References m_rotate.
Referenced by TechDrawGui::TaskCenterLine::createCenterLine().
setShifts()
void CenterLine::setShifts (const double h, const double v)
Definition at line 1123 of file CenterLine.cpp.
References m_hShift, m_vShift, and TestSpreadsheet::v.
Referenced by TechDrawGui::TaskCenterLine::createCenterLine().
setType()
void TechDraw::CenterLine::setType (const int type) inline
Definition at line 163 of file CenterLine.h.
toString()
std::string CenterLine::toString () const
Definition at line 358 of file CenterLine.cpp.
References SCL.SimpleDataTypes::f, m_end, m_extendBy, m_faces, m_flip2Line, m_format, m_hShift, m_mode, m_rotate, m_start, m_type, m_vShift, TechDraw::LineFormat::toString(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by dump().
Member Data Documentation
m_edges
std::vector<std::string> TechDraw::CenterLine::m_edges
Definition at line 171 of file CenterLine.h.
Referenced by CenterLineBuilder(), copy(), Restore(), Save(), scaledAndRotatedGeometry(), scaledGeometry(), and TechDrawGui::TaskCenterLine::updateOrientation().
m_end
Base::Vector3d TechDraw::CenterLine::m_end
Definition at line 167 of file CenterLine.h.
Referenced by CenterLine(), copy(), Restore(), Save(), scaledAndRotatedGeometry(), scaledGeometry(), and toString().
m_extendBy
double TechDraw::CenterLine::m_extendBy
Definition at line 178 of file CenterLine.h.
Referenced by CenterLine(), copy(), execExtendShortenLine(), getExtend(), TechDrawGui::TaskCenterLine::reject(), Restore(), Save(), scaledAndRotatedGeometry(), scaledGeometry(), setExtend(), TechDrawGui::TaskCenterLine::setUiEdit(), and toString().
m_faces
std::vector<std::string> TechDraw::CenterLine::m_faces
Definition at line 170 of file CenterLine.h.
Referenced by CenterLineBuilder(), copy(), Restore(), Save(), scaledAndRotatedGeometry(), scaledGeometry(), and toString().
m_flip2Line
bool TechDraw::CenterLine::m_flip2Line
Definition at line 180 of file CenterLine.h.
Referenced by CenterLine(), CenterLineBuilder(), copy(), TechDrawGui::TaskCenterLine::createCenterLine(), getFlip(), Restore(), Save(), scaledAndRotatedGeometry(), scaledGeometry(), setFlip(), and toString().
m_format
LineFormat TechDraw::CenterLine::m_format
Definition at line 179 of file CenterLine.h.
Referenced by TechDrawGui::_setLineAttributes(), copy(), TechDrawGui::TaskCenterLine::createCenterLine(), TechDrawGui::QGIViewPart::formatGeomFromCenterLine(), TechDrawGui::TaskLineDecor::getFormatAccessPtr(), TechDrawGui::TaskCenterLine::reject(), Restore(), Save(), TechDrawGui::TaskCenterLine::setUiEdit(), and toString().
m_geometry
TechDraw::BaseGeomPtr TechDraw::CenterLine::m_geometry
Definition at line 182 of file CenterLine.h.
Referenced by CenterLine(), copy(), initialize(), Restore(), Save(), scaledAndRotatedGeometry(), and scaledGeometry().
m_hShift
double TechDraw::CenterLine::m_hShift
Definition at line 175 of file CenterLine.h.
Referenced by CenterLine(), copy(), getHShift(), TechDrawGui::TaskCenterLine::reject(), Restore(), Save(), scaledAndRotatedGeometry(), scaledGeometry(), setShifts(), TechDrawGui::TaskCenterLine::setUiEdit(), and toString().
m_mode
int TechDraw::CenterLine::m_mode
Definition at line 174 of file CenterLine.h.
Referenced by CenterLine(), CenterLineBuilder(), copy(), TechDrawGui::TaskCenterLine::reject(), Restore(), Save(), scaledAndRotatedGeometry(), scaledGeometry(), TechDrawGui::TaskCenterLine::setUiEdit(), TechDrawGui::TaskCenterLine::TaskCenterLine(), toString(), and TechDrawGui::TaskCenterLine::updateOrientation().
m_rotate
double TechDraw::CenterLine::m_rotate
Definition at line 177 of file CenterLine.h.
Referenced by CenterLine(), copy(), getRotate(), TechDrawGui::TaskCenterLine::reject(), Restore(), Save(), scaledAndRotatedGeometry(), scaledGeometry(), setRotate(), TechDrawGui::TaskCenterLine::setUiEdit(), and toString().
m_start
Base::Vector3d TechDraw::CenterLine::m_start
Definition at line 166 of file CenterLine.h.
Referenced by CenterLine(), copy(), Restore(), Save(), scaledAndRotatedGeometry(), scaledGeometry(), and toString().
m_type
int TechDraw::CenterLine::m_type
Definition at line 173 of file CenterLine.h.
Referenced by CenterLine(), CenterLineBuilder(), copy(), TechDrawGui::TaskCenterLine::reject(), Restore(), Save(), scaledAndRotatedGeometry(), scaledGeometry(), TechDrawGui::TaskCenterLine::TaskCenterLine(), and toString().
m_verts
std::vector<std::string> TechDraw::CenterLine::m_verts
Definition at line 172 of file CenterLine.h.
Referenced by CenterLineBuilder(), copy(), Restore(), Save(), scaledAndRotatedGeometry(), scaledGeometry(), and TechDrawGui::TaskCenterLine::updateOrientation().
m_vShift
double TechDraw::CenterLine::m_vShift
Definition at line 176 of file CenterLine.h.
Referenced by CenterLine(), copy(), getVShift(), TechDrawGui::TaskCenterLine::reject(), Restore(), Save(), scaledAndRotatedGeometry(), scaledGeometry(), setShifts(), TechDrawGui::TaskCenterLine::setUiEdit(), and toString().
PythonObject
Py::Object TechDraw::CenterLine::PythonObject protected
Definition at line 196 of file CenterLine.h.
Referenced by getPyObject().
tag
boost::uuids::uuid TechDraw::CenterLine::tag protected
Definition at line 194 of file CenterLine.h.
Referenced by assignTag(), clone(), createNewTag(), Dice3DS.dom3ds.ChunkBase::document_html(), Dice3DS.dom3ds.ChunkBase::dump_header(), and getTag().
The documentation for this class was generated from the following files:
CenterLine.h
CenterLine.cpp