FreeCAD: MatGui::ModelSelect Class Reference
MatGui::ModelSelect Class Reference
#include <ModelSelect.h>
Public Member Functions
ModelSelect (QWidget *parent=nullptr, Materials::ModelFilter filter=Materials::ModelFilter_None)
~ModelSelect () override
void onURL (bool checked)
void onDOI (bool checked)
void onFavourite (bool checked)
void onSelectModel (const QItemSelection &selected, const QItemSelection &deselected)
void onDoubleClick (const QModelIndex &index)
const QString & selectedModel () const
void accept () override
void reject () override
Detailed Description
Definition at line 61 of file ModelSelect.h.
Constructor & Destructor Documentation
ModelSelect()
ModelSelect::ModelSelect (QWidget * parent = nullptr, Materials::ModelFilter filter = Materials::ModelFilter_None) explicit
Definition at line 44 of file ModelSelect.cpp.
References accept(), draftgeoutils.intersections::connect(), onDOI(), onDoubleClick(), onFavourite(), onSelectModel(), onURL(), and reject().
~ModelSelect()
ModelSelect::~ModelSelect () override
Definition at line 217 of file ModelSelect.cpp.
Member Function Documentation
accept()
void ModelSelect::accept () override
Definition at line 528 of file ModelSelect.cpp.
Referenced by ModelSelect(), onDoubleClick(), and MaterialEditor.MaterialEditor::verify().
onDOI()
void ModelSelect::onDOI (bool checked)
Definition at line 506 of file ModelSelect.cpp.
Referenced by ModelSelect().
onDoubleClick()
void ModelSelect::onDoubleClick (const QModelIndex & index)
Definition at line 489 of file ModelSelect.cpp.
References accept().
Referenced by ModelSelect().
onFavourite()
void ModelSelect::onFavourite (bool checked)
Definition at line 516 of file ModelSelect.cpp.
Referenced by ModelSelect().
onSelectModel()
void ModelSelect::onSelectModel (const QItemSelection & selected, const QItemSelection & deselected)
Definition at line 464 of file ModelSelect.cpp.
Referenced by ModelSelect().
onURL()
void ModelSelect::onURL (bool checked)
Definition at line 496 of file ModelSelect.cpp.
Referenced by ModelSelect().
reject()
void ModelSelect::reject () override
Definition at line 534 of file ModelSelect.cpp.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and ModelSelect().
selectedModel()
const QString& MatGui::ModelSelect::selectedModel () const inline
Definition at line 75 of file ModelSelect.h.
The documentation for this class was generated from the following files:
ModelSelect.h
ModelSelect.cpp