FreeCAD: MeasureClient.cpp File Reference
MeasureClient.cpp File Reference
#include "PreCompiled.h"
#include <Mod/Part/PartGlobal.h>
#include <string>
#include <TopoDS.hxx>
#include <TopoDS_Vertex.hxx>
#include <TopAbs.hxx>
#include <BRepTools.hxx>
#include <BRep_Tool.hxx>
#include <BRepGProp.hxx>
#include <BRepAdaptor_Curve.hxx>
#include <BRepAdaptor_Surface.hxx>
#include <TopExp.hxx>
#include <GProp_GProps.hxx>
#include <ShapeAnalysis_Edge.hxx>
#include <gp_Circ.hxx>
#include <BRepBuilderAPI_Copy.hxx>
#include <DatumFeature.h>
#include <App/Application.h>
#include <App/Document.h>
#include <App/DocumentObject.h>
#include <App/MeasureManager.h>
#include <App/DocumentObserver.h>
#include <App/GeoFeature.h>
#include <Base/Console.h>
#include <Base/Matrix.h>
#include <Base/Rotation.h>
#include <Base/Vector3D.h>
#include "VectorAdapter.h"
#include "PartFeature.h"
#include "MeasureClient.h"
Functions
static float getLength (TopoDS_Shape &wire)
static float getFaceArea (TopoDS_Shape &face)
static float getRadius (TopoDS_Shape &edge)
TopoDS_Shape getLocatedShape (const App::SubObjectT &subject, Base::Matrix4D *mat=nullptr)
App::MeasureElementType PartMeasureTypeCb (App::DocumentObject *ob, const char *subName)
bool getShapeFromStrings (TopoDS_Shape &shapeOut, const App::SubObjectT &subject, Base::Matrix4D *mat)
Part::VectorAdapter buildAdapter (const App::SubObjectT &subject)
MeasureLengthInfoPtr MeasureLengthHandler (const App::SubObjectT &subject)
MeasureRadiusInfoPtr MeasureRadiusHandler (const App::SubObjectT &subject)
MeasureAreaInfoPtr MeasureAreaHandler (const App::SubObjectT &subject)
MeasurePositionInfoPtr MeasurePositionHandler (const App::SubObjectT &subject)
MeasureAngleInfoPtr MeasureAngleHandler (const App::SubObjectT &subject)
MeasureDistanceInfoPtr MeasureDistanceHandler (const App::SubObjectT &subject)
Function Documentation
buildAdapter()
Part::VectorAdapter buildAdapter (const App::SubObjectT & subject)
Definition at line 186 of file MeasureClient.cpp.
References Base::Console(), Part::VectorAdapter::convert(), FirstVertex(), App::SubObjectT::getElementName(), getLocatedShape(), App::DocumentObjectT::getObjectName(), LastVertex(), Base::ConsoleSingleton::Message(), and TestSpreadsheet::v.
Referenced by MeasureAngleHandler().
getFaceArea()
static float getFaceArea (TopoDS_Shape & face) static
Definition at line 74 of file MeasureClient.cpp.
Referenced by MeasureAreaHandler().
getLength()
static float getLength (TopoDS_Shape & wire) static
Definition at line 68 of file MeasureClient.cpp.
Referenced by App::Meta::GenericMetadata::GenericMetadata(), src.Mod.Show.SceneDetails.ObjectClipPlane::getClipPlaneNode(), src.Mod.Show.SceneDetails.Pickability::getPickStyleNode(), Gui::SoFCPathAnnotation::GLRenderBelowPath(), MeasureLengthHandler(), and draftviewproviders.view_base.ViewProviderDraft::onChanged().
getLocatedShape()
TopoDS_Shape getLocatedShape (const App::SubObjectT & subject, Base::Matrix4D * mat = nullptr)
Definition at line 94 of file MeasureClient.cpp.
References Base::Console(), Base::Persistence::getClassTypeId(), App::SubObjectT::getElementName(), App::GeoFeature::getGlobalPlacement(), App::DocumentObject::getNameInDocument(), App::DocumentObjectT::getObject(), Part::TopoShape::getShape(), App::SubObjectT::getSubName(), App::SubObjectT::getSubObjectList(), Part::TopoShape::getSubShape(), Part::Feature::getTopoShape(), Base::Persistence::getTypeId(), Base::Type::isDerivedFrom(), Part::TopoShape::isNull(), Base::ConsoleSingleton::Log(), and Data::ComplexGeoData::setPlacement().
Referenced by buildAdapter(), TechDraw::ReferenceEntry::getGeometry(), TechDraw::ShapeExtractor::getShapes(), TechDraw::ShapeExtractor::getShapes2d(), TechDraw::ShapeExtractor::getShapesFromObject(), MeasureAngleHandler(), MeasureAreaHandler(), MeasureDistanceHandler(), MeasureLengthHandler(), MeasurePositionHandler(), and MeasureRadiusHandler().
getRadius()
static float getRadius (TopoDS_Shape & edge) static
Definition at line 80 of file MeasureClient.cpp.
Referenced by MeasureRadiusHandler(), draftguitools.gui_offset.Offset::numericRadius(), and draftfunctions.offset::offset().
getShapeFromStrings()
bool getShapeFromStrings (TopoDS_Shape & shapeOut, const App::SubObjectT & subject, Base::Matrix4D * mat)
Definition at line 175 of file MeasureClient.cpp.
References App::SubObjectT::getElementName(), App::DocumentObjectT::getObject(), and Part::Feature::getShape().
MeasureAngleHandler()
MeasureAngleInfoPtr MeasureAngleHandler (const App::SubObjectT & subject)
Definition at line 349 of file MeasureClient.cpp.
References buildAdapter(), Base::Console(), App::SubObjectT::getElementName(), getLocatedShape(), App::DocumentObjectT::getObjectName(), Path.Log::info(), Part::VectorAdapter::isValid(), Base::ConsoleSingleton::Message(), Base::Vector3< float_type >::Set(), and SurfaceTests.TestBlendCurve::vec.
Referenced by Part::MeasureClient::reportAngleCB().
MeasureAreaHandler()
MeasureAreaInfoPtr MeasureAreaHandler (const App::SubObjectT & subject)
Definition at line 300 of file MeasureClient.cpp.
References Base::Console(), App::SubObjectT::getElementName(), getFaceArea(), getLocatedShape(), App::DocumentObjectT::getObjectName(), and Base::ConsoleSingleton::Message().
Referenced by Part::MeasureClient::reportAreaCB().
MeasureDistanceHandler()
MeasureDistanceInfoPtr MeasureDistanceHandler (const App::SubObjectT & subject)
Definition at line 388 of file MeasureClient.cpp.
References Base::Console(), App::SubObjectT::getElementName(), getLocatedShape(), App::DocumentObjectT::getObjectName(), and Base::ConsoleSingleton::Message().
Referenced by Part::MeasureClient::reportDistanceCB().
MeasureLengthHandler()
MeasureLengthInfoPtr MeasureLengthHandler (const App::SubObjectT & subject)
Definition at line 239 of file MeasureClient.cpp.
References Base::Console(), App::SubObjectT::getElementName(), getLength(), getLocatedShape(), App::DocumentObjectT::getObjectName(), and Base::ConsoleSingleton::Message().
Referenced by Part::MeasureClient::reportLengthCB().
MeasurePositionHandler()
MeasurePositionInfoPtr MeasurePositionHandler (const App::SubObjectT & subject)
Definition at line 328 of file MeasureClient.cpp.
References Base::Console(), App::SubObjectT::getElementName(), getLocatedShape(), App::DocumentObjectT::getObjectName(), and Base::ConsoleSingleton::Message().
Referenced by Part::MeasureClient::reportPositionCB().
MeasureRadiusHandler()
MeasureRadiusInfoPtr MeasureRadiusHandler (const App::SubObjectT & subject)
Definition at line 264 of file MeasureClient.cpp.
References FirstVertex(), getLocatedShape(), and getRadius().
Referenced by Part::MeasureClient::reportRadiusCB().
PartMeasureTypeCb()
App::MeasureElementType PartMeasureTypeCb (App::DocumentObject * ob, const char * subName)
Definition at line 122 of file MeasureClient.cpp.
References App::CIRCLE, Base::Console(), App::CURVE, App::CYLINDER, Base::Type::fromName(), App::DocumentObject::getNameInDocument(), Part::Feature::getShape(), Base::Persistence::getTypeId(), App::INVALID, Base::Type::isDerivedFrom(), App::LINE, App::LINESEGMENT, Base::ConsoleSingleton::Message(), App::PLANE, App::POINT, and App::Volume.
Referenced by Part::MeasureClient::initialize().