FreeCAD: Gui::ExpressionParameter Class Reference
Gui::ExpressionParameter Class Reference
#include <ExpressionCompleter.h>
Public Member Functions
bool isCaseSensitive () const
bool isExactMatch () const
Static Public Member Functions
static ExpressionParameter * instance ()
Detailed Description
Definition at line 134 of file ExpressionCompleter.h.
Member Function Documentation
instance()
ExpressionParameter * ExpressionParameter::instance () static
Definition at line 1158 of file ExpressionCompleter.cpp.
Referenced by Gui::Dialog::DlgPropertyLink::DlgPropertyLink(), and Gui::TreePanel::TreePanel().
isCaseSensitive()
bool ExpressionParameter::isCaseSensitive () const
Definition at line 1164 of file ExpressionCompleter.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), and App::Application::GetParameterGroupByPath().
isExactMatch()
bool ExpressionParameter::isExactMatch () const
Definition at line 1171 of file ExpressionCompleter.cpp.
References App::GetApplication(), ParameterGrp::GetBool(), and App::Application::GetParameterGroupByPath().
Referenced by Gui::TreePanel::TreePanel().
The documentation for this class was generated from the following files:
ExpressionCompleter.h
ExpressionCompleter.cpp