FreeCAD: App::DocumentWeakPtrT Class Reference
App::DocumentWeakPtrT Class Reference
The DocumentWeakPtrT class.
#include <DocumentObserver.h>
Classes
class Private
Public Member Functions
DocumentWeakPtrT (App::Document *) noexcept
~DocumentWeakPtrT ()
void reset () noexcept
reset Releases the reference to the managed object. After the call *this manages no object.
bool expired () const noexcept
expired
App::Document * operator* () const noexcept
operator *
App::Document * operator-> () const noexcept
operator ->
DocumentWeakPtrT (const DocumentWeakPtrT &)=delete
DocumentWeakPtrT & operator= (const DocumentWeakPtrT &)=delete
Detailed Description
The DocumentWeakPtrT class.
Definition at line 348 of file App/DocumentObserver.h.
Constructor & Destructor Documentation
DocumentWeakPtrT() [1/2]
DocumentWeakPtrT::DocumentWeakPtrT (App::Document * doc) explicit noexcept
Definition at line 717 of file App/DocumentObserver.cpp.
~DocumentWeakPtrT()
DocumentWeakPtrT::~DocumentWeakPtrT () default
DocumentWeakPtrT() [2/2]
App::DocumentWeakPtrT::DocumentWeakPtrT (const DocumentWeakPtrT &) delete
Member Function Documentation
expired()
bool DocumentWeakPtrT::expired () const noexcept
expired
Returns
true if the managed object has already been deleted, false otherwise.
Definition at line 728 of file App/DocumentObserver.cpp.
operator*()
App::Document * DocumentWeakPtrT::operator* () const noexcept
operator *
Returns
pointer to the document
Definition at line 733 of file App/DocumentObserver.cpp.
operator->()
App::Document * DocumentWeakPtrT::operator-> () const noexcept
operator ->
Returns
pointer to the document
Definition at line 738 of file App/DocumentObserver.cpp.
operator=()
DocumentWeakPtrT& App::DocumentWeakPtrT::operator= (const DocumentWeakPtrT &) delete
reset()
void DocumentWeakPtrT::reset () noexcept
reset Releases the reference to the managed object. After the call *this manages no object.
Definition at line 723 of file App/DocumentObserver.cpp.
Referenced by ArchVRM.Renderer::__init__(), draftguitools.gui_trackers.gridTracker::set(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testAll(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
The documentation for this class was generated from the following files:
App/DocumentObserver.h
App/DocumentObserver.cpp