FreeCAD: TestGui::UnitTestDialogPy Class Reference
TestGui::UnitTestDialogPy Class Reference
#include <UnitTestPy.h>
Public Member Functions
UnitTestDialogPy ()
~UnitTestDialogPy () override
Py::Object repr () override
Py::Object getattr (const char *) override
int setattr (const char *, const Py::Object &) override
Py::Object clearErrorList (const Py::Tuple &)
Py::Object insertError (const Py::Tuple &)
Py::Object setUnitTest (const Py::Tuple &)
Py::Object getUnitTest (const Py::Tuple &)
Py::Object setStatusText (const Py::Tuple &)
Py::Object setProgressFrac (const Py::Tuple &)
Py::Object errorDialog (const Py::Tuple &)
Py::Object setRunCount (const Py::Tuple &)
Py::Object setFailCount (const Py::Tuple &)
Py::Object setErrorCount (const Py::Tuple &)
Py::Object setRemainCount (const Py::Tuple &)
Py::Object updateGUI (const Py::Tuple &)
Py::Object addUnitTest (const Py::Tuple &)
Py::Object clearUnitTests (const Py::Tuple &)
Static Public Member Functions
static void init_type ()
Detailed Description
Definition at line 55 of file UnitTestPy.h.
Constructor & Destructor Documentation
UnitTestDialogPy()
UnitTestDialogPy::UnitTestDialogPy () default
~UnitTestDialogPy()
UnitTestDialogPy::~UnitTestDialogPy () override default
Member Function Documentation
addUnitTest()
Py::Object UnitTestDialogPy::addUnitTest (const Py::Tuple & args)
Definition at line 213 of file UnitTestPy.cpp.
References TestGui::UnitTestDialog::addUnitTest(), toolbit-attributes::args, and TestGui::UnitTestDialog::instance().
Referenced by init_type().
clearErrorList()
Py::Object UnitTestDialogPy::clearErrorList (const Py::Tuple & args)
Definition at line 84 of file UnitTestPy.cpp.
References toolbit-attributes::args, TestGui::UnitTestDialog::clearErrorList(), and TestGui::UnitTestDialog::instance().
Referenced by init_type().
clearUnitTests()
Py::Object UnitTestDialogPy::clearUnitTests (const Py::Tuple & args)
Definition at line 225 of file UnitTestPy.cpp.
References toolbit-attributes::args, TestGui::UnitTestDialog::clearUnitTests(), and TestGui::UnitTestDialog::instance().
Referenced by init_type().
errorDialog()
Py::Object UnitTestDialogPy::errorDialog (const Py::Tuple & args)
Definition at line 153 of file UnitTestPy.cpp.
References toolbit-attributes::args, TestGui::UnitTestDialog::instance(), TestGui::UnitTestDialog::showErrorDialog(), and Plot::title().
Referenced by init_type().
getattr()
Py::Object UnitTestDialogPy::getattr (const char * attr) override
Definition at line 74 of file UnitTestPy.cpp.
getUnitTest()
Py::Object UnitTestDialogPy::getUnitTest (const Py::Tuple & args)
Definition at line 117 of file UnitTestPy.cpp.
References toolbit-attributes::args, TestGui::UnitTestDialog::instance(), and src.Mod.Test.testmakeWireString::String.
Referenced by init_type().
init_type()
void UnitTestDialogPy::init_type () static
Definition at line 38 of file UnitTestPy.cpp.
References addUnitTest(), clearErrorList(), clearUnitTests(), errorDialog(), getUnitTest(), insertError(), setErrorCount(), setFailCount(), setProgressFrac(), setRemainCount(), setRunCount(), setStatusText(), setUnitTest(), and updateGUI().
Referenced by TestGui::Module::Module().
insertError()
Py::Object UnitTestDialogPy::insertError (const Py::Tuple & args)
Definition at line 93 of file UnitTestPy.cpp.
References toolbit-attributes::args, TestGui::UnitTestDialog::insertError(), and TestGui::UnitTestDialog::instance().
Referenced by init_type().
repr()
Py::Object UnitTestDialogPy::repr () override
Definition at line 69 of file UnitTestPy.cpp.
References src.Mod.Test.testmakeWireString::String.
setattr()
int UnitTestDialogPy::setattr (const char * attr, const Py::Object & value) override
Definition at line 79 of file UnitTestPy.cpp.
setErrorCount()
Py::Object UnitTestDialogPy::setErrorCount (const Py::Tuple & args)
Definition at line 184 of file UnitTestPy.cpp.
References toolbit-attributes::args, src.Mod.AddonManager.NetworkManager::count, TestGui::UnitTestDialog::instance(), and TestGui::UnitTestDialog::setErrorCount().
Referenced by init_type().
setFailCount()
Py::Object UnitTestDialogPy::setFailCount (const Py::Tuple & args)
Definition at line 174 of file UnitTestPy.cpp.
References toolbit-attributes::args, src.Mod.AddonManager.NetworkManager::count, TestGui::UnitTestDialog::instance(), and TestGui::UnitTestDialog::setFailCount().
Referenced by init_type().
setProgressFrac()
Py::Object UnitTestDialogPy::setProgressFrac (const Py::Tuple & args)
Definition at line 136 of file UnitTestPy.cpp.
References toolbit-attributes::args, TestGui::UnitTestDialog::instance(), and TestGui::UnitTestDialog::setProgressFraction().
Referenced by init_type().
setRemainCount()
Py::Object UnitTestDialogPy::setRemainCount (const Py::Tuple & args)
Definition at line 194 of file UnitTestPy.cpp.
References toolbit-attributes::args, src.Mod.AddonManager.NetworkManager::count, TestGui::UnitTestDialog::instance(), and TestGui::UnitTestDialog::setRemainCount().
Referenced by init_type().
setRunCount()
Py::Object UnitTestDialogPy::setRunCount (const Py::Tuple & args)
Definition at line 164 of file UnitTestPy.cpp.
References toolbit-attributes::args, src.Mod.AddonManager.NetworkManager::count, TestGui::UnitTestDialog::instance(), and TestGui::UnitTestDialog::setRunCount().
Referenced by init_type().
setStatusText()
Py::Object UnitTestDialogPy::setStatusText (const Py::Tuple & args)
Definition at line 125 of file UnitTestPy.cpp.
References toolbit-attributes::args, TestGui::UnitTestDialog::instance(), and TestGui::UnitTestDialog::setStatusText().
Referenced by init_type().
setUnitTest()
Py::Object UnitTestDialogPy::setUnitTest (const Py::Tuple & args)
Definition at line 106 of file UnitTestPy.cpp.
References toolbit-attributes::args, TestGui::UnitTestDialog::instance(), and TestGui::UnitTestDialog::setUnitTest().
Referenced by init_type().
updateGUI()
Py::Object UnitTestDialogPy::updateGUI (const Py::Tuple & args)
Definition at line 204 of file UnitTestPy.cpp.
References toolbit-attributes::args.
Referenced by init_type().
The documentation for this class was generated from the following files:
UnitTestPy.h
UnitTestPy.cpp