FreeCAD: Gui::GUIApplication Class Reference
Gui::GUIApplication Class Reference
#include <GuiApplication.h>
Public Slots
void commitData (QSessionManager &manager)
Public Member Functions
GUIApplication (int &argc, char **argv)
~GUIApplication () override
bool notify (QObject *receiver, QEvent *event) override
Public Member Functions inherited from Gui::GUIApplicationNativeEventAware
GUIApplicationNativeEventAware (int &argc, char *argv[])
~GUIApplicationNativeEventAware () override
void initSpaceball (QMainWindow *window)
bool isSpaceballPresent () const
void setSpaceballPresent (bool present)
bool processSpaceballEvent (QObject *object, QEvent *event)
void postMotionEvent (std::vector< int > motionDataArray)
void postButtonEvent (int buttonNumber, int buttonPress)
Public Attributes
std::shared_ptr< Base::SystemExitException > caughtException
Pointer to exceptions caught in Qt event handler.
Protected Member Functions
bool event (QEvent *event) override
Detailed Description
Override QCoreApplication::notify() to fetch exceptions in Qt widgets properly that are not handled in the event handler or slot.
Definition at line 39 of file GuiApplication.h.
Constructor & Destructor Documentation
GUIApplication()
GUIApplication::GUIApplication (int & argc, char ** argv) explicit
Definition at line 59 of file GuiApplication.cpp.
References commitData(), and draftgeoutils.intersections::connect().
~GUIApplication()
GUIApplication::~GUIApplication () override default
Member Function Documentation
commitData
void GUIApplication::commitData (QSessionManager & manager) slot
Definition at line 142 of file GuiApplication.cpp.
References App::Application::closeAllDocuments(), App::GetApplication(), and Gui::getMainWindow().
Referenced by GUIApplication().
event()
bool GUIApplication::event (QEvent * event) override protected
Definition at line 159 of file GuiApplication.cpp.
References DrawingExample::file, Gui::getMainWindow(), Gui::Application::Instance, and Gui::Application::open().
Referenced by notify().
notify()
bool GUIApplication::notify (QObject * receiver, QEvent * event) override
Make forwarding events exception-safe and get more detailed information where an unhandled exception comes from.
Definition at line 71 of file GuiApplication.cpp.
References Spaceball::ButtonEvent::ButtonEventType, caughtException, Base::Console(), Path.Post.scripts.estlcam_post::dump(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), event(), Base::ConsoleSingleton::Log(), Spaceball::MotionEvent::MotionEventType, femsolver.signal::notify(), Gui::GUIApplicationNativeEventAware::processSpaceballEvent(), Path.Post.scripts.refactored_centroid_post::str, and src.Mod.PartDesign.fcgear.svggear::w.
Member Data Documentation
caughtException
std::shared_ptr<Base::SystemExitException> Gui::GUIApplication::caughtException
Pointer to exceptions caught in Qt event handler.
Definition at line 54 of file GuiApplication.h.
Referenced by notify().
The documentation for this class was generated from the following files:
GuiApplication.h
GuiApplication.cpp