FreeCAD: Gui::PythonConsole Class Reference
Gui::PythonConsole Class Reference
#include <PythonConsole.h>
Public Types
enum Prompt { Complete = 0, Incomplete = 1, Flush = 2, Special = 3 }
Public Slots
void onSaveHistoryAs ()
void onInsertFileName ()
void onCopyHistory ()
void onCopyCommand ()
void onClearConsole ()
void onFlush ()
Signals
void pendingSource ()
Signals inherited from Gui::TextEdit
void showSearchBar ()
void findNext ()
void findPrevious ()
Public Member Functions
PythonConsole (QWidget *parent=nullptr)
~PythonConsole () override
void OnChange (Base::Subject< const char * > &rCaller, const char *rcReason) override
void printStatement (const QString &cmd)
QString readline ()
Public Member Functions inherited from Gui::PythonTextEditor
PythonTextEditor (QWidget *parent=nullptr)
~PythonTextEditor () override
Public Member Functions inherited from Gui::TextEditor
TextEditor (QWidget *parent=nullptr)
~TextEditor () override
void setSyntaxHighlighter (SyntaxHighlighter *)
void OnChange (Base::Subject< const char * > &rCaller, const char *rcReason) override
void lineNumberAreaPaintEvent (QPaintEvent *)
int lineNumberAreaWidth ()
void setVisibleLineNumbers (bool value)
bool isVisibleLineNumbers () const
void setEnabledHighlightCurrentLine (bool value)
bool isEnabledHighlightCurrentLine () const
Public Member Functions inherited from Gui::TextEdit
TextEdit (QWidget *parent=nullptr)
~TextEdit () override
Public Member Functions inherited from Gui::WindowParameter
WindowParameter (const char *name)
~WindowParameter () override
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
ParameterGrp::handle getWindowParameter ()
return the parameter group of this window
Protected Member Functions
void keyPressEvent (QKeyEvent *e) override
void showEvent (QShowEvent *e) override
void dropEvent (QDropEvent *e) override
void dragEnterEvent (QDragEnterEvent *e) override
void dragMoveEvent (QDragMoveEvent *e) override
void changeEvent (QEvent *e) override
void mouseReleaseEvent (QMouseEvent *e) override
void overrideCursor (const QString &txt)
void contextMenuEvent (QContextMenuEvent *e) override
bool canInsertFromMimeData (const QMimeData *source) const override
QMimeData * createMimeDataFromSelection () const override
void insertFromMimeData (const QMimeData *source) override
QTextCursor inputBegin () const
Protected Member Functions inherited from Gui::PythonTextEditor
void keyPressEvent (QKeyEvent *) override
Protected Member Functions inherited from Gui::TextEditor
void resizeEvent (QResizeEvent *e) override
QWidget * getMarker () const
virtual void drawMarker (int line, int x, int y, QPainter *)
Protected Member Functions inherited from Gui::TextEdit
void keyPressEvent (QKeyEvent *) override
void wheelEvent (QWheelEvent *e) override
Protected Member Functions inherited from Gui::WindowParameter
bool setGroupName (const char *name)
template<typename S , typename T >
void setSlotParamChanged (S slot, T *obsPtr)
connect slot to ParameterManager signal
Friends
class PythonStdout
class PythonStderr
Additional Inherited Members
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter ()
get the parameters
Detailed Description
Definition at line 100 of file PythonConsole.h.
Member Enumeration Documentation
Prompt
enum Gui::PythonConsole::Prompt
Enumerator
Complete
Incomplete
Flush
Special
Definition at line 105 of file PythonConsole.h.
Constructor & Destructor Documentation
PythonConsole()
PythonConsole::PythonConsole (QWidget * parent = nullptr) explicit
Constructs a PythonConsole which is a child of 'parent'.
Definition at line 422 of file PythonConsole.cpp.
References Gui::PythonConsoleP::_stderrPy, Gui::PythonConsoleP::_stdin, Gui::PythonConsoleP::_stdinPy, Gui::PythonConsoleP::_stdoutPy, Base::Subject< MsgType >::Attach(), Gui::PythonConsoleP::callTipsList, Complete, App::Application::Config(), draftgeoutils.intersections::connect(), SCL.SimpleDataTypes::e, Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), Gui::WindowParameter::getWindowParameter(), Gui::PythonConsoleP::hGrpSettings, Gui::PythonConsoleP::info, Gui::PythonConsoleP::interactive, Gui::PythonConsoleP::interpreter, geoff_geometry::Normal(), ParameterGrp::NotifyAll(), Gui::PythonConsoleP::output, PythonStderr, PythonStdout, Gui::TextEditor::setEnabledHighlightCurrentLine(), Gui::TextEditor::setSyntaxHighlighter(), Gui::TextEditor::setVisibleLineNumbers(), and Dice3DS::version.
~PythonConsole()
PythonConsole::~PythonConsole () override
Destroys the object and frees any allocated resources
Definition at line 497 of file PythonConsole.cpp.
References Gui::PythonConsoleP::_stderrPy, Gui::PythonConsoleP::_stdinPy, Gui::PythonConsoleP::_stdoutPy, Base::Subject< MsgType >::Detach(), Gui::PythonConsoleP::hGrpSettings, and Gui::PythonConsoleP::interpreter.
Member Function Documentation
canInsertFromMimeData()
bool PythonConsole::canInsertFromMimeData (const QMimeData * source) const override protected
Definition at line 1091 of file PythonConsole.cpp.
References create_qrc::ext, and Path.Log::info().
Referenced by contextMenuEvent().
changeEvent()
void PythonConsole::changeEvent (QEvent * e) override protected
Definition at line 960 of file PythonConsole.cpp.
References draftgeoutils.intersections::connect(), SCL.SimpleDataTypes::e, ParameterGrp::GetUnsigned(), Gui::WindowParameter::getWindowParameter(), and ParameterGrp::SetUnsigned().
contextMenuEvent()
void PythonConsole::contextMenuEvent (QContextMenuEvent * e) override protected
Pops up the context menu with some extensions
Definition at line 1322 of file PythonConsole.cpp.
References a, canInsertFromMimeData(), Drawing::copy(), Gui::cursorBeyond(), SCL.SimpleDataTypes::e, ParameterGrp::GetBool(), Gui::PythonConsoleP::hGrpSettings, Gui::PythonConsoleP::history, inputBegin(), Gui::ConsoleHistory::isEmpty(), NavigationIndicatorGui::menu, onClearConsole(), onCopyCommand(), onCopyHistory(), onInsertFileName(), onSaveHistoryAs(), and ParameterGrp::SetBool().
createMimeDataFromSelection()
QMimeData * PythonConsole::createMimeDataFromSelection () const override protected
Definition at line 1168 of file PythonConsole.cpp.
References SCL.SimpleDataTypes::b, Gui::PythonConsoleP::Command, SCL.SimpleDataTypes::e, Gui::PythonConsoleP::History, Gui::PythonConsoleP::history, Gui::SyntaxHighlighter::maximumUserState(), Gui::PythonConsoleP::Normal, RobotExample::pos, toolbit-attributes::s, Gui::stripPromptFrom(), Gui::PythonConsoleP::type, and Gui::ConsoleHistory::values().
Referenced by onCopyHistory().
dragEnterEvent()
void PythonConsole::dragEnterEvent (QDragEnterEvent * e) override protected
Dragging of action objects is allowed.
Definition at line 1079 of file PythonConsole.cpp.
References SCL.SimpleDataTypes::e.
dragMoveEvent()
void PythonConsole::dragMoveEvent (QDragMoveEvent * e) override protected
Dragging of action objects is allowed.
Definition at line 1066 of file PythonConsole.cpp.
References SCL.SimpleDataTypes::e.
dropEvent()
void PythonConsole::dropEvent (QDropEvent * e) override protected
Drops the event e and writes the right Python command.
Definition at line 1013 of file PythonConsole.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::cursorBeyond(), SCL.SimpleDataTypes::e, SplineSurface::i, inputBegin(), and printStatement().
inputBegin()
QTextCursor PythonConsole::inputBegin () const protected
Definition at line 1153 of file PythonConsole.cpp.
References Gui::promptLength(), and TechDraw::Right.
Referenced by contextMenuEvent(), dropEvent(), keyPressEvent(), mouseReleaseEvent(), and overrideCursor().
insertFromMimeData()
void PythonConsole::insertFromMimeData (const QMimeData * source) override protected
Allow one to paste plain text or urls of text files.
Definition at line 1115 of file PythonConsole.cpp.
References create_qrc::ext, DrawingExample::file, Path.Log::info(), and Path.Post.scripts.refactored_centroid_post::str.
keyPressEvent()
void PythonConsole::keyPressEvent (QKeyEvent * e) override protected
Checks the input of the console to make the correct indentations. After a command is prompted completely the Python interpreter is started.
The cursor is placed not on the input line (or within the prompt string) So we handle key input as follows:
don't allow changing previous lines.
allow full movement (no prompt restriction)
allow copying content (Ctrl+C)
"escape" to end of input line
The cursor sits somewhere on the input line (after the prompt) Here we handle key input a bit different:
restrict cursor movement to input line range (excluding the prompt characters)
roam the history by Up/Down keys
show call tips on period
Definition at line 543 of file PythonConsole.cpp.
References Gui::ConsoleHistory::append(), Gui::PythonConsoleP::callTipsList, Complete, Gui::cursorBeyond(), SCL.SimpleDataTypes::e, Gui::InteractiveInterpreter::hasPendingInput(), Gui::PythonConsoleP::history, Incomplete, inputBegin(), Gui::PythonConsoleP::interpreter, Gui::InteractiveInterpreter::interrupt(), Gui::PythonTextEditor::keyPressEvent(), Gui::ConsoleHistory::next(), overrideCursor(), Gui::ConsoleHistory::prev(), Gui::ConsoleHistory::restart(), Gui::CallTipsList::showTips(), Gui::stripPromptFrom(), Gui::CallTipsList::validateCursor(), and Gui::ConsoleHistory::value().
mouseReleaseEvent()
void PythonConsole::mouseReleaseEvent (QMouseEvent * e) override protected
Definition at line 980 of file PythonConsole.cpp.
References SCL.SimpleDataTypes::e, and inputBegin().
OnChange()
void PythonConsole::OnChange (Base::Subject< const char * > & rCaller, const char * sReason) override
Set new font and colors according to the parameters.
Definition at line 510 of file PythonConsole.cpp.
References ParameterGrp::GetBool(), and Gui::TextEditor::OnChange().
onClearConsole
void PythonConsole::onClearConsole () slot
Definition at line 1377 of file PythonConsole.cpp.
References Path.Op.Gui.Selection::clear(), Complete, Gui::PythonConsoleP::info, and Gui::PythonConsoleP::output.
Referenced by contextMenuEvent().
onCopyCommand
void PythonConsole::onCopyCommand () slot
Copy the selected commands into the clipboard. This is a subset of the history.
Definition at line 1432 of file PythonConsole.cpp.
References Gui::PythonConsoleP::Command, Gui::PythonConsoleP::Normal, and Gui::PythonConsoleP::type.
Referenced by contextMenuEvent().
onCopyHistory
void PythonConsole::onCopyHistory () slot
Copy the history of the console into the clipboard.
Definition at line 1418 of file PythonConsole.cpp.
References createMimeDataFromSelection(), Gui::PythonConsoleP::History, Gui::PythonConsoleP::history, Gui::ConsoleHistory::isEmpty(), Gui::PythonConsoleP::Normal, and Gui::PythonConsoleP::type.
Referenced by contextMenuEvent().
onFlush
void PythonConsole::onFlush () slot
Definition at line 725 of file PythonConsole.cpp.
References Flush.
onInsertFileName
void PythonConsole::onInsertFileName () slot
Definition at line 1406 of file PythonConsole.cpp.
References Gui::getMainWindow(), and Gui::FileDialog::getOpenFileName().
Referenced by contextMenuEvent().
onSaveHistoryAs
void PythonConsole::onSaveHistoryAs () slot
Definition at line 1384 of file PythonConsole.cpp.
References dot(), SCL.SimpleDataTypes::f, Gui::WindowParameter::getDefaultParameter(), Gui::FileDialog::getSaveFileName(), App::Application::getUserMacroDir(), Gui::PythonConsoleP::history, InitGui::t, and Gui::ConsoleHistory::values().
Referenced by contextMenuEvent().
overrideCursor()
void PythonConsole::overrideCursor (const QString & txt) protected
Overwrites the text of the cursor.
Definition at line 1308 of file PythonConsole.cpp.
References inputBegin(), TechDraw::Right, and create_qrc::txt.
Referenced by keyPressEvent().
pendingSource
void Gui::PythonConsole::pendingSource () signal
Referenced by readline().
printStatement()
void PythonConsole::printStatement (const QString & cmd)
Prints the Python statement cmd to the console.
Note
The statement gets only printed and added to the history but not invoked.
Definition at line 923 of file PythonConsole.cpp.
References Gui::ConsoleHistory::append(), Complete, Gui::PythonConsoleP::history, Gui::PythonConsoleP::interactive, and Gui::PythonConsoleP::statements.
Referenced by dropEvent().
readline()
QString PythonConsole::readline ()
Definition at line 1439 of file PythonConsole.cpp.
References draftgeoutils.intersections::connect(), Gui::PythonConsoleP::output, pendingSource(), and Special.
Referenced by Gui::PythonStdin::readline().
showEvent()
void PythonConsole::showEvent (QShowEvent * e) override protected
Shows the Python window and sets the focus to set text cursor.
Definition at line 946 of file PythonConsole.cpp.
References SCL.SimpleDataTypes::e.
Friends And Related Function Documentation
PythonStderr
friend class PythonStderr friend
Definition at line 172 of file PythonConsole.h.
Referenced by PythonConsole().
PythonStdout
friend class PythonStdout friend
Definition at line 171 of file PythonConsole.h.
Referenced by PythonConsole().
The documentation for this class was generated from the following files:
PythonConsole.h
PythonConsole.cpp