FreeCAD: Gui::LinkView::Element Class Reference
Gui::LinkView::Element Class Reference
Public Member Functions
Element (LinkView &handle)
~Element () override
void unlink (LinkInfoPtr info=LinkInfoPtr()) override
void link (App::DocumentObject *obj)
bool isLinked () const
Public Member Functions inherited from Gui::LinkOwner
virtual void onLinkedIconChange (LinkInfoPtr)
virtual void onLinkedUpdateData (LinkInfoPtr, const App::Property *)
Public Attributes
LinkInfoPtr linkInfo
LinkView & handle
CoinPtr< SoSwitch > pcSwitch
CoinPtr< SoFCSelectionRoot > pcRoot
CoinPtr< SoTransform > pcTransform
int groupIndex = -1
bool isGroup = false
friend LinkView
Additional Inherited Members
Protected Member Functions inherited from Gui::LinkOwner
virtual ~LinkOwner ()=default
Detailed Description
Definition at line 828 of file ViewProviderLink.cpp.
Constructor & Destructor Documentation
Element()
Gui::LinkView::Element::Element (LinkView & handle) inline
Definition at line 840 of file ViewProviderLink.cpp.
References Gui::LinkView::Element::pcRoot, Gui::LinkView::Element::pcSwitch, and Gui::LinkView::Element::pcTransform.
~Element()
Gui::LinkView::Element::~Element () inline override
Definition at line 848 of file ViewProviderLink.cpp.
References Gui::LinkView::getLinkRoot(), Gui::LinkView::Element::handle, Gui::LinkView::Element::pcRoot, and Gui::LinkView::Element::unlink().
Member Function Documentation
isLinked()
bool Gui::LinkView::Element::isLinked () const inline
Definition at line 876 of file ViewProviderLink.cpp.
References Gui::LinkView::Element::linkInfo.
Referenced by Gui::LinkView::Element::link().
link()
void Gui::LinkView::Element::link (App::DocumentObject * obj) inline
Definition at line 867 of file ViewProviderLink.cpp.
References Gui::LinkView::childType, Gui::LinkInfo::get(), Gui::LinkView::Element::handle, Gui::LinkView::Element::isLinked(), Gui::LinkView::Element::linkInfo, Gui::LinkView::Element::pcRoot, and Gui::LinkView::Element::unlink().
unlink()
void Gui::LinkView::Element::unlink (LinkInfoPtr info = LinkInfoPtr()) inline override virtual
Reimplemented from Gui::LinkOwner.
Definition at line 858 of file ViewProviderLink.cpp.
References Gui::coinRemoveAllChildren(), Path.Log::info(), Gui::LinkView::Element::linkInfo, and Gui::LinkView::Element::pcRoot.
Referenced by Gui::LinkView::Element::link(), and Gui::LinkView::Element::~Element().
Member Data Documentation
groupIndex
int Gui::LinkView::Element::groupIndex = -1
Definition at line 835 of file ViewProviderLink.cpp.
handle
LinkView& Gui::LinkView::Element::handle
Definition at line 831 of file ViewProviderLink.cpp.
Referenced by Gui::LinkView::Element::link(), and Gui::LinkView::Element::~Element().
isGroup
bool Gui::LinkView::Element::isGroup = false
Definition at line 836 of file ViewProviderLink.cpp.
linkInfo
LinkInfoPtr Gui::LinkView::Element::linkInfo
Definition at line 830 of file ViewProviderLink.cpp.
Referenced by Gui::LinkView::Element::isLinked(), Gui::LinkView::Element::link(), and Gui::LinkView::Element::unlink().
LinkView
friend Gui::LinkView::Element::LinkView
Definition at line 838 of file ViewProviderLink.cpp.
pcRoot
CoinPtr<SoFCSelectionRoot> Gui::LinkView::Element::pcRoot
Definition at line 833 of file ViewProviderLink.cpp.
Referenced by Gui::LinkView::Element::Element(), Gui::LinkView::Element::link(), Gui::LinkView::Element::unlink(), and Gui::LinkView::Element::~Element().
pcSwitch
CoinPtr<SoSwitch> Gui::LinkView::Element::pcSwitch
Definition at line 832 of file ViewProviderLink.cpp.
Referenced by Gui::LinkView::Element::Element().
pcTransform
CoinPtr<SoTransform> Gui::LinkView::Element::pcTransform
Definition at line 834 of file ViewProviderLink.cpp.
Referenced by Gui::LinkView::Element::Element().
The documentation for this class was generated from the following file:
ViewProviderLink.cpp