FreeCAD: FemGui::TaskPostBox Class Reference
FemGui::TaskPostBox Class Reference abstract
#include <TaskPostBoxes.h>
Public Member Functions
TaskPostBox (Gui::ViewProviderDocumentObject *view, const QPixmap &icon, const QString &title, QWidget *parent=nullptr)
~TaskPostBox () override
virtual void applyPythonCode ()=0
virtual bool isGuiTaskOnly ()
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Protected Member Functions
App::DocumentObject * getObject () const
template<class T >
T * getObject () const
template<typename T >
T * getTypedObject () const
Gui::ViewProviderDocumentObject * getView () const
template<typename T >
T * getTypedView () const
App::Document * getDocument () const
bool autoApply ()
void recompute ()
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Static Protected Member Functions
static void updateEnumerationList (App::PropertyEnumeration &, QComboBox *box)
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
Definition at line 132 of file TaskPostBoxes.h.
Constructor & Destructor Documentation
TaskPostBox()
TaskPostBox::TaskPostBox (Gui::ViewProviderDocumentObject * view, const QPixmap & icon, const QString & title, QWidget * parent = nullptr)
Definition at line 200 of file TaskPostBoxes.cpp.
~TaskPostBox()
TaskPostBox::~TaskPostBox () override default
Member Function Documentation
applyPythonCode()
virtual void FemGui::TaskPostBox::applyPythonCode () pure virtual
Implemented in FemGui::TaskPostWarpVector, FemGui::TaskPostScalarClip, FemGui::TaskPostCut, FemGui::TaskPostContours, FemGui::TaskPostClip, FemGui::TaskPostDataAtPoint, FemGui::TaskPostDataAlongLine, FemGui::TaskPostFunction, and FemGui::TaskPostDisplay.
autoApply()
bool TaskPostBox::autoApply () protected
Definition at line 211 of file TaskPostBoxes.cpp.
References FemGui::FemSettings::getPostAutoRecompute().
Referenced by recompute().
getDocument()
App::Document * TaskPostBox::getDocument () const protected
Definition at line 216 of file TaskPostBoxes.cpp.
References App::DocumentObject::getDocument(), and getObject().
Referenced by recompute(), and FemGui::TaskPostDataAtPoint::~TaskPostDataAtPoint().
getObject() [1/2]
App::DocumentObject* FemGui::TaskPostBox::getObject () const inline protected
Definition at line 150 of file TaskPostBoxes.h.
Referenced by getDocument(), getObject(), and FemGui::TaskPostDataAtPoint::TaskPostDataAtPoint().
getObject() [2/2]
template<class T > T* FemGui::TaskPostBox::getObject () const inline protected
Definition at line 155 of file TaskPostBoxes.h.
References getObject().
getTypedObject()
template<typename T > T* FemGui::TaskPostBox::getTypedObject () const inline protected
Definition at line 160 of file TaskPostBoxes.h.
References App::DocumentObjectWeakPtrT::get().
getTypedView()
template<typename T > T* FemGui::TaskPostBox::getTypedView () const inline protected
Definition at line 169 of file TaskPostBoxes.h.
References Gui::ViewProviderWeakPtrT::get().
getView()
Gui::ViewProviderDocumentObject* FemGui::TaskPostBox::getView () const inline protected
Definition at line 164 of file TaskPostBoxes.h.
isGuiTaskOnly()
virtual bool FemGui::TaskPostBox::isGuiTaskOnly () inline virtual
Reimplemented in FemGui::TaskPostDisplay.
Definition at line 144 of file TaskPostBoxes.h.
recompute()
void TaskPostBox::recompute () protected
Definition at line 222 of file TaskPostBoxes.cpp.
References autoApply(), toolbit-attributes::doc, and getDocument().
updateEnumerationList()
void TaskPostBox::updateEnumerationList (App::PropertyEnumeration & prop, QComboBox * box) static protected
Definition at line 232 of file TaskPostBoxes.cpp.
References MengerSponge::box, App::PropertyEnumeration::getEnumVector(), App::PropertyEnumeration::getValue(), and SurfaceTests.TestBlendCurve::vec.
Referenced by FemGui::TaskPostContours::TaskPostContours(), FemGui::TaskPostDataAlongLine::TaskPostDataAlongLine(), FemGui::TaskPostDataAtPoint::TaskPostDataAtPoint(), FemGui::TaskPostDisplay::TaskPostDisplay(), FemGui::TaskPostScalarClip::TaskPostScalarClip(), and FemGui::TaskPostWarpVector::TaskPostWarpVector().
The documentation for this class was generated from the following files:
TaskPostBoxes.h
TaskPostBoxes.cpp