FreeCAD: Gui::PythonBaseWorkbench Class Reference
Gui::PythonBaseWorkbench Class Reference
#include <Workbench.h>
Public Member Functions
PythonBaseWorkbench ()
~PythonBaseWorkbench () override
PyObject * getPyObject () override
Public Member Functions inherited from Gui::Workbench
Workbench ()
~Workbench () override
std::string name () const
void setName (const std::string &)
void createContextMenu (const char *recipient, MenuItem *) const
virtual void createMainWindowPopupMenu (MenuItem *) const
bool activate ()
void retranslate () const
virtual void activated ()
virtual void deactivated ()
void addTaskWatcher (const std::vector< Gui::TaskView::TaskWatcher * > &Watcher)
helper to add TaskWatcher to the TaskView
void removeTaskWatcher ()
remove the added TaskWatcher
std::list< std::string > listToolbars () const
std::list< std::pair< std::string, std::list< std::string > > > getToolbarItems () const
Shows a list of all toolbars and their commands.
std::list< std::string > listMenus () const
std::list< std::string > listCommandbars () const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Manipulation methods
MenuItem * _menuBar {nullptr}
MenuItem * _contextMenu {nullptr}
ToolBarItem * _toolBar {nullptr}
ToolBarItem * _commandBar {nullptr}
Base::PyObjectBase * _workbenchPy {nullptr}
void appendMenu (const std::list< std::string > &menu, const std::list< std::string > &items) const
Appends a new menu.
void removeMenu (const std::string &menu) const
Removes a menu.
void appendContextMenu (const std::list< std::string > &menu, const std::list< std::string > &items) const
Appends new context menu items.
void removeContextMenu (const std::string &menu) const
Removes a context menu.
void setupContextMenu (const char *recipient, MenuItem *) const override
void clearContextMenu ()
void appendToolbar (const std::string &bar, const std::list< std::string > &items) const
Appends a new toolbar.
void removeToolbar (const std::string &bar) const
Removes a toolbar.
void appendCommandbar (const std::string &bar, const std::list< std::string > &items) const
Appends a new command bar.
void removeCommandbar (const std::string &bar) const
Removes a command bar.
MenuItem * setupMenuBar () const override
ToolBarItem * setupToolBars () const override
ToolBarItem * setupCommandBars () const override
DockWindowItems * setupDockWindows () const override
Additional Inherited Members
Static Public Member Functions inherited from Gui::Workbench
static void createLinkMenu (MenuItem *)
static void addPermanentMenuItem (const std::string &cmd, const std::string &after)
static void removePermanentMenuItem (const std::string &cmd)
Removes the command cmd from the permanent menu items.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions inherited from Gui::Workbench
void addPermanentMenuItems (MenuItem *) const
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
The PythonBaseWorkbench class allows the manipulation of the workbench from Python. Therefore PythonWorkbenchPy provides the required Python interface.
Author
Werner Mayer
Definition at line 251 of file Gui/Workbench.h.
Constructor & Destructor Documentation
PythonBaseWorkbench()
PythonBaseWorkbench::PythonBaseWorkbench () default
~PythonBaseWorkbench()
PythonBaseWorkbench::~PythonBaseWorkbench () override
Definition at line 1045 of file Gui/Workbench.cpp.
References _commandBar, _contextMenu, _menuBar, _toolBar, _workbenchPy, Base::PyObjectBase::DecRef(), and Base::PyObjectBase::setInvalid().
Member Function Documentation
appendCommandbar()
void PythonBaseWorkbench::appendCommandbar (const std::string & bar, const std::list< std::string > & items) const
Appends a new command bar.
Definition at line 1198 of file Gui/Workbench.cpp.
References _commandBar, Gui::ToolBarItem::findItem(), src.Mod.Test.testPathArray::items, and Gui::ToolBarItem::setCommand().
Referenced by InitGui.TemplatePyModWorkbench::Initialize(), and src.Mod.Test.InitGui.TestWorkbench::Initialize().
appendContextMenu()
void PythonBaseWorkbench::appendContextMenu (const std::list< std::string > & menu, const std::list< std::string > & items) const
Appends new context menu items.
Definition at line 1145 of file Gui/Workbench.cpp.
References _contextMenu, Gui::MenuItem::findItem(), src.Mod.Test.testPathArray::items, NavigationIndicatorGui::menu, and Gui::MenuItem::setCommand().
Referenced by InitGui.DraftWorkbench::ContextMenu(), and InitGui.BIMWorkbench::ContextMenu().
appendMenu()
void PythonBaseWorkbench::appendMenu (const std::list< std::string > & menu, const std::list< std::string > & items) const
Appends a new menu.
Definition at line 1099 of file Gui/Workbench.cpp.
References _menuBar, Gui::MenuItem::appendItem(), Gui::MenuItem::findItem(), Gui::MenuItem::insertItem(), src.Mod.Test.testPathArray::items, NavigationIndicatorGui::menu, and Gui::MenuItem::setCommand().
Referenced by InitGui.TemplatePyModWorkbench::Initialize(), src.Mod.Test.InitGui.TestWorkbench::Initialize(), InitGui.OpenSCADWorkbench::Initialize(), InitGui.CAMWorkbench::Initialize(), and InitGui.AssemblyWorkbench::Initialize().
appendToolbar()
void PythonBaseWorkbench::appendToolbar (const std::string & bar, const std::list< std::string > & items) const
Appends a new toolbar.
Definition at line 1176 of file Gui/Workbench.cpp.
References _toolBar, Gui::ToolBarItem::findItem(), src.Mod.Test.testPathArray::items, and Gui::ToolBarItem::setCommand().
Referenced by InitGui.TemplatePyModWorkbench::Initialize(), src.Mod.Test.InitGui.TestWorkbench::Initialize(), InitGui.OpenSCADWorkbench::Initialize(), InitGui.CAMWorkbench::Initialize(), InitGui.AssemblyWorkbench::Initialize(), and src.Mod.Test.Workbench.WorkbenchTestCase::testHandler().
clearContextMenu()
void PythonBaseWorkbench::clearContextMenu ()
Definition at line 1171 of file Gui/Workbench.cpp.
References _contextMenu, and Gui::MenuItem::clear().
getPyObject()
PyObject * PythonBaseWorkbench::getPyObject () override virtual
Creates and returns immediately the corresponding Python workbench object.
Reimplemented from Gui::Workbench.
Definition at line 1057 of file Gui/Workbench.cpp.
References _workbenchPy, and Base::PyObjectBase::IncRef().
removeCommandbar()
void PythonBaseWorkbench::removeCommandbar (const std::string & bar) const
Removes a command bar.
Definition at line 1211 of file Gui/Workbench.cpp.
References _commandBar, Gui::ToolBarItem::findItem(), and Gui::ToolBarItem::removeItem().
removeContextMenu()
void PythonBaseWorkbench::removeContextMenu (const std::string & menu) const
Removes a context menu.
Definition at line 1162 of file Gui/Workbench.cpp.
References _contextMenu, Gui::MenuItem::findItem(), NavigationIndicatorGui::menu, and Gui::MenuItem::removeItem().
removeMenu()
void PythonBaseWorkbench::removeMenu (const std::string & menu) const
Removes a menu.
Definition at line 1136 of file Gui/Workbench.cpp.
References _menuBar, Gui::MenuItem::findItem(), NavigationIndicatorGui::menu, and Gui::MenuItem::removeItem().
removeToolbar()
void PythonBaseWorkbench::removeToolbar (const std::string & bar) const
Removes a toolbar.
Definition at line 1189 of file Gui/Workbench.cpp.
References _toolBar, Gui::ToolBarItem::findItem(), and Gui::ToolBarItem::removeItem().
setupCommandBars()
ToolBarItem * PythonBaseWorkbench::setupCommandBars () const override protected virtual
Returns a ToolBarItem tree structure of command bars for this workbench.
Implements Gui::Workbench.
Reimplemented in Gui::PythonWorkbench.
Definition at line 1080 of file Gui/Workbench.cpp.
References _commandBar, and Gui::ToolBarItem::copy().
setupContextMenu()
void PythonBaseWorkbench::setupContextMenu (const char * recipient, MenuItem * item) const override virtual
Sets up the contextmenu for this workbench. The default implementation does nothing.
Reimplemented from Gui::Workbench.
Reimplemented in Gui::PythonWorkbench.
Definition at line 1090 of file Gui/Workbench.cpp.
References _contextMenu, Gui::MenuItem::appendItem(), Gui::MenuItem::getItems(), and src.Mod.Test.testPathArray::items.
Referenced by Gui::PythonWorkbench::setupContextMenu().
setupDockWindows()
DockWindowItems * PythonBaseWorkbench::setupDockWindows () const override protected virtual
Returns a DockWindowItems structure of dock windows this workbench.
Implements Gui::Workbench.
Reimplemented in Gui::PythonWorkbench.
Definition at line 1085 of file Gui/Workbench.cpp.
setupMenuBar()
MenuItem * PythonBaseWorkbench::setupMenuBar () const override protected virtual
Returns a MenuItem tree structure of menus for this workbench.
Implements Gui::Workbench.
Reimplemented in Gui::PythonWorkbench.
Definition at line 1070 of file Gui/Workbench.cpp.
References _menuBar, and Gui::MenuItem::copy().
setupToolBars()
ToolBarItem * PythonBaseWorkbench::setupToolBars () const override protected virtual
Returns a ToolBarItem tree structure of toolbars for this workbench.
Implements Gui::Workbench.
Reimplemented in Gui::PythonWorkbench.
Definition at line 1075 of file Gui/Workbench.cpp.
References _toolBar, and Gui::ToolBarItem::copy().
Member Data Documentation
_commandBar
ToolBarItem* Gui::PythonBaseWorkbench::_commandBar {nullptr} protected
Definition at line 298 of file Gui/Workbench.h.
Referenced by appendCommandbar(), removeCommandbar(), setupCommandBars(), Gui::PythonWorkbench::setupCommandBars(), and ~PythonBaseWorkbench().
_contextMenu
MenuItem* Gui::PythonBaseWorkbench::_contextMenu {nullptr} protected
Definition at line 296 of file Gui/Workbench.h.
Referenced by appendContextMenu(), clearContextMenu(), removeContextMenu(), setupContextMenu(), and ~PythonBaseWorkbench().
_menuBar
MenuItem* Gui::PythonBaseWorkbench::_menuBar {nullptr} protected
Definition at line 295 of file Gui/Workbench.h.
Referenced by appendMenu(), removeMenu(), setupMenuBar(), Gui::PythonWorkbench::setupMenuBar(), and ~PythonBaseWorkbench().
_toolBar
ToolBarItem* Gui::PythonBaseWorkbench::_toolBar {nullptr} protected
Definition at line 297 of file Gui/Workbench.h.
Referenced by appendToolbar(), removeToolbar(), setupToolBars(), Gui::PythonWorkbench::setupToolBars(), and ~PythonBaseWorkbench().
_workbenchPy
Base::PyObjectBase* Gui::PythonBaseWorkbench::_workbenchPy {nullptr} protected
Definition at line 299 of file Gui/Workbench.h.
Referenced by getPyObject(), and ~PythonBaseWorkbench().
The documentation for this class was generated from the following files:
Gui/Workbench.h
Gui/Workbench.cpp