FreeCAD: OpenSCADFeatures.MatrixTransform Class Reference
OpenSCADFeatures.MatrixTransform Class Reference
Public Member Functions
def __init__ (self, obj, matrix=None, child=None)
def onChanged (self, fp, prop)
def updateProperty (self, fp, prop, value)
def execute (self, fp)
Detailed Description
Definition at line 213 of file OpenSCADFeatures.py.
Constructor & Destructor Documentation
__init__()
def OpenSCADFeatures.MatrixTransform.__init__ (self, obj, matrix = None, child = None)
Definition at line 214 of file OpenSCADFeatures.py.
Member Function Documentation
execute()
def OpenSCADFeatures.MatrixTransform.execute (self, fp)
Definition at line 231 of file OpenSCADFeatures.py.
Referenced by src.Mod.PartDesign.Scripts.Spring.MySpring.onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped.onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder.onChanged(), and FeaturePython.DistanceBolt.onChanged().
onChanged()
def OpenSCADFeatures.MatrixTransform.onChanged (self, fp, prop)
Definition at line 222 of file OpenSCADFeatures.py.
updateProperty()
def OpenSCADFeatures.MatrixTransform.updateProperty (self, fp, prop, value)
Definition at line 226 of file OpenSCADFeatures.py.
The documentation for this class was generated from the following file:
OpenSCADFeatures.py