FreeCAD: BOPTools.JoinFeatures Namespace Reference
BOPTools.JoinFeatures Namespace Reference
Classes
class CommandConnect
class CommandCutout
class CommandEmbed
class FeatureConnect
class FeatureCutout
class FeatureEmbed
class ViewProviderConnect
class ViewProviderCutout
class ViewProviderEmbed
Functions
def getParamRefine ()
def cmdCreateJoinFeature (name, mode)
def getIconPath (icon_dot_svg)
def makeConnect (name)
def makeEmbed (name)
def makeCutout (name)
def addCommands ()
Variables
translate = FreeCAD.Qt.translate
Function Documentation
addCommands()
def BOPTools.JoinFeatures.addCommands ()
Definition at line 400 of file BOPTools/JoinFeatures.py.
cmdCreateJoinFeature()
def BOPTools.JoinFeatures.cmdCreateJoinFeature (name, mode)
cmdCreateJoinFeature(name, mode): generalized implementation of GUI commands.
Definition at line 54 of file BOPTools/JoinFeatures.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by BOPTools.JoinFeatures.CommandConnect.Activated(), BOPTools.JoinFeatures.CommandEmbed.Activated(), and BOPTools.JoinFeatures.CommandCutout.Activated().
getIconPath()
def BOPTools.JoinFeatures.getIconPath (icon_dot_svg)
Definition at line 97 of file BOPTools/JoinFeatures.py.
Referenced by BOPTools.JoinFeatures.CommandConnect.GetResources(), BOPTools.JoinFeatures.CommandEmbed.GetResources(), and BOPTools.JoinFeatures.CommandCutout.GetResources().
getParamRefine()
def BOPTools.JoinFeatures.getParamRefine ()
Definition at line 50 of file BOPTools/JoinFeatures.py.
Referenced by BOPTools.JoinFeatures.FeatureConnect.__init__(), BOPTools.JoinFeatures.FeatureEmbed.__init__(), and BOPTools.JoinFeatures.FeatureCutout.__init__().
makeConnect()
def BOPTools.JoinFeatures.makeConnect (name)
makeConnect(name): makes an Connect object.
Definition at line 104 of file BOPTools/JoinFeatures.py.
makeCutout()
def BOPTools.JoinFeatures.makeCutout (name)
makeCutout(name): makes an Cutout object.
Definition at line 309 of file BOPTools/JoinFeatures.py.
makeEmbed()
def BOPTools.JoinFeatures.makeEmbed (name)
makeEmbed(name): makes an Embed object.
Definition at line 214 of file BOPTools/JoinFeatures.py.
Variable Documentation
translate
BOPTools.JoinFeatures.translate = FreeCAD.Qt.translate
Definition at line 46 of file BOPTools/JoinFeatures.py.