FreeCAD: ReenGui::PoissonWidget Class Reference
ReenGui::PoissonWidget Class Reference
#include <Poisson.h>
Classes
class Private
Public Member Functions
PoissonWidget (const App::DocumentObjectT &, QWidget *parent=nullptr)
~PoissonWidget () override
bool accept ()
Detailed Description
Definition at line 53 of file Poisson.h.
Constructor & Destructor Documentation
PoissonWidget()
PoissonWidget::PoissonWidget (const App::DocumentObjectT & obj, QWidget * parent = nullptr) explicit
Definition at line 50 of file Poisson.cpp.
References ReenGui::PoissonWidget::Private::obj, Init::parent, and ReenGui::PoissonWidget::Private::ui.
~PoissonWidget()
PoissonWidget::~PoissonWidget () override
Definition at line 58 of file Poisson.cpp.
Member Function Documentation
accept()
bool PoissonWidget::accept ()
Definition at line 63 of file Poisson.cpp.
References Gui::Command::abortCommand(), Gui::Command::addModule(), Gui::Command::App, Gui::Command::commitCommand(), Gui::Command::Doc, SCL.SimpleDataTypes::e, App::DocumentObjectT::getDocumentPython(), App::DocumentObjectT::getObjectPython(), ReenGui::PoissonWidget::Private::obj, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, runCommand, ReenGui::PoissonWidget::Private::ui, Gui::Command::updateActive(), and Path.Log::warning().
Referenced by ReenGui::TaskPoisson::accept().
The documentation for this class was generated from the following files:
Poisson.h
Poisson.cpp