FreeCAD: Part::GeometryDefaultExtension< T > Class Template Reference
Part::GeometryDefaultExtension< T > Class Template Reference
#include <GeometryDefaultExtension.h>
Public Member Functions
GeometryDefaultExtension ()
GeometryDefaultExtension (const T &val, std::string name=std::string())
~GeometryDefaultExtension () override=default
void setValue (const T &val)
const T & getValue () const
std::unique_ptr< Part::GeometryExtension > copy () const override
PyObject * getPyObject () override
PyObject * getPyObject ()
PyObject * getPyObject ()
PyObject * getPyObject ()
PyObject * getPyObject ()
void * create ()
void * create ()
void * create ()
void * create ()
GeometryDefaultExtension ()
GeometryDefaultExtension ()
Public Member Functions inherited from Part::GeometryPersistenceExtension
~GeometryPersistenceExtension () override=default
void Save (Base::Writer &) const
void Restore (Base::XMLReader &)
bool isSame (const GeometryPersistenceExtension &other) const
Public Member Functions inherited from Part::GeometryExtension
~GeometryExtension () override=default
PyObject * copyPyObject () const
void setName (const std::string &str)
const std::string & getName () const
virtual void notifyAttachment (Part::Geometry *)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
void copyAttributes (Part::GeometryExtension *cpy) const override
void restoreAttributes (Base::XMLReader &reader) override
void saveAttributes (Base::Writer &writer) const override
void restoreAttributes (Base::XMLReader &reader)
void restoreAttributes (Base::XMLReader &reader)
void restoreAttributes (Base::XMLReader &reader)
Protected Member Functions inherited from Part::GeometryExtension
GeometryExtension ()
GeometryExtension (const GeometryExtension &obj)=default
GeometryExtension & operator= (const GeometryExtension &obj)=default
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
template<typename T>
class Part::GeometryDefaultExtension< T >
Definition at line 53 of file GeometryDefaultExtension.h.
Constructor & Destructor Documentation
GeometryDefaultExtension() [1/4]
template<typename T > Part::GeometryDefaultExtension< T >::GeometryDefaultExtension inline
Definition at line 119 of file GeometryDefaultExtension.h.
GeometryDefaultExtension() [2/4]
template<typename T > GeometryDefaultExtension::GeometryDefaultExtension (const T & val, std::string name = std::string()) explicit
Definition at line 39 of file GeometryDefaultExtension.cpp.
References Part::GeometryExtension::setName().
~GeometryDefaultExtension()
template<typename T > Part::GeometryDefaultExtension< T >::~GeometryDefaultExtension () override default
GeometryDefaultExtension() [3/4]
Part::GeometryDefaultExtension< long >::GeometryDefaultExtension () inline
Definition at line 124 of file GeometryDefaultExtension.h.
GeometryDefaultExtension() [4/4]
Part::GeometryDefaultExtension< double >::GeometryDefaultExtension () inline
Definition at line 127 of file GeometryDefaultExtension.h.
Member Function Documentation
copy()
template<typename T > std::unique_ptr< Part::GeometryExtension > GeometryDefaultExtension::copy override virtual
Implements Part::GeometryExtension.
Definition at line 69 of file GeometryDefaultExtension.cpp.
copyAttributes()
template<typename T > void GeometryDefaultExtension::copyAttributes (Part::GeometryExtension * cpy) const override protected virtual
Reimplemented from Part::GeometryExtension.
Definition at line 46 of file GeometryDefaultExtension.cpp.
References Part::GeometryExtension::copyAttributes().
create() [1/4]
void * Part::GeometryDefaultExtension< long >::create ()
create() [2/4]
void * Part::GeometryDefaultExtension< std::string >::create ()
create() [3/4]
void * Part::GeometryDefaultExtension< bool >::create ()
create() [4/4]
void * Part::GeometryDefaultExtension< double >::create ()
getPyObject() [1/5]
PyObject * Part::GeometryDefaultExtension< long >::getPyObject () virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
Definition at line 93 of file GeometryDefaultExtension.cpp.
getPyObject() [2/5]
PyObject * Part::GeometryDefaultExtension< std::string >::getPyObject () virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
Definition at line 110 of file GeometryDefaultExtension.cpp.
getPyObject() [3/5]
PyObject * Part::GeometryDefaultExtension< bool >::getPyObject () virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
Definition at line 119 of file GeometryDefaultExtension.cpp.
getPyObject() [4/5]
PyObject * Part::GeometryDefaultExtension< double >::getPyObject () virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
Definition at line 136 of file GeometryDefaultExtension.cpp.
getPyObject() [5/5]
template<typename T > PyObject * GeometryDefaultExtension::getPyObject override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
Definition at line 78 of file GeometryDefaultExtension.cpp.
References THROWM.
getValue()
template<typename T > const T& Part::GeometryDefaultExtension< T >::getValue () const inline
Definition at line 82 of file GeometryDefaultExtension.h.
References Base::Type::badType().
restoreAttributes() [1/4]
void Part::GeometryDefaultExtension< long >::restoreAttributes (Base::XMLReader & reader) protected virtual
Reimplemented from Part::GeometryPersistenceExtension.
Definition at line 99 of file GeometryDefaultExtension.cpp.
References TechDrawTools.TaskFillTemplateFields::reader, and Part::GeometryPersistenceExtension::restoreAttributes().
restoreAttributes() [2/4]
void Part::GeometryDefaultExtension< bool >::restoreAttributes (Base::XMLReader & reader) protected virtual
Reimplemented from Part::GeometryPersistenceExtension.
Definition at line 125 of file GeometryDefaultExtension.cpp.
References TechDrawTools.TaskFillTemplateFields::reader, and Part::GeometryPersistenceExtension::restoreAttributes().
restoreAttributes() [3/4]
void Part::GeometryDefaultExtension< double >::restoreAttributes (Base::XMLReader & reader) protected virtual
Reimplemented from Part::GeometryPersistenceExtension.
Definition at line 142 of file GeometryDefaultExtension.cpp.
References TechDrawTools.TaskFillTemplateFields::reader, and Part::GeometryPersistenceExtension::restoreAttributes().
restoreAttributes() [4/4]
template<typename T > void GeometryDefaultExtension::restoreAttributes (Base::XMLReader & reader) override protected virtual
Reimplemented from Part::GeometryPersistenceExtension.
Definition at line 53 of file GeometryDefaultExtension.cpp.
References TechDrawTools.TaskFillTemplateFields::reader, and Part::GeometryPersistenceExtension::restoreAttributes().
saveAttributes()
template<typename T > void GeometryDefaultExtension::saveAttributes (Base::Writer & writer) const override protected virtual
Reimplemented from Part::GeometryPersistenceExtension.
Definition at line 61 of file GeometryDefaultExtension.cpp.
References Part::GeometryPersistenceExtension::saveAttributes(), and Base::Writer::Stream().
setValue()
template<typename T > void Part::GeometryDefaultExtension< T >::setValue (const T & val) inline
Definition at line 81 of file GeometryDefaultExtension.h.
The documentation for this class was generated from the following files:
GeometryDefaultExtension.h
GeometryDefaultExtension.cpp