FreeCAD: CInnerCurves Class Reference
CInnerCurves Class Reference
#include <AreaOrderer.h>
Public Member Functions
CInnerCurves (std::shared_ptr< CInnerCurves > pOuter, std::shared_ptr< CCurve > curve)
CInnerCurves ()
~CInnerCurves ()
void Insert (std::shared_ptr< CCurve > pcurve)
void GetArea (CArea &area, bool outside=true, bool use_curve=true)
void Unite (std::shared_ptr< CInnerCurves > c)
Static Public Attributes
static CAreaOrderer * area_orderer = NULL
Detailed Description
Definition at line 40 of file AreaOrderer.h.
Constructor & Destructor Documentation
CInnerCurves() [1/2]
CInnerCurves::CInnerCurves (std::shared_ptr< CInnerCurves > pOuter, std::shared_ptr< CCurve > curve)
CInnerCurves() [2/2]
CInnerCurves::CInnerCurves () inline
Definition at line 50 of file AreaOrderer.h.
Referenced by Insert().
~CInnerCurves()
CInnerCurves::~CInnerCurves ()
Definition at line 43 of file AreaOrderer.cpp.
Member Function Documentation
GetArea()
void CInnerCurves::GetArea (CArea & area, bool outside = true, bool use_curve = true)
Definition at line 91 of file AreaOrderer.cpp.
References SCL.SimpleDataTypes::c, and CArea::m_curves.
Insert()
void CInnerCurves::Insert (std::shared_ptr< CCurve > pcurve)
Definition at line 46 of file AreaOrderer.cpp.
References SCL.SimpleDataTypes::c, CInnerCurves(), eCrossing, eInside, eOutside, eSiblings, and GetOverlapType().
Referenced by Unite().
Unite()
void CInnerCurves::Unite (std::shared_ptr< CInnerCurves > c)
Definition at line 119 of file AreaOrderer.cpp.
References NavigationIndicatorGui::a2, SCL.SimpleDataTypes::c, Insert(), CCurve::IsClockwise(), and CCurve::Reverse().
Member Data Documentation
area_orderer
CAreaOrderer * CInnerCurves::area_orderer = NULL static
Definition at line 48 of file AreaOrderer.h.
Referenced by CAreaOrderer::Insert().
The documentation for this class was generated from the following files:
AreaOrderer.h
AreaOrderer.cpp