FreeCAD: Sketcher::SketchObject::GeoHistory Class Reference
Sketcher::SketchObject::GeoHistory Class Reference
Public Member Functions
AdjList::iterator find (const Base::Vector3d &pt, bool strict=true)
void clear ()
void update (const Base::Vector3d &pt, long id)
void finishUpdate (const std::map< long, int > &geomap)
AdjList::iterator end ()
size_t size ()
Detailed Description
Definition at line 613 of file SketchObject.cpp.
Member Function Documentation
clear()
void Sketcher::SketchObject::GeoHistory::clear () inline
Definition at line 654 of file SketchObject.cpp.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), and src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__().
end()
AdjList::iterator Sketcher::SketchObject::GeoHistory::end () inline
Definition at line 706 of file SketchObject.cpp.
find()
AdjList::iterator Sketcher::SketchObject::GeoHistory::find (const Base::Vector3d & pt, bool strict = true) inline
Definition at line 634 of file SketchObject.cpp.
References Base::DistanceP2(), and SCL.SimpleDataTypes::e.
finishUpdate()
void Sketcher::SketchObject::GeoHistory::finishUpdate (const std::map< long, int > & geomap) inline
Definition at line 671 of file SketchObject.cpp.
References KDL::abs(), SplineSurface::id, and TestSpreadsheet::v.
size()
size_t Sketcher::SketchObject::GeoHistory::size () inline
Definition at line 710 of file SketchObject.cpp.
Referenced by Path.Post.Utils.GCodeEditorDialog::done().
update()
void Sketcher::SketchObject::GeoHistory::update (const Base::Vector3d & pt, long id) inline
Definition at line 659 of file SketchObject.cpp.
References FC_TRACE, FC_xyz, and DraftVecUtils::find().
The documentation for this class was generated from the following file:
SketchObject.cpp