FreeCAD: MeshCore::MeshEvalNeighbourhood Class Reference
MeshCore::MeshEvalNeighbourhood Class Reference
#include <Evaluation.h>
Public Member Functions
MeshEvalNeighbourhood (const MeshKernel &rclB)
bool Evaluate () override
std::vector< FacetIndex > GetIndices () const
Public Member Functions inherited from MeshCore::MeshEvaluation
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()=default
MeshEvaluation (const MeshEvaluation &)=delete
MeshEvaluation (MeshEvaluation &&)=delete
MeshEvaluation & operator= (const MeshEvaluation &)=delete
MeshEvaluation & operator= (MeshEvaluation &&)=delete
Additional Inherited Members
Protected Attributes inherited from MeshCore::MeshEvaluation
const MeshKernel & _rclMesh
Detailed Description
The MeshEvalNeighbourhood class checks if the neighbourhood among the facets is set correctly.
Author
Werner Mayer
Definition at line 388 of file Evaluation.h.
Constructor & Destructor Documentation
MeshEvalNeighbourhood()
MeshCore::MeshEvalNeighbourhood::MeshEvalNeighbourhood (const MeshKernel & rclB) inline explicit
Definition at line 391 of file Evaluation.h.
Member Function Documentation
Evaluate()
bool MeshEvalNeighbourhood::Evaluate () override virtual
Evaluates the mesh kernel with respect to certain criteria. Must be reimplemented by every subclass. This pure virtual function returns false if the mesh kernel is invalid according to this criterion and true if the mesh kernel is correct.
Implements MeshCore::MeshEvaluation.
Definition at line 816 of file Evaluation.cpp.
References MeshCore::MeshFacet::_aulNeighbours, MeshCore::MeshEvaluation::_rclMesh, src.Mod.AddonManager.NetworkManager::count, MeshCore::FACET_INDEX_MAX, MeshCore::MeshKernel::GetFacets(), SplineSurface::i, Base::SequencerLauncher::next(), MeshCore::Edge_Index::p0, MeshCore::POINT_INDEX_MAX, and MeshCore::MeshFacet::Side().
Referenced by Mesh::MeshObject::hasInvalidNeighbourhood(), and Mesh::MeshObject::load().
GetIndices()
std::vector< FacetIndex > MeshEvalNeighbourhood::GetIndices () const
Definition at line 892 of file Evaluation.cpp.
References MeshCore::MeshFacet::_aulNeighbours, MeshCore::MeshEvaluation::_rclMesh, src.Mod.AddonManager.NetworkManager::count, MeshCore::FACET_INDEX_MAX, MeshCore::MeshKernel::GetFacets(), SplineSurface::i, Base::SequencerLauncher::next(), MeshCore::Edge_Index::p0, MeshCore::POINT_INDEX_MAX, and MeshCore::MeshFacet::Side().
The documentation for this class was generated from the following files:
Evaluation.h
Evaluation.cpp