FreeCAD: App::LinkBaseExtension Class Reference
App::LinkBaseExtension Class Reference
#include <Link.h>
Classes
struct PropInfo
Public Types
enum { LinkModeNone, LinkModeAutoDelete, LinkModeAutoLink, LinkModeAutoUnlink }
Public Member Functions
virtual Base::Type getExtensionTypeId (void) const override
LinkBaseExtension ()
~LinkBaseExtension () override=default
Public Member Functions inherited from App::DocumentObjectExtension
DocumentObjectExtension ()
~DocumentObjectExtension () override
App::DocumentObject * getExtendedObject ()
const App::DocumentObject * getExtendedObject () const
virtual void onExtendedSettingDocument ()
get called after setting the document
virtual void onExtendedSetupObject ()
get called after a brand new object was created
virtual const char * getViewProviderExtensionName () const
Public Member Functions inherited from App::Extension
Extension ()=default
virtual ~Extension ()
virtual void initExtension (App::ExtensionContainer *obj)
App::ExtensionContainer * getExtendedContainer ()
const App::ExtensionContainer * getExtendedContainer () const
std::string name () const
bool isPythonExtension ()
virtual const char * extensionGetPropertyName (const Property *prop) const
get the name of a property
virtual void extensionGetPropertyMap (std::map< std::string, Property * > &Map) const
get all properties of the class (including properties of the parent)
virtual void extensionGetPropertyList (std::vector< Property * > &List) const
get all properties of the class (including properties of the parent)
virtual short extensionGetPropertyType (const Property *prop) const
get the Type of a Property
virtual short extensionGetPropertyType (const char *name) const
get the Type of a named Property
virtual const char * extensionGetPropertyGroup (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyGroup (const char *name) const
get the Group of a named Property
virtual const char * extensionGetPropertyDocumentation (const Property *prop) const
get the Group of a Property
virtual const char * extensionGetPropertyDocumentation (const char *name) const
get the Group of a named Property
virtual void extensionSave (Base::Writer &) const
virtual void extensionRestore (Base::XMLReader &)
bool extensionIsDerivedFrom (const Base::Type type) const
Static Public Member Functions
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Static Public Member Functions inherited from App::DocumentObjectExtension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Static Public Member Functions inherited from App::Extension
static Base::Type getExtensionClassTypeId (void)
static void init (void)
static void * create (void)
Public Attributes
PropertyBool _LinkTouched
PropertyInteger _LinkOwner
PropertyLinkList _ChildCache
Protected Member Functions
virtual const App::PropertyData & extensionGetPropertyData (void) const override
Protected Member Functions inherited from App::Extension
virtual bool extensionHandleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
returns true if the property name change was handled by the extension.
virtual bool extensionHandleChangedPropertyType (Base::XMLReader &reader, const char *TypeName, Property *prop)
returns true if the property type change was handled by the extension.
void initExtensionType (Base::Type type)
Static Protected Member Functions
static const App::PropertyData * extensionGetPropertyDataPtr (void)
Static Protected Member Functions inherited from App::DocumentObjectExtension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
Static Protected Member Functions inherited from App::Extension
static const App::PropertyData * extensionGetPropertyDataPtr (void)
static void initExtensionSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Base::Type::instantiationMethod method=nullptr)
Parameter definition
Parameter definition (Name, Type, Property Type, Default, Document). The variadic is here so that the parameter can be extended by adding extra fields. See LINK_PARAM_EXT() for an example
enum PropIndex { BOOST_PP_SEQ_FOR_EACH =(LINK_PINDEX_DEFINE, _, ((Placement, Base::Placement, App::PropertyPlacement, Base::Placement(), "Alias to LinkPlacement to make the link object compatibale with other objects",)) ((LinkPlacement, Base::Placement, App::PropertyPlacement, Base::Placement(), "Link placement",)) ((LinkedObject, App::DocumentObject*, App::PropertyLink, 0, "Linked object",)) ((LinkClaimChild, bool, App::PropertyBool, false, "Claim the linked object as a child",)) ((LinkTransform, bool, App::PropertyBool, false, "Set to false to override linked object's placement",)) ((Scale, double, App::PropertyFloat, 1.0, "Scale factor",)) ((ScaleVector, Base::Vector3d, App::PropertyVector, Base::Vector3d(1, 1, 1), "Scale factors",)) ((PlacementList, std::vector<Base::Placement>, App::PropertyPlacementList, std::vector<Base::Placement>(), "The placement for each link element",)) ((ScaleList, std::vector<Base::Vector3d>, App::PropertyVectorList, std::vector<Base::Vector3d>(), "The scale factors for each link element",)) ((VisibilityList, boost::dynamic_bitset<>, App::PropertyBoolList, boost::dynamic_bitset<>(), "The visibility state of each link element",)) ((ElementCount, int, App::PropertyInteger, 0, "Link element count",)) ((ElementList, std::vector<App::DocumentObject*>, App::PropertyLinkList, std::vector<App::DocumentObject*>(), "The link element object list",)) ((ShowElement, bool, App::PropertyBool, true, "Enable link element list",)) ((LinkMode, long, App::PropertyEnumeration, ((long)0), "Link group mode",)) ((LinkExecute, const char*, App::PropertyString, (""), "Link execute function. Default to 'appLinkExecute'. 'None' to disable.",)) ((ColoredElements, App::DocumentObject*, App::PropertyLinkSubHidden, 0, "Link colored elements",)) ((LinkCopyOnChange, long, App::PropertyEnumeration, ((long)0), "Disabled: disable copy on change\n" "Enabled: enable copy linked object on change of any of its properties marked as " "CopyOnChange\n" "Owned: indicate the linked object has been copied and is own owned by the link. And the\n" " the link will try to sync any change of the original linked object back to the " "copy.",)) ((LinkCopyOnChangeSource, App::DocumentObject*, App::PropertyLink, 0, "The copy on change source object",)) ((LinkCopyOnChangeGroup, App::DocumentObject*, App::PropertyLink, 0, "Linked to a internal group object for holding on change copies",)) ((LinkCopyOnChangeTouched, bool, App::PropertyBool, 0, "Indicating the copy on change source object has been changed",))) PropMax }
enum LinkCopyOnChangeType { CopyOnChangeDisabled = 0, CopyOnChangeEnabled = 1, CopyOnChangeOwned = 2, CopyOnChangeTracking = 3 }
enum OnChangeCopyOptions { OnChangeCopyOptions::None = 0, OnChangeCopyOptions::Exclude = 1, OnChangeCopyOptions::ApplyAll = 2 }
using PropInfoMap = std::map< std::string, PropInfo >
using LinkPropMap = std::map< const Property *, std::pair< LinkBaseExtension *, int > >
std::vector< Property * > props
std::unordered_set< const App::DocumentObject * > myHiddenElements
std::vector< std::string > mySubElements
std::string mySubName
std::unordered_map< const App::DocumentObject *, boost::signals2::scoped_connection > plainGroupConns
long prevLinkedObjectID = 0
std::unordered_map< std::string, int > myLabelCache
bool enableLabelCache {false}
bool hasOldSubElement {false}
std::vector< boost::signals2::scoped_connection > copyOnChangeConns
std::vector< boost::signals2::scoped_connection > copyOnChangeSrcConns
bool hasCopyOnChange {true}
bool checkingProperty = false
bool pauseCopyOnChange = false
boost::signals2::scoped_connection connCopyOnChangeSource
static int getArrayIndex (const char *subname, const char **psubname=nullptr)
static bool setupCopyOnChange (App::DocumentObject *obj, App::DocumentObject *linked, std::vector< boost::signals2::scoped_connection > *copyOnChangeConns, bool checkExisting)
static bool isCopyOnChangeProperty (App::DocumentObject *obj, const Property &prop)
virtual void setProperty (int idx, Property *prop)
Property * getProperty (int idx)
Property * getProperty (const char *)
virtual const std::vector< PropInfo > & getPropertyInfo () const
virtual const PropInfoMap & getPropertyInfoMap () const
PropertyLinkList * _getElementListProperty () const
const std::vector< App::DocumentObject * > & _getElementListValue () const
PropertyBool * _getShowElementProperty () const
bool _getShowElementValue () const
PropertyInteger * _getElementCountProperty () const
int _getElementCountValue () const
std::vector< DocumentObject * > getLinkedChildren (bool filter=true) const
const char * flattenSubname (const char *subname) const
void expandSubname (std::string &subname) const
DocumentObject * getLink (int depth=0) const
Base::Matrix4D getTransform (bool transform) const
Base::Vector3d getScaleVector () const
App::GroupExtension * linkedPlainGroup () const
bool linkTransform () const
const char * getSubName () const
const std::vector< std::string > & getSubElements () const
bool extensionGetSubObject (DocumentObject *&ret, const char *subname, PyObject **pyObj=nullptr, Base::Matrix4D *mat=nullptr, bool transform=false, int depth=0) const override
bool extensionGetSubObjects (std::vector< std::string > &ret, int reason) const override
bool extensionGetLinkedObject (DocumentObject *&ret, bool recurse, Base::Matrix4D *mat, bool transform, int depth) const override
App::DocumentObjectExecReturn * extensionExecute () override
short extensionMustExecute () override
void extensionOnChanged (const Property *p) override
void onExtendedUnsetupObject () override
get called when object is going to be removed from the document
void onExtendedDocumentRestored () override
get called after a document has been fully restored
int extensionSetElementVisible (const char *, bool) override
int extensionIsElementVisible (const char *) override
bool extensionHasChildElement () const override
PyObject * getExtensionPyObject () override
Property * extensionGetPropertyByName (const char *name) const override
find a property by its name
int getElementIndex (const char *subname, const char **psubname=nullptr) const
void elementNameFromIndex (int idx, std::ostream &ss) const
DocumentObject * getContainer ()
const DocumentObject * getContainer () const
void setLink (int index, DocumentObject *obj, const char *subname=nullptr, const std::vector< std::string > &subs=std::vector< std::string >())
DocumentObject * getTrueLinkedObject (bool recurse, Base::Matrix4D *mat=nullptr, int depth=0, bool noElement=false) const
bool hasPlacement () const
void cacheChildLabel (int enable=-1) const
void syncCopyOnChange ()
void setOnChangeCopyObject (App::DocumentObject *obj, OnChangeCopyOptions options)
std::vector< App::DocumentObject * > getOnChangeCopyObjects (std::vector< App::DocumentObject * > *excludes=nullptr, App::DocumentObject *src=nullptr)
bool isLinkedToConfigurableObject () const
void monitorOnChangeCopyObjects (const std::vector< App::DocumentObject * > &objs)
bool isLinkMutated () const
Check if the linked object is a copy on change.
void _handleChangedPropertyName (Base::XMLReader &reader, const char *TypeName, const char *PropName)
void parseSubName () const
void update (App::DocumentObject *parent, const Property *prop)
void checkCopyOnChange (App::DocumentObject *parent, const App::Property &prop)
void setupCopyOnChange (App::DocumentObject *parent, bool checkSource=false)
App::DocumentObject * makeCopyOnChange ()
void syncElementList ()
void detachElement (App::DocumentObject *obj)
void detachElements ()
void checkGeoElementMap (const App::DocumentObject *obj, const App::DocumentObject *linked, PyObject **pyObj, const char *postfix) const
void updateGroup ()
void slotChangedPlainGroup (const App::DocumentObject &, const App::Property &)
Additional Inherited Members
Protected Attributes inherited from App::Extension
bool m_isPythonExtension = false
Py::SmartPtr ExtensionPythonObject
Detailed Description
Definition at line 52 of file Link.h.
Member Typedef Documentation
LinkPropMap
using App::LinkBaseExtension::LinkPropMap = std::map<const Property*, std::pair<LinkBaseExtension*, int> >
Definition at line 409 of file Link.h.
PropInfoMap
using App::LinkBaseExtension::PropInfoMap = std::map<std::string, PropInfo>
Definition at line 295 of file Link.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
LinkModeNone
LinkModeAutoDelete
LinkModeAutoLink
LinkModeAutoUnlink
Definition at line 65 of file Link.h.
LinkCopyOnChangeType
enum App::LinkBaseExtension::LinkCopyOnChangeType
Enumerator
CopyOnChangeDisabled
CopyOnChangeEnabled
CopyOnChangeOwned
CopyOnChangeTracking
Definition at line 298 of file Link.h.
OnChangeCopyOptions
enum App::LinkBaseExtension::OnChangeCopyOptions strong
Options used in setOnChangeCopyObject() Multiple options can be combined by bitwise or operator
Enumerator
None
No options set.
Exclude
If set, then exclude the input from object list to copy on change, or else, include the input object.
ApplyAll
If set , then apply the setting to all links to the input object, or else, apply only to this link.
Definition at line 431 of file Link.h.
PropIndex
enum App::LinkBaseExtension::PropIndex
Enumerator
BOOST_PP_SEQ_FOR_EACH
Definition at line 254 of file Link.h.
Constructor & Destructor Documentation
LinkBaseExtension()
LinkBaseExtension::LinkBaseExtension ()
Definition at line 167 of file Link.cpp.
References EXTENSION_ADD_PROPERTY_TYPE, getExtensionClassTypeId(), App::Global, App::Prop_Hidden, App::Prop_NoPersist, App::Prop_Output, and App::Prop_ReadOnly.
~LinkBaseExtension()
App::LinkBaseExtension::~LinkBaseExtension () override default
Member Function Documentation
_getElementCountProperty()
App::PropertyInteger * LinkBaseExtension::_getElementCountProperty () const
Definition at line 1077 of file Link.cpp.
References linkedPlainGroup().
Referenced by _getElementCountValue(), getElementIndex(), and update().
_getElementCountValue()
int LinkBaseExtension::_getElementCountValue () const
Definition at line 1086 of file Link.cpp.
References _getElementCountProperty().
Referenced by extensionExecute(), extensionGetLinkedObject(), extensionGetSubObject(), extensionGetSubObjects(), extensionHasChildElement(), and getElementIndex().
_getElementListProperty()
App::PropertyLinkList * LinkBaseExtension::_getElementListProperty () const
Definition at line 1038 of file Link.cpp.
References toolbit-attributes::group, and linkedPlainGroup().
_getElementListValue()
const std::vector< App::DocumentObject * > & LinkBaseExtension::_getElementListValue () const
Definition at line 1047 of file Link.cpp.
References _ChildCache, App::PropertyListsT< T, ListT, ParentT >::getSize(), and App::PropertyListsT< T, ListT, ParentT >::getValues().
Referenced by cacheChildLabel(), elementNameFromIndex(), extensionExecute(), extensionGetSubObject(), extensionHasChildElement(), extensionSetElementVisible(), getElementIndex(), getLinkedChildren(), and update().
_getShowElementProperty()
App::PropertyBool * LinkBaseExtension::_getShowElementProperty () const
Definition at line 1059 of file Link.cpp.
References linkedPlainGroup().
Referenced by _getShowElementValue(), and update().
_getShowElementValue()
bool LinkBaseExtension::_getShowElementValue () const
Definition at line 1068 of file Link.cpp.
References _getShowElementProperty().
Referenced by extensionHasChildElement(), extensionIsElementVisible(), extensionSetElementVisible(), getElementIndex(), and update().
_handleChangedPropertyName()
void LinkBaseExtension::_handleChangedPropertyName (Base::XMLReader & reader, const char * TypeName, const char * PropName) protected
Definition at line 2299 of file Link.cpp.
References Base::Persistence::getClassTypeId(), getContainer(), App::PropertyListsT< T, ListT, ParentT >::getSize(), App::PropertyListsT< T, ListT, ParentT >::getValues(), hasOldSubElement, mySubElements, TechDrawTools.TaskFillTemplateFields::reader, App::PropertyStringList::Restore(), and App::Property::setContainer().
cacheChildLabel()
void LinkBaseExtension::cacheChildLabel (int enable = -1) const
Definition at line 2170 of file Link.cpp.
References _getElementListValue(), enableLabelCache, and myLabelCache.
Referenced by getElementIndex().
checkCopyOnChange()
void LinkBaseExtension::checkCopyOnChange (App::DocumentObject * parent, const App::Property & prop) protected
Definition at line 913 of file Link.cpp.
References App::Property::Copy(), CopyOnChangeDisabled, CopyOnChangeOwned, CopyOnChangeTracking, App::Property::getName(), Base::Persistence::getTypeId(), isCopyOnChangeProperty(), makeCopyOnChange(), buildPsets::p, and Init::parent.
Referenced by update().
checkGeoElementMap()
void LinkBaseExtension::checkGeoElementMap (const App::DocumentObject * obj, const App::DocumentObject * linked, PyObject ** pyObj, const char * postfix) const protected
Definition at line 1629 of file Link.cpp.
References Data::ComplexGeoData::elementMapPrefix(), App::DocumentObject::getDocument(), App::DocumentObject::getID(), App::Document::getStringHasher(), and Data::POSTFIX_EXTERNAL_TAG.
Referenced by extensionGetSubObject().
create()
void * App::LinkBaseExtension::create (void) static
Definition at line 165 of file Link.cpp.
Referenced by draftguitools.gui_labels.Label::action().
detachElement()
void LinkBaseExtension::detachElement (App::DocumentObject * obj) protected
Definition at line 2469 of file Link.cpp.
References create_qrc::ext, getContainer(), App::DocumentObject::getDocument(), App::ExtensionContainer::getExtensionByType(), App::DocumentObject::getNameInDocument(), App::DocumentObject::isAttachedToDocument(), App::DocumentObject::isRemoving(), LinkModeAutoDelete, LinkModeAutoUnlink, and App::Document::removeObject().
Referenced by detachElements(), and setLink().
detachElements()
void LinkBaseExtension::detachElements () protected
Definition at line 2457 of file Link.cpp.
References detachElement(), and replaceobj::objs.
Referenced by onExtendedUnsetupObject(), and setLink().
elementNameFromIndex()
void LinkBaseExtension::elementNameFromIndex (int idx, std::ostream & ss) const
Definition at line 1373 of file Link.cpp.
References _ChildCache, _getElementListValue(), App::PropertyLinkList::find(), App::GroupExtension::getGroupOfObject(), App::PropertyListsT< T, ListT, ParentT >::getSize(), and toolbit-attributes::group.
Referenced by expandSubname().
expandSubname()
void LinkBaseExtension::expandSubname (std::string & subname) const
Definition at line 2526 of file Link.cpp.
References _ChildCache, elementNameFromIndex(), getElementIndex(), App::PropertyListsT< T, ListT, ParentT >::getSize(), and RobotExample::pos.
extensionExecute()
App::DocumentObjectExecReturn * LinkBaseExtension::extensionExecute () override virtual
Reimplemented from App::DocumentObjectExtension.
Definition at line 342 of file Link.cpp.
References _getElementCountValue(), _getElementListValue(), _LinkOwner, _LinkTouched, toolbit-attributes::args, CopyOnChangeDisabled, CopyOnChangeTracking, SCL.SimpleDataTypes::e, App::DocumentObjectExtension::extensionExecute(), getContainer(), App::DocumentObject::getDocument(), App::Document::getObjectByID(), App::ExtensionContainer::getPropertyByName(), App::DocumentObject::getPyObject(), getTrueLinkedObject(), App::PropertyPythonObject::getValue(), App::PropertyInteger::getValue(), hasCopyOnChange, SplineSurface::i, isCopyOnChangeProperty(), Init::parent, props, setupCopyOnChange(), syncCopyOnChange(), and App::Property::touch().
extensionGetLinkedObject()
bool LinkBaseExtension::extensionGetLinkedObject (DocumentObject *& ret, bool recursive, Base::Matrix4D * mat, bool transform, int depth) const override virtual
Get the linked object
See also
DocumentObject::getLinkedObject()
Returns
Return turn if handled, the linked object is returned in ret
Reimplemented from App::DocumentObjectExtension.
Definition at line 1699 of file Link.cpp.
References _getElementCountValue(), getContainer(), getTransform(), and getTrueLinkedObject().
extensionGetPropertyByName()
Property * LinkBaseExtension::extensionGetPropertyByName (const char * name) const override virtual
find a property by its name
Reimplemented from App::Extension.
Definition at line 2554 of file Link.cpp.
References checkingProperty, App::Extension::extensionGetPropertyByName(), getContainer(), getTrueLinkedObject(), isExcludedProperties(), and App::Extension::name().
extensionGetPropertyData()
const App::PropertyData & App::LinkBaseExtension::extensionGetPropertyData (void) const override protected virtual
Reimplemented from App::DocumentObjectExtension.
Reimplemented in App::LinkExtension.
Definition at line 165 of file Link.cpp.
extensionGetPropertyDataPtr()
const App::PropertyData * App::LinkBaseExtension::extensionGetPropertyDataPtr (void) static protected
Definition at line 165 of file Link.cpp.
extensionGetSubObject()
bool LinkBaseExtension::extensionGetSubObject (DocumentObject *& ret, const char * subname, PyObject ** pyObj = nullptr, Base::Matrix4D * mat = nullptr, bool transform = false, int depth = 0) const override virtual
Get the sub object by name
See also
DocumentObject::getSubObject()
Returns
Return turn if handled, the sub object is returned in ret
Reimplemented from App::DocumentObjectExtension.
Definition at line 1451 of file Link.cpp.
References _getElementCountValue(), _getElementListValue(), checkGeoElementMap(), dot(), DraftVecUtils::equals(), getContainer(), getElementIndex(), getScaleVector(), App::DocumentObject::getSubObject(), getTransform(), getTrueLinkedObject(), toolbit-attributes::group, Data::isMappedElement(), mySubElements, Data::POSTFIX_INDEX, and toolbit-attributes::s.
Referenced by flattenSubname().
extensionGetSubObjects()
bool LinkBaseExtension::extensionGetSubObjects (std::vector< std::string > & ret, int reason) const override virtual
Get name references of all sub objects
See also
DocumentObject::getSubObjects()
Returns
Return turn if handled, the sub object is returned in ret
Reimplemented from App::DocumentObjectExtension.
Definition at line 1418 of file Link.cpp.
References _getElementCountValue(), src.Mod.AddonManager.NetworkManager::count, App::DocumentObject::getSubObjects(), getTrueLinkedObject(), SplineSurface::i, mySubElements, and App::Extension::name().
extensionHasChildElement()
bool LinkBaseExtension::extensionHasChildElement () const override virtual
Reimplemented from App::DocumentObjectExtension.
Definition at line 1095 of file Link.cpp.
References _getElementCountValue(), _getElementListValue(), _getShowElementValue(), getTrueLinkedObject(), and App::DocumentObject::hasChildElement().
extensionIsElementVisible()
int LinkBaseExtension::extensionIsElementVisible (const char * element) override virtual
Reimplemented from App::DocumentObjectExtension.
Definition at line 1147 of file Link.cpp.
References _getShowElementValue(), getArrayIndex(), getElementIndex(), getTrueLinkedObject(), and App::DocumentObject::isElementVisible().
extensionMustExecute()
short LinkBaseExtension::extensionMustExecute () override virtual
Reimplemented from App::DocumentObjectExtension.
Definition at line 460 of file Link.cpp.
References getLink().
extensionOnChanged()
void LinkBaseExtension::extensionOnChanged (const Property * p) override virtual
Reimplemented from App::Extension.
Definition at line 1719 of file Link.cpp.
References App::Extension::extensionOnChanged(), getContainer(), Init::parent, App::Property::testStatus(), update(), and App::Property::User3.
extensionSetElementVisible()
int LinkBaseExtension::extensionSetElementVisible (const char * element, bool visible) override virtual
Reimplemented from App::DocumentObjectExtension.
Definition at line 1112 of file Link.cpp.
References _getElementListValue(), _getShowElementValue(), getArrayIndex(), getElementIndex(), getTrueLinkedObject(), myHiddenElements, App::DocumentObject::setElementVisible(), and App::Property::User3.
flattenSubname()
const char * LinkBaseExtension::flattenSubname (const char * subname) const
Definition at line 2505 of file Link.cpp.
References _ChildCache, dot(), extensionGetSubObject(), App::DocumentObjectExtension::getExtensionClassTypeId(), App::PropertyListsT< T, ListT, ParentT >::getSize(), App::ExtensionContainer::hasExtension(), and toolbit-attributes::s.
getArrayIndex()
int LinkBaseExtension::getArrayIndex (const char * subname, const char ** psubname = nullptr) static
Definition at line 1196 of file Link.cpp.
References SCL.SimpleDataTypes::c, dot(), and Data::isMappedElement().
Referenced by extensionIsElementVisible(), extensionSetElementVisible(), getElementIndex(), Gui::ViewProviderLink::getElementPicked(), and Gui::LinkView::linkGetDetailPath().
getContainer() [1/2]
DocumentObject * LinkBaseExtension::getContainer ()
Definition at line 1167 of file Link.cpp.
References create_qrc::ext, Base::Persistence::getClassTypeId(), App::Extension::getExtendedContainer(), and LINK_THROW.
Referenced by _handleChangedPropertyName(), App::LinkElement::canDelete(), detachElement(), extensionExecute(), extensionGetLinkedObject(), extensionGetPropertyByName(), extensionGetSubObject(), extensionOnChanged(), getElementIndex(), getOnChangeCopyObjects(), makeCopyOnChange(), onExtendedDocumentRestored(), setLink(), setOnChangeCopyObject(), syncCopyOnChange(), syncElementList(), and update().
getContainer() [2/2]
const DocumentObject* App::LinkBaseExtension::getContainer () const
getElementIndex()
int LinkBaseExtension::getElementIndex (const char * subname, const char ** psubname = nullptr) const
Definition at line 1226 of file Link.cpp.
References _ChildCache, _getElementCountProperty(), _getElementCountValue(), _getElementListValue(), _getShowElementValue(), cacheChildLabel(), dot(), enableLabelCache, DraftVecUtils::equals(), App::PropertyLinkList::findUsingMap(), getArrayIndex(), getContainer(), App::PropertyListsT< T, ListT, ParentT >::getSize(), getTrueLinkedObject(), toolbit-attributes::group, Data::isMappedElement(), myLabelCache, App::Extension::name(), and create_qrc::txt.
Referenced by expandSubname(), extensionGetSubObject(), extensionIsElementVisible(), and extensionSetElementVisible().
getExtensionClassTypeId()
Base::Type App::LinkBaseExtension::getExtensionClassTypeId (void) static
Definition at line 165 of file Link.cpp.
Referenced by App::GeoFeatureGroupExtension::extensionGetSubObject(), Part::Feature::getTopoShape(), getTrueLinkedObject(), and LinkBaseExtension().
getExtensionPyObject()
PyObject * LinkBaseExtension::getExtensionPyObject () override virtual
Reimplemented from App::DocumentObjectExtension.
Definition at line 189 of file Link.cpp.
References App::Extension::ExtensionPythonObject, Py::SmartPtr::is(), and Py::new_reference_to().
getExtensionTypeId()
Base::Type App::LinkBaseExtension::getExtensionTypeId (void) const override virtual
Reimplemented from App::DocumentObjectExtension.
Reimplemented in App::LinkExtension.
Definition at line 165 of file Link.cpp.
getLink()
DocumentObject * LinkBaseExtension::getLink (int depth = 0) const
Definition at line 1185 of file Link.cpp.
References App::Error, and App::GetApplication().
Referenced by extensionMustExecute(), TechDraw::ShapeExtractor::getShapeFromXLink(), and getTrueLinkedObject().
getLinkedChildren()
std::vector< App::DocumentObject * > LinkBaseExtension::getLinkedChildren (bool filter = true) const
Definition at line 2491 of file Link.cpp.
References _getElementListValue(), App::DocumentObjectExtension::getExtensionClassTypeId(), and src.Mod.Test.testPathArray::o.
Referenced by TechDraw::ShapeExtractor::getXShapes().
getOnChangeCopyObjects()
std::vector< App::DocumentObject * > LinkBaseExtension::getOnChangeCopyObjects (std::vector< App::DocumentObject * > * excludes = nullptr, App::DocumentObject * src = nullptr)
Definition at line 470 of file Link.cpp.
References CopyOnChangeDisabled, App::Document::DepSort, DraftVecUtils::equals(), getContainer(), App::Document::getDependencyList(), Init::parent, and TestSpreadsheet::v.
Referenced by makeCopyOnChange(), onExtendedDocumentRestored(), and syncCopyOnChange().
getProperty() [1/2]
Property * LinkBaseExtension::getProperty (const char * name)
Definition at line 227 of file Link.cpp.
References getProperty(), getPropertyInfoMap(), Path.Log::info(), and App::Extension::name().
getProperty() [2/2]
Property * LinkBaseExtension::getProperty (int idx)
Definition at line 219 of file Link.cpp.
References props.
Referenced by getProperty().
getPropertyInfo()
const std::vector< LinkBaseExtension::PropInfo > & LinkBaseExtension::getPropertyInfo () const virtual
Definition at line 198 of file Link.cpp.
References BOOST_PP_SEQ_FOR_EACH, LINK_PARAMS, and LINK_PROP_INFO.
Referenced by getPropertyInfoMap(), and setProperty().
getPropertyInfoMap()
const LinkBaseExtension::PropInfoMap & LinkBaseExtension::getPropertyInfoMap () const virtual
Definition at line 207 of file Link.cpp.
References getPropertyInfo(), and Path.Log::info().
Referenced by getProperty().
getScaleVector()
Base::Vector3d LinkBaseExtension::getScaleVector () const
Definition at line 1390 of file Link.cpp.
References toolbit-attributes::s.
Referenced by extensionGetSubObject(), TechDraw::ShapeExtractor::getShapeFromXLink(), getTransform(), and TechDraw::ShapeExtractor::getXShapes().
getSubElements()
const std::vector<std::string>& App::LinkBaseExtension::getSubElements () const inline
Definition at line 357 of file Link.h.
getSubName()
const char* App::LinkBaseExtension::getSubName () const inline
Definition at line 351 of file Link.h.
Referenced by getTrueLinkedObject().
getTransform()
Base::Matrix4D LinkBaseExtension::getTransform (bool transform) const
Definition at line 1399 of file Link.cpp.
References getScaleVector(), and toolbit-attributes::s.
Referenced by extensionGetLinkedObject(), and extensionGetSubObject().
getTrueLinkedObject()
DocumentObject * LinkBaseExtension::getTrueLinkedObject (bool recurse, Base::Matrix4D * mat = nullptr, int depth = 0, bool noElement = false) const
Definition at line 1670 of file Link.cpp.
References App::Extension::extensionIsDerivedFrom(), getExtensionClassTypeId(), getLink(), getSubName(), and linkTransform().
Referenced by extensionExecute(), extensionGetLinkedObject(), extensionGetPropertyByName(), extensionGetSubObject(), extensionGetSubObjects(), extensionHasChildElement(), extensionIsElementVisible(), extensionSetElementVisible(), getElementIndex(), linkedPlainGroup(), and setupCopyOnChange().
hasPlacement()
bool App::LinkBaseExtension::hasPlacement () const inline
Definition at line 411 of file Link.h.
Referenced by TechDraw::ShapeExtractor::getShapeFromXLink(), and TechDraw::ShapeExtractor::getXShapes().
init()
void App::LinkBaseExtension::init (void) static
Definition at line 165 of file Link.cpp.
Referenced by App::Application::initTypes(), and DocumentObject.DocumentObject::onChanged().
isCopyOnChangeProperty()
bool LinkBaseExtension::isCopyOnChangeProperty (App::DocumentObject * obj, const Property & prop) static
Definition at line 761 of file Link.cpp.
References _GroupPrefix, App::Property::getContainer(), App::Property::getGroup(), toolbit-attributes::group, App::Property::PropDynamic, and App::Property::testStatus().
Referenced by PartDesign::SubShapeBinder::checkCopyOnChange(), checkCopyOnChange(), extensionExecute(), PartDesign::SubShapeBinder::setupCopyOnChange(), and PartDesign::SubShapeBinder::update().
isLinkedToConfigurableObject()
bool LinkBaseExtension::isLinkedToConfigurableObject () const
Definition at line 747 of file Link.cpp.
References App::Property::CopyOnChange.
isLinkMutated()
bool LinkBaseExtension::isLinkMutated () const
Check if the linked object is a copy on change.
Definition at line 2579 of file Link.cpp.
References CopyOnChangeDisabled.
linkedPlainGroup()
App::GroupExtension * LinkBaseExtension::linkedPlainGroup () const
Definition at line 1026 of file Link.cpp.
References getTrueLinkedObject(), and mySubElements.
Referenced by _getElementCountProperty(), _getElementListProperty(), _getShowElementProperty(), update(), and updateGroup().
linkTransform()
bool LinkBaseExtension::linkTransform () const
Definition at line 2187 of file Link.cpp.
Referenced by getTrueLinkedObject().
makeCopyOnChange()
App::DocumentObject * LinkBaseExtension::makeCopyOnChange () protected
Definition at line 955 of file Link.cpp.
References App::Document::addObject(), CopyOnChangeEnabled, CopyOnChangeOwned, FC_THROWM, getContainer(), App::DocumentObject::getDocument(), getOnChangeCopyObjects(), toolbit-attributes::group, LinkGroup, LinkModeAutoDelete, monitorOnChangeCopyObjects(), replaceobj::objs, Init::parent, App::PartialObject, and pauseCopyOnChange.
Referenced by checkCopyOnChange(), and setupCopyOnChange().
monitorOnChangeCopyObjects()
void LinkBaseExtension::monitorOnChangeCopyObjects (const std::vector< App::DocumentObject * > & objs)
Definition at line 1007 of file Link.cpp.
References CopyOnChangeDisabled, copyOnChangeSrcConns, replaceobj::objs, and App::TouchOnColorChange.
Referenced by makeCopyOnChange(), onExtendedDocumentRestored(), and syncCopyOnChange().
onExtendedDocumentRestored()
void LinkBaseExtension::onExtendedDocumentRestored () override virtual
get called after a document has been fully restored
Reimplemented from App::DocumentObjectExtension.
Definition at line 2237 of file Link.cpp.
References CopyOnChangeDisabled, FC_ERR, Data::findElementName(), getContainer(), getOnChangeCopyObjects(), hasOldSubElement, monitorOnChangeCopyObjects(), Path.Post.scripts.opensbp_post::move(), myHiddenElements, mySubElements, App::DocumentObjectExtension::onExtendedDocumentRestored(), Init::parent, pauseCopyOnChange, toolbit-attributes::s, importers.importIFCmulticore::subs, update(), and TestSpreadsheet::v.
onExtendedUnsetupObject()
void LinkBaseExtension::onExtendedUnsetupObject () override virtual
get called when object is going to be removed from the document
Reimplemented from App::DocumentObjectExtension.
Definition at line 1657 of file Link.cpp.
References detachElements().
parseSubName()
void LinkBaseExtension::parseSubName () const protected
Definition at line 1728 of file Link.cpp.
References Data::findElementName(), SplineSurface::i, mySubElements, mySubName, and importers.importIFCmulticore::subs.
Referenced by update().
setLink()
void LinkBaseExtension::setLink (int index, DocumentObject * obj, const char * subname = nullptr, const std::vector< std::string > & subs = std::vector<std::string>())
Definition at line 2315 of file Link.cpp.
References _LinkOwner, detachElement(), detachElements(), DraftVecUtils::find(), getContainer(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::ExtensionContainer::getPropertyByName(), SplineSurface::i, App::Document::isAnyRestoring(), App::DocumentObject::isAttachedToDocument(), LINK_THROW, LinkModeAutoLink, Path.Post.scripts.opensbp_post::move(), App::Extension::name(), replaceobj::objs, Init::parent, toolbit-attributes::s, App::PropertyInteger::setValue(), and importers.importIFCmulticore::subs.
setOnChangeCopyObject()
void LinkBaseExtension::setOnChangeCopyObject (App::DocumentObject * obj, OnChangeCopyOptions options)
Include or exclude object from list of objects to copy on change
Parameters
obj input object
options control options.
See also
OnChangeCopyOptions.
Definition at line 517 of file Link.cpp.
References App::DocumentObject::addDynamicProperty(), ApplyAll, SCL.SimpleDataTypes::e, Exclude, FC_ERR, getContainer(), App::DocumentObject::getDocument(), App::DocumentObject::getFullName(), App::ExtensionContainer::getPropertyByName(), Init::parent, and Base::Flags< Enum >::testFlag().
setProperty()
void LinkBaseExtension::setProperty (int idx, Property * prop) virtual
Definition at line 237 of file Link.cpp.
References enums, App::Extension::extensionGetPropertyName(), FC_LOG_INSTANCE, FC_LOGLEVEL_TRACE, FC_TRACE, Base::Persistence::getClassTypeId(), App::Property::getContainer(), Base::Type::getName(), App::Property::getName(), getPropertyInfo(), App::Global, App::Property::Hidden, App::Property::Immutable, Base::BaseClass::isDerivedFrom(), App::Property::isValidName(), LINK_THROW, App::Property::LockDynamic, App::Extension::name(), props, App::PropertyEnumeration::setEnums(), App::Property::setStatus(), and Path.Post.scripts.refactored_centroid_post::str.
Referenced by Path.Base.Gui.PropertyEditor._PropertyEditorBool::setModelData(), Path.Base.Gui.PropertyEditor._PropertyEditorString::setModelData(), Path.Base.Gui.PropertyEditor._PropertyEditorPercent::setModelData(), Path.Base.Gui.PropertyEditor._PropertyEditorInteger::setModelData(), Path.Base.Gui.PropertyEditor._PropertyEditorFloat::setModelData(), Path.Base.Gui.PropertyEditor._PropertyEditorFile::setModelData(), and Path.Base.Gui.PropertyEditor._PropertyEditorEnumeration::setModelData().
setupCopyOnChange() [1/2]
bool LinkBaseExtension::setupCopyOnChange (App::DocumentObject * obj, App::DocumentObject * linked, std::vector< boost::signals2::scoped_connection > * copyOnChangeConns, bool checkExisting) static
Definition at line 797 of file Link.cpp.
References _GroupPrefix, App::Property::CopyOnChange, copyOnChangeConns, FC_WARN, App::Property::getName(), App::ExtensionContainer::getPropertyList(), App::Property::getStatus(), Base::Persistence::getTypeId(), buildPsets::p, Init::parent, props, App::Property::User3, and TestSpreadsheet::v.
Referenced by extensionExecute(), PartDesign::SubShapeBinder::setupCopyOnChange(), setupCopyOnChange(), and update().
setupCopyOnChange() [2/2]
void LinkBaseExtension::setupCopyOnChange (App::DocumentObject * parent, bool checkSource = false) protected
Definition at line 770 of file Link.cpp.
References copyOnChangeConns, CopyOnChangeDisabled, CopyOnChangeOwned, copyOnChangeSrcConns, getTrueLinkedObject(), hasCopyOnChange, makeCopyOnChange(), Init::parent, pauseCopyOnChange, setupCopyOnChange(), and App::PropertyLink::setValue().
slotChangedPlainGroup()
void LinkBaseExtension::slotChangedPlainGroup (const App::DocumentObject & obj, const App::Property & prop) protected
Definition at line 1765 of file Link.cpp.
References App::ExtensionContainer::getExtensionByType(), toolbit-attributes::group, and updateGroup().
Referenced by updateGroup().
syncCopyOnChange()
void LinkBaseExtension::syncCopyOnChange ()
Definition at line 556 of file Link.cpp.
References App::Property::CopyOnChange, toolbit-attributes::doc, App::GetApplication(), getContainer(), getOnChangeCopyObjects(), toolbit-attributes::group, LinkGroup, LinkModeAutoDelete, monitorOnChangeCopyObjects(), Path.Post.scripts.opensbp_post::move(), src.Mod.Test.testPathArray::o, replaceobj::objs, buildPsets::p, Init::parent, pauseCopyOnChange, and TestSpreadsheet::v.
Referenced by extensionExecute().
syncElementList()
void LinkBaseExtension::syncElementList () protected
Definition at line 2195 of file Link.cpp.
References getContainer(), App::Property::Hidden, SplineSurface::i, and App::Property::Immutable.
Referenced by update().
update()
void LinkBaseExtension::update (App::DocumentObject * parent, const Property * prop) protected
Definition at line 1843 of file Link.cpp.
References _ChildCache, _getElementCountProperty(), _getElementListValue(), _getShowElementProperty(), _getShowElementValue(), checkCopyOnChange(), connCopyOnChangeSource, CopyOnChangeDisabled, CopyOnChangeEnabled, CopyOnChangeOwned, toolbit-attributes::doc, enableLabelCache, getContainer(), App::PropertyListsT< T, ListT, ParentT >::getSize(), App::Property::getType(), toolbit-attributes::group, App::Property::Hidden, SplineSurface::i, App::Document::isAnyRestoring(), linkedPlainGroup(), myHiddenElements, myLabelCache, App::Extension::name(), App::NoTouch, replaceobj::objs, App::Property::Output, buildPsets::p, Init::parent, parseSubName(), pauseCopyOnChange, App::Prop_Output, toolbit-attributes::s, App::Property::setStatus(), setupCopyOnChange(), App::PropertyListsT< T, ListT, ParentT >::setValue(), syncElementList(), App::DocumentObject::testStatus(), App::Property::testStatus(), updateGroup(), App::Property::User3, and TestSpreadsheet::v.
Referenced by bimcommands.BimViews.BIM_Views::Activated(), ArchAxisSystem.AxisSystemTaskPanel::addElement(), ArchSectionPlane.SectionPlaneTaskPanel::addElement(), DraftGui.FacebinderTaskPanel::addElement(), ArchComponent.ComponentTaskPanel::addElement(), bimcommands.BimViews.BIM_Views::addLevel(), bimcommands.BimViews.BIM_Views::addProxy(), femtaskpanels.task_result_mechanical._TaskPanel::calculate(), bimcommands.BimIfcElements.BIM_IfcElements::checkMatChanged(), ArchWindow._ArchWindowTaskPanel::create(), bimcommands.BimViews.BIM_Views::delete(), draftguitools.gui_edit.Edit::endEditing(), extensionOnChanged(), bimcommands.BimWall.Arch_Wall::getPoint(), ArchStructure._CommandStructure::getPoint(), draftguitools.gui_trackers.boxTracker::height(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimTutorial.BIM_Tutorial::next(), onExtendedDocumentRestored(), bimcommands.BimIfcElements.BIM_IfcElements::onMaterialChanged(), bimcommands.BimIfcElements.BIM_IfcElements::onObjectTypeChanged(), bimcommands.BimIfcProperties.BIM_IfcProperties::onSelected(), bimcommands.BimIfcProperties.BIM_IfcProperties::onVisible(), draftguitools.gui_trackers.rectangleTracker::p3(), Plot.Plot::plot(), bimcommands.BimTutorial.BIM_Tutorial::previous(), ArchAxisSystem.AxisSystemTaskPanel::removeElement(), ArchAxis._AxisTaskPanel::removeElement(), ArchWindow._ArchWindowTaskPanel::removeElement(), ArchSectionPlane.SectionPlaneTaskPanel::removeElement(), DraftGui.FacebinderTaskPanel::removeElement(), ArchComponent.ComponentTaskPanel::removeElement(), draftguitools.gui_trackers.gridTracker::reset(), ArchRoof._RoofTaskPanel::resetObject(), ArchNesting.Nester::run(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setDescription(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setHeight(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setLabel(), draftguitools.gui_trackers.gridTracker::setMainlines(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setMaterial(), draftguitools.gui_trackers.gridTracker::setSize(), draftguitools.gui_trackers.gridTracker::setSpacing(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setTag(), bimcommands.BimWindows.BIM_Windows_TaskPanel::setWidth(), and bimcommands.BimViews.BIM_Views::update().
updateGroup()
void LinkBaseExtension::updateGroup () protected
Definition at line 1774 of file Link.cpp.
References _ChildCache, draftgeoutils.faces::bind(), src.Mod.AddonManager.NetworkManager::count, create_qrc::ext, FC_LOG, App::DocumentObjectExtension::getExtendedObject(), App::DocumentObject::getFullName(), App::PropertyListsT< T, ListT, ParentT >::getValues(), toolbit-attributes::group, linkedPlainGroup(), src.Mod.Test.testPathArray::o, plainGroupConns, App::PropertyListsT< T, ListT, ParentT >::setValue(), and slotChangedPlainGroup().
Referenced by slotChangedPlainGroup(), and update().
Member Data Documentation
_ChildCache
PropertyLinkList App::LinkBaseExtension::_ChildCache
Definition at line 63 of file Link.h.
Referenced by _getElementListValue(), elementNameFromIndex(), expandSubname(), flattenSubname(), getElementIndex(), update(), and updateGroup().
_LinkOwner
PropertyInteger App::LinkBaseExtension::_LinkOwner
Definition at line 62 of file Link.h.
Referenced by App::LinkElement::canDelete(), extensionExecute(), and setLink().
_LinkTouched
PropertyBool App::LinkBaseExtension::_LinkTouched
Definition at line 61 of file Link.h.
Referenced by extensionExecute().
checkingProperty
bool App::LinkBaseExtension::checkingProperty = false mutable protected
Definition at line 497 of file Link.h.
Referenced by extensionGetPropertyByName().
connCopyOnChangeSource
boost::signals2::scoped_connection App::LinkBaseExtension::connCopyOnChangeSource protected
Definition at line 500 of file Link.h.
Referenced by update().
copyOnChangeConns
std::vector<boost::signals2::scoped_connection> App::LinkBaseExtension::copyOnChangeConns protected
Definition at line 493 of file Link.h.
Referenced by setupCopyOnChange().
copyOnChangeSrcConns
std::vector<boost::signals2::scoped_connection> App::LinkBaseExtension::copyOnChangeSrcConns protected
Definition at line 494 of file Link.h.
Referenced by monitorOnChangeCopyObjects(), and setupCopyOnChange().
enableLabelCache
bool App::LinkBaseExtension::enableLabelCache {false} mutable protected
Definition at line 490 of file Link.h.
Referenced by cacheChildLabel(), getElementIndex(), and update().
hasCopyOnChange
bool App::LinkBaseExtension::hasCopyOnChange {true} protected
Definition at line 495 of file Link.h.
Referenced by extensionExecute(), and setupCopyOnChange().
hasOldSubElement
bool App::LinkBaseExtension::hasOldSubElement {false} protected
Definition at line 491 of file Link.h.
Referenced by _handleChangedPropertyName(), and onExtendedDocumentRestored().
myHiddenElements
std::unordered_set<const App::DocumentObject*> App::LinkBaseExtension::myHiddenElements protected
Definition at line 480 of file Link.h.
Referenced by extensionSetElementVisible(), onExtendedDocumentRestored(), and update().
myLabelCache
std::unordered_map<std::string, int> App::LinkBaseExtension::myLabelCache mutable protected
Definition at line 489 of file Link.h.
Referenced by cacheChildLabel(), getElementIndex(), and update().
mySubElements
std::vector<std::string> App::LinkBaseExtension::mySubElements mutable protected
Definition at line 481 of file Link.h.
Referenced by _handleChangedPropertyName(), extensionGetSubObject(), extensionGetSubObjects(), linkedPlainGroup(), onExtendedDocumentRestored(), and parseSubName().
mySubName
std::string App::LinkBaseExtension::mySubName mutable protected
Definition at line 482 of file Link.h.
Referenced by parseSubName().
pauseCopyOnChange
bool App::LinkBaseExtension::pauseCopyOnChange = false protected
Definition at line 498 of file Link.h.
Referenced by makeCopyOnChange(), onExtendedDocumentRestored(), setupCopyOnChange(), syncCopyOnChange(), and update().
plainGroupConns
std::unordered_map<const App::DocumentObject*, boost::signals2::scoped_connection> App::LinkBaseExtension::plainGroupConns protected
Definition at line 485 of file Link.h.
Referenced by updateGroup().
prevLinkedObjectID
long App::LinkBaseExtension::prevLinkedObjectID = 0 protected
Definition at line 487 of file Link.h.
props
std::vector<Property*> App::LinkBaseExtension::props protected
Definition at line 479 of file Link.h.
Referenced by Path.Base.Gui.SetupSheet.OpTaskPanel::accept(), extensionExecute(), getProperty(), setProperty(), setupCopyOnChange(), Path.Base.Gui.SetupSheet.OpTaskPanel::setupUi(), and Path.Base.Gui.PropertyBag.TaskPanel::setupUi().
The documentation for this class was generated from the following files:
Link.h
Link.cpp