FreeCAD: PartGui::SoBrepPointSet Class Reference
PartGui::SoBrepPointSet Class Reference
#include <SoBrepPointSet.h>
Public Member Functions
SoBrepPointSet ()
Static Public Member Functions
static void initClass ()
Protected Member Functions
~SoBrepPointSet () override=default
void GLRender (SoGLRenderAction *action) override
void GLRenderBelowPath (SoGLRenderAction *action) override
void doAction (SoAction *action) override
void getBoundingBox (SoGetBoundingBoxAction *action) override
Detailed Description
Definition at line 39 of file SoBrepPointSet.h.
Constructor & Destructor Documentation
SoBrepPointSet()
SoBrepPointSet::SoBrepPointSet ()
Definition at line 60 of file SoBrepPointSet.cpp.
~SoBrepPointSet()
PartGui::SoBrepPointSet::~SoBrepPointSet () override protected default
Member Function Documentation
doAction()
void SoBrepPointSet::doAction (SoAction * action) override protected
Definition at line 256 of file SoBrepPointSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action, Gui::SoSelectionElementAction::All, Gui::SoSelectionElementAction::Append, Gui::SoFCSelectionCounter::checkAction(), Gui::SoFCSelectionRoot::getActionContext(), Gui::SoHighlightElementAction::getColor(), Gui::SoSelectionElementAction::getColor(), Gui::SoHighlightElementAction::getElement(), Gui::SoSelectionElementAction::getElement(), Gui::SoSelectionElementAction::getType(), Gui::SoHighlightElementAction::isHighlighted(), Gui::SoSelectionElementAction::isSecondary(), Gui::SoSelectionElementAction::None, Gui::SoSelectionElementAction::Remove, and Gui::SoFCSelectionRoot::removeActionContext().
getBoundingBox()
void SoBrepPointSet::getBoundingBox (SoGetBoundingBoxAction * action) override protected
Definition at line 143 of file SoBrepPointSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action.
GLRender()
void SoBrepPointSet::GLRender (SoGLRenderAction * action) override protected
Definition at line 67 of file SoBrepPointSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action, and Gui::SoFCSelectionCounter::checkRenderCache().
GLRenderBelowPath()
void SoBrepPointSet::GLRenderBelowPath (SoGLRenderAction * action) override protected
Definition at line 138 of file SoBrepPointSet.cpp.
References Path.Post.scripts.dynapath_4060_post::action.
initClass()
void SoBrepPointSet::initClass () static
Definition at line 55 of file SoBrepPointSet.cpp.
Referenced by PyMOD_INIT_FUNC().
The documentation for this class was generated from the following files:
SoBrepPointSet.h
SoBrepPointSet.cpp