FreeCAD: AppPoints.cpp File Reference
AppPoints.cpp File Reference
#include "PreCompiled.h"
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include "Points.h"
#include "PointsPy.h"
#include "Properties.h"
#include "PropertyPointKernel.h"
#include "Structured.h"
Namespaces
Points
Functions
PyObject * Points::initModule ()
PyMOD_INIT_FUNC (Points)
Function Documentation
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (Points)
Definition at line 41 of file AppPoints.cpp.
References Base::InterpreterSingleton::addType(), Base::Console(), SIM::Coin3D::Quarter::Quarter::init(), Base::Persistence::init(), Points::initModule(), Base::Interpreter(), Base::ConsoleSingleton::Log(), and PyMOD_Return.