FreeCAD: Gui::Dialog::PlacementHandler Class Reference
Gui::Dialog::PlacementHandler Class Reference
#include <Placement.h>
Public Member Functions
PlacementHandler ()
void openTransactionIfNeeded ()
void setPropertyName (const std::string &)
void setIgnoreTransactions (bool value)
void setSelection (const std::vector< SelectionObject > &)
void reselectObjects ()
const App::DocumentObject * getFirstOfSelection () const
const std::string & getPropertyName () const
void appendDocument (const std::string &)
void activatedDocument (const std::string &)
void revertTransformation ()
void setRefPlacement (const Base::Placement &plm)
const Base::Placement & getRefPlacement () const
void applyPlacement (const Base::Placement &p, bool incremental)
void applyPlacement (const QString &p, bool incremental)
Base::Vector3d computeCenterOfMass () const
void setCenterOfMass (const Base::Vector3d &pnt)
Base::Vector3d getCenterOfMass () const
std::tuple< Base::Vector3d, std::vector< Base::Vector3d > > getSelectedPoints () const
Detailed Description
Definition at line 46 of file Gui/Placement.h.
Constructor & Destructor Documentation
PlacementHandler()
PlacementHandler::PlacementHandler ()
Definition at line 105 of file Gui/Placement.cpp.
Member Function Documentation
activatedDocument()
void PlacementHandler::activatedDocument (const std::string & name)
Definition at line 170 of file Gui/Placement.cpp.
References appendDocument().
appendDocument()
void PlacementHandler::appendDocument (const std::string & name)
Definition at line 165 of file Gui/Placement.cpp.
Referenced by activatedDocument().
applyPlacement() [1/2]
void PlacementHandler::applyPlacement (const Base::Placement & p, bool incremental)
Definition at line 254 of file Gui/Placement.cpp.
References Gui::Application::activeDocument(), Base::Console(), Gui::Application::Instance, buildPsets::p, and Base::ConsoleSingleton::Warning().
Referenced by applyPlacement(), and Gui::Dialog::Placement::reject().
applyPlacement() [2/2]
void PlacementHandler::applyPlacement (const QString & p, bool incremental)
Definition at line 294 of file Gui/Placement.cpp.
References Gui::Application::activeDocument(), applyPlacement(), Base::Console(), Gui::Application::Instance, and Base::ConsoleSingleton::Warning().
computeCenterOfMass()
Base::Vector3d PlacementHandler::computeCenterOfMass () const
Definition at line 359 of file Gui/Placement.cpp.
References Data::ComplexGeoData::getCenterOfGravity(), Base::Persistence::getClassTypeId(), App::PropertyComplexGeoData::getComplexData(), Gui::SelectionSingleton::getObjectsOfType(), and Gui::Selection().
getCenterOfMass()
Base::Vector3d PlacementHandler::getCenterOfMass () const
Definition at line 381 of file Gui/Placement.cpp.
getFirstOfSelection()
const App::DocumentObject * PlacementHandler::getFirstOfSelection () const
Definition at line 151 of file Gui/Placement.cpp.
Referenced by Gui::Dialog::Placement::bindObject().
getPropertyName()
const std::string & PlacementHandler::getPropertyName () const
Definition at line 160 of file Gui/Placement.cpp.
Referenced by Gui::Dialog::Placement::bindObject().
getRefPlacement()
const Base::Placement & PlacementHandler::getRefPlacement () const
Definition at line 249 of file Gui/Placement.cpp.
getSelectedPoints()
std::tuple< Base::Vector3d, std::vector< Base::Vector3d > > PlacementHandler::getSelectedPoints () const
Definition at line 386 of file Gui/Placement.cpp.
References Gui::SelectionSingleton::getSelectionEx(), Path.Dressup.Utils::selection(), and Gui::Selection().
openTransactionIfNeeded()
void PlacementHandler::openTransactionIfNeeded ()
Definition at line 113 of file Gui/Placement.cpp.
Referenced by Gui::Dialog::Placement::open().
reselectObjects()
void PlacementHandler::reselectObjects ()
Definition at line 138 of file Gui/Placement.cpp.
References Gui::SelectionSingleton::addSelection(), Gui::SelectionSingleton::clearSelection(), and Gui::Selection().
revertTransformation()
void PlacementHandler::revertTransformation ()
Definition at line 186 of file Gui/Placement.cpp.
References Gui::Application::getDocument(), and Gui::Application::Instance.
Referenced by Gui::Dialog::Placement::accept(), and Gui::Dialog::Placement::reject().
setCenterOfMass()
void PlacementHandler::setCenterOfMass (const Base::Vector3d & pnt)
Definition at line 376 of file Gui/Placement.cpp.
setIgnoreTransactions()
void PlacementHandler::setIgnoreTransactions (bool value)
Definition at line 128 of file Gui/Placement.cpp.
Referenced by Gui::Dialog::Placement::setIgnoreTransactions().
setPropertyName()
void PlacementHandler::setPropertyName (const std::string & name)
Definition at line 120 of file Gui/Placement.cpp.
Referenced by Gui::Dialog::Placement::setPlacementAndBindObject(), and Gui::Dialog::Placement::setPropertyName().
setRefPlacement()
void PlacementHandler::setRefPlacement (const Base::Placement & plm)
Definition at line 244 of file Gui/Placement.cpp.
setSelection()
void PlacementHandler::setSelection (const std::vector< SelectionObject > & selection)
Definition at line 133 of file Gui/Placement.cpp.
References Path.Dressup.Utils::selection().
Referenced by Gui::Dialog::Placement::setPlacementAndBindObject(), and Gui::Dialog::Placement::setSelection().
The documentation for this class was generated from the following files:
Gui/Placement.h
Gui/Placement.cpp