FreeCAD: Gui::MacroOutputBuffer Class Reference
Gui::MacroOutputBuffer Class Reference
#include <Macro.h>
Public Member Functions
MacroOutputBuffer ()
long getLines () const
Return the added lines regardless of recording or not.
void addPendingLine (int type, const char *line)
insert a new pending line in the macro
bool addPendingLineIfComment (int type, const char *line)
bool hasPendingLines () const
void incrementIfNoComment (int type)
Public Attributes
long totalLines {0}
std::vector< std::pair< int, std::string > > pendingLine
Detailed Description
Definition at line 82 of file Macro.h.
Constructor & Destructor Documentation
MacroOutputBuffer()
MacroOutputBuffer::MacroOutputBuffer () default
Member Function Documentation
addPendingLine()
void MacroOutputBuffer::addPendingLine (int type, const char * line)
insert a new pending line in the macro
Definition at line 140 of file Macro.cpp.
References pendingLine, and Path.Post.scripts.grbl_post::type.
Referenced by Gui::MacroManager::addPendingLine().
addPendingLineIfComment()
bool MacroOutputBuffer::addPendingLineIfComment (int type, const char * line)
Definition at line 150 of file Macro.cpp.
References Gui::MacroOutputOption::isComment(), pendingLine, and Path.Post.scripts.grbl_post::type.
Referenced by Gui::MacroManager::addLine().
getLines()
long Gui::MacroOutputBuffer::getLines () const inline
Return the added lines regardless of recording or not.
Definition at line 87 of file Macro.h.
hasPendingLines()
bool Gui::MacroOutputBuffer::hasPendingLines () const inline
Definition at line 93 of file Macro.h.
Referenced by Gui::MacroManager::addLine().
incrementIfNoComment()
void MacroOutputBuffer::incrementIfNoComment (int type)
Definition at line 160 of file Macro.cpp.
References Gui::MacroOutputOption::isComment(), totalLines, and Path.Post.scripts.grbl_post::type.
Referenced by Gui::MacroManager::addLine().
Member Data Documentation
pendingLine
std::vector<std::pair<int, std::string> > Gui::MacroOutputBuffer::pendingLine
Definition at line 99 of file Macro.h.
Referenced by addPendingLine(), and addPendingLineIfComment().
totalLines
long Gui::MacroOutputBuffer::totalLines {0}
Definition at line 98 of file Macro.h.
Referenced by incrementIfNoComment().
The documentation for this class was generated from the following files:
Macro.h
Macro.cpp