FreeCAD: Gui::SelectionSingleton Class Reference
Gui::SelectionSingleton Class Reference
#include <Selection.h>
Classes
struct _SelObj
struct SelObj
Public Types
enum VisibleState { VisHide = 0, VisShow = 1, VisToggle = -1 }
Visible state used by setVisible()
Public Types inherited from Base::Subject< const SelectionChanges & >
using ObserverType = Observer< const SelectionChanges & >
using MessageType = const SelectionChanges &
using SubjectType = Subject< const SelectionChanges & >
Public Member Functions
bool addSelection (const char *pDocName, const char *pObjectName=nullptr, const char *pSubName=nullptr, float x=0, float y=0, float z=0, const std::vector< SelObj > *pickedList=nullptr, bool clearPreSelect=true)
Add to selection.
bool addSelection2 (const char *pDocName, const char *pObjectName=nullptr, const char *pSubName=nullptr, float x=0, float y=0, float z=0, const std::vector< SelObj > *pickedList=nullptr)
bool addSelection (const SelectionObject &, bool clearPreSelect=true)
Add to selection.
bool addSelections (const char *pDocName, const char *pObjectName, const std::vector< std::string > &pSubNames)
Add to selection with several sub-elements.
bool updateSelection (bool show, const char *pDocName, const char *pObjectName=nullptr, const char *pSubName=nullptr)
Update a selection.
void rmvSelection (const char *pDocName, const char *pObjectName=nullptr, const char *pSubName=nullptr, const std::vector< SelObj > *pickedList=nullptr)
Remove from selection (for internal use)
void setSelection (const char *pDocName, const std::vector< App::DocumentObject * > &)
Set the selection for a document.
void clearSelection (const char *pDocName=nullptr, bool clearPreSelect=true)
Clear the selection of document pDocName. If the document name is not given the selection of the active document is cleared.
void clearCompleteSelection (bool clearPreSelect=true)
Clear the selection of all documents.
bool isSelected (const char *pDocName, const char *pObjectName=nullptr, const char *pSubName=nullptr, ResolveMode resolve=ResolveMode::OldStyleElement) const
Check if selected.
bool isSelected (App::DocumentObject *, const char *pSubName=nullptr, ResolveMode resolve=ResolveMode::OldStyleElement) const
Check if selected.
const char * getSelectedElement (App::DocumentObject *, const char *pSubName) const
int setPreselect (const char *pDocName, const char *pObjectName, const char *pSubName, float x=0, float y=0, float z=0, SelectionChanges::MsgSource signal=SelectionChanges::MsgSource::Any)
set the preselected object (mostly by the 3D view)
void rmvPreselect (bool signal=false)
remove the present preselection
void setPreselectCoord (float x, float y, float z)
sets different coords for the preselection
const SelectionChanges & getPreselection () const
returns the present preselection
void addSelectionGate (Gui::SelectionGate *gate, ResolveMode resolve=ResolveMode::OldStyleElement)
add a SelectionGate to control what is selectable
void rmvSelectionGate ()
remove the active SelectionGate
int disableCommandLog ()
int enableCommandLog (bool silent=false)
template<typename T >
unsigned int countObjectsOfType (const char *pDocName=nullptr, ResolveMode resolve=ResolveMode::OldStyleElement) const
unsigned int countObjectsOfType (const char *typeName, const char *pDocName=nullptr, ResolveMode resolve=ResolveMode::OldStyleElement) const
std::vector< App::DocumentObject * > getObjectsOfType (const Base::Type &typeId, const char *pDocName=nullptr, ResolveMode resolve=ResolveMode::OldStyleElement) const
std::vector< App::DocumentObject * > getObjectsOfType (const char *typeName, const char *pDocName=nullptr, ResolveMode resolve=ResolveMode::OldStyleElement) const
template<typename T >
std::vector< T * > getObjectsOfType (const char *pDocName=nullptr, ResolveMode resolve=ResolveMode::OldStyleElement) const
void setVisible (VisibleState visible)
std::vector< SelObj > getSelection (const char *pDocName=nullptr, ResolveMode resolve=ResolveMode::OldStyleElement, bool single=false) const
std::vector< Gui::SelectionObject > getSelectionEx (const char *pDocName=nullptr, Base::Type typeId=App::DocumentObject::getClassTypeId(), ResolveMode resolve=ResolveMode::OldStyleElement, bool single=false) const
int getAsPropertyLinkSubList (App::PropertyLinkSubList &prop) const
getAsPropertyLinkSubList fills PropertyLinkSubList with current selection.
std::vector< SelObj > getCompleteSelection (ResolveMode resolve=ResolveMode::OldStyleElement) const
bool hasSelection () const
Check if there is any selection.
bool hasSelection (const char *doc, ResolveMode resolve=ResolveMode::OldStyleElement) const
bool hasSubSelection (const char *doc=nullptr, bool subElement=false) const
bool hasPreselection () const
Check if there is any pre-selection.
unsigned int size () const
Size of selected entities for all documents.
Selection stack functions
Selection stack is for storing selection history so that the user can go back and forward to previous selections.
std::size_t selStackBackSize () const
Return the current selection stack size.
std::size_t selStackForwardSize () const
Return the current forward selection stack size.
std::vector< Gui::SelectionObject > selStackGet (const char *pDocName=nullptr, ResolveMode resolve=ResolveMode::OldStyleElement, int index=0) const
void selStackGoBack (int count=1)
void selStackGoForward (int count=1)
void selStackPush (bool clearForward=true, bool overwrite=false)
Picked list functions
Picked list stores all selected geometry elements that intersects the 3D pick point. The list population is done by SoFCUnifiedSelection through addSelection() with the pickedList argument.
bool needPickedList () const
Check whether picked list is enabled.
void enablePickedList (bool)
Turn on or off picked list.
bool hasPickedList () const
Check if there is any selection inside picked list.
std::vector< SelectionSingleton::SelObj > getPickedList (const char *pDocName) const
Return select objects inside picked list.
std::vector< Gui::SelectionObject > getPickedListEx (const char *pDocName=nullptr, Base::Type typeId=App::DocumentObject::getClassTypeId()) const
Return selected object inside picked list grouped by top level parents.
Public Member Functions inherited from Base::Subject< const SelectionChanges & >
Subject ()=default
virtual ~Subject ()
void Attach (Observer< const SelectionChanges & > *ToObserv)
void Detach (Observer< const SelectionChanges & > *ToObserv)
void Notify (const SelectionChanges & rcReason)
Observer< const SelectionChanges & > * Get (const char *Name)
void ClearObserver ()
Public Attributes
boost::signals2::signal< void(const SelectionChanges &msg)> signalSelectionChanged
signal on new object
boost::signals2::signal< void(const SelectionChanges &msg)> signalSelectionChanged2
signal on selection change with resolved object
boost::signals2::signal< void(const SelectionChanges &msg)> signalSelectionChanged3
signal on selection change with resolved object and sub element map
Selection style functions
The selection style changes the way selection works. In Greedy selection it is as if you were pressing Ctrl.
enum SelectionStyle { SelectionStyle::NormalSelection, SelectionStyle::GreedySelection }
using SelStackItem = std::set< App::SubObjectT >
class SelectionFilter
static PyMethodDef Methods []
SelectionChanges CurrentPreselection
std::deque< SelectionChanges > NotificationQueue
bool Notifying = false
std::list< _SelObj > _SelList
std::list< _SelObj > _PickedList
bool _needPickedList {false}
std::deque< SelStackItem > _SelStackBack
std::deque< SelStackItem > _SelStackForward
std::string DocName
std::string FeatName
std::string SubName
float hx
float hy
float hz
Gui::SelectionGate * ActiveGate
ResolveMode gateResolve
int logDisabled = 0
bool logHasSelection = false
SelectionStyle selectionStyle
static SelectionSingleton * _pcSingleton = nullptr
void setSelectionStyle (SelectionStyle selStyle)
Changes the style of selection between greedy and normal.
SelectionStyle getSelectionStyle ()
Get the style of selection.
static SelectionSingleton & instance ()
static void destruct ()
static PyObject * sAddSelection (PyObject *self, PyObject *args)
static PyObject * sUpdateSelection (PyObject *self, PyObject *args)
static PyObject * sRemoveSelection (PyObject *self, PyObject *args)
static PyObject * sClearSelection (PyObject *self, PyObject *args)
static PyObject * sIsSelected (PyObject *self, PyObject *args)
static PyObject * sCountObjectsOfType (PyObject *self, PyObject *args)
static PyObject * sGetSelection (PyObject *self, PyObject *args)
static PyObject * sSetPreselection (PyObject *self, PyObject *args, PyObject *kwd)
static PyObject * sGetPreselection (PyObject *self, PyObject *args)
static PyObject * sRemPreselection (PyObject *self, PyObject *args)
static PyObject * sGetCompleteSelection (PyObject *self, PyObject *args)
static PyObject * sGetSelectionEx (PyObject *self, PyObject *args)
static PyObject * sGetSelectionObject (PyObject *self, PyObject *args)
static PyObject * sSetSelectionStyle (PyObject *self, PyObject *args)
static PyObject * sAddSelObserver (PyObject *self, PyObject *args)
static PyObject * sRemSelObserver (PyObject *self, PyObject *args)
static PyObject * sAddSelectionGate (PyObject *self, PyObject *args)
static PyObject * sRemoveSelectionGate (PyObject *self, PyObject *args)
static PyObject * sGetPickedList (PyObject *self, PyObject *args)
static PyObject * sEnablePickedList (PyObject *self, PyObject *args)
static PyObject * sPreselect (PyObject *self, PyObject *args)
static PyObject * sSetVisible (PyObject *self, PyObject *args)
static PyObject * sPushSelStack (PyObject *self, PyObject *args)
static PyObject * sHasSelection (PyObject *self, PyObject *args)
static PyObject * sHasSubSelection (PyObject *self, PyObject *args)
static PyObject * sGetSelectionFromStack (PyObject *self, PyObject *args)
static App::DocumentObject * getObjectOfType (_SelObj &sel, Base::Type type, ResolveMode resolve, const char **subelement=nullptr)
SelectionSingleton ()
Construction.
~SelectionSingleton () override
Destruction.
void slotDeletedObject (const App::DocumentObject &)
Observer message from the App doc.
App::Document * getDocument (const char *pDocName=nullptr) const
helper to retrieve document by name
void slotSelectionChanged (const SelectionChanges &msg)
void notify (SelectionChanges &&Chng)
void notify (const SelectionChanges &Chng)
int checkSelection (const char *pDocName, const char *pObjectName, const char *pSubName, ResolveMode resolve, _SelObj &sel, const std::list< _SelObj > *selList=nullptr) const
std::vector< Gui::SelectionObject > getObjectList (const char *pDocName, Base::Type typeId, std::list< _SelObj > &objs, ResolveMode resolve, bool single=false) const
unsigned int countObjectsOfType (const Base::Type &typeId=App::DocumentObject::getClassTypeId(), const char *pDocName=nullptr, ResolveMode resolve=ResolveMode::OldStyleElement) const
Detailed Description
The Selection class The selection singleton keeps track of the selection state of the whole application. It gets messages from all entities which can alter the selection (e.g. tree view and 3D-view) and sends messages to entities which need to keep track on the selection state.
The selection consists mainly out of following information per selected object:
document (pointer)
Object (pointer)
list of subelements (list of strings)
3D coordinates where the user clicks to select (Vector3d)
Also the preselection is managed. That means you can add a filter to prevent selection of unwanted objects or subelements.
Definition at line 319 of file Gui/Selection.h.
Member Typedef Documentation
SelStackItem
using Gui::SelectionSingleton::SelStackItem = std::set<App::SubObjectT> protected
Definition at line 701 of file Gui/Selection.h.
Member Enumeration Documentation
SelectionStyle
enum Gui::SelectionSingleton::SelectionStyle strong
Enumerator
NormalSelection
GreedySelection
Definition at line 612 of file Gui/Selection.h.
VisibleState
enum Gui::SelectionSingleton::VisibleState
Visible state used by setVisible()
Enumerator
VisHide
Hide the selection.
VisShow
Show the selection.
VisToggle
Toggle visibility of the selection.
Definition at line 425 of file Gui/Selection.h.
Constructor & Destructor Documentation
SelectionSingleton()
SelectionSingleton::SelectionSingleton () protected
Construction.
A constructor. A more elaborate description of the constructor.
Definition at line 1645 of file Gui/Selection.cpp.
References ActiveGate, draftgeoutils.faces::bind(), gateResolve, App::GetApplication(), hx, hy, hz, Gui::OldStyleElement, App::Application::signalDeletedObject, signalSelectionChanged, slotDeletedObject(), and slotSelectionChanged().
Referenced by instance().
~SelectionSingleton()
SelectionSingleton::~SelectionSingleton () override protected default
Destruction.
A destructor. A more elaborate description of the destructor.
Member Function Documentation
addSelection() [1/2]
bool SelectionSingleton::addSelection (const char * pDocName, const char * pObjectName = nullptr, const char * pSubName = nullptr, float x = 0, float y = 0, float z = 0, const std::vector< SelObj > * pickedList = nullptr, bool clearPreSelect = true)
Add to selection.
Definition at line 893 of file Gui/Selection.cpp.
References _PickedList, _SelList, _SelStackForward, Gui::Application::activeDocument(), ActiveGate, Gui::SelectionChanges::AddSelection, Gui::SelectionGate::allow(), checkSelection(), Gui::SelectionSingleton::_SelObj::DocName, FC_LOG, Gui::SelectionSingleton::_SelObj::FeatName, gateResolve, Gui::Document::getActiveView(), Base::Persistence::getClassTypeId(), Gui::getMainWindow(), getObjectOfType(), Gui::Application::Instance, isSelected(), Gui::SelectionSingleton::_SelObj::log(), logDisabled, Path.Post.scripts.opensbp_post::move(), Path.Op.Surface::msg, Gui::NoResolve, Gui::SelectionGate::notAllowedReason, notify(), Gui::SelectionSingleton::_SelObj::pDoc, Gui::SelectionChanges::pDocName, Gui::SelectionChanges::PickedListChanged, Gui::SelectionChanges::pObjectName, Gui::SelectionChanges::pSubName, rmvPreselect(), toolbit-attributes::s, Gui::MDIView::setOverrideCursor(), Gui::MainWindow::showMessage(), Gui::SelectionSingleton::_SelObj::SubName, src.Mod.AddonManager.Addon::translate, Gui::SelectionSingleton::_SelObj::TypeName, Gui::MainWindow::updateActions(), MovieTool::x, Gui::SelectionSingleton::_SelObj::x, MovieTool::y, Gui::SelectionSingleton::_SelObj::y, and Gui::SelectionSingleton::_SelObj::z.
Referenced by StdCmdLinkMakeGroup::activated(), StdCmdLinkMake::activated(), StdCmdLinkMakeRelative::activated(), StdCmdLinkSelectLinked::activated(), PartGui::FaceAppearances::Private::addFacesToSelection(), TechDrawGui::MDIViewPage::addSceneItemToTreeSel(), addSelection(), Gui::DAG::Model::contextMenuEvent(), Gui::Dialog::DlgPropertyLink::detachObserver(), dimensionMaker(), doSelect(), dressupGetSelected(), Gui::SoFCSelection::handleEvent(), Gui::TreeWidget::itemSearch(), Gui::DAG::Model::mousePressEvent(), PartDesignGui::TaskFeaturePick::onDoubleClick(), PartDesignGui::TaskFeaturePick::onItemSelectionChanged(), Gui::TreeWidget::onSelectDependents(), Gui::ElementColors::Private::onSelectionChanged(), DrawSketchHandlerGenConstraint::releaseButton(), DrawSketchHandlerDimension::releaseButton(), Gui::Dialog::PlacementHandler::reselectObjects(), sAddSelection(), Gui::PropertyEditor::LinkSelection::select(), selStackGoBack(), selStackGoForward(), PartDesignGui::ViewProviderSubShapeBinder::setEdit(), TechDrawGui::ViewProviderViewPart::setEdit(), FemGui::TaskFemConstraint::setSelection(), TechDrawGui::MDIViewPage::setTreeToSceneSelect(), TechDrawGui::TaskDimRepair::slotUseSelection(), PartDesignGui::ViewProvider::unsetEdit(), and SketcherGui::ViewProviderSketch::unsetEdit().
addSelection() [2/2]
bool SelectionSingleton::addSelection (const SelectionObject & obj, bool clearPreSelect = true)
Add to selection.
Definition at line 1163 of file Gui/Selection.cpp.
References addSelection(), Gui::SelectionObject::getDocName(), Gui::SelectionObject::getFeatName(), Gui::SelectionObject::getPickedPoints(), Gui::SelectionObject::getSubNames(), SplineSurface::i, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
addSelection2()
bool Gui::SelectionSingleton::addSelection2 (const char * pDocName, const char * pObjectName = nullptr, const char * pSubName = nullptr, float x = 0, float y = 0, float z = 0, const std::vector< SelObj > * pickedList = nullptr) inline
Definition at line 336 of file Gui/Selection.h.
References MovieTool::x, and MovieTool::y.
Referenced by SketcherGui::TaskSketcherElements::onListWidgetElementsItemPressed().
addSelectionGate()
void SelectionSingleton::addSelectionGate (Gui::SelectionGate * gate, ResolveMode resolve = ResolveMode::OldStyleElement)
add a SelectionGate to control what is selectable
Definition at line 812 of file Gui/Selection.cpp.
References ActiveGate, gateResolve, and rmvSelectionGate().
Referenced by PartDesignGui::TaskTransformedParameters::addReferenceSelectionGate(), Gui::SelectionObserver::attachSelection(), PartGui::DlgFilletEdges::DlgFilletEdges(), Gui::ElementColors::ElementColors(), PartGui::FaceAppearances::FaceAppearances(), PartGui::Mirroring::Mirroring(), PartDesignGui::TaskSketchBasedParameters::onSelectReference(), sAddSelectionGate(), PartDesignGui::TaskExtrudeParameters::setSelectionMode(), PartDesignGui::TaskDressUpParameters::setSelectionMode(), PartGui::ShapeBuilderWidget::ShapeBuilderWidget(), and PartDesignGui::TaskDatumParameters::TaskDatumParameters().
addSelections()
bool SelectionSingleton::addSelections (const char * pDocName, const char * pObjectName, const std::vector< std::string > & pSubNames)
Add to selection with several sub-elements.
Definition at line 1095 of file Gui/Selection.cpp.
References _PickedList, _SelList, _SelStackForward, Gui::SelectionChanges::AddSelection, checkSelection(), Gui::SelectionSingleton::_SelObj::DocName, FC_LOG, Gui::SelectionSingleton::_SelObj::FeatName, Gui::getMainWindow(), Path.Post.scripts.opensbp_post::move(), Gui::NoResolve, notify(), Gui::SelectionChanges::pDocName, Gui::SelectionChanges::PickedListChanged, Gui::SelectionChanges::pObjectName, Gui::SelectionChanges::pSubName, Gui::SelectionSingleton::_SelObj::SubName, Gui::SelectionSingleton::_SelObj::TypeName, Gui::MainWindow::updateActions(), Gui::SelectionSingleton::_SelObj::x, Gui::SelectionSingleton::_SelObj::y, and Gui::SelectionSingleton::_SelObj::z.
Referenced by SketcherGui::ConstraintView::contextMenuEvent(), SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsItemSelectionChanged(), PartDesignGui::ViewProviderSubShapeBinder::setEdit(), and PartGui::DlgFilletEdges::setupFillet().
checkSelection()
int SelectionSingleton::checkSelection (const char * pDocName, const char * pObjectName, const char * pSubName, ResolveMode resolve, _SelObj & sel, const std::list< _SelObj > * selList = nullptr) const protected
Definition at line 1483 of file Gui/Selection.cpp.
References _SelList, Gui::TreeWidget::checkTopParent(), Gui::SelectionSingleton::_SelObj::DocName, Gui::SelectionSingleton::_SelObj::elementName, FC_ERR, Gui::SelectionSingleton::_SelObj::FeatName, getDocument(), Base::Type::getName(), App::Document::getName(), App::DocumentObject::getNameInDocument(), App::Document::getObject(), Base::Persistence::getTypeId(), App::ElementNamePair::newName, Gui::NoResolve, App::GeoFeature::Normal, App::ElementNamePair::oldName, Gui::OldStyleElement, Gui::SelectionSingleton::_SelObj::pDoc, Gui::SelectionSingleton::_SelObj::pObject, Gui::SelectionSingleton::_SelObj::pResolvedObject, App::Remove, App::GeoFeature::resolveElement(), toolbit-attributes::s, Gui::SelectionSingleton::_SelObj::SubName, App::DocumentObject::testStatus(), and Gui::SelectionSingleton::_SelObj::TypeName.
Referenced by addSelection(), addSelections(), isSelected(), rmvSelection(), selStackGet(), and setSelection().
clearCompleteSelection()
void SelectionSingleton::clearCompleteSelection (bool clearPreSelect = true)
Clear the selection of all documents.
Definition at line 1439 of file Gui/Selection.cpp.
References _PickedList, _SelList, Gui::MacroManager::addLine(), Gui::SelectionChanges::ClrSelection, Gui::MacroManager::Cmt, FC_LOG, Gui::getMainWindow(), Gui::Application::Instance, logDisabled, Gui::Application::macroManager(), Path.Post.scripts.opensbp_post::move(), notify(), Gui::SelectionChanges::PickedListChanged, rmvPreselect(), and Gui::MainWindow::updateActions().
Referenced by StdCmdLinkMakeGroup::activated(), StdCmdLinkMake::activated(), StdCmdLinkMakeRelative::activated(), StdCmdLinkSelectLinked::activated(), StdCmdLinkSelectLinkedFinal::activated(), StdCmdLinkSelectAllLinks::activated(), StdCmdTreeSelectAllInstances::activated(), clearSelection(), linkConvert(), selStackGoBack(), selStackGoForward(), and Gui::Application::slotDeleteDocument().
clearSelection()
void SelectionSingleton::clearSelection (const char * pDocName = nullptr, bool clearPreSelect = true)
Clear the selection of document pDocName. If the document name is not given the selection of the active document is cleared.
Definition at line 1388 of file Gui/Selection.cpp.
References _PickedList, _SelList, Gui::MacroManager::addLine(), clearCompleteSelection(), Gui::SelectionChanges::ClrSelection, Gui::MacroManager::Cmt, DocName, getDocument(), Gui::getMainWindow(), Gui::Application::Instance, logDisabled, Gui::Application::macroManager(), notify(), Gui::SelectionChanges::PickedListChanged, rmvPreselect(), and Gui::MainWindow::updateActions().
Referenced by TechDrawGui::TaskDimRepair::accept(), MeshGui::TaskDecimating::accept(), SketcherCopy::activate(), StdCmdAlignment::activated(), CmdSketcherConstrainLock::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadiam::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), CmdSketcherConstrainCoincidentUnified::activatedCoincident(), CmdSketcherConstrainCoincidentUnified::activatedPointOnObject(), Gui::ElementColors::Private::apply(), CmdSketcherConstrainPerpendicular::applyConstraint(), CmdSketcherConstrainTangent::applyConstraint(), CmdSketcherConstrainRadius::applyConstraint(), CmdSketcherConstrainDiameter::applyConstraint(), CmdSketcherConstrainRadiam::applyConstraint(), CmdSketcherConstrainSymmetric::applyConstraint(), PartGui::ViewProviderPartExt::changeFaceAppearances(), Gui::TaskMeasure::clearSelection(), SketcherGui::ConstraintView::contextMenuEvent(), Gui::DAG::Model::contextMenuEvent(), PartDesignGui::TaskDressUpParameters::deleteRef(), Gui::Dialog::DlgPropertyLink::detachObserver(), dimensionMaker(), doSelect(), AssemblyGui::ViewProviderAssembly::doubleClicked(), dressupGetSelected(), execCircleCenterLines(), execCreateHorizChainDimension(), execCreateHorizChamferDimension(), execCreateHorizCoordDimension(), execCreateObliqueChainDimension(), execCreateObliqueCoordDimension(), execCreateVertChainDimension(), execCreateVertChamferDimension(), execCreateVertCoordDimension(), execDrawCosmArc(), execDrawCosmCircle(), execDrawCosmCircle3Points(), TechDrawGui::execHoleCircle(), execLineParallelPerpendicular(), execThreadBoltBottom(), execThreadBoltSide(), execThreadHoleBottom(), execThreadHoleSide(), TDHandlerDimension::finalizeCommand(), finishDatumConstraint(), AssemblyGui::ViewProviderAssembly::getSelectedObjectsWithinAssembly(), Gui::SoFCSelection::handleEvent(), horVerActivated(), Gui::TreeWidget::itemSearch(), AssemblyGui::ViewProviderAssembly::mouseButtonPressed(), SketcherGui::ViewProviderSketch::mouseButtonPressed(), Gui::DAG::Model::mousePressEvent(), TechDrawGui::QGSPage::mousePressEvent(), TDHandlerDimension::mouseReleaseEvent(), CmdSketcherConstrainCoincidentUnified::onActivated(), FemGui::TaskFemConstraint::onButtonReference(), FemGui::TaskFemConstraintOnBoundary::onButtonToggled(), PartDesignGui::TaskDlgPipeParameters::onButtonToggled(), SketcherGui::ViewProviderSketch::onDelete(), PartDesignGui::TaskFeaturePick::onItemSelectionChanged(), SketcherGui::TaskSketcherConstraints::onListWidgetConstraintsItemSelectionChanged(), SketcherGui::TaskSketcherElements::onListWidgetElementsItemPressed(), FemGui::TaskFemConstraintBearing::onSelectionChanged(), FemGui::TaskFemConstraintGear::onSelectionChanged(), PartDesignGui::TaskSketchBasedParameters::onSelectReference(), SurfaceGui::FillingEdgePanel::open(), SurfaceGui::FillingVertexPanel::open(), SurfaceGui::GeomFillSurface::open(), SurfaceGui::SectionsPanel::open(), SurfaceGui::FillingPanel::open(), MeshGui::ParametersDialog::ParametersDialog(), prepareProfileBased(), Gui::NavigationStyle::processEvent(), SketcherGui::ViewProviderSketch::purgeHandler(), PartDesignGui::TaskDressUpParameters::referenceSelected(), TechDrawGui::TaskDimRepair::reject(), DrawSketchHandlerGenConstraint::releaseButton(), MeshGui::RemoveComponents::RemoveComponents(), Gui::Dialog::PlacementHandler::reselectObjects(), Gui::ElementColors::Private::reset(), DrawSketchHandlerGenConstraint::resetOngoingSequences(), DrawSketchHandlerDimension::resetTool(), TechDrawGui::QGSPage::saveSvg(), TechDrawGui::MDIViewPage::sceneSelectionChanged(), sClearSelection(), ReverseEngineeringGui::SegmentationManual::SegmentationManual(), Gui::PropertyEditor::LinkSelection::select(), Gui::TreeWidget::selectAll(), TechDrawGui::ViewProviderGeomHatch::setEdit(), TechDrawGui::ViewProviderHatch::setEdit(), TechDrawGui::ViewProviderLeader::setEdit(), FemGui::ViewProviderFemConstraintPressure::setEdit(), FemGui::ViewProviderFemConstraintRigidBody::setEdit(), PartDesignGui::ViewProviderShapeBinder::setEdit(), FemGui::ViewProviderFemConstraintSpring::setEdit(), FemGui::ViewProviderFemMeshShapeNetgen::setEdit(), PartDesignGui::ViewProviderPrimitive::setEdit(), FemGui::ViewProviderFemConstraintPulley::setEdit(), PartDesignGui::ViewProviderHole::setEdit(), FemGui::ViewProviderFemConstraintBearing::setEdit(), FemGui::ViewProviderFemConstraintGear::setEdit(), FemGui::ViewProviderFemConstraintForce::setEdit(), FemGui::ViewProviderFemConstraintFixed::setEdit(), FemGui::ViewProviderFemConstraintFluidBoundary::setEdit(), FemGui::ViewProviderFemConstraintContact::setEdit(), FemGui::ViewProviderFemConstraintPlaneRotation::setEdit(), FemGui::ViewProviderFemConstraintInitialTemperature::setEdit(), FemGui::ViewProviderFemConstraintDisplacement::setEdit(), FemGui::ViewProviderFemConstraintTemperature::setEdit(), FemGui::ViewProviderFemConstraintHeatflux::setEdit(), FemGui::ViewProviderFemConstraintTransform::setEdit(), TechDrawGui::ViewProviderWeld::setEdit(), PartDesignGui::ViewProviderSubShapeBinder::setEdit(), TechDrawGui::ViewProviderProjGroup::setEdit(), TechDrawGui::ViewProviderViewSection::setEdit(), PartDesignGui::ViewProviderBoolean::setEdit(), PartDesignGui::ViewProvider::setEdit(), TechDrawGui::ViewProviderBalloon::setEdit(), TechDrawGui::ViewProviderViewPart::setEdit(), PartDesignGui::ViewProviderDatum::setEdit(), TechDrawGui::ViewProviderDimension::setEdit(), PartGui::ViewProviderOffset::setEdit(), PartGui::ViewProviderThickness::setEdit(), Gui::ViewProviderLink::setEdit(), SketcherGui::ViewProviderSketch::setEdit(), FemGui::TaskFemConstraint::setSelection(), PartDesignGui::TaskDressUpParameters::setSelection(), PartDesignGui::TaskDressUpParameters::setSelectionMode(), TechDrawGui::MDIViewPage::setTreeToSceneSelect(), AssemblyGui::ViewProviderAssemblyLink::setupContextMenu(), PartGui::DlgFilletEdges::setupFillet(), CmdSketcherConstrainTangent::substituteConstraintCombinations(), CmdSketcherConstrainCoincidentUnified::substituteConstraintCombinationsCoincident(), CmdSketcherConstrainCoincidentUnified::substituteConstraintCombinationsPointOnObject(), MeshGui::TaskSmoothing::TaskSmoothing(), FemGui::ViewProviderFemConstraint::unsetEdit(), PartDesignGui::ViewProvider::unsetEdit(), SketcherGui::ViewProviderSketch::unsetEdit(), PartDesignGui::TaskChamferParameters::~TaskChamferParameters(), PartGui::TaskCheckGeometryResults::~TaskCheckGeometryResults(), PartDesignGui::TaskDraftParameters::~TaskDraftParameters(), PartDesignGui::TaskFilletParameters::~TaskFilletParameters(), and PartDesignGui::TaskThicknessParameters::~TaskThicknessParameters().
countObjectsOfType() [1/3]
unsigned int SelectionSingleton::countObjectsOfType (const Base::Type & typeId = App::DocumentObject::getClassTypeId(), const char * pDocName = nullptr, ResolveMode resolve = ResolveMode::OldStyleElement) const protected
Definition at line 527 of file Gui/Selection.cpp.
References _SelList, and getDocument().
countObjectsOfType() [2/3]
template<typename T > unsigned int Gui::SelectionSingleton::countObjectsOfType (const char * pDocName = nullptr, ResolveMode resolve = ResolveMode::OldStyleElement) const inline
Returns the number of selected objects with a special object type It's the convenient way to check if the right objects are selected to perform an operation (GuiCommand). The check also detects base types. E.g. "Part" also fits on "PartImport" or "PartTransform types. If no document name is given the active document is assumed.
Set 'resolve' to true to resolve any sub object inside selection SubName field.
The typename T must be based on App::DocumentObject.
A convenience template-based method that returns the number of objects of the given type.
Definition at line 736 of file Gui/Selection.h.
Referenced by countObjectsOfType(), StdCmdAlignment::isActive(), SketcherGui::isCommandActive(), SketcherGui::isSketcherBSplineActive(), sCountObjectsOfType(), and PartDesignGui::Workbench::setupContextMenu().
countObjectsOfType() [3/3]
unsigned int SelectionSingleton::countObjectsOfType (const char * typeName, const char * pDocName = nullptr, ResolveMode resolve = ResolveMode::OldStyleElement) const
Does basically the same as the method above unless that it accepts a string literal as first argument. typeName must be a registered type, otherwise 0 is returned.
Definition at line 541 of file Gui/Selection.cpp.
References Base::Type::badType(), countObjectsOfType(), and Base::Type::fromName().
destruct()
void SelectionSingleton::destruct () static
Definition at line 1675 of file Gui/Selection.cpp.
References _pcSingleton.
Referenced by Gui::Application::~Application().
disableCommandLog()
int SelectionSingleton::disableCommandLog ()
Definition at line 847 of file Gui/Selection.cpp.
References hasSelection(), logDisabled, and logHasSelection.
Referenced by Gui::SelectionLogDisabler::SelectionLogDisabler().
enableCommandLog()
int SelectionSingleton::enableCommandLog (bool silent = false)
Definition at line 853 of file Gui/Selection.cpp.
References _SelList, Gui::MacroManager::Cmt, hasSelection(), Gui::Application::Instance, logDisabled, logHasSelection, and Gui::Application::macroManager().
Referenced by Gui::SelectionLogDisabler::~SelectionLogDisabler().
enablePickedList()
void SelectionSingleton::enablePickedList (bool enable)
Turn on or off picked list.
Definition at line 385 of file Gui/Selection.cpp.
References _needPickedList, _PickedList, notify(), and Gui::SelectionChanges::PickedListChanged.
Referenced by sEnablePickedList().
getAsPropertyLinkSubList()
int SelectionSingleton::getAsPropertyLinkSubList (App::PropertyLinkSubList & prop) const
getAsPropertyLinkSubList fills PropertyLinkSubList with current selection.
Parameters
prop (output). The property object to receive links
Returns
the number of items written to the link
Definition at line 441 of file Gui/Selection.cpp.
References getSelectionEx(), replaceobj::objs, App::PropertyLinkSubList::setValues(), and importers.importIFCmulticore::subs.
Referenced by SketcherGui::SuggestAutoMapMode().
getCompleteSelection()
std::vector< SelectionSingleton::SelObj > SelectionSingleton::getCompleteSelection (ResolveMode resolve = ResolveMode::OldStyleElement) const
Returns a vector of all selection objects of all documents.
Definition at line 184 of file Gui/Selection.cpp.
References getSelection().
Referenced by StdCmdToggleTransparency::activated(), StdCmdEdit::activated(), Gui::TreeWidget::contextMenuEvent(), StdCmdDelete::isActive(), StdCmdProperties::isActive(), and sGetCompleteSelection().
getDocument()
App::Document * SelectionSingleton::getDocument (const char * pDocName = nullptr) const protected
helper to retrieve document by name
Definition at line 839 of file Gui/Selection.cpp.
References App::Application::getActiveDocument(), App::GetApplication(), and App::Application::getDocument().
Referenced by checkSelection(), clearSelection(), countObjectsOfType(), getObjectList(), getObjectsOfType(), getPickedList(), getSelection(), hasSelection(), hasSubSelection(), setPreselect(), setSelection(), and updateSelection().
getObjectList()
std::vector< SelectionObject > SelectionSingleton::getObjectList (const char * pDocName, Base::Type typeId, std::list< _SelObj > & objs, ResolveMode resolve, bool single = false) const protected
Definition at line 323 of file Gui/Selection.cpp.
References Base::Type::badType(), getDocument(), getObjectOfType(), and Gui::NoResolve.
Referenced by getPickedListEx(), getSelectionEx(), and selStackGet().
getObjectOfType()
App::DocumentObject * SelectionSingleton::getObjectOfType (_SelObj & sel, Base::Type type, ResolveMode resolve, const char ** subelement = nullptr) static protected
Definition at line 467 of file Gui/Selection.cpp.
References Gui::SelectionSingleton::_SelObj::elementName, Gui::FollowLink, App::ElementNamePair::newName, Gui::NewStyleElement, Gui::NoResolve, App::ElementNamePair::oldName, Gui::SelectionSingleton::_SelObj::pObject, Gui::SelectionSingleton::_SelObj::pResolvedObject, and Gui::SelectionSingleton::_SelObj::SubName.
Referenced by addSelection(), getObjectList(), getObjectsOfType(), getSelection(), and hasSelection().
getObjectsOfType() [1/3]
vector< App::DocumentObject * > SelectionSingleton::getObjectsOfType (const Base::Type & typeId, const char * pDocName = nullptr, ResolveMode resolve = ResolveMode::OldStyleElement) const
Returns a vector of objects of type TypeName selected for the given document name pDocName. If no document name is specified the objects from the active document are regarded. If no objects of this document are selected an empty vector is returned.
Note
The vector reflects the sequence of selection.
Definition at line 494 of file Gui/Selection.cpp.
References _SelList, getDocument(), getObjectOfType(), and replaceobj::objs.
Referenced by DrawingGui::TaskProjection::accept(), TechDrawGui::TaskProjection::accept(), ReenGui::FitBSplineSurfaceWidget::accept(), MeshGui::TaskDecimating::accept(), StdCmdExport::activated(), StdCmdToggleSelectability::activated(), StdCmdPlacement::activated(), StdCmdTransformManip::activated(), StdCmdAlignment::activated(), MeshPartGui::CrossSections::apply(), Gui::Dialog::PlacementHandler::computeCenterOfMass(), createDefaultExportBasename(), execSimpleSection(), execStackBottom(), execStackDown(), execStackTop(), execStackUp(), Gui::Application::exportTo(), TechDrawGui::DrawGuiUtil::findPage(), getObjectsOfType(), getSelectedNodes(), PartGui::getShapesFromSelection(), PartGui::hasShapesInSelection(), Gui::MainWindow::insertFromMimeData(), StdCmdPlacement::isActive(), StdCmdTransformManip::isActive(), MeshInfoWatcher::onSelectionChanged(), prepareProfileBased(), prepareTransformed(), TechDrawGui::TaskDimRepair::slotUseSelection(), MeshGui::TaskDecimating::TaskDecimating(), and DrawingGui::TaskOrthoViews::TaskOrthoViews().
getObjectsOfType() [2/3]
template<typename T > std::vector< T * > Gui::SelectionSingleton::getObjectsOfType (const char * pDocName = nullptr, ResolveMode resolve = ResolveMode::OldStyleElement) const inline
A convenience template-based method that returns an array with the correct types already.
Definition at line 745 of file Gui/Selection.h.
References draftutils.utils::getObjectsOfType, and Path.Post.scripts.grbl_post::type.
getObjectsOfType() [3/3]
std::vector< App::DocumentObject * > SelectionSingleton::getObjectsOfType (const char * typeName, const char * pDocName = nullptr, ResolveMode resolve = ResolveMode::OldStyleElement) const
Does basically the same as the method above unless that it accepts a string literal as first argument. typeName must be a registered type otherwise an empty array is returned.
Definition at line 519 of file Gui/Selection.cpp.
References Base::Type::badType(), Base::Type::fromName(), and getObjectsOfType().
getPickedList()
std::vector< SelectionSingleton::SelObj > SelectionSingleton::getPickedList (const char * pDocName) const
Return select objects inside picked list.
Definition at line 281 of file Gui/Selection.cpp.
References _PickedList, Gui::SelectionSingleton::SelObj::DocName, Gui::SelectionSingleton::SelObj::FeatName, getDocument(), Gui::SelectionSingleton::SelObj::pDoc, Gui::SelectionSingleton::SelObj::pObject, Gui::SelectionSingleton::SelObj::pResolvedObject, Gui::SelectionSingleton::SelObj::SubName, Gui::SelectionSingleton::SelObj::TypeName, Gui::SelectionSingleton::SelObj::x, Gui::SelectionSingleton::SelObj::y, and Gui::SelectionSingleton::SelObj::z.
getPickedListEx()
std::vector< SelectionObject > SelectionSingleton::getPickedListEx (const char * pDocName = nullptr, Base::Type typeId = App::DocumentObject::getClassTypeId()) const
Return selected object inside picked list grouped by top level parents.
Definition at line 318 of file Gui/Selection.cpp.
References _PickedList, getObjectList(), and Gui::NoResolve.
Referenced by sGetPickedList().
getPreselection()
const SelectionChanges & SelectionSingleton::getPreselection () const
returns the present preselection
Definition at line 806 of file Gui/Selection.cpp.
References CurrentPreselection.
Referenced by AssemblyGui::ViewProviderAssembly::getSelectedObjectsWithinAssembly(), and sGetPreselection().
getSelectedElement()
const char * SelectionSingleton::getSelectedElement (App::DocumentObject * obj, const char * pSubName) const
Definition at line 1565 of file Gui/Selection.cpp.
References _SelList.
getSelection()
std::vector< SelectionSingleton::SelObj > SelectionSingleton::getSelection (const char * pDocName = nullptr, ResolveMode resolve = ResolveMode::OldStyleElement, bool single = false) const
Returns a vector of selection objects
Parameters
pDocName document name. If no document name is given the objects of the active are returned. If nothing for this Document is selected an empty vector is returned. If document name is "*", then all document is considered.
resolve sub-object resolving mode 0 no resolve, 1 resolve sub-object with old style element name 2 resolve sub-object with new style element name
single if set to true, then it will return an empty vector if there is more than one selections.
Returns
The returned vector reflects the sequence of selection.
Definition at line 189 of file Gui/Selection.cpp.
References _SelList, Gui::SelectionSingleton::SelObj::DocName, Gui::SelectionSingleton::SelObj::FeatName, Base::Persistence::getClassTypeId(), getDocument(), getObjectOfType(), AssemblyImport::insert(), Gui::NoResolve, Gui::SelectionSingleton::SelObj::pDoc, Gui::SelectionSingleton::SelObj::pObject, Gui::SelectionSingleton::SelObj::pResolvedObject, Gui::SelectionSingleton::SelObj::SubName, Gui::SelectionSingleton::SelObj::TypeName, Gui::SelectionSingleton::SelObj::x, Gui::SelectionSingleton::SelObj::y, and Gui::SelectionSingleton::SelObj::z.
Referenced by StdCmdLinkSelectAllLinks::activated(), Gui::View3DInventorViewer::alignToSelection(), Gui::PropertyEditor::PropertyEditor::contextMenuEvent(), FemGui::TaskCreateElementSet::DefineNodes(), getCompleteSelection(), getSelectedLink(), PartGui::TaskCheckGeometryResults::goCheck(), Gui::TaskMeasure::hasSelection(), StdCmdLinkSelectAllLinks::isActive(), Gui::DAG::Model::selectionChanged(), Gui::DocumentItem::selectItems(), Gui::View3DInventorViewer::setDocument(), femguiutils.selection_widgets._Selector::setHelpText(), PartDesignGui::Workbench::setupContextMenu(), and sGetSelection().
getSelectionEx()
std::vector< SelectionObject > SelectionSingleton::getSelectionEx (const char * pDocName = nullptr, Base::Type typeId = App::DocumentObject::getClassTypeId(), ResolveMode resolve = ResolveMode::OldStyleElement, bool single = false) const
Returns a vector of selection objects
Parameters
pDocName document name. If no document name is given the objects of the active are returned. If nothing for this Document is selected an empty vector is returned. If document name is "*", then all document is considered.
typeId specify the type of object to be returned.
resolve sub-object resolving mode. 0 no resolve, 1 resolve sub-object with old style element name 2 resolve sub-object with new style element name
single if set to true, then it will return an empty vector if there is more than one selections.
Returns
The returned vector reflects the sequence of selection.
Definition at line 312 of file Gui/Selection.cpp.
References _SelList, and getObjectList().
Referenced by _checkDrawViewPart(), _checkDrawViewPartBalloon(), TechDrawGui::_checkSel(), TechDrawGui::_checkSelection(), _checkSelection(), _checkSelectionBalloon(), _checkSelectionHatch(), PartGui::Mirroring::accept(), PartGui::SweepWidget::accept(), SketcherCopy::activate(), StdCmdVarSet::activated(), StdCmdDelete::activated(), StdCmdTreeSelectAllInstances::activated(), CmdSketcherConstrainLock::activated(), CmdSketcherConstrainBlock::activated(), CmdSketcherConstrainDistance::activated(), CmdSketcherConstrainDistanceX::activated(), CmdSketcherConstrainDistanceY::activated(), CmdSketcherConstrainParallel::activated(), CmdSketcherConstrainPerpendicular::activated(), CmdSketcherConstrainTangent::activated(), CmdSketcherConstrainRadius::activated(), CmdSketcherConstrainDiameter::activated(), CmdSketcherConstrainRadiam::activated(), CmdSketcherConstrainAngle::activated(), CmdSketcherConstrainEqual::activated(), CmdSketcherConstrainSymmetric::activated(), FemGui::ViewProviderFemAnalysis::checkSelectedChildren(), SketcherGui::ViewProviderSketch::deleteSelected(), SketcherGui::ConstraintView::deleteSelectedItems(), SketcherGui::ElementView::deleteSelectedItems(), dressupGetSelected(), exec2PointCenterLine(), execCenterLine(), execComplexSection(), execCosmeticCircle(), execLine2Points(), TechDraw::CommandHelpers::faceFromSelection(), faceFromSelection(), TechDraw::CommandHelpers::firstNonSpreadsheetInSelection(), TechDraw::CommandHelpers::firstViewInSelection(), SketcherGui::ViewProviderSketch::generateContextMenu(), getAsPropertyLinkSubList(), getListOfSelectedGeoIds(), TechDraw::getReferencesFromSelection(), AssemblyGui::ViewProviderAssembly::getSelectedJoint(), Gui::Dialog::PlacementHandler::getSelectedPoints(), TechDraw::CommandHelpers::getSelectedShapes(), getSelectedShapes(), TechDraw::CommandHelpers::getSelectedSubElements(), horVerActivated(), StdCmdTreeSelectAllInstances::isActive(), Gui::SelectionFilter::match(), TechDrawGui::QGIPrimPath::mousePressEvent(), TechDrawGui::QGIView::mousePressEvent(), CmdSketcherConstrainCoincidentUnified::onActivated(), TechDrawGui::TaskComplexSection::onProfileObjectsUseSelectionClicked(), TechDrawGui::TaskComplexSection::onSectionObjectsUseSelectionClicked(), TechDrawGui::MDIViewPage::onSelectionChanged(), Gui::PropertyView::onTimer(), prepareProfileBased(), TechDrawGui::QGIViewPart::removeSelectedCosmetic(), TechDrawGui::TaskProjGroup::rotateButtonClicked(), TechDrawGui::MDIViewPage::sceneSelectionChanged(), SketcherGui::SketchSelection::setUp(), and sGetSelectionEx().
getSelectionStyle()
SelectionSingleton::SelectionStyle SelectionSingleton::getSelectionStyle ()
Get the style of selection.
Definition at line 1633 of file Gui/Selection.cpp.
References selectionStyle.
Referenced by Gui::SoFCUnifiedSelection::handleEvent(), and TechDrawGui::PreferencesGui::multiSelection().
hasPickedList()
bool SelectionSingleton::hasPickedList () const
Check if there is any selection inside picked list.
Definition at line 436 of file Gui/Selection.cpp.
References _PickedList.
hasPreselection()
bool SelectionSingleton::hasPreselection () const
Check if there is any pre-selection.
Definition at line 180 of file Gui/Selection.cpp.
References CurrentPreselection, App::DocumentObjectT::getObjectName(), and Gui::SelectionChanges::Object.
hasSelection() [1/2]
bool SelectionSingleton::hasSelection () const
Check if there is any selection.
Definition at line 175 of file Gui/Selection.cpp.
References _SelList.
Referenced by disableCommandLog(), enableCommandLog(), StdCmdCopy::isActive(), StdCmdDuplicateSelection::isActive(), Gui::TreeWidget::scrollItemToTop(), and sHasSelection().
hasSelection() [2/2]
bool SelectionSingleton::hasSelection (const char * doc, ResolveMode resolve = ResolveMode::OldStyleElement) const
Check if there is any selection within a given document
Parameters
doc specify the document to check for selection. If NULL, then check the current active document.
resolve whether to resolve the selected sub-object
If resolve is true, then the selection is first resolved before matching its owner document. So in case the selected sub-object is linked from an external document, it may not match the input doc. If resolve is false, then the match is only done with the top level parent object.
Definition at line 239 of file Gui/Selection.cpp.
References _SelList, toolbit-attributes::doc, Base::Persistence::getClassTypeId(), getDocument(), and getObjectOfType().
hasSubSelection()
bool SelectionSingleton::hasSubSelection (const char * doc = nullptr, bool subElement = false) const
Check if there is any sub-element selection
Parameters
doc optional document to check for selection
subElement whether to count sub-element only selection
Example sub selections are face, edge or vertex. If subElement is false, then sub-object (i.e. a group child object) selection is also counted even if it selects the whole sub-object.
Definition at line 259 of file Gui/Selection.cpp.
References _SelList, toolbit-attributes::doc, and getDocument().
Referenced by StdCmdLinkMakeRelative::isActive(), and sHasSubSelection().
instance()
SelectionSingleton & SelectionSingleton::instance () static
Definition at line 1668 of file Gui/Selection.cpp.
References _pcSingleton, and SelectionSingleton().
isSelected() [1/2]
bool SelectionSingleton::isSelected (App::DocumentObject * pObject, const char * pSubName = nullptr, ResolveMode resolve = ResolveMode::OldStyleElement) const
Check if selected.
Definition at line 1474 of file Gui/Selection.cpp.
References _SelList, checkSelection(), App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), and App::DocumentObject::isAttachedToDocument().
isSelected() [2/2]
bool SelectionSingleton::isSelected (const char * pDocName, const char * pObjectName = nullptr, const char * pSubName = nullptr, ResolveMode resolve = ResolveMode::OldStyleElement) const
Check if selected.
Definition at line 1467 of file Gui/Selection.cpp.
References _SelList, and checkSelection().
Referenced by addSelection(), Gui::SoFCUnifiedSelection::doAction(), Gui::SoFCSelection::doAction(), notify(), sIsSelected(), and updateSelection().
needPickedList()
bool SelectionSingleton::needPickedList () const
Check whether picked list is enabled.
Definition at line 380 of file Gui/Selection.cpp.
References _needPickedList.
Referenced by Gui::View3DInventorSelection::checkGroupOnTop().
notify() [1/2]
void Gui::SelectionSingleton::notify (const SelectionChanges & Chng) inline protected
Definition at line 677 of file Gui/Selection.h.
References notify().
Referenced by notify().
notify() [2/2]
void SelectionSingleton::notify (SelectionChanges && Chng) protected
Definition at line 394 of file Gui/Selection.cpp.
References Gui::SelectionChanges::AddSelection, Gui::SelectionChanges::ClrSelection, Base::Console(), CurrentPreselection, isSelected(), Path.Post.scripts.opensbp_post::move(), Path.Op.Surface::msg, Gui::NoResolve, NotificationQueue, Base::Subject< const SelectionChanges & >::Notify(), Notifying, Gui::SelectionChanges::Object, Gui::SelectionChanges::RmvPreselect, Gui::SelectionChanges::RmvSelection, Gui::SelectionChanges::SetPreselect, signalSelectionChanged, Gui::SelectionChanges::Type, and Base::ConsoleSingleton::Warning().
Referenced by addSelection(), addSelections(), clearCompleteSelection(), clearSelection(), enablePickedList(), rmvPreselect(), rmvSelection(), setPreselect(), setSelection(), slotDeletedObject(), and updateSelection().
rmvPreselect()
void SelectionSingleton::rmvPreselect (bool signal = false)
remove the present preselection
Definition at line 772 of file Gui/Selection.cpp.
References Gui::Application::activeDocument(), ActiveGate, CurrentPreselection, DocName, FC_TRACE, FeatName, Gui::Document::getActiveView(), Gui::getMainWindow(), hx, hy, hz, Gui::Application::Instance, Path.Post.scripts.opensbp_post::move(), notify(), Gui::MDIView::restoreOverrideCursor(), Gui::SelectionChanges::RmvPreselect, Gui::SelectionChanges::RmvPreselectSignal, and SubName.
Referenced by addSelection(), clearCompleteSelection(), clearSelection(), Gui::OverlayManager::eventFilter(), Gui::SoFCSelection::handleEvent(), Gui::DockWnd::SelectionView::leaveEvent(), Gui::Dialog::DlgPropertyLink::leaveEvent(), Gui::ElementColors::leaveEvent(), SketcherGui::TaskSketcherElements::leaveEvent(), Gui::TreeWidget::leaveEvent(), SketcherGui::TaskSketcherElements::onListWidgetElementsMouseMoveOnItem(), SketcherGui::DrawSketchHandler::quit(), SketcherGui::ViewProviderSketch::setEdit(), setPreselect(), slotDeletedObject(), sRemPreselection(), and updateSelection().
rmvSelection()
void SelectionSingleton::rmvSelection (const char * pDocName, const char * pObjectName = nullptr, const char * pSubName = nullptr, const std::vector< SelObj > * pickedList = nullptr)
Remove from selection (for internal use)
Definition at line 1192 of file Gui/Selection.cpp.
References _PickedList, _SelList, checkSelection(), Gui::SelectionSingleton::_SelObj::DocName, FC_LOG, Gui::SelectionSingleton::_SelObj::FeatName, Gui::getMainWindow(), Path.Post.scripts.opensbp_post::move(), Gui::NoResolve, notify(), Gui::SelectionChanges::PickedListChanged, Gui::SelectionChanges::RmvSelection, toolbit-attributes::s, Gui::SelectionSingleton::_SelObj::SubName, and Gui::MainWindow::updateActions().
Referenced by Gui::SoFCSelection::handleEvent(), Gui::DAG::Model::mousePressEvent(), TDHandlerDimension::mouseReleaseEvent(), Gui::ElementColors::Private::onSelectionChanged(), TDHandlerDimension::onSelectionChanged(), DrawSketchHandlerDimension::releaseButton(), TechDrawGui::MDIViewPage::removeUnselectedTreeSelection(), sRemoveSelection(), and Gui::DocumentItem::updateItemSelection().
rmvSelectionGate()
void SelectionSingleton::rmvSelectionGate ()
remove the active SelectionGate
Definition at line 822 of file Gui/Selection.cpp.
References Gui::Application::activeDocument(), ActiveGate, toolbit-attributes::doc, Gui::Application::Instance, and Gui::MDIView::restoreOverrideCursor().
Referenced by PartGui::Mirroring::accept(), SurfaceGui::FillingEdgePanel::accept(), SurfaceGui::GeomFillSurface::accept(), SurfaceGui::SectionsPanel::accept(), SurfaceGui::FillingPanel::accept(), addSelectionGate(), Gui::SelectionObserver::detachSelection(), PartDesignGui::TaskTransformedParameters::exitSelectionMode(), FemGui::TaskCreateNodeSet::onSelectionChanged(), FemGui::TaskCreateElementSet::onSelectionChanged(), SurfaceGui::FillingPanel::onSelectionChanged(), PartDesignGui::TaskSketchBasedParameters::onSelectReference(), SketcherGui::DrawSketchHandler::quit(), PartGui::Mirroring::reject(), SurfaceGui::FillingEdgePanel::reject(), SurfaceGui::GeomFillSurface::reject(), SurfaceGui::SectionsPanel::reject(), SurfaceGui::FillingPanel::reject(), PartDesignGui::TaskDressUpParameters::setSelectionMode(), sRemoveSelectionGate(), PartGui::DlgExtrusion::~DlgExtrusion(), PartGui::DlgFilletEdges::~DlgFilletEdges(), PartGui::DlgProjectionOnSurface::~DlgProjectionOnSurface(), PartGui::DlgProjectOnSurface::~DlgProjectOnSurface(), PartGui::DlgRevolution::~DlgRevolution(), SketcherGui::DrawSketchHandlerFillet::~DrawSketchHandlerFillet(), DrawSketchHandlerGenConstraint::~DrawSketchHandlerGenConstraint(), Gui::ElementColors::~ElementColors(), PartGui::FaceAppearances::~FaceAppearances(), SurfaceGui::FillingEdgePanel::~FillingEdgePanel(), SurfaceGui::FillingVertexPanel::~FillingVertexPanel(), PartGui::ShapeBuilderWidget::~ShapeBuilderWidget(), PartGui::SweepWidget::~SweepWidget(), PartDesignGui::TaskChamferParameters::~TaskChamferParameters(), FemGui::TaskCreateNodeSet::~TaskCreateNodeSet(), PartDesignGui::TaskDatumParameters::~TaskDatumParameters(), PartDesignGui::TaskDraftParameters::~TaskDraftParameters(), PartDesignGui::TaskDressUpParameters::~TaskDressUpParameters(), PartDesignGui::TaskFilletParameters::~TaskFilletParameters(), PartDesignGui::TaskSketchBasedParameters::~TaskSketchBasedParameters(), PartDesignGui::TaskThicknessParameters::~TaskThicknessParameters(), PartDesignGui::TaskTransformedParameters::~TaskTransformedParameters(), and PartGui::ThicknessWidget::~ThicknessWidget().
sAddSelection()
PyObject * SelectionSingleton::sAddSelection (PyObject * self, PyObject * args) static protected
Definition at line 1907 of file Gui/Selection.cpp.
References addSelection(), toolbit-attributes::args, Base::asBoolean(), App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), App::DocumentObject::isAttachedToDocument(), Py_Return, Base::PyExc_FC_GeneralError, Gui::Selection(), src.Mod.Test.testmakeWireString::String, MovieTool::x, and MovieTool::y.
sAddSelectionGate()
PyObject * SelectionSingleton::sAddSelectionGate (PyObject * self, PyObject * args) static protected
Definition at line 2344 of file Gui/Selection.cpp.
References addSelectionGate(), toolbit-attributes::args, Gui::SelectionFilterPy::cast(), PY_CATCH, Py_Return, PY_TRY, and Gui::Selection().
sAddSelObserver()
PyObject * SelectionSingleton::sAddSelObserver (PyObject * self, PyObject * args) static protected
Definition at line 2317 of file Gui/Selection.cpp.
References Gui::SelectionObserverPython::addObserver(), toolbit-attributes::args, src.Mod.Test.testPathArray::o, PY_CATCH, Py_Return, and PY_TRY.
sClearSelection()
PyObject * SelectionSingleton::sClearSelection (PyObject * self, PyObject * args) static protected
Definition at line 2027 of file Gui/Selection.cpp.
References toolbit-attributes::args, Base::asBoolean(), clearSelection(), Py_Return, and Gui::Selection().
sCountObjectsOfType()
PyObject * SelectionSingleton::sCountObjectsOfType (PyObject * self, PyObject * args) static protected
Definition at line 2079 of file Gui/Selection.cpp.
References toolbit-attributes::args, src.Mod.AddonManager.NetworkManager::count, countObjectsOfType(), SCL.SimpleDataTypes::e, and Gui::Selection().
selStackBackSize()
std::size_t Gui::SelectionSingleton::selStackBackSize () const inline
Return the current selection stack size.
Definition at line 536 of file Gui/Selection.h.
Referenced by StdCmdSelBack::isActive().
selStackForwardSize()
std::size_t Gui::SelectionSingleton::selStackForwardSize () const inline
Return the current forward selection stack size.
Definition at line 542 of file Gui/Selection.h.
Referenced by StdCmdSelForward::isActive().
selStackGet()
std::vector< SelectionObject > SelectionSingleton::selStackGet (const char * pDocName = nullptr, ResolveMode resolve = ResolveMode::OldStyleElement, int index = 0) const
Obtain selected objects from stack
Parameters
pDocName optional filtering document, NULL for current active document
resolve sub-object resolving mode. 0 no resolve, 1 resolve sub-object with old style element name 2 resolve sub-object with new style element name
index optional position in the stack
Definition at line 1063 of file Gui/Selection.cpp.
References _SelStackBack, _SelStackForward, checkSelection(), Base::Persistence::getClassTypeId(), getObjectList(), and Gui::NoResolve.
Referenced by sGetSelectionFromStack().
selStackGoBack()
void SelectionSingleton::selStackGoBack (int count = 1)
Go back selection history
Parameters
count optional number of steps to go back
This function pops the selection stack, and populate the current selection with the content of the last pop'd entry
Definition at line 994 of file Gui/Selection.cpp.
References _SelList, _SelStackBack, _SelStackForward, addSelection(), clearCompleteSelection(), src.Mod.AddonManager.NetworkManager::count, Gui::getMainWindow(), SplineSurface::i, Path.Post.scripts.opensbp_post::move(), selStackPush(), and Gui::MainWindow::updateActions().
Referenced by StdCmdSelBack::activated().
selStackGoForward()
void SelectionSingleton::selStackGoForward (int count = 1)
Go forward selection history
Parameters
count optional number of steps to go back
This function pops the selection stack, and populate the current selection with the content of the last pop'd entry
Definition at line 1029 of file Gui/Selection.cpp.
References _SelList, _SelStackBack, _SelStackForward, addSelection(), clearCompleteSelection(), src.Mod.AddonManager.NetworkManager::count, Gui::getMainWindow(), SplineSurface::i, Path.Post.scripts.opensbp_post::move(), selStackPush(), and Gui::MainWindow::updateActions().
Referenced by StdCmdSelForward::activated().
selStackPush()
void SelectionSingleton::selStackPush (bool clearForward = true, bool overwrite = false)
Save the current selection on to the stack
Parameters
clearForward whether to clear forward selection stack
overwrite whether to overwrite the current top entry of the stack instead of pushing a new entry.
Definition at line 972 of file Gui/Selection.cpp.
References _SelList, _SelStackBack, _SelStackForward, App::GetApplication(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), and Path.Post.scripts.opensbp_post::move().
Referenced by StdCmdLinkMakeGroup::activated(), StdCmdLinkMake::activated(), StdCmdLinkMakeRelative::activated(), StdCmdLinkSelectLinked::activated(), StdCmdLinkSelectLinkedFinal::activated(), StdCmdLinkSelectAllLinks::activated(), StdCmdTreeSelectAllInstances::activated(), Gui::Dialog::DlgPropertyLink::attachObserver(), Gui::TreeWidget::itemSearch(), linkConvert(), Gui::PropertyEditor::LinkSelection::select(), Gui::TreeWidget::selectAll(), selStackGoBack(), selStackGoForward(), PartDesignGui::ViewProviderSubShapeBinder::setEdit(), and sPushSelStack().
sEnablePickedList()
PyObject * SelectionSingleton::sEnablePickedList (PyObject * self, PyObject * args) static protected
Definition at line 2131 of file Gui/Selection.cpp.
References toolbit-attributes::args, Base::asBoolean(), enablePickedList(), Py_Return, and Gui::Selection().
setPreselect()
int SelectionSingleton::setPreselect (const char * pDocName, const char * pObjectName, const char * pSubName, float x = 0, float y = 0, float z = 0, SelectionChanges::MsgSource signal = SelectionChanges::MsgSource::Any)
set the preselected object (mostly by the 3D view)
Definition at line 597 of file Gui/Selection.cpp.
References Gui::Application::activeDocument(), ActiveGate, Gui::SelectionGate::allow(), CurrentPreselection, DocName, FC_TRACE, FeatName, gateResolve, Gui::Document::getActiveView(), getDocument(), Gui::getMainWindow(), App::Document::getObject(), hx, hy, hz, Gui::Application::Instance, Gui::SelectionChanges::Internal, Path.Post.scripts.opensbp_post::move(), Path.Op.Surface::msg, Data::newElementName(), App::ElementNamePair::newName, Gui::NoResolve, Gui::SelectionGate::notAllowedReason, notify(), Data::oldElementName(), App::ElementNamePair::oldName, Gui::OldStyleElement, App::GeoFeature::resolveElement(), Gui::MDIView::restoreOverrideCursor(), rmvPreselect(), Gui::MDIView::setOverrideCursor(), Gui::SelectionChanges::SetPreselect, Gui::SelectionChanges::SetPreselectSignal, Gui::MainWindow::showMessage(), SubName, src.Mod.AddonManager.Addon::translate, Gui::SelectionChanges::Type, MovieTool::x, and MovieTool::y.
Referenced by Gui::SoFCSelection::handleEvent(), Gui::TreeWidget::itemSearch(), SketcherGui::TaskSketcherElements::onListWidgetElementsMouseMoveOnItem(), Gui::TreeWidget::onPreSelectTimer(), TechDrawGui::MDIViewPage::preSelectionChanged(), and sSetPreselection().
setPreselectCoord()
void SelectionSingleton::setPreselectCoord (float x, float y, float z)
sets different coords for the preselection
Definition at line 756 of file Gui/Selection.cpp.
References CurrentPreselection, App::DocumentObjectT::getObjectName(), Gui::SelectionChanges::Object, Gui::SelectionChanges::pDocName, Gui::SelectionChanges::pObjectName, Gui::printPreselectionInfo(), Gui::SelectionChanges::pSubName, MovieTool::x, Gui::SelectionChanges::x, MovieTool::y, Gui::SelectionChanges::y, and Gui::SelectionChanges::z.
Referenced by Gui::SoFCSelection::handleEvent().
setSelection()
void SelectionSingleton::setSelection (const char * pDocName, const std::vector< App::DocumentObject * > & sel)
Set the selection for a document.
Definition at line 1357 of file Gui/Selection.cpp.
References _PickedList, _SelList, _SelStackForward, checkSelection(), getDocument(), Gui::getMainWindow(), Gui::NoResolve, notify(), Gui::SelectionChanges::PickedListChanged, Gui::SelectionChanges::SetSelection, and Gui::MainWindow::updateActions().
Referenced by StdCmdSelectVisibleObjects::activated(), StdCmdSelectAll::activated(), FemGui::ViewProviderFemAnalysis::doubleClicked(), Gui::TreeWidget::selectAll(), and Gui::View3DInventorViewer::selectAll().
setSelectionStyle()
void SelectionSingleton::setSelectionStyle (SelectionStyle selStyle)
Changes the style of selection between greedy and normal.
Definition at line 1628 of file Gui/Selection.cpp.
References selectionStyle.
Referenced by TDHandlerDimension::activated(), TDHandlerDimension::deactivated(), sSetSelectionStyle(), Gui::TaskMeasure::TaskMeasure(), and Gui::TaskMeasure::~TaskMeasure().
setVisible()
void SelectionSingleton::setVisible (VisibleState visible)
Set selection object visibility
Parameters
visible see VisibleState
Definition at line 1270 of file Gui/Selection.cpp.
References _SelList, toolbit-attributes::doc, App::GetApplication(), App::Application::getDocument(), Gui::Application::getViewProvider(), Gui::Application::Instance, App::DocumentObject::isAttachedToDocument(), Gui::ViewProvider::isShow(), Init::parent, App::DocumentObject::resolve(), updateSelection(), VisShow, and VisToggle.
Referenced by StdCmdToggleVisibility::activated(), StdCmdShowSelection::activated(), StdCmdHideSelection::activated(), and sSetVisible().
sGetCompleteSelection()
PyObject * SelectionSingleton::sGetCompleteSelection (PyObject * self, PyObject * args) static protected
Definition at line 2190 of file Gui/Selection.cpp.
References Gui::SelectionChanges::AddSelection, toolbit-attributes::args, SCL.SimpleDataTypes::e, getCompleteSelection(), Gui::SelectionObject::getPyObject(), Py::new_reference_to(), and Gui::Selection().
sGetPickedList()
PyObject * SelectionSingleton::sGetPickedList (PyObject * self, PyObject * args) static protected
Definition at line 2249 of file Gui/Selection.cpp.
References toolbit-attributes::args, getPickedListEx(), Py::new_reference_to(), and Gui::Selection().
sGetPreselection()
PyObject * SelectionSingleton::sGetPreselection (PyObject * self, PyObject * args) static protected
Definition at line 2169 of file Gui/Selection.cpp.
References toolbit-attributes::args, getPreselection(), Gui::SelectionObject::getPyObject(), and Gui::Selection().
sGetSelection()
PyObject * SelectionSingleton::sGetSelection (PyObject * self, PyObject * args) static protected
Definition at line 2097 of file Gui/Selection.cpp.
References toolbit-attributes::args, Base::asBoolean(), SCL.SimpleDataTypes::e, getSelection(), Py::new_reference_to(), and Gui::Selection().
sGetSelectionEx()
PyObject * SelectionSingleton::sGetSelectionEx (PyObject * self, PyObject * args) static protected
Definition at line 2221 of file Gui/Selection.cpp.
References toolbit-attributes::args, Base::asBoolean(), SCL.SimpleDataTypes::e, Base::Persistence::getClassTypeId(), getSelectionEx(), Py::new_reference_to(), and Gui::Selection().
sGetSelectionFromStack()
PyObject * SelectionSingleton::sGetSelectionFromStack (PyObject * self, PyObject * args) static protected
Definition at line 2457 of file Gui/Selection.cpp.
References toolbit-attributes::args, Py::new_reference_to(), PY_CATCH, PY_TRY, Gui::Selection(), and selStackGet().
sGetSelectionObject()
PyObject * SelectionSingleton::sGetSelectionObject (PyObject * self, PyObject * args) static protected
Definition at line 2270 of file Gui/Selection.cpp.
References toolbit-attributes::args, Gui::SelectionObject::DocName, SCL.SimpleDataTypes::e, Gui::SelectionObject::FeatName, Gui::SelectionObject::getPyObject(), Gui::SelectionObject::SelPoses, Gui::SelectionObject::SubNames, InitGui::t, MovieTool::x, and MovieTool::y.
sHasSelection()
PyObject * SelectionSingleton::sHasSelection (PyObject * self, PyObject * args) static protected
Definition at line 2424 of file Gui/Selection.cpp.
References toolbit-attributes::args, toolbit-attributes::doc, hasSelection(), Py::new_reference_to(), PY_CATCH, PY_TRY, and Gui::Selection().
sHasSubSelection()
PyObject * SelectionSingleton::sHasSubSelection (PyObject * self, PyObject * args) static protected
Definition at line 2443 of file Gui/Selection.cpp.
References toolbit-attributes::args, Base::asBoolean(), toolbit-attributes::doc, hasSubSelection(), Py::new_reference_to(), PY_CATCH, PY_TRY, and Gui::Selection().
sIsSelected()
PyObject * SelectionSingleton::sIsSelected (PyObject * self, PyObject * args) static protected
Definition at line 2059 of file Gui/Selection.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, isSelected(), and Gui::Selection().
size()
unsigned int Gui::SelectionSingleton::size () const inline
Size of selected entities for all documents.
Definition at line 525 of file Gui/Selection.h.
Referenced by Path.Post.Utils.GCodeEditorDialog::done().
slotDeletedObject()
void SelectionSingleton::slotDeletedObject (const App::DocumentObject & Obj) protected
Observer message from the App doc.
Definition at line 1584 of file Gui/Selection.cpp.
References _PickedList, _SelList, FC_LOG, App::DocumentObject::getDocument(), Gui::getMainWindow(), App::Document::getName(), App::DocumentObject::getNameInDocument(), App::DocumentObject::isAttachedToDocument(), Path.Post.scripts.opensbp_post::move(), notify(), Gui::SelectionChanges::PickedListChanged, rmvPreselect(), Gui::SelectionChanges::RmvSelection, and Gui::MainWindow::updateActions().
Referenced by SelectionSingleton().
slotSelectionChanged()
void SelectionSingleton::slotSelectionChanged (const SelectionChanges & msg) protected
Definition at line 550 of file Gui/Selection.cpp.
References Base::Console(), App::SubObjectT::getSubName(), Gui::SelectionChanges::HideSelection, Path.Op.Surface::msg, Data::newElementName(), App::ElementNamePair::newName, Gui::SelectionChanges::Object, Data::oldElementName(), App::ElementNamePair::oldName, Gui::SelectionChanges::pOriginalMsg, Gui::SelectionChanges::pSubName, App::GeoFeature::resolveElement(), Gui::SelectionChanges::SetPreselectSignal, App::SubObjectT::setSubName(), Gui::SelectionChanges::ShowSelection, signalSelectionChanged2, signalSelectionChanged3, and Base::ConsoleSingleton::Warning().
Referenced by SelectionSingleton().
sPreselect()
static PyObject* Gui::SelectionSingleton::sPreselect (PyObject * self, PyObject * args) static protected
sPushSelStack()
PyObject * SelectionSingleton::sPushSelStack (PyObject * self, PyObject * args) static protected
Definition at line 2412 of file Gui/Selection.cpp.
References toolbit-attributes::args, Base::asBoolean(), Path.Op.Gui.Selection::clear(), Py_Return, Gui::Selection(), and selStackPush().
sRemoveSelection()
PyObject * SelectionSingleton::sRemoveSelection (PyObject * self, PyObject * args) static protected
Definition at line 1997 of file Gui/Selection.cpp.
References toolbit-attributes::args, App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), App::DocumentObject::isAttachedToDocument(), Py_Return, Base::PyExc_FC_GeneralError, rmvSelection(), and Gui::Selection().
sRemoveSelectionGate()
PyObject * SelectionSingleton::sRemoveSelectionGate (PyObject * self, PyObject * args) static protected
Definition at line 2382 of file Gui/Selection.cpp.
References toolbit-attributes::args, PY_CATCH, Py_Return, PY_TRY, rmvSelectionGate(), and Gui::Selection().
sRemPreselection()
PyObject * SelectionSingleton::sRemPreselection (PyObject * self, PyObject * args) static protected
Definition at line 2180 of file Gui/Selection.cpp.
References toolbit-attributes::args, Py_Return, rmvPreselect(), and Gui::Selection().
sRemSelObserver()
PyObject * SelectionSingleton::sRemSelObserver (PyObject * self, PyObject * args) static protected
Definition at line 2331 of file Gui/Selection.cpp.
References toolbit-attributes::args, src.Mod.Test.testPathArray::o, PY_CATCH, Py_Return, PY_TRY, and Gui::SelectionObserverPython::removeObserver().
sSetPreselection()
PyObject * SelectionSingleton::sSetPreselection (PyObject * self, PyObject * args, PyObject * kwd) static protected
Definition at line 2142 of file Gui/Selection.cpp.
References toolbit-attributes::args, App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), App::DocumentObject::isAttachedToDocument(), Py_Return, Base::PyExc_FC_GeneralError, Gui::Selection(), setPreselect(), Path.Post.scripts.grbl_post::type, Base::Wrapped_ParseTupleAndKeywords(), MovieTool::x, and MovieTool::y.
sSetSelectionStyle()
PyObject * SelectionSingleton::sSetSelectionStyle (PyObject * self, PyObject * args) static protected
Definition at line 2304 of file Gui/Selection.cpp.
References toolbit-attributes::args, GreedySelection, NormalSelection, PY_CATCH, Py_Return, PY_TRY, Gui::Selection(), and setSelectionStyle().
sSetVisible()
PyObject * SelectionSingleton::sSetVisible (PyObject * self, PyObject * args) static protected
Definition at line 2394 of file Gui/Selection.cpp.
References toolbit-attributes::args, PY_CATCH, Py_Return, PY_TRY, Base::PyTypeCheck(), Gui::Selection(), setVisible(), VisHide, VisShow, and VisToggle.
sUpdateSelection()
PyObject * SelectionSingleton::sUpdateSelection (PyObject * self, PyObject * args) static protected
Definition at line 1974 of file Gui/Selection.cpp.
References toolbit-attributes::args, Base::asBoolean(), App::DocumentObject::getDocument(), App::Document::getName(), App::DocumentObject::getNameInDocument(), App::DocumentObject::isAttachedToDocument(), Py_Return, Base::PyExc_FC_GeneralError, Gui::Selection(), bimcommands.BimViews::show(), and updateSelection().
updateSelection()
bool SelectionSingleton::updateSelection (bool show, const char * pDocName, const char * pObjectName = nullptr, const char * pSubName = nullptr)
Update a selection.
Definition at line 1130 of file Gui/Selection.cpp.
References DocName, FC_LOG, FC_TRACE, FeatName, getDocument(), Gui::SelectionChanges::HideSelection, isSelected(), Path.Post.scripts.opensbp_post::move(), Gui::NoResolve, notify(), Gui::SelectionChanges::pDocName, Gui::SelectionChanges::pObjectName, Gui::SelectionChanges::pSubName, rmvPreselect(), Gui::SelectionChanges::SetPreselectSignal, bimcommands.BimViews::show(), Gui::SelectionChanges::ShowSelection, and SubName.
Referenced by Path.Op.Gui.Base.TaskPanel::addSelection(), Path.Main.Gui.Job.TaskPanel::addSelection(), Path.Op.Gui.Base.TaskPanel::clearSelection(), Path.Main.Gui.Job.TaskPanel::clearSelection(), Path.Base.Gui.PreferencesAdvanced.AdvancedPreferencesPage::loadSettings(), Path.Op.Gui.Base.TaskPanel::removeSelection(), Path.Main.Gui.Job.TaskPanel::removeSelection(), Path.Op.Gui.Base.TaskPanelDepthsPage::setFields(), Path.Op.Gui.Base.TaskPanel::setSelection(), Path.Main.Gui.Job.TaskPanel::setSelection(), Path.Main.Gui.Job.TaskPanel::setupUi(), setVisible(), and sUpdateSelection().
Friends And Related Function Documentation
SelectionFilter
friend class SelectionFilter friend
Definition at line 624 of file Gui/Selection.h.
Member Data Documentation
_needPickedList
bool Gui::SelectionSingleton::_needPickedList {false} protected
Definition at line 699 of file Gui/Selection.h.
Referenced by enablePickedList(), and needPickedList().
_pcSingleton
SelectionSingleton * SelectionSingleton::_pcSingleton = nullptr static protected
Definition at line 716 of file Gui/Selection.h.
Referenced by destruct(), and instance().
_PickedList
std::list<_SelObj> Gui::SelectionSingleton::_PickedList mutable protected
Definition at line 698 of file Gui/Selection.h.
Referenced by addSelection(), addSelections(), clearCompleteSelection(), clearSelection(), enablePickedList(), getPickedList(), getPickedListEx(), hasPickedList(), rmvSelection(), setSelection(), and slotDeletedObject().
_SelList
std::list<_SelObj> Gui::SelectionSingleton::_SelList mutable protected
Definition at line 696 of file Gui/Selection.h.
Referenced by addSelection(), addSelections(), checkSelection(), clearCompleteSelection(), clearSelection(), countObjectsOfType(), enableCommandLog(), getObjectsOfType(), getSelectedElement(), getSelection(), getSelectionEx(), hasSelection(), hasSubSelection(), isSelected(), rmvSelection(), selStackGoBack(), selStackGoForward(), selStackPush(), setSelection(), setVisible(), and slotDeletedObject().
_SelStackBack
std::deque<SelStackItem> Gui::SelectionSingleton::_SelStackBack protected
Definition at line 702 of file Gui/Selection.h.
Referenced by selStackGet(), selStackGoBack(), selStackGoForward(), and selStackPush().
_SelStackForward
std::deque<SelStackItem> Gui::SelectionSingleton::_SelStackForward protected
Definition at line 703 of file Gui/Selection.h.
Referenced by addSelection(), addSelections(), selStackGet(), selStackGoBack(), selStackGoForward(), selStackPush(), and setSelection().
ActiveGate
Gui::SelectionGate* Gui::SelectionSingleton::ActiveGate protected
Definition at line 723 of file Gui/Selection.h.
Referenced by addSelection(), addSelectionGate(), rmvPreselect(), rmvSelectionGate(), SelectionSingleton(), and setPreselect().
CurrentPreselection
SelectionChanges Gui::SelectionSingleton::CurrentPreselection protected
Definition at line 671 of file Gui/Selection.h.
Referenced by getPreselection(), hasPreselection(), notify(), rmvPreselect(), setPreselect(), and setPreselectCoord().
DocName
std::string Gui::SelectionSingleton::DocName protected
Definition at line 718 of file Gui/Selection.h.
Referenced by clearSelection(), rmvPreselect(), setPreselect(), src.Mod.Test.Document.DocumentPlatformCases::testColorList(), src.Mod.Test.Document.DocumentPlatformCases::testFloatList(), src.Mod.Test.Document.DocumentPlatformCases::testPoints(), src.Mod.Test.Document.DocumentPlatformCases::testVectorList(), and updateSelection().
FeatName
std::string Gui::SelectionSingleton::FeatName protected
Definition at line 719 of file Gui/Selection.h.
Referenced by rmvPreselect(), setPreselect(), and updateSelection().
gateResolve
ResolveMode Gui::SelectionSingleton::gateResolve protected
Definition at line 724 of file Gui/Selection.h.
Referenced by addSelection(), addSelectionGate(), SelectionSingleton(), and setPreselect().
hx
float Gui::SelectionSingleton::hx protected
Definition at line 721 of file Gui/Selection.h.
Referenced by rmvPreselect(), SelectionSingleton(), and setPreselect().
hy
float Gui::SelectionSingleton::hy protected
Definition at line 721 of file Gui/Selection.h.
Referenced by rmvPreselect(), SelectionSingleton(), and setPreselect().
hz
float Gui::SelectionSingleton::hz protected
Definition at line 721 of file Gui/Selection.h.
Referenced by rmvPreselect(), SelectionSingleton(), and setPreselect().
logDisabled
int Gui::SelectionSingleton::logDisabled = 0 protected
Definition at line 726 of file Gui/Selection.h.
Referenced by addSelection(), clearCompleteSelection(), clearSelection(), disableCommandLog(), and enableCommandLog().
logHasSelection
bool Gui::SelectionSingleton::logHasSelection = false protected
Definition at line 727 of file Gui/Selection.h.
Referenced by disableCommandLog(), and enableCommandLog().
Methods
PyMethodDef SelectionSingleton::Methods static
Definition at line 627 of file Gui/Selection.h.
Referenced by Gui::Application::Application().
NotificationQueue
std::deque<SelectionChanges> Gui::SelectionSingleton::NotificationQueue protected
Definition at line 673 of file Gui/Selection.h.
Referenced by notify().
Notifying
bool Gui::SelectionSingleton::Notifying = false protected
Definition at line 674 of file Gui/Selection.h.
Referenced by notify().
selectionStyle
SelectionStyle Gui::SelectionSingleton::selectionStyle protected
Definition at line 729 of file Gui/Selection.h.
Referenced by getSelectionStyle(), and setSelectionStyle().
signalSelectionChanged
boost::signals2::signal<void (const SelectionChanges& msg)> Gui::SelectionSingleton::signalSelectionChanged
signal on new object
Definition at line 441 of file Gui/Selection.h.
Referenced by Gui::SelectionObserver::attachSelection(), notify(), and SelectionSingleton().
signalSelectionChanged2
boost::signals2::signal<void (const SelectionChanges& msg)> Gui::SelectionSingleton::signalSelectionChanged2
signal on selection change with resolved object
Definition at line 444 of file Gui/Selection.h.
Referenced by Gui::SelectionObserver::attachSelection(), and slotSelectionChanged().
signalSelectionChanged3
boost::signals2::signal<void (const SelectionChanges& msg)> Gui::SelectionSingleton::signalSelectionChanged3
signal on selection change with resolved object and sub element map
Definition at line 446 of file Gui/Selection.h.
Referenced by Gui::SelectionObserver::attachSelection(), and slotSelectionChanged().
SubName
std::string Gui::SelectionSingleton::SubName protected
Definition at line 720 of file Gui/Selection.h.
Referenced by rmvPreselect(), setPreselect(), and updateSelection().
The documentation for this class was generated from the following files:
Gui/Selection.h
Gui/Selection.cpp