FreeCAD: SoFCMeshObject.cpp File Reference
SoFCMeshObject.cpp File Reference
#include "PreCompiled.h"
#include <algorithm>
#include <climits>
#include <GL/gl.h>
#include <GL/glu.h>
#include <Inventor/SbLine.h>
#include <Inventor/SoPickedPoint.h>
#include <Inventor/SoPrimitiveVertex.h>
#include <Inventor/actions/SoCallbackAction.h>
#include <Inventor/actions/SoGetBoundingBoxAction.h>
#include <Inventor/actions/SoGetPrimitiveCountAction.h>
#include <Inventor/actions/SoGLRenderAction.h>
#include <Inventor/actions/SoPickAction.h>
#include <Inventor/actions/SoSearchAction.h>
#include <Inventor/bundles/SoMaterialBundle.h>
#include <Inventor/bundles/SoTextureCoordinateBundle.h>
#include <Inventor/details/SoFaceDetail.h>
#include <Inventor/details/SoLineDetail.h>
#include <Inventor/misc/SoState.h>
#include <Base/Console.h>
#include <Base/Exception.h>
#include <Gui/SoFCInteractiveElement.h>
#include <Gui/SoFCSelectionAction.h>
#include <Mod/Mesh/App/Core/Algorithm.h>
#include <Mod/Mesh/App/Core/Elements.h>
#include <Mod/Mesh/App/Core/Grid.h>
#include <Mod/Mesh/App/Core/MeshKernel.h>
#include "SoFCMeshObject.h"
Classes
class SoOutputStreambuf
class SoOutputStream
class SoInputStreambuf
class SoInputStream
Macros
#define RENDER_GLARRAYS
Functions
SO_SFIELD_SOURCE (SoSFMeshObject, Base::Reference< const Mesh::MeshObject >, Base::Reference< const Mesh::MeshObject >) void SoSFMeshObject
void glVertex (const MeshCore::MeshPoint &_v)
void glNormal (const Base::Vector3f &_n)
void glNormal (float *n)
SbVec3f sbvec3f (const Base::Vector3f &_v)
Macro Definition Documentation
RENDER_GLARRAYS
#define RENDER_GLARRAYS
Definition at line 624 of file SoFCMeshObject.cpp.
Function Documentation
glNormal() [1/2]
void glNormal (const Base::Vector3f & _n) inline
Definition at line 581 of file SoFCMeshObject.cpp.
References Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
glNormal() [2/2]
void glNormal (float * n) inline
Definition at line 591 of file SoFCMeshObject.cpp.
glVertex()
void glVertex (const MeshCore::MeshPoint & _v) inline
Definition at line 571 of file SoFCMeshObject.cpp.
References TestSpreadsheet::v, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
sbvec3f()
SbVec3f sbvec3f (const Base::Vector3f & _v) inline
Definition at line 597 of file SoFCMeshObject.cpp.
References Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by MeshGui::SoFCMeshObjectShape::generatePrimitives(), MeshGui::SoFCMeshSegmentShape::generatePrimitives(), and MeshGui::SoFCMeshObjectBoundary::generatePrimitives().
SO_SFIELD_SOURCE()
SO_SFIELD_SOURCE (SoSFMeshObject , Base::Reference< const Mesh::MeshObject > , Base::Reference< const Mesh::MeshObject >)
Definition at line 180 of file SoFCMeshObject.cpp.