FreeCAD: MeshGui::Selection Class Reference
MeshGui::Selection Class Reference
#include <Selection.h>
Public Member Functions
Selection (QWidget *parent=nullptr)
~Selection () override
void setObjects (const std::vector< Gui::SelectionObject > &)
std::vector< App::DocumentObject * > getObjects () const
bool eventFilter (QObject *, QEvent *) override
Detailed Description
Definition at line 58 of file Mod/Mesh/Gui/Selection.h.
Constructor & Destructor Documentation
Selection()
Selection::Selection (QWidget * parent = nullptr) explicit
Definition at line 33 of file Mod/Mesh/Gui/Selection.cpp.
References MeshGui::MeshSelection::setCheckOnlyPointToUserTriangles(), MeshGui::MeshSelection::setCheckOnlyVisibleTriangles(), and MeshGui::MeshSelection::setEnabledViewerSelection().
~Selection()
Selection::~Selection () override
Definition at line 50 of file Mod/Mesh/Gui/Selection.cpp.
References MeshGui::MeshSelection::clearSelection(), and MeshGui::MeshSelection::setEnabledViewerSelection().
Member Function Documentation
eventFilter()
bool Selection::eventFilter (QObject * o, QEvent * e) override
Definition at line 82 of file Mod/Mesh/Gui/Selection.cpp.
References SCL.SimpleDataTypes::e, and src.Mod.Test.testPathArray::o.
getObjects()
std::vector< App::DocumentObject * > Selection::getObjects () const
Definition at line 77 of file Mod/Mesh/Gui/Selection.cpp.
References MeshGui::MeshSelection::getObjects().
Referenced by MeshGui::TaskSmoothing::accept().
setObjects()
void Selection::setObjects (const std::vector< Gui::SelectionObject > & o)
Definition at line 72 of file Mod/Mesh/Gui/Selection.cpp.
References src.Mod.Test.testPathArray::o, and MeshGui::MeshSelection::setObjects().
Referenced by MeshGui::TaskSmoothing::TaskSmoothing().
The documentation for this class was generated from the following files:
Mod/Mesh/Gui/Selection.h
Mod/Mesh/Gui/Selection.cpp