FreeCAD: Gui::TaskView::TaskDialogPy Class Reference
Gui::TaskView::TaskDialogPy Class Reference
The TaskDialogPy class This class exposes a TaskDialog written in C++ to Python.
#include <TaskDialogPython.h>
Public Types
using BaseType = Py::PythonExtension< TaskDialogPy >
Public Member Functions
TaskDialogPy (TaskDialog *)
~TaskDialogPy () override
Py::Object repr () override
Py::Object getattr (const char *) override
int setattr (const char *, const Py::Object &) override
Py::Object getDialogContent (const Py::Tuple &)
Py::Object getStandardButtons (const Py::Tuple &)
tells the framework which buttons are wished for the dialog
Py::Object setEscapeButtonEnabled (const Py::Tuple &)
Defines whether a task dialog can be rejected by pressing Esc.
Py::Object isEscapeButtonEnabled (const Py::Tuple &)
Py::Object setAutoCloseOnTransactionChange (const Py::Tuple &)
Py::Object isAutoCloseOnTransactionChange (const Py::Tuple &)
Py::Object setAutoCloseOnDeletedDocument (const Py::Tuple &)
Py::Object isAutoCloseOnDeletedDocument (const Py::Tuple &)
Py::Object getDocumentName (const Py::Tuple &)
Py::Object setDocumentName (const Py::Tuple &)
Py::Object isAllowedAlterDocument (const Py::Tuple &)
Py::Object isAllowedAlterView (const Py::Tuple &)
Py::Object isAllowedAlterSelection (const Py::Tuple &)
Py::Object needsFullSpace (const Py::Tuple &)
Py::Object accept (const Py::Tuple &)
is called by the framework if the dialog is accepted (Ok)
Py::Object reject (const Py::Tuple &)
is called by the framework if the dialog is rejected (Cancel)
Static Public Member Functions
static void init_type ()
Detailed Description
The TaskDialogPy class This class exposes a TaskDialog written in C++ to Python.
Definition at line 115 of file TaskDialogPython.h.
Member Typedef Documentation
BaseType
using Gui::TaskView::TaskDialogPy::BaseType = Py::PythonExtension<TaskDialogPy>
Definition at line 118 of file TaskDialogPython.h.
Constructor & Destructor Documentation
TaskDialogPy()
TaskDialogPy::TaskDialogPy (TaskDialog * dlg) explicit
Definition at line 363 of file TaskDialogPython.cpp.
~TaskDialogPy()
TaskDialogPy::~TaskDialogPy () override default
Member Function Documentation
accept()
Py::Object TaskDialogPy::accept (const Py::Tuple & args)
is called by the framework if the dialog is accepted (Ok)
Definition at line 525 of file TaskDialogPython.cpp.
References toolbit-attributes::args.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), init_type(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
getattr()
Py::Object TaskDialogPy::getattr (const char * attr) override
Definition at line 378 of file TaskDialogPython.cpp.
getDialogContent()
Py::Object TaskDialogPy::getDialogContent (const Py::Tuple & args)
Definition at line 398 of file TaskDialogPython.cpp.
References toolbit-attributes::args, Gui::PythonWrapper::fromQWidget(), and Gui::PythonWrapper::loadWidgetsModule().
Referenced by init_type().
getDocumentName()
Py::Object TaskDialogPy::getDocumentName (const Py::Tuple & args)
Definition at line 465 of file TaskDialogPython.cpp.
References toolbit-attributes::args, and src.Mod.Test.testmakeWireString::String.
Referenced by init_type().
getStandardButtons()
Py::Object TaskDialogPy::getStandardButtons (const Py::Tuple & args)
tells the framework which buttons are wished for the dialog
Definition at line 415 of file TaskDialogPython.cpp.
References toolbit-attributes::args.
Referenced by init_type().
init_type()
void TaskDialogPy::init_type () static
Definition at line 317 of file TaskDialogPython.cpp.
References accept(), getDialogContent(), getDocumentName(), getStandardButtons(), isAllowedAlterDocument(), isAllowedAlterSelection(), isAllowedAlterView(), isAutoCloseOnDeletedDocument(), isAutoCloseOnTransactionChange(), isEscapeButtonEnabled(), needsFullSpace(), reject(), setAutoCloseOnDeletedDocument(), setAutoCloseOnTransactionChange(), setDocumentName(), and setEscapeButtonEnabled().
Referenced by Gui::Application::Application().
isAllowedAlterDocument()
Py::Object TaskDialogPy::isAllowedAlterDocument (const Py::Tuple & args)
Indicates whether this task dialog allows other commands to modify the document while it is open.
Definition at line 481 of file TaskDialogPython.cpp.
References toolbit-attributes::args.
Referenced by init_type().
isAllowedAlterSelection()
Py::Object TaskDialogPy::isAllowedAlterSelection (const Py::Tuple & args)
Indicates whether this task dialog allows other commands to modify the selection while it is open.
Definition at line 495 of file TaskDialogPython.cpp.
References toolbit-attributes::args.
Referenced by init_type().
isAllowedAlterView()
Py::Object TaskDialogPy::isAllowedAlterView (const Py::Tuple & args)
Indicates whether this task dialog allows other commands to modify the 3d view while it is open.
Definition at line 488 of file TaskDialogPython.cpp.
References toolbit-attributes::args.
Referenced by init_type().
isAutoCloseOnDeletedDocument()
Py::Object TaskDialogPy::isAutoCloseOnDeletedDocument (const Py::Tuple & args)
Definition at line 458 of file TaskDialogPython.cpp.
References toolbit-attributes::args.
Referenced by init_type().
isAutoCloseOnTransactionChange()
Py::Object TaskDialogPy::isAutoCloseOnTransactionChange (const Py::Tuple & args)
Definition at line 444 of file TaskDialogPython.cpp.
References toolbit-attributes::args.
Referenced by init_type().
isEscapeButtonEnabled()
Py::Object TaskDialogPy::isEscapeButtonEnabled (const Py::Tuple & args)
Definition at line 430 of file TaskDialogPython.cpp.
References toolbit-attributes::args.
Referenced by init_type().
needsFullSpace()
Py::Object TaskDialogPy::needsFullSpace (const Py::Tuple & args)
Definition at line 502 of file TaskDialogPython.cpp.
References toolbit-attributes::args.
Referenced by init_type().
reject()
Py::Object TaskDialogPy::reject (const Py::Tuple & args)
is called by the framework if the dialog is rejected (Cancel)
Definition at line 534 of file TaskDialogPython.cpp.
References toolbit-attributes::args.
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), init_type(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
repr()
Py::Object TaskDialogPy::repr () override
Definition at line 370 of file TaskDialogPython.cpp.
References toolbit-attributes::s, and src.Mod.Test.testmakeWireString::String.
setattr()
int TaskDialogPy::setattr (const char * attr, const Py::Object & value) override
Definition at line 388 of file TaskDialogPython.cpp.
setAutoCloseOnDeletedDocument()
Py::Object TaskDialogPy::setAutoCloseOnDeletedDocument (const Py::Tuple & args)
Definition at line 451 of file TaskDialogPython.cpp.
References toolbit-attributes::args.
Referenced by init_type().
setAutoCloseOnTransactionChange()
Py::Object TaskDialogPy::setAutoCloseOnTransactionChange (const Py::Tuple & args)
Defines whether a task dialog must be closed if the document changed the active transaction.
Definition at line 437 of file TaskDialogPython.cpp.
References toolbit-attributes::args.
Referenced by init_type().
setDocumentName()
Py::Object TaskDialogPy::setDocumentName (const Py::Tuple & args)
Definition at line 472 of file TaskDialogPython.cpp.
References toolbit-attributes::args.
Referenced by init_type().
setEscapeButtonEnabled()
Py::Object TaskDialogPy::setEscapeButtonEnabled (const Py::Tuple & args)
Defines whether a task dialog can be rejected by pressing Esc.
Definition at line 423 of file TaskDialogPython.cpp.
References toolbit-attributes::args.
Referenced by init_type().
The documentation for this class was generated from the following files:
TaskDialogPython.h
TaskDialogPython.cpp