FreeCAD: ifc2x3.ifcstructuralloadplanarforce Class Reference
ifc2x3.ifcstructuralloadplanarforce Class Reference
Public Member Functions
def __init__ (self, inherited0__name, planarforcex, planarforcey, planarforcez)
def planarforcex ()
def planarforcey ()
def planarforcez ()
Public Member Functions inherited from ifc2x3.ifcstructuralloadstatic
def __init__ (self, inherited0__name)
Public Member Functions inherited from ifc2x3.ifcstructuralload
def name ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
planarforcex
planarforcey
planarforcez
Public Attributes inherited from ifc2x3.ifcstructuralload
name
Detailed Description
Entity ifcstructuralloadplanarforce definition.
:param planarforcex
:type planarforcex:ifcplanarforcemeasure
:param planarforcey
:type planarforcey:ifcplanarforcemeasure
:param planarforcez
:type planarforcez:ifcplanarforcemeasure
Definition at line 28557 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcstructuralloadplanarforce.__init__ (self, inherited0__name, planarforcex, planarforcey, planarforcez)
Definition at line 28569 of file ifc2x3.py.
Member Function Documentation
planarforcex()
def ifc2x3.ifcstructuralloadplanarforce.planarforcex ()
Definition at line 28576 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadplanarforce._planarforcex, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadplanarforce.planarforcex.
planarforcey()
def ifc2x3.ifcstructuralloadplanarforce.planarforcey ()
Definition at line 28590 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadplanarforce._planarforcey, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadplanarforce.planarforcey.
planarforcez()
def ifc2x3.ifcstructuralloadplanarforce.planarforcez ()
Definition at line 28604 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadplanarforce._planarforcez, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadplanarforce.planarforcez.
Member Data Documentation
planarforcex
ifc2x3.ifcstructuralloadplanarforce.planarforcex
Definition at line 28571 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadplanarforce.planarforcex().
planarforcey
ifc2x3.ifcstructuralloadplanarforce.planarforcey
Definition at line 28572 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadplanarforce.planarforcey().
planarforcez
ifc2x3.ifcstructuralloadplanarforce.planarforcez
Definition at line 28573 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadplanarforce.planarforcez().
The documentation for this class was generated from the following file:
ifc2x3.py