FreeCAD: Gui::TaskOrientation Class Reference
Gui::TaskOrientation Class Reference
#include <TaskOrientation.h>
Public Member Functions
TaskOrientation (App::GeoFeature *obj, QWidget *parent=nullptr)
~TaskOrientation () override
void open ()
void accept ()
void reject ()
Detailed Description
Definition at line 54 of file TaskOrientation.h.
Constructor & Destructor Documentation
TaskOrientation()
TaskOrientation::TaskOrientation (App::GeoFeature * obj, QWidget * parent = nullptr) explicit
Definition at line 42 of file TaskOrientation.cpp.
References draftgeoutils.intersections::connect(), and Gui::QuantitySpinBox::valueChanged().
~TaskOrientation()
TaskOrientation::~TaskOrientation () override default
Member Function Documentation
accept()
void TaskOrientation::accept ()
Definition at line 74 of file TaskOrientation.cpp.
References toolbit-attributes::doc, App::WeakPtrT< T >::expired(), and App::DocumentObject::getDocument().
Referenced by Gui::TaskOrientationDialog::accept(), femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
open()
void TaskOrientation::open ()
Definition at line 65 of file TaskOrientation.cpp.
References toolbit-attributes::doc, App::WeakPtrT< T >::expired(), App::DocumentObject::getDocument(), App::PropertyPlacement::getValue(), App::GeoFeature::Placement, and Arch::QT_TRANSLATE_NOOP.
Referenced by Gui::TaskOrientationDialog::open().
reject()
void TaskOrientation::reject ()
Definition at line 83 of file TaskOrientation.cpp.
References toolbit-attributes::doc, App::WeakPtrT< T >::expired(), App::DocumentObject::getDocument(), and App::DocumentObject::purgeTouched().
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), Gui::TaskOrientationDialog::reject(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
TaskOrientation.h
TaskOrientation.cpp