FreeCAD: Reen::BSplineBasis Class Reference
Reen::BSplineBasis Class Reference
#include <ApproxSurface.h>
Public Member Functions
BSplineBasis (int iSize)
BSplineBasis (TColStd_Array1OfReal &vKnots, int iOrder=1)
BSplineBasis (TColStd_Array1OfReal &vKnots, TColStd_Array1OfInteger &vMults, int iSize, int iOrder=1)
virtual int FindSpan (double fParam)
virtual void AllBasisFunctions (double fParam, TColStd_Array1OfReal &vFuncVals)
ValueT LocalSupport (int iIndex, double fParam) override
double BasisFunction (int iIndex, double fParam) override
void DerivativesOfBasisFunction (int iIndex, int iMaxDer, double fParam, TColStd_Array1OfReal &Derivat) override
double DerivativeOfBasisFunction (int iIndex, int k, double fParam) override
virtual double GetIntegralOfProductOfBSplines (int i, int j, int r, int s)
~BSplineBasis () override
Public Member Functions inherited from Reen::SplineBasisfunction
SplineBasisfunction (int iSize)
SplineBasisfunction (TColStd_Array1OfReal &vKnots, int iOrder=1)
SplineBasisfunction (TColStd_Array1OfReal &vKnots, TColStd_Array1OfInteger &vMults, int iSize, int iOrder=1)
virtual ~SplineBasisfunction ()
virtual void SetKnots (TColStd_Array1OfReal &vKnots, int iOrder=1)
virtual void SetKnots (TColStd_Array1OfReal &vKnots, TColStd_Array1OfInteger &vMults, int iOrder=1)
Protected Member Functions
virtual void GenerateRootsAndWeights (TColStd_Array1OfReal &vAbscissas, TColStd_Array1OfReal &vWeights)
virtual void FindIntegrationArea (int iIdx1, int iIdx2, int &iBegin, int &iEnd)
int CalcSize (int r, int s)
Additional Inherited Members
Public Types inherited from Reen::SplineBasisfunction
enum ValueT { Zero = 0, Full, Other }
Protected Attributes inherited from Reen::SplineBasisfunction
TColStd_Array1OfReal _vKnotVector
int _iOrder
Detailed Description
Definition at line 148 of file ApproxSurface.h.
Constructor & Destructor Documentation
BSplineBasis() [1/3]
BSplineBasis::BSplineBasis (int iSize) explicit
Constructor
Parameters
iSize Length of the knot vector
Definition at line 124 of file ApproxSurface.cpp.
BSplineBasis() [2/3]
BSplineBasis::BSplineBasis (TColStd_Array1OfReal & vKnots, int iOrder = 1) explicit
Constructor
Parameters
vKnots Knot vector
iOrder Order (degree + 1) of the basic polynomial
Definition at line 135 of file ApproxSurface.cpp.
BSplineBasis() [3/3]
BSplineBasis::BSplineBasis (TColStd_Array1OfReal & vKnots, TColStd_Array1OfInteger & vMults, int iSize, int iOrder = 1)
Constructor
Parameters
vKnots Knot vector of shape (value)
vMults Knot vector of shape (multiplicity)
iSize Length of the knot vector The arrays vKnots and vMults have to be of the same size and the sum of the values in vMults has to be identical to iSize.
iOrder Order (degree + 1) of the basic polynomial
Definition at line 128 of file ApproxSurface.cpp.
~BSplineBasis()
BSplineBasis::~BSplineBasis () override default
Destructor
Member Function Documentation
AllBasisFunctions()
void BSplineBasis::AllBasisFunctions (double fParam, TColStd_Array1OfReal & vFuncVals) virtual
Calculates the function values of the basic functions that do not vanish at fParam. It must be ensured that the list for d (= degree of the B-spline) elements (0, ..., d-1) is sufficient (from: Piegl/Tiller 96 The NURBS-Book)
Parameters
fParam Parameter
vFuncVals List of function values Index, Parameter value
Definition at line 165 of file ApproxSurface.cpp.
References Reen::SplineBasisfunction::_iOrder, Reen::SplineBasisfunction::_vKnotVector, and FindSpan().
BasisFunction()
double BSplineBasis::BasisFunction (int iIndex, double fParam) override virtual
Calculates the function value Nik(t) at the point fParam (from: Piegl/Tiller 96 The NURBS-Book)
Parameters
iIndex Index
fParam Parameter value
Returns
Function value Nik(t)
Implements Reen::SplineBasisfunction.
Definition at line 208 of file ApproxSurface.cpp.
References Reen::SplineBasisfunction::_iOrder, Reen::SplineBasisfunction::_vKnotVector, test::m, and buildPsets::p.
Referenced by DerivativeOfBasisFunction(), Reen::BSplineParameterCorrection::SolveWithoutSmoothing(), and Reen::BSplineParameterCorrection::SolveWithSmoothing().
CalcSize()
int BSplineBasis::CalcSize (int r, int s) protected
Calculates the number of roots/weights of the Legendre-Polynomials to be used as a function of the degree
Definition at line 610 of file ApproxSurface.cpp.
References Reen::SplineBasisfunction::_iOrder, and toolbit-attributes::s.
Referenced by GetIntegralOfProductOfBSplines().
DerivativeOfBasisFunction()
double BSplineBasis::DerivativeOfBasisFunction (int iIndex, int k, double fParam) override virtual
Calculates the kth derivative at the point fParam
Implements Reen::SplineBasisfunction.
Definition at line 362 of file ApproxSurface.cpp.
References Reen::SplineBasisfunction::_iOrder, Reen::SplineBasisfunction::_vKnotVector, BasisFunction(), and buildPsets::p.
Referenced by GetIntegralOfProductOfBSplines().
DerivativesOfBasisFunction()
void BSplineBasis::DerivativesOfBasisFunction (int iIndex, int iMaxDer, double fParam, TColStd_Array1OfReal & Derivat) override virtual
Calculates the function values of the first iMaxDer derivatives at the point fParam (from: Piegl/Tiller 96 The NURBS-Book)
Parameters
iIndex Index
iMaxDer max. derivative
fParam Parameter value
Derivat The list must be sufficiently long for iMaxDer+1 elements.
Returns
List of function values
Implements Reen::SplineBasisfunction.
Definition at line 261 of file ApproxSurface.cpp.
References Reen::SplineBasisfunction::_iOrder, Reen::SplineBasisfunction::_vKnotVector, SplineSurface::i, and buildPsets::p.
FindIntegrationArea()
void BSplineBasis::FindIntegrationArea (int iIdx1, int iIdx2, int & iBegin, int & iEnd) protected virtual
Calculates the limits of integration (Indexes of the knots)
Definition at line 594 of file ApproxSurface.cpp.
References Reen::SplineBasisfunction::_iOrder, and Reen::SplineBasisfunction::_vKnotVector.
Referenced by GetIntegralOfProductOfBSplines().
FindSpan()
int BSplineBasis::FindSpan (double fParam) virtual
Specifies the knot index for the parameter value (from: Piegl/Tiller 96 The NURBS-Book)
Parameters
fParam Parameter value
Returns
Knot index
Definition at line 141 of file ApproxSurface.cpp.
References Reen::SplineBasisfunction::_iOrder, and Reen::SplineBasisfunction::_vKnotVector.
Referenced by AllBasisFunctions().
GenerateRootsAndWeights()
void BSplineBasis::GenerateRootsAndWeights (TColStd_Array1OfReal & vAbscissas, TColStd_Array1OfReal & vWeights) protected virtual
Calculates the roots of the Legendre-Polynomials and the corresponding weights
Definition at line 486 of file ApproxSurface.cpp.
Referenced by GetIntegralOfProductOfBSplines().
GetIntegralOfProductOfBSplines()
double BSplineBasis::GetIntegralOfProductOfBSplines (int i, int j, int r, int s) virtual
Calculates the integral of the product of two B-splines or their derivatives. The integration area extends over the entire domain of definition. The integral is calculated by means of the Gaussian quadrature formulas.
Definition at line 454 of file ApproxSurface.cpp.
References Reen::SplineBasisfunction::_vKnotVector, CalcSize(), DerivativeOfBasisFunction(), FindIntegrationArea(), GenerateRootsAndWeights(), and SplineSurface::i.
Referenced by Reen::BSplineParameterCorrection::CalcFirstSmoothMatrix(), Reen::BSplineParameterCorrection::CalcSecondSmoothMatrix(), and Reen::BSplineParameterCorrection::CalcThirdSmoothMatrix().
LocalSupport()
BSplineBasis::ValueT BSplineBasis::LocalSupport (int iIndex, double fParam) override virtual
Specifies whether the function value Nik(t) at the position fParam results in 0, 1 or a value in between. This serves to speed up the calculation under certain circumstances.
Parameters
iIndex Index
fParam Parameter value
Returns
ValueT
Implements Reen::SplineBasisfunction.
Definition at line 191 of file ApproxSurface.cpp.
References Reen::SplineBasisfunction::_iOrder, Reen::SplineBasisfunction::_vKnotVector, Reen::SplineBasisfunction::Full, test::m, Reen::SplineBasisfunction::Other, buildPsets::p, and Reen::SplineBasisfunction::Zero.
The documentation for this class was generated from the following files:
ApproxSurface.h
ApproxSurface.cpp