FreeCAD: Base::InventorOutput Class Reference
Base::InventorOutput Class Reference
#include <Builder3D.h>
Public Member Functions
InventorOutput (std::ostream &result, Indentation &indent)
std::ostream & stream ()
std::ostream & write ()
std::ostream & write (const char *)
std::ostream & write (const std::string &)
std::ostream & writeLine ()
std::ostream & writeLine (const char *)
std::ostream & writeLine (const std::string &)
void increaseIndent ()
void decreaseIndent ()
Detailed Description
Definition at line 241 of file Builder3D.h.
Constructor & Destructor Documentation
InventorOutput()
InventorOutput::InventorOutput (std::ostream & result, Indentation & indent) explicit
Definition at line 148 of file Builder3D.cpp.
Member Function Documentation
decreaseIndent()
void InventorOutput::decreaseIndent ()
Definition at line 199 of file Builder3D.cpp.
References indent.
Referenced by Base::InventorFieldWriter::write(), Base::BoundingBoxItem::write(), Base::FaceSetItem::write(), Base::IndexedLineSetItem::write(), Base::IndexedFaceSetItem::write(), and Base::NurbsSurfaceItem::write().
increaseIndent()
void InventorOutput::increaseIndent ()
Definition at line 194 of file Builder3D.cpp.
References indent.
Referenced by Base::InventorFieldWriter::write(), Base::BoundingBoxItem::write(), Base::FaceSetItem::write(), Base::IndexedLineSetItem::write(), Base::IndexedFaceSetItem::write(), and Base::NurbsSurfaceItem::write().
stream()
std::ostream & InventorOutput::stream ()
Definition at line 153 of file Builder3D.cpp.
References result.
Referenced by Base::InventorFieldWriter::write().
write() [1/3]
std::ostream & InventorOutput::write ()
Definition at line 158 of file Builder3D.cpp.
References indent, and result.
Referenced by Base::InventorFieldWriter::write(), Base::LabelItem::write(), Base::InfoItem::write(), Base::BaseColorItem::write(), Base::PointItem::write(), Base::LineItem::write(), Base::MultiLineItem::write(), Base::ArrowItem::write(), Base::BoundingBoxItem::write(), Base::MaterialBindingItem::write(), Base::DrawStyleItem::write(), Base::ShapeHintsItem::write(), Base::PolygonOffsetItem::write(), Base::FaceSetItem::write(), Base::IndexedLineSetItem::write(), Base::IndexedFaceSetItem::write(), Base::NormalBindingItem::write(), Base::CylinderItem::write(), Base::ConeItem::write(), Base::SphereItem::write(), Base::NurbsSurfaceItem::write(), Base::Text2Item::write(), and Base::TransformItem::write().
write() [2/3]
std::ostream & InventorOutput::write (const char * str)
Definition at line 164 of file Builder3D.cpp.
References indent, result, and Path.Post.scripts.refactored_centroid_post::str.
write() [3/3]
std::ostream & InventorOutput::write (const std::string & str)
Definition at line 170 of file Builder3D.cpp.
References indent, result, and Path.Post.scripts.refactored_centroid_post::str.
writeLine() [1/3]
std::ostream & InventorOutput::writeLine ()
Definition at line 176 of file Builder3D.cpp.
References indent, and result.
Referenced by Base::PointSetItem::write(), and Base::LineSetItem::write().
writeLine() [2/3]
std::ostream & InventorOutput::writeLine (const char * str)
Definition at line 182 of file Builder3D.cpp.
References indent, result, and Path.Post.scripts.refactored_centroid_post::str.
writeLine() [3/3]
std::ostream & InventorOutput::writeLine (const std::string & str)
Definition at line 188 of file Builder3D.cpp.
References indent, result, and Path.Post.scripts.refactored_centroid_post::str.
The documentation for this class was generated from the following files:
Builder3D.h
Builder3D.cpp