FreeCAD: Part::BRepBuilderAPI_RefineModel Class Reference
Part::BRepBuilderAPI_RefineModel Class Reference
#include <modelRefine.h>
Public Member Functions
BRepBuilderAPI_RefineModel (const TopoDS_Shape &)
void Build () override
const TopTools_ListOfShape & Modified (const TopoDS_Shape &S) override
Standard_Boolean IsDeleted (const TopoDS_Shape &S) override
Protected Attributes
TopTools_DataMapOfShapeListOfShape myModified
TopTools_ListOfShape myEmptyList
TopTools_ListOfShape myDeleted
Detailed Description
Definition at line 198 of file modelRefine.h.
Constructor & Destructor Documentation
BRepBuilderAPI_RefineModel()
Part::BRepBuilderAPI_RefineModel::BRepBuilderAPI_RefineModel (const TopoDS_Shape & shape)
Definition at line 1214 of file modelRefine.cpp.
Member Function Documentation
Build()
void Part::BRepBuilderAPI_RefineModel::Build () override
Definition at line 1223 of file modelRefine.cpp.
References ModelRefine::FaceUniter::getShell(), ModelRefine::FaceUniter::isModified(), ModelRefine::FaceUniter::process(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf::shell, and Part::solid.
IsDeleted()
Standard_Boolean Part::BRepBuilderAPI_RefineModel::IsDeleted (const TopoDS_Shape & S) override
Definition at line 1343 of file modelRefine.cpp.
Modified()
const TopTools_ListOfShape & Part::BRepBuilderAPI_RefineModel::Modified (const TopoDS_Shape & S) override
Definition at line 1335 of file modelRefine.cpp.
Member Data Documentation
myDeleted
TopTools_ListOfShape Part::BRepBuilderAPI_RefineModel::myDeleted protected
Definition at line 216 of file modelRefine.h.
myEmptyList
TopTools_ListOfShape Part::BRepBuilderAPI_RefineModel::myEmptyList protected
Definition at line 215 of file modelRefine.h.
myModified
TopTools_DataMapOfShapeListOfShape Part::BRepBuilderAPI_RefineModel::myModified protected
Definition at line 214 of file modelRefine.h.
The documentation for this class was generated from the following files:
modelRefine.h
modelRefine.cpp