FreeCAD: nurbs::NurbsBase1D Struct Reference
nurbs::NurbsBase1D Struct Reference
#include <MeshFlatteningNurbs.h>
Public Member Functions
NurbsBase1D ()=default
NurbsBase1D (Eigen::VectorXd u_knots, Eigen::VectorXd weights, int degree_u=3)
void computeFirstDerivatives ()
void computeSecondDerivatives ()
Eigen::VectorXd getInfluenceVector (double u)
spMat getInfluenceMatrix (Eigen::VectorXd u)
Eigen::VectorXd getDuVector (double u)
spMat getDuMatrix (Eigen::VectorXd u)
Eigen::VectorXd getUMesh (int num_u_points)
std::tuple< NurbsBase1D, Eigen::Matrix< double, Eigen::Dynamic, 3 > > interpolateUBS (Eigen::Matrix< double, Eigen::Dynamic, 3 > poles, int degree, int num_u_poles, int num_u_points)
Static Public Member Functions
static Eigen::VectorXd getKnotSequence (double u_min, double u_max, int deg, int num_poles)
static Eigen::VectorXd getWeightList (Eigen::VectorXd knots, int u_deg)
Public Attributes
int degree_u
Eigen::VectorXd u_knots
Eigen::VectorXd weights
std::vector< std::function< double(double)> > u_functions
std::vector< std::function< double(double)> > Du_functions
std::vector< std::function< double(double)> > DDu_functions
Detailed Description
Definition at line 103 of file MeshFlatteningNurbs.h.
Constructor & Destructor Documentation
NurbsBase1D() [1/2]
nurbs::NurbsBase1D::NurbsBase1D () default
NurbsBase1D() [2/2]
nurbs::NurbsBase1D::NurbsBase1D (Eigen::VectorXd u_knots, Eigen::VectorXd weights, int degree_u = 3)
Definition at line 407 of file MeshFlatteningNurbs.cpp.
References weights.
Member Function Documentation
computeFirstDerivatives()
void nurbs::NurbsBase1D::computeFirstDerivatives ()
Definition at line 445 of file MeshFlatteningNurbs.cpp.
Referenced by BOOST_PYTHON_MODULE(), and PYBIND11_MODULE().
computeSecondDerivatives()
void nurbs::NurbsBase1D::computeSecondDerivatives ()
Definition at line 451 of file MeshFlatteningNurbs.cpp.
References Du_functions, buildPsets::u, and u_functions.
getDuMatrix()
spMat nurbs::NurbsBase1D::getDuMatrix (Eigen::VectorXd u)
Definition at line 492 of file MeshFlatteningNurbs.cpp.
Referenced by BOOST_PYTHON_MODULE(), and PYBIND11_MODULE().
getDuVector()
Eigen::VectorXd nurbs::NurbsBase1D::getDuVector (double u)
Definition at line 458 of file MeshFlatteningNurbs.cpp.
References SplineSurface::i, and weights.
Referenced by BOOST_PYTHON_MODULE(), and PYBIND11_MODULE().
getInfluenceMatrix()
spMat nurbs::NurbsBase1D::getInfluenceMatrix (Eigen::VectorXd u)
Definition at line 435 of file MeshFlatteningNurbs.cpp.
Referenced by BOOST_PYTHON_MODULE(), and PYBIND11_MODULE().
getInfluenceVector()
Eigen::VectorXd nurbs::NurbsBase1D::getInfluenceVector (double u)
Definition at line 416 of file MeshFlatteningNurbs.cpp.
References nurbs::add_triplets(), and buildPsets::u.
Referenced by BOOST_PYTHON_MODULE(), and PYBIND11_MODULE().
getKnotSequence()
Eigen::VectorXd nurbs::NurbsBase1D::getKnotSequence (double u_min, double u_max, int deg, int num_poles) static
Definition at line 63 of file MeshFlatteningNurbs.cpp.
References SplineSurface::i, and InitGui::t.
Referenced by BOOST_PYTHON_MODULE(), and PYBIND11_MODULE().
getUMesh()
Eigen::VectorXd nurbs::NurbsBase1D::getUMesh (int num_u_points)
Definition at line 525 of file MeshFlatteningNurbs.cpp.
Referenced by BOOST_PYTHON_MODULE(), and PYBIND11_MODULE().
getWeightList()
Eigen::VectorXd nurbs::NurbsBase1D::getWeightList (Eigen::VectorXd knots, int u_deg) static
Definition at line 76 of file MeshFlatteningNurbs.cpp.
Referenced by BOOST_PYTHON_MODULE(), and PYBIND11_MODULE().
interpolateUBS()
std::tuple< NurbsBase1D, Eigen::Matrix< double, Eigen::Dynamic, 3 > > nurbs::NurbsBase1D::interpolateUBS (Eigen::Matrix< double, Eigen::Dynamic, 3 > poles, int degree, int num_u_poles, int num_u_points)
Definition at line 502 of file MeshFlatteningNurbs.cpp.
Member Data Documentation
DDu_functions
std::vector<std::function<double(double)> > nurbs::NurbsBase1D::DDu_functions
Definition at line 112 of file MeshFlatteningNurbs.h.
degree_u
int nurbs::NurbsBase1D::degree_u
Definition at line 107 of file MeshFlatteningNurbs.h.
Referenced by BOOST_PYTHON_MODULE(), and PYBIND11_MODULE().
Du_functions
std::vector<std::function<double(double)> > nurbs::NurbsBase1D::Du_functions
Definition at line 111 of file MeshFlatteningNurbs.h.
Referenced by computeSecondDerivatives().
u_functions
std::vector<std::function<double(double)> > nurbs::NurbsBase1D::u_functions
Definition at line 110 of file MeshFlatteningNurbs.h.
Referenced by computeSecondDerivatives().
u_knots
Eigen::VectorXd nurbs::NurbsBase1D::u_knots
Definition at line 108 of file MeshFlatteningNurbs.h.
Referenced by BOOST_PYTHON_MODULE(), and PYBIND11_MODULE().
weights
Eigen::VectorXd nurbs::NurbsBase1D::weights
Definition at line 109 of file MeshFlatteningNurbs.h.
Referenced by BOOST_PYTHON_MODULE(), nurbs::divide(), getDuVector(), NurbsBase1D(), and PYBIND11_MODULE().
The documentation for this struct was generated from the following files:
MeshFlatteningNurbs.h
MeshFlatteningNurbs.cpp