FreeCAD: DrawSketchHandlerDimension Class Reference
DrawSketchHandlerDimension Class Reference
Public Types
enum AvailableConstraint {
AvailableConstraint::FIRST, AvailableConstraint::SECOND, AvailableConstraint::THIRD, AvailableConstraint::FOURTH,
AvailableConstraint::FIFTH, AvailableConstraint::RESET
}
enum SpecialConstraint { SpecialConstraint::LineOr2PointsDistance, SpecialConstraint::Block, SpecialConstraint::None }
Public Member Functions
DrawSketchHandlerDimension (std::vector< std::string > SubNames)
~DrawSketchHandlerDimension () override
void activated () override
void deactivated () override
void registerPressedKey (bool pressed, int key) override
void mouseMove (Base::Vector2d onSketchPos) override
bool pressButton (Base::Vector2d onSketchPos) override
bool releaseButton (Base::Vector2d onSketchPos) override
void quit () override
Public Member Functions inherited from SketcherGui::DrawSketchHandler
DrawSketchHandler ()
virtual ~DrawSketchHandler ()
void activate (ViewProviderSketch *)
void deactivate () override
virtual void pressRightButton (Base::Vector2d pos)
virtual bool onSelectionChanged (const Gui::SelectionChanges &)
void quit () override
int getHighestVertexIndex ()
int getHighestCurveIndex ()
int seekAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
int seekAndRenderAutoConstraint (std::vector< AutoConstraint > &suggestedConstraints, const Base::Vector2d &Pos, const Base::Vector2d &Dir, AutoConstraint::TargetType type=AutoConstraint::VERTEX)
void createAutoConstraints (const std::vector< AutoConstraint > &autoConstrs, int geoId, Sketcher::PointPos pointPos=Sketcher::PointPos::none, bool createowncommand=true)
void setPositionText (const Base::Vector2d &Pos, const SbString &text)
void setPositionText (const Base::Vector2d &Pos)
void resetPositionText ()
void renderSuggestConstraintsCursor (std::vector< AutoConstraint > &suggestedConstraints)
void toolWidgetChanged (QWidget *newwidget)
Slot to receive signaling that a widget intended for the tool has changed and is available ant the provided pointer.
std::unique_ptr< QWidget > createToolWidget () const
Factory function returning a tool widget of the type necessary for the specific tool. This is a NVI interface and specific handlers must overload the corresponding virtual function.
bool isToolWidgetVisible () const
Returns whether this tool expects/supports a visible tool widget. Emphasis is in visibility, so to allow one to adapt the interface accordingly. This is an NVI interface and specific handlers must overload the corresponding virtual function.
QPixmap getToolWidgetHeaderIcon () const
Returns a pixmap icon intended for a visible tool widget. This is an NVI interface and specific handlers must overload the corresponding virtual function.
QString getToolWidgetHeaderText () const
Returns a header text intended for a visible tool widget. This is an NVI interface and specific handlers must overload the corresponding virtual function.
Public Member Functions inherited from Gui::ToolHandler
ToolHandler ()=default
virtual ~ToolHandler ()=default
bool activate ()
void updateCursor ()
Protected Member Functions
void clearRefVectors ()
void handleInitialSelection ()
void finalizeCommand ()
std::vector< SelIdPair > & getSelectionVector (Base::Type selGeoType)
bool notSelectedYet (const SelIdPair &elem)
bool selectionEmpty ()
bool makeAppropriateConstraint (Base::Vector2d onSketchPos)
void makeCts_1Point (bool &selAllowed, Base::Vector2d onSketchPos)
void makeCts_2Point (bool &selAllowed, Base::Vector2d onSketchPos)
void makeCts_1Point1Line (bool &selAllowed, Base::Vector2d onSketchPos)
void makeCts_3Point (bool &selAllowed, size_t s_pts)
void makeCts_1Point1Spline1MoreEdge (bool &)
void makeCts_4MorePoint (bool &selAllowed, size_t s_pts)
void makeCts_2Point1Line (bool &selAllowed, Base::Vector2d onSketchPos, size_t s_pts)
void makeCts_3MorePoint1Line (bool &selAllowed, Base::Vector2d onSketchPos, size_t s_pts)
void makeCts_1Point1Circle (bool &selAllowed, Base::Vector2d onSketchPos)
void makeCts_1MorePoint1Ellipse (bool &selAllowed)
void makeCts_1Line (bool &selAllowed, Base::Vector2d onSketchPos)
void makeCts_2Line (bool &selAllowed, Base::Vector2d onSketchPos)
void makeCts_3MoreLine (bool &selAllowed, size_t s_lns)
void makeCts_1Line1Circle (bool &selAllowed, Base::Vector2d onSketchPos)
void makeCts_1Line2Circle (bool &selAllowed)
void makeCts_1Line1Ellipse (bool &selAllowed)
void makeCts_1Circle (bool &selAllowed, Base::Vector2d onSketchPos)
void makeCts_2Circle (bool &selAllowed, Base::Vector2d onSketchPos)
void makeCts_3MoreCircle (bool &selAllowed, size_t s_cir)
void makeCts_1Circle1Ellipse (bool &selAllowed)
void makeCts_1Ellipse (bool &selAllowed)
void makeCts_2MoreEllipse (bool &selAllowed, size_t s_ell)
void createDistanceConstrain (int GeoId1, Sketcher::PointPos PosId1, int GeoId2, Sketcher::PointPos PosId2, Base::Vector2d onSketchPos)
void createDistanceXYConstrain (Sketcher::ConstraintType type, int GeoId1, Sketcher::PointPos PosId1, int GeoId2, Sketcher::PointPos PosId2, Base::Vector2d onSketchPos)
void createRadiusDiameterConstrain (int GeoId, Base::Vector2d onSketchPos, bool firstCstr)
bool createCoincidenceConstrain (int GeoId1, Sketcher::PointPos PosId1, int GeoId2, Sketcher::PointPos PosId2)
void createEqualityConstrain (int GeoId1, int GeoId2)
void createAngleConstrain (int GeoId1, int GeoId2, Base::Vector2d onSketchPos)
void createArcLengthConstrain (int GeoId, Base::Vector2d onSketchPos)
void createArcAngleConstrain (int GeoId, Base::Vector2d onSketchPos)
void createVerticalConstrain (int GeoId1, Sketcher::PointPos PosId1, int GeoId2, Sketcher::PointPos PosId2)
void createHorizontalConstrain (int GeoId1, Sketcher::PointPos PosId1, int GeoId2, Sketcher::PointPos PosId2)
void createBlockConstrain (int GeoId)
bool isHorizontalVerticalBlock (int GeoId)
void createSymmetryConstrain (int GeoId1, Sketcher::PointPos PosId1, int GeoId2, Sketcher::PointPos PosId2, int GeoId3, Sketcher::PointPos PosId3)
void updateDistanceType (Base::Vector2d onSketchPos)
bool isRadiusDoF (int geoId)
void finishDimensionCreation (int GeoId1, int GeoId2, Base::Vector2d onSketchPos)
void addConstraintIndex ()
bool hasBeenAborted ()
void restartCommand (const char *cstrName)
void resetTool ()
Protected Member Functions inherited from SketcherGui::DrawSketchHandler
virtual std::string getToolName () const
virtual std::unique_ptr< QWidget > createWidget () const
virtual bool isWidgetVisible () const
virtual QPixmap getToolIcon () const
virtual QString getToolWidgetText () const
void drawEdit (const std::vector< Base::Vector2d > &EditCurve) const
void drawEdit (const std::list< std::vector< Base::Vector2d >> &list) const
void drawEdit (const std::vector< Part::Geometry * > &geometries) const
void drawEditMarkers (const std::vector< Base::Vector2d > &EditMarkers, unsigned int augmentationlevel=0) const
void clearEdit () const
void clearEditMarkers () const
void setAxisPickStyle (bool on)
void moveCursorToSketchPoint (Base::Vector2d point)
void ensureFocus ()
void preselectAtPoint (Base::Vector2d point)
void drawPositionAtCursor (const Base::Vector2d &position)
void drawDirectionAtCursor (const Base::Vector2d &position, const Base::Vector2d &origin)
void drawWidthHeightAtCursor (const Base::Vector2d &position, const double val1, const double val2)
void drawDoubleAtCursor (const Base::Vector2d &position, const double radius, Base::Unit unit=Base::Unit::Length)
int getPreselectPoint () const
int getPreselectCurve () const
int getPreselectCross () const
Sketcher::SketchObject * getSketchObject ()
void setAngleSnapping (bool enable, Base::Vector2d referencePoint=Base::Vector2d(0., 0.))
void moveConstraint (int constNum, const Base::Vector2d &toPos)
void signalToolChanged () const
std::vector< QPixmap > suggestedConstraintsPixmaps (std::vector< AutoConstraint > &suggestedConstraints)
Protected Member Functions inherited from Gui::ToolHandler
virtual QString getCrosshairCursorSVGName () const
void setCursor (const QPixmap &pixmap, int x, int y, bool autoScale=true)
void unsetCursor ()
void applyCursor ()
restitutes the DSH cached cursor (without any tail due to autoconstraints, ...)
void addCursorTail (std::vector< QPixmap > &pixmaps)
unsigned long getCrosshairColor ()
returns the color to be used for the crosshair (configurable as a parameter)
qreal devicePixelRatio ()
functions to set the cursor to a given svgName (to be migrated to NVI style)
View3DInventorViewer * getViewer ()
virtual QWidget * getCursorWidget ()
virtual void setWidgetCursor (QCursor cursor)
Protected Attributes
SpecialConstraint specialConstraint
AvailableConstraint availableConstraint
Base::Vector2d previousOnSketchPos
std::vector< SelIdPair > selPoints
std::vector< SelIdPair > selLine
std::vector< SelIdPair > selCircleArc
std::vector< SelIdPair > selEllipseAndCo
std::vector< SelIdPair > selSplineAndCo
std::vector< std::string > initialSelection
std::vector< int > cstrIndexes
Sketcher::SketchObject * Obj
Protected Attributes inherited from SketcherGui::DrawSketchHandler
ViewProviderSketch * sketchgui
QWidget * toolwidget
Protected Attributes inherited from Gui::ToolHandler
QCursor oldCursor
QCursor actCursor
QPixmap actCursorPixmap
Detailed Description
Definition at line 1377 of file CommandConstraints.cpp.
Member Enumeration Documentation
AvailableConstraint
enum DrawSketchHandlerDimension::AvailableConstraint strong
Enumerator
FIRST
SECOND
THIRD
FOURTH
FIFTH
RESET
Definition at line 1397 of file CommandConstraints.cpp.
SpecialConstraint
enum DrawSketchHandlerDimension::SpecialConstraint strong
Enumerator
LineOr2PointsDistance
Block
None
Definition at line 1406 of file CommandConstraints.cpp.
Constructor & Destructor Documentation
DrawSketchHandlerDimension()
DrawSketchHandlerDimension::DrawSketchHandlerDimension (std::vector< std::string > SubNames) inline explicit
Definition at line 1380 of file CommandConstraints.cpp.
~DrawSketchHandlerDimension()
DrawSketchHandlerDimension::~DrawSketchHandlerDimension () inline override
Definition at line 1393 of file CommandConstraints.cpp.
Member Function Documentation
activated()
void DrawSketchHandlerDimension::activated () inline override virtual
Reimplemented from Gui::ToolHandler.
Definition at line 1412 of file CommandConstraints.cpp.
References Gui::BitmapFactory(), Gui::Command::openCommand(), Gui::BitmapFactoryInst::pixmapFromSvg(), and Arch::QT_TRANSLATE_NOOP.
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::set_status_filter().
addConstraintIndex()
void DrawSketchHandlerDimension::addConstraintIndex () inline protected
Definition at line 2729 of file CommandConstraints.cpp.
References Sketcher::SketchObject::Constraints, and Sketcher::PropertyConstraintList::getValues().
clearRefVectors()
void DrawSketchHandlerDimension::clearRefVectors () inline protected
Definition at line 1643 of file CommandConstraints.cpp.
createAngleConstrain()
void DrawSketchHandlerDimension::createAngleConstrain (int GeoId1, int GeoId2, Base::Vector2d onSketchPos) inline protected
Definition at line 2439 of file CommandConstraints.cpp.
References SketcherGui::calculateAngle(), Gui::cmdAppObjectArgs(), Sketcher::none, Arch::QT_TRANSLATE_NOOP, and Sketcher::start.
createArcAngleConstrain()
void DrawSketchHandlerDimension::createArcAngleConstrain (int GeoId, Base::Vector2d onSketchPos) inline protected
Definition at line 2476 of file CommandConstraints.cpp.
References Gui::cmdAppObjectArgs(), Sketcher::GeoUndef, Sketcher::SketchObject::getGeometry(), and Sketcher::isArcOfCircle().
createArcLengthConstrain()
void DrawSketchHandlerDimension::createArcLengthConstrain (int GeoId, Base::Vector2d onSketchPos) inline protected
Definition at line 2461 of file CommandConstraints.cpp.
References Gui::cmdAppObjectArgs(), Sketcher::GeoUndef, Sketcher::SketchObject::getGeometry(), and Sketcher::isArcOfCircle().
createBlockConstrain()
void DrawSketchHandlerDimension::createBlockConstrain (int GeoId) inline protected
Definition at line 2548 of file CommandConstraints.cpp.
References Gui::cmdAppObjectArgs(), and SketcherGui::tryAutoRecompute().
createCoincidenceConstrain()
bool DrawSketchHandlerDimension::createCoincidenceConstrain (int GeoId1, Sketcher::PointPos PosId1, int GeoId2, Sketcher::PointPos PosId2) inline protected
Definition at line 2394 of file CommandConstraints.cpp.
References SketcherGui::areBothPointsOrSegmentsFixed(), Sketcher::SketchObject::arePointsCoincident(), and Gui::cmdAppObjectArgs().
createDistanceConstrain()
void DrawSketchHandlerDimension::createDistanceConstrain (int GeoId1, Sketcher::PointPos PosId1, int GeoId2, Sketcher::PointPos PosId2, Base::Vector2d onSketchPos) inline protected
Definition at line 2199 of file CommandConstraints.cpp.
References KDL::abs(), Gui::cmdAppObjectArgs(), Sketcher::SketchObject::getGeometry(), Sketcher::SketchObject::getPoint(), Part::GeomCircle::getRadius(), Part::GeomArcOfCircle::getRadius(), Sketcher::isArcOfCircle(), TechDraw::isCircle, Sketcher::isLineSegment(), Base::Vector3< float_type >::Length(), FreeCADInit::Length, KDL::max(), KDL::min(), Sketcher::none, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
createDistanceXYConstrain()
void DrawSketchHandlerDimension::createDistanceXYConstrain (Sketcher::ConstraintType type, int GeoId1, Sketcher::PointPos PosId1, int GeoId2, Sketcher::PointPos PosId2, Base::Vector2d onSketchPos) inline protected
Definition at line 2321 of file CommandConstraints.cpp.
References Gui::cmdAppObjectArgs(), Sketcher::DistanceY, Sketcher::SketchObject::getPoint(), Path.Post.scripts.grbl_post::type, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
createEqualityConstrain()
void DrawSketchHandlerDimension::createEqualityConstrain (int GeoId1, int GeoId2) inline protected
Definition at line 2412 of file CommandConstraints.cpp.
References SketcherGui::areBothPointsOrSegmentsFixed(), Gui::cmdAppObjectArgs(), Sketcher::SketchObject::getGeometry(), Sketcher::isArcOfCircle(), Sketcher::isArcOfEllipse(), Sketcher::isArcOfHyperbola(), Sketcher::isArcOfParabola(), SketcherGui::isBsplinePole(), TechDraw::isCircle, TechDraw::isEllipse, Sketcher::isLineSegment(), and Gui::TranslatedUserWarning().
createHorizontalConstrain()
void DrawSketchHandlerDimension::createHorizontalConstrain (int GeoId1, Sketcher::PointPos PosId1, int GeoId2, Sketcher::PointPos PosId2) inline protected
Definition at line 2519 of file CommandConstraints.cpp.
References SketcherGui::areBothPointsOrSegmentsFixed(), Gui::cmdAppObjectArgs(), Sketcher::SketchObject::getGeometry(), Base::BaseClass::is(), FreeCADInit::Length, SketcherGui::tryAutoRecompute(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
createRadiusDiameterConstrain()
void DrawSketchHandlerDimension::createRadiusDiameterConstrain (int GeoId, Base::Vector2d onSketchPos, bool firstCstr) inline protected
Definition at line 2350 of file CommandConstraints.cpp.
References Gui::cmdAppObjectArgs(), Sketcher::GeoUndef, App::GetApplication(), ParameterGrp::GetBool(), Sketcher::SketchObject::getGeometry(), App::Application::GetParameterGroupByPath(), Sketcher::isArcOfCircle(), SketcherGui::isBsplinePole(), and TechDraw::isCircle.
createSymmetryConstrain()
void DrawSketchHandlerDimension::createSymmetryConstrain (int GeoId1, Sketcher::PointPos PosId1, int GeoId2, Sketcher::PointPos PosId2, int GeoId3, Sketcher::PointPos PosId3) inline protected
Definition at line 2568 of file CommandConstraints.cpp.
References SketcherGui::areAllPointsOrSegmentsFixed(), SketcherGui::areBothPointsOrSegmentsFixed(), Gui::cmdAppObjectArgs(), Sketcher::SketchObject::getGeometry(), SketcherGui::isEdge(), Sketcher::isLineSegment(), SketcherGui::isVertex(), Gui::TranslatedUserWarning(), and SketcherGui::tryAutoRecompute().
createVerticalConstrain()
void DrawSketchHandlerDimension::createVerticalConstrain (int GeoId1, Sketcher::PointPos PosId1, int GeoId2, Sketcher::PointPos PosId2) inline protected
Definition at line 2491 of file CommandConstraints.cpp.
References SketcherGui::areBothPointsOrSegmentsFixed(), Gui::cmdAppObjectArgs(), Sketcher::SketchObject::getGeometry(), Base::BaseClass::is(), FreeCADInit::Length, SketcherGui::tryAutoRecompute(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
deactivated()
void DrawSketchHandlerDimension::deactivated () inline override virtual
Reimplemented from Gui::ToolHandler.
Definition at line 1446 of file CommandConstraints.cpp.
References Gui::Command::abortCommand().
finalizeCommand()
void DrawSketchHandlerDimension::finalizeCommand () inline protected
Definition at line 1688 of file CommandConstraints.cpp.
References Gui::Command::commitCommand(), Sketcher::SketchObject::Constraints, SketcherGui::EditDatumDialog::exec(), App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), Sketcher::PropertyConstraintList::getValues(), SketcherGui::EditDatumDialog::isSuccess(), and bimcommands.BimViews::show().
finishDimensionCreation()
void DrawSketchHandlerDimension::finishDimensionCreation (int GeoId1, int GeoId2, Base::Vector2d onSketchPos) inline protected
Definition at line 2716 of file CommandConstraints.cpp.
References SketcherGui::areBothPointsOrSegmentsFixed(), Gui::cmdAppObjectArgs(), constraintCreationMode, Sketcher::SketchObject::Constraints, Sketcher::GeoUndef, Sketcher::PropertyConstraintList::getValues(), SketcherGui::isPointOrSegmentFixed(), and SketcherGui::Reference.
getSelectionVector()
std::vector<SelIdPair>& DrawSketchHandlerDimension::getSelectionVector (Base::Type selGeoType) inline protected
Definition at line 1725 of file CommandConstraints.cpp.
References Base::Persistence::getClassTypeId().
handleInitialSelection()
void DrawSketchHandlerDimension::handleInitialSelection () inline protected
Definition at line 1652 of file CommandConstraints.cpp.
References Base::Type::badType(), SketcherGui::SelIdPair::GeoId, Base::Persistence::getClassTypeId(), Sketcher::SketchObject::getGeometry(), SketcherGui::getIdsFromName(), Base::Persistence::getTypeId(), SketcherGui::isEdge(), SketcherGui::isVertex(), and SketcherGui::SelIdPair::PosId.
hasBeenAborted()
bool DrawSketchHandlerDimension::hasBeenAborted () inline protected
Definition at line 2734 of file CommandConstraints.cpp.
References Sketcher::SketchObject::Constraints, and Sketcher::PropertyConstraintList::getSize().
isHorizontalVerticalBlock()
bool DrawSketchHandlerDimension::isHorizontalVerticalBlock (int GeoId) inline protected
Definition at line 2555 of file CommandConstraints.cpp.
References Sketcher::Block, Sketcher::SketchObject::Constraints, Sketcher::PropertyConstraintList::getValues(), Sketcher::Horizontal, and Sketcher::Vertical.
isRadiusDoF()
bool DrawSketchHandlerDimension::isRadiusDoF (int geoId) inline protected
Definition at line 2694 of file CommandConstraints.cpp.
References Gui::Command::abortCommand(), Sketcher::SketchObject::getGeometry(), Sketcher::SketchObject::getSolvedSketch(), Sketcher::Sketch::getSolverExtension(), Sketcher::isArcOfCircle(), and Sketcher::SketchObject::solve().
makeAppropriateConstraint()
bool DrawSketchHandlerDimension::makeAppropriateConstraint (Base::Vector2d onSketchPos) inline protected
Definition at line 1773 of file CommandConstraints.cpp.
References Path.Dressup.Utils::selection().
makeCts_1Circle()
void DrawSketchHandlerDimension::makeCts_1Circle (bool & selAllowed, Base::Vector2d onSketchPos) inline protected
Definition at line 2072 of file CommandConstraints.cpp.
References Sketcher::SketchObject::getGeometry(), Sketcher::isArcOfCircle(), and Arch::QT_TRANSLATE_NOOP.
makeCts_1Circle1Ellipse()
void DrawSketchHandlerDimension::makeCts_1Circle1Ellipse (bool & selAllowed) inline protected
Definition at line 2162 of file CommandConstraints.cpp.
makeCts_1Ellipse()
void DrawSketchHandlerDimension::makeCts_1Ellipse (bool & selAllowed) inline protected
Definition at line 2172 of file CommandConstraints.cpp.
makeCts_1Line()
void DrawSketchHandlerDimension::makeCts_1Line (bool & selAllowed, Base::Vector2d onSketchPos) inline protected
Definition at line 1970 of file CommandConstraints.cpp.
References Sketcher::end, Sketcher::GeoUndef, Sketcher::HAxis, Sketcher::none, Arch::QT_TRANSLATE_NOOP, Sketcher::start, and Sketcher::VAxis.
makeCts_1Line1Circle()
void DrawSketchHandlerDimension::makeCts_1Line1Circle (bool & selAllowed, Base::Vector2d onSketchPos) inline protected
Definition at line 2040 of file CommandConstraints.cpp.
References Arch::QT_TRANSLATE_NOOP.
makeCts_1Line1Ellipse()
void DrawSketchHandlerDimension::makeCts_1Line1Ellipse (bool & selAllowed) inline protected
Definition at line 2062 of file CommandConstraints.cpp.
makeCts_1Line2Circle()
void DrawSketchHandlerDimension::makeCts_1Line2Circle (bool & selAllowed) inline protected
Definition at line 2051 of file CommandConstraints.cpp.
References Sketcher::mid, and Arch::QT_TRANSLATE_NOOP.
makeCts_1MorePoint1Ellipse()
void DrawSketchHandlerDimension::makeCts_1MorePoint1Ellipse (bool & selAllowed) inline protected
Definition at line 1960 of file CommandConstraints.cpp.
makeCts_1Point()
void DrawSketchHandlerDimension::makeCts_1Point (bool & selAllowed, Base::Vector2d onSketchPos) inline protected
Definition at line 1811 of file CommandConstraints.cpp.
References Sketcher::Block, Sketcher::DistanceX, Sketcher::DistanceY, Arch::QT_TRANSLATE_NOOP, Sketcher::RtPnt, and Sketcher::start.
makeCts_1Point1Circle()
void DrawSketchHandlerDimension::makeCts_1Point1Circle (bool & selAllowed, Base::Vector2d onSketchPos) inline protected
Definition at line 1949 of file CommandConstraints.cpp.
References Arch::QT_TRANSLATE_NOOP.
makeCts_1Point1Line()
void DrawSketchHandlerDimension::makeCts_1Point1Line (bool & selAllowed, Base::Vector2d onSketchPos) inline protected
Definition at line 1851 of file CommandConstraints.cpp.
References Sketcher::end, Arch::QT_TRANSLATE_NOOP, and Sketcher::start.
makeCts_1Point1Spline1MoreEdge()
void DrawSketchHandlerDimension::makeCts_1Point1Spline1MoreEdge (bool &) inline protected
Definition at line 1889 of file CommandConstraints.cpp.
makeCts_2Circle()
void DrawSketchHandlerDimension::makeCts_2Circle (bool & selAllowed, Base::Vector2d onSketchPos) inline protected
Definition at line 2124 of file CommandConstraints.cpp.
References Sketcher::mid, and Arch::QT_TRANSLATE_NOOP.
makeCts_2Line()
void DrawSketchHandlerDimension::makeCts_2Line (bool & selAllowed, Base::Vector2d onSketchPos) inline protected
Definition at line 2006 of file CommandConstraints.cpp.
References Sketcher::HAxis, Arch::QT_TRANSLATE_NOOP, and Sketcher::VAxis.
makeCts_2MoreEllipse()
void DrawSketchHandlerDimension::makeCts_2MoreEllipse (bool & selAllowed, size_t s_ell) inline protected
Definition at line 2178 of file CommandConstraints.cpp.
References Sketcher::SketchObject::getGeometry(), Base::Persistence::getTypeId(), SplineSurface::i, and Arch::QT_TRANSLATE_NOOP.
makeCts_2Point()
void DrawSketchHandlerDimension::makeCts_2Point (bool & selAllowed, Base::Vector2d onSketchPos) inline protected
Definition at line 1832 of file CommandConstraints.cpp.
References Arch::QT_TRANSLATE_NOOP.
makeCts_2Point1Line()
void DrawSketchHandlerDimension::makeCts_2Point1Line (bool & selAllowed, Base::Vector2d onSketchPos, size_t s_pts) inline protected
Definition at line 1919 of file CommandConstraints.cpp.
References SplineSurface::i, and Arch::QT_TRANSLATE_NOOP.
makeCts_3MoreCircle()
void DrawSketchHandlerDimension::makeCts_3MoreCircle (bool & selAllowed, size_t s_cir) inline protected
Definition at line 2149 of file CommandConstraints.cpp.
References SplineSurface::i, and Arch::QT_TRANSLATE_NOOP.
makeCts_3MoreLine()
void DrawSketchHandlerDimension::makeCts_3MoreLine (bool & selAllowed, size_t s_lns) inline protected
Definition at line 2027 of file CommandConstraints.cpp.
References SplineSurface::i, and Arch::QT_TRANSLATE_NOOP.
makeCts_3MorePoint1Line()
void DrawSketchHandlerDimension::makeCts_3MorePoint1Line (bool & selAllowed, Base::Vector2d onSketchPos, size_t s_pts) inline protected
Definition at line 1936 of file CommandConstraints.cpp.
References SplineSurface::i, and Arch::QT_TRANSLATE_NOOP.
makeCts_3Point()
void DrawSketchHandlerDimension::makeCts_3Point (bool & selAllowed, size_t s_pts) inline protected
Definition at line 1866 of file CommandConstraints.cpp.
References SplineSurface::i, and Arch::QT_TRANSLATE_NOOP.
makeCts_4MorePoint()
void DrawSketchHandlerDimension::makeCts_4MorePoint (bool & selAllowed, size_t s_pts) inline protected
Definition at line 1900 of file CommandConstraints.cpp.
References SplineSurface::i, and Arch::QT_TRANSLATE_NOOP.
mouseMove()
void DrawSketchHandlerDimension::mouseMove (Base::Vector2d onSketchPos) inline override virtual
Implements SketcherGui::DrawSketchHandler.
Definition at line 1478 of file CommandConstraints.cpp.
References Sketcher::Block, Base::Vector2d::x, and Base::Vector2d::y.
notSelectedYet()
bool DrawSketchHandlerDimension::notSelectedYet (const SelIdPair & elem) inline protected
Definition at line 1751 of file CommandConstraints.cpp.
References SketcherGui::SelIdPair::GeoId, SketcherGui::SelIdPair::PosId, SurfaceTests.TestBlendCurve::vec, and MovieTool::x.
pressButton()
bool DrawSketchHandlerDimension::pressButton (Base::Vector2d onSketchPos) inline override virtual
Implements SketcherGui::DrawSketchHandler.
Definition at line 1515 of file CommandConstraints.cpp.
quit()
void DrawSketchHandlerDimension::quit () inline override virtual
Reimplemented from Gui::ToolHandler.
Definition at line 1614 of file CommandConstraints.cpp.
registerPressedKey()
void DrawSketchHandlerDimension::registerPressedKey (bool pressed, int key) inline override virtual
Reimplemented from SketcherGui::DrawSketchHandler.
Definition at line 1453 of file CommandConstraints.cpp.
releaseButton()
bool DrawSketchHandlerDimension::releaseButton (Base::Vector2d onSketchPos) inline override virtual
Implements SketcherGui::DrawSketchHandler.
Definition at line 1521 of file CommandConstraints.cpp.
References Gui::SelectionSingleton::addSelection(), Base::Type::badType(), SketcherGui::SelIdPair::GeoId, Sketcher::GeoUndef, Base::Persistence::getClassTypeId(), Base::Persistence::getTypeId(), Sketcher::HAxis, Sketcher::none, SketcherGui::SelIdPair::PosId, Arch::QT_TRANSLATE_NOOP, Sketcher::RefExt, Gui::SelectionSingleton::rmvSelection(), Sketcher::RtPnt, Gui::Selection(), Sketcher::start, Sketcher::VAxis, Base::Vector2d::x, and Base::Vector2d::y.
resetTool()
void DrawSketchHandlerDimension::resetTool () inline protected
Definition at line 2757 of file CommandConstraints.cpp.
References Gui::Command::abortCommand(), Gui::SelectionSingleton::clearSelection(), SCL.SimpleDataTypes::f, Gui::None, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, and Gui::Selection().
restartCommand()
void DrawSketchHandlerDimension::restartCommand (const char * cstrName) inline protected
Definition at line 2747 of file CommandConstraints.cpp.
References Gui::Command::abortCommand(), Gui::None, Gui::Command::openCommand(), and Sketcher::SketchObject::solve().
selectionEmpty()
bool DrawSketchHandlerDimension::selectionEmpty () inline protected
Definition at line 1768 of file CommandConstraints.cpp.
updateDistanceType()
void DrawSketchHandlerDimension::updateDistanceType (Base::Vector2d onSketchPos) inline protected
Definition at line 2625 of file CommandConstraints.cpp.
References Sketcher::SketchObject::Constraints, Sketcher::Distance, Sketcher::DistanceX, Sketcher::DistanceY, Sketcher::end, SketcherGui::SelIdPair::GeoId, Sketcher::SketchObject::getPoint(), Sketcher::PropertyConstraintList::getValues(), KDL::max(), KDL::min(), SketcherGui::SelIdPair::PosId, Arch::QT_TRANSLATE_NOOP, Sketcher::RtPnt, Sketcher::start, Path.Post.scripts.grbl_post::type, Base::Vector2d::x, Base::Vector3< float_type >::x, Base::Vector2d::y, and Base::Vector3< float_type >::y.
Member Data Documentation
availableConstraint
AvailableConstraint DrawSketchHandlerDimension::availableConstraint protected
Definition at line 1627 of file CommandConstraints.cpp.
cstrIndexes
std::vector<int> DrawSketchHandlerDimension::cstrIndexes protected
Definition at line 1639 of file CommandConstraints.cpp.
initialSelection
std::vector<std::string> DrawSketchHandlerDimension::initialSelection protected
Definition at line 1637 of file CommandConstraints.cpp.
Obj
Sketcher::SketchObject* DrawSketchHandlerDimension::Obj protected
Definition at line 1641 of file CommandConstraints.cpp.
Referenced by src.Mod.Test.Document.DocumentPropertyCases::testDescent(), and src.Mod.Test.Document.DocumentPropertyCases::testRemoveProperty().
previousOnSketchPos
Base::Vector2d DrawSketchHandlerDimension::previousOnSketchPos protected
Definition at line 1629 of file CommandConstraints.cpp.
selCircleArc
std::vector<SelIdPair> DrawSketchHandlerDimension::selCircleArc protected
Definition at line 1633 of file CommandConstraints.cpp.
selEllipseAndCo
std::vector<SelIdPair> DrawSketchHandlerDimension::selEllipseAndCo protected
Definition at line 1634 of file CommandConstraints.cpp.
selLine
std::vector<SelIdPair> DrawSketchHandlerDimension::selLine protected
Definition at line 1632 of file CommandConstraints.cpp.
selPoints
std::vector<SelIdPair> DrawSketchHandlerDimension::selPoints protected
Definition at line 1631 of file CommandConstraints.cpp.
selSplineAndCo
std::vector<SelIdPair> DrawSketchHandlerDimension::selSplineAndCo protected
Definition at line 1635 of file CommandConstraints.cpp.
specialConstraint
SpecialConstraint DrawSketchHandlerDimension::specialConstraint protected
Definition at line 1626 of file CommandConstraints.cpp.
The documentation for this class was generated from the following file:
CommandConstraints.cpp