FreeCAD: SketcherGui::SketchOrientationDialog Class Reference
SketcherGui::SketchOrientationDialog Class Reference
#include <SketchOrientationDialog.h>
Public Member Functions
SketchOrientationDialog ()
~SketchOrientationDialog () override
void accept () override
Public Attributes
Base::Placement Pos
int DirType
Protected Slots
void onPreview ()
Detailed Description
Definition at line 56 of file SketchOrientationDialog.h.
Constructor & Destructor Documentation
SketchOrientationDialog()
SketchOrientationDialog::SketchOrientationDialog ()
Definition at line 37 of file SketchOrientationDialog.cpp.
References draftgeoutils.intersections::connect(), DirType, and onPreview().
~SketchOrientationDialog()
SketchOrientationDialog::~SketchOrientationDialog () override
Definition at line 51 of file SketchOrientationDialog.cpp.
Member Function Documentation
accept()
void SketchOrientationDialog::accept () override
Definition at line 54 of file SketchOrientationDialog.cpp.
References DirType, and Pos.
onPreview
void SketchOrientationDialog::onPreview () protected slot
Definition at line 93 of file SketchOrientationDialog.cpp.
References Gui::BitmapFactory().
Referenced by SketchOrientationDialog().
Member Data Documentation
DirType
int SketcherGui::SketchOrientationDialog::DirType
Definition at line 65 of file SketchOrientationDialog.h.
Referenced by accept(), and SketchOrientationDialog().
Pos
Base::Placement SketcherGui::SketchOrientationDialog::Pos
Definition at line 64 of file SketchOrientationDialog.h.
Referenced by accept().
The documentation for this class was generated from the following files:
SketchOrientationDialog.h
SketchOrientationDialog.cpp