FreeCAD: TaskCheckGeometry.cpp File Reference
TaskCheckGeometry.cpp File Reference
#include "PreCompiled.h"
#include <QCheckBox>
#include <QCoreApplication>
#include <QHeaderView>
#include <QPushButton>
#include <QScrollBar>
#include <QTextEdit>
#include <QTextStream>
#include <QThread>
#include <QTreeView>
#include <Standard_Version.hxx>
#include <Bnd_Box.hxx>
#include <BOPAlgo_ArgumentAnalyzer.hxx>
#include <BOPAlgo_ListOfCheckResult.hxx>
#include <BRepBndLib.hxx>
#include <BRepBuilderAPI_Copy.hxx>
#include <BRepCheck_Analyzer.hxx>
#include <BRepCheck_ListIteratorOfListOfStatus.hxx>
#include <BRepCheck_Result.hxx>
#include <BRepTools_ShapeSet.hxx>
#include <ShapeAnalysis_FreeBounds.hxx>
#include <TopoDS.hxx>
#include <TopoDS_Compound.hxx>
#include <TopTools_IndexedMapOfShape.hxx>
#include <TopExp.hxx>
#include <TopExp_Explorer.hxx>
#include <Inventor/nodes/SoCube.h>
#include <Inventor/nodes/SoDrawStyle.h>
#include <Inventor/nodes/SoMaterial.h>
#include <Inventor/nodes/SoResetTransform.h>
#include <Inventor/nodes/SoSeparator.h>
#include <Inventor/nodes/SoSwitch.h>
#include <Inventor/nodes/SoTransform.h>
#include <Base/Interpreter.h>
#include <Gui/Application.h>
#include <Gui/BitmapFactory.h>
#include <Gui/Document.h>
#include <Gui/MainWindow.h>
#include <Gui/Selection.h>
#include <Gui/ViewProvider.h>
#include <Gui/WaitCursor.h>
#include <Mod/Part/App/PartFeature.h>
#include "TaskCheckGeometry.h"
#include "moc_TaskCheckGeometry.cpp"
Functions
QVector< QString > buildShapeEnumVector ()
QString shapeEnumToString (const int &index)
QVector< QString > buildCheckStatusStringVector ()
QString checkStatusToString (const int &index)
QVector< QString > buildBOPCheckResultVector ()
QString getBOPCheckString (const BOPAlgo_CheckStatus &status)
Function Documentation
buildBOPCheckResultVector()
QVector<QString> buildBOPCheckResultVector ()
Definition at line 156 of file TaskCheckGeometry.cpp.
Referenced by getBOPCheckString().
buildCheckStatusStringVector()
QVector<QString> buildCheckStatusStringVector ()
Definition at line 97 of file TaskCheckGeometry.cpp.
References femtools.tokrules::names.
Referenced by checkStatusToString().
buildShapeEnumVector()
QVector<QString> buildShapeEnumVector ()
Definition at line 74 of file TaskCheckGeometry.cpp.
References femtools.tokrules::names.
Referenced by shapeEnumToString().
checkStatusToString()
QString checkStatusToString (const int & index)
Definition at line 138 of file TaskCheckGeometry.cpp.
References buildCheckStatusStringVector(), and femtools.tokrules::names.
getBOPCheckString()
QString getBOPCheckString (const BOPAlgo_CheckStatus & status)
Definition at line 175 of file TaskCheckGeometry.cpp.
References buildBOPCheckResultVector().
shapeEnumToString()
QString shapeEnumToString (const int & index)
Definition at line 89 of file TaskCheckGeometry.cpp.
References buildShapeEnumVector(), and femtools.tokrules::names.
Referenced by Part::TopoShape::analyze(), and PartGui::TaskCheckGeometryResults::goCheck().