FreeCAD: App::TransactionObject Class Reference
App::TransactionObject Class Reference
#include <Transactions.h>
Classes
struct PropData
Public Member Functions
TransactionObject ()
Construction.
~TransactionObject () override
Destruction.
virtual void applyNew (Document &Doc, TransactionalObject *pcObj)
virtual void applyDel (Document &Doc, TransactionalObject *pcObj)
virtual void applyChn (Document &Doc, TransactionalObject *pcObj, bool Forward)
void setProperty (const Property *pcProp)
void addOrRemoveProperty (const Property *pcProp, bool add)
unsigned int getMemSize () const override
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
This method is used to restore properties from an XML document.
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Types
enum Status { New, Del, Chn }
Protected Attributes
enum App::TransactionObject::Status New
std::unordered_map< int64_t, PropData > _PropChangeMap
std::string _NameInDocument
Friends
class Transaction
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Represents an entry for an object in a Transaction
Definition at line 124 of file Transactions.h.
Member Enumeration Documentation
Status
enum App::TransactionObject::Status protected
Enumerator
New
Del
Chn
Definition at line 149 of file Transactions.h.
Constructor & Destructor Documentation
TransactionObject()
TransactionObject::TransactionObject () default
Construction.
A constructor. A more elaborate description of the constructor.
~TransactionObject()
TransactionObject::~TransactionObject () override
Destruction.
A destructor. A more elaborate description of the destructor.
Definition at line 290 of file Transactions.cpp.
References _PropChangeMap, and TestSpreadsheet::v.
Member Function Documentation
addOrRemoveProperty()
void TransactionObject::addOrRemoveProperty (const Property * pcProp, bool add)
Definition at line 392 of file Transactions.cpp.
References _PropChangeMap, App::Property::Copy(), App::Property::getContainer(), App::PropertyContainer::getDynamicPropertyData(), App::Property::getID(), App::Property::getStatus(), Base::Persistence::getTypeId(), and App::DynamicProperty::PropData::property.
Referenced by App::Transaction::addOrRemoveProperty().
applyChn()
void TransactionObject::applyChn (Document & Doc, TransactionalObject * pcObj, bool Forward) virtual
Definition at line 303 of file Transactions.cpp.
References _PropChangeMap, App::PropertyContainer::addDynamicProperty(), Chn, SCL.SimpleDataTypes::e, FC_ERR, App::PropertyContainer::getDynamicPropertyByName(), App::ExtensionContainer::getPropertyName(), New, App::PropertyContainer::removeDynamicProperty(), App::Property::setStatusValue(), and TestSpreadsheet::v.
applyDel()
void TransactionObject::applyDel (Document & Doc, TransactionalObject * pcObj) virtual
Reimplemented in App::TransactionDocumentObject, and Gui::TransactionViewProvider.
Definition at line 297 of file Transactions.cpp.
applyNew()
void TransactionObject::applyNew (Document & Doc, TransactionalObject * pcObj) virtual
Reimplemented in App::TransactionDocumentObject, and Gui::TransactionViewProvider.
Definition at line 300 of file Transactions.cpp.
getMemSize()
unsigned int TransactionObject::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
Definition at line 425 of file Transactions.cpp.
Restore()
void TransactionObject::Restore (Base::XMLReader & reader) override virtual
This method is used to restore properties from an XML document.
Implements Base::Persistence.
Definition at line 435 of file Transactions.cpp.
Save()
void TransactionObject::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 430 of file Transactions.cpp.
setProperty()
void TransactionObject::setProperty (const Property * pcProp)
Definition at line 379 of file Transactions.cpp.
References _PropChangeMap, App::Property::Copy(), App::Property::getContainer(), App::PropertyContainer::getDynamicPropertyData(), App::Property::getID(), App::Property::getStatus(), and Base::Persistence::getTypeId().
Referenced by App::Transaction::addObjectChange(), Path.Base.Gui.PropertyEditor._PropertyEditorBool::setModelData(), Path.Base.Gui.PropertyEditor._PropertyEditorString::setModelData(), Path.Base.Gui.PropertyEditor._PropertyEditorPercent::setModelData(), Path.Base.Gui.PropertyEditor._PropertyEditorInteger::setModelData(), Path.Base.Gui.PropertyEditor._PropertyEditorFloat::setModelData(), Path.Base.Gui.PropertyEditor._PropertyEditorFile::setModelData(), and Path.Base.Gui.PropertyEditor._PropertyEditorEnumeration::setModelData().
Friends And Related Function Documentation
Transaction
friend class Transaction friend
Definition at line 146 of file Transactions.h.
Member Data Documentation
_NameInDocument
std::string App::TransactionObject::_NameInDocument protected
Definition at line 163 of file Transactions.h.
Referenced by App::Transaction::addObjectNew(), and App::TransactionDocumentObject::applyNew().
_PropChangeMap
std::unordered_map<int64_t, PropData> App::TransactionObject::_PropChangeMap protected
Definition at line 161 of file Transactions.h.
Referenced by addOrRemoveProperty(), applyChn(), setProperty(), and ~TransactionObject().
New
enum App::TransactionObject::Status App::TransactionObject::New protected
Referenced by App::Transaction::addObjectDel(), App::Transaction::addObjectNew(), applyChn(), Gui::TransactionViewProvider::applyNew(), App::TransactionDocumentObject::applyNew(), and App::Transaction::~Transaction().
The documentation for this class was generated from the following files:
Transactions.h
Transactions.cpp