FreeCAD: NotificationsAction Class Reference
NotificationsAction Class Reference
Public Member Functions
NotificationsAction (QWidget *parent)
NotificationsAction (const NotificationsAction &)=delete
NotificationsAction (NotificationsAction &&)=delete
NotificationsAction & operator= (const NotificationsAction &)=delete
NotificationsAction & operator= (NotificationsAction &&)=delete
~NotificationsAction () override
void deleteNotifications ()
deletes only notifications (messages of type Notification)
void deleteAll ()
deletes all notifications, errors and warnings
int getUnreadCount () const
returns the amount of unread notifications, errors and warnings
int getCurrentlyNotifyingCount () const
returns the amount of notifications, errors and warnings currently being notified
int getShownCount () const
void clearUnreadFlag ()
marks all notifications, errors and warnings as read
void synchroniseWidget ()
pushes all Notification Items to the Widget, so that they can be shown
void shiftToCache ()
bool isEmpty () const
returns if there are no notifications, errors and warnings at all
auto count () const
returns the total amount of notifications, errors and warnings currently stored
auto getItem (int index) const
retrieves a pointer to a given notification from storage.
void deleteItem (int index)
deletes a given notification, errors or warnings by index
void deleteItem (NotificationItem *item)
deletes a given notification, errors or warnings by pointer
void deleteLastItem ()
deletes the last Notification Item
bool isSameNotification (const QString &notifiername, const QString &message, Base::LogStyle level) const
checks if last notification is the same
void resetLastNotificationStatus ()
auto push_front (std::unique_ptr< NotificationItem > item)
pushes a notification item to the front
QSize size ()
Protected Member Functions
QWidget * createWidget (QWidget *parent) override
creates the Notifications Widget
Detailed Description
Drop menu Action containing the notifications widget. It stores all the notification item information in the form of NotificationItems (QTreeWidgetItem). This information is used by the Widget and by the non-intrusive messages. It owns the notification resources and is responsible for the release of the memory resources, either directly for the intermediate fast cache or indirectly via QT for the case of the QTreeWidgetItems.
Definition at line 458 of file NotificationArea.cpp.
Constructor & Destructor Documentation
NotificationsAction() [1/3]
NotificationsAction::NotificationsAction (QWidget * parent) inline
Definition at line 461 of file NotificationArea.cpp.
NotificationsAction() [2/3]
NotificationsAction::NotificationsAction (const NotificationsAction &) delete
NotificationsAction() [3/3]
NotificationsAction::NotificationsAction (NotificationsAction &&) delete
~NotificationsAction()
NotificationsAction::~NotificationsAction () inline override
Definition at line 470 of file NotificationArea.cpp.
Member Function Documentation
clearUnreadFlag()
void NotificationsAction::clearUnreadFlag () inline
marks all notifications, errors and warnings as read
Definition at line 537 of file NotificationArea.cpp.
References SplineSurface::i, and NotificationItem::setRead().
count()
auto NotificationsAction::count () const inline
returns the total amount of notifications, errors and warnings currently stored
Definition at line 575 of file NotificationArea.cpp.
Referenced by deleteItem(), deleteLastItem(), isSameNotification(), Gui::NotificationArea::pushNotification(), and src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::set_status_filter().
createWidget()
QWidget* NotificationsAction::createWidget (QWidget * parent) inline override protected
creates the Notifications Widget
Definition at line 652 of file NotificationArea.cpp.
References draftgeoutils.intersections::connect(), deleteAll(), deleteNotifications(), NavigationIndicatorGui::menu, Init::parent, and RobotExample::pos.
deleteAll()
void NotificationsAction::deleteAll () inline
deletes all notifications, errors and warnings
Definition at line 502 of file NotificationArea.cpp.
Referenced by createWidget().
deleteItem() [1/2]
void NotificationsAction::deleteItem (int index) inline
deletes a given notification, errors or warnings by index
Definition at line 592 of file NotificationArea.cpp.
Referenced by deleteItem(), and deleteLastItem().
deleteItem() [2/2]
void NotificationsAction::deleteItem (NotificationItem * item) inline
deletes a given notification, errors or warnings by pointer
Definition at line 603 of file NotificationArea.cpp.
References count(), deleteItem(), getItem(), and SplineSurface::i.
deleteLastItem()
void NotificationsAction::deleteLastItem () inline
deletes the last Notification Item
Definition at line 614 of file NotificationArea.cpp.
References count(), and deleteItem().
Referenced by Gui::NotificationArea::pushNotification().
deleteNotifications()
void NotificationsAction::deleteNotifications () inline
deletes only notifications (messages of type Notification)
Definition at line 481 of file NotificationArea.cpp.
References SplineSurface::i, and Base::Notification.
Referenced by createWidget().
getCurrentlyNotifyingCount()
int NotificationsAction::getCurrentlyNotifyingCount () const inline
returns the amount of notifications, errors and warnings currently being notified
Definition at line 520 of file NotificationArea.cpp.
getItem()
auto NotificationsAction::getItem (int index) const inline
retrieves a pointer to a given notification from storage.
Definition at line 581 of file NotificationArea.cpp.
Referenced by deleteItem(), isSameNotification(), and resetLastNotificationStatus().
getShownCount()
int NotificationsAction::getShownCount () const inline
returns the amount of notifications, errors and warnings currently being shown as non-intrusive messages (on-screen)
Definition at line 529 of file NotificationArea.cpp.
getUnreadCount()
int NotificationsAction::getUnreadCount () const inline
returns the amount of unread notifications, errors and warnings
Definition at line 512 of file NotificationArea.cpp.
Referenced by Gui::NotificationArea::pushNotification().
isEmpty()
bool NotificationsAction::isEmpty () const inline
returns if there are no notifications, errors and warnings at all
Definition at line 569 of file NotificationArea.cpp.
isSameNotification()
bool NotificationsAction::isSameNotification (const QString & notifiername, const QString & message, Base::LogStyle level) const inline
checks if last notification is the same
Definition at line 620 of file NotificationArea.cpp.
References count(), getItem(), NotificationItem::isRepeated(), and level().
Referenced by Gui::NotificationArea::pushNotification().
operator=() [1/2]
NotificationsAction& NotificationsAction::operator= (const NotificationsAction &) delete
operator=() [2/2]
NotificationsAction& NotificationsAction::operator= (NotificationsAction &&) delete
push_front()
auto NotificationsAction::push_front (std::unique_ptr< NotificationItem > item) inline
pushes a notification item to the front
Definition at line 638 of file NotificationArea.cpp.
Referenced by Gui::NotificationArea::pushNotification().
resetLastNotificationStatus()
void NotificationsAction::resetLastNotificationStatus () inline
Definition at line 631 of file NotificationArea.cpp.
References NotificationItem::addRepetition(), and getItem().
Referenced by Gui::NotificationArea::pushNotification().
shiftToCache()
void NotificationsAction::shiftToCache () inline
pushes all Notification Items to the fast cache (this also prevents all unnecessary signaling from parents) and allows one to accelerate insertions and deletions
Definition at line 557 of file NotificationArea.cpp.
size()
QSize NotificationsAction::size () inline
Definition at line 645 of file NotificationArea.cpp.
Referenced by Path.Post.Utils.GCodeEditorDialog::done(), and Gui::NotificationArea::NotificationArea().
synchroniseWidget()
void NotificationsAction::synchroniseWidget () inline
pushes all Notification Items to the Widget, so that they can be shown
Definition at line 548 of file NotificationArea.cpp.
Referenced by Gui::NotificationArea::NotificationArea().
The documentation for this class was generated from the following file:
NotificationArea.cpp