FreeCAD: femsolver.equationbase.BaseProxy Class Reference
femsolver.equationbase.BaseProxy Class Reference
FEM
Public Member Functions
def __init__ (self, obj)
def execute (self, obj)
Static Public Attributes
BaseType
Detailed Description
Definition at line 37 of file equationbase.py.
Constructor & Destructor Documentation
__init__()
def femsolver.equationbase.BaseProxy.__init__ (self, obj)
Reimplemented in femsolver.elmer.equations.elasticity.Proxy, femsolver.elmer.equations.flux.Proxy, femsolver.elmer.equations.flow.Proxy, femsolver.elmer.equations.heat.Proxy, femsolver.elmer.equations.linear.Proxy, femsolver.elmer.equations.electricforce.Proxy, femsolver.elmer.equations.electrostatic.Proxy, femsolver.elmer.equations.deformation.Proxy, femsolver.elmer.equations.magnetodynamic.Proxy, femsolver.elmer.equations.magnetodynamic2D.Proxy, femsolver.elmer.equations.equation.Proxy, and femsolver.elmer.equations.nonlinear.Proxy.
Definition at line 41 of file equationbase.py.
Member Function Documentation
execute()
def femsolver.equationbase.BaseProxy.execute (self, obj)
Definition at line 45 of file equationbase.py.
Referenced by src.Mod.PartDesign.Scripts.Spring.MySpring.onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped.onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder.onChanged(), MeasureCOM.MeasureCOM.onChanged(), and FeaturePython.DistanceBolt.onChanged().
Member Data Documentation
BaseType
femsolver.equationbase.BaseProxy.BaseType static
Definition at line 39 of file equationbase.py.
The documentation for this class was generated from the following file:
equationbase.py