FreeCAD: MatGui::Array3DModel Class Reference
MatGui::Array3DModel Class Reference
#include <ArrayModel.h>
Public Member Functions
Array3DModel (const std::shared_ptr< Materials::MaterialProperty > &property=nullptr, const std::shared_ptr< Materials::Material3DArray > &value=nullptr, QObject *parent=nullptr)
~Array3DModel () override=default
int rowCount (const QModelIndex &parent=QModelIndex()) const override
bool newRow (const QModelIndex &index) const override
void deleteRow (const QModelIndex &index)
int columnCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override
Qt::ItemFlags flags (const QModelIndex &index) const override
bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex()) override
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex()) override
bool insertColumns (int column, int count, const QModelIndex &parent=QModelIndex()) override
bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex()) override
void updateData ()
Public Member Functions inherited from MatGui::AbstractArrayModel
AbstractArrayModel (QObject *parent=nullptr)
~AbstractArrayModel () override=default
Detailed Description
Definition at line 131 of file ArrayModel.h.
Constructor & Destructor Documentation
Array3DModel()
Array3DModel::Array3DModel (const std::shared_ptr< Materials::MaterialProperty > & property = nullptr, const std::shared_ptr< Materials::Material3DArray > & value = nullptr, QObject * parent = nullptr) explicit
Definition at line 339 of file ArrayModel.cpp.
~Array3DModel()
MatGui::Array3DModel::~Array3DModel () override default
Member Function Documentation
columnCount()
int Array3DModel::columnCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 361 of file ArrayModel.cpp.
References Init::parent.
Referenced by insertRows().
data()
QVariant Array3DModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 384 of file ArrayModel.cpp.
References Base::Console(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Error(), Materials::MaterialValue::getQuantityFormat(), src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::Quantity, and Base::Quantity::setFormat().
deleteRow()
void Array3DModel::deleteRow (const QModelIndex & index)
Definition at line 378 of file ArrayModel.cpp.
References removeRows().
flags()
Qt::ItemFlags Array3DModel::flags (const QModelIndex & index) const override
Definition at line 452 of file ArrayModel.cpp.
headerData()
QVariant Array3DModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const override
Definition at line 409 of file ArrayModel.cpp.
References App::ExpressionParser::column, Sketcher::Horizontal, rowCount(), and Sketcher::Vertical.
insertColumns()
bool Array3DModel::insertColumns (int column, int count, const QModelIndex & parent = QModelIndex()) override
Definition at line 491 of file ArrayModel.cpp.
References App::ExpressionParser::column, src.Mod.AddonManager.NetworkManager::count, and Init::parent.
insertRows()
bool Array3DModel::insertRows (int row, int count, const QModelIndex & parent = QModelIndex()) override
Definition at line 459 of file ArrayModel.cpp.
References columnCount(), src.Mod.AddonManager.NetworkManager::count, SplineSurface::i, and Init::parent.
Referenced by setData().
newRow()
bool Array3DModel::newRow (const QModelIndex & index) const override virtual
Implements MatGui::AbstractArrayModel.
Definition at line 368 of file ArrayModel.cpp.
removeColumns()
bool Array3DModel::removeColumns (int column, int count, const QModelIndex & parent = QModelIndex()) override
Definition at line 500 of file ArrayModel.cpp.
References App::ExpressionParser::column, src.Mod.AddonManager.NetworkManager::count, and Init::parent.
removeRows()
bool Array3DModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex()) override
Definition at line 478 of file ArrayModel.cpp.
References src.Mod.AddonManager.NetworkManager::count, SplineSurface::i, and Init::parent.
Referenced by deleteRow().
rowCount()
int Array3DModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 347 of file ArrayModel.cpp.
References Init::parent.
Referenced by headerData().
setData()
bool Array3DModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) override
Definition at line 428 of file ArrayModel.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), and insertRows().
updateData()
void Array3DModel::updateData ()
Definition at line 509 of file ArrayModel.cpp.
The documentation for this class was generated from the following files:
ArrayModel.h
ArrayModel.cpp