FreeCAD: Base::InventorFieldWriter Class Reference
Base::InventorFieldWriter Class Reference
Public Member Functions
template<typename T >
void write (const char *fieldName, const std::vector< T > &fieldData, InventorOutput &out) const
template<>
void write (const char *fieldName, const std::vector< int > &fieldData, InventorOutput &out) const
Detailed Description
Writes a field type to a stream.
Author
Werner Mayer
Definition at line 250 of file Builder3D.cpp.
Member Function Documentation
write() [1/2]
template<> void Base::InventorFieldWriter::write (const char * fieldName, const std::vector< int > & fieldData, InventorOutput & out) const
Definition at line 283 of file Builder3D.cpp.
References Base::InventorOutput::decreaseIndent(), Base::InventorOutput::increaseIndent(), Base::InventorOutput::stream(), and Base::InventorOutput::write().
write() [2/2]
template<typename T > void Base::InventorFieldWriter::write (const char * fieldName, const std::vector< T > & fieldData, InventorOutput & out) const
Definition at line 258 of file Builder3D.cpp.
References Base::InventorOutput::decreaseIndent(), Base::InventorOutput::increaseIndent(), Base::InventorOutput::stream(), feminout.exportNastranMesh::write(), and Base::InventorOutput::write().
Referenced by Base::MultiLineItem::write(), Base::Coordinate3Item::write(), Base::FaceSetItem::write(), Base::IndexedLineSetItem::write(), Base::IndexedFaceSetItem::write(), Base::NormalItem::write(), and Base::NurbsSurfaceItem::write().
The documentation for this class was generated from the following file:
Builder3D.cpp