FreeCAD: MeshCore::MeshTrimming Class Reference
MeshCore::MeshTrimming Class Reference
#include <Trim.h>
Public Types
enum TMode { INNER, OUTER }
Public Member Functions
MeshTrimming (MeshKernel &mesh, const Base::ViewProjMethod *proj, const Base::Polygon2d &poly)
void CheckFacets (const MeshFacetGrid &rclGrid, std::vector< FacetIndex > &raulFacets) const
void TrimFacets (const std::vector< FacetIndex > &raulFacets, std::vector< MeshGeomFacet > &aclNewFacets)
void SetInnerOrOuter (TMode tMode)
Detailed Description
Checks the facets in 2D and then trim them in 3D
Definition at line 57 of file Trim.h.
Member Enumeration Documentation
TMode
enum MeshCore::MeshTrimming::TMode
Enumerator
INNER
OUTER
Definition at line 80 of file Trim.h.
Constructor & Destructor Documentation
MeshTrimming()
MeshTrimming::MeshTrimming (MeshKernel & mesh, const Base::ViewProjMethod * proj, const Base::Polygon2d & poly)
Definition at line 38 of file Trim.cpp.
Member Function Documentation
CheckFacets()
void MeshTrimming::CheckFacets (const MeshFacetGrid & rclGrid, std::vector< FacetIndex > & raulFacets) const
Checks all facets for intersection with the polygon and writes all touched facets into the vector
Definition at line 58 of file Trim.cpp.
References Base::Polygon2d::CalcBoundBox(), MeshCore::MeshKernel::CountFacets(), MeshCore::MeshGridIterator::GetBoundBox(), MeshCore::MeshGridIterator::GetElements(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshFacetIterator::Init(), MeshCore::MeshGridIterator::Init(), Base::BoundBox2d::Intersect(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshGridIterator::More(), MeshCore::MeshFacetIterator::Next(), Base::SequencerLauncher::next(), MeshCore::MeshGridIterator::Next(), MeshCore::MeshFacetIterator::Position(), and Base::BoundBox3< Precision >::ProjectBox().
SetInnerOrOuter()
void MeshTrimming::SetInnerOrOuter (TMode tMode)
Setter: Trimm INNER or OUTER
Definition at line 46 of file Trim.cpp.
References INNER, and OUTER.
TrimFacets()
void MeshTrimming::TrimFacets (const std::vector< FacetIndex > & raulFacets, std::vector< MeshGeomFacet > & aclNewFacets)
The facets from raulFacets will be trimmed or deleted and aclNewFacets gives the new generated facets
Definition at line 772 of file Trim.cpp.
References Base::SequencerLauncher::next().
The documentation for this class was generated from the following files:
Trim.h
Trim.cpp