FreeCAD: TechDraw::GeometryMatcher Class Reference
TechDraw::GeometryMatcher Class Reference
#include <GeometryMatcher.h>
Public Member Functions
GeometryMatcher ()=default
bool compareGeometry (const Part::TopoShape &geom1, const Part::TopoShape &geom2)
double getPointTolerance () const
void setPointTolerance (double tol)
Detailed Description
Definition at line 39 of file GeometryMatcher.h.
Constructor & Destructor Documentation
GeometryMatcher()
TechDraw::GeometryMatcher::GeometryMatcher () default
Member Function Documentation
compareGeometry()
bool GeometryMatcher::compareGeometry (const Part::TopoShape & geom1, const Part::TopoShape & geom2)
Definition at line 59 of file GeometryMatcher.cpp.
References Part::TopoShape::getShape(), Part::TopoShape::isNull(), and TechDraw::Preferences::useExactMatchOnDims().
getPointTolerance()
double TechDraw::GeometryMatcher::getPointTolerance () const inline
Definition at line 46 of file GeometryMatcher.h.
setPointTolerance()
void TechDraw::GeometryMatcher::setPointTolerance (double tol) inline
Definition at line 50 of file GeometryMatcher.h.
The documentation for this class was generated from the following files:
GeometryMatcher.h
GeometryMatcher.cpp