FreeCAD: MeshCore::MeshEvalDegeneratedFacets Class Reference
MeshCore::MeshEvalDegeneratedFacets Class Reference
#include <Degeneration.h>
Public Member Functions
MeshEvalDegeneratedFacets (const MeshKernel &rclM, float fEps)
bool Evaluate () override
unsigned long CountEdgeTooSmall (float fMinEdgeLength) const
std::vector< FacetIndex > GetIndices () const
Public Member Functions inherited from MeshCore::MeshEvaluation
MeshEvaluation (const MeshKernel &rclB)
virtual ~MeshEvaluation ()=default
MeshEvaluation (const MeshEvaluation &)=delete
MeshEvaluation (MeshEvaluation &&)=delete
MeshEvaluation & operator= (const MeshEvaluation &)=delete
MeshEvaluation & operator= (MeshEvaluation &&)=delete
Additional Inherited Members
Protected Attributes inherited from MeshCore::MeshEvaluation
const MeshKernel & _rclMesh
Detailed Description
The MeshEvalDegeneratedFacets class searches for degenerated facets. A facet is degenerated either if its points are collinear, i.e. they lie on a line or two points are coincident. In the latter case these points are duplicated. If a facet refers to at least two equal point indices then the facet is also regarded is 'corrupt'.
See also
MeshEvalCorruptedFacets
MeshEvalDuplicatePoints
MeshFixDegeneratedFacets
Author
Werner Mayer
Definition at line 284 of file Degeneration.h.
Constructor & Destructor Documentation
MeshEvalDegeneratedFacets()
MeshCore::MeshEvalDegeneratedFacets::MeshEvalDegeneratedFacets (const MeshKernel & rclM, float fEps) inline
Construction.
Definition at line 290 of file Degeneration.h.
Member Function Documentation
CountEdgeTooSmall()
unsigned long MeshEvalDegeneratedFacets::CountEdgeTooSmall (float fMinEdgeLength) const
Returns the number of facets with an edge smaller than fMinEdgeLength.
Definition at line 486 of file Degeneration.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::MeshEvaluation::_rclMesh, Base::Distance(), MeshCore::MeshFacetIterator::EndReached(), and SplineSurface::i.
Evaluate()
bool MeshEvalDegeneratedFacets::Evaluate () override virtual
Searches degenerated facets.
Implements MeshCore::MeshEvaluation.
Definition at line 474 of file Degeneration.cpp.
References MeshCore::MeshEvaluation::_rclMesh, MeshCore::MeshFacetIterator::Init(), MeshCore::MeshGeomFacet::IsDegenerated(), MeshCore::MeshFacetIterator::More(), and MeshCore::MeshFacetIterator::Next().
GetIndices()
std::vector< FacetIndex > MeshEvalDegeneratedFacets::GetIndices () const
Returns the indices of all corrupt facets.
Definition at line 504 of file Degeneration.cpp.
References MeshCore::MeshEvaluation::_rclMesh, MeshCore::MeshFacetIterator::Init(), MeshCore::MeshGeomFacet::IsDegenerated(), MeshCore::MeshFacetIterator::More(), MeshCore::MeshFacetIterator::Next(), and MeshCore::MeshFacetIterator::Position().
The documentation for this class was generated from the following files:
Degeneration.h
Degeneration.cpp