FreeCAD: Link.cpp File Reference
Link.cpp File Reference
#include "PreCompiled.h"
#include <boost/property_map/property_map.hpp>
#include <boost/range.hpp>
#include <boost/algorithm/string/predicate.hpp>
#include <Base/Tools.h>
#include <Base/Uuid.h>
#include "Application.h"
#include "ElementNamingUtils.h"
#include "ComplexGeoDataPy.h"
#include "Document.h"
#include "DocumentObserver.h"
#include "GeoFeatureGroupExtension.h"
#include "Link.h"
#include "LinkBaseExtensionPy.h"
Namespaces
App
a class to assist with exporting sketches to dxf
Macros
#define CHECK_EXCLUDE_PROP(_name)
Typedefs
using CharRange = boost::iterator_range< const char * >
Functions
static bool isExcludedProperties (const char *name)
Variables
static const char _GroupPrefix [] = "Configuration ("
template class AppExport App::ExtensionPythonT< LinkBaseExtension >
Macro Definition Documentation
CHECK_EXCLUDE_PROP
#define CHECK_EXCLUDE_PROP (_name)
Value:
    if (strcmp(name, #_name) == 0)                                                                 \
        return true;
Typedef Documentation
CharRange
using CharRange = boost::iterator_range<const char*>
Definition at line 52 of file Link.cpp.
Function Documentation
isExcludedProperties()
static bool isExcludedProperties (const char * name) static
Definition at line 2543 of file Link.cpp.
References CHECK_EXCLUDE_PROP, and DrawingExample::Shape.
Referenced by App::LinkBaseExtension::extensionGetPropertyByName().
Variable Documentation
_GroupPrefix
const char _GroupPrefix[] = "Configuration (" static
Definition at line 340 of file Link.cpp.
Referenced by App::LinkBaseExtension::isCopyOnChangeProperty(), and App::LinkBaseExtension::setupCopyOnChange().