FreeCAD: Gui::Camera Class Reference
Gui::Camera Class Reference
#include <Camera.h>
Public Types
enum Orientation {
Top, Bottom, Front, Rear,
Right, Left, Isometric, Dimetric,
Trimetric
}
Static Public Member Functions
static SbRotation top ()
static SbRotation bottom ()
static SbRotation front ()
static SbRotation rear ()
static SbRotation right ()
static SbRotation left ()
static SbRotation isometric ()
static SbRotation dimetric ()
static SbRotation trimetric ()
static SbRotation rotation (Orientation view)
static Base::Rotation convert (Orientation view)
static Base::Rotation convert (const SbRotation &)
static SbRotation convert (const Base::Rotation &)
Detailed Description
Definition at line 52 of file Camera.h.
Member Enumeration Documentation
Orientation
enum Gui::Camera::Orientation
Enumerator
Top
Bottom
Front
Rear
Right
Left
Isometric
Dimetric
Trimetric
Definition at line 74 of file Camera.h.
Member Function Documentation
bottom()
SbRotation Camera::bottom () static
Definition at line 101 of file Camera.cpp.
Referenced by Path.Dressup.Tags.Tag::filterIntersections(), and rotation().
convert() [1/3]
SbRotation Camera::convert (const Base::Rotation & rot) static
Definition at line 198 of file Camera.cpp.
Referenced by femsolver.elmer.writer.Writer::getDensity(), and femsolver.elmer.writer.Writer::getFromUi().
convert() [2/3]
Base::Rotation Camera::convert (const SbRotation & rot) static
Definition at line 193 of file Camera.cpp.
Referenced by femsolver.elmer.writer.Writer::getDensity(), and femsolver.elmer.writer.Writer::getFromUi().
convert() [3/3]
Base::Rotation Camera::convert (Camera::Orientation view) static
Definition at line 188 of file Camera.cpp.
References rotation().
Referenced by femsolver.elmer.writer.Writer::getDensity(), and femsolver.elmer.writer.Writer::getFromUi().
dimetric()
SbRotation Camera::dimetric () static
Definition at line 152 of file Camera.cpp.
Referenced by rotation().
front()
SbRotation Camera::front () static
Definition at line 106 of file Camera.cpp.
Referenced by rotation().
isometric()
SbRotation Camera::isometric () static
Definition at line 128 of file Camera.cpp.
Referenced by rotation().
left()
SbRotation Camera::left () static
Definition at line 123 of file Camera.cpp.
Referenced by rotation().
rear()
SbRotation Camera::rear () static
Definition at line 112 of file Camera.cpp.
Referenced by rotation().
right()
SbRotation Camera::right () static
Definition at line 118 of file Camera.cpp.
Referenced by rotation().
rotation()
SbRotation Camera::rotation (Camera::Orientation view) static
Definition at line 162 of file Camera.cpp.
References bottom(), Bottom, dimetric(), Dimetric, front(), Front, isometric(), Isometric, left(), Left, rear(), Rear, right(), Right, top(), Top, trimetric(), and Trimetric.
Referenced by convert(), Gui::AbstractSplitView::onMsg(), Gui::View3DInventor::onMsg(), Gui::View3DInventorPy::viewBottom(), Gui::View3DInventorPy::viewDefaultOrientation(), Gui::View3DInventorPy::viewDimetric(), Gui::View3DInventorPy::viewFront(), Gui::View3DInventorPy::viewIsometric(), Gui::View3DInventorPy::viewLeft(), Gui::View3DInventorPy::viewRear(), Gui::View3DInventorPy::viewRight(), Gui::View3DInventorPy::viewTop(), and Gui::View3DInventorPy::viewTrimetric().
top()
SbRotation Camera::top () static
Formulas to get quaternion for axonometric views:
from math import sqrt, degrees, asin, atan
p1=App.Rotation(App.Vector(1,0,0),90)
p2=App.Rotation(App.Vector(0,0,1),alpha)
p3=App.Rotation(p2.multVec(App.Vector(1,0,0)),beta)
p4=p3.multiply(p2).multiply(p1)
from pivy import coin
c=Gui.ActiveDocument.ActiveView.getCameraNode()
c.orientation.setValue(*p4.Q)
The angles alpha and beta depend on the type of axonometry Isometric:
alpha=45
beta=degrees(asin(-sqrt(1.0/3.0)))
Dimetric:
alpha=degrees(asin(sqrt(1.0/8.0)))
beta=degrees(-asin(1.0/3.0))
Trimetric:
alpha=30.0
beta=-35.0
Verification code that the axonomtries are correct:
from pivy import coin
c=Gui.ActiveDocument.ActiveView.getCameraNode()
vo=App.Vector(c.getViewVolume().getMatrix().multVecMatrix(coin.SbVec3f(0,0,0)).getValue())
vx=App.Vector(c.getViewVolume().getMatrix().multVecMatrix(coin.SbVec3f(10,0,0)).getValue())
vy=App.Vector(c.getViewVolume().getMatrix().multVecMatrix(coin.SbVec3f(0,10,0)).getValue())
vz=App.Vector(c.getViewVolume().getMatrix().multVecMatrix(coin.SbVec3f(0,0,10)).getValue())
(vx-vo).Length
(vy-vo).Length
(vz-vo).Length
# Projection
vo.z=0
vx.z=0
vy.z=0
vz.z=0
(vx-vo).Length
(vy-vo).Length
(vz-vo).Length
See also: http://www.mathematik.uni-marburg.de/~thormae/lectures/graphics1/graphics_6_2_ger_web.html#1 http://www.mathematik.uni-marburg.de/~thormae/lectures/graphics1/code_v2/Axonometric/qt/Axonometric.cpp https://de.wikipedia.org/wiki/Arkussinus_und_Arkuskosinus
Definition at line 96 of file Camera.cpp.
Referenced by Path.Dressup.Tags.Tag::filterIntersections(), Path.Dressup.Tags.Tag::intersects(), and rotation().
trimetric()
SbRotation Camera::trimetric () static
Definition at line 157 of file Camera.cpp.
Referenced by rotation().
The documentation for this class was generated from the following files:
Camera.h
Camera.cpp