FreeCAD: AppPath.cpp File Reference
AppPath.cpp File Reference
#include "PreCompiled.h"
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include "AreaPy.h"
#include "Command.h"
#include "CommandPy.h"
#include "FeatureArea.h"
Namespaces
PathApp
Functions
PyObject * PathApp::initModule ()
PyMOD_INIT_FUNC (PathApp)
Function Documentation
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (PathApp)
Definition at line 54 of file AppPath.cpp.
References Base::InterpreterSingleton::addType(), Base::Console(), SCL.SimpleDataTypes::e, SIM::Coin3D::Quarter::Quarter::init(), PathApp::initModule(), Base::Interpreter(), Base::ConsoleSingleton::Log(), src.Mod.PartDesign.fcgear.svggear::module, PyMOD_Return, and Base::InterpreterSingleton::runString().