FreeCAD: Gui::OverlayTabWidget Class Reference
Gui::OverlayTabWidget Class Reference
Tab widget to contain dock widgets in overlay mode.
#include <OverlayWidgets.h>
Graphics effect properties for customization through stylesheet
enum AutoMode {
AutoMode::NoAutoMode, AutoMode::AutoHide, AutoMode::EditShow, AutoMode::EditHide,
AutoMode::TaskShow
}
Auto mode to show or hide the tab widget.
enum QueryOption { QueryOption::QueryOverlay, QueryOption::TransparencyChanged, QueryOption::TransparencyNotChanged }
Overlay query option.
QColor effectColor
int effectWidth
int effectHeight
qreal effectOffsetX
qreal effectOffsetY
qreal effectBlurRadius
bool enableEffect
qreal animation
OverlayTabWidget (QWidget *parent, Qt::DockWidgetArea pos)
void setOverlayMode (bool enable)
Enable/disable overlay mode for this tab widget.
void updateSplitterHandles ()
Update splitter handle according to overlay status.
void addWidget (QDockWidget *widget, const QString &title)
void removeWidget (QDockWidget *widget, QDockWidget *last=nullptr)
void setCurrent (QDockWidget *widget)
bool onEscape ()
void setTransparent (bool enable)
Enable/disable transparent background mode.
bool isTransparent () const
Check if transparent background mode is active.
void setAutoMode (AutoMode mode)
Set auto mode to show or hide the tab widget.
AutoMode getAutoMode () const
Get current auto mode.
void touch ()
Touch the tab widget to trigger saving of settings.
bool isTouched () const
Check if the tab widget settings need to be saved.
void setRect (QRect rect)
Set geometry of this tab widget.
const QRect & getRect ()
Get the geometry of this tab widget.
bool isOverlaid (QueryOption option=QueryOption::QueryOverlay) const
Query overlay status.
bool checkAutoHide () const
bool getAutoHideRect (QRect &rect) const
void onAction (QAction *)
Handler of various actions exposed as buttons on title bar.
void syncAutoMode ()
Sync relevant actions status with the current auto mode.
void setOffset (const QSize &ofs)
const QSize & getOffset () const
Get the tab widget position offset.
void setSizeDelta (int delta)
int getSizeDelta () const
Get the tab widget size delta.
OverlayProxyWidget * getProxyWidget ()
Obtain the proxy widget.
QDockWidget * currentDockWidget () const
Obtain the current dock widget.
QDockWidget * dockWidget (int index) const
Obtain the dock widget by index.
int dockWidgetIndex (QDockWidget *) const
Obtain the index of a given dock widget.
void setTitleBar (QWidget *)
Set the title bar for this tab widget.
QSplitter * getSplitter () const
Get the splitter.
QWidget * getTitleBar () const
Get the title bar.
Qt::DockWidgetArea getDockArea () const
Get the docking position of this tab widget.
const QTime & getRevealTime () const
Get delay time for animated reveal.
void setRevealTime (const QTime &time)
Set delay time for animated reveal.
void restore (ParameterGrp::handle handle)
Restore state.
void saveTabs ()
Save tab orders and positions.
static bool isStyleSheetDark (std::string curStyleSheet)
static QPixmap rotateAutoHideIcon (QPixmap pxAutoHide, Qt::DockWidgetArea dockArea)
Graphics effect properties setters and getters
enum State {
State::Showing, State::Normal, State::Hint, State::HintHidden,
State::Hidden
}
Internal state of the tab widget.
enum OverlayOption { OverlayOption::Enable, OverlayOption::Disable, OverlayOption::ShowTab }
Overlay mode options.
class OverlayProxyWidget
class OverlayTitleBar
class OverlayManager
class OverlayManager::Private
class OverlaySplitterHandle
class OverlaySizeGrip
QColor effectColor () const
void setEffectColor (const QColor &)
int effectWidth () const
void setEffectWidth (int)
int effectHeight () const
void setEffectHeight (int)
qreal effectOffsetX () const
void setEffectOffsetX (qreal)
qreal effectOffsetY () const
void setEffectOffsetY (qreal)
qreal effectBlurRadius () const
void setEffectBlurRadius (qreal)
bool effectEnabled () const
void setEffectEnabled (bool)
qreal animation () const
void setAnimation (qreal)
void scheduleRepaint ()
Schedule for repaint.
int testAlpha (const QPoint &pos, int radiusScale)
void startShow ()
Start animated showing.
void startHide ()
Start animated hiding.
void setState (State)
Set state of the tab widget.
State getState () const
Get the state of the widget.
void onSplitterResize (int index)
Handle splitter resize.
bool isSaving () const
Check if the tab widget is saving its state.
static QWidget * createTitleButton (QAction *action, int size)
Helper function to create title bar for a dock widget.
static QLayoutItem * prepareTitleWidget (QWidget *widget, const QList< QAction * > &actions)
Helper function to prepare a widget as a title widget.
void enterEvent (QEnterEvent *ev) override
void leaveEvent (QEvent *ev) override
void changeEvent (QEvent *ev) override
void resizeEvent (QResizeEvent *ev) override
void paintEvent (QPaintEvent *ev) override
bool event (QEvent *ev) override
bool eventFilter (QObject *obj, QEvent *ev) override
void retranslate ()
void refreshIcons ()
void setOverlayMode (QWidget *widget, OverlayOption option)
Toggle overlay mode for a given widget.
void onCurrentChanged (int index)
void onTabMoved (int from, int to)
void onRepaint ()
void onAnimationStateChanged ()
void setupLayout ()
void onSizeGripMove (const QPoint &)
static void _setOverlayMode (QWidget *widget, OverlayOption option)
Helper function to set overlay mode for a give widget.
Detailed Description
Tab widget to contain dock widgets in overlay mode.
Definition at line 55 of file OverlayWidgets.h.
Member Enumeration Documentation
AutoMode
enum Gui::OverlayTabWidget::AutoMode strong
Auto mode to show or hide the tab widget.
Enumerator
NoAutoMode
No auto show or hide.
AutoHide
Auto hide tab widget on lost of focus.
EditShow
Auto show tab widget on any new editing task.
EditHide
Auto hide tab widget on any new editing task.
TaskShow
Auto show on any task panel e.g. suggestive task panel in PartDesign.
Definition at line 124 of file OverlayWidgets.h.
OverlayOption
enum Gui::OverlayTabWidget::OverlayOption strong protected
Overlay mode options.
Enumerator
Enable
Enable overlay.
Disable
Disable overlay.
ShowTab
Enable overlay and show tab bar.
Definition at line 321 of file OverlayWidgets.h.
QueryOption
enum Gui::OverlayTabWidget::QueryOption strong
Overlay query option.
Enumerator
QueryOverlay
Report the current overlay status.
TransparencyChanged
Report true if transparency status has been changed.
TransparencyNotChanged
Report true if transparency status has not been changed.
Definition at line 153 of file OverlayWidgets.h.
State
enum Gui::OverlayTabWidget::State strong
Internal state of the tab widget.
Enumerator
Showing
The tab widget is showing.
Normal
Normal visible state.
Hint
Visual hint is visible.
HintHidden
Hint is hidden by user after pressing ESC.
Hidden
The tab widget is explicitly hidden by user.
Definition at line 276 of file OverlayWidgets.h.
Constructor & Destructor Documentation
OverlayTabWidget()
OverlayTabWidget::OverlayTabWidget (QWidget * parent, Qt::DockWidgetArea pos)
Constructor
Parameters
parent parent widget
pos docking position
Definition at line 337 of file OverlayWidgets.cpp.
References _setOverlayMode(), Gui::Command::addTo(), Gui::Application::commandManager(), draftgeoutils.intersections::connect(), Enable, Gui::CommandManager::getCommandByName(), ArchFence::hide(), Sketcher::Horizontal, Gui::Application::Instance, onAnimationStateChanged(), onCurrentChanged(), onRepaint(), onTabMoved(), OverlayProxyWidget, RobotExample::pos, refreshIcons(), retranslate(), Gui::OverlayGraphicsEffect::setEnabled(), setOverlayMode(), setupLayout(), and Sketcher::Vertical.
Member Function Documentation
_setOverlayMode()
void OverlayTabWidget::_setOverlayMode (QWidget * widget, OverlayOption option) static protected
Helper function to set overlay mode for a give widget.
Definition at line 1195 of file OverlayWidgets.cpp.
References Disable, Gui::OverlayParams::getDockOverlayHidePropertyViewScrollBar(), Gui::TreeParams::getHideHeaderView(), Gui::TreeParams::getHideScrollBar(), Gui::OverlayManager::instance(), Init::parent, and ShowTab.
Referenced by OverlayTabWidget(), and setOverlayMode().
addWidget()
void OverlayTabWidget::addWidget (QDockWidget * widget, const QString & title)
Add a dock widget
Parameters
widget dock widget to be added
title title for the dock widget
Definition at line 1629 of file OverlayWidgets.cpp.
References draftgeoutils.intersections::connect(), src.Mod.AddonManager.NetworkManager::count, Gui::getMainWindow(), Plot::getMdiArea(), Gui::MainWindow::getMdiArea(), Gui::OverlayManager::instance(), Gui::OverlayManager::registerDockWidget(), saveTabs(), Gui::OverlayManager::setFocusView(), setRect(), Plot::title(), and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by OverlayInfo::addWidget(), and restore().
animation()
qreal Gui::OverlayTabWidget::animation () const inline
Definition at line 252 of file OverlayWidgets.h.
changeEvent()
void OverlayTabWidget::changeEvent (QEvent * ev) override protected
Definition at line 859 of file OverlayWidgets.cpp.
References SCL.SimpleDataTypes::e, and retranslate().
checkAutoHide()
bool OverlayTabWidget::checkAutoHide () const
Check if needs to auto hide this tab widget
Besides when auto hide mode is activated by user, the tab widget will also auto hide if the current view does not have panning capability (queried through MdiView::hasMsg("CanPan")). The user can explicitly disable this auto hide if no pan by setting user parameter View/DockOverlayAutoView, or preference option Display -> UI -> Auto hide in non 3D view.
Definition at line 1137 of file OverlayWidgets.cpp.
References Gui::MainWindow::activeWindow(), AutoHide, Gui::Control(), Gui::Application::editDocument(), EditHide, EditShow, Gui::OverlayParams::getDockOverlayAutoView(), Gui::getMainWindow(), Gui::Application::Instance, Gui::TaskView::TaskView::isEmpty(), and Gui::ControlSingleton::taskPanel().
Referenced by getAutoHideRect().
createTitleButton()
QWidget * OverlayTabWidget::createTitleButton (QAction * action, int size) static
Helper function to create title bar for a dock widget.
Definition at line 524 of file OverlayWidgets.cpp.
References Path.Post.scripts.dynapath_4060_post::action.
Referenced by prepareTitleWidget().
currentDockWidget()
QDockWidget * OverlayTabWidget::currentDockWidget () const
Obtain the current dock widget.
Definition at line 1369 of file OverlayWidgets.cpp.
References dockWidget().
Referenced by OverlayInfo::removeWidget().
dockWidget()
QDockWidget * OverlayTabWidget::dockWidget (int index) const
Obtain the dock widget by index.
Definition at line 1380 of file OverlayWidgets.cpp.
Referenced by currentDockWidget(), Gui::OverlayManager::Private::onToggleDockWidget(), Gui::OverlayTitleBar::paintEvent(), OverlayInfo::removeWidget(), restore(), OverlayInfo::restore(), and saveTabs().
dockWidgetIndex()
int OverlayTabWidget::dockWidgetIndex (QDockWidget * dock) const
Obtain the index of a given dock widget.
Definition at line 1680 of file OverlayWidgets.cpp.
Referenced by OverlayInfo::addWidget(), Gui::OverlayManager::Private::dragDockWidget(), Gui::OverlayManager::Private::onToggleDockWidget(), removeWidget(), and setCurrent().
effectBlurRadius()
qreal Gui::OverlayTabWidget::effectBlurRadius () const
effectColor()
QColor Gui::OverlayTabWidget::effectColor () const
effectEnabled()
bool OverlayTabWidget::effectEnabled () const
Definition at line 734 of file OverlayWidgets.cpp.
Referenced by setOverlayMode().
effectHeight()
int Gui::OverlayTabWidget::effectHeight () const
effectOffsetX()
qreal Gui::OverlayTabWidget::effectOffsetX () const
effectOffsetY()
qreal Gui::OverlayTabWidget::effectOffsetY () const
effectWidth()
int Gui::OverlayTabWidget::effectWidth () const
enterEvent()
void OverlayTabWidget::enterEvent (QEnterEvent * ev) override protected
Definition at line 1183 of file OverlayWidgets.cpp.
References Gui::OverlayManager::instance(), and Gui::OverlayManager::refresh().
event()
bool OverlayTabWidget::event (QEvent * ev) override protected
Definition at line 554 of file OverlayWidgets.cpp.
eventFilter()
bool OverlayTabWidget::eventFilter (QObject * obj, QEvent * ev) override protected
Definition at line 744 of file OverlayWidgets.cpp.
References Normal, and src.Mod.Test.testPathArray::o.
getAutoHideRect()
bool OverlayTabWidget::getAutoHideRect (QRect & rect) const
Obtain geometry of auto hiding tab widget
Parameters
rect output geometry of the tab widget
Returns
Return true if the tab widget should be auto hiding
Definition at line 1479 of file OverlayWidgets.cpp.
References checkAutoHide(), Gui::OverlayParams::getDockOverlayHintSize(), Gui::getMainWindow(), Gui::MainWindow::getMdiArea(), KDL::max(), KDL::min(), Normal, and Showing.
Referenced by setRect().
getAutoMode()
AutoMode Gui::OverlayTabWidget::getAutoMode () const inline
Get current auto mode.
Definition at line 139 of file OverlayWidgets.h.
getDockArea()
Qt::DockWidgetArea Gui::OverlayTabWidget::getDockArea () const inline
Get the docking position of this tab widget.
Definition at line 224 of file OverlayWidgets.h.
Referenced by Gui::OverlayManager::Private::dragDockWidget(), Gui::OverlayProxyWidget::OverlayProxyWidget(), and Gui::OverlayTitleBar::paintEvent().
getOffset()
const QSize& Gui::OverlayTabWidget::getOffset () const inline
Get the tab widget position offset.
Definition at line 194 of file OverlayWidgets.h.
Referenced by Gui::OverlayManager::Private::onTimer().
getProxyWidget()
OverlayProxyWidget* Gui::OverlayTabWidget::getProxyWidget () inline
Obtain the proxy widget.
Definition at line 206 of file OverlayWidgets.h.
Referenced by OverlayInfo::OverlayInfo().
getRect()
const QRect & OverlayTabWidget::getRect ()
Get the geometry of this tab widget.
Definition at line 1474 of file OverlayWidgets.cpp.
Referenced by Gui::OverlayManager::Private::onTimer().
getRevealTime()
const QTime& Gui::OverlayTabWidget::getRevealTime () const inline
Get delay time for animated reveal.
Definition at line 227 of file OverlayWidgets.h.
getSizeDelta()
int Gui::OverlayTabWidget::getSizeDelta () const inline
Get the tab widget size delta.
Definition at line 203 of file OverlayWidgets.h.
Referenced by Gui::OverlayManager::Private::onTimer().
getSplitter()
QSplitter* Gui::OverlayTabWidget::getSplitter () const inline
Get the splitter.
Definition at line 219 of file OverlayWidgets.h.
Referenced by Gui::OverlayManager::Private::dragDockWidget(), Gui::OverlayTitleBar::mousePressEvent(), Gui::OverlayManager::Private::onToggleDockWidget(), and restore().
getState()
State Gui::OverlayTabWidget::getState () const inline
Get the state of the widget.
Definition at line 291 of file OverlayWidgets.h.
Referenced by Path.Base.MachineState.MachineState::addCommand(), Gui::OverlayProxyWidget::hitTest(), onEscape(), Gui::OverlayProxyWidget::onMousePress(), and Gui::OverlayManager::Private::onTimer().
getTitleBar()
QWidget* Gui::OverlayTabWidget::getTitleBar () const inline
Get the title bar.
Definition at line 221 of file OverlayWidgets.h.
isOverlaid()
bool OverlayTabWidget::isOverlaid (QueryOption option = QueryOption::QueryOverlay) const
Query overlay status.
Definition at line 1327 of file OverlayWidgets.cpp.
References isTransparent(), QueryOverlay, and TransparencyChanged.
Referenced by testAlpha().
isSaving()
bool Gui::OverlayTabWidget::isSaving () const inline
Check if the tab widget is saving its state.
Definition at line 297 of file OverlayWidgets.h.
Referenced by OverlayInfo::OverlayInfo().
isStyleSheetDark()
bool OverlayTabWidget::isStyleSheetDark (std::string curStyleSheet) static
Definition at line 1930 of file OverlayWidgets.cpp.
Referenced by refreshIcons(), and syncAutoMode().
isTouched()
bool Gui::OverlayTabWidget::isTouched () const inline
Check if the tab widget settings need to be saved.
Definition at line 144 of file OverlayWidgets.h.
isTransparent()
bool OverlayTabWidget::isTransparent () const
Check if transparent background mode is active.
Definition at line 1312 of file OverlayWidgets.cpp.
References Gui::MainWindow::activeWindow(), Gui::OverlayParams::getDockOverlayAutoView(), and Gui::getMainWindow().
Referenced by Gui::OverlayManager::eventFilter(), isOverlaid(), setOverlayMode(), and testAlpha().
leaveEvent()
void OverlayTabWidget::leaveEvent (QEvent * ev) override protected
Definition at line 1173 of file OverlayWidgets.cpp.
References Gui::OverlayManager::instance(), and Gui::OverlayManager::refresh().
onAction()
void OverlayTabWidget::onAction (QAction * action)
Handler of various actions exposed as buttons on title bar.
Definition at line 1043 of file OverlayWidgets.cpp.
References Path.Post.scripts.dynapath_4060_post::action, AutoHide, EditHide, EditShow, Gui::OverlayManager::instance(), NoAutoMode, RobotExample::pos, Gui::OverlayManager::refresh(), setAutoMode(), ParameterGrp::SetBool(), Gui::OverlayManager::setOverlayMode(), TaskShow, and Gui::OverlayManager::ToggleActive.
onAnimationStateChanged()
void OverlayTabWidget::onAnimationStateChanged () protected
Definition at line 479 of file OverlayWidgets.cpp.
References ArchFence::hide(), Gui::OverlayManager::instance(), Normal, Gui::OverlayManager::refresh(), setAnimation(), setState(), and Showing.
Referenced by OverlayTabWidget().
onCurrentChanged()
void OverlayTabWidget::onCurrentChanged (int index) protected
Definition at line 1826 of file OverlayWidgets.cpp.
References SplineSurface::i, onSplitterResize(), toolbit-attributes::s, saveTabs(), setState(), Showing, and Sketcher::Vertical.
Referenced by Gui::OverlayManager::Private::dragDockWidget(), Gui::OverlayManager::Private::onToggleDockWidget(), and OverlayTabWidget().
onEscape()
bool OverlayTabWidget::onEscape ()
Handle ESC key press
If the this overlay tab widget is hidden and its hint/tabs are visible, pressing ESC will hide the hint and tabs.
If this overlay tab widget is visible and the current mouse cursor is on top of the tab widget title bar or any of its split handler, then pressing ESC will hide the title bar and split handler.
Definition at line 1398 of file OverlayWidgets.cpp.
References SCL.SimpleDataTypes::c, getState(), Hidden, Hint, HintHidden, SplineSurface::i, and setState().
onRepaint()
void OverlayTabWidget::onRepaint () protected
Definition at line 641 of file OverlayWidgets.cpp.
Referenced by OverlayTabWidget().
onSizeGripMove()
void OverlayTabWidget::onSizeGripMove (const QPoint & p) protected
Definition at line 1845 of file OverlayWidgets.cpp.
References Gui::OverlayParams::getDockOverlayMinimumSize(), Gui::getMainWindow(), Plot::getMdiArea(), Gui::MainWindow::getMdiArea(), Gui::OverlayManager::instance(), buildPsets::p, RobotExample::pos, Gui::OverlayManager::refresh(), and setRect().
Referenced by prepareTitleWidget().
onSplitterResize()
void OverlayTabWidget::onSplitterResize (int index)
Handle splitter resize.
Definition at line 1796 of file OverlayWidgets.cpp.
References SplineSurface::i, and saveTabs().
Referenced by Gui::OverlayManager::Private::dragDockWidget(), and onCurrentChanged().
onTabMoved()
void OverlayTabWidget::onTabMoved (int from, int to) protected
Definition at line 847 of file OverlayWidgets.cpp.
References saveTabs(), and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by OverlayTabWidget().
paintEvent()
void OverlayTabWidget::paintEvent (QPaintEvent * ev) override protected
Definition at line 632 of file OverlayWidgets.cpp.
prepareTitleWidget()
QLayoutItem * OverlayTabWidget::prepareTitleWidget (QWidget * widget, const QList< QAction * > & actions) static
Helper function to prepare a widget as a title widget.
Definition at line 1880 of file OverlayWidgets.cpp.
References Path.Post.scripts.dynapath_4060_post::action, draftgeoutils.intersections::connect(), createTitleButton(), Gui::OverlaySizeGrip::dragMove(), onSizeGripMove(), OverlaySizeGrip, and widgetMinSize().
Referenced by Gui::OverlaySplitter::createHandle(), and Gui::OverlayManager::Private::createTitleBar().
refreshIcons()
void OverlayTabWidget::refreshIcons () protected
Definition at line 446 of file OverlayWidgets.cpp.
References Gui::BitmapFactory(), App::GetApplication(), ParameterGrp::GetASCII(), App::Application::GetParameterGroupByPath(), isStyleSheetDark(), Gui::BitmapFactoryInst::pixmap(), rotateAutoHideIcon(), and syncAutoMode().
Referenced by OverlayTabWidget().
removeWidget()
void OverlayTabWidget::removeWidget (QDockWidget * widget, QDockWidget * last = nullptr)
Remove a dock widget
Parameters
widget dock widget to be removed
last optional non overlaid widget. If given, then the removed dock widget will be tabified together with this one.
Definition at line 1685 of file OverlayWidgets.cpp.
References src.Mod.AddonManager.NetworkManager::count, Disable, dockWidgetIndex(), Gui::getMainWindow(), ArchFence::hide(), Gui::OverlayManager::instance(), saveTabs(), Gui::OverlayManager::setFocusView(), setOverlayMode(), Gui::OverlayManager::setupTitleBar(), Gui::OverlayManager::unregisterDockWidget(), and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by OverlayInfo::removeWidget().
resizeEvent()
void OverlayTabWidget::resizeEvent (QResizeEvent * ev) override protected
Definition at line 1721 of file OverlayWidgets.cpp.
References Normal.
restore()
void OverlayTabWidget::restore (ParameterGrp::handle handle)
Restore state.
Definition at line 753 of file OverlayWidgets.cpp.
References addWidget(), AutoHide, dockWidget(), EditHide, EditShow, FC_LOG, ParameterGrp::GetASCII(), ParameterGrp::GetBool(), ParameterGrp::GetInt(), Gui::getMainWindow(), getSplitter(), Gui::OverlayManager::instance(), NoAutoMode, Gui::OverlayManager::registerDockWidget(), setAutoMode(), setOffset(), setRect(), setSizeDelta(), setTransparent(), and TaskShow.
Referenced by src.Mod.Show.mTempoVis.TempoVis::__del__(), and OverlayInfo::restore().
retranslate()
void OverlayTabWidget::retranslate () protected
Definition at line 866 of file OverlayWidgets.cpp.
References syncAutoMode().
Referenced by changeEvent(), and OverlayTabWidget().
rotateAutoHideIcon()
QPixmap OverlayTabWidget::rotateAutoHideIcon (QPixmap pxAutoHide, Qt::DockWidgetArea dockArea) static
Definition at line 1939 of file OverlayWidgets.cpp.
References src.Mod.PartDesign.fcgear.fcgear::rotate, and draftfunctions.scale::scale().
Referenced by refreshIcons(), and syncAutoMode().
saveTabs()
void OverlayTabWidget::saveTabs ()
Save tab orders and positions.
Definition at line 818 of file OverlayWidgets.cpp.
References SCL.SimpleDataTypes::c, dockWidget(), FC_LOG, SplineSurface::i, and ParameterGrp::SetASCII().
Referenced by addWidget(), OverlayInfo::addWidget(), Gui::OverlayManager::Private::dragDockWidget(), onCurrentChanged(), onSplitterResize(), onTabMoved(), Gui::OverlayManager::Private::onToggleDockWidget(), removeWidget(), and OverlayInfo::removeWidget().
scheduleRepaint()
void OverlayTabWidget::scheduleRepaint ()
Schedule for repaint.
Definition at line 650 of file OverlayWidgets.cpp.
setAnimation()
void OverlayTabWidget::setAnimation (qreal t)
Definition at line 492 of file OverlayWidgets.cpp.
References setupLayout(), and InitGui::t.
Referenced by onAnimationStateChanged().
setAutoMode()
void OverlayTabWidget::setAutoMode (AutoMode mode)
Set auto mode to show or hide the tab widget.
Definition at line 1335 of file OverlayWidgets.cpp.
References AutoHide, EditHide, EditShow, Gui::OverlayManager::instance(), Gui::OverlayManager::refresh(), ParameterGrp::SetBool(), syncAutoMode(), and TaskShow.
Referenced by onAction(), and restore().
setCurrent()
void OverlayTabWidget::setCurrent (QDockWidget * widget)
Set the current dock widget
Parameters
widget an overlay dock widget
All other dock widget in the same tab widget will be collapsed, and the give widget will take the whole space. This is actually handled inside onCurrentChanged().
Definition at line 1789 of file OverlayWidgets.cpp.
References dockWidgetIndex().
Referenced by OverlayInfo::addWidget(), and Gui::OverlayManager::Private::onToggleDockWidget().
setEffectBlurRadius()
void OverlayTabWidget::setEffectBlurRadius (qreal r)
Definition at line 728 of file OverlayWidgets.cpp.
References Gui::OverlayGraphicsEffect::setBlurRadius().
setEffectColor()
void OverlayTabWidget::setEffectColor (const QColor & color)
Definition at line 665 of file OverlayWidgets.cpp.
References Gui::OverlayGraphicsEffect::setColor().
setEffectEnabled()
void OverlayTabWidget::setEffectEnabled (bool enable)
Definition at line 739 of file OverlayWidgets.cpp.
setEffectHeight()
void OverlayTabWidget::setEffectHeight (int s)
Definition at line 689 of file OverlayWidgets.cpp.
References toolbit-attributes::s, Gui::OverlayGraphicsEffect::setSize(), and Gui::OverlayGraphicsEffect::size().
setEffectOffsetX()
void OverlayTabWidget::setEffectOffsetX (qreal d)
Definition at line 702 of file OverlayWidgets.cpp.
References Gui::OverlayGraphicsEffect::offset(), and Gui::OverlayGraphicsEffect::setOffset().
setEffectOffsetY()
void OverlayTabWidget::setEffectOffsetY (qreal d)
Definition at line 715 of file OverlayWidgets.cpp.
References Gui::OverlayGraphicsEffect::offset(), and Gui::OverlayGraphicsEffect::setOffset().
setEffectWidth()
void OverlayTabWidget::setEffectWidth (int s)
Definition at line 676 of file OverlayWidgets.cpp.
References toolbit-attributes::s, Gui::OverlayGraphicsEffect::setSize(), and Gui::OverlayGraphicsEffect::size().
setOffset()
void OverlayTabWidget::setOffset (const QSize & ofs)
Set tab widget position offset
Parameters
ofs the offset size. Width is the x offset for top and bottom docking tab widget, and y offset for left and right ones. Height is the y offset for top and bottom, and x offset for left and right ones.
Definition at line 1513 of file OverlayWidgets.cpp.
References ParameterGrp::SetInt().
Referenced by ArchPipe._ArchPipeConnector::execute(), and restore().
setOverlayMode() [1/2]
void OverlayTabWidget::setOverlayMode (bool enable)
Enable/disable overlay mode for this tab widget.
Definition at line 1421 of file OverlayWidgets.cpp.
References AutoHide, SCL.SimpleDataTypes::c, src.Mod.AddonManager.NetworkManager::count, Disable, EditShow, effectEnabled(), Enable, Gui::OverlayParams::getDockOverlayHideTabBar(), Gui::OverlayParams::getDockOverlayHintTabBar(), Gui::OverlayManager::getStyleSheet(), Hint, SplineSurface::i, Gui::OverlayManager::instance(), isTransparent(), Normal, Gui::OverlayGraphicsEffect::setEnabled(), Path.Base.Util::setProperty(), setRect(), and ShowTab.
Referenced by Gui::OverlayManager::Private::onTimer(), OverlayTabWidget(), removeWidget(), setOverlayMode(), and startShow().
setOverlayMode() [2/2]
void OverlayTabWidget::setOverlayMode (QWidget * widget, OverlayOption option) protected
Toggle overlay mode for a given widget.
Definition at line 1275 of file OverlayWidgets.cpp.
References _setOverlayMode(), Gui::OverlayParams::getDockOverlayAutoMouseThrough(), setOverlayMode(), and ShowTab.
setRect()
void OverlayTabWidget::setRect (QRect rect)
Set geometry of this tab widget.
Definition at line 1536 of file OverlayWidgets.cpp.
References src.Mod.AddonManager.NetworkManager::count, getAutoHideRect(), Gui::OverlayParams::getDockOverlayHintTabBar(), Gui::OverlayParams::getDockOverlayMinimumSize(), Gui::getMainWindow(), Plot::getMdiArea(), Gui::MainWindow::getMdiArea(), Hidden, Hint, SplineSurface::i, KDL::max(), ParameterGrp::SetInt(), startHide(), startShow(), MovieTool::x, and MovieTool::y.
Referenced by addWidget(), onSizeGripMove(), Gui::OverlayManager::Private::onTimer(), restore(), and setOverlayMode().
setRevealTime()
void OverlayTabWidget::setRevealTime (const QTime & time)
Set delay time for animated reveal.
Definition at line 1190 of file OverlayWidgets.cpp.
Referenced by Gui::OverlayManager::Private::dragDockWidget(), and Gui::OverlayManager::Private::onToggleDockWidget().
setSizeDelta()
void OverlayTabWidget::setSizeDelta (int delta)
Set tab widget size delta
Parameters
delta the size delta. For left and right widget, the delta is added to the height of the tab widget. For top and bottom widget, it is added to the width.
Definition at line 1525 of file OverlayWidgets.cpp.
References ParameterGrp::SetInt().
Referenced by restore().
setState()
void OverlayTabWidget::setState (State state)
Set state of the tab widget.
Definition at line 1071 of file OverlayWidgets.cpp.
References src.Mod.AddonManager.NetworkManager::count, Gui::OverlayParams::getDockOverlayHintTabBar(), Hidden, ArchFence::hide(), Hint, HintHidden, Gui::OverlayManager::instance(), Normal, Gui::OverlayManager::refresh(), Gui::OverlayGraphicsEffect::setEnabled(), bimcommands.BimViews::show(), Showing, and startHide().
Referenced by Gui::OverlayProxyWidget::hitTest(), onAnimationStateChanged(), onCurrentChanged(), onEscape(), Gui::OverlayProxyWidget::onMousePress(), and startShow().
setTitleBar()
void OverlayTabWidget::setTitleBar (QWidget * w)
Set the title bar for this tab widget.
Definition at line 854 of file OverlayWidgets.cpp.
References src.Mod.PartDesign.fcgear.svggear::w.
setTransparent()
void OverlayTabWidget::setTransparent (bool enable)
Enable/disable transparent background mode.
Definition at line 1300 of file OverlayWidgets.cpp.
References Gui::OverlayManager::instance(), Gui::OverlayManager::refresh(), and ParameterGrp::SetBool().
Referenced by restore().
setupLayout()
void OverlayTabWidget::setupLayout () protected
Definition at line 1728 of file OverlayWidgets.cpp.
References src.Mod.AddonManager.NetworkManager::count, Normal, and widgetMinSize().
Referenced by OverlayTabWidget(), and setAnimation().
startHide()
void OverlayTabWidget::startHide ()
Start animated hiding.
Definition at line 535 of file OverlayWidgets.cpp.
References Gui::OverlayParams::getDockOverlayAnimationCurve(), Gui::OverlayParams::getDockOverlayAnimationDuration(), ArchFence::hide(), and Normal.
Referenced by setRect(), and setState().
startShow()
void OverlayTabWidget::startShow ()
Start animated showing.
Definition at line 500 of file OverlayWidgets.cpp.
References Gui::OverlayParams::getDockOverlayAnimationCurve(), Gui::OverlayParams::getDockOverlayAnimationDuration(), Normal, setOverlayMode(), setState(), bimcommands.BimViews::show(), and Showing.
Referenced by setRect().
syncAutoMode()
void OverlayTabWidget::syncAutoMode ()
Sync relevant actions status with the current auto mode.
Definition at line 883 of file OverlayWidgets.cpp.
References Path.Post.scripts.dynapath_4060_post::action, AutoHide, Gui::BitmapFactory(), EditHide, EditShow, App::GetApplication(), ParameterGrp::GetASCII(), App::Application::GetParameterGroupByPath(), isStyleSheetDark(), Gui::BitmapFactoryInst::pixmap(), rotateAutoHideIcon(), and TaskShow.
Referenced by refreshIcons(), retranslate(), and setAutoMode().
testAlpha()
int OverlayTabWidget::testAlpha (const QPoint & pos, int radiusScale)
Return the pixel alpha value at the give position
Parameters
pos position
radiusScale scale of the radius to check for alpha.
Returns
Returns the largest alpha value of a circular area of 'pos' as center and radius as defined by user parameter View/DockOverlayAlphaRadius. May return -1 if out side of the widget, or zero if transparent.
Definition at line 581 of file OverlayWidgets.cpp.
References src.Mod.AddonManager.NetworkManager::count, Gui::OverlayParams::getDockOverlayAlphaRadius(), SplineSurface::i, isOverlaid(), isTransparent(), and RobotExample::pos.
touch()
void Gui::OverlayTabWidget::touch () inline
Touch the tab widget to trigger saving of settings.
Definition at line 142 of file OverlayWidgets.h.
updateSplitterHandles()
void OverlayTabWidget::updateSplitterHandles ()
Update splitter handle according to overlay status.
Definition at line 1387 of file OverlayWidgets.cpp.
References SCL.SimpleDataTypes::c, SplineSurface::i, and Normal.
Referenced by Gui::OverlayManager::Private::onTimer().
Friends And Related Function Documentation
OverlayManager
friend class OverlayManager friend
Definition at line 345 of file OverlayWidgets.h.
OverlayManager::Private
friend class OverlayManager::Private friend
Definition at line 346 of file OverlayWidgets.h.
OverlayProxyWidget
friend class OverlayProxyWidget friend
Definition at line 343 of file OverlayWidgets.h.
Referenced by OverlayTabWidget().
OverlaySizeGrip
friend class OverlaySizeGrip friend
Definition at line 348 of file OverlayWidgets.h.
Referenced by prepareTitleWidget().
OverlaySplitterHandle
friend class OverlaySplitterHandle friend
Definition at line 347 of file OverlayWidgets.h.
OverlayTitleBar
friend class OverlayTitleBar friend
Definition at line 344 of file OverlayWidgets.h.
Property Documentation
animation
qreal Gui::OverlayTabWidget::animation read write
Definition at line 68 of file OverlayWidgets.h.
effectBlurRadius
qreal OverlayTabWidget::effectBlurRadius read write
Definition at line 66 of file OverlayWidgets.h.
effectColor
QColor OverlayTabWidget::effectColor read write
Definition at line 61 of file OverlayWidgets.h.
effectHeight
int OverlayTabWidget::effectHeight read write
Definition at line 63 of file OverlayWidgets.h.
effectOffsetX
qreal OverlayTabWidget::effectOffsetX read write
Definition at line 64 of file OverlayWidgets.h.
effectOffsetY
qreal OverlayTabWidget::effectOffsetY read write
Definition at line 65 of file OverlayWidgets.h.
effectWidth
int OverlayTabWidget::effectWidth read write
Definition at line 62 of file OverlayWidgets.h.
enableEffect
bool Gui::OverlayTabWidget::enableEffect read write
Definition at line 67 of file OverlayWidgets.h.
The documentation for this class was generated from the following files:
OverlayWidgets.h
OverlayWidgets.cpp