FreeCAD: PartDesignGui::TaskPipeOrientation Class Reference
PartDesignGui::TaskPipeOrientation Class Reference
#include <TaskPipeParameters.h>
Public Member Functions
TaskPipeOrientation (ViewProviderPipe *PipeView, bool newObj=false, QWidget *parent=nullptr)
~TaskPipeOrientation () override
Public Member Functions inherited from PartDesignGui::TaskSketchBasedParameters
TaskSketchBasedParameters (PartDesignGui::ViewProvider *vp, QWidget *parent, const std::string &pixmapname, const QString &parname)
~TaskSketchBasedParameters () override
Public Member Functions inherited from PartDesignGui::TaskFeatureParameters
TaskFeatureParameters (PartDesignGui::ViewProvider *vp, QWidget *parent, const std::string &pixmapname, const QString &parname)
~TaskFeatureParameters () override=default
virtual void saveHistory ()
save field history
virtual void apply ()
apply changes made in the parameters input to the model via commands
void recomputeFeature ()
bool isUpdateBlocked () const
Public Member Functions inherited from Gui::TaskView::TaskBox
TaskBox (QWidget *parent=nullptr)
TaskBox (const QString &title, bool expandable=true, QWidget *parent=nullptr)
TaskBox (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
QSize minimumSizeHint () const override
~TaskBox () override
void hideGroupBox ()
bool isGroupVisible () const
Public Member Functions inherited from QSint::ActionGroup
ActionGroup (QWidget *parent=nullptr)
ActionGroup (const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionGroup (const QPixmap &icon, const QString &title, bool expandable=true, QWidget *parent=nullptr)
ActionLabel * addAction (QAction *action, bool addToLayout=true, bool addStretch=true)
ActionLabel * addActionLabel (ActionLabel *label, bool addToLayout=true, bool addStretch=true)
bool addWidget (QWidget *widget, bool addToLayout=true, bool addStretch=true)
QBoxLayout * groupLayout ()
void setScheme (ActionPanelScheme *pointer)
bool isExpandable () const
bool hasHeader () const
QString headerText () const
QSize minimumSizeHint () const override
Public Member Functions inherited from Gui::DocumentObserver
DocumentObserver ()
Constructor.
DocumentObserver (Document *)
virtual ~DocumentObserver ()
void attachDocument (Document *)
void detachDocument ()
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Protected Member Functions
void removeFromListWidget (QListWidget *w, QString name)
bool referenceSelected (const Gui::SelectionChanges &msg) const
Protected Member Functions inherited from PartDesignGui::TaskSketchBasedParameters
const QString onAddSelection (const Gui::SelectionChanges &msg)
virtual void startReferenceSelection (App::DocumentObject *profile, App::DocumentObject *base)
virtual void finishReferenceSelection (App::DocumentObject *profile, App::DocumentObject *base)
void onSelectReference (AllowSelectionFlags)
onSelectReference Start reference selection mode to allow one to select objects of the type defined with AllowSelectionFlags. If AllowSelection::NONE is passed the selection mode is finished.
void exitSelectionMode ()
QVariant setUpToFace (const QString &text)
QVariant objectNameByLabel (const QString &label, const QVariant &suggest) const
QString getFaceReference (const QString &obj, const QString &sub) const
QString make2DLabel (const App::DocumentObject *section, const std::vector< std::string > &subValues)
Protected Member Functions inherited from PartDesignGui::TaskFeatureParameters
template<typename T = PartDesignGui::ViewProvider>
T * getViewObject () const
template<typename T = App::DocumentObject>
T * getObject () const
Gui::Document * getGuiDocument () const
App::Document * getAppDocument () const
bool & getUpdateBlockRef ()
void setUpdateBlocked (bool value)
Protected Member Functions inherited from Gui::TaskView::TaskBox
void showEvent (QShowEvent *) override
void actionEvent (QActionEvent *) override
Protected Member Functions inherited from QSint::ActionGroup
void init (bool header)
void paintEvent (QPaintEvent *event) override
Friends
class TaskDlgPipeParameters
Additional Inherited Members
Public Slots inherited from QSint::ActionGroup
void showHide ()
void setExpandable (bool expandable=true)
void setHeader (bool enable=true)
void setHeaderText (const QString &title)
void setHeaderIcon (const QPixmap &icon)
Protected Slots inherited from PartDesignGui::TaskFeatureParameters
void onUpdateView (bool on)
Protected Slots inherited from QSint::ActionGroup
void processHide ()
void processShow ()
Protected Attributes inherited from QSint::ActionGroup
double m_foldStep
double m_foldDelta
double m_fullHeight
double m_tempHeight
int m_foldDirection
QPixmap m_foldPixmap
class TaskHeader * myHeader
class TaskGroup * myGroup
QWidget * myDummy
ActionPanelScheme * myScheme
Properties inherited from QSint::ActionGroup
bool expandable
bool header
QString headerText
Detailed Description
Definition at line 115 of file TaskPipeParameters.h.
Constructor & Destructor Documentation
TaskPipeOrientation()
TaskPipeOrientation::TaskPipeOrientation (ViewProviderPipe * PipeView, bool newObj = false, QWidget * parent = nullptr) explicit
Definition at line 577 of file TaskPipeParameters.cpp.
References PartDesign::Pipe::AuxilleryCurvelinear, PartDesign::Pipe::AuxillerySpine, Gui::SelectionObserver::blockSelection(), Gui::Application::commandManager(), draftgeoutils.intersections::connect(), Gui::CommandManager::getCommandByName(), Gui::ViewProviderDocumentObject::getObject(), Gui::Command::getShortcut(), App::PropertyLinkSub::getSubValues(), App::PropertyEnumeration::getValue(), App::PropertyString::getValue(), App::PropertyLinkSub::getValue(), App::PropertyBool::getValue(), QSint::ActionGroup::groupLayout(), Gui::Application::Instance, App::DocumentObject::Label, and PartDesign::Pipe::Mode.
~TaskPipeOrientation()
TaskPipeOrientation::~TaskPipeOrientation () override
Definition at line 656 of file TaskPipeParameters.cpp.
References PartDesignGui::ViewProviderPipe::AuxiliarySpine.
Member Function Documentation
referenceSelected()
bool TaskPipeOrientation::referenceSelected (const Gui::SelectionChanges & msg) const protected
Definition at line 777 of file TaskPipeParameters.cpp.
References Gui::SelectionChanges::AddSelection, toolbit-attributes::doc, SCL.SimpleDataTypes::f, DraftVecUtils::find(), PartDesignGui::TaskFeatureParameters::getObject(), PartDesignGui::StateHandlerTaskPipe::getSelectionMode(), and Path.Op.Surface::msg.
removeFromListWidget()
void TaskPipeOrientation::removeFromListWidget (QListWidget * w, QString name) protected
Definition at line 828 of file TaskPipeParameters.cpp.
References src.Mod.Test.testPathArray::items.
Friends And Related Function Documentation
TaskDlgPipeParameters
friend class TaskDlgPipeParameters friend
Definition at line 145 of file TaskPipeParameters.h.
The documentation for this class was generated from the following files:
TaskPipeParameters.h
TaskPipeParameters.cpp