FreeCAD: MeshGui::MeshFaceAddition Class Reference
MeshGui::MeshFaceAddition Class Reference
#include <MeshEditor.h>
Public Slots
void finishEditing ()
Public Member Functions
MeshFaceAddition (Gui::View3DInventor *parent)
~MeshFaceAddition () override
void startEditing (ViewProviderMesh *)
Detailed Description
Display data of a mesh kernel.
Author
Werner Mayer
Definition at line 92 of file MeshEditor.h.
Constructor & Destructor Documentation
MeshFaceAddition()
MeshFaceAddition::MeshFaceAddition (Gui::View3DInventor * parent) explicit
Definition at line 188 of file MeshEditor.cpp.
~MeshFaceAddition()
MeshFaceAddition::~MeshFaceAddition () override
Definition at line 193 of file MeshEditor.cpp.
Member Function Documentation
finishEditing
void MeshFaceAddition::finishEditing () slot
Definition at line 214 of file MeshEditor.cpp.
References Gui::View3DInventor::getViewer(), Init::parent, and OfflineRenderingUtils::viewer().
startEditing()
void MeshFaceAddition::startEditing (MeshGui::ViewProviderMesh * vp)
Definition at line 198 of file MeshEditor.cpp.
References MeshGui::ViewProviderFace::attach(), Gui::ViewProviderDocumentObject::getObject(), Gui::View3DInventor::getViewer(), MeshGui::ViewProviderFace::mesh, Init::parent, and OfflineRenderingUtils::viewer().
The documentation for this class was generated from the following files:
MeshEditor.h
MeshEditor.cpp