FreeCAD: SpreadsheetGui Namespace Reference
SpreadsheetGui Namespace Reference
Classes
class DlgBindSheet
class DlgSettingsImp
class DlgSheetConf
class LineEdit
class Module
class PropertiesDialog
class SheetModel
class SheetTableView
class SheetTableViewAccessibleInterface
class SheetView
class SheetViewHeader
class SheetViewPy
class SpreadsheetDelegate
class ViewProviderSheet
class Workbench
class WorkbenchHelper
Typedefs
using ViewProviderSheetPython = Gui::ViewProviderFeaturePythonT< ViewProviderSheet >
Functions
PyObject * initModule ()
Typedef Documentation
ViewProviderSheetPython
using SpreadsheetGui::ViewProviderSheetPython = typedef Gui::ViewProviderFeaturePythonT<ViewProviderSheet>
Definition at line 114 of file Spreadsheet/Gui/ViewProviderSpreadsheet.h.
Function Documentation
initModule()
PyObject* SpreadsheetGui::initModule ()
Definition at line 119 of file AppSpreadsheetGui.cpp.
References Base::InterpreterSingleton::addModule(), and Base::Interpreter().
Referenced by PyMOD_INIT_FUNC().