FreeCAD: StartGui::StartLauncher Class Reference
StartGui::StartLauncher Class Reference
Public Member Functions
StartLauncher ()
void Launch ()
void EnsureLaunched ()
Detailed Description
Definition at line 69 of file AppStartGui.cpp.
Constructor & Destructor Documentation
StartLauncher()
StartGui::StartLauncher::StartLauncher () inline
Definition at line 72 of file AppStartGui.cpp.
References Launch().
Member Function Documentation
EnsureLaunched()
void StartGui::StartLauncher::EnsureLaunched () inline
Definition at line 93 of file AppStartGui.cpp.
References Gui::getMainWindow(), Launch(), and NavigationIndicatorGui::mw.
Referenced by Launch().
Launch()
void StartGui::StartLauncher::Launch () inline
Definition at line 80 of file AppStartGui.cpp.
References Gui::Application::commandManager(), EnsureLaunched(), App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), Gui::Application::Instance, and Gui::CommandManager::runCommandByName().
Referenced by EnsureLaunched(), and StartLauncher().
The documentation for this class was generated from the following file:
AppStartGui.cpp