FreeCAD: PartGui::FilletRadiusModel Class Reference
PartGui::FilletRadiusModel Class Reference
#include <DlgFilletEdges.h>
Signals
void toggleCheckState (const QModelIndex &)
Public Member Functions
FilletRadiusModel (QObject *parent=nullptr)
Qt::ItemFlags flags (const QModelIndex &index) const override
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override
QVariant data (const QModelIndex &, int role=Qt::DisplayRole) const override
void updateCheckStates ()
Detailed Description
Definition at line 65 of file DlgFilletEdges.h.
Constructor & Destructor Documentation
FilletRadiusModel()
FilletRadiusModel::FilletRadiusModel (QObject * parent = nullptr) explicit
Definition at line 126 of file DlgFilletEdges.cpp.
Member Function Documentation
data()
QVariant FilletRadiusModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 153 of file DlgFilletEdges.cpp.
References Base::Quantity::getUserString(), and Path.Post.scripts.refactored_centroid_post::str.
flags()
Qt::ItemFlags FilletRadiusModel::flags (const QModelIndex & index) const override
Definition at line 136 of file DlgFilletEdges.cpp.
setData()
bool FilletRadiusModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) override
Definition at line 144 of file DlgFilletEdges.cpp.
References toggleCheckState().
toggleCheckState
void PartGui::FilletRadiusModel::toggleCheckState (const QModelIndex &) signal
Referenced by PartGui::DlgFilletEdges::DlgFilletEdges(), and setData().
updateCheckStates()
void FilletRadiusModel::updateCheckStates ()
Definition at line 130 of file DlgFilletEdges.cpp.
The documentation for this class was generated from the following files:
DlgFilletEdges.h
DlgFilletEdges.cpp