FreeCAD: Sandbox::PythonBaseClass Class Reference
Sandbox::PythonBaseClass Class Reference
Public Member Functions
PythonBaseClass (Py::PythonClassInstance *self, Py::Tuple &args, Py::Dict &kwds)
virtual ~PythonBaseClass ()
Py::Object PythonBaseClass_func_noargs (void)
Py::Object PythonBaseClass_func_varargs (const Py::Tuple &args)
Py::Object PythonBaseClass_func_keyword (const Py::Tuple &args, const Py::Dict &kwds)
Py::Object PythonBaseClass_func_noargs_raise_exception (void)
Py::Object getattro (const Py::String &name_)
int setattro (const Py::String &name_, const Py::Object &value)
virtual PyCxx_ssize_t sequence_length ()
virtual Py::Object sequence_concat (const Py::Object &)
virtual Py::Object sequence_repeat (Py_ssize_t)
virtual Py::Object sequence_item (Py_ssize_t i)
virtual Py::Object sequence_slice (Py_ssize_t, Py_ssize_t)
virtual int sequence_ass_item (Py_ssize_t i, const Py::Object &o)
virtual int sequence_ass_slice (Py_ssize_t, Py_ssize_t, const Py::Object &)
Static Public Member Functions
static void init_type (void)
Public Attributes
Py::String m_value
std::vector< Py::Object > m_array
Detailed Description
Definition at line 60 of file AppSandbox.cpp.
Constructor & Destructor Documentation
PythonBaseClass()
Sandbox::PythonBaseClass::PythonBaseClass (Py::PythonClassInstance * self, Py::Tuple & args, Py::Dict & kwds) inline
Definition at line 83 of file AppSandbox.cpp.
References m_value.
~PythonBaseClass()
virtual Sandbox::PythonBaseClass::~PythonBaseClass () inline virtual
Definition at line 100 of file AppSandbox.cpp.
References toolbit-attributes::args, SplineSurface::i, and femtools.tokrules::names.
Member Function Documentation
getattro()
Py::Object Sandbox::PythonBaseClass::getattro (const Py::String & name_) inline
Definition at line 161 of file AppSandbox.cpp.
init_type()
static void Sandbox::PythonBaseClass::init_type (void) inline static
Definition at line 105 of file AppSandbox.cpp.
References SplineSurface::i, femtools.tokrules::names, and src.Mod.Test.testmakeWireString::String.
Referenced by sequence_repeat().
PythonBaseClass_func_keyword()
Py::Object Sandbox::PythonBaseClass::PythonBaseClass_func_keyword (const Py::Tuple & args, const Py::Dict & kwds) inline
Definition at line 139 of file AppSandbox.cpp.
References m_value.
PythonBaseClass_func_noargs()
Py::Object Sandbox::PythonBaseClass::PythonBaseClass_func_noargs (void) inline
Definition at line 124 of file AppSandbox.cpp.
References m_value.
PythonBaseClass_func_noargs_raise_exception()
Py::Object Sandbox::PythonBaseClass::PythonBaseClass_func_noargs_raise_exception (void) inline
Definition at line 153 of file AppSandbox.cpp.
PythonBaseClass_func_varargs()
Py::Object Sandbox::PythonBaseClass::PythonBaseClass_func_varargs (const Py::Tuple & args) inline
Definition at line 132 of file AppSandbox.cpp.
sequence_ass_item()
virtual int Sandbox::PythonBaseClass::sequence_ass_item (Py_ssize_t i, const Py::Object & o) inline virtual
Definition at line 216 of file AppSandbox.cpp.
sequence_ass_slice()
virtual int Sandbox::PythonBaseClass::sequence_ass_slice (Py_ssize_t , Py_ssize_t , const Py::Object &) inline virtual
Definition at line 224 of file AppSandbox.cpp.
sequence_concat()
virtual Py::Object Sandbox::PythonBaseClass::sequence_concat (const Py::Object &) inline virtual
Definition at line 194 of file AppSandbox.cpp.
sequence_item()
virtual Py::Object Sandbox::PythonBaseClass::sequence_item (Py_ssize_t i) inline virtual
Definition at line 204 of file AppSandbox.cpp.
sequence_length()
virtual PyCxx_ssize_t Sandbox::PythonBaseClass::sequence_length () inline virtual
Definition at line 189 of file AppSandbox.cpp.
sequence_repeat()
virtual Py::Object Sandbox::PythonBaseClass::sequence_repeat (Py_ssize_t) inline virtual
Definition at line 199 of file AppSandbox.cpp.
References Sandbox::DocumentProtectorPy::init_type(), and init_type().
sequence_slice()
virtual Py::Object Sandbox::PythonBaseClass::sequence_slice (Py_ssize_t , Py_ssize_t) inline virtual
Definition at line 211 of file AppSandbox.cpp.
setattro()
int Sandbox::PythonBaseClass::setattro (const Py::String & name_, const Py::Object & value) inline
Definition at line 175 of file AppSandbox.cpp.
Member Data Documentation
m_array
std::vector<Py::Object> Sandbox::PythonBaseClass::m_array
Definition at line 231 of file AppSandbox.cpp.
m_value
Py::String Sandbox::PythonBaseClass::m_value
Definition at line 230 of file AppSandbox.cpp.
Referenced by PythonBaseClass(), PythonBaseClass_func_keyword(), and PythonBaseClass_func_noargs().
The documentation for this class was generated from the following file:
AppSandbox.cpp