FreeCAD: SketcherGui::EditModeGeometryCoinManager Class Reference
SketcherGui::EditModeGeometryCoinManager Class Reference
Class for managing the Edit mode coin nodes of ViewProviderSketch relating to geometry.
#include <EditModeGeometryCoinManager.h>
Public Member Functions
EditModeGeometryCoinManager (ViewProviderSketch &vp, DrawingParameters &drawingParams, GeometryLayerParameters &geometryLayerParams, AnalysisResults &analysisResultStruct, EditModeScenegraphNodes &editModeScenegraph, CoinMapping &coinMap)
~EditModeGeometryCoinManager ()
void processGeometry (const GeoListFacade &geolistfacade)
void updateGeometryColor (const GeoListFacade &geolistfacade, bool issketchinvalid)
void updateGeometryLayersConfiguration ()
coin nodes creation
void createEditModeInventorNodes ()
Detailed Description
Class for managing the Edit mode coin nodes of ViewProviderSketch relating to geometry.
EditModeGeometryCoinManager is a helper of EditModeCoinManager specialised in geometry management.
Three main functions are delegated to it:
Creation of Edit mode coin nodes to handle Geometry representation.
Converting Sketcher geometry into Coin information.
Updating the Geometry colors.
Internally, EditModeGeometryCoinManager uses yet another class for geometry conversion, GeometryCoinConverter.
Definition at line 85 of file EditModeGeometryCoinManager.h.
Constructor & Destructor Documentation
EditModeGeometryCoinManager()
EditModeGeometryCoinManager::EditModeGeometryCoinManager (ViewProviderSketch & vp, DrawingParameters & drawingParams, GeometryLayerParameters & geometryLayerParams, AnalysisResults & analysisResultStruct, EditModeScenegraphNodes & editModeScenegraph, CoinMapping & coinMap) explicit
Definition at line 55 of file EditModeGeometryCoinManager.cpp.
~EditModeGeometryCoinManager()
EditModeGeometryCoinManager::~EditModeGeometryCoinManager ()
Definition at line 70 of file EditModeGeometryCoinManager.cpp.
Member Function Documentation
createEditModeInventorNodes()
void EditModeGeometryCoinManager::createEditModeInventorNodes ()
Definition at line 543 of file EditModeGeometryCoinManager.cpp.
References App::PropertyListsT< T, ListT, ParentT >::getSize(), SketcherGui::GeometryLayerParameters::setCoinLayerCount(), and SketcherGui::ViewProviderSketch::VisualLayerList.
processGeometry()
void EditModeGeometryCoinManager::processGeometry (const GeoListFacade & geolistfacade)
Definition at line 73 of file EditModeGeometryCoinManager.cpp.
References KDL::abs(), SketcherGui::AnalysisResults::arcGeoIds, SketcherGui::AnalysisResults::boundingBoxMagnitudeOrder, SketcherGui::AnalysisResults::bsplineGeoIds, SketcherGui::AnalysisResults::combRepresentationScale, SketcherGui::EditModeGeometryCoinConverter::convert(), SketcherGui::EditModeScenegraphNodes::CurvesCoordinate, SketcherGui::EditModeScenegraphNodes::CurveSet, SketcherGui::EditModeScenegraphNodes::CurvesGroup, SketcherGui::EditModeScenegraphNodes::CurvesMaterials, SmSwitchboard::enable, KDL::exp(), SketcherGui::EditModeGeometryCoinConverter::getArcGeoIds(), SketcherGui::EditModeGeometryCoinConverter::getBoundingBoxMaxMagnitude(), SketcherGui::EditModeGeometryCoinConverter::getBSplineGeoIds(), SketcherGui::GeometryLayerParameters::getCoinLayerCount(), SketcherGui::EditModeGeometryCoinConverter::getCombRepresentationScale(), SketcherGui::GeometryLayerParameters::getSubLayerCount(), App::PropertyListsT< T, ListT, ParentT >::getValues(), RobotExample::l, KDL::log(), SketcherGui::EditModeScenegraphNodes::PointsCoordinate, SketcherGui::EditModeScenegraphNodes::PointsGroup, SketcherGui::EditModeScenegraphNodes::PointsMaterials, SketcherGui::EditModeScenegraphNodes::RootCrossSet, InitGui::t, and SketcherGui::ViewProviderSketch::VisualLayerList.
updateGeometryColor()
void EditModeGeometryCoinManager::updateGeometryColor (const GeoListFacade & geolistfacade, bool issketchinvalid)
Definition at line 124 of file EditModeGeometryCoinManager.cpp.
References Sketcher::Coincident, SketcherGui::DrawingParameters::ConstrIcoColor, SketcherGui::DrawingParameters::Construction, SketcherGui::DrawingParameters::CrossColorH, SketcherGui::DrawingParameters::CrossColorV, SketcherGui::DrawingParameters::CurveColor, SketcherGui::DrawingParameters::CurveDraftColor, SketcherGui::DrawingParameters::CurveExternalColor, SketcherGui::EditModeScenegraphNodes::CurvesCoordinate, SketcherGui::EditModeScenegraphNodes::CurveSet, SketcherGui::EditModeScenegraphNodes::CurvesMaterials, Sketcher::end, SketcherGui::DrawingParameters::ExternalGeometry, SketcherGui::MultiFieldId::fieldIndex, SketcherGui::DrawingParameters::FullyConstrainedColor, Sketcher::SolverGeometryExtension::FullyConstraint, SketcherGui::DrawingParameters::FullyConstraintConstructionElementColor, SketcherGui::DrawingParameters::FullyConstraintElementColor, SketcherGui::DrawingParameters::FullyConstraintInternalAlignmentColor, Base::BaseClass::getClassTypeId(), SketcherGui::GeometryLayerParameters::getCoinLayerCount(), SketcherGui::CoinMapping::getCurveGeoId(), Sketcher::GeoListModel< T >::getGeometryFacadeFromGeoId(), SketcherGui::CoinMapping::getIndexLayer(), SketcherGui::CoinMapping::getPointGeoId(), SketcherGui::CoinMapping::getPointPosId(), SketcherGui::GeometryLayerParameters::getSubLayerCount(), Sketcher::HAxis, SplineSurface::i, SketcherGui::DrawingParameters::InternalAlignedGeoColor, SketcherGui::MultiFieldId::Invalid, SketcherGui::DrawingParameters::InvalidSketchColor, SketcherGui::GeometryLayerParameters::isConstructionSubLayer(), Sketcher::GeometryFacade::isInternalAligned(), SketcherGui::GeometryLayerParameters::isInternalSubLayer(), RobotExample::l, SketcherGui::MultiFieldId::layerId, SketcherGui::DrawingParameters::midRenderingGeometry, Sketcher::none, SketcherGui::DrawingParameters::NormalGeometry, Sketcher::Perpendicular, updateLeaderLines::point, SketcherGui::EditModeScenegraphNodes::PointsCoordinate, SketcherGui::EditModeScenegraphNodes::PointsMaterials, SketcherGui::DrawingParameters::PreselectColor, SketcherGui::DrawingParameters::PreselectSelectedColor, SketcherGui::EditModeScenegraphNodes::RootCrossMaterials, SketcherGui::DrawingParameters::SelectColor, Sketcher::start, InitGui::t, Sketcher::Tangent, SketcherGui::DrawingParameters::topRenderingGeometry, Sketcher::VAxis, MovieTool::x, MovieTool::y, SketcherGui::DrawingParameters::zHighlight, SketcherGui::DrawingParameters::zHighLine, SketcherGui::DrawingParameters::zHighLines, SketcherGui::DrawingParameters::zHighPoints, SketcherGui::DrawingParameters::zLowLines, SketcherGui::DrawingParameters::zLowPoints, SketcherGui::DrawingParameters::zMidLines, SketcherGui::DrawingParameters::zMidPoints, and SketcherGui::DrawingParameters::zRootPoint.
updateGeometryLayersConfiguration()
void EditModeGeometryCoinManager::updateGeometryLayersConfiguration ()
Definition at line 523 of file EditModeGeometryCoinManager.cpp.
References App::PropertyListsT< T, ListT, ParentT >::getSize(), SketcherGui::GeometryLayerParameters::setCoinLayerCount(), and SketcherGui::ViewProviderSketch::VisualLayerList.
The documentation for this class was generated from the following files:
EditModeGeometryCoinManager.h
EditModeGeometryCoinManager.cpp