FreeCAD: XStr Class Reference
XStr Class Reference
#include <XMLTools.h>
Public Member Functions
XStr (const char *const toTranscode)
Constructors and Destructor.
~XStr ()
const XMLCh * unicodeForm () const
Getter method.
Detailed Description
Definition at line 150 of file XMLTools.h.
Constructor & Destructor Documentation
XStr()
XStr::XStr (const char *const toTranscode) inline explicit
Constructors and Destructor.
Definition at line 168 of file XMLTools.h.
~XStr()
XStr::~XStr () inline
Definition at line 172 of file XMLTools.h.
References XERCES_CPP_NAMESPACE_QUALIFIER.
Member Function Documentation
unicodeForm()
const XMLCh * XStr::unicodeForm () const inline
Getter method.
Definition at line 181 of file XMLTools.h.
Referenced by ParameterGrp::_SetAttribute(), App::ProjectFile::getInputFiles(), App::ProjectFile::getObjects(), App::ProjectFile::getObjectsOfType(), App::ProjectFile::getPropertyFiles(), App::ProjectFile::getTypeId(), ParameterManager::LoadDocument(), and Base::StdInputSource::StdInputSource().
The documentation for this class was generated from the following file:
XMLTools.h