FreeCAD: ifc2x3.ifcstructuralloadsingledisplacement Class Reference
ifc2x3.ifcstructuralloadsingledisplacement Class Reference
Public Member Functions
def __init__ (self, inherited0__name, displacementx, displacementy, displacementz, rotationaldisplacementrx, rotationaldisplacementry, rotationaldisplacementrz)
def displacementx ()
def displacementy ()
def displacementz ()
def rotationaldisplacementrx ()
def rotationaldisplacementry ()
def rotationaldisplacementrz ()
Public Member Functions inherited from ifc2x3.ifcstructuralloadstatic
def __init__ (self, inherited0__name)
Public Member Functions inherited from ifc2x3.ifcstructuralload
def name ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
displacementx
displacementy
displacementz
rotationaldisplacementrx
rotationaldisplacementry
rotationaldisplacementrz
Public Attributes inherited from ifc2x3.ifcstructuralload
name
Detailed Description
Entity ifcstructuralloadsingledisplacement definition.
:param displacementx
:type displacementx:ifclengthmeasure
:param displacementy
:type displacementy:ifclengthmeasure
:param displacementz
:type displacementz:ifclengthmeasure
:param rotationaldisplacementrx
:type rotationaldisplacementrx:ifcplaneanglemeasure
:param rotationaldisplacementry
:type rotationaldisplacementry:ifcplaneanglemeasure
:param rotationaldisplacementrz
:type rotationaldisplacementrz:ifcplaneanglemeasure
Definition at line 3923 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcstructuralloadsingledisplacement.__init__ (self, inherited0__name, displacementx, displacementy, displacementz, rotationaldisplacementrx, rotationaldisplacementry, rotationaldisplacementrz)
Definition at line 3944 of file ifc2x3.py.
Member Function Documentation
displacementx()
def ifc2x3.ifcstructuralloadsingledisplacement.displacementx ()
Definition at line 3954 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadsingledisplacement._displacementx, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadsingledisplacement.displacementx.
displacementy()
def ifc2x3.ifcstructuralloadsingledisplacement.displacementy ()
Definition at line 3968 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadsingledisplacement._displacementy, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadsingledisplacement.displacementy.
displacementz()
def ifc2x3.ifcstructuralloadsingledisplacement.displacementz ()
Definition at line 3982 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadsingledisplacement._displacementz, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadsingledisplacement.displacementz.
rotationaldisplacementrx()
def ifc2x3.ifcstructuralloadsingledisplacement.rotationaldisplacementrx ()
Definition at line 3996 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadsingledisplacement._rotationaldisplacementrx, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadsingledisplacement.rotationaldisplacementrx.
rotationaldisplacementry()
def ifc2x3.ifcstructuralloadsingledisplacement.rotationaldisplacementry ()
Definition at line 4010 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadsingledisplacement._rotationaldisplacementry, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadsingledisplacement.rotationaldisplacementry.
rotationaldisplacementrz()
def ifc2x3.ifcstructuralloadsingledisplacement.rotationaldisplacementrz ()
Definition at line 4024 of file ifc2x3.py.
References ifc2x3.ifcstructuralloadsingledisplacement._rotationaldisplacementrz, SCL.TypeChecker.check_type(), and ifc2x3.ifcstructuralloadsingledisplacement.rotationaldisplacementrz.
Member Data Documentation
displacementx
ifc2x3.ifcstructuralloadsingledisplacement.displacementx
Definition at line 3946 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadsingledisplacement.displacementx().
displacementy
ifc2x3.ifcstructuralloadsingledisplacement.displacementy
Definition at line 3947 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadsingledisplacement.displacementy().
displacementz
ifc2x3.ifcstructuralloadsingledisplacement.displacementz
Definition at line 3948 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadsingledisplacement.displacementz().
rotationaldisplacementrx
ifc2x3.ifcstructuralloadsingledisplacement.rotationaldisplacementrx
Definition at line 3949 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadsingledisplacement.rotationaldisplacementrx().
rotationaldisplacementry
ifc2x3.ifcstructuralloadsingledisplacement.rotationaldisplacementry
Definition at line 3950 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadsingledisplacement.rotationaldisplacementry().
rotationaldisplacementrz
ifc2x3.ifcstructuralloadsingledisplacement.rotationaldisplacementrz
Definition at line 3951 of file ifc2x3.py.
Referenced by ifc2x3.ifcstructuralloadsingledisplacement.rotationaldisplacementrz().
The documentation for this class was generated from the following file:
ifc2x3.py