FreeCAD: SelectionParser::StringFactory Class Reference
SelectionParser::StringFactory Class Reference
The StringFactory class Helper class to record the created strings used by the parser.
Public Member Functions
std::string * make (const std::string &str)
void clear ()
Static Public Member Functions
static StringFactory * instance ()
static std::string * New (const std::string &str)
Detailed Description
The StringFactory class Helper class to record the created strings used by the parser.
Definition at line 255 of file SelectionFilter.cpp.
Member Function Documentation
clear()
void SelectionParser::StringFactory::clear () inline
Definition at line 270 of file SelectionFilter.cpp.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__(), and Gui::SelectionFilter::parse().
instance()
static StringFactory* SelectionParser::StringFactory::instance () inline static
Definition at line 259 of file SelectionFilter.cpp.
Referenced by Gui::SelectionFilter::parse().
make()
std::string* SelectionParser::StringFactory::make (const std::string & str) inline
Definition at line 263 of file SelectionFilter.cpp.
References Path.Post.scripts.refactored_centroid_post::str.
New()
static std::string* SelectionParser::StringFactory::New (const std::string & str) inline static
Definition at line 267 of file SelectionFilter.cpp.
References Path.Post.scripts.refactored_centroid_post::str.
The documentation for this class was generated from the following file:
SelectionFilter.cpp