FreeCAD: Gui::OverlayManager::Private Class Reference
Gui::OverlayManager::Private Class Reference
Public Member Functions
Private (OverlayManager *host, QWidget *parent)
void refreshIcons ()
void interceptEvent (QWidget *, QEvent *)
void setMouseTransparent (bool enabled)
bool toggleOverlay (QDockWidget *dock, ToggleMode toggle, int dockPos=Qt::NoDockWidgetArea)
void refresh (QWidget *widget=nullptr, bool refreshStyle=false)
void save ()
void restore ()
void onTimer ()
void setOverlayMode (OverlayMode mode)
void onToggleDockWidget (QDockWidget *dock, int checked)
void onFocusChanged (QWidget *, QWidget *)
void setupTitleBar (QDockWidget *dock)
QWidget * createTitleBar (QWidget *parent)
void onAction (QAction *action)
void retranslate ()
void floatDockWidget (QDockWidget *dock)
void dragDockWidget (QPoint pos, QWidget *srcWidget, QPoint dragOffset, QSize dragSize, bool drop)
void raiseAll ()
void registerDockWidget (const QString &name, OverlayTabWidget *widget)
void unregisterDockWidget (const QString &name, OverlayTabWidget *widget)
void reload (OverlayManager::ReloadMode mode)
Public Attributes
QPointer< QWidget > lastIntercept
QTimer _timer
QTimer _reloadTimer
bool mouseTransparent = false
bool intercepting = false
std::unordered_map< QDockWidget *, OverlayInfo * > _overlayMap
OverlayInfo _left
OverlayInfo _right
OverlayInfo _top
OverlayInfo _bottom
std::array< OverlayInfo *, 4 > _overlayInfos
QCursor _cursor
QPoint _lastPos
QAction _actClose
QAction _actFloat
QAction _actOverlay
QList< QAction * > _actions
QPointer< QWidget > _trackingWidget
OverlayTabWidget * _trackingOverlay = nullptr
bool updateStyle = false
QTime wheelDelay
QPoint wheelPos
std::map< QString, OverlayTabWidget * > _dockWidgetNameMap
bool raising = false
OverlayManager::ReloadMode curReloadMode = OverlayManager::ReloadMode::ReloadPending
Detailed Description
Definition at line 305 of file OverlayManager.cpp.
Constructor & Destructor Documentation
Private()
Gui::OverlayManager::Private::Private (OverlayManager * host, QWidget * parent) inline
Definition at line 343 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::_bottom, Gui::OverlayManager::Private::_left, Gui::OverlayManager::Private::_right, and Gui::OverlayManager::Private::_top.
Member Function Documentation
createTitleBar()
QWidget* Gui::OverlayManager::Private::createTitleBar (QWidget * parent) inline
Definition at line 925 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::_actClose, Gui::OverlayManager::Private::_actFloat, Gui::OverlayManager::Private::_actions, Gui::OverlayManager::Private::_actOverlay, Init::parent, Gui::OverlayTabWidget::prepareTitleWidget(), and Gui::OverlayTitleBar::setTitleItem().
Referenced by Gui::OverlayManager::Private::setupTitleBar().
dragDockWidget()
void Gui::OverlayManager::Private::dragDockWidget (QPoint pos, QWidget * srcWidget, QPoint dragOffset, QSize dragSize, bool drop) inline
Definition at line 1003 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::_overlayInfos, Gui::OverlayManager::Private::_overlayMap, _Overlays, Gui::OverlayTabWidget::dockWidgetIndex(), Gui::OverlayTabWidget::getDockArea(), Gui::OverlayParams::getDockOverlayMinimumSize(), Gui::OverlayParams::getDockOverlayRevealDelay(), Gui::getMainWindow(), Gui::MainWindow::getMdiArea(), Gui::OverlayTabWidget::getSplitter(), SplineSurface::i, src.Mod.Test.testPathArray::o, Gui::OverlayTabWidget::onCurrentChanged(), Gui::OverlayTabWidget::onSplitterResize(), nativeifc.ifc_viewproviders::overlay(), RobotExample::pos, Gui::OverlayManager::Private::refresh(), toolbit-attributes::s, Gui::OverlayTabWidget::saveTabs(), Gui::OverlayManager::setFocusView(), Gui::OverlayTabWidget::setRevealTime(), Sketcher::Vertical, and src.Mod.PartDesign.fcgear.svggear::w.
floatDockWidget()
void Gui::OverlayManager::Private::floatDockWidget (QDockWidget * dock) inline
Definition at line 989 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::_overlayMap, and Gui::OverlayManager::setFocusView().
interceptEvent()
void Gui::OverlayManager::Private::interceptEvent (QWidget * widget, QEvent * ev)
Definition at line 1875 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::_trackingOverlay, Gui::OverlayManager::Private::lastIntercept, Init::parent, RobotExample::pos, Sketcher::Vertical, and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by Gui::OverlayManager::eventFilter().
onAction()
void Gui::OverlayManager::Private::onAction (QAction * action) inline
Definition at line 950 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::_actClose, Gui::OverlayManager::Private::_actFloat, Gui::OverlayManager::Private::_actOverlay, Gui::OverlayManager::Private::_overlayMap, Path.Post.scripts.dynapath_4060_post::action, Gui::getMainWindow(), Gui::OverlayManager::instance(), RobotExample::pos, Gui::OverlayManager::Private::refresh(), Gui::OverlayManager::setFocusView(), Gui::OverlayManager::setOverlayMode(), Gui::OverlayManager::ToggleActive, and src.Mod.PartDesign.fcgear.svggear::w.
onFocusChanged()
void Gui::OverlayManager::Private::onFocusChanged (QWidget * , QWidget *) inline
Definition at line 915 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::refresh().
onTimer()
void Gui::OverlayManager::Private::onTimer () inline
Definition at line 527 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::_bottom, Gui::OverlayManager::Private::_left, Gui::OverlayManager::Private::_overlayInfos, Gui::OverlayManager::Private::_right, Gui::OverlayManager::Private::_top, findTabWidget(), App::GetApplication(), Gui::OverlayParams::getDockOverlayCheckNaviCube(), ParameterGrp::GetInt(), Gui::getMainWindow(), Gui::MainWindow::getMdiArea(), NaviCube::getNaviCubeSize(), Gui::OverlayTabWidget::getOffset(), App::Application::GetParameterGroupByPath(), Gui::OverlayTabWidget::getRect(), Gui::OverlayTabWidget::getSizeDelta(), Gui::OverlayTabWidget::getState(), Path.Log::info(), KDL::max(), Gui::OverlayTabWidget::Normal, src.Mod.Test.testPathArray::o, RobotExample::pos, Gui::OverlayTabWidget::setOverlayMode(), Gui::OverlayTabWidget::setRect(), OverlayInfo::tabWidget, Gui::OverlayTabWidget::TransparencyChanged, Gui::OverlayTabWidget::TransparencyNotChanged, Gui::OverlayTabWidget::updateSplitterHandles(), Gui::OverlayManager::Private::updateStyle, and src.Mod.PartDesign.fcgear.svggear::w.
onToggleDockWidget()
void Gui::OverlayManager::Private::onToggleDockWidget (QDockWidget * dock, int checked) inline
Definition at line 820 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::_overlayMap, Gui::OverlayTabWidget::dockWidget(), Gui::OverlayTabWidget::dockWidgetIndex(), Gui::OverlayParams::getDockOverlayRevealDelay(), Gui::OverlayTabWidget::getSplitter(), SplineSurface::i, Gui::OverlayTabWidget::onCurrentChanged(), Gui::OverlayManager::Private::refresh(), Gui::OverlayTabWidget::saveTabs(), Gui::OverlayTabWidget::setCurrent(), and Gui::OverlayTabWidget::setRevealTime().
Referenced by Gui::OverlayManager::initDockWidget().
raiseAll()
void Gui::OverlayManager::Private::raiseAll () inline
Definition at line 1402 of file OverlayManager.cpp.
References _Overlays, and Gui::OverlayManager::Private::raising.
refresh()
void Gui::OverlayManager::Private::refresh (QWidget * widget = nullptr, bool refreshStyle = false) inline
Definition at line 489 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::_overlayInfos, Gui::OverlayManager::Private::_timer, findTabWidget(), Gui::OverlayParams::getDockOverlayDelay(), OverlayStyleSheet::instance(), src.Mod.Test.testPathArray::o, OverlayStyleSheet::update(), and Gui::OverlayManager::Private::updateStyle.
Referenced by Path.Tool.Gui.BitEdit.ToolBitEditor::accept(), Gui::OverlayManager::Private::dragDockWidget(), Gui::OverlayManager::initDockWidget(), Gui::OverlayManager::Private::onAction(), Gui::OverlayManager::Private::onFocusChanged(), Gui::OverlayManager::Private::onToggleDockWidget(), Gui::OverlayManager::Private::restore(), Gui::OverlayManager::Private::setMouseTransparent(), Gui::OverlayManager::Private::setOverlayMode(), Path.Tool.Gui.Controller.ToolControllerEditor::setupUi(), Path.Tool.Gui.BitEdit.ToolBitEditor::setupUI(), and Gui::OverlayManager::Private::toggleOverlay().
refreshIcons()
void Gui::OverlayManager::Private::refreshIcons () inline
Definition at line 403 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::_actClose, Gui::OverlayManager::Private::_actFloat, Gui::OverlayManager::Private::_actOverlay, _Overlays, and Gui::BitmapFactory().
Referenced by Gui::OverlayManager::refreshIcons().
registerDockWidget()
void Gui::OverlayManager::Private::registerDockWidget (const QString & name, OverlayTabWidget * widget) inline
Definition at line 1413 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::_dockWidgetNameMap.
reload()
void Gui::OverlayManager::Private::reload (OverlayManager::ReloadMode mode) inline
Definition at line 1424 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::_reloadTimer, Gui::OverlayManager::Private::curReloadMode, FC_LOG, Gui::OverlayManager::ReloadPause, Gui::OverlayManager::ReloadPending, and Gui::OverlayManager::ReloadResume.
Referenced by Gui::OverlayManager::reload().
restore()
void Gui::OverlayManager::Private::restore () inline
Definition at line 518 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::_bottom, Gui::OverlayManager::Private::_left, Gui::OverlayManager::Private::_right, Gui::OverlayManager::Private::_top, Gui::OverlayManager::Private::refresh(), and OverlayInfo::restore().
Referenced by src.Mod.Show.mTempoVis.TempoVis::__del__().
retranslate()
void Gui::OverlayManager::Private::retranslate () inline
Definition at line 982 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::_actClose, Gui::OverlayManager::Private::_actFloat, and Gui::OverlayManager::Private::_actOverlay.
Referenced by Gui::OverlayManager::retranslate().
save()
void Gui::OverlayManager::Private::save () inline
Definition at line 510 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::_bottom, Gui::OverlayManager::Private::_left, Gui::OverlayManager::Private::_right, Gui::OverlayManager::Private::_top, and OverlayInfo::save().
Referenced by src.Mod.Show.mTempoVis.TempoVis::modify(), src.Mod.Show.mTempoVis.TempoVis::modifyVPProperty(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::onSaveStyle(), src.Mod.Show.mTempoVis.TempoVis::saveCamera(), and nativeifc.ifc_viewproviders.ifc_vp_document::setupContextMenu().
setMouseTransparent()
void Gui::OverlayManager::Private::setMouseTransparent (bool enabled) inline
Definition at line 417 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::_cursor, _Overlays, Gui::OverlayManager::Private::mouseTransparent, and Gui::OverlayManager::Private::refresh().
Referenced by Gui::OverlayManager::eventFilter().
setOverlayMode()
void Gui::OverlayManager::Private::setOverlayMode (OverlayMode mode) inline
Definition at line 700 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::_overlayInfos, a, SCL.SimpleDataTypes::b, Gui::OverlayManager::DisableActive, Gui::OverlayManager::DisableAll, Gui::OverlayManager::EnableActive, Gui::OverlayManager::EnableAll, Gui::getMainWindow(), Gui::OverlayTabWidget::Hidden, test::m, src.Mod.Test.testPathArray::o, RobotExample::pos, Gui::OverlayManager::Private::refresh(), Set, Gui::OverlayTabWidget::Showing, Toggle, Gui::OverlayManager::ToggleActive, Gui::OverlayManager::ToggleAll, Gui::OverlayManager::ToggleBottom, Gui::OverlayManager::ToggleLeft, Gui::OverlayManager::Private::toggleOverlay(), Gui::OverlayManager::ToggleRight, Gui::OverlayManager::ToggleTop, Gui::OverlayManager::ToggleTransparent, Gui::OverlayManager::ToggleTransparentAll, Transparent, Gui::OverlayManager::TransparentAll, Gui::OverlayManager::TransparentNone, Unset, and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by Gui::OverlayManager::setOverlayMode().
setupTitleBar()
void Gui::OverlayManager::Private::setupTitleBar (QDockWidget * dock) inline
Definition at line 919 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::createTitleBar().
Referenced by Gui::OverlayManager::setupDockWidget().
toggleOverlay()
bool Gui::OverlayManager::Private::toggleOverlay (QDockWidget * dock, ToggleMode toggle, int dockPos = Qt::NoDockWidgetArea) inline
Definition at line 434 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::_bottom, Gui::OverlayManager::Private::_left, Gui::OverlayManager::Private::_overlayMap, Gui::OverlayManager::Private::_right, Gui::OverlayManager::Private::_top, Check, Gui::getMainWindow(), src.Mod.Test.testPathArray::o, Gui::OverlayManager::Private::refresh(), Toggle, Transparent, and Unset.
Referenced by Gui::OverlayManager::Private::setOverlayMode(), and Gui::OverlayManager::unsetupDockWidget().
unregisterDockWidget()
void Gui::OverlayManager::Private::unregisterDockWidget (const QString & name, OverlayTabWidget * widget) inline
Definition at line 1418 of file OverlayManager.cpp.
References Gui::OverlayManager::Private::_dockWidgetNameMap.
Member Data Documentation
_actClose
QAction Gui::OverlayManager::Private::_actClose
Definition at line 325 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::Private::createTitleBar(), Gui::OverlayManager::Private::onAction(), Gui::OverlayManager::Private::refreshIcons(), and Gui::OverlayManager::Private::retranslate().
_actFloat
QAction Gui::OverlayManager::Private::_actFloat
Definition at line 326 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::Private::createTitleBar(), Gui::OverlayManager::Private::onAction(), Gui::OverlayManager::Private::refreshIcons(), and Gui::OverlayManager::Private::retranslate().
_actions
QList<QAction*> Gui::OverlayManager::Private::_actions
Definition at line 328 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::Private::createTitleBar().
_actOverlay
QAction Gui::OverlayManager::Private::_actOverlay
Definition at line 327 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::Private::createTitleBar(), Gui::OverlayManager::Private::onAction(), Gui::OverlayManager::Private::refreshIcons(), and Gui::OverlayManager::Private::retranslate().
_bottom
OverlayInfo Gui::OverlayManager::Private::_bottom
Definition at line 319 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::Private::onTimer(), Gui::OverlayManager::Private::Private(), Gui::OverlayManager::Private::restore(), Gui::OverlayManager::Private::save(), and Gui::OverlayManager::Private::toggleOverlay().
_cursor
QCursor Gui::OverlayManager::Private::_cursor
Definition at line 321 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::Private::setMouseTransparent().
_dockWidgetNameMap
std::map<QString, OverlayTabWidget*> Gui::OverlayManager::Private::_dockWidgetNameMap
Definition at line 337 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::initDockWidget(), Gui::OverlayManager::Private::registerDockWidget(), and Gui::OverlayManager::Private::unregisterDockWidget().
_lastPos
QPoint Gui::OverlayManager::Private::_lastPos
Definition at line 323 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::eventFilter().
_left
OverlayInfo Gui::OverlayManager::Private::_left
Definition at line 316 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::Private::onTimer(), Gui::OverlayManager::Private::Private(), Gui::OverlayManager::Private::restore(), Gui::OverlayManager::Private::save(), and Gui::OverlayManager::Private::toggleOverlay().
_overlayInfos
std::array<OverlayInfo*,4> Gui::OverlayManager::Private::_overlayInfos
Definition at line 320 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::Private::dragDockWidget(), Gui::OverlayManager::initDockWidget(), Gui::OverlayManager::Private::onTimer(), Gui::OverlayManager::Private::refresh(), and Gui::OverlayManager::Private::setOverlayMode().
_overlayMap
std::unordered_map<QDockWidget*, OverlayInfo*> Gui::OverlayManager::Private::_overlayMap
Definition at line 315 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::Private::dragDockWidget(), Gui::OverlayManager::Private::floatDockWidget(), Gui::OverlayManager::Private::onAction(), Gui::OverlayManager::Private::onToggleDockWidget(), and Gui::OverlayManager::Private::toggleOverlay().
_reloadTimer
QTimer Gui::OverlayManager::Private::_reloadTimer
Definition at line 310 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::Private::reload().
_right
OverlayInfo Gui::OverlayManager::Private::_right
Definition at line 317 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::Private::onTimer(), Gui::OverlayManager::Private::Private(), Gui::OverlayManager::Private::restore(), Gui::OverlayManager::Private::save(), and Gui::OverlayManager::Private::toggleOverlay().
_timer
QTimer Gui::OverlayManager::Private::_timer
Definition at line 309 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::Private::refresh(), and femsolver.solver_taskpanel.ControlTaskPanel::updateMachine().
_top
OverlayInfo Gui::OverlayManager::Private::_top
Definition at line 318 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::Private::onTimer(), Gui::OverlayManager::Private::Private(), Gui::OverlayManager::Private::restore(), Gui::OverlayManager::Private::save(), and Gui::OverlayManager::Private::toggleOverlay().
_trackingOverlay
OverlayTabWidget* Gui::OverlayManager::Private::_trackingOverlay = nullptr
Definition at line 331 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::eventFilter(), and Gui::OverlayManager::Private::interceptEvent().
_trackingWidget
QPointer<QWidget> Gui::OverlayManager::Private::_trackingWidget
Definition at line 330 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::eventFilter().
curReloadMode
OverlayManager::ReloadMode Gui::OverlayManager::Private::curReloadMode = OverlayManager::ReloadMode::ReloadPending
Definition at line 341 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::Private::reload().
intercepting
bool Gui::OverlayManager::Private::intercepting = false
Definition at line 313 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::eventFilter().
lastIntercept
QPointer<QWidget> Gui::OverlayManager::Private::lastIntercept
Definition at line 308 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::eventFilter(), and Gui::OverlayManager::Private::interceptEvent().
mouseTransparent
bool Gui::OverlayManager::Private::mouseTransparent = false
Definition at line 312 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::eventFilter(), and Gui::OverlayManager::Private::setMouseTransparent().
raising
bool Gui::OverlayManager::Private::raising = false
Definition at line 339 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::eventFilter(), and Gui::OverlayManager::Private::raiseAll().
updateStyle
bool Gui::OverlayManager::Private::updateStyle = false
Definition at line 333 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::Private::onTimer(), and Gui::OverlayManager::Private::refresh().
wheelDelay
QTime Gui::OverlayManager::Private::wheelDelay
Definition at line 334 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::eventFilter().
wheelPos
QPoint Gui::OverlayManager::Private::wheelPos
Definition at line 335 of file OverlayManager.cpp.
Referenced by Gui::OverlayManager::eventFilter().
The documentation for this class was generated from the following file:
OverlayManager.cpp