FreeCAD: Path.GuiInit Namespace Reference
Path.GuiInit Namespace Reference
Functions
def Startup ()
Variables
LOGLEVEL
Processed
Function Documentation
Startup()
def Path.GuiInit.Startup ()
Definition at line 37 of file GuiInit.py.
References Path.Log.debug(), App::ExpressionParser.parse(), and src.Mod.AddonManager.addonmanager_freecad_interface.Version.
Referenced by InitGui.CAMWorkbench.Initialize().
Variable Documentation
LOGLEVEL
Path.GuiInit.LOGLEVEL
Definition at line 26 of file GuiInit.py.
Processed
Path.GuiInit.Processed
Definition at line 34 of file GuiInit.py.