FreeCAD: AppSketcherGui.cpp File Reference
AppSketcherGui.cpp File Reference
#include "PreCompiled.h"
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/PyObjectBase.h>
#include <Gui/Application.h>
#include <Gui/BitmapFactory.h>
#include <Gui/Language/Translator.h>
#include <Gui/WidgetFactory.h>
#include "PropertyConstraintListItem.h"
#include "SketcherSettings.h"
#include "SoZoomTranslation.h"
#include "ViewProviderPython.h"
#include "ViewProviderSketch.h"
#include "ViewProviderSketchGeometryExtension.h"
#include "ViewProviderSketchGeometryExtensionPy.h"
#include "Workbench.h"
Classes
class SketcherGui::Module
Namespaces
SketcherGui
Functions
void CreateSketcherCommands ()
void CreateSketcherCommandsCreateGeo ()
void CreateSketcherCommandsConstraints ()
void CreateSketcherCommandsConstraintAccel ()
void CreateSketcherCommandsAlterGeo ()
void CreateSketcherCommandsBSpline ()
void CreateSketcherCommandsOverlay ()
void CreateSketcherCommandsVirtualSpace ()
void loadSketcherResource ()
PyObject * SketcherGui::initModule ()
PyMOD_INIT_FUNC (SketcherGui)
Function Documentation
CreateSketcherCommands()
void CreateSketcherCommands ()
Definition at line 1862 of file Mod/Sketcher/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
CreateSketcherCommandsAlterGeo()
void CreateSketcherCommandsAlterGeo ()
Definition at line 251 of file CommandAlterGeometry.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
CreateSketcherCommandsBSpline()
void CreateSketcherCommandsBSpline ()
Definition at line 1107 of file CommandSketcherBSpline.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
CreateSketcherCommandsConstraintAccel()
void CreateSketcherCommandsConstraintAccel ()
Definition at line 2489 of file CommandSketcherTools.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
CreateSketcherCommandsConstraints()
void CreateSketcherCommandsConstraints ()
Definition at line 10205 of file CommandConstraints.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
CreateSketcherCommandsCreateGeo()
void CreateSketcherCommandsCreateGeo ()
Definition at line 2124 of file CommandCreateGeo.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
CreateSketcherCommandsOverlay()
void CreateSketcherCommandsOverlay ()
Definition at line 385 of file CommandSketcherOverlay.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
CreateSketcherCommandsVirtualSpace()
void CreateSketcherCommandsVirtualSpace ()
Definition at line 205 of file CommandSketcherVirtualSpace.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
loadSketcherResource()
void loadSketcherResource ()
Definition at line 53 of file AppSketcherGui.cpp.
References Gui::Translator::instance(), and Gui::Translator::refresh().
Referenced by PyMOD_INIT_FUNC().
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (SketcherGui)
Definition at line 86 of file AppSketcherGui.cpp.
References Gui::BitmapFactoryInst::addPath(), Base::InterpreterSingleton::addType(), Gui::BitmapFactory(), Base::Console(), CreateSketcherCommands(), CreateSketcherCommandsAlterGeo(), CreateSketcherCommandsBSpline(), CreateSketcherCommandsConstraintAccel(), CreateSketcherCommandsConstraints(), CreateSketcherCommandsCreateGeo(), CreateSketcherCommandsOverlay(), CreateSketcherCommandsVirtualSpace(), SCL.SimpleDataTypes::e, SIM::Coin3D::Quarter::Quarter::init(), Gui::PropertyEditor::PropertyItem::init(), Base::BaseClass::init(), App::Extension::init(), SketcherGui::SoZoomTranslation::initClass(), SketcherGui::initModule(), Gui::Application::Instance, Base::Interpreter(), loadSketcherResource(), Base::ConsoleSingleton::Log(), PyMOD_Return, Arch::QT_TRANSLATE_NOOP, and Base::InterpreterSingleton::runString().