FreeCAD: Base::IndexedFaceSetItem Class Reference
Base::IndexedFaceSetItem Class Reference
The IndexedFaceSetItem class supports the SoIndexedFaceSet node.
#include <Builder3D.h>
Public Member Functions
IndexedFaceSetItem (std::vector< int >)
void write (InventorOutput &out) const override
Public Member Functions inherited from Base::NodeItem
virtual ~NodeItem ()=default
Additional Inherited Members
Protected Member Functions inherited from Base::NodeItem
NodeItem ()=default
NodeItem (const NodeItem &)=default
NodeItem (NodeItem &&)=default
NodeItem & operator= (const NodeItem &)=default
NodeItem & operator= (NodeItem &&)=default
Detailed Description
The IndexedFaceSetItem class supports the SoIndexedFaceSet node.
Definition at line 542 of file Builder3D.h.
Constructor & Destructor Documentation
IndexedFaceSetItem()
IndexedFaceSetItem::IndexedFaceSetItem (std::vector< int > indices) explicit
Definition at line 771 of file Builder3D.cpp.
Member Function Documentation
write()
void IndexedFaceSetItem::write (InventorOutput & out) const override virtual
Implements Base::NodeItem.
Definition at line 775 of file Builder3D.cpp.
References Base::InventorOutput::decreaseIndent(), Base::InventorOutput::increaseIndent(), Base::InventorOutput::write(), and Base::InventorFieldWriter::write().
The documentation for this class was generated from the following files:
Builder3D.h
Builder3D.cpp