FreeCAD: Mesh::MeshObject::const_facet_iterator Class Reference
Mesh::MeshObject::const_facet_iterator Class Reference
#include <Mesh.h>
Public Member Functions
const_facet_iterator (const MeshObject *, FacetIndex index)
const_facet_iterator (const const_facet_iterator &fi)
const_facet_iterator (const_facet_iterator &&fi)
~const_facet_iterator ()
const_facet_iterator & operator= (const const_facet_iterator &fi)
const_facet_iterator & operator= (const_facet_iterator &&fi)
Mesh::Facet & operator* ()
Mesh::Facet * operator-> ()
bool operator== (const const_facet_iterator &fi) const
bool operator!= (const const_facet_iterator &fi) const
const_facet_iterator & operator++ ()
const_facet_iterator & operator-- ()
Detailed Description
Definition at line 404 of file Mesh.h.
Constructor & Destructor Documentation
const_facet_iterator() [1/3]
MeshObject::const_facet_iterator::const_facet_iterator (const MeshObject * mesh, FacetIndex index)
Definition at line 2199 of file Mesh.cpp.
References Mesh::Facet::Mesh, MeshCore::MeshFacetIterator::Set(), and MeshCore::MeshFacetIterator::Transform().
const_facet_iterator() [2/3]
MeshObject::const_facet_iterator::const_facet_iterator (const const_facet_iterator & fi) default
const_facet_iterator() [3/3]
MeshObject::const_facet_iterator::const_facet_iterator (const_facet_iterator && fi) default
~const_facet_iterator()
MeshObject::const_facet_iterator::~const_facet_iterator () default
Member Function Documentation
operator!=()
bool MeshObject::const_facet_iterator::operator!= (const const_facet_iterator & fi) const
Definition at line 2250 of file Mesh.cpp.
References KDL::operator==().
operator*()
Facet & MeshObject::const_facet_iterator::operator* ()
Definition at line 2233 of file Mesh.cpp.
operator++()
MeshObject::const_facet_iterator & MeshObject::const_facet_iterator::operator++ ()
Definition at line 2255 of file Mesh.cpp.
operator--()
MeshObject::const_facet_iterator & MeshObject::const_facet_iterator::operator-- ()
Definition at line 2261 of file Mesh.cpp.
operator->()
Facet * MeshObject::const_facet_iterator::operator-> ()
Definition at line 2239 of file Mesh.cpp.
operator=() [1/2]
MeshObject::const_facet_iterator & MeshObject::const_facet_iterator::operator= (const const_facet_iterator & fi) default
operator=() [2/2]
MeshObject::const_facet_iterator & MeshObject::const_facet_iterator::operator= (const_facet_iterator && fi) default
operator==()
bool MeshObject::const_facet_iterator::operator== (const const_facet_iterator & fi) const
Definition at line 2245 of file Mesh.cpp.
The documentation for this class was generated from the following files:
Mesh.h
Mesh.cpp