FreeCAD: MeshCore::CylinderSurfaceFit Class Reference
MeshCore::CylinderSurfaceFit Class Reference
#include <Segmentation.h>
Public Member Functions
CylinderSurfaceFit ()
CylinderSurfaceFit (const Base::Vector3f &b, const Base::Vector3f &a, float r)
CylinderSurfaceFit::CylinderSurfaceFit Set a predefined cylinder. Internal cylinder fits are not done, then.
~CylinderSurfaceFit () override
CylinderSurfaceFit (const CylinderSurfaceFit &)=delete
CylinderSurfaceFit (CylinderSurfaceFit &&)=delete
CylinderSurfaceFit & operator= (const CylinderSurfaceFit &)=delete
CylinderSurfaceFit & operator= (CylinderSurfaceFit &&)=delete
const char * GetType () const override
void Initialize (const MeshGeomFacet &) override
bool TestTriangle (const MeshGeomFacet &) const override
void AddTriangle (const MeshGeomFacet &) override
bool Done () const override
float Fit () override
float GetDistanceToSurface (const Base::Vector3f &) const override
std::vector< float > Parameters () const override
Public Member Functions inherited from MeshCore::AbstractSurfaceFit
AbstractSurfaceFit ()=default
virtual ~AbstractSurfaceFit ()=default
AbstractSurfaceFit (const AbstractSurfaceFit &)=delete
AbstractSurfaceFit (AbstractSurfaceFit &&)=delete
AbstractSurfaceFit & operator= (const AbstractSurfaceFit &)=delete
AbstractSurfaceFit & operator= (AbstractSurfaceFit &&)=delete
Detailed Description
Definition at line 188 of file Mesh/App/Core/Segmentation.h.
Constructor & Destructor Documentation
CylinderSurfaceFit() [1/4]
CylinderSurfaceFit::CylinderSurfaceFit ()
Definition at line 203 of file Mesh/App/Core/Segmentation.cpp.
References Base::Vector3< float_type >::Set().
CylinderSurfaceFit() [2/4]
CylinderSurfaceFit::CylinderSurfaceFit (const Base::Vector3f & b, const Base::Vector3f & a, float r)
CylinderSurfaceFit::CylinderSurfaceFit Set a predefined cylinder. Internal cylinder fits are not done, then.
Definition at line 214 of file Mesh/App/Core/Segmentation.cpp.
~CylinderSurfaceFit()
CylinderSurfaceFit::~CylinderSurfaceFit () override
Definition at line 221 of file Mesh/App/Core/Segmentation.cpp.
CylinderSurfaceFit() [3/4]
MeshCore::CylinderSurfaceFit::CylinderSurfaceFit (const CylinderSurfaceFit &) delete
CylinderSurfaceFit() [4/4]
MeshCore::CylinderSurfaceFit::CylinderSurfaceFit (CylinderSurfaceFit &&) delete
Member Function Documentation
AddTriangle()
void CylinderSurfaceFit::AddTriangle (const MeshGeomFacet & tria) override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 236 of file Mesh/App/Core/Segmentation.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, and MeshCore::Approximation::AddPoint().
Done()
bool CylinderSurfaceFit::Done () const override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 253 of file Mesh/App/Core/Segmentation.cpp.
References MeshCore::Approximation::Done().
Fit()
float CylinderSurfaceFit::Fit () override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 262 of file Mesh/App/Core/Segmentation.cpp.
References MeshCore::CylinderFit::Fit(), FLOAT_MAX, MeshCore::CylinderFit::GetAxis(), MeshCore::CylinderFit::GetBase(), and MeshCore::CylinderFit::GetRadius().
GetDistanceToSurface()
float CylinderSurfaceFit::GetDistanceToSurface (const Base::Vector3f & pnt) const override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 277 of file Mesh/App/Core/Segmentation.cpp.
References DraftVecUtils::dist(), Base::Vector3< float_type >::DistanceToLine(), and MeshCore::Approximation::Done().
GetType()
const char* MeshCore::CylinderSurfaceFit::GetType () const inline override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 200 of file Mesh/App/Core/Segmentation.h.
References SCL.SimpleDataTypes::c.
Initialize()
void CylinderSurfaceFit::Initialize (const MeshGeomFacet & tria) override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 226 of file Mesh/App/Core/Segmentation.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, MeshCore::Approximation::AddPoint(), and MeshCore::Approximation::Clear().
operator=() [1/2]
CylinderSurfaceFit& MeshCore::CylinderSurfaceFit::operator= (const CylinderSurfaceFit &) delete
operator=() [2/2]
CylinderSurfaceFit& MeshCore::CylinderSurfaceFit::operator= (CylinderSurfaceFit &&) delete
Parameters()
std::vector< float > CylinderSurfaceFit::Parameters () const override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 287 of file Mesh/App/Core/Segmentation.cpp.
References SCL.SimpleDataTypes::c, MeshCore::CylinderFit::GetAxis(), MeshCore::CylinderFit::GetBase(), MeshCore::CylinderFit::GetRadius(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
TestTriangle()
bool CylinderSurfaceFit::TestTriangle (const MeshGeomFacet & tria) const override virtual
Implements MeshCore::AbstractSurfaceFit.
Definition at line 245 of file Mesh/App/Core/Segmentation.cpp.
References dot(), Base::Vector3< float_type >::Dot(), and MeshCore::MeshGeomFacet::GetNormal().
The documentation for this class was generated from the following files:
Mesh/App/Core/Segmentation.h
Mesh/App/Core/Segmentation.cpp