FreeCAD: Gui::LinkView::SubInfo Class Reference
Gui::LinkView::SubInfo Class Reference
Public Member Functions
SubInfo (LinkView &handle)
~SubInfo () override
void onLinkedIconChange (LinkInfoPtr) override
void unlink (LinkInfoPtr info=LinkInfoPtr()) override
void link (App::DocumentObject *obj)
bool isLinked () const
Public Member Functions inherited from Gui::LinkOwner
virtual void onLinkedUpdateData (LinkInfoPtr, const App::Property *)
Public Attributes
LinkInfoPtr linkInfo
LinkView & handle
CoinPtr< SoSeparator > pcNode
CoinPtr< SoTransform > pcTransform
std::set< std::string > subElements
friend LinkView
Additional Inherited Members
Protected Member Functions inherited from Gui::LinkOwner
virtual ~LinkOwner ()=default
Detailed Description
Definition at line 771 of file ViewProviderLink.cpp.
Constructor & Destructor Documentation
SubInfo()
Gui::LinkView::SubInfo::SubInfo (LinkView & handle) inline
Definition at line 781 of file ViewProviderLink.cpp.
References Gui::LinkView::SubInfo::pcNode, and Gui::LinkView::SubInfo::pcTransform.
~SubInfo()
Gui::LinkView::SubInfo::~SubInfo () inline override
Definition at line 787 of file ViewProviderLink.cpp.
References Gui::LinkView::getLinkRoot(), Gui::LinkView::SubInfo::handle, Gui::LinkView::SubInfo::pcNode, and Gui::LinkView::SubInfo::unlink().
Member Function Documentation
isLinked()
bool Gui::LinkView::SubInfo::isLinked () const inline
Definition at line 821 of file ViewProviderLink.cpp.
References Gui::LinkView::SubInfo::linkInfo.
Referenced by Gui::LinkView::SubInfo::link().
link()
void Gui::LinkView::SubInfo::link (App::DocumentObject * obj) inline
Definition at line 812 of file ViewProviderLink.cpp.
References Gui::LinkInfo::get(), Gui::LinkView::SubInfo::isLinked(), Gui::LinkView::SubInfo::linkInfo, Gui::LinkView::SubInfo::pcNode, Gui::LinkView::SnapshotTransform, and Gui::LinkView::SubInfo::unlink().
onLinkedIconChange()
void Gui::LinkView::SubInfo::onLinkedIconChange (LinkInfoPtr) inline override virtual
Reimplemented from Gui::LinkOwner.
Definition at line 797 of file ViewProviderLink.cpp.
References Gui::LinkView::autoSubLink, Gui::LinkView::SubInfo::handle, Gui::LinkView::linkInfo, Gui::LinkView::onLinkedIconChange(), and Gui::LinkView::subInfo.
unlink()
void Gui::LinkView::SubInfo::unlink (LinkInfoPtr info = LinkInfoPtr()) inline override virtual
Reimplemented from Gui::LinkOwner.
Definition at line 802 of file ViewProviderLink.cpp.
References Gui::coinRemoveAllChildren(), Path.Log::info(), Gui::LinkView::SubInfo::linkInfo, Gui::LinkView::SubInfo::pcNode, and Gui::LinkView::SubInfo::pcTransform.
Referenced by Gui::LinkView::SubInfo::link(), and Gui::LinkView::SubInfo::~SubInfo().
Member Data Documentation
handle
LinkView& Gui::LinkView::SubInfo::handle
Definition at line 774 of file ViewProviderLink.cpp.
Referenced by Gui::LinkView::SubInfo::onLinkedIconChange(), and Gui::LinkView::SubInfo::~SubInfo().
linkInfo
LinkInfoPtr Gui::LinkView::SubInfo::linkInfo
Definition at line 773 of file ViewProviderLink.cpp.
Referenced by Gui::LinkView::SubInfo::isLinked(), Gui::LinkView::SubInfo::link(), and Gui::LinkView::SubInfo::unlink().
LinkView
friend Gui::LinkView::SubInfo::LinkView
Definition at line 779 of file ViewProviderLink.cpp.
pcNode
CoinPtr<SoSeparator> Gui::LinkView::SubInfo::pcNode
Definition at line 775 of file ViewProviderLink.cpp.
Referenced by Gui::LinkView::SubInfo::link(), Gui::LinkView::SubInfo::SubInfo(), Gui::LinkView::SubInfo::unlink(), and Gui::LinkView::SubInfo::~SubInfo().
pcTransform
CoinPtr<SoTransform> Gui::LinkView::SubInfo::pcTransform
Definition at line 776 of file ViewProviderLink.cpp.
Referenced by Gui::LinkView::SubInfo::SubInfo(), and Gui::LinkView::SubInfo::unlink().
subElements
std::set<std::string> Gui::LinkView::SubInfo::subElements
Definition at line 777 of file ViewProviderLink.cpp.
The documentation for this class was generated from the following file:
ViewProviderLink.cpp