FreeCAD: TechDraw::areaPoint Class Reference
TechDraw::areaPoint Class Reference
#include <DimensionGeometry.h>
Public Member Functions
areaPoint ()
areaPoint (const areaPoint &ap)=default
areaPoint & operator= (const areaPoint &ap)
void move (const Base::Vector3d &offset)
void project (const DrawViewPart *dvp)
void invertY ()
void dump (const std::string &text) const
double getFilledArea () const
double getActualArea () const
Base::Vector3d getCenter () const
Public Attributes
double area {0}
double actualArea {0}
Base::Vector3d center
Detailed Description
Definition at line 180 of file DimensionGeometry.h.
Constructor & Destructor Documentation
areaPoint() [1/2]
areaPoint::areaPoint ()
Definition at line 366 of file DimensionGeometry.cpp.
areaPoint() [2/2]
TechDraw::areaPoint::areaPoint (const areaPoint & ap) default
Member Function Documentation
dump()
void areaPoint::dump (const std::string & text) const
Definition at line 396 of file DimensionGeometry.cpp.
References area, center, Base::Console(), TechDraw::DrawUtil::formatVector(), and Base::ConsoleSingleton::Message().
getActualArea()
double TechDraw::areaPoint::getActualArea () const inline
Definition at line 194 of file DimensionGeometry.h.
getCenter()
Base::Vector3d TechDraw::areaPoint::getCenter () const inline
Definition at line 195 of file DimensionGeometry.h.
getFilledArea()
double TechDraw::areaPoint::getFilledArea () const inline
Definition at line 193 of file DimensionGeometry.h.
invertY()
void areaPoint::invertY ()
Definition at line 391 of file DimensionGeometry.cpp.
References center, and TechDraw::DrawUtil::invertY().
Referenced by TechDraw::DrawViewDimension::getAreaParameters().
move()
void areaPoint::move (const Base::Vector3d & offset)
Definition at line 381 of file DimensionGeometry.cpp.
References center.
Referenced by TechDraw::DrawViewDimension::getAreaParameters().
operator=()
areaPoint & areaPoint::operator= (const areaPoint & ap)
Definition at line 373 of file DimensionGeometry.cpp.
References actualArea, area, and center.
project()
void areaPoint::project (const DrawViewPart * dvp)
Definition at line 386 of file DimensionGeometry.cpp.
References center, TechDraw::DrawView::getScale(), and TechDraw::DrawViewPart::projectPoint().
Referenced by TechDraw::DrawViewDimension::getAreaParameters().
Member Data Documentation
actualArea
double TechDraw::areaPoint::actualArea {0}
Definition at line 198 of file DimensionGeometry.h.
Referenced by TechDraw::DrawViewDimension::getAreaParameters(), and operator=().
area
double TechDraw::areaPoint::area {0}
Definition at line 197 of file DimensionGeometry.h.
Referenced by TechDrawGui::QGIViewDimension::drawArea(), dump(), TechDraw::DrawViewDimension::getAreaParameters(), and operator=().
center
Base::Vector3d TechDraw::areaPoint::center
Definition at line 199 of file DimensionGeometry.h.
Referenced by TechDrawGui::QGIViewDimension::drawArea(), dump(), Path.Dressup.Gui.AxisMap.ObjectDressup::execute(), TechDraw::DrawViewDimension::getAreaParameters(), invertY(), move(), Path.Dressup.Gui.AxisMap.ObjectDressup::onChanged(), operator=(), and project().
The documentation for this class was generated from the following files:
DimensionGeometry.h
DimensionGeometry.cpp