FreeCAD: MeshGui::DlgDecimating Class Reference
MeshGui::DlgDecimating Class Reference
#include <DlgDecimating.h>
Public Member Functions
DlgDecimating (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~DlgDecimating () override
void setNumberOfTriangles (int)
double tolerance () const
double reduction () const
bool isAbsoluteNumber () const
int targetNumberOfTriangles () const
Detailed Description
Definition at line 55 of file DlgDecimating.h.
Constructor & Destructor Documentation
DlgDecimating()
DlgDecimating::DlgDecimating (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Definition at line 38 of file DlgDecimating.cpp.
References draftgeoutils.intersections::connect().
~DlgDecimating()
DlgDecimating::~DlgDecimating () override default
Member Function Documentation
isAbsoluteNumber()
bool DlgDecimating::isAbsoluteNumber () const
Definition at line 54 of file DlgDecimating.cpp.
Referenced by MeshGui::TaskDecimating::accept().
reduction()
double DlgDecimating::reduction () const
Returns the level of reduction in the range [0, 1]. 0 means no reduction, 1 means full reduction.
Definition at line 122 of file DlgDecimating.cpp.
References KDL::max(), KDL::min(), and toolbit-attributes::val.
Referenced by MeshGui::TaskDecimating::accept(), and targetNumberOfTriangles().
setNumberOfTriangles()
void DlgDecimating::setNumberOfTriangles (int num)
Definition at line 68 of file DlgDecimating.cpp.
Referenced by MeshGui::TaskDecimating::TaskDecimating().
targetNumberOfTriangles()
int DlgDecimating::targetNumberOfTriangles () const
Definition at line 59 of file DlgDecimating.cpp.
References reduction().
Referenced by MeshGui::TaskDecimating::accept().
tolerance()
double DlgDecimating::tolerance () const
Definition at line 113 of file DlgDecimating.cpp.
Referenced by MeshGui::TaskDecimating::accept().
The documentation for this class was generated from the following files:
DlgDecimating.h
DlgDecimating.cpp