FreeCAD: App::Expression Struct Reference
App::Expression Struct Reference abstract
#include <Expression.h>
Classes
class Exception
Public Types
enum DepOption { DepNormal, DepHidden, DepAll }
using ComponentList = std::vector< Component * >
Public Member Functions
Expression (const App::DocumentObject *_owner)
~Expression () override
virtual bool isTouched () const
Expression * eval () const
std::string toString (bool persistent=false, bool checkPriority=false, int indent=0) const
void toString (std::ostream &os, bool persistent=false, bool checkPriority=false, int indent=0) const
Expression * copy () const
virtual int priority () const
void getIdentifiers (std::map< App::ObjectIdentifier, bool > &) const
std::map< App::ObjectIdentifier, bool > getIdentifiers () const
void getDeps (ExpressionDeps &deps, int option=DepNormal) const
ExpressionDeps getDeps (int option=DepNormal) const
std::map< App::DocumentObject *, bool > getDepObjects (std::vector< std::string > *labels=nullptr) const
void getDepObjects (std::map< App::DocumentObject *, bool > &, std::vector< std::string > *labels=nullptr) const
ExpressionPtr importSubNames (const std::map< std::string, std::string > &nameMap) const
ExpressionPtr updateLabelReference (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const
ExpressionPtr replaceObject (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const
bool adjustLinks (const std::set< App::DocumentObject * > &inList)
virtual Expression * simplify () const =0
void visit (ExpressionVisitor &v)
App::DocumentObject * getOwner () const
virtual void addComponent (Component *component)
bool hasComponent () const
boost::any getValueAsAny () const
Py::Object getPyValue () const
bool isSame (const Expression &other, bool checkComment=true) const
Component (const std::string &n)
Component (Expression *e1, Expression *e2, Expression *e3, bool isRange=false)
Component (const ObjectIdentifier::Component &comp)
Component (const Component &other)
~Component ()
Component & operator= (const Component &)=delete
void visit (ExpressionVisitor &v)
bool isTouched () const
void toString (std::ostream &ss, bool persistent) const
Component * copy () const
Component * eval () const
Py::Object get (const Expression *owner, const Py::Object &pyobj) const
void set (const Expression *owner, Py::Object &pyobj, const Py::Object &value) const
void del (const Expression *owner, Py::Object &pyobj) const
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static Expression * parse (const App::DocumentObject *owner, const std::string &buffer)
static Component * createComponent (const std::string &n)
static Component * createComponent (Expression *e1, Expression *e2=nullptr, Expression *e3=nullptr, bool isRange=false)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes
std::string comment
ObjectIdentifier::Component comp
Expression * e1
Expression * e2
Expression * e3
Protected Member Functions
virtual bool _isIndexable () const
virtual Expression * _copy () const =0
virtual void _toString (std::ostream &ss, bool persistent, int indent=0) const =0
virtual void _getIdentifiers (std::map< App::ObjectIdentifier, bool > &) const
virtual bool _adjustLinks (const std::set< App::DocumentObject * > &, ExpressionVisitor &)
virtual bool _updateElementReference (App::DocumentObject *, bool, ExpressionVisitor &)
virtual bool _relabeledDocument (const std::string &, const std::string &, ExpressionVisitor &)
virtual void _importSubNames (const ObjectIdentifier::SubNameMap &)
virtual void _updateLabelReference (App::DocumentObject *, const std::string &, const char *)
virtual bool _renameObjectIdentifier (const std::map< ObjectIdentifier, ObjectIdentifier > &, const ObjectIdentifier &, ExpressionVisitor &)
virtual void _collectReplacement (std::map< ObjectIdentifier, ObjectIdentifier > &, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const
virtual void _moveCells (const CellAddress &, int, int, ExpressionVisitor &)
virtual void _offsetCells (int, int, ExpressionVisitor &)
virtual Py::Object _getPyValue () const =0
virtual void _visit (ExpressionVisitor &)
Protected Attributes
App::DocumentObject * owner
ComponentList components
Friends
class ExpressionVisitor
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Base class for expressions.
Definition at line 116 of file Expression.h.
Member Typedef Documentation
ComponentList
using App::Expression::ComponentList = std::vector<Component*>
Definition at line 176 of file Expression.h.
Member Enumeration Documentation
DepOption
enum App::Expression::DepOption
Enumerator
DepNormal
DepHidden
DepAll
Definition at line 141 of file Expression.h.
Constructor & Destructor Documentation
Expression()
Expression::Expression (const App::DocumentObject * _owner) explicit
Definition at line 859 of file Expression.cpp.
~Expression()
Expression::~Expression () override
Definition at line 865 of file Expression.cpp.
References SCL.SimpleDataTypes::c, and components.
~Component()
App::Expression::~Component ()
Member Function Documentation
_adjustLinks()
virtual bool App::Expression::_adjustLinks (const std::set< App::DocumentObject * > & , ExpressionVisitor &) inline protected virtual
Reimplemented in App::VariableExpression.
Definition at line 197 of file Expression.h.
_collectReplacement()
virtual void App::Expression::_collectReplacement (std::map< ObjectIdentifier, ObjectIdentifier > & , const App::DocumentObject * parent, App::DocumentObject * oldObj, App::DocumentObject * newObj) const inline protected virtual
Reimplemented in App::VariableExpression.
Definition at line 204 of file Expression.h.
References Init::parent.
_copy()
virtual Expression* App::Expression::_copy () const protected pure virtual
Implemented in App::RangeExpression, App::StringExpression, App::PyObjectExpression, App::VariableExpression, App::FunctionExpression, App::ConditionalExpression, App::OperatorExpression, App::ConstantExpression, App::NumberExpression, and App::UnitExpression.
Referenced by copy().
_getIdentifiers()
virtual void App::Expression::_getIdentifiers (std::map< App::ObjectIdentifier, bool > &) const inline protected virtual
Reimplemented in App::RangeExpression, and App::VariableExpression.
Definition at line 196 of file Expression.h.
_getPyValue()
virtual Py::Object App::Expression::_getPyValue () const protected pure virtual
Implemented in App::RangeExpression, App::StringExpression, App::PyObjectExpression, App::VariableExpression, App::FunctionExpression, App::ConditionalExpression, App::OperatorExpression, App::ConstantExpression, and App::UnitExpression.
Referenced by getPyValue().
_importSubNames()
virtual void App::Expression::_importSubNames (const ObjectIdentifier::SubNameMap &) inline protected virtual
Reimplemented in App::VariableExpression.
Definition at line 200 of file Expression.h.
_isIndexable()
virtual bool App::Expression::_isIndexable () const inline protected virtual
Reimplemented in App::StringExpression, and App::VariableExpression.
Definition at line 193 of file Expression.h.
Referenced by toString().
_moveCells()
virtual void App::Expression::_moveCells (const CellAddress & , int , int , ExpressionVisitor &) inline protected virtual
Reimplemented in App::RangeExpression, and App::VariableExpression.
Definition at line 211 of file Expression.h.
_offsetCells()
virtual void App::Expression::_offsetCells (int , int , ExpressionVisitor &) inline protected virtual
Reimplemented in App::RangeExpression, and App::VariableExpression.
Definition at line 212 of file Expression.h.
_relabeledDocument()
virtual bool App::Expression::_relabeledDocument (const std::string & , const std::string & , ExpressionVisitor &) inline protected virtual
Reimplemented in App::VariableExpression.
Definition at line 199 of file Expression.h.
_renameObjectIdentifier()
virtual bool App::Expression::_renameObjectIdentifier (const std::map< ObjectIdentifier, ObjectIdentifier > & , const ObjectIdentifier & , ExpressionVisitor &) inline protected virtual
Reimplemented in App::RangeExpression, and App::VariableExpression.
Definition at line 202 of file Expression.h.
_toString()
virtual void App::Expression::_toString (std::ostream & ss, bool persistent, int indent = 0) const protected pure virtual
Implemented in App::RangeExpression, App::StringExpression, App::PyObjectExpression, App::VariableExpression, App::FunctionExpression, App::ConditionalExpression, App::OperatorExpression, App::ConstantExpression, App::NumberExpression, and App::UnitExpression.
Referenced by toString().
_updateElementReference()
virtual bool App::Expression::_updateElementReference (App::DocumentObject * , bool , ExpressionVisitor &) inline protected virtual
Reimplemented in App::VariableExpression.
Definition at line 198 of file Expression.h.
_updateLabelReference()
virtual void App::Expression::_updateLabelReference (App::DocumentObject * , const std::string & , const char *) inline protected virtual
Reimplemented in App::VariableExpression.
Definition at line 201 of file Expression.h.
_visit()
virtual void App::Expression::_visit (ExpressionVisitor &) inline protected virtual
Reimplemented in App::FunctionExpression, App::ConditionalExpression, and App::OperatorExpression.
Definition at line 214 of file Expression.h.
Referenced by visit().
addComponent()
void Expression::addComponent (Component * component) virtual
Reimplemented in App::VariableExpression.
Definition at line 1128 of file Expression.cpp.
References components.
Referenced by App::VariableExpression::addComponent().
adjustLinks()
bool Expression::adjustLinks (const std::set< App::DocumentObject * > & inList)
Definition at line 982 of file Expression.cpp.
References TestSpreadsheet::v, and visit().
Component() [1/4]
App::Expression::Component (const Component & other)
Component() [2/4]
App::Expression::Component (const ObjectIdentifier::Component & comp) explicit
Component() [3/4]
App::Expression::Component (const std::string & n) explicit
Referenced by createComponent().
Component() [4/4]
App::Expression::Component (Expression * e1, Expression * e2, Expression * e3, bool isRange = false)
copy() [1/2]
Component* App::Expression::copy () const
copy() [2/2]
Expression * Expression::copy () const
Definition at line 1180 of file Expression.cpp.
References _copy(), comment, components, and copy_vector().
Referenced by App::OperatorExpression::_copy(), App::ConditionalExpression::_copy(), importSubNames(), Spreadsheet::PropertySheet::pasteCells(), replaceObject(), App::NumberExpression::simplify(), App::VariableExpression::simplify(), App::StringExpression::simplify(), App::RangeExpression::simplify(), and updateLabelReference().
createComponent() [1/2]
Expression::Component * Expression::createComponent (const std::string & n) static
Definition at line 871 of file Expression.cpp.
References Component().
createComponent() [2/2]
Expression::Component * Expression::createComponent (Expression * e1, Expression * e2 = nullptr, Expression * e3 = nullptr, bool isRange = false) static
Definition at line 875 of file Expression.cpp.
References Component(), e1, e2, and e3.
del()
void App::Expression::del (const Expression * owner, Py::Object & pyobj) const
eval() [1/2]
Component* App::Expression::eval () const
eval() [2/2]
Expression * Expression::eval () const
Definition at line 1140 of file Expression.cpp.
References App::expressionFromPy(), getPyValue(), and owner.
Referenced by App::OperatorExpression::simplify(), App::FunctionExpression::simplify(), and Spreadsheet::Sheet::updateProperty().
get()
Py::Object App::Expression::get (const Expression * owner, const Py::Object & pyobj) const
Referenced by draftguitools.gui_trackers.editTracker::move().
getDepObjects() [1/2]
void Expression::getDepObjects (std::map< App::DocumentObject *, bool > & deps, std::vector< std::string > * labels = nullptr) const
Definition at line 913 of file Expression.cpp.
References App::ObjectIdentifier::getDep(), getIdentifiers(), App::ExpressionParser::labels, App::Remove, App::DocumentObject::testStatus(), and TestSpreadsheet::v.
getDepObjects() [2/2]
std::map< App::DocumentObject *, bool > Expression::getDepObjects (std::vector< std::string > * labels = nullptr) const
Definition at line 937 of file Expression.cpp.
References App::ExpressionParser::labels.
getDeps() [1/2]
void Expression::getDeps (ExpressionDeps & deps, int option = DepNormal) const
Definition at line 891 of file Expression.cpp.
References DepHidden, DepNormal, App::ObjectIdentifier::getDep(), getIdentifiers(), and TestSpreadsheet::v.
Referenced by getDeps(), and importSubNames().
getDeps() [2/2]
ExpressionDeps Expression::getDeps (int option = DepNormal) const
Definition at line 907 of file Expression.cpp.
References getDeps().
getIdentifiers() [1/2]
std::map< App::ObjectIdentifier, bool > Expression::getIdentifiers () const
Definition at line 961 of file Expression.cpp.
Referenced by getDepObjects(), getDeps(), and updateLabelReference().
getIdentifiers() [2/2]
void Expression::getIdentifiers (std::map< App::ObjectIdentifier, bool > & deps) const
Definition at line 956 of file Expression.cpp.
References TestSpreadsheet::v, and visit().
getOwner()
App::DocumentObject* App::Expression::getOwner () const inline
Definition at line 171 of file Expression.h.
Referenced by App::FunctionExpression::evaluate(), and App::ExpressionParser::parseUnit().
getPyValue()
Py::Object Expression::getPyValue () const
Definition at line 1114 of file Expression.cpp.
References _getPyValue(), SCL.SimpleDataTypes::c, components, and EXPR_PY_THROW.
Referenced by App::ConditionalExpression::_getPyValue(), calc(), eval(), App::FunctionExpression::evaluate(), App::FunctionExpression::evaluateSecondVectorArgument(), App::FunctionExpression::extractLengthValueArgument(), and getValueAsAny().
getValueAsAny()
App::any Expression::getValueAsAny () const
Definition at line 1109 of file Expression.cpp.
References getPyValue(), and App::pyObjectToAny().
hasComponent()
bool App::Expression::hasComponent () const inline
Definition at line 182 of file Expression.h.
importSubNames()
ExpressionPtr Expression::importSubNames (const std::map< std::string, std::string > & nameMap) const
Definition at line 1001 of file Expression.cpp.
References copy(), DepAll, getDeps(), App::DocumentObject::getDocument(), Path.Log::info(), Path.Post.scripts.opensbp_post::move(), owner, App::PropertyLinkBase::tryImportSubName(), and TestSpreadsheet::v.
isSame()
bool Expression::isSame (const Expression & other, bool checkComment = true) const
Definition at line 1145 of file Expression.cpp.
References comment, Base::BaseClass::getTypeId(), and toString().
isTouched() [1/2]
bool App::Expression::isTouched () const
isTouched() [2/2]
virtual bool App::Expression::isTouched () const inline virtual
Reimplemented in App::RangeExpression, App::VariableExpression, App::FunctionExpression, App::ConditionalExpression, and App::OperatorExpression.
Definition at line 125 of file Expression.h.
Referenced by App::OperatorExpression::isTouched(), and App::ConditionalExpression::isTouched().
operator=()
Component& App::Expression::operator= (const Component &) delete
parse()
Expression * Expression::parse (const App::DocumentObject * owner, const std::string & buffer) static
Definition at line 886 of file Expression.cpp.
References owner, and App::ExpressionParser::parse().
Referenced by BOPTools.GeneralFuseResult.GeneralFuseResult::__init__(), SpreadsheetGui::DlgSheetConf::accept(), App::PropertyExpressionEngine::afterRestore(), Sketcher::SketchObject::carbonCopy(), BOPTools.GeneralFuseResult.GeneralFuseResult::explodeCompounds(), StdCmdExpression::pasteExpressions(), SpreadsheetGui::DlgSheetConf::prepare(), App::Metadata::satisfies(), Sketcher::SketchObject::setConstraintExpression(), Spreadsheet::PropertySheet::setPathValue(), and BOPTools.GeneralFuseResult.GeneralFuseResult::splitAggregates().
priority()
int Expression::priority () const virtual
Reimplemented in App::ConditionalExpression, and App::OperatorExpression.
Definition at line 882 of file Expression.cpp.
Referenced by App::OperatorExpression::_toString(), App::ConditionalExpression::_toString(), and toString().
replaceObject()
ExpressionPtr Expression::replaceObject (const App::DocumentObject * parent, App::DocumentObject * oldObj, App::DocumentObject * newObj) const
Definition at line 1090 of file Expression.cpp.
References copy(), Init::parent, TestSpreadsheet::v, and visit().
set()
void App::Expression::set (const Expression * owner, Py::Object & pyobj, const Py::Object & value) const
Referenced by draftguitools.gui_trackers.editTracker::move().
simplify()
virtual Expression* App::Expression::simplify () const pure virtual
Implemented in App::RangeExpression, App::StringExpression, App::PyObjectExpression, App::VariableExpression, App::FunctionExpression, App::ConditionalExpression, App::OperatorExpression, App::NumberExpression, and App::UnitExpression.
Referenced by App::ExpressionParser::parseUnit(), App::OperatorExpression::simplify(), and App::ConditionalExpression::simplify().
toString() [1/3]
std::string Expression::toString (bool persistent = false, bool checkPriority = false, int indent = 0) const
Definition at line 1154 of file Expression.cpp.
References indent.
Referenced by App::OperatorExpression::_toString(), App::ConditionalExpression::_toString(), isSame(), and operator<<().
toString() [2/3]
void Expression::toString (std::ostream & os, bool persistent = false, bool checkPriority = false, int indent = 0) const
Definition at line 1160 of file Expression.cpp.
References _isIndexable(), _toString(), SCL.SimpleDataTypes::c, components, indent, and priority().
toString() [3/3]
void App::Expression::toString (std::ostream & ss, bool persistent) const
updateLabelReference()
ExpressionPtr Expression::updateLabelReference (App::DocumentObject * obj, const std::string & ref, const char * newLabel) const
Definition at line 1047 of file Expression.cpp.
References copy(), getIdentifiers(), App::ExpressionParser::labels, and TestSpreadsheet::v.
visit() [1/2]
void App::Expression::visit (ExpressionVisitor & v)
visit() [2/2]
void Expression::visit (ExpressionVisitor & v)
Definition at line 1133 of file Expression.cpp.
References _visit(), SCL.SimpleDataTypes::c, components, and TestSpreadsheet::v.
Referenced by App::OperatorExpression::_visit(), App::ConditionalExpression::_visit(), adjustLinks(), getIdentifiers(), and replaceObject().
Friends And Related Function Documentation
ExpressionVisitor
friend class ExpressionVisitor friend
Definition at line 190 of file Expression.h.
Member Data Documentation
comment
std::string App::Expression::comment
Definition at line 223 of file Expression.h.
Referenced by copy(), src.Mod.AddonManager.addonmanager_macro.Macro::fill_details_from_wiki(), and isSame().
comp
ObjectIdentifier::Component App::Expression::comp
Definition at line 87 of file ExpressionParser.h.
Referenced by App::VariableExpression::_moveCells(), and App::VariableExpression::_offsetCells().
components
ComponentList App::Expression::components protected
Definition at line 220 of file Expression.h.
Referenced by addComponent(), App::VariableExpression::addComponent(), copy(), getPyValue(), toString(), visit(), and ~Expression().
e1
Expression* App::Expression::e1
Definition at line 88 of file ExpressionParser.h.
Referenced by createComponent(), and App::FunctionExpression::evaluate().
e2
Expression* App::Expression::e2
Definition at line 89 of file ExpressionParser.h.
Referenced by createComponent(), and App::FunctionExpression::evaluate().
e3
Expression* App::Expression::e3
Definition at line 90 of file ExpressionParser.h.
Referenced by createComponent(), and App::FunctionExpression::evaluate().
owner
App::DocumentObject* App::Expression::owner protected
The document object used to access unqualified variables (i.e local scope)
Definition at line 218 of file Expression.h.
Referenced by App::UnitExpression::_copy(), App::NumberExpression::_copy(), App::ConstantExpression::_copy(), App::OperatorExpression::_copy(), App::ConditionalExpression::_copy(), App::FunctionExpression::_copy(), App::VariableExpression::_copy(), App::PyObjectExpression::_copy(), App::StringExpression::_copy(), App::RangeExpression::_copy(), App::RangeExpression::_getIdentifiers(), App::RangeExpression::_getPyValue(), App::RangeExpression::_renameObjectIdentifier(), eval(), App::FunctionExpression::evalAggregate(), App::RangeExpression::getRange(), importSubNames(), App::RangeExpression::isTouched(), parse(), App::UnitExpression::simplify(), App::OperatorExpression::simplify(), App::ConditionalExpression::simplify(), and App::FunctionExpression::simplify().
The documentation for this struct was generated from the following files:
Expression.h
ExpressionParser.h
Expression.cpp