FreeCAD: TechDrawGui::QGIWeldSymbol Class Reference
TechDrawGui::QGIWeldSymbol Class Reference
#include <QGIWeldSymbol.h>
Public Types
enum { Type = QGraphicsItem::UserType + 340 }
Public Types inherited from TechDrawGui::QGIView
enum { Type = QGraphicsItem::UserType + 101 }
Public Member Functions
QGIWeldSymbol ()
~QGIWeldSymbol () override=default
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
QRectF boundingRect () const override
QPainterPath shape () const override
double getEdgeFuzz () const
void drawBorder () override
void updateView (bool update=false) override
virtual TechDraw::DrawWeldSymbol * getFeature ()
virtual TechDraw::DrawLeaderLine * getLeader ()
QPointF getTileOrigin ()
QPointF getKinkPoint ()
QPointF getTailPoint ()
void setPrettyNormal ()
void setPrettySel ()
void setPrettyPre ()
void getTileFeats ()
void makeLines ()
double getLastSegAngle ()
get the angle for the transformed last segment
std::pair< Base::Vector3d, Base::Vector3d > getLocalAxes ()
Public Member Functions inherited from TechDrawGui::QGIView
QGIView ()
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
const char * getViewName () const
const std::string getViewNameAsString () const
void setViewFeature (TechDraw::DrawView *obj)
TechDraw::DrawView * getViewObject () const
MDIViewPage * getMDIViewPage () const
double getScale ()
void hideFrame ()
virtual bool getFrameState ()
virtual void toggleCache (bool state)
virtual void isVisible (bool state)
virtual bool isVisible ()
virtual bool getGroupSelection ()
virtual void setGroupSelection (bool isSelected)
virtual void setGroupSelection (bool isSelected, const std::vector< std::string > &subNames)
virtual void drawCaption ()
virtual void rotateView ()
void makeMark (double xPos, double yPos, QColor color=Qt::red)
void makeMark (Base::Vector3d pos, QColor color=Qt::red)
void makeMark (QPointF pos, QColor color=Qt::red)
void setPosition (qreal xPos, qreal yPos)
qreal getY ()
bool isInnerView () const
void isInnerView (bool state)
QGIViewClip * getClipGroup ()
bool isSnapping ()
void snapPosition (QPointF &position)
void snapSectionView (const TechDraw::DrawViewSection *sectionView, QPointF &newPosition)
Base::Vector3d projItemPagePos (TechDraw::DrawViewPart *item)
void alignTo (QGraphicsItem *, const QString &alignment)
QColor prefNormalColor ()
QColor getNormalColor ()
void setNormalColor (QColor color)
QColor getPreColor ()
QColor getSelectColor ()
QColor getCurrentColor ()
void setCurrentColor (QColor color)
QColor getSettingColor ()
void setSettingColor (QColor color)
virtual void setStack (int z)
virtual void setStackFromVP ()
QFont getFont ()
void setFont (QFont font)
virtual void removeChild (QGIView *child)
virtual void addArbitraryItem (QGraphicsItem *qgi)
virtual void switchParentItem (QGIView *targetParent)
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
Protected Member Functions
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
void draw () override
void drawTile (TechDraw::DrawTileWeld *tileFeat)
void drawAllAround ()
void drawTailText ()
void drawFieldFlag ()
void removeQGITiles ()
std::vector< QGITile * > getQGITiles () const
QColor prefNormalColor ()
double prefArrowSize () const
double prefFontSize () const
virtual QRectF customBoundingRect () const
Protected Member Functions inherited from TechDrawGui::QGIView
QGIView * getQGIVByName (std::string name)
QVariant itemChange (GraphicsItemChange change, const QVariant &value) override
void hoverEnterEvent (QGraphicsSceneHoverEvent *event) override
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event) override
virtual QRectF customChildrenBoundingRect () const
void dumpRect (const char *text, QRectF rect)
Base::Reference< ParameterGrp > getParmGroupCol ()
Additional Inherited Members
Static Public Member Functions inherited from TechDrawGui::QGIView
static Gui::ViewProvider * getViewProvider (App::DocumentObject *obj)
static ViewProviderPage * getViewProviderPage (TechDraw::DrawView *dView)
static int calculateFontPixelSize (double sizeInMillimetres)
static int calculateFontPixelWidth (const QFont &font)
static QString getPrefFont ()
static double getPrefFontSize ()
static double getDimFontSize ()
static int exactFontSize (std::string fontFamily, double nominalSize)
Static Public Attributes inherited from TechDrawGui::QGIView
static const double DefaultFontSizeInMM = 5.0
Detailed Description
Definition at line 59 of file QGIWeldSymbol.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 64 of file QGIWeldSymbol.h.
Constructor & Destructor Documentation
QGIWeldSymbol()
QGIWeldSymbol::QGIWeldSymbol () explicit
Definition at line 59 of file QGIWeldSymbol.cpp.
References ZVALUE::DIMENSION, TechDrawGui::QGIView::getNormalColor(), prefNormalColor(), TechDrawGui::QGIView::setCurrentColor(), TechDrawGui::QGIPrimPath::setFill(), TechDrawGui::QGIView::setNormalColor(), setPrettyNormal(), and TechDrawGui::QGIView::setSettingColor().
~QGIWeldSymbol()
TechDrawGui::QGIWeldSymbol::~QGIWeldSymbol () override default
Member Function Documentation
boundingRect()
QRectF QGIWeldSymbol::boundingRect () const override
Definition at line 576 of file QGIWeldSymbol.cpp.
References customBoundingRect().
customBoundingRect()
QRectF QGIWeldSymbol::customBoundingRect () const protected virtual
Definition at line 581 of file QGIWeldSymbol.cpp.
References getQGITiles(), and result.
Referenced by boundingRect().
draw()
void QGIWeldSymbol::draw () override protected virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 137 of file QGIWeldSymbol.cpp.
References drawAllAround(), drawFieldFlag(), drawTailText(), drawTile(), getTileFeats(), TechDrawGui::QGIView::isVisible(), and removeQGITiles().
Referenced by updateView().
drawAllAround()
void QGIWeldSymbol::drawAllAround () protected
Definition at line 223 of file QGIWeldSymbol.cpp.
References ZVALUE::DIMENSION, TechDrawGui::PreferencesGui::dimFontSizePX(), TechDrawGui::QGIView::getCurrentColor(), getFeature(), getKinkPoint(), getLeader(), TechDrawGui::QGIView::getQGIVByName(), TechDrawGui::QGIPrimPath::setFill(), TechDrawGui::QGIPrimPath::setNormalColor(), TechDrawGui::QGIVertex::setRadius(), and TechDrawGui::QGIPrimPath::setWidth().
Referenced by draw().
drawBorder()
void QGIWeldSymbol::drawBorder () override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 448 of file QGIWeldSymbol.cpp.
drawFieldFlag()
void QGIWeldSymbol::drawFieldFlag () protected
Definition at line 320 of file QGIWeldSymbol.cpp.
References ZVALUE::DIMENSION, TechDrawGui::PreferencesGui::dimFontSizePX(), dot(), getFeature(), getKinkPoint(), getLeader(), getLocalAxes(), TechDrawGui::QGIView::getQGIVByName(), draftfunctions.scale::scale(), TechDrawGui::QGIPrimPath::setWidth(), and TechDraw::DrawUtil::toQPointF().
Referenced by draw().
drawTailText()
void QGIWeldSymbol::drawTailText () protected
Definition at line 248 of file QGIWeldSymbol.cpp.
References DegreesHalfCircle, ZVALUE::DIMENSION, dot(), TechDrawGui::QGIView::exactFontSize(), TechDrawGui::QGIView::getCurrentColor(), getFeature(), TechDraw::DrawLeaderLine::getKinkPoint(), getLastSegAngle(), getLeader(), getLocalAxes(), getTailPoint(), App::PropertyString::getValue(), TechDrawGui::QGIView::getViewProvider(), prefArrowSize(), TechDrawGui::QGCustomText::setColor(), TechDraw::DrawWeldSymbol::TailText, and TechDraw::DrawUtil::toQPointF().
Referenced by draw().
drawTile()
void QGIWeldSymbol::drawTile (TechDraw::DrawTileWeld * tileFeat) protected
Definition at line 161 of file QGIWeldSymbol.cpp.
References TechDraw::DrawTileWeld::CenterText, Base::Console(), DegreesHalfCircle, ZVALUE::DIMENSION, dot(), TechDrawGui::QGIView::exactFontSize(), TechDrawGui::ViewProviderWeld::Font, TechDrawGui::QGIView::getCurrentColor(), getFeature(), getLastSegAngle(), getLeader(), getLocalAxes(), TechDraw::DrawLeaderLine::getScale(), getTileOrigin(), App::PropertyInteger::getValue(), App::PropertyString::getValue(), TechDrawGui::QGIView::getViewProvider(), TechDraw::DrawTileWeld::LeftText, Base::ConsoleSingleton::Message(), TechDraw::DrawTileWeld::RightText, TechDraw::DrawTile::TileColumn, and TechDraw::DrawTile::TileRow.
Referenced by draw().
getEdgeFuzz()
double TechDrawGui::QGIWeldSymbol::getEdgeFuzz () const
getFeature()
TechDraw::DrawWeldSymbol * QGIWeldSymbol::getFeature () virtual
Definition at line 525 of file QGIWeldSymbol.cpp.
References TechDrawGui::QGIView::getViewObject().
Referenced by drawAllAround(), drawFieldFlag(), drawTailText(), drawTile(), getLeader(), getTileFeats(), and updateView().
getKinkPoint()
QPointF QGIWeldSymbol::getKinkPoint ()
Definition at line 511 of file QGIWeldSymbol.cpp.
References TechDraw::DrawLeaderLine::getKinkPoint(), getLeader(), TechDrawGui::Rez::guiX(), result, and TechDraw::DrawUtil::toQPointF().
Referenced by drawAllAround(), and drawFieldFlag().
getLastSegAngle()
double QGIWeldSymbol::getLastSegAngle ()
get the angle for the transformed last segment
Definition at line 541 of file QGIWeldSymbol.cpp.
References TechDraw::DrawUtil::angleWithX(), getLeader(), TechDraw::DrawLeaderLine::lastSegmentDirection(), and Base::toDegrees().
Referenced by drawTailText(), and drawTile().
getLeader()
TechDraw::DrawLeaderLine * QGIWeldSymbol::getLeader () virtual
Definition at line 530 of file QGIWeldSymbol.cpp.
References getFeature(), App::PropertyLink::getValue(), and TechDraw::DrawWeldSymbol::Leader.
Referenced by drawAllAround(), drawFieldFlag(), drawTailText(), drawTile(), getKinkPoint(), getLastSegAngle(), getLocalAxes(), getTailPoint(), getTileOrigin(), and updateView().
getLocalAxes()
std::pair< Base::Vector3d, Base::Vector3d > QGIWeldSymbol::getLocalAxes ()
Definition at line 548 of file QGIWeldSymbol.cpp.
References getLeader(), TechDraw::DrawUtil::invertY(), TechDraw::DrawLeaderLine::lastSegmentDirection(), and M_PI_2.
Referenced by drawFieldFlag(), drawTailText(), and drawTile().
getQGITiles()
std::vector< QGITile * > QGIWeldSymbol::getQGITiles () const protected
Definition at line 409 of file QGIWeldSymbol.cpp.
References result.
Referenced by customBoundingRect(), removeQGITiles(), setPrettyNormal(), setPrettyPre(), and setPrettySel().
getTailPoint()
QPointF QGIWeldSymbol::getTailPoint ()
Definition at line 518 of file QGIWeldSymbol.cpp.
References getLeader(), TechDraw::DrawLeaderLine::getTailPoint(), TechDrawGui::Rez::guiX(), result, and TechDraw::DrawUtil::toQPointF().
Referenced by drawTailText().
getTileFeats()
void QGIWeldSymbol::getTileFeats ()
Definition at line 369 of file QGIWeldSymbol.cpp.
References getFeature(), TechDraw::DrawWeldSymbol::getTiles(), App::PropertyInteger::getValue(), and TechDraw::DrawTile::TileRow.
Referenced by draw().
getTileOrigin()
QPointF QGIWeldSymbol::getTileOrigin ()
Definition at line 504 of file QGIWeldSymbol.cpp.
References getLeader(), TechDraw::DrawLeaderLine::getTileOrigin(), TechDrawGui::Rez::guiX(), result, and TechDraw::DrawUtil::toQPointF().
Referenced by drawTile().
hoverEnterEvent()
void QGIWeldSymbol::hoverEnterEvent (QGraphicsSceneHoverEvent * event) override protected
Definition at line 422 of file QGIWeldSymbol.cpp.
References TechDrawGui::QGIView::getPreColor(), TechDrawGui::QGIView::getSelectColor(), TechDrawGui::QGIView::hoverEnterEvent(), TechDrawGui::QGIView::setCurrentColor(), setPrettyPre(), and setPrettySel().
hoverLeaveEvent()
void QGIWeldSymbol::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) override protected
Definition at line 435 of file QGIWeldSymbol.cpp.
References TechDrawGui::QGIView::getNormalColor(), TechDrawGui::QGIView::getSelectColor(), TechDrawGui::QGIView::hoverLeaveEvent(), TechDrawGui::QGIView::setCurrentColor(), setPrettyNormal(), and setPrettySel().
itemChange()
QVariant QGIWeldSymbol::itemChange (GraphicsItemChange change, const QVariant & value) override protected
Definition at line 106 of file QGIWeldSymbol.cpp.
References TechDrawGui::QGIView::itemChange(), setPrettyNormal(), and setPrettySel().
makeLines()
void TechDrawGui::QGIWeldSymbol::makeLines ()
paint()
void QGIWeldSymbol::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 614 of file QGIWeldSymbol.cpp.
References TechDrawGui::QGIView::paint().
prefArrowSize()
double QGIWeldSymbol::prefArrowSize () const protected
Definition at line 566 of file QGIWeldSymbol.cpp.
References TechDrawGui::PreferencesGui::dimArrowSize().
Referenced by drawTailText().
prefFontSize()
double QGIWeldSymbol::prefFontSize () const protected
Definition at line 571 of file QGIWeldSymbol.cpp.
prefNormalColor()
QColor QGIWeldSymbol::prefNormalColor () protected
Definition at line 560 of file QGIWeldSymbol.cpp.
References TechDrawGui::QGIView::getNormalColor(), TechDrawGui::PreferencesGui::leaderQColor(), and TechDrawGui::QGIView::setNormalColor().
Referenced by QGIWeldSymbol().
removeQGITiles()
void QGIWeldSymbol::removeQGITiles () protected
Definition at line 393 of file QGIWeldSymbol.cpp.
References getQGITiles().
Referenced by draw().
setPrettyNormal()
void QGIWeldSymbol::setPrettyNormal ()
Definition at line 454 of file QGIWeldSymbol.cpp.
References TechDrawGui::QGIView::getNormalColor(), getQGITiles(), TechDrawGui::QGCustomText::setColor(), TechDrawGui::QGIView::setCurrentColor(), TechDrawGui::QGIPrimPath::setNormalColor(), TechDrawGui::QGIPrimPath::setPrettyNormal(), and TechDrawGui::QGCustomText::setPrettyNormal().
Referenced by hoverLeaveEvent(), itemChange(), and QGIWeldSymbol().
setPrettyPre()
void QGIWeldSymbol::setPrettyPre ()
Definition at line 470 of file QGIWeldSymbol.cpp.
References TechDrawGui::QGIView::getPreColor(), getQGITiles(), TechDrawGui::QGCustomText::setColor(), TechDrawGui::QGIView::setCurrentColor(), TechDrawGui::QGIPrimPath::setNormalColor(), TechDrawGui::QGIPrimPath::setPrettyPre(), and TechDrawGui::QGCustomText::setPrettyPre().
Referenced by hoverEnterEvent().
setPrettySel()
void QGIWeldSymbol::setPrettySel ()
Definition at line 487 of file QGIWeldSymbol.cpp.
References getQGITiles(), TechDrawGui::QGIView::getSelectColor(), TechDrawGui::QGCustomText::setColor(), TechDrawGui::QGIView::setCurrentColor(), TechDrawGui::QGIPrimPath::setNormalColor(), TechDrawGui::QGIPrimPath::setPrettySel(), and TechDrawGui::QGCustomText::setPrettySel().
Referenced by hoverEnterEvent(), hoverLeaveEvent(), and itemChange().
shape()
QPainterPath QGIWeldSymbol::shape () const override
Definition at line 609 of file QGIWeldSymbol.cpp.
type()
int TechDrawGui::QGIWeldSymbol::type () const inline override
Definition at line 69 of file QGIWeldSymbol.h.
updateView()
void QGIWeldSymbol::updateView (bool update = false) override virtual
Reimplemented from TechDrawGui::QGIView.
Definition at line 120 of file QGIWeldSymbol.cpp.
References Base::Console(), draw(), getFeature(), getLeader(), App::DocumentObject::isRestoring(), and Base::ConsoleSingleton::Warning().
The documentation for this class was generated from the following files:
QGIWeldSymbol.h
QGIWeldSymbol.cpp