FreeCAD: Application.cpp File Reference
App/Application.cpp File Reference
#include "PreCompiled.h"
#include <boost/program_options.hpp>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <chrono>
#include <random>
#include <QCoreApplication>
#include <QDir>
#include <QFileInfo>
#include <QProcessEnvironment>
#include <QStandardPaths>
#include <LibraryVersions.h>
#include <App/MaterialPy.h>
#include <App/MetadataPy.h>
#include <Base/AxisPy.h>
#include <Base/BaseClass.h>
#include <Base/BoundBoxPy.h>
#include <Base/ConsoleObserver.h>
#include <Base/ServiceProvider.h>
#include <Base/CoordinateSystemPy.h>
#include <Base/Exception.h>
#include <Base/ExceptionFactory.h>
#include <Base/FileInfo.h>
#include <Base/GeometryPyCXX.h>
#include <Base/Interpreter.h>
#include <Base/MatrixPy.h>
#include <Base/QuantityPy.h>
#include <Base/Parameter.h>
#include <Base/Persistence.h>
#include <Base/PlacementPy.h>
#include <Base/PrecisionPy.h>
#include <Base/ProgressIndicatorPy.h>
#include <Base/RotationPy.h>
#include <Base/Tools.h>
#include <Base/Translate.h>
#include <Base/Type.h>
#include <Base/TypePy.h>
#include <Base/UnitPy.h>
#include <Base/UnitsApi.h>
#include <Base/VectorPy.h>
#include "Annotation.h"
#include "Application.h"
#include "CleanupProcess.h"
#include "ComplexGeoData.h"
#include "Services.h"
#include "DocumentObjectFileIncluded.h"
#include "DocumentObjectGroup.h"
#include "DocumentObjectGroupPy.h"
#include "DocumentObserver.h"
#include "DocumentPy.h"
#include "ExpressionParser.h"
#include "FeatureTest.h"
#include "FeaturePython.h"
#include "GeoFeature.h"
#include "GeoFeatureGroupExtension.h"
#include "ImagePlane.h"
#include "InventorObject.h"
#include "Link.h"
#include "LinkBaseExtensionPy.h"
#include "VarSet.h"
#include "MaterialObject.h"
#include "MeasureManagerPy.h"
#include "Origin.h"
#include "Datums.h"
#include "OriginGroupExtension.h"
#include "OriginGroupExtensionPy.h"
#include "SuppressibleExtension.h"
#include "SuppressibleExtensionPy.h"
#include "Part.h"
#include "GeoFeaturePy.h"
#include "Placement.h"
#include "ProgramOptionsUtilities.h"
#include "Property.h"
#include "PropertyContainer.h"
#include "PropertyExpressionEngine.h"
#include "PropertyFile.h"
#include "PropertyLinks.h"
#include "PropertyPythonObject.h"
#include "StringHasherPy.h"
#include "StringIDPy.h"
#include "TextDocument.h"
#include "Transactions.h"
#include "VRMLObject.h"
#include <Build/Version.h>
#include "Branding.h"
#include <App/InitScript.h>
#include <App/TestScript.h>
#include <App/CMakeScript.h>
#include "SafeMode.h"
#include <new>
Classes
struct DocTiming
class DocOpenGuard
Functions
PyDoc_STRVAR (FreeCAD_doc, "The functions in the FreeCAD module allow working with documents.\n" "The FreeCAD instance provides a list of references of documents which\n" "can be addressed by a string. Hence the document name must be unique.\n" "\n" "The document has the read-only attribute FileName which points to the\n" "file the document should be stored to.\n")
PyDoc_STRVAR (Console_doc, "FreeCAD Console module.\n\n" "The Console module contains functions to manage log entries, messages,\n" "warnings and errors.\n" "There are also functions to get/set the status of the observers used as\n" "logging interfaces.")
PyDoc_STRVAR (Base_doc, "The Base module contains the classes for the geometric basics\n" "like vector, matrix, bounding box, placement, rotation, axis, ...\n")
PyMODINIT_FUNC init_freecad_base_module (void)
PyMODINIT_FUNC init_freecad_module (void)
PyMODINIT_FUNC init_image_module ()
static void freecadNewHandler ()
void segmentation_fault_handler (int sig)
void unhandled_exception_handler ()
void unexpection_error_handler ()
template<class T >
ostream & operator<< (ostream &os, const vector< T > &v)
Variables
static PyMethodDef * ApplicationMethods = nullptr
static int _TransSignalCount
static bool _TransSignalled
Function Documentation
freecadNewHandler()
static void freecadNewHandler () static
freecadNewHandler() prints an error message and throws an exception
Definition at line 1795 of file App/Application.cpp.
Referenced by App::Application::init().
init_freecad_base_module()
PyMODINIT_FUNC init_freecad_base_module (void)
Definition at line 211 of file App/Application.cpp.
init_freecad_module()
PyMODINIT_FUNC init_freecad_module (void)
Definition at line 225 of file App/Application.cpp.
References ApplicationMethods.
init_image_module()
PyMODINIT_FUNC init_image_module ()
Definition at line 237 of file App/Application.cpp.
operator<<()
template<class T > ostream& operator<< (ostream & os, const vector< T > & v)
Definition at line 3091 of file App/Application.cpp.
References TestSpreadsheet::v.
PyDoc_STRVAR() [1/3]
PyDoc_STRVAR (Base_doc , "The Base module contains the classes for the geometric basics\n" "like vector, matrix , bounding box, placement , rotation , axis , ...\n")
PyDoc_STRVAR() [2/3]
PyDoc_STRVAR (Console_doc , "FreeCAD Console module.\n\n" "The Console module contains functions to manage log entries, messages , \n" "warnings and errors.\n" "There are also functions to get/set the status of the observers used as\n" "logging interfaces.")
PyDoc_STRVAR() [3/3]
PyDoc_STRVAR (FreeCAD_doc , "The functions in the FreeCAD module allow working with documents.\n" "The FreeCAD instance provides a list of references of documents which\n" "can be addressed by a string. Hence the document name must be unique.\n" "\n" "The document has the read-only attribute FileName which points to the\n" "file the document should be stored to.\n")
Referenced by Gui::Application::Application().
segmentation_fault_handler()
void segmentation_fault_handler (int sig)
Definition at line 1857 of file App/Application.cpp.
Referenced by App::Application::init().
unexpection_error_handler()
void unexpection_error_handler ()
Definition at line 1894 of file App/Application.cpp.
Referenced by App::Application::init().
unhandled_exception_handler()
void unhandled_exception_handler ()
Definition at line 1889 of file App/Application.cpp.
Referenced by App::Application::init().
Variable Documentation
_TransSignalCount
int _TransSignalCount static
Definition at line 1097 of file App/Application.cpp.
Referenced by App::Application::TransactionSignaller::TransactionSignaller(), and App::Application::TransactionSignaller::~TransactionSignaller().
_TransSignalled
bool _TransSignalled static
Definition at line 1098 of file App/Application.cpp.
Referenced by App::Application::TransactionSignaller::TransactionSignaller(), and App::Application::TransactionSignaller::~TransactionSignaller().
ApplicationMethods
PyMethodDef* ApplicationMethods = nullptr static
Definition at line 222 of file App/Application.cpp.
Referenced by init_freecad_module().