FreeCAD: Base Namespace Reference
Base Namespace Reference
Classes
class AbnormalProgramTermination
class AbortException
class AbstractExceptionProducer
Abstract base class of all exception producers.
class AbstractProducer
Abstract base class of all producers.
class AccessViolation
class ArrowItem
class AttributeError
class Axis
class BadFormatError
class BadGraphError
struct base64_decoder
struct base64_encoder
class BaseClass
BaseClass class and root of the type system.
class BaseColorItem
The BaseColorItem class supports the SoBaseColor node.
class BindingElement
class BindingManager
class BitsetLocker
class BoundBox2d
class BoundBox3
class BoundingBoxItem
class Builder3D
class ByteArrayIStreambuf
class ByteArrayOStreambuf
class CADKernelError
class ClassTemplate
class ColorRGB
class ConeItem
The ConeItem class supports the SoCone node.
class ConnectionBlocker
class ConsoleEvent
class ConsoleObserverFile
class ConsoleObserverStd
class ConsoleOutput
class ConsoleRefreshDisabler
class ConsoleSequencer
This class writes the progress to the console window.
class ConsoleSingleton
class Coordinate3Item
The Coordinate3Item class supports the SoCoordinate3 node.
class CoordinateSystem
class CylinderItem
The CylinderItem class supports the SoCylinder node.
class Debugger
class DrawStyle
class DrawStyleItem
The DrawStyleItem class supports the SoDrawStyle node.
class DualNumber
Dual Numbers are 2-part numbers like complex numbers, but different algebra. They are denoted as a + b*eps, where eps^2 = 0. eps, the nilpotent, is like imaginary unit of complex numbers. The neat utility of dual numbers is that if you use them instead of normal numbers in a function like sin(), derivative is implicitly calculated as a multiplier to the dual part.
class DualQuat
The DualQuat class represents a dual quaternion, as a quaternion of dual number components. Dual quaternions are useful for placement interpolation, see pow method.
class EmptySequencer
class Exception
class ExceptionFactory
class ExceptionProducer
class ExpressionError
class FaceSetItem
The FaceSetItem class supports the SoFaceSet node.
class Factory
struct field_traits
struct field_traits< ColorRGB >
struct field_traits< float >
struct field_traits< Vector3f >
class FileException
class FileInfo
class FileSystemError
class FileWriter
class Flags
struct FlagToggler
struct float_traits
struct float_traits< double >
struct float_traits< float >
class FutureWatcherProgress
class Handled
class ifstream
class ILogger
class ILoggerBlocker
class ImportError
class Indentation
class IndexedFaceSetItem
The IndexedFaceSetItem class supports the SoIndexedFaceSet node.
class IndexedLineSetItem
The IndexedLineSetItem class supports the SoIndexedLineSet node.
class IndexError
class InfoItem
The InfoItem class supports the SoInfo node.
class InputStream
class InterpreterSingleton
class InventorBuilder
class InventorFieldWriter
class InventorLoader
class InventorOutput
class IODeviceIStreambuf
class IODeviceOStreambuf
struct iotaGen
class LabelItem
The LabelItem class supports the SoLabel node.
class Line2d
class Line3
class LineItem
class LineSetItem
The LineSetItem class supports the SoLineSet node.
class LogLevel
class manipulator
class MaterialBindingItem
The MaterialBindingItem class supports the SoMaterialBinding node.
class MaterialItem
The MaterialItem class supports the SoMaterial node.
class Matrix4D
class MemoryException
class MultiLineItem
class NameError
class NodeItem
class NormalBindingItem
The MaterialBindingItem class supports the SoMaterialBinding node.
class NormalItem
The NormalItem class supports the SoNormal node.
class NotImplementedError
class NurbsSurfaceItem
The NurbsSurfaceItem class supports the SoNurbsSurface node.
class ObjectStatusLocker
class Observer
class ofstream
class OutputStream
class OverflowError
class ParameterGrpObserver
class ParameterGrpPy
class ParserError
class Persistence
Persistence class and root of the type system.
class Placement
class PointItem
class PointSetItem
The PointSetItem class supports the SoPointSet node.
class Polygon2d
class Polygon3
class PolygonOffset
class PolygonOffsetItem
The PolygonOffsetItem class supports the SoPolygonOffset node.
class Precision
class ProgramInformation
class ProgressIndicatorPy
class PropertyError
class PyException
class PyGILStateLocker
class PyGILStateRelease
class PyHandle
class PyObjectBase
class PyStreambuf
class PythonTypeExt
class to extend PyCXX PythonType class
class Quantity
struct QuantityFormat
class Reader
class RedirectStdError
class RedirectStdLog
class RedirectStdOutput
class Reference
class ReferenceError
class RestoreError
class Rotation
class RuntimeError
class ScriptFactorySingleton
class ScriptProducer
class SequencerBase
This class gives the user an indication of the progress of an operation and it is used to reassure him that the application is still running.
class SequencerLauncher
struct SequencerP
class ServiceProvider
class ShapeHintsItem
The ShapeHintsItem class supports the SoShapeHints node.
class ShapeType
class SphereItem
The SphereItem class supports the SoSphere node.
class StateLocker
class StdInputSource
class StdInputStream
class Stream
class Streambuf
struct string_comp
class StringWriter
class Subject
class SystemExitException
class Text2Item
The Text2Item class supports the SoText2 node.
class TextInputStream
class TextOutputStream
class TimeElapsed
class TimeInfo
struct Tools
class TransformItem
The TransformItem class supports the SoTransform node.
class Translate
class Triangle
class Type
struct TypeData
class TypeError
class UnderflowError
class UnicodeError
class unique_name
class UniqueNameManager
This class acts as a multiset of strings with the capability of generating other names that are not in the collection. Unique names are generated by inserting digits into a base name. Normally these are appended to the base name, but a derived class can override getNameSuffixStartPosition to place the digits elsewhere in the base name.
class Unit
class UnitsApi
class UnitsMismatchError
class UnitsSchema
class UnitsSchemaCentimeters
class UnitsSchemaFemMilliMeterNewton
class UnitsSchemaImperial1
class UnitsSchemaImperialBuilding
class UnitsSchemaImperialCivil
class UnitsSchemaImperialDecimal
class UnitsSchemaInternal
class UnitsSchemaMeterDecimal
class UnitsSchemaMKS
class UnitsSchemaMmMin
class UnknownProgramOption
class Uuid
class ValueError
struct vec_traits
struct vec_traits< App::Color >
struct vec_traits< gp_Dir >
struct vec_traits< gp_Pnt >
struct vec_traits< gp_Vec >
struct vec_traits< gp_XYZ >
struct vec_traits< Rotation >
struct vec_traits< SbColor >
struct vec_traits< SbRotation >
struct vec_traits< SbVec3d >
struct vec_traits< SbVec3f >
struct vec_traits< Vector3d >
struct vec_traits< Vector3f >
struct vec_traits< Wm4::Vector3d >
struct vec_traits< Wm4::Vector3f >
class Vector2d
class Vector2dPy
class Vector3
class VertexOrdering
class ViewOrthoProjMatrix
class ViewProjMatrix
class ViewProjMethod
class Writer
class XMLAttributeError
class XMLBaseException
class XMLParseException
class XMLReader
class ZeroDivisionError
struct ZipTools
class ZipWriter
Typedefs
using BoundBox3d = BoundBox3< double >
using BoundBox3f = BoundBox3< float >
using ParameterGrpObserverList = std::list< ParameterGrpObserver * >
using Clock = std::chrono::system_clock
using Ticks = std::chrono::steady_clock
using Line3f = Line3< float >
using Line3d = Line3< double >
using Polygon3f = Polygon3< float >
using Polygon3d = Polygon3< double >
using UnitsSchemaPtr = std::unique_ptr< UnitsSchema >
using Vector3f = Vector3< float >
using Vector3d = Vector3< double >
Enumerations
enum Base64ErrorHandling { Base64ErrorHandling::throws, Base64ErrorHandling::silent }
enum LogStyle {
LogStyle::Warning, LogStyle::Message, LogStyle::Error, LogStyle::Log,
LogStyle::Critical, LogStyle::Notification
}
enum IntendedRecipient { IntendedRecipient::All, IntendedRecipient::User, IntendedRecipient::Developer }
enum ContentType { ContentType::Untranslated, ContentType::Translated, ContentType::Untranslatable }
enum CharStreamFormat { CharStreamFormat::Raw, CharStreamFormat::Base64Encoded }
enum ScaleType {
ScaleType::Other = -1, ScaleType::NoScaling = 0, ScaleType::NonUniformRight = 1, ScaleType::NonUniformLeft = 2,
ScaleType::Uniform = 3
}
enum UnitSystem {
UnitSystem::SI1 = 0, UnitSystem::SI2 = 1, UnitSystem::Imperial1 = 2, UnitSystem::ImperialDecimal = 3,
UnitSystem::Centimeters = 4, UnitSystem::ImperialBuilding = 5, UnitSystem::MmMin = 6, UnitSystem::ImperialCivil = 7,
UnitSystem::FemMilliMeterNewton = 8, UnitSystem::MeterDecimal = 9, UnitSystem::NumUnitSystemTypes
}
Functions
template<>
SbMatrix convertTo< SbMatrix, Base::Matrix4D > (const Base::Matrix4D &vec2)
template<>
Base::Matrix4D convertTo< Base::Matrix4D, SbMatrix > (const SbMatrix &vec2)
std::size_t base64_encode_size (std::size_t len)
Returns the max bytes of a encoded base64 string.
std::size_t base64_decode_size (std::size_t len)
Returns the max bytes of a decoded base64 binary string.
BaseExport std::size_t base64_encode (char *out, void const *in, std::size_t len)
BaseExport std::array< const signed char, base64DecodeTableSize > base64_decode_table ()
BaseExport std::pair< std::size_t, std::size_t > base64_decode (void *out, char const *, std::size_t len)
void base64_encode (std::string &out, void const *in, std::size_t len)
std::string base64_encode (void const *in, std::size_t len)
template<typename T >
std::size_t base64_decode (T &out, char const *in, std::size_t len)
template<typename T >
std::size_t base64_decode (T &out, std::string const &str)
std::string base64_decode (std::string const &str)
std::unique_ptr< std::ostream > create_base64_encoder (std::ostream &out, std::size_t line_size=base64DefaultBufferSize)
std::unique_ptr< std::ostream > create_base64_encoder (const std::string &filepath, std::size_t line_size=base64DefaultBufferSize)
std::unique_ptr< std::istream > create_base64_decoder (std::istream &in, std::size_t line_size=base64DefaultBufferSize, Base64ErrorHandling errHandling=Base64ErrorHandling::silent)
std::unique_ptr< std::istream > create_base64_decoder (const std::string &filepath, std::size_t line_size=base64DefaultBufferSize, Base64ErrorHandling errHandling=Base64ErrorHandling::silent)
template<typename T >
T * freecad_dynamic_cast (Base::BaseClass *type)
template<typename T >
const T * freecad_dynamic_cast (const Base::BaseClass *type)
BaseExport Vector3f to_vector (std::string str)
std::chrono::duration< double > GetDuration (std::chrono::high_resolution_clock ::time_point &tp)
ConsoleSingleton & Console ()
template<class Vec , typename float_type >
Vec make_vec (const std::tuple< float_type, float_type, float_type > &&ft)
template<class Vec , typename float_type >
Vec make_vec (const std::tuple< float_type, float_type, float_type, float_type > &&ft)
template<class Vec1 , class Vec2 >
Vec1 convertTo (const Vec2 &vec)
DualNumber operator+ (DualNumber a, DualNumber b)
DualNumber operator+ (DualNumber a, double b)
DualNumber operator+ (double a, DualNumber b)
DualNumber operator- (DualNumber a, DualNumber b)
DualNumber operator- (DualNumber a, double b)
DualNumber operator- (double a, DualNumber b)
DualNumber operator* (DualNumber a, DualNumber b)
DualNumber operator* (double a, DualNumber b)
DualNumber operator* (DualNumber a, double b)
DualNumber operator/ (DualNumber a, DualNumber b)
DualNumber operator/ (DualNumber a, double b)
DualNumber pow (DualNumber a, double pw)
BaseExport DualQuat operator+ (DualQuat a, DualQuat b)
BaseExport DualQuat operator- (DualQuat a, DualQuat b)
BaseExport DualQuat operator* (DualQuat a, DualQuat b)
BaseExport DualQuat operator* (DualQuat a, double b)
BaseExport DualQuat operator* (double a, DualQuat b)
BaseExport DualQuat operator* (DualQuat a, DualNumber b)
BaseExport DualQuat operator* (DualNumber a, DualQuat b)
ScriptFactorySingleton & ScriptFactory ()
template<typename T >
Vector3< T > getVectorFromTuple (PyObject *py)
Py::Object pyCall (PyObject *callable, PyObject *args=nullptr)
Py::Object pyCallWithKeywords (PyObject *callable, PyObject *args, PyObject *kwds=nullptr)
InterpreterSingleton & Interpreter ()
Vector3f & operator*= (Vector3f &vec, const Matrix4D &mat)
int streq (const char *A, const char *B)
void Assert (int expr, char *msg)
PyObject * getTypeAsObject (PyTypeObject *type)
bool asBoolean (PyObject *obj)
PyObject * PyAsUnicodeObject (const char *str)
PyObject * PyAsUnicodeObject (const std::string &str)
void PyTypeCheck (PyObject **ptr, PyTypeObject *type, const char *msg=nullptr)
void PyTypeCheck (PyObject **ptr, int(*method)(PyObject *), const char *msg)
template<size_t arraySize>
bool Wrapped_ParseTupleAndKeywords (PyObject *args, PyObject *kw, const char *format, const std::array< const char *, arraySize > keywords,...)
SequencerBase & Sequencer ()
template<typename T >
T * provideService ()
template<typename T >
std::list< T * > provideServiceImplementations ()
template<typename T >
void registerServiceImplementation (T *implementation)
unsigned short SwapOrder ()
Definition of functions that allow swapping of data types dependent on the architecture.
void SwapVar (char &)
void SwapVar (unsigned char &)
void SwapVar (short &)
void SwapVar (unsigned short &)
void SwapVar (long &)
void SwapVar (unsigned long &)
void SwapVar (float &)
void SwapVar (double &)
template<class T >
void SwapEndian (T &v)
std::ostream & tabsN (std::ostream &os, int n)
std::ostream & blanksN (std::ostream &os, int n)
manipulator< int > tabs (int n)
manipulator< int > blanks (int n)
template<class T >
T clamp (T num, T lower, T upper)
template<class T >
T sgn (T t)
template<class T >
T toRadians (T d)
template<class T >
T toDegrees (T r)
template<class T >
T fmod (T numerator, T denominator)
Vector2d operator* (double c, const Vector2d &v)
template<class float_type >
float_type Distance (const Vector3< float_type > &v1, const Vector3< float_type > &v2)
Returns the distance between two points.
template<class float_type >
float_type DistanceP2 (const Vector3< float_type > &v1, const Vector3< float_type > &v2)
Returns the squared distance between two points.
template<class float_type >
Vector3< float_type > operator* (float_type fFac, const Vector3< float_type > &rcVct)
Multiplication of scalar with vector.
template<class Pr1 , class Pr2 >
Vector3< Pr1 > toVector (const Vector3< Pr2 > &v)
Variables
static constexpr size_t base64DecodeTableSize {256}
static constexpr int base64DefaultBufferSize {80}
template class BaseExport Observer< const char * >
template class BaseExport Subject< const char * >
BaseExport PyObject * PyExc_FC_GeneralError = nullptr
BaseExport PyObject * PyExc_FC_FreeCADAbort = nullptr
BaseExport PyObject * PyExc_FC_XMLBaseException = nullptr
BaseExport PyObject * PyExc_FC_XMLParseException = nullptr
BaseExport PyObject * PyExc_FC_XMLAttributeError = nullptr
BaseExport PyObject * PyExc_FC_UnknownProgramOption = nullptr
BaseExport PyObject * PyExc_FC_BadFormatError = nullptr
BaseExport PyObject * PyExc_FC_BadGraphError = nullptr
BaseExport PyObject * PyExc_FC_ExpressionError = nullptr
BaseExport PyObject * PyExc_FC_ParserError = nullptr
BaseExport PyObject * PyExc_FC_CADKernelError = nullptr
BaseExport PyObject * PyExc_FC_PropertyError = nullptr
BaseExport PyObject * PyExc_FC_AbortIOException = nullptr
Base::ServiceProvider globalServiceProvider
template class BaseExport Line3< float >
template class BaseExport Line3< double >
template class BaseExport Polygon3< float >
template class BaseExport Polygon3< double >
template class BaseExport Vector3< float >
template class BaseExport Vector3< double >
Typedef Documentation
BoundBox3d
typedef BoundBox3< double > Base::BoundBox3d
Definition at line 74 of file ComplexGeoData.h.
BoundBox3f
using Base::BoundBox3f = typedef BoundBox3<float>
Definition at line 1151 of file BoundBox.h.
Clock
using Base::Clock = typedef std::chrono::system_clock
Definition at line 57 of file TimeInfo.h.
Line3d
using Base::Line3d = typedef Line3<double>
Definition at line 163 of file Tools3D.h.
Line3f
using Base::Line3f = typedef Line3<float>
Definition at line 162 of file Tools3D.h.
ParameterGrpObserverList
using Base::ParameterGrpObserverList = typedef std::list<ParameterGrpObserver*>
Definition at line 123 of file ParameterPy.cpp.
Polygon3d
using Base::Polygon3d = typedef Polygon3<double>
Definition at line 166 of file Tools3D.h.
Polygon3f
using Base::Polygon3f = typedef Polygon3<float>
Definition at line 165 of file Tools3D.h.
Ticks
using Base::Ticks = typedef std::chrono::steady_clock
Definition at line 118 of file TimeInfo.h.
UnitsSchemaPtr
using Base::UnitsSchemaPtr = typedef std::unique_ptr<UnitsSchema>
Definition at line 38 of file UnitsApi.h.
Vector3d
using Base::Vector3d = typedef Vector3<double>
Definition at line 295 of file Vector3D.h.
Vector3f
using Base::Vector3f = typedef Vector3<float>
Definition at line 294 of file Vector3D.h.
Enumeration Type Documentation
Base64ErrorHandling
enum Base::Base64ErrorHandling strong
Enumerator
throws
silent
Definition at line 66 of file Base64Filter.h.
CharStreamFormat
enum Base::CharStreamFormat strong
When reading and writing a character stream, the incoming data can be dumped into the stream unaltered (if it contains only data that is valid in the current XML character set), or it can be Base64-encoded. This enum is used by Reader and Writer to distinguish the two cases.
Enumerator
Raw
Base64Encoded
Definition at line 61 of file FileInfo.h.
ContentType
enum Base::ContentType strong
Used to indicate the translation state of a message (warning, error, ...). While it is possible to create a custom message via Console().Send, console provides convenience functions for most common combinations.
See documentation of ConsoleSingleton class for more details.
See also
ConsoleSingleton
Enumerator
Untranslated
Translated
Untranslatable
Definition at line 537 of file Console.h.
IntendedRecipient
enum Base::IntendedRecipient strong
Used to indicate the intended recipient of a message (warning, error, ...). While it is possible to create a custom message via Console().Send, console provides convenience functions for most common combinations.
See documentation of ConsoleSingleton class for more details.
See also
ConsoleSingleton
Enumerator
All
User
Developer
Definition at line 522 of file Console.h.
LogStyle
enum Base::LogStyle strong
Used to identify log level
Enumerator
Warning
Message
Error
Log
Critical
Notification
Definition at line 504 of file Console.h.
ScaleType
enum Base::ScaleType strong
Enumerator
Other
NoScaling
NonUniformRight
NonUniformLeft
Uniform
Definition at line 59 of file Matrix.h.
UnitSystem
enum Base::UnitSystem strong
Units systems
Enumerator
SI1
SI2
internal (mm,kg,s) SI system (http://en.wikipedia.org/wiki/International_System_of_Units)
Imperial1
MKS (m,kg,s) SI system
ImperialDecimal
the Imperial system (http://en.wikipedia.org/wiki/Imperial_units)
Centimeters
Imperial with length in inch only
ImperialBuilding
All lengths in centimeters, areas and volumes in square/cubic meters
MmMin
All lengths in feet + inches + fractions
ImperialCivil
Lengths in mm, Speed in mm/min. Angle in degrees. Useful for small parts & CNC
FemMilliMeterNewton
Lengths in ft, Speed in ft/s. Used in Civil Eng in North America
MeterDecimal
Lengths in mm, Mass in t, TimeSpan in s, thus force is in N
NumUnitSystemTypes
Lengths in metres always
Definition at line 53 of file UnitsSchema.h.
Function Documentation
asBoolean()
bool Base::asBoolean (PyObject * obj) inline
Definition at line 125 of file PyObjectBase.h.
Referenced by areaAbort(), areaGetParamsDesc(), Gui::View3DInventorPy::dump(), Gui::MDIViewPy::getActiveObject(), App::PropertyBoolList::getPyValue(), Gui::PythonGroupCommand::hasDropDownMenu(), Gui::PythonCommand::isChecked(), Gui::PythonGroupCommand::isExclusive(), Gui::View3DInventorViewerPy::resetEditingRoot(), Gui::ApplicationPy::sActivateView(), Gui::SelectionSingleton::sAddSelection(), Gui::SelectionSingleton::sClearSelection(), Gui::SelectionSingleton::sEnablePickedList(), Gui::ExpressionBindingPy::setAutoApply(), Gui::View3DInventorPy::setCameraOrientation(), Gui::View3DInventorViewerPy::setEnabledNaviCube(), App::PropertyBool::setPyObject(), Gui::View3DInventorViewerPy::setRedirectToSceneGraph(), Gui::SelectionSingleton::sGetSelection(), Gui::SelectionSingleton::sGetSelectionEx(), Gui::SelectionSingleton::sHasSubSelection(), Gui::SelectionSingleton::sPushSelStack(), Gui::ApplicationPy::sSendActiveView(), Gui::ApplicationPy::sSendFocusView(), Gui::SelectionSingleton::sUpdateSelection(), and Gui::View3DInventorPy::toggleClippingPlane().
Assert()
void Base::Assert (int expr, char * msg) inline
Definition at line 108 of file PyObjectBase.h.
References Path.Op.Surface::msg.
base64_decode() [1/4]
std::string Base::base64_decode (std::string const & str) inline
Decode base64 string into binary data
Parameters
out adding new content.
str input base64 string
Returns
Return the decoded binary data.
Definition at line 153 of file Base64.h.
References base64_decode(), and Path.Post.scripts.refactored_centroid_post::str.
base64_decode() [2/4]
template<typename T > std::size_t Base::base64_decode (T & out, char const * in, std::size_t len) inline
Decode base64 string into binary data
Parameters
out output binary data. Note that the data is not cleared before adding new content.
in input base64 string
len input length
Returns
Return the processed input length. Compare this with the argument len to check for error.
Definition at line 126 of file Base64.h.
References base64_decode(), and base64_decode_size().
base64_decode() [3/4]
template<typename T > std::size_t Base::base64_decode (T & out, std::string const & str) inline
Decode base64 string into binary data
Parameters
out output binary data. Note that the data is not cleared before adding new content.
str input base64 string
Returns
Return the processed input length. Compare this with the argument len to check for error.
Definition at line 143 of file Base64.h.
References base64_decode(), and Path.Post.scripts.refactored_centroid_post::str.
base64_decode() [4/4]
std::pair< std::size_t, std::size_t > Base::base64_decode (void * out, char const * in, std::size_t len)
Decode the input base64 string into binary data
Parameters
out output buffer with minimum size of base64_encode(len) appending new data.
in input binary data
len input length
Returns
Return a pair of output size and input read size. Compare the read size to input size to check for error.
Definition at line 118 of file Base64.cpp.
References base64_decode_table().
Referenced by base64_decode(), Base::XMLReader::readBinFile(), and App::PropertyPythonObject::Restore().
base64_decode_size()
std::size_t Base::base64_decode_size (std::size_t len) inline
Returns the max bytes of a decoded base64 binary string.
Definition at line 57 of file Base64.h.
Referenced by base64_decode().
base64_decode_table()
std::array< const signed char, Base::base64DecodeTableSize > Base::base64_decode_table ()
Return the internal base64 decoding table
The table maps from any 8-bit character to the decoded binary bits. Valid base64 characters are mapped to the corresponding 6-bit binary data. White space (space, tab, vtab, CR and LF) characters are mapped to -2. Other invalid characters are mapped to -1.
Definition at line 48 of file Base64.cpp.
Referenced by base64_decode().
base64_encode() [1/3]
std::size_t Base::base64_encode (char * out, void const * in, std::size_t len)
Encode input binary with base64
Parameters
out output buffer with minimum size of base64_encode(len) appending new data.
in input binary data
len input length
Returns
The character count written to output.
Definition at line 71 of file Base64.cpp.
References base64_chars.
Referenced by base64_encode(), Base::base64_encoder::close(), Cloud::ComputeDigestAmzS3v2(), Base::Writer::insertBinFile(), Cloud::MD5Sum(), and App::PropertyPythonObject::Save().
base64_encode() [2/3]
void Base::base64_encode (std::string & out, void const * in, std::size_t len) inline
Encode input binary into base64 string
Parameters
out output string. Note that the string is not cleared before adding new content.
in input binary data
len input length
Definition at line 97 of file Base64.h.
References base64_encode(), and base64_encode_size().
base64_encode() [3/3]
std::string Base::base64_encode (void const * in, std::size_t len) inline
Encode input binary into base64 string
Parameters
in input binary data
len input length
Returns
Return the base64 string.
Definition at line 110 of file Base64.h.
References base64_encode().
base64_encode_size()
std::size_t Base::base64_encode_size (std::size_t len) inline
Returns the max bytes of a encoded base64 string.
Definition at line 51 of file Base64.h.
Referenced by base64_encode().
blanks()
manipulator<int> Base::blanks (int n) inline
Definition at line 120 of file Base/Tools.h.
blanksN()
std::ostream& Base::blanksN (std::ostream & os, int n) inline
Definition at line 107 of file Base/Tools.h.
Referenced by tabsN().
clamp()
template<class T > T Base::clamp (T num, T lower, T upper) inline
Definition at line 128 of file Base/Tools.h.
References M_PI.
Referenced by AdaptivePath::DistancePointToLineSegSquared(), AdaptivePath::Line2CircleIntersect(), and Gui::Dialog::DlgSettingsNavigation::loadSettings().
Console()
ConsoleSingleton& Base::Console () inline
Access to the Console This method is used to gain access to the one and only instance of the ConsoleSingleton class.
Definition at line 909 of file Console.h.
References Base::ConsoleSingleton::Instance().
Referenced by Attacher::AttachEngine3D::_calculateAttachedPlacement(), Attacher::AttachEngineLine::_calculateAttachedPlacement(), Gui::Command::_doCommand(), Part::TopoShape::_makeTransform(), Base::PyObjectBase::_repr(), PartGui::DlgScale::accept(), ReverseEngineeringGui::Segmentation::accept(), FemGui::TaskDlgMeshShapeNetgen::accept(), RobotGui::TaskDlgEdge2Trac::accept(), MeshGui::GmshWidget::accept(), FemGui::TaskDlgCreateNodeSet::accept(), FemGui::TaskDlgCreateElementSet::accept(), TechDrawGui::TaskCosmeticCircle::accept(), Gui::Dialog::DlgRevertToBackupConfigImp::accept(), MatGui::MaterialsEditor::accept(), TechDrawGui::TaskWeldingSymbol::accept(), FemGui::TaskDlgFemConstraintFluidBoundary::accept(), Gui::TaskView::TaskView::accept(), Gui::StdCmdDownloadOnlineHelp::activated(), CmdSandboxEventLoop::activated(), Gui::PythonCommand::activated(), CmdTestConsoleOutput::activated(), Gui::PythonGroupCommand::activated(), StdCmdViewIvIssueCamPos::activated(), Gui::Application::activateWorkbench(), TechDraw::CosmeticExtension::add1CEToGE(), TechDraw::CosmeticExtension::add1CVToGV(), Sketcher::Sketch::addAngleAtPointConstraint(), Materials::Material::addAppearance(), TechDraw::CosmeticExtension::addCenterLinesToGeom(), Sketcher::Sketch::addConstraints(), Sketcher::SketchObject::addCopy(), Sketcher::Sketch::addEqualConstraint(), Sketcher::SketchObject::addExternal(), Sketcher::Sketch::addPerpendicularConstraint(), Materials::Material::addPhysical(), TechDraw::DrawProjGroup::addProjection(), TechDrawGui::QGSPage::addQView(), Sketcher::Sketch::addSnellsLawConstraint(), Sketcher::Sketch::addTangentConstraint(), Sketcher::Sketch::addTangentLineAtBSplineKnotConstraint(), Sketcher::Sketch::addTangentLineEndpointAtBSplineKnotConstraint(), Gui::CommandManager::addTo(), Materials::MaterialYamlEntry::addToTree(), TechDraw::DrawPage::addView(), Sketcher::SketchAnalysis::analyseMissingPointOnPointCoincident(), TechDraw::DrawUtil::angleWithX(), TechDraw::AOE::AOE(), TechDraw::DrawUtil::apparentIntersection(), PartDesignGui::TaskFilletParameters::apply(), PartDesignGui::TaskDraftParameters::apply(), PartDesignGui::TaskChamferParameters::apply(), PartDesignGui::TaskThicknessParameters::apply(), TechDrawGui::TaskSectionView::apply(), TechDrawGui::TaskComplexSection::apply(), Gui::PreferencePack::apply(), Gui::Dialog::PlacementHandler::applyPlacement(), TechDraw::DrawViewDimension::arcPointsFromBaseGeom(), Measure::Measurement::area(), TechDraw::DrawProjGroup::arrangeViewPointers(), MatGui::Array2D::Array2D(), MatGui::Array3D::Array3D(), TechDrawGui::ViewProviderDrawingView::attach(), Base::Subject< const char * >::Attach(), Sketcher::SketchAnalysis::autoconstraint(), Gui::Gui::GestureNavigationStyle ::AwaitingMoveState::AwaitingMoveState(), Gui::Gui::GestureNavigationStyle ::AwaitingReleaseState::AwaitingReleaseState(), TechDraw::BaseGeom::baseFactory(), buildAdapter(), PartDesignGui::TaskFeaturePick::buildFeatures(), TechDrawGui::QGIFace::buildPixHatch(), TechDrawGui::QGIFace::buildSvgHatch(), Gui::PropertyEditor::PropertyEditor::buildUp(), TechDraw::CenterLine::calcEndPoints(), TechDraw::CenterLine::calcEndPoints2Lines(), TechDraw::CenterLine::calcEndPoints2Points(), TechDrawGui::TaskRichAnno::calcTextStartPos(), SketcherGui::ViewProviderSketch::camSensCB(), Gui::MacroManager::cancel(), TechDraw::DrawProjGroup::canDelete(), Gui::ViewProvider::canDropObject(), Sketcher::SketchObject::carbonCopy(), TechDraw::CenterLine::CenterLineBuilder(), Sketcher::SketchObject::changeConstraintsLocking(), PartDesignGui::TaskHoleParameters::changedObject(), SurfaceGui::GeomFillSurface::changeFillType(), ParameterManager::CheckDocument(), Gui::Application::checkForDeprecatedSettings(), Gui::Dialog::DocumentRecoveryHandler::checkForPreviousCrashes(), Gui::Application::checkForPreviousCrashes(), Part::ExtrusionHelper::checkInnerWires(), TechDraw::ShapeExtractor::checkShape(), App::DocumentP::checkStringHasher(), FemGui::TaskDlgMeshShapeNetgen::clicked(), RobotGui::TaskDlgEdge2Trac::clicked(), TechDraw::CosmeticEdge::clone(), Cloud::Module::cloudRestore(), Gui::cmdAppObjectShow(), Gui::MacroManager::commit(), TechDraw::BaseGeom::completeEdge(), SpreadsheetGui::SheetView::confirmAliasChanged(), Base::ConsoleObserverFile::ConsoleObserverFile(), Base::ConsoleRefreshDisabler::ConsoleRefreshDisabler(), TechDrawGui::QGIViewDimension::constructDimensionArc(), TechDrawGui::QGIViewDimension::constructDimensionLine(), Sketcher::SketchObject::convertToNURBS(), App::PropertyFileIncluded::Copy(), TechDraw::DrawUtil::copyFile(), TechDraw::DrawUtil::countEdges(), TechDraw::DrawUtil::countFaces(), TechDraw::DrawUtil::countWires(), Gui::PythonCommand::createAction(), Gui::PythonGroupCommand::createAction(), TechDrawGui::TaskActiveView::createActiveView(), TechDrawGui::QGISVGTemplate::createClickHandles(), ParameterGrp::CreateElement(), Materials::MaterialLibrary::createFolder(), PartGui::ViewProvider2DObjectGrid::createGrid(), TechDrawGui::TaskHatch::createHatch(), FemGui::ViewProviderFEMMeshBuilder::createMesh(), Gui::DocumentItem::createNewItem(), Fem::createObjectByType(), Gui::WidgetFactoryInst::createPreferencePage(), Gui::WidgetFactoryInst::createPrefWidget(), Part::ExtrusionHelper::createTaperedPrismOffset(), Gui::WidgetFactoryInst::createWidget(), MeshGui::ViewProviderMeshCurvature::curvatureInfoCallback(), SketcherGui::CurveConverter::CurveConverter(), Base::ConsoleOutput::customEvent(), TechDrawGui::PATPathMaker::dashedPPath(), Gui::Dialog::ButtonModel::data(), MatGui::Array3DModel::data(), debugprint(), Sketcher::SketchObject::decreaseBSplineDegree(), FemGui::TaskCreateElementSet::DefineNodes(), Sketcher::SketchObject::delAllExternal(), Materials::MaterialLibrary::deleteFile(), SketcherGui::ViewProviderSketch::deleteSelected(), Measure::Measurement::delta(), Materials::MaterialLoader::dereference(), App::Application::destruct(), App::Application::destructObserver(), Base::Subject< const char * >::Detach(), SketcherGui::EditModeConstraintCoinManager::detectPreselectionConstr(), GCS::System::diagnose(), PartGui::ViewProviderPart::doubleClicked(), MeshGui::ViewProviderMeshTransformDemolding::DragEndCallback(), TechDrawGui::QGILeaderLine::draw(), TechDrawGui::QGIViewDimension::draw(), TechDrawGui::QGIViewPart::drawAllEdges(), TechDrawGui::QGIViewDimension::drawAngle(), TechDrawGui::QGIViewAnnotation::drawAnnotation(), TechDrawGui::QGIViewDimension::drawAreaExecutive(), TechDrawGui::QGIViewClip::drawClip(), TechDrawGui::QGIViewPart::drawComplexSectionLine(), SketcherGui::EditModeConstraintCoinManager::drawConstraintIcons(), TechDrawGui::QGIViewDimension::drawDiameter(), TechDrawGui::QGIViewDimension::drawDistanceExecutive(), TechDrawGui::QGIViewDimension::drawDistanceOverride(), TechDrawGui::QGIViewDimension::drawRadiusExecutive(), TechDrawGui::QGIViewSection::drawSectionFace(), TechDrawGui::QGIViewPart::drawSectionLine(), TechDrawGui::QGIWeldSymbol::drawTile(), TechDraw::CosmeticVertex::dump(), TechDraw::DashSpec::dump(), TechDraw::CosmeticEdge::dump(), TechDraw::LineGroup::dump(), TechDraw::PATLineSpec::dump(), TechDraw::pointPair::dump(), TechDraw::LineFormat::dump(), TechDraw::GeomFormat::dump(), TechDraw::anglePoints::dump(), TechDraw::CenterLine::dump(), TechDraw::arcPoints::dump(), TechDraw::areaPoint::dump(), TechDraw::Vertex::dump(), TechDraw::DrawUtil::dump1Vertex(), TechDraw::DrawViewPart::dumpCosEdges(), TechDraw::DrawViewPart::dumpCosVerts(), TechDraw::DrawUtil::dumpCS(), TechDraw::DrawUtil::dumpCS3(), TechDraw::DrawUtil::dumpEdge(), TechDraw::DrawUtil::dumpEdges(), TechDrawGui::QGEPath::dumpGhostPoints(), TechDraw::DrawProjGroup::dumpISO(), TechDrawGui::QGEPath::dumpMarkerPos(), TechDrawGui::QGIViewPart::dumpPath(), TechDrawGui::DrawGuiUtil::dumpPointF(), TechDrawGui::QGIView::dumpRect(), TechDrawGui::DrawGuiUtil::dumpRectF(), TechDrawGui::TaskLeaderLine::dumpTrackerPoints(), TechDraw::DrawUtil::dumpVertexes(), TechDraw::DrawProjectSplit::dumpVertexMap(), TechDraw::DrawViewPart::dumpVerts(), TechDraw::DrawLeaderLine::dumpWaypoints(), TechDrawGui::TaskDetail::editByHighlight(), SketcherGui::ViewProviderSketch::editDoubleClicked(), TechDraw::Ellipse::Ellipse(), Gui::Translator::enableDecimalPointConversion(), Gui::ViewProvider::eventCallback(), Gui::ViewerEventFilter::eventFilter(), Base::Debugger::exec(), TechDraw::DrawViewMulti::execute(), Part::ImportBrep::execute(), Part::CurveNet::execute(), Part::ImportIges::execute(), Part::ImportStep::execute(), Sketcher::SketchObjectSF::execute(), Drawing::FeaturePage::execute(), Fem::FemMeshShapeNetgenObject::execute(), Sandbox::SandboxObject::execute(), TechDraw::DrawBrokenView::execute(), TechDraw::DrawViewArch::execute(), TechDraw::DrawViewSection::execute(), TechDraw::DrawViewDimension::execute(), TechDraw::DrawViewPart::execute(), PartDesign::Transformed::execute(), Spreadsheet::Sheet::execute(), Inspection::Feature::execute(), SpreadsheetGui::ViewProviderSheet::exportAsFile(), Import::ImpExpDxfWrite::exportBCurve(), Import::ImpExpDxfWrite::exportBSpline(), Fem::FemVTKTools::exportFreeCADResult(), Import::ImpExpDxfWrite::exportShape(), Gui::ViewProviderGroupExtension::extensionCanDropObject(), Part::AttachExtension::extensionOnChanged(), TechDraw::GeometryObject::extractGeometry(), MeshGui::ViewProviderMesh::faceInfo(), MeshGui::ViewProviderMesh::faceInfoCallback(), FC_LOG_LEVEL_INIT(), StartGui::StartView::fileCardSelected(), PartDesignGui::TaskTransformedParameters::fillAxisCombo(), Sketcher::SketchObject::fillet(), MeshGui::ViewProviderMesh::fillHoleCallback(), PartDesignGui::TaskTransformedParameters::fillPlanesCombo(), MeshCore::MeshAlgorithm::FillupHole(), MeshCore::MeshTopoAlgorithm::FillupHoles(), TechDraw::DrawDimHelper::findClosestPoint(), ParameterGrp::FindElement(), TechDraw::BaseGeom::findEndPoints(), TechDraw::DrawViewPart::findFacesNew(), TechDraw::DrawViewPart::findFacesOld(), TechDrawGui::QGIViewDimension::findIsoExt(), TechDraw::DrawComplexSection::findSectionPlaneIntersections(), TechDraw::DrawViewSection::findSectionPlaneIntersections(), MeshCore::CylinderFit::Fit(), MeshCore::SphereFit::Fit(), TechDraw::DimensionFormatter::formatValue(), MeshGui::SoFCMeshObjectShape::generatePrimitives(), MeshGui::SoFCMeshSegmentShape::generatePrimitives(), Assembly::AssemblyObject::generateSimulation(), TechDrawGui::PathBuilder::geomToPainterPath(), Gui::Gui::GestureNavigationStyle ::GestureState::GestureState(), TechDrawGui::TaskDetail::getAnchorScene(), Path::Toolpath::getCycleTime(), TechDraw::DrawGeomHatch::getDecodedSpecsFromFile(), TechDraw::DrawViewDimension::getDimValue(), TechDraw::DrawProjGroup::getDirsFromFront(), TechDraw::DrawViewPart::getDirsFromFront(), Gui::Dialog::DlgSettingsWorkbenchesImp::getDisabledWorkbenches(), TechDraw::DrawProjectSplit::getEdgesForWalker(), Gui::Dialog::DlgSettingsWorkbenchesImp::getEnabledWorkbenches(), TechDraw::BaseGeom::getEndPoint(), MeshGui::ViewProviderMesh::getFacetsFromPolygon(), TechDraw::LineGroup::getGroupNamesFromFile(), TechDraw::LineGenerator::getLineDescriptions(), getLocatedShape(), Materials::Material::getMaterialAppearance(), Materials::MaterialConfigLoader::getMaterialFromPath(), Materials::MaterialLoader::getMaterialFromYAML(), Materials::MaterialLoader::getMaterialLibraries(), Measure::MeasureBaseExtendable< Part::MeasureAreaInfo >::getMeasureInfo(), Fem::FemMesh::getNodesBySolid(), Gui::PreferencePackManager::getPacksFromDirectory(), MeshGui::CylinderFitParameter::getParameter(), TechDraw::PATLineSpec::getPatternList(), CDxfWrite::getPlateFile(), TechDraw::DimensionFormatter::getPrefixSuffixSpec(), TechDrawGui::DrawGuiUtil::getProjDirFromFace(), TechDraw::DrawViewPart::getProjectionCS(), TechDraw::DrawProjGroup::getProjItem(), TechDraw::DrawProjGroup::getProjObj(), Assembly::AssemblyObject::getRackPinionMarkers(), TechDraw::LineGroup::getRecordFromFile(), TechDraw::DrawViewDimension::getRefType(), TechDraw::DrawViewDimension::getSavedBox(), TechDraw::DrawViewSection::getSectionCS(), TechDraw::ShapeExtractor::getShapeFromXLink(), TechDraw::ShapeExtractor::getShapesFused(), TechDraw::DrawViewSection::getShapeToCut(), TechDraw::DrawViewSpreadsheet::getSheetImage(), TechDraw::PATLineSpec::getSpecsForPattern(), TechDraw::BaseGeom::getStartPoint(), Sketcher::SketchObject::getSymmetric(), TechDraw::DrawSVGTemplate::getTemplateDocument(), MeasureGui::ViewProviderMeasureBase::getTextDirection(), MeasureGui::ViewProviderMeasure::getTextPosition(), AttacherGui::getUIStrings(), TechDraw::DrawViewPart::getViewAxis(), TechDraw::DrawProjGroup::getViewIndex(), Gui::View3DInventorViewer::getViewProviderByPath(), Gui::View3DInventorViewer::getViewProviderByPathFromTail(), Gui::View3DInventorViewer::getViewProvidersOfType(), MeasureGui::ViewProviderMeasureBase::getViewScale(), TechDrawGui::QGILeaderLine::getWayPointsFromFeature(), TechDraw::DrawUtil::getWidthInDirection(), TechDraw::DrawProjGroupItem::getXDirection(), TechDraw::ShapeExtractor::getXShapes(), PartGui::ViewProviderCurveNet::handleEvent(), Assembly::AssemblyObject::handleOneSideOfJoint(), TechDraw::DrawProjGroup::hasProjection(), Gui::Gui::GestureNavigationStyle ::IdleState::IdleState(), MatGui::ImageEdit::ImageEdit(), Gui::View3DInventorViewer::imageFromFramebuffer(), Base::Type::importModule(), Part::ImportStepParts(), Fem::FemVTKTools::importVTKMesh(), Sketcher::SketchObject::increaseBSplineDegree(), Gui::View3DInventorViewer::init(), Gui::Application::initApplication(), AssemblyGui::ViewProviderAssembly::initMove(), Gui::GuiNativeEvent::initSpaceball(), TechDrawGui::TaskGeomHatch::initUi(), Sketcher::SketchObject::insertBSplineKnot(), InspectionGui::ViewProviderInspection::inspectCallback(), Gui::Gui::GestureNavigationStyle ::InteractState::InteractState(), TechDraw::DrawUtil::Intersect2d(), TechDraw::DrawUtil::intersect2Lines3d(), Gui::Command::invoke(), TechDraw::DrawBrokenView::isBreakObjectSketch(), Sketcher::SketchObject::isCarbonCopyAllowed(), ModelRefine::FaceTypedBSpline::isEqual(), Sketcher::SketchObject::isExternalAllowed(), TechDraw::DrawProjectSplit::isOnEdge(), TechDraw::DrawLeaderLine::isParentReady(), MeasureGui::ViewProviderMeasureBase::isSubjectVisible(), TechDraw::DimensionFormatter::isTooSmall(), TechDraw::isValidSingleFace3d(), Measure::Measurement::length(), Base::LogLevel::level(), TechDraw::LineGroup::lineGroupFactory(), Measure::Measurement::lineLineDistance(), TechDrawGui::PATPathMaker::lineSetToFillItems(), MatGui::ListEdit::ListEdit(), TechDraw::PATLineSpec::load(), Fem::FemPostPipeline::load(), Mesh::MeshObject::load(), MeshCore::MeshInput::LoadAny(), Start::ExamplesModel::loadExamples(), MeshCore::MeshInput::LoadNastran(), TechDraw::DrawViewSymbol::loadQDomDocument(), TechDrawGui::QGIFace::loadSvgHatch(), loadTechDrawResource(), Gui::MainWindow::loadUrls(), Gui::Gui::GestureNavigationStyle ::Event::log(), GCS::SolverReportingManager::LogToConsole(), PartDesignGui::TaskSketchBasedParameters::make2DLabel(), TechDraw::DrawComplexSection::makeCuttingTool(), TechDraw::DrawViewDetail::makeDetailShape(), TechDraw::DrawViewSection::makeFaceFromWires(), TechDraw::DrawLeaderLine::makeLeader(), TechDraw::DrawViewSection::makeLineSets(), Part::TopoShape::makeLoft(), TechDraw::GeometryUtils::makePerforatedFace(), TechDraw::DrawComplexSection::makeSectionCut(), TechDraw::DrawViewSection::makeSectionCut(), TechDraw::DrawComplexSection::makeSectionLineWire(), TechDrawGui::QGITile::makeSymbol(), MeshPart::CurveProjectorWithToolMesh::makeToolMesh(), TechDraw::DrawViewSection::mapToPage(), MeshGui::ViewProviderMesh::markPartCallback(), TechDraw::DrawUtil::maskDirection(), Measure::Measurement::massCenter(), MeasureAngleHandler(), MeasureAreaHandler(), MeasureDistanceHandler(), MeasureLengthHandler(), MeasurePositionHandler(), messageHandler(), Sketcher::SketchObject::migrateSketch(), Sketcher::SketchObject::modifyBSplineKnotMultiplicity(), AssemblyGui::ViewProviderAssembly::mouseMove(), Base::Observer< const char * >::Name(), Part::Scale::nonuniformScale(), NotificationAreaObserver::NotificationAreaObserver(), Gui::GUIApplication::notify(), Gui::Notify(), Gui::SelectionSingleton::notify(), MatGui::MaterialsEditor::onAppearanceAdd(), PartGui::SectionCut::onBFragTransparencyHSMoved(), SketcherGui::ViewProviderSketch::onCameraChanged(), PartDesignGui::ViewProviderBody::onChanged(), Sandbox::SandboxObject::onChanged(), Fem::ConstraintFluidBoundary::onChanged(), TechDraw::DrawPage::onChanged(), App::Document::onChanged(), Sketcher::SketchObject::onChanged(), PartGui::SectionCut::onCutXvalueChanged(), PartGui::SectionCut::onCutYvalueChanged(), PartGui::SectionCut::onCutZvalueChanged(), AssemblyGui::ViewProviderAssemblyLink::onDelete(), SketcherGui::ViewProviderSketch::onDelete(), PartDesignGui::TaskExtrudeParameters::onDirectionCBChanged(), TechDrawGui::TaskDetail::onHighlightMoved(), TechDraw::DrawViewPart::onHlrFinished(), Gui::Application::onLastWindowClosed(), MatGui::MaterialsEditor::onPhysicalAdd(), Import::ImpExpDxfRead::OnReadArc(), Import::ImpExpDxfRead::OnReadCircle(), Import::ImpExpDxfRead::OnReadEllipse(), Import::ImpExpDxfRead::OnReadSpline(), PartGui::SectionCut::onRefreshCutPBclicked(), Gui::Document::onRelabel(), Gui::GestureNavigationStyle::onRollGesture(), FemGui::TaskCreateNodeSet::onSelectionChanged(), MatGui::MaterialsEditor::onSelectMaterial(), Gui::PropertyView::onTimer(), TechDrawGui::TaskLeaderLine::onTrackerClicked(), TechDrawGui::TaskCosVertex::onTrackerFinished(), TechDrawGui::TaskLeaderLine::onTrackerFinished(), Gui::View3DInventor::onUpdate(), Gui::Document::onUpdate(), Gui::MacroManager::open(), App::Application::openDocuments(), Gui::Gui::GestureNavigationStyle ::PanState::PanState(), PartMeasureTypeCb(), MeshGui::ViewProviderMesh::partMeshCallback(), Gui::VectorTableModel::pasteFromClipboard(), Gui::BitmapFactoryInst::pixmap(), FemGui::TaskPostDataAlongLine::pointCallback(), FemGui::TaskPostDataAtPoint::pointCallback(), Sketcher::SketchObject::port_reversedExternalArcs(), MeasureGui::ViewProviderMeasure::positionAnno(), Gui::GestureNavigationStyle::EventQueue::post(), TechDrawGui::QGSPage::postProcessXml(), Gui::Dialog::PreferenceUiForm::PreferenceUiForm(), TechDraw::DrawViewSection::prepareShape(), Gui::Command::printConflictingAccelerators(), Import::Tools::printLabel(), TechDrawGui::PagePrinter::printPdf(), printPlacement(), MeshPartGui::Tessellation::process(), App::Application::processCmdLineFiles(), SketcherGui::EditModeConstraintCoinManager::processConstraints(), App::Application::processFiles(), Base::ScriptFactorySingleton::ProduceScript(), MeshPart::CurveProjectorShape::projectCurve(), MeshPart::CurveProjectorSimple::projectCurve(), MeshPart::MeshProjection::projectEdgeToEdge(), TechDraw::GeometryObject::projectShape(), TechDraw::GeometryObject::projectShapeWithPolygonAlgo(), TechDraw::DrawProjGroup::purgeProjections(), PyMOD_INIT_FUNC(), Base::PyObjectBase::PyObjectBase(), TechDrawGui::Grabber3d::quickView(), Measure::Measurement::radius(), Gui::Gui::GestureNavigationStyle ::GestureState::react(), TestJtReader::read(), Base::XMLReader::readFiles(), App::Document::readObjects(), App::Document::recompute(), MeasureGui::ViewProviderMeasureAngle::redrawAnnotation(), PartDesign::FeatureAddSub::refineShapeIfActive(), Gui::TaskView::TaskView::reject(), TechDraw::DrawProjectSplit::removeDuplicateEdges(), TechDrawGui::TaskRichAnno::removeFeature(), TechDrawGui::TaskLeaderLine::removeFeature(), Materials::Material::removePhysical(), TechDraw::DrawProjGroup::removeProjection(), Materials::MaterialLibrary::renameFolder(), Base::PyException::ReportException(), Gui::DockWnd::ReportOutput::ReportOutput(), Gui::View3DInventorViewer::resetEditingRoot(), Sandbox::SandboxObject::resetValue(), App::PropertyPythonObject::Restore(), TechDraw::PropertyCenterLineList::Restore(), TechDraw::CosmeticEdge::Restore(), TechDraw::PropertyGeomFormatList::Restore(), TechDraw::PropertyCosmeticEdgeList::Restore(), TechDraw::PropertyCosmeticVertexList::Restore(), Part::PropertyGeometryList::Restore(), TechDraw::CenterLine::Restore(), Part::Geometry::Restore(), App::Document::restore(), App::PropertyContainer::Restore(), App::PropertyEnumeration::Restore(), App::Document::Restore(), App::PropertyLink::Restore(), App::PropertyLinkSubList::Restore(), Fem::PropertyPostDataObject::RestoreDocFile(), Gui::Document::RestoreDocFile(), App::ExtensionContainer::restoreExtensions(), Gui::MainWindowP::restoreWindowState(), Part::TopoShape::revolve(), Gui::Gui::GestureNavigationStyle ::RotateState::RotateState(), TechDrawGui::QGIProjGroup::rotateView(), Sandbox::PythonThread::run(), Sandbox::DocumentTestThread::run(), BarThread::run(), MeshTestJob::run(), Gui::ConsoleMessageTask::run(), Gui::ConsoleWarningTask::run(), Gui::ConsoleErrorTask::run(), Gui::ConsoleLogTask::run(), Gui::ConsoleCriticalTask::run(), Gui::Application::runApplication(), App::Application::runApplication(), Gui::PythonDebugger::runFile(), TechDraw::CosmeticEdge::Save(), MeshCore::WriterOBJ::Save(), TechDraw::CenterLine::Save(), App::PropertyContainer::Save(), Fem::PropertyPostDataObject::SaveDocFile(), Gui::AutoSaver::saveDocument(), App::ExtensionContainer::saveExtensions(), Materials::MaterialLibrary::saveMaterial(), Materials::Material::saveModels(), MeshCore::MeshOutput::SaveOFF(), TechDrawGui::PagePrinter::saveSVG(), Base::Builder3D::saveToLog(), TechDraw::CenterLine::scaledAndRotatedGeometry(), TechDraw::CenterLine::scaledGeometry(), TechDraw::DrawProjectSplit::scrubEdges(), TechDraw::DrawViewSection::sectionExec(), MeshGui::ViewProviderMesh::segmMeshCallback(), Gui::Application::setActiveDocument(), SIM::Coin3D::Quarter::SoQTQuarterAdaptor::setCameraType(), Gui::ViewProviderTextureExtension::setCoinAppearance(), Sketcher::SketchObject::setConstraintExpression(), MatGui::Array3DModel::setData(), AssemblyGui::ViewProviderAssemblyLink::setEdit(), TechDrawGui::ViewProviderViewPart::setEdit(), SketcherGui::ViewProviderSketch::setEdit(), SketcherGui::ViewProviderSketch::setEditViewer(), Gui::EditableDatumLabel::setFocusToSpinbox(), Sandbox::SandboxObject::setIntValue(), Gui::Translator::setLocale(), Gui::PrefWidget::setParamGrpPath(), TechDrawGui::QGTracker::setPoint(), Gui::PropertyEditor::PropertyItem::setPropertyValue(), Gui::EditableDatumLabel::setSpinboxValue(), Gui::ViewProviderCoordinateSystem::setTemporaryVisibility(), Sketcher::Sketch::setUpSketch(), Materials::MaterialProperty::setValue(), Gui::ApplicationPy::sExport(), TechDrawGui::QGEPath::showMarkers(), TechDrawGui::ViewProviderDrawingView::showProgressMessage(), Materials::MaterialLoader::showYaml(), TechDraw::DrawUtil::simpleMinDist(), Gui::ApplicationPy::sInsert(), Gui::Application::slotDeleteDocument(), Gui::SelectionSingleton::slotSelectionChanged(), Sketcher::Sketch::solve(), Sketcher::SketchObject::solve(), Gui::ApplicationPy::sOpen(), TechDraw::EdgeWalker::sortStrip(), Gui::SplashObserver::SplashObserver(), TechDraw::LineGroup::split(), TechDraw::DrawProjectSplit::split1Edge(), Gui::ApplicationPy::sSendActiveView(), Gui::ApplicationPy::sSendFocusView(), Gui::NetworkRetriever::startDownload(), FcLodHandler::startLod(), Gui::GUISingleApplication::Private::startServer(), Gui::StatusBarObserver::StatusBarObserver(), Gui::Gui::GestureNavigationStyle ::StickyPanState::StickyPanState(), TechDrawGui::QGIViewSymbol::symbolToSvg(), Base::RedirectStdOutput::sync(), Base::RedirectStdError::sync(), Base::RedirectStdLog::sync(), MeshPart::MeshingOutput::sync(), PartDesignGui::TaskBoxPrimitives::TaskBoxPrimitives(), TechDrawGui::TaskCenterLine::TaskCenterLine(), TechDrawGui::TaskCosmeticCircle::TaskCosmeticCircle(), TechDrawGui::TaskCosmeticLine::TaskCosmeticLine(), TechDrawGui::TaskDetail::TaskDetail(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), FemGui::TaskPostScalarClip::TaskPostScalarClip(), FemGui::TaskPostWarpVector::TaskPostWarpVector(), TechDrawGui::TaskRichAnno::TaskRichAnno(), Gui::TaskView::TaskSelectLinkProperty::TaskSelectLinkProperty(), TechDrawGui::TaskWeldingSymbol::TaskWeldingSymbol(), MatGui::TextEdit::TextEdit(), TechDrawGui::QGIFace::textureFromBitmap(), Gui::Gui::GestureNavigationStyle ::TiltState::TiltState(), Gui::AutoSaver::timerEvent(), App::PropertyPythonObject::toString(), SpaceNavigatorDevice::translateEvent(), MeshCore::AbstractPolygonTriangulator::TriangulatePolygon(), SketcherGui::ViewProviderSketch::unsetEdit(), TechDraw::DrawProjGroupItem::unsetupObject(), TechDraw::DrawPage::unsetupObject(), Gui::TaskMeasure::update(), PartDesign::SubShapeBinder::update(), PartDesignGui::ViewProviderAddSub::updateAddSubShapeIndicator(), TechDraw::DrawProjGroup::updateChildrenEnforce(), TechDraw::DrawProjGroup::updateChildrenLock(), TechDraw::DrawProjGroup::updateChildrenSource(), Gui::ViewProviderVRMLObject::updateData(), PartGui::ViewProviderCurveNet::updateData(), FemGui::ViewProviderFemConstraintBearing::updateData(), TechDrawGui::TaskDetail::updateDetail(), MatGui::MaterialTreeWidget::updateMaterial(), TechDraw::DrawProjGroup::updateSecondaryDirs(), TechDrawGui::TaskWeldingSymbol::updateTiles(), TechDrawGui::QGILeaderLine::updateView(), TechDrawGui::QGIWeldSymbol::updateView(), PartGui::ViewProviderPartExt::updateVisual(), Sketcher::SketchObject::validateExternalLinks(), Assembly::AssemblyObject::validateNewPlacements(), Gui::Application::viewActivated(), Measure::Measurement::volume(), TechDrawGui::PreferencesGui::weldingDirectory(), Gui::OutputStdout::write(), Gui::OutputStderr::write(), Gui::PythonDebugStderr::write(), Fem::FemMesh::write(), Fem::FemMesh::writeZ88(), Gui::GuiNativeEvent::xcbEventFilter(), Gui::Application::~Application(), Base::ConsoleRefreshDisabler::~ConsoleRefreshDisabler(), PartGui::DlgProjectionOnSurface::~DlgProjectionOnSurface(), DocOpenGuard::~DocOpenGuard(), TechDraw::DrawViewDetail::~DrawViewDetail(), TechDraw::DrawViewPart::~DrawViewPart(), TechDraw::DrawViewSection::~DrawViewSection(), App::FeatureTestAttribute::~FeatureTestAttribute(), Gui::GuiNativeEvent::~GuiNativeEvent(), NotificationAreaObserver::~NotificationAreaObserver(), Base::PyObjectBase::~PyObjectBase(), Gui::DockWnd::ReportOutput::~ReportOutput(), Gui::SplashObserver::~SplashObserver(), Gui::StatusBarObserver::~StatusBarObserver(), PartDesignGui::TaskBoxPrimitives::~TaskBoxPrimitives(), PartDesignGui::TaskLinearPatternParameters::~TaskLinearPatternParameters(), PartDesignGui::TaskMirroredParameters::~TaskMirroredParameters(), PartDesignGui::TaskPolarPatternParameters::~TaskPolarPatternParameters(), and App::Application::TransactionSignaller::~TransactionSignaller().
convertTo()
template<class Vec1 , class Vec2 > Vec1 Base::convertTo (const Vec2 & vec) inline
Definition at line 140 of file Converter.h.
convertTo< Base::Matrix4D, SbMatrix >()
template<> Base::Matrix4D Base::convertTo< Base::Matrix4D, SbMatrix > (const SbMatrix & vec2) inline
Definition at line 120 of file Gui/Utilities.h.
References SplineSurface::i.
convertTo< SbMatrix, Base::Matrix4D >()
template<> SbMatrix Base::convertTo< SbMatrix, Base::Matrix4D > (const Base::Matrix4D & vec2) inline
Definition at line 109 of file Gui/Utilities.h.
create_base64_decoder() [1/2]
std::unique_ptr<std::istream> Base::create_base64_decoder (const std::string & filepath, std::size_t line_size = base64DefaultBufferSize, Base64ErrorHandling errHandling = Base64ErrorHandling::silent) inline
Create an input stream that can transform base64 into binary
Parameters
filepath input file.
ending optional ending character. If non zero, the filter will signal EOF when encounter this character.
putback if true and the filter read the ending character it will put it back into upstream
line_size line size of the encoded base64 string. This is used just as a suggestion for better buffering.
silent whether to throw on invalid non white space character.
Returns
A unique pointer to an input stream that read from the given file and transform the read base64 strings into binary data.
Definition at line 343 of file Base64Filter.h.
create_base64_decoder() [2/2]
std::unique_ptr<std::istream> Base::create_base64_decoder (std::istream & in, std::size_t line_size = base64DefaultBufferSize, Base64ErrorHandling errHandling = Base64ErrorHandling::silent) inline
Create an input stream that can transform base64 into binary
Parameters
in input upstream.
line_size line size of the encoded base64 string. This is used just as a suggestion for better buffering.
silent whether to throw on invalid non white space character.
Returns
A unique pointer to an input stream that read from the given upstream and transform the read base64 strings into binary data.
Definition at line 317 of file Base64Filter.h.
create_base64_encoder() [1/2]
std::unique_ptr<std::ostream> Base::create_base64_encoder (const std::string & filepath, std::size_t line_size = base64DefaultBufferSize) inline
Create an output stream that stores the input binary data to file as base64 strings
Parameters
filename the output file path
line_size line size of the base64 string. Zero to disable segmenting.
Returns
A unique pointer to an output stream that can transforms the input binary data to base64 strings.
Definition at line 297 of file Base64Filter.h.
create_base64_encoder() [2/2]
std::unique_ptr<std::ostream> Base::create_base64_encoder (std::ostream & out, std::size_t line_size = base64DefaultBufferSize) inline
Create an output stream that transforms the input binary data to base64 strings
Parameters
out the downstream output stream that will be fed with base64 string
line_size line size of the base64 string. Zero to disable segmenting.
Returns
A unique pointer to an output stream that can transforms the input binary data to base64 strings.
Definition at line 279 of file Base64Filter.h.
Referenced by Base::Writer::beginCharStream().
Distance()
template<class float_type > float_type Base::Distance (const Vector3< float_type > & v1, const Vector3< float_type > & v2) inline
Returns the distance between two points.
Definition at line 263 of file Vector3D.h.
References KDL::sqrt(), draftgeoutils.general::v1(), MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by MeshCore::MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection(), MeshCore::MeshGeomFacet::AspectRatio2(), MeshCore::MeshGeomFacet::CenterOfInscribedCircle(), MeshCore::MeshAlgorithm::ConnectPolygons(), cos_maxangle(), MeshCore::MeshEvalDegeneratedFacets::CountEdgeTooSmall(), MeshCore::MeshRemoveNeedles::Fixup(), MeshCore::MeshFixCaps::Fixup(), MeshCore::MeshAlgorithm::GetAverageEdgeLength(), MeshCore::MeshRefPointToPoints::GetAverageEdgeLength(), Inspection::InspectNominalPoints::getDistance(), MeshCore::SphereSurfaceFit::GetDistanceToSurface(), MeshCore::AbstractPolygonTriangulator::GetLength(), MeshCore::MeshAlgorithm::GetMaximumEdgeLength(), MeshCore::MeshAlgorithm::GetMinimumEdgeLength(), MeshGui::CylinderFitParameter::getParameter(), MeshCore::MeshGeomEdge::IntersectWithLine(), MeshCore::MeshGeomEdge::IsPointOf(), MeshCore::MeshAlgorithm::IsVertexVisible(), Base::Line3< float >::Length(), MeshPart::CurveProjectorWithToolMesh::makeToolMesh(), MeshCore::MeshGeomFacet::NearestEdgeToPoint(), MeshPart::MeshProjection::projectEdgeToEdge(), and MeshCore::MeshTopoAlgorithm::SplitFacet().
DistanceP2()
template<class float_type > float_type Base::DistanceP2 (const Vector3< float_type > & v1, const Vector3< float_type > & v2) inline
Returns the squared distance between two points.
Definition at line 273 of file Vector3D.h.
References draftgeoutils.general::v1(), MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by MeshCore::MeshSearchNeighbours::AccumulateNeighbours(), SketcherGui::calculateAngle(), MeshCore::MeshSearchNeighbours::CheckDistToFacet(), MeshCore::MeshProjection::connectLines(), MeshCore::MeshIntersection::connectLines(), MeshCore::MeshAlgorithm::ConnectLines(), MeshCore::MeshTopoAlgorithm::DelaunayFlip(), Base::Vector3< float >::DistanceToLineSegment(), Sketcher::SketchObject::GeoHistory::find(), Fem::FemMesh::getNodesByVertex(), MeshCore::MeshGrid::Inside(), Points::PointsGrid::InSide(), MeshCore::MeshGeomEdge::IsPointOf(), MeshCore::MeshGeomFacet::IsPointOfSphere(), Part::GeomPoint::isSame(), Part::GeomConic::isSame(), Part::GeomLine::isSame(), Part::GeomElementarySurface::isSame(), MeshCore::MeshSearchNeighbours::NeighboursFacetFromFacet(), MeshCore::MeshRefNormalToPoints::Rebuild(), MeshCore::MeshRefPointToFacets::SearchNeighbours(), MeshCore::MeshHelpPoint::Set(), MeshCore::MeshTopoAlgorithm::SnapVertex(), Base::Line3< float >::SqrLength(), and MeshCore::MeshFacetModifier::Transpose().
fmod()
template<class T > T Base::fmod (T numerator, T denominator) inline
Definition at line 160 of file Base/Tools.h.
Referenced by TechDraw::AOC::AOC(), TechDraw::AOE::AOE(), App::FunctionExpression::evaluate(), Import::ImpExpDxfWrite::exportEllipseArc(), Sketcher::SketchObject::getSymmetric(), Measure::MeasureAngle::isPrioritizedSelection(), TechDraw::GeometryObject::isWithinArc(), Assembly::AssemblyObject::makeMbdJointOfType(), Idf::process_emn(), SketcherGui::DrawSketchHandler::seekAutoConstraint(), TechDrawGui::CompassDialWidget::setAngle(), TechDrawGui::QGICenterLine::setTools(), and Path::PathSegmentWalker::walk().
freecad_dynamic_cast() [1/2]
template<typename T > T* Base::freecad_dynamic_cast (Base::BaseClass * type)
Template that works just like dynamic_cast, but expects the argument to inherit from Base::BaseClass.
Definition at line 196 of file BaseClass.h.
References Path.Post.scripts.grbl_post::type.
freecad_dynamic_cast() [2/2]
template<typename T > const T* Base::freecad_dynamic_cast (const Base::BaseClass * type)
Template that works just like dynamic_cast, but expects the argument to inherit from a const Base::BaseClass.
Definition at line 211 of file BaseClass.h.
References Path.Post.scripts.grbl_post::type.
GetDuration()
std::chrono::duration<double> Base::GetDuration (std::chrono::high_resolution_clock ::time_point & tp) inline
Definition at line 494 of file Console.h.
References Path.Post.scripts.dumper_post::now.
getTypeAsObject()
PyObject* Base::getTypeAsObject (PyTypeObject * type) inline
Definition at line 117 of file PyObjectBase.h.
References Path.Post.scripts.grbl_post::type.
Referenced by Base::InterpreterSingleton::addType().
getVectorFromTuple()
template<typename T > Vector3<T> Base::getVectorFromTuple (PyObject * py) inline
Definition at line 63 of file GeometryPyCXX.h.
Interpreter()
InterpreterSingleton& Base::Interpreter () inline
Access to the InterpreterSingleton object This method is used to gain access to the one and only instance of the InterpreterSingleton class.
Definition at line 385 of file Interpreter.h.
References Base::InterpreterSingleton::Instance().
Referenced by Gui::Command::_runCommand(), StdCmdCommandLine::activated(), Gui::PythonCommand::activated(), Gui::View3DInventorPy::addDraggerCallback(), Gui::View3DInventorPy::addEventCallbackPivy(), Gui::Command::addModule(), Gui::Application::Application(), Gui::PreferencePack::apply(), Gui::ExpLineEdit::apply(), App::Application::destruct(), Gui::View3DInventorPy::dumpNode(), TechDraw::DrawParametricTemplate::execute(), TechDraw::DrawViewDraft::execute(), TechDraw::DrawViewArch::execute(), Gui::FreeCADGui_exportSubgraph(), Gui::FreeCADGui_subgraphFromObject(), Gui::View3DInventorPy::getCameraNode(), Gui::ViewProviderFeaturePythonImp::getDetail(), Gui::ViewProviderFeaturePythonImp::getDetailPath(), Gui::ViewProviderFeaturePythonImp::getElement(), Gui::ViewProviderFeaturePythonImp::getElementPicked(), Gui::PythonCommand::getHelpUrl(), Gui::View3DInventorViewerPy::getSceneGraph(), Gui::View3DInventorPy::getSceneGraph(), Gui::View3DInventorViewerPy::getSoEventManager(), Gui::View3DInventorViewerPy::getSoRenderManager(), Base::Type::importModule(), Gui::PythonDebugModule::init_module(), Fem::SMESH_HypothesisPy< StdMeshers_TrianglePreferencePy >::init_type(), InspectionGui::initModule(), CloudGui::initModule(), SurfaceGui::initModule(), PointsGui::initModule(), ReverseEngineeringGui::initModule(), MeshPartGui::initModule(), MeasureGui::initModule(), RobotGui::initModule(), MatGui::initModule(), SketcherGui::initModule(), PartDesignGui::initModule(), StartGui::initModule(), PartGui::initModule(), MeshGui::initModule(), SpreadsheetGui::initModule(), JtReaderNS::initModule(), Cloud::initModule(), TestGui::initModule(), Drawing::initModule(), Mesh::initModule(), Reen::initModule(), TechDraw::initModule(), Part::initModule(), TechDraw::DrawDimHelper::makeDistDim(), TechDraw::DrawDimHelper::makeExtentDim(), TechDraw::DrawDimHelper::makeExtentDim3d(), TechDraw::DrawLeaderLine::makeLeader(), Measure::Module::Module(), SketcherGui::ViewProviderSketch::onCameraChanged(), Gui::GestureNavigationStyle::onRollGesture(), App::Application::processCmdLineFiles(), App::Application::processFiles(), PyMOD_INIT_FUNC(), Gui::PythonCommand::PythonCommand(), Gui::PythonGroupCommand::PythonGroupCommand(), Gui::View3DInventorPy::removeDraggerCallback(), Gui::View3DInventorPy::removeEventCallbackPivy(), Gui::SoQtOffscreenRendererPy::render(), Sandbox::PythonThread::run(), Gui::MacroManager::run(), App::Application::runApplication(), Gui::Application::runInitGuiScript(), Gui::ApplicationPy::sCoinRemoveAllChildren(), Gui::Application::setActiveDocument(), Gui::View3DInventorViewerPy::setSceneGraph(), Gui::View3DInventorViewerPy::setupEditingRoot(), TechDraw::DrawViewCollection::unsetupObject(), TechDraw::DrawPage::unsetupObject(), TechDraw::DrawViewPart::unsetupObject(), and PartGui::Workbench::Workbench().
make_vec() [1/2]
template<class Vec , typename float_type > Vec Base::make_vec (const std::tuple< float_type, float_type, float_type > && ft)
Definition at line 118 of file Converter.h.
References Path.Post.scripts.opensbp_post::move(), and SurfaceTests.TestBlendCurve::vec.
make_vec() [2/2]
template<class Vec , typename float_type > Vec Base::make_vec (const std::tuple< float_type, float_type, float_type, float_type > && ft)
Definition at line 129 of file Converter.h.
operator*() [1/10]
DualNumber Base::operator* (double a, DualNumber b) inline
Definition at line 108 of file DualNumber.h.
References a, and pow().
operator*() [2/10]
Base::DualQuat Base::operator* (double a, Base::DualQuat b)
Definition at line 53 of file DualQuaternion.cpp.
References a, and SCL.SimpleDataTypes::b.
operator*() [3/10]
Vector2d Base::operator* (double c, const Vector2d & v) inline
Definition at line 301 of file Tools2D.h.
operator*() [4/10]
DualNumber Base::operator* (DualNumber a, double b) inline
Definition at line 112 of file DualNumber.h.
operator*() [5/10]
DualNumber Base::operator* (DualNumber a, DualNumber b) inline
Definition at line 104 of file DualNumber.h.
operator*() [6/10]
Base::DualQuat Base::operator* (Base::DualNumber a, Base::DualQuat b)
Definition at line 63 of file DualQuaternion.cpp.
References a, and SCL.SimpleDataTypes::b.
operator*() [7/10]
Base::DualQuat Base::operator* (Base::DualQuat a, double b)
Definition at line 48 of file DualQuaternion.cpp.
References a, and SCL.SimpleDataTypes::b.
operator*() [8/10]
Base::DualQuat Base::operator* (Base::DualQuat a, Base::DualNumber b)
Definition at line 58 of file DualQuaternion.cpp.
References a, and SCL.SimpleDataTypes::b.
operator*() [9/10]
Base::DualQuat Base::operator* (Base::DualQuat a, Base::DualQuat b)
Definition at line 40 of file DualQuaternion.cpp.
References a, and SCL.SimpleDataTypes::b.
operator*() [10/10]
template<class float_type > Vector3<float_type> Base::operator* (float_type fFac, const Vector3< float_type > & rcVct) inline
Multiplication of scalar with vector.
Definition at line 283 of file Vector3D.h.
References Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
operator*=()
Vector3f& Base::operator*= (Vector3f & vec, const Matrix4D & mat) inline
Definition at line 441 of file Matrix.h.
operator+() [1/4]
DualNumber Base::operator+ (double a, DualNumber b) inline
Definition at line 86 of file DualNumber.h.
References a, and SCL.SimpleDataTypes::b.
operator+() [2/4]
DualNumber Base::operator+ (DualNumber a, double b) inline
Definition at line 82 of file DualNumber.h.
operator+() [3/4]
DualNumber Base::operator+ (DualNumber a, DualNumber b) inline
Definition at line 78 of file DualNumber.h.
operator+() [4/4]
Base::DualQuat Base::operator+ (Base::DualQuat a, Base::DualQuat b)
Definition at line 30 of file DualQuaternion.cpp.
References a, and SCL.SimpleDataTypes::b.
operator-() [1/4]
DualNumber Base::operator- (double a, DualNumber b) inline
Definition at line 99 of file DualNumber.h.
References a, and SCL.SimpleDataTypes::b.
operator-() [2/4]
DualNumber Base::operator- (DualNumber a, double b) inline
Definition at line 95 of file DualNumber.h.
operator-() [3/4]
DualNumber Base::operator- (DualNumber a, DualNumber b) inline
Definition at line 91 of file DualNumber.h.
operator-() [4/4]
Base::DualQuat Base::operator- (Base::DualQuat a, Base::DualQuat b)
Definition at line 35 of file DualQuaternion.cpp.
References a, and SCL.SimpleDataTypes::b.
operator/() [1/2]
DualNumber Base::operator/ (DualNumber a, double b) inline
Definition at line 121 of file DualNumber.h.
operator/() [2/2]
DualNumber Base::operator/ (DualNumber a, DualNumber b) inline
Definition at line 117 of file DualNumber.h.
pow()
DualNumber Base::pow (DualNumber a, double pw) inline
Definition at line 126 of file DualNumber.h.
Referenced by Attacher::AttachEngine3D::_calculateAttachedPlacement(), GCS::System::addConstraintInternalAlignmentEllipseMajorDiameter(), GCS::System::addConstraintInternalAlignmentEllipseMinorDiameter(), GCS::System::addConstraintInternalAlignmentHyperbolaMajorDiameter(), GCS::System::addConstraintInternalAlignmentHyperbolaMinorDiameter(), Gui::Dialog::ApplicationCache::ApplicationCache(), Gui::PropertyEditor::PropertyRotationItem::assignProperty(), Gui::PropertyEditor::PropertyPlacementItem::assignProperty(), MeshGui::ViewProviderMeshFaceSet::attach(), MeshGui::ViewProviderIndexedFaceSet::attach(), MeshGui::ViewProviderMeshObject::attach(), Points::PointsGrid::CalculateGridLength(), MeshCore::MeshGrid::CalculateGridLength(), MeshCore::MeshAlgorithm::CalculateMinimumGridLength(), Gui::Dialog::Clipping::Clipping(), columnStringToNum(), importers.importWebGL::compress_floats(), Path.Dressup.Gui.RampEntry.ObjectDressup::createCommands(), NaviCubeImplementation::createCubeFaceTextures(), FemGui::ViewProviderFEMMeshBuilder::createMesh(), TechDrawGui::QGIViewBalloon::drawBalloon(), TechDrawGui::QGTracker::drawTrackCircle(), GCS::ConstraintPointOnEllipse::error(), GCS::ConstraintPointOnHyperbola::error(), App::FunctionExpression::evaluate(), draftgeoutils.intersections::findIntersection(), Fem::FemPostDataAlongLineFilter::GetAxisData(), Fem::FemPostDataAtPointFilter::GetPointData(), StdDevCollector::getQuantity(), GCS::ConstraintSlopeAtBSplineKnot::grad(), GCS::ConstraintPointOnEllipse::grad(), GCS::ConstraintPointOnHyperbola::grad(), GCS::ConstraintAngleViaPoint::grad(), GCS::ConstraintAngleViaTwoPoints::grad(), GCS::ConstraintAngleViaPointAndParam::grad(), GCS::ConstraintAngleViaPointAndTwoParams::grad(), Inspection::InspectNominalFastMesh::InspectNominalFastMesh(), Inspection::InspectNominalMesh::InspectNominalMesh(), TechDraw::DimensionFormatter::isTooSmall(), MengerSponge::makeMengerSponge_mt(), makeParallelMengerSponge(), Gui::Dialog::DlgUnitsCalculator::onUnitsBoxActivated(), operator*(), draftobjects.bspline.BSpline::parameterization(), Base::Quantity::pow(), TechDrawGui::DrawGuiUtil::roundToDigits(), TechDraw::DrawUtil::sensibleScale(), TechDrawGui::QGTracker::setCircleFromPoints(), Gui::SoFCColorLegend::setLegendLabels(), TechDrawGui::QGICenterLine::setTools(), PartGui::ShapeFromMesh::ShapeFromMesh(), MengerSponge::Sierpinski(), Sierpinski(), Simplify::simplify_mesh(), TechDrawGui::QGTracker::snapToAngle(), Path::Command::toGCode(), lscmrelax::LscmRelax::transform(), src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunctionSegment::value(), and DrawingGui::SvgView::wheelEvent().
provideService()
template<typename T > T* Base::provideService ()
Obtains primary implementation of requested service from the global service provider.
Template Parameters
T Service kind to obtain.
Returns
Primary implementation of the service or nullptr if there is no implementation available.
Definition at line 192 of file ServiceProvider.h.
provideServiceImplementations()
template<typename T > std::list<T*> Base::provideServiceImplementations ()
Obtains all available implementations of requested service in the global service provider.
Template Parameters
T Service kind to obtain.
Returns
List of available service implementation.
Definition at line 204 of file ServiceProvider.h.
PyAsUnicodeObject() [1/2]
PyObject* Base::PyAsUnicodeObject (const char * str) inline
Python helper class This class encapsulate the Decoding of UTF8 to a python object. Including exception handling.
Definition at line 510 of file PyObjectBase.h.
References buildPsets::p, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by PyAsUnicodeObject().
PyAsUnicodeObject() [2/2]
PyObject* Base::PyAsUnicodeObject (const std::string & str) inline
Definition at line 521 of file PyObjectBase.h.
References PyAsUnicodeObject(), and Path.Post.scripts.refactored_centroid_post::str.
pyCall()
Py::Object Base::pyCall (PyObject * callable, PyObject * args = nullptr) inline
Definition at line 135 of file Interpreter.h.
References toolbit-attributes::args, and result.
Referenced by App::FeaturePythonImp::allowDuplicateLabel(), Gui::ViewProviderFeaturePythonImp::attach(), Gui::ViewProviderFeaturePythonImp::canDelete(), Gui::ViewProviderFeaturePythonImp::canDragAndDropObject(), Gui::ViewProviderFeaturePythonImp::canDragObject(), Gui::ViewProviderFeaturePythonImp::canDragObjects(), Gui::ViewProviderFeaturePythonImp::canDropObject(), Gui::ViewProviderFeaturePythonImp::canDropObjectEx(), Gui::ViewProviderFeaturePythonImp::canDropObjects(), App::FeaturePythonImp::canLinkProperties(), App::FeaturePythonImp::canLoadPartial(), Gui::ViewProviderFeaturePythonImp::canRemoveChildrenFromRoot(), Gui::ViewProviderFeaturePythonImp::claimChildren(), Gui::ViewProviderFeaturePythonImp::doubleClicked(), Gui::ViewProviderFeaturePythonImp::dragObject(), Gui::ViewProviderFeaturePythonImp::dropObject(), Gui::ViewProviderFeaturePythonImp::dropObjectEx(), App::FeaturePythonImp::editProperty(), Gui::ViewProviderFeaturePythonImp::editProperty(), App::FeaturePythonImp::execute(), Gui::ViewProviderFeaturePythonImp::finishRestoring(), Gui::ViewProviderFeaturePythonImp::getDefaultDisplayMode(), Gui::ViewProviderFeaturePythonImp::getDetail(), Gui::ViewProviderFeaturePythonImp::getDetailPath(), Gui::ViewProviderFeaturePythonImp::getDisplayModes(), Gui::ViewProviderFeaturePythonImp::getDropPrefix(), Gui::ViewProviderFeaturePythonImp::getElement(), Gui::ViewProviderFeaturePythonImp::getElementPicked(), Gui::ViewProviderFeaturePythonImp::getIcon(), App::FeaturePythonImp::getLinkedObject(), Gui::ViewProviderFeaturePythonImp::getLinkedViewProvider(), App::FeaturePythonImp::getSubObject(), App::FeaturePythonImp::getSubObjects(), App::FeaturePythonImp::getViewProviderName(), App::FeaturePythonImp::hasChildElement(), App::FeaturePythonImp::isElementVisible(), Gui::ViewProviderFeaturePythonImp::isShow(), App::FeaturePythonImp::mustExecute(), App::FeaturePythonImp::onBeforeChange(), Gui::ViewProviderFeaturePythonImp::onBeforeChange(), App::FeaturePythonImp::onBeforeChangeLabel(), App::FeaturePythonImp::onChanged(), Gui::ViewProviderFeaturePythonImp::onChanged(), Gui::ViewProviderFeaturePythonImp::onDelete(), App::FeaturePythonImp::onDocumentRestored(), App::FeaturePythonImp::redirectSubName(), Gui::ViewProviderFeaturePythonImp::replaceObject(), Gui::ViewProviderFeaturePythonImp::setDisplayMode(), Gui::ViewProviderFeaturePythonImp::setEdit(), Gui::ViewProviderFeaturePythonImp::setEditViewer(), App::FeaturePythonImp::setElementVisible(), Gui::ViewProviderFeaturePythonImp::setupContextMenu(), Gui::ViewProviderFeaturePythonImp::unsetEdit(), Gui::ViewProviderFeaturePythonImp::unsetEditViewer(), App::FeaturePythonImp::unsetupObject(), and Gui::ViewProviderFeaturePythonImp::updateData().
pyCallWithKeywords()
Py::Object Base::pyCallWithKeywords (PyObject * callable, PyObject * args, PyObject * kwds = nullptr) inline
Definition at line 144 of file Interpreter.h.
References toolbit-attributes::args, and result.
PyTypeCheck() [1/2]
void Base::PyTypeCheck (PyObject ** ptr, int(*)(PyObject *) method, const char * msg) inline
Definition at line 546 of file PyObjectBase.h.
References Path.Op.Surface::msg.
PyTypeCheck() [2/2]
void Base::PyTypeCheck (PyObject ** ptr, PyTypeObject * type, const char * msg = nullptr) inline
Helper functions to check if a python object is of a specific type or None, otherwise raise an exception. If the object is None, the pointer is set to nullptr.
Definition at line 530 of file PyObjectBase.h.
References Path.Op.Surface::msg, Path.Post.scripts.refactored_centroid_post::str, and Path.Post.scripts.grbl_post::type.
Referenced by App::PropertyLinkList::getPyValue(), Gui::MDIViewPy::setActiveObject(), App::PropertyLink::setPyObject(), and Gui::SelectionSingleton::sSetVisible().
registerServiceImplementation()
template<typename T > void Base::registerServiceImplementation (T * implementation)
Registers implementation of service in the global service provider.
Template Parameters
T Service kind to obtain.
Returns
List of available service implementation.
Definition at line 216 of file ServiceProvider.h.
ScriptFactory()
ScriptFactorySingleton& Base::ScriptFactory () inline
Definition at line 124 of file Factory.h.
Referenced by App::Application::runApplication(), and Gui::Application::runInitGuiScript().
Sequencer()
SequencerBase& Base::Sequencer () inline
Access to the only SequencerBase instance
Definition at line 406 of file Sequencer.h.
Referenced by Gui::ViewerEventFilter::eventFilter(), CmdTestProgress1::isActive(), CmdTestProgress2::isActive(), CmdTestProgress3::isActive(), CmdTestProgress4::isActive(), CmdTestProgress5::isActive(), MeshGui::ViewProviderMesh::partMeshCallback(), and MeshGui::ViewProviderMesh::segmMeshCallback().
sgn()
template<class T > T Base::sgn (T t) inline
Definition at line 134 of file Base/Tools.h.
References M_PI.
Referenced by TechDrawGui::QGIViewDimension::compareAngleStraightness().
streq()
int Base::streq (const char * A, const char * B) inline
Definition at line 104 of file PyObjectBase.h.
References RobotExample::A, and RobotExample::B.
Referenced by Base::PyObjectBase::__getattro(), Base::PyObjectBase::_getattr(), and Base::PyObjectBase::_setattr().
SwapEndian()
template<class T > void Base::SwapEndian (T & v)
Definition at line 52 of file Swap.h.
References SplineSurface::i, and TestSpreadsheet::v.
Referenced by MeshCore::MeshKernel::Read().
SwapOrder()
unsigned short Base::SwapOrder ()
Definition of functions that allow swapping of data types dependent on the architecture.
Returns machine type (low endian, high endian)
Definition at line 28 of file Swap.cpp.
References HIGH_ENDIAN, and LOW_ENDIAN.
SwapVar() [1/8]
void Base::SwapVar (char &)
Definition at line 34 of file Swap.cpp.
SwapVar() [2/8]
void Base::SwapVar (double & d)
Definition at line 95 of file Swap.cpp.
References SplineSurface::i.
SwapVar() [3/8]
void Base::SwapVar (float & f)
Definition at line 84 of file Swap.cpp.
References SCL.SimpleDataTypes::f, and SplineSurface::i.
SwapVar() [4/8]
void Base::SwapVar (long & l)
Definition at line 62 of file Swap.cpp.
References SplineSurface::i, and RobotExample::l.
SwapVar() [5/8]
void Base::SwapVar (short & s)
Definition at line 40 of file Swap.cpp.
References SplineSurface::i, and toolbit-attributes::s.
SwapVar() [6/8]
void Base::SwapVar (unsigned char &)
Definition at line 37 of file Swap.cpp.
SwapVar() [7/8]
void Base::SwapVar (unsigned long & l)
Definition at line 73 of file Swap.cpp.
References SplineSurface::i, and RobotExample::l.
SwapVar() [8/8]
void Base::SwapVar (unsigned short & s)
Definition at line 51 of file Swap.cpp.
References SplineSurface::i, and toolbit-attributes::s.
tabs()
manipulator<int> Base::tabs (int n) inline
Definition at line 115 of file Base/Tools.h.
References InitGui::t.
Referenced by Gui::SoFCVectorizeU3DAction::printHeader(), Gui::PropertyView::PropertyView(), and MeshCore::MeshOutput::SaveIDTF().
tabsN()
std::ostream& Base::tabsN (std::ostream & os, int n) inline
Definition at line 99 of file Base/Tools.h.
References blanksN().
to_vector()
BaseExport Base::Vector3f Base::to_vector (std::string)
Expects a string of the form "(x,y,z)" and creates a vector from it. If it fails then a std::exception is thrown. Supported type names are float or double
Definition at line 1261 of file Builder3D.cpp.
References Path.Post.scripts.refactored_centroid_post::str, femtools.tokrules::tokens, and SurfaceTests.TestBlendCurve::vec.
Referenced by Gui::View3DSettings::OnChange().
toDegrees()
template<class T > T Base::toDegrees (T r) inline
Definition at line 154 of file Base/Tools.h.
Referenced by Gui::PropertyEditor::RotationHelper::assignProperty(), PartGui::CircleFromThreePoints::command(), TDHandlerDimension::createDistanceDimension(), PartDesign::Helix::execute(), Measure::MeasureAngle::execute(), TechDrawGui::QGIWeldSymbol::getLastSegAngle(), App::PropertyPlacement::getPathValue(), App::PropertyRotation::getPathValue(), TechDraw::DrawViewDimension::getProjectedDimValue(), App::PropertyPlacement::getPyPathValue(), App::PropertyRotation::getPyPathValue(), Measure::ShapeFinder::LocationAsString(), Measure::ShapeFinder::PlacementAsString(), TechDrawGui::TaskCosmeticCircle::setUiEdit(), TechDrawGui::TaskCosmeticCircle::setUiPrimary(), Gui::PropertyEditor::PropertyRotationItem::value(), Gui::PropertyEditor::PropertyPlacementItem::value(), CDxfWrite::writeAngularDimBlock(), and CDxfWrite::writeArc().
toRadians()
template<class T > T Base::toRadians (T d) inline
Definition at line 148 of file Base/Tools.h.
References Base::FlagToggler< Flag >::flag.
Referenced by Gui::ExpressionBinding::assignToProperty(), TechDrawGui::QGIViewBalloon::balloonLabelDragFinished(), TechDrawGui::QGSPage::createBalloon(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), TechDrawGui::TaskProjGroup::customDirectionClicked(), PartDesign::Hole::execute(), PartDesign::Helix::execute(), PartDesign::Revolution::execute(), Mesh::FixDeformations::execute(), Part::Prism::execute(), Part::RegularPolygon::execute(), PartDesign::Prism::execute(), FC_LOG_LEVEL_INIT(), PartDesign::Helix::generateHelixPath(), PartDesign::FeatureExtrude::generateTaperedPrism(), PartDesign::FeatureExtrude::hasTaperedAngle(), TechDraw::DrawLeaderLine::horizLastSegment(), Part::TopoShape::makeHelix(), Part::TopoShape::makeLongHelix(), Assembly::AssemblyObject::makeMbdJointOfType(), TechDrawGui::TaskLeaderLine::scenePointsToDeltas(), App::PropertyPlacement::setPathValue(), App::PropertyRotation::setPathValue(), TechDrawGui::QGIView::snapSectionView(), TechDraw::pointPair::toDisplayForm(), TechDraw::anglePoints::toDisplayForm(), TechDraw::arcPoints::toDisplayForm(), TechDrawGui::DrawGuiUtil::toGuiPoint(), and Mesh::MeshObject::validateDeformations().
toVector()
template<class Pr1 , class Pr2 > Vector3<Pr1> Base::toVector (const Vector3< Pr2 > & v) inline
Definition at line 289 of file Vector3D.h.
References TestSpreadsheet::v.
Referenced by Py::Vector::operator Base::Vector3d().
Wrapped_ParseTupleAndKeywords()
template<size_t arraySize> bool Base::Wrapped_ParseTupleAndKeywords (PyObject * args, PyObject * kw, const char * format, const std::array< const char *, arraySize > keywords, ...)
A thin C++ wrapper around PyArg_ParseTupleAndKeywords providing const-correctness for the keywords argument
args The Python args object
kw The Python kw object
format The format string describing the expected arguments
keywords A std::array of keywords, terminated by a nullptr (required by CPython)
(variadic) Pointers to the storage locations for the parameters
Returns
boolean true on success, or false on failure
Definition at line 60 of file PyWrapParseTupleAndKeywords.h.
Referenced by areaAbort(), areaGetParamsDesc(), areaSetParams(), Gui::View3DInventorPy::boxZoom(), Gui::SelectionSingleton::sSetPreselection(), and Gui::View3DInventorPy::toggleClippingPlane().
Variable Documentation
base64DecodeTableSize
constexpr size_t Base::base64DecodeTableSize {256} static constexpr
Definition at line 48 of file Base64.h.
base64DefaultBufferSize
constexpr int Base::base64DefaultBufferSize {80} static constexpr
Definition at line 71 of file Base64Filter.h.
Referenced by Base::Writer::beginCharStream(), and Base::XMLReader::beginCharStream().
globalServiceProvider
BaseExport ServiceProvider Base::globalServiceProvider
Definition at line 51 of file ServiceProvider.cpp.
Line3< double >
template class BaseExport Base::Line3< double >
Definition at line 273 of file Tools3D.cpp.
Line3< float >
template class BaseExport Base::Line3< float >
Definition at line 272 of file Tools3D.cpp.
Observer< const char * >
template class BaseExport Base::Observer< const char * >
Definition at line 54 of file Observer.cpp.
Polygon3< double >
template class BaseExport Base::Polygon3< double >
Definition at line 275 of file Tools3D.cpp.
Polygon3< float >
template class BaseExport Base::Polygon3< float >
Definition at line 274 of file Tools3D.cpp.
PyExc_FC_AbortIOException
PyObject * Base::PyExc_FC_AbortIOException = nullptr
Definition at line 52 of file PyObjectBase.cpp.
Referenced by ImportGui::Module::Module().
PyExc_FC_BadFormatError
PyObject * Base::PyExc_FC_BadFormatError = nullptr
Definition at line 46 of file PyObjectBase.cpp.
Referenced by Base::BadFormatError::getPyExceptionType().
PyExc_FC_BadGraphError
PyObject * Base::PyExc_FC_BadGraphError = nullptr
Definition at line 47 of file PyObjectBase.cpp.
Referenced by Base::BadGraphError::getPyExceptionType().
PyExc_FC_CADKernelError
PyObject * Base::PyExc_FC_CADKernelError = nullptr
Definition at line 50 of file PyObjectBase.cpp.
Referenced by Base::CADKernelError::getPyExceptionType(), Handle(), and Surface::BlendCurve::setSize().
PyExc_FC_ExpressionError
PyObject * Base::PyExc_FC_ExpressionError = nullptr
Definition at line 48 of file PyObjectBase.cpp.
Referenced by Base::ExpressionError::getPyExceptionType().
PyExc_FC_FreeCADAbort
PyObject * Base::PyExc_FC_FreeCADAbort = nullptr
Definition at line 41 of file PyObjectBase.cpp.
Referenced by Base::AbortException::getPyExceptionType(), and Base::PyException::raiseException().
PyExc_FC_GeneralError
PyObject * Base::PyExc_FC_GeneralError = nullptr
Definition at line 40 of file PyObjectBase.cpp.
Referenced by Base::Exception::getPyExceptionType(), FemGui::Module::Module(), PyMOD_INIT_FUNC(), Gui::ApplicationPy::sActivateWorkbenchHandler(), Gui::ApplicationPy::sAddCommand(), Gui::ApplicationPy::sAddIcon(), Gui::SelectionSingleton::sAddSelection(), Base::Exception::setPyException(), Gui::SelectionSingleton::sRemoveSelection(), Gui::ApplicationPy::sRunCommand(), Gui::SelectionSingleton::sSetPreselection(), and Gui::SelectionSingleton::sUpdateSelection().
PyExc_FC_ParserError
PyObject * Base::PyExc_FC_ParserError = nullptr
Definition at line 49 of file PyObjectBase.cpp.
Referenced by Base::ParserError::getPyExceptionType().
PyExc_FC_PropertyError
PyObject * Base::PyExc_FC_PropertyError = nullptr
Definition at line 51 of file PyObjectBase.cpp.
Referenced by Base::PropertyError::getPyExceptionType().
PyExc_FC_UnknownProgramOption
PyObject * Base::PyExc_FC_UnknownProgramOption = nullptr
Definition at line 45 of file PyObjectBase.cpp.
Referenced by Base::UnknownProgramOption::getPyExceptionType().
PyExc_FC_XMLAttributeError
PyObject * Base::PyExc_FC_XMLAttributeError = nullptr
Definition at line 44 of file PyObjectBase.cpp.
Referenced by Base::XMLAttributeError::getPyExceptionType().
PyExc_FC_XMLBaseException
PyObject * Base::PyExc_FC_XMLBaseException = nullptr
Definition at line 42 of file PyObjectBase.cpp.
Referenced by Base::XMLBaseException::getPyExceptionType().
PyExc_FC_XMLParseException
PyObject * Base::PyExc_FC_XMLParseException = nullptr
Definition at line 43 of file PyObjectBase.cpp.
Referenced by Base::XMLParseException::getPyExceptionType().
Subject< const char * >
template class BaseExport Base::Subject< const char * >
Definition at line 55 of file Observer.cpp.
Vector3< double >
template class BaseExport Base::Vector3< double >
Definition at line 511 of file Vector3D.cpp.
Referenced by MeshCore::MeshCurvature::ComputePerVertex(), and MeshCore::QuadraticFit::Fit().
Vector3< float >
template class BaseExport Base::Vector3< float >
Definition at line 510 of file Vector3D.cpp.
Referenced by MeshCore::MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection(), and MeshCore::MeshSearchNeighbours::NeighboursFromSampledFacets().