FreeCAD: Wm4::ImplicitSurface< Real > Class Template Reference
Wm4::ImplicitSurface< Real > Class Template Reference abstract
#include <Wm4ImplicitSurface.h>
Public Member Functions
virtual ~ImplicitSurface ()
virtual Real F (const Vector3< Real > &rkP) const =0
virtual Real FX (const Vector3< Real > &rkP) const =0
virtual Real FY (const Vector3< Real > &rkP) const =0
virtual Real FZ (const Vector3< Real > &rkP) const =0
virtual Real FXX (const Vector3< Real > &rkP) const =0
virtual Real FXY (const Vector3< Real > &rkP) const =0
virtual Real FXZ (const Vector3< Real > &rkP) const =0
virtual Real FYY (const Vector3< Real > &rkP) const =0
virtual Real FYZ (const Vector3< Real > &rkP) const =0
virtual Real FZZ (const Vector3< Real > &rkP) const =0
bool IsOnSurface (const Vector3< Real > &rkP, Real fEpsilon) const
Vector3< Real > GetGradient (const Vector3< Real > &rkP) const
Matrix3< Real > GetHessian (const Vector3< Real > &rkP) const
void GetFrame (const Vector3< Real > &rkP, Vector3< Real > &rkTangent0, Vector3< Real > &rkTangent1, Vector3< Real > &rkNormal) const
bool ComputePrincipalCurvatureInfo (const Vector3< Real > &rkP, Real &rfCurv0, Real &rfCurv1, Vector3< Real > &rkDir0, Vector3< Real > &rkDir1)
Public Member Functions inherited from Wm4::Surface< Real >
virtual ~Surface ()
Protected Member Functions
ImplicitSurface ()
Protected Member Functions inherited from Wm4::Surface< Real >
Surface ()
Detailed Description
template<class Real>
class Wm4::ImplicitSurface< Real >
Definition at line 28 of file Wm4ImplicitSurface.h.
Constructor & Destructor Documentation
~ImplicitSurface()
template<class Real > Wm4::ImplicitSurface< Real >::~ImplicitSurface virtual
Definition at line 29 of file Wm4ImplicitSurface.cpp.
ImplicitSurface()
template<class Real > Wm4::ImplicitSurface< Real >::ImplicitSurface protected
Definition at line 24 of file Wm4ImplicitSurface.cpp.
Member Function Documentation
ComputePrincipalCurvatureInfo()
template<class Real > bool Wm4::ImplicitSurface< Real >::ComputePrincipalCurvatureInfo (const Vector3< Real > & rkP, Real & rfCurv0, Real & rfCurv1, Vector3< Real > & rkDir0, Vector3< Real > & rkDir1)
Definition at line 73 of file Wm4ImplicitSurface.cpp.
Referenced by MeshCore::FunctionContainer::CurvatureInfo().
F()
template<class Real > virtual Real Wm4::ImplicitSurface< Real >::F (const Vector3< Real > & rkP) const pure virtual
Implemented in Wm4::PolynomialSurface< Real >, and Wm4::QuadricSurface< Real >.
FX()
template<class Real > virtual Real Wm4::ImplicitSurface< Real >::FX (const Vector3< Real > & rkP) const pure virtual
Implemented in Wm4::PolynomialSurface< Real >, and Wm4::QuadricSurface< Real >.
FXX()
template<class Real > virtual Real Wm4::ImplicitSurface< Real >::FXX (const Vector3< Real > & rkP) const pure virtual
Implemented in Wm4::QuadricSurface< Real >, and Wm4::PolynomialSurface< Real >.
FXY()
template<class Real > virtual Real Wm4::ImplicitSurface< Real >::FXY (const Vector3< Real > & rkP) const pure virtual
Implemented in Wm4::QuadricSurface< Real >, and Wm4::PolynomialSurface< Real >.
FXZ()
template<class Real > virtual Real Wm4::ImplicitSurface< Real >::FXZ (const Vector3< Real > & rkP) const pure virtual
Implemented in Wm4::QuadricSurface< Real >, and Wm4::PolynomialSurface< Real >.
FY()
template<class Real > virtual Real Wm4::ImplicitSurface< Real >::FY (const Vector3< Real > & rkP) const pure virtual
Implemented in Wm4::PolynomialSurface< Real >, and Wm4::QuadricSurface< Real >.
FYY()
template<class Real > virtual Real Wm4::ImplicitSurface< Real >::FYY (const Vector3< Real > & rkP) const pure virtual
Implemented in Wm4::QuadricSurface< Real >, and Wm4::PolynomialSurface< Real >.
FYZ()
template<class Real > virtual Real Wm4::ImplicitSurface< Real >::FYZ (const Vector3< Real > & rkP) const pure virtual
Implemented in Wm4::QuadricSurface< Real >, and Wm4::PolynomialSurface< Real >.
FZ()
template<class Real > virtual Real Wm4::ImplicitSurface< Real >::FZ (const Vector3< Real > & rkP) const pure virtual
Implemented in Wm4::QuadricSurface< Real >, and Wm4::PolynomialSurface< Real >.
FZZ()
template<class Real > virtual Real Wm4::ImplicitSurface< Real >::FZZ (const Vector3< Real > & rkP) const pure virtual
Implemented in Wm4::QuadricSurface< Real >, and Wm4::PolynomialSurface< Real >.
GetFrame()
template<class Real > void Wm4::ImplicitSurface< Real >::GetFrame (const Vector3< Real > & rkP, Vector3< Real > & rkTangent0, Vector3< Real > & rkTangent1, Vector3< Real > & rkNormal) const
Definition at line 64 of file Wm4ImplicitSurface.cpp.
GetGradient()
template<class Real > Vector3< Real > Wm4::ImplicitSurface< Real >::GetGradient (const Vector3< Real > & rkP) const
Definition at line 41 of file Wm4ImplicitSurface.cpp.
Referenced by MeshCore::FunctionContainer::GetGradient().
GetHessian()
template<class Real > Matrix3< Real > Wm4::ImplicitSurface< Real >::GetHessian (const Vector3< Real > & rkP) const
Definition at line 51 of file Wm4ImplicitSurface.cpp.
Referenced by MeshCore::FunctionContainer::GetHessian().
IsOnSurface()
template<class Real > bool Wm4::ImplicitSurface< Real >::IsOnSurface (const Vector3< Real > & rkP, Real fEpsilon) const
Definition at line 34 of file Wm4ImplicitSurface.cpp.
The documentation for this class was generated from the following files:
Wm4ImplicitSurface.h
Wm4ImplicitSurface.cpp