FreeCAD: MatGui::DlgInspectAppearance Class Reference
MatGui::DlgInspectAppearance Class Reference
#include <DlgInspectAppearance.h>
Public Member Functions
DlgInspectAppearance (QWidget *parent=nullptr)
~DlgInspectAppearance () override
bool accept ()
void OnChange (Gui::SelectionSingleton::SubjectType &rCaller, Gui::SelectionSingleton::MessageType Reason) override
Observer message from the Selection.
Detailed Description
Definition at line 61 of file DlgInspectAppearance.h.
Constructor & Destructor Documentation
DlgInspectAppearance()
DlgInspectAppearance::DlgInspectAppearance (QWidget * parent = nullptr) explicit
Definition at line 80 of file DlgInspectAppearance.cpp.
References Base::Subject< MsgType >::Attach(), and Gui::Selection().
~DlgInspectAppearance()
DlgInspectAppearance::~DlgInspectAppearance () override
Definition at line 92 of file DlgInspectAppearance.cpp.
References Base::Subject< MsgType >::Detach(), and Gui::Selection().
Member Function Documentation
accept()
bool DlgInspectAppearance::accept ()
Definition at line 97 of file DlgInspectAppearance.cpp.
Referenced by MatGui::TaskInspectAppearance::accept(), and MaterialEditor.MaterialEditor::verify().
OnChange()
void MatGui::DlgInspectAppearance::OnChange (Gui::SelectionSingleton::SubjectType & rCaller, Gui::SelectionSingleton::MessageType Reason) override
Observer message from the Selection.
The documentation for this class was generated from the following files:
DlgInspectAppearance.h
DlgInspectAppearance.cpp