FreeCAD: ModelRefine::FaceTypeSplitter Class Reference
ModelRefine::FaceTypeSplitter Class Reference
#include <modelRefine.h>
Public Member Functions
FaceTypeSplitter ()=default
void addShell (const TopoDS_Shell &shellIn)
void registerType (const GeomAbs_SurfaceType &type)
bool hasType (const GeomAbs_SurfaceType &type) const
void split ()
const FaceVectorType & getTypedFaceVector (const GeomAbs_SurfaceType &type) const
Detailed Description
Definition at line 133 of file modelRefine.h.
Constructor & Destructor Documentation
FaceTypeSplitter()
ModelRefine::FaceTypeSplitter::FaceTypeSplitter () default
Member Function Documentation
addShell()
void FaceTypeSplitter::addShell (const TopoDS_Shell & shellIn)
Definition at line 144 of file modelRefine.cpp.
Referenced by ModelRefine::FaceUniter::process().
getTypedFaceVector()
const FaceVectorType & FaceTypeSplitter::getTypedFaceVector (const GeomAbs_SurfaceType & type) const
Definition at line 173 of file modelRefine.cpp.
References Path.Log::error(), hasType(), and Path.Post.scripts.grbl_post::type.
Referenced by ModelRefine::FaceUniter::process().
hasType()
bool FaceTypeSplitter::hasType (const GeomAbs_SurfaceType & type) const
Definition at line 154 of file modelRefine.cpp.
References Path.Post.scripts.grbl_post::type.
Referenced by getTypedFaceVector().
registerType()
void FaceTypeSplitter::registerType (const GeomAbs_SurfaceType & type)
Definition at line 149 of file modelRefine.cpp.
References Path.Post.scripts.grbl_post::type.
Referenced by ModelRefine::FaceUniter::process().
split()
void FaceTypeSplitter::split ()
Definition at line 159 of file modelRefine.cpp.
References ModelRefine::FaceTypedBase::getFaceType().
Referenced by ModelRefine::FaceUniter::process().
The documentation for this class was generated from the following files:
modelRefine.h
modelRefine.cpp