FreeCAD: ifc2x3.ifcproductsofcombustionproperties Class Reference
ifc2x3.ifcproductsofcombustionproperties Class Reference
Public Member Functions
def __init__ (self, inherited0__material, specificheatcapacity, n20content, cocontent, co2content)
def specificheatcapacity ()
def n20content ()
def cocontent ()
def co2content ()
Public Member Functions inherited from ifc2x3.ifcmaterialproperties
def __init__ (self, material)
def material ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
specificheatcapacity
n20content
cocontent
co2content
Public Attributes inherited from ifc2x3.ifcmaterialproperties
material
Detailed Description
Entity ifcproductsofcombustionproperties definition.
:param specificheatcapacity
:type specificheatcapacity:ifcspecificheatcapacitymeasure
:param n20content
:type n20content:ifcpositiveratiomeasure
:param cocontent
:type cocontent:ifcpositiveratiomeasure
:param co2content
:type co2content:ifcpositiveratiomeasure
Definition at line 11870 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcproductsofcombustionproperties.__init__ (self, inherited0__material, specificheatcapacity, n20content, cocontent, co2content)
Definition at line 11885 of file ifc2x3.py.
Member Function Documentation
co2content()
def ifc2x3.ifcproductsofcombustionproperties.co2content ()
Definition at line 11935 of file ifc2x3.py.
References ifc2x3.ifcproductsofcombustionproperties._co2content, SCL.TypeChecker.check_type(), and ifc2x3.ifcproductsofcombustionproperties.co2content.
cocontent()
def ifc2x3.ifcproductsofcombustionproperties.cocontent ()
Definition at line 11921 of file ifc2x3.py.
References ifc2x3.ifcproductsofcombustionproperties._cocontent, SCL.TypeChecker.check_type(), and ifc2x3.ifcproductsofcombustionproperties.cocontent.
n20content()
def ifc2x3.ifcproductsofcombustionproperties.n20content ()
Definition at line 11907 of file ifc2x3.py.
References ifc2x3.ifcproductsofcombustionproperties._n20content, SCL.TypeChecker.check_type(), and ifc2x3.ifcproductsofcombustionproperties.n20content.
specificheatcapacity()
def ifc2x3.ifcproductsofcombustionproperties.specificheatcapacity ()
Definition at line 11893 of file ifc2x3.py.
References ifc2x3.ifcproductsofcombustionproperties._specificheatcapacity, SCL.TypeChecker.check_type(), and ifc2x3.ifcproductsofcombustionproperties.specificheatcapacity.
Member Data Documentation
co2content
ifc2x3.ifcproductsofcombustionproperties.co2content
Definition at line 11890 of file ifc2x3.py.
Referenced by ifc2x3.ifcproductsofcombustionproperties.co2content().
cocontent
ifc2x3.ifcproductsofcombustionproperties.cocontent
Definition at line 11889 of file ifc2x3.py.
Referenced by ifc2x3.ifcproductsofcombustionproperties.cocontent().
n20content
ifc2x3.ifcproductsofcombustionproperties.n20content
Definition at line 11888 of file ifc2x3.py.
Referenced by ifc2x3.ifcproductsofcombustionproperties.n20content().
specificheatcapacity
ifc2x3.ifcproductsofcombustionproperties.specificheatcapacity
Definition at line 11887 of file ifc2x3.py.
Referenced by ifc2x3.ifcproductsofcombustionproperties.specificheatcapacity().
The documentation for this class was generated from the following file:
ifc2x3.py