FreeCAD: SpreadsheetGui::LineEdit Class Reference
SpreadsheetGui::LineEdit Class Reference
#include <LineEdit.h>
Signals
void finishedWithKey (int key, Qt::KeyboardModifiers modifiers)
Signals inherited from Gui::ExpressionLineEdit
void textChanged2 (QString text, int pos)
Public Member Functions
LineEdit (QWidget *parent=nullptr)
bool event (QEvent *event) override
Public Member Functions inherited from Gui::ExpressionLineEdit
ExpressionLineEdit (QWidget *parent=nullptr, bool noProperty=false, char checkPrefix=0, bool checkInList=true)
void setDocumentObject (const App::DocumentObject *currentDocObj, bool checkInList=true)
void setPrefix (char prefix)
bool completerActive () const
void hideCompleter ()
void setNoProperty (bool enabled=true)
void setExactMatch (bool enabled=true)
Additional Inherited Members
Public Slots inherited from Gui::ExpressionLineEdit
void slotTextChanged (const QString &text)
void slotCompleteText (const QString &completionPrefix, bool isActivated)
void slotCompleteTextHighlighted (const QString &completionPrefix)
void slotCompleteTextSelected (const QString &completionPrefix)
Protected Member Functions inherited from Gui::ExpressionLineEdit
void keyPressEvent (QKeyEvent *event) override
void contextMenuEvent (QContextMenuEvent *event) override
Detailed Description
Definition at line 53 of file LineEdit.h.
Constructor & Destructor Documentation
LineEdit()
LineEdit::LineEdit (QWidget * parent = nullptr) explicit
Definition at line 36 of file LineEdit.cpp.
Member Function Documentation
event()
bool LineEdit::event (QEvent * event) override
Definition at line 65 of file LineEdit.cpp.
References Gui::ExpressionLineEdit::completerActive(), and finishedWithKey().
finishedWithKey
void SpreadsheetGui::LineEdit::finishedWithKey (int key, Qt::KeyboardModifiers modifiers) signal
Referenced by SpreadsheetGui::SpreadsheetDelegate::createEditor(), and event().
The documentation for this class was generated from the following files:
LineEdit.h
LineEdit.cpp