FreeCAD: Wm4::System Class Reference
Wm4::System Class Reference
#include <Wm4System.h>
Public Types
enum { SM_READ, SM_WRITE, SM_READ_WRITE }
Static Public Member Functions
static void SwapBytes (int iSize, void *pvValue)
static void SwapBytes (int iSize, int iQuantity, void *pvValue)
static bool IsBigEndian ()
static void EndianCopy (int iSize, const void *pvSrc, void *pvDst)
static void EndianCopy (int iSize, int iQuantity, const void *pvSrc, void *pvDst)
static double GetTime ()
static bool Load (const char *acFilename, char *&racBuffer, int &riSize)
static bool Save (const char *acFilename, const char *acBuffer, int iSize)
static bool Append (const char *acFilename, char *acBuffer, int iSize)
static int Read1 (const char *acBuffer, int iQuantity, void *pvData)
static int Write1 (char *acBuffer, int iQuantity, const void *pvData)
static int Read1 (FILE *pkFile, int iQuantity, void *pvData)
static int Write1 (FILE *pkFile, int iQuantity, const void *pvData)
static int Read2le (const char *acBuffer, int iQuantity, void *pvData)
static int Read4le (const char *acBuffer, int iQuantity, void *pvData)
static int Read8le (const char *acBuffer, int iQuantity, void *pvData)
static int Write2le (char *acBuffer, int iQuantity, const void *pvData)
static int Write4le (char *acBuffer, int iQuantity, const void *pvData)
static int Write8le (char *acBuffer, int iQuantity, const void *pvData)
static int Read2le (FILE *pkFile, int iQuantity, void *pvData)
static int Read4le (FILE *pkFile, int iQuantity, void *pvData)
static int Read8le (FILE *pkFile, int iQuantity, void *pvData)
static int Write2le (FILE *pkFile, int iQuantity, const void *pvData)
static int Write4le (FILE *pkFile, int iQuantity, const void *pvData)
static int Write8le (FILE *pkFile, int iQuantity, const void *pvData)
static int Read2be (const char *acBuffer, int iQuantity, void *pvData)
static int Read4be (const char *acBuffer, int iQuantity, void *pvData)
static int Read8be (const char *acBuffer, int iQuantity, void *pvData)
static int Write2be (char *acBuffer, int iQuantity, const void *pvData)
static int Write4be (char *acBuffer, int iQuantity, const void *pvData)
static int Write8be (char *acBuffer, int iQuantity, const void *pvData)
static int Read2be (FILE *pkFile, int iQuantity, void *pvData)
static int Read4be (FILE *pkFile, int iQuantity, void *pvData)
static int Read8be (FILE *pkFile, int iQuantity, void *pvData)
static int Write2be (FILE *pkFile, int iQuantity, const void *pvData)
static int Write4be (FILE *pkFile, int iQuantity, const void *pvData)
static int Write8be (FILE *pkFile, int iQuantity, const void *pvData)
static const char * GetPath (const char *acDirectory, const char *acFilename)
static void Initialize ()
static void Terminate ()
static int GetDirectoryQuantity ()
static const char * GetDirectory (int i)
static bool InsertDirectory (const char *acDirectory)
static bool RemoveDirectory (const char *acDirectory)
static void RemoveAllDirectories ()
static const char * GetPath (const char *acFilename, int eMode)
static unsigned int MakeRGB (unsigned char ucR, unsigned char ucG, unsigned char ucB)
static unsigned int MakeRGBA (unsigned char ucR, unsigned char ucG, unsigned char ucB, unsigned char ucA)
static FILE * Fopen (const char *acFilename, const char *acMode)
static int Fprintf (FILE *pkFile, const char *acFormat,...)
static int Fclose (FILE *pkFile)
static const char * GetEnv (const char *acEnvVarName)
static void * Memcpy (void *pvDst, size_t uiDstSize, const void *pvSrc, size_t uiSrcSize)
static int Sprintf (char *acDst, size_t uiDstSize, const char *acFormat,...)
static char * Strcpy (char *acDst, size_t uiDstSize, const char *acSrc)
static char * Strcat (char *acDst, size_t uiDstSize, const char *acSrc)
static char * Strncpy (char *acDst, size_t uiDstSize, const char *acSrc, size_t uiSrcSize)
static char * Strtok (char *acToken, const char *acDelimiters, char *&racNextToken)
Static Public Attributes
static char WM4_PATH [SYSTEM_MAX_ENVVAR]
Detailed Description
Definition at line 55 of file Wm4System.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
SM_READ
SM_WRITE
SM_READ_WRITE
Definition at line 145 of file Wm4System.h.
Member Function Documentation
Append()
bool System::Append (const char * acFilename, char * acBuffer, int iSize) static
Definition at line 207 of file Wm4System.cpp.
References Fclose(), and Fopen().
EndianCopy() [1/2]
void System::EndianCopy (int iSize, const void * pvSrc, void * pvDst) static
Definition at line 85 of file Wm4System.cpp.
References Memcpy(), and SwapBytes().
EndianCopy() [2/2]
void System::EndianCopy (int iSize, int iQuantity, const void * pvSrc, void * pvDst) static
Definition at line 94 of file Wm4System.cpp.
References Memcpy(), and SwapBytes().
Fclose()
int System::Fclose (FILE * pkFile) static
Definition at line 825 of file Wm4System.cpp.
Referenced by Append(), GetPath(), Wm4::ConvexHull1< Real >::Load(), Wm4::ConvexHull3< Real >::Load(), Load(), Wm4::Delaunay1< Real >::Load(), Wm4::Delaunay2< Real >::Load(), Wm4::Delaunay3< Real >::Load(), Wm4::ConvexHull1< Real >::Save(), Wm4::ConvexHull3< Real >::Save(), Save(), Wm4::Delaunay1< Real >::Save(), Wm4::Delaunay2< Real >::Save(), and Wm4::Delaunay3< Real >::Save().
Fopen()
FILE * System::Fopen (const char * acFilename, const char * acMode) static
Definition at line 787 of file Wm4System.cpp.
Referenced by Append(), GetPath(), Wm4::ConvexHull1< Real >::Load(), Wm4::ConvexHull3< Real >::Load(), Load(), Wm4::Delaunay1< Real >::Load(), Wm4::Delaunay2< Real >::Load(), Wm4::Delaunay3< Real >::Load(), Wm4::ConvexHull1< Real >::Save(), Wm4::ConvexHull3< Real >::Save(), Save(), Wm4::Delaunay1< Real >::Save(), Wm4::Delaunay2< Real >::Save(), and Wm4::Delaunay3< Real >::Save().
Fprintf()
int System::Fprintf (FILE * pkFile, const char * acFormat, ...) static
Definition at line 805 of file Wm4System.cpp.
GetDirectory()
const char * System::GetDirectory (int i) static
Definition at line 665 of file Wm4System.cpp.
References SplineSurface::i, and Initialize().
GetDirectoryQuantity()
int System::GetDirectoryQuantity () static
Definition at line 655 of file Wm4System.cpp.
References Initialize().
GetEnv()
const char * System::GetEnv (const char * acEnvVarName) static
Definition at line 830 of file Wm4System.cpp.
References Strcpy().
Referenced by Initialize().
GetPath() [1/2]
const char * System::GetPath (const char * acDirectory, const char * acFilename) static
Definition at line 569 of file Wm4System.cpp.
References Strcat(), and Strcpy().
Referenced by GetPath().
GetPath() [2/2]
const char * System::GetPath (const char * acFilename, int eMode) static
Definition at line 728 of file Wm4System.cpp.
References Fclose(), Fopen(), GetPath(), SplineSurface::i, Initialize(), SM_READ, and SM_WRITE.
GetTime()
double System::GetTime () static
Definition at line 104 of file Wm4System.cpp.
References gs_bInitializedTime, gs_kInitial, and OpenSCADFeatures::long.
Initialize()
void System::Initialize () static
Definition at line 633 of file Wm4System.cpp.
References GetEnv(), Strcpy(), WM4_NEW, and WM4_PATH.
Referenced by GetDirectory(), GetDirectoryQuantity(), GetPath(), InsertDirectory(), RemoveAllDirectories(), and RemoveDirectory().
InsertDirectory()
bool System::InsertDirectory (const char * acDirectory) static
Definition at line 679 of file Wm4System.cpp.
References SplineSurface::i, and Initialize().
IsBigEndian()
bool System::IsBigEndian () static
Definition at line 78 of file Wm4System.cpp.
Load()
bool System::Load (const char * acFilename, char *& racBuffer, int & riSize) static
Definition at line 146 of file Wm4System.cpp.
References Fclose(), Fopen(), WM4_DELETE, and WM4_NEW.
MakeRGB()
unsigned int System::MakeRGB (unsigned char ucR, unsigned char ucG, unsigned char ucB) static
Definition at line 767 of file Wm4System.cpp.
MakeRGBA()
unsigned int System::MakeRGBA (unsigned char ucR, unsigned char ucG, unsigned char ucB, unsigned char ucA) static
Definition at line 777 of file Wm4System.cpp.
Memcpy()
void * System::Memcpy (void * pvDst, size_t uiDstSize, const void * pvSrc, size_t uiSrcSize) static
Definition at line 851 of file Wm4System.cpp.
Referenced by Wm4::PolynomialRoots< Real >::AllRealPartsNegative(), Wm4::PolynomialRoots< Real >::AllRealPartsPositive(), Wm4::ConvexHull2< Real >::ConvexHull2(), Wm4::ConvexHull3< Real >::ConvexHull3(), Wm4::Delaunay2< Real >::Delaunay2(), Wm4::Delaunay3< Real >::Delaunay3(), EndianCopy(), Wm4::QuadraticFit3(), Read1(), Read2be(), Read2le(), Read4be(), Read4le(), Read8be(), Read8le(), Wm4::LinearSystem< Real >::Solve(), Wm4::LinearSystem< Real >::SolveBanded(), Wm4::LinearSystem< Real >::SolveSymmetricCG(), MeshCore::DelaunayTriangulator::Triangulate(), Write1(), Write2be(), Write2le(), Write4be(), Write4le(), Write8be(), and Write8le().
Read1() [1/2]
int System::Read1 (const char * acBuffer, int iQuantity, void * pvData) static
Definition at line 233 of file Wm4System.cpp.
References Memcpy().
Read1() [2/2]
int System::Read1 (FILE * pkFile, int iQuantity, void * pvData) static
Definition at line 249 of file Wm4System.cpp.
Read2be() [1/2]
int System::Read2be (const char * acBuffer, int iQuantity, void * pvData) static
Definition at line 416 of file Wm4System.cpp.
References Memcpy(), and SwapBytes().
Read2be() [2/2]
int System::Read2be (FILE * pkFile, int iQuantity, void * pvData) static
Definition at line 488 of file Wm4System.cpp.
References SwapBytes().
Read2le() [1/2]
int System::Read2le (const char * acBuffer, int iQuantity, void * pvData) static
Definition at line 263 of file Wm4System.cpp.
References Memcpy(), and SwapBytes().
Read2le() [2/2]
int System::Read2le (FILE * pkFile, int iQuantity, void * pvData) static
Definition at line 335 of file Wm4System.cpp.
References SwapBytes().
Read4be() [1/2]
int System::Read4be (const char * acBuffer, int iQuantity, void * pvData) static
Definition at line 428 of file Wm4System.cpp.
References Memcpy(), and SwapBytes().
Read4be() [2/2]
int System::Read4be (FILE * pkFile, int iQuantity, void * pvData) static
Definition at line 498 of file Wm4System.cpp.
References SwapBytes().
Read4le() [1/2]
int System::Read4le (const char * acBuffer, int iQuantity, void * pvData) static
Definition at line 275 of file Wm4System.cpp.
References Memcpy(), and SwapBytes().
Referenced by Wm4::ConvexHull1< Real >::Load(), Wm4::ConvexHull3< Real >::Load(), Wm4::ConvexHull< Real >::Load(), Wm4::Delaunay1< Real >::Load(), Wm4::Delaunay2< Real >::Load(), Wm4::Delaunay3< Real >::Load(), and Wm4::Delaunay< Real >::Load().
Read4le() [2/2]
int System::Read4le (FILE * pkFile, int iQuantity, void * pvData) static
Definition at line 345 of file Wm4System.cpp.
References SwapBytes().
Read8be() [1/2]
int System::Read8be (const char * acBuffer, int iQuantity, void * pvData) static
Definition at line 440 of file Wm4System.cpp.
References Memcpy(), and SwapBytes().
Read8be() [2/2]
int System::Read8be (FILE * pkFile, int iQuantity, void * pvData) static
Definition at line 508 of file Wm4System.cpp.
References SwapBytes().
Read8le() [1/2]
int System::Read8le (const char * acBuffer, int iQuantity, void * pvData) static
Definition at line 287 of file Wm4System.cpp.
References Memcpy(), and SwapBytes().
Referenced by Wm4::ConvexHull1< Real >::Load(), Wm4::ConvexHull3< Real >::Load(), Wm4::Delaunay1< Real >::Load(), Wm4::Delaunay2< Real >::Load(), and Wm4::Delaunay3< Real >::Load().
Read8le() [2/2]
int System::Read8le (FILE * pkFile, int iQuantity, void * pvData) static
Definition at line 355 of file Wm4System.cpp.
References SwapBytes().
RemoveAllDirectories()
void System::RemoveAllDirectories () static
Definition at line 718 of file Wm4System.cpp.
References Initialize().
RemoveDirectory()
bool System::RemoveDirectory (const char * acDirectory) static
Definition at line 698 of file Wm4System.cpp.
References Initialize().
Save()
bool System::Save (const char * acFilename, const char * acBuffer, int iSize) static
Definition at line 181 of file Wm4System.cpp.
References Fclose(), and Fopen().
Sprintf()
int System::Sprintf (char * acDst, size_t uiDstSize, const char * acFormat, ...) static
Definition at line 883 of file Wm4System.cpp.
Strcat()
char * System::Strcat (char * acDst, size_t uiDstSize, const char * acSrc) static
Definition at line 936 of file Wm4System.cpp.
References strcat_s.
Referenced by GetPath().
Strcpy()
char * System::Strcpy (char * acDst, size_t uiDstSize, const char * acSrc) static
Definition at line 903 of file Wm4System.cpp.
References strcpy_s.
Referenced by GetEnv(), GetPath(), and Initialize().
Strncpy()
char * System::Strncpy (char * acDst, size_t uiDstSize, const char * acSrc, size_t uiSrcSize) static
Definition at line 971 of file Wm4System.cpp.
References strncpy_s.
Strtok()
char * System::Strtok (char * acToken, const char * acDelimiters, char *& racNextToken) static
Definition at line 1003 of file Wm4System.cpp.
SwapBytes() [1/2]
void System::SwapBytes (int iSize, int iQuantity, void * pvValue) static
Definition at line 61 of file Wm4System.cpp.
References SplineSurface::i.
SwapBytes() [2/2]
void System::SwapBytes (int iSize, void * pvValue) static
Definition at line 47 of file Wm4System.cpp.
Referenced by EndianCopy(), Read2be(), Read2le(), Read4be(), Read4le(), Read8be(), Read8le(), Write2be(), Write2le(), Write4be(), Write4le(), Write8be(), and Write8le().
Terminate()
void System::Terminate () static
Definition at line 649 of file Wm4System.cpp.
References WM4_DELETE.
Write1() [1/2]
int System::Write1 (char * acBuffer, int iQuantity, const void * pvData) static
Definition at line 241 of file Wm4System.cpp.
References Memcpy().
Write1() [2/2]
int System::Write1 (FILE * pkFile, int iQuantity, const void * pvData) static
Definition at line 256 of file Wm4System.cpp.
Write2be() [1/2]
int System::Write2be (char * acBuffer, int iQuantity, const void * pvData) static
Definition at line 452 of file Wm4System.cpp.
References Memcpy(), and SwapBytes().
Write2be() [2/2]
int System::Write2be (FILE * pkFile, int iQuantity, const void * pvData) static
Definition at line 518 of file Wm4System.cpp.
References SplineSurface::i, and SwapBytes().
Write2le() [1/2]
int System::Write2le (char * acBuffer, int iQuantity, const void * pvData) static
Definition at line 299 of file Wm4System.cpp.
References Memcpy(), and SwapBytes().
Write2le() [2/2]
int System::Write2le (FILE * pkFile, int iQuantity, const void * pvData) static
Definition at line 365 of file Wm4System.cpp.
References SplineSurface::i, and SwapBytes().
Write4be() [1/2]
int System::Write4be (char * acBuffer, int iQuantity, const void * pvData) static
Definition at line 464 of file Wm4System.cpp.
References Memcpy(), and SwapBytes().
Write4be() [2/2]
int System::Write4be (FILE * pkFile, int iQuantity, const void * pvData) static
Definition at line 535 of file Wm4System.cpp.
References SplineSurface::i, and SwapBytes().
Write4le() [1/2]
int System::Write4le (char * acBuffer, int iQuantity, const void * pvData) static
Definition at line 311 of file Wm4System.cpp.
References Memcpy(), and SwapBytes().
Referenced by Wm4::ConvexHull1< Real >::Save(), Wm4::ConvexHull3< Real >::Save(), Wm4::ConvexHull< Real >::Save(), Wm4::Delaunay1< Real >::Save(), Wm4::Delaunay2< Real >::Save(), Wm4::Delaunay3< Real >::Save(), and Wm4::Delaunay< Real >::Save().
Write4le() [2/2]
int System::Write4le (FILE * pkFile, int iQuantity, const void * pvData) static
Definition at line 382 of file Wm4System.cpp.
References SplineSurface::i, and SwapBytes().
Write8be() [1/2]
int System::Write8be (char * acBuffer, int iQuantity, const void * pvData) static
Definition at line 476 of file Wm4System.cpp.
References Memcpy(), and SwapBytes().
Write8be() [2/2]
int System::Write8be (FILE * pkFile, int iQuantity, const void * pvData) static
Definition at line 552 of file Wm4System.cpp.
References SplineSurface::i, and SwapBytes().
Write8le() [1/2]
int System::Write8le (char * acBuffer, int iQuantity, const void * pvData) static
Definition at line 323 of file Wm4System.cpp.
References Memcpy(), and SwapBytes().
Referenced by Wm4::ConvexHull1< Real >::Save(), Wm4::ConvexHull3< Real >::Save(), Wm4::Delaunay1< Real >::Save(), Wm4::Delaunay2< Real >::Save(), and Wm4::Delaunay3< Real >::Save().
Write8le() [2/2]
int System::Write8le (FILE * pkFile, int iQuantity, const void * pvData) static
Definition at line 399 of file Wm4System.cpp.
References SplineSurface::i, and SwapBytes().
Member Data Documentation
WM4_PATH
char System::WM4_PATH static
Definition at line 186 of file Wm4System.h.
Referenced by Initialize().
The documentation for this class was generated from the following files:
Wm4System.h
Wm4System.cpp