FreeCAD: TechDrawGui::QGIGhostHighlight Class Reference
TechDrawGui::QGIGhostHighlight Class Reference
#include <QGIGhostHighlight.h>
Public Types
enum { Type = QGraphicsItem::UserType + 177 }
Public Types inherited from TechDrawGui::QGIHighlight
enum { Type = QGraphicsItem::UserType + 176 }
Public Types inherited from TechDrawGui::QGIDecoration
enum { Type = QGraphicsItem::UserType + 173 }
Signals
void positionChange (QPointF p)
Public Member Functions
QGIGhostHighlight ()
~QGIGhostHighlight () override
int type () const override
void setInteractive (bool state)
void setRadius (double r)
Public Member Functions inherited from TechDrawGui::QGIHighlight
QGIHighlight ()
~QGIHighlight () override
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
void setBounds (double x1, double y1, double x2, double y2)
void setReference (const char *sym)
void setFont (QFont f, double fsize)
void draw () override
void setInteractive (bool state)
void setFeatureName (std::string name)
std::string getFeatureName ()
void setReferenceAngle (double angle)
void onDragFinished () override
void setLinePen (QPen isoPen)
Public Member Functions inherited from TechDrawGui::QGIDecoration
QGIDecoration ()
~QGIDecoration () override=default
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
void setWidth (double w)
double getWidth ()
void setStyle (Qt::PenStyle s)
void setColor (QColor c)
QColor getColor ()
void setFill (Qt::BrushStyle bs)
void makeMark (double x, double y)
void makeMark (Base::Vector3d v)
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
Protected Member Functions inherited from TechDrawGui::QGIHighlight
QColor getHighlightColor ()
void makeHighlight ()
void makeReference ()
void setTools ()
int getHoleStyle ()
Protected Member Functions inherited from TechDrawGui::QGIDecoration
void setPrettyNormal ()
void setPrettyPre ()
void setPrettySel ()
virtual QColor prefNormalColor ()
virtual QColor prefPreColor ()
virtual QColor prefSelectColor ()
Protected Attributes
bool m_dragging
Protected Attributes inherited from TechDrawGui::QGIDecoration
QPen m_pen
QBrush m_brush
QColor m_colCurrent
QColor m_colNormal
double m_width
Qt::PenStyle m_styleCurrent
Qt::BrushStyle m_brushCurrent
int m_dragState
Detailed Description
Definition at line 60 of file QGIGhostHighlight.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 87 of file QGIGhostHighlight.h.
Constructor & Destructor Documentation
QGIGhostHighlight()
QGIGhostHighlight::QGIGhostHighlight () explicit
Definition at line 38 of file QGIGhostHighlight.cpp.
References SCL.SimpleDataTypes::f, TechDrawGui::Rez::guiX(), and importers.importIFCmulticore::setColor().
~QGIGhostHighlight()
QGIGhostHighlight::~QGIGhostHighlight () override
Definition at line 54 of file QGIGhostHighlight.cpp.
Member Function Documentation
mousePressEvent()
void QGIGhostHighlight::mousePressEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 59 of file QGIGhostHighlight.cpp.
References TechDrawGui::QGIDecoration::mousePressEvent().
mouseReleaseEvent()
void QGIGhostHighlight::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) override protected
Definition at line 70 of file QGIGhostHighlight.cpp.
References TechDrawGui::QGIDecoration::mouseReleaseEvent().
positionChange
void TechDrawGui::QGIGhostHighlight::positionChange (QPointF p) signal
Referenced by TechDrawGui::TaskDetail::TaskDetail().
setInteractive()
void QGIGhostHighlight::setInteractive (bool state)
Definition at line 83 of file QGIGhostHighlight.cpp.
setRadius()
void QGIGhostHighlight::setRadius (double r)
Definition at line 92 of file QGIGhostHighlight.cpp.
Referenced by TechDrawGui::TaskDetail::editByHighlight().
type()
int TechDrawGui::QGIGhostHighlight::type () const inline override
Definition at line 88 of file QGIGhostHighlight.h.
Member Data Documentation
m_dragging
bool TechDrawGui::QGIGhostHighlight::m_dragging protected
Definition at line 100 of file QGIGhostHighlight.h.
The documentation for this class was generated from the following files:
QGIGhostHighlight.h
QGIGhostHighlight.cpp