FreeCAD: Points::PointsGrid Class Reference
Points::PointsGrid Class Reference
#include <PointsGrid.h>
Public Member Functions
Construction
PointsGrid (const PointKernel &rclM)
Construction.
PointsGrid ()
Construction.
PointsGrid (const PointKernel &rclM, int iCtGridPerAxis)
Construction.
PointsGrid (const PointKernel &rclM, double fGridLen)
Construction.
PointsGrid (const PointKernel &rclM, unsigned long ulX, unsigned long ulY, unsigned long ulZ)
Construction.
PointsGrid (const PointsGrid &)=default
PointsGrid (PointsGrid &&)=default
virtual ~PointsGrid ()=default
Destruction.
PointsGrid & operator= (const PointsGrid &)=default
PointsGrid & operator= (PointsGrid &&)=default
virtual void Attach (const PointKernel &rclM)
virtual void Rebuild (unsigned long ulPerGrid=256, unsigned long ulMaxGrid=100000)
virtual void Rebuild (int iCtGridPerAxis=20)
virtual void Rebuild (unsigned long ulX, unsigned long ulY, unsigned long ulZ)
Search
virtual unsigned long InSide (const Base::BoundBox3d &rclBB, std::vector< unsigned long > &raulElements, bool bDelDoubles=true) const
virtual unsigned long InSide (const Base::BoundBox3d &rclBB, std::set< unsigned long > &raulElementss) const
virtual unsigned long InSide (const Base::BoundBox3d &rclBB, std::vector< unsigned long > &raulElements, const Base::Vector3d &rclOrg, double fMaxDist, bool bDelDoubles=true) const
void SearchNearestFromPoint (const Base::Vector3d &rclPt, std::set< unsigned long > &rclInd) const
virtual void GetGridLengths (double &rfLenX, double &rfLenY, double &rfLenZ) const
virtual void GetCtGrids (unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
Boundings
class PointsGridIterator
class PointsGridIteratorStatistic
Base::BoundBox3d GetBoundBox (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
Base::BoundBox3d GetBoundBox () const
unsigned long GetCtElements (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
unsigned long FindElements (const Base::Vector3d &rclPoint, std::set< unsigned long > &aulElements) const
virtual void Validate (const PointKernel &rclM)
virtual void Validate ()
virtual bool Verify () const
virtual void Position (const Base::Vector3d &rclPoint, unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
unsigned long GetElements (unsigned long ulX, unsigned long ulY, unsigned long ulZ, std::set< unsigned long > &raclInd) const
bool CheckPos (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
virtual void InitGrid ()
virtual void Clear ()
virtual void CalculateGridLength (unsigned long ulCtGrid, unsigned long ulMaxGrids)
virtual void CalculateGridLength (int iCtGridPerAxis)
virtual void RebuildGrid ()
unsigned long HasElements () const
void GetHull (unsigned long ulX, unsigned long ulY, unsigned long ulZ, unsigned long ulDistance, std::set< unsigned long > &raclInd) const
void AddPoint (const Base::Vector3d &rclPt, unsigned long ulPtIndex, float fEpsilon=0.0f)
void Pos (const Base::Vector3d &rclPoint, unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
Detailed Description
The PointsGrid allows one to divide a global point cloud into smaller regions of elements depending on the resolution of the grid. All grid elements in the grid structure have the same size.
Grids can be used within algorithms to avoid to iterate through all elements, so grids can speed up algorithms dramatically.
Author
Werner Mayer
Definition at line 52 of file PointsGrid.h.
Constructor & Destructor Documentation
PointsGrid() [1/7]
PointsGrid::PointsGrid (const PointKernel & rclM) explicit
Construction.
Definition at line 30 of file PointsGrid.cpp.
References RebuildGrid().
PointsGrid() [2/7]
PointsGrid::PointsGrid ()
Construction.
Definition at line 46 of file PointsGrid.cpp.
PointsGrid() [3/7]
PointsGrid::PointsGrid (const PointKernel & rclM, int iCtGridPerAxis)
Construction.
Definition at line 79 of file PointsGrid.cpp.
References Rebuild().
PointsGrid() [4/7]
PointsGrid::PointsGrid (const PointKernel & rclM, double fGridLen)
Construction.
Definition at line 95 of file PointsGrid.cpp.
References Base::BoundBox3< Precision >::Add(), Base::BoundBox3< Precision >::LengthX(), Base::BoundBox3< Precision >::LengthY(), Base::BoundBox3< Precision >::LengthZ(), and Rebuild().
PointsGrid() [5/7]
PointsGrid::PointsGrid (const PointKernel & rclM, unsigned long ulX, unsigned long ulY, unsigned long ulZ)
Construction.
Definition at line 60 of file PointsGrid.cpp.
References Rebuild().
PointsGrid() [6/7]
Points::PointsGrid::PointsGrid (const PointsGrid &) default
PointsGrid() [7/7]
Points::PointsGrid::PointsGrid (PointsGrid &&) default
~PointsGrid()
virtual Points::PointsGrid::~PointsGrid () virtual default
Destruction.
Member Function Documentation
AddPoint()
void PointsGrid::AddPoint (const Base::Vector3d & rclPt, unsigned long ulPtIndex, float fEpsilon = 0.0f) protected
Adds a new point element to the grid structure. rclPt is the geometric point and ulPtIndex the corresponding index in the point kernel.
Definition at line 694 of file PointsGrid.cpp.
References Pos(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by RebuildGrid().
Attach()
void PointsGrid::Attach (const PointKernel & rclM) virtual
Attaches the point kernel to this grid, an already attached point cloud gets detached. The grid gets rebuilt automatically.
Definition at line 117 of file PointsGrid.cpp.
References RebuildGrid().
Referenced by Validate().
CalculateGridLength() [1/2]
void PointsGrid::CalculateGridLength (int iCtGridPerAxis) protected virtual
Calculates the grid length dependent on the number of grids per axis.
Definition at line 385 of file PointsGrid.cpp.
References Base::BoundBox3< Precision >::Add(), Base::BoundBox3< Precision >::CalcDiagonalLength(), CalculateGridLength(), Base::BoundBox3< Precision >::LengthX(), Base::BoundBox3< Precision >::LengthY(), Base::BoundBox3< Precision >::LengthZ(), POINTS_CT_GRID, POINTS_MAX_GRIDS, Base::pow(), and KDL::sqrt().
CalculateGridLength() [2/2]
void PointsGrid::CalculateGridLength (unsigned long ulCtGrid, unsigned long ulMaxGrids) protected virtual
Calculates the grid length dependent on maximum number of grids.
Definition at line 344 of file PointsGrid.cpp.
References Base::BoundBox3< Precision >::Add(), Base::BoundBox3< Precision >::LengthX(), Base::BoundBox3< Precision >::LengthY(), Base::BoundBox3< Precision >::LengthZ(), and Base::pow().
Referenced by CalculateGridLength(), InitGrid(), and Rebuild().
CheckPos()
bool Points::PointsGrid::CheckPos (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const inline protected
Checks if this is a valid grid position.
Definition at line 350 of file PointsGrid.h.
Referenced by Points::PointsGridIterator::NextOnRay().
Clear()
void PointsGrid::Clear () protected virtual
Deletes the grid structure.
Definition at line 123 of file PointsGrid.cpp.
FindElements()
unsigned long PointsGrid::FindElements (const Base::Vector3d & rclPoint, std::set< unsigned long > & aulElements) const
Finds all points that lie in the same grid as the point rclPoint.
Definition at line 772 of file PointsGrid.cpp.
References GetElements(), and Pos().
GetBoundBox() [1/2]
Base::BoundBox3d Points::PointsGrid::GetBoundBox () const inline
Returns the bounding box of the whole.
Definition at line 340 of file PointsGrid.h.
Referenced by InSide(), and SearchNearestFromPoint().
GetBoundBox() [2/2]
Base::BoundBox3d Points::PointsGrid::GetBoundBox (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const inline
Returns the bounding box of a given grid element.
Definition at line 329 of file PointsGrid.h.
Referenced by Points::PointsGridIterator::InitOnRay(), and Points::PointsGridIterator::NextOnRay().
GetCtElements()
unsigned long Points::PointsGrid::GetCtElements (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const inline
Returns the number of elements in a given grid.
Definition at line 131 of file PointsGrid.h.
GetCtGrids()
virtual void Points::PointsGrid::GetCtGrids (unsigned long & rulX, unsigned long & rulY, unsigned long & rulZ) const inline virtual
Returns the number of grid elements in x,y and z direction.
Definition at line 115 of file PointsGrid.h.
GetElements()
unsigned long PointsGrid::GetElements (unsigned long ulX, unsigned long ulY, unsigned long ulZ, std::set< unsigned long > & raclInd) const
Returns the indices of the elements in the given grid.
Definition at line 680 of file PointsGrid.cpp.
Referenced by FindElements(), Inspection::InspectNominalPoints::getDistance(), and GetHull().
GetGridLengths()
virtual void Points::PointsGrid::GetGridLengths (double & rfLenX, double & rfLenY, double & rfLenZ) const inline virtual
Returns the lengths of the grid elements in x,y and z direction.
Definition at line 108 of file PointsGrid.h.
GetHull()
void PointsGrid::GetHull (unsigned long ulX, unsigned long ulY, unsigned long ulZ, unsigned long ulDistance, std::set< unsigned long > & raclInd) const protected
Get the indices of all elements lying in the grids around a given grid with distance ulDistance.
Definition at line 629 of file PointsGrid.cpp.
References GetElements(), and SplineSurface::i.
Referenced by SearchNearestFromPoint().
HasElements()
unsigned long Points::PointsGrid::HasElements () const inline protected
Returns the number of stored elements.
Definition at line 170 of file PointsGrid.h.
Referenced by Rebuild().
InitGrid()
void PointsGrid::InitGrid () protected virtual
Initializes the size of the internal structure.
Definition at line 152 of file PointsGrid.cpp.
References Base::BoundBox3< Precision >::Add(), CalculateGridLength(), SplineSurface::i, Base::BoundBox3< Precision >::LengthX(), Base::BoundBox3< Precision >::LengthY(), Base::BoundBox3< Precision >::LengthZ(), Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, Base::BoundBox3< Precision >::MinZ, POINTS_CT_GRID, and POINTS_MAX_GRIDS.
Referenced by RebuildGrid().
InSide() [1/3]
unsigned long PointsGrid::InSide (const Base::BoundBox3d & rclBB, std::set< unsigned long > & raulElementss) const virtual
Searches for elements lying in the intersection area of the grid and the bounding box.
Definition at line 291 of file PointsGrid.cpp.
References SplineSurface::i, Base::BoundBox3< Precision >::MaxX, Base::BoundBox3< Precision >::MaxY, Base::BoundBox3< Precision >::MaxZ, Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, Base::BoundBox3< Precision >::MinZ, and Position().
InSide() [2/3]
unsigned long PointsGrid::InSide (const Base::BoundBox3d & rclBB, std::vector< unsigned long > & raulElements, bool bDelDoubles = true) const virtual
Searches for elements lying in the intersection area of the grid and the bounding box.
Definition at line 215 of file PointsGrid.cpp.
References SplineSurface::i, Base::BoundBox3< Precision >::MaxX, Base::BoundBox3< Precision >::MaxY, Base::BoundBox3< Precision >::MaxZ, Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, Base::BoundBox3< Precision >::MinZ, and Position().
InSide() [3/3]
unsigned long PointsGrid::InSide (const Base::BoundBox3d & rclBB, std::vector< unsigned long > & raulElements, const Base::Vector3d & rclOrg, double fMaxDist, bool bDelDoubles = true) const virtual
Searches for elements lying in the intersection area of the grid and the bounding box.
Definition at line 252 of file PointsGrid.cpp.
References Base::BoundBox3< Precision >::CalcDiagonalLength(), Base::DistanceP2(), GetBoundBox(), SplineSurface::i, Base::BoundBox3< Precision >::MaxX, Base::BoundBox3< Precision >::MaxY, Base::BoundBox3< Precision >::MaxZ, Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, Base::BoundBox3< Precision >::MinZ, and Position().
operator=() [1/2]
PointsGrid& Points::PointsGrid::operator= (const PointsGrid &) default
operator=() [2/2]
PointsGrid& Points::PointsGrid::operator= (PointsGrid &&) default
Pos()
void PointsGrid::Pos (const Base::Vector3d & rclPoint, unsigned long & rulX, unsigned long & rulY, unsigned long & rulZ) const protected
Returns the grid numbers to the given point rclPoint.
Definition at line 762 of file PointsGrid.cpp.
References OpenSCADFeatures::long, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by AddPoint(), and FindElements().
Position()
void PointsGrid::Position (const Base::Vector3d & rclPoint, unsigned long & rulX, unsigned long & rulY, unsigned long & rulZ) const virtual
Returns the indices of the grid this point lies in. If the point is outside the grid then the indices of the nearest grid element are taken.
Definition at line 314 of file PointsGrid.cpp.
References Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by Inspection::InspectNominalPoints::getDistance(), Points::PointsGridIterator::InitOnRay(), InSide(), and SearchNearestFromPoint().
Rebuild() [1/3]
void PointsGrid::Rebuild (int iCtGridPerAxis = 20) virtual
Rebuilds the grid structure.
Definition at line 145 of file PointsGrid.cpp.
References CalculateGridLength(), HasElements(), and RebuildGrid().
Rebuild() [2/3]
void PointsGrid::Rebuild (unsigned long ulPerGrid = 256, unsigned long ulMaxGrid = 100000) virtual
Rebuilds the grid structure.
Definition at line 138 of file PointsGrid.cpp.
References CalculateGridLength(), HasElements(), and RebuildGrid().
Referenced by PointsGrid().
Rebuild() [3/3]
void PointsGrid::Rebuild (unsigned long ulX, unsigned long ulY, unsigned long ulZ) virtual
Rebuilds the grid structure.
Definition at line 129 of file PointsGrid.cpp.
References HasElements(), and RebuildGrid().
RebuildGrid()
void PointsGrid::RebuildGrid () protected virtual
Rebuilds the grid structure.
Definition at line 748 of file PointsGrid.cpp.
References AddPoint(), SplineSurface::i, InitGrid(), and Points::PointKernel::size().
Referenced by Attach(), PointsGrid(), Rebuild(), and Validate().
SearchNearestFromPoint()
void PointsGrid::SearchNearestFromPoint (const Base::Vector3d & rclPt, std::set< unsigned long > & rclInd) const
Searches for the nearest grids that contain elements from a point, the result are grid indices.
Definition at line 530 of file PointsGrid.cpp.
References Base::BoundBox3< double >::BACK, Base::BoundBox3< double >::BOTTOM, Base::BoundBox3< double >::FRONT, GetBoundBox(), Base::BoundBox3< Precision >::GetCenter(), GetHull(), Base::BoundBox3< Precision >::GetSideFromRay(), SplineSurface::i, Base::BoundBox3< Precision >::IsInBox(), Base::BoundBox3< double >::LEFT, Position(), Base::BoundBox3< double >::RIGHT, and Base::BoundBox3< double >::TOP.
Validate() [1/2]
void PointsGrid::Validate () virtual
Validates the grid structure and rebuilds it if needed.
Definition at line 713 of file PointsGrid.cpp.
References RebuildGrid(), and Points::PointKernel::size().
Validate() [2/2]
void PointsGrid::Validate (const PointKernel & rclM) virtual
Validates the grid structure and rebuilds it if needed.
Definition at line 703 of file PointsGrid.cpp.
References Attach(), RebuildGrid(), and Points::PointKernel::size().
Verify()
bool PointsGrid::Verify () const virtual
Verifies the grid structure and returns false if inconsistencies are found.
Definition at line 724 of file PointsGrid.cpp.
References Points::PointsGridIterator::GetBoundBox(), Points::PointsGridIterator::GetElements(), Points::PointKernel::getPoint(), Points::PointsGridIterator::Init(), Base::BoundBox3< Precision >::IsInBox(), Points::PointsGridIterator::More(), Points::PointsGridIterator::Next(), and Points::PointKernel::size().
Friends And Related Function Documentation
PointsGridIterator
friend class PointsGridIterator friend
Definition at line 198 of file PointsGrid.h.
PointsGridIteratorStatistic
friend class PointsGridIteratorStatistic friend
Definition at line 199 of file PointsGrid.h.
The documentation for this class was generated from the following files:
PointsGrid.h
PointsGrid.cpp