FreeCAD: Gui::DocumentObjectItem Class Reference
Gui::DocumentObjectItem Class Reference
#include <Tree.h>
Public Member Functions
DocumentObjectItem (DocumentItem *ownerDocItem, DocumentObjectDataPtr data)
~DocumentObjectItem () override
Gui::ViewProviderDocumentObject * object () const
void testStatus (bool resetStatus, QIcon &icon1, QIcon &icon2)
void testStatus (bool resetStatus)
void displayStatusInfo ()
void setExpandedStatus (bool)
void setData (int column, int role, const QVariant &value) override
bool isChildOfItem (DocumentObjectItem *)
void restoreBackground ()
DocumentItem * getParentDocument () const
DocumentItem * getOwnerDocument () const
bool requiredAtRoot (bool excludeSelf=true) const
App::DocumentObject * getFullSubName (std::ostringstream &str, DocumentObjectItem *parent=nullptr) const
App::DocumentObject * getRelativeParent (std::ostringstream &str, DocumentObjectItem *cousin, App::DocumentObject **topParent=nullptr, std::string *topSubname=nullptr) const
int getSubName (std::ostringstream &str, App::DocumentObject *&topParent) const
const std::vector< std::string > & getSubNames () const
void setHighlight (bool set, HighlightMode mode=HighlightMode::LightBlue)
const char * getName () const
const char * getTreeName () const
bool isLink () const
bool isLinkFinal () const
bool isParentLink () const
int isGroup () const
int isParentGroup () const
DocumentObjectItem * getParentItem () const
DocumentObjectItem * getNextSibling () const
DocumentObjectItem * getPreviousSibling () const
TreeWidget * getTree () const
Friends
class TreeWidget
class DocumentItem
Detailed Description
The link between the tree and a document object. Every object in the document gets its associated DocumentObjectItem which controls the visibility and the functions of the object.
Author
Werner Mayer
Definition at line 407 of file Tree.h.
Constructor & Destructor Documentation
DocumentObjectItem()
DocumentObjectItem::DocumentObjectItem (DocumentItem * ownerDocItem, DocumentObjectDataPtr data)
Definition at line 5188 of file Tree.cpp.
References countItems, UtilsAssembly::getObject(), and TREE_LOG.
~DocumentObjectItem()
DocumentObjectItem::~DocumentObjectItem () override
Definition at line 5200 of file Tree.cpp.
References countItems, UtilsAssembly::getObject(), Gui::DocumentItem::getTree(), and TREE_LOG.
Member Function Documentation
displayStatusInfo()
void DocumentObjectItem::displayStatusInfo ()
Definition at line 5512 of file Tree.cpp.
References Gui::MainWindow::Err, Gui::getMainWindow(), Base::Type::getName(), App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), App::DocumentObject::getStatusString(), Base::Persistence::getTypeId(), Path.Log::info(), App::DocumentObject::isError(), App::DocumentObject::mustExecute(), object(), RobotExample::pos, Gui::MainWindow::showMessage(), Gui::MainWindow::showStatus(), and src.Mod.AddonManager.Addon::translate.
getFullSubName()
App::DocumentObject * DocumentObjectItem::getFullSubName (std::ostringstream & str, DocumentObjectItem * parent = nullptr) const
Definition at line 5757 of file Tree.cpp.
References getName(), Gui::ViewProviderDocumentObject::getObject(), getParentItem(), object(), Init::parent, ClipperLib::pi, and Path.Post.scripts.refactored_centroid_post::str.
getName()
const char * DocumentObjectItem::getName () const
Definition at line 5711 of file Tree.cpp.
References App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), and object().
Referenced by Gui::DocumentItem::findItem(), getFullSubName(), getRelativeParent(), and setData().
getNextSibling()
DocumentObjectItem * DocumentObjectItem::getNextSibling () const
Definition at line 5677 of file Tree.cpp.
References Gui::TreeWidget::ObjectType, and Init::parent.
getOwnerDocument()
DocumentItem * DocumentObjectItem::getOwnerDocument () const
Definition at line 5829 of file Tree.cpp.
Referenced by Gui::TreeWidget::onShowHidden(), Gui::DocumentItem::populateItem(), requiredAtRoot(), setExpandedStatus(), and testStatus().
getParentDocument()
DocumentItem * DocumentObjectItem::getParentDocument () const
Definition at line 5825 of file Tree.cpp.
References Gui::TreeWidget::getDocumentItem(), and getTree().
getParentItem()
DocumentObjectItem * DocumentObjectItem::getParentItem () const
Definition at line 5671 of file Tree.cpp.
References Gui::TreeWidget::ObjectType, Init::parent, and Path.Post.scripts.grbl_post::type.
Referenced by getFullSubName(), getSubName(), isGroup(), isParentGroup(), isParentLink(), requiredAtRoot(), testStatus(), and Gui::DocumentItem::updateItemSelection().
getPreviousSibling()
DocumentObjectItem * DocumentObjectItem::getPreviousSibling () const
Definition at line 5695 of file Tree.cpp.
References Gui::TreeWidget::ObjectType, and Init::parent.
getRelativeParent()
App::DocumentObject * DocumentObjectItem::getRelativeParent (std::ostringstream & str, DocumentObjectItem * cousin, App::DocumentObject ** topParent = nullptr, std::string * topSubname = nullptr) const
Definition at line 5769 of file Tree.cpp.
References dot(), FC_ERR, App::DocumentObject::getFullName(), getName(), getSubName(), App::DocumentObject::getSubObject(), and Path.Post.scripts.refactored_centroid_post::str.
getSubName()
int DocumentObjectItem::getSubName (std::ostringstream & str, App::DocumentObject *& topParent) const
Definition at line 5716 of file Tree.cpp.
References App::DocumentObject::getNameInDocument(), getParentItem(), toolbit-attributes::group, App::DocumentObject::isAttachedToDocument(), NotGroup, Init::parent, PartGroup, App::DocumentObject::redirectSubName(), Path.Post.scripts.refactored_centroid_post::str, and SuperGroup.
Referenced by getRelativeParent(), Gui::DocumentItem::slotExpandObject(), and Gui::DocumentItem::updateItemSelection().
getSubNames()
const std::vector<std::string>& Gui::DocumentObjectItem::getSubNames () const inline
Definition at line 449 of file Tree.h.
getTree()
TreeWidget * DocumentObjectItem::getTree () const
Definition at line 5833 of file Tree.cpp.
Referenced by getParentDocument(), and testStatus().
getTreeName()
const char * DocumentObjectItem::getTreeName () const
Definition at line 5285 of file Tree.cpp.
isChildOfItem()
bool DocumentObjectItem::isChildOfItem (DocumentObjectItem * item)
Definition at line 5562 of file Tree.cpp.
References Init::parent.
Referenced by Gui::DocumentItem::populateItem().
isGroup()
int DocumentObjectItem::isGroup () const
Definition at line 5630 of file Tree.cpp.
References App::DocumentObjectExtension::getExtensionClassTypeId(), App::DocumentObject::getLinkedObject(), App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), getParentItem(), App::DocumentObject::hasChildElement(), App::ExtensionContainer::hasExtension(), LinkGroup, NotGroup, object(), Init::parent, and PartGroup.
isLink()
bool DocumentObjectItem::isLink () const
Definition at line 5605 of file Tree.cpp.
References App::DocumentObject::getLinkedObject(), Gui::ViewProviderDocumentObject::getObject(), and object().
isLinkFinal()
bool DocumentObjectItem::isLinkFinal () const
Definition at line 5611 of file Tree.cpp.
References App::DocumentObject::getLinkedObject(), Gui::ViewProviderDocumentObject::getObject(), and object().
isParentGroup()
int DocumentObjectItem::isParentGroup () const
Definition at line 5666 of file Tree.cpp.
References getParentItem(), and ClipperLib::pi.
Referenced by Gui::DocumentItem::findItemByObject(), and Gui::DocumentItem::getTopParent().
isParentLink()
bool DocumentObjectItem::isParentLink () const
Definition at line 5618 of file Tree.cpp.
References getParentItem(), and ClipperLib::pi.
object()
Gui::ViewProviderDocumentObject * DocumentObjectItem::object () const
Definition at line 5290 of file Tree.cpp.
Referenced by displayStatusInfo(), Gui::DocumentItem::findItem(), getFullSubName(), getName(), Gui::TreeWidget::getSelection(), isGroup(), isLink(), isLinkFinal(), Gui::TreeWidget::onToggleVisibilityInTree(), Gui::DocumentItem::populateItem(), Gui::DocumentItem::selectItems(), setData(), setExpandedStatus(), testStatus(), and Gui::DocumentItem::updateItemSelection().
requiredAtRoot()
bool DocumentObjectItem::requiredAtRoot (bool excludeSelf = true) const
Definition at line 5570 of file Tree.cpp.
References UtilsAssembly::getObject(), getOwnerDocument(), getParentItem(), Init::parent, and ClipperLib::pi.
restoreBackground()
void DocumentObjectItem::restoreBackground ()
Definition at line 5218 of file Tree.cpp.
setData()
void DocumentObjectItem::setData (int column, int role, const QVariant & value) override
Definition at line 5540 of file Tree.cpp.
References App::ExpressionParser::column, toolbit-attributes::doc, App::DocumentObject::getDocument(), getName(), Gui::ViewProviderDocumentObject::getObject(), App::DocumentObject::Label, App::DocumentObject::Label2, object(), and Path.Post.scripts.refactored_centroid_post::str.
Referenced by Gui::TreeWidget::synchronizeSelectionCheckBoxes(), and testStatus().
setExpandedStatus()
void DocumentObjectItem::setExpandedStatus (bool on)
Definition at line 5534 of file Tree.cpp.
References App::Expand, Gui::ViewProviderDocumentObject::getObject(), getOwnerDocument(), object(), and App::DocumentObject::setStatus().
setHighlight()
void DocumentObjectItem::setHighlight (bool set, Gui::HighlightMode high = HighlightMode::LightBlue)
Definition at line 5222 of file Tree.cpp.
References Gui::Blue, Gui::Bold, SCL.SimpleDataTypes::f, App::GetApplication(), ParameterGrp::GetBool(), App::Application::GetParameterGroupByPath(), ParameterGrp::GetUnsigned(), highlight(), Gui::Italic, Gui::LightBlue, Gui::Overlined, Gui::StrikeOut, Gui::Underlined, and Gui::UserDefined.
Referenced by Gui::DocumentItem::populateItem().
testStatus() [1/2]
void DocumentObjectItem::testStatus (bool resetStatus)
Definition at line 5295 of file Tree.cpp.
References testStatus().
testStatus() [2/2]
void DocumentObjectItem::testStatus (bool resetStatus, QIcon & icon1, QIcon & icon2)
Definition at line 5312 of file Tree.cpp.
References _Timing, _TimingStop, Gui::BitmapFactory(), Gui::BitmapFactoryInst::BottomRight, App::ExpressionParser::column, Gui::DocumentItem::document(), App::Error, create_qrc::ext, Gui::ViewProviderDocumentObject::getDocument(), App::DocumentObject::getDocument(), App::DocumentObjectExtension::getExtensionClassTypeId(), Gui::ViewProvider::getIcon(), bimcommands.BimIfcElements::getIcon(), App::DocumentObject::getLinkedObject(), Gui::getMainWindow(), App::DocumentObject::getNameInDocument(), Gui::ViewProviderDocumentObject::getObject(), getOwnerDocument(), getParentItem(), getTree(), App::ExtensionContainer::hasExtension(), App::DocumentObject::isElementVisible(), App::DocumentObject::isError(), App::DocumentObject::isFreezed(), Gui::ViewProvider::isShow(), App::DocumentObject::isTouched(), isVisibilityIconEnabled(), Gui::BitmapFactoryInst::merge(), Gui::ViewProvider::mergeColorfulOverlayIcons(), App::DocumentObject::mustExecute(), geoff_geometry::Normal(), object(), geoff_geometry::On(), Init::parent, Gui::BitmapFactoryInst::pixmap(), Gui::BitmapFactoryInst::pixmapFromSvg(), App::Recompute, setData(), Gui::ViewProviderDocumentObject::showInTree(), Timing, TimingStop, Gui::BitmapFactoryInst::TopLeft, Gui::BitmapFactoryInst::TopRight, and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by testStatus(), and Gui::TreeWidget::updateVisibilityIcons().
Friends And Related Function Documentation
DocumentItem
friend class DocumentItem friend
Definition at line 484 of file Tree.h.
TreeWidget
friend class TreeWidget friend
Definition at line 483 of file Tree.h.
The documentation for this class was generated from the following files:
Tree.h
Tree.cpp