FreeCAD: Sketcher::SketchGeometryExtension Class Reference
Sketcher::SketchGeometryExtension Class Reference
#include <SketchGeometryExtension.h>
Public Member Functions
SketchGeometryExtension ()
SketchGeometryExtension (long cid)
~SketchGeometryExtension () override=default
std::unique_ptr< Part::GeometryExtension > copy () const override
PyObject * getPyObject () override
long getId () const override
void setId (long id) override
InternalType::InternalType getInternalType () const override
void setInternalType (InternalType::InternalType type) override
bool testGeometryMode (int flag) const override
void setGeometryMode (int flag, bool v=true) override
int getGeometryLayerId () const override
void setGeometryLayerId (int geolayer) override
Public Member Functions inherited from Part::GeometryPersistenceExtension
~GeometryPersistenceExtension () override=default
void Save (Base::Writer &) const
void Restore (Base::XMLReader &)
bool isSame (const GeometryPersistenceExtension &other) const
Public Member Functions inherited from Part::GeometryExtension
~GeometryExtension () override=default
PyObject * copyPyObject () const
void setName (const std::string &str)
const std::string & getName () const
virtual void notifyAttachment (Part::Geometry *)
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static bool getInternalTypeFromName (std::string str, InternalType::InternalType &type)
static bool getGeometryModeFromName (std::string str, GeometryMode::GeometryMode &type)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Public Attributes
constexpr static std::array< const char *, InternalType::NumInternalGeometryType > internaltype2str
constexpr static std::array< const char *, GeometryMode::NumGeometryMode > geometrymode2str
Protected Member Functions
void copyAttributes (Part::GeometryExtension *cpy) const override
void restoreAttributes (Base::XMLReader &reader) override
void saveAttributes (Base::Writer &writer) const override
void preSave (Base::Writer &writer) const override
void postSave (Base::Writer &writer) const override
Protected Member Functions inherited from Part::GeometryExtension
GeometryExtension ()
GeometryExtension (const GeometryExtension &obj)=default
GeometryExtension & operator= (const GeometryExtension &obj)=default
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 108 of file SketchGeometryExtension.h.
Constructor & Destructor Documentation
SketchGeometryExtension() [1/2]
SketchGeometryExtension::SketchGeometryExtension ()
Definition at line 45 of file SketchGeometryExtension.cpp.
Referenced by getPyObject().
SketchGeometryExtension() [2/2]
SketchGeometryExtension::SketchGeometryExtension (long cid) explicit
Definition at line 51 of file SketchGeometryExtension.cpp.
~SketchGeometryExtension()
Sketcher::SketchGeometryExtension::~SketchGeometryExtension () override default
Member Function Documentation
copy()
std::unique_ptr< Part::GeometryExtension > SketchGeometryExtension::copy () const override virtual
Implements Part::GeometryExtension.
Definition at line 105 of file SketchGeometryExtension.cpp.
References copyAttributes(), and Path.Post.scripts.opensbp_post::move().
copyAttributes()
void SketchGeometryExtension::copyAttributes (Part::GeometryExtension * cpy) const override protected virtual
Reimplemented from Part::GeometryExtension.
Definition at line 57 of file SketchGeometryExtension.cpp.
References Part::GeometryExtension::copyAttributes().
Referenced by copy().
getGeometryLayerId()
int Sketcher::SketchGeometryExtension::getGeometryLayerId () const inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 149 of file SketchGeometryExtension.h.
getGeometryModeFromName()
bool SketchGeometryExtension::getGeometryModeFromName (std::string str, GeometryMode::GeometryMode & type) static
Definition at line 142 of file SketchGeometryExtension.cpp.
References Sketcher::end, geometrymode2str, RobotExample::pos, Path.Post.scripts.refactored_centroid_post::str, Path.Post.scripts.grbl_post::type, and toolbit-attributes::val.
getId()
long Sketcher::SketchGeometryExtension::getId () const inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 122 of file SketchGeometryExtension.h.
getInternalType()
InternalType::InternalType Sketcher::SketchGeometryExtension::getInternalType () const inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 131 of file SketchGeometryExtension.h.
getInternalTypeFromName()
bool SketchGeometryExtension::getInternalTypeFromName (std::string str, InternalType::InternalType & type) static
Definition at line 123 of file SketchGeometryExtension.cpp.
References Sketcher::end, internaltype2str, RobotExample::pos, Path.Post.scripts.refactored_centroid_post::str, Path.Post.scripts.grbl_post::type, and toolbit-attributes::val.
getPyObject()
PyObject * SketchGeometryExtension::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Implements Part::GeometryExtension.
Definition at line 118 of file SketchGeometryExtension.cpp.
References SketchGeometryExtension().
postSave()
void SketchGeometryExtension::postSave (Base::Writer & writer) const override protected virtual
Reimplemented from Part::GeometryMigrationPersistenceExtension.
Definition at line 99 of file SketchGeometryExtension.cpp.
References Sketcher::GeometryMode::Construction, Base::Writer::ind(), and Base::Writer::Stream().
preSave()
void SketchGeometryExtension::preSave (Base::Writer & writer) const override protected virtual
Reimplemented from Part::GeometryMigrationPersistenceExtension.
Definition at line 94 of file SketchGeometryExtension.cpp.
References Base::Writer::Stream().
restoreAttributes()
void SketchGeometryExtension::restoreAttributes (Base::XMLReader & reader) override protected virtual
Reimplemented from Part::GeometryPersistenceExtension.
Definition at line 67 of file SketchGeometryExtension.cpp.
References TechDrawTools.TaskFillTemplateFields::reader, and Part::GeometryPersistenceExtension::restoreAttributes().
saveAttributes()
void SketchGeometryExtension::saveAttributes (Base::Writer & writer) const override protected virtual
Reimplemented from Part::GeometryPersistenceExtension.
Definition at line 85 of file SketchGeometryExtension.cpp.
References Part::GeometryPersistenceExtension::saveAttributes(), and Base::Writer::Stream().
setGeometryLayerId()
void Sketcher::SketchGeometryExtension::setGeometryLayerId (int geolayer) inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 153 of file SketchGeometryExtension.h.
setGeometryMode()
void Sketcher::SketchGeometryExtension::setGeometryMode (int flag, bool v = true) inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 144 of file SketchGeometryExtension.h.
setId()
void Sketcher::SketchGeometryExtension::setId (long id) inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 126 of file SketchGeometryExtension.h.
setInternalType()
void Sketcher::SketchGeometryExtension::setInternalType (InternalType::InternalType type) inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 135 of file SketchGeometryExtension.h.
testGeometryMode()
bool Sketcher::SketchGeometryExtension::testGeometryMode (int flag) const inline override virtual
Implements Sketcher::ISketchGeometryExtension.
Definition at line 140 of file SketchGeometryExtension.h.
Member Data Documentation
geometrymode2str
constexpr std::array< const char *, GeometryMode::NumGeometryMode > SketchGeometryExtension::geometrymode2str static constexpr
Initial value:
{
        {"Blocked", "Construction"}}
Definition at line 172 of file SketchGeometryExtension.h.
Referenced by getGeometryModeFromName().
internaltype2str
constexpr std::array< const char *, InternalType::NumInternalGeometryType > SketchGeometryExtension::internaltype2str static constexpr
Initial value:
{{"None",
                           "EllipseMajorDiameter",
                           "EllipseMinorDiameter",
                           "EllipseFocus1",
                           "EllipseFocus2",
                           "HyperbolaMajor",
                           "HyperbolaMinor",
                           "HyperbolaFocus",
                           "ParabolaFocus",
                           "BSplineControlPoint",
                           "BSplineKnotPoint",
                           "ParabolaFocalAxis"}}
Definition at line 159 of file SketchGeometryExtension.h.
Referenced by getInternalTypeFromName().
The documentation for this class was generated from the following files:
SketchGeometryExtension.h
SketchGeometryExtension.cpp