FreeCAD: Gui::SoFCOffscreenRenderer Class Reference
Gui::SoFCOffscreenRenderer Class Reference
#include <SoFCOffscreenRenderer.h>
Public Member Functions
SoFCOffscreenRenderer (const SoFCOffscreenRenderer &)=delete
SoFCOffscreenRenderer & operator= (const SoFCOffscreenRenderer &)=delete
void writeToImage (QImage &) const
void writeToImageFile (const char *filename, const char *comment, const SbMatrix &mat, const QImage &img)
QStringList getWriteImageFiletypeInfo ()
std::string createMIBA (const SbMatrix &mat) const
Static Public Member Functions
static SoFCOffscreenRenderer & instance ()
Protected Member Functions
SoFCOffscreenRenderer (const SbViewportRegion &viewportregion)
SoFCOffscreenRenderer (SoGLRenderAction *action)
~SoFCOffscreenRenderer ()
Detailed Description
The SoFCOffscreenRenderer class is used for rendering scenes in offscreen buffers.
Author
Werner Mayer
Definition at line 63 of file SoFCOffscreenRenderer.h.
Constructor & Destructor Documentation
SoFCOffscreenRenderer() [1/3]
Gui::SoFCOffscreenRenderer::SoFCOffscreenRenderer (const SoFCOffscreenRenderer &) delete
SoFCOffscreenRenderer() [2/3]
SoFCOffscreenRenderer::SoFCOffscreenRenderer (const SbViewportRegion & viewportregion) protected
Constructor. Argument is the viewportregion we should use when rendering. An internal SoGLRenderAction will be constructed.
Definition at line 76 of file SoFCOffscreenRenderer.cpp.
SoFCOffscreenRenderer() [3/3]
SoFCOffscreenRenderer::SoFCOffscreenRenderer (SoGLRenderAction * action) protected
Constructor. Argument is the action we should apply to the scene graph when rendering the scene. Information about the viewport is extracted from the action.
Definition at line 81 of file SoFCOffscreenRenderer.cpp.
~SoFCOffscreenRenderer()
SoFCOffscreenRenderer::~SoFCOffscreenRenderer () protected default
Destructor.
Member Function Documentation
createMIBA()
std::string SoFCOffscreenRenderer::createMIBA (const SbMatrix & mat) const
Definition at line 261 of file SoFCOffscreenRenderer.cpp.
References App::Application::Config(), and App::Application::getExecutableName().
Referenced by writeToImageFile().
getWriteImageFiletypeInfo()
QStringList SoFCOffscreenRenderer::getWriteImageFiletypeInfo ()
This method returns all image file formats supported by Coin3D (see getWriteFiletypeInfo()) with all QImage file formats that are not directly supported by Coin3D, if so.
Definition at line 222 of file SoFCOffscreenRenderer.cpp.
References create_qrc::ext, and SplineSurface::i.
instance()
SoFCOffscreenRenderer & SoFCOffscreenRenderer::instance () static
The SoOffscreenRenderer base class seems to have a huge memory leak. Whenever an instance is created internal memory doesn't get freed when destroying it. Thus, SoFCOffscreenRenderer is implemented as singleton to allow one to create only one global instance. So, the memory is leaking for this instance only.
Definition at line 69 of file SoFCOffscreenRenderer.cpp.
Referenced by Gui::View3DInventorPy::saveImage(), and Gui::View3DInventorViewer::savePicture().
operator=()
SoFCOffscreenRenderer& Gui::SoFCOffscreenRenderer::operator= (const SoFCOffscreenRenderer &) delete
writeToImage()
void SoFCOffscreenRenderer::writeToImage (QImage & img) const
Writes the rendered image buffer directly into a QImage object instead of an image file.
Definition at line 88 of file SoFCOffscreenRenderer.cpp.
References Gui::BitmapFactory(), and Gui::BitmapFactoryInst::convert().
Referenced by Gui::View3DInventorViewer::savePicture().
writeToImageFile()
void SoFCOffscreenRenderer::writeToImageFile (const char * filename, const char * comment, const SbMatrix & mat, const QImage & img)
Saves the buffer to filename, in the filetype specified by filetypeextensions.
Note that you must still specify the full filename for the first argument, i.e. the second argument will not automatically be attached to the filename – it is only used to decide the filetype.
If comment is set to '$MIBA' information regarding the MIBA standard is embedded to the picture, otherwise the comment is embedded as is. The appropriate file format must support embedding meta information which is provided by JPEG or PNG.
This does basically the same as writeToFile() unless that all QImage file formats are supported if not directly supported by Coin3D.
Definition at line 99 of file SoFCOffscreenRenderer.cpp.
References AttacherGui::comment, createMIBA(), SCL.SimpleDataTypes::e, SCL.SimpleDataTypes::f, DrawingExample::file, App::Application::getExecutableName(), Path.Post.scripts.refactored_centroid_post::str, DraftVecUtils::toString(), and writeJPEGComment().
Referenced by Gui::View3DInventorPy::saveImage().
The documentation for this class was generated from the following files:
SoFCOffscreenRenderer.h
SoFCOffscreenRenderer.cpp