FreeCAD: AppCloudGui.cpp File Reference
AppCloudGui.cpp File Reference
#include "PreCompiled.h"
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/PyObjectBase.h>
#include <Gui/Application.h>
#include "Workbench.h"
Classes
class CloudGui::Module
Namespaces
CloudGui
Functions
void CreateCloudCommands (void)
PyObject * CloudGui::initModule ()
PyMOD_INIT_FUNC (CloudGui)
Function Documentation
CreateCloudCommands()
void CreateCloudCommands (void)
Definition at line 55 of file Mod/Cloud/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (CloudGui)
Definition at line 63 of file AppCloudGui.cpp.
References Base::Console(), CreateCloudCommands(), Base::BaseClass::init(), CloudGui::initModule(), Gui::Application::Instance, Base::ConsoleSingleton::Log(), mod, and PyMOD_Return.