FreeCAD: importDWG Namespace Reference
importDWG Namespace Reference
DRAFT
DWG file importer & exporter.
Functions
def translate (context, txt)
def open (filename)
def insert (filename, docname)
def export (objectslist, filename)
def get_libredwg_converter (typ)
def get_oda_converter ()
def get_qcad_converter ()
def convertToDxf (dwgfilename)
def convertToDwg (dxffilename, dwgfilename)
Detailed Description
DWG file importer & exporter.
Function Documentation
convertToDwg()
def importDWG.convertToDwg (dxffilename, dwgfilename)
Convert a DXF file to a DWG file.
If the converter is found it is used, otherwise the conversion fails.
Parameters
----------
dxffilename : str
    The input DXF file
dwgfilename : str
    The output DWG file
Returns
-------
str
    The same `dwgfilename` file path.
Definition at line 343 of file importDWG.py.
References get_libredwg_converter(), get_oda_converter(), get_qcad_converter(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by export().
convertToDxf()
def importDWG.convertToDxf (dwgfilename)
Convert a DWG file to a DXF file.
If the converter is found it is used, otherwise the conversion fails.
Parameters
----------
dwgfilename : str
    The input filename.
Returns
-------
str
    The new file produced.
Definition at line 256 of file importDWG.py.
References get_libredwg_converter(), get_oda_converter(), get_qcad_converter(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by insert(), and open().
export()
def importDWG.export (objectslist, filename)
Export the DWG file with a given list of objects.
The objects are exported with importDXF.export().
Then the result is converted to DWG.
Parameters
----------
exportList : list
    List of document objects to export.
filename : str
    Path to the new file.
Returns
-------
str
    The same `filename` input.
Definition at line 105 of file importDWG.py.
References convertToDwg(), and importDXF.export().
get_libredwg_converter()
def importDWG.get_libredwg_converter (typ)
Find the LibreDWG converter.
It searches the FreeCAD parameters database, then searches the OS search path.
There are no standard installation paths.
`typ` is required because LibreDWG uses two converters and we store only one.
Parameters
----------
typ : str
    "dwg2dxf" or "dxf2dwg".
Returns
-------
str
    The full path of the converter.
Definition at line 134 of file importDWG.py.
Referenced by convertToDwg(), and convertToDxf().
get_oda_converter()
def importDWG.get_oda_converter ()
Find the ODA converter.
It searches the FreeCAD parameters database, then searches for common paths.
Parameters
----------
None
Returns
-------
str
    The full path of the converter.
Definition at line 176 of file importDWG.py.
Referenced by convertToDwg(), and convertToDxf().
get_qcad_converter()
def importDWG.get_qcad_converter ()
Find the QCAD converter.
It searches the FreeCAD parameters database, then searches for common paths.
Parameters
----------
None
Returns
-------
str
    The full path of the converter.
Definition at line 217 of file importDWG.py.
Referenced by convertToDwg(), and convertToDxf().
insert()
def importDWG.insert (filename, docname)
Imports a file using importDXF.insert().
If no document exist, it is created.
Parameters
----------
filename : str
    The path to the filename to be opened.
docname : str
    The name of the active App::Document if one exists, or
    of the new one created.
Returns
-------
App::Document
    The active FreeCAD document, or the document created if none exists,
    with the parsed information.
Definition at line 77 of file importDWG.py.
References convertToDxf(), and importDXF.insert().
open()
def importDWG.open (filename)
Open filename and parse using importDXF.open().
Parameters
----------
filename : str
    The path to the filename to be opened.
Returns
-------
App::Document
    The new FreeCAD document object created, with the parsed information.
Definition at line 56 of file importDWG.py.
References convertToDxf(), and importDXF.open().
translate()
def importDWG.translate (context, txt)
Definition at line 50 of file importDWG.py.