FreeCAD: src.Mod.AddonManager.AddonManagerTest.app.test_metadata.TestVersion Class Reference
src.Mod.AddonManager.AddonManagerTest.app.test_metadata.TestVersion Class Reference
Public Member Functions
None setUp (self)
None tearDown (self)
def test_init_from_string_manual (self)
def test_init_from_list_good (self)
def test_parse_string_to_tuple_normal (self)
def test_parse_string_to_tuple_invalid (self)
def test_parse_final_entry_normal (self)
def test_parse_final_entry_invalid (self)
def test_operators_internal (self)
Static Public Member Functions
def given_comparison_cases ()
Public Attributes
packaging_version
Detailed Description
Definition at line 34 of file test_metadata.py.
Member Function Documentation
given_comparison_cases()
def src.Mod.AddonManager.AddonManagerTest.app.test_metadata.TestVersion.given_comparison_cases () static
Definition at line 144 of file test_metadata.py.
Referenced by src.Mod.AddonManager.AddonManagerTest.app.test_metadata.TestVersion.test_operators_internal().
setUp()
None src.Mod.AddonManager.AddonManagerTest.app.test_metadata.TestVersion.setUp (self)
Definition at line 35 of file test_metadata.py.
tearDown()
None src.Mod.AddonManager.AddonManagerTest.app.test_metadata.TestVersion.tearDown (self)
Definition at line 43 of file test_metadata.py.
References src.Mod.AddonManager.AddonManagerTest.app.test_metadata.TestVersion.packaging_version.
Referenced by CAMTests.TestPathHelix.TestPathHelix.test03(), CAMTests.TestPathHelix.TestPathHelix.test04(), and CAMTests.TestPathHelix.TestPathHelix.testRecomputeHelixFromV021().
test_init_from_list_good()
def src.Mod.AddonManager.AddonManagerTest.app.test_metadata.TestVersion.test_init_from_list_good (self)
Initialization from a list works for good input
Definition at line 55 of file test_metadata.py.
test_init_from_string_manual()
def src.Mod.AddonManager.AddonManagerTest.app.test_metadata.TestVersion.test_init_from_string_manual (self)
Definition at line 47 of file test_metadata.py.
test_operators_internal()
def src.Mod.AddonManager.AddonManagerTest.app.test_metadata.TestVersion.test_operators_internal (self)
Test internal (non-package) comparison operators
Definition at line 127 of file test_metadata.py.
References src.Mod.AddonManager.AddonManagerTest.app.test_metadata.TestVersion.given_comparison_cases().
test_parse_final_entry_invalid()
def src.Mod.AddonManager.AddonManagerTest.app.test_metadata.TestVersion.test_parse_final_entry_invalid (self)
Invalid input raises an exception
Definition at line 117 of file test_metadata.py.
test_parse_final_entry_normal()
def src.Mod.AddonManager.AddonManagerTest.app.test_metadata.TestVersion.test_parse_final_entry_normal (self)
Parsing of the final entry works for normal cases
Definition at line 100 of file test_metadata.py.
test_parse_string_to_tuple_invalid()
def src.Mod.AddonManager.AddonManagerTest.app.test_metadata.TestVersion.test_parse_string_to_tuple_invalid (self)
Parsing of invalid version string raises an exception
Definition at line 89 of file test_metadata.py.
test_parse_string_to_tuple_normal()
def src.Mod.AddonManager.AddonManagerTest.app.test_metadata.TestVersion.test_parse_string_to_tuple_normal (self)
Parsing of complete version string works for normal cases
Definition at line 70 of file test_metadata.py.
Member Data Documentation
packaging_version
src.Mod.AddonManager.AddonManagerTest.app.test_metadata.TestVersion.packaging_version
Definition at line 38 of file test_metadata.py.
Referenced by src.Mod.AddonManager.AddonManagerTest.app.test_metadata.TestVersion.tearDown().
The documentation for this class was generated from the following file:
test_metadata.py