FreeCAD: Gui::DAG::RectItem Class Reference
Gui::DAG::RectItem Class Reference
#include <DAGRectItem.h>
Public Member Functions
RectItem (QGraphicsItem *parent=nullptr)
void setBackgroundBrush (const QBrush &brushIn)
void setEditingBrush (const QBrush &brushIn)
void preHighlightOn ()
void preHighlightOff ()
void selectionOn ()
void selectionOff ()
bool isSelected ()
bool isPreSelected ()
void editingStart ()
void editingFinished ()
bool isEditing ()
Protected Member Functions
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
Detailed Description
Definition at line 77 of file DAGRectItem.h.
Constructor & Destructor Documentation
RectItem()
RectItem::RectItem (QGraphicsItem * parent = nullptr) explicit
Definition at line 37 of file DAGRectItem.cpp.
Member Function Documentation
editingFinished()
void Gui::DAG::RectItem::editingFinished () inline
Definition at line 110 of file DAGRectItem.h.
editingStart()
void Gui::DAG::RectItem::editingStart () inline
Definition at line 109 of file DAGRectItem.h.
isEditing()
bool Gui::DAG::RectItem::isEditing () inline
Definition at line 111 of file DAGRectItem.h.
Referenced by Gui::DAG::Model::contextMenuEvent().
isPreSelected()
bool Gui::DAG::RectItem::isPreSelected () inline
Definition at line 108 of file DAGRectItem.h.
isSelected()
bool Gui::DAG::RectItem::isSelected () inline
Definition at line 107 of file DAGRectItem.h.
Referenced by Gui::DAG::Model::contextMenuEvent().
paint()
void RectItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override protected
Definition at line 44 of file DAGRectItem.cpp.
preHighlightOff()
void Gui::DAG::RectItem::preHighlightOff () inline
Definition at line 104 of file DAGRectItem.h.
Referenced by Gui::DAG::Model::mouseMoveEvent().
preHighlightOn()
void Gui::DAG::RectItem::preHighlightOn () inline
Definition at line 103 of file DAGRectItem.h.
Referenced by Gui::DAG::Model::mouseMoveEvent().
selectionOff()
void Gui::DAG::RectItem::selectionOff () inline
Definition at line 106 of file DAGRectItem.h.
Referenced by Gui::DAG::Model::selectionChanged().
selectionOn()
void Gui::DAG::RectItem::selectionOn () inline
Definition at line 105 of file DAGRectItem.h.
Referenced by Gui::DAG::Model::selectionChanged().
setBackgroundBrush()
void Gui::DAG::RectItem::setBackgroundBrush (const QBrush & brushIn) inline
Definition at line 101 of file DAGRectItem.h.
setEditingBrush()
void Gui::DAG::RectItem::setEditingBrush (const QBrush & brushIn) inline
Definition at line 102 of file DAGRectItem.h.
The documentation for this class was generated from the following files:
DAGRectItem.h
DAGRectItem.cpp