FreeCAD: NaviCubeImplementation Class Reference
NaviCubeImplementation Class Reference
Public Member Functions
NaviCubeImplementation (Gui::View3DInventorViewer *)
~NaviCubeImplementation ()
void drawNaviCube ()
void createContextMenu (const std::vector< std::string > &cmd)
void createCubeFaceTextures ()
void moveToCorner (NaviCube::Corner c)
void setLabels (const std::vector< std::string > &labels)
bool processSoEvent (const SoEvent *ev)
void setSize (int size)
Public Attributes
QColor m_BaseColor
QColor m_EmphaseColor
QColor m_HiliteColor
bool m_ShowCS = true
PickId m_HiliteId = PickId::None
double m_BorderWidth = 1.1
bool m_RotateToNearest = true
int m_NaviStepByTurn = 8
float m_FontZoom = 0.3F
float m_Chamfer = 0.12F
std::string m_TextFont
int m_FontWeight = 0
int m_FontStretch = 0
float m_InactiveOpacity = 0.5
SbVec2s m_PosOffset = SbVec2s(0,0)
bool m_Prepared = false
bool m_Draggable = false
SbVec2s m_ViewSize = SbVec2s(0,0)
Static Public Attributes
static int m_CubeWidgetSize = 132
static vector< string > m_commands
Detailed Description
Definition at line 69 of file NaviCube.cpp.
Constructor & Destructor Documentation
NaviCubeImplementation()
NaviCubeImplementation::NaviCubeImplementation (Gui::View3DInventorViewer * viewer) explicit
Definition at line 344 of file NaviCube.cpp.
~NaviCubeImplementation()
NaviCubeImplementation::~NaviCubeImplementation ()
Definition at line 353 of file NaviCube.cpp.
Member Function Documentation
createContextMenu()
void NaviCubeImplementation::createContextMenu (const std::vector< std::string > & cmd)
Definition at line 714 of file NaviCube.cpp.
References Gui::Command::addTo(), Gui::CommandManager::getCommandByName(), SplineSurface::i, and Instance.
createCubeFaceTextures()
void NaviCubeImplementation::createCubeFaceTextures ()
Definition at line 417 of file NaviCube.cpp.
References convertWeights, imageVerticalBalance(), m_FontStretch, m_FontWeight, m_FontZoom, m_TextFont, KDL::max(), KDL::min(), Base::pow(), draftfunctions.scale::scale(), and InitGui::t.
drawNaviCube()
void NaviCubeImplementation::drawNaviCube ()
Definition at line 706 of file NaviCube.cpp.
References SCL.SimpleDataTypes::f, m_CubeWidgetSize, and m_InactiveOpacity.
moveToCorner()
void NaviCubeImplementation::moveToCorner (NaviCube::Corner c)
Definition at line 363 of file NaviCube.cpp.
References NaviCube::BottomLeftCorner, NaviCube::BottomRightCorner, SCL.SimpleDataTypes::c, SCL.SimpleDataTypes::f, NaviCube::TopLeftCorner, and NaviCube::TopRightCorner.
processSoEvent()
bool NaviCubeImplementation::processSoEvent (const SoEvent * ev)
Definition at line 1147 of file NaviCube.cpp.
References MovieTool::x, and MovieTool::y.
setLabels()
void NaviCubeImplementation::setLabels (const std::vector< std::string > & labels)
Definition at line 333 of file NaviCube.cpp.
References TechDraw::Bottom, TechDraw::Front, App::ExpressionParser::labels, TechDraw::Left, TechDraw::Rear, TechDraw::Right, and TechDraw::Top.
setSize()
void NaviCubeImplementation::setSize (int size)
Definition at line 638 of file NaviCube.cpp.
References m_CubeWidgetSize, m_Prepared, and m_ViewSize.
Member Data Documentation
m_BaseColor
QColor NaviCubeImplementation::m_BaseColor
Definition at line 166 of file NaviCube.cpp.
m_BorderWidth
double NaviCubeImplementation::m_BorderWidth = 1.1
Definition at line 171 of file NaviCube.cpp.
m_Chamfer
float NaviCubeImplementation::m_Chamfer = 0.12F
Definition at line 175 of file NaviCube.cpp.
m_commands
vector< string > NaviCubeImplementation::m_commands static
Definition at line 183 of file NaviCube.cpp.
Referenced by NaviCube::setNaviCubeCommands().
m_CubeWidgetSize
int NaviCubeImplementation::m_CubeWidgetSize = 132 static
Definition at line 165 of file NaviCube.cpp.
Referenced by drawNaviCube(), NaviCube::getNaviCubeSize(), and setSize().
m_Draggable
bool NaviCubeImplementation::m_Draggable = false
Definition at line 184 of file NaviCube.cpp.
m_EmphaseColor
QColor NaviCubeImplementation::m_EmphaseColor
Definition at line 167 of file NaviCube.cpp.
m_FontStretch
int NaviCubeImplementation::m_FontStretch = 0
Definition at line 178 of file NaviCube.cpp.
Referenced by createCubeFaceTextures().
m_FontWeight
int NaviCubeImplementation::m_FontWeight = 0
Definition at line 177 of file NaviCube.cpp.
Referenced by createCubeFaceTextures().
m_FontZoom
float NaviCubeImplementation::m_FontZoom = 0.3F
Definition at line 174 of file NaviCube.cpp.
Referenced by createCubeFaceTextures().
m_HiliteColor
QColor NaviCubeImplementation::m_HiliteColor
Definition at line 168 of file NaviCube.cpp.
m_HiliteId
PickId NaviCubeImplementation::m_HiliteId = PickId::None
Definition at line 170 of file NaviCube.cpp.
m_InactiveOpacity
float NaviCubeImplementation::m_InactiveOpacity = 0.5
Definition at line 179 of file NaviCube.cpp.
Referenced by drawNaviCube().
m_NaviStepByTurn
int NaviCubeImplementation::m_NaviStepByTurn = 8
Definition at line 173 of file NaviCube.cpp.
m_PosOffset
SbVec2s NaviCubeImplementation::m_PosOffset = SbVec2s(0,0)
Definition at line 180 of file NaviCube.cpp.
m_Prepared
bool NaviCubeImplementation::m_Prepared = false
Definition at line 182 of file NaviCube.cpp.
Referenced by setSize().
m_RotateToNearest
bool NaviCubeImplementation::m_RotateToNearest = true
Definition at line 172 of file NaviCube.cpp.
m_ShowCS
bool NaviCubeImplementation::m_ShowCS = true
Definition at line 169 of file NaviCube.cpp.
m_TextFont
std::string NaviCubeImplementation::m_TextFont
Definition at line 176 of file NaviCube.cpp.
Referenced by createCubeFaceTextures().
m_ViewSize
SbVec2s NaviCubeImplementation::m_ViewSize = SbVec2s(0,0)
Definition at line 185 of file NaviCube.cpp.
Referenced by setSize().
The documentation for this class was generated from the following file:
NaviCube.cpp