FreeCAD: Gui::ProgressBar Class Reference
Gui::ProgressBar Class Reference
#include <ProgressBar.h>
Public Slots
void setMinimumDuration (int ms)
Public Member Functions
ProgressBar (SequencerBar *s, QWidget *parent=nullptr)
~ProgressBar () override
bool eventFilter (QObject *o, QEvent *e) override
int minimumDuration () const
bool canAbort () const
Protected Slots
void delayedShow ()
void aboutToShow ()
void aboutToHide ()
Protected Member Functions
void showEvent (QShowEvent *) override
void hideEvent (QHideEvent *) override
for internal use only
class SequencerBar
Detailed Description
Definition at line 162 of file ProgressBar.h.
Constructor & Destructor Documentation
ProgressBar()
ProgressBar::ProgressBar (SequencerBar * s, QWidget * parent = nullptr)
Construction
Definition at line 385 of file ProgressBar.cpp.
References draftgeoutils.intersections::connect(), delayedShow(), Gui::ProgressBarPrivate::delayShowTimer, ArchFence::hide(), Gui::ProgressBarPrivate::minimumDuration, and Gui::ProgressBarPrivate::observeEventFilter.
~ProgressBar()
ProgressBar::~ProgressBar () override
Destruction
Definition at line 406 of file ProgressBar.cpp.
References delayedShow(), and Gui::ProgressBarPrivate::delayShowTimer.
Member Function Documentation
aboutToHide
void ProgressBar::aboutToHide () protected slot
Definition at line 473 of file ProgressBar.cpp.
References ArchFence::hide().
Referenced by Gui::SequencerBar::resetData().
aboutToShow
void ProgressBar::aboutToShow () protected slot
Definition at line 456 of file ProgressBar.cpp.
References Gui::ProgressBarPrivate::delayShowTimer, and Gui::ProgressBarPrivate::minimumDuration.
Referenced by Gui::SequencerBar::startStep().
canAbort()
bool ProgressBar::canAbort () const
Definition at line 482 of file ProgressBar.cpp.
References Gui::getMainWindow().
Referenced by Gui::SequencerBar::checkAbort(), and Gui::SequencerBar::nextStep().
delayedShow
void ProgressBar::delayedShow () protected slot
Definition at line 466 of file ProgressBar.cpp.
References Base::SequencerBase::isRunning(), bimcommands.BimViews::show(), and Base::SequencerBase::wasCanceled().
Referenced by ProgressBar(), and ~ProgressBar().
eventFilter()
bool ProgressBar::eventFilter (QObject * o, QEvent * e) override
Handles all incoming events while the progress bar is running. All key and mouse events are ignored to block user input.
Definition at line 549 of file ProgressBar.cpp.
References SCL.SimpleDataTypes::e, Gui::getMainWindow(), Gui::ProgressBarPrivate::isModalDialog(), Base::SequencerBase::isRunning(), src.Mod.Test.testPathArray::o, Gui::ProgressBarPrivate::observeEventFilter, Gui::SequencerBar::resetData(), and Base::SequencerBase::tryToCancel().
hideEvent()
void ProgressBar::hideEvent (QHideEvent * e) override protected
Definition at line 497 of file ProgressBar.cpp.
References Gui::ProgressBarPrivate::delayShowTimer, and SCL.SimpleDataTypes::e.
minimumDuration()
int ProgressBar::minimumDuration () const
Returns the time in milliseconds that must pass before the progress bar appears.
Definition at line 413 of file ProgressBar.cpp.
References Gui::ProgressBarPrivate::minimumDuration.
setMinimumDuration
void ProgressBar::setMinimumDuration (int ms) slot
Sets the time that must pass before the progress bar appears to ms.
Definition at line 445 of file ProgressBar.cpp.
References Gui::ProgressBarPrivate::delayShowTimer, and Gui::ProgressBarPrivate::minimumDuration.
showEvent()
void ProgressBar::showEvent (QShowEvent * e) override protected
Definition at line 491 of file ProgressBar.cpp.
References Gui::ProgressBarPrivate::delayShowTimer, and SCL.SimpleDataTypes::e.
Friends And Related Function Documentation
SequencerBar
friend class SequencerBar friend
Definition at line 226 of file ProgressBar.h.
The documentation for this class was generated from the following files:
ProgressBar.h
ProgressBar.cpp