FreeCAD: ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf Namespace Reference
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf Namespace Reference
Classes
class absorbed_dose_measure
class absorbed_dose_measure_with_unit
class absorbed_dose_unit
class abstract_variable
class acceleration_measure
class acceleration_measure_with_unit
class acceleration_unit
class action
class action_assignment
class action_directive
class action_method
class action_method_assignment
class action_method_relationship
class action_method_role
class action_property
class action_property_representation
class action_relationship
class action_request_assignment
class action_request_solution
class action_request_status
class action_status
class address
class advanced_brep_shape_representation
class advanced_face
class ahead_or_behind
class alternate_product_relationship
class amount_of_substance_measure
class amount_of_substance_measure_with_unit
class amount_of_substance_unit
class angle_direction_reference
class angle_relator
class angular_dimension
class angular_location
class angular_size
class angularity_tolerance
class annotation_curve_occurrence
class annotation_fill_area
class annotation_fill_area_occurrence
class annotation_occurrence
class annotation_occurrence_associativity
class annotation_occurrence_relationship
class annotation_plane
class annotation_subfigure_occurrence
class annotation_symbol
class annotation_symbol_occurrence
class annotation_text
class annotation_text_character
class annotation_text_occurrence
class apex
class application_context
class application_context_element
class application_protocol_definition
class applied_action_assignment
class applied_action_method_assignment
class applied_action_request_assignment
class applied_approval_assignment
class applied_attribute_classification_assignment
class applied_certification_assignment
class applied_classification_assignment
class applied_contract_assignment
class applied_date_and_time_assignment
class applied_date_assignment
class applied_document_reference
class applied_document_usage_constraint_assignment
class applied_effectivity_assignment
class applied_event_occurrence_assignment
class applied_external_identification_assignment
class applied_group_assignment
class applied_identification_assignment
class applied_name_assignment
class applied_organization_assignment
class applied_organizational_project_assignment
class applied_person_and_organization_assignment
class applied_presented_item
class applied_security_classification_assignment
class applied_time_interval_assignment
class applied_usage_right
class approval
class approval_assignment
class approval_date_time
class approval_person_organization
class approval_relationship
class approval_role
class approval_status
class area_in_set
class area_measure
class area_measure_with_unit
class area_unit
class assembly_component_usage
class assembly_component_usage_substitute
class assigned_requirement
class atomic_formula
class attribute_assertion
class attribute_classification_assignment
class attribute_language_assignment
class attribute_value_assignment
class attribute_value_role
class auxiliary_geometric_representation_item
class axis1_placement
class axis2_placement_2d
class axis2_placement_3d
class b_spline_curve
class b_spline_curve_form
class b_spline_curve_with_knots
class b_spline_surface
class b_spline_surface_form
class b_spline_surface_with_knots
class back_chaining_rule
class back_chaining_rule_body
class background_colour
class beveled_sheet_representation
class bezier_curve
class bezier_surface
class binary_generic_expression
class binary_numeric_expression
class binary_representation_item
class blend_radius_variation_type
class block
class boolean_expression
class boolean_literal
class boolean_operator
class boolean_representation_item
class boolean_result
class boundary_curve
class bounded_curve
class bounded_pcurve
class bounded_surface
class bounded_surface_curve
class box_domain
class box_height
class box_rotate_angle
class box_slant_angle
class box_width
class boxed_half_space
class breakdown_context
class breakdown_element_group_assignment
class breakdown_element_realization
class breakdown_element_usage
class breakdown_of
class brep_with_voids
class bytes_representation_item
class calendar_date
class camera_image
class camera_image_3d_with_scale
class camera_model
class camera_model_d3
class camera_model_d3_multi_clipping
class camera_model_d3_multi_clipping_intersection
class camera_model_d3_multi_clipping_union
class camera_model_d3_with_hlhsr
class camera_model_with_light_sources
class camera_usage
class capacitance_measure
class capacitance_measure_with_unit
class capacitance_unit
class cartesian_point
class cartesian_transformation_operator
class cartesian_transformation_operator_2d
class cartesian_transformation_operator_3d
class cc_design_approval
class cc_design_certification
class cc_design_contract
class cc_design_date_and_time_assignment
class cc_design_person_and_organization_assignment
class cc_design_security_classification
class cc_design_specification_reference
class celsius_temperature_measure
class celsius_temperature_measure_with_unit
class central_or_parallel
class centre_of_symmetry
class certification
class certification_assignment
class certification_type
class change
class change_request
class character_glyph_font_usage
class character_glyph_style_outline
class character_glyph_style_stroke
class character_glyph_symbol
class character_glyph_symbol_outline
class character_glyph_symbol_stroke
class characteristic_data_column_header
class characteristic_data_column_header_link
class characteristic_data_table_header
class characteristic_data_table_header_decomposition
class characteristic_type
class characterized_class
class characterized_object
class circle
class circular_runout_tolerance
class class_
class class_by_extension
class class_by_intension
class class_system
class class_usage_effectivity_context_assignment
class classification_assignment
class classification_role
class closed_shell
class coaxiality_tolerance
class colour
class colour_rgb
class colour_specification
class common_datum
class comparison_expression
class complex_clause
class complex_conjunctive_clause
class complex_disjunctive_clause
class complex_shelled_solid
class composite_assembly_definition
class composite_assembly_sequence_definition
class composite_assembly_table
class composite_curve
class composite_curve_on_surface
class composite_curve_segment
class composite_material_designation
class composite_shape_aspect
class composite_sheet_representation
class composite_text
class composite_text_with_associated_curves
class composite_text_with_blanking_box
class composite_text_with_delineation
class composite_text_with_extent
class compound_representation_item
class compound_shape_representation
class concentricity_tolerance
class concept_feature_operator
class concept_feature_relationship
class concept_feature_relationship_with_condition
class conditional_concept_feature
class conductance_measure
class conductance_measure_with_unit
class conductance_unit
class configurable_item
class configuration_design
class configuration_effectivity
class configuration_item
class configuration_item_hierarchical_relationship
class configuration_item_relationship
class configuration_item_revision_sequence
class configured_effectivity_assignment
class configured_effectivity_context_assignment
class conic
class conical_stepped_hole_transition
class conical_surface
class connected_edge_set
class connected_face_set
class connected_face_sub_set
class constructive_geometry_representation
class constructive_geometry_representation_relationship
class contact_ratio_representation
class context_dependent_invisibility
class context_dependent_measure
class context_dependent_over_riding_styled_item
class context_dependent_shape_representation
class context_dependent_unit
class contract
class contract_assignment
class contract_relationship
class contract_type
class conversion_based_unit
class coordinated_universal_time_offset
class count_measure
class csg_shape_representation
class csg_solid
class currency
class currency_measure_with_unit
class curve
class curve_bounded_surface
class curve_dimension
class curve_replica
class curve_style
class curve_style_font
class curve_style_font_and_scaling
class curve_style_font_pattern
class curve_style_rendering
class curve_swept_solid_shape_representation
class cylindrical_surface
class cylindricity_tolerance
class data_environment
class date
class date_and_time
class date_and_time_assignment
class date_assignment
class date_representation_item
class date_role
class date_time_representation_item
class date_time_role
class dated_effectivity
class datum
class datum_feature
class datum_feature_callout
class datum_reference
class datum_target
class datum_target_callout
class day_in_month_number
class day_in_week_number
class day_in_year_number
class default_tolerance_table
class default_tolerance_table_cell
class defined_symbol
class definitional_representation
class definitional_representation_relationship
class definitional_representation_relationship_with_same_context
class degenerate_pcurve
class degenerate_toroidal_surface
class derived_shape_aspect
class derived_unit
class derived_unit_element
class description_attribute
class descriptive_measure
class descriptive_representation_item
class design_context
class design_make_from_relationship
class diameter_dimension
class dielectric_constant_measure_with_unit
class dimension_callout
class dimension_callout_component_relationship
class dimension_callout_relationship
class dimension_count
class dimension_curve
class dimension_curve_directed_callout
class dimension_curve_terminator
class dimension_curve_terminator_to_projection_curve_associativity
class dimension_extent_usage
class dimension_pair
class dimension_related_tolerance_zone_element
class dimension_text_associativity
class dimensional_characteristic_representation
class dimensional_exponents
class dimensional_location
class dimensional_location_with_path
class dimensional_size
class dimensional_size_with_path
class directed_action
class directed_dimensional_location
class direction
class document
class document_file
class document_identifier
class document_identifier_assignment
class document_product_association
class document_product_equivalence
class document_reference
class document_relationship
class document_representation_type
class document_type
class document_usage_constraint
class document_usage_constraint_assignment
class document_usage_role
class dose_equivalent_measure
class dose_equivalent_measure_with_unit
class dose_equivalent_unit
class double_offset_shelled_solid
class draped_defined_transformation
class draughting_annotation_occurrence
class draughting_callout
class draughting_callout_relationship
class draughting_elements
class draughting_model
class draughting_model_item_association
class draughting_pre_defined_colour
class draughting_pre_defined_curve_font
class draughting_pre_defined_text_font
class draughting_subfigure_representation
class draughting_symbol_representation
class draughting_text_literal_with_delineation
class draughting_title
class drawing_definition
class drawing_revision
class drawing_revision_sequence
class drawing_sheet_revision
class drawing_sheet_revision_sequence
class drawing_sheet_revision_usage
class edge
class edge_based_wireframe_model
class edge_based_wireframe_shape_representation
class edge_blended_solid
class edge_curve
class edge_loop
class effectivity
class effectivity_assignment
class effectivity_context_assignment
class effectivity_context_role
class effectivity_relationship
class electric_charge_measure
class electric_charge_measure_with_unit
class electric_charge_unit
class electric_current_measure
class electric_current_measure_with_unit
class electric_current_unit
class electric_potential_measure
class electric_potential_measure_with_unit
class electric_potential_unit
class elementary_brep_shape_representation
class elementary_surface
class ellipse
class energy_measure
class energy_measure_with_unit
class energy_unit
class entity_assertion
class enum_reference_prefix
class environment
class evaluated_characteristic
class evaluated_degenerate_pcurve
class evaluation_product_definition
class event_occurrence
class event_occurrence_assignment
class event_occurrence_relationship
class event_occurrence_role
class exclusive_product_concept_feature_category
class executed_action
class expanded_uncertainty
class explicit_procedural_geometric_representation_item_relationship
class explicit_procedural_representation_item_relationship
class explicit_procedural_representation_relationship
class explicit_procedural_shape_representation_relationship
class expression
class expression_conversion_based_unit
class extension
class extent
class external_class_library
class external_identification_assignment
class external_source
class external_source_relationship
class externally_defined_class
class externally_defined_colour
class externally_defined_context_dependent_unit
class externally_defined_conversion_based_unit
class externally_defined_currency
class externally_defined_curve_font
class externally_defined_dimension_definition
class externally_defined_general_property
class externally_defined_hatch_style
class externally_defined_item
class externally_defined_item_relationship
class externally_defined_marker
class externally_defined_picture_representation_item
class externally_defined_representation_item
class externally_defined_string
class externally_defined_symbol
class externally_defined_terminator_symbol
class externally_defined_text_font
class externally_defined_tile
class externally_defined_tile_style
class extruded_area_solid
class extruded_face_solid
class extruded_face_solid_with_draft_angle
class extruded_face_solid_with_multiple_draft_angles
class extruded_face_solid_with_trim_conditions
class face
class face_based_surface_model
class face_bound
class face_outer_bound
class face_surface
class faceted_brep
class faceted_brep_shape_representation
class fact_type
class fill_area_style
class fill_area_style_colour
class fill_area_style_hatching
class fill_area_style_tile_coloured_region
class fill_area_style_tile_curve_with_style
class fill_area_style_tile_symbol_with_style
class fill_area_style_tiles
class flat_pattern_ply_representation_relationship
class flatness_tolerance
class force_measure
class force_measure_with_unit
class force_unit
class forward_chaining_rule
class forward_chaining_rule_premise
class founded_item
ENTITY founded_item #.
class frequency_measure
class frequency_measure_with_unit
class frequency_unit
class func
class functional_breakdown_context
class functional_element_usage
class functionally_defined_transformation
class general_material_property
class general_property
class general_property_association
class general_property_relationship
class generic_character_glyph_symbol
class generic_expression
class generic_literal
class generic_variable
class geometric_alignment
class geometric_curve_set
class geometric_intersection
class geometric_item_specific_usage
class geometric_model_element_relationship
class geometric_representation_context
class geometric_representation_item
class geometric_set
class geometric_tolerance
class geometric_tolerance_relationship
class geometric_tolerance_with_datum_reference
class geometric_tolerance_with_defined_unit
class geometrical_tolerance_callout
class geometrically_bounded_2d_wireframe_representation
class geometrically_bounded_surface_shape_representation
class geometrically_bounded_wireframe_shape_representation
class global_assignment
class global_uncertainty_assigned_context
class global_unit_assigned_context
class ground_fact
class group
class group_assignment
class group_relationship
class half_space_solid
class hardness_representation
class hidden_element_over_riding_styled_item
class hour_in_day
class hyperbola
class id_attribute
class identification_assignment
class identification_role
class identifier
class illuminance_measure
class illuminance_measure_with_unit
class illuminance_unit
class included_text_block
class inclusion_product_concept_feature
class indirectly_selected_elements
class indirectly_selected_shape_elements
class inductance_measure
class inductance_measure_with_unit
class inductance_unit
class information_right
class information_usage_right
class instance_usage_context_assignment
class instanced_feature
class int_literal
class integer_representation_item
class intersection_curve
class interval_expression
class invisibility
class iso4217_currency
class item_defined_transformation
class item_identified_representation_usage
class knot_type
class known_source
class label
class laid_defined_transformation
class laminate_table
class language
class leader_curve
class leader_directed_callout
class leader_directed_dimension
class leader_terminator
class length_measure
class length_measure_with_unit
class length_unit
class light_source
class light_source_ambient
class light_source_directional
class light_source_positional
class light_source_spot
class limit_condition
class limits_and_fits
class line
class line_profile_tolerance
class linear_dimension
class literal_conjunction
class literal_disjunction
class literal_number
class local_time
class logical_literal
class logical_representation_item
class loop
class loss_tangent_measure_with_unit
class lot_effectivity
class luminous_flux_measure
class luminous_flux_measure_with_unit
class luminous_flux_unit
class luminous_intensity_measure
class luminous_intensity_measure_with_unit
class luminous_intensity_unit
class magnetic_flux_density_measure
class magnetic_flux_density_measure_with_unit
class magnetic_flux_density_unit
class magnetic_flux_measure
class magnetic_flux_measure_with_unit
class magnetic_flux_unit
class make_from_usage_option
class manifold_solid_brep
class manifold_subsurface_shape_representation
class manifold_surface_shape_representation
class mapped_item
class marker_type
class mass_measure
class mass_measure_with_unit
class mass_unit
class material_designation
class material_designation_characterization
class material_property
class material_property_representation
class measure_qualification
class measure_representation_item
class measure_with_unit
class mechanical_context
class mechanical_design_and_draughting_relationship
class mechanical_design_geometric_presentation_area
class mechanical_design_geometric_presentation_representation
class mechanical_design_presentation_representation_with_draughting
class mechanical_design_shaded_presentation_area
class mechanical_design_shaded_presentation_representation
class message
class min_and_major_ply_orientation_basis
class minute_in_hour
class modified_geometric_tolerance
class modified_solid
class modified_solid_with_placed_configuration
class moments_of_inertia_representation
class month_in_year_number
class multi_language_attribute_assignment
class multiple_arity_boolean_expression
class multiple_arity_generic_expression
class multiple_arity_numeric_expression
class name_assignment
class name_attribute
class named_unit
class next_assembly_usage_occurrence
class non_manifold_surface_shape_representation
class non_negative_length_measure
class nonnegative_integer
class null_representation_item
class null_style
class numeric_expression
class numeric_measure
class object_role
class offset_curve_2d
class offset_curve_3d
class offset_surface
class one_direction_repeat_factor
class open_shell
class ordinal_date
class ordinate_dimension
class organization
class organization_assignment
class organization_relationship
class organization_role
class organizational_address
class organizational_project
class organizational_project_assignment
class organizational_project_relationship
class organizational_project_role
class oriented_closed_shell
class oriented_edge
class oriented_face
class oriented_open_shell
class oriented_path
class oriented_surface
class outer_boundary_curve
class over_riding_styled_item
class package_product_concept_feature
class parabola
class parallel_offset
class parallelism_tolerance
class parameter_value
class parametric_representation_context
class part_laminate_table
class partial_document_with_structured_text_representation_assignment
class path
class pcurve
class percentage_laminate_definition
class percentage_laminate_table
class percentage_ply_definition
class perpendicular_to
class perpendicularity_tolerance
class person
class person_and_organization
class person_and_organization_address
class person_and_organization_assignment
class person_and_organization_role
class personal_address
class physical_breakdown_context
class physical_element_usage
class picture_representation
class picture_representation_item
class placed_datum_target_feature
class placed_feature
class placement
class planar_box
class planar_extent
class plane
class plane_angle_measure
class plane_angle_measure_with_unit
class plane_angle_unit
class plus_minus_tolerance
class ply_laminate_definition
class ply_laminate_sequence_definition
class ply_laminate_table
class point
class point_and_vector
class point_on_curve
class point_on_surface
class point_path
class point_replica
class point_style
class polar_complex_number_literal
class poly_loop
class polyline
class position_tolerance
class positioned_sketch
class positive_integer
class positive_length_measure
class positive_plane_angle_measure
class positive_ratio_measure
class power_measure
class power_measure_with_unit
class power_unit
class pre_defined_colour
class pre_defined_curve_font
class pre_defined_dimension_symbol
class pre_defined_geometrical_tolerance_symbol
class pre_defined_item
class pre_defined_marker
class pre_defined_point_marker_symbol
class pre_defined_surface_condition_symbol
class pre_defined_surface_side_style
class pre_defined_symbol
class pre_defined_terminator_symbol
class pre_defined_text_font
class pre_defined_tile
class precision_qualifier
class predefined_picture_representation_item
class preferred_surface_curve_representation
class presentable_text
class presentation_area
class presentation_layer_assignment
class presentation_representation
class presentation_set
class presentation_size
class presentation_style_assignment
class presentation_style_by_context
class presentation_view
class presented_item
class presented_item_representation
class pressure_measure
class pressure_measure_with_unit
class pressure_unit
class procedural_representation
class procedural_representation_sequence
class procedural_shape_representation
class procedural_shape_representation_sequence
class product
class product_category
class product_class
class product_concept
class product_concept_context
class product_concept_feature
class product_concept_feature_association
class product_concept_feature_category
class product_concept_feature_category_usage
class product_concept_relationship
class product_context
class product_definition
class product_definition_context
class product_definition_context_association
class product_definition_context_role
class product_definition_effectivity
class product_definition_element_relationship
class product_definition_formation
class product_definition_formation_relationship
class product_definition_formation_with_specified_source
class product_definition_group_assignment
class product_definition_occurrence_relationship
class product_definition_relationship
class product_definition_shape
class product_definition_substitute
class product_definition_usage
class product_definition_with_associated_documents
class product_identification
class product_material_composition_relationship
class product_related_product_category
class product_specification
class projected_zone_definition
class projection_curve
class projection_directed_callout
class promissory_usage_occurrence
class property_definition
class property_definition_relationship
class property_definition_representation
class qualified_representation_item
class qualitative_uncertainty
class quantified_assembly_component_usage
class quasi_uniform_curve
class quasi_uniform_surface
class radioactivity_measure
class radioactivity_measure_with_unit
class radioactivity_unit
class radius_dimension
class range_characteristic
class ratio_measure
class ratio_measure_with_unit
class ratio_unit
class rational_b_spline_curve
class rational_b_spline_surface
class rational_representation_item
class real_literal
class real_representation_item
class rectangular_composite_surface
class rectangular_trimmed_surface
class referenced_modified_datum
class relative_event_occurrence
class rep_item_group
class reparametrised_composite_curve_segment
class representation
class representation_context
class representation_item
class representation_item_relationship
class representation_map
class representation_relationship
class representation_relationship_with_transformation
class requirement_assigned_object
class requirement_assignment
class requirement_source
class requirement_view_definition_relationship
class resistance_measure
class resistance_measure_with_unit
class resistance_unit
class revolved_area_solid
class revolved_face_solid
class revolved_face_solid_with_trim_conditions
class right_angular_wedge
class right_circular_cone
class right_circular_cylinder
class right_to_usage_association
class role_association
class roundness_tolerance
class row_representation_item
class row_value
class row_variable
class rule_action
class rule_condition
class rule_definition
class rule_set
class rule_set_group
class rule_software_definition
class rule_superseded_assignment
class rule_supersedence
class ruled_surface_swept_area_solid
class runout_zone_definition
class runout_zone_orientation
class runout_zone_orientation_reference_direction
class satisfied_requirement
class satisfies_requirement
class satisfying_item
class scalar_variable
class scattering_parameter
class sculptured_solid
class seam_curve
class second_in_minute
class security_classification
class security_classification_assignment
class security_classification_level
class serial_numbered_effectivity
class shading_curve_method
class shading_surface_method
class shape_aspect
class shape_aspect_associativity
class shape_aspect_deriving_relationship
class shape_aspect_relationship
class shape_definition_representation
class shape_dimension_representation
class shape_feature_definition
class shape_representation
class shape_representation_relationship
class shape_representation_with_parameters
class shell_based_surface_model
class shell_based_wireframe_model
class shell_based_wireframe_shape_representation
class shelled_solid
class si_absorbed_dose_unit
class si_capacitance_unit
class si_conductance_unit
class si_dose_equivalent_unit
class si_electric_charge_unit
class si_electric_potential_unit
class si_energy_unit
class si_force_unit
class si_frequency_unit
class si_illuminance_unit
class si_inductance_unit
class si_magnetic_flux_density_unit
class si_magnetic_flux_unit
class si_power_unit
class si_prefix
class si_pressure_unit
class si_radioactivity_unit
class si_resistance_unit
class si_unit
class si_unit_name
class simple_boolean_expression
class simple_clause
class simple_generic_expression
class simple_numeric_expression
class slash_expression
class smeared_material_definition
class solid_angle_measure
class solid_angle_measure_with_unit
class solid_angle_unit
class solid_curve_font
class solid_model
class solid_replica
class solid_with_angle_based_chamfer
class solid_with_chamfered_edges
class solid_with_circular_pattern
class solid_with_circular_pocket
class solid_with_circular_protrusion
class solid_with_conical_bottom_round_hole
class solid_with_constant_radius_edge_blend
class solid_with_curved_slot
class solid_with_depression
class solid_with_double_offset_chamfer
class solid_with_flat_bottom_round_hole
class solid_with_general_pocket
class solid_with_general_protrusion
class solid_with_groove
class solid_with_hole
class solid_with_incomplete_circular_pattern
class solid_with_incomplete_rectangular_pattern
class solid_with_pocket
class solid_with_protrusion
class solid_with_rectangular_pattern
class solid_with_rectangular_pocket
class solid_with_rectangular_protrusion
class solid_with_shape_element_pattern
class solid_with_single_offset_chamfer
class solid_with_slot
class solid_with_spherical_bottom_round_hole
class solid_with_stepped_round_hole
class solid_with_stepped_round_hole_and_conical_transitions
class solid_with_straight_slot
class solid_with_tee_section_slot
class solid_with_through_depression
class solid_with_trapezoidal_section_slot
class solid_with_variable_radius_edge_blend
class source
class source_for_requirement
class sourced_requirement
class specification_definition
class specified_higher_usage_occurrence
class sphere
class spherical_surface
class standard_uncertainty
class start_request
class start_work
class straightness_tolerance
class structured_dimension_callout
class structured_text_composition
class structured_text_representation
class styled_item
class subedge
class subface
class supplied_part_relationship
class surface
class surface_condition_callout
class surface_curve
class surface_curve_swept_area_solid
class surface_of_linear_extrusion
class surface_of_revolution
class surface_patch
class surface_profile_tolerance
class surface_rendering_properties
class surface_replica
class surface_side
class surface_side_style
class surface_style_boundary
class surface_style_control_grid
class surface_style_fill_area
class surface_style_parameter_line
class surface_style_reflectance_ambient
class surface_style_reflectance_ambient_diffuse
class surface_style_reflectance_ambient_diffuse_specular
class surface_style_rendering
class surface_style_rendering_with_properties
class surface_style_segmentation_curve
class surface_style_silhouette
class surface_style_transparent
class surface_style_usage
class surface_texture_representation
class surfaced_open_shell
class swept_area_solid
class swept_disk_solid
class swept_face_solid
class swept_surface
class symbol
class symbol_colour
class symbol_representation
class symbol_representation_map
class symbol_style
class symbol_target
class symmetric_shape_aspect
class symmetry_tolerance
class table_representation_item
class tactile_appearance_representation
class tagged_text_format
class tagged_text_item
class tangent
class terminator_symbol
class text
class text_alignment
class text_delineation
class text_font
class text_font_family
class text_font_in_family
class text_literal
class text_literal_with_associated_curves
class text_literal_with_blanking_box
class text_literal_with_delineation
class text_literal_with_extent
class text_path
class text_string_representation
class text_style
class text_style_for_defined_font
class text_style_with_box_characteristics
class text_style_with_mirror
class text_style_with_spacing
class thermal_resistance_measure_with_unit
class thermal_resistance_unit
class thermodynamic_temperature_measure
class thermodynamic_temperature_measure_with_unit
class thermodynamic_temperature_unit
class thickened_face_solid
class thickness_laminate_definition
class thickness_laminate_table
class time_interval
class time_interval_assignment
class time_interval_based_effectivity
class time_interval_relationship
class time_interval_role
class time_interval_with_bounds
class time_measure
class time_measure_with_unit
class time_unit
class tolerance_value
class tolerance_zone
class tolerance_zone_definition
class tolerance_zone_form
class topological_representation_item
class toroidal_surface
class torus
class total_runout_tolerance
class track_blended_solid
class track_blended_solid_with_end_conditions
class transformation_with_derived_angle
class transition_code
class trim_intent
class trimmed_curve
class trimming_preference
class two_direction_repeat_factor
class type_qualifier
class u_direction_count
class unary_generic_expression
class unary_numeric_expression
class uncertainty_assigned_representation
class uncertainty_measure_with_unit
class uncertainty_qualifier
class uniform_curve
class uniform_resource_identifier
class uniform_surface
class usage_association
class user_defined_curve_font
class user_defined_marker
class user_defined_terminator_symbol
class user_selected_elements
class user_selected_shape_elements
class v_direction_count
class value_range
class value_representation_item
class variable_semantics
class variational_representation_item
class vector
class vector_style
class velocity_measure
class velocity_measure_with_unit
class velocity_unit
class versioned_action_request
class vertex
class vertex_loop
class vertex_point
class vertex_shell
class view_volume
class visual_appearance_representation
class volume_measure
class volume_measure_with_unit
class volume_unit
class week_in_year_number
class week_of_year_and_day_date
class wire_shell
class year_month
class year_number
class zone_structural_makeup
Functions
def build_2axes (ref_direction)
def item_in_context (item, cntxt)
FUNCTION item_in_context #.
def default_tolerance_table_cell_wr3 (agg)
FUNCTION default_tolerance_table_cell_wr3 #.
def default_tolerance_table_cell_wr2 (agg)
FUNCTION default_tolerance_table_cell_wr2 #.
def gbsf_check_point (pnt)
FUNCTION gbsf_check_point #.
def acyclic_solid_replica (rep, parent)
FUNCTION acyclic_solid_replica #.
def build_axes (axis, ref_direction)
FUNCTION build_axes #.
def derive_angle (placement_1, placement_2)
FUNCTION derive_angle #.
def edge_reversed (an_edge)
FUNCTION edge_reversed #.
def default_tolerance_table_cell_wr5 (agg)
FUNCTION default_tolerance_table_cell_wr5 #.
def cc_design_person_and_organization_correlation (e)
FUNCTION cc_design_person_and_organization_correlation #.
def constraints_composite_curve_on_surface (c)
FUNCTION constraints_composite_curve_on_surface #.
def default_tolerance_table_cell_wr4 (agg)
FUNCTION default_tolerance_table_cell_wr4 #.
def check_continuous_edges (edges)
FUNCTION check_continuous_edges #.
def acyclic_mapped_representation (mi)
FUNCTION acyclic_mapped_representation #.
def get_name_value (obj)
FUNCTION get_name_value #.
def validate_countersink_radii (cskhole)
FUNCTION validate_countersink_radii #.
def dependently_instantiated (set_of_input_instances, set_of_input_types, previous_in_chain)
FUNCTION dependently_instantiated #.
def check_text_font (ct)
FUNCTION check_text_font #.
def conditional_reverse (p, an_item)
FUNCTION conditional_reverse #.
def nmsf_curve_check (cv)
FUNCTION nmsf_curve_check #.
def valid_measure_value (m)
FUNCTION valid_measure_value #.
def gbsf_check_curve (cv)
FUNCTION gbsf_check_curve #.
def base_axis (dim, axis1, axis2, axis3)
FUNCTION base_axis #.
def get_basis_surface (c)
FUNCTION get_basis_surface #.
def list_face_loops (f)
FUNCTION list_face_loops #.
def list_of_topology_reversed (a_list)
FUNCTION list_of_topology_reversed #.
def msf_curve_check (cv)
FUNCTION msf_curve_check #.
def shell_reversed (a_shell)
FUNCTION shell_reversed #.
def topology_reversed (an_item)
FUNCTION topology_reversed #.
def first_proj_axis (z_axis, arg)
FUNCTION first_proj_axis #.
def acyclic_composite_text (start_composite, child_text)
FUNCTION acyclic_composite_text #.
def get_shape_aspect_property_definition_representations (s_a_instance)
FUNCTION get_shape_aspect_property_definition_representations #.
def orthogonal_complement (vec)
FUNCTION orthogonal_complement #.
def acyclic_representation_relationship (relation, relatives, specific_relation)
FUNCTION acyclic_representation_relationship #.
def make_array_of_array (lis, low1, u1, low2, u2)
FUNCTION make_array_of_array #.
def compute_total_depth (swsrh)
FUNCTION compute_total_depth #.
def second_proj_axis (z_axis, x_axis, arg)
FUNCTION second_proj_axis #.
def bag_to_set (the_bag)
FUNCTION bag_to_set #.
def valid_wireframe_edge_curve (crv)
FUNCTION valid_wireframe_edge_curve #.
def surface_weights_positive (b)
FUNCTION surface_weights_positive #.
def vector_difference (arg1, arg2)
FUNCTION vector_difference #.
def advanced_face_properties (testface)
FUNCTION advanced_face_properties #.
def external_version_assignment_is_valid (aia)
FUNCTION external_version_assignment_is_valid #.
def value_range_wr1 (agg)
FUNCTION value_range_wr1 #.
def value_range_wr3 (agg)
FUNCTION value_range_wr3 #.
def acyclic_product_definition_relationship (relation, relatives, specific_relation)
FUNCTION acyclic_product_definition_relationship #.
def value_range_wr2 (agg)
FUNCTION value_range_wr2 #.
def constraints_geometry_shell_based_wireframe_model (m)
FUNCTION constraints_geometry_shell_based_wireframe_model #.
def list_to_set (l)
FUNCTION list_to_set #.
def valid_calendar_date (date)
FUNCTION valid_calendar_date #.
def valid_wireframe_vertex_point (pnt)
FUNCTION valid_wireframe_vertex_point #.
def list_to_array (lis, low, u)
FUNCTION list_to_array #.
def using_items (item, checked_items)
FUNCTION using_items #.
def valid_basis_curve_in_2d_wireframe (crv)
FUNCTION valid_basis_curve_in_2d_wireframe #.
def constraints_geometry_shell_based_surface_model (m)
FUNCTION constraints_geometry_shell_based_surface_model #.
def face_bound_reversed (a_face_bound)
FUNCTION face_bound_reversed #.
def acyclic (arg1, arg2)
FUNCTION acyclic #.
def set_of_topology_reversed (a_set)
FUNCTION set_of_topology_reversed #.
def is_int_expr (arg)
FUNCTION is_int_expr #.
def dimension_of (item)
FUNCTION dimension_of #.
def scalar_times_vector (scalar, vec)
FUNCTION scalar_times_vector #.
def dimensions_for_si_unit (n)
FUNCTION dimensions_for_si_unit #.
def surface_condition_correlation (pd, rep)
FUNCTION surface_condition_correlation #.
def open_shell_reversed (a_shell)
FUNCTION open_shell_reversed #.
def acyclic_surface_replica (rep, parent)
FUNCTION acyclic_surface_replica #.
def gbsf_check_surface (sf)
FUNCTION gbsf_check_surface #.
def msf_surface_check (surf)
FUNCTION msf_surface_check #.
def normalise (arg)
FUNCTION normalise #.
def msb_shells (brep)
FUNCTION msb_shells #.
def nmsf_surface_check (surf)
FUNCTION nmsf_surface_check #.
def mixed_loop_type_set (l)
FUNCTION mixed_loop_type_set #.
def derive_dimensional_exponents (x)
FUNCTION derive_dimensional_exponents #.
def curve_weights_positive (b)
FUNCTION curve_weights_positive #.
def type_check_function (the_type, sub_names, criterion)
FUNCTION type_check_function #.
def valid_geometrically_bounded_wf_point (pnt)
FUNCTION valid_geometrically_bounded_wf_point #.
def path_head_to_tail (a_path)
FUNCTION path_head_to_tail #.
def path_reversed (a_path)
FUNCTION path_reversed #.
def get_id_value (obj)
FUNCTION get_id_value #.
def aspect_ratio (p)
FUNCTION aspect_ratio #.
def is_acyclic (arg)
FUNCTION is_acyclic #.
def check_text_alignment (ct)
FUNCTION check_text_alignment #.
def leap_year (year)
FUNCTION leap_year #.
def face_reversed (a_face)
FUNCTION face_reversed #.
def get_description_value (obj)
FUNCTION get_description_value #.
def constraints_param_b_spline (degree, up_knots, up_cp, knot_mult, knots)
FUNCTION constraints_param_b_spline #.
def value_range_aggregate_rep_item (agg)
FUNCTION value_range_aggregate_rep_item #.
def acyclic_mapped_item_usage (rep)
FUNCTION acyclic_mapped_item_usage #.
def class_assignment_is_valid (aia)
FUNCTION class_assignment_is_valid #.
def using_representations (item)
FUNCTION using_representations #.
def control_characters_free (s)
FUNCTION control_characters_free #.
def associated_surface (arg)
FUNCTION associated_surface #.
def acyclic_point_replica (rep, parent)
FUNCTION acyclic_point_replica #.
def valid_datum_target_parameters (pdf)
FUNCTION valid_datum_target_parameters #.
def cross_product (arg1, arg2)
FUNCTION cross_product #.
def categories_of_product (obj)
FUNCTION categories_of_product #.
def valid_units (m)
FUNCTION valid_units #.
def valid_selected_instance_representation (pd)
FUNCTION valid_selected_instance_representation #.
def constraints_rectangular_composite_surface (s)
FUNCTION constraints_rectangular_composite_surface #.
def closed_shell_reversed (a_shell)
FUNCTION closed_shell_reversed #.
def boolean_choose (b, choice1, choice2)
FUNCTION boolean_choose #.
def valid_time (time)
FUNCTION valid_time #.
def is_sql_mappable (arg)
FUNCTION is_sql_mappable #.
def valid_geometrically_bounded_wf_curve (crv)
FUNCTION valid_geometrically_bounded_wf_curve #.
def dot_product (arg1, arg2)
FUNCTION dot_product #.
def get_role (obj)
FUNCTION get_role #.
def acyclic_curve_replica (rep, parent)
FUNCTION acyclic_curve_replica #.
Variables
schema_name
schema_scope
characterized_definition
scope = schema_scope)
geometric_item_specific_usage_select
attribute_language_item
change_request_item
configured_effectivity_context_item
font_select
action_request_item
blend_end_condition_select
draughting_callout_element
name_item
classification_item
curve_font_or_scaled_curve_font_select
characterized_product_definition
reversible_topology_item
size_select
axis2_placement
symbol_style_select
presentation_style_select
set_of_reversible_topology_item = SET(0,None,'reversible_topology_item', scope = schema_scope)
presented_item_select
angle_direction_reference_with_a2p3d_select
set_representation_item = SET(1,None,'representation_item', scope = schema_scope)
angle_direction_reference_select
presentation_representation_select
text_or_character
character_style_select
picture_representation_item_select
annotation_symbol_occurrence_item
invisibility_context
external_identification_item
compound_item_definition
product_definition_or_breakdown_element_usage
draughting_model_item_association_select
represented_definition
text_string_representation_item
event_occurrence_item
measure_value
person_organization_select
presentation_size_assignment_select
date_and_time_item
rendering_properties_select
cc_specified_item
list_representation_item = LIST(1,None,'representation_item', scope = schema_scope)
sketch_basis_select
document_identifier_assigned_item
csg_select
annotation_representation_select
layered_item
pcurve_or_surface
orientation_basis_select
attribute_type
cc_person_organization_item
id_attribute_select
invisible_item
generalized_surface_select
characterized_product_composition_value
effectivity_item
multi_language_attribute_item
draughting_titled_item
surface_style_element_select
security_classification_item
action_items
dimensional_characteristic
document_reference_item
requirement_source_item
classified_item
mechanical_design_geometric_presentation_representation_items
area_or_view
founded_item_select
style_context_select
rule_superseded_item
camera_model_d3_multi_clipping_union_select
product_definition_or_assembly_relationship
source_item
trim_condition_select
contract_item
configured_effectivity_item
date_time_or_event_occurrence
derived_property_select
fill_area_style_tile_shape_select
vector_or_direction
requirement_assigned_item
approval_item
cc_classified_item
geometric_set_select
start_request_item
category_usage_item
base_solid_select
defined_symbol_select
date_time_item
shell
transformation
boolean_operand
certified_item
curve_or_annotation_curve_occurrence
date_time_select
groupable_item
csg_primitive
marker_select
camera_model_d3_multi_clipping_interection_select
constructive_geometry_representation_or_shape_represenation
organization_item
product_or_formation_or_definition
curve_on_surface
attribute_classification_item
string_representation_item_select
trimming_select
curve_style_font_select
point_path_members = LIST(1,None,'point_and_vector', scope = schema_scope)
role_select
contracted_item
characterized_action_definition
tolerance_method_definition
plane_or_planar_box
time_interval_item
character_spacing_select
requirement_satisfaction_item
description_attribute_select
mechanical_design_and_draughting_relationship_select
curve_or_render
name_attribute_select
unit
characterized_material_property
date_item
reversible_topology
work_item
point_and_vector_members = LIST(2,3,'point_and_vector_member', scope = schema_scope)
shape_definition
annotation_text_occurrence_item
mechanical_design_geometric_presentation_area_items
point_and_vector_member
instance_usage_context_select
project_item
person_and_organization_item
box_characteristic_select
certification_item
action_method_items
fill_style_select
draughting_model_item_select
value_qualifier
ir_usage_item
product_definition_or_product_definition_relationship
approved_item
annotation_plane_element
identification_item
direction_count_select
list_of_reversible_topology_item = LIST(0,None,'reversible_topology_item', scope = schema_scope)
configuration_design_item
class_usage_effectivity_context_item
surface_side_style_select
draughting_model_items_constraint = Rule()
RULE draughting_model_items_constraint #.
restrict_product_definitions_for_part_definition_relationship = Rule()
RULE restrict_product_definitions_for_part_definition_relationship #.
restrict_product_definitions_for_base_element = Rule()
RULE restrict_product_definitions_for_base_element #.
restrict_configuration_design_for_design_constraint = Rule()
RULE restrict_configuration_design_for_design_constraint #.
compatible_dimension = Rule()
RULE compatible_dimension #.
restrict_alternative_definition = Rule()
RULE restrict_alternative_definition #.
restrict_group_relationship_for_classification_hierarchy = Rule()
RULE restrict_group_relationship_for_classification_hierarchy #.
subtype_exclusiveness_geometric_tolerance = Rule()
RULE subtype_exclusiveness_geometric_tolerance #.
alternative_solution_requires_solution_definition = Rule()
RULE alternative_solution_requires_solution_definition #.
restrict_centre_of_mass_representation = Rule()
RULE restrict_centre_of_mass_representation #.
selected_instance_usage_requires_representation = Rule()
RULE selected_instance_usage_requires_representation #.
external_version_assignments_are_valid = Rule()
RULE external_version_assignments_are_valid #.
application_protocol_definition_required = Rule()
RULE application_protocol_definition_required #.
thickness_laminate_table_component_select = Rule()
RULE thickness_laminate_table_component_select #.
consistent_uncertainty = Rule()
RULE consistent_uncertainty #.
ply_reference = Rule()
RULE ply_reference #.
breakdown_element_requires_product_definition = Rule()
RULE breakdown_element_requires_product_definition #.
product_definition_replacement_requires_effectivity_assignment = Rule()
RULE product_definition_replacement_requires_effectivity_assignment #.
component_class_for_assembly_select = Rule()
RULE component_class_for_assembly_select #.
restrict_configuration_design_for_class_breakdown_association = Rule()
RULE restrict_configuration_design_for_class_breakdown_association #.
solution_definition_requires_solution_category = Rule()
RULE solution_definition_requires_solution_category #.
restrict_product_definitions_for_collection = Rule()
RULE restrict_product_definitions_for_collection #.
restrict_treatment_result = Rule()
RULE restrict_treatment_result #.
restrict_concept_feature_operator = Rule()
RULE restrict_concept_feature_operator #.
restrict_part_occurrence = Rule()
RULE restrict_part_occurrence #.
constraint_definition_requires_constraint_category = Rule()
RULE constraint_definition_requires_constraint_category #.
design_constraint_requires_product_definition = Rule()
RULE design_constraint_requires_product_definition #.
restrict_product_definitions_for_definition_usage = Rule()
RULE restrict_product_definitions_for_definition_usage #.
plib_property_reference_requires_name_scope = Rule()
RULE plib_property_reference_requires_name_scope #.
ply_stock_material_select = Rule()
RULE ply_stock_material_select #.
styled_curve = Rule()
RULE styled_curve #.
subtype_exclusiveness_representation_item = Rule()
RULE subtype_exclusiveness_representation_item #.
text_font_usage = Rule()
RULE text_font_usage #.
restrict_classification_assignments = Rule()
RULE restrict_classification_assignments #.
restrict_language_assignment_per_attribute = Rule()
RULE restrict_language_assignment_per_attribute #.
stock_material_reference = Rule()
RULE stock_material_reference #.
restrict_group_relationship_for_specification_category = Rule()
RULE restrict_group_relationship_for_specification_category #.
restrict_representation_for_surface_condition = Rule()
RULE restrict_representation_for_surface_condition #.
material_for_coating_layer = Rule()
RULE material_for_coating_layer #.
restrict_product_definitions_for_design_constraint_association = Rule()
RULE restrict_product_definitions_for_design_constraint_association #.
restrict_part_occurrence_category = Rule()
RULE restrict_part_occurrence_category #.
subtype_mandatory_geometric_tolerance = Rule()
RULE subtype_mandatory_geometric_tolerance #.
product_concept_feature_requires_category = Rule()
RULE product_concept_feature_requires_category #.
restrict_assembly_category = Rule()
RULE restrict_assembly_category #.
restrict_collection_category = Rule()
RULE restrict_collection_category #.
plib_property_reference_requires_version = Rule()
RULE plib_property_reference_requires_version #.
validate_dependently_instantiable_entity_data_types = Rule()
RULE validate_dependently_instantiable_entity_data_types #.
Function Documentation
acyclic()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.acyclic (arg1, arg2)
FUNCTION acyclic #.
:param arg1
:type arg1:generic_expression
:param arg2
:type arg2:(null)
Definition at line 40597 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
Referenced by is_acyclic().
acyclic_composite_text()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.acyclic_composite_text (start_composite, child_text)
FUNCTION acyclic_composite_text #.
:param start_composite
:type start_composite:composite_text
:param child_text
:type child_text:(null)
Definition at line 40099 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.HIINDEX(), and SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.composite_text.wr1().
acyclic_curve_replica()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.acyclic_curve_replica (rep, parent)
FUNCTION acyclic_curve_replica #.
:param rep
:type rep:curve_replica
:param parent
:type parent:curve
Definition at line 41745 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.TYPEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.curve_replica.wr2().
acyclic_mapped_item_usage()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.acyclic_mapped_item_usage (rep)
FUNCTION acyclic_mapped_item_usage #.
:param rep
:type rep:representation
Definition at line 41248 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.HIINDEX(), and SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_subfigure_representation.wr4(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_symbol_representation.wr5().
acyclic_mapped_representation()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.acyclic_mapped_representation (mi)
FUNCTION acyclic_mapped_representation #.
:param mi
:type mi:mapped_item
Definition at line 39660 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References bag_to_set(), SCL.Builtin.HIINDEX(), SCL.Builtin.SIZEOF(), SCL.Builtin.USEDIN(), and using_representations().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mapped_item.wr1().
acyclic_point_replica()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.acyclic_point_replica (rep, parent)
FUNCTION acyclic_point_replica #.
:param rep
:type rep:point_replica
:param parent
:type parent:point
Definition at line 41345 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.TYPEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.point_replica.wr2().
acyclic_product_definition_relationship()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.acyclic_product_definition_relationship (relation, relatives, specific_relation)
FUNCTION acyclic_product_definition_relationship #.
:param relation
:type relation:product_definition_relationship
:param relatives
:type relatives:(null)
:param specific_relation
:type specific_relation:STRING
Definition at line 40388 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.HIINDEX().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_definition_usage.wr1().
acyclic_representation_relationship()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.acyclic_representation_relationship (relation, relatives, specific_relation)
FUNCTION acyclic_representation_relationship #.
:param relation
:type relation:representation_relationship
:param relatives
:type relatives:(null)
:param specific_relation
:type specific_relation:STRING
Definition at line 40156 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.HIINDEX().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.definitional_representation_relationship.wr1().
acyclic_solid_replica()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.acyclic_solid_replica (rep, parent)
FUNCTION acyclic_solid_replica #.
:param rep
:type rep:solid_replica
:param parent
:type parent:solid_model
Definition at line 39484 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.TYPEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_replica.wr1().
acyclic_surface_replica()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.acyclic_surface_replica (rep, parent)
FUNCTION acyclic_surface_replica #.
:param rep
:type rep:surface_replica
:param parent
:type parent:surface
Definition at line 40841 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.TYPEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_replica.wr1().
advanced_face_properties()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.advanced_face_properties (testface)
FUNCTION advanced_face_properties #.
:param testface
:type testface:face
Definition at line 40327 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.TYPEOF().
aspect_ratio()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.aspect_ratio (p)
FUNCTION aspect_ratio #.
:param p
:type p:planar_box
Definition at line 41120 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.camera_image_3d_with_scale.wr2().
associated_surface()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.associated_surface (arg)
FUNCTION associated_surface #.
:param arg
:type arg:pcurve_or_surface
Definition at line 41331 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.TYPEOF().
Referenced by get_basis_surface(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.intersection_curve.wr2(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.seam_curve.wr2().
bag_to_set()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.bag_to_set (the_bag)
FUNCTION bag_to_set #.
:param the_bag
:type the_bag:(null)
Definition at line 40241 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.HIINDEX(), and SCL.Builtin.SIZEOF().
Referenced by acyclic_mapped_representation(), get_shape_aspect_property_definition_representations(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.material_property.wr1().
base_axis()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.base_axis (dim, axis1, axis2, axis3)
FUNCTION base_axis #.
:param dim
:type dim:INTEGER
:param axis1
:type axis1:direction
:param axis2
:type axis2:direction
:param axis3
:type axis3:direction
Definition at line 39900 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References dot_product(), SCL.Builtin.EXISTS(), first_proj_axis(), normalise(), SCL.Builtin.NVL(), orthogonal_complement(), and second_proj_axis().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.cartesian_transformation_operator_3d.u(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.cartesian_transformation_operator_2d.u().
boolean_choose()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.boolean_choose (b, choice1, choice2)
FUNCTION boolean_choose #.
:param b
:type b:BOOLEAN
:param choice1
:type choice1:(null)
:param choice2
:type choice2:(null)
Definition at line 41600 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.oriented_edge.edge_edge_end(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.oriented_edge.edge_edge_start().
build_2axes()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.build_2axes (ref_direction)
:param ref_direction
:type ref_direction:direction
Definition at line 39405 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References orthogonal_complement().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.axis2_placement_2d.p().
build_axes()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.build_axes (axis, ref_direction)
FUNCTION build_axes #.
:param axis
:type axis:direction
:param ref_direction
:type ref_direction:direction
Definition at line 39501 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References cross_product(), first_proj_axis(), normalise(), and SCL.Builtin.NVL().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.axis2_placement_3d.p().
categories_of_product()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.categories_of_product (obj)
FUNCTION categories_of_product #.
:param obj
:type obj:product
Definition at line 41413 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.HIINDEX(), SCL.Builtin.LOINDEX(), and SCL.Builtin.USEDIN().
cc_design_person_and_organization_correlation()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.cc_design_person_and_organization_correlation (e)
FUNCTION cc_design_person_and_organization_correlation #.
:param e
:type e:cc_design_person_and_organization_assignment
Definition at line 39563 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.cc_design_person_and_organization_assignment.wr1().
check_continuous_edges()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.check_continuous_edges (edges)
FUNCTION check_continuous_edges #.
:param edges
:type edges:(null)
Definition at line 39631 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.HIINDEX(), and SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.track_blended_solid.wr1().
check_text_alignment()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.check_text_alignment (ct)
FUNCTION check_text_alignment #.
:param ct
:type ct:composite_text
Definition at line 41143 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.HIINDEX(), and SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_annotation_occurrence.wr11().
check_text_font()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.check_text_font (ct)
FUNCTION check_text_font #.
:param ct
:type ct:composite_text
Definition at line 39769 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.HIINDEX(), and SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_annotation_occurrence.wr12().
class_assignment_is_valid()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.class_assignment_is_valid (aia)
FUNCTION class_assignment_is_valid #.
:param aia
:type aia:applied_classification_assignment
Definition at line 41267 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.HIINDEX(), SCL.Builtin.LOINDEX(), SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
closed_shell_reversed()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.closed_shell_reversed (a_shell)
FUNCTION closed_shell_reversed #.
:param a_shell
:type a_shell:closed_shell
Definition at line 41586 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.TYPEOF().
Referenced by shell_reversed().
compute_total_depth()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.compute_total_depth (swsrh)
FUNCTION compute_total_depth #.
:param swsrh
:type swsrh:solid_with_stepped_round_hole
Definition at line 40203 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_stepped_round_hole.solid_with_depression_depth().
conditional_reverse()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conditional_reverse (p, an_item)
FUNCTION conditional_reverse #.
:param p
:type p:BOOLEAN
:param an_item
:type an_item:reversible_topology
Definition at line 39781 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References topology_reversed().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.oriented_open_shell.connected_face_set_cfs_faces(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.oriented_closed_shell.connected_face_set_cfs_faces(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.oriented_face.face_bounds(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.oriented_path.path_edge_list().
constraints_composite_curve_on_surface()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.constraints_composite_curve_on_surface (c)
FUNCTION constraints_composite_curve_on_surface #.
:param c
:type c:composite_curve_on_surface
Definition at line 39604 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.TYPEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.composite_curve_on_surface.wr2().
constraints_geometry_shell_based_surface_model()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.constraints_geometry_shell_based_surface_model (m)
FUNCTION constraints_geometry_shell_based_surface_model #.
:param m
:type m:shell_based_surface_model
Definition at line 40569 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.shell_based_surface_model.wr1().
constraints_geometry_shell_based_wireframe_model()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.constraints_geometry_shell_based_wireframe_model (m)
FUNCTION constraints_geometry_shell_based_wireframe_model #.
:param m
:type m:shell_based_wireframe_model
Definition at line 40422 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.shell_based_wireframe_model.wr1().
constraints_param_b_spline()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.constraints_param_b_spline (degree, up_knots, up_cp, knot_mult, knots)
FUNCTION constraints_param_b_spline #.
:param degree
:type degree:INTEGER
:param up_knots
:type up_knots:INTEGER
:param up_cp
:type up_cp:INTEGER
:param knot_mult
:type knot_mult:(null)
:param knots
:type knots:(null)
Definition at line 41195 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.b_spline_curve_with_knots.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.b_spline_surface_with_knots.wr1(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.b_spline_surface_with_knots.wr2().
constraints_rectangular_composite_surface()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.constraints_rectangular_composite_surface (s)
FUNCTION constraints_rectangular_composite_surface #.
:param s
:type s:rectangular_composite_surface
Definition at line 41564 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.TYPEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.rectangular_composite_surface.wr2().
control_characters_free()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.control_characters_free (s)
FUNCTION control_characters_free #.
:param s
:type s:STRING
Definition at line 41317 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References LENGTH.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.presentable_text.wr1().
cross_product()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.cross_product (arg1, arg2)
FUNCTION cross_product #.
:param arg1
:type arg1:direction
:param arg2
:type arg2:direction
Definition at line 41387 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.EXISTS(), normalise(), and SQRT.
Referenced by build_axes(), first_proj_axis(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.axis2_placement_3d.wr4().
curve_weights_positive()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.curve_weights_positive (b)
FUNCTION curve_weights_positive #.
:param b
:type b:rational_b_spline_curve
Definition at line 41023 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.rational_b_spline_curve.wr2().
default_tolerance_table_cell_wr2()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.default_tolerance_table_cell_wr2 (agg)
FUNCTION default_tolerance_table_cell_wr2 #.
:param agg
:type agg:compound_item_definition
Definition at line 39449 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.default_tolerance_table_cell.wr2().
default_tolerance_table_cell_wr3()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.default_tolerance_table_cell_wr3 (agg)
FUNCTION default_tolerance_table_cell_wr3 #.
:param agg
:type agg:compound_item_definition
Definition at line 39435 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.default_tolerance_table_cell.wr3().
default_tolerance_table_cell_wr4()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.default_tolerance_table_cell_wr4 (agg)
FUNCTION default_tolerance_table_cell_wr4 #.
:param agg
:type agg:compound_item_definition
Definition at line 39617 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.default_tolerance_table_cell.wr4().
default_tolerance_table_cell_wr5()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.default_tolerance_table_cell_wr5 (agg)
FUNCTION default_tolerance_table_cell_wr5 #.
:param agg
:type agg:compound_item_definition
Definition at line 39549 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.default_tolerance_table_cell.wr5().
dependently_instantiated()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dependently_instantiated (set_of_input_instances, set_of_input_types, previous_in_chain)
FUNCTION dependently_instantiated #.
:param set_of_input_instances
:type set_of_input_instances:(null)
:param set_of_input_types
:type set_of_input_types:(null)
:param previous_in_chain
:type previous_in_chain:(null)
Definition at line 39728 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.EXISTS(), SCL.Builtin.SIZEOF(), SCL.Builtin.TYPEOF(), and SCL.Builtin.USEDIN().
derive_angle()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.derive_angle (placement_1, placement_2)
FUNCTION derive_angle #.
:param placement_1
:type placement_1:axis2_placement_3d
:param placement_2
:type placement_2:axis2_placement_3d
Definition at line 39515 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ACOS, and SQRT.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.transformation_with_derived_angle.orientation_angle().
derive_dimensional_exponents()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.derive_dimensional_exponents (x)
FUNCTION derive_dimensional_exponents #.
:param x
:type x:unit
Definition at line 41002 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.HIINDEX(), SCL.Builtin.LOINDEX(), and SCL.Builtin.TYPEOF().
Referenced by valid_units(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.magnetic_flux_density_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.force_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.thermal_resistance_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.energy_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.frequency_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.power_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.acceleration_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dose_equivalent_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.luminous_flux_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.capacitance_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.inductance_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.resistance_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.magnetic_flux_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.electric_potential_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.absorbed_dose_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.electric_charge_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.illuminance_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.pressure_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.radioactivity_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conductance_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.velocity_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.area_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.volume_unit.wr1(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.projected_zone_definition.wr2().
dimension_of()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimension_of (item)
FUNCTION dimension_of #.
:param item
:type item:geometric_representation_item
Definition at line 40685 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF(), SCL.Builtin.TYPEOF(), and using_representations().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_representation_item.dim().
dimensions_for_si_unit()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensions_for_si_unit (n)
FUNCTION dimensions_for_si_unit #.
:param n
:type n:si_unit_name
Definition at line 40733 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.si_unit.named_unit_dimensions(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.magnetic_flux_density_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.force_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.energy_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.frequency_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.power_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dose_equivalent_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.luminous_flux_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.capacitance_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.inductance_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.resistance_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.magnetic_flux_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.electric_potential_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.absorbed_dose_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.electric_charge_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.illuminance_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.pressure_unit.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.radioactivity_unit.wr1(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conductance_unit.wr1().
dot_product()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dot_product (arg1, arg2)
FUNCTION dot_product #.
:param arg1
:type arg1:direction
:param arg2
:type arg2:direction
Definition at line 41707 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.EXISTS(), and normalise().
Referenced by base_axis(), first_proj_axis(), second_proj_axis(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.camera_model_d3.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.extruded_face_solid.wr1(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.extruded_area_solid.wr1().
edge_reversed()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.edge_reversed (an_edge)
FUNCTION edge_reversed #.
:param an_edge
:type an_edge:edge
Definition at line 39535 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.TYPEOF().
Referenced by topology_reversed().
external_version_assignment_is_valid()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.external_version_assignment_is_valid (aia)
FUNCTION external_version_assignment_is_valid #.
:param aia
:type aia:applied_external_identification_assignment
Definition at line 40342 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.HIINDEX(), SCL.Builtin.LOINDEX(), SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
face_bound_reversed()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.face_bound_reversed (a_face_bound)
FUNCTION face_bound_reversed #.
:param a_face_bound
:type a_face_bound:face_bound
Definition at line 40583 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.TYPEOF().
Referenced by topology_reversed().
face_reversed()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.face_reversed (a_face)
FUNCTION face_reversed #.
:param a_face
:type a_face:face
Definition at line 41168 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References set_of_topology_reversed(), and SCL.Builtin.TYPEOF().
Referenced by topology_reversed().
first_proj_axis()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.first_proj_axis (z_axis, arg)
FUNCTION first_proj_axis #.
:param z_axis
:type z_axis:direction
:param arg
:type arg:direction
Definition at line 40068 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References cross_product(), dot_product(), SCL.Builtin.EXISTS(), normalise(), scalar_times_vector(), and vector_difference().
Referenced by base_axis(), and build_axes().
gbsf_check_curve()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.gbsf_check_curve (cv)
FUNCTION gbsf_check_curve #.
:param cv
:type cv:representation_item
Definition at line 39855 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References gbsf_check_surface(), SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
Referenced by gbsf_check_point(), and gbsf_check_surface().
gbsf_check_point()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.gbsf_check_point (pnt)
FUNCTION gbsf_check_point #.
:param pnt
:type pnt:point
Definition at line 39463 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References gbsf_check_curve(), gbsf_check_surface(), and SCL.Builtin.TYPEOF().
gbsf_check_surface()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.gbsf_check_surface (sf)
FUNCTION gbsf_check_surface #.
:param sf
:type sf:surface
Definition at line 40858 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References gbsf_check_curve(), SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
Referenced by gbsf_check_curve(), and gbsf_check_point().
get_basis_surface()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.get_basis_surface (c)
FUNCTION get_basis_surface #.
:param c
:type c:curve_on_surface
Definition at line 39937 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References associated_surface(), SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.composite_curve_on_surface.basis_surface(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_curve.basis_surface().
get_description_value()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.get_description_value (obj)
FUNCTION get_description_value #.
:param obj
:type obj:description_attribute_select
Definition at line 41182 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation.description(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.effectivity.description(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.application_context.description(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.approval_role.description(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.action_request_solution.description(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.property_definition_representation.description(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.person_and_organization_role.description(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.context_dependent_shape_representation.description(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.external_source.description(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.organization_role.description(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.date_time_role.description(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.date_role.description(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.configuration_design.description(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.person_and_organization.description().
get_id_value()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.get_id_value (obj)
FUNCTION get_id_value #.
:param obj
:type obj:id_attribute_select
Definition at line 41107 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation.id(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.group.id(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.shape_aspect.id(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_category.id(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.shape_aspect_relationship.id(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.application_context.id(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.property_definition.id(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.action.id(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.organizational_project.id(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.address.url().
get_name_value()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.get_name_value (obj)
FUNCTION get_name_value #.
:param obj
:type obj:name_attribute_select
Definition at line 39684 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.derived_unit.name(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.effectivity.name(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_definition.name(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.address.name(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.action_request_solution.name(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.property_definition_representation.name(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_definition_substitute.name(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.context_dependent_shape_representation.name(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.configuration_design.name(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.person_and_organization.name().
get_role()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.get_role (obj)
FUNCTION get_role #.
:param obj
:type obj:role_select
Definition at line 41732 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.action_assignment.role(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.certification_assignment.role(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.group_assignment.role(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.action_request_assignment.role(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.effectivity_assignment.role(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.approval_date_time.role(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.contract_assignment.role(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.approval_assignment.role(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.document_reference.role(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.name_assignment.role(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.security_classification_assignment.role().
get_shape_aspect_property_definition_representations()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.get_shape_aspect_property_definition_representations (s_a_instance)
FUNCTION get_shape_aspect_property_definition_representations #.
:param s_a_instance
:type s_a_instance:shape_aspect
Definition at line 40127 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References bag_to_set(), SCL.Builtin.HIINDEX(), SCL.Builtin.SIZEOF(), and SCL.Builtin.USEDIN().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.placed_datum_target_feature.representation_associations().
is_acyclic()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.is_acyclic (arg)
FUNCTION is_acyclic #.
:param arg
:type arg:generic_expression
Definition at line 41133 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References acyclic().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.generic_expression.wr1().
is_int_expr()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.is_int_expr (arg)
FUNCTION is_int_expr #.
:param arg
:type arg:numeric_expression
Definition at line 40635 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.numeric_expression.is_int().
is_sql_mappable()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.is_sql_mappable (arg)
FUNCTION is_sql_mappable #.
:param arg
:type arg:expression
Definition at line 41630 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.numeric_expression.sql_mappable().
item_in_context()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.item_in_context (item, cntxt)
FUNCTION item_in_context #.
:param item
:type item:representation_item
:param cntxt
:type cntxt:representation_context
Definition at line 39415 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.HIINDEX(), SCL.Builtin.SIZEOF(), and SCL.Builtin.USEDIN().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.presentation_size.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation_map.wr1(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.character_glyph_symbol.wr2().
leap_year()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.leap_year (year)
FUNCTION leap_year #.
:param year
:type year:INTEGER
Definition at line 41155 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by valid_calendar_date(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.ordinal_date.wr1().
list_face_loops()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.list_face_loops (f)
FUNCTION list_face_loops #.
:param f
:type f:face
Definition at line 39961 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.face.wr1(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.subface.wr1().
list_of_topology_reversed()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.list_of_topology_reversed (a_list)
FUNCTION list_of_topology_reversed #.
:param a_list
:type a_list:list_of_reversible_topology_item
Definition at line 39973 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF(), and topology_reversed().
Referenced by path_reversed(), and topology_reversed().
list_to_array()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.list_to_array (lis, low, u)
FUNCTION list_to_array #.
:param lis
:type lis:(null)
:param low
:type low:INTEGER
:param u
:type u:INTEGER
Definition at line 40502 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.b_spline_curve.control_points(), make_array_of_array(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.rational_b_spline_curve.weights().
list_to_set()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.list_to_set (l)
FUNCTION list_to_set #.
:param l
:type l:(null)
Definition at line 40436 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.face.wr1(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.subface.wr1().
make_array_of_array()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.make_array_of_array (lis, low1, u1, low2, u2)
FUNCTION make_array_of_array #.
:param lis
:type lis:(null)
:param low1
:type low1:INTEGER
:param u1
:type u1:INTEGER
:param low2
:type low2:INTEGER
:param u2
:type u2:INTEGER
Definition at line 40176 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.HIINDEX(), list_to_array(), and SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.b_spline_surface.control_points(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.rational_b_spline_surface.weights().
mixed_loop_type_set()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mixed_loop_type_set (l)
FUNCTION mixed_loop_type_set #.
:param l
:type l:(null)
Definition at line 40986 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.face.wr1(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.subface.wr1(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.wire_shell.wr1().
msb_shells()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.msb_shells (brep)
FUNCTION msb_shells #.
:param brep
:type brep:manifold_solid_brep
Definition at line 40950 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
msf_curve_check()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.msf_curve_check (cv)
FUNCTION msf_curve_check #.
:param cv
:type cv:representation_item
Definition at line 39986 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References msf_surface_check(), SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
Referenced by msf_surface_check().
msf_surface_check()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.msf_surface_check (surf)
FUNCTION msf_surface_check #.
:param surf
:type surf:surface
Definition at line 40889 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References msf_curve_check(), and SCL.Builtin.TYPEOF().
Referenced by msf_curve_check().
nmsf_curve_check()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.nmsf_curve_check (cv)
FUNCTION nmsf_curve_check #.
:param cv
:type cv:representation_item
Definition at line 39796 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References nmsf_surface_check(), SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
Referenced by nmsf_surface_check().
nmsf_surface_check()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.nmsf_surface_check (surf)
FUNCTION nmsf_surface_check #.
:param surf
:type surf:surface
Definition at line 40962 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References nmsf_curve_check(), and SCL.Builtin.TYPEOF().
Referenced by nmsf_curve_check().
normalise()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.normalise (arg)
FUNCTION normalise #.
:param arg
:type arg:vector_or_direction
Definition at line 40913 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.EXISTS(), SQRT, and SCL.Builtin.TYPEOF().
Referenced by base_axis(), build_axes(), geoff_geometry::CLine.CLine(), cross_product(), dot_product(), first_proj_axis(), geoff_geometry::Plane.Plane(), scalar_times_vector(), second_proj_axis(), and vector_difference().
open_shell_reversed()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.open_shell_reversed (a_shell)
FUNCTION open_shell_reversed #.
:param a_shell
:type a_shell:open_shell
Definition at line 40827 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.TYPEOF().
Referenced by shell_reversed().
orthogonal_complement()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.orthogonal_complement (vec)
FUNCTION orthogonal_complement #.
:param vec
:type vec:direction
Definition at line 40142 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.EXISTS().
Referenced by base_axis(), and build_2axes().
path_head_to_tail()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.path_head_to_tail (a_path)
FUNCTION path_head_to_tail #.
:param a_path
:type a_path:path
Definition at line 41080 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.path.wr1().
path_reversed()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.path_reversed (a_path)
FUNCTION path_reversed #.
:param a_path
:type a_path:path
Definition at line 41093 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References list_of_topology_reversed(), and SCL.Builtin.TYPEOF().
Referenced by topology_reversed().
scalar_times_vector()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.scalar_times_vector (scalar, vec)
FUNCTION scalar_times_vector #.
:param scalar
:type scalar:REAL
:param vec
:type vec:vector_or_direction
Definition at line 40707 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.EXISTS(), normalise(), SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
Referenced by first_proj_axis(), and second_proj_axis().
second_proj_axis()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.second_proj_axis (z_axis, x_axis, arg)
FUNCTION second_proj_axis #.
:param z_axis
:type z_axis:direction
:param x_axis
:type x_axis:direction
:param arg
:type arg:direction
Definition at line 40218 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References dot_product(), SCL.Builtin.EXISTS(), normalise(), scalar_times_vector(), and vector_difference().
Referenced by base_axis().
set_of_topology_reversed()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.set_of_topology_reversed (a_set)
FUNCTION set_of_topology_reversed #.
:param a_set
:type a_set:set_of_reversible_topology_item
Definition at line 40622 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF(), and topology_reversed().
Referenced by face_reversed(), and topology_reversed().
shell_reversed()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.shell_reversed (a_shell)
FUNCTION shell_reversed #.
:param a_shell
:type a_shell:shell
Definition at line 40028 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References closed_shell_reversed(), open_shell_reversed(), and SCL.Builtin.TYPEOF().
Referenced by topology_reversed().
surface_condition_correlation()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_condition_correlation (pd, rep)
FUNCTION surface_condition_correlation #.
:param pd
:type pd:property_definition
:param rep
:type rep:representation
Definition at line 40801 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
surface_weights_positive()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_weights_positive (b)
FUNCTION surface_weights_positive #.
:param b
:type b:rational_b_spline_surface
Definition at line 40272 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.rational_b_spline_surface.wr2().
topology_reversed()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.topology_reversed (an_item)
FUNCTION topology_reversed #.
:param an_item
:type an_item:reversible_topology
Definition at line 40044 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References edge_reversed(), face_bound_reversed(), face_reversed(), list_of_topology_reversed(), path_reversed(), set_of_topology_reversed(), shell_reversed(), and SCL.Builtin.TYPEOF().
Referenced by conditional_reverse(), list_of_topology_reversed(), and set_of_topology_reversed().
type_check_function()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.type_check_function (the_type, sub_names, criterion)
FUNCTION type_check_function #.
:param the_type
:type the_type:(null)
:param sub_names
:type sub_names:(null)
:param criterion
:type criterion:INTEGER
Definition at line 41037 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.EXISTS(), SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
using_items()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.using_items (item, checked_items)
FUNCTION using_items #.
:param item
:type item:founded_item_select
:param checked_items
:type checked_items:(null)
Definition at line 40523 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.HIINDEX(), and SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.founded_item.users(), using_representations(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_general_pocket.wr2(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_general_protrusion.wr2().
using_representations()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.using_representations (item)
FUNCTION using_representations #.
:param item
:type item:founded_item_select
Definition at line 41295 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.HIINDEX(), SCL.Builtin.SIZEOF(), SCL.Builtin.USEDIN(), and using_items().
Referenced by acyclic_mapped_representation(), dimension_of(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation_item.wr1(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.item_identified_representation_usage.wr1().
valid_basis_curve_in_2d_wireframe()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.valid_basis_curve_in_2d_wireframe (crv)
FUNCTION valid_basis_curve_in_2d_wireframe #.
:param crv
:type crv:curve
Definition at line 40542 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
valid_calendar_date()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.valid_calendar_date (date)
FUNCTION valid_calendar_date #.
:param date
:type date:calendar_date
Definition at line 40448 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References leap_year().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.calendar_date.wr1().
valid_datum_target_parameters()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.valid_datum_target_parameters (pdf)
FUNCTION valid_datum_target_parameters #.
:param pdf
:type pdf:placed_datum_target_feature
Definition at line 41362 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.HIINDEX(), and SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.placed_datum_target_feature.wr3().
valid_geometrically_bounded_wf_curve()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.valid_geometrically_bounded_wf_curve (crv)
FUNCTION valid_geometrically_bounded_wf_curve #.
:param crv
:type crv:curve
Definition at line 41680 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
Referenced by valid_geometrically_bounded_wf_point().
valid_geometrically_bounded_wf_point()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.valid_geometrically_bounded_wf_point (pnt)
FUNCTION valid_geometrically_bounded_wf_point #.
:param pnt
:type pnt:point
Definition at line 41062 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.TYPEOF(), and valid_geometrically_bounded_wf_curve().
valid_measure_value()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.valid_measure_value (m)
FUNCTION valid_measure_value #.
:param m
:type m:measure_value
Definition at line 39839 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.TYPEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.uncertainty_measure_with_unit.wr1().
valid_selected_instance_representation()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.valid_selected_instance_representation (pd)
FUNCTION valid_selected_instance_representation #.
:param pd
:type pd:product_definition_or_assembly_relationship
Definition at line 41541 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
valid_time()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.valid_time (time)
FUNCTION valid_time #.
:param time
:type time:local_time
Definition at line 41617 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.EXISTS().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.local_time.wr1().
valid_units()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.valid_units (m)
FUNCTION valid_units #.
:param m
:type m:measure_with_unit
Definition at line 41426 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References derive_dimensional_exponents(), and SCL.Builtin.TYPEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.measure_with_unit.wr1().
valid_wireframe_edge_curve()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.valid_wireframe_edge_curve (crv)
FUNCTION valid_wireframe_edge_curve #.
:param crv
:type crv:curve
Definition at line 40254 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF(), and SCL.Builtin.TYPEOF().
valid_wireframe_vertex_point()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.valid_wireframe_vertex_point (pnt)
FUNCTION valid_wireframe_vertex_point #.
:param pnt
:type pnt:point
Definition at line 40487 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.TYPEOF().
validate_countersink_radii()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.validate_countersink_radii (cskhole)
FUNCTION validate_countersink_radii #.
:param cskhole
:type cskhole:solid_with_stepped_round_hole_and_conical_transitions
Definition at line 39697 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_stepped_round_hole_and_conical_transitions.wr3().
value_range_aggregate_rep_item()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.value_range_aggregate_rep_item (agg)
FUNCTION value_range_aggregate_rep_item #.
:param agg
:type agg:(null)
Definition at line 41234 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
value_range_wr1()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.value_range_wr1 (agg)
FUNCTION value_range_wr1 #.
:param agg
:type agg:compound_item_definition
Definition at line 40360 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.value_range.wr1().
value_range_wr2()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.value_range_wr2 (agg)
FUNCTION value_range_wr2 #.
:param agg
:type agg:compound_item_definition
Definition at line 40408 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.value_range.wr2().
value_range_wr3()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.value_range_wr3 (agg)
FUNCTION value_range_wr3 #.
:param agg
:type agg:compound_item_definition
Definition at line 40374 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.value_range.wr3().
vector_difference()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.vector_difference (arg1, arg2)
FUNCTION vector_difference #.
:param arg1
:type arg1:vector_or_direction
:param arg2
:type arg2:vector_or_direction
Definition at line 40287 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.EXISTS(), normalise(), SCL.Builtin.SIZEOF(), SQRT, and SCL.Builtin.TYPEOF().
Referenced by first_proj_axis(), and second_proj_axis().
Variable Documentation
action_items
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.action_items
Initial value:
 =  SELECT(
         'action_directive',
         'certification_item',
         'characterized_object',
         'classification_item',
         'configuration_effectivity',
         'document_reference_item',
         'identification_item',
         'organization',
         'person_and_organization',
         'product_definition',
         'product_definition_formation',
         'product_definition_formation_relationship',
         'product_definition_relationship',
         'requirement_assigned_item',
         scope = schema_scope)
Definition at line 935 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
action_method_items
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.action_method_items
Initial value:
 =  SELECT(
         'product',
         'product_definition_formation',
         scope = schema_scope)
Definition at line 1931 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
action_request_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.action_request_item
Initial value:
 =  SELECT(
         'product_definition',
         'product_definition_formation',
         'product_definition_formation_relationship',
         'product_definition_relationship',
         'property_definition',
         'versioned_action_request',
         scope = schema_scope)
Definition at line 145 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
alternative_solution_requires_solution_definition
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.alternative_solution_requires_solution_definition = Rule()
RULE alternative_solution_requires_solution_definition #.
Definition at line 41802 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
angle_direction_reference_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.angle_direction_reference_select
Initial value:
 =  SELECT(
         'direction',
         'curve',
         'point_path',
         scope = schema_scope)
Definition at line 375 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.angle_direction_reference.representation_item_relationship_related_representation_item().
angle_direction_reference_with_a2p3d_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.angle_direction_reference_with_a2p3d_select
Initial value:
 =  SELECT(
         'angle_direction_reference_select',
         'axis2_placement_3d',
         scope = schema_scope)
Definition at line 369 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.transformation_with_derived_angle.item_defined_transformation_transform_item_1().
annotation_plane_element
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.annotation_plane_element
Initial value:
 =  SELECT(
         'draughting_callout',
         'styled_item',
         scope = schema_scope)
Definition at line 2013 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
annotation_representation_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.annotation_representation_select
Initial value:
 =  SELECT(
         'presentation_area',
         'presentation_view',
         'symbol_representation',
         scope = schema_scope)
Definition at line 674 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
annotation_symbol_occurrence_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.annotation_symbol_occurrence_item
Initial value:
 =  SELECT(
         'annotation_symbol',
         'defined_symbol',
         scope = schema_scope)
Definition at line 423 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.annotation_symbol_occurrence.styled_item_item().
annotation_text_occurrence_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.annotation_text_occurrence_item
Initial value:
 =  SELECT(
         'text_literal',
         'annotation_text',
         'annotation_text_character',
         'composite_text',
         scope = schema_scope)
Definition at line 1830 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.annotation_text_occurrence.styled_item_item().
application_protocol_definition_required
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.application_protocol_definition_required = Rule()
RULE application_protocol_definition_required #.
Definition at line 41822 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
approval_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.approval_item
Definition at line 1177 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
approved_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.approved_item
Initial value:
 =  SELECT(
         'certification',
         'change',
         'change_request',
         'configuration_effectivity',
         'configuration_item',
         'contract',
         'product',
         'security_classification',
         'start_request',
         'start_work',
         scope = schema_scope)
Definition at line 1995 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
area_or_view
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.area_or_view
Initial value:
 =  SELECT(
         'presentation_area',
         'presentation_view',
         scope = schema_scope)
Definition at line 1048 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.background_colour.presentation().
attribute_classification_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.attribute_classification_item
Definition at line 1480 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
attribute_language_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.attribute_language_item
Definition at line 55 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
attribute_type
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.attribute_type
Initial value:
 =  SELECT(
         'label',
         'text',
         scope = schema_scope)
Definition at line 713 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.attribute_value_assignment.attribute_value().
axis2_placement
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.axis2_placement
Initial value:
 =  SELECT(
         'axis2_placement_2d',
         'axis2_placement_3d',
         scope = schema_scope)
Definition at line 299 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.annotation_text_character.mapped_item_mapping_target(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.annotation_text.mapped_item_mapping_target(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.text_style_with_mirror.mirror_placement(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.text_literal.placement(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.planar_box.placement(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.symbol_target.placement(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conic.position(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.symbol_representation_map.representation_map_mapping_origin().
base_solid_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.base_solid_select
Initial value:
 =  SELECT(
         'solid_model',
         'csg_primitive',
         'boolean_result',
         scope = schema_scope)
Definition at line 1252 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.modified_solid.base_solid().
blend_end_condition_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.blend_end_condition_select
Initial value:
 =  SELECT(
         'point_on_curve',
         'edge_curve',
         'vertex',
         scope = schema_scope)
Definition at line 154 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
boolean_operand
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.boolean_operand
Initial value:
 =  SELECT(
         'solid_model',
         'half_space_solid',
         'csg_primitive',
         'boolean_result',
         scope = schema_scope)
Definition at line 1325 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.boolean_result.first_operand(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.boolean_result.second_operand().
box_characteristic_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.box_characteristic_select
Initial value:
 =  SELECT(
         'box_height',
         'box_width',
         'box_slant_angle',
         'box_rotate_angle',
         scope = schema_scope)
Definition at line 1907 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
breakdown_element_requires_product_definition
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.breakdown_element_requires_product_definition = Rule()
RULE breakdown_element_requires_product_definition #.
Definition at line 41842 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
camera_model_d3_multi_clipping_interection_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.camera_model_d3_multi_clipping_interection_select
Initial value:
 =  SELECT(
         'camera_model_d3_multi_clipping_union',
         'plane',
         scope = schema_scope)
Definition at line 1395 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
camera_model_d3_multi_clipping_union_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.camera_model_d3_multi_clipping_union_select
Initial value:
 =  SELECT(
         'camera_model_d3_multi_clipping_intersection',
         'plane',
         scope = schema_scope)
Definition at line 1076 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
category_usage_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.category_usage_item
Initial value:
 =  SELECT(
         'product_class',
         scope = schema_scope)
Definition at line 1248 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
cc_classified_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.cc_classified_item
Initial value:
 =  SELECT(
         'assembly_component_usage',
         'product_definition_formation',
         scope = schema_scope)
Definition at line 1210 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
cc_person_organization_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.cc_person_organization_item
Initial value:
 =  SELECT(
         'change',
         'change_request',
         'configuration_item',
         'contract',
         'product',
         'product_definition',
         'product_definition_formation',
         'security_classification',
         'start_request',
         'start_work',
         scope = schema_scope)
Definition at line 723 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
cc_specified_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.cc_specified_item
Initial value:
 =  SELECT(
         'product_definition',
         'shape_aspect',
         scope = schema_scope)
Definition at line 644 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
certification_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.certification_item
Initial value:
 =  SELECT(
         'alternate_product_relationship',
         'make_from_usage_option',
         'product_definition_formation',
         'product_definition_formation_relationship',
         scope = schema_scope)
Definition at line 1919 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
certified_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.certified_item
Initial value:
 =  SELECT(
         'supplied_part_relationship',
         scope = schema_scope)
Definition at line 1332 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
change_request_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.change_request_item
Initial value:
 =  SELECT(
         'product_definition_formation',
         scope = schema_scope)
Definition at line 126 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
character_spacing_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.character_spacing_select
Initial value:
 =  SELECT(
         'length_measure',
         'ratio_measure',
         'measure_with_unit',
         'descriptive_measure',
         scope = schema_scope)
Definition at line 1654 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.text_style_with_spacing.character_spacing().
character_style_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.character_style_select
Initial value:
 =  SELECT(
         'character_glyph_style_stroke',
         'character_glyph_style_outline',
         'text_style_for_defined_font',
         scope = schema_scope)
Definition at line 411 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.text_style.character_appearance().
characterized_action_definition
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.characterized_action_definition
Initial value:
 =  SELECT(
         'action',
         'action_method',
         'action_method_relationship',
         'action_relationship',
         scope = schema_scope)
Definition at line 1619 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.action_property.definition().
characterized_definition
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.characterized_definition
Definition at line 19 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.property_definition.definition().
characterized_material_property
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.characterized_material_property
Initial value:
 =  SELECT(
         'material_property_representation',
         'product_material_composition_relationship',
         scope = schema_scope)
Definition at line 1766 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.material_designation_characterization.property().
characterized_product_composition_value
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.characterized_product_composition_value
Initial value:
 =  SELECT(
         'measure_with_unit',
         scope = schema_scope)
Definition at line 795 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
characterized_product_definition
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.characterized_product_definition
Initial value:
 =  SELECT(
         'product_definition',
         'product_definition_relationship',
         scope = schema_scope)
Definition at line 279 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
class_usage_effectivity_context_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.class_usage_effectivity_context_item
Initial value:
 =  SELECT(
         'product_definition',
         scope = schema_scope)
Definition at line 2062 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
classification_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.classification_item
Definition at line 180 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
classified_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.classified_item
Initial value:
 =  SELECT(
         'product',
         'product_definition',
         'product_definition_formation',
         scope = schema_scope)
Definition at line 1007 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
compatible_dimension
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.compatible_dimension = Rule()
RULE compatible_dimension #.
Definition at line 41782 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
component_class_for_assembly_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.component_class_for_assembly_select = Rule()
RULE component_class_for_assembly_select #.
Definition at line 41852 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
compound_item_definition
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.compound_item_definition
Initial value:
 =  SELECT(
         'list_representation_item',
         'set_representation_item',
         scope = schema_scope)
Definition at line 468 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.compound_representation_item.item_element().
configuration_design_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.configuration_design_item
Initial value:
 =  SELECT(
         'product_definition',
         'product_definition_formation',
         scope = schema_scope)
Definition at line 2057 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.configuration_design.design().
configured_effectivity_context_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.configured_effectivity_context_item
Initial value:
 =  SELECT(
         'product_concept_feature_association',
         scope = schema_scope)
Definition at line 130 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
configured_effectivity_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.configured_effectivity_item
Initial value:
 =  SELECT(
         'product_definition',
         scope = schema_scope)
Definition at line 1133 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
consistent_uncertainty
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.consistent_uncertainty = Rule()
RULE consistent_uncertainty #.
Definition at line 41832 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
constraint_definition_requires_constraint_category
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.constraint_definition_requires_constraint_category = Rule()
RULE constraint_definition_requires_constraint_category #.
Definition at line 41887 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
constructive_geometry_representation_or_shape_represenation
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.constructive_geometry_representation_or_shape_represenation
Initial value:
 =  SELECT(
         'constructive_geometry_representation',
         'shape_representation',
         scope = schema_scope)
Definition at line 1400 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.constructive_geometry_representation_relationship.representation_relationship_rep_1().
contract_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.contract_item
Initial value:
 =  SELECT(
         'action_directive',
         'alternate_product_relationship',
         'directed_action',
         'executed_action',
         'information_usage_right',
         'organization',
         'person_and_organization',
         'product',
         'product_definition_formation',
         scope = schema_scope)
Definition at line 1121 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
contracted_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.contracted_item
Initial value:
 =  SELECT(
         'product_definition_formation',
         scope = schema_scope)
Definition at line 1592 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
csg_primitive
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.csg_primitive
Initial value:
 =  SELECT(
         'sphere',
         'block',
         'right_angular_wedge',
         'torus',
         'right_circular_cone',
         'right_circular_cylinder',
         scope = schema_scope)
Definition at line 1376 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
csg_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.csg_select
Initial value:
 =  SELECT(
         'boolean_result',
         'csg_primitive',
         scope = schema_scope)
Definition at line 669 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.csg_solid.tree_root_expression().
curve_font_or_scaled_curve_font_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.curve_font_or_scaled_curve_font_select
Initial value:
 =  SELECT(
         'curve_style_font_select',
         'curve_style_font_and_scaling',
         scope = schema_scope)
Definition at line 269 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.curve_style.curve_font().
curve_on_surface
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.curve_on_surface
Initial value:
 =  SELECT(
         'pcurve',
         'surface_curve',
         'composite_curve_on_surface',
         scope = schema_scope)
Definition at line 1469 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
curve_or_annotation_curve_occurrence
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.curve_or_annotation_curve_occurrence
Initial value:
 =  SELECT(
         'curve',
         'annotation_curve_occurrence',
         scope = schema_scope)
Definition at line 1341 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_tile_coloured_region.closed_curve().
curve_or_render
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.curve_or_render
Initial value:
 =  SELECT(
         'curve_style',
         'curve_style_rendering',
         scope = schema_scope)
Definition at line 1733 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_boundary.style_of_boundary(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_control_grid.style_of_control_grid(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_parameter_line.style_of_parameter_lines(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_segmentation_curve.style_of_segmentation_curve(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_silhouette.style_of_silhouette().
curve_style_font_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.curve_style_font_select
Initial value:
 =  SELECT(
         'curve_style_font',
         'pre_defined_curve_font',
         'externally_defined_curve_font',
         scope = schema_scope)
Definition at line 1566 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.curve_style_font_and_scaling.curve_font().
date_and_time_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.date_and_time_item
Initial value:
 =  SELECT(
         'action',
         'action_directive',
         'applied_action_assignment',
         'applied_organization_assignment',
         'applied_person_and_organization_assignment',
         'applied_security_classification_assignment',
         'approval_person_organization',
         'certification',
         'contract',
         'directed_action',
         'document',
         'document_file',
         'event_occurrence',
         'executed_action',
         'information_usage_right',
         'organizational_project',
         'product_definition',
         'product_definition_formation',
         'product_definition_relationship',
         'rule_action',
         'security_classification',
         'versioned_action_request',
         scope = schema_scope)
Definition at line 573 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
date_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.date_item
Initial value:
 =  SELECT(
         'action',
         'action_directive',
         'applied_action_assignment',
         'applied_organization_assignment',
         'applied_person_and_organization_assignment',
         'applied_security_classification_assignment',
         'approval_person_organization',
         'certification',
         'contract',
         'directed_action',
         'document',
         'document_file',
         'event_occurrence',
         'executed_action',
         'information_usage_right',
         'organizational_project',
         'product_definition',
         'product_definition_formation',
         'product_definition_relationship',
         'security_classification',
         'versioned_action_request',
         scope = schema_scope)
Definition at line 1771 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
date_time_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.date_time_item
Initial value:
 =  SELECT(
         'approval_person_organization',
         'certification',
         'change',
         'change_request',
         'contract',
         'product_definition',
         'security_classification',
         'start_request',
         'start_work',
         scope = schema_scope)
Definition at line 1278 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
date_time_or_event_occurrence
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.date_time_or_event_occurrence
Initial value:
 =  SELECT(
         'date_time_select',
         'event_occurrence',
         scope = schema_scope)
Definition at line 1137 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dated_effectivity.effectivity_end_date(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dated_effectivity.effectivity_start_date(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.time_interval_with_bounds.primary_bound(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.time_interval_with_bounds.secondary_bound().
date_time_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.date_time_select
Initial value:
 =  SELECT(
         'date',
         'date_and_time',
         'local_time',
         scope = schema_scope)
Definition at line 1346 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.approval_date_time.date_time().
defined_symbol_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.defined_symbol_select
Initial value:
 =  SELECT(
         'pre_defined_symbol',
         'externally_defined_symbol',
         scope = schema_scope)
Definition at line 1258 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.defined_symbol.definition().
derived_property_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.derived_property_select
Initial value:
 =  SELECT(
         'property_definition',
         'action_property',
         scope = schema_scope)
Definition at line 1142 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.general_property_association.derived_definition().
description_attribute_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.description_attribute_select
Initial value:
 =  SELECT(
         'action_request_solution',
         'application_context',
         'approval_role',
         'configuration_design',
         'date_role',
         'date_time_role',
         'context_dependent_shape_representation',
         'effectivity',
         'external_source',
         'organization_role',
         'person_and_organization_role',
         'person_and_organization',
         'property_definition_representation',
         'representation',
         scope = schema_scope)
Definition at line 1675 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.description_attribute.described_item().
design_constraint_requires_product_definition
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.design_constraint_requires_product_definition = Rule()
RULE design_constraint_requires_product_definition #.
Definition at line 41892 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
dimensional_characteristic
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_characteristic
Initial value:
 =  SELECT(
         'dimensional_location',
         'dimensional_size',
         scope = schema_scope)
Definition at line 952 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimensional_characteristic_representation.dimension(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.plus_minus_tolerance.toleranced_dimension().
direction_count_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.direction_count_select
Initial value:
 =  SELECT(
         'u_direction_count',
         'v_direction_count',
         scope = schema_scope)
Definition at line 2051 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
document_identifier_assigned_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.document_identifier_assigned_item
Initial value:
 =  SELECT(
         'document',
         scope = schema_scope)
Definition at line 655 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
document_reference_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.document_reference_item
Definition at line 962 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
draughting_callout_element
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_callout_element
Initial value:
 =  SELECT(
         'annotation_text_occurrence',
         'annotation_symbol_occurrence',
         'annotation_curve_occurrence',
         scope = schema_scope)
Definition at line 160 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
draughting_model_item_association_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_model_item_association_select
Initial value:
 =  SELECT(
         'annotation_occurrence',
         'draughting_callout',
         scope = schema_scope)
Definition at line 478 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_model_item_association.item_identified_representation_usage_identified_item().
draughting_model_item_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_model_item_select
Initial value:
 =  SELECT(
         'mapped_item',
         'styled_item',
         'axis2_placement',
         'camera_model',
         'draughting_callout',
         scope = schema_scope)
Definition at line 1949 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
draughting_model_items_constraint
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_model_items_constraint = Rule()
RULE draughting_model_items_constraint #.
Definition at line 41762 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
draughting_titled_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_titled_item
Initial value:
 =  SELECT(
         'drawing_revision',
         'drawing_sheet_revision',
         scope = schema_scope)
Definition at line 878 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
effectivity_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.effectivity_item
Initial value:
 =  SELECT(
         'assembly_component_usage_substitute',
         'product',
         'product_definition',
         'product_definition_formation',
         'product_definition_relationship',
         'product_definition_substitute',
         scope = schema_scope)
Definition at line 799 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
event_occurrence_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.event_occurrence_item
Initial value:
 =  SELECT(
         'organizational_project',
         scope = schema_scope)
Definition at line 512 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
external_identification_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.external_identification_item
Initial value:
 =  SELECT(
         'action_relationship',
         'action_request_status',
         'applied_organization_assignment',
         'applied_person_and_organization_assignment',
         'approval',
         'approval_status',
         'date_and_time_assignment',
         'date_assignment',
         'document_file',
         'external_source',
         'externally_defined_class',
         'externally_defined_context_dependent_unit',
         'externally_defined_conversion_based_unit',
         'externally_defined_general_property',
         'externally_defined_picture_representation_item',
         'externally_defined_representation_item',
         'organizational_address',
         'product_definition',
         'security_classification',
         'trimmed_curve',
         'versioned_action_request',
         scope = schema_scope)
Definition at line 434 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
external_version_assignments_are_valid
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.external_version_assignments_are_valid = Rule()
RULE external_version_assignments_are_valid #.
Definition at line 41817 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
fill_area_style_tile_shape_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_tile_shape_select
Initial value:
 =  SELECT(
         'fill_area_style_tile_curve_with_style',
         'fill_area_style_tile_coloured_region',
         'fill_area_style_tile_symbol_with_style',
         'pre_defined_tile',
         'externally_defined_tile',
         scope = schema_scope)
Definition at line 1147 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
fill_style_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_style_select
Initial value:
 =  SELECT(
         'fill_area_style_colour',
         'externally_defined_tile_style',
         'fill_area_style_tiles',
         'externally_defined_hatch_style',
         'fill_area_style_hatching',
         scope = schema_scope)
Definition at line 1936 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
font_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.font_select
Initial value:
 =  SELECT(
         'pre_defined_text_font',
         'externally_defined_text_font',
         'text_font',
         scope = schema_scope)
Definition at line 134 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.text_literal.font().
founded_item_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.founded_item_select
Initial value:
 =  SELECT(
         'founded_item',
         'representation_item',
         scope = schema_scope)
Definition at line 1058 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
generalized_surface_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.generalized_surface_select
Initial value:
 =  SELECT(
         'surface',
         'face_surface',
         'surfaced_open_shell',
         scope = schema_scope)
Definition at line 774 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.thickened_face_solid.base_element(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.sculptured_solid.sculpturing_element().
geometric_item_specific_usage_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_item_specific_usage_select
Initial value:
 =  SELECT(
         'shape_aspect',
         'shape_aspect_relationship',
         scope = schema_scope)
Definition at line 30 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_item_specific_usage.item_identified_representation_usage_definition().
geometric_set_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_set_select
Initial value:
 =  SELECT(
         'point',
         'curve',
         'surface',
         scope = schema_scope)
Definition at line 1220 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
groupable_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.groupable_item
Initial value:
 =  SELECT(
         'geometric_representation_item',
         'group_relationship',
         'mapped_item',
         'package_product_concept_feature',
         'product_concept_feature',
         'product_definition',
         'product_definition_formation',
         'property_definition_representation',
         'representation',
         'representation_item',
         'representation_relationship_with_transformation',
         'shape_aspect',
         'shape_aspect_relationship',
         'shape_representation_relationship',
         'styled_item',
         'topological_representation_item',
         scope = schema_scope)
Definition at line 1357 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
id_attribute_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.id_attribute_select
Initial value:
 =  SELECT(
         'action',
         'address',
         'product_category',
         'property_definition',
         'shape_aspect',
         'shape_aspect_relationship',
         'application_context',
         'group',
         'organizational_project',
         'representation',
         scope = schema_scope)
Definition at line 741 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.id_attribute.identified_item().
identification_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.identification_item
Definition at line 2018 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
instance_usage_context_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.instance_usage_context_select
Initial value:
 =  SELECT(
         'product_definition_relationship',
         'product_definition_usage',
         scope = schema_scope)
Definition at line 1857 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
invisibility_context
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.invisibility_context
Initial value:
 =  SELECT(
         'draughting_model',
         'presentation_representation',
         'presentation_set',
         scope = schema_scope)
Definition at line 428 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.context_dependent_invisibility.presentation_context().
invisible_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.invisible_item
Initial value:
 =  SELECT(
         'draughting_callout',
         'presentation_layer_assignment',
         'representation',
         'styled_item',
         scope = schema_scope)
Definition at line 767 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
ir_usage_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.ir_usage_item
Initial value:
 =  SELECT(
         'action_directive',
         'certification_item',
         'characterized_object',
         'classification_item',
         'configuration_effectivity',
         'document_reference_item',
         'identification_item',
         'organization',
         'person_and_organization',
         'product_definition',
         'product_definition_formation',
         'product_definition_formation_relationship',
         'product_definition_relationship',
         'requirement_assigned_item',
         scope = schema_scope)
Definition at line 1963 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
layered_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.layered_item
Initial value:
 =  SELECT(
         'presentation_representation',
         'representation_item',
         scope = schema_scope)
Definition at line 680 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
list_of_reversible_topology_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.list_of_reversible_topology_item = LIST(0,None,'reversible_topology_item', scope = schema_scope)
Definition at line 2055 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
list_representation_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.list_representation_item = LIST(1,None,'representation_item', scope = schema_scope)
Definition at line 648 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
marker_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.marker_select
Initial value:
 =  SELECT(
         'marker_type',
         'pre_defined_marker',
         scope = schema_scope)
Definition at line 1390 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.point_style.marker().
material_for_coating_layer
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.material_for_coating_layer = Rule()
RULE material_for_coating_layer #.
Definition at line 41952 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
measure_value
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.measure_value
Definition at line 516 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.measure_with_unit.value_component(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.value_representation_item.value_component().
mechanical_design_and_draughting_relationship_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_and_draughting_relationship_select
Initial value:
 =  SELECT(
         'draughting_model',
         'mechanical_design_geometric_presentation_representation',
         'mechanical_design_presentation_representation_with_draughting',
         'mechanical_design_shaded_presentation_representation',
         'shape_representation',
         scope = schema_scope)
Definition at line 1692 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_and_draughting_relationship.representation_relationship_rep_1(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_and_draughting_relationship.representation_relationship_rep_2().
mechanical_design_geometric_presentation_area_items
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_area_items
Initial value:
 =  SELECT(
         'axis2_placement',
         'mapped_item',
         scope = schema_scope)
Definition at line 1842 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
mechanical_design_geometric_presentation_representation_items
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.mechanical_design_geometric_presentation_representation_items
Initial value:
 =  SELECT(
         'axis2_placement',
         'camera_model_d3',
         'mapped_item',
         'styled_item',
         scope = schema_scope)
Definition at line 1013 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
multi_language_attribute_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.multi_language_attribute_item
Definition at line 808 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
name_attribute_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.name_attribute_select
Initial value:
 =  SELECT(
         'action_request_solution',
         'address',
         'configuration_design',
         'context_dependent_shape_representation',
         'derived_unit',
         'effectivity',
         'person_and_organization',
         'product_definition',
         'product_definition_substitute',
         'property_definition_representation',
         scope = schema_scope)
Definition at line 1748 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.name_attribute.named_item().
name_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.name_item
Initial value:
 =  SELECT(
         'assembly_component_usage',
         'external_class_library',
         'group',
         'group_relationship',
         'product',
         'product_definition',
         scope = schema_scope)
Definition at line 166 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.applied_name_assignment.item().
organization_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.organization_item
Initial value:
 =  SELECT(
         'action',
         'action_directive',
         'alternate_product_relationship',
         'applied_action_assignment',
         'applied_classification_assignment',
         'applied_identification_assignment',
         'applied_security_classification_assignment',
         'approval',
         'assembly_component_usage_substitute',
         'certification',
         'class_',
         'configuration_item',
         'contract',
         'document_file',
         'executed_action',
         'general_property',
         'information_usage_right',
         'organizational_project',
         'product',
         'product_definition',
         'product_definition_formation',
         'product_definition_formation_relationship',
         'property_definition',
         'rule_action',
         'security_classification',
         'shape_representation',
         'versioned_action_request',
         scope = schema_scope)
Definition at line 1415 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
orientation_basis_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.orientation_basis_select
Initial value:
 =  SELECT(
         'axis2_placement_3d',
         'min_and_major_ply_orientation_basis',
         scope = schema_scope)
Definition at line 690 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.angle_direction_reference.representation_item_relationship_relating_representation_item().
pcurve_or_surface
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.pcurve_or_surface
Initial value:
 =  SELECT(
         'pcurve',
         'surface',
         scope = schema_scope)
Definition at line 685 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
person_and_organization_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.person_and_organization_item
Initial value:
 =  SELECT(
         'action',
         'action_directive',
         'alternate_product_relationship',
         'applied_action_assignment',
         'applied_classification_assignment',
         'applied_identification_assignment',
         'applied_security_classification_assignment',
         'approval',
         'assembly_component_usage_substitute',
         'certification',
         'configuration_item',
         'contract',
         'document_file',
         'executed_action',
         'general_property',
         'information_usage_right',
         'organizational_project',
         'person_and_organization',
         'product',
         'product_definition',
         'product_definition_formation',
         'product_definition_formation_relationship',
         'property_definition',
         'rule_action',
         'security_classification',
         'shape_representation',
         'versioned_action_request',
         scope = schema_scope)
Definition at line 1877 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
person_organization_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.person_organization_select
Initial value:
 =  SELECT(
         'person',
         'organization',
         'person_and_organization',
         scope = schema_scope)
Definition at line 561 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.approval_person_organization.person_organization().
picture_representation_item_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.picture_representation_item_select
Initial value:
 =  SELECT(
         'styled_item',
         'planar_box',
         'axis2_placement_2d',
         scope = schema_scope)
Definition at line 417 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
plane_or_planar_box
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.plane_or_planar_box
Initial value:
 =  SELECT(
         'plane',
         'planar_box',
         scope = schema_scope)
Definition at line 1631 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.annotation_plane.styled_item_item().
plib_property_reference_requires_name_scope
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.plib_property_reference_requires_name_scope = Rule()
RULE plib_property_reference_requires_name_scope #.
Definition at line 41902 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
plib_property_reference_requires_version
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.plib_property_reference_requires_version = Rule()
RULE plib_property_reference_requires_version #.
Definition at line 41987 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
ply_reference
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.ply_reference = Rule()
RULE ply_reference #.
Definition at line 41837 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
ply_stock_material_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.ply_stock_material_select = Rule()
RULE ply_stock_material_select #.
Definition at line 41907 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
point_and_vector_member
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.point_and_vector_member
Initial value:
 =  SELECT(
         'point',
         'direction',
         scope = schema_scope)
Definition at line 1852 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
point_and_vector_members
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.point_and_vector_members = LIST(2,3,'point_and_vector_member', scope = schema_scope)
Definition at line 1804 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
point_path_members
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.point_path_members = LIST(1,None,'point_and_vector', scope = schema_scope)
Definition at line 1571 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
presentation_representation_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.presentation_representation_select
Initial value:
 =  SELECT(
         'presentation_representation',
         'presentation_set',
         scope = schema_scope)
Definition at line 381 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.presented_item_representation.presentation().
presentation_size_assignment_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.presentation_size_assignment_select
Initial value:
 =  SELECT(
         'presentation_view',
         'presentation_area',
         'area_in_set',
         scope = schema_scope)
Definition at line 567 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.presentation_size.unit().
presentation_style_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.presentation_style_select
Initial value:
 =  SELECT(
         'point_style',
         'curve_style',
         'surface_style_usage',
         'symbol_style',
         'fill_area_style',
         'text_style',
         'null_style',
         scope = schema_scope)
Definition at line 308 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
presented_item_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.presented_item_select
Initial value:
 =  SELECT(
         'action',
         'action_method',
         'action_relationship',
         'product_concept',
         'product_concept_feature',
         'product_concept_feature_category',
         'product_definition',
         'product_definition_formation',
         'product_definition_relationship',
         scope = schema_scope)
Definition at line 357 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
product_concept_feature_requires_category
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_concept_feature_requires_category = Rule()
RULE product_concept_feature_requires_category #.
Definition at line 41972 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
product_definition_or_assembly_relationship
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_definition_or_assembly_relationship
Initial value:
 =  SELECT(
         'assembly_component_usage',
         'product_definition',
         scope = schema_scope)
Definition at line 1081 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
product_definition_or_breakdown_element_usage
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_definition_or_breakdown_element_usage
Initial value:
 =  SELECT(
         'product_definition',
         'product_definition_usage',
         scope = schema_scope)
Definition at line 473 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
product_definition_or_product_definition_relationship
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_definition_or_product_definition_relationship
Initial value:
 =  SELECT(
         'product_definition',
         'product_definition_usage',
         scope = schema_scope)
Definition at line 1980 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
product_definition_replacement_requires_effectivity_assignment
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_definition_replacement_requires_effectivity_assignment = Rule()
RULE product_definition_replacement_requires_effectivity_assignment #.
Definition at line 41847 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
product_or_formation_or_definition
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.product_or_formation_or_definition
Initial value:
 =  SELECT(
         'product',
         'product_definition_formation',
         'product_definition',
         scope = schema_scope)
Definition at line 1458 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.document_product_association.related_product().
project_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.project_item
Initial value:
 =  SELECT(
         'executed_action',
         'product_concept',
         scope = schema_scope)
Definition at line 1862 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
rendering_properties_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.rendering_properties_select
Initial value:
 =  SELECT(
         'surface_style_reflectance_ambient',
         'surface_style_transparent',
         scope = schema_scope)
Definition at line 603 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
represented_definition
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.represented_definition
Initial value:
 =  SELECT(
         'general_property',
         'property_definition',
         'property_definition_relationship',
         'shape_aspect',
         'shape_aspect_relationship',
         scope = schema_scope)
Definition at line 496 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.item_identified_representation_usage.definition(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.property_definition_representation.definition().
requirement_assigned_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.requirement_assigned_item
Initial value:
 =  SELECT(
         'configuration_item',
         'descriptive_representation_item',
         'product',
         'product_class',
         'product_definition',
         'product_definition_formation',
         'product_definition_relationship',
         'representation',
         'shape_aspect',
         scope = schema_scope)
Definition at line 1165 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
requirement_satisfaction_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.requirement_satisfaction_item
Initial value:
 =  SELECT(
         'requirement_assigned_item',
         scope = schema_scope)
Definition at line 1666 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
requirement_source_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.requirement_source_item
Initial value:
 =  SELECT(
         'characterized_object',
         'group',
         'group_relationship',
         'product',
         'product_definition',
         'product_definition_formation',
         'product_definition_relationship',
         'shape_aspect',
         scope = schema_scope)
Definition at line 996 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
restrict_alternative_definition
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.restrict_alternative_definition = Rule()
RULE restrict_alternative_definition #.
Definition at line 41787 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
restrict_assembly_category
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.restrict_assembly_category = Rule()
RULE restrict_assembly_category #.
Definition at line 41977 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
restrict_centre_of_mass_representation
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.restrict_centre_of_mass_representation = Rule()
RULE restrict_centre_of_mass_representation #.
Definition at line 41807 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
restrict_classification_assignments
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.restrict_classification_assignments = Rule()
RULE restrict_classification_assignments #.
Definition at line 41927 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
restrict_collection_category
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.restrict_collection_category = Rule()
RULE restrict_collection_category #.
Definition at line 41982 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
restrict_concept_feature_operator
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.restrict_concept_feature_operator = Rule()
RULE restrict_concept_feature_operator #.
Definition at line 41877 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
restrict_configuration_design_for_class_breakdown_association
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.restrict_configuration_design_for_class_breakdown_association = Rule()
RULE restrict_configuration_design_for_class_breakdown_association #.
Definition at line 41857 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
restrict_configuration_design_for_design_constraint
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.restrict_configuration_design_for_design_constraint = Rule()
RULE restrict_configuration_design_for_design_constraint #.
Definition at line 41777 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
restrict_group_relationship_for_classification_hierarchy
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.restrict_group_relationship_for_classification_hierarchy = Rule()
RULE restrict_group_relationship_for_classification_hierarchy #.
Definition at line 41792 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
restrict_group_relationship_for_specification_category
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.restrict_group_relationship_for_specification_category = Rule()
RULE restrict_group_relationship_for_specification_category #.
Definition at line 41942 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
restrict_language_assignment_per_attribute
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.restrict_language_assignment_per_attribute = Rule()
RULE restrict_language_assignment_per_attribute #.
Definition at line 41932 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
restrict_part_occurrence
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.restrict_part_occurrence = Rule()
RULE restrict_part_occurrence #.
Definition at line 41882 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
restrict_part_occurrence_category
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.restrict_part_occurrence_category = Rule()
RULE restrict_part_occurrence_category #.
Definition at line 41962 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
restrict_product_definitions_for_base_element
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.restrict_product_definitions_for_base_element = Rule()
RULE restrict_product_definitions_for_base_element #.
Definition at line 41772 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
restrict_product_definitions_for_collection
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.restrict_product_definitions_for_collection = Rule()
RULE restrict_product_definitions_for_collection #.
Definition at line 41867 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
restrict_product_definitions_for_definition_usage
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.restrict_product_definitions_for_definition_usage = Rule()
RULE restrict_product_definitions_for_definition_usage #.
Definition at line 41897 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
restrict_product_definitions_for_design_constraint_association
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.restrict_product_definitions_for_design_constraint_association = Rule()
RULE restrict_product_definitions_for_design_constraint_association #.
Definition at line 41957 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
restrict_product_definitions_for_part_definition_relationship
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.restrict_product_definitions_for_part_definition_relationship = Rule()
RULE restrict_product_definitions_for_part_definition_relationship #.
Definition at line 41767 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
restrict_representation_for_surface_condition
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.restrict_representation_for_surface_condition = Rule()
RULE restrict_representation_for_surface_condition #.
Definition at line 41947 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
restrict_treatment_result
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.restrict_treatment_result = Rule()
RULE restrict_treatment_result #.
Definition at line 41872 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
reversible_topology
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.reversible_topology
Initial value:
 =  SELECT(
         'reversible_topology_item',
         'list_of_reversible_topology_item',
         'set_of_reversible_topology_item',
         scope = schema_scope)
Definition at line 1795 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
reversible_topology_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.reversible_topology_item
Initial value:
 =  SELECT(
         'edge',
         'path',
         'face',
         'face_bound',
         'closed_shell',
         'open_shell',
         scope = schema_scope)
Definition at line 284 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
role_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.role_select
Initial value:
 =  SELECT(
         'action_assignment',
         'action_request_assignment',
         'approval_assignment',
         'approval_date_time',
         'certification_assignment',
         'contract_assignment',
         'document_reference',
         'effectivity_assignment',
         'group_assignment',
         'name_assignment',
         'security_classification_assignment',
         scope = schema_scope)
Definition at line 1573 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.role_association.item_with_role().
rule_superseded_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.rule_superseded_item
Initial value:
 =  SELECT(
         'product_definition_formation',
         scope = schema_scope)
Definition at line 1072 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
schema_name
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.schema_name
Definition at line 14 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
schema_scope
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.schema_scope
Definition at line 16 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
scope
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.scope = schema_scope)
Definition at line 23 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by App::ScopedLink.setScope().
security_classification_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.security_classification_item
Initial value:
 =  SELECT(
         'assembly_component_usage',
         'document',
         'document_file',
         'make_from_usage_option',
         'product',
         'product_definition',
         'product_definition_formation',
         'product_definition_usage',
         scope = schema_scope)
Definition at line 924 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
selected_instance_usage_requires_representation
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.selected_instance_usage_requires_representation = Rule()
RULE selected_instance_usage_requires_representation #.
Definition at line 41812 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
set_of_reversible_topology_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.set_of_reversible_topology_item = SET(0,None,'reversible_topology_item', scope = schema_scope)
Definition at line 317 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
set_representation_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.set_representation_item = SET(1,None,'representation_item', scope = schema_scope)
Definition at line 373 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
shape_definition
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.shape_definition
Initial value:
 =  SELECT(
         'product_definition_shape',
         'shape_aspect',
         'shape_aspect_relationship',
         scope = schema_scope)
Definition at line 1806 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_model_item_association.item_identified_representation_usage_definition().
shell
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.shell
Initial value:
 =  SELECT(
         'vertex_shell',
         'wire_shell',
         'open_shell',
         'closed_shell',
         scope = schema_scope)
Definition at line 1295 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by Part::BRepBuilderAPI_RefineModel.Build(), collectConicEdges(), ModelRefine::FaceAdjacencySplitter.FaceAdjacencySplitter(), FC_LOG_LEVEL_INIT(), Part::ExtrusionHelper.makeDraft(), Part::TopoShape.makeShell(), ModelRefine.removeFaces(), Part::TopoShape.removeSplitter(), and PartGui::ViewProviderSplineExtension.showControlPoints().
size_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.size_select
Initial value:
 =  SELECT(
         'positive_length_measure',
         'measure_with_unit',
         'descriptive_measure',
         scope = schema_scope)
Definition at line 293 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.curve_style.curve_width(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.point_style.marker_size().
sketch_basis_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.sketch_basis_select
Initial value:
 =  SELECT(
         'curve_bounded_surface',
         'face_surface',
         scope = schema_scope)
Definition at line 650 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.positioned_sketch.sketch_basis().
solution_definition_requires_solution_category
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solution_definition_requires_solution_category = Rule()
RULE solution_definition_requires_solution_category #.
Definition at line 41862 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
source_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.source_item
Initial value:
 =  SELECT(
         'identifier',
         'message',
         scope = schema_scope)
Definition at line 1099 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.externally_defined_item.item_id(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.external_source.source_id().
start_request_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.start_request_item
Initial value:
 =  SELECT(
         'product_definition_formation',
         scope = schema_scope)
Definition at line 1239 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
stock_material_reference
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.stock_material_reference = Rule()
RULE stock_material_reference #.
Definition at line 41937 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
string_representation_item_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.string_representation_item_select
Initial value:
 =  SELECT(
         'descriptive_representation_item',
         'included_text_block',
         'structured_text_composition',
         scope = schema_scope)
Definition at line 1555 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
style_context_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.style_context_select
Initial value:
 =  SELECT(
         'group',
         'presentation_layer_assignment',
         'presentation_set',
         'representation',
         'representation_item',
         'representation_relationship',
         scope = schema_scope)
Definition at line 1063 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.presentation_style_by_context.style_context().
styled_curve
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.styled_curve = Rule()
RULE styled_curve #.
Definition at line 41912 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
subtype_exclusiveness_geometric_tolerance
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.subtype_exclusiveness_geometric_tolerance = Rule()
RULE subtype_exclusiveness_geometric_tolerance #.
Definition at line 41797 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
subtype_exclusiveness_representation_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.subtype_exclusiveness_representation_item = Rule()
RULE subtype_exclusiveness_representation_item #.
Definition at line 41917 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
subtype_mandatory_geometric_tolerance
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.subtype_mandatory_geometric_tolerance = Rule()
RULE subtype_mandatory_geometric_tolerance #.
Definition at line 41967 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
surface_side_style_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_side_style_select
Initial value:
 =  SELECT(
         'surface_side_style',
         'pre_defined_surface_side_style',
         scope = schema_scope)
Definition at line 2066 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_usage.style().
surface_style_element_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_style_element_select
Initial value:
 =  SELECT(
         'surface_style_fill_area',
         'surface_style_boundary',
         'surface_style_silhouette',
         'surface_style_segmentation_curve',
         'surface_style_control_grid',
         'surface_style_parameter_line',
         'surface_style_rendering',
         scope = schema_scope)
Definition at line 896 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
symbol_style_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.symbol_style_select
Initial value:
 =  SELECT(
         'symbol_colour',
         scope = schema_scope)
Definition at line 304 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.symbol_style.style_of_symbol().
text_font_usage
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.text_font_usage = Rule()
RULE text_font_usage #.
Definition at line 41922 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
text_or_character
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.text_or_character
Initial value:
 =  SELECT(
         'annotation_text',
         'annotation_text_character',
         'composite_text',
         'text_literal',
         scope = schema_scope)
Definition at line 386 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
text_string_representation_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.text_string_representation_item
Initial value:
 =  SELECT(
         'text_literal',
         'annotation_text',
         'annotation_text_character',
         'composite_text',
         'axis2_placement',
         scope = schema_scope)
Definition at line 504 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
thickness_laminate_table_component_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.thickness_laminate_table_component_select = Rule()
RULE thickness_laminate_table_component_select #.
Definition at line 41827 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
time_interval_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.time_interval_item
Initial value:
 =  SELECT(
         'action',
         'time_interval_based_effectivity',
         scope = schema_scope)
Definition at line 1649 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
tolerance_method_definition
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.tolerance_method_definition
Initial value:
 =  SELECT(
         'tolerance_value',
         'limits_and_fits',
         scope = schema_scope)
Definition at line 1626 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.plus_minus_tolerance.range().
transformation
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.transformation
Initial value:
 =  SELECT(
         'item_defined_transformation',
         'functionally_defined_transformation',
         scope = schema_scope)
Definition at line 1307 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by MeasureGui::DimensionLinear.DimensionLinear(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation_relationship_with_transformation.transformation_operator().
trim_condition_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.trim_condition_select
Initial value:
 =  SELECT(
         'length_measure',
         'plane_angle_measure',
         'generalized_surface_select',
         'solid_model',
         scope = schema_scope)
Definition at line 1114 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.revolved_face_solid_with_trim_conditions.first_trim_condition(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.extruded_face_solid_with_trim_conditions.first_trim_condition(), ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.revolved_face_solid_with_trim_conditions.second_trim_condition(), and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.extruded_face_solid_with_trim_conditions.second_trim_condition().
trimming_select
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.trimming_select
Initial value:
 =  SELECT(
         'cartesian_point',
         'parameter_value',
         scope = schema_scope)
Definition at line 1561 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
unit
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.unit
Initial value:
 =  SELECT(
         'derived_unit',
         'named_unit',
         scope = schema_scope)
Definition at line 1761 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Referenced by ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.measure_with_unit.unit_component().
validate_dependently_instantiable_entity_data_types
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.validate_dependently_instantiable_entity_data_types = Rule()
RULE validate_dependently_instantiable_entity_data_types #.
Definition at line 41992 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
value_qualifier
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.value_qualifier
Initial value:
 =  SELECT(
         'precision_qualifier',
         'type_qualifier',
         'uncertainty_qualifier',
         scope = schema_scope)
Definition at line 1957 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
vector_or_direction
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.vector_or_direction
Initial value:
 =  SELECT(
         'vector',
         'direction',
         scope = schema_scope)
Definition at line 1160 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
work_item
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.work_item
Initial value:
 =  SELECT(
         'product_definition_formation',
         scope = schema_scope)
Definition at line 1801 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.