FreeCAD: Data::ComplexGeoData Class Reference
Data::ComplexGeoData Class Reference abstract
#include <ComplexGeoData.h>
Classes
struct Domain
struct Facet
struct Line
Public Member Functions
ComplexGeoData ()
Constructor.
~ComplexGeoData () override=default
Destructor.
Placement control
void applyTransform (const Base::Matrix4D &rclTrf)
void applyTranslation (const Base::Vector3d &)
void applyRotation (const Base::Rotation &)
void setPlacement (const Base::Placement &rclPlacement)
Base::Placement getPlacement () const
virtual void setTransform (const Base::Matrix4D &rclTrf)=0
virtual Base::Matrix4D getTransform () const =0
Modification
virtual void transformGeometry (const Base::Matrix4D &rclMat)=0
Applies a transformation on the real geometric data type.
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from Base::Handled
Handled ()
virtual ~Handled ()
void ref () const
void unref () const
int unrefNoDelete () const
int getRefCount () const
Handled & operator= (const Handled &)
Handled (const Handled &)=delete
Handled (Handled &&)=delete
Handled & operator= (Handled &&)=delete
Sub-element management
virtual std::vector< const char * > getElementTypes () const =0
virtual unsigned long countSubElements (const char *Type) const =0
virtual Segment * getSubElement (const char *Type, unsigned long) const =0
get the sub-element by type and number
virtual Segment * getSubElementByName (const char *Name) const
get sub-element by combined name
virtual void getLinesFromSubElement (const Segment *, std::vector< Base::Vector3d > &Points, std::vector< Line > &lines) const
virtual void getFacesFromSubElement (const Segment *, std::vector< Base::Vector3d > &Points, std::vector< Base::Vector3d > &PointNormals, std::vector< Facet > &faces) const
static std::pair< std::string, unsigned long > getTypeAndIndex (const char *Name)
Getting basic geometric entities
virtual double getAccuracy () const
Get the standard accuracy to be used with getPoints, getLines or getFaces.
virtual Base::BoundBox3d getBoundBox () const =0
Get the bound box.
virtual Base::Vector3d getPointFromLineIntersection (const Base::Vector3f &base, const Base::Vector3f &dir) const
virtual void getPoints (std::vector< Base::Vector3d > &Points, std::vector< Base::Vector3d > &Normals, double Accuracy, uint16_t flags=0) const
virtual void getLines (std::vector< Base::Vector3d > &Points, std::vector< Line > &lines, double Accuracy, uint16_t flags=0) const
virtual void getFaces (std::vector< Base::Vector3d > &Points, std::vector< Facet > &faces, double Accuracy, uint16_t flags=0) const
virtual bool getCenterOfGravity (Base::Vector3d &center) const
virtual std::optional< Base::Vector3d > centerOfGravity () const
static const std::string & elementMapPrefix ()
Element name mapping
IndexedName getIndexedName (const MappedName &name, ElementIDRefs *sid=nullptr) const
MappedName getMappedName (const IndexedName &element, bool allowUnmapped=false, ElementIDRefs *sid=nullptr) const
MappedElement getElementName (const char *name, ElementIDRefs *sid=nullptr, bool copy=false) const
MappedName setElementName (const IndexedName &element, const MappedName &name, long masterTag, const ElementIDRefs *sid=nullptr, bool overwrite=false)
bool hasElementMap ()
std::vector< std::pair< MappedName, ElementIDRefs > > getElementMappedNames (const IndexedName &element, bool needUnmapped=false) const
void hashChildMaps ()
Hash the child element map postfixes to shorten element name from hierarchical maps.
bool hasChildElementMap () const
Check if there is child element map.
virtual void reTagElementMap (long tag, App::StringHasherRef hasher, const char *postfix=nullptr)
Append the Tag (if and only if it is non zero) into the element map.
long getElementHistory (const MappedName &name, MappedName *original=nullptr, std::vector< MappedName > *history=nullptr) const
void setMappedChildElements (const std::vector< Data::ElementMap::MappedChildElements > &children)
std::vector< Data::ElementMap::MappedChildElements > getMappedChildElements () const
char elementType (const Data::MappedName &) const
char elementType (const Data::IndexedName &) const
char elementType (const char *name) const
virtual ElementMapPtr resetElementMap (ElementMapPtr elementMap=ElementMapPtr())
std::vector< MappedElement > getElementMap () const
Get the entire element map.
void setElementMap (const std::vector< MappedElement > &elements)
Set the entire element map.
size_t getElementMapSize (bool flush=true) const
Get the current element map size.
virtual std::vector< IndexedName > getHigherElements (const char *name, bool silent=false) const
Return the higher level element names of the given element.
virtual std::string getElementMapVersion () const
Return the current element map version.
virtual bool checkElementMapVersion (const char *ver) const
Return true to signal element map version change.
void traceElement (const MappedName &name, TraceCallback cb) const
virtual void flushElementMap () const
static bool isElementName (const char *subName)
Check if the given sub-name only contains an element name.
Save/restore
long Tag {0}
App::StringHasherRef Hasher
String hasher for element name shortening.
std::string _persistenceName
bool _restoreFailed = false
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
void SaveDocFile (Base::Writer &writer) const override
void RestoreDocFile (Base::Reader &reader) override
unsigned int getMemSize () const override
void setPersistenceFileName (const char *name) const
virtual void beforeSave () const
bool isRestoreFailed () const
void resetRestoreFailure () const
void dumpElementMap (std::ostream &stream) const
const std::string dumpElementMap () const
Base::Vector3d transformPointToOutside (const Base::Vector3f &vec) const
from local to outside
template<typename Vec >
std::vector< Base::Vector3d > transformPointsToOutside (const std::vector< Vec > &input) const
from local to outside
Base::Vector3d transformVectorToOutside (const Base::Vector3f &vec) const
template<typename Vec >
std::vector< Base::Vector3d > transformVectorsToOutside (const std::vector< Vec > &input) const
Base::Vector3f transformPointToInside (const Base::Vector3d &vec) const
from local to inside
void restoreStream (std::istream &stream, std::size_t count)
void readElements (Base::XMLReader &reader, size_t count)
Base::Vector3d transformToOutside (const Base::Vector3f &vec) const
from local to outside
Base::Vector3f transformToInside (const Base::Vector3d &vec) const
from local to inside
ElementMapPtr elementMap (bool flush=true) const
ElementMapPtr ensureElementMap (bool flush=true)
Additional Inherited Members
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
ComplexGeoData Object
Definition at line 89 of file ComplexGeoData.h.
Constructor & Destructor Documentation
ComplexGeoData()
ComplexGeoData::ComplexGeoData () default
Constructor.
~ComplexGeoData()
Data::ComplexGeoData::~ComplexGeoData () override default
Destructor.
Member Function Documentation
applyRotation()
void ComplexGeoData::applyRotation (const Base::Rotation & rot)
Applies an additional rotation to the current transformation.
Definition at line 96 of file ComplexGeoData.cpp.
References getTransform(), Base::Rotation::getValue(), and setTransform().
applyTransform()
void ComplexGeoData::applyTransform (const Base::Matrix4D & rclTrf)
Applies an additional transformation to the current transformation.
Definition at line 84 of file ComplexGeoData.cpp.
References getTransform(), and setTransform().
applyTranslation()
void ComplexGeoData::applyTranslation (const Base::Vector3d & mov)
Applies an additional translation to the current transformation.
Definition at line 89 of file ComplexGeoData.cpp.
References getTransform(), Base::Matrix4D::move(), and setTransform().
beforeSave()
void ComplexGeoData::beforeSave () const virtual
Definition at line 694 of file ComplexGeoData.cpp.
References flushElementMap(), and Hasher.
Referenced by Part::PropertyPartShape::beforeSave().
centerOfGravity()
std::optional< Base::Vector3d > ComplexGeoData::centerOfGravity () const virtual
Definition at line 187 of file ComplexGeoData.cpp.
References getCenterOfGravity().
checkElementMapVersion()
bool ComplexGeoData::checkElementMapVersion (const char * ver) const virtual
Return true to signal element map version change.
Definition at line 209 of file ComplexGeoData.cpp.
References DraftVecUtils::equals().
Referenced by Part::PropertyPartShape::Restore().
countSubElements()
virtual unsigned long Data::ComplexGeoData::countSubElements (const char * Type) const pure virtual
Implemented in Part::TopoShape, Mesh::MeshObject, Fem::FemMesh, and Points::PointKernel.
dumpElementMap() [1/2]
const std::string ComplexGeoData::dumpElementMap () const
Debugging method to dump an entire element map in human readable form into a string
Returns
The string
Definition at line 725 of file ComplexGeoData.cpp.
dumpElementMap() [2/2]
void ComplexGeoData::dumpElementMap (std::ostream & stream) const
Debugging method to dump an entire element map in human readable form to a stream
Parameters
stream
Definition at line 716 of file ComplexGeoData.cpp.
References getElementMap().
elementMap()
ElementMapPtr ComplexGeoData::elementMap (bool flush = true) const protected
Definition at line 330 of file ComplexGeoData.cpp.
References flushElementMap().
Referenced by ensureElementMap(), FC_LOG_LEVEL_INIT(), and resetElementMap().
elementMapPrefix()
const std::string & ComplexGeoData::elementMapPrefix () static
Definition at line 198 of file ComplexGeoData.cpp.
References Data::ELEMENT_MAP_PREFIX.
Referenced by App::GeoFeature::_getElementName(), Attacher::AttachEngine::calculateAttachedPlacement(), App::LinkBaseExtension::checkGeoElementMap(), Sketcher::SketchObject::convertSubName(), FC_LOG_LEVEL_INIT(), Sketcher::SketchObject::fixExternalGeometry(), Sketcher::SketchObject::getElementName(), hasSketchMarker(), and PartDesign::SubShapeBinder::update().
elementType() [1/3]
char ComplexGeoData::elementType (const char * name) const
Definition at line 399 of file ComplexGeoData.cpp.
References dot(), elementType(), Data::MappedName::fromRawData(), getElementTypes(), Data::IndexedName::getType(), Data::isMappedElement(), and Path.Post.scripts.grbl_post::type.
elementType() [2/3]
char ComplexGeoData::elementType (const Data::IndexedName & element) const
Definition at line 374 of file ComplexGeoData.cpp.
References DraftVecUtils::equals(), getElementTypes(), Data::IndexedName::getType(), and Path.Post.scripts.grbl_post::type.
elementType() [3/3]
char ComplexGeoData::elementType (const Data::MappedName & name) const
Definition at line 358 of file ComplexGeoData.cpp.
References Data::MappedName::findTagInElementName(), getIndexedName(), and Data::MappedName::toIndexedName().
Referenced by elementType(), FC_LOG_LEVEL_INIT(), Part::Feature::getElementHistory(), and getElementSource().
ensureElementMap()
ElementMapPtr ComplexGeoData::ensureElementMap (bool flush = true) protected
Definition at line 338 of file ComplexGeoData.cpp.
References elementMap(), and resetElementMap().
Referenced by FC_LOG_LEVEL_INIT(), and readElements().
flushElementMap()
void ComplexGeoData::flushElementMap () const virtual
Flush an internal buffering for element mapping
Reimplemented in Part::TopoShape.
Definition at line 346 of file ComplexGeoData.cpp.
Referenced by beforeSave(), elementMap(), getElementMap(), getElementMappedNames(), getElementMapSize(), getIndexedName(), getMappedName(), getMemSize(), hasChildElementMap(), hashChildMaps(), and SaveDocFile().
getAccuracy()
double ComplexGeoData::getAccuracy () const virtual
Get the standard accuracy to be used with getPoints, getLines or getFaces.
Reimplemented in Part::TopoShape.
Definition at line 115 of file ComplexGeoData.cpp.
getBoundBox()
virtual Base::BoundBox3d Data::ComplexGeoData::getBoundBox () const pure virtual
Get the bound box.
Implemented in Part::TopoShape, Mesh::MeshObject, Fem::FemMesh, and Points::PointKernel.
getCenterOfGravity()
bool ComplexGeoData::getCenterOfGravity (Base::Vector3d & center) const virtual
Get the center of gravity If this method is implemented then true is returned and the center of gravity. The default implementation only returns false.
Reimplemented in Part::TopoShape, and Mesh::MeshObject.
Definition at line 181 of file ComplexGeoData.cpp.
Referenced by centerOfGravity(), and Gui::Dialog::PlacementHandler::computeCenterOfMass().
getElementHistory()
long Data::ComplexGeoData::getElementHistory (const MappedName & name, MappedName * original = nullptr, std::vector< MappedName > * history = nullptr) const inline
Definition at line 315 of file ComplexGeoData.h.
Referenced by Part::Feature::getElementHistory(), and getElementSource().
getElementMap()
std::vector< MappedElement > ComplexGeoData::getElementMap () const
Get the entire element map.
Definition at line 321 of file ComplexGeoData.cpp.
References flushElementMap().
Referenced by dumpElementMap().
getElementMappedNames()
std::vector< std::pair< MappedName, ElementIDRefs > > ComplexGeoData::getElementMappedNames (const IndexedName & element, bool needUnmapped = false) const
Get mapped element names
Parameters
element original element name with Type + Index
needUnmapped if true, return the original element name if no mapping is found
Returns
a list of mapped names of the give element along with their associated string ID references
Definition at line 294 of file ComplexGeoData.cpp.
References flushElementMap().
getElementMapSize()
size_t ComplexGeoData::getElementMapSize (bool flush = true) const
Get the current element map size.
Definition at line 214 of file ComplexGeoData.cpp.
References FC_MSG, flushElementMap(), and unit().
Referenced by Part::PropertyPartShape::afterRestore(), Part::PropertyPartShape::beforeSave(), FC_LOG_LEVEL_INIT(), Part::PropertyPartShape::Restore(), Part::PropertyPartShape::Save(), and Save().
getElementMapVersion()
std::string ComplexGeoData::getElementMapVersion () const virtual
Return the current element map version.
Definition at line 204 of file ComplexGeoData.cpp.
Referenced by Part::PropertyPartShape::Restore(), and Part::PropertyPartShape::Save().
getElementName()
Data::MappedElement ComplexGeoData::getElementName (const char * name, ElementIDRefs * sid = nullptr, bool copy = false) const
Return a pair of indexed name and mapped name
Parameters
name the input name.
sid optional output of any App::StringID involved in forming this mapped name
copy if true, copy the name string, or else use it as constant string, and caller must make sure the memory is not freed.
Returns
Returns the MappedElement which contains both the indexed and mapped name.
This function guesses whether the input name is an indexed name or mapped, and perform a lookup and return the names found. If the input name contains only alphabets and underscore followed by optional digits, it will be treated as indexed name. Or else, it will be treated as mapped name.
Definition at line 265 of file ComplexGeoData.cpp.
References dot(), getElementTypes(), getIndexedName(), getMappedName(), Data::isMappedElement(), and result.
Referenced by FC_LOG_LEVEL_INIT(), and Part::Feature::getExportElementName().
getElementTypes()
virtual std::vector<const char*> Data::ComplexGeoData::getElementTypes () const pure virtual
Sub type list List of different sub-element types its NOT a list of the sub-elements itself
Implemented in Part::TopoShape, Mesh::MeshObject, Fem::FemMesh, and Points::PointKernel.
Referenced by elementType(), getElementName(), getIndexedName(), readElements(), and restoreStream().
getFaces()
void ComplexGeoData::getFaces (std::vector< Base::Vector3d > & Points, std::vector< Facet > & faces, double Accuracy, uint16_t flags = 0) const virtual
Get faces from object with given accuracy
Reimplemented in Mesh::MeshObject, and Part::TopoShape.
Definition at line 170 of file ComplexGeoData.cpp.
getFacesFromSubElement()
void ComplexGeoData::getFacesFromSubElement (const Segment * segment, std::vector< Base::Vector3d > & Points, std::vector< Base::Vector3d > & PointNormals, std::vector< Facet > & faces) const virtual
Get faces from segment
Reimplemented in Part::TopoShape, and Mesh::MeshObject.
Definition at line 129 of file ComplexGeoData.cpp.
getHigherElements()
std::vector< IndexedName > ComplexGeoData::getHigherElements (const char * name, bool silent = false) const virtual
Return the higher level element names of the given element.
Reimplemented in Part::TopoShape.
Definition at line 670 of file ComplexGeoData.cpp.
getIndexedName()
IndexedName ComplexGeoData::getIndexedName (const MappedName & name, ElementIDRefs * sid = nullptr) const
Get element indexed name
Parameters
name the input name
sid optional output of and App::StringID involved forming this mapped name
Returns
Returns an indexed name.
Definition at line 251 of file ComplexGeoData.cpp.
References Data::MappedName::appendToBuffer(), flushElementMap(), getElementTypes(), and Path.Post.scripts.refactored_centroid_post::str.
Referenced by elementType(), Part::Feature::getElementHistory(), getElementName(), and Part::Feature::getExportElementName().
getLines()
void ComplexGeoData::getLines (std::vector< Base::Vector3d > & Points, std::vector< Line > & lines, double Accuracy, uint16_t flags = 0) const virtual
Get lines from object with given accuracy
Reimplemented in Part::TopoShape.
Definition at line 159 of file ComplexGeoData.cpp.
getLinesFromSubElement()
void ComplexGeoData::getLinesFromSubElement (const Segment * segment, std::vector< Base::Vector3d > & Points, std::vector< Line > & lines) const virtual
Get lines from segment
Reimplemented in Part::TopoShape.
Definition at line 120 of file ComplexGeoData.cpp.
getMappedChildElements()
std::vector< Data::ElementMap::MappedChildElements > ComplexGeoData::getMappedChildElements () const
Definition at line 686 of file ComplexGeoData.cpp.
getMappedName()
MappedName ComplexGeoData::getMappedName (const IndexedName & element, bool allowUnmapped = false, ElementIDRefs * sid = nullptr) const
Get element mapped name
Parameters
name the input name
allowUnmapped If the queried element is not mapped, then return an empty name if allowUnmapped is false, or else, return the indexed name.
sid optional output of and App::StringID involved forming this mapped name
Returns
Returns the mapped name.
Definition at line 229 of file ComplexGeoData.cpp.
References flushElementMap().
Referenced by FC_LOG_LEVEL_INIT(), Part::Feature::getElementHistory(), and getElementName().
getMemSize()
unsigned int ComplexGeoData::getMemSize () const override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB?
Implements Base::Persistence.
Reimplemented in Part::TopoShape, Mesh::MeshObject, Points::PointKernel, and Fem::FemMesh.
Definition at line 660 of file ComplexGeoData.cpp.
References flushElementMap().
getPlacement()
Base::Placement ComplexGeoData::getPlacement () const
Return the current transformation as placement using getTransform().
Definition at line 108 of file ComplexGeoData.cpp.
References getTransform().
Referenced by PartDesign::Boolean::execute(), Mesh::MeshObject::foraminate(), Mesh::MeshObject::nearestFacetOnRay(), Mesh::MeshObject::trimByPlane(), and PartDesign::ShapeBinder::updatedShape().
getPointFromLineIntersection()
Base::Vector3d ComplexGeoData::getPointFromLineIntersection (const Base::Vector3f & base, const Base::Vector3f & dir) const virtual
Get point from line object intersection
Definition at line 140 of file ComplexGeoData.cpp.
getPoints()
void ComplexGeoData::getPoints (std::vector< Base::Vector3d > & Points, std::vector< Base::Vector3d > & Normals, double Accuracy, uint16_t flags = 0) const virtual
Get points from object with given accuracy
Reimplemented in Part::TopoShape, Mesh::MeshObject, Points::PointKernel, and Fem::FemMesh.
Definition at line 148 of file ComplexGeoData.cpp.
getSubElement()
virtual Segment* Data::ComplexGeoData::getSubElement (const char * Type, unsigned long) const pure virtual
get the sub-element by type and number
Implemented in Mesh::MeshObject, Fem::FemMesh, Points::PointKernel, and Part::TopoShape.
Referenced by getSubElementByName().
getSubElementByName()
Data::Segment * ComplexGeoData::getSubElementByName (const char * Name) const virtual
get sub-element by combined name
Definition at line 78 of file ComplexGeoData.cpp.
References getSubElement(), getTypeAndIndex(), and Path.Post.scripts.grbl_post::type.
getTransform()
virtual Base::Matrix4D Data::ComplexGeoData::getTransform () const pure virtual
Return the current matrix This method has to be handled by the child classes. the actual placement and matrix is not part of this class.
Implemented in Part::TopoShape, Fem::FemMesh, Mesh::MeshObject, and Points::PointKernel.
Referenced by applyRotation(), applyTransform(), applyTranslation(), and getPlacement().
getTypeAndIndex()
std::pair< std::string, unsigned long > ComplexGeoData::getTypeAndIndex (const char * Name) static
Returns a generic element type and index. The determined element type isn't necessarily supported by this geometry.
Definition at line 63 of file ComplexGeoData.cpp.
References Path.Post.scripts.refactored_centroid_post::str.
Referenced by getSubElementByName().
hasChildElementMap()
bool ComplexGeoData::hasChildElementMap () const
Check if there is child element map.
Definition at line 710 of file ComplexGeoData.cpp.
References flushElementMap().
hasElementMap()
bool Data::ComplexGeoData::hasElementMap () inline
Definition at line 282 of file ComplexGeoData.h.
Referenced by Sketcher::SketchObject::buildShape(), Sketcher::SketchObject::getEdge(), and Sketcher::SketchObject::getSubObject().
hashChildMaps()
void ComplexGeoData::hashChildMaps ()
Hash the child element map postfixes to shorten element name from hierarchical maps.
Definition at line 702 of file ComplexGeoData.cpp.
References flushElementMap(), and Tag.
isElementName()
static bool Data::ComplexGeoData::isElementName (const char * subName) inline static
Check if the given sub-name only contains an element name.
Definition at line 359 of file ComplexGeoData.h.
References Data::findElementName().
isRestoreFailed()
bool Data::ComplexGeoData::isRestoreFailed () const inline
Definition at line 388 of file ComplexGeoData.h.
Referenced by Part::PropertyPartShape::afterRestore().
readElements()
void ComplexGeoData::readElements (Base::XMLReader & reader, size_t count) protected
Definition at line 523 of file ComplexGeoData.cpp.
References src.Mod.AddonManager.NetworkManager::count, ensureElementMap(), FC_ERR, getElementTypes(), Hasher, SplineSurface::i, TechDrawTools.TaskFillTemplateFields::reader, and Tag.
Referenced by Restore().
resetElementMap()
ElementMapPtr ComplexGeoData::resetElementMap (ElementMapPtr elementMap = ElementMapPtr()) virtual
Reset/swap the element map
Parameters
elementMap optional new element map
Returns
Returns the existing element map.
Reimplemented in Part::TopoShape.
Definition at line 310 of file ComplexGeoData.cpp.
References elementMap(), and Hasher.
Referenced by ensureElementMap(), FC_LOG_LEVEL_INIT(), Restore(), RestoreDocFile(), restoreStream(), and setMappedChildElements().
resetRestoreFailure()
void Data::ComplexGeoData::resetRestoreFailure () const inline
Definition at line 392 of file ComplexGeoData.h.
Restore()
void ComplexGeoData::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Reimplemented in Part::TopoShape, Mesh::MeshObject, Points::PointKernel, and Fem::FemMesh.
Definition at line 476 of file ComplexGeoData.cpp.
References src.Mod.AddonManager.NetworkManager::count, DrawingExample::file, Hasher, Base::Raw, readElements(), TechDrawTools.TaskFillTemplateFields::reader, resetElementMap(), and restoreStream().
Referenced by Part::TopoShape::Restore().
RestoreDocFile()
void ComplexGeoData::RestoreDocFile (Base::Reader &) override virtual
This method is used to restore large amounts of data from a file In this method you simply stream in your SaveDocFile() saved data. Again you have to apply for the call of this method in the Restore() call:
void PropertyMeshKernel::Restore(Base::XMLReader &reader)
{
  reader.readElement("Mesh");
  std::string file (reader.getAttribute("file") );
  if(file == "")
  {
    // read XML
    MeshCore::MeshDocXML restorer(*_pcMesh);
    restorer.Restore(reader);
  }else{
    // initiate a file read
    reader.addFile(file.c_str(),this);
 }
}
After you issued the reader.addFile() your RestoreDocFile() is called:
void PropertyMeshKernel::RestoreDocFile(Base::Reader &reader)
{
    _pcMesh->Read( reader );
}
See also
Base::Reader,Base::XMLReader
Reimplemented from Base::Persistence.
Reimplemented in Part::TopoShape, Mesh::MeshObject, Points::PointKernel, and Fem::FemMesh.
Definition at line 639 of file ComplexGeoData.cpp.
References src.Mod.AddonManager.NetworkManager::count, DraftVecUtils::equals(), FC_WARN, Hasher, TechDrawTools.TaskFillTemplateFields::reader, resetElementMap(), and restoreStream().
Referenced by Part::TopoShape::RestoreDocFile().
restoreStream()
void ComplexGeoData::restoreStream (std::istream & stream, std::size_t count) protected
Definition at line 570 of file ComplexGeoData.cpp.
References _persistenceName, _restoreFailed, src.Mod.AddonManager.NetworkManager::count, SCL.SimpleDataTypes::e, FC_ERR, FC_THROWM, getElementTypes(), Hasher, SplineSurface::i, resetElementMap(), and Tag.
Referenced by Restore(), and RestoreDocFile().
reTagElementMap()
virtual void Data::ComplexGeoData::reTagElementMap (long tag, App::StringHasherRef hasher, const char * postfix = nullptr) inline virtual
Append the Tag (if and only if it is non zero) into the element map.
Reimplemented in Part::TopoShape.
Definition at line 307 of file ComplexGeoData.h.
References Dice3DS.dom3ds::tag.
Save()
void ComplexGeoData::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Reimplemented in Part::TopoShape, Mesh::MeshObject, Points::PointKernel, and Fem::FemMesh.
Definition at line 449 of file ComplexGeoData.cpp.
References _persistenceName, Base::Writer::addFile(), Base::Writer::beginCharStream(), Base::Writer::endCharStream(), getElementMapSize(), Base::Writer::ind(), Base::Raw, and Base::Writer::Stream().
Referenced by Part::TopoShape::Save().
SaveDocFile()
void ComplexGeoData::SaveDocFile (Base::Writer &) const override virtual
This method is used to save large amounts of data to a binary file. Sometimes it makes no sense to write property data as XML. In case the amount of data is too big or the data type has a more effective way to save itself. In this cases it is possible to write the data in a separate file inside the document archive. In case you want do so you have to re-implement SaveDocFile(). First, you have to inform the framework in Save() that you want do so. Here an example from the Mesh module which can save a (pontetionaly big) triangle mesh:
void PropertyMeshKernel::Save (Base::Writer &writer) const
{
  if (writer.isForceXML())
  {
    writer << writer.ind() << "<Mesh>" << std::endl;
    MeshCore::MeshDocXML saver(*_pcMesh);
    saver.Save(writer);
  }else{
   writer << writer.ind() << "<Mesh file=\"" << writer.addFile("MeshKernel.bms", this) <<
"\"/>" << std::endl;
}
The writer.isForceXML() is an indication to force you to write XML. Regardless of size and effectiveness. The second part informs the Base::writer through writer.addFile("MeshKernel.bms", this) that this object wants to write a file with the given name. The method addFile() returns a unique name that then is written in the XML stream. This allows your RestoreDocFile() method to identify and read the file again. Later your SaveDocFile() method is called as many times as you issued the addFile() call:
 void
PropertyMeshKernel::SaveDocFile (Base::Writer &writer) const
{
    _pcMesh->Write( writer );
}
In this method you can simply stream your content to the file (Base::Writer inheriting from ostream).
Reimplemented from Base::Persistence.
Reimplemented in Part::TopoShape, Mesh::MeshObject, Points::PointKernel, and Fem::FemMesh.
Definition at line 630 of file ComplexGeoData.cpp.
References flushElementMap(), and Base::Writer::Stream().
Referenced by Part::TopoShape::SaveDocFile().
setElementMap()
void ComplexGeoData::setElementMap (const std::vector< MappedElement > & elements)
Set the entire element map.
Definition at line 349 of file ComplexGeoData.cpp.
References Tag.
setElementName()
MappedName Data::ComplexGeoData::setElementName (const IndexedName & element, const MappedName & name, long masterTag, const ElementIDRefs * sid = nullptr, bool overwrite = false) inline
Add a sub-element name mapping.
Parameters
element the original Type + Index element name
name the mapped sub-element name. May or may not start with elementMapPrefix().
sid in case you use a hasher to hash the element name, pass in the string id reference using this parameter. You can have more than one string id associated with the same name.
overwrite if true, it will overwrite existing names
Returns
Returns the stored mapped element name.
An element can have multiple mapped names. However, a name can only be mapped to one element
Note: the original proc was in the context of ComplexGeoData, which provided Tag access, now you must pass in long masterTag explicitly.
Definition at line 273 of file ComplexGeoData.h.
Referenced by Sketcher::SketchObject::buildShape(), Sketcher::SketchObject::getEdge(), and Sketcher::SketchObject::getSubObject().
setMappedChildElements()
void ComplexGeoData::setMappedChildElements (const std::vector< Data::ElementMap::MappedChildElements > & children)
Definition at line 675 of file ComplexGeoData.cpp.
References resetElementMap(), and Tag.
Referenced by FC_LOG_LEVEL_INIT().
setPersistenceFileName()
void ComplexGeoData::setPersistenceFileName (const char * name) const
Definition at line 441 of file ComplexGeoData.cpp.
References _persistenceName.
Referenced by Part::PropertyPartShape::Restore(), and Part::PropertyPartShape::Save().
setPlacement()
void ComplexGeoData::setPlacement (const Base::Placement & rclPlacement)
Override the current transformation with a placement using the setTransform() method.
Definition at line 103 of file ComplexGeoData.cpp.
References setTransform(), and Base::Placement::toMatrix().
Referenced by PartDesign::ShapeBinder::buildShapeFromReferences(), PartDesign::Boolean::execute(), PartDesign::DressUp::getAddSubShape(), getLocatedShape(), TechDraw::ShapeExtractor::getLocatedShape(), TechDraw::ShapeExtractor::getLocation3dFromFeat(), Part::Datum::getShape(), and PartDesign::ShapeBinder::updatedShape().
setTransform()
virtual void Data::ComplexGeoData::setTransform (const Base::Matrix4D & rclTrf) pure virtual
Override the current transformation with the new one. This method has to be handled by the child classes. the actual placement and matrix is not part of this class.
Implemented in Part::TopoShape, Fem::FemMesh, Mesh::MeshObject, and Points::PointKernel.
Referenced by applyRotation(), applyTransform(), applyTranslation(), and setPlacement().
traceElement()
void Data::ComplexGeoData::traceElement (const MappedName & name, TraceCallback cb) const inline
Iterate through the history of the give element name with a given callback
Parameters
name the input element name
cb trace callback with call signature.
See also
TraceCallback
Definition at line 370 of file ComplexGeoData.h.
Referenced by FC_LOG_LEVEL_INIT().
transformGeometry()
virtual void Data::ComplexGeoData::transformGeometry (const Base::Matrix4D & rclMat) pure virtual
Applies a transformation on the real geometric data type.
Implemented in Part::TopoShape, Fem::FemMesh, Points::PointKernel, and Mesh::MeshObject.
transformPointsToOutside()
template<typename Vec > std::vector<Base::Vector3d> Data::ComplexGeoData::transformPointsToOutside (const std::vector< Vec > & input) const inline protected
from local to outside
Definition at line 421 of file ComplexGeoData.h.
References SurfaceTests.TestBlendCurve::vec.
Referenced by Fem::FemMesh::getPoints(), and Mesh::MeshObject::getPoints().
transformPointToInside()
Base::Vector3f Data::ComplexGeoData::transformPointToInside (const Base::Vector3d & vec) const inline protected
from local to inside
Definition at line 466 of file ComplexGeoData.h.
References Base::Matrix4D::inverse(), SurfaceTests.TestBlendCurve::vec, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by Mesh::MeshObject::movePoint(), and Mesh::MeshObject::setPoint().
transformPointToOutside()
Base::Vector3d Data::ComplexGeoData::transformPointToOutside (const Base::Vector3f & vec) const inline protected
from local to outside
Definition at line 411 of file ComplexGeoData.h.
References SurfaceTests.TestBlendCurve::vec.
Referenced by Mesh::MeshObject::getBoundBox(), and Mesh::MeshObject::getCenterOfGravity().
transformToInside()
Base::Vector3f Data::ComplexGeoData::transformToInside (const Base::Vector3d & vec) const inline protected
from local to inside
Definition at line 496 of file ComplexGeoData.h.
References Base::Matrix4D::inverse(), SurfaceTests.TestBlendCurve::vec, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
transformToOutside()
Base::Vector3d Data::ComplexGeoData::transformToOutside (const Base::Vector3f & vec) const inline protected
from local to outside
Definition at line 487 of file ComplexGeoData.h.
References SurfaceTests.TestBlendCurve::vec.
transformVectorsToOutside()
template<typename Vec > std::vector<Base::Vector3d> Data::ComplexGeoData::transformVectorsToOutside (const std::vector< Vec > & input) const inline protected
Definition at line 448 of file ComplexGeoData.h.
References Base::Matrix4D::setCol(), and SurfaceTests.TestBlendCurve::vec.
Referenced by Mesh::MeshObject::getPointNormals(), and Mesh::MeshObject::getPoints().
transformVectorToOutside()
Base::Vector3d Data::ComplexGeoData::transformVectorToOutside (const Base::Vector3f & vec) const inline protected
Definition at line 437 of file ComplexGeoData.h.
References Base::Matrix4D::setCol(), and SurfaceTests.TestBlendCurve::vec.
Referenced by Mesh::MeshObject::getPointNormal().
Member Data Documentation
_persistenceName
std::string Data::ComplexGeoData::_persistenceName mutable protected
Definition at line 514 of file ComplexGeoData.h.
Referenced by restoreStream(), Save(), and setPersistenceFileName().
_restoreFailed
bool Data::ComplexGeoData::_restoreFailed = false mutable protected
Definition at line 515 of file ComplexGeoData.h.
Referenced by restoreStream().
Hasher
App::StringHasherRef Data::ComplexGeoData::Hasher mutable
String hasher for element name shortening.
Definition at line 480 of file ComplexGeoData.h.
Referenced by _getTopoShape(), Part::PropertyPartShape::afterRestore(), Part::PropertyPartShape::beforeSave(), beforeSave(), Part::Extrusion::extrudeShape(), FC_LOG_LEVEL_INIT(), getElementSource(), PartDesign::ProfileBased::getTopoShapeVerifiedFace(), readElements(), resetElementMap(), Part::PropertyPartShape::Restore(), Restore(), RestoreDocFile(), restoreStream(), Part::PropertyPartShape::Save(), and Part::TopoShape::TopoShape().
Tag
long Data::ComplexGeoData::Tag {0} mutable
Definition at line 477 of file ComplexGeoData.h.
Referenced by _getTopoShape(), PartDesign::FeatureExtrude::buildExtrusion(), PartDesign::FeaturePrimitive::execute(), FC_LOG_LEVEL_INIT(), PartDesign::Revolution::generateRevolution(), PartDesign::ProfileBased::getProfileShape(), Part::PropertyPartShape::getShape(), Sketcher::SketchObject::getSubObject(), hashChildMaps(), Part::ExtrusionHelper::makeElementDraft(), Part::TopoShape::makeTransform(), readElements(), restoreStream(), setElementMap(), setMappedChildElements(), Part::PropertyPartShape::setPyObject(), Part::PropertyPartShape::setValue(), and Part::TopoShape::TopoShape().
The documentation for this class was generated from the following files:
ComplexGeoData.h
ComplexGeoData.cpp