FreeCAD: Gui::WeakPtrT< T > Class Template Reference
Gui::WeakPtrT< T > Class Template Reference
The WeakPtrT class.
#include <DocumentObserver.h>
Public Member Functions
WeakPtrT (T *t)
~WeakPtrT ()=default
void reset ()
reset Releases the reference to the managed object. After the call *this manages no object.
bool expired () const
expired
WeakPtrT< T > & operator= (T *p)
operator = Assignment operator
T * operator* () const
operator *
T * operator-> () const
operator ->
bool operator== (const WeakPtrT< T > &p) const
operator ==
bool operator!= (const WeakPtrT< T > &p) const
operator !=
T * get () const noexcept
WeakPtrT (const WeakPtrT &)=delete
WeakPtrT & operator= (const WeakPtrT &)=delete
Detailed Description
template<class T>
class Gui::WeakPtrT< T >
The WeakPtrT class.
Definition at line 238 of file Gui/DocumentObserver.h.
Constructor & Destructor Documentation
WeakPtrT() [1/2]
template<class T > Gui::WeakPtrT< T >::WeakPtrT (T * t) inline explicit
Definition at line 241 of file Gui/DocumentObserver.h.
~WeakPtrT()
template<class T > Gui::WeakPtrT< T >::~WeakPtrT () default
WeakPtrT() [2/2]
template<class T > Gui::WeakPtrT< T >::WeakPtrT (const WeakPtrT< T > &) delete
Member Function Documentation
expired()
template<class T > bool Gui::WeakPtrT< T >::expired () const inline
expired
Returns
true if the managed object has already been deleted, false otherwise.
Definition at line 256 of file Gui/DocumentObserver.h.
get()
template<class T > T* Gui::WeakPtrT< T >::get () const inline noexcept
Get a pointer to the object or 0 if it doesn't exist any more.
Definition at line 296 of file Gui/DocumentObserver.h.
Referenced by draftguitools.gui_trackers.editTracker::move().
operator!=()
template<class T > bool Gui::WeakPtrT< T >::operator!= (const WeakPtrT< T > & p) const inline
operator !=
Returns
true if both objects are inequal, false otherwise
Definition at line 292 of file Gui/DocumentObserver.h.
operator*()
template<class T > T* Gui::WeakPtrT< T >::operator* () const inline
operator *
Returns
pointer to the view provider
Definition at line 271 of file Gui/DocumentObserver.h.
operator->()
template<class T > T* Gui::WeakPtrT< T >::operator-> () const inline
operator ->
Returns
pointer to the view provider
Definition at line 278 of file Gui/DocumentObserver.h.
operator=() [1/2]
template<class T > WeakPtrT& Gui::WeakPtrT< T >::operator= (const WeakPtrT< T > &) delete
operator=() [2/2]
template<class T > WeakPtrT<T>& Gui::WeakPtrT< T >::operator= (T * p) inline
operator = Assignment operator
Definition at line 263 of file Gui/DocumentObserver.h.
operator==()
template<class T > bool Gui::WeakPtrT< T >::operator== (const WeakPtrT< T > & p) const inline
operator ==
Returns
true if both objects are equal, false otherwise
Definition at line 285 of file Gui/DocumentObserver.h.
reset()
template<class T > void Gui::WeakPtrT< T >::reset () inline
reset Releases the reference to the managed object. After the call *this manages no object.
Definition at line 249 of file Gui/DocumentObserver.h.
Referenced by ArchVRM.Renderer::__init__(), draftguitools.gui_trackers.gridTracker::set(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testAll(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
The documentation for this class was generated from the following file:
Gui/DocumentObserver.h