FreeCAD: Gui::SelectionObserverPython Class Reference
Gui::SelectionObserverPython Class Reference
#include <SelectionObserverPython.h>
Public Member Functions
SelectionObserverPython (const Py::Object &obj, ResolveMode resolve=ResolveMode::OldStyleElement)
Constructor.
~SelectionObserverPython () override
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Static Public Member Functions
static void addObserver (const Py::Object &obj, ResolveMode resolve=ResolveMode::OldStyleElement)
static void removeObserver (const Py::Object &obj)
Detailed Description
The SelectionObserverPython class implements a mechanism to register a Python class instance implementing the required interface in order to be notified on selection changes.
Author
Werner Mayer
Definition at line 60 of file SelectionObserverPython.h.
Constructor & Destructor Documentation
SelectionObserverPython()
SelectionObserverPython::SelectionObserverPython (const Py::Object & obj, ResolveMode resolve = ResolveMode::OldStyleElement) explicit
Constructor.
Definition at line 35 of file SelectionObserverPython.cpp.
References FC_PY_SEL_OBSERVER.
Referenced by addObserver().
~SelectionObserverPython()
SelectionObserverPython::~SelectionObserverPython () override default
Member Function Documentation
addObserver()
void SelectionObserverPython::addObserver (const Py::Object & obj, ResolveMode resolve = ResolveMode::OldStyleElement) static
Definition at line 45 of file SelectionObserverPython.cpp.
References SelectionObserverPython().
Referenced by Gui::SelectionSingleton::sAddSelObserver().
removeObserver()
void SelectionObserverPython::removeObserver (const Py::Object & obj) static
Definition at line 50 of file SelectionObserverPython.cpp.
Referenced by Gui::SelectionSingleton::sRemSelObserver().
The documentation for this class was generated from the following files:
SelectionObserverPython.h
SelectionObserverPython.cpp