FreeCAD: PartDesignGui::TaskDlgFeatureParameters Class Reference
PartDesignGui::TaskDlgFeatureParameters Class Reference
A common base for sketch based, dressup and other solid parameters dialogs.
#include <TaskFeatureParameters.h>
Public Member Functions
TaskDlgFeatureParameters (PartDesignGui::ViewProvider *vp)
~TaskDlgFeatureParameters () override
bool accept () override
is called by the framework if the dialog is accepted (Ok)
bool reject () override
is called by the framework if the dialog is rejected (Cancel)
template<typename T = PartDesignGui::ViewProvider>
T * getViewObject () const
template<typename T = App::DocumentObject>
T * getObject () const
Public Member Functions inherited from Gui::TaskView::TaskDialog
TaskDialog ()
~TaskDialog () override
QWidget * addTaskBox (QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBox (const QPixmap &icon, QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBoxWithoutHeader (QWidget *widget)
void setButtonPosition (ButtonPosition p)
ButtonPosition buttonPosition () const
const std::vector< QWidget * > & getDialogContent () const
bool canClose () const
virtual QDialogButtonBox::StandardButtons getStandardButtons () const
tells the framework which buttons are wished for the dialog
virtual void modifyStandardButtons (QDialogButtonBox *)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
bool isEscapeButtonEnabled () const
void setAutoCloseOnTransactionChange (bool on)
bool isAutoCloseOnTransactionChange () const
void setAutoCloseOnDeletedDocument (bool on)
bool isAutoCloseOnDeletedDocument () const
const std::string & getDocumentName () const
void setDocumentName (const std::string &doc)
void setAutoCloseOnClosedView (bool on)
bool isAutoCloseOnClosedView () const
void associateToObject3dView (App::DocumentObject *obj)
const Gui::MDIView * getAssociatedView () const
void setAssociatedView (const Gui::MDIView *view)
virtual bool isAllowedAlterDocument () const
virtual bool isAllowedAlterView () const
virtual bool isAllowedAlterSelection () const
virtual bool needsFullSpace () const
virtual void open ()
is called by the framework when the dialog is opened
virtual void closed ()
is called by the framework when the dialog is closed
virtual void autoClosedOnTransactionChange ()
virtual void autoClosedOnDeletedDocument ()
virtual void autoClosedOnClosedView ()
virtual void clicked (int)
is called by the framework if a button is clicked which has no accept or reject role
virtual void helpRequested ()
is called by the framework if the user press the help button
void emitDestructionSignal ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from Gui::TaskView::TaskDialog
QPointer< QDialogButtonBox > buttonBox
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Detailed Description
A common base for sketch based, dressup and other solid parameters dialogs.
Definition at line 133 of file TaskFeatureParameters.h.
Constructor & Destructor Documentation
TaskDlgFeatureParameters()
TaskDlgFeatureParameters::TaskDlgFeatureParameters (PartDesignGui::ViewProvider * vp) explicit
Definition at line 82 of file TaskFeatureParameters.cpp.
~TaskDlgFeatureParameters()
TaskDlgFeatureParameters::~TaskDlgFeatureParameters () override default
Member Function Documentation
accept()
bool TaskDlgFeatureParameters::accept () override virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
Reimplemented in PartDesignGui::TaskDlgTransformedParameters, PartDesignGui::TaskDlgPipeParameters, PartDesignGui::TaskDlgLoftParameters, PartDesignGui::TaskDlgThicknessParameters, PartDesignGui::TaskDlgSketchBasedParameters, and PartDesignGui::TaskDlgFilletParameters.
Definition at line 90 of file TaskFeatureParameters.cpp.
References Gui::cmdAppDocument(), Gui::cmdAppObjectHide(), Gui::cmdGuiDocument(), Gui::Command::commitCommand(), Gui::TaskView::TaskDialog::Content, SCL.SimpleDataTypes::e, Gui::TaskView::TaskDialog::getDialogContent(), App::DocumentObject::getDocument(), App::DocumentObject::getInList(), Gui::getMainWindow(), Base::Type::getName(), getObject(), Base::Persistence::getTypeId(), Base::BaseClass::isDerivedFrom(), App::DocumentObject::isValid(), Init::param, src.Mod.AddonManager.Addon::translate, and Path.Log::warning().
Referenced by PartDesignGui::TaskDlgSketchBasedParameters::accept(), PartDesignGui::TaskDlgDressUpParameters::accept(), and PartDesignGui::TaskDlgTransformedParameters::accept().
getObject()
template<typename T = App::DocumentObject> T* PartDesignGui::TaskDlgFeatureParameters::getObject () const inline
Definition at line 154 of file TaskFeatureParameters.h.
Referenced by PartDesignGui::TaskDlgFilletParameters::accept(), PartDesignGui::TaskDlgDraftParameters::accept(), PartDesignGui::TaskDlgChamferParameters::accept(), PartDesignGui::TaskDlgThicknessParameters::accept(), PartDesignGui::TaskDlgDressUpParameters::accept(), and accept().
getViewObject()
template<typename T = PartDesignGui::ViewProvider> T* PartDesignGui::TaskDlgFeatureParameters::getViewObject () const inline
Definition at line 147 of file TaskFeatureParameters.h.
Referenced by PartDesignGui::ViewProviderHole::setEdit(), and PartDesignGui::ViewProvider::setEdit().
reject()
bool TaskDlgFeatureParameters::reject () override virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
Reimplemented in PartDesignGui::TaskDlgTransformedParameters, and PartDesignGui::TaskDlgSketchBasedParameters.
Definition at line 153 of file TaskFeatureParameters.cpp.
References Gui::Command::abortCommand(), Gui::cmdAppDocument(), Gui::cmdGuiDocument(), App::DocumentObjectWeakPtrT::expired(), PartDesign::Body::findBodyOf(), Gui::TaskView::TaskDialog::getDialogContent(), App::PropertyLink::getValue(), Gui::Application::getViewProvider(), Gui::Application::Instance, Init::param, Gui::ViewProvider::show(), and Part::BodyBase::Tip.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), PartDesignGui::TaskDlgSketchBasedParameters::reject(), PartDesignGui::TaskDlgDressUpParameters::reject(), and PartDesignGui::TaskDlgTransformedParameters::reject().
The documentation for this class was generated from the following files:
TaskFeatureParameters.h
TaskFeatureParameters.cpp