FreeCAD: Gui::PythonDebugExcept Class Reference
Gui::PythonDebugExcept Class Reference
#include <PythonDebugger.h>
Public Member Functions
PythonDebugExcept ()
~PythonDebugExcept () override
Py::Object repr () override
Py::Object excepthook (const Py::Tuple &)
Static Public Member Functions
static void init_type ()
Detailed Description
Author
Werner Mayer
Definition at line 166 of file PythonDebugger.h.
Constructor & Destructor Documentation
PythonDebugExcept()
PythonDebugExcept::PythonDebugExcept () default
~PythonDebugExcept()
PythonDebugExcept::~PythonDebugExcept () override default
Member Function Documentation
excepthook()
Py::Object PythonDebugExcept::excepthook (const Py::Tuple & args)
Definition at line 269 of file PythonDebugger.cpp.
References toolbit-attributes::args.
Referenced by init_type().
init_type()
void PythonDebugExcept::init_type () static
Definition at line 248 of file PythonDebugger.cpp.
References excepthook().
Referenced by Gui::PythonDebugModule::init_module().
repr()
Py::Object PythonDebugExcept::repr () override
Definition at line 261 of file PythonDebugger.cpp.
References toolbit-attributes::s, and src.Mod.Test.testmakeWireString::String.
The documentation for this class was generated from the following files:
PythonDebugger.h
PythonDebugger.cpp