FreeCAD: Gui::DockWnd::ReportOutput Class Reference
Gui::DockWnd::ReportOutput Class Reference
#include <ReportView.h>
Classes
class Data
Public Slots
void onSaveAs ()
void onToggleError ()
void onToggleWarning ()
void onToggleLogMessage ()
void onToggleNormalMessage ()
void onToggleCritical ()
void onToggleShowReportViewOnWarning ()
void onToggleShowReportViewOnError ()
void onToggleShowReportViewOnNormalMessage ()
void onToggleShowReportViewOnCritical ()
void onToggleShowReportViewOnLogMessage ()
void onToggleRedirectPythonStdout ()
void onToggleRedirectPythonStderr ()
void onToggleGoToEnd ()
Public Member Functions
ReportOutput (QWidget *parent=nullptr)
~ReportOutput () override
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
void SendLog (const std::string &notifiername, const std::string &msg, Base::LogStyle level, Base::IntendedRecipient recipient, Base::ContentType content) override
const char * Name () override
returns the name for observer handling
void restoreFont ()
bool isError () const
bool isWarning () const
bool isLogMessage () const
bool isNormalMessage () const
bool isCritical () const
Public Member Functions inherited from Gui::WindowParameter
WindowParameter (const char *name)
~WindowParameter () override
void OnChange (Base::Subject< const char * > &rCaller, const char *sReason) override
ParameterGrp::handle getWindowParameter ()
return the parameter group of this window
Public Member Functions inherited from Base::ILogger
ILogger ()=default
ILogger (const ILogger &)=delete
ILogger (ILogger &&)=delete
ILogger & operator= (const ILogger &)=delete
ILogger & operator= (ILogger &&)=delete
virtual ~ILogger ()=0
bool isActive (Base::LogStyle category) const
Protected Member Functions
void customEvent (QEvent *ev) override
void changeEvent (QEvent *) override
void contextMenuEvent (QContextMenuEvent *e) override
bool event (QEvent *event) override
Protected Member Functions inherited from Gui::WindowParameter
bool setGroupName (const char *name)
template<typename S , typename T >
void setSlotParamChanged (S slot, T *obsPtr)
connect slot to ParameterManager signal
Additional Inherited Members
Static Public Member Functions inherited from Gui::WindowParameter
static ParameterGrp::handle getDefaultParameter ()
get the parameters
Public Attributes inherited from Base::ILogger
bool bErr {true}
bool bMsg {true}
bool bLog {true}
bool bWrn {true}
bool bCritical {true}
bool bNotification {false}
Detailed Description
Output window 'Report view' to show messages.
See also
Base::ILogger
QTextEdit
Author
Werner Mayer
Definition at line 133 of file ReportView.h.
Constructor & Destructor Documentation
ReportOutput()
ReportOutput::ReportOutput (QWidget * parent = nullptr) explicit
Constructs a ReportOutput which is a child of 'parent', with the name 'name' and widget flags set to 'f'
Definition at line 421 of file ReportView.cpp.
References Base::Subject< MsgType >::Attach(), Base::ConsoleSingleton::AttachObserver(), Base::ILogger::bLog, Path.Op.Gui.Selection::clear(), Base::Console(), Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), Gui::WindowParameter::getWindowParameter(), Gui::DockWnd::ReportOutput::Data::logMessageSize, Base::Subject< MsgType >::Notify(), ParameterGrp::NotifyAll(), and restoreFont().
~ReportOutput()
ReportOutput::~ReportOutput () override
Destroys the object and frees any allocated resources
Definition at line 456 of file ReportView.cpp.
References Base::Console(), Base::Subject< MsgType >::Detach(), Base::ConsoleSingleton::DetachObserver(), and Gui::WindowParameter::getWindowParameter().
Member Function Documentation
changeEvent()
void ReportOutput::changeEvent (QEvent * ev) override protected
Handles the change of style sheets
Definition at line 564 of file ReportView.cpp.
References ParameterGrp::GetUnsigned(), Gui::WindowParameter::getWindowParameter(), and ParameterGrp::SetUnsigned().
contextMenuEvent()
void ReportOutput::contextMenuEvent (QContextMenuEvent * e) override protected
Pops up the context menu with some extensions
Definition at line 578 of file ReportView.cpp.
References Base::ILogger::bCritical, Base::ILogger::bErr, Base::ILogger::bLog, Base::ILogger::bMsg, Base::ILogger::bWrn, Path.Op.Gui.Selection::clear(), Drawing::copy(), SCL.SimpleDataTypes::e, NavigationIndicatorGui::menu, onSaveAs(), onToggleCritical(), onToggleError(), onToggleGoToEnd(), onToggleLogMessage(), onToggleNormalMessage(), onToggleRedirectPythonStderr(), onToggleRedirectPythonStdout(), onToggleShowReportViewOnCritical(), onToggleShowReportViewOnError(), onToggleShowReportViewOnLogMessage(), onToggleShowReportViewOnNormalMessage(), onToggleShowReportViewOnWarning(), onToggleWarning(), Gui::DockWnd::ReportOutput::Data::redirected_stderr, Gui::DockWnd::ReportOutput::Data::redirected_stdout, Path.Op.Gui.Selection::select(), Gui::ReportOutputParameter::showOnCritical(), Gui::ReportOutputParameter::showOnError(), Gui::ReportOutputParameter::showOnLogMessage(), Gui::ReportOutputParameter::showOnMessage(), Gui::ReportOutputParameter::showOnWarning(), and src.Mod.AddonManager.Addon::translate.
customEvent()
void ReportOutput::customEvent (QEvent * ev) override protected
For internal use only
Definition at line 523 of file ReportView.cpp.
References ParameterGrp::GetBool(), Gui::WindowParameter::getWindowParameter(), and Gui::DockWnd::ReportHighlighter::setParagraphType().
event()
bool ReportOutput::event (QEvent * event) override protected
Handle shortcut override events
Definition at line 554 of file ReportView.cpp.
isCritical()
bool ReportOutput::isCritical () const
Returns true whether critical messages are reported.
Definition at line 716 of file ReportView.cpp.
References Base::ILogger::bCritical.
isError()
bool ReportOutput::isError () const
Returns true whether errors are reported.
Definition at line 695 of file ReportView.cpp.
References Base::ILogger::bErr.
isLogMessage()
bool ReportOutput::isLogMessage () const
Returns true whether log messages are reported.
Definition at line 705 of file ReportView.cpp.
References Base::ILogger::bLog.
isNormalMessage()
bool ReportOutput::isNormalMessage () const
Returns true whether normal messages are reported.
Definition at line 710 of file ReportView.cpp.
References Base::ILogger::bMsg.
isWarning()
bool ReportOutput::isWarning () const
Returns true whether warnings are reported.
Definition at line 700 of file ReportView.cpp.
References Base::ILogger::bWrn.
Name()
const char* Gui::DockWnd::ReportOutput::Name () inline override virtual
returns the name for observer handling
Reimplemented from Base::ILogger.
Definition at line 148 of file ReportView.h.
OnChange()
void ReportOutput::OnChange (Base::Subject< const char * > & rCaller, const char * sReason) override
Observes its parameter group.
Definition at line 814 of file ReportView.cpp.
References Base::ILogger::bErr, Base::ILogger::bLog, Base::ILogger::bMsg, Base::ILogger::bWrn, ParameterGrp::GetASCII(), ParameterGrp::GetBool(), ParameterGrp::GetInt(), ParameterGrp::GetUnsigned(), Gui::QtTools::horizontalAdvance(), Gui::DockWnd::ReportOutput::Data::logMessageSize, onToggleRedirectPythonStderr(), onToggleRedirectPythonStdout(), Gui::DockWnd::ReportOutput::Data::redirected_stderr, Gui::DockWnd::ReportOutput::Data::redirected_stdout, Gui::DockWnd::ReportHighlighter::setErrorColor(), Gui::DockWnd::ReportHighlighter::setLogColor(), Gui::DockWnd::ReportHighlighter::setTextColor(), and Gui::DockWnd::ReportHighlighter::setWarningColor().
onSaveAs
void ReportOutput::onSaveAs () slot
Save the report messages into a file.
Definition at line 678 of file ReportView.cpp.
References SCL.SimpleDataTypes::f, and InitGui::t.
Referenced by contextMenuEvent().
onToggleCritical
void ReportOutput::onToggleCritical () slot
Toggles the report of normal messages.
Definition at line 745 of file ReportView.cpp.
References Base::ILogger::bCritical, Gui::WindowParameter::getWindowParameter(), and ParameterGrp::SetBool().
Referenced by contextMenuEvent().
onToggleError
void ReportOutput::onToggleError () slot
Toggles the report of errors.
Definition at line 721 of file ReportView.cpp.
References Base::ILogger::bErr, Gui::WindowParameter::getWindowParameter(), and ParameterGrp::SetBool().
Referenced by contextMenuEvent().
onToggleGoToEnd
void ReportOutput::onToggleGoToEnd () slot
Toggles the report to go to the end if new messages appear.
Definition at line 808 of file ReportView.cpp.
References Gui::WindowParameter::getWindowParameter(), and ParameterGrp::SetBool().
Referenced by contextMenuEvent().
onToggleLogMessage
void ReportOutput::onToggleLogMessage () slot
Toggles the report of log messages.
Definition at line 733 of file ReportView.cpp.
References Base::ILogger::bLog, Gui::WindowParameter::getWindowParameter(), and ParameterGrp::SetBool().
Referenced by contextMenuEvent().
onToggleNormalMessage
void ReportOutput::onToggleNormalMessage () slot
Toggles the report of normal messages.
Definition at line 739 of file ReportView.cpp.
References Base::ILogger::bMsg, Gui::WindowParameter::getWindowParameter(), and ParameterGrp::SetBool().
Referenced by contextMenuEvent().
onToggleRedirectPythonStderr
void ReportOutput::onToggleRedirectPythonStderr () slot
Toggles the redirection of Python stderr.
Definition at line 792 of file ReportView.cpp.
References Gui::DockWnd::ReportOutput::Data::default_stderr, Gui::WindowParameter::getWindowParameter(), Gui::DockWnd::ReportOutput::Data::redirected_stderr, Gui::DockWnd::ReportOutput::Data::replace_stderr, and ParameterGrp::SetBool().
Referenced by contextMenuEvent(), and OnChange().
onToggleRedirectPythonStdout
void ReportOutput::onToggleRedirectPythonStdout () slot
Toggles the redirection of Python stdout.
Definition at line 776 of file ReportView.cpp.
References Gui::DockWnd::ReportOutput::Data::default_stdout, Gui::WindowParameter::getWindowParameter(), Gui::DockWnd::ReportOutput::Data::redirected_stdout, Gui::DockWnd::ReportOutput::Data::replace_stdout, and ParameterGrp::SetBool().
Referenced by contextMenuEvent(), and OnChange().
onToggleShowReportViewOnCritical
void ReportOutput::onToggleShowReportViewOnCritical () slot
Toggles whether to show report view on normal messages
Definition at line 766 of file ReportView.cpp.
References Gui::ReportOutputParameter::toggleShowOnCritical().
Referenced by contextMenuEvent().
onToggleShowReportViewOnError
void ReportOutput::onToggleShowReportViewOnError () slot
Toggles whether to show report view on errors
Definition at line 756 of file ReportView.cpp.
References Gui::ReportOutputParameter::toggleShowOnError().
Referenced by contextMenuEvent().
onToggleShowReportViewOnLogMessage
void ReportOutput::onToggleShowReportViewOnLogMessage () slot
Toggles whether to show report view on log messages
Definition at line 771 of file ReportView.cpp.
References Gui::ReportOutputParameter::toggleShowOnLogMessage().
Referenced by contextMenuEvent().
onToggleShowReportViewOnNormalMessage
void ReportOutput::onToggleShowReportViewOnNormalMessage () slot
Toggles whether to show report view on normal messages
Definition at line 761 of file ReportView.cpp.
References Gui::ReportOutputParameter::toggleShowOnMessage().
Referenced by contextMenuEvent().
onToggleShowReportViewOnWarning
void ReportOutput::onToggleShowReportViewOnWarning () slot
Toggles whether to show report view on warnings
Definition at line 751 of file ReportView.cpp.
References Gui::ReportOutputParameter::toggleShowOnWarning().
Referenced by contextMenuEvent().
onToggleWarning
void ReportOutput::onToggleWarning () slot
Toggles the report of warnings.
Definition at line 727 of file ReportView.cpp.
References Base::ILogger::bWrn, Gui::WindowParameter::getWindowParameter(), and ParameterGrp::SetBool().
Referenced by contextMenuEvent().
restoreFont()
void ReportOutput::restoreFont ()
Restore the default font settings.
Definition at line 465 of file ReportView.cpp.
References geoff_geometry::Normal().
Referenced by ReportOutput().
SendLog()
void ReportOutput::SendLog (const std::string & notifiername, const std::string & msg, Base::LogStyle level, Base::IntendedRecipient recipient, Base::ContentType content) override virtual
Used to send a Log message at the given level.
Parameters
notifiername A string identifying the entity generating the notification. It may be the Label of the App::Document or the full label of the App::DocumentObject.
msg The message to be notified.
level A valid level (Log, Message, Error, Notification, CriticalNotification, ...)
recipient A valid intended recipient (All, Developer, User). Observers may decide to process only notifications when a certain recipient is intended.
content A valid content property (Untranslated, Translatable, Untranslatable). Observers may decide not to process notifications if they are not translated or cannot be translated (are untranslatable). Or conversely, may decide not to process already translated notifications. It is up to the intended behaviour of the observer.
Implements Base::ILogger.
Definition at line 471 of file ReportView.cpp.
References Gui::DockWnd::ReportHighlighter::Critical, Base::Critical, Gui::DockWnd::ReportHighlighter::Error, Base::Error, level(), Base::Log, Gui::DockWnd::ReportHighlighter::LogText, Gui::DockWnd::ReportHighlighter::Message, Base::Message, Path.Op.Surface::msg, Base::Translated, Base::User, Gui::DockWnd::ReportHighlighter::Warning, and Base::Warning.
The documentation for this class was generated from the following files:
ReportView.h
ReportView.cpp