FreeCAD: MeshCore::AbstractPolygonTriangulator Class Reference
MeshCore::AbstractPolygonTriangulator Class Reference abstract
#include <Triangulation.h>
Public Member Functions
AbstractPolygonTriangulator ()
virtual ~AbstractPolygonTriangulator ()
AbstractPolygonTriangulator (const AbstractPolygonTriangulator &)=delete
AbstractPolygonTriangulator (AbstractPolygonTriangulator &&)=delete
AbstractPolygonTriangulator & operator= (const AbstractPolygonTriangulator &)=delete
AbstractPolygonTriangulator & operator= (AbstractPolygonTriangulator &&)=delete
void SetPolygon (const std::vector< Base::Vector3f > &raclPoints)
void SetIndices (const std::vector< PointIndex > &d)
void SetVerifier (TriangulationVerifier *v)
TriangulationVerifier * GetVerifier () const
virtual bool NeedsReindexing () const
std::vector< Base::Vector3f > GetPolygon () const
std::vector< Base::Vector3f > AddedPoints () const
Base::Matrix4D GetTransformToFitPlane () const
std::vector< Base::Vector3f > ProjectToFitPlane ()
bool TriangulatePolygon ()
virtual void PostProcessing (const std::vector< Base::Vector3f > &)
const std::vector< MeshGeomFacet > & GetTriangles () const
const std::vector< MeshFacet > & GetFacets () const
virtual MeshGeomFacet GetTriangle (const MeshPointArray &, const MeshFacet &) const
float GetLength () const
std::vector< PointIndex > GetInfo () const
virtual void Discard ()
virtual void Reset ()
Protected Member Functions
virtual bool Triangulate ()=0
void Done ()
Protected Attributes
bool _discard
Base::Matrix4D _inverse
std::vector< PointIndex > _indices
std::vector< Base::Vector3f > _points
std::vector< Base::Vector3f > _newpoints
std::vector< MeshGeomFacet > _triangles
std::vector< MeshFacet > _facets
std::vector< PointIndex > _info
TriangulationVerifier * _verifier
Detailed Description
Definition at line 80 of file Triangulation.h.
Constructor & Destructor Documentation
AbstractPolygonTriangulator() [1/3]
AbstractPolygonTriangulator::AbstractPolygonTriangulator ()
Definition at line 77 of file Triangulation.cpp.
~AbstractPolygonTriangulator()
AbstractPolygonTriangulator::~AbstractPolygonTriangulator () virtual
Definition at line 82 of file Triangulation.cpp.
References _verifier.
AbstractPolygonTriangulator() [2/3]
MeshCore::AbstractPolygonTriangulator::AbstractPolygonTriangulator (const AbstractPolygonTriangulator &) delete
AbstractPolygonTriangulator() [3/3]
MeshCore::AbstractPolygonTriangulator::AbstractPolygonTriangulator (AbstractPolygonTriangulator &&) delete
Member Function Documentation
AddedPoints()
std::vector< Base::Vector3f > AbstractPolygonTriangulator::AddedPoints () const
The triangulation algorithm may create new points when calling Triangulate(). This method returns these added points.
Note
: Make sure to have called PostProcessing() before using this method if you want the surface points the new points are lying on.
Definition at line 129 of file Triangulation.cpp.
References _inverse, and _newpoints.
Referenced by MeshCore::MeshAlgorithm::FillupHole().
Discard()
void AbstractPolygonTriangulator::Discard () virtual
Definition at line 268 of file Triangulation.cpp.
References _discard, and _info.
Referenced by MeshCore::MeshAlgorithm::FillupHole().
Done()
void AbstractPolygonTriangulator::Done () protected
Definition at line 279 of file Triangulation.cpp.
References _discard, _info, and _points.
Referenced by TriangulatePolygon().
GetFacets()
const std::vector<MeshFacet>& MeshCore::AbstractPolygonTriangulator::GetFacets () const inline
Returns the topologic facets of the polygon.
Definition at line 147 of file Triangulation.h.
Referenced by MeshGui::ViewProviderMesh::createToolMesh(), MeshCore::MeshAlgorithm::FillupHole(), MeshCore::FlatTriangulator::Triangulate(), and MeshCore::ConstraintDelaunayTriangulator::Triangulate().
GetInfo()
std::vector< PointIndex > AbstractPolygonTriangulator::GetInfo () const
Get information about the polygons that were processed. It returns an array of the number of edges for each closed polygon.
Definition at line 263 of file Triangulation.cpp.
References _info.
GetLength()
float AbstractPolygonTriangulator::GetLength () const
Returns the length of the polygon
Definition at line 113 of file Triangulation.cpp.
References _points, and Base::Distance().
GetPolygon()
std::vector< Base::Vector3f > AbstractPolygonTriangulator::GetPolygon () const
Get the polygon points to be triangulated. The points may be projected onto its average plane.
Definition at line 108 of file Triangulation.cpp.
References _points.
Referenced by MeshCore::MeshAlgorithm::FillupHole(), MeshCore::FlatTriangulator::Triangulate(), and MeshCore::ConstraintDelaunayTriangulator::Triangulate().
GetTransformToFitPlane()
Base::Matrix4D AbstractPolygonTriangulator::GetTransformToFitPlane () const
Computes the best-fit plane and returns a transformation matrix built out of the axes of the plane.
Definition at line 140 of file Triangulation.cpp.
References _points, MeshCore::Approximation::AddPoint(), SplineSurface::bs, MeshCore::PlaneFit::Fit(), FLOAT_MAX, MeshCore::PlaneFit::GetBase(), MeshCore::PlaneFit::GetDirU(), MeshCore::PlaneFit::GetDirV(), MeshCore::PlaneFit::GetNormal(), Base::Matrix4D::setToUnity(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by ProjectToFitPlane().
GetTriangle()
MeshGeomFacet AbstractPolygonTriangulator::GetTriangle (const MeshPointArray & points, const MeshFacet & facet) const virtual
Returns the triangle to a given topologic facet.
Definition at line 225 of file Triangulation.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, and MeshCore::MeshFacet::_aulPoints.
Referenced by MeshCore::MeshAlgorithm::FillupHole().
GetTriangles()
const std::vector<MeshGeomFacet>& MeshCore::AbstractPolygonTriangulator::GetTriangles () const inline
Returns the geometric triangles of the polygon.
Definition at line 142 of file Triangulation.h.
Referenced by MeshCore::FlatTriangulator::Triangulate(), and MeshCore::ConstraintDelaunayTriangulator::Triangulate().
GetVerifier()
TriangulationVerifier * AbstractPolygonTriangulator::GetVerifier () const
Definition at line 87 of file Triangulation.cpp.
References _verifier.
Referenced by MeshCore::MeshAlgorithm::FillupHole().
NeedsReindexing()
virtual bool MeshCore::AbstractPolygonTriangulator::NeedsReindexing () const inline virtual
Usually the created faces use the indices of the polygon points from [0, n]. If the faces should be appended to an existing mesh they may need to be reindexed from the calling instance. However, there may other algorithms that directly use the indices of the mesh and thus do not need to be touched afterwards. In this case the method should be reimplemented to return false.
Definition at line 110 of file Triangulation.h.
Referenced by MeshCore::MeshAlgorithm::FillupHole(), and MeshCore::MeshTopoAlgorithm::FillupHoles().
operator=() [1/2]
AbstractPolygonTriangulator& MeshCore::AbstractPolygonTriangulator::operator= (AbstractPolygonTriangulator &&) delete
operator=() [2/2]
AbstractPolygonTriangulator& MeshCore::AbstractPolygonTriangulator::operator= (const AbstractPolygonTriangulator &) delete
PostProcessing()
void AbstractPolygonTriangulator::PostProcessing (const std::vector< Base::Vector3f > & points) virtual
If points were added then we get the 3D points by projecting the added 2D points onto a surface which fits into the given points.
Reimplemented in MeshCore::FlatTriangulator.
Definition at line 196 of file Triangulation.cpp.
References _inverse, _newpoints, MeshCore::Approximation::AddPoint(), SplineSurface::bs, MeshCore::Approximation::CountPoints(), MeshCore::PolynomialFit::Fit(), FLOAT_MAX, and MeshCore::PolynomialFit::Value().
Referenced by MeshCore::MeshAlgorithm::FillupHole().
ProjectToFitPlane()
std::vector< Base::Vector3f > AbstractPolygonTriangulator::ProjectToFitPlane ()
If the points of the polygon set by SetPolygon() doesn't lie in a plane this method can be used to project the points in a common plane.
Definition at line 177 of file Triangulation.cpp.
References _inverse, _points, SplineSurface::bs, and GetTransformToFitPlane().
Referenced by MeshCore::EarClippingTriangulator::Triangulate(), MeshCore::FlatTriangulator::Triangulate(), and MeshCore::ConstraintDelaunayTriangulator::Triangulate().
Reset()
void AbstractPolygonTriangulator::Reset () virtual
Resets some internals. The default implementation does nothing.
Definition at line 276 of file Triangulation.cpp.
SetIndices()
void MeshCore::AbstractPolygonTriangulator::SetIndices (const std::vector< PointIndex > & d) inline
Definition at line 93 of file Triangulation.h.
Referenced by MeshCore::MeshAlgorithm::FillupHole().
SetPolygon()
void AbstractPolygonTriangulator::SetPolygon (const std::vector< Base::Vector3f > & raclPoints)
Sets the polygon to be triangulated.
Definition at line 98 of file Triangulation.cpp.
References _points.
Referenced by MeshGui::ViewProviderMesh::createToolMesh(), MeshCore::MeshAlgorithm::FillupHole(), MeshCore::FlatTriangulator::Triangulate(), and MeshCore::ConstraintDelaunayTriangulator::Triangulate().
SetVerifier()
void AbstractPolygonTriangulator::SetVerifier (TriangulationVerifier * v)
Set a verifier object that checks if the generated triangulation can be accepted and added to the mesh kernel. The triangulator takes ownership of the passed verifier.
Definition at line 92 of file Triangulation.cpp.
References _verifier, and TestSpreadsheet::v.
Referenced by MeshGui::ViewProviderMesh::fillHole().
Triangulate()
virtual bool MeshCore::AbstractPolygonTriangulator::Triangulate () protected pure virtual
Computes the triangulation of a polygon. The resulting facets can be accessed by GetTriangles() or GetFacets().
Implemented in MeshCore::ConstraintDelaunayTriangulator, MeshCore::FlatTriangulator, MeshCore::DelaunayTriangulator, MeshCore::QuasiDelaunayTriangulator, and MeshCore::EarClippingTriangulator.
Referenced by TriangulatePolygon().
TriangulatePolygon()
bool AbstractPolygonTriangulator::TriangulatePolygon ()
Computes the triangulation of a polygon. The resulting facets can be accessed by GetTriangles() or GetFacets().
Definition at line 235 of file Triangulation.cpp.
References _indices, _points, Base::Console(), Done(), SCL.SimpleDataTypes::e, Base::ConsoleSingleton::Log(), and Triangulate().
Referenced by MeshGui::ViewProviderMesh::createToolMesh(), MeshCore::MeshAlgorithm::FillupHole(), MeshCore::FlatTriangulator::Triangulate(), and MeshCore::ConstraintDelaunayTriangulator::Triangulate().
Member Data Documentation
_discard
bool MeshCore::AbstractPolygonTriangulator::_discard protected
Definition at line 173 of file Triangulation.h.
Referenced by Discard(), and Done().
_facets
std::vector<MeshFacet> MeshCore::AbstractPolygonTriangulator::_facets protected
Definition at line 179 of file Triangulation.h.
Referenced by MeshCore::EarClippingTriangulator::Triangulate(), MeshCore::QuasiDelaunayTriangulator::Triangulate(), MeshCore::DelaunayTriangulator::Triangulate(), MeshCore::FlatTriangulator::Triangulate(), and MeshCore::ConstraintDelaunayTriangulator::Triangulate().
_indices
std::vector<PointIndex> MeshCore::AbstractPolygonTriangulator::_indices protected
Definition at line 175 of file Triangulation.h.
Referenced by TriangulatePolygon().
_info
std::vector<PointIndex> MeshCore::AbstractPolygonTriangulator::_info protected
Definition at line 180 of file Triangulation.h.
Referenced by Discard(), Done(), and GetInfo().
_inverse
Base::Matrix4D MeshCore::AbstractPolygonTriangulator::_inverse protected
Definition at line 174 of file Triangulation.h.
Referenced by AddedPoints(), PostProcessing(), and ProjectToFitPlane().
_newpoints
std::vector<Base::Vector3f> MeshCore::AbstractPolygonTriangulator::_newpoints protected
Definition at line 177 of file Triangulation.h.
Referenced by AddedPoints(), PostProcessing(), MeshCore::FlatTriangulator::Triangulate(), and MeshCore::ConstraintDelaunayTriangulator::Triangulate().
_points
std::vector<Base::Vector3f> MeshCore::AbstractPolygonTriangulator::_points protected
Definition at line 176 of file Triangulation.h.
Referenced by Done(), GetLength(), GetPolygon(), GetTransformToFitPlane(), ProjectToFitPlane(), SetPolygon(), MeshCore::EarClippingTriangulator::Triangulate(), MeshCore::QuasiDelaunayTriangulator::Triangulate(), MeshCore::DelaunayTriangulator::Triangulate(), and TriangulatePolygon().
_triangles
std::vector<MeshGeomFacet> MeshCore::AbstractPolygonTriangulator::_triangles protected
Definition at line 178 of file Triangulation.h.
Referenced by MeshCore::EarClippingTriangulator::Triangulate(), MeshCore::DelaunayTriangulator::Triangulate(), MeshCore::FlatTriangulator::Triangulate(), and MeshCore::ConstraintDelaunayTriangulator::Triangulate().
_verifier
TriangulationVerifier* MeshCore::AbstractPolygonTriangulator::_verifier protected
Definition at line 181 of file Triangulation.h.
Referenced by GetVerifier(), SetVerifier(), and ~AbstractPolygonTriangulator().
The documentation for this class was generated from the following files:
Triangulation.h
Triangulation.cpp