FreeCAD: FemGui::GuiTools Namespace Reference
FemGui::GuiTools Namespace Reference
Functions
void createPlacement (SoSeparator *sep, const SbVec3f &base, const SbRotation &r)
void updatePlacement (const SoSeparator *sep, const int idx, const SbVec3f &base, const SbRotation &r)
void createCone (SoSeparator *sep, const double height, const double radius)
SoSeparator * createCone (const double height, const double radius)
void updateCone (const SoNode *node, const int idx, const double height, const double radius)
void createCylinder (SoSeparator *sep, const double height, const double radius)
SoSeparator * createCylinder (const double height, const double radius)
void updateCylinder (const SoNode *node, const int idx, const double height, const double radius)
void createCube (SoSeparator *sep, const double width, const double length, const double height)
SoSeparator * createCube (const double width, const double length, const double height)
void updateCube (const SoNode *node, const int idx, const double width, const double length, const double height)
void createArrow (SoSeparator *sep, const double length, const double radius)
SoSeparator * createArrow (const double length, const double radius)
void updateArrow (const SoNode *node, const int idx, const double length, const double radius)
void createFixed (SoSeparator *sep, const double height, const double width, const bool gap)
SoSeparator * createFixed (const double height, const double width, const bool gap)
void updateFixed (const SoNode *node, const int idx, const double height, const double width, const bool gap)
Function Documentation
createArrow() [1/2]
SoSeparator * FemGui::GuiTools::createArrow (const double length, const double radius)
Definition at line 176 of file FemGuiTools.cpp.
createArrow() [2/2]
void FemGui::GuiTools::createArrow (SoSeparator * sep, const double length, const double radius)
Definition at line 169 of file FemGuiTools.cpp.
Referenced by updateCube(), FemGui::ViewProviderFemConstraintPulley::updateData(), FemGui::ViewProviderFemConstraintGear::updateData(), and FemGui::ViewProviderFemConstraintFluidBoundary::updateData().
createCone() [1/2]
SoSeparator * FemGui::GuiTools::createCone (const double height, const double radius)
Definition at line 98 of file FemGuiTools.cpp.
createCone() [2/2]
void FemGui::GuiTools::createCone (SoSeparator * sep, const double height, const double radius)
Definition at line 86 of file FemGuiTools.cpp.
Referenced by createCube().
createCube() [1/2]
SoSeparator * FemGui::GuiTools::createCube (const double width, const double length, const double height)
Definition at line 149 of file FemGuiTools.cpp.
References createCone(), createCylinder(), and createPlacement().
createCube() [2/2]
void FemGui::GuiTools::createCube (SoSeparator * sep, const double width, const double length, const double height)
Definition at line 140 of file FemGuiTools.cpp.
References cube.
createCylinder() [1/2]
SoSeparator * FemGui::GuiTools::createCylinder (const double height, const double radius)
Definition at line 124 of file FemGuiTools.cpp.
createCylinder() [2/2]
void FemGui::GuiTools::createCylinder (SoSeparator * sep, const double height, const double radius)
Definition at line 116 of file FemGuiTools.cpp.
Referenced by createCube(), FemGui::ViewProviderFemConstraintPulley::updateData(), and FemGui::ViewProviderFemConstraintGear::updateData().
createFixed() [1/2]
SoSeparator * FemGui::GuiTools::createFixed (const double height, const double width, const bool gap)
Definition at line 204 of file FemGuiTools.cpp.
createFixed() [2/2]
void FemGui::GuiTools::createFixed (SoSeparator * sep, const double height, const double width, const bool gap)
Definition at line 194 of file FemGuiTools.cpp.
References CONE_CHILDREN, PLACEMENT_CHILDREN, updateCone(), updateCube(), and updatePlacement().
Referenced by updateArrow(), FemGui::ViewProviderFemConstraintBearing::updateData(), and FemGui::ViewProviderFemConstraintFluidBoundary::updateData().
createPlacement()
void FemGui::GuiTools::createPlacement (SoSeparator * sep, const SbVec3f & base, const SbRotation & r)
Definition at line 65 of file FemGuiTools.cpp.
Referenced by createCube(), FemGui::ViewProviderFemConstraintPulley::updateData(), FemGui::ViewProviderFemConstraintGear::updateData(), FemGui::ViewProviderFemConstraintBearing::updateData(), and FemGui::ViewProviderFemConstraintFluidBoundary::updateData().
updateArrow()
void FemGui::GuiTools::updateArrow (const SoNode * node, const int idx, const double length, const double radius)
Definition at line 183 of file FemGuiTools.cpp.
References createFixed().
Referenced by FemGui::ViewProviderFemConstraintGear::updateData(), FemGui::ViewProviderFemConstraintPulley::updateData(), and FemGui::ViewProviderFemConstraintFluidBoundary::updateData().
updateCone()
void FemGui::GuiTools::updateCone (const SoNode * node, const int idx, const double height, const double radius)
Definition at line 106 of file FemGuiTools.cpp.
Referenced by createFixed().
updateCube()
void FemGui::GuiTools::updateCube (const SoNode * node, const int idx, const double width, const double length, const double height)
Definition at line 156 of file FemGuiTools.cpp.
References createArrow().
Referenced by createFixed().
updateCylinder()
void FemGui::GuiTools::updateCylinder (const SoNode * node, const int idx, const double height, const double radius)
Definition at line 132 of file FemGuiTools.cpp.
Referenced by FemGui::ViewProviderFemConstraintGear::updateData(), and FemGui::ViewProviderFemConstraintPulley::updateData().
updateFixed()
void FemGui::GuiTools::updateFixed (const SoNode * node, const int idx, const double height, const double width, const bool gap)
Definition at line 211 of file FemGuiTools.cpp.
Referenced by FemGui::ViewProviderFemConstraintBearing::updateData().
updatePlacement()
void FemGui::GuiTools::updatePlacement (const SoSeparator * sep, const int idx, const SbVec3f & base, const SbRotation & r)
Definition at line 75 of file FemGuiTools.cpp.
Referenced by createFixed(), FemGui::ViewProviderFemConstraintPulley::updateData(), FemGui::ViewProviderFemConstraintGear::updateData(), FemGui::ViewProviderFemConstraintBearing::updateData(), and FemGui::ViewProviderFemConstraintFluidBoundary::updateData().