FreeCAD: GCS::ArcOfEllipse Class Reference
GCS::ArcOfEllipse Class Reference
#include <Geo.h>
Public Member Functions
ArcOfEllipse ()
~ArcOfEllipse () override
int PushOwnParams (VEC_pD &pvec) override
void ReconstructOnNewPvec (VEC_pD &pvec, int &cnt) override
ArcOfEllipse * Copy () override
Public Member Functions inherited from GCS::Ellipse
Ellipse ()
~Ellipse () override
double getRadMaj (const DeriVector2 &center, const DeriVector2 &f1, double b, double db, double &ret_dRadMaj) const override
double getRadMaj (double *derivparam, double &ret_dRadMaj) const override
double getRadMaj () const override
DeriVector2 CalculateNormal (const Point &p, const double *derivparam=nullptr) const override
DeriVector2 Value (double u, double du, const double *derivparam=nullptr) const override
Value: returns point (vector) given the value of parameter.
Public Member Functions inherited from GCS::MajorRadiusConic
~MajorRadiusConic () override
Public Member Functions inherited from GCS::Curve
virtual ~Curve ()
virtual DeriVector2 CalculateNormal (const double *param, const double *derivparam=nullptr) const
Public Attributes
double * startAngle
double * endAngle
Point start
Point end
Public Attributes inherited from GCS::Ellipse
Point center
Point focus1
double * radmin
Detailed Description
Definition at line 316 of file Geo.h.
Constructor & Destructor Documentation
ArcOfEllipse()
GCS::ArcOfEllipse::ArcOfEllipse () inline
Definition at line 319 of file Geo.h.
Referenced by Copy().
~ArcOfEllipse()
GCS::ArcOfEllipse::~ArcOfEllipse () inline override
Definition at line 325 of file Geo.h.
Member Function Documentation
Copy()
ArcOfEllipse * GCS::ArcOfEllipse::Copy () override virtual
Reimplemented from GCS::Ellipse.
Definition at line 436 of file Geo.cpp.
References ArcOfEllipse().
PushOwnParams()
int GCS::ArcOfEllipse::PushOwnParams (VEC_pD & pvec) override virtual
Reimplemented from GCS::Ellipse.
Definition at line 402 of file Geo.cpp.
References end, endAngle, GCS::Ellipse::PushOwnParams(), start, startAngle, GCS::Point::x, and GCS::Point::y.
ReconstructOnNewPvec()
void GCS::ArcOfEllipse::ReconstructOnNewPvec (VEC_pD & pvec, int & cnt) override virtual
Reimplemented from GCS::Ellipse.
Definition at line 420 of file Geo.cpp.
References end, endAngle, GCS::Ellipse::ReconstructOnNewPvec(), start, startAngle, GCS::Point::x, and GCS::Point::y.
Member Data Documentation
end
Point GCS::ArcOfEllipse::end
Definition at line 331 of file Geo.h.
Referenced by PushOwnParams(), and ReconstructOnNewPvec().
endAngle
double* GCS::ArcOfEllipse::endAngle
Definition at line 328 of file Geo.h.
Referenced by PushOwnParams(), and ReconstructOnNewPvec().
start
Point GCS::ArcOfEllipse::start
Definition at line 330 of file Geo.h.
Referenced by PushOwnParams(), and ReconstructOnNewPvec().
startAngle
double* GCS::ArcOfEllipse::startAngle
Definition at line 327 of file Geo.h.
Referenced by PushOwnParams(), and ReconstructOnNewPvec().
The documentation for this class was generated from the following files:
Geo.h
Geo.cpp