FreeCAD: TechDraw::XMLQuery Class Reference
TechDraw::XMLQuery Class Reference
#include <XMLQuery.h>
Public Member Functions
XMLQuery (QDomDocument &)
bool processItems (const QString &queryStr, const std::function< bool(QDomElement &)> &process)
Detailed Description
Definition at line 38 of file XMLQuery.h.
Constructor & Destructor Documentation
XMLQuery()
XMLQuery::XMLQuery (QDomDocument & dom)
Definition at line 36 of file XMLQuery.cpp.
Member Function Documentation
processItems()
bool XMLQuery::processItems (const QString & queryStr, const std::function< bool(QDomElement &)> & process)
Definition at line 80 of file XMLQuery.cpp.
References importAirfoilDAT::process(), and processElements().
Referenced by TechDrawGui::QGISVGTemplate::createClickHandles(), TechDraw::DrawSVGTemplate::getAutofillByEditableName(), TechDraw::DrawViewSymbol::getEditableFields(), TechDraw::DrawSVGTemplate::getEditableTextsFromTemplate(), TechDraw::DrawSVGTemplate::processTemplate(), and TechDraw::DrawViewSymbol::updateFieldsInSymbol().
The documentation for this class was generated from the following files:
XMLQuery.h
XMLQuery.cpp