FreeCAD: QSint::FreeCADPanelScheme Class Reference
QSint::FreeCADPanelScheme Class Reference
#include <freecadscheme.h>
Public Member Functions
FreeCADPanelScheme ()
void clearActionStyle ()
void restoreActionStyle ()
Public Member Functions inherited from QSint::ActionPanelScheme
ActionPanelScheme ()
Static Public Member Functions
static ActionPanelScheme * defaultScheme ()
Static Public Member Functions inherited from QSint::ActionPanelScheme
static ActionPanelScheme * defaultScheme ()
Additional Inherited Members
Public Types inherited from QSint::ActionPanelScheme
enum TaskPanelFoldEffect { NoFolding, ShrunkFolding, SlideFolding }
Animation effect during expanding/collapsing of the ActionGroup's contents.
Public Attributes inherited from QSint::ActionPanelScheme
int headerSize
Height of the header in pixels.
bool headerAnimation
If set to true, moving mouse over the header results in changing its opacity slowly.
QPixmap headerButtonFold
Image of folding button when the group is expanded.
QPixmap headerButtonFoldOver
Image of folding button when the group is expanded and mouse cursor is over the button.
QPixmap headerButtonUnfold
Image of folding button when the group is collapsed.
QPixmap headerButtonUnfoldOver
Image of folding button when the group is collapsed and mouse cursor is over the button.
QSize headerButtonSize
int groupFoldSteps
Number of steps made for expanding/collapsing animation (default 20).
int groupFoldDelay
Delay in ms between steps made for expanding/collapsing animation (default 15).
TaskPanelFoldEffect groupFoldEffect
Sets folding effect during expanding/collapsing.
bool groupFoldThaw
If set to true, changes group's opacity slowly during expanding/collapsing.
QString actionStyle
The CSS for the ActionPanel/ActionGroup elements.
Detailed Description
Definition at line 54 of file freecadscheme.h.
Constructor & Destructor Documentation
FreeCADPanelScheme()
QSint::FreeCADPanelScheme::FreeCADPanelScheme () explicit
Definition at line 154 of file freecadscheme.cpp.
Member Function Documentation
clearActionStyle()
void QSint::FreeCADPanelScheme::clearActionStyle ()
Definition at line 197 of file freecadscheme.cpp.
References buildPsets::p.
defaultScheme()
static ActionPanelScheme* QSint::FreeCADPanelScheme::defaultScheme () inline static
Definition at line 79 of file freecadscheme.h.
Referenced by Gui::TaskView::TaskView::addTaskWatcher(), Gui::TaskView::TaskView::clearActionStyle(), Gui::TaskView::TaskView::restoreActionStyle(), Gui::TaskView::TaskView::showDialog(), and Gui::TaskView::TaskView::TaskView().
restoreActionStyle()
void QSint::FreeCADPanelScheme::restoreActionStyle ()
Definition at line 207 of file freecadscheme.cpp.
The documentation for this class was generated from the following files:
freecadscheme.h
freecadscheme.cpp