FreeCAD: AutoSaver Class Reference
AutoSaver Class Reference
#include <DownloadItem.h>
Public Slots
void changeOccurred ()
Public Member Functions
AutoSaver (QObject *parent)
~AutoSaver () override
void saveIfNecessary ()
Protected Member Functions
void timerEvent (QTimerEvent *event) override
Detailed Description
Definition at line 70 of file DownloadItem.h.
Constructor & Destructor Documentation
AutoSaver()
AutoSaver::AutoSaver (QObject * parent) explicit
Definition at line 118 of file DownloadItem.cpp.
References Init::parent.
~AutoSaver()
AutoSaver::~AutoSaver () override
Definition at line 124 of file DownloadItem.cpp.
Member Function Documentation
changeOccurred
void AutoSaver::changeOccurred () slot
Definition at line 131 of file DownloadItem.cpp.
References AUTOSAVE_IN, MAXWAIT, and saveIfNecessary().
saveIfNecessary()
void AutoSaver::saveIfNecessary ()
Definition at line 155 of file DownloadItem.cpp.
References Init::parent.
Referenced by changeOccurred(), and timerEvent().
timerEvent()
void AutoSaver::timerEvent (QTimerEvent * event) override protected
Definition at line 145 of file DownloadItem.cpp.
References saveIfNecessary().
The documentation for this class was generated from the following files:
DownloadItem.h
DownloadItem.cpp