FreeCAD: Gui::SoFCSelectionCounter Class Reference
Gui::SoFCSelectionCounter Class Reference
#include <SoFCSelectionContext.h>
Public Member Functions
SoFCSelectionCounter ()
virtual ~SoFCSelectionCounter ()
bool checkRenderCache (SoState *state)
void checkAction (SoHighlightElementAction *hlaction)
void checkAction (SoSelectionElementAction *selaction, SoFCSelectionContextPtr ctx)
Protected Attributes
std::shared_ptr< int > counter
bool hasSelection {false}
bool hasPreselection {false}
Static Protected Attributes
static int cachingMode
Detailed Description
Definition at line 126 of file SoFCSelectionContext.h.
Constructor & Destructor Documentation
SoFCSelectionCounter()
SoFCSelectionCounter::SoFCSelectionCounter ()
Definition at line 241 of file SoFCSelectionContext.cpp.
~SoFCSelectionCounter()
SoFCSelectionCounter::~SoFCSelectionCounter () virtual default
Member Function Documentation
checkAction() [1/2]
void SoFCSelectionCounter::checkAction (SoHighlightElementAction * hlaction)
Definition at line 264 of file SoFCSelectionContext.cpp.
References hasPreselection, and Gui::SoHighlightElementAction::isHighlighted().
Referenced by PartGui::SoBrepEdgeSet::doAction(), PartGui::SoBrepPointSet::doAction(), and PartGui::SoBrepFaceSet::doAction().
checkAction() [2/2]
void SoFCSelectionCounter::checkAction (SoSelectionElementAction * selaction, SoFCSelectionContextPtr ctx)
Definition at line 269 of file SoFCSelectionContext.cpp.
References Gui::SoSelectionElementAction::All, Gui::SoSelectionElementAction::Append, counter, Gui::SoSelectionElementAction::getType(), hasSelection, Gui::SoSelectionElementAction::isSecondary(), and Gui::SoSelectionElementAction::None.
checkRenderCache()
bool SoFCSelectionCounter::checkRenderCache (SoState * state)
Definition at line 248 of file SoFCSelectionContext.cpp.
References counter, Gui::SoFCSeparator::getCacheMode(), hasPreselection, hasSelection, MeshCore::MeshIO::OFF, and Gui::Selection().
Referenced by PartGui::SoBrepEdgeSet::GLRender(), PartGui::SoBrepPointSet::GLRender(), and PartGui::SoBrepFaceSet::GLRender().
Member Data Documentation
cachingMode
int Gui::SoFCSelectionCounter::cachingMode static protected
Definition at line 137 of file SoFCSelectionContext.h.
counter
std::shared_ptr<int> Gui::SoFCSelectionCounter::counter protected
Definition at line 134 of file SoFCSelectionContext.h.
Referenced by checkAction(), checkRenderCache(), src.Mod.AddonManager.addonmanager_workers_startup.CacheMacroCodeWorker::run(), and src.Mod.AddonManager.addonmanager_workers_startup.CacheMacroCodeWorker::update_and_advance().
hasPreselection
bool Gui::SoFCSelectionCounter::hasPreselection {false} protected
Definition at line 136 of file SoFCSelectionContext.h.
Referenced by checkAction(), and checkRenderCache().
hasSelection
bool Gui::SoFCSelectionCounter::hasSelection {false} protected
Definition at line 135 of file SoFCSelectionContext.h.
Referenced by checkAction(), and checkRenderCache().
The documentation for this class was generated from the following files:
SoFCSelectionContext.h
SoFCSelectionContext.cpp