FreeCAD: TechDraw::LineSet Class Reference
TechDraw::LineSet Class Reference
a LineSet is all the generated edges for 1 PATLineSpec for 1 Face
#include <HatchLine.h>
Public Member Functions
LineSet ()
~LineSet ()=default
void setPATLineSpec (const PATLineSpec &s)
void setEdges (std::vector< TopoDS_Edge > e)
void setGeoms (std::vector< TechDraw::BaseGeomPtr > g)
void setBBox (const Bnd_Box &bb)
std::vector< TopoDS_Edge > getEdges ()
TopoDS_Edge getEdge (int i)
std::vector< TechDraw::BaseGeomPtr > getGeoms ()
PATLineSpec getPATLineSpec ()
double getOffset ()
double getAngle ()
Base::Vector3d getOrigin ()
double getInterval ()
double getIntervalX ()
double getIntervalY ()
double getSlope ()
double getPatternLength ()
Base::Vector3d getUnitDir ()
Base::Vector3d getUnitOrtho ()
DashSpec getDashSpec ()
Base::Vector3d calcApparentStart (TechDraw::BaseGeomPtr g)
calculates the apparent start point (ie start of overlay line) for dashed lines
Base::Vector3d findAtomStart ()
Base::Vector3d getLineOrigin ()
Base::Vector3d getPatternStartPoint (TechDraw::BaseGeomPtr g, double &offset, double scale=1.0)
Bnd_Box getBBox ()
double getMinX ()
double getMaxX ()
double getMinY ()
double getMaxY ()
bool isDashed ()
Detailed Description
a LineSet is all the generated edges for 1 PATLineSpec for 1 Face
Definition at line 111 of file HatchLine.h.
Constructor & Destructor Documentation
LineSet()
TechDraw::LineSet::LineSet () inline
Definition at line 114 of file HatchLine.h.
~LineSet()
TechDraw::LineSet::~LineSet () default
Member Function Documentation
calcApparentStart()
Base::Vector3d LineSet::calcApparentStart (TechDraw::BaseGeomPtr g)
calculates the apparent start point (ie start of overlay line) for dashed lines
Definition at line 80 of file HatchLine.cpp.
References toolbit-attributes::g, TechDraw::PATLineSpec::getAngle(), getMinX(), getMinY(), getPATLineSpec(), TechDraw::PATLineSpec::getSlope(), MovieTool::x, and MovieTool::y.
Referenced by getPatternStartPoint().
findAtomStart()
Base::Vector3d LineSet::findAtomStart ()
Definition at line 131 of file HatchLine.cpp.
References getAngle(), getMinX(), getMinY(), getOrigin(), getSlope(), MovieTool::x, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by getPatternStartPoint().
getAngle()
double TechDraw::LineSet::getAngle () inline
Definition at line 128 of file HatchLine.h.
Referenced by findAtomStart(), and getPatternStartPoint().
getBBox()
Bnd_Box TechDraw::LineSet::getBBox () inline
Definition at line 143 of file HatchLine.h.
getDashSpec()
DashSpec TechDraw::LineSet::getDashSpec () inline
Definition at line 137 of file HatchLine.h.
Referenced by TechDrawGui::PATPathMaker::geomToLine(), TechDrawGui::PATPathMaker::geomToStubbyLine(), and TechDrawGui::PATPathMaker::lineSetToFillItems().
getEdge()
TopoDS_Edge TechDraw::LineSet::getEdge (int i) inline
Definition at line 123 of file HatchLine.h.
References SplineSurface::i.
getEdges()
std::vector<TopoDS_Edge> TechDraw::LineSet::getEdges () inline
Definition at line 122 of file HatchLine.h.
getGeoms()
std::vector<TechDraw::BaseGeomPtr> TechDraw::LineSet::getGeoms () inline
Definition at line 124 of file HatchLine.h.
Referenced by TechDrawGui::PATPathMaker::lineSetToFillItems().
getInterval()
double TechDraw::LineSet::getInterval () inline
Definition at line 130 of file HatchLine.h.
Referenced by getPatternStartPoint().
getIntervalX()
double TechDraw::LineSet::getIntervalX () inline
Definition at line 131 of file HatchLine.h.
Referenced by getPatternStartPoint().
getIntervalY()
double TechDraw::LineSet::getIntervalY () inline
Definition at line 132 of file HatchLine.h.
Referenced by getPatternStartPoint().
getLineOrigin()
Base::Vector3d TechDraw::LineSet::getLineOrigin ()
getMaxX()
double LineSet::getMaxX ()
Definition at line 60 of file HatchLine.cpp.
References xMax, xMin, yMax, and yMin.
getMaxY()
double LineSet::getMaxY ()
Definition at line 67 of file HatchLine.cpp.
References xMax, xMin, yMax, and yMin.
getMinX()
double LineSet::getMinX ()
Definition at line 46 of file HatchLine.cpp.
References xMax, xMin, yMax, and yMin.
Referenced by calcApparentStart(), and findAtomStart().
getMinY()
double LineSet::getMinY ()
Definition at line 53 of file HatchLine.cpp.
References xMax, xMin, yMax, and yMin.
Referenced by calcApparentStart(), and findAtomStart().
getOffset()
double TechDraw::LineSet::getOffset () inline
Definition at line 127 of file HatchLine.h.
Referenced by getPatternStartPoint().
getOrigin()
Base::Vector3d TechDraw::LineSet::getOrigin () inline
Definition at line 129 of file HatchLine.h.
Referenced by findAtomStart(), and getPatternStartPoint().
getPATLineSpec()
PATLineSpec TechDraw::LineSet::getPATLineSpec () inline
Definition at line 126 of file HatchLine.h.
Referenced by calcApparentStart().
getPatternLength()
double TechDraw::LineSet::getPatternLength () inline
Definition at line 134 of file HatchLine.h.
Referenced by getPatternStartPoint().
getPatternStartPoint()
Base::Vector3d LineSet::getPatternStartPoint (TechDraw::BaseGeomPtr g, double & offset, double scale = 1.0)
Definition at line 147 of file HatchLine.cpp.
References SCL.SimpleDataTypes::c, calcApparentStart(), findAtomStart(), toolbit-attributes::g, getAngle(), getInterval(), getIntervalX(), getIntervalY(), getOffset(), getOrigin(), getPatternLength(), getUnitDir(), getUnitOrtho(), FreeCADInit::Length, result, Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by TechDrawGui::PATPathMaker::lineSetToFillItems().
getSlope()
double TechDraw::LineSet::getSlope () inline
Definition at line 133 of file HatchLine.h.
Referenced by findAtomStart().
getUnitDir()
Base::Vector3d LineSet::getUnitDir ()
Definition at line 97 of file HatchLine.cpp.
References result.
Referenced by TechDrawGui::PATPathMaker::geomToStubbyLine(), getPatternStartPoint(), and getUnitOrtho().
getUnitOrtho()
Base::Vector3d LineSet::getUnitOrtho ()
Definition at line 111 of file HatchLine.cpp.
References getUnitDir(), result, unit(), DrawingExample::X, Point3D::x, DrawingExample::Y, and Point3D::y.
Referenced by getPatternStartPoint().
isDashed()
bool LineSet::isDashed ()
Definition at line 74 of file HatchLine.cpp.
References TechDraw::PATLineSpec::isDashed().
Referenced by TechDrawGui::PATPathMaker::lineSetToFillItems().
setBBox()
void TechDraw::LineSet::setBBox (const Bnd_Box & bb) inline
Definition at line 120 of file HatchLine.h.
setEdges()
void TechDraw::LineSet::setEdges (std::vector< TopoDS_Edge > e) inline
Definition at line 118 of file HatchLine.h.
References SCL.SimpleDataTypes::e.
setGeoms()
void TechDraw::LineSet::setGeoms (std::vector< TechDraw::BaseGeomPtr > g) inline
Definition at line 119 of file HatchLine.h.
References toolbit-attributes::g.
setPATLineSpec()
void TechDraw::LineSet::setPATLineSpec (const PATLineSpec & s) inline
Definition at line 117 of file HatchLine.h.
References toolbit-attributes::s.
Referenced by TechDraw::DrawGeomHatch::makeLineSets().
The documentation for this class was generated from the following files:
HatchLine.h
HatchLine.cpp