FreeCAD: Gui::Dialog::ParameterBool Class Reference
Gui::Dialog::ParameterBool Class Reference
#include <DlgParameterImp.h>
Public Member Functions
ParameterBool (QTreeWidget *parent, QString label1, bool value, const Base::Reference< ParameterGrp > &hcGrp)
Constructor.
~ParameterBool () override
void changeValue () override
void appendToGroup () override
void removeFromGroup () override
Public Member Functions inherited from Gui::Dialog::ParameterValueItem
ParameterValueItem (QTreeWidget *parent, const Base::Reference< ParameterGrp > &hcGrp)
Constructor.
~ParameterValueItem () override
void setData (int column, int role, const QVariant &value) override
Protected Member Functions
void replace (const QString &oldName, const QString &newName) override
Additional Inherited Members
Protected Attributes inherited from Gui::Dialog::ParameterValueItem
Base::Reference< ParameterGrp > _hcGrp
Detailed Description
The ParameterBool class allows interaction with "boolean" parameter leaves.
Author
Werner Mayer
Definition at line 381 of file DlgParameterImp.h.
Constructor & Destructor Documentation
ParameterBool()
ParameterBool::ParameterBool (QTreeWidget * parent, QString label1, bool value, const Base::Reference< ParameterGrp > & hcGrp)
Constructor.
Definition at line 1339 of file DlgParameterImp.cpp.
References Gui::BitmapFactory().
~ParameterBool()
ParameterBool::~ParameterBool () override default
Member Function Documentation
appendToGroup()
void ParameterBool::appendToGroup () override virtual
Append this item as leaf to the parameter group.
Implements Gui::Dialog::ParameterValueItem.
Definition at line 1386 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::_hcGrp, ParameterGrp::SetBool(), and toolbit-attributes::val.
changeValue()
void ParameterBool::changeValue () override virtual
Opens an input dialog to change the value.
Implements Gui::Dialog::ParameterValueItem.
Definition at line 1353 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::_hcGrp, RobotExample::pos, ParameterGrp::SetBool(), and create_qrc::txt.
removeFromGroup()
void ParameterBool::removeFromGroup () override virtual
Remove the leaf from the parameter group.
Implements Gui::Dialog::ParameterValueItem.
Definition at line 1374 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::_hcGrp, and ParameterGrp::RemoveBool().
replace()
void ParameterBool::replace (const QString & oldName, const QString & newName) override protected virtual
Replaces the name of the leaf from oldName to newName.
Implements Gui::Dialog::ParameterValueItem.
Definition at line 1379 of file DlgParameterImp.cpp.
References Gui::Dialog::ParameterValueItem::_hcGrp, ParameterGrp::GetBool(), ParameterGrp::RemoveBool(), ParameterGrp::SetBool(), and toolbit-attributes::val.
The documentation for this class was generated from the following files:
DlgParameterImp.h
DlgParameterImp.cpp