FreeCAD: Gui::Dialog::DlgPreferencePackManagementImp Class Reference
Gui::Dialog::DlgPreferencePackManagementImp Class Reference
#include <DlgPreferencePackManagementImp.h>
Signals
void packVisibilityChanged ()
Public Member Functions
DlgPreferencePackManagementImp (QWidget *parent=nullptr)
~DlgPreferencePackManagementImp () override
Protected Slots
void deleteUserPack (const std::string &prefPackName)
void hideBuiltInPack (const std::string &prefPackName)
void hideInstalledPack (const std::string &addonName, const std::string &prefPackName)
void showEvent (QShowEvent *event) override
void showAddonManager ()
Detailed Description
Definition at line 48 of file DlgPreferencePackManagementImp.h.
Constructor & Destructor Documentation
DlgPreferencePackManagementImp()
DlgPreferencePackManagementImp::DlgPreferencePackManagementImp (QWidget * parent = nullptr)
Constructs a Gui::Dialog::DlgPreferencePackManagementImp as a child of 'parent'
Definition at line 43 of file DlgPreferencePackManagementImp.cpp.
References draftgeoutils.intersections::connect(), and showAddonManager().
~DlgPreferencePackManagementImp()
DlgPreferencePackManagementImp::~DlgPreferencePackManagementImp () override default
Member Function Documentation
deleteUserPack
void DlgPreferencePackManagementImp::deleteUserPack (const std::string & prefPackName) protected slot
Definition at line 154 of file DlgPreferencePackManagementImp.cpp.
References Gui::PreferencePackManager::deleteUserPack(), Gui::Application::Instance, packVisibilityChanged(), Gui::Application::prefPackManager(), result, showEvent(), and Path.Log::warning().
hideBuiltInPack
void DlgPreferencePackManagementImp::hideBuiltInPack (const std::string & prefPackName) protected slot
Definition at line 167 of file DlgPreferencePackManagementImp.cpp.
References Gui::Application::Instance, packVisibilityChanged(), Gui::Application::prefPackManager(), showEvent(), and Gui::PreferencePackManager::toggleVisibility().
hideInstalledPack
void DlgPreferencePackManagementImp::hideInstalledPack (const std::string & addonName, const std::string & prefPackName) protected slot
Definition at line 174 of file DlgPreferencePackManagementImp.cpp.
References Gui::Application::Instance, packVisibilityChanged(), Gui::Application::prefPackManager(), showEvent(), and Gui::PreferencePackManager::toggleVisibility().
packVisibilityChanged
void Gui::Dialog::DlgPreferencePackManagementImp::packVisibilityChanged () signal
Referenced by deleteUserPack(), hideBuiltInPack(), hideInstalledPack(), and Gui::Dialog::DlgSettingsGeneral::onManagePreferencePacksClicked().
showAddonManager
void DlgPreferencePackManagementImp::showAddonManager () protected slot
Definition at line 181 of file DlgPreferencePackManagementImp.cpp.
References Gui::Application::commandManager(), App::GetApplication(), App::Application::GetParameterGroupByPath(), Gui::Application::Instance, Gui::CommandManager::runCommandByName(), and ParameterGrp::SetInt().
Referenced by DlgPreferencePackManagementImp().
showEvent
void DlgPreferencePackManagementImp::showEvent (QShowEvent * event) override protected slot
Definition at line 51 of file DlgPreferencePackManagementImp.cpp.
References Gui::PreferencePackManager::getPacksFromDirectory(), Gui::PreferencePackManager::getResourcePreferencePacksPath(), Gui::PreferencePackManager::getSavedPreferencePacksPath(), Gui::Application::Instance, mod, Gui::PreferencePackManager::modPaths(), Base::FileInfo::pathToString(), and Gui::Application::prefPackManager().
Referenced by deleteUserPack(), hideBuiltInPack(), and hideInstalledPack().
The documentation for this class was generated from the following files:
DlgPreferencePackManagementImp.h
DlgPreferencePackManagementImp.cpp