FreeCAD: src.Mod.Show.Containers Namespace Reference
src.Mod.Show.Containers Namespace Reference
Classes
class Container
class ContainerError
class ContainerTreeError
class NotAContainerError
Functions
def isAContainer (obj, links_too=False)
def ContainerOf (obj)
def getVisGroupOf (obj)
def ContainerChain (feat)
def CSChain (feat)
def VisGroupChain (feat)
Function Documentation
ContainerChain()
def src.Mod.Show.Containers.ContainerChain (feat)
ContainerChain(feat): container path to feat (not including feat itself).
Last container directly contains the feature.
Example of output:  [<document>,<SuperPart>,<Part>,<Body>]
Definition at line 224 of file Containers.py.
References src.Mod.Show.Containers.isAContainer().
Referenced by src.Mod.Show.Containers.CSChain(), src.Mod.Show.Containers.Container.hasObjectRecursive(), and src.Mod.Show.Containers.VisGroupChain().
ContainerOf()
def src.Mod.Show.Containers.ContainerOf (obj)
ContainerOf(obj): returns the container that immediately has obj.
Definition at line 204 of file Containers.py.
References src.Mod.Show.Containers.isAContainer().
CSChain()
def src.Mod.Show.Containers.CSChain (feat)
Definition at line 252 of file Containers.py.
References src.Mod.Show.Containers.ContainerChain().
getVisGroupOf()
def src.Mod.Show.Containers.getVisGroupOf (obj)
Definition at line 218 of file Containers.py.
References src.Mod.Show.Containers.VisGroupChain().
isAContainer()
def src.Mod.Show.Containers.isAContainer (obj, links_too = False)
isAContainer(obj, links_too): returns True if obj is an object container, such as
Group, Part, Body. The important characteristic of an object being a
container is that it can be activated to receive new objects. Documents
are considered containers, too.
If links_too, App::Link objects are considered containers, too. Then, container tree
isn't necessarily a tree.
Definition at line 184 of file Containers.py.
Referenced by src.Mod.Show.Containers.ContainerChain(), src.Mod.Show.Containers.ContainerOf(), src.Mod.Show.mTempoVis.TempoVis.get_all_dependent(), src.Mod.Show.Containers.Container.getDynamicChildren(), src.Mod.Show.Containers.Container.hasObjectRecursive(), and src.Mod.Show.Containers.Container.self_check().
VisGroupChain()
def src.Mod.Show.Containers.VisGroupChain (feat)
Definition at line 257 of file Containers.py.
References src.Mod.Show.Containers.ContainerChain().
Referenced by src.Mod.Show.Containers.getVisGroupOf().