FreeCAD: BOPTools.SplitFeatures.FeatureXOR Class Reference
BOPTools.SplitFeatures.FeatureXOR Class Reference
Public Member Functions
def __init__ (self, obj)
def execute (self, selfobj)
Public Attributes
Type
Detailed Description
The XOR feature object.
Definition at line 407 of file SplitFeatures.py.
Constructor & Destructor Documentation
__init__()
def BOPTools.SplitFeatures.FeatureXOR.__init__ (self, obj)
Definition at line 410 of file SplitFeatures.py.
Member Function Documentation
execute()
def BOPTools.SplitFeatures.FeatureXOR.execute (self, selfobj)
Definition at line 419 of file SplitFeatures.py.
Referenced by src.Mod.PartDesign.Scripts.Spring.MySpring.onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped.onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder.onChanged(), and FeaturePython.DistanceBolt.onChanged().
Member Data Documentation
Type
BOPTools.SplitFeatures.FeatureXOR.Type
Definition at line 417 of file SplitFeatures.py.
The documentation for this class was generated from the following file:
SplitFeatures.py