FreeCAD: MatGui::Array2DModel Class Reference
MatGui::Array2DModel Class Reference
#include <ArrayModel.h>
Public Member Functions
Array2DModel (const std::shared_ptr< Materials::MaterialProperty > &property=nullptr, const std::shared_ptr< Materials::Material2DArray > &value=nullptr, QObject *parent=nullptr)
~Array2DModel () override=default
int rowCount (const QModelIndex &parent=QModelIndex()) const override
bool newRow (const QModelIndex &index) const override
void deleteRow (const QModelIndex &index)
int columnCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole) override
Qt::ItemFlags flags (const QModelIndex &index) const override
bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex()) override
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex()) override
bool insertColumns (int column, int count, const QModelIndex &parent=QModelIndex()) override
bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex()) override
Public Member Functions inherited from MatGui::AbstractArrayModel
AbstractArrayModel (QObject *parent=nullptr)
~AbstractArrayModel () override=default
Detailed Description
Definition at line 66 of file ArrayModel.h.
Constructor & Destructor Documentation
Array2DModel()
Array2DModel::Array2DModel (const std::shared_ptr< Materials::MaterialProperty > & property = nullptr, const std::shared_ptr< Materials::Material2DArray > & value = nullptr, QObject * parent = nullptr) explicit
Definition at line 49 of file ArrayModel.cpp.
~Array2DModel()
MatGui::Array2DModel::~Array2DModel () override default
Member Function Documentation
columnCount()
int Array2DModel::columnCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 77 of file ArrayModel.cpp.
References Init::parent.
Referenced by insertRows().
data()
QVariant Array2DModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 84 of file ArrayModel.cpp.
References App::ExpressionParser::column, Materials::MaterialValue::getQuantityFormat(), src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::Quantity, Materials::MaterialValue::Quantity, and Base::Quantity::setFormat().
deleteRow()
void Array2DModel::deleteRow (const QModelIndex & index)
Definition at line 71 of file ArrayModel.cpp.
References removeRows().
flags()
Qt::ItemFlags Array2DModel::flags (const QModelIndex & index) const override
Definition at line 142 of file ArrayModel.cpp.
headerData()
QVariant Array2DModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const override
Definition at line 110 of file ArrayModel.cpp.
References App::ExpressionParser::column, Sketcher::Horizontal, rowCount(), and Sketcher::Vertical.
insertColumns()
bool Array2DModel::insertColumns (int column, int count, const QModelIndex & parent = QModelIndex()) override
Definition at line 181 of file ArrayModel.cpp.
References App::ExpressionParser::column, src.Mod.AddonManager.NetworkManager::count, and Init::parent.
insertRows()
bool Array2DModel::insertRows (int row, int count, const QModelIndex & parent = QModelIndex()) override
Definition at line 149 of file ArrayModel.cpp.
References columnCount(), src.Mod.AddonManager.NetworkManager::count, SplineSurface::i, and Init::parent.
Referenced by setData().
newRow()
bool Array2DModel::newRow (const QModelIndex & index) const override virtual
Implements MatGui::AbstractArrayModel.
Definition at line 66 of file ArrayModel.cpp.
removeColumns()
bool Array2DModel::removeColumns (int column, int count, const QModelIndex & parent = QModelIndex()) override
Definition at line 190 of file ArrayModel.cpp.
References App::ExpressionParser::column, src.Mod.AddonManager.NetworkManager::count, and Init::parent.
removeRows()
bool Array2DModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex()) override
Definition at line 168 of file ArrayModel.cpp.
References src.Mod.AddonManager.NetworkManager::count, SplineSurface::i, and Init::parent.
Referenced by deleteRow().
rowCount()
int Array2DModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 57 of file ArrayModel.cpp.
References Init::parent.
Referenced by headerData().
setData()
bool Array2DModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) override
Definition at line 129 of file ArrayModel.cpp.
References insertRows().
The documentation for this class was generated from the following files:
ArrayModel.h
ArrayModel.cpp