FreeCAD: MeshGui::RemoveComponents Class Reference
MeshGui::RemoveComponents Class Reference
#include <RemoveComponents.h>
Public Member Functions
RemoveComponents (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~RemoveComponents () override
void reject ()
void deleteSelection ()
void invertSelection ()
void onSelectRegionClicked ()
void onSelectAllClicked ()
void onSelectComponentsClicked ()
void onSelectTriangleClicked ()
void onDeselectRegionClicked ()
void onDeselectAllClicked ()
void onDeselectComponentsClicked ()
void onDeselectTriangleClicked ()
void onVisibleTrianglesToggled (bool)
void onScreenTrianglesToggled (bool)
void onSelectCompToggled (bool)
void onDeselectCompToggled (bool)
Protected Member Functions
void changeEvent (QEvent *e) override
Detailed Description
Non-modal dialog to de/select components, regions, the complete or single faces of a mesh and delete them.
Author
Werner Mayer
Definition at line 62 of file RemoveComponents.h.
Constructor & Destructor Documentation
RemoveComponents()
RemoveComponents::RemoveComponents (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Definition at line 38 of file RemoveComponents.cpp.
References Gui::SelectionSingleton::clearSelection(), Gui::Selection(), MeshGui::MeshSelection::setCheckOnlyPointToUserTriangles(), MeshGui::MeshSelection::setCheckOnlyVisibleTriangles(), and MeshGui::MeshSelection::setEnabledViewerSelection().
~RemoveComponents()
RemoveComponents::~RemoveComponents () override
Definition at line 55 of file RemoveComponents.cpp.
Member Function Documentation
changeEvent()
void RemoveComponents::changeEvent (QEvent * e) override protected
Definition at line 91 of file RemoveComponents.cpp.
References SCL.SimpleDataTypes::e.
deleteSelection()
void RemoveComponents::deleteSelection ()
Definition at line 155 of file RemoveComponents.cpp.
References Gui::Application::activeDocument(), MeshGui::MeshSelection::deleteSelection(), toolbit-attributes::doc, Gui::Application::Instance, and Arch::QT_TRANSLATE_NOOP.
Referenced by MeshGui::TaskRemoveComponents::clicked().
invertSelection()
void RemoveComponents::invertSelection ()
Definition at line 172 of file RemoveComponents.cpp.
References MeshGui::MeshSelection::invertSelection().
Referenced by MeshGui::TaskRemoveComponents::clicked().
onDeselectAllClicked()
void RemoveComponents::onDeselectAllClicked ()
Definition at line 115 of file RemoveComponents.cpp.
References MeshGui::MeshSelection::clearSelection().
onDeselectComponentsClicked()
void RemoveComponents::onDeselectComponentsClicked ()
Definition at line 128 of file RemoveComponents.cpp.
References MeshGui::MeshSelection::deselectComponent().
onDeselectCompToggled()
void RemoveComponents::onDeselectCompToggled (bool on)
Definition at line 150 of file RemoveComponents.cpp.
References MeshGui::MeshSelection::setRemoveComponentOnClick().
onDeselectRegionClicked()
void RemoveComponents::onDeselectRegionClicked ()
Definition at line 104 of file RemoveComponents.cpp.
References MeshGui::MeshSelection::startDeselection().
onDeselectTriangleClicked()
void RemoveComponents::onDeselectTriangleClicked ()
Definition at line 183 of file RemoveComponents.cpp.
References MeshGui::MeshSelection::deselectTriangle(), and MeshGui::MeshSelection::setRemoveComponentOnClick().
onScreenTrianglesToggled()
void RemoveComponents::onScreenTrianglesToggled (bool on)
Definition at line 140 of file RemoveComponents.cpp.
References MeshGui::MeshSelection::setCheckOnlyPointToUserTriangles().
onSelectAllClicked()
void RemoveComponents::onSelectAllClicked ()
Definition at line 109 of file RemoveComponents.cpp.
References MeshGui::MeshSelection::fullSelection().
onSelectComponentsClicked()
void RemoveComponents::onSelectComponentsClicked ()
Definition at line 121 of file RemoveComponents.cpp.
References MeshGui::MeshSelection::selectComponent().
onSelectCompToggled()
void RemoveComponents::onSelectCompToggled (bool on)
Definition at line 145 of file RemoveComponents.cpp.
References MeshGui::MeshSelection::setAddComponentOnClick().
onSelectRegionClicked()
void RemoveComponents::onSelectRegionClicked ()
Definition at line 99 of file RemoveComponents.cpp.
References MeshGui::MeshSelection::startSelection().
onSelectTriangleClicked()
void RemoveComponents::onSelectTriangleClicked ()
Definition at line 177 of file RemoveComponents.cpp.
References MeshGui::MeshSelection::selectTriangle(), and MeshGui::MeshSelection::setAddComponentOnClick().
onVisibleTrianglesToggled()
void RemoveComponents::onVisibleTrianglesToggled (bool on)
Definition at line 135 of file RemoveComponents.cpp.
References MeshGui::MeshSelection::setCheckOnlyVisibleTriangles().
reject()
void RemoveComponents::reject ()
Definition at line 189 of file RemoveComponents.cpp.
References MeshGui::MeshSelection::clearSelection(), and MeshGui::MeshSelection::setEnabledViewerSelection().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), MeshGui::TaskRemoveComponents::clicked(), and MeshGui::RemoveComponentsDialog::reject().
The documentation for this class was generated from the following files:
RemoveComponents.h
RemoveComponents.cpp