FreeCAD: Gui::Dialog::PreferencesPageItem Class Reference
Gui::Dialog::PreferencesPageItem Class Reference
#include <DlgPreferencesImp.h>
Public Member Functions
QWidget * getWidget () const
void setWidget (QWidget *widget)
bool isExpanded () const
void setExpanded (bool expanded)
Static Public Attributes
static constexpr char const * PropertyName = "SettingsPageItem"
Detailed Description
Definition at line 43 of file DlgPreferencesImp.h.
Member Function Documentation
getWidget()
QWidget * PreferencesPageItem::getWidget () const
Definition at line 81 of file DlgPreferencesImp.cpp.
Referenced by Gui::Dialog::DlgPreferencesImp::onPageSelected().
isExpanded()
bool PreferencesPageItem::isExpanded () const
Definition at line 96 of file DlgPreferencesImp.cpp.
setExpanded()
void PreferencesPageItem::setExpanded (bool expanded)
Definition at line 101 of file DlgPreferencesImp.cpp.
Referenced by Gui::Dialog::DlgPreferencesImp::onGroupCollapsed(), and Gui::Dialog::DlgPreferencesImp::onGroupExpanded().
setWidget()
void PreferencesPageItem::setWidget (QWidget * widget)
Definition at line 86 of file DlgPreferencesImp.cpp.
References PropertyName.
Member Data Documentation
PropertyName
constexpr char const* Gui::Dialog::PreferencesPageItem::PropertyName = "SettingsPageItem" static constexpr
Definition at line 52 of file DlgPreferencesImp.h.
Referenced by setWidget().
The documentation for this class was generated from the following files:
DlgPreferencesImp.h
DlgPreferencesImp.cpp