FreeCAD: Part::MapperHistory Struct Reference
Part::MapperHistory Struct Reference
#include <TopoShape.h>
Public Member Functions
Handle (BRepTools_History) history
MapperHistory (const Handle(BRepTools_History) &history)
MapperHistory (const Handle(BRepTools_ReShape) &reshape)
MapperHistory (ShapeFix_Root &fix)
const std::vector< TopoDS_Shape > & modified (const TopoDS_Shape &s) const override
Return a list of shape modified from the given input shape.
const std::vector< TopoDS_Shape > & generated (const TopoDS_Shape &s) const override
Return a list of shape generated from the given input shape.
Public Member Functions inherited from Part::TopoShape::Mapper
virtual ~Mapper ()
Additional Inherited Members
Public Attributes inherited from Part::TopoShape::Mapper
std::vector< TopoDS_Shape > _res
Helper vector for temporary storage of both generated and modified shapes.
Detailed Description
Shape mapper for BRepTools_History
Uses BRepTools_History::Modified/Generated() function to extract shape history for generating mapped element names
Definition at line 2748 of file TopoShape.h.
Constructor & Destructor Documentation
MapperHistory() [1/3]
Part::MapperHistory::MapperHistory (const Handle(BRepTools_History) & history) explicit
Referenced by FC_LOG_LEVEL_INIT().
MapperHistory() [2/3]
Part::MapperHistory::MapperHistory (const Handle(BRepTools_ReShape) & reshape) explicit
MapperHistory() [3/3]
Part::MapperHistory::MapperHistory (ShapeFix_Root & fix) explicit
Member Function Documentation
generated()
const std::vector<TopoDS_Shape>& Part::MapperHistory::generated (const TopoDS_Shape &) const override virtual
Return a list of shape generated from the given input shape.
Reimplemented from Part::TopoShape::Mapper.
Referenced by FC_LOG_LEVEL_INIT().
Handle()
Part::MapperHistory::Handle (BRepTools_History)
modified()
const std::vector<TopoDS_Shape>& Part::MapperHistory::modified (const TopoDS_Shape &) const override virtual
Return a list of shape modified from the given input shape.
Reimplemented from Part::TopoShape::Mapper.
Referenced by FC_LOG_LEVEL_INIT().
The documentation for this struct was generated from the following file:
TopoShape.h