FreeCAD: PartGui::Mirroring Class Reference
PartGui::Mirroring Class Reference
#include <Mirroring.h>
Public Member Functions
Mirroring (QWidget *parent=nullptr)
~Mirroring () override
bool accept ()
bool reject ()
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Protected Member Functions
void changeEvent (QEvent *e) override
Detailed Description
Definition at line 38 of file Mirroring.h.
Constructor & Destructor Documentation
Mirroring()
Mirroring::Mirroring (QWidget * parent = nullptr) explicit
Definition at line 181 of file Mirroring.cpp.
References Gui::SelectionSingleton::addSelectionGate(), Gui::ItemViewSelection::applyFrom(), draftgeoutils.intersections::connect(), Base::Persistence::getClassTypeId(), draftutils.utils::getObjectsOfType, Base::Unit::Length, and Gui::Selection().
~Mirroring()
Mirroring::~Mirroring () override default
Member Function Documentation
accept()
bool Mirroring::accept ()
Definition at line 277 of file Mirroring.cpp.
References Gui::Command::App, App::Document::commitTransaction(), copyVisual, src.Mod.AddonManager.NetworkManager::count, App::Document::countObjectsOfType(), Base::Tools::escapedUnicodeFromUtf8(), App::GetApplication(), App::Application::getDocument(), Gui::SelectionSingleton::getSelectionEx(), src.Mod.Test.testPathArray::items, NavigationIndicatorGui::label, App::Document::openTransaction(), RobotExample::pos, src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression, App::Document::recompute(), Gui::SelectionSingleton::rmvSelectionGate(), runCommand, Path.Dressup.Utils::selection(), and Gui::Selection().
Referenced by PartGui::TaskMirroring::accept().
changeEvent()
void Mirroring::changeEvent (QEvent * e) override protected
Definition at line 220 of file Mirroring.cpp.
References SCL.SimpleDataTypes::e.
reject()
bool Mirroring::reject ()
Definition at line 271 of file Mirroring.cpp.
References Gui::SelectionSingleton::rmvSelectionGate(), and Gui::Selection().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and PartGui::TaskMirroring::reject().
The documentation for this class was generated from the following files:
Mirroring.h
Mirroring.cpp