FreeCAD: Path.Base.Generator.helix Namespace Reference
Path.Base.Generator.helix Namespace Reference
Functions
def generate (edge, hole_radius, step_down, step_over, tool_diameter, inner_radius=0.0, direction="CW", startAt="Outside")
Function Documentation
generate()
def Path.Base.Generator.helix.generate (edge, hole_radius, step_down, step_over, tool_diameter, inner_radius = 0.0, direction = "CW", startAt = "Outside")
generate(edge, hole_radius, inner_radius, step_over) ... generate helix commands.
hole_radius, inner_radius: outer and inner radius of the hole
step_over: step over % of tool diameter
Definition at line 41 of file helix.py.
References KDL.abs(), Path.Log.debug(), KDL.max(), Path.Log.track(), and Path.Post.scripts.grbl_post.type.