FreeCAD: femexamples.ccx_cantilever_beam_pipe Namespace Reference
femexamples.ccx_cantilever_beam_pipe Namespace Reference
Functions
def get_information ()
def get_explanation (header="")
def setup (doc=None, solvertype="ccxtools")
Function Documentation
get_explanation()
def femexamples.ccx_cantilever_beam_pipe.get_explanation (header = "")
Definition at line 43 of file ccx_cantilever_beam_pipe.py.
Referenced by femexamples.ccx_cantilever_beam_pipe.setup().
get_information()
def femexamples.ccx_cantilever_beam_pipe.get_information ()
Definition at line 31 of file ccx_cantilever_beam_pipe.py.
Referenced by femexamples.ccx_cantilever_beam_pipe.setup().
setup()
def femexamples.ccx_cantilever_beam_pipe.setup (doc = None, solvertype = "ccxtools")
Definition at line 85 of file ccx_cantilever_beam_pipe.py.
References femexamples.ccx_cantilever_beam_pipe.get_explanation(), femexamples.ccx_cantilever_beam_pipe.get_information(), femexamples.manager.init_doc(), and femexamples.ccx_cantilever_base_edge.setup_cantilever_base_edge().