FreeCAD: MeshCore::MeshCurvatureSurfaceSegment Class Reference
MeshCore::MeshCurvatureSurfaceSegment Class Reference
#include <Segmentation.h>
Public Member Functions
MeshCurvatureSurfaceSegment (const std::vector< CurvatureInfo > &ci, unsigned long minFacets)
const CurvatureInfo & GetInfo (std::size_t pos) const
Public Member Functions inherited from MeshCore::MeshSurfaceSegment
MeshSurfaceSegment (unsigned long minFacets)
virtual ~MeshSurfaceSegment ()=default
MeshSurfaceSegment (const MeshSurfaceSegment &)=delete
MeshSurfaceSegment (MeshSurfaceSegment &&)=delete
MeshSurfaceSegment & operator= (const MeshSurfaceSegment &)=delete
MeshSurfaceSegment & operator= (MeshSurfaceSegment &&)=delete
virtual bool TestFacet (const MeshFacet &rclFacet) const =0
virtual const char * GetType () const =0
virtual void Initialize (FacetIndex)
virtual bool TestInitialFacet (FacetIndex) const
virtual void AddFacet (const MeshFacet &rclFacet)
void AddSegment (const std::vector< FacetIndex > &)
const std::vector< MeshSegment > & GetSegments () const
MeshSegment FindSegment (FacetIndex) const
Detailed Description
Definition at line 281 of file Mesh/App/Core/Segmentation.h.
Constructor & Destructor Documentation
MeshCurvatureSurfaceSegment()
MeshCore::MeshCurvatureSurfaceSegment::MeshCurvatureSurfaceSegment (const std::vector< CurvatureInfo > & ci, unsigned long minFacets) inline
Definition at line 284 of file Mesh/App/Core/Segmentation.h.
Member Function Documentation
GetInfo()
const CurvatureInfo& MeshCore::MeshCurvatureSurfaceSegment::GetInfo (std::size_t pos) const inline
Definition at line 289 of file Mesh/App/Core/Segmentation.h.
Referenced by MeshCore::MeshCurvaturePlanarSegment::TestFacet(), MeshCore::MeshCurvatureCylindricalSegment::TestFacet(), MeshCore::MeshCurvatureSphericalSegment::TestFacet(), and MeshCore::MeshCurvatureFreeformSegment::TestFacet().
The documentation for this class was generated from the following file:
Mesh/App/Core/Segmentation.h