FreeCAD: SketcherGui::ElementItemDelegate Class Reference
SketcherGui::ElementItemDelegate Class Reference
Public Types
enum SubControl : int {
CheckBox, LineSelect, StartSelect, EndSelect,
MidSelect, Label
}
Enum containing all controls rendered in this item. Controls in that enum MUST be in order.
Signals
void itemHovered (QModelIndex)
void itemChecked (QModelIndex, Qt::CheckState state)
Public Member Functions
ElementItemDelegate (ElementView *parent)
~ElementItemDelegate () override=default
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const override
bool editorEvent (QEvent *event, QAbstractItemModel *model, const QStyleOptionViewItem &option, const QModelIndex &index) override
ElementItem * getElementItem (const QModelIndex &index) const
QRect subControlRect (SubControl element, const QStyleOptionViewItem &option, const QModelIndex &index) const
void drawSubControl (SubControl element, QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
Public Attributes
const int gap = 4
Detailed Description
Definition at line 114 of file TaskSketcherElements.cpp.
Member Enumeration Documentation
SubControl
enum SketcherGui::ElementItemDelegate::SubControl : int
Enum containing all controls rendered in this item. Controls in that enum MUST be in order.
Enumerator
CheckBox
LineSelect
StartSelect
EndSelect
MidSelect
Label
Definition at line 119 of file TaskSketcherElements.cpp.
Constructor & Destructor Documentation
ElementItemDelegate()
ElementItemDelegate::ElementItemDelegate (ElementView * parent) explicit
Definition at line 874 of file TaskSketcherElements.cpp.
~ElementItemDelegate()
SketcherGui::ElementItemDelegate::~ElementItemDelegate () override default
Member Function Documentation
drawSubControl()
void ElementItemDelegate::drawSubControl (SubControl element, QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const
Definition at line 947 of file TaskSketcherElements.cpp.
References SketcherGui::ElementItem::canBeHidden(), Sketcher::end, EndSelect, SketcherGui::ElementItem::GeometryType, getElementItem(), ElementWidgetIcons::getIcon(), SketcherGui::ElementItem::isGeometryPreselected(), SketcherGui::ElementItem::isGeometrySelected(), SketcherGui::ElementItem::isVisible(), Label, SketcherGui::ElementItem::label, LineSelect, Sketcher::mid, MidSelect, Sketcher::none, RobotExample::pos, Sketcher::start, StartSelect, SketcherGui::ElementItem::State, and subControlRect().
Referenced by paint().
editorEvent()
bool ElementItemDelegate::editorEvent (QEvent * event, QAbstractItemModel * model, const QStyleOptionViewItem & option, const QModelIndex & index) override
Definition at line 1051 of file TaskSketcherElements.cpp.
References SketcherGui::ElementItem::canBeHidden(), SketcherGui::ElementItem::clickedOn, SketcherGui::edge, SketcherGui::end, SketcherGui::ElementItem::GeometryType, Base::Persistence::getClassTypeId(), getElementItem(), SketcherGui::ElementItem::hovered, SketcherGui::ElementItem::isVisible(), itemChecked(), itemHovered(), SketcherGui::mid, RobotExample::pos, SketcherGui::ElementItem::rightClicked, SketcherGui::start, and subControlRect().
getElementItem()
ElementItem * ElementItemDelegate::getElementItem (const QModelIndex & index) const
Definition at line 1096 of file TaskSketcherElements.cpp.
References SketcherGui::ElementView::itemFromIndex(), and Init::parent.
Referenced by drawSubControl(), editorEvent(), and paint().
itemChecked
void SketcherGui::ElementItemDelegate::itemChecked (QModelIndex , Qt::CheckState state) signal
Referenced by editorEvent(), and SketcherGui::ElementView::ElementView().
itemHovered
void SketcherGui::ElementItemDelegate::itemHovered (QModelIndex) signal
Referenced by editorEvent(), and SketcherGui::ElementView::ElementView().
paint()
void ElementItemDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const override
Definition at line 879 of file TaskSketcherElements.cpp.
References drawSubControl(), getElementItem(), SketcherGui::ElementItem::isEndPointSelected, SketcherGui::ElementItem::isLineSelected, SketcherGui::ElementItem::isMidPointSelected, and SketcherGui::ElementItem::isStartingPointSelected.
subControlRect()
QRect ElementItemDelegate::subControlRect (SubControl element, const QStyleOptionViewItem & option, const QModelIndex & index) const
Definition at line 910 of file TaskSketcherElements.cpp.
References gap, and RobotExample::pos.
Referenced by drawSubControl(), and editorEvent().
Member Data Documentation
gap
const int SketcherGui::ElementItemDelegate::gap = 4
Definition at line 141 of file TaskSketcherElements.cpp.
Referenced by subControlRect().
The documentation for this class was generated from the following file:
TaskSketcherElements.cpp