FreeCAD: MeshCore::MeshGeomEdge Class Reference
MeshCore::MeshGeomEdge Class Reference
#include <Elements.h>
Public Member Functions
MeshGeomEdge ()=default
bool ContainedByOrIntersectBoundingBox (const Base::BoundBox3f &rclBB) const
Base::BoundBox3f GetBoundBox () const
bool IntersectBoundingBox (const Base::BoundBox3f &rclBB) const
bool IntersectWithLine (const Base::Vector3f &rclPt, const Base::Vector3f &rclDir, Base::Vector3f &rclRes) const
bool IntersectWithEdge (const MeshGeomEdge &edge, Base::Vector3f &res) const
bool IntersectWithPlane (const Base::Vector3f &rclPt, const Base::Vector3f &rclDir, Base::Vector3f &rclRes) const
void ProjectPointToLine (const Base::Vector3f &rclPoint, Base::Vector3f &rclProj) const
void ClosestPointsToLine (const Base::Vector3f &linePt, const Base::Vector3f &lineDir, Base::Vector3f &rclPnt1, Base::Vector3f &rclPnt2) const
bool IsPointOf (const Base::Vector3f &rclPoint, float fDistance) const
bool IsProjectionPointOf (const Base::Vector3f &point) const
bool IsParallel (const MeshGeomEdge &edge) const
bool IsCollinear (const MeshGeomEdge &edge) const
Public Attributes
Base::Vector3f _aclPoints [2]
bool _bBorder {false}
Detailed Description
The MeshGeomEdge class is geometric counterpart to MeshEdge that holds the geometric data points of an edge.
Definition at line 205 of file Elements.h.
Constructor & Destructor Documentation
MeshGeomEdge()
MeshCore::MeshGeomEdge::MeshGeomEdge () default
Member Function Documentation
ClosestPointsToLine()
void MeshGeomEdge::ClosestPointsToLine (const Base::Vector3f & linePt, const Base::Vector3f & lineDir, Base::Vector3f & rclPnt1, Base::Vector3f & rclPnt2) const
Get the closest points rclPnt1 and rclPnt2 of the line defined by this edge and the line defined by rclPt and rclDir. If the two points are identical then both lines intersect each other.
Definition at line 387 of file Elements.cpp.
References Base::Vector3< float_type >::Cross(), SCL.SimpleDataTypes::e, Base::Vector3< float_type >::GetAngle(), toolbit-attributes::s, and InitGui::t.
ContainedByOrIntersectBoundingBox()
bool MeshGeomEdge::ContainedByOrIntersectBoundingBox (const Base::BoundBox3f & rclBB) const
Checks if the edge is inside the bounding box or intersects with it.
Definition at line 183 of file Elements.cpp.
References Base::BoundBox3< Precision >::IsInBox().
GetBoundBox()
Base::BoundBox3f MeshGeomEdge::GetBoundBox () const
Returns the bounding box of the edge.
Definition at line 206 of file Elements.cpp.
IntersectBoundingBox()
bool MeshGeomEdge::IntersectBoundingBox (const Base::BoundBox3f & rclBB) const
Checks if the edge intersects with the given bounding box.
Definition at line 211 of file Elements.cpp.
References RobotExample::A, RobotExample::B, exportCSG::center(), Base::BoundBox3< Precision >::GetCenter(), Wm4::Vector3< Real >::Length(), Base::BoundBox3< Precision >::LengthX(), Base::BoundBox3< Precision >::LengthY(), Base::BoundBox3< Precision >::LengthZ(), Wm4::Vector3< Real >::Normalize(), buildPsets::p, Wm4::IntrSegment3Box3< Real >::Test(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
IntersectWithEdge()
bool MeshGeomEdge::IntersectWithEdge (const MeshGeomEdge & edge, Base::Vector3f & res) const
Calculates the intersection point of an edge with this edge. The intersection must be inside both edges. If there is no intersection false is returned.
Definition at line 304 of file Elements.cpp.
References Base::Vector3< float_type >::Cross(), Base::Vector3< float_type >::DistanceToPlane(), Base::Vector3< float_type >::Dot(), SCL.SimpleDataTypes::e, Base::Vector3< float_type >::IsNull(), buildPsets::p, toolbit-attributes::s, Base::Vector3< float_type >::Sqr(), InitGui::t, buildPsets::u, and TestSpreadsheet::v.
Referenced by MeshCore::MeshGeomFacet::IntersectWithFacet().
IntersectWithLine()
bool MeshGeomEdge::IntersectWithLine (const Base::Vector3f & rclPt, const Base::Vector3f & rclDir, Base::Vector3f & rclRes) const
Calculates the intersection point of the line defined by the base rclPt and the direction rclDir with the edge. The intersection must be inside the edge. If there is no intersection false is returned.
Definition at line 241 of file Elements.cpp.
References Base::Vector3< float_type >::Cross(), Base::Distance(), Base::Vector3< float_type >::DistanceToPlane(), SCL.SimpleDataTypes::e, Base::Vector3< float_type >::GetAngle(), and toolbit-attributes::s.
IntersectWithPlane()
bool MeshGeomEdge::IntersectWithPlane (const Base::Vector3f & rclPt, const Base::Vector3f & rclDir, Base::Vector3f & rclRes) const
Calculates the intersection point of the plane defined by the base rclPt and the direction rclDir with the edge. The intersection must be inside the edge. If there is no intersection false is returned.
Definition at line 358 of file Elements.cpp.
References SCL.SimpleDataTypes::b, InitGui::t, and buildPsets::u.
IsCollinear()
bool MeshGeomEdge::IsCollinear (const MeshGeomEdge & edge) const
Checks if the two edges are collinear.
Note
Collinear edges always are parallel.
Definition at line 293 of file Elements.cpp.
References Base::Vector3< float_type >::Cross(), and Base::Vector3< float_type >::IsNull().
IsParallel()
bool MeshGeomEdge::IsParallel (const MeshGeomEdge & edge) const
Checks if the two edges are parallel.
Note
Parallel edges could be collinear.
Definition at line 285 of file Elements.cpp.
References Base::Vector3< float_type >::Cross(), Base::Vector3< float_type >::IsNull(), and toolbit-attributes::s.
IsPointOf()
bool MeshGeomEdge::IsPointOf (const Base::Vector3f & rclPoint, float fDistance) const
Checks if the point is part of the edge. A point is regarded as part of an edge if the distance is lower than fDistance to the projected point of rclPoint on the edge.
Definition at line 430 of file Elements.cpp.
References Base::Distance(), Base::DistanceP2(), dot(), and InitGui::t.
IsProjectionPointOf()
bool MeshGeomEdge::IsProjectionPointOf (const Base::Vector3f & point) const
Checks if the projection point of point lies on the edge.
Definition at line 451 of file Elements.cpp.
References dot(), and updateLeaderLines::point.
ProjectPointToLine()
void MeshGeomEdge::ProjectPointToLine (const Base::Vector3f & rclPoint, Base::Vector3f & rclProj) const
Calculates the projection of a point onto the line defined by the edge. The caller must check if the projection point is inside the edge.
Definition at line 378 of file Elements.cpp.
References SurfaceTests.TestBlendCurve::vec.
Member Data Documentation
_aclPoints
Base::Vector3f MeshCore::MeshGeomEdge::_aclPoints[2]
Corner points
Definition at line 270 of file Elements.h.
_bBorder
bool MeshCore::MeshGeomEdge::_bBorder {false}
Set to true if border edge
Definition at line 271 of file Elements.h.
The documentation for this class was generated from the following files:
Elements.h
Elements.cpp