FreeCAD: App::ExpressionParser::ExpressionImporter Class Reference
App::ExpressionParser::ExpressionImporter Class Reference
Convenient class to mark begin of importing.
#include <ExpressionParser.h>
Public Member Functions
ExpressionImporter (Base::XMLReader &reader)
~ExpressionImporter ()
Static Public Member Functions
static Base::XMLReader * reader ()
Detailed Description
Convenient class to mark begin of importing.
Definition at line 629 of file ExpressionParser.h.
Constructor & Destructor Documentation
ExpressionImporter()
ExpressionParser::ExpressionImporter::ExpressionImporter (Base::XMLReader & reader) explicit
Definition at line 3474 of file Expression.cpp.
References _Reader, and reader().
~ExpressionImporter()
ExpressionParser::ExpressionImporter::~ExpressionImporter ()
Definition at line 3479 of file Expression.cpp.
References _Reader.
Member Function Documentation
reader()
Base::XMLReader * ExpressionParser::ExpressionImporter::reader () static
Definition at line 3484 of file Expression.cpp.
References _Reader.
Referenced by App::ObjectIdentifier::String::checkImport(), and ExpressionImporter().
The documentation for this class was generated from the following files:
ExpressionParser.h
Expression.cpp