FreeCAD: Gui::SoFCBoundingBox Class Reference
Gui::SoFCBoundingBox Class Reference
#include <SoFCBoundingBox.h>
Public Member Functions
SoFCBoundingBox ()
Static Public Member Functions
static void initClass ()
static void finish ()
Public Attributes
SoSFVec3f minBounds
SoSFVec3f maxBounds
SoSFBool coordsOn
SoSFBool dimensionsOn
Protected Member Functions
~SoFCBoundingBox () override
void GLRender (SoGLRenderAction *action) override
void generatePrimitives (SoAction *action) override
void computeBBox (SoAction *action, SbBox3f &box, SbVec3f &center) override
Detailed Description
A subclass of SoShape used to create an axis aligned wire frame box based on the minBounds and maxBounds fields. The class also has a field which can be toggled on or off for displaying text coordinate labels at the vertices of the box.
Note
Original source are taken from http://www.wheatchex.com/projects/openinventor/bbox/BoundingBox.h and http://www.wheatchex.com/projects/openinventor/bbox/BoundingBox.cpp
Date
November 12th, 2001
Author
Josh Grant
Definition at line 68 of file SoFCBoundingBox.h.
Constructor & Destructor Documentation
SoFCBoundingBox()
SoFCBoundingBox::SoFCBoundingBox ()
Definition at line 69 of file SoFCBoundingBox.cpp.
References bBoxEdges, coordsOn, dimensionsOn, SplineSurface::i, maxBounds, and minBounds.
~SoFCBoundingBox()
SoFCBoundingBox::~SoFCBoundingBox () override protected
Definition at line 122 of file SoFCBoundingBox.cpp.
Member Function Documentation
computeBBox()
void SoFCBoundingBox::computeBBox (SoAction * action, SbBox3f & box, SbVec3f & center) override protected
Definition at line 220 of file SoFCBoundingBox.cpp.
References MengerSponge::box, exportCSG::center(), SCL.SimpleDataTypes::f, maxBounds, and minBounds.
finish()
void SoFCBoundingBox::finish () static
Definition at line 226 of file SoFCBoundingBox.cpp.
Referenced by drafttaskpanels.task_polararray.TaskPanelPolarArray::accept(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::accept(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::accept(), draftguitools.gui_split.Split::action(), draftguitools.gui_splines.BSpline::action(), draftguitools.gui_beziers.BezCurve::action(), draftguitools.gui_lines.Line::action(), draftguitools.gui_subelements.SubelementHighlight::action(), draftguitools.gui_polygons.Polygon::action(), draftguitools.gui_rotate.Rotate::action(), draftguitools.gui_fillets.Fillet::action(), draftguitools.gui_move.Move::action(), draftguitools.gui_mirror.Mirror::action(), draftguitools.gui_stretch.Stretch::action(), draftguitools.gui_arcs.Arc::action(), draftguitools.gui_texts.Text::action(), draftguitools.gui_scale.Scale::action(), draftguitools.gui_rectangles.Rectangle::action(), draftguitools.gui_offset.Offset::action(), draftguitools.gui_ellipses.Ellipse::action(), draftguitools.gui_labels.Label::action(), draftguitools.gui_trimex.Trimex::action(), draftguitools.gui_beziers.CubicBezCurve::action(), draftguitools.gui_dimensions.Dimension::action(), draftguitools.gui_styles.ApplyStyle::Activated(), draftguitools.gui_join.Join::Activated(), draftguitools.gui_draft2sketch.Draft2Sketch::Activated(), draftguitools.gui_downgrade.Downgrade::Activated(), draftguitools.gui_upgrade.Upgrade::Activated(), draftguitools.gui_shape2dview.Shape2DView::Activated(), draftguitools.gui_facebinders.Facebinder::Activated(), draftguitools.gui_subelements.SubelementHighlight::Activated(), draftguitools.gui_wire2spline.WireToBSpline::Activated(), draftguitools.gui_clone.Clone::Activated(), draftguitools.gui_dimensions.Dimension::Activated(), draftguitools.gui_edit.Edit::Activated(), draftguitools.gui_selectplane.Draft_SelectPlane::check_selection(), DraftGui.DraftToolBar::checkSpecialChars(), draftguitools.gui_points.Point::click(), draftguitools.gui_orthoarray.OrthoArray::completed(), draftguitools.gui_polararray.PolarArray::completed(), draftguitools.gui_circulararray.CircularArray::completed(), draftguitools.gui_labels.Label::create(), bimcommands.BimText.BIM_Text::createObject(), draftguitools.gui_rectangles.Rectangle::createObject(), draftguitools.gui_ellipses.Ellipse::createObject(), draftguitools.gui_texts.Text::createObject(), draftviewproviders.view_text.ViewProviderText::createObject(), draftguitools.gui_stretch.Stretch::doStretch(), draftguitools.gui_fillets.Fillet::draw_arc(), draftguitools.gui_arcs.Arc::drawArc(), draftguitools.gui_polygons.Polygon::drawPolygon(), DraftGui.DraftToolBar::editUi(), DraftGui.DraftToolBar::escape(), Gui::SoFCDB::finish(), draftguitools.gui_move.Move::get_object_selection(), draftguitools.gui_rotate.Rotate::get_object_selection(), draftguitools.gui_scale.Scale::get_object_selection(), draftguitools.gui_arcs.Arc_3Points::getPoint(), draftguitools.gui_edit.Edit::keyPressed(), draftguitools.gui_dimensions.Dimension::numericInput(), draftguitools.gui_offset.Offset::numericRadius(), draftguitools.gui_rotate.Rotate::numericRadius(), draftguitools.gui_trimex.Trimex::numericRadius(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_align(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_auto(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_center(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_front(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_move(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_next(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_previous(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_side(), draftguitools.gui_selectplane.Draft_SelectPlane::on_click_top(), bimcommands.BimShape2DView.BIM_Shape2DView::proceed(), draftguitools.gui_join.Join::proceed(), draftguitools.gui_subelements.SubelementHighlight::proceed(), draftguitools.gui_draft2sketch.Draft2Sketch::proceed(), draftguitools.gui_downgrade.Downgrade::proceed(), bimcommands.BimSlab.BIM_Slab::proceed(), draftguitools.gui_upgrade.Upgrade::proceed(), draftguitools.gui_facebinders.Facebinder::proceed(), draftguitools.gui_pathtwistedarray.PathTwistedArray::proceed(), draftguitools.gui_shape2dview.Shape2DView::proceed(), draftguitools.gui_clone.Clone::proceed(), draftguitools.gui_split.Split::proceed(), draftguitools.gui_pointarray.PointArray::proceed(), draftguitools.gui_patharray.PathArray::proceed(), draftguitools.gui_trimex.Trimex::proceed(), draftguitools.gui_edit.Edit::proceed(), draftguitools.gui_selectplane.Draft_SelectPlane::reject(), drafttaskpanels.task_orthoarray.TaskPanelOrthoArray::reject(), drafttaskpanels.task_polararray.TaskPanelPolarArray::reject(), drafttaskpanels.task_circulararray.TaskPanelCircularArray::reject(), and draftguitools.gui_edit.Edit::setTrackers().
generatePrimitives()
void SoFCBoundingBox::generatePrimitives (SoAction * action) override protected
Definition at line 216 of file SoFCBoundingBox.cpp.
GLRender()
void SoFCBoundingBox::GLRender (SoGLRenderAction * action) override protected
Definition at line 127 of file SoFCBoundingBox.cpp.
References Path.Post.scripts.dynapath_4060_post::action, bBoxVerts, coordsOn, geoff_geometry::corner(), dimensionsOn, SCL.SimpleDataTypes::f, getValue(), SplineSurface::i, maxBounds, minBounds, Path.Post.scripts.refactored_centroid_post::str, and InitGui::t.
initClass()
void SoFCBoundingBox::initClass () static
Definition at line 64 of file SoFCBoundingBox.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
Member Data Documentation
coordsOn
SoSFBool Gui::SoFCBoundingBox::coordsOn
If true, the coordinates are displayed at each vertex
Definition at line 101 of file SoFCBoundingBox.h.
Referenced by GLRender(), Gui::ViewProviderGeometryObject::showBoundingBox(), and SoFCBoundingBox().
dimensionsOn
SoSFBool Gui::SoFCBoundingBox::dimensionsOn
If true, the dimensions are displayed in x,y and z direction
Definition at line 102 of file SoFCBoundingBox.h.
Referenced by GLRender(), Gui::ViewProviderGeometryObject::showBoundingBox(), and SoFCBoundingBox().
maxBounds
SoSFVec3f Gui::SoFCBoundingBox::maxBounds
maximum box coordinates
Definition at line 100 of file SoFCBoundingBox.h.
Referenced by computeBBox(), GLRender(), SoFCBoundingBox(), and Gui::ViewProviderGeometryObject::updateData().
minBounds
SoSFVec3f Gui::SoFCBoundingBox::minBounds
minimum box coordinates
Definition at line 99 of file SoFCBoundingBox.h.
Referenced by computeBBox(), GLRender(), SoFCBoundingBox(), and Gui::ViewProviderGeometryObject::updateData().
The documentation for this class was generated from the following files:
SoFCBoundingBox.h
SoFCBoundingBox.cpp