FreeCAD: Gui::Dialog::wbListItem Class Reference
Gui::Dialog::wbListItem Class Reference
Signals
void wbToggled (const QString &wbName, bool enabled)
Public Member Functions
wbListItem (const QString &wbName, bool enabled, bool startupWb, bool autoLoad, int index, QWidget *parent=nullptr)
~wbListItem () override
bool isEnabled ()
bool isAutoLoading ()
void setStartupWb (bool val)
void setShortcutLabel (int index)
Protected Slots
void onLoadClicked ()
void onWbToggled (bool checked)
Detailed Description
Definition at line 46 of file DlgSettingsWorkbenchesImp.cpp.
Constructor & Destructor Documentation
wbListItem()
wbListItem::wbListItem (const QString & wbName, bool enabled, bool startupWb, bool autoLoad, int index, QWidget * parent = nullptr) explicit
Definition at line 78 of file DlgSettingsWorkbenchesImp.cpp.
References draftgeoutils.intersections::connect(), Gui::WorkbenchManager::getWorkbench(), Gui::WorkbenchManager::instance(), Gui::Application::Instance, onLoadClicked(), onWbToggled(), Gui::Application::workbenchIcon(), Gui::Application::workbenchMenuText(), and Gui::Application::workbenchToolTip().
~wbListItem()
wbListItem::~wbListItem () override default
Member Function Documentation
isAutoLoading()
bool wbListItem::isAutoLoading ()
Definition at line 175 of file DlgSettingsWorkbenchesImp.cpp.
Referenced by Gui::Dialog::DlgSettingsWorkbenchesImp::saveSettings().
isEnabled()
bool wbListItem::isEnabled ()
Definition at line 170 of file DlgSettingsWorkbenchesImp.cpp.
Referenced by Gui::Dialog::DlgSettingsWorkbenchesImp::saveSettings(), draftguitools.gui_snapper.Snapper::setArchDims(), draftguitools.gui_snapper.Snapper::snapToAngles(), draftguitools.gui_snapper.Snapper::snapToCenter(), draftguitools.gui_snapper.Snapper::snapToCenterFace(), draftguitools.gui_snapper.Snapper::snapToCrossExtensions(), draftguitools.gui_snapper.Snapper::snapToDim(), draftguitools.gui_snapper.Snapper::snapToElines(), draftguitools.gui_snapper.Snapper::snapToEndpoints(), draftguitools.gui_snapper.Snapper::snapToExtensions(), draftguitools.gui_snapper.Snapper::snapToExtOrtho(), draftguitools.gui_snapper.Snapper::snapToExtPerpendicular(), draftguitools.gui_snapper.Snapper::snapToGrid(), draftguitools.gui_snapper.Snapper::snapToHold(), draftguitools.gui_snapper.Snapper::snapToIntersection(), draftguitools.gui_snapper.Snapper::snapToMidpoint(), draftguitools.gui_snapper.Snapper::snapToNear(), draftguitools.gui_snapper.Snapper::snapToNearFace(), draftguitools.gui_snapper.Snapper::snapToNearUnprojected(), draftguitools.gui_snapper.Snapper::snapToObject(), draftguitools.gui_snapper.Snapper::snapToOrtho(), draftguitools.gui_snapper.Snapper::snapToPerpendicular(), draftguitools.gui_snapper.Snapper::snapToPerpendicularFace(), draftguitools.gui_snapper.Snapper::snapToPolar(), draftguitools.gui_snapper.Snapper::snapToPolygon(), draftguitools.gui_snapper.Snapper::snapToSpecials(), draftguitools.gui_snapper.Snapper::snapToVertex(), draftguitools.gui_snapper.Snapper::toWP(), and Gui::Dialog::DlgSettingsWorkbenchesImp::wbToggled().
onLoadClicked
void wbListItem::onLoadClicked () protected slot
Definition at line 195 of file DlgSettingsWorkbenchesImp.cpp.
References Gui::Application::activateWorkbench(), Gui::WorkbenchManager::active(), Gui::WorkbenchManager::instance(), Gui::Application::Instance, and Gui::Workbench::name().
Referenced by wbListItem().
onWbToggled
void wbListItem::onWbToggled (bool checked) protected slot
Definition at line 207 of file DlgSettingsWorkbenchesImp.cpp.
References wbToggled().
Referenced by wbListItem().
setShortcutLabel()
void wbListItem::setShortcutLabel (int index)
Definition at line 189 of file DlgSettingsWorkbenchesImp.cpp.
Referenced by Gui::Dialog::DlgSettingsWorkbenchesImp::wbItemMoved().
setStartupWb()
void wbListItem::setStartupWb (bool val)
Definition at line 180 of file DlgSettingsWorkbenchesImp.cpp.
References toolbit-attributes::val.
Referenced by Gui::Dialog::DlgSettingsWorkbenchesImp::onStartWbChanged().
wbToggled
void Gui::Dialog::wbListItem::wbToggled (const QString & wbName, bool enabled) signal
Referenced by onWbToggled().
The documentation for this class was generated from the following file:
DlgSettingsWorkbenchesImp.cpp