FreeCAD: Gui::Dialog::ButtonView Class Reference
Gui::Dialog::ButtonView Class Reference
#include <DlgCustomizeSpaceball.h>
Public Slots
void goSelectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
void goChangedCommand (const QString &commandName)
Signals
void changeCommandSelection (const QString &commandName)
Public Member Functions
ButtonView (QWidget *parent=nullptr)
void selectButton (int number)
Detailed Description
Definition at line 43 of file DlgCustomizeSpaceball.h.
Constructor & Destructor Documentation
ButtonView()
ButtonView::ButtonView (QWidget * parent = nullptr) explicit
Definition at line 53 of file DlgCustomizeSpaceball.cpp.
Member Function Documentation
changeCommandSelection
void Gui::Dialog::ButtonView::changeCommandSelection (const QString & commandName) signal
Referenced by Gui::Dialog::DlgCustomizeSpaceball::DlgCustomizeSpaceball(), and goSelectionChanged().
goChangedCommand
void ButtonView::goChangedCommand (const QString & commandName) slot
Definition at line 73 of file DlgCustomizeSpaceball.cpp.
References Gui::Dialog::ButtonModel::setCommand().
Referenced by Gui::Dialog::DlgCustomizeSpaceball::DlgCustomizeSpaceball().
goSelectionChanged
void ButtonView::goSelectionChanged (const QItemSelection & selected, const QItemSelection & deselected) slot
Definition at line 64 of file DlgCustomizeSpaceball.cpp.
References changeCommandSelection(), Path.Op.Gui.Selection::select(), and DraftVecUtils::toString().
selectButton()
void ButtonView::selectButton (int number)
Definition at line 58 of file DlgCustomizeSpaceball.cpp.
Referenced by Gui::Dialog::DlgCustomizeSpaceball::event().
The documentation for this class was generated from the following files:
DlgCustomizeSpaceball.h
DlgCustomizeSpaceball.cpp