FreeCAD: TechDrawGui::QGICenterLine Class Reference
TechDrawGui::QGICenterLine Class Reference
#include <QGICenterLine.h>
Public Types
enum { Type = QGraphicsItem::UserType + 174 }
Public Types inherited from TechDrawGui::QGIDecoration
enum { Type = QGraphicsItem::UserType + 173 }
Public Member Functions
QGICenterLine ()
~QGICenterLine () override=default
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
void setBounds (double x1, double y1, double x2, double y2)
void draw () override
void setIntersection (bool isIntersecting)
void setLinePen (QPen isoPen)
Public Member Functions inherited from TechDrawGui::QGIDecoration
QGIDecoration ()
~QGIDecoration () override=default
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual void onDragFinished ()
void setWidth (double w)
double getWidth ()
void setStyle (Qt::PenStyle s)
void setColor (QColor c)
QColor getColor ()
void setFill (Qt::BrushStyle bs)
void makeMark (double x, double y)
void makeMark (Base::Vector3d v)
Protected Member Functions
QColor getCenterColor ()
Qt::PenStyle getCenterStyle ()
void makeLine ()
void setTools ()
Protected Member Functions inherited from TechDrawGui::QGIDecoration
void setPrettyNormal ()
void setPrettyPre ()
void setPrettySel ()
virtual QColor prefNormalColor ()
virtual QColor prefPreColor ()
virtual QColor prefSelectColor ()
Additional Inherited Members
Protected Attributes inherited from TechDrawGui::QGIDecoration
QPen m_pen
QBrush m_brush
QColor m_colCurrent
QColor m_colNormal
double m_width
Qt::PenStyle m_styleCurrent
Qt::BrushStyle m_brushCurrent
int m_dragState
Detailed Description
Definition at line 56 of file QGICenterLine.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 82 of file QGICenterLine.h.
Constructor & Destructor Documentation
QGICenterLine()
QGICenterLine::QGICenterLine () explicit
Definition at line 42 of file QGICenterLine.cpp.
References importers.importIFCmulticore::setColor().
~QGICenterLine()
TechDrawGui::QGICenterLine::~QGICenterLine () override default
Member Function Documentation
draw()
void QGICenterLine::draw () override virtual
Reimplemented from TechDrawGui::QGIDecoration.
Definition at line 52 of file QGICenterLine.cpp.
References draftmake.make_line::makeLine.
Referenced by TechDrawGui::QGIViewPart::drawCenterLines().
getCenterColor()
QColor QGICenterLine::getCenterColor () protected
Definition at line 74 of file QGICenterLine.cpp.
getCenterStyle()
Qt::PenStyle QGICenterLine::getCenterStyle () protected
Definition at line 79 of file QGICenterLine.cpp.
References ParameterGrp::GetInt(), and TechDraw::Preferences::getPreferenceGroup().
makeLine()
void QGICenterLine::makeLine () protected
Definition at line 59 of file QGICenterLine.cpp.
paint()
void QGICenterLine::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 85 of file QGICenterLine.cpp.
setBounds()
void QGICenterLine::setBounds (double x1, double y1, double x2, double y2)
Definition at line 68 of file QGICenterLine.cpp.
Referenced by TechDrawGui::QGIViewPart::drawCenterLines().
setIntersection()
void QGICenterLine::setIntersection (bool isIntersecting)
Set the intersection style for the centerline. If isIntersecting is set to true, the middle of the centerline will be the middle of a dash - therefore if two lines intersect, they will form a cross. If isIntersecting is set to false, the middle of the centerline will be a dot.
Definition at line 93 of file QGICenterLine.cpp.
Referenced by TechDrawGui::QGIViewPart::drawCenterLines().
setLinePen()
void QGICenterLine::setLinePen (QPen isoPen)
Definition at line 139 of file QGICenterLine.cpp.
Referenced by TechDrawGui::QGIViewPart::drawCenterLines().
setTools()
void QGICenterLine::setTools () protected
Definition at line 105 of file QGICenterLine.cpp.
References dot(), Base::fmod(), Base::pow(), and KDL::sqrt().
type()
int TechDrawGui::QGICenterLine::type () const inline override
Definition at line 83 of file QGICenterLine.h.
The documentation for this class was generated from the following files:
QGICenterLine.h
QGICenterLine.cpp