FreeCAD: Base::ViewProjMethod Class Reference
Base::ViewProjMethod Class Reference abstract
#include <ViewProj.h>
Public Member Functions
ViewProjMethod (const ViewProjMethod &)=default
ViewProjMethod (ViewProjMethod &&)=default
ViewProjMethod & operator= (const ViewProjMethod &)=default
ViewProjMethod & operator= (ViewProjMethod &&)=default
virtual ~ViewProjMethod ()=default
virtual bool isValid () const
virtual Vector3f operator() (const Vector3f &rclPt) const =0
virtual Vector3d operator() (const Vector3d &rclPt) const =0
virtual Vector3f inverse (const Vector3f &rclPt) const =0
virtual Vector3d inverse (const Vector3d &rclPt) const =0
virtual Matrix4D getProjectionMatrix () const =0
Matrix4D getComposedProjectionMatrix () const
void setTransform (const Base::Matrix4D &)
This method applies an additional transformation to the input points passed with the () operator.
const Base::Matrix4D & getTransform () const
Protected Member Functions
ViewProjMethod ()
void transformInput (const Base::Vector3f &, Base::Vector3f &) const
void transformInput (const Base::Vector3d &, Base::Vector3d &) const
Detailed Description
Abstract base class for all project methods.
Definition at line 57 of file ViewProj.h.
Constructor & Destructor Documentation
ViewProjMethod() [1/3]
Base::ViewProjMethod::ViewProjMethod (const ViewProjMethod &) default
ViewProjMethod() [2/3]
Base::ViewProjMethod::ViewProjMethod (ViewProjMethod &&) default
~ViewProjMethod()
virtual Base::ViewProjMethod::~ViewProjMethod () virtual default
ViewProjMethod() [3/3]
ViewProjMethod::ViewProjMethod () protected default
Member Function Documentation
getComposedProjectionMatrix()
Matrix4D ViewProjMethod::getComposedProjectionMatrix () const
Calculate the composed projection matrix
Calculate the composed projection matrix which is a product of projection matrix multiplied with input transformation matrix.
Definition at line 39 of file ViewProj.cpp.
References getProjectionMatrix().
Referenced by MeshCore::MeshAlgorithm::CheckFacets().
getProjectionMatrix()
virtual Matrix4D Base::ViewProjMethod::getProjectionMatrix () const pure virtual
Calculate the projection (+ mapping) matrix
Implemented in Gui::ViewVolumeProjection, Base::ViewOrthoProjMatrix, and Base::ViewProjMatrix.
Referenced by getComposedProjectionMatrix().
getTransform()
const Base::Matrix4D& Base::ViewProjMethod::getTransform () const inline
Definition at line 101 of file ViewProj.h.
inverse() [1/2]
virtual Vector3d Base::ViewProjMethod::inverse (const Vector3d & rclPt) const pure virtual
Convert a 2D point on the projection plane in 3D space
Implemented in Base::ViewProjMatrix, Base::ViewOrthoProjMatrix, and Gui::ViewVolumeProjection.
inverse() [2/2]
virtual Vector3f Base::ViewProjMethod::inverse (const Vector3f & rclPt) const pure virtual
Convert a 2D point on the projection plane in 3D space
Implemented in Base::ViewProjMatrix, Base::ViewOrthoProjMatrix, and Gui::ViewVolumeProjection.
isValid()
bool ViewProjMethod::isValid () const virtual
Definition at line 31 of file ViewProj.cpp.
operator()() [1/2]
virtual Vector3d Base::ViewProjMethod::operator() (const Vector3d & rclPt) const pure virtual
Convert 3D point to 2D projection plane
Implemented in Base::ViewOrthoProjMatrix, Base::ViewProjMatrix, and Gui::ViewVolumeProjection.
operator()() [2/2]
virtual Vector3f Base::ViewProjMethod::operator() (const Vector3f & rclPt) const pure virtual
Convert 3D point to 2D projection plane
Implemented in Base::ViewOrthoProjMatrix, Base::ViewProjMatrix, and Gui::ViewVolumeProjection.
operator=() [1/2]
ViewProjMethod& Base::ViewProjMethod::operator= (const ViewProjMethod &) default
operator=() [2/2]
ViewProjMethod& Base::ViewProjMethod::operator= (ViewProjMethod &&) default
setTransform()
void ViewProjMethod::setTransform (const Base::Matrix4D & mat)
This method applies an additional transformation to the input points passed with the () operator.
Apply an additional transformation to the input points
Parameters
mat
Definition at line 56 of file ViewProj.cpp.
Referenced by MeshGui::ViewProviderMesh::clipMeshCallback(), and MeshGui::ViewProviderMesh::trimMeshCallback().
transformInput() [1/2]
void ViewProjMethod::transformInput (const Base::Vector3d & src, Base::Vector3d & dst) const protected
Definition at line 70 of file ViewProj.cpp.
References Base::Matrix4D::multVec().
transformInput() [2/2]
void ViewProjMethod::transformInput (const Base::Vector3f & src, Base::Vector3f & dst) const protected
Definition at line 62 of file ViewProj.cpp.
References Base::Matrix4D::multVec().
Referenced by Base::ViewProjMatrix::operator()(), and Gui::ViewVolumeProjection::operator()().
The documentation for this class was generated from the following files:
ViewProj.h
ViewProj.cpp