FreeCAD: Gui::Dialog::DownloadManager Class Reference
Gui::Dialog::DownloadManager Class Reference
#include <DownloadManager.h>
Public Types
enum RemovePolicy { Never, Exit, SuccessFullDownload }
Public Slots
void download (const QNetworkRequest &request, bool requestFileName=false)
void download (const QUrl &url, bool requestFileName=false)
void handleUnsupportedContent (QNetworkReply *reply, bool requestFileName=false)
void cleanup ()
Public Member Functions
int activeDownloads () const
QNetworkAccessManager * networkAccessManager ()
RemovePolicy removePolicy () const
void setRemovePolicy (RemovePolicy policy)
void closeEvent (QCloseEvent *e) override
QUrl redirectUrl (const QUrl &) const
Static Public Member Functions
static DownloadManager * getInstance ()
Properties
RemovePolicy removePolicy
Friends
class DownloadModel
Detailed Description
Definition at line 44 of file DownloadManager.h.
Member Enumeration Documentation
RemovePolicy
enum Gui::Dialog::DownloadManager::RemovePolicy
Enumerator
Never
Exit
SuccessFullDownload
Definition at line 49 of file DownloadManager.h.
Member Function Documentation
activeDownloads()
int DownloadManager::activeDownloads () const
Definition at line 101 of file DownloadManager.cpp.
References src.Mod.AddonManager.NetworkManager::count, and SplineSurface::i.
cleanup
void DownloadManager::cleanup () slot
Definition at line 283 of file DownloadManager.cpp.
References Gui::Dialog::DownloadModel::removeRows().
Referenced by Path.Dressup.Gui.Boundary.TaskPanel::abort(), Path.Dressup.Gui.Tags.PathDressupTagTaskPanel::abort(), PathPythonGui.simple_edit_panel.SimpleEditPanel::abort(), Path.Dressup.Gui.Boundary.TaskPanel::accept(), Path.Dressup.Gui.Tags.PathDressupTagTaskPanel::accept(), Path.Dressup.Gui.DogboneII.TaskPanel::accept(), Path.Main.Gui.Job.TaskPanel::accept(), Path.Dressup.Gui.Dogbone.TaskPanel::accept(), Path.Op.Gui.Base.TaskPanel::accept(), Path.Dressup.Gui.Boundary.TaskPanel::reject(), Path.Dressup.Gui.Tags.PathDressupTagTaskPanel::reject(), Path.Dressup.Gui.DogboneII.TaskPanel::reject(), Path.Main.Gui.Job.TaskPanel::reject(), Path.Dressup.Gui.Dogbone.TaskPanel::reject(), and Path.Op.Gui.Base.TaskPanel::reject().
closeEvent()
void DownloadManager::closeEvent (QCloseEvent * e) override
Definition at line 96 of file DownloadManager.cpp.
References SCL.SimpleDataTypes::e.
download [1/2]
void DownloadManager::download (const QNetworkRequest & request, bool requestFileName = false) slot
Definition at line 145 of file DownloadManager.cpp.
References handleUnsupportedContent().
Referenced by bimcommands.BimLibrary.BIM_Library_TaskPanel::insert(), and Gui::MainWindow::loadUrls().
download [2/2]
void Gui::Dialog::DownloadManager::download (const QUrl & url, bool requestFileName = false) inline slot
Definition at line 77 of file DownloadManager.h.
References ArchCommands::download().
Referenced by bimcommands.BimLibrary.BIM_Library_TaskPanel::insert().
getInstance()
DownloadManager * DownloadManager::getInstance () static
Definition at line 50 of file DownloadManager.cpp.
References Gui::getMainWindow().
Referenced by Gui::MainWindow::loadUrls(), and Gui::ApplicationPy::sShowDownloads().
handleUnsupportedContent
void DownloadManager::handleUnsupportedContent (QNetworkReply * reply, bool requestFileName = false) slot
Definition at line 154 of file DownloadManager.cpp.
Referenced by download().
networkAccessManager()
QNetworkAccessManager* Gui::Dialog::DownloadManager::networkAccessManager () inline
Definition at line 67 of file DownloadManager.h.
redirectUrl()
QUrl DownloadManager::redirectUrl (const QUrl & url) const
Definition at line 111 of file DownloadManager.cpp.
References Path.Post.scripts.refactored_centroid_post::str.
Referenced by Gui::MainWindow::loadUrls().
removePolicy()
RemovePolicy Gui::Dialog::DownloadManager::removePolicy () const
setRemovePolicy()
void DownloadManager::setRemovePolicy (RemovePolicy policy)
Definition at line 213 of file DownloadManager.cpp.
Friends And Related Function Documentation
DownloadModel
friend class DownloadModel friend
Definition at line 97 of file DownloadManager.h.
Property Documentation
removePolicy
DownloadManager::RemovePolicy DownloadManager::removePolicy read write
Definition at line 55 of file DownloadManager.h.
The documentation for this class was generated from the following files:
DownloadManager.h
DownloadManager.cpp