FreeCAD: Gui::AutoSaver Class Reference
Gui::AutoSaver Class Reference
#include <AutoSaver.h>
Public Slots
void renameFile (QString dirName, QString file, QString tmpFile)
Public Member Functions
void setTimeout (int ms)
void setCompressed (bool on)
Static Public Member Functions
static AutoSaver * instance ()
Protected Member Functions
void slotCreateDocument (const App::Document &Doc)
void slotDeleteDocument (const App::Document &Doc)
void timerEvent (QTimerEvent *event) override
void saveDocument (const std::string &, AutoSaveProperty &)
Detailed Description
The class AutoSaver is used to automatically save a document to a temporary file.
Author
Werner Mayer
Definition at line 66 of file AutoSaver.h.
Member Function Documentation
instance()
AutoSaver * AutoSaver::instance () static
Definition at line 72 of file AutoSaver.cpp.
Referenced by Gui::RecoveryRunnable::run(), and Gui::Dialog::DlgSettingsDocumentImp::saveSettings().
renameFile
void AutoSaver::renameFile (QString dirName, QString file, QString tmpFile) slot
Definition at line 80 of file AutoSaver.cpp.
References FC_LOG, and DrawingExample::file.
saveDocument()
void AutoSaver::saveDocument (const std::string & name, AutoSaveProperty & saver) protected
Definition at line 136 of file AutoSaver.cpp.
References Base::Console(), Base::TimeElapsed::diffTimeF(), Gui::AutoSaveProperty::dirName, toolbit-attributes::doc, DrawingExample::file, App::GetApplication(), ParameterGrp::GetBool(), App::Application::getDocument(), Gui::getMainWindow(), App::Application::GetParameterGroupByPath(), Base::ConsoleSingleton::Log(), App::Document::PartialDoc, Base::ZipWriter::putNextEntry(), Base::FileWriter::putNextEntry(), nativeifc.ifc_tools::save(), ParameterGrp::SetBool(), Base::ZipWriter::setComment(), Base::ZipWriter::setLevel(), Base::Writer::setMode(), Gui::MainWindow::showMessage(), Path.Post.scripts.refactored_centroid_post::str, App::Document::TempDoc, Gui::AutoSaveProperty::touched, Gui::RecoveryWriter::writeFiles(), and Base::ZipWriter::writeFiles().
Referenced by timerEvent().
setCompressed()
void AutoSaver::setCompressed (bool on)
Enables or disables to create compreesed recovery files.
Definition at line 102 of file AutoSaver.cpp.
setTimeout()
void AutoSaver::setTimeout (int ms)
Sets the timeout in milliseconds. A value of 0 means that no timer is used.
Definition at line 89 of file AutoSaver.cpp.
References SplineSurface::id.
Referenced by Gui::Dialog::DlgSettingsDocumentImp::saveSettings().
slotCreateDocument()
void AutoSaver::slotCreateDocument (const App::Document & Doc) protected
Definition at line 107 of file AutoSaver.cpp.
References Base::FileInfo::createDirectory(), Gui::AutoSaveProperty::dirName, App::Document::getName(), App::PropertyString::getValue(), SplineSurface::id, Gui::AutoSaveProperty::timerId, and App::Document::TransientDir.
slotDeleteDocument()
void AutoSaver::slotDeleteDocument (const App::Document & Doc) protected
Definition at line 124 of file AutoSaver.cpp.
References App::Document::getName().
timerEvent()
void AutoSaver::timerEvent (QTimerEvent * event) override protected
Definition at line 228 of file AutoSaver.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), and saveDocument().
The documentation for this class was generated from the following files:
AutoSaver.h
AutoSaver.cpp