FreeCAD: App::PropertyQuantity Class Reference
App::PropertyQuantity Class Reference
#include <PropertyUnits.h>
Public Member Functions
PropertyQuantity ()=default
~PropertyQuantity () override=default
Base::Quantity getQuantityValue () const
const char * getEditorName () const override
Get the class name of the associated property editor item.
PyObject * getPyObject () override
void setPyObject (PyObject *) override
void setUnit (const Base::Unit &u)
const Base::Unit & getUnit () const
void setValue (double lValue)
double getValue () const
const Base::QuantityFormat & getFormat () const
void setFormat (const Base::QuantityFormat &fmt)
void setPathValue (const App::ObjectIdentifier &path, const boost::any &value) override
Set value of property.
const boost::any getPathValue (const App::ObjectIdentifier &path) const override
Get value of property.
bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
Public Member Functions inherited from App::PropertyFloat
PropertyFloat ()
~PropertyFloat () override
void setValue (double lValue)
double getValue () const
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
Property * Copy () const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
unsigned int getMemSize () const override
Public Member Functions inherited from App::Property
Property ()
~Property () override
const char * getName () const
bool hasName () const
std::string getFullName () const
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual void afterRestore ()
virtual void onContainerRestored ()
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
int64_t getID () const
virtual void beforeSave () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Protected Member Functions
Base::Quantity createQuantityFromPy (PyObject *value)
Protected Member Functions inherited from App::Property
virtual void hasSetValue ()
Gets called by all setValue() methods after the value has changed.
virtual void aboutToSetValue ()
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Protected Attributes
Base::Unit _Unit
Base::QuantityFormat _Format
Protected Attributes inherited from App::PropertyFloat
double _dValue
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Float with Unit property This is a property for float with a predefined Unit associated.
Definition at line 43 of file PropertyUnits.h.
Constructor & Destructor Documentation
PropertyQuantity()
App::PropertyQuantity::PropertyQuantity () default
~PropertyQuantity()
App::PropertyQuantity::~PropertyQuantity () override default
Member Function Documentation
createQuantityFromPy()
Base::Quantity PropertyQuantity::createQuantityFromPy (PyObject * value) protected
Definition at line 66 of file PropertyUnits.cpp.
References Path.Log::error(), App::ExpressionParser::parse(), and src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::Quantity.
getEditorName()
const char * PropertyQuantity::getEditorName () const override virtual
Get the class name of the associated property editor item.
Reimplemented from App::PropertyFloat.
Reimplemented in App::PropertyAngle, and App::PropertyQuantityConstraint.
Definition at line 56 of file PropertyUnits.cpp.
getFormat()
const Base::QuantityFormat& App::PropertyQuantity::getFormat () const inline
Definition at line 76 of file PropertyUnits.h.
getPathValue()
const boost::any PropertyQuantity::getPathValue (const App::ObjectIdentifier & path) const override virtual
Get value of property.
Reimplemented from App::PropertyFloat.
Definition at line 132 of file PropertyUnits.cpp.
References Base::Quantity::setFormat().
getPyObject()
PyObject * PropertyQuantity::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from App::PropertyFloat.
Definition at line 61 of file PropertyUnits.cpp.
References src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::Quantity.
getQuantityValue()
Base::Quantity PropertyQuantity::getQuantityValue () const
Definition at line 49 of file PropertyUnits.cpp.
References Base::Quantity::setFormat().
Referenced by PartGui::BoxPrimitive::BoxPrimitive(), PartGui::CirclePrimitive::CirclePrimitive(), PartGui::ConePrimitive::ConePrimitive(), PartGui::CylinderPrimitive::CylinderPrimitive(), SpreadsheetGui::SheetModel::data(), PartGui::EllipsePrimitive::EllipsePrimitive(), PartGui::EllipsoidPrimitive::EllipsoidPrimitive(), App::FunctionExpression::evalAggregate(), PartGui::HelixPrimitive::HelixPrimitive(), PartGui::LinePrimitive::LinePrimitive(), PartGui::PlanePrimitive::PlanePrimitive(), PartGui::PolygonPrimitive::PolygonPrimitive(), PartGui::PrismPrimitive::PrismPrimitive(), PartGui::SpherePrimitive::SpherePrimitive(), PartGui::SpiralPrimitive::SpiralPrimitive(), FemGui::TaskFemConstraintContact::TaskFemConstraintContact(), FemGui::TaskFemConstraintDisplacement::TaskFemConstraintDisplacement(), FemGui::TaskFemConstraintForce::TaskFemConstraintForce(), FemGui::TaskFemConstraintHeatflux::TaskFemConstraintHeatflux(), FemGui::TaskFemConstraintInitialTemperature::TaskFemConstraintInitialTemperature(), FemGui::TaskFemConstraintPressure::TaskFemConstraintPressure(), FemGui::TaskFemConstraintSpring::TaskFemConstraintSpring(), FemGui::TaskFemConstraintTemperature::TaskFemConstraintTemperature(), PartGui::TorusPrimitive::TorusPrimitive(), PartGui::VertexPrimitive::VertexPrimitive(), and PartGui::WedgePrimitive::WedgePrimitive().
getUnit()
const Base::Unit& App::PropertyQuantity::getUnit () const inline
Definition at line 62 of file PropertyUnits.h.
Referenced by SpreadsheetGui::SheetModel::data(), Spreadsheet::Cell::getFormattedQuantity(), FemGui::BoxWidget::setViewProvider(), FemGui::CylinderWidget::setViewProvider(), FemGui::SphereWidget::setViewProvider(), FemGui::TaskFemConstraintContact::TaskFemConstraintContact(), FemGui::TaskFemConstraintForce::TaskFemConstraintForce(), FemGui::TaskFemConstraintPressure::TaskFemConstraintPressure(), FemGui::TaskFemConstraintSpring::TaskFemConstraintSpring(), and FemGui::TaskFemConstraintTemperature::TaskFemConstraintTemperature().
getValue()
double App::PropertyQuantity::getValue () const inline
Definition at line 71 of file PropertyUnits.h.
References App::PropertyFloat::getValue().
Referenced by TechDrawGui::QGSPage::addDrawViewClip(), TechDrawGui::QGSPage::addItemToParent(), TechDrawGui::QGSPage::addLeaderToParent(), TechDrawGui::QGSPage::addQView(), TechDrawGui::QGSPage::addRichAnnoToParent(), TechDraw::DrawViewClip::addView(), TechDraw::DrawViewSection::alignSectionFaces(), PartDesignGui::TaskHelixParameters::apply(), TechDraw::ReferenceEntry::asCanonicalTopoShape(), TechDrawGui::QGIViewBalloon::balloonLabelDragFinished(), PartDesign::FeatureExtrude::buildExtrusion(), TechDraw::DrawViewPart::buildGeometryObject(), TechDraw::CenterLine::calcEndPoints(), TechDraw::CenterLine::calcEndPoints2Lines(), TechDraw::CenterLine::calcEndPoints2Points(), TechDraw::DrawViewPart::centerScaleRotate(), Part::Extrusion::computeFinalParameters(), TechDrawGui::TaskLeaderLine::createLeaderFeature(), SpreadsheetGui::SheetModel::data(), PartGui::DlgProjectOnSurface::DlgProjectOnSurface(), TechDrawGui::QGIViewDimension::drawArrows(), TechDrawGui::QGIViewBalloon::drawBalloon(), TechDrawGui::QGIViewClip::drawClip(), TechDrawGui::QGIViewPart::drawComplexSectionLine(), TechDrawGui::QGIViewPart::drawHighlight(), TechDrawGui::QGIViewSection::drawSectionFace(), TechDrawGui::QGIViewPart::drawSectionLine(), TechDraw::DrawViewMulti::execute(), PartDesign::Hole::execute(), PartDesign::Fillet::execute(), Part::Box::execute(), PartDesign::Helix::execute(), Part::Circle::execute(), PartDesign::Thickness::execute(), Part::Vertex::execute(), PartDesign::Chamfer::execute(), PartDesign::Revolution::execute(), PartDesign::Groove::execute(), PartDesign::Box::execute(), TechDraw::DrawViewArch::execute(), Part::Line::execute(), PartDesign::Cylinder::execute(), Part::Plane::execute(), Part::Sphere::execute(), Part::Thickness::execute(), PartDesign::Sphere::execute(), Part::Ellipsoid::execute(), Part::Cylinder::execute(), PartDesign::Cone::execute(), Part::Prism::execute(), PartDesign::Ellipsoid::execute(), Part::RegularPolygon::execute(), Part::Cone::execute(), PartDesign::Torus::execute(), Part::Torus::execute(), PartDesign::Prism::execute(), Part::Helix::execute(), Part::Spiral::execute(), PartDesign::Wedge::execute(), Part::Wedge::execute(), Part::Ellipse::execute(), PartDesign::Helix::generateHelixPath(), TechDrawGui::TaskDetail::getAnchorScene(), TechDrawGui::QGILeaderLine::getAttachFromFeature(), TechDraw::DrawLeaderLine::getAttachPoint(), TechDrawGui::QGILeaderLine::getAttachPoint(), TechDrawGui::QGIViewBalloon::getBalloonPoints(), TechDrawGui::TaskLineDecor::getFormatAccessPtr(), TechDraw::DimensionFormatter::getFormattedDimensionValue(), TechDraw::DimensionFormatter::getFormattedToleranceValue(), TechDraw::DimensionFormatter::getFormattedToleranceValues(), TechDraw::DrawTemplate::getHeight(), TechDraw::DrawSVGTemplate::getHeight(), TechDraw::DrawViewBalloon::getOrigin(), TechDraw::DrawViewBalloon::getOriginOffset(), TechDraw::DrawProjGroup::getRect(), TechDraw::DrawViewAnnotation::getRect(), TechDraw::DrawView::getRectAligned(), TechDraw::DrawViewPart::getRotatedCS(), TechDraw::DrawViewSection::getShapeForDetail(), TechDraw::DrawViewPart::getShapeForDetail(), PartDesign::LinearPattern::getTransformations(), PartDesign::PolarPattern::getTransformations(), TechDraw::DrawLeaderLine::getTransformedWayPoints(), TechDrawGui::QGILeaderLine::getWayPointsFromFeature(), TechDraw::DrawTemplate::getWidth(), TechDraw::DrawSVGTemplate::getWidth(), Image::ImagePlane::getXSizeInPixel(), TechDraw::DrawProjGroup::getXYPosition(), Image::ImagePlane::getYSizeInPixel(), Fem::ConstraintTransform::handleChangedPropertyName(), TechDraw::DrawViewBalloon::handleChangedPropertyType(), TechDraw::DrawView::handleChangedPropertyType(), Fem::ConstraintContact::handleChangedPropertyType(), PartDesign::Helix::handleChangedPropertyType(), TechDraw::DrawViewDimension::handleChangedPropertyType(), PartDesign::FeatureExtrude::hasTaperedAngle(), TechDrawGui::TaskProjGroup::initializeUi(), PartGui::ViewProviderPartExt::loadParameter(), TechDraw::CosmeticVertex::makeCanonicalPoint(), TechDraw::DrawViewDetail::makeDetailShape(), Part::PrismExtension::makePrism(), Gui::ViewProviderAnnotation::onChanged(), PartDesign::LinearPattern::onChanged(), PartDesign::Hole::onChanged(), TechDraw::DrawProjGroup::onChanged(), TechDrawGui::TaskDetail::onHighlightMoved(), TechDrawGui::TaskCosVertex::onTrackerFinished(), TechDraw::DrawViewSection::postHlrTasks(), TechDraw::DrawViewSection::prepareShape(), MeasureGui::ViewProviderMeasureAngle::redrawAnnotation(), Part::Box::Restore(), Part::Circle::Restore(), Part::Ellipse::Restore(), TechDrawGui::QGIViewImage::rotateView(), TechDrawGui::QGIViewAnnotation::rotateView(), TechDrawGui::QGIView::rotateView(), PartDesign::Helix::safePitch(), TechDrawGui::TaskProjGroup::saveGroupState(), TechDrawGui::TaskLeaderLine::saveState(), TechDraw::CenterLine::scaledAndRotatedGeometry(), TechDraw::CenterLine::scaledGeometry(), TechDrawGui::TaskLeaderLine::scenePointsToDeltas(), PartDesignGui::ViewProviderDatumLine::setExtents(), PartDesignGui::ViewProviderDatumPlane::setExtents(), TechDrawGui::QGILeaderLine::setLeaderFeature(), TechDraw::DrawView::setPosition(), TechDrawGui::TaskRichAnno::setUiEdit(), TechDrawGui::TaskLeaderLine::setUiEdit(), PartDesignGui::TaskRevolutionParameters::setupDialog(), TechDrawGui::QGIViewDimension::setViewPartFeature(), TechDrawGui::QGIViewBalloon::setViewPartFeature(), TechDrawGui::QGIView::snapSectionView(), TechDrawGui::TaskBalloon::TaskBalloon(), TechDrawGui::TaskDimension::TaskDimension(), PartDesignGui::TaskDraftParameters::TaskDraftParameters(), PartDesignGui::TaskFilletParameters::TaskFilletParameters(), Gui::TaskImage::TaskImage(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), TechDrawGui::TaskRichAnno::TaskRichAnno(), RobotGui::TaskTrajectoryDressUpParameter::TaskTrajectoryDressUpParameter(), PartGui::ThicknessWidget::ThicknessWidget(), TechDraw::DrawUtil::toAppSpace(), TechDraw::pointPair::toDisplayForm(), TechDraw::anglePoints::toDisplayForm(), TechDraw::arcPoints::toDisplayForm(), TechDrawGui::DrawGuiUtil::toGuiPoint(), TechDrawGui::TaskProjGroup::turnProjGroupToView(), PartDesignGui::ViewProviderAddSub::updateAddSubShapeIndicator(), PartDesignGui::ViewProviderDatumLine::updateData(), Gui::ViewProviderImagePlane::updateData(), PartDesignGui::ViewProviderDatumPlane::updateData(), FemGui::ViewProviderFemPostBoxFunction::updateData(), FemGui::ViewProviderFemPostCylinderFunction::updateData(), FemGui::ViewProviderFemPostSphereFunction::updateData(), TechDrawGui::QGIView::updateView(), and PartGui::ViewProviderPartExt::updateVisual().
isSame()
bool App::PropertyQuantity::isSame (const Property & other) const inline override virtual
Compare if this property has the same content as the given one.
Reimplemented from App::PropertyFloat.
Definition at line 88 of file PropertyUnits.h.
References Base::Persistence::getTypeId(), and getValue().
setFormat()
void App::PropertyQuantity::setFormat (const Base::QuantityFormat & fmt) inline
Definition at line 80 of file PropertyUnits.h.
References Path.Post.scripts.comparams_post::fmt().
Referenced by Path.Main.Gui.Inspect.GCodeHighlighter::highlightBlock(), and Path.Post.Utils.GCodeHighlighter::highlightBlock().
setPathValue()
void PropertyQuantity::setPathValue (const App::ObjectIdentifier & path, const boost::any & value) override virtual
Set value of property.
Reimplemented from App::PropertyFloat.
Definition at line 121 of file PropertyUnits.cpp.
References App::anyToQuantity().
setPyObject()
void PropertyQuantity::setPyObject (PyObject * value) override virtual
Reimplemented from App::PropertyFloat.
Reimplemented in App::PropertyQuantityConstraint.
Definition at line 92 of file PropertyUnits.cpp.
References Base::Quantity::getUnit(), Base::Quantity::getValue(), App::PropertyFloat::setValue(), and unit().
setUnit()
void App::PropertyQuantity::setUnit (const Base::Unit & u) inline
Definition at line 58 of file PropertyUnits.h.
References buildPsets::u.
Referenced by PartDesign::Chamfer::Chamfer(), App::FeatureTest::FeatureTest(), PartDesign::Fillet::Fillet(), and Spreadsheet::Sheet::setQuantityProperty().
setValue()
void App::PropertyQuantity::setValue (double lValue) inline
Definition at line 67 of file PropertyUnits.h.
References App::PropertyFloat::setValue().
Referenced by TechDrawGui::TaskSurfaceFinishSymbols::accept(), TechDraw::DrawPage::addView(), TechDraw::DrawProjGroupItem::autoPosition(), PartGui::CylinderPrimitive::changeValue(), PartGui::ConePrimitive::changeValue(), PartGui::SpherePrimitive::changeValue(), PartGui::EllipsoidPrimitive::changeValue(), PartGui::TorusPrimitive::changeValue(), PartGui::PrismPrimitive::changeValue(), PartGui::WedgePrimitive::changeValue(), PartGui::HelixPrimitive::changeValue(), PartGui::SpiralPrimitive::changeValue(), PartGui::EllipsePrimitive::changeValue(), PartGui::PolygonPrimitive::changeValue(), PartGui::LinePrimitive::changeValue(), TechDrawGui::TaskRichAnno::createAnnoFeature(), FemGui::ViewProviderFemPostBoxFunction::draggerUpdate(), FemGui::ViewProviderFemPostCylinderFunction::draggerUpdate(), FemGui::ViewProviderFemPostSphereFunction::draggerUpdate(), execCreateHorizChainDimension(), execCreateHorizChamferDimension(), execCreateHorizCoordDimension(), execCreateVertChainDimension(), execCreateVertChamferDimension(), execCreateVertCoordDimension(), PartDesign::Helix::execute(), Measure::MeasureLength::execute(), Measure::MeasureArea::execute(), Measure::MeasureRadius::execute(), Measure::MeasureAngle::execute(), Part::Helix::execute(), Part::Spiral::execute(), TechDraw::DrawSVGTemplate::extractTemplateAttributes(), TechDraw::DrawViewBalloon::handleChangedPropertyType(), Fem::ConstraintPressure::handleChangedPropertyType(), TechDraw::DrawView::handleChangedPropertyType(), Fem::ConstraintForce::handleChangedPropertyType(), Fem::ConstraintInitialTemperature::handleChangedPropertyType(), Fem::ConstraintHeatflux::handleChangedPropertyType(), Fem::ConstraintTemperature::handleChangedPropertyType(), Fem::ConstraintContact::handleChangedPropertyType(), PartDesign::Helix::handleChangedPropertyType(), Fem::ConstraintDisplacement::handleChangedPropertyType(), Part::Thickness::handleChangedPropertyType(), TechDraw::DrawProjGroup::handleChangedPropertyType(), PartGui::ViewProviderPartExt::loadParameter(), TechDrawGui::makeArcLengthDimension(), TechDrawGui::makeObliqueChainDimension(), TechDrawGui::makeObliqueCoordDimension(), TechDraw::DrawWeldSymbol::onChanged(), PartDesign::LinearPattern::onChanged(), PartDesign::Hole::onChanged(), TechDraw::DrawProjGroup::onChanged(), positionDimText(), PartDesign::Helix::proposeParameters(), Measure::MeasureDistanceDetached::recalculateDistance(), Part::Box::Restore(), Part::Circle::Restore(), Part::Ellipse::Restore(), TechDrawGui::TaskProjGroup::restoreGroupState(), TechDrawGui::TaskLeaderLine::restoreState(), PartDesignGui::ViewProviderDatumPlane::setExtents(), TechDraw::DrawViewBalloon::setOrigin(), TechDraw::DrawView::setPosition(), Spreadsheet::Sheet::setQuantityProperty(), Image::ImagePlane::setXSizeInPixel(), Image::ImagePlane::setYSizeInPixel(), TechDrawGui::TaskProjGroup::spacingChanged(), TechDrawGui::TaskProjGroup::turnProjGroupToView(), TechDrawGui::TaskProjGroup::turnViewToProjGroup(), TechDrawGui::TaskRichAnno::updateAnnoFeature(), TechDrawGui::TaskLeaderLine::updateLeaderFeature(), and RobotGui::TaskTrajectoryDressUpParameter::writeValues().
Member Data Documentation
_Format
Base::QuantityFormat App::PropertyQuantity::_Format protected
Definition at line 101 of file PropertyUnits.h.
_Unit
Base::Unit App::PropertyQuantity::_Unit protected
Definition at line 100 of file PropertyUnits.h.
Referenced by Spreadsheet::PropertySpreadsheetQuantity::Copy().
The documentation for this class was generated from the following files:
PropertyUnits.h
PropertyUnits.cpp