FreeCAD: TechDrawGui::TaskSectionView Class Reference
TechDrawGui::TaskSectionView Class Reference
#include <TaskSectionView.h>
Public Member Functions
TaskSectionView (TechDraw::DrawViewPart *base)
TaskSectionView (TechDraw::DrawViewSection *section)
~TaskSectionView () override=default
virtual bool accept ()
virtual bool reject ()
Protected Slots
void onUpClicked ()
void onDownClicked ()
void onLeftClicked ()
void onRightClicked ()
void onIdentifierChanged ()
void onScaleChanged ()
void onXChanged ()
void onYChanged ()
void onZChanged ()
void scaleTypeChanged (int index)
void liveUpdateClicked ()
void updateNowClicked ()
void slotChangeAngle (double newAngle)
void slotViewDirectionChanged (Base::Vector3d newDirection)
Protected Member Functions
void changeEvent (QEvent *event) override
void saveSectionState ()
void restoreSectionState ()
bool apply (bool forceUpdate=false)
void applyQuick (std::string dir)
void applyAligned ()
TechDraw::DrawViewSection * createSectionView ()
void updateSectionView ()
void setUiPrimary ()
void setUiEdit ()
void setUiCommon (Base::Vector3d origin)
void checkAll (bool check)
void enableAll (bool enable)
void failNoObject ()
bool isBaseValid ()
bool isSectionValid ()
Detailed Description
Definition at line 44 of file TaskSectionView.h.
Constructor & Destructor Documentation
TaskSectionView() [1/2]
TaskSectionView::TaskSectionView (TechDraw::DrawViewPart * base) explicit
Definition at line 56 of file TaskSectionView.cpp.
References TechDraw::DrawView::findParentPage(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), and setUiPrimary().
TaskSectionView() [2/2]
TaskSectionView::TaskSectionView (TechDraw::DrawViewSection * section) explicit
Definition at line 87 of file TaskSectionView.cpp.
References TechDraw::DrawViewSection::BaseView, TechDraw::DrawView::findParentPage(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::PropertyLink::getValue(), App::PropertyEnumeration::getValueAsString(), saveSectionState(), TechDraw::DrawViewSection::SectionDirection, and setUiEdit().
~TaskSectionView()
TechDrawGui::TaskSectionView::~TaskSectionView () override default
Member Function Documentation
accept()
bool TaskSectionView::accept () virtual
Definition at line 682 of file TaskSectionView.cpp.
References apply(), doCommand, and Gui::Command::Gui.
Referenced by TechDrawGui::TaskDlgSectionView::accept().
apply()
bool TaskSectionView::apply (bool forceUpdate = false) protected
Definition at line 423 of file TaskSectionView.cpp.
References checkAll(), Base::Console(), createSectionView(), enableAll(), Base::ConsoleSingleton::Error(), failNoObject(), isBaseValid(), isSectionValid(), Path.Op.Surface::msg, App::DocumentObject::recomputeFeature(), TechDraw::DrawView::requestPaint(), Gui::WaitCursor::restoreCursor(), and updateSectionView().
Referenced by accept(), applyAligned(), applyQuick(), liveUpdateClicked(), onIdentifierChanged(), onScaleChanged(), onXChanged(), onYChanged(), onZChanged(), and updateNowClicked().
applyAligned()
void TaskSectionView::applyAligned () protected
Definition at line 474 of file TaskSectionView.cpp.
References apply(), and enableAll().
Referenced by onDownClicked(), onLeftClicked(), onRightClicked(), onUpClicked(), slotChangeAngle(), and slotViewDirectionChanged().
applyQuick()
void TaskSectionView::applyQuick (std::string dir) protected
Definition at line 467 of file TaskSectionView.cpp.
References apply(), and enableAll().
changeEvent()
void TaskSectionView::changeEvent (QEvent * event) override protected
Definition at line 729 of file TaskSectionView.cpp.
checkAll()
void TaskSectionView::checkAll (bool check) protected
Definition at line 392 of file TaskSectionView.cpp.
References ArchCommands::check().
Referenced by apply(), onDownClicked(), onIdentifierChanged(), onLeftClicked(), onRightClicked(), onScaleChanged(), onUpClicked(), onXChanged(), onYChanged(), onZChanged(), slotChangeAngle(), and slotViewDirectionChanged().
createSectionView()
TechDraw::DrawViewSection * TaskSectionView::createSectionView () protected
Definition at line 486 of file TaskSectionView.cpp.
References Gui::Command::commitCommand(), doCommand, failNoObject(), App::DocumentObject::getDocument(), App::DocumentObject::getNameInDocument(), App::Document::getObject(), App::Document::getUniqueObjectName(), isBaseValid(), Base::Vector3< float_type >::Normalize(), Gui::Command::openCommand(), TechDrawGui::CompassWidget::positiveValue(), Arch::QT_TRANSLATE_NOOP, TechDraw::DrawViewSection::setCSFromBase(), and TechDrawGui::VectorEditWidget::value().
Referenced by apply().
enableAll()
void TaskSectionView::enableAll (bool enable) protected
Definition at line 400 of file TaskSectionView.cpp.
Referenced by apply(), applyAligned(), applyQuick(), and setUiCommon().
failNoObject()
void TaskSectionView::failNoObject () protected
Definition at line 635 of file TaskSectionView.cpp.
References Gui::ControlSingleton::closeDialog(), Gui::Control(), Gui::getMainWindow(), and Path.Op.Surface::msg.
Referenced by apply(), createSectionView(), and updateSectionView().
isBaseValid()
bool TaskSectionView::isBaseValid () protected
Definition at line 644 of file TaskSectionView.cpp.
References App::Document::getObject().
Referenced by apply(), createSectionView(), and reject().
isSectionValid()
bool TaskSectionView::isSectionValid () protected
Definition at line 656 of file TaskSectionView.cpp.
References App::Document::getObject().
Referenced by apply(), reject(), and updateSectionView().
liveUpdateClicked
void TaskSectionView::liveUpdateClicked () protected slot
Definition at line 418 of file TaskSectionView.cpp.
References apply().
Referenced by setUiCommon().
onDownClicked
void TaskSectionView::onDownClicked () protected slot
Definition at line 304 of file TaskSectionView.cpp.
References applyAligned(), checkAll(), TechDrawGui::CompassWidget::setToSouth(), and TechDrawGui::VectorEditWidget::setValueNoNotify().
Referenced by setUiCommon().
onIdentifierChanged
void TaskSectionView::onIdentifierChanged () protected slot
Definition at line 331 of file TaskSectionView.cpp.
References apply(), and checkAll().
Referenced by setUiCommon().
onLeftClicked
void TaskSectionView::onLeftClicked () protected slot
Definition at line 313 of file TaskSectionView.cpp.
References applyAligned(), checkAll(), TechDrawGui::CompassWidget::setToWest(), and TechDrawGui::VectorEditWidget::setValueNoNotify().
Referenced by setUiCommon().
onRightClicked
void TaskSectionView::onRightClicked () protected slot
Definition at line 322 of file TaskSectionView.cpp.
References applyAligned(), checkAll(), TechDrawGui::CompassWidget::setToEast(), and TechDrawGui::VectorEditWidget::setValueNoNotify().
Referenced by setUiCommon().
onScaleChanged
void TaskSectionView::onScaleChanged () protected slot
Definition at line 337 of file TaskSectionView.cpp.
References apply(), and checkAll().
Referenced by setUiCommon().
onUpClicked
void TaskSectionView::onUpClicked () protected slot
Definition at line 295 of file TaskSectionView.cpp.
References applyAligned(), checkAll(), TechDrawGui::CompassWidget::setToNorth(), and TechDrawGui::VectorEditWidget::setValueNoNotify().
Referenced by setUiCommon().
onXChanged
void TaskSectionView::onXChanged () protected slot
Definition at line 346 of file TaskSectionView.cpp.
References apply(), and checkAll().
Referenced by setUiCommon().
onYChanged
void TaskSectionView::onYChanged () protected slot
Definition at line 351 of file TaskSectionView.cpp.
References apply(), and checkAll().
Referenced by setUiCommon().
onZChanged
void TaskSectionView::onZChanged () protected slot
Definition at line 356 of file TaskSectionView.cpp.
References apply(), and checkAll().
Referenced by setUiCommon().
reject()
bool TaskSectionView::reject () virtual
Definition at line 689 of file TaskSectionView.cpp.
References doCommand, App::DocumentObject::getNameInDocument(), Gui::Command::Gui, isBaseValid(), isSectionValid(), App::DocumentObject::recomputeFeature(), TechDraw::DrawView::requestPaint(), restoreSectionState(), and Gui::Command::updateActive().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and TechDrawGui::TaskDlgSectionView::reject().
restoreSectionState()
void TaskSectionView::restoreSectionState () protected
Definition at line 255 of file TaskSectionView.cpp.
References TechDraw::DrawViewPart::Direction, TechDraw::DrawView::Scale, TechDraw::DrawView::ScaleType, TechDraw::DrawViewSection::SectionDirection, TechDraw::DrawViewSection::SectionNormal, TechDraw::DrawViewSection::SectionOrigin, TechDraw::DrawViewSection::SectionSymbol, App::PropertyVector::setValue(), App::PropertyEnumeration::setValue(), App::PropertyFloat::setValue(), and App::PropertyString::setValue().
Referenced by reject().
saveSectionState()
void TaskSectionView::saveSectionState () protected
Definition at line 239 of file TaskSectionView.cpp.
References TechDraw::DrawViewPart::Direction, TechDraw::DrawView::getScale(), TechDraw::DrawView::getScaleType(), App::PropertyVector::getValue(), App::PropertyString::getValue(), App::PropertyEnumeration::getValueAsString(), TechDraw::DrawViewSection::SectionDirection, TechDraw::DrawViewSection::SectionNormal, TechDraw::DrawViewSection::SectionOrigin, and TechDraw::DrawViewSection::SectionSymbol.
Referenced by TaskSectionView().
scaleTypeChanged
void TaskSectionView::scaleTypeChanged (int index) protected slot
Definition at line 362 of file TaskSectionView.cpp.
References TechDraw::DrawView::autoScale(), TechDraw::DrawView::findParentPage(), App::PropertyFloat::getValue(), TechDraw::DrawView::Scale, and TechDraw::DrawPage::Scale.
Referenced by setUiCommon().
setUiCommon()
void TaskSectionView::setUiCommon (Base::Vector3d origin) protected
Definition at line 187 of file TaskSectionView.cpp.
References TechDrawGui::CompassWidget::angleChanged(), draftgeoutils.intersections::connect(), enableAll(), App::DocumentObject::getNameInDocument(), Base::Unit::Length, liveUpdateClicked(), onDownClicked(), onIdentifierChanged(), onLeftClicked(), onRightClicked(), onScaleChanged(), onUpClicked(), onXChanged(), onYChanged(), onZChanged(), scaleTypeChanged(), TechDrawGui::VectorEditWidget::setLabel(), slotChangeAngle(), slotViewDirectionChanged(), updateNowClicked(), TechDrawGui::VectorEditWidget::valueChanged(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by setUiEdit(), and setUiPrimary().
setUiEdit()
void TaskSectionView::setUiEdit () protected
Definition at line 157 of file TaskSectionView.cpp.
References KDL::atan2(), TechDraw::DrawView::getScale(), TechDraw::DrawView::getScaleType(), App::PropertyVector::getValue(), App::PropertyString::getValue(), App::PropertyEnumeration::isValue(), M_PI, Base::Vector3< float_type >::Normalize(), TechDraw::DrawViewPart::projectPoint(), TechDraw::DrawView::ScaleType, TechDraw::DrawViewSection::SectionNormal, TechDraw::DrawViewSection::SectionOrigin, TechDraw::DrawViewSection::SectionSymbol, TechDrawGui::CompassWidget::setDialAngle(), setUiCommon(), TechDrawGui::VectorEditWidget::setValueNoNotify(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by TaskSectionView().
setUiPrimary()
void TaskSectionView::setUiPrimary () protected
Definition at line 125 of file TaskSectionView.cpp.
References TechDraw::DrawViewPart::getOriginalCentroid(), TechDraw::DrawView::getScale(), TechDraw::DrawView::getScaleType(), TechDrawGui::CompassWidget::setDialAngle(), setUiCommon(), and TechDrawGui::VectorEditWidget::setValueNoNotify().
Referenced by TaskSectionView().
slotChangeAngle
void TaskSectionView::slotChangeAngle (double newAngle) protected slot
Definition at line 282 of file TaskSectionView.cpp.
References applyAligned(), checkAll(), KDL::cos(), M_PI, TechDrawGui::VectorEditWidget::setValueNoNotify(), and KDL::sin().
Referenced by setUiCommon().
slotViewDirectionChanged
void TaskSectionView::slotViewDirectionChanged (Base::Vector3d newDirection) protected slot
Definition at line 270 of file TaskSectionView.cpp.
References applyAligned(), KDL::atan2(), checkAll(), M_PI, Base::Vector3< float_type >::Normalize(), TechDraw::DrawViewPart::projectPoint(), TechDrawGui::CompassWidget::setDialAngle(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
Referenced by setUiCommon().
updateNowClicked
void TaskSectionView::updateNowClicked () protected slot
Definition at line 420 of file TaskSectionView.cpp.
References apply().
Referenced by setUiCommon().
updateSectionView()
void TaskSectionView::updateSectionView () protected
Definition at line 564 of file TaskSectionView.cpp.
References Gui::Command::commitCommand(), doCommand, failNoObject(), App::DocumentObject::getNameInDocument(), isSectionValid(), Base::Vector3< float_type >::Normalize(), Gui::Command::openCommand(), TechDrawGui::CompassWidget::positiveValue(), Arch::QT_TRANSLATE_NOOP, TechDraw::DrawViewSection::setCSFromBase(), and TechDrawGui::VectorEditWidget::value().
Referenced by apply().
The documentation for this class was generated from the following files:
TaskSectionView.h
TaskSectionView.cpp