FreeCAD: Materials::MaterialFilter Class Reference
Materials::MaterialFilter Class Reference
#include <MaterialFilter.h>
Public Member Functions
MaterialFilter ()
virtual ~MaterialFilter ()=default
QString name () const
void setName (const QString &name)
bool modelIncluded (const std::shared_ptr< Material > &material) const
bool modelIncluded (const QString &uuid) const
void addRequired (const QString &uuid)
void addRequiredComplete (const QString &uuid)
void requirePhysical (bool required)
void requireAppearance (bool required)
const QSet< QString > * getRequired () const
const QSet< QString > * getRequiredComplete () const
void clear ()
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Additional Inherited Members
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Definition at line 159 of file MaterialFilter.h.
Constructor & Destructor Documentation
MaterialFilter()
MaterialFilter::MaterialFilter ()
Definition at line 62 of file MaterialFilter.cpp.
~MaterialFilter()
virtual Materials::MaterialFilter::~MaterialFilter () virtual default
Member Function Documentation
addRequired()
void MaterialFilter::addRequired (const QString & uuid)
Definition at line 107 of file MaterialFilter.cpp.
addRequiredComplete()
void MaterialFilter::addRequiredComplete (const QString & uuid)
Definition at line 115 of file MaterialFilter.cpp.
clear()
void MaterialFilter::clear ()
Definition at line 124 of file MaterialFilter.cpp.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), and src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__().
getRequired()
const QSet<QString>* Materials::MaterialFilter::getRequired () const inline
Definition at line 205 of file MaterialFilter.h.
getRequiredComplete()
const QSet<QString>* Materials::MaterialFilter::getRequiredComplete () const inline
Definition at line 209 of file MaterialFilter.h.
modelIncluded() [1/2]
bool MaterialFilter::modelIncluded (const QString & uuid) const
Definition at line 95 of file MaterialFilter.cpp.
References modelIncluded().
modelIncluded() [2/2]
bool MaterialFilter::modelIncluded (const std::shared_ptr< Material > & material) const
Definition at line 69 of file MaterialFilter.cpp.
Referenced by modelIncluded().
name()
QString Materials::MaterialFilter::name () const inline
Definition at line 171 of file MaterialFilter.h.
requireAppearance()
void Materials::MaterialFilter::requireAppearance (bool required) inline
Definition at line 200 of file MaterialFilter.h.
requirePhysical()
void Materials::MaterialFilter::requirePhysical (bool required) inline
Definition at line 196 of file MaterialFilter.h.
setName()
void Materials::MaterialFilter::setName (const QString & name) inline
Definition at line 175 of file MaterialFilter.h.
The documentation for this class was generated from the following files:
MaterialFilter.h
MaterialFilter.cpp