FreeCAD: InspectionGui::ViewProviderProxyObject Class Reference
InspectionGui::ViewProviderProxyObject Class Reference
Public Member Functions
ViewProviderProxyObject (QWidget *w)
~ViewProviderProxyObject () override=default
void customEvent (QEvent *) override
Static Public Member Functions
static void addFlag (Gui::View3DInventorViewer *view, const QString &text, const SoPickedPoint *point)
Detailed Description
Definition at line 474 of file ViewProviderInspection.cpp.
Constructor & Destructor Documentation
ViewProviderProxyObject()
InspectionGui::ViewProviderProxyObject::ViewProviderProxyObject (QWidget * w) inline explicit
Definition at line 477 of file ViewProviderInspection.cpp.
~ViewProviderProxyObject()
InspectionGui::ViewProviderProxyObject::~ViewProviderProxyObject () override default
Member Function Documentation
addFlag()
static void InspectionGui::ViewProviderProxyObject::addFlag (Gui::View3DInventorViewer * view, const QString & text, const SoPickedPoint * point) inline static
Definition at line 505 of file ViewProviderInspection.cpp.
References Gui::GLFlagWindow::addFlag(), Gui::View3DInventorViewer::addGraphicsItem(), Gui::FlagLayout::BottomLeft, Base::BaseClass::getClassTypeId(), Gui::View3DInventorViewer::getGraphicsItemsOfType(), buildPsets::p, Gui::Flag::setOrigin(), and Gui::Flag::setText().
Referenced by InspectionGui::ViewProviderInspection::inspectCallback().
customEvent()
void InspectionGui::ViewProviderProxyObject::customEvent (QEvent *) inline override
Definition at line 482 of file ViewProviderInspection.cpp.
References Gui::getMainWindow().
The documentation for this class was generated from the following file:
ViewProviderInspection.cpp