FreeCAD: SketcherGui::SketcherToolDefaultWidget Class Reference
SketcherGui::SketcherToolDefaultWidget Class Reference
#include <SketcherToolDefaultWidget.h>
Public Types
enum Parameter {
First, Second, Third, Fourth,
Fifth, Sixth, Seventh, Eighth,
Ninth, Tenth, nParameters
}
Parameter spinbox number/label.
enum Checkbox {
FirstBox, SecondBox, ThirdBox, FourthBox,
nCheckbox
}
Checkbox number/label.
enum Combobox { FirstCombo, SecondCombo, ThirdCombo, nCombobox }
Combobox number/label.
Public Member Functions
SketcherToolDefaultWidget (QWidget *parent=nullptr)
~SketcherToolDefaultWidget () override
bool eventFilter (QObject *object, QEvent *event) override
void setParameter (int parameterindex, double val)
void setParameterWithoutPassingFocus (int parameterindex, double val)
void configureParameterInitialValue (int parameterindex, double value)
void configureParameterUnit (int parameterindex, const Base::Unit &unit)
void configureParameterDecimals (int parameterindex, int val)
void configureParameterMax (int parameterindex, double val)
void configureParameterMin (int parameterindex, double val)
double getParameter (int parameterindex)
bool isParameterSet (int parameterindex)
void updateVisualValue (int parameterindex, double val, const Base::Unit &unit=Base::Unit::Length)
void setParameterEnabled (int parameterindex, bool active=true)
void setParameterFocus (int parameterindex)
void setParameterVisible (int parameterindex, bool visible=true)
void reset ()
void initNParameters (int nparameters, QObject *filteringObject=nullptr)
void setParameterLabel (int parameterindex, const QString &string)
void setParameterFilteringObject (int parameterindex, QObject *filteringObject)
void setNoticeText (const QString &string)
void setNoticeVisible (bool visible)
void initNCheckboxes (int ncheckbox)
void setCheckboxVisible (int checkboxindex, bool visible)
void setCheckboxChecked (int checkboxindex, bool checked)
void setCheckboxLabel (int checkboxindex, const QString &string)
void setCheckboxToolTip (int checkboxindex, const QString &string)
bool getCheckboxChecked (int checkboxindex)
void setCheckboxPrefEntry (int checkboxindex, const std::string &prefEntry)
void setCheckboxIcon (int checkboxindex, QIcon icon)
void restoreCheckBoxPref (int checkboxindex)
void initNComboboxes (int ncombobox)
void setComboboxVisible (int comboboxindex, bool visible)
void setComboboxIndex (int comboboxindex, int value)
void setComboboxLabel (int comboboxindex, const QString &string)
int getComboboxIndex (int comboboxindex)
void setComboboxElements (int comboboxindex, const QStringList &names)
void setComboboxItemIcon (int comboboxindex, int index, QIcon icon)
void setComboboxPrefEntry (int comboboxindex, const std::string &prefEntry)
void restoreComboboxPref (int comboboxindex)
template<typename F >
boost::signals2::connection registerParameterTabOrEnterPressed (F &&fn)
template<typename F >
boost::signals2::connection registerParameterValueChanged (F &&fn)
template<typename F >
boost::signals2::connection registerCheckboxCheckedChanged (F &&fn)
template<typename F >
boost::signals2::connection registerComboboxSelectionChanged (F &&fn)
Protected Slots
void parameterOne_valueChanged (double val)
void parameterTwo_valueChanged (double val)
void parameterThree_valueChanged (double val)
void parameterFour_valueChanged (double val)
void parameterFive_valueChanged (double val)
void parameterSix_valueChanged (double val)
void parameterSeven_valueChanged (double val)
void parameterEight_valueChanged (double val)
void parameterNine_valueChanged (double val)
void parameterTen_valueChanged (double val)
void checkBoxTS1_toggled (bool val)
void checkBoxTS2_toggled (bool val)
void checkBoxTS3_toggled (bool val)
void checkBoxTS4_toggled (bool val)
void comboBox1_currentIndexChanged (int val)
void comboBox2_currentIndexChanged (int val)
void comboBox3_currentIndexChanged (int val)
Protected Member Functions
void changeEvent (QEvent *ev) override
Detailed Description
Definition at line 57 of file SketcherToolDefaultWidget.h.
Member Enumeration Documentation
Checkbox
enum SketcherGui::SketcherToolDefaultWidget::Checkbox
Checkbox number/label.
Enumerator
FirstBox
SecondBox
ThirdBox
FourthBox
nCheckbox
Definition at line 86 of file SketcherToolDefaultWidget.h.
Combobox
enum SketcherGui::SketcherToolDefaultWidget::Combobox
Combobox number/label.
Enumerator
FirstCombo
SecondCombo
ThirdCombo
nCombobox
Definition at line 96 of file SketcherToolDefaultWidget.h.
Parameter
enum SketcherGui::SketcherToolDefaultWidget::Parameter
Parameter spinbox number/label.
Enumerator
First
Second
Third
Fourth
Fifth
Sixth
Seventh
Eighth
Ninth
Tenth
nParameters
Definition at line 70 of file SketcherToolDefaultWidget.h.
Constructor & Destructor Documentation
SketcherToolDefaultWidget()
SketcherToolDefaultWidget::SketcherToolDefaultWidget (QWidget * parent = nullptr) explicit
Definition at line 52 of file SketcherToolDefaultWidget.cpp.
References reset().
~SketcherToolDefaultWidget()
SketcherToolDefaultWidget::~SketcherToolDefaultWidget () override default
Member Function Documentation
changeEvent()
void SketcherToolDefaultWidget::changeEvent (QEvent * ev) override protected
Definition at line 839 of file SketcherToolDefaultWidget.cpp.
checkBoxTS1_toggled
void SketcherToolDefaultWidget::checkBoxTS1_toggled (bool val) protected slot
Definition at line 579 of file SketcherToolDefaultWidget.cpp.
References toolbit-attributes::val.
checkBoxTS2_toggled
void SketcherToolDefaultWidget::checkBoxTS2_toggled (bool val) protected slot
Definition at line 588 of file SketcherToolDefaultWidget.cpp.
References toolbit-attributes::val.
checkBoxTS3_toggled
void SketcherToolDefaultWidget::checkBoxTS3_toggled (bool val) protected slot
Definition at line 597 of file SketcherToolDefaultWidget.cpp.
References toolbit-attributes::val.
checkBoxTS4_toggled
void SketcherToolDefaultWidget::checkBoxTS4_toggled (bool val) protected slot
Definition at line 606 of file SketcherToolDefaultWidget.cpp.
References toolbit-attributes::val.
comboBox1_currentIndexChanged
void SketcherToolDefaultWidget::comboBox1_currentIndexChanged (int val) protected slot
Definition at line 735 of file SketcherToolDefaultWidget.cpp.
References toolbit-attributes::val.
comboBox2_currentIndexChanged
void SketcherToolDefaultWidget::comboBox2_currentIndexChanged (int val) protected slot
Definition at line 742 of file SketcherToolDefaultWidget.cpp.
References toolbit-attributes::val.
comboBox3_currentIndexChanged
void SketcherToolDefaultWidget::comboBox3_currentIndexChanged (int val) protected slot
Definition at line 749 of file SketcherToolDefaultWidget.cpp.
References toolbit-attributes::val.
configureParameterDecimals()
void SketcherToolDefaultWidget::configureParameterDecimals (int parameterindex, int val)
Definition at line 370 of file SketcherToolDefaultWidget.cpp.
References nParameters, Arch::QT_TRANSLATE_NOOP, Gui::QuantitySpinBox::setDecimals(), THROWM, and toolbit-attributes::val.
configureParameterInitialValue()
void SketcherToolDefaultWidget::configureParameterInitialValue (int parameterindex, double value)
Definition at line 349 of file SketcherToolDefaultWidget.cpp.
References setParameter(), and toolbit-attributes::val.
configureParameterMax()
void SketcherToolDefaultWidget::configureParameterMax (int parameterindex, double val)
Definition at line 396 of file SketcherToolDefaultWidget.cpp.
References nParameters, Arch::QT_TRANSLATE_NOOP, Gui::QuantitySpinBox::setMaximum(), THROWM, and toolbit-attributes::val.
configureParameterMin()
void SketcherToolDefaultWidget::configureParameterMin (int parameterindex, double val)
Definition at line 383 of file SketcherToolDefaultWidget.cpp.
References nParameters, Arch::QT_TRANSLATE_NOOP, Gui::QuantitySpinBox::setMinimum(), THROWM, and toolbit-attributes::val.
configureParameterUnit()
void SketcherToolDefaultWidget::configureParameterUnit (int parameterindex, const Base::Unit & unit)
Definition at line 355 of file SketcherToolDefaultWidget.cpp.
References nParameters, Arch::QT_TRANSLATE_NOOP, Gui::QuantitySpinBox::setUnit(), THROWM, and unit().
eventFilter()
bool SketcherToolDefaultWidget::eventFilter (QObject * object, QEvent * event) override
Definition at line 148 of file SketcherToolDefaultWidget.cpp.
References SplineSurface::i, and nParameters.
getCheckboxChecked()
bool SketcherToolDefaultWidget::getCheckboxChecked (int checkboxindex)
Definition at line 674 of file SketcherToolDefaultWidget.cpp.
References nParameters, and THROWM.
Referenced by SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::addConstraints(), SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::firstKeyShortcut(), and SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::secondKeyShortcut().
getComboboxIndex()
int SketcherToolDefaultWidget::getComboboxIndex (int comboboxindex)
Definition at line 829 of file SketcherToolDefaultWidget.cpp.
References nCombobox, and THROWM.
getParameter()
double SketcherToolDefaultWidget::getParameter (int parameterindex)
Definition at line 538 of file SketcherToolDefaultWidget.cpp.
References Base::Quantity::getValue(), nParameters, THROWM, and Gui::QuantitySpinBox::value.
initNCheckboxes()
void SketcherToolDefaultWidget::initNCheckboxes (int ncheckbox)
Definition at line 616 of file SketcherToolDefaultWidget.cpp.
References SplineSurface::i, nCheckbox, setCheckboxChecked(), and setCheckboxVisible().
initNComboboxes()
void SketcherToolDefaultWidget::initNComboboxes (int ncombobox)
Definition at line 757 of file SketcherToolDefaultWidget.cpp.
References SplineSurface::i, nCombobox, and setComboboxVisible().
initNParameters()
void SketcherToolDefaultWidget::initNParameters (int nparameters, QObject * filteringObject = nullptr)
Definition at line 285 of file SketcherToolDefaultWidget.cpp.
References SplineSurface::i, nParameters, setParameter(), setParameterFilteringObject(), setParameterFocus(), and setParameterVisible().
isParameterSet()
bool SketcherToolDefaultWidget::isParameterSet (int parameterindex)
Definition at line 547 of file SketcherToolDefaultWidget.cpp.
References nParameters, and THROWM.
parameterEight_valueChanged
void SketcherToolDefaultWidget::parameterEight_valueChanged (double val) protected slot
Definition at line 263 of file SketcherToolDefaultWidget.cpp.
References toolbit-attributes::val.
parameterFive_valueChanged
void SketcherToolDefaultWidget::parameterFive_valueChanged (double val) protected slot
Definition at line 242 of file SketcherToolDefaultWidget.cpp.
References toolbit-attributes::val.
parameterFour_valueChanged
void SketcherToolDefaultWidget::parameterFour_valueChanged (double val) protected slot
Definition at line 235 of file SketcherToolDefaultWidget.cpp.
References toolbit-attributes::val.
parameterNine_valueChanged
void SketcherToolDefaultWidget::parameterNine_valueChanged (double val) protected slot
Definition at line 270 of file SketcherToolDefaultWidget.cpp.
References toolbit-attributes::val.
parameterOne_valueChanged
void SketcherToolDefaultWidget::parameterOne_valueChanged (double val) protected slot
Definition at line 210 of file SketcherToolDefaultWidget.cpp.
References toolbit-attributes::val.
parameterSeven_valueChanged
void SketcherToolDefaultWidget::parameterSeven_valueChanged (double val) protected slot
Definition at line 256 of file SketcherToolDefaultWidget.cpp.
References toolbit-attributes::val.
parameterSix_valueChanged
void SketcherToolDefaultWidget::parameterSix_valueChanged (double val) protected slot
Definition at line 249 of file SketcherToolDefaultWidget.cpp.
References toolbit-attributes::val.
parameterTen_valueChanged
void SketcherToolDefaultWidget::parameterTen_valueChanged (double val) protected slot
Definition at line 277 of file SketcherToolDefaultWidget.cpp.
References toolbit-attributes::val.
parameterThree_valueChanged
void SketcherToolDefaultWidget::parameterThree_valueChanged (double val) protected slot
Definition at line 228 of file SketcherToolDefaultWidget.cpp.
References toolbit-attributes::val.
parameterTwo_valueChanged
void SketcherToolDefaultWidget::parameterTwo_valueChanged (double val) protected slot
Definition at line 221 of file SketcherToolDefaultWidget.cpp.
References FreeCADInit::Second, and toolbit-attributes::val.
registerCheckboxCheckedChanged()
template<typename F > boost::signals2::connection SketcherGui::SketcherToolDefaultWidget::registerCheckboxCheckedChanged (F && fn) inline
Definition at line 170 of file SketcherToolDefaultWidget.h.
registerComboboxSelectionChanged()
template<typename F > boost::signals2::connection SketcherGui::SketcherToolDefaultWidget::registerComboboxSelectionChanged (F && fn) inline
Definition at line 176 of file SketcherToolDefaultWidget.h.
registerParameterTabOrEnterPressed()
template<typename F > boost::signals2::connection SketcherGui::SketcherToolDefaultWidget::registerParameterTabOrEnterPressed (F && fn) inline
Definition at line 158 of file SketcherToolDefaultWidget.h.
registerParameterValueChanged()
template<typename F > boost::signals2::connection SketcherGui::SketcherToolDefaultWidget::registerParameterValueChanged (F && fn) inline
Definition at line 164 of file SketcherToolDefaultWidget.h.
reset()
void SketcherToolDefaultWidget::reset ()
Definition at line 175 of file SketcherToolDefaultWidget.cpp.
References SplineSurface::i, nCheckbox, nCombobox, nParameters, setCheckboxChecked(), setCheckboxPrefEntry(), setCheckboxVisible(), setComboboxIndex(), setComboboxVisible(), setNoticeVisible(), setParameter(), and setParameterVisible().
Referenced by SketcherToolDefaultWidget().
restoreCheckBoxPref()
void SketcherToolDefaultWidget::restoreCheckBoxPref (int checkboxindex)
Definition at line 692 of file SketcherToolDefaultWidget.cpp.
References nCheckbox, and Gui::PrefWidget::onRestore().
restoreComboboxPref()
void SketcherToolDefaultWidget::restoreComboboxPref (int comboboxindex)
Definition at line 722 of file SketcherToolDefaultWidget.cpp.
References nCombobox, and Gui::PrefWidget::onRestore().
setCheckboxChecked()
void SketcherToolDefaultWidget::setCheckboxChecked (int checkboxindex, bool checked)
Definition at line 633 of file SketcherToolDefaultWidget.cpp.
References nCheckbox.
Referenced by SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::addConstraints(), SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::firstKeyShortcut(), initNCheckboxes(), reset(), and SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::secondKeyShortcut().
setCheckboxIcon()
void SketcherToolDefaultWidget::setCheckboxIcon (int checkboxindex, QIcon icon)
Definition at line 699 of file SketcherToolDefaultWidget.cpp.
References nCheckbox.
setCheckboxLabel()
void SketcherToolDefaultWidget::setCheckboxLabel (int checkboxindex, const QString & string)
Definition at line 640 of file SketcherToolDefaultWidget.cpp.
References nCheckbox.
setCheckboxPrefEntry()
void SketcherToolDefaultWidget::setCheckboxPrefEntry (int checkboxindex, const std::string & prefEntry)
Definition at line 683 of file SketcherToolDefaultWidget.cpp.
References nCheckbox, and Gui::PrefWidget::setEntryName().
Referenced by reset().
setCheckboxToolTip()
void SketcherToolDefaultWidget::setCheckboxToolTip (int checkboxindex, const QString & string)
Definition at line 647 of file SketcherToolDefaultWidget.cpp.
References nCheckbox.
setCheckboxVisible()
void SketcherToolDefaultWidget::setCheckboxVisible (int checkboxindex, bool visible)
Definition at line 626 of file SketcherToolDefaultWidget.cpp.
References nCheckbox.
Referenced by initNCheckboxes(), and reset().
setComboboxElements()
void SketcherToolDefaultWidget::setComboboxElements (int comboboxindex, const QStringList & names)
Definition at line 788 of file SketcherToolDefaultWidget.cpp.
References femtools.tokrules::names, and nCombobox.
setComboboxIndex()
void SketcherToolDefaultWidget::setComboboxIndex (int comboboxindex, int value)
Definition at line 774 of file SketcherToolDefaultWidget.cpp.
References nCombobox.
Referenced by reset().
setComboboxItemIcon()
void SketcherToolDefaultWidget::setComboboxItemIcon (int comboboxindex, int index, QIcon icon)
Definition at line 706 of file SketcherToolDefaultWidget.cpp.
References nCombobox.
setComboboxLabel()
void SketcherToolDefaultWidget::setComboboxLabel (int comboboxindex, const QString & string)
Definition at line 781 of file SketcherToolDefaultWidget.cpp.
References nCombobox.
setComboboxPrefEntry()
void SketcherToolDefaultWidget::setComboboxPrefEntry (int comboboxindex, const std::string & prefEntry)
Definition at line 713 of file SketcherToolDefaultWidget.cpp.
References nCombobox, and Gui::PrefWidget::setEntryName().
setComboboxVisible()
void SketcherToolDefaultWidget::setComboboxVisible (int comboboxindex, bool visible)
Definition at line 766 of file SketcherToolDefaultWidget.cpp.
References nCombobox.
Referenced by initNComboboxes(), and reset().
setNoticeText()
void SketcherToolDefaultWidget::setNoticeText (const QString & string)
Definition at line 200 of file SketcherToolDefaultWidget.cpp.
setNoticeVisible()
void SketcherToolDefaultWidget::setNoticeVisible (bool visible)
Definition at line 204 of file SketcherToolDefaultWidget.cpp.
Referenced by reset().
setParameter()
void SketcherToolDefaultWidget::setParameter (int parameterindex, double val)
Definition at line 331 of file SketcherToolDefaultWidget.cpp.
References nParameters, Arch::QT_TRANSLATE_NOOP, Gui::QuantitySpinBox::setValue(), THROWM, and toolbit-attributes::val.
Referenced by configureParameterInitialValue(), initNParameters(), reset(), and setParameterWithoutPassingFocus().
setParameterEnabled()
void SketcherToolDefaultWidget::setParameterEnabled (int parameterindex, bool active = true)
Definition at line 409 of file SketcherToolDefaultWidget.cpp.
References nParameters, Arch::QT_TRANSLATE_NOOP, and THROWM.
setParameterFilteringObject()
void SketcherToolDefaultWidget::setParameterFilteringObject (int parameterindex, QObject * filteringObject)
Definition at line 311 of file SketcherToolDefaultWidget.cpp.
References nParameters, Arch::QT_TRANSLATE_NOOP, and THROWM.
Referenced by initNParameters().
setParameterFocus()
void SketcherToolDefaultWidget::setParameterFocus (int parameterindex)
Definition at line 421 of file SketcherToolDefaultWidget.cpp.
References nParameters, Arch::QT_TRANSLATE_NOOP, and THROWM.
Referenced by SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::doInitControls(), and initNParameters().
setParameterLabel()
void SketcherToolDefaultWidget::setParameterLabel (int parameterindex, const QString & string)
Definition at line 324 of file SketcherToolDefaultWidget.cpp.
References nParameters.
setParameterVisible()
void SketcherToolDefaultWidget::setParameterVisible (int parameterindex, bool visible = true)
Definition at line 303 of file SketcherToolDefaultWidget.cpp.
References nParameters.
Referenced by initNParameters(), and reset().
setParameterWithoutPassingFocus()
void SketcherToolDefaultWidget::setParameterWithoutPassingFocus (int parameterindex, double val)
Definition at line 343 of file SketcherToolDefaultWidget.cpp.
References setParameter(), and toolbit-attributes::val.
updateVisualValue()
void SketcherToolDefaultWidget::updateVisualValue (int parameterindex, double val, const Base::Unit & unit = Base::Unit::Length)
Definition at line 556 of file SketcherToolDefaultWidget.cpp.
References nParameters, Arch::QT_TRANSLATE_NOOP, THROWM, unit(), and toolbit-attributes::val.
The documentation for this class was generated from the following files:
SketcherToolDefaultWidget.h
SketcherToolDefaultWidget.cpp