FreeCAD: SoGesturePanEvent Class Reference
SoGesturePanEvent Class Reference
#include <SoTouchEvents.h>
Public Member Functions
SoGesturePanEvent ()=default
SoGesturePanEvent (QPanGesture *qpan, QWidget *widget)
~SoGesturePanEvent () override=default
SbBool isSoGesturePanEvent (const SoEvent *ev) const
Public Member Functions inherited from SoGestureEvent
SoGestureEvent ()=default
~SoGestureEvent () override=default
SbBool isSoGestureEvent (const SoEvent *ev) const
Static Public Member Functions
static void initClass ()
Static Public Member Functions inherited from SoGestureEvent
static void initClass ()
Public Attributes
SbVec2f deltaOffset
SbVec2f totalOffset
Public Attributes inherited from SoGestureEvent
SbGestureState state {SbGSNoGesture}
Additional Inherited Members
Public Types inherited from SoGestureEvent
enum SbGestureState {
SbGSNoGesture = Qt::NoGesture, SbGSStart = Qt::GestureStarted, SbGSUpdate = Qt::GestureUpdated, SbGSEnd = Qt::GestureFinished,
SbGsCanceled = Qt::GestureCanceled
}
Detailed Description
Definition at line 56 of file SoTouchEvents.h.
Constructor & Destructor Documentation
SoGesturePanEvent() [1/2]
SoGesturePanEvent::SoGesturePanEvent () default
SoGesturePanEvent() [2/2]
SoGesturePanEvent::SoGesturePanEvent (QPanGesture * qpan, QWidget * widget)
Definition at line 45 of file SoTouchEvents.cpp.
References deltaOffset, SoGestureEvent::state, and totalOffset.
~SoGesturePanEvent()
SoGesturePanEvent::~SoGesturePanEvent () override default
Member Function Documentation
initClass()
static void SoGesturePanEvent::initClass () inline static
Definition at line 59 of file SoTouchEvents.h.
Referenced by GesturesDevice::GesturesDevice(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
isSoGesturePanEvent()
SbBool SoGesturePanEvent::isSoGesturePanEvent (const SoEvent * ev) const
Definition at line 59 of file SoTouchEvents.cpp.
Member Data Documentation
deltaOffset
SbVec2f SoGesturePanEvent::deltaOffset
Definition at line 67 of file SoTouchEvents.h.
Referenced by SoGesturePanEvent().
totalOffset
SbVec2f SoGesturePanEvent::totalOffset
Definition at line 68 of file SoTouchEvents.h.
Referenced by SoGesturePanEvent().
The documentation for this class was generated from the following files:
SoTouchEvents.h
SoTouchEvents.cpp