FreeCAD: bimcommands Namespace Reference
bimcommands Namespace Reference
Namespaces
BimArchUtils
BimAxis
BimBackground
BimBeam
BimBox
BimBuilder
BimBuildingPart
BimClassification
BimClone
BimColumn
BimCommon
BimCompound
BimConvert
BimCopy
BimCurtainwall
BimCut
BimCutPlane
BimDiff
BimDimensions
BimDoor
BimDrawingView
BimEmptyTrash
BimEquipment
BimExamples
BimExtrude
BimFence
BimFrame
BimFuse
BimGlue
BimHelp
BimIfcElements
BimIfcExplorer
BimIfcProperties
BimIfcQuantities
BimImagePlane
BimLayers
BimLeader
BimLibrary
BimMaterial
BimMoveView
BimNudge
BimOffset
BimPanel
BimPipe
BimPreflight
BimProfile
BimProject
BimProjectManager
BimRebar
BimReextrude
BimReference
BimReorder
BimResetCloneColors
BimRewire
BimRoof
BimSchedule
BimSectionPlane
BimSetup
BimShape2DView
BimSimpleCopy
BimSite
BimSketch
BimSlab
BimSpace
BimStairs
BimTDPage
BimTDView
BimText
BimTogglePanels
BimTrash
BimTruss
BimTutorial
BimUnclone
BimUngroup
BimViews
BimWall
BimWelcome
BimWindow
BimWindows
BimWPCommands
Variables
modules = glob.glob(os.path.join(os.path.dirname(__file__), "*.py"))
Variable Documentation
modules
bimcommands.modules = glob.glob(os.path.join(os.path.dirname(__file__), "*.py"))
Definition at line 7 of file BIM/bimcommands/__init__.py.
Referenced by Gui::Application.Application(), App::Application.getExportModules(), App::Application.getImportModules(), and Gui::ApplicationPy.sLoadFile().