FreeCAD: Base::PyException Class Reference
Base::PyException Class Reference
#include <Interpreter.h>
Public Member Functions
PyException ()
constructor does the whole job
PyException (const Py::Object &obj)
PyException (const PyException &)=default
PyException (PyException &&)=default
~PyException () noexcept override
PyException & operator= (const PyException &)=default
PyException & operator= (PyException &&)=default
void raiseException ()
const std::string & getStackTrace () const
this function returns the stack trace
const std::string & getErrorType () const
PyObject * getPyExceptionType () const override
returns the corresponding python exception type
void ReportException () const override
Reports exception. It includes a mechanism to only report an exception once.
void setPyException () const override
Sets the Python error indicator and an error message.
Public Member Functions inherited from Base::Exception
Base::Type getTypeId (void) const override
~Exception () noexcept override=default
Exception & operator= (const Exception &inst)
Exception & operator= (Exception &&inst) noexcept
virtual const char * what () const noexcept
void setMessage (const char *sMessage)
void setMessage (const std::string &sMessage)
std::string getMessage () const
std::string getFile () const
int getLine () const
std::string getFunction () const
bool getTranslatable () const
bool getReported () const
void setDebugInformation (const std::string &file, int line, const std::string &function)
void setTranslatable (bool translatable)
void setReported (bool reported)
PyObject * getPyObject () override
returns a Python dictionary containing the exception data
void setPyObject (PyObject *pydict) override
returns sets the exception data from a Python dictionary
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static void ThrowException ()
Static Public Member Functions inherited from Base::Exception
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Additional Inherited Members
Protected Member Functions inherited from Base::Exception
Exception (const char *sMessage)
Exception (std::string sMessage)
Exception ()
Exception (const Exception &inst)
Exception (Exception &&inst) noexcept
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Base::Exception
std::string _sErrMsg
std::string _file
int _line
std::string _function
bool _isTranslatable
bool _isReported
Detailed Description
Definition at line 93 of file Interpreter.h.
Constructor & Destructor Documentation
PyException() [1/4]
PyException::PyException ()
constructor does the whole job
Definition at line 58 of file Interpreter.cpp.
References Base::Exception::_sErrMsg, Path.Log::error(), PP_Fetch_Error_Text(), PP_last_error_info, PP_last_error_trace, PP_last_error_type, PP_last_exception_type, PP_PyDict_Object, and Base::Exception::setPyObject().
PyException() [2/4]
PyException::PyException (const Py::Object & obj) explicit
Definition at line 46 of file Interpreter.cpp.
References Base::Exception::_sErrMsg.
PyException() [3/4]
Base::PyException::PyException (const PyException &) default
PyException() [4/4]
Base::PyException::PyException (PyException &&) default
~PyException()
PyException::~PyException () override default noexcept
Member Function Documentation
getErrorType()
const std::string& Base::PyException::getErrorType () const inline
Definition at line 117 of file Interpreter.h.
Referenced by setPyException().
getPyExceptionType()
PyObject* Base::PyException::getPyExceptionType () const inline override virtual
returns the corresponding python exception type
Reimplemented from Base::Exception.
Definition at line 121 of file Interpreter.h.
Referenced by setPyException().
getStackTrace()
const std::string& Base::PyException::getStackTrace () const inline
this function returns the stack trace
Definition at line 113 of file Interpreter.h.
Referenced by setPyException().
operator=() [1/2]
PyException& Base::PyException::operator= (const PyException &) default
operator=() [2/2]
PyException& Base::PyException::operator= (PyException &&) default
raiseException()
void PyException::raiseException ()
Definition at line 99 of file Interpreter.cpp.
References Base::Exception::_isReported, Base::Exception::_sErrMsg, Base::ExceptionFactory::Instance(), PP_PyDict_Object, Base::PyExc_FC_FreeCADAbort, Base::ExceptionFactory::raiseException(), Base::Exception::setReported(), and src.Mod.Test.testmakeWireString::String.
Referenced by ThrowException().
ReportException()
void PyException::ReportException () const override virtual
Reports exception. It includes a mechanism to only report an exception once.
Reimplemented from Base::Exception.
Definition at line 126 of file Interpreter.cpp.
References Base::Exception::_isReported, Base::Console(), Base::ConsoleSingleton::DeveloperError(), PP_last_traceback, and Base::Exception::what().
Referenced by Gui::RecentMacrosAction::activateFile(), Gui::MDIViewPyWrap::canClose(), Gui::MDIViewPyWrap::MDIViewPyWrap(), Gui::WorkbenchManipulatorPython::modifyContextMenu(), Gui::WorkbenchManipulatorPython::modifyDockWindows(), Gui::WorkbenchManipulatorPython::modifyMenuBar(), Gui::WorkbenchManipulatorPython::modifyToolBars(), Gui::MDIViewPyWrap::onHasMsg(), Gui::MDIViewPyWrap::onMsg(), Gui::GestureNavigationStyle::onRollGesture(), Gui::MDIViewPyWrap::print(), Gui::MDIViewPyWrap::printPdf(), Gui::MDIViewPyWrap::printPreview(), PyMOD_INIT_FUNC(), Gui::MDIViewPyWrap::redoActions(), ThrowException(), Gui::MDIViewPyWrap::undoActions(), and PartDesignGui::TaskMultiTransformParameters::~TaskMultiTransformParameters().
setPyException()
void PyException::setPyException () const override virtual
Sets the Python error indicator and an error message.
Reimplemented from Base::Exception.
Definition at line 141 of file Interpreter.cpp.
References getErrorType(), getPyExceptionType(), getStackTrace(), Path.Post.scripts.refactored_centroid_post::str, and Base::Exception::what().
ThrowException()
void PyException::ThrowException () static
this method determines if the original exception can be reconstructed or not, if yes throws the reconstructed version if not, throws a generic PyException.
Definition at line 92 of file Interpreter.cpp.
References raiseException(), and ReportException().
Referenced by Gui::Command::_runCommand(), App::ObjectIdentifier::Component::del(), Gui::ViewProviderFeaturePythonImp::dropObject(), Gui::ViewProviderFeaturePythonImp::dropObjectEx(), App::FeaturePythonImp::execute(), App::ObjectIdentifier::Component::get(), App::ObjectIdentifier::getPyValue(), App::ObjectIdentifier::getValue(), App::isAnyEqual(), Base::InterpreterSingleton::runString(), Base::InterpreterSingleton::runStringWithKey(), App::ObjectIdentifier::Component::set(), and App::ObjectIdentifier::setValue().
The documentation for this class was generated from the following files:
Interpreter.h
Interpreter.cpp