FreeCAD: MeshGui::MeshSplit Class Reference
MeshGui::MeshSplit Class Reference
Public Member Functions
MeshSplit (ViewProviderMesh *mesh, std::vector< SbVec2f > poly, const Gui::ViewVolumeProjection &proj)
void cutMesh ()
void trimMesh ()
ViewProviderMesh * makeCopy () const
Detailed Description
Definition at line 943 of file Mod/Mesh/Gui/ViewProvider.cpp.
Constructor & Destructor Documentation
MeshSplit()
MeshGui::MeshSplit::MeshSplit (ViewProviderMesh * mesh, std::vector< SbVec2f > poly, const Gui::ViewVolumeProjection & proj) inline
Definition at line 946 of file Mod/Mesh/Gui/ViewProvider.cpp.
Member Function Documentation
cutMesh()
void MeshGui::MeshSplit::cutMesh () inline
Definition at line 953 of file Mod/Mesh/Gui/ViewProvider.cpp.
References MeshGui::ViewProviderMesh::cutMesh(), Gui::ViewProviderDocumentObject::getDocument(), Draft::gui, makeCopy(), and Arch::QT_TRANSLATE_NOOP.
makeCopy()
ViewProviderMesh* MeshGui::MeshSplit::makeCopy () const inline
Definition at line 973 of file Mod/Mesh/Gui/ViewProvider.cpp.
References toolbit-attributes::doc, Gui::ViewProviderDocumentObject::getDocument(), Gui::ViewProviderDocumentObject::getObject(), Draft::gui, App::DocumentObject::Label, and App::PropertyString::setValue().
Referenced by cutMesh(), and trimMesh().
trimMesh()
void MeshGui::MeshSplit::trimMesh () inline
Definition at line 963 of file Mod/Mesh/Gui/ViewProvider.cpp.
References Gui::ViewProviderDocumentObject::getDocument(), Draft::gui, makeCopy(), Arch::QT_TRANSLATE_NOOP, and MeshGui::ViewProviderMesh::trimMesh().
The documentation for this class was generated from the following file:
Mod/Mesh/Gui/ViewProvider.cpp