FreeCAD: ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_representation_item Class Reference
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_representation_item Class Reference
Public Member Functions
def __init__ (self, inherited0__name)
def dim ()
def wr1 (self)
Public Member Functions inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation_item
def name ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Additional Inherited Members
Public Attributes inherited from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation_item
name
Detailed Description
Entity geometric_representation_item definition.
:param dim
:type dim:dimension_count
Definition at line 3108 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Constructor & Destructor Documentation
__init__()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_representation_item.__init__ (self, inherited0__name)
Reimplemented from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation_item.
Reimplemented in ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.point, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.bounded_curve, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.bounded_surface, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.curve, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.camera_model, and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_model.
Definition at line 3114 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
Member Function Documentation
dim()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_representation_item.dim ()
Definition at line 3118 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimension_of().
Referenced by ifc2x3.ifcsweptsurface.dim(), ifc2x3.ifcplacement.dim(), ifc4.ifccompositecurvesegment.dim(), ifc2x3.ifccartesiantransformationoperator.dim(), ifc4.ifcplacement.dim(), ifc2x3.ifccurveboundedplane.dim(), ifc4.ifccartesiantransformationoperator.dim(), ifc2x3.ifccompositecurvesegment.dim(), ifc2x3.ifcgeometricset.dim(), ifc4.ifcgeometricset.dim(), ifc2x3.ifcrectangulartrimmedsurface.dim(), ifc2x3.ifcelementarysurface.dim(), ifc2x3.ifcpointoncurve.dim(), ifc4.ifcpointoncurve.dim(), ifc2x3.ifcpointonsurface.dim(), ifc2x3.ifcvector.dim(), ifc4.ifcpointonsurface.dim(), ifc4.ifcvector.dim(), config_control_design.pcurve.wr3(), and config_control_design.degenerate_pcurve.wr3().
wr1()
def ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_representation_item.wr1 (self)
Reimplemented from ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.representation_item.
Reimplemented in ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimension_text_associativity, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.conical_surface, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.offset_curve_2d, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_flat_bottom_round_hole, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_model_element_relationship, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_replica, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_variable_radius_edge_blend, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_general_protrusion, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_replica, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_general_pocket, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.structured_dimension_callout, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.right_circular_cone, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.advanced_face, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.cartesian_transformation_operator_2d, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_elements, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.b_spline_surface_with_knots, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimension_callout, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.torus, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.rational_b_spline_surface, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.axis2_placement_3d, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_groove, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.seam_curve, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.extruded_face_solid_with_draft_angle, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.ruled_surface_swept_area_solid, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.b_spline_curve_with_knots, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_spherical_bottom_round_hole, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.extruded_face_solid_with_multiple_draft_angles, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.extruded_face_solid_with_trim_conditions, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_text_literal_with_delineation, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.track_blended_solid_with_end_conditions, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.curve_bounded_surface, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.extruded_area_solid, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.degenerate_pcurve, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.annotation_fill_area, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.geometric_curve_set, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.line, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.annotation_plane, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.thickened_face_solid, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.rectangular_trimmed_surface, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.point_replica, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.radius_dimension, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.positioned_sketch, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.face_surface, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_incomplete_rectangular_pattern, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_rectangular_pattern, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.dimension_curve_directed_callout, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.revolved_face_solid_with_trim_conditions, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.degenerate_toroidal_surface, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.track_blended_solid, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_through_depression, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.shell_based_wireframe_model, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.angle_direction_reference, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_circular_pocket, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.right_angular_wedge, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_condition_callout, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.double_offset_shelled_solid, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.bounded_surface_curve, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.projection_directed_callout, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.trimmed_curve, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.intersection_curve, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.bounded_pcurve, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.pcurve, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.vector, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_tee_section_slot, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_rectangular_pocket, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.procedural_shape_representation_sequence, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_stepped_round_hole_and_conical_transitions, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_slot, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.shell_based_surface_model, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.rectangular_composite_surface, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.parabola, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.complex_shelled_solid, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.shelled_solid, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_curve, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.extruded_face_solid, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.swept_face_solid, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.curve_replica, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.swept_disk_solid, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.fill_area_style_tile_coloured_region, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.boundary_curve, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.composite_curve_on_surface, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.composite_curve, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.offset_curve_3d, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.surface_curve_swept_area_solid, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.swept_area_solid, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.light_source, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.direction, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_rectangular_protrusion, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_conical_bottom_round_hole, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_stepped_round_hole, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.rational_b_spline_curve, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.b_spline_curve, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.axis1_placement, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.b_spline_surface, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.composite_text, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.camera_model_d3, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.axis2_placement_2d, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.leader_directed_dimension, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.leader_directed_callout, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.draughting_callout, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.camera_model, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.solid_with_incomplete_circular_pattern, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.cartesian_transformation_operator_3d, and ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.cartesian_transformation_operator.
Definition at line 3126 of file ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py.
References SCL.Builtin.SIZEOF().
Referenced by config_control_design.week_in_year_number.__init__(), config_control_design.minute_in_hour.__init__(), config_control_design.dimension_count.__init__(), config_control_design.positive_length_measure.__init__(), config_control_design.hour_in_day.__init__(), config_control_design.positive_plane_angle_measure.__init__(), ifc2x3.ifctextalignment.__init__(), config_control_design.day_in_week_number.__init__(), ifc4.ifctextalignment.__init__(), ifc2x3.ifcspecularroughness.__init__(), config_control_design.month_in_year_number.__init__(), ifc2x3.ifcheatingvaluemeasure.__init__(), config_control_design.second_in_minute.__init__(), ifc4.ifcspecularroughness.__init__(), automotive_design.minute_in_hour.__init__(), ifc2x3.ifctexttransformation.__init__(), ifc4.ifcheatingvaluemeasure.__init__(), automotive_design.non_negative_length_measure.__init__(), ifc4.ifctexttransformation.__init__(), automotive_design.u_direction_count.__init__(), automotive_design.dimension_count.__init__(), automotive_design.positive_length_measure.__init__(), automotive_design.hour_in_day.__init__(), automotive_design.v_direction_count.__init__(), ifc2x3.ifcfontstyle.__init__(), ifc2x3.ifcboxalignment.__init__(), ifc2x3.ifcminuteinhour.__init__(), automotive_design.day_in_month_number.__init__(), ifc4.ifcfontstyle.__init__(), automotive_design.positive_plane_angle_measure.__init__(), ifc2x3.ifcpositiveplaneanglemeasure.__init__(), ifc4.ifcboxalignment.__init__(), ifc2x3.ifcdimensioncount.__init__(), automotive_design.presentable_text.__init__(), ifc4.ifcpositiveplaneanglemeasure.__init__(), ifc4.ifcdimensioncount.__init__(), ifc2x3.ifcdaylightsavinghour.__init__(), automotive_design.positive_ratio_measure.__init__(), ifc2x3.ifcmonthinyearnumber.__init__(), ifc2x3.ifcsecondinminute.__init__(), ifc2x3.ifcfontvariant.__init__(), automotive_design.month_in_year_number.__init__(), ifc2x3.ifcfontweight.__init__(), ifc2x3.ifchourinday.__init__(), ifc2x3.ifcnormalisedratiomeasure.__init__(), automotive_design.second_in_minute.__init__(), ifc2x3.ifcpositivelengthmeasure.__init__(), ifc2x3.ifcpositiveratiomeasure.__init__(), ifc4.ifcfontvariant.__init__(), ifc4.ifcfontweight.__init__(), ifc2x3.ifctextdecoration.__init__(), ifc4.ifcnormalisedratiomeasure.__init__(), ifc4.ifcpositivelengthmeasure.__init__(), ifc4.ifcpositiveratiomeasure.__init__(), and ifc4.ifctextdecoration.__init__().
The documentation for this class was generated from the following file:
ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf.py