FreeCAD: Gui::ApplicationPy Class Reference
Gui::ApplicationPy Class Reference
#include <ApplicationPy.h>
Static Public Member Functions
static PyObject * sActivateWorkbenchHandler (PyObject *self, PyObject *args)
static PyObject * sAddWorkbenchHandler (PyObject *self, PyObject *args)
static PyObject * sRemoveWorkbenchHandler (PyObject *self, PyObject *args)
static PyObject * sGetWorkbenchHandler (PyObject *self, PyObject *args)
static PyObject * sListWorkbenchHandlers (PyObject *self, PyObject *args)
static PyObject * sActiveWorkbenchHandler (PyObject *self, PyObject *args)
static PyObject * sAddResPath (PyObject *self, PyObject *args)
static PyObject * sAddLangPath (PyObject *self, PyObject *args)
static PyObject * sAddIconPath (PyObject *self, PyObject *args)
static PyObject * sAddIcon (PyObject *self, PyObject *args)
static PyObject * sGetIcon (PyObject *self, PyObject *args)
static PyObject * sIsIconCached (PyObject *self, PyObject *args)
static PyObject * sSendActiveView (PyObject *self, PyObject *args)
static PyObject * sSendFocusView (PyObject *self, PyObject *args)
static PyObject * sGetMainWindow (PyObject *self, PyObject *args)
static PyObject * sUpdateGui (PyObject *self, PyObject *args)
static PyObject * sUpdateLocale (PyObject *self, PyObject *args)
static PyObject * sGetLocale (PyObject *self, PyObject *args)
static PyObject * sSetLocale (PyObject *self, PyObject *args)
static PyObject * sSupportedLocales (PyObject *self, PyObject *args)
static PyObject * sCreateDialog (PyObject *self, PyObject *args)
static PyObject * sAddPreferencePage (PyObject *self, PyObject *args)
static PyObject * sRunCommand (PyObject *self, PyObject *args)
static PyObject * sAddCommand (PyObject *self, PyObject *args)
static PyObject * sHide (PyObject *self, PyObject *args)
static PyObject * sShow (PyObject *self, PyObject *args)
static PyObject * sHideObject (PyObject *self, PyObject *args)
static PyObject * sShowObject (PyObject *self, PyObject *args)
static PyObject * sOpen (PyObject *self, PyObject *args)
static PyObject * sInsert (PyObject *self, PyObject *args)
static PyObject * sExport (PyObject *self, PyObject *args)
static PyObject * sReload (PyObject *self, PyObject *args)
static PyObject * sLoadFile (PyObject *self, PyObject *args)
static PyObject * sCoinRemoveAllChildren (PyObject *self, PyObject *args)
static PyObject * sActiveDocument (PyObject *self, PyObject *args)
static PyObject * sSetActiveDocument (PyObject *self, PyObject *args)
static PyObject * sActiveView (PyObject *self, PyObject *args)
static PyObject * sActivateView (PyObject *self, PyObject *args)
static PyObject * sGetDocument (PyObject *self, PyObject *args)
static PyObject * sEditDocument (PyObject *self, PyObject *args)
static PyObject * sDoCommand (PyObject *self, PyObject *args)
static PyObject * sDoCommandGui (PyObject *self, PyObject *args)
static PyObject * sDoCommandEval (PyObject *self, PyObject *args)
static PyObject * sDoCommandSkip (PyObject *self, PyObject *args)
static PyObject * sAddModule (PyObject *self, PyObject *args)
static PyObject * sShowDownloads (PyObject *self, PyObject *args)
static PyObject * sShowPreferences (PyObject *self, PyObject *args)
static PyObject * sShowPreferencesByName (PyObject *self, PyObject *args)
static PyObject * sCreateViewer (PyObject *self, PyObject *args)
static PyObject * sGetMarkerIndex (PyObject *self, PyObject *args)
static PyObject * sAddDocObserver (PyObject *self, PyObject *args)
static PyObject * sRemoveDocObserver (PyObject *self, PyObject *args)
static PyObject * sAddWbManipulator (PyObject *self, PyObject *args)
static PyObject * sRemoveWbManipulator (PyObject *self, PyObject *args)
static PyObject * sListUserEditModes (PyObject *self, PyObject *args)
static PyObject * sGetUserEditMode (PyObject *self, PyObject *args)
static PyObject * sSetUserEditMode (PyObject *self, PyObject *args)
Static Public Attributes
static PyMethodDef Methods []
Detailed Description
The ApplicationPy class This is the Python wrapper class of Application.
Author
Jürgen Riegel, Werner Mayer
Definition at line 55 of file ApplicationPy.h.
Member Function Documentation
sActivateView()
PyObject * Gui::ApplicationPy::sActivateView (PyObject * self, PyObject * args) static
Definition at line 502 of file Gui/ApplicationPy.cpp.
References Gui::Application::activateView(), toolbit-attributes::args, Base::asBoolean(), importers.importIFClegacy::create(), Base::Type::fromName(), Gui::Application::Instance, Py_Return, and Path.Post.scripts.grbl_post::type.
sActivateWorkbenchHandler()
PyObject * ApplicationPy::sActivateWorkbenchHandler (PyObject * self, PyObject * args) static
Definition at line 972 of file Gui/ApplicationPy.cpp.
References Gui::Application::activateWorkbench(), toolbit-attributes::args, SCL.SimpleDataTypes::e, Gui::Application::Instance, Py::new_reference_to(), Base::PyExc_FC_GeneralError, and XERCES_CPP_NAMESPACE_QUALIFIER.
sActiveDocument()
PyObject * Gui::ApplicationPy::sActiveDocument (PyObject * self, PyObject * args) static
Definition at line 448 of file Gui/ApplicationPy.cpp.
References Gui::Application::activeDocument(), toolbit-attributes::args, Gui::Document::getPyObject(), Gui::Application::Instance, and Py_Return.
sActiveView()
PyObject * Gui::ApplicationPy::sActiveView (PyObject * self, PyObject * args) static
Definition at line 462 of file Gui/ApplicationPy.cpp.
References Gui::Application::activateView(), Gui::Application::activeView(), toolbit-attributes::args, Base::Type::fromName(), Base::BaseClass::getClassTypeId(), Gui::MDIView::getPyObject(), Gui::Application::Instance, Base::BaseClass::isDerivedFrom(), Py::new_reference_to(), PY_CATCH, Py_Return, PY_TRY, and Path.Post.scripts.grbl_post::type.
sActiveWorkbenchHandler()
PyObject * ApplicationPy::sActiveWorkbenchHandler (PyObject * self, PyObject * args) static
Definition at line 1123 of file Gui/ApplicationPy.cpp.
References Gui::WorkbenchManager::active(), toolbit-attributes::args, Gui::WorkbenchManager::instance(), Gui::Application::Instance, and Gui::Workbench::name().
sAddCommand()
PyObject * ApplicationPy::sAddCommand (PyObject * self, PyObject * args) static
Definition at line 1276 of file Gui/ApplicationPy.cpp.
References Gui::CommandManager::addCommand(), toolbit-attributes::args, Gui::Application::commandManager(), SCL.SimpleDataTypes::e, DrawingExample::file, Base::FileInfo::fileNamePure(), Base::FileInfo::filePath(), toolbit-attributes::group, Path.Log::info(), Gui::Application::Instance, mod, src.Mod.PartDesign.fcgear.svggear::module, Py_Return, Base::PyExc_FC_GeneralError, Gui::Command::setAppModuleName(), and Gui::Command::setGroupName().
sAddDocObserver()
PyObject * ApplicationPy::sAddDocObserver (PyObject * self, PyObject * args) static
Definition at line 1688 of file Gui/ApplicationPy.cpp.
References Gui::DocumentObserverPython::addObserver(), toolbit-attributes::args, src.Mod.Test.testPathArray::o, PY_CATCH, Py_Return, and PY_TRY.
sAddIcon()
PyObject * ApplicationPy::sAddIcon (PyObject * self, PyObject * args) static
Definition at line 1209 of file Gui/ApplicationPy.cpp.
References Gui::BitmapFactoryInst::addPixmapToCache(), toolbit-attributes::args, Gui::BitmapFactory(), DrawingExample::file, Py_Return, and Base::PyExc_FC_GeneralError.
sAddIconPath()
PyObject * ApplicationPy::sAddIconPath (PyObject * self, PyObject * args) static
Definition at line 1189 of file Gui/ApplicationPy.cpp.
References Gui::BitmapFactoryInst::addPath(), toolbit-attributes::args, Gui::BitmapFactory(), Path.Preferences::filePath(), App::Application::getHomePath(), Path.Post.scripts.rml_post::home(), src.Mod.Test.testPathArray::path, and Py_Return.
sAddLangPath()
PyObject * ApplicationPy::sAddLangPath (PyObject * self, PyObject * args) static
Definition at line 1169 of file Gui/ApplicationPy.cpp.
References Gui::Translator::addPath(), toolbit-attributes::args, Path.Preferences::filePath(), App::Application::getHomePath(), Path.Post.scripts.rml_post::home(), Gui::Translator::instance(), src.Mod.Test.testPathArray::path, and Py_Return.
sAddModule()
PyObject * ApplicationPy::sAddModule (PyObject * self, PyObject * args) static
Definition at line 1491 of file Gui/ApplicationPy.cpp.
References Gui::Command::addModule(), toolbit-attributes::args, Gui::Command::Doc, SCL.SimpleDataTypes::e, and Py_Return.
sAddPreferencePage()
PyObject * ApplicationPy::sAddPreferencePage (PyObject * self, PyObject * args) static
Definition at line 944 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, toolbit-attributes::grp, and Py_Return.
sAddResPath()
PyObject * ApplicationPy::sAddResPath (PyObject * self, PyObject * args) static
Definition at line 1148 of file Gui/ApplicationPy.cpp.
References Gui::BitmapFactoryInst::addPath(), Gui::Translator::addPath(), toolbit-attributes::args, Gui::BitmapFactory(), Path.Preferences::filePath(), App::Application::getHomePath(), Path.Post.scripts.rml_post::home(), Gui::Translator::instance(), src.Mod.Test.testPathArray::path, and Py_Return.
sAddWbManipulator()
PyObject * ApplicationPy::sAddWbManipulator (PyObject * self, PyObject * args) static
Definition at line 1716 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Gui::WorkbenchManipulatorPython::installManipulator(), src.Mod.Test.testPathArray::o, PY_CATCH, Py_Return, and PY_TRY.
sAddWorkbenchHandler()
PyObject * ApplicationPy::sAddWorkbenchHandler (PyObject * self, PyObject * args) static
Definition at line 1016 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, importers.importIFClegacy::getAttr(), Gui::Application::Instance, src.Mod.PartDesign.fcgear.svggear::module, Py_Return, Gui::Application::signalRefreshWorkbenches, and src.Mod.Test.testmakeWireString::String.
sCoinRemoveAllChildren()
PyObject * ApplicationPy::sCoinRemoveAllChildren (PyObject * self, PyObject * args) static
Definition at line 1744 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Gui::coinRemoveAllChildren(), Base::InterpreterSingleton::convertSWIGPointerObj(), Base::Interpreter(), PY_CATCH, Py_Return, and PY_TRY.
sCreateDialog()
PyObject * ApplicationPy::sCreateDialog (PyObject * self, PyObject * args) static
Definition at line 923 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, and SCL.SimpleDataTypes::e.
sCreateViewer()
PyObject * ApplicationPy::sCreateViewer (PyObject * self, PyObject * args) static
Definition at line 1561 of file Gui/ApplicationPy.cpp.
References Gui::MainWindow::addWindow(), toolbit-attributes::args, Gui::getMainWindow(), Plot::title(), and OfflineRenderingUtils::viewer().
sDoCommand()
PyObject * ApplicationPy::sDoCommand (PyObject * self, PyObject * args) static
Definition at line 1389 of file Gui/ApplicationPy.cpp.
References Gui::MacroManager::addLine(), Gui::MacroManager::App, toolbit-attributes::args, Path.Base.SetupSheet::dict, Gui::Application::Instance, Gui::Application::macroManager(), src.Mod.PartDesign.fcgear.svggear::module, and Gui::Command::printPyCaller().
sDoCommandEval()
PyObject * ApplicationPy::sDoCommandEval (PyObject * self, PyObject * args) static
Definition at line 1449 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Path.Base.SetupSheet::dict, and src.Mod.PartDesign.fcgear.svggear::module.
sDoCommandGui()
PyObject * ApplicationPy::sDoCommandGui (PyObject * self, PyObject * args) static
Definition at line 1419 of file Gui/ApplicationPy.cpp.
References Gui::MacroManager::addLine(), toolbit-attributes::args, Path.Base.SetupSheet::dict, Gui::MacroManager::Gui, Gui::Application::Instance, Gui::Application::macroManager(), src.Mod.PartDesign.fcgear.svggear::module, and Gui::Command::printPyCaller().
sDoCommandSkip()
PyObject * ApplicationPy::sDoCommandSkip (PyObject * self, PyObject * args) static
Definition at line 1476 of file Gui/ApplicationPy.cpp.
References Gui::MacroManager::addLine(), Gui::MacroManager::App, toolbit-attributes::args, Gui::Application::Instance, Gui::Application::macroManager(), and Gui::Command::printPyCaller().
sEditDocument()
PyObject * Gui::ApplicationPy::sEditDocument (PyObject * self, PyObject * args) static
Definition at line 434 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Gui::Application::editDocument(), Gui::Document::getPyObject(), Gui::Application::Instance, and Py_Return.
sExport()
PyObject * ApplicationPy::sExport (PyObject * self, PyObject * args) static
Definition at line 693 of file Gui/ApplicationPy.cpp.
References Path.Post.scripts.dynapath_4060_post::action, toolbit-attributes::args, Base::Console(), toolbit-attributes::doc, Base::ConsoleSingleton::Error(), create_qrc::ext, Gui::Document::getActiveView(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::ViewProvider::getRoot(), Gui::Application::getViewProvider(), Gui::Application::Instance, Gui::MDIView::print(), PY_CATCH, Py_Return, PY_TRY, and Gui::SoFCDB::writeToFile().
sGetDocument()
PyObject * ApplicationPy::sGetDocument (PyObject * self, PyObject * args) static
Definition at line 559 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, toolbit-attributes::doc, Gui::Application::getDocument(), Gui::Document::getPyObject(), and Gui::Application::Instance.
sGetIcon()
PyObject * ApplicationPy::sGetIcon (PyObject * self, PyObject * args) static
Definition at line 1246 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Gui::BitmapFactory(), Gui::PythonWrapper::fromQIcon(), Gui::PythonWrapper::loadGuiModule(), Gui::PythonWrapper::loadWidgetsModule(), Py::new_reference_to(), Gui::BitmapFactoryInst::pixmap(), and Py_Return.
sGetLocale()
PyObject * ApplicationPy::sGetLocale (PyObject * self, PyObject * args) static
Definition at line 876 of file Gui/ApplicationPy.cpp.
References Gui::Translator::activeLanguage(), toolbit-attributes::args, and Gui::Translator::instance().
sGetMainWindow()
PyObject * ApplicationPy::sGetMainWindow (PyObject * self, PyObject * args) static
Definition at line 840 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Gui::MainWindowPy::createWrapper(), Gui::getMainWindow(), and Py::new_reference_to().
sGetMarkerIndex()
PyObject * ApplicationPy::sGetMarkerIndex (PyObject * self, PyObject * args) static
Definition at line 1592 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, defaultSize, DraftVecUtils::find(), App::GetApplication(), Gui::Inventor::MarkerBitmaps::getMarkerIndex(), App::Application::GetParameterGroupByPath(), Gui::Inventor::MarkerBitmaps::getSupportedSizes(), PY_CATCH, and PY_TRY.
sGetUserEditMode()
PyObject * ApplicationPy::sGetUserEditMode (PyObject * self, PyObject * args) static
Definition at line 1779 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Gui::Application::Instance, Py::new_reference_to(), and src.Mod.Test.testmakeWireString::String.
sGetWorkbenchHandler()
PyObject * ApplicationPy::sGetWorkbenchHandler (PyObject * self, PyObject * args) static
Definition at line 1095 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, and Gui::Application::Instance.
sHide()
PyObject * ApplicationPy::sHide (PyObject * self, PyObject * args) static
Definition at line 587 of file Gui/ApplicationPy.cpp.
References Gui::Application::activeDocument(), toolbit-attributes::args, Gui::Application::Instance, Py_Return, and Gui::Document::setHide().
sHideObject()
PyObject * ApplicationPy::sHideObject (PyObject * self, PyObject * args) static
Definition at line 619 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Gui::Application::hideViewProvider(), Gui::Application::Instance, and Py_Return.
sInsert()
PyObject * ApplicationPy::sInsert (PyObject * self, PyObject * args) static
Definition at line 670 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Base::Console(), Base::ConsoleSingleton::Error(), create_qrc::ext, buildPsets::handler, PY_CATCH, Py_Return, and PY_TRY.
sIsIconCached()
PyObject * ApplicationPy::sIsIconCached (PyObject * self, PyObject * args) static
Definition at line 1264 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Gui::BitmapFactory(), and Py::new_reference_to().
sListUserEditModes()
PyObject * ApplicationPy::sListUserEditModes (PyObject * self, PyObject * args) static
Definition at line 1765 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Gui::Application::Instance, Py::new_reference_to(), and src.Mod.Test.testmakeWireString::String.
sListWorkbenchHandlers()
PyObject * ApplicationPy::sListWorkbenchHandlers (PyObject * self, PyObject * args) static
Definition at line 1113 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, and Gui::Application::Instance.
sLoadFile()
PyObject * ApplicationPy::sLoadFile (PyObject * self, PyObject * args) static
Definition at line 1654 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Base::FileInfo::exists(), create_qrc::ext, Base::FileInfo::extension(), App::GetApplication(), App::Application::getImportModules(), Gui::Application::Instance, Base::FileInfo::isFile(), mod, src.Mod.PartDesign.fcgear.svggear::module, bimcommands::modules, Gui::Application::open(), src.Mod.Test.testPathArray::path, PY_CATCH, Py_Return, and PY_TRY.
sOpen()
PyObject * ApplicationPy::sOpen (PyObject * self, PyObject * args) static
Definition at line 647 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Base::Console(), Base::ConsoleSingleton::Error(), create_qrc::ext, buildPsets::handler, PY_CATCH, Py_Return, and PY_TRY.
sReload()
PyObject * ApplicationPy::sReload (PyObject * self, PyObject * args) static
Definition at line 1637 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, toolbit-attributes::doc, App::GetApplication(), Gui::Application::Instance, PY_CATCH, Py_Return, PY_TRY, and Gui::Application::reopen().
sRemoveDocObserver()
PyObject * ApplicationPy::sRemoveDocObserver (PyObject * self, PyObject * args) static
Definition at line 1702 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, src.Mod.Test.testPathArray::o, PY_CATCH, Py_Return, PY_TRY, and Gui::DocumentObserverPython::removeObserver().
sRemoveWbManipulator()
PyObject * ApplicationPy::sRemoveWbManipulator (PyObject * self, PyObject * args) static
Definition at line 1730 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, src.Mod.Test.testPathArray::o, PY_CATCH, Py_Return, PY_TRY, and Gui::WorkbenchManipulatorPython::removeManipulator().
sRemoveWorkbenchHandler()
PyObject * ApplicationPy::sRemoveWorkbenchHandler (PyObject * self, PyObject * args) static
Definition at line 1075 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Gui::WorkbenchManager::instance(), Gui::Application::Instance, Py_Return, Gui::WorkbenchManager::removeWorkbench(), and Gui::Application::signalRefreshWorkbenches.
sRunCommand()
PyObject * ApplicationPy::sRunCommand (PyObject * self, PyObject * args) static
Definition at line 1368 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Gui::Application::commandManager(), Gui::CommandManager::getCommandByName(), Gui::Application::Instance, Gui::Command::invoke(), Py_Return, and Base::PyExc_FC_GeneralError.
sSendActiveView()
PyObject * ApplicationPy::sSendActiveView (PyObject * self, PyObject * args) static
Definition at line 792 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Base::asBoolean(), Base::Console(), Gui::Application::Instance, Py_Return, and Base::ConsoleSingleton::Warning().
sSendFocusView()
PyObject * ApplicationPy::sSendFocusView (PyObject * self, PyObject * args) static
Definition at line 816 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Base::asBoolean(), Base::Console(), Gui::Application::Instance, Py_Return, and Base::ConsoleSingleton::Warning().
sSetActiveDocument()
PyObject * Gui::ApplicationPy::sSetActiveDocument (PyObject * self, PyObject * args) static
Definition at line 517 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, toolbit-attributes::doc, Gui::Document::getActiveView(), Gui::Application::getDocument(), Gui::getMainWindow(), Gui::Application::Instance, Py_Return, and Gui::MainWindow::setActiveWindow().
sSetLocale()
PyObject * ApplicationPy::sSetLocale (PyObject * self, PyObject * args) static
Definition at line 886 of file Gui/ApplicationPy.cpp.
References Gui::Translator::activateLanguage(), toolbit-attributes::args, Gui::Translator::instance(), Py_Return, and Gui::Translator::supportedLocales().
sSetUserEditMode()
PyObject * ApplicationPy::sSetUserEditMode (PyObject * self, PyObject * args) static
Definition at line 1788 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Gui::Application::Instance, Py::new_reference_to(), and Gui::Application::setUserEditMode().
sShow()
PyObject * ApplicationPy::sShow (PyObject * self, PyObject * args) static
Definition at line 603 of file Gui/ApplicationPy.cpp.
References Gui::Application::activeDocument(), toolbit-attributes::args, Gui::Application::Instance, Py_Return, and Gui::Document::setShow().
sShowDownloads()
PyObject * ApplicationPy::sShowDownloads (PyObject * self, PyObject * args) static
Definition at line 1508 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Gui::Dialog::DownloadManager::getInstance(), and Py_Return.
sShowObject()
PyObject * ApplicationPy::sShowObject (PyObject * self, PyObject * args) static
Definition at line 633 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Gui::Application::Instance, Py_Return, and Gui::Application::showViewProvider().
sShowPreferences()
PyObject * ApplicationPy::sShowPreferences (PyObject * self, PyObject * args) static
Definition at line 1519 of file Gui/ApplicationPy.cpp.
References Gui::Dialog::DlgPreferencesImp::activateGroupPage(), toolbit-attributes::args, Gui::getMainWindow(), Py_Return, Gui::WaitCursor::restoreCursor(), and Gui::WaitCursor::setWaitCursor().
sShowPreferencesByName()
PyObject * ApplicationPy::sShowPreferencesByName (PyObject * self, PyObject * args) static
Definition at line 1540 of file Gui/ApplicationPy.cpp.
References Gui::Dialog::DlgPreferencesImp::activateGroupPageByPageName(), toolbit-attributes::args, Gui::getMainWindow(), Py_Return, Gui::WaitCursor::restoreCursor(), and Gui::WaitCursor::setWaitCursor().
sSupportedLocales()
PyObject * ApplicationPy::sSupportedLocales (PyObject * self, PyObject * args) static
Definition at line 906 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Path.Base.SetupSheet::dict, Gui::Translator::instance(), Py::new_reference_to(), src.Mod.Test.testmakeWireString::String, Gui::Translator::supportedLocales(), and toolbit-attributes::val.
sUpdateGui()
PyObject * ApplicationPy::sUpdateGui (PyObject * self, PyObject * args) static
Definition at line 854 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, and Py_Return.
sUpdateLocale()
PyObject * ApplicationPy::sUpdateLocale (PyObject * self, PyObject * args) static
Definition at line 865 of file Gui/ApplicationPy.cpp.
References toolbit-attributes::args, Gui::Translator::instance(), Py_Return, and Gui::Translator::refresh().
Member Data Documentation
Methods
PyMethodDef ApplicationPy::Methods static
Definition at line 154 of file ApplicationPy.h.
Referenced by Gui::Application::Application().
The documentation for this class was generated from the following files:
ApplicationPy.h
Gui/ApplicationPy.cpp