FreeCAD: Gui::PrefPageUiProducer Class Reference
Gui::PrefPageUiProducer Class Reference
#include <WidgetFactory.h>
Public Member Functions
PrefPageUiProducer (const char *filename, const char *group)
~PrefPageUiProducer () override
void * Produce () const override
Public Member Functions inherited from Base::AbstractProducer
AbstractProducer ()=default
virtual ~AbstractProducer ()=default
Detailed Description
The PrefPageUiProducer class provides the ability to create preference pages dynamically from an external UI file.
Author
Werner Mayer
Definition at line 148 of file WidgetFactory.h.
Constructor & Destructor Documentation
PrefPageUiProducer()
PrefPageUiProducer::PrefPageUiProducer (const char * filename, const char * group)
Register a special type of preference page to the WidgetFactoryInst.
Definition at line 206 of file WidgetFactory.cpp.
References Gui::Dialog::DlgPreferencesImp::addPage(), Base::Factory::AddProducer(), toolbit-attributes::group, and Gui::WidgetFactoryInst::instance().
~PrefPageUiProducer()
PrefPageUiProducer::~PrefPageUiProducer () override default
Member Function Documentation
Produce()
void * PrefPageUiProducer::Produce () const override virtual
Creates an instance of the specified widget.
Implements Base::AbstractProducer.
Definition at line 215 of file WidgetFactory.cpp.
The documentation for this class was generated from the following files:
WidgetFactory.h
WidgetFactory.cpp