FreeCAD: CommandDoc.cpp File Reference
CommandDoc.cpp File Reference
#include "PreCompiled.h"
#include <Inventor/nodes/SoCamera.h>
#include <QApplication>
#include <QCheckBox>
#include <QClipboard>
#include <QDateTime>
#include <QMessageBox>
#include <QTextStream>
#include <QTreeWidgetItem>
#include <boost/regex.hpp>
#include <boost/algorithm/string/replace.hpp>
#include <App/AutoTransaction.h>
#include <App/Document.h>
#include <App/DocumentObject.h>
#include <App/Expression.h>
#include <App/GeoFeature.h>
#include <Base/Exception.h>
#include <Base/FileInfo.h>
#include <Base/Stream.h>
#include <Base/Tools.h>
#include "Action.h"
#include "Application.h"
#include "BitmapFactory.h"
#include "Command.h"
#include "Control.h"
#include "DockWindowManager.h"
#include "FileDialog.h"
#include "MainWindow.h"
#include "Selection.h"
#include "DlgObjectSelection.h"
#include "DlgProjectInformationImp.h"
#include "DlgProjectUtility.h"
#include "GraphvizView.h"
#include "ManualAlignment.h"
#include "MergeDocuments.h"
#include "NavigationStyle.h"
#include "Placement.h"
#include "Transform.h"
#include "View3DInventor.h"
#include "View3DInventorViewer.h"
#include "ViewProvider.h"
#include "WaitCursor.h"
Classes
class StdCmdOpen
class StdCmdImport
class StdCmdExport
class StdCmdMergeProjects
class StdCmdDependencyGraph
class StdCmdExportDependencyGraph
class StdCmdNew
class StdCmdSave
class StdCmdSaveAs
class StdCmdSaveCopy
class StdCmdSaveAll
class StdCmdRevert
class StdCmdProjectInfo
class StdCmdProjectUtil
class StdCmdPrint
class StdCmdPrintPreview
class StdCmdPrintPdf
class StdCmdQuit
class StdCmdUndo
class StdCmdRedo
class StdCmdCut
class StdCmdCopy
class StdCmdPaste
class StdCmdDuplicateSelection
class StdCmdSelectAll
class StdCmdDelete
class StdCmdRefresh
class StdCmdTransform
class StdCmdPlacement
class StdCmdTransformManip
class StdCmdAlignment
class StdCmdEdit
class StdCmdProperties
class StdCmdExpression
Namespaces
Gui
Functions
QString createDefaultExportBasename ()
void Gui::CreateDocCommands ()
Function Documentation
createDefaultExportBasename()
QString createDefaultExportBasename ()
Create a default filename from a user-specified format string
Format options are: F - the basename of the .FCStd file (or the label, if it is not saved yet) Lx - the label of the selected object(s), separated by character 'x' Px - the label of the selected object(s) and their first parent, separated by character 'x' U - the date and time, in UTC, ISO 8601 D - the date and time, in local timezone, ISO 8601 Any other characters are treated literally, though if the filename is illegal it will be changed on saving.
The format string is stored in two user preferences (not currently exposed in the GUI): BaseApp/Preferences/General/ExportDefaultFilenameSingle BaseApp/Preferences/General/ExportDefaultFilenameMultiple
Definition at line 315 of file CommandDoc.cpp.
References SCL.SimpleDataTypes::c, FC_WARN, App::GetApplication(), Base::Persistence::getClassTypeId(), Gui::SelectionSingleton::getObjectsOfType(), SplineSurface::i, Path.Dressup.Utils::selection(), and Gui::Selection().
Referenced by StdCmdExport::activated().