FreeCAD: Inspection::InspectNominalFastMesh Class Reference
Inspection::InspectNominalFastMesh Class Reference
#include <InspectionFeature.h>
Public Member Functions
InspectNominalFastMesh (const Mesh::MeshObject &rMesh, float offset)
~InspectNominalFastMesh () override
float getDistance (const Base::Vector3f &) const override
Public Member Functions inherited from Inspection::InspectNominalGeometry
InspectNominalGeometry ()=default
virtual ~InspectNominalGeometry ()=default
Protected Attributes
const MeshCore::MeshKernel & _mesh
MeshCore::MeshGrid * _pGrid
Base::BoundBox3f _box
unsigned long max_level
bool _bApply
Base::Matrix4D _clTrf
Detailed Description
Definition at line 134 of file InspectionFeature.h.
Constructor & Destructor Documentation
InspectNominalFastMesh()
InspectNominalFastMesh::InspectNominalFastMesh (const Mesh::MeshObject & rMesh, float offset)
Definition at line 353 of file InspectionFeature.cpp.
References _bApply, _box, _clTrf, _pGrid, MengerSponge::box, Base::BoundBox3< Precision >::Enlarge(), MeshCore::MeshAlgorithm::GetAverageEdgeLength(), MeshCore::MeshKernel::GetBoundBox(), Mesh::MeshObject::getKernel(), Mesh::MeshObject::getTransform(), OpenSCADFeatures::long, max_level, Base::pow(), and Base::BoundBox3< Precision >::Transformed().
~InspectNominalFastMesh()
InspectNominalFastMesh::~InspectNominalFastMesh () override
Definition at line 384 of file InspectionFeature.cpp.
References _pGrid.
Member Function Documentation
getDistance()
float InspectNominalFastMesh::getDistance (const Base::Vector3f & point) const override virtual
This algorithm is not that exact as that from InspectNominalMesh but is by factors faster and sufficient for many cases.
Implements Inspection::InspectNominalGeometry.
Definition at line 393 of file InspectionFeature.cpp.
References MeshCore::MeshGeomFacet::_aclPoints, _bApply, _box, _clTrf, _mesh, _pGrid, MeshCore::MeshGeomFacet::DistanceToPoint(), MeshCore::MeshGrid::GetElements(), MeshCore::MeshKernel::GetFacet(), MeshCore::MeshGrid::GetHull(), MeshCore::MeshGeomFacet::GetNormal(), Base::BoundBox3< Precision >::IsInBox(), max_level, MeshCore::MeshGrid::Position(), and MeshCore::MeshGeomFacet::Transform().
Member Data Documentation
_bApply
bool Inspection::InspectNominalFastMesh::_bApply protected
Definition at line 146 of file InspectionFeature.h.
Referenced by getDistance(), and InspectNominalFastMesh().
_box
Base::BoundBox3f Inspection::InspectNominalFastMesh::_box protected
Definition at line 144 of file InspectionFeature.h.
Referenced by getDistance(), and InspectNominalFastMesh().
_clTrf
Base::Matrix4D Inspection::InspectNominalFastMesh::_clTrf protected
Definition at line 147 of file InspectionFeature.h.
Referenced by getDistance(), and InspectNominalFastMesh().
_mesh
const MeshCore::MeshKernel& Inspection::InspectNominalFastMesh::_mesh protected
Definition at line 142 of file InspectionFeature.h.
Referenced by getDistance().
_pGrid
MeshCore::MeshGrid* Inspection::InspectNominalFastMesh::_pGrid protected
Definition at line 143 of file InspectionFeature.h.
Referenced by getDistance(), InspectNominalFastMesh(), and ~InspectNominalFastMesh().
max_level
unsigned long Inspection::InspectNominalFastMesh::max_level protected
Definition at line 145 of file InspectionFeature.h.
Referenced by getDistance(), and InspectNominalFastMesh().
The documentation for this class was generated from the following files:
InspectionFeature.h
InspectionFeature.cpp