FreeCAD: Path.Tool.Bit.ToolBitFactory Class Reference
Path.Tool.Bit.ToolBitFactory Class Reference
Public Member Functions
def CreateFromAttrs (self, attrs, name="ToolBit", path=None)
def CreateFrom (self, path, name="ToolBit")
def Create (self, name="ToolBit", shapeFile=None, path=None)
Detailed Description
Definition at line 465 of file Bit.py.
Member Function Documentation
Create()
def Path.Tool.Bit.ToolBitFactory.Create (self, name = "ToolBit", shapeFile = None, path = None)
Definition at line 493 of file Bit.py.
References Path.Log.track().
CreateFrom()
def Path.Tool.Bit.ToolBitFactory.CreateFrom (self, path, name = "ToolBit")
Definition at line 480 of file Bit.py.
References Path.Tool.Bit.Declaration(), Path.Log.error(), and Path.Log.track().
CreateFromAttrs()
def Path.Tool.Bit.ToolBitFactory.CreateFromAttrs (self, attrs, name = "ToolBit", path = None)
Definition at line 466 of file Bit.py.
References Path.Log.track().
The documentation for this class was generated from the following file:
Bit.py