FreeCAD: importers.importSH3D Namespace Reference
importers.importSH3D Namespace Reference
Functions
def open (filename)
def insert (filename, docname)
def read (filename)
Variables
bool DEBUG = True
Function Documentation
insert()
def importers.importSH3D.insert (filename, docname)
Definition at line 53 of file importSH3D.py.
References importers.importSH3D.read().
open()
def importers.importSH3D.open (filename)
Definition at line 43 of file importSH3D.py.
References importers.importSH3D.read().
read()
def importers.importSH3D.read (filename)
Definition at line 64 of file importSH3D.py.
Referenced by importers.importSH3D.insert(), and importers.importSH3D.open().
Variable Documentation
DEBUG
bool importers.importSH3D.DEBUG = True
Definition at line 40 of file importSH3D.py.