FreeCAD: ifc2x3.ifcrelassigns Class Reference
ifc2x3.ifcrelassigns Class Reference
Public Member Functions
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, relatedobjects, relatedobjectstype)
def relatedobjects ()
def relatedobjectstype ()
def wr1 (self)
Public Member Functions inherited from ifc2x3.ifcrelationship
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description)
Public Member Functions inherited from ifc2x3.ifcroot
def globalid ()
def ownerhistory ()
def name ()
def description ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
relatedobjects
relatedobjectstype
Public Attributes inherited from ifc2x3.ifcroot
globalid
ownerhistory
name
description
Detailed Description
Entity ifcrelassigns definition.
:param relatedobjects
:type relatedobjects:SET(1,None,'ifcobjectdefinition', scope = schema_scope)
:param relatedobjectstype
:type relatedobjectstype:ifcobjecttypeenum
Definition at line 2703 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcrelassigns.__init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, relatedobjects, relatedobjectstype)
Definition at line 2712 of file ifc2x3.py.
Member Function Documentation
relatedobjects()
def ifc2x3.ifcrelassigns.relatedobjects ()
Definition at line 2718 of file ifc2x3.py.
References ifc2x3.ifcrelassigns._relatedobjects, SCL.TypeChecker.check_type(), and ifc2x3.ifcrelassigns.relatedobjects.
relatedobjectstype()
def ifc2x3.ifcrelassigns.relatedobjectstype ()
Definition at line 2732 of file ifc2x3.py.
References ifc2x3.ifcrelassigns._relatedobjectstype, SCL.TypeChecker.check_type(), and ifc2x3.ifcrelassigns.relatedobjectstype.
wr1()
def ifc2x3.ifcrelassigns.wr1 (self)
Reimplemented in ifc2x3.ifcrelassignstoactor, ifc2x3.ifcrelassignstoresource, ifc2x3.ifcrelassignstoprocess, ifc2x3.ifcrelassignstasks, ifc2x3.ifcrelassignstoproduct, ifc2x3.ifcrelassignstogroup, and ifc2x3.ifcrelassignstocontrol.
Definition at line 2744 of file ifc2x3.py.
References ifc2x3.ifccorrectobjectassignment(), ifc2x3.ifcrelassigns.relatedobjects, and ifc2x3.ifcrelassigns.relatedobjectstype.
Referenced by ifc4.ifctextalignment.__init__(), ifc4.ifcspecularroughness.__init__(), ifc4.ifcheatingvaluemeasure.__init__(), ifc4.ifctexttransformation.__init__(), ifc4.ifcfontstyle.__init__(), ifc4.ifcboxalignment.__init__(), ifc4.ifcpositiveplaneanglemeasure.__init__(), ifc4.ifcdimensioncount.__init__(), ifc4.ifcfontvariant.__init__(), ifc4.ifcfontweight.__init__(), ifc4.ifcnormalisedratiomeasure.__init__(), ifc4.ifcpositivelengthmeasure.__init__(), ifc4.ifcpositiveratiomeasure.__init__(), and ifc4.ifctextdecoration.__init__().
Member Data Documentation
relatedobjects
ifc2x3.ifcrelassigns.relatedobjects
Definition at line 2714 of file ifc2x3.py.
Referenced by ifc2x3.ifcrelassigns.relatedobjects(), ifc2x3.ifcrelassigns.wr1(), and ifc4.ifcrelassigns.wr1().
relatedobjectstype
ifc2x3.ifcrelassigns.relatedobjectstype
Definition at line 2715 of file ifc2x3.py.
Referenced by ifc2x3.ifcrelassigns.relatedobjectstype(), ifc2x3.ifcrelassigns.wr1(), and ifc4.ifcrelassigns.wr1().
The documentation for this class was generated from the following file:
ifc2x3.py