FreeCAD: nativeifc.ifc_import Namespace Reference
nativeifc.ifc_import Namespace Reference
Functions
def open (filename)
def insert (filename, docname, strategy=None, shapemode=None, switchwb=None, silent=False, singledoc=False)
def get_options (strategy=None, shapemode=None, switchwb=None, silent=False)
def get_project_type (silent=False)
def toggle_lock_on ()
def toggle_lock_off ()
def unset_modified ()
Variables
PARAMS = FreeCAD.ParamGet("User parameter:BaseApp/Preferences/Mod/NativeIFC")
Function Documentation
get_options()
def nativeifc.ifc_import.get_options (strategy = None, shapemode = None, switchwb = None, silent = False)
Shows a dialog to get import options
shapemode: 0 = full shape
           1 = coin only
           2 = no representation
strategy:  0 = only root object
           1 = only bbuilding structure,
           2 = all children
Definition at line 122 of file ifc_import.py.
Referenced by nativeifc.ifc_import.insert().
get_project_type()
def nativeifc.ifc_import.get_project_type (silent = False)
Gets the type of project to make
Definition at line 182 of file ifc_import.py.
insert()
def nativeifc.ifc_import.insert (filename, docname, strategy = None, shapemode = None, switchwb = None, silent = False, singledoc = False)
Inserts an IFC document in a FreeCAD document.
Singledoc defines if the produced result is a locked document or not. The
strategy is:
- When opening IFC files, locked/unlocked depends on the preferences (default locked)
- When inserting IFC files, always unlocked (an IFC doc object is created)
Definition at line 58 of file ifc_import.py.
References nativeifc.ifc_import.get_options().
Referenced by nativeifc.ifc_import.open().
open()
def nativeifc.ifc_import.open (filename)
Opens an IFC file
Definition at line 42 of file ifc_import.py.
References nativeifc.ifc_import.insert().
toggle_lock_off()
def nativeifc.ifc_import.toggle_lock_off ()
Definition at line 208 of file ifc_import.py.
toggle_lock_on()
def nativeifc.ifc_import.toggle_lock_on ()
Definition at line 204 of file ifc_import.py.
unset_modified()
def nativeifc.ifc_import.unset_modified ()
Definition at line 212 of file ifc_import.py.
Variable Documentation
PARAMS
nativeifc.ifc_import.PARAMS = FreeCAD.ParamGet("User parameter:BaseApp/Preferences/Mod/NativeIFC")
Definition at line 39 of file ifc_import.py.