FreeCAD: VolSim.h File Reference
VolSim.h File Reference
#include <vector>
#include <Mod/Mesh/App/Mesh.h>
#include <Mod/CAM/App/Command.h>
Classes
struct toolShapePoint
struct toolShapePoint::less_than
struct Point3D
struct Triangle3D
struct cLineSegment
class cSimTool
class Array2D< T >
class cStock
class cVolSim
Macros
#define SIM_EPSILON 0.00001
#define SIM_TESSEL_TOP 1
#define SIM_TESSEL_BOT 2
#define SIM_WALK_RES 0.6
Functions
static Point3D operator+ (const Point3D &a, const Point3D &b)
static Point3D operator- (const Point3D &a, const Point3D &b)
static Point3D operator* (const Point3D &a, double b)
static Point3D operator/ (const Point3D &a, double b)
static double dot (const Point3D &a, const Point3D &b)
static double length (const Point3D &a)
static Point3D unit (const Point3D &a)
Macro Definition Documentation
SIM_EPSILON
#define SIM_EPSILON 0.00001
Definition at line 34 of file VolSim.h.
SIM_TESSEL_BOT
#define SIM_TESSEL_BOT 2
Definition at line 36 of file VolSim.h.
SIM_TESSEL_TOP
#define SIM_TESSEL_TOP 1
Definition at line 35 of file VolSim.h.
SIM_WALK_RES
#define SIM_WALK_RES 0.6
Definition at line 37 of file VolSim.h.
Function Documentation
dot()
static double dot (const Point3D & a, const Point3D & b) inline static
Definition at line 126 of file VolSim.h.
References a, and SCL.SimpleDataTypes::b.
Referenced by App::GeoFeature::_getElementName(), draftguitools.gui_dimensions.Dimension::action(), Gui::ElementColors::Private::allow(), TechDrawGui::QGITile::calcTilePosition(), TechDraw::DrawComplexSection::canBuild(), TechDraw::DrawUtil::checkParallel(), Sketcher::SketchObject::checkSubName(), Base::Line3< float >::Contains(), draftgeoutils.geometry::distance_to_plane(), Base::Vector3< float >::DistanceToLineSegment(), TechDrawGui::QGIWeldSymbol::drawFieldFlag(), TechDrawGui::QGIWeldSymbol::drawTailText(), TechDrawGui::QGIWeldSymbol::drawTile(), TechDraw::ShapeUtils::edgesAreParallel(), Data::ComplexGeoData::elementType(), App::PropertyLinkBase::exportSubName(), App::OriginGroupExtension::extensionGetSubObject(), App::GroupExtension::extensionGetSubObject(), App::GeoFeatureGroupExtension::extensionGetSubObject(), App::LinkBaseExtension::extensionGetSubObject(), draftgeoutils.fillets::fillet(), Data::findElementName(), draftgeoutils.intersections::findIntersection(), Gui::DocumentItem::findItem(), App::LinkBaseExtension::flattenSubname(), Base::Vector3< float >::GetAngle(), Base::Vector3< float >::GetAngleOriented(), App::LinkBaseExtension::getArrayIndex(), Gui::LinkInfo::getDetail(), Gui::ViewProviderDocumentObject::getDetailPath(), Gui::ViewProviderLink::getDetailPath(), Gui::ViewProviderLink::getElementColors(), App::LinkBaseExtension::getElementIndex(), Data::ComplexGeoData::getElementName(), Sketcher::SketchObject::getElementName(), Part::Feature::getExportElementName(), PartDesign::Feature::getFeatureBody(), App::PropertyLinkBase::getLabelReferences(), Gui::DocumentObjectItem::getRelativeParent(), getSelectedLink(), PartDesign::SubShapeBinder::getSubObject(), Sketcher::SketchObject::getSubObject(), Data::hasMissingElement(), App::GeoFeature::hasMissingElement(), TechDraw::DrawLeaderLine::horizLastSegment(), App::PropertyLinkBase::importSubName(), Base::Line2d::Intersect(), intersection(), geoff_geometry::Plane::Intof(), Sketcher::SketchObject::isCarbonCopyAllowed(), MeshCore::MeshGeomEdge::IsPointOf(), MeshCore::MeshGeomEdge::IsProjectionPointOf(), Base::Rotation::isSame(), TechDraw::isValidMultiEdge(), TechDraw::isValidMultiEdge3d(), length(), Gui::LinkView::linkGetDetailPath(), MeshCore::TriangulationVerifierV2::MustFlip(), Data::newElementName(), Data::oldElementName(), Gui::PythonConsole::onSaveHistoryAs(), draftguitools.gui_trackers.archDimTracker::p1(), draftguitools.gui_trackers.archDimTracker::p2(), Base::DualQuat::pow(), draftgeoutils.geometry::project_point_on_plane(), MeshPart::MeshProjection::projectOnMesh(), App::PropertyLinkBase::restoreLabelReference(), Part::Feature::searchElementCache(), SketcherGui::ViewProviderSketch::setEditViewer(), Gui::ViewProviderLink::setElementColors(), TechDrawGui::QGICenterLine::setTools(), Base::Rotation::setValue(), Base::Rotation::slerp(), TechDrawGui::QGIView::snapSectionView(), TechDrawGui::TaskSurfaceFinishSymbols::TaskSurfaceFinishSymbols(), TestPartApp.PartTestNormals::testPlacement(), MeshCore::CylinderSurfaceFit::TestTriangle(), and App::PropertyLinkBase::tryImportSubName().
length()
static double length (const Point3D & a) inline static
Definition at line 130 of file VolSim.h.
References a, and dot().
Referenced by TechDraw::CenterLine::calcEndPoints2Points(), CArea::InsideCurves(), TechDrawGui::makeArcLengthDimension(), DrawSketchHandlerCopy::mouseMove(), DrawSketchHandlerRectangularArray::mouseMove(), CCurve::PerimToPoint(), prepareProfileBased(), MeshCoreFit::SphereFit::ProjectToSphere(), cLineSegment::SetPoints(), and unit().
operator*()
static Point3D operator* (const Point3D & a, double b) inline static
Definition at line 118 of file VolSim.h.
References a, and SCL.SimpleDataTypes::b.
operator+()
static Point3D operator+ (const Point3D & a, const Point3D & b) inline static
Definition at line 110 of file VolSim.h.
References a, and SCL.SimpleDataTypes::b.
operator-()
static Point3D operator- (const Point3D & a, const Point3D & b) inline static
Definition at line 114 of file VolSim.h.
References a, and SCL.SimpleDataTypes::b.
operator/()
static Point3D operator/ (const Point3D & a, double b) inline static
Definition at line 122 of file VolSim.h.
References a, and SCL.SimpleDataTypes::b.
unit()
static Point3D unit (const Point3D & a) inline static
Definition at line 134 of file VolSim.h.
References a, and length().
Referenced by TestGui::UnitTestDialog::addUnitTest(), cStock::ApplyCircularTool(), SketcherGui::SketcherToolDefaultWidget::configureParameterUnit(), SketcherGui::DrawSketchHandler::drawDoubleAtCursor(), App::FunctionExpression::evaluate(), Spreadsheet::Cell::getComputedUnit(), Spreadsheet::Cell::getDisplayUnit(), Data::ComplexGeoData::getElementMapSize(), App::PropertyVector::getPathValue(), App::PropertyVector::getPyPathValue(), Measure::MeasurePosition::getResultString(), TechDraw::LineSet::getUnitOrtho(), MeshCore::MeshGeomFacet::IsCoplanar(), Base::Quantity::isDimensionlessOrUnit(), Gui::Dialog::DlgUnitsCalculator::onUnitsBoxActivated(), Gui::ExpressionSpinBox::openFormulaDialog(), Import::ReaderGltf::read(), PartGui::DlgExportStep::saveSettings(), PartGui::DlgImportExportIges::saveSettings(), Base::UnitsSchemaImperialDecimal::schemaTranslate(), Base::UnitsSchemaCentimeters::schemaTranslate(), Base::UnitsSchemaMKS::schemaTranslate(), Base::UnitsSchemaImperial1::schemaTranslate(), Base::UnitsSchemaInternal::schemaTranslate(), Base::UnitsSchemaMmMin::schemaTranslate(), Base::UnitsSchemaFemMilliMeterNewton::schemaTranslate(), Base::UnitsSchemaMeterDecimal::schemaTranslate(), Base::UnitsSchemaImperialBuilding::schemaTranslate(), Base::UnitsSchemaImperialCivil::schemaTranslate(), Spreadsheet::Cell::setComputedUnit(), Spreadsheet::PropertySheet::setComputedUnit(), Spreadsheet::Sheet::setComputedUnit(), Spreadsheet::Cell::setDisplayUnit(), Spreadsheet::PropertySheet::setDisplayUnit(), Spreadsheet::Sheet::setDisplayUnit(), cLineSegment::SetPoints(), App::PropertyQuantity::setPyObject(), App::PropertyQuantityConstraint::setPyObject(), Spreadsheet::Sheet::setQuantityProperty(), Gui::EditableDatumLabel::setSpinboxValue(), TestGui::UnitTestDialog::setUnitTest(), FemGui::BoxWidget::setViewProvider(), FemGui::CylinderWidget::setViewProvider(), FemGui::PlaneWidget::setViewProvider(), FemGui::SphereWidget::setViewProvider(), Part::STEP::ImportExportSettings::setVisibleImportDialog(), Gui::Dialog::DlgUnitsCalculator::textChanged(), Gui::PropertyEditor::PropertyUnitItem::toString(), SketcherGui::SketcherToolDefaultWidget::updateVisualValue(), Gui::QuantitySpinBoxPrivate::validate(), Gui::QuantitySpinBoxPrivate::validateAndInterpret(), Part::Interface::writeIgesUnit(), and Part::Interface::writeStepUnit().