FreeCAD: Gui::TaskView::TaskDialogPython Class Reference
Gui::TaskView::TaskDialogPython Class Reference
The TaskDialogPython class This wraps a task dialog that is written in Python.
#include <TaskDialogPython.h>
Public Member Functions
TaskDialogPython (const Py::Object &)
~TaskDialogPython () override
QDialogButtonBox::StandardButtons getStandardButtons () const override
tells the framework which buttons are wished for the dialog
void modifyStandardButtons (QDialogButtonBox *) override
bool isAllowedAlterDocument () const override
bool isAllowedAlterView () const override
bool isAllowedAlterSelection () const override
bool needsFullSpace () const override
void autoClosedOnTransactionChange () override
void autoClosedOnDeletedDocument () override
void open () override
is called by the framework when the dialog is opened
void clicked (int) override
is called by the framework if a button is clicked which has no accept or reject role
bool accept () override
is called by the framework if the dialog is accepted (Ok)
bool reject () override
is called by the framework if the dialog is rejected (Cancel)
void helpRequested () override
is called by the framework if the user press the help button
bool eventFilter (QObject *watched, QEvent *event) override
event handling
Public Member Functions inherited from Gui::TaskView::TaskDialog
TaskDialog ()
~TaskDialog () override
QWidget * addTaskBox (QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBox (const QPixmap &icon, QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBoxWithoutHeader (QWidget *widget)
void setButtonPosition (ButtonPosition p)
ButtonPosition buttonPosition () const
const std::vector< QWidget * > & getDialogContent () const
bool canClose () const
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
bool isEscapeButtonEnabled () const
void setAutoCloseOnTransactionChange (bool on)
bool isAutoCloseOnTransactionChange () const
void setAutoCloseOnDeletedDocument (bool on)
bool isAutoCloseOnDeletedDocument () const
const std::string & getDocumentName () const
void setDocumentName (const std::string &doc)
void setAutoCloseOnClosedView (bool on)
bool isAutoCloseOnClosedView () const
void associateToObject3dView (App::DocumentObject *obj)
const Gui::MDIView * getAssociatedView () const
void setAssociatedView (const Gui::MDIView *view)
virtual void closed ()
is called by the framework when the dialog is closed
virtual void autoClosedOnClosedView ()
void emitDestructionSignal ()
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Protected Attributes inherited from Gui::TaskView::TaskDialog
QPointer< QDialogButtonBox > buttonBox
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Detailed Description
The TaskDialogPython class This wraps a task dialog that is written in Python.
Definition at line 180 of file TaskDialogPython.h.
Constructor & Destructor Documentation
TaskDialogPython()
TaskDialogPython::TaskDialogPython (const Py::Object & o) explicit
Definition at line 545 of file TaskDialogPython.cpp.
~TaskDialogPython()
TaskDialogPython::~TaskDialogPython () override
Definition at line 552 of file TaskDialogPython.cpp.
References Gui::TaskView::TaskDialog::Content.
Member Function Documentation
accept()
bool TaskDialogPython::accept () override virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 685 of file TaskDialogPython.cpp.
References Gui::TaskView::TaskDialog::accept(), toolbit-attributes::args, and SCL.SimpleDataTypes::e.
Referenced by femexamples.examplesgui.FemExamples::clicked(), femexamples.examplesgui.FemExamples::double_clicked(), ArchComponent.ComponentTaskPanel::editObject(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit(), and MaterialEditor.MaterialEditor::verify().
autoClosedOnDeletedDocument()
void TaskDialogPython::autoClosedOnDeletedDocument () override virtual
is called by the framework when the dialog is automatically closed due to deleting the document
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 893 of file TaskDialogPython.cpp.
References toolbit-attributes::args, and SCL.SimpleDataTypes::e.
autoClosedOnTransactionChange()
void TaskDialogPython::autoClosedOnTransactionChange () override virtual
is called by the framework when the dialog is automatically closed due to changing the active transaction
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 877 of file TaskDialogPython.cpp.
References toolbit-attributes::args, and SCL.SimpleDataTypes::e.
clicked()
void TaskDialogPython::clicked (int i) override virtual
is called by the framework if a button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 667 of file TaskDialogPython.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, SplineSurface::i, and Gui::PythonWrapper::toStandardButton().
eventFilter()
bool TaskDialogPython::eventFilter (QObject * watched, QEvent * event) override
event handling
Definition at line 739 of file TaskDialogPython.cpp.
References toolbit-attributes::args, and SCL.SimpleDataTypes::e.
getStandardButtons()
QDialogButtonBox::StandardButtons TaskDialogPython::getStandardButtons () const override virtual
tells the framework which buttons are wished for the dialog
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 760 of file TaskDialogPython.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, Gui::TaskView::TaskDialog::getStandardButtons(), Gui::PythonWrapper::loadWidgetsModule(), and Gui::PythonWrapper::toEnum().
helpRequested()
void TaskDialogPython::helpRequested () override virtual
is called by the framework if the user press the help button
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 723 of file TaskDialogPython.cpp.
References toolbit-attributes::args, and SCL.SimpleDataTypes::e.
isAllowedAlterDocument()
bool TaskDialogPython::isAllowedAlterDocument () const override virtual
Indicates whether this task dialog allows other commands to modify the document while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 801 of file TaskDialogPython.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, and Gui::TaskView::TaskDialog::isAllowedAlterDocument().
isAllowedAlterSelection()
bool TaskDialogPython::isAllowedAlterSelection () const override virtual
Indicates whether this task dialog allows other commands to modify the selection while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 839 of file TaskDialogPython.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, and Gui::TaskView::TaskDialog::isAllowedAlterSelection().
isAllowedAlterView()
bool TaskDialogPython::isAllowedAlterView () const override virtual
Indicates whether this task dialog allows other commands to modify the 3d view while it is open.
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 820 of file TaskDialogPython.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, and Gui::TaskView::TaskDialog::isAllowedAlterView().
modifyStandardButtons()
void TaskDialogPython::modifyStandardButtons (QDialogButtonBox * buttonBox) override virtual
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 781 of file TaskDialogPython.cpp.
References toolbit-attributes::args, Gui::TaskView::TaskDialog::buttonBox, SCL.SimpleDataTypes::e, Gui::PythonWrapper::fromQWidget(), Gui::PythonWrapper::loadGuiModule(), and Gui::PythonWrapper::loadWidgetsModule().
needsFullSpace()
bool TaskDialogPython::needsFullSpace () const override virtual
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 858 of file TaskDialogPython.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, and Gui::TaskView::TaskDialog::needsFullSpace().
open()
void TaskDialogPython::open () override virtual
is called by the framework when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 651 of file TaskDialogPython.cpp.
References toolbit-attributes::args, and SCL.SimpleDataTypes::e.
reject()
bool TaskDialogPython::reject () override virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 704 of file TaskDialogPython.cpp.
References toolbit-attributes::args, SCL.SimpleDataTypes::e, and Gui::TaskView::TaskDialog::reject().
Referenced by bimcommands.BimReorder.BIM_Reorder_TaskPanel::accept(), draftguitools.gui_hatch.Draft_Hatch_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelCmd::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanelEdit::accept(), draftguitools.gui_setstyle.Draft_SetStyle_TaskPanel::accept(), drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), draftguitools.gui_selectplane.Draft_SelectPlane::action(), JointObject.TaskAssemblyCreateJoint::autoClosedOnTransactionChange(), femexamples.examplesgui.FemExamples::clicked(), CommandCreateView.TaskAssemblyCreateView::KeyboardEvent(), JointObject.TaskAssemblyCreateJoint::KeyboardEvent(), src.Mod.AddonManager.AddonManager.CommandAddonManager::launch(), bimcommands.BimProjectManager.BIM_ProjectManager::loadTemplate(), bimcommands.BimLibrary.BIM_Library_TaskPanel::mouseClick(), bimcommands.BimProjectManager.BIM_ProjectManager::saveTemplate(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary::toolEdit().
The documentation for this class was generated from the following files:
TaskDialogPython.h
TaskDialogPython.cpp