FreeCAD: MatGui::AppearancePreview Class Reference
MatGui::AppearancePreview Class Reference
#include <AppearancePreview.h>
Public Member Functions
AppearancePreview (QWidget *parent=nullptr)
~AppearancePreview () override
void setAmbientColor (const QColor &color)
void setDiffuseColor (const QColor &color)
void setSpecularColor (const QColor &color)
void setEmissiveColor (const QColor &color)
void setShininess (double value)
void setTransparency (double value)
void setTexture (const QImage &image)
void setTextureScaling (double scale)
void resetAmbientColor ()
void resetDiffuseColor ()
void resetSpecularColor ()
void resetEmissiveColor ()
void resetShininess ()
void resetTransparency ()
void resetTexture ()
void resetTextureScaling ()
Public Member Functions inherited from Gui::View3DInventorViewer
bool hasViewProvider (ViewProvider *) const
Checks if the view provider is a top-level object of the scene.
bool containsViewProvider (const ViewProvider *) const
void addViewProvider (ViewProvider *)
adds an ViewProvider to the view, e.g. from a feature
void removeViewProvider (ViewProvider *)
remove a ViewProvider
ViewProvider * getViewProviderByPath (SoPath *) const
get view provider by path
ViewProvider * getViewProviderByPathFromTail (SoPath *) const
std::vector< ViewProvider * > getViewProvidersOfType (const Base::Type &typeId) const
get all view providers of given type
void setEditingViewProvider (Gui::ViewProvider *vp, int ModNum)
set the ViewProvider in special edit mode
bool isEditingViewProvider () const
return whether a view provider is edited
ViewProvider * getEditingViewProvider () const
return currently editing view provider
void resetEditingViewProvider ()
reset from edit mode
void setupEditingRoot (SoNode *node=nullptr, const Base::Matrix4D *mat=nullptr)
void resetEditingRoot (bool updateLinks=true)
void setEditingTransform (const Base::Matrix4D &mat)
SoPickedPoint * getPointOnRay (const SbVec2s &pos, const ViewProvider *vp) const
SoPickedPoint * getPointOnRay (const SbVec3f &pos, const SbVec3f &dir, const ViewProvider *vp) const
void setOverrideMode (const std::string &mode)
display override mode
void updateOverrideMode (const std::string &mode)
update override mode. doesn't affect providers
std::string getOverrideMode () const
void savePicture (int width, int height, int sample, const QColor &bg, QImage &img) const
void saveGraphic (int pagesize, const QColor &, SoVectorizeAction *va) const
bool dumpToFile (SoNode *node, const char *filename, bool binary) const
void startSelection (SelectionMode=Lasso)
void abortSelection ()
void stopSelection ()
bool isSelecting () const
std::vector< SbVec2f > getGLPolygon (SelectionRole *role=nullptr) const
std::vector< SbVec2f > getGLPolygon (const std::vector< SbVec2s > &) const
const std::vector< SbVec2s > & getPolygon (SelectionRole *role=nullptr) const
void setSelectionEnabled (bool enable)
bool isSelectionEnabled () const
SbVec2f screenCoordsOfPath (SoPath *path) const
Returns the screen coordinates of the origin of the path's tail object.
void setEditing (bool edit)
bool isEditing () const
void setEditingCursor (const QCursor &cursor)
void setComponentCursor (const QCursor &cursor)
void setRedirectToSceneGraph (bool redirect)
bool isRedirectedToSceneGraph () const
void setRedirectToSceneGraphEnabled (bool enable)
bool isRedirectToSceneGraphEnabled () const
bool pickPoint (const SbVec2s &pos, SbVec3f &point, SbVec3f &norm) const
SoPickedPoint * pickPoint (const SbVec2s &pos) const
const SoPickedPoint * getPickedPoint (SoEventCallback *n) const
bool pubSeekToPoint (const SbVec2s &pos)
void pubSeekToPoint (const SbVec3f &pos)
void addEventCallback (SoType eventtype, SoEventCallbackCB *cb, void *userdata=nullptr)
void removeEventCallback (SoType eventtype, SoEventCallbackCB *cb, void *userdata=nullptr)
SbVec3f getViewDirection () const
void setViewDirection (SbVec3f)
SbVec3f getUpDirection () const
SbRotation getCameraOrientation () const
SbVec3f getPointOnFocalPlane (const SbVec2s &) const
SbVec3f getPointOnLine (const SbVec2s &, const SbVec3f &axisCenter, const SbVec3f &axis) const
SbVec3f getPointOnXYPlaneOfPlacement (const SbVec2s &, const Base::Placement &) const
Base::BoundBox2d getViewportOnXYPlaneOfPlacement (Base::Placement plc) const
SbVec2s getPointOnViewport (const SbVec3f &) const
QPoint toQPoint (const SbVec2s &) const
SbVec2s fromQPoint (const QPoint &) const
void getNearPlane (SbVec3f &rcPt, SbVec3f &rcNormal) const
void getFarPlane (SbVec3f &rcPt, SbVec3f &rcNormal) const
void toggleClippingPlane (int toggle=-1, bool beforeEditing=false, bool noManip=false, const Base::Placement &pla=Base::Placement())
bool hasClippingPlane () const
SbVec3f projectOnNearPlane (const SbVec2f &) const
SbVec3f projectOnFarPlane (const SbVec2f &) const
void projectPointToLine (const SbVec2s &, SbVec3f &pt1, SbVec3f &pt2) const
SbVec2f getNormalizedPosition (const SbVec2s &) const
View3DInventorViewer (QWidget *parent, const QtGLWidget *sharewidget=nullptr)
View3DInventorViewer (const QtGLFormat &format, QWidget *parent, const QtGLWidget *sharewidget=nullptr)
~View3DInventorViewer () override
void init ()
void onSelectionChanged (const SelectionChanges &Reason) override
Observer message from the Selection.
SoDirectionalLight * getBacklight () const
void setBacklightEnabled (bool on)
bool isBacklightEnabled () const
void setSceneGraph (SoNode *root) override
bool searchNode (SoNode *) const
void setAnimationEnabled (bool enable)
Decide if it should be possible to start any animation.
void setSpinningAnimationEnabled (bool enable)
Decide if it should be possible to start a spin animation of the model in the viewer by releasing the mouse button while dragging.
bool isAnimationEnabled () const
bool isSpinningAnimationEnabled () const
bool isAnimating () const
bool isSpinning () const
void startAnimation (const SbRotation &orientation, const SbVec3f &rotationCenter, const SbVec3f &translation, int duration=-1, bool wait=false)
Change the camera pose with an animation.
void startSpinningAnimation (const SbVec3f &axis, float velocity)
Start an infinite spin animation.
void stopAnimating ()
void setPopupMenuEnabled (bool on)
bool isPopupMenuEnabled () const
void setFeedbackVisibility (bool enable)
bool isFeedbackVisible () const
void setFeedbackSize (int size)
int getFeedbackSize () const
void setRenderType (RenderType type)
RenderType getRenderType () const
void renderToFramebuffer (QtGLFramebufferObject *)
QImage grabFramebuffer ()
void imageFromFramebuffer (int width, int height, int samples, const QColor &bgcolor, QImage &img)
void setViewing (bool enable) override
virtual void setCursorEnabled (bool enable)
void addGraphicsItem (GLGraphicsItem *)
void removeGraphicsItem (GLGraphicsItem *)
std::list< GLGraphicsItem * > getGraphicsItems () const
std::list< GLGraphicsItem * > getGraphicsItemsOfType (const Base::Type &) const
void clearGraphicsItems ()
void turnAllDimensionsOn ()
void turnAllDimensionsOff ()
void turn3dDimensionsOn ()
void turn3dDimensionsOff ()
void turnDeltaDimensionsOn ()
void turnDeltaDimensionsOff ()
void eraseAllDimensions ()
void addDimension3d (SoNode *node)
void addDimensionDelta (SoNode *node)
void setCameraOrientation (const SbRotation &orientation, bool moveToCenter=false)
void setCameraType (SoType type) override
void moveCameraTo (const SbRotation &orientation, const SbVec3f &position, int duration=-1)
void boxZoom (const SbBox2s &)
void viewAll () override
void viewAll (float factor)
void viewVR ()
Breaks out a VR window for a Rift.
SbBox3f getBoundingBox () const
void viewSelection ()
void alignToSelection ()
void setGradientBackground (Background)
Background getGradientBackground () const
void setGradientBackgroundColor (const SbColor &fromColor, const SbColor &toColor)
void setGradientBackgroundColor (const SbColor &fromColor, const SbColor &toColor, const SbColor &midColor)
void setNavigationType (Base::Type)
void setAxisLetterColor (const SbColor &color)
void setAxisCross (bool on)
bool hasAxisCross ()
void showRotationCenter (bool show)
void changeRotationCenterPosition (const SbVec3f &newCenter)
void setEnabledFPSCounter (bool on)
void setEnabledNaviCube (bool on)
bool isEnabledNaviCube () const
void setNaviCubeCorner (int)
NaviCube * getNaviCube () const
void setEnabledVBO (bool on)
bool isEnabledVBO () const
void setRenderCache (int)
void getDimensions (float &fHeight, float &fWidth) const
float getMaxDimension () const
SbVec3f getCenterPointOnFocalPlane () const
NavigationStyle * navigationStyle () const
void setDocument (Gui::Document *pcDocument)
Gui::Document * getDocument ()
virtual PyObject * getPyObject ()
Public Member Functions inherited from SIM::Coin3D::Quarter::SoQTQuarterAdaptor
SoQTQuarterAdaptor (QWidget *parent=nullptr, const QtGLWidget *sharewidget=nullptr, Qt::WindowFlags flags=Qt::WindowFlags())
SoQTQuarterAdaptor (const QtGLFormat &format, QWidget *parent=nullptr, const QtGLWidget *shareWidget=nullptr, Qt::WindowFlags flags=Qt::WindowFlags())
SoQTQuarterAdaptor (QtGLContext *context, QWidget *parent=nullptr, const QtGLWidget *sharewidget=nullptr, Qt::WindowFlags flags=Qt::WindowFlags())
~SoQTQuarterAdaptor () override
QWidget * getWidget ()
QWidget * getGLWidget ()
QWidget * getWidget () const
QWidget * getGLWidget () const
SoCamera * getCamera () const
const SbViewportRegion & getViewportRegion () const
bool isViewing () const
void interactiveCountInc ()
void interactiveCountDec ()
int getInteractiveCount () const
void addStartCallback (SoQTQuarterAdaptorCB *func, void *data=nullptr)
void addFinishCallback (SoQTQuarterAdaptorCB *func, void *data=nullptr)
void removeStartCallback (SoQTQuarterAdaptorCB *func, void *data=nullptr)
void removeFinishCallback (SoQTQuarterAdaptorCB *func, void *data=nullptr)
bool isSeekMode () const
bool seekToPoint (const SbVec2s &screenpos)
void seekToPoint (const SbVec3f &scenepos)
void setSeekTime (float seconds)
float getSeekTime () const
void setSeekDistance (float distance)
float getSeekDistance () const
void setSeekValueAsPercentage (bool on)
bool isSeekValuePercentage () const
virtual float getPickRadius () const
virtual void setPickRadius (float pickRadius)
virtual void saveHomePosition ()
virtual void resetToHomePosition ()
virtual bool hasHomePosition () const
void paintEvent (QPaintEvent *event) override
Public Member Functions inherited from SIM::Coin3D::Quarter::QuarterWidget
QuarterWidget (QWidget *parent=nullptr, const QtGLWidget *sharewidget=nullptr, Qt::WindowFlags f=Qt::WindowFlags())
QuarterWidget (QtGLContext *context, QWidget *parent=nullptr, const QtGLWidget *sharewidget=nullptr, Qt::WindowFlags f=Qt::WindowFlags())
QuarterWidget (const QtGLFormat &format, QWidget *parent=nullptr, const QtGLWidget *shareWidget=nullptr, Qt::WindowFlags f=Qt::WindowFlags())
~QuarterWidget () override
TransparencyType transparencyType () const
RenderMode renderMode () const
StereoMode stereoMode () const
void setBackgroundColor (const QColor &color)
QColor backgroundColor () const
qreal devicePixelRatio () const
void resetNavigationModeFile ()
void setNavigationModeFile (const QUrl &url=QUrl(QString::fromLatin1(DEFAULT_NAVIGATIONFILE)))
const QUrl & navigationModeFile () const
void setupDefaultCursors ()
void setContextMenuEnabled (bool yes)
bool contextMenuEnabled () const
QMenu * getContextMenu () const
bool headlightEnabled () const
void setHeadlightEnabled (bool onoff)
SoDirectionalLight * getHeadlight () const
bool clearZBuffer () const
void setClearZBuffer (bool onoff)
bool clearWindow () const
void setClearWindow (bool onoff)
bool interactionModeEnabled () const
void setInteractionModeEnabled (bool onoff)
bool interactionModeOn () const
void setInteractionModeOn (bool onoff)
void setStateCursor (const SbName &state, const QCursor &cursor)
QCursor stateCursor (const SbName &state)
uint32_t getCacheContextId () const
virtual SoNode * getSceneGraph () const
void setSoEventManager (SoEventManager *manager)
SoEventManager * getSoEventManager () const
void setSoRenderManager (SoRenderManager *manager)
SoRenderManager * getSoRenderManager () const
EventFilter * getEventFilter () const
void addStateMachine (SoScXMLStateMachine *statemachine)
void removeStateMachine (SoScXMLStateMachine *statemachine)
QSize minimumSizeHint () const override
QList< QAction * > transparencyTypeActions () const
QList< QAction * > stereoModeActions () const
QList< QAction * > renderModeActions () const
Public Member Functions inherited from Gui::SelectionObserver
SelectionObserver (bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
SelectionObserver (const Gui::ViewProviderDocumentObject *vp, bool attach=true, ResolveMode resolve=ResolveMode::OldStyleElement)
virtual ~SelectionObserver ()
bool blockSelection (bool block)
bool isSelectionBlocked () const
bool isSelectionAttached () const
void attachSelection ()
void detachSelection ()
Additional Inherited Members
Public Types inherited from Gui::View3DInventorViewer
enum SelectionMode {
Lasso = 0, Rectangle = 1, Rubberband = 2, BoxZoom = 3,
Clip = 4
}
Pick modes for picking points in the scene.
enum ViewerMod {
ShowCoord =1, ShowFPS =2, SimpleBackground =4, DisallowRotation =8,
DisallowPanning =16, DisallowZooming =32
}
enum RenderType { Native, Framebuffer, Image }
enum Background { NoGradient, LinearGradient, RadialGradient }
Public Types inherited from SIM::Coin3D::Quarter::QuarterWidget
enum TransparencyType {
SCREEN_DOOR = SoGLRenderAction::SCREEN_DOOR, ADD = SoGLRenderAction::ADD, DELAYED_ADD = SoGLRenderAction::DELAYED_ADD, SORTED_OBJECT_ADD = SoGLRenderAction::SORTED_OBJECT_ADD,
BLEND = SoGLRenderAction::BLEND, DELAYED_BLEND = SoGLRenderAction::DELAYED_BLEND, SORTED_OBJECT_BLEND = SoGLRenderAction::SORTED_OBJECT_BLEND, SORTED_OBJECT_SORTED_TRIANGLE_ADD = SoGLRenderAction::SORTED_OBJECT_SORTED_TRIANGLE_ADD,
SORTED_OBJECT_SORTED_TRIANGLE_BLEND = SoGLRenderAction::SORTED_OBJECT_SORTED_TRIANGLE_BLEND, NONE = SoGLRenderAction::NONE, SORTED_LAYERS_BLEND = SoGLRenderAction::SORTED_LAYERS_BLEND
}
enum RenderMode {
AS_IS = SoRenderManager::AS_IS, WIREFRAME = SoRenderManager::WIREFRAME, WIREFRAME_OVERLAY = SoRenderManager::WIREFRAME_OVERLAY, POINTS = SoRenderManager::POINTS,
HIDDEN_LINE = SoRenderManager::HIDDEN_LINE, BOUNDING_BOX = SoRenderManager::BOUNDING_BOX
}
enum StereoMode {
MONO = SoRenderManager::MONO, ANAGLYPH = SoRenderManager::ANAGLYPH, QUAD_BUFFER = SoRenderManager::QUAD_BUFFER, INTERLEAVED_ROWS = SoRenderManager::INTERLEAVED_ROWS,
INTERLEAVED_COLUMNS = SoRenderManager::INTERLEAVED_COLUMNS
}
Public Slots inherited from SIM::Coin3D::Quarter::QuarterWidget
virtual void seek ()
void redraw ()
void setRenderMode (SIM::Coin3D::Quarter::QuarterWidget::RenderMode mode)
void setStereoMode (SIM::Coin3D::Quarter::QuarterWidget::StereoMode mode)
void setTransparencyType (SIM::Coin3D::Quarter::QuarterWidget::TransparencyType type)
Signals inherited from SIM::Coin3D::Quarter::QuarterWidget
void devicePixelRatioChanged (qreal dev_pixel_ratio)
Static Public Member Functions inherited from Gui::View3DInventorViewer
static int getNumSamples ()
Get the preferred samples from the user settings.
Protected Member Functions inherited from Gui::View3DInventorViewer
void renderScene ()
void renderFramebuffer ()
void renderGLImage ()
void animatedViewAll (int steps, int ms)
void actualRedraw () override
void setSeekMode (bool on) override
void afterRealizeHook () override
bool processSoEvent (const SoEvent *ev) override
void dropEvent (QDropEvent *ev) override
void dragEnterEvent (QDragEnterEvent *ev) override
void dragMoveEvent (QDragMoveEvent *ev) override
void dragLeaveEvent (QDragLeaveEvent *ev) override
bool processSoEventBase (const SoEvent *const ev)
void printDimension () const
void selectAll ()
Protected Member Functions inherited from SIM::Coin3D::Quarter::QuarterWidget
void paintEvent (QPaintEvent *) override
void resizeEvent (QResizeEvent *) override
bool viewportEvent (QEvent *event) override
virtual bool updateDevicePixelRatio ()
Static Protected Member Functions inherited from Gui::View3DInventorViewer
static GLenum getInternalTextureFormat ()
Static Protected Member Functions inherited from SIM::Coin3D::Quarter::SoQTQuarterAdaptor
static void draw2DString (const char *str, SbVec2s glsize, SbVec2f position)
static void printString (const char *str)
Protected Attributes inherited from SIM::Coin3D::Quarter::SoQTQuarterAdaptor
SbVec2f framesPerSecond
Properties inherited from SIM::Coin3D::Quarter::QuarterWidget
QUrl navigationModeFile
QColor backgroundColor
bool contextMenuEnabled
bool headlightEnabled
bool clearZBuffer
bool clearWindow
bool interactionModeEnabled
bool interactionModeOn
TransparencyType transparencyType
RenderMode renderMode
StereoMode stereoMode
qreal devicePixelRatio
Detailed Description
Definition at line 50 of file AppearancePreview.h.
Constructor & Destructor Documentation
AppearancePreview()
AppearancePreview::AppearancePreview (QWidget * parent = nullptr) explicit
Definition at line 123 of file AppearancePreview.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSceneGraph(), Gui::View3DInventorViewer::setCameraType(), Gui::View3DInventorViewer::setEnabledNaviCube(), Gui::View3DInventorViewer::setPopupMenuEnabled(), Gui::View3DInventorViewer::setRedirectToSceneGraph(), Gui::View3DInventorViewer::setViewDirection(), Gui::View3DInventorViewer::setViewing(), and Gui::View3DInventorViewer::viewAll().
~AppearancePreview()
AppearancePreview::~AppearancePreview () override
Definition at line 158 of file AppearancePreview.cpp.
Member Function Documentation
resetAmbientColor()
void AppearancePreview::resetAmbientColor ()
Definition at line 264 of file AppearancePreview.cpp.
resetDiffuseColor()
void AppearancePreview::resetDiffuseColor ()
Definition at line 271 of file AppearancePreview.cpp.
resetEmissiveColor()
void AppearancePreview::resetEmissiveColor ()
Definition at line 285 of file AppearancePreview.cpp.
resetShininess()
void AppearancePreview::resetShininess ()
Definition at line 292 of file AppearancePreview.cpp.
resetSpecularColor()
void AppearancePreview::resetSpecularColor ()
Definition at line 278 of file AppearancePreview.cpp.
resetTexture()
void AppearancePreview::resetTexture ()
Definition at line 306 of file AppearancePreview.cpp.
resetTextureScaling()
void AppearancePreview::resetTextureScaling ()
Definition at line 309 of file AppearancePreview.cpp.
resetTransparency()
void AppearancePreview::resetTransparency ()
Definition at line 299 of file AppearancePreview.cpp.
setAmbientColor()
void AppearancePreview::setAmbientColor (const QColor & color)
Definition at line 204 of file AppearancePreview.cpp.
setDiffuseColor()
void AppearancePreview::setDiffuseColor (const QColor & color)
Definition at line 212 of file AppearancePreview.cpp.
setEmissiveColor()
void AppearancePreview::setEmissiveColor (const QColor & color)
Definition at line 228 of file AppearancePreview.cpp.
setShininess()
void AppearancePreview::setShininess (double value)
Definition at line 236 of file AppearancePreview.cpp.
setSpecularColor()
void AppearancePreview::setSpecularColor (const QColor & color)
Definition at line 220 of file AppearancePreview.cpp.
setTexture()
void AppearancePreview::setTexture (const QImage & image)
Definition at line 250 of file AppearancePreview.cpp.
References Gui::BitmapFactory(), and Gui::BitmapFactoryInst::convert().
setTextureScaling()
void AppearancePreview::setTextureScaling (double scale)
Definition at line 259 of file AppearancePreview.cpp.
setTransparency()
void AppearancePreview::setTransparency (double value)
Definition at line 243 of file AppearancePreview.cpp.
The documentation for this class was generated from the following files:
AppearancePreview.h
AppearancePreview.cpp