FreeCAD: CCurve Class Reference
CCurve Class Reference
#include <Curve.h>
Public Member Functions
void append (const CVertex &vertex)
void FitArcs (bool retry=false)
void UnFitArcs ()
Point NearestPoint (const Point &p) const
Point NearestPoint (const CCurve &p, double *d=NULL) const
Point NearestPoint (const Span &p, double *d=NULL) const
void GetBox (CBox2D &box)
void Reverse ()
double GetArea () const
bool IsClockwise () const
bool IsClosed () const
void ChangeStart (const Point &p)
void ChangeEnd (const Point &p)
bool Offset (double leftwards_value)
void OffsetForward (double forwards_value, bool refit_arcs=true)
void Break (const Point &p)
void ExtractSeparateCurves (const std::list< Point > &ordered_points, std::list< CCurve > &separate_curves) const
double Perim () const
Point PerimToPoint (double perim) const
double PointToPerim (const Point &p) const
void GetSpans (std::list< Span > &spans) const
void RemoveTinySpans ()
void operator+= (const CCurve &p)
void SpanIntersections (const Span &s, std::list< Point > &pts) const
void CurveIntersections (const CCurve &c, std::list< Point > &pts) const
Public Attributes
std::list< CVertex > m_vertices
Protected Member Functions
void AddArcOrLines (bool check_for_arc, std::list< CVertex > &new_vertices, std::list< const CVertex * > &might_be_an_arc, CArc &arc, bool &arc_found, bool &arc_added)
Static Protected Member Functions
static bool CheckForArc (const CVertex &prev_vt, std::list< const CVertex * > &might_be_an_arc, CArc &arc)
Detailed Description
Definition at line 104 of file Curve.h.
Member Function Documentation
AddArcOrLines()
void CCurve::AddArcOrLines (bool check_for_arc, std::list< CVertex > & new_vertices, std::list< const CVertex * > & might_be_an_arc, CArc & arc, bool & arc_found, bool & arc_added) protected
Definition at line 182 of file Curve.cpp.
References Path.Post.scripts.opensbp_post::arc(), CheckForArc(), and TestSpreadsheet::v.
Referenced by FitArcs().
append()
void CCurve::append (const CVertex & vertex)
Definition at line 70 of file Curve.cpp.
References m_vertices.
Referenced by BOOST_PYTHON_MODULE(), init_pyarea(), and CArea::MakePocketToolpath().
Break()
void CCurve::Break (const Point & p)
Definition at line 583 of file Curve.cpp.
References CVertex::m_p, m_vertices, Span::On(), buildPsets::p, and TestSpreadsheet::v.
Referenced by BOOST_PYTHON_MODULE(), and init_pyarea().
ChangeEnd()
void CCurve::ChangeEnd (const Point & p)
Definition at line 685 of file Curve.cpp.
References CVertex::m_p, m_vertices, Span::On(), buildPsets::p, and TestSpreadsheet::v.
Referenced by BOOST_PYTHON_MODULE(), and init_pyarea().
ChangeStart()
void CCurve::ChangeStart (const Point & p)
Definition at line 521 of file Curve.cpp.
References SplineSurface::i, IsClosed(), CVertex::m_p, m_vertices, Span::On(), buildPsets::p, and TestSpreadsheet::v.
Referenced by BOOST_PYTHON_MODULE(), init_pyarea(), and Offset().
CheckForArc()
bool CCurve::CheckForArc (const CVertex & prev_vt, std::list< const CVertex * > & might_be_an_arc, CArc & arc) static protected
Definition at line 75 of file Curve.cpp.
References Path.Post.scripts.opensbp_post::arc(), KDL::atan2(), SCL.SimpleDataTypes::c, SplineSurface::i, CArea::m_accuracy, CVertex::m_p, CArea::m_units, Point::x, and Point::y.
Referenced by AddArcOrLines(), and FitArcs().
CurveIntersections()
void CCurve::CurveIntersections (const CCurve & c, std::list< Point > & pts) const
Definition at line 1003 of file Curve.cpp.
References a, and SCL.SimpleDataTypes::c.
ExtractSeparateCurves()
void CCurve::ExtractSeparateCurves (const std::list< Point > & ordered_points, std::list< CCurve > & separate_curves) const
Definition at line 608 of file Curve.cpp.
References CVertex::m_p, m_vertices, Span::On(), updateLeaderLines::point, and TestSpreadsheet::v.
Referenced by CArea::InsideCurves().
FitArcs()
void CCurve::FitArcs (bool retry = false)
Definition at line 231 of file Curve.cpp.
References AddArcOrLines(), Path.Post.scripts.opensbp_post::arc(), CheckForArc(), SplineSurface::i, IsClosed(), CVertex::m_type, m_vertices, and TestSpreadsheet::v.
Referenced by BOOST_PYTHON_MODULE(), CArea::FitArcs(), init_pyarea(), OffsetForward(), and SetFromResult().
GetArea()
double CCurve::GetArea () const
Definition at line 497 of file Curve.cpp.
References Span::GetArea(), CVertex::m_p, and m_vertices.
Referenced by BOOST_PYTHON_MODULE(), CArea::GetArea(), init_pyarea(), and IsClockwise().
GetBox()
void CCurve::GetBox (CBox2D & box)
Definition at line 460 of file Curve.cpp.
References MengerSponge::box, Span::GetBox(), CVertex::m_p, and m_vertices.
Referenced by CArea::GetBox().
GetSpans()
void CCurve::GetSpans (std::list< Span > & spans) const
Definition at line 843 of file Curve.cpp.
References CVertex::m_p, and m_vertices.
Referenced by CArea::CurveIntersections(), CArea::MakePocketToolpath(), OffsetForward(), and SpanIntersections().
IsClockwise()
bool CCurve::IsClockwise () const inline
Definition at line 130 of file Curve.h.
References GetArea().
Referenced by BOOST_PYTHON_MODULE(), init_pyarea(), make_zig_curve(), Offset(), recur(), CArea::Split(), and CInnerCurves::Unite().
IsClosed()
bool CCurve::IsClosed () const
Definition at line 513 of file Curve.cpp.
References m_vertices.
Referenced by BOOST_PYTHON_MODULE(), ChangeStart(), CArea::ChangeStartToNearest(), FitArcs(), init_pyarea(), MakePoly(), Offset(), and CArea::PopulateClipper().
NearestPoint() [1/3]
Point CCurve::NearestPoint (const CCurve & p, double * d = NULL) const
Definition at line 430 of file Curve.cpp.
References SCL.SimpleDataTypes::c, DraftVecUtils::dist(), CVertex::m_p, and NearestPoint().
NearestPoint() [2/3]
Point CCurve::NearestPoint (const Point & p) const
Definition at line 404 of file Curve.cpp.
References Point::dist(), DraftVecUtils::dist(), CVertex::m_p, m_vertices, Span::NearestPoint(), and buildPsets::p.
Referenced by BOOST_PYTHON_MODULE(), CArea::ChangeStartToNearest(), GetNearestPoint(), init_pyarea(), CArea::NearestPoint(), NearestPoint(), and Offset().
NearestPoint() [3/3]
Point CCurve::NearestPoint (const Span & p, double * d = NULL) const
Definition at line 719 of file Curve.cpp.
References DraftVecUtils::dist(), CVertex::m_p, m_vertices, Span::NearestPoint(), and buildPsets::p.
Offset()
bool CCurve::Offset (double leftwards_value)
Definition at line 782 of file Curve.cpp.
References a, ChangeStart(), Span::GetVector(), IsClockwise(), IsClosed(), CVertex::m_p, Span::m_p, m_vertices, MakeCCurve(), MakeKurve(), NearestPoint(), geoff_geometry::Kurve::OffsetMethod1(), Reverse(), draftgeoutils.general::v1(), Point::x, and Point::y.
Referenced by BOOST_PYTHON_MODULE(), and init_pyarea().
OffsetForward()
void CCurve::OffsetForward (double forwards_value, bool refit_arcs = true)
Definition at line 855 of file Curve.cpp.
References FitArcs(), GetSpans(), Span::GetVector(), CVertex::m_p, Span::m_p, Span::m_v, m_vertices, Point::normalize(), UnFitArcs(), and TestSpreadsheet::v.
Referenced by BOOST_PYTHON_MODULE(), and init_pyarea().
operator+=()
void CCurve::operator+= (const CCurve & p)
Definition at line 986 of file Curve.cpp.
References m_vertices.
Perim()
double CCurve::Perim () const
Definition at line 914 of file Curve.cpp.
References Span::Length(), CVertex::m_p, and m_vertices.
Referenced by BOOST_PYTHON_MODULE(), init_pyarea(), and CArea::InsideCurves().
PerimToPoint()
Point CCurve::PerimToPoint (double perim) const
Definition at line 930 of file Curve.cpp.
References Span::Length(), length(), CVertex::m_p, m_vertices, Span::MidPerim(), and buildPsets::p.
Referenced by BOOST_PYTHON_MODULE(), init_pyarea(), and CArea::InsideCurves().
PointToPerim()
double CCurve::PointToPerim (const Point & p) const
Definition at line 955 of file Curve.cpp.
References Point::dist(), DraftVecUtils::dist(), Span::Length(), CVertex::m_c, CVertex::m_p, CVertex::m_type, Span::m_v, m_vertices, Span::NearestPoint(), and buildPsets::p.
Referenced by BOOST_PYTHON_MODULE(), and init_pyarea().
RemoveTinySpans()
void CCurve::RemoveTinySpans ()
Definition at line 666 of file Curve.cpp.
References CVertex::m_p, CVertex::m_type, m_vertices, and Point::tolerance.
Reverse()
void CCurve::Reverse ()
Definition at line 474 of file Curve.cpp.
References CVertex::m_c, CVertex::m_type, m_vertices, Path.Post.scripts.grbl_post::type, and TestSpreadsheet::v.
Referenced by BOOST_PYTHON_MODULE(), init_pyarea(), make_zig_curve(), Offset(), and CInnerCurves::Unite().
SpanIntersections()
void CCurve::SpanIntersections (const Span & s, std::list< Point > & pts) const
Definition at line 1010 of file Curve.cpp.
References GetSpans(), Span::Intersect(), and toolbit-attributes::s.
UnFitArcs()
void CCurve::UnFitArcs ()
Definition at line 304 of file Curve.cpp.
References KDL::acos(), KDL::atan2(), KDL::cos(), SplineSurface::i, CArea::m_accuracy, CVertex::m_c, CVertex::m_p, CVertex::m_type, CArea::m_units, m_vertices, PI, KDL::sin(), KDL::sqrt(), Point::x, and Point::y.
Referenced by BOOST_PYTHON_MODULE(), init_pyarea(), and OffsetForward().
Member Data Documentation
m_vertices
std::list<CVertex> CCurve::m_vertices
Definition at line 119 of file Curve.h.
Referenced by add_reorder_zig(), append(), Break(), ChangeEnd(), ChangeStart(), CArea::ChangeStartToNearest(), ExtractSeparateCurves(), FirstVertex(), FitArcs(), GetArea(), GetBox(), GetCurveItem::GetCurve(), GetSpans(), getVertices(), IsClosed(), LastVertex(), make_zig_curve(), MakeKurve(), CArea::MakeOnePocketCurve(), CArea::MakePocketToolpath(), MakePoly(), NearestPoint(), num_vertices(), Offset(), OffsetForward(), OffsetSpansWithObrounds(), operator+=(), Perim(), PerimToPoint(), PointToPerim(), RemoveTinySpans(), Reverse(), rotate_area(), SetFromResult(), UnFitArcs(), and UnFitArcs().
The documentation for this class was generated from the following files:
Curve.h
Curve.cpp