FreeCAD: feminout.importZ88O2Results Namespace Reference
feminout.importZ88O2Results Namespace Reference
Functions
def open (filename)
def insert (filename, docname)
def import_z88_disp (filename, analysis=None, result_name_prefix=None)
def read_z88_disp (z88_disp_input)
Function Documentation
import_z88_disp()
def feminout.importZ88O2Results.import_z88_disp (filename, analysis = None, result_name_prefix = None)
insert a FreeCAD FEM mechanical result object in the ActiveDocument
pure usage:
import feminout.importZ88O2Results as importZ88O2Results
disp_file = "/pathtofile/z88o2.txt"
importZ88O2Results.import_z88_disp(disp_file)
the z888i1.txt FEMMesh file needs to be in the same directory as z88o2.txt
# ahh, make a new document first ;-)
Definition at line 59 of file importZ88O2Results.py.
References ObjectsFem.makeMeshResult(), ObjectsFem.makeResultMechanical(), and feminout.importZ88O2Results.read_z88_disp().
Referenced by feminout.importZ88O2Results.insert().
insert()
def feminout.importZ88O2Results.insert (filename, docname)
Definition at line 48 of file importZ88O2Results.py.
References feminout.importZ88O2Results.import_z88_disp().
Referenced by feminout.importZ88O2Results.open().
open()
def feminout.importZ88O2Results.open (filename)
Definition at line 42 of file importZ88O2Results.py.
References feminout.importZ88O2Results.insert().
read_z88_disp()
def feminout.importZ88O2Results.read_z88_disp (z88_disp_input)
read a z88 disp file and extract the nodes and elements
z88 Displacement output file is z88o2.txt
works with Z88OS14
Definition at line 121 of file importZ88O2Results.py.
Referenced by feminout.importZ88O2Results.import_z88_disp().