FreeCAD: Gui::MenuItem Class Reference
Gui::MenuItem Class Reference
#include <MenuManager.h>
Public Member Functions
MenuItem ()
MenuItem (MenuItem *)
~MenuItem ()
void setCommand (const std::string &)
std::string command () const
bool hasItems () const
MenuItem * findItem (const std::string &)
MenuItem * findParentOf (const std::string &)
MenuItem * copy () const
uint count () const
void appendItem (MenuItem *)
bool insertItem (MenuItem *, MenuItem *)
MenuItem * afterItem (MenuItem *) const
void removeItem (MenuItem *)
void clear ()
MenuItem & operator<< (MenuItem *item)
MenuItem & operator<< (const std::string &command)
QList< MenuItem * > getItems () const
Detailed Description
Definition at line 39 of file MenuManager.h.
Constructor & Destructor Documentation
MenuItem() [1/2]
MenuItem::MenuItem () default
Referenced by copy(), and operator<<().
MenuItem() [2/2]
MenuItem::MenuItem (MenuItem * item) explicit
Definition at line 41 of file MenuManager.cpp.
References appendItem().
~MenuItem()
MenuItem::~MenuItem ()
Definition at line 48 of file MenuManager.cpp.
References clear().
Member Function Documentation
afterItem()
MenuItem * MenuItem::afterItem (MenuItem * item) const
Definition at line 135 of file MenuManager.cpp.
References RobotExample::pos.
Referenced by Gui::Workbench::addPermanentMenuItems(), PartDesignGui::Workbench::setupMenuBar(), and PartGui::Workbench::setupMenuBar().
appendItem()
void MenuItem::appendItem (MenuItem * item)
Definition at line 119 of file MenuManager.cpp.
Referenced by Gui::PythonBaseWorkbench::appendMenu(), MenuItem(), operator<<(), and Gui::PythonBaseWorkbench::setupContextMenu().
clear()
void MenuItem::clear ()
Definition at line 152 of file MenuManager.cpp.
Referenced by src.Mod.Test.Document.DocumentObserverCases.Observer::__init__(), src.Mod.Test.Document.DocumentObserverCases.GuiObserver::__init__(), Gui::PythonBaseWorkbench::clearContextMenu(), and ~MenuItem().
command()
std::string MenuItem::command () const
Definition at line 58 of file MenuManager.cpp.
Referenced by copy(), Gui::MainWindow::createPopupMenu(), and operator<<().
copy()
MenuItem * MenuItem::copy () const
Definition at line 101 of file MenuManager.cpp.
References command(), and MenuItem().
Referenced by Gui::PythonBaseWorkbench::setupMenuBar(), and Gui::PythonWorkbench::setupMenuBar().
count()
uint MenuItem::count () const
Definition at line 114 of file MenuManager.cpp.
Referenced by src.Mod.AddonManager.Widgets.addonmanager_widget_filter_selector.WidgetFilterSelector::set_status_filter().
findItem()
MenuItem * MenuItem::findItem (const std::string & name)
Definition at line 68 of file MenuManager.cpp.
Referenced by Gui::Workbench::addPermanentMenuItems(), Gui::PythonBaseWorkbench::appendContextMenu(), Gui::PythonBaseWorkbench::appendMenu(), StartGui::Manipulator::modifyMenuBar(), Gui::PythonBaseWorkbench::removeContextMenu(), Gui::PythonBaseWorkbench::removeMenu(), PartDesignGui::Workbench::setupMenuBar(), SpreadsheetGui::Workbench::setupMenuBar(), SurfaceGui::Workbench::setupMenuBar(), InspectionGui::Workbench::setupMenuBar(), MatGui::Workbench::setupMenuBar(), SandboxGui::Workbench::setupMenuBar(), DrawingGui::Workbench::setupMenuBar(), ReverseEngineeringGui::Workbench::setupMenuBar(), TechDrawGui::Workbench::setupMenuBar(), FemGui::Workbench::setupMenuBar(), PointsGui::Workbench::setupMenuBar(), PartGui::Workbench::setupMenuBar(), MeshGui::Workbench::setupMenuBar(), SketcherGui::Workbench::setupMenuBar(), RobotGui::Workbench::setupMenuBar(), and Gui::TestWorkbench::setupMenuBar().
findParentOf()
MenuItem * MenuItem::findParentOf (const std::string & name)
Definition at line 84 of file MenuManager.cpp.
Referenced by Gui::Workbench::addPermanentMenuItems().
getItems()
QList< MenuItem * > MenuItem::getItems () const
Definition at line 173 of file MenuManager.cpp.
Referenced by Gui::MainWindow::createPopupMenu(), Gui::MenuManager::setup(), and Gui::PythonBaseWorkbench::setupContextMenu().
hasItems()
bool MenuItem::hasItems () const
Definition at line 63 of file MenuManager.cpp.
Referenced by Gui::MainWindow::createPopupMenu(), and PartDesignGui::Workbench::setupContextMenu().
insertItem()
bool MenuItem::insertItem (MenuItem * before, MenuItem * item)
Definition at line 124 of file MenuManager.cpp.
References RobotExample::pos.
Referenced by Gui::Workbench::addPermanentMenuItems(), Gui::PythonBaseWorkbench::appendMenu(), StartGui::Manipulator::modifyMenuBar(), PartDesignGui::Workbench::setupMenuBar(), SpreadsheetGui::Workbench::setupMenuBar(), SurfaceGui::Workbench::setupMenuBar(), InspectionGui::Workbench::setupMenuBar(), MatGui::Workbench::setupMenuBar(), SandboxGui::Workbench::setupMenuBar(), DrawingGui::Workbench::setupMenuBar(), ReverseEngineeringGui::Workbench::setupMenuBar(), TechDrawGui::Workbench::setupMenuBar(), FemGui::Workbench::setupMenuBar(), PointsGui::Workbench::setupMenuBar(), PartGui::Workbench::setupMenuBar(), MeshGui::Workbench::setupMenuBar(), SketcherGui::Workbench::setupMenuBar(), RobotGui::Workbench::setupMenuBar(), and Gui::TestWorkbench::setupMenuBar().
operator<<() [1/2]
MenuItem & MenuItem::operator<< (const std::string & command)
Definition at line 160 of file MenuManager.cpp.
References command(), and MenuItem().
operator<<() [2/2]
MenuItem & MenuItem::operator<< (MenuItem * item)
Definition at line 167 of file MenuManager.cpp.
References appendItem().
removeItem()
void MenuItem::removeItem (MenuItem * item)
Definition at line 144 of file MenuManager.cpp.
References RobotExample::pos.
Referenced by Gui::PythonBaseWorkbench::removeContextMenu(), Gui::PythonBaseWorkbench::removeMenu(), and Gui::TestWorkbench::setupMenuBar().
setCommand()
void MenuItem::setCommand (const std::string & name)
Definition at line 53 of file MenuManager.cpp.
Referenced by Gui::PythonBaseWorkbench::appendContextMenu(), Gui::PythonBaseWorkbench::appendMenu(), Gui::Workbench::createLinkMenu(), StartGui::Manipulator::modifyMenuBar(), Gui::StdWorkbench::setupContextMenu(), PartDesignGui::Workbench::setupMenuBar(), SpreadsheetGui::Workbench::setupMenuBar(), InspectionGui::Workbench::setupMenuBar(), SurfaceGui::Workbench::setupMenuBar(), MatGui::Workbench::setupMenuBar(), SandboxGui::Workbench::setupMenuBar(), DrawingGui::Workbench::setupMenuBar(), ReverseEngineeringGui::Workbench::setupMenuBar(), TechDrawGui::Workbench::setupMenuBar(), PartGui::Workbench::setupMenuBar(), FemGui::Workbench::setupMenuBar(), PointsGui::Workbench::setupMenuBar(), MeshGui::Workbench::setupMenuBar(), SketcherGui::Workbench::setupMenuBar(), RobotGui::Workbench::setupMenuBar(), and Gui::StdWorkbench::setupMenuBar().
The documentation for this class was generated from the following files:
MenuManager.h
MenuManager.cpp