FreeCAD: FemGui::DlgSettingsFemInOutVtkImp Class Reference
FemGui::DlgSettingsFemInOutVtkImp Class Reference
#include <DlgSettingsFemInOutVtkImp.h>
Public Member Functions
DlgSettingsFemInOutVtkImp (QWidget *parent=nullptr)
~DlgSettingsFemInOutVtkImp () override
Public Member Functions inherited from Gui::Dialog::PreferencePage
PreferencePage (QWidget *parent=nullptr)
~PreferencePage () override=default
bool isRestartRequired () const
void requireRestart ()
bool hasHeightForWidth () const override
Protected Member Functions
void saveSettings () override
void loadSettings () override
void changeEvent (QEvent *e) override
Additional Inherited Members
Public Slots inherited from Gui::Dialog::PreferencePage
virtual void resetSettingsToDefaults ()
Detailed Description
Definition at line 59 of file DlgSettingsFemInOutVtkImp.h.
Constructor & Destructor Documentation
DlgSettingsFemInOutVtkImp()
DlgSettingsFemInOutVtkImp::DlgSettingsFemInOutVtkImp (QWidget * parent = nullptr) explicit
Definition at line 35 of file DlgSettingsFemInOutVtkImp.cpp.
~DlgSettingsFemInOutVtkImp()
DlgSettingsFemInOutVtkImp::~DlgSettingsFemInOutVtkImp () override default
Member Function Documentation
changeEvent()
void DlgSettingsFemInOutVtkImp::changeEvent (QEvent * e) override protected virtual
Sets the strings of the subwidgets using the current language.
Implements Gui::Dialog::PreferencePage.
Definition at line 76 of file DlgSettingsFemInOutVtkImp.cpp.
References SCL.SimpleDataTypes::e.
loadSettings()
void DlgSettingsFemInOutVtkImp::loadSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 57 of file DlgSettingsFemInOutVtkImp.cpp.
References App::GetApplication(), ParameterGrp::GetInt(), and App::Application::GetParameterGroupByPath().
saveSettings()
void DlgSettingsFemInOutVtkImp::saveSettings () override protected virtual
Implements Gui::Dialog::PreferencePage.
Definition at line 47 of file DlgSettingsFemInOutVtkImp.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetInt().
The documentation for this class was generated from the following files:
DlgSettingsFemInOutVtkImp.h
DlgSettingsFemInOutVtkImp.cpp