FreeCAD: App::DocumentObjectWeakPtrT Class Reference
App::DocumentObjectWeakPtrT Class Reference
The DocumentObjectWeakPtrT class.
#include <DocumentObserver.h>
Classes
class Private
Public Member Functions
DocumentObjectWeakPtrT (App::DocumentObject *)
~DocumentObjectWeakPtrT ()
void reset ()
reset Releases the reference to the managed object. After the call *this manages no object.
bool expired () const noexcept
expired
DocumentObjectWeakPtrT & operator= (App::DocumentObject *p)
operator = Assignment operator
App::DocumentObject * operator* () const noexcept
operator *
App::DocumentObject * operator-> () const noexcept
operator ->
bool operator== (const DocumentObjectWeakPtrT &p) const noexcept
operator ==
bool operator!= (const DocumentObjectWeakPtrT &p) const noexcept
operator !=
template<typename T >
T * get () const noexcept
DocumentObjectWeakPtrT (const DocumentObjectWeakPtrT &)=delete
DocumentObjectWeakPtrT & operator= (const DocumentObjectWeakPtrT &)=delete
Detailed Description
The DocumentObjectWeakPtrT class.
Definition at line 387 of file App/DocumentObserver.h.
Constructor & Destructor Documentation
DocumentObjectWeakPtrT() [1/2]
DocumentObjectWeakPtrT::DocumentObjectWeakPtrT (App::DocumentObject * obj) explicit
Definition at line 810 of file App/DocumentObserver.cpp.
~DocumentObjectWeakPtrT()
DocumentObjectWeakPtrT::~DocumentObjectWeakPtrT () default
DocumentObjectWeakPtrT() [2/2]
App::DocumentObjectWeakPtrT::DocumentObjectWeakPtrT (const DocumentObjectWeakPtrT &) delete
Member Function Documentation
expired()
bool DocumentObjectWeakPtrT::expired () const noexcept
expired
Returns
true if the managed object has already been deleted, false otherwise.
Definition at line 826 of file App/DocumentObserver.cpp.
Referenced by ReverseEngineeringGui::Segmentation::accept(), PartGui::DlgPrimitives::accept(), PartGui::PlanePrimitive::changeValue(), PartGui::BoxPrimitive::changeValue(), PartGui::CylinderPrimitive::changeValue(), PartGui::ConePrimitive::changeValue(), PartGui::SpherePrimitive::changeValue(), PartGui::EllipsoidPrimitive::changeValue(), PartGui::TorusPrimitive::changeValue(), PartGui::PrismPrimitive::changeValue(), PartGui::WedgePrimitive::changeValue(), PartGui::HelixPrimitive::changeValue(), PartGui::SpiralPrimitive::changeValue(), PartGui::CirclePrimitive::changeValue(), PartGui::EllipsePrimitive::changeValue(), PartGui::PolygonPrimitive::changeValue(), PartGui::LinePrimitive::changeValue(), PartGui::VertexPrimitive::changeValue(), PartGui::AbstractPrimitive::hasValidPrimitive(), PartDesignGui::TaskDlgSketchBasedParameters::reject(), PartDesignGui::TaskDlgFeatureParameters::reject(), and PartGui::DlgPrimitives::reject().
get()
template<typename T > T* App::DocumentObjectWeakPtrT::get () const inline noexcept
Get a pointer to the object or 0 if it doesn't exist any more or the type doesn't match.
Definition at line 430 of file App/DocumentObserver.h.
Referenced by ReverseEngineeringGui::Segmentation::accept(), PartGui::PlanePrimitive::changeValue(), PartGui::BoxPrimitive::changeValue(), PartGui::CylinderPrimitive::changeValue(), PartGui::ConePrimitive::changeValue(), PartGui::SpherePrimitive::changeValue(), PartGui::EllipsoidPrimitive::changeValue(), PartGui::TorusPrimitive::changeValue(), PartGui::PrismPrimitive::changeValue(), PartGui::WedgePrimitive::changeValue(), PartGui::HelixPrimitive::changeValue(), PartGui::SpiralPrimitive::changeValue(), PartGui::CirclePrimitive::changeValue(), PartGui::EllipsePrimitive::changeValue(), PartGui::PolygonPrimitive::changeValue(), PartGui::LinePrimitive::changeValue(), PartGui::VertexPrimitive::changeValue(), FemGui::TaskPostBox::getTypedObject(), and draftguitools.gui_trackers.editTracker::move().
operator!=()
bool DocumentObjectWeakPtrT::operator!= (const DocumentObjectWeakPtrT & p) const noexcept
operator !=
Returns
true if both objects are inequal, false otherwise
Definition at line 853 of file App/DocumentObserver.cpp.
References buildPsets::p.
operator*()
App::DocumentObject * DocumentObjectWeakPtrT::operator* () const noexcept
operator *
Returns
pointer to the document object
Definition at line 838 of file App/DocumentObserver.cpp.
operator->()
App::DocumentObject * DocumentObjectWeakPtrT::operator-> () const noexcept
operator ->
Returns
pointer to the document object
Definition at line 843 of file App/DocumentObserver.cpp.
operator=() [1/2]
DocumentObjectWeakPtrT & DocumentObjectWeakPtrT::operator= (App::DocumentObject * p)
operator = Assignment operator
Definition at line 831 of file App/DocumentObserver.cpp.
References buildPsets::p.
operator=() [2/2]
DocumentObjectWeakPtrT& App::DocumentObjectWeakPtrT::operator= (const DocumentObjectWeakPtrT &) delete
operator==()
bool DocumentObjectWeakPtrT::operator== (const DocumentObjectWeakPtrT & p) const noexcept
operator ==
Returns
true if both objects are equal, false otherwise
Definition at line 848 of file App/DocumentObserver.cpp.
References buildPsets::p.
reset()
void DocumentObjectWeakPtrT::reset ()
reset Releases the reference to the managed object. After the call *this manages no object.
Definition at line 821 of file App/DocumentObserver.cpp.
Referenced by ArchVRM.Renderer::__init__(), draftguitools.gui_trackers.gridTracker::set(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testAll(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
The documentation for this class was generated from the following files:
App/DocumentObserver.h
App/DocumentObserver.cpp