FreeCAD: SIM::Coin3D::Quarter::InteractionMode Class Reference
SIM::Coin3D::Quarter::InteractionMode Class Reference
#include <InteractionMode.h>
Public Member Functions
InteractionMode (QuarterWidget *quarterwidget)
~InteractionMode () override
void setEnabled (bool yes)
bool enabled () const
void setOn (bool on)
bool on () const
Protected Member Functions
bool eventFilter (QObject *, QEvent *event) override
Detailed Description
Definition at line 52 of file InteractionMode.h.
Constructor & Destructor Documentation
InteractionMode()
InteractionMode::InteractionMode (QuarterWidget * quarterwidget)
Definition at line 47 of file InteractionMode.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoEventManager().
~InteractionMode()
InteractionMode::~InteractionMode () override
Definition at line 59 of file InteractionMode.cpp.
Member Function Documentation
enabled()
bool InteractionMode::enabled () const
Definition at line 71 of file InteractionMode.cpp.
eventFilter()
bool InteractionMode::eventFilter (QObject * obj, QEvent * event) override protected
Definition at line 105 of file InteractionMode.cpp.
on()
bool InteractionMode::on () const
Definition at line 99 of file InteractionMode.cpp.
Referenced by draftguitools.gui_trackers.PlaneTracker::set(), draftguitools.gui_trackers.gridTracker::set(), and setOn().
setEnabled()
void InteractionMode::setEnabled (bool yes)
Definition at line 65 of file InteractionMode.cpp.
Referenced by Path.Dressup.Gui.Tags.HoldingTagMarker::setSelected().
setOn()
void InteractionMode::setOn (bool on)
Definition at line 77 of file InteractionMode.cpp.
References SIM::Coin3D::Quarter::QuarterWidget::getSoEventManager(), on(), and SIM::Coin3D::Quarter::QuarterWidget::stateCursor().
The documentation for this class was generated from the following files:
InteractionMode.h
InteractionMode.cpp