FreeCAD: TopoShapeExpansion.cpp File Reference
TopoShapeExpansion.cpp File Reference
#include "PreCompiled.h"
#include <cmath>
#include <BRepAdaptor_Curve.hxx>
#include <BRepAdaptor_CompCurve.hxx>
#include <BRepAdaptor_HCurve.hxx>
#include <BRepAdaptor_HCompCurve.hxx>
#include <BRepBuilderAPI_MakeWire.hxx>
#include <BRepCheck_Analyzer.hxx>
#include <BRepFill.hxx>
#include <BRepFill_Generator.hxx>
#include <BRepTools.hxx>
#include <BRep_Builder.hxx>
#include <BRep_Tool.hxx>
#include <Mod/Part/App/FCBRepAlgoAPI_BooleanOperation.h>
#include <Mod/Part/App/FCBRepAlgoAPI_Common.h>
#include <Mod/Part/App/FCBRepAlgoAPI_Cut.h>
#include <Mod/Part/App/FCBRepAlgoAPI_Fuse.h>
#include <Mod/Part/App/FCBRepAlgoAPI_Section.h>
#include <BRepBuilderAPI_Copy.hxx>
#include <BRepBuilderAPI_FindPlane.hxx>
#include <BRepBuilderAPI_GTransform.hxx>
#include <BRepBuilderAPI_MakeEdge.hxx>
#include <BRepBuilderAPI_MakeFace.hxx>
#include <BRepBuilderAPI_MakeSolid.hxx>
#include <BRepBuilderAPI_NurbsConvert.hxx>
#include <BRepBuilderAPI_Transform.hxx>
#include <BRepFilletAPI_MakeChamfer.hxx>
#include <BRepFilletAPI_MakeFillet.hxx>
#include <BRepLib.hxx>
#include <BRepOffsetAPI_DraftAngle.hxx>
#include <BRepOffsetAPI_MakeFilling.hxx>
#include <BRepOffsetAPI_MakePipe.hxx>
#include <BRepOffsetAPI_MakeEvolved.hxx>
#include <BRepOffsetAPI_MakeThickSolid.hxx>
#include <BRepPrimAPI_MakeRevol.hxx>
#include <BRepPrimAPI_MakePrism.hxx>
#include <BRepProj_Projection.hxx>
#include <BRepTools_WireExplorer.hxx>
#include <GeomConvert.hxx>
#include <GeomFill_BezierCurves.hxx>
#include <GeomFill_BSplineCurves.hxx>
#include <Precision.hxx>
#include <ShapeAnalysis_FreeBounds.hxx>
#include <ShapeBuild_ReShape.hxx>
#include <ShapeConstruct_Curve.hxx>
#include <ShapeUpgrade_ShellSewing.hxx>
#include <TopTools_HSequenceOfShape.hxx>
#include <ShapeFix_Shape.hxx>
#include <ShapeFix_ShapeTolerance.hxx>
#include <gp_Pln.hxx>
#include <utility>
#include "modelRefine.h"
#include "CrossSection.h"
#include "TopoShape.h"
#include "TopoShapeOpCode.h"
#include "TopoShapeCache.h"
#include "TopoShapeMapper.h"
#include "FaceMaker.h"
#include "Geometry.h"
#include "BRepOffsetAPI_MakeOffsetFix.h"
#include "Base/Tools.h"
#include "Base/BoundBox.h"
#include <App/ElementMap.h>
#include <App/ElementNamingUtils.h>
#include <ShapeAnalysis_FreeBoundsProperties.hxx>
#include <BRepFeat_MakeRevol.hxx>
#include "Tools.h"
Functions
FC_LOG_LEVEL_INIT ("TopoShape", true, true) namespace Part
Function Documentation
FC_LOG_LEVEL_INIT()
FC_LOG_LEVEL_INIT ("TopoShape" , true , true)
Encode and set an element name in the elementMap. If a hasher is defined, apply it to the name.
Parameters
element The element name(type) that provides 1 one character suffix to the name IF <conditions>.
names The subnames to build the name from. If empty, return the TopoShape MappedName.
marker The elementMap name or suffix to start the name with. If null, use the elementMapPrefix.
op The op text passed to the element name encoder along with the TopoShape Tag
_sids If defined, records the sub ids processed.
Returns
The encoded, possibly hashed name.
Reorient the outer and inner wires of the TopoShape
Parameters
inner If this is not a nullptr, then any inner wires processed will be returned in this vector.
reorient One of NoReorient, Reorient (Outer forward, inner reversed), ReorientForward (all forward), or ReorientReversed (all reversed)
Returns
The outer wire, or an empty TopoShape if this isn't a Face, has no Face subShapes, or the outer wire isn't found.
Definition at line 109 of file TopoShapeExpansion.cpp.
References Part::TopoShape::_makeElementTransform(), Part::TopoShape::Mapper::_res, NavigationIndicatorGui::a1, NavigationIndicatorGui::a2, ClipperLib::Abs(), KDL::abs(), Part::allowOpenResult, Data::MappedName::appendToBuffer(), Part::arc, importers.importWebGL::base, Part::OpCodes::BSplineFace, SCL.SimpleDataTypes::c, src.Mod.PartDesign.Scripts.Gear::c1, Part::TopoShape::cacheRelatedElements(), Part::TopoShape::canMapElement(), Part::OpCodes::Chamfer, ArchCommands::check(), Data::CheckGeometry, Part::checkScale, Part::TopoShape::chooseMatchingSubShapeByPlaneOrLine(), Part::closed, Part::OpCodes::Common, Part::OpCodes::Compound, Part::OpCodes::Compsolid, Base::Console(), Part::FaceMaker::ConstructFromType(), Part::TopoShape::convert(), Part::coons, Part::copy, Part::TopoShape::copyElementMap(), Data::ElementMap::MappedChildElements::count, src.Mod.AddonManager.NetworkManager::count, Part::TopoShape::countSubShapes(), Part::curved, Part::OpCodes::Cut, Part::TopoShape::decodeElementComboName(), Part::distanceAngle, Part::OpCodes::Draft, SCL.SimpleDataTypes::e, src.Mod.PartDesign.Scripts.Gear::e1, Data::ElementMap::MappedChildElements::elementMap, Data::ComplexGeoData::elementMap(), Data::ComplexGeoData::elementMapPrefix(), Data::ComplexGeoData::elementType(), Data::ComplexGeoData::ensureElementMap(), Part::equalDistance, Part::OpCodes::Evolve, KDL::exp(), Part::OpCodes::Extrude, SCL.SimpleDataTypes::f, Part::OpCodes::Face, Mesh2Shape::faces, FC_ERR, FC_LOG_INSTANCE, FC_LOGLEVEL_LOG, FC_THROWM, FC_WARN, Part::OpCodes::FilledFace, Part::OpCodes::Fillet, DraftVecUtils::find(), Data::MappedName::find(), Part::TopoShape::findAncestor(), Part::TopoShape::findAncestors(), Part::TopoShape::findAncestorShape(), Part::TopoShape::findAncestorsShapes(), Part::TopoShape::findPlane(), Part::TopoShape::findShape(), Part::TopoShape::findSubShapesWithSharedVertex(), Data::MappedName::findTagInElementName(), FirstVertex(), Part::TopoShape::fixSolidOrientation(), Part::flip, Part::TopoShape::flushElementMap(), Part::TopoShape::forceCompound, Data::IndexedName::fromConst(), Part::Geometry::fromShape(), App::StringID::fromString(), Part::OpCodes::Fuse, Part::FuseWithBase, Part::OpCodes::GeneralFuse, Part::Generated, Part::MapperMaker::generated(), Part::MapperHistory::generated(), Base::Persistence::getClassTypeId(), Data::ComplexGeoData::getElementMapSize(), Data::ComplexGeoData::getElementName(), Part::TopoShape::getHigherElements(), Data::IndexedName::getIndex(), importOCA::getline(), Data::ComplexGeoData::getMappedName(), Part::TopoShape::getOrderedEdges(), Part::TopoShape::getOrderedVertexes(), Part::TopoShape::getRelatedElementsCached(), Part::TopoShape::getShape(), Part::TopoShape::getSubShape(), Part::TopoShape::getSubShapes(), Part::TopoShape::getSubTopoShape(), Part::TopoShape::getSubTopoShapes(), draftguitools.gui_tool_utils::getSupport, Part::global, Handle(), Data::ComplexGeoData::Hasher, Part::TopoShape::hasPendingElementMap(), Base::Matrix4D::hasScale(), Part::TopoShape::hasSubShape(), SplineSurface::i, Data::MappedElement::index, Data::ElementMap::MappedChildElements::indexedName, Path.Log::info(), Part::TopoShape::initCache(), Part::intersection, intersection(), Part::TopoShape::isClosed(), Part::Tools::isConcave(), Base::BaseClass::isDerivedFrom(), Part::TopoShape::isElementGenerated(), Base::Vector3< float_type >::IsEqual(), draftgeoutils.edges::isLine, Part::GeomCurve::isLinear(), Part::TopoShape::isLinearEdge(), Part::TopoShape::isNull(), Part::GeomSurface::isPlanar(), Part::TopoShape::isPlanarFace(), Part::TopoShape::isSame(), Path.Base.Util::isSolid(), Part::TopoShape::isValid(), LastVertex(), Part::TopoShape::linearize(), Part::linearizeEdges, Part::linearizeFaces, Part::TopoShape::locate(), Part::TopoShape::located(), Part::OpCodes::Loft, Part::TopoShape::makeElementBoolean(), Part::TopoShape::makeElementBSplineFace(), Part::TopoShape::makeElementChamfer(), Part::TopoShape::makeElementCompound(), Part::TopoShape::makeElementCopy(), Part::TopoShape::makeElementCut(), Part::TopoShape::makeElementDraft(), Part::TopoShape::makeElementEvolve(), Part::TopoShape::makeElementFace(), Part::TopoShape::makeElementFilledFace(), Part::TopoShape::makeElementFillet(), Part::TopoShape::makeElementFuse(), Part::TopoShape::makeElementGeneralFuse(), Part::TopoShape::makeElementGTransform(), Part::TopoShape::makeElementLoft(), Part::TopoShape::makeElementMirror(), Part::TopoShape::makeElementOffset(), Part::TopoShape::makeElementOffset2D(), Part::TopoShape::makeElementOffsetFace(), Part::TopoShape::makeElementOrderedWires(), Part::TopoShape::makeElementPipeShell(), Part::TopoShape::makeElementPrism(), Part::TopoShape::makeElementPrismUntil(), Part::TopoShape::makeElementRefine(), Part::TopoShape::makeElementRevolution(), Part::TopoShape::makeElementRevolve(), Part::TopoShape::makeElementRuledSurface(), Part::TopoShape::makeElementShape(), Part::TopoShape::makeElementShell(), Part::TopoShape::makeElementShellFromWires(), Part::TopoShape::makeElementSlice(), Part::TopoShape::makeElementSlices(), Part::TopoShape::makeElementSolid(), Part::TopoShape::makeElementThickSolid(), Part::TopoShape::makeElementTransform(), Part::TopoShape::makeElementWires(), Part::OpCodes::Maker, Part::MapperMaker::maker, Part::MapperSewing::maker, Part::TopoShape::makeShapeWithElementMap(), Part::makeSolid, Part::map, Part::MapperHistory::MapperHistory(), Part::TopoShape::mapSubElement(), Part::TopoShape::mapSubElementsTo(), Base::ConsoleSingleton::Message(), KDL::min(), Part::OpCodes::Mirror, mod, Part::Modified, Part::MapperMaker::modified(), Part::MapperSewing::modified(), Part::MapperHistory::modified(), Path.Post.scripts.opensbp_post::move(), Part::TopoShape::move(), Part::TopoShape::moved(), femtools.tokrules::names, Part::noCopy, Part::noFill, Gui::None, Part::None, Part::noOpenResult, Base::NoScaling, Part::OpCodes::Offset, Data::ElementMap::MappedChildElements::offset, Part::OpCodes::Offset2D, Path.Op.Util::offsetWire(), Part::on, Part::TopoShape::operator=(), src.Mod.Test.testPathArray::orient, nativeifc.ifc_observer::params, Init::parent, Part::OpCodes::Pipe, Part::OpCodes::PipeShell, WorkingPlane::plane, RobotExample::pos, Data::ElementMap::MappedChildElements::postfix, Data::POSTFIX_GEN, Data::POSTFIX_LOWER, Data::POSTFIX_MOD, Data::POSTFIX_MODGEN, Data::POSTFIX_UPPER, Part::OpCodes::Prism, Part::OpCodes::Refine, Part::TopoShape::removeElementShape(), Part::TopoShape::ReorientForward, Part::TopoShape::ReorientReversed, Part::TopoShape::replaceElementShape(), Part::TopoShape::requireSharedVertex, Data::ComplexGeoData::resetElementMap(), Part::TopoShape::resetElementMap(), result, Part::TopoShape::reTagElementMap(), Part::TopoShape::returnShape, Part::OpCodes::Revolve, Part::RightCorner, Part::RoundCorner, Part::ruled, Part::OpCodes::RuledSurface, toolbit-attributes::s, Part::OpCodes::Section, FCBRepAlgoAPIHelper::setAutoFuzzy(), Part::TopoShape::setElementComboName(), Base::Flags< Enum >::setFlag(), Data::ComplexGeoData::setMappedChildElements(), Part::TopoShape::setShape(), Part::TopoShape::shapeName(), Part::TopoShape::shapeType(), Part::TopoShape::shapeTypeAndIndex(), Part::OpCodes::Shell, ap203_configuration_controlled_3d_design_of_mechanical_parts_and_assemblies_mim_lf::shell, Data::SingleResult, Data::MappedName::size(), Part::OpCodes::Solid, Part::solid, Part::OpCodes::Split, Part::TopoShape::splitWires(), Data::MappedName::startsWith(), Data::ElementMap::MappedChildElements::tag, Data::ComplexGeoData::Tag, Dice3DS.dom3ds::tag, Part::tangent, Base::Flags< Enum >::testFlag(), Part::OpCodes::Thicken, Part::throwException, Part::TopoShape::tol3d, Path.Geom::Tolerance, draftutils.utils::tolerance(), Part::TopoShape::TopoShape(), Base::toRadians(), Data::MappedName::toString(), Data::ComplexGeoData::traceElement(), Part::twoDistances, Path.Post.scripts.grbl_post::type, Base::Uniform, TestSpreadsheet::v, draftgeoutils.general::v1(), SurfaceTests.TestBlendCurve::vec, src.Mod.PartDesign.fcgear.svggear::w, Part::OpCodes::Wire, Mesh2Shape::wires, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.