FreeCAD: Wm4::ConvexHull1< Real > Class Template Reference
Wm4::ConvexHull1< Real > Class Template Reference
#include <Wm4ConvexHull1.h>
Public Member Functions
ConvexHull1 (int iVertexQuantity, Real *afVertex, Real fEpsilon, bool bOwner, Query::Type eQueryType)
virtual ~ConvexHull1 ()
const Real * GetVertices () const
ConvexHull1 (const char *acFilename)
bool Load (const char *acFilename)
bool Save (const char *acFilename) const
Public Member Functions inherited from Wm4::ConvexHull< Real >
virtual ~ConvexHull ()
int GetQueryType () const
int GetVertexQuantity () const
Real GetEpsilon () const
bool GetOwner () const
int GetDimension () const
int GetSimplexQuantity () const
const int * GetIndices () const
Additional Inherited Members
Protected Member Functions inherited from Wm4::ConvexHull< Real >
ConvexHull (int iVertexQuantity, Real fEpsilon, bool bOwner, Query::Type eQueryType)
bool Load (FILE *pkIFile)
bool Save (FILE *pkOFile) const
Protected Attributes inherited from Wm4::ConvexHull< Real >
Query::Type m_eQueryType
int m_iVertexQuantity
int m_iDimension
int m_iSimplexQuantity
int * m_aiIndex
Real m_fEpsilon
bool m_bOwner
Detailed Description
template<class Real>
class Wm4::ConvexHull1< Real >
Definition at line 25 of file Wm4ConvexHull1.h.
Constructor & Destructor Documentation
ConvexHull1() [1/2]
template<class Real > Wm4::ConvexHull1< Real >::ConvexHull1 (int iVertexQuantity, Real * afVertex, Real fEpsilon, bool bOwner, Query::Type eQueryType)
Definition at line 16 of file Wm4ConvexHull1.cpp.
References SplineSurface::i, Wm4::ConvexHull< Real >::m_aiIndex, Wm4::ConvexHull< Real >::m_fEpsilon, Wm4::ConvexHull< Real >::m_iDimension, Wm4::ConvexHull< Real >::m_iSimplexQuantity, Wm4::ConvexHull< Real >::m_iVertexQuantity, and WM4_NEW.
~ConvexHull1()
template<class Real > Wm4::ConvexHull1< Real >::~ConvexHull1 virtual
Definition at line 45 of file Wm4ConvexHull1.cpp.
References WM4_DELETE.
ConvexHull1() [2/2]
template<class Real > Wm4::ConvexHull1< Real >::ConvexHull1 (const char * acFilename)
Definition at line 60 of file Wm4ConvexHull1.cpp.
References Wm4::ConvexHull1< Real >::Load().
Member Function Documentation
GetVertices()
template<class Real > const Real * Wm4::ConvexHull1< Real >::GetVertices
Definition at line 54 of file Wm4ConvexHull1.cpp.
Load()
template<class Real > bool Wm4::ConvexHull1< Real >::Load (const char * acFilename)
Definition at line 71 of file Wm4ConvexHull1.cpp.
References Wm4::System::Fclose(), Wm4::System::Fopen(), Wm4::ConvexHull< Real >::Load(), Wm4::System::Read4le(), Wm4::System::Read8le(), WM4_DELETE, and WM4_NEW.
Referenced by Wm4::ConvexHull1< Real >::ConvexHull1().
Save()
template<class Real > bool Wm4::ConvexHull1< Real >::Save (const char * acFilename) const
Definition at line 104 of file Wm4ConvexHull1.cpp.
References Wm4::System::Fclose(), Wm4::System::Fopen(), Wm4::ConvexHull< Real >::Save(), Wm4::System::Write4le(), and Wm4::System::Write8le().
The documentation for this class was generated from the following files:
Wm4ConvexHull1.h
Wm4ConvexHull1.cpp