FreeCAD: Wm4::MeshCurvature< Real > Class Template Reference
Wm4::MeshCurvature< Real > Class Template Reference
#include <Wm4MeshCurvature.h>
Public Member Functions
MeshCurvature (int iVQuantity, const Vector3< Real > *akVertex, int iTQuantity, const int *aiIndex)
virtual ~MeshCurvature ()
int GetVQuantity () const
const Vector3< Real > * GetVertices () const
int GetTQuantity () const
const int * GetIndices () const
const Vector3< Real > * GetNormals () const
const Real * GetMinCurvatures () const
const Real * GetMaxCurvatures () const
const Vector3< Real > * GetMinDirections () const
const Vector3< Real > * GetMaxDirections () const
Protected Attributes
int m_iVQuantity
const Vector3< Real > * m_akVertex
int m_iTQuantity
const int * m_aiIndex
Vector3< Real > * m_akNormal
Real * m_afMinCurvature
Real * m_afMaxCurvature
Vector3< Real > * m_akMinDirection
Vector3< Real > * m_akMaxDirection
Detailed Description
template<class Real>
class Wm4::MeshCurvature< Real >
Definition at line 28 of file Wm4MeshCurvature.h.
Constructor & Destructor Documentation
MeshCurvature()
template<class Real > Wm4::MeshCurvature< Real >::MeshCurvature (int iVQuantity, const Vector3< Real > * akVertex, int iTQuantity, const int * aiIndex)
Definition at line 24 of file Wm4MeshCurvature.cpp.
References Wm4::Vector3< Real >::Cross(), Wm4::Vector3< Real >::Dot(), Wm4::Vector3< Real >::GenerateComplementBasis(), SplineSurface::i, Wm4::Matrix3< Real >::Inverse(), Wm4::Vector2< Real >::Normalize(), Wm4::Vector3< Real >::Normalize(), Wm4::Math< Real >::Sqrt(), Wm4::Vector2< Real >::SquaredLength(), WM4_DELETE, WM4_NEW, Wm4::Vector2< Real >::X(), and Wm4::Vector2< Real >::Y().
~MeshCurvature()
template<class Real > Wm4::MeshCurvature< Real >::~MeshCurvature virtual
Definition at line 206 of file Wm4MeshCurvature.cpp.
References WM4_DELETE.
Member Function Documentation
GetIndices()
template<class Real > const int * Wm4::MeshCurvature< Real >::GetIndices
Definition at line 234 of file Wm4MeshCurvature.cpp.
GetMaxCurvatures()
template<class Real > const Real * Wm4::MeshCurvature< Real >::GetMaxCurvatures
Definition at line 252 of file Wm4MeshCurvature.cpp.
Referenced by MeshCore::MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection(), and MeshCore::MeshCurvature::ComputePerVertex().
GetMaxDirections()
template<class Real > const Vector3< Real > * Wm4::MeshCurvature< Real >::GetMaxDirections
Definition at line 264 of file Wm4MeshCurvature.cpp.
Referenced by MeshCore::MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection(), and MeshCore::MeshCurvature::ComputePerVertex().
GetMinCurvatures()
template<class Real > const Real * Wm4::MeshCurvature< Real >::GetMinCurvatures
Definition at line 246 of file Wm4MeshCurvature.cpp.
Referenced by MeshCore::MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection(), and MeshCore::MeshCurvature::ComputePerVertex().
GetMinDirections()
template<class Real > const Vector3< Real > * Wm4::MeshCurvature< Real >::GetMinDirections
Definition at line 258 of file Wm4MeshCurvature.cpp.
Referenced by MeshCore::MeshTopoAlgorithm::AdjustEdgesToCurvatureDirection(), and MeshCore::MeshCurvature::ComputePerVertex().
GetNormals()
template<class Real > const Vector3< Real > * Wm4::MeshCurvature< Real >::GetNormals
Definition at line 240 of file Wm4MeshCurvature.cpp.
GetTQuantity()
template<class Real > int Wm4::MeshCurvature< Real >::GetTQuantity
Definition at line 228 of file Wm4MeshCurvature.cpp.
GetVertices()
template<class Real > const Vector3< Real > * Wm4::MeshCurvature< Real >::GetVertices
Definition at line 222 of file Wm4MeshCurvature.cpp.
GetVQuantity()
template<class Real > int Wm4::MeshCurvature< Real >::GetVQuantity
Definition at line 216 of file Wm4MeshCurvature.cpp.
Member Data Documentation
m_afMaxCurvature
template<class Real > Real* Wm4::MeshCurvature< Real >::m_afMaxCurvature protected
Definition at line 58 of file Wm4MeshCurvature.h.
m_afMinCurvature
template<class Real > Real* Wm4::MeshCurvature< Real >::m_afMinCurvature protected
Definition at line 57 of file Wm4MeshCurvature.h.
m_aiIndex
template<class Real > const int* Wm4::MeshCurvature< Real >::m_aiIndex protected
Definition at line 54 of file Wm4MeshCurvature.h.
m_akMaxDirection
template<class Real > Vector3<Real>* Wm4::MeshCurvature< Real >::m_akMaxDirection protected
Definition at line 60 of file Wm4MeshCurvature.h.
m_akMinDirection
template<class Real > Vector3<Real>* Wm4::MeshCurvature< Real >::m_akMinDirection protected
Definition at line 59 of file Wm4MeshCurvature.h.
m_akNormal
template<class Real > Vector3<Real>* Wm4::MeshCurvature< Real >::m_akNormal protected
Definition at line 56 of file Wm4MeshCurvature.h.
m_akVertex
template<class Real > const Vector3<Real>* Wm4::MeshCurvature< Real >::m_akVertex protected
Definition at line 52 of file Wm4MeshCurvature.h.
m_iTQuantity
template<class Real > int Wm4::MeshCurvature< Real >::m_iTQuantity protected
Definition at line 53 of file Wm4MeshCurvature.h.
m_iVQuantity
template<class Real > int Wm4::MeshCurvature< Real >::m_iVQuantity protected
Definition at line 51 of file Wm4MeshCurvature.h.
The documentation for this class was generated from the following files:
Wm4MeshCurvature.h
Wm4MeshCurvature.cpp