FreeCAD: Base::DrawStyleItem Class Reference
Base::DrawStyleItem Class Reference
The DrawStyleItem class supports the SoDrawStyle node.
#include <Builder3D.h>
Public Member Functions
DrawStyleItem ()=default
DrawStyleItem (DrawStyle)
void setValue (DrawStyle value)
void write (InventorOutput &out) const override
Public Member Functions inherited from Base::NodeItem
virtual ~NodeItem ()=default
Additional Inherited Members
Protected Member Functions inherited from Base::NodeItem
NodeItem ()=default
NodeItem (const NodeItem &)=default
NodeItem (NodeItem &&)=default
NodeItem & operator= (const NodeItem &)=default
NodeItem & operator= (NodeItem &&)=default
Detailed Description
The DrawStyleItem class supports the SoDrawStyle node.
Definition at line 438 of file Builder3D.h.
Constructor & Destructor Documentation
DrawStyleItem() [1/2]
Base::DrawStyleItem::DrawStyleItem () default
DrawStyleItem() [2/2]
DrawStyleItem::DrawStyleItem (DrawStyle value) explicit
Definition at line 636 of file Builder3D.cpp.
Member Function Documentation
setValue()
void DrawStyleItem::setValue (DrawStyle value)
Definition at line 640 of file Builder3D.cpp.
write()
void DrawStyleItem::write (InventorOutput & out) const override virtual
Implements Base::NodeItem.
Definition at line 645 of file Builder3D.cpp.
References Base::DrawStyle::lineWidth, Base::DrawStyle::patternAsString(), Base::DrawStyle::pointSize, Base::DrawStyle::styleAsString(), and Base::InventorOutput::write().
The documentation for this class was generated from the following files:
Builder3D.h
Builder3D.cpp