FreeCAD: Sheet.cpp File Reference
Sheet.cpp File Reference
#include "PreCompiled.h"
#include <boost/tokenizer.hpp>
#include <deque>
#include <memory>
#include <sstream>
#include <App/Application.h>
#include <App/Document.h>
#include <App/DynamicProperty.h>
#include <App/ExpressionParser.h>
#include <App/FeaturePythonPyImp.h>
#include <Base/Exception.h>
#include <Base/FileInfo.h>
#include <Base/Reader.h>
#include <Base/Stream.h>
#include "Sheet.h"
#include "SheetObserver.h"
#include "SheetPy.h"
Classes
struct CurrentAddressLock
Namespaces
App
a class to assist with exporting sketches to dxf
Typedefs
using DependencyList = boost::adjacency_list< boost::vecS, boost::vecS, boost::directedS, boost::no_property, boost::no_property, boost::no_property, boost::listS >
using Traits = boost::graph_traits< DependencyList >
using Vertex = Traits::vertex_descriptor
using Edge = Traits::edge_descriptor
Functions
static void writeEscaped (std::string const &s, char quoteChar, char escapeChar, std::ostream &out)
static unsigned _getBorder (const Sheet *sheet, const std::vector< App::Range > &ranges, const App::CellAddress &address)
Typedef Documentation
DependencyList
using DependencyList = boost::adjacency_list< boost::vecS, boost::vecS, boost::directedS, boost::no_property, boost::no_property, boost::no_property, boost::listS >
Definition at line 63 of file Sheet.cpp.
Edge
using Edge = Traits::edge_descriptor
Definition at line 66 of file Sheet.cpp.
Traits
using Traits = boost::graph_traits<DependencyList>
Definition at line 64 of file Sheet.cpp.
Vertex
using Vertex = Traits::vertex_descriptor
Definition at line 65 of file Sheet.cpp.
Function Documentation
_getBorder()
static unsigned _getBorder (const Sheet * sheet, const std::vector< App::Range > & ranges, const App::CellAddress & address) inline static
Definition at line 955 of file Sheet.cpp.
References Spreadsheet::Sheet::BorderAll, Spreadsheet::Sheet::BorderBottom, Spreadsheet::Sheet::BorderLeft, Spreadsheet::Sheet::BorderRight, Spreadsheet::Sheet::BorderTop, App::CellAddress::col(), Spreadsheet::Sheet::getSpans(), and App::CellAddress::row().
Referenced by Spreadsheet::Sheet::getCellBindingBorder(), and Spreadsheet::Sheet::getCopyOrCutBorder().
writeEscaped()
static void writeEscaped (std::string const & s, char quoteChar, char escapeChar, std::ostream & out) static
Write an escaped version of the string s to the stream out.
Parameters
s The string to write.
quoteChar The quote character.
escapeChar The escape character.
stream The stream to output the escaped string to.
Definition at line 270 of file Sheet.cpp.
References SCL.SimpleDataTypes::c, and toolbit-attributes::s.
Referenced by Spreadsheet::Sheet::exportToFile().