FreeCAD: MeshCore::MeshGrid Class Reference
MeshCore::MeshGrid Class Reference abstract
#include <Grid.h>
Public Member Functions
Search
virtual unsigned long Inside (const Base::BoundBox3f &rclBB, std::vector< ElementIndex > &raulElements, bool bDelDoubles=true) const
virtual unsigned long Inside (const Base::BoundBox3f &rclBB, std::set< ElementIndex > &raulElementss) const
virtual unsigned long Inside (const Base::BoundBox3f &rclBB, std::vector< ElementIndex > &raulElements, const Base::Vector3f &rclOrg, float fMaxDist, bool bDelDoubles=true) const
void SearchNearestFromPoint (const Base::Vector3f &pnt, std::set< ElementIndex > &indices) const
Getters
unsigned long GetElements (unsigned long ulX, unsigned long ulY, unsigned long ulZ, std::set< ElementIndex > &raclInd) const
unsigned long GetElements (const Base::Vector3f &rclPoint, std::vector< ElementIndex > &aulFacets) const
virtual void GetGridLengths (float &rfLenX, float &rfLenY, float &rfLenZ) const
virtual void GetCtGrids (unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
Construction
MeshGrid (const MeshKernel &rclM)
Construction.
MeshGrid ()
Construction.
MeshGrid (const MeshGrid &)=default
MeshGrid (MeshGrid &&)=default
MeshGrid & operator= (const MeshGrid &)=default
MeshGrid & operator= (MeshGrid &&)=default
virtual ~MeshGrid ()=default
Destruction.
virtual void Attach (const MeshKernel &rclM)
virtual void Rebuild (int iCtGridPerAxis=20)
virtual void Rebuild (unsigned long ulX, unsigned long ulY, unsigned long ulZ)
Boundings
std::vector< std::vector< std::vector< std::set< ElementIndex > > > > _aulGrid
const MeshKernel * _pclMesh
unsigned long _ulCtElements
unsigned long _ulCtGridsX
unsigned long _ulCtGridsY
unsigned long _ulCtGridsZ
float _fGridLenX
float _fGridLenY
float _fGridLenZ
float _fMinX
float _fMinY
float _fMinZ
class MeshGridIterator
virtual void InitGrid ()
virtual void Clear ()
virtual void CalculateGridLength (int iCtGridPerAxis)
virtual void RebuildGrid ()=0
virtual unsigned long HasElements () const =0
Base::BoundBox3f GetBoundBox (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
Base::BoundBox3f GetBoundBox () const
Base::BoundBox3f GetMeshBoundBox () const
unsigned long GetIndexToPosition (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
bool GetPositionToIndex (unsigned long id, unsigned long &ulX, unsigned long &ulY, unsigned long &ulZ) const
unsigned long GetCtElements (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
virtual void Validate (const MeshKernel &rclM)=0
virtual bool Verify () const =0
bool CheckPosition (const Base::Vector3f &rclPoint, unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
virtual void Position (const Base::Vector3f &rclPoint, unsigned long &rulX, unsigned long &rulY, unsigned long &rulZ) const
bool CheckPos (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
void GetHull (unsigned long ulX, unsigned long ulY, unsigned long ulZ, unsigned long ulDistance, std::set< ElementIndex > &raclInd) const
Detailed Description
The MeshGrid allows one to divide a global mesh object into smaller regions of elements (e.g. facets, points or edges) depending on the resolution of the grid. All grid elements in the grid structure have the same size.
Grids can be used within algorithms to avoid to iterate through all elements, so grids can speed up algorithms dramatically.
Definition at line 55 of file Grid.h.
Constructor & Destructor Documentation
MeshGrid() [1/4]
MeshGrid::MeshGrid (const MeshKernel & rclM) explicit protected
Construction.
Definition at line 38 of file Grid.cpp.
MeshGrid() [2/4]
MeshGrid::MeshGrid () protected
Construction.
Definition at line 52 of file Grid.cpp.
MeshGrid() [3/4]
MeshCore::MeshGrid::MeshGrid (const MeshGrid &) protected default
MeshGrid() [4/4]
MeshCore::MeshGrid::MeshGrid (MeshGrid &&) protected default
~MeshGrid()
virtual MeshCore::MeshGrid::~MeshGrid () virtual default
Destruction.
Member Function Documentation
Attach()
void MeshGrid::Attach (const MeshKernel & rclM) virtual
Attaches the mesh kernel to this grid, an already attached mesh gets detached. The grid gets rebuilt automatically.
Definition at line 66 of file Grid.cpp.
References _pclMesh, and RebuildGrid().
Referenced by MeshCore::MeshFacetGrid::Validate(), and MeshCore::MeshPointGrid::Validate().
CalculateGridLength()
void MeshGrid::CalculateGridLength (int iCtGridPerAxis) protected virtual
Calculates the grid length dependent on the number of grids per axis.
Reimplemented in Inspection::MeshInspectGrid.
Definition at line 294 of file Grid.cpp.
References _pclMesh, _ulCtElements, _ulCtGridsX, _ulCtGridsY, _ulCtGridsZ, Base::BoundBox3< Precision >::CalcDiagonalLength(), MeshCore::MeshKernel::GetBoundBox(), Base::BoundBox3< Precision >::LengthX(), Base::BoundBox3< Precision >::LengthY(), Base::BoundBox3< Precision >::LengthZ(), KDL::max(), Base::pow(), and KDL::sqrt().
Referenced by InitGrid(), and Rebuild().
CheckPos()
bool MeshCore::MeshGrid::CheckPos (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const inline
Checks if this is a valid grid position.
Definition at line 506 of file Grid.h.
References _ulCtGridsX, _ulCtGridsY, and _ulCtGridsZ.
Referenced by GetIndexToPosition(), GetPositionToIndex(), and MeshCore::MeshGridIterator::NextOnRay().
CheckPosition()
bool MeshGrid::CheckPosition (const Base::Vector3f & rclPoint, unsigned long & rulX, unsigned long & rulY, unsigned long & rulZ) const
Checks whether the point is inside the grid. In case it is inside true is returned with the grid position, otherwise false is returned and the grid position is undefined.
Definition at line 249 of file Grid.cpp.
References _fGridLenX, _fGridLenY, _fGridLenZ, _fMinX, _fMinY, _fMinZ, _ulCtGridsX, _ulCtGridsY, _ulCtGridsZ, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by GetElements().
Clear()
void MeshGrid::Clear () protected virtual
Deletes the grid structure.
Definition at line 72 of file Grid.cpp.
References _aulGrid, and _pclMesh.
GetBoundBox() [1/2]
Base::BoundBox3f MeshCore::MeshGrid::GetBoundBox () const inline
Returns the bounding box of the whole.
Definition at line 488 of file Grid.h.
References _fGridLenX, _fGridLenY, _fGridLenZ, _fMinX, _fMinY, _fMinZ, _ulCtGridsX, _ulCtGridsY, and _ulCtGridsZ.
Referenced by Inspection::MeshInspectGrid::AddFacet(), MeshCore::MeshFacetGrid::AddFacet(), Inside(), SearchNearestFromPoint(), and MeshCore::MeshFacetGrid::SearchNearestFromPoint().
GetBoundBox() [2/2]
Base::BoundBox3f MeshCore::MeshGrid::GetBoundBox (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const inline
Returns the bounding box of a given grid element.
Definition at line 479 of file Grid.h.
References _fGridLenX, _fGridLenY, _fGridLenZ, _fMinX, _fMinY, and _fMinZ.
Referenced by MeshCore::MeshGridIterator::InitOnRay(), and MeshCore::MeshGridIterator::NextOnRay().
GetCtElements()
unsigned long MeshCore::MeshGrid::GetCtElements (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const inline
Returns the number of elements in a given grid.
Definition at line 152 of file Grid.h.
GetCtGrids()
virtual void MeshCore::MeshGrid::GetCtGrids (unsigned long & rulX, unsigned long & rulY, unsigned long & rulZ) const inline virtual
Returns the number of grid elements in x,y and z direction.
Definition at line 122 of file Grid.h.
Referenced by MeshCore::MeshEvalSelfIntersection::Evaluate(), and MeshCore::MeshEvalSelfIntersection::GetIntersections().
GetElements() [1/2]
unsigned long MeshGrid::GetElements (const Base::Vector3f & rclPoint, std::vector< ElementIndex > & aulFacets) const
Definition at line 622 of file Grid.cpp.
References _aulGrid, and CheckPosition().
GetElements() [2/2]
unsigned long MeshGrid::GetElements (unsigned long ulX, unsigned long ulY, unsigned long ulZ, std::set< ElementIndex > & raclInd) const
Returns the indices of the elements in the given grid.
Definition at line 608 of file Grid.cpp.
References _aulGrid.
Referenced by MeshCore::MeshEvalPointOnEdge::Evaluate(), MeshCore::MeshPointGrid::FindElements(), MeshCore::MeshAlgorithm::FirstFacetToVertex(), Inspection::InspectNominalFastMesh::getDistance(), and GetHull().
GetGridLengths()
virtual void MeshCore::MeshGrid::GetGridLengths (float & rfLenX, float & rfLenY, float & rfLenZ) const inline virtual
Returns the lengths of the grid elements in x,y and z direction.
Definition at line 115 of file Grid.h.
GetHull()
void MeshGrid::GetHull (unsigned long ulX, unsigned long ulY, unsigned long ulZ, unsigned long ulDistance, std::set< ElementIndex > & raclInd) const
Get the indices of all elements lying in the grids around a given grid with distance ulDistance.
Definition at line 539 of file Grid.cpp.
References _ulCtGridsX, _ulCtGridsY, _ulCtGridsZ, GetElements(), and SplineSurface::i.
Referenced by Inspection::InspectNominalFastMesh::getDistance(), and SearchNearestFromPoint().
GetIndexToPosition()
unsigned long MeshGrid::GetIndexToPosition (unsigned long ulX, unsigned long ulY, unsigned long ulZ) const
Returns an index for the given grid position. If the specified triple is not a valid grid position ULONG_MAX is returned. If the index is valid than its value is between zero and the number of grid elements. For each different grid position a different index is returned.
Definition at line 639 of file Grid.cpp.
References _ulCtGridsX, _ulCtGridsY, and CheckPos().
GetMeshBoundBox()
Base::BoundBox3f MeshCore::MeshGrid::GetMeshBoundBox () const inline
Returns an extended bounding box of the mesh object.
Definition at line 498 of file Grid.h.
References _pclMesh, Base::BoundBox3< Precision >::Enlarge(), MeshCore::MeshKernel::GetBoundBox(), and MeshCore::MESHGRID_BBOX_EXTENSION.
GetPositionToIndex()
bool MeshGrid::GetPositionToIndex (unsigned long id, unsigned long & ulX, unsigned long & ulY, unsigned long & ulZ) const
Returns the grid position to the given index. If the index is equal to or higher than the number of grid elements false is returned and the triple is set to ULONG_MAX.
Definition at line 647 of file Grid.cpp.
References _ulCtGridsX, _ulCtGridsY, and CheckPos().
HasElements()
virtual unsigned long MeshCore::MeshGrid::HasElements () const protected pure virtual
Returns the number of stored elements. Must be implemented in sub-classes.
Implemented in MeshCore::MeshPointGrid, MeshCore::MeshFacetGrid, and Inspection::MeshInspectGrid.
Referenced by Rebuild().
InitGrid()
void MeshGrid::InitGrid () protected virtual
Initializes the size of the internal structure.
Reimplemented in Inspection::MeshInspectGrid.
Definition at line 94 of file Grid.cpp.
References _aulGrid, _fGridLenX, _fGridLenY, _fGridLenZ, _fMinX, _fMinY, _fMinZ, _pclMesh, _ulCtGridsX, _ulCtGridsY, _ulCtGridsZ, CalculateGridLength(), MeshCore::MeshKernel::GetBoundBox(), SplineSurface::i, Base::BoundBox3< Precision >::LengthX(), Base::BoundBox3< Precision >::LengthY(), Base::BoundBox3< Precision >::LengthZ(), MESH_CT_GRID_PER_AXIS, Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, and Base::BoundBox3< Precision >::MinZ.
Referenced by MeshCore::MeshFacetGrid::RebuildGrid(), and MeshCore::MeshPointGrid::RebuildGrid().
Inside() [1/3]
unsigned long MeshGrid::Inside (const Base::BoundBox3f & rclBB, std::set< ElementIndex > & raulElementss) const virtual
Searches for elements lying in the intersection area of the grid and the bounding box.
Definition at line 222 of file Grid.cpp.
References _aulGrid, SplineSurface::i, Base::BoundBox3< Precision >::MaxX, Base::BoundBox3< Precision >::MaxY, Base::BoundBox3< Precision >::MaxZ, Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, Base::BoundBox3< Precision >::MinZ, and Position().
Inside() [2/3]
unsigned long MeshGrid::Inside (const Base::BoundBox3f & rclBB, std::vector< ElementIndex > & raulElements, bool bDelDoubles = true) const virtual
Searches for elements lying in the intersection area of the grid and the bounding box.
Definition at line 142 of file Grid.cpp.
References _aulGrid, SplineSurface::i, Base::BoundBox3< Precision >::MaxX, Base::BoundBox3< Precision >::MaxY, Base::BoundBox3< Precision >::MaxZ, Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, Base::BoundBox3< Precision >::MinZ, and Position().
Referenced by MeshCore::MeshIntersection::getIntersection(), MeshCore::MeshAlgorithm::SearchFacetsFromPolyline(), and MeshCore::MeshFacetGrid::SearchNearestFromPoint().
Inside() [3/3]
unsigned long MeshGrid::Inside (const Base::BoundBox3f & rclBB, std::vector< ElementIndex > & raulElements, const Base::Vector3f & rclOrg, float fMaxDist, bool bDelDoubles = true) const virtual
Searches for elements lying in the intersection area of the grid and the bounding box.
Definition at line 179 of file Grid.cpp.
References _aulGrid, Base::BoundBox3< Precision >::CalcDiagonalLength(), Base::DistanceP2(), GetBoundBox(), SplineSurface::i, Base::BoundBox3< Precision >::MaxX, Base::BoundBox3< Precision >::MaxY, Base::BoundBox3< Precision >::MaxZ, Base::BoundBox3< Precision >::MinX, Base::BoundBox3< Precision >::MinY, Base::BoundBox3< Precision >::MinZ, and Position().
operator=() [1/2]
MeshGrid& MeshCore::MeshGrid::operator= (const MeshGrid &) protected default
operator=() [2/2]
MeshGrid& MeshCore::MeshGrid::operator= (MeshGrid &&) protected default
Position()
void MeshGrid::Position (const Base::Vector3f & rclPoint, unsigned long & rulX, unsigned long & rulY, unsigned long & rulZ) const virtual
Returns the indices of the grid this point lies in. If the point is outside the grid the indices of the nearest grid element are taken.
Definition at line 261 of file Grid.cpp.
References _fGridLenX, _fGridLenY, _fGridLenZ, _fMinX, _fMinY, _fMinZ, _ulCtGridsX, _ulCtGridsY, _ulCtGridsZ, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by Inspection::InspectNominalFastMesh::getDistance(), MeshCore::MeshGridIterator::InitOnRay(), Inside(), SearchNearestFromPoint(), and MeshCore::MeshFacetGrid::SearchNearestFromPoint().
Rebuild() [1/2]
void MeshGrid::Rebuild (int iCtGridPerAxis = 20) virtual
Rebuilds the grid structure.
Definition at line 87 of file Grid.cpp.
References _ulCtElements, CalculateGridLength(), HasElements(), and RebuildGrid().
Referenced by MeshCore::MeshFacetGrid::MeshFacetGrid(), Inspection::MeshInspectGrid::MeshInspectGrid(), and MeshCore::MeshPointGrid::MeshPointGrid().
Rebuild() [2/2]
void MeshGrid::Rebuild (unsigned long ulX, unsigned long ulY, unsigned long ulZ) virtual
Rebuilds the grid structure.
Definition at line 78 of file Grid.cpp.
References _ulCtElements, _ulCtGridsX, _ulCtGridsY, _ulCtGridsZ, HasElements(), and RebuildGrid().
RebuildGrid()
virtual void MeshCore::MeshGrid::RebuildGrid () protected pure virtual
Rebuilds the grid structure. Must be implemented in sub-classes.
Implemented in MeshCore::MeshPointGrid, MeshCore::MeshFacetGrid, and Inspection::MeshInspectGrid.
Referenced by Attach(), and Rebuild().
SearchNearestFromPoint()
void MeshGrid::SearchNearestFromPoint (const Base::Vector3f & pnt, std::set< ElementIndex > & indices) const
Searches for the nearest grids that contain elements from a point, the result are grid indices.
Definition at line 437 of file Grid.cpp.
References _aulGrid, _ulCtGridsX, _ulCtGridsY, _ulCtGridsZ, Base::BoundBox3< Precision >::BACK, Base::BoundBox3< Precision >::BOTTOM, Base::BoundBox3< Precision >::FRONT, GetBoundBox(), Base::BoundBox3< Precision >::GetCenter(), GetHull(), Base::BoundBox3< Precision >::GetSideFromRay(), SplineSurface::i, Base::BoundBox3< Precision >::IsInBox(), Base::BoundBox3< Precision >::LEFT, Position(), Base::BoundBox3< Precision >::RIGHT, and Base::BoundBox3< Precision >::TOP.
Validate()
virtual void MeshCore::MeshGrid::Validate (const MeshKernel & rclM) pure virtual
Validates the grid structure and rebuilds it if needed. Must be implemented in sub-classes.
Implemented in MeshCore::MeshPointGrid, MeshCore::MeshFacetGrid, and Inspection::MeshInspectGrid.
Verify()
virtual bool MeshCore::MeshGrid::Verify () const pure virtual
Verifies the grid structure and returns false if inconsistencies are found.
Implemented in MeshCore::MeshPointGrid, MeshCore::MeshFacetGrid, and Inspection::MeshInspectGrid.
Friends And Related Function Documentation
MeshGridIterator
friend class MeshGridIterator friend
Definition at line 214 of file Grid.h.
Member Data Documentation
_aulGrid
std::vector<std::vector<std::vector<std::set<ElementIndex> > > > MeshCore::MeshGrid::_aulGrid protected
Grid data structure.
Definition at line 199 of file Grid.h.
Referenced by Inspection::MeshInspectGrid::AddFacet(), MeshCore::MeshFacetGrid::AddFacet(), MeshCore::MeshPointGrid::AddPoint(), Clear(), GetElements(), InitGrid(), Inspection::MeshInspectGrid::InitGrid(), MeshCore::MeshGridIterator::InitOnRay(), Inside(), MeshCore::MeshGridIterator::NextOnRay(), MeshCore::MeshFacetGrid::SearchNearestFacetInGrid(), and SearchNearestFromPoint().
_fGridLenX
float MeshCore::MeshGrid::_fGridLenX protected
Length of grid elements in x.
Definition at line 205 of file Grid.h.
Referenced by CheckPosition(), GetBoundBox(), InitGrid(), Inspection::MeshInspectGrid::InitGrid(), Inspection::MeshInspectGrid::Pos(), MeshCore::MeshFacetGrid::Pos(), MeshCore::MeshPointGrid::Pos(), Position(), MeshCore::MeshFacetGrid::PosWithCheck(), and MeshCore::MeshFacetGrid::SearchNearestFromPoint().
_fGridLenY
float MeshCore::MeshGrid::_fGridLenY protected
Length of grid elements in y.
Definition at line 206 of file Grid.h.
Referenced by CheckPosition(), GetBoundBox(), InitGrid(), Inspection::MeshInspectGrid::InitGrid(), Inspection::MeshInspectGrid::Pos(), MeshCore::MeshFacetGrid::Pos(), MeshCore::MeshPointGrid::Pos(), Position(), MeshCore::MeshFacetGrid::PosWithCheck(), and MeshCore::MeshFacetGrid::SearchNearestFromPoint().
_fGridLenZ
float MeshCore::MeshGrid::_fGridLenZ protected
Length of grid elements in z.
Definition at line 207 of file Grid.h.
Referenced by CheckPosition(), GetBoundBox(), InitGrid(), Inspection::MeshInspectGrid::InitGrid(), Inspection::MeshInspectGrid::Pos(), MeshCore::MeshFacetGrid::Pos(), MeshCore::MeshPointGrid::Pos(), Position(), MeshCore::MeshFacetGrid::PosWithCheck(), and MeshCore::MeshFacetGrid::SearchNearestFromPoint().
_fMinX
float MeshCore::MeshGrid::_fMinX protected
Grid null position in x.
Definition at line 208 of file Grid.h.
Referenced by CheckPosition(), GetBoundBox(), InitGrid(), Inspection::MeshInspectGrid::InitGrid(), Inspection::MeshInspectGrid::Pos(), MeshCore::MeshFacetGrid::Pos(), MeshCore::MeshPointGrid::Pos(), Position(), and MeshCore::MeshFacetGrid::PosWithCheck().
_fMinY
float MeshCore::MeshGrid::_fMinY protected
Grid null position in y.
Definition at line 209 of file Grid.h.
Referenced by CheckPosition(), GetBoundBox(), InitGrid(), Inspection::MeshInspectGrid::InitGrid(), Inspection::MeshInspectGrid::Pos(), MeshCore::MeshFacetGrid::Pos(), MeshCore::MeshPointGrid::Pos(), Position(), and MeshCore::MeshFacetGrid::PosWithCheck().
_fMinZ
float MeshCore::MeshGrid::_fMinZ protected
Grid null position in z.
Definition at line 210 of file Grid.h.
Referenced by CheckPosition(), GetBoundBox(), InitGrid(), Inspection::MeshInspectGrid::InitGrid(), Inspection::MeshInspectGrid::Pos(), MeshCore::MeshFacetGrid::Pos(), MeshCore::MeshPointGrid::Pos(), Position(), and MeshCore::MeshFacetGrid::PosWithCheck().
_pclMesh
const MeshKernel* MeshCore::MeshGrid::_pclMesh protected
The mesh kernel.
Definition at line 200 of file Grid.h.
Referenced by Attach(), CalculateGridLength(), Clear(), GetMeshBoundBox(), Inspection::MeshInspectGrid::HasElements(), InitGrid(), Inspection::MeshInspectGrid::InitGrid(), MeshCore::MeshFacetGrid::MeshFacetGrid(), Inspection::MeshInspectGrid::MeshInspectGrid(), MeshCore::MeshPointGrid::MeshPointGrid(), Inspection::MeshInspectGrid::RebuildGrid(), MeshCore::MeshFacetGrid::RebuildGrid(), MeshCore::MeshPointGrid::RebuildGrid(), MeshCore::MeshFacetGrid::SearchNearestFacetInGrid(), MeshCore::MeshFacetGrid::SearchNearestFromPoint(), MeshCore::MeshFacetGrid::Validate(), MeshCore::MeshPointGrid::Validate(), MeshCore::MeshFacetGrid::Verify(), and MeshCore::MeshPointGrid::Verify().
_ulCtElements
unsigned long MeshCore::MeshGrid::_ulCtElements protected
Number of grid elements for validation issues.
Definition at line 201 of file Grid.h.
Referenced by CalculateGridLength(), Rebuild(), Inspection::MeshInspectGrid::RebuildGrid(), MeshCore::MeshFacetGrid::RebuildGrid(), MeshCore::MeshPointGrid::RebuildGrid(), MeshCore::MeshFacetGrid::Validate(), MeshCore::MeshPointGrid::Validate(), MeshCore::MeshFacetGrid::Verify(), and MeshCore::MeshPointGrid::Verify().
_ulCtGridsX
unsigned long MeshCore::MeshGrid::_ulCtGridsX protected
Number of grid elements in z.
Definition at line 202 of file Grid.h.
Referenced by MeshCore::MeshPointGrid::AddPoint(), CalculateGridLength(), CheckPos(), CheckPosition(), MeshCore::MeshPointGrid::FindElements(), GetBoundBox(), GetHull(), GetIndexToPosition(), GetPositionToIndex(), InitGrid(), Inspection::MeshInspectGrid::InitGrid(), Inspection::MeshInspectGrid::Pos(), MeshCore::MeshFacetGrid::Pos(), Position(), MeshCore::MeshFacetGrid::PosWithCheck(), Rebuild(), MeshCore::MeshFacetGrid::SearchNearestFacetInHull(), SearchNearestFromPoint(), and MeshCore::MeshFacetGrid::SearchNearestFromPoint().
_ulCtGridsY
unsigned long MeshCore::MeshGrid::_ulCtGridsY protected
Number of grid elements in z.
Definition at line 203 of file Grid.h.
Referenced by MeshCore::MeshPointGrid::AddPoint(), CalculateGridLength(), CheckPos(), CheckPosition(), MeshCore::MeshPointGrid::FindElements(), GetBoundBox(), GetHull(), GetIndexToPosition(), GetPositionToIndex(), InitGrid(), Inspection::MeshInspectGrid::InitGrid(), Inspection::MeshInspectGrid::Pos(), MeshCore::MeshFacetGrid::Pos(), Position(), MeshCore::MeshFacetGrid::PosWithCheck(), Rebuild(), MeshCore::MeshFacetGrid::SearchNearestFacetInHull(), SearchNearestFromPoint(), and MeshCore::MeshFacetGrid::SearchNearestFromPoint().
_ulCtGridsZ
unsigned long MeshCore::MeshGrid::_ulCtGridsZ protected
Number of grid elements in z.
Definition at line 204 of file Grid.h.
Referenced by MeshCore::MeshPointGrid::AddPoint(), CalculateGridLength(), CheckPos(), CheckPosition(), MeshCore::MeshPointGrid::FindElements(), GetBoundBox(), GetHull(), InitGrid(), Inspection::MeshInspectGrid::InitGrid(), Inspection::MeshInspectGrid::Pos(), MeshCore::MeshFacetGrid::Pos(), Position(), MeshCore::MeshFacetGrid::PosWithCheck(), Rebuild(), MeshCore::MeshFacetGrid::SearchNearestFacetInHull(), SearchNearestFromPoint(), and MeshCore::MeshFacetGrid::SearchNearestFromPoint().
The documentation for this class was generated from the following files:
Grid.h
Grid.cpp