FreeCAD: Part::WireJoiner Class Reference
Part::WireJoiner Class Reference
#include <WireJoiner.h>
Public Member Functions
WireJoiner ()
~WireJoiner () override
void addShape (const TopoShape &shape)
void addShape (const std::vector< TopoShape > &shapes)
void addShape (const std::vector< TopoDS_Shape > &shapes)
void setOutline (bool enable=true)
void setTightBound (bool enable=true)
void setSplitEdges (bool enable=true)
void setMergeEdges (bool enable=true)
void setTolerance (double tolerance, double atol=0.0)
bool getOpenWires (TopoShape &shape, const char *op="", bool noOriginal=true)
bool getResultWires (TopoShape &shape, const char *op="")
void Build () override
const TopTools_ListOfShape & Modified (const TopoDS_Shape &SThatModifies) override
const TopTools_ListOfShape & Generated (const TopoDS_Shape &SThatGenerates) override
Standard_Boolean IsDeleted (const TopoDS_Shape &SDeleted) override
Detailed Description
Definition at line 53 of file WireJoiner.h.
Constructor & Destructor Documentation
WireJoiner()
Part::WireJoiner::WireJoiner ()
~WireJoiner()
Part::WireJoiner::~WireJoiner () override
Member Function Documentation
addShape() [1/3]
void Part::WireJoiner::addShape (const std::vector< TopoDS_Shape > & shapes)
addShape() [2/3]
void Part::WireJoiner::addShape (const std::vector< TopoShape > & shapes)
addShape() [3/3]
void Part::WireJoiner::addShape (const TopoShape & shape)
Referenced by Sketcher::SketchObject::buildInternals().
Build()
void Part::WireJoiner::Build () override
Generated()
const TopTools_ListOfShape& Part::WireJoiner::Generated (const TopoDS_Shape & SThatGenerates) override
getOpenWires()
bool Part::WireJoiner::getOpenWires (TopoShape & shape, const char * op = "", bool noOriginal = true)
Referenced by Sketcher::SketchObject::buildInternals().
getResultWires()
bool Part::WireJoiner::getResultWires (TopoShape & shape, const char * op = "")
Referenced by Sketcher::SketchObject::buildInternals().
IsDeleted()
Standard_Boolean Part::WireJoiner::IsDeleted (const TopoDS_Shape & SDeleted) override
Modified()
const TopTools_ListOfShape& Part::WireJoiner::Modified (const TopoDS_Shape & SThatModifies) override
setMergeEdges()
void Part::WireJoiner::setMergeEdges (bool enable = true)
Referenced by Sketcher::SketchObject::buildInternals().
setOutline()
void Part::WireJoiner::setOutline (bool enable = true)
setSplitEdges()
void Part::WireJoiner::setSplitEdges (bool enable = true)
setTightBound()
void Part::WireJoiner::setTightBound (bool enable = true)
Referenced by Sketcher::SketchObject::buildInternals().
setTolerance()
void Part::WireJoiner::setTolerance (double tolerance, double atol = 0.0)
The documentation for this class was generated from the following file:
WireJoiner.h