FreeCAD: Sketcher::PythonConverter Class Reference
Sketcher::PythonConverter Class Reference
Class for generating python code.
#include <PythonConverter.h>
Public Types
enum Mode { Mode::CreateInternalGeometry, Mode::OmitInternalGeometry }
enum GeoIdMode { GeoIdMode::DoNotChangeGeoIds, GeoIdMode::AddLastGeoIdToGeoIds }
Public Member Functions
PythonConverter ()=delete
~PythonConverter ()=delete
Static Public Member Functions
static std::string convert (const Part::Geometry *geo, Mode mode=Mode::CreateInternalGeometry)
Convert a geometry into the string representing the command creating it.
static std::string convert (const std::string &doc, const std::vector< Part::Geometry * > &geos, Mode mode=Mode::CreateInternalGeometry)
Convert a vector of geometries into the string representing the command creating them.
static std::string convert (const Sketcher::Constraint *constraint, GeoIdMode geoIdMode=GeoIdMode::DoNotChangeGeoIds)
static std::string convert (const std::string &doc, const std::vector< Sketcher::Constraint * > &constraints, GeoIdMode geoIdMode=GeoIdMode::DoNotChangeGeoIds)
static std::vector< std::string > multiLine (std::string &&singlestring)
Detailed Description
Class for generating python code.
Given C++ structures, it generates the python code that should be written in the console to create such objects.
Definition at line 47 of file PythonConverter.h.
Member Enumeration Documentation
GeoIdMode
enum Sketcher::PythonConverter::GeoIdMode strong
Enumerator
DoNotChangeGeoIds
AddLastGeoIdToGeoIds
Definition at line 63 of file PythonConverter.h.
Mode
enum Sketcher::PythonConverter::Mode strong
Enumerator
CreateInternalGeometry
OmitInternalGeometry
Definition at line 57 of file PythonConverter.h.
Constructor & Destructor Documentation
PythonConverter()
Sketcher::PythonConverter::PythonConverter () delete
~PythonConverter()
Sketcher::PythonConverter::~PythonConverter () delete
Member Function Documentation
convert() [1/4]
std::string PythonConverter::convert (const Part::Geometry * geo, Mode mode = Mode::CreateInternalGeometry) static
Convert a geometry into the string representing the command creating it.
Definition at line 39 of file PythonConverter.cpp.
References CreateInternalGeometry, Base::Persistence::getClassTypeId(), Base::Persistence::getTypeId(), and Path.Post.scripts.refactored_centroid_post::str.
Referenced by convert(), copySelectionToClipboard(), and SketcherGui::DrawSketchDefaultHandler< ControllerT::HandlerType, ControllerT::SelectModeType, ControllerT::AutoConstraintInitialSize, ControllerT::ContructionMethodType >::createGeneratedAutoConstraints().
convert() [2/4]
std::string PythonConverter::convert (const Sketcher::Constraint * constraint, GeoIdMode geoIdMode = GeoIdMode::DoNotChangeGeoIds) static
Definition at line 62 of file PythonConverter.cpp.
References Path.Post.scripts.refactored_centroid_post::str.
convert() [3/4]
std::string PythonConverter::convert (const std::string & doc, const std::vector< Part::Geometry * > & geos, Mode mode = Mode::CreateInternalGeometry) static
Convert a vector of geometries into the string representing the command creating them.
Definition at line 73 of file PythonConverter.cpp.
References CreateInternalGeometry, toolbit-attributes::doc, Base::Persistence::getClassTypeId(), Sketcher::GeometryFacade::getConstruction(), Path.Post.scripts.opensbp_post::move(), and Path.Post.scripts.refactored_centroid_post::str.
convert() [4/4]
std::string PythonConverter::convert (const std::string & doc, const std::vector< Sketcher::Constraint * > & constraints, GeoIdMode geoIdMode = GeoIdMode::DoNotChangeGeoIds) static
Definition at line 167 of file PythonConverter.cpp.
References convert(), toolbit-attributes::doc, and Path.Post.scripts.refactored_centroid_post::str.
multiLine()
std::vector< std::string > PythonConverter::multiLine (std::string && singlestring) static
Definition at line 695 of file PythonConverter.cpp.
References femtools.tokrules::tokens.
The documentation for this class was generated from the following files:
PythonConverter.h
PythonConverter.cpp