FreeCAD: TechDrawGui::QGIBreakLine Class Reference
TechDrawGui::QGIBreakLine Class Reference
#include <QGIBreakLine.h>
Public Types
enum { Type = QGraphicsItem::UserType + 250 }
Public Types inherited from TechDrawGui::QGIDecoration
enum { Type = QGraphicsItem::UserType + 173 }
Public Member Functions
QGIBreakLine ()
~QGIBreakLine () override=default
int type () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
void setBounds (double left, double top, double right, double bottom)
void setBounds (Base::Vector3d topLeft, Base::Vector3d bottomRight)
void setDirection (Base::Vector3d dir)
void draw () override
void setLinePen (QPen isoPen)
void setBreakColor (QColor c)
void setBreakType (int style)
int breakType () const
Public Member Functions inherited from TechDrawGui::QGIDecoration
QGIDecoration ()
~QGIDecoration () override=default
int type () const override
QRectF boundingRect () const override
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=nullptr) override
void mousePressEvent (QGraphicsSceneMouseEvent *event) override
void mouseMoveEvent (QGraphicsSceneMouseEvent *event) override
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event) override
virtual void onDragFinished ()
void setWidth (double w)
double getWidth ()
void setStyle (Qt::PenStyle s)
void setColor (QColor c)
QColor getColor ()
void setFill (Qt::BrushStyle bs)
void makeMark (double x, double y)
void makeMark (Base::Vector3d v)
Additional Inherited Members
Protected Member Functions inherited from TechDrawGui::QGIDecoration
void setPrettyNormal ()
void setPrettyPre ()
void setPrettySel ()
virtual QColor prefNormalColor ()
virtual QColor prefPreColor ()
virtual QColor prefSelectColor ()
Protected Attributes inherited from TechDrawGui::QGIDecoration
QPen m_pen
QBrush m_brush
QColor m_colCurrent
QColor m_colNormal
double m_width
Qt::PenStyle m_styleCurrent
Qt::BrushStyle m_brushCurrent
int m_dragState
Detailed Description
Definition at line 63 of file QGIBreakLine.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 89 of file QGIBreakLine.h.
Constructor & Destructor Documentation
QGIBreakLine()
QGIBreakLine::QGIBreakLine () explicit
Definition at line 52 of file QGIBreakLine.cpp.
References TechDrawGui::PreferencesGui::sectionLineQColor(), and importers.importIFCmulticore::setColor().
~QGIBreakLine()
TechDrawGui::QGIBreakLine::~QGIBreakLine () override default
Member Function Documentation
breakType()
int TechDrawGui::QGIBreakLine::breakType () const inline
Definition at line 103 of file QGIBreakLine.h.
draw()
void QGIBreakLine::draw () override virtual
Reimplemented from TechDrawGui::QGIDecoration.
Definition at line 72 of file QGIBreakLine.cpp.
Referenced by TechDrawGui::QGIViewPart::drawBreakLines().
paint()
void QGIBreakLine::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = nullptr) override
Definition at line 242 of file QGIBreakLine.cpp.
References TechDrawGui::QGIDecoration::paint().
setBounds() [1/2]
void QGIBreakLine::setBounds (Base::Vector3d topLeft, Base::Vector3d bottomRight)
Definition at line 221 of file QGIBreakLine.cpp.
References KDL::max(), KDL::min(), Base::Vector3< float_type >::x, and Base::Vector3< float_type >::y.
setBounds() [2/2]
void QGIBreakLine::setBounds (double left, double top, double right, double bottom)
Definition at line 212 of file QGIBreakLine.cpp.
Referenced by TechDrawGui::QGIViewPart::drawBreakLines().
setBreakColor()
void QGIBreakLine::setBreakColor (QColor c)
Definition at line 237 of file QGIBreakLine.cpp.
References SCL.SimpleDataTypes::c, and importers.importIFCmulticore::setColor().
Referenced by TechDrawGui::QGIViewPart::drawBreakLines().
setBreakType()
void TechDrawGui::QGIBreakLine::setBreakType (int style) inline
Definition at line 102 of file QGIBreakLine.h.
Referenced by TechDrawGui::QGIViewPart::drawBreakLines().
setDirection()
void QGIBreakLine::setDirection (Base::Vector3d dir)
Definition at line 231 of file QGIBreakLine.cpp.
Referenced by TechDrawGui::QGIViewPart::drawBreakLines().
setLinePen()
void QGIBreakLine::setLinePen (QPen isoPen)
Definition at line 271 of file QGIBreakLine.cpp.
Referenced by TechDrawGui::QGIViewPart::drawBreakLines().
type()
int TechDrawGui::QGIBreakLine::type () const inline override
Definition at line 90 of file QGIBreakLine.h.
The documentation for this class was generated from the following files:
QGIBreakLine.h
QGIBreakLine.cpp