FreeCAD: Gui::WorkbenchGroup Class Reference
Gui::WorkbenchGroup Class Reference
#include <Action.h>
Signals
void workbenchListRefreshed (QList< QAction * >)
Signals inherited from Gui::ActionGroup
void aboutToHide (QMenu *)
When drop down menu is enabled, the signal is triggered just before hiding the menu.
void aboutToShow (QMenu *)
When drop down menu is enabled, the signal is triggered just before showing the menu.
Public Member Functions
WorkbenchGroup (Command *pcCmd, QObject *parent)
void addTo (QWidget *widget) override
void refreshWorkbenchList ()
void slotActivateWorkbench (const char *)
QList< QAction * > getEnabledWbActions () const
QList< QAction * > getDisabledWbActions () const
Public Member Functions inherited from Gui::ActionGroup
ActionGroup (Command *pcCmd, QObject *parent=nullptr)
~ActionGroup () override
void setEnabled (bool) override
void setDisabled (bool)
void setExclusive (bool)
bool isExclusive () const
void setVisible (bool) override
void setIsMode (bool check)
void setRememberLast (bool)
bool doesRememberLast () const
void setDropDownMenu (bool check)
QAction * addAction (QAction *)
QAction * addAction (const QString &)
QList< QAction * > actions () const
int checkedAction () const
void setCheckedAction (int)
QActionGroup * groupAction () const
Public Member Functions inherited from Gui::Action
Action (Command *pcCmd, QObject *parent=nullptr)
Action (Command *pcCmd, QAction *action, QObject *parent)
Action takes ownership of the 'action' object.
~Action () override
void setCheckable (bool)
void setChecked (bool, bool no_signal=false)
bool isChecked () const
bool isEnabled () const
void setShortcut (const QString &)
QKeySequence shortcut () const
void setIcon (const QIcon &)
QIcon icon () const
void setStatusTip (const QString &)
QString statusTip () const
void setText (const QString &)
QString text () const
void setToolTip (const QString &, const QString &title=QString())
QString toolTip () const
void setWhatsThis (const QString &)
QString whatsThis () const
void setMenuRole (QAction::MenuRole menuRole)
QAction * action () const
Command * command () const
Protected Slots
void onWorkbenchActivated (const QString &)
Additional Inherited Members
Public Slots inherited from Gui::ActionGroup
void onActivated () override
void onToggled (bool) override
void onActivated (QAction *)
void onHovered (QAction *)
Public Slots inherited from Gui::Action
virtual void onActivated ()
virtual void onToggled (bool)
Static Public Member Functions inherited from Gui::Action
static QString createToolTip (QString helpText, const QString &title, const QFont &font, const QString &shortCut, const Command *command=nullptr)
static QString commandToolTip (const Command *cmd, bool richFormat=true)
static QString commandMenuText (const Command *cmd)
static QString cleanTitle (const QString &title)
Clean the title by stripping the mnemonic symbol '&' and ending punctuation.
Detailed Description
The WorkbenchGroup class represents a list of workbenches. When it is added to a menu a submenu gets created, if added to a toolbar a combo box gets created.
Author
Werner Mayer
Definition at line 208 of file Action.h.
Constructor & Destructor Documentation
WorkbenchGroup()
WorkbenchGroup::WorkbenchGroup (Command * pcCmd, QObject * parent)
Creates an action for the command pcCmd to load the workbench name when it gets activated.
Definition at line 612 of file Action.cpp.
References draftgeoutils.faces::bind(), draftgeoutils.intersections::connect(), Gui::getMainWindow(), Gui::Application::Instance, onWorkbenchActivated(), refreshWorkbenchList(), Gui::Application::signalRefreshWorkbenches, and Gui::MainWindow::workbenchActivated().
Member Function Documentation
addTo()
void WorkbenchGroup::addTo (QWidget * widget) override virtual
Adds this action to widget w.
Reimplemented from Gui::ActionGroup.
Definition at line 634 of file Action.cpp.
References Gui::Action::action(), Gui::ActionGroup::actions(), draftgeoutils.intersections::connect(), App::GetApplication(), getEnabledWbActions(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), NavigationIndicatorGui::menu, Gui::Action::text(), and workbenchListRefreshed().
Referenced by src.Mod.PartDesign.WizardShaft.Shaft.Shaft::equilibrium().
getDisabledWbActions()
QList< QAction * > WorkbenchGroup::getDisabledWbActions () const
Definition at line 761 of file Action.cpp.
Referenced by Gui::WorkbenchTabWidget::buildPrefMenu(), and Gui::WorkbenchTabWidget::handleWorkbenchSelection().
getEnabledWbActions()
QList< QAction * > WorkbenchGroup::getEnabledWbActions () const
Definition at line 756 of file Action.cpp.
Referenced by addTo(), Gui::WorkbenchTabWidget::updateWorkbenchList(), and Gui::WorkbenchComboBox::WorkbenchComboBox().
onWorkbenchActivated
void WorkbenchGroup::onWorkbenchActivated (const QString & name) protected slot
Definition at line 733 of file Action.cpp.
References Gui::Action::action(), and Gui::ActionGroup::actions().
Referenced by WorkbenchGroup().
refreshWorkbenchList()
void WorkbenchGroup::refreshWorkbenchList ()
Definition at line 662 of file Action.cpp.
References Gui::Action::action(), Gui::ActionGroup::actions(), Gui::WorkbenchManager::activeName(), Gui::ActionGroup::groupAction(), Gui::WorkbenchManager::instance(), Gui::Application::Instance, Gui::Application::workbenchIcon(), workbenchListRefreshed(), Gui::Application::workbenchMenuText(), and Gui::Application::workbenchToolTip().
Referenced by WorkbenchGroup().
slotActivateWorkbench()
void Gui::WorkbenchGroup::slotActivateWorkbench (const char *)
workbenchListRefreshed
void Gui::WorkbenchGroup::workbenchListRefreshed (QList< QAction * >) signal
Referenced by addTo(), refreshWorkbenchList(), Gui::WorkbenchComboBox::WorkbenchComboBox(), and Gui::WorkbenchTabWidget::WorkbenchTabWidget().
The documentation for this class was generated from the following files:
Action.h
Action.cpp