FreeCAD: src.Mod.AddonManager.addonmanager_devmode_metadata_checker.MetadataValidators Class Reference
src.Mod.AddonManager.addonmanager_devmode_metadata_checker.MetadataValidators Class Reference
Public Member Functions
def validate_all (self, repos)
def validate_package_xml (self, Addon addon)
List[str] validate_content (self, Addon addon)
List[str] validate_top_level (self, Addon addon)
Static Public Member Functions
List[str] validate_urls (urls)
List[str] validate_workbench_metadata (Metadata workbench)
List[str] validate_preference_pack_metadata (Metadata pack)
Detailed Description
A collection of tools for validating various pieces of metadata. Prints
validation information to the console.
Definition at line 35 of file addonmanager_devmode_metadata_checker.py.
Member Function Documentation
validate_all()
def src.Mod.AddonManager.addonmanager_devmode_metadata_checker.MetadataValidators.validate_all (self, repos)
Developer tool: check all repos for validity and print report
Definition at line 39 of file addonmanager_devmode_metadata_checker.py.
References src.Mod.AddonManager.addonmanager_devmode_metadata_checker.MetadataValidators.validate_package_xml().
validate_content()
List[str] src.Mod.AddonManager.addonmanager_devmode_metadata_checker.MetadataValidators.validate_content (self, Addon addon)
Validate the Content items for this Addon
Definition at line 82 of file addonmanager_devmode_metadata_checker.py.
References src.Mod.AddonManager.addonmanager_devmode_metadata_checker.MetadataValidators.validate_preference_pack_metadata(), and src.Mod.AddonManager.addonmanager_devmode_metadata_checker.MetadataValidators.validate_workbench_metadata().
Referenced by src.Mod.AddonManager.addonmanager_devmode_metadata_checker.MetadataValidators.validate_package_xml().
validate_package_xml()
def src.Mod.AddonManager.addonmanager_devmode_metadata_checker.MetadataValidators.validate_package_xml (self, Addon addon)
Check the package.xml file for the specified Addon
Definition at line 63 of file addonmanager_devmode_metadata_checker.py.
References src.Mod.AddonManager.addonmanager_devmode_metadata_checker.MetadataValidators.validate_content(), and src.Mod.AddonManager.addonmanager_devmode_metadata_checker.MetadataValidators.validate_top_level().
Referenced by src.Mod.AddonManager.addonmanager_devmode_metadata_checker.MetadataValidators.validate_all().
validate_preference_pack_metadata()
List[str] src.Mod.AddonManager.addonmanager_devmode_metadata_checker.MetadataValidators.validate_preference_pack_metadata (Metadata pack) static
Validate the required element(s) for a preference pack
Definition at line 179 of file addonmanager_devmode_metadata_checker.py.
Referenced by src.Mod.AddonManager.addonmanager_devmode_metadata_checker.MetadataValidators.validate_content().
validate_top_level()
List[str] src.Mod.AddonManager.addonmanager_devmode_metadata_checker.MetadataValidators.validate_top_level (self, Addon addon)
Check for the presence of the required top-level elements
Definition at line 108 of file addonmanager_devmode_metadata_checker.py.
References src.Mod.AddonManager.addonmanager_devmode_metadata_checker.MetadataValidators.validate_urls().
Referenced by src.Mod.AddonManager.addonmanager_devmode_metadata_checker.MetadataValidators.validate_package_xml().
validate_urls()
List[str] src.Mod.AddonManager.addonmanager_devmode_metadata_checker.MetadataValidators.validate_urls (urls) static
Check the URLs provided by the addon
Definition at line 136 of file addonmanager_devmode_metadata_checker.py.
References importFCMat.decode().
Referenced by src.Mod.AddonManager.addonmanager_devmode_metadata_checker.MetadataValidators.validate_top_level().
validate_workbench_metadata()
List[str] src.Mod.AddonManager.addonmanager_devmode_metadata_checker.MetadataValidators.validate_workbench_metadata (Metadata workbench) static
Validate the required element(s) for a workbench
Definition at line 171 of file addonmanager_devmode_metadata_checker.py.
Referenced by src.Mod.AddonManager.addonmanager_devmode_metadata_checker.MetadataValidators.validate_content().
The documentation for this class was generated from the following file:
addonmanager_devmode_metadata_checker.py