FreeCAD: Wm4::Vector2< Real > Class Template Reference
Wm4::Vector2< Real > Class Template Reference
#include <Wm4Vector2.h>
Public Member Functions
Vector2 ()
Vector2 (Real fX, Real fY)
Vector2 (const Real *afTuple)
Vector2 (const Vector2 &rkV)
operator const Real * () const
operator Real * ()
Real operator[] (int i) const
Real & operator[] (int i)
Real X () const
Real & X ()
Real Y () const
Real & Y ()
Vector2 & operator= (const Vector2 &rkV)
bool operator== (const Vector2 &rkV) const
bool operator!= (const Vector2 &rkV) const
bool operator< (const Vector2 &rkV) const
bool operator<= (const Vector2 &rkV) const
bool operator> (const Vector2 &rkV) const
bool operator>= (const Vector2 &rkV) const
Vector2 operator+ (const Vector2 &rkV) const
Vector2 operator- (const Vector2 &rkV) const
Vector2 operator* (Real fScalar) const
Vector2 operator/ (Real fScalar) const
Vector2 operator- () const
Vector2 & operator+= (const Vector2 &rkV)
Vector2 & operator-= (const Vector2 &rkV)
Vector2 & operator*= (Real fScalar)
Vector2 & operator/= (Real fScalar)
Real Length () const
Real SquaredLength () const
Real Dot (const Vector2 &rkV) const
Real Normalize ()
Vector2 Perp () const
Vector2 UnitPerp () const
Real DotPerp (const Vector2 &rkV) const
void GetBarycentrics (const Vector2 &rkV0, const Vector2 &rkV1, const Vector2 &rkV2, Real afBary[3]) const
const Vector2< float > ZERO (0.0f, 0.0f)
const Vector2< float > UNIT_X (1.0f, 0.0f)
const Vector2< float > UNIT_Y (0.0f, 1.0f)
const Vector2< float > ONE (1.0f, 1.0f)
const Vector2< double > ZERO (0.0, 0.0)
const Vector2< double > UNIT_X (1.0, 0.0)
const Vector2< double > UNIT_Y (0.0, 1.0)
const Vector2< double > ONE (1.0, 1.0)
Static Public Member Functions
static void Orthonormalize (Vector2 &rkU, Vector2 &rkV)
static void GenerateOrthonormalBasis (Vector2 &rkU, Vector2 &rkV)
static void ComputeExtremes (int iVQuantity, const Vector2 *akPoint, Vector2 &rkMin, Vector2 &rkMax)
Static Public Attributes
static const Vector2 ZERO
static const Vector2 UNIT_X
static const Vector2 UNIT_Y
static const Vector2 ONE
Detailed Description
template<class Real>
class Wm4::Vector2< Real >
Definition at line 26 of file Wm4Vector2.h.
Constructor & Destructor Documentation
Vector2() [1/4]
template<class Real > Wm4::Vector2< Real >::Vector2 ()
Vector2() [2/4]
template<class Real > Wm4::Vector2< Real >::Vector2 (Real fX, Real fY)
Vector2() [3/4]
template<class Real > Wm4::Vector2< Real >::Vector2 (const Real * afTuple)
Vector2() [4/4]
template<class Real > Wm4::Vector2< Real >::Vector2 (const Vector2< Real > & rkV)
Member Function Documentation
ComputeExtremes()
template<class Real > static void Wm4::Vector2< Real >::ComputeExtremes (int iVQuantity, const Vector2< Real > * akPoint, Vector2< Real > & rkMin, Vector2< Real > & rkMax) static
Referenced by Wm4::ContAlignedBox().
Dot()
template<class Real > Real Wm4::Vector2< Real >::Dot (const Vector2< Real > & rkV) const
Referenced by Wm4::ContMinBox(), Wm4::ContOrientedBox(), Wm4::IntrTriangle2Triangle2< Real >::Find(), Wm4::ConvexHull2< Real >::GetConvexHull1(), Wm4::ConvexHull3< Real >::GetConvexHull2(), Wm4::Delaunay2< Real >::GetDelaunay1(), Wm4::Delaunay3< Real >::GetDelaunay2(), Wm4::InBox(), Wm4::MergeBoxes(), Wm4::IntrTriangle2Triangle2< Real >::Test(), and Wm4::UpdateBox().
DotPerp()
template<class Real > Real Wm4::Vector2< Real >::DotPerp (const Vector2< Real > & rkV) const
GenerateOrthonormalBasis()
template<class Real > static void Wm4::Vector2< Real >::GenerateOrthonormalBasis (Vector2< Real > & rkU, Vector2< Real > & rkV) static
GetBarycentrics()
template<class Real > void Wm4::Vector2< Real >::GetBarycentrics (const Vector2< Real > & rkV0, const Vector2< Real > & rkV1, const Vector2< Real > & rkV2, Real afBary[3]) const
Referenced by Wm4::Delaunay2< Real >::GetBarycentricSet().
Length()
template<class Real > Real Wm4::Vector2< Real >::Length () const
Normalize()
template<class Real > double KDL::Vector2::Normalize ()
Definition at line 98 of file frames.cpp.
References KDL::Norm(), and TestSpreadsheet::v.
Referenced by Wm4::ContMinBox(), and Wm4::MeshCurvature< Real >::MeshCurvature().
ONE() [1/2]
const Vector2< double > Wm4::Vector2< double >::ONE (1. 0, 1. 0)
ONE() [2/2]
const Vector2< float > Wm4::Vector2< float >::ONE (1. 0f, 1. 0f)
operator const Real *()
template<class Real > Wm4::Vector2< Real >::operator const Real * () const
operator Real *()
template<class Real > Wm4::Vector2< Real >::operator Real * ()
operator!=()
template<class Real > bool Wm4::Vector2< Real >::operator!= (const Vector2< Real > & rkV) const
operator*()
template<class Real > Vector2 Wm4::Vector2< Real >::operator* (Real fScalar) const
operator*=()
template<class Real > Vector2& Wm4::Vector2< Real >::operator*= (Real fScalar)
operator+()
template<class Real > Vector2 Wm4::Vector2< Real >::operator+ (const Vector2< Real > & rkV) const
operator+=()
template<class Real > Vector2& Wm4::Vector2< Real >::operator+= (const Vector2< Real > & rkV)
operator-() [1/2]
template<class Real > Vector2 Wm4::Vector2< Real >::operator- () const
operator-() [2/2]
template<class Real > Vector2 Wm4::Vector2< Real >::operator- (const Vector2< Real > & rkV) const
operator-=()
template<class Real > Vector2& Wm4::Vector2< Real >::operator-= (const Vector2< Real > & rkV)
operator/()
template<class Real > Vector2 Wm4::Vector2< Real >::operator/ (Real fScalar) const
operator/=()
template<class Real > Vector2& Wm4::Vector2< Real >::operator/= (Real fScalar)
operator<()
template<class Real > bool Wm4::Vector2< Real >::operator< (const Vector2< Real > & rkV) const
operator<=()
template<class Real > bool Wm4::Vector2< Real >::operator<= (const Vector2< Real > & rkV) const
operator=()
template<class Real > Vector2& Wm4::Vector2< Real >::operator= (const Vector2< Real > & rkV)
operator==()
template<class Real > bool Wm4::Vector2< Real >::operator== (const Vector2< Real > & rkV) const
operator>()
template<class Real > bool Wm4::Vector2< Real >::operator> (const Vector2< Real > & rkV) const
operator>=()
template<class Real > bool Wm4::Vector2< Real >::operator>= (const Vector2< Real > & rkV) const
operator[]() [1/2]
template<class Real > Real& Wm4::Vector2< Real >::operator[] (int i)
operator[]() [2/2]
template<class Real > Real Wm4::Vector2< Real >::operator[] (int i) const
Orthonormalize()
template<class Real > static void Wm4::Vector2< Real >::Orthonormalize (Vector2< Real > & rkU, Vector2< Real > & rkV) static
Perp()
template<class Real > Vector2 Wm4::Vector2< Real >::Perp () const
Referenced by Wm4::ContMinBox().
SquaredLength()
template<class Real > Real Wm4::Vector2< Real >::SquaredLength () const
Referenced by Wm4::MeshCurvature< Real >::MeshCurvature().
UNIT_X() [1/2]
const Vector2< double > Wm4::Vector2< double >::UNIT_X (1. 0, 0. 0)
UNIT_X() [2/2]
const Vector2< float > Wm4::Vector2< float >::UNIT_X (1. 0f, 0. 0f)
UNIT_Y() [1/2]
const Vector2< double > Wm4::Vector2< double >::UNIT_Y (0. 0, 1. 0)
UNIT_Y() [2/2]
const Vector2< float > Wm4::Vector2< float >::UNIT_Y (0. 0f, 1. 0f)
UnitPerp()
template<class Real > Vector2 Wm4::Vector2< Real >::UnitPerp () const
X() [1/2]
template<class Real > Real& Wm4::Vector2< Real >::X ()
X() [2/2]
template<class Real > Real Wm4::Vector2< Real >::X () const
Referenced by Wm4::ContMinBox(), Wm4::IntrTriangle2Triangle2< Real >::Find(), Wm4::GaussPointsFit2(), Wm4::MeshCurvature< Real >::MeshCurvature(), and Wm4::IntrTriangle2Triangle2< Real >::Test().
Y() [1/2]
template<class Real > Real& Wm4::Vector2< Real >::Y ()
Y() [2/2]
template<class Real > Real Wm4::Vector2< Real >::Y () const
Referenced by Wm4::ContMinBox(), Wm4::IntrTriangle2Triangle2< Real >::Find(), Wm4::GaussPointsFit2(), Wm4::MeshCurvature< Real >::MeshCurvature(), and Wm4::IntrTriangle2Triangle2< Real >::Test().
ZERO() [1/2]
const Vector2< double > Wm4::Vector2< double >::ZERO (0. 0, 0. 0)
ZERO() [2/2]
const Vector2< float > Wm4::Vector2< float >::ZERO (0. 0f, 0. 0f)
Member Data Documentation
ONE
template<class Real > const Vector2 Wm4::Vector2< Real >::ONE static
Definition at line 107 of file Wm4Vector2.h.
UNIT_X
template<class Real > const Vector2 Wm4::Vector2< Real >::UNIT_X static
Definition at line 105 of file Wm4Vector2.h.
UNIT_Y
template<class Real > const Vector2 Wm4::Vector2< Real >::UNIT_Y static
Definition at line 106 of file Wm4Vector2.h.
ZERO
template<class Real > const Vector2 Wm4::Vector2< Real >::ZERO static
Definition at line 104 of file Wm4Vector2.h.
The documentation for this class was generated from the following files:
Wm4Vector2.h
frames.cpp