FreeCAD: Base::Debugger Class Reference
Base::Debugger Class Reference
#include <Debugger.h>
Public Slots
void quit ()
Public Member Functions
Debugger (QObject *parent=nullptr)
~Debugger () override
Debugger (const Debugger &)=delete
Debugger (Debugger &&)=delete
Debugger & operator= (const Debugger &)=delete
Debugger & operator= (Debugger &&)=delete
void attach ()
void detach ()
bool eventFilter (QObject *obj, QEvent *event) override
int exec ()
Detailed Description
This is a utility class to break the application at a point to inspect e.g. the result of an algorithm. You usually use it like this
...
Base::Debugger dbg;
dbg.attach();
dbg.exec();
...
Or you can connect it with a button and let the user click it in order to continue.
QPushButton* btn = new QPushButton();
btn->setText("Continue");
btn->show();
Base::Debugger dbg;
connect(btn, &QPushButton::clicked, &dbg, &Debugger::quit);
dbg.exec();
Author
Werner Mayer
Definition at line 77 of file Debugger.h.
Constructor & Destructor Documentation
Debugger() [1/3]
Debugger::Debugger (QObject * parent = nullptr) explicit
Definition at line 36 of file Debugger.cpp.
~Debugger()
Debugger::~Debugger () override default
Debugger() [2/3]
Base::Debugger::Debugger (const Debugger &) delete
Debugger() [3/3]
Base::Debugger::Debugger (Debugger &&) delete
Member Function Documentation
attach()
void Debugger::attach ()
Definition at line 42 of file Debugger.cpp.
Referenced by Path.Dressup.Gui.Boundary.DressupPathBoundaryViewProvider::__init__().
detach()
void Debugger::detach ()
Definition at line 48 of file Debugger.cpp.
eventFilter()
bool Debugger::eventFilter (QObject * obj, QEvent * event) override
Definition at line 54 of file Debugger.cpp.
exec()
int Debugger::exec ()
Definition at line 66 of file Debugger.cpp.
References Base::Console(), and Base::ConsoleSingleton::Message().
operator=() [1/2]
Debugger& Base::Debugger::operator= (const Debugger &) delete
operator=() [2/2]
Debugger& Base::Debugger::operator= (Debugger &&) delete
quit
void Debugger::quit () slot
Definition at line 74 of file Debugger.cpp.
The documentation for this class was generated from the following files:
Debugger.h
Debugger.cpp