FreeCAD: PartGui::FilletRadiusDelegate Class Reference
PartGui::FilletRadiusDelegate Class Reference
#include <DlgFilletEdges.h>
Public Member Functions
FilletRadiusDelegate (QObject *parent=nullptr)
QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &option, const QModelIndex &index) const override
void setEditorData (QWidget *editor, const QModelIndex &index) const override
void setModelData (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const override
void updateEditorGeometry (QWidget *editor, const QStyleOptionViewItem &option, const QModelIndex &index) const override
Detailed Description
Definition at line 47 of file DlgFilletEdges.h.
Constructor & Destructor Documentation
FilletRadiusDelegate()
FilletRadiusDelegate::FilletRadiusDelegate (QObject * parent = nullptr) explicit
Definition at line 78 of file DlgFilletEdges.cpp.
Member Function Documentation
createEditor()
QWidget * FilletRadiusDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & option, const QModelIndex & index) const override
Definition at line 82 of file DlgFilletEdges.cpp.
References Path.Post.Utils::editor(), Base::Unit::Length, and Init::parent.
setEditorData()
void FilletRadiusDelegate::setEditorData (QWidget * editor, const QModelIndex & index) const override
Definition at line 97 of file DlgFilletEdges.cpp.
References Path.Post.Utils::editor(), and Gui::QuantitySpinBox::setValue().
setModelData()
void FilletRadiusDelegate::setModelData (QWidget * editor, QAbstractItemModel * model, const QModelIndex & index) const override
Definition at line 105 of file DlgFilletEdges.cpp.
References Path.Post.Utils::editor(), and Gui::QuantitySpinBox::value.
updateEditorGeometry()
void FilletRadiusDelegate::updateEditorGeometry (QWidget * editor, const QStyleOptionViewItem & option, const QModelIndex & index) const override
Definition at line 118 of file DlgFilletEdges.cpp.
References Path.Post.Utils::editor().
The documentation for this class was generated from the following files:
DlgFilletEdges.h
DlgFilletEdges.cpp