FreeCAD: GCS::Arc Class Reference
GCS::Arc Class Reference
#include <Geo.h>
Public Member Functions
Arc ()
~Arc () override
int PushOwnParams (VEC_pD &pvec) override
void ReconstructOnNewPvec (VEC_pD &pvec, int &cnt) override
Arc * Copy () override
Public Member Functions inherited from GCS::Circle
Circle ()
~Circle () override
DeriVector2 CalculateNormal (const Point &p, const double *derivparam=nullptr) const override
DeriVector2 Value (double u, double du, const double *derivparam=nullptr) const override
Value: returns point (vector) given the value of parameter.
Public Member Functions inherited from GCS::Curve
virtual ~Curve ()
virtual DeriVector2 CalculateNormal (const double *param, const double *derivparam=nullptr) const
Public Attributes
double * startAngle
double * endAngle
Point start
Point end
Public Attributes inherited from GCS::Circle
Point center
double * rad
Detailed Description
Definition at line 252 of file Geo.h.
Constructor & Destructor Documentation
Arc()
GCS::Arc::Arc () inline
Definition at line 255 of file Geo.h.
References exportCSG::center().
Referenced by Copy().
~Arc()
GCS::Arc::~Arc () inline override
Definition at line 261 of file Geo.h.
Member Function Documentation
Copy()
Arc * GCS::Arc::Copy () override virtual
Reimplemented from GCS::Circle.
Definition at line 269 of file Geo.cpp.
References Arc().
PushOwnParams()
int GCS::Arc::PushOwnParams (VEC_pD & pvec) override virtual
Reimplemented from GCS::Circle.
Definition at line 235 of file Geo.cpp.
References end, endAngle, GCS::Circle::PushOwnParams(), start, startAngle, GCS::Point::x, and GCS::Point::y.
Referenced by GCS::ConstraintArcLength::ConstraintArcLength().
ReconstructOnNewPvec()
void GCS::Arc::ReconstructOnNewPvec (VEC_pD & pvec, int & cnt) override virtual
Reimplemented from GCS::Circle.
Definition at line 253 of file Geo.cpp.
References end, endAngle, GCS::Circle::ReconstructOnNewPvec(), start, startAngle, GCS::Point::x, and GCS::Point::y.
Member Data Documentation
end
Point GCS::Arc::end
Definition at line 268 of file Geo.h.
Referenced by PushOwnParams(), and ReconstructOnNewPvec().
endAngle
double* GCS::Arc::endAngle
Definition at line 264 of file Geo.h.
Referenced by PushOwnParams(), and ReconstructOnNewPvec().
start
Point GCS::Arc::start
Definition at line 267 of file Geo.h.
Referenced by PushOwnParams(), and ReconstructOnNewPvec().
startAngle
double* GCS::Arc::startAngle
Definition at line 263 of file Geo.h.
Referenced by PushOwnParams(), and ReconstructOnNewPvec().
The documentation for this class was generated from the following files:
Geo.h
Geo.cpp