FreeCAD: MeshCore::WriterOBJ Class Reference
MeshCore::WriterOBJ Class Reference
#include <WriterOBJ.h>
Classes
struct Color_Less
Public Member Functions
WriterOBJ (const MeshKernel &kernel, const Material *)
WriterOBJ.
void SetGroups (const std::vector< Group > &g)
Set the mesh groups for the OBJ export. A mesh group is a list of facet indices, i.e. a mesh segment. This function must be called before calling Save()
void SetTransform (const Base::Matrix4D &)
Apply a transformation for the exported mesh.
bool Save (std::ostream &)
Save the mesh to an OBJ file.
bool SaveMaterial (std::ostream &)
Save material file.
Detailed Description
Saves the mesh object into OBJ format.
Definition at line 54 of file WriterOBJ.h.
Constructor & Destructor Documentation
WriterOBJ()
WriterOBJ::WriterOBJ (const MeshKernel & kernel, const Material * material) explicit
WriterOBJ.
Definition at line 52 of file WriterOBJ.cpp.
Member Function Documentation
Save()
bool WriterOBJ::Save (std::ostream & out)
Save the mesh to an OBJ file.
Returns
true if the data could be written successfully, false otherwise.
Definition at line 70 of file WriterOBJ.cpp.
References SCL.SimpleDataTypes::b, MeshCore::Material::binding, SCL.SimpleDataTypes::c, importers.importIFCmulticore::colors, Base::Console(), MeshCore::MeshKernel::CountFacets(), MeshCore::MeshKernel::CountPoints(), MeshCore::Material::diffuseColor, MeshCore::MeshFacetIterator::End(), Base::Tools::escapedUnicodeFromUtf8(), SCL.SimpleDataTypes::f, DraftVecUtils::find(), toolbit-attributes::g, MeshCore::MeshKernel::GetFacets(), MeshCore::MeshKernel::GetPoints(), MeshCore::Material::library, Base::SequencerLauncher::next(), MeshCore::MeshIO::OVERALL, MeshCore::MeshIO::PER_FACE, MeshCore::MeshIO::PER_VERTEX, Base::Vector3< float_type >::Set(), Base::ConsoleSingleton::Warning(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by MeshCore::MeshOutput::SaveOBJ().
SaveMaterial()
bool WriterOBJ::SaveMaterial (std::ostream & out)
Save material file.
Returns
true on success and false otherwise.
Definition at line 257 of file WriterOBJ.cpp.
References MeshCore::Material::binding, MeshCore::Material::diffuseColor, SplineSurface::i, and MeshCore::MeshIO::PER_FACE.
Referenced by MeshCore::MeshOutput::SaveOBJ().
SetGroups()
void WriterOBJ::SetGroups (const std::vector< Group > & g)
Set the mesh groups for the OBJ export. A mesh group is a list of facet indices, i.e. a mesh segment. This function must be called before calling Save()
Parameters
g
Definition at line 57 of file WriterOBJ.cpp.
References toolbit-attributes::g.
Referenced by MeshCore::MeshOutput::SaveOBJ().
SetTransform()
void WriterOBJ::SetTransform (const Base::Matrix4D & mat)
Apply a transformation for the exported mesh.
Definition at line 62 of file WriterOBJ.cpp.
Referenced by MeshCore::MeshOutput::SaveOBJ().
The documentation for this class was generated from the following files:
WriterOBJ.h
WriterOBJ.cpp