FreeCAD: Gui::UiLoader Class Reference
Gui::UiLoader Class Reference
#include <UiLoader.h>
Public Member Functions
~UiLoader () override
QWidget * createWidget (const QString &className, QWidget *parent=nullptr, const QString &name=QString()) override
Static Public Member Functions
static std::unique_ptr< UiLoader > newInstance (QObject *parent=nullptr)
Protected Member Functions
UiLoader (QObject *parent=nullptr)
Detailed Description
The UiLoader class provides the abitlity to use the widget factory framework of FreeCAD within the framework provided by Qt. This class extends QUiLoader by the creation of FreeCAD specific widgets.
Author
Werner Mayer
Definition at line 108 of file UiLoader.h.
Constructor & Destructor Documentation
UiLoader()
UiLoader::UiLoader (QObject * parent = nullptr) explicit protected
A protected construct for UiLoader. To create an instance of UiLoader
See also
UiLoader::newInstance()
Definition at line 489 of file UiLoader.cpp.
~UiLoader()
UiLoader::~UiLoader () override default
Member Function Documentation
createWidget()
QWidget * UiLoader::createWidget (const QString & className, QWidget * parent = nullptr, const QString & name = QString()) override
Creates a widget of the type className with the parent parent. For more details see the documentation to QWidgetFactory.
Definition at line 510 of file UiLoader.cpp.
References Init::parent.
Referenced by Gui::UiLoaderPy::createWidget().
newInstance()
std::unique_ptr< UiLoader > UiLoader::newInstance (QObject * parent = nullptr) static
Creates a new instance of a UiLoader.
Due to its flaw the QUiLoader upon creation loads every available Qt designer plugin it can find in QApplication::libraryPaths(). Some of those plugins may perform some unexpected actions upon load which may interfere with FreeCAD's functionality. Only way to avoid such behaviour is to reset QApplication::libraryPaths, create a QUiLoader and then restore the libs paths. Hence need for this function to wrap construction.
See also
https://github.com/FreeCAD/FreeCAD/issues/8708
Definition at line 496 of file UiLoader.cpp.
References src.Mod.AddonManager.AddonManagerTest.gui.test_python_deps_gui::app, and Init::parent.
Referenced by Gui::PyResource::load(), Gui::Dialog::PreferenceUiForm::PreferenceUiForm(), and Gui::UiLoaderPy::UiLoaderPy().
The documentation for this class was generated from the following files:
UiLoader.h
UiLoader.cpp