FreeCAD: App::PropertyLink Class Reference
App::PropertyLink Class Reference
#include <PropertyLinks.h>
Public Member Functions
PropertyLink ()
~PropertyLink () override
void resetLink ()
virtual void setValue (App::DocumentObject *)
App::DocumentObject * getValue () const
App::DocumentObject * getValue (Base::Type t) const
template<typename _type >
_type getValue () const
PyObject * getPyObject () override
void setPyObject (PyObject *value) override
void Save (Base::Writer &writer) const override
void Restore (Base::XMLReader &reader) override
Property * Copy () const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
void Paste (const Property &from) override
Paste the value from the property (mainly for Undo/Redo and transactions)
unsigned int getMemSize () const override
const char * getEditorName () const override
Get the class name of the associated property editor item.
void getLinks (std::vector< App::DocumentObject * > &objs, bool all=false, std::vector< std::string > *subs=nullptr, bool newStyle=true) const override
void getLinksTo (std::vector< App::ObjectIdentifier > &identifiers, App::DocumentObject *obj, const char *subname=nullptr, bool all=false) const override
void breakLink (App::DocumentObject *obj, bool clear) override
bool adjustLink (const std::set< App::DocumentObject * > &inList) override
Property * CopyOnLinkReplace (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const override
Public Member Functions inherited from App::PropertyLinkBase
PropertyLinkBase ()
~PropertyLinkBase () override
virtual void updateElementReference (App::DocumentObject *feature, bool reverse=false, bool notify=false)
void unregisterElementReference ()
Clear internal element reference registration.
void registerLabelReferences (std::vector< std::string > &&labels, bool reset=true)
void checkLabelReferences (const std::vector< std::string > &subs, bool reset=true)
void unregisterLabelReferences ()
Clear internal label references registration.
virtual bool referenceChanged () const
Test if the element reference has changed after restore.
virtual int checkRestore (std::string *msg=nullptr) const
virtual Property * CopyOnImportExternal (const std::map< std::string, std::string > &nameMap) const
virtual Property * CopyOnLabelChange (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const
std::vector< App::DocumentObject * > linkedObjects (bool all=false) const
Helper function to return all linked objects of this property.
template<class T >
void getLinkedObjects (T &inserter, bool all=false) const
Helper function to return linked objects using an std::inserter.
void getLinkedElements (std::map< App::DocumentObject *, std::vector< std::string >> &elements, bool newStyle=true, bool all=false) const
Helper function to return a map of linked object and its subname references.
std::map< App::DocumentObject *, std::vector< std::string > > linkedElements (bool newStyle=true, bool all=false) const
Helper function to return a map of linked object and its subname references.
bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
void setAllowExternal (bool allow)
bool _updateElementReference (App::DocumentObject *feature, App::DocumentObject *obj, std::string &sub, ShadowSub &shadow, bool reverse, bool notify=false)
void _registerElementReference (App::DocumentObject *obj, std::string &sub, ShadowSub &shadow)
bool testFlag (int flag) const
virtual void setAllowPartial (bool enable)
void setReturnNewElement (bool enable)
void setSilentRestore (bool enable)
Public Member Functions inherited from App::Property
Property ()
~Property () override
const char * getName () const
bool hasName () const
std::string getFullName () const
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual void afterRestore ()
virtual void onContainerRestored ()
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
int64_t getID () const
virtual void beforeSave () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::ScopedLink
void setScope (LinkScope scope)
Set the links scope Allows to define what kind of links are allowed. Only in the Local GeoFeatureGroup, in this and all Childs or to all objects within the Glocal scope.
LinkScope getScope () const
Get the links scope Retrieve what kind of links are allowed. Only in the Local GeoFeatureGroup, in this and all Childs or to all objects within the Glocal scope.
Protected Attributes
App::DocumentObject * _pcLink {nullptr}
Protected Attributes inherited from App::PropertyLinkBase
std::bitset< 32 > _Flags
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::ScopedLink
LinkScope _pcScope = LinkScope::Local
Additional Inherited Members
Public Types inherited from App::PropertyLinkBase
enum LinkFlags {
LinkAllowExternal, LinkDetached, LinkRestoring, LinkAllowPartial,
LinkRestoreLabel, LinkSyncSubObject, LinkNewElement, LinkSilentRestore
}
using ShadowSub = ElementNamePair
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Static Public Member Functions inherited from App::PropertyLinkBase
static std::pair< App::DocumentObject *, std::string > tryReplaceLink (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const char *sub=nullptr)
Helper functions.
static std::pair< App::DocumentObject *, std::vector< std::string > > tryReplaceLinkSubs (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const std::vector< std::string > &subs)
static void updateElementReferences (DocumentObject *feature, bool reverse=false)
Update all element references in all link properties of feature.
static const std::unordered_set< PropertyLinkBase * > & getElementReferences (DocumentObject *)
Obtain link properties that contain element references to a given object.
static void breakLinks (App::DocumentObject *link, const std::vector< App::DocumentObject * > &objs, bool clear)
static std::string tryImportSubName (const App::DocumentObject *obj, const char *sub, const App::Document *doc, const std::map< std::string, std::string > &nameMap)
static App::DocumentObject * tryImport (const App::Document *doc, const App::DocumentObject *obj, const std::map< std::string, std::string > &nameMap)
static const char * exportSubName (std::string &output, const App::DocumentObject *obj, const char *subname, bool first_obj=false)
static std::string importSubName (Base::XMLReader &reader, const char *sub, bool &restoreLabel)
static void restoreLabelReference (const App::DocumentObject *obj, std::string &sub, ShadowSub *shadow=nullptr)
static void getLabelReferences (std::vector< std::string > &labels, const char *subname)
static std::vector< std::pair< Property *, std::unique_ptr< Property > > > updateLabelReferences (App::DocumentObject *obj, const char *newLabel)
static std::string updateLabelReference (const App::DocumentObject *linked, const char *subname, App::DocumentObject *obj, const std::string &ref, const char *newLabel)
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes inherited from App::PropertyLinkBase
boost::signals2::signal< void(const std::string &, const std::string &)> signalUpdateElementReference
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::PropertyLinkBase
void hasSetValue () override
Gets called by all setValue() methods after the value has changed.
void setFlag (int flag, bool value=true)
void _getLinksTo (std::vector< App::ObjectIdentifier > &identifiers, App::DocumentObject *obj, const char *subname, const std::vector< std::string > &subs, const std::vector< PropertyLinkBase::ShadowSub > &shadows) const
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue ()
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
The general Link Property Main Purpose of this property is to Link Objects and Features in a document. Like all links this property is scope aware, meaning it does define which objects are allowed to be linked depending of the GeoFeatureGroup where it is in. Default is Local.
Note
Links that are invalid in respect to the scope of this property is set to are not rejected. They are only detected to be invalid and prevent the feature from recomputing.
Definition at line 648 of file PropertyLinks.h.
Constructor & Destructor Documentation
PropertyLink()
PropertyLink::PropertyLink () default
A constructor. A more elaborate description of the constructor.
Referenced by Copy(), and CopyOnLinkReplace().
~PropertyLink()
PropertyLink::~PropertyLink () override
A destructor. A more elaborate description of the destructor.
Definition at line 681 of file PropertyLinks.cpp.
References resetLink().
Member Function Documentation
adjustLink()
bool PropertyLink::adjustLink (const std::set< App::DocumentObject * > & inList) override virtual
Called to adjust the link to avoid potential cyclic dependency
Parameters
inList recursive in-list of the would-be parent
Returns
Return whether the link has been adjusted
This function tries to correct the link to avoid any (sub)object inside in-list. If the adjustment is impossible, exception will be raised
Implements App::PropertyLinkBase.
Reimplemented in App::PropertyXLink.
Definition at line 860 of file PropertyLinks.cpp.
breakLink()
void PropertyLink::breakLink (App::DocumentObject * obj, bool clear) override virtual
Called to reset this link property
Parameters
obj reset link property if it is linked to this object
clear if true, then also reset property if the owner of this property is obj
See also
breakLinks()
Implements App::PropertyLinkBase.
Definition at line 853 of file PropertyLinks.cpp.
References _pcLink, Path.Op.Gui.Selection::clear(), App::Property::getContainer(), and setValue().
Copy()
Property * PropertyLink::Copy () const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Reimplemented in App::PropertyXLink.
Definition at line 811 of file PropertyLinks.cpp.
References _pcLink, buildPsets::p, and PropertyLink().
CopyOnLinkReplace()
Property * PropertyLink::CopyOnLinkReplace (const App::DocumentObject * parent, App::DocumentObject * oldObj, App::DocumentObject * newObj) const override virtual
Return a copy of the property if the link replacement affects this property
Parameters
owner the parent object whose link property is to be replace. Note that The parent may not be the container of this property. Link sub property can use this opportunity to adjust its relative links.
oldObj object to be replaced
newObj object to replace with
Returns
Return a copy of the property that is adjusted for the link replacement operation.
Implements App::PropertyLinkBase.
Reimplemented in App::PropertyXLink.
Definition at line 866 of file PropertyLinks.cpp.
References _pcLink, App::Property::getContainer(), buildPsets::p, Init::parent, PropertyLink(), and App::PropertyLinkBase::tryReplaceLink().
getEditorName()
const char* App::PropertyLink::getEditorName () const inline override virtual
Get the class name of the associated property editor item.
Reimplemented from App::Property.
Reimplemented in App::PropertyXLinkSub.
Definition at line 700 of file PropertyLinks.h.
getLinks()
void PropertyLink::getLinks (std::vector< App::DocumentObject * > & objs, bool all = false, std::vector< std::string > * subs = nullptr, bool newStyle = true) const override virtual
Obtain the linked objects
Parameters
objs hold the returned linked objects on output
all if true, then return all the linked object regardless of this LinkScope. If false, then return only if the LinkScope is not hidden.
sub if given, then return subname references.
newStyle whether to return new or old style subname reference
Implements App::PropertyLinkBase.
Reimplemented in App::PropertyXLink.
Definition at line 827 of file PropertyLinks.cpp.
References _pcLink, App::ScopedLink::_pcScope, App::Hidden, App::DocumentObject::isAttachedToDocument(), replaceobj::objs, and importers.importIFCmulticore::subs.
getLinksTo()
void PropertyLink::getLinksTo (std::vector< App::ObjectIdentifier > & identifiers, App::DocumentObject * obj, const char * subname = nullptr, bool all = false) const override virtual
Obtain identifiers from this link property that link to a given object
Parameters
identifiers holds the returned identifier to reference the given object
obj the referenced object
subname optional subname reference
all if true, then return all the references regardless of this LinkScope. If false, then return only if the LinkScope is not hidden.
Implements App::PropertyLinkBase.
Reimplemented in App::PropertyXLink.
Definition at line 839 of file PropertyLinks.cpp.
References _pcLink, App::ScopedLink::_pcScope, and App::Hidden.
getMemSize()
unsigned int App::PropertyLink::getMemSize () const inline override virtual
This method is used to get the size of objects It is not meant to have the exact size, it is more or less an estimation which runs fast! Is it two bytes or a GB? This method is defined in Base::Persistence
See also
Base::Persistence
Reimplemented from App::Property.
Definition at line 696 of file PropertyLinks.h.
getPyObject()
PyObject * PropertyLink::getPyObject () override virtual
This method returns the Python wrapper for a C++ object. It's in the responsibility of the programmer to do the correct reference counting. Basically there are two ways how to implement that: Either always return a new Python object then reference counting is not a matter or return always the same Python object then the reference counter must be incremented by one. However, it's absolutely forbidden to return always the same Python object without incrementing the reference counter.
The default implementation returns 'None'.
Reimplemented from Base::BaseClass.
Reimplemented in App::PropertyXLinkSub, and App::PropertyXLink.
Definition at line 747 of file PropertyLinks.cpp.
References _pcLink, App::DocumentObject::getPyObject(), and Py_Return.
getValue() [1/3]
App::DocumentObject * PropertyLink::getValue () const
This method returns the linked DocumentObject
Definition at line 737 of file PropertyLinks.cpp.
References _pcLink.
Referenced by App::Document::_removeObject(), FemGui::TaskDlgMeshShapeNetgen::accept(), TechDrawGui::QGSPage::addChildrenToPage(), Part::Extrusion::calculateShapeNormal(), PathGui::ViewProviderAreaView::claimChildren(), FemGui::ViewProviderFemPostPipeline::claimChildren(), TechDraw::DrawView::claimParent(), App::PropertyXLinkSubList::CopyOnLinkReplace(), FemGui::TaskCreateNodeSet::DefineNodes(), FemGui::TaskCreateElementSet::DefineNodes(), Part::Boolean::execute(), PartDesign::Body::execute(), TechDraw::DrawViewDetail::execute(), Part::Mirroring::execute(), Mesh::Curvature::execute(), Part::Offset::execute(), Part::Revolution::execute(), TechDraw::DrawViewSpreadsheet::execute(), Part::Offset2D::execute(), Drawing::FeatureViewSpreadsheet::execute(), Mesh::HarmonizeNormals::execute(), TechDraw::DrawViewDraft::execute(), Drawing::FeatureProjection::execute(), TechDraw::DrawViewArch::execute(), TechDraw::FeatureProjection::execute(), TechDraw::DrawProjGroup::execute(), Mesh::FlipNormals::execute(), PartDesign::Transformed::execute(), Mesh::FixNonManifolds::execute(), Mesh::FixDuplicatedFaces::execute(), Mesh::FixDuplicatedPoints::execute(), Mesh::FixDegenerations::execute(), Part::Refine::execute(), Part::Reverse::execute(), Mesh::FixDeformations::execute(), Mesh::FixIndices::execute(), Mesh::FillHoles::execute(), Inspection::Feature::execute(), Mesh::RemoveComponents::execute(), PartDesign::FeatureBase::FeatureBase(), TechDraw::DrawRichAnno::findParentPage(), TechDraw::DrawProjGroup::getAnchor(), TechDraw::DrawProjGroup::getAnchorDirection(), TechDrawGui::QGIProjGroup::getAnchorQItem(), TechDraw::DrawViewSection::getBaseDVP(), TechDraw::DrawLeaderLine::getBaseView(), TechDraw::DrawRichAnno::getBaseView(), TechDraw::DrawViewSection::getChangePointsFromSectionLine(), App::GeoFeature::getGlobalPlacement(), Assembly::AssemblyObject::getGroundedParts(), TechDrawGui::QGIWeldSymbol::getLeader(), Measure::ShapeFinder::getLinkAttachParent(), Assembly::AssemblyLink::getLinkedObject2(), PartDesign::Body::getNextSolidFeature(), TechDraw::DrawPage::getOrientation(), TechDraw::DrawPage::getPageHeight(), TechDraw::DrawPage::getPageOrientation(), TechDraw::DrawPage::getPageWidth(), TechDrawGui::PagePrinter::getPaperAttributes(), TechDraw::DrawTile::getParent(), TechDraw::DrawViewBalloon::getParentView(), PartDesign::Body::getPrevSolidFeature(), TechDraw::DrawViewSection::getShapeToCut(), TechDraw::DrawViewSpreadsheet::getSheetImage(), TechDrawGui::QGIViewBalloon::getSourceView(), TechDrawGui::QGSPage::getTemplateCenter(), TechDraw::DrawViewSection::getXDirection(), TechDraw::DrawView::handleChangedPropertyType(), TechDraw::DrawProjGroup::hasAnchor(), TechDraw::DrawPage::hasValidTemplate(), TechDraw::DrawViewSection::isBaseValid(), TechDraw::DrawWeldSymbol::isTailRightSide(), Fem::FemPostPipeline::load(), makeChamferOrFillet(), TechDraw::DrawViewDetail::mapPoint3dToDetail(), TechDrawGui::QGSPage::matchSceneRectToTemplate(), Part::Boolean::mustExecute(), Mesh::Curvature::mustExecute(), TechDraw::DrawView::onBeforeChange(), TechDraw::DrawWeldSymbol::onChanged(), PartDesign::DressUp::onChanged(), Fem::FemPostPipeline::onChanged(), TechDraw::DrawViewSection::onChanged(), PartDesign::Body::onChanged(), TechDraw::DrawView::onChanged(), PartGui::ViewProviderMirror::onDelete(), PartGui::ViewProviderBoolean::onDelete(), PathGui::ViewProviderAreaView::onDelete(), PartGui::ViewProviderFillet::onDelete(), PartDesignGui::ViewProvider::onDelete(), PartGui::ViewProviderChamfer::onDelete(), PartGui::ViewProviderRevolution::onDelete(), PartDesign::Body::onDocumentRestored(), PartDesignGui::TaskBooleanParameters::onSelectionChanged(), FemGui::TaskCreateNodeSet::onSelectionChanged(), FemGui::TaskCreateElementSet::onSelectionChanged(), PartDesign::DressUp::positionByBaseFeature(), TechDraw::DrawViewSection::postHlrTasks(), PartGui::OffsetWidget::reject(), PartDesignGui::TaskDlgBooleanParameters::reject(), PartDesignGui::TaskDlgFeatureParameters::reject(), PartDesignGui::relinkToBody(), PartDesign::Body::removeObject(), App::Document::removeObject(), App::Document::save(), TechDraw::DrawProjGroup::setAnchorDirection(), TechDrawGui::ViewProviderViewPart::setEdit(), TechDrawGui::TaskRichAnno::setUiEdit(), TechDrawGui::TaskLeaderLine::setUiEdit(), PartDesignGui::Workbench::setupContextMenu(), TechDrawGui::QGIViewBalloon::setViewPartFeature(), TechDrawGui::TaskComplexSection::TaskComplexSection(), FemGui::TaskCreateElementSet::TaskCreateElementSet(), FemGui::TaskCreateNodeSet::TaskCreateNodeSet(), TechDrawGui::TaskDetail::TaskDetail(), FemGui::TaskFemConstraintFluidBoundary::TaskFemConstraintFluidBoundary(), TechDrawGui::TaskLeaderLine::TaskLeaderLine(), TechDrawGui::TaskRichAnno::TaskRichAnno(), TechDrawGui::TaskSectionView::TaskSectionView(), TechDrawGui::TaskWeldingSymbol::TaskWeldingSymbol(), TechDraw::DrawViewDetail::unsetupObject(), TechDraw::DrawPage::unsetupObject(), RobotGui::ViewProviderRobotObject::updateData(), TechDrawGui::ViewProviderDrawingView::updateData(), PartDesignGui::ViewProviderBody::updateData(), PartGui::ViewProviderBoolean::updateData(), PartGui::ViewProviderFillet::updateData(), PartGui::ViewProviderChamfer::updateData(), FemGui::ViewProviderFemPostPipeline::updateFunctionSize(), TechDrawGui::QGSPage::updateTemplate(), and App::PropertyLinkSubList::upgrade().
getValue() [2/3]
template<typename _type > _type App::PropertyLink::getValue () const inline
Returns the link type checked
Definition at line 682 of file PropertyLinks.h.
getValue() [3/3]
App::DocumentObject * PropertyLink::getValue (Base::Type t) const
Returns the link type checked
Definition at line 742 of file PropertyLinks.cpp.
References _pcLink, Base::Persistence::getTypeId(), Base::Type::isDerivedFrom(), and InitGui::t.
Paste()
void PropertyLink::Paste (const Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Reimplemented in App::PropertyXLink.
Definition at line 818 of file PropertyLinks.cpp.
References _pcLink, Base::Persistence::getClassTypeId(), Base::BaseClass::isDerivedFrom(), and setValue().
resetLink()
void PropertyLink::resetLink ()
Definition at line 689 of file PropertyLinks.cpp.
References _pcLink, App::ScopedLink::_pcScope, App::DocumentObject::_removeBackLink(), App::Destroy, Base::Persistence::getClassTypeId(), App::Property::getContainer(), App::Hidden, Base::BaseClass::isDerivedFrom(), and Init::parent.
Referenced by App::PropertyXLink::detach(), App::PropertyXLink::unlink(), and ~PropertyLink().
Restore()
void PropertyLink::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Reimplemented in App::PropertyXLink.
Definition at line 775 of file PropertyLinks.cpp.
References Base::Console(), App::Property::getContainer(), App::Document::getObject(), Init::parent, TechDrawTools.TaskFillTemplateFields::reader, setValue(), and Base::ConsoleSingleton::Warning().
Referenced by TechDraw::DrawViewBalloon::handleChangedPropertyName(), TechDraw::DrawView::handleChangedPropertyType(), App::PropertyLinkSubList::upgrade(), and App::PropertyXLink::upgrade().
Save()
void PropertyLink::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Reimplemented in App::PropertyXLink.
Definition at line 769 of file PropertyLinks.cpp.
References _pcLink, App::DocumentObject::getExportName(), Base::Writer::ind(), and Base::Writer::Stream().
setPyObject()
void PropertyLink::setPyObject (PyObject * value) override virtual
Reimplemented from Base::BaseClass.
Reimplemented in App::PropertyXLink.
Definition at line 757 of file PropertyLinks.cpp.
References Base::PyTypeCheck(), and setValue().
setValue()
void PropertyLink::setValue (App::DocumentObject * lValue) virtual
Sets the property
Reimplemented in App::PropertyXLink.
Definition at line 709 of file PropertyLinks.cpp.
References App::DocumentObject::_addBackLink(), _pcLink, App::ScopedLink::_pcScope, App::DocumentObject::_removeBackLink(), App::Property::aboutToSetValue(), App::Destroy, App::Property::getContainer(), App::DocumentObject::getDocument(), App::PropertyLinkBase::hasSetValue(), App::Hidden, App::PropertyLinkBase::LinkAllowExternal, Init::parent, and App::PropertyLinkBase::testFlag().
Referenced by App::Document::_removeObject(), TechDrawGui::TaskSurfaceFinishSymbols::accept(), PartDesign::Body::addObject(), TechDraw::DrawProjGroup::addProjection(), breakLink(), PathGui::ViewProviderAreaView::dragObject(), PathGui::ViewProviderAreaView::dropObject(), PartDesign::DressUp::onChanged(), Fem::FemPostPipeline::onChanged(), PartDesign::Body::onChanged(), TechDraw::DrawWeldSymbol::onSettingDocument(), Paste(), PartDesign::Body::removeObject(), App::Document::removeObject(), App::Document::Restore(), Restore(), PartDesign::Body::setBaseProperty(), setPyObject(), App::LinkBaseExtension::setupCopyOnChange(), TechDrawGui::TaskProjGroup::turnViewToProjGroup(), TechDraw::DrawProjGroupItem::unsetupObject(), TechDraw::DrawPage::unsetupObject(), and PartGui::DlgExtrusion::validate().
Member Data Documentation
_pcLink
App::DocumentObject* App::PropertyLink::_pcLink {nullptr} protected
Definition at line 724 of file PropertyLinks.h.
Referenced by App::PropertyXLink::adjustLink(), App::PropertyXLink::afterRestore(), breakLink(), App::PropertyXLink::checkRestore(), Copy(), App::PropertyXLink::CopyOnImportExternal(), App::PropertyXLink::CopyOnLabelChange(), CopyOnLinkReplace(), App::PropertyXLink::CopyOnLinkReplace(), App::PropertyXLink::copyTo(), App::PropertyXLink::detach(), getLinks(), App::PropertyXLink::getLinks(), getLinksTo(), App::PropertyXLink::getLinksTo(), getPyObject(), App::PropertyXLink::getPyObject(), App::PropertyXLinkSub::getPyObject(), getValue(), App::PropertyXLink::onContainerRestored(), Paste(), resetLink(), App::PropertyXLink::restoreLink(), Save(), App::PropertyXLink::Save(), App::PropertyXLink::setAllowPartial(), setValue(), and App::PropertyXLink::updateElementReference().
The documentation for this class was generated from the following files:
PropertyLinks.h
PropertyLinks.cpp