FreeCAD: zipios::ZipHeader Class Reference
zipios::ZipHeader Class Reference
#include <ZipHeader.h>
Public Member Functions
ZipHeader (std::istream &inp, int s_off=0, int e_off=0)
FileCollection * clone () const override
void close () override
std::istream * getInputStream (const ConstEntryPointer &entry) override
std::istream * getInputStream (const string &entry_name, MatchPath matchpath=MATCH) override
Detailed Description
ZipHeader is a FileCollection, where the files are stored in a .zip file. The class is similar to zipios' ZipFile class with the difference that instead of a file a std::istream can be passed.
Definition at line 58 of file ZipHeader.h.
Constructor & Destructor Documentation
ZipHeader()
ZipHeader::ZipHeader (std::istream & inp, int s_off = 0, int e_off = 0) explicit
Opens the zip file name. If the zip "file" is embedded in a file that contains other data, e.g. a binary program, the offset of the zip file start and end must be specified.
Parameters
inp The input stream of the zip file to open.
s_off Offset relative to the start of the file, that indicates the beginning of the zip file.
e_off Offset relative to the end of the file, that indicates the end of the zip file. The offset is a positive number, even though the offset is towards the beginning of the file.
Exceptions
FColException Thrown if the specified file name is not a valid zip archive.
IOException Thrown if an I/O problem is encountered, while the directory of the specified zip archive is being read.
Definition at line 34 of file ZipHeader.cpp.
Referenced by clone().
Member Function Documentation
clone()
FileCollection * ZipHeader::clone () const override
Create a copy of this instance.
Definition at line 42 of file ZipHeader.cpp.
References ZipHeader().
Referenced by ArchPrecast._Precast::execute(), ArchFrame._Frame::execute(), ArchPrecast._PrecastBeam::execute(), ArchPanel._Panel::execute(), ArchPipe._ArchPipe::execute(), ArchTruss.Truss::execute(), ArchCurtainWall.CurtainWall::execute(), ArchRebar._Rebar::execute(), ArchEquipment._Equipment::execute(), ArchPrecast._PrecastIbeam::execute(), ArchComponent.Component::execute(), ArchSpace._Space::execute(), ArchStairs._Stairs::execute(), ArchPipe._ArchPipeConnector::execute(), ArchPrecast._PrecastPillar::execute(), ArchWall._Wall::execute(), ArchWindow._Window::execute(), ArchPrecast._PrecastPanel::execute(), ArchPrecast._PrecastSlab::execute(), ArchRoof._Roof::execute(), ArchPrecast._PrecastStairs::execute(), ArchStructure._Structure::execute(), src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::integrated(), src.Mod.AddonManager.addonmanager_git.GitManager::repair(), and src.Mod.AddonManager.addonmanager_git.GitManager::update().
close()
void ZipHeader::close () override
Definition at line 47 of file ZipHeader.cpp.
Referenced by femsolver.reportdialog.ReportDialog::__init__(), TechDrawTools.TaskFillTemplateFields.TaskFillTemplateFields::proceed(), and femexamples.examplesgui.FemExamples::reject().
getInputStream() [1/2]
std::istream * ZipHeader::getInputStream (const ConstEntryPointer & entry) override
Definition at line 52 of file ZipHeader.cpp.
getInputStream() [2/2]
std::istream* zipios::ZipHeader::getInputStream (const string & entry_name, MatchPath matchpath = MATCH) override
The documentation for this class was generated from the following files:
ZipHeader.h
ZipHeader.cpp