FreeCAD: Gui::FileIconProvider Class Reference
Gui::FileIconProvider Class Reference
#include <FileDialog.h>
Public Member Functions
FileIconProvider ()
~FileIconProvider () override
QIcon icon (IconType type) const override
QIcon icon (const QFileInfo &info) const override
QString type (const QFileInfo &info) const override
Detailed Description
The FileIconProvider class provides icons for FileDialog to use.
Author
Werner Mayer
Definition at line 136 of file FileDialog.h.
Constructor & Destructor Documentation
FileIconProvider()
FileIconProvider::FileIconProvider () default
Constructs an empty file icon provider called name, with the parent parent.
~FileIconProvider()
FileIconProvider::~FileIconProvider () override default
Member Function Documentation
icon() [1/2]
QIcon FileIconProvider::icon (const QFileInfo & info) const override
Definition at line 604 of file FileDialog.cpp.
References icon(), Path.Log::info(), geoff_geometry::Normal(), geoff_geometry::On(), and src.Mod.PartDesign.fcgear.svggear::w.
icon() [2/2]
QIcon FileIconProvider::icon (IconType type) const override
Definition at line 599 of file FileDialog.cpp.
References type().
Referenced by icon().
type()
QString FileIconProvider::type (const QFileInfo & info) const override
Definition at line 650 of file FileDialog.cpp.
References Path.Log::info(), and Path.Post.scripts.grbl_post::type.
Referenced by icon().
The documentation for this class was generated from the following files:
FileDialog.h
FileDialog.cpp