FreeCAD: Gui::SoShapeScale Class Reference
Gui::SoShapeScale Class Reference
#include <SoAxisCrossKit.h>
Public Member Functions
SoShapeScale ()
Static Public Member Functions
static void initClass ()
Public Attributes
SoSFFloat active
SoSFFloat scaleFactor
Protected Member Functions
void GLRender (SoGLRenderAction *action) override
~SoShapeScale () override
Detailed Description
Definition at line 41 of file SoAxisCrossKit.h.
Constructor & Destructor Documentation
SoShapeScale()
SoShapeScale::SoShapeScale ()
Definition at line 61 of file SoAxisCrossKit.cpp.
References SCL.SimpleDataTypes::f.
~SoShapeScale()
SoShapeScale::~SoShapeScale () override protected default
Member Function Documentation
GLRender()
void SoShapeScale::GLRender (SoGLRenderAction * action) override protected
Definition at line 85 of file SoAxisCrossKit.cpp.
References Path.Post.scripts.dynapath_4060_post::action, active, exportCSG::center(), SCL.SimpleDataTypes::f, SoDevicePixelRatioElement::get(), scaleFactor, and TestSpreadsheet::v.
initClass()
void SoShapeScale::initClass () static
Definition at line 79 of file SoAxisCrossKit.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
Member Data Documentation
active
SoSFFloat Gui::SoShapeScale::active
Definition at line 54 of file SoAxisCrossKit.h.
Referenced by draftguitools.gui_texts.Text::action(), GLRender(), and PathCommands._CommandSelectLoop::IsActive().
scaleFactor
SoSFFloat Gui::SoShapeScale::scaleFactor
Definition at line 55 of file SoAxisCrossKit.h.
Referenced by GLRender(), SoSwitchMarker.SoSwitchMarker::line_sep(), SoSwitchMarker.SoSwitchMarker::plane_sep(), Gui::ViewProviderDatum::resetTemporarySize(), Gui::View3DInventorViewer::setAxisCross(), and Gui::ViewProviderDatum::setTemporaryScale().
The documentation for this class was generated from the following files:
SoAxisCrossKit.h
SoAxisCrossKit.cpp