FreeCAD: Gui::Dialog::PropertyPage Class Reference
Gui::Dialog::PropertyPage Class Reference abstract
#include <PropertyPage.h>
Public Member Functions
PropertyPage (QWidget *parent=nullptr)
~PropertyPage () override=default
bool isModified () const
void setModified (bool b)
void onApply ()
void onCancel ()
void onReset ()
Protected Slots
virtual void loadSettings ()=0
virtual void saveSettings ()=0
Protected Member Functions
virtual void apply ()
virtual void cancel ()
virtual void reset ()
Detailed Description
Base class for property pages.
Author
Werner Mayer
Definition at line 78 of file PropertyPage.h.
Constructor & Destructor Documentation
PropertyPage()
PropertyPage::PropertyPage (QWidget * parent = nullptr) explicit
Construction
Definition at line 41 of file PropertyPage.cpp.
~PropertyPage()
Gui::Dialog::PropertyPage::~PropertyPage () override default
Member Function Documentation
apply()
void PropertyPage::apply () protected virtual
Applies all changes. Reimplement this in your subclasses.
Definition at line 48 of file PropertyPage.cpp.
Referenced by onApply().
cancel()
void PropertyPage::cancel () protected virtual
Discards all changes. Reimplement this in your subclasses.
Definition at line 53 of file PropertyPage.cpp.
Referenced by onCancel().
isModified()
bool PropertyPage::isModified () const
Returns whether the page was modified or not.
Definition at line 63 of file PropertyPage.cpp.
Referenced by onApply(), and onCancel().
loadSettings
virtual void Gui::Dialog::PropertyPage::loadSettings () protected pure virtual slot
onApply()
void PropertyPage::onApply ()
Applies all changes calling apply() and resets the modified state.
Definition at line 75 of file PropertyPage.cpp.
References apply(), isModified(), and setModified().
onCancel()
void PropertyPage::onCancel ()
Discards all changes calling cancel() and resets the modified state.
Definition at line 85 of file PropertyPage.cpp.
References cancel(), isModified(), and setModified().
onReset()
void PropertyPage::onReset ()
Resets to the default values.
Definition at line 94 of file PropertyPage.cpp.
References reset().
reset()
void PropertyPage::reset () protected virtual
Resets to the default values. Reimplement this in your subclasses.
Definition at line 58 of file PropertyPage.cpp.
Referenced by ArchVRM.Renderer::__init__(), onReset(), draftguitools.gui_trackers.gridTracker::set(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testAll(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testBuildings(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCommonPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testCustom(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testExtrusions(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testHierarchy(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testIFC4(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testMaterials(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testPsets(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testQuantities(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testRectangleProfileDef(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSites(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testSolid(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandardCases(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStandards(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testStoreys(), bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testTinyLines(), and bimcommands.BimPreflight.BIM_Preflight_TaskPanel::testUndefined().
saveSettings
virtual void Gui::Dialog::PropertyPage::saveSettings () protected pure virtual slot
setModified()
void PropertyPage::setModified (bool value)
Sets the page to be modified.
Definition at line 69 of file PropertyPage.cpp.
Referenced by onApply(), and onCancel().
The documentation for this class was generated from the following files:
PropertyPage.h
PropertyPage.cpp