FreeCAD: InspectionGui::VisualInspection Class Reference
InspectionGui::VisualInspection Class Reference
#include <VisualInspection.h>
Public Member Functions
VisualInspection (QWidget *parent=nullptr, Qt::WindowFlags fl=Qt::WindowFlags())
~VisualInspection () override
void accept () override
Protected Slots
void onActivateItem (QTreeWidgetItem *)
void loadSettings ()
void saveSettings ()
Detailed Description
Definition at line 35 of file VisualInspection.h.
Constructor & Destructor Documentation
VisualInspection()
VisualInspection::VisualInspection (QWidget * parent = nullptr, Qt::WindowFlags fl = Qt::WindowFlags()) explicit
Constructs a VisualInspection as a child of 'parent', with the name 'name' and widget flags set to 'f'.
Definition at line 81 of file VisualInspection.cpp.
References draftgeoutils.intersections::connect(), toolbit-attributes::doc, Base::Type::fromName(), App::Application::getActiveDocument(), App::GetApplication(), Gui::Application::getDocument(), Gui::ViewProvider::getIcon(), Gui::getMainWindow(), Draft::gui, Gui::Application::Instance, Base::Unit::Length, loadSettings(), Mesh2Shape::mesh, onActivateItem(), InspectionGui::SingleSelectionItem::setCompetitiveItem(), and Gui::MainWindow::whatsThis().
~VisualInspection()
VisualInspection::~VisualInspection () override
Definition at line 152 of file VisualInspection.cpp.
Member Function Documentation
accept()
void VisualInspection::accept () override
Definition at line 216 of file VisualInspection.cpp.
References Gui::Application::activeDocument(), Gui::Command::App, toolbit-attributes::doc, doCommand, Gui::Application::Instance, onActivateItem(), Arch::QT_TRANSLATE_NOOP, runCommand, and saveSettings().
Referenced by MaterialEditor.MaterialEditor::verify().
loadSettings
void VisualInspection::loadSettings () protected slot
Definition at line 158 of file VisualInspection.cpp.
References App::GetApplication(), ParameterGrp::GetFloat(), and App::Application::GetParameterGroupByPath().
Referenced by VisualInspection().
onActivateItem
void VisualInspection::onActivateItem (QTreeWidgetItem * item) protected slot
Definition at line 183 of file VisualInspection.cpp.
References InspectionGui::SingleSelectionItem::getCompetitiveItem().
Referenced by accept(), and VisualInspection().
saveSettings
void VisualInspection::saveSettings () protected slot
Definition at line 172 of file VisualInspection.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetFloat().
Referenced by accept().
The documentation for this class was generated from the following files:
VisualInspection.h
VisualInspection.cpp