FreeCAD: Base::FileWriter Class Reference
Base::FileWriter Class Reference
#include <Writer.h>
Public Member Functions
FileWriter (const char *DirName)
~FileWriter () override
void putNextEntry (const char *filename, const char *objName=nullptr) override
put the next entry with a give name
void writeFiles () override
process the requested file storing
std::ostream & Stream () override
void close ()
virtual bool shouldWrite (const std::string &name, const Base::Persistence *Object) const
FileWriter (const FileWriter &)=delete
FileWriter (FileWriter &&)=delete
FileWriter & operator= (const FileWriter &)=delete
FileWriter & operator= (FileWriter &&)=delete
Public Member Functions inherited from Base::Writer
Writer ()
virtual ~Writer ()
void setForceXML (bool on)
switch the writer in XML only mode (no files allowed)
bool isForceXML () const
check on state
void setFileVersion (int)
int getFileVersion () const
void insertAsciiFile (const char *FileName)
insert a file as CDATA section in the XML file
void insertBinFile (const char *FileName)
insert a binary file BASE64 coded as CDATA section in the XML file
void insertText (const std::string &str)
insert text string as CDATA
std::string addFile (const char *Name, const Base::Persistence *Object)
add a write request of a persistent object
const std::vector< std::string > & getFilenames () const
get all registered file names
void setMode (const std::string &mode)
Set mode.
void setModes (const std::set< std::string > &modes)
Set modes.
bool getMode (const std::string &mode) const
Get mode.
std::set< std::string > getModes () const
Get modes.
void clearMode (const std::string &mode)
Clear mode.
void clearModes ()
Clear modes.
void addError (const std::string &)
bool hasErrors () const
void clearErrors ()
std::vector< std::string > getErrors () const
const char * ind () const
get the current indentation
void incInd ()
increase indentation by one tab
void decInd ()
decrease indentation by one tab
std::ostream & beginCharStream (CharStreamFormat format=CharStreamFormat::Raw)
std::ostream & endCharStream ()
std::ostream & charStream ()
Return the current character output stream.
Writer (const Writer &)=delete
Writer (Writer &&)=delete
Writer & operator= (const Writer &)=delete
Writer & operator= (Writer &&)=delete
Protected Attributes
std::string DirName
std::ofstream FileStream
Protected Attributes inherited from Base::Writer
std::vector< FileEntry > FileList
std::vector< std::string > FileNames
std::vector< std::string > Errors
std::set< std::string > Modes
short indent {0}
char indBuf [1024] {}
bool forceXML {false}
int fileVersion {1}
Additional Inherited Members
Public Attributes inherited from Base::Writer
std::string ObjectName
name for underlying file saves
Protected Member Functions inherited from Base::Writer
std::string getUniqueFileName (const char *Name)
Detailed Description
The FileWriter class This class writes out the data into files into a given directory name.
See also
Base::Persistence
Author
Werner Mayer
Definition at line 273 of file Writer.h.
Constructor & Destructor Documentation
FileWriter() [1/3]
FileWriter::FileWriter (const char * DirName) explicit
Definition at line 383 of file Writer.cpp.
~FileWriter()
FileWriter::~FileWriter () override default
FileWriter() [2/3]
Base::FileWriter::FileWriter (const FileWriter &) delete
FileWriter() [3/3]
Base::FileWriter::FileWriter (FileWriter &&) delete
Member Function Documentation
close()
void Base::FileWriter::close () inline
Definition at line 286 of file Writer.h.
Referenced by femsolver.reportdialog.ReportDialog::__init__(), TechDrawTools.TaskFillTemplateFields.TaskFillTemplateFields::proceed(), femexamples.examplesgui.FemExamples::reject(), and Gui::RecoveryRunnable::run().
operator=() [1/2]
FileWriter& Base::FileWriter::operator= (const FileWriter &) delete
operator=() [2/2]
FileWriter& Base::FileWriter::operator= (FileWriter &&) delete
putNextEntry()
void FileWriter::putNextEntry (const char * filename, const char * objName = nullptr) override virtual
put the next entry with a give name
Reimplemented from Base::Writer.
Definition at line 389 of file Writer.cpp.
References DirName, DrawingExample::file, FileStream, and Base::Writer::putNextEntry().
Referenced by Gui::RecoveryRunnable::RecoveryRunnable(), Gui::AutoSaver::saveDocument(), and writeFiles().
shouldWrite()
bool FileWriter::shouldWrite (const std::string & name, const Base::Persistence * Object) const virtual
This method can be re-implemented in sub-classes to avoid to write out certain objects. The default implementation always returns true.
Reimplemented in Gui::RecoveryWriter.
Definition at line 397 of file Writer.cpp.
Referenced by writeFiles().
Stream()
std::ostream& Base::FileWriter::Stream () inline override virtual
Implements Base::Writer.
Definition at line 282 of file Writer.h.
writeFiles()
void FileWriter::writeFiles () override virtual
process the requested file storing
Implements Base::Writer.
Definition at line 402 of file Writer.cpp.
References Base::FileInfo::createDirectory(), DirName, Base::Writer::FileList, Base::Writer::FileEntry::FileName, Path.Preferences::filePath(), FileStream, Base::Writer::indBuf, Base::Writer::indent, Base::Writer::FileEntry::Object, RobotExample::pos, putNextEntry(), Base::Persistence::SaveDocFile(), and shouldWrite().
Member Data Documentation
DirName
std::string Base::FileWriter::DirName protected
Definition at line 304 of file Writer.h.
Referenced by putNextEntry(), Gui::RecoveryWriter::writeFiles(), and writeFiles().
FileStream
std::ofstream Base::FileWriter::FileStream protected
Definition at line 305 of file Writer.h.
Referenced by putNextEntry(), Gui::RecoveryWriter::writeFiles(), and writeFiles().
The documentation for this class was generated from the following files:
Writer.h
Writer.cpp