FreeCAD: Idf Namespace Reference
Idf Namespace Reference
Functions
def open (filename)
End config section do not touch code below #.
def insert (filename, docname)
def process_emn (doc, filename)
def Process_board_outline (doc, board_outline, drills, board_thickness)
def mid_point (prev_vertex, vertex, angle)
def split_records (line_record)
def process_emp (doc, filename, placement, board_thickness)
def Process_comp_outline (doc, comp_outline, comp_height)
def place_steps (doc, placement, board_thickness)
def toQuaternion (heading, attitude, bank)
def Per_point (prev_vertex, vertex)
Variables
model_tab_filename
Script version dated 19-Jan-2012 #.
step_path
path to directory containing step models
ignore_hole_size
EmpDisplayMode
IDF_sort
IDF_diag
IDF_diag_path
Function Documentation
insert()
def Idf.insert (filename, docname)
called when freecad imports an Emn file
Definition at line 65 of file Idf.py.
References process_emn().
mid_point()
def Idf.mid_point (prev_vertex, vertex, angle)
mid_point(prev_vertex,vertex,angle)-> mid_vertex
   returns mid point on arc of angle between prev_vertex and vertex
Definition at line 191 of file Idf.py.
References KDL.atan2(), KDL.cos(), KDL.hypot(), and KDL.sin().
Referenced by CArc.AlmostALine(), CArea.InsideCurves(), Process_board_outline(), and Process_comp_outline().
open()
def Idf.open (filename)
End config section do not touch code below #.
called when freecad opens an Emn file
Definition at line 57 of file Idf.py.
References process_emn().
Per_point()
def Idf.Per_point (prev_vertex, vertex)
Per_point(center,vertex)->per point
   returns opposite perimeter point of circle
Definition at line 400 of file Idf.py.
Referenced by Process_board_outline(), and Process_comp_outline().
place_steps()
def Idf.place_steps (doc, placement, board_thickness)
place_steps(doc,placement,board_thickness)->place step models on board
    list of models and path to step files is set at start of this script
             model_tab_filename= "" &   step_path=""
Definition at line 326 of file Idf.py.
References Path.Base.SetupSheet.dict, split_records(), Path.Post.scripts.refactored_centroid_post.str, and toQuaternion().
Referenced by process_emn().
Process_board_outline()
def Idf.Process_board_outline (doc, board_outline, drills, board_thickness)
Process_board_outline(doc,board_outline,drills,board_thickness)-> number processed loops
    adds emn geometry from emn file
Definition at line 132 of file Idf.py.
References mid_point(), Per_point(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by process_emn().
Process_comp_outline()
def Idf.Process_comp_outline (doc, comp_outline, comp_height)
Process_comp_outline(doc,comp_outline,comp_height)->part shape
   Create solid component shape base on its outline
Definition at line 297 of file Idf.py.
References mid_point(), Per_point(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by process_emp().
process_emn()
def Idf.process_emn (doc, filename)
process_emn(document, filename)-> adds emn geometry from emn file
Definition at line 72 of file Idf.py.
References Base.fmod(), place_steps(), Process_board_outline(), process_emp(), split_records(), and Path.Post.scripts.refactored_centroid_post.str.
Referenced by insert(), and open().
process_emp()
def Idf.process_emp (doc, filename, placement, board_thickness)
process_emp(doc,filename,placement,board_thickness) -> place components from emn file to board
Definition at line 224 of file Idf.py.
References Path.Base.SetupSheet.dict, Process_comp_outline(), split_records(), Path.Post.scripts.refactored_centroid_post.str, and toQuaternion().
Referenced by process_emn().
split_records()
def Idf.split_records (line_record)
split_records(line_record)-> list of strings(records)
   standard separator list separator is space, records containing encapsulated by "
Definition at line 201 of file Idf.py.
Referenced by place_steps(), process_emn(), and process_emp().
toQuaternion()
def Idf.toQuaternion (heading, attitude, bank)
toQuaternion(heading, attitude,bank)->FreeCAD.Base.Rotation(Quternion)
Definition at line 384 of file Idf.py.
References KDL.cos(), and KDL.sin().
Referenced by place_steps(), and process_emp().
Variable Documentation
EmpDisplayMode
Idf.EmpDisplayMode
Definition at line 45 of file Idf.py.
IDF_diag
Idf.IDF_diag
Definition at line 49 of file Idf.py.
IDF_diag_path
Idf.IDF_diag_path
Definition at line 50 of file Idf.py.
IDF_sort
Idf.IDF_sort
Definition at line 47 of file Idf.py.
ignore_hole_size
Idf.ignore_hole_size
Definition at line 44 of file Idf.py.
model_tab_filename
Idf.model_tab_filename
Script version dated 19-Jan-2012 #.
Configuration parameters below - use standard slashes / # path to table file (simple comma separated values)
Definition at line 38 of file Idf.py.
step_path
Idf.step_path
path to directory containing step models
Definition at line 42 of file Idf.py.