FreeCAD: PartGui::TaskCheckGeometryResults Class Reference
PartGui::TaskCheckGeometryResults Class Reference
#include <TaskCheckGeometry.h>
Public Member Functions
TaskCheckGeometryResults (QWidget *parent=nullptr)
~TaskCheckGeometryResults () override
QString getShapeContentString ()
void goCheck ()
Detailed Description
Definition at line 102 of file TaskCheckGeometry.h.
Constructor & Destructor Documentation
TaskCheckGeometryResults()
TaskCheckGeometryResults::TaskCheckGeometryResults (QWidget * parent = nullptr) explicit
Definition at line 373 of file TaskCheckGeometry.cpp.
~TaskCheckGeometryResults()
TaskCheckGeometryResults::~TaskCheckGeometryResults () override
Definition at line 380 of file TaskCheckGeometry.cpp.
References Gui::SelectionSingleton::clearSelection(), SCL.SimpleDataTypes::e, and Gui::Selection().
Member Function Documentation
getShapeContentString()
QString TaskCheckGeometryResults::getShapeContentString ()
Definition at line 702 of file TaskCheckGeometry.cpp.
Referenced by PartGui::TaskCheckGeometryDialog::TaskCheckGeometryDialog().
goCheck()
void TaskCheckGeometryResults::goCheck ()
Definition at line 413 of file TaskCheckGeometry.cpp.
References PartGui::ResultEntry::children, PartGui::ResultEntry::error, App::GetApplication(), ParameterGrp::GetGroup(), Gui::getMainWindow(), Gui::ViewProvider::getRoot(), Gui::SelectionSingleton::getSelection(), Part::Feature::getShape(), App::Application::GetUserParameter(), Gui::Application::getViewProvider(), PartGui::goSetupResultBoundingBox(), toolbit-attributes::group, Handle(), Gui::Application::Instance, PartGui::ResultEntry::name, PartGui::ResultEntry::parent, Path.Dressup.Utils::selection(), Gui::Selection(), PartGui::ResultModel::setResults(), PartGui::ResultEntry::shape, shapeEnumToString(), PartGui::ResultEntry::type, and PartGui::ResultEntry::viewProviderRoot.
Referenced by PartGui::TaskCheckGeometryDialog::TaskCheckGeometryDialog().
The documentation for this class was generated from the following files:
TaskCheckGeometry.h
TaskCheckGeometry.cpp