FreeCAD: SandboxGui::SoWidgetShape Class Reference
SandboxGui::SoWidgetShape Class Reference
#include <Workbench.h>
Public Member Functions
SoWidgetShape ()
void setWidget (QWidget *w)
Static Public Member Functions
static void initClass ()
Protected Member Functions
virtual void GLRender (SoGLRenderAction *action)
virtual void computeBBox (SoAction *action, SbBox3f &box, SbVec3f &center)
virtual void generatePrimitives (SoAction *action)
void getQuad (SoState *state, SbVec3f &v0, SbVec3f &v1, SbVec3f &v2, SbVec3f &v3)
Detailed Description
Definition at line 69 of file Mod/Sandbox/Gui/Workbench.h.
Constructor & Destructor Documentation
SoWidgetShape()
SoWidgetShape::SoWidgetShape ()
Definition at line 153 of file Mod/Sandbox/Gui/Workbench.cpp.
Member Function Documentation
computeBBox()
void SoWidgetShape::computeBBox (SoAction * action, SbBox3f & box, SbVec3f & center) protected virtual
Definition at line 169 of file Mod/Sandbox/Gui/Workbench.cpp.
References MengerSponge::box, exportCSG::center(), getQuad(), and draftgeoutils.general::v1().
generatePrimitives()
void SoWidgetShape::generatePrimitives (SoAction * action) protected virtual
Definition at line 239 of file Mod/Sandbox/Gui/Workbench.cpp.
References Path.Post.scripts.dynapath_4060_post::action, getQuad(), and draftgeoutils.general::v1().
getQuad()
void SoWidgetShape::getQuad (SoState * state, SbVec3f & v0, SbVec3f & v1, SbVec3f & v2, SbVec3f & v3) protected
Definition at line 190 of file Mod/Sandbox/Gui/Workbench.cpp.
References DraftVecUtils::dist(), SCL.SimpleDataTypes::f, src.Mod.PartDesign.PartDesignTests.TestInvoluteGear::inv(), and draftgeoutils.general::v1().
Referenced by computeBBox(), and generatePrimitives().
GLRender()
void SoWidgetShape::GLRender (SoGLRenderAction * action) protected virtual
Definition at line 158 of file Mod/Sandbox/Gui/Workbench.cpp.
References src.Mod.PartDesign.fcgear.svggear::w.
initClass()
void SoWidgetShape::initClass () static
Definition at line 148 of file Mod/Sandbox/Gui/Workbench.cpp.
Referenced by PyMOD_INIT_FUNC().
setWidget()
void SoWidgetShape::setWidget (QWidget * w)
Definition at line 279 of file Mod/Sandbox/Gui/Workbench.cpp.
References src.Mod.PartDesign.fcgear.svggear::w.
The documentation for this class was generated from the following files:
Mod/Sandbox/Gui/Workbench.h
Mod/Sandbox/Gui/Workbench.cpp