FreeCAD: CommandAnnotate.cpp File Reference
CommandAnnotate.cpp File Reference
#include "PreCompiled.h"
#include <QApplication>
#include <QMessageBox>
#include <App/DocumentObject.h>
#include <Gui/Action.h>
#include <Gui/Application.h>
#include <Gui/BitmapFactory.h>
#include <Gui/Command.h>
#include <Gui/Control.h>
#include <Gui/MainWindow.h>
#include <Gui/Selection.h>
#include <Gui/SelectionObject.h>
#include <Gui/ViewProvider.h>
#include <Mod/TechDraw/App/Cosmetic.h>
#include <Mod/TechDraw/App/Geometry.h>
#include <Mod/TechDraw/App/DrawLeaderLine.h>
#include <Mod/TechDraw/App/DrawPage.h>
#include <Mod/TechDraw/App/DrawView.h>
#include <Mod/TechDraw/App/DrawViewAnnotation.h>
#include <Mod/TechDraw/App/DrawViewPart.h>
#include <Mod/TechDraw/App/DrawViewSymbol.h>
#include <Mod/TechDraw/App/DrawWeldSymbol.h>
#include <Mod/TechDraw/App/DrawUtil.h>
#include "DrawGuiUtil.h"
#include "QGIView.h"
#include "TaskCenterLine.h"
#include "TaskCosmeticLine.h"
#include "TaskCosVertex.h"
#include "TaskLeaderLine.h"
#include "TaskLineDecor.h"
#include "TaskRichAnno.h"
#include "TaskSurfaceFinishSymbols.h"
#include "TaskWeldingSymbol.h"
#include "TaskCosmeticCircle.h"
#include "ViewProviderViewPart.h"
#include "CommandHelpers.h"
Macros
#define GEOMETRYEDGE 0
#define COSMETICEDGE 1
#define CENTERLINE 2
Functions
void execCosmeticVertex (Gui::Command *cmd)
void execMidpoints (Gui::Command *cmd)
void execQuadrants (Gui::Command *cmd)
void execCenterLine (Gui::Command *cmd)
void exec2LineCenterLine (Gui::Command *cmd)
void exec2PointCenterLine (Gui::Command *cmd)
void execLine2Points (Gui::Command *cmd)
void execCosmeticCircle (Gui::Command *cmd)
void CreateTechDrawCommandsAnnotate ()
Macro Definition Documentation
CENTERLINE
#define CENTERLINE 2
Definition at line 1280 of file CommandAnnotate.cpp.
COSMETICEDGE
#define COSMETICEDGE 1
Definition at line 1279 of file CommandAnnotate.cpp.
GEOMETRYEDGE
#define GEOMETRYEDGE 0
Definition at line 1278 of file CommandAnnotate.cpp.
Function Documentation
CreateTechDrawCommandsAnnotate()
void CreateTechDrawCommandsAnnotate ()
Definition at line 1671 of file CommandAnnotate.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
exec2LineCenterLine()
void exec2LineCenterLine (Gui::Command * cmd)
Definition at line 824 of file CommandAnnotate.cpp.
References Gui::Control(), TechDraw::CosmeticExtension::getCenterLineBySelection(), Gui::getMainWindow(), TechDraw::CommandHelpers::getSelectedSubElements(), Gui::ControlSingleton::showDialog(), and Path.Log::warning().
exec2PointCenterLine()
void exec2PointCenterLine (Gui::Command * cmd)
Definition at line 901 of file CommandAnnotate.cpp.
References Gui::Control(), draftgeoutils.general::geomType(), TechDraw::CosmeticExtension::getCenterLineBySelection(), Base::Persistence::getClassTypeId(), Gui::getMainWindow(), Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), toolbit-attributes::s, Path.Dressup.Utils::selection(), Gui::ControlSingleton::showDialog(), and Path.Log::warning().
execCenterLine()
void execCenterLine (Gui::Command * cmd)
Definition at line 713 of file CommandAnnotate.cpp.
References Gui::Control(), draftgeoutils.general::geomType(), TechDraw::CosmeticExtension::getCenterLineBySelection(), Base::Persistence::getClassTypeId(), Gui::getMainWindow(), Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), toolbit-attributes::s, Path.Dressup.Utils::selection(), Gui::ControlSingleton::showDialog(), and Path.Log::warning().
execCosmeticCircle()
void execCosmeticCircle (Gui::Command * cmd)
Definition at line 1166 of file CommandAnnotate.cpp.
References TechDraw::ARCOFCIRCLE, TechDraw::CIRCLE, Gui::Control(), draftgeoutils.general::geomType(), Base::Persistence::getClassTypeId(), TechDraw::CosmeticExtension::getCosmeticEdgeBySelection(), Gui::getMainWindow(), TechDraw::DrawViewPart::getProjVertexByIndex(), Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), TechDraw::CosmeticEdge::m_geometry, buildPsets::p, toolbit-attributes::s, Path.Dressup.Utils::selection(), Gui::ControlSingleton::showDialog(), TestSpreadsheet::v, and Path.Log::warning().
execCosmeticVertex()
void execCosmeticVertex (Gui::Command * cmd)
Definition at line 306 of file CommandAnnotate.cpp.
References Gui::Control(), Base::Persistence::getClassTypeId(), Gui::getMainWindow(), draftutils.utils::getObjectsOfType, Gui::Command::getSelection(), Gui::ControlSingleton::showDialog(), and Path.Log::warning().
execLine2Points()
void execLine2Points (Gui::Command * cmd)
Definition at line 1015 of file CommandAnnotate.cpp.
References Gui::Control(), TechDraw::GENERIC, draftgeoutils.general::geomType(), Base::Persistence::getClassTypeId(), TechDraw::CosmeticExtension::getCosmeticEdgeBySelection(), Gui::getMainWindow(), TechDraw::DrawViewPart::getProjVertexByIndex(), Gui::Command::getSelection(), Gui::SelectionSingleton::getSelectionEx(), TechDraw::CosmeticEdge::m_geometry, buildPsets::p, toolbit-attributes::s, Path.Dressup.Utils::selection(), Gui::ControlSingleton::showDialog(), TestSpreadsheet::v, and Path.Log::warning().
execMidpoints()
void execMidpoints (Gui::Command * cmd)
Definition at line 330 of file CommandAnnotate.cpp.
References TechDraw::CosmeticExtension::addCosmeticVertex(), Gui::Command::commitCommand(), TechDraw::DrawViewPart::getEdgeGeometry(), TechDraw::DrawUtil::getIndexFromName(), TechDraw::CommandHelpers::getSelectedSubElements(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, App::DocumentObject::recomputeFeature(), and toolbit-attributes::s.
execQuadrants()
void execQuadrants (Gui::Command * cmd)
Definition at line 357 of file CommandAnnotate.cpp.
References TechDraw::CosmeticExtension::addCosmeticVertex(), Gui::Command::commitCommand(), TechDraw::DrawViewPart::getEdgeGeometry(), TechDraw::DrawUtil::getIndexFromName(), TechDraw::CommandHelpers::getSelectedSubElements(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, App::DocumentObject::recomputeFeature(), and toolbit-attributes::s.