FreeCAD: MillSim::MillSimulation Class Reference
MillSim::MillSimulation Class Reference
#include <MillSimulation.h>
Public Member Functions
MillSimulation ()
~MillSimulation ()
void ClearMillPathSegments ()
void Clear ()
void SimNext ()
void InitSimulation (float quality)
void AddTool (EndMill *tool)
void AddTool (const std::vector< float > &toolProfile, int toolid, float diameter)
bool ToolExists (int toolid)
void RenderSimulation ()
void RenderTool ()
void RenderPath ()
void RenderBaseShape ()
void Render ()
void ProcessSim (unsigned int time_ms)
void HandleKeyPress (int key)
void HandleGuiAction (eGuiItems actionItem, bool checked)
bool LoadGCodeFile (const char *fileName)
bool AddGcodeLine (const char *line)
void SetSimulationStage (float stage)
void SetBoxStock (float x, float y, float z, float l, float w, float h)
void SetArbitraryStock (std::vector< Vertex > &verts, std::vector< GLushort > &indices)
void SetBaseObject (std::vector< Vertex > &verts, std::vector< GLushort > &indices)
void MouseDrag (int buttons, int dx, int dy)
void MouseMove (int px, int py, int modifiers)
void MouseScroll (float dy)
void MouseHover (int px, int py)
void MousePress (int button, bool isPressed, int px, int py)
void Zoom (float factor)
void UpdateWindowScale (int width, int height)
Protected Member Functions
void InitDisplay (float quality)
void GlsimStart ()
void GlsimToolStep1 (void)
void GlsimToolStep2 (void)
void GlsimClipBack (void)
void GlsimRenderStock (void)
void GlsimRenderTools (void)
void GlsimEnd (void)
void renderSegmentForward (int iSeg)
void renderSegmentReversed (int iSeg)
void CalcSegmentPositions ()
EndMill * GetTool (int tool)
void RemoveTool (int toolId)
Protected Attributes
std::vector< EndMill * > mToolTable
GCodeParser mCodeParser
GuiDisplay guiDisplay
SimDisplay simDisplay
MillPathLine millPathLine
std::vector< MillPathSegment * > MillPathSegments
std::ostringstream mFpsStream
MillMotion mZeroPos = {eNop, -1, 0, 0, 100, 0, 0, 0, 0}
MillMotion mCurMotion = {eNop, -1, 0, 0, 0, 0, 0, 0, 0}
MillMotion mDestMotion = {eNop, -1, 0, 0, 0, 0, 0, 0, 0}
StockObject mStockObject
SolidObject mBaseShape
vec3 bgndColor = {0.1f, 0.2f, 0.3f}
vec3 stockColor = {0.5f, 0.55f, 0.9f}
vec3 cutColor = {0.5f, 0.84f, 0.73f}
vec3 toolColor = {0.5f, 0.4f, 0.3f}
vec3 baseShapeColor = {0.7f, 0.6f, 0.5f}
int mCurStep = 0
int mNTotalSteps = 0
int mPathStep = 0
int mSubStep = 0
int mNPathSteps = 0
int mDebug = 0
int mDebug1 = 0
int mDebug2 = 12
int mSimSpeed = 1
int mViewItems = 1
int mLastMouseX = 0
int mLastMouseY = 0
int mMouseButtonState = 0
int mLastModifiers = 0
bool mIsInStock = false
bool mSimPlaying = false
bool mSingleStep = false
Detailed Description
Definition at line 47 of file MillSimulation.h.
Constructor & Destructor Documentation
MillSimulation()
MillSim::MillSimulation::MillSimulation ()
Definition at line 33 of file MillSimulation.cpp.
References MillSim::eNop, guiDisplay, mCurMotion, and MillSim::GuiDisplay::SetMillSimulator().
~MillSimulation()
MillSim::MillSimulation::~MillSimulation ()
Definition at line 39 of file MillSimulation.cpp.
References Clear().
Member Function Documentation
AddGcodeLine()
bool MillSim::MillSimulation::AddGcodeLine (const char * line)
Definition at line 633 of file MillSimulation.cpp.
References MillSim::GCodeParser::AddLine(), and mCodeParser.
Referenced by CAMSimulator::DlgCAMSimulator::addGcodeCommand(), and CAMSimulator::DlgCAMSimulator::addTool().
AddTool() [1/2]
void MillSim::MillSimulation::AddTool (const std::vector< float > & toolProfile, int toolid, float diameter)
Definition at line 152 of file MillSimulation.cpp.
References mToolTable, and RemoveTool().
AddTool() [2/2]
void MillSim::MillSimulation::AddTool (EndMill * tool)
Definition at line 145 of file MillSimulation.cpp.
References mToolTable, RemoveTool(), and MillSim::EndMill::toolId.
Referenced by CAMSimulator::DlgCAMSimulator::addTool().
CalcSegmentPositions()
void MillSim::MillSimulation::CalcSegmentPositions () protected
Definition at line 247 of file MillSimulation.cpp.
References mCurStep, MillPathSegments, mNPathSteps, mPathStep, mSubStep, and buildPsets::p.
Referenced by SetSimulationStage(), and SimNext().
Clear()
void MillSim::MillSimulation::Clear ()
Definition at line 52 of file MillSimulation.cpp.
References MillSim::SimDisplay::CleanGL(), ClearMillPathSegments(), guiDisplay, SplineSurface::i, mCodeParser, mCurStep, mNTotalSteps, mPathStep, mStockObject, mToolTable, MillSim::GCodeParser::Operations, MillSim::GuiDisplay::ResetGui(), and simDisplay.
Referenced by CAMSimulator::DlgCAMSimulator::hideEvent(), and ~MillSimulation().
ClearMillPathSegments()
void MillSim::MillSimulation::ClearMillPathSegments ()
Definition at line 44 of file MillSimulation.cpp.
References SplineSurface::i, and MillPathSegments.
Referenced by Clear(), and InitSimulation().
GetTool()
EndMill * MillSim::MillSimulation::GetTool (int tool) protected
Definition at line 122 of file MillSimulation.cpp.
References SplineSurface::i, and mToolTable.
Referenced by InitSimulation(), RemoveTool(), and ToolExists().
GlsimClipBack()
void MillSim::MillSimulation::GlsimClipBack (void) protected
Definition at line 186 of file MillSimulation.cpp.
References glCullFace, glDepthFunc, glDepthMask, glStencilFunc, and glStencilOp.
Referenced by RenderSimulation().
GlsimEnd()
void MillSim::MillSimulation::GlsimEnd (void) protected
Definition at line 211 of file MillSimulation.cpp.
References glColorMask, glCullFace, glDepthFunc, glDepthMask, glDisable, and glStencilFunc.
Referenced by RenderSimulation().
GlsimRenderStock()
void MillSim::MillSimulation::GlsimRenderStock (void) protected
Definition at line 196 of file MillSimulation.cpp.
References glColorMask, glCullFace, glDepthFunc, glEnable, glStencilFunc, and glStencilOp.
Referenced by RenderSimulation().
GlsimRenderTools()
void MillSim::MillSimulation::GlsimRenderTools (void) protected
Definition at line 206 of file MillSimulation.cpp.
References glCullFace.
Referenced by RenderSimulation().
GlsimStart()
void MillSim::MillSimulation::GlsimStart () protected
Definition at line 160 of file MillSimulation.cpp.
References glColorMask, glDisable, and glEnable.
Referenced by RenderSimulation().
GlsimToolStep1()
void MillSim::MillSimulation::GlsimToolStep1 (void) protected
Definition at line 167 of file MillSimulation.cpp.
References glCullFace, glDepthFunc, glDepthMask, glStencilFunc, and glStencilOp.
Referenced by renderSegmentForward(), and renderSegmentReversed().
GlsimToolStep2()
void MillSim::MillSimulation::GlsimToolStep2 (void) protected
Definition at line 177 of file MillSimulation.cpp.
References glCullFace, glDepthFunc, glDepthMask, glStencilFunc, and glStencilOp.
Referenced by renderSegmentForward(), renderSegmentReversed(), and RenderSimulation().
HandleGuiAction()
void MillSim::MillSimulation::HandleGuiAction (eGuiItems actionItem, bool checked)
Definition at line 450 of file MillSimulation.cpp.
References MillSim::SimDisplay::applySSAO, MillSim::eGuiItemAmbientOclusion, MillSim::eGuiItemFaster, MillSim::eGuiItemPath, MillSim::eGuiItemPause, MillSim::eGuiItemPlay, MillSim::eGuiItemSingleStep, MillSim::eGuiItemView, guiDisplay, mSimPlaying, mSimSpeed, mSingleStep, mViewItems, simDisplay, MillSim::SimDisplay::updateDisplay, MillSim::GuiDisplay::UpdatePlayState(), MillSim::GuiDisplay::UpdateSimSpeed(), VIEWITEM_MAX, and VIEWITEM_SIMULATION.
HandleKeyPress()
void MillSim::MillSimulation::HandleKeyPress (int key)
Definition at line 433 of file MillSimulation.cpp.
References MillSim::gDebug, guiDisplay, MillSim::GuiDisplay::HandleKeyPress(), mDebug, mDebug2, mNPathSteps, and mSimSpeed.
InitDisplay()
void MillSim::MillSimulation::InitDisplay (float quality) protected
Definition at line 503 of file MillSimulation.cpp.
References guiDisplay, SplineSurface::i, MillSim::SimDisplay::InitGL(), MillSim::GuiDisplay::InitGui(), mToolTable, and simDisplay.
Referenced by InitSimulation().
InitSimulation()
void MillSim::MillSimulation::InitSimulation (float quality)
Definition at line 87 of file MillSimulation.cpp.
References MillSim::MillPathSegment::AppendPathPoints(), MillSim::SimDisplay::applySSAO, MillSim::MillPathLine::Clear(), ClearMillPathSegments(), MillSim::eGuiItemAmbientOclusion, MillSim::MillPathLine::GenerateModel(), GetTool(), guiDisplay, SplineSurface::i, MillSim::MillPathSegment::indexInArray, InitDisplay(), MillSim::GuiDisplay::IsChecked(), MillSim::SimDisplay::maxFar, mCodeParser, mCurMotion, mCurStep, mDestMotion, millPathLine, MillSim::MillPathLine::MillPathPointsBuffer, MillPathSegments, mNPathSteps, mNTotalSteps, mPathStep, mSimPlaying, mSimSpeed, mZeroPos, MillSim::MillPathSegment::numSimSteps, MillSim::GCodeParser::Operations, MillSim::MillPathSegment::segmentIndex, MillSim::MillPathSegment::SetQuality(), simDisplay, and MillSim::MillMotion::tool.
Referenced by CAMSimulator::DlgCAMSimulator::initialize().
LoadGCodeFile()
bool MillSim::MillSimulation::LoadGCodeFile (const char * fileName)
Definition at line 624 of file MillSimulation.cpp.
References mCodeParser, and MillSim::GCodeParser::Parse().
MouseDrag()
void MillSim::MillSimulation::MouseDrag (int buttons, int dx, int dy)
Definition at line 534 of file MillSimulation.cpp.
References SCL.SimpleDataTypes::f, guiDisplay, MillSim::GuiDisplay::MouseDrag(), MillSim::SimDisplay::MoveEye(), MS_KBD_ALT, MS_KBD_CONTROL, MS_KBD_SHIFT, MS_MOUSE_LEFT, MS_MOUSE_MID, MillSim::SimDisplay::RotateEye(), simDisplay, MillSim::SimDisplay::TiltEye(), and Zoom().
Referenced by MouseMove().
MouseHover()
void MillSim::MillSimulation::MouseHover (int px, int py)
Definition at line 578 of file MillSimulation.cpp.
References guiDisplay, and MillSim::GuiDisplay::MouseCursorPos().
Referenced by MouseMove().
MouseMove()
void MillSim::MillSimulation::MouseMove (int px, int py, int modifiers)
Definition at line 549 of file MillSimulation.cpp.
References mLastModifiers, mLastMouseX, mLastMouseY, mMouseButtonState, MouseDrag(), and MouseHover().
Referenced by CAMSimulator::DlgCAMSimulator::mouseMoveEvent().
MousePress()
void MillSim::MillSimulation::MousePress (int button, bool isPressed, int px, int py)
Definition at line 583 of file MillSimulation.cpp.
References guiDisplay, mLastMouseX, mLastMouseY, mMouseButtonState, MillSim::GuiDisplay::MousePressed(), and mSimPlaying.
Referenced by CAMSimulator::DlgCAMSimulator::mousePressEvent(), and CAMSimulator::DlgCAMSimulator::mouseReleaseEvent().
MouseScroll()
void MillSim::MillSimulation::MouseScroll (float dy)
Definition at line 572 of file MillSimulation.cpp.
References SCL.SimpleDataTypes::f, and Zoom().
Referenced by CAMSimulator::DlgCAMSimulator::wheelEvent().
ProcessSim()
void MillSim::MillSimulation::ProcessSim (unsigned int time_ms)
Definition at line 399 of file MillSimulation.cpp.
References MillSim::eGuiItemRotate, SCL.SimpleDataTypes::f, guiDisplay, MillSim::GuiDisplay::IsChecked(), mDestMotion, mFpsStream, mSimPlaying, mSingleStep, Render(), MillSim::SimDisplay::RotateEye(), simDisplay, SimNext(), and MillSim::MillMotion::z.
Referenced by CAMSimulator::DlgCAMSimulator::render().
RemoveTool()
void MillSim::MillSimulation::RemoveTool (int toolId) protected
Definition at line 132 of file MillSimulation.cpp.
References DraftVecUtils::find(), GetTool(), and mToolTable.
Referenced by AddTool().
Render()
void MillSim::MillSimulation::Render ()
Definition at line 360 of file MillSimulation.cpp.
References bgndColor, MillSim::SolidObject::center, SCL.SimpleDataTypes::f, glBindFramebuffer, glClear, glClearColor, guiDisplay, mCurStep, mNTotalSteps, mStockObject, MillSim::SimDisplay::PrepareDisplay(), MillSim::SimDisplay::PrepareFrameBuffer(), MillSim::GuiDisplay::Render(), RenderBaseShape(), RenderPath(), MillSim::SimDisplay::RenderResult(), RenderSimulation(), RenderTool(), simDisplay, and MillSim::SimDisplay::updateDisplay.
Referenced by ProcessSim().
RenderBaseShape()
void MillSim::MillSimulation::RenderBaseShape ()
Definition at line 347 of file MillSimulation.cpp.
References baseShapeColor, glDisable, glEnable, glPolygonOffset, mBaseShape, mViewItems, MillSim::SolidObject::render(), simDisplay, MillSim::SimDisplay::StartDepthPass(), MillSim::SimDisplay::StartGeometryPass(), and VIEWITEM_BASE_SHAPE.
Referenced by Render().
RenderPath()
void MillSim::MillSimulation::RenderPath ()
Definition at line 335 of file MillSimulation.cpp.
References MillSim::eGuiItemPath, glDepthMask, guiDisplay, MillSim::GuiDisplay::IsChecked(), millPathLine, mPathStep, MillSim::MillPathLine::Render(), MillSim::SimDisplay::SetupLinePathPass(), and simDisplay.
Referenced by Render().
renderSegmentForward()
void MillSim::MillSimulation::renderSegmentForward (int iSeg) protected
Definition at line 221 of file MillSimulation.cpp.
References GlsimToolStep1(), GlsimToolStep2(), SplineSurface::i, MillPathSegments, mPathStep, mSubStep, and buildPsets::p.
Referenced by RenderSimulation().
renderSegmentReversed()
void MillSim::MillSimulation::renderSegmentReversed (int iSeg) protected
Definition at line 234 of file MillSimulation.cpp.
References GlsimToolStep1(), GlsimToolStep2(), SplineSurface::i, MillPathSegments, mPathStep, mSubStep, and buildPsets::p.
Referenced by RenderSimulation().
RenderSimulation()
void MillSim::MillSimulation::RenderSimulation ()
Definition at line 266 of file MillSimulation.cpp.
References cutColor, GlsimClipBack(), GlsimEnd(), GlsimRenderStock(), GlsimRenderTools(), GlsimStart(), GlsimToolStep2(), SplineSurface::i, MillPathSegments, mPathStep, mStockObject, mSubStep, mViewItems, buildPsets::p, MillSim::SolidObject::render(), renderSegmentForward(), renderSegmentReversed(), simDisplay, MillSim::SimDisplay::StartDepthPass(), MillSim::SimDisplay::StartGeometryPass(), stockColor, and VIEWITEM_SIMULATION.
Referenced by Render().
RenderTool()
void MillSim::MillSimulation::RenderTool ()
Definition at line 318 of file MillSimulation.cpp.
References MillSim::identityMat, mat4x4_translate(), mDestMotion, MillPathSegments, MillSim::MotionPosToVec(), mPathStep, buildPsets::p, simDisplay, MillSim::SimDisplay::StartGeometryPass(), and toolColor.
Referenced by Render().
SetArbitraryStock()
void MillSim::MillSimulation::SetArbitraryStock (std::vector< Vertex > & verts, std::vector< GLushort > & indices)
Definition at line 523 of file MillSimulation.cpp.
References MillSim::SolidObject::GenerateSolid(), mStockObject, MillSim::SimDisplay::ScaleViewToStock(), and simDisplay.
Referenced by CAMSimulator::DlgCAMSimulator::SetStockShape().
SetBaseObject()
void MillSim::MillSimulation::SetBaseObject (std::vector< Vertex > & verts, std::vector< GLushort > & indices)
Definition at line 529 of file MillSimulation.cpp.
References MillSim::SolidObject::GenerateSolid(), and mBaseShape.
Referenced by CAMSimulator::DlgCAMSimulator::SetBaseShape().
SetBoxStock()
void MillSim::MillSimulation::SetBoxStock (float x, float y, float z, float l, float w, float h)
Definition at line 517 of file MillSimulation.cpp.
References MillSim::StockObject::GenerateBoxStock(), RobotExample::l, mStockObject, MillSim::SimDisplay::ScaleViewToStock(), simDisplay, src.Mod.PartDesign.fcgear.svggear::w, MovieTool::x, and MovieTool::y.
SetSimulationStage()
void MillSim::MillSimulation::SetSimulationStage (float stage)
Definition at line 638 of file MillSimulation.cpp.
References CalcSegmentPositions(), mCurStep, mNTotalSteps, mSingleStep, simDisplay, and MillSim::SimDisplay::updateDisplay.
Referenced by MillSim::GuiDisplay::MouseDrag().
SimNext()
void MillSim::MillSimulation::SimNext ()
Definition at line 69 of file MillSimulation.cpp.
References CalcSegmentPositions(), mCurStep, mNTotalSteps, mSimSpeed, simDisplay, and MillSim::SimDisplay::updateDisplay.
Referenced by ProcessSim().
ToolExists()
bool MillSim::MillSimulation::ToolExists (int toolid) inline
Definition at line 58 of file MillSimulation.h.
References GetTool().
Referenced by CAMSimulator::DlgCAMSimulator::addTool().
UpdateWindowScale()
void MillSim::MillSimulation::UpdateWindowScale (int width, int height)
Definition at line 611 of file MillSimulation.cpp.
References guiDisplay, MillSim::gWindowSizeH, MillSim::gWindowSizeW, simDisplay, MillSim::SimDisplay::updateDisplay, MillSim::SimDisplay::UpdateWindowScale(), and MillSim::GuiDisplay::UpdateWindowScale().
Referenced by CAMSimulator::DlgCAMSimulator::resizeEvent().
Zoom()
void MillSim::MillSimulation::Zoom (float factor)
Definition at line 599 of file MillSimulation.cpp.
References SCL.SimpleDataTypes::f, MillSim::SimDisplay::GetEyeFactor(), simDisplay, and MillSim::SimDisplay::UpdateEyeFactor().
Referenced by MouseDrag(), and MouseScroll().
Member Data Documentation
baseShapeColor
vec3 MillSim::MillSimulation::baseShapeColor = {0.7f, 0.6f, 0.5f} protected
Definition at line 121 of file MillSimulation.h.
Referenced by RenderBaseShape().
bgndColor
vec3 MillSim::MillSimulation::bgndColor = {0.1f, 0.2f, 0.3f} protected
Definition at line 117 of file MillSimulation.h.
Referenced by Render().
cutColor
vec3 MillSim::MillSimulation::cutColor = {0.5f, 0.84f, 0.73f} protected
Definition at line 119 of file MillSimulation.h.
Referenced by RenderSimulation().
guiDisplay
GuiDisplay MillSim::MillSimulation::guiDisplay protected
Definition at line 104 of file MillSimulation.h.
Referenced by Clear(), HandleGuiAction(), HandleKeyPress(), InitDisplay(), InitSimulation(), MillSimulation(), MouseDrag(), MouseHover(), MousePress(), ProcessSim(), Render(), RenderPath(), and UpdateWindowScale().
mBaseShape
SolidObject MillSim::MillSimulation::mBaseShape protected
Definition at line 115 of file MillSimulation.h.
Referenced by RenderBaseShape(), and SetBaseObject().
mCodeParser
GCodeParser MillSim::MillSimulation::mCodeParser protected
Definition at line 103 of file MillSimulation.h.
Referenced by AddGcodeLine(), Clear(), InitSimulation(), and LoadGCodeFile().
mCurMotion
MillMotion MillSim::MillSimulation::mCurMotion = {eNop, -1, 0, 0, 0, 0, 0, 0, 0} protected
Definition at line 111 of file MillSimulation.h.
Referenced by InitSimulation(), and MillSimulation().
mCurStep
int MillSim::MillSimulation::mCurStep = 0 protected
Definition at line 123 of file MillSimulation.h.
Referenced by CalcSegmentPositions(), Clear(), InitSimulation(), Render(), SetSimulationStage(), and SimNext().
mDebug
int MillSim::MillSimulation::mDebug = 0 protected
Definition at line 128 of file MillSimulation.h.
Referenced by HandleKeyPress().
mDebug1
int MillSim::MillSimulation::mDebug1 = 0 protected
Definition at line 129 of file MillSimulation.h.
mDebug2
int MillSim::MillSimulation::mDebug2 = 12 protected
Definition at line 130 of file MillSimulation.h.
Referenced by HandleKeyPress().
mDestMotion
MillMotion MillSim::MillSimulation::mDestMotion = {eNop, -1, 0, 0, 0, 0, 0, 0, 0} protected
Definition at line 112 of file MillSimulation.h.
Referenced by InitSimulation(), ProcessSim(), and RenderTool().
mFpsStream
std::ostringstream MillSim::MillSimulation::mFpsStream protected
Definition at line 108 of file MillSimulation.h.
Referenced by ProcessSim().
millPathLine
MillPathLine MillSim::MillSimulation::millPathLine protected
Definition at line 106 of file MillSimulation.h.
Referenced by InitSimulation(), and RenderPath().
MillPathSegments
std::vector<MillPathSegment*> MillSim::MillSimulation::MillPathSegments protected
Definition at line 107 of file MillSimulation.h.
Referenced by CalcSegmentPositions(), ClearMillPathSegments(), InitSimulation(), renderSegmentForward(), renderSegmentReversed(), RenderSimulation(), and RenderTool().
mIsInStock
bool MillSim::MillSimulation::mIsInStock = false protected
Definition at line 138 of file MillSimulation.h.
mLastModifiers
int MillSim::MillSimulation::mLastModifiers = 0 protected
Definition at line 136 of file MillSimulation.h.
Referenced by MouseMove().
mLastMouseX
int MillSim::MillSimulation::mLastMouseX = 0 protected
Definition at line 134 of file MillSimulation.h.
Referenced by MouseMove(), and MousePress().
mLastMouseY
int MillSim::MillSimulation::mLastMouseY = 0 protected
Definition at line 134 of file MillSimulation.h.
Referenced by MouseMove(), and MousePress().
mMouseButtonState
int MillSim::MillSimulation::mMouseButtonState = 0 protected
Definition at line 135 of file MillSimulation.h.
Referenced by MouseMove(), and MousePress().
mNPathSteps
int MillSim::MillSimulation::mNPathSteps = 0 protected
Definition at line 127 of file MillSimulation.h.
Referenced by CalcSegmentPositions(), HandleKeyPress(), and InitSimulation().
mNTotalSteps
int MillSim::MillSimulation::mNTotalSteps = 0 protected
Definition at line 124 of file MillSimulation.h.
Referenced by Clear(), InitSimulation(), Render(), SetSimulationStage(), and SimNext().
mPathStep
int MillSim::MillSimulation::mPathStep = 0 protected
Definition at line 125 of file MillSimulation.h.
Referenced by CalcSegmentPositions(), Clear(), InitSimulation(), RenderPath(), renderSegmentForward(), renderSegmentReversed(), RenderSimulation(), and RenderTool().
mSimPlaying
bool MillSim::MillSimulation::mSimPlaying = false protected
Definition at line 139 of file MillSimulation.h.
Referenced by HandleGuiAction(), InitSimulation(), MousePress(), and ProcessSim().
mSimSpeed
int MillSim::MillSimulation::mSimSpeed = 1 protected
Definition at line 131 of file MillSimulation.h.
Referenced by HandleGuiAction(), HandleKeyPress(), InitSimulation(), and SimNext().
mSingleStep
bool MillSim::MillSimulation::mSingleStep = false protected
Definition at line 140 of file MillSimulation.h.
Referenced by HandleGuiAction(), ProcessSim(), and SetSimulationStage().
mStockObject
StockObject MillSim::MillSimulation::mStockObject protected
Definition at line 114 of file MillSimulation.h.
Referenced by Clear(), Render(), RenderSimulation(), SetArbitraryStock(), and SetBoxStock().
mSubStep
int MillSim::MillSimulation::mSubStep = 0 protected
Definition at line 126 of file MillSimulation.h.
Referenced by CalcSegmentPositions(), renderSegmentForward(), renderSegmentReversed(), and RenderSimulation().
mToolTable
std::vector<EndMill*> MillSim::MillSimulation::mToolTable protected
Definition at line 102 of file MillSimulation.h.
Referenced by AddTool(), Clear(), GetTool(), InitDisplay(), and RemoveTool().
mViewItems
int MillSim::MillSimulation::mViewItems = 1 protected
Definition at line 132 of file MillSimulation.h.
Referenced by HandleGuiAction(), RenderBaseShape(), and RenderSimulation().
mZeroPos
MillMotion MillSim::MillSimulation::mZeroPos = {eNop, -1, 0, 0, 100, 0, 0, 0, 0} protected
Definition at line 110 of file MillSimulation.h.
Referenced by InitSimulation().
simDisplay
SimDisplay MillSim::MillSimulation::simDisplay protected
Definition at line 105 of file MillSimulation.h.
Referenced by Clear(), HandleGuiAction(), InitDisplay(), InitSimulation(), MouseDrag(), ProcessSim(), Render(), RenderBaseShape(), RenderPath(), RenderSimulation(), RenderTool(), SetArbitraryStock(), SetBoxStock(), SetSimulationStage(), SimNext(), UpdateWindowScale(), and Zoom().
stockColor
vec3 MillSim::MillSimulation::stockColor = {0.5f, 0.55f, 0.9f} protected
Definition at line 118 of file MillSimulation.h.
Referenced by RenderSimulation().
toolColor
vec3 MillSim::MillSimulation::toolColor = {0.5f, 0.4f, 0.3f} protected
Definition at line 120 of file MillSimulation.h.
Referenced by RenderTool().
The documentation for this class was generated from the following files:
MillSimulation.h
MillSimulation.cpp