FreeCAD: Gui::SoGLWidgetElement Class Reference
Gui::SoGLWidgetElement Class Reference
#include <SoFCInteractiveElement.h>
Public Member Functions
void init (SoState *state) override
void push (SoState *state) override
void pop (SoState *state, const SoElement *prevTopElement) override
SbBool matches (const SoElement *element) const override
SoElement * copyMatchInfo () const override
Static Public Member Functions
static void initClass ()
static void set (SoState *state, QtGLWidget *window)
static void get (SoState *state, QtGLWidget *&window)
Protected Member Functions
~SoGLWidgetElement () override
Protected Attributes
QtGLWidget * window
Detailed Description
Definition at line 81 of file SoFCInteractiveElement.h.
Constructor & Destructor Documentation
~SoGLWidgetElement()
SoGLWidgetElement::~SoGLWidgetElement () override protected default
Member Function Documentation
copyMatchInfo()
SoElement * SoGLWidgetElement::copyMatchInfo () const override
Definition at line 118 of file SoFCInteractiveElement.cpp.
get()
void SoGLWidgetElement::get (SoState * state, QtGLWidget *& window) static
Definition at line 96 of file SoFCInteractiveElement.cpp.
References window.
Referenced by Gui::SoStringLabel::GLRender(), Gui::SoFCUnifiedSelection::GLRenderBelowPath(), draftguitools.gui_trackers.editTracker::move(), and Gui::SoFCSelection::redrawHighlighted().
init()
void SoGLWidgetElement::init (SoState * state) override
Definition at line 81 of file SoFCInteractiveElement.cpp.
References SIM::Coin3D::Quarter::Quarter::init(), and window.
Referenced by DocumentObject.DocumentObject::onChanged().
initClass()
void SoGLWidgetElement::initClass () static
Definition at line 74 of file SoFCInteractiveElement.cpp.
Referenced by Gui::SoFCDB::init(), CAMTests.TestPathAdaptive.TestPathAdaptive::setUp(), and CAMTests.TestPathProfile.TestPathProfile::setUp().
matches()
SbBool SoGLWidgetElement::matches (const SoElement * element) const override
Definition at line 113 of file SoFCInteractiveElement.cpp.
pop()
void SoGLWidgetElement::pop (SoState * state, const SoElement * prevTopElement) override
Definition at line 108 of file SoFCInteractiveElement.cpp.
push()
void SoGLWidgetElement::push (SoState * state) override
Definition at line 103 of file SoFCInteractiveElement.cpp.
set()
void SoGLWidgetElement::set (SoState * state, QtGLWidget * window) static
Definition at line 89 of file SoFCInteractiveElement.cpp.
References window.
Referenced by Gui::SoGLWidgetNode::doAction(), draftguitools.gui_trackers.editTracker::move(), and Gui::View3DInventorViewer::renderScene().
Member Data Documentation
window
QtGLWidget* Gui::SoGLWidgetElement::window protected
Definition at line 103 of file SoFCInteractiveElement.h.
Referenced by get(), init(), and set().
The documentation for this class was generated from the following files:
SoFCInteractiveElement.h
SoFCInteractiveElement.cpp