FreeCAD: Gui::Dialog::ApplicationCacheSettings Class Reference
Gui::Dialog::ApplicationCacheSettings Class Reference
#include <DlgSettingsCacheDirectory.h>
Static Public Member Functions
static unsigned int getCacheSizeLimit ()
static void setCacheSizeLimit (unsigned int)
static int getCheckPeriod ()
static void setCheckPeriod (int)
Detailed Description
Definition at line 138 of file DlgSettingsCacheDirectory.h.
Member Function Documentation
getCacheSizeLimit()
unsigned int ApplicationCacheSettings::getCacheSizeLimit () static
Definition at line 367 of file DlgSettingsCacheDirectory.cpp.
References Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), and ParameterGrp::GetUnsigned().
Referenced by Gui::Dialog::ApplicationCache::applyUserSettings(), and Gui::Dialog::DlgSettingsCacheDirectory::loadSettings().
getCheckPeriod()
int ApplicationCacheSettings::getCheckPeriod () static
Definition at line 379 of file DlgSettingsCacheDirectory.cpp.
References Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), ParameterGrp::GetInt(), and Gui::Dialog::ApplicationCache::Weekly.
Referenced by Gui::Dialog::ApplicationCache::applyUserSettings(), and Gui::Dialog::DlgSettingsCacheDirectory::loadSettings().
setCacheSizeLimit()
void ApplicationCacheSettings::setCacheSizeLimit (unsigned int limit) static
Definition at line 373 of file DlgSettingsCacheDirectory.cpp.
References Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), and ParameterGrp::SetUnsigned().
Referenced by Gui::Dialog::DlgSettingsCacheDirectory::saveSettings().
setCheckPeriod()
void ApplicationCacheSettings::setCheckPeriod (int period) static
Definition at line 385 of file DlgSettingsCacheDirectory.cpp.
References Gui::WindowParameter::getDefaultParameter(), ParameterGrp::GetGroup(), and ParameterGrp::SetInt().
Referenced by Gui::Dialog::DlgSettingsCacheDirectory::saveSettings().
The documentation for this class was generated from the following files:
DlgSettingsCacheDirectory.h
DlgSettingsCacheDirectory.cpp