FreeCAD: App::PropertyLinkBase Class Reference
App::PropertyLinkBase Class Reference abstract
Parent class of all link type properties.
#include <PropertyLinks.h>
Public Types
enum LinkFlags {
LinkAllowExternal, LinkDetached, LinkRestoring, LinkAllowPartial,
LinkRestoreLabel, LinkSyncSubObject, LinkNewElement, LinkSilentRestore
}
using ShadowSub = ElementNamePair
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Public Member Functions
PropertyLinkBase ()
~PropertyLinkBase () override
virtual void updateElementReference (App::DocumentObject *feature, bool reverse=false, bool notify=false)
void unregisterElementReference ()
Clear internal element reference registration.
void registerLabelReferences (std::vector< std::string > &&labels, bool reset=true)
void checkLabelReferences (const std::vector< std::string > &subs, bool reset=true)
void unregisterLabelReferences ()
Clear internal label references registration.
virtual bool referenceChanged () const
Test if the element reference has changed after restore.
virtual int checkRestore (std::string *msg=nullptr) const
virtual void getLinks (std::vector< App::DocumentObject * > &objs, bool all=false, std::vector< std::string > *subs=nullptr, bool newStyle=true) const =0
virtual void getLinksTo (std::vector< App::ObjectIdentifier > &identifiers, App::DocumentObject *obj, const char *subname=nullptr, bool all=false) const =0
virtual void breakLink (App::DocumentObject *obj, bool clear)=0
virtual bool adjustLink (const std::set< App::DocumentObject * > &inList)=0
virtual Property * CopyOnLinkReplace (const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj) const =0
virtual Property * CopyOnImportExternal (const std::map< std::string, std::string > &nameMap) const
virtual Property * CopyOnLabelChange (App::DocumentObject *obj, const std::string &ref, const char *newLabel) const
std::vector< App::DocumentObject * > linkedObjects (bool all=false) const
Helper function to return all linked objects of this property.
template<class T >
void getLinkedObjects (T &inserter, bool all=false) const
Helper function to return linked objects using an std::inserter.
void getLinkedElements (std::map< App::DocumentObject *, std::vector< std::string >> &elements, bool newStyle=true, bool all=false) const
Helper function to return a map of linked object and its subname references.
std::map< App::DocumentObject *, std::vector< std::string > > linkedElements (bool newStyle=true, bool all=false) const
Helper function to return a map of linked object and its subname references.
bool isSame (const Property &other) const override
Compare if this property has the same content as the given one.
void setAllowExternal (bool allow)
bool _updateElementReference (App::DocumentObject *feature, App::DocumentObject *obj, std::string &sub, ShadowSub &shadow, bool reverse, bool notify=false)
void _registerElementReference (App::DocumentObject *obj, std::string &sub, ShadowSub &shadow)
bool testFlag (int flag) const
virtual void setAllowPartial (bool enable)
void setReturnNewElement (bool enable)
void setSilentRestore (bool enable)
Public Member Functions inherited from App::Property
Property ()
~Property () override
unsigned int getMemSize () const override
const char * getName () const
bool hasName () const
std::string getFullName () const
virtual const char * getEditorName () const
Get the class name of the associated property editor item.
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual void afterRestore ()
virtual void onContainerRestored ()
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
virtual Property * Copy () const =0
Returns a new copy of the property (mainly for Undo/Redo and transactions)
virtual void Paste (const Property &from)=0
Paste the value from the property (mainly for Undo/Redo and transactions)
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
int64_t getID () const
virtual void beforeSave () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void Save (Writer &) const =0
virtual void Restore (XMLReader &)=0
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Public Member Functions inherited from App::ScopedLink
void setScope (LinkScope scope)
Set the links scope Allows to define what kind of links are allowed. Only in the Local GeoFeatureGroup, in this and all Childs or to all objects within the Glocal scope.
LinkScope getScope () const
Get the links scope Retrieve what kind of links are allowed. Only in the Local GeoFeatureGroup, in this and all Childs or to all objects within the Glocal scope.
Static Public Member Functions
static std::pair< App::DocumentObject *, std::string > tryReplaceLink (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const char *sub=nullptr)
Helper functions.
static std::pair< App::DocumentObject *, std::vector< std::string > > tryReplaceLinkSubs (const App::PropertyContainer *owner, App::DocumentObject *obj, const App::DocumentObject *parent, App::DocumentObject *oldObj, App::DocumentObject *newObj, const std::vector< std::string > &subs)
static void updateElementReferences (DocumentObject *feature, bool reverse=false)
Update all element references in all link properties of feature.
static const std::unordered_set< PropertyLinkBase * > & getElementReferences (DocumentObject *)
Obtain link properties that contain element references to a given object.
static void breakLinks (App::DocumentObject *link, const std::vector< App::DocumentObject * > &objs, bool clear)
static std::string tryImportSubName (const App::DocumentObject *obj, const char *sub, const App::Document *doc, const std::map< std::string, std::string > &nameMap)
static App::DocumentObject * tryImport (const App::Document *doc, const App::DocumentObject *obj, const std::map< std::string, std::string > &nameMap)
static const char * exportSubName (std::string &output, const App::DocumentObject *obj, const char *subname, bool first_obj=false)
static std::string importSubName (Base::XMLReader &reader, const char *sub, bool &restoreLabel)
static void restoreLabelReference (const App::DocumentObject *obj, std::string &sub, ShadowSub *shadow=nullptr)
static void getLabelReferences (std::vector< std::string > &labels, const char *subname)
static std::vector< std::pair< Property *, std::unique_ptr< Property > > > updateLabelReferences (App::DocumentObject *obj, const char *newLabel)
static std::string updateLabelReference (const App::DocumentObject *linked, const char *subname, App::DocumentObject *obj, const std::string &ref, const char *newLabel)
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Public Attributes
boost::signals2::signal< void(const std::string &, const std::string &)> signalUpdateElementReference
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions
void hasSetValue () override
Gets called by all setValue() methods after the value has changed.
void setFlag (int flag, bool value=true)
void _getLinksTo (std::vector< App::ObjectIdentifier > &identifiers, App::DocumentObject *obj, const char *subname, const std::vector< std::string > &subs, const std::vector< PropertyLinkBase::ShadowSub > &shadows) const
Protected Member Functions inherited from App::Property
virtual void aboutToSetValue ()
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Protected Attributes
std::bitset< 32 > _Flags
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Protected Attributes inherited from App::ScopedLink
LinkScope _pcScope = LinkScope::Local
Friends
class DocInfo
Additional Inherited Members
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Detailed Description
Parent class of all link type properties.
Definition at line 111 of file PropertyLinks.h.
Member Typedef Documentation
ShadowSub
using App::PropertyLinkBase::ShadowSub = ElementNamePair
Definition at line 116 of file PropertyLinks.h.
Member Enumeration Documentation
LinkFlags
enum App::PropertyLinkBase::LinkFlags
Enumerator
LinkAllowExternal
LinkDetached
LinkRestoring
LinkAllowPartial
LinkRestoreLabel
LinkSyncSubObject
LinkNewElement
LinkSilentRestore
Definition at line 591 of file PropertyLinks.h.
Constructor & Destructor Documentation
PropertyLinkBase()
PropertyLinkBase::PropertyLinkBase () default
~PropertyLinkBase()
PropertyLinkBase::~PropertyLinkBase () override
Definition at line 67 of file PropertyLinks.cpp.
Member Function Documentation
_getLinksTo()
void PropertyLinkBase::_getLinksTo (std::vector< App::ObjectIdentifier > & identifiers, App::DocumentObject * obj, const char * subname, const std::vector< std::string > & subs, const std::vector< PropertyLinkBase::ShadowSub > & shadows) const protected
Definition at line 1784 of file PropertyLinks.cpp.
References App::SubObjectT::getOldElementName(), App::SubObjectT::getSubObject(), SplineSurface::i, and importers.importIFCmulticore::subs.
Referenced by App::PropertyLinkSub::getLinksTo(), and App::PropertyXLink::getLinksTo().
_registerElementReference()
void PropertyLinkBase::_registerElementReference (App::DocumentObject * obj, std::string & sub, ShadowSub & shadow)
Helper function to register geometry element reference
Parameters
obj the linked object
sub the subname reference
shadow a pair of new and old style element references to be updated.
Search for any geometry element reference inside the subname, and register for future update in case of geometry model update.
Definition at line 301 of file PropertyLinks.cpp.
References _ElementRefMap, _updateElementReference(), App::DocumentObject::getNameInDocument(), App::ElementNamePair::newName, and App::GeoFeature::resolveElement().
Referenced by App::PropertyLinkSub::onContainerRestored(), App::PropertyLinkSubList::onContainerRestored(), and App::PropertyXLink::onContainerRestored().
_updateElementReference()
bool PropertyLinkBase::_updateElementReference (App::DocumentObject * feature, App::DocumentObject * obj, std::string & sub, ShadowSub & shadow, bool reverse, bool notify = false)
Helper function for update individual element reference
Parameters
feature if given, than only update element reference belonging to this feature. If not, then update geometry element references.
sub the subname reference to be updated.
shadow a pair of new and old style element references to be updated.
reverse if true, then use the old style, i.e. non-mapped element reference to query for the new style, i.e. mapped element reference when update. If false, then the other way around.
notify if true, call aboutToSetValue() before change
This helper function is to be called by each link property in the event of geometry element reference change due to geometry model changes.
Definition at line 397 of file PropertyLinks.cpp.
References _ElementRefMap, App::Property::aboutToSetValue(), FC_LOG, FC_TRACE, FC_WARN, Data::findElementName(), App::DocumentObject::getNameInDocument(), Data::hasMappedElementName(), Data::hasMissingElement(), App::GeoFeature::hasMissingElement(), femtools.tokrules::names, App::ElementNamePair::newName, femsolver.signal::notify(), App::ElementNamePair::oldName, RobotExample::pos, RobotExampleTrajectoryOutOfShapes::pos2, propertyName(), App::GeoFeature::resolveElement(), App::GeoFeature::searchElementCache(), and App::ElementNamePair::swap().
Referenced by _registerElementReference(), App::PropertyLinkSubList::updateElementReference(), and updateLinkReference().
adjustLink()
virtual bool App::PropertyLinkBase::adjustLink (const std::set< App::DocumentObject * > & inList) pure virtual
Called to adjust the link to avoid potential cyclic dependency
Parameters
inList recursive in-list of the would-be parent
Returns
Return whether the link has been adjusted
This function tries to correct the link to avoid any (sub)object inside in-list. If the adjustment is impossible, exception will be raised
Implemented in App::PropertyXLinkSubList, App::PropertyXLink, App::PropertyLinkSubList, App::PropertyLinkSub, App::PropertyLinkList, App::PropertyLink, and App::PropertyExpressionEngine.
breakLink()
virtual void App::PropertyLinkBase::breakLink (App::DocumentObject * obj, bool clear) pure virtual
Called to reset this link property
Parameters
obj reset link property if it is linked to this object
clear if true, then also reset property if the owner of this property is obj
See also
breakLinks()
Implemented in App::PropertyXLinkContainer, App::PropertyXLinkSubList, App::PropertyLinkSubList, App::PropertyLinkSub, App::PropertyLinkList, App::PropertyLink, and Spreadsheet::PropertySheet.
Referenced by breakLinks().
breakLinks()
void PropertyLinkBase::breakLinks (App::DocumentObject * link, const std::vector< App::DocumentObject * > & objs, bool clear) static
Helper function for breaking link properties
Parameters
link reset link property if it is linked to this object
objs the objects to check for the link properties
clear if true, then also reset property if the owner of the link property is link
App::Document::breakDependency() calls this function to break the link property
Definition at line 3715 of file PropertyLinks.cpp.
References breakLink(), App::DocInfo::breakLinks(), Path.Op.Gui.Selection::clear(), App::ExtensionContainer::getPropertyList(), and replaceobj::objs.
Referenced by App::Document::breakDependency().
checkLabelReferences()
void PropertyLinkBase::checkLabelReferences (const std::vector< std::string > & subs, bool reset = true)
Check subnames for label registration
Parameters
subs subname references
reset if true, then calls unregisterLabelReference() before registering
Check the give subname references and extract any label reference inside (by calling getLabelReferences()), and register them.
Definition at line 176 of file PropertyLinks.cpp.
References getLabelReferences(), App::ExpressionParser::labels, Path.Post.scripts.opensbp_post::move(), registerLabelReferences(), importers.importIFCmulticore::subs, and unregisterLabelReferences().
Referenced by App::PropertyLinkSubList::addValue(), App::PropertyXLink::setSubValues(), App::PropertyLinkSubList::setValue(), and App::PropertyLinkSubList::setValues().
checkRestore()
virtual int App::PropertyLinkBase::checkRestore (std::string * msg = nullptr) const inline virtual
Test if the link is restored unchanged
Parameters
msg optional error message
Returns
For external linked object, return 2 in case the link is missing, and 1 if the time stamp has changed.
Reimplemented in App::PropertyXLinkContainer, App::PropertyXLinkSubList, and App::PropertyXLink.
Definition at line 179 of file PropertyLinks.h.
References Path.Op.Surface::msg.
CopyOnImportExternal()
virtual Property* App::PropertyLinkBase::CopyOnImportExternal (const std::map< std::string, std::string > & nameMap) const inline virtual
Return a copy of the property if any changes caused by importing external linked object
Parameters
nameMap a map from the original external object name to the imported new object name
Returns
Returns a copy of the property with the updated link reference if affected. The copy will later be assgiend to this property by calling its Paste().
Reimplemented in App::PropertyXLinkSubList, App::PropertyXLink, App::PropertyLinkSubList, App::PropertyLinkSub, Spreadsheet::PropertySheet, and App::PropertyExpressionEngine.
Definition at line 257 of file PropertyLinks.h.
CopyOnLabelChange()
virtual Property* App::PropertyLinkBase::CopyOnLabelChange (App::DocumentObject * obj, const std::string & ref, const char * newLabel) const inline virtual
Update object label reference in this property
Parameters
obj the object owner of the changing label
ref subname reference to old label
newLabel the future new label
Returns
Returns a copy of the property if its link reference is affected. The copy will later be assgiend to this property by calling its Paste().
Reimplemented in App::PropertyXLinkSubList, App::PropertyXLink, App::PropertyLinkSubList, App::PropertyLinkSub, Spreadsheet::PropertySheet, and App::PropertyExpressionEngine.
Definition at line 273 of file PropertyLinks.h.
CopyOnLinkReplace()
virtual Property* App::PropertyLinkBase::CopyOnLinkReplace (const App::DocumentObject * parent, App::DocumentObject * oldObj, App::DocumentObject * newObj) const pure virtual
Return a copy of the property if the link replacement affects this property
Parameters
owner the parent object whose link property is to be replace. Note that The parent may not be the container of this property. Link sub property can use this opportunity to adjust its relative links.
oldObj object to be replaced
newObj object to replace with
Returns
Return a copy of the property that is adjusted for the link replacement operation.
Implemented in App::PropertyXLinkSubList, App::PropertyXLink, App::PropertyLinkSubList, App::PropertyLinkSub, App::PropertyLinkList, App::PropertyLink, Spreadsheet::PropertySheet, and App::PropertyExpressionEngine.
exportSubName()
const char * PropertyLinkBase::exportSubName (std::string & output, const App::DocumentObject * obj, const char * subname, bool first_obj = false) static
Helper function to export a subname reference
Parameters
output output subname if the subname is modified
obj linked object
sub input subname reference
first_obj if true, then the first object referenced in subname is obtained by searching the owner document of obj, otherwise the subname search among obj's sub-objects.
Returns
Return output.c_str() if the subname is modified for exporting otherwise, return the input subname
See also
importSubName(), restoreLabelReference()
The function go through the input subname reference and changes any sub object references inside for exporting. If the sub object is referenced by its internal object name, then the reference is changed from 'objName' to 'objName@docName'. If referenced by label, then it will be changed to 'objName@docName@' instead. importSubName() and restoreLabelReference() can be used together to restore the reference during import.
Definition at line 1630 of file PropertyLinks.cpp.
References toolbit-attributes::doc, dot(), FC_ERR, FC_WARN, App::GetApplication(), App::Application::getDocument(), App::DocumentObject::getDocument(), App::DocumentObject::getExportName(), App::DocumentObject::getNameInDocument(), App::DocumentObject::getSubObject(), App::PropertyString::getValue(), App::DocumentObject::isAttachedToDocument(), App::DocumentObject::isExporting(), App::DocumentObject::Label, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by App::PropertyLinkSub::Save(), App::PropertyLinkSubList::Save(), App::PropertyXLink::Save(), and App::ObjectIdentifier::toPersistentString().
getElementReferences()
const std::unordered_set< PropertyLinkBase * > & PropertyLinkBase::getElementReferences (DocumentObject * feature) static
Obtain link properties that contain element references to a given object.
Definition at line 260 of file PropertyLinks.cpp.
References _ElementRefMap.
Referenced by Part::Feature::onBeforeChange().
getLabelReferences()
void PropertyLinkBase::getLabelReferences (std::vector< std::string > & labels, const char * subname) static
Helper function to extract labels from a subname reference
Parameters
labels output vector of extracted labels
subname subname reference
See also
registerLabelReferences()
This function is used to extract label from subname reference for registering of label changes.
Definition at line 150 of file PropertyLinks.cpp.
References dot(), and importers.importIFCmulticore::subs.
Referenced by checkLabelReferences(), and App::ObjectIdentifier::getDepLabels().
getLinkedElements()
void App::PropertyLinkBase::getLinkedElements (std::map< App::DocumentObject *, std::vector< std::string >> & elements, bool newStyle = true, bool all = false) const inline
Helper function to return a map of linked object and its subname references.
Definition at line 299 of file PropertyLinks.h.
References SplineSurface::i, and importers.importIFCmulticore::subs.
getLinkedObjects()
template<class T > void App::PropertyLinkBase::getLinkedObjects (T & inserter, bool all = false) const inline
Helper function to return linked objects using an std::inserter.
Definition at line 291 of file PropertyLinks.h.
getLinks()
virtual void App::PropertyLinkBase::getLinks (std::vector< App::DocumentObject * > & objs, bool all = false, std::vector< std::string > * subs = nullptr, bool newStyle = true) const pure virtual
Obtain the linked objects
Parameters
objs hold the returned linked objects on output
all if true, then return all the linked object regardless of this LinkScope. If false, then return only if the LinkScope is not hidden.
sub if given, then return subname references.
newStyle whether to return new or old style subname reference
Implemented in App::PropertyXLinkContainer, App::PropertyXLinkSubList, App::PropertyXLink, App::PropertyLinkSubList, App::PropertyLinkSub, App::PropertyLinkList, and App::PropertyLink.
Referenced by Gui::Dialog::DlgPropertyLink::getLinksFromProperty(), and isSame().
getLinksTo()
virtual void App::PropertyLinkBase::getLinksTo (std::vector< App::ObjectIdentifier > & identifiers, App::DocumentObject * obj, const char * subname = nullptr, bool all = false) const pure virtual
Obtain identifiers from this link property that link to a given object
Parameters
identifiers holds the returned identifier to reference the given object
obj the referenced object
subname optional subname reference
all if true, then return all the references regardless of this LinkScope. If false, then return only if the LinkScope is not hidden.
Implemented in App::PropertyXLinkSubList, App::PropertyXLink, App::PropertyLinkSubList, App::PropertyLinkSub, App::PropertyLinkList, App::PropertyLink, App::PropertyExpressionEngine, and Spreadsheet::PropertySheet.
hasSetValue()
void PropertyLinkBase::hasSetValue () override protected virtual
Gets called by all setValue() methods after the value has changed.
Reimplemented from App::Property.
Reimplemented in App::PropertyXLink, and Spreadsheet::PropertySheet.
Definition at line 88 of file PropertyLinks.cpp.
References App::Property::getContainer(), and App::Property::hasSetValue().
Referenced by App::PropertyLinkSubList::addValue(), App::PropertyXLinkContainer::breakLink(), App::PropertyXLinkSubList::hasSetChildValue(), App::PropertyExpressionEngine::hasSetValue(), App::PropertyXLink::hasSetValue(), App::PropertyXLinkSubList::Paste(), App::PropertyLink::setValue(), App::PropertyLinkSubList::setValue(), App::PropertyLinkSubList::setValues(), App::PropertyLinkSub::updateElementReference(), and App::PropertyLinkSubList::updateElementReference().
importSubName()
std::string PropertyLinkBase::importSubName (Base::XMLReader & reader, const char * sub, bool & restoreLabel) static
Helper function to import a subname reference
Parameters
reader the import reader
sub input subname reference
restoreLabel output indicate whether post process is required after restore.
See also
exportSubName(), restoreLabelReference()
Returns
return either an updated subname reference or the input reference if no change. If restoreLabel is set to true on output, it means there are some label reference changes that must be corrected after restore, by calling restoreLabelReference() in property's afterRestore().
Definition at line 1608 of file PropertyLinks.cpp.
References src.Mod.AddonManager.NetworkManager::count, dot(), TechDrawTools.TaskFillTemplateFields::reader, and Path.Post.scripts.refactored_centroid_post::str.
Referenced by App::ObjectIdentifier::String::checkImport(), App::PropertyLinkSub::Restore(), App::PropertyLinkSubList::Restore(), and App::PropertyXLink::Restore().
isSame()
bool PropertyLinkBase::isSame (const Property & other) const override virtual
Compare if this property has the same content as the given one.
Reimplemented from App::Property.
Reimplemented in App::PropertyListsT< DocumentObject *, std::vector< DocumentObject * >, PropertyLinkListBase >.
Definition at line 97 of file PropertyLinks.cpp.
References Base::Persistence::getClassTypeId(), getLinks(), App::ScopedLink::getScope(), Base::BaseClass::isDerivedFrom(), and importers.importIFCmulticore::subs.
linkedElements()
std::map<App::DocumentObject*, std::vector<std::string> > App::PropertyLinkBase::linkedElements (bool newStyle = true, bool all = false) const inline
Helper function to return a map of linked object and its subname references.
Definition at line 314 of file PropertyLinks.h.
linkedObjects()
std::vector<App::DocumentObject*> App::PropertyLinkBase::linkedObjects (bool all = false) const inline
Helper function to return all linked objects of this property.
Definition at line 282 of file PropertyLinks.h.
referenceChanged()
virtual bool App::PropertyLinkBase::referenceChanged () const inline virtual
Test if the element reference has changed after restore.
Reimplemented in App::PropertyXLinkSubList, App::PropertyXLink, App::PropertyLinkSubList, App::PropertyLinkSub, Spreadsheet::PropertySheet, and App::PropertyExpressionEngine.
Definition at line 167 of file PropertyLinks.h.
registerLabelReferences()
void PropertyLinkBase::registerLabelReferences (std::vector< std::string > && labels, bool reset = true)
Register label reference for future object relabel update
Parameters
labels labels to be registered
reset if true, then calls unregisterLabelReference() before registering
Definition at line 163 of file PropertyLinks.cpp.
References _LabelMap, App::ExpressionParser::labels, Path.Post.scripts.opensbp_post::move(), and unregisterLabelReferences().
Referenced by checkLabelReferences(), and Spreadsheet::PropertySheet::hasSetValue().
restoreLabelReference()
void PropertyLinkBase::restoreLabelReference (const App::DocumentObject * obj, std::string & sub, ShadowSub * shadow = nullptr) static
Helper function to restore label references during import
Parameters
obj linked object
sub subname reference
shadow optional shadow subname reference
See also
exportSubName(), importSubName()
When exporting and importing (i.e. copy and paste) objects into the same document, the new object must be renamed, both the internal name and the label. Therefore, the link reference of the new objects must be corrected accordingly. The basic idea is that when exporting object, all object name references are changed to 'objName@docName', and label references are changed to 'objName@docName@'. During import, MergeDocument will maintain a map from objName@docName to object's new name. Object name reference can be restored on spot by consulting the map, while label reference will be restored later in property's afterRestore() function, which calls this function to do the string parsing.
Definition at line 354 of file PropertyLinks.cpp.
References src.Mod.AddonManager.NetworkManager::count, dot(), FC_ERR, App::DocumentObject::getFullName(), App::PropertyString::getStrValue(), App::DocumentObject::getSubObject(), App::DocumentObject::Label, App::ElementNamePair::newName, and App::ElementNamePair::oldName.
Referenced by App::PropertyLinkSub::afterRestore(), App::PropertyLinkSubList::afterRestore(), App::PropertyXLink::afterRestore(), and App::ObjectIdentifier::String::checkImport().
setAllowExternal()
void PropertyLinkBase::setAllowExternal (bool allow)
Enable/disable temporary holding external object without throwing exception
Warning, non-PropertyXLink related property does not have internal tracking of external objects, therefore the link will not by auto broken when external document is closed. Only use this for temporary case, or if you handle signalDeleteDocument yourself, or use one of the PropertyXLink related property.
Definition at line 73 of file PropertyLinks.cpp.
References LinkAllowExternal, and setFlag().
Referenced by App::PropertyXLinkSubList::setPyObject(), and App::PropertyXLinkList::setPyObject().
setAllowPartial()
virtual void App::PropertyLinkBase::setAllowPartial (bool enable) inline virtual
Reimplemented in App::PropertyXLinkSubList, and App::PropertyXLink.
Definition at line 607 of file PropertyLinks.h.
setFlag()
void App::PropertyLinkBase::setFlag (int flag, bool value = true) inline protected
Definition at line 624 of file PropertyLinks.h.
Referenced by App::PropertyLinkSub::afterRestore(), App::PropertyLinkSubList::afterRestore(), App::PropertyXLink::afterRestore(), App::PropertyXLink::Paste(), App::PropertyLinkSub::Restore(), App::PropertyLinkSubList::Restore(), App::PropertyXLink::Restore(), App::PropertyXLinkSubList::Restore(), App::PropertyXLink::restoreLink(), setAllowExternal(), App::PropertyXLink::setAllowPartial(), App::PropertyXLinkSubList::setAllowPartial(), setReturnNewElement(), and setSilentRestore().
setReturnNewElement()
void PropertyLinkBase::setReturnNewElement (bool enable)
Definition at line 83 of file PropertyLinks.cpp.
References LinkNewElement, and setFlag().
setSilentRestore()
void PropertyLinkBase::setSilentRestore (bool enable)
Definition at line 78 of file PropertyLinks.cpp.
References LinkSilentRestore, and setFlag().
testFlag()
bool App::PropertyLinkBase::testFlag (int flag) const inline
Definition at line 602 of file PropertyLinks.h.
Referenced by App::PropertyXLinkSubList::addValue(), adjustLinkSubs(), App::PropertyLinkSub::afterRestore(), App::PropertyLinkSubList::afterRestore(), App::PropertyXLink::afterRestore(), App::PropertyXLink::checkRestore(), App::PropertyXLinkSubList::Copy(), App::PropertyLinkSub::getPyObject(), Spreadsheet::PropertySheet::hasSetValue(), App::PropertyXLinkSubList::Paste(), App::PropertyXLink::Save(), App::PropertyXLinkSubList::Save(), App::PropertyXLinkSubList::set1Value(), App::PropertyLink::setValue(), App::PropertyLinkList::setValues(), App::PropertyXLinkSubList::setValues(), App::PropertyXLinkContainer::updateDeps(), and App::PropertyXLinkSubList::upgrade().
tryImport()
App::DocumentObject * PropertyLinkBase::tryImport (const App::Document * doc, const App::DocumentObject * obj, const std::map< std::string, std::string > & nameMap) static
Helper function for link import operation
Parameters
doc owner document of the imported objects
obj the linked object
nameMap a name map from source object to its imported counter part
Returns
Return the imported object if found, or the input obj if no change.
See also
tryImportSubNames
This function searches for the name map and tries to find the imported object from the given source object.
Definition at line 1716 of file PropertyLinks.cpp.
References toolbit-attributes::doc, FC_THROWM, App::DocumentObject::getExportName(), and App::DocumentObject::isAttachedToDocument().
Referenced by App::PropertyLinkSub::CopyOnImportExternal(), App::PropertyLinkSubList::CopyOnImportExternal(), and App::PropertyXLink::CopyOnImportExternal().
tryImportSubName()
std::string PropertyLinkBase::tryImportSubName (const App::DocumentObject * obj, const char * sub, const App::Document * doc, const std::map< std::string, std::string > & nameMap) static
Helper function for link import operation
Parameters
obj the linked object
sub subname reference
doc importing document
nameMap a name map from source object to its imported counter part
Returns
Return a changed subname reference, or empty string if no change.
Link import operation will go through all link property and imports all externally linked object. After import, the link property must be changed to point to the newly imported objects, which should happen inside the API CopyOnImportExternal(). This function helps to rewrite subname reference to point to the correct sub objects that are imported.
Definition at line 1732 of file PropertyLinks.cpp.
References toolbit-attributes::doc, dot(), FC_ERR, FC_THROWM, App::DocumentObject::getFullName(), App::DocumentObject::getSubObject(), and App::DocumentObject::isAttachedToDocument().
Referenced by App::PropertyLinkSub::CopyOnImportExternal(), App::PropertyLinkSubList::CopyOnImportExternal(), App::PropertyXLink::CopyOnImportExternal(), and App::Expression::importSubNames().
tryReplaceLink()
std::pair< DocumentObject *, std::string > PropertyLinkBase::tryReplaceLink (const App::PropertyContainer * owner, App::DocumentObject * obj, const App::DocumentObject * parent, App::DocumentObject * oldObj, App::DocumentObject * newObj, const char * sub = nullptr) static
Helper functions.
Helper function to check and replace a link
Parameters
owner the owner of the current property
obj the current linked object
parent the parent of the changing link property, may or may not be equal to owner
oldObj the object to be replaced
newObj the object to replace with
sub optional the current subname reference
Returns
Returns a pair(obj,subname). If no replacement is found, pair.first will be NULL
Say a group has one of its child object replaced with another. Any existing link sub reference that refer to the original child object through the group will be broken. This helper function is used to check and correct any link sub reference.
Definition at line 548 of file PropertyLinks.cpp.
References SCL.SimpleDataTypes::c, App::DocumentObject::getNameInDocument(), App::DocumentObject::getSubObject(), App::PropertyString::getValue(), App::DocumentObject::Label, Path.Post.scripts.opensbp_post::move(), Init::parent, and RobotExample::pos.
Referenced by App::PropertyLink::CopyOnLinkReplace(), App::PropertyLinkList::CopyOnLinkReplace(), App::PropertyLinkSubList::CopyOnLinkReplace(), App::ObjectIdentifier::replaceObject(), and tryReplaceLinkSubs().
tryReplaceLinkSubs()
std::pair< DocumentObject *, std::vector< std::string > > PropertyLinkBase::tryReplaceLinkSubs (const App::PropertyContainer * owner, App::DocumentObject * obj, const App::DocumentObject * parent, App::DocumentObject * oldObj, App::DocumentObject * newObj, const std::vector< std::string > & subs) static
Helper function to check and replace a link with multiple subname references
Parameters
owner the owner of the current property
obj the current linked object
parent the parent of the changing link property, may or may not be equal to owner
oldObj the object to be replaced
newObj the object to replace with
subs the current subname references
Returns
Returns the a pair(obj,subs). If no replacement is found, pair.first will be NULL
See also
tryReplaceLink()
Definition at line 623 of file PropertyLinks.cpp.
References Path.Post.scripts.opensbp_post::move(), Init::parent, importers.importIFCmulticore::subs, and tryReplaceLink().
Referenced by App::PropertyLinkSub::CopyOnLinkReplace(), and App::PropertyXLink::CopyOnLinkReplace().
unregisterElementReference()
void PropertyLinkBase::unregisterElementReference ()
Clear internal element reference registration.
Definition at line 122 of file PropertyLinks.cpp.
References _ElementRefMap.
Referenced by Spreadsheet::PropertySheet::hasSetValue(), Spreadsheet::PropertySheet::onContainerRestored(), App::PropertyLinkSub::onContainerRestored(), App::PropertyLinkSubList::onContainerRestored(), Spreadsheet::PropertySheet::updateElementReference(), App::PropertyLinkSubList::updateElementReference(), and updateLinkReference().
unregisterLabelReferences()
void PropertyLinkBase::unregisterLabelReferences ()
Clear internal label references registration.
Definition at line 136 of file PropertyLinks.cpp.
References _LabelMap.
Referenced by checkLabelReferences(), and registerLabelReferences().
updateElementReference()
virtual void App::PropertyLinkBase::updateElementReference (App::DocumentObject * feature, bool reverse = false, bool notify = false) inline virtual
Link type property interface APIs These APIs are moved here so that any type of property can have the property link behavior, e.g. the PropertyExpressionEngine Called to update the element reference of this link property
See also
_updateElementReference()
Reimplemented in App::PropertyXLinkSubList, App::PropertyXLink, App::PropertyLinkSubList, App::PropertyLinkSub, Spreadsheet::PropertySheet, and App::PropertyExpressionEngine.
Definition at line 134 of file PropertyLinks.h.
References femsolver.signal::notify().
updateElementReferences()
void PropertyLinkBase::updateElementReferences (DocumentObject * feature, bool reverse = false) static
Update all element references in all link properties of feature.
Definition at line 272 of file PropertyLinks.cpp.
References _ElementRefMap, SCL.SimpleDataTypes::e, FC_ERR, App::DocumentObject::getNameInDocument(), and propertyName().
Referenced by App::GeoFeature::updateElementReference().
updateLabelReference()
std::string PropertyLinkBase::updateLabelReference (const App::DocumentObject * linked, const char * subname, App::DocumentObject * obj, const std::string & ref, const char * newLabel) static
Helper function to update subname reference on label change
Parameters
linked linked object
subname subname reference
obj the object that owns the label
ref label reference in the format of '$<old_label>.', which is the format used in subname reference for label reference. This parameter is provided for easy search of label reference.
newLabel new label
Returns
Returns an updated subname reference, or empty string if no change.
This function helps to update subname reference on label change. It is usually called inside CopyOnLabelChange(), the API for handling label change, which is called just before label change. In other word, when called, the sub object can still be reached using the original label references, but not the new labels.
Definition at line 189 of file PropertyLinks.cpp.
References App::DocumentObject::isAttachedToDocument(), Init::parent, and RobotExample::pos.
Referenced by App::PropertyLinkSub::CopyOnLabelChange(), App::PropertyLinkSubList::CopyOnLabelChange(), App::PropertyXLink::CopyOnLabelChange(), and App::ObjectIdentifier::updateLabelReference().
updateLabelReferences()
std::vector< std::pair< Property *, std::unique_ptr< Property > > > PropertyLinkBase::updateLabelReferences (App::DocumentObject * obj, const char * newLabel) static
Helper function to collect changed property when an object re-label
Parameters
obj the object that owns the label
newLabel the new label
Returns
return a map from the affected property to a copy of it with updated subname references
Definition at line 217 of file PropertyLinks.cpp.
References _LabelMap, App::PropertyString::getStrValue(), App::PropertyString::getValue(), App::DocumentObject::isAttachedToDocument(), App::DocumentObject::Label, and Path.Post.scripts.opensbp_post::move().
Referenced by App::PropertyString::setValue().
Friends And Related Function Documentation
DocInfo
friend class DocInfo friend
Definition at line 121 of file PropertyLinks.h.
Member Data Documentation
_Flags
std::bitset<32> App::PropertyLinkBase::_Flags protected
Definition at line 623 of file PropertyLinks.h.
Referenced by App::PropertyXLink::copyTo(), App::PropertyLinkSub::setSyncSubObject(), App::PropertyLinkSubList::setSyncSubObject(), App::PropertyXLink::setSyncSubObject(), and App::PropertyXLinkSubList::setSyncSubObject().
signalUpdateElementReference
boost::signals2::signal<void(const std::string&, const std::string&)> App::PropertyLinkBase::signalUpdateElementReference
Definition at line 617 of file PropertyLinks.h.
The documentation for this class was generated from the following files:
PropertyLinks.h
PropertyLinks.cpp