FreeCAD: ifc2x3.ifcsoundvalue Class Reference
ifc2x3.ifcsoundvalue Class Reference
Public Member Functions
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, soundleveltimeseries, frequency, soundlevelsinglevalue)
def soundleveltimeseries ()
def frequency ()
def soundlevelsinglevalue ()
Public Member Functions inherited from ifc2x3.ifcpropertysetdefinition
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description)
def propertydefinitionof ()
def definestype ()
Public Member Functions inherited from ifc2x3.ifcpropertydefinition
def hasassociations ()
Public Member Functions inherited from ifc2x3.ifcroot
def globalid ()
def ownerhistory ()
def name ()
def description ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
soundleveltimeseries
frequency
soundlevelsinglevalue
Public Attributes inherited from ifc2x3.ifcroot
globalid
ownerhistory
name
description
Detailed Description
Entity ifcsoundvalue definition.
:param soundleveltimeseries
:type soundleveltimeseries:ifctimeseries
:param frequency
:type frequency:ifcfrequencymeasure
:param soundlevelsinglevalue
:type soundlevelsinglevalue:ifcderivedmeasurevalue
Definition at line 18205 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcsoundvalue.__init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, soundleveltimeseries, frequency, soundlevelsinglevalue)
Definition at line 18217 of file ifc2x3.py.
Member Function Documentation
frequency()
def ifc2x3.ifcsoundvalue.frequency ()
Definition at line 18238 of file ifc2x3.py.
References ifc2x3.ifcsoundvalue._frequency, SCL.TypeChecker.check_type(), and ifc2x3.ifcsoundvalue.frequency.
soundlevelsinglevalue()
def ifc2x3.ifcsoundvalue.soundlevelsinglevalue ()
Definition at line 18252 of file ifc2x3.py.
References ifc2x3.ifcsoundvalue._soundlevelsinglevalue, SCL.TypeChecker.check_type(), ifc2x3.ifcderivedmeasurevalue, and ifc2x3.ifcsoundvalue.soundlevelsinglevalue.
soundleveltimeseries()
def ifc2x3.ifcsoundvalue.soundleveltimeseries ()
Definition at line 18224 of file ifc2x3.py.
References ifc2x3.ifcsoundvalue._soundleveltimeseries, SCL.TypeChecker.check_type(), and ifc2x3.ifcsoundvalue.soundleveltimeseries.
Member Data Documentation
frequency
ifc2x3.ifcsoundvalue.frequency
Definition at line 18220 of file ifc2x3.py.
Referenced by ifc2x3.ifcsoundvalue.frequency().
soundlevelsinglevalue
ifc2x3.ifcsoundvalue.soundlevelsinglevalue
Definition at line 18221 of file ifc2x3.py.
Referenced by ifc2x3.ifcsoundvalue.soundlevelsinglevalue().
soundleveltimeseries
ifc2x3.ifcsoundvalue.soundleveltimeseries
Definition at line 18219 of file ifc2x3.py.
Referenced by ifc2x3.ifcsoundvalue.soundleveltimeseries().
The documentation for this class was generated from the following file:
ifc2x3.py