FreeCAD: GCS Namespace Reference
GCS Namespace Reference
Classes
class Arc
class ArcOfEllipse
class ArcOfHyperbola
class ArcOfParabola
class BSpline
class Circle
class Constraint
class ConstraintAngleViaPoint
class ConstraintAngleViaPointAndParam
class ConstraintAngleViaPointAndTwoParams
class ConstraintAngleViaTwoPoints
class ConstraintArcLength
class ConstraintC2CDistance
class ConstraintC2LDistance
class ConstraintCenterOfGravity
class ConstraintCurveValue
class ConstraintDifference
class ConstraintEllipseTangentLine
class ConstraintEqual
class ConstraintEqualFocalDistance
class ConstraintEqualLineLength
class ConstraintEqualMajorAxesConic
class ConstraintInternalAlignmentPoint2Ellipse
class ConstraintInternalAlignmentPoint2Hyperbola
class ConstraintL2LAngle
class ConstraintMidpointOnLine
class ConstraintP2CDistance
class ConstraintP2LDistance
class ConstraintP2PAngle
class ConstraintP2PDistance
class ConstraintParallel
class ConstraintPerpendicular
class ConstraintPointOnBSpline
class ConstraintPointOnEllipse
class ConstraintPointOnHyperbola
class ConstraintPointOnLine
class ConstraintPointOnParabola
class ConstraintPointOnPerpBisector
class ConstraintSlopeAtBSplineKnot
class ConstraintSnell
class ConstraintTangentCircumf
class ConstraintWeightedLinearCombination
class Curve
A base class for all curve-based objects (line, circle/arc, ellipse/arc).
class DeriVector2
class Ellipse
class Hyperbola
class Line
class MajorRadiusConic
class Parabola
class Point
class SolverReportingManager
class SubSystem
class System
Typedefs
using Graph = boost::adjacency_list< boost::vecS, boost::vecS, boost::undirectedS >
using VEC_P = std::vector< Point >
using VEC_pD = std::vector< double * >
using VEC_D = std::vector< double >
using VEC_I = std::vector< int >
using MAP_pD_pD = std::map< double *, double * >
using MAP_pD_D = std::map< double *, double >
using MAP_pD_I = std::map< double *, int >
using SET_pD = std::set< double * >
using SET_I = std::set< int >
Enumerations
enum ConstraintType {
None = 0, Equal = 1, Difference = 2, P2PDistance = 3,
P2PAngle = 4, P2LDistance = 5, PointOnLine = 6, PointOnPerpBisector = 7,
Parallel = 8, Perpendicular = 9, L2LAngle = 10, MidpointOnLine = 11,
TangentCircumf = 12, PointOnEllipse = 13, TangentEllipseLine = 14, InternalAlignmentPoint2Ellipse = 15,
EqualMajorAxesConic = 16, EllipticalArcRangeToEndPoints = 17, AngleViaPoint = 18, Snell = 19,
CurveValue = 20, PointOnHyperbola = 21, InternalAlignmentPoint2Hyperbola = 22, PointOnParabola = 23,
EqualFocalDistance = 24, EqualLineLength = 25, CenterOfGravity = 26, WeightedLinearCombination = 27,
SlopeAtBSplineKnot = 28, PointOnBSpline = 29, C2CDistance = 30, C2LDistance = 31,
P2CDistance = 32, AngleViaPointAndParam = 33, AngleViaPointAndTwoParams = 34, AngleViaTwoPoints = 35,
ArcLength = 36
}
enum InternalAlignmentType {
EllipsePositiveMajorX = 0, EllipsePositiveMajorY = 1, EllipseNegativeMajorX = 2, EllipseNegativeMajorY = 3,
EllipsePositiveMinorX = 4, EllipsePositiveMinorY = 5, EllipseNegativeMinorX = 6, EllipseNegativeMinorY = 7,
EllipseFocus2X = 8, EllipseFocus2Y = 9, HyperbolaPositiveMajorX = 10, HyperbolaPositiveMajorY = 11,
HyperbolaNegativeMajorX = 12, HyperbolaNegativeMajorY = 13, HyperbolaPositiveMinorX = 14, HyperbolaPositiveMinorY = 15,
HyperbolaNegativeMinorX = 16, HyperbolaNegativeMinorY = 17
}
enum SolveStatus { Success = 0, Converged = 1, Failed = 2, SuccessfulSolutionInvalid = 3 }
enum Algorithm { BFGS = 0, LevenbergMarquardt = 1, DogLeg = 2 }
enum DogLegGaussStep { FullPivLU = 0, LeastNormFullPivLU = 1, LeastNormLdlt = 2 }
enum QRAlgorithm { EigenDenseQR = 0, EigenSparseQR = 1 }
enum DebugMode { NoDebug = 0, Minimal = 1, IterationLevel = 2 }
enum SpecialTag { DefaultTemporaryConstraint = -1 }
Functions
double lineSearch (SubSystem *subsys, Eigen::VectorXd &xdir)
void free (VEC_pD &doublevec)
void free (std::vector< Constraint * > &constrvec)
void free (std::vector< SubSystem * > &subsysvec)
Variables
static constexpr double pi = boost::math::constants::pi<double>()
static constexpr double pi_2 = pi / 2.0
static constexpr double pi_18 = pi / 18.0
Typedef Documentation
Graph
using GCS::Graph = typedef boost::adjacency_list<boost::vecS, boost::vecS, boost::undirectedS>
Definition at line 452 of file GCS.cpp.
MAP_pD_D
using GCS::MAP_pD_D = typedef std::map<double*, double>
Definition at line 57 of file Util.h.
MAP_pD_I
using GCS::MAP_pD_I = typedef std::map<double*, int>
Definition at line 58 of file Util.h.
MAP_pD_pD
using GCS::MAP_pD_pD = typedef std::map<double*, double*>
Definition at line 56 of file Util.h.
SET_I
using GCS::SET_I = typedef std::set<int>
Definition at line 60 of file Util.h.
SET_pD
using GCS::SET_pD = typedef std::set<double*>
Definition at line 59 of file Util.h.
VEC_D
using GCS::VEC_D = typedef std::vector<double>
Definition at line 54 of file Util.h.
VEC_I
using GCS::VEC_I = typedef std::vector<int>
Definition at line 55 of file Util.h.
VEC_P
using GCS::VEC_P = typedef std::vector<Point>
Definition at line 75 of file Geo.h.
VEC_pD
using GCS::VEC_pD = typedef std::vector<double*>
Definition at line 53 of file Util.h.
Enumeration Type Documentation
Algorithm
enum GCS::Algorithm
Enumerator
BFGS
LevenbergMarquardt
DogLeg
Definition at line 61 of file GCS.h.
ConstraintType
enum GCS::ConstraintType
Enumerator
None
Equal
Difference
P2PDistance
P2PAngle
P2LDistance
PointOnLine
PointOnPerpBisector
Parallel
Perpendicular
L2LAngle
MidpointOnLine
TangentCircumf
PointOnEllipse
TangentEllipseLine
InternalAlignmentPoint2Ellipse
EqualMajorAxesConic
EllipticalArcRangeToEndPoints
AngleViaPoint
Snell
CurveValue
PointOnHyperbola
InternalAlignmentPoint2Hyperbola
PointOnParabola
EqualFocalDistance
EqualLineLength
CenterOfGravity
WeightedLinearCombination
SlopeAtBSplineKnot
PointOnBSpline
C2CDistance
C2LDistance
P2CDistance
AngleViaPointAndParam
AngleViaPointAndTwoParams
AngleViaTwoPoints
ArcLength
Definition at line 47 of file Constraints.h.
DebugMode
enum GCS::DebugMode
Enumerator
NoDebug
Minimal
IterationLevel
Definition at line 81 of file GCS.h.
DogLegGaussStep
enum GCS::DogLegGaussStep
Enumerator
FullPivLU
LeastNormFullPivLU
LeastNormLdlt
Definition at line 68 of file GCS.h.
InternalAlignmentType
enum GCS::InternalAlignmentType
Enumerator
EllipsePositiveMajorX
EllipsePositiveMajorY
EllipseNegativeMajorX
EllipseNegativeMajorY
EllipsePositiveMinorX
EllipsePositiveMinorY
EllipseNegativeMinorX
EllipseNegativeMinorY
EllipseFocus2X
EllipseFocus2Y
HyperbolaPositiveMajorX
HyperbolaPositiveMajorY
HyperbolaNegativeMajorX
HyperbolaNegativeMajorY
HyperbolaPositiveMinorX
HyperbolaPositiveMinorY
HyperbolaNegativeMinorX
HyperbolaNegativeMinorY
Definition at line 88 of file Constraints.h.
QRAlgorithm
enum GCS::QRAlgorithm
Enumerator
EigenDenseQR
EigenSparseQR
Definition at line 75 of file GCS.h.
SolveStatus
enum GCS::SolveStatus
Enumerator
Success
Converged
Failed
SuccessfulSolutionInvalid
Definition at line 52 of file GCS.h.
SpecialTag
enum GCS::SpecialTag
Enumerator
DefaultTemporaryConstraint
Definition at line 100 of file GCS.h.
Function Documentation
free() [1/3]
void GCS::free (std::vector< Constraint * > & constrvec)
Definition at line 5921 of file GCS.cpp.
References Difference, Equal, L2LAngle, MidpointOnLine, None, P2LDistance, P2PAngle, P2PDistance, Parallel, Perpendicular, and PointOnLine.
free() [2/3]
void GCS::free (std::vector< SubSystem * > & subsysvec)
Definition at line 5966 of file GCS.cpp.
free() [3/3]
void GCS::free (VEC_pD & doublevec)
Definition at line 5911 of file GCS.cpp.
Referenced by Cloud::BuildHeaderAmzS3v2(), Cloud::BuildHeaderAmzS3v4(), GCS::System::clear(), Cloud::ComputeDigestAmzS3v4(), StackWalkerInternal::GetModuleInfo(), PartGui::SoBrepFaceSet::VBO::render(), and MillSim::TextureLoader::~TextureLoader().
lineSearch()
double GCS::lineSearch (SubSystem * subsys, Eigen::VectorXd & xdir)
Definition at line 5833 of file GCS.cpp.
References GCS::SubSystem::error(), GCS::SubSystem::getParams(), GCS::SubSystem::maxStep(), GCS::SubSystem::setParams(), and MovieTool::x.
Variable Documentation
pi
constexpr double GCS::pi = boost::math::constants::pi<double>() static constexpr
Definition at line 76 of file Geo.h.
Referenced by GCS::System::addConstraintPerpendicularArc2Line(), and GCS::System::addConstraintPerpendicularLine2Arc().
pi_18
constexpr double GCS::pi_18 = pi / 18.0 static constexpr
Definition at line 78 of file Geo.h.
Referenced by GCS::ConstraintP2PAngle::maxStep(), and GCS::ConstraintL2LAngle::maxStep().
pi_2
constexpr double GCS::pi_2 = pi / 2.0 static constexpr
Definition at line 77 of file Geo.h.
Referenced by GCS::System::addConstraintPerpendicularArc2Circle(), and GCS::System::addConstraintPerpendicularCircle2Arc().