FreeCAD: AppSpreadsheetGui.cpp File Reference
AppSpreadsheetGui.cpp File Reference
#include "PreCompiled.h"
#include <App/Application.h>
#include <App/Document.h>
#include <Base/Console.h>
#include <Base/Exception.h>
#include <Base/FileInfo.h>
#include <Base/Interpreter.h>
#include <Gui/Application.h>
#include <Gui/Language/Translator.h>
#include <Gui/MainWindow.h>
#include <Gui/WidgetFactory.h>
#include <Mod/Spreadsheet/App/Sheet.h>
#include "DlgSettingsImp.h"
#include "SheetTableViewAccessibleInterface.h"
#include "ViewProviderSpreadsheet.h"
#include "Workbench.h"
Classes
class SpreadsheetGui::Module
Namespaces
SpreadsheetGui
Functions
void CreateSpreadsheetCommands ()
void loadSpreadsheetResource ()
PyObject * SpreadsheetGui::initModule ()
PyMOD_INIT_FUNC (SpreadsheetGui)
Function Documentation
CreateSpreadsheetCommands()
void CreateSpreadsheetCommands ()
Definition at line 974 of file Mod/Spreadsheet/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
loadSpreadsheetResource()
void loadSpreadsheetResource ()
Definition at line 46 of file AppSpreadsheetGui.cpp.
References Gui::Translator::instance(), and Gui::Translator::refresh().
Referenced by PyMOD_INIT_FUNC().
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (SpreadsheetGui)
Definition at line 127 of file AppSpreadsheetGui.cpp.
References Base::Console(), CreateSpreadsheetCommands(), SpreadsheetGui::SheetTableViewAccessibleInterface::ifactory(), SIM::Coin3D::Quarter::Quarter::init(), Base::Persistence::init(), Base::BaseClass::init(), SpreadsheetGui::SheetViewPy::init_type(), SpreadsheetGui::initModule(), Gui::Application::Instance, loadSpreadsheetResource(), Base::ConsoleSingleton::Log(), mod, PyMOD_Return, and Arch::QT_TRANSLATE_NOOP.