FreeCAD: TechDrawGui::TaskCosmeticCircle Class Reference
TechDrawGui::TaskCosmeticCircle Class Reference
#include <TaskCosmeticCircle.h>
Public Member Functions
TaskCosmeticCircle (TechDraw::DrawViewPart *partFeat, std::vector< Base::Vector3d > points, bool is3d)
TaskCosmeticCircle (TechDraw::DrawViewPart *partFeat, std::string circleName)
~TaskCosmeticCircle () override
virtual bool accept ()
virtual bool reject ()
void updateTask ()
Protected Slots
void radiusChanged ()
Protected Member Functions
void changeEvent (QEvent *e) override
void setUiPrimary ()
void setUiEdit ()
void createCosmeticCircle ()
void updateCosmeticCircle ()
Detailed Description
Definition at line 52 of file TaskCosmeticCircle.h.
Constructor & Destructor Documentation
TaskCosmeticCircle() [1/2]
TaskCosmeticCircle::TaskCosmeticCircle (TechDraw::DrawViewPart * partFeat, std::vector< Base::Vector3d > points, bool is3d)
Definition at line 79 of file TaskCosmeticCircle.cpp.
References setUiPrimary().
TaskCosmeticCircle() [2/2]
TaskCosmeticCircle::TaskCosmeticCircle (TechDraw::DrawViewPart * partFeat, std::string circleName)
Definition at line 52 of file TaskCosmeticCircle.cpp.
References draftgeoutils.intersections::connect(), Base::Console(), Base::ConsoleSingleton::Error(), TechDraw::CosmeticExtension::getCosmeticEdgeBySelection(), radiusChanged(), and setUiEdit().
~TaskCosmeticCircle()
TaskCosmeticCircle::~TaskCosmeticCircle () override
Definition at line 96 of file TaskCosmeticCircle.cpp.
Member Function Documentation
accept()
bool TaskCosmeticCircle::accept () virtual
Definition at line 252 of file TaskCosmeticCircle.cpp.
References TechDraw::CosmeticExtension::add1CEToGE(), Gui::Command::commitCommand(), Base::Console(), createCosmeticCircle(), doCommand, Base::ConsoleSingleton::Error(), Gui::Command::Gui, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, TechDraw::CosmeticExtension::refreshCEGeoms(), TechDraw::DrawView::requestPaint(), Gui::Command::updateActive(), and updateCosmeticCircle().
Referenced by TechDrawGui::TaskDlgCosmeticCircle::accept().
changeEvent()
void TaskCosmeticCircle::changeEvent (QEvent * e) override protected
Definition at line 110 of file TaskCosmeticCircle.cpp.
References SCL.SimpleDataTypes::e.
createCosmeticCircle()
void TaskCosmeticCircle::createCosmeticCircle () protected
Definition at line 189 of file TaskCosmeticCircle.cpp.
References TechDraw::CosmeticExtension::addCosmeticEdge(), exportCSG::center(), Gui::Command::commitCommand(), TechDraw::CosmeticExtension::getCosmeticEdge(), TechDraw::DrawViewPart::getCurrentCentroid(), Gui::Command::openCommand(), TechDraw::DrawViewPart::projectPoint(), Arch::QT_TRANSLATE_NOOP, TechDraw::CosmeticEdge::setFormat(), MovieTool::x, and MovieTool::y.
Referenced by accept().
radiusChanged
void TaskCosmeticCircle::radiusChanged () protected slot
Definition at line 179 of file TaskCosmeticCircle.cpp.
References Gui::getMainWindow(), and Path.Op.Surface::msg.
Referenced by TaskCosmeticCircle().
reject()
bool TaskCosmeticCircle::reject () virtual
Definition at line 280 of file TaskCosmeticCircle.cpp.
References doCommand, and Gui::Command::Gui.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and TechDrawGui::TaskDlgCosmeticCircle::reject().
setUiEdit()
void TaskCosmeticCircle::setUiEdit () protected
Definition at line 161 of file TaskCosmeticCircle.cpp.
References TechDraw::CosmeticEdge::m_geometry, TechDraw::CosmeticEdge::permaRadius, TechDraw::CosmeticEdge::permaStart, Base::toDegrees(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by TaskCosmeticCircle().
setUiPrimary()
void TaskCosmeticCircle::setUiPrimary () protected
Definition at line 117 of file TaskCosmeticCircle.cpp.
References TechDraw::DrawUtil::angleWithX(), TechDraw::DrawViewPart::getCurrentCentroid(), TechDraw::DrawView::getScale(), TechDraw::DrawUtil::invertY(), Base::Unit::Length, FreeCADInit::Length, TechDraw::DrawViewPart::projectPoint(), Base::toDegrees(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by TaskCosmeticCircle().
updateCosmeticCircle()
void TaskCosmeticCircle::updateCosmeticCircle () protected
Definition at line 225 of file TaskCosmeticCircle.cpp.
References TechDraw::CosmeticEdge::m_geometry, TechDraw::CosmeticEdge::permaEnd, TechDraw::CosmeticEdge::permaRadius, TechDraw::CosmeticEdge::permaStart, MovieTool::x, and MovieTool::y.
Referenced by accept().
updateTask()
void TaskCosmeticCircle::updateTask ()
Definition at line 103 of file TaskCosmeticCircle.cpp.
The documentation for this class was generated from the following files:
TaskCosmeticCircle.h
TaskCosmeticCircle.cpp