FreeCAD: src.Mod.Show.mTempoVis Namespace Reference
src.Mod.Show.mTempoVis Namespace Reference
Classes
class JUST_SAVE
class MAINSTACK
class TempoVis
Variables
Wrn = lambda msg: App.Console.PrintWarning(msg + "\n")
Err = lambda msg: App.Console.PrintError(msg + "\n")
Log = lambda msg: App.Console.PrintLog(msg + "\n")
int S_EMPTY = 0
int S_ACTIVE = 1
int S_RESTORED = 2
int S_INTERNAL = 3
Variable Documentation
Err
src.Mod.Show.mTempoVis.Err = lambda msg: App.Console.PrintError(msg + "\n")
Definition at line 34 of file mTempoVis.py.
Referenced by src.Mod.Show.mTempoVis.TempoVis.restore(), and src.Mod.Show.mTempoVis.TempoVis.restoreVPProperty().
Log
src.Mod.Show.mTempoVis.Log = lambda msg: App.Console.PrintLog(msg + "\n")
Definition at line 35 of file mTempoVis.py.
S_ACTIVE
int src.Mod.Show.mTempoVis.S_ACTIVE = 1
Definition at line 40 of file mTempoVis.py.
S_EMPTY
int src.Mod.Show.mTempoVis.S_EMPTY = 0
Definition at line 39 of file mTempoVis.py.
S_INTERNAL
int src.Mod.Show.mTempoVis.S_INTERNAL = 3
Definition at line 42 of file mTempoVis.py.
S_RESTORED
int src.Mod.Show.mTempoVis.S_RESTORED = 2
Definition at line 41 of file mTempoVis.py.
Wrn
src.Mod.Show.mTempoVis.Wrn = lambda msg: App.Console.PrintWarning(msg + "\n")
Definition at line 33 of file mTempoVis.py.
Referenced by src.Mod.Show.mTempoVis.TempoVis.activateWorkbench(), and src.Mod.Show.mTempoVis.TempoVis.modifyVPProperty().