FreeCAD: MillSim::SimDisplay Class Reference
MillSim::SimDisplay Class Reference
#include <SimDisplay.h>
Public Member Functions
~SimDisplay ()
void InitGL ()
void CleanGL ()
void CleanFbos ()
void PrepareDisplay (vec3 objCenter)
void PrepareFrameBuffer ()
void StartDepthPass ()
void StartGeometryPass (vec3 objColor, bool invertNormals)
void StartCloserGeometryPass (vec3 objColor)
void RenderLightObject ()
void ScaleViewToStock (StockObject *obj)
void RenderResult (bool recalculate)
void RenderResultStandard ()
void RenderResultSSAO (bool recalculate)
void SetupLinePathPass (int curSegment, bool isHidden)
void TiltEye (float tiltStep)
void RotateEye (float rotStep)
void MoveEye (float x, float z)
void UpdateEyeFactor (float factor)
void UpdateWindowScale ()
void UpdateProjection ()
float GetEyeFactor ()
Public Attributes
bool applySSAO = false
bool updateDisplay = false
float maxFar = 100
bool displayInitiated = false
Protected Member Functions
void InitShaders ()
void CreateDisplayFbos ()
void CreateSsaoFbos ()
void CreateFboQuad ()
void CreateGBufTex (GLenum texUnit, GLint intFormat, GLenum format, GLenum type, GLuint &texid)
void UniformHemisphere (vec3 &randVec)
void UniformCircle (vec3 &randVec)
Protected Attributes
Shader shader3D
Shader shaderInv3D
Shader shaderFlat
Shader shaderSimFbo
Shader shaderGeom
Shader shaderSSAO
Shader shaderSSAOLighting
Shader shaderSSAOBlur
Shader shaderGeomCloser
Shader shaderLinePath
vec3 lightColor = {0.5f, 0.6f, 0.7f}
vec3 lightPos = {20.0f, 20.0f, 10.0f}
vec3 ambientCol = {0.2f, 0.2f, 0.25f}
vec4 pathLineColor = {0.0f, 0.9f, 0.0f, 1.0}
vec3 pathLineColorPassed = {0.9f, 0.3f, 0.3f}
vec3 eye = {0, 100, 40}
vec3 target = {0, 0, 0}
vec3 upvec = {0, 0, 1}
mat4x4 mMatLookAt
StockObject mlightObject
int mWidth
int mHeight
std::mt19937 generator
std::uniform_real_distribution< float > distr01
float mEyeDistance = 30
float mEyeRoration = 0
float mEyeInclination = 3.14159265f / 6
float mEyeStep = 3.14159265f / 36
float mMaxStockDim = 100
float mEyeDistFactor = 0.0f
float mEyeXZFactor = 0.01f
float mEyeXZScale = 0
float mEyeX = 0.0f
float mEyeZ = 0.0f
unsigned int mFbo
unsigned int mFboColTexture
unsigned int mFboPosTexture
unsigned int mFboNormTexture
unsigned int mRboDepthStencil
unsigned int mFboQuadVAO
unsigned int mFboQuadVBO
bool mSsaoValid = false
std::vector< Point3D > mSsaoKernel
unsigned int mSsaoFbo
unsigned int mSsaoBlurFbo
unsigned int mFboSsaoTexture
unsigned int mFboSsaoBlurTexture
unsigned int mFboRandTexture
Detailed Description
Definition at line 62 of file SimDisplay.h.
Constructor & Destructor Documentation
~SimDisplay()
MillSim::SimDisplay::~SimDisplay ()
Definition at line 270 of file SimDisplay.cpp.
Member Function Documentation
CleanFbos()
void MillSim::SimDisplay::CleanFbos ()
Definition at line 295 of file SimDisplay.cpp.
CleanGL()
void MillSim::SimDisplay::CleanGL ()
Definition at line 312 of file SimDisplay.cpp.
Referenced by MillSim::MillSimulation::Clear().
CreateDisplayFbos()
void MillSim::SimDisplay::CreateDisplayFbos () protected
Definition at line 164 of file SimDisplay.cpp.
CreateFboQuad()
void MillSim::SimDisplay::CreateFboQuad () protected
Definition at line 111 of file SimDisplay.cpp.
CreateGBufTex()
void MillSim::SimDisplay::CreateGBufTex (GLenum texUnit, GLint intFormat, GLenum format, GLenum type, GLuint & texid) protected
Definition at line 130 of file SimDisplay.cpp.
CreateSsaoFbos()
void MillSim::SimDisplay::CreateSsaoFbos () protected
Definition at line 207 of file SimDisplay.cpp.
GetEyeFactor()
float MillSim::SimDisplay::GetEyeFactor () inline
Definition at line 87 of file SimDisplay.h.
Referenced by MillSim::MillSimulation::Zoom().
InitGL()
void MillSim::SimDisplay::InitGL ()
Definition at line 275 of file SimDisplay.cpp.
Referenced by MillSim::MillSimulation::InitDisplay().
InitShaders()
void MillSim::SimDisplay::InitShaders () protected
Definition at line 67 of file SimDisplay.cpp.
MoveEye()
void MillSim::SimDisplay::MoveEye (float x, float z)
Definition at line 535 of file SimDisplay.cpp.
Referenced by MillSim::MillSimulation::MouseDrag().
PrepareDisplay()
void MillSim::SimDisplay::PrepareDisplay (vec3 objCenter)
Definition at line 333 of file SimDisplay.cpp.
References MillSim::Shader::Activate(), glBindFramebuffer, glDisable, glEnable, mFbo, mMatLookAt, shaderGeom, MillSim::Shader::UpdateNormalState(), MillSim::Shader::UpdateObjColor(), and MillSim::Shader::UpdateViewMat().
Referenced by MillSim::MillSimulation::Render().
PrepareFrameBuffer()
void MillSim::SimDisplay::PrepareFrameBuffer ()
Definition at line 342 of file SimDisplay.cpp.
Referenced by MillSim::MillSimulation::Render().
RenderLightObject()
void MillSim::SimDisplay::RenderLightObject ()
Definition at line 385 of file SimDisplay.cpp.
References MillSim::Shader::Activate(), glBindFramebuffer, and shaderSSAOLighting.
RenderResult()
void MillSim::SimDisplay::RenderResult (bool recalculate)
Definition at line 403 of file SimDisplay.cpp.
Referenced by MillSim::MillSimulation::Render().
RenderResultSSAO()
void MillSim::SimDisplay::RenderResultSSAO (bool recalculate)
Definition at line 439 of file SimDisplay.cpp.
Referenced by StartCloserGeometryPass().
RenderResultStandard()
void MillSim::SimDisplay::RenderResultStandard ()
Definition at line 413 of file SimDisplay.cpp.
Referenced by StartCloserGeometryPass().
RotateEye()
void MillSim::SimDisplay::RotateEye (float rotStep)
Definition at line 523 of file SimDisplay.cpp.
Referenced by MillSim::MillSimulation::MouseDrag(), and MillSim::MillSimulation::ProcessSim().
ScaleViewToStock()
void MillSim::SimDisplay::ScaleViewToStock (StockObject * obj)
Definition at line 392 of file SimDisplay.cpp.
Referenced by MillSim::MillSimulation::SetArbitraryStock(), and MillSim::MillSimulation::SetBoxStock().
SetupLinePathPass()
void MillSim::SimDisplay::SetupLinePathPass (int curSegment, bool isHidden)
Definition at line 497 of file SimDisplay.cpp.
References mEyeRoration, and PI2.
Referenced by MillSim::MillSimulation::RenderPath().
StartCloserGeometryPass()
void MillSim::SimDisplay::StartCloserGeometryPass (vec3 objColor)
Definition at line 374 of file SimDisplay.cpp.
References applySSAO, mSsaoValid, RenderResultSSAO(), and RenderResultStandard().
StartDepthPass()
void MillSim::SimDisplay::StartDepthPass ()
Definition at line 352 of file SimDisplay.cpp.
Referenced by MillSim::MillSimulation::RenderBaseShape(), and MillSim::MillSimulation::RenderSimulation().
StartGeometryPass()
void MillSim::SimDisplay::StartGeometryPass (vec3 objColor, bool invertNormals)
Definition at line 361 of file SimDisplay.cpp.
Referenced by MillSim::MillSimulation::RenderBaseShape(), MillSim::MillSimulation::RenderSimulation(), and MillSim::MillSimulation::RenderTool().
TiltEye()
void MillSim::SimDisplay::TiltEye (float tiltStep)
Definition at line 512 of file SimDisplay.cpp.
Referenced by MillSim::MillSimulation::MouseDrag().
UniformCircle()
void MillSim::SimDisplay::UniformCircle (vec3 & randVec) protected
Definition at line 155 of file SimDisplay.cpp.
UniformHemisphere()
void MillSim::SimDisplay::UniformHemisphere (vec3 & randVec) protected
Definition at line 145 of file SimDisplay.cpp.
UpdateEyeFactor()
void MillSim::SimDisplay::UpdateEyeFactor (float factor)
Definition at line 554 of file SimDisplay.cpp.
Referenced by MillSim::MillSimulation::Zoom().
UpdateProjection()
void MillSim::SimDisplay::UpdateProjection ()
Definition at line 576 of file SimDisplay.cpp.
UpdateWindowScale()
void MillSim::SimDisplay::UpdateWindowScale ()
Definition at line 565 of file SimDisplay.cpp.
Referenced by MillSim::MillSimulation::UpdateWindowScale().
Member Data Documentation
ambientCol
vec3 MillSim::SimDisplay::ambientCol = {0.2f, 0.2f, 0.25f} protected
Definition at line 115 of file SimDisplay.h.
applySSAO
bool MillSim::SimDisplay::applySSAO = false
Definition at line 93 of file SimDisplay.h.
Referenced by MillSim::MillSimulation::HandleGuiAction(), MillSim::MillSimulation::InitSimulation(), and StartCloserGeometryPass().
displayInitiated
bool MillSim::SimDisplay::displayInitiated = false
Definition at line 96 of file SimDisplay.h.
distr01
std::uniform_real_distribution<float> MillSim::SimDisplay::distr01 protected
Definition at line 130 of file SimDisplay.h.
eye
vec3 MillSim::SimDisplay::eye = {0, 100, 40} protected
Definition at line 119 of file SimDisplay.h.
generator
std::mt19937 MillSim::SimDisplay::generator protected
Definition at line 129 of file SimDisplay.h.
lightColor
vec3 MillSim::SimDisplay::lightColor = {0.5f, 0.6f, 0.7f} protected
Definition at line 113 of file SimDisplay.h.
lightPos
vec3 MillSim::SimDisplay::lightPos = {20.0f, 20.0f, 10.0f} protected
Definition at line 114 of file SimDisplay.h.
maxFar
float MillSim::SimDisplay::maxFar = 100
Definition at line 95 of file SimDisplay.h.
Referenced by MillSim::MillSimulation::InitSimulation().
mEyeDistance
float MillSim::SimDisplay::mEyeDistance = 30 protected
Definition at line 133 of file SimDisplay.h.
mEyeDistFactor
float MillSim::SimDisplay::mEyeDistFactor = 0.0f protected
Definition at line 139 of file SimDisplay.h.
mEyeInclination
float MillSim::SimDisplay::mEyeInclination = 3.14159265f / 6 protected
Definition at line 135 of file SimDisplay.h.
mEyeRoration
float MillSim::SimDisplay::mEyeRoration = 0 protected
Definition at line 134 of file SimDisplay.h.
Referenced by SetupLinePathPass().
mEyeStep
float MillSim::SimDisplay::mEyeStep = 3.14159265f / 36 protected
Definition at line 136 of file SimDisplay.h.
mEyeX
float MillSim::SimDisplay::mEyeX = 0.0f protected
Definition at line 142 of file SimDisplay.h.
mEyeXZFactor
float MillSim::SimDisplay::mEyeXZFactor = 0.01f protected
Definition at line 140 of file SimDisplay.h.
mEyeXZScale
float MillSim::SimDisplay::mEyeXZScale = 0 protected
Definition at line 141 of file SimDisplay.h.
mEyeZ
float MillSim::SimDisplay::mEyeZ = 0.0f protected
Definition at line 143 of file SimDisplay.h.
mFbo
unsigned int MillSim::SimDisplay::mFbo protected
Definition at line 146 of file SimDisplay.h.
Referenced by PrepareDisplay().
mFboColTexture
unsigned int MillSim::SimDisplay::mFboColTexture protected
Definition at line 147 of file SimDisplay.h.
mFboNormTexture
unsigned int MillSim::SimDisplay::mFboNormTexture protected
Definition at line 149 of file SimDisplay.h.
mFboPosTexture
unsigned int MillSim::SimDisplay::mFboPosTexture protected
Definition at line 148 of file SimDisplay.h.
mFboQuadVAO
unsigned int MillSim::SimDisplay::mFboQuadVAO protected
Definition at line 151 of file SimDisplay.h.
mFboQuadVBO
unsigned int MillSim::SimDisplay::mFboQuadVBO protected
Definition at line 151 of file SimDisplay.h.
mFboRandTexture
unsigned int MillSim::SimDisplay::mFboRandTexture protected
Definition at line 160 of file SimDisplay.h.
mFboSsaoBlurTexture
unsigned int MillSim::SimDisplay::mFboSsaoBlurTexture protected
Definition at line 159 of file SimDisplay.h.
mFboSsaoTexture
unsigned int MillSim::SimDisplay::mFboSsaoTexture protected
Definition at line 158 of file SimDisplay.h.
mHeight
int MillSim::SimDisplay::mHeight protected
Definition at line 127 of file SimDisplay.h.
mlightObject
StockObject MillSim::SimDisplay::mlightObject protected
Definition at line 124 of file SimDisplay.h.
mMatLookAt
mat4x4 MillSim::SimDisplay::mMatLookAt protected
Definition at line 123 of file SimDisplay.h.
Referenced by PrepareDisplay().
mMaxStockDim
float MillSim::SimDisplay::mMaxStockDim = 100 protected
Definition at line 138 of file SimDisplay.h.
mRboDepthStencil
unsigned int MillSim::SimDisplay::mRboDepthStencil protected
Definition at line 150 of file SimDisplay.h.
mSsaoBlurFbo
unsigned int MillSim::SimDisplay::mSsaoBlurFbo protected
Definition at line 157 of file SimDisplay.h.
mSsaoFbo
unsigned int MillSim::SimDisplay::mSsaoFbo protected
Definition at line 156 of file SimDisplay.h.
mSsaoKernel
std::vector<Point3D> MillSim::SimDisplay::mSsaoKernel protected
Definition at line 155 of file SimDisplay.h.
mSsaoValid
bool MillSim::SimDisplay::mSsaoValid = false protected
Definition at line 154 of file SimDisplay.h.
Referenced by StartCloserGeometryPass().
mWidth
int MillSim::SimDisplay::mWidth protected
Definition at line 126 of file SimDisplay.h.
pathLineColor
vec4 MillSim::SimDisplay::pathLineColor = {0.0f, 0.9f, 0.0f, 1.0} protected
Definition at line 116 of file SimDisplay.h.
pathLineColorPassed
vec3 MillSim::SimDisplay::pathLineColorPassed = {0.9f, 0.3f, 0.3f} protected
Definition at line 117 of file SimDisplay.h.
shader3D
Shader MillSim::SimDisplay::shader3D protected
Definition at line 109 of file SimDisplay.h.
shaderFlat
Shader MillSim::SimDisplay::shaderFlat protected
Definition at line 109 of file SimDisplay.h.
shaderGeom
Shader MillSim::SimDisplay::shaderGeom protected
Definition at line 110 of file SimDisplay.h.
Referenced by PrepareDisplay().
shaderGeomCloser
Shader MillSim::SimDisplay::shaderGeomCloser protected
Definition at line 111 of file SimDisplay.h.
shaderInv3D
Shader MillSim::SimDisplay::shaderInv3D protected
Definition at line 109 of file SimDisplay.h.
shaderLinePath
Shader MillSim::SimDisplay::shaderLinePath protected
Definition at line 112 of file SimDisplay.h.
shaderSimFbo
Shader MillSim::SimDisplay::shaderSimFbo protected
Definition at line 109 of file SimDisplay.h.
shaderSSAO
Shader MillSim::SimDisplay::shaderSSAO protected
Definition at line 110 of file SimDisplay.h.
shaderSSAOBlur
Shader MillSim::SimDisplay::shaderSSAOBlur protected
Definition at line 110 of file SimDisplay.h.
shaderSSAOLighting
Shader MillSim::SimDisplay::shaderSSAOLighting protected
Definition at line 110 of file SimDisplay.h.
Referenced by RenderLightObject().
target
vec3 MillSim::SimDisplay::target = {0, 0, 0} protected
Definition at line 120 of file SimDisplay.h.
Referenced by femsolver.run.Machine::run().
updateDisplay
bool MillSim::SimDisplay::updateDisplay = false
Definition at line 94 of file SimDisplay.h.
Referenced by MillSim::MillSimulation::HandleGuiAction(), MillSim::MillSimulation::Render(), MillSim::MillSimulation::SetSimulationStage(), MillSim::MillSimulation::SimNext(), and MillSim::MillSimulation::UpdateWindowScale().
upvec
vec3 MillSim::SimDisplay::upvec = {0, 0, 1} protected
Definition at line 121 of file SimDisplay.h.
The documentation for this class was generated from the following files:
SimDisplay.h
SimDisplay.cpp