FreeCAD: SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod > Class Template Reference
SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod > Class Template Reference
Class defining a handler controller making use of parameters provided by a widget of type SketcherToolDefaultWidget.
#include <DrawSketchDefaultWidgetController.h>
Public Member Functions
functions NOT intended for specialisation offering specialisation interface for
extension
void parameterValueChanged (int parameterindex, double value)
void parameterTabOrEnterPressed (int parameterindex)
void checkboxCheckedChanged (int checkboxindex, bool value)
void comboboxSelectionChanged (int comboboxindex, int value)
Specialisation Interface
void adaptDrawingToParameterChange (int parameterindex, double value)
Change DSH to reflect a value entered in the widget.
void adaptDrawingToCheckboxChange (int checkboxindex, bool value)
Change DSH to reflect a checkbox changed in the widget.
void adaptDrawingToComboboxChange (int comboboxindex, [[maybe_unused]] int value)
Change DSH to reflect a comboBox changed in the widget.
void addConstraints () override
function to create constraints based on widget information.
void configureToolWidget ()
function to configure the default widget.
void doChangeDrawSketchHandlerMode () override
void adaptParameters (Base::Vector2d onSketchPos) override
void firstKeyShortcut () override
void secondKeyShortcut () override
void thirdKeyShortcut () override
void fourthKeyShortcut () override
void tabShortcut () override
Public Member Functions inherited from SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >
void initControls (QWidget *widget)
Initialises controls, such as the widget and the on-view parameters via NVI.
void resetControls ()
Resets the controls, such as the widget and the on-view parameters.
void mouseMoved (Base::Vector2d originalSketchPosition)
function triggered by the handler when the mouse has been moved
void enforceControlParameters (Base::Vector2d &onSketchPos)
function triggered by the handler to ensure its operating position takes into account widget mandated parameters
void onConstructionMethodChanged ()
virtual bool resetOnConstructionMethodeChanged ()
void onViewValueChanged (int onviewparameterindex, double value)
void tryViewValueChanged (int onviewparameterindex, double value)
void adaptParameters ()
void adaptDrawingToOnViewParameterChange (int onviewparameterindex, double value)
Change DSH to reflect a value entered in the view.
auto getState (int parameterindex) const
void configureOnViewParameters ()
Configures on-view parameters.
void onHandlerModeChanged ()
void doEnforceControlParameters (Base::Vector2d &onSketchPos)
virtual void afterHandlerModeChanged ()
triggered by the controllable DSH after a mode change has been effected
void drawPositionAtCursor (const Base::Vector2d &position)
void drawDirectionAtCursor (const Base::Vector2d &position, const Base::Vector2d &origin)
void drawWidthHeightAtCursor (const Base::Vector2d &position, const double val1, const double val2)
void drawDoubleAtCursor (const Base::Vector2d &position, const double radius, Base::Unit unit=Base::Unit::Length)
DrawSketchController (HandlerT *dshandler)
DrawSketchController (const DrawSketchController &)=delete
DrawSketchController (DrawSketchController &&)=delete
DrawSketchController & operator= (const DrawSketchController &)=delete
DrawSketchController & operator= (DrawSketchController &&)=delete
virtual ~DrawSketchController ()
Meta-programming definitions and members
using ControllerBase = DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >
Named indices for controls of the default widget (SketcherToolDefaultWidget)
DrawSketchDefaultWidgetController (HandlerT *dshandler)
DrawSketchDefaultWidgetController (const DrawSketchDefaultWidgetController &)=delete
DrawSketchDefaultWidgetController (DrawSketchDefaultWidgetController &&)=delete
DrawSketchDefaultWidgetController & operator= (const DrawSketchDefaultWidgetController &)=delete
DrawSketchDefaultWidgetController & operator= (DrawSketchDefaultWidgetController &&)=delete
~DrawSketchDefaultWidgetController () override
DrawSketchController NVI
void doInitControls (QWidget *widget) override
Initialises widget control.
void doResetControls () override
Resets widget controls.
void doConstructionMethodChanged () override
Automatic default method update in combobox.
void setFocusToParameter (unsigned int parameterindex)
here we can pass focus to either OVP or widget parameters.
void passFocusToNextParameter ()
Here we can pass focus to either OVP or widget parameters.
Additional Inherited Members
Public Types inherited from SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >
using ControllerBase = void
using HandlerType = HandlerT
using SelectModeType = SelectModeT
using ContructionMethodType = ConstructionMethods::DefaultConstructionMethod
using DSDefaultHandler = DrawSketchDefaultHandler< HandlerT, SelectModeT, PAutoConstraintSize, ConstructionMethods::DefaultConstructionMethod >
using ConstructionMachine = ConstructionMethodMachine< ConstructionMethods::DefaultConstructionMethod >
using ConstructionMethod = ConstructionMethods::DefaultConstructionMethod
using SelectMode = SelectModeT
Static Public Attributes inherited from SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >
static constexpr const int AutoConstraintInitialSize
Protected Types inherited from SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >
enum OnViewParameter
Protected Member Functions inherited from SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >
virtual void onMouseMoved (Base::Vector2d originalSketchPosition)
virtual void afterEnforceControlParameters ()
void setMode (T &modeenum, int modevalue)
void finishControlsChanged ()
void initNOnViewParameters (int n)
Initialises on-screen parameters.
void unsetOnViewParameter (Gui::EditableDatumLabel *onViewParameter)
Allows a on-view parameter to take any mouse mandated value (as opposed to enforce one)
void setOnViewParameterValue (OnViewParameter index, double val, const Base::Unit &unit=Base::Unit::Length)
void setModeOnViewParameters ()
bool setFocusToOnViewParameter (unsigned int onviewparameterindex)
This function gives the focus to a spinbox and tracks the focus.
void passFocusToNextOnViewParameter ()
Switches focus to the next parameter in the current state machine.
bool isOnViewParameterOfCurrentMode (unsigned int onviewparameterindex) const
bool isOnViewParameterOfPreviousMode (unsigned int onviewparameterindex) const
bool isOnViewParameterVisible (unsigned int onviewparameterindex)
void resetOnViewParameters ()
DrawSketchKeyboardManager * getKeyManager ()
Protected Attributes inherited from SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >
HandlerT * handler
std::vector< std::unique_ptr< Gui::EditableDatumLabel > > onViewParameters
bool init
int parameterWithFocus
bool focusAutoPassing
Detailed Description
template<typename HandlerT, typename SelectModeT, int PAutoConstraintSize, typename OnViewParametersT, typename WidgetParametersT, typename WidgetCheckboxesT, typename WidgetComboboxesT, typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod, bool PFirstComboboxIsConstructionMethod = false>
class SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >
Class defining a handler controller making use of parameters provided by a widget of type SketcherToolDefaultWidget.
This class derives from DrawSketchController and thus provides on-view parameters too. In addition it manages a SketcherToolDefaultWidget in which a number of spinboxes, checkboxes and comboboxes are provided.
It also provides automatic handling of change of creation method.
This class is not intended to control based on a custom widget.
Definition at line 98 of file DrawSketchDefaultWidgetController.h.
Member Typedef Documentation
ControllerBase
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename WidgetParametersT , typename WidgetCheckboxesT , typename WidgetComboboxesT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod, bool PFirstComboboxIsConstructionMethod = false> using SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::ControllerBase = DrawSketchController<HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT>
Definition at line 111 of file DrawSketchDefaultWidgetController.h.
Constructor & Destructor Documentation
DrawSketchDefaultWidgetController() [1/3]
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename WidgetParametersT , typename WidgetCheckboxesT , typename WidgetComboboxesT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod, bool PFirstComboboxIsConstructionMethod = false> SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::DrawSketchDefaultWidgetController (HandlerT * dshandler) inline explicit
Definition at line 139 of file DrawSketchDefaultWidgetController.h.
DrawSketchDefaultWidgetController() [2/3]
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename WidgetParametersT , typename WidgetCheckboxesT , typename WidgetComboboxesT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod, bool PFirstComboboxIsConstructionMethod = false> SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::DrawSketchDefaultWidgetController (const DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod > &) delete
DrawSketchDefaultWidgetController() [3/3]
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename WidgetParametersT , typename WidgetCheckboxesT , typename WidgetComboboxesT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod, bool PFirstComboboxIsConstructionMethod = false> SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::DrawSketchDefaultWidgetController (DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod > &&) delete
~DrawSketchDefaultWidgetController()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename WidgetParametersT , typename WidgetCheckboxesT , typename WidgetComboboxesT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod, bool PFirstComboboxIsConstructionMethod = false> SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::~DrawSketchDefaultWidgetController () inline override
Definition at line 149 of file DrawSketchDefaultWidgetController.h.
Member Function Documentation
adaptDrawingToCheckboxChange()
void SketcherGui::DSHTranslateController::adaptDrawingToCheckboxChange (int checkboxindex, bool value) inline
Change DSH to reflect a checkbox changed in the widget.
Definition at line 220 of file DrawSketchDefaultWidgetController.h.
adaptDrawingToComboboxChange()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename WidgetParametersT , typename WidgetCheckboxesT , typename WidgetComboboxesT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod, bool PFirstComboboxIsConstructionMethod = false> void SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::adaptDrawingToComboboxChange (int comboboxindex, [[maybe_unused] ] int value) inline
Change DSH to reflect a comboBox changed in the widget.
Definition at line 227 of file DrawSketchDefaultWidgetController.h.
Referenced by SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::parameterTabOrEnterPressed().
adaptDrawingToParameterChange()
void SketcherGui::DSHTranslateController::adaptDrawingToParameterChange (int parameterindex, double value) inline
Change DSH to reflect a value entered in the widget.
These functions offer a specialisation interface. Non-virtual functions are specific to this controller. Virtual functions may depend on input from a derived controller, and thus the specialisation needs to be of an overridden version (so as to be able to access members of the derived controller).
Definition at line 213 of file DrawSketchDefaultWidgetController.h.
References SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >::handler.
adaptParameters()
void SketcherGui::DSHTranslateController::adaptParameters (Base::Vector2d onSketchPos) inline override virtual
function that is called by the handler with a Vector2d position to update the widget
Reimplemented from SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >.
Definition at line 252 of file DrawSketchDefaultWidgetController.h.
addConstraints()
void SketcherGui::DSHSlotController::addConstraints inline override virtual
function to create constraints based on widget information.
Reimplemented from SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >.
Definition at line 240 of file DrawSketchDefaultWidgetController.h.
References SketcherGui::SketcherToolDefaultWidget::getCheckboxChecked(), and SketcherGui::SketcherToolDefaultWidget::setCheckboxChecked().
checkboxCheckedChanged()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename WidgetParametersT , typename WidgetCheckboxesT , typename WidgetComboboxesT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod, bool PFirstComboboxIsConstructionMethod = false> void SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::checkboxCheckedChanged (int checkboxindex, bool value) inline
boost slot triggering when a checkbox has changed in the widget It is intended to remote control the DrawSketchDefaultWidgetHandler
Definition at line 188 of file DrawSketchDefaultWidgetController.h.
comboboxSelectionChanged()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename WidgetParametersT , typename WidgetCheckboxesT , typename WidgetComboboxesT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod, bool PFirstComboboxIsConstructionMethod = false> void SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::comboboxSelectionChanged (int comboboxindex, int value) inline
boost slot triggering when a combobox has changed in the widget It is intended to remote control the DrawSketchDefaultWidgetHandler
Definition at line 198 of file DrawSketchDefaultWidgetController.h.
configureToolWidget()
void SketcherGui::DSHTranslateController::configureToolWidget inline
function to configure the default widget.
Definition at line 244 of file DrawSketchDefaultWidgetController.h.
doChangeDrawSketchHandlerMode()
void SketcherGui::DSHTranslateController::doChangeDrawSketchHandlerMode inline override virtual
function that is called by the handler with a Vector2d position to update the widget
Reimplemented from SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >.
Definition at line 248 of file DrawSketchDefaultWidgetController.h.
doConstructionMethodChanged()
void SketcherGui::DSHBSplineController::doConstructionMethodChanged inline override protected virtual
Automatic default method update in combobox.
Reimplemented from SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >.
Definition at line 323 of file DrawSketchDefaultWidgetController.h.
References SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::parameterWithFocus.
doInitControls()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename WidgetParametersT , typename WidgetCheckboxesT , typename WidgetComboboxesT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod, bool PFirstComboboxIsConstructionMethod = false> void SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::doInitControls (QWidget * widget) inline override protected virtual
Initialises widget control.
Reimplemented from SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >.
Definition at line 309 of file DrawSketchDefaultWidgetController.h.
References SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::onViewParameters, and SketcherGui::SketcherToolDefaultWidget::setParameterFocus().
doResetControls()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename WidgetParametersT , typename WidgetCheckboxesT , typename WidgetComboboxesT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod, bool PFirstComboboxIsConstructionMethod = false> void SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::doResetControls () inline override protected virtual
Resets widget controls.
Reimplemented from SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >.
Definition at line 316 of file DrawSketchDefaultWidgetController.h.
firstKeyShortcut()
void SketcherGui::DSHTranslateController::firstKeyShortcut inline override virtual
on first shortcut, it toggles the first checkbox if there is one. Must be specialised if this is not intended
Reimplemented from SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >.
Definition at line 259 of file DrawSketchDefaultWidgetController.h.
References SketcherGui::SketcherToolDefaultWidget::getCheckboxChecked(), and SketcherGui::SketcherToolDefaultWidget::setCheckboxChecked().
fourthKeyShortcut()
void SketcherGui::DSHTranslateController::fourthKeyShortcut inline override virtual
on fourth shortcut, it toggles the fourth checkbox if there is one. Must be specialised if this is not intended
Reimplemented from SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >.
Definition at line 289 of file DrawSketchDefaultWidgetController.h.
operator=() [1/2]
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename WidgetParametersT , typename WidgetCheckboxesT , typename WidgetComboboxesT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod, bool PFirstComboboxIsConstructionMethod = false> DrawSketchDefaultWidgetController& SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::operator= (const DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod > &) delete
operator=() [2/2]
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename WidgetParametersT , typename WidgetCheckboxesT , typename WidgetComboboxesT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod, bool PFirstComboboxIsConstructionMethod = false> DrawSketchDefaultWidgetController& SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::operator= (DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod > &&) delete
parameterTabOrEnterPressed()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename WidgetParametersT , typename WidgetCheckboxesT , typename WidgetComboboxesT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod, bool PFirstComboboxIsConstructionMethod = false> void SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::parameterTabOrEnterPressed (int parameterindex) inline
Definition at line 179 of file DrawSketchDefaultWidgetController.h.
References SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::adaptDrawingToComboboxChange(), and SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethodT >::finishControlsChanged().
parameterValueChanged()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename WidgetParametersT , typename WidgetCheckboxesT , typename WidgetComboboxesT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod, bool PFirstComboboxIsConstructionMethod = false> void SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::parameterValueChanged (int parameterindex, double value) inline
These functions offer a specialisation interface to ensure the order on initialisation. It is heavily encouraged to extend functionality using the specialisation interface. boost slot triggering when a parameter has changed in the widget It is intended to remote control the DrawSketchDefaultWidgetHandler
Definition at line 166 of file DrawSketchDefaultWidgetController.h.
passFocusToNextParameter()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename WidgetParametersT , typename WidgetCheckboxesT , typename WidgetComboboxesT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod, bool PFirstComboboxIsConstructionMethod = false> void SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::passFocusToNextParameter () inline protected
Here we can pass focus to either OVP or widget parameters.
Definition at line 343 of file DrawSketchDefaultWidgetController.h.
Referenced by SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::thirdKeyShortcut().
secondKeyShortcut()
void SketcherGui::DSHTranslateController::secondKeyShortcut inline override virtual
on second shortcut, it toggles the second checkbox if there is one. Must be specialised if this is not intended
Reimplemented from SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >.
Definition at line 269 of file DrawSketchDefaultWidgetController.h.
References SketcherGui::SketcherToolDefaultWidget::getCheckboxChecked(), and SketcherGui::SketcherToolDefaultWidget::setCheckboxChecked().
setFocusToParameter()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename WidgetParametersT , typename WidgetCheckboxesT , typename WidgetComboboxesT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod, bool PFirstComboboxIsConstructionMethod = false> void SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::setFocusToParameter (unsigned int parameterindex) inline protected
here we can pass focus to either OVP or widget parameters.
Definition at line 327 of file DrawSketchDefaultWidgetController.h.
tabShortcut()
template<typename HandlerT , typename SelectModeT , int PAutoConstraintSize, typename OnViewParametersT , typename WidgetParametersT , typename WidgetCheckboxesT , typename WidgetComboboxesT , typename ConstructionMethodT = ConstructionMethods::DefaultConstructionMethod, bool PFirstComboboxIsConstructionMethod = false> void SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::tabShortcut () inline override virtual
on tab, we cycle through OVP and widget parameters
Reimplemented from SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >.
Definition at line 298 of file DrawSketchDefaultWidgetController.h.
thirdKeyShortcut()
void SketcherGui::DSHTranslateController::thirdKeyShortcut inline override virtual
on third shortcut, it toggles the third checkbox if there is one. Must be specialised if this is not intended
Reimplemented from SketcherGui::DrawSketchController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, ConstructionMethods::DefaultConstructionMethod >.
Definition at line 279 of file DrawSketchDefaultWidgetController.h.
References SketcherGui::DrawSketchDefaultWidgetController< HandlerT, SelectModeT, PAutoConstraintSize, OnViewParametersT, WidgetParametersT, WidgetCheckboxesT, WidgetComboboxesT, ConstructionMethodT, PFirstComboboxIsConstructionMethod >::passFocusToNextParameter().
The documentation for this class was generated from the following files:
DrawSketchDefaultWidgetController.h
DrawSketchHandlerArc.h
DrawSketchHandlerArcSlot.h
DrawSketchHandlerBSpline.h
DrawSketchHandlerCircle.h
DrawSketchHandlerEllipse.h
DrawSketchHandlerFillet.h
DrawSketchHandlerLine.h
DrawSketchHandlerOffset.h
DrawSketchHandlerPolygon.h
DrawSketchHandlerRectangle.h
DrawSketchHandlerRotate.h
DrawSketchHandlerScale.h
DrawSketchHandlerSlot.h
DrawSketchHandlerSymmetry.h
DrawSketchHandlerTranslate.h