FreeCAD: Gui::DockWindowManager Class Reference
Gui::DockWindowManager Class Reference
#include <DockWindowManager.h>
Public Member Functions
QDockWidget * addDockWindow (const char *name, QWidget *widget, Qt::DockWidgetArea pos=Qt::AllDockWidgetAreas)
Adds a QDockWidget to the main window and sets widget as its widget.
QWidget * getDockWindow (const char *name) const
QDockWidget * getDockContainer (const char *name) const
Returns the QDockWidget container.
QList< QWidget * > getDockWindows () const
Returns a list of all widgets which set to a QDockWidget.
bool isOverlayActivated () const
Static Public Member Functions
static DockWindowManager * instance ()
static void destruct ()
without deleting it.
Removes the specified dock window with name
bool registerDockWindow (const char *name, QWidget *widget)
QWidget * unregisterDockWindow (const char *name)
QWidget * findRegisteredDockWindow (const char *name)
void setup (DockWindowItems *)
QWidget * removeDockWindow (const char *name)
void removeDockWindow (QWidget *dock)
void activate (QWidget *widget)
If the corresponding dock widget isn't visible then activate it.
void saveState ()
void loadState ()
void retranslate ()
Detailed Description
Class that manages the widgets inside a QDockWidget.
Author
Werner Mayer
Definition at line 61 of file DockWindowManager.h.
Member Function Documentation
activate()
void DockWindowManager::activate (QWidget * widget)
If the corresponding dock widget isn't visible then activate it.
If the corresponding dock widget isn't visible then activate it.
Definition at line 408 of file DockWindowManager.cpp.
Referenced by ArchBuildingPart.ViewProviderBuildingPart::setEdit(), nativeifc.ifc_viewproviders.ifc_vp_object::setupContextMenu(), ArchBuildingPart.ViewProviderBuildingPart::setupContextMenu(), and Gui::DockWnd::ReportOutputObserver::showReportView().
addDockWindow()
QDockWidget * DockWindowManager::addDockWindow (const char * name, QWidget * widget, Qt::DockWidgetArea pos = Qt::AllDockWidgetAreas)
Adds a QDockWidget to the main window and sets widget as its widget.
Adds a new dock window to the main window and embeds the given widget.
Definition at line 239 of file DockWindowManager.cpp.
References Gui::DockWindowManagerP::_dockedWindows, draftgeoutils.intersections::connect(), Gui::getMainWindow(), NavigationIndicatorGui::mw, Gui::DockWindowManagerP::overlayManager, RobotExample::pos, Gui::MainWindow::saveWindowSettings(), and Plot::title().
Referenced by MatGui::DlgMaterialImp::DlgMaterialImp(), Gui::Dialog::DockablePlacement::DockablePlacement(), MeshGui::DockEvaluateMeshImp::DockEvaluateMeshImp(), PartGui::SectionCut::makeDockWidget(), Gui::Dialog::Clipping::makeDockWidget(), and setup().
destruct()
void DockWindowManager::destruct () static
Definition at line 170 of file DockWindowManager.cpp.
Referenced by Gui::WorkbenchManager::~WorkbenchManager().
findRegisteredDockWindow()
QWidget * DockWindowManager::findRegisteredDockWindow (const char * name)
Definition at line 484 of file DockWindowManager.cpp.
References Gui::DockWindowManagerP::_dockWindows.
getDockContainer()
QDockWidget * DockWindowManager::getDockContainer (const char * name) const
Returns the QDockWidget container.
Returns the dock widget by name. If it does not exist 0 is returned.
Definition at line 323 of file DockWindowManager.cpp.
References Gui::DockWindowManagerP::_dockedWindows.
getDockWindow()
QWidget * DockWindowManager::getDockWindow (const char * name) const
Returns the widget with name name added with addDockWindow.
Note
The returned widget is not the QDockWidget instance returned from addDockWindow. If you want to access the QDockWidget you get it with parentWidget() of the returned widget.
Returns the widget inside the dock window by name. If it does not exist 0 is returned.
Definition at line 309 of file DockWindowManager.cpp.
References Gui::DockWindowManagerP::_dockedWindows.
Referenced by StdCmdProperties::activated().
getDockWindows()
QList< QWidget * > DockWindowManager::getDockWindows () const
Returns a list of all widgets which set to a QDockWidget.
Returns a list of all widgets inside the dock windows.
Definition at line 336 of file DockWindowManager.cpp.
References Gui::DockWindowManagerP::_dockedWindows.
instance()
DockWindowManager * DockWindowManager::instance () static
Creates the only instance of the DockWindowManager.
Definition at line 163 of file DockWindowManager.cpp.
Referenced by _updateDockWidget(), Gui::Dialog::DockablePlacement::accept(), Gui::Workbench::activate(), StdCmdProperties::activated(), Gui::PreferencePackManager::apply(), MeshGui::DockEvaluateMeshImp::closeEvent(), copyTemplateParameters(), MatGui::DlgMaterialImp::DlgMaterialImp(), Gui::Dialog::DockablePlacement::DockablePlacement(), MeshGui::DockEvaluateMeshImp::DockEvaluateMeshImp(), PartGui::SectionCut::makeDockWidget(), Gui::Dialog::Clipping::makeDockWidget(), MatGui::DlgMaterialImp::reject(), Gui::Dialog::DockablePlacement::reject(), Gui::Workbench::retranslate(), Gui::MainWindow::saveWindowSettings(), Gui::StdWorkbench::setupMenuBar(), Gui::ControlSingleton::showModelView(), Gui::DockWnd::ReportOutputObserver::showReportView(), Gui::ControlSingleton::taskPanel(), and SandboxGui::Workbench::Workbench().
isOverlayActivated()
bool DockWindowManager::isOverlayActivated () const
Definition at line 193 of file DockWindowManager.cpp.
References Gui::DockWindowManagerP::overlayManager.
loadState()
void DockWindowManager::loadState ()
Definition at line 594 of file DockWindowManager.cpp.
References Gui::DockWindowManagerP::_dockedWindows, Gui::DockWindowManagerP::_dockWindowItems, Gui::DockWindowItems::dockWidgets(), App::GetApplication(), ParameterGrp::GetBool(), ParameterGrp::GetGroup(), and App::Application::GetUserParameter().
Referenced by Gui::PreferencePackManager::apply().
registerDockWindow()
bool DockWindowManager::registerDockWindow (const char * name, QWidget * widget)
Appends a new widget with name to the list of available dock widgets. The caller must make sure that the name is unique. If a widget with this name is already registered nothing is done but false is returned, otherwise it is appended and true is returned.
As default the following widgets are already registered:
Std_TreeView
Std_PropertyView
Std_ReportView
Std_ToolBox
Std_ComboView
Std_SelectionView
To avoid name clashes the caller should use names of the form module_widgettype, i. e. if a analyse dialog for the mesh module is added the name must then be Mesh_AnalyzeDialog.
To make use of dock windows when a workbench gets loaded the method setupDockWindows() must reimplemented in a subclass of Gui::Workbench.
Definition at line 463 of file DockWindowManager.cpp.
References Gui::DockWindowManagerP::_dockWindows.
Referenced by _updateDockWidget(), and SandboxGui::Workbench::Workbench().
removeDockWindow() [1/2]
QWidget * DockWindowManager::removeDockWindow (const char * name)
Removes and destroys the QDockWidget and returns the widget with name name added with addDockWindow.
Definition at line 347 of file DockWindowManager.cpp.
References Gui::DockWindowManagerP::_dockedWindows, Gui::getMainWindow(), and Gui::DockWindowManagerP::overlayManager.
Referenced by Gui::Dialog::DockablePlacement::accept(), MeshGui::DockEvaluateMeshImp::closeEvent(), MatGui::DlgMaterialImp::reject(), and Gui::Dialog::DockablePlacement::reject().
removeDockWindow() [2/2]
void DockWindowManager::removeDockWindow (QWidget * widget)
Removes and destroys the QDockWidget that contains dock. dock does not get destroyed.
Method provided for convenience. Does basically the same as the method above unless that it accepts a pointer.
Definition at line 380 of file DockWindowManager.cpp.
References Gui::DockWindowManagerP::_dockedWindows, Gui::getMainWindow(), and Gui::DockWindowManagerP::overlayManager.
retranslate()
void DockWindowManager::retranslate ()
Sets the window title for the dockable windows.
Definition at line 433 of file DockWindowManager.cpp.
References Gui::DockWindowManagerP::_dockedWindows, and Plot::title().
Referenced by Gui::Workbench::retranslate().
saveState()
void DockWindowManager::saveState ()
Definition at line 582 of file DockWindowManager.cpp.
References Gui::DockWindowManagerP::_dockedWindows, Gui::DockWindowManagerP::_dockWindowItems, Gui::DockWindowManagerP::_hPref, Gui::DockWindowItems::dockWidgets(), and ParameterGrp::SetBool().
Referenced by copyTemplateParameters(), Gui::MainWindow::saveWindowSettings(), and setup().
setup()
void DockWindowManager::setup (DockWindowItems * items)
Sets up the dock windows of the activated workbench.
Definition at line 493 of file DockWindowManager.cpp.
References Gui::DockWindowManagerP::_dockedWindows, Gui::DockWindowManagerP::_dockWindowItems, Gui::DockWindowManagerP::_dockWindows, Gui::DockWindowManagerP::_hPref, addDockWindow(), ParameterGrp::GetBool(), src.Mod.Test.testPathArray::items, Gui::DockWindowManagerP::overlayManager, and saveState().
Referenced by Gui::Workbench::activate(), Path.Dressup.Tags.ObjectTagDressup::doExecute(), Path.Dressup.Gui.Dogbone.ObjectDressup::execute(), Path.Dressup.Tags.ObjectTagDressup::generateTags(), Path.Dressup.Tags.ObjectTagDressup::pointAtBottom(), Path.Dressup.Tags.ObjectTagDressup::pointIsOnPath(), Path.Dressup.Tags.ObjectTagDressup::setXyEnabled(), and Path.Dressup.Tags.ObjectTagDressup::supportsTagGeneration().
unregisterDockWindow()
QWidget * DockWindowManager::unregisterDockWindow (const char * name)
Definition at line 473 of file DockWindowManager.cpp.
References Gui::DockWindowManagerP::_dockWindows.
The documentation for this class was generated from the following files:
DockWindowManager.h
DockWindowManager.cpp