FreeCAD: TechDraw::DimensionFormatter Class Reference
TechDraw::DimensionFormatter Class Reference
#include <DimensionFormatter.h>
Public Member Functions
DimensionFormatter ()
DimensionFormatter (DrawViewDimension *dim)
~DimensionFormatter ()=default
void setDimension (DrawViewDimension *dim)
bool isMultiValueSchema () const
std::string formatValue (const qreal value, const QString &qFormatSpec, const int partial, const bool isDim) const
std::string getFormattedToleranceValue (const int partial) const
get the formatted OverTolerance value
std::pair< std::string, std::string > getFormattedToleranceValues (const int partial) const
get formatted over and under tolerances
std::string getFormattedDimensionValue (const int partial) const
QStringList getPrefixSuffixSpec (const QString &fSpec) const
std::string getDefaultFormatSpec (bool isToleranceFormat) const
bool isTooSmall (const double value, const QString &formatSpec) const
QString formatValueToSpec (const double value, const QString &formatSpecifier) const
bool isNumericFormat (const QString &formatSpecifier) const
Detailed Description
Definition at line 53 of file DimensionFormatter.h.
Constructor & Destructor Documentation
DimensionFormatter() [1/2]
TechDraw::DimensionFormatter::DimensionFormatter () inline
Definition at line 75 of file DimensionFormatter.h.
DimensionFormatter() [2/2]
TechDraw::DimensionFormatter::DimensionFormatter (DrawViewDimension * dim) inline
Definition at line 76 of file DimensionFormatter.h.
~DimensionFormatter()
TechDraw::DimensionFormatter::~DimensionFormatter () default
Member Function Documentation
formatValue()
std::string DimensionFormatter::formatValue (const qreal value, const QString & qFormatSpec, const int partial, const bool isDim) const
Definition at line 58 of file DimensionFormatter.cpp.
References Base::Unit::Angle, Base::Unit::Area, Base::Console(), formatValueToSpec(), Base::UnitsApi::getBasicLengthUnit(), Base::UnitsApi::getDecimals(), App::DocumentObject::getNameInDocument(), getPrefixSuffixSpec(), Base::Quantity::getUserString(), Base::Quantity::getValue(), TechDraw::DrawViewDimension::haveTolerance(), isMultiValueSchema(), isTooSmall(), App::PropertyEnumeration::isValue(), Base::Unit::Length, Base::Quantity::parse(), Base::Quantity::setUnit(), Base::Quantity::setValue(), TechDraw::DrawViewDimension::showUnits(), TechDraw::DrawViewDimension::Type, TechDraw::DrawViewDimension::useDecimals(), and Base::ConsoleSingleton::Warning().
Referenced by getFormattedDimensionValue(), getFormattedToleranceValue(), and getFormattedToleranceValues().
formatValueToSpec()
QString DimensionFormatter::formatValueToSpec (const double value, const QString & formatSpecifier) const
Definition at line 312 of file DimensionFormatter.cpp.
References exportCSG::fs, isNumericFormat(), and src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression.
Referenced by formatValue().
getDefaultFormatSpec()
std::string DimensionFormatter::getDefaultFormatSpec (bool isToleranceFormat) const
Definition at line 369 of file DimensionFormatter.cpp.
References TechDraw::Preferences::altDecimals(), format2, TechDraw::Preferences::formatSpec(), Base::UnitsApi::getDecimals(), TechDraw::DrawViewDimension::getPrefixForDimType(), draftgeoutils.general::precision(), and TechDraw::DrawViewDimension::useDecimals().
getFormattedDimensionValue()
std::string DimensionFormatter::getFormattedDimensionValue (const int partial) const
Definition at line 255 of file DimensionFormatter.cpp.
References TechDraw::DrawViewDimension::Arbitrary, TechDraw::DrawViewDimension::ArbitraryTolerances, TechDraw::DrawViewDimension::EqualTolerance, TechDraw::DrawViewDimension::FormatSpec, formatValue(), TechDraw::DrawUtil::fpCompare(), TechDraw::DrawViewDimension::getDimValue(), getFormattedToleranceValue(), App::PropertyString::getStrValue(), App::PropertyQuantity::getValue(), App::PropertyBool::getValue(), TechDraw::DrawViewDimension::OverTolerance, src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression, TechDraw::DrawViewDimension::TheoreticalExact, and draftutils.utils::tolerance().
getFormattedToleranceValue()
std::string DimensionFormatter::getFormattedToleranceValue (const int partial) const
get the formatted OverTolerance value
Definition at line 210 of file DimensionFormatter.cpp.
References TechDraw::DrawViewDimension::ArbitraryTolerances, TechDraw::DrawViewDimension::FormatSpecOverTolerance, formatValue(), App::PropertyString::getStrValue(), App::PropertyQuantity::getValue(), App::PropertyBool::getValue(), and TechDraw::DrawViewDimension::OverTolerance.
Referenced by getFormattedDimensionValue().
getFormattedToleranceValues()
std::pair< std::string, std::string > DimensionFormatter::getFormattedToleranceValues (const int partial) const
get formatted over and under tolerances
Definition at line 227 of file DimensionFormatter.cpp.
References TechDraw::DrawViewDimension::ArbitraryTolerances, TechDraw::DrawViewDimension::FormatSpecOverTolerance, TechDraw::DrawViewDimension::FormatSpecUnderTolerance, formatValue(), App::PropertyString::getStrValue(), App::PropertyQuantity::getValue(), App::PropertyBool::getValue(), TechDraw::DrawViewDimension::OverTolerance, and TechDraw::DrawViewDimension::UnderTolerance.
getPrefixSuffixSpec()
QStringList DimensionFormatter::getPrefixSuffixSpec (const QString & fSpec) const
Definition at line 345 of file DimensionFormatter.cpp.
References Base::Console(), App::DocumentObject::getNameInDocument(), RobotExample::pos, src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression, result, and Base::ConsoleSingleton::Warning().
Referenced by formatValue().
isMultiValueSchema()
bool DimensionFormatter::isMultiValueSchema () const
Definition at line 38 of file DimensionFormatter.cpp.
References Base::UnitsApi::isMultiUnitAngle(), Base::UnitsApi::isMultiUnitLength(), App::PropertyEnumeration::isValue(), and TechDraw::DrawViewDimension::Type.
Referenced by formatValue().
isNumericFormat()
bool DimensionFormatter::isNumericFormat (const QString & formatSpecifier) const
Definition at line 333 of file DimensionFormatter.cpp.
References RobotExample::pos, and src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression.
Referenced by formatValueToSpec().
isTooSmall()
bool DimensionFormatter::isTooSmall (const double value, const QString & formatSpec) const
Definition at line 408 of file DimensionFormatter.cpp.
References Base::Console(), TechDraw::DrawUtil::fpCompare(), Base::pow(), src.Mod.AddonManager.addonmanager_devmode_license_selector::QRegularExpression, and Base::ConsoleSingleton::Warning().
Referenced by formatValue().
setDimension()
void TechDraw::DimensionFormatter::setDimension (DrawViewDimension * dim) inline
Definition at line 79 of file DimensionFormatter.h.
The documentation for this class was generated from the following files:
DimensionFormatter.h
DimensionFormatter.cpp