FreeCAD: Gui::DocumentModel Class Reference
Gui::DocumentModel Class Reference
#include <DocumentModel.h>
Public Member Functions
DocumentModel (QObject *parent)
~DocumentModel () override
int columnCount (const QModelIndex &parent=QModelIndex()) const override
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const override
bool setData (const QModelIndex &idx, const QVariant &value, int role) override
Qt::ItemFlags flags (const QModelIndex &index) const override
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const override
QModelIndex parent (const QModelIndex &index) const override
int rowCount (const QModelIndex &parent=QModelIndex()) const override
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole) override
Detailed Description
Definition at line 38 of file DocumentModel.h.
Constructor & Destructor Documentation
DocumentModel()
DocumentModel::DocumentModel (QObject * parent) explicit
Definition at line 351 of file DocumentModel.cpp.
References draftgeoutils.faces::bind(), Base::BaseClass::init(), Gui::Application::Instance, Gui::Application::signalActiveDocument, Gui::Application::signalDeleteDocument, Gui::Application::signalNewDocument, Gui::Application::signalRelabelDocument, and Gui::Application::signalRenameDocument.
~DocumentModel()
DocumentModel::~DocumentModel () override
Definition at line 373 of file DocumentModel.cpp.
Member Function Documentation
columnCount()
int DocumentModel::columnCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 603 of file DocumentModel.cpp.
data()
QVariant DocumentModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const override
Definition at line 608 of file DocumentModel.cpp.
References index().
flags()
Qt::ItemFlags DocumentModel::flags (const QModelIndex & index) const override
Definition at line 622 of file DocumentModel.cpp.
References index().
headerData()
QVariant DocumentModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const override
Definition at line 663 of file DocumentModel.cpp.
References Sketcher::Horizontal.
index()
QModelIndex DocumentModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const override
Definition at line 632 of file DocumentModel.cpp.
References App::ExpressionParser::column, parent(), and Gui::DocumentModelP::rootItem.
Referenced by src.Mod.PartDesign.WizardShaft.SegmentFunction.SegmentFunction::addSegment(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::begin(), data(), flags(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::interval(), src.Mod.PartDesign.WizardShaft.SegmentFunction.IntervalFunction::length(), parent(), setData(), automotive_design.index_expression::wr1(), and automotive_design.index_expression::wr2().
parent()
QModelIndex DocumentModel::parent (const QModelIndex & index) const override
Definition at line 644 of file DocumentModel.cpp.
References index(), Gui::DocumentModelIndex::parent(), and Gui::DocumentModelP::rootItem.
Referenced by index(), and rowCount().
rowCount()
int DocumentModel::rowCount (const QModelIndex & parent = QModelIndex()) const override
Definition at line 654 of file DocumentModel.cpp.
References Gui::DocumentModelIndex::childCount(), and parent().
Referenced by src.Mod.AddonManager.package_list.PackageListItemModel::append_item(), src.Mod.AddonManager.AddonManagerOptions.CustomRepoDataModel::appendData(), and src.Mod.AddonManager.package_list.PackageListItemModel::clear().
setData()
bool DocumentModel::setData (const QModelIndex & idx, const QVariant & value, int role) override
Definition at line 615 of file DocumentModel.cpp.
References index().
setHeaderData()
bool DocumentModel::setHeaderData (int section, Qt::Orientation orientation, const QVariant & value, int role = Qt::EditRole) override
Definition at line 675 of file DocumentModel.cpp.
The documentation for this class was generated from the following files:
DocumentModel.h
DocumentModel.cpp