FreeCAD: PartGui Namespace Reference
PartGui Namespace Reference
Namespaces
Ui
Classes
class AbstractPrimitive
class BooleanOperationItem
class BOPProgressIndicator
class BoxPrimitive
class BoxSelection
class CircleFromThreePoints
class CirclePrimitive
class ConePrimitive
class CrossSections
class CylinderPrimitive
class DlgBooleanOperation
class DlgChamferEdges
class DlgExportHeaderStep
class DlgExportStep
class DlgExtrusion
class DlgFilletEdges
class DlgImportExportIges
class DlgImportExportStep
class DlgImportStep
class DlgPartBoxImp
class DlgPartCylinderImp
class DlgPartImportIgesImp
class DlgPartImportStepImp
class DlgPrimitives
class DlgProjectionOnSurface
class DlgProjectOnSurface
class DlgRevolution
class DlgScale
class DlgSettings3DViewPart
class DlgSettingsGeneral
class DlgSettingsObjectColor
class EdgeFaceSelection
class EllipsePrimitive
class EllipsoidPrimitive
class FaceAppearances
class FaceSelection
class FilletEdgesDialog
class FilletRadiusDelegate
class FilletRadiusModel
class GridExtensionP
class HelixPrimitive
class LinePrimitive
class Location
class LoftWidget
class Mirroring
class MirrorPlaneSelection
class Module
class OffsetWidget
class Picker
class PlanePrimitive
class PolygonPrimitive
class PrismPrimitive
class PropertyEnumAttacherItem
class ReferenceHighlighter
The ReferenceHighlighter class.
class ResultEntry
class ResultModel
class SectionCut
class ShapeBuilderWidget
class ShapeFromMesh
class ShapeSelection
class SoBrepEdgeSet
class SoBrepFaceSet
class SoBrepPointSet
class SoFCControlPoints
class SpherePrimitive
class SpiralPrimitive
struct StepImportSettings
struct StepSettings
class SweepWidget
class TaskAttacher
class TaskBooleanOperation
class TaskChamferEdges
class TaskCheckGeometryDialog
class TaskCheckGeometryResults
class TaskCrossSections
class TaskDlgAttacher
simulation dialog for the TaskView
class TaskExportStep
class TaskExtrusion
class TaskFaceAppearances
class TaskFilletEdges
class TaskImportStep
class TaskLoft
class TaskMirroring
class TaskOffset
class TaskPrimitives
class TaskPrimitivesEdit
class TaskProjectionOnSurface
class TaskProjectOnSurface
class TaskRevolution
class TaskScale
class TaskShapeBuilder
class TaskSweep
class TaskThickness
class ThicknessWidget
class TorusPrimitive
class VertexPrimitive
class ViewProvider2DObject
class ViewProvider2DObjectGrid
class ViewProviderAttachExtension
class ViewProviderBoolean
class ViewProviderBox
class ViewProviderChamfer
class ViewProviderCircleParametric
class ViewProviderCompound
class ViewProviderConeParametric
class ViewProviderCrossSections
class ViewProviderCurveNet
class ViewProviderCustom
class ViewProviderCylinderParametric
class ViewProviderEllipseParametric
class ViewProviderEllipsoid
class ViewProviderExtrusion
class ViewProviderFace
class ViewProviderFillet
class ViewProviderGridExtension
class ViewProviderHelixParametric
class ViewProviderImport
class ViewProviderLCS
class ViewProviderLine
class ViewProviderLineParametric
class ViewProviderLoft
class ViewProviderMirror
class ViewProviderMultiCommon
ViewProvider for the MultiFuse feature.
class ViewProviderMultiFuse
ViewProvider for the MultiFuse feature.
class ViewProviderOffset
class ViewProviderOffset2D
class ViewProviderPart
class ViewProviderPartExt
class ViewProviderPartReference
class ViewProviderPlane
class ViewProviderPlaneParametric
class ViewProviderPoint
class ViewProviderPointParametric
class ViewProviderPrimitive
class ViewProviderPrism
class ViewProviderProjectOnSurface
class ViewProviderRefine
class ViewProviderRegularPolygon
class ViewProviderReverse
class ViewProviderRevolution
class ViewProviderRuledSurface
class ViewProviderScale
class ViewProviderShapeBuilder
class ViewProviderSphereParametric
class ViewProviderSpiralParametric
class ViewProviderSpline
class ViewProviderSplineExtension
class ViewProviderSweep
class ViewProviderThickness
class ViewProviderTorusParametric
class ViewProviderWedge
class WedgePrimitive
class Workbench
class WorkbenchManipulator
Typedefs
using Connection = boost::signals2::connection
using Ui_DlgPartBoxPtr = std::shared_ptr< Ui_DlgPartBox >
using Ui_DlgPartCylinderPtr = std::shared_ptr< Ui_DlgPartCylinder >
using ResultFunction = std::function< void(ResultEntry *entry)>
using FunctionMapType = std::tuple< TopAbs_ShapeEnum, BRepCheck_Status, ResultFunction >
using ViewProvider2DObjectPython = Gui::ViewProviderFeaturePythonT< ViewProvider2DObject >
using ViewProviderAttachExtensionPython = Gui::ViewProviderExtensionPythonT< PartGui::ViewProviderAttachExtension >
using ViewProviderGridExtensionPython = Gui::ViewProviderExtensionPythonT< PartGui::ViewProviderGridExtension >
using ViewProviderPython = Gui::ViewProviderFeaturePythonT< ViewProviderPart >
using ViewProviderCustomPython = Gui::ViewProviderFeaturePythonT< ViewProviderCustom >
using ViewProviderSplineExtensionPython = Gui::ViewProviderExtensionPythonT< PartGui::ViewProviderSplineExtension >
Functions
PyObject * initModule ()
bool checkForSolids (const TopoDS_Shape &shape)
std::vector< Part::TopoShape > getShapesFromSelection ()
bool hasShapesInSelection ()
QString getAutoGroupCommandStr (QString objectName)
const char * gce_ErrorStatusText (gce_ErrorType et)
static QString safeQuantityQString (Gui::QuantitySpinBox *qs)
void mapSignalMapper (QObject *sender, QSignalMapper *mapper)
template<typename Function >
void connectMapSignalMapper (typename QtPrivate::FunctionPointer< Function >::Object *sender, Function func, QSignalMapper *mapper)
QString buildSelectionName (const ResultEntry *entry, const TopoDS_Shape &shape)
void goSetupResultTypedSelection (ResultEntry *entry, const TopoDS_Shape &shape, TopAbs_ShapeEnum type)
void goSetupResultBoundingBox (ResultEntry *entry)
void goSetupResultShellNotClosed (ResultEntry *entry)
void goSetupResultWireNotClosed (ResultEntry *entry)
void goSetupResultInvalidPointCurve (ResultEntry *entry)
void goSetupResultIntersectingWires (ResultEntry *entry)
void goSetupResultInvalidCurveSurface (ResultEntry *entry)
void goSetupResultInvalidSameParameterFlag (ResultEntry *entry)
void goSetupResultUnorientableShapeFace (ResultEntry *entry)
Typedef Documentation
Connection
using PartGui::Connection = typedef boost::signals2::connection
Definition at line 38 of file DlgBooleanOperation.h.
FunctionMapType
using PartGui::FunctionMapType = typedef std::tuple<TopAbs_ShapeEnum, BRepCheck_Status, ResultFunction>
Definition at line 79 of file TaskCheckGeometry.h.
ResultFunction
using PartGui::ResultFunction = typedef std::function<void (ResultEntry *entry)>
Definition at line 78 of file TaskCheckGeometry.h.
Ui_DlgPartBoxPtr
using PartGui::Ui_DlgPartBoxPtr = typedef std::shared_ptr<Ui_DlgPartBox>
Definition at line 50 of file DlgPartBoxImp.h.
Ui_DlgPartCylinderPtr
using PartGui::Ui_DlgPartCylinderPtr = typedef std::shared_ptr<Ui_DlgPartCylinder>
Definition at line 50 of file DlgPartCylinderImp.h.
ViewProvider2DObjectPython
using PartGui::ViewProvider2DObjectPython = typedef Gui::ViewProviderFeaturePythonT<ViewProvider2DObject>
Definition at line 101 of file ViewProvider2DObject.h.
ViewProviderAttachExtensionPython
using PartGui::ViewProviderAttachExtensionPython = typedef Gui::ViewProviderExtensionPythonT<PartGui::ViewProviderAttachExtension>
Definition at line 70 of file ViewProviderAttachExtension.h.
ViewProviderCustomPython
using PartGui::ViewProviderCustomPython = typedef Gui::ViewProviderFeaturePythonT<ViewProviderCustom>
Definition at line 69 of file Part/Gui/ViewProviderPython.h.
ViewProviderGridExtensionPython
using PartGui::ViewProviderGridExtensionPython = typedef Gui::ViewProviderExtensionPythonT<PartGui::ViewProviderGridExtension>
Definition at line 114 of file ViewProviderGridExtension.h.
ViewProviderPython
using PartGui::ViewProviderPython = typedef Gui::ViewProviderFeaturePythonT<ViewProviderPart>
Definition at line 68 of file Part/Gui/ViewProviderPython.h.
ViewProviderSplineExtensionPython
using PartGui::ViewProviderSplineExtensionPython = typedef Gui::ViewProviderExtensionPythonT<PartGui::ViewProviderSplineExtension>
Definition at line 92 of file ViewProviderSpline.h.
Function Documentation
buildSelectionName()
QString PartGui::buildSelectionName (const ResultEntry * entry, const TopoDS_Shape & shape)
Definition at line 929 of file TaskCheckGeometry.cpp.
References PartGui::ResultEntry::name, PartGui::ResultEntry::parent, and PartGui::ResultEntry::shape.
Referenced by goSetupResultTypedSelection().
checkForSolids()
bool PartGui::checkForSolids (const TopoDS_Shape & shape)
Definition at line 235 of file Mod/Part/Gui/Command.cpp.
connectMapSignalMapper()
template<typename Function > void PartGui::connectMapSignalMapper (typename QtPrivate::FunctionPointer< Function >::Object * sender, Function func, QSignalMapper * mapper)
Definition at line 233 of file DlgPrimitives.cpp.
References draftgeoutils.intersections::connect(), and mapSignalMapper().
Referenced by PartGui::BoxPrimitive::BoxPrimitive(), PartGui::CirclePrimitive::CirclePrimitive(), PartGui::ConePrimitive::ConePrimitive(), PartGui::CylinderPrimitive::CylinderPrimitive(), PartGui::EllipsePrimitive::EllipsePrimitive(), PartGui::EllipsoidPrimitive::EllipsoidPrimitive(), PartGui::HelixPrimitive::HelixPrimitive(), PartGui::LinePrimitive::LinePrimitive(), PartGui::PlanePrimitive::PlanePrimitive(), PartGui::PolygonPrimitive::PolygonPrimitive(), PartGui::PrismPrimitive::PrismPrimitive(), PartGui::SpherePrimitive::SpherePrimitive(), PartGui::SpiralPrimitive::SpiralPrimitive(), PartGui::TorusPrimitive::TorusPrimitive(), PartGui::VertexPrimitive::VertexPrimitive(), and PartGui::WedgePrimitive::WedgePrimitive().
gce_ErrorStatusText()
const char* PartGui::gce_ErrorStatusText (gce_ErrorType et)
Definition at line 77 of file DlgPrimitives.cpp.
Referenced by PartGui::CircleFromThreePoints::command(), Part::Geom2dCircle::Restore(), Part::Geom2dArcOfCircle::Restore(), Part::Geom2dEllipse::Restore(), Part::Geom2dArcOfEllipse::Restore(), Part::Geom2dHyperbola::Restore(), Part::Geom2dArcOfHyperbola::Restore(), Part::Geom2dParabola::Restore(), Part::Geom2dArcOfParabola::Restore(), and Part::Geom2dLineSegment::Restore().
getAutoGroupCommandStr()
QString PartGui::getAutoGroupCommandStr (QString objectName)
Definition at line 64 of file DlgPrimitives.cpp.
References UtilsAssembly::activePart(), Gui::Application::activeView(), Gui::MDIView::getActiveObject(), and Gui::Application::Instance.
getShapesFromSelection()
std::vector<Part::TopoShape> PartGui::getShapesFromSelection ()
Definition at line 261 of file Mod/Part/Gui/Command.cpp.
References Base::Persistence::getClassTypeId(), Gui::SelectionSingleton::getObjectsOfType(), Part::Feature::getTopoShape(), Part::TopoShape::isNull(), replaceobj::objs, and Gui::Selection().
goSetupResultBoundingBox()
void PartGui::goSetupResultBoundingBox (ResultEntry * entry)
Definition at line 982 of file TaskCheckGeometry.cpp.
References KDL::Add(), PartGui::ResultEntry::boxSep, PartGui::ResultEntry::boxSwitch, cube, toolbit-attributes::group, PartGui::ResultEntry::shape, and PartGui::ResultEntry::viewProviderRoot.
Referenced by PartGui::TaskCheckGeometryResults::goCheck(), goSetupResultIntersectingWires(), goSetupResultInvalidCurveSurface(), goSetupResultInvalidPointCurve(), goSetupResultInvalidSameParameterFlag(), goSetupResultShellNotClosed(), goSetupResultUnorientableShapeFace(), and goSetupResultWireNotClosed().
goSetupResultIntersectingWires()
void PartGui::goSetupResultIntersectingWires (ResultEntry * entry)
Definition at line 1049 of file TaskCheckGeometry.cpp.
References goSetupResultBoundingBox(), goSetupResultTypedSelection(), and PartGui::ResultEntry::shape.
goSetupResultInvalidCurveSurface()
void PartGui::goSetupResultInvalidCurveSurface (ResultEntry * entry)
Definition at line 1055 of file TaskCheckGeometry.cpp.
References goSetupResultBoundingBox(), goSetupResultTypedSelection(), and PartGui::ResultEntry::shape.
goSetupResultInvalidPointCurve()
void PartGui::goSetupResultInvalidPointCurve (ResultEntry * entry)
Definition at line 1043 of file TaskCheckGeometry.cpp.
References goSetupResultBoundingBox(), goSetupResultTypedSelection(), and PartGui::ResultEntry::shape.
goSetupResultInvalidSameParameterFlag()
void PartGui::goSetupResultInvalidSameParameterFlag (ResultEntry * entry)
Definition at line 1061 of file TaskCheckGeometry.cpp.
References goSetupResultBoundingBox(), goSetupResultTypedSelection(), and PartGui::ResultEntry::shape.
goSetupResultShellNotClosed()
void PartGui::goSetupResultShellNotClosed (ResultEntry * entry)
Definition at line 1025 of file TaskCheckGeometry.cpp.
References goSetupResultBoundingBox(), goSetupResultTypedSelection(), and PartGui::ResultEntry::shape.
goSetupResultTypedSelection()
void PartGui::goSetupResultTypedSelection (ResultEntry * entry, const TopoDS_Shape & shape, TopAbs_ShapeEnum type)
Definition at line 971 of file TaskCheckGeometry.cpp.
References buildSelectionName(), PartGui::ResultEntry::selectionStrings, and Path.Post.scripts.grbl_post::type.
Referenced by goSetupResultIntersectingWires(), goSetupResultInvalidCurveSurface(), goSetupResultInvalidPointCurve(), goSetupResultInvalidSameParameterFlag(), goSetupResultShellNotClosed(), goSetupResultUnorientableShapeFace(), and goSetupResultWireNotClosed().
goSetupResultUnorientableShapeFace()
void PartGui::goSetupResultUnorientableShapeFace (ResultEntry * entry)
Definition at line 1067 of file TaskCheckGeometry.cpp.
References goSetupResultBoundingBox(), goSetupResultTypedSelection(), and PartGui::ResultEntry::shape.
goSetupResultWireNotClosed()
void PartGui::goSetupResultWireNotClosed (ResultEntry * entry)
Definition at line 1037 of file TaskCheckGeometry.cpp.
References goSetupResultBoundingBox(), goSetupResultTypedSelection(), and PartGui::ResultEntry::shape.
hasShapesInSelection()
bool PartGui::hasShapesInSelection ()
Definition at line 277 of file Mod/Part/Gui/Command.cpp.
References Base::Persistence::getClassTypeId(), Gui::SelectionSingleton::getObjectsOfType(), Part::Feature::getTopoShape(), draftgeoutils.general::isNull(), and Gui::Selection().
initModule()
PyObject* PartGui::initModule ()
Definition at line 110 of file AppPartGui.cpp.
References Base::InterpreterSingleton::addModule(), and Base::Interpreter().
Referenced by PyMOD_INIT_FUNC().
mapSignalMapper()
void PartGui::mapSignalMapper (QObject * sender, QSignalMapper * mapper)
Definition at line 227 of file DlgPrimitives.cpp.
Referenced by connectMapSignalMapper().
safeQuantityQString()
static QString PartGui::safeQuantityQString (Gui::QuantitySpinBox * qs) static
Definition at line 114 of file DlgPrimitives.cpp.
References Base::Quantity::getSafeUserString(), and Gui::QuantitySpinBox::value.
Referenced by PartGui::PlanePrimitive::change(), PartGui::BoxPrimitive::change(), PartGui::CylinderPrimitive::change(), PartGui::ConePrimitive::change(), PartGui::SpherePrimitive::change(), PartGui::EllipsoidPrimitive::change(), PartGui::TorusPrimitive::change(), PartGui::PrismPrimitive::change(), PartGui::WedgePrimitive::change(), PartGui::HelixPrimitive::change(), PartGui::SpiralPrimitive::change(), PartGui::CirclePrimitive::change(), PartGui::EllipsePrimitive::change(), PartGui::PolygonPrimitive::change(), PartGui::LinePrimitive::change(), PartGui::VertexPrimitive::change(), PartGui::PlanePrimitive::create(), PartGui::BoxPrimitive::create(), PartGui::CylinderPrimitive::create(), PartGui::ConePrimitive::create(), PartGui::SpherePrimitive::create(), PartGui::EllipsoidPrimitive::create(), PartGui::TorusPrimitive::create(), PartGui::PrismPrimitive::create(), PartGui::WedgePrimitive::create(), PartGui::HelixPrimitive::create(), PartGui::SpiralPrimitive::create(), PartGui::CirclePrimitive::create(), PartGui::EllipsePrimitive::create(), PartGui::PolygonPrimitive::create(), PartGui::LinePrimitive::create(), and PartGui::VertexPrimitive::create().