FreeCAD: Gui::ColorButton Class Reference
Gui::ColorButton Class Reference
#include <Widgets.h>
Public Slots
void onChooseColor ()
Signals
void changed ()
Public Member Functions
ColorButton (QWidget *parent=nullptr)
~ColorButton () override
void setColor (const QColor &)
QColor color () const
void setPackedColor (uint32_t)
uint32_t packedColor () const
void setAllowChangeColor (bool)
bool allowChangeColor () const
void setDrawFrame (bool)
bool drawFrame () const
void setAllowTransparency (bool)
bool allowTransparency () const
void setModal (bool)
bool isModal () const
void setAutoChangeColor (bool)
bool autoChangeColor () const
Protected Member Functions
void paintEvent (QPaintEvent *) override
Properties
QColor color
bool allowChangeColor
bool drawFrame
bool allowTransparency
Detailed Description
Implementation of a color button.
Author
Werner Mayer
Definition at line 225 of file Widgets.h.
Constructor & Destructor Documentation
ColorButton()
ColorButton::ColorButton (QWidget * parent = nullptr)
Constructs a colored button called name with parent parent.
Definition at line 632 of file Widgets.cpp.
References Gui::ColorButtonP::col, draftgeoutils.intersections::connect(), SCL.SimpleDataTypes::e, and onChooseColor().
~ColorButton()
ColorButton::~ColorButton () override
Destroys the button.
Definition at line 646 of file Widgets.cpp.
Member Function Documentation
allowChangeColor()
bool Gui::ColorButton::allowChangeColor () const
allowTransparency()
bool Gui::ColorButton::allowTransparency () const
autoChangeColor()
bool ColorButton::autoChangeColor () const
Definition at line 743 of file Widgets.cpp.
References Gui::ColorButtonP::autoChange.
changed
void Gui::ColorButton::changed () signal
Emits this signal when color has changed
Referenced by Gui::PropertyEditor::PropertyColorItem::createEditor(), Gui::PropertyEditor::PropertyMaterialItem::createEditor(), and Gui::PropertyEditor::PropertyMaterialListItem::createEditor().
color()
QColor Gui::ColorButton::color () const
Referenced by Path.Dressup.Gui.DogboneII.Marker::highlight(), Path.Dressup.Gui.Dogbone.Marker::highlight(), Path.Dressup.Gui.DogboneII.Marker::lowlight(), and Path.Dressup.Gui.Dogbone.Marker::lowlight().
drawFrame()
bool Gui::ColorButton::drawFrame () const
isModal()
bool ColorButton::isModal () const
Definition at line 733 of file Widgets.cpp.
References Gui::ColorButtonP::modal.
onChooseColor
void ColorButton::onChooseColor () slot
Opens a QColorDialog to set a new color.
Definition at line 832 of file Widgets.cpp.
References Gui::ColorButtonP::allowChange, and Gui::ColorButtonP::modal.
Referenced by ColorButton().
packedColor()
uint32_t ColorButton::packedColor () const
Returns the current packed color of the button.
Definition at line 687 of file Widgets.cpp.
References Gui::ColorButtonP::col, and color.
paintEvent()
void ColorButton::paintEvent (QPaintEvent * e) override protected
Draws the button label.
Definition at line 751 of file Widgets.cpp.
References Gui::ColorButtonP::col, color, Gui::ColorButtonP::dirty, Gui::ColorButtonP::drawFrame, SCL.SimpleDataTypes::e, buildPsets::p, and src.Mod.PartDesign.fcgear.svggear::w.
setAllowChangeColor()
void ColorButton::setAllowChangeColor (bool ok)
Definition at line 693 of file Widgets.cpp.
References Gui::ColorButtonP::allowChange.
setAllowTransparency()
void Gui::ColorButton::setAllowTransparency (bool allow)
Definition at line 713 of file Widgets.cpp.
setAutoChangeColor()
void ColorButton::setAutoChangeColor (bool on)
Definition at line 738 of file Widgets.cpp.
References Gui::ColorButtonP::autoChange.
setColor()
void ColorButton::setColor (const QColor & c)
Sets the color c to the button.
Definition at line 654 of file Widgets.cpp.
References SCL.SimpleDataTypes::c, Gui::ColorButtonP::col, and Gui::ColorButtonP::dirty.
Referenced by Gui::PrefColorButton::restorePreferences(), MatGui::DlgDisplayPropertiesImp::Private::setElementAppearance(), and MatGui::DlgDisplayPropertiesImp::Private::setElementColor().
setDrawFrame()
void ColorButton::setDrawFrame (bool ok)
Definition at line 703 of file Widgets.cpp.
References Gui::ColorButtonP::drawFrame.
setModal()
void ColorButton::setModal (bool b)
Definition at line 728 of file Widgets.cpp.
References SCL.SimpleDataTypes::b, and Gui::ColorButtonP::modal.
setPackedColor()
void ColorButton::setPackedColor (uint32_t c)
Sets the packed color c to the button.
Definition at line 672 of file Widgets.cpp.
References SCL.SimpleDataTypes::c, Gui::ColorButtonP::col, color, and Gui::ColorButtonP::dirty.
Property Documentation
allowChangeColor
bool ColorButton::allowChangeColor read write
Definition at line 230 of file Widgets.h.
allowTransparency
bool Gui::ColorButton::allowTransparency read write
Definition at line 232 of file Widgets.h.
Referenced by Gui::PrefColorButton::restorePreferences().
color
QColor ColorButton::color read write
Returns the current color of the button.
Definition at line 229 of file Widgets.h.
Referenced by draftguitools.gui_trimex.Trimex::finish(), importSVG.svgHandler::format(), DraftGui.DraftToolBar::getDefaultColor(), Path.Dressup.Gui.DogboneII.Marker::highlight(), Path.Dressup.Gui.Dogbone.Marker::highlight(), Path.Dressup.Gui.DogboneII.Marker::lowlight(), Path.Dressup.Gui.Dogbone.Marker::lowlight(), FeaturePython.ViewProviderOctahedron::onChanged(), ArchSpace._ViewProviderSpace::onChanged(), ArchPanel.ViewProviderPanelCut::onChanged(), ArchSite._ViewProviderSite::onChanged(), ArchPanel.ViewProviderPanelSheet::onChanged(), packedColor(), src.Mod.Test.unittestgui.ProgressBar::paint(), paintEvent(), Gui::PrefColorButton::restorePreferences(), Gui::PrefColorButton::savePreferences(), draftguitools.gui_trackers.Tracker::setColor(), draftguitools.gui_trackers.snapTracker::setColor(), draftguitools.gui_trackers.ghostTracker::setColor(), draftguitools.gui_trackers.editTracker::setColor(), Path.Dressup.Gui.Tags.HoldingTagMarker::setEnabled(), setPackedColor(), and DraftGui.DraftToolBar::setStyleButton().
drawFrame
bool ColorButton::drawFrame read write
Definition at line 231 of file Widgets.h.
The documentation for this class was generated from the following files:
Widgets.h
Widgets.cpp