FreeCAD: TechDrawGui::TaskCosmeticLine Class Reference
TechDrawGui::TaskCosmeticLine Class Reference
#include <TaskCosmeticLine.h>
Public Member Functions
TaskCosmeticLine (TechDraw::DrawViewPart *partFeat, std::vector< Base::Vector3d > points, std::vector< bool > is3d)
TaskCosmeticLine (TechDraw::DrawViewPart *partFeat, std::string edgeName)
~TaskCosmeticLine () override
virtual bool accept ()
virtual bool reject ()
void updateTask ()
Protected Member Functions
void changeEvent (QEvent *e) override
void setUiPrimary ()
void setUiEdit ()
void createCosmeticLine ()
void updateCosmeticLine ()
Detailed Description
Definition at line 52 of file TaskCosmeticLine.h.
Constructor & Destructor Documentation
TaskCosmeticLine() [1/2]
TaskCosmeticLine::TaskCosmeticLine (TechDraw::DrawViewPart * partFeat, std::vector< Base::Vector3d > points, std::vector< bool > is3d)
Definition at line 72 of file TaskCosmeticLine.cpp.
References setUiPrimary().
TaskCosmeticLine() [2/2]
TaskCosmeticLine::TaskCosmeticLine (TechDraw::DrawViewPart * partFeat, std::string edgeName)
Definition at line 49 of file TaskCosmeticLine.cpp.
References Base::Console(), Base::ConsoleSingleton::Error(), TechDraw::CosmeticExtension::getCosmeticEdgeBySelection(), and setUiEdit().
~TaskCosmeticLine()
TaskCosmeticLine::~TaskCosmeticLine () override
Definition at line 90 of file TaskCosmeticLine.cpp.
Member Function Documentation
accept()
bool TaskCosmeticLine::accept () virtual
Definition at line 244 of file TaskCosmeticLine.cpp.
References TechDraw::CosmeticExtension::add1CEToGE(), Gui::Command::commitCommand(), createCosmeticLine(), doCommand, Gui::Command::Gui, Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, TechDraw::CosmeticExtension::refreshCEGeoms(), TechDraw::DrawView::requestPaint(), Gui::Command::updateActive(), and updateCosmeticLine().
Referenced by TechDrawGui::TaskDlgCosmeticLine::accept().
changeEvent()
void TaskCosmeticLine::changeEvent (QEvent * e) override protected
Definition at line 104 of file TaskCosmeticLine.cpp.
References SCL.SimpleDataTypes::e.
createCosmeticLine()
void TaskCosmeticLine::createCosmeticLine () protected
Definition at line 174 of file TaskCosmeticLine.cpp.
References TechDraw::CosmeticExtension::addCosmeticEdge(), Gui::Command::commitCommand(), TechDraw::CosmeticExtension::getCosmeticEdge(), TechDraw::DrawViewPart::getCurrentCentroid(), TechDraw::DrawUtil::invertY(), Gui::Command::openCommand(), TechDraw::DrawViewPart::projectPoint(), Arch::QT_TRANSLATE_NOOP, TechDraw::CosmeticEdge::setFormat(), MovieTool::x, and MovieTool::y.
Referenced by accept().
reject()
bool TaskCosmeticLine::reject () virtual
Definition at line 266 of file TaskCosmeticLine.cpp.
References doCommand, and Gui::Command::Gui.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and TechDrawGui::TaskDlgCosmeticLine::reject().
setUiEdit()
void TaskCosmeticLine::setUiEdit () protected
Definition at line 153 of file TaskCosmeticLine.cpp.
References TechDraw::CosmeticEdge::permaEnd, TechDraw::CosmeticEdge::permaStart, Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by TaskCosmeticLine().
setUiPrimary()
void TaskCosmeticLine::setUiPrimary () protected
Definition at line 111 of file TaskCosmeticLine.cpp.
References TechDraw::DrawViewPart::getCurrentCentroid(), Base::Unit::Length, TechDraw::DrawViewPart::projectPoint(), Base::Vector3< float_type >::x, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by TaskCosmeticLine().
updateCosmeticLine()
void TaskCosmeticLine::updateCosmeticLine () protected
Definition at line 208 of file TaskCosmeticLine.cpp.
References TechDraw::BaseGeom::baseFactory(), TechDraw::DrawViewPart::getCurrentCentroid(), TechDraw::DrawUtil::invertY(), TechDraw::CosmeticEdge::m_geometry, TechDraw::CosmeticEdge::permaEnd, TechDraw::CosmeticEdge::permaStart, TechDraw::DrawViewPart::projectPoint(), MovieTool::x, Base::Vector3< float_type >::x, MovieTool::y, Base::Vector3< float_type >::y, and Base::Vector3< float_type >::z.
Referenced by accept().
updateTask()
void TaskCosmeticLine::updateTask ()
Definition at line 97 of file TaskCosmeticLine.cpp.
The documentation for this class was generated from the following files:
TaskCosmeticLine.h
TaskCosmeticLine.cpp