FreeCAD: cLineSegment Struct Reference
cLineSegment Struct Reference
#include <VolSim.h>
Public Member Functions
cLineSegment ()
cLineSegment (Point3D &p1, Point3D &p2)
void SetPoints (Point3D &p1, Point3D &p2)
void PointAt (float dist, Point3D &retp)
Public Attributes
Point3D pStart
Point3D pDir
Point3D pDirXY
float len
float lenXY
Detailed Description
Definition at line 153 of file VolSim.h.
Constructor & Destructor Documentation
cLineSegment() [1/2]
cLineSegment::cLineSegment () inline
Definition at line 155 of file VolSim.h.
cLineSegment() [2/2]
cLineSegment::cLineSegment (Point3D & p1, Point3D & p2) inline
Definition at line 159 of file VolSim.h.
References SetPoints().
Member Function Documentation
PointAt()
void cLineSegment::PointAt (float dist, Point3D & retp)
Definition at line 683 of file VolSim.cpp.
References DraftVecUtils::dist(), pDir, pStart, Point3D::x, Point3D::y, and Point3D::z.
SetPoints()
void cLineSegment::SetPoints (Point3D & p1, Point3D & p2)
Definition at line 671 of file VolSim.cpp.
References len, length(), lenXY, pDir, pDirXY, pStart, SIM_EPSILON, unit(), Point3D::x, and Point3D::y.
Referenced by cLineSegment().
Member Data Documentation
len
float cLineSegment::len
Definition at line 168 of file VolSim.h.
Referenced by SetPoints().
lenXY
float cLineSegment::lenXY
Definition at line 169 of file VolSim.h.
Referenced by SetPoints().
pDir
Point3D cLineSegment::pDir
Definition at line 166 of file VolSim.h.
Referenced by PointAt(), and SetPoints().
pDirXY
Point3D cLineSegment::pDirXY
Definition at line 167 of file VolSim.h.
Referenced by SetPoints().
pStart
Point3D cLineSegment::pStart
Definition at line 165 of file VolSim.h.
Referenced by PointAt(), and SetPoints().
The documentation for this struct was generated from the following files:
VolSim.h
VolSim.cpp