FreeCAD: Part::PropertyShapeCache Class Reference
Part::PropertyShapeCache Class Reference
#include <PropertyTopoShape.h>
Public Member Functions
virtual App::Property * Copy (void) const override
Returns a new copy of the property (mainly for Undo/Redo and transactions)
virtual void Paste (const App::Property &) override
Paste the value from the property (mainly for Undo/Redo and transactions)
virtual PyObject * getPyObject () override
virtual void setPyObject (PyObject *value) override
virtual void Save (Base::Writer &writer) const override
virtual void Restore (Base::XMLReader &reader) override
Public Member Functions inherited from App::Property
Property ()
~Property () override
unsigned int getMemSize () const override
const char * getName () const
bool hasName () const
std::string getFullName () const
virtual const char * getEditorName () const
Get the class name of the associated property editor item.
short getType () const
Get the type of the property in the container.
const char * getGroup () const
Get the group of this property.
const char * getDocumentation () const
Get the documentation of this property.
void setContainer (PropertyContainer *Father)
Is called by the framework to set the father (container)
PropertyContainer * getContainer () const
Get a pointer to the PropertyContainer derived class the property belongs to.
virtual void setPathValue (const App::ObjectIdentifier &path, const boost::any &value)
Set value of property.
virtual const boost::any getPathValue (const App::ObjectIdentifier &path) const
Get value of property.
virtual bool getPyPathValue (const App::ObjectIdentifier &, Py::Object &) const
Get Python value of property.
virtual App::ObjectIdentifier canonicalPath (const App::ObjectIdentifier &p) const
Convert p to a canonical representation of it.
virtual void getPaths (std::vector< App::ObjectIdentifier > &paths) const
Get valid paths for this property; used by auto completer.
virtual void afterRestore ()
virtual void onContainerRestored ()
void touch ()
Set the property touched.
bool isTouched () const
Test if this property is touched.
void purgeTouched ()
Reset this property touched.
unsigned long getStatus () const
return the status bits
bool testStatus (Status pos) const
void setStatus (Status pos, bool on)
void setStatusValue (unsigned long status)
void setReadOnly (bool readOnly)
Sets property editable/grayed out in property editor.
bool isReadOnly () const
void setSinglePrecision (bool single)
bool isSinglePrecision () const
Gets precision of properties using floating point numbers.
virtual void hasSetChildValue (Property &)
Called when a child property has changed value.
virtual void aboutToSetChildValue (Property &)
Called before a child property changing value.
virtual bool isSame (const Property &other) const
Compare if this property has the same content as the given one.
int64_t getID () const
virtual void beforeSave () const
Property (const Property &)=delete
Property & operator= (const Property &)=delete
Public Member Functions inherited from Base::Persistence
virtual Base::Type getTypeId (void) const
virtual void SaveDocFile (Writer &) const
virtual void RestoreDocFile (Reader &)
void dumpToStream (std::ostream &stream, int compression)
void restoreFromStream (std::istream &stream)
Public Member Functions inherited from Base::BaseClass
bool isDerivedFrom (const Type type) const
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static PropertyShapeCache * get (const App::DocumentObject *obj, bool create)
static bool getShape (const App::DocumentObject *obj, TopoShape &shape, const char *subname=0)
static void setShape (const App::DocumentObject *obj, const TopoShape &shape, const char *subname=0)
Static Public Member Functions inherited from App::Property
static void destroy (Property *p)
For safe deleting of a dynamic property.
static bool isValidName (const char *name)
Static Public Member Functions inherited from Base::Persistence
static Base::Type getClassTypeId (void)
static void init (void)
static void * create (void)
static std::string encodeAttribute (const std::string &)
Encodes an attribute upon saving.
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Additional Inherited Members
Public Types inherited from App::Property
enum Status {
Touched = 0, Immutable = 1, ReadOnly = 2, Hidden = 3,
Transient = 4, MaterialEdit = 5, NoMaterialListEdit = 6, Output = 7,
LockDynamic = 8, NoModify = 9, PartialTrigger = 10, NoRecompute = 11,
Single = 12, Ordered = 13, EvalOnRestore = 14, Busy = 15,
CopyOnChange, UserEdit = 17, PropStaticBegin = 21, PropDynamic = 21,
PropNoPersist = 22, PropNoRecompute = 23, PropReadOnly = 24, PropTransient = 25,
PropHidden = 26, PropOutput = 27, PropStaticEnd = 28, User1 = 28,
User2 = 29, User3 = 30, User4 = 31
}
Public Attributes inherited from App::Property
boost::signals2::signal< void(const App::Property &)> signalChanged
Protected Member Functions inherited from App::Property
virtual void hasSetValue ()
Gets called by all setValue() methods after the value has changed.
virtual void aboutToSetValue ()
Gets called by all setValue() methods before the value has changed.
virtual void verifyPath (const App::ObjectIdentifier &p) const
Verify a path for the current property.
std::string getFileName (const char *postfix=0, const char *prefix=0) const
Return a file name suitable for saving this property.
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from App::Property
std::bitset< 32 > StatusBits
Detailed Description
Definition at line 280 of file PropertyTopoShape.h.
Member Function Documentation
Copy()
App::Property * PropertyShapeCache::Copy (void) const override virtual
Returns a new copy of the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 870 of file PropertyTopoShape.cpp.
get()
PropertyShapeCache * PropertyShapeCache::get (const App::DocumentObject * obj, bool create) static
Find or create the shape cache for a document object
Parameters
obj The document object
create True if we should create the cache if it doesn't exist
Returns
The shape cache, or null if we aren't creating and it doesn't exist
Definition at line 921 of file PropertyTopoShape.cpp.
References draftgeoutils.faces::bind(), Base::Persistence::create(), FC_ERR, App::PropertyContainer::getDynamicPropertyByName(), App::DocumentObject::getFullName(), App::Prop_Hidden, App::Prop_NoPersist, App::Prop_Output, and SHAPE_CACHE_NAME.
Referenced by getShape(), and setShape().
getPyObject()
PyObject * PropertyShapeCache::getPyObject () override virtual
Make a new python List with a tuple for each cache entry containing the key and the shape
Returns
the python list
Reimplemented from Base::BaseClass.
Definition at line 890 of file PropertyTopoShape.cpp.
References Py::new_reference_to(), Part::shape2pyshape(), src.Mod.Test.testmakeWireString::String, and TestSpreadsheet::v.
getShape()
bool PropertyShapeCache::getShape (const App::DocumentObject * obj, TopoShape & shape, const char * subname = 0) static
Look up and return a shape in the cache
Parameters
obj The document object to look in
shape The found shape is returned here
subname The key to look up
Returns
True if the name was found
Definition at line 948 of file PropertyTopoShape.cpp.
References get(), and Part::TopoShape::isNull().
Referenced by _getTopoShape().
Paste()
void PropertyShapeCache::Paste (const App::Property & from) override virtual
Paste the value from the property (mainly for Undo/Redo and transactions)
Implements App::Property.
Definition at line 874 of file PropertyTopoShape.cpp.
Restore()
void PropertyShapeCache::Restore (Base::XMLReader &) override virtual
This method is used to restore properties from an XML document. It uses the XMLReader class, which bases on SAX, to read the in Save() written information. Again the Vector as an example:
void PropertyVector::Restore(Base::XMLReader &reader)
{
  // read my Element
  reader.readElement("PropertyVector");
  // get the value of my Attribute
  _cVec.x = reader.getAttributeAsFloat("valueX");
  _cVec.y = reader.getAttributeAsFloat("valueY");
  _cVec.z = reader.getAttributeAsFloat("valueZ");
}
Implements Base::Persistence.
Definition at line 882 of file PropertyTopoShape.cpp.
Save()
void PropertyShapeCache::Save (Base::Writer &) const override virtual
This method is used to save properties to an XML document. A good example you'll find in PropertyStandard.cpp, e.g. the vector:
void PropertyVector::Save (Writer &writer) const
{
   writer << writer.ind() << "<PropertyVector valueX=\"" <<  _cVec.x <<
                                          "\" valueY=\"" <<  _cVec.y <<
                                          "\" valueZ=\"" <<  _cVec.z <<"\"/>" << endl;
}
The writer.ind() expression writes the indentation, just for pretty printing of the XML. As you see, the writing of the XML document is not done with a DOM implementation because of performance reasons. Therefore the programmer has to take care that a valid XML document is written. This means closing tags and writing UTF-8.
See also
Base::Writer
Implements Base::Persistence.
Definition at line 878 of file PropertyTopoShape.cpp.
setPyObject()
void PropertyShapeCache::setPyObject (PyObject * value) override virtual
Remove the cache entries for every element in the list
Parameters
value A python list of entry names
Reimplemented from Base::BaseClass.
Definition at line 901 of file PropertyTopoShape.cpp.
References App::PropertyListsT< T, ListT, ParentT >::getValues(), and App::PropertyListsT< T, ListT, ParentT >::setPyObject().
setShape()
void PropertyShapeCache::setShape (const App::DocumentObject * obj, const TopoShape & shape, const char * subname = 0) static
Find or create the property shape cache in a document object and then add an entry
Parameters
obj The Object
shape The shape to cache
subname The key to point at that shape
Definition at line 971 of file PropertyTopoShape.cpp.
References get().
Referenced by _getTopoShape().
The documentation for this class was generated from the following files:
PropertyTopoShape.h
PropertyTopoShape.cpp