FreeCAD: AppPartDesignGui.cpp File Reference
AppPartDesignGui.cpp File Reference
#include "PreCompiled.h"
#include <CXX/Extensions.hxx>
#include <CXX/Objects.hxx>
#include <Base/Console.h>
#include <Base/Interpreter.h>
#include <Base/PyObjectBase.h>
#include <Gui/Application.h>
#include <Gui/Language/Translator.h>
#include "Workbench.h"
#include "ViewProviderBase.h"
#include "ViewProviderBody.h"
#include "ViewProviderBoolean.h"
#include "ViewProviderChamfer.h"
#include "ViewProviderDatumCS.h"
#include "ViewProviderDatumLine.h"
#include "ViewProviderDatumPlane.h"
#include "ViewProviderDatumPoint.h"
#include "ViewProviderDraft.h"
#include "ViewProviderDressUp.h"
#include "ViewProviderFillet.h"
#include "ViewProviderGroove.h"
#include "ViewProviderHelix.h"
#include "ViewProviderHole.h"
#include "ViewProviderLinearPattern.h"
#include "ViewProviderLoft.h"
#include "ViewProviderMirrored.h"
#include "ViewProviderMultiTransform.h"
#include "ViewProviderPad.h"
#include "ViewProviderPipe.h"
#include "ViewProviderPocket.h"
#include "ViewProviderPolarPattern.h"
#include "ViewProviderPrimitive.h"
#include "ViewProviderRevolution.h"
#include "ViewProviderScaled.h"
#include "ViewProviderShapeBinder.h"
#include "ViewProviderSketchBased.h"
#include "ViewProviderThickness.h"
#include "ViewProviderTransformed.h"
Classes
class PartDesignGui::Module
Namespaces
PartDesignGui
Functions
void CreatePartDesignCommands ()
void CreatePartDesignBodyCommands ()
void CreatePartDesignPrimitiveCommands ()
void loadPartDesignResource ()
PyObject * PartDesignGui::initModule ()
PyMOD_INIT_FUNC (PartDesignGui)
Function Documentation
CreatePartDesignBodyCommands()
void CreatePartDesignBodyCommands ()
Definition at line 985 of file CommandBody.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
CreatePartDesignCommands()
void CreatePartDesignCommands ()
Definition at line 2448 of file Mod/PartDesign/Gui/Command.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
CreatePartDesignPrimitiveCommands()
void CreatePartDesignPrimitiveCommands ()
Definition at line 391 of file CommandPrimitive.cpp.
References Gui::CommandManager::addCommand(), Gui::Application::commandManager(), and Gui::Application::Instance.
Referenced by PyMOD_INIT_FUNC().
loadPartDesignResource()
void loadPartDesignResource ()
Definition at line 71 of file AppPartDesignGui.cpp.
References Gui::Translator::instance(), and Gui::Translator::refresh().
Referenced by PyMOD_INIT_FUNC().
PyMOD_INIT_FUNC()
PyMOD_INIT_FUNC (PartDesignGui)
Definition at line 102 of file AppPartDesignGui.cpp.
References Base::Console(), CreatePartDesignBodyCommands(), CreatePartDesignCommands(), CreatePartDesignPrimitiveCommands(), SCL.SimpleDataTypes::e, SIM::Coin3D::Quarter::Quarter::init(), Base::Persistence::init(), Base::BaseClass::init(), App::Extension::init(), PartDesignGui::initModule(), Gui::Application::Instance, Base::Interpreter(), loadPartDesignResource(), Base::ConsoleSingleton::Log(), mod, PyMOD_Return, and Base::InterpreterSingleton::runString().