FreeCAD: Gui::Multisample Class Reference
Gui::Multisample Class Reference
#include <Multisample.h>
Public Member Functions
Multisample ()
bool testSamples (int num) const
std::vector< std::pair< QString, AntiAliasing > > supported () const
Static Public Member Functions
static int toSamples (AntiAliasing msaa)
static AntiAliasing toAntiAliasing (int samples)
static AntiAliasing readMSAAFromSettings ()
static void writeMSAAToSettings (AntiAliasing msaa)
Detailed Description
Definition at line 72 of file Multisample.h.
Constructor & Destructor Documentation
Multisample()
Multisample::Multisample ()
Definition at line 51 of file Multisample.cpp.
Member Function Documentation
readMSAAFromSettings()
AntiAliasing Multisample::readMSAAFromSettings () static
Definition at line 110 of file Multisample.cpp.
References App::GetApplication(), ParameterGrp::GetInt(), App::Application::GetParameterGroupByPath(), and Gui::None.
Referenced by Gui::View3DInventorViewer::getNumSamples().
supported()
std::vector< std::pair< QString, AntiAliasing > > Multisample::supported () const
Definition at line 75 of file Multisample.cpp.
References modes, and textMSAA.
testSamples()
bool Multisample::testSamples (int num) const
Definition at line 61 of file Multisample.cpp.
toAntiAliasing()
AntiAliasing Multisample::toAntiAliasing (int samples) static
Definition at line 99 of file Multisample.cpp.
References Gui::None, and textMSAA.
toSamples()
int Multisample::toSamples (AntiAliasing msaa) static
Definition at line 88 of file Multisample.cpp.
References textMSAA.
Referenced by Gui::View3DInventorViewer::getNumSamples().
writeMSAAToSettings()
void Multisample::writeMSAAToSettings (AntiAliasing msaa) static
Definition at line 117 of file Multisample.cpp.
References App::GetApplication(), App::Application::GetParameterGroupByPath(), and ParameterGrp::SetInt().
The documentation for this class was generated from the following files:
Multisample.h
Multisample.cpp