FreeCAD: StrX Class Reference
StrX Class Reference
#include <XMLTools.h>
Public Member Functions
StrX (const XMLCh *const toTranscode)
~StrX ()
const char * c_str () const
Getter method.
Detailed Description
Definition at line 69 of file XMLTools.h.
Constructor & Destructor Documentation
StrX()
StrX::StrX (const XMLCh *const toTranscode) inline explicit
Definition at line 90 of file XMLTools.h.
~StrX()
StrX::~StrX () inline
Definition at line 94 of file XMLTools.h.
References XERCES_CPP_NAMESPACE_QUALIFIER.
Member Function Documentation
c_str()
const char * StrX::c_str () const inline
Getter method.
Definition at line 103 of file XMLTools.h.
Referenced by ParameterGrp::_SetAttribute(), Base::XMLReader::characters(), ParameterGrp::Clear(), ParameterGrp::CreateElement(), Base::XMLReader::endElement(), ParameterGrp::FindElement(), ParameterGrp::FindNextElement(), ParameterGrp::GetAttribute(), ParameterGrp::GetAttributeMap(), ParameterGrp::GetBoolMap(), ParameterGrp::GetBools(), ParameterGrp::GetFloatMap(), ParameterGrp::GetFloats(), ParameterGrp::GetGroups(), App::ProjectFile::getInputFiles(), ParameterGrp::GetIntMap(), ParameterGrp::GetInts(), App::ProjectFile::getObjects(), App::ProjectFile::getObjectsOfType(), ParameterGrp::GetParameterNames(), App::ProjectFile::getPropertyFiles(), App::ProjectFile::getTypeId(), ParameterGrp::GetUnsignedMap(), ParameterGrp::GetUnsigneds(), operator<<(), and Base::XMLReader::startElement().
The documentation for this class was generated from the following file:
XMLTools.h