FreeCAD: MeshCore::ReaderOBJ Class Reference
MeshCore::ReaderOBJ Class Reference
#include <ReaderOBJ.h>
Public Member Functions
ReaderOBJ (MeshKernel &kernel, Material *)
ReaderOBJ.
bool Load (std::istream &str)
Load the mesh from the input stream.
bool LoadMaterial (std::istream &str)
Load the material file to the corresponding OBJ file. This function must be called after Load().
const std::vector< std::string > & GetGroupNames () const
Detailed Description
Loads the mesh object from data in OBJ format.
Definition at line 58 of file ReaderOBJ.h.
Constructor & Destructor Documentation
ReaderOBJ()
ReaderOBJ::ReaderOBJ (MeshKernel & kernel, Material * material) explicit
ReaderOBJ.
Definition at line 40 of file ReaderOBJ.cpp.
Member Function Documentation
GetGroupNames()
const std::vector<std::string>& MeshCore::ReaderOBJ::GetGroupNames () const inline
Definition at line 78 of file ReaderOBJ.h.
Load()
bool ReaderOBJ::Load (std::istream & str)
Load the mesh from the input stream.
Returns
true on success and false otherwise
Definition at line 45 of file ReaderOBJ.cpp.
References MeshCore::MeshKernel::Adopt(), SCL.SimpleDataTypes::b, MeshCore::Material::binding, SCL.SimpleDataTypes::c, MeshCore::MeshKernel::Clear(), MeshCore::Material::diffuseColor, Base::Tools::escapedUnicodeToUtf8(), toolbit-attributes::g, importOCA::getline(), MeshCore::Material::library, MeshCore::MeshIO::OVERALL, MeshCore::MeshIO::PER_FACE, MeshCore::MeshIO::PER_VERTEX, MeshCore::MeshCleanup::RemoveInvalids(), MeshCore::MeshPointFacetAdjacency::SetFacetNeighbourhood(), MeshCore::MeshCleanup::SetMaterial(), MeshCore::MeshFacet::SetProperty(), MeshCore::MeshPointArray::SetProperty(), MeshCore::MeshFacet::SetVertices(), and Path.Post.scripts.refactored_centroid_post::str.
LoadMaterial()
bool ReaderOBJ::LoadMaterial (std::istream & str)
Load the material file to the corresponding OBJ file. This function must be called after Load().
Parameters
str
Returns
true on success and false otherwise
Definition at line 245 of file ReaderOBJ.cpp.
References a, MeshCore::Material::ambientColor, SCL.SimpleDataTypes::b, MeshCore::Material::binding, MeshCore::Material::diffuseColor, Base::Tools::escapedUnicodeToUtf8(), toolbit-attributes::g, importOCA::getline(), MeshCore::MeshIO::OVERALL, MeshCore::MeshIO::PER_FACE, MeshCore::Material::specularColor, Path.Post.scripts.refactored_centroid_post::str, femtools.tokrules::tokens, and MeshCore::Material::transparency.
The documentation for this class was generated from the following files:
ReaderOBJ.h
ReaderOBJ.cpp