FreeCAD: Gui::SoFCColorBarNotifier Class Reference
Gui::SoFCColorBarNotifier Class Reference
#include <SoFCColorBarNotifier.h>
Public Member Functions
void attach (SoFCColorBarBase *bar)
void detach (SoFCColorBarBase *bar)
void OnChange (ParameterGrp::SubjectType &caller, ParameterGrp::MessageType reason) override
Static Public Member Functions
static SoFCColorBarNotifier & instance ()
Detailed Description
Definition at line 53 of file SoFCColorBarNotifier.h.
Member Function Documentation
attach()
void SoFCColorBarNotifier::attach (SoFCColorBarBase * bar)
Definition at line 44 of file SoFCColorBarNotifier.cpp.
References Base::Subject< MsgType >::Notify().
Referenced by Path.Dressup.Gui.Boundary.DressupPathBoundaryViewProvider::__init__(), FemGui::ViewProviderFemPostObject::ViewProviderFemPostObject(), InspectionGui::ViewProviderInspection::ViewProviderInspection(), and MeshGui::ViewProviderMeshCurvature::ViewProviderMeshCurvature().
detach()
void SoFCColorBarNotifier::detach (SoFCColorBarBase * bar)
Definition at line 52 of file SoFCColorBarNotifier.cpp.
References RobotExample::pos.
instance()
SoFCColorBarNotifier & SoFCColorBarNotifier::instance () static
Definition at line 32 of file SoFCColorBarNotifier.cpp.
Referenced by FemGui::ViewProviderFemPostObject::ViewProviderFemPostObject(), InspectionGui::ViewProviderInspection::ViewProviderInspection(), and MeshGui::ViewProviderMeshCurvature::ViewProviderMeshCurvature().
OnChange()
void SoFCColorBarNotifier::OnChange (ParameterGrp::SubjectType & caller, ParameterGrp::MessageType reason) override
Definition at line 61 of file SoFCColorBarNotifier.cpp.
References toolbit-attributes::grp, Gui::SoLabelTextFormat::textColor, and Gui::SoLabelTextFormat::textSize.
The documentation for this class was generated from the following files:
SoFCColorBarNotifier.h
SoFCColorBarNotifier.cpp