FreeCAD: PartGui::AbstractPrimitive Class Reference
PartGui::AbstractPrimitive Class Reference abstract
#include <DlgPrimitives.h>
Public Member Functions
AbstractPrimitive (Part::Primitive *feature=nullptr)
~AbstractPrimitive () override=default
bool hasValidPrimitive () const
virtual const char * getDefaultName () const =0
virtual QString create (const QString &objectName, const QString &placement) const =0
virtual QString change (const QString &objectName, const QString &placement) const =0
virtual void changeValue (QObject *)=0
Protected Member Functions
void connectSignalMapper (QSignalMapper *mapper)
Protected Attributes
App::DocumentObjectWeakPtrT featurePtr
Detailed Description
Definition at line 77 of file DlgPrimitives.h.
Constructor & Destructor Documentation
AbstractPrimitive()
AbstractPrimitive::AbstractPrimitive (Part::Primitive * feature = nullptr)
Definition at line 206 of file DlgPrimitives.cpp.
~AbstractPrimitive()
PartGui::AbstractPrimitive::~AbstractPrimitive () override default
Member Function Documentation
change()
virtual QString PartGui::AbstractPrimitive::change (const QString & objectName, const QString & placement) const pure virtual
Implemented in PartGui::VertexPrimitive, PartGui::LinePrimitive, PartGui::PolygonPrimitive, PartGui::EllipsePrimitive, PartGui::CirclePrimitive, PartGui::SpiralPrimitive, PartGui::HelixPrimitive, PartGui::WedgePrimitive, PartGui::PrismPrimitive, PartGui::TorusPrimitive, PartGui::EllipsoidPrimitive, PartGui::SpherePrimitive, PartGui::ConePrimitive, PartGui::CylinderPrimitive, PartGui::BoxPrimitive, and PartGui::PlanePrimitive.
changeValue()
virtual void PartGui::AbstractPrimitive::changeValue (QObject *) pure virtual
Implemented in PartGui::VertexPrimitive, PartGui::LinePrimitive, PartGui::PolygonPrimitive, PartGui::EllipsePrimitive, PartGui::CirclePrimitive, PartGui::SpiralPrimitive, PartGui::HelixPrimitive, PartGui::WedgePrimitive, PartGui::PrismPrimitive, PartGui::TorusPrimitive, PartGui::EllipsoidPrimitive, PartGui::SpherePrimitive, PartGui::ConePrimitive, PartGui::CylinderPrimitive, PartGui::BoxPrimitive, and PartGui::PlanePrimitive.
Referenced by connectSignalMapper().
connectSignalMapper()
void AbstractPrimitive::connectSignalMapper (QSignalMapper * mapper) protected
Definition at line 216 of file DlgPrimitives.cpp.
References changeValue(), and draftgeoutils.intersections::connect().
Referenced by PartGui::BoxPrimitive::BoxPrimitive(), PartGui::CirclePrimitive::CirclePrimitive(), PartGui::ConePrimitive::ConePrimitive(), PartGui::CylinderPrimitive::CylinderPrimitive(), PartGui::EllipsePrimitive::EllipsePrimitive(), PartGui::EllipsoidPrimitive::EllipsoidPrimitive(), PartGui::HelixPrimitive::HelixPrimitive(), PartGui::LinePrimitive::LinePrimitive(), PartGui::PlanePrimitive::PlanePrimitive(), PartGui::PolygonPrimitive::PolygonPrimitive(), PartGui::PrismPrimitive::PrismPrimitive(), PartGui::SpherePrimitive::SpherePrimitive(), PartGui::SpiralPrimitive::SpiralPrimitive(), PartGui::TorusPrimitive::TorusPrimitive(), PartGui::VertexPrimitive::VertexPrimitive(), and PartGui::WedgePrimitive::WedgePrimitive().
create()
virtual QString PartGui::AbstractPrimitive::create (const QString & objectName, const QString & placement) const pure virtual
Implemented in PartGui::VertexPrimitive, PartGui::LinePrimitive, PartGui::PolygonPrimitive, PartGui::EllipsePrimitive, PartGui::CirclePrimitive, PartGui::SpiralPrimitive, PartGui::HelixPrimitive, PartGui::WedgePrimitive, PartGui::PrismPrimitive, PartGui::TorusPrimitive, PartGui::EllipsoidPrimitive, PartGui::SpherePrimitive, PartGui::ConePrimitive, PartGui::CylinderPrimitive, PartGui::BoxPrimitive, and PartGui::PlanePrimitive.
getDefaultName()
virtual const char* PartGui::AbstractPrimitive::getDefaultName () const pure virtual
Implemented in PartGui::VertexPrimitive, PartGui::LinePrimitive, PartGui::PolygonPrimitive, PartGui::EllipsePrimitive, PartGui::CirclePrimitive, PartGui::SpiralPrimitive, PartGui::HelixPrimitive, PartGui::WedgePrimitive, PartGui::PrismPrimitive, PartGui::TorusPrimitive, PartGui::EllipsoidPrimitive, PartGui::SpherePrimitive, PartGui::ConePrimitive, PartGui::CylinderPrimitive, PartGui::BoxPrimitive, and PartGui::PlanePrimitive.
hasValidPrimitive()
bool AbstractPrimitive::hasValidPrimitive () const
Definition at line 211 of file DlgPrimitives.cpp.
References App::DocumentObjectWeakPtrT::expired(), and featurePtr.
Member Data Documentation
featurePtr
App::DocumentObjectWeakPtrT PartGui::AbstractPrimitive::featurePtr protected
Definition at line 95 of file DlgPrimitives.h.
Referenced by PartGui::PlanePrimitive::changeValue(), PartGui::BoxPrimitive::changeValue(), PartGui::CylinderPrimitive::changeValue(), PartGui::ConePrimitive::changeValue(), PartGui::SpherePrimitive::changeValue(), PartGui::EllipsoidPrimitive::changeValue(), PartGui::TorusPrimitive::changeValue(), PartGui::PrismPrimitive::changeValue(), PartGui::WedgePrimitive::changeValue(), PartGui::HelixPrimitive::changeValue(), PartGui::SpiralPrimitive::changeValue(), PartGui::CirclePrimitive::changeValue(), PartGui::EllipsePrimitive::changeValue(), PartGui::PolygonPrimitive::changeValue(), PartGui::LinePrimitive::changeValue(), PartGui::VertexPrimitive::changeValue(), and hasValidPrimitive().
The documentation for this class was generated from the following files:
DlgPrimitives.h
DlgPrimitives.cpp