FreeCAD: PartDesignGui::TaskDlgFeaturePick Class Reference
PartDesignGui::TaskDlgFeaturePick Class Reference
simulation dialog for the TaskView
#include <TaskFeaturePick.h>
Public Member Functions
TaskDlgFeaturePick (std::vector< App::DocumentObject * > &objects, const std::vector< TaskFeaturePick::featureStatus > &status, std::function< bool(std::vector< App::DocumentObject * >)> acceptfunc, std::function< void(std::vector< App::DocumentObject * >)> workfunc, bool singleFeatureSelect, std::function< void(void)> abortfunc=0)
~TaskDlgFeaturePick () override
void open () override
is called the TaskView when the dialog is opened
void clicked (int) override
is called by the framework if an button is clicked which has no accept or reject role
bool accept () override
is called by the framework if the dialog is accepted (Ok)
bool reject () override
is called by the framework if the dialog is rejected (Cancel)
bool isAllowedAlterDocument () const override
is called by the framework if the user presses the help button
void showExternal (bool val)
QDialogButtonBox::StandardButtons getStandardButtons () const override
returns for Close and Help button
Public Member Functions inherited from Gui::TaskView::TaskDialog
TaskDialog ()
~TaskDialog () override
QWidget * addTaskBox (QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBox (const QPixmap &icon, QWidget *widget, bool expandable=true, QWidget *parent=nullptr)
QWidget * addTaskBoxWithoutHeader (QWidget *widget)
void setButtonPosition (ButtonPosition p)
ButtonPosition buttonPosition () const
const std::vector< QWidget * > & getDialogContent () const
bool canClose () const
virtual void modifyStandardButtons (QDialogButtonBox *)
void setEscapeButtonEnabled (bool on)
Defines whether a task dialog can be rejected by pressing Esc.
bool isEscapeButtonEnabled () const
void setAutoCloseOnTransactionChange (bool on)
bool isAutoCloseOnTransactionChange () const
void setAutoCloseOnDeletedDocument (bool on)
bool isAutoCloseOnDeletedDocument () const
const std::string & getDocumentName () const
void setDocumentName (const std::string &doc)
void setAutoCloseOnClosedView (bool on)
bool isAutoCloseOnClosedView () const
void associateToObject3dView (App::DocumentObject *obj)
const Gui::MDIView * getAssociatedView () const
void setAssociatedView (const Gui::MDIView *view)
virtual bool isAllowedAlterView () const
virtual bool isAllowedAlterSelection () const
virtual bool needsFullSpace () const
virtual void closed ()
is called by the framework when the dialog is closed
virtual void autoClosedOnTransactionChange ()
virtual void autoClosedOnDeletedDocument ()
virtual void autoClosedOnClosedView ()
virtual void helpRequested ()
is called by the framework if the user press the help button
void emitDestructionSignal ()
Protected Attributes
TaskFeaturePick * pick
bool accepted
std::function< bool(std::vector< App::DocumentObject * >)> acceptFunction
std::function< void(std::vector< App::DocumentObject * >)> workFunction
std::function< void(void)> abortFunction
Protected Attributes inherited from Gui::TaskView::TaskDialog
QPointer< QDialogButtonBox > buttonBox
std::vector< QWidget * > Content
List of TaskBoxes of that dialog.
ButtonPosition pos
Additional Inherited Members
Public Types inherited from Gui::TaskView::TaskDialog
enum ButtonPosition { North, South }
Signals inherited from Gui::TaskView::TaskDialog
void aboutToBeDestroyed ()
Detailed Description
simulation dialog for the TaskView
Definition at line 123 of file TaskFeaturePick.h.
Constructor & Destructor Documentation
TaskDlgFeaturePick()
TaskDlgFeaturePick::TaskDlgFeaturePick (std::vector< App::DocumentObject * > & objects, const std::vector< TaskFeaturePick::featureStatus > & status, std::function< bool(std::vector< App::DocumentObject * >)> acceptfunc, std::function< void(std::vector< App::DocumentObject * >)> workfunc, bool singleFeatureSelect, std::function< void(void)> abortfunc = 0)
Definition at line 613 of file TaskFeaturePick.cpp.
References abortFunction, acceptFunction, Gui::TaskView::TaskDialog::Content, importers.importIFCmulticore::objects, pick, and workFunction.
~TaskDlgFeaturePick()
TaskDlgFeaturePick::~TaskDlgFeaturePick () override
Definition at line 630 of file TaskFeaturePick.cpp.
References abortFunction, accepted, PartDesignGui::TaskFeaturePick::buildFeatures(), Gui::TaskView::TaskDialog::Content, pick, and workFunction.
Member Function Documentation
accept()
bool TaskDlgFeaturePick::accept () override virtual
is called by the framework if the dialog is accepted (Ok)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 668 of file TaskFeaturePick.cpp.
References accepted, acceptFunction, PartDesignGui::TaskFeaturePick::getFeatures(), and pick.
clicked()
void TaskDlgFeaturePick::clicked (int) override virtual
is called by the framework if an button is clicked which has no accept or reject role
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 665 of file TaskFeaturePick.cpp.
getStandardButtons()
QDialogButtonBox::StandardButtons PartDesignGui::TaskDlgFeaturePick::getStandardButtons () const inline override virtual
returns for Close and Help button
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 152 of file TaskFeaturePick.h.
isAllowedAlterDocument()
bool PartDesignGui::TaskDlgFeaturePick::isAllowedAlterDocument () const inline override virtual
is called by the framework if the user presses the help button
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 146 of file TaskFeaturePick.h.
open()
void TaskDlgFeaturePick::open () override virtual
is called the TaskView when the dialog is opened
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 662 of file TaskFeaturePick.cpp.
reject()
bool TaskDlgFeaturePick::reject () override virtual
is called by the framework if the dialog is rejected (Cancel)
Reimplemented from Gui::TaskView::TaskDialog.
Definition at line 674 of file TaskFeaturePick.cpp.
References accepted.
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action().
showExternal()
void TaskDlgFeaturePick::showExternal (bool val)
Definition at line 680 of file TaskFeaturePick.cpp.
References pick, PartDesignGui::TaskFeaturePick::showExternal(), and toolbit-attributes::val.
Member Data Documentation
abortFunction
std::function<void (void)> PartDesignGui::TaskDlgFeaturePick::abortFunction protected
Definition at line 161 of file TaskFeaturePick.h.
Referenced by TaskDlgFeaturePick(), and ~TaskDlgFeaturePick().
accepted
bool PartDesignGui::TaskDlgFeaturePick::accepted protected
Definition at line 158 of file TaskFeaturePick.h.
Referenced by accept(), reject(), and ~TaskDlgFeaturePick().
acceptFunction
std::function<bool (std::vector<App::DocumentObject*>)> PartDesignGui::TaskDlgFeaturePick::acceptFunction protected
Definition at line 159 of file TaskFeaturePick.h.
Referenced by accept(), and TaskDlgFeaturePick().
pick
TaskFeaturePick* PartDesignGui::TaskDlgFeaturePick::pick protected
Definition at line 157 of file TaskFeaturePick.h.
Referenced by accept(), showExternal(), TaskDlgFeaturePick(), and ~TaskDlgFeaturePick().
workFunction
std::function<void (std::vector<App::DocumentObject*>)> PartDesignGui::TaskDlgFeaturePick::workFunction protected
Definition at line 160 of file TaskFeaturePick.h.
Referenced by TaskDlgFeaturePick(), and ~TaskDlgFeaturePick().
The documentation for this class was generated from the following files:
TaskFeaturePick.h
TaskFeaturePick.cpp