FreeCAD: Drawing Namespace Reference
Drawing Namespace Reference
Classes
class DrawingOutput
class DXFOutput
class FeatureClip
class FeaturePage
class FeatureProjection
class FeatureView
class FeatureViewAnnotation
class FeatureViewPart
class FeatureViewSpreadsheet
class FeatureViewSymbol
class Module
class PageGroup
class ProjectionAlgos
class SVGOutput
Typedefs
using FeatureViewPython = App::FeaturePythonT< FeatureView >
using FeatureViewAnnotationPython = App::FeaturePythonT< FeatureViewAnnotation >
using FeatureViewPartPython = App::FeaturePythonT< FeatureViewPart >
using FeatureViewSymbolPython = App::FeaturePythonT< FeatureViewSymbol >
Functions
PyObject * initModule ()
template<typename OutputIt >
void copy (Py::Dict sourceRange, OutputIt targetIt)
Typedef Documentation
FeatureViewAnnotationPython
using Drawing::FeatureViewAnnotationPython = typedef App::FeaturePythonT<FeatureViewAnnotation>
Definition at line 84 of file FeatureViewAnnotation.h.
FeatureViewPartPython
using Drawing::FeatureViewPartPython = typedef App::FeaturePythonT<FeatureViewPart>
Definition at line 92 of file FeatureViewPart.h.
FeatureViewPython
using Drawing::FeatureViewPython = typedef App::FeaturePythonT<FeatureView>
Definition at line 85 of file FeatureView.h.
FeatureViewSymbolPython
using Drawing::FeatureViewSymbolPython = typedef App::FeaturePythonT<FeatureViewSymbol>
Definition at line 86 of file FeatureViewSymbol.h.
Function Documentation
copy()
template<typename OutputIt > void Drawing::copy (Py::Dict sourceRange, OutputIt targetIt)
Copies a Python dictionary of Python strings to a C++ container.
After the function call, the key-value pairs of the Python dictionary are copied into the target buffer as C++ pairs (pair<string, string>).
Parameters
sourceRange is a Python dictionary (Py::Dict). Both, the keys and the values must be Python strings.
targetIt refers to where the data should be inserted. Must be of concept output iterator.
Definition at line 58 of file AppDrawingPy.cpp.
References copy(), and src.Mod.Test.testmakeWireString::String.
Referenced by SpreadsheetGui::SheetTableView::_copySelection(), Sketcher::SketchObject::addGeometry(), Sketcher::SketchObject::carbonCopy(), Gui::PythonConsole::contextMenuEvent(), Gui::DockWnd::ReportOutput::contextMenuEvent(), copy(), Part::Feature::getSubObject(), App::Document::importLinks(), Spreadsheet::PropertySheet::insertColumns(), Spreadsheet::PropertySheet::insertRows(), Sketcher::SketchObject::moveDatumsToEnd(), MRichTextEdit::MRichTextEdit(), SpreadsheetGui::SheetTableView::pasteClipboard(), prepareProfileBased(), Gui::Dialog::DlgEditFileIncludePropertyExternal::processFile(), PYBIND11_MODULE(), Spreadsheet::PropertySheet::removeColumns(), and Spreadsheet::PropertySheet::removeRows().
initModule()
PyObject * Drawing::initModule ()
Definition at line 379 of file AppDrawingPy.cpp.
References Base::InterpreterSingleton::addModule(), and Base::Interpreter().
Referenced by PyMOD_INIT_FUNC().