FreeCAD: Wm4::Eigen< Real > Class Template Reference
Wm4::Eigen< Real > Class Template Reference
#include <Wm4Eigen.h>
Public Member Functions
Eigen (int iSize)
Eigen (const Matrix2< Real > &rkM)
Eigen (const Matrix3< Real > &rkM)
Eigen (const GMatrix< Real > &rkM)
~Eigen ()
Real & operator() (int iRow, int iCol)
Eigen & operator= (const Matrix2< Real > &rkM)
Eigen & operator= (const Matrix3< Real > &rkM)
Eigen & operator= (const GMatrix< Real > &rkM)
Real GetEigenvalue (int i) const
const Real * GetEigenvalues () const
void GetEigenvector (int i, Vector2< Real > &rkV) const
void GetEigenvector (int i, Vector3< Real > &rkV) const
GVector< Real > GetEigenvector (int i) const
const GMatrix< Real > & GetEigenvectors () const
void EigenStuff2 ()
void EigenStuff3 ()
void EigenStuffN ()
void EigenStuff ()
void DecrSortEigenStuff2 ()
void DecrSortEigenStuff3 ()
void DecrSortEigenStuffN ()
void DecrSortEigenStuff ()
void IncrSortEigenStuff2 ()
void IncrSortEigenStuff3 ()
void IncrSortEigenStuffN ()
void IncrSortEigenStuff ()
Detailed Description
template<class Real>
class Wm4::Eigen< Real >
Definition at line 30 of file Wm4Eigen.h.
Constructor & Destructor Documentation
Eigen() [1/4]
template<class Real > Wm4::Eigen< Real >::Eigen (int iSize)
Definition at line 24 of file Wm4Eigen.cpp.
References WM4_NEW.
Eigen() [2/4]
template<class Real > Wm4::Eigen< Real >::Eigen (const Matrix2< Real > & rkM)
Definition at line 36 of file Wm4Eigen.cpp.
References WM4_NEW.
Eigen() [3/4]
template<class Real > Wm4::Eigen< Real >::Eigen (const Matrix3< Real > & rkM)
Definition at line 47 of file Wm4Eigen.cpp.
References WM4_NEW.
Eigen() [4/4]
template<class Real > Wm4::Eigen< Real >::Eigen (const GMatrix< Real > & rkM)
Definition at line 58 of file Wm4Eigen.cpp.
References Wm4::GMatrix< Real >::GetColumns(), Wm4::GMatrix< Real >::GetRows(), and WM4_NEW.
~Eigen()
template<class Real > Wm4::Eigen< Real >::~Eigen
Definition at line 70 of file Wm4Eigen.cpp.
References WM4_DELETE.
Member Function Documentation
DecrSortEigenStuff()
template<class Real > void Wm4::Eigen< Real >::DecrSortEigenStuff
Definition at line 589 of file Wm4Eigen.cpp.
DecrSortEigenStuff2()
template<class Real > void Wm4::Eigen< Real >::DecrSortEigenStuff2
Definition at line 562 of file Wm4Eigen.cpp.
DecrSortEigenStuff3()
template<class Real > void Wm4::Eigen< Real >::DecrSortEigenStuff3
Definition at line 571 of file Wm4Eigen.cpp.
Referenced by Wm4::OrthogonalLineFit3(), and Wm4::OrthogonalPlaneFit3().
DecrSortEigenStuffN()
template<class Real > void Wm4::Eigen< Real >::DecrSortEigenStuffN
Definition at line 580 of file Wm4Eigen.cpp.
EigenStuff()
template<class Real > void Wm4::Eigen< Real >::EigenStuff
Definition at line 549 of file Wm4Eigen.cpp.
EigenStuff2()
template<class Real > void Wm4::Eigen< Real >::EigenStuff2
Definition at line 525 of file Wm4Eigen.cpp.
EigenStuff3()
template<class Real > void Wm4::Eigen< Real >::EigenStuff3
Definition at line 533 of file Wm4Eigen.cpp.
EigenStuffN()
template<class Real > void Wm4::Eigen< Real >::EigenStuffN
Definition at line 541 of file Wm4Eigen.cpp.
GetEigenvalue()
template<class Real > Real Wm4::Eigen< Real >::GetEigenvalue (int i) const
Definition at line 114 of file Wm4Eigen.cpp.
References SplineSurface::i.
Referenced by Wm4::GaussPointsFit2(), Wm4::GaussPointsFit3(), Wm4::QuadraticFit3(), and Wm4::QuadraticSphereFit3().
GetEigenvalues()
template<class Real > const Real * Wm4::Eigen< Real >::GetEigenvalues
Definition at line 120 of file Wm4Eigen.cpp.
GetEigenvector() [1/3]
template<class Real > GVector< Real > Wm4::Eigen< Real >::GetEigenvector (int i) const
Definition at line 160 of file Wm4Eigen.cpp.
References SplineSurface::i.
GetEigenvector() [2/3]
template<class Real > void Wm4::Eigen< Real >::GetEigenvector (int i, Vector2< Real > & rkV) const
Definition at line 126 of file Wm4Eigen.cpp.
References SplineSurface::i.
Referenced by Wm4::GaussPointsFit2(), Wm4::GaussPointsFit3(), Wm4::OrthogonalLineFit3(), Wm4::OrthogonalPlaneFit3(), Wm4::QuadraticFit3(), and Wm4::QuadraticSphereFit3().
GetEigenvector() [3/3]
template<class Real > void Wm4::Eigen< Real >::GetEigenvector (int i, Vector3< Real > & rkV) const
Definition at line 143 of file Wm4Eigen.cpp.
References SplineSurface::i.
GetEigenvectors()
template<class Real > const GMatrix< Real > & Wm4::Eigen< Real >::GetEigenvectors
Definition at line 166 of file Wm4Eigen.cpp.
IncrSortEigenStuff()
template<class Real > void Wm4::Eigen< Real >::IncrSortEigenStuff
Definition at line 630 of file Wm4Eigen.cpp.
IncrSortEigenStuff2()
template<class Real > void Wm4::Eigen< Real >::IncrSortEigenStuff2
Definition at line 603 of file Wm4Eigen.cpp.
Referenced by Wm4::GaussPointsFit2().
IncrSortEigenStuff3()
template<class Real > void Wm4::Eigen< Real >::IncrSortEigenStuff3
Definition at line 612 of file Wm4Eigen.cpp.
Referenced by Wm4::GaussPointsFit3().
IncrSortEigenStuffN()
template<class Real > void Wm4::Eigen< Real >::IncrSortEigenStuffN
Definition at line 621 of file Wm4Eigen.cpp.
Referenced by Wm4::QuadraticFit3(), and Wm4::QuadraticSphereFit3().
operator()()
template<class Real > Real & Wm4::Eigen< Real >::operator() (int iRow, int iCol)
Definition at line 77 of file Wm4Eigen.cpp.
operator=() [1/3]
template<class Real > Eigen< Real > & Wm4::Eigen< Real >::operator= (const GMatrix< Real > & rkM)
Definition at line 107 of file Wm4Eigen.cpp.
operator=() [2/3]
template<class Real > Eigen< Real > & Wm4::Eigen< Real >::operator= (const Matrix2< Real > & rkM)
Definition at line 83 of file Wm4Eigen.cpp.
References WM4_DELETE, and WM4_NEW.
operator=() [3/3]
template<class Real > Eigen< Real > & Wm4::Eigen< Real >::operator= (const Matrix3< Real > & rkM)
Definition at line 95 of file Wm4Eigen.cpp.
References WM4_DELETE, and WM4_NEW.
The documentation for this class was generated from the following files:
Wm4Eigen.h
Wm4Eigen.cpp