FreeCAD: importers.importDAE Namespace Reference
importers.importDAE Namespace Reference
Functions
bool check_collada_import ()
def triangulate (shape)
def open (filename)
def insert (filename, docname)
def read (filename)
def export (list[FreeCAD.DocumentObject] exports, str filename, int tessellation=1, Optional[dict[str, tuple]] colors=None)
Variables
bool DEBUG = True
Function Documentation
check_collada_import()
bool importers.importDAE.check_collada_import ()
Return True if the `collada` module is available.
Also imports the module.
Definition at line 54 of file importDAE.py.
Referenced by importers.importDAE.export(), importers.importDAE.insert(), and importers.importDAE.open().
export()
def importers.importDAE.export (list[FreeCAD.DocumentObject] exports, str filename, int tessellation = 1, Optional[dict[str, tuple]] colors = None)
Export FreeCAD contents to a DAE file.
Parameters
----------
- tessellation is used when breaking curved surfaces into triangles.
- colors is an optional dictionary of {objName: shapeColorTuple} or
         {objName: diffuseColorList} elements to be used in non-GUI
         mode if you want to be able to export colors.
Definition at line 173 of file importDAE.py.
References importers.importDAE.check_collada_import(), and importers.importDAE.triangulate().
insert()
def importers.importDAE.insert (filename, docname)
Called when FreeCAD wants to import a file.
Definition at line 111 of file importDAE.py.
References importers.importDAE.check_collada_import(), and importers.importDAE.read().
open()
def importers.importDAE.open (filename)
Called when FreeCAD wants to open a file.
Definition at line 98 of file importDAE.py.
References importers.importDAE.check_collada_import(), and importers.importDAE.read().
read()
def importers.importDAE.read (filename)
Read a DAE file.
Definition at line 125 of file importDAE.py.
References Path.Post.scripts.refactored_centroid_post.str.
Referenced by importers.importDAE.insert(), and importers.importDAE.open().
triangulate()
def importers.importDAE.triangulate (shape)
Triangulate the given shape.
Definition at line 71 of file importDAE.py.
Referenced by importers.importDAE.export(), and Reen::Module.Module().
Variable Documentation
DEBUG
bool importers.importDAE.DEBUG = True
Definition at line 51 of file importDAE.py.