FreeCAD: Part::FaceMakerCheese Class Reference
Part::FaceMakerCheese Class Reference
The FaceMakerCheese class is a legacy face maker that was extracted from Part Extrude. It is used by almost all PartDesign.
#include <FaceMakerCheese.h>
Classes
class Wire_Compare
The Wire_Compare class is for sorting wires by bounding box diagonal length.
Public Member Functions
std::string getUserFriendlyName () const override
std::string getBriefExplanation () const override
Public Member Functions inherited from Part::FaceMaker
FaceMaker ()
~FaceMaker () override
void addTopoShape (const TopoShape &s)
void useTopoCompound (const TopoShape &comp)
const TopoShape & getTopoShape () const
const TopoShape & TopoFace () const
virtual void addWire (const TopoDS_Wire &w)
virtual void addShape (const TopoDS_Shape &sh)
addShape: add another wire, edge, or compound. If compound is added, its internals will be treated as isolated from the rest, and the compounding structure of result will follow.
virtual void useCompound (const TopoDS_Compound &comp)
useCompound: add children of compound to the FaceMaker. Note that this is different from addShape(comp) - structure is lost. The compound is NOT expanded recursively.
virtual void setPlane (const gp_Pln &)
virtual const TopoDS_Face & Face ()
Face: returns the face (result). If result is not a single face, throws Base::TypeError. (hint: use .Shape() instead)
void Build () override
Public Member Functions inherited from Base::BaseClass
virtual Type getTypeId () const
bool isDerivedFrom (const Type type) const
virtual PyObject * getPyObject ()
virtual void setPyObject (PyObject *)
template<typename T >
bool is () const
template<typename T >
bool isDerivedFrom () const
BaseClass ()
Construction.
BaseClass (const BaseClass &)=default
BaseClass & operator= (const BaseClass &)=default
BaseClass (BaseClass &&)=default
BaseClass & operator= (BaseClass &&)=default
virtual ~BaseClass ()
Destruction.
Static Public Member Functions
static TopoDS_Shape makeFace (const std::vector< TopoDS_Wire > &)
static TopoDS_Face validateFace (const TopoDS_Face &)
static bool isInside (const TopoDS_Wire &, const TopoDS_Wire &)
Static Public Member Functions inherited from Part::FaceMaker
static std::unique_ptr< FaceMaker > ConstructFromType (const char *className)
static std::unique_ptr< FaceMaker > ConstructFromType (Base::Type type)
Static Public Member Functions inherited from Base::BaseClass
static Type getClassTypeId ()
static void init ()
static void * create ()
Protected Member Functions
void Build_Essence () override
Build_Essence: build routine that can assume there is no nesting.
Protected Member Functions inherited from Part::FaceMaker
void postBuild ()
Additional Inherited Members
Public Attributes inherited from Part::FaceMaker
const char * MyOp = 0
App::StringHasherRef MyHasher
Static Protected Member Functions inherited from Part::FaceMaker
static void throwNotImplemented ()
Static Protected Member Functions inherited from Base::BaseClass
static void initSubclass (Base::Type &toInit, const char *ClassName, const char *ParentName, Type::instantiationMethod method=nullptr)
Protected Attributes inherited from Part::FaceMaker
std::vector< TopoShape > mySourceShapes
std::vector< TopoDS_Wire > myWires
std::vector< TopoShape > myTopoWires
std::vector< TopoDS_Compound > myCompounds
std::vector< TopoDS_Shape > myShapesToReturn
std::vector< TopoDS_Shape > myInputFaces
TopoShape myTopoShape
int minElementNames = 1
Detailed Description
The FaceMakerCheese class is a legacy face maker that was extracted from Part Extrude. It is used by almost all PartDesign.
Strengths: makes faces with holes
Weaknesses: can't make islands in holes. All faces must be on same plane.
Definition at line 61 of file FaceMakerCheese.h.
Member Function Documentation
Build_Essence()
void FaceMakerCheese::Build_Essence () override protected virtual
Build_Essence: build routine that can assume there is no nesting.
Implementing instructions: Add new faces (or whatever) to myShapesToReturn. The rest is done by base class's Build(). Please ignore contents of myCompounds in implementation. If special handling of nesting is required, override whole Build().
Implements Part::FaceMaker.
Reimplemented in Part::FaceMakerExtrusion.
Definition at line 255 of file FaceMakerCheese.cpp.
References Handle(), SplineSurface::i, makeFace(), Part::FaceMaker::myShapesToReturn, and Part::FaceMaker::myWires.
getBriefExplanation()
std::string FaceMakerCheese::getBriefExplanation () const override virtual
Implements Part::FaceMakerPublic.
Reimplemented in Part::FaceMakerExtrusion.
Definition at line 250 of file FaceMakerCheese.cpp.
getUserFriendlyName()
std::string FaceMakerCheese::getUserFriendlyName () const override virtual
Implements Part::FaceMakerPublic.
Reimplemented in Part::FaceMakerExtrusion.
Definition at line 245 of file FaceMakerCheese.cpp.
isInside()
bool FaceMakerCheese::isInside (const TopoDS_Wire & wire1, const TopoDS_Wire & wire2) static
Definition at line 116 of file FaceMakerCheese.cpp.
References KDL::Add(), Handle(), buildPsets::p, TestSpreadsheet::v, and validateFace().
Referenced by makeFace().
makeFace()
TopoDS_Shape FaceMakerCheese::makeFace (const std::vector< TopoDS_Wire > & w) static
Definition at line 189 of file FaceMakerCheese.cpp.
References isInside(), Path.Post.scripts.opensbp_post::move(), and src.Mod.PartDesign.fcgear.svggear::w.
Referenced by ReverseEngineeringGui::Segmentation::accept(), Part::FaceMakerExtrusion::Build(), Build_Essence(), PartDesign::Pipe::execute(), and TechDraw::GeometryUtils::makePerforatedFace().
validateFace()
TopoDS_Face FaceMakerCheese::validateFace (const TopoDS_Face & face) static
Definition at line 56 of file FaceMakerCheese.cpp.
Referenced by isInside().
The documentation for this class was generated from the following files:
FaceMakerCheese.h
FaceMakerCheese.cpp