FreeCAD: Path.Base.Gui.PropertyBag Namespace Reference
Path.Base.Gui.PropertyBag Namespace Reference
Classes
class Delegate
class PropertyBagCreateCommand
class PropertyCreate
class TaskPanel
class ViewProvider
Functions
def Create (name="PropertyBag")
Variables
translate
Function Documentation
Create()
def Path.Base.Gui.PropertyBag.Create (name = "PropertyBag")
Create(name = 'PropertyBag') ... creates a new setup sheet
Definition at line 398 of file Gui/PropertyBag.py.
Referenced by Path.Base.Gui.PropertyBag.PropertyBagCreateCommand.Activated(), StdViewBoxZoom.activated(), StdBoxSelection.activated(), StdBoxElementSelection.activated(), Wm4::MeshSmoother< Real >.MeshSmoother(), and Path.Tool.Gui.BitLibrary.ToolBitLibrary.toolBitNew().
Variable Documentation
translate
Path.Base.Gui.PropertyBag.translate
Definition at line 45 of file Gui/PropertyBag.py.