FreeCAD: BOPTools.JoinFeatures.FeatureEmbed Class Reference
BOPTools.JoinFeatures.FeatureEmbed Class Reference
Public Member Functions
def __init__ (self, obj)
def execute (self, selfobj)
Public Attributes
Type
Detailed Description
The Part Embed object.
Definition at line 223 of file BOPTools/JoinFeatures.py.
Constructor & Destructor Documentation
__init__()
def BOPTools.JoinFeatures.FeatureEmbed.__init__ (self, obj)
Definition at line 226 of file BOPTools/JoinFeatures.py.
References BOPTools.JoinFeatures.getParamRefine().
Member Function Documentation
execute()
def BOPTools.JoinFeatures.FeatureEmbed.execute (self, selfobj)
Definition at line 239 of file BOPTools/JoinFeatures.py.
Referenced by src.Mod.PartDesign.Scripts.Spring.MySpring.onChanged(), src.Mod.PartDesign.Scripts.Epitrochoid.Epitrochoid.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.Parallelepiped.onChanged(), src.Mod.PartDesign.Scripts.DistanceBolt.DistanceBolt.onChanged(), src.Mod.PartDesign.Scripts.Parallelepiped.BoxCylinder.onChanged(), and FeaturePython.DistanceBolt.onChanged().
Member Data Documentation
Type
BOPTools.JoinFeatures.FeatureEmbed.Type
Definition at line 237 of file BOPTools/JoinFeatures.py.
The documentation for this class was generated from the following file:
BOPTools/JoinFeatures.py