FreeCAD: TechDrawGui::TaskCosVertex Class Reference
TechDrawGui::TaskCosVertex Class Reference
#include <TaskCosVertex.h>
Public Slots
void onTrackerClicked (bool clicked)
void onTrackerFinished (std::vector< QPointF > pts, TechDrawGui::QGIView *qgParent)
Public Member Functions
TaskCosVertex (TechDraw::DrawViewPart *baseFeat, TechDraw::DrawPage *page)
~TaskCosVertex () override=default
virtual bool accept ()
virtual bool reject ()
void updateTask ()
void saveButtons (QPushButton *btnOK, QPushButton *btnCancel)
void enableTaskButtons (bool button)
Protected Member Functions
void changeEvent (QEvent *event) override
void startTracker ()
void removeTracker ()
void abandonEditSession ()
void addCosVertex (QPointF qPos)
create the cv as entered, addCosmeticVertex will invert it
void setUiPrimary ()
void updateUi ()
void setEditCursor (QCursor cursor)
QGIView * findParentQGIV ()
Detailed Description
Definition at line 54 of file TaskCosVertex.h.
Constructor & Destructor Documentation
TaskCosVertex()
TaskCosVertex::TaskCosVertex (TechDraw::DrawViewPart * baseFeat, TechDraw::DrawPage * page)
Definition at line 59 of file TaskCosVertex.cpp.
References draftgeoutils.intersections::connect(), App::DocumentObject::getDocument(), Gui::Application::getDocument(), Gui::Document::getViewProvider(), Gui::Application::Instance, onTrackerClicked(), and setUiPrimary().
~TaskCosVertex()
TechDrawGui::TaskCosVertex::~TaskCosVertex () override default
Member Function Documentation
abandonEditSession()
void TaskCosVertex::abandonEditSession () protected
Definition at line 274 of file TaskCosVertex.cpp.
References Gui::getMainWindow(), Path.Op.Surface::msg, setEditCursor(), and Gui::MainWindow::showMessage().
accept()
bool TaskCosVertex::accept () virtual
Definition at line 299 of file TaskCosVertex.cpp.
References addCosVertex(), toolbit-attributes::doc, doCommand, App::DocumentObject::getDocument(), Gui::Application::getDocument(), TechDrawGui::ViewProviderPage::getMDIViewPage(), Gui::Command::Gui, Gui::Application::Instance, Gui::None, App::DocumentObject::recomputeFeature(), removeTracker(), TechDraw::DrawView::requestPaint(), MovieTool::x, and MovieTool::y.
Referenced by TechDrawGui::TaskDlgCosVertex::accept().
addCosVertex()
void TaskCosVertex::addCosVertex (QPointF qPos) protected
create the cv as entered, addCosmeticVertex will invert it
Definition at line 135 of file TaskCosVertex.cpp.
References TechDraw::CosmeticExtension::addCosmeticVertex(), Gui::Command::commitCommand(), Gui::Command::openCommand(), Arch::QT_TRANSLATE_NOOP, TechDraw::DrawView::requestPaint(), and TechDraw::DrawUtil::toVector3d().
Referenced by accept().
changeEvent()
void TaskCosVertex::changeEvent (QEvent * event) override protected
Definition at line 98 of file TaskCosVertex.cpp.
enableTaskButtons()
void TaskCosVertex::enableTaskButtons (bool button)
Definition at line 292 of file TaskCosVertex.cpp.
Referenced by onTrackerClicked(), and onTrackerFinished().
findParentQGIV()
QGIView* TechDrawGui::TaskCosVertex::findParentQGIV () protected
onTrackerClicked
void TaskCosVertex::onTrackerClicked (bool clicked) slot
Definition at line 149 of file TaskCosVertex.cpp.
References TechDrawGui::CANCEL, enableTaskButtons(), Gui::getMainWindow(), TechDrawGui::ViewProviderPage::getMDIViewPage(), Path.Op.Surface::msg, TechDrawGui::PICK, removeTracker(), setEditCursor(), Gui::MainWindow::showMessage(), and startTracker().
Referenced by TaskCosVertex().
onTrackerFinished
void TaskCosVertex::onTrackerFinished (std::vector< QPointF > pts, TechDrawGui::QGIView * qgParent) slot
Definition at line 206 of file TaskCosVertex.cpp.
References TechDrawGui::Rez::appX(), Base::Console(), enableTaskButtons(), Base::ConsoleSingleton::Error(), TechDrawGui::ViewProviderPage::getMDIViewPage(), TechDraw::DrawProjGroupItem::getPGroup(), App::PropertyQuantity::getValue(), TechDrawGui::Rez::guiX(), TechDrawGui::PICK, setEditCursor(), TechDrawGui::QGTracker::sleep(), TechDraw::DrawUtil::toQPointF(), TechDraw::DrawUtil::toVector3d(), updateUi(), MovieTool::x, TechDraw::DrawView::X, MovieTool::y, and TechDraw::DrawView::Y.
Referenced by startTracker().
reject()
bool TaskCosVertex::reject () virtual
Definition at line 323 of file TaskCosVertex.cpp.
References toolbit-attributes::doc, doCommand, App::DocumentObject::getDocument(), Gui::Application::getDocument(), TechDrawGui::ViewProviderPage::getMDIViewPage(), Gui::Command::Gui, Gui::Application::Instance, Gui::None, and removeTracker().
Referenced by drafttaskpanels.task_shapestring.ShapeStringTaskPanel::action(), and TechDrawGui::TaskDlgCosVertex::reject().
removeTracker()
void TaskCosVertex::removeTracker () protected
Definition at line 256 of file TaskCosVertex.cpp.
References TechDrawGui::ViewProviderPage::getQGSPage().
Referenced by accept(), onTrackerClicked(), and reject().
saveButtons()
void TaskCosVertex::saveButtons (QPushButton * btnOK, QPushButton * btnCancel)
Definition at line 285 of file TaskCosVertex.cpp.
Referenced by TechDrawGui::TaskDlgCosVertex::modifyStandardButtons().
setEditCursor()
void TaskCosVertex::setEditCursor (QCursor cursor) protected
Definition at line 266 of file TaskCosVertex.cpp.
References TechDrawGui::QGSPage::findQViewForDocObj(), and TechDrawGui::ViewProviderPage::getQGSPage().
Referenced by abandonEditSession(), onTrackerClicked(), onTrackerFinished(), and startTracker().
setUiPrimary()
void TaskCosVertex::setUiPrimary () protected
Definition at line 105 of file TaskCosVertex.cpp.
References Base::UnitsApi::getDecimals(), App::DocumentObject::getNameInDocument(), and Base::Unit::Length.
Referenced by TaskCosVertex().
startTracker()
void TaskCosVertex::startTracker () protected
Definition at line 182 of file TaskCosVertex.cpp.
References draftgeoutils.intersections::connect(), TechDrawGui::QGTracker::drawingFinished(), Gui::getMainWindow(), TechDrawGui::ViewProviderPage::getQGSPage(), Path.Op.Surface::msg, Gui::None, onTrackerFinished(), setEditCursor(), and Gui::MainWindow::showMessage().
Referenced by onTrackerClicked().
updateTask()
void TaskCosVertex::updateTask ()
Definition at line 91 of file TaskCosVertex.cpp.
updateUi()
void TaskCosVertex::updateUi () protected
Definition at line 126 of file TaskCosVertex.cpp.
References MovieTool::x, and MovieTool::y.
Referenced by onTrackerFinished().
The documentation for this class was generated from the following files:
TaskCosVertex.h
TaskCosVertex.cpp