FreeCAD: TechDrawGui::CompassWidget Class Reference
TechDrawGui::CompassWidget Class Reference
#include <CompassWidget.h>
Public Slots
void slotChangeAngle (double angle)
void slotSpinBoxEnter (double newAngle)
void resetAngle ()
void setToEast ()
void setToNorth ()
void setToWest ()
void setToSouth ()
void slotCWAdvance ()
void slotCCWAdvance ()
Signals
void angleChanged (double angle)
void angleSet (double angle)
Public Member Functions
CompassWidget (QWidget *parent=nullptr)
~CompassWidget () override=default
QSize sizeHint () const override
QSize minimumSizeHint () const override
bool eventFilter (QObject *target, QEvent *event) override
void retranslateUi ()
double dialAngle () const
double value () const
double positiveValue ()
void setDialAngle (double newAngle)
void setAdvanceIncrement (double newIncrement)
double advanceIncrement () const
Protected Member Functions
void paintEvent (QPaintEvent *event) override
void buildWidget ()
double changeAngleConvention (double CWY) const
Properties
double angle
Detailed Description
Definition at line 43 of file CompassWidget.h.
Constructor & Destructor Documentation
CompassWidget()
CompassWidget::CompassWidget (QWidget * parent = nullptr)
Definition at line 48 of file CompassWidget.cpp.
References buildWidget(), draftgeoutils.intersections::connect(), TechDrawGui::CompassDialWidget::setSize(), slotCCWAdvance(), and slotCWAdvance().
~CompassWidget()
TechDrawGui::CompassWidget::~CompassWidget () override default
Member Function Documentation
advanceIncrement()
double TechDrawGui::CompassWidget::advanceIncrement () const inline
Definition at line 61 of file CompassWidget.h.
angleChanged
void TechDrawGui::CompassWidget::angleChanged (double angle) signal
Referenced by TechDrawGui::TaskSectionView::setUiCommon(), TechDrawGui::TaskComplexSection::setUiCommon(), slotCCWAdvance(), slotCWAdvance(), and slotSpinBoxEnter().
angleSet
void TechDrawGui::CompassWidget::angleSet (double angle) signal
buildWidget()
void CompassWidget::buildWidget () protected
Definition at line 84 of file CompassWidget.cpp.
References geoff_geometry::Normal(), geoff_geometry::On(), and retranslateUi().
Referenced by CompassWidget().
changeAngleConvention()
double TechDrawGui::CompassWidget::changeAngleConvention (double CWY) const protected
dialAngle()
double TechDrawGui::CompassWidget::dialAngle () const inline
Definition at line 56 of file CompassWidget.h.
eventFilter()
bool CompassWidget::eventFilter (QObject * target, QEvent * event) override
Definition at line 64 of file CompassWidget.cpp.
References slotSpinBoxEnter().
minimumSizeHint()
QSize CompassWidget::minimumSizeHint () const override
Definition at line 171 of file CompassWidget.cpp.
paintEvent()
void CompassWidget::paintEvent (QPaintEvent * event) override protected
Definition at line 176 of file CompassWidget.cpp.
positiveValue()
double TechDrawGui::CompassWidget::positiveValue () inline
Definition at line 58 of file CompassWidget.h.
Referenced by TechDrawGui::TaskSectionView::createSectionView(), and TechDrawGui::TaskSectionView::updateSectionView().
resetAngle
void TechDrawGui::CompassWidget::resetAngle () inline slot
Definition at line 70 of file CompassWidget.h.
References setDialAngle().
retranslateUi()
void CompassWidget::retranslateUi ()
Definition at line 155 of file CompassWidget.cpp.
References src.Mod.AddonManager.Addon::translate.
Referenced by buildWidget().
setAdvanceIncrement()
void CompassWidget::setAdvanceIncrement (double newIncrement)
Definition at line 231 of file CompassWidget.cpp.
setDialAngle()
void CompassWidget::setDialAngle (double newAngle)
Definition at line 183 of file CompassWidget.cpp.
References TechDrawGui::CompassDialWidget::setAngle().
Referenced by resetAngle(), setToEast(), setToNorth(), setToSouth(), setToWest(), TechDrawGui::TaskSectionView::setUiEdit(), TechDrawGui::TaskComplexSection::setUiEdit(), TechDrawGui::TaskSectionView::setUiPrimary(), TechDrawGui::TaskComplexSection::setUiPrimary(), slotCCWAdvance(), slotChangeAngle(), slotCWAdvance(), TechDrawGui::TaskSectionView::slotViewDirectionChanged(), and TechDrawGui::TaskComplexSection::slotViewDirectionChanged().
setToEast
void TechDrawGui::CompassWidget::setToEast () inline slot
Definition at line 71 of file CompassWidget.h.
References setDialAngle().
Referenced by TechDrawGui::TaskSectionView::onRightClicked(), and TechDrawGui::TaskComplexSection::onRightClicked().
setToNorth
void TechDrawGui::CompassWidget::setToNorth () inline slot
Definition at line 72 of file CompassWidget.h.
References setDialAngle().
Referenced by TechDrawGui::TaskSectionView::onUpClicked(), and TechDrawGui::TaskComplexSection::onUpClicked().
setToSouth
void TechDrawGui::CompassWidget::setToSouth () inline slot
Definition at line 74 of file CompassWidget.h.
References setDialAngle().
Referenced by TechDrawGui::TaskSectionView::onDownClicked(), and TechDrawGui::TaskComplexSection::onDownClicked().
setToWest
void TechDrawGui::CompassWidget::setToWest () inline slot
Definition at line 73 of file CompassWidget.h.
References setDialAngle().
Referenced by TechDrawGui::TaskSectionView::onLeftClicked(), and TechDrawGui::TaskComplexSection::onLeftClicked().
sizeHint()
QSize CompassWidget::sizeHint () const override
Definition at line 169 of file CompassWidget.cpp.
slotCCWAdvance
void CompassWidget::slotCCWAdvance () slot
Definition at line 218 of file CompassWidget.cpp.
References angle, angleChanged(), and setDialAngle().
Referenced by CompassWidget().
slotChangeAngle
void TechDrawGui::CompassWidget::slotChangeAngle (double angle) inline slot
Definition at line 68 of file CompassWidget.h.
References angle, and setDialAngle().
slotCWAdvance
void CompassWidget::slotCWAdvance () slot
Definition at line 208 of file CompassWidget.cpp.
References angle, angleChanged(), and setDialAngle().
Referenced by CompassWidget().
slotSpinBoxEnter
void CompassWidget::slotSpinBoxEnter (double newAngle) slot
Definition at line 196 of file CompassWidget.cpp.
References angleChanged(), and TechDrawGui::CompassDialWidget::setAngle().
Referenced by eventFilter().
value()
double TechDrawGui::CompassWidget::value () const inline
Definition at line 57 of file CompassWidget.h.
Property Documentation
angle
double TechDrawGui::CompassWidget::angle read write
Definition at line 46 of file CompassWidget.h.
Referenced by Path.Dressup.Gui.Dogbone.Bone::adaptiveLength(), Path.Dressup.Gui.Dogbone.Bone::corner(), Path.Dressup.Gui.Dogbone.Bone::distance(), Path.Base.Generator.dogboneII.Generator::generate(), slotCCWAdvance(), slotChangeAngle(), and slotCWAdvance().
The documentation for this class was generated from the following files:
CompassWidget.h
CompassWidget.cpp