FreeCAD: Gui::SoFCSelectionContext Struct Reference
Gui::SoFCSelectionContext Struct Reference
#include <SoFCSelectionContext.h>
Public Member Functions
~SoFCSelectionContext () override
bool isSelected () const
void selectAll ()
bool isSelectAll () const
bool isHighlighted () const
bool isHighlightAll () const
void highlightAll ()
void removeHighlight ()
bool removeIndex (int index)
bool checkGlobal (SoFCSelectionContextPtr ctx)
virtual SoFCSelectionContextBasePtr copy ()
Public Member Functions inherited from Gui::SoFCSelectionContextBase
virtual ~SoFCSelectionContextBase ()=default
Public Attributes
int highlightIndex = -1
std::set< int > selectionIndex
SbColor selectionColor
SbColor highlightColor
std::shared_ptr< int > counter
Static Public Attributes
static MergeFunc merge
Additional Inherited Members
Public Types inherited from Gui::SoFCSelectionContextBase
using MergeFunc = int(int status, SoFCSelectionContextBasePtr &output, SoFCSelectionContextBasePtr input, SoNode *node)
Detailed Description
Definition at line 54 of file SoFCSelectionContext.h.
Constructor & Destructor Documentation
~SoFCSelectionContext()
SoFCSelectionContext::~SoFCSelectionContext () override
Definition at line 39 of file SoFCSelectionContext.cpp.
References counter.
Member Function Documentation
checkGlobal()
bool SoFCSelectionContext::checkGlobal (SoFCSelectionContextPtr ctx)
Definition at line 44 of file SoFCSelectionContext.cpp.
References Gui::SoFCSelectionRoot::checkSelection(), highlightAll(), highlightColor, highlightIndex, removeHighlight(), selectionColor, and selectionIndex.
copy()
virtual SoFCSelectionContextBasePtr Gui::SoFCSelectionContext::copy () inline virtual
Reimplemented in Gui::SoFCSelectionContextEx.
Definition at line 96 of file SoFCSelectionContext.h.
highlightAll()
void Gui::SoFCSelectionContext::highlightAll () inline
Definition at line 85 of file SoFCSelectionContext.h.
Referenced by checkGlobal().
isHighlightAll()
bool Gui::SoFCSelectionContext::isHighlightAll () const inline
Definition at line 81 of file SoFCSelectionContext.h.
isHighlighted()
bool Gui::SoFCSelectionContext::isHighlighted () const inline
Definition at line 77 of file SoFCSelectionContext.h.
isSelectAll()
bool Gui::SoFCSelectionContext::isSelectAll () const inline
Definition at line 73 of file SoFCSelectionContext.h.
isSelected()
bool Gui::SoFCSelectionContext::isSelected () const inline
Definition at line 64 of file SoFCSelectionContext.h.
removeHighlight()
void Gui::SoFCSelectionContext::removeHighlight () inline
Definition at line 89 of file SoFCSelectionContext.h.
Referenced by checkGlobal().
removeIndex()
bool SoFCSelectionContext::removeIndex (int index)
Definition at line 65 of file SoFCSelectionContext.cpp.
References selectionIndex.
selectAll()
void Gui::SoFCSelectionContext::selectAll () inline
Definition at line 68 of file SoFCSelectionContext.h.
Member Data Documentation
counter
std::shared_ptr<int> Gui::SoFCSelectionContext::counter
Definition at line 60 of file SoFCSelectionContext.h.
Referenced by src.Mod.AddonManager.addonmanager_workers_startup.CacheMacroCodeWorker::run(), src.Mod.AddonManager.addonmanager_workers_startup.CacheMacroCodeWorker::update_and_advance(), and ~SoFCSelectionContext().
highlightColor
SbColor Gui::SoFCSelectionContext::highlightColor
Definition at line 59 of file SoFCSelectionContext.h.
Referenced by checkGlobal().
highlightIndex
int Gui::SoFCSelectionContext::highlightIndex = -1
Definition at line 56 of file SoFCSelectionContext.h.
Referenced by checkGlobal().
merge
int SoFCSelectionContext::merge static
Definition at line 100 of file SoFCSelectionContext.h.
selectionColor
SbColor Gui::SoFCSelectionContext::selectionColor
Definition at line 58 of file SoFCSelectionContext.h.
Referenced by checkGlobal().
selectionIndex
std::set<int> Gui::SoFCSelectionContext::selectionIndex
Definition at line 57 of file SoFCSelectionContext.h.
Referenced by checkGlobal(), and removeIndex().
The documentation for this struct was generated from the following files:
SoFCSelectionContext.h
SoFCSelectionContext.cpp