FreeCAD: Gui::PrefQuantitySpinBoxPrivate Class Reference
Gui::PrefQuantitySpinBoxPrivate Class Reference
Public Member Functions
QByteArray getHistoryGroupName (QByteArray name) const
void restoreHistory (ParameterGrp::handle hGrp)
void clearHistory (ParameterGrp::handle hGrp)
void saveHistory (ParameterGrp::handle hGrp)
Public Attributes
HistoryList history
bool isSaving = false
Detailed Description
Definition at line 628 of file PrefWidgets.cpp.
Member Function Documentation
clearHistory()
void Gui::PrefQuantitySpinBoxPrivate::clearHistory (ParameterGrp::handle hGrp) inline
Definition at line 643 of file PrefWidgets.cpp.
References ParameterGrp::GetASCIIs(), and ParameterGrp::RemoveASCII().
Referenced by saveHistory().
getHistoryGroupName()
QByteArray Gui::PrefQuantitySpinBoxPrivate::getHistoryGroupName (QByteArray name) const inline
Definition at line 634 of file PrefWidgets.cpp.
restoreHistory()
void Gui::PrefQuantitySpinBoxPrivate::restoreHistory (ParameterGrp::handle hGrp) inline
Definition at line 638 of file PrefWidgets.cpp.
References Gui::HistoryList::append(), ParameterGrp::GetASCIIs(), and history.
saveHistory()
void Gui::PrefQuantitySpinBoxPrivate::saveHistory (ParameterGrp::handle hGrp) inline
Definition at line 648 of file PrefWidgets.cpp.
References Gui::HistoryList::asStringList(), clearHistory(), history, SplineSurface::i, and ParameterGrp::SetASCII().
Member Data Documentation
history
HistoryList Gui::PrefQuantitySpinBoxPrivate::history
Definition at line 631 of file PrefWidgets.cpp.
Referenced by restoreHistory(), and saveHistory().
isSaving
bool Gui::PrefQuantitySpinBoxPrivate::isSaving = false
Definition at line 632 of file PrefWidgets.cpp.
The documentation for this class was generated from the following file:
PrefWidgets.cpp