FreeCAD: ifc2x3.ifcbuilding Class Reference
ifc2x3.ifcbuilding Class Reference
Public Member Functions
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__objecttype, inherited5__objectplacement, inherited6__representation, inherited7__longname, inherited8__compositiontype, elevationofrefheight, elevationofterrain, buildingaddress)
def elevationofrefheight ()
def elevationofterrain ()
def buildingaddress ()
Public Member Functions inherited from ifc2x3.ifcspatialstructureelement
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__objecttype, inherited5__objectplacement, inherited6__representation, longname, compositiontype)
def longname ()
def compositiontype ()
def referenceselements ()
def servicedbysystems ()
def containselements ()
def wr41 (self)
Public Member Functions inherited from ifc2x3.ifcproduct
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__objecttype, objectplacement, representation)
def objectplacement ()
def representation ()
def referencedby ()
def wr1 (self)
Public Member Functions inherited from ifc2x3.ifcobject
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, objecttype)
def objecttype ()
def isdefinedby ()
Public Member Functions inherited from ifc2x3.ifcobjectdefinition
def __init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description)
def hasassignments ()
def isdecomposedby ()
def decomposes ()
def hasassociations ()
Public Member Functions inherited from ifc2x3.ifcroot
def globalid ()
def ownerhistory ()
def name ()
def description ()
Public Member Functions inherited from SCL.SCLBase.BaseEntityClass
def __repr__ (self)
Public Attributes
elevationofrefheight
elevationofterrain
buildingaddress
Public Attributes inherited from ifc2x3.ifcspatialstructureelement
longname
compositiontype
Public Attributes inherited from ifc2x3.ifcproduct
objectplacement
representation
Public Attributes inherited from ifc2x3.ifcobject
objecttype
Public Attributes inherited from ifc2x3.ifcroot
globalid
ownerhistory
name
description
Detailed Description
Entity ifcbuilding definition.
:param elevationofrefheight
:type elevationofrefheight:ifclengthmeasure
:param elevationofterrain
:type elevationofterrain:ifclengthmeasure
:param buildingaddress
:type buildingaddress:ifcpostaladdress
Definition at line 14168 of file ifc2x3.py.
Constructor & Destructor Documentation
__init__()
def ifc2x3.ifcbuilding.__init__ (self, inherited0__globalid, inherited1__ownerhistory, inherited2__name, inherited3__description, inherited4__objecttype, inherited5__objectplacement, inherited6__representation, inherited7__longname, inherited8__compositiontype, elevationofrefheight, elevationofterrain, buildingaddress)
Definition at line 14180 of file ifc2x3.py.
Member Function Documentation
buildingaddress()
def ifc2x3.ifcbuilding.buildingaddress ()
Definition at line 14215 of file ifc2x3.py.
References ifc2x3.ifcbuilding._buildingaddress, ifc2x3.ifcbuilding.buildingaddress, and SCL.TypeChecker.check_type().
elevationofrefheight()
def ifc2x3.ifcbuilding.elevationofrefheight ()
Definition at line 14187 of file ifc2x3.py.
References ifc2x3.ifcbuilding._elevationofrefheight, SCL.TypeChecker.check_type(), and ifc2x3.ifcbuilding.elevationofrefheight.
elevationofterrain()
def ifc2x3.ifcbuilding.elevationofterrain ()
Definition at line 14201 of file ifc2x3.py.
References ifc2x3.ifcbuilding._elevationofterrain, SCL.TypeChecker.check_type(), and ifc2x3.ifcbuilding.elevationofterrain.
Member Data Documentation
buildingaddress
ifc2x3.ifcbuilding.buildingaddress
Definition at line 14184 of file ifc2x3.py.
Referenced by ifc2x3.ifcbuilding.buildingaddress().
elevationofrefheight
ifc2x3.ifcbuilding.elevationofrefheight
Definition at line 14182 of file ifc2x3.py.
Referenced by ifc2x3.ifcbuilding.elevationofrefheight().
elevationofterrain
ifc2x3.ifcbuilding.elevationofterrain
Definition at line 14183 of file ifc2x3.py.
Referenced by ifc2x3.ifcbuilding.elevationofterrain().
The documentation for this class was generated from the following file:
ifc2x3.py